FreeCAD: TechDrawGui::QGIDimLines Class Reference
TechDrawGui::QGIDimLines Class Reference
#include <QGIDimLines.h>
Public Types
enum { Type = QGraphicsItem::UserType + 175 }
Public Types inherited from TechDrawGui::QGIPrimPath
enum { Type = QGraphicsItem::UserType + 170 }
Public Member Functions
virtual QRectF boundingRect () const override
void draw ()
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0) override
QGIDimLines ()
virtual QPainterPath shape () const override
int type () const override
~QGIDimLines ()
Public Member Functions inherited from TechDrawGui::QGIPrimPath
QColor getFillColor (void)
Qt::BrushStyle getFillStyle ()
Qt::PenStyle getStyle ()
virtual double getWidth ()
QGIPrimPath ()
void resetFill ()
virtual void setCapStyle (Qt::PenCapStyle c)
void setFill (QBrush b)
void setFill (QColor c, Qt::BrushStyle s)
void setFillColor (QColor c)
void setFillOverride (bool b)
void setFillStyle (Qt::BrushStyle f)
void setHighlighted (bool state)
virtual void setNormalColor (QColor c)
virtual void setPrettyNormal ()
virtual void setPrettyPre ()
virtual void setPrettySel ()
void setStyle (int s)
void setStyle (Qt::PenStyle s)
virtual void setWidth (double w)
int type () const override
~QGIPrimPath ()
Protected Member Functions
double getEdgeFuzz (void) const
Protected Member Functions inherited from TechDrawGui::QGIPrimPath
virtual QColor getNormalColor (void)
Base::Reference< ParameterGrp > getParmGroup (void)
virtual QColor getPreColor (void)
virtual QColor getSelectColor (void)
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) override
virtual Qt::PenCapStyle prefCapStyle (void)
Additional Inherited Members
Protected Attributes inherited from TechDrawGui::QGIPrimPath
bool isHighlighted
QBrush m_brush
Qt::PenCapStyle m_capStyle
QColor m_colCurrent
QColor m_colDefFill
QColor m_colNormal
QColor m_colNormalFill
bool m_colOverride
QColor m_fillColorCurrent
bool m_fillOverride
Qt::BrushStyle m_fillStyleCurrent
QPen m_pen
Qt::PenStyle m_styleCurrent
Qt::BrushStyle m_styleDef
Qt::BrushStyle m_styleNormal
Qt::BrushStyle m_styleSelect
double m_width
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGIDimLines()
QGIDimLines::QGIDimLines () explicit
~QGIDimLines()
TechDrawGui::QGIDimLines::~QGIDimLines ()
Member Function Documentation
boundingRect()
QRectF QGIDimLines::boundingRect () const override virtual
Referenced by TechDrawGui::QGIViewDimension::boundingRect().
draw()
void QGIDimLines::draw (void)
getEdgeFuzz()
double QGIDimLines::getEdgeFuzz (void) const protected
References TechDrawGui::PreferencesGui::edgeFuzz().
paint()
void QGIDimLines::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) override virtual
Reimplemented from TechDrawGui::QGIPrimPath.
References TechDrawGui::QGIPrimPath::paint().
shape()
QPainterPath QGIDimLines::shape (void) const override virtual
Reimplemented from TechDrawGui::QGIPrimPath.
Referenced by draftguitools.gui_offset.Offset::action(), PathScripts.PathSurfaceSupport.PathGeometryGenerator::generatePathGeometry(), and draftguitools.gui_offset.Offset::numericRadius().
type()
int TechDrawGui::QGIDimLines::type (void) const override
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGIDimLines.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGIDimLines.cpp