FreeCAD: StdMeshers_SMESHBlock Class Reference
StdMeshers_SMESHBlock Class Reference
#include <StdMeshers_Penta_3D.hxx>
Public Member Functions
SMESH_Block & Block ()
void ComputeParameters (const double &theU, const TopoDS_Shape &theShape, gp_XYZ &theXYZ)
void ComputeParameters (const gp_Pnt &thePnt, const TopoDS_Shape &theShape, gp_XYZ &theXYZ)
void ComputeParameters (const gp_Pnt &thePnt, gp_XYZ &theXYZ)
int ErrorStatus () const
SMESH_ComputeErrorPtr GetError () const
Return problem description.
bool IsForwadEdge (const int theEdgeID)
void Load (const TopoDS_Shell &theShell)
void Load (const TopoDS_Shell &theShell, const TopoDS_Vertex &theV000, const TopoDS_Vertex &theV001)
void Point (const gp_XYZ &theParams, const TopoDS_Shape &theShape, gp_Pnt &thePnt)
void Point (const gp_XYZ &theParams, gp_Pnt &thePnt)
const TopoDS_Shape & Shape (const int theID)
int ShapeID (const TopoDS_Shape &theShape)
StdMeshers_SMESHBlock ()
Protected Attributes
TopoDS_Shape myEmptyShape
int myErrorStatus
std::vector< int > myIsEdgeForward
TopTools_IndexedMapOfOrientedShape myShapeIDMap
TopoDS_Shell myShell
SMESH_Block myTBlock
Constructor & Destructor Documentation
StdMeshers_SMESHBlock()
StdMeshers_SMESHBlock::StdMeshers_SMESHBlock ()
References myErrorStatus, myIsEdgeForward, and SMESH_Block::NbEdges().
Member Function Documentation
Block()
SMESH_Block & StdMeshers_SMESHBlock::Block ()
Referenced by StdMeshers_Penta_3D::SetHorizEdgeXYZ().
ComputeParameters() [1/3]
void StdMeshers_SMESHBlock::ComputeParameters (const double & theU, const TopoDS_Shape & theShape, gp_XYZ & theXYZ)
References SMESH_Block::EdgeParameters(), SMESH_Block::IsEdgeID(), myErrorStatus, myTBlock, and ShapeID().
ComputeParameters() [2/3]
void StdMeshers_SMESHBlock::ComputeParameters (const gp_Pnt & thePnt, const TopoDS_Shape & theShape, gp_XYZ & theXYZ)
References SMESH_Block::ComputeParameters(), myErrorStatus, myTBlock, and ShapeID().
ComputeParameters() [3/3]
void StdMeshers_SMESHBlock::ComputeParameters (const gp_Pnt & thePnt, gp_XYZ & theXYZ)
References ComputeParameters(), and myShell.
Referenced by ComputeParameters(), and StdMeshers_Penta_3D::MakeNodes().
ErrorStatus()
int StdMeshers_SMESHBlock::ErrorStatus () const
References myErrorStatus.
Referenced by StdMeshers_Penta_3D::MakeBlock(), and StdMeshers_Penta_3D::MakeNodes().
GetError()
SMESH_ComputeErrorPtr StdMeshers_SMESHBlock::GetError () const
Return problem description.
References myErrorStatus, and SMESH_ComputeError::New().
Referenced by StdMeshers_Penta_3D::MakeBlock(), and StdMeshers_Penta_3D::MakeNodes().
IsForwadEdge()
bool StdMeshers_SMESHBlock::IsForwadEdge (const int theEdgeID)
References SMESH_Block::IsEdgeID(), SMESH_Block::IsForwardEdge(), myIsEdgeForward, myShapeIDMap, myTBlock, Shape(), and SMESH_Block::ShapeIndex().
Referenced by StdMeshers_Penta_3D::SetHorizEdgeXYZ().
Load() [1/2]
void StdMeshers_SMESHBlock::Load (const TopoDS_Shell & theShell)
References Load().
Referenced by Load(), and StdMeshers_Penta_3D::MakeBlock().
Load() [2/2]
void StdMeshers_SMESHBlock::Load (const TopoDS_Shell & theShell, const TopoDS_Vertex & theV000, const TopoDS_Vertex & theV001)
References SMESH_Block::LoadBlockShapes(), myErrorStatus, myShapeIDMap, myShell, and myTBlock.
Point() [1/2]
void StdMeshers_SMESHBlock::Point (const gp_XYZ & theParams, const TopoDS_Shape & theShape, gp_Pnt & thePnt)
References SMESH_Block::EdgePoint(), SMESH_Block::FacePoint(), SMESH_Block::IsEdgeID(), SMESH_Block::IsFaceID(), SMESH_Block::IsVertexID(), myErrorStatus, myTBlock, ShapeID(), SMESH_Block::ShellPoint(), and SMESH_Block::VertexPoint().
Point() [2/2]
void StdMeshers_SMESHBlock::Point (const gp_XYZ & theParams, gp_Pnt & thePnt)
References Point().
Referenced by StdMeshers_Penta_3D::FindNodeOnShape(), and Point().
Shape()
const TopoDS_Shape & StdMeshers_SMESHBlock::Shape (const int theID)
References myEmptyShape, myErrorStatus, and myShapeIDMap.
Referenced by StdMeshers_Penta_3D::ClearMeshOnFxy1(), IsForwadEdge(), StdMeshers_Penta_3D::MakeMeshOnFxy1(), StdMeshers_Penta_3D::MakeNodes(), and StdMeshers_Penta_3D::MakeVolumeMesh().
ShapeID()
int StdMeshers_SMESHBlock::ShapeID (const TopoDS_Shape & theShape)
References myErrorStatus, and myShapeIDMap.
Referenced by ComputeParameters(), StdMeshers_Penta_3D::FindNodeOnShape(), and Point().
Member Data Documentation
myEmptyShape
TopoDS_Shape StdMeshers_SMESHBlock::myEmptyShape protected
Referenced by Shape().
myErrorStatus
int StdMeshers_SMESHBlock::myErrorStatus protected
Referenced by ComputeParameters(), ErrorStatus(), GetError(), Load(), Point(), Shape(), ShapeID(), and StdMeshers_SMESHBlock().
myIsEdgeForward
std::vector<int> StdMeshers_SMESHBlock::myIsEdgeForward protected
Referenced by IsForwadEdge(), and StdMeshers_SMESHBlock().
myShapeIDMap
TopTools_IndexedMapOfOrientedShape StdMeshers_SMESHBlock::myShapeIDMap protected
Referenced by IsForwadEdge(), Load(), Shape(), and ShapeID().
myShell
TopoDS_Shell StdMeshers_SMESHBlock::myShell protected
Referenced by ComputeParameters(), and Load().
myTBlock
SMESH_Block StdMeshers_SMESHBlock::myTBlock protected
Referenced by ComputeParameters(), IsForwadEdge(), Load(), and Point().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_Penta_3D.hxx
FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_Penta_3D.cpp