FreeCAD: SpreadsheetGui::SheetModel Class Reference
SpreadsheetGui::SheetModel Class Reference
#include <SheetModel.h>
Public Member Functions
int columnCount (const QModelIndex &parent=QModelIndex()) const
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Qt::ItemFlags flags (const QModelIndex &) const
QVariant headerData (int section, Qt::Orientation orientation, int role) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
bool setData (const QModelIndex &index, const QVariant &value, int role)
SheetModel (QObject *parent)
SheetModel (Spreadsheet::Sheet *_sheet, QObject *parent=0)
~SheetModel ()
Constructor & Destructor Documentation
SheetModel() [1/2]
SheetModel::SheetModel (Spreadsheet::Sheet * _sheet, QObject * parent = 0) explicit
References draftgeoutils.faces::bind(), Spreadsheet::Sheet::cellUpdated, Base::Tools::fromStdString(), App::GetApplication(), ParameterGrp::GetASCII(), and App::Application::GetParameterGroupByPath().
~SheetModel()
SheetModel::~SheetModel ()
SheetModel() [2/2]
SpreadsheetGui::SheetModel::SheetModel (QObject * parent)
Member Function Documentation
columnCount()
int SheetModel::columnCount (const QModelIndex & parent = QModelIndex()) const
data()
QVariant SheetModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
References Spreadsheet::Sheet::dependsOn(), Base::Tools::fromStdString(), Spreadsheet::Cell::getAlias(), Spreadsheet::Cell::getAlignment(), Spreadsheet::Cell::getBackground(), Spreadsheet::Sheet::getCell(), Base::Persistence::getClassTypeId(), Base::UnitsApi::getDecimals(), Spreadsheet::Cell::getDisplayUnit(), Spreadsheet::Cell::getException(), Spreadsheet::Cell::getExpression(), Spreadsheet::Cell::getForeground(), Spreadsheet::Sheet::getPropertyByName(), App::PropertyQuantity::getQuantityValue(), Spreadsheet::Cell::getStringContent(), Spreadsheet::Cell::getStyle(), App::PropertyQuantity::getUnit(), Base::Quantity::getUserString(), App::PropertyString::getValue(), App::PropertyQuantity::getValue(), Spreadsheet::Cell::hasException(), Base::BaseClass::isDerivedFrom(), Base::Unit::isEmpty(), Spreadsheet::Sheet::providesTo(), Spreadsheet::DisplayUnit::scaler, Spreadsheet::DisplayUnit::stringRep, App::CellAddress::toString(), and Spreadsheet::DisplayUnit::unit.
Referenced by ArchSchedule.CommandArchSchedule::IsActive().
flags()
Qt::ItemFlags SheetModel::flags (const QModelIndex &) const
headerData()
QVariant SheetModel::headerData (int section, Qt::Orientation orientation, int role) const
References Spreadsheet::Sheet::getColumnWidth(), and Spreadsheet::Sheet::getRowHeight().
rowCount()
int SheetModel::rowCount (const QModelIndex & parent = QModelIndex()) const
setData()
bool SheetModel::setData (const QModelIndex & index, const QVariant & value, int role)
References Gui::Command::abortCommand(), Gui::Command::commitCommand(), Gui::Command::Doc, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, and Spreadsheet::Sheet::setContent().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Spreadsheet/Gui/SheetModel.h
Sources/FreeCAD/src/Mod/Spreadsheet/Gui/SheetModel.cpp