FreeCAD: PathTests.TestPathOpTools Namespace Reference
PathTests.TestPathOpTools Namespace Reference
Classes
class TestPathOpTools
Functions
def getNegativeShape (obj)
def getPositiveShape (obj)
def getWire (obj, nr=0)
def getWireInside (obj)
def getWireOutside (obj)
def makeWire (pts)
def wireMarkers (wire)
Variables
doc = None
shape = None
triangle = None
Function Documentation
getNegativeShape()
def PathTests.TestPathOpTools.getNegativeShape (obj)
Referenced by PathTests.TestPathOpTools.TestPathOpTools.test35(), PathTests.TestPathOpTools.TestPathOpTools.test36(), PathTests.TestPathOpTools.TestPathOpTools.test37(), and PathTests.TestPathOpTools.TestPathOpTools.test38().
getPositiveShape()
def PathTests.TestPathOpTools.getPositiveShape (obj)
Referenced by PathTests.TestPathOpTools.TestPathOpTools.test31(), PathTests.TestPathOpTools.TestPathOpTools.test32(), PathTests.TestPathOpTools.TestPathOpTools.test33(), and PathTests.TestPathOpTools.TestPathOpTools.test34().
getWire()
def PathTests.TestPathOpTools.getWire (obj, nr = 0)
Referenced by PathTests.TestPathOpTools.getWireInside(), PathTests.TestPathOpTools.getWireOutside(), PathTests.TestPathOpTools.TestPathOpTools.test31(), PathTests.TestPathOpTools.TestPathOpTools.test32(), PathTests.TestPathOpTools.TestPathOpTools.test33(), PathTests.TestPathOpTools.TestPathOpTools.test34(), PathTests.TestPathOpTools.TestPathOpTools.test35(), PathTests.TestPathOpTools.TestPathOpTools.test36(), PathTests.TestPathOpTools.TestPathOpTools.test37(), and PathTests.TestPathOpTools.TestPathOpTools.test38().
getWireInside()
def PathTests.TestPathOpTools.getWireInside (obj)
References PathTests.TestPathOpTools.getWire().
Referenced by PathTests.TestPathOpTools.TestPathOpTools.test11(), PathTests.TestPathOpTools.TestPathOpTools.test12(), PathTests.TestPathOpTools.TestPathOpTools.test20(), PathTests.TestPathOpTools.TestPathOpTools.test21(), PathTests.TestPathOpTools.TestPathOpTools.test44(), PathTests.TestPathOpTools.TestPathOpTools.test45(), PathTests.TestPathOpTools.TestPathOpTools.test46(), and PathTests.TestPathOpTools.TestPathOpTools.test47().
getWireOutside()
def PathTests.TestPathOpTools.getWireOutside (obj)
References PathTests.TestPathOpTools.getWire().
Referenced by PathTests.TestPathOpTools.TestPathOpTools.test13(), PathTests.TestPathOpTools.TestPathOpTools.test22(), PathTests.TestPathOpTools.TestPathOpTools.test40(), PathTests.TestPathOpTools.TestPathOpTools.test41(), PathTests.TestPathOpTools.TestPathOpTools.test42(), and PathTests.TestPathOpTools.TestPathOpTools.test43().
makeWire()
def PathTests.TestPathOpTools.makeWire (pts)
Referenced by PathTests.TestPathOpTools.TestPathOpTools.test00().
wireMarkers()
def PathTests.TestPathOpTools.wireMarkers (wire)
Referenced by PathTests.TestPathOpTools.TestPathOpTools.test50(), PathTests.TestPathOpTools.TestPathOpTools.test51(), and PathTests.TestPathOpTools.TestPathOpTools.test52().
Variable Documentation
doc
PathTests.TestPathOpTools.doc = None
shape
PathTests.TestPathOpTools.shape = None
triangle
PathTests.TestPathOpTools.triangle = None