FreeCAD: Gui::SoSVGVectorOutput Class Reference
Gui::SoSVGVectorOutput Class Reference
#include <SoFCVectorizeSVGAction.h>
Public Member Functions
virtual void closeFile (void)
std::fstream & getFileStream ()
virtual SbBool openFile (const char *filename)
SoSVGVectorOutput ()
virtual ~SoSVGVectorOutput ()
Constructor & Destructor Documentation
SoSVGVectorOutput()
SoSVGVectorOutput::SoSVGVectorOutput ()
~SoSVGVectorOutput()
SoSVGVectorOutput::~SoSVGVectorOutput () virtual
References closeFile().
Member Function Documentation
closeFile()
void SoSVGVectorOutput::closeFile (void) virtual
Referenced by ~SoSVGVectorOutput().
getFileStream()
std::fstream & SoSVGVectorOutput::getFileStream ()
Referenced by Gui::SoFCVectorizeSVGAction::printBackground(), Gui::SoFCVectorizeSVGAction::printFooter(), Gui::SoFCVectorizeSVGAction::printHeader(), Gui::SoFCVectorizeSVGActionP::printLine(), Gui::SoFCVectorizeSVGActionP::printText(), and Gui::SoFCVectorizeSVGActionP::printTriangle().
openFile()
SbBool SoSVGVectorOutput::openFile (const char * filename) virtual
References Base::FileInfo::filePath(), and Base::FileInfo::toStdWString().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/SoFCVectorizeSVGAction.h
FreeCAD/src/Gui/SoFCVectorizeSVGAction.cpp