FreeCAD: Gui::ConsoleHistory Class Reference
Gui::ConsoleHistory Class Reference
This class implements the history for the Python console.
#include <PythonConsole.h>
Public Member Functions
void append (const QString &inputLine)
ConsoleHistory ()
void doScratch (void)
doScratch removes the tail of the history list, starting from the index marked lately.
void first ()
bool isEmpty () const
void markScratch (void)
markScratch stores the current end index of the history list.
bool more ()
bool next ()
next switches the history pointer to the next item.
bool prev (const QString &prefix=QString())
prev switches the history pointer to the previous item.
void restart ()
restart resets the history access to the latest item.
const QString & value () const
const QStringList & values () const
~ConsoleHistory ()
Detailed Description
This class implements the history for the Python console.
Author
Werner Mayer
Constructor & Destructor Documentation
ConsoleHistory()
ConsoleHistory::ConsoleHistory ()
~ConsoleHistory()
ConsoleHistory::~ConsoleHistory ()
Member Function Documentation
append()
void ConsoleHistory::append (const QString & inputLine)
Referenced by Gui::PythonConsole::keyPressEvent(), and Gui::PythonConsole::printStatement().
doScratch()
void ConsoleHistory::doScratch (void)
doScratch removes the tail of the history list, starting from the index marked lately.
References restart().
first()
void ConsoleHistory::first ()
isEmpty()
bool ConsoleHistory::isEmpty (void) const
Referenced by Gui::PythonConsole::contextMenuEvent(), and Gui::PythonConsole::onCopyHistory().
markScratch()
void ConsoleHistory::markScratch (void)
markScratch stores the current end index of the history list.
Note: with simply remembering a start index, it does not work to nest scratch regions. However, just replace the index keeping by a stack - in case this is be a concern.
more()
bool ConsoleHistory::more ()
next()
bool ConsoleHistory::next ()
next switches the history pointer to the next item.
While searching the next item, the routine respects the search prefix set by prev().
Returns
true if the pointer was switched to a later item, false otherwise.
Referenced by Gui::PythonConsole::keyPressEvent().
prev()
bool ConsoleHistory::prev (const QString & prefix = QString())
prev switches the history pointer to the previous item.
The optional parameter prefix allows to search the history selectively for commands that start with a certain character sequence.
Parameters
prefix - prefix string for searching backwards in history, empty string by default
Returns
true if the pointer was switched to an earlier item, false otherwise.
Referenced by Gui::PythonConsole::keyPressEvent().
restart()
void ConsoleHistory::restart (void)
restart resets the history access to the latest item.
Referenced by doScratch(), and Gui::PythonConsole::keyPressEvent().
value()
const QString & ConsoleHistory::value () const
Referenced by PathScripts.PathProperty.Property::displayString(), PathScripts.PathProperty.PropertyQuantity::displayString(), PathScripts.PathSetupSheetOpPrototype.Property::displayString(), PathScripts.PathSetupSheetOpPrototype.PropertyQuantity::displayString(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), PathScripts.PathProperty.Property::getValue(), PathScripts.PathSetupSheetOpPrototype.Property::getValue(), Gui::PythonConsole::keyPressEvent(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), PathScripts.PathProperty.Property::setValue(), and PathScripts.PathSetupSheetOpPrototype.Property::setValue().
values()
const QStringList & ConsoleHistory::values () const
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::addInterval(), Gui::PythonConsole::createMimeDataFromSelection(), Gui::PythonConsole::onSaveHistoryAs(), ifc4.ifcstructuralloadconfiguration::validlistsize(), and Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::value().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/PythonConsole.h
FreeCAD/src/Gui/PythonConsole.cpp