FreeCAD: Gui::Dialog::DlgSettingsCacheDirectory Class Reference
Gui::Dialog::DlgSettingsCacheDirectory Class Reference
The DlgSettingsCacheDirectory class implements a preference page to change settings for the cache directory handling.
#include <DlgSettingsCacheDirectory.h>
Public Member Functions
DlgSettingsCacheDirectory (QWidget *parent=nullptr)
void loadSettings ()
void saveSettings ()
~DlgSettingsCacheDirectory ()
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
virtual void changeEvent (QEvent *e)=0
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Detailed Description
The DlgSettingsCacheDirectory class implements a preference page to change settings for the cache directory handling.
Author
Werner Mayer
Constructor & Destructor Documentation
DlgSettingsCacheDirectory()
DlgSettingsCacheDirectory::DlgSettingsCacheDirectory (QWidget * parent = nullptr)
References draftgeoutils.intersections::connect(), and App::Application::getUserCachePath().
~DlgSettingsCacheDirectory()
DlgSettingsCacheDirectory::~DlgSettingsCacheDirectory ()
Member Function Documentation
changeEvent()
void DlgSettingsCacheDirectory::changeEvent (QEvent * e) protected virtual
Implements Gui::Dialog::PreferencePage.
loadSettings()
void DlgSettingsCacheDirectory::loadSettings () virtual
Implements Gui::Dialog::PreferencePage.
References Gui::Dialog::ApplicationCacheSettings::getCacheSizeLimit(), and Gui::Dialog::ApplicationCacheSettings::getCheckPeriod().
saveSettings()
void DlgSettingsCacheDirectory::saveSettings () virtual
Implements Gui::Dialog::PreferencePage.
References Gui::Dialog::ApplicationCacheSettings::setCacheSizeLimit(), and Gui::Dialog::ApplicationCacheSettings::setCheckPeriod().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgSettingsCacheDirectory.h
FreeCAD/src/Gui/DlgSettingsCacheDirectory.cpp