FreeCAD: PartGui::ThicknessWidget Class Reference
PartGui::ThicknessWidget Class Reference
#include <TaskThickness.h>
Classes
class Private
Public Member Functions
bool accept ()
Part::Thickness * getObject () const
bool reject ()
ThicknessWidget (Part::Thickness *, QWidget *parent=nullptr)
~ThicknessWidget ()
Constructor & Destructor Documentation
ThicknessWidget()
ThicknessWidget::ThicknessWidget (Part::Thickness * thickness, QWidget * parent = nullptr)
References Gui::Command::App, Gui::QuantitySpinBox::bind(), PartGui::Ui_TaskOffset::fillOffset, App::PropertyEnumeration::getValue(), App::PropertyBool::getValue(), App::PropertyQuantity::getValue(), PartGui::Ui_TaskOffset::intersection, Part::Thickness::Intersection, Part::Thickness::Join, PartGui::Ui_TaskOffset::joinType, PartGui::Ui_TaskOffset::labelOffset, Part::Thickness::Mode, PartGui::Ui_TaskOffset::modeType, PartGui::Ui_TaskOffset::selfIntersection, Part::Thickness::SelfIntersection, Gui::QuantitySpinBox::setRange(), Gui::QuantitySpinBox::setSingleStep(), PartGui::Ui_TaskOffset::setupUi(), Gui::QuantitySpinBox::setValue(), PartGui::Ui_TaskOffset::spinOffset, PartGui::ThicknessWidget::Private::thickness, PartGui::ThicknessWidget::Private::ui, and Part::Thickness::Value.
~ThicknessWidget()
ThicknessWidget::~ThicknessWidget ()
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
accept()
bool ThicknessWidget::accept (void)
References Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Gui::Command::Doc, PartGui::Ui_TaskOffset::facesButton, App::DocumentObject::getStatusString(), Base::Quantity::getValue(), Gui::Command::Gui, PartGui::Ui_TaskOffset::intersection, App::DocumentObject::isValid(), PartGui::Ui_TaskOffset::joinType, PartGui::Ui_TaskOffset::modeType, PartGui::ThicknessWidget::Private::selection, PartGui::Ui_TaskOffset::selfIntersection, PartGui::Ui_TaskOffset::spinOffset, PartGui::ThicknessWidget::Private::thickness, PartGui::ThicknessWidget::Private::ui, and Gui::QuantitySpinBox::value.
Referenced by PartGui::TaskThickness::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
getObject()
Part::Thickness * ThicknessWidget::getObject (void) const
References PartGui::ThicknessWidget::Private::thickness.
Referenced by PartGui::TaskThickness::getObject().
reject()
bool ThicknessWidget::reject (void)
References Gui::Command::abortCommand(), Part::Thickness::Faces, PartGui::Ui_TaskOffset::facesButton, App::DocumentObject::getNameInDocument(), App::PropertyLinkSub::getValue(), Gui::Application::getViewProvider(), Gui::Command::Gui, Gui::Application::Instance, Gui::ViewProvider::show(), PartGui::ThicknessWidget::Private::thickness, PartGui::ThicknessWidget::Private::ui, and Gui::Command::updateActive().
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), PartGui::TaskThickness::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/TaskThickness.h
FreeCAD/src/Mod/Part/Gui/TaskThickness.cpp