FreeCAD: Gui::Dialog::DocumentRecovery Class Reference
Gui::Dialog::DocumentRecovery Class Reference
#include <DocumentRecovery.h>
Public Member Functions
void accept ()
DocumentRecovery (const QList< QFileInfo > &, QWidget *parent=nullptr)
bool foundDocuments () const
virtual ~DocumentRecovery ()
Protected Slots
void on_buttonCleanup_clicked ()
void onDeleteSection ()
Protected Member Functions
void cleanup (QDir &, const QList< QFileInfo > &, const QString &)
void closeEvent (QCloseEvent *)
void contextMenuEvent (QContextMenuEvent *)
QString createProjectFile (const QString &)
Detailed Description
Author
Werner Mayer
Constructor & Destructor Documentation
DocumentRecovery()
DocumentRecovery::DocumentRecovery (const QList< QFileInfo > & dirs, QWidget * parent = nullptr)
References Gui::Dialog::DocumentRecoveryPrivate::Created.
~DocumentRecovery()
DocumentRecovery::~DocumentRecovery () virtual
Member Function Documentation
accept()
void DocumentRecovery::accept (void)
References Gui::Dialog::DocumentRecoveryCleaner::clearDirectory(), App::Application::closeDocument(), createProjectFile(), Gui::Dialog::DocumentRecoveryPrivate::Failure, App::GetApplication(), Gui::Application::getDocument(), Gui::Application::Instance, App::Application::openDocuments(), Gui::Document::setModified(), and Gui::Dialog::DocumentRecoveryPrivate::Success.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
cleanup()
void DocumentRecovery::cleanup (QDir & tmp, const QList< QFileInfo > & dirs, const QString & lockFile) protected
References Gui::Dialog::DocumentRecoveryCleaner::clearDirectory().
Referenced by PathPythonGui.simple_edit_panel.SimpleEditPanel::abort(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::abort(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::abort(), PathScripts.PathDressupDogbone.TaskPanel::accept(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::accept(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::accept(), PathScripts.PathJobGui.TaskPanel::accept(), PathScripts.PathOpGui.TaskPanel::accept(), on_buttonCleanup_clicked(), PathScripts.PathDressupDogbone.TaskPanel::reject(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::reject(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::reject(), PathScripts.PathJobGui.TaskPanel::reject(), and PathScripts.PathOpGui.TaskPanel::reject().
closeEvent()
void DocumentRecovery::closeEvent (QCloseEvent * e) protected
contextMenuEvent()
void DocumentRecovery::contextMenuEvent (QContextMenuEvent * ev) protected
References onDeleteSection().
createProjectFile()
QString DocumentRecovery::createProjectFile (const QString & documentXml) protected
References Gui::Command::App.
Referenced by accept().
foundDocuments()
bool DocumentRecovery::foundDocuments () const
on_buttonCleanup_clicked
void DocumentRecovery::on_buttonCleanup_clicked () protected slot
References draftgeoutils.faces::bind(), Gui::Dialog::DocumentRecoveryHandler::checkForPreviousCrashes(), cleanup(), and Gui::Dialog::DlgCheckableMessageBox::showMessage().
onDeleteSection
void DocumentRecovery::onDeleteSection () protected slot
References Gui::Dialog::DocumentRecoveryCleaner::clearDirectory(), and App::Application::getUserCachePath().
Referenced by contextMenuEvent().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DocumentRecovery.h
FreeCAD/src/Gui/DocumentRecovery.cpp