FreeCAD: CDxfRead Class Reference
CDxfRead Class Reference
#include <dxf.h>
Public Member Functions
virtual void AddGraphics () const
virtual void AddGraphics () const
virtual void AddGraphics () const
CDxfRead (const char *filepath)
CDxfRead (const char *filepath)
CDxfRead (const char *filepath)
void DoRead (const bool ignore_errors=false)
void DoRead (const bool ignore_errors=false)
void DoRead (const bool ignore_errors=false)
bool Failed ()
bool Failed ()
bool Failed ()
bool IgnoreErrors () const
bool IgnoreErrors () const
bool IgnoreErrors () const
std::string LayerName () const
std::string LayerName () const
std::string LayerName () const
double mm (const double &value) const
double mm (double value) const
double mm (double value) const
virtual void OnReadArc (const double *, const double *, const double *, bool)
virtual void OnReadArc (const double *, const double *, const double *, bool, bool)
virtual void OnReadArc (const double *, const double *, const double *, bool, bool)
virtual void OnReadCircle (const double *, const double *, bool)
virtual void OnReadCircle (const double *, const double *, bool, bool)
virtual void OnReadCircle (const double *, const double *, bool, bool)
virtual void OnReadDimension (const double *, const double *, const double *, double)
virtual void OnReadDimension (const double *, const double *, const double *, double)
virtual void OnReadEllipse (const double *, double, double, double, double, double, bool)
virtual void OnReadEllipse (const double *, double, double, double, double, double, bool)
virtual void OnReadEllipse (const double *, double, double, double, double, double, bool)
virtual void OnReadInsert (const double *, const double *, const char *, double)
virtual void OnReadInsert (const double *, const double *, const char *, double)
virtual void OnReadInsert (const double *, const double *, const char *, double)
virtual void OnReadLine (const double *, const double *)
virtual void OnReadLine (const double *, const double *, bool)
virtual void OnReadLine (const double *, const double *, bool)
virtual void OnReadPoint (const double *)
virtual void OnReadPoint (const double *)
virtual void OnReadPoint (const double *)
virtual void OnReadSpline (struct SplineData &)
virtual void OnReadSpline (struct SplineData &)
virtual void OnReadSpline (struct SplineData &)
virtual void OnReadText (const double *, const double, const char *)
virtual void OnReadText (const double *, const double, const char *)
virtual void OnReadText (const double *, const double, const char *)
virtual ~CDxfRead ()
virtual ~CDxfRead ()
virtual ~CDxfRead ()
Protected Attributes
Aci_t m_aci
Constructor & Destructor Documentation
CDxfRead() [1/3]
CDxfRead::CDxfRead (const char * filepath)
~CDxfRead() [1/3]
CDxfRead::~CDxfRead () virtual
CDxfRead() [2/3]
CDxfRead::CDxfRead (const char * filepath)
~CDxfRead() [2/3]
virtual CDxfRead::~CDxfRead () virtual
CDxfRead() [3/3]
CDxfRead::CDxfRead (const char * filepath)
~CDxfRead() [3/3]
virtual CDxfRead::~CDxfRead () virtual
Member Function Documentation
AddGraphics() [1/3]
virtual void CDxfRead::AddGraphics () const virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
AddGraphics() [2/3]
virtual void CDxfRead::AddGraphics () const virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
AddGraphics() [3/3]
virtual void CDxfRead::AddGraphics () const virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
DoRead() [1/3]
void CDxfRead::DoRead (const bool ignore_errors = false)
DoRead() [2/3]
void CDxfRead::DoRead (const bool ignore_errors = false)
DoRead() [3/3]
void CDxfRead::DoRead (const bool ignore_errors = false)
Failed() [1/3]
bool CDxfRead::Failed ()
Failed() [2/3]
bool CDxfRead::Failed ()
Failed() [3/3]
bool CDxfRead::Failed ()
IgnoreErrors() [1/3]
bool CDxfRead::IgnoreErrors () const
IgnoreErrors() [2/3]
bool CDxfRead::IgnoreErrors () const
IgnoreErrors() [3/3]
bool CDxfRead::IgnoreErrors () const
LayerName() [1/3]
std::string CDxfRead::LayerName () const
Referenced by DraftUtils::DraftDxfRead::AddObject(), Import::ImpExpDxfRead::AddObject(), DraftUtils::DraftDxfRead::OnReadText(), and Import::ImpExpDxfRead::OnReadText().
LayerName() [2/3]
std::string CDxfRead::LayerName () const
LayerName() [3/3]
std::string CDxfRead::LayerName () const
mm() [1/3]
double CDxfRead::mm (const double & value) const
mm() [2/3]
double CDxfRead::mm (double value) const
mm() [3/3]
double CDxfRead::mm (double value) const
OnReadArc() [1/3]
virtual void CDxfRead::OnReadArc (const double * , const double * , const double * , bool) virtual
Reimplemented in AreaDxfRead.
OnReadArc() [2/3]
virtual void CDxfRead::OnReadArc (const double * , const double * , const double * , bool , bool) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadArc() [3/3]
virtual void CDxfRead::OnReadArc (const double * , const double * , const double * , bool , bool) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadCircle() [1/3]
virtual void CDxfRead::OnReadCircle (const double * , const double * , bool) virtual
OnReadCircle() [2/3]
virtual void CDxfRead::OnReadCircle (const double * , const double * , bool , bool) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadCircle() [3/3]
virtual void CDxfRead::OnReadCircle (const double * , const double * , bool , bool) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadDimension() [1/2]
virtual void CDxfRead::OnReadDimension (const double * , const double * , const double * , double) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadDimension() [2/2]
virtual void CDxfRead::OnReadDimension (const double * , const double * , const double * , double) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadEllipse() [1/3]
virtual void CDxfRead::OnReadEllipse (const double * , double , double , double , double , double , bool) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadEllipse() [2/3]
virtual void CDxfRead::OnReadEllipse (const double * , double , double , double , double , double , bool) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadEllipse() [3/3]
virtual void CDxfRead::OnReadEllipse (const double * , double , double , double , double , double , bool) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadInsert() [1/3]
virtual void CDxfRead::OnReadInsert (const double * , const double * , const char * , double) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadInsert() [2/3]
virtual void CDxfRead::OnReadInsert (const double * , const double * , const char * , double) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadInsert() [3/3]
virtual void CDxfRead::OnReadInsert (const double * , const double * , const char * , double) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadLine() [1/3]
virtual void CDxfRead::OnReadLine (const double * , const double *) virtual
Reimplemented in AreaDxfRead.
OnReadLine() [2/3]
virtual void CDxfRead::OnReadLine (const double * , const double * , bool) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadLine() [3/3]
virtual void CDxfRead::OnReadLine (const double * , const double * , bool) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadPoint() [1/3]
virtual void CDxfRead::OnReadPoint (const double *) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadPoint() [2/3]
virtual void CDxfRead::OnReadPoint (const double *) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadPoint() [3/3]
virtual void CDxfRead::OnReadPoint (const double *) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadSpline() [1/3]
virtual void CDxfRead::OnReadSpline (struct SplineData &) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadSpline() [2/3]
virtual void CDxfRead::OnReadSpline (struct SplineData &) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadSpline() [3/3]
virtual void CDxfRead::OnReadSpline (struct SplineData &) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadText() [1/3]
virtual void CDxfRead::OnReadText (const double * , const double , const char *) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadText() [2/3]
virtual void CDxfRead::OnReadText (const double * , const double , const char *) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
OnReadText() [3/3]
virtual void CDxfRead::OnReadText (const double * , const double , const char *) virtual
Reimplemented in Import::ImpExpDxfRead, and DraftUtils::DraftDxfRead.
Member Data Documentation
m_aci
Aci_t CDxfRead::m_aci protected
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Draft/App/dxf.h
Sources/FreeCAD/src/Mod/Draft/App/dxf.cpp