FreeCAD: Gui::UndoAction Class Reference
Gui::UndoAction Class Reference
The UndoAction class reimplements a special behaviour to make a menu appearing when the button with the arrow is clicked.
#include <Action.h>
Public Member Functions
void addTo (QWidget *w)
Adds this action to widget w.
void setEnabled (bool)
Sets whether the action is enabled.
void setVisible (bool)
UndoAction (Command *pcCmd, QObject *parent=0)
~UndoAction ()
Public Member Functions inherited from Gui::Action
QAction * action () const
Action (Command *pcCmd, QAction *action, QObject *parent)
Action takes ownership of the 'action' object.
Action (Command *pcCmd, QObject *parent=0)
Constructs an action called name with parent parent.
QIcon icon () const
bool isChecked () const
void setCheckable (bool)
void setChecked (bool, bool no_signal=false)
void setIcon (const QIcon &)
void setMenuRole (QAction::MenuRole menuRole)
void setShortcut (const QString &)
void setStatusTip (const QString &)
void setText (const QString &)
void setToolTip (const QString &)
void setWhatsThis (const QString &)
QKeySequence shortcut () const
QString statusTip () const
QString text () const
QString toolTip () const
QString whatsThis () const
virtual ~Action ()
Additional Inherited Members
Public Slots inherited from Gui::Action
virtual void onActivated ()
Activates the command.
virtual void onToggled (bool)
Sets whether the command is toggled.
Detailed Description
The UndoAction class reimplements a special behaviour to make a menu appearing when the button with the arrow is clicked.
Author
Werner Mayer
Constructor & Destructor Documentation
UndoAction()
UndoAction::UndoAction (Command * pcCmd, QObject * parent = 0)
References draftgeoutils.intersections::connect(), and Gui::Action::onActivated().
~UndoAction()
UndoAction::~UndoAction ()
Member Function Documentation
addTo()
void UndoAction::addTo (QWidget * w) virtual
Adds this action to widget w.
Reimplemented from Gui::Action.
References draftgeoutils.intersections::connect().
Referenced by Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium().
setEnabled()
void UndoAction::setEnabled (bool b) virtual
Sets whether the action is enabled.
Reimplemented from Gui::Action.
References Gui::Action::setEnabled().
Referenced by PathScripts.PathDressupTagGui.HoldingTagMarker::setSelected().
setVisible()
void UndoAction::setVisible (bool b) virtual
Reimplemented from Gui::Action.
References Gui::Action::setVisible().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Action.h
Sources/FreeCAD/src/Gui/Action.cpp