FreeCAD: SurfaceGui::Workbench Class Reference
SurfaceGui::Workbench Class Reference
#include <Workbench.h>
Public Member Functions
Workbench ()
virtual ~Workbench ()
Public Member Functions inherited from Gui::StdWorkbench
virtual void createMainWindowPopupMenu (MenuItem *) const
Sets up the contextmenu for the main window for this workbench.
virtual void setupContextMenu (const char *recipient, MenuItem *) const
Defines the standard context menu.
StdWorkbench ()
virtual ~StdWorkbench ()
Public Member Functions inherited from Gui::Workbench
bool activate ()
Activates the workbench and adds/removes GUI elements.
virtual void activated ()
Run some actions when the workbench gets activated.
void addTaskWatcher (const std::vector< Gui::TaskView::TaskWatcher * > &Watcher)
helper to add TaskWatcher to the TaskView
virtual void createMainWindowPopupMenu (MenuItem *) const
Sets up the contextmenu for the main window for this workbench.
virtual void deactivated ()
Run some actions when the workbench gets deactivated.
PyObject * getPyObject ()
The default implementation returns an instance of WorkbenchPy.
std::list< std::pair< std::string, std::list< std::string > > > getToolbarItems () const
Shows a list of all toolbars and their commands.
std::list< std::string > listCommandbars () const
std::list< std::string > listMenus () const
std::list< std::string > listToolbars () const
std::string name () const
Returns the name of the workbench object.
void removeTaskWatcher (void)
remove the added TaskWatcher
void retranslate () const
Translates the window titles of all menus, toolbars and dock windows.
void setName (const std::string &)
Set the name to the workbench object.
virtual void setupContextMenu (const char *recipient, MenuItem *) const
Sets up the contextmenu for this workbench.
Workbench ()
Constructs a workbench object.
virtual ~Workbench ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Member Functions
Gui::MenuItem * setupMenuBar () const
Defines the standard menus.
Gui::ToolBarItem * setupToolBars () const
Defines the standard toolbars.
Protected Member Functions inherited from Gui::StdWorkbench
virtual ToolBarItem * setupCommandBars () const
Defines the standard command bars.
virtual DockWindowItems * setupDockWindows () const
Returns a DockWindowItems structure of dock windows this workbench.
virtual MenuItem * setupMenuBar () const
Defines the standard menus.
virtual ToolBarItem * setupToolBars () const
Defines the standard toolbars.
Protected Member Functions inherited from Gui::Workbench
void addPermanentMenuItems (MenuItem *) const
Add permanent menu items to the structure.
virtual ToolBarItem * setupCommandBars () const =0
Returns a ToolBarItem tree structure of command bars for this workbench.
virtual DockWindowItems * setupDockWindows () const =0
Returns a DockWindowItems structure of dock windows this workbench.
virtual MenuItem * setupMenuBar () const =0
Returns a MenuItem tree structure of menus for this workbench.
virtual ToolBarItem * setupToolBars () const =0
Returns a ToolBarItem tree structure of toolbars for this workbench.
Additional Inherited Members
Static Public Member Functions inherited from Gui::Workbench
static void addPermanentMenuItem (const std::string &cmd, const std::string &after)
Add a permanent menu item cmd after an existing command after.
static void createLinkMenu (MenuItem *)
static void removePermanentMenuItem (const std::string &cmd)
Removes the command cmd from the permanent menu items.
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
Workbench()
Workbench::Workbench ()
~Workbench()
Workbench::~Workbench () virtual
Reimplemented from Gui::Workbench.
Member Function Documentation
setupMenuBar()
Gui::MenuItem * Workbench::setupMenuBar () const protected virtual
Defines the standard menus.
Reimplemented from Gui::StdWorkbench.
References Gui::MenuItem::findItem(), Gui::MenuItem::insertItem(), and Gui::MenuItem::setCommand().
setupToolBars()
Gui::ToolBarItem * Workbench::setupToolBars () const protected virtual
Defines the standard toolbars.
Reimplemented from Gui::StdWorkbench.
References Gui::ToolBarItem::setCommand().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Surface/Gui/Workbench.h
FreeCAD/src/Mod/Surface/Gui/Workbench.cpp