FreeCAD: femtools.geomtools Namespace Reference
femtools.geomtools Namespace Reference
Functions
def find_element_in_shape (aShape, anElement)
def get_cylindrical_coords (obj)
def get_element (part, element)
def get_rectangular_coords (obj)
def get_vertexes_by_element (aShape, anElement)
def is_same_geometry (shape1, shape2)
Function Documentation
find_element_in_shape()
def femtools.geomtools.find_element_in_shape (aShape, anElement)
References femtools.geomtools.is_same_geometry().
get_cylindrical_coords()
def femtools.geomtools.get_cylindrical_coords (obj)
get_element()
def femtools.geomtools.get_element (part, element)
get_rectangular_coords()
def femtools.geomtools.get_rectangular_coords (obj)
get_vertexes_by_element()
def femtools.geomtools.get_vertexes_by_element (aShape, anElement)
References femtools.geomtools.is_same_geometry().
is_same_geometry()
def femtools.geomtools.is_same_geometry (shape1, shape2)
Referenced by femtools.geomtools.find_element_in_shape(), and femtools.geomtools.get_vertexes_by_element().