FreeCAD: Part::GeometryExtension Class Reference
Part::GeometryExtension Class Reference abstract
#include <GeometryExtension.h>
Public Member Functions
virtual std::unique_ptr< GeometryExtension > copy (void) const =0
PyObject * copyPyObject () const
const std::string & getName () const
virtual PyObject * getPyObject (void)=0
This method returns the Python wrapper for a C++ object.
virtual void notifyAttachment (Part::Geometry *)
void setName (const std::string &str)
virtual ~GeometryExtension ()=default
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Member Functions
virtual void copyAttributes (Part::GeometryExtension *cpy) const
GeometryExtension ()
GeometryExtension (const GeometryExtension &obj)=default
GeometryExtension & operator= (const GeometryExtension &obj)=default
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
~GeometryExtension()
virtual Part::GeometryExtension::~GeometryExtension () virtual default
GeometryExtension() [1/2]
GeometryExtension::GeometryExtension () protected
GeometryExtension() [2/2]
Part::GeometryExtension::GeometryExtension (const GeometryExtension & obj) protected default
Member Function Documentation
copy()
virtual std::unique_ptr< GeometryExtension > Part::GeometryExtension::copy (void) const pure virtual
Implemented in Part::GeometryDefaultExtension< T >, Part::GeometryMigrationExtension, Sketcher::ExternalGeometryExtension, Sketcher::SketchGeometryExtension, Sketcher::SolverGeometryExtension, and SketcherGui::ViewProviderSketchGeometryExtension.
Referenced by copyPyObject().
copyAttributes()
void GeometryExtension::copyAttributes (Part::GeometryExtension * cpy) const protected virtual
Reimplemented in Part::GeometryDefaultExtension< T >, Part::GeometryMigrationExtension, Sketcher::ExternalGeometryExtension, Sketcher::SketchGeometryExtension, Sketcher::SolverGeometryExtension, and SketcherGui::ViewProviderSketchGeometryExtension.
References getName(), and setName().
Referenced by Part::GeometryDefaultExtension< T >::copyAttributes(), Part::GeometryMigrationExtension::copyAttributes(), Sketcher::ExternalGeometryExtension::copyAttributes(), Sketcher::SketchGeometryExtension::copyAttributes(), Sketcher::SolverGeometryExtension::copyAttributes(), and SketcherGui::ViewProviderSketchGeometryExtension::copyAttributes().
copyPyObject()
PyObject * GeometryExtension::copyPyObject () const
References copy(), and getPyObject().
getName()
const std::string & Part::GeometryExtension::getName (void) const
Referenced by copyAttributes(), and Part::GeometryPersistenceExtension::saveAttributes().
getPyObject()
virtual PyObject * Part::GeometryExtension::getPyObject (void) pure virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Implemented in Part::GeometryDefaultExtension< T >, Part::GeometryDefaultExtension< T >, Part::GeometryDefaultExtension< T >, Part::GeometryDefaultExtension< T >, Part::GeometryDefaultExtension< T >, Part::GeometryMigrationExtension, Sketcher::ExternalGeometryExtension, Sketcher::SketchGeometryExtension, Sketcher::SolverGeometryExtension, and SketcherGui::ViewProviderSketchGeometryExtension.
Referenced by copyPyObject().
notifyAttachment()
virtual void Part::GeometryExtension::notifyAttachment (Part::Geometry *) virtual
Reimplemented in Sketcher::SolverGeometryExtension.
operator=()
GeometryExtension & Part::GeometryExtension::operator= (const GeometryExtension & obj) protected default
setName()
void Part::GeometryExtension::setName (const std::string & str)
Referenced by copyAttributes(), and Part::GeometryDefaultExtension< T >::GeometryDefaultExtension().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/App/GeometryExtension.h
FreeCAD/src/Mod/Part/App/GeometryExtension.cpp