FreeCAD: PartDesignGui::Ui_TaskPolarPatternParameters Class Reference
PartDesignGui::Ui_TaskPolarPatternParameters Class Reference
#include <ui_TaskPolarPatternParameters.h>
Public Member Functions
void retranslateUi (QWidget *PartDesignGui__TaskPolarPatternParameters)
void setupUi (QWidget *PartDesignGui__TaskPolarPatternParameters)
Public Attributes
QPushButton * buttonAddFeature
QPushButton * buttonOK
QPushButton * buttonRemoveFeature
QCheckBox * checkBoxUpdateView
QCheckBox * checkReverse
QComboBox * comboAxis
QHBoxLayout * horizontalLayout
QHBoxLayout * horizontalLayout_2
QHBoxLayout * horizontalLayout_3
QHBoxLayout * horizontalLayout_4
QHBoxLayout * horizontalLayout_5
QLabel * label
QLabel * label_2
QLabel * labelAxis
QListWidget * listWidgetFeatures
Gui::QuantitySpinBox * polarAngle
Gui::UIntSpinBox * spinOccurrences
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void PartDesignGui::Ui_TaskPolarPatternParameters::retranslateUi (QWidget * PartDesignGui__TaskPolarPatternParameters)
References buttonAddFeature, buttonOK, buttonRemoveFeature, checkBoxUpdateView, checkReverse, label_2, labelAxis, listWidgetFeatures, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void PartDesignGui::Ui_TaskPolarPatternParameters::setupUi (QWidget * PartDesignGui__TaskPolarPatternParameters)
References buttonAddFeature, buttonOK, buttonRemoveFeature, checkBoxUpdateView, checkReverse, comboAxis, draftgeoutils.intersections::connect(), horizontalLayout, horizontalLayout_2, horizontalLayout_3, horizontalLayout_4, horizontalLayout_5, label_2, labelAxis, listWidgetFeatures, polarAngle, retranslateUi(), Gui::QuantitySpinBox::setMaximum(), Gui::QuantitySpinBox::setMinimum(), Gui::QuantitySpinBox::setValue(), spinOccurrences, and verticalLayout.
Member Data Documentation
buttonAddFeature
QPushButton* PartDesignGui::Ui_TaskPolarPatternParameters::buttonAddFeature
Referenced by retranslateUi(), and setupUi().
buttonOK
QPushButton* PartDesignGui::Ui_TaskPolarPatternParameters::buttonOK
Referenced by retranslateUi(), and setupUi().
buttonRemoveFeature
QPushButton* PartDesignGui::Ui_TaskPolarPatternParameters::buttonRemoveFeature
Referenced by retranslateUi(), and setupUi().
checkBoxUpdateView
QCheckBox* PartDesignGui::Ui_TaskPolarPatternParameters::checkBoxUpdateView
Referenced by retranslateUi(), and setupUi().
checkReverse
QCheckBox* PartDesignGui::Ui_TaskPolarPatternParameters::checkReverse
Referenced by retranslateUi(), and setupUi().
comboAxis
QComboBox* PartDesignGui::Ui_TaskPolarPatternParameters::comboAxis
Referenced by setupUi().
horizontalLayout
QHBoxLayout* PartDesignGui::Ui_TaskPolarPatternParameters::horizontalLayout
Referenced by setupUi().
horizontalLayout_2
QHBoxLayout* PartDesignGui::Ui_TaskPolarPatternParameters::horizontalLayout_2
Referenced by setupUi().
horizontalLayout_3
QHBoxLayout* PartDesignGui::Ui_TaskPolarPatternParameters::horizontalLayout_3
Referenced by setupUi().
horizontalLayout_4
QHBoxLayout* PartDesignGui::Ui_TaskPolarPatternParameters::horizontalLayout_4
Referenced by setupUi().
horizontalLayout_5
QHBoxLayout* PartDesignGui::Ui_TaskPolarPatternParameters::horizontalLayout_5
Referenced by setupUi().
label
QLabel* PartDesignGui::Ui_TaskPolarPatternParameters::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
label_2
QLabel* PartDesignGui::Ui_TaskPolarPatternParameters::label_2
Referenced by retranslateUi(), and setupUi().
labelAxis
QLabel* PartDesignGui::Ui_TaskPolarPatternParameters::labelAxis
Referenced by retranslateUi(), and setupUi().
listWidgetFeatures
QListWidget* PartDesignGui::Ui_TaskPolarPatternParameters::listWidgetFeatures
Referenced by retranslateUi(), and setupUi().
polarAngle
Gui::QuantitySpinBox* PartDesignGui::Ui_TaskPolarPatternParameters::polarAngle
Referenced by setupUi().
spinOccurrences
Gui::UIntSpinBox* PartDesignGui::Ui_TaskPolarPatternParameters::spinOccurrences
Referenced by setupUi().
verticalLayout
QVBoxLayout* PartDesignGui::Ui_TaskPolarPatternParameters::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/PartDesign/Gui/ui_TaskPolarPatternParameters.h