FreeCAD: FemGui::TaskFemConstraintGear Class Reference
FemGui::TaskFemConstraintGear Class Reference
#include <TaskFemConstraintGear.h>
Public Member Functions
double getDiameter (void) const
const std::string getDirectionName (void) const
const std::string getDirectionObject (void) const
double getForce (void) const
double getForceAngle (void) const
bool getReverse (void) const
TaskFemConstraintGear (ViewProviderFemConstraint *ConstraintView, QWidget *parent=0, const char *pixmapname="FEM_ConstraintGear")
Public Member Functions inherited from FemGui::TaskFemConstraintBearing
bool getAxial (void) const
double getDistance (void) const
const std::string getLocationName (void) const
const std::string getLocationObject (void) const
virtual const std::string getReferences () const
TaskFemConstraintBearing (ViewProviderFemConstraint *ConstraintView, QWidget *parent=0, const char *pixmapname="FEM_ConstraintBearing")
virtual ~TaskFemConstraintBearing ()
Public Member Functions inherited from FemGui::TaskFemConstraint
const std::string getReferences (const std::vector< std::string > &items) const
const std::string getScale () const
TaskFemConstraint (ViewProviderFemConstraint *ConstraintView, QWidget *parent=0, const char *pixmapname="")
virtual ~TaskFemConstraint ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (QWidget *parent=0)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (QWidget *parent=0)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockConnection (bool block)
void detachSelection ()
Detaches from the selection.
bool isConnectionAttached () const
bool isConnectionBlocked () const
SelectionObserver (bool attach=true, int resolve=1)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, int resolve=1)
Constructor.
virtual ~SelectionObserver ()
Protected Member Functions
virtual void changeEvent (QEvent *e)
virtual void onSelectionChanged (const Gui::SelectionChanges &msg)
Protected Member Functions inherited from FemGui::TaskFemConstraintBearing
bool event (QEvent *e)
Protected Member Functions inherited from FemGui::TaskFemConstraint
void createDeleteAction (QListWidget *parentList)
bool KeyEvent (QEvent *e)
virtual void keyPressEvent (QKeyEvent *ke)
const QString makeRefText (const App::DocumentObject *obj, const std::string &subName) const
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Types inherited from FemGui::TaskFemConstraint
enum { seldir, selref, selloc, selnone }
Protected Slots inherited from FemGui::TaskFemConstraint
void onButtonReference (const bool pressed=true)
void onButtonWizCancel ()
void onButtonWizOk ()
void onReferenceDeleted (const int row)
void setSelection (QListWidgetItem *item)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from FemGui::TaskFemConstraintBearing
Ui_TaskFemConstraintBearing * ui
Protected Attributes inherited from FemGui::TaskFemConstraint
ViewProviderFemConstraint * ConstraintView
QAction * deleteAction
QWidget * proxy
enum FemGui::TaskFemConstraint:: { ... } selectionMode
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskFemConstraintGear()
TaskFemConstraintGear::TaskFemConstraintGear (ViewProviderFemConstraint * ConstraintView, QWidget * parent = 0, const char * pixmapname = "FEM_ConstraintGear")
References draftgeoutils.intersections::connect(), FemGui::TaskFemConstraint::ConstraintView, Fem::ConstraintGear::Diameter, Fem::ConstraintGear::Direction, Fem::ConstraintGear::Force, Fem::ConstraintGear::ForceAngle, Gui::ViewProviderDocumentObject::getObject(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), App::PropertyFloat::getValue(), App::PropertyBool::getValue(), FemGui::TaskFemConstraint::makeRefText(), Fem::ConstraintGear::Reversed, and FemGui::TaskFemConstraintBearing::ui.
Member Function Documentation
changeEvent()
void TaskFemConstraintGear::changeEvent (QEvent * e) protected virtual
Reimplemented from FemGui::TaskFemConstraintBearing.
Reimplemented in FemGui::TaskFemConstraintPulley.
References FemGui::TaskFemConstraint::proxy, and FemGui::TaskFemConstraintBearing::ui.
getDiameter()
double TaskFemConstraintGear::getDiameter (void) const
References FemGui::TaskFemConstraintBearing::ui.
Referenced by FemGui::TaskDlgFemConstraintGear::accept().
getDirectionName()
const std::string TaskFemConstraintGear::getDirectionName (void) const
References FemGui::TaskFemConstraintBearing::ui.
Referenced by FemGui::TaskDlgFemConstraintGear::accept().
getDirectionObject()
const std::string TaskFemConstraintGear::getDirectionObject (void) const
References FemGui::TaskFemConstraintBearing::ui.
Referenced by FemGui::TaskDlgFemConstraintGear::accept().
getForce()
double TaskFemConstraintGear::getForce (void) const
References FemGui::TaskFemConstraintBearing::ui.
Referenced by FemGui::TaskDlgFemConstraintGear::accept().
getForceAngle()
double TaskFemConstraintGear::getForceAngle (void) const
References FemGui::TaskFemConstraintBearing::ui.
Referenced by FemGui::TaskDlgFemConstraintGear::accept().
getReverse()
bool TaskFemConstraintGear::getReverse (void) const
References FemGui::TaskFemConstraintBearing::ui.
Referenced by FemGui::TaskDlgFemConstraintGear::accept().
onSelectionChanged()
void TaskFemConstraintGear::onSelectionChanged (const Gui::SelectionChanges & msg) protected virtual
Reimplemented from FemGui::TaskFemConstraintBearing.
References Gui::SelectionChanges::AddSelection, Gui::SelectionSingleton::clearSelection(), FemGui::TaskFemConstraint::ConstraintView, Fem::ConstraintGear::Direction, App::DocumentObject::getDocument(), App::Document::getName(), App::Document::getObject(), Gui::ViewProviderDocumentObject::getObject(), Part::PropertyPartShape::getShape(), Part::TopoShape::getSubShape(), Fem::Tools::isLinear(), Fem::Tools::isPlanar(), FemGui::TaskFemConstraint::makeRefText(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), FemGui::TaskFemConstraint::seldir, Gui::Selection(), FemGui::TaskFemConstraint::selectionMode, FemGui::TaskFemConstraint::selnone, App::PropertyLinkSub::setValue(), Part::Feature::Shape, and FemGui::TaskFemConstraintBearing::ui.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintGear.h
Sources/FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintGear.cpp