FreeCAD: NavigationIndicatorGui Namespace Reference
NavigationIndicatorGui Namespace Reference
Classes
class IndicatorButton
Functions
def onCompact ()
def onMenu (action)
def onOrbit ()
def onOrbitShow ()
def onTooltip ()
def retranslateUi ()
def setCompact (action)
def setCurrent ()
def translate (context, text)
Variables
a0 = QtGui.QAction(gStyle)
a1 = QtGui.QAction(gStyle)
a2 = QtGui.QAction(gStyle)
a3 = QtGui.QAction(gStyle)
a4 = QtGui.QAction(gStyle)
a5 = QtGui.QAction(gStyle)
a6 = QtGui.QAction(gStyle)
a7 = QtGui.QAction(gStyle)
a8 = QtGui.QAction(gStyle)
aCompact = QtGui.QAction(menuSettings)
aTooltip = QtGui.QAction(menuSettings)
aTrackball = QtGui.QAction(gOrbit)
aTurntable = QtGui.QAction(gOrbit)
gOrbit = QtGui.QActionGroup(menuSettings)
gStyle = QtGui.QActionGroup(menu)
indicator = IndicatorButton(statusBar)
menu = QtGui.QMenu(indicator)
menuOrbit = QtGui.QMenu(menu)
menuSettings = QtGui.QMenu(menu)
mw = Gui.getMainWindow()
p = App.ParamGet("User parameter:Tux/NavigationIndicator")
pView = App.ParamGet("User parameter:BaseApp/Preferences/View")
statusBar = mw.statusBar()
timer = QtCore.QTimer()
Function Documentation
onCompact()
def NavigationIndicatorGui.onCompact ()
Enable or disable compact mode.
References setCurrent().
Referenced by setCurrent().
onMenu()
def NavigationIndicatorGui.onMenu (action)
Set navigation style on selection.
References setCompact().
onOrbit()
def NavigationIndicatorGui.onOrbit ()
Use turntable or trackball orbit style.
onOrbitShow()
def NavigationIndicatorGui.onOrbitShow ()
Set turntable or trackball orbit style.
Referenced by setCurrent().
onTooltip()
def NavigationIndicatorGui.onTooltip ()
Enable or disable verbose tooltips.
References setCurrent().
Referenced by NavigationIndicatorGui.IndicatorButton.changeEvent(), and setCurrent().
retranslateUi()
def NavigationIndicatorGui.retranslateUi ()
Retranslate navigation indicator on language change
Referenced by NavigationIndicatorGui.IndicatorButton.changeEvent(), and setCurrent().
setCompact()
def NavigationIndicatorGui.setCompact (action)
Set compact mode.
Referenced by onMenu(), and setCurrent().
setCurrent()
def NavigationIndicatorGui.setCurrent ()
Set navigation style on start and on interval.
References onCompact(), onOrbitShow(), onTooltip(), retranslateUi(), and setCompact().
Referenced by onCompact(), and onTooltip().
translate()
def NavigationIndicatorGui.translate (context, text)
Variable Documentation
a0
NavigationIndicatorGui.a0 = QtGui.QAction(gStyle)
a1
NavigationIndicatorGui.a1 = QtGui.QAction(gStyle)
a2
NavigationIndicatorGui.a2 = QtGui.QAction(gStyle)
a3
NavigationIndicatorGui.a3 = QtGui.QAction(gStyle)
a4
NavigationIndicatorGui.a4 = QtGui.QAction(gStyle)
a5
NavigationIndicatorGui.a5 = QtGui.QAction(gStyle)
a6
NavigationIndicatorGui.a6 = QtGui.QAction(gStyle)
a7
NavigationIndicatorGui.a7 = QtGui.QAction(gStyle)
a8
NavigationIndicatorGui.a8 = QtGui.QAction(gStyle)
aCompact
NavigationIndicatorGui.aCompact = QtGui.QAction(menuSettings)
aTooltip
NavigationIndicatorGui.aTooltip = QtGui.QAction(menuSettings)
aTrackball
NavigationIndicatorGui.aTrackball = QtGui.QAction(gOrbit)
aTurntable
NavigationIndicatorGui.aTurntable = QtGui.QAction(gOrbit)
gOrbit
NavigationIndicatorGui.gOrbit = QtGui.QActionGroup(menuSettings)
gStyle
NavigationIndicatorGui.gStyle = QtGui.QActionGroup(menu)
indicator
NavigationIndicatorGui.indicator = IndicatorButton(statusBar)
menu
NavigationIndicatorGui.menu = QtGui.QMenu(indicator)
menuOrbit
NavigationIndicatorGui.menuOrbit = QtGui.QMenu(menu)
menuSettings
NavigationIndicatorGui.menuSettings = QtGui.QMenu(menu)
mw
NavigationIndicatorGui.mw = Gui.getMainWindow()
p
NavigationIndicatorGui.p = App.ParamGet("User parameter:Tux/NavigationIndicator")
pView
NavigationIndicatorGui.pView = App.ParamGet("User parameter:BaseApp/Preferences/View")
statusBar
NavigationIndicatorGui.statusBar = mw.statusBar()
timer
NavigationIndicatorGui.timer = QtCore.QTimer()