FreeCAD: ArchSpace Namespace Reference
ArchSpace Namespace Reference
Workbenches » Python workbenches » Arch
The Space object and tools.
Classes
class SpaceTaskPanel
Functions
def addSpaceBoundaries (space, subobjects)
def makeSpace (objects=None, baseobj=None, name="Space")
def removeSpaceBoundaries (space, objects)
Variables
list ConditioningTypes
list SpaceTypes
Detailed Description
The Space object and tools.
This module provides tools to build Space objects. Spaces define an open volume inside or outside a building, ie. a room.
Function Documentation
addSpaceBoundaries()
def ArchSpace.addSpaceBoundaries (space, subobjects)
addSpaceBoundaries(space,subobjects): adds the given subobjects to the given space
makeSpace()
def ArchSpace.makeSpace (objects = None, baseobj = None, name = "Space")
makeSpace([objects]): Creates a space object from the given objects. Objects can be one
document object, in which case it becomes the base shape of the space object, or a list of
selection objects as got from getSelectionEx(), or a list of tuples (object, subobjectname)
References draftutils.gui_utils.getSelectionEx.
removeSpaceBoundaries()
def ArchSpace.removeSpaceBoundaries (space, objects)
removeSpaceBoundaries(space,objects): removes the given objects from the given spaces boundaries
References ArchComponent.ViewProviderComponent.attach(), ArchCommands.getCutVolume(), ArchCommands.getDefaultColor(), ArchComponent.ViewProviderComponent.getDisplayModes(), DraftVecUtils.isNull(), ArchComponent.Component.onChanged(), ArchComponent.Component.onDocumentRestored(), draftutils.translate.QT_TRANSLATE_NOOP, and ArchComponent.ViewProviderComponent.setDisplayMode().
Variable Documentation
ConditioningTypes
list ArchSpace.ConditioningTypes
Initial value:
=  [
"Unconditioned",
"Heated",
"Cooled",
"HeatedAndCooled",
"Vented",
"NaturallyVentedOnly"
]
SpaceTypes
list ArchSpace.SpaceTypes