FreeCAD: WebGui::FcCookieJar Class Reference
WebGui::FcCookieJar Class Reference
#include <CookieJar.h>
Public Slots
void loadFromDisk ()
void reset ()
void scheduleSaveToDisk ()
Public Member Functions
FcCookieJar (QObject *parent=nullptr)
The default cookiejar of qt does not implement saving and restoring of cookies to disk.
virtual bool setCookiesFromUrl (const QList< QNetworkCookie > &, const QUrl &)
virtual ~FcCookieJar ()
Constructor & Destructor Documentation
FcCookieJar()
FcCookieJar::FcCookieJar (QObject * parent = nullptr)
The default cookiejar of qt does not implement saving and restoring of cookies to disk.
So we extend it here, and make it save and restore cookies to a simple text file saved in the FreeCAD user folder. adapted from https://github.com/adobe/webkit/blob/master/Tools/QtTestBrowser
References draftgeoutils.intersections::connect(), Base::FileInfo::filePath(), App::Application::getUserAppDataDir(), and loadFromDisk().
~FcCookieJar()
FcCookieJar::~FcCookieJar () virtual
Member Function Documentation
loadFromDisk
void FcCookieJar::loadFromDisk () slot
Referenced by FcCookieJar().
reset
void FcCookieJar::reset (void) slot
References scheduleSaveToDisk().
Referenced by draftguitools.gui_trackers.gridTracker::set().
scheduleSaveToDisk
void FcCookieJar::scheduleSaveToDisk () slot
Referenced by reset(), and setCookiesFromUrl().
setCookiesFromUrl()
bool FcCookieJar::setCookiesFromUrl (const QList< QNetworkCookie > & cookieList, const QUrl & url) virtual
References scheduleSaveToDisk().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Web/Gui/CookieJar.h
FreeCAD/src/Mod/Web/Gui/CookieJar.cpp