FreeCAD: SMESH_Block::TFace Class Reference
SMESH_Block::TFace Class Reference
#include <SMESH_Block.hxx>
Public Member Functions
void GetCoefs (int i, const gp_XYZ &theParams, double &eCoef, double &vCoef) const
int GetUInd () const
gp_XY GetUV (const gp_XYZ &theParams) const
gp_XY GetUVRange () const
int GetVInd () const
bool IsUVInQuad (const gp_XY &uv, const gp_XYZ &param0, const gp_XYZ &param1, const gp_XYZ &param2, const gp_XYZ &param3) const
gp_XYZ Point (const gp_XYZ &theParams) const
void Set (const int faceID, Adaptor3d_Surface *S, Adaptor2d_Curve2d *c2d[4], const bool isForward[4])
Set face data.
void Set (const int faceID, const TEdge &edgeU0, const TEdge &edgeU1)
Set face data to work with mesh block.
const Adaptor3d_Surface * Surface () const
TFace ()
~TFace ()
Destructor.
Constructor & Destructor Documentation
TFace()
SMESH_Block::TFace::TFace ()
~TFace()
SMESH_Block::TFace::~TFace ()
Destructor.
Member Function Documentation
GetCoefs()
void SMESH_Block::TFace::GetCoefs (int i, const gp_XYZ & theParams, double & eCoef, double & vCoef) const
GetUInd()
int SMESH_Block::TFace::GetUInd () const
Referenced by SMESH_Block::findUVAround(), SMESH_Block::findUVByHalfDivision(), and SMESH_Block::refineParametersOnFace().
GetUV()
gp_XY SMESH_Block::TFace::GetUV (const gp_XYZ & theParams) const
GetUVRange()
gp_XY SMESH_Block::TFace::GetUVRange () const
GetVInd()
int SMESH_Block::TFace::GetVInd () const
Referenced by SMESH_Block::findUVAround(), SMESH_Block::findUVByHalfDivision(), and SMESH_Block::refineParametersOnFace().
IsUVInQuad()
bool SMESH_Block::TFace::IsUVInQuad (const gp_XY & uv, const gp_XYZ & param0, const gp_XYZ & param1, const gp_XYZ & param2, const gp_XYZ & param3) const
Referenced by SMESH_Block::findUVByHalfDivision().
Point()
gp_XYZ SMESH_Block::TFace::Point (const gp_XYZ & theParams) const
Referenced by SMESH_Block::findUVAround(), SMESH_Block::findUVByHalfDivision(), and SMESH_Block::refineParametersOnFace().
Set() [1/2]
void SMESH_Block::TFace::Set (const int faceID, Adaptor3d_Surface * S, Adaptor2d_Curve2d * c2D[4], const bool isForward[4])
Set face data.
Parameters
faceID - block sub-shape ID
S - face surface geometry
c2d - 4 pcurves in the order as returned by GetFaceEdgesIDs(faceID)
isForward - orientation of pcurves comparing with block edge direction
Referenced by StdMeshers_PrismAsBlock::Init(), SMESH_Block::LoadFace(), and SMESH_Block::LoadMeshBlock().
Set() [2/2]
void SMESH_Block::TFace::Set (const int faceID, const TEdge & edgeU0, const TEdge & edgeU1)
Set face data to work with mesh block.
Parameters
faceID - block sub-shape ID
edgeU0 - filled data of edge u0 = GetFaceEdgesIDs(faceID)[ 0 ]
edgeU1 - filled data of edge u1 = GetFaceEdgesIDs(faceID)[ 1 ]
References SMESH_Block::TEdge::NodeXYZ().
Surface()
const Adaptor3d_Surface* SMESH_Block::TFace::Surface () const
Referenced by SMESH_Block::refineParametersOnFace().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_Block.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/SMESH_Block.cpp