FreeCAD: QSint::TaskHeader Class Reference
QSint::TaskHeader Class Reference
#include <taskheader_p.h>
Public Slots
void fold ()
Signals
void activated ()
Public Member Functions
bool expandable () const
void setExpandable (bool expandable)
void setFold (bool)
void setScheme (ActionPanelScheme *scheme)
TaskHeader (const QIcon &icon, const QString &title, bool expandable, QWidget *parent=0)
Protected Slots
void animate ()
Protected Member Functions
void changeIcons ()
virtual void enterEvent (QEvent *event)
bool eventFilter (QObject *obj, QEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
virtual void leaveEvent (QEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void paintEvent (QPaintEvent *event)
Protected Attributes
bool m_buttonOver
bool m_fold
double m_opacity
bool m_over
QLabel * myButton
bool myExpandable
ActionPanelScheme * myScheme
ActionLabel * myTitle
Friends
class ActionGroup
Constructor & Destructor Documentation
TaskHeader()
QSint::TaskHeader::TaskHeader (const QIcon & icon, const QString & title, bool expandable, QWidget * parent = 0)
References draftgeoutils.intersections::connect(), QSint::ActionPanelScheme::defaultScheme(), fold(), myExpandable, myTitle, setExpandable(), and setScheme().
Member Function Documentation
activated
void QSint::TaskHeader::activated () signal
Referenced by fold(), and mouseReleaseEvent().
animate
void QSint::TaskHeader::animate () protected slot
References QSint::ActionPanelScheme::headerAnimation, m_opacity, m_over, and myScheme.
Referenced by enterEvent(), and leaveEvent().
changeIcons()
void QSint::TaskHeader::changeIcons () protected
References QSint::ActionPanelScheme::headerButtonFold, QSint::ActionPanelScheme::headerButtonFoldOver, QSint::ActionPanelScheme::headerButtonSize, QSint::ActionPanelScheme::headerButtonUnfold, QSint::ActionPanelScheme::headerButtonUnfoldOver, m_buttonOver, m_fold, myButton, and myScheme.
Referenced by eventFilter(), fold(), setExpandable(), setFold(), and setScheme().
enterEvent()
void QSint::TaskHeader::enterEvent (QEvent * event) protected virtual
References animate(), and m_over.
eventFilter()
bool QSint::TaskHeader::eventFilter (QObject * obj, QEvent * event) protected
References changeIcons(), fold(), m_buttonOver, and myExpandable.
expandable()
bool QSint::TaskHeader::expandable () const
References myExpandable.
Referenced by QSint::ActionGroup::isExpandable(), setExpandable(), and QSint::ActionGroup::showHide().
fold
void QSint::TaskHeader::fold () slot
References activated(), changeIcons(), m_fold, myButton, and myExpandable.
Referenced by eventFilter(), Gui::TaskView::TaskBox::hideGroupBox(), and TaskHeader().
keyPressEvent()
void QSint::TaskHeader::keyPressEvent (QKeyEvent * event) protected virtual
keyReleaseEvent()
void QSint::TaskHeader::keyReleaseEvent (QKeyEvent * event) protected virtual
leaveEvent()
void QSint::TaskHeader::leaveEvent (QEvent * event) protected virtual
References animate(), and m_over.
mouseReleaseEvent()
void QSint::TaskHeader::mouseReleaseEvent (QMouseEvent * event) protected virtual
References activated().
paintEvent()
void QSint::TaskHeader::paintEvent (QPaintEvent * event) protected virtual
References QSint::ActionPanelScheme::headerAnimation, m_opacity, and myScheme.
setExpandable()
void QSint::TaskHeader::setExpandable (bool expandable)
References changeIcons(), expandable(), QSint::ActionPanelScheme::headerButtonSize, m_fold, myButton, myExpandable, and myScheme.
Referenced by QSint::ActionGroup::setExpandable(), and TaskHeader().
setFold()
void QSint::TaskHeader::setFold (bool on)
References changeIcons(), m_fold, myButton, and myExpandable.
Referenced by QSint::ActionGroup::processHide(), and QSint::ActionGroup::processShow().
setScheme()
void QSint::TaskHeader::setScheme (ActionPanelScheme * scheme)
References QSint::ActionPanelScheme::actionStyle, changeIcons(), QSint::ActionPanelScheme::headerSize, myExpandable, and myScheme.
Referenced by QSint::ActionGroup::setScheme(), and TaskHeader().
Friends And Related Function Documentation
ActionGroup
friend class ActionGroup friend
Member Data Documentation
m_buttonOver
bool QSint::TaskHeader::m_buttonOver protected
Referenced by changeIcons(), and eventFilter().
m_fold
bool QSint::TaskHeader::m_fold protected
Referenced by changeIcons(), fold(), setExpandable(), and setFold().
m_opacity
double QSint::TaskHeader::m_opacity protected
Referenced by animate(), and paintEvent().
m_over
bool QSint::TaskHeader::m_over protected
Referenced by animate(), enterEvent(), and leaveEvent().
myButton
QLabel* QSint::TaskHeader::myButton protected
Referenced by changeIcons(), fold(), setExpandable(), and setFold().
myExpandable
bool QSint::TaskHeader::myExpandable protected
Referenced by eventFilter(), expandable(), fold(), setExpandable(), setFold(), setScheme(), and TaskHeader().
myScheme
ActionPanelScheme* QSint::TaskHeader::myScheme protected
Referenced by animate(), changeIcons(), paintEvent(), setExpandable(), and setScheme().
myTitle
ActionLabel* QSint::TaskHeader::myTitle protected
Referenced by QSint::ActionGroup::headerText(), QSint::ActionGroup::setHeaderText(), and TaskHeader().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/QSint/actionpanel/taskheader_p.h
Sources/FreeCAD/src/Gui/QSint/actionpanel/taskheader_p.cpp