FreeCAD: geoff_geometry::Box Class Reference
geoff_geometry::Box Class Reference
#include <geometry.h>
Public Member Functions
Box ()
Box (Point &pmin, Point &pmax)
void combine (const Box &b)
bool outside (const Box &b) const
Public Attributes
Point max
Point min
bool ok
Constructor & Destructor Documentation
Box() [1/2]
geoff_geometry::Box::Box ()
References max, min, ok, geoff_geometry::Point::x, and geoff_geometry::Point::y.
Referenced by Mod.PartDesign.PartDesignTests.TestBoolean.TestBoolean::testBooleanCommonCase(), Mod.PartDesign.PartDesignTests.TestBoolean.TestBoolean::testBooleanCutCase(), Mod.PartDesign.PartDesignTests.TestRevolve.TestRevolve::testGrooveFace(), Mod.Test.Document.UndoRedoCases::testUndoIssue0003150Part1(), Mod.PartDesign.PartDesignTests.TestLinearPattern.TestLinearPattern::testYAxisLinearPattern(), Mod.PartDesign.PartDesignTests.TestPolarPattern.TestPolarPattern::testYAxisPolarPattern(), Mod.PartDesign.PartDesignTests.TestLinearPattern.TestLinearPattern::testZAxisLinearPattern(), and Mod.PartDesign.PartDesignTests.TestPolarPattern.TestPolarPattern::testZAxisPolarPattern().
Box() [2/2]
geoff_geometry::Box::Box (Point & pmin, Point & pmax)
References max, min, and ok.
Referenced by Mod.PartDesign.PartDesignTests.TestBoolean.TestBoolean::testBooleanCommonCase(), Mod.PartDesign.PartDesignTests.TestBoolean.TestBoolean::testBooleanCutCase(), Mod.PartDesign.PartDesignTests.TestRevolve.TestRevolve::testGrooveFace(), Mod.Test.Document.UndoRedoCases::testUndoIssue0003150Part1(), Mod.PartDesign.PartDesignTests.TestLinearPattern.TestLinearPattern::testYAxisLinearPattern(), Mod.PartDesign.PartDesignTests.TestPolarPattern.TestPolarPattern::testYAxisPolarPattern(), Mod.PartDesign.PartDesignTests.TestLinearPattern.TestLinearPattern::testZAxisLinearPattern(), and Mod.PartDesign.PartDesignTests.TestPolarPattern.TestPolarPattern::testZAxisPolarPattern().
Member Function Documentation
combine()
void geoff_geometry::Box::combine (const Box & b)
References max, min, geoff_geometry::Point::x, and geoff_geometry::Point::y.
outside()
bool geoff_geometry::Box::outside (const Box & b) const
References max, min, geoff_geometry::Point::x, and geoff_geometry::Point::y.
Referenced by geoff_geometry::Intof().
Member Data Documentation
max
Point geoff_geometry::Box::max
Referenced by Box(), combine(), geoff_geometry::Line::Line(), and outside().
min
Point geoff_geometry::Box::min
Referenced by Box(), combine(), geoff_geometry::Line::Line(), and outside().
ok
bool geoff_geometry::Box::ok
Referenced by Box().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Path/libarea/kurve/geometry.h
FreeCAD/src/Mod/Path/libarea/kurve/Finite.cpp