FreeCAD: Base::AxisPy Class Reference
Base::AxisPy Class Reference
The python export class for Axis.
#include <AxisPy.h>
Public Types
typedef Axis * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
AxisPy (Axis *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of AxisPy.
static PyMethodDef Methods []
Methods structure of AxisPy.
static PyTypeObject Type
Type structure of AxisPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~AxisPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * move (PyObject *args)
implementer for the move() method
PyObject * multiply (PyObject *args)
implementer for the multiply() method
PyObject * reversed (PyObject *args)
implementer for the reversed() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_move (PyObject *self, PyObject *args)
callback for the move() method
static PyObject * staticCallback_multiply (PyObject *self, PyObject *args)
callback for the multiply() method
static PyObject * staticCallback_reversed (PyObject *self, PyObject *args)
callback for the reversed() method
callbacks and implementers for the python object attributes
Py::Object getBase (void) const
getter for the Base attribute
void setBase (Py::Object arg)
setter for the Base attribute
Py::Object getDirection (void) const
getter for the Direction attribute
void setDirection (Py::Object arg)
setter for the Direction attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Axis * getAxisPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getBase (PyObject *self, void *closure)
getter callback for the Base attribute
static int staticCallback_setBase (PyObject *self, PyObject *value, void *closure)
setter callback for the Base attribute
static PyObject * staticCallback_getDirection (PyObject *self, void *closure)
getter callback for the Direction attribute
static int staticCallback_setDirection (PyObject *self, PyObject *value, void *closure)
setter callback for the Direction attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Axis.
Member Typedef Documentation
PointerType
typedef Axis* Base::AxisPy::PointerType
Constructor & Destructor Documentation
~AxisPy()
AxisPy::~AxisPy () protected
AxisPy()
AxisPy::AxisPy (Axis * pcObject, PyTypeObject * T = &Type)
Referenced by copy(), multiply(), PyMake(), and reversed().
Member Function Documentation
copy()
PyObject * AxisPy::copy (PyObject * args)
implementer for the copy() method
References AxisPy(), and getAxisPtr().
Referenced by staticCallback_copy().
getAxisPtr()
Axis * AxisPy::getAxisPtr (void) const
getter for the object handled by this class
Referenced by copy(), getBase(), getDirection(), move(), multiply(), PyInit(), reversed(), Base::CoordinateSystemPy::setAxis(), setBase(), and setDirection().
getBase()
Py::Object AxisPy::getBase (void) const
getter for the Base attribute
References getAxisPtr().
Referenced by staticCallback_getBase().
getCustomAttributes()
PyObject * AxisPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getDirection()
Py::Object AxisPy::getDirection (void) const
getter for the Direction attribute
References getAxisPtr().
Referenced by staticCallback_getDirection().
GetType()
virtual PyTypeObject* Base::AxisPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
move()
PyObject * AxisPy::move (PyObject * args)
implementer for the move() method
References getAxisPtr(), Base::Axis::move(), Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by draftguitools.gui_circulararray.CircularArray::Activated(), draftguitools.gui_polararray.PolarArray::Activated(), and staticCallback_move().
multiply()
PyObject * AxisPy::multiply (PyObject * args)
implementer for the multiply() method
References AxisPy(), getAxisPtr(), Base::PlacementPy::getPlacementPtr(), and Base::PlacementPy::Type.
Referenced by PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart(), and staticCallback_multiply().
PyInit()
int AxisPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
References Base::BaseExceptionFreeCADError, getAxisPtr(), Type, and Base::VectorPy::Type.
PyMake()
PyObject * AxisPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References AxisPy().
representation()
std::string AxisPy::representation (void) const
References Base::Axis::getBase(), Base::Axis::getDirection(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
reversed()
PyObject * AxisPy::reversed (PyObject * args)
implementer for the reversed() method
References AxisPy(), getAxisPtr(), and Base::Axis::reversed().
Referenced by staticCallback_reversed().
setBase()
void AxisPy::setBase (Py::Object arg)
setter for the Base attribute
References getAxisPtr(), Base::Axis::setBase(), and Base::toVector().
Referenced by staticCallback_setBase().
setCustomAttributes()
int AxisPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setDirection()
void AxisPy::setDirection (Py::Object arg)
setter for the Direction attribute
References getAxisPtr(), Base::Axis::setDirection(), and Base::toVector().
Referenced by staticCallback_setDirection().
staticCallback_copy()
PyObject * AxisPy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copy(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_getBase()
PyObject * AxisPy::staticCallback_getBase (PyObject * self, void * closure) static
getter callback for the Base attribute
References Base::BaseExceptionFreeCADError, getBase(), and Base::PyObjectBase::isValid().
staticCallback_getDirection()
PyObject * AxisPy::staticCallback_getDirection (PyObject * self, void * closure) static
getter callback for the Direction attribute
References Base::BaseExceptionFreeCADError, getDirection(), and Base::PyObjectBase::isValid().
staticCallback_move()
PyObject * AxisPy::staticCallback_move (PyObject * self, PyObject * args) static
callback for the move() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), move(), and Base::PyObjectBase::startNotify().
staticCallback_multiply()
PyObject * AxisPy::staticCallback_multiply (PyObject * self, PyObject * args) static
callback for the multiply() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), multiply(), and Base::PyObjectBase::startNotify().
staticCallback_reversed()
PyObject * AxisPy::staticCallback_reversed (PyObject * self, PyObject * args) static
callback for the reversed() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), reversed(), and Base::PyObjectBase::startNotify().
staticCallback_setBase()
int AxisPy::staticCallback_setBase (PyObject * self, PyObject * value, void * closure) static
setter callback for the Base attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setBase().
staticCallback_setDirection()
int AxisPy::staticCallback_setDirection (PyObject * self, PyObject * value, void * closure) static
setter callback for the Direction attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setDirection().
Member Data Documentation
GetterSetter
PyGetSetDef AxisPy::GetterSetter static
Initial value:
= {
    {"Base",
        (getter) staticCallback_getBase,
        (setter) staticCallback_setBase,
        "Vector to the Base position of the Axis",
        NULL
    },
    {"Direction",
        (getter) staticCallback_getDirection,
        (setter) staticCallback_setDirection,
        "Direction vector of the Axis",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of AxisPy.
Methods
PyMethodDef AxisPy::Methods static
Initial value:
= {
    {"copy",
        reinterpret_cast<PyCFunction>( staticCallback_copy ),
        METH_VARARGS,
        "\n                    copy()\n                    Returns a copy of this Axis\n                "
    },
    {"move",
        reinterpret_cast<PyCFunction>( staticCallback_move ),
        METH_VARARGS,
        "\n                                     move(Vector)\n                                  Move the axis base along the vector\n                           "
    },
    {"multiply",
        reinterpret_cast<PyCFunction>( staticCallback_multiply ),
        METH_VARARGS,
        "\n                                     multiply(Placement)\n                                   Multiply this axis with a placement\n                           "
    },
    {"reversed",
        reinterpret_cast<PyCFunction>( staticCallback_reversed ),
        METH_VARARGS,
        "\n                                     reversed() -> Axis\n                                    compute the reversed axis\n                             "
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of AxisPy.
Type
PyTypeObject AxisPy::Type static
Type structure of AxisPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), PyInit(), draftobjects.layer.Layer::set_properties(), Base::CoordinateSystemPy::setAxes(), Base::CoordinateSystemPy::setAxis(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Base/AxisPy.h
Sources/FreeCAD/src/Base/AxisPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Base/AxisPy.cpp