FreeCAD: App::GeoFeatureGroupExtensionPy Class Reference
App::GeoFeatureGroupExtensionPy Class Reference
The python export class for GeoFeatureGroupExtension.
#include <GeoFeatureGroupExtensionPy.h>
Public Types
typedef GeoFeatureGroupExtension * PointerType
Public Types inherited from App::GroupExtensionPy
typedef GroupExtension * PointerType
Public Types inherited from App::DocumentObjectExtensionPy
typedef DocumentObjectExtension * PointerType
Public Types inherited from App::ExtensionPy
typedef Extension * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
GeoFeatureGroupExtensionPy (GeoFeatureGroupExtension *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeoFeatureGroupExtension * getGeoFeatureGroupExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from App::GroupExtensionPy
GroupExtensionPy (GroupExtension *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GroupExtension * getGroupExtensionPtr (void) const
getter for the object handled by this class
PyObject * newObject (PyObject *args)
implementer for the newObject() method
PyObject * addObject (PyObject *args)
implementer for the addObject() method
PyObject * addObjects (PyObject *args)
implementer for the addObjects() method
PyObject * setObjects (PyObject *args)
implementer for the setObjects() method
PyObject * removeObject (PyObject *args)
implementer for the removeObject() method
PyObject * removeObjects (PyObject *args)
implementer for the removeObjects() method
PyObject * removeObjectsFromDocument (PyObject *args)
implementer for the removeObjectsFromDocument() method
PyObject * getObject (PyObject *args)
implementer for the getObject() method
PyObject * hasObject (PyObject *args)
implementer for the hasObject() method
Public Member Functions inherited from App::DocumentObjectExtensionPy
DocumentObjectExtensionPy (DocumentObjectExtension *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
DocumentObjectExtension * getDocumentObjectExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from App::ExtensionPy
ExtensionPy (Extension *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Extension * getExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::GroupExtensionPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_newObject (PyObject *self, PyObject *args)
callback for the newObject() method
static PyObject * staticCallback_addObject (PyObject *self, PyObject *args)
callback for the addObject() method
static PyObject * staticCallback_addObjects (PyObject *self, PyObject *args)
callback for the addObjects() method
static PyObject * staticCallback_setObjects (PyObject *self, PyObject *args)
callback for the setObjects() method
static PyObject * staticCallback_removeObject (PyObject *self, PyObject *args)
callback for the removeObject() method
static PyObject * staticCallback_removeObjects (PyObject *self, PyObject *args)
callback for the removeObjects() method
static PyObject * staticCallback_removeObjectsFromDocument (PyObject *self, PyObject *args)
callback for the removeObjectsFromDocument() method
static PyObject * staticCallback_getObject (PyObject *self, PyObject *args)
callback for the getObject() method
static PyObject * staticCallback_hasObject (PyObject *self, PyObject *args)
callback for the hasObject() method
Static Public Member Functions inherited from App::DocumentObjectExtensionPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::ExtensionPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of GeoFeatureGroupExtensionPy.
static PyMethodDef Methods []
Methods structure of GeoFeatureGroupExtensionPy.
static PyTypeObject Type
Type structure of GeoFeatureGroupExtensionPy.
Static Public Attributes inherited from App::GroupExtensionPy
static PyGetSetDef GetterSetter []
Attribute structure of GroupExtensionPy.
static PyMethodDef Methods []
Methods structure of GroupExtensionPy.
static PyTypeObject Type
Type structure of GroupExtensionPy.
Static Public Attributes inherited from App::DocumentObjectExtensionPy
static PyGetSetDef GetterSetter []
Attribute structure of DocumentObjectExtensionPy.
static PyMethodDef Methods []
Methods structure of DocumentObjectExtensionPy.
static PyTypeObject Type
Type structure of DocumentObjectExtensionPy.
Static Public Attributes inherited from App::ExtensionPy
static PyGetSetDef GetterSetter []
Attribute structure of ExtensionPy.
static PyMethodDef Methods []
Methods structure of ExtensionPy.
static PyTypeObject Type
Type structure of ExtensionPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~GeoFeatureGroupExtensionPy ()
Protected Member Functions inherited from App::GroupExtensionPy
~GroupExtensionPy ()
Protected Member Functions inherited from App::DocumentObjectExtensionPy
~DocumentObjectExtensionPy ()
Protected Member Functions inherited from App::ExtensionPy
~ExtensionPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeoFeatureGroupExtension.
Member Typedef Documentation
PointerType
typedef GeoFeatureGroupExtension* App::GeoFeatureGroupExtensionPy::PointerType
Constructor & Destructor Documentation
~GeoFeatureGroupExtensionPy()
GeoFeatureGroupExtensionPy::~GeoFeatureGroupExtensionPy () protected
GeoFeatureGroupExtensionPy()
GeoFeatureGroupExtensionPy::GeoFeatureGroupExtensionPy (GeoFeatureGroupExtension * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
getCustomAttributes()
PyObject * GeoFeatureGroupExtensionPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getGeoFeatureGroupExtensionPtr()
GeoFeatureGroupExtension * GeoFeatureGroupExtensionPy::getGeoFeatureGroupExtensionPtr (void) const
getter for the object handled by this class
GetType()
virtual PyTypeObject* App::GeoFeatureGroupExtensionPy::GetType (void) virtual
Reimplemented from App::GroupExtensionPy.
Reimplemented in App::OriginGroupExtensionPy.
PyInit()
int GeoFeatureGroupExtensionPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from App::GroupExtensionPy.
Reimplemented in App::OriginGroupExtensionPy.
PyMake()
PyObject * GeoFeatureGroupExtensionPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string GeoFeatureGroupExtensionPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int GeoFeatureGroupExtensionPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
Member Data Documentation
GetterSetter
PyGetSetDef GeoFeatureGroupExtensionPy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of GeoFeatureGroupExtensionPy.
Methods
PyMethodDef GeoFeatureGroupExtensionPy::Methods static
Initial value:
= {
    {NULL, NULL, 0, NULL}
}
Methods structure of GeoFeatureGroupExtensionPy.
Type
PyTypeObject GeoFeatureGroupExtensionPy::Type static
Type structure of GeoFeatureGroupExtensionPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/App/GeoFeatureGroupExtensionPy.h
Sources/FreeCAD/src/App/GeoFeatureGroupExtensionPyImp.cpp
Sources/FreeCAD-SourceDocs/src/App/GeoFeatureGroupExtensionPy.cpp