FreeCAD: Part::Curve2dPy Class Reference
Part::Curve2dPy Class Reference
The python export class for Geom2dCurve.
#include <Curve2dPy.h>
Public Types
typedef Geom2dCurve * PointerType
Public Types inherited from Part::Geometry2dPy
typedef Geometry2d * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
Curve2dPy (Geom2dCurve *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Part::Geometry2dPy
Geometry2dPy (Geometry2d *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geometry2d * getGeometry2dPtr (void) const
getter for the object handled by this class
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * copy (PyObject *args)
implementer for the copy() method
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::Geometry2dPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of Curve2dPy.
static PyMethodDef Methods []
Methods structure of Curve2dPy.
static PyTypeObject Type
Type structure of Curve2dPy.
Static Public Attributes inherited from Part::Geometry2dPy
static PyGetSetDef GetterSetter []
Attribute structure of Geometry2dPy.
static PyMethodDef Methods []
Methods structure of Geometry2dPy.
static PyTypeObject Type
Type structure of Geometry2dPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~Curve2dPy ()
Protected Member Functions inherited from Part::Geometry2dPy
~Geometry2dPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * reverse (PyObject *args)
implementer for the reverse() method
PyObject * toShape (PyObject *args)
implementer for the toShape() method
PyObject * discretize (PyObject *args, PyObject *kwd)
implementer for the discretize() method
PyObject * length (PyObject *args)
implementer for the length() method
PyObject * parameterAtDistance (PyObject *args)
implementer for the parameterAtDistance() method
PyObject * value (PyObject *args)
implementer for the value() method
PyObject * tangent (PyObject *args)
implementer for the tangent() method
PyObject * parameter (PyObject *args)
implementer for the parameter() method
PyObject * normal (PyObject *args)
implementer for the normal() method
PyObject * curvature (PyObject *args)
implementer for the curvature() method
PyObject * centerOfCurvature (PyObject *args)
implementer for the centerOfCurvature() method
PyObject * intersectCC (PyObject *args)
implementer for the intersectCC() method
PyObject * toBSpline (PyObject *args)
implementer for the toBSpline() method
PyObject * approximateBSpline (PyObject *args)
implementer for the approximateBSpline() method
static PyObject * staticCallback_reverse (PyObject *self, PyObject *args)
callback for the reverse() method
static PyObject * staticCallback_toShape (PyObject *self, PyObject *args)
callback for the toShape() method
static PyObject * staticCallback_discretize (PyObject *self, PyObject *args, PyObject *kwd)
callback for the discretize() method
static PyObject * staticCallback_length (PyObject *self, PyObject *args)
callback for the length() method
static PyObject * staticCallback_parameterAtDistance (PyObject *self, PyObject *args)
callback for the parameterAtDistance() method
static PyObject * staticCallback_value (PyObject *self, PyObject *args)
callback for the value() method
static PyObject * staticCallback_tangent (PyObject *self, PyObject *args)
callback for the tangent() method
static PyObject * staticCallback_parameter (PyObject *self, PyObject *args)
callback for the parameter() method
static PyObject * staticCallback_normal (PyObject *self, PyObject *args)
callback for the normal() method
static PyObject * staticCallback_curvature (PyObject *self, PyObject *args)
callback for the curvature() method
static PyObject * staticCallback_centerOfCurvature (PyObject *self, PyObject *args)
callback for the centerOfCurvature() method
static PyObject * staticCallback_intersectCC (PyObject *self, PyObject *args)
callback for the intersectCC() method
static PyObject * staticCallback_toBSpline (PyObject *self, PyObject *args)
callback for the toBSpline() method
static PyObject * staticCallback_approximateBSpline (PyObject *self, PyObject *args)
callback for the approximateBSpline() method
callbacks and implementers for the python object attributes
Py::String getContinuity (void) const
getter for the Continuity attribute
Py::Boolean getClosed (void) const
getter for the Closed attribute
Py::Boolean getPeriodic (void) const
getter for the Periodic attribute
Py::Float getFirstParameter (void) const
getter for the FirstParameter attribute
Py::Float getLastParameter (void) const
getter for the LastParameter attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geom2dCurve * getGeom2dCurvePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getContinuity (PyObject *self, void *closure)
getter callback for the Continuity attribute
static int staticCallback_setContinuity (PyObject *self, PyObject *value, void *closure)
setter callback for the Continuity attribute
static PyObject * staticCallback_getClosed (PyObject *self, void *closure)
getter callback for the Closed attribute
static int staticCallback_setClosed (PyObject *self, PyObject *value, void *closure)
setter callback for the Closed attribute
static PyObject * staticCallback_getPeriodic (PyObject *self, void *closure)
getter callback for the Periodic attribute
static int staticCallback_setPeriodic (PyObject *self, PyObject *value, void *closure)
setter callback for the Periodic attribute
static PyObject * staticCallback_getFirstParameter (PyObject *self, void *closure)
getter callback for the FirstParameter attribute
static int staticCallback_setFirstParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the FirstParameter attribute
static PyObject * staticCallback_getLastParameter (PyObject *self, void *closure)
getter callback for the LastParameter attribute
static int staticCallback_setLastParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the LastParameter attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Geom2dCurve.
Member Typedef Documentation
PointerType
typedef Geom2dCurve* Part::Curve2dPy::PointerType
Constructor & Destructor Documentation
~Curve2dPy()
Curve2dPy::~Curve2dPy () protected
Curve2dPy()
Curve2dPy::Curve2dPy (Geom2dCurve * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
approximateBSpline()
PyObject * Curve2dPy::approximateBSpline (PyObject * args)
implementer for the approximateBSpline() method
References Part::Geometry2dPy::getGeometry2dPtr(), Part::PartExceptionOCCError, and draftutils.utils::tolerance().
Referenced by staticCallback_approximateBSpline().
centerOfCurvature()
PyObject * Curve2dPy::centerOfCurvature (PyObject * args)
implementer for the centerOfCurvature() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_centerOfCurvature().
curvature()
PyObject * Curve2dPy::curvature (PyObject * args)
implementer for the curvature() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by discretize(), and staticCallback_curvature().
discretize()
PyObject * Curve2dPy::discretize (PyObject * args, PyObject * kwd)
implementer for the discretize() method
References curvature(), Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_discretize().
getClosed()
Py::Boolean Curve2dPy::getClosed (void) const
getter for the Closed attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getClosed().
getContinuity()
Py::String Curve2dPy::getContinuity (void) const
getter for the Continuity attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getContinuity().
getCustomAttributes()
PyObject * Curve2dPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getFirstParameter()
Py::Float Curve2dPy::getFirstParameter (void) const
getter for the FirstParameter attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getFirstParameter().
getGeom2dCurvePtr()
Geom2dCurve * Curve2dPy::getGeom2dCurvePtr (void) const
getter for the object handled by this class
Referenced by reverse().
getLastParameter()
Py::Float Curve2dPy::getLastParameter (void) const
getter for the LastParameter attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getLastParameter().
getPeriodic()
Py::Boolean Curve2dPy::getPeriodic (void) const
getter for the Periodic attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getPeriodic().
GetType()
virtual PyTypeObject* Part::Curve2dPy::GetType (void) virtual
Reimplemented from Part::Geometry2dPy.
Reimplemented in Part::Parabola2dPy, Part::OffsetCurve2dPy, Part::Line2dSegmentPy, Part::Line2dPy, Part::Hyperbola2dPy, Part::Ellipse2dPy, Part::Conic2dPy, Part::Circle2dPy, Part::BSplineCurve2dPy, Part::BezierCurve2dPy, Part::ArcOfParabola2dPy, Part::ArcOfHyperbola2dPy, Part::ArcOfEllipse2dPy, Part::ArcOfConic2dPy, and Part::ArcOfCircle2dPy.
intersectCC()
PyObject * Curve2dPy::intersectCC (PyObject * args)
implementer for the intersectCC() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Type.
Referenced by staticCallback_intersectCC().
length()
PyObject * Curve2dPy::length (PyObject * args)
implementer for the length() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_length().
normal()
PyObject * Curve2dPy::normal (PyObject * args)
implementer for the normal() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_normal().
parameter()
PyObject * Curve2dPy::parameter (PyObject * args)
implementer for the parameter() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by Part::BSplineCurve2dPy::getCardinalSplineTangents(), and staticCallback_parameter().
parameterAtDistance()
PyObject * Curve2dPy::parameterAtDistance (PyObject * args)
implementer for the parameterAtDistance() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_parameterAtDistance().
PyInit()
int Curve2dPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::Geometry2dPy.
Reimplemented in Part::Parabola2dPy, Part::OffsetCurve2dPy, Part::Line2dSegmentPy, Part::Line2dPy, Part::Hyperbola2dPy, Part::Ellipse2dPy, Part::Conic2dPy, Part::Circle2dPy, Part::BSplineCurve2dPy, Part::BezierCurve2dPy, Part::ArcOfParabola2dPy, Part::ArcOfHyperbola2dPy, Part::ArcOfEllipse2dPy, Part::ArcOfConic2dPy, and Part::ArcOfCircle2dPy.
PyMake()
PyObject * Curve2dPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string Curve2dPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
reverse()
PyObject * Curve2dPy::reverse (PyObject * args)
implementer for the reverse() method
References getGeom2dCurvePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_reverse().
setCustomAttributes()
int Curve2dPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_approximateBSpline()
PyObject * Curve2dPy::staticCallback_approximateBSpline (PyObject * self, PyObject * args) static
callback for the approximateBSpline() method
References approximateBSpline(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_centerOfCurvature()
PyObject * Curve2dPy::staticCallback_centerOfCurvature (PyObject * self, PyObject * args) static
callback for the centerOfCurvature() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, centerOfCurvature(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_curvature()
PyObject * Curve2dPy::staticCallback_curvature (PyObject * self, PyObject * args) static
callback for the curvature() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, curvature(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_discretize()
PyObject * Curve2dPy::staticCallback_discretize (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the discretize() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, discretize(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getClosed()
PyObject * Curve2dPy::staticCallback_getClosed (PyObject * self, void * closure) static
getter callback for the Closed attribute
References Base::BaseExceptionFreeCADError, getClosed(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getContinuity()
PyObject * Curve2dPy::staticCallback_getContinuity (PyObject * self, void * closure) static
getter callback for the Continuity attribute
References Base::BaseExceptionFreeCADError, getContinuity(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFirstParameter()
PyObject * Curve2dPy::staticCallback_getFirstParameter (PyObject * self, void * closure) static
getter callback for the FirstParameter attribute
References Base::BaseExceptionFreeCADError, getFirstParameter(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getLastParameter()
PyObject * Curve2dPy::staticCallback_getLastParameter (PyObject * self, void * closure) static
getter callback for the LastParameter attribute
References Base::BaseExceptionFreeCADError, getLastParameter(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPeriodic()
PyObject * Curve2dPy::staticCallback_getPeriodic (PyObject * self, void * closure) static
getter callback for the Periodic attribute
References Base::BaseExceptionFreeCADError, getPeriodic(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_intersectCC()
PyObject * Curve2dPy::staticCallback_intersectCC (PyObject * self, PyObject * args) static
callback for the intersectCC() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, intersectCC(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_length()
PyObject * Curve2dPy::staticCallback_length (PyObject * self, PyObject * args) static
callback for the length() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), length(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_normal()
PyObject * Curve2dPy::staticCallback_normal (PyObject * self, PyObject * args) static
callback for the normal() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), normal(), and Base::PyObjectBase::PyObjectBase().
staticCallback_parameter()
PyObject * Curve2dPy::staticCallback_parameter (PyObject * self, PyObject * args) static
callback for the parameter() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), parameter(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_parameterAtDistance()
PyObject * Curve2dPy::staticCallback_parameterAtDistance (PyObject * self, PyObject * args) static
callback for the parameterAtDistance() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), parameterAtDistance(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_reverse()
PyObject * Curve2dPy::staticCallback_reverse (PyObject * self, PyObject * args) static
callback for the reverse() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), reverse(), and Base::PyObjectBase::startNotify().
staticCallback_setClosed()
int Curve2dPy::staticCallback_setClosed (PyObject * self, PyObject * value, void * closure) static
setter callback for the Closed attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setContinuity()
int Curve2dPy::staticCallback_setContinuity (PyObject * self, PyObject * value, void * closure) static
setter callback for the Continuity attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setFirstParameter()
int Curve2dPy::staticCallback_setFirstParameter (PyObject * self, PyObject * value, void * closure) static
setter callback for the FirstParameter attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setLastParameter()
int Curve2dPy::staticCallback_setLastParameter (PyObject * self, PyObject * value, void * closure) static
setter callback for the LastParameter attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPeriodic()
int Curve2dPy::staticCallback_setPeriodic (PyObject * self, PyObject * value, void * closure) static
setter callback for the Periodic attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_tangent()
PyObject * Curve2dPy::staticCallback_tangent (PyObject * self, PyObject * args) static
callback for the tangent() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and tangent().
staticCallback_toBSpline()
PyObject * Curve2dPy::staticCallback_toBSpline (PyObject * self, PyObject * args) static
callback for the toBSpline() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and toBSpline().
staticCallback_toShape()
PyObject * Curve2dPy::staticCallback_toShape (PyObject * self, PyObject * args) static
callback for the toShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and toShape().
staticCallback_value()
PyObject * Curve2dPy::staticCallback_value (PyObject * self, PyObject * args) static
callback for the value() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and value().
tangent()
PyObject * Curve2dPy::tangent (PyObject * args)
implementer for the tangent() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_tangent().
toBSpline()
PyObject * Curve2dPy::toBSpline (PyObject * args)
implementer for the toBSpline() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_toBSpline().
toShape()
PyObject * Curve2dPy::toShape (PyObject * args)
implementer for the toShape() method
References Part::create3dCurve(), Part::Geometry2dPy::getGeometry2dPtr(), Part::PartExceptionOCCError, Part::shape2pyshape(), Part::GeometrySurfacePy::Type, and Part::TopoShapeFacePy::Type.
Referenced by staticCallback_toShape().
value()
PyObject * Curve2dPy::value (PyObject * args)
implementer for the value() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_value().
Member Data Documentation
GetterSetter
PyGetSetDef Curve2dPy::GetterSetter static
Attribute structure of Curve2dPy.
Methods
PyMethodDef Curve2dPy::Methods static
Methods structure of Curve2dPy.
Type
PyTypeObject Curve2dPy::Type static
Type structure of Curve2dPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), intersectCC(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), Part::OffsetCurve2dPy::PyInit(), Part::OffsetCurve2dPy::setBasisCurve(), Part::CurveConstraintPy::setCurve2dOnSurf(), and Part::CurveConstraintPy::setProjectedCurve().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/Geom2d/Curve2dPy.h
Sources/FreeCAD/src/Mod/Part/App/Geom2d/Curve2dPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/Geom2d/Curve2dPy.cpp