FreeCAD: Gui::SequencerBar Class Reference
Gui::SequencerBar Class Reference
FreeCAD's progress bar for long operations To see how to use the progress bar have a look at the following examples:
#include <ProgressBar.h>
Public Member Functions
virtual void checkAbort () override
Check if the operation is aborted by user.
QProgressBar * getProgressBar (QWidget *parent=0)
Returns an instance of the progress bar.
bool isBlocking () const override
Returns true if the running sequencer is blocking any user input.
void pause () override
This restores the last overridden cursor and release the keyboard while the progress bar is running.
void resume () override
This sets the wait cursor again and grabs the keyboard.
Public Member Functions inherited from Base::SequencerBase
bool isLocked () const
Returns true if the sequencer was locked, false otherwise.
bool isRunning () const
Returns true if the sequencer is running, otherwise returns false.
bool setLocked (bool bLock)
If bLock is true then the sequencer gets locked.
bool wasCanceled () const
Returns true if the pending operation was canceled.
Static Public Member Functions
static SequencerBar * instance ()
Returns the sequencer object.
Static Public Member Functions inherited from Base::SequencerBase
static SequencerBase & Instance ()
Returns the last created sequencer instance.
Protected Member Functions
void nextStep (bool canAbort) override
Increase the progress bar.
void resetData () override
Resets the sequencer.
SequencerBar ()
Construction.
void setProgress (size_t) override
Sets the progress indicator to a certain position.
void setText (const char *pszTxt) override
Puts text to the status bar.
void showRemainingTime ()
void startStep () override
Starts the progress bar.
~SequencerBar ()
Destruction.
Protected Member Functions inherited from Base::SequencerBase
bool next (bool canAbort=false)
Performs the next step and returns true if the operation is not yet finished.
size_t numberOfSteps () const
Returns the number of steps.
int progressInPercent () const
Returns the current state of progress in percent.
void rejectCancel ()
If you tried to cancel but then decided to continue the operation.
SequencerBase ()
construction
bool start (const char *pszStr, size_t steps)
Starts a new operation, returns false if there is already a pending operation, otherwise it returns true.
bool stop ()
Stops the sequencer if all operations are finished.
void tryToCancel ()
Try to cancel the pending operation(s).
virtual ~SequencerBase ()
Destruction.
for internal use only
class ProgressBar
Additional Inherited Members
Protected Attributes inherited from Base::SequencerBase
size_t nProgress
Stores the current amount of progress.
size_t nTotalSteps
Stores the total number of steps.
Detailed Description
FreeCAD's progress bar for long operations To see how to use the progress bar have a look at the following examples:
unsigned long steps = ...
Base::SequencerLauncher seq("Starting progress bar", 0);
for (unsigned long i=0; i<steps;i++)
{
  seq.next();
  // do one step of your algorithm
}
The example below shows how to use two nested progresses.
void function1()
{
  unsigned long steps = ...
  Base::SequencerLauncger seq("Starting progress bar", 0);
  for (unsigned long i=0; i<steps;i++)
  {
    seq.next();
    // do one step of your algorithm
  }
}
void function2()
{
  unsigned long steps = ...
  Base::SequencerLauncher seq("Starting progress bar", 0);
  for (unsigned long i=0; i<steps;i++)
  {
    seq.next();
    // do one step of your algorithm calling function1
    function1();
  }
}
If the total number of steps cannot be determined before, use 0 instead of to show just a busy indicator instead of percentage steps.
Author
Werner Mayer
Constructor & Destructor Documentation
SequencerBar()
SequencerBar::SequencerBar () protected
Construction.
References Gui::SequencerBarPrivate::bar, Gui::SequencerBarPrivate::guiThread, and Gui::SequencerBarPrivate::waitCursor.
Referenced by instance().
~SequencerBar()
SequencerBar::~SequencerBar () protected
Destruction.
Member Function Documentation
checkAbort()
void SequencerBar::checkAbort () override virtual
Check if the operation is aborted by user.
Reimplemented from Base::SequencerBase.
References Gui::SequencerBarPrivate::bar, Gui::ProgressBar::canAbort(), Gui::SequencerBarPrivate::checkAbortTime, pause(), Base::SequencerBase::rejectCancel(), resume(), and Base::SequencerBase::wasCanceled().
getProgressBar()
QProgressBar * SequencerBar::getProgressBar (QWidget * parent = 0)
Returns an instance of the progress bar.
It creates one if needed.
References Gui::SequencerBarPrivate::bar, and ProgressBar.
Referenced by Gui::MainWindow::MainWindow(), WebGui::BrowserView::onLoadProgress(), and WebGui::BrowserView::onLoadStarted().
instance()
SequencerBar * SequencerBar::instance (void) static
Returns the sequencer object.
References SequencerBar().
Referenced by Gui::MainWindow::MainWindow(), WebGui::BrowserView::onLoadProgress(), and WebGui::BrowserView::onLoadStarted().
isBlocking()
bool SequencerBar::isBlocking () const override virtual
Returns true if the running sequencer is blocking any user input.
This might be only of interest of the GUI where the progress bar or dialog is used from a thread. If started from a thread this method should return false, otherwise true. The default implementation always returns true.
Reimplemented from Base::SequencerBase.
References Gui::SequencerBarPrivate::guiThread.
nextStep()
void SequencerBar::nextStep (bool canAbort) override protected virtual
Increase the progress bar.
Reimplemented from Base::SequencerBase.
References Gui::SequencerBarPrivate::bar, Gui::ProgressBar::canAbort(), Base::SequencerBase::nProgress, pause(), Base::SequencerBase::rejectCancel(), resume(), and Base::SequencerBase::wasCanceled().
pause()
void SequencerBar::pause () override virtual
This restores the last overridden cursor and release the keyboard while the progress bar is running.
This is useful e.g. if a modal dialog appears while a long operation is performed to indicate that the user can click on the dialog. Every pause() must eventually be followed by a corresponding resume().
Reimplemented from Base::SequencerBase.
References Gui::SequencerBarPrivate::bar, Gui::SequencerBarPrivate::guiThread, Gui::WaitCursor::restoreCursor(), and Gui::SequencerBarPrivate::waitCursor.
Referenced by checkAbort(), and nextStep().
resetData()
void SequencerBar::resetData () override protected virtual
Resets the sequencer.
Reimplemented from Base::SequencerBase.
References Gui::ProgressBar::aboutToHide(), Gui::SequencerBarPrivate::bar, Gui::getMainWindow(), Gui::SequencerBarPrivate::guiThread, Gui::MainWindow::setPaneText(), Gui::MainWindow::showMessage(), and Gui::SequencerBarPrivate::waitCursor.
Referenced by Gui::ProgressBar::eventFilter().
resume()
void SequencerBar::resume () override virtual
This sets the wait cursor again and grabs the keyboard.
See also
pause()
Reimplemented from Base::SequencerBase.
References Gui::SequencerBarPrivate::bar, Gui::SequencerBarPrivate::guiThread, Gui::WaitCursor::setWaitCursor(), and Gui::SequencerBarPrivate::waitCursor.
Referenced by checkAbort(), and nextStep().
setProgress()
void SequencerBar::setProgress (size_t step) override protected virtual
Sets the progress indicator to a certain position.
Reimplemented from Base::SequencerBase.
References Gui::SequencerBarPrivate::bar.
setText()
void SequencerBar::setText (const char * pszTxt) override protected virtual
Puts text to the status bar.
Reimplemented from Base::SequencerBase.
References Gui::SequencerBarPrivate::bar, Gui::getMainWindow(), Gui::MainWindow::showMessage(), and Gui::SequencerBarPrivate::text.
showRemainingTime()
void SequencerBar::showRemainingTime () protected
References Gui::SequencerBarPrivate::bar, Gui::getMainWindow(), Gui::SequencerBarPrivate::measureTime, Gui::MainWindow::showMessage(), and Gui::SequencerBarPrivate::text.
startStep()
void SequencerBar::startStep () override protected virtual
Starts the progress bar.
Reimplemented from Base::SequencerBase.
References Gui::ProgressBar::aboutToShow(), Gui::SequencerBarPrivate::bar, Gui::SequencerBarPrivate::checkAbortTime, Gui::SequencerBarPrivate::guiThread, Gui::SequencerBarPrivate::measureTime, Base::SequencerBase::nTotalSteps, Gui::SequencerBarPrivate::progressTime, and Gui::SequencerBarPrivate::waitCursor.
Friends And Related Function Documentation
ProgressBar
friend class ProgressBar friend
Referenced by getProgressBar().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/ProgressBar.h
Sources/FreeCAD/src/Gui/ProgressBar.cpp