FreeCAD: MeshGui::SoFCIndexedFaceSet Class Reference
MeshGui::SoFCIndexedFaceSet Class Reference
class SoFCIndexedFaceSet
#include <SoFCIndexedFaceSet.h>
Public Member Functions
void invalidate ()
SoFCIndexedFaceSet ()
Static Public Member Functions
static void initClass ()
Public Attributes
unsigned int renderTriangleLimit
SoSFBool updateGLArray
Protected Member Functions
void doAction (SoAction *action)
void drawCoords (const SoGLCoordinateElement *const vertexlist, const int32_t *vertexindices, int numindices, const SbVec3f *normals, const int32_t *normalindices, SoMaterialBundle *materials, const int32_t *matindices, const int32_t binding, const SoTextureCoordinateBundle *const texcoords, const int32_t *texindices)
void drawFaces (SoGLRenderAction *action)
virtual void GLRender (SoGLRenderAction *action)
Either renders the complete mesh or only a subset of the points.
virtual ~SoFCIndexedFaceSet ()
Detailed Description
class SoFCIndexedFaceSet
The SoFCIndexedFaceSet class is designed to optimize redrawing a mesh during user interaction.
Author
Werner Mayer
Constructor & Destructor Documentation
SoFCIndexedFaceSet()
SoFCIndexedFaceSet::SoFCIndexedFaceSet ()
References updateGLArray.
~SoFCIndexedFaceSet()
virtual MeshGui::SoFCIndexedFaceSet::~SoFCIndexedFaceSet () protected virtual
Member Function Documentation
doAction()
void SoFCIndexedFaceSet::doAction (SoAction * action) protected
drawCoords()
void SoFCIndexedFaceSet::drawCoords (const SoGLCoordinateElement *const vertexlist, const int32_t * vertexindices, int numindices, const SbVec3f * normals, const int32_t * normalindices, SoMaterialBundle * materials, const int32_t * matindices, const int32_t binding, const SoTextureCoordinateBundle *const texcoords, const int32_t * texindices) protected
References renderTriangleLimit, and draftgeoutils.general::v1().
Referenced by drawFaces().
drawFaces()
void SoFCIndexedFaceSet::drawFaces (SoGLRenderAction * action) protected
References MeshGui::MeshRenderer::canRenderGLArray(), drawCoords(), Gui::SoFCInteractiveElement::get(), MeshGui::MeshRenderer::renderCoordsGLArray(), MeshGui::MeshRenderer::renderFacesGLArray(), renderTriangleLimit, and updateGLArray.
Referenced by GLRender().
GLRender()
void SoFCIndexedFaceSet::GLRender (SoGLRenderAction * action) protected virtual
Either renders the complete mesh or only a subset of the points.
References MeshGui::MeshRenderer::canRenderGLArray(), drawFaces(), Gui::SoGLVBOActivatedElement::get(), MeshGui::MeshRenderer::matchMaterial(), MeshGui::MeshRenderer::needUpdate(), MeshGui::MeshRenderer::renderFacesGLArray(), MeshGui::MeshRenderer::update(), and updateGLArray.
initClass()
void SoFCIndexedFaceSet::initClass (void) static
invalidate()
void SoFCIndexedFaceSet::invalidate ()
References updateGLArray.
Referenced by MeshGui::ViewProviderMeshFaceSet::updateData().
Member Data Documentation
renderTriangleLimit
unsigned int MeshGui::SoFCIndexedFaceSet::renderTriangleLimit
Referenced by drawCoords(), and drawFaces().
updateGLArray
SoSFBool MeshGui::SoFCIndexedFaceSet::updateGLArray
Referenced by drawFaces(), GLRender(), invalidate(), and SoFCIndexedFaceSet().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCIndexedFaceSet.h
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCIndexedFaceSet.cpp