FreeCAD: MeshGui::DlgSmoothing Class Reference
MeshGui::DlgSmoothing Class Reference
#include <DlgSmoothing.h>
Public Types
enum Smooth { }
Signals
void toggledSelection (bool)
Public Member Functions
DlgSmoothing (QWidget *parent=nullptr)
int iterations () const
double lambdaStep () const
Smooth method () const
double microStep () const
bool smoothSelection () const
~DlgSmoothing ()
Member Enumeration Documentation
Smooth
enum MeshGui::DlgSmoothing::Smooth
Enumerator
Taubin
Laplace
Constructor & Destructor Documentation
DlgSmoothing()
DlgSmoothing::DlgSmoothing (QWidget * parent = nullptr)
References draftgeoutils.intersections::connect(), MeshGui::Ui_DlgSmoothing::labelLambda, MeshGui::Ui_DlgSmoothing::labelMu, MeshGui::Ui_DlgSmoothing::radioButtonLaplace, MeshGui::Ui_DlgSmoothing::radioButtonTaubin, and MeshGui::Ui_DlgSmoothing::setupUi().
~DlgSmoothing()
DlgSmoothing::~DlgSmoothing ()
Member Function Documentation
iterations()
int DlgSmoothing::iterations () const
References MeshGui::Ui_DlgSmoothing::iterations.
Referenced by MeshGui::TaskSmoothing::accept().
lambdaStep()
double DlgSmoothing::lambdaStep () const
References MeshGui::Ui_DlgSmoothing::spinLambda.
Referenced by MeshGui::TaskSmoothing::accept().
method()
DlgSmoothing::Smooth DlgSmoothing::method () const
References Laplace, MeshGui::Ui_DlgSmoothing::radioButtonLaplace, MeshGui::Ui_DlgSmoothing::radioButtonTaubin, and Taubin.
Referenced by MeshGui::TaskSmoothing::accept(), PathScripts.PathDressupRampEntry.ObjectDressup::execute(), and PathScripts.PathDressupRampEntry.ObjectDressup::generateRamps().
microStep()
double DlgSmoothing::microStep () const
References MeshGui::Ui_DlgSmoothing::spinMicro.
Referenced by MeshGui::TaskSmoothing::accept().
smoothSelection()
bool DlgSmoothing::smoothSelection () const
References MeshGui::Ui_DlgSmoothing::checkBoxSelection.
Referenced by MeshGui::TaskSmoothing::accept().
toggledSelection
void MeshGui::DlgSmoothing::toggledSelection (bool) signal
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/Gui/DlgSmoothing.h
FreeCAD/src/Mod/Mesh/Gui/DlgSmoothing.cpp