FreeCAD: Gui::Dialog::UndoDialog Class Reference
Gui::Dialog::UndoDialog Class Reference
This class implements the undo dialog.
#include <DlgUndoRedo.h>
Public Member Functions
UndoDialog (QWidget *parent=0)
Constructs a UndoRedoDialog which is a child of 'parent', with the name 'name'.
virtual ~UndoDialog ()
Destroys the object and frees any allocated resources.
Protected Slots
void onFetchInfo ()
This method fetches the undo / redo information from the active document and shows it in the undo / redo dialog.
void onSelected ()
Closes the dialog and sends the message 'Undo' to the currently active MDI view.
Detailed Description
This class implements the undo dialog.
Author
Werner Mayer
Constructor & Destructor Documentation
UndoDialog()
UndoDialog::UndoDialog (QWidget * parent = 0)
Constructs a UndoRedoDialog which is a child of 'parent', with the name 'name'.
'
References draftgeoutils.intersections::connect(), and onFetchInfo().
~UndoDialog()
UndoDialog::~UndoDialog () virtual
Destroys the object and frees any allocated resources.
Member Function Documentation
onFetchInfo
void UndoDialog::onFetchInfo () protected slot
This method fetches the undo / redo information from the active document and shows it in the undo / redo dialog.
References Gui::MainWindow::activeWindow(), Gui::BaseView::getGuiDocument(), Gui::getMainWindow(), Gui::Document::getUndoVector(), onSelected(), draftutils.translate::translate(), Gui::EditorView::undoActions(), and Gui::TextDocumentEditorView::undoActions().
Referenced by UndoDialog().
onSelected
void UndoDialog::onSelected () protected slot
Closes the dialog and sends the message 'Undo' to the currently active MDI view.
References Gui::Application::Instance, and Gui::Application::sendMsgToActiveView().
Referenced by onFetchInfo().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgUndoRedo.h
Sources/FreeCAD/src/Gui/DlgUndoRedo.cpp