FreeCAD: Gui::Dialog::Ui_DlgCustomCommands Class Reference
Gui::Dialog::Ui_DlgCustomCommands Class Reference
#include <ui_DlgCommands.h>
Public Member Functions
void retranslateUi (QWidget *Gui__Dialog__DlgCustomCommands)
void setupUi (QWidget *Gui__Dialog__DlgCustomCommands)
Public Attributes
QTreeWidget * categoryTreeWidget
QTreeWidget * commandTreeWidget
QGridLayout * gridLayout
QLabel * textLabel
Member Function Documentation
retranslateUi()
void Gui::Dialog::Ui_DlgCustomCommands::retranslateUi (QWidget * Gui__Dialog__DlgCustomCommands)
References textLabel, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::Dialog::Ui_DlgCustomCommands::setupUi (QWidget * Gui__Dialog__DlgCustomCommands)
References categoryTreeWidget, commandTreeWidget, gridLayout, retranslateUi(), and textLabel.
Member Data Documentation
categoryTreeWidget
QTreeWidget* Gui::Dialog::Ui_DlgCustomCommands::categoryTreeWidget
Referenced by setupUi().
commandTreeWidget
QTreeWidget* Gui::Dialog::Ui_DlgCustomCommands::commandTreeWidget
Referenced by setupUi().
gridLayout
QGridLayout* Gui::Dialog::Ui_DlgCustomCommands::gridLayout
Referenced by setupUi().
textLabel
QLabel* Gui::Dialog::Ui_DlgCustomCommands::textLabel
Referenced by retranslateUi(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_DlgCommands.h