FreeCAD: MED::V2_2::TVWrapper Class Reference
MED::V2_2::TVWrapper Class Reference
#include <MED_V2_2_Wrapper.hxx>
Public Member Functions
EGeometrieElement GetBallGeom (const TMeshInfo &theMeshInfo)
Read geom type of MED_BALL structural element.
virtual void GetBallInfo (TBallInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapped representation of MED_BALL from the MED file.
virtual void GetCellInfo (MED::TCellInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapper MED Cells representation from defined MED file.
virtual TEntityInfo GetEntityInfo (const MED::TMeshInfo &theMeshInfo, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)
Get TEntityInfo which contains brief information about existing cells and their destribution among MED ENTITIES.
virtual void GetFamilies (TElemInfo &theInfo, TInt nb, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Read sequence MED Family indexes for any descendant of TElemInfo.
virtual void GetFamilyInfo (TInt theFamId, MED::TFamilyInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapper MED Family representation by its number.
virtual void GetFieldInfo (TInt theFieldId, MED::TFieldInfo &theInfo, TErr *theErr=NULL)
Read MEDWrapper MED FIELD representation by its order number.
virtual void GetGaussInfo (TInt theId, TGaussInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapper MED GAUSS representation by its order number from defined MED file.
virtual TGaussInfo::TInfo GetGaussPreInfo (TInt theId, TErr *theErr=NULL)
Read brief MED GAUSS information by its order number from defined MED Mesh.
virtual void GetGrilleInfo (TGrilleInfo &theGrilleInfo, TErr *theErr=NULL)
Read a MEDWrapper MED Grille representation from defined MED file.
void GetGrilleStruct (const MED::TMeshInfo &theMeshInfo, TIntVector &theStruct, TErr *theErr=NULL)
virtual void GetGrilleType (const MED::TMeshInfo &theMeshInfo, EGrilleType &type, TErr *theErr=NULL)
virtual void GetMeshInfo (TInt theMeshId, MED::TMeshInfo &, TErr *theErr=NULL)
Read a MEDWrapper MED Mesh representation by its number.
virtual void GetNames (TElemInfo &theInfo, TInt nb, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Read sequence of names for any descendant of TElemInfo.
virtual TInt GetNbBalls (const TMeshInfo &theMeshInfo)
Read number of balls in the Mesh.
virtual TInt GetNbCells (const MED::TMeshInfo &theMeshInfo, EEntiteMaillage, EGeometrieElement, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)
Read number of cells for defined MED Mesh, ENTITY and geometrical type with define mode of connectivity.
virtual TInt GetNbComp (TInt theFieldId, TErr *theErr=NULL)
Read number of components for the defined MED FIELD by its order number.
virtual TInt GetNbFamAttr (TInt theFamId, const MED::TMeshInfo &theInfo, TErr *theErr=NULL)
Read number of attributes for defined MED Family.
virtual TInt GetNbFamGroup (TInt theFamId, const MED::TMeshInfo &theInfo, TErr *theErr=NULL)
Read number of MED Groups where MED Family with the number belong to.
virtual TInt GetNbFamilies (const MED::TMeshInfo &theMeshInfo, TErr *theErr=NULL)
Read number of MED Family entities in the defined MED file.
virtual TInt GetNbFields (TErr *theErr=NULL)
Read number of MED FIELDS in defined MED Mesh.
virtual TInt GetNbGauss (TErr *theErr=NULL)
Read number of MED GAUSS in defined MED Mesh.
virtual TInt GetNbMeshes (TErr *theErr=NULL)
Read number of MED Mesh entities in the defined MED file.
TInt GetNbNodes (const MED::TMeshInfo &theMeshInfo, ETable theTable, TErr *theErr=NULL)
virtual TInt GetNbNodes (const MED::TMeshInfo &theMeshInfo, TErr *theErr=NULL)
Read number of nodes in defined MED Mesh.
virtual TInt GetNbPolyedres (const TMeshInfo &theMeshInfo, EEntiteMaillage, EGeometrieElement, EConnectivite, TErr *theErr=NULL)
Read number of MED Polyedres in defined MED Mesh.
virtual TInt GetNbPolygones (const TMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)
Read number of MED Polygones in defined MED Mesh.
virtual TInt GetNbProfiles (TErr *theErr=NULL)
Read number of MED PROFILES in defined MED Mesh.
virtual TInt GetNbTimeStamps (const MED::TFieldInfo &theInfo, const MED::TEntityInfo &theEntityInfo, EEntiteMaillage &theEntity, TGeom2Size &theGeom2Size, TErr *theErr=NULL)
Read number of MED TIMESTAMPS in defined MED Mesh.
virtual void GetNodeInfo (MED::TNodeInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapper MED Nodes representation from defined MED file.
virtual void GetNumeration (TElemInfo &theInfo, TInt nb, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Read sequence of numerous for any descendant of TElemInfo.
virtual void GetPolyedreConnSize (const TMeshInfo &theMeshInfo, TInt &theNbFaces, TInt &theConnSize, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)
Read connectivity infroamtion for the MED Polyedres in defined MED Mesh.
virtual void GetPolyedreInfo (TPolyedreInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapper MED Polyedres representation from defined MED file.
virtual TInt GetPolygoneConnSize (const TMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)
Read connectivity infroamtion for the MED Polygones in defined MED Mesh.
virtual void GetPolygoneInfo (TPolygoneInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapper MED Polygones representation from defined MED file.
virtual void GetProfileInfo (TInt theId, TProfileInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapper MED PROFILE representation by its order number from defined MED file.
virtual TProfileInfo::TInfo GetProfilePreInfo (TInt theId, TErr *theErr=NULL)
Read brief MED PROFILE information by its order number from defined MED Mesh.
virtual void GetTimeStampInfo (TInt theTimeStampId, MED::TTimeStampInfo &theInfo, TErr *theErr=NULL)
Read MEDWrapper MED TIMESTAMP representation by its order number.
virtual void GetTimeStampValue (const PTimeStampValueBase &theTimeStampValue, const TMKey2Profile &theMKey2Profile, const TKey2Gauss &theKey2Gauss, TErr *theErr=NULL)
Read the values for MEDWrapper MED TIMESTAMP from defined MED file.
void SetBallInfo (const TBallInfo &theInfo, EModeAcces theMode, TErr *theErr)
Write a MEDWrapped representation of MED_BALL to the MED file.
virtual void SetBallInfo (const TBallInfo &theInfo, TErr *theErr)
Write a MEDWrapped representation of MED_BALL to the MED file.
void SetCellInfo (const MED::TCellInfo &theInfo, EModeAcces theMode, TErr *theErr=NULL)
virtual void SetCellInfo (const MED::TCellInfo &theInfo, TErr *theErr=NULL)
Write the MEDWrapper MED Cells representation into defined MED file.
virtual void SetFamilies (const TElemInfo &theInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Write sequence MED Family indexes for any descendant of TElemInfo.
void SetFamilies (const TElemInfo &theInfo, EModeAcces theMode, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
void SetFamilyInfo (const MED::TFamilyInfo &theInfo, EModeAcces theMode, TErr *theErr=NULL)
virtual void SetFamilyInfo (const MED::TFamilyInfo &theInfo, TErr *theErr=NULL)
Write a MEDWrapper MED Family representation by its number.
void SetFieldInfo (const MED::TFieldInfo &theInfo, EModeAcces theMode, TErr *theErr=NULL)
virtual void SetFieldInfo (const MED::TFieldInfo &theInfo, TErr *theErr=NULL)
Write MEDWrapper MED FIELD representation into defined MED file.
void SetGrilleInfo (const MED::TGrilleInfo &theGrilleInfo, EModeAcces theMode, TErr *theErr=NULL)
virtual void SetGrilleInfo (const MED::TGrilleInfo &theGrilleInfo, TErr *theErr=NULL)
Write the MEDWrapper MED Grille representation into defined MED file.
void SetMeshInfo (const MED::TMeshInfo &theInfo, EModeAcces theMode, TErr *theErr=NULL)
virtual void SetMeshInfo (const MED::TMeshInfo &theInfo, TErr *theErr=NULL)
Write the MEDWrapper MED Mesh representation in the defined MED file.
virtual void SetNames (const TElemInfo &theInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Write sequence of names for any descendant of TElemInfo.
void SetNames (const TElemInfo &theInfo, EModeAcces theMode, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
void SetNodeInfo (const MED::TNodeInfo &theInfo, EModeAcces theMode, TErr *theErr=NULL)
virtual void SetNodeInfo (const MED::TNodeInfo &theInfo, TErr *theErr=NULL)
Write the MEDWrapper MED Nodes representation into defined MED file.
virtual void SetNumeration (const TElemInfo &theInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Write sequence of numerous for any descendant of TElemInfo.
void SetNumeration (const TElemInfo &theInfo, EModeAcces theMode, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
void SetPolyedreInfo (const MED::TPolyedreInfo &theInfo, EModeAcces theMode, TErr *theErr=NULL)
virtual void SetPolyedreInfo (const TPolyedreInfo &theInfo, TErr *theErr=NULL)
Write a MEDWrapper MED Polyedres representation from defined MED file.
void SetPolygoneInfo (const MED::TPolygoneInfo &theInfo, EModeAcces theMode, TErr *theErr=NULL)
virtual void SetPolygoneInfo (const TPolygoneInfo &theInfo, TErr *theErr=NULL)
Write a MEDWrapper MED Polygones representation from defined MED file.
void SetProfileInfo (const TProfileInfo &theInfo, EModeAcces theMode, TErr *theErr=NULL)
virtual void SetProfileInfo (const TProfileInfo &theInfo, TErr *theErr=NULL)
Write a MEDWrapper MED PROFILE representation.
void SetTimeStampValue (const PTimeStampValueBase &theTimeStampValue, EModeAcces theMode, TErr *theErr=NULL)
virtual void SetTimeStampValue (const PTimeStampValueBase &theTimeStampValue, TErr *theErr=NULL)
Write the values for MEDWrapper MED TIMESTAMP to defined MED file.
TVWrapper (const std::string &theFileName)
Public Member Functions inherited from MED::TTWrapper< eV2_2 >
virtual PBallInfo CrBallInfo (const PMeshInfo &theMeshInfo, const PBallInfo &theInfo)
A copy-constructor for the MEDWrapper MED Balls representation.
virtual PBallInfo CrBallInfo (const PMeshInfo &theMeshInfo, const TIntVector &theNodes, TFloatVector &theDiameters, const TIntVector &theFamilyNums=TIntVector(), const TIntVector &theElemNums=TIntVector())
Creates a MEDWrapper MED Balls representation.
virtual PBallInfo CrBallInfo (const PMeshInfo &theMeshInfo, TInt theNbBalls, EBooleen theIsElemNum=eVRAI)
Creates a MEDWrapper MED Balls representation.
virtual PCellInfo CrCellInfo (const PMeshInfo &theMeshInfo, const PCellInfo &theInfo)
A copy-constructor for the MEDWrapper MED Cells representation.
virtual PCellInfo CrCellInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, const TIntVector &theConnectivities, EConnectivite theConnMode=eNOD, const TIntVector &theFamilyNums=TIntVector(), const TIntVector &theElemNums=TIntVector(), const TStringVector &theElemNames=TStringVector(), EModeSwitch theMode=eFULL_INTERLACE)
Creates a MEDWrapper MED Cells representation.
virtual PCellInfo CrCellInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TInt theNbElem, EConnectivite theConnMode=eNOD, EBooleen theIsElemNum=eVRAI, EBooleen theIsElemNames=eVRAI, EModeSwitch theMode=eFULL_INTERLACE)
Creates a MEDWrapper MED Cells representation.
virtual PElemInfo CrElemInfo (const PMeshInfo &theMeshInfo, TInt theNbElem, const TIntVector &theFamNum, const TIntVector &aElemNum, const TStringVector &aElemNames)
Creates a MEDWrapper MED Nodes representation.
virtual PElemInfo CrElemInfo (const PMeshInfo &theMeshInfo, TInt theNbElem, EBooleen theIsElemNum=eVRAI, EBooleen theIsElemNames=eVRAI)
Creates a MEDWrapper MED Nodes representation.
virtual PFamilyInfo CrFamilyInfo (const PMeshInfo &theMeshInfo, const PFamilyInfo &theInfo)
A copy-constructor for the MEDWrapper MED Family representation.
virtual PFamilyInfo CrFamilyInfo (const PMeshInfo &theMeshInfo, const std::string &theValue, TInt theId, const MED::TStringSet &theGroupNames, const MED::TStringVector &theAttrDescs=MED::TStringVector(), const MED::TIntVector &theAttrIds=MED::TIntVector(), const MED::TIntVector &theAttrVals=MED::TIntVector())
Creates a MEDWrapper MED Family representation.
virtual PFamilyInfo CrFamilyInfo (const PMeshInfo &theMeshInfo, TInt theNbGroup=0, TInt theNbAttr=0, TInt theId=0, const std::string &theValue="")
Creates a MEDWrapper MED Family representation.
virtual PFieldInfo CrFieldInfo (const PMeshInfo &theMeshInfo, const PFieldInfo &theInfo)
A copy-constructor for the MEDWrapper MED FIELD representation.
virtual PFieldInfo CrFieldInfo (const PMeshInfo &theMeshInfo, TInt theNbComp=0, ETypeChamp theType=eFLOAT64, const std::string &theValue="", EBooleen theIsLocal=eVRAI, TInt theNbRef=1)
Creates a MEDWrapper MED FIELD representation.
virtual PGaussInfo CrGaussInfo (const TGaussInfo::TInfo &theInfo, EModeSwitch theMode=eFULL_INTERLACE)
Creates a MEDWrapper MED GAUSS representation.
virtual PGrilleInfo CrGrilleInfo (const PMeshInfo &theMeshInfo, const EGrilleType &type)
virtual PGrilleInfo CrGrilleInfo (const PMeshInfo &theMeshInfo, const EGrilleType &type, const MED::TIntVector &nbNodeVec)
virtual PGrilleInfo CrGrilleInfo (const PMeshInfo &theMeshInfo, const EGrilleType &type, const TInt &nbNodes)
virtual PGrilleInfo CrGrilleInfo (const PMeshInfo &theMeshInfo, const PGrilleInfo &theInfo)
virtual PMeshInfo CrMeshInfo (const PMeshInfo &theInfo)
A copy-constructor for the MEDWrapper MED Mesh representation.
virtual PMeshInfo CrMeshInfo (TInt theDim=0, TInt theSpaceDim=0, const std::string &theValue="", EMaillage theType=eNON_STRUCTURE, const std::string &theDesc="")
Creates a MEDWrapper MED Mesh representation.
virtual PNodeInfo CrNodeInfo (const PMeshInfo &theMeshInfo, const PNodeInfo &theInfo)
A copy-constructor for the MEDWrapper MED Nodes representation.
virtual PNodeInfo CrNodeInfo (const PMeshInfo &theMeshInfo, const TFloatVector &theNodeCoords, EModeSwitch theMode=eFULL_INTERLACE, ERepere theSystem=eCART, const TStringVector &theCoordNames=TStringVector(), const TStringVector &theCoordUnits=TStringVector(), const TIntVector &theFamilyNums=TIntVector(), const TIntVector &theElemNums=TIntVector(), const TStringVector &theElemNames=TStringVector())
Creates a MEDWrapper MED Nodes representation.
virtual PNodeInfo CrNodeInfo (const PMeshInfo &theMeshInfo, TInt theNbElem, EModeSwitch theMode=eFULL_INTERLACE, ERepere theSystem=eCART, EBooleen theIsElemNum=eVRAI, EBooleen theIsElemNames=eVRAI)
Creates a MEDWrapper MED Nodes representation.
virtual PPolyedreInfo CrPolyedreInfo (const PMeshInfo &theMeshInfo, const PPolyedreInfo &theInfo)
A copy-constructor for the MEDWrapper MED Polyedres representation.
virtual PPolyedreInfo CrPolyedreInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, const TIntVector &theIndexes, const TIntVector &theFaces, const TIntVector &theConnectivities, EConnectivite theConnMode=eNOD, const TIntVector &theFamilyNums=TIntVector(), const TIntVector &theElemNums=TIntVector(), const TStringVector &theElemNames=TStringVector())
Creates a MEDWrapper MED Polyedres representation.
virtual PPolyedreInfo CrPolyedreInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TInt theNbElem, TInt theNbFaces, TInt theConnSize, EConnectivite theConnMode=eNOD, EBooleen theIsElemNum=eVRAI, EBooleen theIsElemNames=eVRAI)
virtual PPolygoneInfo CrPolygoneInfo (const PMeshInfo &theMeshInfo, const PPolygoneInfo &theInfo)
A copy-constructor for the MEDWrapper MED Polygones representation.
virtual PPolygoneInfo CrPolygoneInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, const TIntVector &theIndexes, const TIntVector &theConnectivities, EConnectivite theConnMode=eNOD, const TIntVector &theFamilyNums=TIntVector(), const TIntVector &theElemNums=TIntVector(), const TStringVector &theElemNames=TStringVector())
Creates a MEDWrapper MED Polygones representation.
virtual PPolygoneInfo CrPolygoneInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TInt theNbElem, TInt theConnSize, EConnectivite theConnMode=eNOD, EBooleen theIsElemNum=eVRAI, EBooleen theIsElemNames=eVRAI)
Creates a MEDWrapper MED Polygones representation.
virtual PProfileInfo CrProfileInfo (const TProfileInfo::TInfo &theInfo, EModeProfil theMode=eCOMPACT)
Creates a MEDWrapper MED PROFILE representation.
virtual PTimeStampInfo CrTimeStampInfo (const PFieldInfo &theFieldInfo, const PTimeStampInfo &theInfo)
A copy-constructor for the MEDWrapper MED TIMESTAMP representation.
virtual PTimeStampInfo CrTimeStampInfo (const PFieldInfo &theFieldInfo, EEntiteMaillage theEntity, const TGeom2Size &theGeom2Size, const TGeom2NbGauss &theGeom2NbGauss=TGeom2NbGauss(), TInt theNumDt=0, TInt theNumOrd=0, TFloat theDt=0, const std::string &theUnitDt="", const TGeom2Gauss &theGeom2Gauss=TGeom2Gauss())
Creates a MEDWrapper MED TIMESTAMP representation.
virtual PTimeStampValueBase CrTimeStampValue (const PTimeStampInfo &theTimeStampInfo, const PTimeStampValueBase &theInfo, ETypeChamp theTypeChamp)
A copy-constructor for the values for MEDWrapper MED TIMESTAMP representation.
virtual PTimeStampValueBase CrTimeStampValue (const PTimeStampInfo &theTimeStampInfo, ETypeChamp theTypeChamp, const TGeom2Profile &theGeom2Profile=TGeom2Profile(), EModeSwitch theMode=eFULL_INTERLACE)
Creates the values for MEDWrapper MED TIMESTAMP representation.
virtual EVersion GetVersion ()
Gets version of the MED library used for the MED file.
Public Member Functions inherited from MED::TWrapper
virtual PBallInfo CrBallInfo (const PMeshInfo &theMeshInfo, const PBallInfo &theInfo)
A copy-constructor for the MEDWrapped MED Balls representation.
virtual PBallInfo CrBallInfo (const PMeshInfo &theMeshInfo, const TIntVector &theNodes, TFloatVector &theDiameters, const TIntVector &theFamilyNums=TIntVector(), const TIntVector &theElemNums=TIntVector())
Creates a MEDWrapper MED Balls representation.
virtual PBallInfo CrBallInfo (const PMeshInfo &theMeshInfo, TInt theNbBalls, EBooleen theIsElemNum=eVRAI)
Creates a MEDWrapper MED Balls representation.
virtual PCellInfo CrCellInfo (const PMeshInfo &theMeshInfo, const PCellInfo &theInfo)=0
A copy-constructor for the MEDWrapper MED Cells representation.
virtual PCellInfo CrCellInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, const TIntVector &theConnectivities, EConnectivite theConnMode=eNOD, const TIntVector &theFamilyNums=TIntVector(), const TIntVector &theElemNums=TIntVector(), const TStringVector &theElemNames=TStringVector(), EModeSwitch theMode=eFULL_INTERLACE)=0
Creates a MEDWrapper MED Cells representation.
virtual PCellInfo CrCellInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TInt theNbElem, EConnectivite theConnMode=eNOD, EBooleen theIsElemNum=eVRAI, EBooleen theIsElemNames=eVRAI, EModeSwitch theMode=eFULL_INTERLACE)=0
Creates a MEDWrapper MED Cells representation.
virtual PElemInfo CrElemInfo (const PMeshInfo &theMeshInfo, TInt theNbElem, const TIntVector &theFamNum, const TIntVector &aElemNum, const TStringVector &aElemNames)
Creates a MEDWrapper MED Nodes representation.
virtual PElemInfo CrElemInfo (const PMeshInfo &theMeshInfo, TInt theNbElem, EBooleen theIsElemNum=eVRAI, EBooleen theIsElemNames=eVRAI)
Creates a MEDWrapper MED Nodes representation.
virtual PFamilyInfo CrFamilyInfo (const PMeshInfo &theMeshInfo, const PFamilyInfo &theInfo)=0
A copy-constructor for the MEDWrapper MED Family representation.
virtual PFamilyInfo CrFamilyInfo (const PMeshInfo &theMeshInfo, const std::string &theValue, TInt theId, const TStringSet &theGroupNames, const TStringVector &theAttrDescs=TStringVector(), const TIntVector &theAttrIds=TIntVector(), const TIntVector &theAttrVals=TIntVector())=0
Creates a MEDWrapper MED Family representation.
virtual PFamilyInfo CrFamilyInfo (const PMeshInfo &theMeshInfo, TInt theNbGroup=0, TInt theNbAttr=0, TInt theId=0, const std::string &theValue="")=0
Creates a MEDWrapper MED Family representation.
virtual PFieldInfo CrFieldInfo (const PMeshInfo &theMeshInfo, const PFieldInfo &theInfo)=0
A copy-constructor for the MEDWrapper MED FIELD representation.
virtual PFieldInfo CrFieldInfo (const PMeshInfo &theMeshInfo, TInt theNbComp=0, ETypeChamp theType=eFLOAT64, const std::string &theValue="", EBooleen theIsLocal=eVRAI, TInt theNbRef=1)=0
Creates a MEDWrapper MED FIELD representation.
virtual PGaussInfo CrGaussInfo (const TGaussInfo::TInfo &theInfo, EModeSwitch theMode=eFULL_INTERLACE)=0
Creates a MEDWrapper MED GAUSS representation.
virtual PGrilleInfo CrGrilleInfo (const PMeshInfo &theMeshInfo)
virtual PGrilleInfo CrGrilleInfo (const PMeshInfo &theMeshInfo, const EGrilleType &type)
virtual PGrilleInfo CrGrilleInfo (const PMeshInfo &theMeshInfo, const EGrilleType &type, const MED::TIntVector &nbNodeVec)
virtual PGrilleInfo CrGrilleInfo (const PMeshInfo &theMeshInfo, const EGrilleType &type, const TInt &nbNodes)
virtual PGrilleInfo CrGrilleInfo (const PMeshInfo &theMeshInfo, const PGrilleInfo &theGrilleInfo)
virtual PMeshInfo CrMeshInfo (const PMeshInfo &theInfo)=0
A copy-constructor for the MEDWrapper MED Mesh representation.
virtual PMeshInfo CrMeshInfo (TInt theDim=0, TInt theSpaceDim=0, const std::string &theValue="", EMaillage theType=eNON_STRUCTURE, const std::string &theDesc="")=0
Creates a MEDWrapper MED Mesh representation.
virtual PNodeInfo CrNodeInfo (const PMeshInfo &theMeshInfo, const PNodeInfo &theInfo)=0
A copy-constructor for the MEDWrapper MED Nodes representation.
virtual PNodeInfo CrNodeInfo (const PMeshInfo &theMeshInfo, const TFloatVector &theNodeCoords, EModeSwitch theMode=eFULL_INTERLACE, ERepere theSystem=eCART, const TStringVector &theCoordNames=TStringVector(), const TStringVector &theCoordUnits=TStringVector(), const TIntVector &theFamilyNums=TIntVector(), const TIntVector &theElemNums=TIntVector(), const TStringVector &theElemNames=TStringVector())=0
Creates a MEDWrapper MED Nodes representation.
virtual PNodeInfo CrNodeInfo (const PMeshInfo &theMeshInfo, TInt theNbElem, EModeSwitch theMode=eFULL_INTERLACE, ERepere theSystem=eCART, EBooleen theIsElemNum=eVRAI, EBooleen theIsElemNames=eVRAI)=0
Creates a MEDWrapper MED Nodes representation.
virtual PPolyedreInfo CrPolyedreInfo (const PMeshInfo &theMeshInfo, const PPolyedreInfo &theInfo)
A copy-constructor for the MEDWrapper MED Polyedres representation.
virtual PPolyedreInfo CrPolyedreInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, const TIntVector &theIndexes, const TIntVector &theFaces, const TIntVector &theConnectivities, EConnectivite theConnMode=eNOD, const TIntVector &theFamilyNums=TIntVector(), const TIntVector &theElemNums=TIntVector(), const TStringVector &theElemNames=TStringVector())
Creates a MEDWrapper MED Polyedres representation.
virtual PPolyedreInfo CrPolyedreInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TInt theNbElem, TInt theNbFaces, TInt theConnSize, EConnectivite theConnMode=eNOD, EBooleen theIsElemNum=eVRAI, EBooleen theIsElemNames=eVRAI)
virtual PPolygoneInfo CrPolygoneInfo (const PMeshInfo &theMeshInfo, const PPolygoneInfo &theInfo)
A copy-constructor for the MEDWrapper MED Polygones representation.
virtual PPolygoneInfo CrPolygoneInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, const TIntVector &theIndexes, const TIntVector &theConnectivities, EConnectivite theConnMode=eNOD, const TIntVector &theFamilyNums=TIntVector(), const TIntVector &theElemNums=TIntVector(), const TStringVector &theElemNames=TStringVector())
Creates a MEDWrapper MED Polygones representation.
virtual PPolygoneInfo CrPolygoneInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TInt theNbElem, TInt theConnSize, EConnectivite theConnMode=eNOD, EBooleen theIsElemNum=eVRAI, EBooleen theIsElemNames=eVRAI)
Creates a MEDWrapper MED Polygones representation.
virtual PProfileInfo CrProfileInfo (const TProfileInfo::TInfo &theInfo, EModeProfil theMode=eCOMPACT)=0
Creates a MEDWrapper MED PROFILE representation.
virtual PTimeStampInfo CrTimeStampInfo (const PFieldInfo &theFieldInfo, const PTimeStampInfo &theInfo)=0
A copy-constructor for the MEDWrapper MED TIMESTAMP representation.
virtual PTimeStampInfo CrTimeStampInfo (const PFieldInfo &theFieldInfo, EEntiteMaillage theEntity, const TGeom2Size &theGeom2Size, const TGeom2NbGauss &theGeom2NbGauss=TGeom2NbGauss(), TInt theNumDt=0, TInt theNumOrd=0, TFloat theDt=0, const std::string &theUnitDt="", const TGeom2Gauss &theGeom2Gauss=TGeom2Gauss())=0
Creates a MEDWrapper MED TIMESTAMP representation.
virtual PTimeStampVal CrTimeStampVal (const PTimeStampInfo &theTimeStampInfo, const PTimeStampVal &theInfo)
A copy-constructor for the values for MEDWrapper MED TIMESTAMP representation.
virtual PTimeStampVal CrTimeStampVal (const PTimeStampInfo &theTimeStampInfo, const TGeom2Profile &theGeom2Profile=TGeom2Profile(), EModeSwitch theMode=eFULL_INTERLACE)
Creates the values for MEDWrapper MED TIMESTAMP representation.
virtual PTimeStampValueBase CrTimeStampValue (const PTimeStampInfo &theTimeStampInfo, const PTimeStampValueBase &theInfo)
A copy-constructor for the values for MEDWrapper MED TIMESTAMP representation.
virtual PTimeStampValueBase CrTimeStampValue (const PTimeStampInfo &theTimeStampInfo, const PTimeStampValueBase &theInfo, ETypeChamp theTypeChamp)=0
A copy-constructor for the values for MEDWrapper MED TIMESTAMP representation.
virtual PTimeStampValueBase CrTimeStampValue (const PTimeStampInfo &theTimeStampInfo, const TGeom2Profile &theGeom2Profile=TGeom2Profile(), EModeSwitch theMode=eFULL_INTERLACE)
Creates the values for MEDWrapper MED TIMESTAMP representation.
virtual PTimeStampValueBase CrTimeStampValue (const PTimeStampInfo &theTimeStampInfo, ETypeChamp theTypeChamp, const TGeom2Profile &theGeom2Profile=TGeom2Profile(), EModeSwitch theMode=eFULL_INTERLACE)=0
Creates the values for MEDWrapper MED TIMESTAMP representation.
virtual void GetBallInfo (TBallInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapped representation of MED_BALL from the MED file.
virtual void GetCellInfo (TCellInfo &theInfo, TErr *theErr=NULL)=0
Read a MEDWrapper MED Cells representation from defined MED file.
virtual TEntityInfo GetEntityInfo (const TMeshInfo &theMeshInfo, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)=0
Get TEntityInfo which contains brief information about existing cells and their destribution among MED ENTITIES.
virtual void GetFamilies (TElemInfo &theInfo, TInt theNb, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Read sequence MED Family indexes for any descendant of TElemInfo.
virtual void GetFamilyInfo (TInt theFamId, TFamilyInfo &theInfo, TErr *theErr=NULL)=0
Read a MEDWrapper MED Family representation by its number.
virtual void GetFieldInfo (TInt theFieldId, TFieldInfo &theInfo, TErr *theErr=NULL)=0
Read MEDWrapper MED FIELD representation by its order number.
virtual void GetGaussInfo (TInt theId, TGaussInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapper MED GAUSS representation by its order number from defined MED file.
virtual TGaussInfo::TInfo GetGaussPreInfo (TInt theId, TErr *theErr=NULL)
Read brief MED GAUSS information by its order number from defined MED Mesh.
virtual void GetGrilleInfo (TGrilleInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapper MED Grille representation from defined MED file.
virtual void GetGrilleType (const TMeshInfo &theMeshInfo, EGrilleType &type, TErr *theErr=NULL)
virtual void GetMeshInfo (TInt theMeshId, TMeshInfo &theInfo, TErr *theErr=NULL)=0
Read a MEDWrapper MED Mesh representation by its number.
virtual void GetNames (TElemInfo &theInfo, TInt theNb, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Read sequence of names for any descendant of TElemInfo.
virtual TInt GetNbBalls (const TMeshInfo &theMeshInfo)
Read number of balls in the Mesh.
virtual TInt GetNbCells (const TMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)=0
Read number of cells for defined MED Mesh, ENTITY and geometrical type with define mode of connectivity.
virtual TInt GetNbComp (TInt theFieldId, TErr *theErr=NULL)=0
Read number of components for the defined MED FIELD by its order number.
virtual TInt GetNbFamAttr (TInt theFamId, const TMeshInfo &theInfo, TErr *theErr=NULL)=0
Read number of attributes for defined MED Family.
virtual TInt GetNbFamGroup (TInt theFamId, const TMeshInfo &theInfo, TErr *theErr=NULL)=0
Read number of MED Groups where MED Family with the number belong to.
virtual TInt GetNbFamilies (const TMeshInfo &theMeshInfo, TErr *theErr=NULL)=0
Read number of MED Family entities in the defined MED file.
virtual TInt GetNbFields (TErr *theErr=NULL)=0
Read number of MED FIELDS in defined MED Mesh.
virtual TInt GetNbGauss (TErr *theErr=NULL)
Read number of MED GAUSS in defined MED Mesh.
virtual TInt GetNbMeshes (TErr *theErr=NULL)=0
Read number of MED Mesh entities in the defined MED file.
virtual TInt GetNbNodes (const TMeshInfo &theMeshInfo, ETable theTable, TErr *theErr=NULL)
virtual TInt GetNbNodes (const TMeshInfo &theMeshInfo, TErr *theErr=NULL)=0
Read number of nodes in defined MED Mesh.
virtual TInt GetNbPolyedres (const TMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)
Read number of MED Polyedres in defined MED Mesh.
virtual TInt GetNbPolygones (const TMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)
Read number of MED Polygones in defined MED Mesh.
virtual TInt GetNbProfiles (TErr *theErr=NULL)=0
Read number of MED PROFILES in defined MED Mesh.
virtual TInt GetNbTimeStamps (const TFieldInfo &theInfo, const TEntityInfo &theEntityInfo, EEntiteMaillage &theEntity, TGeom2Size &theGeom2Size, TErr *theErr=NULL)=0
Read number of MED TIMESTAMPS in defined MED Mesh.
virtual void GetNodeInfo (TNodeInfo &theInfo, TErr *theErr=NULL)=0
Read a MEDWrapper MED Nodes representation from defined MED file.
virtual void GetNumeration (TElemInfo &theInfo, TInt theNb, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Read sequence of numerous for any descendant of TElemInfo.
virtual PBallInfo GetPBallInfo (const PMeshInfo &theMeshInfo)
Read a MEDWrapped MED Balls representation from defined MED file.
PCellInfo GetPCellInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)
Read a MEDWrapper MED Cells representation from defined MED file.
PElemInfo GetPElemInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity=eNOEUD, EGeometrieElement theGeom=ePOINT1, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)
Read a MEDWrapper MED Element representation from defined MED file.
PFamilyInfo GetPFamilyInfo (const PMeshInfo &theMeshInfo, TInt theId, TErr *theErr=NULL)
Write a MEDWrapper MED Family representation by its number.
PFieldInfo GetPFieldInfo (const PMeshInfo &theMeshInfo, TInt theId, TErr *theErr=NULL)
Read a MEDWrapper MED FIELD representation from defined MED file.
PGrilleInfo GetPGrilleInfo (const PMeshInfo &theMeshInfo)
Read a MEDWrapper MED Grille representation from defined MED file.
PGrilleInfo GetPGrilleInfo (const PMeshInfo &theMeshInfo, const PGrilleInfo &theInfo)
Read a MEDWrapper MED Grille representation from defined MED file.
virtual PMeshInfo GetPMeshInfo (TInt theId, TErr *theErr=NULL)
Read a MEDWrapper MED Mesh representation by its number.
PNodeInfo GetPNodeInfo (const PMeshInfo &theMeshInfo, TErr *theErr=NULL)
Read a MEDWrapper MED Nodes representation from defined MED file.
virtual void GetPolyedreConnSize (const TMeshInfo &theMeshInfo, TInt &theNbFaces, TInt &theConnSize, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)
Read connectivity infroamtion for the MED Polyedres in defined MED Mesh.
virtual void GetPolyedreInfo (TPolyedreInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapper MED Polyedres representation from defined MED file.
virtual TInt GetPolygoneConnSize (const TMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)
Read connectivity infroamtion for the MED Polygones in defined MED Mesh.
virtual void GetPolygoneInfo (TPolygoneInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapper MED Polygones representation from defined MED file.
PPolyedreInfo GetPPolyedreInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode=eNOD)
Read a MEDWrapper MED Polyedres representation from defined MED file.
PPolygoneInfo GetPPolygoneInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode=eNOD)
Read a MEDWrapper MED Polygones representation from defined MED file.
PProfileInfo GetPProfileInfo (TInt theId, EModeProfil theMode=eCOMPACT, TErr *theErr=NULL)
Read a MEDWrapper MED PROFILE representation by its order number from defined MED file.
virtual void GetProfileInfo (TInt theId, TProfileInfo &theInfo, TErr *theErr=NULL)=0
Read a MEDWrapper MED PROFILE representation by its order number from defined MED file.
virtual TProfileInfo::TInfo GetProfilePreInfo (TInt theId, TErr *theErr=NULL)=0
Read brief MED PROFILE information by its order number from defined MED Mesh.
PTimeStampInfo GetPTimeStampInfo (const PFieldInfo &theFieldInfo, EEntiteMaillage theEntity, const TGeom2Size &theGeom2Size, TInt theId, TErr *theErr=NULL)
Read MEDWrapper MED TIMESTAMP representation by its order number.
PTimeStampVal GetPTimeStampVal (const PTimeStampInfo &theTimeStampInfo, const TMKey2Profile &theMKey2Profile, const TKey2Gauss &theKey2Gauss, TErr *theErr=NULL)
Read the values for MEDWrapper MED TIMESTAMP from defined MED file.
PTimeStampValueBase GetPTimeStampValue (const PTimeStampInfo &theTimeStampInfo, const TMKey2Profile &theMKey2Profile, const TKey2Gauss &theKey2Gauss, TErr *theErr=NULL)
Read the values for MEDWrapper MED TIMESTAMP from defined MED file.
virtual void GetTimeStampInfo (TInt theTimeStampId, TTimeStampInfo &theInfo, TErr *theErr=NULL)=0
Read MEDWrapper MED TIMESTAMP representation by its order number.
virtual void GetTimeStampVal (const PTimeStampVal &theVal, const TMKey2Profile &theMKey2Profile, const TKey2Gauss &theKey2Gauss, TErr *theErr=NULL)
Read the values for MEDWrapper MED TIMESTAMP from defined MED file.
virtual void GetTimeStampValue (const PTimeStampValueBase &theTimeStampValue, const TMKey2Profile &theMKey2Profile, const TKey2Gauss &theKey2Gauss, TErr *theErr=NULL)=0
Read the values for MEDWrapper MED TIMESTAMP from defined MED file.
virtual EVersion GetVersion ()=0
Gets version of the MED library used for the MED file.
virtual void SetBallInfo (const TBallInfo &theInfo, TErr *theErr=NULL)
Write a MEDWrapped representation of MED_BALL to the MED file.
virtual void SetCellInfo (const TCellInfo &theInfo, TErr *theErr=NULL)=0
Write the MEDWrapper MED Cells representation into defined MED file.
virtual void SetFamilies (const TElemInfo &theInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Write sequence MED Family indexes for any descendant of TElemInfo.
virtual void SetFamilyInfo (const TFamilyInfo &theInfo, TErr *theErr=NULL)=0
Write a MEDWrapper MED Family representation by its number.
virtual void SetFieldInfo (const TFieldInfo &theInfo, TErr *theErr=NULL)=0
Write MEDWrapper MED FIELD representation into defined MED file.
virtual void SetGrilleInfo (const TGrilleInfo &theInfo, TErr *theErr=NULL)
Write the MEDWrapper MED Grille representation into defined MED file.
virtual void SetMeshInfo (const TMeshInfo &theInfo, TErr *theErr=NULL)=0
Write the MEDWrapper MED Mesh representation in the defined MED file.
virtual void SetNames (const TElemInfo &theInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Write sequence of names for any descendant of TElemInfo.
virtual void SetNodeInfo (const TNodeInfo &theInfo, TErr *theErr=NULL)=0
Write the MEDWrapper MED Nodes representation into defined MED file.
virtual void SetNumeration (const TElemInfo &theInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Write sequence of numerous for any descendant of TElemInfo.
virtual void SetPolyedreInfo (const TPolyedreInfo &theInfo, TErr *theErr=NULL)
Write a MEDWrapper MED Polyedres representation from defined MED file.
virtual void SetPolygoneInfo (const TPolygoneInfo &theInfo, TErr *theErr=NULL)
Write a MEDWrapper MED Polygones representation from defined MED file.
virtual void SetProfileInfo (const TProfileInfo &theInfo, TErr *theErr=NULL)=0
Write a MEDWrapper MED PROFILE representation.
virtual void SetTimeStamp (const PTimeStampVal &theVal, TErr *theErr=NULL)
Write the values for MEDWrapper MED TIMESTAMP to defined MED file.
virtual void SetTimeStampValue (const PTimeStampValueBase &theTimeStampValue, TErr *theErr=NULL)=0
Write the values for MEDWrapper MED TIMESTAMP to defined MED file.
virtual ~TWrapper ()
Protected Attributes
PFile myFile
Additional Inherited Members
Public Types inherited from MED::TWrapper
typedef boost::mutex TMutex
Public Attributes inherited from MED::TWrapper
TMutex myMutex
This is a syncronization primitive which allow to support thread safety for the MED access.
Constructor & Destructor Documentation
TVWrapper()
MED::V2_2::TVWrapper::TVWrapper (const std::string & theFileName)
References MED::V2_2::eCREATION, MED::V2_2::eLECTURE, MED::V2_2::eLECTURE_ECRITURE, and myFile.
Member Function Documentation
GetBallGeom()
EGeometrieElement MED::V2_2::TVWrapper::GetBallGeom (const TMeshInfo & theMeshInfo)
Read geom type of MED_BALL structural element.
References MED::V2_2::eLECTURE, and myFile.
Referenced by GetBallInfo(), GetFamilies(), GetNames(), GetNbBalls(), GetNumeration(), SetBallInfo(), SetFamilies(), SetNames(), and SetNumeration().
GetBallInfo()
void MED::V2_2::TVWrapper::GetBallInfo (TBallInfo & theInfo, TErr * theErr = NULL) virtual
Read a MEDWrapped representation of MED_BALL from the MED file.
Reimplemented from MED::TWrapper.
References MED::eBALL, MED::V2_2::eLECTURE, GetBallGeom(), GetCellInfo(), MED::TBallInfo::myDiameters, myFile, MED::TCellInfo::myGeom, and MED::TElemInfo::myMeshInfo.
GetCellInfo()
void MED::V2_2::TVWrapper::GetCellInfo (MED::TCellInfo & theInfo, TErr * theErr = NULL) virtual
Read a MEDWrapper MED Cells representation from defined MED file.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE, MED::TCellInfo::myConn, MED::TCellInfo::myConnMode, MED::TElemInfo::myElemNames, MED::TElemInfo::myElemNum, MED::TCellInfo::myEntity, MED::TElemInfo::myFamNum, myFile, MED::TCellInfo::myGeom, MED::TElemInfo::myIsElemNames, MED::TElemInfo::myIsElemNum, MED::TElemInfo::myIsFamNum, MED::TElemInfo::myMeshInfo, MED::TModeSwitchInfo::myModeSwitch, and MED::TNameInfo::myName.
Referenced by GetBallInfo().
GetEntityInfo()
TEntityInfo MED::V2_2::TVWrapper::GetEntityInfo (const MED::TMeshInfo & theMeshInfo, EConnectivite theConnMode = eNOD, TErr * theErr = NULL) virtual
Get TEntityInfo which contains brief information about existing cells and their destribution among MED ENTITIES.
Implements MED::TWrapper.
References MED::eARETE, MED::eCOOR_IND1, MED::eCOOR_IND2, MED::eCOOR_IND3, MED::eFACE, MED::eGRILLE_STANDARD, MED::eHEXA8, MED::V2_2::eLECTURE, MED::eMAILLE, MED::eNOEUD, MED::eNON_STRUCTURE, MED::ePOINT1, MED::eQUAD4, MED::eSEG2, MED::eSTRUCT_ELEMENT, MED::TMeshInfo::GetDim(), MED::GetEntity2GeomSet(), GetGrilleStruct(), GetGrilleType(), GetNbCells(), GetNbNodes(), MED::TMeshInfo::GetType(), myFile, and MED::TNameInfo::myName.
GetFamilies()
void MED::V2_2::TVWrapper::GetFamilies (TElemInfo & theInfo, TInt theNb, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr * theErr = NULL) virtual
Read sequence MED Family indexes for any descendant of TElemInfo.
Reimplemented from MED::TWrapper.
References MED::eBALL, MED::V2_2::eLECTURE, GetBallGeom(), MED::TElemInfo::myFamNum, myFile, MED::TElemInfo::myMeshInfo, and MED::TNameInfo::myName.
Referenced by GetPolyedreInfo(), and GetPolygoneInfo().
GetFamilyInfo()
void MED::V2_2::TVWrapper::GetFamilyInfo (TInt theFamId, MED::TFamilyInfo & theInfo, TErr * theErr = NULL) virtual
Read a MEDWrapper MED Family representation by its number.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE, MED::TFamilyInfo::myAttrDesc, MED::TFamilyInfo::myAttrId, MED::TFamilyInfo::myAttrVal, myFile, MED::TFamilyInfo::myGroupNames, MED::TFamilyInfo::myId, MED::TFamilyInfo::myMeshInfo, MED::TNameInfo::myName, MED::TFamilyInfo::myNbAttr, and MED::TFamilyInfo::myNbGroup.
GetFieldInfo()
void MED::V2_2::TVWrapper::GetFieldInfo (TInt theFieldId, MED::TFieldInfo & theInfo, TErr * theErr = NULL) virtual
Read MEDWrapper MED FIELD representation by its order number.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE, MED::TFieldInfo::myCompNames, myFile, MED::TFieldInfo::myMeshInfo, MED::TNameInfo::myName, MED::TFieldInfo::myNbComp, MED::TFieldInfo::myType, MED::TFieldInfo::myUnitNames, and MED::TNameInfo::SetName().
GetGaussInfo()
void MED::V2_2::TVWrapper::GetGaussInfo (TInt theId, TGaussInfo & theInfo, TErr * theErr = NULL) virtual
Read a MEDWrapper MED GAUSS representation by its order number from defined MED file.
This feature is support only for version of 2.2 and higher
Reimplemented from MED::TWrapper.
References MED::V2_2::eLECTURE, myFile, MED::TGaussInfo::myGaussCoord, MED::TModeSwitchInfo::myModeSwitch, MED::TNameInfo::myName, MED::TGaussInfo::myRefCoord, and MED::TGaussInfo::myWeight.
GetGaussPreInfo()
TGaussInfo::TInfo MED::V2_2::TVWrapper::GetGaussPreInfo (TInt theId, TErr * theErr = NULL) virtual
Read brief MED GAUSS information by its order number from defined MED Mesh.
This feature is support only for version of 2.2 and higher
Reimplemented from MED::TWrapper.
References MED::V2_2::eLECTURE, MED::ePOINT1, MED::GetNOMLength< eV2_2 >(), and myFile.
GetGrilleInfo()
void MED::V2_2::TVWrapper::GetGrilleInfo (TGrilleInfo & theInfo, TErr * theErr = NULL) virtual
Read a MEDWrapper MED Grille representation from defined MED file.
This feature is support only for version of 2.2 and higher
Reimplemented from MED::TWrapper.
References MED::eCOOR_IND1, MED::eCOOR_IND2, MED::eCOOR_IND3, MED::eGRILLE_STANDARD, MED::V2_2::eLECTURE, MED::eSTRUCTURE, MED::TGrilleInfo::GetEntity(), MED::TGrilleInfo::GetGeom(), GetGrilleStruct(), GetGrilleType(), MED::TGrilleInfo::GetIndexes(), MED::TGrilleInfo::GetNbCells(), GetNbNodes(), MED::TGrilleInfo::GetNbSubCells(), MED::TGrilleInfo::GetSubEntity(), MED::TGrilleInfo::GetSubGeom(), MED::TGrilleInfo::myCoord, MED::TGrilleInfo::myCoordNames, MED::TGrilleInfo::myCoordUnits, MED::TMeshInfo::myDim, MED::TGrilleInfo::myFamNum, MED::TGrilleInfo::myFamNumNode, MED::TGrilleInfo::myFamSubNum, myFile, MED::TGrilleInfo::myGrilleStructure, MED::TGrilleInfo::myGrilleType, MED::TGrilleInfo::myMeshInfo, MED::TModeSwitchInfo::myModeSwitch, MED::TNameInfo::myName, MED::TMeshInfo::myType, and MED::TGrilleInfo::SetGrilleStructure().
GetGrilleStruct()
void MED::V2_2::TVWrapper::GetGrilleStruct (const MED::TMeshInfo & theMeshInfo, TIntVector & theStruct, TErr * theErr = NULL)
References MED::V2_2::eLECTURE, myFile, and MED::TNameInfo::myName.
Referenced by GetEntityInfo(), and GetGrilleInfo().
GetGrilleType()
void MED::V2_2::TVWrapper::GetGrilleType (const MED::TMeshInfo & theMeshInfo, EGrilleType & type, TErr * theErr = NULL) virtual
This feature is support only for version of 2.2 and higher
Reimplemented from MED::TWrapper.
References MED::V2_2::eLECTURE, MED::eSTRUCTURE, myFile, MED::TNameInfo::myName, and MED::TMeshInfo::myType.
Referenced by GetEntityInfo(), and GetGrilleInfo().
GetMeshInfo()
void MED::V2_2::TVWrapper::GetMeshInfo (TInt theMeshId, MED::TMeshInfo & theInfo, TErr * theErr = NULL) virtual
Read a MEDWrapper MED Mesh representation by its number.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE, MED::TMeshInfo::myDesc, MED::TMeshInfo::myDim, myFile, MED::TNameInfo::myName, MED::TMeshInfo::mySpaceDim, and MED::TMeshInfo::myType.
GetNames()
void MED::V2_2::TVWrapper::GetNames (TElemInfo & theInfo, TInt theNb, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr * theErr = NULL) virtual
Read sequence of names for any descendant of TElemInfo.
Reimplemented from MED::TWrapper.
References MED::eBALL, MED::eFAUX, MED::V2_2::eLECTURE, MED::eVRAI, GetBallGeom(), MED::TElemInfo::myElemNames, myFile, MED::TElemInfo::myIsElemNames, MED::TElemInfo::myMeshInfo, and MED::TNameInfo::myName.
Referenced by GetPolyedreInfo(), and GetPolygoneInfo().
GetNbBalls()
TInt MED::V2_2::TVWrapper::GetNbBalls (const TMeshInfo & theMeshInfo) virtual
Read number of balls in the Mesh.
Reimplemented from MED::TWrapper.
References MED::V2_2::eLECTURE, MED::eNOD, MED::eSTRUCT_ELEMENT, GetBallGeom(), GetNbCells(), and myFile.
Referenced by GetNbCells().
GetNbCells()
TInt MED::V2_2::TVWrapper::GetNbCells (const MED::TMeshInfo & theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode = eNOD, TErr * theErr = NULL) virtual
Read number of cells for defined MED Mesh, ENTITY and geometrical type with define mode of connectivity.
Implements MED::TWrapper.
References MED::eBALL, MED::V2_2::eLECTURE, MED::ePOLYEDRE, MED::ePOLYGON2, MED::ePOLYGONE, GetNbBalls(), myFile, and MED::TNameInfo::myName.
Referenced by GetEntityInfo(), GetNbBalls(), GetNbPolyedres(), and GetNbPolygones().
GetNbComp()
TInt MED::V2_2::TVWrapper::GetNbComp (TInt theFieldId, TErr * theErr = NULL) virtual
Read number of components for the defined MED FIELD by its order number.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE, and myFile.
GetNbFamAttr()
TInt MED::V2_2::TVWrapper::GetNbFamAttr (TInt theFamId, const MED::TMeshInfo & theInfo, TErr * theErr = NULL) virtual
Read number of attributes for defined MED Family.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE, myFile, and MED::TNameInfo::myName.
GetNbFamGroup()
TInt MED::V2_2::TVWrapper::GetNbFamGroup (TInt theFamId, const MED::TMeshInfo & theInfo, TErr * theErr = NULL) virtual
Read number of MED Groups where MED Family with the number belong to.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE, myFile, and MED::TNameInfo::myName.
GetNbFamilies()
TInt MED::V2_2::TVWrapper::GetNbFamilies (const MED::TMeshInfo & theMeshInfo, TErr * theErr = NULL) virtual
Read number of MED Family entities in the defined MED file.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE, myFile, and MED::TNameInfo::myName.
GetNbFields()
TInt MED::V2_2::TVWrapper::GetNbFields (TErr * theErr = NULL) virtual
Read number of MED FIELDS in defined MED Mesh.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE, and myFile.
GetNbGauss()
TInt MED::V2_2::TVWrapper::GetNbGauss (TErr * theErr = NULL) virtual
Read number of MED GAUSS in defined MED Mesh.
This feature is support only for version of 2.2 and higher
Reimplemented from MED::TWrapper.
References MED::V2_2::eLECTURE, and myFile.
GetNbMeshes()
TInt MED::V2_2::TVWrapper::GetNbMeshes (TErr * theErr = NULL) virtual
Read number of MED Mesh entities in the defined MED file.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE, and myFile.
Referenced by GetNbTimeStamps().
GetNbNodes() [1/2]
TInt MED::V2_2::TVWrapper::GetNbNodes (const MED::TMeshInfo & theMeshInfo, ETable theTable, TErr * theErr = NULL) virtual
Reimplemented from MED::TWrapper.
References MED::V2_2::eLECTURE, myFile, and MED::TNameInfo::myName.
GetNbNodes() [2/2]
virtual TInt MED::V2_2::TVWrapper::GetNbNodes (const MED::TMeshInfo & theMeshInfo, TErr * theErr = NULL) virtual
Read number of nodes in defined MED Mesh.
Implements MED::TWrapper.
References MED::eCOOR, and MED::GetNbNodes().
Referenced by GetEntityInfo(), and GetGrilleInfo().
GetNbPolyedres()
TInt MED::V2_2::TVWrapper::GetNbPolyedres (const TMeshInfo & theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode, TErr * theErr = NULL) virtual
Read number of MED Polyedres in defined MED Mesh.
This feature is support only for version of 2.2 and higher
Reimplemented from MED::TWrapper.
References GetNbCells().
GetNbPolygones()
TInt MED::V2_2::TVWrapper::GetNbPolygones (const TMeshInfo & theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode = eNOD, TErr * theErr = NULL) virtual
Read number of MED Polygones in defined MED Mesh.
This feature is supported only for version of 2.2 and higher
Reimplemented from MED::TWrapper.
References GetNbCells().
GetNbProfiles()
TInt MED::V2_2::TVWrapper::GetNbProfiles (TErr * theErr = NULL) virtual
Read number of MED PROFILES in defined MED Mesh.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE, and myFile.
GetNbTimeStamps()
TInt MED::V2_2::TVWrapper::GetNbTimeStamps (const MED::TFieldInfo & theInfo, const MED::TEntityInfo & theEntityInfo, EEntiteMaillage & theEntity, TGeom2Size & theGeom2Size, TErr * theErr = NULL) virtual
Read number of MED TIMESTAMPS in defined MED Mesh.
By the way some additional information can be obtained:
to what MED ENTITY the MED TIMESTAMP conntected to;
on what geometrical types the MED TIMESTAMP defined to.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE, MED::eMAILLE, MED::eNOEUD_ELEMENT, GetNbMeshes(), myFile, MED::TFieldInfo::myMeshInfo, and MED::TNameInfo::myName.
GetNodeInfo()
void MED::V2_2::TVWrapper::GetNodeInfo (MED::TNodeInfo & theInfo, TErr * theErr = NULL) virtual
Read a MEDWrapper MED Nodes representation from defined MED file.
Implements MED::TWrapper.
References MED::eFAUX, MED::V2_2::eLECTURE, MED::TNodeInfo::myCoord, MED::TNodeInfo::myCoordNames, MED::TNodeInfo::myCoordUnits, MED::TMeshInfo::myDim, MED::TElemInfo::myElemNames, MED::TElemInfo::myElemNum, MED::TElemInfo::myFamNum, myFile, MED::TElemInfo::myIsElemNames, MED::TElemInfo::myIsElemNum, MED::TElemInfo::myMeshInfo, MED::TModeSwitchInfo::myModeSwitch, MED::TNameInfo::myName, MED::TElemInfo::myNbElem, and MED::TNodeInfo::mySystem.
GetNumeration()
void MED::V2_2::TVWrapper::GetNumeration (TElemInfo & theInfo, TInt theNb, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr * theErr = NULL) virtual
Read sequence of numerous for any descendant of TElemInfo.
Reimplemented from MED::TWrapper.
References MED::eBALL, MED::eFAUX, MED::V2_2::eLECTURE, MED::eVRAI, GetBallGeom(), MED::TElemInfo::myElemNum, myFile, MED::TElemInfo::myIsElemNum, MED::TElemInfo::myMeshInfo, and MED::TNameInfo::myName.
Referenced by GetPolyedreInfo(), and GetPolygoneInfo().
GetPolyedreConnSize()
void MED::V2_2::TVWrapper::GetPolyedreConnSize (const TMeshInfo & theMeshInfo, TInt & theNbFaces, TInt & theConnSize, EConnectivite theConnMode = eNOD, TErr * theErr = NULL) virtual
Read connectivity infroamtion for the MED Polyedres in defined MED Mesh.
This feature is support only for version of 2.2 and higher
Reimplemented from MED::TWrapper.
References MED::V2_2::eLECTURE, myFile, and MED::TNameInfo::myName.
GetPolyedreInfo()
void MED::V2_2::TVWrapper::GetPolyedreInfo (TPolyedreInfo & theInfo, TErr * theErr = NULL) virtual
Read a MEDWrapper MED Polyedres representation from defined MED file.
This feature is support only for version of 2.2 and higher
Reimplemented from MED::TWrapper.
References MED::V2_2::eLECTURE, MED::ePOLYEDRE, GetFamilies(), GetNames(), GetNumeration(), MED::TPolyedreInfo::myConn, MED::TPolyedreInfo::myConnMode, MED::TElemInfo::myElemNum, MED::TPolyedreInfo::myEntity, MED::TPolyedreInfo::myFaces, myFile, MED::TPolyedreInfo::myIndex, MED::TElemInfo::myIsElemNames, MED::TElemInfo::myIsElemNum, MED::TElemInfo::myMeshInfo, and MED::TNameInfo::myName.
GetPolygoneConnSize()
TInt MED::V2_2::TVWrapper::GetPolygoneConnSize (const TMeshInfo & theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode = eNOD, TErr * theErr = NULL) virtual
Read connectivity infroamtion for the MED Polygones in defined MED Mesh.
This feature is supported only for version of 2.2 and higher
Reimplemented from MED::TWrapper.
References MED::V2_2::eLECTURE, myFile, and MED::TNameInfo::myName.
GetPolygoneInfo()
void MED::V2_2::TVWrapper::GetPolygoneInfo (MED::TPolygoneInfo & theInfo, TErr * theErr = NULL) virtual
Read a MEDWrapper MED Polygones representation from defined MED file.
This feature is supported only for version of 2.2 and higher
Reimplemented from MED::TWrapper.
References MED::V2_2::eLECTURE, GetFamilies(), GetNames(), GetNumeration(), MED::TPolygoneInfo::myConn, MED::TPolygoneInfo::myConnMode, MED::TElemInfo::myElemNum, MED::TPolygoneInfo::myEntity, myFile, MED::TPolygoneInfo::myGeom, MED::TPolygoneInfo::myIndex, MED::TElemInfo::myIsElemNames, MED::TElemInfo::myIsElemNum, MED::TElemInfo::myMeshInfo, and MED::TNameInfo::myName.
GetProfileInfo()
void MED::V2_2::TVWrapper::GetProfileInfo (TInt theId, TProfileInfo & theInfo, TErr * theErr = NULL) virtual
Read a MEDWrapper MED PROFILE representation by its order number from defined MED file.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE, MED::TProfileInfo::myElemNum, myFile, and MED::TNameInfo::myName.
GetProfilePreInfo()
TProfileInfo::TInfo MED::V2_2::TVWrapper::GetProfilePreInfo (TInt theId, TErr * theErr = NULL) virtual
Read brief MED PROFILE information by its order number from defined MED Mesh.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE, MED::GetNOMLength< eV2_2 >(), and myFile.
GetTimeStampInfo()
void MED::V2_2::TVWrapper::GetTimeStampInfo (TInt theTimeStampId, MED::TTimeStampInfo & theInfo, TErr * theErr = NULL) virtual
Read MEDWrapper MED TIMESTAMP representation by its order number.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE, MED::TTimeStampInfo::myDt, MED::TTimeStampInfo::myEntity, MED::TTimeStampInfo::myFieldInfo, myFile, MED::TTimeStampInfo::myGeom2NbGauss, MED::TTimeStampInfo::myGeom2Size, MED::TFieldInfo::myIsLocal, MED::TFieldInfo::myMeshInfo, MED::TNameInfo::myName, MED::TFieldInfo::myNbRef, MED::TTimeStampInfo::myNumDt, MED::TTimeStampInfo::myNumOrd, and MED::TTimeStampInfo::myUnitDt.
GetTimeStampValue()
void MED::V2_2::TVWrapper::GetTimeStampValue (const PTimeStampValueBase & theTimeStampValue, const TMKey2Profile & theMKey2Profile, const TKey2Gauss & theKey2Gauss, TErr * theErr = NULL) virtual
Read the values for MEDWrapper MED TIMESTAMP from defined MED file.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE, MED::GetNOMLength< eV2_2 >(), and myFile.
SetBallInfo() [1/2]
void MED::V2_2::TVWrapper::SetBallInfo (const TBallInfo & theInfo, EModeAcces theMode, TErr * theErr)
Write a MEDWrapped representation of MED_BALL to the MED file.
References GetBallGeom(), MED::TBallInfo::myDiameters, myFile, MED::TCellInfo::myGeom, MED::TElemInfo::myMeshInfo, MED::TElemInfo::myNbElem, and SetCellInfo().
SetBallInfo() [2/2]
void MED::V2_2::TVWrapper::SetBallInfo (const TBallInfo & theInfo, TErr * theErr) virtual
Write a MEDWrapped representation of MED_BALL to the MED file.
Reimplemented from MED::TWrapper.
References MED::V2_2::eLECTURE_ECRITURE, and SetBallInfo().
Referenced by SetBallInfo().
SetCellInfo() [1/2]
void MED::V2_2::TVWrapper::SetCellInfo (const MED::TCellInfo & theInfo, EModeAcces theMode, TErr * theErr = NULL)
References MED::TCellInfo::myConn, MED::TCellInfo::myConnMode, MED::TElemInfo::myElemNames, MED::TElemInfo::myElemNum, MED::TCellInfo::myEntity, MED::TElemInfo::myFamNum, myFile, MED::TCellInfo::myGeom, MED::TElemInfo::myIsElemNames, MED::TElemInfo::myIsElemNum, MED::TElemInfo::myIsFamNum, MED::TElemInfo::myMeshInfo, MED::TModeSwitchInfo::myModeSwitch, MED::TNameInfo::myName, and MED::TElemInfo::myNbElem.
SetCellInfo() [2/2]
void MED::V2_2::TVWrapper::SetCellInfo (const MED::TCellInfo & theInfo, TErr * theErr = NULL) virtual
Write the MEDWrapper MED Cells representation into defined MED file.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE_ECRITURE, and SetCellInfo().
Referenced by SetBallInfo(), and SetCellInfo().
SetFamilies() [1/2]
void MED::V2_2::TVWrapper::SetFamilies (const TElemInfo & theInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr * theErr = NULL) virtual
Write sequence MED Family indexes for any descendant of TElemInfo.
Reimplemented from MED::TWrapper.
References MED::V2_2::eLECTURE_ECRITURE, and SetFamilies().
Referenced by SetFamilies(), and SetPolygoneInfo().
SetFamilies() [2/2]
void MED::V2_2::TVWrapper::SetFamilies (const TElemInfo & theInfo, EModeAcces theMode, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr * theErr = NULL)
References MED::eBALL, GetBallGeom(), MED::TElemInfo::myFamNum, myFile, MED::TElemInfo::myMeshInfo, and MED::TNameInfo::myName.
SetFamilyInfo() [1/2]
void MED::V2_2::TVWrapper::SetFamilyInfo (const MED::TFamilyInfo & theInfo, EModeAcces theMode, TErr * theErr = NULL)
References MED::TFamilyInfo::myAttrDesc, MED::TFamilyInfo::myAttrId, MED::TFamilyInfo::myAttrVal, myFile, MED::TFamilyInfo::myGroupNames, MED::TFamilyInfo::myId, MED::TFamilyInfo::myMeshInfo, MED::TNameInfo::myName, MED::TFamilyInfo::myNbAttr, and MED::TFamilyInfo::myNbGroup.
SetFamilyInfo() [2/2]
void MED::V2_2::TVWrapper::SetFamilyInfo (const MED::TFamilyInfo & theInfo, TErr * theErr = NULL) virtual
Write a MEDWrapper MED Family representation by its number.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE_AJOUT, MED::V2_2::eLECTURE_ECRITURE, and SetFamilyInfo().
Referenced by SetFamilyInfo().
SetFieldInfo() [1/2]
void MED::V2_2::TVWrapper::SetFieldInfo (const MED::TFieldInfo & theInfo, EModeAcces theMode, TErr * theErr = NULL)
References MED::TFieldInfo::myCompNames, myFile, MED::TFieldInfo::myMeshInfo, MED::TNameInfo::myName, MED::TFieldInfo::myNbComp, MED::TFieldInfo::myType, and MED::TFieldInfo::myUnitNames.
SetFieldInfo() [2/2]
void MED::V2_2::TVWrapper::SetFieldInfo (const MED::TFieldInfo & theInfo, TErr * theErr = NULL) virtual
Write MEDWrapper MED FIELD representation into defined MED file.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE_AJOUT, MED::V2_2::eLECTURE_ECRITURE, and SetFieldInfo().
Referenced by SetFieldInfo().
SetGrilleInfo() [1/2]
void MED::V2_2::TVWrapper::SetGrilleInfo (const MED::TGrilleInfo & theGrilleInfo, EModeAcces theMode, TErr * theErr = NULL)
References MED::eGRILLE_STANDARD, MED::eSTRUCTURE, MED::TGrilleInfo::GetIndexes(), MED::TGrilleInfo::myCoord, MED::TGrilleInfo::myCoordNames, MED::TGrilleInfo::myCoordUnits, MED::TMeshInfo::myDim, myFile, MED::TGrilleInfo::myGrilleStructure, MED::TGrilleInfo::myGrilleType, MED::TGrilleInfo::myMeshInfo, MED::TModeSwitchInfo::myModeSwitch, and MED::TNameInfo::myName.
SetGrilleInfo() [2/2]
void MED::V2_2::TVWrapper::SetGrilleInfo (const MED::TGrilleInfo & theInfo, TErr * theErr = NULL) virtual
Write the MEDWrapper MED Grille representation into defined MED file.
This feature is support only for version of 2.2 and higher
Reimplemented from MED::TWrapper.
References MED::V2_2::eLECTURE_ECRITURE, and SetGrilleInfo().
Referenced by SetGrilleInfo().
SetMeshInfo() [1/2]
void MED::V2_2::TVWrapper::SetMeshInfo (const MED::TMeshInfo & theInfo, EModeAcces theMode, TErr * theErr = NULL)
References MED::TMeshInfo::myDesc, MED::TMeshInfo::myDim, myFile, MED::TNameInfo::myName, MED::TMeshInfo::mySpaceDim, and MED::TMeshInfo::myType.
SetMeshInfo() [2/2]
void MED::V2_2::TVWrapper::SetMeshInfo (const MED::TMeshInfo & theInfo, TErr * theErr = NULL) virtual
Write the MEDWrapper MED Mesh representation in the defined MED file.
Implements MED::TWrapper.
References MED::V2_2::eCREATION, MED::V2_2::eLECTURE_AJOUT, MED::V2_2::eLECTURE_ECRITURE, and SetMeshInfo().
Referenced by SetMeshInfo().
SetNames() [1/2]
void MED::V2_2::TVWrapper::SetNames (const TElemInfo & theInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr * theErr = NULL) virtual
Write sequence of names for any descendant of TElemInfo.
Reimplemented from MED::TWrapper.
References MED::V2_2::eLECTURE_ECRITURE, and SetNames().
Referenced by SetNames(), and SetPolygoneInfo().
SetNames() [2/2]
void MED::V2_2::TVWrapper::SetNames (const TElemInfo & theInfo, EModeAcces theMode, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr * theErr = NULL)
References MED::eBALL, GetBallGeom(), MED::TElemInfo::myElemNames, myFile, MED::TElemInfo::myIsElemNames, MED::TElemInfo::myMeshInfo, and MED::TNameInfo::myName.
SetNodeInfo() [1/2]
void MED::V2_2::TVWrapper::SetNodeInfo (const MED::TNodeInfo & theInfo, EModeAcces theMode, TErr * theErr = NULL)
References MED::TNodeInfo::myCoord, MED::TNodeInfo::myCoordNames, MED::TNodeInfo::myCoordUnits, MED::TElemInfo::myElemNames, MED::TElemInfo::myElemNum, MED::TElemInfo::myFamNum, myFile, MED::TElemInfo::myIsElemNames, MED::TElemInfo::myIsElemNum, MED::TElemInfo::myMeshInfo, MED::TModeSwitchInfo::myModeSwitch, MED::TNameInfo::myName, MED::TElemInfo::myNbElem, and MED::TNodeInfo::mySystem.
SetNodeInfo() [2/2]
void MED::V2_2::TVWrapper::SetNodeInfo (const MED::TNodeInfo & theInfo, TErr * theErr = NULL) virtual
Write the MEDWrapper MED Nodes representation into defined MED file.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE_AJOUT, MED::V2_2::eLECTURE_ECRITURE, and SetNodeInfo().
Referenced by SetNodeInfo().
SetNumeration() [1/2]
void MED::V2_2::TVWrapper::SetNumeration (const TElemInfo & theInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr * theErr = NULL) virtual
Write sequence of numerous for any descendant of TElemInfo.
Reimplemented from MED::TWrapper.
References MED::V2_2::eLECTURE_ECRITURE, and SetNumeration().
Referenced by SetNumeration(), and SetPolygoneInfo().
SetNumeration() [2/2]
void MED::V2_2::TVWrapper::SetNumeration (const TElemInfo & theInfo, EModeAcces theMode, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr * theErr = NULL)
References MED::eBALL, GetBallGeom(), MED::TElemInfo::myElemNum, myFile, MED::TElemInfo::myIsElemNum, MED::TElemInfo::myMeshInfo, and MED::TNameInfo::myName.
SetPolyedreInfo() [1/2]
void MED::V2_2::TVWrapper::SetPolyedreInfo (const MED::TPolyedreInfo & theInfo, EModeAcces theMode, TErr * theErr = NULL)
References MED::TPolyedreInfo::myConn, MED::TPolyedreInfo::myConnMode, MED::TElemInfo::myElemNames, MED::TElemInfo::myElemNum, MED::TPolyedreInfo::myEntity, MED::TPolyedreInfo::myFaces, MED::TElemInfo::myFamNum, myFile, MED::TPolyedreInfo::myIndex, MED::TElemInfo::myIsElemNames, MED::TElemInfo::myIsElemNum, MED::TElemInfo::myMeshInfo, MED::TNameInfo::myName, and MED::TElemInfo::myNbElem.
SetPolyedreInfo() [2/2]
void MED::V2_2::TVWrapper::SetPolyedreInfo (const TPolyedreInfo & theInfo, TErr * theErr = NULL) virtual
Write a MEDWrapper MED Polyedres representation from defined MED file.
This feature is support only for version of 2.2 and higher
Reimplemented from MED::TWrapper.
References MED::V2_2::eLECTURE_ECRITURE, and SetPolyedreInfo().
Referenced by SetPolyedreInfo().
SetPolygoneInfo() [1/2]
void MED::V2_2::TVWrapper::SetPolygoneInfo (const MED::TPolygoneInfo & theInfo, EModeAcces theMode, TErr * theErr = NULL)
References MED::TPolygoneInfo::myConn, MED::TPolygoneInfo::myConnMode, MED::TPolygoneInfo::myEntity, myFile, MED::TPolygoneInfo::myGeom, MED::TPolygoneInfo::myIndex, MED::TElemInfo::myMeshInfo, MED::TNameInfo::myName, MED::TElemInfo::myNbElem, SetFamilies(), SetNames(), and SetNumeration().
SetPolygoneInfo() [2/2]
void MED::V2_2::TVWrapper::SetPolygoneInfo (const TPolygoneInfo & theInfo, TErr * theErr = NULL) virtual
Write a MEDWrapper MED Polygones representation from defined MED file.
This feature is supported only for version of 2.2 and higher
Reimplemented from MED::TWrapper.
References MED::V2_2::eLECTURE_ECRITURE, and SetPolygoneInfo().
Referenced by SetPolygoneInfo().
SetProfileInfo() [1/2]
void MED::V2_2::TVWrapper::SetProfileInfo (const TProfileInfo & theInfo, EModeAcces theMode, TErr * theErr = NULL)
References MED::TProfileInfo::GetSize(), MED::TProfileInfo::myElemNum, myFile, and MED::TNameInfo::myName.
SetProfileInfo() [2/2]
void MED::V2_2::TVWrapper::SetProfileInfo (const TProfileInfo & theInfo, TErr * theErr = NULL) virtual
Write a MEDWrapper MED PROFILE representation.
Implements MED::TWrapper.
References MED::V2_2::eCREATION, MED::V2_2::eLECTURE_AJOUT, MED::V2_2::eLECTURE_ECRITURE, and SetProfileInfo().
Referenced by SetProfileInfo().
SetTimeStampValue() [1/2]
void MED::V2_2::TVWrapper::SetTimeStampValue (const PTimeStampValueBase & theTimeStampValue, EModeAcces theMode, TErr * theErr = NULL)
References MED::eNO_PFLMOD, MED::GetNOMLength< eV2_2 >(), and myFile.
SetTimeStampValue() [2/2]
void MED::V2_2::TVWrapper::SetTimeStampValue (const PTimeStampValueBase & theTimeStampValue, TErr * theErr = NULL) virtual
Write the values for MEDWrapper MED TIMESTAMP to defined MED file.
Implements MED::TWrapper.
References MED::V2_2::eLECTURE_AJOUT, MED::V2_2::eLECTURE_ECRITURE, and SetTimeStampValue().
Referenced by SetTimeStampValue().
Member Data Documentation
myFile
PFile MED::V2_2::TVWrapper::myFile protected
Referenced by GetBallGeom(), GetBallInfo(), GetCellInfo(), GetEntityInfo(), GetFamilies(), GetFamilyInfo(), GetFieldInfo(), GetGaussInfo(), GetGaussPreInfo(), GetGrilleInfo(), GetGrilleStruct(), GetGrilleType(), GetMeshInfo(), GetNames(), GetNbBalls(), GetNbCells(), GetNbComp(), GetNbFamAttr(), GetNbFamGroup(), GetNbFamilies(), GetNbFields(), GetNbGauss(), GetNbMeshes(), GetNbNodes(), GetNbProfiles(), GetNbTimeStamps(), GetNodeInfo(), GetNumeration(), GetPolyedreConnSize(), GetPolyedreInfo(), GetPolygoneConnSize(), GetPolygoneInfo(), GetProfileInfo(), GetProfilePreInfo(), GetTimeStampInfo(), GetTimeStampValue(), SetBallInfo(), SetCellInfo(), SetFamilies(), SetFamilyInfo(), SetFieldInfo(), SetGrilleInfo(), SetMeshInfo(), SetNames(), SetNodeInfo(), SetNumeration(), SetPolyedreInfo(), SetPolygoneInfo(), SetProfileInfo(), SetTimeStampValue(), and TVWrapper().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/MED_V2_2_Wrapper.hxx
FreeCAD/src/3rdParty/salomesmesh/src/SMESH/MED_V2_2_Wrapper.cpp