FreeCAD: SpaceNavigatorDevice Class Reference
SpaceNavigatorDevice Class Reference
Public Member Functions
SpaceNavigatorDevice (void)
virtual const SoEvent * translateEvent (QEvent *event)
virtual ~SpaceNavigatorDevice ()
Constructor & Destructor Documentation
SpaceNavigatorDevice()
SpaceNavigatorDevice::SpaceNavigatorDevice (void)
~SpaceNavigatorDevice()
virtual SpaceNavigatorDevice::~SpaceNavigatorDevice () virtual
Member Function Documentation
translateEvent()
virtual const SoEvent* SpaceNavigatorDevice::translateEvent (QEvent * event) virtual
References Base::Console(), Base::ConsoleSingleton::Log(), Spaceball::MotionEvent::MotionEventType, Spaceball::MotionEvent::rotationX(), Spaceball::MotionEvent::rotationY(), Spaceball::MotionEvent::rotationZ(), Spaceball::EventBase::setHandled(), Spaceball::MotionEvent::translationX(), Spaceball::MotionEvent::translationY(), and Spaceball::MotionEvent::translationZ().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/View3DInventorViewer.cpp