FreeCAD: PathTests.TestPathDressupHoldingTags.TestHoldingTags Class Reference
PathTests.TestPathDressupHoldingTags.TestHoldingTags Class Reference
Public Member Functions
def test00 (self)
def test01 (self)
def test02 (self)
def test03 (self)
def test04 (self)
Public Member Functions inherited from PathTests.PathTestUtils.PathTestBase
def assertArc (self, edge, pt1, pt2, direction='CW')
def assertCircle (self, edge, pt, r)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertCommandEqual (self, c1, c2)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertEdgeShapesMatch (self, e1, e2)
def assertEqualLocale (self, s1, s2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertPlacement (self, p1, p2)
def assertPointsMatch (self, pts0, pts1)
def assertRoughly (self, f1, f2, error=0.00001)
Detailed Description
Unit tests for the HoldingTags dressup.
Member Function Documentation
test00()
def PathTests.TestPathDressupHoldingTags.TestHoldingTags.test00 (self)
Check Tag origin.
References PathTests.PathTestUtils.PathTestBase.assertCoincide().
Referenced by PathTests.TestPathTool.TestPathTool.test01(), PathTests.TestPathToolController.TestPathToolController.test01(), PathTests.TestPathTooltable.TestPathTooltable.test01(), PathTests.TestPathTool.TestPathTool.test02(), and PathTests.TestPathTooltable.TestPathTooltable.test02().
test01()
def PathTests.TestPathDressupHoldingTags.TestHoldingTags.test01 (self)
Verify solid for a 90 degree tag is a cylinder.
References PathTests.PathTestUtils.PathTestBase.assertCylinderAt().
test02()
def PathTests.TestPathDressupHoldingTags.TestHoldingTags.test02 (self)
Verify trapezoidal tag has a cone shape with a lid.
References PathTests.PathTestUtils.PathTestBase.assertConeAt().
test03()
def PathTests.TestPathDressupHoldingTags.TestHoldingTags.test03 (self)
Verify pointy cone shape of tag with pointy end if width, angle and height match up.
References PathTests.PathTestUtils.PathTestBase.assertConeAt().
test04()
def PathTests.TestPathDressupHoldingTags.TestHoldingTags.test04 (self)
Verify height adjustment if tag isn't wide eough for angle.
References PathTests.PathTestUtils.PathTestBase.assertConeAt().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Path/PathTests/TestPathDressupHoldingTags.py