FreeCAD: ExpressionDelegate Class Reference
ExpressionDelegate Class Reference
Public Member Functions
ExpressionDelegate (QListWidget *_view)
Protected Member Functions
QPixmap getIcon (const char *name, const QSize &size) const
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Protected Attributes
QListWidget * view
Constructor & Destructor Documentation
ExpressionDelegate()
ExpressionDelegate::ExpressionDelegate (QListWidget * _view)
Member Function Documentation
getIcon()
QPixmap ExpressionDelegate::getIcon (const char * name, const QSize & size) const protected
References Gui::BitmapFactory(), DraftVecUtils::find(), and Gui::BitmapFactoryInst::pixmapFromSvg().
paint()
void ExpressionDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const protected
References ConstraintItem::ConstraintNbr, Sketcher::SketchObject::Constraints, Sketcher::PropertyConstraintList::createPath(), App::PropertyExpressionEngine::ExpressionInfo::expression, App::DocumentObject::getExpression(), Sketcher::PropertyConstraintList::getSize(), Sketcher::Constraint::isDriving, and ConstraintItem::sketch.
Member Data Documentation
view
QListWidget* ExpressionDelegate::view protected
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/Gui/TaskSketcherConstrains.cpp