FreeCAD: Gui::GUIApplicationNativeEventAware Class Reference
Gui::GUIApplicationNativeEventAware Class Reference
#include <GuiApplicationNativeEventAware.h>
Public Member Functions
GUIApplicationNativeEventAware (int &argc, char *argv[])
void initSpaceball (QMainWindow *window)
bool isSpaceballPresent () const
void postButtonEvent (int buttonNumber, int buttonPress)
void postMotionEvent (std::vector< int > motionDataArray)
bool processSpaceballEvent (QObject *object, QEvent *event)
void setSpaceballPresent (bool present)
~GUIApplicationNativeEventAware ()
Constructor & Destructor Documentation
GUIApplicationNativeEventAware()
Gui::GUIApplicationNativeEventAware::GUIApplicationNativeEventAware (int & argc, char * argv[])
~GUIApplicationNativeEventAware()
Gui::GUIApplicationNativeEventAware::~GUIApplicationNativeEventAware ()
Member Function Documentation
initSpaceball()
void Gui::GUIApplicationNativeEventAware::initSpaceball (QMainWindow * window)
References Spaceball::ButtonEvent::ButtonEventType, and Spaceball::MotionEvent::MotionEventType.
Referenced by Gui::Application::runApplication().
isSpaceballPresent()
bool Gui::GUIApplicationNativeEventAware::isSpaceballPresent () const
Referenced by Gui::Dialog::DlgCustomizeSpaceball::DlgCustomizeSpaceball(), and Gui::Dialog::DlgCustomizeSpNavSettings::DlgCustomizeSpNavSettings().
postButtonEvent()
void Gui::GUIApplicationNativeEventAware::postButtonEvent (int buttonNumber, int buttonPress)
References Spaceball::BUTTON_PRESSED, Spaceball::BUTTON_RELEASED, Spaceball::ButtonEvent::setButtonNumber(), and Spaceball::ButtonEvent::setButtonStatus().
postMotionEvent()
void Gui::GUIApplicationNativeEventAware::postMotionEvent (std::vector< int > motionDataArray)
References Spaceball::MotionEvent::setRotations(), and Spaceball::MotionEvent::setTranslations().
processSpaceballEvent()
bool Gui::GUIApplicationNativeEventAware::processSpaceballEvent (QObject * object, QEvent * event)
References Spaceball::ButtonEvent::ButtonEventType, Spaceball::EventBase::isHandled(), Spaceball::MotionEvent::MotionEventType, and femsolver.signal::notify().
Referenced by Gui::GUIApplication::notify().
setSpaceballPresent()
void Gui::GUIApplicationNativeEventAware::setSpaceballPresent (bool present)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/GuiApplicationNativeEventAware.h
Sources/FreeCAD/src/Gui/GuiApplicationNativeEventAware.cpp