FreeCAD: MeshCore::MeshInfo Class Reference
MeshCore::MeshInfo Class Reference
Determines information about the mesh data structure.
#include <Info.h>
Public Member Functions
std::ostream & DetailedInformation (std::ostream &rclStream) const
Writes detailed information about the mesh structure into the stream.
std::ostream & GeneralInformation (std::ostream &rclStream) const
Writes general information about the mesh structure into the stream.
std::ostream & InternalInformation (std::ostream &rclStream) const
Writes internal information about the mesh structure into the stream.
MeshInfo (const MeshKernel &rclM)
std::ostream & TopologyInformation (std::ostream &rclStream) const
Writes topological information about the mesh structure into the stream.
virtual ~MeshInfo (void)
Protected Member Functions
std::ostream & DetailedEdgeInfo (std::ostream &rclStream) const
Writes detailed edge information.
std::ostream & DetailedFacetInfo (std::ostream &rclStream) const
Writes detailed facet information.
std::ostream & DetailedPointInfo (std::ostream &rclStream) const
Writes detailed point information.
std::ostream & InternalFacetInfo (std::ostream &rclStream) const
Writes internal facet information.
std::ostream & InternalPointInfo (std::ostream &rclStream) const
Writes internal point information.
Detailed Description
Determines information about the mesh data structure.
Constructor & Destructor Documentation
MeshInfo()
MeshInfo::MeshInfo (const MeshKernel & rclM)
~MeshInfo()
virtual MeshCore::MeshInfo::~MeshInfo (void) virtual
Member Function Documentation
DetailedEdgeInfo()
std::ostream & MeshInfo::DetailedEdgeInfo (std::ostream & rclStream) const protected
Writes detailed edge information.
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by DetailedInformation().
DetailedFacetInfo()
std::ostream & MeshInfo::DetailedFacetInfo (std::ostream & rclStream) const protected
Writes detailed facet information.
References MeshCore::MeshFacetIterator::End().
Referenced by DetailedInformation().
DetailedInformation()
std::ostream & MeshInfo::DetailedInformation (std::ostream & rclStream) const
Writes detailed information about the mesh structure into the stream.
References DetailedEdgeInfo(), DetailedFacetInfo(), and DetailedPointInfo().
DetailedPointInfo()
std::ostream & MeshInfo::DetailedPointInfo (std::ostream & rclStream) const protected
Writes detailed point information.
References MeshCore::MeshPointIterator::End().
Referenced by DetailedInformation().
GeneralInformation()
std::ostream & MeshInfo::GeneralInformation (std::ostream & rclStream) const
Writes general information about the mesh structure into the stream.
InternalFacetInfo()
std::ostream & MeshInfo::InternalFacetInfo (std::ostream & rclStream) const protected
Writes internal facet information.
Referenced by InternalInformation().
InternalInformation()
std::ostream & MeshInfo::InternalInformation (std::ostream & rclStream) const
Writes internal information about the mesh structure into the stream.
References InternalFacetInfo(), and InternalPointInfo().
InternalPointInfo()
std::ostream & MeshInfo::InternalPointInfo (std::ostream & rclStream) const protected
Writes internal point information.
References MeshCore::MeshPointIterator::End().
Referenced by InternalInformation().
TopologyInformation()
std::ostream & MeshInfo::TopologyInformation (std::ostream & rclStream) const
Writes topological information about the mesh structure into the stream.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Info.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Info.cpp