FreeCAD: Driver_SMDS_Mesh Class Reference
Driver_SMDS_Mesh Class Reference
#include <Driver_SMDS_Mesh.h>
Public Member Functions
Driver_SMDS_Mesh ()
void SetMesh (SMDS_Mesh *theMesh)
Public Member Functions inherited from Driver_Mesh
Driver_Mesh ()
virtual SMESH_ComputeErrorPtr GetError ()
Return a structure containing description of errors.
virtual std::string GetMeshName () const
virtual Status Perform ()=0
virtual void SetFile (const std::string &theFileName)
void SetMeshId (int theMeshId)
virtual void SetMeshName (const std::string &theMeshName)
virtual void SetOption (const std::string &optionName, const std::string &optionValue)
virtual ~Driver_Mesh ()
Protected Attributes
SMDS_Mesh * myMesh
Protected Attributes inherited from Driver_Mesh
std::vector< std::string > myErrorMessages
std::string myFile
int myMeshId
std::string myMeshName
Status myStatus
Additional Inherited Members
Public Types inherited from Driver_Mesh
enum Status {
DRS_OK, DRS_EMPTY, DRS_WARN_RENUMBER, DRS_WARN_SKIP_ELEM,
DRS_WARN_DESCENDING, DRS_FAIL
}
Protected Member Functions inherited from Driver_Mesh
Status addMessage (const std::string &msg, const bool isFatal=false)
Stores an error message.
Constructor & Destructor Documentation
Driver_SMDS_Mesh()
Driver_SMDS_Mesh::Driver_SMDS_Mesh ()
Member Function Documentation
SetMesh()
void Driver_SMDS_Mesh::SetMesh (SMDS_Mesh * theMesh)
References myMesh.
Referenced by SMESH_Mesh::DATToMesh(), SMESH_Mesh::ExportDAT(), SMESH_Mesh::ExportSTL(), SMESH_Mesh::ExportUNV(), SMESH_Mesh::STLToMesh(), and SMESH_Mesh::UNVToMesh().
Member Data Documentation
myMesh
SMDS_Mesh* Driver_SMDS_Mesh::myMesh protected
Referenced by DriverSTL_R_SMDS_Mesh::Perform(), DriverSTL_W_SMDS_Mesh::Perform(), and SetMesh().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/Driver_SMDS_Mesh.h
Sources/FreeCAD/src/3rdParty/salomesmesh/src/Driver/Driver_SMDS_Mesh.cpp