FreeCAD: FemGui::Ui_DlgSettingsFemExportAbaqus Class Reference
FemGui::Ui_DlgSettingsFemExportAbaqus Class Reference
#include <ui_DlgSettingsFemExportAbaqus.h>
Public Member Functions
void retranslateUi (QWidget *FemGui__DlgSettingsFemExportAbaqus)
void setupUi (QWidget *FemGui__DlgSettingsFemExportAbaqus)
Public Attributes
Gui::PrefCheckBox * checkBoxWriteGroups
Gui::PrefComboBox * comboBoxElemChoiceParam
QGridLayout * girdLayoutAbaqus
QGridLayout * gridLayout_3
QGridLayout * gridLayout_4
QGroupBox * groupBox
QLabel * label1
QLabel * label2
QSpacerItem * verticalSpacer
Member Function Documentation
retranslateUi()
void FemGui::Ui_DlgSettingsFemExportAbaqus::retranslateUi (QWidget * FemGui__DlgSettingsFemExportAbaqus)
References checkBoxWriteGroups, comboBoxElemChoiceParam, groupBox, label1, label2, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), FemGui::DlgSettingsFemExportAbaqusImp::changeEvent(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void FemGui::Ui_DlgSettingsFemExportAbaqus::setupUi (QWidget * FemGui__DlgSettingsFemExportAbaqus)
References checkBoxWriteGroups, comboBoxElemChoiceParam, girdLayoutAbaqus, gridLayout_3, gridLayout_4, groupBox, label1, label2, retranslateUi(), and verticalSpacer.
Referenced by FemGui::DlgSettingsFemExportAbaqusImp::DlgSettingsFemExportAbaqusImp().
Member Data Documentation
checkBoxWriteGroups
Gui::PrefCheckBox* FemGui::Ui_DlgSettingsFemExportAbaqus::checkBoxWriteGroups
Referenced by FemGui::DlgSettingsFemExportAbaqusImp::loadSettings(), retranslateUi(), FemGui::DlgSettingsFemExportAbaqusImp::saveSettings(), and setupUi().
comboBoxElemChoiceParam
Gui::PrefComboBox* FemGui::Ui_DlgSettingsFemExportAbaqus::comboBoxElemChoiceParam
Referenced by FemGui::DlgSettingsFemExportAbaqusImp::changeEvent(), FemGui::DlgSettingsFemExportAbaqusImp::loadSettings(), retranslateUi(), FemGui::DlgSettingsFemExportAbaqusImp::saveSettings(), and setupUi().
girdLayoutAbaqus
QGridLayout* FemGui::Ui_DlgSettingsFemExportAbaqus::girdLayoutAbaqus
Referenced by setupUi().
gridLayout_3
QGridLayout* FemGui::Ui_DlgSettingsFemExportAbaqus::gridLayout_3
Referenced by setupUi().
gridLayout_4
QGridLayout* FemGui::Ui_DlgSettingsFemExportAbaqus::gridLayout_4
Referenced by setupUi().
groupBox
QGroupBox* FemGui::Ui_DlgSettingsFemExportAbaqus::groupBox
Referenced by retranslateUi(), and setupUi().
label1
QLabel* FemGui::Ui_DlgSettingsFemExportAbaqus::label1
Referenced by retranslateUi(), and setupUi().
label2
QLabel* FemGui::Ui_DlgSettingsFemExportAbaqus::label2
Referenced by retranslateUi(), and setupUi().
verticalSpacer
QSpacerItem* FemGui::Ui_DlgSettingsFemExportAbaqus::verticalSpacer
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Fem/Gui/ui_DlgSettingsFemExportAbaqus.h