FreeCAD: Base::BaseClass Class Reference
Base::BaseClass Class Reference
BaseClass class and root of the type system.
#include <BaseClass.h>
Public Member Functions
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Protected Member Functions
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
BaseClass class and root of the type system.
Constructor & Destructor Documentation
BaseClass() [1/2]
BaseClass::BaseClass ()
Construction.
A constructor.
A more elaborate description of the constructor.
BaseClass() [2/2]
Base::BaseClass::BaseClass (const BaseClass &) default
~BaseClass()
BaseClass::~BaseClass () virtual
Destruction.
A destructor.
A more elaborate description of the destructor.
Member Function Documentation
create()
static void * Base::BaseClass::create (void) static
Referenced by draftguitools.gui_labels.Label::action(), and init().
getClassTypeId()
Type BaseClass::getClassTypeId (void) static
Referenced by DrawingGui::TaskProjection::accept(), SpreadsheetGui::DlgSheetConf::accept(), TechDrawGui::TaskProjection::accept(), StdCmdImport::activated(), StdCmdEdit::activated(), StdCmdToggleNavigation::activated(), Gui::Application::activateWorkbench(), InspectionGui::ViewProviderProxyObject::addFlag(), SpreadsheetGui::ViewProviderSheet::beforeDelete(), Gui::Document::cloneView(), Part::FaceMaker::ConstructFromType(), Gui::Document::createView(), Gui::WorkbenchManager::createWorkbench(), SketcherGui::DrawSketchHandler::devicePixelRatio(), SketcherGui::ViewProviderSketch::draw(), Sketcher::GeometryFacade::ensureSketchGeometryExtension(), Sketcher::ExternalGeometryFacade::ensureSketchGeometryExtensions(), App::FunctionExpression::evalAggregate(), App::FunctionExpression::evaluate(), MeshGui::ViewProviderMesh::faceInfoCallback(), Gui::Document::getActiveView(), Gui::ViewProvider::getBoundingBox(), TechDrawGui::QGVPage::getDevicePixelRatio(), Gui::Document::getEditingViewOfViewProvider(), Mesh::MeshObject::getFacesFromSubElement(), Part::TopoShape::getFacesFromSubElement(), Sketcher::SketchObject::getGeometryWithDependentParameters(), Part::TopoShape::getLinesFromSubElement(), Gui::ViewProviderTextDocument::getMDIView(), SketcherGui::ViewProviderSketch::getScaleFactor(), Gui::UserNavigationStyle::getUserFriendlyNames(), MeshGui::MeshSelection::getViewer(), Gui::Document::getViewOfNode(), StdViewScreenShot::isActive(), StdCmdToggleNavigation::isActive(), StdCmdMeasureDistance::isActive(), StdCmdTextureMapping::isActive(), Gui::View3DInventorPy::listNavigationTypes(), Gui::Dialog::DlgSettingsNavigation::loadSettings(), Sketcher::SketchObject::migrateSketch(), SketcherGui::ViewProviderSketch::mouseButtonPressed(), Gui::TreeWidget::mouseDoubleClickEvent(), SketcherGui::ViewProviderSketch::mouseMove(), Gui::TreeWidget::onActivateDocument(), Gui::View3DInventor::OnChange(), Gui::GraphicsView3D::OnChange(), Gui::Application::onLastWindowClosed(), SpreadsheetGui::DlgSheetConf::prepare(), Gui::Application::reopen(), Part::Geometry::Restore(), Gui::Application::sActiveView(), Part::Geometry::Save(), Gui::Document::Save(), Gui::Document::setActiveView(), SketcherGui::DrawSketchHandler::setCursor(), Gui::View3DInventorViewer::setNavigationType(), Gui::Application::setupContextMenu(), Gui::Application::slotNewDocument(), SketcherGui::DrawSketchHandler::suggestedConstraintsPixmaps(), SketcherGui::DrawSketchHandler::unsetCursor(), SketcherGui::ViewProviderSketch::updateData(), and SketcherGui::EditModeGeometryCoinManager::updateGeometryColor().
getPyObject()
PyObject * BaseClass::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented in App::PropertyFileIncluded, Base::Exception, Gui::AlignmentView, Gui::MDIView, Gui::SelectionObject, Gui::ViewProvider, Gui::Workbench, Gui::PythonBaseWorkbench, DrawingGui::DrawingView, Fem::FemPostPipeline, FemGui::ViewProviderFemMesh, Mesh::Feature, Mesh::PropertyNormalList, Mesh::PropertyCurvatureList, Mesh::PropertyMeshKernel, MeshGui::ViewProviderMesh, Part::TopoShape, Points::PropertyGreyValueList, Points::PropertyNormalList, Points::PropertyCurvatureList, Points::PropertyPointKernel, Spreadsheet::Sheet, TechDrawGui::MDIViewPage, App::DocumentObjectGroup, App::Part, App::PropertyRotation, Base::FileException, Gui::ViewProviderDocumentObject, Gui::ViewProviderLink, Part::BodyBase, Part::Feature, Part::Primitive, PartDesign::FeaturePrimitive, SpreadsheetGui::ViewProviderSheet, App::GeoFeature, App::InventorObject, App::PropertyMatrix, App::PropertyPythonObject, App::PropertyInteger, App::PropertyPath, App::PropertyEnumeration, App::PropertyIntegerSet, App::PropertyMap, App::PropertyFloat, App::PropertyString, App::PropertyUUID, App::PropertyBool, App::PropertyColor, App::PropertyMaterial, App::PropertyQuantity, App::VRMLObject, Gui::Document, Gui::AbstractSplitView, Gui::View3DInventor, Fem::FemMeshObject, Fem::PropertyFemMesh, Fem::FemResultObject, Fem::FemSetElementsObject, Fem::FemSetFacesObject, Fem::FemSetGeometryObject, Fem::FemSetNodesObject, Fem::FemSetObject, Fem::FemSolverObject, Fem::PropertyPostDataObject, Inspection::PropertyDistanceList, Measure::Measurement, Part::GeomPoint, Part::GeomBezierCurve, Part::GeomBSplineCurve, Part::GeomTrimmedCurve, Part::GeomCircle, Part::GeomArcOfCircle, Part::GeomEllipse, Part::GeomArcOfEllipse, Part::GeomHyperbola, Part::GeomArcOfHyperbola, Part::GeomParabola, Part::GeomArcOfParabola, Part::GeomLine, Part::GeomLineSegment, Part::GeomOffsetCurve, Part::GeomBezierSurface, Part::GeomBSplineSurface, Part::GeomCylinder, Part::GeomCone, Part::GeomSphere, Part::GeomToroid, Part::GeomPlane, Part::GeomOffsetSurface, Part::GeomPlateSurface, Part::GeomTrimmedSurface, Part::GeomSurfaceOfRevolution, Part::GeomSurfaceOfExtrusion, Part::Geom2dPoint, Part::Geom2dBezierCurve, Part::Geom2dBSplineCurve, Part::Geom2dCircle, Part::Geom2dArcOfCircle, Part::Geom2dEllipse, Part::Geom2dArcOfEllipse, Part::Geom2dHyperbola, Part::Geom2dArcOfHyperbola, Part::Geom2dParabola, Part::Geom2dArcOfParabola, Part::Geom2dLine, Part::Geom2dLineSegment, Part::Geom2dOffsetCurve, Part::Geom2dTrimmedCurve, Part::GeometryDefaultExtension< T >, Part::GeometryDefaultExtension< T >, Part::GeometryDefaultExtension< T >, Part::GeometryDefaultExtension< T >, Part::PropertyGeometryList, Part::PropertyPartShape, Part::PropertyShapeHistory, Part::PropertyFilletEdges, PartDesign::Feature, Path::FeatureArea, Path::Feature, Path::FeatureCompound, Path::PropertyPath, Path::PropertyTool, Path::PropertyTooltable, Robot::PropertyTrajectory, Robot::RobotObject, Robot::TrajectoryObject, Spreadsheet::PropertyColumnWidths, Spreadsheet::PropertyRowHeights, SpreadsheetGui::SheetView, TechDraw::CosmeticVertex, TechDraw::CosmeticEdge, TechDraw::CenterLine, TechDraw::GeomFormat, TechDraw::DrawParametricTemplate, TechDraw::DrawRichAnno, TechDraw::DrawSVGTemplate, TechDraw::DrawTemplate, TechDraw::DrawTile, TechDraw::DrawTileWeld, TechDraw::DrawViewClip, TechDraw::DrawViewDimExtent, TechDraw::DrawWeldSymbol, TechDraw::PropertyCenterLineList, TechDraw::PropertyCosmeticEdgeList, TechDraw::PropertyCosmeticVertexList, TechDraw::PropertyGeomFormatList, WebGui::BrowserView, App::Document, App::DocumentObject, App::PropertyExpressionEngine, App::PropertyVector, App::PropertyVectorList, App::PropertyPlacement, App::PropertyPlacementList, App::PropertyLink, App::PropertyLinkList, App::PropertyLinkSub, App::PropertyLinkSubList, App::PropertyXLink, App::PropertyXLinkSub, App::PropertyXLinkSubList, App::PropertyXLinkList, App::PropertyIntegerList, App::PropertyFloatList, App::PropertyStringList, App::PropertyBoolList, App::PropertyColorList, App::PropertyMaterialList, App::PropertyPersistentObject, Gui::LinkView, Part::GeometryDefaultExtension< T >, Part::GeometryMigrationExtension, PartDesign::Body, PartDesignGui::ViewProvider, Sketcher::Constraint, Sketcher::ExternalGeometryExtension, Sketcher::ExternalGeometryFacade, Sketcher::GeometryFacade, Sketcher::PropertyConstraintList, Sketcher::SketchGeometryExtension, Sketcher::SketchObject, Sketcher::SolverGeometryExtension, SketcherGui::ViewProviderSketchGeometryExtension, Spreadsheet::PropertySheet, TechDraw::DrawGeomHatch, TechDraw::DrawHatch, TechDraw::DrawLeaderLine, TechDraw::DrawPage, TechDraw::DrawProjGroup, TechDraw::DrawProjGroupItem, TechDraw::DrawView, TechDraw::DrawViewDimension, TechDraw::DrawViewPart, TechDraw::DrawViewSymbol, Part::GeomConic, Part::GeomArcOfConic, Part::Geom2dConic, Part::Geom2dArcOfConic, and Part::GeometryExtension.
Referenced by Sandbox::DocumentObjectProtectorPy::getattr(), and Spreadsheet::PropertySheet::getPyValue().
getTypeId()
Type BaseClass::getTypeId (void) const virtual
Reimplemented in Base::Exception, and Base::Persistence.
Referenced by Gui::Document::cloneView(), Mesh::MeshObject::getFacesFromSubElement(), Part::TopoShape::getFacesFromSubElement(), Part::TopoShape::getLinesFromSubElement(), Gui::View3DInventorPy::getNavigationType(), App::Expression::isSame(), Gui::TreeView::mouseDoubleClickEvent(), Gui::NavigationStyle::openPopupMenu(), Attacher::AttachEngine::readLinks(), Gui::TreeView::rowsInserted(), Part::GeometryPersistenceExtension::Save(), Part::AttachExtension::setAttacher(), Gui::View3DInventorViewer::setNavigationType(), and Gui::Application::setupContextMenu().
init()
void BaseClass::init (void) static
References Base::Type::badType(), create(), and Base::Type::createType().
Referenced by Gui::DocumentModel::DocumentModel(), WebGui::BrowserView::getPyObject(), Gui::SoFCDB::init(), App::Application::initTypes(), Gui::Application::initTypes(), and DocumentObject.DocumentObject::onChanged().
initSubclass()
void BaseClass::initSubclass (Base::Type & toInit, const char * ClassName, const char * ParentName, Type::instantiationMethod method = nullptr) static protected
References Base::Type::badType(), Base::Type::createType(), and Base::Type::fromName().
isDerivedFrom()
bool Base::BaseClass::isDerivedFrom (const Type type) const
References Base::Type::isDerivedFrom().
Referenced by StdCmdToggleSelectability::activated(), Gui::Application::activateView(), PartDesign::Body::addObject(), TechDraw::DrawPage::addView(), SurfaceGui::FillingPanel::ShapeSelection::allow(), SurfaceGui::FillingEdgePanel::ShapeSelection::allow(), SurfaceGui::FillingVertexPanel::VertexSelection::allow(), SurfaceGui::SectionsPanel::ShapeSelection::allow(), SurfaceGui::GeomFillSurface::EdgeSelection::allow(), TechDrawGui::ViewProviderDimension::attach(), Gui::ViewProviderLink::attach(), TechDrawGui::TaskRichAnno::calcTextStartPos(), Part::Extrusion::calculateShapeNormal(), Gui::ViewProviderDocumentObject::canDelete(), App::PropertyExpressionEngine::canonicalPath(), PartDesignGui::ViewProviderHelix::claimChildren(), PartDesignGui::ViewProviderPipe::claimChildren(), PartDesignGui::ViewProviderSketchBased::claimChildren(), TechDrawGui::ViewProviderPage::claimChildren(), Gui::TreeWidget::contextMenuEvent(), Sketcher::SketchObject::convertToNURBS(), SpreadsheetGui::SheetModel::data(), Gui::SoFCUnifiedSelection::doAction(), TechDrawGui::QGIViewDimension::draw(), SketcherGui::ViewProviderSketch::draw(), TechDrawGui::QGIViewBalloon::drawBalloon(), Drawing::FeatureViewSpreadsheet::execute(), PartDesign::FeatureBase::execute(), PartDesign::Loft::execute(), PartDesign::Pipe::execute(), Path::FeatureAreaView::execute(), Surface::Cut::execute(), TechDraw::DrawViewDetail::execute(), Fem::FemVTKTools::exportFreeCADResult(), App::Document::exportGraphviz(), Spreadsheet::Sheet::exportToFile(), Sketcher::SketchObject::fillet(), ImportGui::ExportOCAFGui::findColors(), App::Origin::getAxis(), PartDesign::ProfileBased::getBaseObject(), PartDesign::Transformed::getBaseObject(), PartDesign::Feature::getBaseShape(), PartDesign::Feature::getBaseTopoShape(), App::PropertyFileIncluded::getDocTransientPath(), Spreadsheet::Cell::getFormattedQuantity(), App::OriginGroupExtension::getGroupOfObject(), Gui::View3DInventorPy::getObjectInfo(), Gui::View3DInventorPy::getObjectsInfo(), App::OriginGroupExtension::getOrigin(), TechDrawGui::QGIDrawingTemplate::getParametricTemplate(), App::Origin::getPlane(), PartDesign::ProfileBased::getProfileWires(), PartDesignGui::getReferencedSelection(), SketcherGui::ViewProviderSketch::getScaleFactor(), Path::FeatureAreaView::getShapes(), TechDraw::DrawViewSpreadsheet::getSheetImage(), PartDesign::Transformed::getSketchObject(), TechDrawGui::QGISVGTemplate::getSVGTemplate(), Gui::LinkInfo::getView(), Part::Part2DObject::handleChangedPropertyType(), TechDraw::DrawView::handleChangedPropertyType(), PartDesignGui::ViewProviderShapeBinder::highlightReferences(), PartDesign::Body::insertObject(), App::GeoFeatureGroupExtension::isLinkValid(), App::PropertyLinkBase::isSame(), Import::ImportOCAF2::loadShapes(), PartGui::OffsetWidget::OffsetWidget(), App::Document::onBeforeChangeProperty(), Fem::FemPostClipFilter::onChanged(), Fem::FemPostCutFilter::onChanged(), App::OriginGroupExtension::onExtendedSetupObject(), PartDesignGui::TaskLinearPatternParameters::onSelectionChanged(), PartDesignGui::TaskMirroredParameters::onSelectionChanged(), PartDesignGui::TaskPolarPatternParameters::onSelectionChanged(), Gui::PropertyView::onTimer(), Gui::Dialog::find_placement::operator()(), App::DocumentObjectT::operator=(), PartDesignGui::TaskTransformedParameters::originalSelected(), App::PropertyLink::Paste(), App::PropertyLinkList::Paste(), App::PropertyLinkSub::Paste(), App::PropertyLinkSubList::Paste(), App::PropertyXLink::Paste(), App::PropertyXLinkSubList::Paste(), PartDesign::ProfileBased::positionByPrevious(), Attacher::AttachEngine::readLinks(), PartDesign::Body::removeObject(), TechDraw::DrawPage::removeView(), App::PropertyLink::resetLink(), App::PropertyLink::Restore(), App::PropertyLinkSub::Restore(), App::PropertyXLink::Restore(), Fem::PropertyPostDataObject::RestoreDocFile(), Path::PropertyPath::RestoreDocFile(), Gui::Application::sActiveView(), Fem::PropertyPostDataObject::SaveDocFile(), Part::Part2DObject::seekTrimPoints(), App::PropertyLinkList::set1Value(), PartDesign::Body::setBaseProperty(), Gui::ViewProviderDragger::setEdit(), App::LinkBaseExtension::setProperty(), PartDesignGui::Workbench::setupContextMenu(), App::Origin::setupObject(), Gui::RecoveryWriter::shouldWrite(), Gui::Document::slotActivatedObject(), Gui::Document::slotChangedObject(), Gui::ViewProviderOriginGroupExtension::slotChangedObjectGui(), PartDesignGui::ViewProviderBody::slotChangedObjectGui(), Gui::Document::slotFinishRestoreDocument(), Gui::Document::slotRelabelObject(), Gui::Document::slotTransactionAppend(), Sketcher::SketchObject::split(), App::PropertyXLink::supportXLink(), PartDesignGui::TaskRevolutionParameters::TaskRevolutionParameters(), Sketcher::SketchObject::trim(), Gui::ViewProviderGeometryObject::updateData(), Gui::ViewProviderInventorObject::updateData(), Gui::ViewProviderVRMLObject::updateData(), FemGui::ViewProviderFemMesh::updateData(), Gui::ViewProviderDragger::updateData(), SketcherGui::ViewProviderSketch::updateData(), TechDrawGui::ViewProviderTemplate::updateData(), PartDesignGui::ViewProviderBody::updateData(), PartDesignGui::ViewProviderBody::updateOriginDatumSize(), Gui::ViewProviderOriginGroupExtension::updateOriginSize(), TechDrawGui::MDIViewPage::updateTemplate(), Gui::RecoveryWriter::writeFiles(), App::PropertyLinkList::~PropertyLinkList(), App::PropertyLinkSub::~PropertyLinkSub(), App::PropertyLinkSubList::~PropertyLinkSubList(), and PartDesignGui::TaskDatumParameters::~TaskDatumParameters().
operator=()
BaseClass & Base::BaseClass::operator= (const BaseClass &) default
setPyObject()
void BaseClass::setPyObject (PyObject *) virtual
Reimplemented in App::PropertyFileIncluded, App::PropertyMatrix, App::PropertyPythonObject, App::PropertyInteger, App::PropertyPath, App::PropertyEnumeration, App::PropertyIntegerConstraint, App::PropertyIntegerSet, App::PropertyMap, App::PropertyFloat, App::PropertyFloatConstraint, App::PropertyString, App::PropertyUUID, App::PropertyBool, App::PropertyColor, App::PropertyMaterial, App::PropertyQuantity, App::PropertyQuantityConstraint, Gui::AbstractSplitView, Inspection::PropertyDistanceList, Mesh::PropertyNormalList, Part::PropertyGeometryList, Part::PropertyShapeHistory, Part::PropertyFilletEdges, Part::TopoShape, Points::PropertyGreyValueList, Points::PropertyNormalList, Points::PropertyCurvatureList, TechDraw::PropertyCenterLineList, TechDraw::PropertyCosmeticEdgeList, TechDraw::PropertyCosmeticVertexList, TechDraw::PropertyGeomFormatList, App::PropertyExpressionEngine, App::PropertyVector, App::PropertyPlacement, App::PropertyRotation, App::PropertyLink, App::PropertyLinkSub, App::PropertyLinkSubList, App::PropertyXLink, App::PropertyXLinkSubList, App::PropertyXLinkList, App::PropertyBoolList, Sketcher::PropertyConstraintList, Spreadsheet::PropertySheet, App::PropertyLists, App::PropertyLinkListBase, Base::Exception, Base::FileException, Fem::PropertyFemMesh, Fem::PropertyPostDataObject, Mesh::PropertyCurvatureList, Mesh::PropertyMeshKernel, Part::PropertyPartShape, Path::PropertyPath, Path::PropertyTool, Path::PropertyTooltable, Points::PropertyPointKernel, Robot::PropertyTrajectory, App::PropertyListsT< T, ListT, ParentT >, App::PropertyListsT< bool, boost::dynamic_bitset<> >, App::PropertyListsT< Color >, App::PropertyListsT< double >, App::PropertyListsT< long >, App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >, App::PropertyListsT< Material >, App::PropertyListsT< Base::Placement >, App::PropertyListsT< std::string >, and App::PropertyListsT< Base::Vector3d >.
The documentation for this class was generated from the following files:
FreeCAD/src/Base/BaseClass.h
FreeCAD/src/Base/BaseClass.cpp