FreeCAD: iisTaskHeader Class Reference
iisTaskHeader Class Reference
#include <iistaskheader.h>
Public Slots
void fold ()
Signals
void activated ()
Public Member Functions
iisTaskHeader (const QIcon &icon, const QString &title, bool expandable, QWidget *parent=0)
void setScheme (iisTaskPanelScheme *scheme)
virtual ~iisTaskHeader ()
Protected Slots
void animate ()
Protected Member Functions
void changeIcons ()
virtual void enterEvent (QEvent *event)
bool eventFilter (QObject *obj, QEvent *event)
virtual void leaveEvent (QEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void paintEvent (QPaintEvent *event)
Protected Attributes
bool m_buttonOver
bool m_fold
double m_opacity
bool m_over
QLabel * myButton
bool myExpandable
iisIconLabelScheme * myLabelScheme
iisTaskPanelScheme * myScheme
iisIconLabel * myTitle
Constructor & Destructor Documentation
iisTaskHeader()
iisTaskHeader::iisTaskHeader (const QIcon & icon, const QString & title, bool expandable, QWidget * parent = 0)
References activated(), changeIcons(), draftgeoutils.intersections::connect(), iisTaskPanelScheme::defaultScheme(), fold(), iisTaskPanelScheme::headerButtonSize, myButton, myExpandable, myLabelScheme, myScheme, myTitle, setScheme(), and iisIconLabel::setSchemePointer().
~iisTaskHeader()
iisTaskHeader::~iisTaskHeader () virtual
Member Function Documentation
activated
void iisTaskHeader::activated () signal
Referenced by fold(), iisTaskHeader(), and mouseReleaseEvent().
animate
void iisTaskHeader::animate () protected slot
References iisTaskPanelScheme::headerAnimation, m_opacity, m_over, and myScheme.
Referenced by enterEvent(), and leaveEvent().
changeIcons()
void iisTaskHeader::changeIcons () protected
References iisTaskPanelScheme::headerButtonFold, iisTaskPanelScheme::headerButtonFoldOver, iisTaskPanelScheme::headerButtonSize, iisTaskPanelScheme::headerButtonUnfold, iisTaskPanelScheme::headerButtonUnfoldOver, m_buttonOver, m_fold, myButton, and myScheme.
Referenced by eventFilter(), fold(), iisTaskHeader(), and setScheme().
enterEvent()
void iisTaskHeader::enterEvent (QEvent * event) protected virtual
References animate(), and m_over.
eventFilter()
bool iisTaskHeader::eventFilter (QObject * obj, QEvent * event) protected
References changeIcons(), fold(), and m_buttonOver.
fold
void iisTaskHeader::fold () slot
References activated(), changeIcons(), m_fold, and myExpandable.
Referenced by eventFilter(), and iisTaskHeader().
leaveEvent()
void iisTaskHeader::leaveEvent (QEvent * event) protected virtual
References animate(), and m_over.
mouseReleaseEvent()
void iisTaskHeader::mouseReleaseEvent (QMouseEvent * event) protected virtual
References activated().
paintEvent()
void iisTaskHeader::paintEvent (QPaintEvent * event) protected virtual
References iisTaskPanelScheme::headerAnimation, iisTaskPanelScheme::headerBackground, iisTaskPanelScheme::headerBorder, m_opacity, and myScheme.
setScheme()
void iisTaskHeader::setScheme (iisTaskPanelScheme * scheme)
References changeIcons(), iisIconLabelScheme::cursorOver, iisTaskPanelScheme::headerLabelScheme, iisTaskPanelScheme::headerSize, myExpandable, myLabelScheme, and myScheme.
Referenced by iisTaskHeader(), and iisTaskBox::setScheme().
Member Data Documentation
m_buttonOver
bool iisTaskHeader::m_buttonOver protected
Referenced by changeIcons(), and eventFilter().
m_fold
bool iisTaskHeader::m_fold protected
Referenced by changeIcons(), and fold().
m_opacity
double iisTaskHeader::m_opacity protected
Referenced by animate(), and paintEvent().
m_over
bool iisTaskHeader::m_over protected
Referenced by animate(), enterEvent(), and leaveEvent().
myButton
QLabel* iisTaskHeader::myButton protected
Referenced by changeIcons(), and iisTaskHeader().
myExpandable
bool iisTaskHeader::myExpandable protected
Referenced by fold(), iisTaskHeader(), and setScheme().
myLabelScheme
iisIconLabelScheme* iisTaskHeader::myLabelScheme protected
Referenced by iisTaskHeader(), and setScheme().
myScheme
iisTaskPanelScheme* iisTaskHeader::myScheme protected
Referenced by animate(), changeIcons(), iisTaskHeader(), paintEvent(), and setScheme().
myTitle
iisIconLabel* iisTaskHeader::myTitle protected
Referenced by iisTaskHeader().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/iisTaskPanel/src/iistaskheader.h
Sources/FreeCAD/src/Gui/iisTaskPanel/src/iistaskheader.cpp