FreeCAD: TechDraw::DrawViewPart Class Reference
TechDraw::DrawViewPart Class Reference
#include <DrawViewPart.h>
Public Member Functions
int add1CEToGE (std::string tag)
int add1CLToGE (std::string tag)
int add1CVToGV (std::string tag)
void addCenterLinesToGeom (void)
void addCosmeticEdgesToGeom (void)
void addCosmeticVertexesToGeom (void)
void addReferencesToGeom (void)
std::string addReferenceVertex (Base::Vector3d v)
void clearCenterLines (void)
void clearCosmeticEdges (void)
void clearCosmeticVertexes (void)
void clearGeomFormats (void)
DrawViewPart (void)
void dumpCosEdges (const std::string text)
void dumpCosVerts (const std::string text)
void dumpVerts (const std::string text)
virtual App::DocumentObjectExecReturn * execute (void) override
recalculate the Feature
std::vector< App::DocumentObject * > getAllSources (void) const
std::vector< TechDraw::DrawViewBalloon * > getBalloons () const
virtual Base::BoundBox3d getBoundingBox () const
double getBoxX (void) const
double getBoxY (void) const
int getCVIndex (std::string tag)
virtual std::vector< DrawViewDetail * > getDetailRefs () const
std::vector< TechDraw::DrawViewDimension * > getDimensions () const
const std::vector< TechDraw::BaseGeom * > getEdgeGeometry () const
std::vector< TechDraw::BaseGeom * > getFaceEdgesByIndex (int idx) const
returns existing geometry of 2D Face(idx)
const std::vector< TechDraw::Face * > getFaceGeometry () const
TechDraw::BaseGeom * getGeomByIndex (int idx) const
returns existing BaseGeom of 2D Edge(idx)
TechDraw::GeometryObject * getGeometryObject (void) const
std::vector< TechDraw::DrawGeomHatch * > getGeomHatches (void) const
std::vector< TechDraw::DrawHatch * > getHatches (void) const
virtual Base::Vector3d getLegacyX (const Base::Vector3d &pt, const Base::Vector3d &axis, const bool flip=true) const
virtual Base::Vector3d getOriginalCentroid (void) const
virtual gp_Ax2 getProjectionCS (Base::Vector3d pt) const
TechDraw::Vertex * getProjVertexByCosTag (std::string cosTag)
TechDraw::Vertex * getProjVertexByIndex (int idx) const
returns existing geometry of 2D Vertex(idx)
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
virtual QRectF getRect () const override
virtual std::vector< DrawViewSection * > getSectionRefs () const
virtual TopoDS_Shape getSourceShape (void) const
virtual std::vector< TopoDS_Shape > getSourceShape2d (void) const
virtual TopoDS_Shape getSourceShapeFused (void) const
const std::vector< TechDraw::Vertex * > getVertexGeometry () const
virtual gp_Ax2 getViewAxis (const Base::Vector3d &pt, const Base::Vector3d &direction, const bool flip=true) const
virtual const char * getViewProviderName (void) const override
returns the type name of the ViewProvider
const std::vector< TechDraw::BaseGeom * > getVisibleFaceEdges () const
virtual std::vector< TopoDS_Wire > getWireForFace (int idx) const
virtual Base::Vector3d getXDirection (void) const
bool handleFaces (void)
bool hasGeometry (void) const
bool isIso (void) const
is this an Isometric projection?
bool isUnsetting (void)
virtual short mustExecute () const override
mustExecute We call this method to check if the object was modified to be invoked.
virtual void onDocumentRestored () override
get called after a document has been fully restored
virtual BaseGeom * projectEdge (const TopoDS_Edge &e) const
virtual Base::Vector3d projectPoint (const Base::Vector3d &pt, bool invert=true) const
void refreshCEGeoms (void)
void refreshCLGeoms (void)
void refreshCVGeoms (void)
void removeAllReferencesFromGeom ()
void removeReferenceVertex (std::string tag)
void resetReferenceVerts ()
void updateReferenceVert (std::string tag, Base::Vector3d loc2d)
virtual ~DrawViewPart ()
Public Member Functions inherited from TechDraw::DrawView
DrawView (void)
Constructor.
virtual ~DrawView ()
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, App::Property *prop) override
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
bool isInClip ()
DrawViewClip * getClipGroup (void)
virtual DrawPage * findParentPage () const
virtual double autoScale (void) const
virtual double autoScale (double w, double h) const
virtual bool checkFit (void) const
virtual bool checkFit (DrawPage *) const
check if View is too big for page
virtual void setPosition (double x, double y, bool force=false)
virtual bool keepUpdated (void)
virtual double getScale (void) const
void checkScale (void)
void requestPaint (void)
virtual void handleXYLock (void)
virtual bool isLocked (void) const
virtual bool showLock (void) const
std::vector< TechDraw::DrawLeaderLine * > getLeaders (void) const
Public Member Functions inherited from App::DocumentObject
virtual App::Property * addDynamicProperty (const char *type, const char *name=0, const char *group=0, const char *doc=0, short attr=0, bool ro=false, bool hidden=false) override
virtual bool adjustRelativeLinks (const std::set< App::DocumentObject * > &inList, std::set< App::DocumentObject * > *visited=0)
Called to adjust link properties to avoid cyclic links.
virtual bool allowDuplicateLabel () const
virtual bool canLinkProperties () const
virtual int canLoadPartial () const
allow partial loading of dependent objects
void clearOutListCache () const
clear internal out list cache
virtual const char * detachFromDocument () override
DocumentObject (void)
Constructor.
void enforceRecompute ()
Enforce this document object to be recomputed.
App::Document * getDocument (void) const
gets the document in which this Object is handled
std::string getExportName (bool forced=false) const
returns the name that is safe to be exported to other document
virtual const PropertyExpressionEngine::ExpressionInfo getExpression (const ObjectIdentifier &path) const
virtual std::string getFullName () const override
Return the object full name of the form DocName::ObjName.
DocumentObjectGroup * getGroup () const
get group if object is part of a group, otherwise 0 is returned
long getID () const
Return the object ID that is unique within its owner document.
const std::vector< App::DocumentObject * > & getInList (void) const
std::set< App::DocumentObject * > getInListEx (bool recursive) const
Return a set of all objects linking to this object, including possible external parent objects.
void getInListEx (std::set< App::DocumentObject * > &inSet, bool recursive, std::vector< App::DocumentObject * > *inList=0) const
Get a set of all objects linking to this object, including possible external parent objects.
std::vector< App::DocumentObject * > getInListRecursive (void) const
get all objects link directly or indirectly to this object
virtual DocumentObject * getLinkedObject (bool recurse=true, Base::Matrix4D *mat=0, bool transform=false, int depth=0) const
Return the linked object with optional transformation.
const char * getNameInDocument (void) const
returns the name which is set in the document for this object (not the name property!)
const std::string & getOldLabel () const
const std::vector< App::DocumentObject * > & getOutList () const
returns a list of objects this object is pointing to by Links
std::vector< App::DocumentObject * > getOutList (int option) const
void getOutList (int option, std::vector< App::DocumentObject * > &res) const
std::vector< App::DocumentObject * > getOutListOfProperty (App::Property *) const
returns a list of objects linked by the property
std::vector< App::DocumentObject * > getOutListRecursive (void) const
returns a list of objects this object is pointing to by Links and all further descended
std::vector< std::pair< App::DocumentObject *, std::string > > getParents (int depth=0) const
Obtain top parents and subnames of this object using its InList.
std::vector< std::list< App::DocumentObject * > > getPathsByOutList (App::DocumentObject *to) const
get all possible paths from this to another object following the OutList
unsigned long getStatus () const
return the status bits
const char * getStatusString (void) const
get the status Message
virtual DocumentObject * getSubObject (const char *subname, PyObject **pyObj=0, Base::Matrix4D *mat=0, bool transform=true, int depth=0) const
Get the sub element/object by name.
std::vector< DocumentObject * > getSubObjectList (const char *subname) const
Return a list of objects referenced by a given subname including this object.
virtual std::vector< std::string > getSubObjects (int reason=0) const
Return name reference of all sub-objects.
virtual const char * getViewProviderNameOverride () const
This function is introduced to allow Python feature override its view provider.
const char * getViewProviderNameStored () const
virtual bool hasChildElement () const
return true to activate tree view group object handling and element visibility
virtual bool isAttachedToDocument () const override
virtual int isElementVisible (const char *element) const
Get sub-element visibility.
bool isError (void) const
set this feature to error
int isExporting () const
bool isInInList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the InList
bool isInInListRecursive (DocumentObject *objToTest) const
test if this object is in the InList and recursive further down
bool isInOutList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the OutList
bool isInOutListRecursive (DocumentObject *objToTest) const
test if the given object is in the OutList and recursive further down
bool isRecomputing () const
returns true if this objects is currently recomputing
bool isRemoving () const
returns true if this objects is currently removed from the document
bool isRestoring () const
returns true if this objects is currently restoring from file
bool isTouched (void) const
test if this document object is touched
bool isValid (void) const
bool mustRecompute (void) const
Test if this document object must be recomputed.
virtual void onBeforeChangeLabel (std::string &newLabel)
virtual void onLostLinkToObject (DocumentObject *)
Called in case of losing a link Get called by the document when a object got deleted a link property of this object ist pointing to.
virtual void onUpdateElementReference (const Property *)
void purgeError (void)
remove the error from the object
void purgeTouched (void)
reset this document object touched
bool recomputeFeature (bool recursive=false)
Recompute only this feature.
virtual bool redirectSubName (std::ostringstream &ss, DocumentObject *topParent, DocumentObject *child) const
Allow object to redirect a subname path.
virtual bool removeDynamicProperty (const char *prop) override
virtual void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths)
App::DocumentObject * resolve (const char *subname, App::DocumentObject **parent=0, std::string *childName=0, const char **subElement=0, PyObject **pyObj=0, Base::Matrix4D *mat=0, bool transform=true, int depth=0) const
Resolve the last document object referenced in the subname.
App::DocumentObject * resolveRelativeLink (std::string &subname, App::DocumentObject *&link, std::string &linkSub) const
Resolve a link reference that is relative to this object reference.
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
virtual int setElementVisible (const char *element, bool visible)
Child element handling.
virtual void setExpression (const ObjectIdentifier &path, boost::shared_ptr< App::Expression > expr)
void setStatus (ObjectStatus pos, bool on)
bool testIfLinkDAGCompatible (App::PropertyLinkSub &linkTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSubList &linksTo) const
bool testIfLinkDAGCompatible (const std::vector< DocumentObject * > &linksTo) const
bool testIfLinkDAGCompatible (DocumentObject *linkTo) const
testIfLinkIsDAG tests a link that is about to be created for circular references.
bool testStatus (ObjectStatus pos) const
void touch (bool noRecompute=false)
Set the property touched -> changed, cause recomputation in Update()
virtual ~DocumentObject ()
Public Member Functions inherited from App::TransactionalObject
TransactionalObject (void)
Constructor.
virtual ~TransactionalObject ()
Public Member Functions inherited from App::ExtensionContainer
ExtensionIterator extensionBegin ()
ExtensionContainer ()
ExtensionIterator extensionEnd ()
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
void registerExtension (Base::Type extension, App::Extension *ext)
virtual ~ExtensionContainer ()
virtual Property * getPropertyByName (const char *name) const override
find a property by its name
virtual const char * getPropertyName (const Property *prop) const override
get the name of a property
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
virtual void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
virtual short getPropertyType (const Property *prop) const override
get the Type of a Property
virtual short getPropertyType (const char *name) const override
get the Type of a named Property
virtual const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
virtual void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
Public Member Functions inherited from App::PropertyContainer
virtual App::Property * getDynamicPropertyByName (const char *name) const
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
const char * getPropertyPrefix () const
bool isHidden (const char *name) const
check if the named property is hidden
bool isHidden (const Property *prop) const
check if the property is hidden
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isReadOnly (const Property *prop) const
check if the property is read-only
PropertyContainer ()
A constructor.
void setPropertyPrefix (const char *prefix)
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
virtual ~PropertyContainer ()
A destructor.
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from TechDraw::CosmeticExtension
virtual std::string addCenterLine (Base::Vector3d start, Base::Vector3d end)
virtual std::string addCenterLine (TechDraw::BaseGeom *bg)
virtual std::string addCenterLine (TechDraw::CenterLine *cl)
virtual std::string addCosmeticEdge (Base::Vector3d start, Base::Vector3d end)
virtual std::string addCosmeticEdge (TechDraw::BaseGeom *bg)
virtual std::string addCosmeticVertex (Base::Vector3d pos)
virtual std::string addGeomFormat (TechDraw::GeomFormat *gf)
CosmeticExtension ()
virtual CenterLine * getCenterLine (std::string tag) const
virtual CenterLine * getCenterLineBySelection (int i) const
virtual CenterLine * getCenterLineBySelection (std::string name) const
virtual CosmeticEdge * getCosmeticEdge (std::string id) const
virtual CosmeticEdge * getCosmeticEdgeBySelection (int i) const
virtual CosmeticEdge * getCosmeticEdgeBySelection (std::string name) const
virtual CosmeticVertex * getCosmeticVertex (std::string id) const
virtual CosmeticVertex * getCosmeticVertexBySelection (int i) const
virtual CosmeticVertex * getCosmeticVertexBySelection (std::string name) const
PyObject * getExtensionPyObject (void)
virtual GeomFormat * getGeomFormat (std::string id) const
virtual GeomFormat * getGeomFormatBySelection (int i) const
virtual GeomFormat * getGeomFormatBySelection (std::string name) const
virtual void removeCenterLine (std::string tag)
virtual void removeCenterLine (std::vector< std::string > delTags)
virtual void removeCosmeticEdge (std::string tag)
virtual void removeCosmeticEdge (std::vector< std::string > delTags)
virtual void removeCosmeticVertex (std::string tag)
virtual void removeCosmeticVertex (std::vector< std::string > delTags)
virtual void removeGeomFormat (std::string tag)
virtual bool replaceCenterLine (CenterLine *newLine)
virtual bool replaceCosmeticEdge (CosmeticEdge *newEdge)
virtual bool replaceCosmeticVertex (CosmeticVertex *newVertex)
virtual bool replaceGeomFormat (TechDraw::GeomFormat *gf)
virtual ~CosmeticExtension ()
Public Member Functions inherited from App::DocumentObjectExtension
DocumentObjectExtension ()
virtual App::DocumentObjectExecReturn * extensionExecute (void)
virtual bool extensionGetLinkedObject (DocumentObject *&ret, bool recursive, Base::Matrix4D *mat, bool transform, int depth) const
Get the linked object.
virtual bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const
Get the sub object by name.
virtual bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const
Get name references of all sub objects.
virtual bool extensionHasChildElement () const
virtual int extensionIsElementVisible (const char *)
virtual short extensionMustExecute (void)
virtual int extensionSetElementVisible (const char *, bool)
App::DocumentObject * getExtendedObject ()
const App::DocumentObject * getExtendedObject () const
virtual const char * getViewProviderExtensionName (void) const
returns the type name of the ViewProviderExtension which is automatically attached to the viewprovider object when it is initiated
virtual void onExtendedDocumentRestored ()
get called after a document has been fully restored
virtual void onExtendedSettingDocument ()
get called after setting the document
virtual void onExtendedSetupObject ()
get called after a brand new object was created
virtual void onExtendedUnsetupObject ()
get called when object is going to be removed from the document
virtual ~DocumentObjectExtension ()
Public Member Functions inherited from App::Extension
Extension ()
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
virtual void initExtension (App::ExtensionContainer *obj)
bool isPythonExtension ()
std::string name () const
virtual ~Extension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Public Attributes
App::PropertyBool CoarseView
App::PropertyVector Direction
App::PropertyDistance Focus
App::PropertyBool HardHidden
App::PropertyInteger IsoCount
App::PropertyBool IsoHidden
App::PropertyBool IsoVisible
App::PropertyBool Perspective
App::PropertyBool SeamHidden
App::PropertyBool SeamVisible
App::PropertyBool SmoothHidden
App::PropertyBool SmoothVisible
App::PropertyLinkList Source
App::PropertyVector XDirection
App::PropertyXLinkList XSource
Public Attributes inherited from TechDraw::DrawView
App::PropertyString Caption
App::PropertyBool LockPosition
App::PropertyAngle Rotation
App::PropertyFloatConstraint Scale
App::PropertyEnumeration ScaleType
App::PropertyDistance X
App::PropertyDistance Y
boost::signals2::signal< void(const DrawView *)> signalGuiPaint
Public Attributes inherited from App::DocumentObject
PropertyExpressionEngine ExpressionEngine
PropertyString Label
PropertyString Label2
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChange
signal before changing a property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChanged
signal on changed property of this object
PropertyBool Visibility
Allow control visibility status in App name space.
Public Attributes inherited from TechDraw::CosmeticExtension
TechDraw::PropertyCenterLineList CenterLines
TechDraw::PropertyCosmeticEdgeList CosmeticEdges
TechDraw::PropertyCosmeticVertexList CosmeticVertexes
TechDraw::PropertyGeomFormatList GeomFormats
Protected Member Functions
virtual void addShapes2d (void)
virtual TechDraw::GeometryObject * buildGeometryObject (TopoDS_Shape shape, gp_Ax2 viewAxis)
bool checkXDirection (void) const
void extractFaces ()
make faces from the existing edge geometry
void getRunControl (void)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container.
virtual TechDraw::GeometryObject * makeGeometryForShape (TopoDS_Shape shape)
virtual void onChanged (const App::Property *prop) override
get called by the container when a property was changed
void partExec (TopoDS_Shape shape)
bool prefHardHid (void)
bool prefHardViz (void)
int prefIsoCount (void)
bool prefIsoHid (void)
bool prefIsoViz (void)
bool prefSeamHid (void)
bool prefSeamViz (void)
bool prefSmoothHid (void)
bool prefSmoothViz (void)
virtual void unsetupObject () override
remove features that are useless without this DVP hatches, geomhatches, dimensions,...
Protected Member Functions inherited from TechDraw::DrawView
int prefScaleType (void)
double prefScale (void)
Protected Member Functions inherited from App::DocumentObject
App::DocumentObjectExecReturn * executeExtensions ()
Executes the extensions of a document object.
virtual void onBeforeChange (const Property *prop) override
get called before the value is changed
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus) override
get called when a property status has changed
virtual void onSettingDocument ()
get called after setting the document
virtual void onUndoRedoFinished ()
get called after an undo/redo transaction is finished
virtual App::DocumentObjectExecReturn * recompute (void)
recompute only this object
void resetError (void)
void setDocument (App::Document *doc)
void setError (void)
virtual void setupObject ()
get called after a brand new object was created
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData (void) const
Protected Member Functions inherited from App::Extension
virtual void extensionOnChanged (const Property *p)
void initExtensionType (Base::Type type)
Protected Attributes
Base::BoundBox3d bbox
TechDraw::GeometryObject * geometryObject
bool m_handleFaces
std::vector< TechDraw::Vertex * > m_referenceVerts
Base::Vector3d m_saveCentroid
TopoDS_Shape m_saveShape
Base::Vector3d shapeCentroid
Protected Attributes inherited from TechDraw::DrawView
std::string pageFeatName
bool autoPos
bool mouseMove
Protected Attributes inherited from App::DocumentObject
std::string oldLabel
Old label; used for renaming expressions.
const std::string * pcNameInDocument
Py::Object PythonObject
python object of this class and all descendent
std::bitset< 32 > StatusBits
Status bits of the document object The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::Object ExtensionPythonObject
Additional Inherited Members
Public Types inherited from App::DocumentObject
enum GSReason { GS_DEFAULT, GS_SELECT }
reason of calling getSubObjects()
enum OutListOption { OutListNoExpression = 1, OutListNoHidden = 2, OutListNoXLinked = 4 }
DAG handling This part of the interface deals with viewing the document as a DAG (directed acyclic graph).
Public Types inherited from App::ExtensionContainer
typedef std::map< Base::Type, App::Extension * >::iterator ExtensionIterator
Static Public Member Functions inherited from App::DocumentObject
static const char * hasHiddenMarker (const char *subname)
Check if the subname reference ends with hidden marker.
static const std::string & hiddenMarker ()
Special marker to mark the object as hidden.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Public Attributes inherited from App::DocumentObject
static DocumentObjectExecReturn * StdReturn
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Static Protected Member Functions inherited from App::Extension
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=0)
Constructor & Destructor Documentation
DrawViewPart()
TechDraw::DrawViewPart::DrawViewPart (void)
~DrawViewPart()
DrawViewPart::~DrawViewPart () virtual
References geometryObject, and removeAllReferencesFromGeom().
Member Function Documentation
add1CEToGE()
int DrawViewPart::add1CEToGE (std::string tag)
References TechDraw::GeometryObject::addCosmeticEdge(), Base::Console(), geometryObject, TechDraw::CosmeticExtension::getCosmeticEdge(), TechDraw::DrawView::getScale(), Base::ConsoleSingleton::Message(), and TechDraw::CosmeticEdge::scaledGeometry().
Referenced by TechDrawGui::TaskCosmeticLine::accept(), TechDraw::DrawViewPartPy::makeCosmeticCircle(), TechDraw::DrawViewPartPy::makeCosmeticCircleArc(), TechDraw::DrawViewPartPy::makeCosmeticLine(), and TechDraw::DrawViewPartPy::makeCosmeticLine3D().
add1CLToGE()
int DrawViewPart::add1CLToGE (std::string tag)
References TechDraw::GeometryObject::addCenterLine(), Base::Console(), geometryObject, TechDraw::CosmeticExtension::getCenterLine(), Base::ConsoleSingleton::Message(), and TechDraw::CenterLine::scaledGeometry().
Referenced by TechDraw::DrawViewPartPy::makeCenterLine().
add1CVToGV()
int DrawViewPart::add1CVToGV (std::string tag)
References TechDraw::GeometryObject::addCosmeticVertex(), Base::Console(), geometryObject, TechDraw::CosmeticExtension::getCosmeticVertex(), TechDraw::DrawView::getScale(), TechDraw::CosmeticVertex::getTagAsString(), TechDraw::CosmeticVertex::linkGeom, Base::ConsoleSingleton::Message(), and TechDraw::CosmeticVertex::scaled().
Referenced by TechDraw::DrawViewPartPy::makeCosmeticVertex(), TechDraw::DrawViewPartPy::makeCosmeticVertex3d(), and TechDraw::DrawDimHelper::makeDistDim().
addCenterLinesToGeom()
void DrawViewPart::addCenterLinesToGeom (void)
References TechDraw::GeometryObject::addCenterLine(), TechDraw::CosmeticExtension::CenterLines, Base::Console(), Base::ConsoleSingleton::Error(), geometryObject, TechDraw::BaseGeom::getTagAsString(), and TechDraw::PropertyCenterLineList::getValues().
Referenced by partExec(), and refreshCLGeoms().
addCosmeticEdgesToGeom()
void DrawViewPart::addCosmeticEdgesToGeom (void)
References TechDraw::GeometryObject::addCosmeticEdge(), TechDraw::CosmeticExtension::CosmeticEdges, geometryObject, TechDraw::DrawView::getScale(), TechDraw::BaseGeom::getTagAsString(), and TechDraw::PropertyCosmeticEdgeList::getValues().
Referenced by partExec(), and refreshCEGeoms().
addCosmeticVertexesToGeom()
void DrawViewPart::addCosmeticVertexesToGeom (void)
References TechDraw::GeometryObject::addCosmeticVertex(), TechDraw::CosmeticExtension::CosmeticVertexes, geometryObject, TechDraw::DrawView::getScale(), and TechDraw::PropertyCosmeticVertexList::getValues().
Referenced by partExec(), and refreshCVGeoms().
addReferencesToGeom()
void DrawViewPart::addReferencesToGeom (void)
References getGeometryObject(), getVertexGeometry(), m_referenceVerts, and TechDraw::GeometryObject::setVertexGeometry().
Referenced by TechDraw::LandmarkDimension::execute(), partExec(), and resetReferenceVerts().
addReferenceVertex()
std::string DrawViewPart::addReferenceVertex (Base::Vector3d v)
References m_referenceVerts.
Referenced by TechDraw::LandmarkDimension::execute(), and TechDraw::LandmarkDimension::onDocumentRestored().
addShapes2d()
void DrawViewPart::addShapes2d (void) protected virtual
References TechDraw::GeometryObject::addVertex(), geometryObject, TechDraw::DrawView::getScale(), getSourceShape2d(), m_saveCentroid, and projectPoint().
Referenced by execute().
buildGeometryObject()
TechDraw::GeometryObject * DrawViewPart::buildGeometryObject (TopoDS_Shape shape, gp_Ax2 viewAxis) protected virtual
References bbox, TechDraw::GeometryObject::calcBoundingBox(), CoarseView, Base::Console(), TechDraw::ecHARD, TechDraw::ecOUTLINE, TechDraw::ecSEAM, TechDraw::ecSMOOTH, TechDraw::ecUVISO, TechDraw::GeometryObject::extractGeometry(), Focus, TechDraw::GeometryObject::getEdgeGeometry(), App::DocumentObject::getNameInDocument(), App::PropertyInteger::getValue(), App::PropertyBool::getValue(), App::PropertyQuantity::getValue(), HardHidden, IsoCount, IsoHidden, IsoVisible, TechDraw::GeometryObject::isPerspective(), Base::ConsoleSingleton::Log(), Perspective, TechDraw::GeometryObject::projectShape(), TechDraw::GeometryObject::projectShapeWithPolygonAlgo(), SeamHidden, SeamVisible, TechDraw::GeometryObject::setFocus(), TechDraw::GeometryObject::setIsoCount(), SmoothHidden, SmoothVisible, and TechDraw::GeometryObject::usePolygonHLR().
Referenced by makeGeometryForShape().
checkXDirection()
bool DrawViewPart::checkXDirection (void) const protected
References Base::Console(), Direction, TechDraw::DrawUtil::formatVector(), TechDraw::DrawUtil::fpCompare(), getLegacyX(), App::DocumentObject::getNameInDocument(), App::PropertyVector::getValue(), Base::Vector3< _Precision >::Length(), Base::ConsoleSingleton::Log(), and XDirection.
Referenced by TechDraw::DrawProjGroupItem::execute(), and execute().
clearCenterLines()
void DrawViewPart::clearCenterLines (void)
References TechDraw::CosmeticExtension::CenterLines, and TechDraw::PropertyCenterLineList::setValues().
Referenced by TechDraw::DrawViewPartPy::clearCenterLines().
clearCosmeticEdges()
void DrawViewPart::clearCosmeticEdges (void)
References TechDraw::CosmeticExtension::CosmeticEdges, and TechDraw::PropertyCosmeticEdgeList::setValues().
Referenced by TechDraw::DrawViewPartPy::clearCosmeticEdges().
clearCosmeticVertexes()
void DrawViewPart::clearCosmeticVertexes (void)
References TechDraw::CosmeticExtension::CosmeticVertexes, and TechDraw::PropertyCosmeticVertexList::setValues().
Referenced by TechDraw::DrawViewPartPy::clearCosmeticVertices().
clearGeomFormats()
void DrawViewPart::clearGeomFormats (void)
References TechDraw::CosmeticExtension::GeomFormats, TechDraw::PropertyGeomFormatList::getValues(), and TechDraw::PropertyGeomFormatList::setValues().
Referenced by TechDraw::DrawViewPartPy::clearGeomFormats().
dumpCosEdges()
void DrawViewPart::dumpCosEdges (const std::string text)
References Base::Console(), TechDraw::CosmeticExtension::CosmeticEdges, TechDraw::PropertyCosmeticEdgeList::getValues(), and Base::ConsoleSingleton::Message().
dumpCosVerts()
void DrawViewPart::dumpCosVerts (const std::string text)
References Base::Console(), TechDraw::CosmeticExtension::CosmeticVertexes, TechDraw::PropertyCosmeticVertexList::getValues(), and Base::ConsoleSingleton::Message().
dumpVerts()
void DrawViewPart::dumpVerts (const std::string text)
References Base::Console(), geometryObject, getVertexGeometry(), and Base::ConsoleSingleton::Message().
execute()
App::DocumentObjectExecReturn * DrawViewPart::execute (void) override virtual
recalculate the Feature
Reimplemented from TechDraw::DrawView.
Reimplemented in TechDraw::DrawViewSection, TechDraw::DrawViewMulti, TechDraw::DrawViewDetail, and TechDraw::DrawProjGroupItem.
References addShapes2d(), TechDraw::DrawView::autoScale(), TechDraw::DrawView::checkFit(), checkXDirection(), Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::DrawView::execute(), geometryObject, getAllSources(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), getSourceShape(), getXDirection(), App::DocumentObject::isRestoring(), App::PropertyEnumeration::isValue(), TechDraw::DrawView::keepUpdated(), m_saveShape, partExec(), App::Property::purgeTouched(), TechDraw::DrawView::Scale, TechDraw::DrawView::ScaleType, App::PropertyVector::setValue(), App::PropertyFloat::setValue(), App::DocumentObject::StdReturn, Base::ConsoleSingleton::Warning(), and XDirection.
Referenced by ArchSite.Compass::buildCoordinates(), TechDraw::DrawProjGroupItem::execute(), ArchSchedule.CommandArchSchedule::IsActive(), and FeaturePython.DistanceBolt::onChanged().
extractFaces()
void DrawViewPart::extractFaces () protected
make faces from the existing edge geometry
References TechDraw::GeometryObject::addFaceGeom(), TechDraw::GeometryObject::clearFaceGeom(), Base::Console(), geometryObject, App::DocumentObject::getNameInDocument(), TechDraw::EdgeWalker::getResultNoDups(), App::PropertyBool::getValue(), TechDraw::GeometryObject::getVisibleFaceEdges(), TechDraw::splitPoint::i, TechDraw::DrawProjectSplit::isOnEdge(), TechDraw::DrawUtil::isZeroEdge(), TechDraw::EdgeWalker::loadEdges(), Base::ConsoleSingleton::Log(), draftguitools.gui_annotationstyleeditor::param, TechDraw::splitPoint::param, TechDraw::EdgeWalker::perform(), TechDraw::DrawProjectSplit::removeDuplicateEdges(), SeamVisible, SmoothVisible, TechDraw::DrawProjectSplit::sortSplits(), TechDraw::EdgeWalker::sortStrip(), TechDraw::DrawProjectSplit::splitEdges(), TechDraw::DrawProjectSplit::splitEqual(), TechDraw::splitPoint::v, and Base::ConsoleSingleton::Warning().
Referenced by partExec().
getAllSources()
std::vector< App::DocumentObject * > DrawViewPart::getAllSources (void) const
References App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyXLinkSubList::getValues(), Source, and XSource.
Referenced by execute(), getSourceShape(), getSourceShape2d(), and getSourceShapeFused().
getBalloons()
std::vector< TechDraw::DrawViewBalloon * > DrawViewPart::getBalloons () const
References Base::Persistence::getClassTypeId(), and App::DocumentObject::getInList().
Referenced by unsetupObject().
getBoundingBox()
Base::BoundBox3d DrawViewPart::getBoundingBox () const virtual
References bbox.
Referenced by TechDraw::DrawProjGroup::getBoundingBox(), getBoxX(), getBoxY(), and TechDraw::DrawProjGroup::makeViewBbs().
getBoxX()
double DrawViewPart::getBoxX (void) const
References getBoundingBox(), Base::BoundBox3< _Precision >::MaxX, and Base::BoundBox3< _Precision >::MinX.
Referenced by TechDrawGui::QGIViewPart::drawCenterLines(), and getRect().
getBoxY()
double DrawViewPart::getBoxY (void) const
References getBoundingBox(), Base::BoundBox3< _Precision >::MaxY, and Base::BoundBox3< _Precision >::MinY.
Referenced by TechDrawGui::QGIViewPart::drawCenterLines(), and getRect().
getCVIndex()
int DrawViewPart::getCVIndex (std::string tag)
References TechDraw::CosmeticExtension::CosmeticVertexes, TechDraw::PropertyCosmeticVertexList::getValues(), and getVertexGeometry().
getDetailRefs()
std::vector< DrawViewDetail * > DrawViewPart::getDetailRefs (void) const virtual
References Base::Persistence::getClassTypeId(), and App::DocumentObject::getInList().
Referenced by TechDrawGui::ViewProviderProjGroup::onDelete(), and TechDrawGui::ViewProviderProjGroupItem::onDelete().
getDimensions()
std::vector< TechDraw::DrawViewDimension * > DrawViewPart::getDimensions () const
References Base::Persistence::getClassTypeId(), and App::DocumentObject::getInList().
Referenced by unsetupObject().
getEdgeGeometry()
const std::vector< TechDraw::BaseGeom * > DrawViewPart::getEdgeGeometry () const
References geometryObject, and TechDraw::GeometryObject::getEdgeGeometry().
Referenced by TechDraw::CenterLine::calcEndPoints2Lines(), getGeomByIndex(), TechDraw::DrawViewPartPy::getHiddenEdges(), TechDraw::DrawViewPartPy::getVisibleEdges(), hasGeometry(), TechDraw::DrawDimHelper::minMax(), refreshCEGeoms(), refreshCLGeoms(), and TechDrawGui::TaskCenterLine::TaskCenterLine().
getFaceEdgesByIndex()
std::vector< TechDraw::BaseGeom * > DrawViewPart::getFaceEdgesByIndex (int idx) const
returns existing geometry of 2D Face(idx)
References Base::Console(), getFaceGeometry(), Base::ConsoleSingleton::Log(), and TechDraw::Face::wires.
Referenced by TechDraw::CenterLine::calcEndPoints().
getFaceGeometry()
const std::vector< TechDraw::Face * > DrawViewPart::getFaceGeometry () const
References geometryObject, and TechDraw::GeometryObject::getFaceGeometry().
Referenced by getFaceEdgesByIndex(), and getWireForFace().
getGeomByIndex()
TechDraw::BaseGeom * DrawViewPart::getGeomByIndex (int idx) const
returns existing BaseGeom of 2D Edge(idx)
References Base::Console(), getEdgeGeometry(), and Base::ConsoleSingleton::Log().
Referenced by TechDrawGui::TaskLineDecor::applyDecorations(), TechDraw::CenterLine::calcEndPoints2Lines(), TechDraw::DrawViewDimension::checkReferences2D(), TechDraw::DrawViewDimension::execute(), TechDraw::CosmeticExtension::getCenterLineBySelection(), TechDraw::CosmeticExtension::getCosmeticEdgeBySelection(), TechDrawGui::TaskLineDecor::getDefaults(), TechDraw::DrawViewPartPy::getEdgeByIndex(), TechDraw::DrawViewPartPy::getEdgeBySelection(), TechDraw::DrawViewDimension::getPointsEdgeVert(), TechDraw::DrawViewDimension::getPointsOneEdge(), TechDraw::DrawViewDimension::getPointsTwoEdges(), TechDraw::DrawViewDimension::leaderIntersectsArc(), and TechDraw::DrawDimHelper::minMax().
getGeometryObject()
TechDraw::GeometryObject* TechDraw::DrawViewPart::getGeometryObject (void) const
Referenced by addReferencesToGeom(), refreshCEGeoms(), refreshCLGeoms(), refreshCVGeoms(), and removeAllReferencesFromGeom().
getGeomHatches()
std::vector< TechDraw::DrawGeomHatch * > DrawViewPart::getGeomHatches (void) const
References Base::Persistence::getClassTypeId(), and App::DocumentObject::getInList().
Referenced by unsetupObject().
getHatches()
std::vector< TechDraw::DrawHatch * > DrawViewPart::getHatches (void) const
References Base::Persistence::getClassTypeId(), and App::DocumentObject::getInList().
Referenced by unsetupObject().
getLegacyX()
Base::Vector3d DrawViewPart::getLegacyX (const Base::Vector3d & pt, const Base::Vector3d & axis, const bool flip = true) const virtual
Reimplemented in TechDraw::DrawProjGroupItem.
References TechDraw::legacyViewAxis1().
Referenced by checkXDirection(), and getXDirection().
getOriginalCentroid()
Base::Vector3d DrawViewPart::getOriginalCentroid (void) const virtual
References m_saveCentroid.
Referenced by TechDrawGui::TaskCosmeticLine::createCosmeticLine(), TechDraw::DrawViewPartPy::makeCosmeticLine3D(), TechDraw::DrawViewPartPy::makeCosmeticVertex3d(), TechDraw::LandmarkDimension::projectPoint(), and TechDrawGui::TaskSectionView::setUiPrimary().
getProjectionCS()
gp_Ax2 DrawViewPart::getProjectionCS (Base::Vector3d pt) const virtual
References Base::Console(), Direction, App::DocumentObject::getNameInDocument(), App::PropertyVector::getValue(), getXDirection(), Base::ConsoleSingleton::Warning(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by TechDraw::DrawViewDetail::detailExec(), TechDraw::DrawProjGroup::getDirsFromFront(), TechDraw::DrawProjGroupItem::getRotateAngle(), getViewAxis(), makeGeometryForShape(), projectEdge(), projectPoint(), and TechDraw::LandmarkDimension::projectPoint().
getProjVertexByCosTag()
TechDraw::Vertex * DrawViewPart::getProjVertexByCosTag (std::string cosTag)
References Base::Console(), getVertexGeometry(), and Base::ConsoleSingleton::Log().
Referenced by TechDraw::DrawViewDimExtent::execute(), and TechDraw::DrawViewDimExtent::getPointsTwoVerts().
getProjVertexByIndex()
TechDraw::Vertex * DrawViewPart::getProjVertexByIndex (int idx) const
returns existing geometry of 2D Vertex(idx)
References Base::Console(), getVertexGeometry(), and Base::ConsoleSingleton::Log().
Referenced by TechDraw::CenterLine::calcEndPoints2Points(), TechDraw::DrawViewDimension::checkReferences2D(), TechDraw::DrawViewDimension::execute(), TechDraw::CosmeticExtension::getCosmeticVertexBySelection(), TechDraw::DrawViewDimension::getPointsEdgeVert(), TechDraw::DrawViewDimension::getPointsTwoVerts(), TechDraw::DrawViewPartPy::getVertexByIndex(), TechDraw::DrawViewPartPy::getVertexBySelection(), and TechDraw::DrawDimHelper::makeExtentDim().
getPyObject()
PyObject * DrawViewPart::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from TechDraw::DrawView.
Reimplemented in TechDraw::DrawProjGroupItem.
References App::DocumentObject::PythonObject.
getRect()
QRectF DrawViewPart::getRect (void) const override virtual
Reimplemented from TechDraw::DrawView.
References getBoxX(), and getBoxY().
getRunControl()
void TechDraw::DrawViewPart::getRunControl (void) protected
getSectionRefs()
std::vector< DrawViewSection * > DrawViewPart::getSectionRefs (void) const virtual
References Base::Persistence::getClassTypeId(), and App::DocumentObject::getInList().
Referenced by TechDrawGui::QGIViewPart::drawAllSectionLines(), TechDrawGui::ViewProviderProjGroup::onDelete(), and TechDrawGui::ViewProviderProjGroupItem::onDelete().
getSourceShape()
TopoDS_Shape DrawViewPart::getSourceShape (void) const virtual
References Base::Console(), Base::ConsoleSingleton::Error(), getAllSources(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), TechDraw::ShapeExtractor::getShapes(), App::DocumentObject::isRestoring(), App::Document::testStatus(), and Base::ConsoleSingleton::Warning().
Referenced by execute(), and TechDraw::DrawViewSection::execute().
getSourceShape2d()
std::vector< TopoDS_Shape > DrawViewPart::getSourceShape2d (void) const virtual
References getAllSources(), and TechDraw::ShapeExtractor::getShapes2d().
Referenced by addShapes2d().
getSourceShapeFused()
TopoDS_Shape DrawViewPart::getSourceShapeFused (void) const virtual
References Base::Console(), Base::ConsoleSingleton::Error(), getAllSources(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), TechDraw::ShapeExtractor::getShapesFused(), App::DocumentObject::isRestoring(), App::Document::testStatus(), and Base::ConsoleSingleton::Warning().
Referenced by TechDraw::DrawViewDetail::execute(), and TechDraw::DrawViewSection::execute().
getVertexGeometry()
const std::vector< TechDraw::Vertex * > DrawViewPart::getVertexGeometry () const
References geometryObject, and TechDraw::GeometryObject::getVertexGeometry().
Referenced by addReferencesToGeom(), dumpVerts(), getCVIndex(), getProjVertexByCosTag(), getProjVertexByIndex(), hasGeometry(), refreshCVGeoms(), and removeAllReferencesFromGeom().
getViewAxis()
gp_Ax2 DrawViewPart::getViewAxis (const Base::Vector3d & pt, const Base::Vector3d & direction, const bool flip = true) const virtual
Reimplemented in TechDraw::DrawProjGroupItem.
References Base::Console(), getProjectionCS(), and Base::ConsoleSingleton::Message().
getViewProviderName()
virtual const char* TechDraw::DrawViewPart::getViewProviderName (void) const override virtual
returns the type name of the ViewProvider
Reimplemented from TechDraw::DrawView.
Reimplemented in TechDraw::DrawViewSection, TechDraw::DrawViewMulti, TechDraw::DrawViewDetail, and TechDraw::DrawProjGroupItem.
getVisibleFaceEdges()
const std::vector< TechDraw::BaseGeom * > DrawViewPart::getVisibleFaceEdges () const
References geometryObject, App::PropertyBool::getValue(), TechDraw::GeometryObject::getVisibleFaceEdges(), SeamVisible, and SmoothVisible.
getWireForFace()
std::vector< TopoDS_Wire > DrawViewPart::getWireForFace (int idx) const virtual
References getFaceGeometry(), TechDraw::EdgeWalker::makeCleanWire(), and TechDraw::Face::wires.
getXDirection()
Base::Vector3d DrawViewPart::getXDirection (void) const virtual
Reimplemented in TechDraw::DrawViewSection, and TechDraw::DrawProjGroupItem.
References Direction, TechDraw::DrawUtil::fpCompare(), getLegacyX(), App::ExtensionContainer::getPropertyByName(), App::PropertyVector::getValue(), Base::Vector3< _Precision >::Length(), and XDirection.
Referenced by execute(), getProjectionCS(), and TechDraw::DrawProjGroupItem::getXDirection().
handleChangedPropertyName()
void DrawViewPart::handleChangedPropertyName (Base::XMLReader & reader, const char * TypeName, const char * PropName) override protected virtual
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container.
This method is typically called if the property on file has changed its name in more recent versions.
The default implementation does nothing.
Parameters
reader The XML stream to read from.
TypeName Name of property type on file.
PropName Name of property on file that does not exist in the container anymore.
Reimplemented from App::PropertyContainer.
References App::PropertyContainer::handleChangedPropertyName().
handleFaces()
bool DrawViewPart::handleFaces (void)
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by partExec().
hasGeometry()
bool DrawViewPart::hasGeometry (void) const
References geometryObject, getEdgeGeometry(), and getVertexGeometry().
Referenced by TechDrawGui::QGIViewBalloon::draw(), TechDrawGui::QGIViewDimension::draw(), and TechDrawGui::QGIViewPart::drawSectionLine().
isIso()
bool DrawViewPart::isIso (void) const
is this an Isometric projection?
References Direction, TechDraw::DrawUtil::fpCompare(), App::PropertyVector::getValue(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
isUnsetting()
bool TechDraw::DrawViewPart::isUnsetting (void)
Referenced by TechDraw::DrawProjGroupItem::unsetupObject().
makeGeometryForShape()
GeometryObject * DrawViewPart::makeGeometryForShape (TopoDS_Shape shape) protected virtual
References buildGeometryObject(), TechDraw::findCentroid(), TechDraw::DrawUtil::fpCompare(), getProjectionCS(), TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), m_saveCentroid, m_saveShape, TechDraw::moveShape(), TechDraw::rotateShape(), TechDraw::DrawView::Rotation, and TechDraw::scaleShape().
Referenced by partExec().
mustExecute()
short DrawViewPart::mustExecute () const override virtual
mustExecute We call this method to check if the object was modified to be invoked.
If the object label or an argument is modified. If we must recompute the object - to call the method execute(). 0: no recomputation is needed 1: recomputation needed
Remarks
If an object is marked as 'touched' then this does not necessarily mean that it will be recomputed. It only means that all objects that link it (i.e. its InList) will be recomputed.
Reimplemented from TechDraw::DrawView.
Reimplemented in TechDraw::DrawViewSection, TechDraw::DrawViewMulti, TechDraw::DrawViewDetail, and TechDraw::DrawProjGroupItem.
References CoarseView, Direction, Focus, HardHidden, IsoCount, IsoHidden, IsoVisible, App::DocumentObject::isRestoring(), App::Property::isTouched(), TechDraw::DrawView::mustExecute(), Perspective, TechDraw::DrawView::Rotation, SeamHidden, SeamVisible, SmoothHidden, SmoothVisible, Source, and XSource.
Referenced by TechDraw::DrawProjGroupItem::mustExecute(), and TechDraw::DrawViewMulti::mustExecute().
onChanged()
void DrawViewPart::onChanged (const App::Property * prop) override protected virtual
get called by the container when a property was changed
Reimplemented from TechDraw::DrawView.
Reimplemented in TechDraw::DrawViewSection, TechDraw::DrawViewMulti, TechDraw::DrawViewDetail, and TechDraw::DrawProjGroupItem.
References TechDraw::DrawView::onChanged().
Referenced by ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), TechDraw::DrawProjGroupItem::onChanged(), and TechDraw::DrawViewMulti::onChanged().
onDocumentRestored()
void DrawViewPart::onDocumentRestored () override virtual
get called after a document has been fully restored
Reimplemented from TechDraw::DrawView.
Reimplemented in TechDraw::DrawViewSection, and TechDraw::DrawProjGroupItem.
References TechDraw::DrawView::onDocumentRestored(), and App::DocumentObject::recomputeFeature().
Referenced by TechDraw::DrawViewSection::onDocumentRestored().
partExec()
void DrawViewPart::partExec (TopoDS_Shape shape) protected
References addCenterLinesToGeom(), addCosmeticEdgesToGeom(), addCosmeticVertexesToGeom(), addReferencesToGeom(), Base::Console(), extractFaces(), geometryObject, App::DocumentObject::getNameInDocument(), handleFaces(), Base::ConsoleSingleton::Log(), makeGeometryForShape(), and TechDraw::GeometryObject::usePolygonHLR().
Referenced by execute().
prefHardHid()
bool DrawViewPart::prefHardHid (void) protected
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
prefHardViz()
bool DrawViewPart::prefHardViz (void) protected
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
prefIsoCount()
int DrawViewPart::prefIsoCount (void) protected
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
prefIsoHid()
bool DrawViewPart::prefIsoHid (void) protected
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
prefIsoViz()
bool DrawViewPart::prefIsoViz (void) protected
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
prefSeamHid()
bool DrawViewPart::prefSeamHid (void) protected
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
prefSeamViz()
bool DrawViewPart::prefSeamViz (void) protected
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
prefSmoothHid()
bool DrawViewPart::prefSmoothHid (void) protected
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
prefSmoothViz()
bool DrawViewPart::prefSmoothViz (void) protected
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
projectEdge()
BaseGeom * DrawViewPart::projectEdge (const TopoDS_Edge & e) const virtual
References getProjectionCS().
projectPoint()
Base::Vector3d DrawViewPart::projectPoint (const Base::Vector3d & pt, bool invert = true) const virtual
References getProjectionCS(), TechDraw::DrawUtil::invertY(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by addShapes2d(), TechDrawGui::TaskCosmeticLine::createCosmeticLine(), TechDrawGui::QGIViewPart::drawSectionLine(), TechDraw::DrawViewPartPy::makeCosmeticLine3D(), and TechDraw::DrawViewPartPy::makeCosmeticVertex3d().
refreshCEGeoms()
void DrawViewPart::refreshCEGeoms (void)
References addCosmeticEdgesToGeom(), getEdgeGeometry(), getGeometryObject(), and TechDraw::GeometryObject::setEdgeGeometry().
Referenced by TechDrawGui::TaskCosmeticLine::accept().
refreshCLGeoms()
void DrawViewPart::refreshCLGeoms (void)
References addCenterLinesToGeom(), getEdgeGeometry(), getGeometryObject(), and TechDraw::GeometryObject::setEdgeGeometry().
Referenced by TechDrawGui::TaskCenterLine::updateCenterLine().
refreshCVGeoms()
void DrawViewPart::refreshCVGeoms (void)
References addCosmeticVertexesToGeom(), getGeometryObject(), getVertexGeometry(), and TechDraw::GeometryObject::setVertexGeometry().
Referenced by TechDraw::DrawViewPartPy::makeCosmeticVertex3d(), and TechDraw::DrawViewPartPy::removeCosmeticVertex().
removeAllReferencesFromGeom()
void DrawViewPart::removeAllReferencesFromGeom ()
References getGeometryObject(), getVertexGeometry(), m_referenceVerts, and TechDraw::GeometryObject::setVertexGeometry().
Referenced by resetReferenceVerts(), and ~DrawViewPart().
removeReferenceVertex()
void DrawViewPart::removeReferenceVertex (std::string tag)
References m_referenceVerts, and resetReferenceVerts().
Referenced by TechDraw::LandmarkDimension::unsetupObject().
resetReferenceVerts()
void DrawViewPart::resetReferenceVerts ()
References addReferencesToGeom(), and removeAllReferencesFromGeom().
Referenced by removeReferenceVertex(), and TechDraw::LandmarkDimension::unsetupObject().
unsetupObject()
void DrawViewPart::unsetupObject (void) override protected virtual
remove features that are useless without this DVP hatches, geomhatches, dimensions,...
Reimplemented from App::DocumentObject.
Reimplemented in TechDraw::DrawViewSection, TechDraw::DrawViewDetail, and TechDraw::DrawProjGroupItem.
References TechDraw::DrawView::findParentPage(), getBalloons(), getDimensions(), App::DocumentObject::getDocument(), getGeomHatches(), getHatches(), Base::Interpreter(), TechDraw::DrawPage::removeView(), and Base::InterpreterSingleton::runStringArg().
Referenced by TechDraw::DrawProjGroupItem::unsetupObject(), and TechDraw::DrawViewSection::unsetupObject().
updateReferenceVert()
void DrawViewPart::updateReferenceVert (std::string tag, Base::Vector3d loc2d)
References m_referenceVerts.
Referenced by TechDraw::LandmarkDimension::execute().
Member Data Documentation
bbox
Base::BoundBox3d TechDraw::DrawViewPart::bbox protected
Referenced by buildGeometryObject(), and getBoundingBox().
CoarseView
App::PropertyBool TechDraw::DrawViewPart::CoarseView
Referenced by buildGeometryObject(), and mustExecute().
Direction
App::PropertyVector TechDraw::DrawViewPart::Direction
Referenced by checkXDirection(), TechDraw::DrawViewDetail::detailExec(), TechDraw::DrawProjGroupItem::execute(), TechDraw::DrawProjGroup::getAnchorDirection(), TechDraw::DrawProjGroup::getDirsFromFront(), getProjectionCS(), TechDraw::DrawProjGroupItem::getRotateAngle(), TechDraw::DrawProjGroupItem::getViewAxis(), getXDirection(), isIso(), TechDraw::DrawProjGroupItem::mustExecute(), mustExecute(), TechDrawGui::TaskSectionView::restoreSectionState(), TechDraw::DrawProjGroup::rotateDown(), TechDraw::DrawProjGroup::rotateLeft(), TechDraw::DrawProjGroup::rotateRight(), TechDraw::DrawProjGroup::rotateUp(), TechDrawGui::TaskProjGroup::saveGroupState(), TechDrawGui::TaskSectionView::saveSectionState(), TechDraw::DrawProjGroup::setAnchorDirection(), TechDraw::DrawProjGroup::spinCCW(), TechDraw::DrawProjGroup::spinCW(), and TechDraw::DrawProjGroup::updateSecondaryDirs().
Focus
App::PropertyDistance TechDraw::DrawViewPart::Focus
Referenced by buildGeometryObject(), and mustExecute().
geometryObject
TechDraw::GeometryObject* TechDraw::DrawViewPart::geometryObject protected
Referenced by add1CEToGE(), add1CLToGE(), add1CVToGV(), addCenterLinesToGeom(), addCosmeticEdgesToGeom(), addCosmeticVertexesToGeom(), addShapes2d(), dumpVerts(), execute(), extractFaces(), getEdgeGeometry(), getFaceGeometry(), getVertexGeometry(), getVisibleFaceEdges(), hasGeometry(), partExec(), and ~DrawViewPart().
HardHidden
App::PropertyBool TechDraw::DrawViewPart::HardHidden
Referenced by buildGeometryObject(), and mustExecute().
IsoCount
App::PropertyInteger TechDraw::DrawViewPart::IsoCount
Referenced by buildGeometryObject(), and mustExecute().
IsoHidden
App::PropertyBool TechDraw::DrawViewPart::IsoHidden
Referenced by buildGeometryObject(), and mustExecute().
IsoVisible
App::PropertyBool TechDraw::DrawViewPart::IsoVisible
Referenced by buildGeometryObject(), and mustExecute().
m_handleFaces
bool TechDraw::DrawViewPart::m_handleFaces protected
m_referenceVerts
std::vector<TechDraw::Vertex*> TechDraw::DrawViewPart::m_referenceVerts protected
Referenced by addReferencesToGeom(), addReferenceVertex(), removeAllReferencesFromGeom(), removeReferenceVertex(), and updateReferenceVert().
m_saveCentroid
Base::Vector3d TechDraw::DrawViewPart::m_saveCentroid protected
Referenced by addShapes2d(), getOriginalCentroid(), and makeGeometryForShape().
m_saveShape
TopoDS_Shape TechDraw::DrawViewPart::m_saveShape protected
Referenced by execute(), and makeGeometryForShape().
Perspective
App::PropertyBool TechDraw::DrawViewPart::Perspective
Referenced by buildGeometryObject(), and mustExecute().
SeamHidden
App::PropertyBool TechDraw::DrawViewPart::SeamHidden
Referenced by buildGeometryObject(), and mustExecute().
SeamVisible
App::PropertyBool TechDraw::DrawViewPart::SeamVisible
Referenced by buildGeometryObject(), extractFaces(), getVisibleFaceEdges(), and mustExecute().
shapeCentroid
Base::Vector3d TechDraw::DrawViewPart::shapeCentroid protected
SmoothHidden
App::PropertyBool TechDraw::DrawViewPart::SmoothHidden
Referenced by buildGeometryObject(), and mustExecute().
SmoothVisible
App::PropertyBool TechDraw::DrawViewPart::SmoothVisible
Referenced by buildGeometryObject(), extractFaces(), getVisibleFaceEdges(), and mustExecute().
Source
App::PropertyLinkList TechDraw::DrawViewPart::Source
Referenced by TechDrawGui::TaskDetail::createDetail(), getAllSources(), TechDraw::DrawProjGroupItem::mustExecute(), and mustExecute().
XDirection
App::PropertyVector TechDraw::DrawViewPart::XDirection
Referenced by checkXDirection(), TechDraw::DrawProjGroupItem::execute(), execute(), getXDirection(), TechDraw::DrawProjGroupItem::getXDirection(), TechDraw::DrawProjGroupItem::mustExecute(), TechDraw::DrawProjGroup::rotateDown(), TechDraw::DrawProjGroup::rotateLeft(), TechDraw::DrawProjGroup::rotateRight(), TechDraw::DrawProjGroup::rotateUp(), TechDraw::DrawProjGroup::spinCCW(), and TechDraw::DrawProjGroup::spinCW().
XSource
App::PropertyXLinkList TechDraw::DrawViewPart::XSource
Referenced by getAllSources(), TechDraw::DrawProjGroupItem::mustExecute(), and mustExecute().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/App/DrawViewPart.h
Sources/FreeCAD/src/Mod/TechDraw/App/DrawViewPart.cpp