FreeCAD: Gui::GLPainter Class Reference
Gui::GLPainter Class Reference
#include <GLPainter.h>
Public Member Functions
bool begin (QPaintDevice *device)
bool end ()
GLPainter ()
bool isActive () const
virtual ~GLPainter ()
Setter methods
void setLineWidth (float)
void setPointSize (float)
void setColor (float, float, float, float=0)
void setLogicOp (GLenum)
void resetLogicOp ()
void setDrawBuffer (GLenum)
void setLineStipple (GLint factor, GLushort pattern)
void resetLineStipple ()
Draw routines
void drawRect (int x, int y, int w, int h)
void drawLine (int x1, int y1, int x2, int y2)
void drawPoint (int x, int y)
Constructor & Destructor Documentation
GLPainter()
GLPainter::GLPainter ()
~GLPainter()
GLPainter::~GLPainter () virtual
References end().
Member Function Documentation
begin()
bool GLPainter::begin (QPaintDevice * device)
Referenced by Gui::Flag::drawLine().
drawLine()
void GLPainter::drawLine (int x1, int y1, int x2, int y2)
drawPoint()
void GLPainter::drawPoint (int x, int y)
drawRect()
void GLPainter::drawRect (int x, int y, int w, int h)
end()
bool GLPainter::end ()
Referenced by ~GLPainter().
isActive()
bool GLPainter::isActive (void) const
resetLineStipple()
void GLPainter::resetLineStipple ()
resetLogicOp()
void GLPainter::resetLogicOp ()
setColor()
void GLPainter::setColor (float r, float g, float b, float a = 0)
setDrawBuffer()
void GLPainter::setDrawBuffer (GLenum mode)
setLineStipple()
void GLPainter::setLineStipple (GLint factor, GLushort pattern)
setLineWidth()
void GLPainter::setLineWidth (float w)
setLogicOp()
void GLPainter::setLogicOp (GLenum mode)
setPointSize()
void GLPainter::setPointSize (float s)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/GLPainter.h
Sources/FreeCAD/src/Gui/GLPainter.cpp