FreeCAD: shipCapacityCurve.PlotAux.Plot Class Reference
shipCapacityCurve.PlotAux.Plot Class Reference
Public Member Functions
def plot (self, l, z, v, tank)
def spreadSheet (self, l, z, v, tank)
Member Function Documentation
plot()
def shipCapacityCurve.PlotAux.Plot.plot (self, l, z, v, tank)
 Perform the areas curve plot.
@param l Percentages of filling level.
@param z Level z coordinates.
@param v Volume of fluid.
@param tank Active tank instance.
@return True if error happens.
References Plot.addNewAxes(), Plot.figure(), Plot.grid(), Plot.plot(), Plot.xlabel(), and Plot.ylabel().
spreadSheet()
def shipCapacityCurve.PlotAux.Plot.spreadSheet (self, l, z, v, tank)
 Write the output data file.
@param l Percentages of filling level.
@param z Level z coordinates.
@param v Volume of fluid.
@param tank Active tank instance.
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Ship/shipCapacityCurve/PlotAux.py