FreeCAD: ILoggerBlockerTest Class Reference
ILoggerBlockerTest Class Reference
Public Member Functions
void flush ()
virtual const char * Name ()
void runSingleTest (const char *comment, std::string expectedResult)
void runTest ()
void SendLog (const std::string &msg, Base::LogStyle level)
Used to send a Log message at the given level.
virtual ~ILoggerBlockerTest ()
Public Member Functions inherited from Base::ILogger
ILogger ()
virtual const char * Name ()
virtual void SendLog (const std::string &msg, LogStyle level)=0
Used to send a Log message at the given level.
virtual ~ILogger ()=0
Additional Inherited Members
Public Attributes inherited from Base::ILogger
bool bErr
bool bLog
bool bMsg
bool bWrn
Constructor & Destructor Documentation
~ILoggerBlockerTest()
virtual ILoggerBlockerTest::~ILoggerBlockerTest () virtual
References Base::Console(), and Base::ConsoleSingleton::DetachObserver().
Member Function Documentation
flush()
void ILoggerBlockerTest::flush ()
Referenced by runSingleTest().
Name()
virtual const char * ILoggerBlockerTest::Name (void) virtual
Reimplemented from Base::ILogger.
runSingleTest()
void ILoggerBlockerTest::runSingleTest (const char * comment, std::string expectedResult)
References Base::Console(), Base::ConsoleSingleton::Error(), flush(), Base::ConsoleSingleton::Log(), Base::ConsoleSingleton::Message(), and Base::ConsoleSingleton::Warning().
Referenced by runTest().
runTest()
void ILoggerBlockerTest::runTest ()
References Base::Console(), Base::ConsoleSingleton::MsgType_Err, Base::ConsoleSingleton::MsgType_Log, Base::ConsoleSingleton::MsgType_Txt, Base::ConsoleSingleton::MsgType_Wrn, runSingleTest(), and Base::ConsoleSingleton::SetEnabledMsgType().
SendLog()
void ILoggerBlockerTest::SendLog (const std::string & msg, Base::LogStyle level) virtual
Used to send a Log message at the given level.
Implements Base::ILogger.
References Base::Error, Base::Log, Base::Message, and Base::Warning.
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Test/Gui/AppTestGui.cpp