FreeCAD: MED::TTNodeInfo< eVersion > Struct Template Reference
MED::TTNodeInfo< eVersion > Struct Template Reference
#include <MED_TStructures.hxx>
Public Types
typedef TTElemInfo< eVersion > TElemInfoBase
Public Member Functions
virtual std::string GetCoordName (TInt theId) const
Get name of the coordinate dimension by its order number.
virtual std::string GetCoordUnit (TInt theId) const
Get name of unit for the coordinate dimension by its order number.
virtual void SetCoordName (TInt theId, const std::string &theValue)
Set name of the coordinate dimension by its order number.
virtual void SetCoordUnit (TInt theId, const std::string &theValue)
Set name of unit for the coordinate dimension by its order number.
TTNodeInfo (const PMeshInfo &theMeshInfo, const PNodeInfo &theInfo)
TTNodeInfo (const PMeshInfo &theMeshInfo, const TFloatVector &theNodeCoords, EModeSwitch theMode, ERepere theSystem, const TStringVector &theCoordNames, const TStringVector &theCoordUnits, const TIntVector &theFamilyNums, const TIntVector &theElemNums, const TStringVector &theElemNames)
TTNodeInfo (const PMeshInfo &theMeshInfo, TInt theNbElem, EModeSwitch theMode, ERepere theSystem, EBooleen theIsElemNum, EBooleen theIsElemNames)
Public Member Functions inherited from MED::TNodeInfo
TCoordSlice GetCoordSlice (TInt theId)
Gives coordinates for mesh node by its number.
TCCoordSlice GetCoordSlice (TInt theId) const
Gives coordinates for mesh node by its number (const version)
ERepere GetSystem () const
Get which coordinate system is used for the node describing.
void SetSystem (ERepere theSystem)
Set coordinate system to be used for the node describing.
Public Member Functions inherited from MED::TElemInfo
TInt GetElemNum (TInt theId) const
Get a reference number of the mesh element by its order number.
TInt GetFamNum (TInt theId) const
Get number of a MED FAMILY by order number of the mesh element.
const PMeshInfo & GetMeshInfo () const
Get a reference to corresponding MED Mesh.
TInt GetNbElem () const
EBooleen IsElemNames () const
Let know if the mesh elements havew names.
EBooleen IsElemNum () const
Let know if the mesh elements are indexed.
EBooleen IsFamNum () const
Let know if the mesh elements family are indexed.
void SetElemNum (TInt theId, TInt theVal)
Set a reference number for the mesh element by its order number.
void SetFamNum (TInt theId, TInt theVal)
Set number of a MED FAMILY for the mesh element with the order number.
Public Member Functions inherited from MED::TBase
virtual ~TBase ()
Public Member Functions inherited from MED::TModeSwitchInfo
EModeSwitch GetModeSwitch () const
TModeSwitchInfo ()
To construct instance of the class by default.
TModeSwitchInfo (EModeSwitch theModeSwitch)
To construct instance of the class.
Public Member Functions inherited from MED::TTElemInfo< eVersion >
virtual std::string GetElemName (TInt theId) const
Get name of the mesh element by its order number.
virtual void SetElemName (TInt theId, const std::string &theValue)
Set name of the mesh element by its order number.
TTElemInfo (const PMeshInfo &theMeshInfo, const PElemInfo &theInfo)
TTElemInfo (const PMeshInfo &theMeshInfo, TInt theNbElem, const TIntVector &theFamilyNums, const TIntVector &theElemNums, const TStringVector &theElemNames)
TTElemInfo (const PMeshInfo &theMeshInfo, TInt theNbElem, EBooleen theIsElemNum, EBooleen theIsElemNames)
Additional Inherited Members
Public Attributes inherited from MED::TNodeInfo
PNodeCoord myCoord
Contains all nodal coordinates.
TString myCoordNames
Contains names for the coordinate dimensions.
TString myCoordUnits
Contains units for the coordinate dimensions.
ERepere mySystem
Defines, which coordinate system is used.
Public Attributes inherited from MED::TElemInfo
PString myElemNames
Contains sequence of the names for the mesh elements.
PElemNum myElemNum
Contains sequence of the indexes for the mesh elements.
PElemNum myFamNum
Get number of mesh elements.
EBooleen myIsElemNames
Defines if the mesh elements are named.
EBooleen myIsElemNum
Defines if the mesh elements are indexed.
EBooleen myIsFamNum
Defines if the mesh elements family are indexed.
PMeshInfo myMeshInfo
A reference to correspondig MED Mesh.
TInt myNbElem
Public Attributes inherited from MED::TModeSwitchInfo
EModeSwitch myModeSwitch
Keeps the.
Member Typedef Documentation
TElemInfoBase
template<EVersion eVersion> typedef TTElemInfo<eVersion> MED::TTNodeInfo< eVersion >::TElemInfoBase
Constructor & Destructor Documentation
TTNodeInfo() [1/3]
template<EVersion eVersion> MED::TTNodeInfo< eVersion >::TTNodeInfo (const PMeshInfo & theMeshInfo, const PNodeInfo & theInfo)
References MED::TNodeInfo::myCoord, MED::TNodeInfo::myCoordNames, MED::TNodeInfo::myCoordUnits, MED::TModeSwitchInfo::myModeSwitch, MED::TNodeInfo::mySystem, MED::TTNodeInfo< eVersion >::SetCoordName(), and MED::TTNodeInfo< eVersion >::SetCoordUnit().
TTNodeInfo() [2/3]
template<EVersion eVersion> MED::TTNodeInfo< eVersion >::TTNodeInfo (const PMeshInfo & theMeshInfo, TInt theNbElem, EModeSwitch theMode, ERepere theSystem, EBooleen theIsElemNum, EBooleen theIsElemNames)
References MED::TNodeInfo::myCoord, MED::TNodeInfo::myCoordNames, MED::TNodeInfo::myCoordUnits, and MED::TNodeInfo::mySystem.
TTNodeInfo() [3/3]
template<EVersion eVersion> MED::TTNodeInfo< eVersion >::TTNodeInfo (const PMeshInfo & theMeshInfo, const TFloatVector & theNodeCoords, EModeSwitch theMode, ERepere theSystem, const TStringVector & theCoordNames, const TStringVector & theCoordUnits, const TIntVector & theFamilyNums, const TIntVector & theElemNums, const TStringVector & theElemNames)
References MED::TNodeInfo::myCoord, MED::TNodeInfo::myCoordNames, MED::TNodeInfo::myCoordUnits, MED::TNodeInfo::mySystem, MED::TTNodeInfo< eVersion >::SetCoordName(), and MED::TTNodeInfo< eVersion >::SetCoordUnit().
Member Function Documentation
GetCoordName()
template<EVersion eVersion> virtual std::string MED::TTNodeInfo< eVersion >::GetCoordName (TInt theId) const virtual
Get name of the coordinate dimension by its order number.
Implements MED::TNodeInfo.
References MED::GetString(), and MED::TNodeInfo::myCoordNames.
GetCoordUnit()
template<EVersion eVersion> virtual std::string MED::TTNodeInfo< eVersion >::GetCoordUnit (TInt theId) const virtual
Get name of unit for the coordinate dimension by its order number.
Implements MED::TNodeInfo.
References MED::GetString(), and MED::TNodeInfo::myCoordUnits.
SetCoordName()
template<EVersion eVersion> virtual void MED::TTNodeInfo< eVersion >::SetCoordName (TInt theId, const std::string & theValue) virtual
Set name of the coordinate dimension by its order number.
Implements MED::TNodeInfo.
References MED::TNodeInfo::myCoordNames, and MED::SetString().
Referenced by MED::TTNodeInfo< eVersion >::TTNodeInfo().
SetCoordUnit()
template<EVersion eVersion> virtual void MED::TTNodeInfo< eVersion >::SetCoordUnit (TInt theId, const std::string & theValue) virtual
Set name of unit for the coordinate dimension by its order number.
Implements MED::TNodeInfo.
References MED::TNodeInfo::myCoordUnits, and MED::SetString().
Referenced by MED::TTNodeInfo< eVersion >::TTNodeInfo().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/MED_TStructures.hxx