FreeCAD: MeshGui::ParametersDialog Class Reference
MeshGui::ParametersDialog Class Reference
#include <SegmentationBestFit.h>
Public Member Functions
void accept ()
ParametersDialog (std::vector< float > &, FitParameter *, ParameterList, Mesh::Feature *mesh, QWidget *parent=nullptr)
void reject ()
~ParametersDialog ()
Constructor & Destructor Documentation
ParametersDialog()
ParametersDialog::ParametersDialog (std::vector< float > & val, FitParameter * fitPar, ParameterList par, Mesh::Feature * mesh, QWidget * parent = nullptr)
References accept(), Gui::SelectionSingleton::clearSelection(), draftgeoutils.intersections::connect(), reject(), Gui::Selection(), MeshGui::MeshSelection::setCheckOnlyPointToUserTriangles(), MeshGui::MeshSelection::setCheckOnlyVisibleTriangles(), MeshGui::MeshSelection::setEnabledViewerSelection(), and MeshGui::MeshSelection::setObjects().
~ParametersDialog()
ParametersDialog::~ParametersDialog ()
References MeshGui::MeshSelection::clearSelection(), and MeshGui::MeshSelection::setEnabledViewerSelection().
Member Function Documentation
accept()
void ParametersDialog::accept (void)
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), ParametersDialog(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
reject()
void ParametersDialog::reject (void)
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), ParametersDialog(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/Gui/SegmentationBestFit.h
FreeCAD/src/Mod/Mesh/Gui/SegmentationBestFit.cpp