FreeCAD: Part::GeometryIntExtensionPy Class Reference
Part::GeometryIntExtensionPy Class Reference
The python export class for GeometryIntExtension.
#include <GeometryIntExtensionPy.h>
Public Types
typedef GeometryIntExtension * PointerType
Public Types inherited from Part::GeometryExtensionPy
typedef GeometryExtension * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
GeometryIntExtensionPy (GeometryIntExtension *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Part::GeometryExtensionPy
GeometryExtensionPy (GeometryExtension *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * copy (PyObject *args)
implementer for the copy() method
Py::String getName (void) const
getter for the Name attribute
void setName (Py::String arg)
setter for the Name attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeometryExtension * getGeometryExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::GeometryExtensionPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_getName (PyObject *self, void *closure)
getter callback for the Name attribute
static int staticCallback_setName (PyObject *self, PyObject *value, void *closure)
setter callback for the Name attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of GeometryIntExtensionPy.
static PyMethodDef Methods []
Methods structure of GeometryIntExtensionPy.
static PyTypeObject Type
Type structure of GeometryIntExtensionPy.
Static Public Attributes inherited from Part::GeometryExtensionPy
static PyGetSetDef GetterSetter []
Attribute structure of GeometryExtensionPy.
static PyMethodDef Methods []
Methods structure of GeometryExtensionPy.
static PyTypeObject Type
Type structure of GeometryExtensionPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~GeometryIntExtensionPy ()
Protected Member Functions inherited from Part::GeometryExtensionPy
~GeometryExtensionPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object attributes
Py::Long getValue (void) const
getter for the Value attribute
void setValue (Py::Long arg)
setter for the Value attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeometryIntExtension * getGeometryIntExtensionPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getValue (PyObject *self, void *closure)
getter callback for the Value attribute
static int staticCallback_setValue (PyObject *self, PyObject *value, void *closure)
setter callback for the Value attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeometryIntExtension.
Member Typedef Documentation
PointerType
typedef GeometryIntExtension* Part::GeometryIntExtensionPy::PointerType
Constructor & Destructor Documentation
~GeometryIntExtensionPy()
GeometryIntExtensionPy::~GeometryIntExtensionPy () protected
GeometryIntExtensionPy()
GeometryIntExtensionPy::GeometryIntExtensionPy (GeometryIntExtension * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getCustomAttributes()
PyObject * GeometryIntExtensionPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getGeometryIntExtensionPtr()
GeometryIntExtension * GeometryIntExtensionPy::getGeometryIntExtensionPtr (void) const
getter for the object handled by this class
Referenced by getValue(), PyInit(), representation(), and setValue().
GetType()
virtual PyTypeObject* Part::GeometryIntExtensionPy::GetType (void) virtual
Reimplemented from Part::GeometryExtensionPy.
getValue()
Py::Long GeometryIntExtensionPy::getValue (void) const
getter for the Value attribute
References getGeometryIntExtensionPtr().
Referenced by staticCallback_getValue().
PyInit()
int GeometryIntExtensionPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::GeometryExtensionPy.
References getGeometryIntExtensionPtr(), Part::GeometryExtension::setName(), and Part::GeometryDefaultExtension< T >::setValue().
PyMake()
PyObject * GeometryIntExtensionPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References GeometryIntExtensionPy().
representation()
std::string GeometryIntExtensionPy::representation (void) const
References getGeometryIntExtensionPtr(), Part::GeometryExtension::getName(), Part::GeometryExtensionPy::getName(), and Part::GeometryDefaultExtension< T >::getValue().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int GeometryIntExtensionPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setValue()
void GeometryIntExtensionPy::setValue (Py::Long arg)
setter for the Value attribute
References getGeometryIntExtensionPtr(), and Part::GeometryDefaultExtension< T >::setValue().
Referenced by staticCallback_setValue().
staticCallback_getValue()
PyObject * GeometryIntExtensionPy::staticCallback_getValue (PyObject * self, void * closure) static
getter callback for the Value attribute
References Base::BaseExceptionFreeCADError, getValue(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setValue()
int GeometryIntExtensionPy::staticCallback_setValue (PyObject * self, PyObject * value, void * closure) static
setter callback for the Value attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setValue().
Member Data Documentation
GetterSetter
PyGetSetDef GeometryIntExtensionPy::GetterSetter static
Initial value:
= {
    {"Value",
        (getter) staticCallback_getValue,
        (setter) staticCallback_setValue,
        "\n                returns the value of the GeometryIntExtension.\n            ",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of GeometryIntExtensionPy.
Methods
PyMethodDef GeometryIntExtensionPy::Methods static
Initial value:
= {
    {NULL, NULL, 0, NULL}
}
Methods structure of GeometryIntExtensionPy.
Type
PyTypeObject GeometryIntExtensionPy::Type static
Type structure of GeometryIntExtensionPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeometryIntExtensionPy.h
Sources/FreeCAD/src/Mod/Part/App/GeometryIntExtensionPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeometryIntExtensionPy.cpp