FreeCAD: Gui::NS::GestureState Class Reference
Gui::NS::GestureState Class Reference
Public Types
typedef sc::custom_reaction< NS::Event > reactions
Public Member Functions
GestureState (my_context ctx)
sc::result react (const NS::Event &ev)
virtual ~GestureState ()
Member Typedef Documentation
reactions
typedef sc::custom_reaction<NS::Event> Gui::NS::GestureState::reactions
Constructor & Destructor Documentation
GestureState()
Gui::NS::GestureState::GestureState (my_context ctx)
References Base::Console(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), Base::ConsoleSingleton::Log(), and Gui::NavigationStyle::PANNING.
~GestureState()
virtual Gui::NS::GestureState::~GestureState () virtual
Member Function Documentation
react()
sc::result Gui::NS::GestureState::react (const NS::Event & ev)
References Gui::NS::Event::asGestureEvent(), Base::Console(), SoGesturePinchEvent::curCenter, SoGesturePinchEvent::deltaAngle, SoGesturePinchEvent::deltaCenter, SoGesturePinchEvent::deltaZoom, Gui::NS::Event::flags, Gui::NS::Event::inventor_event, Gui::NS::Event::isGestureEvent(), Gui::NS::Event::isLocation2Event(), Gui::NS::Event::isMouseButtonEvent(), Gui::NS::Event::mbstate(), SoGestureEvent::SbGsCanceled, SoGestureEvent::SbGSEnd, SoGestureEvent::state, and Base::ConsoleSingleton::Warning().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/GestureNavigationStyle.cpp