FreeCAD: PathTests.TestPathDrillGenerator.TestPathDrillGenerator Class Reference
PathTests.TestPathDrillGenerator.TestPathDrillGenerator Class Reference
Public Member Functions
def test00 (self)
def test10 (self)
def test20 (self)
def test30 (self)
def test40 (self)
def test41 (self)
def test42 (self)
Public Member Functions inherited from PathTests.PathTestUtils.PathTestBase
def assertArc (self, edge, pt1, pt2, direction="CW")
def assertCircle (self, edge, pt, r)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertCommandEqual (self, c1, c2)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertEdgeShapesMatch (self, e1, e2)
def assertEqualLocale (self, s1, s2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertPlacement (self, p1, p2)
def assertPointsMatch (self, pts0, pts1)
def assertRoughly (self, f1, f2, error=0.00001)
Member Function Documentation
test00()
def PathTests.TestPathDrillGenerator.TestPathDrillGenerator.test00 (self)
Test Basic Drill Generator Return
Referenced by PathTests.TestPathTool.TestPathTool.test01(), PathTests.TestPathToolController.TestPathToolController.test01(), PathTests.TestPathTooltable.TestPathTooltable.test01(), PathTests.TestPathTool.TestPathTool.test02(), and PathTests.TestPathTooltable.TestPathTooltable.test02().
test10()
def PathTests.TestPathDrillGenerator.TestPathDrillGenerator.test10 (self)
Test edge alignment check
test20()
def PathTests.TestPathDrillGenerator.TestPathDrillGenerator.test20 (self)
Test Basic Peck Drill Generator Return
test30()
def PathTests.TestPathDrillGenerator.TestPathDrillGenerator.test30 (self)
Test Basic Dwell Drill Generator Return
test40()
def PathTests.TestPathDrillGenerator.TestPathDrillGenerator.test40 (self)
Specifying retract height should set R parameter to specified value
test41()
def PathTests.TestPathDrillGenerator.TestPathDrillGenerator.test41 (self)
Not specifying retract height should set R parameter to Z position of start point
test42()
def PathTests.TestPathDrillGenerator.TestPathDrillGenerator.test42 (self)
Non-float retract height should raise ValueError
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Path/PathTests/TestPathDrillGenerator.py