FreeCAD: Image::ImageBase Class Reference
Image::ImageBase Class Reference
#include <ImageBase.h>
Public Member Functions
virtual void clear ()
virtual int createCopy (void *pSrcPixelData, unsigned long width, unsigned long height, int format, unsigned short numSigBitsPerSample)
int getFormat () const
unsigned long getHeight () const
unsigned short getNumBitsPerSample () const
unsigned short getNumBytesPerPixel () const
unsigned short getNumSamples () const
unsigned short getNumSigBitsPerSample () const
void * getPixelDataPtr ()
virtual int getSample (int x, int y, unsigned short sampleIndex, double &value)
unsigned long getWidth () const
bool hasValidData () const
ImageBase ()
ImageBase (const ImageBase &rhs)
bool isOwner () const
ImageBase & operator= (const ImageBase &rhs)
virtual int pointTo (void *pSrcPixelData, unsigned long width, unsigned long height, int format, unsigned short numSigBitsPerSample, bool takeOwnership)
virtual ~ImageBase ()
Constructor & Destructor Documentation
ImageBase() [1/2]
ImageBase::ImageBase ()
~ImageBase()
ImageBase::~ImageBase () virtual
References clear().
ImageBase() [2/2]
ImageBase::ImageBase (const ImageBase & rhs)
References createCopy().
Member Function Documentation
clear()
void ImageBase::clear (void) virtual
Referenced by createCopy(), operator=(), pointTo(), and ~ImageBase().
createCopy()
int ImageBase::createCopy (void * pSrcPixelData, unsigned long width, unsigned long height, int format, unsigned short numSigBitsPerSample) virtual
References clear().
Referenced by ImageBase(), and operator=().
getFormat()
int Image::ImageBase::getFormat (void) const
getHeight()
unsigned long Image::ImageBase::getHeight () const
getNumBitsPerSample()
unsigned short Image::ImageBase::getNumBitsPerSample () const
getNumBytesPerPixel()
unsigned short Image::ImageBase::getNumBytesPerPixel () const
getNumSamples()
unsigned short Image::ImageBase::getNumSamples () const
getNumSigBitsPerSample()
unsigned short Image::ImageBase::getNumSigBitsPerSample () const
getPixelDataPtr()
void* Image::ImageBase::getPixelDataPtr ()
getSample()
int ImageBase::getSample (int x, int y, unsigned short sampleIndex, double & value) virtual
getWidth()
unsigned long Image::ImageBase::getWidth () const
hasValidData()
bool Image::ImageBase::hasValidData () const
isOwner()
bool Image::ImageBase::isOwner () const
operator=()
ImageBase & ImageBase::operator= (const ImageBase & rhs)
References clear(), and createCopy().
pointTo()
int ImageBase::pointTo (void * pSrcPixelData, unsigned long width, unsigned long height, int format, unsigned short numSigBitsPerSample, bool takeOwnership) virtual
References clear().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Image/App/ImageBase.h
Sources/FreeCAD/src/Mod/Image/App/ImageBase.cpp