FreeCAD: Gui::GestureNavigationStyle::EventQueue Class Reference
Gui::GestureNavigationStyle::EventQueue Class Reference
#include <GestureNavigationStyle.h>
Public Member Functions
void discardAll ()
EventQueue (GestureNavigationStyle &ns)
void forwardAll ()
void post (const Event &ev)
Public Attributes
GestureNavigationStyle & ns
Constructor & Destructor Documentation
EventQueue()
Gui::GestureNavigationStyle::EventQueue::EventQueue (GestureNavigationStyle & ns)
Member Function Documentation
discardAll()
void Gui::GestureNavigationStyle::EventQueue::discardAll ()
forwardAll()
void Gui::GestureNavigationStyle::EventQueue::forwardAll ()
post()
void Gui::GestureNavigationStyle::EventQueue::post (const Event & ev)
References Gui::NS::Event::asMouseButtonEvent(), Base::Console(), Gui::NS::Event::flags, Gui::NS::Event::log(), Base::ConsoleSingleton::Log(), Gui::GestureNavigationStyle::logging, and ns.
Member Data Documentation
ns
GestureNavigationStyle& Gui::GestureNavigationStyle::EventQueue::ns
Referenced by post().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/GestureNavigationStyle.h
Sources/FreeCAD/src/Gui/GestureNavigationStyle.cpp