FreeCAD: TechDraw Namespace Reference
TechDraw Namespace Reference
HatchLine - Classes related to processing PAT files.
Classes
struct anglePoints
class AOC
class AOE
struct arcPoints
class ArrowPropEnum
class BaseGeom
class BezierSegment
class BSpline
class CenterLine
class Circle
class CosmeticEdge
class CosmeticExtension
class CosmeticVertex
class DashSpec
struct DimRef
class DrawDimHelper
Additional functions for working with Dimensions.
class DrawGeomHatch
class DrawHatch
class DrawLeaderLine
class DrawPage
class DrawParametricTemplate
class DrawProjectSplit
class DrawProjGroup
Class super-container for managing a collection of DrawProjGroupItem Page Features.
class DrawProjGroupItem
class DrawRichAnno
class DrawSVGTemplate
class DrawTemplate
class DrawTile
class DrawTileWeld
class DrawUtil
Convenient utility functions for TechDraw Module.
class DrawView
Base class of all View Features in the drawing module.
class DrawViewAnnotation
class DrawViewArch
class DrawViewBalloon
class DrawViewClip
class DrawViewCollection
Base class for collection of view objects.
class DrawViewDetail
class DrawViewDimension
class DrawViewDimExtent
class DrawViewDraft
class DrawViewImage
class DrawViewMulti
Base class of all View Features in the drawing module.
class DrawViewPart
class DrawViewSection
class DrawViewSpreadsheet
class DrawViewSymbol
class DrawWeldSymbol
class DXFOutput
class edgeSortItem
class edgeVisitor
class EdgeWalker
class Ellipse
class embedItem
class ewWire
class ewWireList
class Face
Simple Collection of geometric features based on BaseGeom inherited classes in order.
class FeatureProjection
Base class of all View Features in the drawing module.
class Generic
class GeometryObject
class GeometryUtils
Encapsulates some useful static methods.
class GeomFormat
class hTrimCurve
class incidenceItem
class LandmarkDimension
class LineFormat
class LineGroup
class LineSet
a LineSet is all the generated edges for 1 PATLineSpec for 1 Face
class Module
class PATLineSpec
PATLineSpec is the result of parsing a singleline from PAT file into accessible parameters.
class Preferences
class ProjectionAlgos
Algo class for projecting shapes and creating SVG output of it.
class PropertyCenterLineList
class PropertyCosmeticEdgeList
class PropertyCosmeticVertexList
class PropertyGeomFormatList
class ShapeExtractor
struct splitPoint
class SVGOutput
class TechDrawOutput
class Vertex
class WalkerEdge
class Wire
Simple Collection of geometric features based on BaseGeom inherited classes in order.
Typedefs
using AOCPtr = std::shared_ptr< AOC >
using AOEPtr = std::shared_ptr< AOE >
using BaseGeomPtr = std::shared_ptr< BaseGeom >
using BaseGeomPtrVector = std::vector< BaseGeomPtr >
using BezierSegmentPtr = std::shared_ptr< BezierSegment >
using BSplinePtr = std::shared_ptr< BSpline >
using CirclePtr = std::shared_ptr< Circle >
typedef App::ExtensionPythonT< CosmeticExtension > CosmeticExtensionPython
typedef App::FeaturePythonT< DrawGeomHatch > DrawGeomHatchPython
typedef App::FeaturePythonT< DrawHatch > DrawHatchPython
typedef App::FeaturePythonT< DrawLeaderLine > DrawLeaderLinePython
typedef App::FeaturePythonT< DrawPage > DrawPagePython
typedef App::FeaturePythonT< DrawParametricTemplate > DrawParametricTemplatePython
typedef App::FeaturePythonT< DrawProjectSplit > DrawProjectSplitPython
typedef App::FeaturePythonT< DrawRichAnno > DrawRichAnnoPython
typedef App::FeaturePythonT< DrawSVGTemplate > DrawSVGTemplatePython
typedef App::FeaturePythonT< DrawTemplate > DrawTemplatePython
typedef App::FeaturePythonT< DrawTile > DrawTilePython
typedef App::FeaturePythonT< DrawTileWeld > DrawTileWeldPython
typedef App::FeaturePythonT< DrawViewAnnotation > DrawViewAnnotationPython
typedef App::FeaturePythonT< DrawViewClip > DrawViewClipPython
typedef App::FeaturePythonT< DrawViewDetail > DrawViewDetailPython
typedef App::FeaturePythonT< DrawViewDraft > DrawViewDraftPython
typedef App::FeaturePythonT< DrawViewImage > DrawViewImagePython
typedef App::FeaturePythonT< DrawViewMulti > DrawViewMultiPython
typedef App::FeaturePythonT< DrawViewPart > DrawViewPartPython
typedef App::FeaturePythonT< DrawView > DrawViewPython
typedef App::FeaturePythonT< DrawViewSection > DrawViewSectionPython
typedef App::FeaturePythonT< DrawViewSpreadsheet > DrawViewSpreadsheetPython
typedef App::FeaturePythonT< DrawViewSymbol > DrawViewSymbolPython
typedef App::FeaturePythonT< DrawWeldSymbol > DrawWeldSymbolPython
typedef boost::graph_traits< graph >::edge_descriptor edge_t
using EllipsePtr = std::shared_ptr< Ellipse >
using FacePtr = std::shared_ptr< Face >
using GenericPtr = std::shared_ptr< Generic >
typedef boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS, boost::property< boost::vertex_index_t, int >, boost::property< boost::edge_index_t, int > > graph
typedef std::vector< std::vector< edge_t > > planar_embedding_storage_t
typedef boost::iterator_property_map< planar_embedding_storage_t::iterator, boost::property_map< graph, boost::vertex_index_t >::type > planar_embedding_t
typedef std::pair< Base::Vector3d, Base::Vector3d > pointPair
typedef boost::graph_traits< graph >::vertex_descriptor vertex_t
using VertexPtr = std::shared_ptr< Vertex >
Enumerations
enum ArrowType {
FILLED_ARROW = 0 , OPEN_ARROW , TICK , DOT ,
OPEN_CIRCLE , FORK , FILLED_TRIANGLE , NONE
}
enum edgeClass {
ecNONE , ecUVISO , ecOUTLINE , ecSMOOTH ,
ecSEAM , ecHARD
}
enum ExtractionType { Plain , WithHidden , WithSmooth }
enum GeomType {
NOTDEF , CIRCLE , ARCOFCIRCLE , ELLIPSE ,
ARCOFELLIPSE , BEZIER , BSPLINE , GENERIC
}
enum ProjItemType {
Front , Left , Right , Rear ,
Top , Bottom , FrontTopLeft , FrontTopRight ,
FrontBottomLeft , FrontBottomRight
}
enum SourceType { GEOM , COSEDGE , CENTERLINE }
Functions
template<typename OutputIt >
void copy (Py::Dict sourceRange, OutputIt targetIt)
Copies a Python dictionary of Python strings to a C++ container.
gp_Pnt TechDrawExport findCentroid (const TopoDS_Shape &shape, const Base::Vector3d &direction)
Returns the centroid of shape, as viewed according to direction.
gp_Pnt TechDrawExport findCentroid (const TopoDS_Shape &shape, const gp_Ax2 &viewAxis)
Returns the centroid of shape, as viewed according to direction.
Base::Vector3d TechDrawExport findCentroidVec (const TopoDS_Shape &shape, const Base::Vector3d &direction)
Base::Vector3d TechDrawExport findCentroidVec (const TopoDS_Shape &shape, const gp_Ax2 &cs)
gp_Ax2 TechDrawExport getViewAxis (const Base::Vector3d origin, const Base::Vector3d &direction, const Base::Vector3d &xAxis, const bool flip=true)
gets a coordinate system specified by Z and X directions
gp_Ax2 TechDrawExport getViewAxis (const Base::Vector3d origin, const Base::Vector3d &direction, const bool flip=true)
utility non-class member functions gets a coordinate system that matches view system used in 3D with +Z up (or +Y up if necessary) used for individual views, but not secondary views in projection groups flip determines Y mirror or not.
PyObject * initModule ()
gp_Ax2 TechDrawExport legacyViewAxis1 (const Base::Vector3d origin, const Base::Vector3d &direction, const bool flip=true)
TopoDS_Shape TechDrawExport mirrorShape (const TopoDS_Shape &input, const gp_Pnt &inputCenter=gp_Pnt(0.0, 0.0, 0.0), double scale=1.0)
TopoDS_Shape TechDrawExport mirrorShapeVec (const TopoDS_Shape &input, const Base::Vector3d &inputCenter=Base::Vector3d(0.0, 0.0, 0.0), double scale=1.0)
scales & mirrors a shape about a center
TopoDS_Shape TechDrawExport moveShape (const TopoDS_Shape &input, const Base::Vector3d &motion)
moves a shape
TopoDS_Shape TechDrawExport rotateShape (const TopoDS_Shape &input, gp_Ax2 &viewAxis, double rotAngle)
rotates a shape about a viewAxis
TopoDS_Shape TechDrawExport scaleShape (const TopoDS_Shape &input, double scale)
scales a shape about origin
Detailed Description
HatchLine - Classes related to processing PAT files.
LineGroup - Classes related to processing LineGroup definition CSV files.
Typedef Documentation
AOCPtr
using TechDraw::AOCPtr = typedef std::shared_ptr<AOC>
AOEPtr
using TechDraw::AOEPtr = typedef std::shared_ptr<AOE>
BaseGeomPtr
using TechDraw::BaseGeomPtr = typedef std::shared_ptr<BaseGeom>
BaseGeomPtrVector
using TechDraw::BaseGeomPtrVector = typedef std::vector<BaseGeomPtr>
BezierSegmentPtr
using TechDraw::BezierSegmentPtr = typedef std::shared_ptr<BezierSegment>
BSplinePtr
using TechDraw::BSplinePtr = typedef std::shared_ptr<BSpline>
CirclePtr
using TechDraw::CirclePtr = typedef std::shared_ptr<Circle>
CosmeticExtensionPython
typedef App::ExtensionPythonT<CosmeticExtension> TechDraw::CosmeticExtensionPython
DrawGeomHatchPython
typedef App::FeaturePythonT<DrawGeomHatch> TechDraw::DrawGeomHatchPython
DrawHatchPython
typedef App::FeaturePythonT<DrawHatch> TechDraw::DrawHatchPython
DrawLeaderLinePython
typedef App::FeaturePythonT<DrawLeaderLine> TechDraw::DrawLeaderLinePython
DrawPagePython
typedef App::FeaturePythonT<DrawPage> TechDraw::DrawPagePython
DrawParametricTemplatePython
typedef App::FeaturePythonT<DrawParametricTemplate> TechDraw::DrawParametricTemplatePython
DrawProjectSplitPython
typedef App::FeaturePythonT<DrawProjectSplit> TechDraw::DrawProjectSplitPython
DrawRichAnnoPython
typedef App::FeaturePythonT<DrawRichAnno> TechDraw::DrawRichAnnoPython
DrawSVGTemplatePython
typedef App::FeaturePythonT<DrawSVGTemplate> TechDraw::DrawSVGTemplatePython
DrawTemplatePython
typedef App::FeaturePythonT<DrawTemplate> TechDraw::DrawTemplatePython
DrawTilePython
typedef App::FeaturePythonT<DrawTile> TechDraw::DrawTilePython
DrawTileWeldPython
typedef App::FeaturePythonT<DrawTileWeld> TechDraw::DrawTileWeldPython
DrawViewAnnotationPython
typedef App::FeaturePythonT<DrawViewAnnotation> TechDraw::DrawViewAnnotationPython
DrawViewClipPython
typedef App::FeaturePythonT<DrawViewClip> TechDraw::DrawViewClipPython
DrawViewDetailPython
typedef App::FeaturePythonT<DrawViewDetail> TechDraw::DrawViewDetailPython
DrawViewDraftPython
typedef App::FeaturePythonT<DrawViewDraft> TechDraw::DrawViewDraftPython
DrawViewImagePython
typedef App::FeaturePythonT<DrawViewImage> TechDraw::DrawViewImagePython
DrawViewMultiPython
typedef App::FeaturePythonT<DrawViewMulti> TechDraw::DrawViewMultiPython
DrawViewPartPython
typedef App::FeaturePythonT<DrawViewPart> TechDraw::DrawViewPartPython
DrawViewPython
typedef App::FeaturePythonT<DrawView> TechDraw::DrawViewPython
DrawViewSectionPython
typedef App::FeaturePythonT<DrawViewSection> TechDraw::DrawViewSectionPython
DrawViewSpreadsheetPython
typedef App::FeaturePythonT<DrawViewSpreadsheet> TechDraw::DrawViewSpreadsheetPython
DrawViewSymbolPython
typedef App::FeaturePythonT<DrawViewSymbol> TechDraw::DrawViewSymbolPython
DrawWeldSymbolPython
typedef App::FeaturePythonT<DrawWeldSymbol> TechDraw::DrawWeldSymbolPython
edge_t
typedef boost::graph_traits<graph>::edge_descriptor TechDraw::edge_t
EllipsePtr
using TechDraw::EllipsePtr = typedef std::shared_ptr<Ellipse>
FacePtr
using TechDraw::FacePtr = typedef std::shared_ptr<Face>
GenericPtr
using TechDraw::GenericPtr = typedef std::shared_ptr<Generic>
graph
typedef boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS, boost::property<boost::vertex_index_t, int>, boost::property<boost::edge_index_t, int> > TechDraw::graph
planar_embedding_storage_t
typedef std::vector< std::vector<edge_t> > TechDraw::planar_embedding_storage_t
planar_embedding_t
typedef boost::iterator_property_map< planar_embedding_storage_t::iterator, boost::property_map<graph, boost::vertex_index_t>::type > TechDraw::planar_embedding_t
pointPair
typedef std::pair<Base::Vector3d,Base::Vector3d> TechDraw::pointPair
vertex_t
typedef boost::graph_traits<graph>::vertex_descriptor TechDraw::vertex_t
VertexPtr
using TechDraw::VertexPtr = typedef std::shared_ptr<Vertex>
Enumeration Type Documentation
ArrowType
enum TechDraw::ArrowType
Enumerator
FILLED_ARROW
OPEN_ARROW
TICK
DOT
OPEN_CIRCLE
FORK
FILLED_TRIANGLE
NONE
edgeClass
enum TechDraw::edgeClass
Enumerator
ecNONE
ecUVISO
ecOUTLINE
ecSMOOTH
ecSEAM
ecHARD
ExtractionType
enum TechDraw::ExtractionType
Enumerator
Plain
WithHidden
WithSmooth
GeomType
enum TechDraw::GeomType
Enumerator
NOTDEF
CIRCLE
ARCOFCIRCLE
ELLIPSE
ARCOFELLIPSE
BEZIER
BSPLINE
GENERIC
ProjItemType
enum TechDraw::ProjItemType
Enumerator
Front
Left
Right
Rear
Top
Bottom
FrontTopLeft
FrontTopRight
FrontBottomLeft
FrontBottomRight
SourceType
enum TechDraw::SourceType
Enumerator
GEOM
COSEDGE
CENTERLINE
Function Documentation
copy()
template<typename OutputIt > void TechDraw::copy (Py::Dict sourceRange, OutputIt targetIt)
Copies a Python dictionary of Python strings to a C++ container.
After the function call, the key-value pairs of the Python dictionary are copied into the target buffer as C++ pairs (pair<string, string>).
Parameters
sourceRange is a Python dictionary (Py::Dict). Both, the keys and the values must be Python strings.
targetIt refers to where the data should be inserted. Must be of concept output iterator.
findCentroid() [1/2]
gp_Pnt TechDraw::findCentroid (const TopoDS_Shape & shape, const Base::Vector3d & direction)
Returns the centroid of shape, as viewed according to direction.
References findCentroid(), and getViewAxis().
Referenced by TechDraw::DrawViewDetail::detailExec(), TechDraw::DrawViewMulti::execute(), findCentroid(), findCentroidVec(), TechDraw::DrawViewPart::makeGeometryForShape(), TechDraw::GeometryObject::projectShapeWithPolygonAlgo(), and TechDraw::DrawViewSection::sectionExec().
findCentroid() [2/2]
gp_Pnt TechDraw::findCentroid (const TopoDS_Shape & shape, const gp_Ax2 & viewAxis)
Returns the centroid of shape, as viewed according to direction.
findCentroidVec() [1/2]
Base::Vector3d TechDraw::findCentroidVec (const TopoDS_Shape & shape, const Base::Vector3d & direction)
References findCentroid().
Referenced by TechDraw::DrawViewPart::getCurrentCentroid().
findCentroidVec() [2/2]
Base::Vector3d TechDraw::findCentroidVec (const TopoDS_Shape & shape, const gp_Ax2 & cs)
References findCentroid().
getViewAxis() [1/2]
gp_Ax2 TechDraw::getViewAxis (const Base::Vector3d origin, const Base::Vector3d & direction, const Base::Vector3d & xAxis, const bool flip = true)
gets a coordinate system specified by Z and X directions
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
getViewAxis() [2/2]
gp_Ax2 TechDraw::getViewAxis (const Base::Vector3d origin, const Base::Vector3d & direction, const bool flip = true)
utility non-class member functions gets a coordinate system that matches view system used in 3D with +Z up (or +Y up if necessary) used for individual views, but not secondary views in projection groups flip determines Y mirror or not.
References TechDraw::DrawUtil::checkParallel(), Base::Vector3< _Precision >::Cross(), Base::Vector3< _Precision >::IsEqual(), Base::Vector3< _Precision >::Normalize(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by findCentroid(), and TechDraw::DrawProjGroupItem::getViewAxis().
initModule()
PyObject * TechDraw::initModule ()
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().
legacyViewAxis1()
gp_Ax2 TechDraw::legacyViewAxis1 (const Base::Vector3d origin, const Base::Vector3d & direction, const bool flip = true)
References TechDraw::DrawUtil::checkParallel(), Base::Vector3< _Precision >::Cross(), Base::Vector3< _Precision >::IsEqual(), Base::Vector3< _Precision >::Normalize(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by TechDraw::DrawProjectSplit::getEdgesForWalker(), and TechDraw::DrawViewPart::getLegacyX().
mirrorShape()
TopoDS_Shape TechDraw::mirrorShape (const TopoDS_Shape & input, const gp_Pnt & inputCenter = gp_Pnt(0.0,0.0,0.0), double scale = 1.0)
References Base::Console(), and Base::ConsoleSingleton::Log().
Referenced by TechDraw::DrawViewMulti::execute(), and mirrorShapeVec().
mirrorShapeVec()
TopoDS_Shape TechDraw::mirrorShapeVec (const TopoDS_Shape & input, const Base::Vector3d & inputCenter = Base::Vector3d(0.0, 0.0, 0.0), double scale = 1.0)
scales & mirrors a shape about a center
References mirrorShape(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
moveShape()
TopoDS_Shape TechDraw::moveShape (const TopoDS_Shape & input, const Base::Vector3d & motion)
moves a shape
References Base::Console(), Base::ConsoleSingleton::Log(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by TechDraw::DrawViewDetail::detailExec(), TechDraw::DrawGeomHatch::getTrimmedLinesSection(), TechDraw::DrawViewPart::makeGeometryForShape(), TechDraw::GeometryObject::projectShapeWithPolygonAlgo(), and TechDraw::DrawViewSection::sectionExec().
rotateShape()
TopoDS_Shape TechDraw::rotateShape (const TopoDS_Shape & input, gp_Ax2 & viewAxis, double rotAngle)
rotates a shape about a viewAxis
References Base::Console(), and Base::ConsoleSingleton::Log().
Referenced by TechDraw::DrawViewDetail::detailExec(), TechDraw::DrawViewMulti::execute(), TechDraw::DrawViewPart::makeGeometryForShape(), and TechDraw::DrawViewSection::sectionExec().
scaleShape()
TopoDS_Shape TechDraw::scaleShape (const TopoDS_Shape & input, double scale)
scales a shape about origin
References Base::Console(), and Base::ConsoleSingleton::Log().
Referenced by TechDraw::DrawViewDetail::detailExec(), TechDraw::DrawProjectSplit::getEdgesForWalker(), TechDraw::DrawViewPart::makeGeometryForShape(), TechDraw::CosmeticEdge::scaledGeometry(), TechDraw::CenterLine::scaledGeometry(), and TechDraw::DrawViewSection::sectionExec().