FreeCAD: MeshGui::DlgSettingsMeshView Class Reference
MeshGui::DlgSettingsMeshView Class Reference
The DlgSettingsMeshView class implements a preference page to change settings for display of meshes.
#include <DlgSettingsMeshView.h>
Public Member Functions
DlgSettingsMeshView (QWidget *parent=nullptr)
Constructs a DlgSettingsMeshView which is a child of 'parent'.
~DlgSettingsMeshView ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=0)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void loadSettings ()
void saveSettings ()
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
Detailed Description
The DlgSettingsMeshView class implements a preference page to change settings for display of meshes.
Author
Werner Mayer
Constructor & Destructor Documentation
DlgSettingsMeshView()
DlgSettingsMeshView::DlgSettingsMeshView (QWidget * parent = nullptr)
Constructs a DlgSettingsMeshView which is a child of 'parent'.
~DlgSettingsMeshView()
DlgSettingsMeshView::~DlgSettingsMeshView ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void DlgSettingsMeshView::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
loadSettings()
void DlgSettingsMeshView::loadSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References ParameterGrp::GetBool(), Gui::WindowParameter::getDefaultParameter(), and ParameterGrp::GetGroup().
saveSettings()
void DlgSettingsMeshView::saveSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/Gui/DlgSettingsMeshView.h
Sources/FreeCAD/src/Mod/Mesh/Gui/DlgSettingsMeshView.cpp