FreeCAD: UNV2412 Namespace Reference
UNV2412 Namespace Reference
Classes
struct TRecord
Typedefs
typedef std::vector< TRecord > TDataSet
typedef int TElementLab
typedef std::vector< int > TNodeLabels
Functions
MESHDRIVERUNV_EXPORT bool IsBeam (int theFeDescriptorId)
MESHDRIVERUNV_EXPORT bool IsFace (int theFeDescriptorId)
MESHDRIVERUNV_EXPORT bool IsVolume (int theFeDescriptorId)
MESHDRIVERUNV_EXPORT void Read (std::ifstream &in_stream, TDataSet &theDataSet)
MESHDRIVERUNV_EXPORT void Write (std::ofstream &out_stream, const TDataSet &theDataSet)
Typedef Documentation
TDataSet
typedef std::vector<TRecord> UNV2412::TDataSet
TElementLab
typedef int UNV2412::TElementLab
TNodeLabels
typedef std::vector<int> UNV2412::TNodeLabels
Function Documentation
IsBeam()
bool UNV2412::IsBeam (int theFeDescriptorId)
Referenced by DriverUNV_R_SMDS_Mesh::Perform(), Read(), and Write().
IsFace()
bool UNV2412::IsFace (int theFeDescriptorId)
Referenced by DriverUNV_R_SMDS_Mesh::Perform().
IsVolume()
bool UNV2412::IsVolume (int theFeDescriptorId)
Referenced by DriverUNV_R_SMDS_Mesh::Perform().
Read()
void UNV2412::Read (std::ifstream & in_stream, TDataSet & theDataSet)
References UNV2412::TRecord::beam_aft_end, UNV2412::TRecord::beam_fore_end, UNV2412::TRecord::beam_orientation, UNV::beginning_of_dataset(), UNV2412::TRecord::color, UNV2412::TRecord::fe_descriptor_id, IsBeam(), UNV2412::TRecord::label, UNV2412::TRecord::mat_prop_tab_num, UNV2412::TRecord::node_labels, and UNV2412::TRecord::phys_prop_tab_num.
Referenced by DriverUNV_R_SMDS_Mesh::Perform().
Write()
void UNV2412::Write (std::ofstream & out_stream, const TDataSet & theDataSet)
References UNV2412::TRecord::beam_aft_end, UNV2412::TRecord::beam_fore_end, UNV2412::TRecord::beam_orientation, UNV2412::TRecord::color, UNV2412::TRecord::fe_descriptor_id, IsBeam(), UNV2412::TRecord::label, UNV2412::TRecord::mat_prop_tab_num, UNV2412::TRecord::node_labels, and UNV2412::TRecord::phys_prop_tab_num.
Referenced by DriverUNV_W_SMDS_Mesh::Perform().