FreeCAD: MeshCore::MeshEvalDentsOnSurface Class Reference
MeshCore::MeshEvalDentsOnSurface Class Reference
If an adjacent point (A) of a point (P) can be projected onto a triangle shared by (P) but not by (A) then we have a local dent.
#include <Degeneration.h>
Public Member Functions
bool Evaluate ()
Evaluates the mesh kernel with respect to certain criteria.
std::vector< FacetIndex > GetIndices () const
MeshEvalDentsOnSurface (const MeshKernel &rclM)
~MeshEvalDentsOnSurface ()
Public Member Functions inherited from MeshCore::MeshEvaluation
virtual bool Evaluate ()=0
Evaluates the mesh kernel with respect to certain criteria.
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()
Detailed Description
If an adjacent point (A) of a point (P) can be projected onto a triangle shared by (P) but not by (A) then we have a local dent.
The topology is not affected.
Constructor & Destructor Documentation
MeshEvalDentsOnSurface()
MeshCore::MeshEvalDentsOnSurface::MeshEvalDentsOnSurface (const MeshKernel & rclM)
~MeshEvalDentsOnSurface()
MeshCore::MeshEvalDentsOnSurface::~MeshEvalDentsOnSurface ()
Member Function Documentation
Evaluate()
bool MeshEvalDentsOnSurface::Evaluate () virtual
Evaluates the mesh kernel with respect to certain criteria.
Must be reimplemented by every subclass. This pure virtual function returns false if the mesh kernel is invalid according to this criterion and true if the mesh kernel is correct.
Implements MeshCore::MeshEvaluation.
References MeshCore::MeshGeomFacet::GetNormal(), MeshCore::MeshGeomFacet::IntersectWithLine(), and MeshCore::MeshRefPointToFacets::NeighbourPoints().
Referenced by MeshCore::MeshFixDentsOnSurface::Fixup().
GetIndices()
std::vector< FacetIndex > MeshEvalDentsOnSurface::GetIndices () const
Referenced by MeshCore::MeshFixDentsOnSurface::Fixup().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/Core/Degeneration.h
FreeCAD/src/Mod/Mesh/App/Core/Degeneration.cpp