FreeCAD: TechDrawGui::Ui_DlgPageChooser Class Reference
TechDrawGui::Ui_DlgPageChooser Class Reference
#include <ui_DlgPageChooser.h>
Public Member Functions
void retranslateUi (QDialog *TechDrawGui__DlgPageChooser)
void setupUi (QDialog *TechDrawGui__DlgPageChooser)
Public Attributes
QDialogButtonBox * bbButtons
QLabel * lPrompt
QListWidget * lwPages
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void TechDrawGui::Ui_DlgPageChooser::retranslateUi (QDialog * TechDrawGui__DlgPageChooser)
References lPrompt, lwPages, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void TechDrawGui::Ui_DlgPageChooser::setupUi (QDialog * TechDrawGui__DlgPageChooser)
References bbButtons, draftgeoutils.intersections::connect(), lPrompt, lwPages, retranslateUi(), and verticalLayout.
Member Data Documentation
bbButtons
QDialogButtonBox* TechDrawGui::Ui_DlgPageChooser::bbButtons
Referenced by setupUi().
lPrompt
QLabel* TechDrawGui::Ui_DlgPageChooser::lPrompt
Referenced by retranslateUi(), and setupUi().
lwPages
QListWidget* TechDrawGui::Ui_DlgPageChooser::lwPages
Referenced by TechDrawGui::DlgPageChooser::getSelection(), retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* TechDrawGui::Ui_DlgPageChooser::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/TechDraw/Gui/ui_DlgPageChooser.h