FreeCAD: PartDesignGui::TaskBooleanParameters Class Reference
PartDesignGui::TaskBooleanParameters Class Reference
#include <TaskBooleanParameters.h>
Public Member Functions
const std::vector< std::string > getBodies (void) const
int getType (void) const
TaskBooleanParameters (ViewProviderBoolean *BooleanView, QWidget *parent=nullptr)
~TaskBooleanParameters ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Protected Member Functions
void changeEvent (QEvent *e)
void exitSelectionMode ()
virtual void onSelectionChanged (const Gui::SelectionChanges &msg)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskBooleanParameters()
TaskBooleanParameters::TaskBooleanParameters (ViewProviderBoolean * BooleanView, QWidget * parent = nullptr)
References Gui::BitmapFactory(), draftgeoutils.intersections::connect(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyEnumeration::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::GroupExtension::Group, QSint::ActionGroup::groupLayout(), and PartDesign::Boolean::Type.
~TaskBooleanParameters()
TaskBooleanParameters::~TaskBooleanParameters ()
Member Function Documentation
changeEvent()
void TaskBooleanParameters::changeEvent (QEvent * e) protected
exitSelectionMode()
void TaskBooleanParameters::exitSelectionMode () protected
References Gui::Application::activeDocument(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), and Gui::Application::Instance.
Referenced by onSelectionChanged().
getBodies()
const std::vector< std::string > TaskBooleanParameters::getBodies (void) const
Referenced by PartDesignGui::TaskDlgBooleanParameters::accept().
getType()
int TaskBooleanParameters::getType (void) const
Referenced by PartDesignGui::TaskDlgBooleanParameters::accept(), PathScripts.PathToolEdit.ToolEditor::updateToolType(), and PathScripts.PathToolEdit.ToolEditor::updateUI().
onSelectionChanged()
void TaskBooleanParameters::onSelectionChanged (const Gui::SelectionChanges & msg) protected virtual
Implements Gui::SelectionObserver.
References App::GeoFeatureGroupExtension::addObjects(), Gui::SelectionChanges::AddSelection, PartDesign::Feature::BaseFeature, exitSelectionMode(), DraftVecUtils::find(), PartDesign::Body::findBodyOf(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), Gui::ViewProviderDocumentObject::getObject(), Base::Persistence::getTypeId(), App::PropertyLink::getValue(), App::PropertyString::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Gui::Application::getViewProvider(), App::GroupExtension::Group, Gui::ViewProviderDocumentObject::hide(), Gui::Application::Instance, Base::Type::isDerivedFrom(), App::DocumentObject::Label, App::Document::recomputeFeature(), App::GroupExtension::setObjects(), App::PropertyLinkList::setValues(), and Gui::ViewProviderDocumentObject::show().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/PartDesign/Gui/TaskBooleanParameters.h
FreeCAD/src/Mod/PartDesign/Gui/TaskBooleanParameters.cpp