FreeCAD: TechDrawGui::PreferencesGui Class Reference
TechDrawGui::PreferencesGui Class Reference
#include <PreferencesGui.h>
Static Public Member Functions
static App::Color centerColor ()
static QColor centerQColor ()
static double dimArrowSize ()
static int dimArrowStyle ()
static App::Color dimColor ()
static int dimFontSizePX ()
static QColor dimQColor ()
static double edgeFuzz ()
static QFont labelFontQFont ()
static int labelFontSizePX ()
static App::Color leaderColor ()
static QColor leaderQColor ()
static int mattingStyle ()
static QColor normalQColor ()
static QColor preselectQColor ()
static App::Color sectionLineColor ()
static QColor sectionLineQColor ()
static Qt::PenStyle sectionLineStyle ()
static QColor selectQColor ()
static QColor vertexQColor ()
static QString weldingDirectory ()
Member Function Documentation
centerColor()
App::Color PreferencesGui::centerColor () static
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetUnsigned(), and App::Application::GetUserParameter().
centerQColor()
QColor PreferencesGui::centerQColor () static
Referenced by TechDrawGui::QGICenterLine::getCenterColor(), and TechDrawGui::TaskCenterLine::getCenterColor().
dimArrowSize()
double PreferencesGui::dimArrowSize () static
References App::GetApplication(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by TechDrawGui::QGIArrow::getPrefArrowSize(), and TechDrawGui::QGIWeldSymbol::prefArrowSize().
dimArrowStyle()
int PreferencesGui::dimArrowStyle () static
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), and App::Application::GetUserParameter().
Referenced by TechDrawGui::QGIArrow::getPrefArrowStyle(), TechDrawGui::TaskLeaderLine::getPrefArrowStyle(), and TechDrawGui::DlgPrefsTechDrawDimensionsImp::prefArrowStyle().
dimColor()
App::Color PreferencesGui::dimColor () static
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetUnsigned(), App::Application::GetUserParameter(), and App::Color::setPackedValue().
Referenced by dimQColor(), TechDrawGui::ViewProviderDimension::prefColor(), and TechDrawGui::ViewProviderBalloon::ViewProviderBalloon().
dimFontSizePX()
int PreferencesGui::dimFontSizePX () static
References TechDrawGui::Rez::guiX().
Referenced by TechDrawGui::QGIWeldSymbol::drawAllAround(), and TechDrawGui::QGIWeldSymbol::drawFieldFlag().
dimQColor()
QColor PreferencesGui::dimQColor () static
References App::Color::asValue(), and dimColor().
Referenced by TechDrawGui::QGIViewBalloon::getNormalColor(), and TechDrawGui::QGIViewDimension::prefNormalColor().
edgeFuzz()
double PreferencesGui::edgeFuzz () static
References App::GetApplication(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by TechDrawGui::QGEPath::getEdgeFuzz(), TechDrawGui::QGIDimLines::getEdgeFuzz(), TechDrawGui::QGIEdge::getEdgeFuzz(), and TechDrawGui::QGILeaderLine::getEdgeFuzz().
labelFontQFont()
QFont PreferencesGui::labelFontQFont () static
Referenced by TechDrawGui::QGIRichAnno::prefFont().
labelFontSizePX()
int PreferencesGui::labelFontSizePX () static
References TechDrawGui::Rez::guiX().
Referenced by TechDrawGui::QGIView::drawBorder(), TechDrawGui::QGIView::drawCaption(), TechDrawGui::QGITile::makeText(), MRichTextEdit::MRichTextEdit(), and TechDrawGui::QGIView::QGIView().
leaderColor()
App::Color PreferencesGui::leaderColor () static
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetUnsigned(), App::Application::GetUserParameter(), and App::Color::setPackedValue().
Referenced by TechDrawGui::ViewProviderLeader::getDefLineColor(), TechDrawGui::ViewProviderRichAnno::getDefLineColor(), leaderQColor(), TechDrawGui::TaskLeaderLine::prefLineColor(), and TechDrawGui::TaskRichAnno::prefLineColor().
leaderQColor()
QColor PreferencesGui::leaderQColor () static
References App::Color::asValue(), and leaderColor().
Referenced by TechDrawGui::QGILeaderLine::getNormalColor(), and TechDrawGui::QGIWeldSymbol::prefNormalColor().
mattingStyle()
int PreferencesGui::mattingStyle () static
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), and App::Application::GetUserParameter().
Referenced by TechDrawGui::QGIHighlight::getHoleStyle(), and TechDrawGui::QGIMatting::getHoleStyle().
normalQColor()
QColor PreferencesGui::normalQColor () static
References App::Color::asValue().
Referenced by TechDrawGui::QGIViewPart::drawViewPart(), TechDrawGui::QGCustomText::getNormalColor(), TechDrawGui::QGIPrimPath::getNormalColor(), TechDrawGui::QGIView::getNormalColor(), and TechDrawGui::QGIDecoration::prefNormalColor().
preselectQColor()
QColor PreferencesGui::preselectQColor () static
References App::Color::asValue().
Referenced by TechDrawGui::QGCustomText::getPreColor(), TechDrawGui::QGIPrimPath::getPreColor(), TechDrawGui::QGIView::getPreColor(), and TechDrawGui::QGIDecoration::prefPreColor().
sectionLineColor()
App::Color PreferencesGui::sectionLineColor () static
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetUnsigned(), App::Application::GetUserParameter(), and App::Color::setPackedValue().
Referenced by TechDrawGui::ViewProviderViewPart::prefSectionColor().
sectionLineQColor()
QColor PreferencesGui::sectionLineQColor () static
Referenced by TechDrawGui::QGIHighlight::getHighlightColor(), and TechDrawGui::QGISectionLine::getSectionColor().
sectionLineStyle()
Qt::PenStyle PreferencesGui::sectionLineStyle () static
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), and App::Application::GetUserParameter().
Referenced by TechDrawGui::QGIHighlight::getHighlightStyle(), TechDrawGui::QGISectionLine::getSectionStyle(), and TechDrawGui::ViewProviderViewPart::ViewProviderViewPart().
selectQColor()
QColor PreferencesGui::selectQColor () static
References App::Color::asValue().
Referenced by TechDrawGui::QGCustomText::getSelectColor(), TechDrawGui::QGIPrimPath::getSelectColor(), TechDrawGui::QGIView::getSelectColor(), and TechDrawGui::QGIDecoration::prefSelectColor().
vertexQColor()
QColor PreferencesGui::vertexQColor () static
Referenced by TechDrawGui::QGIViewPart::drawViewPart(), and TechDrawGui::QGIVertex::QGIVertex().
weldingDirectory()
QString PreferencesGui::weldingDirectory () static
References Base::Console(), App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetGroup(), App::Application::getResourceDir(), App::Application::GetUserParameter(), Base::FileInfo::isReadable(), and Base::ConsoleSingleton::Warning().
Referenced by TechDrawGui::DlgPrefsTechDrawGeneralImp::loadSettings(), TechDrawGui::TaskWeldingSymbol::setUiEdit(), and TechDrawGui::TaskWeldingSymbol::setUiPrimary().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/PreferencesGui.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/PreferencesGui.cpp