FreeCAD: GCS::ArcOfHyperbola Class Reference
GCS::ArcOfHyperbola Class Reference
#include <Geo.h>
Public Member Functions
ArcOfHyperbola ()
virtual ArcOfHyperbola * Copy ()
virtual int PushOwnParams (VEC_pD &pvec)
virtual void ReconstructOnNewPvec (VEC_pD &pvec, int &cnt)
virtual ~ArcOfHyperbola ()
Public Member Functions inherited from GCS::Hyperbola
DeriVector2 CalculateNormal (Point &p, double *derivparam=0)
virtual double getRadMaj ()
virtual double getRadMaj (const DeriVector2 &center, const DeriVector2 &f1, double b, double db, double &ret_dRadMaj)
virtual double getRadMaj (double *derivparam, double &ret_dRadMaj)
Hyperbola ()
virtual DeriVector2 Value (double u, double du, double *derivparam=0)
Value: returns point (vector) given the value of parameter.
virtual ~Hyperbola ()
Public Member Functions inherited from GCS::MajorRadiusConic
virtual ~MajorRadiusConic ()
Public Member Functions inherited from GCS::Curve
virtual ~Curve ()
Public Attributes
Point end
double * endAngle
Point start
double * startAngle
Public Attributes inherited from GCS::Hyperbola
Point center
Point focus1
double * radmin
Constructor & Destructor Documentation
ArcOfHyperbola()
GCS::ArcOfHyperbola::ArcOfHyperbola ()
References endAngle, GCS::Hyperbola::radmin, and startAngle.
Referenced by Copy().
~ArcOfHyperbola()
virtual GCS::ArcOfHyperbola::~ArcOfHyperbola () virtual
Member Function Documentation
Copy()
ArcOfHyperbola * GCS::ArcOfHyperbola::Copy (void) virtual
Reimplemented from GCS::Hyperbola.
References ArcOfHyperbola().
PushOwnParams()
int GCS::ArcOfHyperbola::PushOwnParams (VEC_pD & pvec) virtual
Reimplemented from GCS::Hyperbola.
References endAngle, GCS::Hyperbola::PushOwnParams(), and startAngle.
ReconstructOnNewPvec()
void GCS::ArcOfHyperbola::ReconstructOnNewPvec (VEC_pD & pvec, int & cnt) virtual
Reimplemented from GCS::Hyperbola.
References endAngle, GCS::Hyperbola::ReconstructOnNewPvec(), and startAngle.
Member Data Documentation
end
Point GCS::ArcOfHyperbola::end
endAngle
double* GCS::ArcOfHyperbola::endAngle
Referenced by ArcOfHyperbola(), PushOwnParams(), and ReconstructOnNewPvec().
start
Point GCS::ArcOfHyperbola::start
Referenced by Sketcher::Sketch::addArcOfHyperbola().
startAngle
double* GCS::ArcOfHyperbola::startAngle
Referenced by ArcOfHyperbola(), PushOwnParams(), and ReconstructOnNewPvec().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Geo.h
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Geo.cpp