FreeCAD: TechDraw::GeometryUtils Class Reference
TechDraw::GeometryUtils Class Reference
Encapsulates some useful static methods.
#include <Geometry.h>
Classes
struct ReturnType
Used by nextGeom()
Static Public Member Functions
static std::vector< BaseGeom * > chainGeoms (std::vector< BaseGeom * > geoms)
return a vector of BaseGeom*'s in tail to nose order
static TopoDS_Edge edgeFromCircle (TechDraw::Circle *c)
static TopoDS_Edge edgeFromCircleArc (TechDraw::AOC *c)
static TopoDS_Edge edgeFromGeneric (TechDraw::Generic *g)
static ReturnType nextGeom (Base::Vector3d atPoint, std::vector< TechDraw::BaseGeom * > geoms, std::vector< bool > used, double tolerance)
Find an unused geom starts or ends at atPoint.
Detailed Description
Encapsulates some useful static methods.
Member Function Documentation
chainGeoms()
BaseGeomPtrVector GeometryUtils::chainGeoms (std::vector< BaseGeom * > geoms) static
return a vector of BaseGeom*'s in tail to nose order
References Base::Console(), TechDraw::BaseGeom::getEndPoint(), TechDraw::BaseGeom::getStartPoint(), Base::ConsoleSingleton::Log(), nextGeom(), and TechDraw::BaseGeom::reversed.
edgeFromCircle()
TopoDS_Edge GeometryUtils::edgeFromCircle (TechDraw::Circle * c) static
Referenced by TechDraw::CosmeticEdge::Restore(), and TechDraw::CenterLine::Restore().
edgeFromCircleArc()
TopoDS_Edge GeometryUtils::edgeFromCircleArc (TechDraw::AOC * c) static
Referenced by TechDraw::CosmeticEdge::Restore(), and TechDraw::CenterLine::Restore().
edgeFromGeneric()
TopoDS_Edge GeometryUtils::edgeFromGeneric (TechDraw::Generic * g) static
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by TechDraw::CosmeticEdge::Restore(), and TechDraw::CenterLine::Restore().
nextGeom()
GeometryUtils::ReturnType GeometryUtils::nextGeom (Base::Vector3d atPoint, std::vector< TechDraw::BaseGeom * > geoms, std::vector< bool > used, double tolerance) static
Find an unused geom starts or ends at atPoint.
returns index[1:geoms.size()),reversed [true,false]
References draftutils.utils::tolerance().
Referenced by chainGeoms().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/App/Geometry.h
Sources/FreeCAD/src/Mod/TechDraw/App/Geometry.cpp