FreeCAD: nurbs Namespace Reference
nurbs Namespace Reference
Classes
struct NurbsBase1D
struct NurbsBase2D
Typedefs
typedef Eigen::SparseMatrix< double > spMat
typedef Eigen::Triplet< double > trip
Functions
void add_triplets (Eigen::VectorXd values, double row, std::vector< trip > &triplets)
double divide (double a, double b)
std::function< double(double)> get_basis (int degree, int i, Eigen::VectorXd knots)
std::function< double(double)> get_basis_derivative (int order, int degree, int i, Eigen::VectorXd knots)
Typedef Documentation
spMat
typedef Eigen::SparseMatrix<double> nurbs::spMat
trip
typedef Eigen::Triplet<double> nurbs::trip
Function Documentation
add_triplets()
void nurbs::add_triplets (Eigen::VectorXd values, double row, std::vector< trip > & triplets)
Referenced by nurbs::NurbsBase2D::getDuMatrix(), nurbs::NurbsBase1D::getDuMatrix(), nurbs::NurbsBase2D::getDvMatrix(), nurbs::NurbsBase2D::getInfluenceMatrix(), and nurbs::NurbsBase1D::getInfluenceMatrix().
divide()
double nurbs::divide (double a, double b)
Referenced by get_basis().
get_basis()
std::function< double(double)> nurbs::get_basis (int degree, int i, Eigen::VectorXd knots)
References divide(), and get_basis().
Referenced by get_basis(), get_basis_derivative(), nurbs::NurbsBase1D::NurbsBase1D(), and nurbs::NurbsBase2D::NurbsBase2D().
get_basis_derivative()
std::function< double(double)> nurbs::get_basis_derivative (int order, int degree, int i, Eigen::VectorXd knots)
References get_basis(), and get_basis_derivative().
Referenced by nurbs::NurbsBase2D::computeFirstDerivatives(), nurbs::NurbsBase1D::computeFirstDerivatives(), nurbs::NurbsBase2D::computeSecondDerivatives(), nurbs::NurbsBase1D::computeSecondDerivatives(), and get_basis_derivative().