FreeCAD: MED Namespace Reference
MED Namespace Reference
Namespaces
V2_2
Classes
class PrefixPrinter
class SharedPtr
To extend the boost::shared_ptr to support such features automatic dynamic cast.
struct TBallInfo
Define a class representing MED_BALL structure element.
struct TBase
Define a parent class for all MEDWrapper classes.
struct TCellInfo
Define a base class which represents MED Cells entity.
class TCoordHelper
class TCSlice
This class intends to provide an uniform way to handle multy-dimention data (const version)
struct TElemInfo
Define a parent class for all MED entities that describes mesh entites such as nodes and cells.
struct TFamilyInfo
Define a base class which represents MED Family entity.
struct TFieldInfo
Define a base class which represents MED Field entity.
class TGaussCoord
Define a helper class to handle Gauss Points coordinates.
struct TGaussDef
Description of family of integration points.
struct TGaussInfo
The class represents MED Gauss entity.
struct TGrilleInfo
Define a base class which represents MED Grille (structured mesh)
struct THexa20a
struct THexa20b
struct THexa27a
struct THexa8a
struct THexa8b
class TLockProxy
This class provide thread-safety for MEDWrapper interaction.
struct TMeshInfo
Define a base class which represents MED Mesh entity.
struct TMeshValueBase
The class is a helper one. It provide safe and flexible way to get access to values for a MED TimeStamp.
struct TModeSwitchInfo
Define a parent class for all MED entities that contains a sequence of numbers.
struct TNameInfo
Define a parent class for all named MED entities.
struct TNodeInfo
Define a base class which represents MED Nodes entity.
struct TPenta15a
struct TPenta15b
struct TPenta6a
struct TPenta6b
struct TPolyedreInfo
Define a base class which represents MED Polyedre entity.
struct TPolygoneInfo
Define a base class which represents MED Polygon entity.
struct TProfileInfo
The class represents MED Profile entity.
struct TPyra13a
struct TPyra13b
struct TPyra5a
struct TPyra5b
struct TQuad4a
struct TQuad4b
struct TQuad8a
struct TQuad8b
struct TQuad9a
struct TQuad9b
struct TSeg2a
struct TSeg3a
struct TShapeFun
Shape function definitions.
class TSlice
This class extend TCSlice functionality for non-constant case.
struct TTBallInfo
struct TTCellInfo
struct TTElemInfo
struct TTetra10a
struct TTetra10b
struct TTetra4a
struct TTetra4b
struct TTFamilyInfo
struct TTFieldInfo
struct TTGaussInfo
struct TTGrilleInfo
struct TTimeStampInfo
Define a base class which represents MED TimeStamp.
struct TTimeStampValue
The class implements a container for MED TimeStamp values.
struct TTimeStampValueBase
The class is a base class for MED TimeStamp values holder.
struct TTMeshInfo
struct TTMeshValue
The class is a helper one. It provide safe and flexible way to get access to values for a MED TimeStamp.
struct TTNameInfo
struct TTNodeInfo
struct TTPolyedreInfo
struct TTPolygoneInfo
struct TTProfileInfo
struct TTria3a
struct TTria3b
struct TTria6a
struct TTria6b
struct TTTimeStampInfo
struct TTTimeStampValue
class TTWrapper
struct TValueHolder
To provide a common way to handle values of MEDWrapper types as native MED types.
struct TValueHolder< TVector< TVal >, TRepresentation >
To customize TValueHolder common template definition for TVector.
class TVector
Main purpose to introduce the class was to customize operator [].
struct TWrapper
Define a base class that wraps the MED API.
Typedefs
typedef SharedPtr< TBallInfo > PBallInfo
typedef SharedPtr< TCellInfo > PCellInfo
typedef SharedPtr< TCoordHelper > PCoordHelper
typedef SharedPtr< TElemInfo > PElemInfo
typedef SharedPtr< TElemNum > PElemNum
typedef SharedPtr< TFamilyInfo > PFamilyInfo
typedef SharedPtr< TFieldInfo > PFieldInfo
typedef SharedPtr< TFloatTimeStampValue > PFloatTimeStampValue
typedef SharedPtr< TGaussCoord > PGaussCoord
typedef SharedPtr< TGaussInfo > PGaussInfo
typedef SharedPtr< TGrilleInfo > PGrilleInfo
typedef SharedPtr< TIntTimeStampValue > PIntTimeStampValue
typedef SharedPtr< TMeshInfo > PMeshInfo
typedef SharedPtr< TNameInfo > PNameInfo
typedef SharedPtr< TNodeCoord > PNodeCoord
typedef SharedPtr< TNodeInfo > PNodeInfo
typedef SharedPtr< TPolyedreInfo > PPolyedreInfo
typedef SharedPtr< TPolygoneInfo > PPolygoneInfo
typedef SharedPtr< TProfileInfo > PProfileInfo
typedef SharedPtr< TString > PString
typedef SharedPtr< TTimeStampInfo > PTimeStampInfo
typedef PFloatTimeStampValue PTimeStampVal
typedef SharedPtr< TTimeStampValueBase > PTimeStampValueBase
typedef SharedPtr< TWrapper > PWrapper
typedef TCIntVecSlice TCConnSlice
typedef TVector< TCConnSlice > TCConnSliceArr
typedef TCFloatVecSlice TCCoordSlice
typedef TVector< TCCoordSlice > TCCoordSliceArr
typedef TCSlice< TFloat > TCFloatVecSlice
typedef TCSlice< TInt > TCIntVecSlice
typedef TIntVecSlice TConnSlice
typedef TVector< TConnSlice > TConnSliceArr
typedef TFloatVecSlice TCoordSlice
typedef TVector< TCoordSlice > TCoordSliceArr
typedef TCSlice< TFloat > TCValueSlice
typedef TVector< TCValueSlice > TCValueSliceArr
typedef std::vector< double > TDoubleVector
typedef TIntVector TElemNum
typedef std::map< EEntiteMaillage, TFieldInfo2TimeStampInfoSet > TEntite2TFieldInfo2TimeStampInfoSet
typedef std::map< EEntiteMaillage, TFamilyTSizeSet > TEntity2FamilySet
typedef std::map< EEntiteMaillage, TGeomSet > TEntity2GeomSet
typedef std::map< EEntiteMaillage, TGeom2ElemInfo > TEntity2TGeom2ElemInfo
typedef std::map< EEntiteMaillage, TGeom2Size > TEntityInfo
typedef herr_t TErr
typedef TIntVector TFamAttr
typedef std::map< TInt, TInt > TFamilyID2NbCells
typedef std::set< PFamilyInfo > TFamilyInfoSet
typedef boost::tuple< PFamilyInfo, TInt > TFamilyTSize
typedef std::set< TFamilyTSize > TFamilyTSizeSet
typedef std::map< PFieldInfo, TTimeStampInfoSet > TFieldInfo2TimeStampInfoSet
typedef double TFloat
typedef TTMeshValue< TFloatVector > TFloatMeshValue
typedef TTimeStampValue< TFloatMeshValue > TFloatTimeStampValue
typedef TSlice< TFloat > TFloatVecSlice
typedef TVector< TFloat > TFloatVector
typedef std::set< EGeometrieElement > TGeom
typedef std::map< EGeometrieElement, PElemInfo > TGeom2ElemInfo
typedef std::map< EGeometrieElement, PGaussInfo > TGeom2Gauss
typedef std::map< EGeometrieElement, TInt > TGeom2NbGauss
typedef std::map< EGeometrieElement, PProfileInfo > TGeom2Profile
typedef std::map< EGeometrieElement, TInt > TGeom2Size
typedef std::map< EGeometrieElement, TMeshValue > TGeom2Value
typedef std::set< EGeometrieElement > TGeomSet
typedef TFloat(* TGetCoord) (const TCCoordSlice &theCoordSlice)
typedef std::map< std::string, TFamilyInfoSet > TGroupInfo
typedef hid_t TIdt
typedef std::map< TInt, TFloatVector > TIndexes
typedef int TInt
typedef TTMeshValue< TIntVector > TIntMeshValue
typedef TTimeStampValue< TIntMeshValue > TIntTimeStampValue
typedef TSlice< TInt > TIntVecSlice
typedef TVector< TInt > TIntVector
typedef std::map< TGaussInfo::TKey, PGaussInfo, TGaussInfo::TLess > TKey2Gauss
typedef std::map< TProfileInfo::TKey, PProfileInfo > TKey2Profile
typedef TFloatMeshValue TMeshValue
typedef boost::tuple< EModeProfil, TKey2Profile > TMKey2Profile
typedef std::map< TInt, TString > TNames
typedef TFloatVector TNodeCoord
typedef TVector< char > TString
Defines a type for managing sequence of strings.
typedef std::set< std::string > TStringSet
typedef TVector< std::string > TStringVector
typedef std::set< PTimeStampInfo > TTimeStampInfoSet
typedef TFloatTimeStampValue TTimeStampVal
typedef TFloatVector TValue
typedef TSlice< TFloat > TValueSlice
typedef TVector< TValueSlice > TValueSliceArr
typedef TFloatVector TWeight
Enumerations
enum EBooleen { eFAUX, eVRAI }
enum EConnectivite { eNOD, eDESC }
enum ECoordName { eX, eY, eZ, eNone }
enum EEntiteMaillage {
eMAILLE, eFACE, eARETE, eNOEUD,
eNOEUD_ELEMENT, eSTRUCT_ELEMENT
}
enum EGeometrieElement {
ePOINT1 =1, eSEG2 =102, eSEG3 =103, eTRIA3 =203,
eQUAD4 =204, eTRIA6 =206, eTRIA7 =207, eQUAD8 =208,
eQUAD9 =209, eTETRA4 =304, ePYRA5 =305, ePENTA6 =306,
eHEXA8 =308, eOCTA12 =312, eTETRA10 =310, ePYRA13 =313,
ePENTA15 =315, eHEXA20 =320, eHEXA27 =327, ePOLYGONE =400,
ePOLYGON2 =420, ePOLYEDRE =500, eNONE =0, eBALL =1101,
eAllGeoType =-1
}
enum EGrilleType { eGRILLE_CARTESIENNE, eGRILLE_POLAIRE, eGRILLE_STANDARD }
enum EMaillage { eNON_STRUCTURE, eSTRUCTURE }
enum EModeProfil { eNO_PFLMOD, eGLOBAL, eCOMPACT }
enum EModeSwitch { eFULL_INTERLACE, eNO_INTERLACE }
enum ERepere { eCART, eCYL, eSPHER }
enum ETable {
eCOOR, eCONN, eNOM, eNUM,
eFAM, eCOOR_IND1, eCOOR_IND2, eCOOR_IND3
}
enum ETypeChamp { eFLOAT64 =6, eINT =24, eLONG =26 }
enum EVersion { eVUnknown = -1, eV2_1, eV2_2 }
Functions
PFloatTimeStampValue MEDWRAPPER_EXPORT CastToFloatTimeStampValue (const PTimeStampValueBase &theTimeStampValue)
PIntTimeStampValue MEDWRAPPER_EXPORT CastToIntTimeStampValue (const PTimeStampValueBase &theTimeStampValue)
MEDWRAPPER_EXPORT EEntiteMaillage ConvertEntity (const EEntiteMaillage &aEntity)
Convert eNOEUD_ELEMENT to eMAILLE.
template<class TMeshValueType >
void CopyTimeStampValue (SharedPtr< TTimeStampValue< TMeshValueType > > theTimeStampValueFrom, SharedPtr< TTimeStampValue< TMeshValueType > > theTimeStampValueTo)
template<class TMeshValueTypeFrom , class TMeshValueTypeTo >
void CopyTimeStampValue (SharedPtr< TTimeStampValue< TMeshValueTypeFrom > > theTimeStampValueFrom, SharedPtr< TTimeStampValue< TMeshValueTypeTo > > theTimeStampValueTo)
void CopyTimeStampValueBase (const PTimeStampValueBase &theValueFrom, const PTimeStampValueBase &theValueTo)
MEDWRAPPER_FACTORY_EXPORT PWrapper CrWrapper (const std::string &theFileName, bool theDoPreCheckInSeparateProcess=false)
MEDWRAPPER_FACTORY_EXPORT PWrapper CrWrapper (const std::string &theFileName, EVersion theId)
MEDWRAPPER_EXPORT bool GetBaryCenter (const TCellInfo &theCellInfo, const TNodeInfo &theNodeInfo, TGaussCoord &theGaussCoord, const TElemNum &theElemNum=TElemNum(), EModeSwitch theMode=eFULL_INTERLACE)
To calculate Gauss Points coordinates for defined TCellInfo as its bary center.
MEDWRAPPER_EXPORT bool GetBaryCenter (const TPolyedreInfo &thePolyedreInfo, const TNodeInfo &theNodeInfo, TGaussCoord &theGaussCoord, const TElemNum &theElemNum=TElemNum(), EModeSwitch theMode=eFULL_INTERLACE)
To calculate Gauss Points coordinates for defined TPolyedreInfo as its bary center.
MEDWRAPPER_EXPORT bool GetBaryCenter (const TPolygoneInfo &thePolygoneInfo, const TNodeInfo &theNodeInfo, TGaussCoord &theGaussCoord, const TElemNum &theElemNum=TElemNum(), EModeSwitch theMode=eFULL_INTERLACE)
To calculate Gauss Points coordinates for defined TPolygoneInfo as its bary center.
template<ECoordName TCoordId>
TFloat GetCoord (const TCCoordSlice &theCoordSlice)
template<>
TFloat GetCoord< eNone > (const TCCoordSlice &theCoordSlice)
MEDWRAPPER_EXPORT PCoordHelper GetCoordHelper (PNodeInfo theNodeInfo)
template<EVersion >
TInt MEDWRAPPER_EXPORT GetDESCLength ()
template<>
TInt MED_V22_WRAPPER_EXPORT GetDESCLength< eV2_2 > ()
MEDWRAPPER_EXPORT TInt GetDimGaussCoord (EGeometrieElement theGeom)
Get dimension of the Gauss coordinates for the defined type of mesh cell.
MEDWRAPPER_EXPORT TEntite2TFieldInfo2TimeStampInfoSet GetEntite2TFieldInfo2TimeStampInfoSet (const TFieldInfo2TimeStampInfoSet &theFieldInfo2TimeStampInfoSet)
Split the input set of MED TIMESTAMPS by corresponding MED FIELDS and MED ENTITIES.
MEDWRAPPER_EXPORT TEntity2FamilySet GetEntity2FamilySet (const PWrapper &theWrapper, const TEntity2TGeom2ElemInfo &theEntity2TGeom2ElemInfo, const TFamilyInfoSet &theFamilyInfoSet)
Split set of MED FAMILIES by corresponding MED ENTITY.
MEDWRAPPER_EXPORT const TEntity2GeomSet & GetEntity2GeomSet ()
MEDWRAPPER_EXPORT TEntity2TGeom2ElemInfo GetEntity2TGeom2ElemInfo (const PWrapper &theWrapper, const PMeshInfo &theMeshInfo, const MED::TEntityInfo &theEntityInfo)
Get set of TElemInfo by its geometrical type and corresponding MED ENTITY.
MEDWRAPPER_EXPORT EEntiteMaillage GetEntityByFamilyId (PGrilleInfo &theInfo, TInt theId)
Get Entity for Grille by family id.
MEDWRAPPER_EXPORT TFamilyID2NbCells GetFamilyID2NbCells (PGrilleInfo &theInfo)
Get Number of cells for theId family, for Grille.
MEDWRAPPER_EXPORT TFamilyInfoSet GetFamilyInfoSet (const PWrapper &theWrapper, const PMeshInfo &theMeshInfo)
Read set of MED FAMILIES for defined MED file.
MEDWRAPPER_EXPORT TFieldInfo2TimeStampInfoSet GetFieldInfo2TimeStampInfoSet (const PWrapper &theWrapper, const PMeshInfo &theMeshInfo, const MED::TEntityInfo &theEntityInfo)
Read set of MED TIMESTAMPS groupped by corresponding MED FIELDS.
MEDWRAPPER_EXPORT bool GetGaussCoord3D (const TGaussInfo &theGaussInfo, const TCellInfo &theCellInfo, const TNodeInfo &theNodeInfo, TGaussCoord &theGaussCoord, const TElemNum &theElemNum=TElemNum(), EModeSwitch theMode=eFULL_INTERLACE)
To calculate Gauss Points coordinates.
MEDWRAPPER_EXPORT TGroupInfo GetGroupInfo (const TFamilyInfoSet &theFamilyInfoSet)
Split the input set of MED FAMILIES by corresponding MED GROUPS.
template<EVersion >
TInt MEDWRAPPER_EXPORT GetIDENTLength ()
template<>
TInt MED_V22_WRAPPER_EXPORT GetIDENTLength< eV2_2 > ()
MEDWRAPPER_EXPORT TKey2Gauss GetKey2Gauss (const PWrapper &theWrapper, TErr *theErr=NULL, EModeSwitch theMode=eFULL_INTERLACE)
Read set of MED GAUSS.
template<EVersion >
TInt MEDWRAPPER_EXPORT GetLNOMLength ()
template<>
TInt MED_V22_WRAPPER_EXPORT GetLNOMLength< eV2_2 > ()
MEDWRAPPER_FACTORY_EXPORT bool getMEDVersion (const std::string &, int &, int &, int &)
MEDWRAPPER_EXPORT TMKey2Profile GetMKey2Profile (const PWrapper &theWrapper, TErr *theErr=NULL, EModeProfil theMode=eCOMPACT)
Read set of MED PROFILES.
template<EVersion >
MEDWRAPPER_EXPORT TInt GetNbConn (EGeometrieElement typmai, EEntiteMaillage typent, TInt mdim)
template<>
TInt MED_V22_WRAPPER_EXPORT GetNbConn< eV2_2 > (EGeometrieElement typmai, EEntiteMaillage typent, TInt mdim)
MEDWRAPPER_EXPORT TInt GetNbNodes (EGeometrieElement typmai)
MEDWRAPPER_EXPORT TInt GetNbRefCoord (EGeometrieElement theGeom)
Get number of referenced nodes for the defined type of mesh cell.
template<EVersion >
TInt MEDWRAPPER_EXPORT GetNOMLength ()
template<>
TInt MED_V22_WRAPPER_EXPORT GetNOMLength< eV2_2 > ()
template<EVersion >
TInt MEDWRAPPER_EXPORT GetPNOMLength ()
template<>
TInt MED_V22_WRAPPER_EXPORT GetPNOMLength< eV2_2 > ()
MEDWRAPPER_EXPORT PProfileInfo GetProfileInfo (const PWrapper &theWrapper, const std::string &theProfileName, TErr *theErr=NULL, EModeProfil theMode=eCOMPACT)
Get MED PROFILE by its name.
MEDWRAPPER_EXPORT std::string GetString (TInt theId, TInt theStep, const TString &theString)
Extract a substring from the sequence of the strings.
MEDWRAPPER_FACTORY_EXPORT EVersion GetVersionId (const std::string &theFileName, bool theDoPreCheckInSeparateProcess=false)
template<EVersion >
void MEDWRAPPER_EXPORT GetVersionRelease (TInt &majeur, TInt &mineur, TInt &release)
template<>
void MED_V22_WRAPPER_EXPORT GetVersionRelease< eV2_2 > (TInt &majeur, TInt &mineur, TInt &release)
bool IsEqual (TFloat theLeft, TFloat theRight)
bool operator< (const TFamilyTSize &theLeft, const TFamilyTSize &theRight)
template<class TimeStampValueType >
void Print (SharedPtr< TimeStampValueType > theTimeStampValue)
MEDWRAPPER_EXPORT void SetString (TInt theId, TInt theStep, TString &theString, const std::string &theValue)
Set a substring in the sequence of the strings.
MEDWRAPPER_EXPORT void SetString (TInt theId, TInt theStep, TString &theString, const TString &theValue)
Set a substring in the sequence of the strings.
Variables
TGetCoord aXGetCoord [3]
TGetCoord aXYGetCoord [3]
TGetCoord aXYZGetCoord [3]
TGetCoord aXZGetCoord [3]
TGetCoord aYGetCoord [3]
TGetCoord aYZGetCoord [3]
TGetCoord aZGetCoord [3]
Typedef Documentation
PBallInfo
typedef SharedPtr<TBallInfo> MED::PBallInfo
PCellInfo
typedef SharedPtr<TCellInfo> MED::PCellInfo
PCoordHelper
typedef SharedPtr<TCoordHelper> MED::PCoordHelper
PElemInfo
typedef SharedPtr<TElemInfo> MED::PElemInfo
PElemNum
typedef SharedPtr<TElemNum> MED::PElemNum
PFamilyInfo
typedef SharedPtr<TFamilyInfo> MED::PFamilyInfo
PFieldInfo
typedef SharedPtr<TFieldInfo> MED::PFieldInfo
PFloatTimeStampValue
typedef SharedPtr<TFloatTimeStampValue> MED::PFloatTimeStampValue
PGaussCoord
typedef SharedPtr<TGaussCoord> MED::PGaussCoord
PGaussInfo
typedef SharedPtr<TGaussInfo> MED::PGaussInfo
PGrilleInfo
typedef SharedPtr<TGrilleInfo> MED::PGrilleInfo
PIntTimeStampValue
typedef SharedPtr<TIntTimeStampValue> MED::PIntTimeStampValue
PMeshInfo
typedef SharedPtr<TMeshInfo> MED::PMeshInfo
PNameInfo
typedef SharedPtr<TNameInfo> MED::PNameInfo
PNodeCoord
typedef SharedPtr<TNodeCoord> MED::PNodeCoord
PNodeInfo
typedef SharedPtr<TNodeInfo> MED::PNodeInfo
PPolyedreInfo
typedef SharedPtr<TPolyedreInfo> MED::PPolyedreInfo
PPolygoneInfo
typedef SharedPtr<TPolygoneInfo> MED::PPolygoneInfo
PProfileInfo
typedef SharedPtr<TProfileInfo> MED::PProfileInfo
PString
typedef SharedPtr<TString> MED::PString
PTimeStampInfo
typedef SharedPtr<TTimeStampInfo> MED::PTimeStampInfo
PTimeStampVal
typedef PFloatTimeStampValue MED::PTimeStampVal
PTimeStampValueBase
typedef SharedPtr<TTimeStampValueBase> MED::PTimeStampValueBase
PWrapper
typedef SharedPtr<TWrapper> MED::PWrapper
TCConnSlice
typedef TCIntVecSlice MED::TCConnSlice
TCConnSliceArr
typedef TVector<TCConnSlice> MED::TCConnSliceArr
TCCoordSlice
typedef TCFloatVecSlice MED::TCCoordSlice
TCCoordSliceArr
typedef TVector<TCCoordSlice> MED::TCCoordSliceArr
TCFloatVecSlice
typedef TCSlice<TFloat> MED::TCFloatVecSlice
TCIntVecSlice
typedef TCSlice<TInt> MED::TCIntVecSlice
TConnSlice
typedef TIntVecSlice MED::TConnSlice
TConnSliceArr
typedef TVector<TConnSlice> MED::TConnSliceArr
TCoordSlice
typedef TFloatVecSlice MED::TCoordSlice
TCoordSliceArr
typedef TVector<TCoordSlice> MED::TCoordSliceArr
TCValueSlice
typedef TCSlice<TFloat> MED::TCValueSlice
TCValueSliceArr
typedef TVector<TCValueSlice> MED::TCValueSliceArr
TDoubleVector
typedef std::vector<double> MED::TDoubleVector
TElemNum
typedef TIntVector MED::TElemNum
TEntite2TFieldInfo2TimeStampInfoSet
typedef std::map<EEntiteMaillage,TFieldInfo2TimeStampInfoSet> MED::TEntite2TFieldInfo2TimeStampInfoSet
TEntity2FamilySet
typedef std::map<EEntiteMaillage,TFamilyTSizeSet> MED::TEntity2FamilySet
TEntity2GeomSet
typedef std::map<EEntiteMaillage,TGeomSet> MED::TEntity2GeomSet
TEntity2TGeom2ElemInfo
typedef std::map<EEntiteMaillage,TGeom2ElemInfo> MED::TEntity2TGeom2ElemInfo
TEntityInfo
typedef std::map<EEntiteMaillage,TGeom2Size> MED::TEntityInfo
TErr
typedef herr_t MED::TErr
TFamAttr
typedef TIntVector MED::TFamAttr
TFamilyID2NbCells
typedef std::map<TInt,TInt> MED::TFamilyID2NbCells
TFamilyInfoSet
typedef std::set<PFamilyInfo> MED::TFamilyInfoSet
TFamilyTSize
typedef boost::tuple<PFamilyInfo,TInt> MED::TFamilyTSize
TFamilyTSizeSet
typedef std::set<TFamilyTSize> MED::TFamilyTSizeSet
TFieldInfo2TimeStampInfoSet
typedef std::map<PFieldInfo,TTimeStampInfoSet> MED::TFieldInfo2TimeStampInfoSet
TFloat
typedef double MED::TFloat
TFloatMeshValue
typedef TTMeshValue<TFloatVector> MED::TFloatMeshValue
TFloatTimeStampValue
typedef TTimeStampValue<TFloatMeshValue> MED::TFloatTimeStampValue
TFloatVecSlice
typedef TSlice<TFloat> MED::TFloatVecSlice
TFloatVector
typedef TVector< TFloat > MED::TFloatVector
TGeom
typedef std::set<EGeometrieElement> MED::TGeom
TGeom2ElemInfo
typedef std::map<EGeometrieElement,PElemInfo> MED::TGeom2ElemInfo
TGeom2Gauss
typedef std::map<EGeometrieElement,PGaussInfo> MED::TGeom2Gauss
TGeom2NbGauss
typedef std::map<EGeometrieElement,TInt> MED::TGeom2NbGauss
TGeom2Profile
typedef std::map<EGeometrieElement,PProfileInfo> MED::TGeom2Profile
TGeom2Size
typedef std::map<EGeometrieElement,TInt> MED::TGeom2Size
TGeom2Value
typedef std::map<EGeometrieElement,TMeshValue> MED::TGeom2Value
TGeomSet
typedef std::set<EGeometrieElement> MED::TGeomSet
TGetCoord
typedef TFloat(* MED::TGetCoord) (const TCCoordSlice &theCoordSlice)
TGroupInfo
typedef std::map<std::string,TFamilyInfoSet> MED::TGroupInfo
TIdt
typedef hid_t MED::TIdt
TIndexes
typedef std::map<TInt,TFloatVector> MED::TIndexes
TInt
typedef int MED::TInt
TIntMeshValue
typedef TTMeshValue<TIntVector> MED::TIntMeshValue
TIntTimeStampValue
typedef TTimeStampValue<TIntMeshValue> MED::TIntTimeStampValue
TIntVecSlice
typedef TSlice<TInt> MED::TIntVecSlice
TIntVector
typedef TVector< TInt > MED::TIntVector
TKey2Gauss
typedef std::map<TGaussInfo::TKey,PGaussInfo,TGaussInfo::TLess> MED::TKey2Gauss
TKey2Profile
typedef std::map<TProfileInfo::TKey,PProfileInfo> MED::TKey2Profile
TMeshValue
typedef TFloatMeshValue MED::TMeshValue
TMKey2Profile
typedef boost::tuple<EModeProfil,TKey2Profile> MED::TMKey2Profile
TNames
typedef std::map<TInt,TString> MED::TNames
TNodeCoord
typedef TFloatVector MED::TNodeCoord
TString
typedef TVector<char> MED::TString
Defines a type for managing sequence of strings.
TStringSet
typedef std::set<std::string> MED::TStringSet
TStringVector
typedef TVector<std::string> MED::TStringVector
TTimeStampInfoSet
typedef std::set<PTimeStampInfo> MED::TTimeStampInfoSet
TTimeStampVal
typedef TFloatTimeStampValue MED::TTimeStampVal
TValue
typedef TFloatVector MED::TValue
TValueSlice
typedef TSlice<TFloat> MED::TValueSlice
TValueSliceArr
typedef TVector<TValueSlice> MED::TValueSliceArr
TWeight
typedef TFloatVector MED::TWeight
Enumeration Type Documentation
EBooleen
enum MED::EBooleen
Enumerator
eFAUX
eVRAI
EConnectivite
enum MED::EConnectivite
Enumerator
eNOD
eDESC
ECoordName
enum MED::ECoordName
Enumerator
eX
eY
eZ
eNone
EEntiteMaillage
enum MED::EEntiteMaillage
Enumerator
eMAILLE
eFACE
eARETE
eNOEUD
eNOEUD_ELEMENT
eSTRUCT_ELEMENT
EGeometrieElement
enum MED::EGeometrieElement
Enumerator
ePOINT1
eSEG2
eSEG3
eTRIA3
eQUAD4
eTRIA6
eTRIA7
eQUAD8
eQUAD9
eTETRA4
ePYRA5
ePENTA6
eHEXA8
eOCTA12
eTETRA10
ePYRA13
ePENTA15
eHEXA20
eHEXA27
ePOLYGONE
ePOLYGON2
ePOLYEDRE
eNONE
eBALL
eAllGeoType
EGrilleType
enum MED::EGrilleType
Enumerator
eGRILLE_CARTESIENNE
eGRILLE_POLAIRE
eGRILLE_STANDARD
EMaillage
enum MED::EMaillage
Enumerator
eNON_STRUCTURE
eSTRUCTURE
EModeProfil
enum MED::EModeProfil
Enumerator
eNO_PFLMOD
eGLOBAL
eCOMPACT
EModeSwitch
enum MED::EModeSwitch
Enumerator
eFULL_INTERLACE
eNO_INTERLACE
ERepere
enum MED::ERepere
Enumerator
eCART
eCYL
eSPHER
ETable
enum MED::ETable
Enumerator
eCOOR
eCONN
eNOM
eNUM
eFAM
eCOOR_IND1
eCOOR_IND2
eCOOR_IND3
ETypeChamp
enum MED::ETypeChamp
Enumerator
eFLOAT64
eINT
eLONG
EVersion
enum MED::EVersion
Enumerator
eVUnknown
eV2_1
eV2_2
Function Documentation
CastToFloatTimeStampValue()
PFloatTimeStampValue MED::CastToFloatTimeStampValue (const PTimeStampValueBase & theTimeStampValue)
CastToIntTimeStampValue()
PIntTimeStampValue MED::CastToIntTimeStampValue (const PTimeStampValueBase & theTimeStampValue)
ConvertEntity()
EEntiteMaillage MED::ConvertEntity (const EEntiteMaillage & aEntity)
Convert eNOEUD_ELEMENT to eMAILLE.
References eARETE, eFACE, eMAILLE, eNOEUD, and eNOEUD_ELEMENT.
Referenced by GetEntite2TFieldInfo2TimeStampInfoSet().
CopyTimeStampValue() [1/2]
template<class TMeshValueType > void MED::CopyTimeStampValue (SharedPtr< TTimeStampValue< TMeshValueType > > theTimeStampValueFrom, SharedPtr< TTimeStampValue< TMeshValueType > > theTimeStampValueTo)
References MED::TTimeStampValue< TMeshValueType >::myGeom2Value.
CopyTimeStampValue() [2/2]
template<class TMeshValueTypeFrom , class TMeshValueTypeTo > void MED::CopyTimeStampValue (SharedPtr< TTimeStampValue< TMeshValueTypeFrom > > theTimeStampValueFrom, SharedPtr< TTimeStampValue< TMeshValueTypeTo > > theTimeStampValueTo)
References MED::TTimeStampValue< TMeshValueType >::myGeom2Value.
CopyTimeStampValueBase()
void MED::CopyTimeStampValueBase (const PTimeStampValueBase & theValueFrom, const PTimeStampValueBase & theValueTo)
References eFLOAT64, and eINT.
Referenced by MED::TWrapper::GetTimeStampVal(), and MED::TWrapper::SetTimeStamp().
CrWrapper() [1/2]
PWrapper MED::CrWrapper (const std::string & theFileName, bool theDoPreCheckInSeparateProcess = false)
References eV2_1, eV2_2, and GetVersionId().
Referenced by DriverMED_R_SMESHDS_Mesh::GetMeshNames(), DriverMED_R_SMESHDS_Mesh::Perform(), DriverMED_W_Field::Perform(), and DriverMED_W_SMESHDS_Mesh::Perform().
CrWrapper() [2/2]
PWrapper MED::CrWrapper (const std::string & theFileName, EVersion theId)
References eV2_1, eV2_2, and GetVersionId().
GetBaryCenter() [1/3]
bool MED::GetBaryCenter (const TCellInfo & theCellInfo, const TNodeInfo & theNodeInfo, TGaussCoord & theGaussCoord, const TElemNum & theElemNum = TElemNum(), EModeSwitch theMode = eFULL_INTERLACE)
To calculate Gauss Points coordinates for defined TCellInfo as its bary center.
References MED::TCellInfo::GetConnDim(), MED::TCellInfo::GetConnSlice(), MED::TNodeInfo::GetCoordSlice(), MED::TGaussCoord::GetCoordSliceArr(), MED::TElemInfo::GetMeshInfo(), MED::TElemInfo::GetNbElem(), and MED::TGaussCoord::Init().
GetBaryCenter() [2/3]
bool MED::GetBaryCenter (const TPolyedreInfo & thePolyedreInfo, const TNodeInfo & theNodeInfo, TGaussCoord & theGaussCoord, const TElemNum & theElemNum = TElemNum(), EModeSwitch theMode = eFULL_INTERLACE)
To calculate Gauss Points coordinates for defined TPolyedreInfo as its bary center.
References MED::TPolyedreInfo::GetConnSliceArr(), MED::TNodeInfo::GetCoordSlice(), MED::TGaussCoord::GetCoordSliceArr(), MED::TElemInfo::GetMeshInfo(), MED::TElemInfo::GetNbElem(), MED::TPolyedreInfo::GetNbNodes(), MED::TGaussCoord::Init(), and MED::TCSlice< TValueType >::size().
GetBaryCenter() [3/3]
bool MED::GetBaryCenter (const TPolygoneInfo & thePolygoneInfo, const TNodeInfo & theNodeInfo, TGaussCoord & theGaussCoord, const TElemNum & theElemNum = TElemNum(), EModeSwitch theMode = eFULL_INTERLACE)
To calculate Gauss Points coordinates for defined TPolygoneInfo as its bary center.
References MED::TPolygoneInfo::GetConnSlice(), MED::TNodeInfo::GetCoordSlice(), MED::TGaussCoord::GetCoordSliceArr(), MED::TElemInfo::GetMeshInfo(), MED::TPolygoneInfo::GetNbConn(), MED::TElemInfo::GetNbElem(), and MED::TGaussCoord::Init().
GetCoord()
template<ECoordName TCoordId> TFloat MED::GetCoord (const TCCoordSlice & theCoordSlice)
GetCoord< eNone >()
template<> TFloat MED::GetCoord< eNone > (const TCCoordSlice & theCoordSlice)
GetCoordHelper()
PCoordHelper MED::GetCoordHelper (PNodeInfo theNodeInfo)
References aXGetCoord, aXYGetCoord, aXYZGetCoord, aXZGetCoord, aYGetCoord, aYZGetCoord, aZGetCoord, eX, eY, and eZ.
Referenced by DriverMED_R_SMESHDS_Mesh::Perform().
GetDESCLength()
template<EVersion > TInt MEDWRAPPER_EXPORT MED::GetDESCLength ()
GetDESCLength< eV2_2 >()
template<> TInt MED::GetDESCLength< eV2_2 > ()
GetDimGaussCoord()
TInt MED::GetDimGaussCoord (EGeometrieElement theGeom)
Get dimension of the Gauss coordinates for the defined type of mesh cell.
Referenced by MED::TGaussInfo::GetDim().
GetEntite2TFieldInfo2TimeStampInfoSet()
TEntite2TFieldInfo2TimeStampInfoSet MED::GetEntite2TFieldInfo2TimeStampInfoSet (const TFieldInfo2TimeStampInfoSet & theFieldInfo2TimeStampInfoSet)
Split the input set of MED TIMESTAMPS by corresponding MED FIELDS and MED ENTITIES.
References ConvertEntity().
GetEntity2FamilySet()
TEntity2FamilySet MED::GetEntity2FamilySet (const PWrapper & theWrapper, const TEntity2TGeom2ElemInfo & theEntity2TGeom2ElemInfo, const TFamilyInfoSet & theFamilyInfoSet)
Split set of MED FAMILIES by corresponding MED ENTITY.
GetEntity2GeomSet()
const MED::TEntity2GeomSet & MED::GetEntity2GeomSet ()
Referenced by MED::V2_2::TVWrapper::GetEntityInfo().
GetEntity2TGeom2ElemInfo()
TEntity2TGeom2ElemInfo MED::GetEntity2TGeom2ElemInfo (const PWrapper & theWrapper, const PMeshInfo & theMeshInfo, const MED::TEntityInfo & theEntityInfo)
Get set of TElemInfo by its geometrical type and corresponding MED ENTITY.
References eNOD, eNOEUD, and ePOINT1.
GetEntityByFamilyId()
EEntiteMaillage MED::GetEntityByFamilyId (PGrilleInfo & theInfo, TInt theId)
Get Entity for Grille by family id.
References eMAILLE, and eNOEUD.
GetFamilyID2NbCells()
TFamilyID2NbCells MED::GetFamilyID2NbCells (PGrilleInfo & theInfo)
Get Number of cells for theId family, for Grille.
GetFamilyInfoSet()
TFamilyInfoSet MED::GetFamilyInfoSet (const PWrapper & theWrapper, const PMeshInfo & theMeshInfo)
Read set of MED FAMILIES for defined MED file.
GetFieldInfo2TimeStampInfoSet()
TFieldInfo2TimeStampInfoSet MED::GetFieldInfo2TimeStampInfoSet (const PWrapper & theWrapper, const PMeshInfo & theMeshInfo, const MED::TEntityInfo & theEntityInfo)
Read set of MED TIMESTAMPS groupped by corresponding MED FIELDS.
GetGaussCoord3D()
bool MED::GetGaussCoord3D (const TGaussInfo & theGaussInfo, const TCellInfo & theCellInfo, const TNodeInfo & theNodeInfo, TGaussCoord & theGaussCoord, const TElemNum & theElemNum = TElemNum(), EModeSwitch theMode = eFULL_INTERLACE)
To calculate Gauss Points coordinates.
References eHEXA20, eHEXA8, ePENTA15, ePENTA6, ePYRA13, ePYRA5, eQUAD4, eQUAD8, eQUAD9, eSEG2, eSEG3, eTETRA10, eTETRA4, eTRIA3, eTRIA6, MED::TGaussInfo::GetGaussCoordSlice(), MED::TGaussInfo::GetNbGauss(), MED::TGaussInfo::GetNbRef(), MED::TGaussInfo::GetRefCoordSlice(), MED::TCellInfo::myGeom, and MED::TGaussInfo::myGeom.
GetGroupInfo()
TGroupInfo MED::GetGroupInfo (const TFamilyInfoSet & theFamilyInfoSet)
Split the input set of MED FAMILIES by corresponding MED GROUPS.
GetIDENTLength()
template<EVersion > TInt MEDWRAPPER_EXPORT MED::GetIDENTLength ()
GetIDENTLength< eV2_2 >()
template<> TInt MED::GetIDENTLength< eV2_2 > ()
GetKey2Gauss()
TKey2Gauss MED::GetKey2Gauss (const PWrapper & theWrapper, TErr * theErr = NULL, EModeSwitch theMode = eFULL_INTERLACE)
Read set of MED GAUSS.
GetLNOMLength()
template<EVersion > TInt MEDWRAPPER_EXPORT MED::GetLNOMLength ()
GetLNOMLength< eV2_2 >()
template<> TInt MED::GetLNOMLength< eV2_2 > ()
getMEDVersion()
bool MED::getMEDVersion (const std::string & fname, int & major, int & minor, int & release)
GetMKey2Profile()
TMKey2Profile MED::GetMKey2Profile (const PWrapper & theWrapper, TErr * theErr = NULL, EModeProfil theMode = eCOMPACT)
Read set of MED PROFILES.
GetNbConn()
template<EVersion > MEDWRAPPER_EXPORT TInt MED::GetNbConn (EGeometrieElement typmai, EEntiteMaillage typent, TInt mdim)
Referenced by MED::TPolygoneInfo::GetConnSlice().
GetNbConn< eV2_2 >()
template<> TInt MED::GetNbConn< eV2_2 > (EGeometrieElement typmai, EEntiteMaillage typent, TInt mdim)
GetNbNodes()
TInt MED::GetNbNodes (EGeometrieElement typmai)
Referenced by MED::TCellInfo::GetConnSlice(), MED::TGrilleInfo::GetCoord(), MED::V2_2::TVWrapper::GetEntityInfo(), MED::V2_2::TVWrapper::GetGrilleInfo(), MED::V2_2::TVWrapper::GetNbNodes(), MED::TWrapper::GetPGrilleInfo(), MED::TWrapper::GetPNodeInfo(), DriverMED_W_SMESHDS_Mesh::Perform(), and MED::TTCellInfo< eVersion >::TTCellInfo().
GetNbRefCoord()
TInt MED::GetNbRefCoord (EGeometrieElement theGeom)
Get number of referenced nodes for the defined type of mesh cell.
Referenced by MED::TGaussInfo::GetNbRef().
GetNOMLength()
template<EVersion > TInt MEDWRAPPER_EXPORT MED::GetNOMLength ()
GetNOMLength< eV2_2 >()
template<> TInt MED::GetNOMLength< eV2_2 > ()
Referenced by MED::V2_2::TVWrapper::GetGaussPreInfo(), MED::V2_2::TVWrapper::GetProfilePreInfo(), MED::V2_2::TVWrapper::GetTimeStampValue(), and MED::V2_2::TVWrapper::SetTimeStampValue().
GetPNOMLength()
template<EVersion > TInt MEDWRAPPER_EXPORT MED::GetPNOMLength ()
GetPNOMLength< eV2_2 >()
template<> TInt MED::GetPNOMLength< eV2_2 > ()
GetProfileInfo()
PProfileInfo MED::GetProfileInfo (const PWrapper & theWrapper, const std::string & theProfileName, TErr * theErr = NULL, EModeProfil theMode = eCOMPACT)
Get MED PROFILE by its name.
Referenced by MED::TWrapper::GetPProfileInfo().
GetString()
std::string MED::GetString (TInt theId, TInt theStep, const TString & theString)
Extract a substring from the sequence of the strings.
Referenced by MED::TTFamilyInfo< eVersion >::GetAttrDesc(), MED::TTFieldInfo< eVersion >::GetCompName(), MED::TTNodeInfo< eVersion >::GetCoordName(), MED::TTGrilleInfo< eVersion >::GetCoordName(), MED::TTNodeInfo< eVersion >::GetCoordUnit(), MED::TTGrilleInfo< eVersion >::GetCoordUnit(), MED::TTMeshInfo< eVersion >::GetDesc(), MED::TTElemInfo< eVersion >::GetElemName(), MED::TTFamilyInfo< eVersion >::GetGroupName(), MED::TTNameInfo< eVersion >::GetName(), MED::TTTimeStampInfo< eVersion >::GetUnitDt(), and MED::TTFieldInfo< eVersion >::GetUnitName().
GetVersionId()
EVersion MED::GetVersionId (const std::string & theFileName, bool theDoPreCheckInSeparateProcess = false)
References eV2_1, eV2_2, and eVUnknown.
Referenced by CrWrapper().
GetVersionRelease()
template<EVersion > void MEDWRAPPER_EXPORT MED::GetVersionRelease (TInt & majeur, TInt & mineur, TInt & release)
GetVersionRelease< eV2_2 >()
template<> void MED::GetVersionRelease< eV2_2 > (TInt & majeur, TInt & mineur, TInt & release)
IsEqual()
bool MED::IsEqual (TFloat theLeft, TFloat theRight)
Referenced by MED::TShapeFun::IsSatisfy().
operator<()
bool MED::operator< (const TFamilyTSize & theLeft, const TFamilyTSize & theRight)
Print()
template<class TimeStampValueType > void MED::Print (SharedPtr< TimeStampValueType > theTimeStampValue)
SetString() [1/2]
void MED::SetString (TInt theId, TInt theStep, TString & theString, const std::string & theValue)
Set a substring in the sequence of the strings.
Referenced by MED::TTFamilyInfo< eVersion >::SetAttrDesc(), MED::TTFieldInfo< eVersion >::SetCompName(), MED::TTNodeInfo< eVersion >::SetCoordName(), MED::TTGrilleInfo< eVersion >::SetCoordName(), MED::TTNodeInfo< eVersion >::SetCoordUnit(), MED::TTGrilleInfo< eVersion >::SetCoordUnit(), MED::TTMeshInfo< eVersion >::SetDesc(), MED::TTElemInfo< eVersion >::SetElemName(), MED::TTFamilyInfo< eVersion >::SetGroupName(), MED::TTNameInfo< eVersion >::SetName(), MED::TTTimeStampInfo< eVersion >::SetUnitDt(), and MED::TTFieldInfo< eVersion >::SetUnitName().
SetString() [2/2]
void MED::SetString (TInt theId, TInt theStep, TString & theString, const TString & theValue)
Set a substring in the sequence of the strings.
Variable Documentation
aXGetCoord
TGetCoord MED::aXGetCoord[3]
Initial value:
= {
    &GetCoord<eX>,
    &GetCoord<eNone>,
    &GetCoord<eNone>
  }
Referenced by GetCoordHelper(), and DriverMED_W_SMESHDS_Mesh::Perform().
aXYGetCoord
TGetCoord MED::aXYGetCoord[3]
Initial value:
= {
    &GetCoord<eX>,
    &GetCoord<eY>,
    &GetCoord<eNone>
  }
Referenced by GetCoordHelper(), and DriverMED_W_SMESHDS_Mesh::Perform().
aXYZGetCoord
TGetCoord MED::aXYZGetCoord[3]
Initial value:
= {
    &GetCoord<eX>,
    &GetCoord<eY>,
    &GetCoord<eZ>
  }
Referenced by GetCoordHelper(), and DriverMED_W_SMESHDS_Mesh::Perform().
aXZGetCoord
TGetCoord MED::aXZGetCoord[3]
Initial value:
= {
    &GetCoord<eX>,
    &GetCoord<eNone>,
    &GetCoord<eY>
  }
Referenced by GetCoordHelper(), and DriverMED_W_SMESHDS_Mesh::Perform().
aYGetCoord
TGetCoord MED::aYGetCoord[3]
Initial value:
= {
    &GetCoord<eNone>,
    &GetCoord<eX>,
    &GetCoord<eNone>
  }
Referenced by GetCoordHelper(), and DriverMED_W_SMESHDS_Mesh::Perform().
aYZGetCoord
TGetCoord MED::aYZGetCoord[3]
Initial value:
= {
    &GetCoord<eNone>,
    &GetCoord<eX>,
    &GetCoord<eY>
  }
Referenced by GetCoordHelper(), and DriverMED_W_SMESHDS_Mesh::Perform().
aZGetCoord
TGetCoord MED::aZGetCoord[3]
Initial value:
= {
    &GetCoord<eNone>,
    &GetCoord<eNone>,
    &GetCoord<eX>
  }
Referenced by GetCoordHelper(), and DriverMED_W_SMESHDS_Mesh::Perform().