FreeCAD: Gui::PrefFileChooser Class Reference
Gui::PrefFileChooser Class Reference
The PrefFileChooser class.
#include <PrefWidgets.h>
Public Member Functions
PrefFileChooser (QWidget *parent=0)
virtual ~PrefFileChooser ()
Public Member Functions inherited from Gui::FileChooser
AcceptMode acceptMode () const
Returns the accept mode.
QString buttonText () const
Returns the button's text.
FileChooser (QWidget *parent=0)
Constructs a file chooser called name with the parent parent.
QString fileName () const
Returns the filename.
QString filter () const
Returns the set filter.
Mode mode () const
Returns true if this widgets is set to choose a file, if it is set to choose false is returned.
void setAcceptMode (AcceptMode mode)
Sets the accept mode.
virtual ~FileChooser ()
Public Member Functions inherited from Gui::PrefWidget
QByteArray entryName () const
Returns the widget's preference name.
virtual void OnChange (Base::Subject< const char * > &rCaller, const char *sReason)
This method is called if one or more values in the parameter settings are changed where getParamGrp() points to.
void onRestore ()
Restores the preferences of the widget.
void onSave ()
Saves the current preferences of the widget.
QByteArray paramGrpPath () const
Returns the widget's preferences path.
void setEntryName (const QByteArray &name)
Sets the preference name to name.
void setParamGrpPath (const QByteArray &path)
Sets the preference path to path.
Public Member Functions inherited from Gui::WindowParameter
ParameterGrp::handle getWindowParameter (void)
return the parameter group of this window
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason)
bool setGroupName (const char *name)
Sets the group of the window to name.
WindowParameter (const char *name)
virtual ~WindowParameter ()
Protected Member Functions
void restorePreferences ()
Restores the preferences Must be reimplemented in any subclasses.
void savePreferences ()
Save the preferences Must be reimplemented in any subclasses.
Protected Member Functions inherited from Gui::FileChooser
void resizeEvent (QResizeEvent *)
Protected Member Functions inherited from Gui::PrefWidget
void failedToRestore (const QString &) const
Print warning that restoring failed.
void failedToSave (const QString &) const
Print warning that saving failed.
PrefWidget ()
Constructs a preference widget.
virtual ~PrefWidget ()
Destroys the widget and detaches it from its parameter group.
Properties
QByteArray prefEntry
QByteArray prefPath
Properties inherited from Gui::FileChooser
AcceptMode acceptMode
QString buttonText
QString fileName
This property holds the file name.
QString filter
This property holds the set filter to choose a file.
Mode mode
This property holds whether the widgets selects either a file or a directory.
Additional Inherited Members
Public Types inherited from Gui::FileChooser
enum AcceptMode { AcceptOpen , AcceptSave }
enum Mode { File , Directory }
Public Slots inherited from Gui::FileChooser
virtual void setButtonText (const QString &)
Sets the browse button's text to txt.
virtual void setFileName (const QString &fn)
Sets the file name s.
virtual void setFilter (const QString &)
Sets the filter for choosing a file.
virtual void setMode (Mode m)
If m is File the widget is set to choose a file, otherwise it is set to choose a directory.
Signals inherited from Gui::FileChooser
void fileNameChanged (const QString &)
void fileNameSelected (const QString &)
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter (void)
get the parameters
Detailed Description
The PrefFileChooser class.
Author
Werner Mayer
Constructor & Destructor Documentation
PrefFileChooser()
PrefFileChooser::PrefFileChooser (QWidget * parent = 0)
~PrefFileChooser()
PrefFileChooser::~PrefFileChooser () virtual
Member Function Documentation
restorePreferences()
void PrefFileChooser::restorePreferences () protected virtual
Restores the preferences Must be reimplemented in any subclasses.
Implements Gui::PrefWidget.
References Gui::PrefWidget::entryName(), Gui::PrefWidget::failedToRestore(), Gui::FileChooser::fileName, Gui::WindowParameter::getWindowParameter(), draftgeoutils.general::isNull(), and Gui::FileChooser::setFileName().
savePreferences()
void PrefFileChooser::savePreferences () protected virtual
Save the preferences Must be reimplemented in any subclasses.
Implements Gui::PrefWidget.
References Gui::PrefWidget::entryName(), Gui::PrefWidget::failedToSave(), Gui::FileChooser::fileName, Gui::WindowParameter::getWindowParameter(), draftgeoutils.general::isNull(), and ParameterGrp::SetASCII().
Property Documentation
prefEntry
QByteArray Gui::PrefFileChooser::prefEntry read write
prefPath
QByteArray Gui::PrefFileChooser::prefPath read write
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/PrefWidgets.h
Sources/FreeCAD/src/Gui/PrefWidgets.cpp