FreeCAD: MeshCore::MeshFixMergeFacets Class Reference
MeshCore::MeshFixMergeFacets Class Reference
The MeshFixMergeFacets class removes vertexes which have three adjacent vertexes and is referenced by three facets.
#include <Degeneration.h>
Public Member Functions
bool Fixup ()
Removes deformed facets.
MeshFixMergeFacets (MeshKernel &rclM)
Construction.
~MeshFixMergeFacets ()
Destruction.
Public Member Functions inherited from MeshCore::MeshValidation
virtual bool Fixup ()=0
This function attempts to change the mesh kernel to be valid according to the checked criterion: True is returned if the errors could be fixed, false otherwise.
MeshValidation (MeshKernel &rclB)
virtual ~MeshValidation ()
Detailed Description
The MeshFixMergeFacets class removes vertexes which have three adjacent vertexes and is referenced by three facets.
Usually all the three facets that reference this vertex are not well-formed. If the number of adjacent vertexes is equal to the number of adjacent facets the affected vertex never lies on the boundary and thus it's safe to delete and replace the three facets with a single facet. Effectively this algorithm does the opposite of MeshTopoAlgorithm::InsertVertex
Author
Werner Mayer
Constructor & Destructor Documentation
MeshFixMergeFacets()
MeshCore::MeshFixMergeFacets::MeshFixMergeFacets (MeshKernel & rclM)
Construction.
~MeshFixMergeFacets()
MeshCore::MeshFixMergeFacets::~MeshFixMergeFacets ()
Destruction.
Member Function Documentation
Fixup()
bool MeshFixMergeFacets::Fixup () virtual
Removes deformed facets.
Implements MeshCore::MeshValidation.
References MeshCore::MeshTopoAlgorithm::Cleanup(), and MeshCore::MeshTopoAlgorithm::CollapseVertex().
Referenced by Mesh::MeshObject::mergeFacets().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/Core/Degeneration.h
FreeCAD/src/Mod/Mesh/App/Core/Degeneration.cpp