FreeCAD: TestArch.ArchTest Class Reference
TestArch.ArchTest Class Reference
Public Member Functions
def setUp (self)
def tearDown (self)
def testAdd (self)
def testAxis (self)
def testBuilding (self)
def testEquipment (self)
def testFloor (self)
def testFrame (self)
def testPipe (self)
def testRebar (self)
def testRemove (self)
def testRoof (self)
def testRoof81Permutations (self)
def testRoofAllAngles90 (self)
def testRoofApex (self)
def testRoofSingleEavePoint (self)
def testSection (self)
def testSite (self)
def testSpace (self)
def testSpaceBBox (self)
def testStairs (self)
def testStructure (self)
def testWall (self)
def testWallMultiMatAlign (self)
def testWindow (self)
Member Function Documentation
setUp()
def TestArch.ArchTest.setUp (self)
tearDown()
def TestArch.ArchTest.tearDown (self)
Referenced by PathTests.TestPathHelix.TestPathHelix.test03(), and PathTests.TestPathHelix.TestPathHelix.test04().
testAdd()
def TestArch.ArchTest.testAdd (self)
testAxis()
def TestArch.ArchTest.testAxis (self)
testBuilding()
def TestArch.ArchTest.testBuilding (self)
testEquipment()
def TestArch.ArchTest.testEquipment (self)
testFloor()
def TestArch.ArchTest.testFloor (self)
testFrame()
def TestArch.ArchTest.testFrame (self)
testPipe()
def TestArch.ArchTest.testPipe (self)
testRebar()
def TestArch.ArchTest.testRebar (self)
testRemove()
def TestArch.ArchTest.testRemove (self)
testRoof()
def TestArch.ArchTest.testRoof (self)
testRoof81Permutations()
def TestArch.ArchTest.testRoof81Permutations (self)
Create 81 roofs using a range of arguments.
testRoofAllAngles90()
def TestArch.ArchTest.testRoofAllAngles90 (self)
Create a roof with the angles of all segments set at 90 degrees.
This corner case results in a flat roof.
testRoofApex()
def TestArch.ArchTest.testRoofApex (self)
Create a hipped roof that relies on apex calculation. The roof has
2 triangular segments with a single apex point.
testRoofSingleEavePoint()
def TestArch.ArchTest.testRoofSingleEavePoint (self)
Create a roof with a single triangular segment that has a single
eave point.
testSection()
def TestArch.ArchTest.testSection (self)
testSite()
def TestArch.ArchTest.testSite (self)
testSpace()
def TestArch.ArchTest.testSpace (self)
testSpaceBBox()
def TestArch.ArchTest.testSpaceBBox (self)
References TestArch.checkBB().
testStairs()
def TestArch.ArchTest.testStairs (self)
testStructure()
def TestArch.ArchTest.testStructure (self)
testWall()
def TestArch.ArchTest.testWall (self)
testWallMultiMatAlign()
def TestArch.ArchTest.testWallMultiMatAlign (self)
testWindow()
def TestArch.ArchTest.testWindow (self)
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Arch/TestArch.py