FreeCAD: SMDS_VtkFace Class Reference
SMDS_VtkFace Class Reference
#include <SMDS_VtkFace.hxx>
Public Member Functions
void ChangeApex (SMDS_MeshNode *node)
change only the first node, used for temporary triangles in quadrangle to triangle adaptor
bool ChangeNodes (const SMDS_MeshNode *nodes[], const int nbNodes)
virtual SMDS_ElemIteratorPtr elementsIterator (SMDSAbs_ElementType type) const
virtual SMDSAbs_EntityType GetEntityType () const
virtual SMDSAbs_GeometryType GetGeomType () const
virtual const SMDS_MeshNode * GetNode (const int ind) const
Return node by its index.
virtual int GetNodeIndex (const SMDS_MeshNode *node) const
Check if a node belongs to the element.
virtual vtkIdType GetVtkType () const
void init (const std::vector< vtkIdType > &nodeIds, SMDS_Mesh *mesh)
void initPoly (const std::vector< vtkIdType > &nodeIds, SMDS_Mesh *mesh)
void initQuadPoly (const std::vector< vtkIdType > &nodeIds, SMDS_Mesh *mesh)
virtual SMDS_NodeIteratorPtr interlacedNodesIterator () const
virtual, redefined in vtkEdge, vtkFace and vtkVolume classes
virtual bool IsMediumNode (const SMDS_MeshNode *node) const
virtual bool IsPoly () const
virtual bool IsQuadratic () const
virtual int NbCornerNodes () const
Return number of nodes excluding medium ones.
virtual int NbEdges () const
Return the number of edges owned by or linked with the current element.
virtual int NbFaces () const
Return the number of faces owned by or linked with the current element.
virtual int NbNodes () const
Return The number of nodes owned by the current element.
virtual SMDS_NodeIteratorPtr nodesIteratorToUNV () const
virtual, redefined in vtkEdge, vtkFace and vtkVolume classes
virtual void Print (std::ostream &OS) const
SMDS_VtkFace ()
SMDS_VtkFace (const std::vector< vtkIdType > &nodeIds, SMDS_Mesh *mesh)
~SMDS_VtkFace ()
Public Member Functions inherited from SMDS_MeshFace
SMDSAbs_ElementType GetType () const
Return the type of the current element.
Public Member Functions inherited from SMDS_MeshCell
SMDS_MeshCell ()
virtual bool vtkOrder (const SMDS_MeshNode *[], const int)
virtual ~SMDS_MeshCell ()
Public Member Functions inherited from SMDS_MeshElement
iterator begin_nodes () const
SMDS_ElemIteratorPtr edgesIterator () const
Create an iterator which iterate on edges linked with or owned by the element.
iterator end_nodes () const
SMDS_ElemIteratorPtr facesIterator () const
Create an iterator which iterate on faces linked with or owned by the element.
int GetID () const
int getIdInShape () const
ShortType getMeshId () const
const SMDS_MeshNode * GetNodeWrap (const int ind) const
Return node by its index.
LongType getshapeId () const
int getVtkId () const
virtual SMDS_ElemIteratorPtr interlacedNodesElemIterator () const
virtual bool IsValidIndex (const int ind) const
Return true if index of node is valid (0 <= ind < NbNodes())
virtual SMDS_NodeIteratorPtr nodeIterator () const
SMDS_ElemIteratorPtr nodesIterator () const
Create an iterator which iterate on nodes owned by the element.
int WrappedIndex (const int ind) const
Return a valid node index, fixing the given one if necessary.
Public Member Functions inherited from SMDS_MeshObject
virtual ~SMDS_MeshObject ()
Additional Inherited Members
Public Types inherited from SMDS_MeshElement
typedef SMDS_StdIterator< const SMDS_MeshNode *, SMDS_ElemIteratorPtr > iterator
Static Public Member Functions inherited from SMDS_MeshCell
template<class VECT >
static void applyInterlace (const std::vector< int > &interlace, VECT &data)
template<class VECT >
static void applyInterlaceRev (const std::vector< int > &interlace, VECT &data)
static const std::vector< int > & fromVtkOrder (SMDSAbs_EntityType smdsType)
Return indices to transform cell connectivity from VTK to SMDS Usage: smdsIDs[i] = vtkIDs[ indices[ i ]].
static const std::vector< int > & fromVtkOrder (VTKCellType vtkType)
Return indices to transform cell connectivity from VTK to SMDS Usage: smdsIDs[i] = vtkIDs[ indices[ i ]].
static const std::vector< int > & interlacedSmdsOrder (SMDSAbs_EntityType smdsType, const size_t nbNodes=0)
Return indices to set nodes of a quadratic 1D or 2D element in interlaced order Usage: interlacedIDs[i] = smdsIDs[ indices[ i ]].
static const std::vector< int > & reverseSmdsOrder (SMDSAbs_EntityType smdsType, const size_t nbNodes=0)
Return indices to reverse an SMDS cell of given type. nbNodes is useful for polygons Usage: reverseIDs[i] = forwardIDs[ indices[ i ]].
static SMDSAbs_ElementType toSmdsType (SMDSAbs_EntityType entityType)
Return SMDSAbs_ElementType by SMDSAbs_EntityType.
static SMDSAbs_ElementType toSmdsType (SMDSAbs_GeometryType geomType)
Return SMDSAbs_ElementType by SMDSAbs_GeometryType.
static SMDSAbs_EntityType toSmdsType (VTKCellType vtkType)
Return SMDSAbs_EntityType corresponding to VTKCellType.
static const std::vector< int > & toVtkOrder (SMDSAbs_EntityType smdsType)
Return indices to transform cell connectivity from SMDS to VTK Usage: vtkIDs[i] = smdsIDs[ indices[ i ]].
static const std::vector< int > & toVtkOrder (VTKCellType vtkType)
Return indices to transform cell connectivity from SMDS to VTK Usage: vtkIDs[i] = smdsIDs[ indices[ i ]].
static VTKCellType toVtkType (SMDSAbs_EntityType vtkType)
Return VTKCellType corresponding to SMDSAbs_EntityType.
Static Public Attributes inherited from SMDS_MeshCell
static int nbCells = 0
Protected Member Functions inherited from SMDS_MeshCell
void exchange (const SMDS_MeshNode *nodes[], int a, int b)
Protected Member Functions inherited from SMDS_MeshElement
virtual void init (int id=-1, ShortType meshId=-1, LongType shapeId=0)
void setId (int id)
void setIdInShape (int id)
void setShapeId (LongType shapeId)
void setVtkId (int vtkId)
SMDS_MeshElement (int id, ShortType meshId, LongType shapeId=0)
SMDS_MeshElement (int ID=-1)
Protected Attributes inherited from SMDS_MeshElement
int myID
Element index in vector SMDS_Mesh::myNodes or SMDS_Mesh::myCells.
int myIdInShape
Element index in SMESHDS_SubMesh vector.
ShortType myMeshId
SMDS_Mesh identification in SMESH.
LongType myShapeId
SubShape and SubMesh identification in SMESHDS.
int myVtkID
index in vtkUnstructuredGrid
Constructor & Destructor Documentation
SMDS_VtkFace() [1/2]
SMDS_VtkFace::SMDS_VtkFace ()
SMDS_VtkFace() [2/2]
SMDS_VtkFace::SMDS_VtkFace (const std::vector< vtkIdType > & nodeIds, SMDS_Mesh * mesh)
~SMDS_VtkFace()
SMDS_VtkFace::~SMDS_VtkFace ()
Member Function Documentation
ChangeApex()
void SMDS_VtkFace::ChangeApex (SMDS_MeshNode * node)
change only the first node, used for temporary triangles in quadrangle to triangle adaptor
References SMDS_MeshNode::AddInverseElement(), and SMDS_MeshElement::getVtkId().
ChangeNodes()
bool SMDS_VtkFace::ChangeNodes (const SMDS_MeshNode * nodes[], const int nbNodes) virtual
Implements SMDS_MeshCell.
References SMDS_MeshElement::getVtkId().
elementsIterator()
SMDS_ElemIteratorPtr SMDS_VtkFace::elementsIterator (SMDSAbs_ElementType type) const virtual
Reimplemented from SMDS_MeshElement.
GetEntityType()
SMDSAbs_EntityType SMDS_VtkFace::GetEntityType () const virtual
Implements SMDS_MeshElement.
References SMDS_MeshCell::toSmdsType().
GetGeomType()
SMDSAbs_GeometryType SMDS_VtkFace::GetGeomType () const virtual
Implements SMDS_MeshElement.
GetNode()
const SMDS_MeshNode * SMDS_VtkFace::GetNode (const int ind) const virtual
Return node by its index.
Parameters
ind - node index
Return values
const SMDS_MeshNode* - the node
Reimplemented from SMDS_MeshElement.
GetNodeIndex()
int SMDS_VtkFace::GetNodeIndex (const SMDS_MeshNode * node) const virtual
Check if a node belongs to the element.
Parameters
node - the node to check
Return values
int - node index within the element, -1 if not found
Reimplemented from SMDS_MeshElement.
References SMDS_MeshElement::getVtkId().
GetVtkType()
vtkIdType SMDS_VtkFace::GetVtkType () const virtual
Reimplemented from SMDS_MeshFace.
Referenced by SMDS_Mesh::AddFaceFromVtkIdsWithID().
init()
void SMDS_VtkFace::init (const std::vector< vtkIdType > & nodeIds, SMDS_Mesh * mesh)
References SMDS_MeshElement::init().
Referenced by SMDS_Mesh::AddFaceFromVtkIdsWithID(), SMDS_Mesh::AddFaceWithID(), SMDS_Mesh::createQuadrangle(), SMDS_Mesh::createTriangle(), and DocumentObject.DocumentObject::onChanged().
initPoly()
void SMDS_VtkFace::initPoly (const std::vector< vtkIdType > & nodeIds, SMDS_Mesh * mesh)
References SMDS_MeshElement::init().
Referenced by SMDS_Mesh::AddPolygonalFaceWithID().
initQuadPoly()
void SMDS_VtkFace::initQuadPoly (const std::vector< vtkIdType > & nodeIds, SMDS_Mesh * mesh)
References SMDS_MeshElement::init().
Referenced by SMDS_Mesh::AddQuadPolygonalFaceWithID().
interlacedNodesIterator()
SMDS_NodeIteratorPtr SMDS_VtkFace::interlacedNodesIterator () const virtual
virtual, redefined in vtkEdge, vtkFace and vtkVolume classes
Reimplemented from SMDS_MeshElement.
IsMediumNode()
bool SMDS_VtkFace::IsMediumNode (const SMDS_MeshNode * node) const virtual
Reimplemented from SMDS_MeshElement.
References SMDS_MeshElement::getVtkId().
IsPoly()
bool SMDS_VtkFace::IsPoly () const virtual
Reimplemented from SMDS_MeshElement.
IsQuadratic()
bool SMDS_VtkFace::IsQuadratic () const virtual
Reimplemented from SMDS_MeshElement.
NbCornerNodes()
int SMDS_VtkFace::NbCornerNodes () const virtual
Return number of nodes excluding medium ones.
Reimplemented from SMDS_MeshElement.
NbEdges()
int SMDS_VtkFace::NbEdges () const virtual
Return the number of edges owned by or linked with the current element.
Reimplemented from SMDS_MeshElement.
NbFaces()
int SMDS_VtkFace::NbFaces () const virtual
Return the number of faces owned by or linked with the current element.
Reimplemented from SMDS_MeshElement.
NbNodes()
int SMDS_VtkFace::NbNodes () const virtual
Return The number of nodes owned by the current element.
Reimplemented from SMDS_MeshElement.
nodesIteratorToUNV()
SMDS_NodeIteratorPtr SMDS_VtkFace::nodesIteratorToUNV () const virtual
virtual, redefined in vtkEdge, vtkFace and vtkVolume classes
Reimplemented from SMDS_MeshElement.
Print()
void SMDS_VtkFace::Print (std::ostream & OS) const virtual
Reimplemented from SMDS_MeshElement.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_VtkFace.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_VtkFace.cpp