FreeCAD: Base::CoordinateSystemPy Class Reference
Base::CoordinateSystemPy Class Reference
The python export class for CoordinateSystem.
#include <CoordinateSystemPy.h>
Public Types
typedef CoordinateSystem * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
CoordinateSystemPy (CoordinateSystem *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of CoordinateSystemPy.
static PyMethodDef Methods []
Methods structure of CoordinateSystemPy.
static PyTypeObject Type
Type structure of CoordinateSystemPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~CoordinateSystemPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * setAxes (PyObject *args)
implementer for the setAxes() method
PyObject * displacement (PyObject *args)
implementer for the displacement() method
PyObject * transformTo (PyObject *args)
implementer for the transformTo() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * setPlacement (PyObject *args)
implementer for the setPlacement() method
static PyObject * staticCallback_setAxes (PyObject *self, PyObject *args)
callback for the setAxes() method
static PyObject * staticCallback_displacement (PyObject *self, PyObject *args)
callback for the displacement() method
static PyObject * staticCallback_transformTo (PyObject *self, PyObject *args)
callback for the transformTo() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_setPlacement (PyObject *self, PyObject *args)
callback for the setPlacement() method
callbacks and implementers for the python object attributes
Py::Object getAxis (void) const
getter for the Axis attribute
void setAxis (Py::Object arg)
setter for the Axis attribute
Py::Object getXDirection (void) const
getter for the XDirection attribute
void setXDirection (Py::Object arg)
setter for the XDirection attribute
Py::Object getYDirection (void) const
getter for the YDirection attribute
void setYDirection (Py::Object arg)
setter for the YDirection attribute
Py::Object getZDirection (void) const
getter for the ZDirection attribute
void setZDirection (Py::Object arg)
setter for the ZDirection attribute
Py::Object getPosition (void) const
getter for the Position attribute
void setPosition (Py::Object arg)
setter for the Position attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
CoordinateSystem * getCoordinateSystemPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getAxis (PyObject *self, void *closure)
getter callback for the Axis attribute
static int staticCallback_setAxis (PyObject *self, PyObject *value, void *closure)
setter callback for the Axis attribute
static PyObject * staticCallback_getXDirection (PyObject *self, void *closure)
getter callback for the XDirection attribute
static int staticCallback_setXDirection (PyObject *self, PyObject *value, void *closure)
setter callback for the XDirection attribute
static PyObject * staticCallback_getYDirection (PyObject *self, void *closure)
getter callback for the YDirection attribute
static int staticCallback_setYDirection (PyObject *self, PyObject *value, void *closure)
setter callback for the YDirection attribute
static PyObject * staticCallback_getZDirection (PyObject *self, void *closure)
getter callback for the ZDirection attribute
static int staticCallback_setZDirection (PyObject *self, PyObject *value, void *closure)
setter callback for the ZDirection attribute
static PyObject * staticCallback_getPosition (PyObject *self, void *closure)
getter callback for the Position attribute
static int staticCallback_setPosition (PyObject *self, PyObject *value, void *closure)
setter callback for the Position attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for CoordinateSystem.
Member Typedef Documentation
PointerType
typedef CoordinateSystem* Base::CoordinateSystemPy::PointerType
Constructor & Destructor Documentation
~CoordinateSystemPy()
CoordinateSystemPy::~CoordinateSystemPy () protected
CoordinateSystemPy()
CoordinateSystemPy::CoordinateSystemPy (CoordinateSystem * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
displacement()
PyObject * CoordinateSystemPy::displacement (PyObject * args)
implementer for the displacement() method
References Base::CoordinateSystem::displacement(), getCoordinateSystemPtr(), and Type.
Referenced by staticCallback_displacement().
getAxis()
Py::Object CoordinateSystemPy::getAxis (void) const
getter for the Axis attribute
References Base::CoordinateSystem::getAxis(), and getCoordinateSystemPtr().
Referenced by staticCallback_getAxis().
getCoordinateSystemPtr()
CoordinateSystem * CoordinateSystemPy::getCoordinateSystemPtr (void) const
getter for the object handled by this class
Referenced by displacement(), getAxis(), getPosition(), getXDirection(), getYDirection(), getZDirection(), setAxes(), setAxis(), setPlacement(), setPosition(), setXDirection(), setYDirection(), setZDirection(), transform(), and transformTo().
getCustomAttributes()
PyObject * CoordinateSystemPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getPosition()
Py::Object CoordinateSystemPy::getPosition (void) const
getter for the Position attribute
References getCoordinateSystemPtr().
Referenced by staticCallback_getPosition().
GetType()
virtual PyTypeObject* Base::CoordinateSystemPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
getXDirection()
Py::Object CoordinateSystemPy::getXDirection (void) const
getter for the XDirection attribute
References getCoordinateSystemPtr().
Referenced by staticCallback_getXDirection().
getYDirection()
Py::Object CoordinateSystemPy::getYDirection (void) const
getter for the YDirection attribute
References getCoordinateSystemPtr().
Referenced by staticCallback_getYDirection().
getZDirection()
Py::Object CoordinateSystemPy::getZDirection (void) const
getter for the ZDirection attribute
References getCoordinateSystemPtr().
Referenced by staticCallback_getZDirection().
PyInit()
int CoordinateSystemPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
PyMake()
PyObject * CoordinateSystemPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References CoordinateSystemPy().
representation()
std::string CoordinateSystemPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setAxes()
PyObject * CoordinateSystemPy::setAxes (PyObject * args)
implementer for the setAxes() method
References getCoordinateSystemPtr(), Base::CoordinateSystem::setAxes(), Base::AxisPy::Type, and Base::VectorPy::Type.
Referenced by staticCallback_setAxes().
setAxis()
void CoordinateSystemPy::setAxis (Py::Object arg)
setter for the Axis attribute
References Base::AxisPy::getAxisPtr(), getCoordinateSystemPtr(), Base::CoordinateSystem::setAxis(), and Base::AxisPy::Type.
Referenced by staticCallback_setAxis().
setCustomAttributes()
int CoordinateSystemPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setPlacement()
PyObject * CoordinateSystemPy::setPlacement (PyObject * args)
implementer for the setPlacement() method
References getCoordinateSystemPtr(), Base::CoordinateSystem::setPlacement(), and Base::PlacementPy::Type.
Referenced by staticCallback_setPlacement().
setPosition()
void CoordinateSystemPy::setPosition (Py::Object arg)
setter for the Position attribute
References getCoordinateSystemPtr(), Base::CoordinateSystem::setPosition(), and Base::toVector().
Referenced by staticCallback_setPosition().
setXDirection()
void CoordinateSystemPy::setXDirection (Py::Object arg)
setter for the XDirection attribute
References getCoordinateSystemPtr(), Base::CoordinateSystem::setXDirection(), and Base::toVector().
Referenced by staticCallback_setXDirection().
setYDirection()
void CoordinateSystemPy::setYDirection (Py::Object arg)
setter for the YDirection attribute
References getCoordinateSystemPtr(), Base::CoordinateSystem::setYDirection(), and Base::toVector().
Referenced by staticCallback_setYDirection().
setZDirection()
void CoordinateSystemPy::setZDirection (Py::Object arg)
setter for the ZDirection attribute
References getCoordinateSystemPtr(), Base::CoordinateSystem::setZDirection(), and Base::toVector().
Referenced by staticCallback_setZDirection().
staticCallback_displacement()
PyObject * CoordinateSystemPy::staticCallback_displacement (PyObject * self, PyObject * args) static
callback for the displacement() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, displacement(), and Base::PyObjectBase::isValid().
staticCallback_getAxis()
PyObject * CoordinateSystemPy::staticCallback_getAxis (PyObject * self, void * closure) static
getter callback for the Axis attribute
References Base::BaseExceptionFreeCADError, getAxis(), and Base::PyObjectBase::isValid().
staticCallback_getPosition()
PyObject * CoordinateSystemPy::staticCallback_getPosition (PyObject * self, void * closure) static
getter callback for the Position attribute
References Base::BaseExceptionFreeCADError, getPosition(), and Base::PyObjectBase::isValid().
staticCallback_getXDirection()
PyObject * CoordinateSystemPy::staticCallback_getXDirection (PyObject * self, void * closure) static
getter callback for the XDirection attribute
References Base::BaseExceptionFreeCADError, getXDirection(), and Base::PyObjectBase::isValid().
staticCallback_getYDirection()
PyObject * CoordinateSystemPy::staticCallback_getYDirection (PyObject * self, void * closure) static
getter callback for the YDirection attribute
References Base::BaseExceptionFreeCADError, getYDirection(), and Base::PyObjectBase::isValid().
staticCallback_getZDirection()
PyObject * CoordinateSystemPy::staticCallback_getZDirection (PyObject * self, void * closure) static
getter callback for the ZDirection attribute
References Base::BaseExceptionFreeCADError, getZDirection(), and Base::PyObjectBase::isValid().
staticCallback_setAxes()
PyObject * CoordinateSystemPy::staticCallback_setAxes (PyObject * self, PyObject * args) static
callback for the setAxes() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), setAxes(), and Base::PyObjectBase::startNotify().
staticCallback_setAxis()
int CoordinateSystemPy::staticCallback_setAxis (PyObject * self, PyObject * value, void * closure) static
setter callback for the Axis attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setAxis().
staticCallback_setPlacement()
PyObject * CoordinateSystemPy::staticCallback_setPlacement (PyObject * self, PyObject * args) static
callback for the setPlacement() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), setPlacement(), and Base::PyObjectBase::startNotify().
staticCallback_setPosition()
int CoordinateSystemPy::staticCallback_setPosition (PyObject * self, PyObject * value, void * closure) static
setter callback for the Position attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setPosition().
staticCallback_setXDirection()
int CoordinateSystemPy::staticCallback_setXDirection (PyObject * self, PyObject * value, void * closure) static
setter callback for the XDirection attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setXDirection().
staticCallback_setYDirection()
int CoordinateSystemPy::staticCallback_setYDirection (PyObject * self, PyObject * value, void * closure) static
setter callback for the YDirection attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setYDirection().
staticCallback_setZDirection()
int CoordinateSystemPy::staticCallback_setZDirection (PyObject * self, PyObject * value, void * closure) static
setter callback for the ZDirection attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setZDirection().
staticCallback_transform()
PyObject * CoordinateSystemPy::staticCallback_transform (PyObject * self, PyObject * args) static
callback for the transform() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::startNotify(), and transform().
staticCallback_transformTo()
PyObject * CoordinateSystemPy::staticCallback_transformTo (PyObject * self, PyObject * args) static
callback for the transformTo() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::startNotify(), and transformTo().
transform()
PyObject * CoordinateSystemPy::transform (PyObject * args)
implementer for the transform() method
References getCoordinateSystemPtr(), Base::CoordinateSystem::transform(), Base::PlacementPy::Type, and Base::RotationPy::Type.
Referenced by staticCallback_transform().
transformTo()
PyObject * CoordinateSystemPy::transformTo (PyObject * args)
implementer for the transformTo() method
References getCoordinateSystemPtr(), Base::CoordinateSystem::transformTo(), Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_transformTo().
Member Data Documentation
GetterSetter
PyGetSetDef CoordinateSystemPy::GetterSetter static
Attribute structure of CoordinateSystemPy.
Methods
PyMethodDef CoordinateSystemPy::Methods static
Initial value:
= {
    {"setAxes",
        reinterpret_cast<PyCFunction>( staticCallback_setAxes ),
        METH_VARARGS,
        "setAxes(Axis or Vector z, Vector x)\nSet axis or z direction and x direction"
    },
    {"displacement",
        reinterpret_cast<PyCFunction>( staticCallback_displacement ),
        METH_VARARGS,
        "displacement(CoordinateSystem)\nComputes the placement from this to the passed coordinate system"
    },
    {"transformTo",
        reinterpret_cast<PyCFunction>( staticCallback_transformTo ),
        METH_VARARGS,
        "transformTo(Vector)\nComputes the coordinates of the point in coordinates of this system\n        "
    },
    {"transform",
        reinterpret_cast<PyCFunction>( staticCallback_transform ),
        METH_VARARGS,
        "transform(Rotation or Placement)\nApplies the rotation or placement on this coordinate system\n        "
    },
    {"setPlacement",
        reinterpret_cast<PyCFunction>( staticCallback_setPlacement ),
        METH_VARARGS,
        "setPlacment(Placement)\nSet placement to the coordinate system.\n        "
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of CoordinateSystemPy.
Type
PyTypeObject CoordinateSystemPy::Type static
Type structure of CoordinateSystemPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), displacement(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Base/CoordinateSystemPy.h
Sources/FreeCAD/src/Base/CoordinateSystemPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Base/CoordinateSystemPy.cpp