FreeCAD: Part::OffsetCurvePy Class Reference
Part::OffsetCurvePy Class Reference
The python export class for GeomOffsetCurve.
#include <OffsetCurvePy.h>
Public Types
typedef GeomOffsetCurve * PointerType
Public Types inherited from Part::GeometryCurvePy
typedef GeomCurve * PointerType
Public Types inherited from Part::GeometryPy
typedef Geometry * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
OffsetCurvePy (GeomOffsetCurve *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Part::GeometryCurvePy
GeometryCurvePy (GeomCurve *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * toShape (PyObject *args)
implementer for the toShape() method
PyObject * discretize (PyObject *args, PyObject *kwd)
implementer for the discretize() method
PyObject * getD0 (PyObject *args)
implementer for the getD0() method
PyObject * getD1 (PyObject *args)
implementer for the getD1() method
PyObject * getD2 (PyObject *args)
implementer for the getD2() method
PyObject * getD3 (PyObject *args)
implementer for the getD3() method
PyObject * getDN (PyObject *args)
implementer for the getDN() method
PyObject * length (PyObject *args)
implementer for the length() method
PyObject * parameterAtDistance (PyObject *args)
implementer for the parameterAtDistance() method
PyObject * value (PyObject *args)
implementer for the value() method
PyObject * tangent (PyObject *args)
implementer for the tangent() method
PyObject * makeRuledSurface (PyObject *args)
implementer for the makeRuledSurface() method
PyObject * intersect2d (PyObject *args)
implementer for the intersect2d() method
PyObject * continuityWith (PyObject *args)
implementer for the continuityWith() method
PyObject * parameter (PyObject *args)
implementer for the parameter() method
PyObject * normal (PyObject *args)
implementer for the normal() method
PyObject * curvature (PyObject *args)
implementer for the curvature() method
PyObject * centerOfCurvature (PyObject *args)
implementer for the centerOfCurvature() method
PyObject * intersect (PyObject *args)
implementer for the intersect() method
PyObject * intersectCS (PyObject *args)
implementer for the intersectCS() method
PyObject * intersectCC (PyObject *args)
implementer for the intersectCC() method
PyObject * toBSpline (PyObject *args)
implementer for the toBSpline() method
PyObject * toNurbs (PyObject *args)
implementer for the toNurbs() method
PyObject * trim (PyObject *args)
implementer for the trim() method
PyObject * approximateBSpline (PyObject *args)
implementer for the approximateBSpline() method
PyObject * reverse (PyObject *args)
implementer for the reverse() method
PyObject * reversedParameter (PyObject *args)
implementer for the reversedParameter() method
PyObject * isPeriodic (PyObject *args)
implementer for the isPeriodic() method
PyObject * period (PyObject *args)
implementer for the period() method
PyObject * isClosed (PyObject *args)
implementer for the isClosed() method
Py::String getContinuity (void) const
getter for the Continuity attribute
Py::Float getFirstParameter (void) const
getter for the FirstParameter attribute
Py::Float getLastParameter (void) const
getter for the LastParameter attribute
Py::Object getRotation (void) const
getter for the Rotation attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomCurve * getGeomCurvePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Part::GeometryPy
GeometryPy (Geometry *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * clone (PyObject *args)
implementer for the clone() method
PyObject * hasExtensionOfType (PyObject *args)
implementer for the hasExtensionOfType() method
PyObject * hasExtensionOfName (PyObject *args)
implementer for the hasExtensionOfName() method
PyObject * getExtensionOfType (PyObject *args)
implementer for the getExtensionOfType() method
PyObject * getExtensionOfName (PyObject *args)
implementer for the getExtensionOfName() method
PyObject * setExtension (PyObject *args)
implementer for the setExtension() method
PyObject * deleteExtensionOfType (PyObject *args)
implementer for the deleteExtensionOfType() method
PyObject * deleteExtensionOfName (PyObject *args)
implementer for the deleteExtensionOfName() method
PyObject * getExtensions (PyObject *args)
implementer for the getExtensions() method
Py::String getTag (void) const
getter for the Tag attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geometry * getGeometryPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::GeometryCurvePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_toShape (PyObject *self, PyObject *args)
callback for the toShape() method
static PyObject * staticCallback_discretize (PyObject *self, PyObject *args, PyObject *kwd)
callback for the discretize() method
static PyObject * staticCallback_getD0 (PyObject *self, PyObject *args)
callback for the getD0() method
static PyObject * staticCallback_getD1 (PyObject *self, PyObject *args)
callback for the getD1() method
static PyObject * staticCallback_getD2 (PyObject *self, PyObject *args)
callback for the getD2() method
static PyObject * staticCallback_getD3 (PyObject *self, PyObject *args)
callback for the getD3() method
static PyObject * staticCallback_getDN (PyObject *self, PyObject *args)
callback for the getDN() method
static PyObject * staticCallback_length (PyObject *self, PyObject *args)
callback for the length() method
static PyObject * staticCallback_parameterAtDistance (PyObject *self, PyObject *args)
callback for the parameterAtDistance() method
static PyObject * staticCallback_value (PyObject *self, PyObject *args)
callback for the value() method
static PyObject * staticCallback_tangent (PyObject *self, PyObject *args)
callback for the tangent() method
static PyObject * staticCallback_makeRuledSurface (PyObject *self, PyObject *args)
callback for the makeRuledSurface() method
static PyObject * staticCallback_intersect2d (PyObject *self, PyObject *args)
callback for the intersect2d() method
static PyObject * staticCallback_continuityWith (PyObject *self, PyObject *args)
callback for the continuityWith() method
static PyObject * staticCallback_parameter (PyObject *self, PyObject *args)
callback for the parameter() method
static PyObject * staticCallback_normal (PyObject *self, PyObject *args)
callback for the normal() method
static PyObject * staticCallback_curvature (PyObject *self, PyObject *args)
callback for the curvature() method
static PyObject * staticCallback_centerOfCurvature (PyObject *self, PyObject *args)
callback for the centerOfCurvature() method
static PyObject * staticCallback_intersect (PyObject *self, PyObject *args)
callback for the intersect() method
static PyObject * staticCallback_intersectCS (PyObject *self, PyObject *args)
callback for the intersectCS() method
static PyObject * staticCallback_intersectCC (PyObject *self, PyObject *args)
callback for the intersectCC() method
static PyObject * staticCallback_toBSpline (PyObject *self, PyObject *args)
callback for the toBSpline() method
static PyObject * staticCallback_toNurbs (PyObject *self, PyObject *args)
callback for the toNurbs() method
static PyObject * staticCallback_trim (PyObject *self, PyObject *args)
callback for the trim() method
static PyObject * staticCallback_approximateBSpline (PyObject *self, PyObject *args)
callback for the approximateBSpline() method
static PyObject * staticCallback_reverse (PyObject *self, PyObject *args)
callback for the reverse() method
static PyObject * staticCallback_reversedParameter (PyObject *self, PyObject *args)
callback for the reversedParameter() method
static PyObject * staticCallback_isPeriodic (PyObject *self, PyObject *args)
callback for the isPeriodic() method
static PyObject * staticCallback_period (PyObject *self, PyObject *args)
callback for the period() method
static PyObject * staticCallback_isClosed (PyObject *self, PyObject *args)
callback for the isClosed() method
static PyObject * staticCallback_getContinuity (PyObject *self, void *closure)
getter callback for the Continuity attribute
static int staticCallback_setContinuity (PyObject *self, PyObject *value, void *closure)
setter callback for the Continuity attribute
static PyObject * staticCallback_getFirstParameter (PyObject *self, void *closure)
getter callback for the FirstParameter attribute
static int staticCallback_setFirstParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the FirstParameter attribute
static PyObject * staticCallback_getLastParameter (PyObject *self, void *closure)
getter callback for the LastParameter attribute
static int staticCallback_setLastParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the LastParameter attribute
static PyObject * staticCallback_getRotation (PyObject *self, void *closure)
getter callback for the Rotation attribute
static int staticCallback_setRotation (PyObject *self, PyObject *value, void *closure)
setter callback for the Rotation attribute
Static Public Member Functions inherited from Part::GeometryPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_clone (PyObject *self, PyObject *args)
callback for the clone() method
static PyObject * staticCallback_hasExtensionOfType (PyObject *self, PyObject *args)
callback for the hasExtensionOfType() method
static PyObject * staticCallback_hasExtensionOfName (PyObject *self, PyObject *args)
callback for the hasExtensionOfName() method
static PyObject * staticCallback_getExtensionOfType (PyObject *self, PyObject *args)
callback for the getExtensionOfType() method
static PyObject * staticCallback_getExtensionOfName (PyObject *self, PyObject *args)
callback for the getExtensionOfName() method
static PyObject * staticCallback_setExtension (PyObject *self, PyObject *args)
callback for the setExtension() method
static PyObject * staticCallback_deleteExtensionOfType (PyObject *self, PyObject *args)
callback for the deleteExtensionOfType() method
static PyObject * staticCallback_deleteExtensionOfName (PyObject *self, PyObject *args)
callback for the deleteExtensionOfName() method
static PyObject * staticCallback_getExtensions (PyObject *self, PyObject *args)
callback for the getExtensions() method
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of OffsetCurvePy.
static PyMethodDef Methods []
Methods structure of OffsetCurvePy.
static PyTypeObject Type
Type structure of OffsetCurvePy.
Static Public Attributes inherited from Part::GeometryCurvePy
static PyGetSetDef GetterSetter []
Attribute structure of GeometryCurvePy.
static PyMethodDef Methods []
Methods structure of GeometryCurvePy.
static PyTypeObject Type
Type structure of GeometryCurvePy.
Static Public Attributes inherited from Part::GeometryPy
static PyGetSetDef GetterSetter []
Attribute structure of GeometryPy.
static PyMethodDef Methods []
Methods structure of GeometryPy.
static PyTypeObject Type
Type structure of GeometryPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~OffsetCurvePy ()
Protected Member Functions inherited from Part::GeometryCurvePy
~GeometryCurvePy ()
Protected Member Functions inherited from Part::GeometryPy
~GeometryPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object attributes
Py::Float getOffsetValue (void) const
getter for the OffsetValue attribute
void setOffsetValue (Py::Float arg)
setter for the OffsetValue attribute
Py::Object getOffsetDirection (void) const
getter for the OffsetDirection attribute
void setOffsetDirection (Py::Object arg)
setter for the OffsetDirection attribute
Py::Object getBasisCurve (void) const
getter for the BasisCurve attribute
void setBasisCurve (Py::Object arg)
setter for the BasisCurve attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomOffsetCurve * getGeomOffsetCurvePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getOffsetValue (PyObject *self, void *closure)
getter callback for the OffsetValue attribute
static int staticCallback_setOffsetValue (PyObject *self, PyObject *value, void *closure)
setter callback for the OffsetValue attribute
static PyObject * staticCallback_getOffsetDirection (PyObject *self, void *closure)
getter callback for the OffsetDirection attribute
static int staticCallback_setOffsetDirection (PyObject *self, PyObject *value, void *closure)
setter callback for the OffsetDirection attribute
static PyObject * staticCallback_getBasisCurve (PyObject *self, void *closure)
getter callback for the BasisCurve attribute
static int staticCallback_setBasisCurve (PyObject *self, PyObject *value, void *closure)
setter callback for the BasisCurve attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeomOffsetCurve.
Member Typedef Documentation
PointerType
typedef GeomOffsetCurve* Part::OffsetCurvePy::PointerType
Constructor & Destructor Documentation
~OffsetCurvePy()
OffsetCurvePy::~OffsetCurvePy () protected
OffsetCurvePy()
OffsetCurvePy::OffsetCurvePy (GeomOffsetCurve * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getBasisCurve()
Py::Object OffsetCurvePy::getBasisCurve (void) const
getter for the BasisCurve attribute
References Part::GeometryPy::getGeometryPtr(), Base::BaseClass::getPyObject(), and Part::makeFromCurve().
Referenced by staticCallback_getBasisCurve().
getCustomAttributes()
PyObject * OffsetCurvePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getGeomOffsetCurvePtr()
GeomOffsetCurve * OffsetCurvePy::getGeomOffsetCurvePtr (void) const
getter for the object handled by this class
Referenced by PyInit().
getOffsetDirection()
Py::Object OffsetCurvePy::getOffsetDirection (void) const
getter for the OffsetDirection attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getOffsetDirection().
getOffsetValue()
Py::Float OffsetCurvePy::getOffsetValue (void) const
getter for the OffsetValue attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getOffsetValue().
GetType()
virtual PyTypeObject* Part::OffsetCurvePy::GetType (void) virtual
Reimplemented from Part::GeometryCurvePy.
PyInit()
int OffsetCurvePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::GeometryCurvePy.
References Part::GeometryPy::getGeometryPtr(), getGeomOffsetCurvePtr(), draftfunctions.offset::offset(), Part::PartExceptionOCCError, Part::GeomOffsetCurve::setHandle(), Base::VectorPy::Type, Part::GeometryPy::Type, Part::GeometryCurvePy::value(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
PyMake()
PyObject * OffsetCurvePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References OffsetCurvePy().
representation()
std::string OffsetCurvePy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setBasisCurve()
void OffsetCurvePy::setBasisCurve (Py::Object arg)
setter for the BasisCurve attribute
References Part::GeometryPy::getGeometryPtr(), and Part::GeometryPy::Type.
Referenced by staticCallback_setBasisCurve().
setCustomAttributes()
int OffsetCurvePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setOffsetDirection()
void OffsetCurvePy::setOffsetDirection (Py::Object arg)
setter for the OffsetDirection attribute
References Part::GeometryPy::getGeometryPtr(), Base::VectorPy::Type, Part::GeometryCurvePy::value(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by staticCallback_setOffsetDirection().
setOffsetValue()
void OffsetCurvePy::setOffsetValue (Py::Float arg)
setter for the OffsetValue attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_setOffsetValue().
staticCallback_getBasisCurve()
PyObject * OffsetCurvePy::staticCallback_getBasisCurve (PyObject * self, void * closure) static
getter callback for the BasisCurve attribute
References Base::BaseExceptionFreeCADError, getBasisCurve(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getOffsetDirection()
PyObject * OffsetCurvePy::staticCallback_getOffsetDirection (PyObject * self, void * closure) static
getter callback for the OffsetDirection attribute
References Base::BaseExceptionFreeCADError, getOffsetDirection(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getOffsetValue()
PyObject * OffsetCurvePy::staticCallback_getOffsetValue (PyObject * self, void * closure) static
getter callback for the OffsetValue attribute
References Base::BaseExceptionFreeCADError, getOffsetValue(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setBasisCurve()
int OffsetCurvePy::staticCallback_setBasisCurve (PyObject * self, PyObject * value, void * closure) static
setter callback for the BasisCurve attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setBasisCurve().
staticCallback_setOffsetDirection()
int OffsetCurvePy::staticCallback_setOffsetDirection (PyObject * self, PyObject * value, void * closure) static
setter callback for the OffsetDirection attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setOffsetDirection().
staticCallback_setOffsetValue()
int OffsetCurvePy::staticCallback_setOffsetValue (PyObject * self, PyObject * value, void * closure) static
setter callback for the OffsetValue attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setOffsetValue().
Member Data Documentation
GetterSetter
PyGetSetDef OffsetCurvePy::GetterSetter static
Initial value:
= {
    {"OffsetValue",
        (getter) staticCallback_getOffsetValue,
        (setter) staticCallback_setOffsetValue,
        "\n                                     Sets or gets the offset value to offset the underlying curve.\n                         ",
        NULL
    },
    {"OffsetDirection",
        (getter) staticCallback_getOffsetDirection,
        (setter) staticCallback_setOffsetDirection,
        "\n                                     Sets or gets the offset direction to offset the underlying curve.\n                             ",
        NULL
    },
    {"BasisCurve",
        (getter) staticCallback_getBasisCurve,
        (setter) staticCallback_setBasisCurve,
        "\n                                     Sets or gets the basic curve.\n                         ",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of OffsetCurvePy.
Methods
PyMethodDef OffsetCurvePy::Methods static
Initial value:
= {
    {NULL, NULL, 0, NULL}
}
Methods structure of OffsetCurvePy.
Type
PyTypeObject OffsetCurvePy::Type static
Type structure of OffsetCurvePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/OffsetCurvePy.h
Sources/FreeCAD/src/Mod/Part/App/OffsetCurvePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/OffsetCurvePy.cpp