FreeCAD: StdMeshers::FunctionExpr Class Reference
StdMeshers::FunctionExpr Class Reference
#include <StdMeshers_Distribution.hxx>
Public Member Functions
FunctionExpr (const char *, const int)
virtual double integral (const double, const double) const
virtual bool value (const double, double &) const
virtual Standard_Boolean Value (const Standard_Real, Standard_Real &)
virtual ~FunctionExpr ()
Public Member Functions inherited from StdMeshers::Function
Function (const int)
virtual ~Function ()
Constructor & Destructor Documentation
FunctionExpr()
StdMeshers::FunctionExpr::FunctionExpr (const char * str, const int conv)
~FunctionExpr()
StdMeshers::FunctionExpr::~FunctionExpr () virtual
Member Function Documentation
integral()
double StdMeshers::FunctionExpr::integral (const double a, const double b) const virtual
Implements StdMeshers::Function.
value()
bool StdMeshers::FunctionExpr::value (const double t, double & f) const virtual
Reimplemented from StdMeshers::Function.
References StdMeshers::Function::value().
Referenced by StdMeshers_CartesianParameters3D::ComputeCoordinates(), PathScripts.PathProperty.Property::displayString(), PathScripts.PathProperty.PropertyQuantity::displayString(), PathScripts.PathSetupSheetOpPrototype.Property::displayString(), PathScripts.PathSetupSheetOpPrototype.PropertyQuantity::displayString(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), PathScripts.PathProperty.Property::getValue(), PathScripts.PathSetupSheetOpPrototype.Property::getValue(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), PathScripts.PathProperty.Property::setValue(), PathScripts.PathSetupSheetOpPrototype.Property::setValue(), and Value().
Value()
Standard_Boolean StdMeshers::FunctionExpr::Value (const Standard_Real T, Standard_Real & F) virtual
References value().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_Distribution.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_Distribution.cpp