FreeCAD: Gui::Dialog::DlgSettingsSelection Class Reference
Gui::Dialog::DlgSettingsSelection Class Reference
The Ui_DlgSettingsSelection class implements a preference page to change settings for the selection.
#include <DlgSettingsSelection.h>
Public Member Functions
DlgSettingsSelection (QWidget *parent=nullptr)
void loadSettings ()
void saveSettings ()
~DlgSettingsSelection ()
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=0)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
Detailed Description
The Ui_DlgSettingsSelection class implements a preference page to change settings for the selection.
Author
Werner Mayer
Constructor & Destructor Documentation
DlgSettingsSelection()
DlgSettingsSelection::DlgSettingsSelection (QWidget * parent = nullptr)
~DlgSettingsSelection()
DlgSettingsSelection::~DlgSettingsSelection ()
Member Function Documentation
changeEvent()
void DlgSettingsSelection::changeEvent (QEvent * e) protected virtual
Implements Gui::Dialog::PreferencePage.
loadSettings()
void DlgSettingsSelection::loadSettings () virtual
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), and App::Application::GetParameterGroupByPath().
saveSettings()
void DlgSettingsSelection::saveSettings () virtual
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), and App::Application::GetParameterGroupByPath().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgSettingsSelection.h
Sources/FreeCAD/src/Gui/DlgSettingsSelection.cpp