FreeCAD: Ui_Angle Class Reference
Ui_Angle Class Reference
#include <ui_DlgLocationAngle.h>
Public Member Functions
void retranslateUi (QWidget *Angle)
void setupUi (QWidget *Angle)
Public Attributes
QCheckBox * checkBoxSnap
QComboBox * comboGridSize
QHBoxLayout * horizontalLayout
QHBoxLayout * horizontalLayout_2
QHBoxLayout * horizontalLayout_3
QLabel * label
QLabel * label_2
QLabel * label_3
QDoubleSpinBox * vectorA
QDoubleSpinBox * vectorB
QDoubleSpinBox * vectorC
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void Ui_Angle::retranslateUi (QWidget * Angle)
References checkBoxSnap, comboGridSize, label_2, label_3, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Ui_Angle::setupUi (QWidget * Angle)
References checkBoxSnap, comboGridSize, horizontalLayout, horizontalLayout_2, horizontalLayout_3, label_2, label_3, retranslateUi(), vectorA, vectorB, vectorC, and verticalLayout.
Referenced by Gui::TaskBoxAngle::TaskBoxAngle().
Member Data Documentation
checkBoxSnap
QCheckBox* Ui_Angle::checkBoxSnap
Referenced by retranslateUi(), and setupUi().
comboGridSize
QComboBox* Ui_Angle::comboGridSize
Referenced by retranslateUi(), and setupUi().
horizontalLayout
QHBoxLayout* Ui_Angle::horizontalLayout
Referenced by setupUi().
horizontalLayout_2
QHBoxLayout* Ui_Angle::horizontalLayout_2
Referenced by setupUi().
horizontalLayout_3
QHBoxLayout* Ui_Angle::horizontalLayout_3
Referenced by setupUi().
label
QLabel* Ui_Angle::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
label_2
QLabel* Ui_Angle::label_2
Referenced by retranslateUi(), and setupUi().
label_3
QLabel* Ui_Angle::label_3
Referenced by retranslateUi(), and setupUi().
vectorA
QDoubleSpinBox* Ui_Angle::vectorA
Referenced by setupUi().
vectorB
QDoubleSpinBox* Ui_Angle::vectorB
Referenced by setupUi().
vectorC
QDoubleSpinBox* Ui_Angle::vectorC
Referenced by setupUi().
verticalLayout
QVBoxLayout* Ui_Angle::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_DlgLocationAngle.h