FreeCAD: PartGui::FaceColors Class Reference
PartGui::FaceColors Class Reference
#include <TaskFaceColors.h>
Classes
class Private
Public Member Functions
bool accept ()
FaceColors (ViewProviderPartExt *vp, QWidget *parent=nullptr)
void open ()
bool reject ()
~FaceColors ()
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Protected Member Functions
void changeEvent (QEvent *e)
void onSelectionChanged (const Gui::SelectionChanges &msg)
void slotDeleteDocument (const Gui::Document &)
void slotDeleteObject (const Gui::ViewProvider &)
void slotUndoDocument (const Gui::Document &Doc)
void updatePanel ()
Constructor & Destructor Documentation
FaceColors()
FaceColors::FaceColors (ViewProviderPartExt * vp, QWidget * parent = nullptr)
References Gui::SelectionSingleton::addSelectionGate(), draftgeoutils.faces::bind(), PartGui::Ui_TaskFaceColors::colorButton, PartGui::FaceColors::Private::connectDelDoc, PartGui::FaceColors::Private::connectDelObj, PartGui::FaceColors::Private::connectUndoDoc, PartGui::FaceColors::Private::doc, Gui::ViewProviderDocumentObject::getObject(), App::PropertyString::getValue(), PartGui::Ui_TaskFaceColors::groupBox, Gui::Application::Instance, App::DocumentObject::Label, Gui::Selection(), Gui::ColorButton::setAllowTransparency(), PartGui::Ui_TaskFaceColors::setupUi(), Gui::Application::signalDeletedObject, Gui::Application::signalDeleteDocument, Gui::Document::signalUndoDocument, slotDeleteDocument(), slotDeleteObject(), slotUndoDocument(), PartGui::FaceColors::Private::ui, and PartGui::FaceColors::Private::vp.
~FaceColors()
FaceColors::~FaceColors ()
References PartGui::FaceColors::Private::connectDelDoc, PartGui::FaceColors::Private::connectDelObj, PartGui::FaceColors::Private::connectUndoDoc, Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), PartGui::FaceColors::Private::selectionCallback(), and PartGui::FaceColors::Private::view.
Member Function Documentation
accept()
bool FaceColors::accept (void)
References Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::Instance, and PartGui::FaceColors::Private::vp.
Referenced by PartGui::TaskFaceColors::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void FaceColors::changeEvent (QEvent * e) protected
References PartGui::Ui_TaskFaceColors::retranslateUi(), and PartGui::FaceColors::Private::ui.
onSelectionChanged()
void FaceColors::onSelectionChanged (const Gui::SelectionChanges & msg) protected virtual
Implements Gui::SelectionObserver.
References App::Color::a, Gui::SelectionChanges::AddSelection, App::Color::b, PartGui::FaceColors::Private::boxSelection, Gui::SelectionChanges::ClrSelection, PartGui::Ui_TaskFaceColors::colorButton, App::Color::g, App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), PartGui::FaceColors::Private::index, PartGui::FaceColors::Private::obj, PartGui::FaceColors::Private::perface, App::Color::r, Gui::SelectionChanges::RmvSelection, Gui::ColorButton::setColor(), PartGui::FaceColors::Private::ui, and updatePanel().
open()
void FaceColors::open ()
References Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::Instance, draftutils.translate::QT_TRANSLATE_NOOP, and PartGui::FaceColors::Private::vp.
Referenced by PartGui::TaskFaceColors::open().
reject()
bool FaceColors::reject (void)
References Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::Instance, and PartGui::FaceColors::Private::vp.
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), PartGui::TaskFaceColors::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
slotDeleteDocument()
void FaceColors::slotDeleteDocument (const Gui::Document & Doc) protected
References Gui::ControlSingleton::closeDialog(), Gui::Control(), and PartGui::FaceColors::Private::doc.
Referenced by FaceColors().
slotDeleteObject()
void FaceColors::slotDeleteObject (const Gui::ViewProvider & obj) protected
References Gui::ControlSingleton::closeDialog(), Gui::Control(), and PartGui::FaceColors::Private::vp.
Referenced by FaceColors().
slotUndoDocument()
void FaceColors::slotUndoDocument (const Gui::Document & Doc) protected
References Gui::ControlSingleton::closeDialog(), Gui::Control(), PartGui::FaceColors::Private::doc, and Gui::Document::resetEdit().
Referenced by FaceColors().
updatePanel()
void FaceColors::updatePanel () protected
References PartGui::Ui_TaskFaceColors::colorButton, Gui::QtTools::horizontalAdvance(), PartGui::FaceColors::Private::index, PartGui::Ui_TaskFaceColors::labelElement, and PartGui::FaceColors::Private::ui.
Referenced by onSelectionChanged(), and PartGui::FaceColors::Private::selectionCallback().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/TaskFaceColors.h
FreeCAD/src/Mod/Part/Gui/TaskFaceColors.cpp