FreeCAD: MED::TVector< _Tp, _Alloc > Class Template Reference
MED::TVector< _Tp, _Alloc > Class Template Reference
Main purpose to introduce the class was to customize operator [].
#include <MED_Vector.hxx>
Public Types
typedef superclass::allocator_type allocator_type
typedef const value_type & const_reference
typedef value_type & reference
typedef size_t size_type
typedef std::vector< _Tp, _Alloc > superclass
typedef _Tp value_type
Public Member Functions
reference at (size_type __n)
const_reference at (size_type __n) const
TVector & operator= (const TVector &__x)
template<typename _Yp , typename _Al >
TVector & operator= (TVector< _Yp, _Al > __y)
reference operator[] (size_type __n)
const_reference operator[] (size_type __n) const
template<typename _InputIterator >
TVector (_InputIterator __first, _InputIterator __last, const allocator_type &__a=allocator_type())
TVector (const allocator_type &__a=allocator_type())
TVector (const TVector &__x)
TVector (size_type __n)
TVector (size_type __n, const value_type &__val, const allocator_type &__a=allocator_type())
template<typename _Yp , typename _Al >
TVector (TVector< _Yp, _Al > __y)
Protected Member Functions
void check_range (size_type __n) const
reference get_value (size_type __n)
const_reference get_value (size_type __n) const
Detailed Description
template<typename _Tp, typename _Alloc = std::allocator<_Tp>>
class MED::TVector< _Tp, _Alloc >
Main purpose to introduce the class was to customize operator [].
Member Typedef Documentation
allocator_type
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> typedef superclass::allocator_type MED::TVector< _Tp, _Alloc >::allocator_type
const_reference
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> typedef const value_type& MED::TVector< _Tp, _Alloc >::const_reference
reference
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> typedef value_type& MED::TVector< _Tp, _Alloc >::reference
size_type
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> typedef size_t MED::TVector< _Tp, _Alloc >::size_type
superclass
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> typedef std::vector<_Tp, _Alloc> MED::TVector< _Tp, _Alloc >::superclass
value_type
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> typedef _Tp MED::TVector< _Tp, _Alloc >::value_type
Constructor & Destructor Documentation
TVector() [1/6]
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> MED::TVector< _Tp, _Alloc >::TVector (const allocator_type & __a = allocator_type()) explicit
TVector() [2/6]
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> MED::TVector< _Tp, _Alloc >::TVector (size_type __n, const value_type & __val, const allocator_type & __a = allocator_type())
TVector() [3/6]
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> MED::TVector< _Tp, _Alloc >::TVector (size_type __n) explicit
TVector() [4/6]
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> MED::TVector< _Tp, _Alloc >::TVector (const TVector< _Tp, _Alloc > & __x)
TVector() [5/6]
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> template<typename _InputIterator > MED::TVector< _Tp, _Alloc >::TVector (_InputIterator __first, _InputIterator __last, const allocator_type & __a = allocator_type())
TVector() [6/6]
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> template<typename _Yp , typename _Al > MED::TVector< _Tp, _Alloc >::TVector (TVector< _Yp, _Al > __y)
Member Function Documentation
at() [1/2]
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> reference MED::TVector< _Tp, _Alloc >::at (size_type __n)
at() [2/2]
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> const_reference MED::TVector< _Tp, _Alloc >::at (size_type __n) const
check_range()
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> void MED::TVector< _Tp, _Alloc >::check_range (size_type __n) const protected
Referenced by MED::TVector< TFloat >::at(), and MED::TVector< TFloat >::operator[]().
get_value() [1/2]
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> reference MED::TVector< _Tp, _Alloc >::get_value (size_type __n) protected
get_value() [2/2]
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> const_reference MED::TVector< _Tp, _Alloc >::get_value (size_type __n) const protected
Referenced by MED::TVector< TFloat >::at(), and MED::TVector< TFloat >::operator[]().
operator=() [1/2]
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> TVector& MED::TVector< _Tp, _Alloc >::operator= (const TVector< _Tp, _Alloc > & __x)
operator=() [2/2]
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> template<typename _Yp , typename _Al > TVector& MED::TVector< _Tp, _Alloc >::operator= (TVector< _Yp, _Al > __y)
operator[]() [1/2]
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> reference MED::TVector< _Tp, _Alloc >::operator[] (size_type __n)
operator[]() [2/2]
template<typename _Tp , typename _Alloc = std::allocator<_Tp>> const_reference MED::TVector< _Tp, _Alloc >::operator[] (size_type __n) const
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/MED_Vector.hxx