FreeCAD: MeshCore::PlaneFitSmoothing Class Reference
MeshCore::PlaneFitSmoothing Class Reference
#include <Smoothing.h>
Public Member Functions
PlaneFitSmoothing (MeshKernel &)
void Smooth (unsigned int)
Smooth the triangle mesh.
void SmoothPoints (unsigned int, const std::vector< PointIndex > &)
virtual ~PlaneFitSmoothing ()
Public Member Functions inherited from MeshCore::AbstractSmoothing
AbstractSmoothing (MeshKernel &)
void initialize (Component comp, Continuity cont)
virtual void Smooth (unsigned int)=0
Smooth the triangle mesh.
virtual void SmoothPoints (unsigned int, const std::vector< PointIndex > &)=0
virtual ~AbstractSmoothing ()
Additional Inherited Members
Public Types inherited from MeshCore::AbstractSmoothing
enum Component { Tangential , Normal , TangentialNormal }
enum Continuity { C0 , C1 , C2 }
Protected Attributes inherited from MeshCore::AbstractSmoothing
Component component
Continuity continuity
MeshKernel & kernel
float tolerance
Constructor & Destructor Documentation
PlaneFitSmoothing()
PlaneFitSmoothing::PlaneFitSmoothing (MeshKernel & m)
~PlaneFitSmoothing()
PlaneFitSmoothing::~PlaneFitSmoothing () virtual
Member Function Documentation
Smooth()
void PlaneFitSmoothing::Smooth (unsigned int) virtual
Smooth the triangle mesh.
Implements MeshCore::AbstractSmoothing.
References MeshCore::Approximation::AddPoint(), MeshCore::MeshPointIterator::Begin(), MeshCore::MeshKernel::CountPoints(), MeshCore::PlaneFit::Fit(), MeshCore::PlaneFit::GetNormal(), MeshCore::MeshKernel::GetPoints(), MeshCore::AbstractSmoothing::kernel, MeshCore::MeshPointIterator::More(), MeshCore::MeshPointIterator::Next(), Base::Vector3< _Precision >::Normalize(), MeshCore::MeshPointIterator::Position(), Base::Vector3< _Precision >::Set(), MeshCore::MeshKernel::SetPoint(), MeshCore::AbstractSmoothing::tolerance, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
SmoothPoints()
void PlaneFitSmoothing::SmoothPoints (unsigned int iterations, const std::vector< PointIndex > & point_indices) virtual
Implements MeshCore::AbstractSmoothing.
References MeshCore::Approximation::AddPoint(), MeshCore::MeshKernel::CountPoints(), MeshCore::PlaneFit::Fit(), MeshCore::PlaneFit::GetNormal(), MeshCore::MeshKernel::GetPoints(), MeshCore::AbstractSmoothing::kernel, Base::Vector3< _Precision >::Normalize(), MeshCore::MeshPointIterator::Position(), Base::Vector3< _Precision >::Set(), MeshCore::MeshPointIterator::Set(), MeshCore::MeshKernel::SetPoint(), MeshCore::AbstractSmoothing::tolerance, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/Core/Smoothing.h
FreeCAD/src/Mod/Mesh/App/Core/Smoothing.cpp