FreeCAD: TechDrawGui::QGDisplayArea Class Reference
TechDrawGui::QGDisplayArea Class Reference
#include <QGDisplayArea.h>
Public Types
enum { Type = QGraphicsItem::UserType + 137 }
Public Member Functions
virtual QRectF boundingRect () const
virtual void centerAt (double cX, double cY)
virtual void centerAt (QPointF centerPos)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr)
QGDisplayArea (void)
int type () const
~QGDisplayArea ()
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGDisplayArea()
QGDisplayArea::QGDisplayArea (void) explicit
~QGDisplayArea()
TechDrawGui::QGDisplayArea::~QGDisplayArea ()
Member Function Documentation
boundingRect()
QRectF QGDisplayArea::boundingRect () const virtual
Referenced by centerAt(), and TechDrawGui::QGIViewSymbol::rotateView().
centerAt() [1/2]
void QGDisplayArea::centerAt (double cX, double cY) virtual
References boundingRect().
centerAt() [2/2]
void QGDisplayArea::centerAt (QPointF centerPos) virtual
References centerAt().
Referenced by centerAt(), and TechDrawGui::QGIViewSymbol::QGIViewSymbol().
paint()
void QGDisplayArea::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr)
type()
int TechDrawGui::QGDisplayArea::type () const
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/QGDisplayArea.h
FreeCAD/src/Mod/TechDraw/Gui/QGDisplayArea.cpp