FreeCAD: App::DocumentObjectPy Class Reference
App::DocumentObjectPy Class Reference
The python export class for DocumentObject.
#include <DocumentObjectPy.h>
Public Types
typedef DocumentObject * PointerType
Public Types inherited from App::ExtensionContainerPy
typedef ExtensionContainer * PointerType
Public Types inherited from App::PropertyContainerPy
typedef PropertyContainer * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
DocumentObjectPy (DocumentObject *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from App::ExtensionContainerPy
ExtensionContainerPy (ExtensionContainer *pcObject, PyTypeObject *T=&Type)
int finalization ()
int initialization ()
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ExtensionContainer * getExtensionContainerPtr (void) const
getter for the object handled by this class
PyObject * addExtension (PyObject *args)
implementer for the addExtension() method
PyObject * hasExtension (PyObject *args)
implementer for the hasExtension() method
Public Member Functions inherited from App::PropertyContainerPy
PropertyContainerPy (PropertyContainer *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getPropertyByName (PyObject *args)
implementer for the getPropertyByName() method
PyObject * getPropertyTouchList (PyObject *args)
implementer for the getPropertyTouchList() method
PyObject * getTypeOfProperty (PyObject *args)
implementer for the getTypeOfProperty() method
PyObject * getTypeIdOfProperty (PyObject *args)
implementer for the getTypeIdOfProperty() method
PyObject * setEditorMode (PyObject *args)
implementer for the setEditorMode() method
PyObject * getEditorMode (PyObject *args)
implementer for the getEditorMode() method
PyObject * getGroupOfProperty (PyObject *args)
implementer for the getGroupOfProperty() method
PyObject * setPropertyStatus (PyObject *args)
implementer for the setPropertyStatus() method
PyObject * getPropertyStatus (PyObject *args)
implementer for the getPropertyStatus() method
PyObject * getDocumentationOfProperty (PyObject *args)
implementer for the getDocumentationOfProperty() method
PyObject * dumpPropertyContent (PyObject *args, PyObject *kwd)
implementer for the dumpPropertyContent() method
PyObject * restorePropertyContent (PyObject *args)
implementer for the restorePropertyContent() method
Py::List getPropertiesList (void) const
getter for the PropertiesList attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
PropertyContainer * getPropertyContainerPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::ExtensionContainerPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_addExtension (PyObject *self, PyObject *args)
callback for the addExtension() method
static PyObject * staticCallback_hasExtension (PyObject *self, PyObject *args)
callback for the hasExtension() method
Static Public Member Functions inherited from App::PropertyContainerPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_getPropertyByName (PyObject *self, PyObject *args)
callback for the getPropertyByName() method
static PyObject * staticCallback_getPropertyTouchList (PyObject *self, PyObject *args)
callback for the getPropertyTouchList() method
static PyObject * staticCallback_getTypeOfProperty (PyObject *self, PyObject *args)
callback for the getTypeOfProperty() method
static PyObject * staticCallback_getTypeIdOfProperty (PyObject *self, PyObject *args)
callback for the getTypeIdOfProperty() method
static PyObject * staticCallback_setEditorMode (PyObject *self, PyObject *args)
callback for the setEditorMode() method
static PyObject * staticCallback_getEditorMode (PyObject *self, PyObject *args)
callback for the getEditorMode() method
static PyObject * staticCallback_getGroupOfProperty (PyObject *self, PyObject *args)
callback for the getGroupOfProperty() method
static PyObject * staticCallback_setPropertyStatus (PyObject *self, PyObject *args)
callback for the setPropertyStatus() method
static PyObject * staticCallback_getPropertyStatus (PyObject *self, PyObject *args)
callback for the getPropertyStatus() method
static PyObject * staticCallback_getDocumentationOfProperty (PyObject *self, PyObject *args)
callback for the getDocumentationOfProperty() method
static PyObject * staticCallback_dumpPropertyContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpPropertyContent() method
static PyObject * staticCallback_restorePropertyContent (PyObject *self, PyObject *args)
callback for the restorePropertyContent() method
static PyObject * staticCallback_getPropertiesList (PyObject *self, void *closure)
getter callback for the PropertiesList attribute
static int staticCallback_setPropertiesList (PyObject *self, PyObject *value, void *closure)
setter callback for the PropertiesList attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of DocumentObjectPy.
static PyMethodDef Methods []
Methods structure of DocumentObjectPy.
static PyTypeObject Type
Type structure of DocumentObjectPy.
Static Public Attributes inherited from App::ExtensionContainerPy
static PyGetSetDef GetterSetter []
Attribute structure of ExtensionContainerPy.
static PyMethodDef Methods []
Methods structure of ExtensionContainerPy.
static PyTypeObject Type
Type structure of ExtensionContainerPy.
Static Public Attributes inherited from App::PropertyContainerPy
static PyGetSetDef GetterSetter []
Attribute structure of PropertyContainerPy.
static PyMethodDef Methods []
Methods structure of PropertyContainerPy.
static PyTypeObject Type
Type structure of PropertyContainerPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~DocumentObjectPy ()
Protected Member Functions inherited from App::ExtensionContainerPy
~ExtensionContainerPy ()
Protected Member Functions inherited from App::PropertyContainerPy
~PropertyContainerPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * addProperty (PyObject *args)
implementer for the addProperty() method
PyObject * removeProperty (PyObject *args)
implementer for the removeProperty() method
PyObject * supportedProperties (PyObject *args)
implementer for the supportedProperties() method
PyObject * touch (PyObject *args)
implementer for the touch() method
PyObject * purgeTouched (PyObject *args)
implementer for the purgeTouched() method
PyObject * enforceRecompute (PyObject *args)
implementer for the enforceRecompute() method
PyObject * setExpression (PyObject *args)
implementer for the setExpression() method
PyObject * evalExpression (PyObject *args)
implementer for the evalExpression() method
PyObject * recompute (PyObject *args)
implementer for the recompute() method
PyObject * getStatusString (PyObject *args)
implementer for the getStatusString() method
PyObject * isValid (PyObject *args)
implementer for the isValid() method
PyObject * getSubObject (PyObject *args, PyObject *kwd)
implementer for the getSubObject() method
PyObject * getSubObjectList (PyObject *args)
implementer for the getSubObjectList() method
PyObject * getSubObjects (PyObject *args)
implementer for the getSubObjects() method
PyObject * getLinkedObject (PyObject *args, PyObject *kwd)
implementer for the getLinkedObject() method
PyObject * setElementVisible (PyObject *args)
implementer for the setElementVisible() method
PyObject * isElementVisible (PyObject *args)
implementer for the isElementVisible() method
PyObject * hasChildElement (PyObject *args)
implementer for the hasChildElement() method
PyObject * getParentGroup (PyObject *args)
implementer for the getParentGroup() method
PyObject * getParentGeoFeatureGroup (PyObject *args)
implementer for the getParentGeoFeatureGroup() method
PyObject * getPathsByOutList (PyObject *args)
implementer for the getPathsByOutList() method
PyObject * resolve (PyObject *args)
implementer for the resolve() method
PyObject * resolveSubElement (PyObject *args)
implementer for the resolveSubElement() method
PyObject * adjustRelativeLinks (PyObject *args)
implementer for the adjustRelativeLinks() method
static PyObject * staticCallback_addProperty (PyObject *self, PyObject *args)
callback for the addProperty() method
static PyObject * staticCallback_removeProperty (PyObject *self, PyObject *args)
callback for the removeProperty() method
static PyObject * staticCallback_supportedProperties (PyObject *self, PyObject *args)
callback for the supportedProperties() method
static PyObject * staticCallback_touch (PyObject *self, PyObject *args)
callback for the touch() method
static PyObject * staticCallback_purgeTouched (PyObject *self, PyObject *args)
callback for the purgeTouched() method
static PyObject * staticCallback_enforceRecompute (PyObject *self, PyObject *args)
callback for the enforceRecompute() method
static PyObject * staticCallback_setExpression (PyObject *self, PyObject *args)
callback for the setExpression() method
static PyObject * staticCallback_evalExpression (PyObject *self, PyObject *args)
callback for the evalExpression() method
static PyObject * staticCallback_recompute (PyObject *self, PyObject *args)
callback for the recompute() method
static PyObject * staticCallback_getStatusString (PyObject *self, PyObject *args)
callback for the getStatusString() method
static PyObject * staticCallback_isValid (PyObject *self, PyObject *args)
callback for the isValid() method
static PyObject * staticCallback_getSubObject (PyObject *self, PyObject *args, PyObject *kwd)
callback for the getSubObject() method
static PyObject * staticCallback_getSubObjectList (PyObject *self, PyObject *args)
callback for the getSubObjectList() method
static PyObject * staticCallback_getSubObjects (PyObject *self, PyObject *args)
callback for the getSubObjects() method
static PyObject * staticCallback_getLinkedObject (PyObject *self, PyObject *args, PyObject *kwd)
callback for the getLinkedObject() method
static PyObject * staticCallback_setElementVisible (PyObject *self, PyObject *args)
callback for the setElementVisible() method
static PyObject * staticCallback_isElementVisible (PyObject *self, PyObject *args)
callback for the isElementVisible() method
static PyObject * staticCallback_hasChildElement (PyObject *self, PyObject *args)
callback for the hasChildElement() method
static PyObject * staticCallback_getParentGroup (PyObject *self, PyObject *args)
callback for the getParentGroup() method
static PyObject * staticCallback_getParentGeoFeatureGroup (PyObject *self, PyObject *args)
callback for the getParentGeoFeatureGroup() method
static PyObject * staticCallback_getPathsByOutList (PyObject *self, PyObject *args)
callback for the getPathsByOutList() method
static PyObject * staticCallback_resolve (PyObject *self, PyObject *args)
callback for the resolve() method
static PyObject * staticCallback_resolveSubElement (PyObject *self, PyObject *args)
callback for the resolveSubElement() method
static PyObject * staticCallback_adjustRelativeLinks (PyObject *self, PyObject *args)
callback for the adjustRelativeLinks() method
callbacks and implementers for the python object attributes
Py::List getOutList (void) const
getter for the OutList attribute
Py::List getOutListRecursive (void) const
getter for the OutListRecursive attribute
Py::List getInList (void) const
getter for the InList attribute
Py::List getInListRecursive (void) const
getter for the InListRecursive attribute
Py::String getFullName (void) const
getter for the FullName attribute
Py::String getName (void) const
getter for the Name attribute
Py::Object getDocument (void) const
getter for the Document attribute
Py::List getState (void) const
getter for the State attribute
Py::Object getViewObject (void) const
getter for the ViewObject attribute
Py::Boolean getMustExecute (void) const
getter for the MustExecute attribute
Py::Int getID (void) const
getter for the ID attribute
Py::Boolean getRemoving (void) const
getter for the Removing attribute
Py::List getParents (void) const
getter for the Parents attribute
Py::String getOldLabel (void) const
getter for the OldLabel attribute
Py::Boolean getNoTouch (void) const
getter for the NoTouch attribute
void setNoTouch (Py::Boolean arg)
setter for the NoTouch attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
DocumentObject * getDocumentObjectPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getOutList (PyObject *self, void *closure)
getter callback for the OutList attribute
static int staticCallback_setOutList (PyObject *self, PyObject *value, void *closure)
setter callback for the OutList attribute
static PyObject * staticCallback_getOutListRecursive (PyObject *self, void *closure)
getter callback for the OutListRecursive attribute
static int staticCallback_setOutListRecursive (PyObject *self, PyObject *value, void *closure)
setter callback for the OutListRecursive attribute
static PyObject * staticCallback_getInList (PyObject *self, void *closure)
getter callback for the InList attribute
static int staticCallback_setInList (PyObject *self, PyObject *value, void *closure)
setter callback for the InList attribute
static PyObject * staticCallback_getInListRecursive (PyObject *self, void *closure)
getter callback for the InListRecursive attribute
static int staticCallback_setInListRecursive (PyObject *self, PyObject *value, void *closure)
setter callback for the InListRecursive attribute
static PyObject * staticCallback_getFullName (PyObject *self, void *closure)
getter callback for the FullName attribute
static int staticCallback_setFullName (PyObject *self, PyObject *value, void *closure)
setter callback for the FullName attribute
static PyObject * staticCallback_getName (PyObject *self, void *closure)
getter callback for the Name attribute
static int staticCallback_setName (PyObject *self, PyObject *value, void *closure)
setter callback for the Name attribute
static PyObject * staticCallback_getDocument (PyObject *self, void *closure)
getter callback for the Document attribute
static int staticCallback_setDocument (PyObject *self, PyObject *value, void *closure)
setter callback for the Document attribute
static PyObject * staticCallback_getState (PyObject *self, void *closure)
getter callback for the State attribute
static int staticCallback_setState (PyObject *self, PyObject *value, void *closure)
setter callback for the State attribute
static PyObject * staticCallback_getViewObject (PyObject *self, void *closure)
getter callback for the ViewObject attribute
static int staticCallback_setViewObject (PyObject *self, PyObject *value, void *closure)
setter callback for the ViewObject attribute
static PyObject * staticCallback_getMustExecute (PyObject *self, void *closure)
getter callback for the MustExecute attribute
static int staticCallback_setMustExecute (PyObject *self, PyObject *value, void *closure)
setter callback for the MustExecute attribute
static PyObject * staticCallback_getID (PyObject *self, void *closure)
getter callback for the ID attribute
static int staticCallback_setID (PyObject *self, PyObject *value, void *closure)
setter callback for the ID attribute
static PyObject * staticCallback_getRemoving (PyObject *self, void *closure)
getter callback for the Removing attribute
static int staticCallback_setRemoving (PyObject *self, PyObject *value, void *closure)
setter callback for the Removing attribute
static PyObject * staticCallback_getParents (PyObject *self, void *closure)
getter callback for the Parents attribute
static int staticCallback_setParents (PyObject *self, PyObject *value, void *closure)
setter callback for the Parents attribute
static PyObject * staticCallback_getOldLabel (PyObject *self, void *closure)
getter callback for the OldLabel attribute
static int staticCallback_setOldLabel (PyObject *self, PyObject *value, void *closure)
setter callback for the OldLabel attribute
static PyObject * staticCallback_getNoTouch (PyObject *self, void *closure)
getter callback for the NoTouch attribute
static int staticCallback_setNoTouch (PyObject *self, PyObject *value, void *closure)
setter callback for the NoTouch attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for DocumentObject.
Member Typedef Documentation
PointerType
typedef DocumentObject* App::DocumentObjectPy::PointerType
Constructor & Destructor Documentation
~DocumentObjectPy()
DocumentObjectPy::~DocumentObjectPy () protected
DocumentObjectPy()
DocumentObjectPy::DocumentObjectPy (DocumentObject * pcObject, PyTypeObject * T = &Type)
Referenced by Path::FeaturePathCompoundPy::addObject(), and Path::FeaturePathCompoundPy::removeObject().
Member Function Documentation
addProperty()
PyObject * DocumentObjectPy::addProperty (PyObject * args)
implementer for the addProperty() method
References App::DocumentObject::addDynamicProperty(), Base::BaseExceptionFreeCADError, and getDocumentObjectPtr().
Referenced by DocumentObject.Box::init(), DocumentObject.DocumentObject::onChanged(), and staticCallback_addProperty().
adjustRelativeLinks()
PyObject * DocumentObjectPy::adjustRelativeLinks (PyObject * args)
implementer for the adjustRelativeLinks() method
References getDocumentObjectPtr(), App::DocumentObject::getInListEx(), and Type.
Referenced by staticCallback_adjustRelativeLinks().
enforceRecompute()
PyObject * DocumentObjectPy::enforceRecompute (PyObject * args)
implementer for the enforceRecompute() method
References App::DocumentObject::enforceRecompute(), and getDocumentObjectPtr().
Referenced by staticCallback_enforceRecompute().
evalExpression()
PyObject * DocumentObjectPy::evalExpression (PyObject * args)
implementer for the evalExpression() method
References getDocumentObjectPtr(), and App::Expression::parse().
Referenced by staticCallback_evalExpression().
getCustomAttributes()
PyObject * DocumentObjectPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
References getDocumentObjectPtr(), App::PropertyContainer::getDynamicPropertyByName(), and Base::BaseClass::getPyObject().
getDocument()
Py::Object DocumentObjectPy::getDocument (void) const
getter for the Document attribute
References getDocumentObjectPtr().
Referenced by Path::FeaturePathCompoundPy::addObject(), getViewObject(), Path::FeaturePathCompoundPy::removeObject(), and staticCallback_getDocument().
getDocumentObjectPtr()
DocumentObject * DocumentObjectPy::getDocumentObjectPtr (void) const
getter for the object handled by this class
Referenced by App::GroupExtensionPy::addObject(), App::GroupExtensionPy::addObjects(), addProperty(), adjustRelativeLinks(), enforceRecompute(), evalExpression(), getCustomAttributes(), getDocument(), getFullName(), App::GeoFeaturePy::getGlobalPlacement(), getID(), getInList(), getInListRecursive(), getLinkedObject(), getMustExecute(), getName(), getNoTouch(), getOldLabel(), getOutList(), getOutListRecursive(), getParentGeoFeatureGroup(), getParentGroup(), getParents(), getPathsByOutList(), getRemoving(), getState(), getStatusString(), getSubObject(), getSubObjectList(), getSubObjects(), getViewObject(), hasChildElement(), App::GroupExtensionPy::hasObject(), Fem::FemPostPipelinePy::holdsPostObject(), PartDesign::BodyPy::insertObject(), isElementVisible(), isValid(), Fem::FemPostPipelinePy::load(), App::DocumentPy::moveObject(), purgeTouched(), Attacher::AttachEnginePy::readParametersFromFeature(), recompute(), App::GroupExtensionPy::removeObject(), App::GroupExtensionPy::removeObjects(), removeProperty(), representation(), resolve(), resolveSubElement(), Gui::SelectionSingleton::sAddSelection(), setCustomAttributes(), setElementVisible(), setExpression(), setNoTouch(), Gui::ViewProviderDocumentObjectPy::setObject(), App::GroupExtensionPy::setObjects(), App::PropertyLink::setPyObject(), App::PropertyLinkSub::setPyObject(), App::PropertyLinkSubList::setPyObject(), App::PropertyXLink::setPyObject(), Gui::SelectionSingleton::sIsSelected(), Gui::SelectionSingleton::sRemoveSelection(), Gui::SelectionSingleton::sSetPreselection(), Gui::SelectionSingleton::sUpdateSelection(), Gui::SelectionFilterPy::test(), touch(), and Attacher::AttachEnginePy::writeParametersToFeature().
getFullName()
Py::String DocumentObjectPy::getFullName (void) const
getter for the FullName attribute
References getDocumentObjectPtr().
Referenced by staticCallback_getFullName().
getID()
Py::Int DocumentObjectPy::getID (void) const
getter for the ID attribute
References getDocumentObjectPtr().
Referenced by staticCallback_getID().
getInList()
Py::List DocumentObjectPy::getInList (void) const
getter for the InList attribute
References getDocumentObjectPtr(), and App::DocumentObject::getInList().
Referenced by staticCallback_getInList().
getInListRecursive()
Py::List DocumentObjectPy::getInListRecursive (void) const
getter for the InListRecursive attribute
References getDocumentObjectPtr(), and App::DocumentObject::getInListRecursive().
Referenced by staticCallback_getInListRecursive().
getLinkedObject()
PyObject * DocumentObjectPy::getLinkedObject (PyObject * args, PyObject * kwd)
implementer for the getLinkedObject() method
References getDocumentObjectPtr(), App::DocumentObject::getLinkedObject(), and Base::MatrixPy::Type.
Referenced by staticCallback_getLinkedObject().
getMustExecute()
Py::Boolean DocumentObjectPy::getMustExecute (void) const
getter for the MustExecute attribute
References getDocumentObjectPtr().
Referenced by staticCallback_getMustExecute().
getName()
Py::String DocumentObjectPy::getName (void) const
getter for the Name attribute
References getDocumentObjectPtr().
Referenced by getViewObject(), and staticCallback_getName().
getNoTouch()
Py::Boolean DocumentObjectPy::getNoTouch (void) const
getter for the NoTouch attribute
References getDocumentObjectPtr().
Referenced by staticCallback_getNoTouch().
getOldLabel()
Py::String DocumentObjectPy::getOldLabel (void) const
getter for the OldLabel attribute
References getDocumentObjectPtr().
Referenced by staticCallback_getOldLabel().
getOutList()
Py::List DocumentObjectPy::getOutList (void) const
getter for the OutList attribute
References getDocumentObjectPtr(), and App::DocumentObject::getOutList().
Referenced by staticCallback_getOutList().
getOutListRecursive()
Py::List DocumentObjectPy::getOutListRecursive (void) const
getter for the OutListRecursive attribute
References getDocumentObjectPtr(), and App::DocumentObject::getOutListRecursive().
Referenced by staticCallback_getOutListRecursive().
getParentGeoFeatureGroup()
PyObject * DocumentObjectPy::getParentGeoFeatureGroup (PyObject * args)
implementer for the getParentGeoFeatureGroup() method
References getDocumentObjectPtr(), and App::GeoFeatureGroupExtension::getGroupOfObject().
Referenced by staticCallback_getParentGeoFeatureGroup().
getParentGroup()
PyObject * DocumentObjectPy::getParentGroup (PyObject * args)
implementer for the getParentGroup() method
References getDocumentObjectPtr(), and App::GroupExtension::getGroupOfObject().
Referenced by staticCallback_getParentGroup().
getParents()
Py::List DocumentObjectPy::getParents (void) const
getter for the Parents attribute
References getDocumentObjectPtr().
Referenced by staticCallback_getParents().
getPathsByOutList()
PyObject * DocumentObjectPy::getPathsByOutList (PyObject * args)
implementer for the getPathsByOutList() method
References getDocumentObjectPtr(), App::DocumentObject::getPathsByOutList(), and Type.
Referenced by staticCallback_getPathsByOutList().
getRemoving()
Py::Boolean DocumentObjectPy::getRemoving (void) const
getter for the Removing attribute
References getDocumentObjectPtr().
Referenced by staticCallback_getRemoving().
getState()
Py::List DocumentObjectPy::getState (void) const
getter for the State attribute
References App::Expand, getDocumentObjectPtr(), App::ObjImporting, App::PartialObject, and App::Recompute2.
Referenced by staticCallback_getState().
getStatusString()
PyObject * DocumentObjectPy::getStatusString (PyObject * args)
implementer for the getStatusString() method
References getDocumentObjectPtr().
Referenced by staticCallback_getStatusString().
getSubObject()
PyObject * DocumentObjectPy::getSubObject (PyObject * args, PyObject * kwd)
implementer for the getSubObject() method
References getDocumentObjectPtr(), App::DocumentObject::getSubObject(), and Base::MatrixPy::Type.
Referenced by staticCallback_getSubObject().
getSubObjectList()
PyObject * DocumentObjectPy::getSubObjectList (PyObject * args)
implementer for the getSubObjectList() method
References getDocumentObjectPtr().
Referenced by staticCallback_getSubObjectList().
getSubObjects()
PyObject * DocumentObjectPy::getSubObjects (PyObject * args)
implementer for the getSubObjects() method
References getDocumentObjectPtr(), and App::DocumentObject::getSubObjects().
Referenced by staticCallback_getSubObjects().
GetType()
virtual PyTypeObject* App::DocumentObjectPy::GetType (void) virtual
Reimplemented from App::ExtensionContainerPy.
Reimplemented in TechDraw::DrawWeldSymbolPy, TechDraw::DrawViewSymbolPy, TechDraw::DrawViewPy, TechDraw::DrawViewPartPy, TechDraw::DrawViewDimExtentPy, TechDraw::DrawViewDimensionPy, TechDraw::DrawViewCollectionPy, TechDraw::DrawViewClipPy, TechDraw::DrawViewAnnotationPy, TechDraw::DrawTileWeldPy, TechDraw::DrawTilePy, TechDraw::DrawTemplatePy, TechDraw::DrawSVGTemplatePy, TechDraw::DrawRichAnnoPy, TechDraw::DrawProjGroupPy, TechDraw::DrawProjGroupItemPy, TechDraw::DrawParametricTemplatePy, TechDraw::DrawPagePy, TechDraw::DrawLeaderLinePy, TechDraw::DrawHatchPy, TechDraw::DrawGeomHatchPy, Spreadsheet::SheetPy, Sketcher::SketchObjectSFPy, Sketcher::SketchObjectPy, Robot::RobotObjectPy, Path::FeaturePathCompoundPy, Path::FeatureAreaPy, PartDesign::FeaturePy, PartDesign::BodyPy, Part::PartFeaturePy, Part::Part2DObjectPy, Part::BodyBasePy, Mesh::MeshFeaturePy, Fem::FemPostPipelinePy, App::PartPy, App::GeoFeaturePy, and App::DocumentObjectGroupPy.
getViewObject()
Py::Object DocumentObjectPy::getViewObject (void) const
getter for the ViewObject attribute
References getDocument(), getDocumentObjectPtr(), getName(), and App::DocumentObject::getNameInDocument().
Referenced by staticCallback_getViewObject().
hasChildElement()
PyObject * DocumentObjectPy::hasChildElement (PyObject * args)
implementer for the hasChildElement() method
References getDocumentObjectPtr().
Referenced by staticCallback_hasChildElement().
isElementVisible()
PyObject * DocumentObjectPy::isElementVisible (PyObject * args)
implementer for the isElementVisible() method
References getDocumentObjectPtr().
Referenced by staticCallback_isElementVisible().
isValid()
PyObject * DocumentObjectPy::isValid (PyObject * args)
implementer for the isValid() method
References getDocumentObjectPtr(), and App::DocumentObject::isValid().
purgeTouched()
PyObject * DocumentObjectPy::purgeTouched (PyObject * args)
implementer for the purgeTouched() method
References getDocumentObjectPtr(), and App::DocumentObject::purgeTouched().
Referenced by staticCallback_purgeTouched().
PyInit()
int DocumentObjectPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from App::ExtensionContainerPy.
Reimplemented in TechDraw::DrawWeldSymbolPy, TechDraw::DrawViewSymbolPy, TechDraw::DrawViewPy, TechDraw::DrawViewPartPy, TechDraw::DrawViewDimExtentPy, TechDraw::DrawViewDimensionPy, TechDraw::DrawViewCollectionPy, TechDraw::DrawViewClipPy, TechDraw::DrawViewAnnotationPy, TechDraw::DrawTileWeldPy, TechDraw::DrawTilePy, TechDraw::DrawTemplatePy, TechDraw::DrawSVGTemplatePy, TechDraw::DrawRichAnnoPy, TechDraw::DrawProjGroupPy, TechDraw::DrawProjGroupItemPy, TechDraw::DrawParametricTemplatePy, TechDraw::DrawPagePy, TechDraw::DrawLeaderLinePy, TechDraw::DrawHatchPy, TechDraw::DrawGeomHatchPy, Spreadsheet::SheetPy, Sketcher::SketchObjectSFPy, Sketcher::SketchObjectPy, Robot::RobotObjectPy, Path::FeaturePathCompoundPy, Path::FeatureAreaPy, PartDesign::FeaturePy, PartDesign::BodyPy, Part::PartFeaturePy, Part::Part2DObjectPy, Part::BodyBasePy, Mesh::MeshFeaturePy, Fem::FemPostPipelinePy, App::PartPy, App::GeoFeaturePy, and App::DocumentObjectGroupPy.
PyMake()
PyObject * DocumentObjectPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
recompute()
PyObject * DocumentObjectPy::recompute (PyObject * args)
implementer for the recompute() method
References getDocumentObjectPtr(), and App::DocumentObject::recomputeFeature().
Referenced by draftguitools.gui_trackers.arcTracker::setApertureAngle(), draftguitools.gui_trackers.arcTracker::setEndAngle(), draftguitools.gui_trackers.arcTracker::setStartAngle(), staticCallback_recompute(), draftguitools.gui_trackers.bsplineTracker::update(), and draftguitools.gui_trackers.bezcurveTracker::update().
removeProperty()
PyObject * DocumentObjectPy::removeProperty (PyObject * args)
implementer for the removeProperty() method
References getDocumentObjectPtr(), and App::DocumentObject::removeDynamicProperty().
Referenced by staticCallback_removeProperty().
representation()
std::string DocumentObjectPy::representation (void) const
References getDocumentObjectPtr().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
resolve()
PyObject * DocumentObjectPy::resolve (PyObject * args)
implementer for the resolve() method
References getDocumentObjectPtr(), App::DocumentObject::getPyObject(), and App::DocumentObject::resolve().
Referenced by staticCallback_resolve().
resolveSubElement()
PyObject * DocumentObjectPy::resolveSubElement (PyObject * args)
implementer for the resolveSubElement() method
References getDocumentObjectPtr(), and App::GeoFeature::resolveElement().
Referenced by staticCallback_resolveSubElement().
setCustomAttributes()
int DocumentObjectPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
References getDocumentObjectPtr(), App::PropertyContainer::getDynamicPropertyByName(), App::Property::getName(), App::ExtensionContainer::getPropertyByName(), App::Property::Immutable, App::Prop_ReadOnly, Base::BaseClass::setPyObject(), App::Property::testStatus(), and Base::Exception::what().
setElementVisible()
PyObject * DocumentObjectPy::setElementVisible (PyObject * args)
implementer for the setElementVisible() method
References getDocumentObjectPtr().
Referenced by staticCallback_setElementVisible().
setExpression()
PyObject * DocumentObjectPy::setExpression (PyObject * args)
implementer for the setExpression() method
References getDocumentObjectPtr(), App::ObjectIdentifier::parse(), App::ExpressionParser::parse(), App::Expression::parse(), and App::DocumentObject::setExpression().
Referenced by staticCallback_setExpression().
setNoTouch()
void DocumentObjectPy::setNoTouch (Py::Boolean arg)
setter for the NoTouch attribute
References getDocumentObjectPtr(), and App::DocumentObject::setStatus().
Referenced by staticCallback_setNoTouch().
staticCallback_addProperty()
PyObject * DocumentObjectPy::staticCallback_addProperty (PyObject * self, PyObject * args) static
callback for the addProperty() method
References addProperty(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_adjustRelativeLinks()
PyObject * DocumentObjectPy::staticCallback_adjustRelativeLinks (PyObject * self, PyObject * args) static
callback for the adjustRelativeLinks() method
References adjustRelativeLinks(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_enforceRecompute()
PyObject * DocumentObjectPy::staticCallback_enforceRecompute (PyObject * self, PyObject * args) static
callback for the enforceRecompute() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, enforceRecompute(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_evalExpression()
PyObject * DocumentObjectPy::staticCallback_evalExpression (PyObject * self, PyObject * args) static
callback for the evalExpression() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, evalExpression(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getDocument()
PyObject * DocumentObjectPy::staticCallback_getDocument (PyObject * self, void * closure) static
getter callback for the Document attribute
References Base::BaseExceptionFreeCADError, getDocument(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFullName()
PyObject * DocumentObjectPy::staticCallback_getFullName (PyObject * self, void * closure) static
getter callback for the FullName attribute
References Base::BaseExceptionFreeCADError, getFullName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getID()
PyObject * DocumentObjectPy::staticCallback_getID (PyObject * self, void * closure) static
getter callback for the ID attribute
References Base::BaseExceptionFreeCADError, getID(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getInList()
PyObject * DocumentObjectPy::staticCallback_getInList (PyObject * self, void * closure) static
getter callback for the InList attribute
References Base::BaseExceptionFreeCADError, getInList(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getInListRecursive()
PyObject * DocumentObjectPy::staticCallback_getInListRecursive (PyObject * self, void * closure) static
getter callback for the InListRecursive attribute
References Base::BaseExceptionFreeCADError, getInListRecursive(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getLinkedObject()
PyObject * DocumentObjectPy::staticCallback_getLinkedObject (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the getLinkedObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getLinkedObject(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getMustExecute()
PyObject * DocumentObjectPy::staticCallback_getMustExecute (PyObject * self, void * closure) static
getter callback for the MustExecute attribute
References Base::BaseExceptionFreeCADError, getMustExecute(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getName()
PyObject * DocumentObjectPy::staticCallback_getName (PyObject * self, void * closure) static
getter callback for the Name attribute
References Base::BaseExceptionFreeCADError, getName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNoTouch()
PyObject * DocumentObjectPy::staticCallback_getNoTouch (PyObject * self, void * closure) static
getter callback for the NoTouch attribute
References Base::BaseExceptionFreeCADError, getNoTouch(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getOldLabel()
PyObject * DocumentObjectPy::staticCallback_getOldLabel (PyObject * self, void * closure) static
getter callback for the OldLabel attribute
References Base::BaseExceptionFreeCADError, getOldLabel(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getOutList()
PyObject * DocumentObjectPy::staticCallback_getOutList (PyObject * self, void * closure) static
getter callback for the OutList attribute
References Base::BaseExceptionFreeCADError, getOutList(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getOutListRecursive()
PyObject * DocumentObjectPy::staticCallback_getOutListRecursive (PyObject * self, void * closure) static
getter callback for the OutListRecursive attribute
References Base::BaseExceptionFreeCADError, getOutListRecursive(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getParentGeoFeatureGroup()
PyObject * DocumentObjectPy::staticCallback_getParentGeoFeatureGroup (PyObject * self, PyObject * args) static
callback for the getParentGeoFeatureGroup() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getParentGeoFeatureGroup(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getParentGroup()
PyObject * DocumentObjectPy::staticCallback_getParentGroup (PyObject * self, PyObject * args) static
callback for the getParentGroup() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getParentGroup(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getParents()
PyObject * DocumentObjectPy::staticCallback_getParents (PyObject * self, void * closure) static
getter callback for the Parents attribute
References Base::BaseExceptionFreeCADError, getParents(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPathsByOutList()
PyObject * DocumentObjectPy::staticCallback_getPathsByOutList (PyObject * self, PyObject * args) static
callback for the getPathsByOutList() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPathsByOutList(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getRemoving()
PyObject * DocumentObjectPy::staticCallback_getRemoving (PyObject * self, void * closure) static
getter callback for the Removing attribute
References Base::BaseExceptionFreeCADError, getRemoving(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getState()
PyObject * DocumentObjectPy::staticCallback_getState (PyObject * self, void * closure) static
getter callback for the State attribute
References Base::BaseExceptionFreeCADError, getState(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getStatusString()
PyObject * DocumentObjectPy::staticCallback_getStatusString (PyObject * self, PyObject * args) static
callback for the getStatusString() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getStatusString(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getSubObject()
PyObject * DocumentObjectPy::staticCallback_getSubObject (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the getSubObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getSubObject(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getSubObjectList()
PyObject * DocumentObjectPy::staticCallback_getSubObjectList (PyObject * self, PyObject * args) static
callback for the getSubObjectList() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getSubObjectList(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getSubObjects()
PyObject * DocumentObjectPy::staticCallback_getSubObjects (PyObject * self, PyObject * args) static
callback for the getSubObjects() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getSubObjects(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getViewObject()
PyObject * DocumentObjectPy::staticCallback_getViewObject (PyObject * self, void * closure) static
getter callback for the ViewObject attribute
References Base::BaseExceptionFreeCADError, getViewObject(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_hasChildElement()
PyObject * DocumentObjectPy::staticCallback_hasChildElement (PyObject * self, PyObject * args) static
callback for the hasChildElement() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hasChildElement(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_isElementVisible()
PyObject * DocumentObjectPy::staticCallback_isElementVisible (PyObject * self, PyObject * args) static
callback for the isElementVisible() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), isElementVisible(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_isValid()
PyObject * DocumentObjectPy::staticCallback_isValid (PyObject * self, PyObject * args) static
callback for the isValid() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_purgeTouched()
PyObject * DocumentObjectPy::staticCallback_purgeTouched (PyObject * self, PyObject * args) static
callback for the purgeTouched() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), purgeTouched(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_recompute()
PyObject * DocumentObjectPy::staticCallback_recompute (PyObject * self, PyObject * args) static
callback for the recompute() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), recompute(), and Base::PyObjectBase::startNotify().
staticCallback_removeProperty()
PyObject * DocumentObjectPy::staticCallback_removeProperty (PyObject * self, PyObject * args) static
callback for the removeProperty() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeProperty(), and Base::PyObjectBase::startNotify().
staticCallback_resolve()
PyObject * DocumentObjectPy::staticCallback_resolve (PyObject * self, PyObject * args) static
callback for the resolve() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and resolve().
staticCallback_resolveSubElement()
PyObject * DocumentObjectPy::staticCallback_resolveSubElement (PyObject * self, PyObject * args) static
callback for the resolveSubElement() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and resolveSubElement().
staticCallback_setDocument()
int DocumentObjectPy::staticCallback_setDocument (PyObject * self, PyObject * value, void * closure) static
setter callback for the Document attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setElementVisible()
PyObject * DocumentObjectPy::staticCallback_setElementVisible (PyObject * self, PyObject * args) static
callback for the setElementVisible() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setElementVisible(), and Base::PyObjectBase::startNotify().
staticCallback_setExpression()
PyObject * DocumentObjectPy::staticCallback_setExpression (PyObject * self, PyObject * args) static
callback for the setExpression() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setExpression(), and Base::PyObjectBase::startNotify().
staticCallback_setFullName()
int DocumentObjectPy::staticCallback_setFullName (PyObject * self, PyObject * value, void * closure) static
setter callback for the FullName attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setID()
int DocumentObjectPy::staticCallback_setID (PyObject * self, PyObject * value, void * closure) static
setter callback for the ID attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setInList()
int DocumentObjectPy::staticCallback_setInList (PyObject * self, PyObject * value, void * closure) static
setter callback for the InList attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setInListRecursive()
int DocumentObjectPy::staticCallback_setInListRecursive (PyObject * self, PyObject * value, void * closure) static
setter callback for the InListRecursive attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setMustExecute()
int DocumentObjectPy::staticCallback_setMustExecute (PyObject * self, PyObject * value, void * closure) static
setter callback for the MustExecute attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setName()
int DocumentObjectPy::staticCallback_setName (PyObject * self, PyObject * value, void * closure) static
setter callback for the Name attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setNoTouch()
int DocumentObjectPy::staticCallback_setNoTouch (PyObject * self, PyObject * value, void * closure) static
setter callback for the NoTouch attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setNoTouch().
staticCallback_setOldLabel()
int DocumentObjectPy::staticCallback_setOldLabel (PyObject * self, PyObject * value, void * closure) static
setter callback for the OldLabel attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setOutList()
int DocumentObjectPy::staticCallback_setOutList (PyObject * self, PyObject * value, void * closure) static
setter callback for the OutList attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setOutListRecursive()
int DocumentObjectPy::staticCallback_setOutListRecursive (PyObject * self, PyObject * value, void * closure) static
setter callback for the OutListRecursive attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setParents()
int DocumentObjectPy::staticCallback_setParents (PyObject * self, PyObject * value, void * closure) static
setter callback for the Parents attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setRemoving()
int DocumentObjectPy::staticCallback_setRemoving (PyObject * self, PyObject * value, void * closure) static
setter callback for the Removing attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setState()
int DocumentObjectPy::staticCallback_setState (PyObject * self, PyObject * value, void * closure) static
setter callback for the State attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setViewObject()
int DocumentObjectPy::staticCallback_setViewObject (PyObject * self, PyObject * value, void * closure) static
setter callback for the ViewObject attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_supportedProperties()
PyObject * DocumentObjectPy::staticCallback_supportedProperties (PyObject * self, PyObject * args) static
callback for the supportedProperties() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and supportedProperties().
staticCallback_touch()
PyObject * DocumentObjectPy::staticCallback_touch (PyObject * self, PyObject * args) static
callback for the touch() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and touch().
supportedProperties()
PyObject * DocumentObjectPy::supportedProperties (PyObject * args)
implementer for the supportedProperties() method
References Base::Type::getAllDerivedFrom(), and Base::Persistence::getClassTypeId().
Referenced by staticCallback_supportedProperties().
touch()
PyObject * DocumentObjectPy::touch (PyObject * args)
implementer for the touch() method
References getDocumentObjectPtr(), App::ExtensionContainer::getPropertyByName(), and App::DocumentObject::touch().
Referenced by staticCallback_touch().
Member Data Documentation
GetterSetter
PyGetSetDef DocumentObjectPy::GetterSetter static
Attribute structure of DocumentObjectPy.
Methods
PyMethodDef DocumentObjectPy::Methods static
Methods structure of DocumentObjectPy.
Type
PyTypeObject DocumentObjectPy::Type static
Type structure of DocumentObjectPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), App::GroupExtensionPy::addObject(), App::GroupExtensionPy::addObjects(), ArchStructure.StructSelectionObserver::addSelection(), TechDraw::DrawPagePy::addView(), TechDraw::DrawViewClipPy::addView(), TechDraw::DrawViewCollectionPy::addView(), adjustRelativeLinks(), Gui::ExpressionBindingPy::bind(), ArchSite.Compass::buildCoordinates(), Gui::ViewProviderPy::canDragAndDropObject(), Gui::ViewProviderPy::canDragObject(), Gui::ViewProviderPy::canDropObject(), Gui::ViewProviderPythonFeatureImp::claimChildren(), App::DocumentPy::copyObject(), Gui::ViewProviderPy::dragObject(), Gui::ViewProviderPy::dropObject(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), Gui::FreeCADGui_subgraphFromObject(), App::FeaturePythonImp::getLinkedObject(), App::DocumentPy::getLinksTo(), getPathsByOutList(), App::PropertyLinkList::getPyValue(), App::FeaturePythonImp::getSubObject(), App::GroupExtensionPy::hasObject(), Fem::FemPostPipelinePy::holdsPostObject(), App::DocumentPy::importLinks(), PartDesign::BodyPy::insertObject(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), Fem::FemPostPipelinePy::load(), App::DocumentPy::moveObject(), Attacher::AttachEnginePy::readParametersFromFeature(), App::DocumentPy::recompute(), App::GroupExtensionPy::removeObject(), App::GroupExtensionPy::removeObjects(), TechDraw::DrawPagePy::removeView(), TechDraw::DrawViewClipPy::removeView(), TechDraw::DrawViewCollectionPy::removeView(), Gui::ViewProviderPy::replaceObject(), Gui::SelectionSingleton::sAddSelection(), draftobjects.layer.Layer::set_properties(), Gui::MDIViewPy::setActiveObject(), Gui::View3DInventorPy::setActiveObject(), Gui::DocumentPy::setEdit(), Gui::LinkViewPy::setLink(), Gui::ViewProviderDocumentObjectPy::setObject(), App::GroupExtensionPy::setObjects(), ArchReference.ArchReference::setProperties(), App::PropertyLink::setPyObject(), App::PropertyLinkSub::setPyObject(), App::PropertyLinkSubList::setPyObject(), App::PropertyXLink::setPyObject(), Gui::Application::sExport(), Gui::Application::sHideObject(), Gui::SelectionSingleton::sIsSelected(), Gui::SelectionSingleton::sRemoveSelection(), Gui::SelectionSingleton::sSetPreselection(), Gui::Application::sShowObject(), Gui::SelectionSingleton::sUpdateSelection(), Gui::SelectionFilterPy::test(), Gui::DocumentPy::toggleTreeItem(), and Attacher::AttachEnginePy::writeParametersToFeature().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/App/DocumentObjectPy.h
Sources/FreeCAD/src/App/DocumentObjectPyImp.cpp
Sources/FreeCAD-SourceDocs/src/App/DocumentObjectPy.cpp