FreeCAD: SMDS_MeshNode_MyIterator Class Reference
SMDS_MeshNode_MyIterator Class Reference
Public Member Functions
bool more ()
Return true if and only if there are other object in this iterator.
const SMDS_MeshElement * next ()
Return the current object and step to the next one.
SMDS_MeshNode_MyIterator (SMDS_Mesh *mesh, vtkIdType *cells, int ncells, SMDSAbs_ElementType type)
Public Member Functions inherited from SMDS_Iterator< VALUE >
virtual void remove ()
Delete the current element and step to the next one.
virtual ~SMDS_Iterator ()
Provide virtual destructor just for case if some derived iterator must have a destructor.
Constructor & Destructor Documentation
SMDS_MeshNode_MyIterator()
SMDS_MeshNode_MyIterator::SMDS_MeshNode_MyIterator (SMDS_Mesh * mesh, vtkIdType * cells, int ncells, SMDSAbs_ElementType type)
References SMDS_Mesh::FindElement(), SMDS_Mesh::fromVtkToSmds(), and SMDS_MeshElement::GetType().
Member Function Documentation
more()
bool SMDS_MeshNode_MyIterator::more () virtual
Return true if and only if there are other object in this iterator.
Implements SMDS_Iterator< VALUE >.
next()
const SMDS_MeshElement* SMDS_MeshNode_MyIterator::next () virtual
Return the current object and step to the next one.
Implements SMDS_Iterator< VALUE >.
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_MeshNode.cpp