FreeCAD: SMESH::Controls::TMeshModifTracer Class Reference
SMESH::Controls::TMeshModifTracer Class Reference
Class used to detect mesh modification: IsMeshModified() returns true if a mesh has changed since last calling IsMeshModified()
#include <SMESH_ControlsDef.hxx>
Public Member Functions
const SMDS_Mesh * GetMesh () const
bool IsMeshModified ()
void SetMesh (const SMDS_Mesh *theMesh)
TMeshModifTracer ()
Detailed Description
Class used to detect mesh modification: IsMeshModified() returns true if a mesh has changed since last calling IsMeshModified()
Constructor & Destructor Documentation
TMeshModifTracer()
TMeshModifTracer::TMeshModifTracer ()
Member Function Documentation
GetMesh()
const SMDS_Mesh* SMESH::Controls::TMeshModifTracer::GetMesh () const
Referenced by SMESH::Controls::ElementsOnShape::IsSatisfy(), SMESH::Controls::ConnectedElements::IsSatisfy(), SMESH::Controls::CoplanarFaces::SetMesh(), SMESH::Controls::ConnectedElements::SetNode(), and SMESH::Controls::ConnectedElements::SetPoint().
IsMeshModified()
bool TMeshModifTracer::IsMeshModified ()
References SMDS_Mesh::GetMTime().
Referenced by SMESH::Controls::ElementsOnSurface::SetMesh(), SMESH::Controls::ElementsOnShape::SetMesh(), SMESH::Controls::CoplanarFaces::SetMesh(), SMESH::Controls::ConnectedElements::SetMesh(), SMESH::Controls::ConnectedElements::SetNode(), SMESH::Controls::ConnectedElements::SetPoint(), and SMESH::Controls::ConnectedElements::SetType().
SetMesh()
void TMeshModifTracer::SetMesh (const SMDS_Mesh * theMesh)
Referenced by SMESH::Controls::ElementsOnSurface::SetMesh(), SMESH::Controls::ElementsOnShape::SetMesh(), SMESH::Controls::CoplanarFaces::SetMesh(), and SMESH::Controls::ConnectedElements::SetMesh().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp