FreeCAD: GCS::Hyperbola Class Reference
GCS::Hyperbola Class Reference
#include <Geo.h>
Public Member Functions
DeriVector2 CalculateNormal (Point &p, double *derivparam=0)
virtual Hyperbola * Copy ()
virtual double getRadMaj ()
virtual double getRadMaj (const DeriVector2 &center, const DeriVector2 &f1, double b, double db, double &ret_dRadMaj)
virtual double getRadMaj (double *derivparam, double &ret_dRadMaj)
Hyperbola ()
virtual int PushOwnParams (VEC_pD &pvec)
virtual void ReconstructOnNewPvec (VEC_pD &pvec, int &cnt)
virtual DeriVector2 Value (double u, double du, double *derivparam=0)
Value: returns point (vector) given the value of parameter.
virtual ~Hyperbola ()
Public Member Functions inherited from GCS::MajorRadiusConic
virtual ~MajorRadiusConic ()
Public Member Functions inherited from GCS::Curve
virtual ~Curve ()
Public Attributes
Point center
Point focus1
double * radmin
Constructor & Destructor Documentation
Hyperbola()
GCS::Hyperbola::Hyperbola ()
References radmin.
Referenced by Copy().
~Hyperbola()
virtual GCS::Hyperbola::~Hyperbola () virtual
Member Function Documentation
CalculateNormal()
DeriVector2 GCS::Hyperbola::CalculateNormal (Point & p, double * derivparam = 0) virtual
Implements GCS::MajorRadiusConic.
References center, focus1, GCS::DeriVector2::getNormalized(), GCS::DeriVector2::linCombi(), GCS::DeriVector2::mult(), GCS::DeriVector2::subtr(), and GCS::DeriVector2::sum().
Copy()
Hyperbola * GCS::Hyperbola::Copy (void) virtual
Implements GCS::Curve.
Reimplemented in GCS::ArcOfHyperbola.
References Hyperbola().
getRadMaj() [1/3]
double GCS::Hyperbola::getRadMaj () virtual
Implements GCS::MajorRadiusConic.
Referenced by getRadMaj(), and Value().
getRadMaj() [2/3]
double GCS::Hyperbola::getRadMaj (const DeriVector2 & center, const DeriVector2 & f1, double b, double db, double & ret_dRadMaj) virtual
Implements GCS::MajorRadiusConic.
References center, GCS::DeriVector2::length(), and GCS::DeriVector2::subtr().
getRadMaj() [3/3]
double GCS::Hyperbola::getRadMaj (double * derivparam, double & ret_dRadMaj) virtual
Implements GCS::MajorRadiusConic.
References center, focus1, getRadMaj(), and radmin.
PushOwnParams()
int GCS::Hyperbola::PushOwnParams (VEC_pD & pvec) virtual
Implements GCS::Curve.
Reimplemented in GCS::ArcOfHyperbola.
References center, focus1, radmin, GCS::Point::x, and GCS::Point::y.
Referenced by GCS::ConstraintInternalAlignmentPoint2Hyperbola::ConstraintInternalAlignmentPoint2Hyperbola(), and GCS::ArcOfHyperbola::PushOwnParams().
ReconstructOnNewPvec()
void GCS::Hyperbola::ReconstructOnNewPvec (VEC_pD & pvec, int & cnt) virtual
Implements GCS::Curve.
Reimplemented in GCS::ArcOfHyperbola.
References center, focus1, radmin, GCS::Point::x, and GCS::Point::y.
Referenced by GCS::ArcOfHyperbola::ReconstructOnNewPvec().
Value()
DeriVector2 GCS::Hyperbola::Value (double u, double du, double * derivparam = 0) virtual
Value: returns point (vector) given the value of parameter.
Parameters
u value of parameter
du derivative of parameter by derivparam
derivparam pointer to sketch parameter to calculate the derivative for
Returns
Reimplemented from GCS::Curve.
References center, focus1, GCS::DeriVector2::getNormalized(), getRadMaj(), GCS::DeriVector2::multD(), radmin, GCS::DeriVector2::rotate90ccw(), GCS::DeriVector2::subtr(), and GCS::DeriVector2::sum().
Member Data Documentation
center
Point GCS::Hyperbola::center
Referenced by CalculateNormal(), PathScripts.PathDressupAxisMap.ObjectDressup::execute(), getRadMaj(), PathScripts.PathDressupAxisMap.ObjectDressup::onChanged(), PushOwnParams(), ReconstructOnNewPvec(), and Value().
focus1
Point GCS::Hyperbola::focus1
Referenced by CalculateNormal(), getRadMaj(), PushOwnParams(), ReconstructOnNewPvec(), and Value().
radmin
double* GCS::Hyperbola::radmin
Referenced by GCS::ArcOfHyperbola::ArcOfHyperbola(), getRadMaj(), Hyperbola(), PushOwnParams(), ReconstructOnNewPvec(), and Value().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Geo.h
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Geo.cpp