FreeCAD: Base::ViewProjMatrix Class Reference
Base::ViewProjMatrix Class Reference
The ViewProjMatrix class returns the result of the multiplication of the 3D vector and the view transformation matrix.
#include <ViewProj.h>
Public Member Functions
Matrix4D getProjectionMatrix () const
Calculate the projection (+ mapping) matrix.
Vector3d inverse (const Vector3d &rclPt) const
Convert a 2D point on the projection plane in 3D space.
Vector3f inverse (const Vector3f &rclPt) const
Convert a 2D point on the projection plane in 3D space.
Vector3d operator() (const Vector3d &rclPt) const
Convert 3D point to 2D projection plane.
Vector3f operator() (const Vector3f &rclPt) const
Convert 3D point to 2D projection plane.
ViewProjMatrix (const Matrix4D &rclMtx)
Public Member Functions inherited from Base::ViewProjMethod
Matrix4D getComposedProjectionMatrix () const
Calculate the composed projection matrix.
virtual Matrix4D getProjectionMatrix () const =0
Calculate the projection (+ mapping) matrix.
const Base::Matrix4D & getTransform () const
virtual Vector3d inverse (const Vector3d &rclPt) const =0
Convert a 2D point on the projection plane in 3D space.
virtual Vector3f inverse (const Vector3f &rclPt) const =0
Convert a 2D point on the projection plane in 3D space.
virtual bool isValid () const
virtual Vector3d operator() (const Vector3d &rclPt) const =0
Convert 3D point to 2D projection plane.
virtual Vector3f operator() (const Vector3f &rclPt) const =0
Convert 3D point to 2D projection plane.
ViewProjMethod & operator= (const ViewProjMethod &)=default
void setTransform (const Base::Matrix4D &)
Apply an additional transformation to the input points.
ViewProjMethod (const ViewProjMethod &)=default
virtual ~ViewProjMethod ()=default
Protected Attributes
bool isOrthographic
Additional Inherited Members
Protected Member Functions inherited from Base::ViewProjMethod
void transformInput (const Base::Vector3d &, Base::Vector3d &) const
void transformInput (const Base::Vector3f &, Base::Vector3f &) const
ViewProjMethod ()
Detailed Description
The ViewProjMatrix class returns the result of the multiplication of the 3D vector and the view transformation matrix.
Constructor & Destructor Documentation
ViewProjMatrix()
ViewProjMatrix::ViewProjMatrix (const Matrix4D & rclMtx)
References isOrthographic.
Member Function Documentation
getProjectionMatrix()
Matrix4D ViewProjMatrix::getProjectionMatrix () const virtual
Calculate the projection (+ mapping) matrix.
Implements Base::ViewProjMethod.
References isOrthographic, Base::Matrix4D::move(), and Base::Matrix4D::scale().
inverse() [1/2]
Vector3d ViewProjMatrix::inverse (const Vector3d & rclPt) const virtual
Convert a 2D point on the projection plane in 3D space.
Implements Base::ViewProjMethod.
References isOrthographic, and Base::Vector3< _Precision >::Set().
inverse() [2/2]
Vector3f ViewProjMatrix::inverse (const Vector3f & rclPt) const virtual
Convert a 2D point on the projection plane in 3D space.
Implements Base::ViewProjMethod.
References isOrthographic, and Base::Vector3< _Precision >::Set().
operator()() [1/2]
Vector3d ViewProjMatrix::operator() (const Vector3d & rclPt) const virtual
Convert 3D point to 2D projection plane.
Implements Base::ViewProjMethod.
References isOrthographic, and Base::ViewProjMethod::transformInput().
operator()() [2/2]
Vector3f ViewProjMatrix::operator() (const Vector3f & rclPt) const virtual
Convert 3D point to 2D projection plane.
Implements Base::ViewProjMethod.
References isOrthographic, and Base::ViewProjMethod::transformInput().
Member Data Documentation
isOrthographic
bool Base::ViewProjMatrix::isOrthographic protected
Referenced by getProjectionMatrix(), inverse(), operator()(), and ViewProjMatrix().
The documentation for this class was generated from the following files:
FreeCAD/src/Base/ViewProj.h
FreeCAD/src/Base/ViewProj.cpp