FreeCAD: App Namespace Reference
App Namespace Reference
Core » App
The FreeCAD Application layer.
Namespaces
namespace ExpressionParser
namespace Meta
Classes
class Annotation
class AnnotationLabel
class Application
The Application The root of the whole application.
class AtomicPropertyChangeInterface
A template class that is used to inhibit multiple nested calls to aboutToSetValue/hasSetValue for properties.
class AutoTransaction
Helper class to manager transaction (i.e. undo/redo)
class BackupPolicy
class Branding
struct CellAddress
class Color
Color class.
class ColorField
class ColorGradient
struct ColorGradientProfile
class ColorLegend
class ColorModel
class ColorModelBlackGray
class ColorModelBlackWhite
class ColorModelBlueCyanGreen
class ColorModelBlueGreenRed
class ColorModelBlueWhite
class ColorModelBlueWhiteRed
class ColorModelGrayBlack
class ColorModelGrayWhite
class ColorModelGreenCyanBlue
class ColorModelGreenYellowRed
struct ColorModelPack
class ColorModelRedGreenBlue
class ColorModelRedYellowGreen
class ColorModelWhiteBlack
class ColorModelWhiteGray
class ColorModelWhiteRed
class ConditionalExpression
class ConstantExpression
struct CStringHasher
class DocInfo
class Document
The document class.
class DocumentObject
Base class of all Classes handled in the Document.
class DocumentObjectExecReturn
Return object for feature execution.
class DocumentObjectExtension
Extension with special document object calls.
class DocumentObjectFileIncluded
class DocumentObjectGroup
class DocumentObjectObserver
The DocumentObjectObserver class checks for a list of objects which of them get removed.
class DocumentObjectT
The DocumentObjectT class is a helper class to store the names of a document object and its document.
class DocumentObjectWeakPtrT
The DocumentObjectWeakPtrT class.
class DocumentObserver
The DocumentObserver class simplfies the step to write classes that listen to what happens inside a document.
class DocumentObserverPython
The DocumentObserverPython class is used to notify registered Python instances whenever something happens to a document, like creation, destruction, adding or removing objects or when property changes.
struct DocumentP
class DocumentT
The DocumentT class is a helper class to store the name of a document.
class DocumentWeakPtrT
The DocumentWeakPtrT class.
class DynamicProperty
This class implements an interface to add properties at run-time to an object derived from PropertyContainer.
class Enumeration
A bidirectional string-integer mapping.
class Expression
Base class for expressions.
class ExpressionModifier
class ExpressionVisitor
class Extension
Base class for all extension that can be added to a DocumentObject.
class ExtensionContainer
Container which can hold extensions.
class ExtensionPythonT
Generic Python extension class which allows every extension derived class to behave as a Python extension – simply by subclassing.
class FeatureCustomT
FeatureCustomT is a template class to be used with DocumentObject or any of its subclasses as template parameter.
class FeaturePythonImp
class FeaturePythonPyT
class FeaturePythonT
Generic Python feature class which allows to behave every DocumentObject derived class as Python feature – simply by subclassing.
class FeatureTest
The testing feature.
class FeatureTestException
The exception testing feature.
class FunctionExpression
Class implementing various functions, e.g sin, cos, etc.
class GeoFeature
Base class of all geometric document objects.
class GeoFeatureGroupExtension
The base class for placeable group of DocumentObjects.
class GroupExtension
class GroupExtensionPythonT
class InventorObject
class Line
class Link
class LinkBaseExtension
class LinkElement
class LinkExtension
class LinkGroup
class LinkParams
Convenient class to obtain App::Link related parameters.
class Material
Material class.
class MaterialObject
class MeasureDistance
class MergeDocuments
class Metadata
Reads data from a metadata file.
class MoveCellsExpressionVisitor
class NumberExpression
Class implementing a number with an optional unit.
class ObjectIdentifier
class OffsetCellsExpressionVisitor
class OperatorExpression
Class implementing an infix expression.
class Origin
Base class of all geometric document objects.
class OriginFeature
Plane Object Used to define planar support for all kind of operations in the document space.
class OriginGroupExtension
Represents an abstract placeable group of objects with an associated Origin.
class Part
Base class of all geometric document objects.
class Path
Base class of all geometric document objects.
class Placement
Placement Object Handles the repositioning of data.
class Plane
class Property
Base class of all properties This is the father of all properties.
class PropertyAcceleration
Acceleration property This is a property for representing acceleration.
class PropertyAngle
Angle property This is a property for representing angles.
class PropertyArea
Area property This is a property for representing areas.
class PropertyBool
Bool properties This is the father of all properties handling booleans.
class PropertyBoolList
Bool list properties.
struct PropertyCleaner
The PropertyCleaner struct Make deleting dynamic property safer by postponing its destruction.
class PropertyColor
Color properties This is the father of all properties handling colors.
class PropertyColorList
class PropertyComplexGeoData
The base class for all complex data properties.
class PropertyContainer
Base class of all classes with properties.
struct PropertyData
class PropertyDirection
class PropertyDistance
Distance property This is a property for representing distances.
class PropertyElectricPotential
ElectricPotential property This is a property for electric potentials.
class PropertyEnumeration
Property wrapper around an Enumeration object.
class PropertyExpressionContainer
class PropertyExpressionEngine
class PropertyFile
File properties This property holds a file name.
class PropertyFileIncluded
File include properties This property doesn't only save the file name like PropertyFile it also includes the file itself into the document.
class PropertyFloat
Float properties This is the father of all properties handling floats.
class PropertyFloatConstraint
Constraint float properties This property fulfills the need of a constraint float.
class PropertyFloatList
class PropertyFont
Property handling with font names.
class PropertyForce
Force property This is a property for representing acceleration.
class PropertyFrequency
Frequency property This is a property for representing frequency.
class PropertyGeometry
The base class for all basic geometry properties.
class PropertyInteger
Integer properties This is the father of all properties handling Integers.
class PropertyIntegerConstraint
Constraint integer properties This property fulfills the need of a constraint integer.
class PropertyIntegerList
Integer list properties.
class PropertyIntegerSet
Integer list properties.
class PropertyLength
Length property This is a property for representing lengths.
class PropertyLink
The general Link Property Main Purpose of this property is to Link Objects and Features in a document.
class PropertyLinkBase
Parent class of all link type properties.
class PropertyLinkChild
The general Link Property with Child scope.
class PropertyLinkGlobal
The general Link Property with Global scope.
class PropertyLinkHidden
The general Link Property that are hidden from dependency checking.
class PropertyLinkList
class PropertyLinkListBase
class PropertyLinkListChild
The general Link Property with Child scope.
class PropertyLinkListGlobal
The general Link Property with Global scope.
class PropertyLinkListHidden
The general Link Property that are hidden from dependency checking.
class PropertyLinkSub
the Link Property with sub elements This property links an object and a defined sequence of sub elements.
class PropertyLinkSubChild
The general Link Property with Child scope.
class PropertyLinkSubGlobal
The general Link Property with Global scope.
class PropertyLinkSubHidden
The general Link Property that are hidden from dependency checking.
class PropertyLinkSubList
class PropertyLinkSubListChild
The general Link Property with Child scope.
class PropertyLinkSubListGlobal
The general Link Property with Global scope.
class PropertyLinkSubListHidden
The general Link Property that are hidden from dependency checking.
class PropertyLinkT
The PropertyLinkT class is a helper class to create Python statements for property links.
class PropertyLists
Base class of all property lists.
class PropertyListsBase
Helper class to construct list like properties.
class PropertyListsT
Helper class to implement PropertyLists.
class PropertyMap
implements a key/value list as property The key ought to be ASCII the Value should be treated as UTF8 to be saved.
class PropertyMaterial
Material properties This is the father of all properties handling colors.
class PropertyMaterialList
Material properties.
class PropertyMatrix
Property representing a 4x4 matrix.
class PropertyPath
Path properties Properties handling file system paths.
class PropertyPercent
Percent property This property is a special integer property and holds only numbers between 0 and 100.
class PropertyPersistentObject
Property for dynamic creation of a FreeCAD persistent object.
class PropertyPlacement
Property representing a placement.
class PropertyPlacementLink
the general Link Property Main Purpose of this property is to Link Objects and Features in a document.
class PropertyPlacementList
class PropertyPosition
class PropertyPrecision
Precision properties This property fulfills the need of a floating value with many decimal points, e.g.
class PropertyPressure
Pressure property This is a property for representing acceleration.
class PropertyPythonObject
PropertyPythonObject is used to manage Py::Object instances as properties.
class PropertyQuantity
Float with Unit property This is a property for float with a predefined Unit associated.
class PropertyQuantityConstraint
Float with Unit property This is a property for float with a predefined Unit associated.
class PropertyRotation
Property representing a rotation.
class PropertySpeed
Speed property This is a property for representing speed.
class PropertyStiffness
Stiffness property This is a property for representing stiffness.
class PropertyString
String properties This is the father of all properties handling Strings.
class PropertyStringList
class PropertyUUID
UUID properties This property handles unique identifieers.
class PropertyVacuumPermittivity
VacuumPermittivity property This is a property for representing vacuum permittivity.
class PropertyVector
Vector properties This is the father of all properties handling Integers.
class PropertyVectorDistance
class PropertyVectorList
class PropertyVolume
Volume property This is a property for representing volumes.
class PropertyXLink
Link to an (sub)object in the same or different document.
class PropertyXLinkContainer
Abstract property that can link to multiple external objects.
class PropertyXLinkList
Link to one or more (sub)object(s) of one or more object(s) from the same or different document.
class PropertyXLinkSub
Link to one or more (sub)object from the same or different document.
class PropertyXLinkSubList
Link to one or more (sub)object(s) of one or more object(s) from the same or different document.
class PyObjectExpression
class Range
The Range class is a spreadsheet range iterator.
class RangeExpression
class RelabelDocumentExpressionVisitor
class RenameObjectIdentifierExpressionVisitor
The RenameObjectIdentifierExpressionVisitor class is a functor used to visit each node of an expression, and possibly rename VariableExpression nodes.
class ScopedLink
Enables scope handling for links This class is a base for all link properties and enables them to handle scopes of the linked objects.
class StringExpression
Class implementing a string.
class SubObjectT
class TextDocument
class Transaction
Represents a atomic transaction of the document.
class TransactionalObject
Base class of transactional objects.
class TransactionDocumentObject
Represents an entry for a document object in a transaction.
class TransactionFactory
class TransactionLocker
Helper class to lock a transaction from being closed or aborted.
class TransactionObject
Represents an entry for an object in a Transaction.
class TransactionProducer
class UnitExpression
Part of an expressions that contains a unit.
class UpdateElementReferenceExpressionVisitor
class ValueFloatToRGB
Abstract base class that calculates the matching RGB color to a given value.
class VariableExpression
Class implementing a reference to a property.
class VRMLObject
class WeakPtrT
The WeakPtrT class.
class XMLMergeReader
Typedefs
using any = boost::any
typedef std::shared_ptr< DocInfo > DocInfoPtr
typedef App::FeaturePythonT< DocumentObjectGroup > DocumentObjectGroupPython
typedef std::map< App::DocumentObject *, std::map< std::string, std::vector< ObjectIdentifier > > > ExpressionDeps
using ExpressionPtr = std::unique_ptr< Expression >
typedef ExtensionPythonT< App::Extension > ExtensionPython
typedef FeaturePythonT< DocumentObject > FeaturePython
typedef ExtensionPythonT< GroupExtensionPythonT< GeoFeatureGroupExtension > > GeoFeatureGroupExtensionPython
typedef FeaturePythonT< GeoFeature > GeometryPython
typedef ExtensionPythonT< GroupExtensionPythonT< GroupExtension > > GroupExtensionPython
typedef ExtensionPythonT< LinkBaseExtension > LinkBaseExtensionPython
typedef App::FeaturePythonT< LinkElement > LinkElementPython
typedef ExtensionPythonT< LinkExtension > LinkExtensionPython
typedef App::FeaturePythonT< LinkGroup > LinkGroupPython
typedef App::FeaturePythonT< Link > LinkPython
typedef App::FeaturePythonT< MaterialObject > MaterialObjectPython
typedef ExtensionPythonT< GroupExtensionPythonT< OriginGroupExtension > > OriginGroupExtensionPython
typedef App::FeaturePythonT< App::Placement > PlacementPython
using VisibilityFlags = Base::Flags< Visibility >
Enumerations
enum class ColorBarStyle { FLOW , ZERO_BASED }
enum GetLinkOption { GetLinkRecursive = 1 , GetLinkArrayElement = 2 , GetLinkedObject = 4 , GetLinkExternal = 8 }
enum class LinkScope { Local , Child , Global , Hidden }
Defines different scopes for which a link can be valid The scopes defined in this enum describe the different possibilities of where a link can point to.
enum ObjectStatus {
Touch = 0 , Error = 1 , New = 2 , Recompute = 3 ,
Restore = 4 , Remove = 5 , PythonCall = 6 , Destroy = 7 ,
Enforce = 8 , Recompute2 = 9 , PartialObject = 10 , PendingRecompute = 11 ,
ObjImporting = 13 , NoTouch = 14 , GeoExcluded = 15 , Expand = 16 ,
NoAutoExpand = 17 , PendingTransactionUpdate = 18 , RecomputeExtension = 19 , TouchOnColorChange = 20
}
enum PropertyType {
Prop_None = 0 , Prop_ReadOnly = 1 , Prop_Transient = 2 , Prop_Hidden = 4 ,
Prop_Output = 8 , Prop_NoRecompute = 16 , Prop_NoPersist = 32
}
enum class Visibility { Default , Grayed , Invisible }
Functions
template<class T >
T & any_cast (boost::any &value)
template<class T >
const T & any_cast (const boost::any &value)
static bool anyToDouble (double &res, const App::any &value)
static bool anyToLong (long &res, const App::any &value)
Quantity anyToQuantity (const App::any &value, const char *msg)
int decodeColumn (const std::string &colstr, bool silent=false)
Decode a column specification into a 0-based integer.
int decodeRow (const std::string &rowstr, bool silent=false)
Decode a row specification into a 0-based integer.
Expression * expressionFromPy (const DocumentObject *owner, const Py::Object &value)
App::Application & GetApplication (void)
Singleton getter of the Application.
const char * getNameFromFile (PyObject *value)
std::size_t hash_value (const App::ObjectIdentifier &path)
bool isAnyEqual (const App::any &v1, const App::any &v2)
bool isIOFile (PyObject *file)
Py::Object pyFromQuantity (const Quantity &quantity)
Py::Object pyObjectFromAny (const App::any &value)
App::any pyObjectToAny (Py::Object pyobj, bool check=true)
Helper function to convert Python object to/from App::any.
static Quantity pyToQuantity (const Py::Object &pyobj, const Expression *e, const char *msg=nullptr)
bool pyToQuantity (Quantity &q, const Py::Object &pyobj)
std::string quote (const std::string &input, bool toPython=false)
Quote input string according to quoting rules for an expression: because " and ' are used to designate inch and foot units, strings are quoted as <<string>>.
CellAddress stringToAddress (const char *strAddress, bool silent=false)
Convert a string address into integer row and column.
int validColumn (const std::string &colstr)
Determine whether a column specification is valid or not.
int validRow (const std::string &rowstr)
Determine whether a row specification is valid or not.
Detailed Description
The FreeCAD Application layer.
This namespace includes Application services of FreeCAD like:
The Application class
The Document class
Typedef Documentation
any
using App::any = typedef boost::any
DocInfoPtr
typedef std::shared_ptr<DocInfo> App::DocInfoPtr
DocumentObjectGroupPython
typedef App::FeaturePythonT<DocumentObjectGroup> App::DocumentObjectGroupPython
ExpressionDeps
typedef std::map<App::DocumentObject*, std::map<std::string, std::vector<ObjectIdentifier> > > App::ExpressionDeps
ExpressionPtr
typedef std::unique_ptr< Expression > App::ExpressionPtr
ExtensionPython
typedef ExtensionPythonT<App::Extension> App::ExtensionPython
FeaturePython
typedef FeaturePythonT<DocumentObject> App::FeaturePython
GeoFeatureGroupExtensionPython
typedef ExtensionPythonT<GroupExtensionPythonT<GeoFeatureGroupExtension> > App::GeoFeatureGroupExtensionPython
GeometryPython
typedef FeaturePythonT<GeoFeature > App::GeometryPython
GroupExtensionPython
typedef ExtensionPythonT<GroupExtensionPythonT<GroupExtension> > App::GroupExtensionPython
LinkBaseExtensionPython
typedef ExtensionPythonT<LinkBaseExtension> App::LinkBaseExtensionPython
LinkElementPython
typedef App::FeaturePythonT<LinkElement> App::LinkElementPython
LinkExtensionPython
typedef ExtensionPythonT<LinkExtension> App::LinkExtensionPython
LinkGroupPython
typedef App::FeaturePythonT<LinkGroup> App::LinkGroupPython
LinkPython
typedef App::FeaturePythonT<Link> App::LinkPython
MaterialObjectPython
typedef App::FeaturePythonT<MaterialObject> App::MaterialObjectPython
OriginGroupExtensionPython
typedef ExtensionPythonT<GroupExtensionPythonT<OriginGroupExtension> > App::OriginGroupExtensionPython
PlacementPython
typedef App::FeaturePythonT<App::Placement> App::PlacementPython
VisibilityFlags
using App::VisibilityFlags = typedef Base::Flags<Visibility>
Enumeration Type Documentation
ColorBarStyle
enum class App::ColorBarStyle strong
Enumerator
FLOW
ZERO_BASED
GetLinkOption
enum App::GetLinkOption
Enumerator
GetLinkRecursive
Get all links (both directly and in directly) linked to the given object.
GetLinkArrayElement
Get link array element instead of the array.
GetLinkedObject
Get linked object instead of the link, no effect if GetLinkRecursive.
GetLinkExternal
Get only external links, no effect if GetLinkRecursive.
LinkScope
enum class App::LinkScope strong
Defines different scopes for which a link can be valid The scopes defined in this enum describe the different possibilities of where a link can point to.
Local: links are valid only within the same GeoFeatureGroup as the linkowner is in or in none. Child: links are valid within the same or any sub GeoFeatureGroup Global: all possible links are valid Hidden: links are not included in dependency calculation
Enumerator
Local
Child
Global
Hidden
ObjectStatus
enum App::ObjectStatus
Enumerator
Touch
Error
New
Recompute
Restore
Remove
PythonCall
Destroy
Enforce
Recompute2
PartialObject
PendingRecompute
ObjImporting
NoTouch
GeoExcluded
Expand
NoAutoExpand
PendingTransactionUpdate
RecomputeExtension
TouchOnColorChange
PropertyType
enum App::PropertyType
Enumerator
Prop_None
No special property type
Prop_ReadOnly
Property is read-only in the editor
Prop_Transient
Property content won't be saved to file, but still saves name, type and status
Prop_Hidden
Property won't appear in the editor
Prop_Output
Modified property doesn't touch its parent container
Prop_NoRecompute
Modified property doesn't touch its container for recompute
Prop_NoPersist
Property won't be saved to file at all
Visibility
enum class App::Visibility strong
Enumerator
Default
Grayed
Invisible
Function Documentation
any_cast() [1/2]
template<class T > T & App::any_cast (boost::any & value)
any_cast() [2/2]
template<class T > const T & App::any_cast (const boost::any & value)
anyToDouble()
static bool App::anyToDouble (double & res, const App::any & value) static
Referenced by isAnyEqual().
anyToLong()
static bool App::anyToLong (long & res, const App::any & value) static
Referenced by isAnyEqual().
anyToQuantity()
Base::Quantity App::anyToQuantity (const App::any & value, const char * msg)
Referenced by isAnyEqual(), and App::PropertyQuantity::setPathValue().
decodeColumn()
int App::decodeColumn (const std::string & colstr, bool silent = false)
Decode a column specification into a 0-based integer.
Parameters
colstr Column specified as a string, with "A" begin the first column.
Returns
The column.
References validColumn().
Referenced by Spreadsheet::PropertyColumnWidths::Restore(), and stringToAddress().
decodeRow()
int App::decodeRow (const std::string & rowstr, bool silent = false)
Decode a row specification into a 0-based integer.
Parameters
rowstr Row specified as a string, with "1" being the first row.
Returns
The row.
References validRow().
Referenced by Spreadsheet::PropertyRowHeights::Restore(), and stringToAddress().
expressionFromPy()
Expression * App::expressionFromPy (const DocumentObject * owner, const Py::Object & value)
References pyToQuantity().
Referenced by App::Expression::eval().
GetApplication()
App::Application & App::GetApplication (void)
Singleton getter of the Application.
Referenced by Gui::Command::abortCommand(), App::Document::abortTransaction(), Gui::Dialog::DlgCheckableMessageBox::accept(), Gui::Dialog::DocumentRecovery::accept(), Gui::ElementColors::Private::accept(), DrawingGui::TaskDlgOrthoViews::accept(), MeshGui::Segmentation::accept(), MeshGui::SegmentationBestFit::accept(), MeshPartGui::Tessellation::accept(), PartGui::DlgBooleanOperation::accept(), PartGui::DlgFilletEdges::accept(), PartGui::DlgRevolution::accept(), PartGui::Mirroring::accept(), ReverseEngineeringGui::Segmentation::accept(), SpreadsheetGui::DlgBindSheet::accept(), Gui::Dialog::DlgAddProperty::accept(), Gui::Dialog::DlgRevertToBackupConfigImp::accept(), Gui::TaskCSysDragger::accept(), PartDesignGui::DlgActiveBody::accept(), App::TransactionLocker::activate(), PartDesignGui::Workbench::activated(), Gui::MacroCommand::activated(), StdCmdOpen::activated(), StdCmdImport::activated(), StdCmdExport::activated(), StdCmdMergeProjects::activated(), StdCmdDependencyGraph::activated(), StdCmdNew::activated(), StdCmdDuplicateSelection::activated(), StdCmdSelectAll::activated(), StdCmdDelete::activated(), StdCmdExpression::activated(), StdCmdLinkMakeGroup::activated(), StdCmdLinkMake::activated(), StdCmdLinkMakeRelative::activated(), StdCmdLinkImportAll::activated(), StdCmdOnlineHelpWebsite::activated(), StdCmdFreeCADDonation::activated(), StdCmdFreeCADWebsite::activated(), StdCmdFreeCADUserHub::activated(), StdCmdFreeCADPowerUserHub::activated(), StdCmdFreeCADForum::activated(), StdCmdFreeCADFAQ::activated(), StdCmdReportBug::activated(), StdCmdUserEditMode::activated(), StdCmdToggleSelectability::activated(), StdCmdViewHome::activated(), StdViewScreenShot::activated(), CmdViewMeasureToggleAll::activated(), Gui::StdCmdDownloadOnlineHelp::activated(), CmdSandboxMeshLoader::activated(), CmdSketcherConstrainHorizontal::activated(), CmdSketcherConstrainVertical::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainCoincident::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainPointOnObject::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), Gui::Application::activateWorkbench(), Gui::MainWindow::activateWorkbench(), App::DynamicProperty::addDynamicProperty(), PartGui::addLinearDimensions(), App::Document::addOrRemovePropertyOfObject(), App::Document::afterRestore(), TechDraw::DrawPage::AllowPageOverride(), TechDraw::Preferences::altDecimals(), Gui::RecentFilesAction::appendFile(), Gui::RecentMacrosAction::appendFile(), Gui::Application::Application(), Gui::ElementColors::Private::apply(), PartGui::DlgExtrusion::apply(), Gui::PreferencePack::apply(), Gui::ExpressionBinding::apply(), CmdSketcherConstrainLock::applyConstraint(), TechDraw::Preferences::ASMEGap(), PartDesignGui::ViewProviderDatumPoint::attach(), MeshGui::ViewProviderMeshOrientation::attach(), MeshGui::ViewProviderMeshNonManifolds::attach(), MeshGui::ViewProviderMeshNonManifoldPoints::attach(), MeshGui::ViewProviderMeshDuplicatedFaces::attach(), MeshGui::ViewProviderMeshDegenerations::attach(), MeshGui::ViewProviderMeshDuplicatedPoints::attach(), MeshGui::ViewProviderMeshIndices::attach(), MeshGui::ViewProviderMeshSelfIntersections::attach(), MeshGui::ViewProviderMeshFolds::attach(), RobotGui::ViewProviderTrajectory::attach(), App::DocInfo::attach(), App::AutoTransaction::AutoTransaction(), Gui::NS::AwaitingMoveState::AwaitingMoveState(), TechDraw::Preferences::balloonArrow(), TechDraw::Preferences::bitmapFill(), Part::Boolean::Boolean(), PartDesign::Boolean::Boolean(), PartGui::TaskMeasureLinear::buildDimension(), PartGui::TaskMeasureAngular::buildDimension(), PartDesignGui::TaskFeaturePick::buildFeatures(), TechDrawGui::PreferencesGui::centerColor(), App::Document::clearDocument(), App::AutoTransaction::close(), Gui::MainWindow::closeAllDocuments(), Gui::Dialog::DlgParameterImp::closeEvent(), Cloud::Module::cloudRestore(), Cloud::Module::cloudSave(), Gui::Command::commitCommand(), Gui::GUIApplication::commitData(), App::Document::commitTransaction(), Gui::MainWindow::confirmSave(), Sketcher::SketchObject::constraintsRenamed(), Gui::TreeWidget::contextMenuEvent(), StdCmdUserEditMode::createAction(), TechDrawGui::QGISVGTemplate::createClickHandles(), Gui::TreeWidgetEditDelegate::createEditor(), PartGui::ViewProvider2DObjectGrid::createGrid(), Gui::Workbench::createLinkMenu(), Fem::createObjectByType(), PartGui::DlgPrimitives::createPrimitive(), Gui::CreateViewStdCommands(), SketcherGui::CurveConverter::CurveConverter(), Gui::View3DInventor::customEvent(), ConstraintItem::data(), TechDraw::DrawViewDetail::debugDetail(), TechDraw::DrawViewSection::debugSection(), Gui::ViewProviderOrigin::defaultSize(), TechDraw::Preferences::defaultTemplate(), TechDraw::Preferences::defaultTemplateDir(), SketcherGui::ConstraintView::deleteSelectedItems(), SketcherGui::ElementView::deleteSelectedItems(), TechDrawGui::PreferencesGui::dimArrowSize(), TechDrawGui::PreferencesGui::dimArrowStyle(), TechDrawGui::PreferencesGui::dimColor(), TechDraw::Preferences::dimFontSizeMM(), Gui::Dialog::DlgAddProperty::DlgAddProperty(), SpreadsheetGui::DlgBindSheet::DlgBindSheet(), PartGui::DlgBooleanOperation::DlgBooleanOperation(), Gui::Dialog::DlgCustomActionsImp::DlgCustomActionsImp(), MeshGui::DlgEvaluateMeshImp::DlgEvaluateMeshImp(), Gui::Dialog::DlgExpressionInput::DlgExpressionInput(), PartGui::DlgFilletEdges::DlgFilletEdges(), Gui::Dialog::DlgParameterImp::DlgParameterImp(), PartGui::DlgProjectionOnSurface::DlgProjectionOnSurface(), PartGui::DlgSettings3DViewPart::DlgSettings3DViewPart(), Gui::Dialog::DlgSettingsMacroImp::DlgSettingsMacroImp(), Gui::SoFCUnifiedSelection::doAction(), Gui::Document::Document(), App::Document::Document(), Gui::DocumentItem::DocumentItem(), App::DocumentObserver::DocumentObserver(), Gui::DialogOptions::dontUseNativeColorDialog(), Gui::DialogOptions::dontUseNativeFileDialog(), FemGui::ViewProviderFemPostObject::doubleClicked(), PartDesignGui::ViewProviderBody::doubleClicked(), DraftUtils::DraftDxfRead::DraftDxfRead(), DrawingGui::DrawingView::DrawingView(), NaviCubeImplementation::drawNaviCube(), TechDraw::DrawPage::DrawPage(), TechDraw::DrawProjGroup::DrawProjGroup(), TechDrawGui::QGIViewPart::drawViewPart(), Gui::MainWindow::dropEvent(), Gui::TreeWidget::dropEvent(), TechDrawGui::PreferencesGui::edgeFuzz(), Gui::ElementColors::ElementColors(), PartGui::ensure3dDimensionVisible(), PartGui::ensureSomeDimensionVisible(), PartGui::evaluateAngularPreSelection(), PartGui::evaluateLinearPreSelection(), Gui::MainWindow::event(), Part::Boolean::execute(), Part::MultiCommon::execute(), Part::MultiFuse::execute(), Gui::GraphvizView::exportGraph(), App::Document::exportGraphviz(), Gui::SelectModule::exportHandler(), Import::ExportOCAF2::ExportOCAF2(), App::PropertyLinkBase::exportSubName(), Gui::Application::exportTo(), MeshGui::ViewProviderMesh::faceInfoCallback(), PartDesign::FeatureAddSub::FeatureAddSub(), FemGui::FemSettings::FemSettings(), PartGui::DlgExtrusion::findShapes(), PartGui::DlgFilletEdges::findShapes(), TechDraw::Preferences::formatSpec(), Gui::GestureNavigationStyle::GestureNavigationStyle(), Gui::NS::GestureState::GestureState(), App::DocInfo::get(), PartGui::DlgExtrusion::getAxisLink(), PartGui::DlgRevolution::getAxisLink(), TechDrawGui::QGSPage::getBackgroundColor(), TechDrawGui::QGVPage::getBackgroundColor(), Gui::ViewProviderGeometryObject::getBoundColor(), PathGui::ViewProviderPath::getBoundColor(), TechDrawGui::QGICenterLine::getCenterStyle(), TechDrawGui::TaskCenterLine::getCenterStyle(), Spreadsheet::Sheet::getCharsFromPrefs(), TechDrawGui::QGICMark::getCMarkColor(), SketcherGui::DrawSketchHandler::getCrosshairColor(), Path::Toolpath::getCycleTime(), Gui::WindowParameter::getDefaultParameter(), TechDraw::DrawLeaderLine::getDefAuto(), TechDraw::LineFormat::getDefEdgeStyle(), App::DocumentT::getDocument(), App::DocumentObjectT::getDocument(), Gui::Application::getDocument(), Gui::Command::getDocument(), Gui::SelectionSingleton::getDocument(), App::ObjectIdentifier::getDocument(), TechDrawGui::TaskCenterLine::getExtendBy(), PartDesignGui::TaskFeaturePick::getFeatures(), TechDrawGui::QGIEdge::getHiddenColor(), TechDrawGui::QGIEdge::getHiddenStyle(), Gui::View3DInventorViewer::getInternalTextureFormat(), App::LinkBaseExtension::getLink(), App::Document::getLinksTo(), TechDrawGui::QGICMark::getMarkFuzz(), TechDrawGui::QGVPage::getNavStyleParameter(), Gui::View3DInventorViewer::getNumSamples(), Gui::SelectionObject::getObject(), Fem::getObjectByType(), Gui::Command::getObjectCmd(), MeshGui::MeshSelection::getObjects(), TechDrawGui::Rez::getParameter(), TechDraw::DrawViewSection::getParameters(), TechDrawGui::QGIFace::getParameters(), TechDrawGui::ViewProviderViewSection::getParameters(), TechDrawGui::QGCustomText::getParmGroup(), TechDrawGui::QGIPrimPath::getParmGroup(), TechDrawGui::QGIView::getParmGroupCol(), TechDrawGui::QGIDatumLabel::getPrecision(), TechDraw::DrawViewDimension::getPrefix(), TechDrawGui::QGISectionLine::getPrefSectionStandard(), PartGui::getShapeFromStrings(), PartGui::DlgExtrusion::getShapesToExtrude(), PartGui::DlgRevolution::getShapesToRevolve(), Part::Feature::getSubObject(), PartDesign::SubShapeBinder::getSubObject(), TechDrawGui::QGITile::getSymbolFactor(), TechDrawGui::QGITile::getSymbolHeight(), TechDrawGui::QGITile::getSymbolWidth(), TechDrawGui::QGITile::getTileColor(), TechDrawGui::QGIDatumLabel::getTolAdjust(), TechDrawGui::QGTracker::getTrackerColor(), TechDrawGui::QGTracker::getTrackerWeight(), Gui::Command::getUniqueObjectName(), TechDraw::DrawPage::GlobalUpdateDrawings(), PartGui::TaskCheckGeometryResults::goCheck(), PartGui::goDimensionAngularNoTask(), Gui::GraphicsView3D::GraphicsView3D(), Gui::GraphvizView::GraphvizView(), TechDrawGui::PreferencesGui::gridColor(), TechDrawGui::PreferencesGui::gridSpacing(), TechDraw::DrawViewPart::handleFaces(), Gui::Command::hasPendingCommand(), ImageGui::ImageView::ImageView(), Gui::Application::importFrom(), Gui::SelectModule::importHandler(), Import::ImportOCAF2::ImportOCAF2(), ShapeCache::init(), TechDrawGui::QGVPage::Private::init(), Gui::Dialog::DlgPropertyLink::init(), App::DocInfo::init(), Gui::NavigationStyle::initialize(), TechDrawGui::QGVNavStyle::initialize(), Gui::MainWindow::insertFromMimeData(), Inspection::InspectActualShape::InspectActualShape(), Gui::BitmapFactoryInst::instance(), StdCmdExpression::isActive(), StdCmdSelectAll::isActive(), StdCmdLinkMakeGroup::isActive(), StdCmdLinkMake::isActive(), StdCmdLinkImportAll::isActive(), StdCmdLinkSelectAllLinks::isActive(), StdCmdSelectVisibleObjects::isActive(), StdCmdToggleObjects::isActive(), StdCmdShowObjects::isActive(), StdCmdHideObjects::isActive(), StdCmdMeasureDistance::isActive(), StdCmdCloseAllWindows::isActive(), Gui::ExpressionParameter::isCaseSensitive(), TechDraw::DrawUtil::isCrazy(), Gui::ExpressionParameter::isExactMatch(), TechDraw::Preferences::ISOGap(), PartDesignGui::TaskFeaturePick::isSingleSelectionEnabled(), Gui::PreferencePackManager::isVisible(), TechDraw::Preferences::keepPagesUpToDate(), TechDraw::Preferences::labelFont(), TechDraw::Preferences::labelFontSizeMM(), TechDrawGui::PreferencesGui::leaderColor(), TechDraw::Preferences::lineGroup(), TechDraw::Preferences::lineGroupFile(), Cloud::Module::LinkXSetValue(), Gui::MacroCommand::load(), Gui::Dialog::DlgWorkbenchesImp::load_disabled_workbenches(), Gui::Dialog::DlgWorkbenchesImp::load_enabled_workbenches(), SketcherGui::SketcherGeneralWidget::loadOrderingOrder(), PartGui::ViewProviderPartExt::loadParameter(), Gui::Dialog::DlgGeneralImp::loadSettings(), Gui::Dialog::DlgSettings3DViewImp::loadSettings(), Gui::Dialog::DlgSettingsLazyLoadedImp::loadSettings(), Gui::Dialog::DlgSettingsNavigation::loadSettings(), Gui::Dialog::DlgSettingsSelection::loadSettings(), Gui::Dialog::DlgSettingsUnitsImp::loadSettings(), FemGui::DlgSettingsFemCcxImp::loadSettings(), FemGui::DlgSettingsFemExportAbaqusImp::loadSettings(), FemGui::DlgSettingsFemInOutVtkImp::loadSettings(), FemGui::DlgSettingsFemZ88Imp::loadSettings(), InspectionGui::VisualInspection::loadSettings(), MeshGui::DlgSettingsImportExport::loadSettings(), PartGui::DlgImportExportIges::loadSettings(), PartGui::DlgImportExportStep::loadSettings(), SketcherGui::SketcherSettingsDisplay::loadSettings(), SpreadsheetGui::DlgSettingsImp::loadSettings(), StartGui::DlgStartPreferencesImp::loadSettings(), Gui::DockWindowManager::loadState(), Gui::MainWindow::loadUrls(), Gui::MacroManager::MacroManager(), Gui::MainWindow::MainWindow(), PartDesignGui::TaskFeaturePick::makeCopy(), TechDraw::Preferences::mattingStyle(), MeasureInfo::MeasureInfo(), Gui::DAG::Model::Model(), TechDrawGui::QGIRichAnno::mouseDoubleClickEvent(), TechDrawGui::QGIViewAnnotation::mouseDoubleClickEvent(), Part::MultiCommon::MultiCommon(), Part::MultiFuse::MultiFuse(), NaviCubeImplementation::NaviCubeImplementation(), TechDraw::Preferences::normalColor(), Gui::Dialog::DlgParameterImp::on_buttonSaveToDisk_clicked(), Gui::Dialog::DlgMacroExecuteImp::on_createButton_clicked(), MeshGui::DlgRegularSolidImp::on_createSolidButton_clicked(), Gui::Dialog::DlgMacroExecuteImp::on_duplicateButton_clicked(), Gui::Dialog::DlgMacroExecuteImp::on_renameButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairAllTogether_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairDegeneratedButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairDuplicatedFacesButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairDuplicatedPointsButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairFoldsButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairIndicesButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairNonmanifoldsButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairOrientationButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairSelfIntersectionButton_clicked(), Gui::Dialog::DlgMacroExecuteImp::on_toolbarButton_clicked(), SketcherGui::TaskSketcherConstraints::on_visibilityButton_trackingaction_changed(), PathGui::ViewProviderPath::onChanged(), PartDesignGui::ViewProviderSubShapeBinder::onChanged(), App::Document::onChanged(), Gui::Dialog::DlgParameterImp::onChangeParameterSet(), WebGui::BrowserView::onDownloadRequested(), Gui::TreeWidget::onReloadDoc(), Gui::GestureNavigationStyle::onRollGesture(), TechDrawGui::TaskDlgProjGroup::open(), Gui::TaskCSysDragger::open(), Gui::Application::open(), Gui::Command::openCommand(), Gui::PropertyEditor::PropertyEditor::openEditor(), App::Document::openTransaction(), DrawingGui::OrthoViews::OrthoViews(), App::PropertyXLink::Paste(), SpreadsheetGui::SheetTableView::pasteClipboard(), StdCmdExpression::pasteExpressions(), TechDraw::Preferences::patFile(), Gui::Dialog::Placement::Placement(), TechDraw::ShapeExtractor::prefAdd2d(), TechDrawGui::QGIPrimPath::prefCapStyle(), TechDraw::DrawViewSection::prefCutSurface(), TechDrawGui::QGIViewPart::prefFaceEdges(), TechDraw::DrawGeomHatch::prefGeomHatchColor(), TechDraw::DrawGeomHatch::prefGeomHatchName(), TechDraw::DrawViewPart::prefHardHid(), TechDraw::DrawViewPart::prefHardViz(), TechDrawGui::ViewProviderViewPart::prefHighlightColor(), TechDrawGui::ViewProviderViewPart::prefHighlightStyle(), TechDraw::DrawViewPart::prefIsoCount(), TechDraw::DrawViewPart::prefIsoHid(), TechDraw::DrawViewPart::prefIsoViz(), TechDraw::DrawViewBalloon::prefKinkLength(), TechDrawGui::QGIViewBalloon::prefOrthoPyramid(), TechDrawGui::QGIViewPart::prefPrintCenters(), TechDraw::DrawView::prefScale(), TechDraw::DrawView::prefScaleType(), TechDraw::DrawViewPart::prefSeamHid(), TechDraw::DrawViewPart::prefSeamViz(), TechDraw::DrawViewBalloon::prefShape(), TechDraw::DrawViewPart::prefSmoothHid(), TechDraw::DrawViewPart::prefSmoothViz(), TechDrawGui::ViewProviderDimension::prefStandardAndStyle(), TechDraw::DrawHatch::prefSvgHatchColor(), TechDrawGui::ViewProviderWeld::prefTileTextAdjust(), TechDraw::Preferences::preselectColor(), SketcherGui::DrawSketchHandlerLineSet::pressButton(), Gui::DocumentWeakPtrT::Private::Private(), TechDrawGui::QGVPage::Private::Private(), Gui::RecentFilesAction::Private::Private(), App::Application::processCmdLineFiles(), App::Application::processFiles(), TechDraw::Preferences::projectionAngle(), App::PropertyExpressionContainer::PropertyExpressionContainer(), Gui::PropertyView::PropertyView(), SketcherGui::DrawSketchHandlerBSpline::quit(), SketcherGui::DrawSketchHandlerLineSet::quit(), Fem::FemVTKTools::readResult(), App::Document::recompute(), Gui::Document::redo(), PartGui::refreshDimensions(), Gui::Dialog::DlgCheckableMessageBox::reject(), DrawingGui::TaskDlgOrthoViews::reject(), SketcherGui::TaskDlgEditSketch::reject(), DrawSketchHandlerBSplineInsertKnot::releaseButton(), SketcherGui::DrawSketchHandlerArc::releaseButton(), SketcherGui::DrawSketchHandler3PointArc::releaseButton(), SketcherGui::DrawSketchHandlerArcOfEllipse::releaseButton(), SketcherGui::DrawSketchHandlerCircle::releaseButton(), SketcherGui::DrawSketchHandler3PointCircle::releaseButton(), SketcherGui::DrawSketchHandlerEllipse::releaseButton(), SketcherGui::DrawSketchHandlerExtend::releaseButton(), SketcherGui::DrawSketchHandlerLine::releaseButton(), SketcherGui::DrawSketchHandlerLineSet::releaseButton(), SketcherGui::DrawSketchHandlerPoint::releaseButton(), SketcherGui::DrawSketchHandlerRegularPolygon::releaseButton(), SketcherGui::DrawSketchHandlerBox::releaseButton(), SketcherGui::DrawSketchHandlerOblong::releaseButton(), SketcherGui::DrawSketchHandlerSlot::releaseButton(), SketcherGui::DrawSketchHandlerArcOfHyperbola::releaseButton(), SketcherGui::DrawSketchHandlerArcOfParabola::releaseButton(), App::DynamicProperty::removeDynamicProperty(), Gui::Application::reopen(), Gui::ViewProviderDocumentObject::replaceObject(), Gui::ElementColors::Private::reset(), App::Document::restore(), TechDraw::CosmeticVertex::restoreCosmetic(), Part::PropertyPartShape::RestoreDocFile(), Gui::FileDialog::restoreLocation(), Gui::MDIView::restorePrinterSettings(), Gui::ToolBarManager::restoreState(), Gui::GraphvizWorker::run(), Sandbox::DocumentThread::run(), Sandbox::DocumentTestThread::run(), Gui::MacroManager::run(), Gui::Application::runApplication(), Gui::MacroCommand::save(), Gui::Document::Save(), App::Document::save(), Gui::Document::saveAll(), Gui::Document::saveAs(), Gui::Document::saveCopy(), Gui::Thumbnail::SaveDocFile(), Part::PropertyPartShape::SaveDocFile(), Gui::AutoSaver::saveDocument(), Gui::FileDialog::saveLocation(), SketcherGui::SketcherGeneralWidget::saveOrderingOrder(), MeshPartGui::Tessellation::saveParameters(), Gui::View3DInventorViewer::savePicture(), Gui::MDIView::savePrinterSettings(), Gui::Dialog::DlgGeneralImp::saveSettings(), Gui::Dialog::DlgSettings3DViewImp::saveSettings(), Gui::Dialog::DlgSettingsLazyLoadedImp::saveSettings(), Gui::Dialog::DlgSettingsNavigation::saveSettings(), Gui::Dialog::DlgSettingsSelection::saveSettings(), Gui::Dialog::DlgSettingsUnitsImp::saveSettings(), FemGui::DlgSettingsFemCcxImp::saveSettings(), FemGui::DlgSettingsFemExportAbaqusImp::saveSettings(), FemGui::DlgSettingsFemInOutVtkImp::saveSettings(), FemGui::DlgSettingsFemZ88Imp::saveSettings(), InspectionGui::VisualInspection::saveSettings(), MeshGui::DlgSettingsImportExport::saveSettings(), PartGui::DlgSettings3DViewPart::saveSettings(), PartGui::DlgImportExportIges::saveSettings(), PartGui::DlgImportExportStep::saveSettings(), SketcherGui::SketcherSettingsDisplay::saveSettings(), SpreadsheetGui::DlgSettingsImp::saveSettings(), StartGui::DlgStartPreferencesImp::saveSettings(), Gui::DockWindowManager::saveState(), Gui::ToolBarManager::saveState(), App::Document::saveToFile(), TechDrawGui::PreferencesGui::sectionLineColor(), TechDrawGui::PreferencesGui::sectionLineStyle(), Gui::TreeWidget::selectAll(), Gui::TreeWidget::selectAllLinks(), TechDraw::Preferences::selectColor(), Gui::SelectionSingleton::SelectionSingleton(), Gui::TreeWidget::selectLinkedObject(), Gui::SelectionSingleton::selStackPush(), App::DocumentObjectWeakPtrT::Private::set(), App::PropertyXLink::setAllowPartial(), Gui::QuantitySpinBox::setBoundToByName(), App::AutoTransaction::setEnable(), Gui::ExpressionBinding::setExpression(), Gui::WindowParameter::setGroupName(), Gui::DocumentObjectItem::setHighlight(), Import::ImpExpDxfRead::setOptions(), Import::ImpExpDxfWrite::setOptions(), Gui::StatefulLabel::setParameterGroup(), Gui::InputField::setParamGrpPath(), Gui::Dialog::DlgCheckableMessageBox::setPrefEntry(), PartDesignGui::TaskBoxPrimitives::setPrimitive(), Gui::Dialog::DlgCustomKeyboardImp::setShortcutOfCurrentAction(), Gui::DockWindowManager::setup(), Gui::MenuManager::setup(), Gui::ToolBarManager::setup(), Gui::StdWorkbench::setupDockWindows(), PartDesign::SubShapeBinder::setupObject(), Gui::AbstractSplitView::setupSettings(), PartDesignGui::TaskDressUpParameters::setupTransaction(), PartDesignGui::TaskTransformedParameters::setupTransaction(), App::PropertyString::setValue(), Gui::SelectionSingleton::setVisible(), Gui::Application::sGetMarkerIndex(), SpreadsheetGui::SheetModel::SheetModel(), Gui::TaskView::TaskWatcherCommandsEmptyDoc::shouldShow(), Gui::TaskView::TaskWatcherCommandsEmptySelection::shouldShow(), Gui::Dialog::DlgPreferencePackManagementImp::showAddonManager(), Gui::MainWindow::showDocumentation(), Gui::Dialog::DlgParameterImp::showEvent(), TechDrawGui::PreferencesGui::showGrid(), Gui::Dialog::DlgCheckableMessageBox::showMessage(), PartDesignGui::TaskHelixParameters::showPreview(), TechDraw::DrawViewSection::showSectionEdges(), Path::Area::showShape(), TechDraw::DrawViewDimension::showUnits(), Gui::Application::sInsert(), Gui::Application::sLoadFile(), PartDesignGui::ViewProviderBody::slotChangedObjectApp(), Gui::DocumentItem::slotInEdit(), Gui::Document::slotSkipRecompute(), Gui::Application::sOpen(), Gui::SplashObserver::SplashObserver(), MeshGui::ViewProviderMesh::splitMesh(), Gui::SplitView3DInventor::SplitView3DInventor(), Gui::Application::sReload(), MeshGui::MeshFillHole::startEditing(), Gui::MainWindow::startSplasher(), Gui::StatefulLabel::StatefulLabel(), StdCmdRefresh::StdCmdRefresh(), TechDraw::Preferences::svgFile(), App::LinkBaseExtension::syncCopyOnChange(), PartGui::TaskCheckGeometryDialog::TaskCheckGeometryDialog(), SketcherGui::TaskDlgEditSketch::TaskDlgEditSketch(), PartDesignGui::TaskDressUpParameters::TaskDressUpParameters(), PartDesignGui::TaskHoleParameters::TaskHoleParameters(), DrawingGui::TaskOrthoViews::TaskOrthoViews(), SketcherGui::TaskSketcherElements::TaskSketcherElements(), PartDesignGui::TaskTransformedParameters::TaskTransformedParameters(), Gui::TaskView::TaskView::TaskView(), MeshPartGui::Tessellation::Tessellation(), Gui::Dialog::TextureMapping::TextureMapping(), PartGui::toggle3d(), PartGui::toggleDelta(), Gui::PreferencePackManager::toggleVisibility(), PartDesign::Transformed::Transformed(), Gui::TreeParams::TreeParams(), SketcherGui::tryAutoRecompute(), Gui::Application::tryClose(), Gui::Document::undo(), PartDesign::SubShapeBinder::update(), InspectionGui::ViewProviderInspection::updateData(), SketcherGui::TaskSketcherSolverAdvanced::updateDefaultMethodParameters(), SketcherGui::TaskSketcherSolverAdvanced::updateRedundantMethodParameters(), TechDraw::Preferences::useGlobalDecimals(), Attacher::AttachEngine::verifyReferencesAreSafe(), TechDraw::Preferences::vertexColor(), TechDraw::Preferences::vertexScale(), Gui::View3DInventor::View3DInventor(), Gui::View3DInventorPy::viewDefaultOrientation(), Gui::ViewParams::ViewParams(), Gui::ViewProviderAnnotation::ViewProviderAnnotation(), FemGui::ViewProviderDataMarker::ViewProviderDataMarker(), PartDesignGui::ViewProviderDatum::ViewProviderDatum(), PartDesignGui::ViewProviderDatumCoordinateSystem::ViewProviderDatumCoordinateSystem(), Gui::ViewProviderGeometryObject::ViewProviderGeometryObject(), PartGui::ViewProviderPartExt::ViewProviderPartExt(), PathGui::ViewProviderPath::ViewProviderPath(), PartDesignGui::ViewProviderShapeBinder::ViewProviderShapeBinder(), Gui::ViewProviderTextDocument::ViewProviderTextDocument(), TechDrawGui::ViewProviderViewPart::ViewProviderViewPart(), InspectionGui::VisualInspection::VisualInspection(), Path::PathSegmentWalker::walk(), TechDrawGui::PreferencesGui::weldingDirectory(), SandboxGui::Workbench::Workbench(), Fem::FemMesh::write(), Fem::FemVTKTools::writeResult(), App::AutoTransaction::~AutoTransaction(), SketcherGui::CurveConverter::~CurveConverter(), MeshGui::DlgEvaluateMeshImp::~DlgEvaluateMeshImp(), NaviCubeImplementation::~NaviCubeImplementation(), and SketcherGui::TaskSketcherElements::~TaskSketcherElements().
getNameFromFile()
const char * App::getNameFromFile (PyObject * value)
Referenced by App::PropertyFileIncluded::setPyObject().
hash_value()
std::size_t App::hash_value (const App::ObjectIdentifier & path)
isAnyEqual()
bool App::isAnyEqual (const App::any & v1, const App::any & v2)
References anyToDouble(), anyToLong(), and anyToQuantity().
Referenced by App::PropertyExpressionEngine::execute().
isIOFile()
bool App::isIOFile (PyObject * file)
Referenced by App::PropertyFileIncluded::setPyObject().
pyFromQuantity()
Py::Object App::pyFromQuantity (const Quantity & quantity)
References Base::Quantity::getUnit(), Base::Quantity::getValue(), and Base::Unit::isEmpty().
Referenced by App::FunctionExpression::evalAggregate().
pyObjectFromAny()
Py::Object App::pyObjectFromAny (const App::any & value)
Referenced by App::PropertyEnumeration::setPathValue(), App::PropertyString::setPathValue(), Spreadsheet::PropertySheet::setPathValue(), and App::ObjectIdentifier::setValue().
pyObjectToAny()
App::any App::pyObjectToAny (Py::Object pyobj, bool check = true)
Helper function to convert Python object to/from App::any.
WARNING! Must hold Python global interpreter lock before calling these functions
Referenced by App::PropertyEnumeration::getPathValue(), App::ObjectIdentifier::getValue(), and App::Expression::getValueAsAny().
pyToQuantity() [1/2]
static Quantity App::pyToQuantity (const Py::Object & pyobj, const Expression * e, const char * msg = nullptr) static
References pyToQuantity().
pyToQuantity() [2/2]
bool App::pyToQuantity (Quantity & q, const Py::Object & pyobj)
Referenced by App::FunctionExpression::evalAggregate(), App::FunctionExpression::evaluate(), expressionFromPy(), and pyToQuantity().
quote()
std::string App::quote (const std::string & input, bool toPython = false)
Quote input string according to quoting rules for an expression: because " and ' are used to designate inch and foot units, strings are quoted as <<string>>.
Parameters
input
Returns
Referenced by SpreadsheetGui::DlgBindSheet::accept(), App::PropertyXLinkContainer::afterRestore(), and App::ObjectIdentifier::String::toString().
stringToAddress()
App::CellAddress App::stringToAddress (const char * strAddress, bool silent = false)
Convert a string address into integer row and column.
row and col are 0-based.
This function will throw an exception if the specified address is invalid.
Parameters
strAddress Address to parse.
References decodeColumn(), and decodeRow().
Referenced by SpreadsheetGui::DlgBindSheet::accept(), App::CellAddress::CellAddress(), Spreadsheet::PropertySheet::getCellAddress(), App::RangeExpression::getRange(), and App::CellAddress::parseAbsoluteAddress().
validColumn()
int App::validColumn (const std::string & colstr)
Determine whether a column specification is valid or not.
Parameters
colstr Column specified as a string, with "A" begin the first column.
Returns
0 or positive on success, -1 on error.
Referenced by decodeColumn(), and Spreadsheet::PropertySheet::isValidAlias().
validRow()
int App::validRow (const std::string & rowstr)
Determine whether a row specification is valid or not.
Parameters
rowstr Row specified as a string, with "1" being the first row.
Returns
0 or positive on success, -1 on error.
References App::CellAddress::MAX_ROWS.
Referenced by decodeRow(), and Spreadsheet::PropertySheet::isValidAlias().