FreeCAD: SMESH::Controls::ElementsOnShape Class Reference
SMESH::Controls::ElementsOnShape Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
ElementsOnShape ()
bool GetAllNodes () const
double GetTolerance () const
virtual SMDSAbs_ElementType GetType () const
virtual bool IsSatisfy (long theElementId)
void SetAllNodes (bool theAllNodes)
virtual void SetMesh (const SMDS_Mesh *theMesh)
void SetShape (const TopoDS_Shape &theShape, const SMDSAbs_ElementType theType)
void SetTolerance (const double theToler)
~ElementsOnShape ()
virtual SMDSAbs_ElementType GetType () const =0
virtual bool IsSatisfy (long theElementId)=0
Public Member Functions inherited from SMESH::Controls::Functor
virtual SMDSAbs_ElementType GetType () const =0
virtual void SetMesh (const SMDS_Mesh *theMesh)=0
virtual ~Functor ()
Constructor & Destructor Documentation
ElementsOnShape()
ElementsOnShape::ElementsOnShape ()
~ElementsOnShape()
ElementsOnShape::~ElementsOnShape ()
Member Function Documentation
GetAllNodes()
bool SMESH::Controls::ElementsOnShape::GetAllNodes () const
GetTolerance()
double ElementsOnShape::GetTolerance () const
GetType()
SMDSAbs_ElementType ElementsOnShape::GetType () const virtual
Implements SMESH::Controls::Predicate.
IsSatisfy()
bool ElementsOnShape::IsSatisfy (long theElementId) virtual
Implements SMESH::Controls::Predicate.
References SMESH::Controls::TMeshModifTracer::GetMesh(), SMDS_MeshElement::NbNodes(), and SMDS_MeshElement::nodesIterator().
SetAllNodes()
void ElementsOnShape::SetAllNodes (bool theAllNodes)
SetMesh()
void ElementsOnShape::SetMesh (const SMDS_Mesh * theMesh) virtual
Implements SMESH::Controls::Functor.
References SMESHUtils::FreeVector(), SMESH::Controls::TMeshModifTracer::IsMeshModified(), SMDS_Mesh::NbNodes(), and SMESH::Controls::TMeshModifTracer::SetMesh().
SetShape()
void ElementsOnShape::SetShape (const TopoDS_Shape & theShape, const SMDSAbs_ElementType theType)
References SMESHUtils::FreeVector().
Referenced by SetTolerance().
SetTolerance()
void ElementsOnShape::SetTolerance (const double theToler)
References SetShape().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp