FreeCAD: FemGui::TaskDlgFemConstraintBearing Class Reference
FemGui::TaskDlgFemConstraintBearing Class Reference
simulation dialog for the TaskView
#include <TaskFemConstraintBearing.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
TaskDlgFemConstraintBearing ()
TaskDlgFemConstraintBearing (ViewProviderFemConstraintBearing *ConstraintView)
Public Member Functions inherited from FemGui::TaskDlgFemConstraint
ViewProviderFemConstraint * getConstraintView () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
returns for Close and Help button
virtual bool isAllowedAlterDocument (void) const
void open ()
is called the TaskView when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
Public Member Functions inherited from Gui::TaskView::TaskDialog
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from FemGui::TaskDlgFemConstraint
ViewProviderFemConstraint * ConstraintView
TaskFemConstraint * parameter
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
simulation dialog for the TaskView
Constructor & Destructor Documentation
TaskDlgFemConstraintBearing() [1/2]
FemGui::TaskDlgFemConstraintBearing::TaskDlgFemConstraintBearing ()
TaskDlgFemConstraintBearing() [2/2]
TaskDlgFemConstraintBearing::TaskDlgFemConstraintBearing (ViewProviderFemConstraintBearing * ConstraintView)
References FemGui::TaskDlgFemConstraint::ConstraintView, Gui::TaskView::TaskDialog::Content, and FemGui::TaskDlgFemConstraint::parameter.
Member Function Documentation
accept()
bool TaskDlgFemConstraintBearing::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from FemGui::TaskDlgFemConstraint.
Reimplemented in FemGui::TaskDlgFemConstraintPulley, and FemGui::TaskDlgFemConstraintGear.
References FemGui::TaskDlgFemConstraint::accept(), FemGui::TaskDlgFemConstraint::ConstraintView, Gui::Command::Doc, FemGui::TaskFemConstraintBearing::getAxial(), FemGui::TaskFemConstraintBearing::getDistance(), FemGui::TaskFemConstraintBearing::getLocationName(), FemGui::TaskFemConstraintBearing::getLocationObject(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), and FemGui::TaskDlgFemConstraint::parameter.
Referenced by FemGui::TaskDlgFemConstraintGear::accept(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintBearing.h
Sources/FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintBearing.cpp