FreeCAD: femexamples.ccx_cantilever_faceload Namespace Reference
femexamples.ccx_cantilever_faceload Namespace Reference
Functions
def get_information ()
def init_doc (doc=None)
def setup (doc=None, solvertype="ccxtools")
def setup_cantileverbase (doc=None, solvertype="ccxtools")
Variables
string mesh_name = "Mesh"
Function Documentation
get_information()
def femexamples.ccx_cantilever_faceload.get_information ()
init_doc()
def femexamples.ccx_cantilever_faceload.init_doc (doc = None)
Referenced by femexamples.ccx_cantilever_faceload.setup_cantileverbase().
setup()
def femexamples.ccx_cantilever_faceload.setup (doc = None, solvertype = "ccxtools")
References ObjectsFem.makeConstraintForce(), and femexamples.ccx_cantilever_faceload.setup_cantileverbase().
setup_cantileverbase()
def femexamples.ccx_cantilever_faceload.setup_cantileverbase (doc = None, solvertype = "ccxtools")
References femexamples.ccx_cantilever_faceload.init_doc(), ObjectsFem.makeAnalysis(), ObjectsFem.makeConstraintFixed(), ObjectsFem.makeEquationElasticity(), ObjectsFem.makeMaterialSolid(), ObjectsFem.makeMeshGmsh(), ObjectsFem.makeSolverCalculix(), ObjectsFem.makeSolverCalculixCcxTools(), ObjectsFem.makeSolverElmer(), and ObjectsFem.makeSolverZ88().
Referenced by femexamples.ccx_cantilever_faceload.setup().
Variable Documentation
mesh_name
string femexamples.ccx_cantilever_faceload.mesh_name = "Mesh"