FreeCAD: Gui::ViewProviderPy Class Reference
Gui::ViewProviderPy Class Reference
The python export class for ViewProvider.
#include <ViewProviderPy.h>
Public Types
typedef ViewProvider * PointerType
Public Types inherited from App::ExtensionContainerPy
typedef ExtensionContainer * PointerType
Public Types inherited from App::PropertyContainerPy
typedef PropertyContainer * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
ViewProviderPy (ViewProvider *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from App::ExtensionContainerPy
ExtensionContainerPy (ExtensionContainer *pcObject, PyTypeObject *T=&Type)
int finalization ()
int initialization ()
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ExtensionContainer * getExtensionContainerPtr (void) const
getter for the object handled by this class
PyObject * addExtension (PyObject *args)
implementer for the addExtension() method
PyObject * hasExtension (PyObject *args)
implementer for the hasExtension() method
Public Member Functions inherited from App::PropertyContainerPy
PropertyContainerPy (PropertyContainer *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getPropertyByName (PyObject *args)
implementer for the getPropertyByName() method
PyObject * getPropertyTouchList (PyObject *args)
implementer for the getPropertyTouchList() method
PyObject * getTypeOfProperty (PyObject *args)
implementer for the getTypeOfProperty() method
PyObject * getTypeIdOfProperty (PyObject *args)
implementer for the getTypeIdOfProperty() method
PyObject * setEditorMode (PyObject *args)
implementer for the setEditorMode() method
PyObject * getEditorMode (PyObject *args)
implementer for the getEditorMode() method
PyObject * getGroupOfProperty (PyObject *args)
implementer for the getGroupOfProperty() method
PyObject * setPropertyStatus (PyObject *args)
implementer for the setPropertyStatus() method
PyObject * getPropertyStatus (PyObject *args)
implementer for the getPropertyStatus() method
PyObject * getDocumentationOfProperty (PyObject *args)
implementer for the getDocumentationOfProperty() method
PyObject * dumpPropertyContent (PyObject *args, PyObject *kwd)
implementer for the dumpPropertyContent() method
PyObject * restorePropertyContent (PyObject *args)
implementer for the restorePropertyContent() method
Py::List getPropertiesList (void) const
getter for the PropertiesList attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
PropertyContainer * getPropertyContainerPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::ExtensionContainerPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_addExtension (PyObject *self, PyObject *args)
callback for the addExtension() method
static PyObject * staticCallback_hasExtension (PyObject *self, PyObject *args)
callback for the hasExtension() method
Static Public Member Functions inherited from App::PropertyContainerPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_getPropertyByName (PyObject *self, PyObject *args)
callback for the getPropertyByName() method
static PyObject * staticCallback_getPropertyTouchList (PyObject *self, PyObject *args)
callback for the getPropertyTouchList() method
static PyObject * staticCallback_getTypeOfProperty (PyObject *self, PyObject *args)
callback for the getTypeOfProperty() method
static PyObject * staticCallback_getTypeIdOfProperty (PyObject *self, PyObject *args)
callback for the getTypeIdOfProperty() method
static PyObject * staticCallback_setEditorMode (PyObject *self, PyObject *args)
callback for the setEditorMode() method
static PyObject * staticCallback_getEditorMode (PyObject *self, PyObject *args)
callback for the getEditorMode() method
static PyObject * staticCallback_getGroupOfProperty (PyObject *self, PyObject *args)
callback for the getGroupOfProperty() method
static PyObject * staticCallback_setPropertyStatus (PyObject *self, PyObject *args)
callback for the setPropertyStatus() method
static PyObject * staticCallback_getPropertyStatus (PyObject *self, PyObject *args)
callback for the getPropertyStatus() method
static PyObject * staticCallback_getDocumentationOfProperty (PyObject *self, PyObject *args)
callback for the getDocumentationOfProperty() method
static PyObject * staticCallback_dumpPropertyContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpPropertyContent() method
static PyObject * staticCallback_restorePropertyContent (PyObject *self, PyObject *args)
callback for the restorePropertyContent() method
static PyObject * staticCallback_getPropertiesList (PyObject *self, void *closure)
getter callback for the PropertiesList attribute
static int staticCallback_setPropertiesList (PyObject *self, PyObject *value, void *closure)
setter callback for the PropertiesList attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of ViewProviderPy.
static PyMethodDef Methods []
Methods structure of ViewProviderPy.
static PyTypeObject Type
Type structure of ViewProviderPy.
Static Public Attributes inherited from App::ExtensionContainerPy
static PyGetSetDef GetterSetter []
Attribute structure of ExtensionContainerPy.
static PyMethodDef Methods []
Methods structure of ExtensionContainerPy.
static PyTypeObject Type
Type structure of ExtensionContainerPy.
Static Public Attributes inherited from App::PropertyContainerPy
static PyGetSetDef GetterSetter []
Attribute structure of PropertyContainerPy.
static PyMethodDef Methods []
Methods structure of PropertyContainerPy.
static PyTypeObject Type
Type structure of PropertyContainerPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~ViewProviderPy ()
Protected Member Functions inherited from App::ExtensionContainerPy
~ExtensionContainerPy ()
Protected Member Functions inherited from App::PropertyContainerPy
~PropertyContainerPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * addProperty (PyObject *args)
implementer for the addProperty() method
PyObject * removeProperty (PyObject *args)
implementer for the removeProperty() method
PyObject * supportedProperties (PyObject *args)
implementer for the supportedProperties() method
PyObject * show (PyObject *args)
implementer for the show() method
PyObject * hide (PyObject *args)
implementer for the hide() method
PyObject * isVisible (PyObject *args)
implementer for the isVisible() method
PyObject * canDragObject (PyObject *args)
implementer for the canDragObject() method
PyObject * dragObject (PyObject *args)
implementer for the dragObject() method
PyObject * canDropObject (PyObject *args)
implementer for the canDropObject() method
PyObject * dropObject (PyObject *args)
implementer for the dropObject() method
PyObject * canDragAndDropObject (PyObject *args)
implementer for the canDragAndDropObject() method
PyObject * replaceObject (PyObject *args)
implementer for the replaceObject() method
PyObject * doubleClicked (PyObject *args)
implementer for the doubleClicked() method
PyObject * addDisplayMode (PyObject *args)
implementer for the addDisplayMode() method
PyObject * listDisplayModes (PyObject *args)
implementer for the listDisplayModes() method
PyObject * toString (PyObject *args)
implementer for the toString() method
PyObject * setTransformation (PyObject *args)
implementer for the setTransformation() method
PyObject * claimChildren (PyObject *args)
implementer for the claimChildren() method
PyObject * partialRender (PyObject *args)
implementer for the partialRender() method
PyObject * getElementColors (PyObject *args)
implementer for the getElementColors() method
PyObject * setElementColors (PyObject *args)
implementer for the setElementColors() method
PyObject * getElementPicked (PyObject *args)
implementer for the getElementPicked() method
PyObject * getDetailPath (PyObject *args)
implementer for the getDetailPath() method
PyObject * signalChangeIcon (PyObject *args)
implementer for the signalChangeIcon() method
PyObject * getBoundingBox (PyObject *args)
implementer for the getBoundingBox() method
static PyObject * staticCallback_addProperty (PyObject *self, PyObject *args)
callback for the addProperty() method
static PyObject * staticCallback_removeProperty (PyObject *self, PyObject *args)
callback for the removeProperty() method
static PyObject * staticCallback_supportedProperties (PyObject *self, PyObject *args)
callback for the supportedProperties() method
static PyObject * staticCallback_show (PyObject *self, PyObject *args)
callback for the show() method
static PyObject * staticCallback_hide (PyObject *self, PyObject *args)
callback for the hide() method
static PyObject * staticCallback_isVisible (PyObject *self, PyObject *args)
callback for the isVisible() method
static PyObject * staticCallback_canDragObject (PyObject *self, PyObject *args)
callback for the canDragObject() method
static PyObject * staticCallback_dragObject (PyObject *self, PyObject *args)
callback for the dragObject() method
static PyObject * staticCallback_canDropObject (PyObject *self, PyObject *args)
callback for the canDropObject() method
static PyObject * staticCallback_dropObject (PyObject *self, PyObject *args)
callback for the dropObject() method
static PyObject * staticCallback_canDragAndDropObject (PyObject *self, PyObject *args)
callback for the canDragAndDropObject() method
static PyObject * staticCallback_replaceObject (PyObject *self, PyObject *args)
callback for the replaceObject() method
static PyObject * staticCallback_doubleClicked (PyObject *self, PyObject *args)
callback for the doubleClicked() method
static PyObject * staticCallback_addDisplayMode (PyObject *self, PyObject *args)
callback for the addDisplayMode() method
static PyObject * staticCallback_listDisplayModes (PyObject *self, PyObject *args)
callback for the listDisplayModes() method
static PyObject * staticCallback_toString (PyObject *self, PyObject *args)
callback for the toString() method
static PyObject * staticCallback_setTransformation (PyObject *self, PyObject *args)
callback for the setTransformation() method
static PyObject * staticCallback_claimChildren (PyObject *self, PyObject *args)
callback for the claimChildren() method
static PyObject * staticCallback_partialRender (PyObject *self, PyObject *args)
callback for the partialRender() method
static PyObject * staticCallback_getElementColors (PyObject *self, PyObject *args)
callback for the getElementColors() method
static PyObject * staticCallback_setElementColors (PyObject *self, PyObject *args)
callback for the setElementColors() method
static PyObject * staticCallback_getElementPicked (PyObject *self, PyObject *args)
callback for the getElementPicked() method
static PyObject * staticCallback_getDetailPath (PyObject *self, PyObject *args)
callback for the getDetailPath() method
static PyObject * staticCallback_signalChangeIcon (PyObject *self, PyObject *args)
callback for the signalChangeIcon() method
static PyObject * staticCallback_getBoundingBox (PyObject *self, PyObject *args)
callback for the getBoundingBox() method
callbacks and implementers for the python object attributes
Py::Object getAnnotation (void) const
getter for the Annotation attribute
void setAnnotation (Py::Object arg)
setter for the Annotation attribute
Py::Object getIcon (void) const
getter for the Icon attribute
Py::Object getRootNode (void) const
getter for the RootNode attribute
void setRootNode (Py::Object arg)
setter for the RootNode attribute
Py::Object getSwitchNode (void) const
getter for the SwitchNode attribute
void setSwitchNode (Py::Object arg)
setter for the SwitchNode attribute
Py::Int getDefaultMode (void) const
getter for the DefaultMode attribute
void setDefaultMode (Py::Int arg)
setter for the DefaultMode attribute
Py::String getIV (void) const
getter for the IV attribute
Py::Boolean getCanRemoveChildrenFromRoot (void) const
getter for the CanRemoveChildrenFromRoot attribute
Py::Boolean getLinkVisibility (void) const
getter for the LinkVisibility attribute
void setLinkVisibility (Py::Boolean arg)
setter for the LinkVisibility attribute
Py::String getDropPrefix (void) const
getter for the DropPrefix attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ViewProvider * getViewProviderPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getAnnotation (PyObject *self, void *closure)
getter callback for the Annotation attribute
static int staticCallback_setAnnotation (PyObject *self, PyObject *value, void *closure)
setter callback for the Annotation attribute
static PyObject * staticCallback_getIcon (PyObject *self, void *closure)
getter callback for the Icon attribute
static int staticCallback_setIcon (PyObject *self, PyObject *value, void *closure)
setter callback for the Icon attribute
static PyObject * staticCallback_getRootNode (PyObject *self, void *closure)
getter callback for the RootNode attribute
static int staticCallback_setRootNode (PyObject *self, PyObject *value, void *closure)
setter callback for the RootNode attribute
static PyObject * staticCallback_getSwitchNode (PyObject *self, void *closure)
getter callback for the SwitchNode attribute
static int staticCallback_setSwitchNode (PyObject *self, PyObject *value, void *closure)
setter callback for the SwitchNode attribute
static PyObject * staticCallback_getDefaultMode (PyObject *self, void *closure)
getter callback for the DefaultMode attribute
static int staticCallback_setDefaultMode (PyObject *self, PyObject *value, void *closure)
setter callback for the DefaultMode attribute
static PyObject * staticCallback_getIV (PyObject *self, void *closure)
getter callback for the IV attribute
static int staticCallback_setIV (PyObject *self, PyObject *value, void *closure)
setter callback for the IV attribute
static PyObject * staticCallback_getCanRemoveChildrenFromRoot (PyObject *self, void *closure)
getter callback for the CanRemoveChildrenFromRoot attribute
static int staticCallback_setCanRemoveChildrenFromRoot (PyObject *self, PyObject *value, void *closure)
setter callback for the CanRemoveChildrenFromRoot attribute
static PyObject * staticCallback_getLinkVisibility (PyObject *self, void *closure)
getter callback for the LinkVisibility attribute
static int staticCallback_setLinkVisibility (PyObject *self, PyObject *value, void *closure)
setter callback for the LinkVisibility attribute
static PyObject * staticCallback_getDropPrefix (PyObject *self, void *closure)
getter callback for the DropPrefix attribute
static int staticCallback_setDropPrefix (PyObject *self, PyObject *value, void *closure)
setter callback for the DropPrefix attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for ViewProvider.
Member Typedef Documentation
PointerType
typedef ViewProvider* Gui::ViewProviderPy::PointerType
Constructor & Destructor Documentation
~ViewProviderPy()
ViewProviderPy::~ViewProviderPy () protected
ViewProviderPy()
ViewProviderPy::ViewProviderPy (ViewProvider * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
addDisplayMode()
PyObject * ViewProviderPy::addDisplayMode (PyObject * args)
implementer for the addDisplayMode() method
References Gui::ViewProvider::addDisplayMaskMode(), Base::InterpreterSingleton::convertSWIGPointerObj(), getViewProviderPtr(), and Base::Interpreter().
Referenced by staticCallback_addDisplayMode().
addProperty()
PyObject * ViewProviderPy::addProperty (PyObject * args)
implementer for the addProperty() method
References App::PropertyContainer::addDynamicProperty(), Base::BaseExceptionFreeCADError, and getViewProviderPtr().
Referenced by DocumentObject.Box::init(), DocumentObject.DocumentObject::onChanged(), and staticCallback_addProperty().
canDragAndDropObject()
PyObject * ViewProviderPy::canDragAndDropObject (PyObject * args)
implementer for the canDragAndDropObject() method
References Gui::ViewProvider::canDragAndDropObject(), getViewProviderPtr(), and App::DocumentObjectPy::Type.
Referenced by staticCallback_canDragAndDropObject().
canDragObject()
PyObject * ViewProviderPy::canDragObject (PyObject * args)
implementer for the canDragObject() method
References Gui::ViewProvider::canDragObject(), Gui::ViewProvider::canDragObjects(), getViewProviderPtr(), and App::DocumentObjectPy::Type.
Referenced by staticCallback_canDragObject().
canDropObject()
PyObject * ViewProviderPy::canDropObject (PyObject * args)
implementer for the canDropObject() method
References Gui::ViewProvider::canDropObjectEx(), Gui::ViewProvider::canDropObjects(), App::PropertyListsT< T, ListT, ParentT >::getValues(), getViewProviderPtr(), App::PropertyListsT< T, ListT, ParentT >::setPyObject(), and App::DocumentObjectPy::Type.
Referenced by staticCallback_canDropObject().
claimChildren()
PyObject * ViewProviderPy::claimChildren (PyObject * args)
implementer for the claimChildren() method
References Gui::ViewProvider::claimChildren(), and getViewProviderPtr().
Referenced by femviewprovider.view_mesh_gmsh.VPMeshGmsh::onDelete(), femviewprovider.view_result_mechanical.VPResultMechanical::onDelete(), BOPTools.JoinFeatures.ViewProviderConnect::onDelete(), BOPTools.SplitFeatures.ViewProviderBooleanFragments::onDelete(), BOPTools.SplitFeatures.ViewProviderSlice::onDelete(), BOPTools.SplitFeatures.ViewProviderXOR::onDelete(), and staticCallback_claimChildren().
doubleClicked()
PyObject * ViewProviderPy::doubleClicked (PyObject * args)
implementer for the doubleClicked() method
References getViewProviderPtr().
Referenced by staticCallback_doubleClicked().
dragObject()
PyObject * ViewProviderPy::dragObject (PyObject * args)
implementer for the dragObject() method
References Gui::ViewProvider::dragObject(), getViewProviderPtr(), and App::DocumentObjectPy::Type.
Referenced by staticCallback_dragObject().
dropObject()
PyObject * ViewProviderPy::dropObject (PyObject * args)
implementer for the dropObject() method
References Gui::ViewProvider::dropObjectEx(), App::PropertyListsT< T, ListT, ParentT >::getValues(), getViewProviderPtr(), App::PropertyListsT< T, ListT, ParentT >::setPyObject(), and App::DocumentObjectPy::Type.
Referenced by staticCallback_dropObject().
getAnnotation()
Py::Object ViewProviderPy::getAnnotation (void) const
getter for the Annotation attribute
References Base::InterpreterSingleton::createSWIGPointerObj(), Gui::ViewProvider::getAnnotation(), getViewProviderPtr(), and Base::Interpreter().
Referenced by staticCallback_getAnnotation().
getBoundingBox()
PyObject * ViewProviderPy::getBoundingBox (PyObject * args)
implementer for the getBoundingBox() method
References Gui::ViewProvider::getBoundingBox(), and getViewProviderPtr().
Referenced by staticCallback_getBoundingBox().
getCanRemoveChildrenFromRoot()
Py::Boolean ViewProviderPy::getCanRemoveChildrenFromRoot (void) const
getter for the CanRemoveChildrenFromRoot attribute
References getViewProviderPtr().
Referenced by staticCallback_getCanRemoveChildrenFromRoot().
getCustomAttributes()
PyObject * ViewProviderPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
References App::PropertyContainer::getDynamicPropertyByName(), Base::BaseClass::getPyObject(), and getViewProviderPtr().
getDefaultMode()
Py::Int ViewProviderPy::getDefaultMode (void) const
getter for the DefaultMode attribute
References getViewProviderPtr().
Referenced by staticCallback_getDefaultMode().
getDetailPath()
PyObject * ViewProviderPy::getDetailPath (PyObject * args)
implementer for the getDetailPath() method
References Base::InterpreterSingleton::convertSWIGPointerObj(), Base::InterpreterSingleton::createSWIGPointerObj(), getViewProviderPtr(), and Base::Interpreter().
Referenced by staticCallback_getDetailPath().
getDropPrefix()
Py::String ViewProviderPy::getDropPrefix (void) const
getter for the DropPrefix attribute
References getViewProviderPtr().
Referenced by staticCallback_getDropPrefix().
getElementColors()
PyObject * ViewProviderPy::getElementColors (PyObject * args)
implementer for the getElementColors() method
References getViewProviderPtr().
Referenced by staticCallback_getElementColors().
getElementPicked()
PyObject * ViewProviderPy::getElementPicked (PyObject * args)
implementer for the getElementPicked() method
References Base::InterpreterSingleton::convertSWIGPointerObj(), getViewProviderPtr(), and Base::Interpreter().
Referenced by staticCallback_getElementPicked().
getIcon()
Py::Object ViewProviderPy::getIcon (void) const
getter for the Icon attribute
References Gui::PythonWrapper::fromQIcon(), Gui::ViewProvider::getIcon(), getViewProviderPtr(), Gui::PythonWrapper::loadGuiModule(), and Gui::PythonWrapper::loadWidgetsModule().
Referenced by staticCallback_getIcon(), ArchAxis.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), and ArchSectionPlane.SectionPlaneTaskPanel::update().
getIV()
Py::String ViewProviderPy::getIV (void) const
getter for the IV attribute
References getViewProviderPtr(), and Gui::SoFCDB::writeNodesToString().
Referenced by staticCallback_getIV().
getLinkVisibility()
Py::Boolean ViewProviderPy::getLinkVisibility (void) const
getter for the LinkVisibility attribute
References getViewProviderPtr().
Referenced by staticCallback_getLinkVisibility().
getRootNode()
Py::Object ViewProviderPy::getRootNode (void) const
getter for the RootNode attribute
References Base::InterpreterSingleton::createSWIGPointerObj(), Gui::ViewProvider::getRoot(), getViewProviderPtr(), and Base::Interpreter().
Referenced by staticCallback_getRootNode().
getSwitchNode()
Py::Object ViewProviderPy::getSwitchNode (void) const
getter for the SwitchNode attribute
References Base::InterpreterSingleton::createSWIGPointerObj(), Gui::ViewProvider::getModeSwitch(), getViewProviderPtr(), and Base::Interpreter().
Referenced by staticCallback_getSwitchNode().
GetType()
virtual PyTypeObject* Gui::ViewProviderPy::GetType (void) virtual
Reimplemented from App::ExtensionContainerPy.
Reimplemented in PartDesignGui::ViewProviderPy, MeshGui::ViewProviderMeshPy, FemGui::ViewProviderFemMeshPy, Gui::ViewProviderLinkPy, and Gui::ViewProviderDocumentObjectPy.
getViewProviderPtr()
ViewProvider * ViewProviderPy::getViewProviderPtr (void) const
getter for the object handled by this class
Referenced by addDisplayMode(), addProperty(), canDragAndDropObject(), canDragObject(), canDropObject(), claimChildren(), doubleClicked(), dragObject(), dropObject(), getAnnotation(), getBoundingBox(), getCanRemoveChildrenFromRoot(), getCustomAttributes(), getDefaultMode(), getDetailPath(), getDropPrefix(), getElementColors(), getElementPicked(), getIcon(), getIV(), getLinkVisibility(), getRootNode(), getSwitchNode(), hide(), isVisible(), listDisplayModes(), partialRender(), removeProperty(), replaceObject(), setCustomAttributes(), setDefaultMode(), Gui::DocumentPy::setEdit(), setElementColors(), setLinkVisibility(), setTransformation(), show(), signalChangeIcon(), and toString().
hide()
PyObject * ViewProviderPy::hide (PyObject * args)
implementer for the hide() method
References getViewProviderPtr(), and Gui::ViewProvider::hide().
Referenced by Mod.Show.mTempoVis.TempoVis::hide_all_dependencies(), Mod.Show.mTempoVis.TempoVis::hide_all_dependent(), and staticCallback_hide().
isVisible()
PyObject * ViewProviderPy::isVisible (PyObject * args)
implementer for the isVisible() method
References getViewProviderPtr().
Referenced by ArchVRM.Renderer::removeHidden(), and staticCallback_isVisible().
listDisplayModes()
PyObject * ViewProviderPy::listDisplayModes (PyObject * args)
implementer for the listDisplayModes() method
References Gui::ViewProvider::getDisplayModes(), and getViewProviderPtr().
Referenced by staticCallback_listDisplayModes().
partialRender()
PyObject * ViewProviderPy::partialRender (PyObject * args)
implementer for the partialRender() method
References getViewProviderPtr().
Referenced by staticCallback_partialRender().
PyInit()
int ViewProviderPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from App::ExtensionContainerPy.
Reimplemented in PartDesignGui::ViewProviderPy, MeshGui::ViewProviderMeshPy, FemGui::ViewProviderFemMeshPy, Gui::ViewProviderLinkPy, and Gui::ViewProviderDocumentObjectPy.
PyMake()
PyObject * ViewProviderPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
removeProperty()
PyObject * ViewProviderPy::removeProperty (PyObject * args)
implementer for the removeProperty() method
References getViewProviderPtr(), and App::PropertyContainer::removeDynamicProperty().
Referenced by staticCallback_removeProperty().
replaceObject()
PyObject * ViewProviderPy::replaceObject (PyObject * args)
implementer for the replaceObject() method
References getViewProviderPtr(), Gui::ViewProvider::replaceObject(), and App::DocumentObjectPy::Type.
Referenced by staticCallback_replaceObject().
representation()
std::string ViewProviderPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setAnnotation()
void ViewProviderPy::setAnnotation (Py::Object arg)
setter for the Annotation attribute
Referenced by staticCallback_setAnnotation().
setCustomAttributes()
int ViewProviderPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
References App::PropertyContainer::getDynamicPropertyByName(), getViewProviderPtr(), Base::BaseClass::setPyObject(), and Base::Exception::what().
setDefaultMode()
void ViewProviderPy::setDefaultMode (Py::Int arg)
setter for the DefaultMode attribute
References getViewProviderPtr(), and Gui::ViewProvider::setDefaultMode().
Referenced by staticCallback_setDefaultMode().
setElementColors()
PyObject * ViewProviderPy::setElementColors (PyObject * args)
implementer for the setElementColors() method
References App::PropertyColor::getValue(), getViewProviderPtr(), Gui::ViewProvider::setElementColors(), and App::PropertyColor::setPyObject().
Referenced by staticCallback_setElementColors().
setLinkVisibility()
void ViewProviderPy::setLinkVisibility (Py::Boolean arg)
setter for the LinkVisibility attribute
References getViewProviderPtr(), and Gui::ViewProvider::setLinkVisible().
Referenced by staticCallback_setLinkVisibility().
setRootNode()
void ViewProviderPy::setRootNode (Py::Object arg)
setter for the RootNode attribute
Referenced by staticCallback_setRootNode().
setSwitchNode()
void ViewProviderPy::setSwitchNode (Py::Object arg)
setter for the SwitchNode attribute
Referenced by staticCallback_setSwitchNode().
setTransformation()
PyObject * ViewProviderPy::setTransformation (PyObject * args)
implementer for the setTransformation() method
References Base::BaseExceptionFreeCADError, Base::PlacementPy::getPlacementPtr(), getViewProviderPtr(), Gui::ViewProvider::setTransformation(), Base::Placement::toMatrix(), Base::MatrixPy::Type, and Base::PlacementPy::Type.
Referenced by staticCallback_setTransformation().
show()
PyObject * ViewProviderPy::show (PyObject * args)
implementer for the show() method
References getViewProviderPtr(), and Gui::ViewProvider::show().
Referenced by Mod.Show.mTempoVis.TempoVis::show_all_dependencies(), Mod.Show.mTempoVis.TempoVis::show_all_dependent(), and staticCallback_show().
signalChangeIcon()
PyObject * ViewProviderPy::signalChangeIcon (PyObject * args)
implementer for the signalChangeIcon() method
References getViewProviderPtr(), and Gui::ViewProvider::signalChangeIcon.
Referenced by staticCallback_signalChangeIcon().
staticCallback_addDisplayMode()
PyObject * ViewProviderPy::staticCallback_addDisplayMode (PyObject * self, PyObject * args) static
callback for the addDisplayMode() method
References addDisplayMode(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addProperty()
PyObject * ViewProviderPy::staticCallback_addProperty (PyObject * self, PyObject * args) static
callback for the addProperty() method
References addProperty(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_canDragAndDropObject()
PyObject * ViewProviderPy::staticCallback_canDragAndDropObject (PyObject * self, PyObject * args) static
callback for the canDragAndDropObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, canDragAndDropObject(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_canDragObject()
PyObject * ViewProviderPy::staticCallback_canDragObject (PyObject * self, PyObject * args) static
callback for the canDragObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, canDragObject(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_canDropObject()
PyObject * ViewProviderPy::staticCallback_canDropObject (PyObject * self, PyObject * args) static
callback for the canDropObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, canDropObject(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_claimChildren()
PyObject * ViewProviderPy::staticCallback_claimChildren (PyObject * self, PyObject * args) static
callback for the claimChildren() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, claimChildren(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_doubleClicked()
PyObject * ViewProviderPy::staticCallback_doubleClicked (PyObject * self, PyObject * args) static
callback for the doubleClicked() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, doubleClicked(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_dragObject()
PyObject * ViewProviderPy::staticCallback_dragObject (PyObject * self, PyObject * args) static
callback for the dragObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, dragObject(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_dropObject()
PyObject * ViewProviderPy::staticCallback_dropObject (PyObject * self, PyObject * args) static
callback for the dropObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, dropObject(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getAnnotation()
PyObject * ViewProviderPy::staticCallback_getAnnotation (PyObject * self, void * closure) static
getter callback for the Annotation attribute
References Base::BaseExceptionFreeCADError, getAnnotation(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getBoundingBox()
PyObject * ViewProviderPy::staticCallback_getBoundingBox (PyObject * self, PyObject * args) static
callback for the getBoundingBox() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getBoundingBox(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getCanRemoveChildrenFromRoot()
PyObject * ViewProviderPy::staticCallback_getCanRemoveChildrenFromRoot (PyObject * self, void * closure) static
getter callback for the CanRemoveChildrenFromRoot attribute
References Base::BaseExceptionFreeCADError, getCanRemoveChildrenFromRoot(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getDefaultMode()
PyObject * ViewProviderPy::staticCallback_getDefaultMode (PyObject * self, void * closure) static
getter callback for the DefaultMode attribute
References Base::BaseExceptionFreeCADError, getDefaultMode(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getDetailPath()
PyObject * ViewProviderPy::staticCallback_getDetailPath (PyObject * self, PyObject * args) static
callback for the getDetailPath() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getDetailPath(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getDropPrefix()
PyObject * ViewProviderPy::staticCallback_getDropPrefix (PyObject * self, void * closure) static
getter callback for the DropPrefix attribute
References Base::BaseExceptionFreeCADError, getDropPrefix(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getElementColors()
PyObject * ViewProviderPy::staticCallback_getElementColors (PyObject * self, PyObject * args) static
callback for the getElementColors() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getElementColors(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getElementPicked()
PyObject * ViewProviderPy::staticCallback_getElementPicked (PyObject * self, PyObject * args) static
callback for the getElementPicked() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getElementPicked(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getIcon()
PyObject * ViewProviderPy::staticCallback_getIcon (PyObject * self, void * closure) static
getter callback for the Icon attribute
References Base::BaseExceptionFreeCADError, getIcon(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getIV()
PyObject * ViewProviderPy::staticCallback_getIV (PyObject * self, void * closure) static
getter callback for the IV attribute
References Base::BaseExceptionFreeCADError, getIV(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getLinkVisibility()
PyObject * ViewProviderPy::staticCallback_getLinkVisibility (PyObject * self, void * closure) static
getter callback for the LinkVisibility attribute
References Base::BaseExceptionFreeCADError, getLinkVisibility(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRootNode()
PyObject * ViewProviderPy::staticCallback_getRootNode (PyObject * self, void * closure) static
getter callback for the RootNode attribute
References Base::BaseExceptionFreeCADError, getRootNode(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSwitchNode()
PyObject * ViewProviderPy::staticCallback_getSwitchNode (PyObject * self, void * closure) static
getter callback for the SwitchNode attribute
References Base::BaseExceptionFreeCADError, getSwitchNode(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_hide()
PyObject * ViewProviderPy::staticCallback_hide (PyObject * self, PyObject * args) static
callback for the hide() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hide(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_isVisible()
PyObject * ViewProviderPy::staticCallback_isVisible (PyObject * self, PyObject * args) static
callback for the isVisible() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), isVisible(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_listDisplayModes()
PyObject * ViewProviderPy::staticCallback_listDisplayModes (PyObject * self, PyObject * args) static
callback for the listDisplayModes() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), listDisplayModes(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_partialRender()
PyObject * ViewProviderPy::staticCallback_partialRender (PyObject * self, PyObject * args) static
callback for the partialRender() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), partialRender(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_removeProperty()
PyObject * ViewProviderPy::staticCallback_removeProperty (PyObject * self, PyObject * args) static
callback for the removeProperty() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeProperty(), and Base::PyObjectBase::startNotify().
staticCallback_replaceObject()
PyObject * ViewProviderPy::staticCallback_replaceObject (PyObject * self, PyObject * args) static
callback for the replaceObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), replaceObject(), and Base::PyObjectBase::startNotify().
staticCallback_setAnnotation()
int ViewProviderPy::staticCallback_setAnnotation (PyObject * self, PyObject * value, void * closure) static
setter callback for the Annotation attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setAnnotation().
staticCallback_setCanRemoveChildrenFromRoot()
int ViewProviderPy::staticCallback_setCanRemoveChildrenFromRoot (PyObject * self, PyObject * value, void * closure) static
setter callback for the CanRemoveChildrenFromRoot attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setDefaultMode()
int ViewProviderPy::staticCallback_setDefaultMode (PyObject * self, PyObject * value, void * closure) static
setter callback for the DefaultMode attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setDefaultMode().
staticCallback_setDropPrefix()
int ViewProviderPy::staticCallback_setDropPrefix (PyObject * self, PyObject * value, void * closure) static
setter callback for the DropPrefix attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setElementColors()
PyObject * ViewProviderPy::staticCallback_setElementColors (PyObject * self, PyObject * args) static
callback for the setElementColors() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setElementColors(), and Base::PyObjectBase::startNotify().
staticCallback_setIcon()
int ViewProviderPy::staticCallback_setIcon (PyObject * self, PyObject * value, void * closure) static
setter callback for the Icon attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setIV()
int ViewProviderPy::staticCallback_setIV (PyObject * self, PyObject * value, void * closure) static
setter callback for the IV attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setLinkVisibility()
int ViewProviderPy::staticCallback_setLinkVisibility (PyObject * self, PyObject * value, void * closure) static
setter callback for the LinkVisibility attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setLinkVisibility().
staticCallback_setRootNode()
int ViewProviderPy::staticCallback_setRootNode (PyObject * self, PyObject * value, void * closure) static
setter callback for the RootNode attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setRootNode().
staticCallback_setSwitchNode()
int ViewProviderPy::staticCallback_setSwitchNode (PyObject * self, PyObject * value, void * closure) static
setter callback for the SwitchNode attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setSwitchNode().
staticCallback_setTransformation()
PyObject * ViewProviderPy::staticCallback_setTransformation (PyObject * self, PyObject * args) static
callback for the setTransformation() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setTransformation(), and Base::PyObjectBase::startNotify().
staticCallback_show()
PyObject * ViewProviderPy::staticCallback_show (PyObject * self, PyObject * args) static
callback for the show() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), show(), and Base::PyObjectBase::startNotify().
staticCallback_signalChangeIcon()
PyObject * ViewProviderPy::staticCallback_signalChangeIcon (PyObject * self, PyObject * args) static
callback for the signalChangeIcon() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and signalChangeIcon().
staticCallback_supportedProperties()
PyObject * ViewProviderPy::staticCallback_supportedProperties (PyObject * self, PyObject * args) static
callback for the supportedProperties() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and supportedProperties().
staticCallback_toString()
PyObject * ViewProviderPy::staticCallback_toString (PyObject * self, PyObject * args) static
callback for the toString() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and toString().
supportedProperties()
PyObject * ViewProviderPy::supportedProperties (PyObject * args)
implementer for the supportedProperties() method
References Base::Type::getAllDerivedFrom(), and Base::Persistence::getClassTypeId().
Referenced by staticCallback_supportedProperties().
toString()
PyObject * ViewProviderPy::toString (PyObject * args)
implementer for the toString() method
References getViewProviderPtr(), and Gui::ViewProvider::toString().
Referenced by staticCallback_toString().
Member Data Documentation
GetterSetter
PyGetSetDef ViewProviderPy::GetterSetter static
Attribute structure of ViewProviderPy.
Methods
PyMethodDef ViewProviderPy::Methods static
Methods structure of ViewProviderPy.
Type
PyTypeObject ViewProviderPy::Type static
Type structure of ViewProviderPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), Gui::Application::Application(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), Gui::DocumentPy::setEdit(), ArchReference.ArchReference::setProperties(), and Gui::DocumentPy::toggleInSceneGraph().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Gui/ViewProviderPy.h
Sources/FreeCAD/src/Gui/ViewProviderPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Gui/ViewProviderPy.cpp