FreeCAD: Gui::WorkbenchComboBox Class Reference
Gui::WorkbenchComboBox Class Reference
#include <Action.h>
Public Slots
void onActivated (int)
void onActivated (QAction *)
Public Member Functions
void showPopup ()
WorkbenchComboBox (WorkbenchGroup *wb, QWidget *parent=0)
virtual ~WorkbenchComboBox ()
Protected Slots
void onWorkbenchActivated (const QString &)
Protected Member Functions
void actionEvent (QActionEvent *)
Constructor & Destructor Documentation
WorkbenchComboBox()
WorkbenchComboBox::WorkbenchComboBox (WorkbenchGroup * wb, QWidget * parent = 0)
References draftgeoutils.intersections::connect(), Gui::getMainWindow(), onActivated(), and onWorkbenchActivated().
~WorkbenchComboBox()
WorkbenchComboBox::~WorkbenchComboBox () virtual
Member Function Documentation
actionEvent()
void WorkbenchComboBox::actionEvent (QActionEvent * e) protected
onActivated [1/2]
void WorkbenchComboBox::onActivated (int i) slot
Referenced by WorkbenchComboBox().
onActivated [2/2]
void WorkbenchComboBox::onActivated (QAction * action) slot
onWorkbenchActivated
void WorkbenchComboBox::onWorkbenchActivated (const QString & name) protected slot
Referenced by WorkbenchComboBox().
showPopup()
void WorkbenchComboBox::showPopup ()
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Action.h
Sources/FreeCAD/src/Gui/Action.cpp