FreeCAD: PartGui::ShapeBuilderWidget Class Reference
PartGui::ShapeBuilderWidget Class Reference
#include <TaskShapeBuilder.h>
Classes
class Private
Public Member Functions
bool accept ()
bool reject ()
ShapeBuilderWidget (QWidget *parent=nullptr)
~ShapeBuilderWidget ()
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Constructor & Destructor Documentation
ShapeBuilderWidget()
ShapeBuilderWidget::ShapeBuilderWidget (QWidget * parent = nullptr)
References Gui::SelectionSingleton::addSelectionGate(), PartGui::ShapeBuilderWidget::Private::bg, draftgeoutils.intersections::connect(), PartGui::ShapeBuilderWidget::Private::gate, PartGui::Ui_TaskShapeBuilder::label, PartGui::Ui_TaskShapeBuilder::radioButtonEdgeFromVertex, PartGui::Ui_TaskShapeBuilder::radioButtonFaceFromEdge, PartGui::Ui_TaskShapeBuilder::radioButtonFaceFromVertex, PartGui::Ui_TaskShapeBuilder::radioButtonShellFromFace, PartGui::Ui_TaskShapeBuilder::radioButtonSolidFromShell, PartGui::Ui_TaskShapeBuilder::radioButtonWireFromEdge, Gui::Selection(), PartGui::Ui_TaskShapeBuilder::setupUi(), and PartGui::ShapeBuilderWidget::Private::ui.
~ShapeBuilderWidget()
ShapeBuilderWidget::~ShapeBuilderWidget ()
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
accept()
bool ShapeBuilderWidget::accept (void)
Referenced by PartGui::TaskShapeBuilder::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
reject()
bool ShapeBuilderWidget::reject (void)
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), PartGui::TaskShapeBuilder::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/TaskShapeBuilder.h
FreeCAD/src/Mod/Part/Gui/TaskShapeBuilder.cpp