FreeCAD: Part::AttachExtensionPy Class Reference
Part::AttachExtensionPy Class Reference
The python export class for AttachExtension.
#include <AttachExtensionPy.h>
Public Types
typedef AttachExtension * PointerType
Public Types inherited from App::DocumentObjectExtensionPy
typedef DocumentObjectExtension * PointerType
Public Types inherited from App::ExtensionPy
typedef Extension * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
AttachExtensionPy (AttachExtension *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from App::DocumentObjectExtensionPy
DocumentObjectExtensionPy (DocumentObjectExtension *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
DocumentObjectExtension * getDocumentObjectExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from App::ExtensionPy
ExtensionPy (Extension *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Extension * getExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::DocumentObjectExtensionPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::ExtensionPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of AttachExtensionPy.
static PyMethodDef Methods []
Methods structure of AttachExtensionPy.
static PyTypeObject Type
Type structure of AttachExtensionPy.
Static Public Attributes inherited from App::DocumentObjectExtensionPy
static PyGetSetDef GetterSetter []
Attribute structure of DocumentObjectExtensionPy.
static PyMethodDef Methods []
Methods structure of DocumentObjectExtensionPy.
static PyTypeObject Type
Type structure of DocumentObjectExtensionPy.
Static Public Attributes inherited from App::ExtensionPy
static PyGetSetDef GetterSetter []
Attribute structure of ExtensionPy.
static PyMethodDef Methods []
Methods structure of ExtensionPy.
static PyTypeObject Type
Type structure of ExtensionPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~AttachExtensionPy ()
Protected Member Functions inherited from App::DocumentObjectExtensionPy
~DocumentObjectExtensionPy ()
Protected Member Functions inherited from App::ExtensionPy
~ExtensionPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * positionBySupport (PyObject *args)
implementer for the positionBySupport() method
PyObject * changeAttacherType (PyObject *args)
implementer for the changeAttacherType() method
static PyObject * staticCallback_positionBySupport (PyObject *self, PyObject *args)
callback for the positionBySupport() method
static PyObject * staticCallback_changeAttacherType (PyObject *self, PyObject *args)
callback for the changeAttacherType() method
callbacks and implementers for the python object attributes
Py::Object getAttacher (void) const
getter for the Attacher attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
AttachExtension * getAttachExtensionPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getAttacher (PyObject *self, void *closure)
getter callback for the Attacher attribute
static int staticCallback_setAttacher (PyObject *self, PyObject *value, void *closure)
setter callback for the Attacher attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for AttachExtension.
Member Typedef Documentation
PointerType
typedef AttachExtension* Part::AttachExtensionPy::PointerType
Constructor & Destructor Documentation
~AttachExtensionPy()
AttachExtensionPy::~AttachExtensionPy () protected
AttachExtensionPy()
AttachExtensionPy::AttachExtensionPy (AttachExtension * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
changeAttacherType()
PyObject * AttachExtensionPy::changeAttacherType (PyObject * args)
implementer for the changeAttacherType() method
References Base::BaseExceptionFreeCADError, Part::AttachExtension::changeAttacherType(), getAttachExtensionPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_changeAttacherType().
getAttacher()
Py::Object AttachExtensionPy::getAttacher (void) const
getter for the Attacher attribute
References Part::AttachExtension::attacher(), Base::BaseExceptionFreeCADError, getAttachExtensionPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getAttacher().
getAttachExtensionPtr()
AttachExtension * AttachExtensionPy::getAttachExtensionPtr (void) const
getter for the object handled by this class
Referenced by changeAttacherType(), getAttacher(), and positionBySupport().
getCustomAttributes()
PyObject * AttachExtensionPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
GetType()
virtual PyTypeObject* Part::AttachExtensionPy::GetType (void) virtual
Reimplemented from App::DocumentObjectExtensionPy.
positionBySupport()
PyObject * AttachExtensionPy::positionBySupport (PyObject * args)
implementer for the positionBySupport() method
References Base::BaseExceptionFreeCADError, getAttachExtensionPtr(), Part::PartExceptionOCCError, and Part::AttachExtension::positionBySupport().
Referenced by staticCallback_positionBySupport().
PyInit()
int AttachExtensionPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from App::DocumentObjectExtensionPy.
PyMake()
PyObject * AttachExtensionPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string AttachExtensionPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int AttachExtensionPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_changeAttacherType()
PyObject * AttachExtensionPy::staticCallback_changeAttacherType (PyObject * self, PyObject * args) static
callback for the changeAttacherType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, changeAttacherType(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getAttacher()
PyObject * AttachExtensionPy::staticCallback_getAttacher (PyObject * self, void * closure) static
getter callback for the Attacher attribute
References Base::BaseExceptionFreeCADError, getAttacher(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_positionBySupport()
PyObject * AttachExtensionPy::staticCallback_positionBySupport (PyObject * self, PyObject * args) static
callback for the positionBySupport() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), positionBySupport(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_setAttacher()
int AttachExtensionPy::staticCallback_setAttacher (PyObject * self, PyObject * value, void * closure) static
setter callback for the Attacher attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
Member Data Documentation
GetterSetter
PyGetSetDef AttachExtensionPy::GetterSetter static
Initial value:
= {
    {"Attacher",
        (getter) staticCallback_getAttacher,
        (setter) staticCallback_setAttacher,
        "AttachEngine object driving this AttachableObject. Returns a copy.",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of AttachExtensionPy.
Methods
PyMethodDef AttachExtensionPy::Methods static
Initial value:
= {
    {"positionBySupport",
        reinterpret_cast<PyCFunction>( staticCallback_positionBySupport ),
        METH_VARARGS,
        "positionBySupport(): Reposition object based on Support, MapMode and MapPathParameter properties.\nReturns True if attachment calculation was successful, false if object is not attached and Placement wasn't updated,\nand raises an exception if attachment calculation fails."
    },
    {"changeAttacherType",
        reinterpret_cast<PyCFunction>( staticCallback_changeAttacherType ),
        METH_VARARGS,
        "changeAttacherType(typename): Changes Attacher class of this object.\ntypename: string. The following are accepted so far:\n'Attacher::AttachEngine3D'\n'Attacher::AttachEnginePlane'\n'Attacher::AttachEngineLine'\n'Attacher::AttachEnginePoint'"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of AttachExtensionPy.
Type
PyTypeObject AttachExtensionPy::Type static
Type structure of AttachExtensionPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/AttachExtensionPy.h
Sources/FreeCAD/src/Mod/Part/App/AttachExtensionPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/AttachExtensionPy.cpp