FreeCAD: Reen::ScalarProduct Class Reference
Reen::ScalarProduct Class Reference
Public Member Functions
std::vector< double > multiply (int col) const
ScalarProduct (const math_Matrix &mat)
Constructor & Destructor Documentation
ScalarProduct()
Reen::ScalarProduct::ScalarProduct (const math_Matrix & mat)
Member Function Documentation
multiply()
std::vector<double> Reen::ScalarProduct::multiply (int col) const
References draftgeoutils.general::vec().
Referenced by PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart(), and Reen::BSplineParameterCorrection::SolveWithSmoothing().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/ReverseEngineering/App/ApproxSurface.cpp