FreeCAD: Base::UnitsSchemaImperialBuilding Class Reference
Base::UnitsSchemaImperialBuilding Class Reference
The schema class for the imperial unit system Here are the definitions for the imperial unit system.
#include <UnitsSchemaImperial1.h>
Public Member Functions
virtual QString schemaTranslate (const Base::Quantity &quant, double &factor, QString &unitString)
This method translates the quantity in a string as the user may expect it.
Public Member Functions inherited from Base::UnitsSchema
virtual void resetSchemaUnits (void)
If you use setSchemaUnits() you also have to impment this method to undo your changes!
virtual void setSchemaUnits (void)
Gets called if this schema gets activated.
QString toLocale (const Base::Quantity &quant, double factor, const QString &unitString) const
virtual ~UnitsSchema ()
Detailed Description
The schema class for the imperial unit system Here are the definitions for the imperial unit system.
It also defines how the value/units get printed.
Member Function Documentation
schemaTranslate()
QString UnitsSchemaImperialBuilding::schemaTranslate (const Base::Quantity & quant, double & factor, QString & unitString) virtual
This method translates the quantity in a string as the user may expect it.
Implements Base::UnitsSchema.
References Base::Unit::Angle, Base::Unit::Area, Base::QuantityFormat::getDenominator(), Base::Quantity::getFormat(), Base::Unit::getString(), Base::Quantity::getUnit(), Base::Quantity::getValue(), Base::Unit::Length, Base::UnitsSchema::toLocale(), Base::Unit::Velocity, and Base::Unit::Volume.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Base/UnitsSchemaImperial1.h
Sources/FreeCAD/src/Base/UnitsSchemaImperial1.cpp