FreeCAD: VisualPathSegmentVisitor Class Reference
VisualPathSegmentVisitor Class Reference
Public Member Functions
virtual void g0 (int id, const Base::Vector3d &last, const Base::Vector3d &next, const std::deque< Base::Vector3d > &pts)
virtual void g1 (int id, const Base::Vector3d &last, const Base::Vector3d &next, const std::deque< Base::Vector3d > &pts)
virtual void g23 (int id, const Base::Vector3d &last, const Base::Vector3d &next, const std::deque< Base::Vector3d > &pts, const Base::Vector3d &center)
virtual void g38 (int id, const Base::Vector3d &last, const Base::Vector3d &next)
virtual void g8x (int id, const Base::Vector3d &last, const Base::Vector3d &next, const std::deque< Base::Vector3d > &pts, const std::deque< Base::Vector3d > &p, const std::deque< Base::Vector3d > &q)
virtual void setup (const Base::Vector3d &last)
VisualPathSegmentVisitor (const Toolpath &tp, SoCoordinate3 *pcLineCoords_, SoCoordinate3 *pcMarkerCoords_, std::vector< int > &command2Edge_, std::deque< int > &edge2Command_, std::deque< int > &edgeIndices_, std::vector< int > &colorindex_, std::deque< Base::Vector3d > &points_, std::deque< Base::Vector3d > &markers_)
Public Member Functions inherited from Path::PathSegmentVisitor
virtual ~PathSegmentVisitor ()
Constructor & Destructor Documentation
VisualPathSegmentVisitor()
VisualPathSegmentVisitor::VisualPathSegmentVisitor (const Toolpath & tp, SoCoordinate3 * pcLineCoords_, SoCoordinate3 * pcMarkerCoords_, std::vector< int > & command2Edge_, std::deque< int > & edge2Command_, std::deque< int > & edgeIndices_, std::vector< int > & colorindex_, std::deque< Base::Vector3d > & points_, std::deque< Base::Vector3d > & markers_)
References Path::Toolpath::getSize().
Member Function Documentation
g0()
virtual void VisualPathSegmentVisitor::g0 (int id, const Base::Vector3d & last, const Base::Vector3d & next, const std::deque< Base::Vector3d > & pts) virtual
Reimplemented from Path::PathSegmentVisitor.
g1()
virtual void VisualPathSegmentVisitor::g1 (int id, const Base::Vector3d & last, const Base::Vector3d & next, const std::deque< Base::Vector3d > & pts) virtual
Reimplemented from Path::PathSegmentVisitor.
g23()
virtual void VisualPathSegmentVisitor::g23 (int id, const Base::Vector3d & last, const Base::Vector3d & next, const std::deque< Base::Vector3d > & pts, const Base::Vector3d & center) virtual
Reimplemented from Path::PathSegmentVisitor.
g38()
virtual void VisualPathSegmentVisitor::g38 (int id, const Base::Vector3d & last, const Base::Vector3d & next) virtual
Reimplemented from Path::PathSegmentVisitor.
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
g8x()
virtual void VisualPathSegmentVisitor::g8x (int id, const Base::Vector3d & last, const Base::Vector3d & next, const std::deque< Base::Vector3d > & pts, const std::deque< Base::Vector3d > & p, const std::deque< Base::Vector3d > & q) virtual
Reimplemented from Path::PathSegmentVisitor.
setup()
virtual void VisualPathSegmentVisitor::setup (const Base::Vector3d & last) virtual
Reimplemented from Path::PathSegmentVisitor.
Referenced by PathScripts.PathDressupHoldingTags.ObjectTagDressup::doExecute(), PathScripts.PathDressupDogbone.ObjectDressup::execute(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::generateTags(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::pointAtBottom(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::pointIsOnPath(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::setXyEnabled(), and PathScripts.PathDressupHoldingTags.ObjectTagDressup::supportsTagGeneration().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Path/Gui/ViewProviderPath.cpp