FreeCAD: SMESHDS_Hypothesis Class Reference
SMESHDS_Hypothesis Class Reference abstract
#include <SMESHDS_Hypothesis.hxx>
Public Types
enum hypothesis_type {
PARAM_ALGO, ALGO_0D, ALGO_1D, ALGO_2D,
ALGO_3D
}
Public Member Functions
int GetID () const
const char * GetName () const
int GetType () const
bool IsSameName (const SMESHDS_Hypothesis &other) const
Compare types of hypotheses.
virtual std::istream & LoadFrom (std::istream &load)=0
bool operator!= (const SMESHDS_Hypothesis &other) const
virtual bool operator== (const SMESHDS_Hypothesis &other) const
virtual std::ostream & SaveTo (std::ostream &save)=0
SMESHDS_Hypothesis (int hypId)
virtual ~SMESHDS_Hypothesis ()
Member Enumeration Documentation
hypothesis_type
enum SMESHDS_Hypothesis::hypothesis_type
Enumerator
PARAM_ALGO
ALGO_0D
ALGO_1D
ALGO_2D
ALGO_3D
Constructor & Destructor Documentation
SMESHDS_Hypothesis()
SMESHDS_Hypothesis::SMESHDS_Hypothesis (int hypId)
~SMESHDS_Hypothesis()
SMESHDS_Hypothesis::~SMESHDS_Hypothesis () virtual
Member Function Documentation
GetID()
int SMESHDS_Hypothesis::GetID () const
Referenced by SMESHDS_Document::AddHypothesis(), VISCOUS_3D::_LayerEdge::FindIntersection(), VISCOUS_3D::getDistFromEdge(), and StdMeshers_MEFISTO_2D::LoadPoints().
GetName()
const char * SMESHDS_Hypothesis::GetName () const
Referenced by SMESH_Mesh::AddHypothesis(), SMESH_subMesh::AlgoStateEngine(), SMESH_subMesh::checkComputeError(), NETGENPlugin_NETGEN_2D_ONLY::CheckHypothesis(), StdMeshers_Quadrangle_2D::CheckHypothesis(), NETGENPlugin_NETGEN_2D::CheckHypothesis(), NETGENPlugin_NETGEN_2D3D::CheckHypothesis(), StdMeshers_Import_1D::CheckHypothesis(), StdMeshers_Import_1D2D::CheckHypothesis(), StdMeshers_MEFISTO_2D::CheckHypothesis(), StdMeshers_Projection_1D::CheckHypothesis(), StdMeshers_Projection_2D::CheckHypothesis(), StdMeshers_Projection_3D::CheckHypothesis(), StdMeshers_RadialPrism_3D::CheckHypothesis(), StdMeshers_RadialQuadrangle_1D2D::CheckHypothesis(), StdMeshers_Regular_1D::CheckHypothesis(), StdMeshers_Hexa_3D::Evaluate(), StdMeshers_CompositeSegment_1D::GetFaceSide(), SMESH_subMesh::getSimilarAttached(), StdMeshers_ProjectionUtils::InitVertexAssociation(), SMESH_HypoFilter::NamePredicate::IsOk(), StdMeshers_ProjectionUtils::MakeComputed(), and StdMeshers_Cartesian_3D::SetEventListener().
GetType()
int SMESHDS_Hypothesis::GetType () const
Referenced by SMESH_Mesh::AddHypothesis(), SMESH_subMesh::AlgoStateEngine(), SMESH_Gen::GetAlgoState(), SMESH_subMesh::getSimilarAttached(), SMESH_subMesh::IsApplicableHypotesis(), SMESH_Hypothesis::IsAuxiliary(), SMESH_Mesh::IsUsedHypothesis(), SMESH_Mesh::RemoveHypothesis(), and SMESH_HypoFilter::TypePredicate::Value().
IsSameName()
bool SMESHDS_Hypothesis::IsSameName (const SMESHDS_Hypothesis & other) const
Compare types of hypotheses.
Referenced by StdMeshers_Regular_1D::CheckHypothesis(), and SMESH_subMesh::getCollection().
LoadFrom()
virtual std::istream& SMESHDS_Hypothesis::LoadFrom (std::istream & load) pure virtual
Implemented in StdMeshers_ViscousLayers, StdMeshers_TrianglePreference, StdMeshers_StartEndLength, StdMeshers_SegmentLengthAroundVertex, StdMeshers_Reversible1D, StdMeshers_QuadraticMesh, StdMeshers_QuadranglePreference, StdMeshers_QuadrangleParams, StdMeshers_Propagation, StdMeshers_ProjectionSource3D, StdMeshers_ProjectionSource2D, StdMeshers_ProjectionSource1D, StdMeshers_NumberOfSegments, StdMeshers_NumberOfLayers, StdMeshers_NotConformAllowed, StdMeshers_MaxLength, StdMeshers_MaxElementVolume, StdMeshers_MaxElementArea, StdMeshers_LocalLength, StdMeshers_LengthFromEdges, StdMeshers_LayerDistribution, StdMeshers_ImportSource1D, StdMeshers_Geometric1D, StdMeshers_FixedPoints1D, StdMeshers_Deflection1D, StdMeshers_CartesianParameters3D, StdMeshers_AutomaticLength, StdMeshers_Arithmetic1D, StdMeshers_Adaptive1D, SMESH_Algo, NETGENPlugin_SimpleHypothesis_3D, NETGENPlugin_SimpleHypothesis_2D, and NETGENPlugin_Hypothesis.
operator!=()
bool SMESHDS_Hypothesis::operator!= (const SMESHDS_Hypothesis & other) const
operator==()
bool SMESHDS_Hypothesis::operator== (const SMESHDS_Hypothesis & other) const virtual
Equality
SaveTo()
virtual std::ostream& SMESHDS_Hypothesis::SaveTo (std::ostream & save) pure virtual
Implemented in StdMeshers_ViscousLayers, StdMeshers_TrianglePreference, StdMeshers_StartEndLength, StdMeshers_SegmentLengthAroundVertex, StdMeshers_Reversible1D, StdMeshers_QuadraticMesh, StdMeshers_QuadranglePreference, StdMeshers_QuadrangleParams, StdMeshers_Propagation, StdMeshers_ProjectionSource3D, StdMeshers_ProjectionSource2D, StdMeshers_ProjectionSource1D, StdMeshers_NumberOfSegments, StdMeshers_NumberOfLayers, StdMeshers_NotConformAllowed, StdMeshers_MaxLength, StdMeshers_MaxElementVolume, StdMeshers_MaxElementArea, StdMeshers_LocalLength, StdMeshers_LengthFromEdges, StdMeshers_LayerDistribution, StdMeshers_ImportSource1D, StdMeshers_Geometric1D, StdMeshers_FixedPoints1D, StdMeshers_Deflection1D, StdMeshers_CartesianParameters3D, StdMeshers_AutomaticLength, StdMeshers_Arithmetic1D, StdMeshers_Adaptive1D, SMESH_Algo, NETGENPlugin_SimpleHypothesis_3D, NETGENPlugin_SimpleHypothesis_2D, and NETGENPlugin_Hypothesis.
Referenced by StdMeshers_LayerDistribution::SetLayerDistribution().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESHDS_Hypothesis.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESHDS/SMESHDS_Hypothesis.cpp