FreeCAD: automotive_design.geometric_representation_item Class Reference
automotive_design.geometric_representation_item Class Reference
Public Member Functions
def dim ()
def wr1 (self)
Public Member Functions inherited from automotive_design.representation_item
def name ()
Additional Inherited Members
Public Attributes inherited from automotive_design.representation_item
name
Detailed Description
Entity geometric_representation_item definition.
        :param dim
        :type dim:dimension_count
Member Function Documentation
dim()
def automotive_design.geometric_representation_item.dim ()
References automotive_design.dimension_of().
Referenced by ifc2x3.ifcsweptsurface.dim(), ifc2x3.ifcplacement.dim(), ifc2x3.ifccartesiantransformationoperator.dim(), ifc2x3.ifccurveboundedplane.dim(), ifc2x3.ifccompositecurvesegment.dim(), ifc2x3.ifcgeometricset.dim(), ifc2x3.ifcrectangulartrimmedsurface.dim(), ifc2x3.ifcelementarysurface.dim(), ifc2x3.ifcpointoncurve.dim(), ifc2x3.ifcpointonsurface.dim(), ifc2x3.ifcvector.dim(), ifc4.ifccompositecurvesegment.dim(), ifc4.ifcplacement.dim(), ifc4.ifccartesiantransformationoperator.dim(), ifc4.ifcgeometricset.dim(), ifc4.ifcpointoncurve.dim(), ifc4.ifcpointonsurface.dim(), and ifc4.ifcvector.dim().
wr1()
def automotive_design.geometric_representation_item.wr1 (self)
Reimplemented from automotive_design.representation_item.
Reimplemented in automotive_design.dimension_text_associativity, automotive_design.conical_surface, automotive_design.offset_curve_2d, automotive_design.solid_replica, automotive_design.surface_replica, automotive_design.structured_dimension_callout, automotive_design.right_circular_cone, automotive_design.advanced_face, automotive_design.cartesian_transformation_operator_2d, automotive_design.draughting_elements, automotive_design.b_spline_surface_with_knots, automotive_design.dimension_callout, automotive_design.torus, automotive_design.rational_b_spline_surface, automotive_design.axis2_placement_3d, automotive_design.seam_curve, automotive_design.ruled_surface_swept_area_solid, automotive_design.b_spline_curve_with_knots, automotive_design.draughting_text_literal_with_delineation, automotive_design.curve_bounded_surface, automotive_design.extruded_area_solid, automotive_design.degenerate_pcurve, automotive_design.annotation_fill_area, automotive_design.geometric_curve_set, automotive_design.line, automotive_design.annotation_plane, automotive_design.rectangular_trimmed_surface, automotive_design.point_replica, automotive_design.radius_dimension, automotive_design.face_surface, automotive_design.dimension_curve_directed_callout, automotive_design.degenerate_toroidal_surface, automotive_design.right_angular_wedge, automotive_design.kinematic_frame_based_transformation, automotive_design.surface_condition_callout, automotive_design.bounded_surface_curve, automotive_design.projection_directed_callout, automotive_design.trimmed_curve, automotive_design.intersection_curve, automotive_design.bounded_pcurve, automotive_design.pcurve, automotive_design.vector, automotive_design.shell_based_surface_model, automotive_design.rectangular_composite_surface, automotive_design.parabola, automotive_design.surface_curve, automotive_design.extruded_face_solid, automotive_design.swept_face_solid, automotive_design.curve_replica, automotive_design.swept_disk_solid, automotive_design.boundary_curve, automotive_design.composite_curve_on_surface, automotive_design.composite_curve, automotive_design.offset_curve_3d, automotive_design.surface_curve_swept_area_solid, automotive_design.swept_area_solid, automotive_design.camera_model_d3, automotive_design.camera_model_d2, automotive_design.light_source, automotive_design.direction, automotive_design.rational_b_spline_curve, automotive_design.b_spline_curve, automotive_design.axis1_placement, automotive_design.b_spline_surface, automotive_design.composite_text, automotive_design.axis2_placement_2d, automotive_design.leader_directed_dimension, automotive_design.leader_directed_callout, automotive_design.draughting_callout, automotive_design.camera_model, automotive_design.cartesian_transformation_operator_3d, and automotive_design.cartesian_transformation_operator.
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Import/App/automotive_design.py