FreeCAD: TechDrawGui::QGCustomLabel Class Reference
TechDrawGui::QGCustomLabel Class Reference
#include <QGCustomLabel.h>
Public Types
enum { Type = QGraphicsItem::UserType + 135 }
Public Member Functions
virtual void centerAt (double cX, double cY)
virtual void centerAt (QPointF centerPos)
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr)
QGCustomLabel (void)
int type () const
~QGCustomLabel ()
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGCustomLabel()
QGCustomLabel::QGCustomLabel (void) explicit
~QGCustomLabel()
TechDrawGui::QGCustomLabel::~QGCustomLabel ()
Member Function Documentation
centerAt() [1/2]
void QGCustomLabel::centerAt (double cX, double cY) virtual
centerAt() [2/2]
void QGCustomLabel::centerAt (QPointF centerPos) virtual
References centerAt().
Referenced by centerAt().
paint()
void QGCustomLabel::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) virtual
type()
int TechDrawGui::QGCustomLabel::type () const
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/QGCustomLabel.h
FreeCAD/src/Mod/TechDraw/Gui/QGCustomLabel.cpp