FreeCAD: FemGui::PointMarker Class Reference
FemGui::PointMarker Class Reference
#include <TaskPostBoxes.h>
Signals
void PointsChanged (double x1, double y1, double z1, double x2, double y2, double z2)
Public Member Functions
void addPoint (const SbVec3f &)
int countPoints () const
PointMarker (Gui::View3DInventorViewer *view, std::string ObjName)
~PointMarker ()
Protected Member Functions
void customEvent (QEvent *e)
Constructor & Destructor Documentation
PointMarker()
FemGui::PointMarker::PointMarker (Gui::View3DInventorViewer * view, std::string ObjName)
~PointMarker()
FemGui::PointMarker::~PointMarker ()
Member Function Documentation
addPoint()
void FemGui::PointMarker::addPoint (const SbVec3f &)
Referenced by draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_edit.Edit::evaluate_menu_action(), draftguitools.gui_stretch.Stretch::numericInput(), and FemGui::TaskPostDataAlongLine::pointCallback().
countPoints()
int FemGui::PointMarker::countPoints () const
Referenced by FemGui::TaskPostDataAlongLine::pointCallback().
customEvent()
void FemGui::PointMarker::customEvent (QEvent * e) protected
PointsChanged
void FemGui::PointMarker::PointsChanged (double x1, double y1, double z1, double x2, double y2, double z2) signal
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Fem/Gui/TaskPostBoxes.h
Sources/FreeCAD/src/Mod/Fem/Gui/TaskPostBoxes.cpp