FreeCAD: MED::TTTimeStampValue< eVersion, TMeshValueType > Struct Template Reference
MED::TTTimeStampValue< eVersion, TMeshValueType > Struct Template Reference
#include <MED_TStructures.hxx>
Public Member Functions
virtual void AllocateValue (EGeometrieElement theGeom, TInt theNbElem, TInt theNbGauss, TInt theNbComp, EModeSwitch theMode=eFULL_INTERLACE)
Allocates values for the given geometry.
virtual size_t GetNbGauss (EGeometrieElement theGeom) const
virtual size_t GetNbVal (EGeometrieElement theGeom) const
virtual unsigned char * GetValuePtr (EGeometrieElement theGeom)
virtual size_t GetValueSize (EGeometrieElement theGeom) const
TTTimeStampValue (const PTimeStampInfo &theTimeStampInfo, const PTimeStampValueBase &theInfo, ETypeChamp theTypeChamp)
TTTimeStampValue (const PTimeStampInfo &theTimeStampInfo, ETypeChamp theTypeChamp, const TGeom2Profile &theGeom2Profile, EModeSwitch theMode)
Public Member Functions inherited from MED::TTimeStampValue< TMeshValueType >
const TTGeom2Value & GetGeom2Value () const
TTMeshValue & GetMeshValue (EGeometrieElement theGeom)
Gets MED TimeStamp values for the given geometric type.
const TTMeshValue & GetMeshValue (EGeometrieElement theGeom) const
Gets MED TimeStamp values for the given geometric type (const version)
PTMeshValue & GetMeshValuePtr (EGeometrieElement theGeom)
Gets MED TimeStamp values for the given geometric type.
const PTMeshValue & GetMeshValuePtr (EGeometrieElement theGeom) const
Gets MED TimeStamp values for the given geometric type (const version)
virtual ETypeChamp GetTypeChamp () const
Gets type of the champ.
Public Member Functions inherited from MED::TTimeStampValueBase
const TGeom2Profile & GetGeom2Profile () const
Gets a map of MED Profiles per geometric type.
const TGeomSet & GetGeomSet () const
const PTimeStampInfo & GetTimeStampInfo () const
Public Member Functions inherited from MED::TModeSwitchInfo
EModeSwitch GetModeSwitch () const
TModeSwitchInfo ()
To construct instance of the class by default.
TModeSwitchInfo (EModeSwitch theModeSwitch)
To construct instance of the class.
Public Member Functions inherited from MED::TBase
virtual ~TBase ()
Additional Inherited Members
Public Types inherited from MED::TTimeStampValue< TMeshValueType >
typedef SharedPtr< TMeshValueType > PTMeshValue
typedef TMeshValueType::TElement TElement
typedef std::map< EGeometrieElement, PTMeshValue > TTGeom2Value
typedef TMeshValueType TTMeshValue
Public Attributes inherited from MED::TTimeStampValue< TMeshValueType >
TTGeom2Value myGeom2Value
Keeps map of MED TimeStamp values per geometric type (const version)
ETypeChamp myTypeChamp
Public Attributes inherited from MED::TTimeStampValueBase
TGeom2Profile myGeom2Profile
Keeps map of MED Profiles per geometric type.
TGeomSet myGeomSet
Keeps set of MED EGeometrieElement which contains values for the timestamp.
PTimeStampInfo myTimeStampInfo
A reference to correspondig MED TimeStamp.
Public Attributes inherited from MED::TModeSwitchInfo
EModeSwitch myModeSwitch
Keeps the.
Constructor & Destructor Documentation
TTTimeStampValue() [1/2]
template<EVersion eVersion, class TMeshValueType > MED::TTTimeStampValue< eVersion, TMeshValueType >::TTTimeStampValue (const PTimeStampInfo & theTimeStampInfo, const PTimeStampValueBase & theInfo, ETypeChamp theTypeChamp)
References MED::TTimeStampValueBase::myGeom2Profile, MED::TTimeStampValue< TMeshValueType >::myGeom2Value, MED::TTimeStampValueBase::myGeomSet, MED::TTimeStampValueBase::myTimeStampInfo, and MED::TTimeStampValue< TMeshValueType >::myTypeChamp.
TTTimeStampValue() [2/2]
template<EVersion eVersion, class TMeshValueType > MED::TTTimeStampValue< eVersion, TMeshValueType >::TTTimeStampValue (const PTimeStampInfo & theTimeStampInfo, ETypeChamp theTypeChamp, const TGeom2Profile & theGeom2Profile, EModeSwitch theMode)
References MED::TTimeStampValue< TMeshValueType >::GetMeshValue(), MED::TTimeStampValueBase::myGeom2Profile, MED::TTimeStampValueBase::myTimeStampInfo, and MED::TTimeStampValue< TMeshValueType >::myTypeChamp.
Member Function Documentation
AllocateValue()
template<EVersion eVersion, class TMeshValueType > virtual void MED::TTTimeStampValue< eVersion, TMeshValueType >::AllocateValue (EGeometrieElement theGeom, TInt theNbElem, TInt theNbGauss, TInt theNbComp, EModeSwitch theMode = eFULL_INTERLACE) virtual
Allocates values for the given geometry.
Implements MED::TTimeStampValueBase.
References MED::TTimeStampValue< TMeshValueType >::GetMeshValue().
GetNbGauss()
template<EVersion eVersion, class TMeshValueType > virtual size_t MED::TTTimeStampValue< eVersion, TMeshValueType >::GetNbGauss (EGeometrieElement theGeom) const virtual
Implements MED::TTimeStampValueBase.
References MED::TTimeStampValue< TMeshValueType >::GetMeshValue().
GetNbVal()
template<EVersion eVersion, class TMeshValueType > virtual size_t MED::TTTimeStampValue< eVersion, TMeshValueType >::GetNbVal (EGeometrieElement theGeom) const virtual
Implements MED::TTimeStampValueBase.
References MED::TTimeStampValue< TMeshValueType >::GetMeshValue().
GetValuePtr()
template<EVersion eVersion, class TMeshValueType > virtual unsigned char* MED::TTTimeStampValue< eVersion, TMeshValueType >::GetValuePtr (EGeometrieElement theGeom) virtual
Implements MED::TTimeStampValueBase.
References MED::TTimeStampValue< TMeshValueType >::GetMeshValue().
GetValueSize()
template<EVersion eVersion, class TMeshValueType > virtual size_t MED::TTTimeStampValue< eVersion, TMeshValueType >::GetValueSize (EGeometrieElement theGeom) const virtual
Implements MED::TTimeStampValueBase.
References MED::TTimeStampValue< TMeshValueType >::GetMeshValue().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/MED_TStructures.hxx