FreeCAD: FemGui::TaskFemConstraintDisplacement Class Reference
FemGui::TaskFemConstraintDisplacement Class Reference
#include <TaskFemConstraintDisplacement.h>
Public Member Functions
bool get_dispxfix () const
bool get_dispxfree () const
bool get_dispyfix () const
bool get_dispyfree () const
bool get_dispzfix () const
bool get_dispzfree () const
bool get_rotxfix () const
bool get_rotxfree () const
bool get_rotyfix () const
bool get_rotyfree () const
bool get_rotzfix () const
bool get_rotzfree () const
double get_spinxDisplacement () const
double get_spinxRotation () const
double get_spinyDisplacement () const
double get_spinyRotation () const
double get_spinzDisplacement () const
double get_spinzRotation () const
const std::string getReferences () const
TaskFemConstraintDisplacement (ViewProviderFemConstraintDisplacement *ConstraintView, QWidget *parent=nullptr)
~TaskFemConstraintDisplacement ()
Public Member Functions inherited from FemGui::TaskFemConstraintOnBoundary
TaskFemConstraintOnBoundary (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="")
~TaskFemConstraintOnBoundary ()
Public Member Functions inherited from FemGui::TaskFemConstraint
const std::string getReferences (const std::vector< std::string > &items) const
virtual const std::string getReferences (void) const
const std::string getScale () const
TaskFemConstraint (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="")
virtual ~TaskFemConstraint ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Protected Member Functions
void changeEvent (QEvent *e)
void clearButtons (const SelectionChangeModes notThis) override
bool event (QEvent *e)
Protected Member Functions inherited from FemGui::TaskFemConstraintOnBoundary
virtual void clearButtons (const SelectionChangeModes notThis)=0
virtual void onSelectionChanged (const Gui::SelectionChanges &) override
Protected Member Functions inherited from FemGui::TaskFemConstraint
virtual void changeEvent (QEvent *e)
void createDeleteAction (QListWidget *parentList)
bool KeyEvent (QEvent *e)
virtual void keyPressEvent (QKeyEvent *ke)
const QString makeRefText (const App::DocumentObject *obj, const std::string &subName) const
const QString makeRefText (const std::string &objName, const std::string &subName) const
virtual void onSelectionChanged (const Gui::SelectionChanges &)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Types inherited from FemGui::TaskFemConstraintOnBoundary
enum class SelectionChangeModes { none , refAdd , refRemove }
Protected Types inherited from FemGui::TaskFemConstraint
enum { seldir , selref , selloc , selnone }
Protected Slots inherited from FemGui::TaskFemConstraintOnBoundary
virtual void addToSelection ()=0
void onButtonToggled (QAbstractButton *button, bool checked)
virtual void removeFromSelection ()=0
Protected Slots inherited from FemGui::TaskFemConstraint
void onButtonReference (const bool pressed=true)
void onButtonWizCancel ()
void onButtonWizOk ()
void onReferenceDeleted (const int row)
void setSelection (QListWidgetItem *item)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from FemGui::TaskFemConstraintOnBoundary
Gui::ButtonGroup * buttonGroup
enum SelectionChangeModes selChangeMode
Protected Attributes inherited from FemGui::TaskFemConstraint
Gui::WeakPtrT< ViewProviderFemConstraint > ConstraintView
QAction * deleteAction
QWidget * proxy
enum FemGui::TaskFemConstraint:: { ... } selectionMode
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskFemConstraintDisplacement()
TaskFemConstraintDisplacement::TaskFemConstraintDisplacement (ViewProviderFemConstraintDisplacement * ConstraintView, QWidget * parent = nullptr)
References Ui_TaskFemConstraintDisplacement::btnAdd, Ui_TaskFemConstraintDisplacement::btnRemove, FemGui::TaskFemConstraintOnBoundary::buttonGroup, draftgeoutils.intersections::connect(), FemGui::TaskFemConstraint::ConstraintView, FemGui::TaskFemConstraint::createDeleteAction(), FemGui::TaskFemConstraint::deleteAction, Ui_TaskFemConstraintDisplacement::dispxfix, Ui_TaskFemConstraintDisplacement::dispxfree, Ui_TaskFemConstraintDisplacement::dispyfix, Ui_TaskFemConstraintDisplacement::dispyfree, Ui_TaskFemConstraintDisplacement::dispzfix, Ui_TaskFemConstraintDisplacement::dispzfree, App::PropertyLinkSubList::getSubValues(), App::PropertyFloat::getValue(), App::PropertyBool::getValue(), App::PropertyLinkSubList::getValues(), QSint::ActionGroup::groupLayout(), Ui_TaskFemConstraintDisplacement::lw_references, FemGui::TaskFemConstraint::makeRefText(), FemGui::TaskFemConstraint::proxy, FemGui::TaskFemConstraintOnBoundary::refAdd, Fem::Constraint::References, FemGui::TaskFemConstraintOnBoundary::refRemove, Ui_TaskFemConstraintDisplacement::rotxfix, Fem::ConstraintDisplacement::rotxFix, Ui_TaskFemConstraintDisplacement::rotxfree, Fem::ConstraintDisplacement::rotxFree, Ui_TaskFemConstraintDisplacement::rotyfix, Fem::ConstraintDisplacement::rotyFix, Ui_TaskFemConstraintDisplacement::rotyfree, Fem::ConstraintDisplacement::rotyFree, Ui_TaskFemConstraintDisplacement::rotzfix, Fem::ConstraintDisplacement::rotzFix, Ui_TaskFemConstraintDisplacement::rotzfree, Fem::ConstraintDisplacement::rotzFree, FemGui::TaskFemConstraint::setSelection(), Ui_TaskFemConstraintDisplacement::setupUi(), Ui_TaskFemConstraintDisplacement::spinxDisplacement, Ui_TaskFemConstraintDisplacement::spinxRotation, Ui_TaskFemConstraintDisplacement::spinyDisplacement, Ui_TaskFemConstraintDisplacement::spinyRotation, Ui_TaskFemConstraintDisplacement::spinzDisplacement, Ui_TaskFemConstraintDisplacement::spinzRotation, Fem::ConstraintDisplacement::xDisplacement, Fem::ConstraintDisplacement::xFix, Fem::ConstraintDisplacement::xFree, Fem::ConstraintDisplacement::xRotation, Fem::ConstraintDisplacement::yDisplacement, Fem::ConstraintDisplacement::yFix, Fem::ConstraintDisplacement::yFree, Fem::ConstraintDisplacement::yRotation, Fem::ConstraintDisplacement::zDisplacement, Fem::ConstraintDisplacement::zFix, Fem::ConstraintDisplacement::zFree, and Fem::ConstraintDisplacement::zRotation.
~TaskFemConstraintDisplacement()
TaskFemConstraintDisplacement::~TaskFemConstraintDisplacement ()
Member Function Documentation
changeEvent()
void TaskFemConstraintDisplacement::changeEvent (QEvent * e) protected virtual
Reimplemented from FemGui::TaskFemConstraint.
clearButtons()
void TaskFemConstraintDisplacement::clearButtons (const SelectionChangeModes notThis) override protected virtual
Implements FemGui::TaskFemConstraintOnBoundary.
References Ui_TaskFemConstraintDisplacement::btnAdd, Ui_TaskFemConstraintDisplacement::btnRemove, FemGui::TaskFemConstraintOnBoundary::refAdd, and FemGui::TaskFemConstraintOnBoundary::refRemove.
event()
bool TaskFemConstraintDisplacement::event (QEvent * e) protected
References FemGui::TaskFemConstraint::KeyEvent().
get_dispxfix()
bool TaskFemConstraintDisplacement::get_dispxfix () const
References Ui_TaskFemConstraintDisplacement::dispxfix.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
get_dispxfree()
bool TaskFemConstraintDisplacement::get_dispxfree () const
References Ui_TaskFemConstraintDisplacement::dispxfree.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
get_dispyfix()
bool TaskFemConstraintDisplacement::get_dispyfix () const
References Ui_TaskFemConstraintDisplacement::dispyfix.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
get_dispyfree()
bool TaskFemConstraintDisplacement::get_dispyfree () const
References Ui_TaskFemConstraintDisplacement::dispyfree.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
get_dispzfix()
bool TaskFemConstraintDisplacement::get_dispzfix () const
References Ui_TaskFemConstraintDisplacement::dispzfix.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
get_dispzfree()
bool TaskFemConstraintDisplacement::get_dispzfree () const
References Ui_TaskFemConstraintDisplacement::dispzfree.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
get_rotxfix()
bool TaskFemConstraintDisplacement::get_rotxfix () const
References Ui_TaskFemConstraintDisplacement::rotxfix.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
get_rotxfree()
bool TaskFemConstraintDisplacement::get_rotxfree () const
References Ui_TaskFemConstraintDisplacement::rotxfree.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
get_rotyfix()
bool TaskFemConstraintDisplacement::get_rotyfix () const
References Ui_TaskFemConstraintDisplacement::rotyfix.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
get_rotyfree()
bool TaskFemConstraintDisplacement::get_rotyfree () const
References Ui_TaskFemConstraintDisplacement::rotyfree.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
get_rotzfix()
bool TaskFemConstraintDisplacement::get_rotzfix () const
References Ui_TaskFemConstraintDisplacement::rotzfix.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
get_rotzfree()
bool TaskFemConstraintDisplacement::get_rotzfree () const
References Ui_TaskFemConstraintDisplacement::rotzfree.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
get_spinxDisplacement()
double TaskFemConstraintDisplacement::get_spinxDisplacement () const
References Ui_TaskFemConstraintDisplacement::spinxDisplacement.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
get_spinxRotation()
double TaskFemConstraintDisplacement::get_spinxRotation () const
References Ui_TaskFemConstraintDisplacement::spinxRotation.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
get_spinyDisplacement()
double TaskFemConstraintDisplacement::get_spinyDisplacement () const
References Ui_TaskFemConstraintDisplacement::spinyDisplacement.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
get_spinyRotation()
double TaskFemConstraintDisplacement::get_spinyRotation () const
References Ui_TaskFemConstraintDisplacement::spinyRotation.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
get_spinzDisplacement()
double TaskFemConstraintDisplacement::get_spinzDisplacement () const
References Ui_TaskFemConstraintDisplacement::spinzDisplacement.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
get_spinzRotation()
double TaskFemConstraintDisplacement::get_spinzRotation () const
References Ui_TaskFemConstraintDisplacement::spinzRotation.
Referenced by FemGui::TaskDlgFemConstraintDisplacement::accept().
getReferences()
const std::string TaskFemConstraintDisplacement::getReferences (void) const virtual
Reimplemented from FemGui::TaskFemConstraint.
References FemGui::TaskFemConstraint::getReferences(), and Ui_TaskFemConstraintDisplacement::lw_references.
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintDisplacement.h
FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintDisplacement.cpp