FreeCAD: Part::BRepOffsetAPI_MakePipeShellPy Class Reference
Part::BRepOffsetAPI_MakePipeShellPy Class Reference
The python export class for BRepOffsetAPI_MakePipeShell.
#include <BRepOffsetAPI_MakePipeShellPy.h>
Public Types
typedef BRepOffsetAPI_MakePipeShell * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
BRepOffsetAPI_MakePipeShellPy (BRepOffsetAPI_MakePipeShell *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BRepOffsetAPI_MakePipeShell * getBRepOffsetAPI_MakePipeShellPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of BRepOffsetAPI_MakePipeShellPy.
static PyMethodDef Methods []
Methods structure of BRepOffsetAPI_MakePipeShellPy.
static PyTypeObject Type
Type structure of BRepOffsetAPI_MakePipeShellPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~BRepOffsetAPI_MakePipeShellPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * setFrenetMode (PyObject *args)
implementer for the setFrenetMode() method
PyObject * setTrihedronMode (PyObject *args)
implementer for the setTrihedronMode() method
PyObject * setBiNormalMode (PyObject *args)
implementer for the setBiNormalMode() method
PyObject * setSpineSupport (PyObject *args)
implementer for the setSpineSupport() method
PyObject * setAuxiliarySpine (PyObject *args)
implementer for the setAuxiliarySpine() method
PyObject * add (PyObject *args, PyObject *kwd)
implementer for the add() method
PyObject * remove (PyObject *args)
implementer for the remove() method
PyObject * isReady (PyObject *args)
implementer for the isReady() method
PyObject * getStatus (PyObject *args)
implementer for the getStatus() method
PyObject * makeSolid (PyObject *args)
implementer for the makeSolid() method
PyObject * setTolerance (PyObject *args)
implementer for the setTolerance() method
PyObject * setTransitionMode (PyObject *args)
implementer for the setTransitionMode() method
PyObject * firstShape (PyObject *args)
implementer for the firstShape() method
PyObject * lastShape (PyObject *args)
implementer for the lastShape() method
PyObject * build (PyObject *args)
implementer for the build() method
PyObject * shape (PyObject *args)
implementer for the shape() method
PyObject * generated (PyObject *args)
implementer for the generated() method
PyObject * setMaxDegree (PyObject *args)
implementer for the setMaxDegree() method
PyObject * setMaxSegments (PyObject *args)
implementer for the setMaxSegments() method
PyObject * setForceApproxC1 (PyObject *args)
implementer for the setForceApproxC1() method
PyObject * simulate (PyObject *args)
implementer for the simulate() method
static PyObject * staticCallback_setFrenetMode (PyObject *self, PyObject *args)
callback for the setFrenetMode() method
static PyObject * staticCallback_setTrihedronMode (PyObject *self, PyObject *args)
callback for the setTrihedronMode() method
static PyObject * staticCallback_setBiNormalMode (PyObject *self, PyObject *args)
callback for the setBiNormalMode() method
static PyObject * staticCallback_setSpineSupport (PyObject *self, PyObject *args)
callback for the setSpineSupport() method
static PyObject * staticCallback_setAuxiliarySpine (PyObject *self, PyObject *args)
callback for the setAuxiliarySpine() method
static PyObject * staticCallback_add (PyObject *self, PyObject *args, PyObject *kwd)
callback for the add() method
static PyObject * staticCallback_remove (PyObject *self, PyObject *args)
callback for the remove() method
static PyObject * staticCallback_isReady (PyObject *self, PyObject *args)
callback for the isReady() method
static PyObject * staticCallback_getStatus (PyObject *self, PyObject *args)
callback for the getStatus() method
static PyObject * staticCallback_makeSolid (PyObject *self, PyObject *args)
callback for the makeSolid() method
static PyObject * staticCallback_setTolerance (PyObject *self, PyObject *args)
callback for the setTolerance() method
static PyObject * staticCallback_setTransitionMode (PyObject *self, PyObject *args)
callback for the setTransitionMode() method
static PyObject * staticCallback_firstShape (PyObject *self, PyObject *args)
callback for the firstShape() method
static PyObject * staticCallback_lastShape (PyObject *self, PyObject *args)
callback for the lastShape() method
static PyObject * staticCallback_build (PyObject *self, PyObject *args)
callback for the build() method
static PyObject * staticCallback_shape (PyObject *self, PyObject *args)
callback for the shape() method
static PyObject * staticCallback_generated (PyObject *self, PyObject *args)
callback for the generated() method
static PyObject * staticCallback_setMaxDegree (PyObject *self, PyObject *args)
callback for the setMaxDegree() method
static PyObject * staticCallback_setMaxSegments (PyObject *self, PyObject *args)
callback for the setMaxSegments() method
static PyObject * staticCallback_setForceApproxC1 (PyObject *self, PyObject *args)
callback for the setForceApproxC1() method
static PyObject * staticCallback_simulate (PyObject *self, PyObject *args)
callback for the simulate() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for BRepOffsetAPI_MakePipeShell.
Member Typedef Documentation
PointerType
typedef BRepOffsetAPI_MakePipeShell* Part::BRepOffsetAPI_MakePipeShellPy::PointerType
Constructor & Destructor Documentation
~BRepOffsetAPI_MakePipeShellPy()
BRepOffsetAPI_MakePipeShellPy::~BRepOffsetAPI_MakePipeShellPy () protected
BRepOffsetAPI_MakePipeShellPy()
BRepOffsetAPI_MakePipeShellPy::BRepOffsetAPI_MakePipeShellPy (BRepOffsetAPI_MakePipeShell * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
add()
PyObject * BRepOffsetAPI_MakePipeShellPy::add (PyObject * args, PyObject * kwd)
implementer for the add() method
References getBRepOffsetAPI_MakePipeShellPtr(), Part::PartExceptionOCCError, Part::TopoShapePy::Type, and Part::TopoShapeVertexPy::Type.
Referenced by staticCallback_add().
build()
PyObject * BRepOffsetAPI_MakePipeShellPy::build (PyObject * args)
implementer for the build() method
References getBRepOffsetAPI_MakePipeShellPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_build().
firstShape()
PyObject * BRepOffsetAPI_MakePipeShellPy::firstShape (PyObject * args)
implementer for the firstShape() method
References getBRepOffsetAPI_MakePipeShellPtr(), Part::PartExceptionOCCError, and shape().
Referenced by staticCallback_firstShape().
generated()
PyObject * BRepOffsetAPI_MakePipeShellPy::generated (PyObject * args)
implementer for the generated() method
References getBRepOffsetAPI_MakePipeShellPtr(), Part::PartExceptionOCCError, shape(), and Part::TopoShapePy::Type.
Referenced by staticCallback_generated().
getBRepOffsetAPI_MakePipeShellPtr()
BRepOffsetAPI_MakePipeShell * BRepOffsetAPI_MakePipeShellPy::getBRepOffsetAPI_MakePipeShellPtr (void) const
getter for the object handled by this class
Referenced by add(), build(), firstShape(), generated(), getStatus(), isReady(), lastShape(), makeSolid(), remove(), setAuxiliarySpine(), setBiNormalMode(), setForceApproxC1(), setFrenetMode(), setMaxDegree(), setMaxSegments(), setSpineSupport(), setTolerance(), setTransitionMode(), setTrihedronMode(), shape(), and simulate().
getCustomAttributes()
PyObject * BRepOffsetAPI_MakePipeShellPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getStatus()
PyObject * BRepOffsetAPI_MakePipeShellPy::getStatus (PyObject * args)
implementer for the getStatus() method
References getBRepOffsetAPI_MakePipeShellPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getStatus().
GetType()
virtual PyTypeObject* Part::BRepOffsetAPI_MakePipeShellPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
isReady()
PyObject * BRepOffsetAPI_MakePipeShellPy::isReady (PyObject * args)
implementer for the isReady() method
References getBRepOffsetAPI_MakePipeShellPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_isReady().
lastShape()
PyObject * BRepOffsetAPI_MakePipeShellPy::lastShape (PyObject * args)
implementer for the lastShape() method
References getBRepOffsetAPI_MakePipeShellPtr(), Part::PartExceptionOCCError, and shape().
Referenced by staticCallback_lastShape().
makeSolid()
PyObject * BRepOffsetAPI_MakePipeShellPy::makeSolid (PyObject * args)
implementer for the makeSolid() method
References getBRepOffsetAPI_MakePipeShellPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_makeSolid().
PyInit()
int BRepOffsetAPI_MakePipeShellPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
PyMake()
PyObject * BRepOffsetAPI_MakePipeShellPy::PyMake (struct _typeobject * , PyObject * args, PyObject *) static
References BRepOffsetAPI_MakePipeShellPy(), Part::PartExceptionOCCError, and Part::TopoShapePy::Type.
remove()
PyObject * BRepOffsetAPI_MakePipeShellPy::remove (PyObject * args)
implementer for the remove() method
References getBRepOffsetAPI_MakePipeShellPtr(), Part::PartExceptionOCCError, and Part::TopoShapePy::Type.
Referenced by staticCallback_remove().
representation()
std::string BRepOffsetAPI_MakePipeShellPy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setAuxiliarySpine()
PyObject * BRepOffsetAPI_MakePipeShellPy::setAuxiliarySpine (PyObject * args)
implementer for the setAuxiliarySpine() method
References getBRepOffsetAPI_MakePipeShellPtr(), Part::PartExceptionOCCError, and Part::TopoShapePy::Type.
Referenced by staticCallback_setAuxiliarySpine().
setBiNormalMode()
PyObject * BRepOffsetAPI_MakePipeShellPy::setBiNormalMode (PyObject * args)
implementer for the setBiNormalMode() method
References getBRepOffsetAPI_MakePipeShellPtr(), Part::PartExceptionOCCError, and Base::VectorPy::Type.
Referenced by staticCallback_setBiNormalMode().
setCustomAttributes()
int BRepOffsetAPI_MakePipeShellPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setForceApproxC1()
PyObject * BRepOffsetAPI_MakePipeShellPy::setForceApproxC1 (PyObject * args)
implementer for the setForceApproxC1() method
References getBRepOffsetAPI_MakePipeShellPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setForceApproxC1().
setFrenetMode()
PyObject * BRepOffsetAPI_MakePipeShellPy::setFrenetMode (PyObject * args)
implementer for the setFrenetMode() method
References getBRepOffsetAPI_MakePipeShellPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setFrenetMode().
setMaxDegree()
PyObject * BRepOffsetAPI_MakePipeShellPy::setMaxDegree (PyObject * args)
implementer for the setMaxDegree() method
References getBRepOffsetAPI_MakePipeShellPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setMaxDegree().
setMaxSegments()
PyObject * BRepOffsetAPI_MakePipeShellPy::setMaxSegments (PyObject * args)
implementer for the setMaxSegments() method
References getBRepOffsetAPI_MakePipeShellPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setMaxSegments().
setSpineSupport()
PyObject * BRepOffsetAPI_MakePipeShellPy::setSpineSupport (PyObject * args)
implementer for the setSpineSupport() method
References getBRepOffsetAPI_MakePipeShellPtr(), Part::PartExceptionOCCError, shape(), and Part::TopoShapePy::Type.
Referenced by staticCallback_setSpineSupport().
setTolerance()
PyObject * BRepOffsetAPI_MakePipeShellPy::setTolerance (PyObject * args)
implementer for the setTolerance() method
References getBRepOffsetAPI_MakePipeShellPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setTolerance().
setTransitionMode()
PyObject * BRepOffsetAPI_MakePipeShellPy::setTransitionMode (PyObject * args)
implementer for the setTransitionMode() method
References getBRepOffsetAPI_MakePipeShellPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setTransitionMode().
setTrihedronMode()
PyObject * BRepOffsetAPI_MakePipeShellPy::setTrihedronMode (PyObject * args)
implementer for the setTrihedronMode() method
References getBRepOffsetAPI_MakePipeShellPtr(), Part::PartExceptionOCCError, and Base::VectorPy::Type.
Referenced by staticCallback_setTrihedronMode().
shape()
PyObject * BRepOffsetAPI_MakePipeShellPy::shape (PyObject * args)
implementer for the shape() method
References getBRepOffsetAPI_MakePipeShellPtr(), and Part::PartExceptionOCCError.
Referenced by draftguitools.gui_offset.Offset::action(), firstShape(), generated(), PathScripts.PathSurfaceSupport.PathGeometryGenerator::generatePathGeometry(), lastShape(), draftguitools.gui_offset.Offset::numericRadius(), setSpineSupport(), and staticCallback_shape().
simulate()
PyObject * BRepOffsetAPI_MakePipeShellPy::simulate (PyObject * args)
implementer for the simulate() method
References getBRepOffsetAPI_MakePipeShellPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_simulate().
staticCallback_add()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_add (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the add() method
References add(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_build()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_build (PyObject * self, PyObject * args) static
callback for the build() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, build(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_firstShape()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_firstShape (PyObject * self, PyObject * args) static
callback for the firstShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, firstShape(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_generated()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_generated (PyObject * self, PyObject * args) static
callback for the generated() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, generated(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getStatus()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_getStatus (PyObject * self, PyObject * args) static
callback for the getStatus() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getStatus(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_isReady()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_isReady (PyObject * self, PyObject * args) static
callback for the isReady() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), isReady(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_lastShape()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_lastShape (PyObject * self, PyObject * args) static
callback for the lastShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), lastShape(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_makeSolid()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_makeSolid (PyObject * self, PyObject * args) static
callback for the makeSolid() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), makeSolid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_remove()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_remove (PyObject * self, PyObject * args) static
callback for the remove() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), remove(), and Base::PyObjectBase::startNotify().
staticCallback_setAuxiliarySpine()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_setAuxiliarySpine (PyObject * self, PyObject * args) static
callback for the setAuxiliarySpine() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setAuxiliarySpine(), and Base::PyObjectBase::startNotify().
staticCallback_setBiNormalMode()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_setBiNormalMode (PyObject * self, PyObject * args) static
callback for the setBiNormalMode() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setBiNormalMode(), and Base::PyObjectBase::startNotify().
staticCallback_setForceApproxC1()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_setForceApproxC1 (PyObject * self, PyObject * args) static
callback for the setForceApproxC1() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setForceApproxC1(), and Base::PyObjectBase::startNotify().
staticCallback_setFrenetMode()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_setFrenetMode (PyObject * self, PyObject * args) static
callback for the setFrenetMode() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setFrenetMode(), and Base::PyObjectBase::startNotify().
staticCallback_setMaxDegree()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_setMaxDegree (PyObject * self, PyObject * args) static
callback for the setMaxDegree() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setMaxDegree(), and Base::PyObjectBase::startNotify().
staticCallback_setMaxSegments()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_setMaxSegments (PyObject * self, PyObject * args) static
callback for the setMaxSegments() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setMaxSegments(), and Base::PyObjectBase::startNotify().
staticCallback_setSpineSupport()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_setSpineSupport (PyObject * self, PyObject * args) static
callback for the setSpineSupport() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setSpineSupport(), and Base::PyObjectBase::startNotify().
staticCallback_setTolerance()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_setTolerance (PyObject * self, PyObject * args) static
callback for the setTolerance() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setTolerance(), and Base::PyObjectBase::startNotify().
staticCallback_setTransitionMode()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_setTransitionMode (PyObject * self, PyObject * args) static
callback for the setTransitionMode() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setTransitionMode(), and Base::PyObjectBase::startNotify().
staticCallback_setTrihedronMode()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_setTrihedronMode (PyObject * self, PyObject * args) static
callback for the setTrihedronMode() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setTrihedronMode(), and Base::PyObjectBase::startNotify().
staticCallback_shape()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_shape (PyObject * self, PyObject * args) static
callback for the shape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), shape(), and Base::PyObjectBase::startNotify().
staticCallback_simulate()
PyObject * BRepOffsetAPI_MakePipeShellPy::staticCallback_simulate (PyObject * self, PyObject * args) static
callback for the simulate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), simulate(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef BRepOffsetAPI_MakePipeShellPy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of BRepOffsetAPI_MakePipeShellPy.
Methods
PyMethodDef BRepOffsetAPI_MakePipeShellPy::Methods static
Methods structure of BRepOffsetAPI_MakePipeShellPy.
Type
PyTypeObject BRepOffsetAPI_MakePipeShellPy::Type static
Type structure of BRepOffsetAPI_MakePipeShellPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/BRepOffsetAPI_MakePipeShellPy.h
Sources/FreeCAD/src/Mod/Part/App/BRepOffsetAPI_MakePipeShellPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/BRepOffsetAPI_MakePipeShellPy.cpp