FreeCAD: Gui::TaskView::TaskWatcherCommands Class Reference
Gui::TaskView::TaskWatcherCommands Class Reference
Special watcher class for showing commands dependene on the selection.
#include <TaskWatcher.h>
Public Member Functions
virtual bool shouldShow (void)
is called wenn the document or the Selection changes.
TaskWatcherCommands (const char *Filter, const char *commands[], const char *name, const char *pixmap)
Public Member Functions inherited from Gui::TaskView::TaskWatcher
std::vector< QWidget * > & getWatcherContent (void)
TaskWatcher (const char *Filter)
virtual ~TaskWatcher ()
Public Member Functions inherited from Gui::SelectionFilter
void addError (const char *e)
const std::string & getFilter () const
bool isValid (void) const
true if a valid filter is set
bool match (void)
Test to current selection This method tests the current selection set against the filter and returns true if the described object(s) are selected.
SelectionFilter (const char *filter)
Constructs a SelectionFilter object.
SelectionFilter (const std::string &filter)
void setFilter (const char *filter)
Set a new filter string.
bool test (App::DocumentObject *pObj, const char *sSubName)
Test objects This method tests if a given object is described in the filter.
virtual ~SelectionFilter ()
Additional Inherited Members
Public Attributes inherited from Gui::SelectionFilter
std::vector< std::vector< SelectionObject > > Result
Protected Member Functions inherited from Gui::SelectionFilter
bool parse (void)
Protected Attributes inherited from Gui::TaskView::TaskWatcher
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
Protected Attributes inherited from Gui::SelectionFilter
Node_Block * Ast
std::string Errors
std::string Filter
Detailed Description
Special watcher class for showing commands dependene on the selection.
Constructor & Destructor Documentation
TaskWatcherCommands()
TaskWatcherCommands::TaskWatcherCommands (const char * Filter, const char * commands[], const char * name, const char * pixmap)
References Gui::Command::addTo(), Gui::BitmapFactory(), Gui::Application::commandManager(), Gui::TaskView::TaskWatcher::Content, Gui::CommandManager::getCommandByName(), and Gui::Application::Instance.
Member Function Documentation
shouldShow()
bool TaskWatcherCommands::shouldShow (void) virtual
is called wenn the document or the Selection changes.
Reimplemented from Gui::TaskView::TaskWatcher.
Reimplemented in Gui::TaskView::TaskWatcherCommandsEmptySelection, and Gui::TaskView::TaskWatcherCommandsEmptyDoc.
References Gui::SelectionFilter::match().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/TaskView/TaskWatcher.h
Sources/FreeCAD/src/Gui/TaskView/TaskWatcher.cpp