FreeCAD: femsolver.z88.solver.ViewProxy Class Reference
femsolver.z88.solver.ViewProxy Class Reference
Public Member Functions
def getIcon (self)
Public Member Functions inherited from femsolver.solverbase.ViewProxy
def attach (self, vobj)
def doubleClicked (self, vobj)
def setEdit (self, vobj, mode=0)
def unsetEdit (self, vobj, mode=0)
Member Function Documentation
getIcon()
def femsolver.z88.solver.ViewProxy.getIcon (self)
Referenced by ArchAxisSystem.AxisSystemTaskPanel.update(), ArchComponent.ComponentTaskPanel.update(), and ArchSectionPlane.SectionPlaneTaskPanel.update().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Fem/femsolver/z88/solver.py