FreeCAD: Gui::UnsignedValidator Class Reference
Gui::UnsignedValidator Class Reference
A validator that allows only input of unsigned int values in the range from 0 to UINT_MAX.
#include <SpinBox.h>
Public Member Functions
uint bottom () const
void setBottom (uint)
virtual void setRange (uint bottom, uint top)
void setTop (uint)
uint top () const
UnsignedValidator (QObject *parent)
UnsignedValidator (uint bottom, uint top, QObject *parent)
QValidator::State validate (QString &, int &) const
~UnsignedValidator ()
Properties
uint bottom
uint top
Detailed Description
A validator that allows only input of unsigned int values in the range from 0 to UINT_MAX.
Constructor & Destructor Documentation
UnsignedValidator() [1/2]
UnsignedValidator::UnsignedValidator (QObject * parent)
UnsignedValidator() [2/2]
UnsignedValidator::UnsignedValidator (uint bottom, uint top, QObject * parent)
~UnsignedValidator()
UnsignedValidator::~UnsignedValidator ()
Member Function Documentation
bottom()
uint Gui::UnsignedValidator::bottom () const
Referenced by PathScripts.PathDressupHoldingTags.Tag::filterIntersections().
setBottom()
void UnsignedValidator::setBottom (uint bottom)
References setRange(), and top.
setRange()
void UnsignedValidator::setRange (uint bottom, uint top) virtual
Referenced by setBottom(), and setTop().
setTop()
void UnsignedValidator::setTop (uint top)
References bottom, and setRange().
top()
uint Gui::UnsignedValidator::top () const
Referenced by Mod.Test.unittestgui.TkTestRunner::createWidgets(), PathScripts.PathDressupHoldingTags.Tag::filterIntersections(), PathScripts.PathDressupHoldingTags.Tag::intersects(), and Mod.Test.unittestgui.TkTestRunner::notifyTestStarted().
validate()
QValidator::State UnsignedValidator::validate (QString & input, int &) const
Referenced by Gui::UIntSpinBox::validate().
Property Documentation
bottom
uint Gui::UnsignedValidator::bottom read write
Referenced by PathScripts.PathDressupHoldingTags.Tag::filterIntersections(), and setTop().
top
uint Gui::UnsignedValidator::top read write
Referenced by Mod.Test.unittestgui.TkTestRunner::createWidgets(), PathScripts.PathDressupHoldingTags.Tag::filterIntersections(), PathScripts.PathDressupHoldingTags.Tag::intersects(), Mod.Test.unittestgui.TkTestRunner::notifyTestStarted(), and setBottom().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SpinBox.h
Sources/FreeCAD/src/Gui/SpinBox.cpp