FreeCAD: CustomGLWidget Class Reference
CustomGLWidget Class Reference
Public Member Functions
void aboutToDestroyGLContext ()
CustomGLWidget (const QSurfaceFormat &format, QWidget *parent=nullptr, const QOpenGLWidget *shareWidget=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
bool event (QEvent *e)
void handleLoggedMessage (const QOpenGLDebugMessage &message)
void initializeGL ()
void paintGL ()
void showEvent (QShowEvent *)
void slotResized ()
~CustomGLWidget ()
Public Attributes
QSurfaceFormat myFormat
Constructor & Destructor Documentation
CustomGLWidget()
CustomGLWidget::CustomGLWidget (const QSurfaceFormat & format, QWidget * parent = nullptr, const QOpenGLWidget * shareWidget = nullptr, Qt::WindowFlags f = Qt::WindowFlags())
~CustomGLWidget()
CustomGLWidget::~CustomGLWidget ()
Member Function Documentation
aboutToDestroyGLContext()
void CustomGLWidget::aboutToDestroyGLContext ()
Referenced by initializeGL().
event()
bool CustomGLWidget::event (QEvent * e)
handleLoggedMessage()
void CustomGLWidget::handleLoggedMessage (const QOpenGLDebugMessage & message)
Referenced by initializeGL().
initializeGL()
void CustomGLWidget::initializeGL ()
References aboutToDestroyGLContext(), draftgeoutils.intersections::connect(), handleLoggedMessage(), and slotResized().
paintGL()
void CustomGLWidget::paintGL ()
showEvent()
void CustomGLWidget::showEvent (QShowEvent *)
slotResized()
void CustomGLWidget::slotResized ()
Referenced by initializeGL().
Member Data Documentation
myFormat
QSurfaceFormat CustomGLWidget::myFormat
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/Quarter/QuarterWidget.cpp