FreeCAD: Gui::LocationWidget Class Reference
Gui::LocationWidget Class Reference
#include <InputVector.h>
Public Member Functions
Base::Vector3d getDirection () const
Base::Vector3d getPosition () const
Base::Vector3d getUserDirection (bool *ok=nullptr) const
LocationWidget (QWidget *parent=nullptr)
void setDirection (const Base::Vector3d &dir)
void setPosition (const Base::Vector3d &)
QSize sizeHint () const
virtual ~LocationWidget ()
Constructor & Destructor Documentation
LocationWidget()
LocationWidget::LocationWidget (QWidget * parent = nullptr)
References draftgeoutils.intersections::connect(), Base::Unit::Length, Gui::QuantitySpinBox::setMaximum(), Gui::QuantitySpinBox::setMinimum(), and Gui::QuantitySpinBox::setUnit().
~LocationWidget()
LocationWidget::~LocationWidget () virtual
Member Function Documentation
getDirection()
Base::Vector3d LocationWidget::getDirection () const
getPosition()
Base::Vector3d LocationWidget::getPosition () const
References Base::Quantity::getValue(), and Gui::QuantitySpinBox::value.
getUserDirection()
Base::Vector3d LocationWidget::getUserDirection (bool * ok = nullptr) const
References Base::UnitsApi::getDecimals(), Gui::Dialog::Ui_InputVector::setupUi(), Gui::Dialog::Ui_InputVector::vectorX, Gui::Dialog::Ui_InputVector::vectorY, Gui::Dialog::Ui_InputVector::vectorZ, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
setDirection()
void LocationWidget::setDirection (const Base::Vector3d & dir)
References femsolver.report::display(), Base::Vector3< double >::epsilon(), Base::Vector3< _Precision >::Length(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
setPosition()
void LocationWidget::setPosition (const Base::Vector3d & v)
References Gui::QuantitySpinBox::setValue().
sizeHint()
QSize LocationWidget::sizeHint () const
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/InputVector.h
FreeCAD/src/Gui/InputVector.cpp