FreeCAD: importIFCmulticore Namespace Reference
importIFCmulticore Namespace Reference
Functions
def createLayer (obj, ifcproduct)
def createMaterial (obj, ifcproduct)
def createModelStructure (obj, ifcobj)
def createProduct (ifcproduct, brep)
def insert (filename, docname=None, preferences=None)
def open (filename)
def processRelationships ()
def setAttributes (obj, ifcproduct)
def setColor (obj, ifcproduct)
def setProperties (obj, ifcproduct)
def setRelationships (obj, ifcobj)
def storeColorDict ()
def writeProgress (count=None, total=None, starttime=None)
Variables
dictionary adds = {}
dictionary colors = {}
dictionary layers = {}
dictionary materials = {}
dictionary objects = {}
dictionary subs = {}
Function Documentation
createLayer()
def importIFCmulticore.createLayer (obj, ifcproduct)
sets the layer of a component
Referenced by createProduct().
createMaterial()
def importIFCmulticore.createMaterial (obj, ifcproduct)
sets the material of a component
References importIFCHelper.getColorFromMaterial().
Referenced by createProduct().
createModelStructure()
def importIFCmulticore.createModelStructure (obj, ifcobj)
sets the parent containers of an IFC object
References createModelStructure(), importIFCHelper.getParents(), setAttributes(), and setProperties().
Referenced by createModelStructure(), and createProduct().
createProduct()
def importIFCmulticore.createProduct (ifcproduct, brep)
creates an Arch object from an IFC product
References createLayer(), createMaterial(), createModelStructure(), setAttributes(), setColor(), setProperties(), and setRelationships().
Referenced by insert().
insert()
def importIFCmulticore.insert (filename, docname = None, preferences = None)
imports the contents of an IFC file in the given document
References importIFCHelper.createAnnotation(), createProduct(), importIFC.getPreferences(), importIFCHelper.getScaling(), processRelationships(), storeColorDict(), and writeProgress().
Referenced by importIFC.insert(), and open().
open()
def importIFCmulticore.open (filename)
References insert().
processRelationships()
def importIFCmulticore.processRelationships ()
process all stored relationships
Referenced by insert().
setAttributes()
def importIFCmulticore.setAttributes (obj, ifcproduct)
sets the IFC attributes of a component
References ArchIFC.uncamel().
Referenced by createModelStructure(), and createProduct().
setColor()
def importIFCmulticore.setColor (obj, ifcproduct)
sets the color of an object
References importIFCHelper.getColorFromProduct().
Referenced by createProduct().
setProperties()
def importIFCmulticore.setProperties (obj, ifcproduct)
sets the IFC properties of a component
Referenced by createModelStructure(), and createProduct().
setRelationships()
def importIFCmulticore.setRelationships (obj, ifcobj)
sets additions/subtractions
Referenced by createProduct().
storeColorDict()
def importIFCmulticore.storeColorDict ()
stores the color dictionary in the document Meta if non-GUI mode
Referenced by insert().
writeProgress()
def importIFCmulticore.writeProgress (count = None, total = None, starttime = None)
write progress to console
Referenced by insert().
Variable Documentation
adds
dictionary importIFCmulticore.adds = {}
colors
dictionary importIFCmulticore.colors = {}
layers
dictionary importIFCmulticore.layers = {}
materials
dictionary importIFCmulticore.materials = {}
objects
dictionary importIFCmulticore.objects = {}
subs
dictionary importIFCmulticore.subs = {}