FreeCAD: DrawSketchHandlerSlot Class Reference
DrawSketchHandlerSlot Class Reference
Create Slot.
Public Types
enum BoxMode { STATUS_SEEK_First, STATUS_SEEK_Second, STATUS_End }
mode table
Public Member Functions
virtual void activated (ViewProviderSketch *)
DrawSketchHandlerSlot ()
virtual void mouseMove (Base::Vector2d onSketchPos)
virtual bool pressButton (Base::Vector2d onSketchPos)
virtual bool releaseButton (Base::Vector2d onSketchPos)
virtual ~DrawSketchHandlerSlot ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::none, bool createowncommand=true)
virtual void deactivated (ViewProviderSketch *)
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual void quit (void)
virtual void registerPressedKey (bool, int)
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Attributes
double a
std::vector< Base::Vector2d > EditCurve
double lx
double ly
BoxMode Mode
double r
Base::Vector2d StartPos
std::vector< AutoConstraint > sugConstr1
std::vector< AutoConstraint > sugConstr2
Protected Attributes inherited from SketcherGui::DrawSketchHandler
QCursor actCursor
QPixmap actCursorPixmap
QCursor oldCursor
ViewProviderSketch * sketchgui
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
void addCursorTail (std::vector< QPixmap > &pixmaps)
void applyCursor (QCursor &newCursor)
void applyCursor (void)
qreal devicePixelRatio ()
unsigned long getCrosshairColor ()
void setCrosshairColor ()
void setCrosshairCursor (const char *svgName)
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
Sets a cursor for 3D inventor view.
void setSvgCursor (const QString &svgName, int x, int y, const std::map< unsigned long, unsigned long > &colorMapping=std::map< unsigned long, unsigned long >())
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
void unsetCursor (void)
Detailed Description
Create Slot.
Member Enumeration Documentation
BoxMode
enum DrawSketchHandlerSlot::BoxMode
mode table
Enumerator
STATUS_SEEK_First
enum value -—.
STATUS_SEEK_Second
enum value -—.
STATUS_End
Constructor & Destructor Documentation
DrawSketchHandlerSlot()
DrawSketchHandlerSlot::DrawSketchHandlerSlot ()
~DrawSketchHandlerSlot()
virtual DrawSketchHandlerSlot::~DrawSketchHandlerSlot () virtual
Member Function Documentation
activated()
virtual void DrawSketchHandlerSlot::activated (ViewProviderSketch *) virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::setCrosshairCursor().
mouseMove()
virtual void DrawSketchHandlerSlot::mouseMove (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References a, SketcherGui::DrawSketchHandler::applyCursor(), SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, lx, ly, Mode, SketcherGui::DrawSketchHandler::renderSuggestConstraintsCursor(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), SketcherGui::DrawSketchHandler::setPositionText(), Base::sgn(), SketcherGui::DrawSketchHandler::sketchgui, StartPos, STATUS_SEEK_First, STATUS_SEEK_Second, sugConstr1, sugConstr2, Base::Vector2d::x, and Base::Vector2d::y.
pressButton()
virtual bool DrawSketchHandlerSlot::pressButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References Mode, StartPos, STATUS_End, STATUS_SEEK_First, and STATUS_SEEK_Second.
releaseButton()
virtual bool DrawSketchHandlerSlot::releaseButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), SketcherGui::DrawSketchHandler::applyCursor(), Gui::Command::commitCommand(), Base::Console(), SketcherGui::DrawSketchHandler::createAutoConstraints(), Gui::Command::Doc, SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, Sketcher::end, Base::ConsoleSingleton::Error(), SketcherGui::geometryCreationMode, App::GetApplication(), ParameterGrp::GetBool(), SketcherGui::DrawSketchHandler::getHighestCurveIndex(), Gui::ViewProviderDocumentObject::getObject(), Gui::Command::getObjectCmd(), App::Application::GetParameterGroupByPath(), lx, ly, Sketcher::mid, Mode, Gui::Command::openCommand(), SketcherGui::ViewProviderSketch::purgeHandler(), draftutils.translate::QT_TRANSLATE_NOOP, SketcherGui::DrawSketchHandler::resetPositionText(), SketcherGui::DrawSketchHandler::sketchgui, StartPos, STATUS_End, STATUS_SEEK_First, sugConstr1, sugConstr2, SketcherGui::tryAutoRecompute(), SketcherGui::tryAutoRecomputeIfNotSolve(), SketcherGui::DrawSketchHandler::unsetCursor(), Base::Vector2d::x, and Base::Vector2d::y.
Member Data Documentation
a
double DrawSketchHandlerSlot::a protected
Referenced by mouseMove().
EditCurve
std::vector<Base::Vector2d> DrawSketchHandlerSlot::EditCurve protected
Referenced by mouseMove(), and releaseButton().
lx
double DrawSketchHandlerSlot::lx protected
Referenced by mouseMove(), and releaseButton().
ly
double DrawSketchHandlerSlot::ly protected
Referenced by mouseMove(), and releaseButton().
Mode
BoxMode DrawSketchHandlerSlot::Mode protected
Referenced by mouseMove(), pressButton(), and releaseButton().
r
double DrawSketchHandlerSlot::r protected
StartPos
Base::Vector2d DrawSketchHandlerSlot::StartPos protected
Referenced by mouseMove(), pressButton(), and releaseButton().
sugConstr1
std::vector<AutoConstraint> DrawSketchHandlerSlot::sugConstr1 protected
Referenced by mouseMove(), and releaseButton().
sugConstr2
std::vector<AutoConstraint> DrawSketchHandlerSlot::sugConstr2 protected
Referenced by mouseMove(), and releaseButton().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/Gui/CommandCreateGeo.cpp