FreeCAD: Robot::TrajectoryPy Class Reference
Robot::TrajectoryPy Class Reference
The python export class for Trajectory.
#include <TrajectoryPy.h>
Public Types
typedef Trajectory * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
TrajectoryPy (Trajectory *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of TrajectoryPy.
static PyMethodDef Methods []
Methods structure of TrajectoryPy.
static PyTypeObject Type
Type structure of TrajectoryPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~TrajectoryPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * insertWaypoints (PyObject *args)
implementer for the insertWaypoints() method
PyObject * position (PyObject *args)
implementer for the position() method
PyObject * velocity (PyObject *args)
implementer for the velocity() method
PyObject * deleteLast (PyObject *args)
implementer for the deleteLast() method
static PyObject * staticCallback_insertWaypoints (PyObject *self, PyObject *args)
callback for the insertWaypoints() method
static PyObject * staticCallback_position (PyObject *self, PyObject *args)
callback for the position() method
static PyObject * staticCallback_velocity (PyObject *self, PyObject *args)
callback for the velocity() method
static PyObject * staticCallback_deleteLast (PyObject *self, PyObject *args)
callback for the deleteLast() method
callbacks and implementers for the python object attributes
Py::Float getDuration (void) const
getter for the Duration attribute
Py::Float getLength (void) const
getter for the Length attribute
Py::List getWaypoints (void) const
getter for the Waypoints attribute
void setWaypoints (Py::List arg)
setter for the Waypoints attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Trajectory * getTrajectoryPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getDuration (PyObject *self, void *closure)
getter callback for the Duration attribute
static int staticCallback_setDuration (PyObject *self, PyObject *value, void *closure)
setter callback for the Duration attribute
static PyObject * staticCallback_getLength (PyObject *self, void *closure)
getter callback for the Length attribute
static int staticCallback_setLength (PyObject *self, PyObject *value, void *closure)
setter callback for the Length attribute
static PyObject * staticCallback_getWaypoints (PyObject *self, void *closure)
getter callback for the Waypoints attribute
static int staticCallback_setWaypoints (PyObject *self, PyObject *value, void *closure)
setter callback for the Waypoints attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Trajectory.
Member Typedef Documentation
PointerType
typedef Trajectory* Robot::TrajectoryPy::PointerType
Constructor & Destructor Documentation
~TrajectoryPy()
TrajectoryPy::~TrajectoryPy () protected
TrajectoryPy()
TrajectoryPy::TrajectoryPy (Trajectory * pcObject, PyTypeObject * T = &Type)
Referenced by deleteLast(), insertWaypoints(), and PyMake().
Member Function Documentation
deleteLast()
PyObject * TrajectoryPy::deleteLast (PyObject * args)
implementer for the deleteLast() method
References Robot::Trajectory::deleteLast(), getTrajectoryPtr(), and TrajectoryPy().
Referenced by staticCallback_deleteLast().
getCustomAttributes()
PyObject * TrajectoryPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getDuration()
Py::Float TrajectoryPy::getDuration (void) const
getter for the Duration attribute
References getTrajectoryPtr().
Referenced by staticCallback_getDuration().
getLength()
Py::Float TrajectoryPy::getLength (void) const
getter for the Length attribute
References getTrajectoryPtr().
Referenced by staticCallback_getLength().
getTrajectoryPtr()
Trajectory * TrajectoryPy::getTrajectoryPtr (void) const
getter for the object handled by this class
Referenced by deleteLast(), getDuration(), getLength(), getWaypoints(), insertWaypoints(), position(), PyInit(), representation(), Robot::PropertyTrajectory::setPyObject(), and velocity().
GetType()
virtual PyTypeObject* Robot::TrajectoryPy::GetType (void) virtual
Reimplemented from Base::PersistencePy.
getWaypoints()
Py::List TrajectoryPy::getWaypoints (void) const
getter for the Waypoints attribute
References Robot::Trajectory::getSize(), and getTrajectoryPtr().
Referenced by staticCallback_getWaypoints().
insertWaypoints()
PyObject * TrajectoryPy::insertWaypoints (PyObject * args)
implementer for the insertWaypoints() method
References Robot::Trajectory::addWaypoint(), Base::BaseExceptionFreeCADError, Robot::Trajectory::generateTrajectory(), getTrajectoryPtr(), TrajectoryPy(), Base::PlacementPy::Type, and Robot::WaypointPy::Type.
Referenced by staticCallback_insertWaypoints().
position()
PyObject * TrajectoryPy::position (PyObject * args)
implementer for the position() method
References getTrajectoryPtr().
Referenced by WorkingPlane.Plane::alignToPointAndAxis(), WorkingPlane.Plane::alignToPointAndAxis_SVG(), WorkingPlane.Plane::copy(), ifc2x3.ifcsweptsurface::dim(), ifc2x3.ifcelementarysurface::dim(), WorkingPlane.Plane::getGlobalCoords(), WorkingPlane.Plane::getLocalCoords(), WorkingPlane.Plane::getPlacement(), WorkingPlane.Plane::offsetToPoint(), WorkingPlane.Plane::restore(), WorkingPlane.Plane::save(), WorkingPlane.Plane::setFromPlacement(), and staticCallback_position().
PyInit()
int TrajectoryPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PersistencePy.
References Robot::Trajectory::addWaypoint(), Robot::Trajectory::generateTrajectory(), getTrajectoryPtr(), and Robot::WaypointPy::Type.
PyMake()
PyObject * TrajectoryPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References TrajectoryPy().
representation()
std::string TrajectoryPy::representation (void) const
References Robot::Trajectory::getDuration(), Robot::Trajectory::getLength(), Robot::Trajectory::getSize(), and getTrajectoryPtr().
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int TrajectoryPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setWaypoints()
void TrajectoryPy::setWaypoints (Py::List arg)
setter for the Waypoints attribute
Referenced by staticCallback_setWaypoints().
staticCallback_deleteLast()
PyObject * TrajectoryPy::staticCallback_deleteLast (PyObject * self, PyObject * args) static
callback for the deleteLast() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, deleteLast(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getDuration()
PyObject * TrajectoryPy::staticCallback_getDuration (PyObject * self, void * closure) static
getter callback for the Duration attribute
References Base::BaseExceptionFreeCADError, getDuration(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getLength()
PyObject * TrajectoryPy::staticCallback_getLength (PyObject * self, void * closure) static
getter callback for the Length attribute
References Base::BaseExceptionFreeCADError, getLength(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getWaypoints()
PyObject * TrajectoryPy::staticCallback_getWaypoints (PyObject * self, void * closure) static
getter callback for the Waypoints attribute
References Base::BaseExceptionFreeCADError, getWaypoints(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_insertWaypoints()
PyObject * TrajectoryPy::staticCallback_insertWaypoints (PyObject * self, PyObject * args) static
callback for the insertWaypoints() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, insertWaypoints(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_position()
PyObject * TrajectoryPy::staticCallback_position (PyObject * self, PyObject * args) static
callback for the position() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), position(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_setDuration()
int TrajectoryPy::staticCallback_setDuration (PyObject * self, PyObject * value, void * closure) static
setter callback for the Duration attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setLength()
int TrajectoryPy::staticCallback_setLength (PyObject * self, PyObject * value, void * closure) static
setter callback for the Length attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setWaypoints()
int TrajectoryPy::staticCallback_setWaypoints (PyObject * self, PyObject * value, void * closure) static
setter callback for the Waypoints attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setWaypoints().
staticCallback_velocity()
PyObject * TrajectoryPy::staticCallback_velocity (PyObject * self, PyObject * args) static
callback for the velocity() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and velocity().
velocity()
PyObject * TrajectoryPy::velocity (PyObject * args)
implementer for the velocity() method
References getTrajectoryPtr().
Referenced by staticCallback_velocity().
Member Data Documentation
GetterSetter
PyGetSetDef TrajectoryPy::GetterSetter static
Initial value:
= {
    {"Duration",
        (getter) staticCallback_getDuration,
        (setter) staticCallback_setDuration,
        "duration of the trajectory",
        NULL
    },
    {"Length",
        (getter) staticCallback_getLength,
        (setter) staticCallback_setLength,
        "length of the trajectory",
        NULL
    },
    {"Waypoints",
        (getter) staticCallback_getWaypoints,
        (setter) staticCallback_setWaypoints,
        "waypoints of this trajectory",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of TrajectoryPy.
Methods
PyMethodDef TrajectoryPy::Methods static
Initial value:
= {
    {"insertWaypoints",
        reinterpret_cast<PyCFunction>( staticCallback_insertWaypoints ),
        METH_VARARGS,
        "\n                               adds one or a list of waypoint to the end of the trajectory\n                   "
    },
    {"position",
        reinterpret_cast<PyCFunction>( staticCallback_position ),
        METH_VARARGS,
        "\n                               returns a Frame to a given time in the trajectory\n                     "
    },
    {"velocity",
        reinterpret_cast<PyCFunction>( staticCallback_velocity ),
        METH_VARARGS,
        "\n          returns the velocity to a given time in the trajectory\n        "
    },
    {"deleteLast",
        reinterpret_cast<PyCFunction>( staticCallback_deleteLast ),
        METH_VARARGS,
        "\n          deleteLast(n) - delete n waypoints at the end\n          deleteLast()  - delete the last waypoint\n        "
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of TrajectoryPy.
Type
PyTypeObject TrajectoryPy::Type static
Type structure of TrajectoryPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), ArchReference.ArchReference::setProperties(), and Robot::PropertyTrajectory::setPyObject().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Robot/App/TrajectoryPy.h
Sources/FreeCAD/src/Mod/Robot/App/TrajectoryPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Robot/App/TrajectoryPy.cpp