FreeCAD: FemGui::DlgSettingsFemElmerImp Class Reference
FemGui::DlgSettingsFemElmerImp Class Reference
#include <DlgSettingsFemElmerImp.h>
Public Member Functions
DlgSettingsFemElmerImp (QWidget *parent=nullptr)
~DlgSettingsFemElmerImp ()
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Slots
void onfileNameChanged (QString FileName)
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void loadSettings ()
void saveSettings ()
virtual void changeEvent (QEvent *e)=0
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Constructor & Destructor Documentation
DlgSettingsFemElmerImp()
DlgSettingsFemElmerImp::DlgSettingsFemElmerImp (QWidget * parent = nullptr)
References draftgeoutils.intersections::connect(), Gui::FileChooser::fileNameChanged(), and onfileNameChanged().
~DlgSettingsFemElmerImp()
DlgSettingsFemElmerImp::~DlgSettingsFemElmerImp ()
Member Function Documentation
changeEvent()
void DlgSettingsFemElmerImp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
loadSettings()
void DlgSettingsFemElmerImp::loadSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
onfileNameChanged
void DlgSettingsFemElmerImp::onfileNameChanged (QString FileName) protected slot
Referenced by DlgSettingsFemElmerImp().
saveSettings()
void DlgSettingsFemElmerImp::saveSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/DlgSettingsFemElmerImp.h
FreeCAD/src/Mod/Fem/Gui/DlgSettingsFemElmerImp.cpp