FreeCAD: PartGui::TaskDlgAttacher Class Reference
PartGui::TaskDlgAttacher Class Reference
simulation dialog for the TaskView
#include <TaskAttacher.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void clicked (int)
is called by the framework if an button is clicked which has no accept or reject role
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
returns for Close and Help button
Gui::ViewProviderDocumentObject * getViewProvider () const
virtual bool isAllowedAlterDocument (void) const
is called by the framework if the user presses the help button
virtual void open ()
is called the TaskView when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgAttacher (Gui::ViewProviderDocumentObject *ViewProvider, bool createBox=true)
~TaskDlgAttacher ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
ButtonPosition buttonPosition () const
bool canClose () const
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Protected Attributes
TaskAttacher * parameter
Gui::ViewProviderDocumentObject * ViewProvider
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
simulation dialog for the TaskView
Constructor & Destructor Documentation
TaskDlgAttacher()
TaskDlgAttacher::TaskDlgAttacher (Gui::ViewProviderDocumentObject * ViewProvider, bool createBox = true)
References Gui::TaskView::TaskDialog::Content, parameter, and Gui::TaskView::TaskDialog::setDocumentName().
~TaskDlgAttacher()
TaskDlgAttacher::~TaskDlgAttacher ()
Member Function Documentation
accept()
bool TaskDlgAttacher::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Reimplemented in PartDesignGui::TaskDlgDatumParameters.
References Part::AttachExtension::AttachmentOffset, Gui::cmdAppObject(), Gui::cmdAppObjectArgs(), Gui::cmdGuiDocument(), Gui::Document::commitCommand(), Gui::TaskView::TaskDialog::getDocumentName(), App::ExtensionContainer::getExtensionByType(), Base::Placement::getPosition(), App::PropertyLinkSubList::getPyReprString(), Base::Placement::getRotation(), App::PropertyPlacement::getValue(), App::PropertyEnumeration::getValue(), App::PropertyFloat::getValue(), App::PropertyBool::getValue(), Base::Rotation::getYawPitchRoll(), Part::AttachExtension::MapMode, Part::AttachExtension::MapPathParameter, Part::AttachExtension::MapReversed, parameter, Part::AttachExtension::Support, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by PartDesignGui::TaskDlgDatumParameters::accept(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
clicked()
void TaskDlgAttacher::clicked (int) virtual
is called by the framework if an button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
getStandardButtons()
virtual QDialogButtonBox::StandardButtons PartGui::TaskDlgAttacher::getStandardButtons (void) const virtual
returns for Close and Help button
Reimplemented from Gui::TaskView::TaskDialog.
getViewProvider()
Gui::ViewProviderDocumentObject* PartGui::TaskDlgAttacher::getViewProvider () const
Referenced by PartDesignGui::ViewProviderDatum::setEdit().
isAllowedAlterDocument()
virtual bool PartGui::TaskDlgAttacher::isAllowedAlterDocument (void) const virtual
is called by the framework if the user presses the help button
Reimplemented from Gui::TaskView::TaskDialog.
open()
void TaskDlgAttacher::open () virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Application::getDocument(), Gui::Application::Instance, Gui::Document::openCommand(), and draftutils.translate::QT_TRANSLATE_NOOP.
reject()
bool TaskDlgAttacher::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Reimplemented in PartDesignGui::TaskDlgDatumParameters.
References Gui::Document::abortCommand(), Gui::Command::Doc, Gui::TaskView::TaskDialog::getDocumentName(), and Gui::Command::Gui.
Referenced by PartDesignGui::TaskDlgDatumParameters::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
Member Data Documentation
parameter
TaskAttacher* PartGui::TaskDlgAttacher::parameter protected
Referenced by accept(), PartDesignGui::TaskDlgDatumParameters::accept(), Mod.Test.Document.DocumentObserverCases.Observer::slotAbortTransaction(), Mod.Test.Document.DocumentObserverCases.Observer::slotActivateDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotActivateDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotAddedDynamicExtension(), Mod.Test.Document.DocumentObserverCases.Observer::slotAppendDynamicProperty(), Mod.Test.Document.DocumentObserverCases.Observer::slotBeforeAddingDynamicExtension(), Mod.Test.Document.DocumentObserverCases.Observer::slotBeforeChangeDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotBeforeChangeObject(), Mod.Test.Document.DocumentObserverCases.Observer::slotChangedDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotChangedObject(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotChangedObject(), Mod.Test.Document.DocumentObserverCases.Observer::slotChangePropertyEditor(), Mod.Test.Document.DocumentObserverCases.Observer::slotCommitTransaction(), Mod.Test.Document.DocumentObserverCases.Observer::slotCreatedDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotCreatedDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotCreatedObject(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotCreatedObject(), Mod.Test.Document.DocumentObserverCases.Observer::slotDeletedDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotDeletedDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotDeletedObject(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotDeletedObject(), Mod.Test.Document.DocumentObserverCases.Observer::slotFinishSaveDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotInEdit(), Mod.Test.Document.DocumentObserverCases.Observer::slotOpenTransaction(), Mod.Test.Document.DocumentObserverCases.Observer::slotRecomputedDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotRecomputedObject(), Mod.Test.Document.DocumentObserverCases.Observer::slotRedoDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotRelabelDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotRelabelDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotRemoveDynamicProperty(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotRenameDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotResetEdit(), Mod.Test.Document.DocumentObserverCases.Observer::slotStartSaveDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotUndoDocument(), TaskDlgAttacher(), and PartDesignGui::TaskDlgDatumParameters::TaskDlgDatumParameters().
ViewProvider
Gui::ViewProviderDocumentObject* PartGui::TaskDlgAttacher::ViewProvider protected
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/Gui/TaskAttacher.h
Sources/FreeCAD/src/Mod/Part/Gui/TaskAttacher.cpp