FreeCAD: TechDrawGui::QGIViewSymbol Class Reference
TechDrawGui::QGIViewSymbol Class Reference
#include <QGIViewSymbol.h>
Public Types
enum { Type = QGraphicsItem::UserType + 121 }
Public Types inherited from TechDrawGui::QGIView
enum { Type = QGraphicsItem::UserType + 101 }
Public Member Functions
virtual void draw () override
QGIViewSymbol ()
virtual void rotateView (void) override
void setViewSymbolFeature (TechDraw::DrawViewSymbol *obj)
int type () const override
virtual void updateView (bool update=false) override
~QGIViewSymbol ()
Public Member Functions inherited from TechDrawGui::QGIView
virtual void addArbitraryItem (QGraphicsItem *qgi)
void alignTo (QGraphicsItem *, const QString &alignment)
virtual QRectF boundingRect () const override
virtual void drawBorder (void)
virtual void drawCaption (void)
QGIViewClip * getClipGroup (void)
virtual QColor getCurrentColor (void)
virtual bool getFrameState (void)
MDIViewPage * getMDIViewPage (void) const
virtual QColor getNormalColor (void)
virtual QColor getPreColor (void)
double getScale (void)
virtual QColor getSelectColor (void)
virtual QColor getSettingColor (void)
const char * getViewName () const
const std::string getViewNameAsString () const
TechDraw::DrawView * getViewObject () const
virtual void isVisible (bool state)
virtual bool isVisible (void)
void makeMark (Base::Vector3d v, QColor c=Qt::red)
void makeMark (double x, double y, QColor c=Qt::red)
void makeMark (QPointF p, QColor c=Qt::red)
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) override
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QGIView ()
virtual void removeChild (QGIView *child)
virtual void setGroupSelection (bool b)
void setLocked (bool b)
virtual void setSettingColor (QColor c)
void setViewFeature (TechDraw::DrawView *obj)
virtual void toggleCache (bool state)
int type () const override
virtual ~QGIView ()
void setPosition (qreal x, qreal y)
Methods to ensure that Y-Coordinates are orientated correctly.
qreal getY ()
bool isInnerView ()
void isInnerView (bool state)
double getYInClip (double y)
Protected Member Functions
virtual void drawSvg ()
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void symbolToSvg (QByteArray qba)
Protected Member Functions inherited from TechDrawGui::QGIView
virtual QRectF customChildrenBoundingRect (void) const
void dumpRect (const char *text, QRectF r)
Base::Reference< ParameterGrp > getParmGroupCol (void)
QGIView * getQGIVByName (std::string name)
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
Protected Attributes
QGDisplayArea * m_displayArea
QGCustomSvg * m_svgItem
Protected Attributes inherited from TechDrawGui::QGIView
QHash< QString, QGraphicsItem * > alignHash
QGCustomBorder * m_border
QBrush m_brush
QGICaption * m_caption
QColor m_colCurrent
QColor m_colNormal
QColor m_colPre
QColor m_colSel
QColor m_colSetting
QPen m_decorPen
QFont m_font
bool m_innerView
QGCustomLabel * m_label
QGCustomImage * m_lock
bool m_locked
double m_lockHeight
double m_lockWidth
QPen m_pen
std::string viewName
TechDraw::DrawView * viewObj
Additional Inherited Members
Public Slots inherited from TechDrawGui::QGIView
virtual void onSourceChange (TechDraw::DrawView *newParent)
Static Public Member Functions inherited from TechDrawGui::QGIView
static int calculateFontPixelSize (double sizeInMillimetres)
static int calculateFontPixelWidth (const QFont &font)
static double getDimFontSize (void)
static QGVPage * getGraphicsView (TechDraw::DrawView *dv)
static QString getPrefFont (void)
static double getPrefFontSize (void)
static Gui::ViewProvider * getViewProvider (App::DocumentObject *obj)
Public Attributes inherited from TechDrawGui::QGIView
boost::signals2::signal< void(QGIView *, QPointF)> signalSelectPoint
Static Public Attributes inherited from TechDrawGui::QGIView
static const double DefaultFontSizeInMM = 5.0
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGIViewSymbol()
QGIViewSymbol::QGIViewSymbol ()
References TechDrawGui::QGCustomSvg::centerAt(), TechDrawGui::QGDisplayArea::centerAt(), m_displayArea, and m_svgItem.
~QGIViewSymbol()
QGIViewSymbol::~QGIViewSymbol ()
Member Function Documentation
draw()
void QGIViewSymbol::draw (void) override virtual
Reimplemented from TechDrawGui::QGIView.
References TechDrawGui::QGIView::draw(), drawSvg(), and TechDrawGui::QGIView::isVisible().
Referenced by updateView().
drawSvg()
void QGIViewSymbol::drawSvg () protected virtual
References Base::Persistence::getClassTypeId(), TechDrawGui::Rez::getRezFactor(), TechDrawGui::QGIView::getViewObject(), m_svgItem, rotateView(), and symbolToSvg().
Referenced by draw().
itemChange()
QVariant QGIViewSymbol::itemChange (GraphicsItemChange change, const QVariant & value) override protected virtual
Reimplemented from TechDrawGui::QGIView.
References TechDrawGui::QGIView::itemChange().
rotateView()
void QGIViewSymbol::rotateView (void) override virtual
Reimplemented from TechDrawGui::QGIView.
References TechDrawGui::QGDisplayArea::boundingRect(), App::PropertyQuantity::getValue(), TechDrawGui::QGIView::getViewObject(), m_displayArea, and TechDraw::DrawView::Rotation.
Referenced by drawSvg().
setViewSymbolFeature()
void QGIViewSymbol::setViewSymbolFeature (TechDraw::DrawViewSymbol * obj)
References TechDrawGui::QGIView::setViewFeature().
symbolToSvg()
void QGIViewSymbol::symbolToSvg (QByteArray qba) protected
References TechDrawGui::QGCustomSvg::centerAt(), Base::Console(), Base::ConsoleSingleton::Error(), TechDrawGui::QGIView::getViewName(), TechDrawGui::QGCustomSvg::load(), and m_svgItem.
Referenced by drawSvg().
type()
int TechDrawGui::QGIViewSymbol::type (void) const override
updateView()
void QGIViewSymbol::updateView (bool update = false) override virtual
Reimplemented from TechDrawGui::QGIView.
References draw(), TechDrawGui::QGIView::getViewObject(), and TechDrawGui::QGIView::updateView().
Member Data Documentation
m_displayArea
QGDisplayArea* TechDrawGui::QGIViewSymbol::m_displayArea protected
Referenced by QGIViewSymbol(), and rotateView().
m_svgItem
QGCustomSvg* TechDrawGui::QGIViewSymbol::m_svgItem protected
Referenced by drawSvg(), QGIViewSymbol(), and symbolToSvg().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGIViewSymbol.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGIViewSymbol.cpp