FreeCAD: DrawSketchHandlerCoincident Class Reference
DrawSketchHandlerCoincident Class Reference
Public Member Functions
virtual void activated (ViewProviderSketch *)
DrawSketchHandlerCoincident ()
virtual void mouseMove (Base::Vector2d onSketchPos)
virtual bool pressButton (Base::Vector2d onSketchPos)
virtual bool releaseButton (Base::Vector2d onSketchPos)
virtual ~DrawSketchHandlerCoincident ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::none, bool createowncommand=true)
virtual void deactivated (ViewProviderSketch *)
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual void quit (void)
virtual void registerPressedKey (bool, int)
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Attributes
int GeoId1
int GeoId2
Sketcher::PointPos PosId1
Sketcher::PointPos PosId2
Protected Attributes inherited from SketcherGui::DrawSketchHandler
QCursor actCursor
QPixmap actCursorPixmap
QCursor oldCursor
ViewProviderSketch * sketchgui
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
void addCursorTail (std::vector< QPixmap > &pixmaps)
void applyCursor (QCursor &newCursor)
void applyCursor (void)
qreal devicePixelRatio ()
unsigned long getCrosshairColor ()
void setCrosshairColor ()
void setCrosshairCursor (const char *svgName)
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
Sets a cursor for 3D inventor view.
void setSvgCursor (const QString &svgName, int x, int y, const std::map< unsigned long, unsigned long > &colorMapping=std::map< unsigned long, unsigned long >())
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
void unsetCursor (void)
Constructor & Destructor Documentation
DrawSketchHandlerCoincident()
DrawSketchHandlerCoincident::DrawSketchHandlerCoincident ()
References GeoId1, GeoId2, Sketcher::none, PosId1, and PosId2.
~DrawSketchHandlerCoincident()
virtual DrawSketchHandlerCoincident::~DrawSketchHandlerCoincident () virtual
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
activated()
virtual void DrawSketchHandlerCoincident::activated (ViewProviderSketch *) virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References Gui::SelectionSingleton::addSelectionGate(), Gui::ViewProviderDocumentObject::getObject(), Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), SketcherGui::SelRoot, SketcherGui::SelVertex, SketcherGui::GenericConstraintSelection::setAllowedSelTypes(), SketcherGui::DrawSketchHandler::setCursor(), and SketcherGui::DrawSketchHandler::sketchgui.
mouseMove()
virtual void DrawSketchHandlerCoincident::mouseMove (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
pressButton()
virtual bool DrawSketchHandlerCoincident::pressButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
releaseButton()
virtual bool DrawSketchHandlerCoincident::releaseButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), Gui::SelectionSingleton::addSelection(), Sketcher::SketchObject::arePointsCoincident(), Gui::SelectionSingleton::clearSelection(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), GeoId1, GeoId2, App::DocumentObject::getDocument(), Sketcher::SketchObject::getGeoVertexIndex(), App::Document::getName(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), SketcherGui::ViewProviderSketch::getPreselectCross(), SketcherGui::ViewProviderSketch::getPreselectPoint(), SketcherGui::ViewProviderSketch::getSketchObject(), Sketcher::none, Gui::Command::openCommand(), PosId1, PosId2, draftutils.translate::QT_TRANSLATE_NOOP, Sketcher::GeoEnum::RtPnt, Gui::Selection(), SketcherGui::DrawSketchHandler::sketchgui, Sketcher::start, Base::Vector2d::x, and Base::Vector2d::y.
Member Data Documentation
GeoId1
int DrawSketchHandlerCoincident::GeoId1 protected
Referenced by DrawSketchHandlerCoincident(), and releaseButton().
GeoId2
int DrawSketchHandlerCoincident::GeoId2 protected
Referenced by DrawSketchHandlerCoincident(), and releaseButton().
PosId1
Sketcher::PointPos DrawSketchHandlerCoincident::PosId1 protected
Referenced by DrawSketchHandlerCoincident(), and releaseButton().
PosId2
Sketcher::PointPos DrawSketchHandlerCoincident::PosId2 protected
Referenced by DrawSketchHandlerCoincident(), and releaseButton().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/Gui/CommandConstraints.cpp