FreeCAD: Points::PointsGridIterator Class Reference
Points::PointsGridIterator Class Reference
The PointsGridIterator class provides an interface to walk through all grid elements of a point grid.
#include <PointsGrid.h>
Classes
struct GridElement
Checks if a grid position is already visited by NextOnRay().
Public Member Functions
Base::BoundBox3d GetBoundBox (void) const
Returns the bounding box of the current grid element.
void GetElements (std::vector< unsigned long > &raulElements) const
Returns indices of the elements in the current grid.
PointsGridIterator (const PointsGrid &rclG)
Construction.
Iteration
void Init (void)
Sets the iterator to the first element.
bool More (void) const
Checks if the iterator has not yet reached the end position.
void Next (void)
Go to the next grid.
Tests with rays
bool InitOnRay (const Base::Vector3d &rclPt, const Base::Vector3d &rclDir, std::vector< unsigned long > &raulElements)
Searches for facets around the ray.
bool InitOnRay (const Base::Vector3d &rclPt, const Base::Vector3d &rclDir, float fMaxSearchArea, std::vector< unsigned long > &raulElements)
Searches for facets around the ray.
bool NextOnRay (std::vector< unsigned long > &raulElements)
Searches for facets around the ray.
void GetGridPos (unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
Returns the grid number of the current position.
Detailed Description
The PointsGridIterator class provides an interface to walk through all grid elements of a point grid.
Constructor & Destructor Documentation
PointsGridIterator()
PointsGridIterator::PointsGridIterator (const PointsGrid & rclG)
Construction.
Member Function Documentation
GetBoundBox()
Base::BoundBox3d Points::PointsGridIterator::GetBoundBox (void) const
Returns the bounding box of the current grid element.
Referenced by Points::PointsGrid::Verify().
GetElements()
void Points::PointsGridIterator::GetElements (std::vector< unsigned long > & raulElements) const
Returns indices of the elements in the current grid.
Referenced by Points::PointsGrid::Verify().
GetGridPos()
void Points::PointsGridIterator::GetGridPos (unsigned long & rulX, unsigned long & rulY, unsigned long & rulZ) const
Returns the grid number of the current position.
Init()
void Points::PointsGridIterator::Init (void)
Sets the iterator to the first element.
Referenced by Points::PointsGrid::Verify().
InitOnRay() [1/2]
bool PointsGridIterator::InitOnRay (const Base::Vector3d & rclPt, const Base::Vector3d & rclDir, float fMaxSearchArea, std::vector< unsigned long > & raulElements)
Searches for facets around the ray.
References InitOnRay().
InitOnRay() [2/2]
bool PointsGridIterator::InitOnRay (const Base::Vector3d & rclPt, const Base::Vector3d & rclDir, std::vector< unsigned long > & raulElements)
Searches for facets around the ray.
Referenced by InitOnRay().
More()
bool Points::PointsGridIterator::More (void) const
Checks if the iterator has not yet reached the end position.
Referenced by Points::PointsGrid::Verify().
Next()
void Points::PointsGridIterator::Next (void)
Go to the next grid.
Referenced by Points::PointsGrid::Verify().
NextOnRay()
bool PointsGridIterator::NextOnRay (std::vector< unsigned long > & raulElements)
Searches for facets around the ray.
References Base::BoundBox3< double >::BACK, Base::BoundBox3< double >::BOTTOM, Base::BoundBox3< double >::FRONT, Base::BoundBox3< double >::INVALID, Base::BoundBox3< double >::LEFT, Base::BoundBox3< double >::RIGHT, and Base::BoundBox3< double >::TOP.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Points/App/PointsGrid.h
Sources/FreeCAD/src/Mod/Points/App/PointsGrid.cpp