FreeCAD: StdMeshers_Adaptive1D Class Reference
StdMeshers_Adaptive1D Class Reference
Adaptive 1D hypothesis.
#include <StdMeshers_Adaptive1D.hxx>
Public Member Functions
SMESH_Algo * GetAlgo () const
Returns an algorithm that works using this hypothesis.
double GetDeflection () const
double GetMaxSize () const
double GetMinSize () const
virtual std::istream & LoadFrom (std::istream &load)
virtual std::ostream & SaveTo (std::ostream &save)
void SetDeflection (double value)
void SetMaxSize (double maxSegLen)
void SetMinSize (double minSegLen)
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)
Initialize deflection value by the mesh built on the geometry.
StdMeshers_Adaptive1D (int hypId, int studyId, SMESH_Gen *gen)
~StdMeshers_Adaptive1D ()
Public Member Functions inherited from SMESH_Hypothesis
void ClearParameters ()
virtual bool DataDependOnParams () const
The returned value is used by NotifySubMeshesHypothesisModification() to decide to call subMesh->AlgoStateEngine(MODIF_HYP, hyp) or not if subMesh is ready to be computed (algo+hyp==OK) but not yet computed. True result is reasonable for example if EventListeners depend on parameters of hypothesis.
virtual int GetDim () const
SMESH_Gen * GetGen () const
char * GetLastParameters () const
virtual const char * GetLibName () const
SMESH_Mesh * GetMeshByPersistentID (int id)
Find a mesh with given persistent ID.
char * GetParameters () const
virtual int GetShapeType () const
int GetStudyId () const
virtual bool IsAuxiliary () const
Return true if me is an auxiliary hypothesis.
virtual void NotifySubMeshesHypothesisModification ()
void SetLastParameters (const char *theParameters)
void SetLibName (const char *theLibName)
void SetParameters (const char *theParameters)
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)=0
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)=0
Initialize my parameter values by the mesh built on the geometry.
SMESH_Hypothesis (int hypId, int studyId, SMESH_Gen *gen)
virtual ~SMESH_Hypothesis ()
Public Member Functions inherited from SMESHDS_Hypothesis
int GetID () const
const char * GetName () const
int GetType () const
bool IsSameName (const SMESHDS_Hypothesis &other) const
Compare types of hypotheses.
virtual std::istream & LoadFrom (std::istream &load)=0
bool operator!= (const SMESHDS_Hypothesis &other) const
virtual bool operator== (const SMESHDS_Hypothesis &other) const
virtual std::ostream & SaveTo (std::ostream &save)=0
SMESHDS_Hypothesis (int hypId)
virtual ~SMESHDS_Hypothesis ()
Protected Attributes
SMESH_Algo * myAlgo
double myDeflection
double myMaxSize
double myMinSize
Additional Inherited Members
Public Types inherited from SMESH_Hypothesis
enum Hypothesis_Status {
HYP_OK = 0 , HYP_MISSING , HYP_CONCURENT , HYP_BAD_PARAMETER ,
HYP_HIDDEN_ALGO , HYP_HIDING_ALGO , HYP_UNKNOWN_FATAL , HYP_INCOMPATIBLE ,
HYP_NOTCONFORM , HYP_ALREADY_EXIST , HYP_BAD_DIM , HYP_BAD_SUBSHAPE ,
HYP_BAD_GEOMETRY , HYP_NEED_SHAPE , HYP_INCOMPAT_HYPS
}
Public Types inherited from SMESHDS_Hypothesis
enum hypothesis_type {
PARAM_ALGO , ALGO_0D , ALGO_1D , ALGO_2D ,
ALGO_3D
}
Static Public Member Functions inherited from SMESH_Hypothesis
static bool IsStatusFatal (Hypothesis_Status theStatus)
Detailed Description
Adaptive 1D hypothesis.
Constructor & Destructor Documentation
StdMeshers_Adaptive1D()
StdMeshers_Adaptive1D::StdMeshers_Adaptive1D (int hypId, int studyId, SMESH_Gen * gen)
References myAlgo, myDeflection, myMaxSize, and myMinSize.
~StdMeshers_Adaptive1D()
StdMeshers_Adaptive1D::~StdMeshers_Adaptive1D ()
References myAlgo.
Member Function Documentation
GetAlgo()
SMESH_Algo * StdMeshers_Adaptive1D::GetAlgo () const
Returns an algorithm that works using this hypothesis.
References myAlgo.
GetDeflection()
double StdMeshers_Adaptive1D::GetDeflection () const
GetMaxSize()
double StdMeshers_Adaptive1D::GetMaxSize () const
GetMinSize()
double StdMeshers_Adaptive1D::GetMinSize () const
LoadFrom()
istream & StdMeshers_Adaptive1D::LoadFrom (std::istream & load) virtual
Implements SMESHDS_Hypothesis.
References myDeflection, myMaxSize, and myMinSize.
SaveTo()
ostream & StdMeshers_Adaptive1D::SaveTo (std::ostream & save) virtual
Implements SMESHDS_Hypothesis.
References myDeflection, myMaxSize, myMinSize, and OfflineRenderingUtils::save().
SetDeflection()
void StdMeshers_Adaptive1D::SetDeflection (double value)
Sets <deflection> parameter value, i.e. a maximal allowed distance between a segment and an edge.
References myDeflection, and SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
SetMaxSize()
void StdMeshers_Adaptive1D::SetMaxSize (double maxSegLen)
Sets maximal allowed segment length
References myMaxSize, and SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
SetMinSize()
void StdMeshers_Adaptive1D::SetMinSize (double minSegLen)
Sets minimal allowed segment length
References myMinSize, and SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
SetParametersByDefaults()
bool StdMeshers_Adaptive1D::SetParametersByDefaults (const TDefaults & dflts, const SMESH_Mesh * theMesh = 0) virtual
Initialize my parameter values by default parameters.
Return values
bool - true if parameter values have been successfully defined
Implements SMESH_Hypothesis.
References myDeflection, myMaxSize, and myMinSize.
SetParametersByMesh()
bool StdMeshers_Adaptive1D::SetParametersByMesh (const SMESH_Mesh * theMesh, const TopoDS_Shape & theShape) virtual
Initialize deflection value by the mesh built on the geometry.
Parameters
theMesh - the built mesh
theShape - the geometry of interest
Return values
bool - true if parameter values have been successfully defined
Implements SMESH_Hypothesis.
References SMESHDS_SubMesh::GetElements(), SMESH_Mesh::GetMeshDS(), SMDS_MeshElement::GetNode(), SMESH_MesherHelper::GetNodeU(), SMESHDS_Mesh::MeshElements(), myDeflection, myMaxSize, myMinSize, SMESH_MesherHelper::SetSubShape(), and SMESH_TNodeXYZ::SquareDistance().
Member Data Documentation
myAlgo
SMESH_Algo* StdMeshers_Adaptive1D::myAlgo protected
Referenced by GetAlgo(), StdMeshers_Adaptive1D(), and ~StdMeshers_Adaptive1D().
myDeflection
double StdMeshers_Adaptive1D::myDeflection protected
Referenced by LoadFrom(), SaveTo(), SetDeflection(), SetParametersByDefaults(), SetParametersByMesh(), and StdMeshers_Adaptive1D().
myMaxSize
double StdMeshers_Adaptive1D::myMaxSize protected
Referenced by LoadFrom(), SaveTo(), SetMaxSize(), SetParametersByDefaults(), SetParametersByMesh(), and StdMeshers_Adaptive1D().
myMinSize
double StdMeshers_Adaptive1D::myMinSize protected
Referenced by LoadFrom(), SaveTo(), SetMinSize(), SetParametersByDefaults(), SetParametersByMesh(), and StdMeshers_Adaptive1D().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_Adaptive1D.hxx
FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_Adaptive1D.cpp