FreeCAD: Gui::Ui_DlgTreeWidget Class Reference
Gui::Ui_DlgTreeWidget Class Reference
#include <ui_DlgTreeWidget.h>
Public Member Functions
void retranslateUi (QDialog *Gui__DlgTreeWidget)
void setupUi (QDialog *Gui__DlgTreeWidget)
Public Attributes
QDialogButtonBox * buttonBox
QGridLayout * gridLayout
QGridLayout * gridLayout_2
QGroupBox * groupBox
QTreeWidget * treeWidget
Member Function Documentation
retranslateUi()
void Gui::Ui_DlgTreeWidget::retranslateUi (QDialog * Gui__DlgTreeWidget)
References groupBox, draftguitools.gui_setstyle::translate, and treeWidget.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::Ui_DlgTreeWidget::setupUi (QDialog * Gui__DlgTreeWidget)
References buttonBox, draftgeoutils.intersections::connect(), gridLayout, gridLayout_2, groupBox, retranslateUi(), and treeWidget.
Member Data Documentation
buttonBox
QDialogButtonBox* Gui::Ui_DlgTreeWidget::buttonBox
Referenced by PathScripts.PathGetPoint.TaskPanel::getPoint(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::modifyStandardButtons(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::pageDirtyChanged(), PathScripts.PathGetPoint.TaskPanel::pointFinish(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setClean(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setDirty(), and setupUi().
gridLayout
QGridLayout* Gui::Ui_DlgTreeWidget::gridLayout
Referenced by setupUi().
gridLayout_2
QGridLayout* Gui::Ui_DlgTreeWidget::gridLayout_2
Referenced by setupUi().
groupBox
QGroupBox* Gui::Ui_DlgTreeWidget::groupBox
Referenced by retranslateUi(), and setupUi().
treeWidget
QTreeWidget* Gui::Ui_DlgTreeWidget::treeWidget
Referenced by retranslateUi(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_DlgTreeWidget.h