FreeCAD: GCS::ConstraintMidpointOnLine Class Reference
GCS::ConstraintMidpointOnLine Class Reference
#include <Constraints.h>
Public Member Functions
ConstraintMidpointOnLine (Line &l1, Line &l2)
ConstraintMidpointOnLine (Point &l1p1, Point &l1p2, Point &l2p1, Point &l2p2)
virtual double error ()
virtual ConstraintType getTypeId ()
virtual double grad (double *)
virtual void rescale (double coef=1.)
Public Member Functions inherited from GCS::Constraint
Constraint ()
int findParamInPvec (double *param)
int getTag ()
bool isDriving () const
virtual double maxStep (MAP_pD_D &dir, double lim=1.)
VEC_pD params ()
void redirectParams (MAP_pD_pD redirectionmap)
void revertParams ()
void setDriving (bool isdriving)
void setTag (int tagId)
virtual ~Constraint ()
Constructor & Destructor Documentation
ConstraintMidpointOnLine() [1/2]
GCS::ConstraintMidpointOnLine::ConstraintMidpointOnLine (Line & l1, Line & l2)
References rescale().
ConstraintMidpointOnLine() [2/2]
GCS::ConstraintMidpointOnLine::ConstraintMidpointOnLine (Point & l1p1, Point & l1p2, Point & l2p1, Point & l2p2)
References rescale(), GCS::Point::x, and GCS::Point::y.
Member Function Documentation
error()
double GCS::ConstraintMidpointOnLine::error () virtual
Reimplemented from GCS::Constraint.
Referenced by femmesh.gmshtools.GmshTools::read_and_set_new_mesh(), FreeCADInit.FCADLogger::report(), and femmesh.gmshtools.GmshTools::run_gmsh_with_geo().
getTypeId()
ConstraintType GCS::ConstraintMidpointOnLine::getTypeId (void) virtual
Reimplemented from GCS::Constraint.
References GCS::MidpointOnLine.
grad()
double GCS::ConstraintMidpointOnLine::grad (double * param) virtual
Reimplemented from GCS::Constraint.
rescale()
void GCS::ConstraintMidpointOnLine::rescale (double coef = 1.) virtual
Reimplemented from GCS::Constraint.
Referenced by ConstraintMidpointOnLine().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Constraints.h
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Constraints.cpp