FreeCAD: PathScripts.PathGui Namespace Reference
PathScripts.PathGui Namespace Reference
Classes
class QuantitySpinBox
Functions
def disableItem (item)
def findItem (docitem, objname)
def getDocNode ()
def populateCombobox (form, enumTups, comboBoxesPropertyMap)
def updateInputField (obj, prop, widget, onBeforeChange=None)
Function Documentation
disableItem()
def PathScripts.PathGui.disableItem (item)
References PathScripts.PathGui.disableItem().
Referenced by PathScripts.PathGui.disableItem().
findItem()
def PathScripts.PathGui.findItem (docitem, objname)
References PathScripts.PathGui.findItem().
Referenced by PathScripts.PathGui.findItem().
getDocNode()
def PathScripts.PathGui.getDocNode ()
populateCombobox()
def PathScripts.PathGui.populateCombobox (form, enumTups, comboBoxesPropertyMap)
populateCombobox(form, enumTups, comboBoxesPropertyMap) ... populate comboboxes with translated enumerations
** comboBoxesPropertyMap will be unnecessary if UI files use strict combobox naming protocol.
Args:
    form = UI form
    enumTups = list of (translated_text, data_string) tuples
    comboBoxesPropertyMap = list of (translated_text, data_string) tuples
updateInputField()
def PathScripts.PathGui.updateInputField (obj, prop, widget, onBeforeChange = None)
updateInputField(obj, prop, widget) ... update obj's property prop with the value of widget.
The property's value is only assigned if the new value differs from the current value.
This prevents onChanged notifications where the value didn't actually change.
Gui::InputField and Gui::QuantitySpinBox widgets are supported - and the property can
be of type Quantity or Float.
If onBeforeChange is specified it is called before a new value is assigned to the property.
Returns True if a new value was assigned, False otherwise (new value is the same as the current).
Referenced by PathScripts.PathGui.QuantitySpinBox.updateProperty().