FreeCAD: FemGui::TaskDlgCreateNodeSet Class Reference
FemGui::TaskDlgCreateNodeSet Class Reference
simulation dialog for the TaskView
#include <TaskDlgCreateNodeSet.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
returns for Close and Help button
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual void open ()
is called the TaskView when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgCreateNodeSet (Fem::FemSetNodesObject *)
~TaskDlgCreateNodeSet ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
tells the framework which buttons are wished for the dialog
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Protected Attributes
Fem::FemSetNodesObject * FemSetNodesObject
TaskObjectName * name
TaskCreateNodeSet * param
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
simulation dialog for the TaskView
Constructor & Destructor Documentation
TaskDlgCreateNodeSet()
TaskDlgCreateNodeSet::TaskDlgCreateNodeSet (Fem::FemSetNodesObject * obj)
References Gui::TaskView::TaskDialog::Content, and param.
~TaskDlgCreateNodeSet()
TaskDlgCreateNodeSet::~TaskDlgCreateNodeSet ()
Member Function Documentation
accept()
bool TaskDlgCreateNodeSet::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References Base::Console(), FemSetNodesObject, Gui::Command::Gui, App::DocumentObject::Label, FemGui::TaskCreateNodeSet::MeshViewProvider, Fem::FemSetNodesObject::Nodes, param, App::DocumentObject::recomputeFeature(), FemGui::ViewProviderFemMesh::resetHighlightNodes(), App::PropertyString::setValue(), App::PropertyIntegerSet::setValues(), FemGui::TaskCreateNodeSet::tempSet, and Base::ConsoleSingleton::Warning().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
getStandardButtons()
virtual QDialogButtonBox::StandardButtons FemGui::TaskDlgCreateNodeSet::getStandardButtons (void) const virtual
returns for Close and Help button
Reimplemented from Gui::TaskView::TaskDialog.
helpRequested()
void TaskDlgCreateNodeSet::helpRequested () virtual
is called by the framework if the user press the help button
Reimplemented from Gui::TaskView::TaskDialog.
open()
void TaskDlgCreateNodeSet::open () virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
reject()
bool TaskDlgCreateNodeSet::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Command::abortCommand(), Fem::FemSetNodesObject::execute(), FemSetNodesObject, Gui::Command::Gui, FemGui::TaskCreateNodeSet::MeshViewProvider, param, and FemGui::ViewProviderFemMesh::resetHighlightNodes().
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
Member Data Documentation
FemSetNodesObject
Fem::FemSetNodesObject* FemGui::TaskDlgCreateNodeSet::FemSetNodesObject protected
Referenced by accept(), and reject().
name
TaskObjectName* FemGui::TaskDlgCreateNodeSet::name protected
Referenced by draftguitools.gui_groups.Ui_AddNamedGroup::accept(), prototype.Node::addtofreecad(), Addon.Addon::disable(), Addon.Addon::enable(), addonmanager_macro.Macro::filename(), gzip_utf8.GzipFile::filename(), addonmanager_macro.Macro::fill_details_from_code(), addonmanager_macro.Macro::fill_details_from_wiki(), Addon.Addon::get_cached_icon_filename(), ifc4.ifcapproval::hasidentifierorname(), addonmanager_macro.Macro::install(), Addon.Addon::is_disabled(), femsolver.elmer.sifio.Section::keys(), automotive_design.si_unit::named_unit_dimensions(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::output(), prototype.Node::pprint(), prototype.Node::pprint2(), PathScripts.PathSetupSheetGui.OpTaskPanel::propertyGroup(), PathScripts.PathSetupSheetGui.OpTaskPanel::propertyName(), PathScripts.PathJobGui.TaskPanel::reject(), addonmanager_macro.Macro::remove(), Addon.Addon::to_cache(), ifc2x3.ifcexternalreference::wr1(), ifc2x3.ifcdocumentreference::wr1(), ifc4.ifcexternalreference::wr1(), ifc4.ifcdocumentreference::wr1(), and automotive_design.general_property_association::wr2().
param
TaskCreateNodeSet* FemGui::TaskDlgCreateNodeSet::param protected
Referenced by accept(), draftguitools.gui_selectplane.Draft_SelectPlane::finish(), draftguitools.gui_selectplane.Draft_SelectPlane::onSetExtension(), draftguitools.gui_selectplane.Draft_SelectPlane::onSetGridSize(), draftguitools.gui_selectplane.Draft_SelectPlane::onSetMainline(), draftguitools.gui_selectplane.Draft_SelectPlane::onSetSnapRadius(), reject(), and TaskDlgCreateNodeSet().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/TaskDlgCreateNodeSet.h
FreeCAD/src/Mod/Fem/Gui/TaskDlgCreateNodeSet.cpp