FreeCAD: SMESH::Controls::Filter Class Reference
SMESH::Controls::Filter Class Reference
#include <SMESH_ControlsDef.hxx>
Public Types
typedef std::vector< long > TIdSequence
Public Member Functions
Filter ()
virtual void GetElementsId (const SMDS_Mesh *theMesh, TIdSequence &theSequence)
virtual void SetPredicate (PredicatePtr thePred)
virtual ~Filter ()
Static Public Member Functions
static void GetElementsId (const SMDS_Mesh *theMesh, PredicatePtr thePredicate, TIdSequence &theSequence)
Protected Attributes
PredicatePtr myPredicate
Member Typedef Documentation
TIdSequence
typedef std::vector<long> SMESH::Controls::Filter::TIdSequence
Constructor & Destructor Documentation
Filter()
Filter::Filter ()
~Filter()
Filter::~Filter () virtual
Member Function Documentation
GetElementsId() [1/2]
void Filter::GetElementsId (const SMDS_Mesh * theMesh, PredicatePtr thePredicate, TIdSequence & theSequence) static
References SMDS_Mesh::elementsIterator(), and SMDS_MeshElement::GetID().
GetElementsId() [2/2]
void Filter::GetElementsId (const SMDS_Mesh * theMesh, Filter::TIdSequence & theSequence) virtual
References GetElementsId(), and myPredicate.
Referenced by GetElementsId().
SetPredicate()
void Filter::SetPredicate (PredicatePtr thePred) virtual
References myPredicate.
Member Data Documentation
myPredicate
PredicatePtr SMESH::Controls::Filter::myPredicate protected
Referenced by GetElementsId(), and SetPredicate().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp