FreeCAD: Robot::WaypointPy Class Reference
Robot::WaypointPy Class Reference
The python export class for Waypoint.
#include <WaypointPy.h>
Public Types
typedef Waypoint * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
WaypointPy (Waypoint *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of WaypointPy.
static PyMethodDef Methods []
Methods structure of WaypointPy.
static PyTypeObject Type
Type structure of WaypointPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~WaypointPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object attributes
Py::String getName (void) const
getter for the Name attribute
void setName (Py::String arg)
setter for the Name attribute
Py::String getType (void) const
getter for the Type attribute
void setType (Py::String arg)
setter for the Type attribute
Py::Object getPos (void) const
getter for the Pos attribute
void setPos (Py::Object arg)
setter for the Pos attribute
Py::Boolean getCont (void) const
getter for the Cont attribute
void setCont (Py::Boolean arg)
setter for the Cont attribute
Py::Float getVelocity (void) const
getter for the Velocity attribute
void setVelocity (Py::Float arg)
setter for the Velocity attribute
Py::Long getTool (void) const
getter for the Tool attribute
void setTool (Py::Long arg)
setter for the Tool attribute
Py::Long getBase (void) const
getter for the Base attribute
void setBase (Py::Long arg)
setter for the Base attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Waypoint * getWaypointPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getName (PyObject *self, void *closure)
getter callback for the Name attribute
static int staticCallback_setName (PyObject *self, PyObject *value, void *closure)
setter callback for the Name attribute
static PyObject * staticCallback_getType (PyObject *self, void *closure)
getter callback for the Type attribute
static int staticCallback_setType (PyObject *self, PyObject *value, void *closure)
setter callback for the Type attribute
static PyObject * staticCallback_getPos (PyObject *self, void *closure)
getter callback for the Pos attribute
static int staticCallback_setPos (PyObject *self, PyObject *value, void *closure)
setter callback for the Pos attribute
static PyObject * staticCallback_getCont (PyObject *self, void *closure)
getter callback for the Cont attribute
static int staticCallback_setCont (PyObject *self, PyObject *value, void *closure)
setter callback for the Cont attribute
static PyObject * staticCallback_getVelocity (PyObject *self, void *closure)
getter callback for the Velocity attribute
static int staticCallback_setVelocity (PyObject *self, PyObject *value, void *closure)
setter callback for the Velocity attribute
static PyObject * staticCallback_getTool (PyObject *self, void *closure)
getter callback for the Tool attribute
static int staticCallback_setTool (PyObject *self, PyObject *value, void *closure)
setter callback for the Tool attribute
static PyObject * staticCallback_getBase (PyObject *self, void *closure)
getter callback for the Base attribute
static int staticCallback_setBase (PyObject *self, PyObject *value, void *closure)
setter callback for the Base attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Waypoint.
Member Typedef Documentation
PointerType
typedef Waypoint* Robot::WaypointPy::PointerType
Constructor & Destructor Documentation
~WaypointPy()
WaypointPy::~WaypointPy () protected
WaypointPy()
WaypointPy::WaypointPy (Waypoint * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
getBase()
Py::Long WaypointPy::getBase (void) const
getter for the Base attribute
Referenced by staticCallback_getBase().
getCont()
Py::Boolean WaypointPy::getCont (void) const
getter for the Cont attribute
Referenced by staticCallback_getCont().
getCustomAttributes()
PyObject * WaypointPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getName()
Py::String WaypointPy::getName (void) const
getter for the Name attribute
Referenced by staticCallback_getName().
getPos()
Py::Object WaypointPy::getPos (void) const
getter for the Pos attribute
Referenced by staticCallback_getPos().
getTool()
Py::Long WaypointPy::getTool (void) const
getter for the Tool attribute
Referenced by staticCallback_getTool().
GetType()
virtual PyTypeObject* Robot::WaypointPy::GetType (void) virtual
Reimplemented from Base::PersistencePy.
getType()
Py::String WaypointPy::getType (void) const
getter for the Type attribute
References Robot::Waypoint::CIRC, Robot::Waypoint::LINE, Robot::Waypoint::PTP, Robot::Waypoint::UNDEF, and Robot::Waypoint::WAIT.
Referenced by staticCallback_getType().
getVelocity()
Py::Float WaypointPy::getVelocity (void) const
getter for the Velocity attribute
Referenced by staticCallback_getVelocity().
getWaypointPtr()
Waypoint * WaypointPy::getWaypointPtr (void) const
getter for the object handled by this class
PyInit()
int WaypointPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PersistencePy.
References Base::Unit::Acceleration, Robot::Waypoint::CIRC, Robot::Waypoint::LINE, Robot::Waypoint::PTP, Base::UnitsApi::toDbl(), Base::PlacementPy::Type, Robot::Waypoint::UNDEF, Base::Unit::Velocity, and Robot::Waypoint::WAIT.
PyMake()
PyObject * WaypointPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string WaypointPy::representation (void) const
References Robot::Waypoint::CIRC, Robot::Waypoint::LINE, Robot::Waypoint::PTP, Robot::Waypoint::UNDEF, and Robot::Waypoint::WAIT.
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setBase()
void WaypointPy::setBase (Py::Long arg)
setter for the Base attribute
Referenced by staticCallback_setBase().
setCont()
void WaypointPy::setCont (Py::Boolean arg)
setter for the Cont attribute
Referenced by staticCallback_setCont().
setCustomAttributes()
int WaypointPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setName()
void WaypointPy::setName (Py::String arg)
setter for the Name attribute
Referenced by staticCallback_setName().
setPos()
void WaypointPy::setPos (Py::Object arg)
setter for the Pos attribute
References PyType_Object::o, and Base::PlacementPy::Type.
Referenced by staticCallback_setPos().
setTool()
void WaypointPy::setTool (Py::Long arg)
setter for the Tool attribute
Referenced by staticCallback_setTool().
setType()
void WaypointPy::setType (Py::String arg)
setter for the Type attribute
References Robot::Waypoint::CIRC, Robot::Waypoint::LINE, Robot::Waypoint::PTP, and Robot::Waypoint::WAIT.
Referenced by staticCallback_setType().
setVelocity()
void WaypointPy::setVelocity (Py::Float arg)
setter for the Velocity attribute
Referenced by staticCallback_setVelocity().
staticCallback_getBase()
PyObject * WaypointPy::staticCallback_getBase (PyObject * self, void * closure) static
getter callback for the Base attribute
References Base::BaseExceptionFreeCADError, getBase(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCont()
PyObject * WaypointPy::staticCallback_getCont (PyObject * self, void * closure) static
getter callback for the Cont attribute
References Base::BaseExceptionFreeCADError, getCont(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getName()
PyObject * WaypointPy::staticCallback_getName (PyObject * self, void * closure) static
getter callback for the Name attribute
References Base::BaseExceptionFreeCADError, getName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPos()
PyObject * WaypointPy::staticCallback_getPos (PyObject * self, void * closure) static
getter callback for the Pos attribute
References Base::BaseExceptionFreeCADError, getPos(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTool()
PyObject * WaypointPy::staticCallback_getTool (PyObject * self, void * closure) static
getter callback for the Tool attribute
References Base::BaseExceptionFreeCADError, getTool(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getType()
PyObject * WaypointPy::staticCallback_getType (PyObject * self, void * closure) static
getter callback for the Type attribute
References Base::BaseExceptionFreeCADError, getType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVelocity()
PyObject * WaypointPy::staticCallback_getVelocity (PyObject * self, void * closure) static
getter callback for the Velocity attribute
References Base::BaseExceptionFreeCADError, getVelocity(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setBase()
int WaypointPy::staticCallback_setBase (PyObject * self, PyObject * value, void * closure) static
setter callback for the Base attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setBase().
staticCallback_setCont()
int WaypointPy::staticCallback_setCont (PyObject * self, PyObject * value, void * closure) static
setter callback for the Cont attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setCont().
staticCallback_setName()
int WaypointPy::staticCallback_setName (PyObject * self, PyObject * value, void * closure) static
setter callback for the Name attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setName().
staticCallback_setPos()
int WaypointPy::staticCallback_setPos (PyObject * self, PyObject * value, void * closure) static
setter callback for the Pos attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setPos().
staticCallback_setTool()
int WaypointPy::staticCallback_setTool (PyObject * self, PyObject * value, void * closure) static
setter callback for the Tool attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setTool().
staticCallback_setType()
int WaypointPy::staticCallback_setType (PyObject * self, PyObject * value, void * closure) static
setter callback for the Type attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setType().
staticCallback_setVelocity()
int WaypointPy::staticCallback_setVelocity (PyObject * self, PyObject * value, void * closure) static
setter callback for the Velocity attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setVelocity().
Member Data Documentation
GetterSetter
PyGetSetDef WaypointPy::GetterSetter static
Attribute structure of WaypointPy.
Methods
PyMethodDef WaypointPy::Methods static
Initial value:
= {
    {NULL, NULL, 0, NULL}
}
Methods structure of WaypointPy.
Type
PyTypeObject WaypointPy::Type static
Type structure of WaypointPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), Robot::TrajectoryPy::insertWaypoints(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), and Robot::TrajectoryPy::PyInit().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Robot/App/WaypointPy.h
Sources/FreeCAD/src/Mod/Robot/App/WaypointPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Robot/App/WaypointPy.cpp