FreeCAD: Base::Quantity Class Reference
Base::Quantity Class Reference
The Quantity class.
#include <Quantity.h>
Public Member Functions
const QuantityFormat & getFormat () const
const Unit & getUnit (void) const
returns the unit of the quantity
QString getUserString (double &factor, QString &unitString) const
transfer to user preferred unit/potence
QString getUserString (UnitsSchema *schema, double &factor, QString &unitString) const
QString getUserString (void) const
double getValue (void) const
get the Value of the quantity
double getValueAs (const Quantity &) const
get the Value in a special unit given as quantity.
bool isDimensionless (void) const
true if it has a number without a unit
bool isQuantity (void) const
true if it has a number and a valid unit
bool isValid (void) const
true if it has a number with or without a unit
Quantity operator* (const Quantity &p) const
Operators.
Quantity operator* (double p) const
Quantity operator+ (const Quantity &p) const
Quantity & operator+= (const Quantity &p)
Quantity operator- (const Quantity &p) const
Quantity operator- (void) const
Quantity & operator-= (const Quantity &p)
Quantity operator/ (const Quantity &p) const
Quantity operator/ (double p) const
bool operator< (const Quantity &) const
bool operator<= (const Quantity &) const
Quantity & operator= (const Quantity &)
bool operator== (const Quantity &) const
bool operator> (const Quantity &) const
bool operator>= (const Quantity &) const
Quantity pow (const Quantity &) const
Quantity pow (double) const
Quantity (const Quantity &)
Quantity (double Value, const Unit &unit=Unit())
Quantity (void)
default constructor
void setFormat (const QuantityFormat &f)
void setInvalid (void)
sets the quantity invalid
void setUnit (const Unit &un)
set the unit of the quantity
void setValue (double val)
set the value of the quantity
~Quantity ()
Destruction.
Static Public Member Functions
static Quantity parse (const QString &string)
Static Public Attributes
static Quantity Ampere
static Quantity AngMinute
static Quantity AngSecond
static Quantity Bar
static Quantity Calorie
static Quantity Candela
static Quantity CentiMetre
static Quantity Coulomb
static Quantity CubicFoot
static Quantity DeciMetre
static Quantity Degree
static Quantity ElectronVolt
static Quantity Farad
static Quantity Foot
static Quantity Gauss
static Quantity GigaHertz
static Quantity GigaPascal
static Quantity Gon
static Quantity Gram
static Quantity Henry
static Quantity Hertz
static Quantity Hour
static Quantity Hundredweights
static Quantity Inch
static Quantity Joule
static Quantity Kelvin
static Quantity KiloAmpere
static Quantity KiloCalorie
static Quantity KiloElectronVolt
static Quantity KiloGram
static Quantity KiloHertz
static Quantity KiloJoule
static Quantity KiloMetre
static Quantity KiloNewton
static Quantity KiloOhm
static Quantity KiloPascal
static Quantity KiloVolt
static Quantity KiloWatt
static Quantity KiloWattHour
static Quantity KMH
static Quantity KSI
static Quantity Liter
static Quantity MegaAmpere
static Quantity MegaElectronVolt
static Quantity MegaHertz
static Quantity MegaNewton
static Quantity MegaOhm
static Quantity MegaPascal
static Quantity Metre
static Quantity MicroFarad
static Quantity MicroGram
static Quantity MicroHenry
static Quantity MicroKelvin
static Quantity MicroMetre
static Quantity MicroSiemens
static Quantity Mile
static Quantity MilePerHour
static Quantity MilliAmpere
static Quantity MilliBar
static Quantity MilliFarad
static Quantity MilliGram
static Quantity MilliHenry
static Quantity MilliJoule
static Quantity MilliKelvin
static Quantity MilliLiter
static Quantity MilliMetre
static Quantity MilliMole
static Quantity MilliNewton
static Quantity MilliSiemens
static Quantity MilliVolt
static Quantity MilliWatt
static Quantity Minute
static Quantity Mole
static Quantity MPH
static Quantity MPSI
static Quantity mTorr
static Quantity NanoFarad
static Quantity NanoHenry
static Quantity NanoMetre
Predefined Unit types.
static Quantity Newton
static Quantity NewtonMeter
static Quantity Oersted
static Quantity Ohm
static Quantity Ounce
static Quantity Pascal
static Quantity PicoFarad
static Quantity Pound
static Quantity PoundForce
static Quantity PSI
static Quantity Radian
static Quantity Second
static Quantity Siemens
static Quantity SquareFoot
static Quantity Stone
static Quantity TeraHertz
static Quantity Tesla
static Quantity Thou
static Quantity Ton
static Quantity Torr
static Quantity Volt
static Quantity VoltAmpere
static Quantity VoltAmpereSecond
static Quantity Watt
static Quantity WattSecond
static Quantity Weber
static Quantity Yard
static Quantity yTorr
Detailed Description
The Quantity class.
Constructor & Destructor Documentation
Quantity() [1/3]
Quantity::Quantity (void)
default constructor
Referenced by operator*(), operator+(), operator-(), operator/(), parse(), and pow().
Quantity() [2/3]
Quantity::Quantity (const Quantity & that)
Quantity() [3/3]
Quantity::Quantity (double Value, const Unit & unit = Unit()) explicit
~Quantity()
Base::Quantity::~Quantity ()
Destruction.
Member Function Documentation
getFormat()
const QuantityFormat& Base::Quantity::getFormat () const
Referenced by Base::QuantityPy::getFormat(), Gui::InputField::getFormat(), Gui::InputField::getPrecision(), Sketcher::Constraint::getPresentationValue(), Gui::InputField::newInput(), Base::UnitsSchemaImperialBuilding::schemaTranslate(), Gui::InputField::selectNumber(), Gui::InputField::setFormat(), Base::QuantityPy::setFormat(), Gui::InputField::setPrecision(), Base::UnitsSchema::toLocale(), and Base::QuantityPy::toStr().
getUnit()
const Unit& Base::Quantity::getUnit (void) const
returns the unit of the quantity
Referenced by CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), Base::QuantityPy::getValueAs(), App::pyFromQuantity(), Base::UnitPy::PyInit(), Base::QuantityPy::representation(), Base::UnitsSchemaCentimeters::schemaTranslate(), Base::UnitsSchemaFemMilliMeterNewton::schemaTranslate(), Base::UnitsSchemaImperial1::schemaTranslate(), Base::UnitsSchemaImperialDecimal::schemaTranslate(), Base::UnitsSchemaImperialBuilding::schemaTranslate(), Base::UnitsSchemaImperialCivil::schemaTranslate(), Base::UnitsSchemaInternal::schemaTranslate(), Base::UnitsSchemaMKS::schemaTranslate(), Base::UnitsSchemaMmMin::schemaTranslate(), Sketcher::SketchObjectPy::setDatum(), App::PropertyQuantity::setPyObject(), App::PropertyQuantityConstraint::setPyObject(), Gui::InputField::setUnitText(), Gui::QuantitySpinBox::setUnitText(), Gui::InputField::setValue(), Base::QuantityPy::toStr(), Base::Unit::Unit(), and Gui::Dialog::DlgUnitsCalculator::valueChanged().
getUserString() [1/3]
QString Quantity::getUserString (double & factor, QString & unitString) const
transfer to user preferred unit/potence
References Base::UnitsApi::schemaTranslate().
Referenced by PartGui::createLinearDimension(), Gui::PointMarker::customEvent(), SpreadsheetGui::SheetModel::data(), ConstraintItem::data(), Gui::TDragger::drag(), Gui::RDragger::drag(), SketcherGui::ViewProviderSketch::draw(), PartGui::dumpLinearResults(), Gui::InputField::focusOutEvent(), TechDraw::DrawViewDimension::formatValue(), SketcherGui::ViewProviderSketch::getPresentationString(), Gui::InputField::getQuantityString(), Gui::InputField::getUnitText(), Base::QuantityPy::getUserPreferred(), Gui::InputField::keyPressEvent(), Sketcher::SketchObjectPy::setDatum(), Gui::InputField::setRawText(), Gui::PropertyEditor::PropertyPlacementItem::toolTip(), Gui::PropertyEditor::PropertyVectorDistanceItem::toString(), Gui::PropertyEditor::PropertyPlacementItem::toString(), and Gui::InputField::wheelEvent().
getUserString() [2/3]
QString Quantity::getUserString (UnitsSchema * schema, double & factor, QString & unitString) const
References Base::UnitsSchema::schemaTranslate().
getUserString() [3/3]
QString Base::Quantity::getUserString (void) const
getValue()
double Base::Quantity::getValue (void) const
get the Value of the quantity
Referenced by PartGui::DlgFilletEdges::accept(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), Gui::QuantitySpinBox::apply(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), ConstraintItem::data(), PartGui::DlgPrimitives::DlgPrimitives(), SketcherGui::PropertyConstraintListItem::event(), TechDraw::DrawViewDimension::formatValue(), Sketcher::SketchObjectPy::getDatum(), Gui::LocationWidget::getPosition(), Base::QuantityPy::number_nonzero_handler(), Base::QuantityPy::number_remainder_handler(), TechDraw::DrawSVGTemplate::processTemplate(), App::pyFromQuantity(), Gui::InputField::rawValue(), Base::QuantityPy::representation(), Base::UnitsSchemaImperial1::schemaTranslate(), Base::UnitsSchemaImperialBuilding::schemaTranslate(), Base::UnitsSchemaImperialCivil::schemaTranslate(), Base::UnitsSchemaInternal::schemaTranslate(), Base::UnitsSchemaMKS::schemaTranslate(), Sketcher::SketchObjectPy::setDatum(), Gui::InputField::setMaximum(), Gui::InputField::setMinimum(), App::PropertyQuantity::setPyObject(), App::PropertyQuantityConstraint::setPyObject(), Gui::InputField::setValue(), Base::UnitsSchema::toLocale(), Base::QuantityPy::toStr(), Gui::Dialog::DlgUnitsCalculator::valueChanged(), and SketcherGui::ViewProviderSketch::ViewProviderSketch().
getValueAs()
double Quantity::getValueAs (const Quantity & q) const
get the Value in a special unit given as quantity.
One can use one of the predifeined quantity units in this class
Referenced by FemGui::TaskFemConstraintTemperature::get_cflux(), FemGui::TaskFemConstraintPressure::get_Pressure(), FemGui::TaskFemConstraintInitialTemperature::get_temperature(), FemGui::TaskFemConstraintTemperature::get_temperature(), FemGui::TaskFemConstraintHeatflux::getAmbientTemp(), FemGui::TaskFemConstraintHeatflux::getFilmCoef(), and Sketcher::ConstraintPy::PyInit().
isDimensionless()
bool Quantity::isDimensionless (void) const
true if it has a number without a unit
References isValid().
isQuantity()
bool Quantity::isQuantity (void) const
true if it has a number and a valid unit
References isValid().
Referenced by Base::QuantityPy::getValueAs().
isValid()
bool Quantity::isValid (void) const
true if it has a number with or without a unit
Referenced by Base::QuantityPy::getValueAs(), isDimensionless(), and isQuantity().
operator*() [1/2]
Quantity Quantity::operator* (const Quantity & p) const
Operators.
References Quantity().
operator*() [2/2]
Quantity Quantity::operator* (double p) const
References Quantity().
operator+()
Quantity Quantity::operator+ (const Quantity & p) const
References Quantity().
operator+=()
Quantity & Quantity::operator+= (const Quantity & p)
operator-() [1/2]
Quantity Quantity::operator- (const Quantity & p) const
References Quantity().
operator-() [2/2]
Quantity Quantity::operator- (void) const
References Quantity().
operator-=()
Quantity & Quantity::operator-= (const Quantity & p)
operator/() [1/2]
Quantity Quantity::operator/ (const Quantity & p) const
References Quantity().
operator/() [2/2]
Quantity Quantity::operator/ (double p) const
References Quantity().
operator<()
bool Quantity::operator< (const Quantity & that) const
operator<=()
bool Quantity::operator<= (const Quantity & that) const
operator=()
Quantity & Quantity::operator= (const Quantity & New)
operator==()
bool Quantity::operator== (const Quantity & that) const
operator>()
bool Quantity::operator> (const Quantity & that) const
operator>=()
bool Quantity::operator>= (const Quantity & that) const
parse()
Quantity Quantity::parse (const QString & string) static
References Quantity().
Referenced by BOPTools.GeneralFuseResult.GeneralFuseResult::explodeCompounds(), TechDraw::DrawViewDimension::formatValue(), Base::QuantityPy::getValueAs(), TechDraw::DrawSVGTemplate::processTemplate(), Base::QuantityPy::PyInit(), Base::UnitPy::PyInit(), Gui::InputField::setRawText(), Gui::InputField::setUnitText(), Gui::QuantitySpinBox::setUnitText(), Base::UnitsApi::sParseQuantity(), BOPTools.GeneralFuseResult.GeneralFuseResult::splitAggregates(), Base::UnitsApi::toDbl(), Base::UnitsApi::toQuantity(), Base::Unit::Unit(), Gui::QuantitySpinBoxPrivate::validateAndInterpret(), Gui::Dialog::DlgUnitsCalculator::valueChanged(), and SketcherGui::ViewProviderSketch::ViewProviderSketch().
pow() [1/2]
Quantity Quantity::pow (const Quantity & p) const
References Quantity().
pow() [2/2]
Quantity Quantity::pow (double p) const
References Quantity().
setFormat()
void Base::Quantity::setFormat (const QuantityFormat & f)
Referenced by Sketcher::Constraint::getPresentationValue(), PathScripts.PathInspect.GCodeHighlighter::highlightBlock(), PathScripts.PostUtils.GCodeHighlighter::highlightBlock(), Gui::InputField::setFormat(), Base::QuantityPy::setFormat(), Gui::InputField::setPrecision(), and Gui::QuantitySpinBoxPrivate::validate().
setInvalid()
void Quantity::setInvalid (void)
sets the quantity invalid
Referenced by Base::QuantityPy::getValueAs().
setUnit()
void Base::Quantity::setUnit (const Unit & un)
set the unit of the quantity
Referenced by CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), SketcherGui::EditDatumDialog::exec(), TechDraw::DrawViewDimension::formatValue(), Sketcher::SketchObjectPy::getDatum(), Sketcher::Constraint::getPresentationValue(), Base::QuantityPy::getValueAs(), TechDraw::DrawSVGTemplate::processTemplate(), TechDrawGui::TaskCenterLine::setUiEdit(), TechDrawGui::TaskCenterLine::setUiPrimary(), Gui::InputField::setUnit(), Base::QuantityPy::setUnit(), and SketcherGui::PropertyConstraintListItem::value().
setValue()
void Base::Quantity::setValue (double val)
set the value of the quantity
Referenced by CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), SketcherGui::EditDatumDialog::exec(), TechDraw::DrawViewDimension::formatValue(), Sketcher::SketchObjectPy::getDatum(), Sketcher::Constraint::getPresentationValue(), Base::QuantityPy::getValueAs(), Gui::View3DInventorViewer::printDimension(), Gui::schemaTranslatePoint(), Sketcher::SketchObjectPy::setDatum(), Gui::InputField::setMaximum(), Gui::InputField::setMinimum(), App::PropertyQuantityConstraint::setPyObject(), TechDrawGui::TaskCenterLine::setUiEdit(), TechDrawGui::TaskCenterLine::setUiPrimary(), Gui::InputField::setValue(), Gui::QuantitySpinBox::setValue(), Base::QuantityPy::setValue(), and SketcherGui::PropertyConstraintListItem::value().
Member Data Documentation
Ampere
Quantity Quantity::Ampere static
AngMinute
Quantity Quantity::AngMinute static
Referenced by Base::QuantityPy::getCustomAttributes().
AngSecond
Quantity Quantity::AngSecond static
Referenced by Base::QuantityPy::getCustomAttributes().
Bar
Quantity Quantity::Bar static
Calorie
Quantity Quantity::Calorie static
Candela
Quantity Quantity::Candela static
CentiMetre
Quantity Quantity::CentiMetre static
Coulomb
Quantity Quantity::Coulomb static
CubicFoot
Quantity Quantity::CubicFoot static
DeciMetre
Quantity Quantity::DeciMetre static
Degree
Quantity Quantity::Degree static
Referenced by PartGui::DlgRevolution::getAngle().
ElectronVolt
Quantity Quantity::ElectronVolt static
Farad
Quantity Quantity::Farad static
Foot
Quantity Quantity::Foot static
Gauss
Quantity Quantity::Gauss static
GigaHertz
Quantity Quantity::GigaHertz static
GigaPascal
Quantity Quantity::GigaPascal static
Gon
Quantity Quantity::Gon static
Gram
Quantity Quantity::Gram static
Henry
Quantity Quantity::Henry static
Hertz
Quantity Quantity::Hertz static
Hour
Quantity Quantity::Hour static
Hundredweights
Quantity Quantity::Hundredweights static
Inch
Quantity Quantity::Inch static
Joule
Quantity Quantity::Joule static
Kelvin
Quantity Quantity::Kelvin static
Referenced by FemGui::TaskFemConstraintInitialTemperature::get_temperature(), FemGui::TaskFemConstraintTemperature::get_temperature(), and FemGui::TaskFemConstraintHeatflux::getAmbientTemp().
KiloAmpere
Quantity Quantity::KiloAmpere static
KiloCalorie
Quantity Quantity::KiloCalorie static
KiloElectronVolt
Quantity Quantity::KiloElectronVolt static
KiloGram
Quantity Quantity::KiloGram static
KiloHertz
Quantity Quantity::KiloHertz static
KiloJoule
Quantity Quantity::KiloJoule static
KiloMetre
Quantity Quantity::KiloMetre static
KiloNewton
Quantity Quantity::KiloNewton static
KiloOhm
Quantity Quantity::KiloOhm static
KiloPascal
Quantity Quantity::KiloPascal static
KiloVolt
Quantity Quantity::KiloVolt static
KiloWatt
Quantity Quantity::KiloWatt static
KiloWattHour
Quantity Quantity::KiloWattHour static
KMH
Quantity Quantity::KMH static
KSI
Quantity Quantity::KSI static
Liter
Quantity Quantity::Liter static
MegaAmpere
Quantity Quantity::MegaAmpere static
MegaElectronVolt
Quantity Quantity::MegaElectronVolt static
MegaHertz
Quantity Quantity::MegaHertz static
MegaNewton
Quantity Quantity::MegaNewton static
MegaOhm
Quantity Quantity::MegaOhm static
MegaPascal
Quantity Quantity::MegaPascal static
Referenced by FemGui::TaskFemConstraintPressure::get_Pressure().
Metre
Quantity Quantity::Metre static
MicroFarad
Quantity Quantity::MicroFarad static
MicroGram
Quantity Quantity::MicroGram static
MicroHenry
Quantity Quantity::MicroHenry static
MicroKelvin
Quantity Quantity::MicroKelvin static
MicroMetre
Quantity Quantity::MicroMetre static
MicroSiemens
Quantity Quantity::MicroSiemens static
Mile
Quantity Quantity::Mile static
MilePerHour
Quantity Quantity::MilePerHour static
MilliAmpere
Quantity Quantity::MilliAmpere static
MilliBar
Quantity Quantity::MilliBar static
MilliFarad
Quantity Quantity::MilliFarad static
MilliGram
Quantity Quantity::MilliGram static
MilliHenry
Quantity Quantity::MilliHenry static
MilliJoule
Quantity Quantity::MilliJoule static
MilliKelvin
Quantity Quantity::MilliKelvin static
MilliLiter
Quantity Quantity::MilliLiter static
MilliMetre
Quantity Quantity::MilliMetre static
Referenced by PartGui::DlgRevolution::getPosition(), Gui::View3DInventorViewer::printDimension(), and Gui::schemaTranslatePoint().
MilliMole
Quantity Quantity::MilliMole static
MilliNewton
Quantity Quantity::MilliNewton static
MilliSiemens
Quantity Quantity::MilliSiemens static
MilliVolt
Quantity Quantity::MilliVolt static
MilliWatt
Quantity Quantity::MilliWatt static
Minute
Quantity Quantity::Minute static
Mole
Quantity Quantity::Mole static
MPH
Quantity Quantity::MPH static
MPSI
Quantity Quantity::MPSI static
mTorr
Quantity Quantity::mTorr static
Referenced by Base::QuantityPy::getCustomAttributes().
NanoFarad
Quantity Quantity::NanoFarad static
NanoHenry
Quantity Quantity::NanoHenry static
NanoMetre
Quantity Quantity::NanoMetre static
Predefined Unit types.
Newton
Quantity Quantity::Newton static
NewtonMeter
Quantity Quantity::NewtonMeter static
Oersted
Quantity Quantity::Oersted static
Ohm
Quantity Quantity::Ohm static
Ounce
Quantity Quantity::Ounce static
Pascal
Quantity Quantity::Pascal static
PicoFarad
Quantity Quantity::PicoFarad static
Pound
Quantity Quantity::Pound static
PoundForce
Quantity Quantity::PoundForce static
Referenced by Base::QuantityPy::getCustomAttributes().
PSI
Quantity Quantity::PSI static
Radian
Quantity Quantity::Radian static
Referenced by Sketcher::ConstraintPy::PyInit(), Base::MatrixPy::rotateX(), Base::MatrixPy::rotateY(), and Base::MatrixPy::rotateZ().
Second
Quantity Quantity::Second static
Siemens
Quantity Quantity::Siemens static
SquareFoot
Quantity Quantity::SquareFoot static
Stone
Quantity Quantity::Stone static
TeraHertz
Quantity Quantity::TeraHertz static
Tesla
Quantity Quantity::Tesla static
Thou
Quantity Quantity::Thou static
Ton
Quantity Quantity::Ton static
Torr
Quantity Quantity::Torr static
Referenced by Base::QuantityPy::getCustomAttributes().
Volt
Quantity Quantity::Volt static
VoltAmpere
Quantity Quantity::VoltAmpere static
VoltAmpereSecond
Quantity Quantity::VoltAmpereSecond static
Watt
Quantity Quantity::Watt static
Referenced by FemGui::TaskFemConstraintTemperature::get_cflux().
WattSecond
Quantity Quantity::WattSecond static
Weber
Quantity Quantity::Weber static
Yard
Quantity Quantity::Yard static
yTorr
Quantity Quantity::yTorr static
Referenced by Base::QuantityPy::getCustomAttributes().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Base/Quantity.h
Sources/FreeCAD/src/Base/Quantity.cpp