FreeCAD: Gui::PythonStdin Class Reference
Gui::PythonStdin Class Reference
Python class for redirection of stdin to an input dialog of Qt.
#include <PythonConsolePy.h>
Public Member Functions
PythonStdin (PythonConsole *pc)
Py::Object readline (const Py::Tuple &)
Py::Object repr ()
~PythonStdin ()
Static Public Member Functions
static void init_type (void)
Detailed Description
Python class for redirection of stdin to an input dialog of Qt.
Author
Werner Mayer
Constructor & Destructor Documentation
PythonStdin()
PythonStdin::PythonStdin (PythonConsole * pc)
~PythonStdin()
PythonStdin::~PythonStdin ()
Member Function Documentation
init_type()
void PythonStdin::init_type (void) static
References readline().
Referenced by Gui::Application::Application().
readline()
Py::Object PythonStdin::readline (const Py::Tuple &)
References Gui::PythonConsole::readline().
Referenced by init_type().
repr()
Py::Object PythonStdin::repr ()
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/PythonConsolePy.h
Sources/FreeCAD/src/Gui/PythonConsolePy.cpp