FreeCAD: MaterialEditor Namespace Reference
MaterialEditor Namespace Reference
Classes
class MaterialEditor
class MaterialsDelegate
Functions
def editMaterial (material=None, card_path=None)
def matProperWidget (parent=None, matproperty=None, Type="String", Value=None, minimum=None, maximum=None, stepsize=None, precision=12)
def openEditor (obj=None, prop=None)
def string2tuple (string)
def translate (context, text)
Variables
unicode = str
Function Documentation
editMaterial()
def MaterialEditor.editMaterial (material = None, card_path = None)
editMaterial(material): opens the editor to edit the contents
of the given material dictionary. Returns the modified material dictionary.
References editMaterial(), and openEditor().
Referenced by femtaskpanels.task_material_common._TaskPanel.edit_material(), femtaskpanels.task_material_reinforced._TaskPanel.edit_material_m(), femtaskpanels.task_material_reinforced._TaskPanel.edit_material_r(), and editMaterial().
matProperWidget()
def MaterialEditor.matProperWidget (parent = None, matproperty = None, Type = "String", Value = None, minimum = None, maximum = None, stepsize = None, precision = 12)
customs widgets for the material stuff.
References string2tuple().
Referenced by MaterialEditor.MaterialsDelegate.createEditor().
openEditor()
def MaterialEditor.openEditor (obj = None, prop = None)
openEditor([obj,prop]): opens the editor, optionally with
an object name and material property name to edit
Referenced by editMaterial().
string2tuple()
def MaterialEditor.string2tuple (string)
Referenced by matProperWidget().
translate()
def MaterialEditor.translate (context, text)
Variable Documentation
unicode
MaterialEditor.unicode = str
Referenced by MaterialEditor.MaterialEditor.getDict().