FreeCAD: MeshGui::TaskRemeshGmsh Class Reference
MeshGui::TaskRemeshGmsh Class Reference
Embed the panel into a task dialog.
#include <RemeshGmsh.h>
Public Member Functions
void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual QDialogButtonBox::StandardButtons getStandardButtons () const
tells the framework which buttons are wished for the dialog
virtual bool isAllowedAlterDocument (void) const
TaskRemeshGmsh (Mesh::Feature *mesh)
~TaskRemeshGmsh ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
Embed the panel into a task dialog.
Constructor & Destructor Documentation
TaskRemeshGmsh()
TaskRemeshGmsh::TaskRemeshGmsh (Mesh::Feature * mesh)
References Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
~TaskRemeshGmsh()
TaskRemeshGmsh::~TaskRemeshGmsh ()
Member Function Documentation
clicked()
void TaskRemeshGmsh::clicked (int) virtual
is called by the framework if a button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
References MeshGui::GmshWidget::accept(), and MeshGui::GmshWidget::reject().
getStandardButtons()
virtual QDialogButtonBox::StandardButtons MeshGui::TaskRemeshGmsh::getStandardButtons (void) const virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
isAllowedAlterDocument()
virtual bool MeshGui::TaskRemeshGmsh::isAllowedAlterDocument (void) const virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/Gui/RemeshGmsh.h
Sources/FreeCAD/src/Mod/Mesh/Gui/RemeshGmsh.cpp