FreeCAD: SMDS_CellLinks Class Reference
SMDS_CellLinks Class Reference
#include <SMDS_UnstructuredGrid.hxx>
Public Member Functions
void ResizeForPoint (vtkIdType vtkID)
Static Public Member Functions
static SMDS_CellLinks * New ()
Protected Member Functions
SMDS_CellLinks ()
~SMDS_CellLinks ()
Constructor & Destructor Documentation
SMDS_CellLinks()
SMDS_CellLinks::SMDS_CellLinks () protected
Referenced by New().
~SMDS_CellLinks()
SMDS_CellLinks::~SMDS_CellLinks () protected
Member Function Documentation
New()
SMDS_CellLinks * SMDS_CellLinks::New () static
References SMDS_CellLinks().
Referenced by SMDS_UnstructuredGrid::BuildLinks().
ResizeForPoint()
void SMDS_CellLinks::ResizeForPoint (vtkIdType vtkID)
References SMDS_Mesh::chunkSize.
Referenced by SMDS_MeshNode::init().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_UnstructuredGrid.hxx
FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp