FreeCAD: NETGENPlugin_SimpleHypothesis_2D Class Reference
NETGENPlugin_SimpleHypothesis_2D Class Reference
#include <NETGENPlugin_SimpleHypothesis_2D.hxx>
Public Member Functions
bool GetAllowQuadrangles () const
double GetLocalLength () const
double GetMaxElementArea () const
int GetNumberOfSegments () const
void LengthFromEdges ()
virtual istream & LoadFrom (istream &load)
NETGENPlugin_SimpleHypothesis_2D (int hypId, int studyId, SMESH_Gen *gen)
virtual ostream & SaveTo (ostream &save)
void SetAllowQuadrangles (bool toAllow)
void SetLocalLength (double segmentLength)
void SetMaxElementArea (double area)
void SetNumberOfSegments (int nb)
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)
Set parameters by mesh.
Public Member Functions inherited from SMESH_Hypothesis
void ClearParameters ()
virtual bool DataDependOnParams () const
The returned value is used by NotifySubMeshesHypothesisModification() to decide to call subMesh->AlgoStateEngine(MODIF_HYP, hyp) or not if subMesh is ready to be computed (algo+hyp==OK) but not yet computed. True result is reasonable for example if EventListeners depend on parameters of hypothesis.
virtual int GetDim () const
SMESH_Gen * GetGen () const
char * GetLastParameters () const
virtual const char * GetLibName () const
SMESH_Mesh * GetMeshByPersistentID (int id)
Find a mesh with given persistent ID.
char * GetParameters () const
virtual int GetShapeType () const
int GetStudyId () const
virtual bool IsAuxiliary () const
Return true if me is an auxiliary hypothesis.
virtual void NotifySubMeshesHypothesisModification ()
void SetLastParameters (const char *theParameters)
void SetLibName (const char *theLibName)
void SetParameters (const char *theParameters)
SMESH_Hypothesis (int hypId, int studyId, SMESH_Gen *gen)
virtual ~SMESH_Hypothesis ()
Public Member Functions inherited from SMESHDS_Hypothesis
int GetID () const
const char * GetName () const
int GetType () const
bool IsSameName (const SMESHDS_Hypothesis &other) const
Compare types of hypotheses.
bool operator!= (const SMESHDS_Hypothesis &other) const
virtual bool operator== (const SMESHDS_Hypothesis &other) const
SMESHDS_Hypothesis (int hypId)
virtual ~SMESHDS_Hypothesis ()
Additional Inherited Members
Public Types inherited from SMESH_Hypothesis
enum Hypothesis_Status {
HYP_OK = 0, HYP_MISSING, HYP_CONCURENT, HYP_BAD_PARAMETER,
HYP_HIDDEN_ALGO, HYP_HIDING_ALGO, HYP_UNKNOWN_FATAL, HYP_INCOMPATIBLE,
HYP_NOTCONFORM, HYP_ALREADY_EXIST, HYP_BAD_DIM, HYP_BAD_SUBSHAPE,
HYP_BAD_GEOMETRY, HYP_NEED_SHAPE, HYP_INCOMPAT_HYPS
}
Public Types inherited from SMESHDS_Hypothesis
enum hypothesis_type {
PARAM_ALGO, ALGO_0D, ALGO_1D, ALGO_2D,
ALGO_3D
}
Static Public Member Functions inherited from SMESH_Hypothesis
static bool IsStatusFatal (Hypothesis_Status theStatus)
Constructor & Destructor Documentation
NETGENPlugin_SimpleHypothesis_2D()
NETGENPlugin_SimpleHypothesis_2D::NETGENPlugin_SimpleHypothesis_2D (int hypId, int studyId, SMESH_Gen * gen)
Member Function Documentation
GetAllowQuadrangles()
bool NETGENPlugin_SimpleHypothesis_2D::GetAllowQuadrangles () const
Returns true if generation of quadrangular faces is enabled
GetLocalLength()
double NETGENPlugin_SimpleHypothesis_2D::GetLocalLength () const
Returns <segment length> value. Can be zero in case if NumberOfSegments() has been set
GetMaxElementArea()
double NETGENPlugin_SimpleHypothesis_2D::GetMaxElementArea () const
Returns <maximum element area> value. Can be zero in case of LengthFromEdges()
GetNumberOfSegments()
int NETGENPlugin_SimpleHypothesis_2D::GetNumberOfSegments () const
Returns <number of segments> value. Can be zero in case if LocalLength() has been set
LengthFromEdges()
void NETGENPlugin_SimpleHypothesis_2D::LengthFromEdges ()
Sets <maximum element area> to be dependent on 1D discretization
LoadFrom()
istream & NETGENPlugin_SimpleHypothesis_2D::LoadFrom (istream & load) virtual
Implements SMESHDS_Hypothesis.
Reimplemented in NETGENPlugin_SimpleHypothesis_3D.
Referenced by NETGENPlugin_SimpleHypothesis_3D::LoadFrom().
SaveTo()
ostream & NETGENPlugin_SimpleHypothesis_2D::SaveTo (ostream & save) virtual
Implements SMESHDS_Hypothesis.
Reimplemented in NETGENPlugin_SimpleHypothesis_3D.
References OfflineRenderingUtils::save().
Referenced by NETGENPlugin_SimpleHypothesis_3D::SaveTo().
SetAllowQuadrangles()
void NETGENPlugin_SimpleHypothesis_2D::SetAllowQuadrangles (bool toAllow)
Enables/disables generation of quadrangular faces
SetLocalLength()
void NETGENPlugin_SimpleHypothesis_2D::SetLocalLength (double segmentLength)
Sets <segment length> value
SetMaxElementArea()
void NETGENPlugin_SimpleHypothesis_2D::SetMaxElementArea (double area)
Sets <maximum element area> value. Zero or negative value means same as LengthFromEdges().
SetNumberOfSegments()
void NETGENPlugin_SimpleHypothesis_2D::SetNumberOfSegments (int nb)
Sets <number of segments> value
SetParametersByDefaults()
bool NETGENPlugin_SimpleHypothesis_2D::SetParametersByDefaults (const TDefaults & dflts, const SMESH_Mesh * theMesh = 0) virtual
Initialize my parameter values by default parameters.
Return values
bool - true if parameter values have been successfully defined
Implements SMESH_Hypothesis.
SetParametersByMesh()
bool NETGENPlugin_SimpleHypothesis_2D::SetParametersByMesh (const SMESH_Mesh * theMesh, const TopoDS_Shape & theShape) virtual
Set parameters by mesh.
Does nothing.
Parameters
theMesh - the built mesh
theShape - the geometry of interest
Return values
bool - true if theShape is meshed
Parameters
theMesh - the built mesh
theShape - the geometry of interest
Return values
bool - always false
Implements SMESH_Hypothesis.
Reimplemented in NETGENPlugin_SimpleHypothesis_3D.
References SMESHDS_SubMesh::GetElements(), SMESH::Controls::NumericalFunctor::GetPoints(), SMESH_Mesh::GetSubMeshContaining(), SMESH_subMesh::GetSubMeshDS(), SMESH::Controls::Area::GetValue(), SMESH_subMesh::IsEmpty(), and SMESHDS_SubMesh::NbElements().
Referenced by NETGENPlugin_SimpleHypothesis_3D::SetParametersByMesh().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/NETGENPlugin_SimpleHypothesis_2D.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/NETGENPlugin/NETGENPlugin_SimpleHypothesis_2D.cpp