FreeCAD: SMESH_Array2< TheItemType > Class Template Reference
SMESH_Array2< TheItemType > Class Template Reference
Purpose: The class Array2 represents bi-dimensional arrays of fixed size known at run time.
#include <SMESH_Array2.hxx>
Classes
class Iterator
Public Member Functions
virtual void Assign (const NCollection_BaseCollection< TheItemType > &theOther)
Assign.
TheItemType & ChangeValue (const Standard_Integer theRow, const Standard_Integer theCol)
Variable value access.
Standard_Integer ColLength (void) const
ColLength.
void Init (const TheItemType &theValue)
Initialise the values.
Standard_Boolean IsDeletable (void) const
myDeletable flag
Standard_Integer Length (void) const
Length (number of items)
Standard_Integer LowerCol (void) const
LowerCol.
Standard_Integer LowerRow (void) const
LowerRow.
TheItemType & operator() (const Standard_Integer theRow, const Standard_Integer theCol)
operator() - alias to ChangeValue
const TheItemType & operator() (const Standard_Integer theRow, const Standard_Integer theCol) const
operator() - alias to ChangeValue
SMESH_Array2 & operator= (const SMESH_Array2 &theOther)
operator= (array to array)
Standard_Integer RowLength (void) const
RowLength.
void SetValue (const Standard_Integer theRow, const Standard_Integer theCol, const TheItemType &theItem)
SetValue.
virtual Standard_Integer Size (void) const
Size (number of items)
SMESH_Array2 (const SMESH_Array2 &theOther)
Copy constructor.
SMESH_Array2 (const Standard_Integer theRowLower, const Standard_Integer theRowUpper, const Standard_Integer theColLower, const Standard_Integer theColUpper)
Constructor.
SMESH_Array2 (const TheItemType &theBegin, const Standard_Integer theRowLower, const Standard_Integer theRowUpper, const Standard_Integer theColLower, const Standard_Integer theColUpper)
C array-based constructor.
Standard_Integer UpperCol (void) const
UpperCol.
Standard_Integer UpperRow (void) const
UpperRow.
const TheItemType & Value (const Standard_Integer theRow, const Standard_Integer theCol) const
Constant value access.
~SMESH_Array2 (void)
Destructor - releases the memory.
Protected Attributes
TheItemType ** myData
Pointer to the row pointers table.
Standard_Boolean myDeletable
Flag showing who allocated the array.
Standard_Integer myLowerCol
Standard_Integer myLowerRow
TheItemType * myStart
Pointer to the memory array.
Standard_Integer myUpperCol
Standard_Integer myUpperRow
Friends
class Iterator
Detailed Description
template<class TheItemType>
class SMESH_Array2< TheItemType >
Purpose: The class Array2 represents bi-dimensional arrays of fixed size known at run time.
The ranges of indices are user defined.
Warning: Programs clients of such class must be independant of the range of the first element. Then, a C++ for loop must be written like this
for (i = A.LowerRow(); i <= A.UpperRow(); i++) for (j = A.LowerCol(); j <= A.UpperCol(); j++)
Constructor & Destructor Documentation
SMESH_Array2() [1/3]
template<class TheItemType > SMESH_Array2< TheItemType >::SMESH_Array2 (const Standard_Integer theRowLower, const Standard_Integer theRowUpper, const Standard_Integer theColLower, const Standard_Integer theColUpper)
Constructor.
SMESH_Array2() [2/3]
template<class TheItemType > SMESH_Array2< TheItemType >::SMESH_Array2 (const SMESH_Array2< TheItemType > & theOther)
Copy constructor.
SMESH_Array2() [3/3]
template<class TheItemType > SMESH_Array2< TheItemType >::SMESH_Array2 (const TheItemType & theBegin, const Standard_Integer theRowLower, const Standard_Integer theRowUpper, const Standard_Integer theColLower, const Standard_Integer theColUpper)
C array-based constructor.
References SMESH_Array2< TheItemType >::myStart.
~SMESH_Array2()
template<class TheItemType > SMESH_Array2< TheItemType >::~SMESH_Array2 (void)
Destructor - releases the memory.
References SMESH_Array2< TheItemType >::myData, SMESH_Array2< TheItemType >::myDeletable, SMESH_Array2< TheItemType >::myLowerRow, and SMESH_Array2< TheItemType >::myStart.
Member Function Documentation
Assign()
template<class TheItemType > virtual void SMESH_Array2< TheItemType >::Assign (const NCollection_BaseCollection< TheItemType > & theOther) virtual
Assign.
References SMESH_Array2< TheItemType >::Length(), and SMESH_Array2< TheItemType >::myStart.
ChangeValue()
template<class TheItemType > TheItemType& SMESH_Array2< TheItemType >::ChangeValue (const Standard_Integer theRow, const Standard_Integer theCol)
Variable value access.
References SMESH_Array2< TheItemType >::myData, SMESH_Array2< TheItemType >::myUpperCol, and SMESH_Array2< TheItemType >::myUpperRow.
Referenced by SMESH_Array2< TheItemType >::operator()().
ColLength()
template<class TheItemType > Standard_Integer SMESH_Array2< TheItemType >::ColLength (void) const
ColLength.
References SMESH_Array2< TheItemType >::myLowerRow, and SMESH_Array2< TheItemType >::myUpperRow.
Referenced by SMESH_Array2< TheItemType >::Length().
Init()
template<class TheItemType > void SMESH_Array2< TheItemType >::Init (const TheItemType & theValue)
Initialise the values.
References SMESH_Array2< TheItemType >::myStart, and SMESH_Array2< TheItemType >::Size().
IsDeletable()
template<class TheItemType > Standard_Boolean SMESH_Array2< TheItemType >::IsDeletable (void) const
myDeletable flag
References SMESH_Array2< TheItemType >::myDeletable.
Length()
template<class TheItemType > Standard_Integer SMESH_Array2< TheItemType >::Length (void) const
Length (number of items)
References SMESH_Array2< TheItemType >::ColLength(), and SMESH_Array2< TheItemType >::RowLength().
Referenced by SMESH_Array2< TheItemType >::Assign(), SMESH_Array2< TheItemType >::Iterator::Init(), SMESH_Array2< TheItemType >::operator=(), and SMESH_Array2< TheItemType >::Size().
LowerCol()
template<class TheItemType > Standard_Integer SMESH_Array2< TheItemType >::LowerCol (void) const
LowerCol.
References SMESH_Array2< TheItemType >::myLowerCol.
LowerRow()
template<class TheItemType > Standard_Integer SMESH_Array2< TheItemType >::LowerRow (void) const
LowerRow.
References SMESH_Array2< TheItemType >::myLowerRow.
operator()() [1/2]
template<class TheItemType > TheItemType& SMESH_Array2< TheItemType >::operator() (const Standard_Integer theRow, const Standard_Integer theCol)
operator() - alias to ChangeValue
References SMESH_Array2< TheItemType >::ChangeValue().
operator()() [2/2]
template<class TheItemType > const TheItemType& SMESH_Array2< TheItemType >::operator() (const Standard_Integer theRow, const Standard_Integer theCol) const
operator() - alias to ChangeValue
References SMESH_Array2< TheItemType >::Value().
operator=()
template<class TheItemType > SMESH_Array2& SMESH_Array2< TheItemType >::operator= (const SMESH_Array2< TheItemType > & theOther)
operator= (array to array)
References SMESH_Array2< TheItemType >::Length(), and SMESH_Array2< TheItemType >::myStart.
RowLength()
template<class TheItemType > Standard_Integer SMESH_Array2< TheItemType >::RowLength (void) const
RowLength.
References SMESH_Array2< TheItemType >::myLowerCol, and SMESH_Array2< TheItemType >::myUpperCol.
Referenced by SMESH_Array2< TheItemType >::Length().
SetValue()
template<class TheItemType > void SMESH_Array2< TheItemType >::SetValue (const Standard_Integer theRow, const Standard_Integer theCol, const TheItemType & theItem)
SetValue.
References SMESH_Array2< TheItemType >::myData, SMESH_Array2< TheItemType >::myUpperCol, and SMESH_Array2< TheItemType >::myUpperRow.
Size()
template<class TheItemType > virtual Standard_Integer SMESH_Array2< TheItemType >::Size (void) const virtual
Size (number of items)
References SMESH_Array2< TheItemType >::Length().
Referenced by SMESH_Array2< TheItemType >::Init().
UpperCol()
template<class TheItemType > Standard_Integer SMESH_Array2< TheItemType >::UpperCol (void) const
UpperCol.
References SMESH_Array2< TheItemType >::myUpperCol.
UpperRow()
template<class TheItemType > Standard_Integer SMESH_Array2< TheItemType >::UpperRow (void) const
UpperRow.
References SMESH_Array2< TheItemType >::myUpperRow.
Value()
template<class TheItemType > const TheItemType& SMESH_Array2< TheItemType >::Value (const Standard_Integer theRow, const Standard_Integer theCol) const
Constant value access.
References SMESH_Array2< TheItemType >::myData, SMESH_Array2< TheItemType >::myUpperCol, and SMESH_Array2< TheItemType >::myUpperRow.
Referenced by SMESH_Array2< TheItemType >::operator()().
Friends And Related Function Documentation
Iterator
template<class TheItemType > friend class Iterator friend
Member Data Documentation
myData
template<class TheItemType > TheItemType** SMESH_Array2< TheItemType >::myData protected
Pointer to the row pointers table.
Referenced by SMESH_Array2< TheItemType >::ChangeValue(), SMESH_Array2< TheItemType >::SetValue(), SMESH_Array2< TheItemType >::Value(), and SMESH_Array2< TheItemType >::~SMESH_Array2().
myDeletable
template<class TheItemType > Standard_Boolean SMESH_Array2< TheItemType >::myDeletable protected
Flag showing who allocated the array.
Referenced by SMESH_Array2< TheItemType >::IsDeletable(), and SMESH_Array2< TheItemType >::~SMESH_Array2().
myLowerCol
template<class TheItemType > Standard_Integer SMESH_Array2< TheItemType >::myLowerCol protected
Referenced by SMESH_Array2< TheItemType >::LowerCol(), and SMESH_Array2< TheItemType >::RowLength().
myLowerRow
template<class TheItemType > Standard_Integer SMESH_Array2< TheItemType >::myLowerRow protected
Referenced by SMESH_Array2< TheItemType >::ColLength(), SMESH_Array2< TheItemType >::LowerRow(), and SMESH_Array2< TheItemType >::~SMESH_Array2().
myStart
template<class TheItemType > TheItemType* SMESH_Array2< TheItemType >::myStart protected
Pointer to the memory array.
Referenced by SMESH_Array2< TheItemType >::Assign(), SMESH_Array2< TheItemType >::Iterator::ChangeValue(), SMESH_Array2< TheItemType >::Init(), SMESH_Array2< TheItemType >::operator=(), SMESH_Array2< TheItemType >::SMESH_Array2(), SMESH_Array2< TheItemType >::Iterator::Value(), and SMESH_Array2< TheItemType >::~SMESH_Array2().
myUpperCol
template<class TheItemType > Standard_Integer SMESH_Array2< TheItemType >::myUpperCol protected
Referenced by SMESH_Array2< TheItemType >::ChangeValue(), SMESH_Array2< TheItemType >::RowLength(), SMESH_Array2< TheItemType >::SetValue(), SMESH_Array2< TheItemType >::UpperCol(), and SMESH_Array2< TheItemType >::Value().
myUpperRow
template<class TheItemType > Standard_Integer SMESH_Array2< TheItemType >::myUpperRow protected
Referenced by SMESH_Array2< TheItemType >::ChangeValue(), SMESH_Array2< TheItemType >::ColLength(), SMESH_Array2< TheItemType >::SetValue(), SMESH_Array2< TheItemType >::UpperRow(), and SMESH_Array2< TheItemType >::Value().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_Array2.hxx