FreeCAD: TechDrawGui::QGITemplate Class Reference
TechDrawGui::QGITemplate Class Reference abstract
#include <QGITemplate.h>
Public Types
enum { Type = QGraphicsItem::UserType + 150 }
Public Member Functions
void clearContents ()
virtual void draw ()=0
TechDraw::DrawTemplate * getTemplate ()
std::vector< TemplateTextField * > getTextFields (void)
qreal getY ()
QGITemplate (QGSPage *)
void setTemplate (TechDraw::DrawTemplate *obj)
int type () const
virtual void updateView (bool update=false)
~QGITemplate ()
Protected Member Functions
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value)
Protected Attributes
TechDraw::DrawTemplate * pageTemplate
std::vector< TemplateTextField * > textFields
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGITemplate()
QGITemplate::QGITemplate (QGSPage * scene)
References ZVALUE::TEMPLATE.
~QGITemplate()
QGITemplate::~QGITemplate ()
References pageTemplate.
Member Function Documentation
clearContents()
void QGITemplate::clearContents ()
draw()
virtual void TechDrawGui::QGITemplate::draw () pure virtual
Implemented in TechDrawGui::QGIDrawingTemplate, and TechDrawGui::QGISVGTemplate.
Referenced by updateView().
getTemplate()
TechDraw::DrawTemplate * TechDrawGui::QGITemplate::getTemplate ()
getTextFields()
std::vector< TemplateTextField * > TechDrawGui::QGITemplate::getTextFields (void)
Referenced by TechDrawGui::ViewProviderTemplate::setMarkers().
getY()
qreal TechDrawGui::QGITemplate::getY ()
itemChange()
QVariant QGITemplate::itemChange (GraphicsItemChange change, const QVariant & value) protected virtual
Reimplemented in TechDrawGui::QGIDrawingTemplate, and TechDrawGui::QGISVGTemplate.
setTemplate()
void QGITemplate::setTemplate (TechDraw::DrawTemplate * obj)
References pageTemplate.
Referenced by TechDrawGui::QGSPage::setPageTemplate(), and TechDrawGui::MDIViewPage::updateTemplate().
type()
int TechDrawGui::QGITemplate::type (void) const
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
updateView()
void QGITemplate::updateView (bool update = false) virtual
Reimplemented in TechDrawGui::QGIDrawingTemplate, and TechDrawGui::QGISVGTemplate.
References draw().
Referenced by TechDrawGui::QGSPage::setPageTemplate(), TechDrawGui::ViewProviderPage::setTemplateMarkers(), and TechDrawGui::MDIViewPage::updateTemplate().
Member Data Documentation
pageTemplate
TechDraw::DrawTemplate* TechDrawGui::QGITemplate::pageTemplate protected
Referenced by TechDrawGui::QGIDrawingTemplate::getParametricTemplate(), TechDrawGui::QGISVGTemplate::getSVGTemplate(), setTemplate(), and ~QGITemplate().
textFields
std::vector<TemplateTextField *> TechDrawGui::QGITemplate::textFields protected
Referenced by TechDrawGui::QGISVGTemplate::createClickHandles().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/QGITemplate.h
FreeCAD/src/Mod/TechDraw/Gui/QGITemplate.cpp