FreeCAD: Gui::SoFCUnifiedSelection Class Reference
Gui::SoFCUnifiedSelection Class Reference
Unified Selection node This is the new selection node for the 3D Viewer which will gradually remove all the low level selection nodes in the view provider.
#include <SoFCUnifiedSelection.h>
Public Types
enum HighlightModes { AUTO , ON , OFF }
Public Member Functions
void applySettings ()
virtual void doAction (SoAction *action)
const char * getFileFormatName (void) const
virtual void GLRenderBelowPath (SoGLRenderAction *action)
virtual void handleEvent (SoHandleEventAction *action)
SoFCUnifiedSelection (void)
void write (SoWriteAction *action)
Static Public Member Functions
static void finish (void)
static bool hasHighlight ()
static void initClass (void)
Public Attributes
SoSFColor colorHighlight
SoSFColor colorSelection
SoSFEnum highlightMode
SoSFEnum selectionMode
SoSFBool selectionRole
SoSFBool useNewSelection
Protected Member Functions
virtual ~SoFCUnifiedSelection ()
Friends
class View3DInventorViewer
Detailed Description
Unified Selection node This is the new selection node for the 3D Viewer which will gradually remove all the low level selection nodes in the view provider.
The handling of the highlighting and the selection will be unified here.
Author
Jürgen Riegel
Member Enumeration Documentation
HighlightModes
enum Gui::SoFCUnifiedSelection::HighlightModes
Enumerator
AUTO
ON
OFF
Constructor & Destructor Documentation
SoFCUnifiedSelection()
SoFCUnifiedSelection::SoFCUnifiedSelection (void)
Constructor.
~SoFCUnifiedSelection()
SoFCUnifiedSelection::~SoFCUnifiedSelection () protected virtual
Destructor.
Member Function Documentation
applySettings()
void SoFCUnifiedSelection::applySettings ()
References colorHighlight, colorSelection, ParameterGrp::GetBool(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), ParameterGrp::GetUnsigned(), highlightMode, OFF, and selectionMode.
doAction()
void SoFCUnifiedSelection::doAction (SoAction * action) virtual
References Gui::SelectionChanges::AddSelection, Gui::SoSelectionElementAction::All, Gui::SoSelectionElementAction::Append, AUTO, Gui::SelectionChanges::ClrSelection, colorHighlight, colorSelection, App::GetApplication(), Base::Persistence::getClassTypeId(), Gui::ViewProvider::getDetail(), Gui::ViewProvider::getDetailPath(), App::Application::getDocument(), Gui::ViewProviderDocumentObject::getObject(), Gui::ViewProvider::getRoot(), Gui::Application::getViewProvider(), Gui::Document::getViewProvidersOfType(), Gui::SoFCEnableHighlightAction::highlight, Gui::SoFCHighlightColorAction::highlightColor, highlightMode, Gui::Application::Instance, Base::BaseClass::isDerivedFrom(), Gui::ViewProvider::isSelectable(), Gui::SelectionSingleton::isSelected(), OFF, ON, Gui::SelectionChanges::pDocName, Gui::SelectionChanges::pObjectName, Gui::SelectionChanges::pSubName, Gui::SoSelectionElementAction::Remove, Gui::SelectionChanges::RmvPreselect, Gui::SelectionChanges::RmvSelection, Gui::SoFCHighlightAction::SelChange, Gui::SoFCSelectionAction::SelChange, Gui::Selection(), Gui::SoFCEnableSelectionAction::selection, Gui::SoFCSelectionColorAction::selectionColor, selectionMode, Gui::SoHighlightElementAction::setColor(), Gui::SoSelectionElementAction::setColor(), Gui::SoHighlightElementAction::setElement(), Gui::SoSelectionElementAction::setElement(), Gui::SoHighlightElementAction::setHighlighted(), Gui::SelectionChanges::SetPreselect, Gui::SelectionChanges::SetPreselectSignal, Gui::SelectionChanges::SetSelection, Gui::SelectionChanges::Type, useNewSelection, Gui::ViewProvider::useNewSelectionModel(), Gui::SelectionChanges::x, Gui::SelectionChanges::y, and Gui::SelectionChanges::z.
finish()
void SoFCUnifiedSelection::finish (void) static
Referenced by drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), draftguitools.gui_shapestrings.ShapeString::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_split.Split::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_edit.Edit::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_selectplane.Draft_SelectPlane::checkSelection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_labels.Label::create(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_shapestrings.ShapeString::createObject(), draftguitools.gui_texts.Text::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::escape(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_fillets.Fillet::numericRadius(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickAlign(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickAuto(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickCenter(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickFront(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickMove(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickPrevious(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickSide(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickTop(), draftguitools.gui_array_simple.Array::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
getFileFormatName()
const char * SoFCUnifiedSelection::getFileFormatName (void) const
GLRenderBelowPath()
void SoFCUnifiedSelection::GLRenderBelowPath (SoGLRenderAction * action) virtual
References Gui::SoGLWidgetElement::get().
handleEvent()
void SoFCUnifiedSelection::handleEvent (SoHandleEventAction * action) virtual
References AUTO, highlightMode, ON, Gui::Selection(), selectionMode, and selectionRole.
hasHighlight()
bool SoFCUnifiedSelection::hasHighlight () static
initClass()
void SoFCUnifiedSelection::initClass (void) static
Referenced by Gui::SoFCDB::init().
write()
void SoFCUnifiedSelection::write (SoWriteAction * action)
Referenced by gzip_utf8.GzipFile::seek().
Friends And Related Function Documentation
View3DInventorViewer
friend class View3DInventorViewer friend
Member Data Documentation
colorHighlight
SoSFColor Gui::SoFCUnifiedSelection::colorHighlight
Referenced by applySettings(), Gui::View3DInventorViewer::checkGroupOnTop(), and doAction().
colorSelection
SoSFColor Gui::SoFCUnifiedSelection::colorSelection
Referenced by applySettings(), Gui::View3DInventorViewer::checkGroupOnTop(), and doAction().
highlightMode
SoSFEnum Gui::SoFCUnifiedSelection::highlightMode
Referenced by applySettings(), doAction(), and handleEvent().
selectionMode
SoSFEnum Gui::SoFCUnifiedSelection::selectionMode
Referenced by applySettings(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonRef1(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonRef2(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonSupport(), doAction(), handleEvent(), and PartGui::Location::~Location().
selectionRole
SoSFBool Gui::SoFCUnifiedSelection::selectionRole
Referenced by handleEvent().
useNewSelection
SoSFBool Gui::SoFCUnifiedSelection::useNewSelection
Referenced by doAction().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SoFCUnifiedSelection.h
Sources/FreeCAD/src/Gui/SoFCUnifiedSelection.cpp