FreeCAD: Gui::WaitCursorP Class Reference
Gui::WaitCursorP Class Reference
Public Member Functions
WaitCursor::FilterEventsFlags ignoreEvents () const
void setBusy (bool)
void setIgnoreEvents (WaitCursor::FilterEventsFlags flags)
Static Public Member Functions
static WaitCursorP * getInstance ()
Protected Member Functions
bool eventFilter (QObject *, QEvent *)
bool isModalDialog (QObject *o) const
Member Function Documentation
eventFilter()
bool WaitCursorP::eventFilter (QObject * o, QEvent * e) protected
References isModalDialog(), Gui::WaitCursor::KeyEvents, and Gui::WaitCursor::MouseEvents.
getInstance()
WaitCursorP * WaitCursorP::getInstance () static
Referenced by Gui::WaitCursor::ignoreEvents(), Gui::WaitCursor::restoreCursor(), Gui::WaitCursor::setIgnoreEvents(), Gui::WaitCursor::setWaitCursor(), Gui::WaitCursor::WaitCursor(), and Gui::WaitCursor::~WaitCursor().
ignoreEvents()
WaitCursor::FilterEventsFlags WaitCursorP::ignoreEvents () const
Referenced by Gui::WaitCursor::ignoreEvents(), and Gui::WaitCursor::WaitCursor().
isModalDialog()
bool WaitCursorP::isModalDialog (QObject * o) const protected
References DraftVecUtils::find().
Referenced by eventFilter().
setBusy()
void WaitCursorP::setBusy (bool on)
Referenced by Gui::WaitCursor::restoreCursor(), and Gui::WaitCursor::setWaitCursor().
setIgnoreEvents()
void WaitCursorP::setIgnoreEvents (WaitCursor::FilterEventsFlags flags)
Referenced by Gui::WaitCursor::setIgnoreEvents(), and Gui::WaitCursor::~WaitCursor().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/WaitCursor.cpp