FreeCAD: MED::TQuad9a Struct Reference
MED::TQuad9a Struct Reference
#include <MED_GaussUtils.hxx>
Public Member Functions
virtual void InitFun (const TCCoordSliceArr &theRef, const TCCoordSliceArr &theGauss, TFun &theFun) const
TQuad9a ()
Public Member Functions inherited from MED::TShapeFun
bool Eval (const TCellInfo &theCellInfo, const TNodeInfo &theNodeInfo, const TElemNum &theElemNum, const TCCoordSliceArr &theRef, const TCCoordSliceArr &theGauss, TGaussCoord &theGaussCoord, EModeSwitch theMode)
TCoordSlice GetCoord (TInt theRefId)
TCCoordSlice GetCoord (TInt theRefId) const
void GetFun (const TCCoordSliceArr &theRef, const TCCoordSliceArr &theGauss, TFun &theFun) const
TInt GetNbRef () const
virtual void InitFun (const TCCoordSliceArr &theRef, const TCCoordSliceArr &theGauss, TFun &theFun) const =0
virtual bool IsSatisfy (const TCCoordSliceArr &theRefCoord) const
TShapeFun (TInt theDim=0, TInt theNbRef=0)
Additional Inherited Members
Public Attributes inherited from MED::TShapeFun
TInt myDim
TInt myNbRef
TFloatVector myRefCoord
Constructor & Destructor Documentation
TQuad9a()
MED::TQuad9a::TQuad9a ()
References MED::TShapeFun::GetCoord(), and MED::TShapeFun::GetNbRef().
Member Function Documentation
InitFun()
void MED::TQuad9a::InitFun (const TCCoordSliceArr & theRef, const TCCoordSliceArr & theGauss, TFun & theFun) const virtual
Implements MED::TShapeFun.
References MED::TShapeFun::GetFun(), and MED::TShapeFun::TFun::GetFunSlice().
The documentation for this struct was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/MED_GaussUtils.hxx
FreeCAD/src/3rdParty/salomesmesh/src/SMESH/MED_GaussUtils.cpp