FreeCAD: Ui_TaskRobotMessages Class Reference
Ui_TaskRobotMessages Class Reference
#include <ui_TaskRobotMessages.h>
Public Member Functions
void retranslateUi (QWidget *TaskRobotMessages)
void setupUi (QWidget *TaskRobotMessages)
Public Attributes
QPushButton * pushButtonClear
QTextEdit * textEditMessages
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void Ui_TaskRobotMessages::retranslateUi (QWidget * TaskRobotMessages)
References pushButtonClear, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Ui_TaskRobotMessages::setupUi (QWidget * TaskRobotMessages)
References pushButtonClear, retranslateUi(), textEditMessages, and verticalLayout.
Referenced by RobotGui::TaskRobotMessages::TaskRobotMessages().
Member Data Documentation
pushButtonClear
QPushButton* Ui_TaskRobotMessages::pushButtonClear
Referenced by retranslateUi(), and setupUi().
textEditMessages
QTextEdit* Ui_TaskRobotMessages::textEditMessages
Referenced by setupUi().
verticalLayout
QVBoxLayout* Ui_TaskRobotMessages::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Robot/Gui/ui_TaskRobotMessages.h