FreeCAD: Path::VoronoiCellPy Class Reference
Path::VoronoiCellPy Class Reference
The python export class for VoronoiCell.
#include <VoronoiCellPy.h>
Public Types
typedef VoronoiCell * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
VoronoiCellPy (VoronoiCell *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * richCompare (PyObject *v, PyObject *w, int op)
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of VoronoiCellPy.
static PyMethodDef Methods []
Methods structure of VoronoiCellPy.
static PyTypeObject Type
Type structure of VoronoiCellPy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~VoronoiCellPy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
static PyObject * staticCallback_containsPoint (PyObject *self, PyObject *args)
callback for the containsPoint() method
static PyObject * staticCallback_containsSegment (PyObject *self, PyObject *args)
callback for the containsSegment() method
static PyObject * staticCallback_isDegenerate (PyObject *self, PyObject *args)
callback for the isDegenerate() method
static PyObject * staticCallback_getSource (PyObject *self, PyObject *args)
callback for the getSource() method
PyObject * containsPoint (PyObject *args)
implementer for the containsPoint() method
PyObject * containsSegment (PyObject *args)
implementer for the containsSegment() method
PyObject * isDegenerate (PyObject *args)
implementer for the isDegenerate() method
PyObject * getSource (PyObject *args)
implementer for the getSource() method
callbacks and implementers for the python object attributes
static PyObject * staticCallback_getIndex (PyObject *self, void *closure)
getter callback for the Index attribute
static int staticCallback_setIndex (PyObject *self, PyObject *value, void *closure)
setter callback for the Index attribute
static PyObject * staticCallback_getColor (PyObject *self, void *closure)
getter callback for the Color attribute
static int staticCallback_setColor (PyObject *self, PyObject *value, void *closure)
setter callback for the Color attribute
static PyObject * staticCallback_getSourceIndex (PyObject *self, void *closure)
getter callback for the SourceIndex attribute
static int staticCallback_setSourceIndex (PyObject *self, PyObject *value, void *closure)
setter callback for the SourceIndex attribute
static PyObject * staticCallback_getSourceCategory (PyObject *self, void *closure)
getter callback for the SourceCategory attribute
static int staticCallback_setSourceCategory (PyObject *self, PyObject *value, void *closure)
setter callback for the SourceCategory attribute
static PyObject * staticCallback_getIncidentEdge (PyObject *self, void *closure)
getter callback for the IncidentEdge attribute
static int staticCallback_setIncidentEdge (PyObject *self, PyObject *value, void *closure)
setter callback for the IncidentEdge attribute
Py::Long getIndex (void) const
getter for the Index attribute
Py::Long getColor (void) const
getter for the Color attribute
void setColor (Py::Long arg)
setter for the Color attribute
Py::Long getSourceIndex (void) const
getter for the SourceIndex attribute
Py::Int getSourceCategory (void) const
getter for the SourceCategory attribute
Py::Object getIncidentEdge (void) const
getter for the IncidentEdge attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
VoronoiCell * getVoronoiCellPtr (void) const
getter for the object handled by this class
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for VoronoiCell.
Member Typedef Documentation
PointerType
typedef VoronoiCell* Path::VoronoiCellPy::PointerType
Constructor & Destructor Documentation
~VoronoiCellPy()
VoronoiCellPy::~VoronoiCellPy () protected
VoronoiCellPy()
VoronoiCellPy::VoronoiCellPy (VoronoiCell * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
containsPoint()
PyObject * VoronoiCellPy::containsPoint (PyObject * args)
implementer for the containsPoint() method
Referenced by staticCallback_containsPoint().
containsSegment()
PyObject * VoronoiCellPy::containsSegment (PyObject * args)
implementer for the containsSegment() method
Referenced by staticCallback_containsSegment().
getColor()
Py::Long VoronoiCellPy::getColor (void) const
getter for the Color attribute
References Path::Voronoi::ColorMask, and getVoronoiCellPtr().
Referenced by staticCallback_getColor().
getCustomAttributes()
PyObject * VoronoiCellPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getIncidentEdge()
Py::Object VoronoiCellPy::getIncidentEdge (void) const
getter for the IncidentEdge attribute
Referenced by staticCallback_getIncidentEdge().
getIndex()
Py::Long VoronoiCellPy::getIndex (void) const
getter for the Index attribute
References getVoronoiCellPtr().
Referenced by staticCallback_getIndex().
getSource()
PyObject * VoronoiCellPy::getSource (PyObject * args)
implementer for the getSource() method
Referenced by staticCallback_getSource().
getSourceCategory()
Py::Int VoronoiCellPy::getSourceCategory (void) const
getter for the SourceCategory attribute
Referenced by staticCallback_getSourceCategory().
getSourceIndex()
Py::Long VoronoiCellPy::getSourceIndex (void) const
getter for the SourceIndex attribute
Referenced by staticCallback_getSourceIndex().
GetType()
virtual PyTypeObject* Path::VoronoiCellPy::GetType (void) virtual
Reimplemented from Base::BaseClassPy.
getVoronoiCellPtr()
VoronoiCell * VoronoiCellPy::getVoronoiCellPtr (void) const
getter for the object handled by this class
Referenced by getColor(), getIndex(), representation(), and richCompare().
isDegenerate()
PyObject * VoronoiCellPy::isDegenerate (PyObject * args)
implementer for the isDegenerate() method
Referenced by staticCallback_isDegenerate().
PyInit()
int VoronoiCellPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::BaseClassPy.
PyMake()
PyObject * VoronoiCellPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References VoronoiCellPy().
representation()
std::string VoronoiCellPy::representation (void) const
References getVoronoiCellPtr().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
richCompare()
PyObject * VoronoiCellPy::richCompare (PyObject * v, PyObject * w, int op) static
References Path::VoronoiCell::dia, getVoronoiCellPtr(), Path::VoronoiCell::index, and Type.
setColor()
void VoronoiCellPy::setColor (Py::Long arg)
setter for the Color attribute
References Path::Voronoi::ColorMask.
Referenced by staticCallback_setColor().
setCustomAttributes()
int VoronoiCellPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_containsPoint()
PyObject * VoronoiCellPy::staticCallback_containsPoint (PyObject * self, PyObject * args) static
callback for the containsPoint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, containsPoint(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_containsSegment()
PyObject * VoronoiCellPy::staticCallback_containsSegment (PyObject * self, PyObject * args) static
callback for the containsSegment() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, containsSegment(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getColor()
PyObject * VoronoiCellPy::staticCallback_getColor (PyObject * self, void * closure) static
getter callback for the Color attribute
References Base::BaseExceptionFreeCADError, getColor(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getIncidentEdge()
PyObject * VoronoiCellPy::staticCallback_getIncidentEdge (PyObject * self, void * closure) static
getter callback for the IncidentEdge attribute
References Base::BaseExceptionFreeCADError, getIncidentEdge(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getIndex()
PyObject * VoronoiCellPy::staticCallback_getIndex (PyObject * self, void * closure) static
getter callback for the Index attribute
References Base::BaseExceptionFreeCADError, getIndex(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSource()
PyObject * VoronoiCellPy::staticCallback_getSource (PyObject * self, PyObject * args) static
callback for the getSource() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getSource(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSourceCategory()
PyObject * VoronoiCellPy::staticCallback_getSourceCategory (PyObject * self, void * closure) static
getter callback for the SourceCategory attribute
References Base::BaseExceptionFreeCADError, getSourceCategory(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSourceIndex()
PyObject * VoronoiCellPy::staticCallback_getSourceIndex (PyObject * self, void * closure) static
getter callback for the SourceIndex attribute
References Base::BaseExceptionFreeCADError, getSourceIndex(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isDegenerate()
PyObject * VoronoiCellPy::staticCallback_isDegenerate (PyObject * self, PyObject * args) static
callback for the isDegenerate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isDegenerate(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setColor()
int VoronoiCellPy::staticCallback_setColor (PyObject * self, PyObject * value, void * closure) static
setter callback for the Color attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setColor().
staticCallback_setIncidentEdge()
int VoronoiCellPy::staticCallback_setIncidentEdge (PyObject * self, PyObject * value, void * closure) static
setter callback for the IncidentEdge attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setIndex()
int VoronoiCellPy::staticCallback_setIndex (PyObject * self, PyObject * value, void * closure) static
setter callback for the Index attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setSourceCategory()
int VoronoiCellPy::staticCallback_setSourceCategory (PyObject * self, PyObject * value, void * closure) static
setter callback for the SourceCategory attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setSourceIndex()
int VoronoiCellPy::staticCallback_setSourceIndex (PyObject * self, PyObject * value, void * closure) static
setter callback for the SourceIndex attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
Member Data Documentation
GetterSetter
PyGetSetDef VoronoiCellPy::GetterSetter static
Attribute structure of VoronoiCellPy.
Methods
PyMethodDef VoronoiCellPy::Methods static
Initial value:
= {
    {"containsPoint",
        reinterpret_cast<PyCFunction>( staticCallback_containsPoint ),
        METH_VARARGS,
        "Returns true if the cell contains a point site"
    },
    {"containsSegment",
        reinterpret_cast<PyCFunction>( staticCallback_containsSegment ),
        METH_VARARGS,
        "Returns true if the cell contains a segment site"
    },
    {"isDegenerate",
        reinterpret_cast<PyCFunction>( staticCallback_isDegenerate ),
        METH_VARARGS,
        "Returns true if the cell doesn't have an incident edge"
    },
    {"getSource",
        reinterpret_cast<PyCFunction>( staticCallback_getSource ),
        METH_VARARGS,
        "Returns the Source for the cell"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of VoronoiCellPy.
Type
PyTypeObject VoronoiCellPy::Type static
Type structure of VoronoiCellPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), and richCompare().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/VoronoiCellPy.h
Sources/FreeCAD/src/Mod/Path/App/VoronoiCellPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/VoronoiCellPy.cpp