FreeCAD: Base::Flags< Enum > Class Template Reference
Base::Flags< Enum > Class Template Reference
#include <Bitmask.h>
Public Member Functions
constexpr Flags (Enum f)
constexpr bool isEqual (Flags f) const
constexpr void setFlag (Enum f, bool on=true)
constexpr bool testFlag (Enum f) const
Constructor & Destructor Documentation
Flags()
template<typename Enum > constexpr Base::Flags< Enum >::Flags (Enum f) constexpr
Member Function Documentation
isEqual()
template<typename Enum > constexpr bool Base::Flags< Enum >::isEqual (Flags< Enum > f) const constexpr
Referenced by App::ColorGradientProfile::isEqual().
setFlag()
template<typename Enum > constexpr void Base::Flags< Enum >::setFlag (Enum f, bool on = true) constexpr
Referenced by Gui::Dialog::DlgSettingsColorGradientImp::getProfile().
testFlag()
template<typename Enum > constexpr bool Base::Flags< Enum >::testFlag (Enum f) const constexpr
Referenced by Gui::Dialog::DlgSettingsColorGradientImp::setProfile().
The documentation for this class was generated from the following file:
FreeCAD/src/Base/Bitmask.h