FreeCAD: Base::Reader Class Reference
Base::Reader Class Reference
#include <Reader.h>
Public Member Functions
std::string getFileName () const
int getFileVersion () const
std::shared_ptr< Base::XMLReader > getLocalReader () const
std::istream & getStream ()
void initLocalReader (std::shared_ptr< Base::XMLReader >)
Reader (std::istream &, const std::string &, int version)
~Reader ()
Constructor & Destructor Documentation
Reader()
Base::Reader::Reader (std::istream & str, const std::string & name, int version)
~Reader()
Base::Reader::~Reader ()
Member Function Documentation
getFileName()
std::string Base::Reader::getFileName () const
Referenced by Fem::PropertyPostDataObject::RestoreDocFile(), and Part::PropertyPartShape::RestoreDocFile().
getFileVersion()
int Base::Reader::getFileVersion () const
Referenced by Gui::Document::RestoreDocFile().
getLocalReader()
std::shared_ptr< Base::XMLReader > Base::Reader::getLocalReader () const
Referenced by Base::XMLReader::readFiles().
getStream()
std::istream & Base::Reader::getStream ()
initLocalReader()
void Base::Reader::initLocalReader (std::shared_ptr< Base::XMLReader > reader)
Referenced by Gui::Document::importObjects(), and Gui::Document::RestoreDocFile().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Base/Reader.h
Sources/FreeCAD/src/Base/Reader.cpp