FreeCAD: TechDraw::GeomFormat Class Reference
TechDraw::GeomFormat Class Reference
#include <Cosmetic.h>
Public Member Functions
GeomFormat * clone (void) const
GeomFormat * copy (void) const
void dump (const char *title) const
GeomFormat ()
GeomFormat (int idx, LineFormat fmt)
GeomFormat (TechDraw::GeomFormat *gf)
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
boost::uuids::uuid getTag () const
virtual std::string getTagAsString (void) const
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
std::string toString (void) const
~GeomFormat ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Attributes
LineFormat m_format
int m_geomIndex
Protected Member Functions
void assignTag (const TechDraw::GeomFormat *gf)
void createNewTag ()
Protected Attributes
Py::Object PythonObject
boost::uuids::uuid tag
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
GeomFormat() [1/3]
GeomFormat::GeomFormat ()
References TechDraw::LineFormat::getDefEdgeColor(), TechDraw::LineFormat::getDefEdgeStyle(), and TechDraw::LineFormat::getDefEdgeWidth().
Referenced by copy().
GeomFormat() [2/3]
GeomFormat::GeomFormat (TechDraw::GeomFormat * gf)
References createNewTag(), TechDraw::LineFormat::m_color, m_format, m_geomIndex, TechDraw::LineFormat::m_style, TechDraw::LineFormat::m_visible, and TechDraw::LineFormat::m_weight.
GeomFormat() [3/3]
GeomFormat::GeomFormat (int idx, TechDraw::LineFormat fmt)
References createNewTag(), TechDraw::LineFormat::m_color, m_format, TechDraw::LineFormat::m_style, TechDraw::LineFormat::m_visible, and TechDraw::LineFormat::m_weight.
~GeomFormat()
GeomFormat::~GeomFormat ()
Member Function Documentation
assignTag()
void GeomFormat::assignTag (const TechDraw::GeomFormat * gf) protected
References Base::Persistence::getTypeId(), and tag.
clone()
GeomFormat * GeomFormat::clone (void) const
References copy(), and tag.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.CommandStructuralSystem::Activated(), ArchComponent.Component::execute(), ArchCurtainWall.CurtainWall::execute(), ArchTruss.Truss::execute(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated(), TechDraw::PropertyGeomFormatList::setValue(), and PathTests.TestPathHelix.TestPathHelix::test04().
copy()
GeomFormat * GeomFormat::copy (void) const
References GeomFormat(), TechDraw::LineFormat::m_color, m_format, m_geomIndex, TechDraw::LineFormat::m_style, TechDraw::LineFormat::m_visible, and TechDraw::LineFormat::m_weight.
Referenced by clone().
createNewTag()
void GeomFormat::createNewTag () protected
References tag.
Referenced by GeomFormat().
dump()
void GeomFormat::dump (const char * title) const
References Base::Console(), Base::ConsoleSingleton::Message(), and toString().
getMemSize()
unsigned int GeomFormat::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
getPyObject()
PyObject * GeomFormat::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
References PythonObject.
getTag()
boost::uuids::uuid GeomFormat::getTag () const
References tag.
Referenced by getTagAsString().
getTagAsString()
std::string GeomFormat::getTagAsString (void) const virtual
References getTag().
Referenced by TechDraw::CosmeticExtension::addGeomFormat().
Restore()
void GeomFormat::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References App::Color::fromHexString(), Base::XMLReader::getAttribute(), Base::XMLReader::getAttributeAsFloat(), Base::XMLReader::getAttributeAsInteger(), TechDraw::LineFormat::m_color, m_format, m_geomIndex, TechDraw::LineFormat::m_style, TechDraw::LineFormat::m_visible, TechDraw::LineFormat::m_weight, Base::XMLReader::readElement(), and TechDraw::CosmeticVertex::restoreCosmetic().
Referenced by TechDraw::PropertyGeomFormatList::Restore().
Save()
void GeomFormat::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References App::Color::asHexString(), Base::Writer::ind(), TechDraw::LineFormat::m_color, m_format, m_geomIndex, TechDraw::LineFormat::m_style, TechDraw::LineFormat::m_visible, TechDraw::LineFormat::m_weight, and Base::Writer::Stream().
toString()
std::string GeomFormat::toString (void) const
References m_format, m_geomIndex, and TechDraw::LineFormat::toString().
Referenced by dump().
Member Data Documentation
m_format
LineFormat TechDraw::GeomFormat::m_format
Referenced by TechDrawGui::TaskLineDecor::applyDecorations(), copy(), TechDrawGui::QGIViewPart::drawViewPart(), GeomFormat(), TechDrawGui::TaskLineDecor::getDefaults(), Restore(), Save(), and toString().
m_geomIndex
int TechDraw::GeomFormat::m_geomIndex
Referenced by copy(), GeomFormat(), Restore(), Save(), and toString().
PythonObject
Py::Object TechDraw::GeomFormat::PythonObject protected
Referenced by getPyObject().
tag
boost::uuids::uuid TechDraw::GeomFormat::tag protected
Referenced by PathScripts.PathDressupHoldingTags.MapWireToTag::add(), assignTag(), PathScripts.PathDressupHoldingTags.MapWireToTag::cleanupEdges(), clone(), PathScripts.PathDressupHoldingTags.MapWireToTag::commandsForEdges(), createNewTag(), Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.ChunkBase::dump_header(), getTag(), ArchPanel.PanelCut::getWires(), PathScripts.PathDressupHoldingTags.MapWireToTag::shell(), and FreeCADInit.FCADLogger::trace().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/App/Cosmetic.h
FreeCAD/src/Mod/TechDraw/App/Cosmetic.cpp