FreeCAD: Base::PyStreambuf Class Reference
Base::PyStreambuf Class Reference
#include <Stream.h>
Public Types
enum Type { StringIO , BytesIO , Unknown }
Public Member Functions
PyStreambuf (PyObject *o, std::size_t buf_size=256, std::size_t put_back=8)
void setType (Type t)
virtual ~PyStreambuf ()
Protected Member Functions
int_type overflow (int_type c=EOF)
pos_type seekoff (off_type offset, seekdir dir, openmode)
pos_type seekpos (pos_type offset, openmode mode)
int sync ()
int_type underflow ()
std::streamsize xsputn (const char *s, std::streamsize num)
Member Enumeration Documentation
Type
enum Base::PyStreambuf::Type
Enumerator
StringIO
BytesIO
Unknown
Constructor & Destructor Documentation
PyStreambuf()
PyStreambuf::PyStreambuf (PyObject * o, std::size_t buf_size = 256, std::size_t put_back = 8)
~PyStreambuf()
PyStreambuf::~PyStreambuf () virtual
References sync().
Member Function Documentation
overflow()
PyStreambuf::int_type PyStreambuf::overflow (PyStreambuf::int_type ch = EOF) protected
References sync().
seekoff()
PyStreambuf::pos_type PyStreambuf::seekoff (PyStreambuf::off_type offset, PyStreambuf::seekdir dir, PyStreambuf::openmode) protected
Referenced by seekpos().
seekpos()
PyStreambuf::pos_type PyStreambuf::seekpos (PyStreambuf::pos_type offset, PyStreambuf::openmode mode) protected
References seekoff().
setType()
void Base::PyStreambuf::setType (Type t)
sync()
int PyStreambuf::sync () protected
Referenced by overflow(), and ~PyStreambuf().
underflow()
PyStreambuf::int_type PyStreambuf::underflow () protected
xsputn()
std::streamsize PyStreambuf::xsputn (const char * s, std::streamsize num) protected
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Base/Stream.h
Sources/FreeCAD/src/Base/Stream.cpp