FreeCAD: Gui::Dialog::ButtonModel Class Reference
Gui::Dialog::ButtonModel Class Reference
#include <DlgCustomizeSpaceball.h>
Public Member Functions
ButtonModel (QObject *parent)
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
void goButtonPress (int number)
void goClear ()
void goMacroRemoved (const QByteArray &macroName)
void insertButtonRows (int number)
void loadConfig (const char *RequiredDeviceName)
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
void setCommand (int row, QString command)
Constructor & Destructor Documentation
ButtonModel()
ButtonModel::ButtonModel (QObject * parent)
Member Function Documentation
data()
QVariant ButtonModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
References Gui::BitmapFactory(), Base::Console(), ParameterGrp::GetGroups(), and Base::ConsoleSingleton::Log().
Referenced by Mod.Show.mTempoVis.TempoVis::activateWorkbench(), Mod.Show.SceneDetail.SceneDetail::apply_data(), importIFClegacy.IfcSchema::capitalize(), Gui::Dialog::PrintModel::data(), Mod.Show.mTempoVis.TempoVis::forget(), Mod.Show.mTempoVis.TempoVis::forgetDetail(), Mod.Show.mTempoVis.TempoVis::has(), ArchSchedule.CommandArchSchedule::IsActive(), importIFClegacy.IfcSchema::readEntities(), importIFClegacy.IfcSchema::readTypes(), Mod.Show.mTempoVis.TempoVis::restore(), Mod.Show.mTempoVis.TempoVis::save(), Mod.Show.mTempoVis.TempoVis::stored_val(), FeaturePython.ViewProviderOctahedron::updateData(), and Dice3DS.dom3ds.UndefinedChunk::write().
goButtonPress()
void ButtonModel::goButtonPress (int number)
References insertButtonRows().
Referenced by Gui::Dialog::DlgCustomizeSpaceball::event().
goClear()
void ButtonModel::goClear ()
References ParameterGrp::Clear(), and rowCount().
Referenced by loadConfig().
goMacroRemoved()
void ButtonModel::goMacroRemoved (const QByteArray & macroName)
References ParameterGrp::GetGroups().
Referenced by Gui::Dialog::DlgCustomizeSpaceball::onRemoveMacroAction().
insertButtonRows()
void ButtonModel::insertButtonRows (int number)
References ParameterGrp::GetGroup(), ParameterGrp::GetGroups(), and ParameterGrp::SetASCII().
Referenced by goButtonPress().
loadConfig()
void ButtonModel::loadConfig (const char * RequiredDeviceName)
References goClear().
rowCount()
int ButtonModel::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
References ParameterGrp::GetGroups().
Referenced by package_list.PackageListItemModel::append_item(), package_list.PackageListItemModel::clear(), goClear(), and Gui::Dialog::PrintModel::rowCount().
setCommand()
void ButtonModel::setCommand (int row, QString command)
References ParameterGrp::GetGroups().
Referenced by Gui::Dialog::ButtonView::goChangedCommand().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgCustomizeSpaceball.h
FreeCAD/src/Gui/DlgCustomizeSpaceball.cpp