FreeCAD: ArchEquipment Namespace Reference
ArchEquipment Namespace Reference
Workbenches » Python workbenches » Arch
The Equipment object and tools.
Functions
def createMeshView (obj, direction=FreeCAD.Vector(0, 0,-1), outeronly=False, largestonly=False)
def makeEquipment (baseobj=None, placement=None, name="Equipment")
Detailed Description
The Equipment object and tools.
This module provides tools to build equipment objects. Equipment is used to represent furniture and all kinds of electrical or hydraulic appliances in a building
Function Documentation
createMeshView()
def ArchEquipment.createMeshView (obj, direction = FreeCAD.Vector(0,0,-1), outeronly = False, largestonly = False)
createMeshView(obj,[direction,outeronly,largestonly]): creates a flat shape that is the
projection of the given mesh object in the given direction (default = on the XY plane). If
outeronly is True, only the outer contour is taken into consideration, discarding the inner
holes. If largestonly is True, only the largest segment of the given mesh will be used.
References ArchComponent.Component.onChanged(), ArchComponent.Component.onDocumentRestored(), draftutils.translate.QT_TRANSLATE_NOOP, and DraftVecUtils.rounded().
makeEquipment()
def ArchEquipment.makeEquipment (baseobj = None, placement = None, name = "Equipment")