FreeCAD: PathScripts.post.opensbp_post Namespace Reference
PathScripts.post.opensbp_post Namespace Reference
Functions
def arc (command)
def comment (command)
def export (objectslist, filename, argstring)
def getImperialValue (val)
def getMetricValue (val)
def linenumber ()
def move (command)
def parse (pathobj)
def spindle (command)
def tool_change (command)
Variables
string COMMAND_SPACE = ","
dictionary CurrentState = {}
def GetValue = getMetricValue
now = datetime.datetime.now()
bool OUTPUT_COMMENTS = False
bool OUTPUT_HEADER = True
string POST_OPERATION = ''''''
string POSTAMBLE = ''''''
string PRE_OPERATION = ''''''
string PREAMBLE = ''''''
pythonopen = open
dictionary scommands
bool SHOW_EDITOR = True
string TOOL_CHANGE = ''''''
string TOOLTIP
string TOOLTIP_ARGS
Function Documentation
arc()
def PathScripts.post.opensbp_post.arc (command)
References PathScripts.post.opensbp_post.GetValue.
comment()
def PathScripts.post.opensbp_post.comment (command)
export()
def PathScripts.post.opensbp_post.export (objectslist, filename, argstring)
References PathScripts.post.opensbp_post.linenumber(), PathScripts.post.opensbp_post.parse(), and PathScripts.post.opensbp_post.pythonopen.
getImperialValue()
def PathScripts.post.opensbp_post.getImperialValue (val)
getMetricValue()
def PathScripts.post.opensbp_post.getMetricValue (val)
linenumber()
def PathScripts.post.opensbp_post.linenumber ()
Referenced by PathScripts.post.opensbp_post.export(), and PathScripts.post.opensbp_post.parse().
move()
def PathScripts.post.opensbp_post.move (command)
References PathScripts.post.opensbp_post.GetValue.
parse()
def PathScripts.post.opensbp_post.parse (pathobj)
References PathScripts.post.opensbp_post.linenumber().
Referenced by PathScripts.post.opensbp_post.export().
spindle()
def PathScripts.post.opensbp_post.spindle (command)
tool_change()
def PathScripts.post.opensbp_post.tool_change (command)
Variable Documentation
COMMAND_SPACE
string PathScripts.post.opensbp_post.COMMAND_SPACE = ","
CurrentState
dictionary PathScripts.post.opensbp_post.CurrentState = {}
GetValue
def PathScripts.post.opensbp_post.GetValue = getMetricValue
Referenced by PathScripts.post.opensbp_post.arc(), and PathScripts.post.opensbp_post.move().
now
PathScripts.post.opensbp_post.now = datetime.datetime.now()
OUTPUT_COMMENTS
bool PathScripts.post.opensbp_post.OUTPUT_COMMENTS = False
OUTPUT_HEADER
bool PathScripts.post.opensbp_post.OUTPUT_HEADER = True
POST_OPERATION
string PathScripts.post.opensbp_post.POST_OPERATION = ''''''
POSTAMBLE
string PathScripts.post.opensbp_post.POSTAMBLE = ''''''
PRE_OPERATION
string PathScripts.post.opensbp_post.PRE_OPERATION = ''''''
PREAMBLE
string PathScripts.post.opensbp_post.PREAMBLE = ''''''
pythonopen
PathScripts.post.opensbp_post.pythonopen = open
Referenced by PathScripts.post.opensbp_post.export().
scommands
dictionary PathScripts.post.opensbp_post.scommands
Initial value:
 =  {
     "G0": move,
     "G1": move,
     "G2": arc,
     "G3": arc,
     "M6": tool_change,
     "M3": spindle,
     "G00": move,
     "G01": move,
     "G02": arc,
     "G03": arc,
     "M06": tool_change,
     "M03": spindle,
     "message": comment
 }
SHOW_EDITOR
bool PathScripts.post.opensbp_post.SHOW_EDITOR = True
TOOL_CHANGE
string PathScripts.post.opensbp_post.TOOL_CHANGE = ''''''
TOOLTIP
string PathScripts.post.opensbp_post.TOOLTIP
Initial value:
 =  '''
 This is an postprocessor file for the Path workbench. It will output path data
 in a format suitable for OpenSBP controllers like shopbot.  This postprocessor,
 once placed in the appropriate PathScripts folder, can be used directly from
 inside FreeCAD, via the GUI importer or via python scripts with:
 import Path
 Path.write(object,"/path/to/file.ncc","post_opensbp")
 '''
TOOLTIP_ARGS
string PathScripts.post.opensbp_post.TOOLTIP_ARGS
Initial value:
 =  '''
 Arguments for opensbp:
     --comments          ... insert comments - mostly for debugging
     --inches            ... convert output to inches
     --no-header         ... suppress header output
     --no-show-editor    ... don't show editor, just save result
 '''