FreeCAD: Inspection::InspectNominalMesh Class Reference
Inspection::InspectNominalMesh Class Reference
#include <InspectionFeature.h>
Public Member Functions
virtual float getDistance (const Base::Vector3f &) const
InspectNominalMesh (const Mesh::MeshObject &rMesh, float offset)
~InspectNominalMesh ()
Public Member Functions inherited from Inspection::InspectNominalGeometry
virtual float getDistance (const Base::Vector3f &) const =0
InspectNominalGeometry ()
virtual ~InspectNominalGeometry ()
Constructor & Destructor Documentation
InspectNominalMesh()
InspectNominalMesh::InspectNominalMesh (const Mesh::MeshObject & rMesh, float offset)
References MeshCore::MeshAlgorithm::GetAverageEdgeLength(), Mesh::MeshObject::getTransform(), and Base::BoundBox3< _Precision >::Transformed().
~InspectNominalMesh()
InspectNominalMesh::~InspectNominalMesh ()
Member Function Documentation
getDistance()
float InspectNominalMesh::getDistance (const Base::Vector3f & point) const virtual
Implements Inspection::InspectNominalGeometry.
References MeshCore::MeshGeomFacet::DistanceToPoint(), MeshCore::MeshGeomFacet::GetNormal(), and MeshCore::MeshGeomFacet::Transform().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Inspection/App/InspectionFeature.h
FreeCAD/src/Mod/Inspection/App/InspectionFeature.cpp