FreeCAD: Gui::Dialog::DlgSettingsImageImp Class Reference
Gui::Dialog::DlgSettingsImageImp Class Reference
The DlgSettingsImageImp class implements a preference page to change settings for the Inventor viewer.
#include <DlgSettingsImageImp.h>
Public Member Functions
DlgSettingsImageImp (QWidget *parent=0)
Constructs a DlgSettingsImageImp as a child of 'parent', with the name 'name' and widget flags set to 'f'.
~DlgSettingsImageImp ()
Destroys the object and frees any allocated resources.
Image dimensions
void setImageSize (int, int)
Sets the image size to (w, h).
void setImageSize (const QSize &)
Sets the image size to s.
QSize imageSize () const
Returns the currently set image size.
int imageWidth () const
Returns the currently set image width.
int imageHeight () const
Returns the currently set image height.
Image meta information
void setMethod (const QByteArray &)
QByteArray method () const
QString comment () const
Returns the comment of the picture.
int backgroundType () const
void setBackgroundType (int)
Sets the image size to (w, h).
bool addWatermark () const
void onSelectedFilter (const QString &)
void on_buttonRatioScreen_clicked ()
void on_buttonRatio4x3_clicked ()
void on_buttonRatio16x9_clicked ()
void on_buttonRatio1x1_clicked ()
void on_standardSizeBox_activated (int)
void on_comboMethod_activated (int)
void adjustImageSize (float fRatio)
void changeEvent (QEvent *e)
Detailed Description
The DlgSettingsImageImp class implements a preference page to change settings for the Inventor viewer.
Author
Werner Mayer
Constructor & Destructor Documentation
DlgSettingsImageImp()
DlgSettingsImageImp::DlgSettingsImageImp (QWidget * parent = 0)
Constructs a DlgSettingsImageImp as a child of 'parent', with the name 'name' and widget flags set to 'f'.
~DlgSettingsImageImp()
DlgSettingsImageImp::~DlgSettingsImageImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
addWatermark()
bool DlgSettingsImageImp::addWatermark () const
Referenced by StdViewScreenShot::activated().
adjustImageSize()
void DlgSettingsImageImp::adjustImageSize (float fRatio) protected
Referenced by on_buttonRatio16x9_clicked(), on_buttonRatio1x1_clicked(), on_buttonRatio4x3_clicked(), and on_buttonRatioScreen_clicked().
backgroundType()
int DlgSettingsImageImp::backgroundType () const
Referenced by StdViewScreenShot::activated().
changeEvent()
void DlgSettingsImageImp::changeEvent (QEvent * e) protected
comment()
QString DlgSettingsImageImp::comment () const
Returns the comment of the picture.
If for the currently selected image format no comments are supported QString() is returned.
Referenced by StdViewScreenShot::activated().
imageHeight()
int DlgSettingsImageImp::imageHeight () const
Returns the currently set image height.
Referenced by StdViewScreenShot::activated().
imageSize()
QSize DlgSettingsImageImp::imageSize () const
Returns the currently set image size.
imageWidth()
int DlgSettingsImageImp::imageWidth () const
Returns the currently set image width.
Referenced by StdViewScreenShot::activated().
method()
QByteArray DlgSettingsImageImp::method () const
Referenced by StdViewScreenShot::activated(), PathScripts.PathDressupRampEntry.ObjectDressup::execute(), and PathScripts.PathDressupRampEntry.ObjectDressup::generateRamps().
on_buttonRatio16x9_clicked
void DlgSettingsImageImp::on_buttonRatio16x9_clicked () protected slot
References adjustImageSize().
on_buttonRatio1x1_clicked
void DlgSettingsImageImp::on_buttonRatio1x1_clicked () protected slot
References adjustImageSize().
on_buttonRatio4x3_clicked
void DlgSettingsImageImp::on_buttonRatio4x3_clicked () protected slot
References adjustImageSize().
on_buttonRatioScreen_clicked
void DlgSettingsImageImp::on_buttonRatioScreen_clicked () protected slot
References adjustImageSize().
on_comboMethod_activated
void DlgSettingsImageImp::on_comboMethod_activated (int index) protected slot
on_standardSizeBox_activated
void DlgSettingsImageImp::on_standardSizeBox_activated (int index) protected slot
onSelectedFilter
void DlgSettingsImageImp::onSelectedFilter (const QString & filter) slot
Referenced by StdViewScreenShot::activated().
setBackgroundType()
void DlgSettingsImageImp::setBackgroundType (int t)
Sets the image size to (w, h).
Referenced by StdViewScreenShot::activated().
setImageSize() [1/2]
void DlgSettingsImageImp::setImageSize (const QSize & s)
Sets the image size to s.
setImageSize() [2/2]
void DlgSettingsImageImp::setImageSize (int w, int h)
Sets the image size to (w, h).
Referenced by StdViewScreenShot::activated().
setMethod()
void DlgSettingsImageImp::setMethod (const QByteArray & m)
Referenced by StdViewScreenShot::activated().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgSettingsImageImp.h
Sources/FreeCAD/src/Gui/DlgSettingsImageImp.cpp