FreeCAD: Gui::Dialog::ParameterUInt Class Reference
Gui::Dialog::ParameterUInt Class Reference
The ParameterUInt class allows interaction with "unsigned integer" parameter leaves.
#include <DlgParameterImp.h>
Public Member Functions
void appendToGroup ()
Append this item as leaf to the parameter group.
void changeValue ()
Opens an input dialog to change the value.
ParameterUInt (QTreeWidget *parent, QString label1, unsigned long value, const Base::Reference< ParameterGrp > &hcGrp)
Constructor.
void removeFromGroup ()
Remove the leaf from the parameter group.
~ParameterUInt ()
Public Member Functions inherited from Gui::Dialog::ParameterValueItem
ParameterValueItem (QTreeWidget *parent, const Base::Reference< ParameterGrp > &hcGrp)
Constructor.
virtual void setData (int column, int role, const QVariant &value)
If the name of the item has changed replace() is invoked.
virtual ~ParameterValueItem ()
Protected Member Functions
void replace (const QString &oldName, const QString &newName)
Replaces the name of the leaf from oldName to newName.
Detailed Description
The ParameterUInt class allows interaction with "unsigned integer" parameter leaves.
Author
Werner Mayer
Constructor & Destructor Documentation
ParameterUInt()
ParameterUInt::ParameterUInt (QTreeWidget * parent, QString label1, unsigned long value, const Base::Reference< ParameterGrp > & hcGrp)
Constructor.
References Gui::BitmapFactory().
~ParameterUInt()
ParameterUInt::~ParameterUInt ()
Member Function Documentation
appendToGroup()
void ParameterUInt::appendToGroup () virtual
Append this item as leaf to the parameter group.
Implements Gui::Dialog::ParameterValueItem.
changeValue()
void ParameterUInt::changeValue () virtual
Opens an input dialog to change the value.
Implements Gui::Dialog::ParameterValueItem.
References Gui::Dialog::DlgInputDialogImp::getUIntBox(), Gui::UIntSpinBox::setRange(), Gui::UIntSpinBox::setValue(), and Gui::Dialog::DlgInputDialogImp::UIntBox.
removeFromGroup()
void ParameterUInt::removeFromGroup () virtual
Remove the leaf from the parameter group.
Implements Gui::Dialog::ParameterValueItem.
replace()
void ParameterUInt::replace (const QString & oldName, const QString & newName) protected virtual
Replaces the name of the leaf from oldName to newName.
Implements Gui::Dialog::ParameterValueItem.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgParameterImp.h
Sources/FreeCAD/src/Gui/DlgParameterImp.cpp