FreeCAD: zipios::FileCollection Class Reference
zipios::FileCollection Class Reference abstract
FileCollection is an abstract baseclass that represents a collection of files.
#include <fcoll.h>
Public Types
enum MatchPath { IGN, MATCH }
Public Member Functions
virtual FileCollection * clone () const =0
Create a heap allocated clone of the object this method is called for.
virtual void close ()=0
Closes the FileCollection.
virtual ConstEntries entries () const
Returns a vector of const pointers to the entries in the FileCollection.
FileCollection ()
FileCollection constructor.
FileCollection (const FileCollection &src)
Copy constructor.
virtual ConstEntryPointer getEntry (const string &name, MatchPath matchpath=MATCH) const
Returns a ConstEntryPointer to a FileEntry object for the entry with the specified name.
virtual istream * getInputStream (const ConstEntryPointer &entry)=0
Returns a pointer to an opened istream for the specified FileEntry.
virtual istream * getInputStream (const string &entry_name, MatchPath matchpath=MATCH)=0
Returns a pointer to an opened istream for the specified entry name.
virtual string getName () const
Returns the name of the FileCollection.
bool isValid () const
The member function returns true if the collection is valid.
const FileCollection & operator= (const FileCollection &src)
Copy assignment operator.
virtual int size () const
Returns the number of entries in the FileCollection.
virtual ~FileCollection ()
FileCollection destructor.
Detailed Description
FileCollection is an abstract baseclass that represents a collection of files.
The specializations of FileCollection represents different origins of file collections, such as directories, simple filename lists and compressed archives.
Member Enumeration Documentation
MatchPath
enum zipios::FileCollection::MatchPath
Enumerator
IGN
MATCH
Constructor & Destructor Documentation
FileCollection() [1/2]
zipios::FileCollection::FileCollection () explicit
FileCollection constructor.
FileCollection() [2/2]
zipios::FileCollection::FileCollection (const FileCollection & src)
Copy constructor.
~FileCollection()
zipios::FileCollection::~FileCollection () virtual
FileCollection destructor.
Member Function Documentation
clone()
virtual FileCollection* zipios::FileCollection::clone () const pure virtual
Create a heap allocated clone of the object this method is called for.
The caller is responsible for deallocating the clone when he is done with it.
Returns
A heap allocated copy of the object this method is called for.
Implemented in zipios::ZipFile, zipios::DirectoryCollection, and zipios::CollectionCollection.
Referenced by ArchPanel.CommandPanelSheet::Activated(), zipios::CollectionCollection::addCollection(), ArchComponent.Component::execute(), ArchCurtainWall.CurtainWall::execute(), ArchTruss.Truss::execute(), and Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated().
close()
virtual void zipios::FileCollection::close () pure virtual
Closes the FileCollection.
Implemented in zipios::ZipFile, zipios::DirectoryCollection, and zipios::CollectionCollection.
Referenced by femexamples.examplesgui.FemExamples::reject().
entries()
ConstEntries zipios::FileCollection::entries () const virtual
Returns a vector of const pointers to the entries in the FileCollection.
Returns
a ConstEntries containing the entries of the FileCollection.
Exceptions
InvalidStateException Thrown if the collection is invalid.
Reimplemented in zipios::DirectoryCollection, and zipios::CollectionCollection.
Referenced by zipios::DirectoryCollection::entries(), and zipios::operator<<().
getEntry()
ConstEntryPointer zipios::FileCollection::getEntry (const string & name, MatchPath matchpath = MATCH) const virtual
Returns a ConstEntryPointer to a FileEntry object for the entry with the specified name.
To ignore the path part of the filename in search of a match, specify FileCollection::IGNORE as the second argument.
Parameters
name A string containing the name of the entry to get.
matchpath Speficy MATCH, if the path should match as well, specify IGNORE, if the path should be ignored.
Returns
A ConstEntryPointer to the found entry. The returned pointer equals zero if no entry is found.
Exceptions
InvalidStateException Thrown if the collection is invalid.
Reimplemented in zipios::DirectoryCollection, and zipios::CollectionCollection.
References MATCH.
Referenced by zipios::DirectoryCollection::getEntry(), and zipios::ZipFile::getInputStream().
getInputStream() [1/2]
virtual istream* zipios::FileCollection::getInputStream (const ConstEntryPointer & entry) pure virtual
Returns a pointer to an opened istream for the specified FileEntry.
It is the callers responsibility to delete the stream when he is done with it. Returns 0, if there is no such FileEntry in the FileCollection.
Parameters
entry A ConstEntryPointer to the FileEntry to get an istream to.
Returns
an open istream for the specified entry. The istream is allocated on heap and it is the users responsibility to delete it when he is done with it.
Exceptions
InvalidStateException Thrown if the collection is invalid.
Implemented in zipios::ZipFile, zipios::DirectoryCollection, and zipios::CollectionCollection.
getInputStream() [2/2]
virtual istream* zipios::FileCollection::getInputStream (const string & entry_name, MatchPath matchpath = MATCH) pure virtual
Returns a pointer to an opened istream for the specified entry name.
It is the callers responsibility to delete the stream when he is done with it. Returns 0, if there is no entry with the specified name in the FileCollection.
Parameters
entry_name
matchpath Speficy MATCH, if the path should match as well, specify IGNORE, if the path should be ignored.
Returns
an open istream for the specified entry. The istream is allocated on heap and it is the users responsibility to delete it when he is done with it.
Exceptions
InvalidStateException Thrown if the collection is invalid.
Implemented in zipios::ZipFile, zipios::DirectoryCollection, and zipios::CollectionCollection.
getName()
string zipios::FileCollection::getName () const virtual
Returns the name of the FileCollection.
Returns
the name of the FileCollection.
Exceptions
InvalidStateException Thrown if the collection is invalid.
Referenced by zipios::operator<<().
isValid()
bool zipios::FileCollection::isValid () const
The member function returns true if the collection is valid.
Returns
true if the collection is valid.
Referenced by zipios::CollectionCollection::addCollection().
operator=()
const FileCollection & zipios::FileCollection::operator= (const FileCollection & src)
Copy assignment operator.
Referenced by zipios::CollectionCollection::operator=().
size()
int zipios::FileCollection::size () const virtual
Returns the number of entries in the FileCollection.
Returns
the number of entries in the FileCollection.
Exceptions
InvalidStateException Thrown if the collection is invalid.
Reimplemented in zipios::DirectoryCollection, and zipios::CollectionCollection.
Referenced by PathScripts.PostUtils.GCodeEditorDialog::done().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/zipios++/fcoll.h
Sources/FreeCAD/src/zipios++/fcoll.cpp