FreeCAD: Gui::PythonWorkbench Class Reference
Gui::PythonWorkbench Class Reference
The PythonWorkbench class allows the manipulation of the workbench from Python.
#include <Workbench.h>
Public Member Functions
virtual void createMainWindowPopupMenu (MenuItem *) const
Sets up the contextmenu for the main window for this workbench.
PythonWorkbench ()
virtual void setupContextMenu (const char *recipient, MenuItem *) const
Defines the standard context menu.
~PythonWorkbench ()
Public Member Functions inherited from Gui::PythonBaseWorkbench
PyObject * getPyObject ()
Creates and returns immediately the corresponding Python workbench object.
PythonBaseWorkbench ()
~PythonBaseWorkbench ()
void appendMenu (const std::list< std::string > &menu, const std::list< std::string > &items) const
Appends a new menu.
void removeMenu (const std::string &menu) const
Removes a menu.
void appendContextMenu (const std::list< std::string > &menu, const std::list< std::string > &items) const
Appends new context menu items.
void removeContextMenu (const std::string &menu) const
Removes a context menu.
void clearContextMenu ()
void appendToolbar (const std::string &bar, const std::list< std::string > &items) const
Appends a new toolbar.
void removeToolbar (const std::string &bar) const
Removes a toolbar.
void appendCommandbar (const std::string &bar, const std::list< std::string > &items) const
Appends a new command bar.
void removeCommandbar (const std::string &bar) const
Removes a command bar.
Public Member Functions inherited from Gui::Workbench
bool activate ()
Activates the workbench and adds/removes GUI elements.
virtual void activated ()
Run some actions when the workbench gets activated.
void addTaskWatcher (const std::vector< Gui::TaskView::TaskWatcher * > &Watcher)
helper to add TaskWatcher to the TaskView
virtual void createMainWindowPopupMenu (MenuItem *) const
Sets up the contextmenu for the main window for this workbench.
virtual void deactivated ()
Run some actions when the workbench gets deactivated.
PyObject * getPyObject ()
The default implementation returns an instance of WorkbenchPy.
std::list< std::pair< std::string, std::list< std::string > > > getToolbarItems () const
Shows a list of all toolbars and their commands.
std::list< std::string > listCommandbars () const
std::list< std::string > listMenus () const
std::list< std::string > listToolbars () const
std::string name () const
Returns the name of the workbench object.
void removeTaskWatcher (void)
remove the added TaskWatcher
void retranslate () const
Translates the window titles of all menus, toolbars and dock windows.
void setName (const std::string &)
Set the name to the workbench object.
virtual void setupContextMenu (const char *recipient, MenuItem *) const
Sets up the contextmenu for this workbench.
Workbench ()
Constructs a workbench object.
virtual ~Workbench ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Member Functions
ToolBarItem * setupCommandBars () const
Returns a ToolBarItem tree structure of command bars for this workbench.
DockWindowItems * setupDockWindows () const
Returns a DockWindowItems structure of dock windows this workbench.
MenuItem * setupMenuBar () const
Returns a MenuItem tree structure of menus for this workbench.
ToolBarItem * setupToolBars () const
Returns a ToolBarItem tree structure of toolbars for this workbench.
Protected Member Functions inherited from Gui::PythonBaseWorkbench
Protected Member Functions inherited from Gui::Workbench
void addPermanentMenuItems (MenuItem *) const
Add permanent menu items to the structure.
virtual ToolBarItem * setupCommandBars () const =0
Returns a ToolBarItem tree structure of command bars for this workbench.
virtual DockWindowItems * setupDockWindows () const =0
Returns a DockWindowItems structure of dock windows this workbench.
virtual MenuItem * setupMenuBar () const =0
Returns a MenuItem tree structure of menus for this workbench.
virtual ToolBarItem * setupToolBars () const =0
Returns a ToolBarItem tree structure of toolbars for this workbench.
Additional Inherited Members
Static Public Member Functions inherited from Gui::Workbench
static void addPermanentMenuItem (const std::string &cmd, const std::string &after)
Add a permanent menu item cmd after an existing command after.
static void createLinkMenu (MenuItem *)
static void removePermanentMenuItem (const std::string &cmd)
Removes the command cmd from the permanent menu items.
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The PythonWorkbench class allows the manipulation of the workbench from Python.
Therefore PythonWorkbenchPy provides the required Python interface.
Author
Werner Mayer
Constructor & Destructor Documentation
PythonWorkbench()
PythonWorkbench::PythonWorkbench ()
References Gui::StdWorkbench::setupMenuBar(), and Gui::StdWorkbench::setupToolBars().
~PythonWorkbench()
PythonWorkbench::~PythonWorkbench ()
Member Function Documentation
createMainWindowPopupMenu()
void PythonWorkbench::createMainWindowPopupMenu (MenuItem *) const virtual
Sets up the contextmenu for the main window for this workbench.
The default implementation does nothing.
Reimplemented from Gui::Workbench.
References Gui::StdWorkbench::createMainWindowPopupMenu().
setupCommandBars()
ToolBarItem * PythonWorkbench::setupCommandBars () const protected virtual
Returns a ToolBarItem tree structure of command bars for this workbench.
Reimplemented from Gui::PythonBaseWorkbench.
References Gui::ToolBarItem::copy().
setupContextMenu()
void PythonWorkbench::setupContextMenu (const char * recipient, MenuItem * item) const virtual
Defines the standard context menu.
Reimplemented from Gui::PythonBaseWorkbench.
References Gui::StdWorkbench::setupContextMenu(), and Gui::PythonBaseWorkbench::setupContextMenu().
setupDockWindows()
DockWindowItems * PythonWorkbench::setupDockWindows () const protected virtual
Returns a DockWindowItems structure of dock windows this workbench.
Reimplemented from Gui::PythonBaseWorkbench.
References Gui::StdWorkbench::setupDockWindows().
setupMenuBar()
MenuItem * PythonWorkbench::setupMenuBar () const protected virtual
Returns a MenuItem tree structure of menus for this workbench.
Reimplemented from Gui::PythonBaseWorkbench.
References Gui::MenuItem::copy().
setupToolBars()
ToolBarItem * PythonWorkbench::setupToolBars () const protected virtual
Returns a ToolBarItem tree structure of toolbars for this workbench.
Reimplemented from Gui::PythonBaseWorkbench.
References Gui::ToolBarItem::copy().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/Workbench.h
FreeCAD/src/Gui/Workbench.cpp