FreeCAD: TechDrawGui::DlgTemplateField Class Reference
TechDrawGui::DlgTemplateField Class Reference
#include <DlgTemplateField.h>
Public Slots
void accept ()
void reject ()
Public Member Functions
DlgTemplateField (QWidget *parent=nullptr)
QString getFieldContent ()
void setFieldContent (std::string content)
void setFieldName (std::string name)
virtual ~DlgTemplateField ()=default
Protected Member Functions
void changeEvent (QEvent *e)
Constructor & Destructor Documentation
DlgTemplateField()
DlgTemplateField::DlgTemplateField (QWidget * parent = nullptr)
~DlgTemplateField()
virtual TechDrawGui::DlgTemplateField::~DlgTemplateField () virtual default
Member Function Documentation
accept
void DlgTemplateField::accept (void) slot
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void DlgTemplateField::changeEvent (QEvent * e) protected
getFieldContent()
QString DlgTemplateField::getFieldContent ()
Referenced by TechDrawGui::TemplateTextField::mouseReleaseEvent().
reject
void DlgTemplateField::reject (void) slot
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
setFieldContent()
void DlgTemplateField::setFieldContent (std::string content)
Referenced by TechDrawGui::TemplateTextField::mouseReleaseEvent().
setFieldName()
void DlgTemplateField::setFieldName (std::string name)
Referenced by TechDrawGui::TemplateTextField::mouseReleaseEvent().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/DlgTemplateField.h
FreeCAD/src/Mod/TechDraw/Gui/DlgTemplateField.cpp