FreeCAD: BuildRegularGeoms Namespace Reference
BuildRegularGeoms Namespace Reference
Functions
def Cone (radius1, radius2, len, closed, edgelen, count)
def Cube (lenX, lenY, lenZ)
def Cylinder (radius, len, closed, edgelen, count)
def Ellipsoid (lenX, lenY, count)
def FineCube (lenX, lenY, lenZ, edgelen)
def main ()
def RotationBody (polyline, count)
def Sphere (radius, count)
def Toroid (radius1, radius2, count)
Function Documentation
Cone()
def BuildRegularGeoms.Cone (radius1, radius2, len, closed, edgelen, count)
References RotationBody().
Referenced by Cylinder().
Cube()
def BuildRegularGeoms.Cube (lenX, lenY, lenZ)
Cylinder()
def BuildRegularGeoms.Cylinder (radius, len, closed, edgelen, count)
References Cone().
Ellipsoid()
def BuildRegularGeoms.Ellipsoid (lenX, lenY, count)
References RotationBody().
Referenced by Sphere().
FineCube()
def BuildRegularGeoms.FineCube (lenX, lenY, lenZ, edgelen)
main()
def BuildRegularGeoms.main ()
References main().
Referenced by main().
RotationBody()
def BuildRegularGeoms.RotationBody (polyline, count)
Build a rotation body from a given (closed) polyline, rotation axis is the X-Axis.
Parameter: polyline: list of tuple of 2 floats (2d vector)
Referenced by Cone(), Ellipsoid(), and Toroid().
Sphere()
def BuildRegularGeoms.Sphere (radius, count)
Creates a sphere with a given radius.
bla bla bla
References Ellipsoid().
Toroid()
def BuildRegularGeoms.Toroid (radius1, radius2, count)
References RotationBody().