FreeCAD: FemGui::DlgSettingsFemCcxImp Class Reference
FemGui::DlgSettingsFemCcxImp Class Reference
#include <DlgSettingsFemCcxImp.h>
Public Member Functions
DlgSettingsFemCcxImp (QWidget *parent=nullptr)
~DlgSettingsFemCcxImp ()
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void loadSettings ()
void saveSettings ()
virtual void changeEvent (QEvent *e)=0
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Constructor & Destructor Documentation
DlgSettingsFemCcxImp()
DlgSettingsFemCcxImp::DlgSettingsFemCcxImp (QWidget * parent = nullptr)
~DlgSettingsFemCcxImp()
DlgSettingsFemCcxImp::~DlgSettingsFemCcxImp ()
Member Function Documentation
changeEvent()
void DlgSettingsFemCcxImp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
loadSettings()
void DlgSettingsFemCcxImp::loadSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), ParameterGrp::GetInt(), and App::Application::GetParameterGroupByPath().
saveSettings()
void DlgSettingsFemCcxImp::saveSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetInt().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/DlgSettingsFemCcxImp.h
FreeCAD/src/Mod/Fem/Gui/DlgSettingsFemCcxImp.cpp