FreeCAD: Gui::SoFCColorBarBase Class Reference
Gui::SoFCColorBarBase Class Reference abstract
The abstract color bar base class to get most important information on how to convert a scalar to an RGB color.
#include <SoFCColorBar.h>
Public Member Functions
virtual bool customize ()=0
Opens a dialog to customize the current settings of the color bar.
virtual App::Color getColor (float fVal) const =0
Returns the associated color to the value fVal.
virtual const char * getColorBarName () const =0
Returns the name of the color bar.
virtual float getMaxValue (void) const =0
Returns the current maximum of the parameter range.
virtual float getMinValue (void) const =0
Returns the current minimum of the parameter range.
virtual void GLRenderBelowPath (SoGLRenderAction *action)
virtual bool isVisible (float fVal) const =0
Returns always true if the color bar is in mode to show colors to arbitrary values of fVal, otherwise true is returned if fVal is within the specified parameter range, if not false is returned.
virtual void setOutsideGrayed (bool bVal)=0
Sets whether values outside the range should be in gray,.
virtual void setRange (float fMin, float fMax, int prec=3)=0
Sets the range of the colorbar from the maximum fMax to the minimum fMin.
Static Public Member Functions
static void finish (void)
static void initClass (void)
Protected Member Functions
virtual void setViewportSize (const SbVec2s &size)=0
Sets the current viewer size to recalculate the new position.
SoFCColorBarBase (void)
virtual ~SoFCColorBarBase ()
Protected Member Functions inherited from App::ValueFloatToRGB
ValueFloatToRGB (void)
virtual ~ValueFloatToRGB ()
Detailed Description
The abstract color bar base class to get most important information on how to convert a scalar to an RGB color.
Author
Werner Mayer
Constructor & Destructor Documentation
SoFCColorBarBase()
SoFCColorBarBase::SoFCColorBarBase (void) protected
Constructor.
~SoFCColorBarBase()
SoFCColorBarBase::~SoFCColorBarBase () protected virtual
Destructor.
Member Function Documentation
customize()
virtual bool Gui::SoFCColorBarBase::customize () pure virtual
Opens a dialog to customize the current settings of the color bar.
Returns true if the settings have been changed, false otherwise.
This method must be implemented in subclasses.
Implemented in Gui::SoFCColorLegend, Gui::SoFCColorGradient, and Gui::SoFCColorBar.
Referenced by Gui::SoFCColorBar::customize().
finish()
void SoFCColorBarBase::finish (void) static
Referenced by drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), draftguitools.gui_shapestrings.ShapeString::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_split.Split::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_edit.Edit::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_selectplane.Draft_SelectPlane::checkSelection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_labels.Label::create(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_shapestrings.ShapeString::createObject(), draftguitools.gui_texts.Text::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::escape(), Gui::SoFCDB::finish(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_fillets.Fillet::numericRadius(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickAlign(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickAuto(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickCenter(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickFront(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickMove(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickPrevious(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickSide(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickTop(), draftguitools.gui_array_simple.Array::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
getColor()
virtual App::Color Gui::SoFCColorBarBase::getColor (float fVal) const pure virtual
Returns the associated color to the value fVal.
This method must be implemented in subclasses.
Implements App::ValueFloatToRGB.
Implemented in Gui::SoFCColorLegend, Gui::SoFCColorGradient, and Gui::SoFCColorBar.
Referenced by Gui::SoFCColorBar::getColor().
getColorBarName()
virtual const char* Gui::SoFCColorBarBase::getColorBarName () const pure virtual
Returns the name of the color bar.
This method must be implemented in subclasses.
Implemented in Gui::SoFCColorLegend, Gui::SoFCColorGradient, and Gui::SoFCColorBar.
getMaxValue()
virtual float Gui::SoFCColorBarBase::getMaxValue (void) const pure virtual
Returns the current maximum of the parameter range.
This method must be implemented in subclasses.
Implemented in Gui::SoFCColorLegend, Gui::SoFCColorGradient, and Gui::SoFCColorBar.
Referenced by Gui::SoFCColorBar::getMaxValue().
getMinValue()
virtual float Gui::SoFCColorBarBase::getMinValue (void) const pure virtual
Returns the current minimum of the parameter range.
This method must be implemented in subclasses.
Implemented in Gui::SoFCColorLegend, Gui::SoFCColorGradient, and Gui::SoFCColorBar.
Referenced by Gui::SoFCColorBar::getMinValue().
GLRenderBelowPath()
void SoFCColorBarBase::GLRenderBelowPath (SoGLRenderAction * action) virtual
References setViewportSize().
initClass()
void SoFCColorBarBase::initClass (void) static
Referenced by Gui::SoFCDB::init().
isVisible()
virtual bool Gui::SoFCColorBarBase::isVisible (float fVal) const pure virtual
Returns always true if the color bar is in mode to show colors to arbitrary values of fVal, otherwise true is returned if fVal is within the specified parameter range, if not false is returned.
This method must be implemented in subclasses.
Implemented in Gui::SoFCColorLegend, Gui::SoFCColorGradient, and Gui::SoFCColorBar.
Referenced by Gui::SoFCColorBar::isVisible(), and ArchVRM.Renderer::removeHidden().
setOutsideGrayed()
virtual void Gui::SoFCColorBarBase::setOutsideGrayed (bool bVal) pure virtual
Sets whether values outside the range should be in gray,.
This method must be implemented in subclasses.
Implemented in Gui::SoFCColorLegend, Gui::SoFCColorGradient, and Gui::SoFCColorBar.
setRange()
virtual void Gui::SoFCColorBarBase::setRange (float fMin, float fMax, int prec = 3) pure virtual
Sets the range of the colorbar from the maximum fMax to the minimum fMin.
prec indicates the post decimal positions, prec should be in between 0 and 6.
This method must be implemented in subclasses.
Implemented in Gui::SoFCColorLegend, Gui::SoFCColorGradient, and Gui::SoFCColorBar.
setViewportSize()
virtual void Gui::SoFCColorBarBase::setViewportSize (const SbVec2s & size) protected pure virtual
Sets the current viewer size to recalculate the new position.
This method must be implemented in subclasses.
Implemented in Gui::SoFCColorLegend, Gui::SoFCColorGradient, and Gui::SoFCColorBar.
Referenced by GLRenderBelowPath().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SoFCColorBar.h
Sources/FreeCAD/src/Gui/SoFCColorBar.cpp