FreeCAD: Gui::PropertyListEditor Class Reference
Gui::PropertyListEditor Class Reference
#include <Widgets.h>
Public Member Functions
void lineNumberAreaPaintEvent (QPaintEvent *event)
int lineNumberAreaWidth ()
PropertyListEditor (QWidget *parent=0)
Protected Member Functions
void resizeEvent (QResizeEvent *event)
Constructor & Destructor Documentation
PropertyListEditor()
PropertyListEditor::PropertyListEditor (QWidget * parent = 0)
References draftgeoutils.intersections::connect().
Member Function Documentation
lineNumberAreaPaintEvent()
void PropertyListEditor::lineNumberAreaPaintEvent (QPaintEvent * event)
lineNumberAreaWidth()
int PropertyListEditor::lineNumberAreaWidth ()
References Gui::QtTools::horizontalAdvance().
Referenced by resizeEvent().
resizeEvent()
void PropertyListEditor::resizeEvent (QResizeEvent * event) protected
References lineNumberAreaWidth().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Widgets.h
Sources/FreeCAD/src/Gui/Widgets.cpp