FreeCAD: MED::TWrapper Struct Reference
MED::TWrapper Struct Reference abstract
Define a base class that wraps the MED API.
#include <MED_Wrapper.hxx>
Public Types
typedef boost::mutex TMutex
Public Member Functions
virtual PBallInfo CrBallInfo (const PMeshInfo &theMeshInfo, const PBallInfo &theInfo)
A copy-constructor for the MEDWrapped MED Balls representation.
virtual PBallInfo CrBallInfo (const PMeshInfo &theMeshInfo, const TIntVector &theNodes, TFloatVector &theDiameters, const TIntVector &theFamilyNums=TIntVector(), const TIntVector &theElemNums=TIntVector())
Creates a MEDWrapper MED Balls representation.
virtual PBallInfo CrBallInfo (const PMeshInfo &theMeshInfo, TInt theNbBalls, EBooleen theIsElemNum=eVRAI)
Creates a MEDWrapper MED Balls representation.
virtual PCellInfo CrCellInfo (const PMeshInfo &theMeshInfo, const PCellInfo &theInfo)=0
A copy-constructor for the MEDWrapper MED Cells representation.
virtual PCellInfo CrCellInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, const TIntVector &theConnectivities, EConnectivite theConnMode=eNOD, const TIntVector &theFamilyNums=TIntVector(), const TIntVector &theElemNums=TIntVector(), const TStringVector &theElemNames=TStringVector(), EModeSwitch theMode=eFULL_INTERLACE)=0
Creates a MEDWrapper MED Cells representation.
virtual PCellInfo CrCellInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TInt theNbElem, EConnectivite theConnMode=eNOD, EBooleen theIsElemNum=eVRAI, EBooleen theIsElemNames=eVRAI, EModeSwitch theMode=eFULL_INTERLACE)=0
Creates a MEDWrapper MED Cells representation.
virtual PElemInfo CrElemInfo (const PMeshInfo &theMeshInfo, TInt theNbElem, const TIntVector &theFamNum, const TIntVector &aElemNum, const TStringVector &aElemNames)
Creates a MEDWrapper MED Nodes representation.
virtual PElemInfo CrElemInfo (const PMeshInfo &theMeshInfo, TInt theNbElem, EBooleen theIsElemNum=eVRAI, EBooleen theIsElemNames=eVRAI)
Creates a MEDWrapper MED Nodes representation.
virtual PFamilyInfo CrFamilyInfo (const PMeshInfo &theMeshInfo, const PFamilyInfo &theInfo)=0
A copy-constructor for the MEDWrapper MED Family representation.
virtual PFamilyInfo CrFamilyInfo (const PMeshInfo &theMeshInfo, const std::string &theValue, TInt theId, const TStringSet &theGroupNames, const TStringVector &theAttrDescs=TStringVector(), const TIntVector &theAttrIds=TIntVector(), const TIntVector &theAttrVals=TIntVector())=0
Creates a MEDWrapper MED Family representation.
virtual PFamilyInfo CrFamilyInfo (const PMeshInfo &theMeshInfo, TInt theNbGroup=0, TInt theNbAttr=0, TInt theId=0, const std::string &theValue="")=0
Creates a MEDWrapper MED Family representation.
virtual PFieldInfo CrFieldInfo (const PMeshInfo &theMeshInfo, const PFieldInfo &theInfo)=0
A copy-constructor for the MEDWrapper MED FIELD representation.
virtual PFieldInfo CrFieldInfo (const PMeshInfo &theMeshInfo, TInt theNbComp=0, ETypeChamp theType=eFLOAT64, const std::string &theValue="", EBooleen theIsLocal=eVRAI, TInt theNbRef=1)=0
Creates a MEDWrapper MED FIELD representation.
virtual PGaussInfo CrGaussInfo (const TGaussInfo::TInfo &theInfo, EModeSwitch theMode=eFULL_INTERLACE)=0
Creates a MEDWrapper MED GAUSS representation.
virtual PGrilleInfo CrGrilleInfo (const PMeshInfo &theMeshInfo)
virtual PGrilleInfo CrGrilleInfo (const PMeshInfo &theMeshInfo, const EGrilleType &type)
virtual PGrilleInfo CrGrilleInfo (const PMeshInfo &theMeshInfo, const EGrilleType &type, const MED::TIntVector &nbNodeVec)
virtual PGrilleInfo CrGrilleInfo (const PMeshInfo &theMeshInfo, const EGrilleType &type, const TInt &nbNodes)
virtual PGrilleInfo CrGrilleInfo (const PMeshInfo &theMeshInfo, const PGrilleInfo &theGrilleInfo)
virtual PMeshInfo CrMeshInfo (const PMeshInfo &theInfo)=0
A copy-constructor for the MEDWrapper MED Mesh representation.
virtual PMeshInfo CrMeshInfo (TInt theDim=0, TInt theSpaceDim=0, const std::string &theValue="", EMaillage theType=eNON_STRUCTURE, const std::string &theDesc="")=0
Creates a MEDWrapper MED Mesh representation.
virtual PNodeInfo CrNodeInfo (const PMeshInfo &theMeshInfo, const PNodeInfo &theInfo)=0
A copy-constructor for the MEDWrapper MED Nodes representation.
virtual PNodeInfo CrNodeInfo (const PMeshInfo &theMeshInfo, const TFloatVector &theNodeCoords, EModeSwitch theMode=eFULL_INTERLACE, ERepere theSystem=eCART, const TStringVector &theCoordNames=TStringVector(), const TStringVector &theCoordUnits=TStringVector(), const TIntVector &theFamilyNums=TIntVector(), const TIntVector &theElemNums=TIntVector(), const TStringVector &theElemNames=TStringVector())=0
Creates a MEDWrapper MED Nodes representation.
virtual PNodeInfo CrNodeInfo (const PMeshInfo &theMeshInfo, TInt theNbElem, EModeSwitch theMode=eFULL_INTERLACE, ERepere theSystem=eCART, EBooleen theIsElemNum=eVRAI, EBooleen theIsElemNames=eVRAI)=0
Creates a MEDWrapper MED Nodes representation.
virtual PPolyedreInfo CrPolyedreInfo (const PMeshInfo &theMeshInfo, const PPolyedreInfo &theInfo)
A copy-constructor for the MEDWrapper MED Polyedres representation.
virtual PPolyedreInfo CrPolyedreInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, const TIntVector &theIndexes, const TIntVector &theFaces, const TIntVector &theConnectivities, EConnectivite theConnMode=eNOD, const TIntVector &theFamilyNums=TIntVector(), const TIntVector &theElemNums=TIntVector(), const TStringVector &theElemNames=TStringVector())
Creates a MEDWrapper MED Polyedres representation.
virtual PPolyedreInfo CrPolyedreInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TInt theNbElem, TInt theNbFaces, TInt theConnSize, EConnectivite theConnMode=eNOD, EBooleen theIsElemNum=eVRAI, EBooleen theIsElemNames=eVRAI)
virtual PPolygoneInfo CrPolygoneInfo (const PMeshInfo &theMeshInfo, const PPolygoneInfo &theInfo)
A copy-constructor for the MEDWrapper MED Polygones representation.
virtual PPolygoneInfo CrPolygoneInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, const TIntVector &theIndexes, const TIntVector &theConnectivities, EConnectivite theConnMode=eNOD, const TIntVector &theFamilyNums=TIntVector(), const TIntVector &theElemNums=TIntVector(), const TStringVector &theElemNames=TStringVector())
Creates a MEDWrapper MED Polygones representation.
virtual PPolygoneInfo CrPolygoneInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TInt theNbElem, TInt theConnSize, EConnectivite theConnMode=eNOD, EBooleen theIsElemNum=eVRAI, EBooleen theIsElemNames=eVRAI)
Creates a MEDWrapper MED Polygones representation.
virtual PProfileInfo CrProfileInfo (const TProfileInfo::TInfo &theInfo, EModeProfil theMode=eCOMPACT)=0
Creates a MEDWrapper MED PROFILE representation.
virtual PTimeStampInfo CrTimeStampInfo (const PFieldInfo &theFieldInfo, const PTimeStampInfo &theInfo)=0
A copy-constructor for the MEDWrapper MED TIMESTAMP representation.
virtual PTimeStampInfo CrTimeStampInfo (const PFieldInfo &theFieldInfo, EEntiteMaillage theEntity, const TGeom2Size &theGeom2Size, const TGeom2NbGauss &theGeom2NbGauss=TGeom2NbGauss(), TInt theNumDt=0, TInt theNumOrd=0, TFloat theDt=0, const std::string &theUnitDt="", const TGeom2Gauss &theGeom2Gauss=TGeom2Gauss())=0
Creates a MEDWrapper MED TIMESTAMP representation.
virtual PTimeStampVal CrTimeStampVal (const PTimeStampInfo &theTimeStampInfo, const PTimeStampVal &theInfo)
A copy-constructor for the values for MEDWrapper MED TIEMSTAMP representation.
virtual PTimeStampVal CrTimeStampVal (const PTimeStampInfo &theTimeStampInfo, const TGeom2Profile &theGeom2Profile=TGeom2Profile(), EModeSwitch theMode=eFULL_INTERLACE)
Creates the values for MEDWrapper MED TIEMSTAMP representation.
virtual PTimeStampValueBase CrTimeStampValue (const PTimeStampInfo &theTimeStampInfo, const PTimeStampValueBase &theInfo)
A copy-constructor for the values for MEDWrapper MED TIEMSTAMP representation.
virtual PTimeStampValueBase CrTimeStampValue (const PTimeStampInfo &theTimeStampInfo, const PTimeStampValueBase &theInfo, ETypeChamp theTypeChamp)=0
A copy-constructor for the values for MEDWrapper MED TIEMSTAMP representation.
virtual PTimeStampValueBase CrTimeStampValue (const PTimeStampInfo &theTimeStampInfo, const TGeom2Profile &theGeom2Profile=TGeom2Profile(), EModeSwitch theMode=eFULL_INTERLACE)
Creates the values for MEDWrapper MED TIEMSTAMP representation.
virtual PTimeStampValueBase CrTimeStampValue (const PTimeStampInfo &theTimeStampInfo, ETypeChamp theTypeChamp, const TGeom2Profile &theGeom2Profile=TGeom2Profile(), EModeSwitch theMode=eFULL_INTERLACE)=0
Creates the values for MEDWrapper MED TIEMSTAMP representation.
virtual void GetBallInfo (TBallInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapped representation of MED_BALL from the MED file.
virtual void GetCellInfo (TCellInfo &theInfo, TErr *theErr=NULL)=0
Read a MEDWrapper MED Cells representation from defined MED file.
virtual TEntityInfo GetEntityInfo (const TMeshInfo &theMeshInfo, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)=0
Get TEntityInfo which contains brief information about existing cells and their destribution among MED ENTITIES.
virtual void GetFamilies (TElemInfo &theInfo, TInt theNb, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Read sequence MED Family indexes for any descendant of TElemInfo.
virtual void GetFamilyInfo (TInt theFamId, TFamilyInfo &theInfo, TErr *theErr=NULL)=0
Read a MEDWrapper MED Family representation by its number.
virtual void GetFieldInfo (TInt theFieldId, TFieldInfo &theInfo, TErr *theErr=NULL)=0
Read MEDWrapper MED FIELD representation by its order number.
virtual void GetGaussInfo (TInt theId, TGaussInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapper MED GAUSS representation by its order number from defined MED file.
virtual TGaussInfo::TInfo GetGaussPreInfo (TInt theId, TErr *theErr=NULL)
Read brief MED GAUSS information by its order number from defined MED Mesh.
virtual void GetGrilleInfo (TGrilleInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapper MED Grille representation from defined MED file.
virtual void GetGrilleType (const TMeshInfo &theMeshInfo, EGrilleType &type, TErr *theErr=NULL)
virtual void GetMeshInfo (TInt theMeshId, TMeshInfo &theInfo, TErr *theErr=NULL)=0
Read a MEDWrapper MED Mesh representation by its number.
virtual void GetNames (TElemInfo &theInfo, TInt theNb, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Read sequence of names for any descendant of TElemInfo.
virtual TInt GetNbBalls (const TMeshInfo &theMeshInfo)
Read number of balls in the Mesh.
virtual TInt GetNbCells (const TMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)=0
Read number of cells for defined MED Mesh, ENTITY and geometrical type with define mode of connectivity.
virtual TInt GetNbComp (TInt theFieldId, TErr *theErr=NULL)=0
Read number of components for the defined MED FIELD by its order number.
virtual TInt GetNbFamAttr (TInt theFamId, const TMeshInfo &theInfo, TErr *theErr=NULL)=0
Read number of attributes for defined MED Family.
virtual TInt GetNbFamGroup (TInt theFamId, const TMeshInfo &theInfo, TErr *theErr=NULL)=0
Read number of MED Groups where MED Family with the number belong to.
virtual TInt GetNbFamilies (const TMeshInfo &theMeshInfo, TErr *theErr=NULL)=0
Read number of MED Family entities in the defined MED file.
virtual TInt GetNbFields (TErr *theErr=NULL)=0
Read number of MED FIELDS in defined MED Mesh.
virtual TInt GetNbGauss (TErr *theErr=NULL)
Read number of MED GAUSS in defined MED Mesh.
virtual TInt GetNbMeshes (TErr *theErr=NULL)=0
Read number of MED Mesh entities in the defined MED file.
virtual TInt GetNbNodes (const TMeshInfo &theMeshInfo, ETable theTable, TErr *theErr=NULL)
virtual TInt GetNbNodes (const TMeshInfo &theMeshInfo, TErr *theErr=NULL)=0
Read number of nodes in defined MED Mesh.
virtual TInt GetNbPolyedres (const TMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)
Read number of MED Polyedres in defined MED Mesh.
virtual TInt GetNbPolygones (const TMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)
Read number of MED Polygones in defined MED Mesh.
virtual TInt GetNbProfiles (TErr *theErr=NULL)=0
Read number of MED PROFILES in defined MED Mesh.
virtual TInt GetNbTimeStamps (const TFieldInfo &theInfo, const TEntityInfo &theEntityInfo, EEntiteMaillage &theEntity, TGeom2Size &theGeom2Size, TErr *theErr=NULL)=0
Read number of MED TIMESTAMPS in defined MED Mesh.
virtual void GetNodeInfo (TNodeInfo &theInfo, TErr *theErr=NULL)=0
Read a MEDWrapper MED Nodes representation from defined MED file.
virtual void GetNumeration (TElemInfo &theInfo, TInt theNb, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Read sequence of numerous for any descendant of TElemInfo.
virtual PBallInfo GetPBallInfo (const PMeshInfo &theMeshInfo)
Read a MEDWrapped MED Balls representation from defined MED file.
PCellInfo GetPCellInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)
Read a MEDWrapper MED Cells representation from defined MED file.
PElemInfo GetPElemInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity=eNOEUD, EGeometrieElement theGeom=ePOINT1, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)
Read a MEDWrapper MED Element representation from defined MED file.
PFamilyInfo GetPFamilyInfo (const PMeshInfo &theMeshInfo, TInt theId, TErr *theErr=NULL)
Write a MEDWrapper MED Family representation by its number.
PFieldInfo GetPFieldInfo (const PMeshInfo &theMeshInfo, TInt theId, TErr *theErr=NULL)
Read a MEDWrapper MED FIELD representation from defined MED file.
PGrilleInfo GetPGrilleInfo (const PMeshInfo &theMeshInfo)
Read a MEDWrapper MED Grille representation from defined MED file.
PGrilleInfo GetPGrilleInfo (const PMeshInfo &theMeshInfo, const PGrilleInfo &theInfo)
Read a MEDWrapper MED Grille representation from defined MED file.
virtual PMeshInfo GetPMeshInfo (TInt theId, TErr *theErr=NULL)
Read a MEDWrapper MED Mesh representation by its number.
PNodeInfo GetPNodeInfo (const PMeshInfo &theMeshInfo, TErr *theErr=NULL)
Read a MEDWrapper MED Nodes representation from defined MED file.
virtual void GetPolyedreConnSize (const TMeshInfo &theMeshInfo, TInt &theNbFaces, TInt &theConnSize, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)
Read connectivity infroamtion for the MED Polyedres in defined MED Mesh.
virtual void GetPolyedreInfo (TPolyedreInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapper MED Polyedres representation from defined MED file.
virtual TInt GetPolygoneConnSize (const TMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode=eNOD, TErr *theErr=NULL)
Read connectivity infroamtion for the MED Polygones in defined MED Mesh.
virtual void GetPolygoneInfo (TPolygoneInfo &theInfo, TErr *theErr=NULL)
Read a MEDWrapper MED Polygones representation from defined MED file.
PPolyedreInfo GetPPolyedreInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode=eNOD)
Read a MEDWrapper MED Polyedres representation from defined MED file.
PPolygoneInfo GetPPolygoneInfo (const PMeshInfo &theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode=eNOD)
Read a MEDWrapper MED Polygones representation from defined MED file.
PProfileInfo GetPProfileInfo (TInt theId, EModeProfil theMode=eCOMPACT, TErr *theErr=NULL)
Read a MEDWrapper MED PROFILE representation by its order number from defined MED file.
virtual void GetProfileInfo (TInt theId, TProfileInfo &theInfo, TErr *theErr=NULL)=0
Read a MEDWrapper MED PROFILE representation by its order number from defined MED file.
virtual TProfileInfo::TInfo GetProfilePreInfo (TInt theId, TErr *theErr=NULL)=0
Read brief MED PROFILE information by its order number from defined MED Mesh.
PTimeStampInfo GetPTimeStampInfo (const PFieldInfo &theFieldInfo, EEntiteMaillage theEntity, const TGeom2Size &theGeom2Size, TInt theId, TErr *theErr=NULL)
Read MEDWrapper MED TIMESTAMP representation by its order number.
PTimeStampVal GetPTimeStampVal (const PTimeStampInfo &theTimeStampInfo, const TMKey2Profile &theMKey2Profile, const TKey2Gauss &theKey2Gauss, TErr *theErr=NULL)
Read the values for MEDWrapper MED TIEMSTAMP from defined MED file.
PTimeStampValueBase GetPTimeStampValue (const PTimeStampInfo &theTimeStampInfo, const TMKey2Profile &theMKey2Profile, const TKey2Gauss &theKey2Gauss, TErr *theErr=NULL)
Read the values for MEDWrapper MED TIEMSTAMP from defined MED file.
virtual void GetTimeStampInfo (TInt theTimeStampId, TTimeStampInfo &theInfo, TErr *theErr=NULL)=0
Read MEDWrapper MED TIMESTAMP representation by its order number.
virtual void GetTimeStampVal (const PTimeStampVal &theVal, const TMKey2Profile &theMKey2Profile, const TKey2Gauss &theKey2Gauss, TErr *theErr=NULL)
Read the values for MEDWrapper MED TIEMSTAMP from defined MED file.
virtual void GetTimeStampValue (const PTimeStampValueBase &theTimeStampValue, const TMKey2Profile &theMKey2Profile, const TKey2Gauss &theKey2Gauss, TErr *theErr=NULL)=0
Read the values for MEDWrapper MED TIEMSTAMP from defined MED file.
virtual EVersion GetVersion ()=0
Gets version of the MED library used for the MED file.
virtual void SetBallInfo (const TBallInfo &theInfo, TErr *theErr=NULL)
Write a MEDWrapped representation of MED_BALL to the MED file.
virtual void SetCellInfo (const TCellInfo &theInfo, TErr *theErr=NULL)=0
Write the MEDWrapper MED Cells representation into defined MED file.
virtual void SetFamilies (const TElemInfo &theInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Write sequence MED Family indexes for any descendant of TElemInfo.
virtual void SetFamilyInfo (const TFamilyInfo &theInfo, TErr *theErr=NULL)=0
Write a MEDWrapper MED Family representation by its number.
virtual void SetFieldInfo (const TFieldInfo &theInfo, TErr *theErr=NULL)=0
Write MEDWrapper MED FIELD representation into defined MED file.
virtual void SetGrilleInfo (const TGrilleInfo &theInfo, TErr *theErr=NULL)
Write the MEDWrapper MED Grille representation into defined MED file.
virtual void SetMeshInfo (const TMeshInfo &theInfo, TErr *theErr=NULL)=0
Write the MEDWrapper MED Mesh representation in the defined MED file.
virtual void SetNames (const TElemInfo &theInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Write sequence of names for any descendant of TElemInfo.
virtual void SetNodeInfo (const TNodeInfo &theInfo, TErr *theErr=NULL)=0
Write the MEDWrapper MED Nodes representation into defined MED file.
virtual void SetNumeration (const TElemInfo &theInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr *theErr=NULL)
Write sequence of numerous for any descendant of TElemInfo.
virtual void SetPolyedreInfo (const TPolyedreInfo &theInfo, TErr *theErr=NULL)
Write a MEDWrapper MED Polyedres representation from defined MED file.
virtual void SetPolygoneInfo (const TPolygoneInfo &theInfo, TErr *theErr=NULL)
Write a MEDWrapper MED Polygones representation from defined MED file.
virtual void SetProfileInfo (const TProfileInfo &theInfo, TErr *theErr=NULL)=0
Write a MEDWrapper MED PROFILE representation.
virtual void SetTimeStamp (const PTimeStampVal &theVal, TErr *theErr=NULL)
Write the values for MEDWrapper MED TIEMSTAMP to defined MED file.
virtual void SetTimeStampValue (const PTimeStampValueBase &theTimeStampValue, TErr *theErr=NULL)=0
Write the values for MEDWrapper MED TIEMSTAMP to defined MED file.
virtual ~TWrapper ()
Public Attributes
TMutex myMutex
This is a syncronization primitive which allow to support thread safety for the MED access.
Detailed Description
Define a base class that wraps the MED API.
Member Typedef Documentation
TMutex
typedef boost::mutex MED::TWrapper::TMutex
Constructor & Destructor Documentation
~TWrapper()
MED::TWrapper::~TWrapper () virtual
Member Function Documentation
CrBallInfo() [1/3]
virtual PBallInfo MED::TWrapper::CrBallInfo (const PMeshInfo & theMeshInfo, const PBallInfo & theInfo) virtual
A copy-constructor for the MEDWrapped MED Balls representation.
Reimplemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrBallInfo() [2/3]
virtual PBallInfo MED::TWrapper::CrBallInfo (const PMeshInfo & theMeshInfo, const TIntVector & theNodes, TFloatVector & theDiameters, const TIntVector & theFamilyNums = TIntVector(), const TIntVector & theElemNums = TIntVector()) virtual
Creates a MEDWrapper MED Balls representation.
This feature is supported since version 3.0
Reimplemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrBallInfo() [3/3]
virtual PBallInfo MED::TWrapper::CrBallInfo (const PMeshInfo & theMeshInfo, TInt theNbBalls, EBooleen theIsElemNum = eVRAI) virtual
Creates a MEDWrapper MED Balls representation.
This feature is supported since version 3.0
Reimplemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrCellInfo() [1/3]
virtual PCellInfo MED::TWrapper::CrCellInfo (const PMeshInfo & theMeshInfo, const PCellInfo & theInfo) pure virtual
A copy-constructor for the MEDWrapper MED Cells representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrCellInfo() [2/3]
virtual PCellInfo MED::TWrapper::CrCellInfo (const PMeshInfo & theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, const TIntVector & theConnectivities, EConnectivite theConnMode = eNOD, const TIntVector & theFamilyNums = TIntVector(), const TIntVector & theElemNums = TIntVector(), const TStringVector & theElemNames = TStringVector(), EModeSwitch theMode = eFULL_INTERLACE) pure virtual
Creates a MEDWrapper MED Cells representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrCellInfo() [3/3]
virtual PCellInfo MED::TWrapper::CrCellInfo (const PMeshInfo & theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TInt theNbElem, EConnectivite theConnMode = eNOD, EBooleen theIsElemNum = eVRAI, EBooleen theIsElemNames = eVRAI, EModeSwitch theMode = eFULL_INTERLACE) pure virtual
Creates a MEDWrapper MED Cells representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrElemInfo() [1/2]
virtual PElemInfo MED::TWrapper::CrElemInfo (const PMeshInfo & theMeshInfo, TInt theNbElem, const TIntVector & theFamNum, const TIntVector & aElemNum, const TStringVector & aElemNames) virtual
Creates a MEDWrapper MED Nodes representation.
Reimplemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrElemInfo() [2/2]
virtual PElemInfo MED::TWrapper::CrElemInfo (const PMeshInfo & theMeshInfo, TInt theNbElem, EBooleen theIsElemNum = eVRAI, EBooleen theIsElemNames = eVRAI) virtual
Creates a MEDWrapper MED Nodes representation.
Reimplemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrFamilyInfo() [1/3]
virtual PFamilyInfo MED::TWrapper::CrFamilyInfo (const PMeshInfo & theMeshInfo, const PFamilyInfo & theInfo) pure virtual
A copy-constructor for the MEDWrapper MED Family representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrFamilyInfo() [2/3]
virtual PFamilyInfo MED::TWrapper::CrFamilyInfo (const PMeshInfo & theMeshInfo, const std::string & theValue, TInt theId, const TStringSet & theGroupNames, const TStringVector & theAttrDescs = TStringVector(), const TIntVector & theAttrIds = TIntVector(), const TIntVector & theAttrVals = TIntVector()) pure virtual
Creates a MEDWrapper MED Family representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrFamilyInfo() [3/3]
virtual PFamilyInfo MED::TWrapper::CrFamilyInfo (const PMeshInfo & theMeshInfo, TInt theNbGroup = 0, TInt theNbAttr = 0, TInt theId = 0, const std::string & theValue = "") pure virtual
Creates a MEDWrapper MED Family representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrFieldInfo() [1/2]
virtual PFieldInfo MED::TWrapper::CrFieldInfo (const PMeshInfo & theMeshInfo, const PFieldInfo & theInfo) pure virtual
A copy-constructor for the MEDWrapper MED FIELD representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrFieldInfo() [2/2]
virtual PFieldInfo MED::TWrapper::CrFieldInfo (const PMeshInfo & theMeshInfo, TInt theNbComp = 0, ETypeChamp theType = eFLOAT64, const std::string & theValue = "", EBooleen theIsLocal = eVRAI, TInt theNbRef = 1) pure virtual
Creates a MEDWrapper MED FIELD representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrGaussInfo()
virtual PGaussInfo MED::TWrapper::CrGaussInfo (const TGaussInfo::TInfo & theInfo, EModeSwitch theMode = eFULL_INTERLACE) pure virtual
Creates a MEDWrapper MED GAUSS representation.
This feature is support only for version of 2.2 and higher
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrGrilleInfo() [1/5]
virtual PGrilleInfo MED::TWrapper::CrGrilleInfo (const PMeshInfo & theMeshInfo) virtual
This feature is support only for version of 2.2 and higher
CrGrilleInfo() [2/5]
virtual PGrilleInfo MED::TWrapper::CrGrilleInfo (const PMeshInfo & theMeshInfo, const EGrilleType & type) virtual
This feature is support only for version of 2.2 and higher
Reimplemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrGrilleInfo() [3/5]
virtual PGrilleInfo MED::TWrapper::CrGrilleInfo (const PMeshInfo & theMeshInfo, const EGrilleType & type, const MED::TIntVector & nbNodeVec) virtual
This feature is support only for version of 2.2 and higher
Reimplemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrGrilleInfo() [4/5]
virtual PGrilleInfo MED::TWrapper::CrGrilleInfo (const PMeshInfo & theMeshInfo, const EGrilleType & type, const TInt & nbNodes) virtual
This feature is support only for version of 2.2 and higher
Reimplemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrGrilleInfo() [5/5]
virtual PGrilleInfo MED::TWrapper::CrGrilleInfo (const PMeshInfo & theMeshInfo, const PGrilleInfo & theGrilleInfo) virtual
This feature is support only for version of 2.2 and higher
Reimplemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrMeshInfo() [1/2]
virtual PMeshInfo MED::TWrapper::CrMeshInfo (const PMeshInfo & theInfo) pure virtual
A copy-constructor for the MEDWrapper MED Mesh representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrMeshInfo() [2/2]
virtual PMeshInfo MED::TWrapper::CrMeshInfo (TInt theDim = 0, TInt theSpaceDim = 0, const std::string & theValue = "", EMaillage theType = eNON_STRUCTURE, const std::string & theDesc = "") pure virtual
Creates a MEDWrapper MED Mesh representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrNodeInfo() [1/3]
virtual PNodeInfo MED::TWrapper::CrNodeInfo (const PMeshInfo & theMeshInfo, const PNodeInfo & theInfo) pure virtual
A copy-constructor for the MEDWrapper MED Nodes representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrNodeInfo() [2/3]
virtual PNodeInfo MED::TWrapper::CrNodeInfo (const PMeshInfo & theMeshInfo, const TFloatVector & theNodeCoords, EModeSwitch theMode = eFULL_INTERLACE, ERepere theSystem = eCART, const TStringVector & theCoordNames = TStringVector(), const TStringVector & theCoordUnits = TStringVector(), const TIntVector & theFamilyNums = TIntVector(), const TIntVector & theElemNums = TIntVector(), const TStringVector & theElemNames = TStringVector()) pure virtual
Creates a MEDWrapper MED Nodes representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrNodeInfo() [3/3]
virtual PNodeInfo MED::TWrapper::CrNodeInfo (const PMeshInfo & theMeshInfo, TInt theNbElem, EModeSwitch theMode = eFULL_INTERLACE, ERepere theSystem = eCART, EBooleen theIsElemNum = eVRAI, EBooleen theIsElemNames = eVRAI) pure virtual
Creates a MEDWrapper MED Nodes representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrPolyedreInfo() [1/3]
virtual PPolyedreInfo MED::TWrapper::CrPolyedreInfo (const PMeshInfo & theMeshInfo, const PPolyedreInfo & theInfo) virtual
A copy-constructor for the MEDWrapper MED Polyedres representation.
Reimplemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrPolyedreInfo() [2/3]
virtual PPolyedreInfo MED::TWrapper::CrPolyedreInfo (const PMeshInfo & theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, const TIntVector & theIndexes, const TIntVector & theFaces, const TIntVector & theConnectivities, EConnectivite theConnMode = eNOD, const TIntVector & theFamilyNums = TIntVector(), const TIntVector & theElemNums = TIntVector(), const TStringVector & theElemNames = TStringVector()) virtual
Creates a MEDWrapper MED Polyedres representation.
This feature is support only for version of 2.2 and higher
Reimplemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrPolyedreInfo() [3/3]
virtual PPolyedreInfo MED::TWrapper::CrPolyedreInfo (const PMeshInfo & theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TInt theNbElem, TInt theNbFaces, TInt theConnSize, EConnectivite theConnMode = eNOD, EBooleen theIsElemNum = eVRAI, EBooleen theIsElemNames = eVRAI) virtual
Reimplemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrPolygoneInfo() [1/3]
virtual PPolygoneInfo MED::TWrapper::CrPolygoneInfo (const PMeshInfo & theMeshInfo, const PPolygoneInfo & theInfo) virtual
A copy-constructor for the MEDWrapper MED Polygones representation.
Reimplemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrPolygoneInfo() [2/3]
virtual PPolygoneInfo MED::TWrapper::CrPolygoneInfo (const PMeshInfo & theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, const TIntVector & theIndexes, const TIntVector & theConnectivities, EConnectivite theConnMode = eNOD, const TIntVector & theFamilyNums = TIntVector(), const TIntVector & theElemNums = TIntVector(), const TStringVector & theElemNames = TStringVector()) virtual
Creates a MEDWrapper MED Polygones representation.
This feature is supported only for version of 2.2 and higher
Reimplemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrPolygoneInfo() [3/3]
virtual PPolygoneInfo MED::TWrapper::CrPolygoneInfo (const PMeshInfo & theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TInt theNbElem, TInt theConnSize, EConnectivite theConnMode = eNOD, EBooleen theIsElemNum = eVRAI, EBooleen theIsElemNames = eVRAI) virtual
Creates a MEDWrapper MED Polygones representation.
This feature is supported only for version of 2.2 and higher
Reimplemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrProfileInfo()
virtual PProfileInfo MED::TWrapper::CrProfileInfo (const TProfileInfo::TInfo & theInfo, EModeProfil theMode = eCOMPACT) pure virtual
Creates a MEDWrapper MED PROFILE representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrTimeStampInfo() [1/2]
virtual PTimeStampInfo MED::TWrapper::CrTimeStampInfo (const PFieldInfo & theFieldInfo, const PTimeStampInfo & theInfo) pure virtual
A copy-constructor for the MEDWrapper MED TIMESTAMP representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrTimeStampInfo() [2/2]
virtual PTimeStampInfo MED::TWrapper::CrTimeStampInfo (const PFieldInfo & theFieldInfo, EEntiteMaillage theEntity, const TGeom2Size & theGeom2Size, const TGeom2NbGauss & theGeom2NbGauss = TGeom2NbGauss(), TInt theNumDt = 0, TInt theNumOrd = 0, TFloat theDt = 0, const std::string & theUnitDt = "", const TGeom2Gauss & theGeom2Gauss = TGeom2Gauss()) pure virtual
Creates a MEDWrapper MED TIMESTAMP representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrTimeStampVal() [1/2]
PTimeStampVal MED::TWrapper::CrTimeStampVal (const PTimeStampInfo & theTimeStampInfo, const PTimeStampVal & theInfo) virtual
A copy-constructor for the values for MEDWrapper MED TIEMSTAMP representation.
References MED::eFLOAT64.
CrTimeStampVal() [2/2]
PTimeStampVal MED::TWrapper::CrTimeStampVal (const PTimeStampInfo & theTimeStampInfo, const TGeom2Profile & theGeom2Profile = TGeom2Profile(), EModeSwitch theMode = eFULL_INTERLACE) virtual
Creates the values for MEDWrapper MED TIEMSTAMP representation.
References MED::eFLOAT64.
CrTimeStampValue() [1/4]
PTimeStampValueBase MED::TWrapper::CrTimeStampValue (const PTimeStampInfo & theTimeStampInfo, const PTimeStampValueBase & theInfo) virtual
A copy-constructor for the values for MEDWrapper MED TIEMSTAMP representation.
CrTimeStampValue() [2/4]
virtual PTimeStampValueBase MED::TWrapper::CrTimeStampValue (const PTimeStampInfo & theTimeStampInfo, const PTimeStampValueBase & theInfo, ETypeChamp theTypeChamp) pure virtual
A copy-constructor for the values for MEDWrapper MED TIEMSTAMP representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
CrTimeStampValue() [3/4]
PTimeStampValueBase MED::TWrapper::CrTimeStampValue (const PTimeStampInfo & theTimeStampInfo, const TGeom2Profile & theGeom2Profile = TGeom2Profile(), EModeSwitch theMode = eFULL_INTERLACE) virtual
Creates the values for MEDWrapper MED TIEMSTAMP representation.
CrTimeStampValue() [4/4]
virtual PTimeStampValueBase MED::TWrapper::CrTimeStampValue (const PTimeStampInfo & theTimeStampInfo, ETypeChamp theTypeChamp, const TGeom2Profile & theGeom2Profile = TGeom2Profile(), EModeSwitch theMode = eFULL_INTERLACE) pure virtual
Creates the values for MEDWrapper MED TIEMSTAMP representation.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
GetBallInfo()
virtual void MED::TWrapper::GetBallInfo (TBallInfo & theInfo, TErr * theErr = NULL) virtual
Read a MEDWrapped representation of MED_BALL from the MED file.
This feature is supported since version 3.0
Reimplemented in MED::V2_2::TVWrapper.
GetCellInfo()
virtual void MED::TWrapper::GetCellInfo (TCellInfo & theInfo, TErr * theErr = NULL) pure virtual
Read a MEDWrapper MED Cells representation from defined MED file.
Implemented in MED::V2_2::TVWrapper.
GetEntityInfo()
virtual TEntityInfo MED::TWrapper::GetEntityInfo (const TMeshInfo & theMeshInfo, EConnectivite theConnMode = eNOD, TErr * theErr = NULL) pure virtual
Get TEntityInfo which contains brief information about existing cells and their destribution among MED ENTITIES.
Implemented in MED::V2_2::TVWrapper.
GetFamilies()
virtual void MED::TWrapper::GetFamilies (TElemInfo & theInfo, TInt theNb, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr * theErr = NULL) virtual
Read sequence MED Family indexes for any descendant of TElemInfo.
Reimplemented in MED::V2_2::TVWrapper.
GetFamilyInfo()
virtual void MED::TWrapper::GetFamilyInfo (TInt theFamId, TFamilyInfo & theInfo, TErr * theErr = NULL) pure virtual
Read a MEDWrapper MED Family representation by its number.
Implemented in MED::V2_2::TVWrapper.
GetFieldInfo()
virtual void MED::TWrapper::GetFieldInfo (TInt theFieldId, TFieldInfo & theInfo, TErr * theErr = NULL) pure virtual
Read MEDWrapper MED FIELD representation by its order number.
Implemented in MED::V2_2::TVWrapper.
GetGaussInfo()
virtual void MED::TWrapper::GetGaussInfo (TInt theId, TGaussInfo & theInfo, TErr * theErr = NULL) virtual
Read a MEDWrapper MED GAUSS representation by its order number from defined MED file.
This feature is support only for version of 2.2 and higher
Reimplemented in MED::V2_2::TVWrapper.
GetGaussPreInfo()
virtual TGaussInfo::TInfo MED::TWrapper::GetGaussPreInfo (TInt theId, TErr * theErr = NULL) virtual
Read brief MED GAUSS information by its order number from defined MED Mesh.
This feature is support only for version of 2.2 and higher
Reimplemented in MED::V2_2::TVWrapper.
References MED::ePOINT1.
GetGrilleInfo()
virtual void MED::TWrapper::GetGrilleInfo (TGrilleInfo & theInfo, TErr * theErr = NULL) virtual
Read a MEDWrapper MED Grille representation from defined MED file.
This feature is support only for version of 2.2 and higher
Reimplemented in MED::V2_2::TVWrapper.
GetGrilleType()
virtual void MED::TWrapper::GetGrilleType (const TMeshInfo & theMeshInfo, EGrilleType & type, TErr * theErr = NULL) virtual
This feature is support only for version of 2.2 and higher
Reimplemented in MED::V2_2::TVWrapper.
GetMeshInfo()
virtual void MED::TWrapper::GetMeshInfo (TInt theMeshId, TMeshInfo & theInfo, TErr * theErr = NULL) pure virtual
Read a MEDWrapper MED Mesh representation by its number.
Implemented in MED::V2_2::TVWrapper.
GetNames()
virtual void MED::TWrapper::GetNames (TElemInfo & theInfo, TInt theNb, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr * theErr = NULL) virtual
Read sequence of names for any descendant of TElemInfo.
Reimplemented in MED::V2_2::TVWrapper.
GetNbBalls()
virtual TInt MED::TWrapper::GetNbBalls (const TMeshInfo & theMeshInfo) virtual
Read number of balls in the Mesh.
This feature is supported since version 3.0
Reimplemented in MED::V2_2::TVWrapper.
GetNbCells()
virtual TInt MED::TWrapper::GetNbCells (const TMeshInfo & theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode = eNOD, TErr * theErr = NULL) pure virtual
Read number of cells for defined MED Mesh, ENTITY and geometrical type with define mode of connectivity.
Implemented in MED::V2_2::TVWrapper.
GetNbComp()
virtual TInt MED::TWrapper::GetNbComp (TInt theFieldId, TErr * theErr = NULL) pure virtual
Read number of components for the defined MED FIELD by its order number.
Implemented in MED::V2_2::TVWrapper.
GetNbFamAttr()
virtual TInt MED::TWrapper::GetNbFamAttr (TInt theFamId, const TMeshInfo & theInfo, TErr * theErr = NULL) pure virtual
Read number of attributes for defined MED Family.
Implemented in MED::V2_2::TVWrapper.
GetNbFamGroup()
virtual TInt MED::TWrapper::GetNbFamGroup (TInt theFamId, const TMeshInfo & theInfo, TErr * theErr = NULL) pure virtual
Read number of MED Groups where MED Family with the number belong to.
Implemented in MED::V2_2::TVWrapper.
GetNbFamilies()
virtual TInt MED::TWrapper::GetNbFamilies (const TMeshInfo & theMeshInfo, TErr * theErr = NULL) pure virtual
Read number of MED Family entities in the defined MED file.
Implemented in MED::V2_2::TVWrapper.
GetNbFields()
virtual TInt MED::TWrapper::GetNbFields (TErr * theErr = NULL) pure virtual
Read number of MED FIELDS in defined MED Mesh.
Implemented in MED::V2_2::TVWrapper.
GetNbGauss()
virtual TInt MED::TWrapper::GetNbGauss (TErr * theErr = NULL) virtual
Read number of MED GAUSS in defined MED Mesh.
This feature is support only for version of 2.2 and higher
Reimplemented in MED::V2_2::TVWrapper.
GetNbMeshes()
virtual TInt MED::TWrapper::GetNbMeshes (TErr * theErr = NULL) pure virtual
Read number of MED Mesh entities in the defined MED file.
Implemented in MED::V2_2::TVWrapper.
GetNbNodes() [1/2]
virtual TInt MED::TWrapper::GetNbNodes (const TMeshInfo & theMeshInfo, ETable theTable, TErr * theErr = NULL) virtual
Reimplemented in MED::V2_2::TVWrapper.
GetNbNodes() [2/2]
virtual TInt MED::TWrapper::GetNbNodes (const TMeshInfo & theMeshInfo, TErr * theErr = NULL) pure virtual
Read number of nodes in defined MED Mesh.
Implemented in MED::V2_2::TVWrapper.
GetNbPolyedres()
virtual TInt MED::TWrapper::GetNbPolyedres (const TMeshInfo & theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode = eNOD, TErr * theErr = NULL) virtual
Read number of MED Polyedres in defined MED Mesh.
This feature is support only for version of 2.2 and higher
Reimplemented in MED::V2_2::TVWrapper.
GetNbPolygones()
virtual TInt MED::TWrapper::GetNbPolygones (const TMeshInfo & theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode = eNOD, TErr * theErr = NULL) virtual
Read number of MED Polygones in defined MED Mesh.
This feature is supported only for version of 2.2 and higher
Reimplemented in MED::V2_2::TVWrapper.
GetNbProfiles()
virtual TInt MED::TWrapper::GetNbProfiles (TErr * theErr = NULL) pure virtual
Read number of MED PROFILES in defined MED Mesh.
Implemented in MED::V2_2::TVWrapper.
GetNbTimeStamps()
virtual TInt MED::TWrapper::GetNbTimeStamps (const TFieldInfo & theInfo, const TEntityInfo & theEntityInfo, EEntiteMaillage & theEntity, TGeom2Size & theGeom2Size, TErr * theErr = NULL) pure virtual
Read number of MED TIMESTAMPS in defined MED Mesh.
By the way some additional information can be obtained:
to what MED ENTITY the MED TIMESTAMP conntected to;
on what geometrical types the MED TIMESTAMP defined to.
Implemented in MED::V2_2::TVWrapper.
GetNodeInfo()
virtual void MED::TWrapper::GetNodeInfo (TNodeInfo & theInfo, TErr * theErr = NULL) pure virtual
Read a MEDWrapper MED Nodes representation from defined MED file.
Implemented in MED::V2_2::TVWrapper.
GetNumeration()
virtual void MED::TWrapper::GetNumeration (TElemInfo & theInfo, TInt theNb, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr * theErr = NULL) virtual
Read sequence of numerous for any descendant of TElemInfo.
Reimplemented in MED::V2_2::TVWrapper.
GetPBallInfo()
PBallInfo MED::TWrapper::GetPBallInfo (const PMeshInfo & theMeshInfo) virtual
Read a MEDWrapped MED Balls representation from defined MED file.
Read a MEDWrapped representation of MED Balls from the MED file.
This feature is supported since version 3.0
GetPCellInfo()
PCellInfo MED::TWrapper::GetPCellInfo (const PMeshInfo & theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode = eNOD, TErr * theErr = NULL)
Read a MEDWrapper MED Cells representation from defined MED file.
References MED::eNON_STRUCTURE.
GetPElemInfo()
PElemInfo MED::TWrapper::GetPElemInfo (const PMeshInfo & theMeshInfo, EEntiteMaillage theEntity = eNOEUD, EGeometrieElement theGeom = ePOINT1, EConnectivite theConnMode = eNOD, TErr * theErr = NULL)
Read a MEDWrapper MED Element representation from defined MED file.
References MED::eFAUX, MED::eHEXA8, MED::eNOEUD, MED::eNON_STRUCTURE, MED::ePOINT1, MED::ePOLYEDRE, MED::ePOLYGONE, MED::eQUAD4, MED::eSEG2, and MED::eVRAI.
GetPFamilyInfo()
PFamilyInfo MED::TWrapper::GetPFamilyInfo (const PMeshInfo & theMeshInfo, TInt theId, TErr * theErr = NULL)
Write a MEDWrapper MED Family representation by its number.
GetPFieldInfo()
PFieldInfo MED::TWrapper::GetPFieldInfo (const PMeshInfo & theMeshInfo, TInt theId, TErr * theErr = NULL)
Read a MEDWrapper MED FIELD representation from defined MED file.
GetPGrilleInfo() [1/2]
PGrilleInfo MED::TWrapper::GetPGrilleInfo (const PMeshInfo & theMeshInfo)
Read a MEDWrapper MED Grille representation from defined MED file.
This feature is support only for version of 2.2 and higher
References MED::eCOOR_IND1, MED::eCOOR_IND2, MED::eCOOR_IND3, MED::eGRILLE_STANDARD, MED::eSTRUCTURE, and MED::GetNbNodes().
GetPGrilleInfo() [2/2]
PGrilleInfo MED::TWrapper::GetPGrilleInfo (const PMeshInfo & theMeshInfo, const PGrilleInfo & theInfo)
Read a MEDWrapper MED Grille representation from defined MED file.
This feature is support only for version of 2.2 and higher
GetPMeshInfo()
PMeshInfo MED::TWrapper::GetPMeshInfo (TInt theId, TErr * theErr = NULL) virtual
Read a MEDWrapper MED Mesh representation by its number.
GetPNodeInfo()
PNodeInfo MED::TWrapper::GetPNodeInfo (const PMeshInfo & theMeshInfo, TErr * theErr = NULL)
Read a MEDWrapper MED Nodes representation from defined MED file.
References MED::GetNbNodes().
GetPolyedreConnSize()
virtual void MED::TWrapper::GetPolyedreConnSize (const TMeshInfo & theMeshInfo, TInt & theNbFaces, TInt & theConnSize, EConnectivite theConnMode = eNOD, TErr * theErr = NULL) virtual
Read connectivity infroamtion for the MED Polyedres in defined MED Mesh.
This feature is support only for version of 2.2 and higher
Reimplemented in MED::V2_2::TVWrapper.
GetPolyedreInfo()
virtual void MED::TWrapper::GetPolyedreInfo (TPolyedreInfo & theInfo, TErr * theErr = NULL) virtual
Read a MEDWrapper MED Polyedres representation from defined MED file.
This feature is support only for version of 2.2 and higher
Reimplemented in MED::V2_2::TVWrapper.
GetPolygoneConnSize()
virtual TInt MED::TWrapper::GetPolygoneConnSize (const TMeshInfo & theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode = eNOD, TErr * theErr = NULL) virtual
Read connectivity infroamtion for the MED Polygones in defined MED Mesh.
This feature is supported only for version of 2.2 and higher
Reimplemented in MED::V2_2::TVWrapper.
GetPolygoneInfo()
virtual void MED::TWrapper::GetPolygoneInfo (TPolygoneInfo & theInfo, TErr * theErr = NULL) virtual
Read a MEDWrapper MED Polygones representation from defined MED file.
This feature is supported only for version of 2.2 and higher
Reimplemented in MED::V2_2::TVWrapper.
GetPPolyedreInfo()
PPolyedreInfo MED::TWrapper::GetPPolyedreInfo (const PMeshInfo & theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode = eNOD)
Read a MEDWrapper MED Polyedres representation from defined MED file.
This feature is support only for version of 2.2 and higher
References MED::eNON_STRUCTURE, and MED::TCSlice< TValueType >::size().
GetPPolygoneInfo()
PPolygoneInfo MED::TWrapper::GetPPolygoneInfo (const PMeshInfo & theMeshInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, EConnectivite theConnMode = eNOD)
Read a MEDWrapper MED Polygones representation from defined MED file.
This feature is support only for version of 2.2 and higher
References MED::eNON_STRUCTURE, and MED::TCSlice< TValueType >::size().
GetPProfileInfo()
PProfileInfo MED::TWrapper::GetPProfileInfo (TInt theId, EModeProfil theMode = eCOMPACT, TErr * theErr = NULL)
Read a MEDWrapper MED PROFILE representation by its order number from defined MED file.
References MED::GetProfileInfo().
GetProfileInfo()
virtual void MED::TWrapper::GetProfileInfo (TInt theId, TProfileInfo & theInfo, TErr * theErr = NULL) pure virtual
Read a MEDWrapper MED PROFILE representation by its order number from defined MED file.
Implemented in MED::V2_2::TVWrapper.
GetProfilePreInfo()
virtual TProfileInfo::TInfo MED::TWrapper::GetProfilePreInfo (TInt theId, TErr * theErr = NULL) pure virtual
Read brief MED PROFILE information by its order number from defined MED Mesh.
Implemented in MED::V2_2::TVWrapper.
GetPTimeStampInfo()
PTimeStampInfo MED::TWrapper::GetPTimeStampInfo (const PFieldInfo & theFieldInfo, EEntiteMaillage theEntity, const TGeom2Size & theGeom2Size, TInt theId, TErr * theErr = NULL)
Read MEDWrapper MED TIMESTAMP representation by its order number.
GetPTimeStampVal()
PTimeStampVal MED::TWrapper::GetPTimeStampVal (const PTimeStampInfo & theTimeStampInfo, const TMKey2Profile & theMKey2Profile, const TKey2Gauss & theKey2Gauss, TErr * theErr = NULL)
Read the values for MEDWrapper MED TIEMSTAMP from defined MED file.
GetPTimeStampValue()
PTimeStampValueBase MED::TWrapper::GetPTimeStampValue (const PTimeStampInfo & theTimeStampInfo, const TMKey2Profile & theMKey2Profile, const TKey2Gauss & theKey2Gauss, TErr * theErr = NULL)
Read the values for MEDWrapper MED TIEMSTAMP from defined MED file.
References MED::eFLOAT64.
GetTimeStampInfo()
virtual void MED::TWrapper::GetTimeStampInfo (TInt theTimeStampId, TTimeStampInfo & theInfo, TErr * theErr = NULL) pure virtual
Read MEDWrapper MED TIMESTAMP representation by its order number.
Implemented in MED::V2_2::TVWrapper.
GetTimeStampVal()
void MED::TWrapper::GetTimeStampVal (const PTimeStampVal & theVal, const TMKey2Profile & theMKey2Profile, const TKey2Gauss & theKey2Gauss, TErr * theErr = NULL) virtual
Read the values for MEDWrapper MED TIEMSTAMP from defined MED file.
References MED::CopyTimeStampValueBase(), MED::eFLOAT64, and MED::eINT.
GetTimeStampValue()
virtual void MED::TWrapper::GetTimeStampValue (const PTimeStampValueBase & theTimeStampValue, const TMKey2Profile & theMKey2Profile, const TKey2Gauss & theKey2Gauss, TErr * theErr = NULL) pure virtual
Read the values for MEDWrapper MED TIEMSTAMP from defined MED file.
Implemented in MED::V2_2::TVWrapper.
GetVersion()
virtual EVersion MED::TWrapper::GetVersion () pure virtual
Gets version of the MED library used for the MED file.
Implemented in MED::TTWrapper< eVersion >, and MED::TTWrapper< eV2_2 >.
SetBallInfo()
virtual void MED::TWrapper::SetBallInfo (const TBallInfo & theInfo, TErr * theErr = NULL) virtual
Write a MEDWrapped representation of MED_BALL to the MED file.
This feature is supported since version 3.0
Reimplemented in MED::V2_2::TVWrapper.
SetCellInfo()
virtual void MED::TWrapper::SetCellInfo (const TCellInfo & theInfo, TErr * theErr = NULL) pure virtual
Write the MEDWrapper MED Cells representation into defined MED file.
Implemented in MED::V2_2::TVWrapper.
SetFamilies()
virtual void MED::TWrapper::SetFamilies (const TElemInfo & theInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr * theErr = NULL) virtual
Write sequence MED Family indexes for any descendant of TElemInfo.
Reimplemented in MED::V2_2::TVWrapper.
SetFamilyInfo()
virtual void MED::TWrapper::SetFamilyInfo (const TFamilyInfo & theInfo, TErr * theErr = NULL) pure virtual
Write a MEDWrapper MED Family representation by its number.
Implemented in MED::V2_2::TVWrapper.
SetFieldInfo()
virtual void MED::TWrapper::SetFieldInfo (const TFieldInfo & theInfo, TErr * theErr = NULL) pure virtual
Write MEDWrapper MED FIELD representation into defined MED file.
Implemented in MED::V2_2::TVWrapper.
SetGrilleInfo()
virtual void MED::TWrapper::SetGrilleInfo (const TGrilleInfo & theInfo, TErr * theErr = NULL) virtual
Write the MEDWrapper MED Grille representation into defined MED file.
This feature is support only for version of 2.2 and higher
Reimplemented in MED::V2_2::TVWrapper.
SetMeshInfo()
virtual void MED::TWrapper::SetMeshInfo (const TMeshInfo & theInfo, TErr * theErr = NULL) pure virtual
Write the MEDWrapper MED Mesh representation in the defined MED file.
Implemented in MED::V2_2::TVWrapper.
SetNames()
virtual void MED::TWrapper::SetNames (const TElemInfo & theInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr * theErr = NULL) virtual
Write sequence of names for any descendant of TElemInfo.
Reimplemented in MED::V2_2::TVWrapper.
SetNodeInfo()
virtual void MED::TWrapper::SetNodeInfo (const TNodeInfo & theInfo, TErr * theErr = NULL) pure virtual
Write the MEDWrapper MED Nodes representation into defined MED file.
Implemented in MED::V2_2::TVWrapper.
SetNumeration()
virtual void MED::TWrapper::SetNumeration (const TElemInfo & theInfo, EEntiteMaillage theEntity, EGeometrieElement theGeom, TErr * theErr = NULL) virtual
Write sequence of numerous for any descendant of TElemInfo.
Reimplemented in MED::V2_2::TVWrapper.
SetPolyedreInfo()
virtual void MED::TWrapper::SetPolyedreInfo (const TPolyedreInfo & theInfo, TErr * theErr = NULL) virtual
Write a MEDWrapper MED Polyedres representation from defined MED file.
This feature is support only for version of 2.2 and higher
Reimplemented in MED::V2_2::TVWrapper.
SetPolygoneInfo()
virtual void MED::TWrapper::SetPolygoneInfo (const TPolygoneInfo & theInfo, TErr * theErr = NULL) virtual
Write a MEDWrapper MED Polygones representation from defined MED file.
This feature is supported only for version of 2.2 and higher
Reimplemented in MED::V2_2::TVWrapper.
SetProfileInfo()
virtual void MED::TWrapper::SetProfileInfo (const TProfileInfo & theInfo, TErr * theErr = NULL) pure virtual
Write a MEDWrapper MED PROFILE representation.
Implemented in MED::V2_2::TVWrapper.
SetTimeStamp()
void MED::TWrapper::SetTimeStamp (const PTimeStampVal & theVal, TErr * theErr = NULL) virtual
Write the values for MEDWrapper MED TIEMSTAMP to defined MED file.
References MED::CopyTimeStampValueBase(), MED::eFLOAT64, and MED::eINT.
SetTimeStampValue()
virtual void MED::TWrapper::SetTimeStampValue (const PTimeStampValueBase & theTimeStampValue, TErr * theErr = NULL) pure virtual
Write the values for MEDWrapper MED TIEMSTAMP to defined MED file.
Implemented in MED::V2_2::TVWrapper.
Member Data Documentation
myMutex
TMutex MED::TWrapper::myMutex
This is a syncronization primitive which allow to support thread safety for the MED access.
The documentation for this struct was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/MED_Wrapper.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/MED_Wrapper.cpp