FreeCAD: TechDrawGui::QGIMatting Class Reference
TechDrawGui::QGIMatting Class Reference
#include <QGIMatting.h>
Public Types
enum { Type = QGraphicsItem::UserType + 205 }
Public Member Functions
virtual QRectF boundingRect () const
virtual void draw (void)
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr)
QGIMatting (void)
virtual void setRadius (double r)
virtual void setSize (double w, double h)
int type () const
~QGIMatting ()
Protected Member Functions
int getHoleStyle (void)
Protected Attributes
QGraphicsPathItem * m_border
double m_height
QGraphicsPathItem * m_mat
double m_radius
double m_width
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGIMatting()
QGIMatting::QGIMatting (void) explicit
References m_border, m_mat, and ZVALUE::MATTING.
~QGIMatting()
TechDrawGui::QGIMatting::~QGIMatting ()
Member Function Documentation
boundingRect()
QRectF QGIMatting::boundingRect () const virtual
draw()
void QGIMatting::draw (void) virtual
References getHoleStyle(), m_border, m_height, m_mat, m_radius, m_width, and ZVALUE::MATTING.
Referenced by TechDrawGui::QGIViewPart::drawMatting().
getHoleStyle()
int QGIMatting::getHoleStyle (void) protected
References TechDraw::Preferences::mattingStyle().
Referenced by draw().
paint()
void QGIMatting::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) virtual
setRadius()
virtual void TechDrawGui::QGIMatting::setRadius (double r) virtual
Referenced by TechDrawGui::QGIViewPart::drawMatting(), and draftguitools.gui_trackers.arcTracker::setBy3Points().
setSize()
virtual void TechDrawGui::QGIMatting::setSize (double w, double h) virtual
type()
int TechDrawGui::QGIMatting::type (void) const
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
Member Data Documentation
m_border
QGraphicsPathItem* TechDrawGui::QGIMatting::m_border protected
Referenced by draw(), and QGIMatting().
m_height
double TechDrawGui::QGIMatting::m_height protected
Referenced by draw().
m_mat
QGraphicsPathItem* TechDrawGui::QGIMatting::m_mat protected
Referenced by draw(), and QGIMatting().
m_radius
double TechDrawGui::QGIMatting::m_radius protected
Referenced by draw().
m_width
double TechDrawGui::QGIMatting::m_width protected
Referenced by draw().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/QGIMatting.h
FreeCAD/src/Mod/TechDraw/Gui/QGIMatting.cpp