FreeCAD: Gui::CustomMessageEvent Class Reference
Gui::CustomMessageEvent Class Reference
The CustomMessageEvent class is used to send messages as events in the methods Error(), Warning() and Message() of the StatusBarObserver class to the main window to display them on the status bar instead of printing them directly to the status bar.
Public Member Functions
CustomMessageEvent (int t, const QString &s, int timeout=0)
const QString & message () const
int timeout () const
int type () const
~CustomMessageEvent ()
Detailed Description
The CustomMessageEvent class is used to send messages as events in the methods Error(), Warning() and Message() of the StatusBarObserver class to the main window to display them on the status bar instead of printing them directly to the status bar.
This makes the usage of StatusBarObserver thread-safe.
Author
Werner Mayer
Constructor & Destructor Documentation
CustomMessageEvent()
Gui::CustomMessageEvent::CustomMessageEvent (int t, const QString & s, int timeout = 0)
~CustomMessageEvent()
Gui::CustomMessageEvent::~CustomMessageEvent ()
Member Function Documentation
message()
const QString & Gui::CustomMessageEvent::message () const
Referenced by Gui::MainWindow::customEvent(), and addonmanager_workers.GitProgressMonitor::update().
timeout()
int Gui::CustomMessageEvent::timeout () const
Referenced by Gui::MainWindow::customEvent(), and package_details.PackageDetails::load_finished().
type()
int Gui::CustomMessageEvent::type () const
Referenced by ArchProfile.ProfileTaskPanel::accept(), Gui::MainWindow::customEvent(), and ArchProfile.ProfileTaskPanel::retranslateUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/MainWindow.cpp