FreeCAD: Gui::Dialog::Ui_DlgPreferencePackManagement Class Reference
Gui::Dialog::Ui_DlgPreferencePackManagement Class Reference
#include <ui_DlgPreferencePackManagement.h>
Public Member Functions
void retranslateUi (QDialog *Gui__Dialog__DlgPreferencePackManagement)
void setupUi (QDialog *Gui__Dialog__DlgPreferencePackManagement)
Public Attributes
QGridLayout * gridLayout
QHBoxLayout * horizontalLayout
QSpacerItem * horizontalSpacer
QPushButton * pushButtonOpenAddonManager
QTreeWidget * treeWidget
Member Function Documentation
retranslateUi()
void Gui::Dialog::Ui_DlgPreferencePackManagement::retranslateUi (QDialog * Gui__Dialog__DlgPreferencePackManagement)
References pushButtonOpenAddonManager, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::Dialog::Ui_DlgPreferencePackManagement::setupUi (QDialog * Gui__Dialog__DlgPreferencePackManagement)
References gridLayout, horizontalLayout, horizontalSpacer, pushButtonOpenAddonManager, retranslateUi(), and treeWidget.
Member Data Documentation
gridLayout
QGridLayout* Gui::Dialog::Ui_DlgPreferencePackManagement::gridLayout
Referenced by setupUi().
horizontalLayout
QHBoxLayout* Gui::Dialog::Ui_DlgPreferencePackManagement::horizontalLayout
Referenced by setupUi().
horizontalSpacer
QSpacerItem* Gui::Dialog::Ui_DlgPreferencePackManagement::horizontalSpacer
Referenced by setupUi().
pushButtonOpenAddonManager
QPushButton* Gui::Dialog::Ui_DlgPreferencePackManagement::pushButtonOpenAddonManager
Referenced by retranslateUi(), and setupUi().
treeWidget
QTreeWidget* Gui::Dialog::Ui_DlgPreferencePackManagement::treeWidget
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_DlgPreferencePackManagement.h