FreeCAD: PathScripts.post.centroid_post Namespace Reference
PathScripts.post.centroid_post Namespace Reference
Functions
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
def processArguments (argstring)
Variables
int AXIS_PRECISION = 4
string COMMAND_SPACE = " "
string COMMENT = ";"
dictionary CORNER_MAX = {'x': 609.6, 'y': 152.4, 'z': 304.8}
dictionary CORNER_MIN = {'x': -609.6, 'y': -152.4, 'z': 0}
int FEED_PRECISION = 1
string HEADER
int LINENR = 100
string MACHINE_NAME = "Centroid"
bool MODAL = False
now = datetime.datetime.now()
bool OUTPUT_COMMENTS = True
bool OUTPUT_HEADER = True
bool OUTPUT_LINE_NUMBERS = False
string POST_OPERATION = ''''''
string POSTAMBLE
string PRE_OPERATION = ''''''
string PREAMBLE
pythonopen = open
string SAFETYBLOCK
bool SHOW_EDITOR = True
int SPINDLE_DECIMALS = 0
string TOOL_CHANGE = ''''''
string TOOLRETURN
string TOOLTIP
string TOOLTIP_ARGS
string UNIT_FORMAT = 'mm/min'
string UNITS = "G20"
string ZAXISRETURN
Function Documentation
export()
def PathScripts.post.centroid_post.export (objectslist, filename, argstring)
References PathScripts.post.centroid_post.linenumber(), PathScripts.post.centroid_post.parse(), PathScripts.post.centroid_post.processArguments(), and PathScripts.post.centroid_post.pythonopen.
linenumber()
def PathScripts.post.centroid_post.linenumber ()
Referenced by PathScripts.post.centroid_post.export(), and PathScripts.post.centroid_post.parse().
parse()
def PathScripts.post.centroid_post.parse (pathobj)
References PathScripts.post.centroid_post.linenumber().
Referenced by PathScripts.post.centroid_post.export().
processArguments()
def PathScripts.post.centroid_post.processArguments (argstring)
Referenced by PathScripts.post.centroid_post.export().
Variable Documentation
AXIS_PRECISION
int PathScripts.post.centroid_post.AXIS_PRECISION = 4
COMMAND_SPACE
string PathScripts.post.centroid_post.COMMAND_SPACE = " "
COMMENT
string PathScripts.post.centroid_post.COMMENT = ";"
CORNER_MAX
dictionary PathScripts.post.centroid_post.CORNER_MAX = {'x': 609.6, 'y': 152.4, 'z': 304.8}
CORNER_MIN
dictionary PathScripts.post.centroid_post.CORNER_MIN = {'x': -609.6, 'y': -152.4, 'z': 0}
FEED_PRECISION
int PathScripts.post.centroid_post.FEED_PRECISION = 1
HEADER
string PathScripts.post.centroid_post.HEADER
Initial value:
 =  '''
 ;Exported by FreeCAD
 ;Post Processor: {}
 ;CAM file: {}
 ;Output Time: {}
 '''.format(__name__, FreeCAD.ActiveDocument.FileName, str(now))
LINENR
int PathScripts.post.centroid_post.LINENR = 100
MACHINE_NAME
string PathScripts.post.centroid_post.MACHINE_NAME = "Centroid"
MODAL
bool PathScripts.post.centroid_post.MODAL = False
now
PathScripts.post.centroid_post.now = datetime.datetime.now()
OUTPUT_COMMENTS
bool PathScripts.post.centroid_post.OUTPUT_COMMENTS = True
OUTPUT_HEADER
bool PathScripts.post.centroid_post.OUTPUT_HEADER = True
OUTPUT_LINE_NUMBERS
bool PathScripts.post.centroid_post.OUTPUT_LINE_NUMBERS = False
POST_OPERATION
string PathScripts.post.centroid_post.POST_OPERATION = ''''''
POSTAMBLE
string PathScripts.post.centroid_post.POSTAMBLE
Initial value:
 =  '''M99
 '''
PRE_OPERATION
string PathScripts.post.centroid_post.PRE_OPERATION = ''''''
PREAMBLE
string PathScripts.post.centroid_post.PREAMBLE
Initial value:
 =  '''G53 G00 G17
 '''
pythonopen
PathScripts.post.centroid_post.pythonopen = open
Referenced by PathScripts.post.centroid_post.export().
SAFETYBLOCK
string PathScripts.post.centroid_post.SAFETYBLOCK
Initial value:
 =  '''G90 G80 G40 G49
 '''
SHOW_EDITOR
bool PathScripts.post.centroid_post.SHOW_EDITOR = True
SPINDLE_DECIMALS
int PathScripts.post.centroid_post.SPINDLE_DECIMALS = 0
TOOL_CHANGE
string PathScripts.post.centroid_post.TOOL_CHANGE = ''''''
TOOLRETURN
string PathScripts.post.centroid_post.TOOLRETURN
Initial value:
 =  '''M5 M25
 G49 H0
 '''
TOOLTIP
string PathScripts.post.centroid_post.TOOLTIP
Initial value:
 =  '''
 This is a postprocessor file for the Path workbench. It is used to
 take a pseudo-gcode fragment outputted by a Path object, and output
 real GCode suitable for a centroid 3 axis mill. This postprocessor, once placed
 in the appropriate PathScripts folder, can be used directly from inside
 FreeCAD, via the GUI importer or via python scripts with:
 import centroid_post
 centroid_post.export(object,"/path/to/file.ncc","")
 '''
TOOLTIP_ARGS
string PathScripts.post.centroid_post.TOOLTIP_ARGS
Initial value:
 =  '''
 Arguments for centroid:
     --header,--no-header             ... output headers (--header)
     --comments,--no-comments         ... output comments (--comments)
     --line-numbers,--no-line-numbers ... prefix with line numbers (--no-lin-numbers)
     --show-editor, --no-show-editor  ... pop up editor before writing output(--show-editor)
     --feed-precision=1               ... number of digits of precision for feed rate.  Default=1
     --axis-precision=4               ... number of digits of precision for axis moves.  Default=4
 '''
UNIT_FORMAT
string PathScripts.post.centroid_post.UNIT_FORMAT = 'mm/min'
UNITS
string PathScripts.post.centroid_post.UNITS = "G20"
ZAXISRETURN
string PathScripts.post.centroid_post.ZAXISRETURN
Initial value:
 =  '''G91 G28 X0 Z0
 G90
 '''