FreeCAD: Mod.Test.BaseTests.AlgebraTestCase Class Reference
Mod.Test.BaseTests.AlgebraTestCase Class Reference
Public Member Functions
def setUp (self)
def testAngle (self)
def testAngleWithNullVector (self)
def testBounding (self)
def testInverted (self)
def testMatrix (self)
def testRotAndMoveMatrix (self)
def testRotation (self)
def testVector2d (self)
def testYawPitchRoll (self)
Member Function Documentation
setUp()
def Mod.Test.BaseTests.AlgebraTestCase.setUp (self)
testAngle()
def Mod.Test.BaseTests.AlgebraTestCase.testAngle (self)
testAngleWithNullVector()
def Mod.Test.BaseTests.AlgebraTestCase.testAngleWithNullVector (self)
testBounding()
def Mod.Test.BaseTests.AlgebraTestCase.testBounding (self)
References femsolver.elmer.sifio.isValid().
testInverted()
def Mod.Test.BaseTests.AlgebraTestCase.testInverted (self)
testMatrix()
def Mod.Test.BaseTests.AlgebraTestCase.testMatrix (self)
testRotAndMoveMatrix()
def Mod.Test.BaseTests.AlgebraTestCase.testRotAndMoveMatrix (self)
testRotation()
def Mod.Test.BaseTests.AlgebraTestCase.testRotation (self)
References Mod.Test.Document.DocumentExpressionCases.assertAlmostEqual().
testVector2d()
def Mod.Test.BaseTests.AlgebraTestCase.testVector2d (self)
References Mod.Test.Document.DocumentExpressionCases.assertAlmostEqual().
testYawPitchRoll()
def Mod.Test.BaseTests.AlgebraTestCase.testYawPitchRoll (self)
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Test/BaseTests.py