FreeCAD: MeshPart::Mesher Class Reference
MeshPart::Mesher Class Reference
#include <Mesher.h>
Classes
struct Vertex
Public Types
enum Method { , Mefisto = 1, Standard = 3 }
Public Member Functions
Method getMethod () const
Mesher (const TopoDS_Shape &)
void setMethod (Method m)
~Mesher ()
Mefisto settings
void setMaxLength (double s)
double getMaxLength () const
void setMaxArea (double s)
double getMaxArea () const
void setLocalLength (double s)
double getLocalLength () const
void setDeflection (double s)
double getDeflection () const
void setAngularDeflection (double s)
double getAngularDeflection () const
void setMinMaxLengths (double f, double l)
void getMinMaxLengths (double &f, double &l) const
void setRegular (bool s)
bool isRegular () const
void setRelative (bool s)
bool isRelative () const
void setSegments (bool s)
bool isSegments () const
void setColors (const std::vector< uint32_t > &c)
Mesh::MeshObject * createMesh () const
Member Enumeration Documentation
Method
enum MeshPart::Mesher::Method
Enumerator
Mefisto
Standard
Constructor & Destructor Documentation
Mesher()
Mesher::Mesher (const TopoDS_Shape & s)
~Mesher()
Mesher::~Mesher ()
Member Function Documentation
createMesh()
Mesh::MeshObject * Mesher::createMesh () const
References Mesh::Segment::addIndices(), Mesh::MeshObject::addSegment(), MeshCore::MeshKernel::Adopt(), App::Color::asHexString(), SMESH_Gen::Compute(), Base::Console(), SMESH_Gen::CreateMesh(), Base::DistanceP2(), Data::ComplexGeoData::Domain::facets, Part::TopoShape::getDomains(), SMDS_MeshElement::GetNode(), Data::ComplexGeoData::Facet::I1, Data::ComplexGeoData::Facet::I2, Data::ComplexGeoData::Facet::I3, Mefisto, SMDS_MeshElement::NbNodes(), Data::ComplexGeoData::Domain::points, Mesh::Segment::save(), Base::Vector3< _Precision >::Set(), Mesh::Segment::setColor(), StdMeshers_Deflection1D::SetDeflection(), StdMeshers_LocalLength::SetLength(), StdMeshers_MaxLength::SetLength(), StdMeshers_Arithmetic1D::SetLength(), StdMeshers_MaxElementArea::SetMaxArea(), Mesh::Segment::setName(), StdMeshers_NumberOfSegments::SetNumberOfSegments(), App::Color::setPackedValue(), Standard, Mesh::MeshObject::swap(), draftgeoutils.general::v1(), Base::ConsoleSingleton::Warning(), SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
getAngularDeflection()
double MeshPart::Mesher::getAngularDeflection () const
getDeflection()
double MeshPart::Mesher::getDeflection () const
getLocalLength()
double MeshPart::Mesher::getLocalLength () const
getMaxArea()
double MeshPart::Mesher::getMaxArea () const
getMaxLength()
double MeshPart::Mesher::getMaxLength () const
getMethod()
Method MeshPart::Mesher::getMethod () const
getMinMaxLengths()
void MeshPart::Mesher::getMinMaxLengths (double & f, double & l) const
isRegular()
bool MeshPart::Mesher::isRegular () const
isRelative()
bool MeshPart::Mesher::isRelative () const
isSegments()
bool MeshPart::Mesher::isSegments () const
setAngularDeflection()
void MeshPart::Mesher::setAngularDeflection (double s)
setColors()
void MeshPart::Mesher::setColors (const std::vector< uint32_t > & c)
setDeflection()
void MeshPart::Mesher::setDeflection (double s)
setLocalLength()
void MeshPart::Mesher::setLocalLength (double s)
setMaxArea()
void MeshPart::Mesher::setMaxArea (double s)
setMaxLength()
void MeshPart::Mesher::setMaxLength (double s)
setMethod()
void MeshPart::Mesher::setMethod (Method m)
setMinMaxLengths()
void MeshPart::Mesher::setMinMaxLengths (double f, double l)
setRegular()
void MeshPart::Mesher::setRegular (bool s)
setRelative()
void MeshPart::Mesher::setRelative (bool s)
setSegments()
void MeshPart::Mesher::setSegments (bool s)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/MeshPart/App/Mesher.h
Sources/FreeCAD/src/Mod/MeshPart/App/Mesher.cpp