FreeCAD: MeshCore::MeshFacetVisitor Class Reference
MeshCore::MeshFacetVisitor Class Reference abstract
Abstract base class for facet visitors.
#include <Visitor.h>
Public Member Functions
virtual bool AllowVisit (const MeshFacet &rclFacet, const MeshFacet &rclFrom, unsigned long ulFInd, unsigned long ulLevel, unsigned short neighbourIndex)
Test before a facet will be flagged as VISIT, return false means: go on with visiting the facets but not this one and set not the VISIT flag.
MeshFacetVisitor (void)
Construction.
virtual bool Visit (const MeshFacet &rclFacet, const MeshFacet &rclFrom, unsigned long ulFInd, unsigned long ulLevel)=0
Needs to be implemented in sub-classes.
virtual ~MeshFacetVisitor (void)
Denstruction.
Detailed Description
Abstract base class for facet visitors.
The MeshFacetVisitor class can be used for the so called "Region growing" algorithms.
Constructor & Destructor Documentation
MeshFacetVisitor()
MeshCore::MeshFacetVisitor::MeshFacetVisitor (void)
Construction.
~MeshFacetVisitor()
virtual MeshCore::MeshFacetVisitor::~MeshFacetVisitor (void) virtual
Denstruction.
Member Function Documentation
AllowVisit()
virtual bool MeshCore::MeshFacetVisitor::AllowVisit (const MeshFacet & rclFacet, const MeshFacet & rclFrom, unsigned long ulFInd, unsigned long ulLevel, unsigned short neighbourIndex) virtual
Test before a facet will be flagged as VISIT, return false means: go on with visiting the facets but not this one and set not the VISIT flag.
Reimplemented in MeshCore::MeshPlaneVisitor, and MeshCore::MeshSurfaceVisitor.
Referenced by MeshCore::MeshKernel::VisitNeighbourFacets().
Visit()
virtual bool MeshCore::MeshFacetVisitor::Visit (const MeshFacet & rclFacet, const MeshFacet & rclFrom, unsigned long ulFInd, unsigned long ulLevel) pure virtual
Needs to be implemented in sub-classes.
rclFacet is the currently visited facet with the index ulFInd, rclFrom is the last visited facet and ulLevel indicates the ring number around the start facet. If true is returned the next iteration is done if there are still facets to visit. If false is returned the calling method stops immediately visiting further facets.
Implemented in MeshCore::MeshTopFacetVisitor, MeshCore::MeshSearchNeighbourFacetsVisitor, MeshCore::MeshPlaneVisitor, MeshCore::MeshSurfaceVisitor, MeshCore::MeshSameOrientationCollector, MeshCore::MeshOrientationCollector, and MeshCore::MeshOrientationVisitor.
Referenced by MeshCore::MeshKernel::VisitNeighbourFacets(), and MeshCore::MeshKernel::VisitNeighbourFacetsOverCorners().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Visitor.h