FreeCAD: PathScripts.post.gcode_pre Namespace Reference
PathScripts.post.gcode_pre Namespace Reference
Classes
class PathNoActiveDocumentException
class PathNoJobException
Functions
def insert (filename, docname=None)
def matchToolController (op, toolnumber)
def open (filename)
def parse (inputstring)
Variables
PathCustom = PathCustomGui.PathCustom
pythonopen = open
translate = FreeCAD.Qt.translate
Function Documentation
insert()
def PathScripts.post.gcode_pre.insert (filename, docname = None)
called when freecad imports a file
References PathScripts.post.gcode_pre.matchToolController().
Referenced by PathScripts.post.gcode_pre.open().
matchToolController()
def PathScripts.post.gcode_pre.matchToolController (op, toolnumber)
Try to match a tool controller in the job by number
Referenced by PathScripts.post.gcode_pre.insert().
open()
def PathScripts.post.gcode_pre.open (filename)
called when freecad opens a file.
References PathScripts.post.gcode_pre.insert().
parse()
def PathScripts.post.gcode_pre.parse (inputstring)
References PathScripts.post.gcode_pre.parse(), and PathScripts.post.gcode_pre.pythonopen.
Referenced by PathScripts.post.gcode_pre.parse().
Variable Documentation
PathCustom
PathScripts.post.gcode_pre.PathCustom = PathCustomGui.PathCustom
pythonopen
PathScripts.post.gcode_pre.pythonopen = open
Referenced by PathScripts.post.gcode_pre.parse().
translate
PathScripts.post.gcode_pre.translate = FreeCAD.Qt.translate