FreeCAD: NavigationIndicatorGui.IndicatorButton Class Reference
NavigationIndicatorGui.IndicatorButton Class Reference
Public Member Functions
def changeEvent (self, event)
def onChange (self, paramGrp, param)
Detailed Description
Detect language change events.
Member Function Documentation
changeEvent()
def NavigationIndicatorGui.IndicatorButton.changeEvent (self, event)
Change events.
References NavigationIndicatorGui.IndicatorButton.changeEvent(), NavigationIndicatorGui.onTooltip(), and NavigationIndicatorGui.retranslateUi().
Referenced by NavigationIndicatorGui.IndicatorButton.changeEvent().
onChange()
def NavigationIndicatorGui.IndicatorButton.onChange (self, paramGrp, param)
References NavigationIndicatorGui.setCurrent().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Tux/NavigationIndicatorGui.py