FreeCAD: NETGENPlugin_NetgenLibWrapper Struct Reference
NETGENPlugin_NetgenLibWrapper Struct Reference
It correctly initializes netgen library at constructor and correctly finishes using netgen library at destructor.
#include <NETGENPlugin_Mesher.hxx>
Public Member Functions
NETGENPlugin_NetgenLibWrapper ()
Initialize netgen library.
void setMesh (nglib::Ng_Mesh *mesh)
Set netgen mesh to delete at destruction.
~NETGENPlugin_NetgenLibWrapper ()
Finish using netgen library.
Detailed Description
It correctly initializes netgen library at constructor and correctly finishes using netgen library at destructor.
Constructor & Destructor Documentation
NETGENPlugin_NetgenLibWrapper()
NETGENPlugin_NetgenLibWrapper::NETGENPlugin_NetgenLibWrapper ()
Initialize netgen library.
~NETGENPlugin_NetgenLibWrapper()
NETGENPlugin_NetgenLibWrapper::~NETGENPlugin_NetgenLibWrapper ()
Finish using netgen library.
References NETGENPlugin_Mesher::RemoveTmpFiles().
Member Function Documentation
setMesh()
void NETGENPlugin_NetgenLibWrapper::setMesh (nglib::Ng_Mesh * mesh)
Set netgen mesh to delete at destruction.
Referenced by NETGENPlugin_Mesher::Compute(), and NETGENPlugin_Mesher::Evaluate().
The documentation for this struct was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/NETGENPlugin_Mesher.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/NETGENPlugin/NETGENPlugin_Mesher.cpp