FreeCAD: TechDraw::Wire Class Reference
TechDraw::Wire Class Reference
Simple Collection of geometric features based on BaseGeom inherited classes in order.
#include <Geometry.h>
Public Member Functions
void dump (std::string s)
TopoDS_Wire toOccWire (void) const
Wire ()
Wire (const TopoDS_Wire &w)
~Wire ()
Public Attributes
BaseGeomPtrVector geoms
Detailed Description
Simple Collection of geometric features based on BaseGeom inherited classes in order.
Constructor & Destructor Documentation
Wire() [1/2]
Wire::Wire ()
Wire() [2/2]
Wire::Wire (const TopoDS_Wire & w)
References TechDraw::BaseGeom::baseFactory(), Base::Console(), geoms, and Base::ConsoleSingleton::Log().
~Wire()
Wire::~Wire ()
References geoms.
Member Function Documentation
dump()
void Wire::dump (std::string s)
References toOccWire().
toOccWire()
TopoDS_Wire Wire::toOccWire (void) const
References geoms.
Referenced by dump().
Member Data Documentation
geoms
BaseGeomPtrVector TechDraw::Wire::geoms
Referenced by toOccWire(), Wire(), and ~Wire().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/App/Geometry.h
FreeCAD/src/Mod/TechDraw/App/Geometry.cpp