FreeCAD: SMESH_MAT2d::Boundary Class Reference
SMESH_MAT2d::Boundary Class Reference
Face boundary is discretized so that each its segment to correspond to an edge of MA.
#include <SMESH_MAT2d.hxx>
Public Member Functions
Boundary (std::size_t nbEdges)
bool getBranchPoint (const BoundaryPoint &bp, BranchPoint &p) const
Returns a BranchPoint corresponding to a given BoundaryPoint on a geom EDGE.
bool getBranchPoint (const std::size_t iEdge, double u, BranchPoint &p) const
Returns a BranchPoint corresponding to a given point on a geom EDGE.
bool getPoint (std::size_t iEdge, std::size_t iSeg, double u, BoundaryPoint &bp) const
Returns a boundary point on a given EDGE.
BndPoints & getPoints (std::size_t iEdge)
bool isConcaveSegment (std::size_t iEdge, std::size_t iSeg) const
Check if a given boundary segment is a null-length segment on a concave boundary corner.
bool moveToClosestEdgeEnd (BoundaryPoint &bp) const
Moves (changes _param) a given BoundaryPoint to a closest EDGE end.
std::size_t nbEdges () const
Detailed Description
Face boundary is discretized so that each its segment to correspond to an edge of MA.
Constructor & Destructor Documentation
Boundary()
SMESH_MAT2d::Boundary::Boundary (std::size_t nbEdges)
Member Function Documentation
getBranchPoint() [1/2]
bool SMESH_MAT2d::Boundary::getBranchPoint (const BoundaryPoint & bp, BranchPoint & p) const
Returns a BranchPoint corresponding to a given BoundaryPoint on a geom EDGE.
Parameters
[in] bp - the BoundaryPoint
[out] p - the found BranchPoint
Returns
bool - is OK
getBranchPoint() [2/2]
bool SMESH_MAT2d::Boundary::getBranchPoint (const std::size_t iEdge, double u, BranchPoint & p) const
Returns a BranchPoint corresponding to a given point on a geom EDGE.
Parameters
[in] iEdge - index of geom EDGE within a vector passed at MA construction
[in] u - parameter of the point on EDGE curve
[out] p - the found BranchPoint
Returns
bool - is OK
getPoint()
bool SMESH_MAT2d::Boundary::getPoint (std::size_t iEdge, std::size_t iSeg, double u, BoundaryPoint & bp) const
Returns a boundary point on a given EDGE.
Parameters
[in] iEdge - index of the EDGE within MedialAxis
[in] iSeg - index of a boundary segment within this Branch
[in] u - [0;1] normalized param within iSeg-th segment
[out] bp - the found BoundaryPoint
Returns
bool - true if the BoundaryPoint is found
Referenced by PathScripts.PathOpGui.TaskPanelBaseLocationPage::addLocation(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::addNewTag(), PathScripts.PathOpGui.TaskPanelBaseLocationPage::editLocation(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::editTag(), draftguitools.gui_arcs.Arc_3Points::getPoint(), ArchCurtainWall.CommandArchCurtainWall::getPoint(), ArchTruss.CommandArchTruss::getPoint(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::modifyStandardButtons(), and PathScripts.PathOpGui.TaskPanelBaseLocationPage::modifyStandardButtons().
getPoints()
BndPoints& SMESH_MAT2d::Boundary::getPoints (std::size_t iEdge)
isConcaveSegment()
bool SMESH_MAT2d::Boundary::isConcaveSegment (std::size_t iEdge, std::size_t iSeg) const
Check if a given boundary segment is a null-length segment on a concave boundary corner.
Parameters
[in] iEdge - index of a geom EDGE
[in] iSeg - index of a boundary segment
Returns
bool - true if the segment is on concave corner
moveToClosestEdgeEnd()
bool SMESH_MAT2d::Boundary::moveToClosestEdgeEnd (BoundaryPoint & bp) const
Moves (changes _param) a given BoundaryPoint to a closest EDGE end.
nbEdges()
std::size_t SMESH_MAT2d::Boundary::nbEdges () const
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_MAT2d.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/SMESH_MAT2d.cpp