FreeCAD: RobotGui::TaskDlgEdge2Trac Class Reference
RobotGui::TaskDlgEdge2Trac Class Reference
simulation dialog for the TaskView
#include <TaskDlgEdge2Trac.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void clicked (int)
is called by the framework if an button is clicked which has no accept or rject role
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
returns for Close and Help button
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual void open ()
is called the TaskView when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgEdge2Trac (Robot::Edge2TracObject *)
~TaskDlgEdge2Trac ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
tells the framework which buttons are wished for the dialog
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Protected Attributes
Robot::Edge2TracObject * Edge2TaskObject
TaskEdge2TracParameter * param
Gui::TaskView::TaskSelectLinkProperty * select
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
simulation dialog for the TaskView
Constructor & Destructor Documentation
TaskDlgEdge2Trac()
TaskDlgEdge2Trac::TaskDlgEdge2Trac (Robot::Edge2TracObject * obj)
References Gui::TaskView::TaskDialog::Content, param, and select.
~TaskDlgEdge2Trac()
TaskDlgEdge2Trac::~TaskDlgEdge2Trac ()
Member Function Documentation
accept()
bool TaskDlgEdge2Trac::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::TaskView::TaskSelectLinkProperty::accept(), Gui::Application::activeDocument(), Base::Console(), Edge2TaskObject, Gui::Application::Instance, Gui::TaskView::TaskSelectLinkProperty::isSelectionValid(), App::DocumentObject::recomputeFeature(), select, and Base::ConsoleSingleton::Warning().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
clicked()
void TaskDlgEdge2Trac::clicked (int button) virtual
is called by the framework if an button is clicked which has no accept or rject role
Reimplemented from Gui::TaskView::TaskDialog.
References Base::Console(), Edge2TaskObject, Robot::Edge2TracObject::execute(), Gui::TaskView::TaskSelectLinkProperty::isSelectionValid(), Robot::Edge2TracObject::NbrOfCluster, Robot::Edge2TracObject::NbrOfEdges, param, select, Gui::TaskView::TaskSelectLinkProperty::sendSelection2Property(), RobotGui::TaskEdge2TracParameter::setEdgeAndClusterNbr(), and Base::ConsoleSingleton::Warning().
getStandardButtons()
virtual QDialogButtonBox::StandardButtons RobotGui::TaskDlgEdge2Trac::getStandardButtons (void) const virtual
returns for Close and Help button
Reimplemented from Gui::TaskView::TaskDialog.
helpRequested()
void TaskDlgEdge2Trac::helpRequested () virtual
is called by the framework if the user press the help button
Reimplemented from Gui::TaskView::TaskDialog.
open()
void TaskDlgEdge2Trac::open () virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::TaskView::TaskSelectLinkProperty::activate(), Edge2TaskObject, Robot::Edge2TracObject::execute(), Robot::Edge2TracObject::NbrOfCluster, Robot::Edge2TracObject::NbrOfEdges, param, select, and RobotGui::TaskEdge2TracParameter::setEdgeAndClusterNbr().
reject()
bool TaskDlgEdge2Trac::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References Edge2TaskObject, Robot::Edge2TracObject::execute(), Gui::TaskView::TaskSelectLinkProperty::reject(), and select.
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
Member Data Documentation
Edge2TaskObject
Robot::Edge2TracObject* RobotGui::TaskDlgEdge2Trac::Edge2TaskObject protected
Referenced by accept(), clicked(), open(), and reject().
param
TaskEdge2TracParameter* RobotGui::TaskDlgEdge2Trac::param protected
Referenced by clicked(), draftguitools.gui_selectplane.Draft_SelectPlane::finish(), draftguitools.gui_selectplane.Draft_SelectPlane::onSetExtension(), draftguitools.gui_selectplane.Draft_SelectPlane::onSetGridSize(), draftguitools.gui_selectplane.Draft_SelectPlane::onSetMainline(), draftguitools.gui_selectplane.Draft_SelectPlane::onSetSnapRadius(), open(), and TaskDlgEdge2Trac().
select
Gui::TaskView::TaskSelectLinkProperty* RobotGui::TaskDlgEdge2Trac::select protected
Referenced by accept(), clicked(), open(), reject(), and TaskDlgEdge2Trac().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Robot/Gui/TaskDlgEdge2Trac.h
FreeCAD/src/Mod/Robot/Gui/TaskDlgEdge2Trac.cpp