FreeCAD: PathTests.TestPathThreadMilling.TestPathThreadMilling Class Reference
PathTests.TestPathThreadMilling.TestPathThreadMilling Class Reference
Public Member Functions
def assertList (self, have, want)
def assertRadii (self, have, want)
def test00 (self)
def test01 (self)
def test10 (self)
Public Member Functions inherited from PathTests.PathTestUtils.PathTestBase
def assertArc (self, edge, pt1, pt2, direction='CW')
def assertCircle (self, edge, pt, r)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertCommandEqual (self, c1, c2)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertEdgeShapesMatch (self, e1, e2)
def assertEqualLocale (self, s1, s2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertPlacement (self, p1, p2)
def assertPointsMatch (self, pts0, pts1)
def assertRoughly (self, f1, f2, error=0.00001)
Detailed Description
Test thread milling basics.
Member Function Documentation
assertList()
def PathTests.TestPathThreadMilling.TestPathThreadMilling.assertList (self, have, want)
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
Referenced by PathTests.TestPathThreadMilling.TestPathThreadMilling.test10().
assertRadii()
def PathTests.TestPathThreadMilling.TestPathThreadMilling.assertRadii (self, have, want)
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
Referenced by PathTests.TestPathThreadMilling.TestPathThreadMilling.test00(), and PathTests.TestPathThreadMilling.TestPathThreadMilling.test01().
test00()
def PathTests.TestPathThreadMilling.TestPathThreadMilling.test00 (self)
Verify internal radii.
References PathTests.TestPathThreadMilling.TestPathThreadMilling.assertRadii().
Referenced by PathTests.TestPathTool.TestPathTool.test01(), PathTests.TestPathToolController.TestPathToolController.test01(), PathTests.TestPathTooltable.TestPathTooltable.test01(), PathTests.TestPathTool.TestPathTool.test02(), and PathTests.TestPathTooltable.TestPathTooltable.test02().
test01()
def PathTests.TestPathThreadMilling.TestPathThreadMilling.test01 (self)
Verify internal radii with tool crest.
References PathTests.TestPathThreadMilling.TestPathThreadMilling.assertRadii().
test10()
def PathTests.TestPathThreadMilling.TestPathThreadMilling.test10 (self)
Verify thread passes.
References PathTests.TestPathThreadMilling.TestPathThreadMilling.assertList().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Path/PathTests/TestPathThreadMilling.py