FreeCAD: App::PropertyLinkSubList Class Reference
App::PropertyLinkSubList Class Reference
#include <PropertyLinks.h>
Public Types
typedef std::pair< DocumentObject *, std::vector< std::string > > SubSet
Public Types inherited from App::PropertyLinkBase
enum LinkFlags {
LinkAllowExternal , LinkDetached , LinkRestoring , LinkAllowPartial ,
LinkRestoreLabel
}
typedef std::pair< std::string, std::string > ShadowSub
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , PropStaticBegin = 21 ,
PropDynamic = 21 , PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 ,
PropTransient = 25 , PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 ,
User1 = 28 , User2 = 29 , User3 = 30 , User4 = 31
}
Public Member Functions
virtual bool adjustLink (const std::set< App::DocumentObject * > &inList) override
Called to adjust the link to avoid potential cyclic dependency.
virtual void afterRestore () override
Called at the beginning of Document::afterRestore()
virtual void breakLink (App::DocumentObject *obj, bool clear) override
Called to reset this link property.
virtual Property * Copy (void) const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
virtual Property * CopyOnImportExternal (const std::map< std::string, std::string > &nameMap) const override
Return a copy of the property if any changes caused by importing external object.
virtual Property * CopyOnLabelChange (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const override
Update object label reference in this property.
virtual Property * CopyOnLinkReplace (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const override
Return a copy of the property if the link replacement affects this property.
virtual const char * getEditorName (void) const override
Get the class name of the associated property editor item.
virtual void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=0, bool newStyle=true) const override
Obtain the linked objects.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
const std::string getPyReprString () const
const std::vector< ShadowSub > & getShadowSubs () const
int getSize (void) const
std::vector< SubSet > getSubListValues (bool newStyle=false) const
std::vector< std::string > getSubValues (bool newStyle) const
const std::vector< std::string > & getSubValues (void) const
DocumentObject * getValue () const
getValue emulates the action of a single-object link.
const std::vector< DocumentObject * > & getValues (void) const
virtual void onContainerRestored () override
Called before calling DocumentObject::onDocumentRestored()
virtual void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
PropertyLinkSubList ()
A constructor.
virtual bool referenceChanged () const override
Test if the element reference has changed after restore.
int removeValue (App::DocumentObject *lValue)
Removes all occurrences of lValue in the property together with its sub-elements and returns the number of entries removed.
virtual void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
virtual void setPyObject (PyObject *) override
void setSize (int newSize)
void setSubListValues (const std::vector< SubSet > &)
void setValue (App::DocumentObject *lValue, const std::vector< std::string > &SubList=std::vector< std::string >())
setValue: PropertyLinkSub-compatible overload
void setValue (DocumentObject *, const char *)
Sets the property.
void setValues (const std::vector< DocumentObject * > &, const std::vector< const char * > &)
void setValues (const std::vector< DocumentObject * > &, const std::vector< std::string > &, std::vector< ShadowSub > &&ShadowSubList={})
void setValues (std::vector< DocumentObject * > &&, std::vector< std::string > &&subs, std::vector< ShadowSub > &&ShadowSubList={})
virtual void updateElementReference (DocumentObject *feature, bool reverse=false, bool notify=false) override
Link type property interface APIs These APIs are moved here so that any type of property can have the property link behavior, e.g.
virtual ~PropertyLinkSubList ()
A destructor.
Public Member Functions inherited from App::PropertyLinkBase
void checkLabelReferences (const std::vector< std::string > &subs, bool reset=true)
Check subnames for label registration.
virtual int checkRestore (std::string *msg=0) const
Test if the link is restored unchanged.
void getLinkedElements (std::map< App::DocumentObject *, std::vector< std::string > > &elements, bool newStyle=true, bool all=true) const
Helper function to return a map of linked object and its subname references.
template<class T >
void getLinkedObjects (T &inserter, bool all=false) const
Helper function to return linked objects using an std::inserter.
std::map< App::DocumentObject *, std::vector< std::string > > linkedElements (bool newStyle=true, bool all=true) const
Helper function to return a map of linked object and its subname references.
std::vector< App::DocumentObject * > linkedObjects (bool all=false) const
Helper function to return all linked objects of this property.
PropertyLinkBase ()
void registerLabelReferences (std::vector< std::string > &&labels, bool reset=true)
Register label reference for future object relabel update.
void setAllowExternal (bool allow)
Enable/disable temporary holding external object without throwing exception.
virtual void setAllowPartial (bool enable)
bool testFlag (int flag) const
void unregisterElementReference ()
Clear internal element reference registration.
void unregisterLabelReferences ()
Clear internal label references registration.
virtual ~PropertyLinkBase ()
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
const char * getName (void) const
get the name of this property in the belonging container
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::ScopedLink
LinkScope getScope ()
Get the links scope Retrieve what kind of links are allowed.
void setScope (LinkScope scope)
Set the links scope Allows to define what kind of links are allowed.
Additional Inherited Members
Static Public Member Functions inherited from App::PropertyLinkBase
static void breakLinks (App::DocumentObject *link, const std::vector< App::DocumentObject * > &objs, bool clear)
Helper function for breaking link properties.
static const char * exportSubName (std::string &output, const App::DocumentObject *obj, const char *subname, bool first_obj=false)
Helper function to export a subname reference.
static void getLabelReferences (std::vector< std::string > &labels, const char *subname)
Helper function to extract labels from a subname reference.
static std::string importSubName (Base::XMLReader &reader, const char *sub, bool &restoreLabel)
Helper function to import a subname reference.
static void restoreLabelReference (const App::DocumentObject *obj, std::string &sub, ShadowSub *shadow=0)
Helper function to restore label references during import.
static App::DocumentObject * tryImport (const App::Document *doc, const App::DocumentObject *obj, const std::map< std::string, std::string > &nameMap)
Helper function for link import operation.
static std::string tryImportSubName (const App::DocumentObject *obj, const char *sub, const App::Document *doc, const std::map< std::string, std::string > &nameMap)
Helper function for link import operation.
static std::pair< App::DocumentObject *, std::string > tryReplaceLink (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const char *sub=0)
Helper functions.
static std::pair< App::DocumentObject *, std::vector< std::string > > tryReplaceLinkSubs (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const std::vector< std::string > &subs)
Helper function to check and replace a link with multiple subname references.
static void updateElementReferences (DocumentObject *feature, bool reverse=false)
Update all element references in all link properties of feature.
static std::string updateLabelReference (const App::DocumentObject *linked, const char *subname, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
Helper function to update subname reference on label change.
static std::vector< std::pair< Property *, std::unique_ptr< Property > > > updateLabelReferences (App::DocumentObject *obj, const char *newLabel)
Helper function to collect changed property when an object re-label.
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Protected Member Functions inherited from App::PropertyLinkBase
virtual void hasSetValue () override
Gets called by all setValue() methods after the value has changed.
void setFlag (int flag, bool value=true)
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Member Typedef Documentation
SubSet
typedef std::pair<DocumentObject*, std::vector<std::string> > App::PropertyLinkSubList::SubSet
Constructor & Destructor Documentation
PropertyLinkSubList()
PropertyLinkSubList::PropertyLinkSubList ()
A constructor.
A more elaborate description of the constructor.
Referenced by Copy().
~PropertyLinkSubList()
PropertyLinkSubList::~PropertyLinkSubList () virtual
A destructor.
A more elaborate description of the destructor.
References Base::Persistence::getClassTypeId(), App::Property::getContainer(), App::Hidden, Base::BaseClass::isDerivedFrom(), and App::DocumentObject::testStatus().
Member Function Documentation
adjustLink()
bool PropertyLinkSubList::adjustLink (const std::set< App::DocumentObject * > & inList) override virtual
Called to adjust the link to avoid potential cyclic dependency.
Parameters
inList recursive in-list of the would-be parent
Returns
Return whether the link has been adjusted
This function tries to correct the link to avoid any (sub)object inside in-list. If the adjustment is impossible, exception will be raised
Implements App::PropertyLinkBase.
References App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::DocumentObject::getSubObject(), App::Hidden, and setValues().
afterRestore()
void PropertyLinkSubList::afterRestore () override virtual
Called at the beginning of Document::afterRestore()
This function is called without dependency sorting, because some types of link property can only reconstructs the linking information inside this function.
One example use case of this function is PropertyLinkSub that uses afterRestore() to parse and restore subname references, which may contain sub-object reference from external document, and there will be special mapping required during object import.
Another example is PropertyExpressionEngine which only parse the restored expression in afterRestore(). The reason, in addition to subname mapping like PropertyLinkSub, is that it can handle document name adjustment as well. It internally relies on PropertyXLink to store the external document path for external linking. When the external document is restored, its internal name may change due to name conflict with existing documents. PropertyExpressionEngine can now auto adjust external references without any problem.
Reimplemented from App::Property.
References App::PropertyLinkBase::LinkRestoreLabel, App::PropertyLinkBase::restoreLabelReference(), App::PropertyLinkBase::setFlag(), and App::PropertyLinkBase::testFlag().
breakLink()
void PropertyLinkSubList::breakLink (App::DocumentObject * obj, bool clear) override virtual
Called to reset this link property.
Parameters
obj reset link property if it is linked to this object
clear if true, then also reset property if the owner of this property is obj
See also
breakLinks()
Implements App::PropertyLinkBase.
References App::Property::getContainer(), and setValues().
Copy()
Property * PropertyLinkSubList::Copy (void) const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References PropertyLinkSubList().
CopyOnImportExternal()
Property * PropertyLinkSubList::CopyOnImportExternal (const std::map< std::string, std::string > & nameMap) const override virtual
Return a copy of the property if any changes caused by importing external object.
Reimplemented from App::PropertyLinkBase.
References App::Property::getContainer(), draftfunctions.move::move(), App::PropertyLinkBase::tryImport(), and App::PropertyLinkBase::tryImportSubName().
CopyOnLabelChange()
Property * PropertyLinkSubList::CopyOnLabelChange (App::DocumentObject * obj, const std::string & ref, const char * newLabel) const override virtual
Update object label reference in this property.
Parameters
obj the object owner of the changing label
ref subname reference to old label
newLabel the future new label
Returns
Returns a copy of the property if its link reference is affected. The copy will later be assgiend to this property by calling its Paste().
Reimplemented from App::PropertyLinkBase.
References App::Property::getContainer(), draftfunctions.move::move(), and App::PropertyLinkBase::updateLabelReference().
CopyOnLinkReplace()
Property * PropertyLinkSubList::CopyOnLinkReplace (const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj) const override virtual
Return a copy of the property if the link replacement affects this property.
Parameters
owner the parent object whose link property is to be replace. Note that The parent may not be the container of this property. Link sub property can use this opportunity to adjust its relative links.
oldObj object to be replaced
newObj object to replace with
Returns
Return a copy of the property that is adjusted for the link replacement operation.
Implements App::PropertyLinkBase.
References App::Property::getContainer(), draftfunctions.move::move(), and App::PropertyLinkBase::tryReplaceLink().
getEditorName()
virtual const char* App::PropertyLinkSubList::getEditorName (void) const override virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
getLinks()
void PropertyLinkSubList::getLinks (std::vector< App::DocumentObject * > & objs, bool all = false, std::vector< std::string > * subs = 0, bool newStyle = true) const override virtual
Obtain the linked objects.
Parameters
objs hold the returned linked objects on output
all if true, then return all the linked object regardless of this LinkScope. If false, then return only if the LinkScope is not hidden.
sub if given, then return subname references.
newStyle whether to return new or old style subname reference
Implements App::PropertyLinkBase.
References getSubValues(), App::Hidden, and draftfunctions.move::move().
getMemSize()
unsigned int PropertyLinkSubList::getMemSize (void) const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
See also
Base::Persistence
Reimplemented from App::Property.
References getSize().
getPyObject()
PyObject * PropertyLinkSubList::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
References getSize(), getSubListValues(), and DraftVecUtils::tup().
Referenced by Attacher::AttachEnginePy::getReferences().
getPyReprString()
const string PropertyLinkSubList::getPyReprString () const
References App::DocumentObject::getDocument(), and App::Document::getName().
Referenced by PartGui::TaskDlgAttacher::accept().
getShadowSubs()
const std::vector<ShadowSub>& App::PropertyLinkSubList::getShadowSubs () const
getSize()
int PropertyLinkSubList::getSize (void) const
Referenced by Surface::Filling::execute(), getMemSize(), getPyObject(), TechDraw::DrawViewDimension::has3DReferences(), Surface::GeomFillSurface::onChanged(), Save(), and PartGui::TaskAttacher::TaskAttacher().
getSubListValues()
std::vector< PropertyLinkSubList::SubSet > PropertyLinkSubList::getSubListValues (bool newStyle = false) const
Referenced by SurfaceGui::FillingPanel::accept(), SurfaceGui::FillingEdgePanel::accept(), SurfaceGui::SectionsPanel::accept(), SurfaceGui::GeomFillSurface::EdgeSelection::allow(), Surface::Sewing::execute(), getPyObject(), Surface::GeomFillSurface::getWire(), SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), SurfaceGui::FillingPanel::onSelectionChanged(), SurfaceGui::FillingEdgePanel::onSelectionChanged(), SurfaceGui::FillingVertexPanel::onSelectionChanged(), SurfaceGui::FillingPanel::open(), SurfaceGui::FillingEdgePanel::open(), SurfaceGui::FillingVertexPanel::open(), SurfaceGui::SectionsPanel::open(), SurfaceGui::FillingPanel::reject(), SurfaceGui::FillingEdgePanel::reject(), SurfaceGui::FillingVertexPanel::reject(), SurfaceGui::SectionsPanel::reject(), SurfaceGui::FillingPanel::slotDeletedObject(), SurfaceGui::FillingEdgePanel::slotDeletedObject(), SurfaceGui::FillingVertexPanel::slotDeletedObject(), and SurfaceGui::SectionsPanel::slotDeletedObject().
getSubValues() [1/2]
std::vector< std::string > PropertyLinkSubList::getSubValues (bool newStyle) const
getSubValues() [2/2]
const std::vector<std::string>& App::PropertyLinkSubList::getSubValues (void) const
Referenced by PartDesignGui::TaskDlgDatumParameters::accept(), TechDraw::DrawViewDimension::checkReferences2D(), TechDrawGui::TaskLinkDim::dimReferencesSelection(), Surface::Sections::execute(), TechDraw::DrawViewDimension::execute(), Fem::Constraint::getCylinder(), PartDesign::ShapeBinder::getFilteredReferences(), getLinks(), Fem::Constraint::getPoints(), TechDraw::DrawViewDimension::getPointsEdgeVert(), TechDraw::DrawViewDimension::getPointsOneEdge(), TechDraw::DrawViewDimension::getPointsTwoEdges(), TechDraw::DrawViewDimension::getPointsTwoVerts(), TechDraw::DrawViewDimension::getRefType(), TechDraw::DrawViewDimExtent::getSubNames(), TechDraw::DrawViewDimension::has2DReferences(), TechDraw::DrawViewDimension::leaderIntersectsArc(), TechDraw::DrawDimHelper::makeExtentDim(), Fem::Constraint::onChanged(), FemGui::TaskFemConstraint::onReferenceDeleted(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), SurfaceGui::FillingEdgePanel::onSelectionChanged(), SurfaceGui::FillingVertexPanel::onSelectionChanged(), SurfaceGui::GeomFillSurface::onSelectionChanged(), Attacher::AttachEngine::readLinks(), PartDesignGui::relinkToBody(), TechDraw::DrawViewDimension::setAll3DMeasurement(), SurfaceGui::FillingPanel::setEditedObject(), SurfaceGui::FillingEdgePanel::setEditedObject(), SurfaceGui::FillingVertexPanel::setEditedObject(), SurfaceGui::GeomFillSurface::setEditedObject(), SurfaceGui::SectionsPanel::setEditedObject(), SketcherGui::SuggestAutoMapMode(), PartGui::TaskAttacher::TaskAttacher(), FemGui::TaskFemConstraintBearing::TaskFemConstraintBearing(), FemGui::TaskFemConstraintContact::TaskFemConstraintContact(), FemGui::TaskFemConstraintDisplacement::TaskFemConstraintDisplacement(), FemGui::TaskFemConstraintFixed::TaskFemConstraintFixed(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintForce::TaskFemConstraintForce(), FemGui::TaskFemConstraintHeatflux::TaskFemConstraintHeatflux(), FemGui::TaskFemConstraintInitialTemperature::TaskFemConstraintInitialTemperature(), FemGui::TaskFemConstraintPlaneRotation::TaskFemConstraintPlaneRotation(), FemGui::TaskFemConstraintPressure::TaskFemConstraintPressure(), FemGui::TaskFemConstraintTemperature::TaskFemConstraintTemperature(), FemGui::TaskFemConstraintTransform::TaskFemConstraintTransform(), and App::PropertyXLinkSubList::upgrade().
getValue()
DocumentObject * PropertyLinkSubList::getValue (void) const
getValue emulates the action of a single-object link.
Returns
reference to object, if the link is to only one object. NULL if the link is empty, or links to subelements of more than one document object.
Referenced by TechDraw::DrawViewDimExtent::execute(), PartDesignGui::fixSketchSupport(), PartDesign::ProfileBased::getBaseObject(), PartDesign::ProfileBased::getSupportFace(), PartDesign::ProfileBased::positionByPrevious(), and SketcherGui::SketchSelection::setUp().
getValues()
const std::vector<DocumentObject*>& App::PropertyLinkSubList::getValues (void) const
Referenced by PartDesignGui::TaskDlgDatumParameters::accept(), TechDraw::DrawViewDimension::checkReferences2D(), TechDrawGui::TaskLinkDim::dimReferencesSelection(), Surface::Cut::execute(), Surface::Sections::execute(), TechDraw::LandmarkDimension::execute(), TechDrawGui::QGVPage::findParent(), TechDraw::LandmarkDimension::get2DPoints(), Fem::Constraint::getCylinder(), PartDesign::ShapeBinder::getFilteredReferences(), Fem::Constraint::getPoints(), TechDraw::DrawViewDimension::getViewPart(), TechDraw::LandmarkDimension::getViewPart(), TechDraw::DrawViewDimension::has2DReferences(), TechDraw::LandmarkDimension::has2DReferences(), Fem::Constraint::onChanged(), TechDraw::DrawViewDimension::onChanged(), TechDraw::LandmarkDimension::onDocumentRestored(), FemGui::TaskFemConstraint::onReferenceDeleted(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), SurfaceGui::FillingEdgePanel::onSelectionChanged(), SurfaceGui::FillingVertexPanel::onSelectionChanged(), SurfaceGui::GeomFillSurface::onSelectionChanged(), Attacher::AttachEngine::readLinks(), PartDesignGui::relinkToBody(), TechDraw::DrawViewDimension::setAll3DMeasurement(), SurfaceGui::FillingPanel::setEditedObject(), SurfaceGui::FillingEdgePanel::setEditedObject(), SurfaceGui::FillingVertexPanel::setEditedObject(), SurfaceGui::GeomFillSurface::setEditedObject(), SurfaceGui::SectionsPanel::setEditedObject(), FemGui::TaskFemConstraintBearing::TaskFemConstraintBearing(), FemGui::TaskFemConstraintContact::TaskFemConstraintContact(), FemGui::TaskFemConstraintDisplacement::TaskFemConstraintDisplacement(), FemGui::TaskFemConstraintFixed::TaskFemConstraintFixed(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintForce::TaskFemConstraintForce(), FemGui::TaskFemConstraintHeatflux::TaskFemConstraintHeatflux(), FemGui::TaskFemConstraintInitialTemperature::TaskFemConstraintInitialTemperature(), FemGui::TaskFemConstraintPlaneRotation::TaskFemConstraintPlaneRotation(), FemGui::TaskFemConstraintPressure::TaskFemConstraintPressure(), FemGui::TaskFemConstraintTemperature::TaskFemConstraintTemperature(), FemGui::TaskFemConstraintTransform::TaskFemConstraintTransform(), Part::Part2DObject::transformPlacement(), App::PropertyXLinkSubList::upgrade(), and Attacher::AttachEngine::verifyReferencesAreSafe().
onContainerRestored()
void PropertyLinkSubList::onContainerRestored () override virtual
Called before calling DocumentObject::onDocumentRestored()
This function is called after finished calling Property::afterRestore() of all properties of objects. By then, the object dependency information is assumed ready. So, unlike Property::afterRestore(), this function is called on objects with dependency order.
Reimplemented from App::Property.
References App::PropertyLinkBase::unregisterElementReference().
Paste()
void PropertyLinkSubList::Paste (const Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References Base::Persistence::getClassTypeId(), Base::BaseClass::isDerivedFrom(), and setValues().
Referenced by Attacher::AttachEngine::setUp(), and Attacher::AttachEnginePy::writeParametersToFeature().
referenceChanged()
bool PropertyLinkSubList::referenceChanged () const override virtual
Test if the element reference has changed after restore.
Reimplemented from App::PropertyLinkBase.
removeValue()
int PropertyLinkSubList::removeValue (App::DocumentObject * lValue)
Removes all occurrences of lValue in the property together with its sub-elements and returns the number of entries removed.
References setValues().
Restore()
void PropertyLinkSubList::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References Base::Console(), Base::XMLReader::getAttribute(), Base::XMLReader::getAttributeAsInteger(), App::Property::getContainer(), App::DocumentObject::getDocument(), Base::XMLReader::getName(), App::Document::getObject(), Base::XMLReader::hasAttribute(), App::PropertyLinkBase::importSubName(), Base::XMLReader::isVerbose(), App::PropertyLinkBase::LinkRestoreLabel, draftfunctions.move::move(), Base::XMLReader::readElement(), Base::XMLReader::readEndElement(), App::PropertyLinkBase::setFlag(), setValues(), and Base::ConsoleSingleton::Warning().
Referenced by PartDesign::ShapeBinder::handleChangedPropertyType(), and App::PropertyXLinkSubList::upgrade().
Save()
void PropertyLinkSubList::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References Base::Writer::decInd(), App::PropertyLinkBase::exportSubName(), App::Property::getContainer(), getSize(), Base::Writer::incInd(), Base::Writer::ind(), and Base::Writer::Stream().
setPyObject()
void PropertyLinkSubList::setPyObject (PyObject * value) override virtual
Reimplemented from Base::BaseClass.
References App::DocumentObjectPy::getDocumentObjectPtr(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), App::PropertyString::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyString::setPyObject(), App::PropertyLinkSub::setPyObject(), App::PropertyListsT< T, ListT, ParentT >::setPyObject(), setValue(), setValues(), and App::DocumentObjectPy::Type.
Referenced by Attacher::AttachEnginePy::setReferences().
setSize()
void PropertyLinkSubList::setSize (int newSize)
setSubListValues()
void PropertyLinkSubList::setSubListValues (const std::vector< SubSet > & values)
References setValues().
setValue() [1/2]
void PropertyLinkSubList::setValue (App::DocumentObject * lValue, const std::vector< std::string > & SubList = std::vector<std::string>())
setValue: PropertyLinkSub-compatible overload
Parameters
SubList
References App::Property::aboutToSetValue(), App::PropertyLinkBase::checkLabelReferences(), App::Property::getContainer(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::PropertyLinkBase::hasSetValue(), App::Hidden, App::PropertyLinkBase::LinkAllowExternal, App::PropertyLinkBase::testFlag(), and updateElementReference().
setValue() [2/2]
void PropertyLinkSubList::setValue (DocumentObject * lValue, const char * SubName)
Sets the property.
setValue(0, whatever) clears the property
References App::Property::aboutToSetValue(), App::PropertyLinkBase::checkLabelReferences(), App::Property::getContainer(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::PropertyLinkBase::hasSetValue(), App::Hidden, App::PropertyLinkBase::LinkAllowExternal, App::PropertyLinkBase::testFlag(), and updateElementReference().
Referenced by TechDraw::LandmarkDimension::execute(), Attacher::AttachEngine::getShapeType(), PartDesignGui::TaskFeaturePick::makeCopy(), TechDraw::DrawDimHelper::makeExtentDim(), setPyObject(), and TechDrawGui::TaskLinkDim::updateDims().
setValues() [1/3]
void PropertyLinkSubList::setValues (const std::vector< DocumentObject * > & lValue, const std::vector< const char * > & lSubNames)
References App::Property::aboutToSetValue(), App::PropertyLinkBase::checkLabelReferences(), App::Property::getContainer(), App::PropertyLinkBase::hasSetValue(), App::Hidden, App::PropertyLinkBase::LinkAllowExternal, App::PropertyLinkBase::testFlag(), and updateElementReference().
Referenced by PartDesignGui::TaskDlgDatumParameters::accept(), adjustLink(), breakLink(), Gui::SelectionSingleton::getAsPropertyLinkSubList(), TechDraw::DrawDimHelper::makeDistDim(), FemGui::TaskFemConstraint::onReferenceDeleted(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), SurfaceGui::FillingEdgePanel::onSelectionChanged(), SurfaceGui::FillingVertexPanel::onSelectionChanged(), SurfaceGui::GeomFillSurface::onSelectionChanged(), Paste(), removeValue(), Restore(), setPyObject(), setSubListValues(), setValues(), and TechDrawGui::TaskLinkDim::updateDims().
setValues() [2/3]
void PropertyLinkSubList::setValues (const std::vector< DocumentObject * > & lValue, const std::vector< std::string > & lSubNames, std::vector< ShadowSub > && ShadowSubList = {})
References draftfunctions.move::move(), and setValues().
setValues() [3/3]
void PropertyLinkSubList::setValues (std::vector< DocumentObject * > && lValue, std::vector< std::string > && subs, std::vector< ShadowSub > && ShadowSubList = {})
References App::Property::aboutToSetValue(), App::PropertyLinkBase::checkLabelReferences(), App::Property::getContainer(), App::PropertyLinkBase::hasSetValue(), App::Hidden, App::PropertyLinkBase::LinkAllowExternal, draftfunctions.move::move(), App::PropertyLinkBase::testFlag(), and updateElementReference().
updateElementReference()
void PropertyLinkSubList::updateElementReference (DocumentObject * feature, bool reverse = false, bool notify = false) override virtual
Link type property interface APIs These APIs are moved here so that any type of property can have the property link behavior, e.g.
the PropertyExpressionEngine Called to update the element reference of this link property
See also
_updateElementReference()
Reimplemented from App::PropertyLinkBase.
References App::Property::getContainer(), App::PropertyLinkBase::hasSetValue(), femsolver.signal::notify(), and App::PropertyLinkBase::unregisterElementReference().
Referenced by setValue(), and setValues().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/App/PropertyLinks.h
Sources/FreeCAD/src/App/PropertyLinks.cpp