FreeCAD: Gui::TextEdit Class Reference
Gui::TextEdit Class Reference
#include <TextEdit.h>
Signals
void findNext ()
void findPrevious ()
void showSearchBar ()
Public Member Functions
TextEdit (QWidget *parent=nullptr)
Constructs a TextEdit which is a child of 'parent'.
virtual ~TextEdit ()
Destroys the object and frees any allocated resources.
Protected Member Functions
void keyPressEvent (QKeyEvent *)
Set the approproriate item of the completion box or hide it, if needed.
Constructor & Destructor Documentation
TextEdit()
TextEdit::TextEdit (QWidget * parent = nullptr)
Constructs a TextEdit which is a child of 'parent'.
References draftgeoutils.intersections::connect(), findNext(), findPrevious(), and showSearchBar().
~TextEdit()
TextEdit::~TextEdit () virtual
Destroys the object and frees any allocated resources.
Member Function Documentation
findNext
void Gui::TextEdit::findNext () signal
Referenced by TextEdit().
findPrevious
void Gui::TextEdit::findPrevious () signal
Referenced by TextEdit().
keyPressEvent()
void TextEdit::keyPressEvent (QKeyEvent * e) protected
Set the approproriate item of the completion box or hide it, if needed.
Referenced by Gui::PythonConsole::keyPressEvent(), and Gui::TextEditor::keyPressEvent().
showSearchBar
void Gui::TextEdit::showSearchBar () signal
Referenced by TextEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/TextEdit.h
FreeCAD/src/Gui/TextEdit.cpp