FreeCAD: TechDrawGui::Ui_TaskProjection Class Reference
TechDrawGui::Ui_TaskProjection Class Reference
#include <ui_TaskProjection.h>
Public Member Functions
void retranslateUi (QWidget *TechDrawGui__TaskProjection)
void setupUi (QWidget *TechDrawGui__TaskProjection)
Public Attributes
QCheckBox * cbHidIso
QCheckBox * cbHidOutline
QCheckBox * cbHidSewn
QCheckBox * cbHidSharp
QCheckBox * cbHidSmooth
QCheckBox * cbVisIso
QCheckBox * cbVisOutline
QCheckBox * cbVisSewn
QCheckBox * cbVisSharp
QCheckBox * cbVisSmooth
QVBoxLayout * verticalLayout
QVBoxLayout * verticalLayout_2
Member Function Documentation
retranslateUi()
void TechDrawGui::Ui_TaskProjection::retranslateUi (QWidget * TechDrawGui__TaskProjection)
References cbHidIso, cbHidOutline, cbHidSewn, cbHidSharp, cbHidSmooth, cbVisIso, cbVisOutline, cbVisSewn, cbVisSharp, cbVisSmooth, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void TechDrawGui::Ui_TaskProjection::setupUi (QWidget * TechDrawGui__TaskProjection)
References cbHidIso, cbHidOutline, cbHidSewn, cbHidSharp, cbHidSmooth, cbVisIso, cbVisOutline, cbVisSewn, cbVisSharp, cbVisSmooth, retranslateUi(), verticalLayout, and verticalLayout_2.
Member Data Documentation
cbHidIso
QCheckBox* TechDrawGui::Ui_TaskProjection::cbHidIso
Referenced by retranslateUi(), and setupUi().
cbHidOutline
QCheckBox* TechDrawGui::Ui_TaskProjection::cbHidOutline
Referenced by retranslateUi(), and setupUi().
cbHidSewn
QCheckBox* TechDrawGui::Ui_TaskProjection::cbHidSewn
Referenced by retranslateUi(), and setupUi().
cbHidSharp
QCheckBox* TechDrawGui::Ui_TaskProjection::cbHidSharp
Referenced by retranslateUi(), and setupUi().
cbHidSmooth
QCheckBox* TechDrawGui::Ui_TaskProjection::cbHidSmooth
Referenced by retranslateUi(), and setupUi().
cbVisIso
QCheckBox* TechDrawGui::Ui_TaskProjection::cbVisIso
Referenced by retranslateUi(), and setupUi().
cbVisOutline
QCheckBox* TechDrawGui::Ui_TaskProjection::cbVisOutline
Referenced by retranslateUi(), and setupUi().
cbVisSewn
QCheckBox* TechDrawGui::Ui_TaskProjection::cbVisSewn
Referenced by retranslateUi(), and setupUi().
cbVisSharp
QCheckBox* TechDrawGui::Ui_TaskProjection::cbVisSharp
Referenced by retranslateUi(), and setupUi().
cbVisSmooth
QCheckBox* TechDrawGui::Ui_TaskProjection::cbVisSmooth
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* TechDrawGui::Ui_TaskProjection::verticalLayout
Referenced by setupUi().
verticalLayout_2
QVBoxLayout* TechDrawGui::Ui_TaskProjection::verticalLayout_2
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/TechDraw/Gui/ui_TaskProjection.h