FreeCAD: PartGui::DlgSettings3DViewPart Class Reference
PartGui::DlgSettings3DViewPart Class Reference
The DlgSettings3DViewPartImp class implements a preference page to change settings for the Inventor viewer.
#include <DlgSettings3DViewPartImp.h>
Public Member Functions
DlgSettings3DViewPart (QWidget *parent=nullptr)
Constructs a DlgSettings3DViewPart which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
~DlgSettings3DViewPart ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void loadSettings ()
void saveSettings ()
virtual void changeEvent (QEvent *e)=0
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Detailed Description
The DlgSettings3DViewPartImp class implements a preference page to change settings for the Inventor viewer.
Author
Jürgen Riegel
Constructor & Destructor Documentation
DlgSettings3DViewPart()
DlgSettings3DViewPart::DlgSettings3DViewPart (QWidget * parent = nullptr)
Constructs a DlgSettings3DViewPart which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
References App::GetApplication(), ParameterGrp::GetFloat(), and App::Application::GetParameterGroupByPath().
~DlgSettings3DViewPart()
DlgSettings3DViewPart::~DlgSettings3DViewPart ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void DlgSettings3DViewPart::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
loadSettings()
void DlgSettings3DViewPart::loadSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
saveSettings()
void DlgSettings3DViewPart::saveSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), Base::Persistence::getClassTypeId(), Gui::Application::getDocument(), App::Application::getDocuments(), Gui::Application::Instance, and PartGui::ViewProviderPartExt::reload().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/DlgSettings3DViewPartImp.h
FreeCAD/src/Mod/Part/Gui/DlgSettings3DViewPartImp.cpp