FreeCAD: Gui::RecoveryRunnable Class Reference
Gui::RecoveryRunnable Class Reference
Public Member Functions
RecoveryRunnable (const std::set< std::string > &modes, const char *dir, const char *file, const App::Property *p)
virtual void run ()
virtual ~RecoveryRunnable ()
Constructor & Destructor Documentation
RecoveryRunnable()
Gui::RecoveryRunnable::RecoveryRunnable (const std::set< std::string > & modes, const char * dir, const char * file, const App::Property * p)
References Base::FileWriter::putNextEntry(), and Base::Writer::setModes().
~RecoveryRunnable()
virtual Gui::RecoveryRunnable::~RecoveryRunnable () virtual
Member Function Documentation
run()
virtual void Gui::RecoveryRunnable::run () virtual
References Base::FileWriter::close(), Gui::AutoSaver::instance(), and Base::Persistence::SaveDocFile().
Referenced by femexamples.examplesgui.FemExamples::clicked(), and femsolver.task.Task::protector().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/AutoSaver.cpp