FreeCAD: TechDrawGui::QGIDatumLabel Class Reference
TechDrawGui::QGIDatumLabel Class Reference
#include <QGIViewDimension.h>
Public Types
enum { Type = QGraphicsItem::UserType + 107 }
Signals
void dragFinished ()
void dragging (bool)
void hover (bool state)
void selected (bool state)
void setPretty (int state)
Public Member Functions
virtual QRectF boundingRect () const override
QGCustomText * getDimText (void)
QFont getFont (void)
double getLineWidth (void)
double getTolAdjust (void)
QGCustomText * getTolTextOver (void)
QGCustomText * getTolTextUnder (void)
bool isFramed (void)
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QGIDatumLabel ()
void setColor (QColor c)
void setDimString (QString t)
void setDimString (QString t, qreal maxWidth)
void setDimText (QGCustomText *newText)
void setFont (QFont f)
void setFramed (bool framed)
void setLabelCenter ()
void setLineWidth (double lineWidth)
void setPosFromCenter (const double &xCenter, const double &yCenter)
void setPrettyNormal (void)
void setPrettyPre (void)
void setPrettySel (void)
void setToleranceString ()
void setTolTextOver (QGCustomText *newTol)
void setTolTextUnder (QGCustomText *newTol)
void setUnitString (QString t)
int type () const override
double X () const
double Y () const
virtual ~QGIDatumLabel ()=default
Public Attributes
QGIViewDimension * parent
std::vector< int > seps
bool verticalSep
Protected Member Functions
int getPrecision (void)
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) override
Protected Attributes
QColor m_colNormal
bool m_ctrl
QGCustomText * m_dimText
bool m_isFramed
double m_lineWidth
QGCustomText * m_tolTextOver
QGCustomText * m_tolTextUnder
QGCustomText * m_unitText
double posX
double posY
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGIDatumLabel()
QGIDatumLabel::QGIDatumLabel ()
References TechDrawGui::Rez::guiX(), m_ctrl, m_dimText, m_isFramed, m_lineWidth, m_tolTextOver, m_tolTextUnder, m_unitText, parent, posX, posY, TechDrawGui::QGCustomText::setTightBounding(), and verticalSep.
~QGIDatumLabel()
virtual TechDrawGui::QGIDatumLabel::~QGIDatumLabel () virtual default
Member Function Documentation
boundingRect()
QRectF QGIDatumLabel::boundingRect () const override virtual
References m_lineWidth.
Referenced by TechDrawGui::QGIViewDimension::boundingRect(), TechDrawGui::QGIViewDimension::drawAngle(), TechDrawGui::QGIViewDimension::drawDiameter(), TechDrawGui::QGIViewDimension::drawDistance(), TechDrawGui::QGIViewDimension::drawDistanceExecutive(), TechDrawGui::QGIViewDimension::drawDistanceOverride(), TechDrawGui::QGIViewDimension::drawRadius(), TechDrawGui::QGIViewDimension::drawRadiusExecutive(), and paint().
dragFinished
void TechDrawGui::QGIDatumLabel::dragFinished () signal
Referenced by mouseReleaseEvent().
dragging
void TechDrawGui::QGIDatumLabel::dragging (bool) signal
Referenced by itemChange().
getDimText()
QGCustomText * TechDrawGui::QGIDatumLabel::getDimText (void)
References m_dimText.
Referenced by TechDrawGui::QGIViewDimension::getLabelText().
getFont()
QFont TechDrawGui::QGIDatumLabel::getFont (void)
References m_dimText.
Referenced by TechDrawGui::QGIViewDimension::updateDim().
getLineWidth()
double TechDrawGui::QGIDatumLabel::getLineWidth (void)
References m_lineWidth.
getPrecision()
int QGIDatumLabel::getPrecision (void) protected
References App::GetApplication(), Base::UnitsApi::getDecimals(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), App::Application::GetUserParameter(), and draftgeoutils.general::precision().
getTolAdjust()
double QGIDatumLabel::getTolAdjust (void)
References App::GetApplication(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by setFont().
getTolTextOver()
QGCustomText * TechDrawGui::QGIDatumLabel::getTolTextOver (void)
References m_tolTextOver.
Referenced by TechDrawGui::QGIViewDimension::getLabelText().
getTolTextUnder()
QGCustomText * TechDrawGui::QGIDatumLabel::getTolTextUnder (void)
References m_tolTextUnder.
Referenced by TechDrawGui::QGIViewDimension::getLabelText().
hover
void TechDrawGui::QGIDatumLabel::hover (bool state) signal
Referenced by hoverEnterEvent(), and hoverLeaveEvent().
hoverEnterEvent()
void QGIDatumLabel::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected virtual
References hover(), setPrettyPre(), and setPrettySel().
hoverLeaveEvent()
void QGIDatumLabel::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected virtual
References hover(), setPrettyNormal(), and setPrettySel().
isFramed()
bool TechDrawGui::QGIDatumLabel::isFramed (void)
References m_isFramed.
itemChange()
QVariant QGIDatumLabel::itemChange (GraphicsItemChange change, const QVariant & value) override protected virtual
References dragging(), m_ctrl, setLabelCenter(), setPrettyNormal(), and setPrettySel().
mouseDoubleClickEvent()
void QGIDatumLabel::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override protected virtual
References TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), and Gui::ViewProviderDocumentObject::startDefaultEditMode().
mouseMoveEvent()
void QGIDatumLabel::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override protected virtual
mousePressEvent()
void QGIDatumLabel::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected virtual
References m_ctrl.
mouseReleaseEvent()
void QGIDatumLabel::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override virtual
References dragFinished(), and m_ctrl.
paint()
void QGIDatumLabel::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override virtual
References boundingRect(), m_dimText, m_isFramed, and m_lineWidth.
selected
void TechDrawGui::QGIDatumLabel::selected (bool state) signal
Referenced by PathScripts.PathDressupTagGui.HoldingTagMarker::setEnabled(), and PathScripts.PathDressupTagGui.HoldingTagMarker::setSelected().
setColor()
void QGIDatumLabel::setColor (QColor c)
References m_colNormal, m_dimText, m_tolTextOver, m_tolTextUnder, m_unitText, and TechDrawGui::QGCustomText::setColor().
Referenced by TechDrawGui::QGIViewDimension::setNormalColorAll().
setDimString() [1/2]
void QGIDatumLabel::setDimString (QString t)
References m_dimText.
Referenced by TechDrawGui::QGIViewDimension::updateDim().
setDimString() [2/2]
void QGIDatumLabel::setDimString (QString t, qreal maxWidth)
References m_dimText.
setDimText()
void TechDrawGui::QGIDatumLabel::setDimText (QGCustomText * newText)
References m_dimText.
setFont()
void QGIDatumLabel::setFont (QFont f)
References getTolAdjust(), m_dimText, m_tolTextOver, m_tolTextUnder, and m_unitText.
Referenced by TechDrawGui::QGIViewDimension::updateDim().
setFramed()
void TechDrawGui::QGIDatumLabel::setFramed (bool framed)
References m_isFramed.
Referenced by TechDrawGui::QGIViewDimension::updateDim().
setLabelCenter()
void QGIDatumLabel::setLabelCenter ()
References TechDrawGui::QGCustomText::boundingRect(), m_dimText, posX, and posY.
Referenced by itemChange().
setLineWidth()
void TechDrawGui::QGIDatumLabel::setLineWidth (double lineWidth)
References m_lineWidth.
Referenced by TechDrawGui::QGIViewDimension::updateDim().
setPosFromCenter()
void QGIDatumLabel::setPosFromCenter (const double & xCenter, const double & yCenter)
References TechDrawGui::QGCustomText::boundingRect(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGCustomText::justifyRightAt(), m_dimText, m_tolTextOver, m_tolTextUnder, m_unitText, and TechDrawGui::QGCustomText::tightBoundingAdjust().
Referenced by TechDrawGui::QGIViewDimension::setViewPartFeature(), TechDrawGui::QGIViewDimension::updateDim(), and TechDrawGui::QGIViewDimension::updateView().
setPretty
void TechDrawGui::QGIDatumLabel::setPretty (int state) signal
Referenced by setPrettyNormal(), setPrettyPre(), and setPrettySel().
setPrettyNormal()
void QGIDatumLabel::setPrettyNormal (void)
References m_dimText, m_tolTextOver, m_tolTextUnder, m_unitText, setPretty(), and TechDrawGui::QGCustomText::setPrettyNormal().
Referenced by hoverLeaveEvent(), and itemChange().
setPrettyPre()
void QGIDatumLabel::setPrettyPre (void)
References m_dimText, m_tolTextOver, m_tolTextUnder, m_unitText, setPretty(), and TechDrawGui::QGCustomText::setPrettyPre().
Referenced by hoverEnterEvent().
setPrettySel()
void QGIDatumLabel::setPrettySel (void)
References m_dimText, m_tolTextOver, m_tolTextUnder, m_unitText, setPretty(), and TechDrawGui::QGCustomText::setPrettySel().
Referenced by hoverEnterEvent(), hoverLeaveEvent(), and itemChange().
setToleranceString()
void QGIDatumLabel::setToleranceString ()
References TechDrawGui::QGIView::getViewObject(), m_tolTextOver, and m_tolTextUnder.
Referenced by TechDrawGui::QGIViewDimension::updateDim().
setTolTextOver()
void TechDrawGui::QGIDatumLabel::setTolTextOver (QGCustomText * newTol)
References m_tolTextOver.
setTolTextUnder()
void TechDrawGui::QGIDatumLabel::setTolTextUnder (QGCustomText * newTol)
References m_tolTextOver.
setUnitString()
void QGIDatumLabel::setUnitString (QString t)
References m_unitText.
type()
int TechDrawGui::QGIDatumLabel::type (void) const override
References Type.
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
X()
double TechDrawGui::QGIDatumLabel::X () const
References posX.
Referenced by TechDrawGui::QGIViewDimension::datumLabelDragFinished(), PathMachineState.MachineState::getPosition(), PathMachineState.MachineState::getState(), and TechDrawGui::QGIViewDimension::updateDim().
Y()
double TechDrawGui::QGIDatumLabel::Y () const
References posY.
Referenced by TechDrawGui::QGIViewDimension::datumLabelDragFinished(), PathMachineState.MachineState::getPosition(), PathMachineState.MachineState::getState(), and TechDrawGui::QGIViewDimension::updateDim().
Member Data Documentation
m_colNormal
QColor TechDrawGui::QGIDatumLabel::m_colNormal protected
Referenced by setColor().
m_ctrl
bool TechDrawGui::QGIDatumLabel::m_ctrl protected
Referenced by itemChange(), mousePressEvent(), mouseReleaseEvent(), and QGIDatumLabel().
m_dimText
QGCustomText* TechDrawGui::QGIDatumLabel::m_dimText protected
Referenced by getDimText(), getFont(), paint(), QGIDatumLabel(), setColor(), setDimString(), setDimText(), setFont(), setLabelCenter(), setPosFromCenter(), setPrettyNormal(), setPrettyPre(), and setPrettySel().
m_isFramed
bool TechDrawGui::QGIDatumLabel::m_isFramed protected
Referenced by isFramed(), paint(), QGIDatumLabel(), and setFramed().
m_lineWidth
double TechDrawGui::QGIDatumLabel::m_lineWidth protected
Referenced by boundingRect(), getLineWidth(), paint(), QGIDatumLabel(), and setLineWidth().
m_tolTextOver
QGCustomText* TechDrawGui::QGIDatumLabel::m_tolTextOver protected
Referenced by getTolTextOver(), QGIDatumLabel(), setColor(), setFont(), setPosFromCenter(), setPrettyNormal(), setPrettyPre(), setPrettySel(), setToleranceString(), setTolTextOver(), and setTolTextUnder().
m_tolTextUnder
QGCustomText* TechDrawGui::QGIDatumLabel::m_tolTextUnder protected
Referenced by getTolTextUnder(), QGIDatumLabel(), setColor(), setFont(), setPosFromCenter(), setPrettyNormal(), setPrettyPre(), setPrettySel(), and setToleranceString().
m_unitText
QGCustomText* TechDrawGui::QGIDatumLabel::m_unitText protected
Referenced by QGIDatumLabel(), setColor(), setFont(), setPosFromCenter(), setPrettyNormal(), setPrettyPre(), setPrettySel(), and setUnitString().
parent
QGIViewDimension* TechDrawGui::QGIDatumLabel::parent
Referenced by PathScripts.PathSimulatorGui.CAMSimTaskUi::accept(), Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium(), QGIDatumLabel(), PathScripts.PathSimulatorGui.CAMSimTaskUi::reject(), and PathScripts.PathOpGui.TaskPanelPage::setParent().
posX
double TechDrawGui::QGIDatumLabel::posX protected
Referenced by QGIDatumLabel(), setLabelCenter(), and X().
posY
double TechDrawGui::QGIDatumLabel::posY protected
Referenced by QGIDatumLabel(), setLabelCenter(), and Y().
seps
std::vector<int> TechDrawGui::QGIDatumLabel::seps
verticalSep
bool TechDrawGui::QGIDatumLabel::verticalSep
Referenced by QGIDatumLabel().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/QGIViewDimension.h
FreeCAD/src/Mod/TechDraw/Gui/QGIViewDimension.cpp