FreeCAD: PartDesignGui::TaskDlgThicknessParameters Class Reference
PartDesignGui::TaskDlgThicknessParameters Class Reference
simulation dialog for the TaskView
#include <TaskThicknessParameters.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
TaskDlgThicknessParameters (ViewProviderThickness *ThicknessView)
~TaskDlgThicknessParameters ()
Public Member Functions inherited from PartDesignGui::TaskDlgDressUpParameters
ViewProviderDressUp * getDressUpView () const
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgDressUpParameters (ViewProviderDressUp *DressUpView)
virtual ~TaskDlgDressUpParameters ()
Public Member Functions inherited from PartDesignGui::TaskDlgFeatureParameters
TaskDlgFeatureParameters (PartDesignGui::ViewProvider *vp)
PartDesignGui::ViewProvider * viewProvider () const
Returns the view provider dialog is runed for.
virtual ~TaskDlgFeatureParameters ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
tells the framework which buttons are wished for the dialog
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from PartDesignGui::TaskDlgDressUpParameters
TaskDressUpParameters * parameter
Protected Attributes inherited from PartDesignGui::TaskDlgFeatureParameters
PartDesignGui::ViewProvider * vp
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
simulation dialog for the TaskView
Constructor & Destructor Documentation
TaskDlgThicknessParameters()
TaskDlgThicknessParameters::TaskDlgThicknessParameters (ViewProviderThickness * ThicknessView)
References Gui::TaskView::TaskDialog::Content, and PartDesignGui::TaskDlgDressUpParameters::parameter.
~TaskDlgThicknessParameters()
TaskDlgThicknessParameters::~TaskDlgThicknessParameters ()
Member Function Documentation
accept()
bool TaskDlgThicknessParameters::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from PartDesignGui::TaskDlgDressUpParameters.
References PartDesignGui::TaskDlgDressUpParameters::accept(), PartDesignGui::TaskThicknessParameters::getIntersection(), PartDesignGui::TaskThicknessParameters::getJoinType(), PartDesignGui::TaskThicknessParameters::getMode(), Gui::ViewProviderDocumentObject::getObject(), PartDesignGui::TaskThicknessParameters::getReversed(), PartDesignGui::TaskThicknessParameters::getValue(), PartDesignGui::TaskDlgDressUpParameters::parameter, PartDesignGui::TaskDressUpParameters::showObject(), and PartDesignGui::TaskDlgFeatureParameters::vp.
Referenced by PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/PartDesign/Gui/TaskThicknessParameters.h
Sources/FreeCAD/src/Mod/PartDesign/Gui/TaskThicknessParameters.cpp