FreeCAD: Base::TimeInfo Class Reference
Base::TimeInfo Class Reference
BaseClass class and root of the type system.
#include <TimeInfo.h>
Public Member Functions
unsigned short getMiliseconds (void) const
uint64_t getSeconds (void) const
bool isNull () const
bool operator!= (const TimeInfo &time) const
bool operator< (const TimeInfo &time) const
bool operator<= (const TimeInfo &time) const
bool operator== (const TimeInfo &time) const
bool operator> (const TimeInfo &time) const
bool operator>= (const TimeInfo &time) const
void setCurrent (void)
sets the object to the actual system time
void setTime_t (uint64_t seconds)
TimeInfo ()
Construction.
virtual ~TimeInfo ()
Destruction.
Static Public Member Functions
static std::string currentDateTimeString ()
static std::string diffTime (const TimeInfo &timeStart, const TimeInfo &timeEnd=TimeInfo())
static float diffTimeF (const TimeInfo &timeStart, const TimeInfo &timeEnd=TimeInfo())
static TimeInfo null ()
Detailed Description
BaseClass class and root of the type system.
Constructor & Destructor Documentation
TimeInfo()
TimeInfo::TimeInfo ()
Construction.
A constructor.
A more elaborate description of the constructor.
References setCurrent().
~TimeInfo()
TimeInfo::~TimeInfo () virtual
Destruction.
A destructor.
A more elaborate description of the destructor.
Member Function Documentation
currentDateTimeString()
std::string TimeInfo::currentDateTimeString () static
Referenced by Cloud::Module::cloudSave(), App::Document::Document(), and App::Document::save().
diffTime()
std::string TimeInfo::diffTime (const TimeInfo & timeStart, const TimeInfo & timeEnd = TimeInfo()) static
References diffTimeF().
Referenced by Sketcher::Sketch::setUpSketch(), and Sketcher::Sketch::solve().
diffTimeF()
float TimeInfo::diffTimeF (const TimeInfo & timeStart, const TimeInfo & timeEnd = TimeInfo()) static
References getMiliseconds(), and getSeconds().
Referenced by FemGui::ViewProviderFEMMeshBuilder::createMesh(), GCS::System::diagnose(), diffTime(), Fem::FemVTKTools::readResult(), Fem::FemVTKTools::readVTKMesh(), FemGui::ViewProviderFemMeshPy::setNodeColor(), Sketcher::Sketch::solve(), PartGui::ViewProviderPartExt::updateVisual(), Fem::FemVTKTools::writeResult(), and Fem::FemVTKTools::writeVTKMesh().
getMiliseconds()
unsigned short Base::TimeInfo::getMiliseconds (void) const
Referenced by diffTimeF().
getSeconds()
uint64_t Base::TimeInfo::getSeconds (void) const
Referenced by diffTimeF().
isNull()
bool TimeInfo::isNull (void) const
References null().
null()
TimeInfo TimeInfo::null () static
Referenced by isNull(), Base::FileInfo::lastModified(), and Base::FileInfo::lastRead().
operator!=()
bool Base::TimeInfo::operator!= (const TimeInfo & time) const
operator<()
bool Base::TimeInfo::operator< (const TimeInfo & time) const
operator<=()
bool Base::TimeInfo::operator<= (const TimeInfo & time) const
operator==()
bool Base::TimeInfo::operator== (const TimeInfo & time) const
operator>()
bool Base::TimeInfo::operator> (const TimeInfo & time) const
operator>=()
bool Base::TimeInfo::operator>= (const TimeInfo & time) const
setCurrent()
void TimeInfo::setCurrent (void)
sets the object to the actual system time
Referenced by TimeInfo().
setTime_t()
void TimeInfo::setTime_t (uint64_t seconds)
Referenced by Base::FileInfo::lastModified(), and Base::FileInfo::lastRead().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Base/TimeInfo.h
Sources/FreeCAD/src/Base/TimeInfo.cpp