FreeCAD: Gui::ViewProviderDocumentObject Class Reference
Gui::ViewProviderDocumentObject Class Reference
#include <ViewProviderDocumentObject.h>
Public Member Functions
virtual void attach (App::DocumentObject *pcObject)
virtual bool canDelete (App::DocumentObject *obj) const override
Asks the view provider if the given object can be deleted.
virtual bool canDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const override
Query object dropping with full qualified name.
virtual void forceUpdate (bool enable=true)
virtual bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const override
return the coin node detail and path to the node of the subname
Gui::Document * getDocument () const
Get the GUI document to this ViewProvider object.
virtual bool getElementPicked (const SoPickedPoint *, std::string &subname) const override
return a hit element given the picked point which contains the full node path
App::DocumentObject * getObject (void) const
Get the object of this ViewProvider object.
PyObject * getPyObject () override
Get the python wrapper for that ViewProvider.
virtual void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const override
Get a list of TaskBoxes associated with this object.
virtual const char * getTransactionText () const override
Is called by the tree if the user double clicks on the object.
virtual void hide (void) override
Hide the object in the view.
virtual bool isUpdateForced () const
virtual void reattach (App::DocumentObject *)
virtual int replaceObject (App::DocumentObject *, App::DocumentObject *) override
Replace an object to the view provider by drag and drop.
void setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
virtual void show (void) override
Show the object in the view.
virtual bool showInTree () const override
Tell the tree view if this object should appear there.
virtual void update (const App::Property *) override
update the content of the ViewProvider this method have to implement the recalculation of the ViewProvider.
void updateView ()
Run a redraw.
ViewProviderDocumentObject ()
constructor.
virtual ~ViewProviderDocumentObject ()
destructor.
Public Member Functions inherited from Gui::ViewProvider
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual std::vector< App::DocumentObject * > claimChildren3D (void) const
deliver the children belonging to this object this method is used to deliver the objects to the 3DView which should be grouped under its scene graph.
SoSeparator * getAnnotation (void)
virtual SoSeparator * getBackRoot (void) const
virtual SoGroup * getChildRoot (void) const
virtual SoSeparator * getFrontRoot (void) const
SoSwitch * getModeSwitch (void) const
virtual SoSeparator * getRoot (void) const
SoTransform * getTransformNode () const
ViewProvider ()
constructor.
virtual ~ViewProvider ()
destructor.
virtual bool useNewSelectionModel (void) const
indicates if the ViewProvider use the new Selection model
virtual bool isSelectable (void) const
virtual std::string getElement (const SoDetail *) const
return a hit element to the selection path or 0
virtual SoDetail * getDetail (const char *) const
return the coin node detail of the subelement
int partialRender (const std::vector< std::string > &subelements, bool clear)
partial rendering setup
virtual std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const
virtual std::vector< Base::Vector3d > getSelectionShape (const char *Element) const
return the highlight lines for a given element or the whole shape
Base::BoundBox3d getBoundingBox (const char *subname=nullptr, bool transform=true, MDIView *view=nullptr) const
Return the bound box of this view object.
virtual bool onDelete (const std::vector< std::string > &subNames)
Get called if the object is about to get deleted.
virtual void beforeDelete ()
Called before deletion.
virtual bool canDragObjects () const
Check whether children can be removed from the view provider by drag and drop.
virtual bool canDragObject (App::DocumentObject *) const
Check whether the object can be removed from the view provider by drag and drop.
virtual void dragObject (App::DocumentObject *)
Remove a child from the view provider by drag and drop.
virtual bool canDropObjects () const
Check whether objects can be added to the view provider by drag and drop or drop only.
virtual bool canDropObject (App::DocumentObject *) const
Check whether the object can be dropped to the view provider by drag and drop or drop only.
virtual bool canDragAndDropObject (App::DocumentObject *) const
Return false to force drop only operation for a given object.
virtual void dropObject (App::DocumentObject *)
Add an object to the view provider by drag and drop.
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
Add an object with full qualified name to the view provider by drag and drop.
virtual bool canRemoveChildrenFromRoot () const
Tell the tree view to remove children items from the tree root.
std::string getActiveDisplayMode (void) const
virtual void setDisplayMode (const char *ModeName)
set the display mode
virtual const char * getDefaultDisplayMode () const
get the default display mode
virtual std::vector< std::string > getDisplayModes (void) const
returns a list of all possible display modes
virtual bool isShow (void) const
checks whether the view provider is visible or not
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
virtual void setOverrideMode (const std::string &mode)
Overrides the display mode with mode.
const std::string getOverrideMode ()
virtual bool keyPressed (bool pressed, int key)
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
virtual bool doubleClicked (void)
is called by the tree if the user double clicks on the object
virtual bool mouseMove (const SbVec2s &cursorPos, View3DInventorViewer *viewer)
is called when the provider is in edit and the mouse is moved
virtual bool mouseButtonPressed (int button, bool pressed, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
is called when the Provider is in edit and the mouse is clicked
virtual bool mouseWheelEvent (int delta, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
virtual void setupContextMenu (QMenu *, QObject *, const char *)
set up the context-menu with the supported edit modes
virtual ViewProvider * startEditing (int ModNum=0)
bool isEditing () const
void finishEditing ()
virtual void setEditViewer (View3DInventorViewer *, int ModNum)
adjust viewer settings when editing a view provider
virtual void unsetEditViewer (View3DInventorViewer *)
restores viewer settings when leaving editing mode
virtual void updateData (const App::Property *)
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
virtual QIcon getIcon (void) const
deliver the icon shown in the tree view
virtual QIcon mergeColorfulOverlayIcons (const QIcon &orig) const
virtual std::vector< App::DocumentObject * > claimChildren (void) const
deliver the children belonging to this object this method is used to deliver the objects to the tree framework which should be grouped under its label.
virtual std::map< std::string, App::Color > getElementColors (const char *element=nullptr) const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
virtual MDIView * getMDIView () const
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
virtual const char * detachFromDocument ()
virtual bool isAttachedToDocument () const
TransactionalObject (void)
Constructor.
virtual ~TransactionalObject ()
Public Member Functions inherited from App::ExtensionContainer
ExtensionIterator extensionBegin ()
ExtensionContainer ()
ExtensionIterator extensionEnd ()
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
void registerExtension (Base::Type extension, App::Extension *ext)
virtual ~ExtensionContainer ()
virtual Property * getPropertyByName (const char *name) const override
find a property by its name
virtual const char * getPropertyName (const Property *prop) const override
get the name of a property
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
virtual void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
virtual short getPropertyType (const Property *prop) const override
get the Type of a Property
virtual short getPropertyType (const char *name) const override
get the Type of a named Property
virtual const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
Public Member Functions inherited from App::PropertyContainer
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false)
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual void editProperty (const char *)
virtual App::Property * getDynamicPropertyByName (const char *name) const
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual std::string getFullName () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Property * getPropertyByName (const char *name) const
find a property by its name
virtual const char * getPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * getPropertyGroup (const Property *prop) const
get the Group of a Property
virtual void getPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual const char * getPropertyName (const Property *prop) const
get the name of a property
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
const char * getPropertyPrefix () const
virtual short getPropertyType (const char *name) const
get the Type of a named Property
virtual short getPropertyType (const Property *prop) const
get the Type of a Property
bool isHidden (const char *name) const
check if the named property is hidden
bool isHidden (const Property *prop) const
check if the property is hidden
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isReadOnly (const Property *prop) const
check if the property is read-only
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus)
PropertyContainer ()
A constructor.
virtual bool removeDynamicProperty (const char *name)
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
void setPropertyPrefix (const char *prefix)
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
virtual ~PropertyContainer ()
A destructor.
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Attributes
App::PropertyEnumeration DisplayMode
App::PropertyEnumeration OnTopWhenSelected
App::PropertyEnumeration SelectionStyle
App::PropertyBool ShowInTree
App::PropertyBool Visibility
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
Transaction handling
App::DocumentObject * pcObject
Gui::Document * pcDocument
class Document
virtual bool isAttachedToDocument () const override
virtual const char * detachFromDocument () override
virtual void onPropertyStatusChanged (const App::Property &prop, unsigned long oldStatus) override
get called when a property status has changed
virtual void setModeSwitch () override
Turn on mode switch.
void addDefaultAction (QMenu *, const QString &)
Adds a menu item and bind it with startDefaultEditMode().
Restoring view provider from document load
virtual void startRestoring ()
virtual void finishRestoring ()
virtual bool removeDynamicProperty (const char *prop) override
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
virtual ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=nullptr, bool recursive=false) const
Return the linked view object.
virtual std::string getFullName () const override
virtual bool allowOverride (const App::DocumentObject &) const
Allow this class to be used as an override for the original view provider of the given object.
void setShowable (bool enable)
bool isShowable () const
void startDefaultEditMode ()
Start the edit mode with ViewProvider::Default.
Gui::MDIView * getActiveView () const
Gui::MDIView * getEditingView () const
Gui::MDIView * getInventorView () const
Gui::MDIView * getViewOfNode (SoNode *node) const
virtual void onBeforeChange (const App::Property *prop) override
get called before the value is changed
virtual void onChanged (const App::Property *prop) override
Gets called by the container whenever a property has been changed.
SoNode * findFrontRootOfType (const SoType &type) const
Searches in all view providers that are attached to an object that is part of the same document as the object this view provider is attached to for an front root of type.
Additional Inherited Members
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0 , Transform , Cutting , Color }
Public Types inherited from App::ExtensionContainer
typedef std::map< Base::Type, App::Extension * >::iterator ExtensionIterator
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Protected Member Functions inherited from Gui::ViewProvider
virtual bool setEdit (int ModNum)
is called by the document when the provider goes in edit mode
virtual void unsetEdit (int ModNum)
is called when you lose the edit mode
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
virtual QIcon mergeGreyableOverlayIcons (const QIcon &orig) const
bool checkRecursion (SoNode *)
Helper method to check that the node is valid, i.e.
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
Helper method to get picked entities while editing.
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
Helper method to get picked entities while editing.
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData (void) const
virtual void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container.
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
virtual void onBeforeChange (const Property *)
get called before the value is changed
virtual void onChanged (const Property *)
get called by the container when a property has changed
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation
The root separator for annotations.
ViewProviderPy * pyViewObject
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Constructor & Destructor Documentation
ViewProviderDocumentObject()
ViewProviderDocumentObject::ViewProviderDocumentObject ()
constructor.
References App::Prop_None.
Referenced by SketcherGui::ViewProviderSketch::setEdit(), and SketcherGui::ViewProviderSketch::setEditViewer().
~ViewProviderDocumentObject()
ViewProviderDocumentObject::~ViewProviderDocumentObject () virtual
destructor.
References DisplayMode, App::Property::setContainer(), and App::PropertyEnumeration::setEnums().
Member Function Documentation
addDefaultAction()
void ViewProviderDocumentObject::addDefaultAction (QMenu * menu, const QString & text) protected
Adds a menu item and bind it with startDefaultEditMode().
References draftgeoutils.faces::bind(), Gui::ViewProvider::Default, and startDefaultEditMode().
Referenced by PartGui::ViewProviderOffset::setupContextMenu(), PartGui::ViewProviderThickness::setupContextMenu(), PartDesignGui::ViewProviderGroove::setupContextMenu(), PartDesignGui::ViewProviderHelix::setupContextMenu(), PartDesignGui::ViewProviderLoft::setupContextMenu(), PartDesignGui::ViewProviderMultiTransform::setupContextMenu(), PartDesignGui::ViewProviderPad::setupContextMenu(), PartDesignGui::ViewProviderPipe::setupContextMenu(), PartDesignGui::ViewProviderPocket::setupContextMenu(), PartDesignGui::ViewProviderRevolution::setupContextMenu(), PartDesignGui::ViewProviderBoolean::setupContextMenu(), PartDesignGui::ViewProviderHole::setupContextMenu(), and PartDesignGui::ViewProviderPrimitive::setupContextMenu().
addDynamicProperty()
App::Property * ViewProviderDocumentObject::addDynamicProperty (const char * type, const char * name = nullptr, const char * group = nullptr, const char * doc = nullptr, short attr = 0, bool ro = false, bool hidden = false) override virtual
Reimplemented from App::PropertyContainer.
References App::PropertyContainer::addDynamicProperty(), App::Document::addOrRemovePropertyOfObject(), App::DocumentObject::getDocument(), and getObject().
allowOverride()
virtual bool Gui::ViewProviderDocumentObject::allowOverride (const App::DocumentObject &) const virtual
Allow this class to be used as an override for the original view provider of the given object.
See also
App::DocumentObject::getViewProviderNameOverride()
Reimplemented in Gui::ViewProviderLink, and PartGui::ViewProviderPartExt.
Referenced by Gui::ViewProviderLink::onChanged(), and Gui::Document::slotNewObject().
attach()
void ViewProviderDocumentObject::attach (App::DocumentObject * pcObject) virtual
Reimplemented in Gui::ViewProviderAnnotation, Gui::ViewProviderAnnotationLabel, Gui::ViewProviderLine, Gui::ViewProviderMeasureDistance, Gui::ViewProviderOriginFeature, Gui::ViewProviderPlane, DrawingGui::ViewProviderDrawingPage, DrawingGui::ViewProviderDrawingView, DrawingGui::ViewProviderDrawingClip, FemGui::ViewProviderFemConstraint, MeshGui::ViewProviderMesh, MeshGui::ViewProviderIndexedFaceSet, MeshGui::ViewProviderMeshTransform, MeshGui::ViewProviderMeshTransformDemolding, PartGui::ViewProvider2DObjectGrid, PartGui::ViewProviderCurveNet, PartGui::ViewProviderPartReference, PartDesignGui::ViewProviderAddSub, PartDesignGui::ViewProviderPrimitive, PointsGui::ViewProviderScattered, PointsGui::ViewProviderStructured, TechDrawGui::ViewProviderAnnotation, TechDrawGui::ViewProviderBalloon, TechDrawGui::ViewProviderDimension, TechDrawGui::ViewProviderImage, TechDrawGui::ViewProviderLeader, TechDrawGui::ViewProviderProjGroup, TechDrawGui::ViewProviderProjGroupItem, TechDrawGui::ViewProviderRichAnno, TechDrawGui::ViewProviderSpreadsheet, TechDrawGui::ViewProviderSymbol, TechDrawGui::ViewProviderTile, TechDrawGui::ViewProviderViewClip, TechDrawGui::ViewProviderViewPart, TechDrawGui::ViewProviderViewSection, TechDrawGui::ViewProviderWeld, Gui::ViewProviderPlacement, PartGui::ViewProviderPartExt, PartDesignGui::ViewProviderBody, PartDesignGui::ViewProviderBoolean, PartDesignGui::ViewProviderDatum, SketcherGui::ViewProviderSketch, TechDrawGui::ViewProviderDrawingView, TechDrawGui::ViewProviderGeomHatch, TechDrawGui::ViewProviderHatch, TechDrawGui::ViewProviderPage, TechDrawGui::ViewProviderTemplate, MeshGui::ViewProviderFace, PartDesignGui::ViewProviderDatumCoordinateSystem, PartDesignGui::ViewProviderDatumLine, PartDesignGui::ViewProviderDatumPlane, PartDesignGui::ViewProviderDatumPoint, PartDesignGui::ViewProviderSubShapeBinder, InspectionGui::ViewProviderInspection, MeshGui::ViewProviderMeshObject, MeshGui::ViewProviderMeshFaceSet, MeshGui::ViewProviderMeshNode, MeshGui::ViewProviderMeshCurvature, MeshGui::ViewProviderMeshOrientation, MeshGui::ViewProviderMeshNonManifolds, MeshGui::ViewProviderMeshNonManifoldPoints, MeshGui::ViewProviderMeshDuplicatedFaces, MeshGui::ViewProviderMeshDegenerations, MeshGui::ViewProviderMeshDuplicatedPoints, MeshGui::ViewProviderMeshIndices, MeshGui::ViewProviderMeshSelfIntersections, MeshGui::ViewProviderMeshFolds, MeshGui::ViewProviderMeshDefects, Gui::ViewProviderFeature, Gui::ViewProviderLink, Gui::ViewProviderGeometryObject, Gui::ViewProviderInventorObject, Gui::ViewProviderOrigin, Gui::ViewProviderVRMLObject, FemGui::ViewProviderFemMesh, FemGui::ViewProviderFemPostFunction, FemGui::ViewProviderFemPostObject, ImageGui::ViewProviderImagePlane, PathGui::ViewProviderPath, RobotGui::ViewProviderRobotObject, and RobotGui::ViewProviderTrajectory.
References DisplayMode, Gui::ViewProvider::getDefaultDisplayMode(), Gui::ViewProvider::getDisplayModes(), App::DocumentObject::getNameInDocument(), App::PropertyBool::getValue(), Gui::ViewProvider::isRestoring(), pcObject, App::PropertyEnumeration::setEnums(), App::PropertyBool::setValue(), App::PropertyEnumeration::setValue(), and App::DocumentObject::Visibility.
Referenced by Gui::ViewProviderAnnotation::attach(), Gui::ViewProviderAnnotationLabel::attach(), Gui::ViewProviderMeasureDistance::attach(), MeshGui::ViewProviderMeshCurvature::attach(), Gui::ViewProviderFeature::attach(), Gui::ViewProviderLink::attach(), Gui::ViewProviderGeometryObject::attach(), Gui::ViewProviderInventorObject::attach(), Gui::ViewProviderOrigin::attach(), Gui::ViewProviderVRMLObject::attach(), Gui::ViewProviderLink::onChanged(), and Gui::Document::slotNewObject().
canDelete()
bool ViewProviderDocumentObject::canDelete (App::DocumentObject * obj) const override virtual
Asks the view provider if the given object can be deleted.
Reimplemented from Gui::ViewProvider.
Reimplemented in FemGui::ViewProviderFemAnalysis, FemGui::ViewProviderFemPostFunctionProvider, FemGui::ViewProviderFemPostObject, FemGui::ViewProviderSolver, TechDrawGui::ViewProviderBalloon, TechDrawGui::ViewProviderDimension, TechDrawGui::ViewProviderLeader, TechDrawGui::ViewProviderProjGroup, TechDrawGui::ViewProviderProjGroupItem, TechDrawGui::ViewProviderRichAnno, TechDrawGui::ViewProviderTile, TechDrawGui::ViewProviderViewClip, TechDrawGui::ViewProviderViewPart, TechDrawGui::ViewProviderViewSection, TechDrawGui::ViewProviderWeld, Gui::ViewProviderLink, TechDrawGui::ViewProviderGeomHatch, TechDrawGui::ViewProviderHatch, and TechDrawGui::ViewProviderPage.
References Base::Persistence::getClassTypeId(), getObject(), App::ExtensionContainer::hasExtension(), and Base::BaseClass::isDerivedFrom().
canDropObjectEx()
bool ViewProviderDocumentObject::canDropObjectEx (App::DocumentObject * obj, App::DocumentObject * owner, const char * subname, const std::vector< std::string > & elements) const override virtual
Query object dropping with full qualified name.
Tree view now calls this function instead of canDropObject(), and may query for objects from other document. The default implementation (actually in ViewProviderDocumentObject) inhibites cross document dropping, and calls canDropObject(obj) for the rest. Override this function to enable cross document linking.
Parameters
obj the object being dropped
owner the (grand)parent object of the dropping object. Maybe null. This may not be the top parent object, as tree view will try to find a parent of the dropping object relative to this object to avoid cyclic dependency
subname subname reference to the dropping object
elements non-object sub-elements, e.g. Faces, Edges, selected when the object is being dropped
Returns
Return whether the dropping action is allowed.
Reimplemented from Gui::ViewProvider.
Reimplemented in PartDesignGui::ViewProviderSubShapeBinder, and Gui::ViewProviderLink.
References Gui::ViewProvider::canDropObject(), getDocument(), and getObject().
Referenced by Gui::TreeWidget::dragMoveEvent(), and Gui::TreeWidget::dropEvent().
detachFromDocument()
const char * ViewProviderDocumentObject::detachFromDocument () override protected virtual
Reimplemented from App::TransactionalObject.
References Gui::Detach, and Gui::ViewProvider::setStatus().
findFrontRootOfType()
SoNode * ViewProviderDocumentObject::findFrontRootOfType (const SoType & type) const protected
Searches in all view providers that are attached to an object that is part of the same document as the object this view provider is attached to for an front root of type.
Before calling this function this view provider has to be attached to an object. The method returns after the first front root node matches. If no front root node matches, 0 is returned.
References Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::ViewProvider::getFrontRoot(), App::Document::getObjects(), Gui::Document::getViewProvider(), Gui::Application::Instance, and pcObject.
Referenced by InspectionGui::ViewProviderInspection::attach(), MeshGui::ViewProviderMeshCurvature::attach(), and FemGui::ViewProviderFemPostObject::attach().
finishRestoring()
void ViewProviderDocumentObject::finishRestoring () virtual
Reimplemented in DrawingGui::ViewProviderDrawingView, DrawingGui::ViewProviderDrawingClip, Gui::ViewProviderLink, TechDrawGui::ViewProviderDrawingView, and TechDrawGui::ViewProviderPage.
Referenced by Gui::ViewProviderLink::finishRestoring(), TechDrawGui::ViewProviderDrawingView::finishRestoring(), and TechDrawGui::ViewProviderPage::finishRestoring().
forceUpdate()
virtual void Gui::ViewProviderDocumentObject::forceUpdate (bool enable = true) virtual
Reimplemented in PartGui::ViewProviderPartExt.
Referenced by Gui::LinkInfo::LinkInfo(), and Gui::LinkInfo::release().
getActiveView()
Gui::MDIView * ViewProviderDocumentObject::getActiveView (void) const protected
Get the active mdi view of the document this view provider is part of.
Note
The returned mdi view doesn't need to be a 3d view but can be e.g. an image view, an SVG view or something else.
References Gui::Document::getActiveView(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::Application::Instance, and pcObject.
Referenced by SketcherGui::ViewProviderSketch::centerSelection(), SketcherGui::ViewProviderSketch::draw(), and PartDesignGui::ViewProviderDatum::getRelevantBoundBox().
getDetailPath()
bool ViewProviderDocumentObject::getDetailPath (const char * subname, SoFullPath * pPath, bool append, SoDetail *& det) const override virtual
return the coin node detail and path to the node of the subname
Reimplemented from Gui::ViewProvider.
Reimplemented in Gui::ViewProviderLink, and Gui::ViewProviderPlacement.
References Gui::ViewProvider::getChildRoot(), Gui::ViewProvider::getDetailPath(), getObject(), Gui::Application::getViewProvider(), Gui::Application::Instance, and Gui::ViewProvider::pcModeSwitch.
Referenced by Gui::LinkInfo::getDetail().
getDocument()
Gui::Document * ViewProviderDocumentObject::getDocument (void) const
Get the GUI document to this ViewProvider object.
References Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::Application::Instance, pcDocument, and pcObject.
Referenced by TechDrawGui::TaskBalloon::accept(), TechDrawGui::TaskDimension::accept(), SpreadsheetGui::ViewProviderSheet::beforeDelete(), canDropObjectEx(), Gui::ViewProviderLink::canDropObjectEx(), MeshGui::MeshSplit::cutMesh(), Gui::ViewProviderLink::doubleClicked(), Gui::ViewProviderPart::doubleClicked(), PartDesignGui::ViewProviderBody::doubleClicked(), PartDesignGui::ViewProviderDatum::doubleClicked(), Gui::ViewProviderGroupExtension::extensionDragObject(), PartDesignGui::TaskSketchBasedParameters::finishReferenceSelection(), PartDesignGui::TaskHelixParameters::finishReferenceSelection(), Gui::ViewProviderLink::finishRestoring(), PartDesignGui::ViewProvider::getBodyViewProvider(), FemGui::ViewProviderFemPostFunction::getBoundingsOfView(), TechDrawGui::QGVPage::getDevicePixelRatio(), Gui::LinkInfo::getDocName(), getElementPicked(), Gui::ViewProviderTextDocument::getMDIView(), TechDrawGui::ViewProviderDrawingView::getMDIViewPage(), TechDrawGui::ViewProviderDrawingView::getQView(), MeshGui::MeshSplit::makeCopy(), SketcherGui::ViewProviderSketch::mouseButtonPressed(), TechDrawGui::ViewProviderDrawingView::onGuiRepaint(), SketcherGui::ViewProviderSketch::onSelectionChanged(), Gui::DocumentItem::populateItem(), Gui::ElementColors::Private::Private(), PartDesignGui::TaskPipeParameters::referenceSelected(), TechDrawGui::TaskBalloon::reject(), TechDrawGui::TaskDimension::reject(), Gui::Document::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), SketcherGui::ViewProviderSketch::setEditViewer(), PartDesignGui::ViewProviderShapeBinder::setupContextMenu(), startDefaultEditMode(), PartDesignGui::TaskSketchBasedParameters::startReferenceSelection(), PartDesignGui::TaskHelixParameters::startReferenceSelection(), PartDesignGui::TaskBoxPrimitives::TaskBoxPrimitives(), TechDrawGui::TaskDimension::TaskDimension(), PartDesignGui::TaskFeatureParameters::TaskFeatureParameters(), PartDesignGui::TaskPipeParameters::TaskPipeParameters(), Gui::DocumentObjectItem::testStatus(), MeshGui::MeshSplit::trimMesh(), SketcherGui::ViewProviderSketch::unsetEdit(), SketcherGui::ViewProviderSketch::updateData(), Gui::ViewProviderLink::updateDataPrivate(), PartDesignGui::ViewProviderBody::updateOriginDatumSize(), and Gui::ViewProviderOriginGroupExtension::updateOriginSize().
getEditingView()
Gui::MDIView * ViewProviderDocumentObject::getEditingView () const protected
Get the mdi view of the document this view provider is part of and that is in editing mode.
Note
In case there is no mdi view in editing mode 0 is returned. If a value different to 0 is returned it is guaranteed to be a 3d view.
References Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::Document::getEditingViewOfViewProvider(), Gui::Application::Instance, and pcObject.
getElementPicked()
bool ViewProviderDocumentObject::getElementPicked (const SoPickedPoint * pp, std::string & subname) const override virtual
return a hit element given the picked point which contains the full node path
Reimplemented from Gui::ViewProvider.
Reimplemented in Gui::ViewProviderLink, and Gui::ViewProviderPlacement.
References Gui::ViewProvider::getChildRoot(), getDocument(), Gui::ViewProvider::getElementPicked(), Gui::Document::getViewProvider(), Gui::ViewProvider::isSelectable(), and Gui::ViewProvider::pcModeSwitch.
Referenced by Gui::LinkInfo::getElementPicked(), and Gui::ViewProviderLink::getElementPicked().
getFullName()
std::string ViewProviderDocumentObject::getFullName () const override virtual
Reimplemented from App::PropertyContainer.
References App::DocumentObject::getFullName(), and pcObject.
Referenced by Gui::ViewProviderLink::onChanged().
getInventorView()
Gui::MDIView * ViewProviderDocumentObject::getInventorView () const protected
Get any mdi view of the document this view provider is part of. In case there is an mdi view in editing mode that contains this view provider that mdi view is returned. Otherwise any other 3d view that contains this view provider is returned. If a value different to 0 is returned it is guaranteed to be a 3d view.
References Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::Document::getEditingViewOfViewProvider(), Gui::Document::getViewOfViewProvider(), Gui::Application::Instance, and pcObject.
getLinkedViewProvider()
ViewProviderDocumentObject * ViewProviderDocumentObject::getLinkedViewProvider (std::string * subname = nullptr, bool recursive = false) const virtual
Return the linked view object.
This function is mainly used for GUI navigation (e.g. StdCmdLinkSelectLinked).
Parameters
subname output as the subname referencing the linked object
recursive whether to follow the link recursively
Returns
Returns the linked view provider. If none, it shall return itself.
Reimplemented in Gui::ViewProviderLink.
References App::DocumentObject::getLinkedObject(), App::DocumentObject::getNameInDocument(), Gui::Application::Instance, and pcObject.
getObject()
App::DocumentObject * Gui::ViewProviderDocumentObject::getObject (void) const
Get the object of this ViewProvider object.
Referenced by Gui::ElementColors::Private::accept(), FemGui::TaskDlgFemConstraint::accept(), FemGui::TaskDlgFemConstraintBearing::accept(), FemGui::TaskDlgFemConstraintContact::accept(), FemGui::TaskDlgFemConstraintDisplacement::accept(), FemGui::TaskDlgFemConstraintFixed::accept(), FemGui::TaskDlgFemConstraintFluidBoundary::accept(), FemGui::TaskDlgFemConstraintForce::accept(), FemGui::TaskDlgFemConstraintGear::accept(), FemGui::TaskDlgFemConstraintHeatflux::accept(), FemGui::TaskDlgFemConstraintInitialTemperature::accept(), FemGui::TaskDlgFemConstraintPlaneRotation::accept(), FemGui::TaskDlgFemConstraintPressure::accept(), FemGui::TaskDlgFemConstraintPulley::accept(), FemGui::TaskDlgFemConstraintSpring::accept(), FemGui::TaskDlgFemConstraintTemperature::accept(), FemGui::TaskDlgFemConstraintTransform::accept(), PartGui::FaceColors::accept(), PartDesignGui::TaskDlgBooleanParameters::accept(), PartDesignGui::TaskDlgChamferParameters::accept(), PartDesignGui::TaskDlgDatumParameters::accept(), PartDesignGui::TaskDlgDraftParameters::accept(), PartDesignGui::TaskDlgDressUpParameters::accept(), PartDesignGui::TaskDlgFeatureParameters::accept(), PartDesignGui::TaskDlgFilletParameters::accept(), PartDesignGui::TaskDlgLoftParameters::accept(), PartDesignGui::TaskDlgMirroredParameters::accept(), PartDesignGui::TaskDlgMultiTransformParameters::accept(), PartDesignGui::TaskPipeParameters::accept(), PartDesignGui::TaskPrimitiveParameters::accept(), PartDesignGui::TaskDlgSketchBasedParameters::accept(), PartDesignGui::TaskDlgThicknessParameters::accept(), PathGui::TaskDlgPathCompound::accept(), TechDrawGui::TaskBalloon::accept(), TechDrawGui::TaskDimension::accept(), StdCmdDelete::activated(), PartDesignGui::TaskDressUpParameters::addAllEdges(), addDynamicProperty(), Gui::Document::addViewProvider(), PartDesignGui::TaskChamferParameters::apply(), PartDesignGui::TaskFilletParameters::apply(), PartDesignGui::TaskLinearPatternParameters::apply(), PartDesignGui::TaskPolarPatternParameters::apply(), PartDesignGui::TaskScaledParameters::apply(), PartDesignGui::TaskHelixParameters::apply(), PartDesignGui::TaskHoleParameters::apply(), PartDesignGui::TaskRevolutionParameters::apply(), Gui::ViewProviderLink::applyColors(), CmdSketcherConstrainHorizontal::applyConstraint(), CmdSketcherConstrainVertical::applyConstraint(), CmdSketcherConstrainLock::applyConstraint(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainCoincident::applyConstraint(), CmdSketcherConstrainPointOnObject::applyConstraint(), CmdSketcherConstrainParallel::applyConstraint(), PartDesignGui::TaskExtrudeParameters::applyParameters(), Gui::ViewProviderOriginFeature::attach(), PartDesignGui::ViewProviderDatum::attach(), canDelete(), Gui::ViewProviderLink::canDragAndDropObject(), canDropObjectEx(), Gui::ViewProviderLink::canDropObjectEx(), PartDesignGui::ViewProviderBody::canDropObjects(), PartDesignGui::TaskHoleParameters::changedObject(), Gui::ViewProviderLink::checkIcon(), PartGui::ViewProviderCompound::claimChildren(), PartGui::ViewProviderMirror::claimChildren(), PartGui::ViewProviderFillet::claimChildren(), PartGui::ViewProviderChamfer::claimChildren(), PartGui::ViewProviderRuledSurface::claimChildren(), Gui::ViewProviderOrigin::claimChildren(), FemGui::ViewProviderFemPostFunctionProvider::claimChildren(), FemGui::ViewProviderFemPostPipeline::claimChildren(), PartGui::ViewProviderBoolean::claimChildren(), PartGui::ViewProviderMultiFuse::claimChildren(), PartGui::ViewProviderMultiCommon::claimChildren(), PartGui::ViewProviderExtrusion::claimChildren(), PartGui::ViewProviderRevolution::claimChildren(), PartGui::ViewProviderLoft::claimChildren(), PartGui::ViewProviderSweep::claimChildren(), PartGui::ViewProviderOffset::claimChildren(), PartGui::ViewProviderThickness::claimChildren(), PartGui::ViewProviderFace::claimChildren(), PartDesignGui::ViewProviderHelix::claimChildren(), PartDesignGui::ViewProviderHole::claimChildren(), PartDesignGui::ViewProviderLoft::claimChildren(), PartDesignGui::ViewProviderMainPart::claimChildren(), PartDesignGui::ViewProviderMultiTransform::claimChildren(), PartDesignGui::ViewProviderPipe::claimChildren(), PartDesignGui::ViewProviderSketchBased::claimChildren(), PathGui::ViewProviderArea::claimChildren(), PathGui::ViewProviderAreaView::claimChildren(), PathGui::ViewProviderPathCompound::claimChildren(), PathGui::ViewProviderPathShape::claimChildren(), RobotGui::ViewProviderTrajectoryCompound::claimChildren(), RobotGui::ViewProviderTrajectoryDressUp::claimChildren(), PartDesignGui::ViewProviderSubShapeBinder::claimChildren(), MeshGui::ViewProviderMesh::clipMeshCallback(), Gui::TreeWidget::contextMenuEvent(), SketcherGui::DrawSketchHandler::createAutoConstraints(), Gui::TreeWidgetEditDelegate::createEditor(), MeshPartGui::CurveOnMeshHandler::Private::createGrid(), Gui::DocumentObjectItem::displayStatusInfo(), Gui::SoFCUnifiedSelection::doAction(), Gui::DocumentObjectData::DocumentObjectData(), Gui::ViewProviderTextDocument::doubleClicked(), FemGui::ViewProviderFemAnalysis::doubleClicked(), PartGui::ViewProviderPart::doubleClicked(), PartDesignGui::ViewProviderBase::doubleClicked(), Gui::ViewProviderPart::doubleClicked(), PartDesignGui::ViewProvider::doubleClicked(), PartDesignGui::ViewProviderBody::doubleClicked(), PartDesignGui::ViewProviderDatum::doubleClicked(), FemGui::ViewProviderFemPostPlaneFunction::draggerUpdate(), FemGui::ViewProviderFemPostSphereFunction::draggerUpdate(), Gui::TreeWidget::dragMoveEvent(), PartGui::ViewProviderMultiFuse::dragObject(), PartGui::ViewProviderMultiCommon::dragObject(), PartGui::ViewProviderCompound::dragObject(), PartGui::ViewProviderFace::dragObject(), PathGui::ViewProviderArea::dragObject(), PathGui::ViewProviderAreaView::dragObject(), PathGui::ViewProviderPathCompound::dragObject(), PathGui::ViewProviderPathShape::dragObject(), Gui::TreeWidget::dropEvent(), PartGui::ViewProviderMultiFuse::dropObject(), PartGui::ViewProviderMultiCommon::dropObject(), PartGui::ViewProviderCompound::dropObject(), PartGui::ViewProviderFace::dropObject(), PathGui::ViewProviderArea::dropObject(), PathGui::ViewProviderAreaView::dropObject(), PathGui::ViewProviderPathCompound::dropObject(), PathGui::ViewProviderPathShape::dropObject(), PartDesignGui::ViewProviderBody::dropObject(), PartDesignGui::ViewProviderSubShapeBinder::dropObjectEx(), Gui::ElementColors::ElementColors(), PartDesignGui::TaskBooleanParameters::exitSelectionMode(), MeshGui::ViewProviderMesh::exportMesh(), Gui::ViewProviderGroupExtension::extensionCanDropObject(), Gui::ViewProviderGeoFeatureGroupExtension::extensionClaimChildren(), Gui::ViewProviderGroupExtension::extensionClaimChildren(), Gui::ViewProviderGeoFeatureGroupExtension::extensionClaimChildren3D(), Gui::ViewProviderGroupExtension::extensionDropObject(), Gui::ViewProviderGroupExtension::extensionHide(), PartGui::ViewProviderAttachExtension::extensionMergeColorfullOverlayIcons(), PartGui::ViewProviderSplineExtension::extensionOnChanged(), Gui::ViewProviderGroupExtension::extensionOnDelete(), PartGui::ViewProviderAttachExtension::extensionSetupContextMenu(), Gui::ViewProviderGroupExtension::extensionShow(), Gui::ViewProviderGeoFeatureGroupExtension::extensionUpdateData(), PartGui::ViewProviderAttachExtension::extensionUpdateData(), Gui::ViewProviderOriginGroupExtension::extensionUpdateData(), PartGui::FaceColors::FaceColors(), MeshGui::ViewProviderMesh::faceInfo(), PartDesignGui::TaskRevolutionParameters::fillAxisCombo(), PartDesignGui::TaskExtrudeParameters::fillDirectionCombo(), MeshGui::ViewProviderMesh::fillHole(), Gui::DocumentItem::findItem(), PartDesignGui::TaskHelixParameters::finishReferenceSelection(), PartDesignGui::TaskDressUpParameters::getBase(), PartDesignGui::ViewProvider::getBodyViewProvider(), Gui::LinkInfo::getDetail(), getDetailPath(), Gui::ViewProviderLink::getElementColors(), PartDesignGui::TaskSketchBasedParameters::getFaceReference(), Gui::DocumentObjectItem::getFullSubName(), PartGui::ViewProviderBoolean::getIcon(), PartDesignGui::ViewProviderHelix::getIcon(), PartDesignGui::ViewProviderLoft::getIcon(), PartDesignGui::ViewProviderPipe::getIcon(), PartDesignGui::ViewProviderPrimitive::getIcon(), Gui::ViewProviderLink::getIcon(), Gui::ViewProviderPart::getIcon(), PartDesignGui::TaskDraftParameters::getLine(), Gui::LinkInfo::getLinkedLabel(), Gui::LinkInfo::getLinkedName(), Gui::ViewProviderLink::getLinkedView(), Gui::ViewProviderTextDocument::getMDIView(), PartGui::ViewProviderPartExt::getModelPoints(), Gui::DocumentObjectItem::getName(), PartDesignGui::TaskTransformedParameters::getObject(), Gui::View3DInventorPy::getObjectInfo(), Gui::View3DInventorPy::getObjectsInfo(), PartDesignGui::TaskDraftParameters::getPlane(), PartDesignGui::TaskExtrudeParameters::getReferenceAxis(), PartDesignGui::TaskHelixParameters::getReferenceAxis(), PartDesignGui::TaskRevolutionParameters::getReferenceAxis(), PartDesignGui::TaskDressUpParameters::getReferences(), PartDesignGui::ViewProviderDatum::getRelevantBoundBox(), Gui::TreeWidget::getSelection(), Gui::LinkInfo::getSnapshot(), PartDesignGui::TaskTransformedParameters::getTopTransformedObject(), PartDesignGui::TaskMultiTransformParameters::getTransformFeatures(), Gui::ViewProviderDocumentObjectGroup::getViewProviders(), DrawingGui::ViewProviderDrawingView::hide(), DrawingGui::ViewProviderDrawingClip::hide(), PartDesignGui::TaskDressUpParameters::hideObject(), PartDesignGui::TaskDressUpParameters::hideOnError(), PartDesignGui::ViewProviderLoft::highlightProfile(), PartDesignGui::ViewProviderShapeBinder::highlightReferences(), SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), PartDesignGui::ViewProviderDressUp::highlightReferences(), FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences(), PartDesignGui::ViewProviderPipe::highlightReferences(), PartDesignGui::ViewProviderLoft::highlightSection(), Gui::DocumentObjectItem::isGroup(), Gui::DocumentObjectItem::isLink(), Gui::LinkInfo::isLinked(), Gui::DocumentObjectItem::isLinkFinal(), Gui::LinkInfo::LinkInfo(), MeshGui::MeshSplit::makeCopy(), Gui::TreeWidget::mimeData(), SketcherGui::ViewProviderSketch::mouseButtonPressed(), Gui::TreeWidget::mouseDoubleClickEvent(), SketcherGui::DrawSketchHandlerTrimming::mouseMove(), Gui::ActiveObjectList::objectDeleted(), PartDesignGui::TaskSketchBasedParameters::objectNameByLabel(), PartDesignGui::TaskSketchBasedParameters::onAddSelection(), PartDesignGui::TaskExtrudeParameters::onAlongSketchNormalChanged(), onBeforeChange(), PartDesignGui::TaskBoxPrimitives::onBoxHeightChanged(), PartDesignGui::TaskBoxPrimitives::onBoxLengthChanged(), PartDesignGui::TaskBoxPrimitives::onBoxWidthChanged(), PartDesignGui::ViewProviderDatumCoordinateSystem::onChanged(), Gui::ViewProviderAnnotationLabel::onChanged(), Gui::ViewProviderGeometryObject::onChanged(), Gui::ViewProviderOrigin::onChanged(), FemGui::ViewProviderFemPostObject::onChanged(), TechDrawGui::ViewProviderImage::onChanged(), onChanged(), Gui::ViewProviderLink::onChanged(), PartDesignGui::ViewProvider::onChanged(), PartDesignGui::ViewProviderBody::onChanged(), PartDesignGui::ViewProviderSubShapeBinder::onChanged(), TechDrawGui::ViewProviderDrawingView::onChanged(), TechDrawGui::ViewProviderTemplate::onChanged(), PartDesignGui::TaskBoxPrimitives::onConeAngleChanged(), PartDesignGui::TaskBoxPrimitives::onConeHeightChanged(), PartDesignGui::TaskBoxPrimitives::onConeRadius1Changed(), PartDesignGui::TaskBoxPrimitives::onConeRadius2Changed(), Gui::TreeWidget::onCreateGroup(), PartDesignGui::TaskBoxPrimitives::onCylinderAngleChanged(), PartDesignGui::TaskBoxPrimitives::onCylinderHeightChanged(), PartDesignGui::TaskBoxPrimitives::onCylinderRadiusChanged(), PartDesignGui::TaskBoxPrimitives::onCylinderXSkewChanged(), PartDesignGui::TaskBoxPrimitives::onCylinderYSkewChanged(), Gui::ViewProviderOrigin::onDelete(), Gui::ViewProviderOriginFeature::onDelete(), PartGui::ViewProviderBoolean::onDelete(), PartGui::ViewProviderMultiFuse::onDelete(), PartGui::ViewProviderMultiCommon::onDelete(), PartGui::ViewProviderCompound::onDelete(), PartGui::ViewProviderMirror::onDelete(), PartGui::ViewProviderFillet::onDelete(), PartGui::ViewProviderChamfer::onDelete(), PartGui::ViewProviderRevolution::onDelete(), PartGui::ViewProviderOffset::onDelete(), PartGui::ViewProviderThickness::onDelete(), PartGui::ViewProviderRuledSurface::onDelete(), PartDesignGui::ViewProviderHelix::onDelete(), PartDesignGui::ViewProviderMultiTransform::onDelete(), PartDesignGui::ViewProviderSketchBased::onDelete(), PathGui::ViewProviderArea::onDelete(), PathGui::ViewProviderAreaView::onDelete(), PathGui::ViewProviderPathShape::onDelete(), Gui::ViewProviderLink::onDelete(), PartDesignGui::ViewProvider::onDelete(), PartDesignGui::ViewProviderBody::onDelete(), PartDesignGui::ViewProviderBoolean::onDelete(), SketcherGui::ViewProviderSketch::onDelete(), PartDesignGui::ViewProviderHole::onDelete(), PartDesignGui::TaskExtrudeParameters::onDirectionCBChanged(), PartDesignGui::TaskBoxPrimitives::onEllipsoidAngle1Changed(), PartDesignGui::TaskBoxPrimitives::onEllipsoidAngle2Changed(), PartDesignGui::TaskBoxPrimitives::onEllipsoidAngle3Changed(), PartDesignGui::TaskBoxPrimitives::onEllipsoidRadius1Changed(), PartDesignGui::TaskBoxPrimitives::onEllipsoidRadius2Changed(), PartDesignGui::TaskBoxPrimitives::onEllipsoidRadius3Changed(), Gui::TreeWidget::onFinishEditing(), PartDesignGui::TaskExtrudeParameters::onLength2Changed(), PartDesignGui::TaskExtrudeParameters::onLengthChanged(), Gui::TreeWidget::onMarkRecompute(), PartDesignGui::TaskExtrudeParameters::onMidplaneChanged(), PartDesignGui::TaskExtrudeParameters::onOffsetChanged(), PartDesignGui::TaskBoxPrimitives::onPrismCircumradiusChanged(), PartDesignGui::TaskBoxPrimitives::onPrismHeightChanged(), PartDesignGui::TaskBoxPrimitives::onPrismPolygonChanged(), PartDesignGui::TaskBoxPrimitives::onPrismXSkewChanged(), PartDesignGui::TaskBoxPrimitives::onPrismYSkewChanged(), Gui::TreeWidget::onRecomputeObject(), PartDesignGui::TaskExtrudeParameters::onReversedChanged(), Gui::TreeWidget::onSelectDependents(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), PartDesignGui::TaskDraftParameters::onSelectionChanged(), PartDesignGui::TaskHelixParameters::onSelectionChanged(), PartDesignGui::TaskRevolutionParameters::onSelectionChanged(), SketcherGui::DrawSketchHandlerCarbonCopy::onSelectionChanged(), SketcherGui::DrawSketchHandlerExternal::onSelectionChanged(), SketcherGui::ViewProviderSketch::onSelectionChanged(), PartDesignGui::TaskSketchBasedParameters::onSelectReference(), PartDesignGui::TaskBoxPrimitives::onSphereAngle1Changed(), PartDesignGui::TaskBoxPrimitives::onSphereAngle2Changed(), PartDesignGui::TaskBoxPrimitives::onSphereAngle3Changed(), PartDesignGui::TaskBoxPrimitives::onSphereRadiusChanged(), Gui::TreeWidget::onStartEditing(), PartDesignGui::TaskExtrudeParameters::onTaper2Changed(), PartDesignGui::TaskExtrudeParameters::onTaperChanged(), Gui::PropertyView::onTimer(), PartDesignGui::TaskBoxPrimitives::onTorusAngle1Changed(), PartDesignGui::TaskBoxPrimitives::onTorusAngle2Changed(), PartDesignGui::TaskBoxPrimitives::onTorusAngle3Changed(), PartDesignGui::TaskBoxPrimitives::onTorusRadius1Changed(), PartDesignGui::TaskBoxPrimitives::onTorusRadius2Changed(), PartDesignGui::TaskBoxPrimitives::onWedgeX2maxChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeX2minChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeXmaxChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeXminChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeYmaxChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeYminChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeZ2maxChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeZ2minChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeZmaxChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeZminChanged(), PartDesignGui::TaskExtrudeParameters::onXDirectionEditChanged(), PartDesignGui::TaskExtrudeParameters::onYDirectionEditChanged(), PartDesignGui::TaskExtrudeParameters::onZDirectionEditChanged(), FemGui::TaskDlgFemConstraint::open(), FemGui::TaskDlgFemConstraintContact::open(), FemGui::TaskDlgFemConstraintDisplacement::open(), FemGui::TaskDlgFemConstraintFixed::open(), FemGui::TaskDlgFemConstraintForce::open(), FemGui::TaskDlgFemConstraintHeatflux::open(), FemGui::TaskDlgFemConstraintInitialTemperature::open(), FemGui::TaskDlgFemConstraintPlaneRotation::open(), FemGui::TaskDlgFemConstraintPressure::open(), FemGui::TaskDlgFemConstraintPulley::open(), FemGui::TaskDlgFemConstraintSpring::open(), FemGui::TaskDlgFemConstraintTemperature::open(), FemGui::TaskDlgFemConstraintTransform::open(), PartGui::FaceColors::open(), MeshGui::ViewProviderMesh::partMeshCallback(), Gui::DocumentItem::populateItem(), SketcherGui::DrawSketchHandlerBSpline::pressButton(), Gui::ElementColors::Private::Private(), PartGui::FaceColors::Private::Private(), SketcherGui::DrawSketchHandlerBSpline::quit(), FemGui::TaskDlgPost::recompute(), PartDesignGui::TaskFeatureParameters::recomputeFeature(), TechDrawGui::TaskBalloon::recomputeFeature(), TechDrawGui::TaskDimension::recomputeFeature(), TechDrawGui::TaskLeaderLine::recomputeFeature(), PartDesignGui::ViewProviderTransformed::recomputeFeature(), PartDesignGui::TaskDressUpParameters::referenceSelected(), PartDesignGui::TaskPipeParameters::referenceSelected(), PartDesignGui::TaskPipeOrientation::referenceSelected(), PartDesignGui::TaskPipeScaling::referenceSelected(), SketcherGui::DrawSketchHandlerBSpline::registerPressedKey(), PartGui::FaceColors::reject(), PartDesignGui::TaskDlgBooleanParameters::reject(), PartDesignGui::TaskDlgFeatureParameters::reject(), PartDesignGui::TaskDlgSketchBasedParameters::reject(), TechDrawGui::TaskBalloon::reject(), TechDrawGui::TaskDimension::reject(), DrawSketchHandlerCoincident::releaseButton(), DrawSketchHandlerCopy::releaseButton(), DrawSketchHandlerRectangularArray::releaseButton(), SketcherGui::DrawSketchHandlerArc::releaseButton(), SketcherGui::DrawSketchHandler3PointArc::releaseButton(), SketcherGui::DrawSketchHandlerArcOfEllipse::releaseButton(), SketcherGui::DrawSketchHandlerCircle::releaseButton(), SketcherGui::DrawSketchHandler3PointCircle::releaseButton(), SketcherGui::DrawSketchHandlerExtend::releaseButton(), SketcherGui::DrawSketchHandlerFillet::releaseButton(), SketcherGui::DrawSketchHandlerLine::releaseButton(), SketcherGui::DrawSketchHandlerLineSet::releaseButton(), SketcherGui::DrawSketchHandlerPoint::releaseButton(), SketcherGui::DrawSketchHandlerRegularPolygon::releaseButton(), SketcherGui::DrawSketchHandlerBox::releaseButton(), SketcherGui::DrawSketchHandlerOblong::releaseButton(), SketcherGui::DrawSketchHandlerSlot::releaseButton(), SketcherGui::DrawSketchHandlerSplitting::releaseButton(), SketcherGui::DrawSketchHandlerTrimming::releaseButton(), SketcherGui::DrawSketchHandlerArcOfHyperbola::releaseButton(), SketcherGui::DrawSketchHandlerArcOfParabola::releaseButton(), removeDynamicProperty(), replaceObject(), MeshGui::ViewProviderMesh::segmMeshCallback(), Gui::View3DInventorViewer::selectAll(), Gui::DocumentItem::selectAllInstances(), Gui::SelectionObserver::SelectionObserver(), Gui::Document::setActiveView(), Gui::DocumentObjectItem::setData(), PartDesignGui::TaskExtrudeParameters::setDirectionMode(), Gui::Document::setEdit(), FemGui::ViewProviderSetNodes::setEdit(), PartGui::ViewProviderMirror::setEdit(), PartGui::ViewProviderFillet::setEdit(), PartGui::ViewProviderChamfer::setEdit(), PartGui::ViewProviderOffset::setEdit(), PartGui::ViewProviderThickness::setEdit(), PartGui::ViewProviderPrimitive::setEdit(), PartDesignGui::ViewProviderBase::setEdit(), PartDesignGui::ViewProviderDressUp::setEdit(), PartDesignGui::ViewProviderHelix::setEdit(), RaytracingGui::ViewProviderLux::setEdit(), RaytracingGui::ViewProviderPovray::setEdit(), RobotGui::ViewProviderEdge2TracObject::setEdit(), SurfaceGui::ViewProviderFilling::setEdit(), SurfaceGui::ViewProviderGeomFillSurface::setEdit(), SurfaceGui::ViewProviderSections::setEdit(), Gui::ViewProviderDragger::setEdit(), PartDesignGui::ViewProviderSubShapeBinder::setEdit(), SketcherGui::ViewProviderSketch::setEditViewer(), Gui::ViewProviderDragger::setEditViewer(), Gui::ViewProviderLink::setElementColors(), Gui::DocumentObjectItem::setExpandedStatus(), PartDesignGui::ViewProviderDatumLine::setExtents(), PartDesignGui::ViewProviderDatumPlane::setExtents(), PartGui::ViewProviderPartExt::setHighlightedEdges(), PartGui::ViewProviderPartExt::setHighlightedFaces(), PartGui::ViewProviderPartExt::setHighlightedPoints(), Gui::Dialog::DlgInspector::setNodeNames(), Gui::ViewProviderLink::setOverrideMode(), PartDesignGui::ViewProviderAddSub::setPreviewDisplayMode(), PartDesignGui::TaskDressUpParameters::setSelection(), Gui::ViewProviderOrigin::setTemporaryVisibility(), PartGui::ViewProviderPrimitive::setupContextMenu(), TechDrawGui::ViewProviderBalloon::setupContextMenu(), TechDrawGui::ViewProviderDimension::setupContextMenu(), PartDesignGui::ViewProviderShapeBinder::setupContextMenu(), PartDesignGui::ViewProviderBase::setupContextMenu(), PartDesignGui::TaskExtrudeParameters::setupDialog(), FemGui::ViewProviderFemPostObject::setupPipeline(), FemGui::ViewProviderFemPostClip::setupTaskDialog(), FemGui::ViewProviderFemPostCut::setupTaskDialog(), PartDesignGui::TaskSketchBasedParameters::setUpToFace(), PartDesignGui::TaskDressUpParameters::setupTransaction(), PartDesignGui::ViewProviderBody::setVisualBodyMode(), MeshGui::Annotation::show(), DrawingGui::ViewProviderDrawingView::show(), DrawingGui::ViewProviderDrawingClip::show(), show(), PartDesignGui::TaskDressUpParameters::showObject(), Gui::ViewProviderOriginGroupExtension::slotChangedObjectApp(), PartDesignGui::ViewProviderBody::slotChangedObjectApp(), Gui::ViewProviderOriginGroupExtension::slotChangedObjectGui(), PartDesignGui::ViewProviderBody::slotChangedObjectGui(), Gui::DocumentItem::slotInEdit(), Gui::Document::slotSkipRecompute(), startDefaultEditMode(), Gui::ViewProviderLink::startEditing(), PartDesignGui::ViewProviderTransformed::startEditing(), MeshGui::MeshFaceAddition::startEditing(), MeshGui::MeshFillHole::startEditing(), PartDesignGui::TaskHelixParameters::startReferenceSelection(), PartDesignGui::TaskBooleanParameters::TaskBooleanParameters(), PartDesignGui::TaskBoxPrimitives::TaskBoxPrimitives(), PartDesignGui::TaskChamferParameters::TaskChamferParameters(), Gui::TaskCSysDragger::TaskCSysDragger(), PartDesignGui::TaskDatumParameters::TaskDatumParameters(), PartDesignGui::TaskDraftParameters::TaskDraftParameters(), PartDesignGui::TaskFilletParameters::TaskFilletParameters(), PartDesignGui::TaskHoleParameters::TaskHoleParameters(), PartDesignGui::TaskLoftParameters::TaskLoftParameters(), PartDesignGui::TaskMultiTransformParameters::TaskMultiTransformParameters(), PartDesignGui::TaskPipeOrientation::TaskPipeOrientation(), PartDesignGui::TaskPipeParameters::TaskPipeParameters(), PartDesignGui::TaskPipeScaling::TaskPipeScaling(), PartDesignGui::TaskRevolutionParameters::TaskRevolutionParameters(), PartDesignGui::TaskThicknessParameters::TaskThicknessParameters(), PathGui::TaskWidgetPathCompound::TaskWidgetPathCompound(), Gui::DocumentObjectItem::testStatus(), MeshGui::ViewProviderMesh::trimMeshCallback(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), PartGui::ViewProviderMirror::unsetEdit(), update(), PartDesignGui::ViewProviderAddSub::updateAddSubShapeIndicator(), Gui::DocumentObjectData::updateChildren(), Gui::ViewProviderGeometryObject::updateData(), Gui::ViewProviderOriginFeature::updateData(), FemGui::ViewProviderFemConstraintBearing::updateData(), FemGui::ViewProviderFemConstraintContact::updateData(), FemGui::ViewProviderFemConstraintDisplacement::updateData(), FemGui::ViewProviderFemConstraintFixed::updateData(), FemGui::ViewProviderFemConstraintFluidBoundary::updateData(), FemGui::ViewProviderFemConstraintForce::updateData(), FemGui::ViewProviderFemConstraintGear::updateData(), FemGui::ViewProviderFemConstraintHeatflux::updateData(), FemGui::ViewProviderFemConstraintPlaneRotation::updateData(), FemGui::ViewProviderFemConstraintPressure::updateData(), FemGui::ViewProviderFemConstraintPulley::updateData(), FemGui::ViewProviderFemConstraintSpring::updateData(), FemGui::ViewProviderFemConstraintTemperature::updateData(), FemGui::ViewProviderFemConstraintTransform::updateData(), FemGui::ViewProviderFemPostPlaneFunction::updateData(), FemGui::ViewProviderFemPostSphereFunction::updateData(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderMultiFuse::updateData(), PartGui::ViewProviderMultiCommon::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderFillet::updateData(), PartGui::ViewProviderChamfer::updateData(), PartGui::ViewProviderCustom::updateData(), PartDesignGui::ViewProviderDatumLine::updateData(), PartDesignGui::ViewProviderDatumPlane::updateData(), SketcherGui::ViewProviderCustom::updateData(), PartDesignGui::ViewProviderBody::updateData(), PartDesignGui::TaskExtrudeParameters::updateDirectionEdits(), FemGui::ViewProviderFemPostPipeline::updateFunctionSize(), Gui::DocumentItem::updateItemSelection(), PartDesignGui::ViewProviderBody::updateOriginDatumSize(), Gui::ViewProviderOriginGroupExtension::updateOriginSize(), PartGui::ViewProviderPartExt::updateVisual(), PartDesignGui::TaskBoxPrimitives::~TaskBoxPrimitives(), PartDesignGui::TaskHelixParameters::~TaskHelixParameters(), PartDesignGui::TaskPipeParameters::~TaskPipeParameters(), and PartDesignGui::TaskRevolutionParameters::~TaskRevolutionParameters().
getPyObject()
PyObject * ViewProviderDocumentObject::getPyObject (void) override virtual
Get the python wrapper for that ViewProvider.
Reimplemented from Gui::ViewProvider.
Reimplemented in FemGui::ViewProviderFemMesh, MeshGui::ViewProviderMesh, Gui::ViewProviderLink, SpreadsheetGui::ViewProviderSheet, and PartDesignGui::ViewProvider.
References Gui::ViewProvider::pyViewObject.
getTaskViewContent()
void ViewProviderDocumentObject::getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > & vec) const override virtual
Get a list of TaskBoxes associated with this object.
Reimplemented from Gui::ViewProvider.
References draftgeoutils.general::vec().
getTransactionText()
const char * ViewProviderDocumentObject::getTransactionText () const override virtual
Is called by the tree if the user double clicks on the object.
It returns the string for the transaction that will be shown in the undo/redo dialog. If null is returned then no transaction will be opened.
Reimplemented from Gui::ViewProvider.
Reimplemented in SketcherGui::ViewProviderSketch.
References draftutils.translate::QT_TRANSLATE_NOOP.
Referenced by Gui::TreeWidget::mouseDoubleClickEvent().
getViewOfNode()
Gui::MDIView * ViewProviderDocumentObject::getViewOfNode (SoNode * node) const protected
Get the mdi view of the document that contains the given node.
References Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::Document::getViewOfNode(), Gui::Application::Instance, and pcObject.
hide()
void ViewProviderDocumentObject::hide (void) override virtual
Hide the object in the view.
Reimplemented from Gui::ViewProvider.
Reimplemented in MeshGui::ViewProviderMeshCurvature, DrawingGui::ViewProviderDrawingPage, DrawingGui::ViewProviderDrawingView, DrawingGui::ViewProviderDrawingClip, FemGui::ViewProviderFemAnalysis, FemGui::ViewProviderFemPostObject, InspectionGui::ViewProviderInspection, TechDrawGui::ViewProviderViewClip, TechDrawGui::ViewProviderDrawingView, TechDrawGui::ViewProviderPage, and TechDrawGui::ViewProviderTemplate.
References Gui::ViewProvider::hide(), and App::Property::User2.
Referenced by ArchComponent.ArchSelectionObserver::addSelection(), Gui::ViewProviderLink::attach(), Gui::ViewProviderAnnotationLabel::drawImage(), MeshGui::ViewProviderMeshCurvature::hide(), FemGui::ViewProviderFemAnalysis::hide(), FemGui::ViewProviderFemPostObject::hide(), Mod.Show.mTempoVis.TempoVis::hide_all_dependencies(), Mod.Show.mTempoVis.TempoVis::hide_all_dependent(), MeshGui::ViewProviderMeshDefects::onChanged(), PathGui::ViewProviderPath::onChanged(), onChanged(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), PathScripts.PathToolEdit.ToolEditorImage::setupUI(), startRestoring(), and PathScripts.PathToolEdit.ToolEditorImage::updateTool().
isAttachedToDocument()
bool ViewProviderDocumentObject::isAttachedToDocument () const override protected virtual
Reimplemented from App::TransactionalObject.
References Gui::Detach, and Gui::ViewProvider::testStatus().
Referenced by onBeforeChange().
isShowable()
bool ViewProviderDocumentObject::isShowable () const
Referenced by setModeSwitch().
isUpdateForced()
virtual bool Gui::ViewProviderDocumentObject::isUpdateForced () const virtual
Reimplemented in PartGui::ViewProviderPartExt.
onBeforeChange()
void ViewProviderDocumentObject::onBeforeChange (const App::Property * prop) override protected virtual
get called before the value is changed
Reimplemented from Gui::ViewProvider.
Reimplemented in Gui::ViewProviderLink.
References getObject(), isAttachedToDocument(), Gui::ViewProvider::onBeforeChange(), and App::TransactionalObject::onBeforeChangeProperty().
Referenced by Gui::ViewProviderLink::onBeforeChange(), and PathScripts.PathGui.QuantitySpinBox::updateProperty().
onChanged()
void ViewProviderDocumentObject::onChanged (const App::Property * prop) override protected virtual
Gets called by the container whenever a property has been changed.
Reimplemented from Gui::ViewProvider.
Reimplemented in FemGui::ViewProviderFemPostPlaneFunction, PartDesignGui::ViewProviderDatumCoordinateSystem, TechDrawGui::ViewProviderBalloon, TechDrawGui::ViewProviderDimension, TechDrawGui::ViewProviderLeader, TechDrawGui::ViewProviderRichAnno, TechDrawGui::ViewProviderWeld, Gui::ViewProviderAnnotation, Gui::ViewProviderAnnotationLabel, Gui::ViewProviderGeometryObject, Gui::ViewProviderMeasureDistance, Gui::ViewProviderOrigin, Gui::ViewProviderOriginFeature, Gui::ViewProviderTextDocument, FemGui::ViewProviderFemConstraint, FemGui::ViewProviderFemMesh, FemGui::ViewProviderFemPostFunctionProvider, FemGui::ViewProviderFemPostFunction, FemGui::ViewProviderFemPostObject, InspectionGui::ViewProviderInspection, MeshGui::ViewProviderMesh, MeshGui::ViewProviderMeshCurvature, MeshGui::ViewProviderMeshDefects, MeshGui::ViewProviderMeshNode, PartGui::ViewProvider2DObjectGrid, PartGui::ViewProviderCustom, PartGui::ViewProviderPartReference, PartDesignGui::ViewProviderDatumPoint, PathGui::ViewProviderPath, PointsGui::ViewProviderPoints, RobotGui::ViewProviderRobotObject, SketcherGui::ViewProviderCustom, TechDrawGui::ViewProviderImage, TechDrawGui::ViewProviderProjGroup, TechDrawGui::ViewProviderViewPart, TechDrawGui::ViewProviderViewSection, Gui::ViewProviderLink, Gui::ViewProviderPart, Gui::ViewProviderPlacement, PartGui::ViewProviderPartExt, PartDesignGui::ViewProvider, PartDesignGui::ViewProviderBody, PartDesignGui::ViewProviderBoolean, PartDesignGui::ViewProviderSubShapeBinder, SketcherGui::ViewProviderSketch, TechDrawGui::ViewProviderDrawingView, TechDrawGui::ViewProviderGeomHatch, TechDrawGui::ViewProviderHatch, TechDrawGui::ViewProviderPage, and TechDrawGui::ViewProviderTemplate.
References Gui::SoFCSelectionRoot::Box, DisplayMode, Gui::SoFCSelectionRoot::Full, App::Property::getFullName(), getObject(), Gui::ViewProvider::getRoot(), App::PropertyEnumeration::getValue(), hide(), Gui::Document::isModified(), App::Property::NoModify, Gui::ViewProvider::onChanged(), pcDocument, SelectionStyle, setActiveMode(), Gui::Document::setModified(), App::PropertyBool::setValue(), show(), App::Property::testStatus(), Gui::ViewProvider::testStatus(), App::Property::User1, App::Property::User2, and App::DocumentObject::Visibility.
Referenced by ArchStructure.CommandStructuralSystem::Activated(), draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSite.Compass::buildCoordinates(), draftobjects.wire.Wire::execute(), TechDrawGui::ViewProviderBalloon::onChanged(), Gui::ViewProviderAnnotation::onChanged(), Gui::ViewProviderAnnotationLabel::onChanged(), Gui::ViewProviderGeometryObject::onChanged(), Gui::ViewProviderMeasureDistance::onChanged(), Gui::ViewProviderOrigin::onChanged(), Gui::ViewProviderTextDocument::onChanged(), FemGui::ViewProviderFemPostFunctionProvider::onChanged(), FemGui::ViewProviderFemPostFunction::onChanged(), TechDrawGui::ViewProviderImage::onChanged(), Gui::ViewProviderLink::onChanged(), Gui::ViewProviderPart::onChanged(), TechDrawGui::ViewProviderDrawingView::onChanged(), TechDrawGui::ViewProviderGeomHatch::onChanged(), TechDrawGui::ViewProviderPage::onChanged(), TechDrawGui::ViewProviderTemplate::onChanged(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchPanel.ViewProviderPanelSheet::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), and draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData().
onPropertyStatusChanged()
void ViewProviderDocumentObject::onPropertyStatusChanged (const App::Property & prop, unsigned long oldStatus) override protected virtual
get called when a property status has changed
Reimplemented from App::PropertyContainer.
References App::DocumentObject::getDocument(), App::Document::isAnyRestoring(), pcObject, and App::Document::signalChangePropertyEditor.
reattach()
void ViewProviderDocumentObject::reattach (App::DocumentObject * pcObj) virtual
Reimplemented in Gui::ViewProviderLink.
Referenced by Gui::ViewProviderLink::reattach(), and Gui::Document::slotNewObject().
removeDynamicProperty()
bool ViewProviderDocumentObject::removeDynamicProperty (const char * prop) override virtual
Reimplemented from App::PropertyContainer.
References App::Document::addOrRemovePropertyOfObject(), App::DocumentObject::getDocument(), App::PropertyContainer::getDynamicPropertyByName(), getObject(), App::Property::LockDynamic, App::PropertyContainer::removeDynamicProperty(), and App::Property::testStatus().
replaceObject()
int ViewProviderDocumentObject::replaceObject (App::DocumentObject * oldObj, App::DocumentObject * newObj) override virtual
Replace an object to the view provider by drag and drop.
Parameters
oldObj object to be replaced
newObj object to replace with
Returns
Returns 0 if not found, 1 if succeeded, -1 if not supported
Reimplemented from Gui::ViewProvider.
References App::GetApplication(), App::DocumentObject::getNameInDocument(), getObject(), draftfunctions.move::move(), and Gui::ViewProvider::replaceObject().
setActiveMode()
void ViewProviderDocumentObject::setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
References DisplayMode, App::PropertyEnumeration::getValueAsString(), Gui::ViewProvider::hide(), App::PropertyEnumeration::isValid(), and Gui::ViewProvider::setDisplayMode().
Referenced by InspectionGui::ViewProviderInspection::OnChange(), MeshGui::ViewProviderMeshCurvature::OnChange(), onChanged(), Gui::ViewProviderLink::onChanged(), Gui::Document::slotNewObject(), MeshGui::ViewProviderMeshCurvature::updateData(), PointsGui::ViewProviderScattered::updateData(), and PointsGui::ViewProviderStructured::updateData().
setModeSwitch()
void ViewProviderDocumentObject::setModeSwitch () override protected virtual
Turn on mode switch.
Reimplemented from Gui::ViewProvider.
References isShowable(), and Gui::ViewProvider::setModeSwitch().
Referenced by setShowable().
setShowable()
void ViewProviderDocumentObject::setShowable (bool enable)
References Gui::ViewProvider::getModeSwitch(), Gui::ViewProvider::hide(), and setModeSwitch().
Referenced by Gui::DocumentObjectData::updateChildren().
show()
void ViewProviderDocumentObject::show (void) override virtual
Show the object in the view.
Reimplemented from Gui::ViewProvider.
Reimplemented in MeshGui::ViewProviderMeshCurvature, DrawingGui::ViewProviderDrawingPage, DrawingGui::ViewProviderDrawingView, DrawingGui::ViewProviderDrawingClip, FemGui::ViewProviderFemAnalysis, FemGui::ViewProviderFemPostObject, InspectionGui::ViewProviderInspection, TechDrawGui::ViewProviderViewClip, TechDrawGui::ViewProviderDrawingView, TechDrawGui::ViewProviderPage, and TechDrawGui::ViewProviderTemplate.
References getObject(), Gui::TreeWidget::isObjectShowable(), App::PropertyBool::setValue(), Gui::ViewProvider::show(), App::Property::User2, and App::DocumentObject::Visibility.
Referenced by Gui::DAG::Model::mousePressEvent(), MeshGui::ViewProviderMeshDefects::onChanged(), PathGui::ViewProviderPath::onChanged(), onChanged(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), MeshGui::ViewProviderMeshCurvature::show(), FemGui::ViewProviderFemAnalysis::show(), FemGui::ViewProviderFemPostObject::show(), Mod.Show.mTempoVis.TempoVis::show_all_dependencies(), Mod.Show.mTempoVis.TempoVis::show_all_dependent(), PathGui::ViewProviderPath::showBoundingBox(), Gui::ViewProviderGeometryObject::showBoundingBox(), MeshGui::ViewProviderMesh::showOpenEdges(), MeshGui::ViewProviderIndexedFaceSet::showOpenEdges(), MeshGui::ViewProviderMeshObject::showOpenEdges(), MeshGui::ViewProviderMeshFaceSet::showOpenEdges(), MeshGui::ViewProviderMeshNode::showOpenEdges(), and PartDesignGui::TaskHoleParameters::TaskHoleParameters().
showInTree()
bool ViewProviderDocumentObject::showInTree () const override virtual
Tell the tree view if this object should appear there.
Reimplemented from Gui::ViewProvider.
References App::PropertyBool::getValue(), and ShowInTree.
Referenced by Gui::TreeWidget::contextMenuEvent(), Gui::DocumentObjectData::DocumentObjectData(), Gui::DocumentObjectItem::testStatus(), and Gui::DocumentItem::updateItemsVisibility().
startDefaultEditMode()
void ViewProviderDocumentObject::startDefaultEditMode ()
Start the edit mode with ViewProvider::Default.
References Gui::ViewProvider::Default, getDocument(), getObject(), Gui::Command::openCommand(), and Gui::Document::setEdit().
Referenced by addDefaultAction(), TechDrawGui::ViewProviderBalloon::doubleClicked(), TechDrawGui::ViewProviderDimension::doubleClicked(), TechDrawGui::QGIBalloonLabel::mouseDoubleClickEvent(), TechDrawGui::QGIDatumLabel::mouseDoubleClickEvent(), PartGui::ViewProviderPrimitive::setupContextMenu(), TechDrawGui::ViewProviderBalloon::setupContextMenu(), and TechDrawGui::ViewProviderDimension::setupContextMenu().
startRestoring()
void ViewProviderDocumentObject::startRestoring () virtual
Reimplemented in DrawingGui::ViewProviderDrawingView, DrawingGui::ViewProviderDrawingClip, TechDrawGui::ViewProviderDrawingView, and TechDrawGui::ViewProviderPage.
References hide().
Referenced by TechDrawGui::ViewProviderDrawingView::startRestoring(), and TechDrawGui::ViewProviderPage::startRestoring().
update()
void ViewProviderDocumentObject::update (const App::Property * prop) override virtual
update the content of the ViewProvider this method have to implement the recalculation of the ViewProvider.
There are different reasons to update. E.g. only the view attribute has changed, or the data has manipulated.
Reimplemented from Gui::ViewProvider.
References getObject(), Gui::ViewProvider::isRestoring(), Gui::ViewProvider::update(), and App::Property::User1.
Referenced by ArchStructure.CommandStructuralSystem::Activated(), ArchAxisSystem.AxisSystemTaskPanel::addElement(), ArchComponent.ComponentTaskPanel::addElement(), ArchSectionPlane.SectionPlaneTaskPanel::addElement(), DraftGui.FacebinderTaskPanel::addElement(), femtaskpanels.task_result_mechanical._TaskPanel::calculate(), Gui::ViewProviderLink::callDraggerProxy(), Spreadsheet_legacy.SpreadsheetView::changeCell(), draftguitools.gui_edit.Edit::endEditing(), draftguitools.gui_trackers.boxTracker::height(), draftguitools.gui_trackers.rectangleTracker::p3(), Plot.Plot::plot(), Spreadsheet_legacy.SpreadsheetView::recompute(), ArchAxisSystem.AxisSystemTaskPanel::removeElement(), ArchComponent.ComponentTaskPanel::removeElement(), ArchSectionPlane.SectionPlaneTaskPanel::removeElement(), DraftGui.FacebinderTaskPanel::removeElement(), draftguitools.gui_trackers.gridTracker::reset(), ArchNesting.Nester::run(), draftguitools.gui_trackers.gridTracker::setMainlines(), draftguitools.gui_trackers.gridTracker::setSize(), draftguitools.gui_trackers.gridTracker::setSpacing(), and draftguitools.gui_edit_arch_objects.ArchWallGuiTools::update_object_from_edit_points().
updateView()
void ViewProviderDocumentObject::updateView ()
Run a redraw.
References App::ExtensionContainer::getPropertyMap(), Gui::ViewProvider::hide(), Gui::ViewProvider::isShow(), pcObject, Gui::ViewProvider::show(), Gui::ViewProvider::testStatus(), Gui::ViewProvider::updateData(), and App::Property::User1.
Referenced by Gui::ViewProviderLink::onChanged(), and Gui::Document::slotNewObject().
Friends And Related Function Documentation
Document
friend class Document friend
Member Data Documentation
DisplayMode
App::PropertyEnumeration Gui::ViewProviderDocumentObject::DisplayMode
Referenced by attach(), onChanged(), PartDesignGui::ViewProviderBody::onChanged(), setActiveMode(), PartDesignGui::ViewProviderDatum::ViewProviderDatum(), Gui::ViewProviderLink::ViewProviderLink(), Gui::ViewProviderTextDocument::ViewProviderTextDocument(), and ~ViewProviderDocumentObject().
OnTopWhenSelected
App::PropertyEnumeration Gui::ViewProviderDocumentObject::OnTopWhenSelected
Referenced by Gui::ElementColors::ElementColors(), Gui::ElementColors::Private::Private(), PartDesignGui::ViewProviderDatumCoordinateSystem::ViewProviderDatumCoordinateSystem(), Gui::ViewProviderTextDocument::ViewProviderTextDocument(), and Gui::ElementColors::Private::~Private().
pcDocument
Gui::Document* Gui::ViewProviderDocumentObject::pcDocument protected
Referenced by getDocument(), onChanged(), and Gui::Document::slotNewObject().
pcObject
App::DocumentObject* Gui::ViewProviderDocumentObject::pcObject protected
Referenced by MeshGui::ViewProviderMesh::addSelection(), Gui::ViewProviderAnnotation::attach(), Gui::ViewProviderMeasureDistance::attach(), Gui::ViewProviderOriginFeature::attach(), FemGui::ViewProviderFemConstraint::attach(), MeshGui::ViewProviderMeshTransformDemolding::attach(), Gui::ViewProviderPlacement::attach(), PartDesignGui::ViewProviderBody::attach(), attach(), Gui::ViewProviderOrigin::attach(), MeshGui::ViewProviderMeshTransformDemolding::calcNormalVector(), Gui::ViewProviderLink::canDropObjectEx(), MeshGui::ViewProviderMesh::canHighlightColors(), MeshGui::ViewProviderMesh::clearSelection(), MeshGui::ViewProviderMeshCurvature::curvatureInfo(), PointsGui::ViewProviderScattered::cut(), PointsGui::ViewProviderStructured::cut(), MeshGui::ViewProviderMesh::deleteSelection(), MeshGui::ViewProviderMesh::deselectComponent(), MeshGui::ViewProviderMesh::deselectFacet(), PartGui::ViewProviderPart::doubleClicked(), PartDesignGui::ViewProvider::doubleClicked(), PartDesignGui::ViewProviderDatum::doubleClicked(), RobotGui::ViewProviderRobotObject::DraggerMotionCallback(), MeshGui::ViewProviderMesh::exportToVrml(), findFrontRootOfType(), getActiveView(), MeshGui::ViewProviderMesh::getColorProperty(), PointsGui::ViewProviderPoints::getDisplayModes(), getDocument(), TechDrawGui::ViewProviderPage::getDrawPage(), getEditingView(), PathGui::ViewProviderPath::getElement(), MeshGui::ViewProviderMesh::getFacetsFromPolygon(), TechDrawGui::ViewProviderLeader::getFeature(), TechDrawGui::ViewProviderRichAnno::getFeature(), TechDrawGui::ViewProviderTile::getFeature(), getFullName(), InspectionGui::ViewProviderInspection::getIcon(), getInventorView(), getLinkedViewProvider(), Gui::ViewProviderLink::getLinkExtension(), DrawingGui::ViewProviderDrawingPage::getPageObject(), Gui::ViewProviderLink::getPropertyByName(), SketcherGui::ViewProviderSketch::getSketchObject(), SpreadsheetGui::ViewProviderSheet::getSpreadsheetObject(), TechDrawGui::ViewProviderTemplate::getTemplate(), TechDrawGui::ViewProviderAnnotation::getViewObject(), TechDrawGui::ViewProviderBalloon::getViewObject(), TechDrawGui::ViewProviderDimension::getViewObject(), TechDrawGui::ViewProviderDrawingView::getViewObject(), TechDrawGui::ViewProviderGeomHatch::getViewObject(), TechDrawGui::ViewProviderHatch::getViewObject(), TechDrawGui::ViewProviderImage::getViewObject(), TechDrawGui::ViewProviderLeader::getViewObject(), TechDrawGui::ViewProviderProjGroup::getViewObject(), TechDrawGui::ViewProviderProjGroupItem::getViewObject(), TechDrawGui::ViewProviderRichAnno::getViewObject(), TechDrawGui::ViewProviderSpreadsheet::getViewObject(), TechDrawGui::ViewProviderSymbol::getViewObject(), TechDrawGui::ViewProviderViewClip::getViewObject(), TechDrawGui::ViewProviderViewPart::getViewObject(), TechDrawGui::ViewProviderViewSection::getViewObject(), TechDrawGui::ViewProviderWeld::getViewObject(), getViewOfNode(), MeshGui::ViewProviderMesh::getVisibleFacets(), MeshGui::ViewProviderMeshNode::handleEvent(), MeshGui::ViewProviderMesh::hasSelection(), MeshGui::ViewProviderMesh::highlightColors(), MeshGui::ViewProviderMesh::highlightComponents(), MeshGui::ViewProviderMesh::highlightSegments(), MeshGui::ViewProviderMesh::highlightSelection(), InspectionGui::ViewProviderInspection::inspectDistance(), MeshGui::ViewProviderMesh::invertSelection(), MeshGui::ViewProviderMesh::isFacetSelected(), FemGui::ViewProviderFemMesh::onChanged(), onPropertyStatusChanged(), PathGui::ViewProviderPath::recomputeBoundingBox(), MeshGui::ViewProviderMesh::removeFacets(), MeshGui::ViewProviderMesh::removeSelection(), MeshGui::ViewProviderMesh::segmentMesh(), MeshGui::ViewProviderMesh::selectArea(), MeshGui::ViewProviderMesh::selectComponent(), MeshGui::ViewProviderMesh::selectFacet(), RobotGui::ViewProviderRobotObject::setAxisTo(), PointsGui::ViewProviderPoints::setDisplayMode(), InspectionGui::ViewProviderInspection::setDistances(), RobotGui::ViewProviderRobotObject::setDragger(), FemGui::ViewProviderFemMesh::setHighlightNodes(), MeshGui::ViewProviderMesh::setSelection(), MeshGui::ViewProviderMeshCurvature::setVertexCurvatureMode(), PartDesignGui::ViewProviderBody::setVisualBodyMode(), MeshGui::ViewProviderMeshOrientation::showDefects(), MeshGui::ViewProviderMeshNonManifolds::showDefects(), MeshGui::ViewProviderMeshNonManifoldPoints::showDefects(), MeshGui::ViewProviderMeshDuplicatedFaces::showDefects(), MeshGui::ViewProviderMeshDegenerations::showDefects(), MeshGui::ViewProviderMeshDuplicatedPoints::showDefects(), MeshGui::ViewProviderMeshIndices::showDefects(), MeshGui::ViewProviderMeshSelfIntersections::showDefects(), MeshGui::ViewProviderMeshFolds::showDefects(), DrawingGui::ViewProviderDrawingPage::showDrawingView(), TechDrawGui::ViewProviderPage::showMDIViewPage(), MeshGui::ViewProviderIndexedFaceSet::showOpenEdges(), MeshGui::ViewProviderMeshFaceSet::showOpenEdges(), MeshGui::ViewProviderMeshNode::showOpenEdges(), SpreadsheetGui::ViewProviderSheet::showSpreadsheetView(), MeshGui::ViewProviderMesh::splitMesh(), MeshGui::ViewProviderMesh::trimMesh(), MeshGui::ViewProviderMesh::tryColorPerVertexOrFace(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), PartDesignGui::ViewProviderAddSub::updateAddSubShapeIndicator(), Gui::ViewProviderInventorObject::updateData(), Gui::ViewProviderVRMLObject::updateData(), DrawingGui::ViewProviderDrawingPage::updateData(), ImageGui::ViewProviderImagePlane::updateData(), InspectionGui::ViewProviderInspection::updateData(), MeshGui::ViewProviderMeshCurvature::updateData(), PathGui::ViewProviderPath::updateData(), RobotGui::ViewProviderRobotObject::updateData(), RobotGui::ViewProviderTrajectory::updateData(), Gui::ViewProviderLink::updateData(), PathGui::ViewProviderPath::updateShowConstraints(), updateView(), PartGui::ViewProviderPartExt::updateVisual(), and PathGui::ViewProviderPath::updateVisual().
SelectionStyle
App::PropertyEnumeration Gui::ViewProviderDocumentObject::SelectionStyle
Referenced by PathGui::ViewProviderPath::getBoundColor(), MeshGui::ViewProviderMesh::onChanged(), PathGui::ViewProviderPath::onChanged(), PointsGui::ViewProviderPoints::onChanged(), onChanged(), PathGui::ViewProviderPath::useNewSelectionModel(), PointsGui::ViewProviderPoints::ViewProviderPoints(), and Gui::ViewProviderTextDocument::ViewProviderTextDocument().
ShowInTree
App::PropertyBool Gui::ViewProviderDocumentObject::ShowInTree
Referenced by showInTree().
Visibility
App::PropertyBool Gui::ViewProviderDocumentObject::Visibility
Referenced by PartDesignGui::TaskDlgBooleanParameters::accept(), TechDrawGui::QGIView::isVisible(), Gui::ViewProviderLink::onChanged(), and PartDesignGui::ViewProviderBody::slotChangedObjectGui().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/ViewProviderDocumentObject.h
FreeCAD/src/Gui/ViewProviderDocumentObject.cpp