FreeCAD: StdMeshers::FunctionIntegral Class Reference
StdMeshers::FunctionIntegral Class Reference
#include <StdMeshers_Distribution.hxx>
Public Member Functions
FunctionIntegral (const Function *, const double)
virtual double integral (const double, const double) const
virtual bool value (const double, double &) const
virtual ~FunctionIntegral ()
Public Member Functions inherited from StdMeshers::Function
Function (const int)
virtual double integral (const double, const double) const =0
virtual bool value (const double, double &) const
virtual ~Function ()
Constructor & Destructor Documentation
FunctionIntegral()
StdMeshers::FunctionIntegral::FunctionIntegral (const Function * f, const double st)
~FunctionIntegral()
StdMeshers::FunctionIntegral::~FunctionIntegral () virtual
Member Function Documentation
integral()
double StdMeshers::FunctionIntegral::integral (const double , const double) const virtual
Implements StdMeshers::Function.
value()
bool StdMeshers::FunctionIntegral::value (const double t, double & f) const virtual
Reimplemented from StdMeshers::Function.
References StdMeshers::Function::integral(), and StdMeshers::Function::value().
Referenced by PathScripts.PathProperty.Property::displayString(), PathScripts.PathProperty.PropertyQuantity::displayString(), PathScripts.PathSetupSheetOpPrototype.Property::displayString(), PathScripts.PathSetupSheetOpPrototype.PropertyQuantity::displayString(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), PathScripts.PathProperty.Property::getValue(), PathScripts.PathSetupSheetOpPrototype.Property::getValue(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), PathScripts.PathProperty.Property::setValue(), and PathScripts.PathSetupSheetOpPrototype.Property::setValue().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_Distribution.hxx
FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_Distribution.cpp