FreeCAD: Import::ExportOCAF2 Class Reference
Import::ExportOCAF2 Class Reference
#include <ImportOCAF2.h>
Public Types
typedef std::function< std::map< std::string, App::Color > App::DocumentObject *, const char *)> GetShapeColorsFunc
Public Member Functions
bool canFallback (std::vector< App::DocumentObject * > objs)
void exportObjects (std::vector< App::DocumentObject * > &objs, const char *name=0)
ExportOCAF2 (Handle(TDocStd_Document) h, GetShapeColorsFunc func=GetShapeColorsFunc())
void setExportHiddenObject (bool enable)
void setKeepPlacement (bool enable)
Member Typedef Documentation
GetShapeColorsFunc
typedef std::function<std::map<std::string,App::Color> App::DocumentObject*, const char*)> Import::ExportOCAF2::GetShapeColorsFunc
Constructor & Destructor Documentation
ExportOCAF2()
ExportOCAF2::ExportOCAF2 (Handle(TDocStd_Document) h, GetShapeColorsFunc func = GetShapeColorsFunc())
References App::Color::a, App::GetApplication(), App::Application::GetParameterGroupByPath(), and App::Color::setPackedValue().
Member Function Documentation
canFallback()
bool ExportOCAF2::canFallback (std::vector< App::DocumentObject * > objs)
exportObjects()
void ExportOCAF2::exportObjects (std::vector< App::DocumentObject * > & objs, const char * name = 0)
setExportHiddenObject()
void Import::ExportOCAF2::setExportHiddenObject (bool enable)
setKeepPlacement()
void Import::ExportOCAF2::setKeepPlacement (bool enable)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Import/App/ImportOCAF2.h
Sources/FreeCAD/src/Mod/Import/App/ImportOCAF2.cpp