FreeCAD: PathScripts.PathPocketShape Namespace Reference
PathScripts.PathPocketShape Namespace Reference
Classes
class Extension
class ObjectPocket
Functions
def Create (name, obj=None)
def endPoints (edgeOrWire)
def extendWire (feature, wire, length)
def includesPoint (p, pts)
def selectOffsetWire (feature, wires)
def SetupProperties ()
def translate (context, text, disambig=None)
Variables
Draft = LazyLoader('Draft', globals(), 'Draft')
Part = LazyLoader('Part', globals(), 'Part')
TechDraw = LazyLoader('TechDraw', globals(), 'TechDraw')
Function Documentation
Create()
def PathScripts.PathPocketShape.Create (name, obj = None)
Create(name) ... Creates and returns a Pocket operation.
endPoints()
def PathScripts.PathPocketShape.endPoints (edgeOrWire)
endPoints(edgeOrWire) ... return the first and last point of the wire or the edge, assuming the argument is not a closed wire.
Referenced by PathScripts.PathPocketShape.extendWire(), and PathScripts.PathPocketShape.Extension.getWire().
extendWire()
def PathScripts.PathPocketShape.extendWire (feature, wire, length)
extendWire(wire, length) ... return a closed Wire which extends wire by length
References PathScripts.PathPocketShape.endPoints(), PathScripts.PathPocketShape.includesPoint(), and PathScripts.PathPocketShape.selectOffsetWire().
Referenced by PathScripts.PathPocketShape.Extension.getSubLink(), and PathScripts.PathPocketShape.Extension.getWire().
includesPoint()
def PathScripts.PathPocketShape.includesPoint (p, pts)
includesPoint(p, pts) ... answer True if the collection of pts includes the point p
Referenced by PathScripts.PathPocketShape.extendWire().
selectOffsetWire()
def PathScripts.PathPocketShape.selectOffsetWire (feature, wires)
selectOffsetWire(feature, wires) ... returns the Wire in wires which is does not intersect with feature
Referenced by PathScripts.PathPocketShape.extendWire().
SetupProperties()
def PathScripts.PathPocketShape.SetupProperties ()
translate()
def PathScripts.PathPocketShape.translate (context, text, disambig = None)
Variable Documentation
Draft
PathScripts.PathPocketShape.Draft = LazyLoader('Draft', globals(), 'Draft')
Part
PathScripts.PathPocketShape.Part = LazyLoader('Part', globals(), 'Part')
TechDraw
PathScripts.PathPocketShape.TechDraw = LazyLoader('TechDraw', globals(), 'TechDraw')