FreeCAD: MeshGui::MeshFillHole Class Reference
MeshGui::MeshFillHole Class Reference
Display data of a mesh kernel.
#include <MeshEditor.h>
Public Slots
void finishEditing ()
Public Member Functions
MeshFillHole (MeshHoleFiller &hf, Gui::View3DInventor *parent)
void startEditing (ViewProviderMesh *)
virtual ~MeshFillHole ()
Detailed Description
Display data of a mesh kernel.
Author
Werner Mayer
Constructor & Destructor Documentation
MeshFillHole()
MeshFillHole::MeshFillHole (MeshHoleFiller & hf, Gui::View3DInventor * parent)
~MeshFillHole()
MeshFillHole::~MeshFillHole () virtual
Member Function Documentation
finishEditing
void MeshFillHole::finishEditing () slot
References OfflineRenderingUtils::viewer().
startEditing()
void MeshFillHole::startEditing (MeshGui::ViewProviderMesh * vp)
References draftgeoutils.faces::bind(), Gui::coinRemoveAllChildren(), App::GetApplication(), Gui::ViewProviderDocumentObject::getObject(), App::Application::signalChangedObject, and OfflineRenderingUtils::viewer().
Referenced by draftguitools.gui_edit.Edit::mousePressed().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/Gui/MeshEditor.h
FreeCAD/src/Mod/Mesh/Gui/MeshEditor.cpp