FreeCAD: Base::FileInfo Class Reference
Base::FileInfo Class Reference
File name unification This class handles everything related to file names the file names are internal generally UTF-8 encoded on all platforms.
#include <FileInfo.h>
Public Types
enum Permissions { WriteOnly = 0x01 , ReadOnly = 0x02 , ReadWrite = 0x03 }
Public Member Functions
FileInfo (const char *_FileName="")
Construction.
FileInfo (const std::string &_FileName)
void setFile (const char *name)
Set a new file name.
void setFile (const std::string &name)
Set a new file name.
extraction of information
std::string filePath () const
Returns the file name, including the path (which may be absolute or relative).
std::string dirPath () const
Returns the dir path name (which may be absolute or relative).
std::string fileName () const
Returns the name of the file, excluding the path, including the extension.
std::string fileNamePure () const
Returns the name of the file, excluding the path and the extension.
std::wstring toStdWString () const
Convert the path name into a UTF-16 encoded wide string format.
std::string extension () const
Returns the extension of the file.
std::string completeExtension () const
Returns the complete extension of the file.
bool hasExtension (const char *Ext) const
Checks for a special extension, NOT case sensitive.
methods to test the status of the file or dir
bool exists () const
Does the file exist?
bool isReadable () const
Checks if the file exist and is readable.
bool isWritable () const
Checks if the file exist and is writable.
bool setPermissions (Permissions)
Tries to set the file permission.
bool isFile () const
Checks if it is a file (not a directory)
bool isDir () const
Checks if it is a directory (not a file)
unsigned int size () const
The size of the file.
TimeInfo lastModified () const
Returns the time when the file was last modified.
TimeInfo lastRead () const
Returns the time when the file was last read (accessed).
Directory management
bool createDirectory () const
Creates a directory. Returns true if successful; otherwise returns false.
bool createDirectories () const
Creates a directory and all its parent directories. Returns true if successful; otherwise returns false.
std::vector< Base::FileInfo > getDirectoryContent () const
Get a list of the directory content.
bool deleteDirectory () const
Delete an empty directory.
bool deleteDirectoryRecursive () const
Delete a directory and all its content.
bool deleteFile () const
Delete the file.
bool renameFile (const char *NewName)
Rename the file.
bool copyTo (const char *NewName) const
Rename the file.
Tools
std::string FileName
static std::string getTempFileName (const char *FileName=nullptr, const char *path=nullptr)
Get a unique File Name in the given or (if 0) in the temp path.
static const std::string & getTempPath ()
Get the path to the dir which is considered to temp files.
static std::string pathToString (const boost::filesystem::path &p)
Convert from filesystem path to string.
static boost::filesystem::path stringToPath (const std::string &str)
Convert from string to filesystem path.
Detailed Description
File name unification This class handles everything related to file names the file names are internal generally UTF-8 encoded on all platforms.
Member Enumeration Documentation
Permissions
enum Base::FileInfo::Permissions
Enumerator
WriteOnly
ReadOnly
ReadWrite
Constructor & Destructor Documentation
FileInfo() [1/2]
FileInfo::FileInfo (const char * _FileName = "")
Construction.
References setFile().
Referenced by getDirectoryContent().
FileInfo() [2/2]
FileInfo::FileInfo (const std::string & _FileName)
References setFile().
Member Function Documentation
completeExtension()
std::string FileInfo::completeExtension () const
Returns the complete extension of the file.
The complete extension consists of all characters in the file after (but not including) the first '.' character.
FileInfo fi("/tmp/archive.tar.gz");
ext = fi.completeExtension();   // ext = "tar.gz"
References FileName.
copyTo()
bool FileInfo::copyTo (const char * NewName) const
Rename the file.
References FileName, and toStdWString().
Referenced by TechDraw::DrawUtil::copyFile(), and App::PropertyFileIncluded::Paste().
createDirectories()
bool FileInfo::createDirectories () const
Creates a directory and all its parent directories. Returns true if successful; otherwise returns false.
References FileName, and stringToPath().
Referenced by App::Document::onChanged().
createDirectory()
bool FileInfo::createDirectory () const
Creates a directory. Returns true if successful; otherwise returns false.
References FileName, and toStdWString().
Referenced by App::VRMLObject::makeDirectories(), Gui::AutoSaver::slotCreateDocument(), Base::FileWriter::writeFiles(), and Gui::RecoveryWriter::writeFiles().
deleteDirectory()
bool FileInfo::deleteDirectory () const
Delete an empty directory.
References FileName, isDir(), and toStdWString().
Referenced by deleteDirectoryRecursive().
deleteDirectoryRecursive()
bool FileInfo::deleteDirectoryRecursive () const
Delete a directory and all its content.
References deleteDirectory(), getDirectoryContent(), isDir(), and ReadWrite.
Referenced by App::Document::~Document().
deleteFile()
bool FileInfo::deleteFile () const
Delete the file.
References FileName, and toStdWString().
Referenced by StdCmdDuplicateSelection::activated(), Gui::MainWindow::closeEvent(), App::Document::importLinks(), MeshGui::RemeshGmsh::loadOutput(), MeshPartGui::Mesh2ShapeGmsh::loadOutput(), App::PropertyFileIncluded::Paste(), Fem::FemMesh::RestoreDocFile(), Fem::PropertyPostDataObject::RestoreDocFile(), Gui::Application::runApplication(), Fem::FemMesh::SaveDocFile(), and Fem::PropertyPostDataObject::SaveDocFile().
dirPath()
std::string FileInfo::dirPath () const
Returns the dir path name (which may be absolute or relative).
References FileName.
Referenced by Mesh::AmfExporter::AmfExporter(), Import::ImportOCAF2::ImportOCAF2(), Mesh::MeshObject::load(), App::VRMLObject::onChanged(), App::PropertyFileIncluded::Paste(), App::VRMLObject::RestoreDocFile(), Mesh::MeshObject::save(), Import::ImportOCAF2::setMode(), and App::PropertyFileIncluded::setValue().
exists()
bool FileInfo::exists () const
Does the file exist?
References FileName, and toStdWString().
Referenced by Gui::ViewProviderVRMLObject::addResource(), Mesh::AmfExporter::AmfExporter(), Gui::MainWindow::closeEvent(), App::PropertyFileIncluded::getUniqueFileName(), Part::ImportStepParts(), isDir(), isFile(), lastModified(), lastRead(), MeshCore::MeshInput::LoadAny(), Drawing::FeaturePage::onChanged(), App::Document::onChanged(), Drawing::FeaturePage::onDocumentRestored(), Raytracing::LuxProject::onDocumentRestored(), Raytracing::RayProject::onDocumentRestored(), App::Application::openDocumentPrivate(), App::PropertyFileIncluded::Paste(), Import::StepShape::read(), App::PropertyFileIncluded::RestoreDocFile(), App::PropertyFileIncluded::Save(), MeshCore::MeshOutput::SaveAny(), App::VRMLObject::SaveDocFile(), App::PropertyFileIncluded::setValue(), and Gui::Application::sLoadFile().
extension()
std::string FileInfo::extension () const
Returns the extension of the file.
The extension consists of all characters in the file after (but not including) the last '.' character.
FileInfo fi("/tmp/archive.tar.gz");
ext = fi.extension();   // ext = "gz"
References FileName.
Referenced by Gui::Application::exportTo(), Base::Writer::getUniqueFileName(), hasExtension(), Gui::Application::importFrom(), TechDraw::DrawHatch::isBitmapHatch(), TechDraw::DrawHatch::isSvgHatch(), TechDraw::DrawViewSection::makeLineSets(), Gui::Application::open(), App::Application::processCmdLineFiles(), Fem::PropertyPostDataObject::RestoreDocFile(), App::PropertyFileIncluded::setValue(), and Gui::Application::sLoadFile().
fileName()
std::string FileInfo::fileName () const
Returns the name of the file, excluding the path, including the extension.
References FileName.
Referenced by Mesh::AmfExporter::AmfExporter(), Drawing::FeaturePage::execute(), TechDraw::DrawSVGTemplate::execute(), fileNamePure(), TechDraw::DrawSVGTemplate::getEditableTextsFromTemplate(), Drawing::FeaturePage::getEditableTextsFromTemplate(), Base::FileException::getFileName(), Base::FileException::getPyObject(), App::VRMLObject::getRelativePath(), Drawing::FeaturePage::onDocumentRestored(), Raytracing::LuxProject::onDocumentRestored(), Raytracing::RayProject::onDocumentRestored(), App::PropertyFileIncluded::Paste(), TechDrawGui::QGSPage::postProcessXml(), and App::PropertyFileIncluded::setValue().
fileNamePure()
std::string FileInfo::fileNamePure () const
Returns the name of the file, excluding the path and the extension.
References fileName().
Referenced by Base::Writer::getUniqueFileName(), Part::ImportIgesParts(), Part::ImportStepParts(), App::Application::openDocumentPrivate(), Fem::FemMesh::read(), Gui::Application::sAddCommand(), Mesh::MeshObject::save(), App::Document::saveAs(), App::PropertyFileIncluded::setValue(), and Fem::FemMesh::write().
filePath()
std::string FileInfo::filePath () const
Returns the file name, including the path (which may be absolute or relative).
References FileName.
Referenced by Mesh::AmfExporter::AmfExporter(), App::Application::closeDocument(), App::PropertyFileIncluded::Copy(), Gui::MainWindow::createMimeDataFromSelection(), Drawing::FeaturePage::execute(), Raytracing::LuxProject::execute(), Raytracing::RayProject::execute(), TechDraw::DrawSVGTemplate::execute(), Gui::Application::exportTo(), WebGui::FcCookieJar::FcCookieJar(), Base::FileException::FileException(), App::Application::getDocumentByPath(), TechDraw::DrawSVGTemplate::getEditableTextsFromTemplate(), Drawing::FeaturePage::getEditableTextsFromTemplate(), CDxfWrite::getPlateFile(), App::PropertyFileIncluded::getUniqueFileName(), Gui::Application::importFrom(), App::Document::onChanged(), Drawing::FeaturePage::onDocumentRestored(), Raytracing::LuxProject::onDocumentRestored(), Raytracing::RayProject::onDocumentRestored(), Gui::Application::open(), App::Application::openDocumentPrivate(), Gui::SoSVGVectorOutput::openFile(), Gui::SoU3DVectorOutput::openFile(), App::PropertyFileIncluded::Paste(), Fem::FemPostPipeline::read(), Fem::FemMesh::read(), Part::TopoShape::read(), Fem::FemMesh::RestoreDocFile(), Fem::PropertyPostDataObject::RestoreDocFile(), Gui::Application::sAddCommand(), App::PropertyFileIncluded::Save(), Fem::FemMesh::SaveDocFile(), Fem::PropertyPostDataObject::SaveDocFile(), App::PropertyFileIncluded::setValue(), Fem::FemMesh::write(), Part::TopoShape::write(), and MeshGui::RemeshGmsh::writeProject().
getDirectoryContent()
std::vector< Base::FileInfo > FileInfo::getDirectoryContent () const
Get a list of the directory content.
References FileInfo(), FileName, and toStdWString().
Referenced by deleteDirectoryRecursive().
getTempFileName()
std::string FileInfo::getTempFileName (const char * FileName = nullptr, const char * path = nullptr) static
Get a unique File Name in the given or (if 0) in the temp path.
References FileName, getTempPath(), and draftgeoutils.general::vec().
Referenced by App::PropertyFileIncluded::getExchangeTempFile(), and App::Application::getTempFileName().
getTempPath()
const std::string & FileInfo::getTempPath () static
Get the path to the dir which is considered to temp files.
References isDir().
Referenced by getTempFileName().
hasExtension()
bool FileInfo::hasExtension (const char * Ext) const
Checks for a special extension, NOT case sensitive.
References extension().
Referenced by Fem::FemPostPipeline::canRead(), Gui::View3DInventorViewer::dumpToFile(), MeshCore::MeshInput::getFormat(), Gui::Application::importFrom(), Points::PointsAlgos::Load(), MeshCore::MeshInput::LoadAny(), Gui::Application::open(), Fem::FemPostPipeline::read(), Fem::FemMesh::read(), Part::TopoShape::read(), Part::PropertyPartShape::RestoreDocFile(), Gui::View3DInventorPy::saveVectorGraphic(), Fem::FemMesh::write(), Part::TopoShape::write(), and Gui::SoFCDB::writeToFile().
isDir()
bool FileInfo::isDir () const
Checks if it is a directory (not a file)
References exists(), FileName, and toStdWString().
Referenced by deleteDirectory(), deleteDirectoryRecursive(), and getTempPath().
isFile()
bool FileInfo::isFile () const
Checks if it is a file (not a directory)
References exists(), FileName, and toStdWString().
Referenced by MeshCore::MeshInput::LoadAny(), and Gui::Application::sLoadFile().
isReadable()
bool FileInfo::isReadable () const
Checks if the file exist and is readable.
References FileName, and toStdWString().
Referenced by TechDraw::Preferences::bitmapFill(), TechDraw::DrawUtil::copyFile(), TechDraw::Preferences::defaultTemplate(), TechDraw::Preferences::defaultTemplateDir(), Drawing::FeaturePage::execute(), Part::CurveNet::execute(), Part::ImportBrep::execute(), Part::ImportIges::execute(), Part::ImportStep::execute(), Raytracing::LuxProject::execute(), Raytracing::RayProject::execute(), TechDraw::DrawParametricTemplate::execute(), TechDraw::DrawSVGTemplate::execute(), TechDraw::DrawGeomHatch::getDecodedSpecsFromFile(), TechDraw::DrawSVGTemplate::getEditableTextsFromTemplate(), Drawing::FeaturePage::getEditableTextsFromTemplate(), CDxfWrite::getPlateFile(), TechDraw::Preferences::lineGroupFile(), Points::PointsAlgos::Load(), MeshCore::MeshInput::LoadAny(), TechDraw::DrawViewSection::makeLineSets(), TechDraw::DrawTileWeld::onChanged(), TechDraw::DrawViewSection::onChanged(), TechDraw::DrawTileWeld::onDocumentRestored(), TechDraw::DrawGeomHatch::onDocumentRestored(), TechDraw::DrawHatch::onDocumentRestored(), TechDraw::DrawViewSection::onDocumentRestored(), TechDraw::Preferences::patFile(), Fem::FemPostPipeline::read(), Fem::FemMesh::read(), Part::TopoShape::read(), TechDraw::DrawViewImage::setupImageIncluded(), TechDraw::Preferences::svgFile(), and TechDrawGui::PreferencesGui::weldingDirectory().
isWritable()
bool FileInfo::isWritable () const
Checks if the file exist and is writable.
References FileName, and toStdWString().
Referenced by Mesh::AmfExporter::AmfExporter(), App::PropertyFileIncluded::RestoreDocFile(), and MeshCore::MeshOutput::SaveAny().
lastModified()
TimeInfo FileInfo::lastModified () const
Returns the time when the file was last modified.
References exists(), FileName, Base::TimeInfo::null(), Base::TimeInfo::setTime_t(), and toStdWString().
lastRead()
TimeInfo FileInfo::lastRead () const
Returns the time when the file was last read (accessed).
References exists(), FileName, Base::TimeInfo::null(), Base::TimeInfo::setTime_t(), and toStdWString().
pathToString()
std::string FileInfo::pathToString (const boost::filesystem::path & p) static
Convert from filesystem path to string.
renameFile()
bool FileInfo::renameFile (const char * NewName)
Rename the file.
References FileName, and toStdWString().
Referenced by App::Document::onChanged(), and App::PropertyFileIncluded::Paste().
setFile() [1/2]
void FileInfo::setFile (const char * name)
Set a new file name.
References FileName.
Referenced by Drawing::FeaturePage::execute(), TechDraw::DrawSVGTemplate::execute(), FileInfo(), TechDraw::DrawSVGTemplate::getEditableTextsFromTemplate(), Drawing::FeaturePage::getEditableTextsFromTemplate(), Base::Writer::getUniqueFileName(), App::PropertyFileIncluded::getUniqueFileName(), Mesh::MeshObject::load(), Drawing::FeaturePage::onDocumentRestored(), Raytracing::LuxProject::onDocumentRestored(), Raytracing::RayProject::onDocumentRestored(), App::PropertyFileIncluded::Paste(), Mesh::MeshObject::save(), App::VRMLObject::SaveDocFile(), Base::FileException::setFileName(), and App::PropertyFileIncluded::setValue().
setFile() [2/2]
void Base::FileInfo::setFile (const std::string & name)
Set a new file name.
References setFile().
Referenced by setFile().
setPermissions()
bool FileInfo::setPermissions (Permissions perms)
Tries to set the file permission.
References FileName, ReadOnly, toStdWString(), and WriteOnly.
Referenced by App::PropertyFileIncluded::Copy(), App::PropertyFileIncluded::Paste(), App::PropertyFileIncluded::Restore(), and App::PropertyFileIncluded::RestoreDocFile().
size()
unsigned int FileInfo::size () const
The size of the file.
Referenced by gzip_utf8.GzipFile::close(), PathScripts.PostUtils.GCodeEditorDialog::done(), and gzip_utf8.GzipFile::write().
stringToPath()
boost::filesystem::path FileInfo::stringToPath (const std::string & str) static
Convert from string to filesystem path.
Referenced by createDirectories().
toStdWString()
std::wstring FileInfo::toStdWString () const
Convert the path name into a UTF-16 encoded wide string format.
Note
: Use this function on Windows only.
References FileName.
Referenced by copyTo(), createDirectory(), deleteDirectory(), deleteFile(), exists(), getDirectoryContent(), isDir(), isFile(), isReadable(), isWritable(), lastModified(), lastRead(), Gui::SoSVGVectorOutput::openFile(), Gui::SoU3DVectorOutput::openFile(), renameFile(), Gui::Application::runApplication(), Base::InterpreterSingleton::runFile(), Gui::PythonDebugger::runFile(), setPermissions(), zipios::ZipFile::ZipFile(), and zipios::ZipInputStream::ZipInputStream().
Member Data Documentation
FileName
std::string Base::FileInfo::FileName protected
Referenced by completeExtension(), copyTo(), createDirectories(), createDirectory(), deleteDirectory(), deleteFile(), dirPath(), exists(), extension(), fileName(), filePath(), getDirectoryContent(), getTempFileName(), isDir(), isFile(), isReadable(), isWritable(), lastModified(), lastRead(), renameFile(), setFile(), setPermissions(), and toStdWString().
The documentation for this class was generated from the following files:
FreeCAD/src/Base/FileInfo.h
FreeCAD/src/Base/FileInfo.cpp