FreeCAD: ArchBuildingPart Namespace Reference
ArchBuildingPart Namespace Reference
Workbenches » Python workbenches » Arch
The BuildingPart object and tools.
Classes
class BuildingPart
class CommandBuildingPart
class ViewProviderBuildingPart
Functions
def convertFloors (floor=None)
def makeBuilding (objectslist=None, baseobj=None, name="Building")
def makeBuildingPart (objectslist=None, baseobj=None, name="BuildingPart")
def makeFloor (objectslist=None, baseobj=None, name="Floor")
Variables
list BuildingTypes
unicode = str
Detailed Description
The BuildingPart object and tools.
This module provides tools to build BuildingPart objects. BuildingParts are used to group different Arch objects
Function Documentation
convertFloors()
def ArchBuildingPart.convertFloors (floor = None)
convert the given Floor or Building (or all Arch Floors from the active document if none is given) into BuildingParts
References makeBuildingPart(), and draftutils.translate.QT_TRANSLATE_NOOP.
makeBuilding()
def ArchBuildingPart.makeBuilding (objectslist = None, baseobj = None, name = "Building")
overwrites ArchBuilding.makeBuilding
References makeBuildingPart(), and draftutils.translate.QT_TRANSLATE_NOOP.
makeBuildingPart()
def ArchBuildingPart.makeBuildingPart (objectslist = None, baseobj = None, name = "BuildingPart")
makeBuildingPart(objectslist): creates a buildingPart including the
objects from the given list.
Referenced by ArchBuildingPart.ViewProviderBuildingPart.cloneUp(), convertFloors(), makeBuilding(), and makeFloor().
makeFloor()
def ArchBuildingPart.makeFloor (objectslist = None, baseobj = None, name = "Floor")
overwrites ArchFloor.makeFloor
References makeBuildingPart().
Variable Documentation
BuildingTypes
list ArchBuildingPart.BuildingTypes
unicode
ArchBuildingPart.unicode = str