FreeCAD: draftguitools.gui_lines.Wire Class Reference
draftguitools.gui_lines.Wire Class Reference
Workbenches » Python workbenches » Draft » draftguitools
Public Member Functions
def Activated (self)
def GetResources (self)
Public Member Functions inherited from draftguitools.gui_lines.Line
def action (self, arg)
def Activated (self, name="Line", icon="Draft_Line")
def drawSegment (self, point)
def finish (self, closed=False, cont=False)
def GetResources (self)
def numericInput (self, numx, numy, numz)
def orientWP (self)
def removeTemporaryObject (self)
def undolast (self)
def wipe (self)
def Activated (self, name="None", noplanesetup=False)
Public Member Functions inherited from draftguitools.gui_base_original.DraftTool
def Activated (self, name="None", noplanesetup=False, is_subtool=False)
def commit (self, name, func)
def finish (self, close=False)
def getStrings (self, addrot=None)
def IsActive (self)
Additional Inherited Members
Public Attributes inherited from draftguitools.gui_lines.Line
call
isWire
node
obj
oldWP
point
pos
Public Attributes inherited from draftguitools.gui_base_original.Creator
support
Public Attributes inherited from draftguitools.gui_base_original.DraftTool
call
commitList
constrain
doc
extendedCopy
featureName
node
obj
planetrack
point
pos
support
ui
view
Detailed Description
Gui command for the Wire or Polyline tool.
It inherits the `Line` class, and calls essentially the same code,
only this time the `wiremode` is set to `True`,
so we are allowed to place more than two points.
Member Function Documentation
Activated()
def draftguitools.gui_lines.Wire.Activated (self)
Execute when the command is called.
Reimplemented from draftguitools.gui_lines.Line.
References draftguitools.gui_lines.Wire.Activated().
Referenced by ArchStructure.CommandStructuralSystem.Activated(), draftguitools.gui_lines.Wire.Activated(), draftguitools.gui_arcs.Arc.finish(), draftguitools.gui_beziers.BezCurve.finish(), draftguitools.gui_beziers.CubicBezCurve.finish(), draftguitools.gui_ellipses.Ellipse.finish(), draftguitools.gui_lines.Line.finish(), draftguitools.gui_mirror.Mirror.finish(), draftguitools.gui_move.Move.finish(), draftguitools.gui_polygons.Polygon.finish(), draftguitools.gui_rectangles.Rectangle.finish(), draftguitools.gui_rotate.Rotate.finish(), draftguitools.gui_splines.BSpline.finish(), draftguitools.gui_texts.Text.finish(), draftguitools.gui_points.Point.finish(), draftguitools.gui_shapestrings.ShapeString.finish(), draftguitools.gui_arcs.Arc_3Points.getPoint(), and ArchPanel.CommandPanel.getPoint().
GetResources()
def draftguitools.gui_lines.Wire.GetResources (self)
Set icon, menu and tooltip.
Reimplemented from draftguitools.gui_lines.Line.
References draftutils.translate.QT_TRANSLATE_NOOP.
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Draft/draftguitools/gui_lines.py