FreeCAD: PartDesignGui::Ui_TaskFilletParameters Class Reference
PartDesignGui::Ui_TaskFilletParameters Class Reference
#include <ui_TaskFilletParameters.h>
Public Member Functions
void retranslateUi (QWidget *PartDesignGui__TaskFilletParameters)
void setupUi (QWidget *PartDesignGui__TaskFilletParameters)
Public Attributes
QToolButton * buttonRefAdd
QToolButton * buttonRefRemove
QCheckBox * checkBoxUseAllEdges
Gui::QuantitySpinBox * filletRadius
QHBoxLayout * horizontalLayout
QHBoxLayout * horizontalLayout_2
QLabel * label
QListWidget * listWidgetReferences
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void PartDesignGui::Ui_TaskFilletParameters::retranslateUi (QWidget * PartDesignGui__TaskFilletParameters)
References buttonRefAdd, buttonRefRemove, checkBoxUseAllEdges, listWidgetReferences, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void PartDesignGui::Ui_TaskFilletParameters::setupUi (QWidget * PartDesignGui__TaskFilletParameters)
References buttonRefAdd, buttonRefRemove, checkBoxUseAllEdges, filletRadius, horizontalLayout, horizontalLayout_2, listWidgetReferences, retranslateUi(), and verticalLayout.
Member Data Documentation
buttonRefAdd
QToolButton* PartDesignGui::Ui_TaskFilletParameters::buttonRefAdd
Referenced by retranslateUi(), and setupUi().
buttonRefRemove
QToolButton* PartDesignGui::Ui_TaskFilletParameters::buttonRefRemove
Referenced by retranslateUi(), and setupUi().
checkBoxUseAllEdges
QCheckBox* PartDesignGui::Ui_TaskFilletParameters::checkBoxUseAllEdges
Referenced by retranslateUi(), and setupUi().
filletRadius
Gui::QuantitySpinBox* PartDesignGui::Ui_TaskFilletParameters::filletRadius
Referenced by setupUi().
horizontalLayout
QHBoxLayout* PartDesignGui::Ui_TaskFilletParameters::horizontalLayout
Referenced by setupUi().
horizontalLayout_2
QHBoxLayout* PartDesignGui::Ui_TaskFilletParameters::horizontalLayout_2
Referenced by setupUi().
label
QLabel* PartDesignGui::Ui_TaskFilletParameters::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
listWidgetReferences
QListWidget* PartDesignGui::Ui_TaskFilletParameters::listWidgetReferences
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* PartDesignGui::Ui_TaskFilletParameters::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/PartDesign/Gui/ui_TaskFilletParameters.h