FreeCAD: SMESH::Controls::CoplanarFaces Class Reference
SMESH::Controls::CoplanarFaces Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
CoplanarFaces ()
Class CoplanarFaces.
long GetFace () const
double GetTolerance () const
virtual SMDSAbs_ElementType GetType () const
virtual bool IsSatisfy (long theElementId)
void SetFace (long theID)
virtual void SetMesh (const SMDS_Mesh *theMesh)
void SetTolerance (const double theToler)
Public Member Functions inherited from SMESH::Controls::Functor
virtual ~Functor ()
Constructor & Destructor Documentation
CoplanarFaces()
CoplanarFaces::CoplanarFaces ()
Class CoplanarFaces.
Member Function Documentation
GetFace()
long SMESH::Controls::CoplanarFaces::GetFace () const
GetTolerance()
double SMESH::Controls::CoplanarFaces::GetTolerance () const
GetType()
virtual SMDSAbs_ElementType SMESH::Controls::CoplanarFaces::GetType () const virtual
Implements SMESH::Controls::Predicate.
IsSatisfy()
bool CoplanarFaces::IsSatisfy (long theElementId) virtual
Implements SMESH::Controls::Predicate.
SetFace()
void SMESH::Controls::CoplanarFaces::SetFace (long theID)
SetMesh()
void CoplanarFaces::SetMesh (const SMDS_Mesh * theMesh) virtual
Implements SMESH::Controls::Functor.
References SMDS_Mesh::FindElement(), SMDS_MeshNode::GetInverseElementIterator(), SMESH::Controls::TMeshModifTracer::GetMesh(), SMDS_MeshElement::GetNode(), SMESH::Controls::TMeshModifTracer::IsMeshModified(), and SMESH::Controls::TMeshModifTracer::SetMesh().
SetTolerance()
void SMESH::Controls::CoplanarFaces::SetTolerance (const double theToler)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp