FreeCAD: Gui::OutputStderr Class Reference
Gui::OutputStderr Class Reference
Python class for redirection of stderr to FreeCAD's output console window.
#include <PythonConsolePy.h>
Public Member Functions
Py::Object flush (const Py::Tuple &)
Py::Object getattr (const char *name)
Py::Object isatty ()
OutputStderr ()
Py::Object repr ()
Py::Object write (const Py::Tuple &)
~OutputStderr ()
Static Public Member Functions
static void init_type (void)
Detailed Description
Python class for redirection of stderr to FreeCAD's output console window.
This allows to report all Python errors to the output window which simplifies error tracking.
See also
PythonStdout
PythonStderr
Author
Werner Mayer
Constructor & Destructor Documentation
OutputStderr()
OutputStderr::OutputStderr ()
~OutputStderr()
OutputStderr::~OutputStderr ()
Member Function Documentation
flush()
Py::Object OutputStderr::flush (const Py::Tuple &)
Referenced by init_type().
getattr()
Py::Object OutputStderr::getattr (const char * name)
init_type()
void OutputStderr::init_type (void) static
References flush(), isatty(), and write().
Referenced by Gui::Application::Application().
isatty()
Py::Object OutputStderr::isatty ()
Referenced by init_type().
repr()
Py::Object OutputStderr::repr ()
write()
Py::Object OutputStderr::write (const Py::Tuple & args)
References Base::Console(), and Base::ConsoleSingleton::Error().
Referenced by init_type(), and gzip_utf8.GzipFile::seek().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/PythonConsolePy.h
FreeCAD/src/Gui/PythonConsolePy.cpp