FreeCAD: feminout.importCcxDatResults Namespace Reference
feminout.importCcxDatResults Namespace Reference
Functions
def import_dat (filename, Analysis=None)
def insert (filename, docname)
def open (filename)
def readResult (dat_input)
Variables
string EIGENVALUE_OUTPUT_SECTION = " E I G E N V A L U E O U T P U T"
pyopen = open
Function Documentation
import_dat()
def feminout.importCcxDatResults.import_dat (filename, Analysis = None)
References feminout.importCcxDatResults.readResult().
Referenced by feminout.importCcxDatResults.insert().
insert()
def feminout.importCcxDatResults.insert (filename, docname)
References feminout.importCcxDatResults.import_dat().
Referenced by feminout.importCcxDatResults.open().
open()
def feminout.importCcxDatResults.open (filename)
References feminout.importCcxDatResults.insert().
readResult()
def feminout.importCcxDatResults.readResult (dat_input)
References feminout.importCcxDatResults.pyopen.
Referenced by feminout.importCcxDatResults.import_dat().
Variable Documentation
EIGENVALUE_OUTPUT_SECTION
string feminout.importCcxDatResults.EIGENVALUE_OUTPUT_SECTION = " E I G E N V A L U E O U T P U T"
pyopen
feminout.importCcxDatResults.pyopen = open
Referenced by feminout.importCcxDatResults.readResult().