FreeCAD: RobotGui::TaskTrajectoryDressUpParameter Class Reference
RobotGui::TaskTrajectoryDressUpParameter Class Reference
#include <TaskTrajectoryDressUpParameter.h>
Public Member Functions
TaskTrajectoryDressUpParameter (Robot::TrajectoryDressUpObject *obj, QWidget *parent=0)
void writeValues (void)
this methode write the values from the Gui to the object, usually in accept()
~TaskTrajectoryDressUpParameter ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (QWidget *parent=0)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (QWidget *parent=0)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Protected Member Functions
void viewPlacement (void)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Protected Attributes
Base::Placement PosAdd
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskTrajectoryDressUpParameter()
TaskTrajectoryDressUpParameter::TaskTrajectoryDressUpParameter (Robot::TrajectoryDressUpObject * obj, QWidget * parent = 0)
References Robot::TrajectoryDressUpObject::Acceleration, Robot::TrajectoryDressUpObject::AddType, Gui::BitmapFactory(), draftgeoutils.intersections::connect(), Robot::TrajectoryDressUpObject::ContType, App::PropertyPlacement::getValue(), App::PropertyEnumeration::getValue(), App::PropertyBool::getValue(), App::PropertyQuantity::getValue(), QSint::ActionGroup::groupLayout(), Robot::TrajectoryDressUpObject::PosAdd, PosAdd, Robot::TrajectoryDressUpObject::Speed, Robot::TrajectoryDressUpObject::UseAcceleration, Robot::TrajectoryDressUpObject::UseSpeed, and viewPlacement().
~TaskTrajectoryDressUpParameter()
TaskTrajectoryDressUpParameter::~TaskTrajectoryDressUpParameter ()
Member Function Documentation
viewPlacement()
void TaskTrajectoryDressUpParameter::viewPlacement (void) protected
References Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Rotation::getYawPitchRoll(), and PosAdd.
Referenced by TaskTrajectoryDressUpParameter().
writeValues()
void TaskTrajectoryDressUpParameter::writeValues (void)
this methode write the values from the Gui to the object, usually in accept()
References Robot::TrajectoryDressUpObject::Acceleration, Robot::TrajectoryDressUpObject::AddType, Robot::TrajectoryDressUpObject::ContType, Robot::TrajectoryDressUpObject::PosAdd, PosAdd, App::PropertyBool::setValue(), App::PropertyPlacement::setValue(), App::PropertyEnumeration::setValue(), App::PropertyQuantity::setValue(), Robot::TrajectoryDressUpObject::Speed, Robot::TrajectoryDressUpObject::UseAcceleration, and Robot::TrajectoryDressUpObject::UseSpeed.
Referenced by RobotGui::TaskDlgTrajectoryDressUp::accept(), and RobotGui::TaskDlgTrajectoryDressUp::clicked().
Member Data Documentation
PosAdd
Base::Placement RobotGui::TaskTrajectoryDressUpParameter::PosAdd protected
Referenced by TaskTrajectoryDressUpParameter(), viewPlacement(), and writeValues().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Robot/Gui/TaskTrajectoryDressUpParameter.h
Sources/FreeCAD/src/Mod/Robot/Gui/TaskTrajectoryDressUpParameter.cpp