FreeCAD: SketcherGui::SketchMirrorDialog Class Reference
SketcherGui::SketchMirrorDialog Class Reference
#include <SketchMirrorDialog.h>
Public Member Functions
void accept ()
SketchMirrorDialog (void)
~SketchMirrorDialog ()
Public Attributes
int RefGeoid
Sketcher::PointPos RefPosid
Constructor & Destructor Documentation
SketchMirrorDialog()
SketchMirrorDialog::SketchMirrorDialog (void)
~SketchMirrorDialog()
SketchMirrorDialog::~SketchMirrorDialog ()
Member Function Documentation
accept()
void SketchMirrorDialog::accept (void)
References Sketcher::none, RefGeoid, RefPosid, and Sketcher::start.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
Member Data Documentation
RefGeoid
int SketcherGui::SketchMirrorDialog::RefGeoid
Referenced by accept().
RefPosid
Sketcher::PointPos SketcherGui::SketchMirrorDialog::RefPosid
Referenced by accept().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/Gui/SketchMirrorDialog.h
FreeCAD/src/Mod/Sketcher/Gui/SketchMirrorDialog.cpp