FreeCAD: Gui::Dialog::DlgMacroRecordImp Class Reference
Gui::Dialog::DlgMacroRecordImp Class Reference
The DlgMacroRecordImp class implements a dialog to record a macro.
#include <DlgMacroRecordImp.h>
Public Member Functions
DlgMacroRecordImp (QWidget *parent=0, Qt::WindowFlags fl=Qt::WindowFlags())
Constructs a DlgMacroRecordImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
virtual ~DlgMacroRecordImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::WindowParameter
ParameterGrp::handle getWindowParameter (void)
return the parameter group of this window
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason)
bool setGroupName (const char *name)
Sets the group of the window to name.
WindowParameter (const char *name)
virtual ~WindowParameter ()
Protected Slots
void on_buttonCancel_clicked ()
Abort the macro.
void on_buttonStart_clicked ()
Starts the record of the macro.
void on_buttonStop_clicked ()
Stops the record of the macro and save to the file.
void on_lineEditMacroPath_textChanged (const QString &)
void on_pushButtonChooseDir_clicked ()
Additional Inherited Members
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter (void)
get the parameters
Detailed Description
The DlgMacroRecordImp class implements a dialog to record a macro.
Author
Jürgen Riegel
Constructor & Destructor Documentation
DlgMacroRecordImp()
DlgMacroRecordImp::DlgMacroRecordImp (QWidget * parent = 0, Qt::WindowFlags fl = Qt::WindowFlags())
Constructs a DlgMacroRecordImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
References App::Application::getUserMacroDir(), Gui::WindowParameter::getWindowParameter(), Gui::Application::Instance, Gui::MacroManager::isOpen(), and Gui::Application::macroManager().
~DlgMacroRecordImp()
DlgMacroRecordImp::~DlgMacroRecordImp () virtual
Destroys the object and frees any allocated resources.
Member Function Documentation
on_buttonCancel_clicked
void DlgMacroRecordImp::on_buttonCancel_clicked () protected slot
Abort the macro.
References Gui::MacroManager::cancel(), and Gui::MacroManager::isOpen().
on_buttonStart_clicked
void DlgMacroRecordImp::on_buttonStart_clicked () protected slot
Starts the record of the macro.
References Gui::MacroManager::File, Gui::getMainWindow(), and Gui::MacroManager::open().
on_buttonStop_clicked
void DlgMacroRecordImp::on_buttonStop_clicked () protected slot
Stops the record of the macro and save to the file.
References Gui::MacroManager::commit(), and Gui::MacroManager::isOpen().
on_lineEditMacroPath_textChanged
void DlgMacroRecordImp::on_lineEditMacroPath_textChanged (const QString & newDir) protected slot
on_pushButtonChooseDir_clicked
void DlgMacroRecordImp::on_pushButtonChooseDir_clicked () protected slot
References Gui::WindowParameter::getWindowParameter(), and ParameterGrp::SetASCII().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgMacroRecordImp.h
Sources/FreeCAD/src/Gui/DlgMacroRecordImp.cpp