FreeCAD: Gui::Dialog::TaskTransform Class Reference
Gui::Dialog::TaskTransform Class Reference
#include <Transform.h>
Public Member Functions
bool accept ()
is called by the framework if the dialog is accepted (Ok)
void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual QDialogButtonBox::StandardButtons getStandardButtons () const
tells the framework which buttons are wished for the dialog
bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setTransformStrategy (TransformStrategy *ts)
TaskTransform ()
~TaskTransform ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
ButtonPosition buttonPosition () const
bool canClose () const
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Constructor & Destructor Documentation
TaskTransform()
TaskTransform::TaskTransform ()
References Gui::TaskView::TaskDialog::Content, QSint::ActionGroup::groupLayout(), Gui::TaskView::TaskDialog::setButtonPosition(), Gui::Dialog::Transform::showStandardButtons(), and Gui::TaskView::TaskDialog::South.
~TaskTransform()
TaskTransform::~TaskTransform ()
Member Function Documentation
accept()
bool TaskTransform::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Dialog::Transform::accept().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
clicked()
void TaskTransform::clicked (int) virtual
is called by the framework if a button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Dialog::Transform::on_applyButton_clicked().
getStandardButtons()
virtual QDialogButtonBox::StandardButtons Gui::Dialog::TaskTransform::getStandardButtons (void) const virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
reject()
bool TaskTransform::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Dialog::Transform::reject().
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
setTransformStrategy()
void TaskTransform::setTransformStrategy (TransformStrategy * ts)
References Gui::Dialog::Transform::setTransformStrategy().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Transform.h
Sources/FreeCAD/src/Gui/Transform.cpp