FreeCAD: Mesh::MergeExporter Class Reference
Mesh::MergeExporter Class Reference
Creates a single mesh, in a file, from one or more objects.
#include <Exporter.h>
Public Member Functions
bool addMeshFeat (App::DocumentObject *obj) override
Directly adds a mesh feature.
bool addPartFeat (App::DocumentObject *obj, float tol) override
Converts the a Part::Feature to a mesh, adds that mesh.
MergeExporter (std::string fileName, MeshCore::MeshIO::Format fmt)
~MergeExporter ()
Public Member Functions inherited from Mesh::Exporter
bool addAppGroup (App::DocumentObject *obj, float tol)
Recursively adds objects from App::Part & App::DocumentObjectGroup.
bool addObject (App::DocumentObject *obj, float tol)
Exporter ()
virtual ~Exporter ()=default
Protected Attributes
std::string fName
MeshObject mergingMesh
Protected Attributes inherited from Mesh::Exporter
const Base::Type appPartId
const Base::Type groupExtensionId
const Base::Type meshFeatId
Additional Inherited Members
Static Public Member Functions inherited from Mesh::Exporter
static bool isSupported (App::DocumentObject *obj)
Static Protected Member Functions inherited from Mesh::Exporter
static std::string xmlEscape (const std::string &input)
Does some simple escaping of characters for XML-type exports.
Detailed Description
Creates a single mesh, in a file, from one or more objects.
Constructor & Destructor Documentation
MergeExporter()
MergeExporter::MergeExporter (std::string fileName, MeshCore::MeshIO::Format fmt)
~MergeExporter()
MergeExporter::~MergeExporter ()
References Mesh::MeshObject::countSegments(), fName, Mesh::MeshObject::getSegment(), mergingMesh, Mesh::Segment::save(), and Mesh::MeshObject::save().
Member Function Documentation
addMeshFeat()
bool MergeExporter::addMeshFeat (App::DocumentObject * obj) override virtual
Directly adds a mesh feature.
Implements Mesh::Exporter.
References Mesh::MeshObject::addMesh(), Mesh::MeshObject::addSegment(), Mesh::MeshObject::countFacets(), Mesh::Segment::getIndices(), Mesh::Segment::getName(), Mesh::Segment::isSaved(), mergingMesh, Mesh::MeshObject::setKernel(), Mesh::Segment::setName(), Base::Placement::toMatrix(), and MeshCore::MeshKernel::Transform().
addPartFeat()
bool MergeExporter::addPartFeat (App::DocumentObject * obj, float tol) override virtual
Converts the a Part::Feature to a mesh, adds that mesh.
Implements Mesh::Exporter.
References Mesh::MeshObject::addMesh(), Mesh::MeshObject::addSegment(), Mesh::MeshObject::countFacets(), Base::Persistence::getClassTypeId(), App::PropertyPlacement::getValue(), App::GeoFeature::globalPlacement(), Base::Placement::inverse(), mergingMesh, Base::Placement::multVec(), App::GeoFeature::Placement, and Mesh::Segment::setName().
Member Data Documentation
fName
std::string Mesh::MergeExporter::fName protected
Referenced by ~MergeExporter().
mergingMesh
MeshObject Mesh::MergeExporter::mergingMesh protected
Referenced by addMeshFeat(), addPartFeat(), and ~MergeExporter().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Exporter.h
Sources/FreeCAD/src/Mod/Mesh/App/Exporter.cpp