FreeCAD: MED::TTNameInfo< eVersion > Struct Template Reference
MED::TTNameInfo< eVersion > Struct Template Reference
#include <MED_TStructures.hxx>
Public Member Functions
virtual std::string GetName () const
Gets its name.
virtual void SetName (const std::string &theValue)
Set a new name.
virtual void SetName (const TString &theValue)
Set a new name.
TTNameInfo (const std::string &theValue)
virtual std::string GetName () const =0
Gets its name.
virtual void SetName (const std::string &theValue)=0
Set a new name.
virtual void SetName (const TString &theValue)=0
Set a new name.
Public Member Functions inherited from MED::TBase
virtual ~TBase ()
Additional Inherited Members
Public Attributes inherited from MED::TNameInfo
TString myName
Keeps its name.
Constructor & Destructor Documentation
TTNameInfo()
template<EVersion eVersion> MED::TTNameInfo< eVersion >::TTNameInfo (const std::string & theValue)
References MED::TNameInfo::myName, and MED::TTNameInfo< eVersion >::SetName().
Member Function Documentation
GetName()
template<EVersion eVersion> virtual std::string MED::TTNameInfo< eVersion >::GetName () const virtual
Gets its name.
Implements MED::TNameInfo.
References MED::GetString(), and MED::TNameInfo::myName.
SetName() [1/2]
template<EVersion eVersion> virtual void MED::TTNameInfo< eVersion >::SetName (const std::string & theValue) virtual
Set a new name.
Implements MED::TNameInfo.
References MED::TNameInfo::myName, and MED::SetString().
Referenced by MED::TTNameInfo< eVersion >::TTNameInfo().
SetName() [2/2]
template<EVersion eVersion> virtual void MED::TTNameInfo< eVersion >::SetName (const TString & theValue) virtual
Set a new name.
Implements MED::TNameInfo.
References MED::TNameInfo::myName, and MED::SetString().
The documentation for this struct was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/inc/MED_TStructures.hxx