FreeCAD: Import::StepShape Class Reference
Import::StepShape Class Reference
The StepShape helper class The MeshFacet class provides an interface for the MeshFacetPy class for convenient access to the Mesh data structure.
#include <StepShape.h>
Public Member Functions
int read (const char *fileName)
StepShape ()
~StepShape ()
Detailed Description
The StepShape helper class The MeshFacet class provides an interface for the MeshFacetPy class for convenient access to the Mesh data structure.
This class should not be used for programming algorithms in C++. Use Mesh Core classes instead!
Constructor & Destructor Documentation
StepShape()
StepShape::StepShape ()
~StepShape()
StepShape::~StepShape ()
Member Function Documentation
read()
int StepShape::read (const char * fileName)
References Base::FileInfo::exists().
Referenced by Import::StepShapePy::PyInit(), gzip_utf8.GzipFile::readline(), and gzip_utf8.GzipFile::seek().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Import/App/StepShape.h
Sources/FreeCAD/src/Mod/Import/App/StepShape.cpp