FreeCAD: TechDrawGui::TaskDlgCenterLine Class Reference
TechDrawGui::TaskDlgCenterLine Class Reference
#include <TaskCenterLine.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void clicked (int)
is called by the framework if an button is clicked which has no accept or reject role
virtual void helpRequested ()
is called by the framework if the user presses the help button
virtual bool isAllowedAlterDocument (void) const
void modifyStandardButtons (QDialogButtonBox *box)
virtual void open ()
is called the TaskView when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgCenterLine (TechDraw::DrawViewPart *baseFeat, TechDraw::DrawPage *page, std::string edgeName, bool editMode)
TaskDlgCenterLine (TechDraw::DrawViewPart *baseFeat, TechDraw::DrawPage *page, std::vector< std::string > subNames, bool editMode)
void update ()
~TaskDlgCenterLine ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
tells the framework which buttons are wished for the dialog
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual bool needsFullSpace () const
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Constructor & Destructor Documentation
TaskDlgCenterLine() [1/2]
TaskDlgCenterLine::TaskDlgCenterLine (TechDraw::DrawViewPart * baseFeat, TechDraw::DrawPage * page, std::vector< std::string > subNames, bool editMode)
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
TaskDlgCenterLine() [2/2]
TaskDlgCenterLine::TaskDlgCenterLine (TechDraw::DrawViewPart * baseFeat, TechDraw::DrawPage * page, std::string edgeName, bool editMode)
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
~TaskDlgCenterLine()
TaskDlgCenterLine::~TaskDlgCenterLine ()
Member Function Documentation
accept()
bool TaskDlgCenterLine::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References TechDrawGui::TaskCenterLine::accept().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
clicked()
void TaskDlgCenterLine::clicked (int) virtual
is called by the framework if an button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
helpRequested()
virtual void TechDrawGui::TaskDlgCenterLine::helpRequested () virtual
is called by the framework if the user presses the help button
Reimplemented from Gui::TaskView::TaskDialog.
isAllowedAlterDocument()
virtual bool TechDrawGui::TaskDlgCenterLine::isAllowedAlterDocument (void) const virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
modifyStandardButtons()
void TaskDlgCenterLine::modifyStandardButtons (QDialogButtonBox * box) virtual
Reimplemented from Gui::TaskView::TaskDialog.
References TechDrawGui::TaskCenterLine::saveButtons().
open()
void TaskDlgCenterLine::open () virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
reject()
bool TaskDlgCenterLine::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References TechDrawGui::TaskCenterLine::reject().
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
update()
void TaskDlgCenterLine::update ()
Referenced by ArchAxis.AxisSystemTaskPanel::addElement(), ArchComponent.ComponentTaskPanel::addElement(), ArchSectionPlane.SectionPlaneTaskPanel::addElement(), DraftGui.FacebinderTaskPanel::addElement(), femtaskpanels.task_result_mechanical._TaskPanel::calculate(), Spreadsheet_legacy.SpreadsheetView::changeCell(), draftguitools.gui_edit.Edit::endEditing(), draftguitools.gui_trackers.boxTracker::height(), ArchAxis.CommandArchGrid::IsActive(), draftguitools.gui_trackers.rectangleTracker::p3(), Plot.Plot::plot(), Spreadsheet_legacy.SpreadsheetView::recompute(), ArchAxis.AxisSystemTaskPanel::removeElement(), ArchComponent.ComponentTaskPanel::removeElement(), ArchSectionPlane.SectionPlaneTaskPanel::removeElement(), DraftGui.FacebinderTaskPanel::removeElement(), draftguitools.gui_trackers.gridTracker::reset(), and ArchNesting.Nester::run().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/TaskCenterLine.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/TaskCenterLine.cpp