FreeCAD: Gui::SoU3DVectorOutput Class Reference
Gui::SoU3DVectorOutput Class Reference
#include <SoFCVectorizeU3DAction.h>
Public Member Functions
virtual void closeFile (void)
std::fstream & getFileStream ()
virtual SbBool openFile (const char *filename)
SoU3DVectorOutput ()
virtual ~SoU3DVectorOutput ()
Constructor & Destructor Documentation
SoU3DVectorOutput()
SoU3DVectorOutput::SoU3DVectorOutput ()
~SoU3DVectorOutput()
SoU3DVectorOutput::~SoU3DVectorOutput () virtual
References closeFile().
Member Function Documentation
closeFile()
void SoU3DVectorOutput::closeFile (void) virtual
Referenced by ~SoU3DVectorOutput().
getFileStream()
std::fstream & SoU3DVectorOutput::getFileStream ()
Referenced by Gui::SoFCVectorizeU3DAction::printHeader().
openFile()
SbBool SoU3DVectorOutput::openFile (const char * filename) virtual
References Base::FileInfo::filePath(), and Base::FileInfo::toStdWString().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SoFCVectorizeU3DAction.h
Sources/FreeCAD/src/Gui/SoFCVectorizeU3DAction.cpp