FreeCAD: config_control_design Namespace Reference
config_control_design Namespace Reference
Classes
class action
class action_assignment
class action_directive
class action_method
class action_request_assignment
class action_request_solution
class action_request_status
class action_status
class address
class advanced_brep_shape_representation
class advanced_face
class ahead_or_behind
class alternate_product_relationship
class application_context
class application_context_element
class application_protocol_definition
class approval
class approval_assignment
class approval_date_time
class approval_person_organization
class approval_relationship
class approval_role
class approval_status
class area_measure
class area_measure_with_unit
class area_unit
class assembly_component_usage
class assembly_component_usage_substitute
class axis1_placement
class axis2_placement_2d
class axis2_placement_3d
class b_spline_curve
class b_spline_curve_form
class b_spline_curve_with_knots
class b_spline_surface
class b_spline_surface_form
class b_spline_surface_with_knots
class bezier_curve
class bezier_surface
class boundary_curve
class bounded_curve
class bounded_pcurve
class bounded_surface
class bounded_surface_curve
class brep_with_voids
class calendar_date
class cartesian_point
class cartesian_transformation_operator
class cartesian_transformation_operator_3d
class cc_design_approval
class cc_design_certification
class cc_design_contract
class cc_design_date_and_time_assignment
class cc_design_person_and_organization_assignment
class cc_design_security_classification
class cc_design_specification_reference
class certification
class certification_assignment
class certification_type
class change
class change_request
class circle
class closed_shell
class composite_curve
class composite_curve_on_surface
class composite_curve_segment
class configuration_design
class configuration_effectivity
class configuration_item
class conic
class conical_surface
class connected_edge_set
class connected_face_set
class context_dependent_measure
class context_dependent_shape_representation
class context_dependent_unit
class contract
class contract_assignment
class contract_type
class conversion_based_unit
class coordinated_universal_time_offset
class count_measure
class curve
class curve_bounded_surface
class curve_replica
class cylindrical_surface
class date
class date_and_time
class date_and_time_assignment
class date_time_role
class dated_effectivity
class day_in_month_number
class day_in_week_number
class day_in_year_number
class definitional_representation
class degenerate_pcurve
class degenerate_toroidal_surface
class descriptive_measure
class design_context
class design_make_from_relationship
class dimension_count
class dimensional_exponents
class directed_action
class direction
class document
class document_reference
class document_relationship
class document_type
class document_usage_constraint
class document_with_class
class edge
class edge_based_wireframe_model
class edge_based_wireframe_shape_representation
class edge_curve
class edge_loop
class effectivity
class elementary_surface
class ellipse
class evaluated_degenerate_pcurve
class executed_action
class face
class face_bound
class face_outer_bound
class face_surface
class faceted_brep
class faceted_brep_shape_representation
class founded_item
class functionally_defined_transformation
class geometric_curve_set
class geometric_representation_context
class geometric_representation_item
class geometric_set
class geometrically_bounded_surface_shape_representation
class geometrically_bounded_wireframe_shape_representation
class global_uncertainty_assigned_context
class global_unit_assigned_context
class hour_in_day
class hyperbola
class identifier
class intersection_curve
class item_defined_transformation
class knot_type
class label
class length_measure
class length_measure_with_unit
class length_unit
class line
class local_time
class loop
class lot_effectivity
class manifold_solid_brep
class manifold_surface_shape_representation
class mapped_item
class mass_measure
class mass_measure_with_unit
class mass_unit
class measure_with_unit
class mechanical_context
class minute_in_hour
class month_in_year_number
class named_unit
class next_assembly_usage_occurrence
class offset_curve_3d
class offset_surface
class open_shell
class ordinal_date
class organization
class organization_relationship
class organizational_address
class organizational_project
class oriented_closed_shell
class oriented_edge
class oriented_face
class oriented_open_shell
class oriented_path
class outer_boundary_curve
class parabola
class parameter_value
class parametric_representation_context
class path
class pcurve
class person
class person_and_organization
class person_and_organization_assignment
class person_and_organization_role
class personal_address
class placement
class plane
class plane_angle_measure
class plane_angle_measure_with_unit
class plane_angle_unit
class point
class point_on_curve
class point_on_surface
class point_replica
class poly_loop
class polyline
class positive_length_measure
class positive_plane_angle_measure
class preferred_surface_curve_representation
class product
class product_category
class product_category_relationship
class product_concept
class product_concept_context
class product_context
class product_definition
class product_definition_context
class product_definition_effectivity
class product_definition_formation
class product_definition_formation_with_specified_source
class product_definition_relationship
class product_definition_shape
class product_definition_usage
class product_definition_with_associated_documents
class product_related_product_category
class promissory_usage_occurrence
class property_definition
class property_definition_representation
class quantified_assembly_component_usage
class quasi_uniform_curve
class quasi_uniform_surface
class rational_b_spline_curve
class rational_b_spline_surface
class rectangular_composite_surface
class rectangular_trimmed_surface
class reparametrised_composite_curve_segment
class representation
class representation_context
class representation_item
ENTITY representation_item #.
class representation_map
class representation_relationship
class representation_relationship_with_transformation
class seam_curve
class second_in_minute
class security_classification
class security_classification_assignment
class security_classification_level
class serial_numbered_effectivity
class shape_aspect
class shape_aspect_relationship
class shape_definition_representation
class shape_representation
class shape_representation_relationship
class shell_based_surface_model
class shell_based_wireframe_model
class shell_based_wireframe_shape_representation
class si_prefix
class si_unit
class si_unit_name
class solid_angle_measure
class solid_angle_measure_with_unit
class solid_angle_unit
class solid_model
class source
class specified_higher_usage_occurrence
class spherical_surface
class start_request
class start_work
class supplied_part_relationship
class surface
class surface_curve
class surface_of_linear_extrusion
class surface_of_revolution
class surface_patch
class surface_replica
class swept_surface
class text
class topological_representation_item
class toroidal_surface
class transition_code
class trimmed_curve
class trimming_preference
class uncertainty_measure_with_unit
class uniform_curve
class uniform_surface
class vector
class versioned_action_request
class vertex
class vertex_loop
class vertex_point
class vertex_shell
class volume_measure
class volume_measure_with_unit
class volume_unit
class week_in_year_number
class week_of_year_and_day_date
class wire_shell
class year_number
Functions
def acyclic_curve_replica (rep, parent)
FUNCTION acyclic_curve_replica #.
def acyclic_mapped_representation (parent_set, children_set)
FUNCTION acyclic_mapped_representation #.
def acyclic_point_replica (rep, parent)
FUNCTION acyclic_point_replica #.
def acyclic_product_category_relationship (relation, children)
FUNCTION acyclic_product_category_relationship #.
def acyclic_product_definition_relationship (relation, relatives, specific_relation)
FUNCTION acyclic_product_definition_relationship #.
def acyclic_surface_replica (rep, parent)
FUNCTION acyclic_surface_replica #.
def assembly_shape_is_defined (assy, schma)
FUNCTION assembly_shape_is_defined #.
def associated_surface (arg)
FUNCTION associated_surface #.
def bag_to_set (the_bag)
FUNCTION bag_to_set #.
def base_axis (dim, axis1, axis2, axis3)
FUNCTION base_axis #.
def boolean_choose (b, choice1, choice2)
FUNCTION boolean_choose #.
def build_2axes (ref_direction)
def build_axes (axis, ref_direction)
FUNCTION build_axes #.
def cc_design_date_time_correlation (e)
FUNCTION cc_design_date_time_correlation #.
def cc_design_person_and_organization_correlation (e)
FUNCTION cc_design_person_and_organization_correlation #.
def closed_shell_reversed (a_shell)
FUNCTION closed_shell_reversed #.
def conditional_reverse (p, an_item)
FUNCTION conditional_reverse #.
def constraints_composite_curve_on_surface (c)
FUNCTION constraints_composite_curve_on_surface #.
def constraints_geometry_shell_based_surface_model (m)
FUNCTION constraints_geometry_shell_based_surface_model #.
def constraints_geometry_shell_based_wireframe_model (m)
FUNCTION constraints_geometry_shell_based_wireframe_model #.
def constraints_param_b_spline (degree, up_knots, up_cp, knot_mult, knots)
FUNCTION constraints_param_b_spline #.
def constraints_rectangular_composite_surface (s)
FUNCTION constraints_rectangular_composite_surface #.
def cross_product (arg1, arg2)
FUNCTION cross_product #.
def curve_weights_positive (b)
FUNCTION curve_weights_positive #.
def derive_dimensional_exponents (x)
FUNCTION derive_dimensional_exponents #.
def dimension_of (item)
FUNCTION dimension_of #.
def dimensions_for_si_unit (n)
FUNCTION dimensions_for_si_unit #.
def dot_product (arg1, arg2)
FUNCTION dot_product #.
def edge_reversed (an_edge)
FUNCTION edge_reversed #.
def face_bound_reversed (a_face_bound)
FUNCTION face_bound_reversed #.
def face_reversed (a_face)
FUNCTION face_reversed #.
def first_proj_axis (z_axis, arg)
FUNCTION first_proj_axis #.
def gbsf_check_curve (cv)
FUNCTION gbsf_check_curve #.
def gbsf_check_point (pnt)
FUNCTION gbsf_check_point #.
def gbsf_check_surface (sf)
FUNCTION gbsf_check_surface #.
def get_basis_surface (c)
FUNCTION get_basis_surface #.
def item_in_context (item, cntxt)
FUNCTION item_in_context #.
def leap_year (year)
FUNCTION leap_year #.
def list_face_loops (f)
FUNCTION list_face_loops #.
def list_of_topology_reversed (a_list)
FUNCTION list_of_topology_reversed #.
def list_to_array (lis, low, u)
FUNCTION list_to_array #.
def list_to_set (l)
FUNCTION list_to_set #.
def make_array_of_array (lis, low1, u1, low2, u2)
FUNCTION make_array_of_array #.
def mixed_loop_type_set (l)
FUNCTION mixed_loop_type_set #.
def msb_shells (brep)
FUNCTION msb_shells #.
def msf_curve_check (cv)
FUNCTION msf_curve_check #.
def msf_surface_check (surf)
FUNCTION msf_surface_check #.
def normalise (arg)
FUNCTION normalise #.
def open_shell_reversed (a_shell)
FUNCTION open_shell_reversed #.
def orthogonal_complement (vec)
FUNCTION orthogonal_complement #.
def path_head_to_tail (a_path)
FUNCTION path_head_to_tail #.
def path_reversed (a_path)
FUNCTION path_reversed #.
def scalar_times_vector (scalar, vec)
FUNCTION scalar_times_vector #.
def second_proj_axis (z_axis, x_axis, arg)
FUNCTION second_proj_axis #.
def set_of_topology_reversed (a_set)
FUNCTION set_of_topology_reversed #.
def shell_reversed (a_shell)
FUNCTION shell_reversed #.
def surface_weights_positive (b)
FUNCTION surface_weights_positive #.
def topology_reversed (an_item)
FUNCTION topology_reversed #.
def unique_version_change_order (c)
FUNCTION unique_version_change_order #.
def using_items (item, checked_items)
FUNCTION using_items #.
def using_representations (item)
FUNCTION using_representations #.
def valid_calendar_date (date)
FUNCTION valid_calendar_date #.
def valid_geometrically_bounded_wf_curve (crv)
FUNCTION valid_geometrically_bounded_wf_curve #.
def valid_geometrically_bounded_wf_point (pnt)
FUNCTION valid_geometrically_bounded_wf_point #.
def valid_measure_value (m)
FUNCTION valid_measure_value #.
def valid_time (time)
FUNCTION valid_time #.
def valid_units (m)
FUNCTION valid_units #.
def valid_wireframe_edge_curve (crv)
FUNCTION valid_wireframe_edge_curve #.
def valid_wireframe_vertex_point (pnt)
FUNCTION valid_wireframe_vertex_point #.
def vector_difference (arg1, arg2)
FUNCTION vector_difference #.
Variables
acu_requires_security_classification = Rule()
RULE acu_requires_security_classification #.
application_context_requires_ap_definition = Rule()
RULE application_context_requires_ap_definition #.
approval_date_time_constraints = Rule()
RULE approval_date_time_constraints #.
approval_person_organization_constraints = Rule()
RULE approval_person_organization_constraints #.
approval_requires_approval_date_time = Rule()
RULE approval_requires_approval_date_time #.
approval_requires_approval_person_organization = Rule()
RULE approval_requires_approval_person_organization #.
approvals_are_assigned = Rule()
RULE approvals_are_assigned #.
approved_item
as_required_quantity = Rule()
RULE as_required_quantity #.
axis2_placement
boolean_operand
certification_requires_approval = Rule()
RULE certification_requires_approval #.
certification_requires_date_time = Rule()
RULE certification_requires_date_time #.
certified_item
change_request_item
change_request_requires_approval = Rule()
RULE change_request_requires_approval #.
change_request_requires_date_time = Rule()
RULE change_request_requires_date_time #.
change_request_requires_person_organization = Rule()
RULE change_request_requires_person_organization #.
change_requires_approval = Rule()
RULE change_requires_approval #.
change_requires_date_time = Rule()
RULE change_requires_date_time #.
characterized_definition
characterized_product_definition
classified_item
compatible_dimension = Rule()
RULE compatible_dimension #.
configuration_item_requires_approval = Rule()
RULE configuration_item_requires_approval #.
configuration_item_requires_person_organization = Rule()
RULE configuration_item_requires_person_organization #.
contract_requires_approval = Rule()
RULE contract_requires_approval #.
contract_requires_person_organization = Rule()
RULE contract_requires_person_organization #.
contracted_item
coordinated_assembly_and_shape = Rule()
RULE coordinated_assembly_and_shape #.
curve_on_surface
date_time_item
date_time_select
dependent_instantiable_action_directive = Rule()
RULE dependent_instantiable_action_directive #.
dependent_instantiable_approval_status = Rule()
RULE dependent_instantiable_approval_status #.
dependent_instantiable_certification_type = Rule()
RULE dependent_instantiable_certification_type #.
dependent_instantiable_contract_type = Rule()
RULE dependent_instantiable_contract_type #.
dependent_instantiable_date = Rule()
RULE dependent_instantiable_date #.
dependent_instantiable_date_time_role = Rule()
RULE dependent_instantiable_date_time_role #.
dependent_instantiable_document_type = Rule()
RULE dependent_instantiable_document_type #.
dependent_instantiable_named_unit = Rule()
RULE dependent_instantiable_named_unit #.
dependent_instantiable_parametric_representation_context = Rule()
RULE dependent_instantiable_parametric_representation_context #.
dependent_instantiable_person_and_organization_role = Rule()
RULE dependent_instantiable_person_and_organization_role #.
dependent_instantiable_representation_item = Rule()
RULE dependent_instantiable_representation_item #.
dependent_instantiable_security_classification_level = Rule()
RULE dependent_instantiable_security_classification_level #.
dependent_instantiable_shape_representation = Rule()
RULE dependent_instantiable_shape_representation #.
design_context_for_property = Rule()
RULE design_context_for_property #.
document_to_product_definition = Rule()
RULE document_to_product_definition #.
effectivity_requires_approval = Rule()
RULE effectivity_requires_approval #.
founded_item_select
geometric_representation_item_3d = Rule()
RULE geometric_representation_item_3d #.
geometric_set_select
global_unit_assignment = Rule()
RULE global_unit_assignment #.
list_of_reversible_topology_item = LIST(0,None,'reversible_topology_item', scope = schema_scope)
measure_value
no_shape_for_make_from = Rule()
RULE no_shape_for_make_from #.
no_shape_for_supplied_part = Rule()
RULE no_shape_for_supplied_part #.
pcurve_or_surface
person_organization_item
person_organization_select
product_concept_requires_configuration_item = Rule()
RULE product_concept_requires_configuration_item #.
product_definition_requires_approval = Rule()
RULE product_definition_requires_approval #.
product_definition_requires_date_time = Rule()
RULE product_definition_requires_date_time #.
product_definition_requires_person_organization = Rule()
RULE product_definition_requires_person_organization #.
product_requires_person_organization = Rule()
RULE product_requires_person_organization #.
product_requires_product_category = Rule()
RULE product_requires_product_category #.
product_requires_version = Rule()
RULE product_requires_version #.
product_version_requires_approval = Rule()
RULE product_version_requires_approval #.
product_version_requires_person_organization = Rule()
RULE product_version_requires_person_organization #.
product_version_requires_security_classification = Rule()
RULE product_version_requires_security_classification #.
restrict_action_request_status = Rule()
RULE restrict_action_request_status #.
restrict_approval_status = Rule()
RULE restrict_approval_status #.
restrict_certification_type = Rule()
RULE restrict_certification_type #.
restrict_contract_type = Rule()
RULE restrict_contract_type #.
restrict_date_time_role = Rule()
RULE restrict_date_time_role #.
restrict_document_type = Rule()
RULE restrict_document_type #.
restrict_person_organization_role = Rule()
RULE restrict_person_organization_role #.
restrict_product_category_value = Rule()
RULE restrict_product_category_value #.
restrict_security_classification_level = Rule()
RULE restrict_security_classification_level #.
reversible_topology
reversible_topology_item
string schema_name = 'config_control_design'
schema_scope = sys.modules[__name__]
security_classification_optional_date_time = Rule()
RULE security_classification_optional_date_time #.
security_classification_requires_approval = Rule()
RULE security_classification_requires_approval #.
security_classification_requires_date_time = Rule()
RULE security_classification_requires_date_time #.
security_classification_requires_person_organization = Rule()
RULE security_classification_requires_person_organization #.
set_of_reversible_topology_item = SET(0,None,'reversible_topology_item', scope = schema_scope)
shape_definition
shell
specified_item
start_request_item
start_request_requires_approval = Rule()
RULE start_request_requires_approval #.
start_request_requires_date_time = Rule()
RULE start_request_requires_date_time #.
start_request_requires_person_organization = Rule()
RULE start_request_requires_person_organization #.
start_work_requires_approval = Rule()
RULE start_work_requires_approval #.
start_work_requires_date_time = Rule()
RULE start_work_requires_date_time #.
subtype_mandatory_action = Rule()
RULE subtype_mandatory_action #.
subtype_mandatory_effectivity = Rule()
RULE subtype_mandatory_effectivity #.
subtype_mandatory_product_context = Rule()
RULE subtype_mandatory_product_context #.
subtype_mandatory_product_definition_formation = Rule()
RULE subtype_mandatory_product_definition_formation #.
subtype_mandatory_product_definition_usage = Rule()
RULE subtype_mandatory_product_definition_usage #.
subtype_mandatory_representation = Rule()
RULE subtype_mandatory_representation #.
subtype_mandatory_representation_context = Rule()
RULE subtype_mandatory_representation_context #.
subtype_mandatory_shape_representation = Rule()
RULE subtype_mandatory_shape_representation #.
supported_item
surface_model
transformation
trimming_select
unique_version_change_order_rule = Rule()
RULE unique_version_change_order_rule #.
unit
vector_or_direction
versioned_action_request_requires_solution = Rule()
RULE versioned_action_request_requires_solution #.
versioned_action_request_requires_status = Rule()
RULE versioned_action_request_requires_status #.
wireframe_model
work_item
Function Documentation
acyclic_curve_replica()
def config_control_design.acyclic_curve_replica (rep, parent)
FUNCTION acyclic_curve_replica #.
        :param rep
        :type rep:curve_replica
        :param parent
        :type parent:curve
Referenced by config_control_design.curve_replica.wr2().
acyclic_mapped_representation()
def config_control_design.acyclic_mapped_representation (parent_set, children_set)
FUNCTION acyclic_mapped_representation #.
        :param parent_set
        :type parent_set:(null)
        :param children_set
        :type children_set:(null)
Referenced by config_control_design.mapped_item.wr1().
acyclic_point_replica()
def config_control_design.acyclic_point_replica (rep, parent)
FUNCTION acyclic_point_replica #.
        :param rep
        :type rep:point_replica
        :param parent
        :type parent:point
Referenced by config_control_design.point_replica.wr2().
acyclic_product_category_relationship()
def config_control_design.acyclic_product_category_relationship (relation, children)
FUNCTION acyclic_product_category_relationship #.
        :param relation
        :type relation:product_category_relationship
        :param children
        :type children:(null)
References bag_to_set().
Referenced by config_control_design.product_category_relationship.wr1().
acyclic_product_definition_relationship()
def config_control_design.acyclic_product_definition_relationship (relation, relatives, specific_relation)
FUNCTION acyclic_product_definition_relationship #.
        :param relation
        :type relation:product_definition_relationship
        :param relatives
        :type relatives:(null)
        :param specific_relation
        :type specific_relation:STRING
Referenced by config_control_design.product_definition_usage.wr1().
acyclic_surface_replica()
def config_control_design.acyclic_surface_replica (rep, parent)
FUNCTION acyclic_surface_replica #.
        :param rep
        :type rep:surface_replica
        :param parent
        :type parent:surface
Referenced by config_control_design.surface_replica.wr1().
assembly_shape_is_defined()
def config_control_design.assembly_shape_is_defined (assy, schma)
FUNCTION assembly_shape_is_defined #.
        :param assy
        :type assy:next_assembly_usage_occurrence
        :param schma
        :type schma:STRING
References bag_to_set().
associated_surface()
def config_control_design.associated_surface (arg)
FUNCTION associated_surface #.
        :param arg
        :type arg:pcurve_or_surface
Referenced by get_basis_surface(), config_control_design.intersection_curve.wr2(), and config_control_design.seam_curve.wr2().
bag_to_set()
def config_control_design.bag_to_set (the_bag)
FUNCTION bag_to_set #.
        :param the_bag
        :type the_bag:(null)
Referenced by acyclic_product_category_relationship(), and assembly_shape_is_defined().
base_axis()
def config_control_design.base_axis (dim, axis1, axis2, axis3)
FUNCTION base_axis #.
        :param dim
        :type dim:INTEGER
        :param axis1
        :type axis1:direction
        :param axis2
        :type axis2:direction
        :param axis3
        :type axis3:direction
References dot_product(), first_proj_axis(), normalise(), orthogonal_complement(), and second_proj_axis().
Referenced by config_control_design.cartesian_transformation_operator_3d.u().
boolean_choose()
def config_control_design.boolean_choose (b, choice1, choice2)
FUNCTION boolean_choose #.
        :param b
        :type b:BOOLEAN
        :param choice1
        :type choice1:(null)
        :param choice2
        :type choice2:(null)
Referenced by config_control_design.oriented_edge.edge_edge_end(), and config_control_design.oriented_edge.edge_edge_start().
build_2axes()
def config_control_design.build_2axes (ref_direction)
        :param ref_direction
        :type ref_direction:direction
References orthogonal_complement().
Referenced by config_control_design.axis2_placement_2d.p().
build_axes()
def config_control_design.build_axes (axis, ref_direction)
FUNCTION build_axes #.
        :param axis
        :type axis:direction
        :param ref_direction
        :type ref_direction:direction
References cross_product(), first_proj_axis(), and normalise().
Referenced by config_control_design.axis2_placement_3d.p().
cc_design_date_time_correlation()
def config_control_design.cc_design_date_time_correlation (e)
FUNCTION cc_design_date_time_correlation #.
        :param e
        :type e:cc_design_date_and_time_assignment
Referenced by config_control_design.cc_design_date_and_time_assignment.wr1().
cc_design_person_and_organization_correlation()
def config_control_design.cc_design_person_and_organization_correlation (e)
FUNCTION cc_design_person_and_organization_correlation #.
        :param e
        :type e:cc_design_person_and_organization_assignment
Referenced by config_control_design.cc_design_person_and_organization_assignment.wr1().
closed_shell_reversed()
def config_control_design.closed_shell_reversed (a_shell)
FUNCTION closed_shell_reversed #.
        :param a_shell
        :type a_shell:closed_shell
Referenced by shell_reversed().
conditional_reverse()
def config_control_design.conditional_reverse (p, an_item)
FUNCTION conditional_reverse #.
        :param p
        :type p:BOOLEAN
        :param an_item
        :type an_item:reversible_topology
References topology_reversed().
Referenced by config_control_design.oriented_open_shell.connected_face_set_cfs_faces(), config_control_design.oriented_closed_shell.connected_face_set_cfs_faces(), config_control_design.oriented_face.face_bounds(), and config_control_design.oriented_path.path_edge_list().
constraints_composite_curve_on_surface()
def config_control_design.constraints_composite_curve_on_surface (c)
FUNCTION constraints_composite_curve_on_surface #.
        :param c
        :type c:composite_curve_on_surface
Referenced by config_control_design.composite_curve_on_surface.wr2().
constraints_geometry_shell_based_surface_model()
def config_control_design.constraints_geometry_shell_based_surface_model (m)
FUNCTION constraints_geometry_shell_based_surface_model #.
        :param m
        :type m:shell_based_surface_model
Referenced by config_control_design.shell_based_surface_model.wr1().
constraints_geometry_shell_based_wireframe_model()
def config_control_design.constraints_geometry_shell_based_wireframe_model (m)
FUNCTION constraints_geometry_shell_based_wireframe_model #.
        :param m
        :type m:shell_based_wireframe_model
Referenced by config_control_design.shell_based_wireframe_model.wr1().
constraints_param_b_spline()
def config_control_design.constraints_param_b_spline (degree, up_knots, up_cp, knot_mult, knots)
FUNCTION constraints_param_b_spline #.
        :param degree
        :type degree:INTEGER
        :param up_knots
        :type up_knots:INTEGER
        :param up_cp
        :type up_cp:INTEGER
        :param knot_mult
        :type knot_mult:(null)
        :param knots
        :type knots:(null)
Referenced by config_control_design.b_spline_curve_with_knots.wr1(), config_control_design.b_spline_surface_with_knots.wr1(), and config_control_design.b_spline_surface_with_knots.wr2().
constraints_rectangular_composite_surface()
def config_control_design.constraints_rectangular_composite_surface (s)
FUNCTION constraints_rectangular_composite_surface #.
        :param s
        :type s:rectangular_composite_surface
Referenced by config_control_design.rectangular_composite_surface.wr2().
cross_product()
def config_control_design.cross_product (arg1, arg2)
FUNCTION cross_product #.
        :param arg1
        :type arg1:direction
        :param arg2
        :type arg2:direction
References normalise().
Referenced by build_axes(), first_proj_axis(), and config_control_design.axis2_placement_3d.wr4().
curve_weights_positive()
def config_control_design.curve_weights_positive (b)
FUNCTION curve_weights_positive #.
        :param b
        :type b:rational_b_spline_curve
Referenced by config_control_design.rational_b_spline_curve.wr2().
derive_dimensional_exponents()
def config_control_design.derive_dimensional_exponents (x)
FUNCTION derive_dimensional_exponents #.
        :param x
        :type x:unit
Referenced by valid_units().
dimension_of()
def config_control_design.dimension_of (item)
FUNCTION dimension_of #.
        :param item
        :type item:geometric_representation_item
References using_representations().
Referenced by config_control_design.geometric_representation_item.dim().
dimensions_for_si_unit()
def config_control_design.dimensions_for_si_unit (n)
FUNCTION dimensions_for_si_unit #.
        :param n
        :type n:si_unit_name
Referenced by config_control_design.si_unit.named_unit_dimensions().
dot_product()
def config_control_design.dot_product (arg1, arg2)
FUNCTION dot_product #.
        :param arg1
        :type arg1:direction
        :param arg2
        :type arg2:direction
References normalise().
Referenced by base_axis(), first_proj_axis(), and second_proj_axis().
edge_reversed()
def config_control_design.edge_reversed (an_edge)
FUNCTION edge_reversed #.
        :param an_edge
        :type an_edge:edge
Referenced by topology_reversed().
face_bound_reversed()
def config_control_design.face_bound_reversed (a_face_bound)
FUNCTION face_bound_reversed #.
        :param a_face_bound
        :type a_face_bound:face_bound
Referenced by topology_reversed().
face_reversed()
def config_control_design.face_reversed (a_face)
FUNCTION face_reversed #.
        :param a_face
        :type a_face:face
References set_of_topology_reversed().
Referenced by topology_reversed().
first_proj_axis()
def config_control_design.first_proj_axis (z_axis, arg)
FUNCTION first_proj_axis #.
        :param z_axis
        :type z_axis:direction
        :param arg
        :type arg:direction
References cross_product(), dot_product(), normalise(), scalar_times_vector(), and vector_difference().
Referenced by base_axis(), and build_axes().
gbsf_check_curve()
def config_control_design.gbsf_check_curve (cv)
FUNCTION gbsf_check_curve #.
        :param cv
        :type cv:curve
References gbsf_check_surface().
Referenced by gbsf_check_point(), and gbsf_check_surface().
gbsf_check_point()
def config_control_design.gbsf_check_point (pnt)
FUNCTION gbsf_check_point #.
        :param pnt
        :type pnt:point
References gbsf_check_curve(), and gbsf_check_surface().
gbsf_check_surface()
def config_control_design.gbsf_check_surface (sf)
FUNCTION gbsf_check_surface #.
        :param sf
        :type sf:surface
References gbsf_check_curve().
Referenced by gbsf_check_curve(), and gbsf_check_point().
get_basis_surface()
def config_control_design.get_basis_surface (c)
FUNCTION get_basis_surface #.
        :param c
        :type c:curve_on_surface
References associated_surface().
Referenced by config_control_design.composite_curve_on_surface.basis_surface(), and config_control_design.surface_curve.basis_surface().
item_in_context()
def config_control_design.item_in_context (item, cntxt)
FUNCTION item_in_context #.
        :param item
        :type item:representation_item
        :param cntxt
        :type cntxt:representation_context
Referenced by config_control_design.representation_map.wr1().
leap_year()
def config_control_design.leap_year (year)
FUNCTION leap_year #.
        :param year
        :type year:INTEGER
Referenced by valid_calendar_date(), and config_control_design.ordinal_date.wr1().
list_face_loops()
def config_control_design.list_face_loops (f)
FUNCTION list_face_loops #.
        :param f
        :type f:face
Referenced by config_control_design.face.wr1().
list_of_topology_reversed()
def config_control_design.list_of_topology_reversed (a_list)
FUNCTION list_of_topology_reversed #.
        :param a_list
        :type a_list:list_of_reversible_topology_item
References topology_reversed().
Referenced by path_reversed(), and topology_reversed().
list_to_array()
def config_control_design.list_to_array (lis, low, u)
FUNCTION list_to_array #.
        :param lis
        :type lis:(null)
        :param low
        :type low:INTEGER
        :param u
        :type u:INTEGER
Referenced by config_control_design.b_spline_curve.control_points(), make_array_of_array(), and config_control_design.rational_b_spline_curve.weights().
list_to_set()
def config_control_design.list_to_set (l)
FUNCTION list_to_set #.
        :param l
        :type l:(null)
Referenced by config_control_design.face.wr1().
make_array_of_array()
def config_control_design.make_array_of_array (lis, low1, u1, low2, u2)
FUNCTION make_array_of_array #.
        :param lis
        :type lis:(null)
        :param low1
        :type low1:INTEGER
        :param u1
        :type u1:INTEGER
        :param low2
        :type low2:INTEGER
        :param u2
        :type u2:INTEGER
References list_to_array().
Referenced by config_control_design.b_spline_surface.control_points(), and config_control_design.rational_b_spline_surface.weights().
mixed_loop_type_set()
def config_control_design.mixed_loop_type_set (l)
FUNCTION mixed_loop_type_set #.
        :param l
        :type l:(null)
Referenced by config_control_design.face.wr1(), and config_control_design.wire_shell.wr1().
msb_shells()
def config_control_design.msb_shells (brep)
FUNCTION msb_shells #.
        :param brep
        :type brep:manifold_solid_brep
msf_curve_check()
def config_control_design.msf_curve_check (cv)
FUNCTION msf_curve_check #.
        :param cv
        :type cv:curve
References msf_surface_check().
Referenced by msf_surface_check().
msf_surface_check()
def config_control_design.msf_surface_check (surf)
FUNCTION msf_surface_check #.
        :param surf
        :type surf:surface
References msf_curve_check().
Referenced by msf_curve_check().
normalise()
def config_control_design.normalise (arg)
FUNCTION normalise #.
        :param arg
        :type arg:vector_or_direction
Referenced by base_axis(), build_axes(), cross_product(), dot_product(), first_proj_axis(), scalar_times_vector(), second_proj_axis(), and vector_difference().
open_shell_reversed()
def config_control_design.open_shell_reversed (a_shell)
FUNCTION open_shell_reversed #.
        :param a_shell
        :type a_shell:open_shell
Referenced by shell_reversed().
orthogonal_complement()
def config_control_design.orthogonal_complement (vec)
FUNCTION orthogonal_complement #.
        :param vec
        :type vec:direction
Referenced by base_axis(), and build_2axes().
path_head_to_tail()
def config_control_design.path_head_to_tail (a_path)
FUNCTION path_head_to_tail #.
        :param a_path
        :type a_path:path
Referenced by config_control_design.path.wr1().
path_reversed()
def config_control_design.path_reversed (a_path)
FUNCTION path_reversed #.
        :param a_path
        :type a_path:path
References list_of_topology_reversed().
Referenced by topology_reversed().
scalar_times_vector()
def config_control_design.scalar_times_vector (scalar, vec)
FUNCTION scalar_times_vector #.
        :param scalar
        :type scalar:REAL
        :param vec
        :type vec:vector_or_direction
References normalise().
Referenced by first_proj_axis(), and second_proj_axis().
second_proj_axis()
def config_control_design.second_proj_axis (z_axis, x_axis, arg)
FUNCTION second_proj_axis #.
        :param z_axis
        :type z_axis:direction
        :param x_axis
        :type x_axis:direction
        :param arg
        :type arg:direction
References dot_product(), normalise(), scalar_times_vector(), and vector_difference().
Referenced by base_axis().
set_of_topology_reversed()
def config_control_design.set_of_topology_reversed (a_set)
FUNCTION set_of_topology_reversed #.
        :param a_set
        :type a_set:set_of_reversible_topology_item
References topology_reversed().
Referenced by face_reversed(), and topology_reversed().
shell_reversed()
def config_control_design.shell_reversed (a_shell)
FUNCTION shell_reversed #.
        :param a_shell
        :type a_shell:shell
References closed_shell_reversed(), and open_shell_reversed().
Referenced by topology_reversed().
surface_weights_positive()
def config_control_design.surface_weights_positive (b)
FUNCTION surface_weights_positive #.
        :param b
        :type b:rational_b_spline_surface
Referenced by config_control_design.rational_b_spline_surface.wr2().
topology_reversed()
def config_control_design.topology_reversed (an_item)
FUNCTION topology_reversed #.
        :param an_item
        :type an_item:reversible_topology
References edge_reversed(), face_bound_reversed(), face_reversed(), list_of_topology_reversed(), path_reversed(), set_of_topology_reversed(), and shell_reversed().
Referenced by conditional_reverse(), list_of_topology_reversed(), and set_of_topology_reversed().
unique_version_change_order()
def config_control_design.unique_version_change_order (c)
FUNCTION unique_version_change_order #.
        :param c
        :type c:action
using_items()
def config_control_design.using_items (item, checked_items)
FUNCTION using_items #.
        :param item
        :type item:founded_item_select
        :param checked_items
        :type checked_items:(null)
Referenced by using_representations().
using_representations()
def config_control_design.using_representations (item)
FUNCTION using_representations #.
        :param item
        :type item:founded_item_select
References using_items().
Referenced by dimension_of(), config_control_design.representation_item.wr1(), and config_control_design.mapped_item.wr1().
valid_calendar_date()
def config_control_design.valid_calendar_date (date)
FUNCTION valid_calendar_date #.
        :param date
        :type date:calendar_date
References leap_year().
Referenced by config_control_design.calendar_date.wr1().
valid_geometrically_bounded_wf_curve()
def config_control_design.valid_geometrically_bounded_wf_curve (crv)
FUNCTION valid_geometrically_bounded_wf_curve #.
        :param crv
        :type crv:curve
Referenced by valid_geometrically_bounded_wf_point().
valid_geometrically_bounded_wf_point()
def config_control_design.valid_geometrically_bounded_wf_point (pnt)
FUNCTION valid_geometrically_bounded_wf_point #.
        :param pnt
        :type pnt:point
References valid_geometrically_bounded_wf_curve().
valid_measure_value()
def config_control_design.valid_measure_value (m)
FUNCTION valid_measure_value #.
        :param m
        :type m:measure_value
Referenced by config_control_design.uncertainty_measure_with_unit.wr1().
valid_time()
def config_control_design.valid_time (time)
FUNCTION valid_time #.
        :param time
        :type time:local_time
Referenced by config_control_design.local_time.wr1().
valid_units()
def config_control_design.valid_units (m)
FUNCTION valid_units #.
        :param m
        :type m:measure_with_unit
References derive_dimensional_exponents().
Referenced by config_control_design.measure_with_unit.wr1().
valid_wireframe_edge_curve()
def config_control_design.valid_wireframe_edge_curve (crv)
FUNCTION valid_wireframe_edge_curve #.
        :param crv
        :type crv:curve
valid_wireframe_vertex_point()
def config_control_design.valid_wireframe_vertex_point (pnt)
FUNCTION valid_wireframe_vertex_point #.
        :param pnt
        :type pnt:point
vector_difference()
def config_control_design.vector_difference (arg1, arg2)
FUNCTION vector_difference #.
        :param arg1
        :type arg1:vector_or_direction
        :param arg2
        :type arg2:vector_or_direction
References normalise().
Referenced by first_proj_axis(), and second_proj_axis().
Variable Documentation
acu_requires_security_classification
config_control_design.acu_requires_security_classification = Rule()
RULE acu_requires_security_classification #.
application_context_requires_ap_definition
config_control_design.application_context_requires_ap_definition = Rule()
RULE application_context_requires_ap_definition #.
approval_date_time_constraints
config_control_design.approval_date_time_constraints = Rule()
RULE approval_date_time_constraints #.
approval_person_organization_constraints
config_control_design.approval_person_organization_constraints = Rule()
RULE approval_person_organization_constraints #.
approval_requires_approval_date_time
config_control_design.approval_requires_approval_date_time = Rule()
RULE approval_requires_approval_date_time #.
approval_requires_approval_person_organization
config_control_design.approval_requires_approval_person_organization = Rule()
RULE approval_requires_approval_person_organization #.
approvals_are_assigned
config_control_design.approvals_are_assigned = Rule()
RULE approvals_are_assigned #.
approved_item
config_control_design.approved_item
Initial value:
 =  SELECT(
         'product_definition_formation',
         'product_definition',
         'configuration_effectivity',
         'configuration_item',
         'security_classification',
         'change_request',
         'change',
         'start_request',
         'start_work',
         'certification',
         'contract',
         scope = schema_scope)
as_required_quantity
config_control_design.as_required_quantity = Rule()
RULE as_required_quantity #.
axis2_placement
config_control_design.axis2_placement
Initial value:
 =  SELECT(
         'axis2_placement_2d',
         'axis2_placement_3d',
         scope = schema_scope)
Referenced by config_control_design.conic.position().
boolean_operand
config_control_design.boolean_operand
Initial value:
 =  SELECT(
         'solid_model',
         scope = schema_scope)
certification_requires_approval
config_control_design.certification_requires_approval = Rule()
RULE certification_requires_approval #.
certification_requires_date_time
config_control_design.certification_requires_date_time = Rule()
RULE certification_requires_date_time #.
certified_item
config_control_design.certified_item
Initial value:
 =  SELECT(
         'supplied_part_relationship',
         scope = schema_scope)
change_request_item
config_control_design.change_request_item
Initial value:
 =  SELECT(
         'product_definition_formation',
         scope = schema_scope)
change_request_requires_approval
config_control_design.change_request_requires_approval = Rule()
RULE change_request_requires_approval #.
change_request_requires_date_time
config_control_design.change_request_requires_date_time = Rule()
RULE change_request_requires_date_time #.
change_request_requires_person_organization
config_control_design.change_request_requires_person_organization = Rule()
RULE change_request_requires_person_organization #.
change_requires_approval
config_control_design.change_requires_approval = Rule()
RULE change_requires_approval #.
change_requires_date_time
config_control_design.change_requires_date_time = Rule()
RULE change_requires_date_time #.
characterized_definition
config_control_design.characterized_definition
Initial value:
 =  SELECT(
         'characterized_product_definition',
         'shape_definition',
         scope = schema_scope)
Referenced by config_control_design.property_definition.definition().
characterized_product_definition
config_control_design.characterized_product_definition
Initial value:
 =  SELECT(
         'product_definition',
         'product_definition_relationship',
         scope = schema_scope)
classified_item
config_control_design.classified_item
Initial value:
 =  SELECT(
         'product_definition_formation',
         'assembly_component_usage',
         scope = schema_scope)
compatible_dimension
config_control_design.compatible_dimension = Rule()
RULE compatible_dimension #.
configuration_item_requires_approval
config_control_design.configuration_item_requires_approval = Rule()
RULE configuration_item_requires_approval #.
configuration_item_requires_person_organization
config_control_design.configuration_item_requires_person_organization = Rule()
RULE configuration_item_requires_person_organization #.
contract_requires_approval
config_control_design.contract_requires_approval = Rule()
RULE contract_requires_approval #.
contract_requires_person_organization
config_control_design.contract_requires_person_organization = Rule()
RULE contract_requires_person_organization #.
contracted_item
config_control_design.contracted_item
Initial value:
 =  SELECT(
         'product_definition_formation',
         scope = schema_scope)
coordinated_assembly_and_shape
config_control_design.coordinated_assembly_and_shape = Rule()
RULE coordinated_assembly_and_shape #.
curve_on_surface
config_control_design.curve_on_surface
Initial value:
 =  SELECT(
         'pcurve',
         'surface_curve',
         'composite_curve_on_surface',
         scope = schema_scope)
date_time_item
config_control_design.date_time_item
Initial value:
 =  SELECT(
         'product_definition',
         'change_request',
         'start_request',
         'change',
         'start_work',
         'approval_person_organization',
         'contract',
         'security_classification',
         'certification',
         scope = schema_scope)
date_time_select
config_control_design.date_time_select
Initial value:
 =  SELECT(
         'date',
         'local_time',
         'date_and_time',
         scope = schema_scope)
Referenced by config_control_design.approval_date_time.date_time().
dependent_instantiable_action_directive
config_control_design.dependent_instantiable_action_directive = Rule()
RULE dependent_instantiable_action_directive #.
dependent_instantiable_approval_status
config_control_design.dependent_instantiable_approval_status = Rule()
RULE dependent_instantiable_approval_status #.
dependent_instantiable_certification_type
config_control_design.dependent_instantiable_certification_type = Rule()
RULE dependent_instantiable_certification_type #.
dependent_instantiable_contract_type
config_control_design.dependent_instantiable_contract_type = Rule()
RULE dependent_instantiable_contract_type #.
dependent_instantiable_date
config_control_design.dependent_instantiable_date = Rule()
RULE dependent_instantiable_date #.
dependent_instantiable_date_time_role
config_control_design.dependent_instantiable_date_time_role = Rule()
RULE dependent_instantiable_date_time_role #.
dependent_instantiable_document_type
config_control_design.dependent_instantiable_document_type = Rule()
RULE dependent_instantiable_document_type #.
dependent_instantiable_named_unit
config_control_design.dependent_instantiable_named_unit = Rule()
RULE dependent_instantiable_named_unit #.
dependent_instantiable_parametric_representation_context
config_control_design.dependent_instantiable_parametric_representation_context = Rule()
RULE dependent_instantiable_parametric_representation_context #.
dependent_instantiable_person_and_organization_role
config_control_design.dependent_instantiable_person_and_organization_role = Rule()
RULE dependent_instantiable_person_and_organization_role #.
dependent_instantiable_representation_item
config_control_design.dependent_instantiable_representation_item = Rule()
RULE dependent_instantiable_representation_item #.
dependent_instantiable_security_classification_level
config_control_design.dependent_instantiable_security_classification_level = Rule()
RULE dependent_instantiable_security_classification_level #.
dependent_instantiable_shape_representation
config_control_design.dependent_instantiable_shape_representation = Rule()
RULE dependent_instantiable_shape_representation #.
design_context_for_property
config_control_design.design_context_for_property = Rule()
RULE design_context_for_property #.
document_to_product_definition
config_control_design.document_to_product_definition = Rule()
RULE document_to_product_definition #.
effectivity_requires_approval
config_control_design.effectivity_requires_approval = Rule()
RULE effectivity_requires_approval #.
founded_item_select
config_control_design.founded_item_select
Initial value:
 =  SELECT(
         'founded_item',
         'representation_item',
         scope = schema_scope)
geometric_representation_item_3d
config_control_design.geometric_representation_item_3d = Rule()
RULE geometric_representation_item_3d #.
geometric_set_select
config_control_design.geometric_set_select
Initial value:
 =  SELECT(
         'point',
         'curve',
         'surface',
         scope = schema_scope)
global_unit_assignment
config_control_design.global_unit_assignment = Rule()
RULE global_unit_assignment #.
list_of_reversible_topology_item
config_control_design.list_of_reversible_topology_item = LIST(0,None,'reversible_topology_item', scope = schema_scope)
measure_value
config_control_design.measure_value
Initial value:
 =  SELECT(
         'length_measure',
         'mass_measure',
         'plane_angle_measure',
         'solid_angle_measure',
         'area_measure',
         'volume_measure',
         'parameter_value',
         'context_dependent_measure',
         'descriptive_measure',
         'positive_length_measure',
         'positive_plane_angle_measure',
         'count_measure',
         scope = schema_scope)
Referenced by config_control_design.measure_with_unit.value_component().
no_shape_for_make_from
config_control_design.no_shape_for_make_from = Rule()
RULE no_shape_for_make_from #.
no_shape_for_supplied_part
config_control_design.no_shape_for_supplied_part = Rule()
RULE no_shape_for_supplied_part #.
pcurve_or_surface
config_control_design.pcurve_or_surface
Initial value:
 =  SELECT(
         'pcurve',
         'surface',
         scope = schema_scope)
person_organization_item
config_control_design.person_organization_item
Initial value:
 =  SELECT(
         'change',
         'start_work',
         'change_request',
         'start_request',
         'configuration_item',
         'product',
         'product_definition_formation',
         'product_definition',
         'contract',
         'security_classification',
         scope = schema_scope)
person_organization_select
config_control_design.person_organization_select
Initial value:
 =  SELECT(
         'person',
         'organization',
         'person_and_organization',
         scope = schema_scope)
Referenced by config_control_design.approval_person_organization.person_organization().
product_concept_requires_configuration_item
config_control_design.product_concept_requires_configuration_item = Rule()
RULE product_concept_requires_configuration_item #.
product_definition_requires_approval
config_control_design.product_definition_requires_approval = Rule()
RULE product_definition_requires_approval #.
product_definition_requires_date_time
config_control_design.product_definition_requires_date_time = Rule()
RULE product_definition_requires_date_time #.
product_definition_requires_person_organization
config_control_design.product_definition_requires_person_organization = Rule()
RULE product_definition_requires_person_organization #.
product_requires_person_organization
config_control_design.product_requires_person_organization = Rule()
RULE product_requires_person_organization #.
product_requires_product_category
config_control_design.product_requires_product_category = Rule()
RULE product_requires_product_category #.
product_requires_version
config_control_design.product_requires_version = Rule()
RULE product_requires_version #.
product_version_requires_approval
config_control_design.product_version_requires_approval = Rule()
RULE product_version_requires_approval #.
product_version_requires_person_organization
config_control_design.product_version_requires_person_organization = Rule()
RULE product_version_requires_person_organization #.
product_version_requires_security_classification
config_control_design.product_version_requires_security_classification = Rule()
RULE product_version_requires_security_classification #.
restrict_action_request_status
config_control_design.restrict_action_request_status = Rule()
RULE restrict_action_request_status #.
restrict_approval_status
config_control_design.restrict_approval_status = Rule()
RULE restrict_approval_status #.
restrict_certification_type
config_control_design.restrict_certification_type = Rule()
RULE restrict_certification_type #.
restrict_contract_type
config_control_design.restrict_contract_type = Rule()
RULE restrict_contract_type #.
restrict_date_time_role
config_control_design.restrict_date_time_role = Rule()
RULE restrict_date_time_role #.
restrict_document_type
config_control_design.restrict_document_type = Rule()
RULE restrict_document_type #.
restrict_person_organization_role
config_control_design.restrict_person_organization_role = Rule()
RULE restrict_person_organization_role #.
restrict_product_category_value
config_control_design.restrict_product_category_value = Rule()
RULE restrict_product_category_value #.
restrict_security_classification_level
config_control_design.restrict_security_classification_level = Rule()
RULE restrict_security_classification_level #.
reversible_topology
config_control_design.reversible_topology
Initial value:
 =  SELECT(
         'reversible_topology_item',
         'list_of_reversible_topology_item',
         'set_of_reversible_topology_item',
         scope = schema_scope)
reversible_topology_item
config_control_design.reversible_topology_item
Initial value:
 =  SELECT(
         'edge',
         'path',
         'face',
         'face_bound',
         'closed_shell',
         'open_shell',
         scope = schema_scope)
schema_name
string config_control_design.schema_name = 'config_control_design'
schema_scope
config_control_design.schema_scope = sys.modules[__name__]
security_classification_optional_date_time
config_control_design.security_classification_optional_date_time = Rule()
RULE security_classification_optional_date_time #.
security_classification_requires_approval
config_control_design.security_classification_requires_approval = Rule()
RULE security_classification_requires_approval #.
security_classification_requires_date_time
config_control_design.security_classification_requires_date_time = Rule()
RULE security_classification_requires_date_time #.
security_classification_requires_person_organization
config_control_design.security_classification_requires_person_organization = Rule()
RULE security_classification_requires_person_organization #.
set_of_reversible_topology_item
config_control_design.set_of_reversible_topology_item = SET(0,None,'reversible_topology_item', scope = schema_scope)
shape_definition
config_control_design.shape_definition
Initial value:
 =  SELECT(
         'product_definition_shape',
         'shape_aspect',
         'shape_aspect_relationship',
         scope = schema_scope)
shell
config_control_design.shell
Initial value:
 =  SELECT(
         'vertex_shell',
         'wire_shell',
         'open_shell',
         'closed_shell',
         scope = schema_scope)
specified_item
config_control_design.specified_item
Initial value:
 =  SELECT(
         'product_definition',
         'shape_aspect',
         scope = schema_scope)
start_request_item
config_control_design.start_request_item
Initial value:
 =  SELECT(
         'product_definition_formation',
         scope = schema_scope)
start_request_requires_approval
config_control_design.start_request_requires_approval = Rule()
RULE start_request_requires_approval #.
start_request_requires_date_time
config_control_design.start_request_requires_date_time = Rule()
RULE start_request_requires_date_time #.
start_request_requires_person_organization
config_control_design.start_request_requires_person_organization = Rule()
RULE start_request_requires_person_organization #.
start_work_requires_approval
config_control_design.start_work_requires_approval = Rule()
RULE start_work_requires_approval #.
start_work_requires_date_time
config_control_design.start_work_requires_date_time = Rule()
RULE start_work_requires_date_time #.
subtype_mandatory_action
config_control_design.subtype_mandatory_action = Rule()
RULE subtype_mandatory_action #.
subtype_mandatory_effectivity
config_control_design.subtype_mandatory_effectivity = Rule()
RULE subtype_mandatory_effectivity #.
subtype_mandatory_product_context
config_control_design.subtype_mandatory_product_context = Rule()
RULE subtype_mandatory_product_context #.
subtype_mandatory_product_definition_formation
config_control_design.subtype_mandatory_product_definition_formation = Rule()
RULE subtype_mandatory_product_definition_formation #.
subtype_mandatory_product_definition_usage
config_control_design.subtype_mandatory_product_definition_usage = Rule()
RULE subtype_mandatory_product_definition_usage #.
subtype_mandatory_representation
config_control_design.subtype_mandatory_representation = Rule()
RULE subtype_mandatory_representation #.
subtype_mandatory_representation_context
config_control_design.subtype_mandatory_representation_context = Rule()
RULE subtype_mandatory_representation_context #.
subtype_mandatory_shape_representation
config_control_design.subtype_mandatory_shape_representation = Rule()
RULE subtype_mandatory_shape_representation #.
supported_item
config_control_design.supported_item
Initial value:
 =  SELECT(
         'action_directive',
         'action',
         'action_method',
         scope = schema_scope)
surface_model
config_control_design.surface_model
Initial value:
 =  SELECT(
         'shell_based_surface_model',
         scope = schema_scope)
transformation
config_control_design.transformation
Initial value:
 =  SELECT(
         'item_defined_transformation',
         'functionally_defined_transformation',
         scope = schema_scope)
Referenced by config_control_design.representation_relationship_with_transformation.transformation_operator().
trimming_select
config_control_design.trimming_select
Initial value:
 =  SELECT(
         'cartesian_point',
         'parameter_value',
         scope = schema_scope)
unique_version_change_order_rule
config_control_design.unique_version_change_order_rule = Rule()
RULE unique_version_change_order_rule #.
unit
config_control_design.unit
Initial value:
 =  SELECT(
         'named_unit',
         scope = schema_scope)
Referenced by config_control_design.measure_with_unit.unit_component().
vector_or_direction
config_control_design.vector_or_direction
Initial value:
 =  SELECT(
         'vector',
         'direction',
         scope = schema_scope)
versioned_action_request_requires_solution
config_control_design.versioned_action_request_requires_solution = Rule()
RULE versioned_action_request_requires_solution #.
versioned_action_request_requires_status
config_control_design.versioned_action_request_requires_status = Rule()
RULE versioned_action_request_requires_status #.
wireframe_model
config_control_design.wireframe_model
Initial value:
 =  SELECT(
         'shell_based_wireframe_model',
         'edge_based_wireframe_model',
         scope = schema_scope)
work_item
config_control_design.work_item
Initial value:
 =  SELECT(
         'product_definition_formation',
         scope = schema_scope)