FreeCAD: TechDrawGui::TaskGeomHatch Class Reference
TechDrawGui::TaskGeomHatch Class Reference
#include <TaskGeomHatch.h>
Public Member Functions
virtual bool accept ()
bool getCreateMode ()
virtual bool reject ()
void setCreateMode (bool b)
TaskGeomHatch (TechDraw::DrawGeomHatch *inHatch, TechDrawGui::ViewProviderGeomHatch *inVp, bool mode)
~TaskGeomHatch ()
Protected Slots
void onFileChanged (void)
Protected Member Functions
void changeEvent (QEvent *e)
void getParameters ()
void initUi ()
QStringList listToQ (std::vector< std::string > in)
void updateValues ()
Constructor & Destructor Documentation
TaskGeomHatch()
TaskGeomHatch::TaskGeomHatch (TechDraw::DrawGeomHatch * inHatch, TechDrawGui::ViewProviderGeomHatch * inVp, bool mode)
References draftgeoutils.intersections::connect(), getParameters(), App::PropertyLinkSub::getValue(), initUi(), onFileChanged(), and TechDraw::DrawGeomHatch::Source.
~TaskGeomHatch()
TaskGeomHatch::~TaskGeomHatch ()
Member Function Documentation
accept()
bool TaskGeomHatch::accept (void) virtual
References Gui::Command::Gui, App::DocumentObject::recomputeFeature(), TechDraw::DrawView::requestPaint(), and updateValues().
Referenced by TechDrawGui::TaskDlgGeomHatch::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void TaskGeomHatch::changeEvent (QEvent * e) protected
getCreateMode()
bool TechDrawGui::TaskGeomHatch::getCreateMode (void)
Referenced by getParameters(), and reject().
getParameters()
void TaskGeomHatch::getParameters (void) protected
References TechDrawGui::ViewProviderGeomHatch::ColorPattern, TechDraw::DrawGeomHatch::FilePattern, getCreateMode(), App::PropertyFloat::getValue(), App::PropertyString::getValue(), App::PropertyColor::getValue(), TechDraw::DrawGeomHatch::NamePattern, TechDraw::DrawGeomHatch::ScalePattern, and TechDrawGui::ViewProviderGeomHatch::WeightPattern.
Referenced by TaskGeomHatch().
initUi()
void TaskGeomHatch::initUi (void) protected
References App::Color::asValue(), draftgeoutils.intersections::connect(), Base::Console(), listToQ(), and Base::ConsoleSingleton::Warning().
Referenced by TaskGeomHatch().
listToQ()
QStringList TaskGeomHatch::listToQ (std::vector< std::string > in) protected
Referenced by initUi(), and onFileChanged().
onFileChanged
void TaskGeomHatch::onFileChanged (void) protected slot
References TechDraw::DrawGeomHatch::FilePattern, listToQ(), and App::PropertyString::setValue().
Referenced by TaskGeomHatch().
reject()
bool TaskGeomHatch::reject (void) virtual
References TechDrawGui::ViewProviderGeomHatch::ColorPattern, TechDraw::DrawGeomHatch::FilePattern, getCreateMode(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), Gui::Command::Gui, TechDraw::DrawGeomHatch::NamePattern, App::Document::recompute(), TechDraw::DrawGeomHatch::ScalePattern, App::PropertyString::setValue(), App::PropertyColor::setValue(), App::PropertyFloat::setValue(), App::DocumentObject::touch(), and TechDrawGui::ViewProviderGeomHatch::WeightPattern.
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), TechDrawGui::TaskDlgGeomHatch::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
setCreateMode()
void TechDrawGui::TaskGeomHatch::setCreateMode (bool b)
Referenced by TechDrawGui::TaskDlgGeomHatch::setCreateMode().
updateValues()
void TaskGeomHatch::updateValues (void) protected
References TechDrawGui::ViewProviderGeomHatch::ColorPattern, TechDraw::DrawGeomHatch::FilePattern, TechDraw::DrawGeomHatch::NamePattern, TechDraw::DrawGeomHatch::ScalePattern, App::PropertyString::setValue(), App::PropertyColor::setValue(), App::Color::setValue(), App::PropertyFloat::setValue(), and TechDrawGui::ViewProviderGeomHatch::WeightPattern.
Referenced by accept().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/TaskGeomHatch.h
FreeCAD/src/Mod/TechDraw/Gui/TaskGeomHatch.cpp