FreeCAD: Sketcher::PropertyConstraintList Class Reference
Sketcher::PropertyConstraintList Class Reference
#include <PropertyConstraintList.h>
Public Types
typedef std::pair< int, const Constraint * > ConstraintInfo
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , Busy = 15 ,
CopyOnChange = 16 , UserEdit = 17 , PropStaticBegin = 21 , PropDynamic = 21 ,
PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 , PropTransient = 25 ,
PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 , User1 = 28 ,
User2 = 29 , User3 = 30 , User4 = 31
}
Public Member Functions
void acceptGeometry (const std::vector< Part::Geometry * > &GeoList)
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const override
Convert p to a canonical representation of it.
bool checkConstraintIndices (int geomax, int geomin)
bool checkGeometry (const std::vector< Part::Geometry * > &GeoList)
virtual Property * Copy (void) const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
App::ObjectIdentifier createPath (int ConstrNbr) const
const Constraint * getConstraint (const App::ObjectIdentifier &path) const
const char * getEditorName (void) const override
Get the class name of the associated property editor item.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const override
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const override
Get value of property.
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
virtual bool getPyPathValue (const App::ObjectIdentifier &path, Py::Object &res) const override
Get Python value of property.
virtual int getSize (void) const override
const std::vector< Constraint * > & getValues (void) const
const std::vector< Constraint * > & getValuesForce (void) const
bool hasInvalidGeometry () const
Return status of geometry for better error reporting.
const Constraint * operator[] (const int idx) const
virtual void Paste (const App::Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
PropertyConstraintList ()
A constructor.
virtual void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
bool scanGeometry (const std::vector< Part::Geometry * > &GeoList) const
PropertyConstraintList::scanGeometry tests if the supplied geometry is the same (all elements are of the same type as they used to be).
void set1Value (const int idx, const Constraint *)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value) override
Set value of property.
virtual void setPyObject (PyObject *) override
virtual void setSize (int newSize) override
void setValue (const Constraint *)
void setValues (const std::vector< Constraint * > &)
void setValues (std::vector< Constraint * > &&)
virtual ~PropertyConstraintList ()
A destructor.
Public Member Functions inherited from App::PropertyLists
bool isOrderRelevant () const
void setOrderRelevant (bool on)
virtual void setPyObject (PyObject *obj) override
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual Property * Copy (void) const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
int64_t getID () const
Return a unique ID for the property.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const char * getName (void) const
Get the name of this property in the belonging container With hasName() it can be checked beforehand if a valid name is set.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
bool hasName () const
Check if the property has a name set.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::PropertyListsBase
void clearTouchList ()
virtual int getSize (void) const =0
const std::set< int > & getTouchList () const
virtual void setSize (int newSize)=0
Static Public Member Functions
static std::string getConstraintName (const std::string &name, int i)
static std::string getConstraintName (int i)
static int getIndexFromConstraintName (const std::string &name)
static bool validConstraintName (const std::string &name)
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Check if the passed name is valid.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Public Attributes
boost::signals2::signal< void(const std::set< App::ObjectIdentifier > &)> signalConstraintsRemoved
boost::signals2::signal< void(const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &)> signalConstraintsRenamed
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Additional Inherited Members
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Protected Member Functions inherited from App::PropertyListsBase
virtual void setPyValues (const std::vector< PyObject * > &vals, const std::vector< int > &indices)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Member Typedef Documentation
ConstraintInfo
typedef std::pair<int, const Constraint*> Sketcher::PropertyConstraintList::ConstraintInfo
Constructor & Destructor Documentation
PropertyConstraintList()
PropertyConstraintList::PropertyConstraintList ()
A constructor.
A more elaborate description of the constructor.
Referenced by Copy(), and getMemSize().
~PropertyConstraintList()
PropertyConstraintList::~PropertyConstraintList () virtual
A destructor.
A more elaborate description of the destructor.
Member Function Documentation
acceptGeometry()
void PropertyConstraintList::acceptGeometry (const std::vector< Part::Geometry * > & GeoList)
References App::Property::aboutToSetValue(), Base::Persistence::getTypeId(), and App::Property::hasSetValue().
Referenced by Sketcher::SketchObject::acceptGeometry(), Sketcher::SketchObject::delConstraintsToExternal(), Sketcher::SketchObject::execute(), Sketcher::SketchObject::restoreFinished(), and Sketcher::SketchObject::validateConstraints().
canonicalPath()
ObjectIdentifier PropertyConstraintList::canonicalPath (const App::ObjectIdentifier & p) const override virtual
Convert p to a canonical representation of it.
Reimplemented from App::Property.
References App::Property::getName().
checkConstraintIndices()
bool PropertyConstraintList::checkConstraintIndices (int geomax, int geomin)
Referenced by Sketcher::SketchObject::onChanged(), and Sketcher::SketchObject::onUndoRedoFinished().
checkGeometry()
bool PropertyConstraintList::checkGeometry (const std::vector< Part::Geometry * > & GeoList)
References scanGeometry(), and App::Property::touch().
Referenced by Sketcher::SketchObject::onChanged().
Copy()
Property * PropertyConstraintList::Copy (void) const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References PropertyConstraintList().
createPath()
ObjectIdentifier PropertyConstraintList::createPath (int ConstrNbr) const
Referenced by Sketcher::SketchObject::addCopyOfConstraints(), Sketcher::SketchObject::carbonCopy(), Sketcher::SketchObject::constraintHasExpression(), ConstraintItem::data(), SketcherGui::EditDatumDialog::exec(), ExpressionDelegate::paint(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::processTags(), Sketcher::SketchObject::setDatumsDriving(), Sketcher::SketchObject::setDriving(), and Sketcher::SketchObject::toggleDriving().
getConstraint()
const Constraint * PropertyConstraintList::getConstraint (const App::ObjectIdentifier & path) const
References App::Property::getName().
Referenced by getPathValue(), and Sketcher::SketchObject::validateExpression().
getConstraintName() [1/2]
string PropertyConstraintList::getConstraintName (const std::string & name, int i) static
References getConstraintName().
Referenced by SketcherGui::ConstraintView::contextMenuEvent(), ConstraintItem::data(), getConstraintName(), SketcherGui::ViewProviderSketch::mouseButtonPressed(), SketcherGui::TaskSketcherConstraints::on_listWidgetConstraints_itemChanged(), and SketcherGui::TaskSketcherConstraints::on_listWidgetConstraints_itemSelectionChanged().
getConstraintName() [2/2]
string PropertyConstraintList::getConstraintName (int i) static
getEditorName()
const char * Sketcher::PropertyConstraintList::getEditorName (void) const override virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
getIndexFromConstraintName()
int PropertyConstraintList::getIndexFromConstraintName (const std::string & name) static
Referenced by SketcherGui::ViewProviderSketch::onDelete(), and SketcherGui::ViewProviderSketch::onSelectionChanged().
getMemSize()
unsigned int PropertyConstraintList::getMemSize (void) const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
See also
Base::Persistence
Reimplemented from App::Property.
References getMemSize(), getSize(), and PropertyConstraintList().
Referenced by getMemSize().
getPaths()
void PropertyConstraintList::getPaths (std::vector< App::ObjectIdentifier > & paths) const override virtual
Get valid paths for this property; used by auto completer.
Reimplemented from App::Property.
getPathValue()
const boost::any PropertyConstraintList::getPathValue (const App::ObjectIdentifier & path) const override virtual
Get value of property.
Reimplemented from App::Property.
References getConstraint().
getPyObject()
PyObject * PropertyConstraintList::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
References getPyObject(), and getSize().
Referenced by getPyObject().
getPyPathValue()
bool PropertyConstraintList::getPyPathValue (const App::ObjectIdentifier & , Py::Object &) const override virtual
Get Python value of property.
Reimplemented from App::Property.
References App::Property::getName(), and Sketcher::Constraint::getPresentationValue().
getSize()
int PropertyConstraintList::getSize (void) const override virtual
Implements App::PropertyListsBase.
Referenced by CmdSketcherConstrainLock::activated(), Sketcher::SketchObject::addConstraint(), Sketcher::SketchObject::addConstraints(), Sketcher::SketchObject::addCopyOfConstraints(), ConstraintItem::data(), getMemSize(), getPyObject(), ExpressionDelegate::paint(), and Save().
getValues()
const std::vector< Constraint * > & Sketcher::PropertyConstraintList::getValues (void) const
Referenced by CmdSketcherConstrainHorizontal::activated(), CmdSketcherConstrainVertical::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainAngle::activated(), Sketcher::SketchObject::addConstraint(), Sketcher::SketchObject::addConstraints(), Sketcher::SketchObject::addCopy(), Sketcher::SketchObject::addCopyOfConstraints(), Sketcher::SketchObject::addSymmetric(), CmdSketcherConstrainHorizontal::applyConstraint(), CmdSketcherConstrainVertical::applyConstraint(), CmdSketcherConstrainLock::applyConstraint(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), SketcherGui::areAllPointsOrSegmentsFixed(), SketcherGui::areBothPointsOrSegmentsFixed(), Sketcher::SketchObject::calculateConstraintError(), Sketcher::SketchObject::carbonCopy(), Sketcher::SketchObject::changeConstraintsLocking(), Sketcher::SketchObject::convertToNURBS(), Sketcher::SketchObject::delAllExternal(), Sketcher::SketchObject::delConstraint(), Sketcher::SketchObject::delConstraintOnPoint(), Sketcher::SketchObject::delConstraints(), Sketcher::SketchObject::deleteUnusedInternalGeometry(), Sketcher::SketchObject::delExternal(), Sketcher::SketchObject::delGeometries(), Sketcher::SketchObject::delGeometriesExclusiveList(), Sketcher::SketchObject::delGeometry(), Sketcher::SketchAnalysis::detectMissingEqualityConstraints(), Sketcher::SketchAnalysis::detectMissingPointOnPointConstraints(), Sketcher::SketchObject::diagnoseAdditionalConstraints(), SketcherGui::EditDatumDialog::EditDatumDialog(), SketcherGui::ViewProviderSketch::editDoubleClicked(), SketcherGui::PropertyConstraintListItem::event(), Sketcher::SketchObject::exposeInternalGeometry(), Sketcher::SketchObject::fillet(), Sketcher::SketchObject::getActive(), Sketcher::SketchObject::getCoincidenceGroups(), Sketcher::SketchObject::getConstraintIndices(), Sketcher::SketchObject::getDirectlyCoincidentPoints(), Sketcher::SketchObject::getDriving(), Sketcher::SketchObject::getVirtualSpace(), Sketcher::SketchObject::insertBSplineKnot(), SketcherGui::isPointOrSegmentFixed(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::loadDefaults(), Sketcher::SketchObject::migrateSketch(), Sketcher::SketchObject::modifyBSplineKnotMultiplicity(), Sketcher::SketchObject::moveDatumsToEnd(), Sketcher::SketchObject::movePoint(), SketcherGui::TaskSketcherConstraints::on_listWidgetConstraints_itemChanged(), SketcherGui::ViewProviderSketch::onDelete(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle(), Sketcher::SketchObject::port_reversedExternalArcs(), Sketcher::SketchObject::removeAxesAlignment(), Sketcher::SketchObject::setActive(), Sketcher::SketchObject::setDatum(), Sketcher::SketchObject::setDatumsDriving(), Sketcher::SketchObject::setDriving(), Sketcher::SketchObject::setUpSketch(), Sketcher::SketchObject::setVirtualSpace(), Sketcher::SketchObject::solve(), Sketcher::SketchObject::split(), CmdSketcherConstrainTangent::substituteConstraintCombinations(), CmdSketcherConstrainPointOnObject::substituteConstraintCombinations(), CmdSketcherConstrainCoincident::substituteConstraintCombinations(), Sketcher::SketchObject::synchroniseGeometryState(), Sketcher::SketchObject::testDrivingChange(), Sketcher::SketchObject::toggleActive(), Sketcher::SketchObject::toggleDriving(), Sketcher::SketchObject::toggleVirtualSpace(), Sketcher::SketchObject::transferConstraints(), Sketcher::SketchObject::transferFilletConstraints(), Sketcher::SketchObject::trim(), and Sketcher::SketchObject::validateExternalLinks().
getValuesForce()
const std::vector< Constraint * > & Sketcher::PropertyConstraintList::getValuesForce (void) const
Referenced by Sketcher::SketchObject::delConstraintsToExternal(), Sketcher::SketchObject::evaluateConstraints(), and Sketcher::SketchObject::validateConstraints().
hasInvalidGeometry()
bool Sketcher::PropertyConstraintList::hasInvalidGeometry () const
Return status of geometry for better error reporting.
Referenced by Sketcher::SketchObject::setDatum().
operator[]()
const Constraint * Sketcher::PropertyConstraintList::operator[] (const int idx) const
Index operator
Note
If the geometry is invalid then the index operator returns null. This must be checked by the caller.
Paste()
void PropertyConstraintList::Paste (const App::Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References setValues().
Restore()
void PropertyConstraintList::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References Base::XMLReader::getAttributeAsInteger(), draftfunctions.move::move(), Sketcher::NumConstraintTypes, Base::XMLReader::readElement(), Base::XMLReader::readEndElement(), Sketcher::Constraint::Restore(), setValues(), and Sketcher::Constraint::Type.
Save()
void PropertyConstraintList::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References Base::Writer::decInd(), getSize(), Base::Writer::incInd(), Base::Writer::ind(), Save(), and Base::Writer::Stream().
Referenced by Save().
scanGeometry()
bool PropertyConstraintList::scanGeometry (const std::vector< Part::Geometry * > & GeoList) const
PropertyConstraintList::scanGeometry tests if the supplied geometry is the same (all elements are of the same type as they used to be).
Parameters
GeoList - new geometry list to be checked
Returns
false, if the types have changed.
Referenced by checkGeometry(), Sketcher::SketchObject::evaluateConstraints(), and Sketcher::SketchObject::validateConstraints().
set1Value()
void PropertyConstraintList::set1Value (const int idx, const Constraint * lValue)
Sets a single constraint to the property at a certain position. The value is cloned inernally so it's in the responsibility of the caller to free the memory.
References App::Property::aboutToSetValue(), Sketcher::Constraint::clone(), App::Property::hasSetValue(), Sketcher::Constraint::Name, signalConstraintsRenamed, and Sketcher::Constraint::tag.
Referenced by Sketcher::SketchObject::renameConstraint().
setPathValue()
void PropertyConstraintList::setPathValue (const App::ObjectIdentifier & path, const boost::any & value) override virtual
Set value of property.
Reimplemented from App::Property.
References App::Property::aboutToSetValue(), Sketcher::Angle, App::Property::getName(), and App::Property::hasSetValue().
setPyObject()
void PropertyConstraintList::setPyObject (PyObject * value) override virtual
Reimplemented from App::PropertyLists.
References setValue(), and setValues().
setSize()
void PropertyConstraintList::setSize (int newSize) override virtual
Implements App::PropertyListsBase.
References signalConstraintsRemoved.
setValue()
void PropertyConstraintList::setValue (const Constraint * lValue)
Sets a single constraint to the property. The value is cloned inernally so it's in the responsibility of the caller to free the memory.
References App::Property::aboutToSetValue(), Sketcher::Constraint::clone(), App::Property::hasSetValue(), signalConstraintsRemoved, signalConstraintsRenamed, and Sketcher::Constraint::tag.
Referenced by setPyObject().
setValues() [1/2]
void PropertyConstraintList::setValues (const std::vector< Constraint * > & lValue)
Sets a vector of constraint to the property. The values of the array are cloned inernally so it's in the responsibility of the caller to free the memory.
References draftfunctions.move::move(), and setValues().
Referenced by Sketcher::SketchObject::addConstraint(), Sketcher::SketchObject::addConstraints(), Sketcher::SketchObject::addCopy(), Sketcher::SketchObject::addCopyOfConstraints(), Sketcher::SketchObject::addSymmetric(), Sketcher::SketchObject::carbonCopy(), Sketcher::SketchObject::changeConstraintsLocking(), Sketcher::SketchObject::convertToNURBS(), Sketcher::SketchObject::delAllExternal(), Sketcher::SketchObject::delConstraint(), Sketcher::SketchObject::delConstraintOnPoint(), Sketcher::SketchObject::delConstraints(), Sketcher::SketchObject::delConstraintsToExternal(), Sketcher::SketchObject::deleteAllConstraints(), Sketcher::SketchObject::deleteAllGeometry(), Sketcher::SketchObject::delExternal(), Sketcher::SketchObject::delGeometriesExclusiveList(), Sketcher::SketchObject::delGeometry(), Sketcher::SketchObject::insertBSplineKnot(), Sketcher::SketchObject::modifyBSplineKnotMultiplicity(), Sketcher::SketchObject::moveDatumsToEnd(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle(), Paste(), Sketcher::SketchObject::port_reversedExternalArcs(), Sketcher::SketchObject::removeAxesAlignment(), Restore(), Sketcher::SketchObject::setActive(), Sketcher::SketchObject::setDatum(), Sketcher::SketchObject::setDatumsDriving(), Sketcher::SketchObject::setDriving(), setPyObject(), setValues(), Sketcher::SketchObject::setVirtualSpace(), Sketcher::SketchObject::toggleActive(), Sketcher::SketchObject::toggleDriving(), Sketcher::SketchObject::toggleVirtualSpace(), Sketcher::SketchObject::transferConstraints(), Sketcher::SketchObject::transferFilletConstraints(), Sketcher::SketchObject::validateConstraints(), and Sketcher::SketchObject::validateExternalLinks().
setValues() [2/2]
void PropertyConstraintList::setValues (std::vector< Constraint * > && lValue)
Sets a vector of constraint to the property. The values of the array are moved, and the ownership of constraints inside are taken by this property
References App::Property::aboutToSetValue(), App::Property::hasSetValue(), and draftfunctions.move::move().
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle().
validConstraintName()
bool PropertyConstraintList::validConstraintName (const std::string & name) static
Member Data Documentation
signalConstraintsRemoved
boost::signals2::signal<void (const std::set<App::ObjectIdentifier> &)> Sketcher::PropertyConstraintList::signalConstraintsRemoved
Referenced by setSize(), and setValue().
signalConstraintsRenamed
boost::signals2::signal<void (const std::map<App::ObjectIdentifier, App::ObjectIdentifier> &)> Sketcher::PropertyConstraintList::signalConstraintsRenamed
Referenced by set1Value(), and setValue().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/App/PropertyConstraintList.h
FreeCAD/src/Mod/Sketcher/App/PropertyConstraintList.cpp