FreeCAD: PathScripts.PathPreferences Namespace Reference
PathScripts.PathPreferences Namespace Reference
Functions
def advancedOCLFeaturesEnabled ()
def allAvailablePostProcessors ()
def allEnabledPostProcessors (include=None)
def defaultFilePath ()
def defaultGeometryTolerance ()
def defaultJobTemplate ()
def defaultLibAreaCurveAccuracy ()
def defaultOutputFile ()
def defaultOutputPolicy ()
def defaultPostProcessor ()
def defaultPostProcessorArgs ()
def defaultStockTemplate ()
def defaultTaskPanelLayout ()
def experimentalFeaturesEnabled ()
def filePath ()
def lastFileToolLibrary ()
def lastPathToolBit ()
def lastPathToolLibrary ()
def lastPathToolShape ()
def lastPathToolTable ()
def macroFilePath ()
def pathDefaultToolsPath (sub=None)
def pathScriptsSourcePath ()
def postProcessorBlacklist ()
def preferences ()
def searchPaths ()
def searchPathsPost ()
def searchPathsTool (sub)
def setDefaultStockTemplate (template)
def setDefaultTaskPanelLayout (style)
def setJobDefaults (fileName, jobTemplate, geometryTolerance, curveAccuracy)
def setLastFileToolLibrary (path)
def setLastPathToolBit (path)
def setLastPathToolLibrary (path)
def setLastPathToolShape (path)
def setLastPathToolTable (table)
def setOutputFileDefaults (fileName, policy)
def setPostProcessorDefaults (processor, args, blacklist)
def setPreferencesAdvanced (ocl, warnSpeeds, warnRapids, warnModes, warnOCL, warnVelocity)
def setToolsSettings (legacy, relative)
def suppressAllSpeedsWarning ()
def suppressOpenCamLibWarning ()
def suppressRapidSpeedsWarning (user=True)
def suppressSelectionModeWarning ()
def suppressVelocity ()
def toolsStoreAbsolutePaths ()
def toolsUseLegacyTools ()
Variables
string DefaultFilePath = "DefaultFilePath"
string DefaultJobTemplate = "DefaultJobTemplate"
string DefaultStockTemplate = "DefaultStockTemplate"
string DefaultTaskPanelLayout = "DefaultTaskPanelLayout"
string EnableAdvancedOCLFeatures = "EnableAdvancedOCLFeatures"
string EnableExperimentalFeatures = "EnableExperimentalFeatures"
string GeometryTolerance = "GeometryTolerance"
string LastFileToolBit = "LastFileToolBit"
string LastFileToolLibrary = "LastFileToolLibrary"
string LastFileToolShape = "LastFileToolShape"
string LastPathToolBit = "LastPathToolBit"
string LastPathToolLibrary = "LastPathToolLibrary"
string LastPathToolShape = "LastPathToolShape"
string LastPathToolTable = "LastPathToolTable"
string LibAreaCurveAccuracy = "LibAreaCurveAccuracy"
string PostProcessorBlacklist = "PostProcessorBlacklist"
string PostProcessorDefault = "PostProcessorDefault"
string PostProcessorDefaultArgs = "PostProcessorDefaultArgs"
string PostProcessorOutputFile = "PostProcessorOutputFile"
string PostProcessorOutputPolicy = "PostProcessorOutputPolicy"
translate = FreeCAD.Qt.translate
string UseAbsoluteToolPaths = "UseAbsoluteToolPaths"
string UseLegacyTools = "UseLegacyTools"
string WarningSuppressAllSpeeds = "WarningSuppressAllSpeeds"
string WarningSuppressOpenCamLib = "WarningSuppressOpenCamLib"
string WarningSuppressRapidSpeeds = "WarningSuppressRapidSpeeds"
string WarningSuppressSelectionMode = "WarningSuppressSelectionMode"
string WarningSuppressVelocity = "WarningSuppressVelocity"
Function Documentation
advancedOCLFeaturesEnabled()
def PathScripts.PathPreferences.advancedOCLFeaturesEnabled ()
References PathScripts.PathPreferences.preferences().
allAvailablePostProcessors()
def PathScripts.PathPreferences.allAvailablePostProcessors ()
References PathScripts.PathPreferences.searchPathsPost().
Referenced by PathScripts.PathPreferences.allEnabledPostProcessors().
allEnabledPostProcessors()
def PathScripts.PathPreferences.allEnabledPostProcessors (include = None)
References PathScripts.PathPreferences.allAvailablePostProcessors(), and PathScripts.PathPreferences.postProcessorBlacklist().
defaultFilePath()
def PathScripts.PathPreferences.defaultFilePath ()
References PathScripts.PathPreferences.preferences().
Referenced by PathScripts.PathPreferences.filePath(), PathScripts.PathPreferences.searchPaths(), and PathScripts.PathPreferences.searchPathsPost().
defaultGeometryTolerance()
def PathScripts.PathPreferences.defaultGeometryTolerance ()
References PathScripts.PathPreferences.preferences().
defaultJobTemplate()
def PathScripts.PathPreferences.defaultJobTemplate ()
References PathScripts.PathPreferences.preferences().
defaultLibAreaCurveAccuracy()
def PathScripts.PathPreferences.defaultLibAreaCurveAccuracy ()
References PathScripts.PathPreferences.preferences().
defaultOutputFile()
def PathScripts.PathPreferences.defaultOutputFile ()
References PathScripts.PathPreferences.preferences().
defaultOutputPolicy()
def PathScripts.PathPreferences.defaultOutputPolicy ()
References PathScripts.PathPreferences.preferences().
defaultPostProcessor()
def PathScripts.PathPreferences.defaultPostProcessor ()
References PathScripts.PathPreferences.preferences().
defaultPostProcessorArgs()
def PathScripts.PathPreferences.defaultPostProcessorArgs ()
References PathScripts.PathPreferences.preferences().
defaultStockTemplate()
def PathScripts.PathPreferences.defaultStockTemplate ()
References PathScripts.PathPreferences.preferences().
defaultTaskPanelLayout()
def PathScripts.PathPreferences.defaultTaskPanelLayout ()
References PathScripts.PathPreferences.preferences().
experimentalFeaturesEnabled()
def PathScripts.PathPreferences.experimentalFeaturesEnabled ()
References PathScripts.PathPreferences.preferences().
filePath()
def PathScripts.PathPreferences.filePath ()
References PathScripts.PathPreferences.defaultFilePath(), and PathScripts.PathPreferences.macroFilePath().
lastFileToolLibrary()
def PathScripts.PathPreferences.lastFileToolLibrary ()
References PathScripts.PathPreferences.pathDefaultToolsPath(), PathScripts.PathPreferences.preferences(), and PathScripts.PathPreferences.setLastFileToolLibrary().
Referenced by PathScripts.PathPreferences.setLastPathToolLibrary().
lastPathToolBit()
def PathScripts.PathPreferences.lastPathToolBit ()
References PathScripts.PathPreferences.pathDefaultToolsPath(), and PathScripts.PathPreferences.preferences().
Referenced by PathScripts.PathToolBitCmd.CommandToolBitSave.Activated().
lastPathToolLibrary()
def PathScripts.PathPreferences.lastPathToolLibrary ()
References PathScripts.PathPreferences.pathDefaultToolsPath(), and PathScripts.PathPreferences.preferences().
lastPathToolShape()
def PathScripts.PathPreferences.lastPathToolShape ()
References PathScripts.PathPreferences.pathDefaultToolsPath(), and PathScripts.PathPreferences.preferences().
lastPathToolTable()
def PathScripts.PathPreferences.lastPathToolTable ()
References PathScripts.PathPreferences.preferences().
macroFilePath()
def PathScripts.PathPreferences.macroFilePath ()
Referenced by PathScripts.PathPreferences.filePath(), PathScripts.PathPreferences.searchPaths(), and PathScripts.PathPreferences.searchPathsPost().
pathDefaultToolsPath()
def PathScripts.PathPreferences.pathDefaultToolsPath (sub = None)
Referenced by PathScripts.PathPreferences.lastFileToolLibrary(), PathScripts.PathPreferences.lastPathToolBit(), PathScripts.PathPreferences.lastPathToolLibrary(), and PathScripts.PathPreferences.lastPathToolShape().
pathScriptsSourcePath()
def PathScripts.PathPreferences.pathScriptsSourcePath ()
Referenced by PathScripts.PathPreferences.searchPathsPost().
postProcessorBlacklist()
def PathScripts.PathPreferences.postProcessorBlacklist ()
References PathScripts.PathPreferences.preferences().
Referenced by PathScripts.PathPreferences.allEnabledPostProcessors().
preferences()
def PathScripts.PathPreferences.preferences ()
Referenced by PathScripts.PathPreferences.advancedOCLFeaturesEnabled(), PathScripts.PathPreferences.defaultFilePath(), PathScripts.PathPreferences.defaultGeometryTolerance(), PathScripts.PathPreferences.defaultJobTemplate(), PathScripts.PathPreferences.defaultLibAreaCurveAccuracy(), PathScripts.PathPreferences.defaultOutputFile(), PathScripts.PathPreferences.defaultOutputPolicy(), PathScripts.PathPreferences.defaultPostProcessor(), PathScripts.PathPreferences.defaultPostProcessorArgs(), PathScripts.PathPreferences.defaultStockTemplate(), PathScripts.PathPreferences.defaultTaskPanelLayout(), PathScripts.PathPreferences.experimentalFeaturesEnabled(), PathScripts.PathPreferences.lastFileToolLibrary(), PathScripts.PathPreferences.lastPathToolBit(), PathScripts.PathPreferences.lastPathToolLibrary(), PathScripts.PathPreferences.lastPathToolShape(), PathScripts.PathPreferences.lastPathToolTable(), PathScripts.PathPreferences.postProcessorBlacklist(), PathScripts.PathPreferences.setDefaultStockTemplate(), PathScripts.PathPreferences.setDefaultTaskPanelLayout(), PathScripts.PathPreferences.setJobDefaults(), PathScripts.PathPreferences.setLastFileToolLibrary(), PathScripts.PathPreferences.setLastPathToolBit(), PathScripts.PathPreferences.setLastPathToolLibrary(), PathScripts.PathPreferences.setLastPathToolShape(), PathScripts.PathPreferences.setLastPathToolTable(), PathScripts.PathPreferences.setOutputFileDefaults(), PathScripts.PathPreferences.setPostProcessorDefaults(), PathScripts.PathPreferences.setPreferencesAdvanced(), PathScripts.PathPreferences.setToolsSettings(), PathScripts.PathPreferences.suppressAllSpeedsWarning(), PathScripts.PathPreferences.suppressOpenCamLibWarning(), PathScripts.PathPreferences.suppressRapidSpeedsWarning(), PathScripts.PathPreferences.suppressSelectionModeWarning(), PathScripts.PathPreferences.suppressVelocity(), PathScripts.PathPreferences.toolsStoreAbsolutePaths(), and PathScripts.PathPreferences.toolsUseLegacyTools().
searchPaths()
def PathScripts.PathPreferences.searchPaths ()
References PathScripts.PathPreferences.defaultFilePath(), and PathScripts.PathPreferences.macroFilePath().
searchPathsPost()
def PathScripts.PathPreferences.searchPathsPost ()
References PathScripts.PathPreferences.defaultFilePath(), PathScripts.PathPreferences.macroFilePath(), and PathScripts.PathPreferences.pathScriptsSourcePath().
Referenced by PathScripts.PathPreferences.allAvailablePostProcessors().
searchPathsTool()
def PathScripts.PathPreferences.searchPathsTool (sub)
setDefaultStockTemplate()
def PathScripts.PathPreferences.setDefaultStockTemplate (template)
References PathScripts.PathPreferences.preferences().
setDefaultTaskPanelLayout()
def PathScripts.PathPreferences.setDefaultTaskPanelLayout (style)
References PathScripts.PathPreferences.preferences().
setJobDefaults()
def PathScripts.PathPreferences.setJobDefaults (fileName, jobTemplate, geometryTolerance, curveAccuracy)
References PathScripts.PathPreferences.preferences().
setLastFileToolLibrary()
def PathScripts.PathPreferences.setLastFileToolLibrary (path)
References PathScripts.PathPreferences.preferences().
Referenced by PathScripts.PathPreferences.lastFileToolLibrary(), and PathScripts.PathPreferences.setLastPathToolLibrary().
setLastPathToolBit()
def PathScripts.PathPreferences.setLastPathToolBit (path)
References PathScripts.PathPreferences.preferences().
Referenced by PathScripts.PathToolBitCmd.CommandToolBitSave.Activated().
setLastPathToolLibrary()
def PathScripts.PathPreferences.setLastPathToolLibrary (path)
References PathScripts.PathPreferences.lastFileToolLibrary(), PathScripts.PathPreferences.preferences(), and PathScripts.PathPreferences.setLastFileToolLibrary().
setLastPathToolShape()
def PathScripts.PathPreferences.setLastPathToolShape (path)
References PathScripts.PathPreferences.preferences().
setLastPathToolTable()
def PathScripts.PathPreferences.setLastPathToolTable (table)
References PathScripts.PathPreferences.preferences().
setOutputFileDefaults()
def PathScripts.PathPreferences.setOutputFileDefaults (fileName, policy)
References PathScripts.PathPreferences.preferences().
setPostProcessorDefaults()
def PathScripts.PathPreferences.setPostProcessorDefaults (processor, args, blacklist)
References PathScripts.PathPreferences.preferences().
setPreferencesAdvanced()
def PathScripts.PathPreferences.setPreferencesAdvanced (ocl, warnSpeeds, warnRapids, warnModes, warnOCL, warnVelocity)
References PathScripts.PathPreferences.preferences().
setToolsSettings()
def PathScripts.PathPreferences.setToolsSettings (legacy, relative)
References PathScripts.PathPreferences.preferences().
suppressAllSpeedsWarning()
def PathScripts.PathPreferences.suppressAllSpeedsWarning ()
References PathScripts.PathPreferences.preferences().
Referenced by PathScripts.PathPreferences.suppressRapidSpeedsWarning().
suppressOpenCamLibWarning()
def PathScripts.PathPreferences.suppressOpenCamLibWarning ()
References PathScripts.PathPreferences.preferences().
suppressRapidSpeedsWarning()
def PathScripts.PathPreferences.suppressRapidSpeedsWarning (user = True)
References PathScripts.PathPreferences.preferences(), and PathScripts.PathPreferences.suppressAllSpeedsWarning().
suppressSelectionModeWarning()
def PathScripts.PathPreferences.suppressSelectionModeWarning ()
References PathScripts.PathPreferences.preferences().
suppressVelocity()
def PathScripts.PathPreferences.suppressVelocity ()
References PathScripts.PathPreferences.preferences().
toolsStoreAbsolutePaths()
def PathScripts.PathPreferences.toolsStoreAbsolutePaths ()
References PathScripts.PathPreferences.preferences().
toolsUseLegacyTools()
def PathScripts.PathPreferences.toolsUseLegacyTools ()
References PathScripts.PathPreferences.preferences().
Variable Documentation
DefaultFilePath
string PathScripts.PathPreferences.DefaultFilePath = "DefaultFilePath"
DefaultJobTemplate
string PathScripts.PathPreferences.DefaultJobTemplate = "DefaultJobTemplate"
DefaultStockTemplate
string PathScripts.PathPreferences.DefaultStockTemplate = "DefaultStockTemplate"
DefaultTaskPanelLayout
string PathScripts.PathPreferences.DefaultTaskPanelLayout = "DefaultTaskPanelLayout"
EnableAdvancedOCLFeatures
string PathScripts.PathPreferences.EnableAdvancedOCLFeatures = "EnableAdvancedOCLFeatures"
EnableExperimentalFeatures
string PathScripts.PathPreferences.EnableExperimentalFeatures = "EnableExperimentalFeatures"
GeometryTolerance
string PathScripts.PathPreferences.GeometryTolerance = "GeometryTolerance"
LastFileToolBit
string PathScripts.PathPreferences.LastFileToolBit = "LastFileToolBit"
LastFileToolLibrary
string PathScripts.PathPreferences.LastFileToolLibrary = "LastFileToolLibrary"
LastFileToolShape
string PathScripts.PathPreferences.LastFileToolShape = "LastFileToolShape"
LastPathToolBit
string PathScripts.PathPreferences.LastPathToolBit = "LastPathToolBit"
LastPathToolLibrary
string PathScripts.PathPreferences.LastPathToolLibrary = "LastPathToolLibrary"
LastPathToolShape
string PathScripts.PathPreferences.LastPathToolShape = "LastPathToolShape"
LastPathToolTable
string PathScripts.PathPreferences.LastPathToolTable = "LastPathToolTable"
LibAreaCurveAccuracy
string PathScripts.PathPreferences.LibAreaCurveAccuracy = "LibAreaCurveAccuracy"
PostProcessorBlacklist
string PathScripts.PathPreferences.PostProcessorBlacklist = "PostProcessorBlacklist"
PostProcessorDefault
string PathScripts.PathPreferences.PostProcessorDefault = "PostProcessorDefault"
PostProcessorDefaultArgs
string PathScripts.PathPreferences.PostProcessorDefaultArgs = "PostProcessorDefaultArgs"
PostProcessorOutputFile
string PathScripts.PathPreferences.PostProcessorOutputFile = "PostProcessorOutputFile"
PostProcessorOutputPolicy
string PathScripts.PathPreferences.PostProcessorOutputPolicy = "PostProcessorOutputPolicy"
translate
PathScripts.PathPreferences.translate = FreeCAD.Qt.translate
UseAbsoluteToolPaths
string PathScripts.PathPreferences.UseAbsoluteToolPaths = "UseAbsoluteToolPaths"
UseLegacyTools
string PathScripts.PathPreferences.UseLegacyTools = "UseLegacyTools"
WarningSuppressAllSpeeds
string PathScripts.PathPreferences.WarningSuppressAllSpeeds = "WarningSuppressAllSpeeds"
WarningSuppressOpenCamLib
string PathScripts.PathPreferences.WarningSuppressOpenCamLib = "WarningSuppressOpenCamLib"
WarningSuppressRapidSpeeds
string PathScripts.PathPreferences.WarningSuppressRapidSpeeds = "WarningSuppressRapidSpeeds"
WarningSuppressSelectionMode
string PathScripts.PathPreferences.WarningSuppressSelectionMode = "WarningSuppressSelectionMode"
WarningSuppressVelocity
string PathScripts.PathPreferences.WarningSuppressVelocity = "WarningSuppressVelocity"