FreeCAD: MeshCore::MeshKDTree Class Reference
MeshCore::MeshKDTree Class Reference
#include <KDTree.h>
Classes
class Private
Public Member Functions
void AddPoint (Base::Vector3f &point)
void AddPoints (const MeshPointArray &points)
void AddPoints (const std::vector< Base::Vector3f > &points)
void Clear ()
PointIndex FindExact (const Base::Vector3f &p) const
void FindInRange (const Base::Vector3f &, float, std::vector< PointIndex > &) const
PointIndex FindNearest (const Base::Vector3f &p, Base::Vector3f &n, float &) const
PointIndex FindNearest (const Base::Vector3f &p, float max_dist, Base::Vector3f &n, float &) const
bool IsEmpty () const
MeshKDTree ()
MeshKDTree (const MeshPointArray &points)
MeshKDTree (const std::vector< Base::Vector3f > &points)
void Optimize ()
~MeshKDTree ()
Constructor & Destructor Documentation
MeshKDTree() [1/3]
MeshKDTree::MeshKDTree ()
MeshKDTree() [2/3]
MeshKDTree::MeshKDTree (const std::vector< Base::Vector3f > & points)
References KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::insert(), and MeshCore::MeshKDTree::Private::kd_tree.
MeshKDTree() [3/3]
MeshKDTree::MeshKDTree (const MeshPointArray & points)
References KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::insert(), and MeshCore::MeshKDTree::Private::kd_tree.
~MeshKDTree()
MeshKDTree::~MeshKDTree ()
Member Function Documentation
AddPoint()
void MeshKDTree::AddPoint (Base::Vector3f & point)
References KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::insert(), MeshCore::MeshKDTree::Private::kd_tree, and KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::size().
AddPoints() [1/2]
void MeshKDTree::AddPoints (const MeshPointArray & points)
References KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::insert(), MeshCore::MeshKDTree::Private::kd_tree, and KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::size().
AddPoints() [2/2]
void MeshKDTree::AddPoints (const std::vector< Base::Vector3f > & points)
References KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::insert(), MeshCore::MeshKDTree::Private::kd_tree, and KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::size().
Clear()
void MeshKDTree::Clear (void)
References KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::clear(), and MeshCore::MeshKDTree::Private::kd_tree.
FindExact()
PointIndex MeshKDTree::FindExact (const Base::Vector3f & p) const
References KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::end(), KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::find_exact(), MeshCore::MeshKDTree::Private::kd_tree, and MeshCore::POINT_INDEX_MAX.
FindInRange()
void MeshKDTree::FindInRange (const Base::Vector3f & p, float range, std::vector< PointIndex > & indices) const
References KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::find_within_range(), and MeshCore::MeshKDTree::Private::kd_tree.
FindNearest() [1/2]
PointIndex MeshKDTree::FindNearest (const Base::Vector3f & p, Base::Vector3f & n, float & dist) const
References DraftVecUtils::dist(), KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::end(), KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::find_nearest(), MeshCore::MeshKDTree::Private::kd_tree, and MeshCore::POINT_INDEX_MAX.
FindNearest() [2/2]
PointIndex MeshKDTree::FindNearest (const Base::Vector3f & p, float max_dist, Base::Vector3f & n, float & dist) const
References DraftVecUtils::dist(), KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::end(), KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::find_nearest(), MeshCore::MeshKDTree::Private::kd_tree, and MeshCore::POINT_INDEX_MAX.
IsEmpty()
bool MeshKDTree::IsEmpty () const
References KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::empty(), and MeshCore::MeshKDTree::Private::kd_tree.
Optimize()
void MeshKDTree::Optimize ()
References MeshCore::MeshKDTree::Private::kd_tree, and KDTree::KDTree< __K, _Val, _Acc, _Dist, _Cmp, _Alloc >::optimize().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/Core/KDTree.h
FreeCAD/src/Mod/Mesh/App/Core/KDTree.cpp