FreeCAD: Points::PointsPy Class Reference
Points::PointsPy Class Reference
The python export class for PointKernel.
#include <PointsPy.h>
Public Types
typedef PointKernel * PointerType
Public Types inherited from Data::ComplexGeoDataPy
typedef ComplexGeoData * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
PointsPy (PointKernel *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Data::ComplexGeoDataPy
ComplexGeoDataPy (ComplexGeoData *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getFacesFromSubelement (PyObject *args)
implementer for the getFacesFromSubelement() method
Py::Object getBoundBox (void) const
getter for the BoundBox attribute
Py::Object getPlacement (void) const
getter for the Placement attribute
void setPlacement (Py::Object arg)
setter for the Placement attribute
Py::Object getMatrix (void) const
getter for the Matrix attribute
void setMatrix (Py::Object arg)
setter for the Matrix attribute
Py::Int getTag (void) const
getter for the Tag attribute
void setTag (Py::Int arg)
setter for the Tag attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ComplexGeoData * getComplexGeoDataPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Data::ComplexGeoDataPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_getFacesFromSubelement (PyObject *self, PyObject *args)
callback for the getFacesFromSubelement() method
static PyObject * staticCallback_getBoundBox (PyObject *self, void *closure)
getter callback for the BoundBox attribute
static int staticCallback_setBoundBox (PyObject *self, PyObject *value, void *closure)
setter callback for the BoundBox attribute
static PyObject * staticCallback_getPlacement (PyObject *self, void *closure)
getter callback for the Placement attribute
static int staticCallback_setPlacement (PyObject *self, PyObject *value, void *closure)
setter callback for the Placement attribute
static PyObject * staticCallback_getMatrix (PyObject *self, void *closure)
getter callback for the Matrix attribute
static int staticCallback_setMatrix (PyObject *self, PyObject *value, void *closure)
setter callback for the Matrix attribute
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of PointsPy.
static PyMethodDef Methods []
Methods structure of PointsPy.
static PyTypeObject Type
Type structure of PointsPy.
Static Public Attributes inherited from Data::ComplexGeoDataPy
static PyGetSetDef GetterSetter []
Attribute structure of ComplexGeoDataPy.
static PyMethodDef Methods []
Methods structure of ComplexGeoDataPy.
static PyTypeObject Type
Type structure of ComplexGeoDataPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~PointsPy ()
Protected Member Functions inherited from Data::ComplexGeoDataPy
~ComplexGeoDataPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * read (PyObject *args)
implementer for the read() method
PyObject * write (PyObject *args)
implementer for the write() method
PyObject * writeInventor (PyObject *args)
implementer for the writeInventor() method
PyObject * addPoints (PyObject *args)
implementer for the addPoints() method
PyObject * fromSegment (PyObject *args)
implementer for the fromSegment() method
PyObject * fromValid (PyObject *args)
implementer for the fromValid() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_read (PyObject *self, PyObject *args)
callback for the read() method
static PyObject * staticCallback_write (PyObject *self, PyObject *args)
callback for the write() method
static PyObject * staticCallback_writeInventor (PyObject *self, PyObject *args)
callback for the writeInventor() method
static PyObject * staticCallback_addPoints (PyObject *self, PyObject *args)
callback for the addPoints() method
static PyObject * staticCallback_fromSegment (PyObject *self, PyObject *args)
callback for the fromSegment() method
static PyObject * staticCallback_fromValid (PyObject *self, PyObject *args)
callback for the fromValid() method
callbacks and implementers for the python object attributes
Py::Long getCountPoints (void) const
getter for the CountPoints attribute
Py::List getPoints (void) const
getter for the Points attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
PointKernel * getPointKernelPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getCountPoints (PyObject *self, void *closure)
getter callback for the CountPoints attribute
static int staticCallback_setCountPoints (PyObject *self, PyObject *value, void *closure)
setter callback for the CountPoints attribute
static PyObject * staticCallback_getPoints (PyObject *self, void *closure)
getter callback for the Points attribute
static int staticCallback_setPoints (PyObject *self, PyObject *value, void *closure)
setter callback for the Points attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for PointKernel.
Member Typedef Documentation
PointerType
typedef PointKernel* Points::PointsPy::PointerType
Constructor & Destructor Documentation
~PointsPy()
PointsPy::~PointsPy () protected
PointsPy()
PointsPy::PointsPy (PointKernel * pcObject, PyTypeObject * T = &Type)
Referenced by copy(), fromSegment(), fromValid(), and PyMake().
Member Function Documentation
addPoints()
PyObject * PointsPy::addPoints (PyObject * args)
implementer for the addPoints() method
References Base::BaseExceptionFreeCADError, getPointKernelPtr(), PyType_Object::o, Points::PointKernel::push_back(), Base::VectorPy::Type, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by PyInit(), and staticCallback_addPoints().
copy()
PyObject * PointsPy::copy (PyObject * args)
implementer for the copy() method
References getPointKernelPtr(), and PointsPy().
Referenced by staticCallback_copy().
fromSegment()
PyObject * PointsPy::fromSegment (PyObject * args)
implementer for the fromSegment() method
References Base::BaseExceptionFreeCADError, getPointKernelPtr(), and PointsPy().
Referenced by staticCallback_fromSegment().
fromValid()
PyObject * PointsPy::fromValid (PyObject * args)
implementer for the fromValid() method
References Base::BaseExceptionFreeCADError, getPointKernelPtr(), and PointsPy().
Referenced by staticCallback_fromValid().
getCountPoints()
Py::Long PointsPy::getCountPoints (void) const
getter for the CountPoints attribute
References getPointKernelPtr().
Referenced by staticCallback_getCountPoints().
getCustomAttributes()
PyObject * PointsPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getPointKernelPtr()
PointKernel * PointsPy::getPointKernelPtr (void) const
getter for the object handled by this class
Referenced by addPoints(), copy(), fromSegment(), fromValid(), getCountPoints(), getPoints(), PyInit(), read(), Points::PropertyPointKernel::setPyObject(), write(), and writeInventor().
getPoints()
Py::List PointsPy::getPoints (void) const
getter for the Points attribute
References getPointKernelPtr().
Referenced by staticCallback_getPoints().
GetType()
virtual PyTypeObject* Points::PointsPy::GetType (void) virtual
Reimplemented from Data::ComplexGeoDataPy.
PyInit()
int PointsPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Data::ComplexGeoDataPy.
References addPoints(), getPointKernelPtr(), Points::PointKernel::load(), and Type.
PyMake()
PyObject * PointsPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References PointsPy().
read()
PyObject * PointsPy::read (PyObject * args)
implementer for the read() method
References getPointKernelPtr(), and Points::PointKernel::load().
Referenced by gzip_utf8.GzipFile::readline(), gzip_utf8.GzipFile::seek(), and staticCallback_read().
representation()
std::string PointsPy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int PointsPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_addPoints()
PyObject * PointsPy::staticCallback_addPoints (PyObject * self, PyObject * args) static
callback for the addPoints() method
References addPoints(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_copy()
PyObject * PointsPy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copy(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_fromSegment()
PyObject * PointsPy::staticCallback_fromSegment (PyObject * self, PyObject * args) static
callback for the fromSegment() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, fromSegment(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_fromValid()
PyObject * PointsPy::staticCallback_fromValid (PyObject * self, PyObject * args) static
callback for the fromValid() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, fromValid(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCountPoints()
PyObject * PointsPy::staticCallback_getCountPoints (PyObject * self, void * closure) static
getter callback for the CountPoints attribute
References Base::BaseExceptionFreeCADError, getCountPoints(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPoints()
PyObject * PointsPy::staticCallback_getPoints (PyObject * self, void * closure) static
getter callback for the Points attribute
References Base::BaseExceptionFreeCADError, getPoints(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_read()
PyObject * PointsPy::staticCallback_read (PyObject * self, PyObject * args) static
callback for the read() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), read(), and Base::PyObjectBase::startNotify().
staticCallback_setCountPoints()
int PointsPy::staticCallback_setCountPoints (PyObject * self, PyObject * value, void * closure) static
setter callback for the CountPoints attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPoints()
int PointsPy::staticCallback_setPoints (PyObject * self, PyObject * value, void * closure) static
setter callback for the Points attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_write()
PyObject * PointsPy::staticCallback_write (PyObject * self, PyObject * args) static
callback for the write() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and write().
staticCallback_writeInventor()
PyObject * PointsPy::staticCallback_writeInventor (PyObject * self, PyObject * args) static
callback for the writeInventor() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and writeInventor().
write()
PyObject * PointsPy::write (PyObject * args)
implementer for the write() method
References getPointKernelPtr(), and Points::PointKernel::save().
Referenced by gzip_utf8.GzipFile::seek(), and staticCallback_write().
writeInventor()
PyObject * PointsPy::writeInventor (PyObject * args)
implementer for the writeInventor() method
References Base::InventorBuilder::addPoint(), Base::InventorBuilder::addPointSet(), Points::PointKernel::begin(), Base::InventorBuilder::beginPoints(), Base::InventorBuilder::close(), Points::PointKernel::end(), Base::InventorBuilder::endPoints(), and getPointKernelPtr().
Referenced by ArchBuildingPart.ViewProviderBuildingPart::onChanged(), staticCallback_writeInventor(), and ArchBuildingPart.ViewProviderBuildingPart::updateData().
Member Data Documentation
GetterSetter
PyGetSetDef PointsPy::GetterSetter static
Initial value:
= {
    {"CountPoints",
        (getter) staticCallback_getCountPoints,
        (setter) staticCallback_setCountPoints,
        "Return the number of vertices of the points object.",
        NULL
    },
    {"Points",
        (getter) staticCallback_getPoints,
        (setter) staticCallback_setPoints,
        "A collection of points\nWith this attribute it is possible to get access to the points of the object\n\nfor p in pnt.Points:\n print p\n\n                             ",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of PointsPy.
Methods
PyMethodDef PointsPy::Methods static
Methods structure of PointsPy.
Type
PyTypeObject PointsPy::Type static
Type structure of PointsPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), PyInit(), draftobjects.layer.Layer::set_properties(), ArchReference.ArchReference::setProperties(), and Points::PropertyPointKernel::setPyObject().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Points/App/PointsPy.h
Sources/FreeCAD/src/Mod/Points/App/PointsPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Points/App/PointsPy.cpp