FreeCAD: SketcherGui::Ui_SketchOrientationDialog Class Reference
SketcherGui::Ui_SketchOrientationDialog Class Reference
#include <ui_SketchOrientationDialog.h>
Public Member Functions
void retranslateUi (QDialog *SketcherGui__SketchOrientationDialog)
void setupUi (QDialog *SketcherGui__SketchOrientationDialog)
Public Attributes
QDialogButtonBox * buttonBox
QGridLayout * gridLayout
QGroupBox * groupBox
QHBoxLayout * horizontalLayout
QLabel * label
Gui::QuantitySpinBox * Offset_doubleSpinBox
QLabel * previewLabel
QCheckBox * Reverse_checkBox
QVBoxLayout * verticalLayout
QRadioButton * XY_radioButton
QRadioButton * XZ_radioButton
QRadioButton * YZ_radioButton
Member Function Documentation
retranslateUi()
void SketcherGui::Ui_SketchOrientationDialog::retranslateUi (QDialog * SketcherGui__SketchOrientationDialog)
References groupBox, Reverse_checkBox, draftguitools.gui_setstyle::translate, XY_radioButton, XZ_radioButton, and YZ_radioButton.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void SketcherGui::Ui_SketchOrientationDialog::setupUi (QDialog * SketcherGui__SketchOrientationDialog)
References buttonBox, draftgeoutils.intersections::connect(), gridLayout, groupBox, horizontalLayout, Offset_doubleSpinBox, previewLabel, retranslateUi(), Reverse_checkBox, Gui::QuantitySpinBox::setMaximum(), Gui::QuantitySpinBox::setMinimum(), Gui::QuantitySpinBox::setSingleStep(), verticalLayout, XY_radioButton, XZ_radioButton, and YZ_radioButton.
Member Data Documentation
buttonBox
QDialogButtonBox* SketcherGui::Ui_SketchOrientationDialog::buttonBox
Referenced by PathScripts.PathGetPoint.TaskPanel::getPoint(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::modifyStandardButtons(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::pageDirtyChanged(), PathScripts.PathGetPoint.TaskPanel::pointFinish(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setClean(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setDirty(), and setupUi().
gridLayout
QGridLayout* SketcherGui::Ui_SketchOrientationDialog::gridLayout
Referenced by setupUi().
groupBox
QGroupBox* SketcherGui::Ui_SketchOrientationDialog::groupBox
Referenced by retranslateUi(), and setupUi().
horizontalLayout
QHBoxLayout* SketcherGui::Ui_SketchOrientationDialog::horizontalLayout
Referenced by setupUi().
label
QLabel* SketcherGui::Ui_SketchOrientationDialog::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
Offset_doubleSpinBox
Gui::QuantitySpinBox* SketcherGui::Ui_SketchOrientationDialog::Offset_doubleSpinBox
Referenced by setupUi().
previewLabel
QLabel* SketcherGui::Ui_SketchOrientationDialog::previewLabel
Referenced by setupUi().
Reverse_checkBox
QCheckBox* SketcherGui::Ui_SketchOrientationDialog::Reverse_checkBox
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* SketcherGui::Ui_SketchOrientationDialog::verticalLayout
Referenced by setupUi().
XY_radioButton
QRadioButton* SketcherGui::Ui_SketchOrientationDialog::XY_radioButton
Referenced by retranslateUi(), and setupUi().
XZ_radioButton
QRadioButton* SketcherGui::Ui_SketchOrientationDialog::XZ_radioButton
Referenced by retranslateUi(), and setupUi().
YZ_radioButton
QRadioButton* SketcherGui::Ui_SketchOrientationDialog::YZ_radioButton
Referenced by retranslateUi(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/ui_SketchOrientationDialog.h