FreeCAD: Gui::DocumentObserverPython Class Reference
Gui::DocumentObserverPython Class Reference
The DocumentObserverPython class is used to notify registered Python instances whenever something happens to a document, like creation, destruction, adding or removing viewproviders or when viewprovider property changes.
#include <DocumentObserverPython.h>
Public Member Functions
DocumentObserverPython (const Py::Object &obj)
Constructor.
virtual ~DocumentObserverPython ()
Static Public Member Functions
static void addObserver (const Py::Object &obj)
static void removeObserver (const Py::Object &obj)
Detailed Description
The DocumentObserverPython class is used to notify registered Python instances whenever something happens to a document, like creation, destruction, adding or removing viewproviders or when viewprovider property changes.
This is the equivalent to the app python document observer
Constructor & Destructor Documentation
DocumentObserverPython()
DocumentObserverPython::DocumentObserverPython (const Py::Object & obj)
Constructor.
Referenced by addObserver().
~DocumentObserverPython()
DocumentObserverPython::~DocumentObserverPython () virtual
Member Function Documentation
addObserver()
void DocumentObserverPython::addObserver (const Py::Object & obj) static
References DocumentObserverPython().
Referenced by Gui::Application::sAddDocObserver().
removeObserver()
void DocumentObserverPython::removeObserver (const Py::Object & obj) static
Referenced by Gui::Application::sRemoveDocObserver().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DocumentObserverPython.h
Sources/FreeCAD/src/Gui/DocumentObserverPython.cpp