FreeCAD: UNV2411 Namespace Reference
UNV2411 Namespace Reference
Classes
struct TRecord
Typedefs
typedef std::vector< TRecord > TDataSet
typedef int TNodeLab
Functions
MESHDRIVERUNV_EXPORT void Read (std::ifstream &in_stream, TDataSet &theDataSet)
MESHDRIVERUNV_EXPORT void Write (std::ofstream &out_stream, const TDataSet &theDataSet)
Typedef Documentation
TDataSet
typedef std::vector<TRecord> UNV2411::TDataSet
TNodeLab
typedef int UNV2411::TNodeLab
Function Documentation
Read()
void UNV2411::Read (std::ifstream & in_stream, TDataSet & theDataSet)
always 3 coordinates in the UNV file, no matter which dimensionality libMesh is in
References UNV::beginning_of_dataset(), UNV2411::TRecord::color, UNV2411::TRecord::coord, UNV::D_to_e(), UNV2411::TRecord::disp_coord_sys_num, UNV2411::TRecord::exp_coord_sys_num, UNV2411::TRecord::label, and UNV::read_line().
Referenced by DriverUNV_R_SMDS_Mesh::Perform().
Write()
void UNV2411::Write (std::ofstream & out_stream, const TDataSet & theDataSet)
References UNV2411::TRecord::color, UNV2411::TRecord::coord, UNV2411::TRecord::disp_coord_sys_num, UNV2411::TRecord::exp_coord_sys_num, and UNV2411::TRecord::label.
Referenced by DriverUNV_W_SMDS_Mesh::Perform().