FreeCAD: SMESH_HypoFilter::IsMoreLocalThanPredicate Struct Reference
SMESH_HypoFilter::IsMoreLocalThanPredicate Struct Reference
#include <SMESH_HypoFilter.hxx>
Public Member Functions
void findPreferable ()
Finds shapes preferable over _shape due to sub-mesh order.
IsMoreLocalThanPredicate (const TopoDS_Shape &shape, const SMESH_Mesh &mesh)
bool IsOk (const SMESH_Hypothesis *aHyp, const TopoDS_Shape &aShape) const
Public Member Functions inherited from SMESH_HypoPredicate
virtual bool IsOk (const SMESH_Hypothesis *aHyp, const TopoDS_Shape &aShape) const =0
virtual ~SMESH_HypoPredicate ()
Constructor & Destructor Documentation
IsMoreLocalThanPredicate()
SMESH_HypoFilter::IsMoreLocalThanPredicate::IsMoreLocalThanPredicate (const TopoDS_Shape & shape, const SMESH_Mesh & mesh)
Member Function Documentation
findPreferable()
void SMESH_HypoFilter::IsMoreLocalThanPredicate::findPreferable ()
Finds shapes preferable over _shape due to sub-mesh order.
References DraftVecUtils::find().
IsOk()
bool SMESH_HypoFilter::IsMoreLocalThanPredicate::IsOk (const SMESH_Hypothesis * aHyp, const TopoDS_Shape & aShape) const virtual
Implements SMESH_HypoPredicate.
References SMESH_Hypothesis::GetDim(), SMESH_Gen::GetShapeDim(), and SMESH_MesherHelper::IsSubShape().
The documentation for this struct was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_HypoFilter.hxx
FreeCAD/src/3rdParty/salomesmesh/src/SMESH/SMESH_HypoFilter.cpp