FreeCAD: Gui::AbstractSplitViewPy Class Reference
Gui::AbstractSplitViewPy Class Reference
#include <SplitView3DInventor.h>
Public Types
using BaseType = Py::PythonExtension< AbstractSplitViewPy >
Public Member Functions
AbstractSplitViewPy (AbstractSplitView *vi)
Py::Object cast_to_base (const Py::Tuple &)
Py::Object close (const Py::Tuple &)
Py::Object fitAll (const Py::Tuple &)
Py::Object getattr (const char *)
AbstractSplitView * getSplitViewPtr ()
Py::Object getViewer (const Py::Tuple &)
Py::Object repr ()
Py::Object sequence_item (Py_ssize_t)
int sequence_length ()
Py::Object viewBottom (const Py::Tuple &)
Py::Object viewFront (const Py::Tuple &)
Py::Object viewIsometric (const Py::Tuple &)
Py::Object viewLeft (const Py::Tuple &)
Py::Object viewRear (const Py::Tuple &)
Py::Object viewRight (const Py::Tuple &)
Py::Object viewTop (const Py::Tuple &)
~AbstractSplitViewPy ()
Static Public Member Functions
static void init_type ()
Member Typedef Documentation
BaseType
using Gui::AbstractSplitViewPy::BaseType = Py::PythonExtension<AbstractSplitViewPy>
Constructor & Destructor Documentation
AbstractSplitViewPy()
AbstractSplitViewPy::AbstractSplitViewPy (AbstractSplitView * vi)
~AbstractSplitViewPy()
AbstractSplitViewPy::~AbstractSplitViewPy ()
Member Function Documentation
cast_to_base()
Py::Object AbstractSplitViewPy::cast_to_base (const Py::Tuple &)
References Gui::MDIViewPy::create().
Referenced by init_type().
close()
Py::Object AbstractSplitViewPy::close (const Py::Tuple & args)
References getSplitViewPtr().
Referenced by init_type(), and femexamples.examplesgui.FemExamples::reject().
fitAll()
Py::Object AbstractSplitViewPy::fitAll (const Py::Tuple & args)
References getSplitViewPtr(), and Gui::AbstractSplitView::onMsg().
Referenced by init_type().
getattr()
Py::Object AbstractSplitViewPy::getattr (const char * attr)
References getSplitViewPtr().
getSplitViewPtr()
AbstractSplitView * AbstractSplitViewPy::getSplitViewPtr ()
Referenced by close(), fitAll(), getattr(), getViewer(), repr(), sequence_item(), sequence_length(), viewBottom(), viewFront(), viewIsometric(), viewLeft(), viewRear(), viewRight(), and viewTop().
getViewer()
Py::Object AbstractSplitViewPy::getViewer (const Py::Tuple & args)
References getSplitViewPtr(), and Gui::AbstractSplitView::getViewer().
Referenced by init_type().
init_type()
void AbstractSplitViewPy::init_type (void) static
References cast_to_base(), close(), fitAll(), getViewer(), viewBottom(), viewFront(), viewIsometric(), viewLeft(), viewRear(), viewRight(), and viewTop().
Referenced by Gui::Application::Application().
repr()
Py::Object AbstractSplitViewPy::repr ()
References getSplitViewPtr().
sequence_item()
Py::Object AbstractSplitViewPy::sequence_item (Py_ssize_t viewIndex)
References getSplitViewPtr(), and OfflineRenderingUtils::viewer().
sequence_length()
int AbstractSplitViewPy::sequence_length ()
References getSplitViewPtr().
viewBottom()
Py::Object AbstractSplitViewPy::viewBottom (const Py::Tuple & args)
References getSplitViewPtr(), and Gui::AbstractSplitView::onMsg().
Referenced by init_type().
viewFront()
Py::Object AbstractSplitViewPy::viewFront (const Py::Tuple & args)
References getSplitViewPtr(), and Gui::AbstractSplitView::onMsg().
Referenced by init_type().
viewIsometric()
Py::Object AbstractSplitViewPy::viewIsometric (const Py::Tuple & args)
References getSplitViewPtr(), and Gui::AbstractSplitView::onMsg().
Referenced by init_type().
viewLeft()
Py::Object AbstractSplitViewPy::viewLeft (const Py::Tuple & args)
References getSplitViewPtr(), and Gui::AbstractSplitView::onMsg().
Referenced by init_type().
viewRear()
Py::Object AbstractSplitViewPy::viewRear (const Py::Tuple & args)
References getSplitViewPtr(), and Gui::AbstractSplitView::onMsg().
Referenced by init_type().
viewRight()
Py::Object AbstractSplitViewPy::viewRight (const Py::Tuple & args)
References getSplitViewPtr(), and Gui::AbstractSplitView::onMsg().
Referenced by init_type().
viewTop()
Py::Object AbstractSplitViewPy::viewTop (const Py::Tuple & args)
References getSplitViewPtr(), and Gui::AbstractSplitView::onMsg().
Referenced by init_type().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/SplitView3DInventor.h
FreeCAD/src/Gui/SplitView3DInventor.cpp