FreeCAD: Sandbox::MeshLoaderThread Class Reference
Sandbox::MeshLoaderThread Class Reference
#include <DocumentThread.h>
Public Member Functions
Base::Reference< Mesh::MeshObject > getMesh () const
MeshLoaderThread (const QString &, QObject *parent=0)
~MeshLoaderThread ()
Protected Member Functions
void run ()
Constructor & Destructor Documentation
MeshLoaderThread()
MeshLoaderThread::MeshLoaderThread (const QString & fn, QObject * parent = 0)
~MeshLoaderThread()
MeshLoaderThread::~MeshLoaderThread ()
Member Function Documentation
getMesh()
Base::Reference< Mesh::MeshObject > MeshLoaderThread::getMesh () const
Referenced by CmdSandboxMeshLoader::activated().
run()
void MeshLoaderThread::run (void) protected
References Mesh::MeshObject::load().
Referenced by femexamples.examplesgui.FemExamples::clicked(), and femsolver.task.Task::protector().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sandbox/App/DocumentThread.h
FreeCAD/src/Mod/Sandbox/App/DocumentThread.cpp