FreeCAD: ColorPickerItem Class Reference
ColorPickerItem Class Reference
Public Slots
void setColor (const QColor &color, const QString &text=QString())
Signals
void clicked ()
void selected ()
Public Member Functions
QColor color () const
ColorPickerItem (const QColor &color=Qt::white, const QString &text=QString(), QWidget *parent=0)
bool isSelected () const
void setSelected (bool)
QString text () const
~ColorPickerItem ()
Protected Member Functions
void mouseMoveEvent (QMouseEvent *e)
void mousePressEvent (QMouseEvent *e)
void mouseReleaseEvent (QMouseEvent *e)
void paintEvent (QPaintEvent *e)
Constructor & Destructor Documentation
ColorPickerItem()
ColorPickerItem::ColorPickerItem (const QColor & color = Qt::white, const QString & text = QString(), QWidget * parent = 0)
Constructs a ColorPickerItem whose color is set to color, and whose name is set to text.
~ColorPickerItem()
ColorPickerItem::~ColorPickerItem ()
Destructs a ColorPickerItem.
Member Function Documentation
clicked
void ColorPickerItem::clicked () signal
color()
QColor ColorPickerItem::color () const
Returns the item's color.
See also
text()
Referenced by ArchSite.Compass::buildCoordinates(), draftviewproviders.view_dimension.ViewProviderLinearDimension::draw_dim_arrows(), draftviewproviders.view_dimension.ViewProviderAngularDimension::draw_dim_arrows(), draftviewproviders.view_dimension.ViewProviderLinearDimension::draw_dim_overshoot(), draftviewproviders.view_dimension.ViewProviderLinearDimension::draw_ext_overshoot(), draftguitools.gui_trimex.Trimex::finish(), importSVG.svgHandler::format(), DraftGui.DraftToolBar::getcol(), DraftGui.DraftToolBar::getDefaultColor(), ColorPickerPopup::keyPressEvent(), ArchPanel.ViewProviderPanelCut::onChanged(), ArchPanel.ViewProviderPanelSheet::onChanged(), draftviewproviders.view_dimension.ViewProviderLinearDimension::onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension::onChanged(), FeaturePython.ViewProviderOctahedron::onChanged(), Mod.Test.unittestgui.ProgressBar::paint(), setColor(), draftguitools.gui_trackers.editTracker::setColor(), PathScripts.PathDressupTagGui.HoldingTagMarker::setEnabled(), DraftGui.DraftToolBar::setStyleButton(), and ColorPickerPopup::updateSelected().
isSelected()
bool ColorPickerItem::isSelected () const
mouseMoveEvent()
void ColorPickerItem::mouseMoveEvent (QMouseEvent * e) protected
mousePressEvent()
void ColorPickerItem::mousePressEvent (QMouseEvent * e) protected
mouseReleaseEvent()
void ColorPickerItem::mouseReleaseEvent (QMouseEvent * e) protected
References selected().
paintEvent()
void ColorPickerItem::paintEvent (QPaintEvent * e) protected
selected
void ColorPickerItem::selected () signal
Referenced by mouseReleaseEvent(), PathScripts.PathDressupTagGui.HoldingTagMarker::setEnabled(), setSelected(), and PathScripts.PathDressupTagGui.HoldingTagMarker::setSelected().
setColor
void ColorPickerItem::setColor (const QColor & color, const QString & text = QString()) slot
Sets the item's color to color, and its name to text.
References color(), and text().
setSelected()
void ColorPickerItem::setSelected (bool selected)
References selected().
Referenced by ColorPickerPopup::insertColor(), ColorPickerPopup::keyPressEvent(), QtColorPicker::setCurrentColor(), and ColorPickerPopup::updateSelected().
text()
QString ColorPickerItem::text () const
Returns the item's text.
See also
color()
Referenced by importSVG.svgHandler::characters(), draftguitools.gui_texts.Text::createObject(), importSVG.svgHandler::endElement(), exportIFCHelper.SIUnitCreator::getSIPrefix(), exportIFCHelper.SIUnitCreator::getSIUnitName(), Mod.Test.unittestgui.ProgressBar::paint(), setColor(), and QtColorPicker::setCurrentColor().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Spreadsheet/Gui/qtcolorpicker.cpp