FreeCAD: App::PropertyContainerPy Class Reference
App::PropertyContainerPy Class Reference
The python export class for PropertyContainer.
#include <PropertyContainerPy.h>
Public Types
typedef PropertyContainer * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
PropertyContainerPy (PropertyContainer *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of PropertyContainerPy.
static PyMethodDef Methods []
Methods structure of PropertyContainerPy.
static PyTypeObject Type
Type structure of PropertyContainerPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~PropertyContainerPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * getPropertyByName (PyObject *args)
implementer for the getPropertyByName() method
PyObject * getPropertyTouchList (PyObject *args)
implementer for the getPropertyTouchList() method
PyObject * getTypeOfProperty (PyObject *args)
implementer for the getTypeOfProperty() method
PyObject * getTypeIdOfProperty (PyObject *args)
implementer for the getTypeIdOfProperty() method
PyObject * setEditorMode (PyObject *args)
implementer for the setEditorMode() method
PyObject * getEditorMode (PyObject *args)
implementer for the getEditorMode() method
PyObject * getGroupOfProperty (PyObject *args)
implementer for the getGroupOfProperty() method
PyObject * setPropertyStatus (PyObject *args)
implementer for the setPropertyStatus() method
PyObject * getPropertyStatus (PyObject *args)
implementer for the getPropertyStatus() method
PyObject * getDocumentationOfProperty (PyObject *args)
implementer for the getDocumentationOfProperty() method
PyObject * dumpPropertyContent (PyObject *args, PyObject *kwd)
implementer for the dumpPropertyContent() method
PyObject * restorePropertyContent (PyObject *args)
implementer for the restorePropertyContent() method
static PyObject * staticCallback_getPropertyByName (PyObject *self, PyObject *args)
callback for the getPropertyByName() method
static PyObject * staticCallback_getPropertyTouchList (PyObject *self, PyObject *args)
callback for the getPropertyTouchList() method
static PyObject * staticCallback_getTypeOfProperty (PyObject *self, PyObject *args)
callback for the getTypeOfProperty() method
static PyObject * staticCallback_getTypeIdOfProperty (PyObject *self, PyObject *args)
callback for the getTypeIdOfProperty() method
static PyObject * staticCallback_setEditorMode (PyObject *self, PyObject *args)
callback for the setEditorMode() method
static PyObject * staticCallback_getEditorMode (PyObject *self, PyObject *args)
callback for the getEditorMode() method
static PyObject * staticCallback_getGroupOfProperty (PyObject *self, PyObject *args)
callback for the getGroupOfProperty() method
static PyObject * staticCallback_setPropertyStatus (PyObject *self, PyObject *args)
callback for the setPropertyStatus() method
static PyObject * staticCallback_getPropertyStatus (PyObject *self, PyObject *args)
callback for the getPropertyStatus() method
static PyObject * staticCallback_getDocumentationOfProperty (PyObject *self, PyObject *args)
callback for the getDocumentationOfProperty() method
static PyObject * staticCallback_dumpPropertyContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpPropertyContent() method
static PyObject * staticCallback_restorePropertyContent (PyObject *self, PyObject *args)
callback for the restorePropertyContent() method
callbacks and implementers for the python object attributes
Py::List getPropertiesList (void) const
getter for the PropertiesList attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
PropertyContainer * getPropertyContainerPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getPropertiesList (PyObject *self, void *closure)
getter callback for the PropertiesList attribute
static int staticCallback_setPropertiesList (PyObject *self, PyObject *value, void *closure)
setter callback for the PropertiesList attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for PropertyContainer.
Member Typedef Documentation
PointerType
typedef PropertyContainer* App::PropertyContainerPy::PointerType
Constructor & Destructor Documentation
~PropertyContainerPy()
PropertyContainerPy::~PropertyContainerPy () protected
PropertyContainerPy()
PropertyContainerPy::PropertyContainerPy (PropertyContainer * pcObject, PyTypeObject * T = &Type)
References Base::PyObjectBase::setShouldNotify().
Member Function Documentation
dumpPropertyContent()
PyObject * PropertyContainerPy::dumpPropertyContent (PyObject * args, PyObject * kwd)
implementer for the dumpPropertyContent() method
References Base::Persistence::dumpToStream(), App::PropertyContainer::getPropertyByName(), and getPropertyContainerPtr().
Referenced by staticCallback_dumpPropertyContent().
getCustomAttributes()
PyObject * PropertyContainerPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
References Base::Persistence::getClassTypeId(), App::PropertyContainer::getPropertyByName(), getPropertyContainerPtr(), App::PropertyContainer::getPropertyMap(), Base::BaseClass::getPyObject(), Base::BaseClassPy::isDerivedFrom(), and Base::streq().
Referenced by App::ExtensionContainerPy::getCustomAttributes().
getDocumentationOfProperty()
PyObject * PropertyContainerPy::getDocumentationOfProperty (PyObject * args)
implementer for the getDocumentationOfProperty() method
References App::PropertyContainer::getPropertyByName(), getPropertyContainerPtr(), and App::PropertyContainer::getPropertyDocumentation().
Referenced by staticCallback_getDocumentationOfProperty().
getEditorMode()
PyObject * PropertyContainerPy::getEditorMode (PyObject * args)
implementer for the getEditorMode() method
References App::PropertyContainer::getPropertyByName(), getPropertyContainerPtr(), App::Property::getType(), App::Property::Hidden, App::Prop_Hidden, App::Prop_ReadOnly, App::Property::ReadOnly, App::Property::testStatus(), and Type.
Referenced by staticCallback_getEditorMode().
getGroupOfProperty()
PyObject * PropertyContainerPy::getGroupOfProperty (PyObject * args)
implementer for the getGroupOfProperty() method
References App::PropertyContainer::getPropertyByName(), getPropertyContainerPtr(), and App::PropertyContainer::getPropertyGroup().
Referenced by staticCallback_getGroupOfProperty().
getPropertiesList()
Py::List PropertyContainerPy::getPropertiesList (void) const
getter for the PropertiesList attribute
References getPropertyContainerPtr(), and App::PropertyContainer::getPropertyMap().
Referenced by staticCallback_getPropertiesList().
getPropertyByName()
PyObject * PropertyContainerPy::getPropertyByName (PyObject * args)
implementer for the getPropertyByName() method
References App::Property::getContainer(), App::PropertyContainer::getPropertyByName(), getPropertyContainerPtr(), and Base::BaseClass::getPyObject().
Referenced by staticCallback_getPropertyByName().
getPropertyContainerPtr()
PropertyContainer * PropertyContainerPy::getPropertyContainerPtr (void) const
getter for the object handled by this class
Referenced by dumpPropertyContent(), App::DocumentPy::getCustomAttributes(), getCustomAttributes(), getDocumentationOfProperty(), getEditorMode(), getGroupOfProperty(), getPropertiesList(), getPropertyByName(), getPropertyStatus(), getPropertyTouchList(), getTypeIdOfProperty(), getTypeOfProperty(), restorePropertyContent(), App::DocumentPy::setCustomAttributes(), setCustomAttributes(), setEditorMode(), and setPropertyStatus().
getPropertyStatus()
PyObject * PropertyContainerPy::getPropertyStatus (PyObject * args)
implementer for the getPropertyStatus() method
References App::PropertyContainer::getPropertyByName(), getPropertyContainerPtr(), App::Property::getStatus(), and App::PropertyLinkBase::LinkAllowPartial.
Referenced by staticCallback_getPropertyStatus().
getPropertyTouchList()
PyObject * PropertyContainerPy::getPropertyTouchList (PyObject * args)
implementer for the getPropertyTouchList() method
References Base::Persistence::getClassTypeId(), App::PropertyContainer::getPropertyByName(), getPropertyContainerPtr(), and Base::BaseClass::isDerivedFrom().
Referenced by staticCallback_getPropertyTouchList().
GetType()
virtual PyTypeObject* App::PropertyContainerPy::GetType (void) virtual
Reimplemented from Base::PersistencePy.
Reimplemented in TechDraw::DrawWeldSymbolPy, TechDraw::DrawViewSymbolPy, TechDraw::DrawViewPy, TechDraw::DrawViewPartPy, TechDraw::DrawViewDimExtentPy, TechDraw::DrawViewDimensionPy, TechDraw::DrawViewCollectionPy, TechDraw::DrawViewClipPy, TechDraw::DrawViewAnnotationPy, TechDraw::DrawTileWeldPy, TechDraw::DrawTilePy, TechDraw::DrawTemplatePy, TechDraw::DrawSVGTemplatePy, TechDraw::DrawRichAnnoPy, TechDraw::DrawProjGroupPy, TechDraw::DrawProjGroupItemPy, TechDraw::DrawParametricTemplatePy, TechDraw::DrawPagePy, TechDraw::DrawLeaderLinePy, TechDraw::DrawHatchPy, TechDraw::DrawGeomHatchPy, Spreadsheet::SheetPy, Sketcher::SketchObjectSFPy, Sketcher::SketchObjectPy, Robot::RobotObjectPy, Path::FeaturePathCompoundPy, Path::FeatureAreaPy, PartDesignGui::ViewProviderPy, PartDesign::FeaturePy, PartDesign::BodyPy, Part::PartFeaturePy, Part::Part2DObjectPy, Part::BodyBasePy, MeshGui::ViewProviderMeshPy, Mesh::MeshFeaturePy, FemGui::ViewProviderFemMeshPy, Fem::FemPostPipelinePy, Gui::ViewProviderPy, Gui::ViewProviderLinkPy, Gui::ViewProviderDocumentObjectPy, App::PartPy, App::GeoFeaturePy, App::ExtensionContainerPy, App::DocumentPy, App::DocumentObjectPy, and App::DocumentObjectGroupPy.
getTypeIdOfProperty()
PyObject * PropertyContainerPy::getTypeIdOfProperty (PyObject * args)
implementer for the getTypeIdOfProperty() method
References Base::Type::getName(), App::PropertyContainer::getPropertyByName(), getPropertyContainerPtr(), and Base::Persistence::getTypeId().
Referenced by staticCallback_getTypeIdOfProperty().
getTypeOfProperty()
PyObject * PropertyContainerPy::getTypeOfProperty (PyObject * args)
implementer for the getTypeOfProperty() method
References App::PropertyContainer::getPropertyByName(), getPropertyContainerPtr(), App::Property::getType(), App::Prop_Hidden, App::Prop_NoRecompute, App::Prop_Output, App::Prop_ReadOnly, App::Prop_Transient, and Type.
Referenced by staticCallback_getTypeOfProperty().
PyInit()
int PropertyContainerPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PersistencePy.
Reimplemented in TechDraw::DrawWeldSymbolPy, TechDraw::DrawViewSymbolPy, TechDraw::DrawViewPy, TechDraw::DrawViewPartPy, TechDraw::DrawViewDimExtentPy, TechDraw::DrawViewDimensionPy, TechDraw::DrawViewCollectionPy, TechDraw::DrawViewClipPy, TechDraw::DrawViewAnnotationPy, TechDraw::DrawTileWeldPy, TechDraw::DrawTilePy, TechDraw::DrawTemplatePy, TechDraw::DrawSVGTemplatePy, TechDraw::DrawRichAnnoPy, TechDraw::DrawProjGroupPy, TechDraw::DrawProjGroupItemPy, TechDraw::DrawParametricTemplatePy, TechDraw::DrawPagePy, TechDraw::DrawLeaderLinePy, TechDraw::DrawHatchPy, TechDraw::DrawGeomHatchPy, Spreadsheet::SheetPy, Sketcher::SketchObjectSFPy, Sketcher::SketchObjectPy, Robot::RobotObjectPy, Path::FeaturePathCompoundPy, Path::FeatureAreaPy, PartDesignGui::ViewProviderPy, PartDesign::FeaturePy, PartDesign::BodyPy, Part::PartFeaturePy, Part::Part2DObjectPy, Part::BodyBasePy, MeshGui::ViewProviderMeshPy, Mesh::MeshFeaturePy, FemGui::ViewProviderFemMeshPy, Fem::FemPostPipelinePy, Gui::ViewProviderPy, Gui::ViewProviderLinkPy, Gui::ViewProviderDocumentObjectPy, App::PartPy, App::GeoFeaturePy, App::ExtensionContainerPy, App::DocumentPy, App::DocumentObjectPy, and App::DocumentObjectGroupPy.
PyMake()
PyObject * PropertyContainerPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string PropertyContainerPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
restorePropertyContent()
PyObject * PropertyContainerPy::restorePropertyContent (PyObject * args)
implementer for the restorePropertyContent() method
References App::PropertyContainer::getPropertyByName(), getPropertyContainerPtr(), and Base::Persistence::restoreFromStream().
Referenced by staticCallback_restorePropertyContent().
setCustomAttributes()
int PropertyContainerPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
References App::Property::getFullName(), App::PropertyContainer::getPropertyByName(), getPropertyContainerPtr(), App::Property::Immutable, Base::BaseClass::setPyObject(), and App::Property::testStatus().
setEditorMode()
PyObject * PropertyContainerPy::setEditorMode (PyObject * args)
implementer for the setEditorMode() method
References App::PropertyContainer::getPropertyByName(), getPropertyContainerPtr(), App::Property::getStatus(), App::Property::Hidden, App::Property::ReadOnly, and App::Property::setStatusValue().
Referenced by staticCallback_setEditorMode().
setPropertyStatus()
PyObject * PropertyContainerPy::setPropertyStatus (PyObject * args)
implementer for the setPropertyStatus() method
References App::PropertyContainer::getPropertyByName(), getPropertyContainerPtr(), App::Property::getStatus(), and App::Property::setStatusValue().
Referenced by staticCallback_setPropertyStatus().
staticCallback_dumpPropertyContent()
PyObject * PropertyContainerPy::staticCallback_dumpPropertyContent (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the dumpPropertyContent() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, dumpPropertyContent(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getDocumentationOfProperty()
PyObject * PropertyContainerPy::staticCallback_getDocumentationOfProperty (PyObject * self, PyObject * args) static
callback for the getDocumentationOfProperty() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getDocumentationOfProperty(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getEditorMode()
PyObject * PropertyContainerPy::staticCallback_getEditorMode (PyObject * self, PyObject * args) static
callback for the getEditorMode() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getEditorMode(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getGroupOfProperty()
PyObject * PropertyContainerPy::staticCallback_getGroupOfProperty (PyObject * self, PyObject * args) static
callback for the getGroupOfProperty() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getGroupOfProperty(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getPropertiesList()
PyObject * PropertyContainerPy::staticCallback_getPropertiesList (PyObject * self, void * closure) static
getter callback for the PropertiesList attribute
References Base::BaseExceptionFreeCADError, getPropertiesList(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPropertyByName()
PyObject * PropertyContainerPy::staticCallback_getPropertyByName (PyObject * self, PyObject * args) static
callback for the getPropertyByName() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPropertyByName(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getPropertyStatus()
PyObject * PropertyContainerPy::staticCallback_getPropertyStatus (PyObject * self, PyObject * args) static
callback for the getPropertyStatus() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPropertyStatus(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getPropertyTouchList()
PyObject * PropertyContainerPy::staticCallback_getPropertyTouchList (PyObject * self, PyObject * args) static
callback for the getPropertyTouchList() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPropertyTouchList(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getTypeIdOfProperty()
PyObject * PropertyContainerPy::staticCallback_getTypeIdOfProperty (PyObject * self, PyObject * args) static
callback for the getTypeIdOfProperty() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getTypeIdOfProperty(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getTypeOfProperty()
PyObject * PropertyContainerPy::staticCallback_getTypeOfProperty (PyObject * self, PyObject * args) static
callback for the getTypeOfProperty() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getTypeOfProperty(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_restorePropertyContent()
PyObject * PropertyContainerPy::staticCallback_restorePropertyContent (PyObject * self, PyObject * args) static
callback for the restorePropertyContent() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), restorePropertyContent(), and Base::PyObjectBase::startNotify().
staticCallback_setEditorMode()
PyObject * PropertyContainerPy::staticCallback_setEditorMode (PyObject * self, PyObject * args) static
callback for the setEditorMode() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setEditorMode(), and Base::PyObjectBase::startNotify().
staticCallback_setPropertiesList()
int PropertyContainerPy::staticCallback_setPropertiesList (PyObject * self, PyObject * value, void * closure) static
setter callback for the PropertiesList attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPropertyStatus()
PyObject * PropertyContainerPy::staticCallback_setPropertyStatus (PyObject * self, PyObject * args) static
callback for the setPropertyStatus() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setPropertyStatus(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef PropertyContainerPy::GetterSetter static
Initial value:
= {
    {"PropertiesList",
        (getter) staticCallback_getPropertiesList,
        (setter) staticCallback_setPropertiesList,
        "A list of all property names",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of PropertyContainerPy.
Methods
PyMethodDef PropertyContainerPy::Methods static
Methods structure of PropertyContainerPy.
Type
PyTypeObject PropertyContainerPy::Type static
Type structure of PropertyContainerPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), getEditorMode(), getTypeOfProperty(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/App/PropertyContainerPy.h
Sources/FreeCAD/src/App/PropertyContainerPyImp.cpp
Sources/FreeCAD-SourceDocs/src/App/PropertyContainerPy.cpp