FreeCAD: PathTests.TestPathCore.TestPathCore Class Reference
PathTests.TestPathCore.TestPathCore Class Reference
Public Member Functions
def test00 (self)
def test10 (self)
def test20 (self)
def test50 (self)
Public Member Functions inherited from PathTests.PathTestUtils.PathTestBase
def assertArc (self, edge, pt1, pt2, direction='CW')
def assertCircle (self, edge, pt, r)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertCommandEqual (self, c1, c2)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertEdgeShapesMatch (self, e1, e2)
def assertEqualLocale (self, s1, s2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertPlacement (self, p1, p2)
def assertPointsMatch (self, pts0, pts1)
def assertRoughly (self, f1, f2, error=0.00001)
Member Function Documentation
test00()
def PathTests.TestPathCore.TestPathCore.test00 (self)
Test Path command core functionality
Referenced by PathTests.TestPathTool.TestPathTool.test01(), PathTests.TestPathToolController.TestPathToolController.test01(), PathTests.TestPathTooltable.TestPathTooltable.test01(), PathTests.TestPathTool.TestPathTool.test02(), and PathTests.TestPathTooltable.TestPathTooltable.test02().
test10()
def PathTests.TestPathCore.TestPathCore.test10 (self)
Test Path Object core functionality
References Mod.Test.Document.DocumentExpressionCases.assertAlmostEqual().
test20()
def PathTests.TestPathCore.TestPathCore.test20 (self)
Test Path Tool and ToolTable object core functionality
test50()
def PathTests.TestPathCore.TestPathCore.test50 (self)
Test Path.Length calculation
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Path/PathTests/TestPathCore.py