FreeCAD: MeshGui::RemeshGmsh Class Reference
MeshGui::RemeshGmsh Class Reference
Non-modal dialog to remesh an existing mesh.
#include <RemeshGmsh.h>
Classes
class Private
Public Member Functions
RemeshGmsh (Mesh::Feature *mesh, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~RemeshGmsh ()
Public Member Functions inherited from MeshGui::GmshWidget
void accept ()
GmshWidget (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
void reject ()
~GmshWidget ()
Protected Member Functions
virtual bool loadOutput ()
virtual bool writeProject (QString &inpFile, QString &outFile)
Protected Member Functions inherited from MeshGui::GmshWidget
void changeEvent (QEvent *e)
double getAngle () const
double getMaxSize () const
double getMinSize () const
virtual bool loadOutput ()
int meshingAlgorithm () const
virtual bool writeProject (QString &inpFile, QString &outFile)
Detailed Description
Non-modal dialog to remesh an existing mesh.
Author
Werner Mayer
Constructor & Destructor Documentation
RemeshGmsh()
RemeshGmsh::RemeshGmsh (Mesh::Feature * mesh, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
References App::Application::getTempFileName().
~RemeshGmsh()
RemeshGmsh::~RemeshGmsh ()
Member Function Documentation
loadOutput()
bool RemeshGmsh::loadOutput () protected virtual
Reimplemented from MeshGui::GmshWidget.
References Base::FileInfo::deleteFile(), App::DocumentObject::getDocument(), Mesh::MeshObject::getKernel(), Mesh::MeshObject::harmonizeNormals(), Mesh::Feature::Mesh, and Mesh::PropertyMeshKernel::setValue().
writeProject()
bool RemeshGmsh::writeProject (QString & inpFile, QString & outFile) protected virtual
Reimplemented from MeshGui::GmshWidget.
References Base::FileInfo::filePath(), MeshGui::GmshWidget::getAngle(), MeshGui::GmshWidget::getMaxSize(), MeshGui::GmshWidget::getMinSize(), MeshGui::GmshWidget::meshingAlgorithm(), and MeshCore::MeshOutput::SaveBinarySTL().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/Gui/RemeshGmsh.h
FreeCAD/src/Mod/Mesh/Gui/RemeshGmsh.cpp