FreeCAD: FemGui::SphereWidget Class Reference
FemGui::SphereWidget Class Reference
#include <ViewProviderFemPostFunction.h>
Public Member Functions
virtual void applyPythonCode ()
virtual void onChange (const App::Property &p)
virtual void setViewProvider (ViewProviderFemPostFunction *view)
SphereWidget ()
virtual ~SphereWidget ()
Public Member Functions inherited from FemGui::FunctionWidget
virtual void applyPythonCode ()=0
FunctionWidget ()
void onObjectsChanged (const App::DocumentObject &obj, const App::Property &)
virtual void setViewProvider (ViewProviderFemPostFunction *view)
virtual ~FunctionWidget ()
Additional Inherited Members
Protected Member Functions inherited from FemGui::FunctionWidget
bool blockObjectUpdates ()
Fem::FemPostFunction * getObject ()
ViewProviderFemPostFunction * getView ()
virtual void onChange (const App::Property &p)=0
void setBlockObjectUpdates (bool val)
Constructor & Destructor Documentation
SphereWidget()
SphereWidget::SphereWidget ()
References Ui_SphereWidget::centerX, Ui_SphereWidget::centerY, Ui_SphereWidget::centerZ, draftgeoutils.intersections::connect(), Base::UnitsApi::getDecimals(), Ui_SphereWidget::radius, Gui::QuantitySpinBox::setDecimals(), Ui_SphereWidget::setupUi(), and Gui::QuantitySpinBox::sizeForText().
~SphereWidget()
SphereWidget::~SphereWidget () virtual
Member Function Documentation
applyPythonCode()
void SphereWidget::applyPythonCode () virtual
Implements FemGui::FunctionWidget.
onChange()
void SphereWidget::onChange (const App::Property & p) virtual
Implements FemGui::FunctionWidget.
References Ui_SphereWidget::centerX, Ui_SphereWidget::centerY, Ui_SphereWidget::centerZ, Ui_SphereWidget::radius, FemGui::FunctionWidget::setBlockObjectUpdates(), Gui::QuantitySpinBox::setValue(), and draftgeoutils.general::vec().
Referenced by setViewProvider().
setViewProvider()
void SphereWidget::setViewProvider (ViewProviderFemPostFunction * view) virtual
Reimplemented from FemGui::FunctionWidget.
References Ui_SphereWidget::centerX, Ui_SphereWidget::centerY, Ui_SphereWidget::centerZ, FemGui::FunctionWidget::getObject(), onChange(), Ui_SphereWidget::radius, FemGui::FunctionWidget::setBlockObjectUpdates(), Gui::QuantitySpinBox::setUnit(), and FemGui::FunctionWidget::setViewProvider().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/ViewProviderFemPostFunction.h
FreeCAD/src/Mod/Fem/Gui/ViewProviderFemPostFunction.cpp