FreeCAD: TechDrawGui::TemplateTextField Class Reference
TechDrawGui::TemplateTextField Class Reference
QGraphicsRectItem-derived class for the text fields in title blocks.
#include <TemplateTextField.h>
Public Types
enum { Type = QGraphicsItem::UserType + 160 }
Public Member Functions
std::string fieldName () const
Returns the field name that this TemplateTextField represents.
TemplateTextField (QGraphicsItem *parent, TechDraw::DrawTemplate *myTmplte, const std::string &myFieldName)
int type () const
virtual ~TemplateTextField ()=default
Protected Member Functions
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event)
Need this to properly handle mouse release.
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
Trigger the dialog for editing template text.
Protected Attributes
std::string fieldNameStr
TechDraw::DrawTemplate * tmplte
Detailed Description
QGraphicsRectItem-derived class for the text fields in title blocks.
Makes an area on the drawing that's clickable, so appropriate Properties of the template can be modified.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
TemplateTextField()
TemplateTextField::TemplateTextField (QGraphicsItem * parent, TechDraw::DrawTemplate * myTmplte, const std::string & myFieldName)
~TemplateTextField()
virtual TechDrawGui::TemplateTextField::~TemplateTextField () virtual default
Member Function Documentation
fieldName()
std::string TechDrawGui::TemplateTextField::fieldName () const
Returns the field name that this TemplateTextField represents.
mousePressEvent()
void TemplateTextField::mousePressEvent (QGraphicsSceneMouseEvent * event) protected virtual
Need this to properly handle mouse release.
References tmplte.
mouseReleaseEvent()
void TemplateTextField::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected virtual
Trigger the dialog for editing template text.
References TechDraw::DrawTemplate::EditableTexts, fieldNameStr, TechDrawGui::DlgTemplateField::getFieldContent(), TechDrawGui::DlgTemplateField::setFieldContent(), TechDrawGui::DlgTemplateField::setFieldName(), App::PropertyMap::setValue(), and tmplte.
type()
int TechDrawGui::TemplateTextField::type (void) const
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
Member Data Documentation
fieldNameStr
std::string TechDrawGui::TemplateTextField::fieldNameStr protected
Referenced by mouseReleaseEvent().
tmplte
TechDraw::DrawTemplate* TechDrawGui::TemplateTextField::tmplte protected
Referenced by mousePressEvent(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/TemplateTextField.h
FreeCAD/src/Mod/TechDraw/Gui/TemplateTextField.cpp