FreeCAD: PathScripts.PathAdaptive Namespace Reference
PathScripts.PathAdaptive Namespace Reference
Classes
class PathAdaptive
Functions
def CalcHelixConePoint (height, cur_z, radius, angle)
def convertTo2d (pathArray)
def Create (name, obj=None, parentJob=None)
def discretize (edge, flipDirection=False)
def Execute (op, obj)
def GenerateGCode (op, obj, adaptiveResults, helixDiameter)
def sceneClean ()
def sceneDrawPath (path, color=(0, 0, 1))
def SetupProperties ()
Variables
DraftGeomUtils = LazyLoader("DraftGeomUtils", globals(), "DraftGeomUtils")
FeatureExtensions
Part = LazyLoader("Part", globals(), "Part")
sceneGraph = None
list scenePathNodes = []
int topZ = 10
translate = FreeCAD.Qt.translate
Function Documentation
CalcHelixConePoint()
def PathScripts.PathAdaptive.CalcHelixConePoint (height, cur_z, radius, angle)
Referenced by PathScripts.PathAdaptive.GenerateGCode().
convertTo2d()
def PathScripts.PathAdaptive.convertTo2d (pathArray)
Referenced by PathScripts.PathAdaptive.Execute().
Create()
def PathScripts.PathAdaptive.Create (name, obj = None, parentJob = None)
Create(name) ... Creates and returns a Adaptive operation.
discretize()
def PathScripts.PathAdaptive.discretize (edge, flipDirection = False)
Referenced by PathScripts.PathAdaptive.Execute().
Execute()
def PathScripts.PathAdaptive.Execute (op, obj)
References PathScripts.PathAdaptive.convertTo2d(), PathScripts.PathAdaptive.discretize(), PathScripts.PathAdaptive.GenerateGCode(), PathScripts.PathAdaptive.sceneClean(), and PathScripts.PathAdaptive.sceneDrawPath().
GenerateGCode()
def PathScripts.PathAdaptive.GenerateGCode (op, obj, adaptiveResults, helixDiameter)
References PathScripts.PathAdaptive.CalcHelixConePoint().
Referenced by PathScripts.PathAdaptive.Execute().
sceneClean()
def PathScripts.PathAdaptive.sceneClean ()
Referenced by PathScripts.PathAdaptive.Execute().
sceneDrawPath()
def PathScripts.PathAdaptive.sceneDrawPath (path, color = (0, 0, 1))
Referenced by PathScripts.PathAdaptive.Execute().
SetupProperties()
def PathScripts.PathAdaptive.SetupProperties ()
Variable Documentation
DraftGeomUtils
PathScripts.PathAdaptive.DraftGeomUtils = LazyLoader("DraftGeomUtils", globals(), "DraftGeomUtils")
FeatureExtensions
PathScripts.PathAdaptive.FeatureExtensions
Initial value:
=  LazyLoader(
    "PathScripts.PathFeatureExtensions", globals(), "PathScripts.PathFeatureExtensions"
)
Part
PathScripts.PathAdaptive.Part = LazyLoader("Part", globals(), "Part")
sceneGraph
PathScripts.PathAdaptive.sceneGraph = None
scenePathNodes
list PathScripts.PathAdaptive.scenePathNodes = []
topZ
int PathScripts.PathAdaptive.topZ = 10
translate
PathScripts.PathAdaptive.translate = FreeCAD.Qt.translate