FreeCAD: App::PropertyXLinkContainer Class Reference
App::PropertyXLinkContainer Class Reference
Abstract property that can link to multiple external objects.
#include <PropertyLinks.h>
Public Member Functions
virtual void afterRestore () override
Called at the beginning of Document::afterRestore()
virtual void breakLink (App::DocumentObject *obj, bool clear) override
Called to reset this link property.
virtual int checkRestore (std::string *msg=nullptr) const override
Test if the link is restored unchanged.
virtual void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=nullptr, bool newStyle=true) const override
Obtain the linked objects.
bool isLinkedToDocument (const App::Document &doc) const
PropertyXLinkContainer ()
virtual void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
~PropertyXLinkContainer ()
Public Member Functions inherited from App::PropertyLinkBase
virtual bool adjustLink (const std::set< App::DocumentObject * > &inList)=0
Called to adjust the link to avoid potential cyclic dependency.
virtual void breakLink (App::DocumentObject *obj, bool clear)=0
Called to reset this link property.
void checkLabelReferences (const std::vector< std::string > &subs, bool reset=true)
Check subnames for label registration.
virtual int checkRestore (std::string *msg=nullptr) const
Test if the link is restored unchanged.
virtual Property * CopyOnImportExternal (const std::map< std::string, std::string > &nameMap) const
Return a copy of the property if any changes caused by importing external linked object.
virtual Property * CopyOnLabelChange (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const
Update object label reference in this property.
virtual Property * CopyOnLinkReplace (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const =0
Return a copy of the property if the link replacement affects this property.
void getLinkedElements (std::map< App::DocumentObject *, std::vector< std::string > > &elements, bool newStyle=true, bool all=true) const
Helper function to return a map of linked object and its subname references.
template<class T >
void getLinkedObjects (T &inserter, bool all=false) const
Helper function to return linked objects using an std::inserter.
virtual void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=nullptr, bool newStyle=true) const =0
Obtain the linked objects.
virtual bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
std::map< App::DocumentObject *, std::vector< std::string > > linkedElements (bool newStyle=true, bool all=true) const
Helper function to return a map of linked object and its subname references.
std::vector< App::DocumentObject * > linkedObjects (bool all=false) const
Helper function to return all linked objects of this property.
PropertyLinkBase ()
virtual bool referenceChanged () const
Test if the element reference has changed after restore.
void registerLabelReferences (std::vector< std::string > &&labels, bool reset=true)
Register label reference for future object relabel update.
void setAllowExternal (bool allow)
Enable/disable temporary holding external object without throwing exception.
virtual void setAllowPartial (bool enable)
bool testFlag (int flag) const
void unregisterElementReference ()
Clear internal element reference registration.
void unregisterLabelReferences ()
Clear internal label references registration.
virtual void updateElementReference (App::DocumentObject *feature, bool reverse=false, bool notify=false)
Link type property interface APIs These APIs are moved here so that any type of property can have the property link behavior, e.g.
virtual ~PropertyLinkBase ()
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual Property * Copy (void) const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
int64_t getID () const
Return a unique ID for the property.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const char * getName (void) const
Get the name of this property in the belonging container With hasName() it can be checked beforehand if a valid name is set.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
bool hasName () const
Check if the property has a name set.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::ScopedLink
LinkScope getScope () const
Get the links scope Retrieve what kind of links are allowed.
void setScope (LinkScope scope)
Set the links scope Allows to define what kind of links are allowed.
Protected Member Functions
virtual void aboutToSetChildValue (App::Property &prop) override
Called before a child property changing value.
void clearDeps ()
virtual PropertyXLink * createXLink ()
virtual void onAddDep (App::DocumentObject *)
virtual void onBreakLink (App::DocumentObject *obj)
virtual void onRemoveDep (App::DocumentObject *)
void updateDeps (std::map< DocumentObject *, bool > &&newDeps)
Protected Member Functions inherited from App::PropertyLinkBase
virtual void hasSetValue () override
Gets called by all setValue() methods after the value has changed.
void setFlag (int flag, bool value=true)
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Additional Inherited Members
Public Types inherited from App::PropertyLinkBase
enum LinkFlags {
LinkAllowExternal , LinkDetached , LinkRestoring , LinkAllowPartial ,
LinkRestoreLabel , LinkSyncSubObject
}
typedef std::pair< std::string, std::string > ShadowSub
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , Busy = 15 ,
CopyOnChange = 16 , UserEdit = 17 , PropStaticBegin = 21 , PropDynamic = 21 ,
PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 , PropTransient = 25 ,
PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 , User1 = 28 ,
User2 = 29 , User3 = 30 , User4 = 31
}
Static Public Member Functions inherited from App::PropertyLinkBase
static void breakLinks (App::DocumentObject *link, const std::vector< App::DocumentObject * > &objs, bool clear)
Helper function for breaking link properties.
static const char * exportSubName (std::string &output, const App::DocumentObject *obj, const char *subname, bool first_obj=false)
Helper function to export a subname reference.
static void getLabelReferences (std::vector< std::string > &labels, const char *subname)
Helper function to extract labels from a subname reference.
static std::string importSubName (Base::XMLReader &reader, const char *sub, bool &restoreLabel)
Helper function to import a subname reference.
static void restoreLabelReference (const App::DocumentObject *obj, std::string &sub, ShadowSub *shadow=nullptr)
Helper function to restore label references during import.
static App::DocumentObject * tryImport (const App::Document *doc, const App::DocumentObject *obj, const std::map< std::string, std::string > &nameMap)
Helper function for link import operation.
static std::string tryImportSubName (const App::DocumentObject *obj, const char *sub, const App::Document *doc, const std::map< std::string, std::string > &nameMap)
Helper function for link import operation.
static std::pair< App::DocumentObject *, std::string > tryReplaceLink (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const char *sub=nullptr)
Helper functions.
static std::pair< App::DocumentObject *, std::vector< std::string > > tryReplaceLinkSubs (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const std::vector< std::string > &subs)
Helper function to check and replace a link with multiple subname references.
static void updateElementReferences (DocumentObject *feature, bool reverse=false)
Update all element references in all link properties of feature.
static std::string updateLabelReference (const App::DocumentObject *linked, const char *subname, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
Helper function to update subname reference on label change.
static std::vector< std::pair< Property *, std::unique_ptr< Property > > > updateLabelReferences (App::DocumentObject *obj, const char *newLabel)
Helper function to collect changed property when an object re-label.
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Check if the passed name is valid.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Detailed Description
Abstract property that can link to multiple external objects.
See also
See PropertyExpressionEngine for example usage
Constructor & Destructor Documentation
PropertyXLinkContainer()
PropertyXLinkContainer::PropertyXLinkContainer ()
References App::Global.
~PropertyXLinkContainer()
PropertyXLinkContainer::~PropertyXLinkContainer ()
Member Function Documentation
aboutToSetChildValue()
void PropertyXLinkContainer::aboutToSetChildValue (App::Property &) override protected virtual
Called before a child property changing value.
Reimplemented from App::Property.
References App::PropertyLinkBase::LinkDetached, and onBreakLink().
afterRestore()
void PropertyXLinkContainer::afterRestore () override virtual
Called at the beginning of Document::afterRestore()
This function is called without dependency sorting, because some types of link property can only reconstructs the linking information inside this function.
One example use case of this function is PropertyLinkSub that uses afterRestore() to parse and restore subname references, which may contain sub-object reference from external document, and there will be special mapping required during object import.
Another example is PropertyExpressionEngine which only parse the restored expression in afterRestore(). The reason, in addition to subname mapping like PropertyLinkSub, is that it can handle document name adjustment as well. It internally relies on PropertyXLink to store the external document path for external linking. When the external document is restored, its internal name may change due to name conflict with existing documents. PropertyExpressionEngine can now auto adjust external references without any problem.
Reimplemented from App::Property.
Reimplemented in App::PropertyExpressionEngine, and Spreadsheet::PropertySheet.
References App::Hidden, draftfunctions.move::move(), and App::quote().
Referenced by App::PropertyExpressionEngine::afterRestore().
breakLink()
void PropertyXLinkContainer::breakLink (App::DocumentObject * obj, bool clear) override virtual
Called to reset this link property.
Parameters
obj reset link property if it is linked to this object
clear if true, then also reset property if the owner of this property is obj
See also
breakLinks()
Implements App::PropertyLinkBase.
Reimplemented in Spreadsheet::PropertySheet.
References App::Property::aboutToSetValue(), App::Property::getContainer(), App::PropertyLinkBase::hasSetValue(), and onBreakLink().
checkRestore()
int PropertyXLinkContainer::checkRestore (std::string * msg = nullptr) const override virtual
Test if the link is restored unchanged.
Parameters
msg optional error message
Returns
For external linked object, return 2 in case the link is missing, and 1 if the time stamp has changed.
Reimplemented from App::PropertyLinkBase.
clearDeps()
void PropertyXLinkContainer::clearDeps () protected
References App::Property::getContainer().
createXLink()
PropertyXLink * PropertyXLinkContainer::createXLink () protected virtual
Referenced by Restore(), and updateDeps().
getLinks()
void PropertyXLinkContainer::getLinks (std::vector< App::DocumentObject * > & objs, bool all = false, std::vector< std::string > * subs = nullptr, bool newStyle = true) const override virtual
Obtain the linked objects.
Parameters
objs hold the returned linked objects on output
all if true, then return all the linked object regardless of this LinkScope. If false, then return only if the LinkScope is not hidden.
sub if given, then return subname references.
newStyle whether to return new or old style subname reference
Implements App::PropertyLinkBase.
isLinkedToDocument()
bool PropertyXLinkContainer::isLinkedToDocument (const App::Document & doc) const
onAddDep()
virtual void App::PropertyXLinkContainer::onAddDep (App::DocumentObject *) protected virtual
Reimplemented in Spreadsheet::PropertySheet.
Referenced by updateDeps().
onBreakLink()
void PropertyXLinkContainer::onBreakLink (App::DocumentObject * obj) protected virtual
Reimplemented in Spreadsheet::PropertySheet.
Referenced by aboutToSetChildValue(), and breakLink().
onRemoveDep()
virtual void App::PropertyXLinkContainer::onRemoveDep (App::DocumentObject *) protected virtual
Reimplemented in Spreadsheet::PropertySheet.
Referenced by updateDeps().
Restore()
void PropertyXLinkContainer::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Reimplemented in App::PropertyExpressionEngine, and Spreadsheet::PropertySheet.
References createXLink(), Base::XMLReader::getAttribute(), Base::XMLReader::getAttributeAsUnsigned(), Base::XMLReader::hasAttribute(), App::Hidden, Base::XMLReader::readElement(), and Base::XMLReader::readEndElement().
Referenced by App::PropertyExpressionEngine::Restore().
Save()
void PropertyXLinkContainer::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Reimplemented in App::PropertyExpressionEngine, and Spreadsheet::PropertySheet.
References Base::Writer::decInd(), Base::Persistence::encodeAttribute(), App::Property::getContainer(), App::Hidden, Base::Writer::incInd(), Base::Writer::ind(), and Base::Writer::Stream().
Referenced by App::PropertyExpressionEngine::Save().
updateDeps()
void PropertyXLinkContainer::updateDeps (std::map< DocumentObject *, bool > && newDeps) protected
References createXLink(), App::Property::getContainer(), App::Global, App::Hidden, App::PropertyLinkBase::LinkDetached, App::PropertyLinkBase::LinkRestoring, draftfunctions.move::move(), onAddDep(), onRemoveDep(), and App::PropertyLinkBase::testFlag().
Referenced by App::PropertyExpressionEngine::hasSetValue(), and Spreadsheet::PropertySheet::hasSetValue().
The documentation for this class was generated from the following files:
FreeCAD/src/App/PropertyLinks.h
FreeCAD/src/App/PropertyLinks.cpp