FreeCAD: SurfaceGui::SectionsPanel Class Reference
SurfaceGui::SectionsPanel Class Reference
#include <TaskSections.h>
Classes
class ShapeSelection
Public Member Functions
bool accept ()
void checkOpenCommand ()
void open ()
bool reject ()
SectionsPanel (ViewProviderSections *vp, Surface::Sections *obj)
void setEditedObject (Surface::Sections *obj)
~SectionsPanel ()
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockConnection (bool block)
void detachSelection ()
Detaches from the selection.
bool isConnectionAttached () const
bool isConnectionBlocked () const
SelectionObserver (bool attach=true, int resolve=1)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, int resolve=1)
Constructor.
virtual ~SelectionObserver ()
Public Member Functions inherited from Gui::DocumentObserver
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
virtual ~DocumentObserver ()
Protected Types
enum SelectionMode { , AppendEdge, RemoveEdge }
Protected Member Functions
void changeEvent (QEvent *e)
virtual void onSelectionChanged (const Gui::SelectionChanges &msg)
virtual void slotDeletedObject (const Gui::ViewProviderDocumentObject &Obj)
Notifies when the object is about to be removed.
virtual void slotRedoDocument (const Gui::Document &Doc)
Notifies on redo.
virtual void slotUndoDocument (const Gui::Document &Doc)
Notifies on undo.
Protected Attributes
bool checkCommand
Surface::Sections * editedObject
SelectionMode selectionMode
Member Enumeration Documentation
SelectionMode
enum SurfaceGui::SectionsPanel::SelectionMode protected
Enumerator
AppendEdge
RemoveEdge
Constructor & Destructor Documentation
SectionsPanel()
SurfaceGui::SectionsPanel::SectionsPanel (ViewProviderSections * vp, Surface::Sections * obj)
References checkCommand, draftgeoutils.intersections::connect(), selectionMode, and setEditedObject().
~SectionsPanel()
SurfaceGui::SectionsPanel::~SectionsPanel ()
Member Function Documentation
accept()
bool SurfaceGui::SectionsPanel::accept (void)
References SurfaceGui::ViewProviderSections::Edge, editedObject, App::DocumentObject::getStatusString(), App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderSections::highlightReferences(), App::DocumentObject::isValid(), Part::Feature::mustExecute(), Surface::Sections::NSections, App::DocumentObject::recomputeFeature(), Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), and selectionMode.
Referenced by SurfaceGui::TaskSections::accept().
changeEvent()
void SurfaceGui::SectionsPanel::changeEvent (QEvent * e) protected
checkOpenCommand()
void SurfaceGui::SectionsPanel::checkOpenCommand ()
References checkCommand, editedObject, App::PropertyString::getValue(), Gui::Command::hasPendingCommand(), App::DocumentObject::Label, and Gui::Command::openCommand().
Referenced by onSelectionChanged(), and open().
onSelectionChanged()
void SurfaceGui::SectionsPanel::onSelectionChanged (const Gui::SelectionChanges & msg) protected virtual
Implements Gui::SelectionObserver.
References Gui::SelectionChanges::AddSelection, AppendEdge, checkOpenCommand(), editedObject, Gui::SelectionObject::getObject(), App::PropertyString::getValue(), App::DocumentObject::Label, App::DocumentObject::recomputeFeature(), RemoveEdge, and selectionMode.
open()
void SurfaceGui::SectionsPanel::open ()
References checkOpenCommand(), Gui::SelectionSingleton::clearSelection(), SurfaceGui::ViewProviderSections::Edge, editedObject, App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderSections::highlightReferences(), Surface::Sections::NSections, and Gui::Selection().
Referenced by SurfaceGui::TaskSections::open().
reject()
bool SurfaceGui::SectionsPanel::reject (void)
References SurfaceGui::ViewProviderSections::Edge, editedObject, App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderSections::highlightReferences(), Surface::Sections::NSections, Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), and selectionMode.
Referenced by SurfaceGui::TaskSections::reject().
setEditedObject()
void SurfaceGui::SectionsPanel::setEditedObject (Surface::Sections * obj)
References Gui::DocumentObserver::attachDocument(), editedObject, App::DocumentObject::getDocument(), App::PropertyLinkSubList::getSubValues(), App::PropertyLinkSubList::getValues(), Gui::Application::Instance, and Surface::Sections::NSections.
Referenced by SectionsPanel(), and SurfaceGui::TaskSections::setEditedObject().
slotDeletedObject()
void SurfaceGui::SectionsPanel::slotDeletedObject (const Gui::ViewProviderDocumentObject & Obj) protected virtual
Notifies when the object is about to be removed.
Reimplemented from Gui::DocumentObserver.
References SurfaceGui::ViewProviderSections::Edge, editedObject, App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderSections::highlightReferences(), and Surface::Sections::NSections.
slotRedoDocument()
void SurfaceGui::SectionsPanel::slotRedoDocument (const Gui::Document & Doc) protected virtual
Notifies on redo.
Reimplemented from Gui::DocumentObserver.
References checkCommand.
slotUndoDocument()
void SurfaceGui::SectionsPanel::slotUndoDocument (const Gui::Document & Doc) protected virtual
Notifies on undo.
Reimplemented from Gui::DocumentObserver.
References checkCommand.
Member Data Documentation
checkCommand
bool SurfaceGui::SectionsPanel::checkCommand protected
Referenced by checkOpenCommand(), SectionsPanel(), slotRedoDocument(), and slotUndoDocument().
editedObject
Surface::Sections* SurfaceGui::SectionsPanel::editedObject protected
Referenced by accept(), checkOpenCommand(), onSelectionChanged(), open(), reject(), setEditedObject(), and slotDeletedObject().
selectionMode
SelectionMode SurfaceGui::SectionsPanel::selectionMode protected
Referenced by accept(), onSelectionChanged(), reject(), and SectionsPanel().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Surface/Gui/TaskSections.h
Sources/FreeCAD/src/Mod/Surface/Gui/TaskSections.cpp