FreeCAD: SpreadsheetGui::SheetTableView Class Reference
SpreadsheetGui::SheetTableView Class Reference
#include <SheetTableView.h>
Public Slots
void copySelection ()
void cutSelection ()
void deleteSelection ()
void finishEditWithMove (int keyPressed, Qt::KeyboardModifiers modifiers, bool handleTabMotion=false)
void mergeCells ()
void ModifyBlockSelection (int targetRow, int targetColumn)
void pasteClipboard ()
void splitCell ()
Public Member Functions
void edit (const QModelIndex &index)
QModelIndexList selectedIndexesRaw () const
std::vector< App::Range > selectedRanges () const
void setSheet (Spreadsheet::Sheet *_sheet)
SheetTableView (QWidget *parent=nullptr)
QString toHtml () const
~SheetTableView ()
Protected Slots
void cellProperties ()
void commitData (QWidget *editor)
void insertColumns ()
void insertColumnsAfter ()
void insertRows ()
void insertRowsAfter ()
void onBind ()
void onConfSetup ()
void onRecompute ()
void removeColumns ()
void removeRows ()
void updateCellSpan (App::CellAddress address)
Protected Member Functions
void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint)
void contextMenuEvent (QContextMenuEvent *e)
bool edit (const QModelIndex &index, EditTrigger trigger, QEvent *event)
bool event (QEvent *event)
void mousePressEvent (QMouseEvent *event)
void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Protected Attributes
QAction * actionBind
QAction * actionCopy
QAction * actionCut
QAction * actionDel
QAction * actionMerge
QAction * actionPaste
QAction * actionSplit
boost::signals2::scoped_connection cellSpanChangedConnection
QMenu * contextMenu
QModelIndex currentEditIndex
Spreadsheet::Sheet * sheet
int tabCounter
Constructor & Destructor Documentation
SheetTableView()
SheetTableView::SheetTableView (QWidget * parent = nullptr) explicit
References actionBind, actionCopy, actionCut, actionDel, actionMerge, actionPaste, actionSplit, cellProperties(), draftgeoutils.intersections::connect(), contextMenu, copySelection(), cutSelection(), deleteSelection(), insertColumns(), insertColumnsAfter(), insertRows(), insertRowsAfter(), mergeCells(), onBind(), onConfSetup(), onRecompute(), pasteClipboard(), removeColumns(), removeRows(), and splitCell().
~SheetTableView()
SheetTableView::~SheetTableView ()
Member Function Documentation
cellProperties
void SheetTableView::cellProperties () protected slot
References selectedRanges(), and sheet.
Referenced by SheetTableView().
closeEditor()
void SheetTableView::closeEditor (QWidget * editor, QAbstractItemDelegate::EndEditHint hint) protected
commitData
void SheetTableView::commitData (QWidget * editor) protected slot
contextMenuEvent()
void SheetTableView::contextMenuEvent (QContextMenuEvent * e) protected
References actionBind, actionCopy, actionCut, actionDel, actionMerge, actionPaste, actionSplit, contextMenu, Spreadsheet::Sheet::isMergedCell(), selectedIndexesRaw(), selectedRanges(), and sheet.
copySelection
void SheetTableView::copySelection () slot
References selectedRanges().
Referenced by event(), SpreadsheetGui::SheetView::onMsg(), and SheetTableView().
cutSelection
void SheetTableView::cutSelection () slot
References selectedRanges().
Referenced by event(), SpreadsheetGui::SheetView::onMsg(), and SheetTableView().
deleteSelection
void SheetTableView::deleteSelection () slot
References Gui::Command::commitCommand(), Gui::Command::Doc, App::DocumentObject::getNameInDocument(), Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, selectedRanges(), and sheet.
Referenced by SpreadsheetGui::SheetView::deleteSelection(), event(), and SheetTableView().
edit() [1/2]
void SheetTableView::edit (const QModelIndex & index)
References currentEditIndex.
Referenced by PathScripts.PathToolLibraryEditor.CommandToolLibraryEdit::Activated().
edit() [2/2]
bool SheetTableView::edit (const QModelIndex & index, EditTrigger trigger, QEvent * event) protected
References currentEditIndex.
Referenced by PathScripts.PathToolLibraryEditor.CommandToolLibraryEdit::Activated().
event()
bool SheetTableView::event (QEvent * event) protected
References copySelection(), cutSelection(), deleteSelection(), event(), finishEditWithMove(), pasteClipboard(), Spreadsheet::Sheet::setCopyOrCutRanges(), and sheet.
Referenced by event().
finishEditWithMove
void SheetTableView::finishEditWithMove (int keyPressed, Qt::KeyboardModifiers modifiers, bool handleTabMotion = false) slot
References Spreadsheet::Sheet::getAnchor(), Spreadsheet::Sheet::getCell(), Spreadsheet::Sheet::getCells(), Spreadsheet::PropertySheet::getNonEmptyCells(), Spreadsheet::Sheet::getSpans(), Spreadsheet::Sheet::isMergedCell(), Spreadsheet::Cell::isUsed(), ModifyBlockSelection(), sheet, and tabCounter.
Referenced by SpreadsheetGui::SheetView::editingFinishedWithKey(), and event().
insertColumns
void SheetTableView::insertColumns () protected slot
References Gui::cmdAppObjectArgs(), Spreadsheet::columnName(), Gui::Command::commitCommand(), Gui::Command::Doc, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, and sheet.
Referenced by SheetTableView().
insertColumnsAfter
void SheetTableView::insertColumnsAfter () protected slot
References Gui::cmdAppObjectArgs(), Spreadsheet::columnName(), Gui::Command::commitCommand(), Gui::Command::Doc, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, and sheet.
Referenced by SheetTableView().
insertRows
void SheetTableView::insertRows () protected slot
References Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Gui::Command::Doc, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, Spreadsheet::rowName(), and sheet.
Referenced by SheetTableView().
insertRowsAfter
void SheetTableView::insertRowsAfter () protected slot
References Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Gui::Command::Doc, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, Spreadsheet::rowName(), and sheet.
Referenced by SheetTableView().
mergeCells
void SheetTableView::mergeCells () slot
References Gui::Application::commandManager(), Gui::Application::Instance, and Gui::CommandManager::runCommandByName().
Referenced by SheetTableView().
ModifyBlockSelection
void SheetTableView::ModifyBlockSelection (int targetRow, int targetColumn) slot
Referenced by finishEditWithMove().
mousePressEvent()
void SheetTableView::mousePressEvent (QMouseEvent * event) protected
References tabCounter.
onBind
void SheetTableView::onBind () protected slot
References selectedRanges(), and sheet.
Referenced by SheetTableView().
onConfSetup
void SheetTableView::onConfSetup () protected slot
References selectedRanges(), and sheet.
Referenced by SheetTableView().
onRecompute
void SheetTableView::onRecompute () protected slot
References Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Gui::Command::openCommand(), selectedRanges(), and sheet.
Referenced by SheetTableView().
pasteClipboard
void SheetTableView::pasteClipboard () slot
References Spreadsheet::Sheet::clear(), App::CellAddress::col(), App::Application::getActiveDocument(), App::GetApplication(), Spreadsheet::Sheet::getCells(), Spreadsheet::Sheet::getCopyOrCutRange(), Gui::getMainWindow(), Spreadsheet::PropertySheet::pasteCells(), App::Document::recompute(), App::CellAddress::row(), selectedRanges(), and sheet.
Referenced by event(), SpreadsheetGui::SheetView::onMsg(), and SheetTableView().
removeColumns
void SheetTableView::removeColumns () protected slot
References Gui::cmdAppObjectArgs(), Spreadsheet::columnName(), Gui::Command::commitCommand(), Gui::Command::Doc, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, and sheet.
Referenced by SheetTableView().
removeRows
void SheetTableView::removeRows () protected slot
References Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Gui::Command::Doc, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, Spreadsheet::rowName(), and sheet.
Referenced by SheetTableView().
selectedIndexesRaw()
QModelIndexList SheetTableView::selectedIndexesRaw () const
Referenced by contextMenuEvent(), and SpreadsheetGui::SheetView::selectedIndexesRaw().
selectedRanges()
std::vector< Range > SheetTableView::selectedRanges () const
References Spreadsheet::Sheet::getCells(), Spreadsheet::PropertySheet::hasSpan(), and sheet.
Referenced by cellProperties(), contextMenuEvent(), copySelection(), cutSelection(), deleteSelection(), onBind(), onConfSetup(), onRecompute(), pasteClipboard(), and SpreadsheetGui::SheetView::selectedRanges().
selectionChanged()
void SheetTableView::selectionChanged (const QItemSelection & selected, const QItemSelection & deselected) protected
References Gui::getMainWindow(), and Gui::MainWindow::updateActions().
Referenced by PathScripts.PathFeatureExtensionsGui.TaskPanelExtensionPage::toggleExtensionCorners().
setSheet()
void SheetTableView::setSheet (Spreadsheet::Sheet * _sheet)
References draftgeoutils.faces::bind(), Spreadsheet::Sheet::cellSpanChanged, cellSpanChangedConnection, Spreadsheet::Sheet::getColumnWidths(), Spreadsheet::Sheet::getRowHeights(), Spreadsheet::Sheet::getUsedCells(), Spreadsheet::Sheet::isMergedCell(), sheet, and updateCellSpan().
splitCell
void SheetTableView::splitCell () slot
References Gui::Application::commandManager(), Gui::Application::Instance, and Gui::CommandManager::runCommandByName().
Referenced by SheetTableView().
toHtml()
QString SheetTableView::toHtml () const
References Spreadsheet::Sheet::getCells(), Spreadsheet::Sheet::getColumnWidth(), Spreadsheet::PropertySheet::getNonEmptyCells(), Spreadsheet::Sheet::getSpans(), Spreadsheet::Sheet::isMergedCell(), and sheet.
Referenced by SpreadsheetGui::SheetView::print().
updateCellSpan
void SheetTableView::updateCellSpan (App::CellAddress address) protected slot
References Spreadsheet::Sheet::getSpans(), and sheet.
Referenced by setSheet().
Member Data Documentation
actionBind
QAction* SpreadsheetGui::SheetTableView::actionBind protected
Referenced by contextMenuEvent(), and SheetTableView().
actionCopy
QAction* SpreadsheetGui::SheetTableView::actionCopy protected
Referenced by contextMenuEvent(), and SheetTableView().
actionCut
QAction* SpreadsheetGui::SheetTableView::actionCut protected
Referenced by contextMenuEvent(), and SheetTableView().
actionDel
QAction* SpreadsheetGui::SheetTableView::actionDel protected
Referenced by contextMenuEvent(), and SheetTableView().
actionMerge
QAction* SpreadsheetGui::SheetTableView::actionMerge protected
Referenced by contextMenuEvent(), and SheetTableView().
actionPaste
QAction* SpreadsheetGui::SheetTableView::actionPaste protected
Referenced by contextMenuEvent(), and SheetTableView().
actionSplit
QAction* SpreadsheetGui::SheetTableView::actionSplit protected
Referenced by contextMenuEvent(), and SheetTableView().
cellSpanChangedConnection
boost::signals2::scoped_connection SpreadsheetGui::SheetTableView::cellSpanChangedConnection protected
Referenced by setSheet().
contextMenu
QMenu* SpreadsheetGui::SheetTableView::contextMenu protected
Referenced by contextMenuEvent(), and SheetTableView().
currentEditIndex
QModelIndex SpreadsheetGui::SheetTableView::currentEditIndex protected
Referenced by edit().
sheet
Spreadsheet::Sheet* SpreadsheetGui::SheetTableView::sheet protected
Referenced by cellProperties(), contextMenuEvent(), deleteSelection(), event(), finishEditWithMove(), insertColumns(), insertColumnsAfter(), insertRows(), insertRowsAfter(), onBind(), onConfSetup(), onRecompute(), pasteClipboard(), removeColumns(), removeRows(), selectedRanges(), setSheet(), TestSpreadsheetGui.SpreadsheetGuiCases::testCopySingleCell(), toHtml(), and updateCellSpan().
tabCounter
int SpreadsheetGui::SheetTableView::tabCounter protected
Referenced by finishEditWithMove(), and mousePressEvent().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Spreadsheet/Gui/SheetTableView.h
FreeCAD/src/Mod/Spreadsheet/Gui/SheetTableView.cpp