FreeCAD: femsolver.equationbase.ElectricforceViewProxy Class Reference
femsolver.equationbase.ElectricforceViewProxy Class Reference
Workbenches » Python workbenches » Fem
Public Member Functions
def getIcon (self)
Public Member Functions inherited from femsolver.equationbase.BaseViewProxy
def attach (self, vobj)
def getDefaultDisplayMode (self)
def getDisplayModes (self, obj)
def setDisplayMode (self, mode)
Member Function Documentation
getIcon()
def femsolver.equationbase.ElectricforceViewProxy.getIcon (self)
Referenced by ArchAxisSystem.AxisSystemTaskPanel.update(), ArchComponent.ComponentTaskPanel.update(), and ArchSectionPlane.SectionPlaneTaskPanel.update().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Fem/femsolver/equationbase.py