FreeCAD: SMDS_Position Class Reference
SMDS_Position Class Reference abstract
#include <SMDS_Position.hxx>
Public Member Functions
virtual int GetDim () const
virtual SMDS_TypeOfPosition GetTypeOfPosition () const =0
virtual ~SMDS_Position ()
Protected Member Functions
SMDS_Position ()
Constructor & Destructor Documentation
~SMDS_Position()
virtual SMDS_Position::~SMDS_Position () virtual
SMDS_Position()
SMDS_Position::SMDS_Position () protected
Member Function Documentation
GetDim()
int SMDS_Position::GetDim () const virtual
References GetTypeOfPosition().
Referenced by SMESH_MeshEditor::Smooth().
GetTypeOfPosition()
virtual SMDS_TypeOfPosition SMDS_Position::GetTypeOfPosition () const pure virtual
Implemented in SMDS_VertexPosition, SMDS_SpacePosition, SMDS_FacePosition, and SMDS_EdgePosition.
Referenced by SMESH_MesherHelper::AddTLinks(), NETGENPlugin_NETGEN_3D::Compute(), StdMeshers_Projection_2D::Compute(), NETGENPlugin_Mesher::FillNgMesh(), StdMeshers_ProjectionUtils::FindMatchingNodesOnFaces(), GetDim(), VISCOUS_3D::getFaceDir(), SMESH_MesherHelper::GetMediumNode(), SMESH_MesherHelper::GetMediumPos(), SMESH_Algo::GetMeshError(), SMESH_MesherHelper::GetNodeUV(), Prism_3D::TNode::GetPositionType(), SMESH_ProxyMesh::GetProxyNode(), SMESH_MesherHelper::IsReversedSubMesh(), SMESH::Controls::BelongToGeom::IsSatisfy(), SMESH_MeshEditor::QuadToTri(), and SMESH_MeshEditor::Remove().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_Position.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_Position.cpp