FreeCAD: Gui::Dialog::DlgCustomActionsImp Class Reference
Gui::Dialog::DlgCustomActionsImp Class Reference
This class implements the creation of user defined actions executing a recorded macro.
#include <DlgActionsImp.h>
Signals
void addMacroAction (const QByteArray &)
void modifyMacroAction (const QByteArray &)
void removeMacroAction (const QByteArray &)
Public Member Functions
DlgCustomActionsImp (QWidget *parent=0)
Constructs a DlgCustomActionsImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
~DlgCustomActionsImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::CustomizeActionPage
CustomizeActionPage (QWidget *parent=0)
Construction.
virtual ~CustomizeActionPage ()
Destruction.
Protected Slots
void on_actionListWidget_itemActivated (QTreeWidgetItem *i)
Enables/disables buttons for deletion.
void on_buttonAddAction_clicked ()
Adds a custom action.
void on_buttonChoosePixmap_clicked ()
Opens a iconview to select a pixmap.
void on_buttonRemoveAction_clicked ()
Deletes a custom action.
void on_buttonReplaceAction_clicked ()
Shows the setup of the action.
void onAddMacroAction (const QByteArray &)
void onModifyMacroAction (const QByteArray &)
void onRemoveMacroAction (const QByteArray &)
Protected Slots inherited from Gui::Dialog::CustomizeActionPage
virtual void onAddMacroAction (const QByteArray &)=0
virtual void onModifyMacroAction (const QByteArray &)=0
virtual void onRemoveMacroAction (const QByteArray &)=0
Protected Member Functions
void changeEvent (QEvent *e)
bool event (QEvent *e)
Trigger for reparent event.
void showEvent (QShowEvent *e)
Displays this page.
Protected Member Functions inherited from Gui::Dialog::CustomizeActionPage
bool event (QEvent *e)
Detailed Description
This class implements the creation of user defined actions executing a recorded macro.
It is possible to use these actions in own toolbars or commandbars.
See also
Gui::Action
MacroCommand
Command
Author
Werner Mayer
Constructor & Destructor Documentation
DlgCustomActionsImp()
DlgCustomActionsImp::DlgCustomActionsImp (QWidget * parent = 0)
Constructs a DlgCustomActionsImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
References App::GetApplication(), and App::Application::getUserMacroDir().
~DlgCustomActionsImp()
DlgCustomActionsImp::~DlgCustomActionsImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
addMacroAction
void Gui::Dialog::DlgCustomActionsImp::addMacroAction (const QByteArray &) signal
Referenced by event(), and on_buttonAddAction_clicked().
changeEvent()
void DlgCustomActionsImp::changeEvent (QEvent * e) protected virtual
Implements Gui::Dialog::CustomizeActionPage.
event()
bool DlgCustomActionsImp::event (QEvent * e) protected
Trigger for reparent event.
References addMacroAction(), draftgeoutils.intersections::connect(), modifyMacroAction(), and removeMacroAction().
Referenced by draftguitools.gui_edit.Edit::evaluate_menu_action().
modifyMacroAction
void Gui::Dialog::DlgCustomActionsImp::modifyMacroAction (const QByteArray &) signal
Referenced by event(), and on_buttonReplaceAction_clicked().
on_actionListWidget_itemActivated
void DlgCustomActionsImp::on_actionListWidget_itemActivated (QTreeWidgetItem * i) protected slot
Enables/disables buttons for deletion.
References Gui::BitmapFactory(), Gui::Application::commandManager(), Gui::CommandBase::getAccel(), Gui::CommandManager::getCommandByName(), Gui::CommandBase::getMenuText(), Gui::CommandBase::getPixmap(), Gui::MacroCommand::getScriptName(), Gui::CommandBase::getStatusTip(), Gui::CommandBase::getToolTipText(), Gui::CommandBase::getWhatsThis(), Gui::Application::Instance, and Gui::BitmapFactoryInst::pixmap().
on_buttonAddAction_clicked
void DlgCustomActionsImp::on_buttonAddAction_clicked () protected slot
Adds a custom action.
References Gui::CommandManager::addCommand(), addMacroAction(), Gui::Application::commandManager(), Gui::Application::Instance, Gui::CommandBase::setAccel(), Gui::CommandBase::setMenuText(), Gui::CommandBase::setPixmap(), Gui::MacroCommand::setScriptName(), Gui::CommandBase::setStatusTip(), Gui::CommandBase::setToolTipText(), and Gui::CommandBase::setWhatsThis().
on_buttonChoosePixmap_clicked
void DlgCustomActionsImp::on_buttonChoosePixmap_clicked () protected slot
Opens a iconview to select a pixmap.
References Gui::Dialog::IconDialog::currentItem().
on_buttonRemoveAction_clicked
void DlgCustomActionsImp::on_buttonRemoveAction_clicked () protected slot
Deletes a custom action.
References Gui::Application::commandManager(), Gui::CommandManager::getGroupCommands(), Gui::Application::Instance, Gui::CommandManager::removeCommand(), and removeMacroAction().
on_buttonReplaceAction_clicked
void DlgCustomActionsImp::on_buttonReplaceAction_clicked () protected slot
Shows the setup of the action.
References Gui::BitmapFactory(), Gui::Application::commandManager(), Gui::CommandBase::getAccel(), Gui::CommandBase::getAction(), Gui::CommandManager::getCommandByName(), Gui::CommandBase::getMenuText(), Gui::CommandBase::getPixmap(), Gui::CommandBase::getStatusTip(), Gui::CommandBase::getToolTipText(), Gui::CommandBase::getWhatsThis(), Gui::Application::Instance, modifyMacroAction(), Gui::BitmapFactoryInst::pixmap(), Gui::CommandBase::setAccel(), Gui::CommandBase::setMenuText(), Gui::CommandBase::setPixmap(), Gui::MacroCommand::setScriptName(), Gui::CommandBase::setStatusTip(), Gui::CommandBase::setToolTipText(), and Gui::CommandBase::setWhatsThis().
onAddMacroAction
void DlgCustomActionsImp::onAddMacroAction (const QByteArray &) protected slot
onModifyMacroAction
void DlgCustomActionsImp::onModifyMacroAction (const QByteArray &) protected slot
onRemoveMacroAction
void DlgCustomActionsImp::onRemoveMacroAction (const QByteArray &) protected slot
removeMacroAction
void Gui::Dialog::DlgCustomActionsImp::removeMacroAction (const QByteArray &) signal
Referenced by event(), and on_buttonRemoveAction_clicked().
showEvent()
void DlgCustomActionsImp::showEvent (QShowEvent * e) protected
Displays this page.
If no macros were found a message box appears.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgActionsImp.h
Sources/FreeCAD/src/Gui/DlgActionsImp.cpp