FreeCAD: SMESH::Controls::CoincidentElements Class Reference
SMESH::Controls::CoincidentElements Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
CoincidentElements ()
virtual bool IsSatisfy (long theElementId)
virtual void SetMesh (const SMDS_Mesh *theMesh)
Public Member Functions inherited from SMESH::Controls::Predicate
virtual SMDSAbs_ElementType GetType () const =0
Public Member Functions inherited from SMESH::Controls::Functor
~Functor ()
Constructor & Destructor Documentation
CoincidentElements()
CoincidentElements::CoincidentElements ()
References SMESH::Controls::NumericalFunctor::myMesh.
Member Function Documentation
IsSatisfy()
bool CoincidentElements::IsSatisfy (long theElementId) virtual
Implements SMESH::Controls::Predicate.
References SMDS_Mesh::FindElement(), SMDS_MeshElement::GetNode(), SMESH::Controls::Length2D::GetType(), SMESH::Controls::NumericalFunctor::myMesh, and SMDS_MeshElement::NbNodes().
SetMesh()
void CoincidentElements::SetMesh (const SMDS_Mesh * theMesh) virtual
Implements SMESH::Controls::Functor.
References SMESH::Controls::NumericalFunctor::myMesh.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp