FreeCAD: SMESH_TLink Struct Reference
SMESH_TLink Struct Reference
A sorted pair of nodes.
#include <SMESH_TypeDefs.hxx>
Public Member Functions
const SMDS_MeshNode * node1 () const
const SMDS_MeshNode * node2 () const
SMESH_TLink (const NLink &link)
SMESH_TLink (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2)
Detailed Description
A sorted pair of nodes.
Constructor & Destructor Documentation
SMESH_TLink() [1/2]
SMESH_TLink::SMESH_TLink (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2)
References SMDS_MeshElement::GetID().
SMESH_TLink() [2/2]
SMESH_TLink::SMESH_TLink (const NLink & link)
Member Function Documentation
node1()
const SMDS_MeshNode* SMESH_TLink::node1 () const
Referenced by StdMeshers_Import_1D2D::Evaluate(), SMESH_ElementSearcherImpl::findOuterBoundary(), SMESH_Algo::GetMeshError(), and StdMeshers_Quadrangle_2D::smooth().
node2()
const SMDS_MeshNode* SMESH_TLink::node2 () const
Referenced by StdMeshers_Import_1D2D::Evaluate(), SMESH_ElementSearcherImpl::findOuterBoundary(), SMESH_Algo::GetMeshError(), and StdMeshers_Quadrangle_2D::smooth().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_TypeDefs.hxx