FreeCAD: GCS::ConstraintCurveValue Class Reference
GCS::ConstraintCurveValue Class Reference
#include <Constraints.h>
Public Member Functions
ConstraintCurveValue (Point &p, double *pcoord, Curve &crv, double *u)
ConstraintCurveValue: solver constraint that ties parameter value with point coordinates, according to curve's parametric equation.
virtual double error ()
virtual ConstraintType getTypeId ()
virtual double grad (double *)
virtual double maxStep (MAP_pD_D &dir, double lim=1.)
virtual void rescale (double coef=1.)
~ConstraintCurveValue ()
Public Member Functions inherited from GCS::Constraint
Constraint ()
int findParamInPvec (double *param)
int getTag ()
bool isDriving () const
VEC_pD params ()
void redirectParams (MAP_pD_pD redirectionmap)
void revertParams ()
void setDriving (bool isdriving)
void setTag (int tagId)
virtual ~Constraint ()
Constructor & Destructor Documentation
ConstraintCurveValue()
GCS::ConstraintCurveValue::ConstraintCurveValue (Point & p, double * pcoord, Curve & crv, double * u)
ConstraintCurveValue: solver constraint that ties parameter value with point coordinates, according to curve's parametric equation.
Parameters
p : endpoint to be constrained
pcoord : pointer to point coordinate to be constrained. Must be either p.x or p.y
crv : the curve (crv->Value() must be functional)
u : pointer to u parameter corresponding to the point
References GCS::Curve::Copy(), GCS::Curve::PushOwnParams(), and rescale().
~ConstraintCurveValue()
GCS::ConstraintCurveValue::~ConstraintCurveValue ()
Member Function Documentation
error()
double GCS::ConstraintCurveValue::error () virtual
Reimplemented from GCS::Constraint.
Referenced by femmesh.gmshtools.GmshTools::read_and_set_new_mesh(), FreeCADInit.FCADLogger::report(), and femmesh.gmshtools.GmshTools::run_gmsh_with_geo().
getTypeId()
ConstraintType GCS::ConstraintCurveValue::getTypeId (void) virtual
Reimplemented from GCS::Constraint.
References GCS::CurveValue.
grad()
double GCS::ConstraintCurveValue::grad (double * param) virtual
Reimplemented from GCS::Constraint.
References GCS::Constraint::findParamInPvec().
maxStep()
double GCS::ConstraintCurveValue::maxStep (MAP_pD_D & dir, double lim = 1.) virtual
Reimplemented from GCS::Constraint.
rescale()
void GCS::ConstraintCurveValue::rescale (double coef = 1.) virtual
Reimplemented from GCS::Constraint.
Referenced by ConstraintCurveValue().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Constraints.h
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Constraints.cpp