FreeCAD: StartGui::DlgStartPreferencesImp Class Reference
StartGui::DlgStartPreferencesImp Class Reference
#include <DlgStartPreferencesImp.h>
Public Member Functions
DlgStartPreferencesImp (QWidget *parent=nullptr)
Constructs a DlgStartPreferencesImp which is a child of 'parent'.
~DlgStartPreferencesImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void loadSettings ()
void saveSettings ()
virtual void changeEvent (QEvent *e)=0
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Constructor & Destructor Documentation
DlgStartPreferencesImp()
DlgStartPreferencesImp::DlgStartPreferencesImp (QWidget * parent = nullptr)
Constructs a DlgStartPreferencesImp which is a child of 'parent'.
References Gui::Application::Instance, Gui::Application::workbenches(), Gui::Application::workbenchIcon(), and Gui::Application::workbenchMenuText().
~DlgStartPreferencesImp()
DlgStartPreferencesImp::~DlgStartPreferencesImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void DlgStartPreferencesImp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
loadSettings()
void DlgStartPreferencesImp::loadSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References App::Application::Config(), App::GetApplication(), and App::Application::GetParameterGroupByPath().
saveSettings()
void DlgStartPreferencesImp::saveSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), and App::Application::GetParameterGroupByPath().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Start/Gui/DlgStartPreferencesImp.h
FreeCAD/src/Mod/Start/Gui/DlgStartPreferencesImp.cpp