FreeCAD: DrawSketchHandlerFillet Class Reference
DrawSketchHandlerFillet Class Reference
Public Types
enum SelectMode { STATUS_SEEK_First, STATUS_SEEK_Second }
Public Member Functions
virtual void activated (ViewProviderSketch *)
DrawSketchHandlerFillet ()
virtual void mouseMove (Base::Vector2d onSketchPos)
virtual bool pressButton (Base::Vector2d onSketchPos)
virtual bool releaseButton (Base::Vector2d onSketchPos)
virtual ~DrawSketchHandlerFillet ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::none, bool createowncommand=true)
virtual void deactivated (ViewProviderSketch *)
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual void quit (void)
virtual void registerPressedKey (bool, int)
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Attributes
int firstCurve
Base::Vector2d firstPos
SelectMode Mode
Protected Attributes inherited from SketcherGui::DrawSketchHandler
QCursor actCursor
QPixmap actCursorPixmap
QCursor oldCursor
ViewProviderSketch * sketchgui
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
void addCursorTail (std::vector< QPixmap > &pixmaps)
void applyCursor (QCursor &newCursor)
void applyCursor (void)
qreal devicePixelRatio ()
unsigned long getCrosshairColor ()
void setCrosshairColor ()
void setCrosshairCursor (const char *svgName)
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
Sets a cursor for 3D inventor view.
void setSvgCursor (const QString &svgName, int x, int y, const std::map< unsigned long, unsigned long > &colorMapping=std::map< unsigned long, unsigned long >())
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
void unsetCursor (void)
Member Enumeration Documentation
SelectMode
enum DrawSketchHandlerFillet::SelectMode
Enumerator
STATUS_SEEK_First
STATUS_SEEK_Second
Constructor & Destructor Documentation
DrawSketchHandlerFillet()
DrawSketchHandlerFillet::DrawSketchHandlerFillet ()
~DrawSketchHandlerFillet()
virtual DrawSketchHandlerFillet::~DrawSketchHandlerFillet () virtual
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
activated()
virtual void DrawSketchHandlerFillet::activated (ViewProviderSketch *) virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References Gui::SelectionSingleton::addSelectionGate(), Gui::ViewProviderDocumentObject::getObject(), Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), SketcherGui::DrawSketchHandler::setCrosshairCursor(), and SketcherGui::DrawSketchHandler::sketchgui.
mouseMove()
virtual void DrawSketchHandlerFillet::mouseMove (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
pressButton()
virtual bool DrawSketchHandlerFillet::pressButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
releaseButton()
virtual bool DrawSketchHandlerFillet::releaseButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Base::Console(), Sketcher::end, Base::ConsoleSingleton::Error(), firstCurve, firstPos, Base::Vector3< _Precision >::GetAngle(), Base::Persistence::getClassTypeId(), Sketcher::GeometryFacade::getConstruction(), Sketcher::SketchObject::getDirectlyCoincidentPoints(), App::DocumentObject::getDocument(), Part::GeomLineSegment::getEndPoint(), Sketcher::SketchObject::getGeometry(), Sketcher::SketchObject::getGeoVertexIndex(), SketcherGui::DrawSketchHandler::getHighestCurveIndex(), Gui::getMainWindow(), App::Document::getName(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), SketcherGui::ViewProviderSketch::getPreselectCurve(), SketcherGui::ViewProviderSketch::getPreselectPoint(), SketcherGui::ViewProviderSketch::getSketchObject(), Part::GeomLineSegment::getStartPoint(), Base::Persistence::getTypeId(), Base::Type::isDerivedFrom(), Base::Vector3< _Precision >::Length(), Mode, Sketcher::none, Gui::Command::openCommand(), SketcherGui::ViewProviderSketch::purgeHandler(), draftutils.translate::QT_TRANSLATE_NOOP, Gui::Selection(), SketcherGui::DrawSketchHandler::sketchgui, Sketcher::start, STATUS_SEEK_First, STATUS_SEEK_Second, Part::suggestFilletRadius(), SketcherGui::tryAutoRecompute(), SketcherGui::tryAutoRecomputeIfNotSolve(), Base::Vector2d::x, and Base::Vector2d::y.
Member Data Documentation
firstCurve
int DrawSketchHandlerFillet::firstCurve protected
Referenced by releaseButton().
firstPos
Base::Vector2d DrawSketchHandlerFillet::firstPos protected
Referenced by releaseButton().
Mode
SelectMode DrawSketchHandlerFillet::Mode protected
Referenced by releaseButton().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/Gui/CommandCreateGeo.cpp