FreeCAD: ArchRoof Namespace Reference
ArchRoof Namespace Reference
Workbenches » Python workbenches » Arch
The Roof object and tools.
Functions
def adjust_list_len (lst, newLn, val)
def face_from_points (ptLst)
def find_inters (edge1, edge2, infinite1=True, infinite2=True)
def makeRoof (baseobj=None, facenr=0, angles=[45.0], run=[250.0], idrel=[-1], thickness=[50.0], overhang=[100.0], name="Roof")
Detailed Description
The Roof object and tools.
This module provides tools to build Roof objects. Roofs are built from a closed contour and a series of slopes.
Function Documentation
adjust_list_len()
def ArchRoof.adjust_list_len (lst, newLn, val)
Returns a clone of lst with length newLn, val is appended if required
Referenced by makeRoof().
face_from_points()
def ArchRoof.face_from_points (ptLst)
References DraftVecUtils.removeDoubles().
Referenced by makeRoof().
find_inters()
def ArchRoof.find_inters (edge1, edge2, infinite1 = True, infinite2 = True)
Future wrapper for DraftGeomUtils.findIntersection. The function now
contains a modified copy of getLineIntersections from that function.
References DraftVecUtils.isNull(), and draftgeoutils.general.isPtOnEdge().
Referenced by makeRoof().
makeRoof()
def ArchRoof.makeRoof (baseobj = None, facenr = 0, angles = [45.0], run = [250.0], idrel = [-1], thickness = [50.0], overhang = [100.0], name = "Roof")
makeRoof(baseobj, [facenr], [angle], [name]): Makes a roof based on
a closed wire or an object.
You can provide a list of angles, run, idrel, thickness, overhang for
each edge in the wire to define the roof shape. The default for angle is
45 and the list is automatically completed to match the number of edges
in the wire.
If the base object is a solid the roof uses its shape.
References adjust_list_len(), DraftVecUtils.angle(), ArchComponent.Component.computeAreas(), face_from_points(), find_inters(), draftgeoutils.general.isNull(), ArchComponent.Component.onDocumentRestored(), draftutils.translate.QT_TRANSLATE_NOOP, and draftgeoutils.faces.removeSplitter().