FreeCAD: Gui::Dialog::DlgSettingsDocumentImp Class Reference
Gui::Dialog::DlgSettingsDocumentImp Class Reference
The DlgSettingsDocumentImp class implements a preference page to change settings for the document.
#include <DlgSettingsDocumentImp.h>
Public Member Functions
DlgSettingsDocumentImp (QWidget *parent=0)
Constructs a DlgSettingsDocumentImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
void loadSettings ()
void saveSettings ()
~DlgSettingsDocumentImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=0)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Slots
void onLicenseTypeChanged (int index)
Set the correct URL depending on the license type.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
Detailed Description
The DlgSettingsDocumentImp class implements a preference page to change settings for the document.
Author
Jürgen Riegel
Constructor & Destructor Documentation
DlgSettingsDocumentImp()
DlgSettingsDocumentImp::DlgSettingsDocumentImp (QWidget * parent = 0)
Constructs a DlgSettingsDocumentImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
References draftgeoutils.intersections::connect(), and onLicenseTypeChanged().
~DlgSettingsDocumentImp()
DlgSettingsDocumentImp::~DlgSettingsDocumentImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void DlgSettingsDocumentImp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
loadSettings()
void DlgSettingsDocumentImp::loadSettings () virtual
Implements Gui::Dialog::PreferencePage.
onLicenseTypeChanged
void DlgSettingsDocumentImp::onLicenseTypeChanged (int index) protected slot
Set the correct URL depending on the license type.
Referenced by DlgSettingsDocumentImp().
saveSettings()
void DlgSettingsDocumentImp::saveSettings () virtual
Implements Gui::Dialog::PreferencePage.
References Gui::AutoSaver::instance(), and Gui::AutoSaver::setTimeout().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgSettingsDocumentImp.h
Sources/FreeCAD/src/Gui/DlgSettingsDocumentImp.cpp