FreeCAD: Mesh::Importer Class Reference
Mesh::Importer Class Reference
#include <Importer.h>
Public Member Functions
Importer (App::Document *)
void load (const std::string &fileName)
~Importer ()=default
Constructor & Destructor Documentation
Importer()
Importer::Importer (App::Document * doc)
~Importer()
Mesh::Importer::~Importer () default
Member Function Documentation
load()
void Importer::load (const std::string & fileName)
References MeshCore::Material::binding, MeshCore::Material::diffuseColor, MeshCore::MeshIO::PER_FACE, MeshCore::MeshIO::PER_VERTEX, and App::DocumentObject::purgeTouched().
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::loadDefaults(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/Importer.h
FreeCAD/src/Mod/Mesh/App/Importer.cpp