FreeCAD: Spreadsheet Namespace Reference
Spreadsheet Namespace Reference
Classes
class Cell
class DisplayUnit
class Module
class PropertyColumnWidths
class PropertyColumnWidthsPy
The python export class for PropertyColumnWidths.
class PropertyRowHeights
class PropertyRowHeightsPy
The python export class for PropertyRowHeights.
class PropertySheet
class PropertySheetPy
The python export class for PropertySheet.
class PropertySpreadsheetQuantity
Spreadsheet quantity property This is a property for quantities, and unlike its ancestor implements Copy() and Paste() methods.
class Sheet
class SheetObserver
class SheetPy
The python export class for Sheet.
Typedefs
typedef App::FeaturePythonT< Sheet > SheetPython
Functions
SpreadsheetExport std::string columnName (int col)
Encode col as a string.
SpreadsheetExport void createRectangles (std::set< std::pair< int, int > > &cells, std::map< std::pair< int, int >, std::pair< int, int > > &rectangles)
PyObject * initModule ()
SpreadsheetExport std::string quote (const std::string &input)
SpreadsheetExport std::string rowName (int row)
Encode row as a string.
SpreadsheetExport std::string unquote (const std::string &input)
Typedef Documentation
SheetPython
typedef App::FeaturePythonT<Sheet> Spreadsheet::SheetPython
Function Documentation
columnName()
std::string Spreadsheet::columnName (int col)
Encode col as a string.
Parameters
col Column given as a 0-based column position.
Returns
String with column position, with "A" being the first column, "B" being the second and so on.
Referenced by SpreadsheetGui::SheetTableView::insertColumns(), SpreadsheetGui::SheetTableView::removeColumns(), and Spreadsheet::PropertyColumnWidths::Save().
createRectangles()
void Spreadsheet::createRectangles (std::set< std::pair< int, int > > & cells, std::map< std::pair< int, int >, std::pair< int, int > > & rectangles)
Referenced by SpreadsheetGui::SheetTableView::selectedRanges().
initModule()
PyObject* Spreadsheet::initModule ()
quote()
std::string Spreadsheet::quote (const std::string & input)
rowName()
std::string Spreadsheet::rowName (int row)
Encode row as a string.
Parameters
row Row given as a 0-based row position.
Returns
String with row position, with "1" being the first row.
Referenced by SpreadsheetGui::SheetTableView::insertRows(), SpreadsheetGui::SheetTableView::removeRows(), and Spreadsheet::PropertyRowHeights::Save().
unquote()
std::string Spreadsheet::unquote (const std::string & input)