FreeCAD: MeshGui::RemoveComponentsDialog Class Reference
MeshGui::RemoveComponentsDialog Class Reference
Embed the panel into a dialog.
#include <RemoveComponents.h>
Public Member Functions
void reject ()
RemoveComponentsDialog (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~RemoveComponentsDialog ()
Detailed Description
Embed the panel into a dialog.
Constructor & Destructor Documentation
RemoveComponentsDialog()
RemoveComponentsDialog::RemoveComponentsDialog (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
References draftgeoutils.intersections::connect().
~RemoveComponentsDialog()
RemoveComponentsDialog::~RemoveComponentsDialog ()
Member Function Documentation
reject()
void RemoveComponentsDialog::reject (void)
References MeshGui::RemoveComponents::reject().
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/Gui/RemoveComponents.h
FreeCAD/src/Mod/Mesh/Gui/RemoveComponents.cpp