FreeCAD: Gui::ViewerEventFilter Class Reference
Gui::ViewerEventFilter Class Reference
Public Member Functions
bool eventFilter (QObject *obj, QEvent *event)
ViewerEventFilter ()
~ViewerEventFilter ()
Detailed Description
As ProgressBar has no chance to control the incoming Qt events of Quarter so we need to stop the event handling to prevent the scenegraph from being selected or deselected while the progress bar is running.
Constructor & Destructor Documentation
ViewerEventFilter()
Gui::ViewerEventFilter::ViewerEventFilter ()
~ViewerEventFilter()
Gui::ViewerEventFilter::~ViewerEventFilter ()
Member Function Documentation
eventFilter()
bool Gui::ViewerEventFilter::eventFilter (QObject * obj, QEvent * event)
References Spaceball::ButtonEvent::ButtonEventType, Base::Console(), Gui::View3DInventorViewer::ewgtsDisabled, Gui::View3DInventorViewer::ewgtsNeedTuning, Gui::View3DInventorViewer::ewgtsTuned, Base::SequencerBase::isBlocking(), Base::SequencerBase::isRunning(), Base::ConsoleSingleton::Log(), Spaceball::MotionEvent::MotionEventType, Base::Sequencer(), and Base::ConsoleSingleton::Warning().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/View3DInventorViewer.cpp