FreeCAD: Gui::TextEditor Class Reference
Gui::TextEditor Class Reference
#include <TextEdit.h>
Public Member Functions
void lineNumberAreaPaintEvent (QPaintEvent *)
int lineNumberAreaWidth ()
void OnChange (Base::Subject< const char * > &rCaller, const char *rcReason)
Sets the font, font size and tab size of the editor.
void setSyntaxHighlighter (SyntaxHighlighter *)
TextEditor (QWidget *parent=0)
Constructs a TextEditor which is a child of 'parent' and does the syntax highlighting for the Python language.
~TextEditor ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::TextEdit
TextEdit (QWidget *parent=0)
Constructs a TextEdit which is a child of 'parent'.
virtual ~TextEdit ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::WindowParameter
ParameterGrp::handle getWindowParameter (void)
return the parameter group of this window
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason)
bool setGroupName (const char *name)
Sets the group of the window to name.
WindowParameter (const char *name)
virtual ~WindowParameter ()
Protected Member Functions
virtual void drawMarker (int line, int x, int y, QPainter *)
QWidget * getMarker () const
void keyPressEvent (QKeyEvent *e)
void paintEvent (QPaintEvent *e)
Draw a beam in the line where the cursor is.
void resizeEvent (QResizeEvent *e)
Protected Member Functions inherited from Gui::TextEdit
void keyPressEvent (QKeyEvent *)
Set the approproriate item of the completion box or hide it, if needed.
Friends
class SyntaxHighlighter
Additional Inherited Members
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter (void)
get the parameters
Constructor & Destructor Documentation
TextEditor()
TextEditor::TextEditor (QWidget * parent = 0)
Constructs a TextEditor which is a child of 'parent' and does the syntax highlighting for the Python language.
References Base::Subject< _MessageType >::Attach(), draftgeoutils.intersections::connect(), Gui::WindowParameter::getWindowParameter(), ParameterGrp::NotifyAll(), and ParameterGrp::SetInt().
~TextEditor()
TextEditor::~TextEditor ()
Destroys the object and frees any allocated resources.
References Base::Subject< _MessageType >::Detach(), and Gui::WindowParameter::getWindowParameter().
Member Function Documentation
drawMarker()
void TextEditor::drawMarker (int line, int x, int y, QPainter * p) protected virtual
Reimplemented in Gui::PythonEditor.
Referenced by lineNumberAreaPaintEvent().
getMarker()
QWidget* Gui::TextEditor::getMarker () const protected
Referenced by Gui::PythonEditor::hideDebugMarker(), Gui::PythonEditor::showDebugMarker(), and Gui::PythonEditor::toggleBreakpoint().
keyPressEvent()
void TextEditor::keyPressEvent (QKeyEvent * e) protected
References ParameterGrp::GetBool(), ParameterGrp::GetInt(), Gui::WindowParameter::getWindowParameter(), and Gui::TextEdit::keyPressEvent().
lineNumberAreaPaintEvent()
void TextEditor::lineNumberAreaPaintEvent (QPaintEvent * event)
References drawMarker().
Referenced by Gui::LineMarker::paintEvent().
lineNumberAreaWidth()
int TextEditor::lineNumberAreaWidth ()
References Gui::QtTools::horizontalAdvance().
Referenced by OnChange(), resizeEvent(), and Gui::LineMarker::sizeHint().
OnChange()
void TextEditor::OnChange (Base::Subject< const char * > & rCaller, const char * rcReason)
Sets the font, font size and tab size of the editor.
References Gui::TextEditorP::colormap, ParameterGrp::GetASCII(), ParameterGrp::GetBool(), ParameterGrp::GetInt(), ParameterGrp::GetUnsigned(), Gui::WindowParameter::getWindowParameter(), Gui::QtTools::horizontalAdvance(), lineNumberAreaWidth(), and Gui::SyntaxHighlighter::setColor().
paintEvent()
void TextEditor::paintEvent (QPaintEvent * e) protected
Draw a beam in the line where the cursor is.
resizeEvent()
void TextEditor::resizeEvent (QResizeEvent * e) protected
References lineNumberAreaWidth().
setSyntaxHighlighter()
void TextEditor::setSyntaxHighlighter (SyntaxHighlighter * sh)
Referenced by Gui::PythonEditor::PythonEditor().
Friends And Related Function Documentation
SyntaxHighlighter
friend class SyntaxHighlighter friend
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/TextEdit.h
Sources/FreeCAD/src/Gui/TextEdit.cpp