FreeCAD: Import::ImportOCAFAssembly Class Reference
Import::ImportOCAFAssembly Class Reference
#include <ImportOCAFAssembly.h>
Public Member Functions
ImportOCAFAssembly (Handle(TDocStd_Document) h, App::Document *d, const std::string &name, App::DocumentObject *target)
void loadAssembly ()
void loadShapes ()
virtual ~ImportOCAFAssembly ()
Protected Member Functions
std::string getName (const TDF_Label &label)
Protected Attributes
App::DocumentObject * targetObj
Constructor & Destructor Documentation
ImportOCAFAssembly()
ImportOCAFAssembly::ImportOCAFAssembly (Handle(TDocStd_Document) h, App::Document * d, const std::string & name, App::DocumentObject * target)
~ImportOCAFAssembly()
ImportOCAFAssembly::~ImportOCAFAssembly () virtual
Member Function Documentation
getName()
std::string ImportOCAFAssembly::getName (const TDF_Label & label) protected
loadAssembly()
void ImportOCAFAssembly::loadAssembly ()
References loadShapes().
loadShapes()
void ImportOCAFAssembly::loadShapes ()
References loadShapes().
Referenced by loadAssembly(), and loadShapes().
Member Data Documentation
targetObj
App::DocumentObject* Import::ImportOCAFAssembly::targetObj protected
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Import/App/ImportOCAFAssembly.h
FreeCAD/src/Mod/Import/App/ImportOCAFAssembly.cpp