FreeCAD: TechDrawGui::TaskActiveView Class Reference
TechDrawGui::TaskActiveView Class Reference
#include <TaskActiveView.h>
Public Member Functions
virtual bool accept ()
void enableTaskButtons (bool b)
virtual bool reject ()
void saveButtons (QPushButton *btnOK, QPushButton *btnCancel)
TaskActiveView (TechDraw::DrawPage *pageFeat)
void updateTask ()
~TaskActiveView ()
Protected Member Functions
void blockButtons (bool b)
void changeEvent (QEvent *e)
TechDraw::DrawViewSymbol * createActiveView (void)
void setUiPrimary (void)
Constructor & Destructor Documentation
TaskActiveView()
TaskActiveView::TaskActiveView (TechDraw::DrawPage * pageFeat)
References Base::Unit::Length, and setUiPrimary().
~TaskActiveView()
TaskActiveView::~TaskActiveView ()
Member Function Documentation
accept()
bool TaskActiveView::accept (void) virtual
References Gui::Command::commitCommand(), createActiveView(), Gui::Command::Gui, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, App::DocumentObject::recomputeFeature(), and Gui::Command::updateActive().
Referenced by TechDrawGui::TaskDlgActiveView::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
blockButtons()
void TaskActiveView::blockButtons (bool b) protected
changeEvent()
void TaskActiveView::changeEvent (QEvent * e) protected
createActiveView()
TechDraw::DrawViewSymbol * TaskActiveView::createActiveView (void) protected
References Base::Console(), TechDrawGui::Grabber3d::copyActiveViewToSvgFile(), Base::ConsoleSingleton::Error(), Base::Tools::escapeEncodeFilename(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), App::Document::getUniqueObjectName(), and Base::Tools::toStdString().
Referenced by accept().
enableTaskButtons()
void TaskActiveView::enableTaskButtons (bool b)
reject()
bool TaskActiveView::reject (void) virtual
References Gui::Command::Gui.
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), TechDrawGui::TaskDlgActiveView::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
saveButtons()
void TaskActiveView::saveButtons (QPushButton * btnOK, QPushButton * btnCancel)
Referenced by TechDrawGui::TaskDlgActiveView::modifyStandardButtons().
setUiPrimary()
void TaskActiveView::setUiPrimary (void) protected
Referenced by TaskActiveView().
updateTask()
void TaskActiveView::updateTask ()
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/TaskActiveView.h
FreeCAD/src/Mod/TechDraw/Gui/TaskActiveView.cpp