FreeCAD: Gui::SoFCColorGradient Class Reference
Gui::SoFCColorGradient Class Reference
#include <SoFCColorGradient.h>
Public Member Functions
void customize (SoFCColorBarBase *)
Opens a dialog to customize the current settings of the color gradient bar.
App::Color getColor (float fVal) const
Returns the associated color to the value fVal.
const char * getColorBarName () const
Returns the name of the color bar.
float getMaxValue () const
Returns the current maximum of the parameter range.
float getMinValue () const
Returns the current minimum of the parameter range.
bool isVisible (float fVal) const
Returns always true if the gradient is in mode to show colors to arbitrary values of fVal, otherwise true is returned if fVal is within the specified parameter range, if not false is returned.
void setOutsideGrayed (bool bVal)
Sets whether values outside the range should be in gray,.
void setRange (float fMin, float fMax, int prec=3)
Sets the range of the colorbar from the maximum fMax to the minimum fMin.
SoFCColorGradient ()
Public Member Functions inherited from Gui::SoFCColorBarBase
virtual void customize (SoFCColorBarBase *)=0
Opens a dialog to customize the current settings of the color bar.
virtual App::Color getColor (float fVal) const =0
Returns the associated color to the value fVal.
virtual const char * getColorBarName () const =0
Returns the name of the color bar.
virtual float getMaxValue () const =0
Returns the current maximum of the parameter range.
virtual float getMinValue () const =0
Returns the current minimum of the parameter range.
virtual void GLRenderBelowPath (SoGLRenderAction *action)
virtual bool isVisible (float fVal) const =0
Returns always true if the color bar is in mode to show colors to arbitrary values of fVal, otherwise true is returned if fVal is within the specified parameter range, if not false is returned.
virtual void setOutsideGrayed (bool bVal)=0
Sets whether values outside the range should be in gray,.
virtual void setRange (float fMin, float fMax, int prec=3)=0
Sets the range of the colorbar from the maximum fMax to the minimum fMin.
virtual void triggerChange (SoFCColorBarBase *base)
Forward a triggered change.
virtual Color getColor (float fVal) const =0
Static Public Member Functions
static void finish ()
static void initClass ()
Static Public Member Functions inherited from Gui::SoFCColorBarBase
static void finish ()
static void initClass ()
Protected Member Functions
std::vector< float > getMarkerValues (float fMin, float fMax, int count) const
Returns a list of count labels within the range [fMin, fMax].
void rebuildGradient ()
Rebuild the gradient bar.
void setColorModel (std::size_t index)
Sets the color model of the underlying color gradient to index.
void setColorStyle (App::ColorBarStyle tStyle)
Sets the color style of the underlying color gradient to tStyle.
void setViewportSize (const SbVec2s &size)
Sets the current viewer size this color gradient is embedded into, to recalculate its new position.
virtual ~SoFCColorGradient ()
Protected Member Functions inherited from Gui::SoFCColorBarBase
float getBoundingWidth (const SbVec2s &size)
Returns the width of the color bar and labels.
float getBounds (const SbVec2s &size, float &fMinX, float &fMinY, float &fMaxX, float &fMaxY)
Computes the dimensions of the color bar and labels in coordinates with respect to the defined height of the camera.
void setModified ()
Mark the object as modified.
virtual void setViewportSize (const SbVec2s &size)=0
Sets the current viewer size to recalculate the new position.
SoFCColorBarBase ()
virtual ~SoFCColorBarBase ()
Protected Member Functions inherited from App::ValueFloatToRGB
ValueFloatToRGB ()=default
virtual ~ValueFloatToRGB ()=default
Constructor & Destructor Documentation
SoFCColorGradient()
SoFCColorGradient::SoFCColorGradient ()
Constructor.
References App::FLOW.
~SoFCColorGradient()
SoFCColorGradient::~SoFCColorGradient () protected virtual
Destructor.
Member Function Documentation
customize()
void SoFCColorGradient::customize (SoFCColorBarBase * parentNode) virtual
Opens a dialog to customize the current settings of the color gradient bar.
Implements Gui::SoFCColorBarBase.
References Gui::MainWindow::activeWindow(), Gui::Dialog::DlgSettingsColorGradientImp::colorModelChanged(), draftgeoutils.intersections::connect(), App::ColorGradientProfile::fMax, App::ColorGradientProfile::fMin, Gui::getMainWindow(), Gui::Dialog::DlgSettingsColorGradientImp::getProfile(), App::ColorGradientProfile::isEqual(), Gui::Dialog::DlgSettingsColorGradientImp::numberOfDecimals(), draftgeoutils.general::precision(), rebuildGradient(), Gui::Dialog::DlgSettingsColorGradientImp::setNumberOfDecimals(), Gui::Dialog::DlgSettingsColorGradientImp::setProfile(), setRange(), and Gui::SoFCColorBarBase::triggerChange().
finish()
void SoFCColorGradient::finish (void) static
Referenced by drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), draftguitools.gui_shapestrings.ShapeString::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_split.Split::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_edit.Edit::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_selectplane.Draft_SelectPlane::checkSelection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_labels.Label::create(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_shapestrings.ShapeString::createObject(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::escape(), Gui::SoFCDB::finish(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_arcs.Arc_3Points::getPoint(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_fillets.Fillet::numericRadius(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickAlign(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickAuto(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickCenter(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickFront(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickMove(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickPrevious(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickSide(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickTop(), draftguitools.gui_array_simple.Array::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
getColor()
App::Color Gui::SoFCColorGradient::getColor (float fVal) const virtual
Returns the associated color to the value fVal.
Implements Gui::SoFCColorBarBase.
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::getPrefColor(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::setValues().
getColorBarName()
const char * Gui::SoFCColorGradient::getColorBarName () const virtual
Returns the name of the color bar.
Implements Gui::SoFCColorBarBase.
getMarkerValues()
std::vector< float > SoFCColorGradient::getMarkerValues (float fMin, float fMax, int count) const protected
Returns a list of count labels within the range [fMin, fMax].
References App::ZERO_BASED.
Referenced by setRange().
getMaxValue()
float Gui::SoFCColorGradient::getMaxValue () const virtual
Returns the current maximum of the parameter range.
Implements Gui::SoFCColorBarBase.
getMinValue()
float Gui::SoFCColorGradient::getMinValue () const virtual
Returns the current minimum of the parameter range.
Implements Gui::SoFCColorBarBase.
initClass()
void SoFCColorGradient::initClass (void) static
Referenced by Gui::SoFCDB::init().
isVisible()
bool SoFCColorGradient::isVisible (float fVal) const virtual
Returns always true if the gradient is in mode to show colors to arbitrary values of fVal, otherwise true is returned if fVal is within the specified parameter range, if not false is returned.
Implements Gui::SoFCColorBarBase.
Referenced by ArchVRM.Renderer::removeHidden().
rebuildGradient()
void SoFCColorGradient::rebuildGradient () protected
Rebuild the gradient bar.
References App::Color::b, Gui::coinRemoveAllChildren(), App::ColorModel::colors, App::Color::g, App::ColorModel::getCountColors(), and App::Color::r.
Referenced by customize(), setColorModel(), and setColorStyle().
setColorModel()
void SoFCColorGradient::setColorModel (std::size_t index) protected
Sets the color model of the underlying color gradient to index.
References rebuildGradient().
setColorStyle()
void SoFCColorGradient::setColorStyle (App::ColorBarStyle tStyle) protected
Sets the color style of the underlying color gradient to tStyle.
tStyle either can be FLOW or ZERO_BASED
References rebuildGradient().
setOutsideGrayed()
void Gui::SoFCColorGradient::setOutsideGrayed (bool bVal) virtual
Sets whether values outside the range should be in gray,.
This method must be implemented in subclasses.
Implements Gui::SoFCColorBarBase.
setRange()
void SoFCColorGradient::setRange (float fMin, float fMax, int prec = 3) virtual
Sets the range of the colorbar from the maximum fMax to the minimum fMin.
prec indicates the post decimal positions, prec should be in between 0 and 6.
Implements Gui::SoFCColorBarBase.
References getMarkerValues().
Referenced by customize().
setViewportSize()
void SoFCColorGradient::setViewportSize (const SbVec2s & size) protected virtual
Sets the current viewer size this color gradient is embedded into, to recalculate its new position.
Implements Gui::SoFCColorBarBase.
References Gui::SoFCColorBarBase::getBounds().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/SoFCColorGradient.h
FreeCAD/src/Gui/SoFCColorGradient.cpp