FreeCAD: MeshGui::GmshWidget Class Reference
MeshGui::GmshWidget Class Reference
Non-modal dialog to remesh an existing mesh.
#include <RemeshGmsh.h>
Classes
class Private
Public Member Functions
void accept ()
GmshWidget (QWidget *parent=0, Qt::WindowFlags fl=Qt::WindowFlags())
void reject ()
~GmshWidget ()
Protected Member Functions
void changeEvent (QEvent *e)
double getAngle () const
double getMaxSize () const
double getMinSize () const
virtual bool loadOutput ()
int meshingAlgorithm () const
virtual bool writeProject (QString &inpFile, QString &outFile)
Detailed Description
Non-modal dialog to remesh an existing mesh.
Author
Werner Mayer
Constructor & Destructor Documentation
GmshWidget()
GmshWidget::GmshWidget (QWidget * parent = 0, Qt::WindowFlags fl = Qt::WindowFlags())
References draftgeoutils.intersections::connect().
~GmshWidget()
GmshWidget::~GmshWidget ()
Member Function Documentation
accept()
void GmshWidget::accept (void)
References Base::Console(), Base::ConsoleSingleton::Warning(), and writeProject().
Referenced by MeshGui::TaskRemeshGmsh::clicked(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), MeshPartGui::Mesh2ShapeGmsh::loadOutput(), MeshPartGui::Mesh2ShapeGmsh::process(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void GmshWidget::changeEvent (QEvent * e) protected
getAngle()
double GmshWidget::getAngle (void) const protected
Referenced by PathScripts.PathDressupDogbone.Chord::getAngleXY(), draftguitools.gui_trackers.arcTracker::setEndPoint(), draftguitools.gui_trackers.arcTracker::setStartPoint(), and MeshGui::RemeshGmsh::writeProject().
getMaxSize()
double GmshWidget::getMaxSize () const protected
Referenced by MeshGui::RemeshGmsh::writeProject(), and MeshPartGui::Mesh2ShapeGmsh::writeProject().
getMinSize()
double GmshWidget::getMinSize () const protected
Referenced by MeshGui::RemeshGmsh::writeProject(), and MeshPartGui::Mesh2ShapeGmsh::writeProject().
loadOutput()
bool GmshWidget::loadOutput () protected virtual
Reimplemented in MeshPartGui::Mesh2ShapeGmsh, and MeshGui::RemeshGmsh.
meshingAlgorithm()
int GmshWidget::meshingAlgorithm () const protected
Referenced by MeshGui::RemeshGmsh::writeProject(), and MeshPartGui::Mesh2ShapeGmsh::writeProject().
reject()
void GmshWidget::reject (void)
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), MeshGui::TaskRemeshGmsh::clicked(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
writeProject()
bool GmshWidget::writeProject (QString & inpFile, QString & outFile) protected virtual
Reimplemented in MeshPartGui::Mesh2ShapeGmsh, and MeshGui::RemeshGmsh.
Referenced by accept().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/Gui/RemeshGmsh.h
Sources/FreeCAD/src/Mod/Mesh/Gui/RemeshGmsh.cpp