FreeCAD: MeshGui::SoFCMeshFacetElement Class Reference
MeshGui::SoFCMeshFacetElement Class Reference
#include <SoFCMeshFaceSet.h>
Public Member Functions
virtual void init (SoState *state)
virtual void print (FILE *file) const
Static Public Member Functions
static const MeshCore::MeshFacetArray * get (SoState *const state)
static const SoFCMeshFacetElement * getInstance (SoState *state)
static void initClass (void)
static void set (SoState *const state, SoNode *const node, const MeshCore::MeshFacetArray *const coords)
Protected Member Functions
virtual ~SoFCMeshFacetElement ()
Protected Attributes
const MeshCore::MeshFacetArray * coordIndex
Constructor & Destructor Documentation
~SoFCMeshFacetElement()
SoFCMeshFacetElement::~SoFCMeshFacetElement () protected virtual
Member Function Documentation
get()
const MeshCore::MeshFacetArray * SoFCMeshFacetElement::get (SoState *const state) static
References coordIndex, and getInstance().
Referenced by MeshGui::SoFCMeshFaceSet::generatePrimitives(), MeshGui::SoFCMeshOpenEdgeSet::generatePrimitives(), MeshGui::SoFCMeshFaceSet::getPrimitiveCount(), MeshGui::SoFCMeshOpenEdgeSet::getPrimitiveCount(), MeshGui::SoFCMeshFaceSet::GLRender(), and MeshGui::SoFCMeshOpenEdgeSet::GLRender().
getInstance()
const SoFCMeshFacetElement * SoFCMeshFacetElement::getInstance (SoState * state) static
Referenced by get().
init()
void SoFCMeshFacetElement::init (SoState * state) virtual
References coordIndex.
Referenced by DocumentObject.DocumentObject::onChanged().
initClass()
void SoFCMeshFacetElement::initClass (void) static
print()
void SoFCMeshFacetElement::print (FILE * file) const virtual
set()
void SoFCMeshFacetElement::set (SoState *const state, SoNode *const node, const MeshCore::MeshFacetArray *const coords) static
References coordIndex.
Referenced by MeshGui::SoFCMeshFacet::doAction().
Member Data Documentation
coordIndex
const MeshCore::MeshFacetArray* MeshGui::SoFCMeshFacetElement::coordIndex protected
Referenced by get(), init(), and set().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCMeshFaceSet.h
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCMeshFaceSet.cpp