FreeCAD: App::PropertyString Class Reference
App::PropertyString Class Reference
String properties This is the father of all properties handling Strings.
#include <PropertyStandard.h>
Public Member Functions
virtual Property * Copy (void) const
Returns a new copy of the property (mainly for Undo/Redo and transactions)
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
const std::string & getStrValue (void) const
const char * getValue (void) const
bool isEmpty (void)
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
virtual void Paste (const Property &from)
Paste the value from the property (mainly for Undo/Redo and transactions)
PropertyString (void)
A constructor.
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual void setPyObject (PyObject *)
virtual void setValue (const char *sString)
void setValue (const std::string &sString)
virtual ~PropertyString ()
A destructor.
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual Property * Copy (void) const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
int64_t getID () const
Return a unique ID for the property.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const char * getName (void) const
Get the name of this property in the belonging container With hasName() it can be checked beforehand if a valid name is set.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
bool hasName () const
Check if the property has a name set.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , Busy = 15 ,
CopyOnChange = 16 , UserEdit = 17 , PropStaticBegin = 21 , PropDynamic = 21 ,
PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 , PropTransient = 25 ,
PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 , User1 = 28 ,
User2 = 29 , User3 = 30 , User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Check if the passed name is valid.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Detailed Description
String properties This is the father of all properties handling Strings.
Constructor & Destructor Documentation
PropertyString()
PropertyString::PropertyString (void)
A constructor.
A more elaborate description of the constructor.
Referenced by Copy().
~PropertyString()
PropertyString::~PropertyString () virtual
A destructor.
A more elaborate description of the destructor.
Member Function Documentation
Copy()
Property * PropertyString::Copy (void) const virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Reimplemented in App::PropertyPersistentObject.
References PropertyString().
getEditorName()
virtual const char * App::PropertyString::getEditorName (void) const virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
Reimplemented in App::PropertyFile, and App::PropertyFont.
getMemSize()
unsigned int PropertyString::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
See also
Base::Persistence
Reimplemented from App::Property.
Reimplemented in App::PropertyPersistentObject.
Referenced by App::PropertyPersistentObject::getMemSize().
getPathValue()
const boost::any PropertyString::getPathValue (const App::ObjectIdentifier & path) const virtual
Get value of property.
Reimplemented from App::Property.
References App::Property::verifyPath().
getPyObject()
PyObject * PropertyString::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Reimplemented in App::PropertyPersistentObject.
Referenced by App::PropertyXLink::getPyObject(), App::PropertyXLinkSub::getPyObject(), and App::PropertyEnumeration::getPyPathValue().
getStrValue()
const std::string & App::PropertyString::getStrValue (void) const
Referenced by TechDraw::DrawViewDimension::getFormattedDimensionValue(), TechDraw::DrawViewDimension::getFormattedToleranceValue(), TechDraw::DrawViewDimension::getFormattedToleranceValues(), Gui::ViewProviderPart::getIcon(), App::Document::onChanged(), App::PropertyLinkBase::restoreLabelReference(), App::Document::saveAs(), App::Document::saveCopy(), App::PropertyXLink::setPyObject(), TechDrawGui::QGIViewBalloon::setViewPartFeature(), App::RelabelDocumentExpressionVisitor::visit(), and MeshPartGui::Mesh2ShapeGmsh::writeProject().
getValue()
const char * PropertyString::getValue (void) const
Referenced by MeshGui::Segmentation::accept(), MeshGui::SegmentationBestFit::accept(), PartGui::SweepWidget::accept(), ReverseEngineeringGui::Segmentation::accept(), Gui::ExpressionBinding::apply(), Gui::ViewProviderOriginFeature::attach(), Gui::Document::canClose(), SurfaceGui::FillingPanel::checkOpenCommand(), SurfaceGui::FillingEdgePanel::checkOpenCommand(), SurfaceGui::FillingVertexPanel::checkOpenCommand(), SurfaceGui::GeomFillSurface::checkOpenCommand(), SurfaceGui::SectionsPanel::checkOpenCommand(), Part::Extrusion::computeFinalParameters(), Import::ExportOCAF::createNode(), Gui::Document::createView(), SpreadsheetGui::SheetModel::data(), SpreadsheetGui::DlgBindSheet::DlgBindSheet(), Gui::DocumentObjectData::DocumentObjectData(), PartDesignGui::ViewProviderDatum::doubleClicked(), TechDrawGui::QGIViewPart::drawHighlight(), Gui::ViewProviderAnnotationLabel::drawImage(), TechDrawGui::QGIViewPart::drawSectionLine(), TechDrawGui::QGIWeldSymbol::drawTailText(), TechDrawGui::QGIWeldSymbol::drawTile(), Gui::ElementColors::ElementColors(), Mesh::Export::execute(), Mesh::SetOperations::execute(), Drawing::FeatureClip::execute(), Drawing::FeaturePage::execute(), Drawing::FeatureViewAnnotation::execute(), Drawing::FeatureViewPart::execute(), Drawing::FeatureViewSpreadsheet::execute(), Drawing::FeatureViewSymbol::execute(), Inspection::Feature::execute(), Part::CurveNet::execute(), Part::ImportBrep::execute(), Part::ImportIges::execute(), Part::ImportStep::execute(), Raytracing::LuxProject::execute(), Raytracing::RayProject::execute(), TechDraw::DrawParametricTemplate::execute(), TechDraw::DrawSVGTemplate::execute(), TechDraw::DrawViewSpreadsheet::execute(), Part::Face::execute(), Part::Revolution::execute(), TechDraw::DrawViewArch::execute(), TechDraw::DrawViewDraft::execute(), TechDraw::DrawViewSymbol::execute(), MeshGui::ViewProviderMesh::exportMesh(), App::OriginGroupExtension::extensionGetSubObject(), Part::AttachExtension::extensionOnChanged(), PartGui::FaceColors::FaceColors(), PartGui::DlgExtrusion::findShapes(), Fem::FemPostDataAlongLineFilter::GetAxisData(), TechDraw::DrawGeomHatch::getDecodedSpecsFromFile(), TechDraw::DrawProjGroup::getDirsFromFront(), TechDraw::DrawSVGTemplate::getEditableTextsFromTemplate(), Drawing::FeaturePage::getEditableTextsFromTemplate(), App::Document::getFileName(), Spreadsheet::Cell::getFormattedQuantity(), Gui::LinkInfo::getLinkedLabel(), TechDrawGui::TaskGeomHatch::getParameters(), Fem::FemPostDataAtPointFilter::GetPointData(), TechDraw::DrawViewSpreadsheet::getSheetImage(), Import::ImportOCAF2::ImportOCAF2(), TechDraw::DrawHatch::isBitmapHatch(), App::Document::isSaved(), TechDraw::DrawHatch::isSvgHatch(), TechDrawGui::TaskLinkDim::loadToTree(), MeshGui::MeshSplit::makeCopy(), TechDraw::DrawViewSection::makeLineSets(), TechDrawGui::QGITile::makeSymbol(), TechDrawGui::QGIRichAnno::mouseDoubleClickEvent(), App::Document::onBeforeChange(), Gui::ViewProviderAnnotation::onChanged(), Gui::ViewProviderTextDocument::onChanged(), Drawing::FeatureViewSymbol::onChanged(), TechDraw::DrawTileWeld::onChanged(), TechDraw::DrawGeomHatch::onChanged(), TechDraw::DrawHatch::onChanged(), TechDraw::DrawPage::onChanged(), TechDraw::DrawViewDetail::onChanged(), TechDraw::DrawViewDimension::onChanged(), TechDraw::DrawViewSection::onChanged(), TechDraw::DrawViewSymbol::onChanged(), Drawing::FeaturePage::onDocumentRestored(), Raytracing::LuxProject::onDocumentRestored(), Raytracing::RayProject::onDocumentRestored(), TechDraw::DrawTileWeld::onDocumentRestored(), TechDraw::DrawGeomHatch::onDocumentRestored(), TechDraw::DrawHatch::onDocumentRestored(), TechDraw::DrawViewSection::onDocumentRestored(), TechDrawGui::TaskWeldingSymbol::onFlipSidesClicked(), Gui::MDIView::onRelabel(), DrawingGui::DrawingView::onRelabel(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), SurfaceGui::FillingEdgePanel::onSelectionChanged(), SurfaceGui::FillingVertexPanel::onSelectionChanged(), SurfaceGui::GeomFillSurface::onSelectionChanged(), SurfaceGui::SectionsPanel::onSelectionChanged(), App::Application::openDocumentPrivate(), TechDrawGui::QGSPage::postProcessXml(), TechDraw::DrawSVGTemplate::processTemplate(), App::Document::recompute(), App::OriginGroupExtension::relinkToOrigin(), App::Document::Restore(), App::Document::restore(), App::VRMLObject::RestoreDocFile(), Sandbox::DocumentSaverThread::run(), App::Document::save(), App::VRMLObject::SaveDocFile(), TechDrawGui::TaskHatch::saveHatchState(), TechDrawGui::TaskSectionView::saveSectionState(), Import::ExportOCAF::saveShape(), TechDraw::DrawViewSection::sectionExec(), Part::AttachExtension::setAttacher(), SurfaceGui::FillingPanel::setEditedObject(), Gui::ExpressionBinding::setExpression(), RobotGui::TaskEdge2TracParameter::setHideShowObject(), Import::ImportOCAF2::setMode(), App::PropertyLinkSub::setPyObject(), App::PropertyLinkSubList::setPyObject(), TechDrawGui::QGIRichAnno::setTextItem(), TechDrawGui::TaskSectionView::setUiEdit(), TechDrawGui::TaskWeldingSymbol::setUiEdit(), TechDrawGui::TaskRichAnno::setUiEdit(), TechDrawGui::TaskDetail::setUiFromFeat(), TechDraw::DrawHatch::setupFileIncluded(), TechDraw::DrawGeomHatch::setupPatIncluded(), TechDraw::DrawViewSection::setupPatIncluded(), TechDraw::DrawViewSection::setupSvgIncluded(), TechDraw::DrawTileWeld::setupSymbolIncluded(), PartDesignGui::TaskDressUpParameters::setupTransaction(), DrawingGui::ViewProviderDrawingPage::showDrawingView(), SpreadsheetGui::ViewProviderSheet::showSpreadsheetView(), Gui::AutoSaver::slotCreateDocument(), TechDrawGui::TaskBalloon::TaskBalloon(), TechDrawGui::TaskDimension::TaskDimension(), FemGui::TaskObjectName::TaskObjectName(), PartDesignGui::TaskPipeOrientation::TaskPipeOrientation(), PartDesignGui::TaskPipeParameters::TaskPipeParameters(), App::PropertyLinkBase::tryReplaceLink(), TechDraw::DrawProjGroupItem::unsetupObject(), SpreadsheetGui::SheetView::updateCell(), Gui::ViewProviderInventorObject::updateData(), DrawingGui::ViewProviderDrawingPage::updateData(), and App::Document::~Document().
isEmpty()
bool App::PropertyString::isEmpty (void)
Referenced by TechDraw::DrawGeomHatch::makeLineSets(), TechDraw::DrawViewSection::makeLineSets(), TechDraw::DrawTileWeld::onChanged(), TechDraw::DrawGeomHatch::onChanged(), TechDraw::DrawHatch::onChanged(), TechDraw::DrawViewSection::onChanged(), TechDraw::DrawTileWeld::onDocumentRestored(), TechDraw::DrawGeomHatch::onDocumentRestored(), TechDraw::DrawHatch::onDocumentRestored(), TechDraw::DrawViewSection::onDocumentRestored(), TechDraw::DrawHatch::setupFileIncluded(), TechDraw::DrawGeomHatch::setupPatIncluded(), and TechDraw::DrawViewSection::setupPatIncluded().
isSame()
virtual bool App::PropertyString::isSame (const Property & other) const virtual
Compare if this property has the same content as the given one.
Reimplemented from App::Property.
Reimplemented in App::PropertyFont.
References Base::Persistence::getTypeId().
Paste()
void PropertyString::Paste (const Property & from) virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Reimplemented in App::PropertyPersistentObject.
References setValue().
Restore()
void PropertyString::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Reimplemented in App::PropertyPersistentObject.
References App::Property::aboutToSetValue(), Base::XMLReader::getAttribute(), Base::XMLReader::getAttributeAsInteger(), App::Property::getContainer(), Base::XMLReader::getName(), Base::XMLReader::hasAttribute(), App::Property::hasSetValue(), Base::XMLReader::readElement(), and setValue().
Referenced by App::PropertyPersistentObject::Restore().
Save()
void PropertyString::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Reimplemented in App::PropertyPersistentObject.
References Base::Persistence::encodeAttribute(), App::Property::getContainer(), Base::Writer::ind(), and Base::Writer::Stream().
Referenced by App::PropertyPersistentObject::Save().
setPathValue()
void PropertyString::setPathValue (const App::ObjectIdentifier & path, const boost::any & value) virtual
Set value of property.
Reimplemented from App::Property.
References App::pyObjectFromAny(), setValue(), and App::Property::verifyPath().
setPyObject()
void PropertyString::setPyObject (PyObject * value) virtual
Reimplemented from Base::BaseClass.
References setValue().
Referenced by App::PropertyLinkSub::setPyObject(), App::PropertyLinkSubList::setPyObject(), and App::PropertyXLink::setPyObject().
setValue() [1/2]
void PropertyString::setValue (const char * sString) virtual
Reimplemented in App::PropertyPersistentObject.
References App::Property::aboutToSetValue(), App::Application::closeActiveTransaction(), DraftVecUtils::find(), App::GetApplication(), ParameterGrp::GetBool(), App::Property::getContainer(), ParameterGrp::GetGroup(), Base::Tools::getUniqueName(), App::Application::GetUserParameter(), App::Property::hasSetValue(), App::Document::Importing, App::Document::Restoring, App::Application::setActiveTransaction(), and App::PropertyLinkBase::updateLabelReferences().
Referenced by FemGui::TaskDlgCreateNodeSet::accept(), MeshGui::Segmentation::accept(), MeshGui::SegmentationBestFit::accept(), ReverseEngineeringGui::Segmentation::accept(), TechDrawGui::TaskCustomizeFormat::accept(), App::Document::addObject(), App::Document::addObjects(), TechDrawGui::TaskRichAnno::commonFeatureUpdate(), TechDrawGui::QGSPage::createBalloon(), Gui::PointMarker::customEvent(), PartGui::DlgProjectionOnSurface::DlgProjectionOnSurface(), App::FeatureTest::execute(), Drawing::FeatureClip::execute(), Drawing::FeatureViewAnnotation::execute(), Drawing::FeatureViewPart::execute(), Drawing::FeatureViewSpreadsheet::execute(), Drawing::FeatureViewSymbol::execute(), Raytracing::LuxFeature::execute(), Raytracing::RayFeature::execute(), TechDraw::DrawViewSpreadsheet::execute(), TechDraw::DrawViewSymbol::execute(), App::PropertyXLink::getPyObject(), App::PropertyXLinkSub::getPyObject(), App::PropertyEnumeration::getPyPathValue(), Part::ImportIgesParts(), MeshPartGui::Mesh2ShapeGmsh::loadOutput(), Import::ImportOCAF2::loadShapes(), MeshGui::MeshSplit::makeCopy(), TechDrawGui::QGIRichAnno::mouseDoubleClickEvent(), TechDraw::DrawSVGTemplate::onChanged(), TechDraw::DrawViewDetail::onChanged(), TechDraw::DrawViewDimension::onChanged(), TechDraw::DrawViewSection::onChanged(), App::Document::onChanged(), Drawing::FeaturePage::onDocumentRestored(), Raytracing::LuxProject::onDocumentRestored(), Raytracing::RayProject::onDocumentRestored(), TechDrawGui::TaskGeomHatch::onFileChanged(), App::Application::openDocumentPrivate(), Paste(), TechDrawGui::TaskGeomHatch::reject(), App::Document::removeObject(), Restore(), App::Document::Restore(), TechDrawGui::TaskHatch::restoreHatchState(), TechDrawGui::TaskSectionView::restoreSectionState(), Sandbox::DocumentTestThread::run(), App::Document::save(), App::Document::saveAs(), DrawingGui::orthoview::set_data(), Part::AttachExtension::setAttacher(), Gui::DocumentItem::setData(), App::LinkBaseExtension::setLink(), setPathValue(), setPyObject(), Spreadsheet::Sheet::setStringProperty(), App::Origin::setupObject(), Part::Face::setupObject(), setValue(), MeshGui::Annotation::show(), TechDrawGui::TaskDetail::updateDetail(), TechDrawGui::TaskWeldingSymbol::updateTiles(), and TechDrawGui::TaskGeomHatch::updateValues().
setValue() [2/2]
void PropertyString::setValue (const std::string & sString)
References setValue().
The documentation for this class was generated from the following files:
FreeCAD/src/App/PropertyStandard.h
FreeCAD/src/App/PropertyStandard.cpp