FreeCAD: Ui_TaskAnalysisInfo Class Reference
Ui_TaskAnalysisInfo Class Reference
#include <ui_TaskAnalysisInfo.h>
Public Member Functions
void retranslateUi (QWidget *TaskAnalysisInfo)
void setupUi (QWidget *TaskAnalysisInfo)
Public Attributes
QLabel * label
QLabel * label_2
QListView * listView
QListView * listView_2
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void Ui_TaskAnalysisInfo::retranslateUi (QWidget * TaskAnalysisInfo)
References label_2, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Ui_TaskAnalysisInfo::setupUi (QWidget * TaskAnalysisInfo)
References label_2, listView, listView_2, retranslateUi(), and verticalLayout.
Referenced by FemGui::TaskAnalysisInfo::TaskAnalysisInfo().
Member Data Documentation
label
QLabel* Ui_TaskAnalysisInfo::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
label_2
QLabel* Ui_TaskAnalysisInfo::label_2
Referenced by retranslateUi(), and setupUi().
listView
QListView* Ui_TaskAnalysisInfo::listView
Referenced by setupUi().
listView_2
QListView* Ui_TaskAnalysisInfo::listView_2
Referenced by setupUi().
verticalLayout
QVBoxLayout* Ui_TaskAnalysisInfo::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Fem/Gui/ui_TaskAnalysisInfo.h