FreeCAD: SketcherGui::SketcherGeneralWidget Class Reference
SketcherGui::SketcherGeneralWidget Class Reference
#include <TaskSketcherGeneral.h>
Signals
void emitRenderOrderChanged ()
void emitSetGridSize (double)
void emitToggleAutoconstraints (bool)
void emitToggleAvoidRedundant (bool)
void emitToggleGridSnap (bool)
void emitToggleGridView (bool)
Public Member Functions
void checkAutoconstraints (bool)
void checkAvoidRedundant (bool)
void checkGridSnap (bool)
void checkGridView (bool)
void enableAvoidRedundant (bool)
void enableGridSettings (bool)
bool eventFilter (QObject *object, QEvent *event)
void loadOrderingOrder ()
void loadSettings ()
void saveOrderingOrder ()
void saveSettings ()
void setGridSize (double val)
SketcherGeneralWidget (QWidget *parent=0)
~SketcherGeneralWidget ()
Protected Member Functions
void changeEvent (QEvent *e)
Constructor & Destructor Documentation
SketcherGeneralWidget()
SketcherGeneralWidget::SketcherGeneralWidget (QWidget * parent = 0)
References draftgeoutils.intersections::connect(), emitSetGridSize(), emitToggleAutoconstraints(), emitToggleAvoidRedundant(), emitToggleGridSnap(), and emitToggleGridView().
~SketcherGeneralWidget()
SketcherGeneralWidget::~SketcherGeneralWidget ()
Member Function Documentation
changeEvent()
void SketcherGeneralWidget::changeEvent (QEvent * e) protected
checkAutoconstraints()
void SketcherGeneralWidget::checkAutoconstraints (bool on)
Referenced by SketcherGui::TaskSketcherGeneral::TaskSketcherGeneral().
checkAvoidRedundant()
void SketcherGeneralWidget::checkAvoidRedundant (bool on)
Referenced by SketcherGui::TaskSketcherGeneral::TaskSketcherGeneral().
checkGridSnap()
void SketcherGeneralWidget::checkGridSnap (bool on)
Referenced by SketcherGui::TaskSketcherGeneral::TaskSketcherGeneral().
checkGridView()
void SketcherGeneralWidget::checkGridView (bool on)
Referenced by SketcherGui::TaskSketcherGeneral::TaskSketcherGeneral().
emitRenderOrderChanged
void SketcherGui::SketcherGeneralWidget::emitRenderOrderChanged () signal
Referenced by eventFilter().
emitSetGridSize
void SketcherGui::SketcherGeneralWidget::emitSetGridSize (double) signal
Referenced by SketcherGeneralWidget().
emitToggleAutoconstraints
void SketcherGui::SketcherGeneralWidget::emitToggleAutoconstraints (bool) signal
Referenced by SketcherGeneralWidget().
emitToggleAvoidRedundant
void SketcherGui::SketcherGeneralWidget::emitToggleAvoidRedundant (bool) signal
Referenced by SketcherGeneralWidget().
emitToggleGridSnap
void SketcherGui::SketcherGeneralWidget::emitToggleGridSnap (bool) signal
Referenced by SketcherGeneralWidget().
emitToggleGridView
void SketcherGui::SketcherGeneralWidget::emitToggleGridView (bool) signal
Referenced by SketcherGeneralWidget().
enableAvoidRedundant()
void SketcherGeneralWidget::enableAvoidRedundant (bool on)
Referenced by SketcherGui::TaskSketcherGeneral::onToggleAutoconstraints(), and SketcherGui::TaskSketcherGeneral::TaskSketcherGeneral().
enableGridSettings()
void SketcherGeneralWidget::enableGridSettings (bool on)
Referenced by SketcherGui::TaskSketcherGeneral::onToggleGridView(), and SketcherGui::TaskSketcherGeneral::TaskSketcherGeneral().
eventFilter()
bool SketcherGeneralWidget::eventFilter (QObject * object, QEvent * event)
References emitRenderOrderChanged().
loadOrderingOrder()
void SketcherGeneralWidget::loadOrderingOrder ()
References App::GetApplication(), ParameterGrp::GetInt(), and App::Application::GetParameterGroupByPath().
Referenced by loadSettings().
loadSettings()
void SketcherGeneralWidget::loadSettings ()
References loadOrderingOrder().
Referenced by SketcherGui::SketcherSettings::loadSettings(), and SketcherGui::TaskSketcherGeneral::TaskSketcherGeneral().
saveOrderingOrder()
void SketcherGeneralWidget::saveOrderingOrder ()
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetInt().
Referenced by SketcherGui::TaskSketcherGeneral::onRenderOrderChanged(), and saveSettings().
saveSettings()
void SketcherGeneralWidget::saveSettings ()
References saveOrderingOrder().
Referenced by SketcherGui::SketcherSettings::saveSettings().
setGridSize()
void SketcherGeneralWidget::setGridSize (double val)
References Base::Unit::Length.
Referenced by SketcherGui::TaskSketcherGeneral::TaskSketcherGeneral().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sketcher/Gui/TaskSketcherGeneral.h
Sources/FreeCAD/src/Mod/Sketcher/Gui/TaskSketcherGeneral.cpp