FreeCAD: PartDesignGui::TaskPocketParameters Class Reference
PartDesignGui::TaskPocketParameters Class Reference
#include <TaskPocketParameters.h>
Public Member Functions
virtual void apply () override
apply changes made in the parameters input to the model via commands
TaskPocketParameters (ViewProviderPocket *PocketView, QWidget *parent=nullptr, bool newObj=false)
~TaskPocketParameters ()
Public Member Functions inherited from PartDesignGui::TaskExtrudeParameters
void addAxisToCombo (App::DocumentObject *linkObj, std::string linkSubname, QString itemText, bool hasSketch=true)
void applyParameters (QString facename)
void fillDirectionCombo ()
virtual void saveHistory () override
save field history
TaskExtrudeParameters (ViewProviderSketchBased *SketchBasedView, QWidget *parent, const std::string &pixmapname, const QString &parname)
~TaskExtrudeParameters ()
Public Member Functions inherited from PartDesignGui::TaskSketchBasedParameters
TaskSketchBasedParameters (PartDesignGui::ViewProvider *vp, QWidget *parent, const std::string &pixmapname, const QString &parname)
~TaskSketchBasedParameters ()
Public Member Functions inherited from PartDesignGui::TaskFeatureParameters
virtual void apply ()
apply changes made in the parameters input to the model via commands
void recomputeFeature ()
virtual void saveHistory (void)
save field history
TaskFeatureParameters (PartDesignGui::ViewProvider *vp, QWidget *parent, const std::string &pixmapname, const QString &parname)
virtual ~TaskFeatureParameters ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::DocumentObserver
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Additional Inherited Members
Public Types inherited from PartDesignGui::TaskExtrudeParameters
enum class Modes {
Dimension , ThroughAll , ToLast = ThroughAll , ToFirst ,
ToFace , TwoDimensions
}
enum class Type { Pad , Pocket }
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Slots inherited from PartDesignGui::TaskExtrudeParameters
void onAlongSketchNormalChanged (bool)
void onButtonFace (const bool pressed=true)
void onDirectionCBChanged (int)
void onDirectionToggled (bool)
void onFaceName (const QString &text)
void onLength2Changed (double)
void onLengthChanged (double)
void onMidplaneChanged (bool)
virtual void onModeChanged (int)
void onOffsetChanged (double)
void onReversedChanged (bool)
void onTaper2Changed (double)
void onTaperChanged (double)
void onXDirectionEditChanged (double)
void onYDirectionEditChanged (double)
void onZDirectionEditChanged (double)
Protected Slots inherited from PartDesignGui::TaskFeatureParameters
void onUpdateView (bool on)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Member Functions inherited from PartDesignGui::TaskExtrudeParameters
void changeEvent (QEvent *e) override
bool getAlongSketchNormal (void) const
bool getCustom (void) const
QString getFaceName (void) const
bool getMidplane (void) const
int getMode (void) const
double getOffset (void) const
void getReferenceAxis (App::DocumentObject *&obj, std::vector< std::string > &sub) const
std::string getReferenceAxis (void) const
bool getReversed (void) const
double getXDirection (void) const
double getYDirection (void) const
double getZDirection (void) const
void onSelectionChanged (const Gui::SelectionChanges &msg) override
void readValuesFromHistory ()
void setCheckboxes (Modes mode, Type type)
void setDirectionMode (int index)
void setupDialog ()
virtual void translateModeList (int index)
void updateDirectionEdits (void)
virtual void updateUI (int index)
Protected Member Functions inherited from PartDesignGui::TaskSketchBasedParameters
void exitSelectionMode ()
virtual void finishReferenceSelection (App::DocumentObject *profile, App::DocumentObject *base)
QString getFaceReference (const QString &obj, const QString &sub) const
QString make2DLabel (const App::DocumentObject *section, const std::vector< std::string > &subValues)
Create a label for the 2D feature: the objects name if it's already 2D, or the subelement's name if the object is a solid.
QVariant objectNameByLabel (const QString &label, const QVariant &suggest) const
Try to find the name of a feature with the given label.
const QString onAddSelection (const Gui::SelectionChanges &msg)
void onSelectionChanged (const Gui::SelectionChanges &msg)=0
void onSelectReference (AllowSelectionFlags)
onSelectReference Start reference selection mode to allow to select objects of the type defined with AllowSelectionFlags. If AllowSelection::NONE is passed the selection mode is finished.
QVariant setUpToFace (const QString &text)
virtual void startReferenceSelection (App::DocumentObject *profile, App::DocumentObject *base)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Protected Attributes inherited from PartDesignGui::TaskExtrudeParameters
std::vector< std::unique_ptr< App::PropertyLinkSub > > axesInList
App::PropertyLinkSub * propReferenceAxis
QWidget * proxy
bool selectionFace
std::unique_ptr< Ui_TaskPadPocketParameters > ui
Protected Attributes inherited from PartDesignGui::TaskFeatureParameters
bool blockUpdate
Lock updateUI(), applying changes to the underlying feature and calling recomputeFeature()
PartDesignGui::ViewProvider * vp
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskPocketParameters()
TaskPocketParameters::TaskPocketParameters (ViewProviderPocket * PocketView, QWidget * parent = nullptr, bool newObj = false)
References PartDesignGui::TaskExtrudeParameters::readValuesFromHistory(), PartDesignGui::TaskExtrudeParameters::setupDialog(), and PartDesignGui::TaskExtrudeParameters::ui.
~TaskPocketParameters()
TaskPocketParameters::~TaskPocketParameters ()
Member Function Documentation
apply()
void TaskPocketParameters::apply (void) override virtual
apply changes made in the parameters input to the model via commands
Reimplemented from PartDesignGui::TaskFeatureParameters.
References PartDesignGui::TaskExtrudeParameters::applyParameters(), PartDesignGui::TaskExtrudeParameters::getFaceName(), PartDesignGui::TaskExtrudeParameters::getMode(), and PartDesignGui::TaskExtrudeParameters::ToFace.
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/PartDesign/Gui/TaskPocketParameters.h
FreeCAD/src/Mod/PartDesign/Gui/TaskPocketParameters.cpp