FreeCAD: Web::AppServer Class Reference
Web::AppServer Class Reference
The Server class implements a simple TCP server.
#include <Server.h>
Public Member Functions
AppServer (QObject *parent=0)
void incomingConnection (int socket)
Static Public Member Functions
static std::string runPython (const QByteArray &)
Protected Member Functions
void customEvent (QEvent *e)
Detailed Description
The Server class implements a simple TCP server.
Constructor & Destructor Documentation
AppServer()
AppServer::AppServer (QObject * parent = 0)
Member Function Documentation
customEvent()
void AppServer::customEvent (QEvent * e) protected
References Web::ServerEvent::request(), runPython(), and Web::ServerEvent::socket().
incomingConnection()
void AppServer::incomingConnection (int socket)
References draftgeoutils.intersections::connect().
runPython()
std::string AppServer::runPython (const QByteArray & msg) static
References Web::Firewall::filter(), Web::Firewall::getInstance(), Base::Interpreter(), and Base::InterpreterSingleton::runString().
Referenced by customEvent().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Web/App/Server.h
Sources/FreeCAD/src/Mod/Web/App/Server.cpp