FreeCAD: App::ObjectIdentifier::String Class Reference
App::ObjectIdentifier::String Class Reference
#include <ObjectIdentifier.h>
Public Member Functions
void checkImport (const App::DocumentObject *owner, const App::DocumentObject *obj=nullptr, String *objName=nullptr)
FC_DEFAULT_CTORS (String)
const std::string & getString () const
Returns the string.
bool isForceIdentifier () const
bool isRealString () const
Return true is string need to be quoted.
operator const char * () const
operator std::string () const
bool operator!= (const String &other) const
bool operator< (const String &other) const
bool operator== (const String &other) const
bool operator> (const String &other) const
bool operator>= (const String &other) const
String (const std::string &s="", bool _isRealString=false, bool _forceIdentifier=false)
String (std::string &&s, bool _isRealString=false, bool _forceIdentifier=false)
std::string toString (bool toPython=false) const
Returns a possibly quoted string.
Friends
class ObjectIdentifier
Constructor & Destructor Documentation
String() [1/2]
App::ObjectIdentifier::String::String (const std::string & s = "", bool _isRealString = false, bool _forceIdentifier = false)
String() [2/2]
App::ObjectIdentifier::String::String (std::string && s, bool _isRealString = false, bool _forceIdentifier = false)
Member Function Documentation
checkImport()
void ObjectIdentifier::String::checkImport (const App::DocumentObject * owner, const App::DocumentObject * obj = nullptr, String * objName = nullptr)
References App::DocumentObject::getDocument(), App::ObjectIdentifier::getDocumentObject(), App::Document::getObject(), App::PropertyLinkBase::importSubName(), App::ObjectIdentifier::owner, App::ExpressionParser::ExpressionImporter::reader(), App::PropertyLinkBase::restoreLabelReference(), and toString().
FC_DEFAULT_CTORS()
App::ObjectIdentifier::String::FC_DEFAULT_CTORS (String)
References draftfunctions.move::move().
getString()
const std::string & App::ObjectIdentifier::String::getString () const
Returns the string.
Referenced by App::ObjectIdentifier::access(), Sketcher::SketchObject::carbonCopy(), App::ObjectIdentifier::getDepLabels(), App::ObjectIdentifier::getPropertyComponents(), App::ObjectIdentifier::getStringList(), App::ObjectIdentifier::getSubObjectName(), App::ObjectIdentifier::hasDocumentObjectName(), App::ObjectIdentifier::importSubNames(), App::ObjectIdentifier::relabeledDocument(), App::ObjectIdentifier::replaceObject(), App::ObjectIdentifier::resolve(), App::ObjectIdentifier::resolveAmbiguity(), App::ObjectIdentifier::ResolveResults::resolveErrorString(), App::ObjectIdentifier::resolveProperty(), App::ObjectIdentifier::toPersistentString(), App::ObjectIdentifier::toString(), App::ObjectIdentifier::updateElementReference(), and App::ObjectIdentifier::updateLabelReference().
isForceIdentifier()
bool App::ObjectIdentifier::String::isForceIdentifier () const
Referenced by App::ObjectIdentifier::resolveAmbiguity(), and App::ObjectIdentifier::updateLabelReference().
isRealString()
bool App::ObjectIdentifier::String::isRealString () const
Return true is string need to be quoted.
Referenced by App::ObjectIdentifier::getDepLabels(), App::ObjectIdentifier::importSubNames(), App::ObjectIdentifier::relabeledDocument(), App::ObjectIdentifier::replaceObject(), App::ObjectIdentifier::resolveAmbiguity(), App::ObjectIdentifier::setDocumentObjectName(), App::ObjectIdentifier::toPersistentString(), and App::ObjectIdentifier::updateLabelReference().
operator const char *()
App::ObjectIdentifier::String::operator const char * () const
operator std::string()
App::ObjectIdentifier::String::operator std::string () const
Referenced by Spreadsheet_legacy.MathParser::hasNext(), and Spreadsheet_legacy.MathParser::peek().
operator!=()
bool App::ObjectIdentifier::String::operator!= (const String & other) const
operator<()
bool App::ObjectIdentifier::String::operator< (const String & other) const
operator==()
bool App::ObjectIdentifier::String::operator== (const String & other) const
operator>()
bool App::ObjectIdentifier::String::operator> (const String & other) const
operator>=()
bool App::ObjectIdentifier::String::operator>= (const String & other) const
toString()
std::string ObjectIdentifier::String::toString (bool toPython = false) const
Returns a possibly quoted string.
Get a string representation of this object identifier.
Returns
String representation.
References App::quote().
Referenced by checkImport(), App::ObjectIdentifier::getStringList(), App::ObjectIdentifier::ResolveResults::resolveErrorString(), App::ObjectIdentifier::toPersistentString(), and App::ObjectIdentifier::toString().
Friends And Related Function Documentation
ObjectIdentifier
friend class ObjectIdentifier friend
The documentation for this class was generated from the following files:
FreeCAD/src/App/ObjectIdentifier.h
FreeCAD/src/App/ObjectIdentifier.cpp