FreeCAD: PathScripts.PathStop.Stop Class Reference
PathScripts.PathStop.Stop Class Reference
Public Member Functions
def execute (self, obj)
def onChanged (self, obj, prop)
Member Function Documentation
execute()
def PathScripts.PathStop.Stop.execute (self, obj)
Referenced by ArchSite.Compass.buildCoordinates(), ArchSchedule.CommandArchSchedule.IsActive(), and FeaturePython.DistanceBolt.onChanged().
onChanged()
def PathScripts.PathStop.Stop.onChanged (self, obj, prop)
Referenced by ArchSite.Compass.buildCoordinates(), and ArchAxis.CommandArchGrid.IsActive().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Path/PathScripts/PathStop.py