FreeCAD: PathScripts.PathSurfaceSupport Namespace Reference
PathScripts.PathSurfaceSupport Namespace Reference
Classes
class FindUnifiedRegions
class OCL_Tool
class PathGeometryGenerator
class ProcessSelectedFaces
Functions
def getCrossSection (shape)
def getExtrudedShape (wire)
def getProjectedFace (tempGroup, wire)
def getShapeEnvelope (shape)
def getShapeSlice (shape)
def getSliceFromEnvelope (env)
def makeExtendedBoundBox (wBB, bbBfr, zDep)
def pathGeomToCircularPointSet (self, obj, compGeoShp)
def pathGeomToLinesPointSet (self, obj, compGeoShp)
def pathGeomToOffsetPointSet (obj, compGeoShp)
def pathGeomToSpiralPointSet (obj, compGeoShp)
def pathGeomToZigzagPointSet (self, obj, compGeoShp)
def translate (context, text, disambig=None)
Variables
closedGap
CutClimb
Part = LazyLoader('Part', globals(), 'Part')
Function Documentation
getCrossSection()
def PathScripts.PathSurfaceSupport.getCrossSection (shape)
Referenced by PathScripts.PathSurfaceSupport.FindUnifiedRegions.getUnifiedRegions(), and PathScripts.PathSurfaceSupport.ProcessSelectedFaces.preProcessModel().
getExtrudedShape()
def PathScripts.PathSurfaceSupport.getExtrudedShape (wire)
Referenced by PathScripts.PathSurfaceSupport.FindUnifiedRegions.getUnifiedRegions().
getProjectedFace()
def PathScripts.PathSurfaceSupport.getProjectedFace (tempGroup, wire)
getShapeEnvelope()
def PathScripts.PathSurfaceSupport.getShapeEnvelope (shape)
getShapeSlice()
def PathScripts.PathSurfaceSupport.getShapeSlice (shape)
Referenced by PathScripts.PathSurfaceSupport.ProcessSelectedFaces.preProcessModel().
getSliceFromEnvelope()
def PathScripts.PathSurfaceSupport.getSliceFromEnvelope (env)
Referenced by PathScripts.PathSurfaceSupport.ProcessSelectedFaces.preProcessModel().
makeExtendedBoundBox()
def PathScripts.PathSurfaceSupport.makeExtendedBoundBox (wBB, bbBfr, zDep)
pathGeomToCircularPointSet()
def PathScripts.PathSurfaceSupport.pathGeomToCircularPointSet (self, obj, compGeoShp)
pathGeomToCircularPointSet(self, obj, compGeoShp)...
Convert a compound set of arcs/circles to a set of directionally-oriented arc end points
and the corresponding center point.
pathGeomToLinesPointSet()
def PathScripts.PathSurfaceSupport.pathGeomToLinesPointSet (self, obj, compGeoShp)
pathGeomToLinesPointSet(self, obj, compGeoShp)...
Convert a compound set of sequential line segments to directionally-oriented collinear groupings.
pathGeomToOffsetPointSet()
def PathScripts.PathSurfaceSupport.pathGeomToOffsetPointSet (obj, compGeoShp)
pathGeomToOffsetPointSet(obj, compGeoShp)...
Convert a compound set of 3D profile segmented wires to 2D segments, applying linear optimization.
pathGeomToSpiralPointSet()
def PathScripts.PathSurfaceSupport.pathGeomToSpiralPointSet (obj, compGeoShp)
_pathGeomToSpiralPointSet(obj, compGeoShp)...
Convert a compound set of sequential line segments to directional, connected groupings.
pathGeomToZigzagPointSet()
def PathScripts.PathSurfaceSupport.pathGeomToZigzagPointSet (self, obj, compGeoShp)
_pathGeomToZigzagPointSet(self, obj, compGeoShp)...
Convert a compound set of sequential line segments to directionally-oriented collinear groupings
with a ZigZag directional indicator included for each collinear group.
translate()
def PathScripts.PathSurfaceSupport.translate (context, text, disambig = None)
Variable Documentation
closedGap
PathScripts.PathSurfaceSupport.closedGap
CutClimb
PathScripts.PathSurfaceSupport.CutClimb
Part
PathScripts.PathSurfaceSupport.Part = LazyLoader('Part', globals(), 'Part')