FreeCAD: TechDraw::Generic Class Reference
TechDraw::Generic Class Reference
#include <Geometry.h>
Public Member Functions
Base::Vector3d apparentInter (Generic *g)
Base::Vector3d asVector (void)
Generic ()
Generic (const TopoDS_Edge &e)
Generic is a multiline.
virtual void Restore (Base::XMLReader &r) override
virtual void Save (Base::Writer &w) const override
double slope (void)
virtual std::string toString (void) const override
~Generic ()=default
Public Member Functions inherited from TechDraw::BaseGeom
BaseGeom ()
bool closed (void)
BaseGeom * copy ()
std::string dump ()
std::vector< Base::Vector3d > findEndPoints ()
std::string getCosmeticTag (void)
Base::Vector3d getEndPoint ()
Base::Vector3d getMidPoint ()
std::vector< Base::Vector3d > getQuads ()
Base::Vector3d getStartPoint ()
boost::uuids::uuid getTag () const
virtual std::string getTagAsString (void) const
double minDist (Base::Vector3d p)
Base::Vector3d nearPoint (Base::Vector3d p)
Base::Vector3d nearPoint (const BaseGeom *p)
find point on me nearest to p
void setCosmeticTag (std::string t)
void source (int s)
int source (void)
void sourceIndex (int si)
int sourceIndex (void)
virtual ~BaseGeom ()=default
Public Attributes
std::vector< Base::Vector3d > points
Public Attributes inherited from TechDraw::BaseGeom
edgeClass classOfEdge
bool cosmetic
ExtractionType extractType
GeomType geomType
bool hlrVisible
TopoDS_Edge occEdge
int ref3D
bool reversed
Additional Inherited Members
Static Public Member Functions inherited from TechDraw::BaseGeom
static BaseGeom * baseFactory (TopoDS_Edge edge)
Convert 1 OCC edge into 1 BaseGeom (static factory method)
static bool validateEdge (TopoDS_Edge edge)
Protected Member Functions inherited from TechDraw::BaseGeom
void createNewTag ()
Protected Attributes inherited from TechDraw::BaseGeom
std::string cosmeticTag
int m_source
int m_sourceIndex
boost::uuids::uuid tag
Constructor & Destructor Documentation
Generic() [1/2]
Generic::Generic (const TopoDS_Edge & e)
Generic is a multiline.
References TechDraw::GENERIC, TechDraw::BaseGeom::geomType, TechDraw::BaseGeom::occEdge, and TechDraw::BaseGeom::reversed.
Generic() [2/2]
Generic::Generic ()
References TechDraw::GENERIC, and TechDraw::BaseGeom::geomType.
~Generic()
TechDraw::Generic::~Generic () default
Member Function Documentation
apparentInter()
Base::Vector3d Generic::apparentInter (Generic * g)
References asVector(), Base::Vector3< _Precision >::x, and Base::Vector3< _Precision >::y.
Referenced by TechDraw::DrawViewDimension::execute().
asVector()
Base::Vector3d Generic::asVector (void)
References TechDraw::BaseGeom::getEndPoint(), and TechDraw::BaseGeom::getStartPoint().
Referenced by apparentInter(), PathScripts.PathDressupDogbone.Chord::getAngleOfVector(), PathScripts.PathDressupDogbone.Chord::getDirectionOfVector(), PathScripts.PathDressupDogbone.Chord::getLength(), and slope().
Restore()
void Generic::Restore (Base::XMLReader & r) override virtual
Reimplemented from TechDraw::BaseGeom.
References Base::XMLReader::getAttributeAsFloat(), Base::XMLReader::getAttributeAsInteger(), Base::XMLReader::readElement(), Base::XMLReader::readEndElement(), TechDraw::BaseGeom::Restore(), and Base::Vector3< _Precision >::x.
Referenced by TechDraw::CosmeticEdge::Restore(), and TechDraw::CenterLine::Restore().
Save()
void Generic::Save (Base::Writer & w) const override virtual
Reimplemented from TechDraw::BaseGeom.
References Base::Writer::decInd(), Base::Writer::incInd(), Base::Writer::ind(), TechDraw::BaseGeom::Save(), and Base::Writer::Stream().
Referenced by TechDraw::CosmeticEdge::Save(), and TechDraw::CenterLine::Save().
slope()
double Generic::slope (void)
References asVector().
toString()
std::string Generic::toString (void) const override virtual
Reimplemented from TechDraw::BaseGeom.
References TechDraw::BaseGeom::toString().
Member Data Documentation
points
std::vector<Base::Vector3d> TechDraw::Generic::points
Referenced by TechDrawGui::QGIDrawingTemplate::draw(), draftguitools.gui_arcs.Arc_3Points::drawArc(), TechDraw::DrawParametricTemplate::drawLine(), TechDrawGui::QGIViewPart::geomToPainterPath(), draftguitools.gui_arcs.Arc_3Points::getPoint(), ArchCurtainWall.CommandArchCurtainWall::getPoint(), ArchTruss.CommandArchTruss::getPoint(), TechDraw::DrawViewDimension::getPointsOneEdge(), shipHydrostatics.PlotAux.Plot::plotCoeffs(), shipHydrostatics.PlotAux.Plot::plotStability(), shipHydrostatics.PlotAux.Plot::plotVolume(), draftguitools.gui_trackers.bsplineTracker::recompute(), draftguitools.gui_trackers.bezcurveTracker::recompute(), shipHydrostatics.PlotAux.Plot::spreadSheet(), draftguitools.gui_trackers.bsplineTracker::update(), draftguitools.gui_trackers.bezcurveTracker::update(), automotive_design.advanced_face::wr10(), and config_control_design.advanced_face::wr10().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/App/Geometry.h
Sources/FreeCAD/src/Mod/TechDraw/App/Geometry.cpp