FreeCAD: SpreadsheetGui::Ui_DlgSettings Class Reference
SpreadsheetGui::Ui_DlgSettings Class Reference
#include <ui_DlgSettings.h>
Public Member Functions
void retranslateUi (QWidget *SpreadsheetGui__DlgSettings)
void setupUi (QWidget *SpreadsheetGui__DlgSettings)
Public Attributes
Gui::PrefComboBox * delimiterComboBox
Gui::PrefLineEdit * escapeCharLineEdit
QGridLayout * gridLayout
QGridLayout * gridLayout_2
QGroupBox * groupBox
QSpacerItem * horizontalSpacer
Gui::PrefLineEdit * quoteCharLineEdit
QLabel * textLabel
QLabel * textLabel2
QLabel * textLabel3
QSpacerItem * verticalSpacer
Member Function Documentation
retranslateUi()
void SpreadsheetGui::Ui_DlgSettings::retranslateUi (QWidget * SpreadsheetGui__DlgSettings)
References delimiterComboBox, escapeCharLineEdit, groupBox, quoteCharLineEdit, textLabel, textLabel2, textLabel3, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void SpreadsheetGui::Ui_DlgSettings::setupUi (QWidget * SpreadsheetGui__DlgSettings)
References delimiterComboBox, escapeCharLineEdit, gridLayout, gridLayout_2, groupBox, horizontalSpacer, quoteCharLineEdit, retranslateUi(), textLabel, textLabel2, textLabel3, and verticalSpacer.
Member Data Documentation
delimiterComboBox
Gui::PrefComboBox* SpreadsheetGui::Ui_DlgSettings::delimiterComboBox
Referenced by retranslateUi(), and setupUi().
escapeCharLineEdit
Gui::PrefLineEdit* SpreadsheetGui::Ui_DlgSettings::escapeCharLineEdit
Referenced by retranslateUi(), and setupUi().
gridLayout
QGridLayout* SpreadsheetGui::Ui_DlgSettings::gridLayout
Referenced by setupUi().
gridLayout_2
QGridLayout* SpreadsheetGui::Ui_DlgSettings::gridLayout_2
Referenced by setupUi().
groupBox
QGroupBox* SpreadsheetGui::Ui_DlgSettings::groupBox
Referenced by retranslateUi(), and setupUi().
horizontalSpacer
QSpacerItem* SpreadsheetGui::Ui_DlgSettings::horizontalSpacer
Referenced by setupUi().
quoteCharLineEdit
Gui::PrefLineEdit* SpreadsheetGui::Ui_DlgSettings::quoteCharLineEdit
Referenced by retranslateUi(), and setupUi().
textLabel
QLabel* SpreadsheetGui::Ui_DlgSettings::textLabel
Referenced by retranslateUi(), and setupUi().
textLabel2
QLabel* SpreadsheetGui::Ui_DlgSettings::textLabel2
Referenced by retranslateUi(), and setupUi().
textLabel3
QLabel* SpreadsheetGui::Ui_DlgSettings::textLabel3
Referenced by retranslateUi(), and setupUi().
verticalSpacer
QSpacerItem* SpreadsheetGui::Ui_DlgSettings::verticalSpacer
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Spreadsheet/Gui/ui_DlgSettings.h