FreeCAD: Gui::PythonDebugModule Class Reference
Gui::PythonDebugModule Class Reference
#include <PythonDebugger.h>
Public Member Functions
PythonDebugModule ()
virtual ~PythonDebugModule ()
Static Public Member Functions
static void init_module (void)
Detailed Description
Author
Werner Mayer
Constructor & Destructor Documentation
PythonDebugModule()
PythonDebugModule::PythonDebugModule ()
Referenced by init_module().
~PythonDebugModule()
PythonDebugModule::~PythonDebugModule () virtual
Member Function Documentation
init_module()
void PythonDebugModule::init_module (void) static
References Gui::PythonDebugStdout::init_type(), Gui::PythonDebugStderr::init_type(), Gui::PythonDebugExcept::init_type(), and PythonDebugModule().
Referenced by Gui::Application::Application().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/PythonDebugger.h
Sources/FreeCAD/src/Gui/PythonDebugger.cpp