FreeCAD: PartGui::Ui_DlgSettingsGeneral Class Reference
PartGui::Ui_DlgSettingsGeneral Class Reference
#include <ui_DlgSettingsGeneral.h>
Public Member Functions
void retranslateUi (QWidget *PartGui__DlgSettingsGeneral)
void setupUi (QWidget *PartGui__DlgSettingsGeneral)
Public Attributes
Gui::PrefCheckBox * checkBooleanCheck
Gui::PrefCheckBox * checkBooleanRefine
Gui::PrefCheckBox * checkObjectNaming
Gui::PrefCheckBox * checkSketchBaseRefine
QGridLayout * gridLayout
QGridLayout * gridLayout_2
QGridLayout * gridLayout_3
QGroupBox * groupBox_2
QGroupBox * groupBox_3
QSpacerItem * spacerItem
Member Function Documentation
retranslateUi()
void PartGui::Ui_DlgSettingsGeneral::retranslateUi (QWidget * PartGui__DlgSettingsGeneral)
References checkBooleanCheck, checkBooleanRefine, checkObjectNaming, checkSketchBaseRefine, groupBox_2, groupBox_3, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void PartGui::Ui_DlgSettingsGeneral::setupUi (QWidget * PartGui__DlgSettingsGeneral)
References checkBooleanCheck, checkBooleanRefine, checkObjectNaming, checkSketchBaseRefine, gridLayout, gridLayout_2, gridLayout_3, groupBox_2, groupBox_3, retranslateUi(), and spacerItem.
Member Data Documentation
checkBooleanCheck
Gui::PrefCheckBox* PartGui::Ui_DlgSettingsGeneral::checkBooleanCheck
Referenced by retranslateUi(), and setupUi().
checkBooleanRefine
Gui::PrefCheckBox* PartGui::Ui_DlgSettingsGeneral::checkBooleanRefine
Referenced by retranslateUi(), and setupUi().
checkObjectNaming
Gui::PrefCheckBox* PartGui::Ui_DlgSettingsGeneral::checkObjectNaming
Referenced by retranslateUi(), and setupUi().
checkSketchBaseRefine
Gui::PrefCheckBox* PartGui::Ui_DlgSettingsGeneral::checkSketchBaseRefine
Referenced by retranslateUi(), and setupUi().
gridLayout
QGridLayout* PartGui::Ui_DlgSettingsGeneral::gridLayout
Referenced by setupUi().
gridLayout_2
QGridLayout* PartGui::Ui_DlgSettingsGeneral::gridLayout_2
Referenced by setupUi().
gridLayout_3
QGridLayout* PartGui::Ui_DlgSettingsGeneral::gridLayout_3
Referenced by setupUi().
groupBox_2
QGroupBox* PartGui::Ui_DlgSettingsGeneral::groupBox_2
Referenced by retranslateUi(), and setupUi().
groupBox_3
QGroupBox* PartGui::Ui_DlgSettingsGeneral::groupBox_3
Referenced by retranslateUi(), and setupUi().
spacerItem
QSpacerItem* PartGui::Ui_DlgSettingsGeneral::spacerItem
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Part/Gui/ui_DlgSettingsGeneral.h