FreeCAD: TechDrawGui::QGVPage Class Reference
TechDrawGui::QGVPage Class Reference
#include <QGVPage.h>
Public Types
enum RendererType { Native, OpenGL, Image }
Public Slots
void setHighQualityAntialiasing (bool highQualityAntialiasing)
Public Member Functions
void addBalloonToParent (QGIViewBalloon *balloon, QGIView *parent)
void addDimToParent (QGIViewDimension *dim, QGIView *parent)
QGIView * addDrawView (TechDraw::DrawView *view)
QGIView * addDrawViewAnnotation (TechDraw::DrawViewAnnotation *view)
QGIView * addDrawViewClip (TechDraw::DrawViewClip *view)
QGIView * addDrawViewCollection (TechDraw::DrawViewCollection *view)
QGIView * addDrawViewImage (TechDraw::DrawViewImage *view)
QGIView * addDrawViewSpreadsheet (TechDraw::DrawViewSpreadsheet *view)
QGIView * addDrawViewSymbol (TechDraw::DrawViewSymbol *view)
void addLeaderToParent (QGILeaderLine *lead, QGIView *parent)
QGIView * addProjectionGroup (TechDraw::DrawProjGroup *view)
int addQView (QGIView *view)
QGIView * addRichAnno (TechDraw::DrawRichAnno *anno)
QGIView * addViewBalloon (TechDraw::DrawViewBalloon *balloon)
QGIView * addViewDimension (TechDraw::DrawViewDimension *dim)
QGIView * addViewLeader (TechDraw::DrawLeaderLine *view)
QGIView * addViewPart (TechDraw::DrawViewPart *part)
QGIView * addViewSection (TechDraw::DrawViewPart *part)
QGIView * addWeldSymbol (TechDraw::DrawWeldSymbol *weld)
void drawBackground (QPainter *p, const QRectF &rect) override
QGIView * findParent (QGIView *) const
QGIView * findQViewForDocObj (App::DocumentObject *obj) const
find the graphic for a DocumentObject
TechDraw::DrawPage * getDrawPage ()
QGIView * getQGIVByName (std::string name)
find the graphic for DocumentObject with name
QGITemplate * getTemplate () const
std::vector< QGIView * > getViews () const
retrieve the QGIView objects currently in the scene
void postProcessXml (QTemporaryFile &tempFile, QString filename, QString pagename)
QGVPage (ViewProviderPage *vp, QGraphicsScene *s, QWidget *parent=0)
virtual void refreshViews (void)
int removeQView (QGIView *view)
int removeQViewByName (const char *name)
void removeQViewFromScene (QGIView *view)
void removeTemplate ()
void saveSvg (QString filename)
Renders the page to SVG with filename.
void setExporting (bool enable)
void setPageTemplate (TechDraw::DrawTemplate *pageTemplate)
void setRenderer (RendererType type=Native)
virtual ~QGVPage ()
Protected Member Functions
void enterEvent (QEvent *event) override
void focusOutEvent (QFocusEvent *event) override
QColor getBackgroundColor ()
void kbPanScroll (int xMove=1, int yMove=1)
void keyPressEvent (QKeyEvent *event) override
void leaveEvent (QEvent *event) override
void mouseMoveEvent (QMouseEvent *event) override
void mousePressEvent (QMouseEvent *event) override
void mouseReleaseEvent (QMouseEvent *event) override
void paintEvent (QPaintEvent *event) override
void wheelEvent (QWheelEvent *event) override
Protected Attributes
QGITemplate * pageTemplate
Static Protected Attributes
static QColor PreselectColor
static QColor SelectColor
Member Enumeration Documentation
RendererType
enum TechDrawGui::QGVPage::RendererType
Enumerator
Native
OpenGL
Image
Constructor & Destructor Documentation
QGVPage()
QGVPage::QGVPage (ViewProviderPage * vp, QGraphicsScene * s, QWidget * parent = 0)
References App::GetApplication(), getBackgroundColor(), ParameterGrp::GetBool(), TechDrawGui::ViewProviderPage::getDrawPage(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), App::DocumentObject::getNameInDocument(), App::Application::GetUserParameter(), and TechDrawGui::ViewProviderPage::setGraphicsView().
~QGVPage()
QGVPage::~QGVPage () virtual
Member Function Documentation
addBalloonToParent()
void QGVPage::addBalloonToParent (QGIViewBalloon * balloon, QGIView * parent)
References ZVALUE::DIMENSION.
Referenced by addViewBalloon(), and TechDrawGui::MDIViewPage::setBalloonGroups().
addDimToParent()
void QGVPage::addDimToParent (QGIViewDimension * dim, QGIView * parent)
References ZVALUE::DIMENSION.
Referenced by addViewDimension(), and TechDrawGui::MDIViewPage::setDimensionGroups().
addDrawView()
QGIView * QGVPage::addDrawView (TechDraw::DrawView * view)
References addQView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addDrawViewAnnotation()
QGIView * QGVPage::addDrawViewAnnotation (TechDraw::DrawViewAnnotation * view)
References addQView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addDrawViewClip()
QGIView * QGVPage::addDrawViewClip (TechDraw::DrawViewClip * view)
References addQView(), and TechDrawGui::Rez::guiX().
Referenced by TechDrawGui::MDIViewPage::attachView().
addDrawViewCollection()
QGIView * QGVPage::addDrawViewCollection (TechDraw::DrawViewCollection * view)
References addQView().
addDrawViewImage()
QGIView * QGVPage::addDrawViewImage (TechDraw::DrawViewImage * view)
References addQView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addDrawViewSpreadsheet()
QGIView * QGVPage::addDrawViewSpreadsheet (TechDraw::DrawViewSpreadsheet * view)
References addQView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addDrawViewSymbol()
QGIView * QGVPage::addDrawViewSymbol (TechDraw::DrawViewSymbol * view)
References addQView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addLeaderToParent()
void QGVPage::addLeaderToParent (QGILeaderLine * lead, QGIView * parent)
References ZVALUE::DIMENSION.
Referenced by addViewLeader(), and TechDrawGui::MDIViewPage::setLeaderGroups().
addProjectionGroup()
QGIView * QGVPage::addProjectionGroup (TechDraw::DrawProjGroup * view)
References addQView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addQView()
int QGVPage::addQView (QGIView * view)
References findParent(), getQGIVByName(), and TechDrawGui::Rez::guiX().
Referenced by addDrawView(), addDrawViewAnnotation(), addDrawViewClip(), addDrawViewCollection(), addDrawViewImage(), addDrawViewSpreadsheet(), addDrawViewSymbol(), addProjectionGroup(), addViewPart(), and addViewSection().
addRichAnno()
QGIView * QGVPage::addRichAnno (TechDraw::DrawRichAnno * anno)
References TechDraw::DrawRichAnno::AnnoParent, findQViewForDocObj(), App::PropertyLink::getValue(), and TechDrawGui::QGIRichAnno::updateView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addViewBalloon()
QGIView * QGVPage::addViewBalloon (TechDraw::DrawViewBalloon * balloon)
References addBalloonToParent(), findParent(), getDrawPage(), and TechDraw::DrawViewBalloon::origin.
Referenced by TechDrawGui::MDIViewPage::attachView().
addViewDimension()
QGIView * QGVPage::addViewDimension (TechDraw::DrawViewDimension * dim)
References addDimToParent(), and findParent().
Referenced by TechDrawGui::MDIViewPage::attachView().
addViewLeader()
QGIView * QGVPage::addViewLeader (TechDraw::DrawLeaderLine * view)
References addLeaderToParent(), findParent(), TechDrawGui::QGILeaderLine::setLeaderFeature(), and TechDrawGui::QGILeaderLine::updateView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addViewPart()
QGIView * QGVPage::addViewPart (TechDraw::DrawViewPart * part)
References addQView(), and findQViewForDocObj().
Referenced by TechDrawGui::MDIViewPage::attachView().
addViewSection()
QGIView * QGVPage::addViewSection (TechDraw::DrawViewPart * part)
References addQView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addWeldSymbol()
QGIView * QGVPage::addWeldSymbol (TechDraw::DrawWeldSymbol * weld)
References Base::Console(), Base::ConsoleSingleton::Error(), findQViewForDocObj(), App::PropertyLink::getValue(), TechDraw::DrawWeldSymbol::Leader, TechDrawGui::QGIWeldSymbol::setFeature(), TechDrawGui::QGIView::setViewFeature(), and TechDrawGui::QGIWeldSymbol::updateView().
Referenced by TechDrawGui::MDIViewPage::attachView().
drawBackground()
void QGVPage::drawBackground (QPainter * p, const QRectF & rect) override
References TechDrawGui::ViewProviderPage::getDrawPage(), TechDraw::DrawPage::getPageHeight(), TechDraw::DrawPage::getPageWidth(), TechDrawGui::Rez::guiX(), and TechDraw::DrawPage::hasValidTemplate().
enterEvent()
void QGVPage::enterEvent (QEvent * event) override protected
References getDrawPage().
findParent()
QGIView * QGVPage::findParent (QGIView * view) const
References App::DocumentObject::getNameInDocument(), App::PropertyLink::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyLinkSubList::getValues(), TechDrawGui::QGIView::getViewObject(), getViews(), TechDraw::DrawLeaderLine::LeaderParent, TechDraw::DrawViewDimension::References2D, TechDraw::DrawViewBalloon::SourceView, and TechDraw::DrawViewCollection::Views.
Referenced by addQView(), addViewBalloon(), addViewDimension(), addViewLeader(), TechDrawGui::MDIViewPage::setBalloonGroups(), TechDrawGui::MDIViewPage::setDimensionGroups(), and TechDrawGui::MDIViewPage::setLeaderGroups().
findQViewForDocObj()
QGIView * QGVPage::findQViewForDocObj (App::DocumentObject * obj) const
find the graphic for a DocumentObject
References getViews().
Referenced by addRichAnno(), addViewPart(), addWeldSymbol(), TechDrawGui::MDIViewPage::fixOrphans(), TechDrawGui::TaskLeaderLine::onTrackerClicked(), TechDrawGui::MDIViewPage::selectQGIView(), TechDrawGui::TaskCosVertex::setEditCursor(), TechDrawGui::TaskLeaderLine::setEditCursor(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), and TechDrawGui::TaskRichAnno::TaskRichAnno().
focusOutEvent()
void QGVPage::focusOutEvent (QFocusEvent * event) override protected
getBackgroundColor()
QColor QGVPage::getBackgroundColor (void) protected
References App::Color::asValue(), App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetUnsigned(), App::Application::GetUserParameter(), and App::Color::setPackedValue().
Referenced by QGVPage().
getDrawPage()
TechDraw::DrawPage * QGVPage::getDrawPage ()
References TechDrawGui::ViewProviderPage::getDrawPage().
Referenced by addViewBalloon(), enterEvent(), TechDrawGui::DrawGuiUtil::findPage(), leaveEvent(), and mouseReleaseEvent().
getQGIVByName()
QGIView * QGVPage::getQGIVByName (std::string name)
find the graphic for DocumentObject with name
References TechDrawGui::QGIView::getViewName().
Referenced by addQView().
getTemplate()
QGITemplate * QGVPage::getTemplate () const
References pageTemplate.
Referenced by TechDrawGui::ViewProviderTemplate::getQTemplate(), and TechDrawGui::MDIViewPage::updateTemplate().
getViews()
std::vector< QGIView * > QGVPage::getViews () const
retrieve the QGIView objects currently in the scene
Referenced by TechDrawGui::MDIViewPage::clearSceneSelection(), findParent(), findQViewForDocObj(), TechDrawGui::MDIViewPage::fixOrphans(), TechDrawGui::MDIViewPage::hasQView(), TechDrawGui::MDIViewPage::redraw1View(), TechDrawGui::MDIViewPage::redrawAllViews(), removeQViewByName(), TechDrawGui::MDIViewPage::setBalloonGroups(), TechDrawGui::MDIViewPage::setDimensionGroups(), and TechDrawGui::MDIViewPage::setLeaderGroups().
kbPanScroll()
void QGVPage::kbPanScroll (int xMove = 1, int yMove = 1) protected
Referenced by keyPressEvent().
keyPressEvent()
void QGVPage::keyPressEvent (QKeyEvent * event) override protected
References kbPanScroll(), and draftfunctions.scale::scale().
leaveEvent()
void QGVPage::leaveEvent (QEvent * event) override protected
References getDrawPage().
mouseMoveEvent()
void QGVPage::mouseMoveEvent (QMouseEvent * event) override protected
mousePressEvent()
void QGVPage::mousePressEvent (QMouseEvent * event) override protected
mouseReleaseEvent()
void QGVPage::mouseReleaseEvent (QMouseEvent * event) override protected
References TechDraw::DrawPage::balloonParent, Gui::Command::commitCommand(), App::DocumentObject::getDocument(), getDrawPage(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), App::Document::getUniqueObjectName(), App::PropertyQuantity::getValue(), Gui::Command::openCommand(), TechDraw::DrawViewBalloon::origin, draftutils.translate::QT_TRANSLATE_NOOP, App::DocumentObject::recomputeFeature(), App::PropertyLink::setValue(), App::PropertyQuantity::setValue(), TechDraw::DrawViewBalloon::SourceView, and TechDraw::DrawView::X.
paintEvent()
void QGVPage::paintEvent (QPaintEvent * event) override protected
References OfflineRenderingUtils::render().
postProcessXml()
void QGVPage::postProcessXml (QTemporaryFile & tempFile, QString filename, QString pagename)
References Base::Console(), Base::FileInfo::fileName(), QDomNodeModel::fromDomNode(), TechDrawGui::QGISVGTemplate::getSVGTemplate(), App::PropertyFileIncluded::getValue(), App::PropertyString::getValue(), TechDrawGui::Rez::guiX(), Base::ConsoleSingleton::Message(), TechDraw::DrawSVGTemplate::PageResult, pageTemplate, TechDraw::DrawSVGTemplate::Template, and QDomNodeModel::toDomNode().
Referenced by saveSvg().
refreshViews()
void QGVPage::refreshViews (void) virtual
References TechDrawGui::QGIView::updateView().
Referenced by TechDrawGui::MDIViewPage::print(), and saveSvg().
removeQView()
int QGVPage::removeQView (QGIView * view)
References removeQViewFromScene().
Referenced by TechDrawGui::MDIViewPage::fixOrphans().
removeQViewByName()
int QGVPage::removeQViewByName (const char * name)
References getViews(), removeQViewFromScene(), and TechDrawGui::QGIView::type().
Referenced by TechDrawGui::MDIViewPage::onDeleteObject().
removeQViewFromScene()
void QGVPage::removeQViewFromScene (QGIView * view)
References TechDrawGui::QGIView::removeChild().
Referenced by removeQView(), and removeQViewByName().
removeTemplate()
void QGVPage::removeTemplate ()
References pageTemplate.
Referenced by setPageTemplate().
saveSvg()
void QGVPage::saveSvg (QString filename)
Renders the page to SVG with filename.
References Gui::SelectionSingleton::clearSelection(), App::DocumentObject::getDocument(), TechDrawGui::ViewProviderPage::getDrawPage(), TechDrawGui::ViewProviderPage::getFrameState(), App::Document::getName(), App::DocumentObject::getNameInDocument(), TechDraw::DrawPage::getPageHeight(), TechDraw::DrawPage::getPageWidth(), TechDrawGui::Rez::guiX(), pageTemplate, postProcessXml(), refreshViews(), Gui::Selection(), setExporting(), TechDrawGui::ViewProviderPage::setFrameState(), and TechDrawGui::ViewProviderPage::setTemplateMarkers().
Referenced by TechDrawGui::MDIViewPage::saveSVG().
setExporting()
void QGVPage::setExporting (bool enable)
References TechDrawGui::QGIRichAnno::setExporting(), and TechDrawGui::QGIViewPart::setExporting().
Referenced by saveSvg().
setHighQualityAntialiasing
void QGVPage::setHighQualityAntialiasing (bool highQualityAntialiasing) slot
setPageTemplate()
void QGVPage::setPageTemplate (TechDraw::DrawTemplate * pageTemplate)
References Base::Persistence::getClassTypeId(), pageTemplate, removeTemplate(), TechDrawGui::QGITemplate::setTemplate(), and TechDrawGui::QGITemplate::updateView().
Referenced by TechDrawGui::MDIViewPage::attachTemplate().
setRenderer()
void QGVPage::setRenderer (RendererType type = Native)
References OpenGL.
wheelEvent()
void QGVPage::wheelEvent (QWheelEvent * event) override protected
References draftfunctions.scale::scale(), and draftutils.translate::translate().
Member Data Documentation
pageTemplate
QGITemplate* TechDrawGui::QGVPage::pageTemplate protected
Referenced by getTemplate(), postProcessXml(), removeTemplate(), saveSvg(), and setPageTemplate().
PreselectColor
QColor TechDrawGui::QGVPage::PreselectColor static protected
SelectColor
QColor TechDrawGui::QGVPage::SelectColor static protected
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGVPage.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGVPage.cpp