FreeCAD: WebGui::WebView Class Reference
WebGui::WebView Class Reference
#include <BrowserView.h>
Signals
void openLinkInExternalBrowser (const QUrl &)
void openLinkInNewWindow (const QUrl &)
void viewSource (const QUrl &)
Public Member Functions
WebView (QWidget *parent=nullptr)
Constructs a WebView widget which can be zoomed with Ctrl+Mousewheel.
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *event)
void mousePressEvent (QMouseEvent *event)
void wheelEvent (QWheelEvent *event)
Constructor & Destructor Documentation
WebView()
WebView::WebView (QWidget * parent = nullptr)
Constructs a WebView widget which can be zoomed with Ctrl+Mousewheel.
Member Function Documentation
contextMenuEvent()
void WebView::contextMenuEvent (QContextMenuEvent * event) protected
References draftgeoutils.intersections::connect().
mousePressEvent()
void WebView::mousePressEvent (QMouseEvent * event) protected
References openLinkInNewWindow().
openLinkInExternalBrowser
void WebGui::WebView::openLinkInExternalBrowser (const QUrl &) signal
openLinkInNewWindow
void WebGui::WebView::openLinkInNewWindow (const QUrl &) signal
Referenced by mousePressEvent().
viewSource
void WebGui::WebView::viewSource (const QUrl &) signal
wheelEvent()
void WebView::wheelEvent (QWheelEvent * event) protected
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Web/Gui/BrowserView.h
FreeCAD/src/Mod/Web/Gui/BrowserView.cpp