FreeCAD: Gui::VectorTableModel Class Reference
Gui::VectorTableModel Class Reference
#include <VectorListEditor.h>
Public Member Functions
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Qt::ItemFlags flags (const QModelIndex &index) const
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
virtual bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
virtual QModelIndex parent (const QModelIndex &index) const
virtual bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
void setValues (const QList< Base::Vector3d > &d)
const QList< Base::Vector3d > & values () const
VectorTableModel (int decimals, QObject *parent=nullptr)
Constructor & Destructor Documentation
VectorTableModel()
VectorTableModel::VectorTableModel (int decimals, QObject * parent = nullptr)
Member Function Documentation
columnCount()
int VectorTableModel::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
data()
QVariant VectorTableModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
Referenced by Mod.Show.mTempoVis.TempoVis::activateWorkbench(), Mod.Show.SceneDetail.SceneDetail::apply_data(), importIFClegacy.IfcSchema::capitalize(), Mod.Show.mTempoVis.TempoVis::forget(), Mod.Show.mTempoVis.TempoVis::forgetDetail(), Mod.Show.mTempoVis.TempoVis::has(), ArchSchedule.CommandArchSchedule::IsActive(), importIFClegacy.IfcSchema::readEntities(), importIFClegacy.IfcSchema::readTypes(), Mod.Show.mTempoVis.TempoVis::restore(), Mod.Show.mTempoVis.TempoVis::save(), Gui::VectorListEditor::setValues(), Mod.Show.mTempoVis.TempoVis::stored_val(), FeaturePython.ViewProviderOctahedron::updateData(), and Dice3DS.dom3ds.UndefinedChunk::write().
flags()
Qt::ItemFlags VectorTableModel::flags (const QModelIndex & index) const
headerData()
QVariant VectorTableModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
insertRows()
bool VectorTableModel::insertRows (int row, int count, const QModelIndex & parent = QModelIndex()) virtual
References parent().
parent()
QModelIndex VectorTableModel::parent (const QModelIndex & index) const virtual
Referenced by PathScripts.PathSimulatorGui.CAMSimTaskUi::accept(), Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium(), insertRows(), PathScripts.PathSimulatorGui.CAMSimTaskUi::reject(), removeRows(), and PathScripts.PathOpGui.TaskPanelPage::setParent().
removeRows()
bool VectorTableModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex()) virtual
References parent().
rowCount()
int VectorTableModel::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Referenced by package_list.PackageListItemModel::append_item(), and package_list.PackageListItemModel::clear().
setData()
bool VectorTableModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole)
Referenced by package_list.PackageListItemModel::update_item_icon(), and package_list.PackageListItemModel::update_item_status().
setValues()
void VectorTableModel::setValues (const QList< Base::Vector3d > & d)
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle(), and Gui::VectorListEditor::setValues().
values()
const QList< Base::Vector3d > & VectorTableModel::values () const
Referenced by Gui::VectorListEditor::accept(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::addInterval(), ifc4.ifcstructuralloadconfiguration::validlistsize(), and Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::value().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/VectorListEditor.h
FreeCAD/src/Gui/VectorListEditor.cpp