FreeCAD: femexamples.manager Namespace Reference
femexamples.manager Namespace Reference
Functions
def add_explanation_obj (doc, the_text)
def get_header (information)
def get_meshname ()
def init_doc (doc=None)
def print_info_dict (information)
def run_all ()
def run_analysis (doc, base_name, filepath="", run_solver=False)
def run_example (example, solver=None, base_name=None, run_solver=False)
def setup_all ()
Function Documentation
add_explanation_obj()
def femexamples.manager.add_explanation_obj (doc, the_text)
get_header()
def femexamples.manager.get_header (information)
References femexamples.manager.print_info_dict().
get_meshname()
def femexamples.manager.get_meshname ()
init_doc()
def femexamples.manager.init_doc (doc = None)
print_info_dict()
def femexamples.manager.print_info_dict (information)
Referenced by femexamples.manager.get_header().
run_all()
def femexamples.manager.run_all ()
References femexamples.manager.run_example().
run_analysis()
def femexamples.manager.run_analysis (doc, base_name, filepath = "", run_solver = False)
Referenced by femexamples.manager.run_example().
run_example()
def femexamples.manager.run_example (example, solver = None, base_name = None, run_solver = False)
References femexamples.manager.run_analysis().
Referenced by femexamples.manager.run_all(), and femexamples.manager.setup_all().
setup_all()
def femexamples.manager.setup_all ()
References femexamples.manager.run_example().