FreeCAD: Mod.PartDesign.SprocketFeature.Sprocket Class Reference
Mod.PartDesign.SprocketFeature.Sprocket Class Reference
Public Member Functions
def execute (self, obj)
Public Attributes
Type
Static Public Attributes
dictionary SprocketReferenceRollerTable
Detailed Description
The Sprocket object
    ANSI B29.1-2011 standard roller chain sizes in USCS units (inches)
    {size: [Pitch, Roller Diameter]}
Member Function Documentation
execute()
def Mod.PartDesign.SprocketFeature.Sprocket.execute (self, obj)
Referenced by draftobjects.facebinder.Facebinder.addSubobjects(), PathScripts.PathDressupDogbone.ObjectDressup.boneStateList(), ArchSite.Compass.buildCoordinates(), PathScripts.PathDressupHoldingTags.ObjectTagDressup.generateTags(), ArchPanel.PanelCut.getWires(), ArchSchedule.CommandArchSchedule.IsActive(), Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), FeaturePython.DistanceBolt.onChanged(), PathScripts.PathStock.StockFromBase.onChanged(), PathScripts.PathStock.StockCreateBox.onChanged(), PathScripts.PathStock.StockCreateCylinder.onChanged(), draftobjects.draftlink.DraftLink.onDocumentRestored(), draftobjects.patharray.PathArray.onDocumentRestored(), and draftobjects.pathtwistedarray.PathTwistedArray.onDocumentRestored().
Member Data Documentation
SprocketReferenceRollerTable
dictionary Mod.PartDesign.SprocketFeature.Sprocket.SprocketReferenceRollerTable static
Initial value:
=  {"ANSI 25": [0.250, 0.130, 0.110],
                           "ANSI 35": [0.375, 0.200, 0.168],
                           "ANSI 41": [0.500, 0.306, 0.227],
                           "ANSI 40": [0.500, 0.312, 0.284],
                           "ANSI 50": [0.625, 0.400, 0.343],
                           "ANSI 60": [0.750, 0.469, 0.459],
                           "ANSI 80": [1.000, 0.625, 0.575],
                           "ANSI 100":[1.250, 0.750, 0.692],
                           "ANSI 120":[1.500, 0.875, 0.924],
                           "ANSI 140":[1.750, 1.000, 0.924],
                           "ANSI 160":[2.000, 1.125, 1.156],
                           "ANSI 180":[2.250, 1.460, 1.301],
                           "ANSI 200":[2.500, 1.562, 1.389],
                           "ANSI 240":[3.000, 1.875, 1.738],
                           "Bicycle with Derailleur":[0.500, 0.3125, 0.11],
                           "Bicycle without Derailleur":[0.500, 0.3125, 0.084],
                           "ISO 606 06B":[0.375, 5.72/25.4, 5.2/25.4],
                           "ISO 606 08B":[0.500, 7.75/25.4, 7.0/25.4],
                           "ISO 606 10B":[0.625, 9.65/25.4, 9.1/25.4],
                           "ISO 606 12B":[0.750, 11.68/25.4, 11.1/25.4],
                           "ISO 606 16B":[1.000, 17.02/25.4, 16.2/25.4],
                           "ISO 606 20B":[1.250, 19.56/25.4, 18.5/25.4],
                           "ISO 606 24B":[1.500, 25.4/25.4, 24.1/25.4],
                           "Motorcycle 420":[0.500, 0.3125, 0.227],
                           "Motorcycle 425":[0.500, 0.3125, 0.284],
                           "Motorcycle 428":[0.500, 0.335, 0.284],
                           "Motorcycle 520":[0.625, 0.400, 0.227],
                           "Motorcycle 525":[0.625, 0.400, 0.284],
                           "Motorcycle 530":[0.625, 0.400, 0.343],
                           "Motorcycle 630":[0.750, 0.400, 0.343]}
Type
Mod.PartDesign.SprocketFeature.Sprocket.Type
Referenced by ArchPanel.CommandPanelSheet.Activated(), ArchStructure.CommandStructuralSystem.Activated(), draftobjects.draft_annotation.DraftAnnotation.add_missing_properties_0v19(), ArchStructure.StructSelectionObserver.addSelection(), ArchSite.Compass.buildCoordinates(), ArchComponent.Component.execute(), draftobjects.layer.LayerContainer.execute(), ArchSchedule.CommandArchSchedule.IsActive(), draftobjects.layer.Layer.set_properties(), and ArchReference.ArchReference.setProperties().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/PartDesign/SprocketFeature.py