FreeCAD: Part::GeometrySurfacePy Class Reference
Part::GeometrySurfacePy Class Reference
The python export class for GeomSurface.
#include <GeometrySurfacePy.h>
Public Types
typedef GeomSurface * PointerType
Public Types inherited from Part::GeometryPy
typedef Geometry * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
GeometrySurfacePy (GeomSurface *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Part::GeometryPy
GeometryPy (Geometry *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * clone (PyObject *args)
implementer for the clone() method
PyObject * hasExtensionOfType (PyObject *args)
implementer for the hasExtensionOfType() method
PyObject * hasExtensionOfName (PyObject *args)
implementer for the hasExtensionOfName() method
PyObject * getExtensionOfType (PyObject *args)
implementer for the getExtensionOfType() method
PyObject * getExtensionOfName (PyObject *args)
implementer for the getExtensionOfName() method
PyObject * setExtension (PyObject *args)
implementer for the setExtension() method
PyObject * deleteExtensionOfType (PyObject *args)
implementer for the deleteExtensionOfType() method
PyObject * deleteExtensionOfName (PyObject *args)
implementer for the deleteExtensionOfName() method
PyObject * getExtensions (PyObject *args)
implementer for the getExtensions() method
Py::String getTag (void) const
getter for the Tag attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geometry * getGeometryPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::GeometryPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_clone (PyObject *self, PyObject *args)
callback for the clone() method
static PyObject * staticCallback_hasExtensionOfType (PyObject *self, PyObject *args)
callback for the hasExtensionOfType() method
static PyObject * staticCallback_hasExtensionOfName (PyObject *self, PyObject *args)
callback for the hasExtensionOfName() method
static PyObject * staticCallback_getExtensionOfType (PyObject *self, PyObject *args)
callback for the getExtensionOfType() method
static PyObject * staticCallback_getExtensionOfName (PyObject *self, PyObject *args)
callback for the getExtensionOfName() method
static PyObject * staticCallback_setExtension (PyObject *self, PyObject *args)
callback for the setExtension() method
static PyObject * staticCallback_deleteExtensionOfType (PyObject *self, PyObject *args)
callback for the deleteExtensionOfType() method
static PyObject * staticCallback_deleteExtensionOfName (PyObject *self, PyObject *args)
callback for the deleteExtensionOfName() method
static PyObject * staticCallback_getExtensions (PyObject *self, PyObject *args)
callback for the getExtensions() method
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of GeometrySurfacePy.
static PyMethodDef Methods []
Methods structure of GeometrySurfacePy.
static PyTypeObject Type
Type structure of GeometrySurfacePy.
Static Public Attributes inherited from Part::GeometryPy
static PyGetSetDef GetterSetter []
Attribute structure of GeometryPy.
static PyMethodDef Methods []
Methods structure of GeometryPy.
static PyTypeObject Type
Type structure of GeometryPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~GeometrySurfacePy ()
Protected Member Functions inherited from Part::GeometryPy
~GeometryPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * toShape (PyObject *args)
implementer for the toShape() method
PyObject * getD0 (PyObject *args)
implementer for the getD0() method
PyObject * getDN (PyObject *args)
implementer for the getDN() method
PyObject * value (PyObject *args)
implementer for the value() method
PyObject * tangent (PyObject *args)
implementer for the tangent() method
PyObject * normal (PyObject *args)
implementer for the normal() method
PyObject * projectPoint (PyObject *args, PyObject *kwd)
implementer for the projectPoint() method
PyObject * isUmbillic (PyObject *args)
implementer for the isUmbillic() method
PyObject * curvature (PyObject *args)
implementer for the curvature() method
PyObject * curvatureDirections (PyObject *args)
implementer for the curvatureDirections() method
PyObject * bounds (PyObject *args)
implementer for the bounds() method
PyObject * isPlanar (PyObject *args)
implementer for the isPlanar() method
PyObject * uIso (PyObject *args)
implementer for the uIso() method
PyObject * vIso (PyObject *args)
implementer for the vIso() method
PyObject * isUPeriodic (PyObject *args)
implementer for the isUPeriodic() method
PyObject * isVPeriodic (PyObject *args)
implementer for the isVPeriodic() method
PyObject * isUClosed (PyObject *args)
implementer for the isUClosed() method
PyObject * isVClosed (PyObject *args)
implementer for the isVClosed() method
PyObject * UPeriod (PyObject *args)
implementer for the UPeriod() method
PyObject * VPeriod (PyObject *args)
implementer for the VPeriod() method
PyObject * parameter (PyObject *args)
implementer for the parameter() method
PyObject * toBSpline (PyObject *args, PyObject *kwd)
implementer for the toBSpline() method
PyObject * intersect (PyObject *args)
implementer for the intersect() method
PyObject * intersectSS (PyObject *args)
implementer for the intersectSS() method
static PyObject * staticCallback_toShape (PyObject *self, PyObject *args)
callback for the toShape() method
static PyObject * staticCallback_getD0 (PyObject *self, PyObject *args)
callback for the getD0() method
static PyObject * staticCallback_getDN (PyObject *self, PyObject *args)
callback for the getDN() method
static PyObject * staticCallback_value (PyObject *self, PyObject *args)
callback for the value() method
static PyObject * staticCallback_tangent (PyObject *self, PyObject *args)
callback for the tangent() method
static PyObject * staticCallback_normal (PyObject *self, PyObject *args)
callback for the normal() method
static PyObject * staticCallback_projectPoint (PyObject *self, PyObject *args, PyObject *kwd)
callback for the projectPoint() method
static PyObject * staticCallback_isUmbillic (PyObject *self, PyObject *args)
callback for the isUmbillic() method
static PyObject * staticCallback_curvature (PyObject *self, PyObject *args)
callback for the curvature() method
static PyObject * staticCallback_curvatureDirections (PyObject *self, PyObject *args)
callback for the curvatureDirections() method
static PyObject * staticCallback_bounds (PyObject *self, PyObject *args)
callback for the bounds() method
static PyObject * staticCallback_isPlanar (PyObject *self, PyObject *args)
callback for the isPlanar() method
static PyObject * staticCallback_uIso (PyObject *self, PyObject *args)
callback for the uIso() method
static PyObject * staticCallback_vIso (PyObject *self, PyObject *args)
callback for the vIso() method
static PyObject * staticCallback_isUPeriodic (PyObject *self, PyObject *args)
callback for the isUPeriodic() method
static PyObject * staticCallback_isVPeriodic (PyObject *self, PyObject *args)
callback for the isVPeriodic() method
static PyObject * staticCallback_isUClosed (PyObject *self, PyObject *args)
callback for the isUClosed() method
static PyObject * staticCallback_isVClosed (PyObject *self, PyObject *args)
callback for the isVClosed() method
static PyObject * staticCallback_UPeriod (PyObject *self, PyObject *args)
callback for the UPeriod() method
static PyObject * staticCallback_VPeriod (PyObject *self, PyObject *args)
callback for the VPeriod() method
static PyObject * staticCallback_parameter (PyObject *self, PyObject *args)
callback for the parameter() method
static PyObject * staticCallback_toBSpline (PyObject *self, PyObject *args, PyObject *kwd)
callback for the toBSpline() method
static PyObject * staticCallback_intersect (PyObject *self, PyObject *args)
callback for the intersect() method
static PyObject * staticCallback_intersectSS (PyObject *self, PyObject *args)
callback for the intersectSS() method
callbacks and implementers for the python object attributes
Py::String getContinuity (void) const
getter for the Continuity attribute
Py::Object getRotation (void) const
getter for the Rotation attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomSurface * getGeomSurfacePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getContinuity (PyObject *self, void *closure)
getter callback for the Continuity attribute
static int staticCallback_setContinuity (PyObject *self, PyObject *value, void *closure)
setter callback for the Continuity attribute
static PyObject * staticCallback_getRotation (PyObject *self, void *closure)
getter callback for the Rotation attribute
static int staticCallback_setRotation (PyObject *self, PyObject *value, void *closure)
setter callback for the Rotation attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeomSurface.
Member Typedef Documentation
PointerType
typedef GeomSurface* Part::GeometrySurfacePy::PointerType
Constructor & Destructor Documentation
~GeometrySurfacePy()
GeometrySurfacePy::~GeometrySurfacePy () protected
GeometrySurfacePy()
GeometrySurfacePy::GeometrySurfacePy (GeomSurface * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
bounds()
PyObject * GeometrySurfacePy::bounds (PyObject * args)
implementer for the bounds() method
References Part::GeometryPy::getGeometryPtr(), and draftgeoutils.general::v1().
Referenced by staticCallback_bounds().
curvature()
PyObject * GeometrySurfacePy::curvature (PyObject * args)
implementer for the curvature() method
References Part::GeomSurface::Gaussian, getGeomSurfacePtr(), Part::GeomSurface::Maximum, Part::GeomSurface::Mean, Part::GeomSurface::Minimum, and Part::PartExceptionOCCError.
Referenced by staticCallback_curvature().
curvatureDirections()
PyObject * GeometrySurfacePy::curvatureDirections (PyObject * args)
implementer for the curvatureDirections() method
References getGeomSurfacePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_curvatureDirections().
getContinuity()
Py::String GeometrySurfacePy::getContinuity (void) const
getter for the Continuity attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getContinuity().
getCustomAttributes()
PyObject * GeometrySurfacePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getD0()
PyObject * GeometrySurfacePy::getD0 (PyObject * args)
implementer for the getD0() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getD0().
getDN()
PyObject * GeometrySurfacePy::getDN (PyObject * args)
implementer for the getDN() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getDN().
getGeomSurfacePtr()
GeomSurface * GeometrySurfacePy::getGeomSurfacePtr (void) const
getter for the object handled by this class
Referenced by curvature(), curvatureDirections(), isUmbillic(), normal(), and Part::RectangularTrimmedSurfacePy::PyInit().
getRotation()
Py::Object GeometrySurfacePy::getRotation (void) const
getter for the Rotation attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getRotation().
GetType()
virtual PyTypeObject* Part::GeometrySurfacePy::GetType (void) virtual
Reimplemented from Part::GeometryPy.
Reimplemented in Part::ToroidPy, Part::SurfaceOfRevolutionPy, Part::SurfaceOfExtrusionPy, Part::SpherePy, Part::RectangularTrimmedSurfacePy, Part::PlateSurfacePy, Part::PlanePy, Part::OffsetSurfacePy, Part::CylinderPy, Part::ConePy, Part::BSplineSurfacePy, and Part::BezierSurfacePy.
intersect()
PyObject * GeometrySurfacePy::intersect (PyObject * args)
implementer for the intersect() method
References Part::GeometryPy::getGeometryPtr(), Part::GeometryCurvePy::intersectCS(), intersectSS(), Part::GeometryCurvePy::Type, and Type.
Referenced by staticCallback_intersect().
intersectSS()
PyObject * GeometrySurfacePy::intersectSS (PyObject * args)
implementer for the intersectSS() method
References Part::GeometryPy::getGeometryPtr(), Part::makeGeometryCurvePy(), and Type.
Referenced by intersect(), and staticCallback_intersectSS().
isPlanar()
PyObject * GeometrySurfacePy::isPlanar (PyObject * args)
implementer for the isPlanar() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_isPlanar().
isUClosed()
PyObject * GeometrySurfacePy::isUClosed (PyObject * args)
implementer for the isUClosed() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_isUClosed().
isUmbillic()
PyObject * GeometrySurfacePy::isUmbillic (PyObject * args)
implementer for the isUmbillic() method
References getGeomSurfacePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_isUmbillic().
isUPeriodic()
PyObject * GeometrySurfacePy::isUPeriodic (PyObject * args)
implementer for the isUPeriodic() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_isUPeriodic().
isVClosed()
PyObject * GeometrySurfacePy::isVClosed (PyObject * args)
implementer for the isVClosed() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_isVClosed().
isVPeriodic()
PyObject * GeometrySurfacePy::isVPeriodic (PyObject * args)
implementer for the isVPeriodic() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_isVPeriodic().
normal()
PyObject * GeometrySurfacePy::normal (PyObject * args)
implementer for the normal() method
References getGeomSurfacePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_normal().
parameter()
PyObject * GeometrySurfacePy::parameter (PyObject * args)
implementer for the parameter() method
References Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, and Base::VectorPy::Type.
Referenced by staticCallback_parameter().
projectPoint()
PyObject * GeometrySurfacePy::projectPoint (PyObject * args, PyObject * kwd)
implementer for the projectPoint() method
References DraftVecUtils::dist(), Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_projectPoint().
PyInit()
int GeometrySurfacePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::GeometryPy.
Reimplemented in Part::ToroidPy, Part::SurfaceOfRevolutionPy, Part::SurfaceOfExtrusionPy, Part::SpherePy, Part::RectangularTrimmedSurfacePy, Part::PlateSurfacePy, Part::PlanePy, Part::OffsetSurfacePy, Part::CylinderPy, Part::ConePy, Part::BSplineSurfacePy, and Part::BezierSurfacePy.
PyMake()
PyObject * GeometrySurfacePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string GeometrySurfacePy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int GeometrySurfacePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_bounds()
PyObject * GeometrySurfacePy::staticCallback_bounds (PyObject * self, PyObject * args) static
callback for the bounds() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, bounds(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_curvature()
PyObject * GeometrySurfacePy::staticCallback_curvature (PyObject * self, PyObject * args) static
callback for the curvature() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, curvature(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_curvatureDirections()
PyObject * GeometrySurfacePy::staticCallback_curvatureDirections (PyObject * self, PyObject * args) static
callback for the curvatureDirections() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, curvatureDirections(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getContinuity()
PyObject * GeometrySurfacePy::staticCallback_getContinuity (PyObject * self, void * closure) static
getter callback for the Continuity attribute
References Base::BaseExceptionFreeCADError, getContinuity(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getD0()
PyObject * GeometrySurfacePy::staticCallback_getD0 (PyObject * self, PyObject * args) static
callback for the getD0() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getD0(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getDN()
PyObject * GeometrySurfacePy::staticCallback_getDN (PyObject * self, PyObject * args) static
callback for the getDN() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getDN(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRotation()
PyObject * GeometrySurfacePy::staticCallback_getRotation (PyObject * self, void * closure) static
getter callback for the Rotation attribute
References Base::BaseExceptionFreeCADError, getRotation(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_intersect()
PyObject * GeometrySurfacePy::staticCallback_intersect (PyObject * self, PyObject * args) static
callback for the intersect() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, intersect(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_intersectSS()
PyObject * GeometrySurfacePy::staticCallback_intersectSS (PyObject * self, PyObject * args) static
callback for the intersectSS() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, intersectSS(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isPlanar()
PyObject * GeometrySurfacePy::staticCallback_isPlanar (PyObject * self, PyObject * args) static
callback for the isPlanar() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isPlanar(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isUClosed()
PyObject * GeometrySurfacePy::staticCallback_isUClosed (PyObject * self, PyObject * args) static
callback for the isUClosed() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isUClosed(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isUmbillic()
PyObject * GeometrySurfacePy::staticCallback_isUmbillic (PyObject * self, PyObject * args) static
callback for the isUmbillic() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isUmbillic(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isUPeriodic()
PyObject * GeometrySurfacePy::staticCallback_isUPeriodic (PyObject * self, PyObject * args) static
callback for the isUPeriodic() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isUPeriodic(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isVClosed()
PyObject * GeometrySurfacePy::staticCallback_isVClosed (PyObject * self, PyObject * args) static
callback for the isVClosed() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), isVClosed(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isVPeriodic()
PyObject * GeometrySurfacePy::staticCallback_isVPeriodic (PyObject * self, PyObject * args) static
callback for the isVPeriodic() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), isVPeriodic(), and Base::PyObjectBase::PyObjectBase().
staticCallback_normal()
PyObject * GeometrySurfacePy::staticCallback_normal (PyObject * self, PyObject * args) static
callback for the normal() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), normal(), and Base::PyObjectBase::PyObjectBase().
staticCallback_parameter()
PyObject * GeometrySurfacePy::staticCallback_parameter (PyObject * self, PyObject * args) static
callback for the parameter() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), parameter(), and Base::PyObjectBase::PyObjectBase().
staticCallback_projectPoint()
PyObject * GeometrySurfacePy::staticCallback_projectPoint (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the projectPoint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), projectPoint(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setContinuity()
int GeometrySurfacePy::staticCallback_setContinuity (PyObject * self, PyObject * value, void * closure) static
setter callback for the Continuity attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setRotation()
int GeometrySurfacePy::staticCallback_setRotation (PyObject * self, PyObject * value, void * closure) static
setter callback for the Rotation attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_tangent()
PyObject * GeometrySurfacePy::staticCallback_tangent (PyObject * self, PyObject * args) static
callback for the tangent() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and tangent().
staticCallback_toBSpline()
PyObject * GeometrySurfacePy::staticCallback_toBSpline (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the toBSpline() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and toBSpline().
staticCallback_toShape()
PyObject * GeometrySurfacePy::staticCallback_toShape (PyObject * self, PyObject * args) static
callback for the toShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and toShape().
staticCallback_uIso()
PyObject * GeometrySurfacePy::staticCallback_uIso (PyObject * self, PyObject * args) static
callback for the uIso() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and uIso().
staticCallback_UPeriod()
PyObject * GeometrySurfacePy::staticCallback_UPeriod (PyObject * self, PyObject * args) static
callback for the UPeriod() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and UPeriod().
staticCallback_value()
PyObject * GeometrySurfacePy::staticCallback_value (PyObject * self, PyObject * args) static
callback for the value() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and value().
staticCallback_vIso()
PyObject * GeometrySurfacePy::staticCallback_vIso (PyObject * self, PyObject * args) static
callback for the vIso() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and vIso().
staticCallback_VPeriod()
PyObject * GeometrySurfacePy::staticCallback_VPeriod (PyObject * self, PyObject * args) static
callback for the VPeriod() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and VPeriod().
tangent()
PyObject * GeometrySurfacePy::tangent (PyObject * args)
implementer for the tangent() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_tangent().
toBSpline()
PyObject * GeometrySurfacePy::toBSpline (PyObject * args, PyObject * kwd)
implementer for the toBSpline() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_toBSpline().
toShape()
PyObject * GeometrySurfacePy::toShape (PyObject * args)
implementer for the toShape() method
References Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, and draftgeoutils.general::v1().
Referenced by staticCallback_toShape().
uIso()
PyObject * GeometrySurfacePy::uIso (PyObject * args)
implementer for the uIso() method
References Part::GeometryPy::getGeometryPtr(), Part::makeGeometryCurvePy(), and Part::PartExceptionOCCError.
Referenced by staticCallback_uIso().
UPeriod()
PyObject * GeometrySurfacePy::UPeriod (PyObject * args)
implementer for the UPeriod() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_UPeriod().
value()
PyObject * GeometrySurfacePy::value (PyObject * args)
implementer for the value() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by Part::BSplineSurfacePy::movePoint(), Part::ConePy::PyInit(), Part::CylinderPy::PyInit(), Part::PlanePy::PyInit(), Part::SurfaceOfExtrusionPy::PyInit(), Part::SurfaceOfRevolutionPy::PyInit(), Part::ConePy::setAxis(), Part::CylinderPy::setAxis(), Part::PlanePy::setAxis(), Part::SpherePy::setAxis(), Part::ToroidPy::setAxis(), Part::ConePy::setCenter(), Part::CylinderPy::setCenter(), Part::SpherePy::setCenter(), Part::ToroidPy::setCenter(), Part::SurfaceOfExtrusionPy::setDirection(), Part::SurfaceOfRevolutionPy::setDirection(), Part::SurfaceOfRevolutionPy::setLocation(), Part::BezierSurfacePy::setPole(), Part::BSplineSurfacePy::setPole(), Part::PlanePy::setPosition(), and staticCallback_value().
vIso()
PyObject * GeometrySurfacePy::vIso (PyObject * args)
implementer for the vIso() method
References Part::GeometryPy::getGeometryPtr(), Part::makeGeometryCurvePy(), and Part::PartExceptionOCCError.
Referenced by staticCallback_vIso().
VPeriod()
PyObject * GeometrySurfacePy::VPeriod (PyObject * args)
implementer for the VPeriod() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_VPeriod().
Member Data Documentation
GetterSetter
PyGetSetDef GeometrySurfacePy::GetterSetter static
Initial value:
= {
    {"Continuity",
        (getter) staticCallback_getContinuity,
        (setter) staticCallback_setContinuity,
        "\n                                     Returns the global continuity of the surface.\n                         ",
        NULL
    },
    {"Rotation",
        (getter) staticCallback_getRotation,
        (setter) staticCallback_setRotation,
        "Returns a rotation object to describe the orientation for surface that supports it",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of GeometrySurfacePy.
Methods
PyMethodDef GeometrySurfacePy::Methods static
Methods structure of GeometrySurfacePy.
Type
PyTypeObject GeometrySurfacePy::Type static
Type structure of GeometrySurfacePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), Part::GeometryCurvePy::intersect(), intersect(), Part::GeometryCurvePy::intersectCS(), intersectSS(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), Part::BuildPlateSurfacePy::loadInitSurface(), Part::BuildPlateSurfacePy::PyInit(), Part::RectangularTrimmedSurfacePy::PyInit(), Part::TopoShapeFacePy::PyInit(), and Part::Curve2dPy::toShape().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeometrySurfacePy.h
Sources/FreeCAD/src/Mod/Part/App/GeometrySurfacePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeometrySurfacePy.cpp