FreeCAD: MeshPart::BrepMesh Class Reference
MeshPart::BrepMesh Class Reference
Public Member Functions
BrepMesh (bool s, const std::vector< uint32_t > &c)
Mesh::MeshObject * create (const std::vector< Part::TopoShape::Domain > &domains) const
Constructor & Destructor Documentation
BrepMesh()
MeshPart::BrepMesh::BrepMesh (bool s, const std::vector< uint32_t > & c)
Member Function Documentation
create()
Mesh::MeshObject * MeshPart::BrepMesh::create (const std::vector< Part::TopoShape::Domain > & domains) const
References Mesh::Segment::addIndices(), Mesh::MeshObject::addSegment(), MeshCore::MeshKernel::Adopt(), App::Color::asHexString(), Data::ComplexGeoData::Domain::facets, Data::ComplexGeoData::Facet::I1, Data::ComplexGeoData::Facet::I2, Data::ComplexGeoData::Facet::I3, Data::ComplexGeoData::Domain::points, Mesh::Segment::save(), Mesh::Segment::setColor(), Mesh::Segment::setName(), App::Color::setPackedValue(), Mesh::MeshObject::swap(), and draftgeoutils.general::v1().
Referenced by draftguitools.gui_labels.Label::action().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/MeshPart/App/Mesher.cpp