FreeCAD: PartDesignGui::TaskPadParameters Class Reference
PartDesignGui::TaskPadParameters Class Reference
#include <TaskPadParameters.h>
Public Member Functions
virtual void apply () override
apply changes made in the parameters input to the model via commands
virtual void saveHistory () override
save field history
TaskPadParameters (ViewProviderPad *PadView, QWidget *parent=0, bool newObj=false)
~TaskPadParameters ()
Public Member Functions inherited from PartDesignGui::TaskSketchBasedParameters
TaskSketchBasedParameters (PartDesignGui::ViewProvider *vp, QWidget *parent, const std::string &pixmapname, const QString &parname)
~TaskSketchBasedParameters ()
Public Member Functions inherited from PartDesignGui::TaskFeatureParameters
void recomputeFeature ()
TaskFeatureParameters (PartDesignGui::ViewProvider *vp, QWidget *parent, const std::string &pixmapname, const QString &parname)
virtual ~TaskFeatureParameters ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (QWidget *parent=0)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (QWidget *parent=0)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::DocumentObserver
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
virtual ~DocumentObserver ()
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockConnection (bool block)
void detachSelection ()
Detaches from the selection.
bool isConnectionAttached () const
bool isConnectionBlocked () const
SelectionObserver (bool attach=true, int resolve=1)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, int resolve=1)
Constructor.
virtual ~SelectionObserver ()
Protected Member Functions
void changeEvent (QEvent *e) override
Protected Member Functions inherited from PartDesignGui::TaskSketchBasedParameters
void exitSelectionMode ()
QString getFaceReference (const QString &obj, const QString &sub) const
QVariant objectNameByLabel (const QString &label, const QVariant &suggest) const
Try to find the name of a feature with the given label.
const QString onAddSelection (const Gui::SelectionChanges &msg)
void onSelectReference (const bool pressed, const bool edge, const bool face, const bool planar)
QVariant setUpToFace (const QString &text)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Slots inherited from PartDesignGui::TaskFeatureParameters
void onUpdateView (bool on)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from PartDesignGui::TaskFeatureParameters
bool blockUpdate
Lock updateUI(), applying changes to the underlying feature and calling recomputeFeature()
PartDesignGui::ViewProvider * vp
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskPadParameters()
TaskPadParameters::TaskPadParameters (ViewProviderPad * PadView, QWidget * parent = 0, bool newObj = false)
References draftgeoutils.intersections::connect(), PartDesign::Pad::Direction, Base::UnitsApi::getDecimals(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyQuantity::getQuantityValue(), App::PropertyLinkSub::getSubValues(), App::PropertyVector::getValue(), App::PropertyLinkSub::getValue(), App::PropertyEnumeration::getValue(), App::PropertyBool::getValue(), QSint::ActionGroup::groupLayout(), PartDesign::Feature::isDatum(), PartDesign::Pad::Length, PartDesign::Pad::Length2, PartDesign::ProfileBased::Midplane, PartDesign::Pad::Offset, PartDesignGui::TaskFeatureParameters::onUpdateView(), App::ObjectIdentifier::parse(), PartDesign::ProfileBased::Reversed, PartDesign::Pad::Type, PartDesign::ProfileBased::UpToFace, PartDesign::Pad::UseCustomVector, PartDesignGui::TaskFeatureParameters::vp, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
~TaskPadParameters()
TaskPadParameters::~TaskPadParameters ()
Member Function Documentation
apply()
void TaskPadParameters::apply (void) override virtual
apply changes made in the parameters input to the model via commands
Reimplemented from PartDesignGui::TaskFeatureParameters.
References Gui::ViewProviderDocumentObject::getObject(), and PartDesignGui::TaskFeatureParameters::vp.
changeEvent()
void TaskPadParameters::changeEvent (QEvent * e) override protected
saveHistory()
void TaskPadParameters::saveHistory (void) override virtual
save field history
Reimplemented from PartDesignGui::TaskFeatureParameters.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/PartDesign/Gui/TaskPadParameters.h
Sources/FreeCAD/src/Mod/PartDesign/Gui/TaskPadParameters.cpp