FreeCAD: Gui::ViewProviderGeometryObject Class Reference
Gui::ViewProviderGeometryObject Class Reference
The base class for all view providers that display geometric data, like mesh, point clouds and shapes.
#include <ViewProviderGeometryObject.h>
Public Member Functions
void attach (App::DocumentObject *pcObject)
Attaches the document object to this view provider.
SoPickedPoint * getPickedPoint (const SbVec2s &pos, const View3DInventorViewer &viewer) const
This method is provided for convenience and does basically the same as getPickedPoints() unless that only the closest point to the camera will be picked.
SoPickedPointList getPickedPoints (const SbVec2s &pos, const View3DInventorViewer &viewer, bool pickAll=false) const
Returns a list of picked points from the geometry under getRoot().
bool isSelectable (void) const
void updateData (const App::Property *)
ViewProviderGeometryObject ()
constructor.
virtual ~ViewProviderGeometryObject ()
destructor.
Public Member Functions inherited from Gui::ViewProviderDragger
ViewProviderDragger ()
constructor.
virtual ~ViewProviderDragger ()
destructor.
bool doubleClicked (void) override
is called by the tree if the user double clicks on the object
void setupContextMenu (QMenu *, QObject *, const char *) override
set up the context-menu with the supported edit modes
virtual ViewProvider * startEditing (int ModNum=0) override
Public Member Functions inherited from Gui::ViewProviderDocumentObject
virtual bool canDelete (App::DocumentObject *obj) const override
Asks the view provider if the given object can be deleted.
virtual bool canDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const override
Query object dropping with full qualified name.
virtual void forceUpdate (bool enable=true)
virtual bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const override
return the coin node detail and path to the node of the subname
Gui::Document * getDocument () const
Get the GUI document to this ViewProvider object.
virtual bool getElementPicked (const SoPickedPoint *, std::string &subname) const override
return a hit element given the picked point which contains the full node path
App::DocumentObject * getObject (void) const
Get the object of this ViewProvider object.
PyObject * getPyObject () override
Get the python wrapper for that ViewProvider.
virtual void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const override
Get a list of TaskBoxes associated with this object.
virtual const char * getTransactionText () const override
Is called by the tree if the user double clicks on the object.
virtual void hide (void) override
Hide the object in the view.
virtual bool isUpdateForced () const
virtual void reattach (App::DocumentObject *)
virtual int replaceObject (App::DocumentObject *, App::DocumentObject *) override
Replace an object to the view provider by drag and drop.
void setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
virtual void show (void) override
Show the object in the view.
virtual bool showInTree () const override
Tell the tree view if this object should appear there.
virtual void update (const App::Property *) override
update the content of the ViewProvider this method have to implement the recalculation of the ViewProvider.
void updateView ()
Run a redraw.
ViewProviderDocumentObject ()
constructor.
virtual ~ViewProviderDocumentObject ()
destructor.
virtual void startRestoring ()
virtual void finishRestoring ()
virtual bool removeDynamicProperty (const char *prop) override
virtual App::Property * addDynamicProperty (const char *type, const char *name=0, const char *group=0, const char *doc=0, short attr=0, bool ro=false, bool hidden=false) override
virtual ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=0, bool recursive=false) const
Return the linked view object.
virtual std::string getFullName () const override
virtual bool allowOverride (const App::DocumentObject &) const
Allow this class to be used as an override for the original view provider of the given object.
void setShowable (bool enable)
bool isShowable () const
Public Member Functions inherited from Gui::ViewProvider
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual std::vector< App::DocumentObject * > claimChildren3D (void) const
deliver the children belonging to this object this method is used to deliver the objects to the 3DView which should be grouped under its scene graph.
SoSeparator * getAnnotation (void)
virtual SoSeparator * getBackRoot (void) const
virtual SoGroup * getChildRoot (void) const
virtual SoSeparator * getFrontRoot (void) const
SoSwitch * getModeSwitch (void) const
virtual SoSeparator * getRoot (void) const
SoTransform * getTransformNode () const
ViewProvider ()
constructor.
virtual ~ViewProvider ()
destructor.
virtual bool useNewSelectionModel (void) const
indicates if the ViewProvider use the new Selection model
virtual std::string getElement (const SoDetail *) const
return a hit element to the selection path or 0
virtual SoDetail * getDetail (const char *) const
return the coin node detail of the subelement
int partialRender (const std::vector< std::string > &subelements, bool clear)
partial rendering setup
virtual std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const
virtual std::vector< Base::Vector3d > getSelectionShape (const char *Element) const
return the highlight lines for a given element or the whole shape
Base::BoundBox3d getBoundingBox (const char *subname=0, bool transform=true, MDIView *view=0) const
Return the bound box of this view object.
virtual bool onDelete (const std::vector< std::string > &subNames)
Get called if the object is about to get deleted.
virtual void beforeDelete ()
Called before deletion.
virtual bool canDragObjects () const
Check whether children can be removed from the view provider by drag and drop.
virtual bool canDragObject (App::DocumentObject *) const
Check whether the object can be removed from the view provider by drag and drop.
virtual void dragObject (App::DocumentObject *)
Remove a child from the view provider by drag and drop.
virtual bool canDropObjects () const
Check whether objects can be added to the view provider by drag and drop or drop only.
virtual bool canDropObject (App::DocumentObject *) const
Check whether the object can be dropped to the view provider by drag and drop or drop only.
virtual bool canDragAndDropObject (App::DocumentObject *) const
Return false to force drop only operation for a given object.
virtual void dropObject (App::DocumentObject *)
Add an object to the view provider by drag and drop.
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
Add an object with full qualified name to the view provider by drag and drop.
virtual bool canRemoveChildrenFromRoot () const
Tell the tree view to remove children items from the tree root.
std::string getActiveDisplayMode (void) const
virtual void setDisplayMode (const char *ModeName)
set the display mode
virtual const char * getDefaultDisplayMode () const
get the default display mode
virtual std::vector< std::string > getDisplayModes (void) const
returns a list of all possible display modes
virtual bool isShow (void) const
checks whether the view provider is visible or not
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
virtual void setOverrideMode (const std::string &mode)
Overrides the display mode with mode.
const std::string getOverrideMode ()
virtual bool keyPressed (bool pressed, int key)
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
virtual bool mouseMove (const SbVec2s &cursorPos, View3DInventorViewer *viewer)
is called when the provider is in edit and the mouse is moved
virtual bool mouseButtonPressed (int button, bool pressed, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
is called when the Provider is in edit and the mouse is clicked
virtual QIcon getIcon (void) const
deliver the icon shown in the tree view
virtual std::vector< App::DocumentObject * > claimChildren (void) const
deliver the children belonging to this object this method is used to deliver the objects to the tree framework which should be grouped under its label.
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
virtual std::map< std::string, App::Color > getElementColors (const char *element=0) const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
bool isEditing () const
void finishEditing ()
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
virtual MDIView * getMDIView () const
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
TransactionalObject (void)
Constructor.
virtual ~TransactionalObject ()
Public Member Functions inherited from App::ExtensionContainer
ExtensionIterator extensionBegin ()
ExtensionContainer ()
ExtensionIterator extensionEnd ()
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
void registerExtension (Base::Type extension, App::Extension *ext)
virtual ~ExtensionContainer ()
virtual Property * getPropertyByName (const char *name) const override
find a property by its name
virtual const char * getPropertyName (const Property *prop) const override
get the name of a property
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
virtual void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
virtual short getPropertyType (const Property *prop) const override
get the Type of a Property
virtual short getPropertyType (const char *name) const override
get the Type of a named Property
virtual const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
Public Member Functions inherited from App::PropertyContainer
virtual App::Property * getDynamicPropertyByName (const char *name) const
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
const char * getPropertyPrefix () const
bool isHidden (const char *name) const
check if the named property is hidden
bool isHidden (const Property *prop) const
check if the property is hidden
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isReadOnly (const Property *prop) const
check if the property is read-only
PropertyContainer ()
A constructor.
void setPropertyPrefix (const char *prefix)
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
virtual ~PropertyContainer ()
A destructor.
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Attributes
App::PropertyBool BoundingBox
App::PropertyBool Selectable
App::PropertyColor ShapeColor
App::PropertyMaterial ShapeMaterial
App::PropertyPercent Transparency
Public Attributes inherited from Gui::ViewProviderDocumentObject
App::PropertyEnumeration DisplayMode
App::PropertyEnumeration OnTopWhenSelected
App::PropertyEnumeration SelectionStyle
App::PropertyBool ShowInTree
App::PropertyBool Visibility
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
Edit methods
SoMaterial * pcShapeMaterial
SoFCBoundingBox * pcBoundingBox
SoSwitch * pcBoundSwitch
SoBaseColor * pcBoundColor
virtual void showBoundingBox (bool)
void onChanged (const App::Property *prop)
get called by the container whenever a property has been changed
void setSelectable (bool Selectable=true)
virtual unsigned long getBoundColor () const
Additional Inherited Members
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0, Transform, Cutting, Color }
Public Types inherited from App::ExtensionContainer
typedef std::map< Base::Type, App::Extension * >::iterator ExtensionIterator
Static Public Member Functions inherited from Gui::ViewProviderDragger
static void updateTransform (const Base::Placement &from, SoTransform *to)
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Protected Member Functions inherited from Gui::ViewProviderDragger
bool setEdit (int ModNum) override
is called by the document when the provider goes in edit mode
void unsetEdit (int ModNum) override
is called when you lose the edit mode
void setEditViewer (View3DInventorViewer *, int ModNum) override
adjust viewer settings when editing a view provider
void unsetEditViewer (View3DInventorViewer *) override
restores viewer settings when leaving editing mode
Protected Member Functions inherited from Gui::ViewProviderDocumentObject
Gui::MDIView * getActiveView () const
Gui::MDIView * getEditingView () const
Gui::MDIView * getInventorView () const
Gui::MDIView * getViewOfNode (SoNode *node) const
virtual void onBeforeChange (const App::Property *prop) override
get called before the value is changed
SoNode * findFrontRootOfType (const SoType &type) const
Searches in all view providers that are attached to an object that is part of the same document as the object this view provider is attached to for an front root of type.
virtual bool isAttachedToDocument () const override
virtual const char * detachFromDocument () override
virtual void onPropertyStatusChanged (const App::Property &prop, unsigned long oldStatus) override
get called when a property status has changed
virtual void setModeSwitch () override
Turn on mode switch.
Protected Member Functions inherited from Gui::ViewProvider
virtual QIcon mergeOverlayIcons (const QIcon &orig) const
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
bool checkRecursion (SoNode *)
Helper method to check that the node is valid, i.e.
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
Helper method to get picked entities while editing.
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
Helper method to get picked entities while editing.
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData (void) const
virtual void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container.
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::ViewProviderDragger
SoFCCSysDragger * csysDragger = nullptr
Protected Attributes inherited from Gui::ViewProviderDocumentObject
App::DocumentObject * pcObject
Gui::Document * pcDocument
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation
The root separator for annotations.
ViewProviderPy * pyViewObject
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Detailed Description
The base class for all view providers that display geometric data, like mesh, point clouds and shapes.
Author
Werner Mayer
Constructor & Destructor Documentation
ViewProviderGeometryObject()
ViewProviderGeometryObject::ViewProviderGeometryObject ()
constructor.
References BoundingBox, App::Material::DEFAULT, App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), ParameterGrp::GetUnsigned(), pcBoundColor, pcBoundingBox, pcShapeMaterial, App::Prop_None, Selectable, App::PropertyIntegerConstraint::setConstraints(), App::PropertyBool::setValue(), ShapeColor, ShapeMaterial, Gui::ViewProvider::sPixmap, App::Property::touch(), and Transparency.
~ViewProviderGeometryObject()
ViewProviderGeometryObject::~ViewProviderGeometryObject () virtual
destructor.
References pcBoundColor, pcBoundingBox, and pcShapeMaterial.
Member Function Documentation
attach()
void ViewProviderGeometryObject::attach (App::DocumentObject * pcObject) virtual
Attaches the document object to this view provider.
Reimplemented from Gui::ViewProviderDocumentObject.
Reimplemented in RobotGui::ViewProviderTrajectory, RobotGui::ViewProviderRobotObject, PathGui::ViewProviderPath, ImageGui::ViewProviderImagePlane, FemGui::ViewProviderFemMesh, MeshGui::ViewProviderMeshNode, MeshGui::ViewProviderMeshFaceSet, MeshGui::ViewProviderMeshObject, PartDesignGui::ViewProviderDatumPoint, PartDesignGui::ViewProviderDatumPlane, PartDesignGui::ViewProviderDatumLine, PartDesignGui::ViewProviderDatumCoordinateSystem, PartDesignGui::ViewProviderDatum, PartDesignGui::ViewProviderBoolean, PartDesignGui::ViewProviderBody, PartGui::ViewProviderPartExt, Gui::ViewProviderPlacement, SketcherGui::ViewProviderSketch, PointsGui::ViewProviderStructured, PointsGui::ViewProviderScattered, PartDesignGui::ViewProviderPrimitive, PartDesignGui::ViewProviderAddSub, PartGui::ViewProviderPartReference, PartGui::ViewProviderCurveNet, PartGui::ViewProvider2DObjectGrid, MeshGui::ViewProviderMeshTransformDemolding, MeshGui::ViewProviderMeshTransform, MeshGui::ViewProviderIndexedFaceSet, MeshGui::ViewProviderMesh, FemGui::ViewProviderFemConstraint, Gui::ViewProviderPlane, Gui::ViewProviderOriginFeature, and Gui::ViewProviderLine.
References Gui::ViewProviderDocumentObject::attach().
Referenced by Gui::ViewProviderOriginFeature::attach(), Gui::ViewProviderPlacement::attach(), and RobotGui::ViewProviderRobotObject::attach().
getBoundColor()
unsigned long ViewProviderGeometryObject::getBoundColor () const protected virtual
Reimplemented in PathGui::ViewProviderPath.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::GetUnsigned().
Referenced by showBoundingBox().
getPickedPoint()
SoPickedPoint * ViewProviderGeometryObject::getPickedPoint (const SbVec2s & pos, const View3DInventorViewer & viewer) const
This method is provided for convenience and does basically the same as getPickedPoints() unless that only the closest point to the camera will be picked.
Note
It is in the response of the client programmer to delete the returned SoPickedPoint object.
References Gui::ViewProvider::getRoot(), and OfflineRenderingUtils::viewer().
getPickedPoints()
SoPickedPointList ViewProviderGeometryObject::getPickedPoints (const SbVec2s & pos, const View3DInventorViewer & viewer, bool pickAll = false) const
Returns a list of picked points from the geometry under getRoot().
If pickAll is false (the default) only the intersection point closest to the camera will be picked, otherwise all intersection points will be picked.
References Gui::ViewProvider::getRoot(), and OfflineRenderingUtils::viewer().
isSelectable()
bool Gui::ViewProviderGeometryObject::isSelectable (void) const virtual
Reimplemented from Gui::ViewProvider.
Reimplemented in PartDesignGui::ViewProviderDatum, Gui::ViewProviderPlacement, and SketcherGui::ViewProviderSketch.
References App::PropertyBool::getValue().
Referenced by SketcherGui::ViewProviderSketch::isSelectable().
onChanged()
void ViewProviderGeometryObject::onChanged (const App::Property * prop) protected virtual
get called by the container whenever a property has been changed
Reimplemented from Gui::ViewProviderDocumentObject.
Reimplemented in PartDesignGui::ViewProviderBoolean, PartDesignGui::ViewProviderBody, PartDesignGui::ViewProvider, PartGui::ViewProviderPartExt, Gui::ViewProviderPlacement, SketcherGui::ViewProviderSketch, SketcherGui::ViewProviderCustom, RobotGui::ViewProviderRobotObject, PointsGui::ViewProviderPoints, PathGui::ViewProviderPath, PartDesignGui::ViewProviderDatumPoint, PartGui::ViewProviderSpline, PartGui::ViewProviderPartReference, PartGui::ViewProviderCustom, PartGui::ViewProvider2DObjectGrid, MeshGui::ViewProviderMeshNode, MeshGui::ViewProviderMesh, FemGui::ViewProviderFemMesh, FemGui::ViewProviderFemConstraint, Gui::ViewProviderOriginFeature, and PartDesignGui::ViewProviderDatumCoordinateSystem.
References App::Material::ambientColor, App::Color::b, BoundingBox, App::Material::diffuseColor, App::Material::emissiveColor, App::Color::g, App::PropertyInteger::getValue(), App::PropertyBool::getValue(), App::PropertyColor::getValue(), App::PropertyMaterial::getValue(), Gui::ViewProviderDocumentObject::onChanged(), pcShapeMaterial, App::Color::r, Selectable, App::PropertyMaterial::setDiffuseColor(), setSelectable(), App::PropertyMaterial::setTransparency(), App::PropertyColor::setValue(), App::PropertyInteger::setValue(), ShapeColor, ShapeMaterial, App::Material::shininess, showBoundingBox(), App::Material::specularColor, App::Material::transparency, and Transparency.
Referenced by draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSite.Compass::buildCoordinates(), draftobjects.wire.Wire::execute(), ArchAxis.CommandArchGrid::IsActive(), PartDesignGui::ViewProviderDatumCoordinateSystem::onChanged(), Gui::ViewProviderOriginFeature::onChanged(), PartDesignGui::ViewProviderDatumPoint::onChanged(), RobotGui::ViewProviderRobotObject::onChanged(), Gui::ViewProviderPlacement::onChanged(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchPanel.ViewProviderPanelSheet::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), and draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData().
setSelectable()
void ViewProviderGeometryObject::setSelectable (bool Selectable = true) protected
References Gui::SoFCSelection::AUTO, Gui::SoFCSelection::highlightMode, Gui::SoFCSelection::NOTSELECTED, Gui::SoFCSelection::OFF, Gui::ViewProvider::pcRoot, Gui::SoFCSelection::SEL_OFF, Gui::SoFCSelection::SEL_ON, Gui::SoFCSelection::selected, and Gui::SoFCSelection::selectionMode.
Referenced by onChanged().
showBoundingBox()
void ViewProviderGeometryObject::showBoundingBox (bool show) virtual
Reimplemented in PathGui::ViewProviderPath.
References Gui::SoFCBoundingBox::coordsOn, Gui::SoFCBoundingBox::dimensionsOn, getBoundColor(), pcBoundColor, pcBoundingBox, pcBoundSwitch, Gui::ViewProvider::pcRoot, and Gui::ViewProviderDocumentObject::show().
Referenced by onChanged().
updateData()
void ViewProviderGeometryObject::updateData (const App::Property * prop) virtual
Reimplemented from Gui::ViewProviderDragger.
Reimplemented in PartDesignGui::ViewProviderBody, PartGui::ViewProviderSpline, FemGui::ViewProviderFemConstraint, PartDesignGui::ViewProvider, PartGui::ViewProviderPartExt, Gui::ViewProviderPlacement, SketcherGui::ViewProviderSketch, SketcherGui::ViewProviderCustom, RobotGui::ViewProviderTrajectory, RobotGui::ViewProviderRobotObject, PointsGui::ViewProviderStructured, PointsGui::ViewProviderScattered, PathGui::ViewProviderPathShape, PathGui::ViewProviderPath, PathGui::ViewProviderAreaView, PathGui::ViewProviderArea, PartDesignGui::ViewProviderPrimitive, PartDesignGui::ViewProviderDatumPlane, PartDesignGui::ViewProviderDatumLine, PartDesignGui::ViewProviderDatumCoordinateSystem, PartDesignGui::ViewProviderAddSub, PartGui::ViewProviderRuledSurface, PartGui::ViewProviderPartReference, PartGui::ViewProviderCustom, PartGui::ViewProviderChamfer, PartGui::ViewProviderFillet, PartGui::ViewProviderCurveNet, PartGui::ViewProviderCompound, PartGui::ViewProviderMultiCommon, PartGui::ViewProviderMultiFuse, PartGui::ViewProviderBoolean, PartGui::ViewProvider2DObjectGrid, MeshGui::ViewProviderMeshTransform, MeshGui::ViewProviderMeshNode, MeshGui::ViewProviderMeshFaceSet, MeshGui::ViewProviderMeshObject, MeshGui::ViewProviderIndexedFaceSet, MeshGui::ViewProviderMesh, ImageGui::ViewProviderImagePlane, FemGui::ViewProviderFemMeshShapeNetgen, FemGui::ViewProviderFemMesh, FemGui::ViewProviderFemConstraintTransform, FemGui::ViewProviderFemConstraintTemperature, FemGui::ViewProviderFemConstraintPulley, FemGui::ViewProviderFemConstraintPressure, FemGui::ViewProviderFemConstraintPlaneRotation, FemGui::ViewProviderFemConstraintInitialTemperature, FemGui::ViewProviderFemConstraintHeatflux, FemGui::ViewProviderFemConstraintGear, FemGui::ViewProviderFemConstraintForce, FemGui::ViewProviderFemConstraintFluidBoundary, FemGui::ViewProviderFemConstraintFixed, FemGui::ViewProviderFemConstraintDisplacement, FemGui::ViewProviderFemConstraintContact, FemGui::ViewProviderFemConstraintBearing, and Gui::ViewProviderOriginFeature.
References Gui::ViewProvider::getBoundingBox(), Base::Persistence::getClassTypeId(), Gui::ViewProviderDocumentObject::getObject(), Base::BaseClass::isDerivedFrom(), Gui::SoFCBoundingBox::maxBounds, Gui::SoFCBoundingBox::minBounds, pcBoundingBox, and Gui::ViewProviderDragger::updateData().
Referenced by PathScripts.PathJobDlg.JobCreate::exec_(), draftviewproviders.view_dimension.ViewProviderLinearDimension::onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension::onChanged(), draftviewproviders.view_wire.ViewProviderWire::onChanged(), PathScripts.PathOpGui.TaskPanelPage::pageUpdateData(), PathScripts.PathSetupSheetGui.OpTaskPanel::setupUi(), Gui::ViewProviderOriginFeature::updateData(), FemGui::ViewProviderFemMesh::updateData(), ImageGui::ViewProviderImagePlane::updateData(), MeshGui::ViewProviderMesh::updateData(), PartGui::ViewProviderCurveNet::updateData(), PartDesignGui::ViewProviderDatumCoordinateSystem::updateData(), PartDesignGui::ViewProviderDatumLine::updateData(), PartDesignGui::ViewProviderDatumPlane::updateData(), PointsGui::ViewProviderScattered::updateData(), PointsGui::ViewProviderStructured::updateData(), Gui::ViewProviderPlacement::updateData(), PartGui::ViewProviderPartExt::updateData(), and FemGui::ViewProviderFemConstraint::updateData().
Member Data Documentation
BoundingBox
App::PropertyBool Gui::ViewProviderGeometryObject::BoundingBox
Referenced by onChanged(), and ViewProviderGeometryObject().
pcBoundColor
SoBaseColor* Gui::ViewProviderGeometryObject::pcBoundColor protected
Referenced by showBoundingBox(), ViewProviderGeometryObject(), and ~ViewProviderGeometryObject().
pcBoundingBox
SoFCBoundingBox* Gui::ViewProviderGeometryObject::pcBoundingBox protected
Referenced by showBoundingBox(), updateData(), ViewProviderGeometryObject(), and ~ViewProviderGeometryObject().
pcBoundSwitch
SoSwitch* Gui::ViewProviderGeometryObject::pcBoundSwitch protected
Referenced by showBoundingBox().
pcShapeMaterial
SoMaterial* Gui::ViewProviderGeometryObject::pcShapeMaterial protected
Referenced by Gui::ViewProviderOriginFeature::attach(), MeshGui::ViewProviderMesh::attach(), MeshGui::ViewProviderMeshTransform::attach(), PartGui::ViewProviderPartExt::attach(), PartDesignGui::ViewProviderDatum::attach(), MeshGui::ViewProviderMeshNode::attach(), FemGui::ViewProviderFemMesh::attach(), MeshGui::ViewProviderMesh::deselectFacet(), MeshGui::ViewProviderMesh::exportMesh(), MeshGui::ViewProviderMesh::highlightComponents(), MeshGui::ViewProviderMesh::highlightSegments(), MeshGui::ViewProviderMesh::highlightSelection(), onChanged(), PartGui::ViewProviderPartExt::onChanged(), FemGui::ViewProviderFemMesh::resetColorByElementId(), FemGui::ViewProviderFemMesh::resetColorByNodeId(), MeshGui::ViewProviderMesh::resetFacetTransparency(), MeshGui::ViewProviderMesh::selectFacet(), FemGui::ViewProviderFemMesh::setColorByElementId(), FemGui::ViewProviderFemMesh::setColorByNodeIdHelper(), MeshGui::ViewProviderMesh::setColorPerFace(), MeshGui::ViewProviderMesh::setColorPerVertex(), MeshGui::ViewProviderMesh::setFacetTransparency(), PartGui::ViewProviderPartExt::setHighlightedFaces(), MeshGui::ViewProviderMesh::tryColorPerVertexOrFace(), MeshGui::ViewProviderMesh::unhighlightSelection(), ViewProviderGeometryObject(), and ~ViewProviderGeometryObject().
Selectable
App::PropertyBool Gui::ViewProviderGeometryObject::Selectable
Referenced by Gui::ViewProviderOriginFeature::attach(), onChanged(), PartDesignGui::ViewProvider::setBodyMode(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), ViewProviderGeometryObject(), and PartGui::DlgProjectionOnSurface::~DlgProjectionOnSurface().
ShapeColor
App::PropertyColor Gui::ViewProviderGeometryObject::ShapeColor
Referenced by MeshGui::ViewProviderFace::attach(), MeshGui::ViewProviderMesh::deselectFacet(), ExportOCAFGui::findColors(), PartGui::ViewProviderPartExt::getElementColors(), PartDesignGui::ViewProviderDressUp::highlightReferences(), PartDesignGui::ViewProviderShapeBinder::highlightReferences(), SurfaceGui::ViewProviderFilling::highlightReferences(), SurfaceGui::ViewProviderSections::highlightReferences(), MeshGui::ViewProviderMesh::highlightSegments(), MeshGui::ViewProviderMesh::highlightSelection(), onChanged(), MeshGui::ViewProviderMesh::onChanged(), MeshGui::ViewProviderMeshNode::onChanged(), PartGui::ViewProviderPartExt::onChanged(), PartGui::FaceColors::Private::Private(), FemGui::ViewProviderFemMesh::resetColorByElementId(), FemGui::ViewProviderFemMesh::resetColorByNodeId(), MeshGui::ViewProviderMesh::resetFacetTransparency(), MeshGui::ViewProviderMesh::setFacetTransparency(), MeshGui::ViewProviderMesh::tryColorPerVertexOrFace(), MeshGui::ViewProviderMesh::unhighlightSelection(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderChamfer::updateData(), PartDesignGui::ViewProviderDatum::ViewProviderDatum(), FemGui::ViewProviderFemMesh::ViewProviderFemMesh(), ViewProviderGeometryObject(), and PartGui::ViewProviderPartExt::ViewProviderPartExt().
ShapeMaterial
App::PropertyMaterial Gui::ViewProviderGeometryObject::ShapeMaterial
Referenced by onChanged(), MeshGui::ViewProviderMesh::onChanged(), MeshGui::ViewProviderMeshNode::onChanged(), PartGui::ViewProviderPartExt::onChanged(), and ViewProviderGeometryObject().
Transparency
App::PropertyPercent Gui::ViewProviderGeometryObject::Transparency
Referenced by PartGui::ViewProviderPartExt::getElementColors(), onChanged(), PartDesignGui::ViewProviderDatumPoint::onChanged(), PartGui::ViewProviderPartExt::onChanged(), PartGui::ViewProviderPartExt::unsetHighlightedFaces(), PartGui::ViewProviderChamfer::updateData(), PartDesignGui::ViewProviderDatum::ViewProviderDatum(), ViewProviderGeometryObject(), and PartGui::DlgProjectionOnSurface::~DlgProjectionOnSurface().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/ViewProviderGeometryObject.h
Sources/FreeCAD/src/Gui/ViewProviderGeometryObject.cpp