FreeCAD: SketcherGui::Ui_ConstraintMultiFilterDialog Class Reference
SketcherGui::Ui_ConstraintMultiFilterDialog Class Reference
#include <ui_ConstraintMultiFilterDialog.h>
Public Member Functions
void retranslateUi (QWidget *SketcherGui__ConstraintMultiFilterDialog)
void setupUi (QWidget *SketcherGui__ConstraintMultiFilterDialog)
Public Attributes
QDialogButtonBox * buttonBox
QPushButton * checkAllButton
QHBoxLayout * horizontalLayout
QLabel * label
QListWidget * listMultiFilter
QPushButton * uncheckAllButton
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void SketcherGui::Ui_ConstraintMultiFilterDialog::retranslateUi (QWidget * SketcherGui__ConstraintMultiFilterDialog)
References checkAllButton, listMultiFilter, draftguitools.gui_setstyle::translate, and uncheckAllButton.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void SketcherGui::Ui_ConstraintMultiFilterDialog::setupUi (QWidget * SketcherGui__ConstraintMultiFilterDialog)
References buttonBox, checkAllButton, draftgeoutils.intersections::connect(), horizontalLayout, listMultiFilter, retranslateUi(), uncheckAllButton, and verticalLayout.
Member Data Documentation
buttonBox
QDialogButtonBox* SketcherGui::Ui_ConstraintMultiFilterDialog::buttonBox
Referenced by PathScripts.PathGetPoint.TaskPanel::getPoint(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::modifyStandardButtons(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::pageDirtyChanged(), PathScripts.PathGetPoint.TaskPanel::pointFinish(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setClean(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setDirty(), and setupUi().
checkAllButton
QPushButton* SketcherGui::Ui_ConstraintMultiFilterDialog::checkAllButton
Referenced by retranslateUi(), and setupUi().
horizontalLayout
QHBoxLayout* SketcherGui::Ui_ConstraintMultiFilterDialog::horizontalLayout
Referenced by setupUi().
label
QLabel* SketcherGui::Ui_ConstraintMultiFilterDialog::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
listMultiFilter
QListWidget* SketcherGui::Ui_ConstraintMultiFilterDialog::listMultiFilter
Referenced by retranslateUi(), and setupUi().
uncheckAllButton
QPushButton* SketcherGui::Ui_ConstraintMultiFilterDialog::uncheckAllButton
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* SketcherGui::Ui_ConstraintMultiFilterDialog::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/ui_ConstraintMultiFilterDialog.h