FreeCAD: draftguitools
draftguitools
Workbenches » Python workbenches » Draft
Modules that define the workbench GuiCommands to perform actions.
Classes
class draftguitools.gui_annotationstyleeditor.AnnotationStyleEditor
class draftguitools.gui_arcs.Arc
class draftguitools.gui_arcs.Arc_3Points
class draftguitools.gui_arcs.ArcGroup
class draftguitools.gui_array_simple.Array
class draftguitools.gui_array_simple.LinkArray
class draftguitools.gui_arrays.ArrayGroup
class draftguitools.gui_base.GuiCommandBase
class draftguitools.gui_base.GuiCommandNeedsSelection
class draftguitools.gui_base.GuiCommandSimplest
class draftguitools.gui_base_original.Creator
class draftguitools.gui_base_original.DraftTool
class draftguitools.gui_base_original.Modifier
class draftguitools.gui_beziers.BezCurve
class draftguitools.gui_beziers.BezierGroup
class draftguitools.gui_beziers.CubicBezCurve
class draftguitools.gui_circles.Circle
class draftguitools.gui_circulararray.CircularArray
class draftguitools.gui_clone.Clone
class draftguitools.gui_dimension_ops.FlipDimension
class draftguitools.gui_dimensions.Dimension
class draftguitools.gui_downgrade.Downgrade
class draftguitools.gui_draft2sketch.Draft2Sketch
class draftguitools.gui_drawing.Drawing
class draftguitools.gui_edit.Edit
class draftguitools.gui_edit.GuiToolsRepository
class draftguitools.gui_edit_arch_objects.ArchPanelCutGuiTools
class draftguitools.gui_edit_arch_objects.ArchPanelSheetGuiTools
class draftguitools.gui_edit_arch_objects.ArchSpaceGuiTools
class draftguitools.gui_edit_arch_objects.ArchStructureGuiTools
class draftguitools.gui_edit_arch_objects.ArchWallGuiTools
class draftguitools.gui_edit_arch_objects.ArchWindowGuiTools
class draftguitools.gui_edit_base_object.GuiTools
class draftguitools.gui_edit_draft_objects.DraftBezCurveGuiTools
class draftguitools.gui_edit_draft_objects.DraftBSplineGuiTools
class draftguitools.gui_edit_draft_objects.DraftCircleGuiTools
class draftguitools.gui_edit_draft_objects.DraftDimensionGuiTools
class draftguitools.gui_edit_draft_objects.DraftEllipseGuiTools
class draftguitools.gui_edit_draft_objects.DraftPolygonGuiTools
class draftguitools.gui_edit_draft_objects.DraftRectangleGuiTools
class draftguitools.gui_edit_draft_objects.DraftWireGuiTools
class draftguitools.gui_edit_part_objects.PartBoxGuiTools
class draftguitools.gui_edit_part_objects.PartConeGuiTools
class draftguitools.gui_edit_part_objects.PartCylinderGuiTools
class draftguitools.gui_edit_part_objects.PartLineGuiTools
class draftguitools.gui_edit_part_objects.PartSphereGuiTools
class draftguitools.gui_edit_sketcher_objects.SketcherSketchObjectGuiTools
class draftguitools.gui_ellipses.Ellipse
class draftguitools.gui_facebinders.Facebinder
class draftguitools.gui_fillets.Fillet
class draftguitools.gui_grid.ToggleGrid
class draftguitools.gui_groups.AddToConstruction
class draftguitools.gui_groups.AddToGroup
class draftguitools.gui_groups.SelectGroup
class draftguitools.gui_groups.SetAutoGroup
class draftguitools.gui_heal.Heal
class draftguitools.gui_join.Join
class draftguitools.gui_labels.Label
class draftguitools.gui_layers.Layer
class draftguitools.gui_line_add_delete.AddPoint
class draftguitools.gui_line_add_delete.DelPoint
class draftguitools.gui_lineops.CloseLine
class draftguitools.gui_lineops.FinishLine
class draftguitools.gui_lineops.LineAction
class draftguitools.gui_lineops.UndoLine
class draftguitools.gui_lines.Line
class draftguitools.gui_lines.Wire
class draftguitools.gui_lineslope.LineSlope
class draftguitools.gui_mirror.Mirror
class draftguitools.gui_move.Move
class draftguitools.gui_offset.Offset
class draftguitools.gui_orthoarray.OrthoArray
class draftguitools.gui_patharray.PathArray
class draftguitools.gui_patharray.PathLinkArray
class draftguitools.gui_pathtwistedarray.PathTwistedArray
class draftguitools.gui_pathtwistedarray.PathTwistedLinkArray
class draftguitools.gui_planeproxy.Draft_WorkingPlaneProxy
class draftguitools.gui_pointarray.PointArray
class draftguitools.gui_pointarray.PointLinkArray
class draftguitools.gui_points.Point
class draftguitools.gui_polararray.PolarArray
class draftguitools.gui_polygons.Polygon
class draftguitools.gui_rectangles.Rectangle
class draftguitools.gui_rotate.Rotate
class draftguitools.gui_scale.Scale
class draftguitools.gui_selectplane.Draft_SelectPlane
class draftguitools.gui_setstyle.Draft_SetStyle
class draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel
class draftguitools.gui_shape2dview.Shape2DView
class draftguitools.gui_shapestrings.ShapeString
class draftguitools.gui_snapper.Snapper
class draftguitools.gui_snaps.Draft_Snap_Angle
class draftguitools.gui_snaps.Draft_Snap_Center
class draftguitools.gui_snaps.Draft_Snap_Dimensions
class draftguitools.gui_snaps.Draft_Snap_Endpoint
class draftguitools.gui_snaps.Draft_Snap_Extension
class draftguitools.gui_snaps.Draft_Snap_Grid
class draftguitools.gui_snaps.Draft_Snap_Intersection
class draftguitools.gui_snaps.Draft_Snap_Lock
class draftguitools.gui_snaps.Draft_Snap_Midpoint
class draftguitools.gui_snaps.Draft_Snap_Near
class draftguitools.gui_snaps.Draft_Snap_Ortho
class draftguitools.gui_snaps.Draft_Snap_Parallel
class draftguitools.gui_snaps.Draft_Snap_Perpendicular
class draftguitools.gui_snaps.Draft_Snap_Special
class draftguitools.gui_snaps.Draft_Snap_WorkingPlane
class draftguitools.gui_snaps.ShowSnapBar
class draftguitools.gui_splines.BSpline
class draftguitools.gui_split.Split
class draftguitools.gui_stretch.Stretch
class draftguitools.gui_styles.ApplyStyle
class draftguitools.gui_subelements.SubelementHighlight
class draftguitools.gui_texts.Text
class draftguitools.gui_togglemodes.BaseMode
class draftguitools.gui_togglemodes.ToggleConstructionMode
class draftguitools.gui_togglemodes.ToggleContinueMode
class draftguitools.gui_togglemodes.ToggleDisplayMode
class draftguitools.gui_trackers.archDimTracker
class draftguitools.gui_trackers.arcTracker
class draftguitools.gui_trackers.bezcurveTracker
class draftguitools.gui_trackers.boxTracker
class draftguitools.gui_trackers.bsplineTracker
class draftguitools.gui_trackers.dimTracker
class draftguitools.gui_trackers.editTracker
class draftguitools.gui_trackers.ghostTracker
class draftguitools.gui_trackers.gridTracker
class draftguitools.gui_trackers.lineTracker
class draftguitools.gui_trackers.PlaneTracker
class draftguitools.gui_trackers.radiusTracker
class draftguitools.gui_trackers.rectangleTracker
class draftguitools.gui_trackers.snapTracker
class draftguitools.gui_trackers.Tracker
class draftguitools.gui_trackers.wireTracker
class draftguitools.gui_trimex.Trimex
class draftguitools.gui_upgrade.Upgrade
class draftguitools.gui_wire2spline.WireToBSpline
Functions
def draftguitools.gui_tool_utils.format_unit (exp, unit="mm")
def draftguitools.gui_tool_utils.get_point (target, args, mobile=False, sym=False, workingplane=True, noTracker=False)
def draftguitools.gui_snaps.get_snap_statusbar_widget ()
def draftguitools.gui_tool_utils.get_support (mouseEvent=None)
def draftguitools.gui_tool_utils.has_mod (args, mod)
def draftguitools.gui_setstyle.QT_TRANSLATE_NOOP (ctx, txt)
def draftguitools.gui_tool_utils.redraw_3d_view ()
def draftguitools.gui_tool_utils.select_object (arg)
def draftguitools.gui_tool_utils.set_mod (args, mod, state)
def draftguitools.gui_tool_utils.set_working_plane_to_object_under_cursor (mouseEvent)
def draftguitools.gui_tool_utils.set_working_plane_to_selected_object ()
def draftguitools.gui_snaps.sync_snap_statusbar_button (button, status)
def draftguitools.gui_snaps.sync_snap_toolbar_button (button, status)
Variables
dictionary draftguitools.gui_edit.COLORS
draftguitools.gui_groups.Draft_AddConstruction = AddToConstruction
draftguitools.gui_arcs.Draft_Arc_3Points = Arc_3Points
draftguitools.gui_clone.Draft_Clone = Clone
draftguitools.gui_facebinders.Draft_Facebinder = Facebinder
draftguitools.gui_dimension_ops.Draft_FlipDimension = FlipDimension
draftguitools.gui_labels.Draft_Label = Label
draftguitools.gui_lineslope.Draft_Slope = LineSlope
def draftguitools.gui_tool_utils.formatUnit = format_unit
def draftguitools.gui_tool_utils.getPoint = get_point
def draftguitools.gui_tool_utils.getSupport = get_support
def draftguitools.gui_tool_utils.hasMod = has_mod
list draftguitools.gui_tool_utils.MODALT = MODS[utils.get_param("modalt", 2)]
list draftguitools.gui_tool_utils.MODCONSTRAIN = MODS[utils.get_param("modconstrain", 0)]
list draftguitools.gui_tool_utils.MODS = ["shift", "ctrl", "alt"]
list draftguitools.gui_tool_utils.MODSNAP = MODS[utils.get_param("modsnap", 1)]
draftguitools.gui_annotationstyleeditor.param = App.ParamGet("User parameter:BaseApp/Preferences/Mod/Draft")
def draftguitools.gui_tool_utils.redraw3DView = redraw_3d_view
def draftguitools.gui_tool_utils.selectObject = select_object
def draftguitools.gui_tool_utils.setMod = set_mod
def draftguitools.gui_tool_utils.setWorkingPlaneToObjectUnderCursor = set_working_plane_to_object_under_cursor
def draftguitools.gui_tool_utils.setWorkingPlaneToSelectedObject = set_working_plane_to_selected_object
tuple draftguitools.gui_snapper.UNSNAPPABLES = ('Image::ImagePlane',)
Detailed Description
Modules that define the workbench GuiCommands to perform actions.
Function Documentation
format_unit()
def draftguitools.gui_tool_utils.format_unit (exp, unit = "mm")
Return a formatting string to set a number to the correct unit.
get_point()
def draftguitools.gui_tool_utils.get_point (target, args, mobile = False, sym = False, workingplane = True, noTracker = False)
Return a constrained 3D point and its original point.
It is used by the Draft tools.
Parameters
----------
target: object (class)
    The target object with a `node` attribute. If this is present,
    return the last node, otherwise return `None`.
    In the Draft tools, `target` is essentially the same class
    of the Gui command, that is, `self`. Therefore, this method
    probably makes more sense as a class method.
args: Coin event
    The Coin event received from the 3D view.
mobile: bool, optional
    It defaults to `False`.
    If it is `True` the constraining occurs from the location of
    the mouse cursor when `Shift` is pressed; otherwise from the last
    entered point.
sym: bool, optional
    It defaults to `False`.
    If it is `True`, the x and y values always stay equal.
workingplane: bool, optional
    It defaults to `True`.
    If it is `False`, the point won't be projected on the currently
    active working plane.
noTracker: bool, optional
    It defaults to `False`.
    If it is `True`, the tracking line will not be displayed.
Returns
-------
CoinPoint, Base::Vector3, str
    It returns a tuple with some information.
    The first is the Coin point returned by `Snapper.snap`
    or by the `ActiveView`; the second is that same point
    turned into an `App.Vector`,
    and the third is some information of the point
    returned by the `Snapper` or by the `ActiveView`.
References draftguitools.gui_tool_utils.hasMod.
get_snap_statusbar_widget()
def draftguitools.gui_snaps.get_snap_statusbar_widget ()
Return snap statusbar button.
References Gui.getMainWindow().
Referenced by draftguitools.gui_snaps.sync_snap_statusbar_button().
get_support()
def draftguitools.gui_tool_utils.get_support (mouseEvent = None)
Return the supporting object and set the working plane.
It saves the current working plane, then sets it to the selected object.
Parameters
----------
mouseEvent: Coin event, optional
    It defaults to `None`.
    Coin event with the mouse, that is, a click.
    If there is a mouse event it calls
    `set_working_plane_to_object_under_cursor`.
    Otherwise, it calls `set_working_plane_to_selected_object`.
Returns
-------
None
    If there was a mouse event, but there was nothing under the cursor.
    Or if the working plane is not `weak`.
    Or if there was an exception with aligning the working plane
    to the component under the cursor.
    Or if more than one object was selected.
    Or if the selected object has many subelements.
    Or if the single subelement is not a `'Face'`.
Coin info
    If there was a mouse event, the `getObjectInfo`
    of the object under the cursor.
App::DocumentObject
    If there was no mouse event, the single selected object
    that contains the single selected face that was used
    to align the working plane.
References draftguitools.gui_tool_utils.setWorkingPlaneToObjectUnderCursor, and draftguitools.gui_tool_utils.setWorkingPlaneToSelectedObject.
has_mod()
def draftguitools.gui_tool_utils.has_mod (args, mod)
Check if args has a specific modifier.
Parameters
----------
args: Coin event
    The Coin event received from the 3D view.
mod: str
    A string indicating the modifier, either `'shift'`, `'ctrl'`,
    or `'alt'`.
Returns
-------
bool
    It returns `args["ShiftDown"]`, `args["CtrlDown"]`,
    or `args["AltDown"]`, depending on the passed value of `mod`.
QT_TRANSLATE_NOOP()
def draftguitools.gui_setstyle.QT_TRANSLATE_NOOP (ctx, txt)
Referenced by draftguitools.gui_setstyle.Draft_SetStyle.GetResources().
redraw_3d_view()
def draftguitools.gui_tool_utils.redraw_3d_view ()
Force a redraw of 3D view or do nothing if it fails.
select_object()
def draftguitools.gui_tool_utils.select_object (arg)
Handle the selection of objects depending on buttons pressed.
This is a scene event handler, to be called from the Draft tools
when they need to select an object.
::
    self.call = self.view.addEventCallback("SoEvent", select_object)
Parameters
----------
arg: Coin event
    The Coin event received from the 3D view.
    If it is of type Keyboard and the `ESCAPE` key, it runs the `finish`
    method of the active command.
    If it is of type Mouse button and `BUTTON1` press,
    it captures the position of the cursor (x, y)
    and the object below that cursor to add it to the active selection;
    then it runs the `proceed` method of the active command
    to continue with the command's logic.
set_mod()
def draftguitools.gui_tool_utils.set_mod (args, mod, state)
Set a specific modifier state in args.
Parameters
----------
args: Coin event
    The Coin event received from the 3D view.
mod: str
    A string indicating the modifier, either `'shift'`, `'ctrl'`,
    or `'alt'`.
state: bool
    The boolean value of `state` is assigned to `args["ShiftDown"]`,
    `args["CtrlDown"]`, or `args["AltDown"]`
    depending on `mod`.
set_working_plane_to_object_under_cursor()
def draftguitools.gui_tool_utils.set_working_plane_to_object_under_cursor (mouseEvent)
Set the working plane to the object under the cursor.
It tests for an object under the cursor.
If it is found, it checks whether a `'face'` or `'curve'` component
is selected in the object's `Shape`.
Then it tries to align the working plane to that face or curve.
The working plane is only aligned to the face if
the working plane is not `'weak'`.
Parameters
----------
mouseEvent: Coin event
    Coin event with the mouse, that is, a click.
Returns
-------
None
    If no object was found in the 3D view under the cursor.
    Or if the working plane is not `weak`.
    Or if there was an exception with aligning the working plane
    to the component under the cursor.
Coin info
    The `getObjectInfo` of the object under the cursor.
set_working_plane_to_selected_object()
def draftguitools.gui_tool_utils.set_working_plane_to_selected_object ()
Set the working plane to the selected object's face.
The working plane is only aligned to the face if
the working plane is `'weak'`.
Returns
-------
None
    If more than one object was selected.
    Or if the selected object has many subelements.
    Or if the single subelement is not a `'Face'`.
App::DocumentObject
    The single object that contains a single selected face.
sync_snap_statusbar_button()
def draftguitools.gui_snaps.sync_snap_statusbar_button (button, status)
Set snap statusbar button to given state.
References draftguitools.gui_snaps.get_snap_statusbar_widget().
Referenced by draftguitools.gui_snaps.Draft_Snap_Lock.Activated(), draftguitools.gui_snaps.Draft_Snap_Midpoint.Activated(), draftguitools.gui_snaps.Draft_Snap_Perpendicular.Activated(), draftguitools.gui_snaps.Draft_Snap_Grid.Activated(), draftguitools.gui_snaps.Draft_Snap_Intersection.Activated(), draftguitools.gui_snaps.Draft_Snap_Parallel.Activated(), draftguitools.gui_snaps.Draft_Snap_Endpoint.Activated(), draftguitools.gui_snaps.Draft_Snap_Angle.Activated(), draftguitools.gui_snaps.Draft_Snap_Center.Activated(), draftguitools.gui_snaps.Draft_Snap_Extension.Activated(), draftguitools.gui_snaps.Draft_Snap_Near.Activated(), draftguitools.gui_snaps.Draft_Snap_Ortho.Activated(), draftguitools.gui_snaps.Draft_Snap_Special.Activated(), draftguitools.gui_snaps.Draft_Snap_Dimensions.Activated(), and draftguitools.gui_snaps.Draft_Snap_WorkingPlane.Activated().
sync_snap_toolbar_button()
def draftguitools.gui_snaps.sync_snap_toolbar_button (button, status)
Set snap toolbar button to given state.
Referenced by draftguitools.gui_snaps.Draft_Snap_Lock.Activated(), draftguitools.gui_snaps.Draft_Snap_Midpoint.Activated(), draftguitools.gui_snaps.Draft_Snap_Perpendicular.Activated(), draftguitools.gui_snaps.Draft_Snap_Grid.Activated(), draftguitools.gui_snaps.Draft_Snap_Intersection.Activated(), draftguitools.gui_snaps.Draft_Snap_Parallel.Activated(), draftguitools.gui_snaps.Draft_Snap_Endpoint.Activated(), draftguitools.gui_snaps.Draft_Snap_Angle.Activated(), draftguitools.gui_snaps.Draft_Snap_Center.Activated(), draftguitools.gui_snaps.Draft_Snap_Extension.Activated(), draftguitools.gui_snaps.Draft_Snap_Near.Activated(), draftguitools.gui_snaps.Draft_Snap_Ortho.Activated(), draftguitools.gui_snaps.Draft_Snap_Special.Activated(), draftguitools.gui_snaps.Draft_Snap_Dimensions.Activated(), and draftguitools.gui_snaps.Draft_Snap_WorkingPlane.Activated().
Variable Documentation
COLORS
dictionary draftguitools.gui_edit.COLORS
Initial value:
 =  {
     "default": Gui.draftToolBar.getDefaultColor("snap"),
     "black":  (0., 0., 0.),
     "white":  (1., 1., 1.),
     "grey":   (.5, .5, .5),
     "red":    (1., 0., 0.),
     "green":  (0., 1., 0.),
     "blue":   (0., 0., 1.),
     "yellow": (1., 1., 0.),
     "cyan":   (0., 1., 1.),
     "magenta": (1., 0., 1.)
 }
Draft_AddConstruction
draftguitools.gui_groups.Draft_AddConstruction = AddToConstruction
Draft_Arc_3Points
draftguitools.gui_arcs.Draft_Arc_3Points = Arc_3Points
Draft_Clone
draftguitools.gui_clone.Draft_Clone = Clone
Draft_Facebinder
draftguitools.gui_facebinders.Draft_Facebinder = Facebinder
Draft_FlipDimension
draftguitools.gui_dimension_ops.Draft_FlipDimension = FlipDimension
Draft_Label
draftguitools.gui_labels.Draft_Label = Label
Draft_Slope
draftguitools.gui_lineslope.Draft_Slope = LineSlope
formatUnit
def draftguitools.gui_tool_utils.formatUnit = format_unit
getPoint
def draftguitools.gui_tool_utils.getPoint = get_point
Referenced by DrawSketchHandlerCopy.activated(), DrawSketchHandlerRectangularArray.activated(), Sketcher::SketchObject.addCopy(), Sketcher::SketchObject.addSymmetric(), ArchWall.areSameWallTypes(), Commands.SphereCreator.create(), draftguitools.gui_stretch.Stretch.doStretch(), Sketcher::SketchObject.fillet(), PathScripts.PathSurfaceSupport.PathGeometryGenerator.generatePathGeometry(), Points::PointKernel.getPoints(), ArchStructure.placeAlongEdge(), ArchWindow.recolorize(), Part::Geom2dPoint.Save(), Sketcher::SketchObject.transferFilletConstraints(), and Sketcher::SketchObject.trim().
getSupport
def draftguitools.gui_tool_utils.getSupport = get_support
hasMod
def draftguitools.gui_tool_utils.hasMod = has_mod
Referenced by draftguitools.gui_tool_utils.get_point().
MODALT
list draftguitools.gui_tool_utils.MODALT = MODS[utils.get_param("modalt", 2)]
MODCONSTRAIN
list draftguitools.gui_tool_utils.MODCONSTRAIN = MODS[utils.get_param("modconstrain", 0)]
MODS
list draftguitools.gui_tool_utils.MODS = ["shift", "ctrl", "alt"]
MODSNAP
list draftguitools.gui_tool_utils.MODSNAP = MODS[utils.get_param("modsnap", 1)]
param
draftguitools.gui_annotationstyleeditor.param = App.ParamGet("User parameter:BaseApp/Preferences/Mod/Draft")
Referenced by MeshPartGui::Tessellation.accept(), PartDesignGui::TaskDlgFeatureParameters.accept(), GCS::System.addConstraint(), TechDraw::DrawUtil.angleWithX(), StdMeshers_RadialQuadrangle_1D2D.Compute(), StdMeshers_Regular_1D.Compute(), StdMeshers_Regular_1D.computeInternalParameters(), StdMeshers_MEFISTO_2D.ComputeScaleOnFace(), SketcherGui::ViewProviderSketch.draw(), SMESH_Block.EdgeParameters(), TechDraw::DrawViewPart.extractFaces(), NETGENPlugin_Mesher.FillSMesh(), SMESH_MAT2d::Branch.getBoundaryPoints(), TechDraw::DrawProjectSplit.getEdges(), SMESH_ElementSearcherImpl.getIntersParamOnLine(), SMESH_MesherHelper.GetNodeU(), SMESH_MesherHelper.GetOtherParam(), SMESH_ElementSearcherImpl.GetPointState(), GCS::ConstraintEllipseTangentLine.grad(), GCS::ConstraintInternalAlignmentPoint2Ellipse.grad(), GCS::ConstraintAngleViaPoint.grad(), GCS::ConstraintSnell.grad(), TechDraw::DrawProjectSplit.isOnEdge(), CArc.MidParam(), Span.MidParam(), geoff_geometry::Span.MidParam(), PartDesignGui::TaskDlgFeatureParameters.reject(), GCS::System.removeConstraint(), Part::Part2DObject.seekTrimPoints(), StdMeshers_Penta_3D.SetHorizEdgeXYZ(), SMESH_MeshEditor.SewFreeBorder(), and VISCOUS_3D::_LayerEdge.smoothNefPolygon().
redraw3DView
def draftguitools.gui_tool_utils.redraw3DView = redraw_3d_view
selectObject
def draftguitools.gui_tool_utils.selectObject = select_object
setMod
def draftguitools.gui_tool_utils.setMod = set_mod
setWorkingPlaneToObjectUnderCursor
def draftguitools.gui_tool_utils.setWorkingPlaneToObjectUnderCursor = set_working_plane_to_object_under_cursor
Referenced by draftguitools.gui_tool_utils.get_support().
setWorkingPlaneToSelectedObject
def draftguitools.gui_tool_utils.setWorkingPlaneToSelectedObject = set_working_plane_to_selected_object
Referenced by draftguitools.gui_tool_utils.get_support().
UNSNAPPABLES
tuple draftguitools.gui_snapper.UNSNAPPABLES = ('Image::ImagePlane',)