FreeCAD: MeshTestJob Class Reference
MeshTestJob Class Reference
Public Member Functions
MeshTestJob ()
Mesh::MeshObject * run (const std::vector< Mesh::MeshObjectConstRef > &meshdata)
~MeshTestJob ()
Constructor & Destructor Documentation
MeshTestJob()
MeshTestJob::MeshTestJob ()
~MeshTestJob()
MeshTestJob::~MeshTestJob ()
Member Function Documentation
run()
Mesh::MeshObject * MeshTestJob::run (const std::vector< Mesh::MeshObjectConstRef > & meshdata)
References Base::Console(), and Base::ConsoleSingleton::Message().
Referenced by femexamples.examplesgui.FemExamples::clicked(), and femsolver.task.Task::protector().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sandbox/Gui/Command.cpp