FreeCAD: RobotGui::TaskDlgTrajectoryDressUp Class Reference
RobotGui::TaskDlgTrajectoryDressUp Class Reference
simulation dialog for the TaskView
#include <TaskDlgTrajectoryDressUp.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void clicked (int)
is called by the framework if an button is clicked which has no accept or rject role
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
returns for Close and Help button
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual void open ()
is called the TaskView when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgTrajectoryDressUp (Robot::TrajectoryDressUpObject *)
~TaskDlgTrajectoryDressUp ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
tells the framework which buttons are wished for the dialog
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Protected Attributes
TaskTrajectoryDressUpParameter * param
Robot::TrajectoryDressUpObject * pcObject
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
simulation dialog for the TaskView
Constructor & Destructor Documentation
TaskDlgTrajectoryDressUp()
TaskDlgTrajectoryDressUp::TaskDlgTrajectoryDressUp (Robot::TrajectoryDressUpObject * obj)
References Gui::TaskView::TaskDialog::Content, and param.
~TaskDlgTrajectoryDressUp()
TaskDlgTrajectoryDressUp::~TaskDlgTrajectoryDressUp ()
Member Function Documentation
accept()
bool TaskDlgTrajectoryDressUp::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Application::activeDocument(), Gui::Application::Instance, param, pcObject, App::DocumentObject::recomputeFeature(), and RobotGui::TaskTrajectoryDressUpParameter::writeValues().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
clicked()
void TaskDlgTrajectoryDressUp::clicked (int button) virtual
is called by the framework if an button is clicked which has no accept or rject role
Reimplemented from Gui::TaskView::TaskDialog.
References param, pcObject, App::DocumentObject::recomputeFeature(), and RobotGui::TaskTrajectoryDressUpParameter::writeValues().
getStandardButtons()
virtual QDialogButtonBox::StandardButtons RobotGui::TaskDlgTrajectoryDressUp::getStandardButtons (void) const virtual
returns for Close and Help button
Reimplemented from Gui::TaskView::TaskDialog.
helpRequested()
void TaskDlgTrajectoryDressUp::helpRequested () virtual
is called by the framework if the user press the help button
Reimplemented from Gui::TaskView::TaskDialog.
open()
void TaskDlgTrajectoryDressUp::open () virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
reject()
bool TaskDlgTrajectoryDressUp::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Application::activeDocument(), and Gui::Application::Instance.
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
Member Data Documentation
param
TaskTrajectoryDressUpParameter* RobotGui::TaskDlgTrajectoryDressUp::param protected
Referenced by accept(), clicked(), draftguitools.gui_selectplane.Draft_SelectPlane::finish(), draftguitools.gui_selectplane.Draft_SelectPlane::onSetExtension(), draftguitools.gui_selectplane.Draft_SelectPlane::onSetGridSize(), draftguitools.gui_selectplane.Draft_SelectPlane::onSetMainline(), draftguitools.gui_selectplane.Draft_SelectPlane::onSetSnapRadius(), and TaskDlgTrajectoryDressUp().
pcObject
Robot::TrajectoryDressUpObject* RobotGui::TaskDlgTrajectoryDressUp::pcObject protected
Referenced by accept(), and clicked().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Robot/Gui/TaskDlgTrajectoryDressUp.h
FreeCAD/src/Mod/Robot/Gui/TaskDlgTrajectoryDressUp.cpp