FreeCAD: RotTransDragger Class Reference
RotTransDragger Class Reference
#include <SoNavigationDragger.h>
Public Member Functions
RotTransDragger ()
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFRotation rotation
SoSFVec3f translation
Protected Member Functions
virtual void setDefaultOnNonWritingFields ()
virtual SbBool setUpConnections (SbBool onOff, SbBool doItAlways=false)
Static Protected Member Functions
static void fieldSensorCB (void *, SoSensor *)
static void invalidateSurroundScaleCB (void *, SoDragger *)
static void valueChangedCB (void *, SoDragger *)
Protected Attributes
SoFieldSensor * rotFieldSensor
SoFieldSensor * translFieldSensor
Constructor & Destructor Documentation
RotTransDragger()
RotTransDragger::RotTransDragger ()
References fieldSensorCB(), rotation, rotFieldSensor, setUpConnections(), translation, translFieldSensor, and valueChangedCB().
Member Function Documentation
fieldSensorCB()
void RotTransDragger::fieldSensorCB (void * inDragger, SoSensor *) static protected
Referenced by RotTransDragger(), and setUpConnections().
initClass()
void RotTransDragger::initClass (void) static
Referenced by Gui::SoFCDB::init().
invalidateSurroundScaleCB()
void RotTransDragger::invalidateSurroundScaleCB (void * parent, SoDragger *) static protected
Referenced by setUpConnections().
setDefaultOnNonWritingFields()
void RotTransDragger::setDefaultOnNonWritingFields () protected virtual
setUpConnections()
SbBool RotTransDragger::setUpConnections (SbBool onOff, SbBool doItAlways = false) protected virtual
References fieldSensorCB(), invalidateSurroundScaleCB(), rotation, rotFieldSensor, translation, and translFieldSensor.
Referenced by RotTransDragger().
valueChangedCB()
void RotTransDragger::valueChangedCB (void * , SoDragger * inDragger) static protected
References rotation, rotFieldSensor, draftfunctions.scale::scale(), translation, and translFieldSensor.
Referenced by RotTransDragger().
Member Data Documentation
rotation
SoSFRotation RotTransDragger::rotation
Referenced by femtaskpanels.task_element_rotation1D._TaskPanel::accept(), femtaskpanels.task_element_rotation1D._TaskPanel::rotation_changed(), RotTransDragger(), setUpConnections(), and valueChangedCB().
rotFieldSensor
SoFieldSensor* RotTransDragger::rotFieldSensor protected
Referenced by RotTransDragger(), setUpConnections(), and valueChangedCB().
translation
SoSFVec3f RotTransDragger::translation
Referenced by RotTransDragger(), setUpConnections(), and valueChangedCB().
translFieldSensor
SoFieldSensor* RotTransDragger::translFieldSensor protected
Referenced by RotTransDragger(), setUpConnections(), and valueChangedCB().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SoNavigationDragger.h
Sources/FreeCAD/src/Gui/SoNavigationDragger.cpp
Sources/FreeCAD/src/Gui/SoNavigationDraggerLayout.h