FreeCAD: SpreadsheetGui::SpreadsheetDelegate Class Reference
SpreadsheetGui::SpreadsheetDelegate Class Reference
#include <SpreadsheetDelegate.h>
Signals
void finishedWithKey (int key, Qt::KeyboardModifiers modifiers)
Public Member Functions
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &, const QModelIndex &index) const
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void setEditorData (QWidget *editor, const QModelIndex &index) const
void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const
QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const
SpreadsheetDelegate (Spreadsheet::Sheet *sheet, QWidget *parent=nullptr)
Constructor & Destructor Documentation
SpreadsheetDelegate()
SpreadsheetDelegate::SpreadsheetDelegate (Spreadsheet::Sheet * sheet, QWidget * parent = nullptr) explicit
Member Function Documentation
createEditor()
QWidget * SpreadsheetDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & , const QModelIndex & index) const
References draftgeoutils.intersections::connect(), SpreadsheetGui::LineEdit::finishedWithKey(), and Spreadsheet::Sheet::getCellBinding().
finishedWithKey
void SpreadsheetGui::SpreadsheetDelegate::finishedWithKey (int key, Qt::KeyboardModifiers modifiers) signal
paint()
void SpreadsheetDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const
References Spreadsheet::Sheet::getCellBindingBorder(), and Spreadsheet::Sheet::getCopyOrCutBorder().
setEditorData()
void SpreadsheetDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const
setModelData()
void SpreadsheetDelegate::setModelData (QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const
sizeHint()
QSize SpreadsheetDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Spreadsheet/Gui/SpreadsheetDelegate.h
FreeCAD/src/Mod/Spreadsheet/Gui/SpreadsheetDelegate.cpp