FreeCAD: Points Namespace Reference
Points Namespace Reference
Classes
class AscReader
class AscWriter
class Converter
class ConverterT
struct CurvatureInfo
Curvature information.
class DataStreambuf
class E57Reader
class Feature
Base class of all Points feature classes in FreeCAD.
class Module
class PcdReader
class PcdWriter
class PlyReader
class PlyWriter
class PointKernel
Point kernel.
class PointsAlgos
The Points algorithms container class.
class PointsGrid
The PointsGrid allows to divide a global point cloud into smaller regions of elements depending on the resolution of the grid.
class PointsGridIterator
The PointsGridIterator class provides an interface to walk through all grid elements of a point grid.
class PropertyCurvatureList
The Curvature property class.
class PropertyGreyValue
Greyvalue property.
class PropertyGreyValueList
class PropertyNormalList
class PropertyPointKernel
The point kernel property.
class Reader
class Structured
class Writer
Typedefs
typedef std::shared_ptr< Converter > ConverterPtr
typedef App::FeatureCustomT< Feature > FeatureCustom
typedef App::FeaturePythonT< Feature > FeaturePython
typedef App::FeatureCustomT< Structured > StructuredCustom
Functions
PyObject * initModule ()
unsigned int lzfDecompress (const void *const in_data, unsigned int in_len, void *out_data, unsigned int out_len)
Typedef Documentation
ConverterPtr
typedef std::shared_ptr<Converter> Points::ConverterPtr
FeatureCustom
typedef App::FeatureCustomT<Feature> Points::FeatureCustom
FeaturePython
typedef App::FeaturePythonT<Feature> Points::FeaturePython
StructuredCustom
typedef App::FeatureCustomT<Structured> Points::StructuredCustom
Function Documentation
initModule()
PyObject * Points::initModule ()
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().
lzfDecompress()
unsigned int Points::lzfDecompress (const void *const in_data, unsigned int in_len, void * out_data, unsigned int out_len)
Referenced by Points::PcdReader::read().