FreeCAD: Gui::TreeWidget Class Reference
Gui::TreeWidget Class Reference
Tree view that allows drag & drop of document objects.
#include <Tree.h>
Classes
struct SelInfo
Public Member Functions
bool eventFilter (QObject *, QEvent *ev) override
void expandSelectedItems (TreeItemMode mode)
DocumentItem * getDocumentItem (const Gui::Document *) const
const char * getTreeName () const
void itemSearch (const QString &text, bool select)
void markItem (const App::DocumentObject *Obj, bool mark)
void resetItemSearch ()
virtual void selectAll () override
void selectAllInstances (const ViewProviderDocumentObject &vpd)
void selectAllLinks (App::DocumentObject *obj)
void selectLinkedObject (App::DocumentObject *linked)
void startDragging ()
void startItemSearch (QLineEdit *)
void synchronizeSelectionCheckBoxes ()
void syncView (ViewProviderDocumentObject *vp)
TreeWidget (const char *name, QWidget *parent=0)
~TreeWidget ()
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockConnection (bool block)
void detachSelection ()
Detaches from the selection.
bool isConnectionAttached () const
bool isConnectionBlocked () const
SelectionObserver (bool attach=true, int resolve=1)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, int resolve=1)
Constructor.
virtual ~SelectionObserver ()
Static Public Member Functions
static void checkTopParent (App::DocumentObject *&obj, std::string &subname)
static std::vector< SelInfo > getSelection (App::Document *doc=0)
static TreeWidget * instance ()
static bool isObjectShowable (App::DocumentObject *obj)
static void scrollItemToTop ()
static Gui::Document * selectedDocument ()
static void updateStatus (bool delay=true)
Static Public Attributes
static const int DocumentType = 1000
static const int ObjectType = 1001
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *e) override
void drawRow (QPainter *, const QStyleOptionViewItem &, const QModelIndex &) const override
void onSelectionChanged (const SelectionChanges &msg) override
Observer message from the Selection.
Drag and drop
class DocumentItem
class DocumentObjectItem
void startDrag (Qt::DropActions supportedActions) override
bool dropMimeData (QTreeWidgetItem *parent, int index, const QMimeData *data, Qt::DropAction action) override
Qt::DropActions supportedDropActions () const override
QMimeData * mimeData (const QList< QTreeWidgetItem * > items) const override
void dragEnterEvent (QDragEnterEvent *event) override
void dragLeaveEvent (QDragLeaveEvent *event) override
void dragMoveEvent (QDragMoveEvent *event) override
void dropEvent (QDropEvent *event) override
bool event (QEvent *e) override
void keyPressEvent (QKeyEvent *event) override
void mouseDoubleClickEvent (QMouseEvent *event) override
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
void leaveEvent (QEvent *) override
void onCreateGroup ()
void onRelabelObject ()
void onActivateDocument (QAction *)
void onStartEditing ()
void onFinishEditing ()
void onSkipRecompute (bool on)
void onAllowPartialRecompute (bool on)
void onReloadDoc ()
void onCloseDoc ()
void onMarkRecompute ()
void onRecomputeObject ()
void onPreSelectTimer ()
void onSelectTimer ()
void onShowHidden ()
void onHideInTree ()
void onSearchObjects ()
void emitSearchObjects ()
Detailed Description
Tree view that allows drag & drop of document objects.
Author
Werner Mayer
Constructor & Destructor Documentation
TreeWidget()
TreeWidget::TreeWidget (const char * name, QWidget * parent = 0)
References draftgeoutils.faces::bind(), Gui::BitmapFactory(), draftgeoutils.intersections::connect(), Gui::Application::Instance, onAllowPartialRecompute(), onCloseDoc(), onCreateGroup(), onFinishEditing(), onHideInTree(), onMarkRecompute(), onPreSelectTimer(), onRecomputeObject(), onRelabelObject(), onReloadDoc(), onSearchObjects(), onSelectTimer(), onShowHidden(), onSkipRecompute(), Gui::Application::signalActiveDocument, Gui::Application::signalChangedObject, Gui::Application::signalDeleteDocument, Gui::Application::signalNewDocument, Gui::Application::signalRelabelDocument, Gui::Application::signalRenameDocument, and Gui::Application::signalShowHidden.
~TreeWidget()
TreeWidget::~TreeWidget ()
Member Function Documentation
checkTopParent()
void TreeWidget::checkTopParent (App::DocumentObject *& obj, std::string & subname) static
References Gui::Application::Instance.
Referenced by Gui::SelectionSingleton::checkSelection().
contextMenuEvent()
void TreeWidget::contextMenuEvent (QContextMenuEvent * e) override protected
References App::Document::AllowPartialRecompute, draftgeoutils.intersections::connect(), Gui::Workbench::createLinkMenu(), Gui::DocumentItem::document(), DocumentType, App::Application::getActiveDocument(), App::GetApplication(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), Gui::Document::getDocument(), App::Application::getDocuments(), Gui::MenuManager::getInstance(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::Instance, Base::BaseClass::isDerivedFrom(), Gui::ViewProvider::isEditing(), Gui::DocumentObjectItem::object(), ObjectType, onActivateDocument(), onStartEditing(), App::Document::PartialDoc, App::Application::setActiveDocument(), Gui::Application::setupContextMenu(), Gui::MenuManager::setupContextMenu(), Gui::ViewProvider::setupContextMenu(), Gui::DocumentItem::showHidden(), Gui::ViewProviderDocumentObject::showInTree(), and App::Document::SkipRecompute.
dragEnterEvent()
void TreeWidget::dragEnterEvent (QDragEnterEvent * event) override protected
dragLeaveEvent()
void TreeWidget::dragLeaveEvent (QDragLeaveEvent * event) override protected
dragMoveEvent()
void TreeWidget::dragMoveEvent (QDragMoveEvent * event) override protected
References Gui::ViewProvider::canDragAndDropObject(), Gui::ViewProviderDocumentObject::canDropObjectEx(), Gui::ViewProvider::canDropObjects(), DocumentType, Gui::ViewProviderDocumentObject::getObject(), Gui::DocumentObjectItem::getParentItem(), leaveEvent(), Gui::DocumentObjectItem::object(), and ObjectType.
drawRow()
void TreeWidget::drawRow (QPainter * painter, const QStyleOptionViewItem & options, const QModelIndex & index) const override protected
dropEvent()
void TreeWidget::dropEvent (QDropEvent * event) override protected
References Gui::SelectionSingleton::addSelection(), Gui::Command::App, Gui::MacroManager::App, Gui::ViewProvider::canDragAndDropObject(), Gui::ViewProviderDocumentObject::canDropObjectEx(), Gui::ViewProvider::canDropObjects(), Gui::SelectionSingleton::clearCompleteSelection(), App::AutoTransaction::close(), App::Document::copyObject(), Gui::DocumentItem::document(), DocumentType, Gui::ViewProvider::dragObject(), Gui::ViewProvider::dropObjectEx(), App::GetApplication(), App::Application::getDocument(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::Document::getDocument(), App::ExtensionContainer::getExtensionByType(), App::GeoFeatureGroupExtension::getGroupOfObject(), App::DocumentObject::getInListEx(), Gui::getMainWindow(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), Gui::ViewProviderDocumentObject::getObject(), Gui::Command::getObjectCmd(), Gui::DocumentObjectItem::getOwnerDocument(), Gui::DocumentObjectItem::getParentItem(), Gui::DocumentObjectItem::getSubName(), App::Document::getUniqueObjectName(), App::PropertyPlacement::getValue(), Gui::Application::getViewProvider(), Gui::MacroManager::Gui, Gui::Application::Instance, Gui::TreeParams::Instance(), Base::Placement::inverse(), Base::Matrix4D::inverseGauss(), Gui::DocumentObjectItem::isGroup(), Gui::Application::macroManager(), App::Document::moveObject(), Gui::DocumentObjectItem::object(), ObjectType, App::Document::recompute(), Gui::Selection(), Gui::SelectionSingleton::selStackPush(), Gui::Document::setActiveView(), Gui::SelectionSingleton::setSelection(), App::PropertyPlacement::setValueIfChanged(), and Base::Placement::toMatrix().
dropMimeData()
bool TreeWidget::dropMimeData (QTreeWidgetItem * parent, int index, const QMimeData * data, Qt::DropAction action) override protected
emitSearchObjects
void Gui::TreeWidget::emitSearchObjects () signal
Referenced by onSearchObjects().
event()
bool TreeWidget::event (QEvent * e) override protected
Referenced by draftguitools.gui_edit.Edit::evaluate_menu_action().
eventFilter()
bool TreeWidget::eventFilter (QObject * , QEvent * ev) override
expandSelectedItems()
void TreeWidget::expandSelectedItems (TreeItemMode mode)
References Gui::CollapseItem, Gui::ExpandItem, Gui::ExpandPath, Gui::SelectionObserver::isConnectionAttached(), and Gui::ToggleItem.
Referenced by StdCmdTreeCollapse::activated(), and StdCmdTreeExpand::activated().
getDocumentItem()
DocumentItem * TreeWidget::getDocumentItem (const Gui::Document * doc) const
Referenced by Gui::DocumentObjectItem::getParentDocument(), itemSearch(), and selectLinkedObject().
getSelection()
std::vector< TreeWidget::SelInfo > TreeWidget::getSelection (App::Document * doc = 0) static
References App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), instance(), Gui::SelectionObserver::isConnectionAttached(), Gui::DocumentObjectItem::object(), ObjectType, and onSelectTimer().
Referenced by femguiutils.selection_widgets._Selector::setHelpText().
getTreeName()
const char * TreeWidget::getTreeName () const
Referenced by Gui::DocumentItem::DocumentItem().
hideEvent()
void TreeWidget::hideEvent (QHideEvent * ev) override protected
References Gui::SelectionObserver::detachSelection().
instance()
TreeWidget * TreeWidget::instance (void) static
Referenced by getSelection(), Gui::Document::RestoreDocFile(), and Gui::Document::SaveDocFile().
isObjectShowable()
bool TreeWidget::isObjectShowable (App::DocumentObject * obj) static
References Gui::Application::getDocument(), and Gui::Application::Instance.
Referenced by Gui::ViewProviderDocumentObject::show().
itemSearch()
void TreeWidget::itemSearch (const QString & text, bool select)
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), getDocumentItem(), Gui::Application::Instance, App::ObjectIdentifier::parse(), resetItemSearch(), draftutils.gui_utils::select(), Gui::Selection(), Gui::SelectionSingleton::selStackPush(), and Gui::SelectionSingleton::setPreselect().
keyPressEvent()
void TreeWidget::keyPressEvent (QKeyEvent * event) override protected
References onSearchObjects().
leaveEvent()
void TreeWidget::leaveEvent (QEvent *) override protected
References Gui::TreeParams::Instance(), Gui::SelectionSingleton::rmvPreselect(), and Gui::Selection().
Referenced by dragMoveEvent().
markItem()
void Gui::TreeWidget::markItem (const App::DocumentObject * Obj, bool mark)
mimeData()
QMimeData * TreeWidget::mimeData (const QList< QTreeWidgetItem * > items) const override protected
References Gui::ViewProviderDocumentObject::getObject(), Gui::DocumentObjectItem::object(), and ObjectType.
mouseDoubleClickEvent()
void TreeWidget::mouseDoubleClickEvent (QMouseEvent * event) override protected
References Gui::DocumentItem::document(), DocumentType, Gui::ViewProvider::doubleClicked(), Gui::Application::editDocument(), Base::BaseClass::getClassTypeId(), Gui::ViewProviderDocumentObject::getObject(), Gui::Command::getObjectCmd(), Gui::DocumentObjectItem::getOwnerDocument(), Gui::ViewProviderDocumentObject::getTransactionText(), Gui::MacroManager::Gui, Gui::Application::Instance, Gui::Application::macroManager(), Gui::DocumentObjectItem::object(), ObjectType, onReloadDoc(), App::Document::PartialDoc, Gui::Document::setActiveView(), and App::AutoTransaction::setEnable().
onActivateDocument
void TreeWidget::onActivateDocument (QAction * active) protected slot
References Base::BaseClass::getClassTypeId(), Gui::Application::getDocument(), and Gui::Application::Instance.
Referenced by contextMenuEvent().
onAllowPartialRecompute
void TreeWidget::onAllowPartialRecompute (bool on) protected slot
References App::Document::AllowPartialRecompute, Gui::DocumentItem::document(), DocumentType, and Gui::Document::getDocument().
Referenced by TreeWidget().
onCloseDoc
void TreeWidget::onCloseDoc () protected slot
References Gui::Command::Doc, Gui::DocumentItem::document(), DocumentType, and Draft::gui.
Referenced by TreeWidget().
onCreateGroup
void TreeWidget::onCreateGroup () protected slot
References Gui::Command::App, Gui::DocumentItem::document(), DocumentType, Gui::Document::getDocument(), Gui::ViewProviderDocumentObject::getObject(), Gui::DocumentObjectItem::object(), and ObjectType.
Referenced by TreeWidget().
onFinishEditing
void TreeWidget::onFinishEditing () protected slot
References Gui::Application::getDocument(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::Instance, Gui::DocumentObjectItem::object(), and ObjectType.
Referenced by TreeWidget().
onHideInTree
void TreeWidget::onHideInTree () protected slot
References ObjectType.
Referenced by TreeWidget().
onMarkRecompute
void TreeWidget::onMarkRecompute () protected slot
References Gui::DocumentItem::document(), DocumentType, App::DocumentObject::enforceRecompute(), Gui::Document::getDocument(), Gui::ViewProviderDocumentObject::getObject(), Gui::DocumentObjectItem::object(), and ObjectType.
Referenced by TreeWidget().
onPreSelectTimer
void TreeWidget::onPreSelectTimer () protected slot
References App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), Gui::DocumentObjectItem::getSubName(), Gui::TreeParams::Instance(), Gui::DocumentObjectItem::object(), ObjectType, Gui::Selection(), and Gui::SelectionSingleton::setPreselect().
Referenced by TreeWidget().
onRecomputeObject
void TreeWidget::onRecomputeObject () protected slot
References Gui::ViewProviderDocumentObject::getObject(), Gui::DocumentObjectItem::object(), and ObjectType.
Referenced by TreeWidget().
onRelabelObject
void TreeWidget::onRelabelObject () protected slot
Referenced by TreeWidget().
onReloadDoc
void TreeWidget::onReloadDoc () protected slot
References Gui::DocumentItem::document(), DocumentType, App::GetApplication(), Gui::Document::getDocument(), Gui::Application::Instance, Gui::Application::reopen(), and App::Application::setActiveDocument().
Referenced by mouseDoubleClickEvent(), and TreeWidget().
onSearchObjects
void TreeWidget::onSearchObjects () protected slot
References emitSearchObjects().
Referenced by keyPressEvent(), and TreeWidget().
onSelectionChanged()
void TreeWidget::onSelectionChanged (const SelectionChanges & msg) override protected virtual
Observer message from the Selection.
Implements Gui::SelectionObserver.
References Gui::SelectionChanges::AddSelection, Gui::SelectionChanges::ClrSelection, Gui::TreeParams::Instance(), Gui::SelectionChanges::RmvSelection, and Gui::SelectionChanges::SetSelection.
onSelectTimer
void TreeWidget::onSelectTimer () protected slot
References Gui::SelectionObserver::blockConnection(), Gui::DocumentItem::clearSelection(), Gui::TreeParams::Instance(), Gui::Selection(), Gui::DocumentItem::selectItems(), Gui::DocumentItem::SR_EXPAND, and Gui::DocumentItem::SR_SELECT.
Referenced by getSelection(), selectAllInstances(), selectAllLinks(), selectLinkedObject(), and TreeWidget().
onShowHidden
void TreeWidget::onShowHidden () protected slot
References DocumentType, Gui::DocumentObjectItem::getOwnerDocument(), ObjectType, and Gui::DocumentItem::setShowHidden().
Referenced by TreeWidget().
onSkipRecompute
void TreeWidget::onSkipRecompute (bool on) protected slot
References Gui::DocumentItem::document(), DocumentType, Gui::Document::getDocument(), and App::Document::SkipRecompute.
Referenced by TreeWidget().
onStartEditing
void TreeWidget::onStartEditing () protected slot
References Gui::DocumentItem::document(), Gui::getMainWindow(), Gui::ViewProviderDocumentObject::getObject(), Gui::DocumentObjectItem::getOwnerDocument(), Gui::DocumentObjectItem::object(), ObjectType, and Gui::MainWindow::setActiveWindow().
Referenced by contextMenuEvent().
resetItemSearch()
void TreeWidget::resetItemSearch ()
Referenced by itemSearch(), and startItemSearch().
scrollItemToTop()
void TreeWidget::scrollItemToTop () static
References Gui::Application::activeDocument(), Gui::SelectionSingleton::hasSelection(), Gui::Application::Instance, Gui::Selection(), and Gui::DocumentItem::SR_FORCE_EXPAND.
selectAll()
void TreeWidget::selectAll () override virtual
References Gui::SelectionSingleton::clearSelection(), App::GetApplication(), Gui::Application::getDocument(), Gui::Application::Instance, Gui::TreeParams::Instance(), Gui::Selection(), Gui::SelectionSingleton::selStackPush(), and Gui::SelectionSingleton::setSelection().
selectAllInstances()
void TreeWidget::selectAllInstances (const ViewProviderDocumentObject & vpd)
References Gui::SelectionObserver::isConnectionAttached(), and onSelectTimer().
selectAllLinks()
void TreeWidget::selectAllLinks (App::DocumentObject * obj)
References App::GetApplication(), App::GetLinkRecursive, Gui::Application::getViewProvider(), Gui::Application::Instance, Gui::SelectionObserver::isConnectionAttached(), and onSelectTimer().
selectedDocument()
Gui::Document * TreeWidget::selectedDocument () static
References DocumentType.
Referenced by Gui::PropertyView::onTimer().
selectLinkedObject()
void TreeWidget::selectLinkedObject (App::DocumentObject * linked)
References App::Application::getActiveDocument(), App::GetApplication(), getDocumentItem(), Gui::Application::Instance, Gui::SelectionObserver::isConnectionAttached(), Gui::SelectionObserver::isConnectionBlocked(), and onSelectTimer().
showEvent()
void TreeWidget::showEvent (QShowEvent * ev) override protected
References Gui::SelectionObserver::attachSelection(), and Gui::TreeParams::Instance().
startDrag()
void TreeWidget::startDrag (Qt::DropActions supportedActions) override protected
Referenced by startDragging().
startDragging()
void TreeWidget::startDragging ()
References startDrag().
startItemSearch()
void TreeWidget::startItemSearch (QLineEdit * edit)
References Gui::Application::activeDocument(), DocumentType, Gui::Document::getDocument(), App::Document::getObjects(), Gui::Application::Instance, ObjectType, and resetItemSearch().
supportedDropActions()
Qt::DropActions TreeWidget::supportedDropActions () const override protected
synchronizeSelectionCheckBoxes()
void TreeWidget::synchronizeSelectionCheckBoxes ()
References Gui::DocumentObjectItem::setData().
syncView()
void TreeWidget::syncView (ViewProviderDocumentObject * vp)
References Gui::DocumentItem::document(), Gui::TreeParams::Instance(), and Gui::Document::setActiveView().
Referenced by Gui::DocumentItem::selectItems(), and Gui::DocumentItem::updateItemSelection().
updateStatus()
void TreeWidget::updateStatus (bool delay = true) static
Referenced by Gui::Document::slotRecomputed().
Friends And Related Function Documentation
DocumentItem
friend class DocumentItem friend
DocumentObjectItem
friend class DocumentObjectItem friend
Member Data Documentation
DocumentType
const int TreeWidget::DocumentType = 1000 static
Referenced by contextMenuEvent(), dragMoveEvent(), dropEvent(), mouseDoubleClickEvent(), onAllowPartialRecompute(), onCloseDoc(), onCreateGroup(), onMarkRecompute(), onReloadDoc(), onShowHidden(), onSkipRecompute(), selectedDocument(), and startItemSearch().
ObjectType
const int TreeWidget::ObjectType = 1001 static
Referenced by contextMenuEvent(), Gui::TreeWidgetEditDelegate::createEditor(), dragMoveEvent(), dropEvent(), Gui::DocumentItem::findItem(), Gui::DocumentItem::findRootIndex(), Gui::DocumentObjectItem::getParentItem(), getSelection(), mimeData(), mouseDoubleClickEvent(), onCreateGroup(), onFinishEditing(), onHideInTree(), onMarkRecompute(), onPreSelectTimer(), onRecomputeObject(), onShowHidden(), onStartEditing(), Gui::DocumentItem::populateItem(), Gui::DocumentItem::showItem(), startItemSearch(), Gui::DocumentItem::updateItemsVisibility(), and Gui::DocumentItem::updateSelection().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Tree.h
Sources/FreeCAD/src/Gui/Tree.cpp