FreeCAD: MED::TTMeshInfo< eVersion > Struct Template Reference
MED::TTMeshInfo< eVersion > Struct Template Reference
#include <MED_TStructures.hxx>
Public Types
typedef TTNameInfo< eVersion > TNameInfoBase
Public Member Functions
virtual std::string GetDesc () const
Get description for the mesh.
virtual void SetDesc (const std::string &theValue)
Sets description for the mesh.
TTMeshInfo (const PMeshInfo &theInfo)
TTMeshInfo (TInt theDim, TInt theSpaceDim, const std::string &theValue, EMaillage theType, const std::string &theDesc)
Public Member Functions inherited from MED::TMeshInfo
TInt GetDim () const
Gets dimension of the mesh.
TInt GetSpaceDim () const
EMaillage GetType () const
Gets type of the mesh.
Public Member Functions inherited from MED::TBase
virtual ~TBase ()
Public Member Functions inherited from MED::TTNameInfo< eVersion >
virtual std::string GetName () const
Gets its name.
virtual void SetName (const std::string &theValue)
Set a new name.
virtual void SetName (const TString &theValue)
Set a new name.
TTNameInfo (const std::string &theValue)
Additional Inherited Members
Public Attributes inherited from MED::TMeshInfo
TString myDesc
Description of the mesh.
TInt myDim
Dimension of the mesh (0, 1, 2 or 3)
TInt mySpaceDim
EMaillage myType
Type of the mesh.
Public Attributes inherited from MED::TNameInfo
TString myName
Keeps its name.
Member Typedef Documentation
TNameInfoBase
template<EVersion eVersion> typedef TTNameInfo<eVersion> MED::TTMeshInfo< eVersion >::TNameInfoBase
Constructor & Destructor Documentation
TTMeshInfo() [1/2]
template<EVersion eVersion> MED::TTMeshInfo< eVersion >::TTMeshInfo (const PMeshInfo & theInfo)
References MED::TMeshInfo::myDesc, MED::TMeshInfo::myDim, MED::TMeshInfo::mySpaceDim, MED::TMeshInfo::myType, and MED::TTMeshInfo< eVersion >::SetDesc().
TTMeshInfo() [2/2]
template<EVersion eVersion> MED::TTMeshInfo< eVersion >::TTMeshInfo (TInt theDim, TInt theSpaceDim, const std::string & theValue, EMaillage theType, const std::string & theDesc)
References MED::TMeshInfo::myDesc, MED::TMeshInfo::myDim, MED::TMeshInfo::mySpaceDim, MED::TMeshInfo::myType, and MED::TTMeshInfo< eVersion >::SetDesc().
Member Function Documentation
GetDesc()
template<EVersion eVersion> virtual std::string MED::TTMeshInfo< eVersion >::GetDesc () const virtual
Get description for the mesh.
Implements MED::TMeshInfo.
References MED::GetString(), and MED::TMeshInfo::myDesc.
SetDesc()
template<EVersion eVersion> virtual void MED::TTMeshInfo< eVersion >::SetDesc (const std::string & theValue) virtual
Sets description for the mesh.
Implements MED::TMeshInfo.
References MED::TMeshInfo::myDesc, and MED::SetString().
Referenced by MED::TTMeshInfo< eVersion >::TTMeshInfo().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/MED_TStructures.hxx