FreeCAD: draftviewproviders.view_clone.ViewProviderClone Class Reference
draftviewproviders.view_clone.ViewProviderClone Class Reference
Workbenches » Python workbenches » Draft » draftviewproviders
Public Member Functions
def getDisplayModes (self, vobj)
def getIcon (self)
def resetColors (self, vobj)
def setDisplayMode (self, mode)
Detailed Description
a view provider that displays a Clone icon instead of a Draft icon
Member Function Documentation
getDisplayModes()
def draftviewproviders.view_clone.ViewProviderClone.getDisplayModes (self, vobj)
getIcon()
def draftviewproviders.view_clone.ViewProviderClone.getIcon (self)
Referenced by ArchAxisSystem.AxisSystemTaskPanel.update(), ArchComponent.ComponentTaskPanel.update(), and ArchSectionPlane.SectionPlaneTaskPanel.update().
resetColors()
def draftviewproviders.view_clone.ViewProviderClone.resetColors (self, vobj)
setDisplayMode()
def draftviewproviders.view_clone.ViewProviderClone.setDisplayMode (self, mode)
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Draft/draftviewproviders/view_clone.py