FreeCAD: Mesh::PropertyMeshKernel Class Reference
Mesh::PropertyMeshKernel Class Reference
The mesh kernel property class.
#include <MeshProperties.h>
Public Member Functions
PropertyMeshKernel ()
~PropertyMeshKernel ()
Getter/setter
void setValuePtr (MeshObject *m)
This method references the passed mesh object and takes possession of it, it does NOT create a copy.
void setValue (const MeshObject &m)
This method sets the mesh by copying the data.
void setValue (const MeshCore::MeshKernel &m)
This method sets the mesh by copying the data.
void swapMesh (MeshObject &)
Swaps the mesh data structure.
void swapMesh (MeshCore::MeshKernel &)
Swaps the mesh data structure.
const MeshObject & getValue () const
Returns a the attached mesh object by reference.
const MeshObject * getValuePtr () const
virtual unsigned int getMemSize () const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
Getting basic geometric entities
const Data::ComplexGeoData * getComplexData () const
Base::BoundBox3d getBoundingBox () const
Returns the bounding box around the underlying mesh kernel.
Modification
MeshObject * startEditing ()
void finishEditing ()
void transformGeometry (const Base::Matrix4D &rclMat)
Transform the real mesh data.
void setPointIndices (const std::vector< std::pair< PointIndex, Base::Vector3f > > &)
void setTransform (const Base::Matrix4D &rclTrf)
Set the placement of the geometry.
Base::Matrix4D getTransform () const
Get the placement of the geometry.
Python interface
PyObject * getPyObject ()
Returns a Python wrapper for the referenced mesh object.
void setPyObject (PyObject *value)
This method copies the content, hence creates an new mesh object to copy the data.
const char * getEditorName () const
Get the class name of the associated property editor item.
Public Member Functions inherited from App::PropertyComplexGeoData
PropertyComplexGeoData ()
virtual ~PropertyComplexGeoData ()
Public Member Functions inherited from App::PropertyGeometry
PropertyGeometry ()
virtual ~PropertyGeometry ()
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual Property * Copy (void) const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
int64_t getID () const
Return a unique ID for the property.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const char * getName (void) const
Get the name of this property in the belonging container With hasName() it can be checked beforehand if a valid name is set.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
bool hasName () const
Check if the property has a name set.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Save/restore
void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
void SaveDocFile (Base::Writer &writer) const
This method is used to save large amounts of data to a binary file.
void RestoreDocFile (Base::Reader &reader)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
App::Property * Copy () const
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const App::Property &from)
Paste the value from the property (mainly for Undo/Redo and transactions)
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , Busy = 15 ,
CopyOnChange = 16 , UserEdit = 17 , PropStaticBegin = 21 , PropDynamic = 21 ,
PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 , PropTransient = 25 ,
PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 , User1 = 28 ,
User2 = 29 , User3 = 30 , User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Check if the passed name is valid.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Detailed Description
The mesh kernel property class.
Author
Werner Mayer
Constructor & Destructor Documentation
PropertyMeshKernel()
PropertyMeshKernel::PropertyMeshKernel ()
Referenced by Copy().
~PropertyMeshKernel()
PropertyMeshKernel::~PropertyMeshKernel ()
Member Function Documentation
Copy()
App::Property * PropertyMeshKernel::Copy (void) const virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References PropertyMeshKernel().
finishEditing()
void PropertyMeshKernel::finishEditing ()
References App::Property::hasSetValue().
Referenced by MeshGui::Segmentation::accept(), MeshGui::SegmentationBestFit::accept(), ReverseEngineeringGui::Segmentation::accept(), ReverseEngineeringGui::SegmentationManual::createSegment(), MeshGui::ViewProviderMesh::fillHole(), MeshGui::DlgEvaluateMeshImp::on_repairSelfIntersectionButton_clicked(), MeshGui::ViewProviderMesh::removeFacets(), MeshGui::ViewProviderMesh::segmentMesh(), and MeshPropertyLock::~MeshPropertyLock().
getBoundingBox()
Base::BoundBox3d PropertyMeshKernel::getBoundingBox () const virtual
Returns the bounding box around the underlying mesh kernel.
Implements App::PropertyComplexGeoData.
getComplexData()
const Data::ComplexGeoData * PropertyMeshKernel::getComplexData () const virtual
Implements App::PropertyComplexGeoData.
getEditorName()
const char * Mesh::PropertyMeshKernel::getEditorName (void) const virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
getMemSize()
unsigned int PropertyMeshKernel::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
See also
Base::Persistence
Reimplemented from App::Property.
getPyObject()
PyObject * PropertyMeshKernel::getPyObject (void) virtual
Returns a Python wrapper for the referenced mesh object.
It does NOT create a copy. However, the Python wrapper is marked as immutable so that the mesh object cannot be modified from outside.
Reimplemented from Base::BaseClass.
getTransform()
Base::Matrix4D PropertyMeshKernel::getTransform () const virtual
Get the placement of the geometry.
Implements App::PropertyGeometry.
getValue()
const MeshObject & PropertyMeshKernel::getValue (void) const
Returns a the attached mesh object by reference.
It cannot be modified from outside.
Referenced by MeshPartGui::CrossSections::apply(), MeshPartGui::CurveOnMeshHandler::Private::createGrid(), MeshGui::MeshSelection::deleteSelection(), MeshGui::ViewProviderMesh::deleteSelection(), MeshGui::MeshSelection::deleteSelectionBorder(), Mesh::Curvature::execute(), Mesh::HarmonizeNormals::execute(), Mesh::FlipNormals::execute(), Mesh::FixNonManifolds::execute(), Mesh::FixDuplicatedFaces::execute(), Mesh::FixDuplicatedPoints::execute(), Mesh::FixDegenerations::execute(), Mesh::FixDeformations::execute(), Mesh::FixIndices::execute(), Mesh::FillHoles::execute(), Mesh::RemoveComponents::execute(), Mesh::Export::execute(), Mesh::SegmentByMesh::execute(), Mesh::SetOperations::execute(), MeshGui::ViewProviderMesh::faceInfo(), MeshGui::ViewProviderMesh::fillHole(), MeshGui::ViewProviderMesh::getFacetsFromPolygon(), MeshGui::ViewProviderMesh::getVisibleFacets(), MeshGui::ViewProviderMeshNode::handleEvent(), MeshGui::ViewProviderMesh::hasSelection(), MeshGui::MeshSplit::makeCopy(), MeshGui::DlgEvaluateMeshImp::on_analyzeDegeneratedButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_analyzeDuplicatedFacesButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_analyzeDuplicatedPointsButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_analyzeFoldsButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_analyzeIndicesButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_analyzeNonmanifoldsButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_analyzeOrientationButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_analyzeSelfIntersectionButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairAllTogether_clicked(), MeshInfoWatcher::onSelectionChanged(), MeshGui::ViewProviderMesh::segmentMesh(), MeshGui::DlgEvaluateMeshImp::showInformation(), MeshGui::ViewProviderMesh::splitMesh(), MeshGui::ViewProviderMesh::tryColorPerVertexOrFace(), and MeshGui::PropertyMeshKernelItem::value().
getValuePtr()
const MeshObject * PropertyMeshKernel::getValuePtr () const
Referenced by MeshGui::Segmentation::accept(), MeshGui::SegmentationBestFit::accept(), MeshGui::ViewProviderMeshNode::attach(), MeshGui::MeshSelection::deselectComponent(), MeshGui::MeshSelection::fullSelection(), MeshGui::MeshSelection::selectComponent(), and MeshGui::ViewProviderMeshNode::showOpenEdges().
Paste()
void PropertyMeshKernel::Paste (const App::Property & from) virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Restore()
void PropertyMeshKernel::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References App::Property::aboutToSetValue(), Base::XMLReader::addFile(), MeshCore::MeshKernel::Adopt(), Base::XMLReader::getAttribute(), App::Property::hasSetValue(), MeshCore::MeshInput::LoadXML(), and Base::XMLReader::readElement().
RestoreDocFile()
void PropertyMeshKernel::RestoreDocFile (Base::Reader &) virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Base::Persistence.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Save()
void PropertyMeshKernel::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References Base::Writer::addFile(), Base::Writer::ind(), Base::Writer::isForceXML(), MeshCore::MeshOutput::SaveXML(), and Base::Writer::Stream().
SaveDocFile()
void PropertyMeshKernel::SaveDocFile (Base::Writer &) const virtual
This method is used to save large amounts of data to a binary file.
Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) << "\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
void PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Base::Persistence.
References Base::Writer::Stream().
setPointIndices()
void PropertyMeshKernel::setPointIndices (const std::vector< std::pair< PointIndex, Base::Vector3f > > & inds)
References App::Property::aboutToSetValue(), App::Property::hasSetValue(), and MeshCore::MeshKernel::SetPoint().
setPyObject()
void PropertyMeshKernel::setPyObject (PyObject * value) virtual
This method copies the content, hence creates an new mesh object to copy the data.
The passed argument can be an instance of the Python wrapper for the mesh object or simply a list of triangles, i.e. a list of lists of three floats.
Reimplemented from Base::BaseClass.
References Mesh::MeshObject::createMeshFromList(), setValue(), and setValuePtr().
setTransform()
void PropertyMeshKernel::setTransform (const Base::Matrix4D & rclTrf) virtual
Set the placement of the geometry.
Implements App::PropertyGeometry.
setValue() [1/2]
void PropertyMeshKernel::setValue (const MeshCore::MeshKernel & m)
This method sets the mesh by copying the data.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
setValue() [2/2]
void PropertyMeshKernel::setValue (const MeshObject & m)
This method sets the mesh by copying the data.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Referenced by MeshGui::RemeshGmsh::loadOutput(), MeshPartGui::Mesh2ShapeGmsh::loadOutput(), MeshGui::MeshSplit::makeCopy(), and setPyObject().
setValuePtr()
void PropertyMeshKernel::setValuePtr (MeshObject * m)
This method references the passed mesh object and takes possession of it, it does NOT create a copy.
The currently referenced mesh object gets de-referenced and possibly deleted if its reference counter becomes zero. However, the mesh gets saved before if a transaction is open at this time.
Note
Make sure not to reference the internal mesh pointer pf this class in client code. This could lead to crashes if not handled properly.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Referenced by setPyObject().
startEditing()
MeshObject * PropertyMeshKernel::startEditing ()
References App::Property::aboutToSetValue().
Referenced by MeshGui::Segmentation::accept(), MeshGui::SegmentationBestFit::accept(), ReverseEngineeringGui::Segmentation::accept(), ReverseEngineeringGui::SegmentationManual::createSegment(), MeshGui::ViewProviderMesh::fillHole(), MeshPropertyLock::MeshPropertyLock(), draftguitools.gui_edit.Edit::mousePressed(), MeshGui::DlgEvaluateMeshImp::on_repairSelfIntersectionButton_clicked(), MeshGui::ViewProviderMesh::removeFacets(), and MeshGui::ViewProviderMesh::segmentMesh().
swapMesh() [1/2]
void PropertyMeshKernel::swapMesh (MeshCore::MeshKernel & mesh)
Swaps the mesh data structure.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
swapMesh() [2/2]
void PropertyMeshKernel::swapMesh (MeshObject & mesh)
Swaps the mesh data structure.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
transformGeometry()
void PropertyMeshKernel::transformGeometry (const Base::Matrix4D & rclMat) virtual
Transform the real mesh data.
Implements App::PropertyComplexGeoData.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/MeshProperties.h
FreeCAD/src/Mod/Mesh/App/MeshProperties.cpp