FreeCAD: Path::Voronoi Class Reference
Path::Voronoi Class Reference
#include <Voronoi.h>
Classes
class diagram_type
Public Types
typedef std::size_t color_type
typedef double coordinate_type
typedef boost::polygon::point_data< coordinate_type > point_type
typedef boost::polygon::segment_data< coordinate_type > segment_type
typedef boost::polygon::voronoi_vertex< double > vertex_type
typedef boost::polygon::voronoi_diagram< double > voronoi_diagram_type
Public Member Functions
void addPoint (const point_type &p)
void addSegment (const segment_type &p)
void colorColinear (color_type color, double degree)
void colorExterior (color_type color)
void colorTwins (color_type color)
void construct ()
template<typename T >
T * create (int index)
double getScale () const
long numCells () const
long numEdges () const
long numPoints () const
long numSegments () const
long numVertices () const
void resetColor (color_type color)
void setScale (double scale)
Voronoi ()
~Voronoi ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId (void) const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Static Public Attributes
static const color_type ColorMask = PATH_VORONOI_COLOR_MASK
static const int InvalidIndex = INT_MAX
Friends
class VoronoiPy
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Member Typedef Documentation
color_type
typedef std::size_t Path::Voronoi::color_type
coordinate_type
typedef double Path::Voronoi::coordinate_type
point_type
typedef boost::polygon::point_data<coordinate_type> Path::Voronoi::point_type
segment_type
typedef boost::polygon::segment_data<coordinate_type> Path::Voronoi::segment_type
vertex_type
typedef boost::polygon::voronoi_vertex<double> Path::Voronoi::vertex_type
voronoi_diagram_type
typedef boost::polygon::voronoi_diagram<double> Path::Voronoi::voronoi_diagram_type
Constructor & Destructor Documentation
Voronoi()
Voronoi::Voronoi ()
~Voronoi()
Voronoi::~Voronoi ()
Member Function Documentation
addPoint()
void Voronoi::addPoint (const point_type & p)
Referenced by Path::VoronoiPy::addPoint().
addSegment()
void Voronoi::addSegment (const segment_type & p)
Referenced by Path::VoronoiPy::addSegment().
colorColinear()
void Voronoi::colorColinear (Voronoi::color_type color, double degree)
References DraftVecUtils::angle().
Referenced by Path::VoronoiPy::colorColinear().
colorExterior()
void Voronoi::colorExterior (Voronoi::color_type color)
Referenced by Path::VoronoiPy::colorExterior().
colorTwins()
void Voronoi::colorTwins (Voronoi::color_type color)
Referenced by Path::VoronoiPy::colorTwins().
construct()
void Voronoi::construct ()
Referenced by Path::VoronoiPy::construct().
create()
template<typename T > T* Path::Voronoi::create (int index)
getScale()
double Path::Voronoi::getScale (void) const
Referenced by Path::VoronoiPy::PyInit().
numCells()
long Voronoi::numCells () const
Referenced by Path::VoronoiPy::getCells(), and Path::VoronoiPy::representation().
numEdges()
long Voronoi::numEdges () const
Referenced by Path::VoronoiPy::getEdges(), and Path::VoronoiPy::representation().
numPoints()
long Voronoi::numPoints () const
Referenced by Path::VoronoiPy::representation().
numSegments()
long Voronoi::numSegments () const
Referenced by Path::VoronoiPy::representation().
numVertices()
long Voronoi::numVertices () const
Referenced by Path::VoronoiPy::getVertices(), and Path::VoronoiPy::representation().
resetColor()
void Voronoi::resetColor (Voronoi::color_type color)
Referenced by Path::VoronoiPy::resetColor().
setScale()
void Path::Voronoi::setScale (double scale)
Referenced by Path::VoronoiPy::PyInit().
Friends And Related Function Documentation
VoronoiPy
friend class VoronoiPy friend
Member Data Documentation
ColorMask
const color_type Path::Voronoi::ColorMask = PATH_VORONOI_COLOR_MASK static
Referenced by Path::VoronoiCellPy::getColor(), Path::VoronoiEdgePy::getColor(), Path::VoronoiVertexPy::getColor(), Path::VoronoiCellPy::setColor(), Path::VoronoiEdgePy::setColor(), and Path::VoronoiVertexPy::setColor().
InvalidIndex
const int Path::Voronoi::InvalidIndex = INT_MAX static
Referenced by Path::VoronoiCell::isBound(), Path::VoronoiEdge::isBound(), and Path::VoronoiVertex::isBound().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Path/App/Voronoi.h
Sources/FreeCAD/src/Mod/Path/App/Voronoi.cpp