FreeCAD: MeshGui::PlaneFitParameter Class Reference
MeshGui::PlaneFitParameter Class Reference
Public Member Functions
virtual std::vector< float > getParameter (FitParameter::Points pts) const
PlaneFitParameter ()
virtual ~PlaneFitParameter ()
Public Member Functions inherited from MeshGui::FitParameter
virtual std::vector< float > getParameter (Points) const =0
virtual ~FitParameter ()
Constructor & Destructor Documentation
PlaneFitParameter()
MeshGui::PlaneFitParameter::PlaneFitParameter ()
~PlaneFitParameter()
virtual MeshGui::PlaneFitParameter::~PlaneFitParameter () virtual
Member Function Documentation
getParameter()
virtual std::vector< float > MeshGui::PlaneFitParameter::getParameter (FitParameter::Points pts) const virtual
Implements MeshGui::FitParameter.
References MeshCore::Approximation::AddPoints(), MeshCore::PlaneFit::Fit(), MeshCore::PlaneFit::GetBase(), MeshCore::PlaneFit::GetNormal(), MeshGui::FitParameter::Points::points, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Mesh/Gui/SegmentationBestFit.cpp