FreeCAD: ParameterSerializer Class Reference
ParameterSerializer Class Reference
The parameter serializer class This is a helper class to serialize a parameter XML document.
#include <Parameter.h>
Public Member Functions
virtual int LoadDocument (ParameterManager &)
virtual bool LoadOrCreateDocument (ParameterManager &)
ParameterSerializer (const std::string &fn)
virtual void SaveDocument (const ParameterManager &)
virtual ~ParameterSerializer ()
Protected Attributes
std::string filename
Detailed Description
The parameter serializer class This is a helper class to serialize a parameter XML document.
Does loading and saving the DOM document from and to files. In sub-classes the load and saving of XML documents can be customized.
See also
ParameterManager
Constructor & Destructor Documentation
ParameterSerializer()
ParameterSerializer::ParameterSerializer (const std::string & fn)
~ParameterSerializer()
ParameterSerializer::~ParameterSerializer () virtual
Member Function Documentation
LoadDocument()
int ParameterSerializer::LoadDocument (ParameterManager & mgr) virtual
References filename, and ParameterManager::LoadDocument().
Referenced by ParameterManager::LoadDocument().
LoadOrCreateDocument()
bool ParameterSerializer::LoadOrCreateDocument (ParameterManager & mgr) virtual
References filename, and ParameterManager::LoadOrCreateDocument().
Referenced by ParameterManager::LoadOrCreateDocument().
SaveDocument()
void ParameterSerializer::SaveDocument (const ParameterManager & mgr) virtual
References filename, and ParameterManager::SaveDocument().
Referenced by ParameterManager::SaveDocument().
Member Data Documentation
filename
std::string ParameterSerializer::filename protected
Referenced by ArchReference.ArchReferenceTaskPanel::accept(), ArchReference.ArchReferenceTaskPanel::chooseFile(), addonmanager_macro.Macro::is_installed(), LoadDocument(), LoadOrCreateDocument(), exportDRAWEXE.Drawexporter::process_object(), SaveDocument(), and exportDRAWEXE.Drawexporter::saveSweep().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Base/Parameter.h
Sources/FreeCAD/src/Base/Parameter.cpp