FreeCAD: App::PropertyListsBase Class Reference
App::PropertyListsBase Class Reference abstract
Helper class to construct list like properties.
#include <Property.h>
Public Member Functions
void clearTouchList ()
virtual int getSize (void) const =0
const std::set< int > & getTouchList () const
virtual void setSize (int newSize)=0
Protected Member Functions
virtual void setPyValues (const std::vector< PyObject * > &vals, const std::vector< int > &indices)
Detailed Description
Helper class to construct list like properties.
This class is not derived from Property so that we can have more that one base class for list like properties, e.g. see PropertyList, and PropertyLinkListBase
Member Function Documentation
clearTouchList()
void App::PropertyListsBase::clearTouchList ()
getSize()
virtual int App::PropertyListsBase::getSize (void) const pure virtual
Implemented in Sketcher::PropertyConstraintList, App::PropertyListsT< T, ListT, ParentT >, App::PropertyListsT< long >, App::PropertyListsT< Base::Vector3d >, App::PropertyListsT< Color >, App::PropertyListsT< double >, App::PropertyListsT< std::string >, App::PropertyListsT< bool, boost::dynamic_bitset<> >, App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >, App::PropertyListsT< Material >, App::PropertyListsT< Base::Placement >, TechDraw::PropertyGeomFormatList, TechDraw::PropertyCosmeticVertexList, TechDraw::PropertyCosmeticEdgeList, TechDraw::PropertyCenterLineList, Points::PropertyCurvatureList, Points::PropertyNormalList, Points::PropertyGreyValueList, Part::PropertyFilletEdges, Part::PropertyShapeHistory, Part::PropertyGeometryList, Mesh::PropertyCurvatureList, Mesh::PropertyNormalList, and Inspection::PropertyDistanceList.
Referenced by Gui::ViewProviderLink::applyMaterial(), Surface::GeomFillSurface::onChanged(), and Gui::ViewProviderLink::updateElementList().
getTouchList()
const std::set<int>& App::PropertyListsBase::getTouchList () const
setPyValues()
virtual void App::PropertyListsBase::setPyValues (const std::vector< PyObject * > & vals, const std::vector< int > & indices) protected virtual
Reimplemented in App::PropertyListsT< T, ListT, ParentT >, App::PropertyListsT< long >, App::PropertyListsT< Base::Vector3d >, App::PropertyListsT< Color >, App::PropertyListsT< double >, App::PropertyListsT< std::string >, App::PropertyListsT< bool, boost::dynamic_bitset<> >, App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >, App::PropertyListsT< Material >, and App::PropertyListsT< Base::Placement >.
setSize()
virtual void App::PropertyListsBase::setSize (int newSize) pure virtual
Implemented in Sketcher::PropertyConstraintList, App::PropertyLinkList, App::PropertyListsT< T, ListT, ParentT >, App::PropertyListsT< long >, App::PropertyListsT< Base::Vector3d >, App::PropertyListsT< Color >, App::PropertyListsT< double >, App::PropertyListsT< std::string >, App::PropertyListsT< bool, boost::dynamic_bitset<> >, App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >, App::PropertyListsT< Material >, App::PropertyListsT< Base::Placement >, TechDraw::PropertyGeomFormatList, TechDraw::PropertyCosmeticVertexList, TechDraw::PropertyCosmeticEdgeList, TechDraw::PropertyCenterLineList, Points::PropertyCurvatureList, Points::PropertyNormalList, Points::PropertyGreyValueList, Part::PropertyFilletEdges, Part::PropertyShapeHistory, Part::PropertyGeometryList, Mesh::PropertyCurvatureList, Mesh::PropertyNormalList, and Inspection::PropertyDistanceList.
Referenced by Surface::GeomFillSurface::onChanged(), and Gui::ViewProviderLink::updateElementList().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/App/Property.h
Sources/FreeCAD/src/App/Property.cpp