FreeCAD: Inspection::InspectActualShape Class Reference
Inspection::InspectActualShape Class Reference
#include <InspectionFeature.h>
Public Member Functions
virtual unsigned long countPoints () const
Number of points to be checked.
virtual Base::Vector3f getPoint (unsigned long) const
InspectActualShape (const Part::TopoShape &)
Public Member Functions inherited from Inspection::InspectActualGeometry
InspectActualGeometry ()
virtual ~InspectActualGeometry ()
Constructor & Destructor Documentation
InspectActualShape()
InspectActualShape::InspectActualShape (const Part::TopoShape & shape)
References App::GetApplication(), ParameterGrp::GetFloat(), App::Application::GetParameterGroupByPath(), Base::BoundBox3< _Precision >::LengthX(), Base::BoundBox3< _Precision >::LengthY(), and Base::BoundBox3< _Precision >::LengthZ().
Member Function Documentation
countPoints()
unsigned long InspectActualShape::countPoints () const virtual
Number of points to be checked.
Implements Inspection::InspectActualGeometry.
getPoint()
Base::Vector3f InspectActualShape::getPoint (unsigned long index) const virtual
Implements Inspection::InspectActualGeometry.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Inspection/App/InspectionFeature.h
Sources/FreeCAD/src/Mod/Inspection/App/InspectionFeature.cpp