FreeCAD: DriverMED_Family Class Reference
DriverMED_Family Class Reference
#include <DriverMED_Family.h>
Public Member Functions
void AddElement (const SMDS_MeshElement *theElement)
void AddGroupName (std::string theGroupName)
DriverMED_Family ()
const ElementsSet & GetElements () const
Returns elements of this family.
MED::PFamilyInfo GetFamilyInfo (const MED::PWrapper &theWrapper, const MED::PMeshInfo &theMeshInfo) const
Create TFamilyInfo for this family.
int GetGroupAttributVal () const
const MED::TStringSet & GetGroupNames () const
int GetId () const
Returns a family ID.
SMDSAbs_ElementType GetType ()
const std::set< SMDSAbs_ElementType > & GetTypes () const
bool MemberOf (std::string theGroupName) const
void SetGroupAttributVal (int theValue)
void SetId (const int theId)
Sets a family ID.
void SetType (const SMDSAbs_ElementType theType)
Static Public Member Functions
static DriverMED_FamilyPtrList MakeFamilies (SMESHDS_SubMeshIteratorPtr theSubMeshes, const SMESHDS_GroupBasePtrList &theGroups, const bool doGroupOfNodes, const bool doGroupOfEdges, const bool doGroupOfFaces, const bool doGroupOfVolumes, const bool doGroupOf0DElems, const bool doGroupOfBalls)
Methods for groups storing to MED.
Constructor & Destructor Documentation
DriverMED_Family()
DriverMED_Family::DriverMED_Family ()
Default constructor
Member Function Documentation
AddElement()
void DriverMED_Family::AddElement (const SMDS_MeshElement * theElement)
AddGroupName()
void DriverMED_Family::AddGroupName (std::string theGroupName)
GetElements()
const ElementsSet & DriverMED_Family::GetElements () const
Returns elements of this family.
GetFamilyInfo()
MED::PFamilyInfo DriverMED_Family::GetFamilyInfo (const MED::PWrapper & theWrapper, const MED::PMeshInfo & theMeshInfo) const
Create TFamilyInfo for this family.
Create TFamilyInfo for this family
GetGroupAttributVal()
int DriverMED_Family::GetGroupAttributVal () const
GetGroupNames()
const MED::TStringSet & DriverMED_Family::GetGroupNames () const
GetId()
int DriverMED_Family::GetId () const
Returns a family ID.
GetType()
SMDSAbs_ElementType DriverMED_Family::GetType ()
GetTypes()
const std::set< SMDSAbs_ElementType > & DriverMED_Family::GetTypes () const
MakeFamilies()
DriverMED_FamilyPtrList DriverMED_Family::MakeFamilies (SMESHDS_SubMeshIteratorPtr theSubMeshes, const SMESHDS_GroupBasePtrList & theGroups, const bool doGroupOfNodes, const bool doGroupOfEdges, const bool doGroupOfFaces, const bool doGroupOfVolumes, const bool doGroupOf0DElems, const bool doGroupOfBalls) static
Methods for groups storing to MED.
Split each group from list <theGroups> and each sub-mesh from list <theSubMeshes> on some parts (families) on the basis of the elements membership in other groups from <theGroups> and other sub-meshes from <theSubMeshes>. Resulting families have no common elements.
Split each group from list <aGroups> on some parts (families) on the basis of the elements membership in other groups from this list. Resulting families have no common elements.
References SMESHDS_SubMesh::GetID(), and SMESHDS_SubMesh::IsComplexSubmesh().
Referenced by DriverMED_W_SMESHDS_Mesh::Perform().
MemberOf()
bool DriverMED_Family::MemberOf (std::string theGroupName) const
SetGroupAttributVal()
void DriverMED_Family::SetGroupAttributVal (int theValue)
SetId()
void DriverMED_Family::SetId (const int theId)
Sets a family ID.
SetType()
void DriverMED_Family::SetType (const SMDSAbs_ElementType theType)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/DriverMED_Family.h
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/DriverMED_Family.cpp