FreeCAD: Part::Line2dSegmentPy Class Reference
Part::Line2dSegmentPy Class Reference
The python export class for Geom2dLineSegment.
#include <Line2dSegmentPy.h>
Public Types
typedef Geom2dLineSegment * PointerType
Public Types inherited from Part::Curve2dPy
typedef Geom2dCurve * PointerType
Public Types inherited from Part::Geometry2dPy
typedef Geometry2d * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
Line2dSegmentPy (Geom2dLineSegment *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Part::Curve2dPy
Curve2dPy (Geom2dCurve *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * reverse (PyObject *args)
implementer for the reverse() method
PyObject * toShape (PyObject *args)
implementer for the toShape() method
PyObject * discretize (PyObject *args, PyObject *kwd)
implementer for the discretize() method
PyObject * length (PyObject *args)
implementer for the length() method
PyObject * parameterAtDistance (PyObject *args)
implementer for the parameterAtDistance() method
PyObject * value (PyObject *args)
implementer for the value() method
PyObject * tangent (PyObject *args)
implementer for the tangent() method
PyObject * parameter (PyObject *args)
implementer for the parameter() method
PyObject * normal (PyObject *args)
implementer for the normal() method
PyObject * curvature (PyObject *args)
implementer for the curvature() method
PyObject * centerOfCurvature (PyObject *args)
implementer for the centerOfCurvature() method
PyObject * intersectCC (PyObject *args)
implementer for the intersectCC() method
PyObject * toBSpline (PyObject *args)
implementer for the toBSpline() method
PyObject * approximateBSpline (PyObject *args)
implementer for the approximateBSpline() method
Py::String getContinuity (void) const
getter for the Continuity attribute
Py::Boolean getClosed (void) const
getter for the Closed attribute
Py::Boolean getPeriodic (void) const
getter for the Periodic attribute
Py::Float getFirstParameter (void) const
getter for the FirstParameter attribute
Py::Float getLastParameter (void) const
getter for the LastParameter attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geom2dCurve * getGeom2dCurvePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Part::Geometry2dPy
Geometry2dPy (Geometry2d *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geometry2d * getGeometry2dPtr (void) const
getter for the object handled by this class
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * copy (PyObject *args)
implementer for the copy() method
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::Curve2dPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_reverse (PyObject *self, PyObject *args)
callback for the reverse() method
static PyObject * staticCallback_toShape (PyObject *self, PyObject *args)
callback for the toShape() method
static PyObject * staticCallback_discretize (PyObject *self, PyObject *args, PyObject *kwd)
callback for the discretize() method
static PyObject * staticCallback_length (PyObject *self, PyObject *args)
callback for the length() method
static PyObject * staticCallback_parameterAtDistance (PyObject *self, PyObject *args)
callback for the parameterAtDistance() method
static PyObject * staticCallback_value (PyObject *self, PyObject *args)
callback for the value() method
static PyObject * staticCallback_tangent (PyObject *self, PyObject *args)
callback for the tangent() method
static PyObject * staticCallback_parameter (PyObject *self, PyObject *args)
callback for the parameter() method
static PyObject * staticCallback_normal (PyObject *self, PyObject *args)
callback for the normal() method
static PyObject * staticCallback_curvature (PyObject *self, PyObject *args)
callback for the curvature() method
static PyObject * staticCallback_centerOfCurvature (PyObject *self, PyObject *args)
callback for the centerOfCurvature() method
static PyObject * staticCallback_intersectCC (PyObject *self, PyObject *args)
callback for the intersectCC() method
static PyObject * staticCallback_toBSpline (PyObject *self, PyObject *args)
callback for the toBSpline() method
static PyObject * staticCallback_approximateBSpline (PyObject *self, PyObject *args)
callback for the approximateBSpline() method
static PyObject * staticCallback_getContinuity (PyObject *self, void *closure)
getter callback for the Continuity attribute
static int staticCallback_setContinuity (PyObject *self, PyObject *value, void *closure)
setter callback for the Continuity attribute
static PyObject * staticCallback_getClosed (PyObject *self, void *closure)
getter callback for the Closed attribute
static int staticCallback_setClosed (PyObject *self, PyObject *value, void *closure)
setter callback for the Closed attribute
static PyObject * staticCallback_getPeriodic (PyObject *self, void *closure)
getter callback for the Periodic attribute
static int staticCallback_setPeriodic (PyObject *self, PyObject *value, void *closure)
setter callback for the Periodic attribute
static PyObject * staticCallback_getFirstParameter (PyObject *self, void *closure)
getter callback for the FirstParameter attribute
static int staticCallback_setFirstParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the FirstParameter attribute
static PyObject * staticCallback_getLastParameter (PyObject *self, void *closure)
getter callback for the LastParameter attribute
static int staticCallback_setLastParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the LastParameter attribute
Static Public Member Functions inherited from Part::Geometry2dPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of Line2dSegmentPy.
static PyMethodDef Methods []
Methods structure of Line2dSegmentPy.
static PyTypeObject Type
Type structure of Line2dSegmentPy.
Static Public Attributes inherited from Part::Curve2dPy
static PyGetSetDef GetterSetter []
Attribute structure of Curve2dPy.
static PyMethodDef Methods []
Methods structure of Curve2dPy.
static PyTypeObject Type
Type structure of Curve2dPy.
Static Public Attributes inherited from Part::Geometry2dPy
static PyGetSetDef GetterSetter []
Attribute structure of Geometry2dPy.
static PyMethodDef Methods []
Methods structure of Geometry2dPy.
static PyTypeObject Type
Type structure of Geometry2dPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~Line2dSegmentPy ()
Protected Member Functions inherited from Part::Curve2dPy
~Curve2dPy ()
Protected Member Functions inherited from Part::Geometry2dPy
~Geometry2dPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * setParameterRange (PyObject *args)
implementer for the setParameterRange() method
static PyObject * staticCallback_setParameterRange (PyObject *self, PyObject *args)
callback for the setParameterRange() method
callbacks and implementers for the python object attributes
Py::Object getStartPoint (void) const
getter for the StartPoint attribute
void setStartPoint (Py::Object arg)
setter for the StartPoint attribute
Py::Object getEndPoint (void) const
getter for the EndPoint attribute
void setEndPoint (Py::Object arg)
setter for the EndPoint attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geom2dLineSegment * getGeom2dLineSegmentPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getStartPoint (PyObject *self, void *closure)
getter callback for the StartPoint attribute
static int staticCallback_setStartPoint (PyObject *self, PyObject *value, void *closure)
setter callback for the StartPoint attribute
static PyObject * staticCallback_getEndPoint (PyObject *self, void *closure)
getter callback for the EndPoint attribute
static int staticCallback_setEndPoint (PyObject *self, PyObject *value, void *closure)
setter callback for the EndPoint attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Geom2dLineSegment.
Member Typedef Documentation
PointerType
typedef Geom2dLineSegment* Part::Line2dSegmentPy::PointerType
Constructor & Destructor Documentation
~Line2dSegmentPy()
Line2dSegmentPy::~Line2dSegmentPy () protected
Line2dSegmentPy()
Line2dSegmentPy::Line2dSegmentPy (Geom2dLineSegment * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getCustomAttributes()
PyObject * Line2dSegmentPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getEndPoint()
Py::Object Line2dSegmentPy::getEndPoint (void) const
getter for the EndPoint attribute
References getGeom2dLineSegmentPtr().
Referenced by staticCallback_getEndPoint().
getGeom2dLineSegmentPtr()
Geom2dLineSegment * Line2dSegmentPy::getGeom2dLineSegmentPtr (void) const
getter for the object handled by this class
Referenced by getEndPoint(), getStartPoint(), PyInit(), setEndPoint(), setParameterRange(), and setStartPoint().
getStartPoint()
Py::Object Line2dSegmentPy::getStartPoint (void) const
getter for the StartPoint attribute
References getGeom2dLineSegmentPtr().
Referenced by staticCallback_getStartPoint().
GetType()
virtual PyTypeObject* Part::Line2dSegmentPy::GetType (void) virtual
Reimplemented from Part::Curve2dPy.
PyInit()
int Line2dSegmentPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::Curve2dPy.
References Part::Line2dPy::getGeom2dLinePtr(), getGeom2dLineSegmentPtr(), Part::PartExceptionOCCError, Part::Line2dPy::Type, and Type.
PyMake()
PyObject * Line2dSegmentPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References Line2dSegmentPy().
representation()
std::string Line2dSegmentPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int Line2dSegmentPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setEndPoint()
void Line2dSegmentPy::setEndPoint (Py::Object arg)
setter for the EndPoint attribute
References getGeom2dLineSegmentPtr().
Referenced by staticCallback_setEndPoint().
setParameterRange()
PyObject * Line2dSegmentPy::setParameterRange (PyObject * args)
implementer for the setParameterRange() method
References getGeom2dLineSegmentPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setParameterRange().
setStartPoint()
void Line2dSegmentPy::setStartPoint (Py::Object arg)
setter for the StartPoint attribute
References getGeom2dLineSegmentPtr().
Referenced by staticCallback_setStartPoint().
staticCallback_getEndPoint()
PyObject * Line2dSegmentPy::staticCallback_getEndPoint (PyObject * self, void * closure) static
getter callback for the EndPoint attribute
References Base::BaseExceptionFreeCADError, getEndPoint(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getStartPoint()
PyObject * Line2dSegmentPy::staticCallback_getStartPoint (PyObject * self, void * closure) static
getter callback for the StartPoint attribute
References Base::BaseExceptionFreeCADError, getStartPoint(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setEndPoint()
int Line2dSegmentPy::staticCallback_setEndPoint (PyObject * self, PyObject * value, void * closure) static
setter callback for the EndPoint attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setEndPoint().
staticCallback_setParameterRange()
PyObject * Line2dSegmentPy::staticCallback_setParameterRange (PyObject * self, PyObject * args) static
callback for the setParameterRange() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setParameterRange(), and Base::PyObjectBase::startNotify().
staticCallback_setStartPoint()
int Line2dSegmentPy::staticCallback_setStartPoint (PyObject * self, PyObject * value, void * closure) static
setter callback for the StartPoint attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setStartPoint().
Member Data Documentation
GetterSetter
PyGetSetDef Line2dSegmentPy::GetterSetter static
Initial value:
= {
    {"StartPoint",
        (getter) staticCallback_getStartPoint,
        (setter) staticCallback_setStartPoint,
        "Returns the start point of this line segment.",
        NULL
    },
    {"EndPoint",
        (getter) staticCallback_getEndPoint,
        (setter) staticCallback_setEndPoint,
        "Returns the end point of this line segment.",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of Line2dSegmentPy.
Methods
PyMethodDef Line2dSegmentPy::Methods static
Initial value:
= {
    {"setParameterRange",
        reinterpret_cast<PyCFunction>( staticCallback_setParameterRange ),
        METH_VARARGS,
        "Set the parameter range of the underlying line segment geometry"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of Line2dSegmentPy.
Type
PyTypeObject Line2dSegmentPy::Type static
Type structure of Line2dSegmentPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), and PyInit().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/Geom2d/Line2dSegmentPy.h
Sources/FreeCAD/src/Mod/Part/App/Geom2d/Line2dSegmentPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/Geom2d/Line2dSegmentPy.cpp