FreeCAD: TechDraw::CosmeticVertex Class Reference
TechDraw::CosmeticVertex Class Reference
#include <Cosmetic.h>
Public Member Functions
CosmeticVertex * clone (void) const
CosmeticVertex * copy (void) const
CosmeticVertex ()
CosmeticVertex (Base::Vector3d loc)
CosmeticVertex (const CosmeticVertex *cv)
void dump (const char *title)
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
boost::uuids::uuid getTag () const
virtual std::string getTagAsString (void) const
void move (Base::Vector3d newPos)
void moveRelative (Base::Vector3d movement)
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
Base::Vector3d scaled (double factor)
std::string toString (void) const
virtual ~CosmeticVertex ()=default
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from TechDraw::Vertex
boost::uuids::uuid getTag () const
bool isEqual (Vertex *v, double tol)
void point (Base::Vector3d v)
Base::Vector3d point (void) const
Vertex ()
Vertex (Base::Vector3d v)
Vertex (const Vertex *v)
Vertex (double x, double y)
double x ()
double y ()
virtual ~Vertex ()
Static Public Member Functions
static bool restoreCosmetic (void)
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Public Attributes
App::Color color
int linkGeom
Base::Vector3d permaPoint
double size
int style
bool visible
Public Attributes inherited from TechDraw::Vertex
bool cosmetic
int cosmeticLink
std::string cosmeticTag
ExtractionType extractType
bool hlrVisible
bool isCenter
TopoDS_Vertex occVertex
Base::Vector3d pnt
int ref3D
bool reference
Protected Member Functions
void assignTag (const TechDraw::CosmeticVertex *cv)
void createNewTag ()
Protected Member Functions inherited from TechDraw::Vertex
void assignTag (const TechDraw::Vertex *v)
void createNewTag ()
Protected Attributes
Py::Object PythonObject
boost::uuids::uuid tag
Protected Attributes inherited from TechDraw::Vertex
boost::uuids::uuid tag
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
CosmeticVertex() [1/3]
CosmeticVertex::CosmeticVertex ()
References TechDraw::LineGroup::getDefaultWidth(), TechDraw::Preferences::lineGroup(), TechDraw::Preferences::vertexColor(), and TechDraw::Preferences::vertexScale().
Referenced by copy().
CosmeticVertex() [2/3]
CosmeticVertex::CosmeticVertex (const CosmeticVertex * cv)
References color, TechDraw::Vertex::cosmetic, createNewTag(), TechDraw::Vertex::hlrVisible, linkGeom, permaPoint, size, style, and visible.
CosmeticVertex() [3/3]
CosmeticVertex::CosmeticVertex (Base::Vector3d loc)
References TechDraw::Vertex::cosmetic, createNewTag(), TechDraw::LineGroup::getDefaultWidth(), TechDraw::Vertex::hlrVisible, TechDraw::Preferences::lineGroup(), linkGeom, permaPoint, style, TechDraw::Preferences::vertexColor(), TechDraw::Preferences::vertexScale(), and visible.
~CosmeticVertex()
virtual TechDraw::CosmeticVertex::~CosmeticVertex () virtual default
Member Function Documentation
assignTag()
void CosmeticVertex::assignTag (const TechDraw::CosmeticVertex * cv) protected
References Base::Persistence::getTypeId(), and tag.
clone()
CosmeticVertex * CosmeticVertex::clone (void) const
References copy(), and tag.
Referenced by ArchPanel.CommandPanelSheet::Activated(), and TechDraw::CosmeticVertexPy::clone().
copy()
CosmeticVertex * CosmeticVertex::copy (void) const
References CosmeticVertex().
Referenced by clone(), and TechDraw::CosmeticVertexPy::copy().
createNewTag()
void CosmeticVertex::createNewTag () protected
References tag.
Referenced by CosmeticVertex().
dump()
void CosmeticVertex::dump (const char * title) virtual
Reimplemented from TechDraw::Vertex.
References Base::Console(), Base::ConsoleSingleton::Message(), and toString().
getMemSize()
unsigned int CosmeticVertex::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
getPyObject()
PyObject * CosmeticVertex::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
References PythonObject.
Referenced by TechDraw::DrawViewPartPy::getCosmeticVertex(), and TechDraw::DrawViewPartPy::getCosmeticVertexBySelection().
getTag()
boost::uuids::uuid CosmeticVertex::getTag (void) const
References tag.
Referenced by getTagAsString().
getTagAsString()
std::string CosmeticVertex::getTagAsString (void) const virtual
Reimplemented from TechDraw::Vertex.
References getTag().
Referenced by TechDraw::DrawViewPart::add1CVToGV(), TechDraw::CosmeticExtension::addCosmeticVertex(), TechDraw::GeometryObject::addCosmeticVertex(), TechDraw::CosmeticExtension::getCosmeticVertex(), TechDraw::DrawViewPartPy::removeCosmeticVertex(), Save(), and toString().
move()
void CosmeticVertex::move (Base::Vector3d newPos)
References permaPoint.
moveRelative()
void CosmeticVertex::moveRelative (Base::Vector3d movement)
References permaPoint.
Restore()
void CosmeticVertex::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References Base::XMLReader::getAttribute(), Base::XMLReader::getAttributeAsFloat(), Base::XMLReader::getAttributeAsInteger(), linkGeom, permaPoint, Base::XMLReader::readElement(), TechDraw::Vertex::Restore(), restoreCosmetic(), style, tag, visible, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by TechDraw::PropertyCosmeticVertexList::Restore().
restoreCosmetic()
bool CosmeticVertex::restoreCosmetic (void) static
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by Restore(), TechDraw::CosmeticEdge::Restore(), TechDraw::CenterLine::Restore(), and TechDraw::GeomFormat::Restore().
Save()
void CosmeticVertex::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References getTagAsString(), Base::Writer::ind(), linkGeom, permaPoint, TechDraw::Vertex::Save(), Base::Writer::Stream(), style, visible, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
scaled()
Base::Vector3d CosmeticVertex::scaled (double factor)
References permaPoint, and TechDraw::Vertex::pnt.
Referenced by TechDraw::DrawViewPart::add1CVToGV(), and TechDraw::GeometryObject::addCosmeticVertex().
toString()
std::string CosmeticVertex::toString (void) const
References getTagAsString(), linkGeom, permaPoint, TechDraw::Vertex::point(), style, visible, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by dump().
Member Data Documentation
color
App::Color TechDraw::CosmeticVertex::color
Referenced by ArchSite.Compass::buildCoordinates(), CosmeticVertex(), TechDrawGui::QGIViewPart::drawViewPart(), TechDraw::CosmeticVertexPy::getColor(), FeaturePython.ViewProviderOctahedron::onChanged(), Mod.Test.unittestgui.ProgressBar::paint(), and TechDraw::CosmeticVertexPy::setColor().
linkGeom
int TechDraw::CosmeticVertex::linkGeom
Referenced by TechDraw::DrawViewPart::add1CVToGV(), CosmeticVertex(), Restore(), Save(), and toString().
permaPoint
Base::Vector3d TechDraw::CosmeticVertex::permaPoint
Referenced by CosmeticVertex(), TechDraw::DrawViewDimExtent::execute(), TechDraw::CosmeticVertexPy::getPoint(), move(), moveRelative(), Restore(), Save(), scaled(), TechDraw::CosmeticVertexPy::setPoint(), and toString().
PythonObject
Py::Object TechDraw::CosmeticVertex::PythonObject protected
Referenced by getPyObject().
size
double TechDraw::CosmeticVertex::size
Referenced by CosmeticVertex(), PathScripts.PostUtils.GCodeEditorDialog::done(), TechDrawGui::QGIViewPart::drawViewPart(), TechDraw::CosmeticVertexPy::getSize(), and TechDraw::CosmeticVertexPy::setSize().
style
int TechDraw::CosmeticVertex::style
Referenced by CosmeticVertex(), TechDraw::CosmeticVertexPy::getStyle(), Restore(), Save(), TechDraw::CosmeticVertexPy::setStyle(), and toString().
tag
boost::uuids::uuid TechDraw::CosmeticVertex::tag protected
Referenced by assignTag(), clone(), createNewTag(), Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.ChunkBase::dump_header(), getTag(), and Restore().
visible
bool TechDraw::CosmeticVertex::visible
Referenced by CosmeticVertex(), TechDraw::CosmeticVertexPy::getShow(), Restore(), Save(), TechDraw::CosmeticVertexPy::setShow(), and toString().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/App/Cosmetic.h
Sources/FreeCAD/src/Mod/TechDraw/App/Cosmetic.cpp