FreeCAD: PathTests.TestPathHelixGenerator.TestPathHelixGenerator Class Reference
PathTests.TestPathHelixGenerator.TestPathHelixGenerator Class Reference
Public Member Functions
def test00 (self)
def test01 (self)
def test07 (self)
def test08 (self)
def test09 (self)
def test10 (self)
Public Member Functions inherited from PathTests.PathTestUtils.PathTestBase
def assertArc (self, edge, pt1, pt2, direction="CW")
def assertCircle (self, edge, pt, r)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertCommandEqual (self, c1, c2)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertEdgeShapesMatch (self, e1, e2)
def assertEqualLocale (self, s1, s2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertPlacement (self, p1, p2)
def assertPointsMatch (self, pts0, pts1)
def assertRoughly (self, f1, f2, error=0.00001)
Static Public Attributes
string expectedHelixGCode
Member Function Documentation
test00()
def PathTests.TestPathHelixGenerator.TestPathHelixGenerator.test00 (self)
Test Basic Helix Generator Return
References PathTests.TestPathHelixGenerator.TestPathHelixGenerator.expectedHelixGCode.
Referenced by PathTests.TestPathTool.TestPathTool.test01(), PathTests.TestPathToolController.TestPathToolController.test01(), PathTests.TestPathTooltable.TestPathTooltable.test01(), PathTests.TestPathTool.TestPathTool.test02(), and PathTests.TestPathTooltable.TestPathTooltable.test02().
test01()
def PathTests.TestPathHelixGenerator.TestPathHelixGenerator.test01 (self)
Test Value and Type checking
test07()
def PathTests.TestPathHelixGenerator.TestPathHelixGenerator.test07 (self)
Test Basic Helix Generator verify linear edge is vertical
test08()
def PathTests.TestPathHelixGenerator.TestPathHelixGenerator.test08 (self)
Test Helix Generator with horizontal edge
test09()
def PathTests.TestPathHelixGenerator.TestPathHelixGenerator.test09 (self)
Test Helix Generator with inverted vertical edge
test10()
def PathTests.TestPathHelixGenerator.TestPathHelixGenerator.test10 (self)
Test Helix Retraction
Member Data Documentation
expectedHelixGCode
string PathTests.TestPathHelixGenerator.TestPathHelixGenerator.expectedHelixGCode static
Initial value:
=  "G0 X7.500000 Y5.000000\
G1 Z20.000000\
G2 I-2.500000 J0.000000 X2.500000 Y5.000000 Z19.500000\
G2 I2.500000 J0.000000 X7.500000 Y5.000000 Z19.000000\
G2 I-2.500000 J0.000000 X2.500000 Y5.000000 Z18.500000\
G2 I2.500000 J0.000000 X7.500000 Y5.000000 Z18.000000\
G2 I-2.500000 J0.000000 X2.500000 Y5.000000 Z18.000000\
G2 I2.500000 J0.000000 X7.500000 Y5.000000 Z18.000000\
G0 X5.000000 Y5.000000 Z18.000000\
G0 Z20.000000G0 X10.000000 Y5.000000\
G1 Z20.000000\
G2 I-5.000000 J0.000000 X0.000000 Y5.000000 Z19.500000\
G2 I5.000000 J0.000000 X10.000000 Y5.000000 Z19.000000\
G2 I-5.000000 J0.000000 X0.000000 Y5.000000 Z18.500000\
G2 I5.000000 J0.000000 X10.000000 Y5.000000 Z18.000000\
G2 I-5.000000 J0.000000 X0.000000 Y5.000000 Z18.000000\
G2 I5.000000 J0.000000 X10.000000 Y5.000000 Z18.000000\
G0 X5.000000 Y5.000000 Z18.000000\
G0 Z20.000000G0 X12.500000 Y5.000000\
G1 Z20.000000\
G2 I-7.500000 J0.000000 X-2.500000 Y5.000000 Z19.500000\
G2 I7.500000 J0.000000 X12.500000 Y5.000000 Z19.000000\
G2 I-7.500000 J0.000000 X-2.500000 Y5.000000 Z18.500000\
G2 I7.500000 J0.000000 X12.500000 Y5.000000 Z18.000000\
G2 I-7.500000 J0.000000 X-2.500000 Y5.000000 Z18.000000\
G2 I7.500000 J0.000000 X12.500000 Y5.000000 Z18.000000\
G0 X5.000000 Y5.000000 Z18.000000G0 Z20.000000"
Referenced by PathTests.TestPathHelixGenerator.TestPathHelixGenerator.test00().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Path/PathTests/TestPathHelixGenerator.py