FreeCAD: FemGui::PlaneWidget Class Reference
FemGui::PlaneWidget Class Reference
#include <ViewProviderFemPostFunction.h>
Public Member Functions
virtual void applyPythonCode ()
virtual void onChange (const App::Property &p)
PlaneWidget ()
virtual void setViewProvider (ViewProviderFemPostFunction *view)
virtual ~PlaneWidget ()
Public Member Functions inherited from FemGui::FunctionWidget
virtual void applyPythonCode ()=0
FunctionWidget ()
void onObjectsChanged (const App::DocumentObject &obj, const App::Property &)
virtual void setViewProvider (ViewProviderFemPostFunction *view)
virtual ~FunctionWidget ()
Additional Inherited Members
Protected Member Functions inherited from FemGui::FunctionWidget
bool blockObjectUpdates ()
Fem::FemPostFunction * getObject ()
ViewProviderFemPostFunction * getView ()
virtual void onChange (const App::Property &p)=0
void setBlockObjectUpdates (bool val)
Constructor & Destructor Documentation
PlaneWidget()
PlaneWidget::PlaneWidget ()
References draftgeoutils.intersections::connect(), Base::UnitsApi::getDecimals(), Ui_PlaneWidget::normalX, Ui_PlaneWidget::normalY, Ui_PlaneWidget::normalZ, Ui_PlaneWidget::originX, Ui_PlaneWidget::originY, Ui_PlaneWidget::originZ, Gui::QuantitySpinBox::setDecimals(), Ui_PlaneWidget::setupUi(), and Gui::QuantitySpinBox::sizeForText().
~PlaneWidget()
PlaneWidget::~PlaneWidget () virtual
Member Function Documentation
applyPythonCode()
void PlaneWidget::applyPythonCode () virtual
Implements FemGui::FunctionWidget.
onChange()
void PlaneWidget::onChange (const App::Property & p) virtual
Implements FemGui::FunctionWidget.
References Ui_PlaneWidget::normalX, Ui_PlaneWidget::normalY, Ui_PlaneWidget::normalZ, Ui_PlaneWidget::originX, Ui_PlaneWidget::originY, Ui_PlaneWidget::originZ, FemGui::FunctionWidget::setBlockObjectUpdates(), Gui::QuantitySpinBox::setValue(), and draftgeoutils.general::vec().
Referenced by setViewProvider().
setViewProvider()
void PlaneWidget::setViewProvider (ViewProviderFemPostFunction * view) virtual
Reimplemented from FemGui::FunctionWidget.
References FemGui::FunctionWidget::getObject(), onChange(), Ui_PlaneWidget::originX, Ui_PlaneWidget::originY, Ui_PlaneWidget::originZ, FemGui::FunctionWidget::setBlockObjectUpdates(), Gui::QuantitySpinBox::setUnit(), and FemGui::FunctionWidget::setViewProvider().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/ViewProviderFemPostFunction.h
FreeCAD/src/Mod/Fem/Gui/ViewProviderFemPostFunction.cpp