FreeCAD: Gui::SelectModule Class Reference
Gui::SelectModule Class Reference
The SelectModule class provides a list of radio buttons to choose the module that should handle a certain file type.
#include <FileDialog.h>
Public Types
typedef QMap< QString, QString > Dict
Public Member Functions
QString getModule () const
SelectModule (const QString &type, const Dict &, QWidget *parent)
virtual ~SelectModule ()
Import/Export handler
These methods accepts a file name or a list of file names and return a map of file names with the associated Python module that should open the file.
void accept ()
void reject ()
static Dict exportHandler (const QString &fn, const QString &filter=QString())
static Dict exportHandler (const QStringList &fn, const QString &filter=QString())
static Dict importHandler (const QString &fn, const QString &filter=QString())
static Dict importHandler (const QStringList &fn, const QString &filter=QString())
Detailed Description
The SelectModule class provides a list of radio buttons to choose the module that should handle a certain file type.
Author
Werner Mayer
Member Typedef Documentation
Dict
typedef QMap<QString, QString> Gui::SelectModule::Dict
Constructor & Destructor Documentation
SelectModule()
SelectModule::SelectModule (const QString & type, const Dict & types, QWidget * parent)
References accept(), and draftgeoutils.intersections::connect().
~SelectModule()
SelectModule::~SelectModule () virtual
Member Function Documentation
accept()
void SelectModule::accept (void)
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), SelectModule(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
exportHandler() [1/2]
SelectModule::Dict SelectModule::exportHandler (const QString & fn, const QString & filter = QString()) static
References exportHandler().
Referenced by exportHandler().
exportHandler() [2/2]
SelectModule::Dict SelectModule::exportHandler (const QStringList & fn, const QString & filter = QString()) static
References App::GetApplication(), App::Application::getExportFilters(), Gui::getMainWindow(), and getModule().
getModule()
QString SelectModule::getModule () const
Referenced by exportHandler(), and importHandler().
importHandler() [1/2]
SelectModule::Dict SelectModule::importHandler (const QString & fn, const QString & filter = QString()) static
References importHandler().
Referenced by Gui::RecentFilesAction::activateFile(), importHandler(), and Gui::MainWindow::loadUrls().
importHandler() [2/2]
SelectModule::Dict SelectModule::importHandler (const QStringList & fn, const QString & filter = QString()) static
References App::GetApplication(), App::Application::getImportFilters(), Gui::getMainWindow(), and getModule().
reject()
void SelectModule::reject (void)
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/FileDialog.h
FreeCAD/src/Gui/FileDialog.cpp