FreeCAD: TechDraw::DashSpec Class Reference
TechDraw::DashSpec Class Reference
#include <HatchLine.h>
Public Member Functions
DashSpec ()
DashSpec (std::vector< double > p)
void dump (const char *title)
bool empty (void)
double get (int i)
std::vector< double > get (void)
double length (void)
DashSpec reversed (void)
int size (void)
~DashSpec ()
Constructor & Destructor Documentation
DashSpec() [1/2]
TechDraw::DashSpec::DashSpec ()
DashSpec() [2/2]
TechDraw::DashSpec::DashSpec (std::vector< double > p)
~DashSpec()
TechDraw::DashSpec::~DashSpec ()
Member Function Documentation
dump()
void DashSpec::dump (const char * title)
References Base::Console(), and Base::ConsoleSingleton::Message().
Referenced by TechDraw::PATLineSpec::dump().
empty()
bool TechDraw::DashSpec::empty (void)
Referenced by TechDraw::PATLineSpec::isDashed().
get() [1/2]
double TechDraw::DashSpec::get (int i)
Referenced by TechDrawGui::QGIFace::decodeDashSpec(), and draftguitools.gui_trackers.editTracker::move().
get() [2/2]
std::vector< double > TechDraw::DashSpec::get (void)
Referenced by length(), draftguitools.gui_trackers.editTracker::move(), and reversed().
length()
double DashSpec::length (void)
References get().
Referenced by PathScripts.PathStock.StockFromBase::execute(), PathScripts.PathDressupDogbone.ObjectDressup::execute(), TechDrawGui::QGIFace::geomToStubbyLine(), PathScripts.PathFeatureExtensions.Extension::getSubLink(), PathScripts.PathFeatureExtensions.Extension::getWire(), and Mod.PartDesign.Scripts.FilletArc.Vector::norm().
reversed()
DashSpec DashSpec::reversed (void)
References get().
Referenced by TechDrawGui::QGIFace::lineSetToFillItems().
size()
int TechDraw::DashSpec::size (void)
Referenced by gzip_utf8.GzipFile::close(), PathScripts.PostUtils.GCodeEditorDialog::done(), and gzip_utf8.GzipFile::write().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/App/HatchLine.h
FreeCAD/src/Mod/TechDraw/App/HatchLine.cpp