FreeCAD: PartDesignGui::TaskDlgDatumParameters Class Reference
PartDesignGui::TaskDlgDatumParameters Class Reference
simulation dialog for the TaskView
#include <TaskDatumParameters.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgDatumParameters (ViewProviderDatum *DatumView)
~TaskDlgDatumParameters ()
Public Member Functions inherited from PartGui::TaskDlgAttacher
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void clicked (int)
is called by the framework if an button is clicked which has no accept or reject role
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
returns for Close and Help button
Gui::ViewProviderDocumentObject * getViewProvider () const
virtual bool isAllowedAlterDocument (void) const
is called by the framework if the user presses the help button
virtual void open ()
is called the TaskView when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgAttacher (Gui::ViewProviderDocumentObject *ViewProvider, bool createBox=true)
~TaskDlgAttacher ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
tells the framework which buttons are wished for the dialog
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from PartGui::TaskDlgAttacher
TaskAttacher * parameter
Gui::ViewProviderDocumentObject * ViewProvider
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
simulation dialog for the TaskView
Constructor & Destructor Documentation
TaskDlgDatumParameters()
TaskDlgDatumParameters::TaskDlgDatumParameters (ViewProviderDatum * DatumView)
References Gui::TaskView::TaskDialog::Content, and PartGui::TaskDlgAttacher::parameter.
~TaskDlgDatumParameters()
TaskDlgDatumParameters::~TaskDlgDatumParameters ()
Member Function Documentation
accept()
bool TaskDlgDatumParameters::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from PartGui::TaskDlgAttacher.
References PartGui::TaskDlgAttacher::accept(), PartGui::TaskAttacher::getActiveMapMode(), PartDesignGui::getBodyFor(), Gui::getMainWindow(), Gui::ViewProviderDocumentObject::getObject(), PartDesignGui::getPartFor(), App::PropertyLinkSubList::getSubValues(), App::PropertyLinkSubList::getValues(), PartDesignGui::TaskFeaturePick::makeCopy(), Attacher::mmDeactivated, PartGui::TaskDlgAttacher::parameter, PartDesignGui::Ui_DlgReference::radioIndependent, PartDesignGui::Ui_DlgReference::radioXRef, PartDesignGui::Ui_DlgReference::setupUi(), App::PropertyLinkSubList::setValues(), and Part::AttachExtension::Support.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
reject()
bool TaskDlgDatumParameters::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from PartGui::TaskDlgAttacher.
References PartGui::TaskDlgAttacher::reject().
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/PartDesign/Gui/TaskDatumParameters.h
FreeCAD/src/Mod/PartDesign/Gui/TaskDatumParameters.cpp