FreeCAD: Part::OffsetCurve2dPy Class Reference
Part::OffsetCurve2dPy Class Reference
The python export class for Geom2dOffsetCurve.
#include <OffsetCurve2dPy.h>
Public Types
typedef Geom2dOffsetCurve * PointerType
Public Types inherited from Part::Curve2dPy
typedef Geom2dCurve * PointerType
Public Types inherited from Part::Geometry2dPy
typedef Geometry2d * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
OffsetCurve2dPy (Geom2dOffsetCurve *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Part::Curve2dPy
Curve2dPy (Geom2dCurve *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * reverse (PyObject *args)
implementer for the reverse() method
PyObject * toShape (PyObject *args)
implementer for the toShape() method
PyObject * discretize (PyObject *args, PyObject *kwd)
implementer for the discretize() method
PyObject * length (PyObject *args)
implementer for the length() method
PyObject * parameterAtDistance (PyObject *args)
implementer for the parameterAtDistance() method
PyObject * value (PyObject *args)
implementer for the value() method
PyObject * tangent (PyObject *args)
implementer for the tangent() method
PyObject * parameter (PyObject *args)
implementer for the parameter() method
PyObject * normal (PyObject *args)
implementer for the normal() method
PyObject * curvature (PyObject *args)
implementer for the curvature() method
PyObject * centerOfCurvature (PyObject *args)
implementer for the centerOfCurvature() method
PyObject * intersectCC (PyObject *args)
implementer for the intersectCC() method
PyObject * toBSpline (PyObject *args)
implementer for the toBSpline() method
PyObject * approximateBSpline (PyObject *args)
implementer for the approximateBSpline() method
Py::String getContinuity (void) const
getter for the Continuity attribute
Py::Boolean getClosed (void) const
getter for the Closed attribute
Py::Boolean getPeriodic (void) const
getter for the Periodic attribute
Py::Float getFirstParameter (void) const
getter for the FirstParameter attribute
Py::Float getLastParameter (void) const
getter for the LastParameter attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geom2dCurve * getGeom2dCurvePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Part::Geometry2dPy
Geometry2dPy (Geometry2d *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geometry2d * getGeometry2dPtr (void) const
getter for the object handled by this class
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * copy (PyObject *args)
implementer for the copy() method
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::Curve2dPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_reverse (PyObject *self, PyObject *args)
callback for the reverse() method
static PyObject * staticCallback_toShape (PyObject *self, PyObject *args)
callback for the toShape() method
static PyObject * staticCallback_discretize (PyObject *self, PyObject *args, PyObject *kwd)
callback for the discretize() method
static PyObject * staticCallback_length (PyObject *self, PyObject *args)
callback for the length() method
static PyObject * staticCallback_parameterAtDistance (PyObject *self, PyObject *args)
callback for the parameterAtDistance() method
static PyObject * staticCallback_value (PyObject *self, PyObject *args)
callback for the value() method
static PyObject * staticCallback_tangent (PyObject *self, PyObject *args)
callback for the tangent() method
static PyObject * staticCallback_parameter (PyObject *self, PyObject *args)
callback for the parameter() method
static PyObject * staticCallback_normal (PyObject *self, PyObject *args)
callback for the normal() method
static PyObject * staticCallback_curvature (PyObject *self, PyObject *args)
callback for the curvature() method
static PyObject * staticCallback_centerOfCurvature (PyObject *self, PyObject *args)
callback for the centerOfCurvature() method
static PyObject * staticCallback_intersectCC (PyObject *self, PyObject *args)
callback for the intersectCC() method
static PyObject * staticCallback_toBSpline (PyObject *self, PyObject *args)
callback for the toBSpline() method
static PyObject * staticCallback_approximateBSpline (PyObject *self, PyObject *args)
callback for the approximateBSpline() method
static PyObject * staticCallback_getContinuity (PyObject *self, void *closure)
getter callback for the Continuity attribute
static int staticCallback_setContinuity (PyObject *self, PyObject *value, void *closure)
setter callback for the Continuity attribute
static PyObject * staticCallback_getClosed (PyObject *self, void *closure)
getter callback for the Closed attribute
static int staticCallback_setClosed (PyObject *self, PyObject *value, void *closure)
setter callback for the Closed attribute
static PyObject * staticCallback_getPeriodic (PyObject *self, void *closure)
getter callback for the Periodic attribute
static int staticCallback_setPeriodic (PyObject *self, PyObject *value, void *closure)
setter callback for the Periodic attribute
static PyObject * staticCallback_getFirstParameter (PyObject *self, void *closure)
getter callback for the FirstParameter attribute
static int staticCallback_setFirstParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the FirstParameter attribute
static PyObject * staticCallback_getLastParameter (PyObject *self, void *closure)
getter callback for the LastParameter attribute
static int staticCallback_setLastParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the LastParameter attribute
Static Public Member Functions inherited from Part::Geometry2dPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of OffsetCurve2dPy.
static PyMethodDef Methods []
Methods structure of OffsetCurve2dPy.
static PyTypeObject Type
Type structure of OffsetCurve2dPy.
Static Public Attributes inherited from Part::Curve2dPy
static PyGetSetDef GetterSetter []
Attribute structure of Curve2dPy.
static PyMethodDef Methods []
Methods structure of Curve2dPy.
static PyTypeObject Type
Type structure of Curve2dPy.
Static Public Attributes inherited from Part::Geometry2dPy
static PyGetSetDef GetterSetter []
Attribute structure of Geometry2dPy.
static PyMethodDef Methods []
Methods structure of Geometry2dPy.
static PyTypeObject Type
Type structure of Geometry2dPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~OffsetCurve2dPy ()
Protected Member Functions inherited from Part::Curve2dPy
~Curve2dPy ()
Protected Member Functions inherited from Part::Geometry2dPy
~Geometry2dPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object attributes
Py::Float getOffsetValue (void) const
getter for the OffsetValue attribute
void setOffsetValue (Py::Float arg)
setter for the OffsetValue attribute
Py::Object getBasisCurve (void) const
getter for the BasisCurve attribute
void setBasisCurve (Py::Object arg)
setter for the BasisCurve attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geom2dOffsetCurve * getGeom2dOffsetCurvePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getOffsetValue (PyObject *self, void *closure)
getter callback for the OffsetValue attribute
static int staticCallback_setOffsetValue (PyObject *self, PyObject *value, void *closure)
setter callback for the OffsetValue attribute
static PyObject * staticCallback_getBasisCurve (PyObject *self, void *closure)
getter callback for the BasisCurve attribute
static int staticCallback_setBasisCurve (PyObject *self, PyObject *value, void *closure)
setter callback for the BasisCurve attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Geom2dOffsetCurve.
Member Typedef Documentation
PointerType
typedef Geom2dOffsetCurve* Part::OffsetCurve2dPy::PointerType
Constructor & Destructor Documentation
~OffsetCurve2dPy()
OffsetCurve2dPy::~OffsetCurve2dPy () protected
OffsetCurve2dPy()
OffsetCurve2dPy::OffsetCurve2dPy (Geom2dOffsetCurve * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getBasisCurve()
Py::Object OffsetCurve2dPy::getBasisCurve (void) const
getter for the BasisCurve attribute
References Part::Geometry2dPy::getGeometry2dPtr(), Base::BaseClass::getPyObject(), and Part::makeFromCurve2d().
Referenced by staticCallback_getBasisCurve().
getCustomAttributes()
PyObject * OffsetCurve2dPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getGeom2dOffsetCurvePtr()
Geom2dOffsetCurve * OffsetCurve2dPy::getGeom2dOffsetCurvePtr (void) const
getter for the object handled by this class
Referenced by PyInit().
getOffsetValue()
Py::Float OffsetCurve2dPy::getOffsetValue (void) const
getter for the OffsetValue attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getOffsetValue().
GetType()
virtual PyTypeObject* Part::OffsetCurve2dPy::GetType (void) virtual
Reimplemented from Part::Curve2dPy.
PyInit()
int OffsetCurve2dPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::Curve2dPy.
References getGeom2dOffsetCurvePtr(), Part::Geometry2dPy::getGeometry2dPtr(), draftfunctions.offset::offset(), Part::PartExceptionOCCError, Part::Geom2dOffsetCurve::setHandle(), and Part::Curve2dPy::Type.
PyMake()
PyObject * OffsetCurve2dPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References OffsetCurve2dPy().
representation()
std::string OffsetCurve2dPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setBasisCurve()
void OffsetCurve2dPy::setBasisCurve (Py::Object arg)
setter for the BasisCurve attribute
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::Curve2dPy::Type.
Referenced by staticCallback_setBasisCurve().
setCustomAttributes()
int OffsetCurve2dPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setOffsetValue()
void OffsetCurve2dPy::setOffsetValue (Py::Float arg)
setter for the OffsetValue attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_setOffsetValue().
staticCallback_getBasisCurve()
PyObject * OffsetCurve2dPy::staticCallback_getBasisCurve (PyObject * self, void * closure) static
getter callback for the BasisCurve attribute
References Base::BaseExceptionFreeCADError, getBasisCurve(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getOffsetValue()
PyObject * OffsetCurve2dPy::staticCallback_getOffsetValue (PyObject * self, void * closure) static
getter callback for the OffsetValue attribute
References Base::BaseExceptionFreeCADError, getOffsetValue(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setBasisCurve()
int OffsetCurve2dPy::staticCallback_setBasisCurve (PyObject * self, PyObject * value, void * closure) static
setter callback for the BasisCurve attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setBasisCurve().
staticCallback_setOffsetValue()
int OffsetCurve2dPy::staticCallback_setOffsetValue (PyObject * self, PyObject * value, void * closure) static
setter callback for the OffsetValue attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setOffsetValue().
Member Data Documentation
GetterSetter
PyGetSetDef OffsetCurve2dPy::GetterSetter static
Initial value:
= {
    {"OffsetValue",
        (getter) staticCallback_getOffsetValue,
        (setter) staticCallback_setOffsetValue,
        "\n                                     Sets or gets the offset value to offset the underlying curve.\n                         ",
        NULL
    },
    {"BasisCurve",
        (getter) staticCallback_getBasisCurve,
        (setter) staticCallback_setBasisCurve,
        "\n                                     Sets or gets the basic curve.\n                         ",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of OffsetCurve2dPy.
Methods
PyMethodDef OffsetCurve2dPy::Methods static
Initial value:
= {
    {NULL, NULL, 0, NULL}
}
Methods structure of OffsetCurve2dPy.
Type
PyTypeObject OffsetCurve2dPy::Type static
Type structure of OffsetCurve2dPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/Geom2d/OffsetCurve2dPy.h
Sources/FreeCAD/src/Mod/Part/App/Geom2d/OffsetCurve2dPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/Geom2d/OffsetCurve2dPy.cpp