FreeCAD: FemGui::TaskDlgFemConstraintTemperature Class Reference
FemGui::TaskDlgFemConstraintTemperature Class Reference
#include <TaskFemConstraintTemperature.h>
Public Member Functions
bool accept ()
is called by the framework if the dialog is accepted (Ok)
void open ()
is called the TaskView when the dialog is opened
bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgFemConstraintTemperature (ViewProviderFemConstraintTemperature *ConstraintView)
Public Member Functions inherited from FemGui::TaskDlgFemConstraint
ViewProviderFemConstraint * getConstraintView () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
returns for Close and Help button
virtual bool isAllowedAlterDocument (void) const
Public Member Functions inherited from Gui::TaskView::TaskDialog
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from FemGui::TaskDlgFemConstraint
ViewProviderFemConstraint * ConstraintView
TaskFemConstraint * parameter
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Constructor & Destructor Documentation
TaskDlgFemConstraintTemperature()
TaskDlgFemConstraintTemperature::TaskDlgFemConstraintTemperature (ViewProviderFemConstraintTemperature * ConstraintView)
References FemGui::TaskDlgFemConstraint::ConstraintView, Gui::TaskView::TaskDialog::Content, and FemGui::TaskDlgFemConstraint::parameter.
Member Function Documentation
accept()
bool TaskDlgFemConstraintTemperature::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from FemGui::TaskDlgFemConstraint.
References FemGui::TaskDlgFemConstraint::accept(), FemGui::TaskDlgFemConstraint::ConstraintView, Gui::Command::Doc, App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), FemGui::TaskFemConstraint::getScale(), and FemGui::TaskDlgFemConstraint::parameter.
Referenced by PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
open()
void TaskDlgFemConstraintTemperature::open () virtual
is called the TaskView when the dialog is opened
Reimplemented from FemGui::TaskDlgFemConstraint.
References FemGui::TaskDlgFemConstraint::ConstraintView, Gui::Command::Doc, FemGui::ViewProviderFemConstraint::gethideMeshShowPartStr(), Gui::ViewProviderDocumentObject::getObject(), Gui::Command::hasPendingCommand(), Gui::Command::openCommand(), and Gui::ViewProvider::setVisible().
reject()
bool TaskDlgFemConstraintTemperature::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from FemGui::TaskDlgFemConstraint.
References Gui::Command::abortCommand(), Gui::Command::Gui, and Gui::Command::updateActive().
Referenced by PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintTemperature.h
Sources/FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintTemperature.cpp