FreeCAD: MeshCore::MeshEvalSelfIntersection Class Reference
MeshCore::MeshEvalSelfIntersection Class Reference
The MeshEvalSelfIntersection class checks the mesh for self intersection.
#include <Evaluation.h>
Public Member Functions
bool Evaluate ()
Evaluate the mesh and return if true if there are self intersections.
void GetIntersections (const std::vector< std::pair< FacetIndex, FacetIndex > > &, std::vector< std::pair< Base::Vector3f, Base::Vector3f > > &) const
collect all intersection lines
void GetIntersections (std::vector< std::pair< FacetIndex, FacetIndex > > &) const
collect the index of all facets with self intersections
MeshEvalSelfIntersection (const MeshKernel &rclB)
virtual ~MeshEvalSelfIntersection ()
Public Member Functions inherited from MeshCore::MeshEvaluation
virtual bool Evaluate ()=0
Evaluates the mesh kernel with respect to certain criteria.
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()
Detailed Description
The MeshEvalSelfIntersection class checks the mesh for self intersection.
Author
Werner Mayer
Constructor & Destructor Documentation
MeshEvalSelfIntersection()
MeshCore::MeshEvalSelfIntersection::MeshEvalSelfIntersection (const MeshKernel & rclB)
~MeshEvalSelfIntersection()
virtual MeshCore::MeshEvalSelfIntersection::~MeshEvalSelfIntersection () virtual
Member Function Documentation
Evaluate()
bool MeshEvalSelfIntersection::Evaluate () virtual
Evaluate the mesh and return if true if there are self intersections.
Implements MeshCore::MeshEvaluation.
References MeshCore::MeshFacetIterator::Begin(), MeshCore::MeshGrid::GetCtGrids(), MeshCore::MeshGridIterator::GetElements(), MeshCore::MeshGridIterator::Init(), MeshCore::MeshGeomFacet::IntersectWithFacet(), MeshCore::MeshGridIterator::More(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshGridIterator::Next(), MeshCore::MeshFacetIterator::Next(), Base::SequencerLauncher::next(), and MeshCore::MeshFacetIterator::Set().
Referenced by MeshCore::MeshKernel::HasSelfIntersections(), Mesh::MeshObject::hasSelfIntersections(), and MeshGui::DlgEvaluateMeshImp::on_repairAllTogether_clicked().
GetIntersections() [1/2]
void MeshEvalSelfIntersection::GetIntersections (const std::vector< std::pair< FacetIndex, FacetIndex > > & indices, std::vector< std::pair< Base::Vector3f, Base::Vector3f > > & intersection) const
collect all intersection lines
References MeshCore::MeshGeomFacet::GetBoundBox(), MeshCore::MeshGeomFacet::IntersectWithFacet(), and MeshCore::MeshFacetIterator::Set().
Referenced by Mesh::MeshObject::offsetSpecial2(), MeshPart::MeshAlgos::offsetSpecial2(), MeshGui::DlgEvaluateMeshImp::on_analyzeSelfIntersectionButton_clicked(), Mesh::MeshObject::removeSelfIntersections(), and MeshGui::ViewProviderMeshSelfIntersections::showDefects().
GetIntersections() [2/2]
void MeshEvalSelfIntersection::GetIntersections (std::vector< std::pair< FacetIndex, FacetIndex > > & intersection) const
collect the index of all facets with self intersections
References MeshCore::MeshFacetIterator::Begin(), MeshCore::MeshGrid::GetCtGrids(), MeshCore::MeshGridIterator::GetElements(), MeshCore::MeshGridIterator::Init(), MeshCore::MeshGeomFacet::IntersectWithFacet(), MeshCore::MeshGridIterator::More(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshGridIterator::Next(), MeshCore::MeshFacetIterator::Next(), Base::SequencerLauncher::next(), and MeshCore::MeshFacetIterator::Set().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/Core/Evaluation.h
FreeCAD/src/Mod/Mesh/App/Core/Evaluation.cpp