FreeCAD: Gui::Dialog::DlgProjectInformationImp Class Reference
Gui::Dialog::DlgProjectInformationImp Class Reference
#include <DlgProjectInformationImp.h>
Public Member Functions
void accept ()
Applies the changes to the project information of the given document.
DlgProjectInformationImp (App::Document *doc, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
Constructs a Gui::Dialog::DlgProjectInformationImp as a child of 'parent', with the name 'name' and widget flags set to 'fl'.
~DlgProjectInformationImp ()
Destroys the object and frees any allocated resources.
Constructor & Destructor Documentation
DlgProjectInformationImp()
DlgProjectInformationImp::DlgProjectInformationImp (App::Document * doc, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Constructs a Gui::Dialog::DlgProjectInformationImp as a child of 'parent', with the name 'name' and widget flags set to 'fl'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
References Gui::Dialog::Ui_DlgProjectInformation::comboLicense, draftgeoutils.intersections::connect(), Gui::Dialog::Ui_DlgProjectInformation::lineEditCompany, Gui::Dialog::Ui_DlgProjectInformation::lineEditCreator, Gui::Dialog::Ui_DlgProjectInformation::lineEditDate, Gui::Dialog::Ui_DlgProjectInformation::lineEditLastMod, Gui::Dialog::Ui_DlgProjectInformation::lineEditLastModDate, Gui::Dialog::Ui_DlgProjectInformation::lineEditLicenseURL, Gui::Dialog::Ui_DlgProjectInformation::lineEditName, Gui::Dialog::Ui_DlgProjectInformation::lineEditPath, Gui::Dialog::Ui_DlgProjectInformation::lineEditProgramVersion, Gui::Dialog::Ui_DlgProjectInformation::lineEditUuid, Gui::Dialog::Ui_DlgProjectInformation::pushButtonOpenURL, Gui::Dialog::Ui_DlgProjectInformation::setupUi(), Gui::Dialog::Ui_DlgProjectInformation::textEditComment, and draftguitools.gui_setstyle::translate.
~DlgProjectInformationImp()
DlgProjectInformationImp::~DlgProjectInformationImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
accept()
void DlgProjectInformationImp::accept ()
Applies the changes to the project information of the given document.
References Gui::Dialog::Ui_DlgProjectInformation::comboLicense, Gui::Dialog::Ui_DlgProjectInformation::lineEditCompany, Gui::Dialog::Ui_DlgProjectInformation::lineEditCreator, Gui::Dialog::Ui_DlgProjectInformation::lineEditLicenseURL, and Gui::Dialog::Ui_DlgProjectInformation::textEditComment.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgProjectInformationImp.h
FreeCAD/src/Gui/DlgProjectInformationImp.cpp