FreeCAD: CmdSketcherConstrainEqual Class Reference
CmdSketcherConstrainEqual Class Reference
Public Member Functions
virtual const char * className () const
The C++ class name is needed as context for the translation framework.
CmdSketcherConstrainEqual ()
virtual ~CmdSketcherConstrainEqual ()
Public Member Functions inherited from CmdSketcherConstraint
CmdSketcherConstraint (const char *name)
virtual ~CmdSketcherConstraint ()
Public Member Functions inherited from Gui::Command
const char * beginCmdHelp (void)
returns the begin of a online help page
const char * endCmdHelp (void)
returns the end of a online help page
virtual const char * getHelpUrl (void) const
Get the help URL.
bool hasActiveDocument (void) const
true when there is a document
bool hasObject (const char *Name)
true when there is a document and a Feature with Name
const char * getAppModuleName (void) const
returns the name to which the command belongs
void setAppModuleName (const char *)
const char * getName () const
Get the command name.
const char * getGroupName () const
Get the name of the grouping of the command.
void setGroupName (const char *)
void testActive (void)
Get somtile called to check the state of the command.
void setEnabled (bool)
Enables or disables the command.
TriggerSource triggerSource () const
Return the current command trigger source.
void invoke (int index, TriggerSource trigger=TriggerNone)
Called to invoke the command.
void addTo (QWidget *)
adds this command to arbitrary widgets
void addToGroup (ActionGroup *, bool checkable)
void addToGroup (ActionGroup *)
void adjustCameraPosition ()
Gui::Document * getActiveGuiDocument (void) const
Get pointer to the active gui document.
App::Document * getDocument (const char *Name=0) const
Get pointer to the named or active App document Returns a pointer to the named document or the active document when no name is given.
bool isViewOfType (Base::Type t) const
checks if the active view is of a special type or derived
App::DocumentObject * getObject (const char *Name) const
returns the named feature or the active one from the active document or NULL
std::string getUniqueObjectName (const char *BaseName, const App::DocumentObject *obj=0) const
Get unique Feature name from the active document.
void languageChange ()
Translate command.
void updateAction (int mode)
Updates the QAction with respect to the passed mode.
void setupCheckable (int iMsg)
Setup checkable actions based on current TriggerSource.
const std::string strToPython (const char *Str)
translate a string to a python string literal (needed e.g. in file names for windows...)
const std::string strToPython (const std::string &Str)
Public Member Functions inherited from Gui::CommandBase
Action * getAction () const
Returns the Action object of this command, or 0 if it doesn't exist.
virtual const char * getMenuText () const
virtual const char * getToolTipText () const
virtual const char * getStatusTip () const
virtual const char * getWhatsThis () const
virtual const char * getPixmap () const
virtual const char * getAccel () const
void setWhatsThis (const char *)
void setMenuText (const char *)
void setToolTipText (const char *)
void setStatusTip (const char *)
void setPixmap (const char *)
void setAccel (const char *)
Protected Member Functions
virtual void activated (int iMsg)
Methods which gets called when activated, needs to be reimplemented!
virtual void applyConstraint (std::vector< SelIdPair > &selSeq, int seqIndex)
Protected Member Functions inherited from CmdSketcherConstraint
virtual bool isActive (void)
Override this method if your Cmd is not always active.
Protected Member Functions inherited from Gui::Command
Command (const char *name)
virtual ~Command ()
virtual Action * createAction (void)
Creates the used Action.
void applyCommandData (const char *context, Action *)
Applies the menu text, tool and status tip to the passed action object.
const char * keySequenceToAccel (int) const
Protected Member Functions inherited from Gui::CommandBase
CommandBase (const char *sMenu, const char *sToolTip=0, const char *sWhat=0, const char *sStatus=0, const char *sPixmap=0, const char *sAccel=0)
virtual ~CommandBase ()
Additional Inherited Members
Public Types inherited from Gui::Command
enum TriggerSource { TriggerNone , TriggerAction , TriggerChildAction }
Command trigger source.
enum DoCmd_Type { Doc , App , Gui }
types of application level actions for DoCommand()
Static Public Member Functions inherited from Gui::Command
static void blockCommand (bool)
Blocks all command objects.
static void printPyCaller ()
Print to Python console the current Python calling source file and line number.
static void printCaller (const char *file, int line)
Print to Python console the current calling source file and line number.
static void addModule (DoCmd_Type eType, const char *sModuleName)
import an external (or own) module only once
static Application * getGuiApplication (void)
Get pointer to the Application Window.
static Gui::SelectionSingleton & getSelection (void)
Get a reference to the selection.
static std::string getObjectCmd (const char *Name, const App::Document *doc=0, const char *prefix=0, const char *postfix=0, bool gui=false)
returns a python command string to retrieve an object from a document
static std::string getObjectCmd (const App::DocumentObject *obj, const char *prefix=0, const char *postfix=0, bool gui=false)
returns a python command string to retrieve the given object
static void openCommand (const char *sName=0)
Open a new Undo transaction on the active document.
static void commitCommand (void)
Commit the Undo transaction on the active document.
static void abortCommand (void)
Abort the Undo transaction on the active document.
static bool hasPendingCommand (void)
Check if an Undo transaction is open on the active document.
static void updateActive (void)
Updates the (active) document (propagate changes)
static void updateAll (std::list< Gui::Document * > cList)
Updates the (all or listed) documents (propagate changes)
static bool isActiveObjectValid (void)
Checks if the active object of the active document is valid.
static std::string getPythonTuple (const std::string &name, const std::vector< std::string > &subnames)
Get Python tuple from object and sub-elements.
Protected Types inherited from Gui::Command
enum CmdType {
AlterDoc = 1 , Alter3DView = 2 , AlterSelection = 4 , ForEdit = 8 ,
NoTransaction = 16
}
Protected Attributes inherited from CmdSketcherConstraint
std::vector< std::vector< SketcherGui::SelType > > allowedSelSequences
allowedSelSequences Each element is a vector representing sequence of selections allowable.
Protected Attributes inherited from Gui::Command
const char * sAppModule
const char * sGroup
const char * sName
const char * sHelpUrl
int eType
bool bCanLog
Indicate if the command shall log to MacroManager.
Protected Attributes inherited from Gui::CommandBase
const char * sMenuText
const char * sToolTipText
const char * sWhatsThis
const char * sStatusTip
const char * sPixmap
const char * sAccel
std::string displayText
Constructor & Destructor Documentation
CmdSketcherConstrainEqual()
CmdSketcherConstrainEqual::CmdSketcherConstrainEqual ()
References CmdSketcherConstraint::allowedSelSequences, Gui::Command::eType, Gui::Command::ForEdit, Gui::CommandBase::sAccel, Gui::Command::sAppModule, SketcherGui::SelEdge, SketcherGui::SelExternalEdge, Gui::Command::sGroup, Gui::CommandBase::sMenuText, Gui::CommandBase::sPixmap, Gui::CommandBase::sStatusTip, Gui::CommandBase::sToolTipText, and Gui::CommandBase::sWhatsThis.
~CmdSketcherConstrainEqual()
virtual CmdSketcherConstrainEqual::~CmdSketcherConstrainEqual () virtual
Member Function Documentation
activated()
void CmdSketcherConstrainEqual::activated (int iMsg) protected virtual
Methods which gets called when activated, needs to be reimplemented!
Reimplemented from CmdSketcherConstraint.
References Gui::SelectionSingleton::clearSelection(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), CmdSketcherConstraint::DrawSketchHandlerGenConstraint, Gui::Command::getActiveGuiDocument(), App::GetApplication(), ParameterGrp::GetBool(), Base::Persistence::getClassTypeId(), Sketcher::SketchObject::getGeometry(), SketcherGui::getIdsFromName(), Gui::getMainWindow(), Gui::Command::getObject(), App::Application::GetParameterGroupByPath(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), Base::Persistence::getTypeId(), Sketcher::GeoEnum::HAxis, SketcherGui::isBsplinePole(), SketcherGui::isEdge(), SketcherGui::isPointOrSegmentFixed(), Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, SketcherGui::tryAutoRecompute(), and Sketcher::GeoEnum::VAxis.
applyConstraint()
void CmdSketcherConstrainEqual::applyConstraint (std::vector< SelIdPair > & selSeq, int seqIndex) protected virtual
Reimplemented from CmdSketcherConstraint.
References SketcherGui::areBothPointsOrSegmentsFixed(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Gui::Command::getActiveGuiDocument(), Base::Persistence::getClassTypeId(), Sketcher::SketchObject::getGeometry(), Gui::Document::getInEdit(), Gui::getMainWindow(), SketcherGui::ViewProviderSketch::getSketchObject(), Base::Persistence::getTypeId(), SketcherGui::isBsplinePole(), Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, and SketcherGui::tryAutoRecompute().
className()
virtual const char* CmdSketcherConstrainEqual::className () const virtual
The C++ class name is needed as context for the translation framework.
Reimplemented from CmdSketcherConstraint.
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/Gui/CommandConstraints.cpp