FreeCAD: Instance.Ship Class Reference
Instance.Ship Class Reference
Public Member Functions
def cleanLoadConditions (self, fp)
def cleanTanks (self, fp)
def cleanWeights (self, fp)
def execute (self, fp)
def onChanged (self, fp, prop)
Member Function Documentation
cleanLoadConditions()
def Instance.Ship.cleanLoadConditions (self, fp)
Reanalyse the weights list looking for duplicated objects, or
removed ones.
cleanTanks()
def Instance.Ship.cleanTanks (self, fp)
Reanalyse the weights list looking for duplicated objects, or
removed ones.
cleanWeights()
def Instance.Ship.cleanWeights (self, fp)
Reanalyse the weights list looking for duplicated objects, or
removed ones.
execute()
def Instance.Ship.execute (self, fp)
Detects the entity recomputations.
Keyword arguments:
fp -- Part::FeaturePython object affected.
Referenced by ArchSite.Compass.buildCoordinates(), ArchSchedule.CommandArchSchedule.IsActive(), and FeaturePython.DistanceBolt.onChanged().
onChanged()
def Instance.Ship.onChanged (self, fp, prop)
Detects the ship data changes.
Keyword arguments:
fp -- Part::FeaturePython object affected.
prop -- Modified property name.
Referenced by ArchSite.Compass.buildCoordinates(), and ArchAxis.CommandArchGrid.IsActive().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Ship/Instance.py