FreeCAD: Path Namespace Reference
Path Namespace Reference
Classes
class Area
Base class for FreeCAD wrapping of libarea.
struct AreaParams
Store all Area configurations.
class AreaPy
The python export class for Area.
struct AreaStaticParams
struct CAreaConfig
libarea configurator
struct CAreaParams
Store libarea algorithm configuration.
class Command
The representation of a cnc command in a path.
class CommandPy
The python export class for Command.
class Feature
class FeatureArea
class FeatureAreaPy
The python export class for FeatureArea.
class FeatureAreaView
class FeatureCompound
class FeaturePathCompoundPy
The python export class for FeaturePathCompound.
class FeatureShape
class Module
class PathPy
The python export class for Toolpath.
class PathSegmentVisitor
PathSegmentVisitor is the companion class to PathSegmentWalker.
class PathSegmentWalker
PathSegmentWalker processes a path a splits all movement commands into straight segments and calls the appropriate member of the provided PathSegmentVisitor.
class PropertyPath
The path property class.
class PropertyTool
The tool property class.
class PropertyTooltable
The tooltable property class.
class Tool
The representation of a single tool.
class Toolpath
The representation of a CNC Toolpath.
class ToolPy
The python export class for Tool.
class Tooltable
The representation of a table of tools.
class TooltablePy
The python export class for Tooltable.
class Voronoi
class VoronoiCell
class VoronoiCellPy
The python export class for VoronoiCell.
class VoronoiEdge
class VoronoiEdgePy
The python export class for VoronoiEdge.
class VoronoiPy
The python export class for Voronoi.
class VoronoiVertex
class VoronoiVertexPy
The python export class for VoronoiVertex.
Typedefs
typedef App::FeaturePythonT< FeatureArea > FeatureAreaPython
typedef App::FeaturePythonT< FeatureAreaView > FeatureAreaViewPython
typedef App::FeaturePythonT< FeatureCompound > FeatureCompoundPython
typedef App::FeaturePythonT< Feature > FeaturePython
typedef App::FeaturePythonT< FeatureShape > FeatureShapePython
Functions
Base::Vector3d compensateRotation (const Base::Vector3d &pt, const Base::Rotation &rot, const Base::Vector3d &center)
PyObject * initModule ()
Base::Rotation yawPitchRoll (double a, double b, double c)
Typedef Documentation
FeatureAreaPython
typedef App::FeaturePythonT<FeatureArea> Path::FeatureAreaPython
FeatureAreaViewPython
typedef App::FeaturePythonT<FeatureAreaView> Path::FeatureAreaViewPython
FeatureCompoundPython
typedef App::FeaturePythonT<FeatureCompound> Path::FeatureCompoundPython
FeaturePython
typedef App::FeaturePythonT<Feature> Path::FeaturePython
FeatureShapePython
typedef App::FeaturePythonT<FeatureShape> Path::FeatureShapePython
Function Documentation
compensateRotation()
Base::Vector3d Path::compensateRotation (const Base::Vector3d & pt, const Base::Rotation & rot, const Base::Vector3d & center)
References Base::Rotation::multVec().
Referenced by Path::PathSegmentWalker::walk().
initModule()
PyObject * Path::initModule ()
yawPitchRoll()
Base::Rotation Path::yawPitchRoll (double a, double b, double c)
References Base::Rotation::setYawPitchRoll().
Referenced by Path::PathSegmentWalker::walk().