FreeCAD: SMESH::Controls::Length2D Class Reference
SMESH::Controls::Length2D Class Reference
#include <SMESH_ControlsDef.hxx>
Classes
struct Value
Public Types
typedef std::set< Value > TValues
Public Member Functions
virtual double GetBadRate (double Value, int nbNodes) const
virtual SMDSAbs_ElementType GetType () const
virtual double GetValue (long theElementId)
void GetValues (TValues &theValues)
Public Member Functions inherited from SMESH::Controls::NumericalFunctor
void GetHistogram (int nbIntervals, std::vector< int > &nbEvents, std::vector< double > &funValues, const std::vector< int > &elements, const double *minmax=0, const bool isLogarithmic=false)
Return histogram of functor values.
bool GetPoints (const int theId, TSequenceOfXYZ &theRes) const
long GetPrecision () const
virtual double GetValue (const TSequenceOfXYZ &thePoints)
NumericalFunctor ()
double Round (const double &value)
virtual void SetMesh (const SMDS_Mesh *theMesh)
void SetPrecision (const long thePrecision)
Public Member Functions inherited from SMESH::Controls::Functor
virtual ~Functor ()
Additional Inherited Members
Static Public Member Functions inherited from SMESH::Controls::NumericalFunctor
static bool GetPoints (const SMDS_MeshElement *theElem, TSequenceOfXYZ &theRes)
Protected Attributes inherited from SMESH::Controls::NumericalFunctor
const SMDS_MeshElement * myCurrElement
const SMDS_Mesh * myMesh
long myPrecision
double myPrecisionValue
Member Typedef Documentation
TValues
typedef std::set<Value> SMESH::Controls::Length2D::TValues
Member Function Documentation
GetBadRate()
double Length2D::GetBadRate (double Value, int nbNodes) const virtual
Implements SMESH::Controls::NumericalFunctor.
GetType()
SMDSAbs_ElementType Length2D::GetType () const virtual
Implements SMESH::Controls::NumericalFunctor.
Referenced by SMESH::Controls::CoincidentElements::IsSatisfy().
GetValue()
double Length2D::GetValue (long theElementId) virtual
Reimplemented from SMESH::Controls::NumericalFunctor.
References SMESH::Controls::TSequenceOfXYZ::getElementEntity(), SMESH::Controls::NumericalFunctor::GetPoints(), SMESH::Controls::NumericalFunctor::myPrecision, and SMESH::Controls::TSequenceOfXYZ::size().
GetValues()
void Length2D::GetValues (TValues & theValues)
References SMDS_Mesh::facesIterator(), SMDS_MeshElement::GetID(), SMDS_MeshElement::interlacedNodesElemIterator(), SMDS_MeshElement::IsQuadratic(), SMESH::Controls::NumericalFunctor::myMesh, SMDS_MeshElement::nodesIterator(), SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp