FreeCAD: DocumentObject.ViewProvider Class Reference
DocumentObject.ViewProvider Class Reference
Public Member Functions
def addDisplayMode (self, node, mode)
def addProperty (self, type, name='', group='', doc='', attr=0, readonly=False, hidden=False)
def Annotation (self)
def Content (self)
def DisplayModes (self)
def getAllDerivedFrom (self)
def getDocumentationOfProperty (self, attr)
def getGroupOfProperty (self, attr)
def getProperty (self, attr)
def getTypeOfProperty (self, attr)
def hide (self)
def isDerivedFrom (self, obj)
def isVisible (self)
def MemSize (self)
def Module (self)
def Object (self)
def PropertiesList (self)
def RootNode (self)
def setTransformation (self, trsf)
def show (self)
def supportedProperties (self)
def toString (self)
def Type (self)
def update (self)
Detailed Description
The ViewProvider is the counterpart of the DocumentObject in
the GUI space. It is only present when FreeCAD runs in GUI mode.
It contains all that is needed to represent the DocumentObject in
the 3D view and the FreeCAD interface
Member Function Documentation
addDisplayMode()
def DocumentObject.ViewProvider.addDisplayMode (self, node, mode)
References DocumentObject.ViewProvider.__vobject__.
addProperty()
def DocumentObject.ViewProvider.addProperty (self, type, name = '', group = '', doc = '', attr = 0, readonly = False, hidden = False)
References DocumentObject.ViewProvider.__vobject__.
Annotation()
def DocumentObject.ViewProvider.Annotation (self)
References DocumentObject.ViewProvider.__vobject__.
Content()
def DocumentObject.ViewProvider.Content (self)
shows the contents of the properties of this object as an xml string.
This is the content that is saved when the file is saved by FreeCAD
References DocumentObject.ViewProvider.__vobject__.
DisplayModes()
def DocumentObject.ViewProvider.DisplayModes (self)
References DocumentObject.ViewProvider.__vobject__.
getAllDerivedFrom()
def DocumentObject.ViewProvider.getAllDerivedFrom (self)
References DocumentObject.ViewProvider.__vobject__.
getDocumentationOfProperty()
def DocumentObject.ViewProvider.getDocumentationOfProperty (self, attr)
References DocumentObject.ViewProvider.__vobject__.
getGroupOfProperty()
def DocumentObject.ViewProvider.getGroupOfProperty (self, attr)
References DocumentObject.ViewProvider.__vobject__.
getProperty()
def DocumentObject.ViewProvider.getProperty (self, attr)
References DocumentObject.ViewProvider.__vobject__.
getTypeOfProperty()
def DocumentObject.ViewProvider.getTypeOfProperty (self, attr)
References DocumentObject.ViewProvider.__vobject__.
hide()
def DocumentObject.ViewProvider.hide (self)
References DocumentObject.ViewProvider.__vobject__.
isDerivedFrom()
def DocumentObject.ViewProvider.isDerivedFrom (self, obj)
returns True if this object is derived from the given C++ class, for
example Part::Feature
References DocumentObject.ViewProvider.__vobject__.
isVisible()
def DocumentObject.ViewProvider.isVisible (self)
References DocumentObject.ViewProvider.__vobject__.
MemSize()
def DocumentObject.ViewProvider.MemSize (self)
References DocumentObject.ViewProvider.__vobject__.
Module()
def DocumentObject.ViewProvider.Module (self)
References DocumentObject.ViewProvider.__vobject__.
Object()
def DocumentObject.ViewProvider.Object (self)
References DocumentObject.ViewProvider.__vobject__.
Referenced by ArchPanel.CommandPanelSheet.Activated(), ArchSite.Compass.buildCoordinates(), and ArchSchedule.CommandArchSchedule.IsActive().
PropertiesList()
def DocumentObject.ViewProvider.PropertiesList (self)
References DocumentObject.ViewProvider.__vobject__.
RootNode()
def DocumentObject.ViewProvider.RootNode (self)
References DocumentObject.ViewProvider.__vobject__.
setTransformation()
def DocumentObject.ViewProvider.setTransformation (self, trsf)
References DocumentObject.ViewProvider.__vobject__.
show()
def DocumentObject.ViewProvider.show (self)
References DocumentObject.ViewProvider.__vobject__.
supportedProperties()
def DocumentObject.ViewProvider.supportedProperties (self)
References DocumentObject.ViewProvider.__vobject__.
toString()
def DocumentObject.ViewProvider.toString (self)
References DocumentObject.ViewProvider.__vobject__.
Type()
def DocumentObject.ViewProvider.Type (self)
References DocumentObject.ViewProvider.__vobject__.
Referenced by ArchPanel.CommandPanelSheet.Activated(), ArchStructure.StructSelectionObserver.addSelection(), ArchSite.Compass.buildCoordinates(), ArchAxis.CommandArchGrid.IsActive(), and ArchSchedule.CommandArchSchedule.IsActive().
update()
def DocumentObject.ViewProvider.update (self)
References DocumentObject.ViewProvider.__vobject__.
Referenced by ArchAxis.CommandArchGrid.IsActive().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/TemplatePyMod/DocumentObject.py