FreeCAD: DrawingGui::TaskProjection Class Reference
DrawingGui::TaskProjection Class Reference
Embed the panel into a task dialog.
#include <TaskDialog.h>
Public Member Functions
bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual QDialogButtonBox::StandardButtons getStandardButtons () const
tells the framework which buttons are wished for the dialog
virtual bool isAllowedAlterDocument (void) const
TaskProjection ()
~TaskProjection ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
Embed the panel into a task dialog.
Constructor & Destructor Documentation
TaskProjection()
TaskProjection::TaskProjection ()
References Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
~TaskProjection()
TaskProjection::~TaskProjection ()
Member Function Documentation
accept()
bool TaskProjection::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Application::activeDocument(), Gui::Command::addModule(), Gui::Command::commitCommand(), Gui::Command::Doc, Base::BaseClass::getClassTypeId(), Gui::Document::getMDIViewsOfType(), Gui::SelectionSingleton::getObjectsOfType(), Gui::Application::Instance, Gui::Command::openCommand(), Gui::Selection(), Gui::Command::updateActive(), and OfflineRenderingUtils::viewer().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
getStandardButtons()
virtual QDialogButtonBox::StandardButtons DrawingGui::TaskProjection::getStandardButtons (void) const virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
isAllowedAlterDocument()
virtual bool DrawingGui::TaskProjection::isAllowedAlterDocument (void) const virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Drawing/Gui/TaskDialog.h
Sources/FreeCAD/src/Mod/Drawing/Gui/TaskDialog.cpp