FreeCAD: MeshGui::SoFCMeshVertex Class Reference
MeshGui::SoFCMeshVertex Class Reference
#include <SoFCMeshVertex.h>
Public Member Functions
virtual void callback (SoCallbackAction *action)
virtual void doAction (SoAction *action)
virtual void getBoundingBox (SoGetBoundingBoxAction *action)
virtual void getPrimitiveCount (SoGetPrimitiveCountAction *action)
virtual void GLRender (SoGLRenderAction *action)
virtual void pick (SoPickAction *action)
SoFCMeshVertex (void)
Static Public Member Functions
static void initClass (void)
Public Attributes
SoSFMeshPointArray point
Protected Member Functions
virtual ~SoFCMeshVertex ()
Constructor & Destructor Documentation
SoFCMeshVertex()
SoFCMeshVertex::SoFCMeshVertex (void)
Constructor.
~SoFCMeshVertex()
SoFCMeshVertex::~SoFCMeshVertex () protected virtual
Destructor.
Member Function Documentation
callback()
void SoFCMeshVertex::callback (SoCallbackAction * action) virtual
References doAction().
Referenced by qtunittest.GUITestResult::addError(), Mod.Test.unittestgui.GUITestResult::addError(), qtunittest.GUITestResult::addFailure(), Mod.Test.unittestgui.GUITestResult::addFailure(), ArchStructure.StructSelectionObserver::addSelection(), PathScripts.PathCamoticsGui.CamoticsSimulation::execute(), qtunittest.GUITestResult::startTest(), Mod.Test.unittestgui.GUITestResult::startTest(), qtunittest.GUITestResult::stopTest(), and Mod.Test.unittestgui.GUITestResult::stopTest().
doAction()
void SoFCMeshVertex::doAction (SoAction * action) virtual
References MeshGui::SoFCMeshVertexElement::set().
Referenced by callback(), getBoundingBox(), getPrimitiveCount(), GLRender(), and pick().
getBoundingBox()
void SoFCMeshVertex::getBoundingBox (SoGetBoundingBoxAction * action) virtual
References doAction().
getPrimitiveCount()
void SoFCMeshVertex::getPrimitiveCount (SoGetPrimitiveCountAction * action) virtual
References doAction().
GLRender()
void SoFCMeshVertex::GLRender (SoGLRenderAction * action) virtual
References doAction().
initClass()
void SoFCMeshVertex::initClass (void) static
pick()
void SoFCMeshVertex::pick (SoPickAction * action) virtual
References doAction().
Member Data Documentation
point
SoSFMeshPointArray MeshGui::SoFCMeshVertex::point
Referenced by draftguitools.gui_arcs.Arc::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_shapestrings.ShapeString::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_split.Split::action(), draftguitools.gui_texts.Text::action(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_circulararray.CircularArray::click(), draftguitools.gui_orthoarray.OrthoArray::click(), draftguitools.gui_points.Point::click(), draftguitools.gui_polararray.PolarArray::click(), PathScripts.PathGetPoint.TaskPanel::getPoint(), draftguitools.gui_scale.Scale::handle_mouse_click_event(), draftguitools.gui_move.Move::handle_mouse_click_event(), draftguitools.gui_rotate.Rotate::handle_mouse_click_event(), draftguitools.gui_move.Move::handle_mouse_move_event(), draftguitools.gui_rotate.Rotate::handle_mouse_move_event(), draftguitools.gui_scale.Scale::handle_mouse_move_event(), draftguitools.gui_circulararray.CircularArray::move(), draftguitools.gui_points.Point::move(), draftguitools.gui_polararray.PolarArray::move(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_points.Point::numericInput(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_rotate.Rotate::set_center(), draftguitools.gui_dimensions.Dimension::set_constraint_node(), draftguitools.gui_rotate.Rotate::set_rotation_angle(), draftguitools.gui_trimex.Trimex::trimObject(), and PathScripts.PathGetPoint.TaskPanel::updatePoint().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/Gui/SoFCMeshVertex.h
FreeCAD/src/Mod/Mesh/Gui/SoFCMeshVertex.cpp