FreeCAD: Gui::Dialog::DlgMaterialPropertiesImp Class Reference
Gui::Dialog::DlgMaterialPropertiesImp Class Reference
#include <DlgMaterialPropertiesImp.h>
Public Slots
void on_ambientColor_changed ()
Sets the ambient color.
void on_diffuseColor_changed ()
Sets the diffuse color.
void on_emissiveColor_changed ()
Sets the emissive color.
void on_shininess_valueChanged (int)
Sets the current shininess.
void on_specularColor_changed ()
Sets the specular color.
Public Member Functions
QColor diffuseColor () const
DlgMaterialPropertiesImp (const std::string &mat, QWidget *parent=0, Qt::WindowFlags fl=Qt::WindowFlags())
Constructs a Gui::Dialog::DlgMaterialPropertiesImp as a child of 'parent', with the name 'name' and widget flags set to 'f'.
void setViewProviders (const std::vector< Gui::ViewProvider * > &)
Sets the document objects and their view providers to manipulate the material.
~DlgMaterialPropertiesImp ()
Destroys the object and frees any allocated resources.
Constructor & Destructor Documentation
DlgMaterialPropertiesImp()
DlgMaterialPropertiesImp::DlgMaterialPropertiesImp (const std::string & mat, QWidget * parent = 0, Qt::WindowFlags fl = Qt::WindowFlags())
Constructs a Gui::Dialog::DlgMaterialPropertiesImp as a child of 'parent', with the name 'name' and widget flags set to 'f'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
~DlgMaterialPropertiesImp()
DlgMaterialPropertiesImp::~DlgMaterialPropertiesImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
diffuseColor()
QColor DlgMaterialPropertiesImp::diffuseColor () const
on_ambientColor_changed
void DlgMaterialPropertiesImp::on_ambientColor_changed () slot
Sets the ambient color.
References App::Material::ambientColor, Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), App::PropertyMaterial::getValue(), Base::Type::isDerivedFrom(), and App::PropertyMaterial::setValue().
on_diffuseColor_changed
void DlgMaterialPropertiesImp::on_diffuseColor_changed () slot
Sets the diffuse color.
References App::Material::diffuseColor, Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), App::PropertyMaterial::getValue(), Base::Type::isDerivedFrom(), and App::PropertyMaterial::setValue().
on_emissiveColor_changed
void DlgMaterialPropertiesImp::on_emissiveColor_changed () slot
Sets the emissive color.
References App::Material::emissiveColor, Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), App::PropertyMaterial::getValue(), Base::Type::isDerivedFrom(), and App::PropertyMaterial::setValue().
on_shininess_valueChanged
void DlgMaterialPropertiesImp::on_shininess_valueChanged (int sh) slot
Sets the current shininess.
References Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), App::PropertyMaterial::getValue(), Base::Type::isDerivedFrom(), App::PropertyMaterial::setValue(), and App::Material::shininess.
on_specularColor_changed
void DlgMaterialPropertiesImp::on_specularColor_changed () slot
Sets the specular color.
References Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), App::PropertyMaterial::getValue(), Base::Type::isDerivedFrom(), App::PropertyMaterial::setValue(), and App::Material::specularColor.
setViewProviders()
void DlgMaterialPropertiesImp::setViewProviders (const std::vector< Gui::ViewProvider * > & Obj)
Sets the document objects and their view providers to manipulate the material.
References App::Material::ambientColor, App::Color::b, App::Material::diffuseColor, App::Material::emissiveColor, App::Color::g, Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), App::PropertyMaterial::getValue(), Base::Type::isDerivedFrom(), App::Color::r, App::Material::shininess, and App::Material::specularColor.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgMaterialPropertiesImp.h
Sources/FreeCAD/src/Gui/DlgMaterialPropertiesImp.cpp