FreeCAD: TechDraw::Preferences Class Reference
TechDraw::Preferences Class Reference
#include <Preferences.h>
Static Public Member Functions
static int altDecimals ()
static double ASMEGap ()
static int balloonArrow ()
static std::string bitmapFill (void)
static QString defaultTemplate ()
static QString defaultTemplateDir ()
static double dimFontSizeMM ()
static std::string formatSpec ()
static double ISOGap ()
static bool keepPagesUpToDate ()
static std::string labelFont ()
static QString labelFontQString ()
static double labelFontSizeMM ()
static int lineGroup ()
static std::string lineGroupFile ()
static int mattingStyle ()
static App::Color normalColor ()
static std::string patFile ()
static App::Color preselectColor ()
static int projectionAngle ()
static App::Color selectColor ()
static std::string svgFile ()
static bool useGlobalDecimals ()
static App::Color vertexColor ()
static double vertexScale ()
Static Public Attributes
static const double DefaultFontSizeInMM = 5.0
Member Function Documentation
altDecimals()
int Preferences::altDecimals () static
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), and App::Application::GetUserParameter().
Referenced by TechDraw::DrawViewDimension::getDefaultFormatSpec().
ASMEGap()
double Preferences::ASMEGap () static
References App::GetApplication(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
balloonArrow()
int Preferences::balloonArrow () static
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), and App::Application::GetUserParameter().
Referenced by TechDraw::DrawViewBalloon::prefEnd().
bitmapFill()
std::string Preferences::bitmapFill (void) static
References Base::Console(), App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetGroup(), App::Application::getResourceDir(), App::Application::GetUserParameter(), Base::FileInfo::isReadable(), and Base::ConsoleSingleton::Warning().
defaultTemplate()
QString Preferences::defaultTemplate () static
References Base::Console(), App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetGroup(), App::Application::getResourceDir(), App::Application::GetUserParameter(), Base::FileInfo::isReadable(), and Base::ConsoleSingleton::Warning().
defaultTemplateDir()
QString Preferences::defaultTemplateDir () static
References Base::Console(), App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetGroup(), App::Application::getResourceDir(), App::Application::GetUserParameter(), Base::FileInfo::isReadable(), and Base::ConsoleSingleton::Warning().
dimFontSizeMM()
double Preferences::dimFontSizeMM () static
References DefaultFontSizeInMM, App::GetApplication(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by MRichTextEdit::getDefFontSizeNum().
formatSpec()
std::string Preferences::formatSpec () static
References App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by TechDraw::DrawViewDimension::getDefaultFormatSpec().
ISOGap()
double Preferences::ISOGap () static
References App::GetApplication(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
keepPagesUpToDate()
bool Preferences::keepPagesUpToDate () static
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by TechDraw::DrawPage::DrawPage().
labelFont()
std::string Preferences::labelFont () static
References App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by TechDraw::DrawViewAnnotation::DrawViewAnnotation(), and labelFontQString().
labelFontQString()
QString Preferences::labelFontQString () static
References labelFont().
labelFontSizeMM()
double Preferences::labelFontSizeMM () static
References DefaultFontSizeInMM, App::GetApplication(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by TechDraw::DrawViewAnnotation::DrawViewAnnotation().
lineGroup()
int Preferences::lineGroup () static
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), and App::Application::GetUserParameter().
Referenced by TechDraw::CosmeticVertex::CosmeticVertex(), TechDraw::DrawUtil::getDefaultLineWeight(), TechDraw::LineGroup::getDefaultWidth(), and TechDraw::LineFormat::getDefEdgeWidth().
lineGroupFile()
std::string Preferences::lineGroupFile () static
References Base::Console(), App::GetApplication(), ParameterGrp::GetASCII(), App::Application::getResourceDir(), Base::FileInfo::isReadable(), and Base::ConsoleSingleton::Warning().
Referenced by TechDraw::LineGroup::lineGroupFactory().
mattingStyle()
int Preferences::mattingStyle () static
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), and App::Application::GetUserParameter().
Referenced by TechDraw::DrawViewDetail::detailExec(), TechDrawGui::QGIHighlight::getHoleStyle(), and TechDrawGui::QGIMatting::getHoleStyle().
normalColor()
App::Color Preferences::normalColor () static
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetUnsigned(), App::Application::GetUserParameter(), and App::Color::setPackedValue().
Referenced by TechDraw::LineFormat::getDefEdgeColor().
patFile()
std::string Preferences::patFile () static
References Base::Console(), App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetGroup(), App::Application::getResourceDir(), App::Application::GetUserParameter(), Base::FileInfo::isReadable(), and Base::ConsoleSingleton::Warning().
Referenced by TechDraw::DrawGeomHatch::prefGeomHatchFile().
preselectColor()
App::Color Preferences::preselectColor () static
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetUnsigned(), App::Application::GetUserParameter(), and App::Color::setPackedValue().
projectionAngle()
int Preferences::projectionAngle () static
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), and App::Application::GetUserParameter().
Referenced by TechDraw::DrawPage::DrawPage(), and TechDraw::DrawProjGroup::getDefProjConv().
selectColor()
App::Color Preferences::selectColor () static
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetUnsigned(), App::Application::GetUserParameter(), and App::Color::setPackedValue().
svgFile()
std::string Preferences::svgFile () static
References Base::Console(), App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetGroup(), App::Application::getResourceDir(), App::Application::GetUserParameter(), Base::FileInfo::isReadable(), and Base::ConsoleSingleton::Warning().
Referenced by TechDraw::DrawHatch::prefSvgHatch().
useGlobalDecimals()
bool Preferences::useGlobalDecimals () static
References App::GetApplication(), and ParameterGrp::GetBool().
Referenced by TechDraw::DrawViewDimension::useDecimals().
vertexColor()
App::Color Preferences::vertexColor () static
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetUnsigned(), App::Application::GetUserParameter(), and App::Color::setPackedValue().
Referenced by TechDraw::CosmeticVertex::CosmeticVertex().
vertexScale()
double Preferences::vertexScale () static
References App::GetApplication(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by TechDraw::CosmeticVertex::CosmeticVertex().
Member Data Documentation
DefaultFontSizeInMM
const double Preferences::DefaultFontSizeInMM = 5.0 static
Referenced by dimFontSizeMM(), and labelFontSizeMM().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/App/Preferences.h
FreeCAD/src/Mod/TechDraw/App/Preferences.cpp