FreeCAD: PartDesignGui::TaskDatumParameters Class Reference
PartDesignGui::TaskDatumParameters Class Reference
#include <TaskDatumParameters.h>
Public Member Functions
TaskDatumParameters (ViewProviderDatum *DatumView, QWidget *parent=0)
~TaskDatumParameters ()
Public Member Functions inherited from PartGui::TaskAttacher
Attacher::eMapMode getActiveMapMode ()
getActiveMapMode returns either the default mode for selected references, or the mode that was selected by the user in the list.
bool getFlip (void) const
bool isCompleted () const
TaskAttacher (Gui::ViewProviderDocumentObject *ViewProvider, QWidget *parent=0, QString picture=QString(), QString text=QString::fromLatin1("Attachment"), VisibilityFunction func=0)
~TaskAttacher ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (QWidget *parent=0)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (QWidget *parent=0)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockConnection (bool block)
void detachSelection ()
Detaches from the selection.
bool isConnectionAttached () const
bool isConnectionBlocked () const
SelectionObserver (bool attach=true, int resolve=1)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, int resolve=1)
Constructor.
virtual ~SelectionObserver ()
Additional Inherited Members
Public Types inherited from PartGui::TaskAttacher
typedef boost::function< void(bool, const std::string &, Gui::ViewProviderDocumentObject *, App::DocumentObject *, const std::string &)> VisibilityFunction
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Member Functions inherited from PartGui::TaskAttacher
void changeEvent (QEvent *e) override
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Protected Attributes inherited from PartGui::TaskAttacher
std::string ObjectName
Gui::ViewProviderDocumentObject * ViewProvider
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskDatumParameters()
TaskDatumParameters::TaskDatumParameters (ViewProviderDatum * DatumView, QWidget * parent = 0)
References Gui::SelectionSingleton::addSelectionGate(), Gui::ViewProviderDocumentObject::getObject(), and Gui::Selection().
~TaskDatumParameters()
TaskDatumParameters::~TaskDatumParameters ()
References Base::Persistence::getClassTypeId(), Base::BaseClass::isDerivedFrom(), Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), and PartGui::TaskAttacher::ViewProvider.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/PartDesign/Gui/TaskDatumParameters.h
Sources/FreeCAD/src/Mod/PartDesign/Gui/TaskDatumParameters.cpp