FreeCAD: SMESH_MeshVSLink Class Reference
SMESH_MeshVSLink Class Reference
#include <SMESH_MeshVSLink.hxx>
Public Member Functions
Standard_EXPORT Standard_Boolean Get3DGeom (const Standard_Integer ID, Standard_Integer &NbNodes, Handle(MeshVS_HArray1OfSequenceOfInteger)&Data) const override
Standard_EXPORT Standard_Address GetAddr (const Standard_Integer ID, const Standard_Boolean IsElement) const override
This method returns by number an address of any entity which represents element or node data structure.
Standard_EXPORT const TColStd_PackedMapOfInteger & GetAllElements () const override
This method returns map of all elements the object consist of.
Standard_EXPORT void GetAllGroups (TColStd_PackedMapOfInteger &Ids) const override
This method returns map of all groups the object contains.
Standard_EXPORT const TColStd_PackedMapOfInteger & GetAllNodes () const override
This method returns map of all nodes the object consist of.
Standard_EXPORT Standard_Boolean GetGeom (const Standard_Integer ID, const Standard_Boolean IsElement, TColStd_Array1OfReal &Coords, Standard_Integer &NbNodes, MeshVS_EntityType &Type) const override
Returns geometry information about node (if IsElement is False) or element (IsElement is True)
by co-ordinates.
Standard_EXPORT Standard_Boolean GetGeomType (const Standard_Integer ID, const Standard_Boolean IsElement, MeshVS_EntityType &Type) const override
This method is similar to GetGeom, but returns only element or node type.
Standard_EXPORT Standard_Boolean GetNodesByElement (const Standard_Integer ID, TColStd_Array1OfInteger &NodeIDs, Standard_Integer &NbNodes) const override
This method returns information about what node this element consist of.
Standard_EXPORT Standard_Boolean GetNormal (const Standard_Integer Id, const Standard_Integer Max, Standard_Real &nx, Standard_Real &ny, Standard_Real &nz) const override
This method calculates normal of face, which is using for correct reflection presentation.
Standard_EXPORT const Handle (Standard_Type) &DynamicType() const
Standard_EXPORT SMESH_MeshVSLink (const SMESH_Mesh *aMesh)
Constructor
Constructor & Destructor Documentation
SMESH_MeshVSLink()
SMESH_MeshVSLink::SMESH_MeshVSLink (const SMESH_Mesh * aMesh)
Constructor
References SMDS_Mesh::edgesIterator(), SMDS_Mesh::facesIterator(), SMESHDS_Mesh::GetGroups(), SMDS_MeshElement::GetID(), SMESHDS_GroupBase::GetID(), SMESH_Mesh::GetMeshDS(), SMESHDS_Group::IsEmpty(), SMDS_Mesh::nodesIterator(), and SMDS_Mesh::volumesIterator().
Member Function Documentation
Get3DGeom()
Standard_Boolean SMESH_MeshVSLink::Get3DGeom (const Standard_Integer ID, Standard_Integer & NbNodes, Handle(MeshVS_HArray1OfSequenceOfInteger)& Data) const override
References SMDS_Mesh::FindElement(), SMDS_VolumeTool::GetFaceNodesIndices(), SMESH_Mesh::GetMeshDS(), SMDS_MeshElement::GetType(), SMDS_VolumeTool::NbFaceNodes(), SMDS_VolumeTool::NbFaces(), SMDS_VolumeTool::NbNodes(), and SMDS_VolumeTool::Set().
GetAddr()
Standard_Address SMESH_MeshVSLink::GetAddr (const Standard_Integer ID, const Standard_Boolean IsElement) const override
This method returns by number an address of any entity which represents element or node data structure.
GetAllElements()
const TColStd_PackedMapOfInteger & SMESH_MeshVSLink::GetAllElements () const override
This method returns map of all elements the object consist of.
GetAllGroups()
void SMESH_MeshVSLink::GetAllGroups (TColStd_PackedMapOfInteger & Ids) const override
This method returns map of all groups the object contains.
GetAllNodes()
const TColStd_PackedMapOfInteger & SMESH_MeshVSLink::GetAllNodes () const override
This method returns map of all nodes the object consist of.
GetGeom()
Standard_Boolean SMESH_MeshVSLink::GetGeom (const Standard_Integer ID, const Standard_Boolean IsElement, TColStd_Array1OfReal & Coords, Standard_Integer & NbNodes, MeshVS_EntityType & Type) const override
Returns geometry information about node (if IsElement is False) or element (IsElement is True)
by co-ordinates.
For element this method must return all its nodes co-ordinates in the strict order: X, Y, Z and
with nodes order is the same as in wire bounding the face or link. NbNodes is number of nodes of element.
It is recommended to return 1 for node. Type is an element type.
References SMDS_Mesh::FindElement(), SMDS_Mesh::FindNode(), SMESH_Mesh::GetMeshDS(), SMDS_MeshElement::GetNode(), SMDS_MeshNode::GetType(), SMDS_MeshElement::GetType(), SMDS_MeshElement::NbNodes(), SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
GetGeomType()
Standard_Boolean SMESH_MeshVSLink::GetGeomType (const Standard_Integer ID, const Standard_Boolean IsElement, MeshVS_EntityType & Type) const override
This method is similar to GetGeom, but returns only element or node type.
This method is provided for
a fine performance.
References SMDS_Mesh::FindElement(), SMDS_Mesh::FindNode(), SMESH_Mesh::GetMeshDS(), SMDS_MeshNode::GetType(), and SMDS_MeshElement::GetType().
GetNodesByElement()
Standard_Boolean SMESH_MeshVSLink::GetNodesByElement (const Standard_Integer ID, TColStd_Array1OfInteger & NodeIDs, Standard_Integer & NbNodes) const override
This method returns information about what node this element consist of.
References SMDS_Mesh::FindElement(), SMDS_MeshElement::GetID(), SMESH_Mesh::GetMeshDS(), SMDS_MeshElement::GetNode(), and SMDS_MeshElement::NbNodes().
GetNormal()
Standard_Boolean SMESH_MeshVSLink::GetNormal (const Standard_Integer Id, const Standard_Integer Max, Standard_Real & nx, Standard_Real & ny, Standard_Real & nz) const override
This method calculates normal of face, which is using for correct reflection presentation.
There is default method, for advance reflection this method can be redefined.
References SMDS_Mesh::FindElement(), SMESH_Mesh::GetMeshDS(), SMDS_MeshElement::GetNode(), SMDS_MeshElement::NbNodes(), SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
Handle()
Standard_EXPORT const SMESH_MeshVSLink::Handle (Standard_Type) const &
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_MeshVSLink.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/SMESH_MeshVSLink.cpp