FreeCAD: PathSimulator::PathSim Class Reference
PathSimulator::PathSim Class Reference
The representation of a CNC Toolpath Simulator.
#include <PathSim.h>
Public Member Functions
Base::Placement * ApplyCommand (Base::Placement *pos, Command *cmd)
void BeginSimulation (Part::TopoShape *stock, float resolution)
PathSim ()
void SetToolShape (const TopoDS_Shape &toolShape, float resolution)
~PathSim ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Attributes
cStock * m_stock
cSimTool * m_tool
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The representation of a CNC Toolpath Simulator.
Constructor & Destructor Documentation
PathSim()
PathSim::PathSim ()
References m_stock, and m_tool.
~PathSim()
PathSim::~PathSim ()
References m_stock, and m_tool.
Member Function Documentation
ApplyCommand()
Base::Placement * PathSim::ApplyCommand (Base::Placement * pos, Command * cmd)
References cStock::ApplyCircularTool(), cStock::ApplyLinearTool(), Path::Command::getCenter(), m_stock, m_tool, Path::Command::Name, Base::Placement::setPosition(), Point3D::UpdateCmd(), draftgeoutils.general::vec(), Point3D::x, Point3D::y, and Point3D::z.
BeginSimulation()
void PathSim::BeginSimulation (Part::TopoShape * stock, float resolution)
References Part::TopoShape::getBoundBox(), Base::BoundBox3< _Precision >::LengthX(), Base::BoundBox3< _Precision >::LengthY(), Base::BoundBox3< _Precision >::LengthZ(), m_stock, Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, and Base::BoundBox3< _Precision >::MinZ.
SetToolShape()
void PathSim::SetToolShape (const TopoDS_Shape & toolShape, float resolution)
References m_tool.
Member Data Documentation
m_stock
cStock* PathSimulator::PathSim::m_stock
Referenced by ApplyCommand(), BeginSimulation(), PathSim(), and ~PathSim().
m_tool
cSimTool* PathSimulator::PathSim::m_tool
Referenced by ApplyCommand(), PathSim(), SetToolShape(), and ~PathSim().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Path/PathSimulator/App/PathSim.h
FreeCAD/src/Mod/Path/PathSimulator/App/PathSim.cpp