FreeCAD: Utils_Mutex Class Reference
Utils_Mutex Class Reference
#include <Utils_Mutex.hxx>
Public Member Functions
void lock ()
void unlock ()
Utils_Mutex ()
~Utils_Mutex ()
Constructor & Destructor Documentation
Utils_Mutex()
Utils_Mutex::Utils_Mutex ()
~Utils_Mutex()
Utils_Mutex::~Utils_Mutex ()
Member Function Documentation
lock()
void Utils_Mutex::lock ()
Referenced by AddonManager.CommandAddonManager::on_package_updated(), drafttaskpanels.task_scale.ScaleTaskPanel::retranslateUi(), drafttaskpanels.task_scale.ScaleTaskPanel::setValue(), addonmanager_workers.CacheMacroCode::terminate(), and addonmanager_workers.CacheMacroCode::update_and_advance().
unlock()
void Utils_Mutex::unlock ()
The documentation for this class was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/inc/Utils_Mutex.hxx