FreeCAD: MeshCore::MeshFixDegeneratedFacets Class Reference
MeshCore::MeshFixDegeneratedFacets Class Reference
The MeshFixDegeneratedFacets class tries to fix degenerations by removing the concerning facets.
#include <Degeneration.h>
Public Member Functions
bool Fixup ()
Removes degenerated facets.
MeshFixDegeneratedFacets (MeshKernel &rclM, float fEps)
Construction.
~MeshFixDegeneratedFacets ()
Destruction.
Public Member Functions inherited from MeshCore::MeshValidation
MeshValidation (MeshKernel &rclB)
virtual ~MeshValidation ()
Detailed Description
The MeshFixDegeneratedFacets class tries to fix degenerations by removing the concerning facets.
See also
MeshEvalDegeneratedFacets
Author
Werner Mayer
Constructor & Destructor Documentation
MeshFixDegeneratedFacets()
MeshCore::MeshFixDegeneratedFacets::MeshFixDegeneratedFacets (MeshKernel & rclM, float fEps)
Construction.
~MeshFixDegeneratedFacets()
MeshCore::MeshFixDegeneratedFacets::~MeshFixDegeneratedFacets ()
Destruction.
Member Function Documentation
Fixup()
bool MeshFixDegeneratedFacets::Fixup () virtual
Removes degenerated facets.
Implements MeshCore::MeshValidation.
References MeshCore::MeshFacetIterator::Init(), MeshCore::MeshGeomFacet::IsDegenerated(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), MeshCore::MeshFacetIterator::Position(), MeshCore::MeshTopoAlgorithm::RemoveDegeneratedFacet(), and MeshCore::MeshFacetIterator::Set().
Referenced by Mesh::MeshObject::validateDegenerations().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Degeneration.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Degeneration.cpp