FreeCAD: Path::VoronoiPy Class Reference
Path::VoronoiPy Class Reference
The python export class for Voronoi.
#include <VoronoiPy.h>
Public Types
typedef Voronoi * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
VoronoiPy (Voronoi *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of VoronoiPy.
static PyMethodDef Methods []
Methods structure of VoronoiPy.
static PyTypeObject Type
Type structure of VoronoiPy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~VoronoiPy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * numCells (PyObject *args)
implementer for the numCells() method
PyObject * numEdges (PyObject *args)
implementer for the numEdges() method
PyObject * numVertices (PyObject *args)
implementer for the numVertices() method
PyObject * addPoint (PyObject *args)
implementer for the addPoint() method
PyObject * addSegment (PyObject *args)
implementer for the addSegment() method
PyObject * construct (PyObject *args)
implementer for the construct() method
PyObject * colorExterior (PyObject *args)
implementer for the colorExterior() method
PyObject * colorTwins (PyObject *args)
implementer for the colorTwins() method
PyObject * colorColinear (PyObject *args)
implementer for the colorColinear() method
PyObject * resetColor (PyObject *args)
implementer for the resetColor() method
PyObject * getPoints (PyObject *args)
implementer for the getPoints() method
PyObject * numPoints (PyObject *args)
implementer for the numPoints() method
PyObject * getSegments (PyObject *args)
implementer for the getSegments() method
PyObject * numSegments (PyObject *args)
implementer for the numSegments() method
static PyObject * staticCallback_numCells (PyObject *self, PyObject *args)
callback for the numCells() method
static PyObject * staticCallback_numEdges (PyObject *self, PyObject *args)
callback for the numEdges() method
static PyObject * staticCallback_numVertices (PyObject *self, PyObject *args)
callback for the numVertices() method
static PyObject * staticCallback_addPoint (PyObject *self, PyObject *args)
callback for the addPoint() method
static PyObject * staticCallback_addSegment (PyObject *self, PyObject *args)
callback for the addSegment() method
static PyObject * staticCallback_construct (PyObject *self, PyObject *args)
callback for the construct() method
static PyObject * staticCallback_colorExterior (PyObject *self, PyObject *args)
callback for the colorExterior() method
static PyObject * staticCallback_colorTwins (PyObject *self, PyObject *args)
callback for the colorTwins() method
static PyObject * staticCallback_colorColinear (PyObject *self, PyObject *args)
callback for the colorColinear() method
static PyObject * staticCallback_resetColor (PyObject *self, PyObject *args)
callback for the resetColor() method
static PyObject * staticCallback_getPoints (PyObject *self, PyObject *args)
callback for the getPoints() method
static PyObject * staticCallback_numPoints (PyObject *self, PyObject *args)
callback for the numPoints() method
static PyObject * staticCallback_getSegments (PyObject *self, PyObject *args)
callback for the getSegments() method
static PyObject * staticCallback_numSegments (PyObject *self, PyObject *args)
callback for the numSegments() method
callbacks and implementers for the python object attributes
Py::List getCells (void) const
getter for the Cells attribute
Py::List getEdges (void) const
getter for the Edges attribute
Py::List getVertices (void) const
getter for the Vertices attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Voronoi * getVoronoiPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getCells (PyObject *self, void *closure)
getter callback for the Cells attribute
static int staticCallback_setCells (PyObject *self, PyObject *value, void *closure)
setter callback for the Cells attribute
static PyObject * staticCallback_getEdges (PyObject *self, void *closure)
getter callback for the Edges attribute
static int staticCallback_setEdges (PyObject *self, PyObject *value, void *closure)
setter callback for the Edges attribute
static PyObject * staticCallback_getVertices (PyObject *self, void *closure)
getter callback for the Vertices attribute
static int staticCallback_setVertices (PyObject *self, PyObject *value, void *closure)
setter callback for the Vertices attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Voronoi.
Member Typedef Documentation
PointerType
typedef Voronoi* Path::VoronoiPy::PointerType
Constructor & Destructor Documentation
~VoronoiPy()
VoronoiPy::~VoronoiPy () protected
VoronoiPy()
VoronoiPy::VoronoiPy (Voronoi * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
addPoint()
PyObject * VoronoiPy::addPoint (PyObject * args)
implementer for the addPoint() method
References Path::Voronoi::addPoint(), and getVoronoiPtr().
Referenced by staticCallback_addPoint().
addSegment()
PyObject * VoronoiPy::addSegment (PyObject * args)
implementer for the addSegment() method
References Path::Voronoi::addSegment(), and getVoronoiPtr().
Referenced by staticCallback_addSegment().
colorColinear()
PyObject * VoronoiPy::colorColinear (PyObject * args)
implementer for the colorColinear() method
References Path::Voronoi::colorColinear(), and getVoronoiPtr().
Referenced by staticCallback_colorColinear().
colorExterior()
PyObject * VoronoiPy::colorExterior (PyObject * args)
implementer for the colorExterior() method
References Path::Voronoi::colorExterior(), and getVoronoiPtr().
Referenced by staticCallback_colorExterior().
colorTwins()
PyObject * VoronoiPy::colorTwins (PyObject * args)
implementer for the colorTwins() method
References Path::Voronoi::colorTwins(), and getVoronoiPtr().
Referenced by staticCallback_colorTwins().
construct()
PyObject * VoronoiPy::construct (PyObject * args)
implementer for the construct() method
References Path::Voronoi::construct(), and getVoronoiPtr().
Referenced by staticCallback_construct().
getCells()
Py::List VoronoiPy::getCells (void) const
getter for the Cells attribute
References getVoronoiPtr(), and Path::Voronoi::numCells().
Referenced by staticCallback_getCells().
getCustomAttributes()
PyObject * VoronoiPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getEdges()
Py::List VoronoiPy::getEdges (void) const
getter for the Edges attribute
References getVoronoiPtr(), and Path::Voronoi::numEdges().
Referenced by staticCallback_getEdges().
getPoints()
PyObject * VoronoiPy::getPoints (PyObject * args)
implementer for the getPoints() method
References getVoronoiPtr().
Referenced by staticCallback_getPoints().
getSegments()
PyObject * VoronoiPy::getSegments (PyObject * args)
implementer for the getSegments() method
References getVoronoiPtr().
Referenced by staticCallback_getSegments().
GetType()
virtual PyTypeObject* Path::VoronoiPy::GetType (void) virtual
Reimplemented from Base::BaseClassPy.
getVertices()
Py::List VoronoiPy::getVertices (void) const
getter for the Vertices attribute
References getVoronoiPtr(), and Path::Voronoi::numVertices().
Referenced by staticCallback_getVertices().
getVoronoiPtr()
Voronoi * VoronoiPy::getVoronoiPtr (void) const
getter for the object handled by this class
Referenced by addPoint(), addSegment(), colorColinear(), colorExterior(), colorTwins(), construct(), getCells(), getEdges(), getPoints(), getSegments(), getVertices(), numCells(), numEdges(), numPoints(), numSegments(), numVertices(), PyInit(), representation(), and resetColor().
numCells()
PyObject * VoronoiPy::numCells (PyObject * args)
implementer for the numCells() method
References getVoronoiPtr().
Referenced by staticCallback_numCells().
numEdges()
PyObject * VoronoiPy::numEdges (PyObject * args)
implementer for the numEdges() method
References getVoronoiPtr().
Referenced by staticCallback_numEdges().
numPoints()
PyObject * VoronoiPy::numPoints (PyObject * args)
implementer for the numPoints() method
References getVoronoiPtr().
Referenced by staticCallback_numPoints().
numSegments()
PyObject * VoronoiPy::numSegments (PyObject * args)
implementer for the numSegments() method
References getVoronoiPtr().
Referenced by staticCallback_numSegments().
numVertices()
PyObject * VoronoiPy::numVertices (PyObject * args)
implementer for the numVertices() method
References getVoronoiPtr().
Referenced by staticCallback_numVertices().
PyInit()
int VoronoiPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::BaseClassPy.
References Path::Voronoi::getScale(), getVoronoiPtr(), and Path::Voronoi::setScale().
PyMake()
PyObject * VoronoiPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References VoronoiPy().
representation()
std::string VoronoiPy::representation (void) const
References getVoronoiPtr(), Path::Voronoi::numCells(), Path::Voronoi::numEdges(), Path::Voronoi::numPoints(), Path::Voronoi::numSegments(), and Path::Voronoi::numVertices().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
resetColor()
PyObject * VoronoiPy::resetColor (PyObject * args)
implementer for the resetColor() method
References getVoronoiPtr(), and Path::Voronoi::resetColor().
Referenced by staticCallback_resetColor().
setCustomAttributes()
int VoronoiPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_addPoint()
PyObject * VoronoiPy::staticCallback_addPoint (PyObject * self, PyObject * args) static
callback for the addPoint() method
References addPoint(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addSegment()
PyObject * VoronoiPy::staticCallback_addSegment (PyObject * self, PyObject * args) static
callback for the addSegment() method
References addSegment(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_colorColinear()
PyObject * VoronoiPy::staticCallback_colorColinear (PyObject * self, PyObject * args) static
callback for the colorColinear() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, colorColinear(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_colorExterior()
PyObject * VoronoiPy::staticCallback_colorExterior (PyObject * self, PyObject * args) static
callback for the colorExterior() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, colorExterior(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_colorTwins()
PyObject * VoronoiPy::staticCallback_colorTwins (PyObject * self, PyObject * args) static
callback for the colorTwins() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, colorTwins(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_construct()
PyObject * VoronoiPy::staticCallback_construct (PyObject * self, PyObject * args) static
callback for the construct() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, construct(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getCells()
PyObject * VoronoiPy::staticCallback_getCells (PyObject * self, void * closure) static
getter callback for the Cells attribute
References Base::BaseExceptionFreeCADError, getCells(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getEdges()
PyObject * VoronoiPy::staticCallback_getEdges (PyObject * self, void * closure) static
getter callback for the Edges attribute
References Base::BaseExceptionFreeCADError, getEdges(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPoints()
PyObject * VoronoiPy::staticCallback_getPoints (PyObject * self, PyObject * args) static
callback for the getPoints() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPoints(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSegments()
PyObject * VoronoiPy::staticCallback_getSegments (PyObject * self, PyObject * args) static
callback for the getSegments() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getSegments(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVertices()
PyObject * VoronoiPy::staticCallback_getVertices (PyObject * self, void * closure) static
getter callback for the Vertices attribute
References Base::BaseExceptionFreeCADError, getVertices(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_numCells()
PyObject * VoronoiPy::staticCallback_numCells (PyObject * self, PyObject * args) static
callback for the numCells() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), numCells(), and Base::PyObjectBase::PyObjectBase().
staticCallback_numEdges()
PyObject * VoronoiPy::staticCallback_numEdges (PyObject * self, PyObject * args) static
callback for the numEdges() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), numEdges(), and Base::PyObjectBase::PyObjectBase().
staticCallback_numPoints()
PyObject * VoronoiPy::staticCallback_numPoints (PyObject * self, PyObject * args) static
callback for the numPoints() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), numPoints(), and Base::PyObjectBase::PyObjectBase().
staticCallback_numSegments()
PyObject * VoronoiPy::staticCallback_numSegments (PyObject * self, PyObject * args) static
callback for the numSegments() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), numSegments(), and Base::PyObjectBase::PyObjectBase().
staticCallback_numVertices()
PyObject * VoronoiPy::staticCallback_numVertices (PyObject * self, PyObject * args) static
callback for the numVertices() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), numVertices(), and Base::PyObjectBase::PyObjectBase().
staticCallback_resetColor()
PyObject * VoronoiPy::staticCallback_resetColor (PyObject * self, PyObject * args) static
callback for the resetColor() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), resetColor(), and Base::PyObjectBase::startNotify().
staticCallback_setCells()
int VoronoiPy::staticCallback_setCells (PyObject * self, PyObject * value, void * closure) static
setter callback for the Cells attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setEdges()
int VoronoiPy::staticCallback_setEdges (PyObject * self, PyObject * value, void * closure) static
setter callback for the Edges attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setVertices()
int VoronoiPy::staticCallback_setVertices (PyObject * self, PyObject * value, void * closure) static
setter callback for the Vertices attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
Member Data Documentation
GetterSetter
PyGetSetDef VoronoiPy::GetterSetter static
Initial value:
= {
    {"Cells",
        (getter) staticCallback_getCells,
        (setter) staticCallback_setCells,
        "List of all cells of the voronoi diagram",
        NULL
    },
    {"Edges",
        (getter) staticCallback_getEdges,
        (setter) staticCallback_setEdges,
        "List of all edges of the voronoi diagram",
        NULL
    },
    {"Vertices",
        (getter) staticCallback_getVertices,
        (setter) staticCallback_setVertices,
        "List of all vertices of the voronoi diagram",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of VoronoiPy.
Methods
PyMethodDef VoronoiPy::Methods static
Methods structure of VoronoiPy.
Type
PyTypeObject VoronoiPy::Type static
Type structure of VoronoiPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/VoronoiPy.h
Sources/FreeCAD/src/Mod/Path/App/VoronoiPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/VoronoiPy.cpp