FreeCAD: Sandbox::WorkerThread Class Reference
Sandbox::WorkerThread Class Reference
#include <DocumentThread.h>
Public Member Functions
WorkerThread (QObject *parent=0)
~WorkerThread ()
Protected Member Functions
void run ()
Constructor & Destructor Documentation
WorkerThread()
WorkerThread::WorkerThread (QObject * parent = 0)
~WorkerThread()
WorkerThread::~WorkerThread ()
Member Function Documentation
run()
void WorkerThread::run (void) protected
References Base::SequencerLauncher::next().
Referenced by femexamples.examplesgui.FemExamples::clicked(), and femsolver.task.Task::protector().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sandbox/App/DocumentThread.h
Sources/FreeCAD/src/Mod/Sandbox/App/DocumentThread.cpp