FreeCAD: StdMeshers_PropagOfDistribution Class Reference
StdMeshers_PropagOfDistribution Class Reference
Propagation Of Distribution hypothesis.
#include <StdMeshers_Propagation.hxx>
Public Member Functions
StdMeshers_PropagOfDistribution (int hypId, int studyId, SMESH_Gen *gen)
Public Member Functions inherited from StdMeshers_Propagation
virtual std::istream & LoadFrom (std::istream &load)
virtual std::ostream & SaveTo (std::ostream &save)
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)
Initialize my parameter values by the mesh built on the geometry.
StdMeshers_Propagation (int hypId, int studyId, SMESH_Gen *gen)
virtual ~StdMeshers_Propagation ()
Public Member Functions inherited from SMESH_Hypothesis
void ClearParameters ()
virtual bool DataDependOnParams () const
The returned value is used by NotifySubMeshesHypothesisModification() to decide to call subMesh->AlgoStateEngine(MODIF_HYP, hyp) or not if subMesh is ready to be computed (algo+hyp==OK) but not yet computed. True result is reasonable for example if EventListeners depend on parameters of hypothesis.
virtual int GetDim () const
SMESH_Gen * GetGen () const
char * GetLastParameters () const
virtual const char * GetLibName () const
SMESH_Mesh * GetMeshByPersistentID (int id)
Find a mesh with given persistent ID.
char * GetParameters () const
virtual int GetShapeType () const
int GetStudyId () const
virtual bool IsAuxiliary () const
Return true if me is an auxiliary hypothesis.
virtual void NotifySubMeshesHypothesisModification ()
void SetLastParameters (const char *theParameters)
void SetLibName (const char *theLibName)
void SetParameters (const char *theParameters)
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)=0
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)=0
Initialize my parameter values by the mesh built on the geometry.
SMESH_Hypothesis (int hypId, int studyId, SMESH_Gen *gen)
virtual ~SMESH_Hypothesis ()
Public Member Functions inherited from SMESHDS_Hypothesis
int GetID () const
const char * GetName () const
int GetType () const
bool IsSameName (const SMESHDS_Hypothesis &other) const
Compare types of hypotheses.
virtual std::istream & LoadFrom (std::istream &load)=0
bool operator!= (const SMESHDS_Hypothesis &other) const
virtual bool operator== (const SMESHDS_Hypothesis &other) const
virtual std::ostream & SaveTo (std::ostream &save)=0
SMESHDS_Hypothesis (int hypId)
virtual ~SMESHDS_Hypothesis ()
Static Public Member Functions
static std::string GetName ()
Static Public Member Functions inherited from StdMeshers_Propagation
static const SMESH_HypoFilter & GetFilter ()
Returns a filter selecting both StdMeshers_Propagation and StdMeshers_PropagOfDistribution hypotheses.
static std::string GetName ()
static TopoDS_Edge GetPropagationSource (SMESH_Mesh &theMesh, const TopoDS_Shape &theEdge, bool &isPropagOfDistribution)
Return an edge from which hypotheses are propagated.
static void SetPropagationMgr (SMESH_subMesh *subMesh)
Set EventListener managing propagation of hypotheses.
Static Public Member Functions inherited from SMESH_Hypothesis
static bool IsStatusFatal (Hypothesis_Status theStatus)
Additional Inherited Members
Public Types inherited from SMESH_Hypothesis
enum Hypothesis_Status {
HYP_OK = 0 , HYP_MISSING , HYP_CONCURENT , HYP_BAD_PARAMETER ,
HYP_HIDDEN_ALGO , HYP_HIDING_ALGO , HYP_UNKNOWN_FATAL , HYP_INCOMPATIBLE ,
HYP_NOTCONFORM , HYP_ALREADY_EXIST , HYP_BAD_DIM , HYP_BAD_SUBSHAPE ,
HYP_BAD_GEOMETRY , HYP_NEED_SHAPE , HYP_INCOMPAT_HYPS
}
Public Types inherited from SMESHDS_Hypothesis
enum hypothesis_type {
PARAM_ALGO , ALGO_0D , ALGO_1D , ALGO_2D ,
ALGO_3D
}
Detailed Description
Propagation Of Distribution hypothesis.
Constructor & Destructor Documentation
StdMeshers_PropagOfDistribution()
StdMeshers_PropagOfDistribution::StdMeshers_PropagOfDistribution (int hypId, int studyId, SMESH_Gen * gen)
References GetName().
Member Function Documentation
GetName()
string StdMeshers_PropagOfDistribution::GetName () static
Referenced by StdMeshers_Regular_1D::CheckHypothesis(), StdMeshers_Propagation::GetFilter(), and StdMeshers_PropagOfDistribution().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_Propagation.hxx
FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_Propagation.cpp