FreeCAD: SMESH_ComputeError Struct Reference
SMESH_ComputeError Struct Reference
Contains an algorithm and description of an occured error.
#include <SMESH_ComputeError.hxx>
Public Member Functions
std::string CommonName () const
bool HasBadElems () const
bool IsCommon () const
bool IsKO () const
bool IsOK () const
SMESH_ComputeError (int error=COMPERR_OK, std::string comment="", const SMESH_Algo *algo=0)
Static Public Member Functions
static SMESH_ComputeErrorPtr New (int error=COMPERR_OK, std::string comment="", const SMESH_Algo *algo=0)
static SMESH_ComputeErrorPtr Worst (SMESH_ComputeErrorPtr er1, SMESH_ComputeErrorPtr er2)
Public Attributes
const SMESH_Algo * myAlgo
std::list< const SMDS_MeshElement * > myBadElements
to explain COMPERR_BAD_INPUT_MESH
std::string myComment
int myName
SMESH_ComputeErrorName or anything algo specific.
Detailed Description
Contains an algorithm and description of an occured error.
Constructor & Destructor Documentation
SMESH_ComputeError()
SMESH_ComputeError::SMESH_ComputeError (int error = COMPERR_OK, std::string comment = "", const SMESH_Algo * algo = 0)
Member Function Documentation
CommonName()
std::string SMESH_ComputeError::CommonName () const
References myName.
HasBadElems()
bool SMESH_ComputeError::HasBadElems () const
IsCommon()
bool SMESH_ComputeError::IsCommon () const
IsKO()
bool SMESH_ComputeError::IsKO () const
IsOK()
bool SMESH_ComputeError::IsOK () const
New()
static SMESH_ComputeErrorPtr SMESH_ComputeError::New (int error = COMPERR_OK, std::string comment = "", const SMESH_Algo * algo = 0) static
Referenced by NETGENPlugin_Mesher::AddSegmentsToMesh(), SMESH_subMesh::checkComputeError(), StdMeshers_ViscousLayers2D::CheckHypothesis(), NETGENPlugin_Mesher::Compute(), StdMeshers_Prism_3D::Compute(), SMESH_subMesh::ComputeStateEngine(), SMESH_subMesh::Evaluate(), SMESH_Algo::GetComputeError(), Driver_Mesh::GetError(), StdMeshers_SMESHBlock::GetError(), StdMeshers_PrismAsBlock::Init(), and NETGENPlugin_Mesher::ReadErrors().
Worst()
SMESH_ComputeErrorPtr SMESH_ComputeError::Worst (SMESH_ComputeErrorPtr er1, SMESH_ComputeErrorPtr er2) static
Referenced by SMESH_subMesh::ComputeStateEngine().
Member Data Documentation
myAlgo
const SMESH_Algo* SMESH_ComputeError::myAlgo
myBadElements
std::list<const SMDS_MeshElement*> SMESH_ComputeError::myBadElements
to explain COMPERR_BAD_INPUT_MESH
myComment
std::string SMESH_ComputeError::myComment
myName
int SMESH_ComputeError::myName
SMESH_ComputeErrorName or anything algo specific.
Referenced by CommonName().
The documentation for this struct was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ComputeError.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/SMESH_TryCatch.cpp