FreeCAD: Gui::Dialog::AboutDialog Class Reference
Gui::Dialog::AboutDialog Class Reference
This widget provides the "About dialog" of an application.
#include <Splashscreen.h>
Classes
class LibraryInfo
Public Member Functions
AboutDialog (bool showLic, QWidget *parent=nullptr)
Constructs an AboutDialog which is a child of 'parent', with the name 'name' and widget flags set to 'WStyle_Customize|WStyle_NoBorder|WType_Modal'.
~AboutDialog ()
Destroys the object and frees any allocated resources.
Protected Slots
void linkActivated (const QUrl &link)
virtual void on_copyButton_clicked ()
Protected Member Functions
QString getAdditionalLicenseInformation () const
void setupLabels ()
void showCollectionInformation ()
void showCredits ()
void showLibraryInformation ()
void showLicenseInformation ()
void showOrHideImage (const QRect &rect)
Detailed Description
This widget provides the "About dialog" of an application.
This shows the current version, the build number and date.
Author
Werner Mayer
Constructor & Destructor Documentation
AboutDialog()
AboutDialog::AboutDialog (bool showLic, QWidget * parent = nullptr)
Constructs an AboutDialog which is a child of 'parent', with the name 'name' and widget flags set to 'WStyle_Customize|WStyle_NoBorder|WType_Modal'.
The dialog will be modal.
References Gui::MainWindow::aboutImage(), Gui::getMainWindow(), Gui::Dialog::Ui_AboutApplication::labelSplashPicture, setupLabels(), Gui::Dialog::Ui_AboutApplication::setupUi(), showCollectionInformation(), showCredits(), showLibraryInformation(), showLicenseInformation(), showOrHideImage(), Gui::MainWindow::splashImage(), and Gui::Dialog::Ui_AboutApplication::tabWidget.
~AboutDialog()
AboutDialog::~AboutDialog ()
Destroys the object and frees any allocated resources.
Member Function Documentation
getAdditionalLicenseInformation()
QString AboutDialog::getAdditionalLicenseInformation () const protected
Referenced by showLicenseInformation().
linkActivated
void AboutDialog::linkActivated (const QUrl & link) protected slot
References Gui::MainWindow::addWindow(), Gui::getMainWindow(), and Gui::Dialog::LicenseView::setSource().
Referenced by showLibraryInformation().
on_copyButton_clicked
void AboutDialog::on_copyButton_clicked () protected virtual slot
References App::Application::Config(), App::Application::getExecutableName(), App::Application::getUserAppDataDir(), App::Meta::Version::str(), and App::Metadata::version().
setupLabels()
void AboutDialog::setupLabels () protected
References App::Application::Config(), Gui::Dialog::Ui_AboutApplication::labelAuthor, Gui::Dialog::Ui_AboutApplication::labelBranch, Gui::Dialog::Ui_AboutApplication::labelBuildBranch, Gui::Dialog::Ui_AboutApplication::labelBuildDate, Gui::Dialog::Ui_AboutApplication::labelBuildHash, Gui::Dialog::Ui_AboutApplication::labelBuildOS, Gui::Dialog::Ui_AboutApplication::labelBuildPlatform, Gui::Dialog::Ui_AboutApplication::labelBuildRevision, Gui::Dialog::Ui_AboutApplication::labelBuildVersion, Gui::Dialog::Ui_AboutApplication::labelHash, and Gui::UrlLabel::setUrl().
Referenced by AboutDialog().
showCollectionInformation()
void AboutDialog::showCollectionInformation () protected
References App::Application::getHelpDir(), and Gui::Dialog::Ui_AboutApplication::tabWidget.
Referenced by AboutDialog().
showCredits()
void AboutDialog::showCredits () protected
References Gui::Dialog::Ui_AboutApplication::tabWidget.
Referenced by AboutDialog().
showLibraryInformation()
void AboutDialog::showLibraryInformation () protected
References draftgeoutils.intersections::connect(), App::Application::getHelpDir(), Gui::Dialog::AboutDialog::LibraryInfo::href, linkActivated(), Gui::Dialog::AboutDialog::LibraryInfo::name, Gui::Dialog::Ui_AboutApplication::tabWidget, Gui::Dialog::AboutDialog::LibraryInfo::url, and Gui::Dialog::AboutDialog::LibraryInfo::version.
Referenced by AboutDialog().
showLicenseInformation()
void AboutDialog::showLicenseInformation () protected
References getAdditionalLicenseInformation(), App::Application::getHelpDir(), Gui::Dialog::Ui_AboutApplication::tabWidget, and Gui::Dialog::Ui_AboutApplication::textBrowserLicense.
Referenced by AboutDialog().
showOrHideImage()
void AboutDialog::showOrHideImage (const QRect & rect) protected
References Gui::Dialog::Ui_AboutApplication::labelSplashPicture.
Referenced by AboutDialog().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/Splashscreen.h
FreeCAD/src/Gui/Splashscreen.cpp