FreeCAD: TechDraw::ewWireList Class Reference
TechDraw::ewWireList Class Reference
#include <EdgeWalker.h>
Public Member Functions
void push_back (ewWire e)
ewWireList removeDuplicateWires ()
int size (void)
Public Attributes
std::vector< ewWire > wires
Member Function Documentation
push_back()
void ewWireList::push_back (ewWire e)
Referenced by TechDraw::edgeVisitor::end_face(), and removeDuplicateWires().
removeDuplicateWires()
ewWireList ewWireList::removeDuplicateWires ()
References push_back().
Referenced by TechDraw::EdgeWalker::getResultNoDups().
size()
int ewWireList::size (void)
Referenced by gzip_utf8.GzipFile::close(), PathScripts.PostUtils.GCodeEditorDialog::done(), and gzip_utf8.GzipFile::write().
Member Data Documentation
wires
std::vector<ewWire> TechDraw::ewWireList::wires
Referenced by TechDraw::EdgeWalker::getResultNoDups(), TechDraw::EdgeWalker::getResultWires(), and PathScripts.PathEngrave.ObjectEngrave::opExecute().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/App/EdgeWalker.h
FreeCAD/src/Mod/TechDraw/App/EdgeWalker.cpp