FreeCAD: PartDesignGui::TaskTransformedMessages Class Reference
PartDesignGui::TaskTransformedMessages Class Reference
#include <TaskTransformedMessages.h>
Public Member Functions
void slotDiagnosis (QString msg)
TaskTransformedMessages (ViewProviderTransformed *transformedView)
~TaskTransformedMessages ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (QWidget *parent=0)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (QWidget *parent=0)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Protected Attributes
Connection connectionDiagnosis
ViewProviderTransformed * transformedView
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskTransformedMessages()
TaskTransformedMessages::TaskTransformedMessages (ViewProviderTransformed * transformedView)
References draftgeoutils.faces::bind(), connectionDiagnosis, PartDesignGui::ViewProviderTransformed::getMessage(), QSint::ActionGroup::groupLayout(), PartDesignGui::ViewProviderTransformed::signalDiagnosis, slotDiagnosis(), and transformedView.
~TaskTransformedMessages()
TaskTransformedMessages::~TaskTransformedMessages ()
References connectionDiagnosis.
Member Function Documentation
slotDiagnosis()
void TaskTransformedMessages::slotDiagnosis (QString msg)
Referenced by TaskTransformedMessages().
Member Data Documentation
connectionDiagnosis
Connection PartDesignGui::TaskTransformedMessages::connectionDiagnosis protected
Referenced by TaskTransformedMessages(), and ~TaskTransformedMessages().
transformedView
ViewProviderTransformed* PartDesignGui::TaskTransformedMessages::transformedView protected
Referenced by TaskTransformedMessages().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/PartDesign/Gui/TaskTransformedMessages.h
Sources/FreeCAD/src/Mod/PartDesign/Gui/TaskTransformedMessages.cpp