FreeCAD: PartDesignGui::ViewProviderBody Class Reference
PartDesignGui::ViewProviderBody Class Reference
ViewProvider of the Body feature This class manages the visual appearance of the features in the Body feature.
#include <ViewProviderBody.h>
Public Member Functions
virtual void attach (App::DocumentObject *) override
Attaches the document object to this view provider.
virtual bool canDropObject (App::DocumentObject *) const override
Check whether the object can be dropped to the view provider by drag and drop.
virtual bool canDropObjects () const override
Check whether objects can be added to the view provider by drag and drop.
virtual bool doubleClicked (void) override
is called by the tree if the user double clicks on the object
virtual void dropObject (App::DocumentObject *) override
Add an object to the view provider by drag and drop.
SbBox3f getBoundBox ()
Return the bounding box of visible features.
virtual std::vector< std::string > getDisplayModes (void) const override
returns a list of all possible modes
virtual void onChanged (const App::Property *prop) override
unify children visuals
virtual bool onDelete (const std::vector< std::string > &) override
Get called if the object is about to get deleted.
virtual void setDisplayMode (const char *ModeName) override
set the display mode
virtual void setOverrideMode (const std::string &mode) override
Overrides the display mode with mode.
virtual void setupContextMenu (QMenu *menu, QObject *receiver, const char *member) override
set up the context-menu with the supported edit modes
virtual void updateData (const App::Property *prop) override
Update the children's highlighting when triggered.
void updateOriginDatumSize ()
Update the sizes of origin and datums.
ViewProviderBody ()
constructor
virtual ~ViewProviderBody ()
destructor
Public Member Functions inherited from PartGui::ViewProviderPart
ViewProviderPart ()
constructor
virtual ~ViewProviderPart ()
destructor
Public Member Functions inherited from PartGui::ViewProviderPartExt
bool changeFaceColors ()
If no other task is pending it opens a dialog to allow to change face colors.
void reload ()
Update the view representation.
ViewProviderPartExt ()
constructor
virtual ~ViewProviderPartExt ()
destructor
virtual bool useNewSelectionModel (void) const override
indicates if the ViewProvider use the new Selection model
virtual std::string getElement (const SoDetail *) const override
return a hit element to the selection path or 0
virtual SoDetail * getDetail (const char *) const override
return the coin node detail of the subelement
virtual std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const override
virtual std::vector< Base::Vector3d > getSelectionShape (const char *Element) const override
return the highlight lines for a given element or the whole shape
void setHighlightedFaces (const std::vector< App::Color > &colors)
void setHighlightedFaces (const std::vector< App::Material > &colors)
void unsetHighlightedFaces ()
void setHighlightedEdges (const std::vector< App::Color > &colors)
void unsetHighlightedEdges ()
void setHighlightedPoints (const std::vector< App::Color > &colors)
void unsetHighlightedPoints ()
virtual std::map< std::string, App::Color > getElementColors (const char *element=0) const override
virtual bool isUpdateForced () const override
virtual void forceUpdate (bool enable=true) override
virtual bool allowOverride (const App::DocumentObject &) const override
Allow this class to be used as an override for the original view provider of the given object.
Public Member Functions inherited from Gui::ViewProviderGeometryObject
SoPickedPoint * getPickedPoint (const SbVec2s &pos, const View3DInventorViewer &viewer) const
This method is provided for convenience and does basically the same as getPickedPoints() unless that only the closest point to the camera will be picked.
SoPickedPointList getPickedPoints (const SbVec2s &pos, const View3DInventorViewer &viewer, bool pickAll=false) const
Returns a list of picked points from the geometry under getRoot().
bool isSelectable (void) const
ViewProviderGeometryObject ()
constructor.
virtual ~ViewProviderGeometryObject ()
destructor.
virtual void showBoundingBox (bool)
Public Member Functions inherited from Gui::ViewProviderDragger
ViewProviderDragger ()
constructor.
virtual ~ViewProviderDragger ()
destructor.
virtual ViewProvider * startEditing (int ModNum=0) override
Public Member Functions inherited from Gui::ViewProviderDocumentObject
virtual bool canDelete (App::DocumentObject *obj) const override
Asks the view provider if the given object can be deleted.
virtual bool canDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const override
Query object dropping with full qualified name.
virtual bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const override
return the coin node detail and path to the node of the subname
Gui::Document * getDocument () const
Get the GUI document to this ViewProvider object.
virtual bool getElementPicked (const SoPickedPoint *, std::string &subname) const override
return a hit element given the picked point which contains the full node path
App::DocumentObject * getObject (void) const
Get the object of this ViewProvider object.
PyObject * getPyObject () override
Get the python wrapper for that ViewProvider.
virtual void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const override
Get a list of TaskBoxes associated with this object.
virtual const char * getTransactionText () const override
Is called by the tree if the user double clicks on the object.
virtual void hide (void) override
Hide the object in the view.
virtual void reattach (App::DocumentObject *)
virtual int replaceObject (App::DocumentObject *, App::DocumentObject *) override
Replace an object to the view provider by drag and drop.
void setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
virtual void show (void) override
Show the object in the view.
virtual bool showInTree () const override
Tell the tree view if this object should appear there.
virtual void update (const App::Property *) override
update the content of the ViewProvider this method have to implement the recalculation of the ViewProvider.
void updateView ()
Run a redraw.
ViewProviderDocumentObject ()
constructor.
virtual ~ViewProviderDocumentObject ()
destructor.
virtual void startRestoring ()
virtual void finishRestoring ()
virtual bool removeDynamicProperty (const char *prop) override
virtual App::Property * addDynamicProperty (const char *type, const char *name=0, const char *group=0, const char *doc=0, short attr=0, bool ro=false, bool hidden=false) override
virtual ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=0, bool recursive=false) const
Return the linked view object.
virtual std::string getFullName () const override
void setShowable (bool enable)
bool isShowable () const
Public Member Functions inherited from Gui::ViewProvider
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual std::vector< App::DocumentObject * > claimChildren3D (void) const
deliver the children belonging to this object this method is used to deliver the objects to the 3DView which should be grouped under its scene graph.
SoSeparator * getAnnotation (void)
virtual SoSeparator * getBackRoot (void) const
virtual SoGroup * getChildRoot (void) const
virtual SoSeparator * getFrontRoot (void) const
SoSwitch * getModeSwitch (void) const
virtual SoSeparator * getRoot (void) const
SoTransform * getTransformNode () const
ViewProvider ()
constructor.
virtual ~ViewProvider ()
destructor.
int partialRender (const std::vector< std::string > &subelements, bool clear)
partial rendering setup
Base::BoundBox3d getBoundingBox (const char *subname=0, bool transform=true, MDIView *view=0) const
Return the bound box of this view object.
virtual void beforeDelete ()
Called before deletion.
virtual bool canDragObjects () const
Check whether children can be removed from the view provider by drag and drop.
virtual bool canDragObject (App::DocumentObject *) const
Check whether the object can be removed from the view provider by drag and drop.
virtual void dragObject (App::DocumentObject *)
Remove a child from the view provider by drag and drop.
virtual bool canDragAndDropObject (App::DocumentObject *) const
Return false to force drop only operation for a given object.
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
Add an object with full qualified name to the view provider by drag and drop.
virtual bool canRemoveChildrenFromRoot () const
Tell the tree view to remove children items from the tree root.
std::string getActiveDisplayMode (void) const
virtual const char * getDefaultDisplayMode () const
get the default display mode
virtual bool isShow (void) const
checks whether the view provider is visible or not
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
const std::string getOverrideMode ()
virtual bool keyPressed (bool pressed, int key)
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
virtual bool mouseMove (const SbVec2s &cursorPos, View3DInventorViewer *viewer)
is called when the provider is in edit and the mouse is moved
virtual bool mouseButtonPressed (int button, bool pressed, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
is called when the Provider is in edit and the mouse is clicked
virtual QIcon getIcon (void) const
deliver the icon shown in the tree view
virtual std::vector< App::DocumentObject * > claimChildren (void) const
deliver the children belonging to this object this method is used to deliver the objects to the tree framework which should be grouped under its label.
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
bool isEditing () const
void finishEditing ()
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
virtual MDIView * getMDIView () const
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
TransactionalObject (void)
Constructor.
virtual ~TransactionalObject ()
Public Member Functions inherited from App::ExtensionContainer
ExtensionIterator extensionBegin ()
ExtensionContainer ()
ExtensionIterator extensionEnd ()
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
void registerExtension (Base::Type extension, App::Extension *ext)
virtual ~ExtensionContainer ()
virtual Property * getPropertyByName (const char *name) const override
find a property by its name
virtual const char * getPropertyName (const Property *prop) const override
get the name of a property
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
virtual void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
virtual short getPropertyType (const Property *prop) const override
get the Type of a Property
virtual short getPropertyType (const char *name) const override
get the Type of a named Property
virtual const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
Public Member Functions inherited from App::PropertyContainer
virtual App::Property * getDynamicPropertyByName (const char *name) const
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
const char * getPropertyPrefix () const
bool isHidden (const char *name) const
check if the named property is hidden
bool isHidden (const Property *prop) const
check if the property is hidden
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isReadOnly (const Property *prop) const
check if the property is read-only
PropertyContainer ()
A constructor.
void setPropertyPrefix (const char *prefix)
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
virtual ~PropertyContainer ()
A destructor.
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Gui::ViewProviderOriginGroupExtension
virtual void extensionAttach (App::DocumentObject *pcObject) override
virtual std::vector< App::DocumentObject * > extensionClaimChildren (void) const override
virtual std::vector< App::DocumentObject * > extensionClaimChildren3D (void) const override
virtual void extensionUpdateData (const App::Property *prop) override
void updateOriginSize ()
ViewProviderOriginGroupExtension (void)
Constructor.
virtual ~ViewProviderOriginGroupExtension ()
Public Member Functions inherited from Gui::ViewProviderGeoFeatureGroupExtension
virtual void extensionFinishRestoring () override
virtual SoGroup * extensionGetChildRoot (void) const override
virtual std::vector< std::string > extensionGetDisplayModes (void) const override
virtual void extensionHide (void) override
Hide the object in the view: suppresses behavior of DocumentObjectGroup.
virtual void extensionSetDisplayMode (const char *ModeName) override
virtual void extensionShow (void) override
Show the object in the view: suppresses behavior of DocumentObjectGroup.
ViewProviderGeoFeatureGroupExtension (void)
Constructor.
virtual ~ViewProviderGeoFeatureGroupExtension ()
Public Member Functions inherited from Gui::ViewProviderGroupExtension
virtual bool extensionCanDragObject (App::DocumentObject *) const override
virtual bool extensionCanDragObjects () const override
virtual bool extensionCanDropObject (App::DocumentObject *) const override
virtual bool extensionCanDropObjects () const override
virtual void extensionDragObject (App::DocumentObject *) override
virtual void extensionDropObject (App::DocumentObject *) override
virtual bool extensionOnDelete (const std::vector< std::string > &) override
ViewProviderGroupExtension (void)
Constructor.
virtual ~ViewProviderGroupExtension ()
Public Member Functions inherited from Gui::ViewProviderExtension
virtual void extensionBeforeDelete ()
virtual bool extensionCanDragAndDropObject (App::DocumentObject *) const
virtual bool extensionCanDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const
virtual std::string extensionDropObjectEx (App::DocumentObject *obj, App::DocumentObject *, const char *, const std::vector< std::string > &)
virtual SoSeparator * extensionGetBackRoot (void) const
virtual bool extensionGetDetailPath (const char *, SoFullPath *, SoDetail *&) const
virtual bool extensionGetElementPicked (const SoPickedPoint *, std::string &) const
virtual SoSeparator * extensionGetFrontRoot (void) const
virtual QIcon extensionMergeOverlayIcons (const QIcon &orig) const
virtual void extensionModeSwitchChange (void)
virtual void extensionReattach (App::DocumentObject *)
virtual int extensionReplaceObject (App::DocumentObject *, App::DocumentObject *)
virtual void extensionSetupContextMenu (QMenu *, QObject *, const char *)
virtual void extensionStartRestoring ()
Gui::ViewProviderDocumentObject * getExtendedViewProvider ()
const Gui::ViewProviderDocumentObject * getExtendedViewProvider () const
virtual PyObject * getExtensionPyObject ()
bool ignoreOverlayIcon () const
void setIgnoreOverlayIcon (bool on)
ViewProviderExtension ()
virtual ~ViewProviderExtension ()
Public Member Functions inherited from App::Extension
Extension ()
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
virtual void initExtension (App::ExtensionContainer *obj)
bool isPythonExtension ()
std::string name () const
virtual ~Extension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Public Attributes
App::PropertyEnumeration DisplayModeBody
Public Attributes inherited from PartGui::ViewProviderPartExt
App::PropertyAngle AngularDeflection
App::PropertyBool ControlPoints
App::PropertyFloatConstraint Deviation
App::PropertyColorList DiffuseColor
App::PropertyEnumeration DrawStyle
App::PropertyEnumeration Lighting
App::PropertyColor LineColor
App::PropertyColorList LineColorArray
App::PropertyMaterial LineMaterial
App::PropertyFloatConstraint LineWidth
App::PropertyColor PointColor
App::PropertyColorList PointColorArray
App::PropertyMaterial PointMaterial
App::PropertyFloatConstraint PointSize
Public Attributes inherited from Gui::ViewProviderGeometryObject
App::PropertyBool BoundingBox
App::PropertyBool Selectable
App::PropertyColor ShapeColor
App::PropertyMaterial ShapeMaterial
App::PropertyPercent Transparency
Public Attributes inherited from Gui::ViewProviderDocumentObject
App::PropertyEnumeration DisplayMode
App::PropertyEnumeration OnTopWhenSelected
App::PropertyEnumeration SelectionStyle
App::PropertyBool ShowInTree
App::PropertyBool Visibility
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
Protected Member Functions
void setVisualBodyMode (bool bodymode)
Set Feature viewprovider into visual body mode.
void slotChangedObjectApp (const App::DocumentObject &obj, const App::Property &prop)
void slotChangedObjectGui (const Gui::ViewProviderDocumentObject &obj, const App::Property &prop)
void unifyVisualProperty (const App::Property *prop)
Copy over all visual properties to the child features.
Protected Member Functions inherited from PartGui::ViewProviderPart
void applyColor (const Part::ShapeHistory &hist, const std::vector< App::Color > &colBase, std::vector< App::Color > &colBool)
void applyTransparency (const float &transparency, std::vector< App::Color > &colors)
Protected Member Functions inherited from PartGui::ViewProviderPartExt
bool setEdit (int ModNum) override
is called by the document when the provider goes in edit mode
void unsetEdit (int ModNum) override
is called when you lose the edit mode
bool loadParameter ()
void updateVisual ()
void getNormals (const TopoDS_Face &theFace, const Handle(Poly_Triangulation)&aPolyTri, TColgp_Array1OfDir &theNormals)
Protected Member Functions inherited from Gui::ViewProviderGeometryObject
void setSelectable (bool Selectable=true)
virtual unsigned long getBoundColor () const
Protected Member Functions inherited from Gui::ViewProviderDragger
void setEditViewer (View3DInventorViewer *, int ModNum) override
adjust viewer settings when editing a view provider
void unsetEditViewer (View3DInventorViewer *) override
restores viewer settings when leaving editing mode
Protected Member Functions inherited from Gui::ViewProviderDocumentObject
Gui::MDIView * getActiveView () const
Gui::MDIView * getEditingView () const
Gui::MDIView * getInventorView () const
Gui::MDIView * getViewOfNode (SoNode *node) const
virtual void onBeforeChange (const App::Property *prop) override
get called before the value is changed
SoNode * findFrontRootOfType (const SoType &type) const
Searches in all view providers that are attached to an object that is part of the same document as the object this view provider is attached to for an front root of type.
virtual bool isAttachedToDocument () const override
virtual const char * detachFromDocument () override
virtual void onPropertyStatusChanged (const App::Property &prop, unsigned long oldStatus) override
get called when a property status has changed
virtual void setModeSwitch () override
Turn on mode switch.
Protected Member Functions inherited from Gui::ViewProvider
virtual QIcon mergeOverlayIcons (const QIcon &orig) const
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
bool checkRecursion (SoNode *)
Helper method to check that the node is valid, i.e.
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
Helper method to get picked entities while editing.
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
Helper method to get picked entities while editing.
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData (void) const
virtual void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container.
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
Protected Member Functions inherited from Gui::ViewProviderOriginGroupExtension
void slotChangedObjectApp (const App::DocumentObject &obj)
void slotChangedObjectGui (const Gui::ViewProviderDocumentObject &obj)
Protected Member Functions inherited from App::Extension
virtual void extensionOnChanged (const Property *p)
void initExtensionType (Base::Type type)
Additional Inherited Members
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0, Transform, Cutting, Color }
Public Types inherited from App::ExtensionContainer
typedef std::map< Base::Type, App::Extension * >::iterator ExtensionIterator
Static Public Member Functions inherited from Gui::ViewProviderDragger
static void updateTransform (const Base::Placement &from, SoTransform *to)
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Static Protected Member Functions inherited from App::Extension
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=0)
Protected Attributes inherited from PartGui::ViewProviderPartExt
SoMaterialBinding * pcFaceBind
SoMaterialBinding * pcLineBind
SoMaterialBinding * pcPointBind
SoMaterial * pcLineMaterial
SoMaterial * pcPointMaterial
SoDrawStyle * pcLineStyle
SoDrawStyle * pcPointStyle
SoShapeHints * pShapeHints
SoCoordinate3 * coords
SoBrepFaceSet * faceset
SoNormal * norm
SoNormalBinding * normb
SoBrepEdgeSet * lineset
SoBrepPointSet * nodeset
bool VisualTouched
bool NormalsFromUV
Protected Attributes inherited from Gui::ViewProviderGeometryObject
SoMaterial * pcShapeMaterial
SoFCBoundingBox * pcBoundingBox
SoSwitch * pcBoundSwitch
SoBaseColor * pcBoundColor
Protected Attributes inherited from Gui::ViewProviderDragger
SoFCCSysDragger * csysDragger = nullptr
Protected Attributes inherited from Gui::ViewProviderDocumentObject
App::DocumentObject * pcObject
Gui::Document * pcDocument
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation
The root separator for annotations.
ViewProviderPy * pyViewObject
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Protected Attributes inherited from Gui::ViewProviderGeoFeatureGroupExtension
SoGroup * pcGroupChildren
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::Object ExtensionPythonObject
Detailed Description
ViewProvider of the Body feature This class manages the visual appearance of the features in the Body feature.
That means while editing all visible features are shown. If the Body is not active it shows only the result shape (tip).
Author
jriegel
Constructor & Destructor Documentation
ViewProviderBody()
ViewProviderBody::ViewProviderBody ()
constructor
References App::Extension::initExtension().
~ViewProviderBody()
ViewProviderBody::~ViewProviderBody () virtual
destructor
Member Function Documentation
attach()
void ViewProviderBody::attach (App::DocumentObject * pcObject) override virtual
Attaches the document object to this view provider.
Reimplemented from PartGui::ViewProviderPartExt.
References draftgeoutils.faces::bind(), DisplayModeBody, Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::Application::Instance, onChanged(), Gui::ViewProviderDocumentObject::pcObject, App::Document::signalChangedObject, Gui::Document::signalChangedObject, slotChangedObjectApp(), and slotChangedObjectGui().
canDropObject()
bool ViewProviderBody::canDropObject (App::DocumentObject * obj) const override virtual
Check whether the object can be dropped to the view provider by drag and drop.
Reimplemented from Gui::ViewProvider.
References PartDesign::Body::findBodyOf(), PartDesignGui::getActivePart(), Base::Persistence::getClassTypeId(), and App::Part::getPartOfObject().
canDropObjects()
bool ViewProviderBody::canDropObjects () const override virtual
Check whether objects can be added to the view provider by drag and drop.
Reimplemented from Gui::ViewProvider.
References Part::BodyBase::BaseFeature, Gui::ViewProviderDocumentObject::getObject(), and App::Property::testStatus().
doubleClicked()
bool ViewProviderBody::doubleClicked (void) override virtual
is called by the tree if the user double clicks on the object
Reimplemented from PartGui::ViewProviderPart.
References Gui::Application::activeDocument(), App::GetApplication(), Gui::ViewProviderDocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), Gui::Command::getObjectCmd(), App::Part::getPartOfObject(), Gui::Command::Gui, and Gui::Application::Instance.
Referenced by setupContextMenu().
dropObject()
void ViewProviderBody::dropObject (App::DocumentObject * obj) override virtual
Add an object to the view provider by drag and drop.
Reimplemented from Gui::ViewProvider.
References PartDesign::Body::addObject(), PartDesign::Body::addObjects(), Part::BodyBase::BaseFeature, PartDesignGui::collectMovableDependencies(), PartDesign::Body::findBodyOf(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyLink::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::GroupExtension::Group, Gui::Application::hideViewProvider(), Gui::Application::Instance, PartDesign::Body::isAllowed(), PartDesignGui::isFeatureMovable(), draftfunctions.move::move(), and App::PropertyLink::setValue().
getBoundBox()
SbBox3f PartDesignGui::ViewProviderBody::getBoundBox ()
Return the bounding box of visible features.
Note
datums are counted as their base point only
getDisplayModes()
std::vector< std::string > ViewProviderBody::getDisplayModes (void) const override virtual
returns a list of all possible modes
Reimplemented from PartGui::ViewProviderPartExt.
onChanged()
void ViewProviderBody::onChanged (const App::Property * prop) override virtual
unify children visuals
Reimplemented from PartGui::ViewProviderPartExt.
References Base::Console(), Gui::ViewProviderDocumentObject::DisplayMode, DisplayModeBody, Gui::ViewProviderDocumentObject::getObject(), Gui::ViewProvider::getOverrideMode(), App::PropertyEnumeration::getValue(), App::PropertyEnumeration::getValueAsString(), Base::ConsoleSingleton::Message(), PartGui::ViewProviderPartExt::onChanged(), Gui::ViewProvider::overrideMode, Gui::ViewProvider::setDisplayMaskMode(), Gui::ViewProvider::setOverrideMode(), App::Property::touch(), unifyVisualProperty(), and Gui::ViewProviderDocumentObject::Visibility.
Referenced by attach(), ArchSite.Compass::buildCoordinates(), and ArchAxis.CommandArchGrid::IsActive().
onDelete()
bool ViewProviderBody::onDelete (const std::vector< std::string > & subNames) override virtual
Get called if the object is about to get deleted.
Here you can delete other objects, switch their visibility or prevent the deletion of the object.
Parameters
subNames list of selected subelements
Returns
true if the deletion is approved by the view provider.
Reimplemented from Gui::ViewProvider.
References Gui::ViewProviderDocumentObject::getObject().
setDisplayMode()
void ViewProviderBody::setDisplayMode (const char * ModeName) override virtual
set the display mode
If you add new viewing modes in getDisplayModes() then you need to reimplement also seDisplaytMode() to handle these new modes by setting the appropriate display mode.
Reimplemented from PartGui::ViewProviderPartExt.
References DisplayModeBody, App::PropertyEnumeration::getValue(), and PartGui::ViewProviderPartExt::setDisplayMode().
setOverrideMode()
void ViewProviderBody::setOverrideMode (const std::string & mode) override virtual
Overrides the display mode with mode.
Reimplemented from Gui::ViewProvider.
References DisplayModeBody, App::PropertyEnumeration::getValue(), Gui::ViewProvider::overrideMode, and Gui::ViewProvider::setOverrideMode().
setupContextMenu()
void ViewProviderBody::setupContextMenu (QMenu * menu, QObject * receiver, const char * method) override virtual
set up the context-menu with the supported edit modes
Reimplemented from PartGui::ViewProviderPartExt.
References draftgeoutils.faces::bind(), doubleClicked(), and Gui::ViewProviderDragger::setupContextMenu().
setVisualBodyMode()
void ViewProviderBody::setVisualBodyMode (bool bodymode) protected
Set Feature viewprovider into visual body mode.
References Base::Persistence::getClassTypeId(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Gui::Document::getViewProvider(), App::GroupExtension::Group, Gui::Application::Instance, Gui::ViewProviderDocumentObject::pcObject, and PartDesignGui::ViewProvider::setBodyMode().
Referenced by updateData().
slotChangedObjectApp()
void ViewProviderBody::slotChangedObjectApp (const App::DocumentObject & obj, const App::Property & prop) protected
References App::GetApplication(), Base::Persistence::getClassTypeId(), Gui::ViewProviderDocumentObject::getObject(), App::OriginGroupExtension::hasObject(), Gui::ViewProvider::isRestoring(), App::GeoFeature::Placement, Part::Feature::Shape, and updateOriginDatumSize().
Referenced by attach().
slotChangedObjectGui()
void ViewProviderBody::slotChangedObjectGui (const Gui::ViewProviderDocumentObject & obj, const App::Property & prop) protected
References Base::Persistence::getClassTypeId(), Gui::ViewProviderDocumentObject::getObject(), App::OriginGroupExtension::hasObject(), Base::BaseClass::isDerivedFrom(), updateOriginDatumSize(), and Gui::ViewProviderDocumentObject::Visibility.
Referenced by attach().
unifyVisualProperty()
void ViewProviderBody::unifyVisualProperty (const App::Property * prop) protected
Copy over all visual properties to the child features.
References PartGui::ViewProviderPartExt::DiffuseColor, DisplayModeBody, Base::Persistence::getClassTypeId(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), App::Property::getName(), Gui::ViewProviderDocumentObject::getObject(), App::ExtensionContainer::getPropertyByName(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Gui::Document::getViewProvider(), App::GroupExtension::Group, Gui::Application::Instance, Gui::ViewProvider::isRestoring(), PartGui::ViewProviderPartExt::LineColorArray, App::Property::Paste(), Gui::ViewProviderDocumentObject::pcObject, PartGui::ViewProviderPartExt::PointColorArray, Gui::ViewProviderGeometryObject::Selectable, and Gui::ViewProviderDocumentObject::Visibility.
Referenced by onChanged().
updateData()
void ViewProviderBody::updateData (const App::Property * prop) override virtual
Update the children's highlighting when triggered.
Reimplemented from PartGui::ViewProviderPartExt.
References Part::BodyBase::BaseFeature, Base::Persistence::getClassTypeId(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyLink::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Gui::Application::getViewProvider(), App::GroupExtension::Group, Gui::Application::Instance, Base::BaseClass::isDerivedFrom(), setVisualBodyMode(), Part::BodyBase::Tip, PartGui::ViewProviderPartExt::updateData(), and updateOriginDatumSize().
Referenced by PathScripts.PathJobDlg.JobCreate::exec_(), PathScripts.PathOpGui.TaskPanelPage::pageUpdateData(), and PathScripts.PathSetupSheetGui.OpTaskPanel::setupUi().
updateOriginDatumSize()
void ViewProviderBody::updateOriginDatumSize ()
Update the sizes of origin and datums.
References Base::Console(), Gui::ViewProviderOrigin::defaultSize(), Base::ConsoleSingleton::Error(), Base::Persistence::getClassTypeId(), Gui::ViewProviderDocumentObject::getDocument(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::Document::getDocument(), Gui::ViewProviderExtension::getExtendedViewProvider(), Part::BodyBase::getFullModel(), Gui::ViewProviderDocumentObject::getObject(), App::OriginGroupExtension::getOrigin(), PartDesignGui::ViewProviderDatum::getRelevantBoundBox(), Gui::ViewProvider::getRoot(), Gui::Document::getViewOfViewProvider(), Gui::Application::getViewProvider(), Gui::Application::Instance, Base::BaseClass::isDerivedFrom(), App::Document::Restoring, PartDesignGui::ViewProviderDatum::setExtents(), App::PropertyVector::setValue(), Gui::ViewProviderOrigin::Size, App::Document::testStatus(), OfflineRenderingUtils::viewer(), and Base::Exception::what().
Referenced by slotChangedObjectApp(), slotChangedObjectGui(), and updateData().
Member Data Documentation
DisplayModeBody
App::PropertyEnumeration PartDesignGui::ViewProviderBody::DisplayModeBody
Referenced by attach(), onChanged(), setDisplayMode(), setOverrideMode(), and unifyVisualProperty().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/PartDesign/Gui/ViewProviderBody.h
Sources/FreeCAD/src/Mod/PartDesign/Gui/ViewProviderBody.cpp