FreeCAD: GCS::ArcOfParabola Class Reference
GCS::ArcOfParabola Class Reference
#include <Geo.h>
Public Member Functions
ArcOfParabola ()
virtual ArcOfParabola * Copy ()
virtual int PushOwnParams (VEC_pD &pvec)
virtual void ReconstructOnNewPvec (VEC_pD &pvec, int &cnt)
virtual ~ArcOfParabola ()
Public Member Functions inherited from GCS::Parabola
DeriVector2 CalculateNormal (Point &p, double *derivparam=0)
Parabola ()
virtual DeriVector2 Value (double u, double du, double *derivparam=0)
Value: returns point (vector) given the value of parameter.
virtual ~Parabola ()
Public Member Functions inherited from GCS::Curve
virtual ~Curve ()
Public Attributes
Point end
double * endAngle
Point start
double * startAngle
Public Attributes inherited from GCS::Parabola
Point focus1
Point vertex
Constructor & Destructor Documentation
ArcOfParabola()
GCS::ArcOfParabola::ArcOfParabola ()
References endAngle, and startAngle.
Referenced by Copy().
~ArcOfParabola()
virtual GCS::ArcOfParabola::~ArcOfParabola () virtual
Member Function Documentation
Copy()
ArcOfParabola * GCS::ArcOfParabola::Copy (void) virtual
Reimplemented from GCS::Parabola.
References ArcOfParabola().
PushOwnParams()
int GCS::ArcOfParabola::PushOwnParams (VEC_pD & pvec) virtual
Reimplemented from GCS::Parabola.
References endAngle, GCS::Parabola::PushOwnParams(), and startAngle.
Referenced by GCS::ConstraintEqualFocalDistance::ConstraintEqualFocalDistance().
ReconstructOnNewPvec()
void GCS::ArcOfParabola::ReconstructOnNewPvec (VEC_pD & pvec, int & cnt) virtual
Reimplemented from GCS::Parabola.
References endAngle, GCS::Parabola::ReconstructOnNewPvec(), and startAngle.
Member Data Documentation
end
Point GCS::ArcOfParabola::end
endAngle
double* GCS::ArcOfParabola::endAngle
Referenced by ArcOfParabola(), PushOwnParams(), and ReconstructOnNewPvec().
start
Point GCS::ArcOfParabola::start
Referenced by Sketcher::Sketch::addArcOfParabola().
startAngle
double* GCS::ArcOfParabola::startAngle
Referenced by ArcOfParabola(), PushOwnParams(), and ReconstructOnNewPvec().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Geo.h
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Geo.cpp