FreeCAD: PathScripts.post.marlin_post Namespace Reference
PathScripts.post.marlin_post Namespace Reference
Functions
def drill_translate (outlist, cmd, params)
def dump (obj)
def export (objectslist, filename, argstring)
def format_outlist (strTable)
def linenumber ()
def parse (pathobj)
def processArguments (argstring)
Variables
action
string COMMAND_SPACE = " "
CURRENT_X = None
CURRENT_Y = None
CURRENT_Z = None
default
string DRILL_RETRACT_MODE = "G98"
help
int LINEINCR = 10
int LINENR = 100
bool MODAL = False
list MOTION_COMMANDS = ["G0", "G00", "G1", "G01", "G2", "G02", "G3", "G03"]
string MOTION_MODE = "G90"
bool OUTPUT_BCNC = False
bool OUTPUT_COMMENTS = True
bool OUTPUT_FINISH = False
bool OUTPUT_HEADER = True
bool OUTPUT_LINE_NUMBERS = False
bool OUTPUT_MARLIN_CONFIG = False
bool OUTPUT_PATH = False
bool OUTPUT_TOOL_CHANGE = False
parser = argparse.ArgumentParser(prog="marlin", add_help=False)
string POST_OPERATION = """"""
string POSTAMBLE
string PRE_OPERATION = """"""
string PREAMBLE = """"""
int PRECISION = 3
list RAPID_MOVES = ["G0", "G00"]
RETURN_TO = None
string Revised = "2020-11-03"
bool SHOW_EDITOR = True
int SPINDLE_WAIT = 3
list SUPPRESS_COMMANDS = [""]
string TOOL_CHANGE = """"""
string TOOLTIP
TOOLTIP_ARGS = parser.format_help()
bool TRANSLATE_DRILL_CYCLES = True
type
string UNIT_FEED_FORMAT = "mm/min"
string UNIT_FORMAT = "mm"
string UNITS = "G21"
string WORK_PLANE = "G17"
Function Documentation
drill_translate()
def PathScripts.post.marlin_post.drill_translate (outlist, cmd, params)
References PathScripts.post.marlin_post.format_outlist(), and PathScripts.post.marlin_post.linenumber().
Referenced by PathScripts.post.marlin_post.parse().
dump()
def PathScripts.post.marlin_post.dump (obj)
export()
def PathScripts.post.marlin_post.export (objectslist, filename, argstring)
References PathScripts.post.marlin_post.linenumber(), PathScripts.post.marlin_post.parse(), and PathScripts.post.marlin_post.processArguments().
format_outlist()
def PathScripts.post.marlin_post.format_outlist (strTable)
Referenced by PathScripts.post.marlin_post.drill_translate(), and PathScripts.post.marlin_post.parse().
linenumber()
def PathScripts.post.marlin_post.linenumber ()
Referenced by PathScripts.post.marlin_post.drill_translate(), PathScripts.post.marlin_post.export(), and PathScripts.post.marlin_post.parse().
parse()
def PathScripts.post.marlin_post.parse (pathobj)
References PathScripts.post.marlin_post.drill_translate(), DraftVecUtils.find(), PathScripts.post.marlin_post.format_outlist(), PathScripts.post.marlin_post.linenumber(), and PathScripts.post.marlin_post.parse().
Referenced by PathScripts.post.marlin_post.export(), and PathScripts.post.marlin_post.parse().
processArguments()
def PathScripts.post.marlin_post.processArguments (argstring)
Referenced by PathScripts.post.marlin_post.export().
Variable Documentation
action
PathScripts.post.marlin_post.action
COMMAND_SPACE
string PathScripts.post.marlin_post.COMMAND_SPACE = " "
CURRENT_X
PathScripts.post.marlin_post.CURRENT_X = None
CURRENT_Y
PathScripts.post.marlin_post.CURRENT_Y = None
CURRENT_Z
PathScripts.post.marlin_post.CURRENT_Z = None
default
PathScripts.post.marlin_post.default
DRILL_RETRACT_MODE
string PathScripts.post.marlin_post.DRILL_RETRACT_MODE = "G98"
help
PathScripts.post.marlin_post.help
LINEINCR
int PathScripts.post.marlin_post.LINEINCR = 10
LINENR
int PathScripts.post.marlin_post.LINENR = 100
MODAL
bool PathScripts.post.marlin_post.MODAL = False
MOTION_COMMANDS
list PathScripts.post.marlin_post.MOTION_COMMANDS = ["G0", "G00", "G1", "G01", "G2", "G02", "G3", "G03"]
MOTION_MODE
string PathScripts.post.marlin_post.MOTION_MODE = "G90"
OUTPUT_BCNC
bool PathScripts.post.marlin_post.OUTPUT_BCNC = False
OUTPUT_COMMENTS
bool PathScripts.post.marlin_post.OUTPUT_COMMENTS = True
OUTPUT_FINISH
bool PathScripts.post.marlin_post.OUTPUT_FINISH = False
OUTPUT_HEADER
bool PathScripts.post.marlin_post.OUTPUT_HEADER = True
OUTPUT_LINE_NUMBERS
bool PathScripts.post.marlin_post.OUTPUT_LINE_NUMBERS = False
OUTPUT_MARLIN_CONFIG
bool PathScripts.post.marlin_post.OUTPUT_MARLIN_CONFIG = False
OUTPUT_PATH
bool PathScripts.post.marlin_post.OUTPUT_PATH = False
OUTPUT_TOOL_CHANGE
bool PathScripts.post.marlin_post.OUTPUT_TOOL_CHANGE = False
parser
PathScripts.post.marlin_post.parser = argparse.ArgumentParser(prog="marlin", add_help=False)
POST_OPERATION
string PathScripts.post.marlin_post.POST_OPERATION = """"""
POSTAMBLE
string PathScripts.post.marlin_post.POSTAMBLE
Initial value:
=  """M5
"""
PRE_OPERATION
string PathScripts.post.marlin_post.PRE_OPERATION = """"""
PREAMBLE
string PathScripts.post.marlin_post.PREAMBLE = """"""
PRECISION
int PathScripts.post.marlin_post.PRECISION = 3
RAPID_MOVES
list PathScripts.post.marlin_post.RAPID_MOVES = ["G0", "G00"]
RETURN_TO
PathScripts.post.marlin_post.RETURN_TO = None
Revised
string PathScripts.post.marlin_post.Revised = "2020-11-03"
SHOW_EDITOR
bool PathScripts.post.marlin_post.SHOW_EDITOR = True
SPINDLE_WAIT
int PathScripts.post.marlin_post.SPINDLE_WAIT = 3
SUPPRESS_COMMANDS
list PathScripts.post.marlin_post.SUPPRESS_COMMANDS = [""]
TOOL_CHANGE
string PathScripts.post.marlin_post.TOOL_CHANGE = """"""
TOOLTIP
string PathScripts.post.marlin_post.TOOLTIP
Initial value:
=  """
Generate g-code from a Path that is compatible with the Marlin controller.
import marlin_post
marlin_post.export(object, "/path/to/file.nc")
"""
TOOLTIP_ARGS
PathScripts.post.marlin_post.TOOLTIP_ARGS = parser.format_help()
TRANSLATE_DRILL_CYCLES
bool PathScripts.post.marlin_post.TRANSLATE_DRILL_CYCLES = True
type
PathScripts.post.marlin_post.type
UNIT_FEED_FORMAT
string PathScripts.post.marlin_post.UNIT_FEED_FORMAT = "mm/min"
UNIT_FORMAT
string PathScripts.post.marlin_post.UNIT_FORMAT = "mm"
UNITS
string PathScripts.post.marlin_post.UNITS = "G21"
WORK_PLANE
string PathScripts.post.marlin_post.WORK_PLANE = "G17"