FreeCAD: PathScripts.post.uccnc_post Namespace Reference
PathScripts.post.uccnc_post Namespace Reference
Functions
def append (line)
def append0 (line)
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
def processArguments (argstring)
Variables
action
string COMMAND_SPACE = " "
default
string GCODE_PROCESSOR = "UC-CNC"
Other configuration settings #.
string HEADER
help
int LINE_NUMBER_START = 0
int LINE_NUMBER_STEP = 1
int LINENR = 0
bool MODAL = False
now = datetime.datetime.now()
bool OUTPUT_COMMENTS = True
bool OUTPUT_HEADER = True
bool OUTPUT_LINE_NUMBERS = False
parser = argparse.ArgumentParser(prog=__name__, add_help=False)
No more configuration settings after this line #.
string POST_OPERATION = """"""
string POSTAMBLE = POSTAMBLE_DEFAULT
string POSTAMBLE_DEFAULT
string POSTAMBLE_DEFAULT_NO_COMMENT
string PRE_OPERATION = """"""
string PREAMBLE = PREAMBLE_DEFAULT
string PREAMBLE_DEFAULT
string PREAMBLE_DEFAULT_NO_COMMENT
int PRECISION = 3
int problems_count = 0
string PROG_NAME = "prog1"
pythonopen = open
bool REPEAT_ARGUMENTS = False
bool SHOW_EDITOR = True
string TOOL_CHANGE = """"""
string TOOLTIP
TOOLTIP_ARGS = parser.format_help()
bool trace_gcode = False
bool UNIT_DEFAULT_CHANGED = False
string UNIT_FORMAT = UNIT_FORMAT_METRIC
string UNIT_FORMAT_METRIC = "mm"
string UNIT_FORMAT_US_IMP = "in"
string UNIT_SPEED_FORMAT = UNIT_SPEED_FORMAT_METRIC
string UNIT_SPEED_FORMAT_METRIC = "mm/min"
string UNIT_SPEED_FORMAT_US_IMP = "in/min"
string UNITS = UNITS_METRIC
string UNITS_METRIC = "G21"
string UNITS_US_IMP = "G20"
bool USE_TLO = False
string VERSION = "0.0.4"
int warnings_count = 0
Function Documentation
append()
def PathScripts.post.uccnc_post.append (line)
References PathScripts.post.uccnc_post.linenumber().
Referenced by PathScripts.post.uccnc_post.export().
append0()
def PathScripts.post.uccnc_post.append0 (line)
Referenced by PathScripts.post.uccnc_post.export().
export()
def PathScripts.post.uccnc_post.export (objectslist, filename, argstring)
References PathScripts.post.uccnc_post.append(), PathScripts.post.uccnc_post.append0(), PathScripts.post.uccnc_post.parse(), PathScripts.post.uccnc_post.processArguments(), and PathScripts.post.uccnc_post.pythonopen.
linenumber()
def PathScripts.post.uccnc_post.linenumber ()
Referenced by PathScripts.post.uccnc_post.append(), and PathScripts.post.uccnc_post.parse().
parse()
def PathScripts.post.uccnc_post.parse (pathobj)
References PathScripts.post.uccnc_post.linenumber(), and PathScripts.post.uccnc_post.parse().
Referenced by PathScripts.post.uccnc_post.export(), and PathScripts.post.uccnc_post.parse().
processArguments()
def PathScripts.post.uccnc_post.processArguments (argstring)
Referenced by PathScripts.post.uccnc_post.export().
Variable Documentation
action
PathScripts.post.uccnc_post.action
COMMAND_SPACE
string PathScripts.post.uccnc_post.COMMAND_SPACE = " "
default
PathScripts.post.uccnc_post.default
GCODE_PROCESSOR
string PathScripts.post.uccnc_post.GCODE_PROCESSOR = "UC-CNC"
Other configuration settings #.
HEADER
string PathScripts.post.uccnc_post.HEADER
Initial value:
=  """(Exported by FreeCAD for {})
(Post Processor: {}, version {})
(CAM file: {})
(Output Time: {})
"""
help
PathScripts.post.uccnc_post.help
LINE_NUMBER_START
int PathScripts.post.uccnc_post.LINE_NUMBER_START = 0
LINE_NUMBER_STEP
int PathScripts.post.uccnc_post.LINE_NUMBER_STEP = 1
LINENR
int PathScripts.post.uccnc_post.LINENR = 0
MODAL
bool PathScripts.post.uccnc_post.MODAL = False
now
PathScripts.post.uccnc_post.now = datetime.datetime.now()
OUTPUT_COMMENTS
bool PathScripts.post.uccnc_post.OUTPUT_COMMENTS = True
OUTPUT_HEADER
bool PathScripts.post.uccnc_post.OUTPUT_HEADER = True
OUTPUT_LINE_NUMBERS
bool PathScripts.post.uccnc_post.OUTPUT_LINE_NUMBERS = False
parser
PathScripts.post.uccnc_post.parser = argparse.ArgumentParser(prog=__name__, add_help=False)
No more configuration settings after this line #.
POST_OPERATION
string PathScripts.post.uccnc_post.POST_OPERATION = """"""
POSTAMBLE
string PathScripts.post.uccnc_post.POSTAMBLE = POSTAMBLE_DEFAULT
POSTAMBLE_DEFAULT
string PathScripts.post.uccnc_post.POSTAMBLE_DEFAULT
Initial value:
=  """M05 (stop spindle)
G17 (Default: XY-plane)
G54 (Default: First coordinate system)
G40 (Default: Cutter radius compensation none)
G90 (Default: Absolute distance mode selection)
G80 (Cancel canned cycle)
M30 (Stop program and rewind code)
"""
POSTAMBLE_DEFAULT_NO_COMMENT
string PathScripts.post.uccnc_post.POSTAMBLE_DEFAULT_NO_COMMENT
Initial value:
=  """M05
G17
G54
G40
G90
G80
M30
"""
PRE_OPERATION
string PathScripts.post.uccnc_post.PRE_OPERATION = """"""
PREAMBLE
string PathScripts.post.uccnc_post.PREAMBLE = PREAMBLE_DEFAULT
PREAMBLE_DEFAULT
string PathScripts.post.uccnc_post.PREAMBLE_DEFAULT
Initial value:
=  """G17 (Default: XY-plane)
G54 (Default: First coordinate system)
G40 (Default: Cutter radius compensation none)
G49 (Default: Tool Length Offsets: cancel tool length)
G90 (Default: Absolute distance mode selection)
G80 (Cancel canned cycle)
"""
PREAMBLE_DEFAULT_NO_COMMENT
string PathScripts.post.uccnc_post.PREAMBLE_DEFAULT_NO_COMMENT
Initial value:
=  """G17
G54
G40
G49
G90
G80
"""
PRECISION
int PathScripts.post.uccnc_post.PRECISION = 3
problems_count
int PathScripts.post.uccnc_post.problems_count = 0
PROG_NAME
string PathScripts.post.uccnc_post.PROG_NAME = "prog1"
pythonopen
PathScripts.post.uccnc_post.pythonopen = open
Referenced by PathScripts.post.uccnc_post.export().
REPEAT_ARGUMENTS
bool PathScripts.post.uccnc_post.REPEAT_ARGUMENTS = False
SHOW_EDITOR
bool PathScripts.post.uccnc_post.SHOW_EDITOR = True
TOOL_CHANGE
string PathScripts.post.uccnc_post.TOOL_CHANGE = """"""
TOOLTIP
string PathScripts.post.uccnc_post.TOOLTIP
Initial value:
=  """ Post processor for UC-CNC.
This is a postprocessor file for the Path workbench. It is used to
take a pseudo-gcode fragment outputted by a Path object, and output
real GCode. This postprocessor, once placed in the appropriate
PathScripts folder, can be used directly from inside FreeCAD,
via the GUI importer or via python scripts with:
import UCCNC_post
UCCNC_post.export(object,"/path/to/file.ncc","")
This postprocessor was tested on UC-CNC v1.2111, an UC100 and a Stepcraft 420.
It was tested on FreeCAD v0.17, v0.18 and v0.19
Other (Stepcraft) machines using UC-CNC and UC* controllers should be easy to adapt.
"""
TOOLTIP_ARGS
PathScripts.post.uccnc_post.TOOLTIP_ARGS = parser.format_help()
trace_gcode
bool PathScripts.post.uccnc_post.trace_gcode = False
UNIT_DEFAULT_CHANGED
bool PathScripts.post.uccnc_post.UNIT_DEFAULT_CHANGED = False
UNIT_FORMAT
string PathScripts.post.uccnc_post.UNIT_FORMAT = UNIT_FORMAT_METRIC
UNIT_FORMAT_METRIC
string PathScripts.post.uccnc_post.UNIT_FORMAT_METRIC = "mm"
UNIT_FORMAT_US_IMP
string PathScripts.post.uccnc_post.UNIT_FORMAT_US_IMP = "in"
UNIT_SPEED_FORMAT
string PathScripts.post.uccnc_post.UNIT_SPEED_FORMAT = UNIT_SPEED_FORMAT_METRIC
UNIT_SPEED_FORMAT_METRIC
string PathScripts.post.uccnc_post.UNIT_SPEED_FORMAT_METRIC = "mm/min"
UNIT_SPEED_FORMAT_US_IMP
string PathScripts.post.uccnc_post.UNIT_SPEED_FORMAT_US_IMP = "in/min"
UNITS
string PathScripts.post.uccnc_post.UNITS = UNITS_METRIC
UNITS_METRIC
string PathScripts.post.uccnc_post.UNITS_METRIC = "G21"
UNITS_US_IMP
string PathScripts.post.uccnc_post.UNITS_US_IMP = "G20"
USE_TLO
bool PathScripts.post.uccnc_post.USE_TLO = False
VERSION
string PathScripts.post.uccnc_post.VERSION = "0.0.4"
warnings_count
int PathScripts.post.uccnc_post.warnings_count = 0