FreeCAD: Gui::SelectionObject Class Reference
Gui::SelectionObject Class Reference
The Selection object class.
#include <SelectionObject.h>
Public Member Functions
std::string getAsPropertyLinkSubString (void) const
returns python expreasion sutably for assigning to a LinkSub property
const char * getDocName (void) const
get the name of the Document of this SelctionObject
const char * getFeatName (void) const
get the name of the Document Object of this SelectionObject
App::DocumentObject * getObject (void)
returns the selected DocumentObject or NULL if the object is already deleted
const App::DocumentObject * getObject (void) const
returns the selected DocumentObject or NULL if the object is already deleted
const std::vector< Base::Vector3d > getPickedPoints (void) const
get the selection points
PyObject * getPyObject ()
The default implementation returns an instance of SelectionObjectPy.
const std::vector< std::string > & getSubNames (void) const
get the SubElement name of this SelectionObject
const char * getTypeName (void) const
get the Type of the selected Object
bool hasSubNames (void) const
are there any SubNames selected
bool isObjectTypeOf (const Base::Type &typeId) const
check the selected object is a special type or derived of
SelectionObject ()
Constructs a SelectionObject object.
SelectionObject (App::DocumentObject *)
SelectionObject (const SelectionChanges &msg)
virtual ~SelectionObject ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual Type getTypeId (void) const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Attributes
std::string DocName
std::string FeatName
std::vector< Base::Vector3d > SelPoses
std::vector< std::string > SubNames
std::string TypeName
Friends
class SelectionSingleton
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The Selection object class.
Constructor & Destructor Documentation
SelectionObject() [1/3]
SelectionObject::SelectionObject ()
Constructs a SelectionObject object.
Referenced by getPyObject().
SelectionObject() [2/3]
SelectionObject::SelectionObject (const SelectionChanges & msg)
Constructs a SelectionObject from the SelectionChanges structure.
References DocName, FeatName, SelPoses, SubNames, and TypeName.
SelectionObject() [3/3]
SelectionObject::SelectionObject (App::DocumentObject * obj) explicit
References DocName, FeatName, and TypeName.
~SelectionObject()
SelectionObject::~SelectionObject () virtual
Member Function Documentation
getAsPropertyLinkSubString()
std::string SelectionObject::getAsPropertyLinkSubString (void) const
returns python expreasion sutably for assigning to a LinkSub property
References getObject(), Gui::Command::getObjectCmd(), and SubNames.
getDocName()
const char* Gui::SelectionObject::getDocName (void) const
get the name of the Document of this SelctionObject
getFeatName()
const char* Gui::SelectionObject::getFeatName (void) const
get the name of the Document Object of this SelectionObject
getObject() [1/2]
App::DocumentObject * SelectionObject::getObject (void)
returns the selected DocumentObject or NULL if the object is already deleted
References DocName, FeatName, App::GetApplication(), and App::Application::getDocument().
getObject() [2/2]
const App::DocumentObject * SelectionObject::getObject (void) const
returns the selected DocumentObject or NULL if the object is already deleted
References DocName, FeatName, App::GetApplication(), and App::Application::getDocument().
Referenced by Gui::SelectionSingleton::getAsPropertyLinkSubList(), getAsPropertyLinkSubString(), Gui::SelectionObjectPy::getSubObjects(), isObjectTypeOf(), PartDesignGui::TaskScaledParameters::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), SurfaceGui::FillingEdgePanel::onSelectionChanged(), SurfaceGui::FillingVertexPanel::onSelectionChanged(), SurfaceGui::GeomFillSurface::onSelectionChanged(), SurfaceGui::SectionsPanel::onSelectionChanged(), and PartGui::DlgFilletEdges::Private::SelectionObjectCompare::operator()().
getPickedPoints()
const std::vector<Base::Vector3d> Gui::SelectionObject::getPickedPoints (void) const
get the selection points
Referenced by Gui::SelectionObjectPy::getPickedPoints().
getPyObject()
PyObject * SelectionObject::getPyObject (void) virtual
The default implementation returns an instance of SelectionObjectPy.
Reimplemented from Base::BaseClass.
References SelectionObject().
Referenced by Gui::SelectionSingleton::sGetSelectionObject().
getSubNames()
const std::vector<std::string>& Gui::SelectionObject::getSubNames (void) const
get the SubElement name of this SelectionObject
Referenced by Gui::SelectionSingleton::getAsPropertyLinkSubList(), and Gui::SelectionObjectPy::getSubElementNames().
getTypeName()
const char* Gui::SelectionObject::getTypeName (void) const
get the Type of the selected Object
hasSubNames()
bool Gui::SelectionObject::hasSubNames (void) const
are there any SubNames selected
isObjectTypeOf()
bool SelectionObject::isObjectTypeOf (const Base::Type & typeId) const
check the selected object is a special type or derived of
References getObject().
Referenced by Gui::SelectionObjectPy::isObjectTypeOf().
Friends And Related Function Documentation
SelectionSingleton
friend class SelectionSingleton friend
Member Data Documentation
DocName
std::string Gui::SelectionObject::DocName protected
Referenced by getObject(), SelectionObject(), Gui::SelectionSingleton::sGetSelectionObject(), Mod.Test.Document.DocumentPlatformCases::testColorList(), Mod.Test.Document.DocumentPlatformCases::testFloatList(), Mod.Test.Document.DocumentPlatformCases::testPoints(), and Mod.Test.Document.DocumentPlatformCases::testVectorList().
FeatName
std::string Gui::SelectionObject::FeatName protected
Referenced by getObject(), SelectionObject(), and Gui::SelectionSingleton::sGetSelectionObject().
SelPoses
std::vector<Base::Vector3d> Gui::SelectionObject::SelPoses protected
Referenced by SelectionObject(), and Gui::SelectionSingleton::sGetSelectionObject().
SubNames
std::vector<std::string> Gui::SelectionObject::SubNames protected
Referenced by getAsPropertyLinkSubString(), SelectionObject(), and Gui::SelectionSingleton::sGetSelectionObject().
TypeName
std::string Gui::SelectionObject::TypeName protected
Referenced by SelectionObject().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SelectionObject.h
Sources/FreeCAD/src/Gui/SelectionObject.cpp