FreeCAD: Gui::Dialog::TaskPlacement Class Reference
Gui::Dialog::TaskPlacement Class Reference
#include <Placement.h>
Public Slots
void slotPlacementChanged (const QVariant &, bool, bool)
Signals
void placementChanged (const QVariant &, bool, bool)
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Public Member Functions
bool accept ()
is called by the framework if the dialog is accepted (Ok)
void bindObject ()
void clicked (int id)
is called by the framework if a button is clicked which has no accept or reject role
QDialogButtonBox::StandardButtons getStandardButtons () const
tells the framework which buttons are wished for the dialog
bool isAllowedAlterDocument (void) const
bool isAllowedAlterSelection (void) const
bool isAllowedAlterView (void) const
void open ()
is called by the framework when the dialog is opened
bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setPlacement (const Base::Placement &)
void setPropertyName (const QString &)
TaskPlacement ()
~TaskPlacement ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual void helpRequested ()
is called by the framework if the user press the help button
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Constructor & Destructor Documentation
TaskPlacement()
TaskPlacement::TaskPlacement ()
References draftgeoutils.intersections::connect(), Gui::TaskView::TaskDialog::Content, QSint::ActionGroup::groupLayout(), placementChanged(), Gui::TaskView::TaskDialog::setButtonPosition(), Gui::Dialog::Placement::showDefaultButtons(), slotPlacementChanged(), and Gui::TaskView::TaskDialog::South.
~TaskPlacement()
TaskPlacement::~TaskPlacement ()
Member Function Documentation
accept()
bool TaskPlacement::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Dialog::Placement::accept().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
bindObject()
void TaskPlacement::bindObject ()
References Gui::Dialog::Placement::bindObject().
clicked()
void TaskPlacement::clicked (int) virtual
is called by the framework if a button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
getStandardButtons()
QDialogButtonBox::StandardButtons TaskPlacement::getStandardButtons (void) const virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
isAllowedAlterDocument()
bool Gui::Dialog::TaskPlacement::isAllowedAlterDocument (void) const virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
isAllowedAlterSelection()
bool Gui::Dialog::TaskPlacement::isAllowedAlterSelection (void) const virtual
Indicates whether this task dialog allows other commands to modify the selection while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
isAllowedAlterView()
bool Gui::Dialog::TaskPlacement::isAllowedAlterView (void) const virtual
Indicates whether this task dialog allows other commands to modify the 3d view while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
open()
void TaskPlacement::open () virtual
is called by the framework when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Dialog::Placement::open().
placementChanged
void Gui::Dialog::TaskPlacement::placementChanged (const QVariant & , bool , bool) signal
Referenced by slotPlacementChanged(), and TaskPlacement().
reject()
bool TaskPlacement::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Dialog::Placement::reject().
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
setPlacement()
void TaskPlacement::setPlacement (const Base::Placement & p)
References Gui::Dialog::Placement::setPlacement().
Referenced by StdCmdPlacement::activated().
setPropertyName()
void TaskPlacement::setPropertyName (const QString & name)
slotPlacementChanged
void TaskPlacement::slotPlacementChanged (const QVariant & p, bool incr, bool data) slot
References placementChanged().
Referenced by TaskPlacement().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Placement.h
Sources/FreeCAD/src/Gui/Placement.cpp