FreeCAD: SketcherGui::ExtendSelection Class Reference
SketcherGui::ExtendSelection Class Reference
#include <DrawSketchHandlerExtend.h>
Public Member Functions
bool allow (App::Document *, App::DocumentObject *pObj, const char *sSubName)
ExtendSelection (App::DocumentObject *obj)
void setDisabled (bool isDisabled)
Public Member Functions inherited from Gui::SelectionFilterGate
virtual bool allow (App::Document *, App::DocumentObject *, const char *)
SelectionFilterGate (const char *filter)
construct with the filter string
SelectionFilterGate (SelectionFilter *filter)
~SelectionFilterGate ()
Public Member Functions inherited from Gui::SelectionGate
virtual bool allow (App::Document *, App::DocumentObject *, const char *)=0
virtual ~SelectionGate ()
Protected Attributes
bool disabled
Protected Attributes inherited from Gui::SelectionFilterGate
SelectionFilter * Filter
Additional Inherited Members
Public Attributes inherited from Gui::SelectionGate
std::string notAllowedReason
notAllowedReason is a string that sets the message to be displayed in statusbar for cluing the user on why is the selection not allowed.
Protected Member Functions inherited from Gui::SelectionFilterGate
SelectionFilterGate ()
Static Protected Member Functions inherited from Gui::SelectionFilterGate
static SelectionFilter * nullPointer ()
static const char * nullString ()
Constructor & Destructor Documentation
ExtendSelection()
SketcherGui::ExtendSelection::ExtendSelection (App::DocumentObject * obj)
Member Function Documentation
allow()
bool SketcherGui::ExtendSelection::allow (App::Document * , App::DocumentObject * pObj, const char * sSubName) virtual
Reimplemented from Gui::SelectionFilterGate.
References disabled, Base::Persistence::getClassTypeId(), Sketcher::SketchObject::getGeometry(), and Base::Persistence::getTypeId().
setDisabled()
void SketcherGui::ExtendSelection::setDisabled (bool isDisabled)
References disabled.
Referenced by SketcherGui::DrawSketchHandlerExtend::releaseButton().
Member Data Documentation
disabled
bool SketcherGui::ExtendSelection::disabled protected
Referenced by allow(), and setDisabled().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/DrawSketchHandlerExtend.h