FreeCAD: Gui::Dialog::DlgCustomToolbarsImp Class Reference
Gui::Dialog::DlgCustomToolbarsImp Class Reference
This class implements the creation of user defined toolbars.
#include <DlgToolbarsImp.h>
Public Member Functions
DlgCustomToolbarsImp (QWidget *parent=0)
Constructs a DlgCustomToolbarsImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
~DlgCustomToolbarsImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::CustomizeActionPage
CustomizeActionPage (QWidget *parent=0)
Construction.
virtual ~CustomizeActionPage ()
Destruction.
Protected Member Functions
virtual void addCustomCommand (const QString &, const QByteArray &)
virtual void addCustomToolbar (const QString &)
void changeEvent (QEvent *e)
virtual void moveDownCustomCommand (const QString &, const QByteArray &)
virtual void moveUpCustomCommand (const QString &, const QByteArray &)
virtual void removeCustomCommand (const QString &, const QByteArray &)
virtual void removeCustomToolbar (const QString &)
virtual void renameCustomToolbar (const QString &, const QString &)
Protected Member Functions inherited from Gui::Dialog::DlgCustomToolbars
DlgCustomToolbars (Type, QWidget *parent=0)
Constructs a DlgCustomToolbars which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
void hideEvent (QHideEvent *event)
virtual ~DlgCustomToolbars ()
Destroys the object and frees any allocated resources.
Protected Member Functions inherited from Gui::Dialog::CustomizeActionPage
bool event (QEvent *e)
Additional Inherited Members
Protected Types inherited from Gui::Dialog::DlgCustomToolbars
enum Type { Toolbar , Toolboxbar }
Protected Slots inherited from Gui::Dialog::DlgCustomToolbars
void on_categoryBox_activated (int index)
void on_deleteButton_clicked ()
void on_moveActionDownButton_clicked ()
Moves down an action.
void on_moveActionLeftButton_clicked ()
Removes an action.
void on_moveActionRightButton_clicked ()
Adds a new action.
void on_moveActionUpButton_clicked ()
Moves up an action.
void on_newButton_clicked ()
void on_renameButton_clicked ()
void on_workbenchBox_activated (int index)
void onAddMacroAction (const QByteArray &)
void onModifyMacroAction (const QByteArray &)
void onRemoveMacroAction (const QByteArray &)
Protected Slots inherited from Gui::Dialog::CustomizeActionPage
virtual void onAddMacroAction (const QByteArray &)=0
virtual void onModifyMacroAction (const QByteArray &)=0
virtual void onRemoveMacroAction (const QByteArray &)=0
Protected Attributes inherited from Gui::Dialog::DlgCustomToolbars
std::unique_ptr< Ui_DlgCustomToolbars > ui
Detailed Description
This class implements the creation of user defined toolbars.
See also
DlgCustomToolbars
DlgCustomCmdbarsImp
Author
Werner Mayer
Constructor & Destructor Documentation
DlgCustomToolbarsImp()
DlgCustomToolbarsImp::DlgCustomToolbarsImp (QWidget * parent = 0)
Constructs a DlgCustomToolbarsImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
~DlgCustomToolbarsImp()
DlgCustomToolbarsImp::~DlgCustomToolbarsImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
addCustomCommand()
void DlgCustomToolbarsImp::addCustomCommand (const QString & name, const QByteArray & cmd) protected virtual
Reimplemented from Gui::Dialog::DlgCustomToolbars.
References Gui::WorkbenchManager::active(), Gui::CommandManager::addTo(), Gui::Application::commandManager(), Gui::getMainWindow(), Gui::Application::Instance, Gui::WorkbenchManager::instance(), and Gui::Dialog::DlgCustomToolbars::ui.
addCustomToolbar()
void DlgCustomToolbarsImp::addCustomToolbar (const QString & name) protected virtual
Reimplemented from Gui::Dialog::DlgCustomToolbars.
References Gui::WorkbenchManager::active(), Gui::getMainWindow(), Gui::WorkbenchManager::instance(), and Gui::Dialog::DlgCustomToolbars::ui.
changeEvent()
void DlgCustomToolbarsImp::changeEvent (QEvent * e) protected virtual
Reimplemented from Gui::Dialog::DlgCustomToolbars.
References Gui::Dialog::DlgCustomToolbars::changeEvent().
moveDownCustomCommand()
void DlgCustomToolbarsImp::moveDownCustomCommand (const QString & name, const QByteArray & userdata) protected virtual
Reimplemented from Gui::Dialog::DlgCustomToolbars.
References Gui::WorkbenchManager::active(), Gui::getMainWindow(), Gui::WorkbenchManager::instance(), and Gui::Dialog::DlgCustomToolbars::ui.
moveUpCustomCommand()
void DlgCustomToolbarsImp::moveUpCustomCommand (const QString & name, const QByteArray & userdata) protected virtual
Reimplemented from Gui::Dialog::DlgCustomToolbars.
References Gui::WorkbenchManager::active(), Gui::getMainWindow(), Gui::WorkbenchManager::instance(), and Gui::Dialog::DlgCustomToolbars::ui.
removeCustomCommand()
void DlgCustomToolbarsImp::removeCustomCommand (const QString & name, const QByteArray & userdata) protected virtual
Reimplemented from Gui::Dialog::DlgCustomToolbars.
References Gui::WorkbenchManager::active(), Gui::getMainWindow(), Gui::WorkbenchManager::instance(), and Gui::Dialog::DlgCustomToolbars::ui.
removeCustomToolbar()
void DlgCustomToolbarsImp::removeCustomToolbar (const QString & name) protected virtual
Reimplemented from Gui::Dialog::DlgCustomToolbars.
References Gui::WorkbenchManager::active(), Gui::getMainWindow(), Gui::WorkbenchManager::instance(), and Gui::Dialog::DlgCustomToolbars::ui.
renameCustomToolbar()
void DlgCustomToolbarsImp::renameCustomToolbar (const QString & old_name, const QString & new_name) protected virtual
Reimplemented from Gui::Dialog::DlgCustomToolbars.
References Gui::WorkbenchManager::active(), Gui::getMainWindow(), Gui::WorkbenchManager::instance(), and Gui::Dialog::DlgCustomToolbars::ui.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgToolbarsImp.h
Sources/FreeCAD/src/Gui/DlgToolbarsImp.cpp