FreeCAD: PathTests.TestPathDepthParams.depthTestCases Class Reference
PathTests.TestPathDepthParams.depthTestCases Class Reference
Public Member Functions
def test00 (self)
def test001 (self)
def test002 (self)
def test003 (self)
def test004 (self)
def test005 (self)
def test006 (self)
def test007 (self)
def test008 (self)
def test009 (self)
def test010 (self)
Member Function Documentation
test00()
def PathTests.TestPathDepthParams.depthTestCases.test00 (self)
Stepping down to zero
Referenced by PathTests.TestPathTool.TestPathTool.test01(), PathTests.TestPathToolController.TestPathToolController.test01(), PathTests.TestPathTooltable.TestPathTooltable.test01(), PathTests.TestPathTool.TestPathTool.test02(), and PathTests.TestPathTooltable.TestPathTooltable.test02().
test001()
def PathTests.TestPathDepthParams.depthTestCases.test001 (self)
Stepping from zero to a negative depth
test002()
def PathTests.TestPathDepthParams.depthTestCases.test002 (self)
Start and end are equal or start lower than finish
test003()
def PathTests.TestPathDepthParams.depthTestCases.test003 (self)
User Parameters passed in
test004()
def PathTests.TestPathDepthParams.depthTestCases.test004 (self)
z_finish_step passed in.
test005()
def PathTests.TestPathDepthParams.depthTestCases.test005 (self)
stepping down with equalstep=True
test006()
def PathTests.TestPathDepthParams.depthTestCases.test006 (self)
stepping down with equalstep=True and a finish depth
test007()
def PathTests.TestPathDepthParams.depthTestCases.test007 (self)
stepping down with stepdown greater than total depth
test008()
def PathTests.TestPathDepthParams.depthTestCases.test008 (self)
Test handling of negative step-down, negative finish step, and relative size of step/finish
test009()
def PathTests.TestPathDepthParams.depthTestCases.test009 (self)
stepping down with single stepdown exactly equal to total depth
test010()
def PathTests.TestPathDepthParams.depthTestCases.test010 (self)
stepping down with single stepdown roughly equal to total depth
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Path/PathTests/TestPathDepthParams.py