FreeCAD: VISCOUS_3D::_ViscousBuilder Class Reference
VISCOUS_3D::_ViscousBuilder Class Reference
Builder of viscous layers.
Public Member Functions
SMESH_ComputeErrorPtr CheckHypotheses (SMESH_Mesh &mesh, const TopoDS_Shape &shape)
Check validity of hypotheses.
SMESH_ComputeErrorPtr Compute (SMESH_Mesh &mesh, const TopoDS_Shape &shape)
Does its job.
bool MakeN2NMap (_MeshOfSolid *pm)
computes SMESH_ProxyMesh::SubMesh::_n2n
void RestoreListeners ()
At study restoration, restore event listeners used to clear an inferior dim sub-mesh modified by viscous layers.
Detailed Description
Builder of viscous layers.
Member Function Documentation
CheckHypotheses()
SMESH_ComputeErrorPtr _ViscousBuilder::CheckHypotheses (SMESH_Mesh & mesh, const TopoDS_Shape & shape)
Check validity of hypotheses.
References VISCOUS_3D::_ViscousListener::GetSolidMesh(), and VISCOUS_3D::_ViscousListener::RemoveSolidMesh().
Referenced by StdMeshers_ViscousLayers::CheckHypothesis().
Compute()
SMESH_ComputeErrorPtr _ViscousBuilder::Compute (SMESH_Mesh & mesh, const TopoDS_Shape & shape)
Does its job.
References VISCOUS_3D::PyDump::Finish(), and VISCOUS_3D::_ViscousListener::GetSolidMesh().
Referenced by StdMeshers_ViscousLayers::Compute().
MakeN2NMap()
bool _ViscousBuilder::MakeN2NMap (_MeshOfSolid * pm)
computes SMESH_ProxyMesh::SubMesh::_n2n
References SMESH_ProxyMesh::SubMesh::GetElements(), SMESHDS_SubMesh::GetElements(), SMESH_subMesh::GetId(), SMESH_ProxyMesh::GetMeshDS(), SMDS_MeshElement::GetNode(), SMESH_ProxyMesh::GetProxySubMesh(), SMESH_subMesh::GetSubShape(), SMESHDS_Mesh::MeshElements(), SMESH_subMeshEventListenerData::mySubMeshes, SMESH_ProxyMesh::SubMesh::NbElements(), SMESHDS_SubMesh::NbElements(), SMDS_MeshElement::NbNodes(), and VISCOUS_3D::_MeshOfSolid::setNode2Node().
Referenced by StdMeshers_ViscousLayers::Compute().
RestoreListeners()
void _ViscousBuilder::RestoreListeners ()
At study restoration, restore event listeners used to clear an inferior dim sub-mesh modified by viscous layers.
The documentation for this class was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_ViscousLayers.cpp