FreeCAD: Base::UnitsSchema Class Reference
Base::UnitsSchema Class Reference abstract
The UnitSchema class The subclasses of this class define the stuff for a certain units schema.
#include <UnitsSchema.h>
Public Member Functions
virtual void resetSchemaUnits (void)
If you use setSchemaUnits() you also have to impment this method to undo your changes!
virtual QString schemaTranslate (const Base::Quantity &quant, double &factor, QString &unitString)=0
This method translates the quantity in a string as the user may expect it.
virtual void setSchemaUnits (void)
Gets called if this schema gets activated.
QString toLocale (const Base::Quantity &quant, double factor, const QString &unitString) const
virtual ~UnitsSchema ()
Detailed Description
The UnitSchema class The subclasses of this class define the stuff for a certain units schema.
Constructor & Destructor Documentation
~UnitsSchema()
virtual Base::UnitsSchema::~UnitsSchema () virtual
Member Function Documentation
resetSchemaUnits()
virtual void Base::UnitsSchema::resetSchemaUnits (void) virtual
If you use setSchemaUnits() you also have to impment this method to undo your changes!
schemaTranslate()
virtual QString Base::UnitsSchema::schemaTranslate (const Base::Quantity & quant, double & factor, QString & unitString) pure virtual
This method translates the quantity in a string as the user may expect it.
Implemented in Base::UnitsSchemaMmMin, Base::UnitsSchemaMKS, Base::UnitsSchemaInternal, Base::UnitsSchemaImperialCivil, Base::UnitsSchemaImperialBuilding, Base::UnitsSchemaImperialDecimal, Base::UnitsSchemaImperial1, Base::UnitsSchemaFemMilliMeterNewton, and Base::UnitsSchemaCentimeters.
Referenced by Base::Quantity::getUserString(), and Base::UnitsApi::sSchemaTranslate().
setSchemaUnits()
virtual void Base::UnitsSchema::setSchemaUnits (void) virtual
Gets called if this schema gets activated.
Here it's theoretically possible that you can change the static factors for certain units (e.g. mi = 1,8km instead of mi=1.6km).
toLocale()
QString UnitsSchema::toLocale (const Base::Quantity & quant, double factor, const QString & unitString) const
References Base::Quantity::getFormat(), and Base::Quantity::getValue().
Referenced by Base::UnitsSchemaCentimeters::schemaTranslate(), Base::UnitsSchemaFemMilliMeterNewton::schemaTranslate(), Base::UnitsSchemaImperial1::schemaTranslate(), Base::UnitsSchemaImperialDecimal::schemaTranslate(), Base::UnitsSchemaImperialBuilding::schemaTranslate(), Base::UnitsSchemaImperialCivil::schemaTranslate(), Base::UnitsSchemaInternal::schemaTranslate(), Base::UnitsSchemaMKS::schemaTranslate(), and Base::UnitsSchemaMmMin::schemaTranslate().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Base/UnitsSchema.h
Sources/FreeCAD/src/Base/UnitsSchema.cpp