FreeCAD: Part::PrismExtension Class Reference
Part::PrismExtension Class Reference
#include <PrismExtension.h>
Public Member Functions
virtual App::DocumentObjectExecReturn * extensionExecute (void)
virtual short int extensionMustExecute (void)
TopoDS_Shape makePrism (double height, const TopoDS_Face &face) const
PrismExtension ()
virtual ~PrismExtension ()
Public Member Functions inherited from App::DocumentObjectExtension
DocumentObjectExtension ()
virtual App::DocumentObjectExecReturn * extensionExecute ()
virtual bool extensionGetLinkedObject (DocumentObject *&ret, bool recursive, Base::Matrix4D *mat, bool transform, int depth) const
Get the linked object.
virtual bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const
Get the sub object by name.
virtual bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const
Get name references of all sub objects.
virtual bool extensionHasChildElement () const
virtual int extensionIsElementVisible (const char *)
virtual short extensionMustExecute ()
virtual int extensionSetElementVisible (const char *, bool)
App::DocumentObject * getExtendedObject ()
const App::DocumentObject * getExtendedObject () const
virtual PyObject * getExtensionPyObject () override
virtual const char * getViewProviderExtensionName () const
returns the type name of the ViewProviderExtension which is automatically attached to the viewprovider object when it is initiated
virtual void onExtendedDocumentRestored ()
get called after a document has been fully restored
virtual void onExtendedSettingDocument ()
get called after setting the document
virtual void onExtendedSetupObject ()
get called after a brand new object was created
virtual void onExtendedUnsetupObject ()
get called when object is going to be removed from the document
virtual ~DocumentObjectExtension ()
Public Member Functions inherited from App::Extension
Extension ()
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
virtual PyObject * getExtensionPyObject ()
virtual void initExtension (App::ExtensionContainer *obj)
bool isPythonExtension ()
std::string name () const
virtual ~Extension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Public Attributes
App::PropertyAngle FirstAngle
App::PropertyAngle SecondAngle
Protected Member Functions
virtual void extensionOnChanged (const App::Property *)
Protected Member Functions inherited from App::Extension
void initExtensionType (Base::Type type)
Additional Inherited Members
Static Protected Member Functions inherited from App::Extension
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Constructor & Destructor Documentation
PrismExtension()
PrismExtension::PrismExtension ()
References App::Prop_None.
~PrismExtension()
PrismExtension::~PrismExtension () virtual
Member Function Documentation
extensionExecute()
App::DocumentObjectExecReturn * PrismExtension::extensionExecute (void) virtual
Reimplemented from App::DocumentObjectExtension.
References App::DocumentObjectExtension::extensionExecute().
extensionMustExecute()
short int PrismExtension::extensionMustExecute (void) virtual
Reimplemented from App::DocumentObjectExtension.
References FirstAngle, App::Property::isTouched(), and SecondAngle.
extensionOnChanged()
void PrismExtension::extensionOnChanged (const App::Property * prop) protected virtual
Reimplemented from App::Extension.
References App::Extension::extensionOnChanged().
makePrism()
TopoDS_Shape PrismExtension::makePrism (double height, const TopoDS_Face & face) const
References FirstAngle, App::PropertyQuantity::getValue(), and SecondAngle.
Referenced by Part::Cylinder::execute(), Part::Prism::execute(), PartDesign::Cylinder::execute(), and PartDesign::Prism::execute().
Member Data Documentation
FirstAngle
App::PropertyAngle Part::PrismExtension::FirstAngle
Referenced by PartGui::DlgPrimitives::DlgPrimitives(), extensionMustExecute(), makePrism(), PartDesignGui::TaskBoxPrimitives::onCylinderXSkewChanged(), PartDesignGui::TaskBoxPrimitives::onPrismXSkewChanged(), and PartDesignGui::TaskBoxPrimitives::TaskBoxPrimitives().
SecondAngle
App::PropertyAngle Part::PrismExtension::SecondAngle
Referenced by PartGui::DlgPrimitives::DlgPrimitives(), extensionMustExecute(), makePrism(), PartDesignGui::TaskBoxPrimitives::onCylinderYSkewChanged(), PartDesignGui::TaskBoxPrimitives::onPrismYSkewChanged(), and PartDesignGui::TaskBoxPrimitives::TaskBoxPrimitives().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/App/PrismExtension.h
FreeCAD/src/Mod/Part/App/PrismExtension.cpp