FreeCAD: MED::TTimeStampValue< TMeshValueType > Struct Template Reference
MED::TTimeStampValue< TMeshValueType > Struct Template Reference
The class implements a container for MED TimeStamp values.
#include <MED_Structures.hxx>
Public Types
typedef SharedPtr< TMeshValueType > PTMeshValue
typedef TMeshValueType::TElement TElement
typedef std::map< EGeometrieElement, PTMeshValue > TTGeom2Value
typedef TMeshValueType TTMeshValue
Public Member Functions
const TTGeom2Value & GetGeom2Value () const
TTMeshValue & GetMeshValue (EGeometrieElement theGeom)
Gets MED TimeStamp values for the given geometric type.
const TTMeshValue & GetMeshValue (EGeometrieElement theGeom) const
Gets MED TimeStamp values for the given geometric type (const version)
PTMeshValue & GetMeshValuePtr (EGeometrieElement theGeom)
Gets MED TimeStamp values for the given geometric type.
const PTMeshValue & GetMeshValuePtr (EGeometrieElement theGeom) const
Gets MED TimeStamp values for the given geometric type (const version)
virtual ETypeChamp GetTypeChamp () const
Gets type of the champ.
Public Member Functions inherited from MED::TTimeStampValueBase
virtual void AllocateValue (EGeometrieElement theGeom, TInt theNbElem, TInt theNbGauss, TInt theNbComp, EModeSwitch theMode=eFULL_INTERLACE)=0
Allocates values for the given geometry.
const TGeom2Profile & GetGeom2Profile () const
Gets a map of MED Profiles per geometric type.
const TGeomSet & GetGeomSet () const
virtual size_t GetNbGauss (EGeometrieElement theGeom) const =0
virtual size_t GetNbVal (EGeometrieElement theGeom) const =0
const PTimeStampInfo & GetTimeStampInfo () const
virtual ETypeChamp GetTypeChamp () const =0
Gets type of the champ.
virtual unsigned char * GetValuePtr (EGeometrieElement theGeom)=0
virtual size_t GetValueSize (EGeometrieElement theGeom) const =0
Public Member Functions inherited from MED::TModeSwitchInfo
EModeSwitch GetModeSwitch () const
TModeSwitchInfo ()
To construct instance of the class by default.
TModeSwitchInfo (EModeSwitch theModeSwitch)
To construct instance of the class.
Public Member Functions inherited from MED::TBase
virtual ~TBase ()
Public Attributes
TTGeom2Value myGeom2Value
Keeps map of MED TimeStamp values per geometric type (const version)
ETypeChamp myTypeChamp
Public Attributes inherited from MED::TTimeStampValueBase
TGeom2Profile myGeom2Profile
Keeps map of MED Profiles per geometric type.
TGeomSet myGeomSet
Keeps set of MED EGeometrieElement which contains values for the timestamp.
PTimeStampInfo myTimeStampInfo
A reference to corresponding MED TimeStamp.
Public Attributes inherited from MED::TModeSwitchInfo
EModeSwitch myModeSwitch
Keeps the.
Detailed Description
template<class TMeshValueType>
struct MED::TTimeStampValue< TMeshValueType >
The class implements a container for MED TimeStamp values.
Member Typedef Documentation
PTMeshValue
template<class TMeshValueType > typedef SharedPtr<TMeshValueType> MED::TTimeStampValue< TMeshValueType >::PTMeshValue
TElement
template<class TMeshValueType > typedef TMeshValueType::TElement MED::TTimeStampValue< TMeshValueType >::TElement
TTGeom2Value
template<class TMeshValueType > typedef std::map<EGeometrieElement, PTMeshValue> MED::TTimeStampValue< TMeshValueType >::TTGeom2Value
TTMeshValue
template<class TMeshValueType > typedef TMeshValueType MED::TTimeStampValue< TMeshValueType >::TTMeshValue
Member Function Documentation
GetGeom2Value()
template<class TMeshValueType > const TTGeom2Value & MED::TTimeStampValue< TMeshValueType >::GetGeom2Value () const
References MED::TTimeStampValue< TMeshValueType >::myGeom2Value.
GetMeshValue() [1/2]
template<class TMeshValueType > TTMeshValue & MED::TTimeStampValue< TMeshValueType >::GetMeshValue (EGeometrieElement theGeom)
Gets MED TimeStamp values for the given geometric type.
References MED::TTimeStampValue< TMeshValueType >::GetMeshValuePtr().
GetMeshValue() [2/2]
template<class TMeshValueType > const TTMeshValue & MED::TTimeStampValue< TMeshValueType >::GetMeshValue (EGeometrieElement theGeom) const
Gets MED TimeStamp values for the given geometric type (const version)
References MED::TTimeStampValue< TMeshValueType >::GetMeshValuePtr().
Referenced by MED::TTTimeStampValue< eVersion, TMeshValueType >::AllocateValue(), MED::TTTimeStampValue< eVersion, TMeshValueType >::GetNbGauss(), MED::TTTimeStampValue< eVersion, TMeshValueType >::GetNbVal(), MED::TTTimeStampValue< eVersion, TMeshValueType >::GetValuePtr(), MED::TTTimeStampValue< eVersion, TMeshValueType >::GetValueSize(), and MED::TTTimeStampValue< eVersion, TMeshValueType >::TTTimeStampValue().
GetMeshValuePtr() [1/2]
template<class TMeshValueType > PTMeshValue & MED::TTimeStampValue< TMeshValueType >::GetMeshValuePtr (EGeometrieElement theGeom)
Gets MED TimeStamp values for the given geometric type.
References MED::TTimeStampValue< TMeshValueType >::myGeom2Value, and MED::TTimeStampValueBase::myGeomSet.
GetMeshValuePtr() [2/2]
template<class TMeshValueType > const PTMeshValue & MED::TTimeStampValue< TMeshValueType >::GetMeshValuePtr (EGeometrieElement theGeom) const
Gets MED TimeStamp values for the given geometric type (const version)
References MED::TTimeStampValue< TMeshValueType >::myGeom2Value.
Referenced by MED::TTimeStampValue< TMeshValueType >::GetMeshValue().
GetTypeChamp()
template<class TMeshValueType > virtual ETypeChamp MED::TTimeStampValue< TMeshValueType >::GetTypeChamp () const virtual
Gets type of the champ.
Implements MED::TTimeStampValueBase.
References MED::TTimeStampValue< TMeshValueType >::myTypeChamp.
Member Data Documentation
myGeom2Value
template<class TMeshValueType > TTGeom2Value MED::TTimeStampValue< TMeshValueType >::myGeom2Value
Keeps map of MED TimeStamp values per geometric type (const version)
Referenced by MED::CopyTimeStampValue(), MED::TTimeStampValue< TMeshValueType >::GetGeom2Value(), MED::TTimeStampValue< TMeshValueType >::GetMeshValuePtr(), and MED::TTTimeStampValue< eVersion, TMeshValueType >::TTTimeStampValue().
myTypeChamp
template<class TMeshValueType > ETypeChamp MED::TTimeStampValue< TMeshValueType >::myTypeChamp
Referenced by MED::TTimeStampValue< TMeshValueType >::GetTypeChamp(), and MED::TTTimeStampValue< eVersion, TMeshValueType >::TTTimeStampValue().
The documentation for this struct was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/inc/MED_Structures.hxx