FreeCAD: MeshGui::SoFCMeshVertexElement Class Reference
MeshGui::SoFCMeshVertexElement Class Reference
#include <SoFCMeshVertex.h>
Public Member Functions
virtual void init (SoState *state)
virtual void print (FILE *file) const
Static Public Member Functions
static const MeshCore::MeshPointArray * get (SoState *const state)
static const SoFCMeshVertexElement * getInstance (SoState *state)
static void initClass (void)
static void set (SoState *const state, SoNode *const node, const MeshCore::MeshPointArray *const coords)
Protected Member Functions
virtual ~SoFCMeshVertexElement ()
Protected Attributes
const MeshCore::MeshPointArray * coords3D
Constructor & Destructor Documentation
~SoFCMeshVertexElement()
SoFCMeshVertexElement::~SoFCMeshVertexElement () protected virtual
Member Function Documentation
get()
const MeshCore::MeshPointArray * SoFCMeshVertexElement::get (SoState *const state) static
References coords3D, and getInstance().
Referenced by MeshGui::SoFCMeshFaceSet::computeBBox(), MeshGui::SoFCMeshOpenEdgeSet::computeBBox(), MeshGui::SoFCMeshFaceSet::generatePrimitives(), MeshGui::SoFCMeshOpenEdgeSet::generatePrimitives(), MeshGui::SoFCMeshFaceSet::GLRender(), MeshGui::SoFCMeshOpenEdgeSet::GLRender(), and draftguitools.gui_trackers.editTracker::move().
getInstance()
const SoFCMeshVertexElement * SoFCMeshVertexElement::getInstance (SoState * state) static
Referenced by get().
init()
void SoFCMeshVertexElement::init (SoState * state) virtual
References coords3D.
Referenced by DocumentObject.DocumentObject::onChanged().
initClass()
void SoFCMeshVertexElement::initClass (void) static
print()
void SoFCMeshVertexElement::print (FILE * file) const virtual
set()
void SoFCMeshVertexElement::set (SoState *const state, SoNode *const node, const MeshCore::MeshPointArray *const coords) static
References coords3D.
Referenced by MeshGui::SoFCMeshVertex::doAction(), and draftguitools.gui_trackers.editTracker::move().
Member Data Documentation
coords3D
const MeshCore::MeshPointArray* MeshGui::SoFCMeshVertexElement::coords3D protected
Referenced by get(), init(), and set().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/Gui/SoFCMeshVertex.h
FreeCAD/src/Mod/Mesh/Gui/SoFCMeshVertex.cpp