FreeCAD: MED::TShapeFun::TFun Class Reference
MED::TShapeFun::TFun Class Reference
Public Member Functions
TFloatVecSlice GetFunSlice (TInt theGaussId)
TCFloatVecSlice GetFunSlice (TInt theGaussId) const
void Init (TInt theNbGauss, TInt theNbRef)
Member Function Documentation
GetFunSlice() [1/2]
TFloatVecSlice MED::TShapeFun::TFun::GetFunSlice (TInt theGaussId)
GetFunSlice() [2/2]
TCFloatVecSlice MED::TShapeFun::TFun::GetFunSlice (TInt theGaussId) const
Referenced by MED::TShapeFun::Eval(), MED::TSeg2a::InitFun(), MED::TSeg3a::InitFun(), MED::TTria3a::InitFun(), MED::TTria6a::InitFun(), MED::TTria3b::InitFun(), MED::TTria6b::InitFun(), MED::TQuad4a::InitFun(), MED::TQuad8a::InitFun(), MED::TQuad9a::InitFun(), MED::TQuad4b::InitFun(), MED::TQuad8b::InitFun(), MED::TQuad9b::InitFun(), MED::TTetra4a::InitFun(), MED::TTetra10a::InitFun(), MED::TTetra4b::InitFun(), MED::TTetra10b::InitFun(), MED::THexa8a::InitFun(), MED::THexa20a::InitFun(), MED::THexa27a::InitFun(), MED::THexa8b::InitFun(), MED::THexa20b::InitFun(), MED::TPenta6a::InitFun(), MED::TPenta6b::InitFun(), MED::TPenta15a::InitFun(), MED::TPenta15b::InitFun(), MED::TPyra5a::InitFun(), MED::TPyra5b::InitFun(), MED::TPyra13a::InitFun(), and MED::TPyra13b::InitFun().
Init()
void MED::TShapeFun::TFun::Init (TInt theNbGauss, TInt theNbRef)
Referenced by MED::TShapeFun::GetFun().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/MED_GaussUtils.cpp