FreeCAD: PartGui::Ui_TaskSweep Class Reference
PartGui::Ui_TaskSweep Class Reference
#include <ui_TaskSweep.h>
Public Member Functions
void retranslateUi (QWidget *PartGui__TaskSweep)
void setupUi (QWidget *PartGui__TaskSweep)
Public Attributes
QPushButton * buttonPath
QCheckBox * checkFrenet
QCheckBox * checkSolid
QGridLayout * gridLayout
QSpacerItem * horizontalSpacer
QSpacerItem * horizontalSpacer_2
QLabel * labelPath
Gui::ActionSelector * selector
Member Function Documentation
retranslateUi()
void PartGui::Ui_TaskSweep::retranslateUi (QWidget * PartGui__TaskSweep)
References buttonPath, checkFrenet, checkSolid, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void PartGui::Ui_TaskSweep::setupUi (QWidget * PartGui__TaskSweep)
References buttonPath, checkFrenet, checkSolid, gridLayout, horizontalSpacer, horizontalSpacer_2, labelPath, retranslateUi(), and selector.
Referenced by PartGui::SweepWidget::SweepWidget().
Member Data Documentation
buttonPath
QPushButton* PartGui::Ui_TaskSweep::buttonPath
Referenced by PartGui::SweepWidget::accept(), PartGui::SweepWidget::reject(), retranslateUi(), and setupUi().
checkFrenet
QCheckBox* PartGui::Ui_TaskSweep::checkFrenet
Referenced by PartGui::SweepWidget::accept(), retranslateUi(), and setupUi().
checkSolid
QCheckBox* PartGui::Ui_TaskSweep::checkSolid
Referenced by PartGui::SweepWidget::accept(), retranslateUi(), and setupUi().
gridLayout
QGridLayout* PartGui::Ui_TaskSweep::gridLayout
Referenced by setupUi().
horizontalSpacer
QSpacerItem* PartGui::Ui_TaskSweep::horizontalSpacer
Referenced by setupUi().
horizontalSpacer_2
QSpacerItem* PartGui::Ui_TaskSweep::horizontalSpacer_2
Referenced by setupUi().
labelPath
QLabel* PartGui::Ui_TaskSweep::labelPath
Referenced by setupUi(), and PartGui::SweepWidget::SweepWidget().
selector
Gui::ActionSelector* PartGui::Ui_TaskSweep::selector
Referenced by PartGui::SweepWidget::accept(), setupUi(), and PartGui::SweepWidget::SweepWidget().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Part/Gui/ui_TaskSweep.h