FreeCAD: PartDesignGui::TaskDlgDressUpParameters Class Reference
PartDesignGui::TaskDlgDressUpParameters Class Reference
simulation dialog for the TaskView
#include <TaskDressUpParameters.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
ViewProviderDressUp * getDressUpView () const
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgDressUpParameters (ViewProviderDressUp *DressUpView)
virtual ~TaskDlgDressUpParameters ()
Public Member Functions inherited from PartDesignGui::TaskDlgFeatureParameters
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgFeatureParameters (PartDesignGui::ViewProvider *vp)
PartDesignGui::ViewProvider * viewProvider () const
Returns the view provider dialog is runed for.
virtual ~TaskDlgFeatureParameters ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
tells the framework which buttons are wished for the dialog
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Protected Attributes
TaskDressUpParameters * parameter
Protected Attributes inherited from PartDesignGui::TaskDlgFeatureParameters
PartDesignGui::ViewProvider * vp
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
simulation dialog for the TaskView
Constructor & Destructor Documentation
TaskDlgDressUpParameters()
TaskDlgDressUpParameters::TaskDlgDressUpParameters (ViewProviderDressUp * DressUpView)
~TaskDlgDressUpParameters()
TaskDlgDressUpParameters::~TaskDlgDressUpParameters () virtual
Member Function Documentation
accept()
bool TaskDlgDressUpParameters::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from PartDesignGui::TaskDlgFeatureParameters.
Reimplemented in PartDesignGui::TaskDlgChamferParameters, PartDesignGui::TaskDlgDraftParameters, PartDesignGui::TaskDlgFilletParameters, and PartDesignGui::TaskDlgThicknessParameters.
References PartDesignGui::TaskDlgFeatureParameters::accept(), Gui::Command::Doc, PartDesignGui::TaskDressUpParameters::getBase(), getDressUpView(), Gui::ViewProviderDocumentObject::getObject(), Gui::Command::getObjectCmd(), PartDesignGui::TaskDressUpParameters::getReferences(), PartDesignGui::ViewProviderDressUp::highlightReferences(), parameter, and PartDesignGui::TaskDlgFeatureParameters::vp.
Referenced by PartDesignGui::TaskDlgChamferParameters::accept(), PartDesignGui::TaskDlgDraftParameters::accept(), PartDesignGui::TaskDlgFilletParameters::accept(), PartDesignGui::TaskDlgThicknessParameters::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
getDressUpView()
ViewProviderDressUp * PartDesignGui::TaskDlgDressUpParameters::getDressUpView () const
References PartDesignGui::TaskDlgFeatureParameters::vp.
Referenced by accept(), and reject().
reject()
bool TaskDlgDressUpParameters::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from PartDesignGui::TaskDlgFeatureParameters.
References getDressUpView(), PartDesignGui::ViewProviderDressUp::highlightReferences(), and PartDesignGui::TaskDlgFeatureParameters::reject().
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
Member Data Documentation
parameter
TaskDressUpParameters* PartDesignGui::TaskDlgDressUpParameters::parameter protected
Referenced by PartDesignGui::TaskDlgChamferParameters::accept(), PartDesignGui::TaskDlgDraftParameters::accept(), accept(), PartDesignGui::TaskDlgFilletParameters::accept(), PartDesignGui::TaskDlgThicknessParameters::accept(), Mod.Test.Document.DocumentObserverCases.Observer::slotAbortTransaction(), Mod.Test.Document.DocumentObserverCases.Observer::slotActivateDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotActivateDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotAddedDynamicExtension(), Mod.Test.Document.DocumentObserverCases.Observer::slotAppendDynamicProperty(), Mod.Test.Document.DocumentObserverCases.Observer::slotBeforeAddingDynamicExtension(), Mod.Test.Document.DocumentObserverCases.Observer::slotBeforeChangeDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotBeforeChangeObject(), Mod.Test.Document.DocumentObserverCases.Observer::slotChangedDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotChangedObject(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotChangedObject(), Mod.Test.Document.DocumentObserverCases.Observer::slotChangePropertyEditor(), Mod.Test.Document.DocumentObserverCases.Observer::slotCommitTransaction(), Mod.Test.Document.DocumentObserverCases.Observer::slotCreatedDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotCreatedDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotCreatedObject(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotCreatedObject(), Mod.Test.Document.DocumentObserverCases.Observer::slotDeletedDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotDeletedDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotDeletedObject(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotDeletedObject(), Mod.Test.Document.DocumentObserverCases.Observer::slotFinishSaveDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotInEdit(), Mod.Test.Document.DocumentObserverCases.Observer::slotOpenTransaction(), Mod.Test.Document.DocumentObserverCases.Observer::slotRecomputedDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotRecomputedObject(), Mod.Test.Document.DocumentObserverCases.Observer::slotRedoDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotRelabelDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotRelabelDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotRemoveDynamicProperty(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotRenameDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotResetEdit(), Mod.Test.Document.DocumentObserverCases.Observer::slotStartSaveDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotUndoDocument(), PartDesignGui::TaskDlgChamferParameters::TaskDlgChamferParameters(), PartDesignGui::TaskDlgDraftParameters::TaskDlgDraftParameters(), PartDesignGui::TaskDlgFilletParameters::TaskDlgFilletParameters(), and PartDesignGui::TaskDlgThicknessParameters::TaskDlgThicknessParameters().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/PartDesign/Gui/TaskDressUpParameters.h
FreeCAD/src/Mod/PartDesign/Gui/TaskDressUpParameters.cpp