FreeCAD: Gui::Dialog::Ui_DlgOnlineHelp Class Reference
Gui::Dialog::Ui_DlgOnlineHelp Class Reference
#include <ui_DlgOnlineHelp.h>
Public Member Functions
void retranslateUi (QWidget *Gui__Dialog__DlgOnlineHelp)
void setupUi (QWidget *Gui__Dialog__DlgOnlineHelp)
Public Attributes
QGridLayout * gridLayout
QGridLayout * gridLayout1
QGroupBox * GroupBoxOther
Gui::PrefFileChooser * prefStartPage
QSpacerItem * spacerItem
QLabel * TextLabelURL
Member Function Documentation
retranslateUi()
void Gui::Dialog::Ui_DlgOnlineHelp::retranslateUi (QWidget * Gui__Dialog__DlgOnlineHelp)
References GroupBoxOther, TextLabelURL, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::Dialog::Ui_DlgOnlineHelp::setupUi (QWidget * Gui__Dialog__DlgOnlineHelp)
References gridLayout, gridLayout1, GroupBoxOther, prefStartPage, retranslateUi(), spacerItem, and TextLabelURL.
Member Data Documentation
gridLayout
QGridLayout* Gui::Dialog::Ui_DlgOnlineHelp::gridLayout
Referenced by setupUi().
gridLayout1
QGridLayout* Gui::Dialog::Ui_DlgOnlineHelp::gridLayout1
Referenced by setupUi().
GroupBoxOther
QGroupBox* Gui::Dialog::Ui_DlgOnlineHelp::GroupBoxOther
Referenced by retranslateUi(), and setupUi().
prefStartPage
Gui::PrefFileChooser* Gui::Dialog::Ui_DlgOnlineHelp::prefStartPage
Referenced by setupUi().
spacerItem
QSpacerItem* Gui::Dialog::Ui_DlgOnlineHelp::spacerItem
Referenced by setupUi().
TextLabelURL
QLabel* Gui::Dialog::Ui_DlgOnlineHelp::TextLabelURL
Referenced by retranslateUi(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_DlgOnlineHelp.h