FreeCAD: Spreadsheet::SheetObserver Class Reference
Spreadsheet::SheetObserver Class Reference
#include <SheetObserver.h>
Public Member Functions
App::Document * getDocument () const
void ref ()
Increase reference count.
SheetObserver (App::Document *document, PropertySheet *_sheet)
The SheetObserver constructor.
virtual void slotChangedObject (const App::DocumentObject &Obj, const App::Property &Prop)
Invoke the sheets recomputeDependants when a change to a Property occurs.
virtual void slotCreatedObject (const App::DocumentObject &Obj)
Invalidate cells that depend on this document object.
virtual void slotDeletedObject (const App::DocumentObject &Obj)
Invalidate cells that depend on this document object.
bool unref ()
Decrease reference count.
~SheetObserver ()
Public Member Functions inherited from App::DocumentObserver
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
Additional Inherited Members
Protected Member Functions inherited from App::DocumentObserver
Document * getDocument () const
Constructor & Destructor Documentation
SheetObserver()
SheetObserver::SheetObserver (App::Document * document, PropertySheet * _sheet)
The SheetObserver constructor.
Parameters
document The Document we are observing
_sheet The sheet owning this observer.
~SheetObserver()
Spreadsheet::SheetObserver::~SheetObserver ()
Member Function Documentation
getDocument()
App::Document * Spreadsheet::SheetObserver::getDocument (void) const
References App::DocumentObserver::getDocument().
ref()
void SheetObserver::ref ()
Increase reference count.
slotChangedObject()
void SheetObserver::slotChangedObject (const App::DocumentObject & Obj, const App::Property & Prop) virtual
Invoke the sheets recomputeDependants when a change to a Property occurs.
Reimplemented from App::DocumentObserver.
References App::Property::getName(), App::ExtensionContainer::getPropertyName(), App::DocumentObject::Label, and Spreadsheet::PropertySheet::renamedDocumentObject().
slotCreatedObject()
void SheetObserver::slotCreatedObject (const App::DocumentObject & Obj) virtual
Invalidate cells that depend on this document object.
Reimplemented from App::DocumentObserver.
References Spreadsheet::PropertySheet::invalidateDependants().
slotDeletedObject()
void SheetObserver::slotDeletedObject (const App::DocumentObject & Obj) virtual
Invalidate cells that depend on this document object.
Reimplemented from App::DocumentObserver.
References Spreadsheet::PropertySheet::deletedDocumentObject(), and Spreadsheet::PropertySheet::invalidateDependants().
unref()
bool SheetObserver::unref ()
Decrease reference count.
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Spreadsheet/App/SheetObserver.h
FreeCAD/src/Mod/Spreadsheet/App/SheetObserver.cpp