FreeCAD: MengerSponge Namespace Reference
MengerSponge Namespace Reference
Classes
class MengerThread
Multi-threaded ###.
Functions
def makeMengerSponge (level=3, x0=0, y0=0, z0=0)
Single-threaded ###.
def makeMengerSponge_mt (level=3, x0=0, y0=0, z0=0)
def PlaceBox (x, y, z)
def Sierpinski (level, x0, y0, z0)
Variables
box = Mesh.createBox(1,1,1)
Function Documentation
makeMengerSponge()
def MengerSponge.makeMengerSponge (level = 3, x0 = 0, y0 = 0, z0 = 0)
Single-threaded ###.
References Sierpinski().
makeMengerSponge_mt()
def MengerSponge.makeMengerSponge_mt (level = 3, x0 = 0, y0 = 0, z0 = 0)
Is much slower than makeMengerSponge!!! :(
References Sierpinski().
PlaceBox()
def MengerSponge.PlaceBox (x, y, z)
Referenced by Sierpinski().
Sierpinski()
def MengerSponge.Sierpinski (level, x0, y0, z0)
References PlaceBox(), and Sierpinski().
Referenced by makeMengerSponge(), makeMengerSponge_mt(), MengerSponge.MengerThread.run(), and Sierpinski().
Variable Documentation
box
MengerSponge.box = Mesh.createBox(1,1,1)