FreeCAD: GCS::Line Class Reference
GCS::Line Class Reference
#include <Geo.h>
Public Member Functions
DeriVector2 CalculateNormal (const Point &p, const double *derivparam=nullptr) const override
virtual Line * Copy () override
Line ()
virtual int PushOwnParams (VEC_pD &pvec) override
virtual void ReconstructOnNewPvec (VEC_pD &pvec, int &cnt) override
DeriVector2 Value (double u, double du, const double *derivparam=nullptr) const override
Value: returns point (vector) given the value of parameter.
virtual ~Line ()
Public Member Functions inherited from GCS::Curve
virtual DeriVector2 CalculateNormal (const Point &p, const double *derivparam=nullptr) const =0
virtual Curve * Copy ()=0
virtual int PushOwnParams (VEC_pD &pvec)=0
virtual void ReconstructOnNewPvec (VEC_pD &pvec, int &cnt)=0
virtual DeriVector2 Value (double u, double du, const double *derivparam=nullptr) const
Value: returns point (vector) given the value of parameter.
virtual ~Curve ()
Public Attributes
Point p1
Point p2
Constructor & Destructor Documentation
Line()
GCS::Line::Line ()
Referenced by Copy().
~Line()
virtual GCS::Line::~Line () virtual
Member Function Documentation
CalculateNormal()
DeriVector2 Line::CalculateNormal (const Point & p, const double * derivparam = nullptr) const override virtual
Implements GCS::Curve.
References p1, p2, GCS::DeriVector2::rotate90ccw(), and GCS::DeriVector2::subtr().
Copy()
Line * Line::Copy (void) override virtual
Implements GCS::Curve.
References Line().
PushOwnParams()
int Line::PushOwnParams (VEC_pD & pvec) override virtual
Implements GCS::Curve.
References p1, p2, GCS::Point::x, and GCS::Point::y.
Referenced by GCS::ConstraintEllipseTangentLine::ConstraintEllipseTangentLine(), and GCS::ConstraintEqualLineLength::ConstraintEqualLineLength().
ReconstructOnNewPvec()
void Line::ReconstructOnNewPvec (VEC_pD & pvec, int & cnt) override virtual
Implements GCS::Curve.
References p1, p2, GCS::Point::x, and GCS::Point::y.
Value()
DeriVector2 Line::Value (double u, double du, const double * derivparam = nullptr) const override virtual
Value: returns point (vector) given the value of parameter.
Parameters
u value of parameter
du derivative of parameter by derivparam
derivparam pointer to sketch parameter to calculate the derivative for
Returns
Reimplemented from GCS::Curve.
References GCS::DeriVector2::multD(), p1, p2, GCS::DeriVector2::subtr(), and GCS::DeriVector2::sum().
Member Data Documentation
p1
Point GCS::Line::p1
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_trackers.dimTracker::calc(), CalculateNormal(), draftguitools.gui_trackers.rectangleTracker::isInside(), PushOwnParams(), ReconstructOnNewPvec(), draftguitools.gui_trackers.dimTracker::update(), and Value().
p2
Point GCS::Line::p2
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_trackers.dimTracker::calc(), CalculateNormal(), draftviewproviders.view_dimension.ViewProviderLinearDimension::draw_dim_arrows(), draftguitools.gui_trackers.rectangleTracker::isInside(), PushOwnParams(), ReconstructOnNewPvec(), draftguitools.gui_trackers.dimTracker::update(), and Value().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/App/planegcs/Geo.h
FreeCAD/src/Mod/Sketcher/App/planegcs/Geo.cpp