FreeCAD: DriverMED Namespace Reference
DriverMED Namespace Reference
Functions
bool buildMeshGrille (const MED::PWrapper &theWrapper, const MED::PMeshInfo &theMeshInfo, SMESHDS_Mesh *theMesh, const TID2FamilyMap &myFamilies)
Reading the structured mesh and convert to non structured (by filling of smesh structure for non structured mesh)
bool checkFamilyID (DriverMED_FamilyPtr &aFamily, int anID, const TID2FamilyMap &myFamilies)
Ensure aFamily has a required ID.
const SMDS_MeshNode * FindNode (const SMDS_Mesh *theMesh, TInt theId)
MESHDRIVERMED_EXPORT int GetMedGeoType (SMDSAbs_EntityType smdsType)
const std::vector< MED::EGeometrieElement > & getMedTypesVec ()
MESHDRIVERMED_EXPORT SMDSAbs_EntityType GetSMDSType (int medType)
Function Documentation
buildMeshGrille()
bool DriverMED::buildMeshGrille (const MED::PWrapper & theWrapper, const MED::PMeshInfo & theMeshInfo, SMESHDS_Mesh * myMesh, const TID2FamilyMap & myFamilies)
Reading the structured mesh and convert to non structured (by filling of smesh structure for non structured mesh)
Parameters
theWrapper - PWrapper const pointer
theMeshInfo - PMeshInfo const pointer
myFamilies - a map of the family ID to the Family
Returns
TRUE, if successfully. Else FALSE
References SMESHDS_Mesh::AddEdgeWithID(), SMESHDS_Mesh::AddFaceWithID(), SMESHDS_Mesh::AddNodeWithID(), SMESHDS_Mesh::AddVolumeWithID(), checkFamilyID(), MED::eHEXA8, MED::eQUAD4, MED::eSEG2, and SMDS_MeshElement::GetType().
Referenced by DriverMED_R_SMESHDS_Mesh::Perform().
checkFamilyID()
bool DriverMED::checkFamilyID (DriverMED_FamilyPtr & aFamily, int anID, const TID2FamilyMap & myFamilies)
Ensure aFamily has a required ID.
Ensure aFamily to have required ID.
Parameters
aFamily - a family to check
anID - an ID aFamily should have
myFamilies - a map of the family ID to the Family
Return values
bool - true if successful
Parameters
aFamily - a family to check and update
anID - an ID aFamily should have
Return values
bool - true if successful
Referenced by buildMeshGrille(), and DriverMED_R_SMESHDS_Mesh::Perform().
FindNode()
const SMDS_MeshNode * DriverMED::FindNode (const SMDS_Mesh * theMesh, TInt theId)
References SMDS_Mesh::FindNode().
GetMedGeoType()
int DriverMED::GetMedGeoType (SMDSAbs_EntityType smdsType)
Returns MED element geom type (MED::EGeometrieElement) by SMDS type
References getMedTypesVec().
Referenced by DriverMED_W_Field::Perform().
getMedTypesVec()
const std::vector< MED::EGeometrieElement > & DriverMED::getMedTypesVec ()
Returns a vector containing MED::EGeometrieElement for each SMDSAbs_EntityType
References MED::eAllGeoType, MED::eBALL, MED::eHEXA20, MED::eHEXA27, MED::eHEXA8, MED::eNONE, MED::eOCTA12, MED::ePENTA15, MED::ePENTA6, MED::ePOINT1, MED::ePOLYEDRE, MED::ePOLYGONE, MED::ePYRA13, MED::ePYRA5, MED::eQUAD4, MED::eQUAD8, MED::eQUAD9, MED::eSEG2, MED::eSEG3, MED::eTETRA10, MED::eTETRA4, MED::eTRIA3, MED::eTRIA6, and MED::eTRIA7.
Referenced by GetMedGeoType(), and GetSMDSType().
GetSMDSType()
SMDSAbs_EntityType DriverMED::GetSMDSType (int medType)
Returns SMDS element geom type by MED type (MED::EGeometrieElement)
References DraftVecUtils::find(), and getMedTypesVec().