FreeCAD: PathScripts.post.example_pre Namespace Reference
PathScripts.post.example_pre Namespace Reference
Functions
def insert (filename, docname)
def open (filename)
def parse (inputstring)
Variables
LEVEL = PathLog.Level.INFO
pythonopen = open
Function Documentation
insert()
def PathScripts.post.example_pre.insert (filename, docname)
References PathScripts.post.example_pre.parse(), and PathScripts.post.example_pre.pythonopen.
Referenced by PathScripts.post.example_pre.open().
open()
def PathScripts.post.example_pre.open (filename)
References PathScripts.post.example_pre.insert().
parse()
def PathScripts.post.example_pre.parse (inputstring)
Referenced by PathScripts.post.example_pre.insert().
Variable Documentation
LEVEL
PathScripts.post.example_pre.LEVEL = PathLog.Level.INFO
pythonopen
PathScripts.post.example_pre.pythonopen = open
Referenced by PathScripts.post.example_pre.insert().