FreeCAD: Part::GeometryExtensionPy Class Reference
Part::GeometryExtensionPy Class Reference
The python export class for GeometryExtension.
#include <GeometryExtensionPy.h>
Public Types
typedef GeometryExtension * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
GeometryExtensionPy (GeometryExtension *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of GeometryExtensionPy.
static PyMethodDef Methods []
Methods structure of GeometryExtensionPy.
static PyTypeObject Type
Type structure of GeometryExtensionPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~GeometryExtensionPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * copy (PyObject *args)
implementer for the copy() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
callbacks and implementers for the python object attributes
Py::String getName (void) const
getter for the Name attribute
void setName (Py::String arg)
setter for the Name attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeometryExtension * getGeometryExtensionPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getName (PyObject *self, void *closure)
getter callback for the Name attribute
static int staticCallback_setName (PyObject *self, PyObject *value, void *closure)
setter callback for the Name attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeometryExtension.
Member Typedef Documentation
PointerType
typedef GeometryExtension* Part::GeometryExtensionPy::PointerType
Constructor & Destructor Documentation
~GeometryExtensionPy()
GeometryExtensionPy::~GeometryExtensionPy () protected
GeometryExtensionPy()
GeometryExtensionPy::GeometryExtensionPy (GeometryExtension * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
copy()
PyObject * GeometryExtensionPy::copy (PyObject * args)
implementer for the copy() method
References draftmake.make_clone::clone, getGeometryExtensionPtr(), and GetType().
Referenced by staticCallback_copy().
getCustomAttributes()
PyObject * GeometryExtensionPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getGeometryExtensionPtr()
GeometryExtension * GeometryExtensionPy::getGeometryExtensionPtr (void) const
getter for the object handled by this class
Referenced by copy(), getName(), and setName().
getName()
Py::String GeometryExtensionPy::getName (void) const
getter for the Name attribute
References getGeometryExtensionPtr(), and Part::GeometryExtension::getName().
Referenced by Part::GeometryBoolExtensionPy::representation(), Part::GeometryDoubleExtensionPy::representation(), Part::GeometryIntExtensionPy::representation(), Part::GeometryStringExtensionPy::representation(), Sketcher::ExternalGeometryExtensionPy::representation(), Sketcher::SketchGeometryExtensionPy::representation(), and staticCallback_getName().
GetType()
virtual PyTypeObject* Part::GeometryExtensionPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
Reimplemented in Sketcher::SketchGeometryExtensionPy, Sketcher::ExternalGeometryExtensionPy, Part::GeometryStringExtensionPy, Part::GeometryIntExtensionPy, Part::GeometryDoubleExtensionPy, and Part::GeometryBoolExtensionPy.
Referenced by copy().
PyInit()
int GeometryExtensionPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
Reimplemented in Sketcher::SketchGeometryExtensionPy, Sketcher::ExternalGeometryExtensionPy, Part::GeometryStringExtensionPy, Part::GeometryIntExtensionPy, Part::GeometryDoubleExtensionPy, and Part::GeometryBoolExtensionPy.
PyMake()
PyObject * GeometryExtensionPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string GeometryExtensionPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int GeometryExtensionPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setName()
void GeometryExtensionPy::setName (Py::String arg)
setter for the Name attribute
References getGeometryExtensionPtr(), and Part::GeometryExtension::setName().
Referenced by staticCallback_setName().
staticCallback_copy()
PyObject * GeometryExtensionPy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copy(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getName()
PyObject * GeometryExtensionPy::staticCallback_getName (PyObject * self, void * closure) static
getter callback for the Name attribute
References Base::BaseExceptionFreeCADError, getName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setName()
int GeometryExtensionPy::staticCallback_setName (PyObject * self, PyObject * value, void * closure) static
setter callback for the Name attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setName().
Member Data Documentation
GetterSetter
PyGetSetDef GeometryExtensionPy::GetterSetter static
Initial value:
= {
    {"Name",
        (getter) staticCallback_getName,
        (setter) staticCallback_setName,
        "Sets/returns the name of this extension.",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of GeometryExtensionPy.
Methods
PyMethodDef GeometryExtensionPy::Methods static
Initial value:
= {
    {"copy",
        reinterpret_cast<PyCFunction>( staticCallback_copy ),
        METH_VARARGS,
        "Create a copy of this geometry extension."
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of GeometryExtensionPy.
Type
PyTypeObject GeometryExtensionPy::Type static
Type structure of GeometryExtensionPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), Part::GeometryPy::setExtension(), Sketcher::ExternalGeometryFacadePy::setExtension(), and Sketcher::GeometryFacadePy::setExtension().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeometryExtensionPy.h
Sources/FreeCAD/src/Mod/Part/App/GeometryExtensionPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeometryExtensionPy.cpp