FreeCAD: iisTaskPanel Class Reference
iisTaskPanel Class Reference
#include <iistaskpanel.h>
Public Member Functions
void addStretch (int s=0)
void addWidget (QWidget *w)
iisTaskPanel (QWidget *parent=0)
void removeStretch ()
void removeWidget (QWidget *w)
void setScheme (iisTaskPanelScheme *scheme)
~iisTaskPanel ()
Protected Member Functions
virtual void paintEvent (QPaintEvent *event)
Protected Attributes
iisTaskPanelScheme * myScheme
QSpacerItem * mySpacer
Constructor & Destructor Documentation
iisTaskPanel()
iisTaskPanel::iisTaskPanel (QWidget * parent = 0)
References iisTaskPanelScheme::defaultScheme(), and myScheme.
~iisTaskPanel()
iisTaskPanel::~iisTaskPanel ()
Member Function Documentation
addStretch()
void iisTaskPanel::addStretch (int s = 0)
References mySpacer.
Referenced by SandboxGui::TaskPanelView::TaskPanelView().
addWidget()
void iisTaskPanel::addWidget (QWidget * w)
Referenced by SandboxGui::TaskPanelView::TaskPanelView().
paintEvent()
void iisTaskPanel::paintEvent (QPaintEvent * event) protected virtual
References myScheme, and iisTaskPanelScheme::panelBackground.
removeStretch()
void iisTaskPanel::removeStretch ()
References mySpacer.
removeWidget()
void iisTaskPanel::removeWidget (QWidget * w)
setScheme()
void iisTaskPanel::setScheme (iisTaskPanelScheme * scheme)
References myScheme.
Referenced by SandboxGui::TaskPanelView::TaskPanelView().
Member Data Documentation
myScheme
iisTaskPanelScheme* iisTaskPanel::myScheme protected
Referenced by iisTaskPanel(), paintEvent(), and setScheme().
mySpacer
QSpacerItem* iisTaskPanel::mySpacer protected
Referenced by addStretch(), and removeStretch().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/iisTaskPanel/src/iistaskpanel.h
Sources/FreeCAD/src/Gui/iisTaskPanel/src/iistaskpanel.cpp