FreeCAD: GCS::ConstraintP2PDistance Class Reference
GCS::ConstraintP2PDistance Class Reference
#include <Constraints.h>
Public Member Functions
ConstraintP2PDistance (Point &p1, Point &p2, double *d)
virtual double error ()
virtual ConstraintType getTypeId ()
virtual double grad (double *)
virtual double maxStep (MAP_pD_D &dir, double lim=1.)
virtual void rescale (double coef=1.)
Public Member Functions inherited from GCS::Constraint
Constraint ()
int findParamInPvec (double *param)
int getTag ()
bool isDriving () const
VEC_pD params ()
void redirectParams (MAP_pD_pD redirectionmap)
void revertParams ()
void setDriving (bool isdriving)
void setTag (int tagId)
virtual ~Constraint ()
Constructor & Destructor Documentation
ConstraintP2PDistance()
GCS::ConstraintP2PDistance::ConstraintP2PDistance (Point & p1, Point & p2, double * d)
References rescale(), GCS::Point::x, and GCS::Point::y.
Member Function Documentation
error()
double GCS::ConstraintP2PDistance::error () virtual
Reimplemented from GCS::Constraint.
References DraftVecUtils::dist().
Referenced by femmesh.gmshtools.GmshTools::read_and_set_new_mesh(), FreeCADInit.FCADLogger::report(), and femmesh.gmshtools.GmshTools::run_gmsh_with_geo().
getTypeId()
ConstraintType GCS::ConstraintP2PDistance::getTypeId (void) virtual
Reimplemented from GCS::Constraint.
References GCS::P2PDistance.
grad()
double GCS::ConstraintP2PDistance::grad (double * param) virtual
Reimplemented from GCS::Constraint.
maxStep()
double GCS::ConstraintP2PDistance::maxStep (MAP_pD_D & dir, double lim = 1.) virtual
Reimplemented from GCS::Constraint.
References DraftVecUtils::dist().
rescale()
void GCS::ConstraintP2PDistance::rescale (double coef = 1.) virtual
Reimplemented from GCS::Constraint.
Referenced by ConstraintP2PDistance().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Constraints.h
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Constraints.cpp