FreeCAD: e57::ScaledIntegerNodeImpl Class Reference
e57::ScaledIntegerNodeImpl Class Reference
#include <ScaledIntegerNodeImpl.h>
Public Member Functions
void checkLeavesInSet (const StringSet &pathNames, NodeImplSharedPtr origin) override
bool isDefined (const ustring &pathName) override
bool isTypeEquivalent (NodeImplSharedPtr ni) override
int64_t maximum ()
int64_t minimum ()
double offset ()
int64_t rawValue ()
double scale ()
ScaledIntegerNodeImpl (ImageFileImplWeakPtr destImageFile, double scaledValue=0., double scaledMinimum=0., double scaledMaximum=0., double scale=1.0, double offset=0.0)
ScaledIntegerNodeImpl (ImageFileImplWeakPtr destImageFile, int64_t value=0, int64_t minimum=0, int64_t maximum=0, double scale=1.0, double offset=0.0)
double scaledMaximum ()
double scaledMinimum ()
double scaledValue ()
NodeType type () const override
void writeXml (ImageFileImplSharedPtr imf, CheckedFile &cf, int indent, const char *forcedFieldName=nullptr) override
~ScaledIntegerNodeImpl () override=default
Public Member Functions inherited from e57::NodeImpl
void checkBuffers (const std::vector< SourceDestBuffer > &sdbufs, bool allowMissing)
void checkImageFileOpen (const char *srcFileName, int srcLineNumber, const char *srcFunctionName) const
virtual void checkLeavesInSet (const StringSet &pathNames, NodeImplSharedPtr origin)=0
ImageFileImplSharedPtr destImageFile ()
ustring elementName () const
bool findTerminalPosition (const NodeImplSharedPtr &target, uint64_t &countFromLeft)
virtual NodeImplSharedPtr get (const ustring &pathName)
ustring imageFileName () const
bool isAttached () const
virtual bool isDefined (const ustring &pathName)=0
bool isRoot () const
bool isTypeConstrained ()
virtual bool isTypeEquivalent (NodeImplSharedPtr ni)=0
NodeImplSharedPtr parent ()
ustring pathName () const
ustring relativePathName (const NodeImplSharedPtr &origin, ustring childPathName=ustring()) const
virtual void set (const StringList &fields, unsigned level, NodeImplSharedPtr ni, bool autoPathCreate=false)
virtual void set (const ustring &pathName, NodeImplSharedPtr ni, bool autoPathCreate=false)
virtual void setAttachedRecursive ()
void setParent (NodeImplSharedPtr parent, const ustring &elementName)
virtual NodeType type () const =0
virtual void writeXml (ImageFileImplSharedPtr imf, CheckedFile &cf, int indent, const char *forcedFieldName=nullptr)=0
virtual ~NodeImpl ()=default
Additional Inherited Members
Protected Member Functions inherited from e57::NodeImpl
NodeImplSharedPtr getRoot ()
virtual NodeImplSharedPtr lookup (const ustring &)
NodeImpl (ImageFileImplWeakPtr destImageFile)
NodeImpl & operator= (NodeImpl &n)
Protected Attributes inherited from e57::NodeImpl
ImageFileImplWeakPtr destImageFile_
ustring elementName_
bool isAttached_
NodeImplWeakPtr parent_
Constructor & Destructor Documentation
ScaledIntegerNodeImpl() [1/2]
e57::ScaledIntegerNodeImpl::ScaledIntegerNodeImpl (ImageFileImplWeakPtr destImageFile, int64_t value = 0, int64_t minimum = 0, int64_t maximum = 0, double scale = 1.0, double offset = 0.0)
Enforce the given bounds on raw value
References e57::E57_ERROR_VALUE_OUT_OF_BOUNDS, maximum(), minimum(), e57::NodeImpl::pathName(), rawValue(), and e57::toString().
ScaledIntegerNodeImpl() [2/2]
e57::ScaledIntegerNodeImpl::ScaledIntegerNodeImpl (ImageFileImplWeakPtr destImageFile, double scaledValue = 0., double scaledMinimum = 0., double scaledMaximum = 0., double scale = 1.0, double offset = 0.0)
Enforce the given bounds on raw value
References e57::E57_ERROR_VALUE_OUT_OF_BOUNDS, e57::NodeImpl::pathName(), scaledMaximum(), scaledMinimum(), scaledValue(), and e57::toString().
~ScaledIntegerNodeImpl()
e57::ScaledIntegerNodeImpl::~ScaledIntegerNodeImpl () override default
Member Function Documentation
checkLeavesInSet()
void e57::ScaledIntegerNodeImpl::checkLeavesInSet (const StringSet & pathNames, NodeImplSharedPtr origin) override virtual
We are a leaf node, so verify that we are listed in set.
Implements e57::NodeImpl.
References e57::E57_ERROR_NO_BUFFER_FOR_ELEMENT, e57::NodeImpl::pathName(), and e57::NodeImpl::relativePathName().
isDefined()
bool e57::ScaledIntegerNodeImpl::isDefined (const ustring & pathName) override virtual
We have no sub-structure, so if path not empty return false
Implements e57::NodeImpl.
References e57::NodeImpl::pathName().
isTypeEquivalent()
bool e57::ScaledIntegerNodeImpl::isTypeEquivalent (NodeImplSharedPtr ni) override virtual
Same node type?
Downcast to shared_ptr<ScaledIntegerNodeImpl>
minimum must match
maximum must match
scale must match
offset must match
ignore value_, doesn't have to match
Types match
Implements e57::NodeImpl.
References e57::E57_SCALED_INTEGER.
maximum()
int64_t e57::ScaledIntegerNodeImpl::maximum (void)
References e57::NodeImpl::checkImageFileOpen().
Referenced by ScaledIntegerNodeImpl().
minimum()
int64_t e57::ScaledIntegerNodeImpl::minimum (void)
References e57::NodeImpl::checkImageFileOpen().
Referenced by ScaledIntegerNodeImpl().
offset()
double e57::ScaledIntegerNodeImpl::offset ()
References e57::NodeImpl::checkImageFileOpen().
Referenced by gzip_utf8.GzipFile::read(), gzip_utf8.GzipFile::readline(), DraftGui.DraftToolBar::reset_ui_values(), gzip_utf8.GzipFile::rewind(), gzip_utf8.GzipFile::seek(), and gzip_utf8.GzipFile::write().
rawValue()
int64_t e57::ScaledIntegerNodeImpl::rawValue ()
References e57::NodeImpl::checkImageFileOpen().
Referenced by ScaledIntegerNodeImpl().
scale()
double e57::ScaledIntegerNodeImpl::scale ()
References e57::NodeImpl::checkImageFileOpen().
Referenced by automotive_design.cartesian_transformation_operator::scl(), config_control_design.cartesian_transformation_operator::scl(), ifc2x3.ifccartesiantransformationoperator::scl(), and ifc4.ifccartesiantransformationoperator::scl().
scaledMaximum()
double e57::ScaledIntegerNodeImpl::scaledMaximum ()
References e57::NodeImpl::checkImageFileOpen().
Referenced by ScaledIntegerNodeImpl().
scaledMinimum()
double e57::ScaledIntegerNodeImpl::scaledMinimum ()
References e57::NodeImpl::checkImageFileOpen().
Referenced by ScaledIntegerNodeImpl().
scaledValue()
double e57::ScaledIntegerNodeImpl::scaledValue ()
References e57::NodeImpl::checkImageFileOpen().
Referenced by ScaledIntegerNodeImpl().
type()
NodeType e57::ScaledIntegerNodeImpl::type () const override virtual
Implements e57::NodeImpl.
References e57::E57_SCALED_INTEGER.
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
writeXml()
void e57::ScaledIntegerNodeImpl::writeXml (ImageFileImplSharedPtr imf, CheckedFile & cf, int indent, const char * forcedFieldName = nullptr) override virtual
Don't need to write if are default values
Write value as child text, unless it is the default value
Implements e57::NodeImpl.
References e57::NodeImpl::elementName_, and e57::space().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/libE57Format/src/ScaledIntegerNodeImpl.h
FreeCAD/src/3rdParty/libE57Format/src/ScaledIntegerNodeImpl.cpp