FreeCAD: TechDraw::DrawDimHelper Class Reference
TechDraw::DrawDimHelper Class Reference
Additional functions for working with Dimensions.
#include <DrawDimHelper.h>
Static Public Member Functions
static gp_Pnt2d findClosestPoint (std::vector< hTrimCurve > hCurve2dList, Handle(Geom2d_Curve) boundary)
static TechDraw::DrawViewDimension * makeDistDim (DrawViewPart *dvp, std::string dimType, Base::Vector3d refMin, Base::Vector3d refMax, bool extent=false)
static void makeExtentDim (DrawViewPart *dvp, std::vector< std::string > edgeNames, int direction)
static std::pair< Base::Vector3d, Base::Vector3d > minMax (DrawViewPart *dvp, std::vector< std::string > edgeNames, int direction)
Detailed Description
Additional functions for working with Dimensions.
Member Function Documentation
findClosestPoint()
gp_Pnt2d DrawDimHelper::findClosestPoint (std::vector< hTrimCurve > hCurve2dList, Handle(Geom2d_Curve) boundary) static
References DraftVecUtils::dist().
Referenced by minMax().
makeDistDim()
DrawViewDimension * DrawDimHelper::makeDistDim (DrawViewPart * dvp, std::string dimType, Base::Vector3d refMin, Base::Vector3d refMax, bool extent = false) static
References TechDraw::DrawViewPart::add1CVToGV(), TechDraw::CosmeticExtension::addCosmeticVertex(), TechDraw::DrawView::findParentPage(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), Base::Interpreter(), TechDraw::DrawUtil::invertY(), App::DocumentObject::recomputeFeature(), TechDraw::DrawViewDimension::References2D, TechDraw::DrawView::requestPaint(), Base::InterpreterSingleton::runStringArg(), and App::PropertyLinkSubList::setValues().
Referenced by makeExtentDim().
makeExtentDim()
void DrawDimHelper::makeExtentDim (DrawViewPart * dvp, std::vector< std::string > edgeNames, int direction) static
References TechDraw::Vertex::cosmeticTag, TechDraw::DrawViewDimExtent::CosmeticTags, App::DocumentObject::getDocument(), TechDraw::DrawUtil::getIndexFromName(), App::DocumentObject::getNameInDocument(), TechDraw::DrawViewPart::getProjVertexByIndex(), TechDraw::DrawView::getScale(), App::PropertyLinkSubList::getSubValues(), Base::Interpreter(), makeDistDim(), minMax(), App::DocumentObject::recomputeFeature(), TechDraw::DrawViewDimension::References2D, Base::InterpreterSingleton::runStringArg(), App::Document::setStatus(), App::PropertyLinkSubList::setValue(), App::PropertyStringList::setValues(), and TechDraw::DrawViewDimExtent::Source.
minMax()
std::pair< Base::Vector3d, Base::Vector3d > DrawDimHelper::minMax (DrawViewPart * dvp, std::vector< std::string > edgeNames, int direction) static
References findClosestPoint(), draftgeoutils.general::geomType(), TechDraw::DrawViewPart::getEdgeGeometry(), TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::DrawUtil::getGeomTypeFromName(), and TechDraw::DrawUtil::getIndexFromName().
Referenced by TechDraw::DrawViewDimExtent::execute(), and makeExtentDim().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/App/DrawDimHelper.h
Sources/FreeCAD/src/Mod/TechDraw/App/DrawDimHelper.cpp