FreeCAD: MeshGui::DockEvaluateMeshImp Class Reference
MeshGui::DockEvaluateMeshImp Class Reference
The DockEvaluateMeshImp class creates a single instance and embeds it into a dock window.
#include <DlgEvaluateMeshImp.h>
Public Member Functions
QSize sizeHint () const
Returns an appropriate size hint for the dock window.
Public Member Functions inherited from MeshGui::DlgEvaluateMeshImp
DlgEvaluateMeshImp (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
Constructs a DlgEvaluateMeshImp which is a child of 'parent', with the widget flags set to 'f'.
void setMesh (Mesh::Feature *)
~DlgEvaluateMeshImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from App::DocumentObserver
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
Static Public Member Functions
static void destruct ()
static bool hasInstance ()
static DockEvaluateMeshImp * instance ()
Protected Member Functions
void closeEvent (QCloseEvent *e)
Destroys the dock window this object is embedded into without destroying itself.
DockEvaluateMeshImp (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
Constructs a DockEvaluateMeshImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
~DockEvaluateMeshImp ()
Destroys the object and frees any allocated resources.
Protected Member Functions inherited from MeshGui::DlgEvaluateMeshImp
void addViewProvider (const char *vp, const std::vector< Mesh::ElementIndex > &indices)
void changeEvent (QEvent *e)
void cleanInformation ()
void refreshList ()
void removeViewProvider (const char *vp)
void removeViewProviders ()
void showInformation ()
Protected Member Functions inherited from App::DocumentObserver
Document * getDocument () const
Additional Inherited Members
Protected Slots inherited from MeshGui::DlgEvaluateMeshImp
void on_analyzeAllTogether_clicked ()
void on_analyzeDegeneratedButton_clicked ()
void on_analyzeDuplicatedFacesButton_clicked ()
void on_analyzeDuplicatedPointsButton_clicked ()
void on_analyzeFoldsButton_clicked ()
void on_analyzeIndicesButton_clicked ()
void on_analyzeNonmanifoldsButton_clicked ()
void on_analyzeOrientationButton_clicked ()
void on_analyzeSelfIntersectionButton_clicked ()
void on_buttonBox_clicked (QAbstractButton *)
void on_checkDegenerationButton_clicked ()
void on_checkDuplicatedFacesButton_clicked ()
void on_checkDuplicatedPointsButton_clicked ()
void on_checkFoldsButton_clicked ()
void on_checkIndicesButton_clicked ()
void on_checkNonmanifoldsButton_clicked ()
void on_checkOrientationButton_clicked ()
void on_checkSelfIntersectionButton_clicked ()
void on_meshNameButton_activated (int)
void on_refreshButton_clicked ()
void on_repairAllTogether_clicked ()
void on_repairDegeneratedButton_clicked ()
void on_repairDuplicatedFacesButton_clicked ()
void on_repairDuplicatedPointsButton_clicked ()
void on_repairFoldsButton_clicked ()
void on_repairIndicesButton_clicked ()
void on_repairNonmanifoldsButton_clicked ()
void on_repairOrientationButton_clicked ()
void on_repairSelfIntersectionButton_clicked ()
Detailed Description
The DockEvaluateMeshImp class creates a single instance and embeds it into a dock window.
Author
Werner Mayer
Constructor & Destructor Documentation
DockEvaluateMeshImp()
DockEvaluateMeshImp::DockEvaluateMeshImp (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) protected
Constructs a DockEvaluateMeshImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
References Gui::DockWindowManager::addDockWindow(), and Gui::DockWindowManager::instance().
Referenced by instance().
~DockEvaluateMeshImp()
DockEvaluateMeshImp::~DockEvaluateMeshImp () protected
Destroys the object and frees any allocated resources.
Member Function Documentation
closeEvent()
void DockEvaluateMeshImp::closeEvent (QCloseEvent * e) protected
Destroys the dock window this object is embedded into without destroying itself.
References Gui::DockWindowManager::instance(), and Gui::DockWindowManager::removeDockWindow().
destruct()
void DockEvaluateMeshImp::destruct (void) static
Referenced by MeshGui::CleanupHandler::cleanup().
hasInstance()
bool DockEvaluateMeshImp::hasInstance () static
instance()
DockEvaluateMeshImp * DockEvaluateMeshImp::instance (void) static
References DockEvaluateMeshImp(), and Gui::getMainWindow().
sizeHint()
QSize DockEvaluateMeshImp::sizeHint () const
Returns an appropriate size hint for the dock window.
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/Gui/DlgEvaluateMeshImp.h
FreeCAD/src/Mod/Mesh/Gui/DlgEvaluateMeshImp.cpp