FreeCAD: TechDraw::DrawViewDimension Class Reference
TechDraw::DrawViewDimension Class Reference
#include <DrawViewDimension.h>
Public Types
enum RefType {
invalidRef , oneEdge , twoEdge , twoVertex ,
vertexEdge , threeVertex
}
Public Types inherited from App::DocumentObject
enum GSReason { GS_DEFAULT , GS_SELECT }
reason of calling getSubObjects()
enum OutListOption { OutListNoExpression = 1 , OutListNoHidden = 2 , OutListNoXLinked = 4 }
DAG handling This part of the interface deals with viewing the document as a DAG (directed acyclic graph).
Public Types inherited from App::ExtensionContainer
typedef std::map< Base::Type, App::Extension * >::iterator ExtensionIterator
Public Member Functions
DrawViewDimension ()
Constructor.
virtual bool has2DReferences (void) const
virtual bool has3DReferences (void) const
bool hasOverUnderTolerance (void) const
short mustExecute () const override
mustExecute We call this method to check if the object was modified to be invoked.
virtual ~DrawViewDimension ()
Public Member Functions inherited from TechDraw::DrawView
DrawView (void)
Constructor.
virtual ~DrawView ()
virtual App::DocumentObjectExecReturn * recompute () override
recalculate the Feature
bool isInClip ()
DrawViewClip * getClipGroup (void)
virtual DrawPage * findParentPage () const
virtual double autoScale (void) const
virtual double autoScale (double w, double h) const
virtual bool checkFit (void) const
virtual bool checkFit (DrawPage *) const
check if View is too big for page
virtual void setPosition (double x, double y, bool force=false)
virtual bool keepUpdated (void)
virtual double getScale (void) const
void checkScale (void)
void requestPaint (void)
virtual void handleXYLock (void)
virtual bool isLocked (void) const
virtual bool showLock (void) const
std::vector< TechDraw::DrawLeaderLine * > getLeaders (void) const
Public Member Functions inherited from App::DocumentObject
virtual App::Property * addDynamicProperty (const char *type, const char *name=0, const char *group=0, const char *doc=0, short attr=0, bool ro=false, bool hidden=false) override
virtual bool adjustRelativeLinks (const std::set< App::DocumentObject * > &inList, std::set< App::DocumentObject * > *visited=0)
Called to adjust link properties to avoid cyclic links.
virtual bool allowDuplicateLabel () const
virtual bool canLinkProperties () const
virtual int canLoadPartial () const
allow partial loading of dependent objects
void clearOutListCache () const
clear internal out list cache
virtual const char * detachFromDocument () override
DocumentObject (void)
Constructor.
void enforceRecompute ()
Enforce this document object to be recomputed.
App::Document * getDocument (void) const
gets the document in which this Object is handled
std::string getExportName (bool forced=false) const
returns the name that is safe to be exported to other document
virtual const PropertyExpressionEngine::ExpressionInfo getExpression (const ObjectIdentifier &path) const
virtual std::string getFullName () const override
Return the object full name of the form DocName::ObjName.
DocumentObjectGroup * getGroup () const
get group if object is part of a group, otherwise 0 is returned
long getID () const
Return the object ID that is unique within its owner document.
const std::vector< App::DocumentObject * > & getInList (void) const
std::set< App::DocumentObject * > getInListEx (bool recursive) const
Return a set of all objects linking to this object, including possible external parent objects.
void getInListEx (std::set< App::DocumentObject * > &inSet, bool recursive, std::vector< App::DocumentObject * > *inList=0) const
Get a set of all objects linking to this object, including possible external parent objects.
std::vector< App::DocumentObject * > getInListRecursive (void) const
get all objects link directly or indirectly to this object
virtual DocumentObject * getLinkedObject (bool recurse=true, Base::Matrix4D *mat=0, bool transform=false, int depth=0) const
Return the linked object with optional transformation.
const char * getNameInDocument (void) const
returns the name which is set in the document for this object (not the name property!)
const std::string & getOldLabel () const
const std::vector< App::DocumentObject * > & getOutList () const
returns a list of objects this object is pointing to by Links
std::vector< App::DocumentObject * > getOutList (int option) const
void getOutList (int option, std::vector< App::DocumentObject * > &res) const
std::vector< App::DocumentObject * > getOutListOfProperty (App::Property *) const
returns a list of objects linked by the property
std::vector< App::DocumentObject * > getOutListRecursive (void) const
returns a list of objects this object is pointing to by Links and all further descended
std::vector< std::pair< App::DocumentObject *, std::string > > getParents (int depth=0) const
Obtain top parents and subnames of this object using its InList.
std::vector< std::list< App::DocumentObject * > > getPathsByOutList (App::DocumentObject *to) const
get all possible paths from this to another object following the OutList
unsigned long getStatus () const
return the status bits
const char * getStatusString (void) const
get the status Message
virtual DocumentObject * getSubObject (const char *subname, PyObject **pyObj=0, Base::Matrix4D *mat=0, bool transform=true, int depth=0) const
Get the sub element/object by name.
std::vector< DocumentObject * > getSubObjectList (const char *subname) const
Return a list of objects referenced by a given subname including this object.
virtual std::vector< std::string > getSubObjects (int reason=0) const
Return name reference of all sub-objects.
virtual const char * getViewProviderNameOverride () const
This function is introduced to allow Python feature override its view provider.
const char * getViewProviderNameStored () const
virtual bool hasChildElement () const
return true to activate tree view group object handling and element visibility
virtual bool isAttachedToDocument () const override
virtual int isElementVisible (const char *element) const
Get sub-element visibility.
bool isError (void) const
set this feature to error
int isExporting () const
bool isInInList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the InList
bool isInInListRecursive (DocumentObject *objToTest) const
test if this object is in the InList and recursive further down
bool isInOutList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the OutList
bool isInOutListRecursive (DocumentObject *objToTest) const
test if the given object is in the OutList and recursive further down
bool isRecomputing () const
returns true if this objects is currently recomputing
bool isRemoving () const
returns true if this objects is currently removed from the document
bool isRestoring () const
returns true if this objects is currently restoring from file
bool isTouched (void) const
test if this document object is touched
bool isValid (void) const
bool mustRecompute (void) const
Test if this document object must be recomputed.
virtual void onBeforeChangeLabel (std::string &newLabel)
virtual void onLostLinkToObject (DocumentObject *)
Called in case of losing a link Get called by the document when a object got deleted a link property of this object ist pointing to.
virtual void onUpdateElementReference (const Property *)
void purgeError (void)
remove the error from the object
void purgeTouched (void)
reset this document object touched
bool recomputeFeature (bool recursive=false)
Recompute only this feature.
virtual bool redirectSubName (std::ostringstream &ss, DocumentObject *topParent, DocumentObject *child) const
Allow object to redirect a subname path.
virtual bool removeDynamicProperty (const char *prop) override
virtual void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths)
App::DocumentObject * resolve (const char *subname, App::DocumentObject **parent=0, std::string *childName=0, const char **subElement=0, PyObject **pyObj=0, Base::Matrix4D *mat=0, bool transform=true, int depth=0) const
Resolve the last document object referenced in the subname.
App::DocumentObject * resolveRelativeLink (std::string &subname, App::DocumentObject *&link, std::string &linkSub) const
Resolve a link reference that is relative to this object reference.
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
virtual int setElementVisible (const char *element, bool visible)
Child element handling.
virtual void setExpression (const ObjectIdentifier &path, boost::shared_ptr< App::Expression > expr)
void setStatus (ObjectStatus pos, bool on)
bool testIfLinkDAGCompatible (App::PropertyLinkSub &linkTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSubList &linksTo) const
bool testIfLinkDAGCompatible (const std::vector< DocumentObject * > &linksTo) const
bool testIfLinkDAGCompatible (DocumentObject *linkTo) const
testIfLinkIsDAG tests a link that is about to be created for circular references.
bool testStatus (ObjectStatus pos) const
void touch (bool noRecompute=false)
Set the property touched -> changed, cause recomputation in Update()
virtual ~DocumentObject ()
Public Member Functions inherited from App::TransactionalObject
TransactionalObject (void)
Constructor.
virtual ~TransactionalObject ()
Public Member Functions inherited from App::ExtensionContainer
ExtensionIterator extensionBegin ()
ExtensionContainer ()
ExtensionIterator extensionEnd ()
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
void registerExtension (Base::Type extension, App::Extension *ext)
virtual ~ExtensionContainer ()
virtual Property * getPropertyByName (const char *name) const override
find a property by its name
virtual const char * getPropertyName (const Property *prop) const override
get the name of a property
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
virtual void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
virtual short getPropertyType (const Property *prop) const override
get the Type of a Property
virtual short getPropertyType (const char *name) const override
get the Type of a named Property
virtual const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
Public Member Functions inherited from App::PropertyContainer
virtual App::Property * getDynamicPropertyByName (const char *name) const
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
const char * getPropertyPrefix () const
bool isHidden (const char *name) const
check if the named property is hidden
bool isHidden (const Property *prop) const
check if the property is hidden
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isReadOnly (const Property *prop) const
check if the property is read-only
PropertyContainer ()
A constructor.
void setPropertyPrefix (const char *prefix)
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
virtual ~PropertyContainer ()
A destructor.
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Attributes
App::PropertyBool Arbitrary
App::PropertyBool ArbitraryTolerances
App::PropertyBool EqualTolerance
App::PropertyString FormatSpec
App::PropertyString FormatSpecOverTolerance
App::PropertyString FormatSpecUnderTolerance
App::PropertyBool Inverted
App::PropertyEnumeration MeasureType
App::PropertyQuantityConstraint OverTolerance
App::PropertyLinkSubList References2D
App::PropertyLinkSubList References3D
App::PropertyBool TheoreticalExact
App::PropertyEnumeration Type
App::PropertyQuantityConstraint UnderTolerance
Public Attributes inherited from TechDraw::DrawView
App::PropertyString Caption
App::PropertyBool LockPosition
App::PropertyAngle Rotation
App::PropertyFloatConstraint Scale
App::PropertyEnumeration ScaleType
App::PropertyDistance X
App::PropertyDistance Y
boost::signals2::signal< void(const DrawView *)> signalGuiPaint
Public Attributes inherited from App::DocumentObject
PropertyExpressionEngine ExpressionEngine
PropertyString Label
PropertyString Label2
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChange
signal before changing a property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChanged
signal on changed property of this object
PropertyBool Visibility
Allow control visibility status in App name space.
methods override Feature
Measure::Measurement * measurement
pointPair m_linearPoints
pointPair m_arrowPositions
virtual App::DocumentObjectExecReturn * execute (void) override
recalculate the Feature
virtual const char * getViewProviderName (void) const override
returns the type name of the ViewProvider
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
virtual std::string getFormattedToleranceValue (int partial)
virtual std::pair< std::string, std::string > getFormattedToleranceValues (int partial=0)
virtual std::string getFormattedDimensionValue (int partial=0)
virtual std::string formatValue (qreal value, QString qFormatSpec, int partial=0)
virtual double getDimValue ()
NOTE: this returns the Dimension value in internal units (ie mm)!!!!
QStringList getPrefixSuffixSpec (QString fSpec)
virtual DrawViewPart * getViewPart () const
virtual QRectF getRect () const override
virtual int getRefType () const
void setAll3DMeasurement ()
add Dimension 3D references to measurement
void clear3DMeasurements (void)
virtual bool checkReferences2D (void) const
validate 2D references - only checks if the target exists
pointPair getLinearPoints (void)
arcPoints getArcPoints (void)
anglePoints getAnglePoints (void)
bool leaderIntersectsArc (Base::Vector3d s, Base::Vector3d pointOnCircle)
bool isMultiValueSchema (void) const
std::string getBaseLengthUnit (Base::UnitSystem system)
pointPair getArrowPositions (void)
void saveArrowPositions (const Base::Vector2d positions[])
bool showUnits () const
bool useDecimals () const
static int getRefTypeSubElements (const std::vector< std::string > &)
virtual void handleChangedPropertyType (Base::XMLReader &, const char *, App::Property *) override
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
virtual void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
virtual void onChanged (const App::Property *prop) override
get called by the container when a property was changed
virtual void onDocumentRestored () override
get called after a document has been fully restored
std::string getPrefix () const
std::string getDefaultFormatSpec (bool isToleranceFormat=false) const
virtual pointPair getPointsOneEdge ()
virtual pointPair getPointsTwoEdges ()
virtual pointPair getPointsTwoVerts ()
virtual pointPair getPointsEdgeVert ()
double dist2Segs (Base::Vector3d s1, Base::Vector3d e1, Base::Vector3d s2, Base::Vector3d e2) const
pointPair closestPoints (TopoDS_Shape s1, TopoDS_Shape s2) const
Additional Inherited Members
Static Public Member Functions inherited from App::DocumentObject
static const char * hasHiddenMarker (const char *subname)
Check if the subname reference ends with hidden marker.
static const std::string & hiddenMarker ()
Special marker to mark the object as hidden.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Public Attributes inherited from App::DocumentObject
static DocumentObjectExecReturn * StdReturn
Protected Member Functions inherited from TechDraw::DrawView
int prefScaleType (void)
double prefScale (void)
Protected Member Functions inherited from App::DocumentObject
App::DocumentObjectExecReturn * executeExtensions ()
Executes the extensions of a document object.
virtual void onBeforeChange (const Property *prop) override
get called before the value is changed
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus) override
get called when a property status has changed
virtual void onSettingDocument ()
get called after setting the document
virtual void onUndoRedoFinished ()
get called after an undo/redo transaction is finished
void resetError (void)
void setDocument (App::Document *doc)
void setError (void)
virtual void setupObject ()
get called after a brand new object was created
virtual void unsetupObject ()
get called when object is going to be removed from the document
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData (void) const
virtual void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container.
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from TechDraw::DrawView
std::string pageFeatName
bool autoPos
bool mouseMove
Protected Attributes inherited from App::DocumentObject
std::string oldLabel
Old label; used for renaming expressions.
const std::string * pcNameInDocument
Py::Object PythonObject
python object of this class and all descendent
std::bitset< 32 > StatusBits
Status bits of the document object The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Member Enumeration Documentation
RefType
enum TechDraw::DrawViewDimension::RefType
Enumerator
invalidRef
oneEdge
twoEdge
twoVertex
vertexEdge
threeVertex
Constructor & Destructor Documentation
DrawViewDimension()
DrawViewDimension::DrawViewDimension (void)
Constructor.
References Arbitrary, ArbitraryTolerances, TechDraw::arcPoints::arcCW, TechDraw::arcPoints::arcEnds, TechDraw::DrawView::Caption, TechDraw::arcPoints::center, TechDraw::anglePoints::ends, EqualTolerance, FormatSpec, FormatSpecOverTolerance, FormatSpecUnderTolerance, getDefaultFormatSpec(), App::Global, App::Property::Hidden, Inverted, TechDraw::arcPoints::isArc, Base::Unit::Length, TechDraw::DrawView::LockPosition, m_linearPoints, measurement, MeasureType, TechDraw::arcPoints::midArc, TechDraw::arcPoints::onCurve, OverTolerance, App::Prop_None, App::Prop_Output, App::Property::ReadOnly, References2D, References3D, TechDraw::DrawView::Rotation, TechDraw::DrawView::Scale, TechDraw::DrawView::ScaleType, App::PropertyQuantityConstraint::setConstraints(), App::PropertyEnumeration::setEnums(), App::ScopedLink::setScope(), App::Property::setStatus(), App::PropertyQuantity::setUnit(), TheoreticalExact, Type, UnderTolerance, and TechDraw::anglePoints::vertex.
~DrawViewDimension()
DrawViewDimension::~DrawViewDimension () virtual
References measurement.
Member Function Documentation
checkReferences2D()
bool DrawViewDimension::checkReferences2D (void) const virtual
validate 2D references - only checks if the target exists
Reimplemented in TechDraw::DrawViewDimExtent, and TechDraw::LandmarkDimension.
References Base::Console(), TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), App::DocumentObject::getNameInDocument(), TechDraw::DrawViewPart::getProjVertexByIndex(), App::PropertyLinkSubList::getSubValues(), App::PropertyLinkSubList::getValues(), getViewPart(), Base::ConsoleSingleton::Log(), and References2D.
Referenced by execute(), and getDimValue().
clear3DMeasurements()
void DrawViewDimension::clear3DMeasurements (void)
References Measure::Measurement::clear(), and measurement.
Referenced by onChanged(), and TechDrawGui::TaskLinkDim::updateDims().
closestPoints()
pointPair DrawViewDimension::closestPoints (TopoDS_Shape s1, TopoDS_Shape s2) const protected
Referenced by getPointsEdgeVert(), and getPointsTwoEdges().
dist2Segs()
double DrawViewDimension::dist2Segs (Base::Vector3d s1, Base::Vector3d e1, Base::Vector3d s2, Base::Vector3d e2) const protected
References Base::Vector3< _Precision >::x, and Base::Vector3< _Precision >::y.
execute()
App::DocumentObjectExecReturn * DrawViewDimension::execute (void) override virtual
recalculate the Feature
Reimplemented from TechDraw::DrawView.
Reimplemented in TechDraw::LandmarkDimension, and TechDraw::DrawViewDimExtent.
References TechDraw::Generic::apparentInter(), TechDraw::arcPoints::arcCW, TechDraw::arcPoints::arcEnds, TechDraw::arcPoints::center, TechDraw::Ellipse::center, checkReferences2D(), Base::Console(), TechDraw::AOE::cw, TechDraw::AOC::cw, TechDraw::BSpline::cw, TechDraw::AOE::endPnt, TechDraw::AOC::endPnt, TechDraw::BSpline::endPnt, TechDraw::anglePoints::ends, Base::ConsoleSingleton::Error(), TechDraw::DrawView::execute(), TechDraw::BaseGeom::geomType, TechDraw::BSpline::getCircleParms(), App::DocumentObject::getDocument(), TechDraw::BaseGeom::getEndPoint(), TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::DrawUtil::getIndexFromName(), App::DocumentObject::getNameInDocument(), getPointsEdgeVert(), getPointsOneEdge(), getPointsTwoEdges(), getPointsTwoVerts(), TechDraw::DrawViewPart::getProjVertexByIndex(), getRefType(), TechDraw::BaseGeom::getStartPoint(), App::PropertyLinkSubList::getSubValues(), getViewPart(), has2DReferences(), TechDraw::arcPoints::isArc, TechDraw::BSpline::isCircle(), App::DocumentObject::isRestoring(), App::PropertyEnumeration::isValue(), TechDraw::DrawView::keepUpdated(), Base::ConsoleSingleton::Log(), m_linearPoints, TechDraw::Ellipse::major, TechDraw::arcPoints::midArc, TechDraw::AOE::midPnt, TechDraw::AOC::midPnt, TechDraw::BSpline::midPnt, TechDraw::Ellipse::minor, TechDraw::arcPoints::onCurve, oneEdge, TechDraw::Vertex::point(), TechDraw::arcPoints::radius, References2D, TechDraw::AOE::startPnt, TechDraw::AOC::startPnt, TechDraw::BSpline::startPnt, App::DocumentObject::StdReturn, App::DocumentObject::testStatus(), threeVertex, twoEdge, twoVertex, Type, TechDraw::anglePoints::vertex, vertexEdge, Base::ConsoleSingleton::Warning(), Base::Vector3< _Precision >::x, and Base::Vector3< _Precision >::y.
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), PathScripts.PathDressupDogbone.ObjectDressup::boneStateList(), ArchSite.Compass::buildCoordinates(), TechDraw::DrawViewDimExtent::execute(), TechDraw::LandmarkDimension::execute(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::generateTags(), ArchPanel.PanelCut::getWires(), ArchSchedule.CommandArchSchedule::IsActive(), Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), FeaturePython.DistanceBolt::onChanged(), PathScripts.PathStock.StockFromBase::onChanged(), PathScripts.PathStock.StockCreateBox::onChanged(), PathScripts.PathStock.StockCreateCylinder::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), draftobjects.patharray.PathArray::onDocumentRestored(), and draftobjects.pathtwistedarray.PathTwistedArray::onDocumentRestored().
formatValue()
std::string DrawViewDimension::formatValue (qreal value, QString qFormatSpec, int partial = 0) virtual
References Base::Unit::Angle, Base::Console(), getBaseLengthUnit(), Base::UnitsApi::getDecimals(), App::DocumentObject::getNameInDocument(), getPrefix(), getPrefixSuffixSpec(), Base::UnitsApi::getSchema(), Base::Quantity::getUserString(), Base::Quantity::getValue(), Base::ImperialCivil, isMultiValueSchema(), App::PropertyEnumeration::isValue(), Base::Unit::Length, Base::Quantity::parse(), Base::Quantity::setUnit(), Base::Quantity::setValue(), showUnits(), Base::Tools::toStdString(), Type, useDecimals(), and Base::ConsoleSingleton::Warning().
Referenced by getFormattedDimensionValue(), getFormattedToleranceValue(), and getFormattedToleranceValues().
getAnglePoints()
anglePoints TechDraw::DrawViewDimension::getAnglePoints (void)
Referenced by TechDraw::DrawViewDimensionPy::getAnglePoints().
getArcPoints()
arcPoints TechDraw::DrawViewDimension::getArcPoints (void)
Referenced by TechDraw::DrawViewDimensionPy::getArcPoints().
getArrowPositions()
pointPair DrawViewDimension::getArrowPositions (void)
References m_arrowPositions.
Referenced by TechDraw::DrawViewDimensionPy::getArrowPositions().
getBaseLengthUnit()
std::string DrawViewDimension::getBaseLengthUnit (Base::UnitSystem system)
References Base::Centimeters, Base::FemMilliMeterNewton, Base::Imperial1, Base::ImperialBuilding, Base::ImperialCivil, Base::ImperialDecimal, Base::MmMin, Base::SI1, and Base::SI2.
Referenced by formatValue().
getDefaultFormatSpec()
std::string DrawViewDimension::getDefaultFormatSpec (bool isToleranceFormat = false) const protected
References Base::Tools::fromStdString(), App::GetApplication(), ParameterGrp::GetASCII(), Base::UnitsApi::getDecimals(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), getPrefix(), App::Application::GetUserParameter(), draftgeoutils.general::precision(), Base::Tools::toStdString(), and useDecimals().
Referenced by DrawViewDimension(), and onChanged().
getDimValue()
double DrawViewDimension::getDimValue () virtual
NOTE: this returns the Dimension value in internal units (ie mm)!!!!
References Measure::Measurement::angle(), checkReferences2D(), Base::Console(), TechDraw::anglePoints::ends, Base::Vector3< _Precision >::GetAngle(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), TechDraw::DrawView::getScale(), App::PropertyBool::getValue(), getViewPart(), has2DReferences(), Measure::Measurement::has3DReferences(), Inverted, App::DocumentObject::isRestoring(), App::PropertyEnumeration::isValue(), Measure::Measurement::length(), Base::Vector3< _Precision >::Length(), m_linearPoints, measurement, MeasureType, Measure::Measurement::radius(), TechDraw::arcPoints::radius, App::DocumentObject::testStatus(), Type, TechDraw::anglePoints::vertex, Base::ConsoleSingleton::Warning(), Base::Vector3< _Precision >::x, and Base::Vector3< _Precision >::y.
Referenced by getFormattedDimensionValue(), and TechDraw::DrawViewDimensionPy::getRawValue().
getFormattedDimensionValue()
std::string DrawViewDimension::getFormattedDimensionValue (int partial = 0) virtual
References Arbitrary, ArbitraryTolerances, EqualTolerance, FormatSpec, formatValue(), TechDraw::DrawUtil::fpCompare(), getDimValue(), getFormattedToleranceValue(), App::PropertyString::getStrValue(), App::PropertyBool::getValue(), App::PropertyQuantity::getValue(), App::PropertyEnumeration::isValue(), OverTolerance, TheoreticalExact, draftutils.utils::tolerance(), and Type.
Referenced by TechDraw::DrawViewDimensionPy::getText().
getFormattedToleranceValue()
std::string DrawViewDimension::getFormattedToleranceValue (int partial) virtual
References ArbitraryTolerances, FormatSpec, FormatSpecOverTolerance, formatValue(), App::PropertyString::getStrValue(), App::PropertyBool::getValue(), App::PropertyQuantity::getValue(), and OverTolerance.
Referenced by getFormattedDimensionValue().
getFormattedToleranceValues()
std::pair< std::string, std::string > DrawViewDimension::getFormattedToleranceValues (int partial = 0) virtual
References ArbitraryTolerances, FormatSpecOverTolerance, FormatSpecUnderTolerance, formatValue(), TechDraw::DrawUtil::fpCompare(), App::PropertyString::getStrValue(), App::PropertyBool::getValue(), App::PropertyQuantity::getValue(), OverTolerance, and UnderTolerance.
getLinearPoints()
pointPair TechDraw::DrawViewDimension::getLinearPoints (void)
Referenced by TechDraw::DrawViewDimensionPy::getLinearPoints().
getPointsEdgeVert()
pointPair DrawViewDimension::getPointsEdgeVert () protected virtual
References closestPoints(), Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), App::DocumentObject::getNameInDocument(), TechDraw::DrawViewPart::getProjVertexByIndex(), App::PropertyLinkSubList::getSubValues(), getViewPart(), and References2D.
Referenced by execute().
getPointsOneEdge()
pointPair DrawViewDimension::getPointsOneEdge () protected virtual
References Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::BaseGeom::geomType, TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::DrawUtil::getIndexFromName(), App::DocumentObject::getNameInDocument(), App::PropertyLinkSubList::getSubValues(), getViewPart(), TechDraw::Generic::points, and References2D.
Referenced by execute().
getPointsTwoEdges()
pointPair DrawViewDimension::getPointsTwoEdges () protected virtual
References closestPoints(), Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::DrawUtil::getIndexFromName(), App::DocumentObject::getNameInDocument(), App::PropertyLinkSubList::getSubValues(), getViewPart(), TechDraw::BaseGeom::occEdge, and References2D.
Referenced by execute().
getPointsTwoVerts()
pointPair DrawViewDimension::getPointsTwoVerts () protected virtual
Reimplemented in TechDraw::LandmarkDimension, and TechDraw::DrawViewDimExtent.
References Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::DrawUtil::getIndexFromName(), App::DocumentObject::getNameInDocument(), TechDraw::DrawViewPart::getProjVertexByIndex(), App::PropertyLinkSubList::getSubValues(), getViewPart(), and References2D.
Referenced by execute().
getPrefix()
std::string DrawViewDimension::getPrefix () const protected
References App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), App::PropertyEnumeration::isValue(), and Type.
Referenced by formatValue(), and getDefaultFormatSpec().
getPrefixSuffixSpec()
QStringList DrawViewDimension::getPrefixSuffixSpec (QString fSpec)
References Base::Console(), App::DocumentObject::getNameInDocument(), and Base::ConsoleSingleton::Warning().
Referenced by formatValue().
getPyObject()
PyObject * DrawViewDimension::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from TechDraw::DrawView.
Reimplemented in TechDraw::DrawViewDimExtent.
References App::DocumentObject::PythonObject.
getRect()
virtual QRectF TechDraw::DrawViewDimension::getRect (void) const override virtual
Reimplemented from TechDraw::DrawView.
getRefType()
int DrawViewDimension::getRefType () const virtual
Reimplemented in TechDraw::LandmarkDimension.
References getRefTypeSubElements(), App::PropertyLinkSubList::getSubValues(), and References2D.
Referenced by execute(), and TechDrawGui::TaskLinkDim::loadAvailDims().
getRefTypeSubElements()
int DrawViewDimension::getRefTypeSubElements (const std::vector< std::string > & subElements) static
References TechDraw::DrawUtil::getGeomTypeFromName(), invalidRef, oneEdge, threeVertex, twoEdge, twoVertex, and vertexEdge.
Referenced by getRefType(), and TechDrawGui::TaskLinkDim::loadAvailDims().
getViewPart()
DrawViewPart * DrawViewDimension::getViewPart () const virtual
Reimplemented in TechDraw::LandmarkDimension.
References App::PropertyLinkSubList::getValues(), and References2D.
Referenced by checkReferences2D(), TechDraw::DrawViewDimExtent::checkReferences2D(), TechDrawGui::QGIViewDimension::draw(), execute(), getDimValue(), getPointsEdgeVert(), getPointsOneEdge(), getPointsTwoEdges(), getPointsTwoVerts(), TechDraw::DrawViewDimExtent::getPointsTwoVerts(), leaderIntersectsArc(), saveArrowPositions(), and TechDraw::DrawViewDimExtent::unsetupObject().
getViewProviderName()
virtual const char* TechDraw::DrawViewDimension::getViewProviderName (void) const override virtual
returns the type name of the ViewProvider
Reimplemented from TechDraw::DrawView.
Reimplemented in TechDraw::LandmarkDimension.
handleChangedPropertyType()
void DrawViewDimension::handleChangedPropertyType (Base::XMLReader & reader, const char * TypeName, App::Property * prop) override protected virtual
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
This method is typically called if the property on file has changed its type in more recent versions.
The default implementation does nothing.
Parameters
reader The XML stream to read from.
TypeName Name of property type on file.
prop Pointer to property to restore. Its type differs from TypeName.
Reimplemented from TechDraw::DrawView.
References App::PropertyQuantity::getValue(), TechDraw::DrawView::handleChangedPropertyType(), OverTolerance, App::PropertyFloat::Restore(), App::PropertyQuantity::setValue(), and UnderTolerance.
has2DReferences()
bool DrawViewDimension::has2DReferences (void) const virtual
Reimplemented in TechDraw::LandmarkDimension.
References App::PropertyLinkSubList::getSubValues(), App::PropertyLinkSubList::getValues(), and References2D.
Referenced by TechDrawGui::QGIViewDimension::draw(), execute(), and getDimValue().
has3DReferences()
bool DrawViewDimension::has3DReferences (void) const virtual
References App::PropertyLinkSubList::getSize(), and References3D.
Referenced by TechDrawGui::TaskLinkDim::dimReferencesSelection(), TechDrawGui::TaskLinkDim::loadAvailDims(), and onDocumentRestored().
hasOverUnderTolerance()
bool DrawViewDimension::hasOverUnderTolerance (void) const
References ArbitraryTolerances, TechDraw::DrawUtil::fpCompare(), App::PropertyBool::getValue(), App::PropertyQuantity::getValue(), OverTolerance, and UnderTolerance.
isMultiValueSchema()
bool DrawViewDimension::isMultiValueSchema (void) const
References Base::UnitsApi::getSchema(), Base::ImperialBuilding, Base::ImperialCivil, App::PropertyEnumeration::isValue(), and Type.
Referenced by formatValue().
leaderIntersectsArc()
bool DrawViewDimension::leaderIntersectsArc (Base::Vector3d s, Base::Vector3d pointOnCircle)
References TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::DrawUtil::getIndexFromName(), App::PropertyLinkSubList::getSubValues(), getViewPart(), TechDraw::AOC::intersectsArc(), TechDraw::BSpline::intersectsArc(), TechDraw::BSpline::isCircle(), and References2D.
mustExecute()
short DrawViewDimension::mustExecute () const override virtual
mustExecute We call this method to check if the object was modified to be invoked.
If the object label or an argument is modified. If we must recompute the object - to call the method execute(). 0: no recomputation is needed 1: recomputation needed
Remarks
If an object is marked as 'touched' then this does not necessarily mean that it will be recomputed. It only means that all objects that link it (i.e. its InList) will be recomputed.
Reimplemented from TechDraw::DrawView.
Reimplemented in TechDraw::LandmarkDimension, and TechDraw::DrawViewDimExtent.
References Arbitrary, ArbitraryTolerances, EqualTolerance, FormatSpec, FormatSpecOverTolerance, FormatSpecUnderTolerance, Inverted, App::DocumentObject::isRestoring(), App::Property::isTouched(), MeasureType, TechDraw::DrawView::mustExecute(), OverTolerance, References2D, TheoreticalExact, Type, and UnderTolerance.
Referenced by TechDraw::DrawViewDimExtent::mustExecute(), and TechDraw::LandmarkDimension::mustExecute().
onChanged()
void DrawViewDimension::onChanged (const App::Property * prop) override protected virtual
get called by the container when a property was changed
Reimplemented from TechDraw::DrawView.
Reimplemented in TechDraw::LandmarkDimension, and TechDraw::DrawViewDimExtent.
References Base::Unit::Angle, Arbitrary, ArbitraryTolerances, clear3DMeasurements(), Base::Console(), EqualTolerance, FormatSpec, FormatSpecOverTolerance, FormatSpecUnderTolerance, getDefaultFormatSpec(), App::DocumentObject::getNameInDocument(), App::PropertyQuantity::getUnit(), App::PropertyEnumeration::getValue(), App::PropertyString::getValue(), App::PropertyBool::getValue(), App::PropertyQuantity::getValue(), App::PropertyLinkSubList::getValues(), Measure::Measurement::has3DReferences(), Inverted, App::DocumentObject::isRestoring(), App::PropertyEnumeration::isValue(), Base::Unit::Length, measurement, MeasureType, TechDraw::DrawView::onChanged(), OverTolerance, References3D, TechDraw::DrawView::requestPaint(), setAll3DMeasurement(), App::PropertyQuantityConstraint::setConstraints(), App::Property::setReadOnly(), App::PropertyQuantity::setUnit(), App::PropertyBool::setValue(), App::PropertyString::setValue(), App::PropertyEnumeration::setValue(), App::PropertyQuantity::setValue(), TheoreticalExact, App::Property::touch(), Type, UnderTolerance, and Base::ConsoleSingleton::Warning().
Referenced by draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSite.Compass::buildCoordinates(), draftobjects.wire.Wire::execute(), ArchAxis.CommandArchGrid::IsActive(), TechDraw::DrawViewDimExtent::onChanged(), TechDraw::LandmarkDimension::onChanged(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchPanel.ViewProviderPanelSheet::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), and draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData().
onDocumentRestored()
void DrawViewDimension::onDocumentRestored () override protected virtual
get called after a document has been fully restored
Reimplemented from TechDraw::DrawView.
Reimplemented in TechDraw::LandmarkDimension.
References Base::Unit::Angle, App::PropertyEnumeration::getValue(), has3DReferences(), OverTolerance, setAll3DMeasurement(), App::PropertyQuantity::setUnit(), Type, and UnderTolerance.
Referenced by TechDraw::LandmarkDimension::onDocumentRestored().
Restore()
void DrawViewDimension::Restore (Base::XMLReader &) override protected virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from App::ExtensionContainer.
References EqualTolerance, App::ExtensionContainer::Restore(), and App::PropertyBool::setValue().
saveArrowPositions()
void DrawViewDimension::saveArrowPositions (const Base::Vector2d positions[])
References TechDraw::DrawView::getScale(), getViewPart(), m_arrowPositions, and draftfunctions.scale::scale().
setAll3DMeasurement()
void DrawViewDimension::setAll3DMeasurement ()
add Dimension 3D references to measurement
References Measure::Measurement::addReference3D(), Measure::Measurement::clear(), App::PropertyLinkSubList::getSubValues(), App::PropertyLinkSubList::getValues(), measurement, and References3D.
Referenced by onChanged(), and onDocumentRestored().
showUnits()
bool DrawViewDimension::showUnits () const
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by formatValue().
useDecimals()
bool DrawViewDimension::useDecimals () const
References TechDraw::Preferences::useGlobalDecimals().
Referenced by formatValue(), and getDefaultFormatSpec().
Member Data Documentation
Arbitrary
App::PropertyBool TechDraw::DrawViewDimension::Arbitrary
Referenced by DrawViewDimension(), getFormattedDimensionValue(), mustExecute(), onChanged(), and TechDrawGui::TaskDimension::TaskDimension().
ArbitraryTolerances
App::PropertyBool TechDraw::DrawViewDimension::ArbitraryTolerances
Referenced by DrawViewDimension(), getFormattedDimensionValue(), getFormattedToleranceValue(), getFormattedToleranceValues(), hasOverUnderTolerance(), mustExecute(), onChanged(), and TechDrawGui::TaskDimension::TaskDimension().
EqualTolerance
App::PropertyBool TechDraw::DrawViewDimension::EqualTolerance
Referenced by DrawViewDimension(), getFormattedDimensionValue(), mustExecute(), onChanged(), Restore(), and TechDrawGui::TaskDimension::TaskDimension().
FormatSpec
App::PropertyString TechDraw::DrawViewDimension::FormatSpec
Referenced by DrawViewDimension(), getFormattedDimensionValue(), getFormattedToleranceValue(), mustExecute(), onChanged(), and TechDrawGui::TaskDimension::TaskDimension().
FormatSpecOverTolerance
App::PropertyString TechDraw::DrawViewDimension::FormatSpecOverTolerance
Referenced by DrawViewDimension(), getFormattedToleranceValue(), getFormattedToleranceValues(), mustExecute(), onChanged(), and TechDrawGui::TaskDimension::TaskDimension().
FormatSpecUnderTolerance
App::PropertyString TechDraw::DrawViewDimension::FormatSpecUnderTolerance
Referenced by DrawViewDimension(), getFormattedToleranceValues(), mustExecute(), onChanged(), and TechDrawGui::TaskDimension::TaskDimension().
Inverted
App::PropertyBool TechDraw::DrawViewDimension::Inverted
Referenced by DrawViewDimension(), getDimValue(), mustExecute(), and onChanged().
m_arrowPositions
pointPair TechDraw::DrawViewDimension::m_arrowPositions protected
Referenced by getArrowPositions(), and saveArrowPositions().
m_linearPoints
pointPair TechDraw::DrawViewDimension::m_linearPoints protected
Referenced by DrawViewDimension(), execute(), TechDraw::LandmarkDimension::execute(), getDimValue(), and TechDraw::LandmarkDimension::onDocumentRestored().
measurement
Measure::Measurement* TechDraw::DrawViewDimension::measurement protected
Referenced by clear3DMeasurements(), DrawViewDimension(), getDimValue(), onChanged(), setAll3DMeasurement(), and ~DrawViewDimension().
MeasureType
App::PropertyEnumeration TechDraw::DrawViewDimension::MeasureType
Referenced by DrawViewDimension(), getDimValue(), mustExecute(), and onChanged().
OverTolerance
App::PropertyQuantityConstraint TechDraw::DrawViewDimension::OverTolerance
Referenced by DrawViewDimension(), getFormattedDimensionValue(), getFormattedToleranceValue(), getFormattedToleranceValues(), handleChangedPropertyType(), hasOverUnderTolerance(), mustExecute(), onChanged(), onDocumentRestored(), and TechDrawGui::TaskDimension::TaskDimension().
References2D
App::PropertyLinkSubList TechDraw::DrawViewDimension::References2D
Referenced by checkReferences2D(), DrawViewDimension(), execute(), TechDraw::LandmarkDimension::execute(), TechDrawGui::QGVPage::findParent(), getPointsEdgeVert(), getPointsOneEdge(), getPointsTwoEdges(), getPointsTwoVerts(), getRefType(), getViewPart(), TechDraw::LandmarkDimension::getViewPart(), has2DReferences(), TechDraw::LandmarkDimension::has2DReferences(), leaderIntersectsArc(), TechDraw::DrawDimHelper::makeDistDim(), TechDraw::DrawDimHelper::makeExtentDim(), and mustExecute().
References3D
App::PropertyLinkSubList TechDraw::DrawViewDimension::References3D
Referenced by TechDrawGui::TaskLinkDim::dimReferencesSelection(), DrawViewDimension(), TechDraw::LandmarkDimension::execute(), TechDraw::LandmarkDimension::get2DPoints(), has3DReferences(), onChanged(), TechDraw::LandmarkDimension::onChanged(), TechDraw::LandmarkDimension::onDocumentRestored(), setAll3DMeasurement(), and TechDrawGui::TaskLinkDim::updateDims().
TheoreticalExact
App::PropertyBool TechDraw::DrawViewDimension::TheoreticalExact
Referenced by DrawViewDimension(), getFormattedDimensionValue(), mustExecute(), onChanged(), and TechDrawGui::TaskDimension::TaskDimension().
Type
App::PropertyEnumeration TechDraw::DrawViewDimension::Type
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), TechDrawGui::QGIViewDimension::draw(), DrawViewDimension(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), execute(), formatValue(), getDimValue(), getFormattedDimensionValue(), getPrefix(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), isMultiValueSchema(), mustExecute(), onChanged(), onDocumentRestored(), draftobjects.layer.Layer::set_properties(), ArchReference.ArchReference::setProperties(), and TechDrawGui::TaskDimension::TaskDimension().
UnderTolerance
App::PropertyQuantityConstraint TechDraw::DrawViewDimension::UnderTolerance
Referenced by DrawViewDimension(), getFormattedToleranceValues(), handleChangedPropertyType(), hasOverUnderTolerance(), mustExecute(), onChanged(), onDocumentRestored(), and TechDrawGui::TaskDimension::TaskDimension().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/App/DrawViewDimension.h
Sources/FreeCAD/src/Mod/TechDraw/App/DrawViewDimension.cpp