FreeCAD: Gui::Dialog::DlgUnitsCalculator Class Reference
Gui::Dialog::DlgUnitsCalculator Class Reference
The DlgUnitsCalculator provides a unit conversion dialog.
#include <DlgUnitsCalculatorImp.h>
Public Member Functions
DlgUnitsCalculator (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
Constructs a DlgUnitsCalculator which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
~DlgUnitsCalculator ()
Destroys the object and frees any allocated resources.
Protected Slots
void copy (void)
void on_comboBoxScheme_activated (int)
void on_spinBoxDecimals_valueChanged (int)
void on_unitsBox_activated (int)
void parseError (const QString &errorText)
void returnPressed (void)
void textChanged (const QString)
void valueChanged (const Base::Quantity &)
Protected Member Functions
void accept ()
void reject ()
Detailed Description
The DlgUnitsCalculator provides a unit conversion dialog.
Author
Juergen Riegel
Constructor & Destructor Documentation
DlgUnitsCalculator()
DlgUnitsCalculator::DlgUnitsCalculator (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Constructs a DlgUnitsCalculator which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
References Base::Unit::Acceleration, accept(), Base::Unit::AmountOfSubstance, Base::Unit::Angle, Base::Unit::Area, draftgeoutils.intersections::connect(), copy(), Base::Unit::Density, Base::Unit::ElectricalCapacitance, Base::Unit::ElectricalConductance, Base::Unit::ElectricalConductivity, Base::Unit::ElectricalInductance, Base::Unit::ElectricalResistance, Base::Unit::ElectricCharge, Base::Unit::ElectricCurrent, Base::Unit::ElectricPotential, Base::Unit::Force, Base::Unit::Frequency, Base::UnitsApi::getDecimals(), Base::UnitsApi::getDescription(), Base::Unit::HeatFlux, Base::Unit::Length, Base::Unit::LuminousIntensity, Base::Unit::MagneticFieldStrength, Base::Unit::MagneticFlux, Base::Unit::MagneticFluxDensity, Base::Unit::Mass, Base::NumUnitSystemTypes, parseError(), Base::Unit::Power, Base::Unit::Pressure, returnPressed(), Base::Unit::SpecificHeat, Base::Unit::Stiffness, Base::Unit::Stress, Base::Unit::Temperature, textChanged(), Base::Unit::ThermalConductivity, Base::Unit::ThermalExpansionCoefficient, Base::Unit::ThermalTransferCoefficient, Base::Unit::TimeSpan, valueChanged(), Base::Unit::Velocity, Base::Unit::Volume, and Base::Unit::Work.
~DlgUnitsCalculator()
DlgUnitsCalculator::~DlgUnitsCalculator ()
Destroys the object and frees any allocated resources.
Member Function Documentation
accept()
void DlgUnitsCalculator::accept (void) protected
Referenced by femexamples.examplesgui.FemExamples::clicked(), DlgUnitsCalculator(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
copy
void DlgUnitsCalculator::copy (void) protected slot
Referenced by DlgUnitsCalculator().
on_comboBoxScheme_activated
void DlgUnitsCalculator::on_comboBoxScheme_activated (int index) protected slot
on_spinBoxDecimals_valueChanged
void DlgUnitsCalculator::on_spinBoxDecimals_valueChanged (int value) protected slot
on_unitsBox_activated
void DlgUnitsCalculator::on_unitsBox_activated (int index) protected slot
parseError
void DlgUnitsCalculator::parseError (const QString & errorText) protected slot
Referenced by DlgUnitsCalculator().
reject()
void DlgUnitsCalculator::reject (void) protected
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
returnPressed
void DlgUnitsCalculator::returnPressed (void) protected slot
Referenced by DlgUnitsCalculator().
textChanged
void DlgUnitsCalculator::textChanged (const QString) protected slot
References valueChanged().
Referenced by DlgUnitsCalculator().
valueChanged
void DlgUnitsCalculator::valueChanged (const Base::Quantity & quant) protected slot
References Base::UnitsApi::getDecimals(), Base::Unit::getTypeString(), Base::Quantity::getUnit(), Base::Quantity::getValue(), and Base::Quantity::parse().
Referenced by DlgUnitsCalculator(), and textChanged().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgUnitsCalculatorImp.h
FreeCAD/src/Gui/DlgUnitsCalculatorImp.cpp