FreeCAD: PathScripts.post.opensbp_pre Namespace Reference
PathScripts.post.opensbp_pre Namespace Reference
Functions
def insert (filename, docname)
def open (filename)
def parse (inputstring)
Variables
string AXIS = 'X', 'Y', 'Z', 'A', 'B'
pythonopen = open
string SPEEDS = 'XY', 'Z', 'A', 'B'
Function Documentation
insert()
def PathScripts.post.opensbp_pre.insert (filename, docname)
called when freecad imports a file
This insert expects parse to return a list of strings
each string will become a separate path
References PathScripts.post.opensbp_pre.parse(), and PathScripts.post.opensbp_pre.pythonopen.
Referenced by PathScripts.post.opensbp_pre.open().
open()
def PathScripts.post.opensbp_pre.open (filename)
References PathScripts.post.opensbp_pre.insert().
parse()
def PathScripts.post.opensbp_pre.parse (inputstring)
Referenced by PathScripts.post.opensbp_pre.insert().
Variable Documentation
AXIS
string PathScripts.post.opensbp_pre.AXIS = 'X', 'Y', 'Z', 'A', 'B'
pythonopen
PathScripts.post.opensbp_pre.pythonopen = open
Referenced by PathScripts.post.opensbp_pre.insert().
SPEEDS
string PathScripts.post.opensbp_pre.SPEEDS = 'XY', 'Z', 'A', 'B'