FreeCAD: TechDrawGui::TaskDimension Class Reference
TechDrawGui::TaskDimension Class Reference
#include <TaskDimension.h>
Public Member Functions
virtual bool accept ()
void recomputeFeature ()
virtual bool reject ()
TaskDimension (QGIViewDimension *parent, ViewProviderDimension *dimensionVP)
~TaskDimension ()
Constructor & Destructor Documentation
TaskDimension()
TaskDimension::TaskDimension (QGIViewDimension * parent, ViewProviderDimension * dimensionVP)
References Base::Unit::Angle, TechDraw::DrawViewDimension::Arbitrary, TechDraw::DrawViewDimension::ArbitraryTolerances, App::Color::asValue(), TechDrawGui::ViewProviderDimension::Color, draftgeoutils.intersections::connect(), TechDrawGui::QGIViewDimension::dvDimension, TechDraw::DrawViewDimension::EqualTolerance, TechDrawGui::ViewProviderDimension::FlipArrowheads, TechDrawGui::ViewProviderDimension::Fontsize, TechDraw::DrawViewDimension::FormatSpec, TechDraw::DrawViewDimension::FormatSpecOverTolerance, TechDraw::DrawViewDimension::FormatSpecUnderTolerance, App::PropertyEnumeration::getValue(), App::PropertyString::getValue(), App::PropertyBool::getValue(), App::PropertyColor::getValue(), App::PropertyQuantity::getValue(), App::PropertyEnumeration::isValue(), Base::Unit::Length, TechDraw::DrawViewDimension::OverTolerance, TechDrawGui::ViewProviderDimension::StandardAndStyle, TechDraw::DrawViewDimension::TheoreticalExact, TechDraw::DrawViewDimension::Type, and TechDraw::DrawViewDimension::UnderTolerance.
~TaskDimension()
TaskDimension::~TaskDimension ()
Member Function Documentation
accept()
bool TaskDimension::accept (void) virtual
References Gui::ViewProviderDocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), and App::DocumentObject::purgeTouched().
Referenced by TechDrawGui::TaskDlgDimension::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
recomputeFeature()
void TaskDimension::recomputeFeature ()
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), and App::Document::recomputeFeature().
Referenced by reject().
reject()
bool TaskDimension::reject (void) virtual
References Gui::ViewProviderDocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::DocumentObject::purgeTouched(), recomputeFeature(), and TechDrawGui::QGIViewDimension::updateView().
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), TechDrawGui::TaskDlgDimension::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/TaskDimension.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/TaskDimension.cpp