FreeCAD: RobotGui::TaskTrajectory Class Reference
RobotGui::TaskTrajectory Class Reference
#include <TaskTrajectory.h>
Signals
void axisChanged (float A1, float A2, float A3, float A4, float A5, float A6, const Base::Placement &Tcp)
Public Member Functions
void OnChange (Gui::SelectionSingleton::SubjectType &rCaller, Gui::SelectionSingleton::MessageType Reason)
Observer message from the Selection.
TaskTrajectory (Robot::RobotObject *pcRobotObject, Robot::TrajectoryObject *pcTrajectoryObject, QWidget *parent=nullptr)
~TaskTrajectory ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Protected Member Functions
void setTo (void)
void viewTool (const Base::Placement &pos)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Protected Attributes
bool block
float duration
Robot::RobotObject * pcRobot
bool Run
Robot::Simulation sim
float timePos
QTimer * timer
ViewProviderRobotObject * ViewProv
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskTrajectory()
TaskTrajectory::TaskTrajectory (Robot::RobotObject * pcRobotObject, Robot::TrajectoryObject * pcTrajectoryObject, QWidget * parent = nullptr)
References Robot::Waypoint::Acceleration, Gui::Application::activeDocument(), Gui::BitmapFactory(), RobotGui::Ui_TaskTrajectory::ButtonStepBack, RobotGui::Ui_TaskTrajectory::ButtonStepEnd, RobotGui::Ui_TaskTrajectory::ButtonStepForward, RobotGui::Ui_TaskTrajectory::ButtonStepRun, RobotGui::Ui_TaskTrajectory::ButtonStepStart, RobotGui::Ui_TaskTrajectory::ButtonStepStop, Robot::Waypoint::CIRC, draftgeoutils.intersections::connect(), Robot::Waypoint::Cont, duration, Robot::Trajectory::getDuration(), Robot::Trajectory::getSize(), App::PropertyPlacement::getValue(), Robot::PropertyTrajectory::getValue(), Gui::Document::getViewProvider(), Robot::Trajectory::getWaypoint(), QSint::ActionGroup::groupLayout(), Gui::Application::Instance, Robot::Waypoint::LINE, Robot::Waypoint::Name, Robot::Waypoint::PTP, setTo(), RobotGui::Ui_TaskTrajectory::setupUi(), sim, timer, RobotGui::Ui_TaskTrajectory::timeSlider, RobotGui::Ui_TaskTrajectory::timeSpinBox, Robot::RobotObject::Tool, Robot::Simulation::Tool, Robot::TrajectoryObject::Trajectory, RobotGui::Ui_TaskTrajectory::trajectoryTable, Robot::Waypoint::Type, Robot::Waypoint::UNDEF, Robot::Waypoint::Velocity, and ViewProv.
~TaskTrajectory()
TaskTrajectory::~TaskTrajectory ()
Member Function Documentation
axisChanged
void RobotGui::TaskTrajectory::axisChanged (float A1, float A2, float A3, float A4, float A5, float A6, const Base::Placement & Tcp) signal
Referenced by setTo().
OnChange()
void RobotGui::TaskTrajectory::OnChange (Gui::SelectionSingleton::SubjectType & rCaller, Gui::SelectionSingleton::MessageType Reason)
Observer message from the Selection.
setTo()
void TaskTrajectory::setTo (void) protected
References Robot::Simulation::Axis, axisChanged(), Robot::Robot6Axis::getTcp(), App::PropertyPlacement::getValue(), pcRobot, Robot::Simulation::reset(), Robot::Simulation::Rob, RobotGui::ViewProviderRobotObject::setAxisTo(), Robot::Simulation::setToTime(), sim, timePos, Robot::RobotObject::Tool, Robot::Simulation::Tool, ViewProv, and viewTool().
Referenced by TaskTrajectory().
viewTool()
void TaskTrajectory::viewTool (const Base::Placement & pos) protected
References RobotGui::Ui_TaskTrajectory::label_Pos.
Referenced by setTo().
Member Data Documentation
block
bool RobotGui::TaskTrajectory::block protected
Referenced by AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::attachmentOffsetChanged(), AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::checkBoxFlipClicked(), AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::fillAllRefLines(), AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::lineRefChanged(), AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::modeSelected(), AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::readParameters(), AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::refButtonClicked(), AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::updateListOfModes(), and AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::updateRefButtons().
duration
float RobotGui::TaskTrajectory::duration protected
Referenced by TaskTrajectory(), and automotive_design.time_interval_with_bounds::wr1().
pcRobot
Robot::RobotObject* RobotGui::TaskTrajectory::pcRobot protected
Referenced by setTo().
Run
bool RobotGui::TaskTrajectory::Run protected
sim
Robot::Simulation RobotGui::TaskTrajectory::sim protected
Referenced by setTo(), and TaskTrajectory().
timePos
float RobotGui::TaskTrajectory::timePos protected
Referenced by setTo().
timer
QTimer* RobotGui::TaskTrajectory::timer protected
Referenced by ArchReference.ViewProviderArchReference::checkChanges(), PathScripts.PathSimulatorGui.PathSimulation::EndSimulation(), ArchReference.ViewProviderArchReference::onDelete(), PathScripts.PathSimulatorGui.PathSimulation::onSpeedBarChange(), PathScripts.PathSimulatorGui.PathSimulation::SimFF(), PathScripts.PathSimulatorGui.PathSimulation::SimPause(), PathScripts.PathSimulatorGui.PathSimulation::SimPlay(), and TaskTrajectory().
ViewProv
ViewProviderRobotObject* RobotGui::TaskTrajectory::ViewProv protected
Referenced by setTo(), and TaskTrajectory().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Robot/Gui/TaskTrajectory.h
FreeCAD/src/Mod/Robot/Gui/TaskTrajectory.cpp