FreeCAD: MeshCore::MeshEvalOrientation Class Reference
MeshCore::MeshEvalOrientation Class Reference
The MeshEvalOrientation class checks the mesh kernel for consistent facet normals.
#include <Evaluation.h>
Public Member Functions
bool Evaluate ()
Evaluates the mesh kernel with respect to certain criteria.
std::vector< FacetIndex > GetIndices () const
MeshEvalOrientation (const MeshKernel &rclM)
~MeshEvalOrientation ()
Public Member Functions inherited from MeshCore::MeshEvaluation
virtual bool Evaluate ()=0
Evaluates the mesh kernel with respect to certain criteria.
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()
Detailed Description
The MeshEvalOrientation class checks the mesh kernel for consistent facet normals.
Author
Werner Mayer
Constructor & Destructor Documentation
MeshEvalOrientation()
MeshEvalOrientation::MeshEvalOrientation (const MeshKernel & rclM)
~MeshEvalOrientation()
MeshEvalOrientation::~MeshEvalOrientation ()
Member Function Documentation
Evaluate()
bool MeshEvalOrientation::Evaluate () virtual
Evaluates the mesh kernel with respect to certain criteria.
Must be reimplemented by every subclass. This pure virtual function returns false if the mesh kernel is invalid according to this criterion and true if the mesh kernel is correct.
Implements MeshCore::MeshEvaluation.
References MeshCore::FACET_INDEX_MAX.
Referenced by MeshCore::MeshFixOrientation::Fixup(), MeshGui::DlgEvaluateMeshImp::on_analyzeOrientationButton_clicked(), and MeshGui::DlgEvaluateMeshImp::on_repairAllTogether_clicked().
GetIndices()
std::vector< FacetIndex > MeshEvalOrientation::GetIndices () const
References MeshCore::FACET_INDEX_MAX, MeshCore::MeshAlgorithm::ResetFacetFlag(), MeshCore::MeshAlgorithm::ResetFacetsFlag(), MeshCore::MeshAlgorithm::SetFacetsFlag(), MeshCore::MeshFacet::TMP0, and MeshCore::MeshFacet::VISIT.
Referenced by Mesh::MeshObject::countNonUniformOrientedFacets(), MeshCore::MeshTopoAlgorithm::HarmonizeNormals(), and MeshGui::DlgEvaluateMeshImp::on_analyzeOrientationButton_clicked().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/Core/Evaluation.h
FreeCAD/src/Mod/Mesh/App/Core/Evaluation.cpp