FreeCAD: Gui::ToolBarAction Class Reference
Gui::ToolBarAction Class Reference
Special action to show all toolbars in an own popup menu.
#include <Action.h>
Public Member Functions
void addTo (QWidget *w)
Adds this action to widget w.
ToolBarAction (Command *pcCmd, QObject *parent=0)
virtual ~ToolBarAction ()
Public Member Functions inherited from Gui::Action
QAction * action () const
Action (Command *pcCmd, QAction *action, QObject *parent)
Action takes ownership of the 'action' object.
Action (Command *pcCmd, QObject *parent=0)
Constructs an action called name with parent parent.
QIcon icon () const
bool isChecked () const
void setCheckable (bool)
void setChecked (bool, bool no_signal=false)
virtual void setEnabled (bool)
Sets whether the action is enabled.
void setIcon (const QIcon &)
void setMenuRole (QAction::MenuRole menuRole)
void setShortcut (const QString &)
void setStatusTip (const QString &)
void setText (const QString &)
void setToolTip (const QString &)
virtual void setVisible (bool)
void setWhatsThis (const QString &)
QKeySequence shortcut () const
QString statusTip () const
QString text () const
QString toolTip () const
QString whatsThis () const
virtual ~Action ()
Additional Inherited Members
Public Slots inherited from Gui::Action
virtual void onActivated ()
Activates the command.
virtual void onToggled (bool)
Sets whether the command is toggled.
Detailed Description
Special action to show all toolbars in an own popup menu.
Author
Werner Mayer
Constructor & Destructor Documentation
ToolBarAction()
ToolBarAction::ToolBarAction (Command * pcCmd, QObject * parent = 0)
~ToolBarAction()
ToolBarAction::~ToolBarAction () virtual
Member Function Documentation
addTo()
void ToolBarAction::addTo (QWidget * w) virtual
Adds this action to widget w.
Reimplemented from Gui::Action.
References draftgeoutils.intersections::connect(), and Gui::getMainWindow().
Referenced by Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Action.h
Sources/FreeCAD/src/Gui/Action.cpp