FreeCAD: e57::CompressedVectorSectionHeader Struct Reference
e57::CompressedVectorSectionHeader Struct Reference
#include <SectionHeaders.h>
Public Member Functions
CompressedVectorSectionHeader ()
void verify (uint64_t filePhysicalSize=0)
Public Attributes
uint64_t dataPhysicalOffset = 0
uint64_t indexPhysicalOffset = 0
uint8_t reserved1 [7] = {}
const uint8_t sectionId = COMPRESSED_VECTOR_SECTION
uint64_t sectionLogicalLength = 0
Constructor & Destructor Documentation
CompressedVectorSectionHeader()
e57::CompressedVectorSectionHeader::CompressedVectorSectionHeader ()
Double check that header is correct length. Watch out for RTTI increasing the size.
References CompressedVectorSectionHeader().
Referenced by CompressedVectorSectionHeader().
Member Function Documentation
verify()
void e57::CompressedVectorSectionHeader::verify (uint64_t filePhysicalSize = 0)
Verify reserved fields are zero. ??? if fileversion==1.0 ???
Check section length is multiple of 4
Check sectionLogicalLength is in bounds
Check dataPhysicalOffset is in bounds
Check indexPhysicalOffset is in bounds
References dataPhysicalOffset, e57::E57_ERROR_BAD_CV_HEADER, indexPhysicalOffset, reserved1, sectionLogicalLength, and e57::toString().
Referenced by e57::CompressedVectorWriterImpl::close(), and e57::CompressedVectorReaderImpl::CompressedVectorReaderImpl().
Member Data Documentation
dataPhysicalOffset
uint64_t e57::CompressedVectorSectionHeader::dataPhysicalOffset = 0
Referenced by e57::CompressedVectorWriterImpl::close(), e57::CompressedVectorReaderImpl::CompressedVectorReaderImpl(), and verify().
indexPhysicalOffset
uint64_t e57::CompressedVectorSectionHeader::indexPhysicalOffset = 0
Referenced by e57::CompressedVectorWriterImpl::close(), and verify().
reserved1
uint8_t e57::CompressedVectorSectionHeader::reserved1[7] = {}
Referenced by verify().
sectionId
const uint8_t e57::CompressedVectorSectionHeader::sectionId = COMPRESSED_VECTOR_SECTION
sectionLogicalLength
uint64_t e57::CompressedVectorSectionHeader::sectionLogicalLength = 0
Referenced by e57::CompressedVectorWriterImpl::close(), e57::CompressedVectorReaderImpl::CompressedVectorReaderImpl(), and verify().
The documentation for this struct was generated from the following files:
FreeCAD/src/3rdParty/libE57Format/src/SectionHeaders.h
FreeCAD/src/3rdParty/libE57Format/src/SectionHeaders.cpp