FreeCAD: Gui::Inventor::SoDrawingGrid Class Reference
Gui::Inventor::SoDrawingGrid Class Reference
#include <SoDrawingGrid.h>
Public Member Functions
virtual void computeBBox (SoAction *action, SbBox3f &box, SbVec3f &center)
virtual void generatePrimitives (SoAction *action)
virtual void GLRender (SoGLRenderAction *action)
virtual void GLRenderBelowPath (SoGLRenderAction *action)
virtual void GLRenderInPath (SoGLRenderAction *action)
virtual void GLRenderOffPath (SoGLRenderAction *action)
SoDrawingGrid ()
Static Public Member Functions
static void initClass ()
Constructor & Destructor Documentation
SoDrawingGrid()
SoDrawingGrid::SoDrawingGrid ()
Member Function Documentation
computeBBox()
void SoDrawingGrid::computeBBox (SoAction * action, SbBox3f & box, SbVec3f & center) virtual
generatePrimitives()
void SoDrawingGrid::generatePrimitives (SoAction * action) virtual
GLRender()
void SoDrawingGrid::GLRender (SoGLRenderAction * action) virtual
References GLRenderBelowPath(), and GLRenderInPath().
GLRenderBelowPath()
void SoDrawingGrid::GLRenderBelowPath (SoGLRenderAction * action) virtual
Referenced by GLRender().
GLRenderInPath()
void SoDrawingGrid::GLRenderInPath (SoGLRenderAction * action) virtual
Referenced by GLRender().
GLRenderOffPath()
void SoDrawingGrid::GLRenderOffPath (SoGLRenderAction * action) virtual
initClass()
void SoDrawingGrid::initClass (void) static
Referenced by Gui::SoFCDB::init().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Inventor/SoDrawingGrid.h
Sources/FreeCAD/src/Gui/Inventor/SoDrawingGrid.cpp