FreeCAD: TechDrawGui::TaskRichAnno Class Reference
TechDrawGui::TaskRichAnno Class Reference
#include <TaskRichAnno.h>
Public Slots
void onEditorClicked (bool b)
Public Member Functions
virtual bool accept ()
void enableTaskButtons (bool b)
virtual bool getCreateMode (void)
virtual bool reject ()
void saveButtons (QPushButton *btnOK, QPushButton *btnCancel)
virtual void setCreateMode (bool b)
TaskRichAnno (TechDraw::DrawView *baseFeat, TechDraw::DrawPage *page)
TaskRichAnno (TechDrawGui::ViewProviderRichAnno *leadVP)
void updateTask ()
~TaskRichAnno ()
Protected Slots
void onEditorExit (void)
void onSaveAndExit (QString)
Protected Member Functions
void blockButtons (bool b)
QPointF calcTextStartPos (double scale)
void changeEvent (QEvent *e)
void commonFeatureUpdate (void)
void createAnnoFeature (void)
void enableTextUi (bool b)
void enableVPUi (bool b)
App::Color prefLineColor (void)
double prefWeight () const
void removeFeature (void)
void setUiEdit (void)
void setUiPrimary (void)
void updateAnnoFeature (void)
Constructor & Destructor Documentation
TaskRichAnno() [1/2]
TaskRichAnno::TaskRichAnno (TechDraw::DrawView * baseFeat, TechDraw::DrawPage * page)
References draftgeoutils.intersections::connect(), TechDrawGui::QGSPage::findQViewForDocObj(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), TechDrawGui::ViewProviderPage::getMDIViewPage(), TechDrawGui::MDIViewPage::getQGSPage(), Gui::Document::getViewProvider(), Gui::Application::Instance, onEditorClicked(), and setUiPrimary().
TaskRichAnno() [2/2]
TaskRichAnno::TaskRichAnno (TechDrawGui::ViewProviderRichAnno * leadVP)
References TechDraw::DrawRichAnno::AnnoParent, draftgeoutils.intersections::connect(), Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::DrawView::findParentPage(), TechDrawGui::QGSPage::findQViewForDocObj(), Base::Persistence::getClassTypeId(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), TechDrawGui::ViewProviderRichAnno::getFeature(), TechDrawGui::ViewProviderPage::getMDIViewPage(), TechDrawGui::MDIViewPage::getQGSPage(), App::PropertyLink::getValue(), App::PropertyQuantity::getValue(), Gui::Document::getViewProvider(), TechDrawGui::Rez::guiX(), Gui::Application::Instance, onEditorClicked(), setUiEdit(), TechDraw::DrawView::X, and TechDraw::DrawView::Y.
~TaskRichAnno()
TaskRichAnno::~TaskRichAnno ()
Member Function Documentation
accept()
bool TaskRichAnno::accept (void) virtual
References createAnnoFeature(), getCreateMode(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::Command::Gui, Gui::Application::Instance, and updateAnnoFeature().
Referenced by TechDrawGui::TaskDlgRichAnno::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
blockButtons()
void TechDrawGui::TaskRichAnno::blockButtons (bool b) protected
calcTextStartPos()
QPointF TaskRichAnno::calcTextStartPos (double scale) protected
References Base::Console(), Base::Persistence::getClassTypeId(), TechDraw::DrawPage::getPageHeight(), TechDraw::DrawPage::getPageWidth(), App::PropertyFloat::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), TechDrawGui::Rez::guiX(), Base::BaseClass::isDerivedFrom(), TechDraw::DrawRichAnno::MaxWidth, Base::ConsoleSingleton::Message(), draftfunctions.scale::scale(), and TechDraw::DrawLeaderLine::WayPoints.
Referenced by createAnnoFeature().
changeEvent()
void TaskRichAnno::changeEvent (QEvent * e) protected
commonFeatureUpdate()
void TaskRichAnno::commonFeatureUpdate (void) protected
References TechDraw::DrawRichAnno::AnnoText, TechDrawGui::Rez::appX(), TechDraw::DrawRichAnno::MaxWidth, TechDraw::DrawView::setPosition(), App::PropertyBool::setValue(), App::PropertyString::setValue(), App::PropertyFloat::setValue(), TechDraw::DrawRichAnno::ShowFrame, Base::Vector3< _Precision >::x, and Base::Vector3< _Precision >::y.
Referenced by createAnnoFeature(), and updateAnnoFeature().
createAnnoFeature()
void TaskRichAnno::createAnnoFeature (void) protected
References TechDrawGui::Rez::appX(), calcTextStartPos(), Gui::Command::commitCommand(), commonFeatureUpdate(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), TechDraw::DrawPage::getPageHeight(), TechDraw::DrawPage::getPageWidth(), TechDraw::DrawView::getScale(), App::Document::getUniqueObjectName(), TechDrawGui::QGIView::getViewProvider(), Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, TechDraw::DrawView::requestPaint(), App::Color::setValue(), App::PropertyQuantity::setValue(), App::DocumentObject::touch(), Gui::Command::updateActive(), Base::Vector3< _Precision >::x, TechDraw::DrawView::X, Base::Vector3< _Precision >::y, and TechDraw::DrawView::Y.
Referenced by accept().
enableTaskButtons()
void TaskRichAnno::enableTaskButtons (bool b)
enableTextUi()
void TaskRichAnno::enableTextUi (bool b) protected
Referenced by setUiEdit().
enableVPUi()
void TaskRichAnno::enableVPUi (bool b) protected
Referenced by setUiEdit(), and setUiPrimary().
getCreateMode()
virtual bool TechDrawGui::TaskRichAnno::getCreateMode (void) virtual
Referenced by accept(), and reject().
onEditorClicked
void TaskRichAnno::onEditorClicked (bool b) slot
References draftgeoutils.intersections::connect(), onEditorExit(), and onSaveAndExit().
Referenced by TaskRichAnno().
onEditorExit
void TaskRichAnno::onEditorExit (void) protected slot
Referenced by onEditorClicked().
onSaveAndExit
void TaskRichAnno::onSaveAndExit (QString qs) protected slot
Referenced by onEditorClicked().
prefLineColor()
App::Color TaskRichAnno::prefLineColor (void) protected
References TechDrawGui::PreferencesGui::leaderColor().
Referenced by setUiPrimary().
prefWeight()
double TaskRichAnno::prefWeight () const protected
References TechDraw::LineGroup::lineGroupFactory().
Referenced by setUiPrimary().
reject()
bool TaskRichAnno::reject (void) virtual
References getCreateMode(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::Command::Gui, Gui::Application::Instance, and removeFeature().
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), TechDrawGui::TaskDlgRichAnno::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
removeFeature()
void TaskRichAnno::removeFeature (void) protected
References Gui::Application::activeDocument(), Base::Console(), App::DocumentObject::getNameInDocument(), Gui::Document::getUndoVector(), Gui::Command::Gui, Gui::Command::hasPendingCommand(), Gui::Application::Instance, Base::ConsoleSingleton::Log(), Gui::Document::undo(), and Base::ConsoleSingleton::Warning().
Referenced by reject().
saveButtons()
void TaskRichAnno::saveButtons (QPushButton * btnOK, QPushButton * btnCancel)
Referenced by TechDrawGui::TaskDlgRichAnno::modifyStandardButtons().
setCreateMode()
virtual void TechDrawGui::TaskRichAnno::setCreateMode (bool b) virtual
setUiEdit()
void TaskRichAnno::setUiEdit (void) protected
References TechDraw::DrawRichAnno::AnnoParent, TechDraw::DrawRichAnno::AnnoText, App::Color::asValue(), enableTextUi(), enableVPUi(), Base::Tools::fromStdString(), App::DocumentObject::getNameInDocument(), App::PropertyLink::getValue(), App::PropertyEnumeration::getValue(), App::PropertyFloat::getValue(), App::PropertyString::getValue(), App::PropertyBool::getValue(), App::PropertyColor::getValue(), App::PropertyQuantity::getValue(), TechDrawGui::ViewProviderRichAnno::LineColor, TechDrawGui::ViewProviderRichAnno::LineStyle, TechDrawGui::ViewProviderRichAnno::LineWidth, TechDraw::DrawRichAnno::MaxWidth, and TechDraw::DrawRichAnno::ShowFrame.
Referenced by TaskRichAnno().
setUiPrimary()
void TaskRichAnno::setUiPrimary (void) protected
References enableVPUi(), Base::Tools::fromStdString(), MRichTextEdit::getDefFontSizeNum(), App::DocumentObject::getNameInDocument(), Base::Unit::Length, prefLineColor(), and prefWeight().
Referenced by TaskRichAnno().
updateAnnoFeature()
void TaskRichAnno::updateAnnoFeature (void) protected
References Gui::Command::commitCommand(), commonFeatureUpdate(), TechDrawGui::ViewProviderRichAnno::LineColor, TechDrawGui::ViewProviderRichAnno::LineStyle, TechDrawGui::ViewProviderRichAnno::LineWidth, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, TechDraw::DrawView::requestPaint(), App::PropertyEnumeration::setValue(), App::PropertyColor::setValue(), App::Color::setValue(), and App::PropertyQuantity::setValue().
Referenced by accept().
updateTask()
void TaskRichAnno::updateTask ()
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/TaskRichAnno.h
FreeCAD/src/Mod/TechDraw/Gui/TaskRichAnno.cpp