FreeCAD: DriverGMF_Read Class Reference
DriverGMF_Read Class Reference
Driver reading a mesh from the GMF file. The mesh to read is selected by an index (counted form 0) set via SetMeshId()
#include <DriverGMF_Read.hxx>
Public Member Functions
DriverGMF_Read ()
virtual Status Perform ()
Read a GMF file.
void SetMakeRequiredGroups (bool theMakeRequiredGroups)
~DriverGMF_Read ()
Public Member Functions inherited from Driver_SMESHDS_Mesh
Driver_SMESHDS_Mesh ()
void SetMesh (SMESHDS_Mesh *theMesh)
Public Member Functions inherited from Driver_Mesh
Driver_Mesh ()
virtual SMESH_ComputeErrorPtr GetError ()
Return a structure containing description of errors.
virtual std::string GetMeshName () const
virtual void SetFile (const std::string &theFileName)
void SetMeshId (int theMeshId)
virtual void SetMeshName (const std::string &theMeshName)
virtual void SetOption (const std::string &optionName, const std::string &optionValue)
virtual ~Driver_Mesh ()
Additional Inherited Members
Public Types inherited from Driver_Mesh
enum Status {
DRS_OK, DRS_EMPTY, DRS_WARN_RENUMBER, DRS_WARN_SKIP_ELEM,
DRS_WARN_DESCENDING, DRS_FAIL
}
Protected Member Functions inherited from Driver_Mesh
Status addMessage (const std::string &msg, const bool isFatal=false)
Stores an error message.
Protected Attributes inherited from Driver_SMESHDS_Mesh
SMESHDS_Mesh * myMesh
Protected Attributes inherited from Driver_Mesh
std::vector< std::string > myErrorMessages
std::string myFile
int myMeshId
std::string myMeshName
Status myStatus
Detailed Description
Driver reading a mesh from the GMF file. The mesh to read is selected by an index (counted form 0) set via SetMeshId()
Constructor & Destructor Documentation
DriverGMF_Read()
DriverGMF_Read::DriverGMF_Read ()
~DriverGMF_Read()
DriverGMF_Read::~DriverGMF_Read ()
Member Function Documentation
Perform()
Driver_Mesh::Status DriverGMF_Read::Perform () virtual
Read a GMF file.
Implements Driver_Mesh.
References SMESHDS_Mesh::AddEdgeWithID(), SMESHDS_Mesh::AddFaceWithID(), SMESHDS_Mesh::AddGroup(), Driver_Mesh::addMessage(), SMESHDS_Mesh::AddNodeWithID(), SMESHDS_Mesh::AddVolumeWithID(), Driver_Mesh::DRS_OK, SMESHUtils::FreeVector(), SMESHDS_Mesh::GetGroups(), SMDS_Mesh::GetMeshInfo(), DriverGMF::isExtensionCorrect(), Driver_Mesh::myFile, Driver_SMESHDS_Mesh::myMesh, SMDS_MeshInfo::NbElements(), and SMDS_MeshInfo::NbNodes().
Referenced by SMESH_Mesh::GMFToMesh().
SetMakeRequiredGroups()
void DriverGMF_Read::SetMakeRequiredGroups (bool theMakeRequiredGroups)
Referenced by SMESH_Mesh::GMFToMesh().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/DriverGMF_Read.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/DriverGMF_Read.cpp