FreeCAD: MeshCore::FacetCurvature Class Reference
MeshCore::FacetCurvature Class Reference
#include <Curvature.h>
Public Member Functions
CurvatureInfo Compute (unsigned long index) const
FacetCurvature (const MeshKernel &kernel, const MeshRefPointToFacets &search, float, unsigned long)
Constructor & Destructor Documentation
FacetCurvature()
FacetCurvature::FacetCurvature (const MeshKernel & kernel, const MeshRefPointToFacets & search, float r, unsigned long pt)
Member Function Documentation
Compute()
CurvatureInfo FacetCurvature::Compute (unsigned long index) const
References MeshCore::Approximation::AddPoints(), MeshCore::SurfaceFit::Fit(), MeshCore::SurfaceFit::GetCurvatureInfo(), MeshCore::MeshKernel::GetFacet(), MeshCore::PlaneFit::GetNormal(), MeshCore::MeshKernel::GetPoints(), and MeshCore::MeshRefPointToFacets::Neighbours().
Referenced by MeshCore::MeshCurvature::ComputePerFace().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Curvature.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Curvature.cpp