FreeCAD: Gui::Dialog::Ui_DocumentRecovery Class Reference
Gui::Dialog::Ui_DocumentRecovery Class Reference
#include <ui_DocumentRecovery.h>
Public Member Functions
void retranslateUi (QDialog *Gui__Dialog__DocumentRecovery)
void setupUi (QDialog *Gui__Dialog__DocumentRecovery)
Public Attributes
QDialogButtonBox * buttonBox
QPushButton * buttonCleanup
QGridLayout * gridLayout
QLabel * label
QLabel * label_2
QTreeWidget * treeWidget
QSpacerItem * verticalSpacer
QSpacerItem * verticalSpacer_2
Member Function Documentation
retranslateUi()
void Gui::Dialog::Ui_DocumentRecovery::retranslateUi (QDialog * Gui__Dialog__DocumentRecovery)
References buttonCleanup, label_2, draftguitools.gui_setstyle::translate, and treeWidget.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::Dialog::Ui_DocumentRecovery::setupUi (QDialog * Gui__Dialog__DocumentRecovery)
References buttonBox, buttonCleanup, draftgeoutils.intersections::connect(), gridLayout, label_2, retranslateUi(), treeWidget, verticalSpacer, and verticalSpacer_2.
Member Data Documentation
buttonBox
QDialogButtonBox* Gui::Dialog::Ui_DocumentRecovery::buttonBox
Referenced by PathScripts.PathGetPoint.TaskPanel::getPoint(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::modifyStandardButtons(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::pageDirtyChanged(), PathScripts.PathGetPoint.TaskPanel::pointFinish(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setClean(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setDirty(), and setupUi().
buttonCleanup
QPushButton* Gui::Dialog::Ui_DocumentRecovery::buttonCleanup
Referenced by retranslateUi(), and setupUi().
gridLayout
QGridLayout* Gui::Dialog::Ui_DocumentRecovery::gridLayout
Referenced by setupUi().
label
QLabel* Gui::Dialog::Ui_DocumentRecovery::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
label_2
QLabel* Gui::Dialog::Ui_DocumentRecovery::label_2
Referenced by retranslateUi(), and setupUi().
treeWidget
QTreeWidget* Gui::Dialog::Ui_DocumentRecovery::treeWidget
Referenced by retranslateUi(), and setupUi().
verticalSpacer
QSpacerItem* Gui::Dialog::Ui_DocumentRecovery::verticalSpacer
Referenced by setupUi().
verticalSpacer_2
QSpacerItem* Gui::Dialog::Ui_DocumentRecovery::verticalSpacer_2
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_DocumentRecovery.h