FreeCAD: DriverGMF_Write Class Reference
DriverGMF_Write Class Reference
Driver Writing a mesh into a GMF file.
#include <DriverGMF_Write.hxx>
Public Member Functions
DriverGMF_Write ()
std::vector< std::string > GetSizeMapFiles ()
virtual Status Perform ()
Reads a GMF file.
Status PerformSizeMap (const std::vector< Control_Pnt > &points)
void SetExportRequiredGroups (bool toExport)
void SetSizeMapPrefix (std::string prefix)
~DriverGMF_Write ()
Public Member Functions inherited from Driver_SMESHDS_Mesh
Driver_SMESHDS_Mesh ()
void SetMesh (SMESHDS_Mesh *theMesh)
Public Member Functions inherited from Driver_Mesh
Driver_Mesh ()
virtual SMESH_ComputeErrorPtr GetError ()
Return a structure containing description of errors.
virtual std::string GetMeshName () const
virtual void SetFile (const std::string &theFileName)
void SetMeshId (int theMeshId)
virtual void SetMeshName (const std::string &theMeshName)
virtual void SetOption (const std::string &optionName, const std::string &optionValue)
virtual ~Driver_Mesh ()
Additional Inherited Members
Public Types inherited from Driver_Mesh
enum Status {
DRS_OK, DRS_EMPTY, DRS_WARN_RENUMBER, DRS_WARN_SKIP_ELEM,
DRS_WARN_DESCENDING, DRS_FAIL
}
Protected Member Functions inherited from Driver_Mesh
Status addMessage (const std::string &msg, const bool isFatal=false)
Stores an error message.
Protected Attributes inherited from Driver_SMESHDS_Mesh
SMESHDS_Mesh * myMesh
Protected Attributes inherited from Driver_Mesh
std::vector< std::string > myErrorMessages
std::string myFile
int myMeshId
std::string myMeshName
Status myStatus
Detailed Description
Driver Writing a mesh into a GMF file.
Constructor & Destructor Documentation
DriverGMF_Write()
DriverGMF_Write::DriverGMF_Write ()
~DriverGMF_Write()
DriverGMF_Write::~DriverGMF_Write ()
Member Function Documentation
GetSizeMapFiles()
std::vector< std::string > DriverGMF_Write::GetSizeMapFiles ()
Perform()
Driver_Mesh::Status DriverGMF_Write::Perform () virtual
Reads a GMF file.
Implements Driver_Mesh.
References Driver_Mesh::addMessage(), Driver_Mesh::DRS_OK, SMDS_MeshElement::GetEntityType(), SMESHDS_Mesh::GetGroups(), SMDS_MeshNode::GetXYZ(), DriverGMF::isExtensionCorrect(), Driver_Mesh::myFile, Driver_SMESHDS_Mesh::myMesh, SMDS_Mesh::NbEdges(), SMDS_Mesh::NbFaces(), SMDS_Mesh::NbNodes(), and SMDS_Mesh::nodesIterator().
Referenced by SMESH_Mesh::ExportGMF().
PerformSizeMap()
Driver_Mesh::Status DriverGMF_Write::PerformSizeMap (const std::vector< Control_Pnt > & points)
References Driver_Mesh::DRS_OK.
SetExportRequiredGroups()
void DriverGMF_Write::SetExportRequiredGroups (bool toExport)
Referenced by SMESH_Mesh::ExportGMF().
SetSizeMapPrefix()
void DriverGMF_Write::SetSizeMapPrefix (std::string prefix)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/DriverGMF_Write.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/DriverGMF_Write.cpp