FreeCAD: Gui::SplashObserver Class Reference
Gui::SplashObserver Class Reference
Displays all messages at startup inside the splash screen.
Public Member Functions
void Log (const char *s)
const char * Name () override
void SendLog (const std::string &msg, Base::LogStyle level) override
Used to send a Log message at the given level.
SplashObserver (QSplashScreen *splasher=nullptr)
virtual ~SplashObserver ()
Public Member Functions inherited from Base::ILogger
ILogger ()
virtual const char * Name ()
virtual void SendLog (const std::string &msg, LogStyle level)=0
Used to send a Log message at the given level.
virtual ~ILogger ()=0
Additional Inherited Members
Public Attributes inherited from Base::ILogger
bool bErr
bool bLog
bool bMsg
bool bWrn
Detailed Description
Displays all messages at startup inside the splash screen.
Author
Werner Mayer
Constructor & Destructor Documentation
SplashObserver()
Gui::SplashObserver::SplashObserver (QSplashScreen * splasher = nullptr)
References Base::ConsoleSingleton::AttachObserver(), App::Application::Config(), Base::Console(), and App::GetApplication().
~SplashObserver()
virtual Gui::SplashObserver::~SplashObserver () virtual
References Base::Console(), and Base::ConsoleSingleton::DetachObserver().
Member Function Documentation
Log()
void Gui::SplashObserver::Log (const char * s)
Referenced by SendLog().
Name()
const char * Gui::SplashObserver::Name (void) override virtual
Reimplemented from Base::ILogger.
SendLog()
void Gui::SplashObserver::SendLog (const std::string & msg, Base::LogStyle level) override virtual
Used to send a Log message at the given level.
Implements Base::ILogger.
References Base::Log, and Log().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/Splashscreen.cpp