FreeCAD: Part::GeomCurve Class Reference
Part::GeomCurve Class Reference
#include <Geometry.h>
Public Member Functions
bool closestParameter (const Base::Vector3d &point, double &u) const
bool closestParameterToBasisCurve (const Base::Vector3d &point, double &u) const
double curvatureAt (double u) const
Base::Vector3d firstDerivativeAtParameter (double u) const
GeomCurve ()
double getFirstParameter () const
double getLastParameter () const
bool intersect (const GeomCurve *c, std::vector< std::pair< Base::Vector3d, Base::Vector3d > > &points, double tol=Precision::Confusion()) const
double length (double u, double v) const
bool normalAt (const Base::Vector3d &curvepoint, Base::Vector3d &dir) const
bool normalAt (double u, Base::Vector3d &dir) const
Base::Vector3d pointAtParameter (double u) const
void reverse (void)
Base::Vector3d secondDerivativeAtParameter (double u) const
bool tangent (double u, Base::Vector3d &dir) const
bool tangent (double u, gp_Dir &) const
GeomBSplineCurve * toBSpline (double first, double last) const
toBSpline Converts the curve to a B-spline
virtual GeomBSplineCurve * toNurbs (double first, double last) const
TopoDS_Shape toShape () const
Base::Vector3d value (double u) const
virtual ~GeomCurve ()
Public Member Functions inherited from Part::Geometry
Geometry * clone (void) const
returns a cloned object.
virtual Geometry * copy (void) const =0
returns a copy of this object having a new randomly generated tag.
void deleteExtension (Base::Type type)
void deleteExtension (const std::string &name)
std::weak_ptr< GeometryExtension > getExtension (Base::Type type)
std::weak_ptr< const GeometryExtension > getExtension (Base::Type type) const
std::weak_ptr< GeometryExtension > getExtension (const std::string &name)
std::weak_ptr< const GeometryExtension > getExtension (const std::string &name) const
std::vector< std::weak_ptr< const GeometryExtension > > getExtensions () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
boost::uuids::uuid getTag () const
returns the tag of the geometry object
virtual const Handle (Geom_Geometry) &handle() const =0
bool hasExtension (Base::Type type) const
bool hasExtension (const std::string &name) const
void mirror (const Base::Vector3d &point)
void mirror (const Base::Vector3d &point, const Base::Vector3d &dir)
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
void rotate (const Base::Placement &plm)
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
void scale (const Base::Vector3d &vec, double scale)
void setExtension (std::unique_ptr< GeometryExtension > &&geo)
virtual TopoDS_Shape toShape () const =0
void transform (const Base::Matrix4D &mat)
void translate (const Base::Vector3d &vec)
virtual ~Geometry ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Static Protected Member Functions
static bool intersect (const Handle(Geom_Curve) c, const Handle(Geom_Curve) c2, std::vector< std::pair< Base::Vector3d, Base::Vector3d > > &points, double tol=Precision::Confusion())
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Protected Member Functions inherited from Part::Geometry
void assignTag (const Part::Geometry *)
copies the tag from the geometry passed as a parameter to this object
void copyNonTag (const Part::Geometry *)
void createNewTag ()
create a new tag for the geometry object
Geometry ()
Protected Attributes inherited from Part::Geometry
std::vector< std::shared_ptr< GeometryExtension > > extensions
boost::uuids::uuid tag
Constructor & Destructor Documentation
GeomCurve()
GeomCurve::GeomCurve ()
~GeomCurve()
GeomCurve::~GeomCurve () virtual
Member Function Documentation
closestParameter()
bool GeomCurve::closestParameter (const Base::Vector3d & point, double & u) const
References Part::Geometry::Handle(), and pointAtParameter().
Referenced by Sketcher::SketchAnalysis::analyseMissingPointOnPointCoincident(), closestParameterToBasisCurve(), Sketcher::SketchObject::fillet(), Sketcher::Sketch::initBSplinePieceMove(), normalAt(), and Sketcher::SketchObject::trim().
closestParameterToBasisCurve()
bool GeomCurve::closestParameterToBasisCurve (const Base::Vector3d & point, double & u) const
References closestParameter(), and Part::Geometry::Handle().
curvatureAt()
double GeomCurve::curvatureAt (double u) const
References Part::Geometry::Handle().
firstDerivativeAtParameter()
Base::Vector3d GeomCurve::firstDerivativeAtParameter (double u) const
References Part::Geometry::Handle(), and draftgeoutils.general::vec().
Referenced by Sketcher::SketchAnalysis::analyseMissingPointOnPointCoincident(), and Sketcher::SketchObject::fillet().
getFirstParameter()
double GeomCurve::getFirstParameter () const
References Part::Geometry::Handle().
Referenced by Sketcher::SketchObject::convertToNURBS(), Sketcher::SketchAnalysis::detectDegeneratedGeometries(), Sketcher::SketchObject::fillet(), Sketcher::SketchObject::insertBSplineKnot(), Sketcher::SketchAnalysis::removeDegeneratedGeometries(), and Sketcher::SketchObject::trim().
getLastParameter()
double GeomCurve::getLastParameter () const
References Part::Geometry::Handle().
Referenced by Sketcher::SketchObject::convertToNURBS(), Sketcher::SketchAnalysis::detectDegeneratedGeometries(), Sketcher::SketchObject::insertBSplineKnot(), and Sketcher::SketchAnalysis::removeDegeneratedGeometries().
intersect() [1/2]
bool GeomCurve::intersect (const GeomCurve * c, std::vector< std::pair< Base::Vector3d, Base::Vector3d > > & points, double tol = Precision::Confusion()) const
References Part::Geometry::Handle(), and intersect().
Referenced by Sketcher::SketchObject::fillet(), intersect(), and Part::GeomTrimmedCurve::intersectBasisCurves().
intersect() [2/2]
bool GeomCurve::intersect (const Handle(Geom_Curve) c, const Handle(Geom_Curve) c2, std::vector< std::pair< Base::Vector3d, Base::Vector3d > > & points, double tol = Precision::Confusion()) static protected
References Part::Geometry::Handle().
length()
double GeomCurve::length (double u, double v) const
References Part::Geometry::Handle().
Referenced by Sketcher::SketchAnalysis::detectDegeneratedGeometries(), PathScripts.PathStock.StockFromBase::execute(), PathScripts.PathDressupDogbone.ObjectDressup::execute(), PathScripts.PathFeatureExtensions.Extension::getSubLink(), PathScripts.PathFeatureExtensions.Extension::getWire(), Mod.PartDesign.Scripts.FilletArc.Vector::norm(), and Sketcher::SketchAnalysis::removeDegeneratedGeometries().
normalAt() [1/2]
bool GeomCurve::normalAt (const Base::Vector3d & curvepoint, Base::Vector3d & dir) const
References closestParameter(), and normalAt().
normalAt() [2/2]
bool GeomCurve::normalAt (double u, Base::Vector3d & dir) const
References Part::Geometry::Handle(), and Base::Vector3< _Precision >::Set().
Referenced by normalAt().
pointAtParameter()
Base::Vector3d GeomCurve::pointAtParameter (double u) const
References Part::Geometry::Handle().
Referenced by closestParameter(), Sketcher::SketchObject::exposeInternalGeometry(), and Sketcher::SketchObject::fillet().
reverse()
void GeomCurve::reverse (void)
References Part::Geometry::Handle().
secondDerivativeAtParameter()
Base::Vector3d GeomCurve::secondDerivativeAtParameter (double u) const
References Part::Geometry::Handle(), and draftgeoutils.general::vec().
tangent() [1/2]
bool GeomCurve::tangent (double u, Base::Vector3d & dir) const
References tangent().
tangent() [2/2]
bool GeomCurve::tangent (double u, gp_Dir & dir) const
References Part::Geometry::Handle().
Referenced by Sketcher::SketchObject::fillet(), and tangent().
toBSpline()
GeomBSplineCurve * GeomCurve::toBSpline (double first, double last) const
toBSpline Converts the curve to a B-spline
Parameters
This is the start parameter of the curve
This is the end parameter of the curve
Returns
a B-spline curve
References Part::Geometry::Handle().
Referenced by toNurbs().
toNurbs()
GeomBSplineCurve * GeomCurve::toNurbs (double first, double last) const virtual
The default implementation does the same as toBSpline. In sub-classes this can be reimplemented to create a real NURBS curve and not just an approximation.
Reimplemented in Part::GeomCircle, Part::GeomArcOfCircle, Part::GeomEllipse, Part::GeomArcOfEllipse, Part::GeomHyperbola, Part::GeomArcOfHyperbola, Part::GeomParabola, and Part::GeomArcOfParabola.
References toBSpline().
Referenced by Sketcher::SketchObject::convertToNURBS(), Part::GeomEllipse::toNurbs(), Part::GeomHyperbola::toNurbs(), and Part::GeomParabola::toNurbs().
toShape()
TopoDS_Shape GeomCurve::toShape () const virtual
Implements Part::Geometry.
References Part::Geometry::Handle().
value()
Base::Vector3d GeomCurve::value (double u) const
References Part::Geometry::Handle().
Referenced by PathScripts.PathProperty.Property::displayString(), PathScripts.PathProperty.PropertyQuantity::displayString(), PathScripts.PathSetupSheetOpPrototype.Property::displayString(), PathScripts.PathSetupSheetOpPrototype.PropertyQuantity::displayString(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), PathScripts.PathProperty.Property::getValue(), PathScripts.PathSetupSheetOpPrototype.Property::getValue(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), PathScripts.PathProperty.Property::setValue(), and PathScripts.PathSetupSheetOpPrototype.Property::setValue().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/App/Geometry.h
FreeCAD/src/Mod/Part/App/Geometry.cpp