FreeCAD: PartDesignGui::ViewProviderDatum Class Reference
PartDesignGui::ViewProviderDatum Class Reference
#include <ViewProviderDatum.h>
Public Member Functions
virtual void attach (App::DocumentObject *) override
Attaches the document object to this view provider.
virtual bool doubleClicked (void) override
is called by the tree if the user double clicks on the object
virtual SoDetail * getDetail (const char *) const override
return the coin node detail of the subelement
std::vector< std::string > getDisplayModes (void) const override
returns a list of all possible display modes
virtual std::string getElement (const SoDetail *) const override
return a hit element to the selection path or 0
bool isPickable ()
Enable/Disable the selectability of the datum This differs from the normal ViewProvider selectability in that, that with this enabled one can pick through the datum and select stuff behind it.
virtual bool isSelectable (void) const override
indicates if the ViewProvider can be selected
virtual bool onDelete (const std::vector< std::string > &) override
Get called if the object is about to get deleted.
void setDisplayMode (const char *ModeName) override
set the display mode
virtual void setExtents (Base::BoundBox3d)
Update the visual size to match the given extents.
void setExtents (const SbBox3f &bbox)
Update the visual sizes. This overloaded version of the previous function to allow pass coin type.
void setPickable (bool val)
void setupContextMenu (QMenu *, QObject *, const char *) override
grouping handling
void updateExtents ()
update size to match the guessed bounding box
virtual bool useNewSelectionModel (void) const override
indicates if the ViewProvider use the new Selection model
ViewProviderDatum ()
constructor
virtual ~ViewProviderDatum ()
destructor
Public Member Functions inherited from Gui::ViewProviderGeometryObject
void attach (App::DocumentObject *pcObject)
Attaches the document object to this view provider.
SoPickedPoint * getPickedPoint (const SbVec2s &pos, const View3DInventorViewer &viewer) const
This method is provided for convenience and does basically the same as getPickedPoints() unless that only the closest point to the camera will be picked.
SoPickedPointList getPickedPoints (const SbVec2s &pos, const View3DInventorViewer &viewer, bool pickAll=false) const
Returns a list of picked points from the geometry under getRoot().
bool isSelectable (void) const
void updateData (const App::Property *)
ViewProviderGeometryObject ()
constructor.
virtual ~ViewProviderGeometryObject ()
destructor.
virtual void showBoundingBox (bool)
Public Member Functions inherited from Gui::ViewProviderDragger
ViewProviderDragger ()
constructor.
virtual ~ViewProviderDragger ()
destructor.
virtual ViewProvider * startEditing (int ModNum=0) override
Public Member Functions inherited from Gui::ViewProviderDocumentObject
virtual void attach (App::DocumentObject *pcObject)
virtual bool canDelete (App::DocumentObject *obj) const override
Asks the view provider if the given object can be deleted.
virtual bool canDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const override
Query object dropping with full qualified name.
virtual void forceUpdate (bool enable=true)
virtual bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const override
return the coin node detail and path to the node of the subname
Gui::Document * getDocument () const
Get the GUI document to this ViewProvider object.
virtual bool getElementPicked (const SoPickedPoint *, std::string &subname) const override
return a hit element given the picked point which contains the full node path
App::DocumentObject * getObject (void) const
Get the object of this ViewProvider object.
PyObject * getPyObject () override
Get the python wrapper for that ViewProvider.
virtual void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const override
Get a list of TaskBoxes associated with this object.
virtual const char * getTransactionText () const override
Is called by the tree if the user double clicks on the object.
virtual void hide (void) override
Hide the object in the view.
virtual bool isUpdateForced () const
virtual void reattach (App::DocumentObject *)
virtual int replaceObject (App::DocumentObject *, App::DocumentObject *) override
Replace an object to the view provider by drag and drop.
void setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
virtual void show (void) override
Show the object in the view.
virtual bool showInTree () const override
Tell the tree view if this object should appear there.
virtual void update (const App::Property *) override
update the content of the ViewProvider this method have to implement the recalculation of the ViewProvider.
void updateView ()
Run a redraw.
ViewProviderDocumentObject ()
constructor.
virtual ~ViewProviderDocumentObject ()
destructor.
virtual void startRestoring ()
virtual void finishRestoring ()
virtual bool removeDynamicProperty (const char *prop) override
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
virtual ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=nullptr, bool recursive=false) const
Return the linked view object.
virtual std::string getFullName () const override
virtual bool allowOverride (const App::DocumentObject &) const
Allow this class to be used as an override for the original view provider of the given object.
void setShowable (bool enable)
bool isShowable () const
void startDefaultEditMode ()
Start the edit mode with ViewProvider::Default.
Public Member Functions inherited from Gui::ViewProvider
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual std::vector< App::DocumentObject * > claimChildren3D (void) const
deliver the children belonging to this object this method is used to deliver the objects to the 3DView which should be grouped under its scene graph.
SoSeparator * getAnnotation (void)
virtual SoSeparator * getBackRoot (void) const
virtual SoGroup * getChildRoot (void) const
virtual SoSeparator * getFrontRoot (void) const
SoSwitch * getModeSwitch (void) const
virtual SoSeparator * getRoot (void) const
SoTransform * getTransformNode () const
ViewProvider ()
constructor.
virtual ~ViewProvider ()
destructor.
int partialRender (const std::vector< std::string > &subelements, bool clear)
partial rendering setup
virtual std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const
virtual std::vector< Base::Vector3d > getSelectionShape (const char *Element) const
return the highlight lines for a given element or the whole shape
Base::BoundBox3d getBoundingBox (const char *subname=nullptr, bool transform=true, MDIView *view=nullptr) const
Return the bound box of this view object.
virtual void beforeDelete ()
Called before deletion.
virtual bool canDragObjects () const
Check whether children can be removed from the view provider by drag and drop.
virtual bool canDragObject (App::DocumentObject *) const
Check whether the object can be removed from the view provider by drag and drop.
virtual void dragObject (App::DocumentObject *)
Remove a child from the view provider by drag and drop.
virtual bool canDropObjects () const
Check whether objects can be added to the view provider by drag and drop or drop only.
virtual bool canDropObject (App::DocumentObject *) const
Check whether the object can be dropped to the view provider by drag and drop or drop only.
virtual bool canDragAndDropObject (App::DocumentObject *) const
Return false to force drop only operation for a given object.
virtual void dropObject (App::DocumentObject *)
Add an object to the view provider by drag and drop.
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
Add an object with full qualified name to the view provider by drag and drop.
virtual bool canRemoveChildrenFromRoot () const
Tell the tree view to remove children items from the tree root.
std::string getActiveDisplayMode (void) const
virtual const char * getDefaultDisplayMode () const
get the default display mode
virtual bool isShow (void) const
checks whether the view provider is visible or not
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
virtual void setOverrideMode (const std::string &mode)
Overrides the display mode with mode.
const std::string getOverrideMode ()
virtual bool keyPressed (bool pressed, int key)
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
virtual bool mouseMove (const SbVec2s &cursorPos, View3DInventorViewer *viewer)
is called when the provider is in edit and the mouse is moved
virtual bool mouseButtonPressed (int button, bool pressed, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
is called when the Provider is in edit and the mouse is clicked
virtual bool mouseWheelEvent (int delta, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
bool isEditing () const
void finishEditing ()
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
virtual QIcon getIcon (void) const
deliver the icon shown in the tree view
virtual QIcon mergeColorfulOverlayIcons (const QIcon &orig) const
virtual std::vector< App::DocumentObject * > claimChildren (void) const
deliver the children belonging to this object this method is used to deliver the objects to the tree framework which should be grouped under its label.
virtual std::map< std::string, App::Color > getElementColors (const char *element=nullptr) const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
virtual MDIView * getMDIView () const
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
virtual const char * detachFromDocument ()
virtual bool isAttachedToDocument () const
TransactionalObject (void)
Constructor.
virtual ~TransactionalObject ()
Public Member Functions inherited from App::ExtensionContainer
ExtensionIterator extensionBegin ()
ExtensionContainer ()
ExtensionIterator extensionEnd ()
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
void registerExtension (Base::Type extension, App::Extension *ext)
virtual ~ExtensionContainer ()
virtual Property * getPropertyByName (const char *name) const override
find a property by its name
virtual const char * getPropertyName (const Property *prop) const override
get the name of a property
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
virtual void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
virtual short getPropertyType (const Property *prop) const override
get the Type of a Property
virtual short getPropertyType (const char *name) const override
get the Type of a named Property
virtual const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
Public Member Functions inherited from App::PropertyContainer
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false)
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual void editProperty (const char *)
virtual App::Property * getDynamicPropertyByName (const char *name) const
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual std::string getFullName () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Property * getPropertyByName (const char *name) const
find a property by its name
virtual const char * getPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * getPropertyGroup (const Property *prop) const
get the Group of a Property
virtual void getPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual const char * getPropertyName (const Property *prop) const
get the name of a property
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
const char * getPropertyPrefix () const
virtual short getPropertyType (const char *name) const
get the Type of a named Property
virtual short getPropertyType (const Property *prop) const
get the Type of a Property
bool isHidden (const char *name) const
check if the named property is hidden
bool isHidden (const Property *prop) const
check if the property is hidden
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isReadOnly (const Property *prop) const
check if the property is read-only
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus)
PropertyContainer ()
A constructor.
virtual bool removeDynamicProperty (const char *name)
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
void setPropertyPrefix (const char *prefix)
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
virtual ~PropertyContainer ()
A destructor.
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static SbBox3f defaultBoundBox ()
static SbBox3f getRelevantBoundBox (SoGetBoundingBoxAction &bboxAction, const std::vector< App::DocumentObject * > &objs)
Computes appropriate bounding box for the given list of objects to be passed to setExtents ()
static double marginFactor ()
Static Public Member Functions inherited from Gui::ViewProviderDragger
static void updateTransform (const Base::Placement &from, SoTransform *to)
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Public Attributes
QString datumMenuText
QString datumText
QString datumType
The datum type (Plane, Line or Point)
Public Attributes inherited from Gui::ViewProviderGeometryObject
App::PropertyBool BoundingBox
App::PropertyBool Selectable
App::PropertyColor ShapeColor
App::PropertyMaterial ShapeMaterial
App::PropertyPercent Transparency
Public Attributes inherited from Gui::ViewProviderDocumentObject
App::PropertyEnumeration DisplayMode
App::PropertyEnumeration OnTopWhenSelected
App::PropertyEnumeration SelectionStyle
App::PropertyBool ShowInTree
App::PropertyBool Visibility
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
Static Public Attributes
static const double defaultSize = Gui::ViewProviderOrigin::defaultSize ()
Default size used to produce the default bbox.
Protected Member Functions
SbBox3f getRelevantBoundBox () const
Guesses the context this datum belongs to and returns appropriate bounding box of all visible content of the feature.
SoSeparator * getShapeRoot ()
virtual bool setEdit (int ModNum) override
is called by the document when the provider goes in edit mode
virtual void unsetEdit (int ModNum) override
is called when you lose the edit mode
Protected Member Functions inherited from Gui::ViewProviderGeometryObject
void onChanged (const App::Property *prop)
get called by the container whenever a property has been changed
void setSelectable (bool Selectable=true)
virtual unsigned long getBoundColor () const
Protected Member Functions inherited from Gui::ViewProviderDragger
void setEditViewer (View3DInventorViewer *, int ModNum) override
adjust viewer settings when editing a view provider
void unsetEditViewer (View3DInventorViewer *) override
restores viewer settings when leaving editing mode
Protected Member Functions inherited from Gui::ViewProviderDocumentObject
virtual bool isAttachedToDocument () const override
virtual const char * detachFromDocument () override
virtual void onPropertyStatusChanged (const App::Property &prop, unsigned long oldStatus) override
get called when a property status has changed
virtual void setModeSwitch () override
Turn on mode switch.
void addDefaultAction (QMenu *, const QString &)
Adds a menu item and bind it with startDefaultEditMode().
Gui::MDIView * getActiveView () const
Gui::MDIView * getEditingView () const
Gui::MDIView * getInventorView () const
Gui::MDIView * getViewOfNode (SoNode *node) const
virtual void onBeforeChange (const App::Property *prop) override
get called before the value is changed
SoNode * findFrontRootOfType (const SoType &type) const
Searches in all view providers that are attached to an object that is part of the same document as the object this view provider is attached to for an front root of type.
Protected Member Functions inherited from Gui::ViewProvider
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
virtual QIcon mergeGreyableOverlayIcons (const QIcon &orig) const
bool checkRecursion (SoNode *)
Helper method to check that the node is valid, i.e.
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
Helper method to get picked entities while editing.
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
Helper method to get picked entities while editing.
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData (void) const
virtual void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container.
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
virtual void onBeforeChange (const Property *)
get called before the value is changed
virtual void onChanged (const Property *)
get called by the container when a property has changed
Additional Inherited Members
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0 , Transform , Cutting , Color }
Public Types inherited from App::ExtensionContainer
typedef std::map< Base::Type, App::Extension * >::iterator ExtensionIterator
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::ViewProviderGeometryObject
SoMaterial * pcShapeMaterial
SoFCBoundingBox * pcBoundingBox
SoSwitch * pcBoundSwitch
SoBaseColor * pcBoundColor
Protected Attributes inherited from Gui::ViewProviderDragger
SoFCCSysDragger * csysDragger = nullptr
Protected Attributes inherited from Gui::ViewProviderDocumentObject
App::DocumentObject * pcObject
Gui::Document * pcDocument
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation
The root separator for annotations.
ViewProviderPy * pyViewObject
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Constructor & Destructor Documentation
ViewProviderDatum()
ViewProviderDatum::ViewProviderDatum ()
constructor
References App::Color::a, Gui::ViewProviderDocumentObject::DisplayMode, App::GetApplication(), App::Application::GetParameterGroupByPath(), ParameterGrp::GetUnsigned(), App::Property::Hidden, App::Extension::initExtension(), App::Property::setStatus(), App::PropertyColor::setValue(), App::PropertyInteger::setValue(), Gui::ViewProviderGeometryObject::ShapeColor, and Gui::ViewProviderGeometryObject::Transparency.
~ViewProviderDatum()
ViewProviderDatum::~ViewProviderDatum () virtual
destructor
Member Function Documentation
attach()
void ViewProviderDatum::attach (App::DocumentObject * pcObject) override virtual
Attaches the document object to this view provider.
Reimplemented from Gui::ViewProviderGeometryObject.
Reimplemented in PartDesignGui::ViewProviderDatumCoordinateSystem, PartDesignGui::ViewProviderDatumLine, PartDesignGui::ViewProviderDatumPlane, and PartDesignGui::ViewProviderDatumPoint.
References Gui::ViewProvider::addDisplayMaskMode(), datumMenuText, datumText, datumType, Base::Persistence::getClassTypeId(), Gui::ViewProviderDocumentObject::getObject(), and Gui::ViewProviderGeometryObject::pcShapeMaterial.
Referenced by PartDesignGui::ViewProviderDatumCoordinateSystem::attach(), PartDesignGui::ViewProviderDatumLine::attach(), PartDesignGui::ViewProviderDatumPlane::attach(), and PartDesignGui::ViewProviderDatumPoint::attach().
defaultBoundBox()
SbBox3f ViewProviderDatum::defaultBoundBox () static
References defaultSize.
Referenced by PartDesignGui::ViewProviderDatumCoordinateSystem::attach(), PartDesignGui::ViewProviderDatumLine::attach(), PartDesignGui::ViewProviderDatumPlane::attach(), and getRelevantBoundBox().
doubleClicked()
bool ViewProviderDatum::doubleClicked (void) override virtual
is called by the tree if the user double clicks on the object
Reimplemented from Gui::ViewProviderDragger.
References Gui::Application::activeDocument(), PartDesignGui::getBodyFor(), Gui::ViewProviderDocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), Gui::Command::getObjectCmd(), App::PropertyString::getValue(), Gui::Command::Gui, Gui::Application::Instance, App::DocumentObject::Label, Gui::Command::openCommand(), Gui::ViewProviderDocumentObject::pcObject, and PartDesignGui::setEdit().
getDetail()
SoDetail * ViewProviderDatum::getDetail (const char *) const override virtual
return the coin node detail of the subelement
Reimplemented from Gui::ViewProvider.
Reimplemented in PartDesignGui::ViewProviderDatumCoordinateSystem.
getDisplayModes()
std::vector< std::string > ViewProviderDatum::getDisplayModes (void) const override virtual
returns a list of all possible display modes
Reimplemented from Gui::ViewProvider.
getElement()
std::string ViewProviderDatum::getElement (const SoDetail * detail) const override virtual
return a hit element to the selection path or 0
Reimplemented from Gui::ViewProvider.
Reimplemented in PartDesignGui::ViewProviderDatumCoordinateSystem.
References datumType.
getRelevantBoundBox() [1/2]
SbBox3f ViewProviderDatum::getRelevantBoundBox () const protected
Guesses the context this datum belongs to and returns appropriate bounding box of all visible content of the feature.
Currently known contexts are:
PartDesign::Body
App::DocumentObjectGroup (App::Part as well as subclass)
Whole document
References defaultBoundBox(), PartDesign::Body::findBodyOf(), Gui::ViewProviderDocumentObject::getActiveView(), App::DocumentObject::getDocument(), Part::BodyBase::getFullModel(), App::GroupExtension::getGroupOfObject(), Gui::ViewProviderDocumentObject::getObject(), App::Document::getObjects(), getRelevantBoundBox(), and OfflineRenderingUtils::viewer().
Referenced by getRelevantBoundBox(), updateExtents(), and PartDesignGui::ViewProviderBody::updateOriginDatumSize().
getRelevantBoundBox() [2/2]
SbBox3f ViewProviderDatum::getRelevantBoundBox (SoGetBoundingBoxAction & bboxAction, const std::vector< App::DocumentObject * > & objs) static
Computes appropriate bounding box for the given list of objects to be passed to setExtents ()
Parameters
bboxAction a coin action for traverse the given objects views.
objs the list of objects to traverse, due to we traverse the scene graph, the geo children will likely be traversed too.
References defaultBoundBox(), Base::Persistence::getClassTypeId(), Gui::ViewProvider::getRoot(), Gui::Application::getViewProvider(), Gui::Application::Instance, Gui::ViewProvider::isVisible(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
getShapeRoot()
SoSeparator * PartDesignGui::ViewProviderDatum::getShapeRoot () protected
Referenced by PartDesignGui::ViewProviderDatumCoordinateSystem::attach(), PartDesignGui::ViewProviderDatumLine::attach(), PartDesignGui::ViewProviderDatumPlane::attach(), and PartDesignGui::ViewProviderDatumPoint::attach().
isPickable()
bool ViewProviderDatum::isPickable ()
Enable/Disable the selectability of the datum This differs from the normal ViewProvider selectability in that, that with this enabled one can pick through the datum and select stuff behind it.
isSelectable()
bool ViewProviderDatum::isSelectable (void) const override virtual
indicates if the ViewProvider can be selected
Reimplemented from Gui::ViewProviderGeometryObject.
marginFactor()
static double PartDesignGui::ViewProviderDatum::marginFactor () static
Referenced by PartDesignGui::ViewProviderDatumCoordinateSystem::setExtents(), PartDesignGui::ViewProviderDatumLine::setExtents(), and PartDesignGui::ViewProviderDatumPlane::setExtents().
onDelete()
bool ViewProviderDatum::onDelete (const std::vector< std::string > & subNames) override virtual
Get called if the object is about to get deleted.
Here you can delete other objects, switch their visibility or prevent the deletion of the object.
Parameters
subNames list of selected subelements
Returns
true if the deletion is approved by the view provider.
Reimplemented from Gui::ViewProvider.
setDisplayMode()
void ViewProviderDatum::setDisplayMode (const char * ModeName) override virtual
set the display mode
If you add new viewing modes in getDisplayModes() then you need to reimplement also seDisplaytMode() to handle these new modes by setting the appropriate display mode.
Reimplemented from Gui::ViewProvider.
References Gui::ViewProvider::setDisplayMaskMode().
setEdit()
bool ViewProviderDatum::setEdit (int ModNum) override protected virtual
is called by the document when the provider goes in edit mode
Reimplemented from Gui::ViewProviderDragger.
References Gui::ControlSingleton::activeDialog(), Gui::SelectionSingleton::clearSelection(), Gui::ControlSingleton::closeDialog(), Gui::Control(), Gui::ViewProvider::Default, PartGui::TaskDlgAttacher::getViewProvider(), Gui::Selection(), PartDesignGui::ViewProvider::setEdit(), and Gui::ControlSingleton::showDialog().
Referenced by ArchGrid.ViewProviderArchGrid::doubleClicked(), ArchReference.ViewProviderArchReference::doubleClicked(), draftviewproviders.view_dimension.ViewProviderDimensionBase::doubleClicked(), draftviewproviders.view_hatch.ViewProviderDraftHatch::doubleClicked(), draftviewproviders.view_text.ViewProviderText::doubleClicked(), PathScripts.PathPropertyBagGui.ViewProvider::doubleClicked(), PathScripts.PathSetupSheetGui.ViewProvider::doubleClicked(), PathScripts.PathToolBitGui.ViewProvider::doubleClicked(), Spreadsheet_legacy.ViewProviderSpreadsheet::doubleClicked(), ArchSchedule.CommandArchSchedule::IsActive(), PathScripts.PathIconViewProvider.ViewProvider::setupContextMenu(), PathScripts.PathJobGui.ViewProvider::setupContextMenu(), PathScripts.PathOpGui.ViewProvider::setupContextMenu(), and PathScripts.PathToolControllerGui.ViewProvider::setupContextMenu().
setExtents() [1/2]
virtual void PartDesignGui::ViewProviderDatum::setExtents (Base::BoundBox3d) virtual
Update the visual size to match the given extents.
Note
should be reimplemented in the offspings
use FreeCAD-specific bbox here to simplify the math in derived classes
Reimplemented in PartDesignGui::ViewProviderDatumCoordinateSystem, PartDesignGui::ViewProviderDatumLine, and PartDesignGui::ViewProviderDatumPlane.
Referenced by PartDesignGui::ViewProviderDatumCoordinateSystem::attach(), PartDesignGui::ViewProviderDatumLine::attach(), PartDesignGui::ViewProviderDatumPlane::attach(), setExtents(), updateExtents(), and PartDesignGui::ViewProviderBody::updateOriginDatumSize().
setExtents() [2/2]
void ViewProviderDatum::setExtents (const SbBox3f & bbox)
Update the visual sizes. This overloaded version of the previous function to allow pass coin type.
References setExtents().
setPickable()
void ViewProviderDatum::setPickable (bool val)
setupContextMenu()
void ViewProviderDatum::setupContextMenu (QMenu * menu, QObject * receiver, const char * member) override virtual
grouping handling
Reimplemented from Gui::ViewProviderDragger.
References Gui::ViewProvider::Default, and Gui::ViewProvider::setupContextMenu().
unsetEdit()
void ViewProviderDatum::unsetEdit (int ModNum) override protected virtual
is called when you lose the edit mode
Reimplemented from Gui::ViewProviderDragger.
References Gui::ControlSingleton::closeDialog(), Gui::Control(), Gui::ViewProvider::Default, and Gui::ViewProviderDragger::unsetEdit().
Referenced by PathScripts.PathJobGui.ViewProvider::uneditObject().
updateExtents()
void ViewProviderDatum::updateExtents ()
update size to match the guessed bounding box
References getRelevantBoundBox(), and setExtents().
Referenced by PartDesignGui::ViewProviderDatumCoordinateSystem::onChanged(), PartDesignGui::ViewProviderDatumCoordinateSystem::updateData(), PartDesignGui::ViewProviderDatumLine::updateData(), and PartDesignGui::ViewProviderDatumPlane::updateData().
useNewSelectionModel()
virtual bool PartDesignGui::ViewProviderDatum::useNewSelectionModel (void) const override virtual
indicates if the ViewProvider use the new Selection model
Reimplemented from Gui::ViewProvider.
Member Data Documentation
datumMenuText
QString PartDesignGui::ViewProviderDatum::datumMenuText
Referenced by attach().
datumText
QString PartDesignGui::ViewProviderDatum::datumText
Referenced by attach().
datumType
QString PartDesignGui::ViewProviderDatum::datumType
The datum type (Plane, Line or Point)
Referenced by attach(), and getElement().
defaultSize
const double ViewProviderDatum::defaultSize = Gui::ViewProviderOrigin::defaultSize () static
Default size used to produce the default bbox.
Referenced by defaultBoundBox().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/PartDesign/Gui/ViewProviderDatum.h
FreeCAD/src/Mod/PartDesign/Gui/ViewProviderDatum.cpp