FreeCAD: Base::BaseClassPy Class Reference
Base::BaseClassPy Class Reference
The python export class for BaseClass.
#include <BaseClassPy.h>
Public Types
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
callbacks and implementers for the python object attributes
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for BaseClass.
Member Typedef Documentation
PointerType
typedef BaseClass* Base::BaseClassPy::PointerType
Constructor & Destructor Documentation
~BaseClassPy()
BaseClassPy::~BaseClassPy () protected
BaseClassPy()
BaseClassPy::BaseClassPy (BaseClass * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
getAllDerivedFrom()
PyObject * BaseClassPy::getAllDerivedFrom (PyObject * args)
implementer for the getAllDerivedFrom() method
References Base::Type::getAllDerivedFrom(), getBaseClassPtr(), and getTypeId().
Referenced by staticCallback_getAllDerivedFrom().
getBaseClassPtr()
BaseClass * BaseClassPy::getBaseClassPtr (void) const
getter for the object handled by this class
Referenced by getAllDerivedFrom(), getModule(), getTypeId(), and isDerivedFrom().
getCustomAttributes()
PyObject * BaseClassPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getModule()
Py::String BaseClassPy::getModule (void) const
getter for the Module attribute
References getBaseClassPtr(), and getTypeId().
Referenced by staticCallback_getModule().
GetType()
virtual PyTypeObject* Base::BaseClassPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
Reimplemented in TechDraw::DrawWeldSymbolPy, TechDraw::DrawViewSymbolPy, TechDraw::DrawViewPy, TechDraw::DrawViewPartPy, TechDraw::DrawViewDimExtentPy, TechDraw::DrawViewDimensionPy, TechDraw::DrawViewCollectionPy, TechDraw::DrawViewClipPy, TechDraw::DrawViewAnnotationPy, TechDraw::DrawTileWeldPy, TechDraw::DrawTilePy, TechDraw::DrawTemplatePy, TechDraw::DrawSVGTemplatePy, TechDraw::DrawRichAnnoPy, TechDraw::DrawProjGroupPy, TechDraw::DrawProjGroupItemPy, TechDraw::DrawParametricTemplatePy, TechDraw::DrawPagePy, TechDraw::DrawLeaderLinePy, TechDraw::DrawHatchPy, TechDraw::DrawGeomHatchPy, Spreadsheet::SheetPy, Spreadsheet::PropertySheetPy, Spreadsheet::PropertyRowHeightsPy, Spreadsheet::PropertyColumnWidthsPy, Sketcher::SketchPy, Sketcher::SketchObjectSFPy, Sketcher::SketchObjectPy, Sketcher::GeometryFacadePy, Sketcher::ExternalGeometryFacadePy, Sketcher::ConstraintPy, Robot::WaypointPy, Robot::TrajectoryPy, Robot::RobotObjectPy, Robot::Robot6AxisPy, Points::PointsPy, PathSimulator::PathSimPy, Path::VoronoiVertexPy, Path::VoronoiPy, Path::VoronoiEdgePy, Path::VoronoiCellPy, Path::TooltablePy, Path::ToolPy, Path::PathPy, Path::FeaturePathCompoundPy, Path::FeatureAreaPy, Path::CommandPy, Path::AreaPy, PartDesignGui::ViewProviderPy, PartDesign::FeaturePy, PartDesign::BodyPy, Part::TrimmedCurvePy, Part::ToroidPy, Part::TopoShapeWirePy, Part::TopoShapeVertexPy, Part::TopoShapeSolidPy, Part::TopoShapeShellPy, Part::TopoShapePy, Part::TopoShapeFacePy, Part::TopoShapeEdgePy, Part::TopoShapeCompSolidPy, Part::TopoShapeCompoundPy, Part::SurfaceOfRevolutionPy, Part::SurfaceOfExtrusionPy, Part::SpherePy, Part::RectangularTrimmedSurfacePy, Part::PointPy, Part::PlateSurfacePy, Part::PlanePy, Part::PartFeaturePy, Part::Part2DObjectPy, Part::ParabolaPy, Part::OffsetSurfacePy, Part::OffsetCurvePy, Part::LineSegmentPy, Part::LinePy, Part::HyperbolaPy, Part::GeometrySurfacePy, Part::GeometryPy, Part::GeometryCurvePy, Part::EllipsePy, Part::CylinderPy, Part::ConicPy, Part::ConePy, Part::CirclePy, Part::BSplineSurfacePy, Part::BSplineCurvePy, Part::BoundedCurvePy, Part::BodyBasePy, Part::BezierSurfacePy, Part::BezierCurvePy, Attacher::AttachEnginePy, Part::ArcPy, Part::ArcOfParabolaPy, Part::ArcOfHyperbolaPy, Part::ArcOfEllipsePy, Part::ArcOfConicPy, Part::ArcOfCirclePy, MeshGui::ViewProviderMeshPy, Mesh::MeshPy, Mesh::MeshFeaturePy, Measure::MeasurementPy, FemGui::ViewProviderFemMeshPy, Fem::FemPostPipelinePy, Fem::FemMeshPy, Gui::WorkbenchPy, Gui::ViewProviderPy, Gui::ViewProviderLinkPy, Gui::ViewProviderDocumentObjectPy, Gui::SelectionObjectPy, Gui::PythonWorkbenchPy, Gui::LinkViewPy, Gui::DocumentPy, Gui::AxisOriginPy, Base::PersistencePy, App::PropertyContainerPy, App::PartPy, App::GeoFeaturePy, App::ExtensionContainerPy, App::DocumentPy, App::DocumentObjectPy, App::DocumentObjectGroupPy, and Data::ComplexGeoDataPy.
getTypeId()
Py::String BaseClassPy::getTypeId (void) const
getter for the TypeId attribute
References getBaseClassPtr().
Referenced by Gui::WorkbenchPy::activate(), getAllDerivedFrom(), Attacher::AttachEnginePy::getAttacherType(), Attacher::AttachEnginePy::getModeInfo(), getModule(), Sketcher::ExternalGeometryFacadePy::setConstruction(), and staticCallback_getTypeId().
isDerivedFrom()
PyObject * BaseClassPy::isDerivedFrom (PyObject * args)
implementer for the isDerivedFrom() method
References Base::Type::badType(), Base::Type::fromName(), getBaseClassPtr(), Base::BaseClass::getTypeId(), and Base::Type::isDerivedFrom().
Referenced by App::PropertyContainerPy::getCustomAttributes(), and staticCallback_isDerivedFrom().
PyInit()
int BaseClassPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
Reimplemented in TechDraw::DrawWeldSymbolPy, TechDraw::DrawViewSymbolPy, TechDraw::DrawViewPy, TechDraw::DrawViewPartPy, TechDraw::DrawViewDimExtentPy, TechDraw::DrawViewDimensionPy, TechDraw::DrawViewCollectionPy, TechDraw::DrawViewClipPy, TechDraw::DrawViewAnnotationPy, TechDraw::DrawTileWeldPy, TechDraw::DrawTilePy, TechDraw::DrawTemplatePy, TechDraw::DrawSVGTemplatePy, TechDraw::DrawRichAnnoPy, TechDraw::DrawProjGroupPy, TechDraw::DrawProjGroupItemPy, TechDraw::DrawParametricTemplatePy, TechDraw::DrawPagePy, TechDraw::DrawLeaderLinePy, TechDraw::DrawHatchPy, TechDraw::DrawGeomHatchPy, Spreadsheet::SheetPy, Spreadsheet::PropertySheetPy, Spreadsheet::PropertyRowHeightsPy, Spreadsheet::PropertyColumnWidthsPy, Sketcher::SketchPy, Sketcher::SketchObjectSFPy, Sketcher::SketchObjectPy, Sketcher::GeometryFacadePy, Sketcher::ExternalGeometryFacadePy, Sketcher::ConstraintPy, Robot::WaypointPy, Robot::TrajectoryPy, Robot::RobotObjectPy, Robot::Robot6AxisPy, Points::PointsPy, PathSimulator::PathSimPy, Path::VoronoiVertexPy, Path::VoronoiPy, Path::VoronoiEdgePy, Path::VoronoiCellPy, Path::TooltablePy, Path::ToolPy, Path::PathPy, Path::FeaturePathCompoundPy, Path::FeatureAreaPy, Path::CommandPy, Path::AreaPy, PartDesignGui::ViewProviderPy, PartDesign::FeaturePy, PartDesign::BodyPy, Part::TrimmedCurvePy, Part::ToroidPy, Part::TopoShapeWirePy, Part::TopoShapeVertexPy, Part::TopoShapeSolidPy, Part::TopoShapeShellPy, Part::TopoShapePy, Part::TopoShapeFacePy, Part::TopoShapeEdgePy, Part::TopoShapeCompSolidPy, Part::TopoShapeCompoundPy, Part::SurfaceOfRevolutionPy, Part::SurfaceOfExtrusionPy, Part::SpherePy, Part::RectangularTrimmedSurfacePy, Part::PointPy, Part::PlateSurfacePy, Part::PlanePy, Part::PartFeaturePy, Part::Part2DObjectPy, Part::ParabolaPy, Part::OffsetSurfacePy, Part::OffsetCurvePy, Part::LineSegmentPy, Part::LinePy, Part::HyperbolaPy, Part::GeometrySurfacePy, Part::GeometryPy, Part::GeometryCurvePy, Part::EllipsePy, Part::CylinderPy, Part::ConicPy, Part::ConePy, Part::CirclePy, Part::BSplineSurfacePy, Part::BSplineCurvePy, Part::BoundedCurvePy, Part::BodyBasePy, Part::BezierSurfacePy, Part::BezierCurvePy, Attacher::AttachEnginePy, Part::ArcPy, Part::ArcOfParabolaPy, Part::ArcOfHyperbolaPy, Part::ArcOfEllipsePy, Part::ArcOfConicPy, Part::ArcOfCirclePy, MeshGui::ViewProviderMeshPy, Mesh::MeshPy, Mesh::MeshFeaturePy, Measure::MeasurementPy, FemGui::ViewProviderFemMeshPy, Fem::FemPostPipelinePy, Fem::FemMeshPy, Gui::WorkbenchPy, Gui::ViewProviderPy, Gui::ViewProviderLinkPy, Gui::ViewProviderDocumentObjectPy, Gui::SelectionObjectPy, Gui::PythonWorkbenchPy, Gui::LinkViewPy, Gui::DocumentPy, Gui::AxisOriginPy, Base::PersistencePy, App::PropertyContainerPy, App::PartPy, App::GeoFeaturePy, App::ExtensionContainerPy, App::DocumentPy, App::DocumentObjectPy, App::DocumentObjectGroupPy, and Data::ComplexGeoDataPy.
PyMake()
PyObject * BaseClassPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string BaseClassPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int BaseClassPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_getAllDerivedFrom()
PyObject * BaseClassPy::staticCallback_getAllDerivedFrom (PyObject * self, PyObject * args) static
callback for the getAllDerivedFrom() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getAllDerivedFrom(), and Base::PyObjectBase::isValid().
staticCallback_getModule()
PyObject * BaseClassPy::staticCallback_getModule (PyObject * self, void * closure) static
getter callback for the Module attribute
References Base::BaseExceptionFreeCADError, getModule(), and Base::PyObjectBase::isValid().
staticCallback_getTypeId()
PyObject * BaseClassPy::staticCallback_getTypeId (PyObject * self, void * closure) static
getter callback for the TypeId attribute
References Base::BaseExceptionFreeCADError, getTypeId(), and Base::PyObjectBase::isValid().
staticCallback_isDerivedFrom()
PyObject * BaseClassPy::staticCallback_isDerivedFrom (PyObject * self, PyObject * args) static
callback for the isDerivedFrom() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isDerivedFrom(), and Base::PyObjectBase::isValid().
staticCallback_setModule()
int BaseClassPy::staticCallback_setModule (PyObject * self, PyObject * value, void * closure) static
setter callback for the Module attribute
References Base::PyObjectBase::isValid().
staticCallback_setTypeId()
int BaseClassPy::staticCallback_setTypeId (PyObject * self, PyObject * value, void * closure) static
setter callback for the TypeId attribute
References Base::PyObjectBase::isValid().
Member Data Documentation
GetterSetter
PyGetSetDef BaseClassPy::GetterSetter static
Initial value:
= {
    {"TypeId",
        (getter) staticCallback_getTypeId,
        (setter) staticCallback_setTypeId,
        "Is the type of the FreeCAD object with module domain",
        NULL
    },
    {"Module",
        (getter) staticCallback_getModule,
        (setter) staticCallback_setModule,
        "Module in which this class is defined",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of BaseClassPy.
Methods
PyMethodDef BaseClassPy::Methods static
Initial value:
= {
    {"isDerivedFrom",
        reinterpret_cast<PyCFunction>( staticCallback_isDerivedFrom ),
        METH_VARARGS,
        "Returns true if given type is a father"
    },
    {"getAllDerivedFrom",
        reinterpret_cast<PyCFunction>( staticCallback_getAllDerivedFrom ),
        METH_VARARGS,
        "Returns all descendants"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of BaseClassPy.
Type
PyTypeObject BaseClassPy::Type static
Type structure of BaseClassPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Base/BaseClassPy.h
Sources/FreeCAD/src/Base/BaseClassPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Base/BaseClassPy.cpp