FreeCAD: FemGui::Ui_DlgSettingsFemMystranImp Class Reference
FemGui::Ui_DlgSettingsFemMystranImp Class Reference
#include <ui_DlgSettingsFemMystran.h>
Public Member Functions
void retranslateUi (QWidget *FemGui__DlgSettingsFemMystranImp)
void setupUi (QWidget *FemGui__DlgSettingsFemMystranImp)
Public Attributes
Gui::PrefCheckBox * cb_mystran_binary_std
Gui::PrefCheckBox * cb_mystran_write_comments
Gui::PrefFileChooser * fc_mystran_binary_path
QGroupBox * gb_mystran_param
QGridLayout * gridLayout
QLabel * l_mystran_binary_path
QLabel * l_mystran_write_comments
QVBoxLayout * verticalLayout
QVBoxLayout * verticalLayout_2
QSpacerItem * verticalSpacer
Member Function Documentation
retranslateUi()
void FemGui::Ui_DlgSettingsFemMystranImp::retranslateUi (QWidget * FemGui__DlgSettingsFemMystranImp)
References cb_mystran_binary_std, cb_mystran_write_comments, fc_mystran_binary_path, gb_mystran_param, l_mystran_binary_path, l_mystran_write_comments, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void FemGui::Ui_DlgSettingsFemMystranImp::setupUi (QWidget * FemGui__DlgSettingsFemMystranImp)
References cb_mystran_binary_std, cb_mystran_write_comments, draftgeoutils.intersections::connect(), fc_mystran_binary_path, gb_mystran_param, gridLayout, l_mystran_binary_path, l_mystran_write_comments, retranslateUi(), verticalLayout, verticalLayout_2, and verticalSpacer.
Member Data Documentation
cb_mystran_binary_std
Gui::PrefCheckBox* FemGui::Ui_DlgSettingsFemMystranImp::cb_mystran_binary_std
Referenced by retranslateUi(), and setupUi().
cb_mystran_write_comments
Gui::PrefCheckBox* FemGui::Ui_DlgSettingsFemMystranImp::cb_mystran_write_comments
Referenced by retranslateUi(), and setupUi().
fc_mystran_binary_path
Gui::PrefFileChooser* FemGui::Ui_DlgSettingsFemMystranImp::fc_mystran_binary_path
Referenced by retranslateUi(), and setupUi().
gb_mystran_param
QGroupBox* FemGui::Ui_DlgSettingsFemMystranImp::gb_mystran_param
Referenced by retranslateUi(), and setupUi().
gridLayout
QGridLayout* FemGui::Ui_DlgSettingsFemMystranImp::gridLayout
Referenced by setupUi().
l_mystran_binary_path
QLabel* FemGui::Ui_DlgSettingsFemMystranImp::l_mystran_binary_path
Referenced by retranslateUi(), and setupUi().
l_mystran_write_comments
QLabel* FemGui::Ui_DlgSettingsFemMystranImp::l_mystran_write_comments
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* FemGui::Ui_DlgSettingsFemMystranImp::verticalLayout
Referenced by setupUi().
verticalLayout_2
QVBoxLayout* FemGui::Ui_DlgSettingsFemMystranImp::verticalLayout_2
Referenced by setupUi().
verticalSpacer
QSpacerItem* FemGui::Ui_DlgSettingsFemMystranImp::verticalSpacer
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Fem/Gui/ui_DlgSettingsFemMystran.h