FreeCAD: Gui::Dialog::DlgCustomizeSpNavSettings Class Reference
Gui::Dialog::DlgCustomizeSpNavSettings Class Reference
#include <DlgCustomizeSpNavSettings.h>
Public Member Functions
DlgCustomizeSpNavSettings (QWidget *parent=nullptr)
~DlgCustomizeSpNavSettings ()
Public Member Functions inherited from Gui::Dialog::CustomizeActionPage
CustomizeActionPage (QWidget *parent=nullptr)
Construction.
virtual ~CustomizeActionPage ()
Destruction.
Protected Slots
void on_ButtonCalibrate_clicked ()
void on_ButtonDefaultSpNavMotions_clicked ()
void on_CBDominant_clicked ()
void on_CBEnablePanLR_clicked ()
void on_CBEnablePanUD_clicked ()
void on_CBEnableRoll_clicked ()
void on_CBEnableSpin_clicked ()
void on_CBEnableTilt_clicked ()
void on_CBEnableZoom_clicked ()
void on_CBFlipYZ_clicked ()
void on_CBReversePanLR_clicked ()
void on_CBReversePanUD_clicked ()
void on_CBReverseRoll_clicked ()
void on_CBReverseSpin_clicked ()
void on_CBReverseTilt_clicked ()
void on_CBReverseZoom_clicked ()
void on_CBRotations_clicked ()
void on_CBTranslations_clicked ()
void on_SliderGlobal_sliderReleased ()
void on_SliderPanLR_sliderReleased ()
void on_SliderPanUD_sliderReleased ()
void on_SliderRoll_sliderReleased ()
void on_SliderSpin_sliderReleased ()
void on_SliderTilt_sliderReleased ()
void on_SliderZoom_sliderReleased ()
void onAddMacroAction (const QByteArray &)
void onModifyMacroAction (const QByteArray &)
void onRemoveMacroAction (const QByteArray &)
Protected Slots inherited from Gui::Dialog::CustomizeActionPage
virtual void onAddMacroAction (const QByteArray &)=0
virtual void onModifyMacroAction (const QByteArray &)=0
virtual void onRemoveMacroAction (const QByteArray &)=0
Protected Member Functions
void changeEvent (QEvent *e)
Protected Member Functions inherited from Gui::Dialog::CustomizeActionPage
virtual void changeEvent (QEvent *e)=0
bool event (QEvent *e)
Constructor & Destructor Documentation
DlgCustomizeSpNavSettings()
DlgCustomizeSpNavSettings::DlgCustomizeSpNavSettings (QWidget * parent = nullptr) explicit
~DlgCustomizeSpNavSettings()
DlgCustomizeSpNavSettings::~DlgCustomizeSpNavSettings ()
Member Function Documentation
changeEvent()
void DlgCustomizeSpNavSettings::changeEvent (QEvent * e) protected virtual
Implements Gui::Dialog::CustomizeActionPage.
on_ButtonCalibrate_clicked
void DlgCustomizeSpNavSettings::on_ButtonCalibrate_clicked () protected slot
References ParameterGrp::SetBool().
on_ButtonDefaultSpNavMotions_clicked
void DlgCustomizeSpNavSettings::on_ButtonDefaultSpNavMotions_clicked () protected slot
References ParameterGrp::Clear().
on_CBDominant_clicked
void DlgCustomizeSpNavSettings::on_CBDominant_clicked () protected slot
References ParameterGrp::SetBool().
on_CBEnablePanLR_clicked
void DlgCustomizeSpNavSettings::on_CBEnablePanLR_clicked () protected slot
References ParameterGrp::SetBool().
on_CBEnablePanUD_clicked
void DlgCustomizeSpNavSettings::on_CBEnablePanUD_clicked () protected slot
References ParameterGrp::SetBool().
on_CBEnableRoll_clicked
void DlgCustomizeSpNavSettings::on_CBEnableRoll_clicked () protected slot
References ParameterGrp::SetBool().
on_CBEnableSpin_clicked
void DlgCustomizeSpNavSettings::on_CBEnableSpin_clicked () protected slot
References ParameterGrp::SetBool().
on_CBEnableTilt_clicked
void DlgCustomizeSpNavSettings::on_CBEnableTilt_clicked () protected slot
References ParameterGrp::SetBool().
on_CBEnableZoom_clicked
void DlgCustomizeSpNavSettings::on_CBEnableZoom_clicked () protected slot
References ParameterGrp::SetBool().
on_CBFlipYZ_clicked
void DlgCustomizeSpNavSettings::on_CBFlipYZ_clicked () protected slot
References ParameterGrp::SetBool().
on_CBReversePanLR_clicked
void DlgCustomizeSpNavSettings::on_CBReversePanLR_clicked () protected slot
References ParameterGrp::SetBool().
on_CBReversePanUD_clicked
void DlgCustomizeSpNavSettings::on_CBReversePanUD_clicked () protected slot
References ParameterGrp::SetBool().
on_CBReverseRoll_clicked
void DlgCustomizeSpNavSettings::on_CBReverseRoll_clicked () protected slot
References ParameterGrp::SetBool().
on_CBReverseSpin_clicked
void DlgCustomizeSpNavSettings::on_CBReverseSpin_clicked () protected slot
References ParameterGrp::SetBool().
on_CBReverseTilt_clicked
void DlgCustomizeSpNavSettings::on_CBReverseTilt_clicked () protected slot
References ParameterGrp::SetBool().
on_CBReverseZoom_clicked
void DlgCustomizeSpNavSettings::on_CBReverseZoom_clicked () protected slot
References ParameterGrp::SetBool().
on_CBRotations_clicked
void DlgCustomizeSpNavSettings::on_CBRotations_clicked () protected slot
References ParameterGrp::SetBool().
on_CBTranslations_clicked
void DlgCustomizeSpNavSettings::on_CBTranslations_clicked () protected slot
References ParameterGrp::SetBool().
on_SliderGlobal_sliderReleased
void DlgCustomizeSpNavSettings::on_SliderGlobal_sliderReleased () protected slot
References ParameterGrp::SetInt().
on_SliderPanLR_sliderReleased
void DlgCustomizeSpNavSettings::on_SliderPanLR_sliderReleased () protected slot
References ParameterGrp::SetInt().
on_SliderPanUD_sliderReleased
void DlgCustomizeSpNavSettings::on_SliderPanUD_sliderReleased () protected slot
References ParameterGrp::SetInt().
on_SliderRoll_sliderReleased
void DlgCustomizeSpNavSettings::on_SliderRoll_sliderReleased () protected slot
References ParameterGrp::SetInt().
on_SliderSpin_sliderReleased
void DlgCustomizeSpNavSettings::on_SliderSpin_sliderReleased () protected slot
References ParameterGrp::SetInt().
on_SliderTilt_sliderReleased
void DlgCustomizeSpNavSettings::on_SliderTilt_sliderReleased () protected slot
References ParameterGrp::SetInt().
on_SliderZoom_sliderReleased
void DlgCustomizeSpNavSettings::on_SliderZoom_sliderReleased () protected slot
References ParameterGrp::SetInt().
onAddMacroAction
void DlgCustomizeSpNavSettings::onAddMacroAction (const QByteArray & macroName) protected slot
onModifyMacroAction
void DlgCustomizeSpNavSettings::onModifyMacroAction (const QByteArray & macroName) protected slot
onRemoveMacroAction
void DlgCustomizeSpNavSettings::onRemoveMacroAction (const QByteArray & macroName) protected slot
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgCustomizeSpNavSettings.h
FreeCAD/src/Gui/DlgCustomizeSpNavSettings.cpp