FreeCAD: femexamples.ccx_cantilever_base_solid Namespace Reference
femexamples.ccx_cantilever_base_solid Namespace Reference
Functions
def setup_cantilever_base_solid (doc=None, solvertype="ccxtools")
Function Documentation
setup_cantilever_base_solid()
def femexamples.ccx_cantilever_base_solid.setup_cantilever_base_solid (doc = None, solvertype = "ccxtools")
References ObjectsFem.makeAnalysis(), ObjectsFem.makeConstraintFixed(), ObjectsFem.makeEquationElasticity(), ObjectsFem.makeMaterialSolid(), ObjectsFem.makeMeshGmsh(), ObjectsFem.makeSolverCalculix(), ObjectsFem.makeSolverCalculixCcxTools(), ObjectsFem.makeSolverElmer(), ObjectsFem.makeSolverMystran(), and ObjectsFem.makeSolverZ88().