FreeCAD: UNV Namespace Reference
UNV Namespace Reference
Classes
class PrefixPrinter
Functions
bool beginning_of_dataset (std::istream &in_file, const std::string &ds_name)
bool check_file (const std::string theFileName)
double D_to_e (std::string &number)
Method for converting exponential notation from "D" to "e", for example 3.141592654D+00 --> 3.141592654e+00 in order to make it readable for C++.
std::string read_line (std::ifstream &in_stream, const bool next=true)
reads a whole line
Variables
const size_t theMaxLineLen = 82
Function Documentation
beginning_of_dataset()
bool UNV::beginning_of_dataset (std::istream & in_file, const std::string & ds_name)
Returns
false when error occurred, true otherwise. Adjusts the in_stream to the beginning of the dataset ds_name.
Referenced by UNV2420::Read(), UNV2411::Read(), UNV2412::Read(), and UNV164::Read().
check_file()
bool UNV::check_file (const std::string theFileName)
Returns
false when file is incorrect, true otherwise. Check file with name theFileName for correct terminate string, i.e. the next to the last line is equal to " -1",
Referenced by DriverUNV_W_SMDS_Mesh::Perform().
D_to_e()
double UNV::D_to_e (std::string & number)
Method for converting exponential notation from "D" to "e", for example 3.141592654D+00 --> 3.141592654e+00 in order to make it readable for C++.
Referenced by UNV2420::Read(), UNV2411::Read(), and UNV164::Read().
read_line()
std::string UNV::read_line (std::ifstream & in_stream, const bool next = true)
reads a whole line
Parameters
in_stream - source stream
next - if true, first reads the current line up to the end which is necessary after reading using >> operator
Return values
std::string - the result line
Referenced by UNV2420::Read(), and UNV2411::Read().
Variable Documentation
theMaxLineLen
const size_t UNV::theMaxLineLen = 82
Referenced by UNV164::Read().