FreeCAD: Gui::PropertyEditor::PropertyMatrixItem Class Reference
Gui::PropertyEditor::PropertyMatrixItem Class Reference
#include <PropertyItem.h>
Protected Member Functions
PropertyMatrixItem ()
virtual void setValue (const QVariant &)
virtual QVariant toolTip (const App::Property *) const
virtual QVariant toString (const QVariant &) const
virtual QVariant value (const App::Property *) const
Protected Member Functions inherited from Gui::PropertyEditor::PropertyItem
virtual QVariant decoration (const QVariant &) const
virtual QVariant displayName () const
virtual void initialize ()
virtual void onChange ()
PropertyItem ()
Protected Member Functions inherited from Gui::ExpressionBinding
void expressionChange (const App::ObjectIdentifier &id)
std::string getEscapedExpressionString () const
boost::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
const App::ObjectIdentifier & getPath () const
void objectDeleted (const App::DocumentObject &)
virtual void setExpression (boost::shared_ptr< App::Expression > expr)
Properties
double A11
double A12
double A13
double A14
double A21
double A22
double A23
double A24
double A31
double A32
double A33
double A34
double A41
double A42
double A43
double A44
Additional Inherited Members
Public Member Functions inherited from Gui::PropertyEditor::PropertyItem
void appendChild (PropertyItem *child)
virtual void assignProperty (const App::Property *)
virtual void bind (const App::ObjectIdentifier &_path)
virtual void bind (const App::Property &prop)
override the bind functions to ensure we issue the propertyBound() call, which is then overloaded by childs which like to be informed of a binding
PropertyItem * child (int row)
int childCount () const
int columnCount () const
QWidget * createExpressionEditor (QWidget *parent, const QObject *receiver, const char *method) const
virtual QVariant data (int column, int role) const
int decimals () const
QString expressionAsString () const
QVariant expressionEditorData (QWidget *editor) const
Qt::ItemFlags flags (int column) const
App::Property * getFirstProperty ()
const App::Property * getFirstProperty () const
const std::vector< App::Property * > & getPropertyData () const
bool hasAnyExpression () const
bool hasProperty (const App::Property *) const
void insertChild (int, PropertyItem *child)
bool isLinked () const
bool isReadOnly () const
virtual bool isSeparator () const
PropertyItem * parent () const
virtual void propertyBound ()
QString propertyName () const
void removeChildren (int from, int to)
PropertyItem::removeChildren Deletes the children in the range of [from, to].
bool removeProperty (const App::Property *)
void reset ()
int row () const
bool setData (const QVariant &value)
void setDecimals (int)
void setExpressionEditorData (QWidget *editor, const QVariant &data) const
void setLinked (bool)
void setParent (PropertyItem *parent)
void setPropertyData (const std::vector< App::Property * > &)
Sets the current property objects.
void setPropertyName (const QString &)
void setPropertyValue (const QString &)
void setReadOnly (bool)
PropertyItem * takeChild (int)
PropertyItem::takeChild Removes the child at index row but doesn't delete it.
bool testStatus (App::Property::Status pos) const
void updateData ()
~PropertyItem ()
Public Member Functions inherited from Gui::ExpressionBinding
virtual bool apply ()
virtual bool apply (const std::string &propName)
bool autoApply () const
ExpressionBinding ()
QPixmap getIcon (const char *name, const QSize &size) const
bool hasExpression () const
bool isBound () const
void setAutoApply (bool value)
void unbind ()
virtual ~ExpressionBinding ()
Protected Attributes inherited from Gui::PropertyEditor::PropertyItem
QList< PropertyItem * > childItems
bool cleared
QString displayText
bool linked
PropertyItem * parentItem
int precision
std::vector< App::Property * > propertyItems
QString propName
bool readonly
Protected Attributes inherited from Gui::ExpressionBinding
QPalette defaultPalette
boost::signals2::scoped_connection expressionchanged
int iconHeight
QLabel * iconLabel
bool m_autoApply
boost::signals2::scoped_connection objectdeleted
Constructor & Destructor Documentation
PropertyMatrixItem()
PropertyMatrixItem::PropertyMatrixItem () protected
References femsolver.elmer.equations.elasticity::create(), and Gui::PropertyEditor::PropertyItem::setParent().
Member Function Documentation
setValue()
void PropertyMatrixItem::setValue (const QVariant & value) protected virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
References Gui::PropertyEditor::PropertyItem::decimals(), and Gui::PropertyEditor::PropertyItem::setPropertyValue().
toolTip()
QVariant PropertyMatrixItem::toolTip (const App::Property * prop) const protected virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
References Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), and Base::Type::isDerivedFrom().
toString()
QVariant PropertyMatrixItem::toString (const QVariant & prop) const protected virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
value()
QVariant PropertyMatrixItem::value (const App::Property * prop) const protected virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
References Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), and Base::Type::isDerivedFrom().
Referenced by PathScripts.PathProperty.Property::displayString(), PathScripts.PathProperty.PropertyQuantity::displayString(), PathScripts.PathSetupSheetOpPrototype.Property::displayString(), PathScripts.PathSetupSheetOpPrototype.PropertyQuantity::displayString(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), PathScripts.PathProperty.Property::getValue(), PathScripts.PathSetupSheetOpPrototype.Property::getValue(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), PathScripts.PathProperty.Property::setValue(), and PathScripts.PathSetupSheetOpPrototype.Property::setValue().
Property Documentation
A11
double Gui::PropertyEditor::PropertyMatrixItem::A11 read write
A12
double Gui::PropertyEditor::PropertyMatrixItem::A12 read write
A13
double Gui::PropertyEditor::PropertyMatrixItem::A13 read write
A14
double Gui::PropertyEditor::PropertyMatrixItem::A14 read write
A21
double Gui::PropertyEditor::PropertyMatrixItem::A21 read write
A22
double Gui::PropertyEditor::PropertyMatrixItem::A22 read write
A23
double Gui::PropertyEditor::PropertyMatrixItem::A23 read write
A24
double Gui::PropertyEditor::PropertyMatrixItem::A24 read write
A31
double Gui::PropertyEditor::PropertyMatrixItem::A31 read write
A32
double Gui::PropertyEditor::PropertyMatrixItem::A32 read write
A33
double Gui::PropertyEditor::PropertyMatrixItem::A33 read write
A34
double Gui::PropertyEditor::PropertyMatrixItem::A34 read write
A41
double Gui::PropertyEditor::PropertyMatrixItem::A41 read write
A42
double Gui::PropertyEditor::PropertyMatrixItem::A42 read write
A43
double Gui::PropertyEditor::PropertyMatrixItem::A43 read write
A44
double Gui::PropertyEditor::PropertyMatrixItem::A44 read write
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/propertyeditor/PropertyItem.h
Sources/FreeCAD/src/Gui/propertyeditor/PropertyItem.cpp