FreeCAD: PathScripts.PathToolBitGui Namespace Reference
PathScripts.PathToolBitGui Namespace Reference
Classes
class TaskPanel
class ToolBitGuiFactory
class ViewProvider
Functions
def GetNewToolFile (parent=None)
def GetToolFile (parent=None)
def GetToolFiles (parent=None)
def GetToolShapeFile (parent=None)
def isValidFileName (filename)
def LoadTool (parent=None)
def LoadTools (parent=None)
def translate (context, text, disambig=None)
Function Documentation
GetNewToolFile()
def PathScripts.PathToolBitGui.GetNewToolFile (parent = None)
References PathScripts.PathToolBitGui.isValidFileName().
GetToolFile()
def PathScripts.PathToolBitGui.GetToolFile (parent = None)
Referenced by PathScripts.PathToolBitGui.LoadTool().
GetToolFiles()
def PathScripts.PathToolBitGui.GetToolFiles (parent = None)
Referenced by PathScripts.PathToolBitGui.LoadTools().
GetToolShapeFile()
def PathScripts.PathToolBitGui.GetToolShapeFile (parent = None)
isValidFileName()
def PathScripts.PathToolBitGui.isValidFileName (filename)
Referenced by PathScripts.PathToolBitGui.GetNewToolFile().
LoadTool()
def PathScripts.PathToolBitGui.LoadTool (parent = None)
LoadTool(parent=None) ... Open a file dialog to load a tool from a file.
References PathScripts.PathToolBitGui.GetToolFile().
LoadTools()
def PathScripts.PathToolBitGui.LoadTools (parent = None)
LoadTool(parent=None) ... Open a file dialog to load a tool from a file.
References PathScripts.PathToolBitGui.GetToolFiles().
Referenced by PathScripts.PathToolBitCmd.CommandToolBitLoad.Activated().
translate()
def PathScripts.PathToolBitGui.translate (context, text, disambig = None)