FreeCAD: SMESH_NodeSearcherImpl Struct Reference
SMESH_NodeSearcherImpl Struct Reference
Implementation of search for the node closest to point.
Public Member Functions
const SMDS_MeshNode * FindClosestTo (const gp_Pnt &thePnt)
Do it's job.
int FindNearPoint (const gp_Pnt &point, const double tolerance, std::vector< const SMDS_MeshNode * > &foundNodes)
Finds nodes located within a tolerance near a point.
const SMESH_OctreeNode * getTree () const
Return the node tree.
void MoveNode (const SMDS_MeshNode *node, const gp_Pnt &toPnt)
Move node and update myOctreeNode accordingly.
SMESH_NodeSearcherImpl (const SMDS_Mesh *theMesh)
Constructor.
~SMESH_NodeSearcherImpl ()
Destructor.
Public Member Functions inherited from SMESH_NodeSearcher
virtual ~SMESH_NodeSearcher ()
Detailed Description
Implementation of search for the node closest to point.
Constructor & Destructor Documentation
SMESH_NodeSearcherImpl()
SMESH_NodeSearcherImpl::SMESH_NodeSearcherImpl (const SMDS_Mesh * theMesh)
Constructor.
References SMESH_OctreeNode::GetChildrenIterator(), SMESH_Tree< BND_BOX, NB_CHILDREN >::isLeaf(), SMESH_Octree::maxSize(), and SMDS_Mesh::nodesIterator().
~SMESH_NodeSearcherImpl()
SMESH_NodeSearcherImpl::~SMESH_NodeSearcherImpl ()
Destructor.
Member Function Documentation
FindClosestTo()
const SMDS_MeshNode* SMESH_NodeSearcherImpl::FindClosestTo (const gp_Pnt & thePnt) virtual
Do it's job.
Implements SMESH_NodeSearcher.
References SMESH_Tree< BND_BOX, NB_CHILDREN >::getBox(), SMESH_OctreeNode::GetChildrenIterator(), SMESH_OctreeNode::GetNodeIterator(), SMESH_OctreeNode::isInside(), SMESH_Tree< BND_BOX, NB_CHILDREN >::isLeaf(), SMESH_OctreeNode::NbNodes(), and SMESH_OctreeNode::NodesAround().
FindNearPoint()
int SMESH_NodeSearcherImpl::FindNearPoint (const gp_Pnt & point, const double tolerance, std::vector< const SMDS_MeshNode * > & foundNodes) virtual
Finds nodes located within a tolerance near a point.
Implements SMESH_NodeSearcher.
References draftutils.utils::tolerance().
Referenced by SMESH_ElementSearcherImpl::FindElementsByPoint().
getTree()
const SMESH_OctreeNode* SMESH_NodeSearcherImpl::getTree () const
Return the node tree.
Referenced by SMESH_ElementSearcherImpl::getTolerance().
MoveNode()
void SMESH_NodeSearcherImpl::MoveNode (const SMDS_MeshNode * node, const gp_Pnt & toPnt) virtual
Move node and update myOctreeNode accordingly.
Implements SMESH_NodeSearcher.
References SMDS_MeshNode::X().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/SMESH_MeshAlgos.cpp