FreeCAD: MeshGui::CleanupHandler Class Reference
MeshGui::CleanupHandler Class Reference
The GuiCleanupHandler class is used to cleanup GUI elements from the MeshGui module when the application is about to be closed.
#include <DlgEvaluateMeshImp.h>
Public Slots
void cleanup ()
Public Member Functions
CleanupHandler ()
Detailed Description
The GuiCleanupHandler class is used to cleanup GUI elements from the MeshGui module when the application is about to be closed.
Author
Werner Mayer
Constructor & Destructor Documentation
CleanupHandler()
CleanupHandler::CleanupHandler ()
References cleanup(), and draftgeoutils.intersections::connect().
Member Function Documentation
cleanup
void CleanupHandler::cleanup () slot
References MeshGui::DockEvaluateMeshImp::destruct().
Referenced by PathPythonGui.simple_edit_panel.SimpleEditPanel::abort(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::abort(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::abort(), PathScripts.PathDressupDogbone.TaskPanel::accept(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::accept(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::accept(), PathScripts.PathJobGui.TaskPanel::accept(), PathScripts.PathOpGui.TaskPanel::accept(), CleanupHandler(), PathScripts.PathDressupDogbone.TaskPanel::reject(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::reject(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::reject(), PathScripts.PathJobGui.TaskPanel::reject(), and PathScripts.PathOpGui.TaskPanel::reject().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/Gui/DlgEvaluateMeshImp.h
FreeCAD/src/Mod/Mesh/Gui/DlgEvaluateMeshImp.cpp