FreeCAD: ClipperLib::PolyNode Class Reference
ClipperLib::PolyNode Class Reference
#include <clipper.hpp>
Public Member Functions
int ChildCount () const
PolyNode * GetNext () const
bool IsHole () const
bool IsOpen () const
PolyNode ()
virtual ~PolyNode ()
Public Attributes
PolyNodes Childs
Path Contour
PolyNode * Parent
Friends
class Clipper
class ClipperOffset
Constructor & Destructor Documentation
PolyNode()
ClipperLib::PolyNode::PolyNode ()
~PolyNode()
virtual ClipperLib::PolyNode::~PolyNode () virtual
Member Function Documentation
ChildCount()
int ClipperLib::PolyNode::ChildCount () const
References Childs.
Referenced by ClipperLib::ClipperOffset::AddPath(), ClipperLib::AddPolyNodeToPaths(), ClipperLib::ClipperOffset::Clear(), ClipperLib::ClipperOffset::Execute(), and ClipperLib::OpenPathsFromPolyTree().
GetNext()
PolyNode * ClipperLib::PolyNode::GetNext () const
References Childs.
IsHole()
bool ClipperLib::PolyNode::IsHole () const
References Parent.
IsOpen()
bool ClipperLib::PolyNode::IsOpen () const
Referenced by ClipperLib::AddPolyNodeToPaths().
Friends And Related Function Documentation
Clipper
friend class Clipper friend
ClipperOffset
friend class ClipperOffset friend
Member Data Documentation
Childs
PolyNodes ClipperLib::PolyNode::Childs
Referenced by ClipperLib::ClipperOffset::AddPath(), ClipperLib::AddPolyNodeToPaths(), ChildCount(), ClipperLib::PolyTree::Clear(), ClipperLib::ClipperOffset::Clear(), ClipperLib::ClipperOffset::Execute(), ClipperLib::PolyTree::GetFirst(), GetNext(), and ClipperLib::OpenPathsFromPolyTree().
Contour
Path ClipperLib::PolyNode::Contour
Referenced by ClipperLib::ClipperOffset::AddPath(), and ClipperLib::AddPolyNodeToPaths().
Parent
PolyNode* ClipperLib::PolyNode::Parent
Referenced by IsHole().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Path/libarea/clipper.hpp
Sources/FreeCAD/src/Mod/Path/libarea/clipper.cpp