FreeCAD: TechDrawGui::Ui_TaskCosVertex Class Reference
TechDrawGui::Ui_TaskCosVertex Class Reference
#include <ui_TaskCosVertex.h>
Public Member Functions
void retranslateUi (QWidget *TechDrawGui__TaskCosVertex)
void setupUi (QWidget *TechDrawGui__TaskCosVertex)
Public Attributes
Gui::QuantitySpinBox * dsbX
Gui::QuantitySpinBox * dsbY
QGridLayout * gridLayout
QGridLayout * gridLayout_2
QGroupBox * groupBox
QHBoxLayout * horizontalLayout
QSpacerItem * horizontalSpacer
QSpacerItem * horizontalSpacer_2
QSpacerItem * horizontalSpacer_3
QLabel * label_2
QLabel * label_3
QLabel * label_4
QLineEdit * leBaseView
QFrame * line
QPushButton * pbTracker
QVBoxLayout * verticalLayout
QVBoxLayout * verticalLayout_2
Member Function Documentation
retranslateUi()
void TechDrawGui::Ui_TaskCosVertex::retranslateUi (QWidget * TechDrawGui__TaskCosVertex)
References groupBox, label_2, label_3, label_4, pbTracker, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void TechDrawGui::Ui_TaskCosVertex::setupUi (QWidget * TechDrawGui__TaskCosVertex)
References dsbX, dsbY, gridLayout, gridLayout_2, groupBox, horizontalLayout, horizontalSpacer, horizontalSpacer_2, horizontalSpacer_3, label_2, label_3, label_4, leBaseView, line, pbTracker, retranslateUi(), Gui::QuantitySpinBox::setMaximum(), Gui::QuantitySpinBox::setMinimum(), verticalLayout, and verticalLayout_2.
Member Data Documentation
dsbX
Gui::QuantitySpinBox* TechDrawGui::Ui_TaskCosVertex::dsbX
Referenced by setupUi().
dsbY
Gui::QuantitySpinBox* TechDrawGui::Ui_TaskCosVertex::dsbY
Referenced by setupUi().
gridLayout
QGridLayout* TechDrawGui::Ui_TaskCosVertex::gridLayout
Referenced by setupUi().
gridLayout_2
QGridLayout* TechDrawGui::Ui_TaskCosVertex::gridLayout_2
Referenced by setupUi().
groupBox
QGroupBox* TechDrawGui::Ui_TaskCosVertex::groupBox
Referenced by retranslateUi(), and setupUi().
horizontalLayout
QHBoxLayout* TechDrawGui::Ui_TaskCosVertex::horizontalLayout
Referenced by setupUi().
horizontalSpacer
QSpacerItem* TechDrawGui::Ui_TaskCosVertex::horizontalSpacer
Referenced by setupUi().
horizontalSpacer_2
QSpacerItem* TechDrawGui::Ui_TaskCosVertex::horizontalSpacer_2
Referenced by setupUi().
horizontalSpacer_3
QSpacerItem* TechDrawGui::Ui_TaskCosVertex::horizontalSpacer_3
Referenced by setupUi().
label_2
QLabel* TechDrawGui::Ui_TaskCosVertex::label_2
Referenced by retranslateUi(), and setupUi().
label_3
QLabel* TechDrawGui::Ui_TaskCosVertex::label_3
Referenced by retranslateUi(), and setupUi().
label_4
QLabel* TechDrawGui::Ui_TaskCosVertex::label_4
Referenced by retranslateUi(), and setupUi().
leBaseView
QLineEdit* TechDrawGui::Ui_TaskCosVertex::leBaseView
Referenced by setupUi().
line
QFrame* TechDrawGui::Ui_TaskCosVertex::line
Referenced by Plot.Line::getp(), Plot.Line::setp(), setupUi(), draftguitools.gui_trackers.wireTracker::update(), and draftviewproviders.view_label.ViewProviderLabel::updateData().
pbTracker
QPushButton* TechDrawGui::Ui_TaskCosVertex::pbTracker
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* TechDrawGui::Ui_TaskCosVertex::verticalLayout
Referenced by setupUi().
verticalLayout_2
QVBoxLayout* TechDrawGui::Ui_TaskCosVertex::verticalLayout_2
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/TechDraw/Gui/ui_TaskCosVertex.h