FreeCAD: PartGui::DimensionControl Class Reference
PartGui::DimensionControl Class Reference
#include <TaskDimension.h>
Public Slots
void clearAllSlot (bool)
void toggle3dSlot (bool)
void toggleDeltaSlot (bool)
Public Member Functions
DimensionControl (QWidget *parent)
Public Attributes
QPushButton * resetButton
Detailed Description
widget for buttons controlling the display of dimensions
Constructor & Destructor Documentation
DimensionControl()
PartGui::DimensionControl::DimensionControl (QWidget * parent) explicit
References Gui::BitmapFactory(), clearAllSlot(), draftgeoutils.intersections::connect(), resetButton, toggle3dSlot(), and toggleDeltaSlot().
Member Function Documentation
clearAllSlot
void PartGui::DimensionControl::clearAllSlot (bool) slot
References PartGui::eraseAllDimensions().
Referenced by DimensionControl().
toggle3dSlot
void PartGui::DimensionControl::toggle3dSlot (bool) slot
References PartGui::toggle3d().
Referenced by DimensionControl().
toggleDeltaSlot
void PartGui::DimensionControl::toggleDeltaSlot (bool) slot
References PartGui::toggleDelta().
Referenced by DimensionControl().
Member Data Documentation
resetButton
QPushButton* PartGui::DimensionControl::resetButton
Referenced by DimensionControl().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/Gui/TaskDimension.h
Sources/FreeCAD/src/Mod/Part/Gui/TaskDimension.cpp