FreeCAD: Path::ToolPy Class Reference
Path::ToolPy Class Reference
The python export class for Tool.
#include <ToolPy.h>
Public Types
typedef Tool * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
ToolPy (Tool *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of ToolPy.
static PyMethodDef Methods []
Methods structure of ToolPy.
static PyTypeObject Type
Type structure of ToolPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~ToolPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * getToolTypes (PyObject *args)
implementer for the getToolTypes() method
PyObject * getToolMaterials (PyObject *args)
implementer for the getToolMaterials() method
PyObject * setFromTemplate (PyObject *args)
implementer for the setFromTemplate() method
PyObject * templateAttrs (PyObject *args)
implementer for the templateAttrs() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_getToolTypes (PyObject *self, PyObject *args)
callback for the getToolTypes() method
static PyObject * staticCallback_getToolMaterials (PyObject *self, PyObject *args)
callback for the getToolMaterials() method
static PyObject * staticCallback_setFromTemplate (PyObject *self, PyObject *args)
callback for the setFromTemplate() method
static PyObject * staticCallback_templateAttrs (PyObject *self, PyObject *args)
callback for the templateAttrs() method
callbacks and implementers for the python object attributes
Py::String getName (void) const
getter for the Name attribute
void setName (Py::String arg)
setter for the Name attribute
Py::String getToolType (void) const
getter for the ToolType attribute
void setToolType (Py::String arg)
setter for the ToolType attribute
Py::String getMaterial (void) const
getter for the Material attribute
void setMaterial (Py::String arg)
setter for the Material attribute
Py::Float getDiameter (void) const
getter for the Diameter attribute
void setDiameter (Py::Float arg)
setter for the Diameter attribute
Py::Float getLengthOffset (void) const
getter for the LengthOffset attribute
void setLengthOffset (Py::Float arg)
setter for the LengthOffset attribute
Py::Float getFlatRadius (void) const
getter for the FlatRadius attribute
void setFlatRadius (Py::Float arg)
setter for the FlatRadius attribute
Py::Float getCornerRadius (void) const
getter for the CornerRadius attribute
void setCornerRadius (Py::Float arg)
setter for the CornerRadius attribute
Py::Float getCuttingEdgeAngle (void) const
getter for the CuttingEdgeAngle attribute
void setCuttingEdgeAngle (Py::Float arg)
setter for the CuttingEdgeAngle attribute
Py::Float getCuttingEdgeHeight (void) const
getter for the CuttingEdgeHeight attribute
void setCuttingEdgeHeight (Py::Float arg)
setter for the CuttingEdgeHeight attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Tool * getToolPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getName (PyObject *self, void *closure)
getter callback for the Name attribute
static int staticCallback_setName (PyObject *self, PyObject *value, void *closure)
setter callback for the Name attribute
static PyObject * staticCallback_getToolType (PyObject *self, void *closure)
getter callback for the ToolType attribute
static int staticCallback_setToolType (PyObject *self, PyObject *value, void *closure)
setter callback for the ToolType attribute
static PyObject * staticCallback_getMaterial (PyObject *self, void *closure)
getter callback for the Material attribute
static int staticCallback_setMaterial (PyObject *self, PyObject *value, void *closure)
setter callback for the Material attribute
static PyObject * staticCallback_getDiameter (PyObject *self, void *closure)
getter callback for the Diameter attribute
static int staticCallback_setDiameter (PyObject *self, PyObject *value, void *closure)
setter callback for the Diameter attribute
static PyObject * staticCallback_getLengthOffset (PyObject *self, void *closure)
getter callback for the LengthOffset attribute
static int staticCallback_setLengthOffset (PyObject *self, PyObject *value, void *closure)
setter callback for the LengthOffset attribute
static PyObject * staticCallback_getFlatRadius (PyObject *self, void *closure)
getter callback for the FlatRadius attribute
static int staticCallback_setFlatRadius (PyObject *self, PyObject *value, void *closure)
setter callback for the FlatRadius attribute
static PyObject * staticCallback_getCornerRadius (PyObject *self, void *closure)
getter callback for the CornerRadius attribute
static int staticCallback_setCornerRadius (PyObject *self, PyObject *value, void *closure)
setter callback for the CornerRadius attribute
static PyObject * staticCallback_getCuttingEdgeAngle (PyObject *self, void *closure)
getter callback for the CuttingEdgeAngle attribute
static int staticCallback_setCuttingEdgeAngle (PyObject *self, PyObject *value, void *closure)
setter callback for the CuttingEdgeAngle attribute
static PyObject * staticCallback_getCuttingEdgeHeight (PyObject *self, void *closure)
getter callback for the CuttingEdgeHeight attribute
static int staticCallback_setCuttingEdgeHeight (PyObject *self, PyObject *value, void *closure)
setter callback for the CuttingEdgeHeight attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Tool.
Member Typedef Documentation
PointerType
typedef Tool* Path::ToolPy::PointerType
Constructor & Destructor Documentation
~ToolPy()
ToolPy::~ToolPy () protected
ToolPy()
ToolPy::ToolPy (Tool * pcObject, PyTypeObject * T = &Type)
Referenced by copy(), and PyMake().
Member Function Documentation
copy()
PyObject * ToolPy::copy (PyObject * args)
implementer for the copy() method
References getToolPtr(), and ToolPy().
Referenced by staticCallback_copy().
getCornerRadius()
Py::Float ToolPy::getCornerRadius (void) const
getter for the CornerRadius attribute
References getToolPtr().
Referenced by staticCallback_getCornerRadius().
getCustomAttributes()
PyObject * ToolPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getCuttingEdgeAngle()
Py::Float ToolPy::getCuttingEdgeAngle (void) const
getter for the CuttingEdgeAngle attribute
References getToolPtr().
Referenced by staticCallback_getCuttingEdgeAngle().
getCuttingEdgeHeight()
Py::Float ToolPy::getCuttingEdgeHeight (void) const
getter for the CuttingEdgeHeight attribute
References getToolPtr().
Referenced by staticCallback_getCuttingEdgeHeight().
getDiameter()
Py::Float ToolPy::getDiameter (void) const
getter for the Diameter attribute
References getToolPtr().
Referenced by staticCallback_getDiameter().
getFlatRadius()
Py::Float ToolPy::getFlatRadius (void) const
getter for the FlatRadius attribute
References getToolPtr().
Referenced by staticCallback_getFlatRadius().
getLengthOffset()
Py::Float ToolPy::getLengthOffset (void) const
getter for the LengthOffset attribute
References getToolPtr().
Referenced by staticCallback_getLengthOffset().
getMaterial()
Py::String ToolPy::getMaterial (void) const
getter for the Material attribute
References getToolPtr(), and Path::Tool::MaterialName().
Referenced by staticCallback_getMaterial().
getName()
Py::String ToolPy::getName (void) const
getter for the Name attribute
References getToolPtr().
Referenced by staticCallback_getName().
getToolMaterials()
PyObject * ToolPy::getToolMaterials (PyObject * args)
implementer for the getToolMaterials() method
References Path::Tool::ToolMaterials().
Referenced by staticCallback_getToolMaterials().
getToolPtr()
Tool * ToolPy::getToolPtr (void) const
getter for the object handled by this class
Referenced by copy(), getCornerRadius(), getCuttingEdgeAngle(), getCuttingEdgeHeight(), getDiameter(), getFlatRadius(), getLengthOffset(), getMaterial(), getName(), getToolType(), PyInit(), representation(), setCornerRadius(), setCuttingEdgeAngle(), setCuttingEdgeHeight(), setDiameter(), setFlatRadius(), setFromTemplate(), setLengthOffset(), setMaterial(), setName(), Path::PropertyTool::setPyObject(), setToolType(), and templateAttrs().
getToolType()
Py::String ToolPy::getToolType (void) const
getter for the ToolType attribute
References getToolPtr(), Type, and Path::Tool::TypeName().
Referenced by staticCallback_getToolType().
getToolTypes()
PyObject * ToolPy::getToolTypes (PyObject * args)
implementer for the getToolTypes() method
References Path::Tool::ToolTypes().
Referenced by staticCallback_getToolTypes().
GetType()
virtual PyTypeObject* Path::ToolPy::GetType (void) virtual
Reimplemented from Base::PersistencePy.
PyInit()
int ToolPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PersistencePy.
References Path::Tool::CornerRadius, Path::Tool::CuttingEdgeAngle, Path::Tool::CuttingEdgeHeight, Path::Tool::Diameter, Path::Tool::FlatRadius, Path::Tool::getToolMaterial(), getToolPtr(), Path::Tool::getToolType(), Path::Tool::LengthOffset, Path::Tool::Material, Path::Tool::Name, and Path::Tool::Type.
Referenced by setFromTemplate().
PyMake()
PyObject * ToolPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References ToolPy().
representation()
std::string ToolPy::representation (void) const
References getToolPtr(), and Path::Tool::Name.
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCornerRadius()
void ToolPy::setCornerRadius (Py::Float arg)
setter for the CornerRadius attribute
References Path::Tool::CornerRadius, and getToolPtr().
Referenced by staticCallback_setCornerRadius().
setCustomAttributes()
int ToolPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setCuttingEdgeAngle()
void ToolPy::setCuttingEdgeAngle (Py::Float arg)
setter for the CuttingEdgeAngle attribute
References Path::Tool::CuttingEdgeAngle, and getToolPtr().
Referenced by staticCallback_setCuttingEdgeAngle().
setCuttingEdgeHeight()
void ToolPy::setCuttingEdgeHeight (Py::Float arg)
setter for the CuttingEdgeHeight attribute
References Path::Tool::CuttingEdgeHeight, and getToolPtr().
Referenced by staticCallback_setCuttingEdgeHeight().
setDiameter()
void ToolPy::setDiameter (Py::Float arg)
setter for the Diameter attribute
References Path::Tool::Diameter, and getToolPtr().
Referenced by staticCallback_setDiameter().
setFlatRadius()
void ToolPy::setFlatRadius (Py::Float arg)
setter for the FlatRadius attribute
References Path::Tool::FlatRadius, and getToolPtr().
Referenced by staticCallback_setFlatRadius().
setFromTemplate()
PyObject * ToolPy::setFromTemplate (PyObject * args)
implementer for the setFromTemplate() method
References getToolPtr(), PyInit(), and Path::Tool::Restore().
Referenced by Path::TooltablePy::setTools(), and staticCallback_setFromTemplate().
setLengthOffset()
void ToolPy::setLengthOffset (Py::Float arg)
setter for the LengthOffset attribute
References getToolPtr(), and Path::Tool::LengthOffset.
Referenced by staticCallback_setLengthOffset().
setMaterial()
void ToolPy::setMaterial (Py::String arg)
setter for the Material attribute
References Path::Tool::getToolMaterial(), getToolPtr(), and Path::Tool::Material.
Referenced by staticCallback_setMaterial().
setName()
void ToolPy::setName (Py::String arg)
setter for the Name attribute
References getToolPtr(), and Path::Tool::Name.
Referenced by staticCallback_setName().
setToolType()
void ToolPy::setToolType (Py::String arg)
setter for the ToolType attribute
References getToolPtr(), Path::Tool::getToolType(), and Path::Tool::Type.
Referenced by staticCallback_setToolType().
staticCallback_copy()
PyObject * ToolPy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copy(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getCornerRadius()
PyObject * ToolPy::staticCallback_getCornerRadius (PyObject * self, void * closure) static
getter callback for the CornerRadius attribute
References Base::BaseExceptionFreeCADError, getCornerRadius(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCuttingEdgeAngle()
PyObject * ToolPy::staticCallback_getCuttingEdgeAngle (PyObject * self, void * closure) static
getter callback for the CuttingEdgeAngle attribute
References Base::BaseExceptionFreeCADError, getCuttingEdgeAngle(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCuttingEdgeHeight()
PyObject * ToolPy::staticCallback_getCuttingEdgeHeight (PyObject * self, void * closure) static
getter callback for the CuttingEdgeHeight attribute
References Base::BaseExceptionFreeCADError, getCuttingEdgeHeight(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getDiameter()
PyObject * ToolPy::staticCallback_getDiameter (PyObject * self, void * closure) static
getter callback for the Diameter attribute
References Base::BaseExceptionFreeCADError, getDiameter(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFlatRadius()
PyObject * ToolPy::staticCallback_getFlatRadius (PyObject * self, void * closure) static
getter callback for the FlatRadius attribute
References Base::BaseExceptionFreeCADError, getFlatRadius(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getLengthOffset()
PyObject * ToolPy::staticCallback_getLengthOffset (PyObject * self, void * closure) static
getter callback for the LengthOffset attribute
References Base::BaseExceptionFreeCADError, getLengthOffset(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMaterial()
PyObject * ToolPy::staticCallback_getMaterial (PyObject * self, void * closure) static
getter callback for the Material attribute
References Base::BaseExceptionFreeCADError, getMaterial(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getName()
PyObject * ToolPy::staticCallback_getName (PyObject * self, void * closure) static
getter callback for the Name attribute
References Base::BaseExceptionFreeCADError, getName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getToolMaterials()
PyObject * ToolPy::staticCallback_getToolMaterials (PyObject * self, PyObject * args) static
callback for the getToolMaterials() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getToolMaterials(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getToolType()
PyObject * ToolPy::staticCallback_getToolType (PyObject * self, void * closure) static
getter callback for the ToolType attribute
References Base::BaseExceptionFreeCADError, getToolType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getToolTypes()
PyObject * ToolPy::staticCallback_getToolTypes (PyObject * self, PyObject * args) static
callback for the getToolTypes() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getToolTypes(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_setCornerRadius()
int ToolPy::staticCallback_setCornerRadius (PyObject * self, PyObject * value, void * closure) static
setter callback for the CornerRadius attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setCornerRadius().
staticCallback_setCuttingEdgeAngle()
int ToolPy::staticCallback_setCuttingEdgeAngle (PyObject * self, PyObject * value, void * closure) static
setter callback for the CuttingEdgeAngle attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setCuttingEdgeAngle().
staticCallback_setCuttingEdgeHeight()
int ToolPy::staticCallback_setCuttingEdgeHeight (PyObject * self, PyObject * value, void * closure) static
setter callback for the CuttingEdgeHeight attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setCuttingEdgeHeight().
staticCallback_setDiameter()
int ToolPy::staticCallback_setDiameter (PyObject * self, PyObject * value, void * closure) static
setter callback for the Diameter attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setDiameter().
staticCallback_setFlatRadius()
int ToolPy::staticCallback_setFlatRadius (PyObject * self, PyObject * value, void * closure) static
setter callback for the FlatRadius attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setFlatRadius().
staticCallback_setFromTemplate()
PyObject * ToolPy::staticCallback_setFromTemplate (PyObject * self, PyObject * args) static
callback for the setFromTemplate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setFromTemplate(), and Base::PyObjectBase::startNotify().
staticCallback_setLengthOffset()
int ToolPy::staticCallback_setLengthOffset (PyObject * self, PyObject * value, void * closure) static
setter callback for the LengthOffset attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setLengthOffset().
staticCallback_setMaterial()
int ToolPy::staticCallback_setMaterial (PyObject * self, PyObject * value, void * closure) static
setter callback for the Material attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setMaterial().
staticCallback_setName()
int ToolPy::staticCallback_setName (PyObject * self, PyObject * value, void * closure) static
setter callback for the Name attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setName().
staticCallback_setToolType()
int ToolPy::staticCallback_setToolType (PyObject * self, PyObject * value, void * closure) static
setter callback for the ToolType attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setToolType().
staticCallback_templateAttrs()
PyObject * ToolPy::staticCallback_templateAttrs (PyObject * self, PyObject * args) static
callback for the templateAttrs() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and templateAttrs().
templateAttrs()
PyObject * ToolPy::templateAttrs (PyObject * args)
implementer for the templateAttrs() method
References getToolPtr(), Path::Tool::MaterialName(), Type, and Path::Tool::TypeName().
Referenced by staticCallback_templateAttrs(), and Path::TooltablePy::templateAttrs().
Member Data Documentation
GetterSetter
PyGetSetDef ToolPy::GetterSetter static
Attribute structure of ToolPy.
Methods
PyMethodDef ToolPy::Methods static
Initial value:
= {
    {"copy",
        reinterpret_cast<PyCFunction>( staticCallback_copy ),
        METH_VARARGS,
        "returns a copy of this tool"
    },
    {"getToolTypes",
        reinterpret_cast<PyCFunction>( staticCallback_getToolTypes ),
        METH_VARARGS,
        "returns all available tool types"
    },
    {"getToolMaterials",
        reinterpret_cast<PyCFunction>( staticCallback_getToolMaterials ),
        METH_VARARGS,
        "returns all available tool materials"
    },
    {"setFromTemplate",
        reinterpret_cast<PyCFunction>( staticCallback_setFromTemplate ),
        METH_VARARGS,
        "setFromTemplate(xmlString|dictionary) ... fills receiver with values from the template string or dictionary"
    },
    {"templateAttrs",
        reinterpret_cast<PyCFunction>( staticCallback_templateAttrs ),
        METH_VARARGS,
        "templateAttrs() ... returns a dictionary with all attributes"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of ToolPy.
Type
PyTypeObject ToolPy::Type static
Type structure of ToolPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), Path::TooltablePy::addTools(), ArchSite.Compass::buildCoordinates(), getToolType(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), Path::TooltablePy::PyInit(), Path::PropertyTool::setPyObject(), Path::TooltablePy::setTool(), Path::TooltablePy::setTools(), and templateAttrs().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/ToolPy.h
Sources/FreeCAD/src/Mod/Path/App/ToolPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/ToolPy.cpp