FreeCAD: Gui::Dialog::DlgDisplayPropertiesImp Class Reference
Gui::Dialog::DlgDisplayPropertiesImp Class Reference
The DlgDisplayPropertiesImp class implements a dialog containing all available document templates to create a new document.
#include <DlgDisplayPropertiesImp.h>
Classes
class Private
Public Member Functions
DlgDisplayPropertiesImp (bool floating, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
Constructs a DlgDisplayPropertiesImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
void OnChange (Gui::SelectionSingleton::SubjectType &rCaller, Gui::SelectionSingleton::MessageType Reason)
Observer message from the Selection.
void reject ()
Destroys the dock window this object is embedded into without destroying itself.
void showDefaultButtons (bool)
~DlgDisplayPropertiesImp ()
Destroys the object and frees any allocated resources.
Protected Member Functions
void changeEvent (QEvent *e)
Detailed Description
The DlgDisplayPropertiesImp class implements a dialog containing all available document templates to create a new document.
Author
Jürgen Riegel
Constructor & Destructor Documentation
DlgDisplayPropertiesImp()
DlgDisplayPropertiesImp::DlgDisplayPropertiesImp (bool floating, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Constructs a DlgDisplayPropertiesImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
References Gui::DockWindowManager::addDockWindow(), Base::Subject< _MessageType >::Attach(), draftgeoutils.faces::bind(), Gui::Application::Instance, Gui::DockWindowManager::instance(), Gui::Selection(), and Gui::Application::signalChangedObject.
~DlgDisplayPropertiesImp()
DlgDisplayPropertiesImp::~DlgDisplayPropertiesImp ()
Destroys the object and frees any allocated resources.
References Base::Subject< _MessageType >::Detach(), and Gui::Selection().
Member Function Documentation
changeEvent()
void DlgDisplayPropertiesImp::changeEvent (QEvent * e) protected
OnChange()
void Gui::Dialog::DlgDisplayPropertiesImp::OnChange (Gui::SelectionSingleton::SubjectType & rCaller, Gui::SelectionSingleton::MessageType Reason)
Observer message from the Selection.
reject()
void DlgDisplayPropertiesImp::reject ()
Destroys the dock window this object is embedded into without destroying itself.
References Gui::DockWindowManager::instance(), and Gui::DockWindowManager::removeDockWindow().
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), Gui::Dialog::TaskDisplayProperties::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
showDefaultButtons()
void DlgDisplayPropertiesImp::showDefaultButtons (bool ok)
Referenced by Gui::Dialog::TaskDisplayProperties::TaskDisplayProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgDisplayPropertiesImp.h
Sources/FreeCAD/src/Gui/DlgDisplayPropertiesImp.cpp