FreeCAD: DriverMED_W_SMESHDS_Mesh Class Reference
DriverMED_W_SMESHDS_Mesh Class Reference
#include <DriverMED_W_SMESHDS_Mesh.h>
Public Member Functions
void AddAllSubMeshes ()
void AddGroup (SMESHDS_GroupBase *theGroup)
void AddGroupOf0DElems ()
void AddGroupOfBalls ()
void AddGroupOfEdges ()
void AddGroupOfFaces ()
void AddGroupOfNodes ()
void AddGroupOfVolumes ()
void AddODOnVertices (bool toAdd)
void AddSubMesh (SMESHDS_SubMesh *theSubMesh, int theID)
DriverMED_W_SMESHDS_Mesh ()
virtual Status Perform ()
void SetAutoDimension (bool toFindOutDimension)
virtual void SetFile (const std::string &theFileName)
void SetFile (const std::string &theFileName, MED::EVersion theId)
Public Member Functions inherited from Driver_SMESHDS_Mesh
Driver_SMESHDS_Mesh ()
void SetMesh (SMESHDS_Mesh *theMesh)
Public Member Functions inherited from Driver_Mesh
Driver_Mesh ()
virtual SMESH_ComputeErrorPtr GetError ()
Return a structure containing description of errors.
virtual std::string GetMeshName () const
void SetMeshId (int theMeshId)
virtual void SetMeshName (const std::string &theMeshName)
virtual void SetOption (const std::string &optionName, const std::string &optionValue)
virtual ~Driver_Mesh ()
Static Public Member Functions
static bool getNodesOfMissing0DOnVert (SMESHDS_Mesh *mesh, std::vector< const SMDS_MeshElement * > &nodes)
Returns nodes on VERTEXes where 0D elements are absent.
static std::string GetVersionString (const MED::EVersion theVersion, int theNbDigits=2)
Additional Inherited Members
Public Types inherited from Driver_Mesh
enum Status {
DRS_OK, DRS_EMPTY, DRS_WARN_RENUMBER, DRS_WARN_SKIP_ELEM,
DRS_WARN_DESCENDING, DRS_FAIL
}
Protected Member Functions inherited from Driver_Mesh
Status addMessage (const std::string &msg, const bool isFatal=false)
Stores an error message.
Protected Attributes inherited from Driver_SMESHDS_Mesh
SMESHDS_Mesh * myMesh
Protected Attributes inherited from Driver_Mesh
std::vector< std::string > myErrorMessages
std::string myFile
int myMeshId
std::string myMeshName
Status myStatus
Constructor & Destructor Documentation
DriverMED_W_SMESHDS_Mesh()
DriverMED_W_SMESHDS_Mesh::DriverMED_W_SMESHDS_Mesh ()
References MED::eV2_2.
Member Function Documentation
AddAllSubMeshes()
void DriverMED_W_SMESHDS_Mesh::AddAllSubMeshes ()
AddGroup()
void DriverMED_W_SMESHDS_Mesh::AddGroup (SMESHDS_GroupBase * theGroup)
functions to prepare adding one mesh
Referenced by SMESH_Mesh::ExportMED().
AddGroupOf0DElems()
void DriverMED_W_SMESHDS_Mesh::AddGroupOf0DElems ()
AddGroupOfBalls()
void DriverMED_W_SMESHDS_Mesh::AddGroupOfBalls ()
AddGroupOfEdges()
void DriverMED_W_SMESHDS_Mesh::AddGroupOfEdges ()
Referenced by SMESH_Mesh::ExportMED().
AddGroupOfFaces()
void DriverMED_W_SMESHDS_Mesh::AddGroupOfFaces ()
Referenced by SMESH_Mesh::ExportMED().
AddGroupOfNodes()
void DriverMED_W_SMESHDS_Mesh::AddGroupOfNodes ()
Referenced by SMESH_Mesh::ExportMED().
AddGroupOfVolumes()
void DriverMED_W_SMESHDS_Mesh::AddGroupOfVolumes ()
Referenced by SMESH_Mesh::ExportMED().
AddODOnVertices()
void DriverMED_W_SMESHDS_Mesh::AddODOnVertices (bool toAdd)
Referenced by SMESH_Mesh::ExportMED().
AddSubMesh()
void DriverMED_W_SMESHDS_Mesh::AddSubMesh (SMESHDS_SubMesh * theSubMesh, int theID)
getNodesOfMissing0DOnVert()
bool DriverMED_W_SMESHDS_Mesh::getNodesOfMissing0DOnVert (SMESHDS_Mesh * mesh, std::vector< const SMDS_MeshElement * > & nodes) static
Returns nodes on VERTEXes where 0D elements are absent.
References SMESHDS_Mesh::IndexToShape(), SMESHDS_Mesh::MaxShapeIndex(), and SMESHDS_Mesh::MeshElements().
Referenced by Perform(), and DriverMED_W_Field::Set().
GetVersionString()
string DriverMED_W_SMESHDS_Mesh::GetVersionString (const MED::EVersion theVersion, int theNbDigits = 2) static
Perform()
Driver_Mesh::Status DriverMED_W_SMESHDS_Mesh::Perform () virtual
add one mesh
Implements Driver_Mesh.
References MED::aXGetCoord, MED::aXYGetCoord, MED::aXYZGetCoord, MED::aXZGetCoord, MED::aYGetCoord, MED::aYZGetCoord, MED::aZGetCoord, MED::CrWrapper(), Driver_Mesh::DRS_FAIL, Driver_Mesh::DRS_OK, MED::eARETE, MED::eBALL, MED::eCART, MED::eFACE, MED::eFAUX, MED::eFULL_INTERLACE, MED::eHEXA20, MED::eHEXA27, MED::eHEXA8, SMDS_Mesh::elementEntityIterator(), SMDS_Mesh::elementGeomIterator(), SMDS_Mesh::elementsIterator(), MED::eMAILLE, MED::eNOD, MED::eNOEUD_ELEMENT, MED::eOCTA12, MED::ePENTA15, MED::ePENTA6, MED::ePOINT1, MED::ePOLYEDRE, MED::ePOLYGON2, MED::ePOLYGONE, MED::ePYRA13, MED::ePYRA5, MED::eQUAD4, MED::eQUAD8, MED::eQUAD9, MED::eSEG2, MED::eSEG3, MED::eSTRUCT_ELEMENT, MED::eTETRA10, MED::eTETRA4, MED::eTRIA3, MED::eTRIA6, MED::eTRIA7, MED::eVRAI, SMDS_MeshElement::GetID(), SMDS_Mesh::GetMeshInfo(), MED::GetNbNodes(), SMDS_MeshElement::GetNode(), getNodesOfMissing0DOnVert(), SMDS_Mesh::hasConstructionEdges(), SMDS_Mesh::hasConstructionFaces(), SMDS_MeshElement::IsPoly(), DriverMED_Family::MakeFamilies(), Driver_Mesh::myFile, Driver_SMESHDS_Mesh::myMesh, Driver_Mesh::myMeshId, Driver_Mesh::myMeshName, SMDS_Mesh::Nb0DElements(), SMDS_MeshInfo::Nb0DElements(), SMDS_Mesh::NbBalls(), SMDS_MeshInfo::NbBalls(), SMDS_MeshInfo::NbBiQuadQuadrangles(), SMDS_MeshInfo::NbBiQuadTriangles(), SMDS_Mesh::NbEdges(), SMDS_MeshInfo::NbEdges(), SMDS_VtkVolume::NbFaceNodes(), SMDS_Mesh::NbFaces(), SMDS_VtkVolume::NbFaces(), SMDS_MeshInfo::NbHexas(), SMDS_MeshInfo::NbHexPrisms(), SMDS_Mesh::NbNodes(), SMDS_MeshElement::NbNodes(), SMDS_VtkVolume::NbNodes(), SMDS_MeshInfo::NbPolygons(), SMDS_MeshInfo::NbPolyhedrons(), SMDS_MeshInfo::NbPrisms(), SMDS_MeshInfo::NbPyramids(), SMDS_MeshInfo::NbQuadrangles(), SMDS_MeshInfo::NbTetras(), SMDS_MeshInfo::NbTriangles(), SMDS_MeshInfo::NbTriQuadHexas(), SMDS_Mesh::NbVolumes(), SMDS_MeshElement::nodesIterator(), SMDS_Mesh::nodesIterator(), SMESHDS_Mesh::ShapeToMesh(), SMESHDS_Mesh::SubMeshes(), SMESHDS_Mesh::SubMeshIndices(), SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
Referenced by SMESH_Mesh::ExportMED().
SetAutoDimension()
void DriverMED_W_SMESHDS_Mesh::SetAutoDimension (bool toFindOutDimension)
Referenced by SMESH_Mesh::ExportMED().
SetFile() [1/2]
void DriverMED_W_SMESHDS_Mesh::SetFile (const std::string & theFileName) virtual
Reimplemented from Driver_Mesh.
References Driver_Mesh::SetFile().
Referenced by SMESH_Mesh::ExportMED().
SetFile() [2/2]
void DriverMED_W_SMESHDS_Mesh::SetFile (const std::string & theFileName, MED::EVersion theId)
References Driver_Mesh::SetFile().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/DriverMED_W_SMESHDS_Mesh.h
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/DriverMED_W_SMESHDS_Mesh.cpp