FreeCAD: MeshGui::SphereFitParameter Class Reference
MeshGui::SphereFitParameter Class Reference
Public Member Functions
virtual std::vector< float > getParameter (FitParameter::Points pts) const
SphereFitParameter ()
virtual ~SphereFitParameter ()
Public Member Functions inherited from MeshGui::FitParameter
virtual std::vector< float > getParameter (Points) const =0
virtual ~FitParameter ()
Constructor & Destructor Documentation
SphereFitParameter()
MeshGui::SphereFitParameter::SphereFitParameter ()
~SphereFitParameter()
virtual MeshGui::SphereFitParameter::~SphereFitParameter () virtual
Member Function Documentation
getParameter()
virtual std::vector< float > MeshGui::SphereFitParameter::getParameter (FitParameter::Points pts) const virtual
Implements MeshGui::FitParameter.
References MeshCore::Approximation::AddPoints(), MeshCore::SphereFit::Fit(), MeshCore::SphereFit::GetCenter(), MeshCore::SphereFit::GetRadius(), and MeshGui::FitParameter::Points::points.
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Mesh/Gui/SegmentationBestFit.cpp