FreeCAD: femexamples.equation_electrostatics_capacitance_two_balls Namespace Reference
femexamples.equation_electrostatics_capacitance_two_balls Namespace Reference
Functions
def get_explanation (header="")
def get_information ()
def setup (doc=None, solvertype="elmer")
Function Documentation
get_explanation()
def femexamples.equation_electrostatics_capacitance_two_balls.get_explanation (header = "")
Referenced by femexamples.equation_electrostatics_capacitance_two_balls.setup().
get_information()
def femexamples.equation_electrostatics_capacitance_two_balls.get_information ()
Referenced by femexamples.equation_electrostatics_capacitance_two_balls.setup().
setup()
def femexamples.equation_electrostatics_capacitance_two_balls.setup (doc = None, solvertype = "elmer")
References femexamples.equation_electrostatics_capacitance_two_balls.get_explanation(), femexamples.equation_electrostatics_capacitance_two_balls.get_information(), ObjectsFem.makeAnalysis(), ObjectsFem.makeConstantVacuumPermittivity(), ObjectsFem.makeConstraintElectrostaticPotential(), ObjectsFem.makeEquationElectrostatic(), ObjectsFem.makeMaterialFluid(), ObjectsFem.makeMeshGmsh(), ObjectsFem.makeMeshRegion(), and ObjectsFem.makeSolverElmer().