FreeCAD: Mod.Show.SceneDetails.Pickability Namespace Reference
Mod.Show.SceneDetails.Pickability Namespace Reference
Classes
class Pickability
Functions
def getPickStyle (viewprovider)
def getPickStyleNode (viewprovider, make_if_missing=True)
def setPickStyle (viewprovider, pickstyle)
Variables
int PS_BOUNDBOX = 1
int PS_REGULAR = 0
int PS_UNPICKABLE = 2
Function Documentation
getPickStyle()
def Mod.Show.SceneDetails.Pickability.getPickStyle (viewprovider)
References Mod.Show.SceneDetails.Pickability.getPickStyleNode().
Referenced by Mod.Show.SceneDetails.Pickability.Pickability.scene_value().
getPickStyleNode()
def Mod.Show.SceneDetails.Pickability.getPickStyleNode (viewprovider, make_if_missing = True)
Referenced by Mod.Show.SceneDetails.Pickability.getPickStyle(), and Mod.Show.SceneDetails.Pickability.setPickStyle().
setPickStyle()
def Mod.Show.SceneDetails.Pickability.setPickStyle (viewprovider, pickstyle)
References Mod.Show.SceneDetails.Pickability.getPickStyleNode().
Referenced by Mod.Show.SceneDetails.Pickability.Pickability.apply_data().
Variable Documentation
PS_BOUNDBOX
int Mod.Show.SceneDetails.Pickability.PS_BOUNDBOX = 1
PS_REGULAR
int Mod.Show.SceneDetails.Pickability.PS_REGULAR = 0
PS_UNPICKABLE
int Mod.Show.SceneDetails.Pickability.PS_UNPICKABLE = 2