FreeCAD: SketcherGui::SketcherRegularPolygonDialog Class Reference
SketcherGui::SketcherRegularPolygonDialog Class Reference
#include <SketcherRegularPolygonDialog.h>
Public Member Functions
void accept ()
SketcherRegularPolygonDialog (void)
~SketcherRegularPolygonDialog ()
Public Attributes
int sides
Protected Member Functions
void updateValues (void)
Constructor & Destructor Documentation
SketcherRegularPolygonDialog()
SketcherRegularPolygonDialog::SketcherRegularPolygonDialog (void)
References updateValues().
~SketcherRegularPolygonDialog()
SketcherRegularPolygonDialog::~SketcherRegularPolygonDialog ()
Member Function Documentation
accept()
void SketcherRegularPolygonDialog::accept (void)
References updateValues().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
updateValues()
void SketcherRegularPolygonDialog::updateValues (void) protected
References sides.
Referenced by accept(), and SketcherRegularPolygonDialog().
Member Data Documentation
sides
int SketcherGui::SketcherRegularPolygonDialog::sides
Referenced by updateValues().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/Gui/SketcherRegularPolygonDialog.h
FreeCAD/src/Mod/Sketcher/Gui/SketcherRegularPolygonDialog.cpp