FreeCAD: FaceQuadStruct::Side Struct Reference
FaceQuadStruct::Side Struct Reference
#include <StdMeshers_Quadrangle_2D.hxx>
Classes
struct Contact
Public Member Functions
void AddContact (int ip, Side *side, int iop)
Sets up a contact between this and another side.
const UVPtStruct & First () const
const vector< UVPtStruct > & GetUVPtStruct (bool isXConst=0, double constValue=0) const
bool IsForced (int nodeIndex) const
Checks if a node is enforced.
bool IsReversed () const
const UVPtStruct & Last () const
double Length (int from=-1, int to=-1) const
Returns side length.
int NbPoints () const
operator const StdMeshers_FaceSidePtr () const
operator StdMeshers_FaceSidePtr ()
Side & operator= (const Side &otherSide)
Side copying.
double Param (int nodeIndex) const
Returns a normalized parameter of a point indexed within a quadrangle.
bool Reverse (bool keepGrid)
Reverse the side.
Side (StdMeshers_FaceSidePtr theGrid=StdMeshers_FaceSidePtr())
Constructor of a side of quad.
int ToQuadIndex (int sideNodeIndex) const
Converts node index of this side to node index of a quad.
int ToSideIndex (int quadNodeIndex) const
Converts node index of a quad to node index of this side.
gp_XY Value2d (double x) const
Returns UV by a parameter normalized within a quadrangle.
Public Attributes
std::vector< Contact > contacts
int di
std::set< int > forced_nodes
int from
StdMeshers_FaceSidePtr grid
int nbNodeOut
int to
Constructor & Destructor Documentation
Side()
FaceQuadStruct::Side::Side (StdMeshers_FaceSidePtr theGrid = StdMeshers_FaceSidePtr())
Constructor of a side of quad.
Member Function Documentation
AddContact()
void FaceQuadStruct::Side::AddContact (int ip, Side * side, int iop)
Sets up a contact between this and another side.
References FaceQuadStruct::Side::Contact::point, and FaceQuadStruct::side.
Referenced by StdMeshers_Quadrangle_2D::splitQuad().
First()
const UVPtStruct & FaceQuadStruct::Side::First () const
References from, and GetUVPtStruct().
Referenced by StdMeshers_Quadrangle_2D::setNormalizedGrid().
GetUVPtStruct()
const vector< UVPtStruct > & FaceQuadStruct::Side::GetUVPtStruct (bool isXConst = 0, double constValue = 0) const
References grid, nbNodeOut, and NbPoints().
Referenced by StdMeshers_Quadrangle_2D::addEnforcedNodes(), First(), Last(), StdMeshers_Quadrangle_2D::setNormalizedGrid(), and StdMeshers_Quadrangle_2D::updateSideUV().
IsForced()
bool FaceQuadStruct::Side::IsForced (int nodeIndex) const
Checks if a node is enforced.
Parameters
[in] nodeIndex - an index of a node in a size
Returns
bool - true if the node is forced
Referenced by StdMeshers_Quadrangle_2D::addEnforcedNodes().
IsReversed()
bool FaceQuadStruct::Side::IsReversed () const
References from, nbNodeOut, and to.
Referenced by Last().
Last()
const UVPtStruct & FaceQuadStruct::Side::Last () const
References GetUVPtStruct(), IsReversed(), nbNodeOut, and to.
Referenced by StdMeshers_Quadrangle_2D::setNormalizedGrid().
Length()
double FaceQuadStruct::Side::Length (int from = -1, int to = -1) const
Returns side length.
Referenced by ArchStructure.CommandStructuralSystem::Activated(), ArchPanel.CommandPanel::getPoint(), ArchPanel.CommandPanel::setLength(), and ArchPanel.CommandPanel::update().
NbPoints()
int FaceQuadStruct::Side::NbPoints () const
References from, and to.
Referenced by GetUVPtStruct(), StdMeshers_Quadrangle_2D::setNormalizedGrid(), and StdMeshers_Quadrangle_2D::updateSideUV().
operator const StdMeshers_FaceSidePtr()
FaceQuadStruct::Side::operator const StdMeshers_FaceSidePtr () const
References grid.
operator StdMeshers_FaceSidePtr()
FaceQuadStruct::Side::operator StdMeshers_FaceSidePtr ()
References grid.
operator=()
FaceQuadStruct::Side & FaceQuadStruct::Side::operator= (const Side & otherSide)
Side copying.
References contacts, di, forced_nodes, from, grid, nbNodeOut, and to.
Param()
double FaceQuadStruct::Side::Param (int nodeIndex) const
Returns a normalized parameter of a point indexed within a quadrangle.
Reverse()
bool FaceQuadStruct::Side::Reverse (bool keepGrid)
Reverse the side.
ToQuadIndex()
int FaceQuadStruct::Side::ToQuadIndex (int sideNodeIndex) const
Converts node index of this side to node index of a quad.
ToSideIndex()
int FaceQuadStruct::Side::ToSideIndex (int quadNodeIndex) const
Converts node index of a quad to node index of this side.
Referenced by StdMeshers_Quadrangle_2D::addEnforcedNodes(), and StdMeshers_Quadrangle_2D::splitQuad().
Value2d()
gp_XY FaceQuadStruct::Side::Value2d (double x) const
Returns UV by a parameter normalized within a quadrangle.
Member Data Documentation
contacts
std::vector<Contact> FaceQuadStruct::Side::contacts
Referenced by StdMeshers_Quadrangle_2D::addEnforcedNodes(), operator=(), and FaceQuadStruct::shift().
di
int FaceQuadStruct::Side::di
Referenced by operator=().
forced_nodes
std::set<int> FaceQuadStruct::Side::forced_nodes
Referenced by StdMeshers_Quadrangle_2D::addEnforcedNodes(), operator=(), and StdMeshers_Quadrangle_2D::updateSideUV().
from
int FaceQuadStruct::Side::from
Referenced by StdMeshers_Quadrangle_2D::addEnforcedNodes(), First(), IsReversed(), NbPoints(), and operator=().
grid
StdMeshers_FaceSidePtr FaceQuadStruct::Side::grid
Referenced by StdMeshers_Quadrangle_2D::addEnforcedNodes(), GetUVPtStruct(), Plot.Plot::isGrid(), draftguitools.gui_snapper.Snapper::off(), operator const StdMeshers_FaceSidePtr(), operator StdMeshers_FaceSidePtr(), operator=(), draftguitools.gui_snapper.Snapper::restack(), draftguitools.gui_snapper.Snapper::setGrid(), StdMeshers_Quadrangle_2D::setNormalizedGrid(), draftguitools.gui_snapper.Snapper::setTrackers(), draftguitools.gui_snapper.Snapper::snapToGrid(), and StdMeshers_Quadrangle_2D::updateSideUV().
nbNodeOut
int FaceQuadStruct::Side::nbNodeOut
Referenced by StdMeshers_Quadrangle_2D::addEnforcedNodes(), GetUVPtStruct(), IsReversed(), Last(), and operator=().
to
int FaceQuadStruct::Side::to
Referenced by StdMeshers_Quadrangle_2D::addEnforcedNodes(), IsReversed(), Last(), NbPoints(), and operator=().
The documentation for this struct was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_Quadrangle_2D.hxx
FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_Quadrangle_2D.cpp