FreeCAD: Gui::ActionSelector Class Reference
Gui::ActionSelector Class Reference
#include <Widgets.h>
Public Member Functions
ActionSelector (QWidget *parent=nullptr)
QString availableLabel () const
QTreeWidget * availableTreeWidget () const
QString selectedLabel () const
QTreeWidget * selectedTreeWidget () const
void setAvailableLabel (const QString &)
void setSelectedLabel (const QString &)
~ActionSelector ()
Constructor & Destructor Documentation
ActionSelector()
ActionSelector::ActionSelector (QWidget * parent = nullptr)
References Gui::BitmapFactory(), and draftgeoutils.intersections::connect().
~ActionSelector()
ActionSelector::~ActionSelector ()
Member Function Documentation
availableLabel()
QString ActionSelector::availableLabel () const
availableTreeWidget()
QTreeWidget * Gui::ActionSelector::availableTreeWidget () const
Referenced by PartGui::LoftWidget::LoftWidget(), and PartGui::SweepWidget::SweepWidget().
selectedLabel()
QString ActionSelector::selectedLabel () const
selectedTreeWidget()
QTreeWidget * Gui::ActionSelector::selectedTreeWidget () const
Referenced by PartGui::LoftWidget::accept(), PartGui::SweepWidget::accept(), PartGui::LoftWidget::LoftWidget(), and PartGui::SweepWidget::SweepWidget().
setAvailableLabel()
void ActionSelector::setAvailableLabel (const QString & label)
Referenced by PartGui::LoftWidget::LoftWidget(), and PartGui::SweepWidget::SweepWidget().
setSelectedLabel()
void ActionSelector::setSelectedLabel (const QString & label)
Referenced by PartGui::LoftWidget::LoftWidget(), and PartGui::SweepWidget::SweepWidget().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/Widgets.h
FreeCAD/src/Gui/Widgets.cpp