FreeCAD: Driver_Mesh Class Reference
Driver_Mesh Class Reference abstract
#include <Driver_Mesh.h>
Public Types
enum Status {
DRS_OK , DRS_EMPTY , DRS_WARN_RENUMBER , DRS_WARN_SKIP_ELEM ,
DRS_WARN_DESCENDING , DRS_FAIL
}
Public Member Functions
Driver_Mesh ()
virtual SMESH_ComputeErrorPtr GetError ()
Return a structure containing description of errors.
virtual std::string GetMeshName () const
virtual Status Perform ()=0
virtual void SetFile (const std::string &theFileName)
void SetMeshId (int theMeshId)
virtual void SetMeshName (const std::string &theMeshName)
virtual void SetOption (const std::string &optionName, const std::string &optionValue)
virtual ~Driver_Mesh ()
Protected Member Functions
Status addMessage (const std::string &msg, const bool isFatal=false)
Stores an error message.
Protected Attributes
std::vector< std::string > myErrorMessages
std::string myFile
int myMeshId
std::string myMeshName
Status myStatus
Member Enumeration Documentation
Status
enum Driver_Mesh::Status
Enumerator
DRS_OK
DRS_EMPTY
DRS_WARN_RENUMBER
DRS_WARN_SKIP_ELEM
DRS_WARN_DESCENDING
DRS_FAIL
Constructor & Destructor Documentation
Driver_Mesh()
Driver_Mesh::Driver_Mesh ()
~Driver_Mesh()
virtual Driver_Mesh::~Driver_Mesh () virtual
Member Function Documentation
addMessage()
Driver_Mesh::Status Driver_Mesh::addMessage (const std::string & msg, const bool isFatal = false) protected
Stores an error message.
We consider an error fatal if none mesh can be read
References DRS_FAIL, DRS_WARN_SKIP_ELEM, myErrorMessages, and myStatus.
Referenced by DriverGMF_Read::Perform(), DriverGMF_Write::Perform(), and DriverMED_W_Field::Perform().
GetError()
SMESH_ComputeErrorPtr Driver_Mesh::GetError () virtual
Return a structure containing description of errors.
References DRS_OK, myErrorMessages, myStatus, and SMESH_ComputeError::New().
Referenced by SMESH_Mesh::GMFToMesh().
GetMeshName()
std::string Driver_Mesh::GetMeshName () const virtual
References myMeshName.
Perform()
virtual Status Driver_Mesh::Perform () pure virtual
Implemented in DriverUNV_W_SMDS_Mesh, DriverUNV_R_SMDS_Mesh, DriverSTL_W_SMDS_Mesh, DriverSTL_R_SMDS_Mesh, DriverMED_W_SMESHDS_Mesh, DriverMED_W_Field, DriverMED_R_SMESHDS_Mesh, DriverGMF_Write, DriverGMF_Read, DriverDAT_W_SMDS_Mesh, and DriverDAT_R_SMDS_Mesh.
SetFile()
void Driver_Mesh::SetFile (const std::string & theFileName) virtual
Reimplemented in DriverMED_W_SMESHDS_Mesh.
References myFile.
Referenced by SMESH_Mesh::DATToMesh(), SMESH_Mesh::ExportDAT(), SMESH_Mesh::ExportGMF(), SMESH_Mesh::ExportSTL(), SMESH_Mesh::ExportUNV(), SMESH_Mesh::GMFToMesh(), SMESH_Mesh::MEDToMesh(), DriverMED_W_SMESHDS_Mesh::SetFile(), SMESH_Mesh::STLToMesh(), and SMESH_Mesh::UNVToMesh().
SetMeshId()
void Driver_Mesh::SetMeshId (int theMeshId)
References myMeshId.
Referenced by SMESH_Mesh::DATToMesh(), SMESH_Mesh::ExportDAT(), SMESH_Mesh::ExportMED(), SMESH_Mesh::ExportSTL(), SMESH_Mesh::ExportUNV(), SMESH_Mesh::MEDToMesh(), SMESH_Mesh::STLToMesh(), and SMESH_Mesh::UNVToMesh().
SetMeshName()
void Driver_Mesh::SetMeshName (const std::string & theMeshName) virtual
References myMeshName.
Referenced by SMESH_Mesh::ExportMED().
SetOption()
virtual void Driver_Mesh::SetOption (const std::string & optionName, const std::string & optionValue) virtual
Member Data Documentation
myErrorMessages
std::vector< std::string > Driver_Mesh::myErrorMessages protected
Referenced by addMessage(), and GetError().
myFile
std::string Driver_Mesh::myFile protected
Referenced by DriverGMF_Read::Perform(), DriverGMF_Write::Perform(), DriverMED_W_Field::Perform(), DriverMED_W_SMESHDS_Mesh::Perform(), DriverSTL_R_SMDS_Mesh::Perform(), and SetFile().
myMeshId
int Driver_Mesh::myMeshId protected
Referenced by DriverMED_W_Field::Perform(), DriverMED_W_SMESHDS_Mesh::Perform(), and SetMeshId().
myMeshName
std::string Driver_Mesh::myMeshName protected
Referenced by GetMeshName(), DriverMED_W_Field::Perform(), DriverMED_W_SMESHDS_Mesh::Perform(), and SetMeshName().
myStatus
Status Driver_Mesh::myStatus protected
Referenced by addMessage(), and GetError().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/Driver_Mesh.h
Sources/FreeCAD/src/3rdParty/salomesmesh/src/Driver/Driver_Mesh.cpp