FreeCAD: Gui::TaskView::TaskWatcherPython Class Reference
Gui::TaskView::TaskWatcherPython Class Reference
#include <TaskDialogPython.h>
Public Member Functions
bool shouldShow ()
is called wenn the document or the Selection changes.
TaskWatcherPython (const Py::Object &)
~TaskWatcherPython ()
Public Member Functions inherited from Gui::TaskView::TaskWatcher
std::vector< QWidget * > & getWatcherContent (void)
virtual bool shouldShow (void)
is called wenn the document or the Selection changes.
TaskWatcher (const char *Filter)
virtual ~TaskWatcher ()
Public Member Functions inherited from Gui::SelectionFilter
void addError (const char *e)
const std::string & getFilter () const
bool isValid (void) const
true if a valid filter is set
bool match (void)
Test to current selection This method tests the current selection set against the filter and returns true if the described object(s) are selected.
SelectionFilter (const char *filter)
Constructs a SelectionFilter object.
SelectionFilter (const std::string &filter)
void setFilter (const char *filter)
Set a new filter string.
bool test (App::DocumentObject *pObj, const char *sSubName)
Test objects This method tests if a given object is described in the filter.
virtual ~SelectionFilter ()
Additional Inherited Members
Public Attributes inherited from Gui::SelectionFilter
std::vector< std::vector< SelectionObject > > Result
Protected Member Functions inherited from Gui::SelectionFilter
bool parse (void)
Protected Attributes inherited from Gui::TaskView::TaskWatcher
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
Protected Attributes inherited from Gui::SelectionFilter
std::shared_ptr< Node_Block > Ast
std::string Errors
std::string Filter
Constructor & Destructor Documentation
TaskWatcherPython()
TaskWatcherPython::TaskWatcherPython (const Py::Object & o)
References Gui::Command::addTo(), Gui::BitmapFactory(), Gui::Application::commandManager(), Gui::TaskView::TaskWatcher::Content, Gui::CommandManager::getCommandByName(), QSint::ActionGroup::groupLayout(), Gui::Application::Instance, Gui::PythonWrapper::loadCoreModule(), Gui::BitmapFactoryInst::pixmap(), Gui::SelectionFilter::setFilter(), and Gui::PythonWrapper::toQObject().
~TaskWatcherPython()
TaskWatcherPython::~TaskWatcherPython ()
References Gui::TaskView::TaskWatcher::Content.
Member Function Documentation
shouldShow()
bool TaskWatcherPython::shouldShow (void) virtual
is called wenn the document or the Selection changes.
Reimplemented from Gui::TaskView::TaskWatcher.
References Gui::SelectionFilter::Filter, Gui::SelectionFilter::match(), and Gui::TaskView::TaskWatcher::shouldShow().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/TaskView/TaskDialogPython.h
FreeCAD/src/Gui/TaskView/TaskDialogPython.cpp