FreeCAD: Gui::DAG::View Class Reference
Gui::DAG::View Class Reference
view for DAG viewer
#include <DAGView.h>
Public Slots
void awakeSlot ()
hooked up to event dispatcher for update when idle.
Public Member Functions
View (QWidget *parentIn=0)
virtual ~View () override
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockConnection (bool block)
void detachSelection ()
Detaches from the selection.
bool isConnectionAttached () const
bool isConnectionBlocked () const
SelectionObserver (bool attach=true, int resolve=1)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, int resolve=1)
Constructor.
virtual ~SelectionObserver ()
Detailed Description
view for DAG viewer
Constructor & Destructor Documentation
View()
View::View (QWidget * parentIn = 0)
References awakeSlot(), draftgeoutils.faces::bind(), draftgeoutils.intersections::connect(), Gui::Application::Instance, Gui::Application::signalActiveDocument, and Gui::Application::signalDeleteDocument.
~View()
View::~View () override virtual
References draftgeoutils.faces::bind(), Gui::Application::Instance, Gui::Application::signalActiveDocument, and Gui::Application::signalDeleteDocument.
Member Function Documentation
awakeSlot
void View::awakeSlot () slot
hooked up to event dispatcher for update when idle.
References Gui::DAG::Model::awake().
Referenced by View().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DAGView/DAGView.h
Sources/FreeCAD/src/Gui/DAGView/DAGView.cpp