FreeCAD: StdMeshers_MaxElementArea Class Reference
StdMeshers_MaxElementArea Class Reference
#include <StdMeshers_MaxElementArea.hxx>
Public Member Functions
double GetMaxArea () const
virtual std::istream & LoadFrom (std::istream &load)
virtual std::ostream & SaveTo (std::ostream &save)
void SetMaxArea (double maxArea)
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)
Initialize maximal area by the mesh built on the geometry.
StdMeshers_MaxElementArea (int hypId, int studyId, SMESH_Gen *gen)
virtual ~ StdMeshers_MaxElementArea ()
Public Member Functions inherited from SMESH_Hypothesis
void ClearParameters ()
virtual bool DataDependOnParams () const
The returned value is used by NotifySubMeshesHypothesisModification() to decide to call subMesh->AlgoStateEngine(MODIF_HYP, hyp) or not if subMesh is ready to be computed (algo+hyp==OK) but not yet computed. True result is reasonable for example if EventListeners depend on parameters of hypothesis.
virtual int GetDim () const
SMESH_Gen * GetGen () const
char * GetLastParameters () const
virtual const char * GetLibName () const
SMESH_Mesh * GetMeshByPersistentID (int id)
Find a mesh with given persistent ID.
char * GetParameters () const
virtual int GetShapeType () const
int GetStudyId () const
virtual bool IsAuxiliary () const
Return true if me is an auxiliary hypothesis.
virtual void NotifySubMeshesHypothesisModification ()
void SetLastParameters (const char *theParameters)
void SetLibName (const char *theLibName)
void SetParameters (const char *theParameters)
SMESH_Hypothesis (int hypId, int studyId, SMESH_Gen *gen)
virtual ~SMESH_Hypothesis ()
Public Member Functions inherited from SMESHDS_Hypothesis
int GetID () const
const char * GetName () const
int GetType () const
bool IsSameName (const SMESHDS_Hypothesis &other) const
Compare types of hypotheses.
bool operator!= (const SMESHDS_Hypothesis &other) const
virtual bool operator== (const SMESHDS_Hypothesis &other) const
SMESHDS_Hypothesis (int hypId)
virtual ~SMESHDS_Hypothesis ()
Friends
std::ostream & operator<< (std::ostream &save, StdMeshers_MaxElementArea &hyp)
std::istream & operator>> (std::istream &load, StdMeshers_MaxElementArea &hyp)
Additional Inherited Members
Public Types inherited from SMESH_Hypothesis
enum Hypothesis_Status {
HYP_OK = 0 , HYP_MISSING , HYP_CONCURENT , HYP_BAD_PARAMETER ,
HYP_HIDDEN_ALGO , HYP_HIDING_ALGO , HYP_UNKNOWN_FATAL , HYP_INCOMPATIBLE ,
HYP_NOTCONFORM , HYP_ALREADY_EXIST , HYP_BAD_DIM , HYP_BAD_SUBSHAPE ,
HYP_BAD_GEOMETRY , HYP_NEED_SHAPE , HYP_INCOMPAT_HYPS
}
Public Types inherited from SMESHDS_Hypothesis
enum hypothesis_type {
PARAM_ALGO , ALGO_0D , ALGO_1D , ALGO_2D ,
ALGO_3D
}
Static Public Member Functions inherited from SMESH_Hypothesis
static bool IsStatusFatal (Hypothesis_Status theStatus)
Constructor & Destructor Documentation
StdMeshers_MaxElementArea()
StdMeshers_MaxElementArea::StdMeshers_MaxElementArea (int hypId, int studyId, SMESH_Gen * gen)
~ StdMeshers_MaxElementArea()
virtual StdMeshers_MaxElementArea::~ StdMeshers_MaxElementArea () virtual
Member Function Documentation
GetMaxArea()
double StdMeshers_MaxElementArea::GetMaxArea () const
LoadFrom()
istream & StdMeshers_MaxElementArea::LoadFrom (std::istream & load) virtual
Implements SMESHDS_Hypothesis.
SaveTo()
ostream & StdMeshers_MaxElementArea::SaveTo (std::ostream & save) virtual
Implements SMESHDS_Hypothesis.
References OfflineRenderingUtils::save().
SetMaxArea()
void StdMeshers_MaxElementArea::SetMaxArea (double maxArea)
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
Referenced by MeshPart::Mesher::createMesh().
SetParametersByDefaults()
bool StdMeshers_MaxElementArea::SetParametersByDefaults (const TDefaults & dflts, const SMESH_Mesh * theMesh = 0) virtual
Initialize my parameter values by default parameters.
Return values
bool - true if parameter values have been successfully defined
Implements SMESH_Hypothesis.
SetParametersByMesh()
bool StdMeshers_MaxElementArea::SetParametersByMesh (const SMESH_Mesh * theMesh, const TopoDS_Shape & theShape) virtual
Initialize maximal area by the mesh built on the geometry.
Parameters
theMesh - the built mesh
theShape - the geometry of interest
Return values
bool - true if parameter values have been successfully defined
Implements SMESH_Hypothesis.
References SMESHDS_SubMesh::GetElements(), SMESH::Controls::NumericalFunctor::GetPoints(), SMDS_MeshElement::GetType(), SMESH::Controls::Area::GetValue(), and SMESHDS_Mesh::MeshElements().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & save, StdMeshers_MaxElementArea & hyp) friend
operator>>
std::istream& operator>> (std::istream & load, StdMeshers_MaxElementArea & hyp) friend
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_MaxElementArea.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_MaxElementArea.cpp