FreeCAD: MeshCore::MeshFacetGrid Class Reference
MeshCore::MeshFacetGrid Class Reference
Special grid class that stores facet indices of the mesh object in its grids.
#include <Grid.h>
Public Member Functions
Construction
MeshFacetGrid (const MeshKernel &rclM)
Construction.
MeshFacetGrid (void)
Construction.
MeshFacetGrid (const MeshKernel &rclM, unsigned long ulX, unsigned long ulY, unsigned long ulZ)
Construction.
MeshFacetGrid (const MeshKernel &rclM, int iCtGridPerAxis)
Construction.
MeshFacetGrid (const MeshKernel &rclM, float fGridLen)
Construction.
virtual ~MeshFacetGrid (void)
Destruction.
Public Member Functions inherited from MeshCore::MeshGrid
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::vector< unsigned long > &raulElements, bool bDelDoubles=true) const
Searches for elements lying in the intersection area of the grid and the bounding box.
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::set< unsigned long > &raulElementss) const
Searches for elements lying in the intersection area of the grid and the bounding box.
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::vector< unsigned long > &raulElements, const Base::Vector3f &rclOrg, float fMaxDist, bool bDelDoubles=true) const
Searches for elements lying in the intersection area of the grid and the bounding box.
void SearchNearestFromPoint (const Base::Vector3f &rclPt, std::set< unsigned long > &rclInd) const
Searches for the nearest grids that contain elements from a point, the result are grid indices.
unsigned long GetElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ, std::set< unsigned long > &raclInd) const
Returns the indices of the elements in the given grid.
unsigned long GetElements (const Base::Vector3f &rclPoint, std::vector< unsigned long > &aulFacets) const
virtual void GetGridLengths (float &rfLenX, float &rfLenY, float &rfLenZ) const
Returns the lengths of the grid elements in x,y and z direction.
virtual void GetCtGrids (unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
Returns the number of grid elements in x,y and z direction.
Base::BoundBox3f GetBoundBox (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
Returns the bounding box of a given grid element.
Base::BoundBox3f GetBoundBox (void) const
Returns the bounding box of the whole.
Base::BoundBox3f GetMeshBoundBox (void) const
Returns an extended bounding box of the mesh object.
unsigned long GetIndexToPosition (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
Returns an index for the given grid position.
bool GetPositionToIndex (unsigned long id, unsigned long &ulX, unsigned long &ulY, unsigned long &ulZ) const
Returns the grid position to the given index.
unsigned long GetCtElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
Returns the number of elements in a given grid.
bool CheckPosition (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
Checks whether the point is inside the grid.
virtual void Position (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
Returns the indices of the grid this point lies in.
bool CheckPos (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
Checks if this is a valid grid position.
void GetHull (unsigned long ulX, unsigned long ulY, unsigned long ulZ, unsigned long ulDistance, std::set< unsigned long > &raclInd) const
Get the indices of all elements lying in the grids around a given grid with distance ulDistance.
virtual ~MeshGrid (void)
Destruction.
virtual void Attach (const MeshKernel &rclM)
Attaches the mesh kernel to this grid, an already attached mesh gets detached.
virtual void Rebuild (unsigned long ulPerGrid=MESH_CT_GRID, unsigned long ulMaxGrid=MESH_MAX_GRIDS)
Rebuilds the grid structure.
virtual void Rebuild (int iCtGridPerAxis=MESH_CT_GRID_PER_AXIS)
Rebuilds the grid structure.
virtual void Rebuild (unsigned long ulX, unsigned long ulY, unsigned long ulZ)
Rebuilds the grid structure.
Search
unsigned long SearchNearestFromPoint (const Base::Vector3f &rclPt) const
Searches for the nearest facet from a point.
unsigned long SearchNearestFromPoint (const Base::Vector3f &rclPt, float fMaxSearchArea) const
Searches for the nearest facet from a point with the maximum search area.
void SearchNearestFacetInGrid (unsigned long ulX, unsigned long ulY, unsigned long ulZ, const Base::Vector3f &rclPt, float &rfMinDist, unsigned long &rulFacetInd) const
Searches for the nearest facet in a given grid element and returns the facet index and the actual distance.
void SearchNearestFacetInHull (unsigned long ulX, unsigned long ulY, unsigned long ulZ, unsigned long ulDistance, const Base::Vector3f &rclPt, unsigned long &rulFacetInd, float &rfMinDist) const
Does basically the same as the method above unless that grid neighbours up to the order of ulDistance are introduced into the search.
virtual void Validate (const MeshKernel &rclM)
Validates the grid structure and rebuilds it if needed.
virtual void Validate (void)
Validates the grid structure and rebuilds it if needed.
virtual bool Verify () const
Verifies the grid structure and returns false if inconsistencies are found.
void Pos (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
Returns the grid numbers to the given point rclPoint.
void PosWithCheck (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
Returns the grid numbers to the given point rclPoint.
void AddFacet (const MeshGeomFacet &rclFacet, unsigned long ulFacetIndex, float fEpsilon=0.0f)
Adds a new facet element to the grid structure.
unsigned long HasElements (void) const
Returns the number of stored elements.
virtual void RebuildGrid (void)
Rebuilds the grid structure.
Additional Inherited Members
Protected Member Functions inherited from MeshCore::MeshGrid
virtual void InitGrid (void)
Initializes the size of the internal structure.
virtual void Clear (void)
Deletes the grid structure.
virtual void CalculateGridLength (unsigned long ulCtGrid, unsigned long ulMaxGrids)
Calculates the grid length dependent on maximum number of grids.
virtual void CalculateGridLength (int iCtGridPerAxis)
Calculates the grid length dependent on the number of grids per axis.
MeshGrid (const MeshKernel &rclM)
Construction.
MeshGrid (void)
Construction.
Detailed Description
Special grid class that stores facet indices of the mesh object in its grids.
Constructor & Destructor Documentation
MeshFacetGrid() [1/5]
MeshFacetGrid::MeshFacetGrid (const MeshKernel & rclM)
Construction.
References RebuildGrid().
MeshFacetGrid() [2/5]
MeshCore::MeshFacetGrid::MeshFacetGrid (void)
Construction.
MeshFacetGrid() [3/5]
MeshFacetGrid::MeshFacetGrid (const MeshKernel & rclM, unsigned long ulX, unsigned long ulY, unsigned long ulZ)
Construction.
References MeshCore::MeshGrid::Rebuild().
MeshFacetGrid() [4/5]
MeshFacetGrid::MeshFacetGrid (const MeshKernel & rclM, int iCtGridPerAxis)
Construction.
References MeshCore::MeshGrid::Rebuild().
MeshFacetGrid() [5/5]
MeshFacetGrid::MeshFacetGrid (const MeshKernel & rclM, float fGridLen)
Construction.
References Base::BoundBox3< _Precision >::LengthX(), Base::BoundBox3< _Precision >::LengthY(), Base::BoundBox3< _Precision >::LengthZ(), and MeshCore::MeshGrid::Rebuild().
~MeshFacetGrid()
virtual MeshCore::MeshFacetGrid::~MeshFacetGrid (void) virtual
Destruction.
Member Function Documentation
AddFacet()
void MeshCore::MeshFacetGrid::AddFacet (const MeshGeomFacet & rclFacet, unsigned long ulFacetIndex, float fEpsilon = 0.0f) protected
Adds a new facet element to the grid structure.
rclFacet is the geometric facet and ulFacetIndex the corresponding index in the mesh kernel. The facet is added to each grid element that intersects the facet.
References Base::BoundBox3< _Precision >::Add(), MeshCore::MeshGrid::GetBoundBox(), MeshCore::MeshGeomFacet::IntersectBoundingBox(), Base::BoundBox3< _Precision >::MaxX, Base::BoundBox3< _Precision >::MaxY, Base::BoundBox3< _Precision >::MaxZ, Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, Base::BoundBox3< _Precision >::MinZ, and Pos().
Referenced by RebuildGrid().
HasElements()
unsigned long MeshCore::MeshFacetGrid::HasElements (void) const protected virtual
Returns the number of stored elements.
Implements MeshCore::MeshGrid.
Pos()
void MeshCore::MeshFacetGrid::Pos (const Base::Vector3f & rclPoint, unsigned long & rulX, unsigned long & rulY, unsigned long & rulZ) const protected
Returns the grid numbers to the given point rclPoint.
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by AddFacet().
PosWithCheck()
void MeshCore::MeshFacetGrid::PosWithCheck (const Base::Vector3f & rclPoint, unsigned long & rulX, unsigned long & rulY, unsigned long & rulZ) const protected
Returns the grid numbers to the given point rclPoint.
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
RebuildGrid()
void MeshFacetGrid::RebuildGrid (void) protected virtual
Rebuilds the grid structure.
Implements MeshCore::MeshGrid.
References AddFacet(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshGrid::InitGrid(), MeshCore::MeshFacetIterator::More(), and MeshCore::MeshFacetIterator::Next().
Referenced by MeshFacetGrid(), and Validate().
SearchNearestFacetInGrid()
void MeshFacetGrid::SearchNearestFacetInGrid (unsigned long ulX, unsigned long ulY, unsigned long ulZ, const Base::Vector3f & rclPt, float & rfMinDist, unsigned long & rulFacetInd) const
Searches for the nearest facet in a given grid element and returns the facet index and the actual distance.
Referenced by SearchNearestFacetInHull(), and SearchNearestFromPoint().
SearchNearestFacetInHull()
void MeshFacetGrid::SearchNearestFacetInHull (unsigned long ulX, unsigned long ulY, unsigned long ulZ, unsigned long ulDistance, const Base::Vector3f & rclPt, unsigned long & rulFacetInd, float & rfMinDist) const
Does basically the same as the method above unless that grid neighbours up to the order of ulDistance are introduced into the search.
References SearchNearestFacetInGrid().
Referenced by SearchNearestFromPoint().
SearchNearestFromPoint() [1/2]
unsigned long MeshFacetGrid::SearchNearestFromPoint (const Base::Vector3f & rclPt) const
Searches for the nearest facet from a point.
References Base::BoundBox3< _Precision >::BACK, Base::BoundBox3< _Precision >::BOTTOM, Base::BoundBox3< _Precision >::FRONT, MeshCore::MeshGrid::GetBoundBox(), Base::BoundBox3< _Precision >::GetCenter(), Base::BoundBox3< _Precision >::GetSideFromRay(), Base::BoundBox3< _Precision >::IsInBox(), Base::BoundBox3< _Precision >::LEFT, Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, Base::BoundBox3< _Precision >::MinZ, MeshCore::MeshGrid::Position(), Base::BoundBox3< _Precision >::RIGHT, SearchNearestFacetInGrid(), SearchNearestFacetInHull(), Base::BoundBox3< _Precision >::TOP, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by MeshCore::MeshAlgorithm::NearestPointFromPoint().
SearchNearestFromPoint() [2/2]
unsigned long MeshFacetGrid::SearchNearestFromPoint (const Base::Vector3f & rclPt, float fMaxSearchArea) const
Searches for the nearest facet from a point with the maximum search area.
References MeshCore::MeshAlgorithm::Distance(), MeshCore::MeshGrid::Inside(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Validate() [1/2]
void MeshFacetGrid::Validate (const MeshKernel & rclM) virtual
Validates the grid structure and rebuilds it if needed.
Implements MeshCore::MeshGrid.
References MeshCore::MeshGrid::Attach(), MeshCore::MeshKernel::CountFacets(), and RebuildGrid().
Validate() [2/2]
void MeshFacetGrid::Validate (void) virtual
Validates the grid structure and rebuilds it if needed.
References RebuildGrid().
Verify()
bool MeshFacetGrid::Verify () const virtual
Verifies the grid structure and returns false if inconsistencies are found.
Implements MeshCore::MeshGrid.
References MeshCore::MeshGridIterator::GetBoundBox(), MeshCore::MeshGridIterator::GetElements(), MeshCore::MeshGridIterator::Init(), MeshCore::MeshGeomFacet::IntersectBoundingBox(), MeshCore::MeshGridIterator::More(), MeshCore::MeshGridIterator::Next(), and MeshCore::MeshFacetIterator::Set().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Grid.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Grid.cpp