FreeCAD: FemGui::Ui_DlgSettingsFemElmerImp Class Reference
FemGui::Ui_DlgSettingsFemElmerImp Class Reference
#include <ui_DlgSettingsFemElmer.h>
Public Member Functions
void retranslateUi (QWidget *FemGui__DlgSettingsFemElmerImp)
void setupUi (QWidget *FemGui__DlgSettingsFemElmerImp)
Public Attributes
Gui::PrefCheckBox * cb_elmer_binary_std
Gui::PrefCheckBox * cb_grid_binary_std
Gui::PrefFileChooser * fc_elmer_binary_path
Gui::PrefFileChooser * fc_grid_binary_path
QGroupBox * gb_gmsh_param
QGridLayout * gl_01
QHBoxLayout * horizontalLayout_2
QLabel * l_elmer_binary_path
QLabel * l_elmer_binary_std
QLabel * l_grid_binary_path
QLabel * l_grid_binary_std
QVBoxLayout * verticalLayout
QVBoxLayout * verticalLayout_2
QSpacerItem * verticalSpacer
Member Function Documentation
retranslateUi()
void FemGui::Ui_DlgSettingsFemElmerImp::retranslateUi (QWidget * FemGui__DlgSettingsFemElmerImp)
References cb_elmer_binary_std, cb_grid_binary_std, fc_elmer_binary_path, fc_grid_binary_path, gb_gmsh_param, l_elmer_binary_path, l_elmer_binary_std, l_grid_binary_path, l_grid_binary_std, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void FemGui::Ui_DlgSettingsFemElmerImp::setupUi (QWidget * FemGui__DlgSettingsFemElmerImp)
References cb_elmer_binary_std, cb_grid_binary_std, draftgeoutils.intersections::connect(), fc_elmer_binary_path, fc_grid_binary_path, gb_gmsh_param, gl_01, horizontalLayout_2, l_elmer_binary_path, l_elmer_binary_std, l_grid_binary_path, l_grid_binary_std, retranslateUi(), verticalLayout, verticalLayout_2, and verticalSpacer.
Member Data Documentation
cb_elmer_binary_std
Gui::PrefCheckBox* FemGui::Ui_DlgSettingsFemElmerImp::cb_elmer_binary_std
Referenced by retranslateUi(), and setupUi().
cb_grid_binary_std
Gui::PrefCheckBox* FemGui::Ui_DlgSettingsFemElmerImp::cb_grid_binary_std
Referenced by retranslateUi(), and setupUi().
fc_elmer_binary_path
Gui::PrefFileChooser* FemGui::Ui_DlgSettingsFemElmerImp::fc_elmer_binary_path
Referenced by retranslateUi(), and setupUi().
fc_grid_binary_path
Gui::PrefFileChooser* FemGui::Ui_DlgSettingsFemElmerImp::fc_grid_binary_path
Referenced by retranslateUi(), and setupUi().
gb_gmsh_param
QGroupBox* FemGui::Ui_DlgSettingsFemElmerImp::gb_gmsh_param
Referenced by retranslateUi(), and setupUi().
gl_01
QGridLayout* FemGui::Ui_DlgSettingsFemElmerImp::gl_01
Referenced by setupUi().
horizontalLayout_2
QHBoxLayout* FemGui::Ui_DlgSettingsFemElmerImp::horizontalLayout_2
Referenced by setupUi().
l_elmer_binary_path
QLabel* FemGui::Ui_DlgSettingsFemElmerImp::l_elmer_binary_path
Referenced by retranslateUi(), and setupUi().
l_elmer_binary_std
QLabel* FemGui::Ui_DlgSettingsFemElmerImp::l_elmer_binary_std
Referenced by retranslateUi(), and setupUi().
l_grid_binary_path
QLabel* FemGui::Ui_DlgSettingsFemElmerImp::l_grid_binary_path
Referenced by retranslateUi(), and setupUi().
l_grid_binary_std
QLabel* FemGui::Ui_DlgSettingsFemElmerImp::l_grid_binary_std
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* FemGui::Ui_DlgSettingsFemElmerImp::verticalLayout
Referenced by setupUi().
verticalLayout_2
QVBoxLayout* FemGui::Ui_DlgSettingsFemElmerImp::verticalLayout_2
Referenced by setupUi().
verticalSpacer
QSpacerItem* FemGui::Ui_DlgSettingsFemElmerImp::verticalSpacer
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Fem/Gui/ui_DlgSettingsFemElmer.h