FreeCAD: StdMeshers Namespace Reference
StdMeshers Namespace Reference
Classes
class Function
class FunctionExpr
class FunctionIntegral
class FunctionTable
Functions
STDMESHERS_EXPORT bool buildDistribution (const Function &f, const double start, const double end, const int nbSeg, std::vector< double > &data, const double eps)
STDMESHERS_EXPORT bool buildDistribution (const std::vector< double > &f, const int conv, const double start, const double end, const int nbSeg, std::vector< double > &data, const double eps)
STDMESHERS_EXPORT bool buildDistribution (const TCollection_AsciiString &f, const int conv, const double start, const double end, const int nbSeg, std::vector< double > &data, const double eps)
double dihotomySolve (Function &f, const double val, const double _start, const double _fin, const double eps, bool &ok)
Function Documentation
buildDistribution() [1/3]
bool StdMeshers::buildDistribution (const Function & f, const double start, const double end, const int nbSeg, std::vector< double > & data, const double eps)
References dihotomySolve().
Referenced by buildDistribution(), StdMeshers_NumberOfSegments::BuildDistributionExpr(), and StdMeshers_NumberOfSegments::BuildDistributionTab().
buildDistribution() [2/3]
bool StdMeshers::buildDistribution (const std::vector< double > & f, const int conv, const double start, const double end, const int nbSeg, std::vector< double > & data, const double eps)
References buildDistribution().
buildDistribution() [3/3]
bool StdMeshers::buildDistribution (const TCollection_AsciiString & f, const int conv, const double start, const double end, const int nbSeg, std::vector< double > & data, const double eps)
References buildDistribution().
dihotomySolve()
double StdMeshers::dihotomySolve (Function & f, const double val, const double _start, const double _fin, const double eps, bool & ok)
Referenced by buildDistribution().