FreeCAD: Gui::PythonWrapper Class Reference
Gui::PythonWrapper Class Reference
#include <PythonWrapper.h>
Public Member Functions
Py::Object fromQDir (const QDir &)
Py::Object fromQIcon (const QIcon *)
Py::Object fromQObject (QObject *, const char *className=nullptr)
Py::Object fromQWidget (QWidget *, const char *className=nullptr)
const char * getWrapperName (QObject *) const
bool loadCoreModule ()
bool loadGuiModule ()
bool loadUiToolsModule ()
bool loadWidgetsModule ()
PythonWrapper ()
bool toCString (const Py::Object &, std::string &)
QDir * toQDir (PyObject *pyobj)
QGraphicsItem * toQGraphicsItem (PyObject *ptr)
QGraphicsObject * toQGraphicsObject (PyObject *pyPtr)
QIcon * toQIcon (PyObject *pyobj)
QObject * toQObject (const Py::Object &)
Static Public Member Functions
static void createChildrenNameAttributes (PyObject *root, QObject *object)
static void setParent (PyObject *pyWdg, QObject *parent)
Constructor & Destructor Documentation
PythonWrapper()
PythonWrapper::PythonWrapper ()
Member Function Documentation
createChildrenNameAttributes()
void PythonWrapper::createChildrenNameAttributes (PyObject * root, QObject * object) static
References createChildrenNameAttributes(), and Gui::qt_identifyType().
Referenced by createChildrenNameAttributes(), and Gui::UiLoaderPy::load().
fromQDir()
Py::Object PythonWrapper::fromQDir (const QDir & dir)
fromQIcon()
Py::Object PythonWrapper::fromQIcon (const QIcon * icon)
Create a Python wrapper for the icon. The icon must be created on the heap and the Python wrapper takes ownership of it.
Referenced by Gui::Application::sGetIcon().
fromQObject()
Py::Object PythonWrapper::fromQObject (QObject * object, const char * className = nullptr)
fromQWidget()
Py::Object PythonWrapper::fromQWidget (QWidget * widget, const char * className = nullptr)
Referenced by Gui::MainWindowPy::createWrapper(), Gui::View3DInventorPy::graphicsView(), Gui::UiLoaderPy::load(), Gui::TaskView::TaskDialogPython::modifyStandardButtons(), and Gui::ViewProviderPythonFeatureImp::setupContextMenu().
getWrapperName()
const char * PythonWrapper::getWrapperName (QObject * obj) const
Referenced by Gui::UiLoaderPy::load().
loadCoreModule()
bool PythonWrapper::loadCoreModule ()
Referenced by Gui::MainWindowPy::createWrapper(), Gui::UiLoaderPy::load(), Gui::Dialog::PreferencePagePython::PreferencePagePython(), Gui::TaskView::TaskDialogPython::TaskDialogPython(), and Gui::TaskView::TaskWatcherPython::TaskWatcherPython().
loadGuiModule()
bool PythonWrapper::loadGuiModule ()
Referenced by Gui::MainWindowPy::createWrapper(), Gui::ViewProviderPythonFeatureImp::getIcon(), Gui::UiLoaderPy::load(), Gui::TaskView::TaskDialogPython::modifyStandardButtons(), Gui::ViewProviderPythonFeatureImp::setupContextMenu(), and Gui::Application::sGetIcon().
loadUiToolsModule()
bool PythonWrapper::loadUiToolsModule ()
loadWidgetsModule()
bool PythonWrapper::loadWidgetsModule ()
Referenced by Gui::MainWindowPy::createWrapper(), Gui::ViewProviderPythonFeatureImp::getIcon(), Gui::View3DInventorPy::graphicsView(), Gui::UiLoaderPy::load(), Gui::TaskView::TaskDialogPython::modifyStandardButtons(), Gui::ViewProviderPythonFeatureImp::setupContextMenu(), and Gui::Application::sGetIcon().
setParent()
void PythonWrapper::setParent (PyObject * pyWdg, QObject * parent) static
Referenced by Gui::UiLoaderPy::load().
toCString()
bool PythonWrapper::toCString (const Py::Object & pyobject, std::string & str)
Referenced by Gui::UiLoaderPy::load().
toQDir()
QDir * PythonWrapper::toQDir (PyObject * pyobj)
toQGraphicsItem()
QGraphicsItem * PythonWrapper::toQGraphicsItem (PyObject * ptr)
References Gui::qt_getCppPointer().
toQGraphicsObject()
QGraphicsObject * PythonWrapper::toQGraphicsObject (PyObject * pyPtr)
References Gui::qt_getCppPointer().
toQIcon()
QIcon * PythonWrapper::toQIcon (PyObject * pyobj)
Referenced by Gui::ViewProviderPythonFeatureImp::getIcon().
toQObject()
QObject * PythonWrapper::toQObject (const Py::Object & pyobject)
References Gui::qt_getCppPointer().
Referenced by Gui::UiLoaderPy::load(), Gui::Dialog::PreferencePagePython::PreferencePagePython(), Gui::TaskView::TaskDialogPython::TaskDialogPython(), and Gui::TaskView::TaskWatcherPython::TaskWatcherPython().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/PythonWrapper.h
FreeCAD/src/Gui/PythonWrapper.cpp