FreeCAD: Import::ImpExpDxfWrite Class Reference
Import::ImpExpDxfWrite Class Reference
#include <ImpExpDxf.h>
Public Member Functions
void exportAngularDim (Base::Vector3d textLocn, Base::Vector3d lineLocn, Base::Vector3d extLine1Start, Base::Vector3d extLine2Start, Base::Vector3d apexPoint, char *dimText)
void exportDiametricDim (Base::Vector3d textLocn, Base::Vector3d arcPoint1, Base::Vector3d arcPoint2, char *dimText)
void exportLinearDim (Base::Vector3d textLocn, Base::Vector3d lineLocn, Base::Vector3d extLine1Start, Base::Vector3d extLine2Start, char *dimText, int type)
void exportRadialDim (Base::Vector3d centerPoint, Base::Vector3d textLocn, Base::Vector3d arcPoint, char *dimText)
void exportShape (const TopoDS_Shape input)
void exportText (const char *text, Base::Vector3d position1, Base::Vector3d position2, double size, int just)
std::string getOptionSource ()
ImpExpDxfWrite (std::string filepath)
void setOptions (void)
void setOptionSource (std::string s)
~ImpExpDxfWrite ()
Public Member Functions inherited from CDxfWrite
void addBlockName (std::string s, std::string blkRecordHandle)
CDxfWrite (const char *filepath)
CDxfWrite (const char *filepath)
CDxfWrite (const char *filepath)
void endRun (void)
assemble pieces into output file
bool Failed ()
bool Failed ()
bool Failed ()
std::string getLayerName ()
void init (void)
void makeBlockRecordTableBody (void)
void makeBlockRecordTableHead (void)
void makeBlockSectionHead (void)
void makeLayerTable (void)
void setLayerName (std::string s)
void setPolyOverride (bool b)
void setVersion (int v)
void writeAngularDim (const double *textMidPoint, const double *lineDefPoint, const double *startExt1, const double *endExt1, const double *startExt2, const double *endExt2, const char *dimText)
void writeAngularDimBlock (const double *textMidPoint, const double *lineDefPoint, const double *startExt1, const double *endExt1, const double *startExt2, const double *endExt2, const char *dimText)
void writeArc (const double *s, const double *e, const double *c, bool dir)
void WriteArc (const double *s, const double *e, const double *c, bool dir, const char *layer_name)
void WriteArc (const double *s, const double *e, const double *c, bool dir, const char *layer_name)
void writeBlocksSection (void)
void writeBlockTrailer (void)
void writeCircle (const double *c, double radius)
void WriteCircle (const double *c, double radius, const char *layer_name)
void WriteCircle (const double *c, double radius, const char *layer_name)
void writeClassesSection (void)
void writeDiametricDim (const double *textMidPoint, const double *arcPoint1, const double *arcPoint2, const char *dimText)
void writeDiametricDimBlock (const double *textMidPoint, const double *arcPoint1, const double *arcPoint2, const char *dimText)
void writeDimBlockPreamble ()
void WriteEllipse (const double *c, double major_radius, double minor_radius, double rotation, double start_angle, double end_angle, bool dir, const char *layer_name)
void WriteEllipse (const double *c, double major_radius, double minor_radius, double rotation, double start_angle, double end_angle, bool dir, const char *layer_name)
void writeEllipse (const double *c, double major_radius, double minor_radius, double rotation, double start_angle, double end_angle, bool endIsCW)
void writeEntitiesSection (void)
void writeHeaderSection (void)
void writeLine (const double *s, const double *e)
void WriteLine (const double *s, const double *e, const char *layer_name)
void WriteLine (const double *s, const double *e, const char *layer_name)
void writeLinearDim (const double *textMidPoint, const double *lineDefPoint, const double *extLine1, const double *extLine2, const char *dimText, int type)
void writeLinearDimBlock (const double *textMidPoint, const double *lineDefPoint, const double *extLine1, const double *extLine2, const char *dimText, int type)
void writeLWPolyLine (const LWPolyDataOut &pd)
void writeObjectsSection (void)
void writePoint (const double *)
void WritePoint (const double *, const char *)
void WritePoint (const double *, const char *)
void writePolyline (const LWPolyDataOut &pd)
void writeRadialDim (const double *centerPoint, const double *textMidPoint, const double *arcPoint, const char *dimText)
void writeRadialDimBlock (const double *centerPoint, const double *textMidPoint, const double *arcPoint, const char *dimText)
void writeSpline (const SplineDataOut &sd)
void writeTablesSection (void)
void writeText (const char *text, const double *location1, const double *location2, const double height, const int horizJust)
void writeVertex (double x, double y, double z)
~CDxfWrite ()
~CDxfWrite ()
~CDxfWrite ()
Static Public Member Functions
static bool gp_PntCompare (gp_Pnt p1, gp_Pnt p2)
static bool gp_PntEqual (gp_Pnt p1, gp_Pnt p2)
Protected Member Functions
void exportArc (BRepAdaptor_Curve &c)
void exportBCurve (BRepAdaptor_Curve &c)
void exportBSpline (BRepAdaptor_Curve &c)
void exportCircle (BRepAdaptor_Curve &c)
void exportEllipse (BRepAdaptor_Curve &c)
void exportEllipseArc (BRepAdaptor_Curve &c)
void exportLine (BRepAdaptor_Curve &c)
void exportLWPoly (BRepAdaptor_Curve &c)
void exportPolyline (BRepAdaptor_Curve &c)
Protected Member Functions inherited from CDxfWrite
std::string getBlkRecordHandle (void)
std::string getBlockHandle (void)
std::string getEntityHandle (void)
std::string getHandle (void)
std::string getLayerHandle (void)
std::string getPlateFile (std::string fileSpec)
copy boiler plate file
void putArrow (Base::Vector3d arrowPos, Base::Vector3d barb1Pos, Base::Vector3d barb2Pos, std::ostringstream *outStream, const std::string handle, const std::string ownerHandle)
void putLine (const Base::Vector3d s, const Base::Vector3d e, std::ostringstream *outStream, const std::string handle, const std::string ownerHandle)
void putText (const char *text, const Base::Vector3d location1, const Base::Vector3d location2, const double height, const int horizJust, std::ostringstream *outStream, const std::string handle, const std::string ownerHandle)
void setDataDir (std::string s)
Protected Attributes
bool optionExpPoints
double optionMaxLength
bool optionPolyLine
Protected Attributes inherited from CDxfWrite
int m_blkRecordHandle
std::vector< std::string > m_blkRecordList
int m_blockHandle
std::vector< std::string > m_blockList
std::string m_currentBlock
std::string m_dataDir
int m_entityHandle
int m_handle
int m_layerHandle
std::vector< std::string > m_layerList
std::string m_layerName
std::string m_optionSource
bool m_polyOverride
std::string m_saveBlkRecordHandle
std::string m_saveBlockRecordTableHandle
std::string m_saveModelSpaceHandle
std::string m_savePaperSpaceHandle
int m_version
Constructor & Destructor Documentation
ImpExpDxfWrite()
ImpExpDxfWrite::ImpExpDxfWrite (std::string filepath)
References setOptions(), and setOptionSource().
~ImpExpDxfWrite()
ImpExpDxfWrite::~ImpExpDxfWrite ()
Member Function Documentation
exportAngularDim()
void ImpExpDxfWrite::exportAngularDim (Base::Vector3d textLocn, Base::Vector3d lineLocn, Base::Vector3d extLine1Start, Base::Vector3d extLine2Start, Base::Vector3d apexPoint, char * dimText)
References CDxfWrite::writeAngularDim(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
exportArc()
void ImpExpDxfWrite::exportArc (BRepAdaptor_Curve & c) protected
References draftgeoutils.general::v1(), and CDxfWrite::writeArc().
Referenced by exportShape().
exportBCurve()
void ImpExpDxfWrite::exportBCurve (BRepAdaptor_Curve & c) protected
References Base::Console(), and Base::ConsoleSingleton::Message().
Referenced by exportShape().
exportBSpline()
void ImpExpDxfWrite::exportBSpline (BRepAdaptor_Curve & c) protected
References Base::Console(), SplineDataOut::control, SplineDataOut::control_points, SplineDataOut::degree, SplineDataOut::endtan, SplineDataOut::flag, SplineDataOut::knot, SplineDataOut::knots, Base::ConsoleSingleton::Message(), SplineDataOut::norm, SplineDataOut::starttan, CDxfWrite::writeSpline(), point3D::x, point3D::y, and point3D::z.
Referenced by exportShape().
exportCircle()
void ImpExpDxfWrite::exportCircle (BRepAdaptor_Curve & c) protected
References CDxfWrite::writeCircle().
Referenced by exportShape().
exportDiametricDim()
void ImpExpDxfWrite::exportDiametricDim (Base::Vector3d textLocn, Base::Vector3d arcPoint1, Base::Vector3d arcPoint2, char * dimText)
References CDxfWrite::writeDiametricDim(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
exportEllipse()
void ImpExpDxfWrite::exportEllipse (BRepAdaptor_Curve & c) protected
References CDxfWrite::writeEllipse().
Referenced by exportShape().
exportEllipseArc()
void ImpExpDxfWrite::exportEllipseArc (BRepAdaptor_Curve & c) protected
References draftgeoutils.general::v1(), and CDxfWrite::writeEllipse().
Referenced by exportShape().
exportLine()
void ImpExpDxfWrite::exportLine (BRepAdaptor_Curve & c) protected
References CDxfWrite::writeLine().
Referenced by exportShape().
exportLinearDim()
void ImpExpDxfWrite::exportLinearDim (Base::Vector3d textLocn, Base::Vector3d lineLocn, Base::Vector3d extLine1Start, Base::Vector3d extLine2Start, char * dimText, int type)
References CDxfWrite::writeLinearDim(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
exportLWPoly()
void ImpExpDxfWrite::exportLWPoly (BRepAdaptor_Curve & c) protected
References LWPolyDataOut::Elev, LWPolyDataOut::Extr, LWPolyDataOut::Flag, LWPolyDataOut::nVert, optionMaxLength, LWPolyDataOut::Thick, LWPolyDataOut::Verts, CDxfWrite::writeLWPolyLine(), point3D::x, point3D::y, and point3D::z.
Referenced by exportShape().
exportPolyline()
void ImpExpDxfWrite::exportPolyline (BRepAdaptor_Curve & c) protected
References LWPolyDataOut::Elev, LWPolyDataOut::Extr, LWPolyDataOut::Flag, LWPolyDataOut::nVert, optionMaxLength, LWPolyDataOut::Thick, LWPolyDataOut::Verts, CDxfWrite::writePolyline(), point3D::x, point3D::y, and point3D::z.
Referenced by exportShape().
exportRadialDim()
void ImpExpDxfWrite::exportRadialDim (Base::Vector3d centerPoint, Base::Vector3d textLocn, Base::Vector3d arcPoint, char * dimText)
References CDxfWrite::writeRadialDim(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
exportShape()
void ImpExpDxfWrite::exportShape (const TopoDS_Shape input)
References Base::Console(), exportArc(), exportBCurve(), exportBSpline(), exportCircle(), exportEllipse(), exportEllipseArc(), exportLine(), exportLWPoly(), exportPolyline(), gp_PntCompare(), gp_PntEqual(), CDxfWrite::m_polyOverride, CDxfWrite::m_version, optionExpPoints, optionPolyLine, Base::ConsoleSingleton::Warning(), and CDxfWrite::writePoint().
exportText()
void ImpExpDxfWrite::exportText (const char * text, Base::Vector3d position1, Base::Vector3d position2, double size, int just)
References CDxfWrite::writeText(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
getOptionSource()
std::string Import::ImpExpDxfWrite::getOptionSource ()
Referenced by setOptions().
gp_PntCompare()
bool ImpExpDxfWrite::gp_PntCompare (gp_Pnt p1, gp_Pnt p2) static
Referenced by exportShape().
gp_PntEqual()
bool ImpExpDxfWrite::gp_PntEqual (gp_Pnt p1, gp_Pnt p2) static
Referenced by exportShape().
setOptions()
void ImpExpDxfWrite::setOptions (void)
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetFloat(), ParameterGrp::GetInt(), getOptionSource(), App::Application::GetParameterGroupByPath(), App::Application::getResourceDir(), CDxfWrite::m_polyOverride, CDxfWrite::m_version, optionExpPoints, optionMaxLength, optionPolyLine, and CDxfWrite::setDataDir().
Referenced by ImpExpDxfWrite().
setOptionSource()
void Import::ImpExpDxfWrite::setOptionSource (std::string s)
Referenced by ImpExpDxfWrite().
Member Data Documentation
optionExpPoints
bool Import::ImpExpDxfWrite::optionExpPoints protected
Referenced by exportShape(), and setOptions().
optionMaxLength
double Import::ImpExpDxfWrite::optionMaxLength protected
Referenced by exportLWPoly(), exportPolyline(), and setOptions().
optionPolyLine
bool Import::ImpExpDxfWrite::optionPolyLine protected
Referenced by exportShape(), and setOptions().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Import/App/ImpExpDxf.h
Sources/FreeCAD/src/Mod/Import/App/ImpExpDxf.cpp