FreeCAD: PathScripts.PathToolBit Namespace Reference
PathScripts.PathToolBit Namespace Reference
Classes
class AttributePrototype
class ToolBit
class ToolBitFactory
Functions
def Declaration (path)
def findBit (path)
def findLibrary (path, dbg=False)
def findRelativePathLibrary (path)
def findRelativePathShape (path)
def findRelativePathTool (path)
def findShape (path)
def translate (context, text, disambig=None)
def updateConstraint (sketch, name, value)
Variables
Factory = ToolBitFactory()
dictionary ParameterTypeConstraint
Part = LazyLoader('Part', globals(), 'Part')
string PropertyGroupAttribute = 'Attribute'
string PropertyGroupBit = 'Bit'
Function Documentation
Declaration()
def PathScripts.PathToolBit.Declaration (path)
Referenced by PathScripts.PathToolBit.ToolBitFactory.CreateFrom().
findBit()
def PathScripts.PathToolBit.findBit (path)
findLibrary()
def PathScripts.PathToolBit.findLibrary (path, dbg = False)
findRelativePathLibrary()
def PathScripts.PathToolBit.findRelativePathLibrary (path)
findRelativePathShape()
def PathScripts.PathToolBit.findRelativePathShape (path)
Referenced by PathScripts.PathToolBit.ToolBit.templateAttrs().
findRelativePathTool()
def PathScripts.PathToolBit.findRelativePathTool (path)
findShape()
def PathScripts.PathToolBit.findShape (path)
findShape(path) ... search for path, full and partially
in all known shape directories.
Referenced by PathScripts.PathToolBit.ToolBit.getBitThumbnail(), and PathScripts.PathToolBit.ToolBit.onDelete().
translate()
def PathScripts.PathToolBit.translate (context, text, disambig = None)
updateConstraint()
def PathScripts.PathToolBit.updateConstraint (sketch, name, value)
Referenced by PathScripts.PathToolBit.ToolBit.onDelete().
Variable Documentation
Factory
PathScripts.PathToolBit.Factory = ToolBitFactory()
ParameterTypeConstraint
dictionary PathScripts.PathToolBit.ParameterTypeConstraint
Initial value:
 =  {
         'Angle':        'App::PropertyAngle',
         'Distance':     'App::PropertyLength',
         'DistanceX':    'App::PropertyLength',
         'DistanceY':    'App::PropertyLength',
         'Radius':       'App::PropertyLength'}
Part
PathScripts.PathToolBit.Part = LazyLoader('Part', globals(), 'Part')
PropertyGroupAttribute
string PathScripts.PathToolBit.PropertyGroupAttribute = 'Attribute'
PropertyGroupBit
string PathScripts.PathToolBit.PropertyGroupBit = 'Bit'