FreeCAD: UNV164 Namespace Reference
UNV164 Namespace Reference
Classes
struct TRecord
Enumerations
enum { LENGTH_FACTOR , FORCE_FACTOR , TEMP_FACTOR , TEMP_OFFSET }
Functions
MESHDRIVERUNV_EXPORT void Read (std::ifstream &in_stream, TRecord &theUnitsRecord)
MESHDRIVERUNV_EXPORT void Write (std::ofstream &out_stream)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
LENGTH_FACTOR
FORCE_FACTOR
TEMP_FACTOR
TEMP_OFFSET
Function Documentation
Read()
void UNV164::Read (std::ifstream & in_stream, TRecord & theUnitsRecord)
References UNV::beginning_of_dataset(), UNV::D_to_e(), UNV164::TRecord::factors, UNV164::TRecord::temp_mode, UNV::theMaxLineLen, UNV164::TRecord::units_code, and UNV164::TRecord::units_description.
Referenced by DriverUNV_R_SMDS_Mesh::Perform().
Write()
void UNV164::Write (std::ofstream & out_stream)
Referenced by DriverUNV_W_SMDS_Mesh::Perform().