FreeCAD: PartDesignGui::Ui_TaskDraftParameters Class Reference
PartDesignGui::Ui_TaskDraftParameters Class Reference
#include <ui_TaskDraftParameters.h>
Public Member Functions
void retranslateUi (QWidget *PartDesignGui__TaskDraftParameters)
void setupUi (QWidget *PartDesignGui__TaskDraftParameters)
Public Attributes
QToolButton * buttonLine
QToolButton * buttonPlane
QToolButton * buttonRefAdd
QToolButton * buttonRefRemove
QCheckBox * checkReverse
Gui::QuantitySpinBox * draftAngle
QHBoxLayout * horizontalLayout
QHBoxLayout * horizontalLayout_2
QHBoxLayout * horizontalLayout_3
QHBoxLayout * horizontalLayout_4
QLabel * label
QLineEdit * lineLine
QLineEdit * linePlane
QListWidget * listWidgetReferences
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void PartDesignGui::Ui_TaskDraftParameters::retranslateUi (QWidget * PartDesignGui__TaskDraftParameters)
References buttonLine, buttonPlane, buttonRefAdd, buttonRefRemove, checkReverse, listWidgetReferences, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void PartDesignGui::Ui_TaskDraftParameters::setupUi (QWidget * PartDesignGui__TaskDraftParameters)
References buttonLine, buttonPlane, buttonRefAdd, buttonRefRemove, checkReverse, draftAngle, horizontalLayout, horizontalLayout_2, horizontalLayout_3, horizontalLayout_4, lineLine, linePlane, listWidgetReferences, retranslateUi(), Gui::QuantitySpinBox::setMaximum(), Gui::QuantitySpinBox::setMinimum(), Gui::QuantitySpinBox::setSingleStep(), Gui::QuantitySpinBox::setValue(), and verticalLayout.
Member Data Documentation
buttonLine
QToolButton* PartDesignGui::Ui_TaskDraftParameters::buttonLine
Referenced by retranslateUi(), and setupUi().
buttonPlane
QToolButton* PartDesignGui::Ui_TaskDraftParameters::buttonPlane
Referenced by retranslateUi(), and setupUi().
buttonRefAdd
QToolButton* PartDesignGui::Ui_TaskDraftParameters::buttonRefAdd
Referenced by retranslateUi(), and setupUi().
buttonRefRemove
QToolButton* PartDesignGui::Ui_TaskDraftParameters::buttonRefRemove
Referenced by retranslateUi(), and setupUi().
checkReverse
QCheckBox* PartDesignGui::Ui_TaskDraftParameters::checkReverse
Referenced by retranslateUi(), and setupUi().
draftAngle
Gui::QuantitySpinBox* PartDesignGui::Ui_TaskDraftParameters::draftAngle
Referenced by setupUi().
horizontalLayout
QHBoxLayout* PartDesignGui::Ui_TaskDraftParameters::horizontalLayout
Referenced by setupUi().
horizontalLayout_2
QHBoxLayout* PartDesignGui::Ui_TaskDraftParameters::horizontalLayout_2
Referenced by setupUi().
horizontalLayout_3
QHBoxLayout* PartDesignGui::Ui_TaskDraftParameters::horizontalLayout_3
Referenced by setupUi().
horizontalLayout_4
QHBoxLayout* PartDesignGui::Ui_TaskDraftParameters::horizontalLayout_4
Referenced by setupUi().
label
QLabel* PartDesignGui::Ui_TaskDraftParameters::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
lineLine
QLineEdit* PartDesignGui::Ui_TaskDraftParameters::lineLine
Referenced by setupUi().
linePlane
QLineEdit* PartDesignGui::Ui_TaskDraftParameters::linePlane
Referenced by setupUi().
listWidgetReferences
QListWidget* PartDesignGui::Ui_TaskDraftParameters::listWidgetReferences
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* PartDesignGui::Ui_TaskDraftParameters::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/PartDesign/Gui/ui_TaskDraftParameters.h