FreeCAD: MeshGui::Segmentation Class Reference
MeshGui::Segmentation Class Reference
#include <Segmentation.h>
Public Member Functions
void accept ()
Segmentation (Mesh::Feature *mesh, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~Segmentation ()
Protected Member Functions
void changeEvent (QEvent *e)
Constructor & Destructor Documentation
Segmentation()
Segmentation::Segmentation (Mesh::Feature * mesh, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
References MeshGui::Ui_Segmentation::checkBoxSmooth, MeshGui::Ui_Segmentation::crv1Free, MeshGui::Ui_Segmentation::crv2Free, MeshGui::Ui_Segmentation::crvCyl, MeshGui::Ui_Segmentation::crvSph, MeshGui::Ui_Segmentation::numCyl, MeshGui::Ui_Segmentation::numFree, MeshGui::Ui_Segmentation::numPln, MeshGui::Ui_Segmentation::numSph, and MeshGui::Ui_Segmentation::setupUi().
~Segmentation()
Segmentation::~Segmentation ()
Member Function Documentation
accept()
void Segmentation::accept (void)
References App::Document::addObject(), MeshGui::Ui_Segmentation::checkBoxSmooth, App::Document::commitTransaction(), MeshCore::MeshCurvature::ComputePerVertex(), MeshGui::Ui_Segmentation::crv1Free, MeshGui::Ui_Segmentation::crv2Free, MeshGui::Ui_Segmentation::crvCyl, MeshGui::Ui_Segmentation::crvSph, MeshCore::MeshSegmentAlgorithm::FindSegments(), Mesh::PropertyMeshKernel::finishEditing(), App::Application::getActiveDocument(), App::GetApplication(), MeshCore::MeshCurvature::GetCurvature(), App::DocumentObject::getNameInDocument(), App::PropertyString::getValue(), Mesh::PropertyMeshKernel::getValuePtr(), MeshGui::Ui_Segmentation::groupBoxCyl, MeshGui::Ui_Segmentation::groupBoxFree, MeshGui::Ui_Segmentation::groupBoxPln, MeshGui::Ui_Segmentation::groupBoxSph, App::DocumentObject::Label, Mesh::Feature::Mesh, MeshGui::Ui_Segmentation::numCyl, MeshGui::Ui_Segmentation::numFree, MeshGui::Ui_Segmentation::numPln, MeshGui::Ui_Segmentation::numSph, App::Document::openTransaction(), App::PropertyString::setValue(), MeshCore::LaplaceSmoothing::Smooth(), MeshGui::Ui_Segmentation::smoothSteps, Mesh::PropertyMeshKernel::startEditing(), Mesh::MeshObject::swap(), MeshGui::Ui_Segmentation::tol1Cyl, MeshGui::Ui_Segmentation::tol1Free, MeshGui::Ui_Segmentation::tol2Cyl, MeshGui::Ui_Segmentation::tol2Free, MeshGui::Ui_Segmentation::tolPln, and MeshGui::Ui_Segmentation::tolSph.
Referenced by MeshGui::TaskSegmentation::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void Segmentation::changeEvent (QEvent * e) protected
References MeshGui::Ui_Segmentation::retranslateUi().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/Gui/Segmentation.h
FreeCAD/src/Mod/Mesh/Gui/Segmentation.cpp