FreeCAD: SMDS_Mesh Class Reference
SMDS_Mesh Class Reference
#include <SMDS_Mesh.hxx>
Public Types
typedef std::vector< SMDS_MeshCell * > SetOfCells
typedef std::vector< SMDS_MeshNode * > SetOfNodes
Public Member Functions
virtual SMDS_Mesh0DElement * Add0DElement (const SMDS_MeshNode *n)
create a Mesh0DElement and add it to the current Mesh
virtual SMDS_Mesh0DElement * Add0DElementWithID (const SMDS_MeshNode *n, int ID)
Create a new Mesh0DElement and at it to the mesh.
virtual SMDS_Mesh0DElement * Add0DElementWithID (int n, int ID)
create a Mesh0DElement and add it to the current Mesh
virtual SMDS_BallElement * AddBall (const SMDS_MeshNode *n, double diameter)
create a Ball and add it to the current Mesh
virtual SMDS_BallElement * AddBallWithID (const SMDS_MeshNode *n, double diameter, int ID)
Create a new Ball and at it to the mesh.
virtual SMDS_BallElement * AddBallWithID (int n, double diameter, int ID)
create a Ball and add it to the current Mesh
virtual SMDS_MeshEdge * AddEdge (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2)
create a MeshEdge and add it to the current Mesh
virtual SMDS_MeshEdge * AddEdge (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n12)
virtual SMDS_MeshEdge * AddEdgeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n12, int ID)
virtual SMDS_MeshEdge * AddEdgeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, int ID)
Create a new edge and at it to the mesh.
virtual SMDS_MeshEdge * AddEdgeWithID (int n1, int n2, int ID)
create a MeshEdge and add it to the current Mesh
virtual SMDS_MeshEdge * AddEdgeWithID (int n1, int n2, int n12, int ID)
virtual SMDS_MeshFace * AddFace (const SMDS_MeshEdge *e1, const SMDS_MeshEdge *e2, const SMDS_MeshEdge *e3)
Add a triangle defined by its edges.
virtual SMDS_MeshFace * AddFace (const SMDS_MeshEdge *e1, const SMDS_MeshEdge *e2, const SMDS_MeshEdge *e3, const SMDS_MeshEdge *e4)
Add a quadrangle defined by its edges.
virtual SMDS_MeshFace * AddFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3)
Add a triangle defined by its nodes.
virtual SMDS_MeshFace * AddFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n31)
virtual SMDS_MeshFace * AddFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n31, const SMDS_MeshNode *nCenter)
virtual SMDS_MeshFace * AddFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4)
Add a quadrangle defined by its nodes.
virtual SMDS_MeshFace * AddFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41)
virtual SMDS_MeshFace * AddFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, const SMDS_MeshNode *nCenter)
virtual SMDS_MeshFace * AddFaceFromVtkIds (const std::vector< vtkIdType > &vtkNodeIds)
virtual SMDS_MeshFace * AddFaceFromVtkIdsWithID (const std::vector< vtkIdType > &vtkNodeIds, const int ID)
virtual SMDS_MeshFace * AddFaceWithID (const SMDS_MeshEdge *e1, const SMDS_MeshEdge *e2, const SMDS_MeshEdge *e3, const SMDS_MeshEdge *e4, int ID)
Add a quadrangle defined by its edges.
virtual SMDS_MeshFace * AddFaceWithID (const SMDS_MeshEdge *e1, const SMDS_MeshEdge *e2, const SMDS_MeshEdge *e3, int ID)
Add a triangle defined by its edges.
virtual SMDS_MeshFace * AddFaceWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n31, const SMDS_MeshNode *nCenter, int ID)
virtual SMDS_MeshFace * AddFaceWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n31, int ID)
virtual SMDS_MeshFace * AddFaceWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, const SMDS_MeshNode *nCenter, int ID)
virtual SMDS_MeshFace * AddFaceWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, int ID)
virtual SMDS_MeshFace * AddFaceWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, int ID)
Add a quadrangle defined by its nodes.
virtual SMDS_MeshFace * AddFaceWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, int ID)
Add a triangle defined by its nodes.
virtual SMDS_MeshFace * AddFaceWithID (int n1, int n2, int n3, int ID)
Add a triangle defined by its nodes IDs.
virtual SMDS_MeshFace * AddFaceWithID (int n1, int n2, int n3, int n12, int n23, int n31, int ID)
virtual SMDS_MeshFace * AddFaceWithID (int n1, int n2, int n3, int n12, int n23, int n31, int nCenter, int ID)
virtual SMDS_MeshFace * AddFaceWithID (int n1, int n2, int n3, int n4, int ID)
Add a quadrangle defined by its nodes IDs.
virtual SMDS_MeshFace * AddFaceWithID (int n1, int n2, int n3, int n4, int n12, int n23, int n34, int n41, int ID)
virtual SMDS_MeshFace * AddFaceWithID (int n1, int n2, int n3, int n4, int n12, int n23, int n34, int n41, int nCenter, int ID)
virtual SMDS_MeshNode * AddNode (double x, double y, double z)
create a MeshNode and add it to the current Mesh An ID is automatically assigned to the node.
virtual SMDS_MeshNode * AddNodeWithID (double x, double y, double z, int ID)
create a MeshNode and add it to the current Mesh
virtual SMDS_MeshFace * AddPolygonalFace (const std::vector< const SMDS_MeshNode * > &nodes)
Add a polygon defined by its nodes.
virtual SMDS_MeshFace * AddPolygonalFaceWithID (const std::vector< const SMDS_MeshNode * > &nodes, const int ID)
Add a polygon defined by its nodes.
virtual SMDS_MeshFace * AddPolygonalFaceWithID (const std::vector< int > &nodes_ids, const int ID)
Add a polygon defined by its nodes IDs.
virtual SMDS_MeshVolume * AddPolyhedralVolume (const std::vector< const SMDS_MeshNode * > &nodes, const std::vector< int > &quantities)
Create a new polyhedral volume and add it to the mesh.
virtual SMDS_MeshVolume * AddPolyhedralVolumeWithID (const std::vector< const SMDS_MeshNode * > &nodes, const std::vector< int > &quantities, const int ID)
Create a new polyhedral volume and add it to the mesh.
virtual SMDS_MeshVolume * AddPolyhedralVolumeWithID (const std::vector< int > &nodes_ids, const std::vector< int > &quantities, const int ID)
Create a new polyhedral volume and add it to the mesh.
virtual SMDS_MeshFace * AddQuadPolygonalFace (const std::vector< const SMDS_MeshNode * > &nodes)
Add a quadratic polygon defined by its nodes.
virtual SMDS_MeshFace * AddQuadPolygonalFaceWithID (const std::vector< const SMDS_MeshNode * > &nodes, const int ID)
Add a quadratic polygon defined by its nodes.
virtual SMDS_MeshFace * AddQuadPolygonalFaceWithID (const std::vector< int > &nodes_ids, const int ID)
Add a quadratic polygon defined by its nodes IDs.
SMDS_Mesh * AddSubMesh ()
Create a submesh and add it to the current mesh.
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshFace *f1, const SMDS_MeshFace *f2, const SMDS_MeshFace *f3, const SMDS_MeshFace *f4)
Create a new tetrahedron defined by its faces and add it to the mesh.
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshFace *f1, const SMDS_MeshFace *f2, const SMDS_MeshFace *f3, const SMDS_MeshFace *f4, const SMDS_MeshFace *f5)
Create a new pyramid defined by its faces and add it to the mesh.
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshFace *f1, const SMDS_MeshFace *f2, const SMDS_MeshFace *f3, const SMDS_MeshFace *f4, const SMDS_MeshFace *f5, const SMDS_MeshFace *f6)
Create a new prism defined by its faces and add it to the mesh.
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4)
Create a new tetrahedron and add it to the mesh.
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n31, const SMDS_MeshNode *n14, const SMDS_MeshNode *n24, const SMDS_MeshNode *n34)
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5)
Create a new pyramid and add it to the mesh.
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, const SMDS_MeshNode *n15, const SMDS_MeshNode *n25, const SMDS_MeshNode *n35, const SMDS_MeshNode *n45)
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6)
Create a new prism and add it to the mesh.
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n31, const SMDS_MeshNode *n45, const SMDS_MeshNode *n56, const SMDS_MeshNode *n64, const SMDS_MeshNode *n14, const SMDS_MeshNode *n25, const SMDS_MeshNode *n36)
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8)
Create a new hexahedron and add it to the mesh.
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, const SMDS_MeshNode *n56, const SMDS_MeshNode *n67, const SMDS_MeshNode *n78, const SMDS_MeshNode *n85, const SMDS_MeshNode *n15, const SMDS_MeshNode *n26, const SMDS_MeshNode *n37, const SMDS_MeshNode *n48)
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, const SMDS_MeshNode *n56, const SMDS_MeshNode *n67, const SMDS_MeshNode *n78, const SMDS_MeshNode *n85, const SMDS_MeshNode *n15, const SMDS_MeshNode *n26, const SMDS_MeshNode *n37, const SMDS_MeshNode *n48, const SMDS_MeshNode *n1234, const SMDS_MeshNode *n1256, const SMDS_MeshNode *n2367, const SMDS_MeshNode *n3478, const SMDS_MeshNode *n1458, const SMDS_MeshNode *n5678, const SMDS_MeshNode *nCenter)
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8, const SMDS_MeshNode *n9, const SMDS_MeshNode *n10, const SMDS_MeshNode *n11, const SMDS_MeshNode *n12)
Create a new hexagonal prism and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeFromVtkIds (const std::vector< vtkIdType > &vtkNodeIds)
virtual SMDS_MeshVolume * AddVolumeFromVtkIdsWithID (const std::vector< vtkIdType > &vtkNodeIds, const int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshFace *f1, const SMDS_MeshFace *f2, const SMDS_MeshFace *f3, const SMDS_MeshFace *f4, const SMDS_MeshFace *f5, const SMDS_MeshFace *f6, int ID)
Create a new prism defined by its faces and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshFace *f1, const SMDS_MeshFace *f2, const SMDS_MeshFace *f3, const SMDS_MeshFace *f4, const SMDS_MeshFace *f5, int ID)
Create a new pyramid defined by its faces and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshFace *f1, const SMDS_MeshFace *f2, const SMDS_MeshFace *f3, const SMDS_MeshFace *f4, int ID)
Create a new tetrahedron defined by its faces and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n31, const SMDS_MeshNode *n14, const SMDS_MeshNode *n24, const SMDS_MeshNode *n34, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, const SMDS_MeshNode *n15, const SMDS_MeshNode *n25, const SMDS_MeshNode *n35, const SMDS_MeshNode *n45, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n31, const SMDS_MeshNode *n45, const SMDS_MeshNode *n56, const SMDS_MeshNode *n64, const SMDS_MeshNode *n14, const SMDS_MeshNode *n25, const SMDS_MeshNode *n36, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, const SMDS_MeshNode *n56, const SMDS_MeshNode *n67, const SMDS_MeshNode *n78, const SMDS_MeshNode *n85, const SMDS_MeshNode *n15, const SMDS_MeshNode *n26, const SMDS_MeshNode *n37, const SMDS_MeshNode *n48, const SMDS_MeshNode *n1234, const SMDS_MeshNode *n1256, const SMDS_MeshNode *n2367, const SMDS_MeshNode *n3478, const SMDS_MeshNode *n1458, const SMDS_MeshNode *n5678, const SMDS_MeshNode *nCenter, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, const SMDS_MeshNode *n56, const SMDS_MeshNode *n67, const SMDS_MeshNode *n78, const SMDS_MeshNode *n85, const SMDS_MeshNode *n15, const SMDS_MeshNode *n26, const SMDS_MeshNode *n37, const SMDS_MeshNode *n48, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8, const SMDS_MeshNode *n9, const SMDS_MeshNode *n10, const SMDS_MeshNode *n11, const SMDS_MeshNode *n12, int ID)
Create a new hexagonal prism and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8, int ID)
Create a new hexahedron and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, int ID)
Create a new prism and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, int ID)
Create a new pyramid and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, int ID)
Create a new tetrahedron and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int ID)
Create a new tetrahedron and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n12, int n23, int n31, int n14, int n24, int n34, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int ID)
Create a new pyramid and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n12, int n23, int n34, int n41, int n15, int n25, int n35, int n45, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int ID)
Create a new prism and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int n12, int n23, int n31, int n45, int n56, int n64, int n14, int n25, int n36, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int ID)
Create a new hexahedron and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n12, int n23, int n34, int n41, int n56, int n67, int n78, int n85, int n15, int n26, int n37, int n48, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n12, int n23, int n34, int n41, int n56, int n67, int n78, int n85, int n15, int n26, int n37, int n48, int n1234, int n1256, int n2367, int n3478, int n1458, int n5678, int nCenter, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n9, int n10, int n11, int n12, int ID)
Create a new hexagonal prism and add it to the mesh.
void adjustStructure ()
bool ChangeElementNodes (const SMDS_MeshElement *elem, const SMDS_MeshNode *nodes[], const int nbnodes)
bool ChangePolyhedronNodes (const SMDS_MeshElement *elem, const std::vector< const SMDS_MeshNode * > &nodes, const std::vector< int > &quantities)
virtual void Clear ()
Clear all data.
virtual void compactMesh ()
bool Contains (const SMDS_MeshElement *elem) const
void DebugStats () const
void Dump0DElements () const
void DumpEdges () const
void DumpFaces () const
void dumpGrid (string ficdump="dumpGrid")
void DumpNodes () const
void DumpVolumes () const
virtual SMDS_EdgeIteratorPtr edgesIterator (bool idInceasingOrder=false) const
Return an iterator on edges of the current mesh.
virtual SMDS_ElemIteratorPtr elementEntityIterator (SMDSAbs_EntityType type) const
virtual SMDS_ElemIteratorPtr elementGeomIterator (SMDSAbs_GeometryType type) const
virtual SMDS_ElemIteratorPtr elementsIterator (SMDSAbs_ElementType type=SMDSAbs_All) const
Return an iterator on elements of the current mesh factory.
virtual SMDS_FaceIteratorPtr facesIterator (bool idInceasingOrder=false) const
Return an iterator on faces of the current mesh.
const SMDS_Mesh0DElement * Find0DElement (int idnode) const
const SMDS_BallElement * FindBall (int idnode) const
const SMDS_MeshEdge * FindEdge (int idnode1, int idnode2) const
const SMDS_MeshEdge * FindEdge (int idnode1, int idnode2, int idnode3) const
const SMDS_MeshElement * FindElement (int IDelem) const
const SMDS_MeshFace * FindFace (const std::vector< int > &nodes_ids) const
const SMDS_MeshFace * FindFace (int idnode1, int idnode2, int idnode3) const
const SMDS_MeshFace * FindFace (int idnode1, int idnode2, int idnode3, int idnode4) const
const SMDS_MeshFace * FindFace (int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6) const
const SMDS_MeshFace * FindFace (int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6, int idnode7, int idnode8) const
const SMDS_MeshNode * FindNode (int idnode) const
Return the node whose SMDS ID is 'ID'.
const SMDS_MeshNode * FindNodeVtk (int idnode) const
Return the node whose VTK ID is 'vtkId'.
int fromVtkToSmds (int vtkid)
SMDSAbs_ElementType GetElementType (const int id, const bool iselem) const
SMDS_UnstructuredGrid * getGrid ()
actual nodes coordinates, cells definition and reverse connectivity are stored in a vtkUnstructuredGrid
double getMaxDim ()
int getMeshId ()
const SMDS_MeshInfo & GetMeshInfo () const
VTK_MTIME_TYPE GetMTime () const
get last modification timeStamp
bool hasConstructionEdges ()
Return true if this mesh create faces with edges.
bool hasConstructionFaces ()
Return true if this mesh create volumes with faces A false returned value mean that volumes are created with nodes or edges.
bool hasInverseElements ()
Return true if nodes are linked to the finit elements, they are belonging to.
void incrementCellsCapacity (int nbCells)
void incrementNodesCapacity (int nbNodes)
bool isCompacted ()
int MaxElementID () const
int MaxNodeID () const
int MinElementID () const
int MinNodeID () const
void Modified ()
modification that needs compact structure and redraw
virtual void MoveNode (const SMDS_MeshNode *n, double x, double y, double z)
virtual int Nb0DElements () const
Return the number of 0D elements.
virtual int NbBalls () const
Return the number of 0D elements.
virtual int NbEdges () const
Return the number of edges (including construction edges)
virtual int NbFaces () const
Return the number of faces (including construction faces)
virtual int NbNodes () const
Return the number of nodes.
virtual int NbSubMesh () const
Return the number of child mesh of this mesh.
virtual int NbVolumes () const
Return the number of volumes.
virtual SMDS_NodeIteratorPtr nodesIterator (bool idInceasingOrder=false) const
Return an iterator on nodes of the current mesh factory.
virtual void Remove0DElement (const SMDS_Mesh0DElement *elem0d)
Remove an edge and all the elements which own this edge.
virtual void RemoveEdge (const SMDS_MeshEdge *edge)
Remove an edge and all the elements which own this edge.
virtual void RemoveElement (const SMDS_MeshElement *elem, bool removenodes=false)
virtual void RemoveElement (const SMDS_MeshElement *elem, std::list< const SMDS_MeshElement * > &removedElems, std::list< const SMDS_MeshElement * > &removedNodes, const bool removenodes=false)
virtual void RemoveFace (const SMDS_MeshFace *face)
Remove an face and all the elements which own this face.
virtual void RemoveFreeElement (const SMDS_MeshElement *elem)
virtual bool RemoveFromParent ()
virtual void RemoveNode (const SMDS_MeshNode *node)
Remove a node and all the elements which own this node.
virtual bool RemoveSubMesh (const SMDS_Mesh *aMesh)
virtual void RemoveVolume (const SMDS_MeshVolume *volume)
Remove a volume.
virtual void Renumber (const bool isNodes, const int startID=1, const int deltaID=1)
void setConstructionEdges (bool)
Make this mesh creating construction edges (see hasConstructionEdges)
void setConstructionFaces (bool)
Make this mesh creating construction faces (see hasConstructionFaces)
void setInverseElements (bool)
Make this mesh creating link from nodes to elements (see hasInverseElements)
void setMyModified ()
low level modification: add, change or remove node or element
SMDS_Mesh ()
Create a new mesh object.
void updateBoundingBox ()
void updateNodeMinMax ()
virtual SMDS_VolumeIteratorPtr volumesIterator (bool idInceasingOrder=false) const
Return an iterator on volumes of the current mesh.
virtual ~SMDS_Mesh ()
Destroy the mesh and all its elements All pointer on elements owned by this mesh become illegals.
Public Member Functions inherited from SMDS_MeshObject
virtual ~SMDS_MeshObject ()
Static Public Member Functions
static int CheckMemory (const bool doNotRaise=false)
Raise an exception if free memory (ram+swap) too low.
static const SMDS_Mesh0DElement * Find0DElement (const SMDS_MeshNode *n)
static const SMDS_BallElement * FindBall (const SMDS_MeshNode *n)
static const SMDS_MeshEdge * FindEdge (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2)
static const SMDS_MeshEdge * FindEdge (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3)
static const SMDS_MeshElement * FindElement (const std::vector< const SMDS_MeshNode * > &nodes, const SMDSAbs_ElementType type=SMDSAbs_All, const bool noMedium=true)
Return element based on all given nodes.
static const SMDS_MeshFace * FindFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3)
static const SMDS_MeshFace * FindFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4)
static const SMDS_MeshFace * FindFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6)
static const SMDS_MeshFace * FindFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8)
static const SMDS_MeshFace * FindFace (const std::vector< const SMDS_MeshNode * > &nodes)
Static Public Attributes
static int chunkSize = 1024
Protected Member Functions
void addChildrenWithNodes (std::set< const SMDS_MeshElement * > &setOfChildren, const SMDS_MeshElement *element, std::set< const SMDS_MeshElement * > &nodes)
Find the children of an element that are made of given nodes.
void adjustBoundingBox (double x, double y, double z)
void adjustmyCellsCapacity (int ID)
SMDS_MeshFace * createQuadrangle (const SMDS_MeshNode *node1, const SMDS_MeshNode *node2, const SMDS_MeshNode *node3, const SMDS_MeshNode *node4, int ID)
Create a quadrangle and add it to the current mesh.
SMDS_MeshFace * createTriangle (const SMDS_MeshNode *node1, const SMDS_MeshNode *node2, const SMDS_MeshNode *node3, int ID)
Create a triangle and add it to the current mesh.
SMDS_MeshEdge * FindEdgeOrCreate (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2)
SMDS_MeshFace * FindFaceOrCreate (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3)
SMDS_MeshFace * FindFaceOrCreate (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4)
bool registerElement (int ID, SMDS_MeshElement *element)
Registers element with the given ID, maintains inverse connections.
SMDS_Mesh (SMDS_Mesh *parent)
Create a new child mesh Note that the tree structure of SMDS_Mesh seems to be unused in this version (2003-09-08) of SMESH.
Protected Attributes
ObjectPool< SMDS_BallElement > * myBallPool
std::vector< int > myCellIdVtkToSmds
for cells only: index = ID in vtkUnstructuredGrid, value = ID for SMDS users
SetOfCells myCells
SMDS_MeshCells refer to vtk cells (vtk id != index in myCells),store reference to this mesh, and sub-shape.
std::list< SMDS_Mesh * > myChildren
unsigned long myCompactTime
ObjectPool< SMDS_VtkEdge > * myEdgePool
SMDS_MeshElementIDFactory * myElementIDFactory
ObjectPool< SMDS_VtkFace > * myFacePool
SMDS_UnstructuredGrid * myGrid
actual nodes coordinates, cells definition and reverse connectivity are stored in a vtkUnstructuredGrid
bool myHasConstructionEdges
bool myHasConstructionFaces
bool myHasInverseElements
SMDS_MeshInfo myInfo
int myMeshId
index of this SMDS_mesh in the static vector<SMDS_Mesh*> _meshList
bool myModified
any add, remove or change of node or cell
unsigned long myModifTime
use a counter to keep track of modifications
SMDS_MeshNodeIDFactory * myNodeIDFactory
std::vector< vtkIdType > myNodeIds
a buffer to speed up elements addition by excluding some memory allocation
int myNodeMax
int myNodeMin
ObjectPool< SMDS_MeshNode > * myNodePool
Small objects like SMDS_MeshNode are allocated by chunks to limit memory costs of new.
SetOfNodes myNodes
SMDS_MeshNodes refer to vtk nodes (vtk id = index in myNodes),store reference to this mesh, and sub-shape.
SMDS_Mesh * myParent
ObjectPool< SMDS_VtkVolume > * myVolumePool
Small objects like SMDS_VtkVolume are allocated by chunks to limit memory costs of new.
double xmax
double xmin
double ymax
double ymin
double zmax
double zmin
Friends
class SMDS_MeshElementIDFactory
class SMDS_MeshIDFactory
class SMDS_MeshNode
class SMDS_MeshNodeIDFactory
class SMDS_MeshVolumeVtkNodes
Member Typedef Documentation
SetOfCells
typedef std::vector<SMDS_MeshCell *> SMDS_Mesh::SetOfCells
SetOfNodes
typedef std::vector<SMDS_MeshNode *> SMDS_Mesh::SetOfNodes
Constructor & Destructor Documentation
SMDS_Mesh() [1/2]
SMDS_Mesh::SMDS_Mesh ()
Create a new mesh object.
References SMDS_UnstructuredGrid::BuildLinks(), chunkSize, Modified(), myBallPool, myCellIdVtkToSmds, myCells, myEdgePool, myElementIDFactory, myFacePool, myGrid, myMeshId, myNodeIDFactory, myNodePool, myNodes, myVolumePool, SMDS_UnstructuredGrid::New(), SMDS_MeshIDFactory::SetMesh(), and SMDS_UnstructuredGrid::setSMDS_mesh().
Referenced by AddSubMesh().
~SMDS_Mesh()
SMDS_Mesh::~SMDS_Mesh () virtual
Destroy the mesh and all its elements All pointer on elements owned by this mesh become illegals.
References elementsIterator(), SMDS_MeshElement::GetID(), SMDS_MeshElement::getVtkId(), myBallPool, myChildren, myEdgePool, myElementIDFactory, myFacePool, myGrid, myNodeIDFactory, myNodePool, myParent, myVolumePool, nodesIterator(), SMDS_SpacePosition::originSpacePosition(), SMDS_MeshElementIDFactory::ReleaseID(), SMDS_MeshNodeIDFactory::ReleaseID(), and SMDS_MeshNode::SetPosition().
SMDS_Mesh() [2/2]
SMDS_Mesh::SMDS_Mesh (SMDS_Mesh * parent) protected
Create a new child mesh Note that the tree structure of SMDS_Mesh seems to be unused in this version (2003-09-08) of SMESH.
Member Function Documentation
Add0DElement()
SMDS_Mesh0DElement * SMDS_Mesh::Add0DElement (const SMDS_MeshNode * node) virtual
create a Mesh0DElement and add it to the current Mesh
Returns
: The created Mesh0DElement
Reimplemented in SMESHDS_Mesh.
References Add0DElementWithID(), SMDS_MeshElementIDFactory::GetFreeID(), and myElementIDFactory.
Referenced by SMESHDS_Mesh::Add0DElement().
Add0DElementWithID() [1/2]
SMDS_Mesh0DElement * SMDS_Mesh::Add0DElementWithID (const SMDS_MeshNode * n, int ID) virtual
Create a new Mesh0DElement and at it to the mesh.
Parameters
idnode ID of the node
ID ID of the 0D element to create
Returns
The created 0D element or NULL if an element with this ID already exists or if input node is not found.
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), SMDS_MeshElementIDFactory::BindID(), CheckMemory(), myCells, myElementIDFactory, myInfo, and Nb0DElements().
Add0DElementWithID() [2/2]
SMDS_Mesh0DElement * SMDS_Mesh::Add0DElementWithID (int idnode, int ID) virtual
create a Mesh0DElement and add it to the current Mesh
Returns
: The created Mesh0DElement
Reimplemented in SMESHDS_Mesh.
References SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
Referenced by Add0DElement(), and SMESHDS_Mesh::Add0DElementWithID().
AddBall()
SMDS_BallElement * SMDS_Mesh::AddBall (const SMDS_MeshNode * node, double diameter) virtual
create a Ball and add it to the current Mesh
Returns
: The created Ball
Reimplemented in SMESHDS_Mesh.
References AddBallWithID(), SMDS_MeshElementIDFactory::GetFreeID(), and myElementIDFactory.
Referenced by SMESHDS_Mesh::AddBall().
AddBallWithID() [1/2]
SMDS_BallElement * SMDS_Mesh::AddBallWithID (const SMDS_MeshNode * n, double diameter, int ID) virtual
Create a new Ball and at it to the mesh.
Parameters
idnode ID of the node
ID ID of the 0D element to create
Returns
The created 0D element or NULL if an element with this ID already exists or if input node is not found.
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), CheckMemory(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), SMDS_BallElement::init(), myBallPool, myCells, myGrid, myInfo, NbBalls(), and registerElement().
AddBallWithID() [2/2]
SMDS_BallElement * SMDS_Mesh::AddBallWithID (int idnode, double diameter, int ID) virtual
create a Ball and add it to the current Mesh
Returns
: The created Ball
Reimplemented in SMESHDS_Mesh.
References SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
Referenced by AddBall(), and SMESHDS_Mesh::AddBallWithID().
addChildrenWithNodes()
void SMDS_Mesh::addChildrenWithNodes (std::set< const SMDS_MeshElement * > & setOfChildren, const SMDS_MeshElement * element, std::set< const SMDS_MeshElement * > & nodes) protected
Find the children of an element that are made of given nodes.
Parameters
setOfChildren The set in which matching children will be inserted
element The element were to search matching children
nodes The nodes that the children must have to be selected
References SMDS_MeshElement::edgesIterator(), SMDS_MeshElement::facesIterator(), SMDS_MeshElement::GetType(), hasConstructionEdges(), hasConstructionFaces(), and SMDS_MeshElement::nodesIterator().
Referenced by RemoveElement().
AddEdge() [1/2]
SMDS_MeshEdge * SMDS_Mesh::AddEdge (const SMDS_MeshNode * node1, const SMDS_MeshNode * node2) virtual
create a MeshEdge and add it to the current Mesh
Returns
: The created MeshEdge
Reimplemented in SMESHDS_Mesh.
References AddEdgeWithID(), SMDS_MeshElementIDFactory::GetFreeID(), and myElementIDFactory.
Referenced by SMESHDS_Mesh::AddEdge().
AddEdge() [2/2]
SMDS_MeshEdge * SMDS_Mesh::AddEdge (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n12) virtual
Reimplemented in SMESHDS_Mesh.
References AddEdgeWithID(), SMDS_MeshElementIDFactory::GetFreeID(), and myElementIDFactory.
AddEdgeWithID() [1/4]
SMDS_MeshEdge * SMDS_Mesh::AddEdgeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n12, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), SMDS_VtkEdge::init(), myCells, myEdgePool, myGrid, myInfo, myNodeIds, and registerElement().
AddEdgeWithID() [2/4]
SMDS_MeshEdge * SMDS_Mesh::AddEdgeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, int ID) virtual
Create a new edge and at it to the mesh.
Parameters
idnode1 ID of the first node
idnode2 ID of the second node
ID ID of the edge to create
Returns
The created edge or NULL if an element with this ID already exists or if input nodes are not found.
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), SMDS_VtkEdge::init(), myCells, myEdgePool, myGrid, myInfo, and registerElement().
AddEdgeWithID() [3/4]
SMDS_MeshEdge * SMDS_Mesh::AddEdgeWithID (int idnode1, int idnode2, int ID) virtual
create a MeshEdge and add it to the current Mesh
Returns
: The created MeshEdge
Reimplemented in SMESHDS_Mesh.
References SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
Referenced by AddEdge(), SMESHDS_Mesh::AddEdgeWithID(), and AddEdgeWithID().
AddEdgeWithID() [4/4]
SMDS_MeshEdge * SMDS_Mesh::AddEdgeWithID (int n1, int n2, int n12, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References AddEdgeWithID(), SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
AddFace() [1/8]
SMDS_MeshFace * SMDS_Mesh::AddFace (const SMDS_MeshEdge * e1, const SMDS_MeshEdge * e2, const SMDS_MeshEdge * e3) virtual
Add a triangle defined by its edges.
An ID is automatically assigned to the Created face
References AddFaceWithID(), SMDS_MeshElementIDFactory::GetFreeID(), hasConstructionEdges(), and myElementIDFactory.
AddFace() [2/8]
SMDS_MeshFace * SMDS_Mesh::AddFace (const SMDS_MeshEdge * e1, const SMDS_MeshEdge * e2, const SMDS_MeshEdge * e3, const SMDS_MeshEdge * e4) virtual
Add a quadrangle defined by its edges.
An ID is automatically assigned to the Created face
References AddFaceWithID(), SMDS_MeshElementIDFactory::GetFreeID(), hasConstructionEdges(), and myElementIDFactory.
AddFace() [3/8]
SMDS_MeshFace * SMDS_Mesh::AddFace (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3) virtual
Add a triangle defined by its nodes.
An ID is automatically affected to the Created face
Reimplemented in SMESHDS_Mesh.
References AddFaceWithID(), SMDS_MeshElementIDFactory::GetFreeID(), and myElementIDFactory.
Referenced by SMESHDS_Mesh::AddFace().
AddFace() [4/8]
SMDS_MeshFace * SMDS_Mesh::AddFace (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n31) virtual
Reimplemented in SMESHDS_Mesh.
References AddFaceWithID(), SMDS_MeshElementIDFactory::GetFreeID(), and myElementIDFactory.
AddFace() [5/8]
SMDS_MeshFace * SMDS_Mesh::AddFace (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n31, const SMDS_MeshNode * nCenter) virtual
Reimplemented in SMESHDS_Mesh.
References AddFaceWithID(), SMDS_MeshElementIDFactory::GetFreeID(), and myElementIDFactory.
AddFace() [6/8]
SMDS_MeshFace * SMDS_Mesh::AddFace (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4) virtual
Add a quadrangle defined by its nodes.
An ID is automatically affected to the created face
Reimplemented in SMESHDS_Mesh.
References AddFaceWithID(), SMDS_MeshElementIDFactory::GetFreeID(), and myElementIDFactory.
AddFace() [7/8]
SMDS_MeshFace * SMDS_Mesh::AddFace (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41) virtual
Reimplemented in SMESHDS_Mesh.
References AddFaceWithID(), SMDS_MeshElementIDFactory::GetFreeID(), and myElementIDFactory.
AddFace() [8/8]
SMDS_MeshFace * SMDS_Mesh::AddFace (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, const SMDS_MeshNode * nCenter) virtual
Reimplemented in SMESHDS_Mesh.
References AddFaceWithID(), SMDS_MeshElementIDFactory::GetFreeID(), and myElementIDFactory.
AddFaceFromVtkIds()
SMDS_MeshFace * SMDS_Mesh::AddFaceFromVtkIds (const std::vector< vtkIdType > & vtkNodeIds) virtual
References AddFaceFromVtkIdsWithID(), SMDS_MeshElementIDFactory::GetFreeID(), myElementIDFactory, and SMDS_MeshElementIDFactory::ReleaseID().
Referenced by SMESH_MeshEditor::DoubleNodesOnGroupBoundaries().
AddFaceFromVtkIdsWithID()
SMDS_MeshFace * SMDS_Mesh::AddFaceFromVtkIdsWithID (const std::vector< vtkIdType > & vtkNodeIds, const int ID) virtual
References adjustmyCellsCapacity(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), SMDS_VtkFace::GetVtkType(), SMDS_VtkFace::init(), myCells, myFacePool, myGrid, myInfo, and registerElement().
Referenced by AddFaceFromVtkIds().
AddFaceWithID() [1/14]
SMDS_MeshFace * SMDS_Mesh::AddFaceWithID (const SMDS_MeshEdge * e1, const SMDS_MeshEdge * e2, const SMDS_MeshEdge * e3, const SMDS_MeshEdge * e4, int ID) virtual
Add a quadrangle defined by its edges.
References adjustmyCellsCapacity(), CheckMemory(), SMDS_MeshElementIDFactory::GetFreeID(), hasConstructionEdges(), myCells, myElementIDFactory, myInfo, NbFaces(), and registerElement().
AddFaceWithID() [2/14]
SMDS_MeshFace * SMDS_Mesh::AddFaceWithID (const SMDS_MeshEdge * e1, const SMDS_MeshEdge * e2, const SMDS_MeshEdge * e3, int ID) virtual
Add a triangle defined by its edges.
References adjustmyCellsCapacity(), CheckMemory(), SMDS_MeshElementIDFactory::GetFreeID(), hasConstructionEdges(), myCells, myElementIDFactory, myInfo, NbFaces(), and registerElement().
AddFaceWithID() [3/14]
SMDS_MeshFace * SMDS_Mesh::AddFaceWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n31, const SMDS_MeshNode * nCenter, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionEdges(), SMDS_VtkFace::init(), myCells, myFacePool, myGrid, myInfo, myNodeIds, and registerElement().
AddFaceWithID() [4/14]
SMDS_MeshFace * SMDS_Mesh::AddFaceWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n31, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionEdges(), SMDS_VtkFace::init(), myCells, myFacePool, myGrid, myInfo, myNodeIds, and registerElement().
AddFaceWithID() [5/14]
SMDS_MeshFace * SMDS_Mesh::AddFaceWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, const SMDS_MeshNode * nCenter, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionEdges(), SMDS_VtkFace::init(), myCells, myFacePool, myGrid, myInfo, myNodeIds, and registerElement().
AddFaceWithID() [6/14]
SMDS_MeshFace * SMDS_Mesh::AddFaceWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionEdges(), SMDS_VtkFace::init(), myCells, myFacePool, myGrid, myInfo, myNodeIds, and registerElement().
AddFaceWithID() [7/14]
SMDS_MeshFace * SMDS_Mesh::AddFaceWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, int ID) virtual
Add a quadrangle defined by its nodes.
Reimplemented in SMESHDS_Mesh.
References createQuadrangle().
AddFaceWithID() [8/14]
SMDS_MeshFace * SMDS_Mesh::AddFaceWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, int ID) virtual
Add a triangle defined by its nodes.
Reimplemented in SMESHDS_Mesh.
References createTriangle().
AddFaceWithID() [9/14]
SMDS_MeshFace * SMDS_Mesh::AddFaceWithID (int n1, int n2, int n3, int ID) virtual
Add a triangle defined by its nodes IDs.
Reimplemented in SMESHDS_Mesh.
References SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
Referenced by AddFace(), SMESHDS_Mesh::AddFaceWithID(), and AddFaceWithID().
AddFaceWithID() [10/14]
SMDS_MeshFace * SMDS_Mesh::AddFaceWithID (int n1, int n2, int n3, int n12, int n23, int n31, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References AddFaceWithID(), SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
AddFaceWithID() [11/14]
SMDS_MeshFace * SMDS_Mesh::AddFaceWithID (int n1, int n2, int n3, int n12, int n23, int n31, int nCenter, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References AddFaceWithID(), SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
AddFaceWithID() [12/14]
SMDS_MeshFace * SMDS_Mesh::AddFaceWithID (int n1, int n2, int n3, int n4, int ID) virtual
Add a quadrangle defined by its nodes IDs.
Reimplemented in SMESHDS_Mesh.
References AddFaceWithID(), SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
AddFaceWithID() [13/14]
SMDS_MeshFace * SMDS_Mesh::AddFaceWithID (int n1, int n2, int n3, int n4, int n12, int n23, int n34, int n41, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References AddFaceWithID(), SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
AddFaceWithID() [14/14]
SMDS_MeshFace * SMDS_Mesh::AddFaceWithID (int n1, int n2, int n3, int n4, int n12, int n23, int n34, int n41, int nCenter, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References AddFaceWithID(), SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
AddNode()
SMDS_MeshNode * SMDS_Mesh::AddNode (double x, double y, double z) virtual
create a MeshNode and add it to the current Mesh An ID is automatically assigned to the node.
Returns
: The created node
Reimplemented in SMESHDS_Mesh.
References AddNodeWithID(), SMDS_MeshNodeIDFactory::GetFreeID(), and myNodeIDFactory.
Referenced by SMESHDS_Mesh::AddNode().
AddNodeWithID()
SMDS_MeshNode * SMDS_Mesh::AddNodeWithID (double x, double y, double z, int ID) virtual
create a MeshNode and add it to the current Mesh
Parameters
ID : The ID of the MeshNode to create
Returns
: The created node or NULL if a node with this ID already exists
Reimplemented in SMESHDS_Mesh.
References adjustBoundingBox(), SMDS_MeshIDFactory::adjustMaxId(), SMDS_MeshNodeIDFactory::BindID(), chunkSize, SMDS_MeshNodeIDFactory::GetFreeID(), ObjectPool< X >::getNew(), SMDS_MeshNode::init(), SMDS_MeshNodeIDFactory::MeshElement(), myInfo, myMeshId, myModified, myNodeIDFactory, myNodePool, and myNodes.
Referenced by AddNode(), and SMESHDS_Mesh::AddNodeWithID().
AddPolygonalFace()
SMDS_MeshFace * SMDS_Mesh::AddPolygonalFace (const std::vector< const SMDS_MeshNode * > & nodes) virtual
Add a polygon defined by its nodes.
An ID is automatically affected to the created face.
Reimplemented in SMESHDS_Mesh.
References AddPolygonalFaceWithID(), SMDS_MeshElementIDFactory::GetFreeID(), and myElementIDFactory.
Referenced by SMESHDS_Mesh::AddPolygonalFace().
AddPolygonalFaceWithID() [1/2]
SMDS_MeshFace * SMDS_Mesh::AddPolygonalFaceWithID (const std::vector< const SMDS_MeshNode * > & nodes, const int ID) virtual
Add a polygon defined by its nodes.
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), CheckMemory(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionEdges(), SMDS_VtkFace::initPoly(), myCells, myFacePool, myGrid, myInfo, myNodeIds, NbFaces(), and registerElement().
AddPolygonalFaceWithID() [2/2]
SMDS_MeshFace * SMDS_Mesh::AddPolygonalFaceWithID (const std::vector< int > & nodes_ids, const int ID) virtual
Add a polygon defined by its nodes IDs.
Reimplemented in SMESHDS_Mesh.
References SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
Referenced by AddPolygonalFace(), and SMESHDS_Mesh::AddPolygonalFaceWithID().
AddPolyhedralVolume()
SMDS_MeshVolume * SMDS_Mesh::AddPolyhedralVolume (const std::vector< const SMDS_MeshNode * > & nodes, const std::vector< int > & quantities) virtual
Create a new polyhedral volume and add it to the mesh.
Returns
The created volume
Reimplemented in SMESHDS_Mesh.
References AddPolyhedralVolumeWithID(), SMDS_MeshElementIDFactory::GetFreeID(), myElementIDFactory, and SMDS_MeshElementIDFactory::ReleaseID().
Referenced by SMESHDS_Mesh::AddPolyhedralVolume().
AddPolyhedralVolumeWithID() [1/2]
SMDS_MeshVolume * SMDS_Mesh::AddPolyhedralVolumeWithID (const std::vector< const SMDS_MeshNode * > & nodes, const std::vector< int > & quantities, const int ID) virtual
Create a new polyhedral volume and add it to the mesh.
Parameters
ID The ID of the new volume
Returns
The created volume
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), CheckMemory(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionEdges(), hasConstructionFaces(), SMDS_VtkVolume::initPoly(), myCells, myGrid, myInfo, myNodeIds, myVolumePool, NbVolumes(), and registerElement().
AddPolyhedralVolumeWithID() [2/2]
SMDS_MeshVolume * SMDS_Mesh::AddPolyhedralVolumeWithID (const std::vector< int > & nodes_ids, const std::vector< int > & quantities, const int ID) virtual
Create a new polyhedral volume and add it to the mesh.
Parameters
ID The ID of the new volume
Returns
The created volume or NULL if an element with this ID already exists or if input nodes are not found.
Reimplemented in SMESHDS_Mesh.
References SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
Referenced by AddPolyhedralVolume(), and SMESHDS_Mesh::AddPolyhedralVolumeWithID().
AddQuadPolygonalFace()
SMDS_MeshFace * SMDS_Mesh::AddQuadPolygonalFace (const std::vector< const SMDS_MeshNode * > & nodes) virtual
Add a quadratic polygon defined by its nodes.
An ID is automatically affected to the created face.
Reimplemented in SMESHDS_Mesh.
References AddQuadPolygonalFaceWithID(), SMDS_MeshElementIDFactory::GetFreeID(), and myElementIDFactory.
Referenced by SMESHDS_Mesh::AddQuadPolygonalFace().
AddQuadPolygonalFaceWithID() [1/2]
SMDS_MeshFace * SMDS_Mesh::AddQuadPolygonalFaceWithID (const std::vector< const SMDS_MeshNode * > & nodes, const int ID) virtual
Add a quadratic polygon defined by its nodes.
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), CheckMemory(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionEdges(), SMDS_VtkFace::initQuadPoly(), myCells, myFacePool, myGrid, myInfo, myNodeIds, NbFaces(), and registerElement().
AddQuadPolygonalFaceWithID() [2/2]
SMDS_MeshFace * SMDS_Mesh::AddQuadPolygonalFaceWithID (const std::vector< int > & nodes_ids, const int ID) virtual
Add a quadratic polygon defined by its nodes IDs.
Reimplemented in SMESHDS_Mesh.
References SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
Referenced by AddQuadPolygonalFace(), and SMESHDS_Mesh::AddQuadPolygonalFaceWithID().
AddSubMesh()
SMDS_Mesh * SMDS_Mesh::AddSubMesh ()
Create a submesh and add it to the current mesh.
References myChildren, and SMDS_Mesh().
AddVolume() [1/13]
SMDS_MeshVolume * SMDS_Mesh::AddVolume (const SMDS_MeshFace * f1, const SMDS_MeshFace * f2, const SMDS_MeshFace * f3, const SMDS_MeshFace * f4) virtual
Create a new tetrahedron defined by its faces and add it to the mesh.
Returns
The created tetrahedron
References AddVolumeWithID(), SMDS_MeshElementIDFactory::GetFreeID(), hasConstructionFaces(), and myElementIDFactory.
AddVolume() [2/13]
SMDS_MeshVolume * SMDS_Mesh::AddVolume (const SMDS_MeshFace * f1, const SMDS_MeshFace * f2, const SMDS_MeshFace * f3, const SMDS_MeshFace * f4, const SMDS_MeshFace * f5) virtual
Create a new pyramid defined by its faces and add it to the mesh.
Returns
The created pyramid
References AddVolumeWithID(), SMDS_MeshElementIDFactory::GetFreeID(), hasConstructionFaces(), and myElementIDFactory.
AddVolume() [3/13]
SMDS_MeshVolume * SMDS_Mesh::AddVolume (const SMDS_MeshFace * f1, const SMDS_MeshFace * f2, const SMDS_MeshFace * f3, const SMDS_MeshFace * f4, const SMDS_MeshFace * f5, const SMDS_MeshFace * f6) virtual
Create a new prism defined by its faces and add it to the mesh.
Returns
The created prism
References AddVolumeWithID(), SMDS_MeshElementIDFactory::GetFreeID(), hasConstructionFaces(), and myElementIDFactory.
AddVolume() [4/13]
SMDS_MeshVolume * SMDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4) virtual
Create a new tetrahedron and add it to the mesh.
Returns
The created tetrahedron
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshElementIDFactory::GetFreeID(), myElementIDFactory, and SMDS_MeshElementIDFactory::ReleaseID().
Referenced by SMESHDS_Mesh::AddVolume().
AddVolume() [5/13]
SMDS_MeshVolume * SMDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n31, const SMDS_MeshNode * n14, const SMDS_MeshNode * n24, const SMDS_MeshNode * n34) virtual
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshElementIDFactory::GetFreeID(), myElementIDFactory, and SMDS_MeshElementIDFactory::ReleaseID().
AddVolume() [6/13]
SMDS_MeshVolume * SMDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5) virtual
Create a new pyramid and add it to the mesh.
Nodes 1,2,3 and 4 define the base of the pyramid
Returns
The created pyramid
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshElementIDFactory::GetFreeID(), myElementIDFactory, and SMDS_MeshElementIDFactory::ReleaseID().
AddVolume() [7/13]
SMDS_MeshVolume * SMDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, const SMDS_MeshNode * n15, const SMDS_MeshNode * n25, const SMDS_MeshNode * n35, const SMDS_MeshNode * n45) virtual
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshElementIDFactory::GetFreeID(), myElementIDFactory, and SMDS_MeshElementIDFactory::ReleaseID().
AddVolume() [8/13]
SMDS_MeshVolume * SMDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6) virtual
Create a new prism and add it to the mesh.
Nodes 1,2,3 is a triangle and 1,2,5,4 a quadrangle.
Returns
The created prism
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshElementIDFactory::GetFreeID(), myElementIDFactory, and SMDS_MeshElementIDFactory::ReleaseID().
AddVolume() [9/13]
SMDS_MeshVolume * SMDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n31, const SMDS_MeshNode * n45, const SMDS_MeshNode * n56, const SMDS_MeshNode * n64, const SMDS_MeshNode * n14, const SMDS_MeshNode * n25, const SMDS_MeshNode * n36) virtual
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshElementIDFactory::GetFreeID(), myElementIDFactory, and SMDS_MeshElementIDFactory::ReleaseID().
AddVolume() [10/13]
SMDS_MeshVolume * SMDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n7, const SMDS_MeshNode * n8) virtual
Create a new hexahedron and add it to the mesh.
Nodes 1,2,3,4 and 5,6,7,8 are quadrangle and 5,1 and 7,3 are an edges.
Returns
The created hexahedron
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshElementIDFactory::GetFreeID(), myElementIDFactory, and SMDS_MeshElementIDFactory::ReleaseID().
AddVolume() [11/13]
SMDS_MeshVolume * SMDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n7, const SMDS_MeshNode * n8, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, const SMDS_MeshNode * n56, const SMDS_MeshNode * n67, const SMDS_MeshNode * n78, const SMDS_MeshNode * n85, const SMDS_MeshNode * n15, const SMDS_MeshNode * n26, const SMDS_MeshNode * n37, const SMDS_MeshNode * n48) virtual
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshElementIDFactory::GetFreeID(), myElementIDFactory, and SMDS_MeshElementIDFactory::ReleaseID().
AddVolume() [12/13]
SMDS_MeshVolume * SMDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n7, const SMDS_MeshNode * n8, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, const SMDS_MeshNode * n56, const SMDS_MeshNode * n67, const SMDS_MeshNode * n78, const SMDS_MeshNode * n85, const SMDS_MeshNode * n15, const SMDS_MeshNode * n26, const SMDS_MeshNode * n37, const SMDS_MeshNode * n48, const SMDS_MeshNode * n1234, const SMDS_MeshNode * n1256, const SMDS_MeshNode * n2367, const SMDS_MeshNode * n3478, const SMDS_MeshNode * n1458, const SMDS_MeshNode * n5678, const SMDS_MeshNode * nCenter) virtual
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshElementIDFactory::GetFreeID(), myElementIDFactory, and SMDS_MeshElementIDFactory::ReleaseID().
AddVolume() [13/13]
SMDS_MeshVolume * SMDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n7, const SMDS_MeshNode * n8, const SMDS_MeshNode * n9, const SMDS_MeshNode * n10, const SMDS_MeshNode * n11, const SMDS_MeshNode * n12) virtual
Create a new hexagonal prism and add it to the mesh.
Returns
The created prism
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshElementIDFactory::GetFreeID(), myElementIDFactory, and SMDS_MeshElementIDFactory::ReleaseID().
AddVolumeFromVtkIds()
SMDS_MeshVolume * SMDS_Mesh::AddVolumeFromVtkIds (const std::vector< vtkIdType > & vtkNodeIds) virtual
References AddVolumeFromVtkIdsWithID(), SMDS_MeshElementIDFactory::GetFreeID(), myElementIDFactory, and SMDS_MeshElementIDFactory::ReleaseID().
Referenced by SMESH_MeshEditor::DoubleNodesOnGroupBoundaries().
AddVolumeFromVtkIdsWithID()
SMDS_MeshVolume * SMDS_Mesh::AddVolumeFromVtkIdsWithID (const std::vector< vtkIdType > & vtkNodeIds, const int ID) virtual
References adjustmyCellsCapacity(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), SMDS_VtkVolume::GetVtkType(), SMDS_VtkVolume::init(), myCells, myGrid, myInfo, myVolumePool, and registerElement().
Referenced by AddVolumeFromVtkIds().
AddVolumeWithID() [1/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (const SMDS_MeshFace * f1, const SMDS_MeshFace * f2, const SMDS_MeshFace * f3, const SMDS_MeshFace * f4, const SMDS_MeshFace * f5, const SMDS_MeshFace * f6, int ID) virtual
Create a new prism defined by its faces and add it to the mesh.
Parameters
ID The ID of the new volume
Returns
The created prism
References adjustmyCellsCapacity(), CheckMemory(), SMDS_MeshElementIDFactory::GetFreeID(), hasConstructionFaces(), myCells, myElementIDFactory, myInfo, NbVolumes(), and registerElement().
AddVolumeWithID() [2/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (const SMDS_MeshFace * f1, const SMDS_MeshFace * f2, const SMDS_MeshFace * f3, const SMDS_MeshFace * f4, const SMDS_MeshFace * f5, int ID) virtual
Create a new pyramid defined by its faces and add it to the mesh.
Parameters
ID The ID of the new volume
Returns
The created pyramid
References adjustmyCellsCapacity(), CheckMemory(), SMDS_MeshElementIDFactory::GetFreeID(), hasConstructionFaces(), myCells, myElementIDFactory, myInfo, NbVolumes(), and registerElement().
AddVolumeWithID() [3/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (const SMDS_MeshFace * f1, const SMDS_MeshFace * f2, const SMDS_MeshFace * f3, const SMDS_MeshFace * f4, int ID) virtual
Create a new tetrahedron defined by its faces and add it to the mesh.
Parameters
ID The ID of the new volume
Returns
The created tetrahedron
References adjustmyCellsCapacity(), CheckMemory(), SMDS_MeshElementIDFactory::GetFreeID(), hasConstructionFaces(), myCells, myElementIDFactory, myInfo, NbVolumes(), and registerElement().
AddVolumeWithID() [4/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n31, const SMDS_MeshNode * n14, const SMDS_MeshNode * n24, const SMDS_MeshNode * n34, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionFaces(), SMDS_VtkVolume::init(), myCells, myGrid, myInfo, myNodeIds, myVolumePool, and registerElement().
AddVolumeWithID() [5/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, const SMDS_MeshNode * n15, const SMDS_MeshNode * n25, const SMDS_MeshNode * n35, const SMDS_MeshNode * n45, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionFaces(), SMDS_VtkVolume::init(), myCells, myGrid, myInfo, myNodeIds, myVolumePool, and registerElement().
AddVolumeWithID() [6/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n31, const SMDS_MeshNode * n45, const SMDS_MeshNode * n56, const SMDS_MeshNode * n64, const SMDS_MeshNode * n14, const SMDS_MeshNode * n25, const SMDS_MeshNode * n36, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionFaces(), SMDS_VtkVolume::init(), myCells, myGrid, myInfo, myNodeIds, myVolumePool, and registerElement().
AddVolumeWithID() [7/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n7, const SMDS_MeshNode * n8, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, const SMDS_MeshNode * n56, const SMDS_MeshNode * n67, const SMDS_MeshNode * n78, const SMDS_MeshNode * n85, const SMDS_MeshNode * n15, const SMDS_MeshNode * n26, const SMDS_MeshNode * n37, const SMDS_MeshNode * n48, const SMDS_MeshNode * n1234, const SMDS_MeshNode * n1256, const SMDS_MeshNode * n2367, const SMDS_MeshNode * n3478, const SMDS_MeshNode * n1458, const SMDS_MeshNode * n5678, const SMDS_MeshNode * nCenter, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionFaces(), SMDS_VtkVolume::init(), myCells, myGrid, myInfo, myNodeIds, myVolumePool, and registerElement().
AddVolumeWithID() [8/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n7, const SMDS_MeshNode * n8, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, const SMDS_MeshNode * n56, const SMDS_MeshNode * n67, const SMDS_MeshNode * n78, const SMDS_MeshNode * n85, const SMDS_MeshNode * n15, const SMDS_MeshNode * n26, const SMDS_MeshNode * n37, const SMDS_MeshNode * n48, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionFaces(), SMDS_VtkVolume::init(), myCells, myGrid, myInfo, myNodeIds, myVolumePool, and registerElement().
AddVolumeWithID() [9/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n7, const SMDS_MeshNode * n8, const SMDS_MeshNode * n9, const SMDS_MeshNode * n10, const SMDS_MeshNode * n11, const SMDS_MeshNode * n12, int ID) virtual
Create a new hexagonal prism and add it to the mesh.
Parameters
ID The ID of the new volume
Returns
The created prism
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), CheckMemory(), ObjectPool< X >::destroy(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionEdges(), hasConstructionFaces(), SMDS_VtkVolume::init(), myCells, myGrid, myInfo, myNodeIds, myVolumePool, NbVolumes(), and registerElement().
AddVolumeWithID() [10/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n7, const SMDS_MeshNode * n8, int ID) virtual
Create a new hexahedron and add it to the mesh.
Nodes 1,2,3,4 and 5,6,7,8 are quadrangle and 5,1 and 7,3 are an edges.
Parameters
ID The ID of the new volume
Returns
The created prism or NULL if an element with this ID already exists or if input nodes are not found.
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), CheckMemory(), ObjectPool< X >::destroy(), FindFaceOrCreate(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionEdges(), hasConstructionFaces(), SMDS_VtkVolume::init(), myCells, myGrid, myInfo, myNodeIds, myVolumePool, NbVolumes(), and registerElement().
AddVolumeWithID() [11/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, int ID) virtual
Create a new prism and add it to the mesh.
Nodes 1,2,3 is a triangle and 1,2,5,4 a quadrangle.
Parameters
ID The ID of the new volume
Returns
The created prism
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), CheckMemory(), ObjectPool< X >::destroy(), FindFaceOrCreate(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionEdges(), hasConstructionFaces(), SMDS_VtkVolume::init(), myCells, myGrid, myInfo, myNodeIds, myVolumePool, NbVolumes(), and registerElement().
AddVolumeWithID() [12/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, int ID) virtual
Create a new pyramid and add it to the mesh.
Nodes 1,2,3 and 4 define the base of the pyramid
Parameters
ID The ID of the new volume
Returns
The created pyramid
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), CheckMemory(), ObjectPool< X >::destroy(), FindFaceOrCreate(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionEdges(), hasConstructionFaces(), SMDS_VtkVolume::init(), myCells, myGrid, myInfo, myNodeIds, myVolumePool, NbVolumes(), and registerElement().
AddVolumeWithID() [13/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, int ID) virtual
Create a new tetrahedron and add it to the mesh.
Parameters
ID The ID of the new volume
Returns
The created tetrahedron
Reimplemented in SMESHDS_Mesh.
References adjustmyCellsCapacity(), CheckMemory(), ObjectPool< X >::destroy(), FindFaceOrCreate(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionEdges(), hasConstructionFaces(), SMDS_VtkVolume::init(), myCells, myGrid, myInfo, myNodeIds, myVolumePool, NbVolumes(), and registerElement().
AddVolumeWithID() [14/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (int idnode1, int idnode2, int idnode3, int idnode4, int ID) virtual
Create a new tetrahedron and add it to the mesh.
Parameters
ID The ID of the new volume
Returns
The created tetrahedron or NULL if an element with this ID already exists or if input nodes are not found.
Reimplemented in SMESHDS_Mesh.
References SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
Referenced by AddVolume(), SMESHDS_Mesh::AddVolumeWithID(), and AddVolumeWithID().
AddVolumeWithID() [15/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (int n1, int n2, int n3, int n4, int n12, int n23, int n31, int n14, int n24, int n34, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
AddVolumeWithID() [16/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int ID) virtual
Create a new pyramid and add it to the mesh.
Nodes 1,2,3 and 4 define the base of the pyramid
Parameters
ID The ID of the new volume
Returns
The created pyramid or NULL if an element with this ID already exists or if input nodes are not found.
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
AddVolumeWithID() [17/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n12, int n23, int n34, int n41, int n15, int n25, int n35, int n45, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
AddVolumeWithID() [18/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6, int ID) virtual
Create a new prism and add it to the mesh.
Nodes 1,2,3 is a triangle and 1,2,5,4 a quadrangle.
Parameters
ID The ID of the new volume
Returns
The created prism or NULL if an element with this ID already exists or if input nodes are not found.
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
AddVolumeWithID() [19/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int n12, int n23, int n31, int n45, int n56, int n64, int n14, int n25, int n36, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
AddVolumeWithID() [20/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6, int idnode7, int idnode8, int ID) virtual
Create a new hexahedron and add it to the mesh.
Nodes 1,2,3,4 and 5,6,7,8 are quadrangle and 5,1 and 7,3 are an edges.
Parameters
ID The ID of the new volume
Returns
The created hexahedron or NULL if an element with this ID already exists or if input nodes are not found.
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
AddVolumeWithID() [21/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n12, int n23, int n34, int n41, int n56, int n67, int n78, int n85, int n15, int n26, int n37, int n48, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
AddVolumeWithID() [22/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n12, int n23, int n34, int n41, int n56, int n67, int n78, int n85, int n15, int n26, int n37, int n48, int n1234, int n1256, int n2367, int n3478, int n1458, int n5678, int nCenter, int ID) virtual
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
AddVolumeWithID() [23/23]
SMDS_MeshVolume * SMDS_Mesh::AddVolumeWithID (int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6, int idnode7, int idnode8, int idnode9, int idnode10, int idnode11, int idnode12, int ID) virtual
Create a new hexagonal prism and add it to the mesh.
Parameters
ID The ID of the new volume
Returns
The created prism or NULL if an element with this ID already exists or if input nodes are not found.
Reimplemented in SMESHDS_Mesh.
References AddVolumeWithID(), SMDS_MeshNodeIDFactory::MeshElement(), and myNodeIDFactory.
adjustBoundingBox()
void SMDS_Mesh::adjustBoundingBox (double x, double y, double z) protected
Referenced by AddNodeWithID().
adjustmyCellsCapacity()
void SMDS_Mesh::adjustmyCellsCapacity (int ID) protected
References chunkSize.
Referenced by Add0DElementWithID(), AddBallWithID(), AddEdgeWithID(), AddFaceFromVtkIdsWithID(), AddFaceWithID(), AddPolygonalFaceWithID(), AddPolyhedralVolumeWithID(), AddQuadPolygonalFaceWithID(), AddVolumeFromVtkIdsWithID(), AddVolumeWithID(), createQuadrangle(), createTriangle(), and FindEdgeOrCreate().
adjustStructure()
void SMDS_Mesh::adjustStructure ()
References SMDS_MeshNodeIDFactory::GetMaxID(), SMDS_UnstructuredGrid::GetPoints(), myGrid, and myNodeIDFactory.
ChangeElementNodes()
bool SMDS_Mesh::ChangeElementNodes (const SMDS_MeshElement * elem, const SMDS_MeshNode * nodes[], const int nbnodes)
References SMDS_MeshNode::AddInverseElement(), SMDS_MeshElement::begin_nodes(), SMDS_MeshCell::ChangeNodes(), SMDS_MeshElement::end_nodes(), SMDS_MeshNode::RemoveInverseElement(), and SMDS_MeshCell::vtkOrder().
Referenced by SMESHDS_Mesh::ChangeElementNodes().
ChangePolyhedronNodes()
bool SMDS_Mesh::ChangePolyhedronNodes (const SMDS_MeshElement * elem, const std::vector< const SMDS_MeshNode * > & nodes, const std::vector< int > & quantities)
References SMDS_MeshElement::GetType(), SMDS_MeshElement::nodesIterator(), and SMDS_MeshNode::RemoveInverseElement().
Referenced by SMESHDS_Mesh::ChangePolyhedronNodes().
CheckMemory()
int SMDS_Mesh::CheckMemory (const bool doNotRaise = false) static
Raise an exception if free memory (ram+swap) too low.
Parameters
doNotRaise - if true, suppres exception, just return free memory size
Return values
int - amount of available memory in MB or negative number in failure case
Referenced by Add0DElementWithID(), AddBallWithID(), AddFaceWithID(), AddPolygonalFaceWithID(), AddPolyhedralVolumeWithID(), AddQuadPolygonalFaceWithID(), AddVolumeWithID(), SMESH_subMesh::ComputeStateEngine(), createQuadrangle(), createTriangle(), and FindEdgeOrCreate().
Clear()
void SMDS_Mesh::Clear () virtual
Clear all data.
References SMDS_UnstructuredGrid::BuildLinks(), ObjectPool< X >::clear(), SMDS_MeshElementIDFactory::Clear(), SMDS_MeshInfo::Clear(), SMDS_MeshNodeIDFactory::Clear(), elementsIterator(), SMDS_MeshElement::GetID(), SMDS_MeshElement::getVtkId(), myBallPool, myCellIdVtkToSmds, myCells, myChildren, myEdgePool, myElementIDFactory, myFacePool, myGrid, myInfo, myModified, myModifTime, myNodeIDFactory, myNodePool, myNodes, myParent, myVolumePool, nodesIterator(), SMDS_SpacePosition::originSpacePosition(), SMDS_MeshElementIDFactory::ReleaseID(), SMDS_MeshNodeIDFactory::ReleaseID(), SMDS_MeshNode::SetPosition(), xmax, xmin, ymax, ymin, and zmin.
Referenced by SMESHDS_Mesh::ClearMesh().
compactMesh()
void SMDS_Mesh::compactMesh () virtual
Reimplemented in SMESHDS_Mesh.
Contains()
bool SMDS_Mesh::Contains (const SMDS_MeshElement * elem) const
Checks if the element is present in mesh. Useful to determine dead pointers. Use this function for debug purpose only! Do not check in the code using it even in DEBUG mode
Checks if the element is present in mesh. Useful to determine dead pointers.
References elementsIterator(), and nodesIterator().
Referenced by SMESH_MeshEditor::ExtrusionAlongTrack().
createQuadrangle()
SMDS_MeshFace * SMDS_Mesh::createQuadrangle (const SMDS_MeshNode * node1, const SMDS_MeshNode * node2, const SMDS_MeshNode * node3, const SMDS_MeshNode * node4, int ID) protected
Create a quadrangle and add it to the current mesh.
This methode do not bind a ID to the create triangle.
References adjustmyCellsCapacity(), CheckMemory(), ObjectPool< X >::destroy(), FindEdgeOrCreate(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionEdges(), SMDS_VtkFace::init(), myCells, myFacePool, myGrid, myInfo, myNodeIds, NbFaces(), and registerElement().
Referenced by AddFaceWithID(), and FindFaceOrCreate().
createTriangle()
SMDS_MeshFace * SMDS_Mesh::createTriangle (const SMDS_MeshNode * node1, const SMDS_MeshNode * node2, const SMDS_MeshNode * node3, int ID) protected
Create a triangle and add it to the current mesh.
This method do not bind an ID to the create triangle.
References adjustmyCellsCapacity(), CheckMemory(), ObjectPool< X >::destroy(), FindEdgeOrCreate(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), hasConstructionEdges(), SMDS_VtkFace::init(), myCells, myFacePool, myGrid, myInfo, myNodeIds, NbFaces(), and registerElement().
Referenced by AddFaceWithID(), and FindFaceOrCreate().
DebugStats()
void SMDS_Mesh::DebugStats () const
References facesIterator(), SMDS_MeshNode::GetInverseElementIterator(), Nb0DElements(), NbEdges(), NbFaces(), NbNodes(), NbVolumes(), and nodesIterator().
Dump0DElements()
void SMDS_Mesh::Dump0DElements () const
References elementsIterator().
DumpEdges()
void SMDS_Mesh::DumpEdges () const
References edgesIterator().
DumpFaces()
void SMDS_Mesh::DumpFaces () const
References facesIterator().
dumpGrid()
void SMDS_Mesh::dumpGrid (string ficdump = "dumpGrid")
References myGrid.
DumpNodes()
void SMDS_Mesh::DumpNodes () const
References nodesIterator().
DumpVolumes()
void SMDS_Mesh::DumpVolumes () const
References volumesIterator().
edgesIterator()
SMDS_EdgeIteratorPtr SMDS_Mesh::edgesIterator (bool idInceasingOrder = false) const virtual
Return an iterator on edges of the current mesh.
References myCells.
Referenced by SMESH_MeshEditor::ConvertToQuadratic(), DumpEdges(), Fem::FemMeshPy::getEdges(), and SMESH_MeshVSLink::SMESH_MeshVSLink().
elementEntityIterator()
SMDS_ElemIteratorPtr SMDS_Mesh::elementEntityIterator (SMDSAbs_EntityType type) const virtual
References myCells, and myNodes.
Referenced by DriverMED_W_SMESHDS_Mesh::Perform().
elementGeomIterator()
SMDS_ElemIteratorPtr SMDS_Mesh::elementGeomIterator (SMDSAbs_GeometryType type) const virtual
References myCells.
Referenced by DriverMED_W_SMESHDS_Mesh::Perform().
elementsIterator()
SMDS_ElemIteratorPtr SMDS_Mesh::elementsIterator (SMDSAbs_ElementType type = SMDSAbs_All) const virtual
Return an iterator on elements of the current mesh factory.
References myCells, and myNodes.
Referenced by Clear(), Contains(), SMESH_MeshEditor::Create0DElementsOnAllNodes(), Dump0DElements(), SMDS_MeshElementIDFactory::elementsIterator(), SMDS_MeshNodeIDFactory::elementsIterator(), SMESH_MeshEditor::ExtrusionAlongTrack(), SMESH_MeshEditor::FindEqualElements(), SMESHDS_GroupOnFilter::GetElements(), SMESH::Controls::Filter::GetElementsId(), SMESH_ProxyMesh::GetFaces(), SMESH::Controls::NumericalFunctor::GetHistogram(), Fem::FemMeshPy::getIdByElementType(), DriverMED_W_Field::GetOrderedElems(), SMESH_ElementSearcherImpl::getTolerance(), StdMeshers_Import_1D::importMesh(), SMESH_Pattern::Load(), SMESH_MeshEditor::MakeBoundaryMesh(), DriverMED_W_SMESHDS_Mesh::Perform(), SMESH_MeshEditor::QuadTo4Tri(), SMESH_MeshEditor::Reorient2DBy3D(), SMESH_MeshEditor::Transform(), and ~SMDS_Mesh().
facesIterator()
SMDS_FaceIteratorPtr SMDS_Mesh::facesIterator (bool idInceasingOrder = false) const virtual
Return an iterator on faces of the current mesh.
References myCells.
Referenced by StdMeshers_QuadToTriaAdaptor::Compute(), SMESH_MeshEditor::ConvertToQuadratic(), DebugStats(), DumpFaces(), Fem::FemVTKTools::exportVTKMesh(), SMESH::Controls::FreeEdges::GetBoreders(), Fem::FemMeshPy::getFaces(), SMESH::Controls::MultiConnection2D::GetValues(), SMESH::Controls::Length2D::GetValues(), SMESH_MesherHelper::IsQuadraticSubMesh(), SMESH_MeshEditor::Reorient2D(), SMESH_MeshVSLink::SMESH_MeshVSLink(), and SMESH_MeshEditor::Smooth().
Find0DElement() [1/2]
const SMDS_Mesh0DElement * SMDS_Mesh::Find0DElement (const SMDS_MeshNode * n) static
References SMDS_MeshNode::GetInverseElementIterator().
Find0DElement() [2/2]
const SMDS_Mesh0DElement * SMDS_Mesh::Find0DElement (int idnode) const
References FindNode().
FindBall() [1/2]
const SMDS_BallElement * SMDS_Mesh::FindBall (const SMDS_MeshNode * n) static
References SMDS_MeshNode::GetInverseElementIterator().
FindBall() [2/2]
const SMDS_BallElement * SMDS_Mesh::FindBall (int idnode) const
References FindNode().
FindEdge() [1/4]
const SMDS_MeshEdge * SMDS_Mesh::FindEdge (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2) static
References SMDS_MeshNode::GetInverseElementIterator().
FindEdge() [2/4]
const SMDS_MeshEdge * SMDS_Mesh::FindEdge (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3) static
References SMDS_MeshNode::GetInverseElementIterator().
FindEdge() [3/4]
const SMDS_MeshEdge * SMDS_Mesh::FindEdge (int idnode1, int idnode2) const
References FindNode().
Referenced by StdMeshers_Projection_1D2D::Compute(), NETGENPlugin_Mesher::FillSMesh(), FindEdge(), FindEdgeOrCreate(), SMDS_VolumeTool::GetAllExistingEdges(), SMESH_MeshEditor::InsertNodesIntoLink(), and SMESH_MeshEditor::MakeBoundaryMesh().
FindEdge() [4/4]
const SMDS_MeshEdge * SMDS_Mesh::FindEdge (int idnode1, int idnode2, int idnode3) const
References FindEdge(), and FindNode().
FindEdgeOrCreate()
SMDS_MeshEdge * SMDS_Mesh::FindEdgeOrCreate (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2) protected
References adjustmyCellsCapacity(), CheckMemory(), ObjectPool< X >::destroy(), FindEdge(), SMDS_MeshElementIDFactory::GetFreeID(), ObjectPool< X >::getNew(), SMDS_MeshElement::getVtkId(), SMDS_VtkEdge::init(), myCells, myEdgePool, myElementIDFactory, myGrid, myInfo, myNodeIds, NbEdges(), and registerElement().
Referenced by createQuadrangle(), and createTriangle().
FindElement() [1/2]
const SMDS_MeshElement * SMDS_Mesh::FindElement (const std::vector< const SMDS_MeshNode * > & nodes, const SMDSAbs_ElementType type = SMDSAbs_All, const bool noMedium = true) static
Return element based on all given nodes.
Parameters
nodes - node of element
type - type of element
noMedium - true if medium nodes of quadratic element are not included in <nodes>
Return values
const SMDS_MeshElement* - found element or NULL
FindElement() [2/2]
const SMDS_MeshElement * SMDS_Mesh::FindElement (int IDelem) const
References myCells.
Referenced by StdMeshers_Import_1D2D::Compute(), SMESH_MeshEditor::CreateHoleSkin(), SMESH_MeshEditor::DoubleNodes(), SMESH_MeshEditor::DoubleNodesOnGroupBoundaries(), FindFace(), SMESHDS_GroupBase::findInMesh(), SMESH_MeshVSLink::Get3DGeom(), SMESH_MeshVSLink::GetGeom(), SMESH_MeshVSLink::GetGeomType(), SMESH_MeshVSLink::GetNodesByElement(), SMESH_MeshVSLink::GetNormal(), SMESH::Controls::NumericalFunctor::GetPoints(), SMESH::Controls::NumericalFunctor::GetValue(), SMESH::Controls::Volume::GetValue(), SMESH::Controls::MaxElementLength3D::GetValue(), SMESH::Controls::AspectRatio::GetValue(), SMESH::Controls::AspectRatio3D::GetValue(), SMESH::Controls::MultiConnection2D::GetValue(), SMESH::Controls::BallDiameter::GetValue(), StdMeshers_Import_1D::importMesh(), SMESH::Controls::CoincidentElements::IsSatisfy(), SMESH::Controls::BadOrientedVolume::IsSatisfy(), SMESH::Controls::ElemEntityType::IsSatisfy(), SMESH::Controls::BareBorderVolume::IsSatisfy(), SMESH::Controls::BareBorderFace::IsSatisfy(), SMESH::Controls::OverConstrainedVolume::IsSatisfy(), SMESH::Controls::OverConstrainedFace::IsSatisfy(), SMESH::Controls::FreeEdges::IsSatisfy(), SMESH::Controls::BelongToGeom::IsSatisfy(), SMESH::Controls::LyingOnGeom::IsSatisfy(), SMESH::Controls::FreeFaces::IsSatisfy(), SMESH::Controls::LinearOrQuadratic::IsSatisfy(), SMESH::Controls::ElemGeomType::IsSatisfy(), SMESH::Controls::RangeOfIds::IsSatisfy(), SMESH_MeshEditor::Make2DMeshFrom3D(), SMESH_MeshEditor::MakeBoundaryMesh(), SMESH_MeshEditor::MergeElements(), SMDS_MeshElementIDFactory::MeshElement(), SMDS_MeshNode_MyInvIterator::next(), SMESH_MeshEditor::Remove(), SMESH::Controls::CoplanarFaces::SetMesh(), SMESH_MeshEditor::SewSideElements(), SMDS_MeshNode_MyInvIterator::SMDS_MeshNode_MyInvIterator(), and SMDS_MeshNode_MyIterator::SMDS_MeshNode_MyIterator().
FindFace() [1/10]
const SMDS_MeshFace * SMDS_Mesh::FindFace (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3) static
References SMDS_MeshNode::GetInverseElementIterator().
FindFace() [2/10]
const SMDS_MeshFace * SMDS_Mesh::FindFace (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4) static
References SMDS_MeshNode::GetInverseElementIterator().
FindFace() [3/10]
const SMDS_MeshFace * SMDS_Mesh::FindFace (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6) static
References SMDS_MeshNode::GetInverseElementIterator().
FindFace() [4/10]
const SMDS_MeshFace * SMDS_Mesh::FindFace (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n7, const SMDS_MeshNode * n8) static
References SMDS_MeshNode::GetInverseElementIterator().
FindFace() [5/10]
const SMDS_MeshFace * SMDS_Mesh::FindFace (const std::vector< const SMDS_MeshNode * > & nodes) static
References FindElement().
FindFace() [6/10]
const SMDS_MeshFace * SMDS_Mesh::FindFace (const std::vector< int > & nodes_ids) const
References FindFace(), and FindNode().
FindFace() [7/10]
const SMDS_MeshFace * SMDS_Mesh::FindFace (int idnode1, int idnode2, int idnode3) const
References FindNode().
Referenced by FindFace(), FindFaceOrCreate(), SMESH_MesherHelper::FixQuadraticElements(), and SMDS_VolumeTool::GetAllExistingFaces().
FindFace() [8/10]
const SMDS_MeshFace * SMDS_Mesh::FindFace (int idnode1, int idnode2, int idnode3, int idnode4) const
References FindFace(), and FindNode().
FindFace() [9/10]
const SMDS_MeshFace * SMDS_Mesh::FindFace (int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6) const
References FindFace(), and FindNode().
FindFace() [10/10]
const SMDS_MeshFace * SMDS_Mesh::FindFace (int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6, int idnode7, int idnode8) const
References FindFace(), and FindNode().
FindFaceOrCreate() [1/2]
SMDS_MeshFace * SMDS_Mesh::FindFaceOrCreate (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3) protected
References createTriangle(), FindFace(), SMDS_MeshElementIDFactory::GetFreeID(), and myElementIDFactory.
Referenced by AddVolumeWithID().
FindFaceOrCreate() [2/2]
SMDS_MeshFace * SMDS_Mesh::FindFaceOrCreate (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4) protected
References createQuadrangle(), FindFace(), SMDS_MeshElementIDFactory::GetFreeID(), and myElementIDFactory.
FindNode()
const SMDS_MeshNode * SMDS_Mesh::FindNode (int idnode) const
Return the node whose SMDS ID is 'ID'.
References myNodes.
Referenced by Fem::FemMeshPy::addEdge(), Fem::FemMeshPy::addFace(), Fem::FemMeshPy::addQuad(), Fem::FemMeshPy::addVolume(), SMESH_MeshEditor::DoubleNodes(), Find0DElement(), FindBall(), FindEdge(), FindFace(), SMESHDS_GroupBase::findInMesh(), DriverMED::FindNode(), StdMeshers_Penta_3D::FindNodeOnShape(), SMESH_MeshVSLink::GetGeom(), SMESH_MeshVSLink::GetGeomType(), Fem::FemMeshPy::getNodeById(), SMESH::Controls::ElemEntityType::IsSatisfy(), SMESH::Controls::BelongToGeom::IsSatisfy(), SMESH::Controls::LyingOnGeom::IsSatisfy(), SMESH::Controls::ConnectedElements::IsSatisfy(), SMESH::Controls::FreeNodes::IsSatisfy(), SMESH::Controls::RangeOfIds::IsSatisfy(), SMDS_MeshNodeIDFactory::MeshElement(), SMESH_MeshEditor::Remove(), and SMESH::Controls::ConnectedElements::SetNode().
FindNodeVtk()
const SMDS_MeshNode * SMDS_Mesh::FindNodeVtk (int idnode) const
Return the node whose VTK ID is 'vtkId'.
References myNodes.
Referenced by SMESH_MeshEditor::DoubleNodesOnGroupBoundaries().
fromVtkToSmds()
int SMDS_Mesh::fromVtkToSmds (int vtkid)
References myCellIdVtkToSmds.
Referenced by SMESH_MeshEditor::CreateHoleSkin(), SMESH_MeshEditor::DoubleNodesOnGroupBoundaries(), SMDS_MeshNode_MyInvIterator::next(), SMDS_MeshNode_MyInvIterator::SMDS_MeshNode_MyInvIterator(), and SMDS_MeshNode_MyIterator::SMDS_MeshNode_MyIterator().
GetElementType()
SMDSAbs_ElementType SMDS_Mesh::GetElementType (const int id, const bool iselem) const
References SMDS_MeshElement::GetType(), SMDS_MeshElementIDFactory::MeshElement(), SMDS_MeshNodeIDFactory::MeshElement(), myElementIDFactory, and myNodeIDFactory.
getGrid()
SMDS_UnstructuredGrid* SMDS_Mesh::getGrid ()
actual nodes coordinates, cells definition and reverse connectivity are stored in a vtkUnstructuredGrid
Referenced by SMESH_MeshEditor::CreateHoleSkin(), SMESH_MeshEditor::DoubleNodesOnGroupBoundaries(), and SMDS_MeshElementIDFactory::SetInVtkGrid().
getMaxDim()
double SMDS_Mesh::getMaxDim ()
References xmax, xmin, ymax, ymin, and zmin.
getMeshId()
int SMDS_Mesh::getMeshId ()
References SMDS_MeshElement::myMeshId.
GetMeshInfo()
const SMDS_MeshInfo& SMDS_Mesh::GetMeshInfo () const
Referenced by Fem::FemVTKTools::exportVTKMesh(), SMESHDS_GroupOnFilter::GetElements(), SMESH::Controls::NumericalFunctor::GetHistogram(), SMESH_ElementSearcherImpl::getTolerance(), SMESH::Controls::ConnectedElements::IsSatisfy(), SMESH_Pattern::Load(), SMESH_ProxyMesh::NbFaces(), DriverGMF_Read::Perform(), and DriverMED_W_SMESHDS_Mesh::Perform().
GetMTime()
VTK_MTIME_TYPE SMDS_Mesh::GetMTime () const
get last modification timeStamp
References myModifTime.
Referenced by SMESHDS_GroupOnFilter::GetTic(), SMESHDS_GroupOnGeom::GetTic(), SMESH::Controls::TMeshModifTracer::IsMeshModified(), and SMESHDS_GroupOnFilter::IsUpToDate().
hasConstructionEdges()
bool SMDS_Mesh::hasConstructionEdges ()
Return true if this mesh create faces with edges.
A false returned value mean that faces are created with nodes. A concequence is, iteration on edges (SMDS_Element::edgesIterator) will be unavailable.
References myHasConstructionEdges.
Referenced by addChildrenWithNodes(), AddFace(), AddFaceWithID(), AddPolygonalFaceWithID(), AddPolyhedralVolumeWithID(), AddQuadPolygonalFaceWithID(), AddVolumeWithID(), createQuadrangle(), createTriangle(), DriverMED_W_SMESHDS_Mesh::Perform(), SMESHDS_Mesh::RemoveElement(), RemoveElement(), SMESHDS_Mesh::RemoveFreeElement(), RemoveFreeElement(), and SMESHDS_Mesh::RemoveNode().
hasConstructionFaces()
bool SMDS_Mesh::hasConstructionFaces ()
Return true if this mesh create volumes with faces A false returned value mean that volumes are created with nodes or edges.
(see hasConstructionEdges) A concequence is, iteration on faces (SMDS_Element::facesIterator) will be unavailable.
References myHasConstructionFaces.
Referenced by addChildrenWithNodes(), AddPolyhedralVolumeWithID(), AddVolume(), AddVolumeWithID(), DriverMED_W_SMESHDS_Mesh::Perform(), SMESHDS_Mesh::RemoveElement(), RemoveElement(), SMESHDS_Mesh::RemoveFreeElement(), RemoveFreeElement(), and SMESHDS_Mesh::RemoveNode().
hasInverseElements()
bool SMDS_Mesh::hasInverseElements ()
Return true if nodes are linked to the finit elements, they are belonging to.
Currently, It always return true.
References myHasInverseElements.
incrementCellsCapacity()
void SMDS_Mesh::incrementCellsCapacity (int nbCells)
References myCellIdVtkToSmds, myCells, and myNodes.
incrementNodesCapacity()
void SMDS_Mesh::incrementNodesCapacity (int nbNodes)
References myNodes.
isCompacted()
bool SMDS_Mesh::isCompacted ()
References myCompactTime, and myModifTime.
Referenced by SMESHDS_Mesh::Renumber().
MaxElementID()
int SMDS_Mesh::MaxElementID () const
References SMDS_MeshNodeIDFactory::GetMaxID(), and myElementIDFactory.
MaxNodeID()
int SMDS_Mesh::MaxNodeID () const
References myNodeMax.
Referenced by SMDS_MeshNodeIDFactory::updateMinMax().
MinElementID()
int SMDS_Mesh::MinElementID () const
References SMDS_MeshNodeIDFactory::GetMinID(), and myElementIDFactory.
MinNodeID()
int SMDS_Mesh::MinNodeID () const
References myNodeMin.
Referenced by SMDS_MeshNodeIDFactory::updateMinMax().
Modified()
void SMDS_Mesh::Modified ()
modification that needs compact structure and redraw
References myModified, and myModifTime.
Referenced by SMESH_Mesh::NotifySubMeshesHypothesisModification(), and SMDS_Mesh().
MoveNode()
void SMDS_Mesh::MoveNode (const SMDS_MeshNode * n, double x, double y, double z) virtual
Reimplemented in SMESHDS_Mesh.
References SMDS_MeshNode::setXYZ().
Referenced by SMESHDS_Mesh::MoveNode().
Nb0DElements()
int SMDS_Mesh::Nb0DElements () const virtual
Return the number of 0D elements.
References myInfo, and SMDS_MeshInfo::Nb0DElements().
Referenced by Add0DElementWithID(), DebugStats(), and DriverMED_W_SMESHDS_Mesh::Perform().
NbBalls()
int SMDS_Mesh::NbBalls () const virtual
Return the number of 0D elements.
References myInfo, and SMDS_MeshInfo::NbBalls().
Referenced by AddBallWithID(), and DriverMED_W_SMESHDS_Mesh::Perform().
NbEdges()
int SMDS_Mesh::NbEdges () const virtual
Return the number of edges (including construction edges)
References myInfo, and SMDS_MeshInfo::NbEdges().
Referenced by SMESH_MeshEditor::ConvertFromQuadratic(), SMESH_MeshEditor::ConvertToQuadratic(), DebugStats(), FindEdgeOrCreate(), DriverGMF_Write::Perform(), and DriverMED_W_SMESHDS_Mesh::Perform().
NbFaces()
int SMDS_Mesh::NbFaces () const virtual
Return the number of faces (including construction faces)
References myInfo, and SMDS_MeshInfo::NbFaces().
Referenced by AddFaceWithID(), AddPolygonalFaceWithID(), AddQuadPolygonalFaceWithID(), SMESH_MeshEditor::ConvertFromQuadratic(), SMESH_MeshEditor::ConvertToQuadratic(), createQuadrangle(), createTriangle(), DebugStats(), SMESH_Pattern::Load(), SMESH_ProxyMesh::NbFaces(), DriverGMF_Write::Perform(), and DriverMED_W_SMESHDS_Mesh::Perform().
NbNodes()
int SMDS_Mesh::NbNodes () const virtual
Return the number of nodes.
References myInfo, and SMDS_MeshInfo::NbNodes().
Referenced by DebugStats(), StdMeshers_Import_1D::importMesh(), DriverGMF_Write::Perform(), DriverMED_W_SMESHDS_Mesh::Perform(), Fem::FemMesh::read(), SMESH::Controls::ElementsOnShape::SetMesh(), and SMESHDS_Mesh::SetPersistentId().
NbSubMesh()
int SMDS_Mesh::NbSubMesh () const virtual
Return the number of child mesh of this mesh.
Note that the tree structure of SMDS_Mesh is unused in SMESH
References myChildren.
NbVolumes()
int SMDS_Mesh::NbVolumes () const virtual
Return the number of volumes.
References myInfo, and SMDS_MeshInfo::NbVolumes().
Referenced by AddPolyhedralVolumeWithID(), AddVolumeWithID(), SMESH_MeshEditor::ConvertFromQuadratic(), SMESH_MeshEditor::ConvertToQuadratic(), DebugStats(), and DriverMED_W_SMESHDS_Mesh::Perform().
nodesIterator()
SMDS_NodeIteratorPtr SMDS_Mesh::nodesIterator (bool idInceasingOrder = false) const virtual
Return an iterator on nodes of the current mesh factory.
References myNodes.
Referenced by Clear(), Contains(), DebugStats(), DumpNodes(), Fem::FemVTKTools::exportFreeCADResult(), Fem::FemVTKTools::exportVTKMesh(), SMESH_MeshEditor::ExtrusionAlongTrack(), SMESH_MeshEditor::FindCoincidentNodes(), Fem::FemMeshPy::getNodes(), SMESH_ElementSearcherImpl::getTolerance(), StdMeshers_Import_1D::importMesh(), DriverGMF_Write::Perform(), DriverMED_W_SMESHDS_Mesh::Perform(), SMESH::Controls::CoincidentNodes::SetMesh(), SMESH_MeshVSLink::SMESH_MeshVSLink(), SMESH_NodeSearcherImpl::SMESH_NodeSearcherImpl(), SMESH_MeshEditor::Transform(), and ~SMDS_Mesh().
registerElement()
bool SMDS_Mesh::registerElement (int ID, SMDS_MeshElement * element) protected
Registers element with the given ID, maintains inverse connections.
References chunkSize, SMDS_MeshElement::getVtkId(), myCellIdVtkToSmds, myCells, myElementIDFactory, SMDS_MeshElement::myID, myMeshId, SMDS_MeshElement::myMeshId, SMDS_MeshElementIDFactory::SetInVtkGrid(), and SMDS_MeshElementIDFactory::updateMinMax().
Referenced by AddBallWithID(), AddEdgeWithID(), AddFaceFromVtkIdsWithID(), AddFaceWithID(), AddPolygonalFaceWithID(), AddPolyhedralVolumeWithID(), AddQuadPolygonalFaceWithID(), AddVolumeFromVtkIdsWithID(), AddVolumeWithID(), SMDS_MeshElementIDFactory::BindID(), createQuadrangle(), createTriangle(), and FindEdgeOrCreate().
Remove0DElement()
void SMDS_Mesh::Remove0DElement (const SMDS_Mesh0DElement * elem0d) virtual
Remove an edge and all the elements which own this edge.
References RemoveElement().
RemoveEdge()
void SMDS_Mesh::RemoveEdge (const SMDS_MeshEdge * edge) virtual
Remove an edge and all the elements which own this edge.
References RemoveElement().
RemoveElement() [1/2]
void SMDS_Mesh::RemoveElement (const SMDS_MeshElement * elem, bool removenodes = false) virtual
Parameters
elem The element to delete
removenodes if true remaining nodes will be removed
References RemoveElement().
RemoveElement() [2/2]
void SMDS_Mesh::RemoveElement (const SMDS_MeshElement * elem, std::list< const SMDS_MeshElement * > & removedElems, std::list< const SMDS_MeshElement * > & removedNodes, const bool removenodes = false) virtual
Parameters
elem The element to delete
removedElems to be filled with all removed elements
removedNodes to be filled with all removed nodes
removenodes if true remaining nodes will be removed
References addChildrenWithNodes(), ObjectPool< X >::destroy(), SMDS_MeshElement::GetType(), hasConstructionEdges(), hasConstructionFaces(), myBallPool, myCells, myEdgePool, myElementIDFactory, myFacePool, myGrid, myInfo, myNodeIDFactory, myNodePool, myNodes, myVolumePool, SMDS_SpacePosition::originSpacePosition(), SMDS_MeshElementIDFactory::ReleaseID(), SMDS_MeshNodeIDFactory::ReleaseID(), and SMDS_MeshNode::RemoveInverseElement().
Referenced by Remove0DElement(), RemoveEdge(), SMESHDS_Mesh::RemoveElement(), RemoveElement(), RemoveFace(), SMESHDS_Mesh::RemoveNode(), RemoveNode(), and RemoveVolume().
RemoveFace()
void SMDS_Mesh::RemoveFace (const SMDS_MeshFace * face) virtual
Remove an face and all the elements which own this face.
References RemoveElement().
RemoveFreeElement()
void SMDS_Mesh::RemoveFreeElement (const SMDS_MeshElement * elem) virtual
Remove only the given element and only if it is free. Method does not work for meshes with descendants. Implemented for fast cleaning of meshes.
Parameters
elem The element to delete
References ObjectPool< X >::destroy(), SMDS_MeshElement::GetID(), SMDS_MeshNode::GetInverseElementIterator(), SMDS_MeshElement::GetType(), SMDS_MeshElement::getVtkId(), hasConstructionEdges(), hasConstructionFaces(), myBallPool, myCells, myEdgePool, myElementIDFactory, myFacePool, myGrid, myInfo, myNodeIDFactory, myNodePool, myNodes, myVolumePool, SMDS_MeshElement::nodesIterator(), SMDS_SpacePosition::originSpacePosition(), SMDS_MeshElementIDFactory::ReleaseID(), SMDS_MeshNodeIDFactory::ReleaseID(), and SMDS_MeshNode::RemoveInverseElement().
Referenced by SMESHDS_Mesh::RemoveFreeElement(), and SMESHDS_Mesh::RemoveFreeNode().
RemoveFromParent()
bool SMDS_Mesh::RemoveFromParent () virtual
References myParent, and RemoveSubMesh().
RemoveNode()
void SMDS_Mesh::RemoveNode (const SMDS_MeshNode * node) virtual
Remove a node and all the elements which own this node.
Reimplemented in SMESHDS_Mesh.
References RemoveElement().
RemoveSubMesh()
bool SMDS_Mesh::RemoveSubMesh (const SMDS_Mesh * aMesh) virtual
References myChildren.
Referenced by RemoveFromParent().
RemoveVolume()
void SMDS_Mesh::RemoveVolume (const SMDS_MeshVolume * volume) virtual
Remove a volume.
References RemoveElement().
Renumber()
void SMDS_Mesh::Renumber (const bool isNodes, const int startID = 1, const int deltaID = 1) virtual
Reimplemented in SMESHDS_Mesh.
References SMDS_MeshNodeIDFactory::BindID(), SMDS_MeshNodeIDFactory::Clear(), SMDS_MeshNodeIDFactory::elementsIterator(), SMDS_MeshElement::GetID(), myElementIDFactory, and myNodeIDFactory.
setConstructionEdges()
void SMDS_Mesh::setConstructionEdges (bool b)
Make this mesh creating construction edges (see hasConstructionEdges)
Parameters
b true to have construction edges, else false.
References myHasConstructionEdges.
setConstructionFaces()
void SMDS_Mesh::setConstructionFaces (bool b)
Make this mesh creating construction faces (see hasConstructionFaces)
Parameters
b true to have construction faces, else false.
References myHasConstructionFaces.
setInverseElements()
void SMDS_Mesh::setInverseElements (bool b)
Make this mesh creating link from nodes to elements (see hasInverseElements)
Parameters
b true to link nodes to elements, else false.
References myHasInverseElements.
setMyModified()
void SMDS_Mesh::setMyModified ()
low level modification: add, change or remove node or element
Referenced by SMDS_MeshElementIDFactory::ReleaseID(), and SMDS_MeshNodeIDFactory::ReleaseID().
updateBoundingBox()
void SMDS_Mesh::updateBoundingBox ()
References SMDS_UnstructuredGrid::GetPoints(), myGrid, myNodes, xmax, xmin, ymax, ymin, and zmin.
updateNodeMinMax()
void SMDS_Mesh::updateNodeMinMax ()
References myNodeMax, myNodeMin, and myNodes.
Referenced by SMDS_MeshNodeIDFactory::updateMinMax().
volumesIterator()
SMDS_VolumeIteratorPtr SMDS_Mesh::volumesIterator (bool idInceasingOrder = false) const virtual
Return an iterator on volumes of the current mesh.
References myCells.
Referenced by SMESH_MeshEditor::ConvertToQuadratic(), DumpVolumes(), Fem::FemVTKTools::exportVTKMesh(), Fem::FemMeshPy::getVolumes(), SMESH_MeshEditor::Make2DMeshFrom3D(), and SMESH_MeshVSLink::SMESH_MeshVSLink().
Friends And Related Function Documentation
SMDS_MeshElementIDFactory
friend class SMDS_MeshElementIDFactory friend
SMDS_MeshIDFactory
friend class SMDS_MeshIDFactory friend
SMDS_MeshNode
friend class SMDS_MeshNode friend
SMDS_MeshNodeIDFactory
friend class SMDS_MeshNodeIDFactory friend
SMDS_MeshVolumeVtkNodes
friend class SMDS_MeshVolumeVtkNodes friend
Member Data Documentation
chunkSize
int SMDS_Mesh::chunkSize = 1024 static
Referenced by AddNodeWithID(), adjustmyCellsCapacity(), SMDS_Down1D::allocate(), SMDS_Down2D::allocate(), SMDS_Down3D::allocate(), registerElement(), SMDS_CellLinks::ResizeForPoint(), and SMDS_Mesh().
myBallPool
ObjectPool<SMDS_BallElement>* SMDS_Mesh::myBallPool protected
Referenced by AddBallWithID(), Clear(), RemoveElement(), RemoveFreeElement(), SMDS_Mesh(), and ~SMDS_Mesh().
myCellIdVtkToSmds
std::vector<int> SMDS_Mesh::myCellIdVtkToSmds protected
for cells only: index = ID in vtkUnstructuredGrid, value = ID for SMDS users
Referenced by Clear(), SMDS_MeshElementIDFactory::Clear(), SMESHDS_Mesh::compactMesh(), fromVtkToSmds(), incrementCellsCapacity(), registerElement(), SMDS_MeshElementIDFactory::ReleaseID(), and SMDS_Mesh().
myCells
SetOfCells SMDS_Mesh::myCells protected
SMDS_MeshCells refer to vtk cells (vtk id != index in myCells),store reference to this mesh, and sub-shape.
Referenced by Add0DElementWithID(), AddBallWithID(), AddEdgeWithID(), AddFaceFromVtkIdsWithID(), AddFaceWithID(), AddPolygonalFaceWithID(), AddPolyhedralVolumeWithID(), AddQuadPolygonalFaceWithID(), AddVolumeFromVtkIdsWithID(), AddVolumeWithID(), Clear(), SMESHDS_Mesh::compactMesh(), createQuadrangle(), createTriangle(), edgesIterator(), elementEntityIterator(), elementGeomIterator(), elementsIterator(), facesIterator(), FindEdgeOrCreate(), FindElement(), incrementCellsCapacity(), SMDS_MeshElementIDFactory::MeshElement(), registerElement(), RemoveElement(), RemoveFreeElement(), SMDS_Mesh(), SMDS_MeshElementIDFactory::updateMinMax(), and volumesIterator().
myChildren
std::list<SMDS_Mesh *> SMDS_Mesh::myChildren protected
Referenced by AddSubMesh(), Clear(), NbSubMesh(), RemoveSubMesh(), and ~SMDS_Mesh().
myCompactTime
unsigned long SMDS_Mesh::myCompactTime protected
Referenced by isCompacted().
myEdgePool
ObjectPool<SMDS_VtkEdge>* SMDS_Mesh::myEdgePool protected
Referenced by AddEdgeWithID(), Clear(), FindEdgeOrCreate(), RemoveElement(), RemoveFreeElement(), SMDS_Mesh(), and ~SMDS_Mesh().
myElementIDFactory
SMDS_MeshElementIDFactory* SMDS_Mesh::myElementIDFactory protected
Referenced by Add0DElement(), Add0DElementWithID(), AddBall(), AddEdge(), AddFace(), AddFaceFromVtkIds(), AddFaceWithID(), AddPolygonalFace(), AddPolyhedralVolume(), AddQuadPolygonalFace(), AddVolume(), AddVolumeFromVtkIds(), AddVolumeWithID(), Clear(), SMESHDS_Mesh::compactMesh(), FindEdgeOrCreate(), FindFaceOrCreate(), GetElementType(), MaxElementID(), MinElementID(), registerElement(), RemoveElement(), RemoveFreeElement(), Renumber(), SMDS_Mesh(), and ~SMDS_Mesh().
myFacePool
ObjectPool<SMDS_VtkFace>* SMDS_Mesh::myFacePool protected
Referenced by AddFaceFromVtkIdsWithID(), AddFaceWithID(), AddPolygonalFaceWithID(), AddQuadPolygonalFaceWithID(), Clear(), createQuadrangle(), createTriangle(), RemoveElement(), RemoveFreeElement(), SMDS_Mesh(), and ~SMDS_Mesh().
myGrid
SMDS_UnstructuredGrid* SMDS_Mesh::myGrid protected
actual nodes coordinates, cells definition and reverse connectivity are stored in a vtkUnstructuredGrid
Referenced by AddBallWithID(), AddEdgeWithID(), AddFaceFromVtkIdsWithID(), AddFaceWithID(), AddPolygonalFaceWithID(), AddPolyhedralVolumeWithID(), AddQuadPolygonalFaceWithID(), AddVolumeFromVtkIdsWithID(), AddVolumeWithID(), adjustStructure(), SMESHDS_Mesh::BuildDownWardConnectivity(), SMESHDS_Mesh::CleanDownWardConnectivity(), Clear(), SMESHDS_Mesh::compactMesh(), createQuadrangle(), createTriangle(), dumpGrid(), FindEdgeOrCreate(), SMESHDS_Mesh::ModifyCellNodes(), RemoveElement(), RemoveFreeElement(), SMDS_Mesh(), updateBoundingBox(), and ~SMDS_Mesh().
myHasConstructionEdges
bool SMDS_Mesh::myHasConstructionEdges protected
Referenced by hasConstructionEdges(), and setConstructionEdges().
myHasConstructionFaces
bool SMDS_Mesh::myHasConstructionFaces protected
Referenced by hasConstructionFaces(), and setConstructionFaces().
myHasInverseElements
bool SMDS_Mesh::myHasInverseElements protected
Referenced by hasInverseElements(), and setInverseElements().
myInfo
SMDS_MeshInfo SMDS_Mesh::myInfo protected
Referenced by Add0DElementWithID(), AddBallWithID(), AddEdgeWithID(), AddFaceFromVtkIdsWithID(), AddFaceWithID(), AddNodeWithID(), AddPolygonalFaceWithID(), AddPolyhedralVolumeWithID(), AddQuadPolygonalFaceWithID(), AddVolumeFromVtkIdsWithID(), AddVolumeWithID(), Clear(), createQuadrangle(), createTriangle(), FindEdgeOrCreate(), Nb0DElements(), NbBalls(), NbEdges(), NbFaces(), NbNodes(), NbVolumes(), RemoveElement(), and RemoveFreeElement().
myMeshId
int SMDS_Mesh::myMeshId protected
index of this SMDS_mesh in the static vector<SMDS_Mesh*> _meshList
Referenced by AddNodeWithID(), registerElement(), and SMDS_Mesh().
myModified
bool SMDS_Mesh::myModified protected
any add, remove or change of node or cell
Referenced by AddNodeWithID(), Clear(), and Modified().
myModifTime
unsigned long SMDS_Mesh::myModifTime protected
use a counter to keep track of modifications
Referenced by Clear(), GetMTime(), isCompacted(), and Modified().
myNodeIDFactory
SMDS_MeshNodeIDFactory* SMDS_Mesh::myNodeIDFactory protected
Referenced by Add0DElementWithID(), AddBallWithID(), AddEdgeWithID(), AddFaceWithID(), AddNode(), AddNodeWithID(), AddPolygonalFaceWithID(), AddPolyhedralVolumeWithID(), AddQuadPolygonalFaceWithID(), AddVolumeWithID(), adjustStructure(), Clear(), SMESHDS_Mesh::compactMesh(), GetElementType(), RemoveElement(), RemoveFreeElement(), Renumber(), SMDS_Mesh(), and ~SMDS_Mesh().
myNodeIds
std::vector<vtkIdType> SMDS_Mesh::myNodeIds protected
a buffer to speed up elements addition by excluding some memory allocation
Referenced by AddEdgeWithID(), AddFaceWithID(), AddPolygonalFaceWithID(), AddPolyhedralVolumeWithID(), AddQuadPolygonalFaceWithID(), AddVolumeWithID(), createQuadrangle(), createTriangle(), and FindEdgeOrCreate().
myNodeMax
int SMDS_Mesh::myNodeMax protected
Referenced by MaxNodeID(), and updateNodeMinMax().
myNodeMin
int SMDS_Mesh::myNodeMin protected
Referenced by MinNodeID(), and updateNodeMinMax().
myNodePool
ObjectPool<SMDS_MeshNode>* SMDS_Mesh::myNodePool protected
Small objects like SMDS_MeshNode are allocated by chunks to limit memory costs of new.
Referenced by AddNodeWithID(), Clear(), RemoveElement(), RemoveFreeElement(), SMDS_Mesh(), and ~SMDS_Mesh().
myNodes
SetOfNodes SMDS_Mesh::myNodes protected
SMDS_MeshNodes refer to vtk nodes (vtk id = index in myNodes),store reference to this mesh, and sub-shape.
Referenced by AddNodeWithID(), Clear(), SMESHDS_Mesh::compactMesh(), elementEntityIterator(), elementsIterator(), FindNode(), FindNodeVtk(), incrementCellsCapacity(), incrementNodesCapacity(), nodesIterator(), RemoveElement(), RemoveFreeElement(), SMDS_Mesh(), updateBoundingBox(), and updateNodeMinMax().
myParent
SMDS_Mesh* SMDS_Mesh::myParent protected
Referenced by Clear(), RemoveFromParent(), and ~SMDS_Mesh().
myVolumePool
ObjectPool<SMDS_VtkVolume>* SMDS_Mesh::myVolumePool protected
Small objects like SMDS_VtkVolume are allocated by chunks to limit memory costs of new.
Referenced by AddPolyhedralVolumeWithID(), AddVolumeFromVtkIdsWithID(), AddVolumeWithID(), Clear(), RemoveElement(), RemoveFreeElement(), SMDS_Mesh(), and ~SMDS_Mesh().
xmax
double SMDS_Mesh::xmax protected
Referenced by Clear(), getMaxDim(), and updateBoundingBox().
xmin
double SMDS_Mesh::xmin protected
Referenced by Clear(), getMaxDim(), and updateBoundingBox().
ymax
double SMDS_Mesh::ymax protected
Referenced by Clear(), getMaxDim(), and updateBoundingBox().
ymin
double SMDS_Mesh::ymin protected
Referenced by Clear(), getMaxDim(), and updateBoundingBox().
zmax
double SMDS_Mesh::zmax protected
zmin
double SMDS_Mesh::zmin protected
Referenced by Clear(), getMaxDim(), and updateBoundingBox().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_Mesh.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_Mesh.cpp