FreeCAD: Gui::SoFCVectorizeSVGAction Class Reference
Gui::SoFCVectorizeSVGAction Class Reference
#include <SoFCVectorizeSVGAction.h>
Public Member Functions
virtual bool getBackgroundState (void) const
virtual double getLineWidth (void) const
SoSVGVectorOutput * getSVGOutput (void) const
virtual bool getUseMM (void) const
virtual void setBackgroundState (bool b)
virtual void setLineWidth (double w)
virtual void setUseMM (bool b)
SoFCVectorizeSVGAction (void)
virtual ~SoFCVectorizeSVGAction ()
Static Public Member Functions
static void initClass (void)
Protected Member Functions
virtual void printBackground (void) const
virtual void printFooter (void) const
virtual void printHeader (void) const
virtual void printItem (const SoVectorizeItem *item) const
virtual void printViewport (void) const
Friends
class SoFCVectorizeSVGActionP
Constructor & Destructor Documentation
SoFCVectorizeSVGAction()
SoFCVectorizeSVGAction::SoFCVectorizeSVGAction (void)
References SoFCVectorizeSVGActionP.
~SoFCVectorizeSVGAction()
SoFCVectorizeSVGAction::~SoFCVectorizeSVGAction () virtual
Member Function Documentation
getBackgroundState()
virtual bool Gui::SoFCVectorizeSVGAction::getBackgroundState (void) const virtual
Referenced by printBackground().
getLineWidth()
virtual double Gui::SoFCVectorizeSVGAction::getLineWidth (void) const virtual
Referenced by printBackground(), Gui::SoFCVectorizeSVGActionP::printLine(), and Gui::SoFCVectorizeSVGActionP::printTriangle().
getSVGOutput()
SoSVGVectorOutput * SoFCVectorizeSVGAction::getSVGOutput (void) const
Referenced by printBackground(), printFooter(), printHeader(), Gui::SoFCVectorizeSVGActionP::printLine(), Gui::SoFCVectorizeSVGActionP::printText(), and Gui::SoFCVectorizeSVGActionP::printTriangle().
getUseMM()
virtual bool Gui::SoFCVectorizeSVGAction::getUseMM (void) const virtual
Referenced by printHeader().
initClass()
void SoFCVectorizeSVGAction::initClass (void) static
Referenced by Gui::SoFCDB::init().
printBackground()
void SoFCVectorizeSVGAction::printBackground (void) const protected virtual
References getBackgroundState(), Gui::SoSVGVectorOutput::getFileStream(), getLineWidth(), and getSVGOutput().
printFooter()
void SoFCVectorizeSVGAction::printFooter (void) const protected virtual
References Gui::SoSVGVectorOutput::getFileStream(), and getSVGOutput().
printHeader()
void SoFCVectorizeSVGAction::printHeader (void) const protected virtual
References Gui::SoSVGVectorOutput::getFileStream(), getSVGOutput(), and getUseMM().
printItem()
void SoFCVectorizeSVGAction::printItem (const SoVectorizeItem * item) const protected virtual
References SoVectorizeItem::IMAGE, SoVectorizeItem::LINE, SoVectorizeItem::POINT, SoVectorizeItem::TEXT, SoVectorizeItem::TRIANGLE, and SoVectorizeItem::type.
printViewport()
void SoFCVectorizeSVGAction::printViewport (void) const protected virtual
setBackgroundState()
virtual void Gui::SoFCVectorizeSVGAction::setBackgroundState (bool b) virtual
Referenced by TechDrawGui::Grabber3d::execVectorizeAction().
setLineWidth()
virtual void Gui::SoFCVectorizeSVGAction::setLineWidth (double w) virtual
Referenced by TechDrawGui::Grabber3d::execVectorizeAction().
setUseMM()
virtual void Gui::SoFCVectorizeSVGAction::setUseMM (bool b) virtual
Referenced by TechDrawGui::Grabber3d::execVectorizeAction().
Friends And Related Function Documentation
SoFCVectorizeSVGActionP
friend class SoFCVectorizeSVGActionP friend
Referenced by SoFCVectorizeSVGAction().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SoFCVectorizeSVGAction.h
Sources/FreeCAD/src/Gui/SoFCVectorizeSVGAction.cpp