FreeCAD: PathScripts.post.dynapath_post Namespace Reference
PathScripts.post.dynapath_post Namespace Reference
Functions
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
def processArguments (argstring)
Variables
action
string COMMAND_SPACE = " "
dictionary CORNER_MAX = {'x': 340, 'y': -355, 'z': -150}
dictionary CORNER_MIN = {'x': -340, 'y': 0, 'z': 0}
default
help
int LINENR = 1
string MACHINE_NAME = "Tree MM"
bool MODAL = False
now = datetime.datetime.now()
bool OUTPUT_COMMENTS = True
bool OUTPUT_HEADER = True
bool OUTPUT_LINE_NUMBERS = False
parser
string POST_OPERATION = ''''''
string POSTAMBLE
string PRE_OPERATION = ''''''
string PREAMBLE
pythonopen = open
bool SHOW_EDITOR = True
string TOOL_CHANGE = ''''''
string TOOLTIP
TOOLTIP_ARGS = parser.format_help()
string UNIT_FORMAT = 'mm'
string UNIT_SPEED_FORMAT = 'mm/min'
string UNITS = "G21"
Function Documentation
export()
def PathScripts.post.dynapath_post.export (objectslist, filename, argstring)
References PathScripts.post.dynapath_post.linenumber(), PathScripts.post.dynapath_post.parse(), PathScripts.post.dynapath_post.processArguments(), and PathScripts.post.dynapath_post.pythonopen.
linenumber()
def PathScripts.post.dynapath_post.linenumber ()
Referenced by PathScripts.post.dynapath_post.export(), and PathScripts.post.dynapath_post.parse().
parse()
def PathScripts.post.dynapath_post.parse (pathobj)
References PathScripts.post.dynapath_post.linenumber().
Referenced by PathScripts.post.dynapath_post.export().
processArguments()
def PathScripts.post.dynapath_post.processArguments (argstring)
Referenced by PathScripts.post.dynapath_post.export().
Variable Documentation
action
PathScripts.post.dynapath_post.action
COMMAND_SPACE
string PathScripts.post.dynapath_post.COMMAND_SPACE = " "
CORNER_MAX
dictionary PathScripts.post.dynapath_post.CORNER_MAX = {'x': 340, 'y': -355, 'z': -150}
CORNER_MIN
dictionary PathScripts.post.dynapath_post.CORNER_MIN = {'x': -340, 'y': 0, 'z': 0}
default
PathScripts.post.dynapath_post.default
help
PathScripts.post.dynapath_post.help
LINENR
int PathScripts.post.dynapath_post.LINENR = 1
MACHINE_NAME
string PathScripts.post.dynapath_post.MACHINE_NAME = "Tree MM"
MODAL
bool PathScripts.post.dynapath_post.MODAL = False
now
PathScripts.post.dynapath_post.now = datetime.datetime.now()
OUTPUT_COMMENTS
bool PathScripts.post.dynapath_post.OUTPUT_COMMENTS = True
OUTPUT_HEADER
bool PathScripts.post.dynapath_post.OUTPUT_HEADER = True
OUTPUT_LINE_NUMBERS
bool PathScripts.post.dynapath_post.OUTPUT_LINE_NUMBERS = False
parser
PathScripts.post.dynapath_post.parser
Initial value:
 =  argparse.ArgumentParser(prog='dynapath_post',
         add_help=False)
POST_OPERATION
string PathScripts.post.dynapath_post.POST_OPERATION = ''''''
POSTAMBLE
string PathScripts.post.dynapath_post.POSTAMBLE
Initial value:
 =  '''M09
 M05
 G80
 G40
 G17
 G90
 M30
 '''
PRE_OPERATION
string PathScripts.post.dynapath_post.PRE_OPERATION = ''''''
PREAMBLE
string PathScripts.post.dynapath_post.PREAMBLE
Initial value:
 =  '''G17
 G90
 ;G90.1 ;needed for simulation only
 G80
 G40
 '''
pythonopen
PathScripts.post.dynapath_post.pythonopen = open
Referenced by PathScripts.post.dynapath_post.export().
SHOW_EDITOR
bool PathScripts.post.dynapath_post.SHOW_EDITOR = True
TOOL_CHANGE
string PathScripts.post.dynapath_post.TOOL_CHANGE = ''''''
TOOLTIP
string PathScripts.post.dynapath_post.TOOLTIP
TOOLTIP_ARGS
PathScripts.post.dynapath_post.TOOLTIP_ARGS = parser.format_help()
UNIT_FORMAT
string PathScripts.post.dynapath_post.UNIT_FORMAT = 'mm'
UNIT_SPEED_FORMAT
string PathScripts.post.dynapath_post.UNIT_SPEED_FORMAT = 'mm/min'
UNITS
string PathScripts.post.dynapath_post.UNITS = "G21"