FreeCAD: SMESH_subMeshEventListener Class Reference
SMESH_subMeshEventListener Class Reference
A base for objects reacting on submesh events.
#include <SMESH_subMeshEventListener.hxx>
Public Member Functions
virtual void BeforeDelete (SMESH_subMesh *subMesh, SMESH_subMeshEventListenerData *data)
const char * GetName () const
bool IsDeletable () const
virtual void ProcessEvent (const int event, const int eventType, SMESH_subMesh *subMesh, SMESH_subMeshEventListenerData *data, const SMESH_Hypothesis *hyp=0)
Do something on a certain event.
SMESH_subMeshEventListener (bool isDeletable, const char *name)
virtual ~SMESH_subMeshEventListener ()
Friends
class SMESH_subMesh
Detailed Description
A base for objects reacting on submesh events.
Constructor & Destructor Documentation
SMESH_subMeshEventListener()
SMESH_subMeshEventListener::SMESH_subMeshEventListener (bool isDeletable, const char * name)
~SMESH_subMeshEventListener()
virtual SMESH_subMeshEventListener::~SMESH_subMeshEventListener () virtual
Member Function Documentation
BeforeDelete()
virtual void SMESH_subMeshEventListener::BeforeDelete (SMESH_subMesh * subMesh, SMESH_subMeshEventListenerData * data) virtual
GetName()
const char * SMESH_subMeshEventListener::GetName () const
Referenced by SMESH_subMesh::setEventListener().
IsDeletable()
bool SMESH_subMeshEventListener::IsDeletable () const
Referenced by SMESH_subMesh::setEventListener().
ProcessEvent()
void SMESH_subMeshEventListener::ProcessEvent (const int event, const int eventType, SMESH_subMesh * subMesh, SMESH_subMeshEventListenerData * data, const SMESH_Hypothesis * hyp = 0) virtual
Do something on a certain event.
Parameters
event - algo_event or compute_event itself (of SMESH_subMesh)
eventType - ALGO_EVENT or COMPUTE_EVENT (of SMESH_subMesh)
subMesh - the submesh where the event occurs
data - listener data stored in the subMesh
hyp - hypothesis, if eventType is algo_event
The base implementation (see SMESH_subMesh.cxx) translates CLEAN event to the subMeshes stored in the listener data. Also it sends SUBMESH_COMPUTED event in case of successful COMPUTE event.
Parameters
event - algo_event or compute_event itself
eventType - algo_event or compute_event
subMesh - the submesh where the event occurs
data - listener data stored in the subMesh
hyp - hypothesis, if eventType is algo_event
The base implementation translates CLEAN event to the subMesh stored in listener data. Also it sends SUBMESH_COMPUTED event in case of successful COMPUTE event.
Reimplemented in VISCOUS_3D::_ShrinkShapeListener, VISCOUS_2D::_ProxyMeshHolder, and VISCOUS_3D::_ViscousListener.
References SMESH_subMesh::CLEAN, SMESH_subMesh::COMPUTE, SMESH_subMesh::COMPUTE_EVENT, SMESH_subMesh::COMPUTE_OK, SMESH_subMesh::COMPUTE_SUBMESH, SMESH_subMesh::GetComputeState(), and SMESH_subMesh::SUBMESH_COMPUTED.
Referenced by VISCOUS_3D::_ShrinkShapeListener::ProcessEvent().
Friends And Related Function Documentation
SMESH_subMesh
friend class SMESH_subMesh friend
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_subMeshEventListener.hxx
FreeCAD/src/3rdParty/salomesmesh/src/SMESH/SMESH_subMesh.cpp