FreeCAD: PathScripts.post.philips_post Namespace Reference
PathScripts.post.philips_post Namespace Reference
Functions
def angleUnder180 (command, lastX, lastY, x, y, i, j)
def export (objectslist, filename, argstring)
def linenumberify (GCodeString)
def mapGCode (command)
def mkHeader (selection)
def processArguments (argstring)
Variables
bool ABSOLUTE_CIRCLE_CENTER = True
action
int AXIS_DECIMALS = 3
string COMMAND_SPACE = " "
string COMMENT = ""
dictionary CORNER_MAX = {"x": 591.5, "y": 391.498, "z": 391.5}
dictionary CORNER_MIN = {"x": -51.877, "y": 0, "z": 0}
int FEED_DECIMALS = 2
string GCODE_FOOTER = "M30"
string GCODE_HEADER = ""
dictionary GCODE_MAP
help
int linenr = 0
int LINENUMBER_INCREMENT = 1
bool LINENUMBERS = True
string MACHINE_NAME = "Maho 600E"
bool MODAL = True
list MODALPARAMS = ["X", "Y", "Z", "S", "F"]
parser = argparse.ArgumentParser(prog="philips", add_help=False)
pythonopen = open
bool RADIUS_COMMENT = True
bool SHOW_EDITOR = True
int SPINDLE_DECIMALS = 0
int STARTLINENR = 1
bool SUPPRESS_ZERO_FEED = True
bool SWAP_G2_G3 = True
tuple SWAP_Y_Z
string TOOLTIP
TOOLTIP_ARGS = parser.format_help()
string UNITS = "G21"
bool UNITS_INCLUDED = False
bool USE_RADIUS_IF_POSSIBLE = True
Function Documentation
angleUnder180()
def PathScripts.post.philips_post.angleUnder180 (command, lastX, lastY, x, y, i, j)
Referenced by PathScripts.post.philips_post.export().
export()
def PathScripts.post.philips_post.export (objectslist, filename, argstring)
References PathScripts.post.philips_post.angleUnder180(), PathScripts.post.philips_post.linenumberify(), PathScripts.post.philips_post.mapGCode(), PathScripts.post.philips_post.mkHeader(), and PathScripts.post.philips_post.pythonopen.
linenumberify()
def PathScripts.post.philips_post.linenumberify (GCodeString)
Referenced by PathScripts.post.philips_post.export(), and PathScripts.post.philips_post.mkHeader().
mapGCode()
def PathScripts.post.philips_post.mapGCode (command)
Referenced by PathScripts.post.philips_post.export().
mkHeader()
def PathScripts.post.philips_post.mkHeader (selection)
References PathScripts.post.philips_post.linenumberify().
Referenced by PathScripts.post.philips_post.export().
processArguments()
def PathScripts.post.philips_post.processArguments (argstring)
Variable Documentation
ABSOLUTE_CIRCLE_CENTER
bool PathScripts.post.philips_post.ABSOLUTE_CIRCLE_CENTER = True
action
PathScripts.post.philips_post.action
AXIS_DECIMALS
int PathScripts.post.philips_post.AXIS_DECIMALS = 3
COMMAND_SPACE
string PathScripts.post.philips_post.COMMAND_SPACE = " "
COMMENT
string PathScripts.post.philips_post.COMMENT = ""
CORNER_MAX
dictionary PathScripts.post.philips_post.CORNER_MAX = {"x": 591.5, "y": 391.498, "z": 391.5}
CORNER_MIN
dictionary PathScripts.post.philips_post.CORNER_MIN = {"x": -51.877, "y": 0, "z": 0}
FEED_DECIMALS
int PathScripts.post.philips_post.FEED_DECIMALS = 2
GCODE_FOOTER
string PathScripts.post.philips_post.GCODE_FOOTER = "M30"
GCODE_HEADER
string PathScripts.post.philips_post.GCODE_HEADER = ""
GCODE_MAP
dictionary PathScripts.post.philips_post.GCODE_MAP
Initial value:
=  {
    "M1": "M0",
    "M6": "M66",
    "G20": "G70",
    "G21": "G71",
}
help
PathScripts.post.philips_post.help
linenr
int PathScripts.post.philips_post.linenr = 0
LINENUMBER_INCREMENT
int PathScripts.post.philips_post.LINENUMBER_INCREMENT = 1
LINENUMBERS
bool PathScripts.post.philips_post.LINENUMBERS = True
MACHINE_NAME
string PathScripts.post.philips_post.MACHINE_NAME = "Maho 600E"
MODAL
bool PathScripts.post.philips_post.MODAL = True
MODALPARAMS
list PathScripts.post.philips_post.MODALPARAMS = ["X", "Y", "Z", "S", "F"]
parser
PathScripts.post.philips_post.parser = argparse.ArgumentParser(prog="philips", add_help=False)
pythonopen
PathScripts.post.philips_post.pythonopen = open
Referenced by PathScripts.post.philips_post.export().
RADIUS_COMMENT
bool PathScripts.post.philips_post.RADIUS_COMMENT = True
SHOW_EDITOR
bool PathScripts.post.philips_post.SHOW_EDITOR = True
SPINDLE_DECIMALS
int PathScripts.post.philips_post.SPINDLE_DECIMALS = 0
STARTLINENR
int PathScripts.post.philips_post.STARTLINENR = 1
SUPPRESS_ZERO_FEED
bool PathScripts.post.philips_post.SUPPRESS_ZERO_FEED = True
SWAP_G2_G3
bool PathScripts.post.philips_post.SWAP_G2_G3 = True
SWAP_Y_Z
tuple PathScripts.post.philips_post.SWAP_Y_Z
Initial value:
=  (
    True  # machines with an angle milling head do not switch axes, so we do it here
)
TOOLTIP
string PathScripts.post.philips_post.TOOLTIP
Initial value:
=  """Post processor for Maho M 600E mill
Machines with Philips or Heidenhain control should be very easy to adapt.
The post processor is configurable by changing the values of constants.
No programming experience required. This can make a generated g-code
program more readable and since older machines have very
limited memory it seems sensible to reduce the number of commands and
parameters, like e.g. suppress the units in the header and at every hop.
"""
TOOLTIP_ARGS
PathScripts.post.philips_post.TOOLTIP_ARGS = parser.format_help()
UNITS
string PathScripts.post.philips_post.UNITS = "G21"
UNITS_INCLUDED
bool PathScripts.post.philips_post.UNITS_INCLUDED = False
USE_RADIUS_IF_POSSIBLE
bool PathScripts.post.philips_post.USE_RADIUS_IF_POSSIBLE = True