FreeCAD: Sandbox::CustomCallableEvent Class Reference
Sandbox::CustomCallableEvent Class Reference
Public Member Functions
CustomCallableEvent (const AbstractCallable &call)
void execute ()
~CustomCallableEvent ()
Public Member Functions inherited from Sandbox::AbstractCustomProtectorEvent
AbstractCustomProtectorEvent ()
~AbstractCustomProtectorEvent ()
Protected Attributes
const AbstractCallable & callable
Additional Inherited Members
Public Attributes inherited from Sandbox::AbstractCustomProtectorEvent
QSemaphore * semaphore
Constructor & Destructor Documentation
CustomCallableEvent()
Sandbox::CustomCallableEvent::CustomCallableEvent (const AbstractCallable & call)
~CustomCallableEvent()
Sandbox::CustomCallableEvent::~CustomCallableEvent ()
Member Function Documentation
execute()
void Sandbox::CustomCallableEvent::execute (void) virtual
Implements Sandbox::AbstractCustomProtectorEvent.
References callable.
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), PathScripts.PathDressupDogbone.ObjectDressup::boneStateList(), ArchSite.Compass::buildCoordinates(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::generateTags(), ArchPanel.PanelCut::getWires(), ArchSchedule.CommandArchSchedule::IsActive(), Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), FeaturePython.DistanceBolt::onChanged(), PathScripts.PathStock.StockFromBase::onChanged(), PathScripts.PathStock.StockCreateBox::onChanged(), PathScripts.PathStock.StockCreateCylinder::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), draftobjects.patharray.PathArray::onDocumentRestored(), and draftobjects.pathtwistedarray.PathTwistedArray::onDocumentRestored().
Member Data Documentation
callable
const AbstractCallable& Sandbox::CustomCallableEvent::callable protected
Referenced by execute().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sandbox/App/DocumentProtector.cpp