FreeCAD: Robot::Simulation Class Reference
Robot::Simulation Class Reference
Algo class for projecting shapes and creating SVG output of it.
#include <Simulation.h>
Public Member Functions
double getDuration (void)
double getLength (void)
Base::Placement getPosition (void)
double getVelocity (void)
void reset (void)
void setToTime (float t)
void setToWaypoint (unsigned int n)
Simulation (const Trajectory &Trac, Robot6Axis &Rob)
Constructor.
void step (double tick)
virtual ~Simulation ()
Public Attributes
double Axis [6]
double Pos
Robot6Axis & Rob
double startAxis [6]
Base::Placement Tool
Trajectory Trac
Detailed Description
Algo class for projecting shapes and creating SVG output of it.
Constructor & Destructor Documentation
Simulation()
Simulation::Simulation (const Trajectory & Trac, Robot::Robot6Axis & Rob)
Constructor.
References Robot::Robot6Axis::getAxis(), Robot::Trajectory::getSize(), Rob, setToTime(), startAxis, and Trac.
~Simulation()
Simulation::~Simulation () virtual
Member Function Documentation
getDuration()
double Robot::Simulation::getDuration (void)
References Robot::Trajectory::getDuration().
getLength()
double Robot::Simulation::getLength (void)
References Robot::Trajectory::getLength().
getPosition()
Base::Placement Robot::Simulation::getPosition (void)
References Robot::Trajectory::getPosition().
getVelocity()
double Robot::Simulation::getVelocity (void)
References Robot::Trajectory::getVelocity().
reset()
void Simulation::reset (void)
References Axis, Robot::Robot6Axis::getAxis(), Robot::Trajectory::getPosition(), Base::Placement::inverse(), Rob, Robot::Robot6Axis::setAxis(), Robot::Robot6Axis::setTo(), startAxis, Tool, and Trac.
Referenced by draftguitools.gui_trackers.gridTracker::set(), and RobotGui::TaskTrajectory::setTo().
setToTime()
void Simulation::setToTime (float t)
References Axis, Robot::Robot6Axis::getAxis(), Robot::Trajectory::getPosition(), Base::Placement::inverse(), Pos, Rob, Robot::Robot6Axis::setTo(), Tool, and Trac.
Referenced by RobotGui::TaskTrajectory::setTo(), RobotGui::TrajectorySimulate::setTo(), and Simulation().
setToWaypoint()
void Simulation::setToWaypoint (unsigned int n)
step()
void Simulation::step (double tick)
References Pos.
Referenced by draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_stretch.Stretch::addPoint(), draftguitools.gui_rotate.Rotate::handle_mouse_click_event(), draftguitools.gui_arcs.Arc::numericInput(), draftguitools.gui_polygons.Polygon::numericInput(), draftguitools.gui_rotate.Rotate::numericInput(), draftguitools.gui_arcs.Arc::numericRadius(), and draftguitools.gui_rotate.Rotate::numericRadius().
Member Data Documentation
Axis
double Robot::Simulation::Axis[6]
Referenced by reset(), RobotGui::TaskTrajectory::setTo(), RobotGui::TrajectorySimulate::setTo(), and setToTime().
Pos
double Robot::Simulation::Pos
Referenced by setToTime(), and step().
Rob
Robot6Axis& Robot::Simulation::Rob
Referenced by reset(), RobotGui::TaskTrajectory::setTo(), RobotGui::TrajectorySimulate::setTo(), setToTime(), and Simulation().
startAxis
double Robot::Simulation::startAxis[6]
Referenced by reset(), and Simulation().
Tool
Base::Placement Robot::Simulation::Tool
Referenced by PathScripts.PathToolEdit.ToolEditor::accept(), PathScripts.PathToolEdit.ToolEditor::reject(), reset(), RobotGui::TaskTrajectory::setTo(), setToTime(), RobotGui::TaskTrajectory::TaskTrajectory(), and RobotGui::TrajectorySimulate::TrajectorySimulate().
Trac
Trajectory Robot::Simulation::Trac
Referenced by reset(), setToTime(), and Simulation().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Robot/App/Simulation.h
FreeCAD/src/Mod/Robot/App/Simulation.cpp