FreeCAD: TechDraw::GeometryObject Class Reference
TechDraw::GeometryObject Class Reference
#include <GeometryObject.h>
Public Member Functions
int addCenterLine (TechDraw::BaseGeomPtr bg, std::string tag)
int addCosmeticEdge (Base::Vector3d start, Base::Vector3d end)
int addCosmeticEdge (Base::Vector3d start, Base::Vector3d end, std::string tagString)
int addCosmeticEdge (CosmeticEdge *ce)
int addCosmeticEdge (TechDraw::BaseGeomPtr base, std::string tagString)
int addCosmeticVertex (Base::Vector3d pos)
int addCosmeticVertex (Base::Vector3d pos, std::string tagString)
int addCosmeticVertex (CosmeticVertex *cv)
void addEdge (TechDraw::BaseGeomPtr bg)
void addFaceGeom (FacePtr f)
add a Face to Face Geometry
void addVertex (TechDraw::VertexPtr v)
Base::BoundBox3d calcBoundingBox () const
Returns 2D bounding box.
void clear ()
void clearFaceGeom ()
empty Face geometry
void extractGeometry (edgeClass category, bool visible)
add edges meeting filter criteria for category, visibility
GeometryObject (const std::string &parent, TechDraw::DrawView *parentObj)
Constructor.
const BaseGeomPtrVector & getEdgeGeometry () const
const std::vector< FacePtr > & getFaceGeometry () const
double getFocus (void)
TopoDS_Shape getHidHard (void)
TopoDS_Shape getHidIso (void)
TopoDS_Shape getHidOutline (void)
TopoDS_Shape getHidSeam (void)
TopoDS_Shape getHidSmooth (void)
const std::vector< VertexPtr > & getVertexGeometry () const
TopoDS_Shape getVisHard (void)
const BaseGeomPtrVector getVisibleFaceEdges (bool smooth, bool seam) const
TopoDS_Shape getVisIso (void)
TopoDS_Shape getVisOutline (void)
TopoDS_Shape getVisSeam (void)
TopoDS_Shape getVisSmooth (void)
void isPerspective (bool b)
bool isPerspective (void)
TopoDS_Shape projectFace (const TopoDS_Shape &face, const gp_Ax2 &CS)
void projectShape (const TopoDS_Shape &input, const gp_Ax2 &viewAxis)
set up a hidden line remover and project a shape with it
void projectShapeWithPolygonAlgo (const TopoDS_Shape &input, const gp_Ax2 &viewAxis)
set up a hidden line remover and project a shape with it
void pruneVertexGeom (Base::Vector3d center, double radius)
void setEdgeGeometry (BaseGeomPtrVector newGeoms)
void setFocus (double f)
void setIsoCount (int i)
void setParentName (std::string n)
void setVertexGeometry (std::vector< VertexPtr > newVerts)
void usePolygonHLR (bool b)
bool usePolygonHLR (void) const
virtual ~GeometryObject ()
Static Public Member Functions
static TopoDS_Shape invertGeometry (const TopoDS_Shape s)
Protected Member Functions
void addGeomFromCompound (TopoDS_Shape edgeCompound, edgeClass category, bool visible)
update edgeGeom and vertexGeom from Compound of edges
bool findVertex (Base::Vector3d v)
does this GeometryObject already have this vertex
TechDraw::DrawViewDetail * isParentDetail (void)
bool isWithinArc (double theta, double first, double last, bool cw) const
Protected Attributes
BaseGeomPtrVector edgeGeom
std::vector< FacePtr > faceGeom
TopoDS_Shape hidHard
TopoDS_Shape hidIso
TopoDS_Shape hidOutline
TopoDS_Shape hidSeam
TopoDS_Shape hidSmooth
double m_focus
int m_isoCount
bool m_isPersp
TechDraw::DrawView * m_parent
std::string m_parentName
bool m_usePolygonHLR
std::vector< VertexPtr > vertexGeom
TopoDS_Shape visHard
TopoDS_Shape visIso
TopoDS_Shape visOutline
TopoDS_Shape visSeam
TopoDS_Shape visSmooth
Constructor & Destructor Documentation
GeometryObject()
GeometryObject::GeometryObject (const std::string & parent, TechDraw::DrawView * parentObj)
Constructor.
~GeometryObject()
GeometryObject::~GeometryObject () virtual
References clear().
Member Function Documentation
addCenterLine()
int GeometryObject::addCenterLine (TechDraw::BaseGeomPtr bg, std::string tag)
References edgeGeom.
Referenced by TechDraw::DrawViewPart::add1CLToGE(), and TechDraw::DrawViewPart::addCenterLinesToGeom().
addCosmeticEdge() [1/4]
int GeometryObject::addCosmeticEdge (Base::Vector3d start, Base::Vector3d end)
References TechDraw::BaseGeom::baseFactory(), and edgeGeom.
addCosmeticEdge() [2/4]
int GeometryObject::addCosmeticEdge (Base::Vector3d start, Base::Vector3d end, std::string tagString)
References TechDraw::BaseGeom::baseFactory(), and edgeGeom.
addCosmeticEdge() [3/4]
int GeometryObject::addCosmeticEdge (CosmeticEdge * ce)
References edgeGeom, TechDraw::DrawView::getScale(), TechDraw::CosmeticEdge::getTagAsString(), m_parent, and TechDraw::CosmeticEdge::scaledGeometry().
Referenced by TechDraw::DrawViewPart::add1CEToGE(), and TechDraw::DrawViewPart::addCosmeticEdgesToGeom().
addCosmeticEdge() [4/4]
int GeometryObject::addCosmeticEdge (TechDraw::BaseGeomPtr base, std::string tagString)
References edgeGeom.
addCosmeticVertex() [1/3]
int GeometryObject::addCosmeticVertex (Base::Vector3d pos)
References Base::Console(), Base::ConsoleSingleton::Message(), and vertexGeom.
addCosmeticVertex() [2/3]
int GeometryObject::addCosmeticVertex (Base::Vector3d pos, std::string tagString)
References vertexGeom.
addCosmeticVertex() [3/3]
int GeometryObject::addCosmeticVertex (CosmeticVertex * cv)
References TechDraw::DrawView::getScale(), TechDraw::CosmeticVertex::getTagAsString(), m_parent, TechDraw::CosmeticVertex::scaled(), and vertexGeom.
Referenced by TechDraw::DrawViewPart::add1CVToGV(), and TechDraw::DrawViewPart::addCosmeticVertexesToGeom().
addEdge()
void GeometryObject::addEdge (TechDraw::BaseGeomPtr bg)
References edgeGeom.
Referenced by PathScripts.PathDressupHoldingTags.MapWireToTag::add().
addFaceGeom()
void GeometryObject::addFaceGeom (FacePtr f)
add a Face to Face Geometry
References faceGeom.
Referenced by TechDraw::DrawViewPart::extractFaces().
addGeomFromCompound()
void GeometryObject::addGeomFromCompound (TopoDS_Shape edgeCompound, edgeClass category, bool visible) protected
update edgeGeom and vertexGeom from Compound of edges
References TechDraw::BaseGeom::baseFactory(), Base::Console(), edgeGeom, TechDraw::DrawUtil::isCrazy(), TechDraw::DrawUtil::isZeroEdge(), Base::ConsoleSingleton::Log(), and vertexGeom.
Referenced by extractGeometry().
addVertex()
void GeometryObject::addVertex (TechDraw::VertexPtr v)
References vertexGeom.
Referenced by TechDraw::DrawViewPart::addShapes2d().
calcBoundingBox()
Base::BoundBox3d GeometryObject::calcBoundingBox () const
Returns 2D bounding box.
References Base::Console(), edgeGeom, and Base::ConsoleSingleton::Log().
Referenced by TechDraw::DrawViewPart::buildGeometryObject().
clear()
void GeometryObject::clear (void)
References edgeGeom, faceGeom, and vertexGeom.
Referenced by projectShape(), projectShapeWithPolygonAlgo(), and ~GeometryObject().
clearFaceGeom()
void GeometryObject::clearFaceGeom ()
empty Face geometry
References faceGeom.
Referenced by TechDraw::DrawViewPart::extractFaces().
extractGeometry()
void GeometryObject::extractGeometry (edgeClass category, bool visible)
add edges meeting filter criteria for category, visibility
References addGeomFromCompound(), Base::Console(), TechDraw::ecHARD, TechDraw::ecOUTLINE, TechDraw::ecSEAM, TechDraw::ecSMOOTH, TechDraw::ecUVISO, hidHard, hidIso, hidOutline, hidSeam, hidSmooth, visHard, visIso, visOutline, visSeam, visSmooth, and Base::ConsoleSingleton::Warning().
Referenced by TechDraw::DrawProjectSplit::buildGeometryObject(), and TechDraw::DrawViewPart::buildGeometryObject().
findVertex()
bool GeometryObject::findVertex (Base::Vector3d v) protected
does this GeometryObject already have this vertex
References DraftVecUtils::dist(), and vertexGeom.
getEdgeGeometry()
const BaseGeomPtrVector & TechDraw::GeometryObject::getEdgeGeometry () const
Referenced by TechDraw::DrawViewPart::buildGeometryObject(), and TechDraw::DrawViewPart::getEdgeGeometry().
getFaceGeometry()
const std::vector< FacePtr > & TechDraw::GeometryObject::getFaceGeometry () const
Referenced by TechDraw::DrawViewPart::getFaceGeometry().
getFocus()
double TechDraw::GeometryObject::getFocus (void)
getHidHard()
TopoDS_Shape TechDraw::GeometryObject::getHidHard (void)
getHidIso()
TopoDS_Shape TechDraw::GeometryObject::getHidIso (void)
getHidOutline()
TopoDS_Shape TechDraw::GeometryObject::getHidOutline (void)
getHidSeam()
TopoDS_Shape TechDraw::GeometryObject::getHidSeam (void)
getHidSmooth()
TopoDS_Shape TechDraw::GeometryObject::getHidSmooth (void)
getVertexGeometry()
const std::vector< VertexPtr > & TechDraw::GeometryObject::getVertexGeometry () const
Referenced by TechDraw::DrawViewPart::getVertexGeometry(), and pruneVertexGeom().
getVisHard()
TopoDS_Shape TechDraw::GeometryObject::getVisHard (void)
getVisibleFaceEdges()
const BaseGeomPtrVector GeometryObject::getVisibleFaceEdges (bool smooth, bool seam) const
References TechDraw::ecHARD, TechDraw::ecOUTLINE, TechDraw::ecSEAM, TechDraw::ecSMOOTH, and edgeGeom.
Referenced by TechDraw::DrawViewPart::extractFaces(), TechDraw::DrawProjectSplit::getEdges(), and TechDraw::DrawViewPart::getVisibleFaceEdges().
getVisIso()
TopoDS_Shape TechDraw::GeometryObject::getVisIso (void)
getVisOutline()
TopoDS_Shape TechDraw::GeometryObject::getVisOutline (void)
getVisSeam()
TopoDS_Shape TechDraw::GeometryObject::getVisSeam (void)
getVisSmooth()
TopoDS_Shape TechDraw::GeometryObject::getVisSmooth (void)
invertGeometry()
TopoDS_Shape GeometryObject::invertGeometry (const TopoDS_Shape s) static
Referenced by TechDraw::DrawGeomHatch::getTrimmedLinesSection(), projectFace(), projectShape(), projectShapeWithPolygonAlgo(), and TechDraw::DrawViewSection::sectionExec().
isParentDetail()
TechDraw::DrawViewDetail * GeometryObject::isParentDetail (void) protected
References m_parent.
isPerspective() [1/2]
void TechDraw::GeometryObject::isPerspective (bool b)
Referenced by TechDraw::DrawViewPart::buildGeometryObject().
isPerspective() [2/2]
bool TechDraw::GeometryObject::isPerspective (void)
isWithinArc()
bool GeometryObject::isWithinArc (double theta, double first, double last, bool cw) const protected
Returns true iff angle theta is in [first, last], where the arc goes clockwise (cw=true) or counterclockwise (cw=false) from first to last.
projectFace()
TopoDS_Shape GeometryObject::projectFace (const TopoDS_Shape & face, const gp_Ax2 & CS)
References invertGeometry().
Referenced by ArchVRM.Renderer::reorient().
projectShape()
void GeometryObject::projectShape (const TopoDS_Shape & input, const gp_Ax2 & viewAxis)
set up a hidden line remover and project a shape with it
References clear(), Base::Console(), Base::ConsoleSingleton::Error(), hidHard, hidIso, hidOutline, hidSeam, hidSmooth, invertGeometry(), Base::ConsoleSingleton::Log(), m_focus, m_isoCount, m_isPersp, m_parentName, visHard, visIso, visOutline, visSeam, and visSmooth.
Referenced by TechDraw::DrawProjectSplit::buildGeometryObject(), and TechDraw::DrawViewPart::buildGeometryObject().
projectShapeWithPolygonAlgo()
void GeometryObject::projectShapeWithPolygonAlgo (const TopoDS_Shape & input, const gp_Ax2 & viewAxis)
set up a hidden line remover and project a shape with it
References clear(), Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::findCentroid(), hidHard, hidOutline, hidSeam, hidSmooth, invertGeometry(), Base::ConsoleSingleton::Log(), m_focus, m_isPersp, m_parentName, TechDraw::moveShape(), visHard, visOutline, visSeam, and visSmooth.
Referenced by TechDraw::DrawProjectSplit::buildGeometryObject(), and TechDraw::DrawViewPart::buildGeometryObject().
pruneVertexGeom()
void GeometryObject::pruneVertexGeom (Base::Vector3d center, double radius)
References getVertexGeometry(), and vertexGeom.
Referenced by TechDraw::DrawViewDetail::detailExec().
setEdgeGeometry()
void TechDraw::GeometryObject::setEdgeGeometry (BaseGeomPtrVector newGeoms)
Referenced by TechDraw::DrawViewPart::refreshCEGeoms(), and TechDraw::DrawViewPart::refreshCLGeoms().
setFocus()
void TechDraw::GeometryObject::setFocus (double f)
Referenced by TechDraw::DrawViewPart::buildGeometryObject(), DraftGui.DraftToolBar::displayPoint(), DraftGui.DraftToolBar::pointUi(), and DraftGui.DraftToolBar::setNextFocus().
setIsoCount()
void TechDraw::GeometryObject::setIsoCount (int i)
Referenced by TechDraw::DrawViewPart::buildGeometryObject().
setParentName()
void TechDraw::GeometryObject::setParentName (std::string n)
setVertexGeometry()
void TechDraw::GeometryObject::setVertexGeometry (std::vector< VertexPtr > newVerts)
Referenced by TechDraw::DrawViewPart::addReferencesToGeom(), TechDraw::DrawViewPart::refreshCVGeoms(), and TechDraw::DrawViewPart::removeAllReferencesFromGeom().
usePolygonHLR() [1/2]
void TechDraw::GeometryObject::usePolygonHLR (bool b)
Referenced by TechDraw::DrawProjectSplit::buildGeometryObject(), TechDraw::DrawViewPart::buildGeometryObject(), and TechDraw::DrawViewPart::partExec().
usePolygonHLR() [2/2]
bool TechDraw::GeometryObject::usePolygonHLR (void) const
Member Data Documentation
edgeGeom
BaseGeomPtrVector TechDraw::GeometryObject::edgeGeom protected
Referenced by addCenterLine(), addCosmeticEdge(), addEdge(), addGeomFromCompound(), calcBoundingBox(), clear(), and getVisibleFaceEdges().
faceGeom
std::vector<FacePtr> TechDraw::GeometryObject::faceGeom protected
Referenced by addFaceGeom(), clear(), and clearFaceGeom().
hidHard
TopoDS_Shape TechDraw::GeometryObject::hidHard protected
Referenced by extractGeometry(), projectShape(), and projectShapeWithPolygonAlgo().
hidIso
TopoDS_Shape TechDraw::GeometryObject::hidIso protected
Referenced by extractGeometry(), and projectShape().
hidOutline
TopoDS_Shape TechDraw::GeometryObject::hidOutline protected
Referenced by extractGeometry(), projectShape(), and projectShapeWithPolygonAlgo().
hidSeam
TopoDS_Shape TechDraw::GeometryObject::hidSeam protected
Referenced by extractGeometry(), projectShape(), and projectShapeWithPolygonAlgo().
hidSmooth
TopoDS_Shape TechDraw::GeometryObject::hidSmooth protected
Referenced by extractGeometry(), projectShape(), and projectShapeWithPolygonAlgo().
m_focus
double TechDraw::GeometryObject::m_focus protected
Referenced by projectShape(), and projectShapeWithPolygonAlgo().
m_isoCount
int TechDraw::GeometryObject::m_isoCount protected
Referenced by projectShape().
m_isPersp
bool TechDraw::GeometryObject::m_isPersp protected
Referenced by projectShape(), and projectShapeWithPolygonAlgo().
m_parent
TechDraw::DrawView* TechDraw::GeometryObject::m_parent protected
Referenced by addCosmeticEdge(), addCosmeticVertex(), and isParentDetail().
m_parentName
std::string TechDraw::GeometryObject::m_parentName protected
Referenced by projectShape(), and projectShapeWithPolygonAlgo().
m_usePolygonHLR
bool TechDraw::GeometryObject::m_usePolygonHLR protected
vertexGeom
std::vector<VertexPtr> TechDraw::GeometryObject::vertexGeom protected
Referenced by addCosmeticVertex(), addGeomFromCompound(), addVertex(), clear(), findVertex(), and pruneVertexGeom().
visHard
TopoDS_Shape TechDraw::GeometryObject::visHard protected
Referenced by extractGeometry(), projectShape(), and projectShapeWithPolygonAlgo().
visIso
TopoDS_Shape TechDraw::GeometryObject::visIso protected
Referenced by extractGeometry(), and projectShape().
visOutline
TopoDS_Shape TechDraw::GeometryObject::visOutline protected
Referenced by extractGeometry(), projectShape(), and projectShapeWithPolygonAlgo().
visSeam
TopoDS_Shape TechDraw::GeometryObject::visSeam protected
Referenced by extractGeometry(), projectShape(), and projectShapeWithPolygonAlgo().
visSmooth
TopoDS_Shape TechDraw::GeometryObject::visSmooth protected
Referenced by extractGeometry(), projectShape(), and projectShapeWithPolygonAlgo().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/App/GeometryObject.h
FreeCAD/src/Mod/TechDraw/App/GeometryObject.cpp