FreeCAD: MED::TCSlice< TValueType > Class Template Reference
MED::TCSlice< TValueType > Class Template Reference
This class intends to provide an uniform way to handle multy-dimension data (const version)
#include <MED_SliceArray.hxx>
Public Types
typedef TValueType value_type
Public Member Functions
const value_type & at (size_t theId) const
const value_type & operator[] (size_t theId) const
Get element by its number (const version)
size_t size () const
Get range of the order numbers.
TCSlice ()
Default constructor (dangerous)
TCSlice (const TVector< value_type > &theContainer, const std::slice &theSlice)
Construct the class from corresponding container.
TCSlice (const value_type *theValuePtr, size_t theSourceSize, const std::slice &theSlice)
Construct the class from bare pointer.
Protected Member Functions
size_t calculate_id (size_t theId) const
Calculate internal index to get proper element from the source multy-dimension data.
void check_id (size_t theId) const
size_t get_id (size_t theId) const
size_t get_id_at (size_t theId) const
Detailed Description
template<class TValueType>
class MED::TCSlice< TValueType >
This class intends to provide an uniform way to handle multy-dimension data (const version)
It just contains pointer to real sequence and implement proper calcultion of its indexes. This class deal with constant pointer to the sources data and provide const method to read the them (data).
Member Typedef Documentation
value_type
template<class TValueType > typedef TValueType MED::TCSlice< TValueType >::value_type
Constructor & Destructor Documentation
TCSlice() [1/3]
template<class TValueType > MED::TCSlice< TValueType >::TCSlice (const value_type * theValuePtr, size_t theSourceSize, const std::slice & theSlice)
Construct the class from bare pointer.
TCSlice() [2/3]
template<class TValueType > MED::TCSlice< TValueType >::TCSlice (const TVector< value_type > & theContainer, const std::slice & theSlice)
Construct the class from corresponding container.
TCSlice() [3/3]
template<class TValueType > MED::TCSlice< TValueType >::TCSlice ()
Default constructor (dangerous)
Member Function Documentation
at()
template<class TValueType > const value_type & MED::TCSlice< TValueType >::at (size_t theId) const
References MED::TCSlice< TValueType >::get_id_at().
calculate_id()
template<class TValueType > size_t MED::TCSlice< TValueType >::calculate_id (size_t theId) const protected
Calculate internal index to get proper element from the source multy-dimension data.
Referenced by MED::TCSlice< TValueType >::get_id(), and MED::TCSlice< TValueType >::get_id_at().
check_id()
template<class TValueType > void MED::TCSlice< TValueType >::check_id (size_t theId) const protected
Referenced by MED::TCSlice< TValueType >::get_id(), and MED::TCSlice< TValueType >::get_id_at().
get_id()
template<class TValueType > size_t MED::TCSlice< TValueType >::get_id (size_t theId) const protected
References MED::TCSlice< TValueType >::calculate_id(), and MED::TCSlice< TValueType >::check_id().
Referenced by MED::TSlice< TValueType >::operator[](), and MED::TCSlice< TValueType >::operator[]().
get_id_at()
template<class TValueType > size_t MED::TCSlice< TValueType >::get_id_at (size_t theId) const protected
References MED::TCSlice< TValueType >::calculate_id(), and MED::TCSlice< TValueType >::check_id().
Referenced by MED::TSlice< TValueType >::at(), and MED::TCSlice< TValueType >::at().
operator[]()
template<class TValueType > const value_type & MED::TCSlice< TValueType >::operator[] (size_t theId) const
Get element by its number (const version)
References MED::TCSlice< TValueType >::get_id().
size()
template<class TValueType > size_t MED::TCSlice< TValueType >::size () const
Get range of the order numbers.
Referenced by gzip_utf8.GzipFile::close(), PathScripts.PostUtils.GCodeEditorDialog::done(), MED::GetBaryCenter(), MED::TWrapper::GetPPolyedreInfo(), MED::TWrapper::GetPPolygoneInfo(), MED::TShapeFun::IsSatisfy(), DriverMED_R_SMESHDS_Mesh::Perform(), and gzip_utf8.GzipFile::write().
The documentation for this class was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/inc/MED_SliceArray.hxx