FreeCAD: App::Enumeration::Object Class Reference
App::Enumeration::Object Class Reference abstract
#include <Enumeration.h>
Public Member Functions
virtual const char * data () const =0
virtual bool isCustom () const =0
virtual bool isEqual (const char *) const =0
virtual ~Object ()
Constructor & Destructor Documentation
~Object()
virtual App::Enumeration::Object::~Object () virtual
Member Function Documentation
data()
virtual const char * App::Enumeration::Object::data () const pure virtual
Referenced by Mod.Show.mTempoVis.TempoVis::activateWorkbench(), Mod.Show.SceneDetail.SceneDetail::apply_data(), importIFClegacy.IfcSchema::capitalize(), Mod.Show.mTempoVis.TempoVis::forget(), Mod.Show.mTempoVis.TempoVis::forgetDetail(), Mod.Show.mTempoVis.TempoVis::has(), ArchSchedule.CommandArchSchedule::IsActive(), importIFClegacy.IfcSchema::readEntities(), importIFClegacy.IfcSchema::readTypes(), Mod.Show.mTempoVis.TempoVis::restore(), Mod.Show.mTempoVis.TempoVis::save(), Mod.Show.mTempoVis.TempoVis::stored_val(), FeaturePython.ViewProviderOctahedron::updateData(), and Dice3DS.dom3ds.UndefinedChunk::write().
isCustom()
virtual bool App::Enumeration::Object::isCustom () const pure virtual
isEqual()
virtual bool App::Enumeration::Object::isEqual (const char *) const pure virtual
The documentation for this class was generated from the following file:
FreeCAD/src/App/Enumeration.h