FreeCAD: TechDrawGui::Ui_TaskHatch Class Reference
TechDrawGui::Ui_TaskHatch Class Reference
#include <ui_TaskHatch.h>
Public Member Functions
void retranslateUi (QWidget *TechDrawGui__TaskHatch)
void setupUi (QWidget *TechDrawGui__TaskHatch)
Public Attributes
Gui::ColorButton * ccColor
Gui::FileChooser * fcFile
QGridLayout * gridLayout_2
QGridLayout * gridLayout_3
QGroupBox * groupBox
QLabel * label
QLabel * label_2
QLabel * label_3
Gui::QuantitySpinBox * sbScale
QVBoxLayout * verticalLayout
QVBoxLayout * verticalLayout_2
Member Function Documentation
retranslateUi()
void TechDrawGui::Ui_TaskHatch::retranslateUi (QWidget * TechDrawGui__TaskHatch)
References ccColor, fcFile, groupBox, label_2, label_3, sbScale, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void TechDrawGui::Ui_TaskHatch::setupUi (QWidget * TechDrawGui__TaskHatch)
References ccColor, fcFile, gridLayout_2, gridLayout_3, groupBox, label_2, label_3, retranslateUi(), sbScale, Gui::QuantitySpinBox::setMinimum(), Gui::QuantitySpinBox::setSingleStep(), Gui::QuantitySpinBox::setValue(), verticalLayout, and verticalLayout_2.
Member Data Documentation
ccColor
Gui::ColorButton* TechDrawGui::Ui_TaskHatch::ccColor
Referenced by retranslateUi(), and setupUi().
fcFile
Gui::FileChooser* TechDrawGui::Ui_TaskHatch::fcFile
Referenced by retranslateUi(), and setupUi().
gridLayout_2
QGridLayout* TechDrawGui::Ui_TaskHatch::gridLayout_2
Referenced by setupUi().
gridLayout_3
QGridLayout* TechDrawGui::Ui_TaskHatch::gridLayout_3
Referenced by setupUi().
groupBox
QGroupBox* TechDrawGui::Ui_TaskHatch::groupBox
Referenced by retranslateUi(), and setupUi().
label
QLabel* TechDrawGui::Ui_TaskHatch::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
label_2
QLabel* TechDrawGui::Ui_TaskHatch::label_2
Referenced by retranslateUi(), and setupUi().
label_3
QLabel* TechDrawGui::Ui_TaskHatch::label_3
Referenced by retranslateUi(), and setupUi().
sbScale
Gui::QuantitySpinBox* TechDrawGui::Ui_TaskHatch::sbScale
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* TechDrawGui::Ui_TaskHatch::verticalLayout
Referenced by setupUi().
verticalLayout_2
QVBoxLayout* TechDrawGui::Ui_TaskHatch::verticalLayout_2
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/TechDraw/Gui/ui_TaskHatch.h