FreeCAD: Gui::Dialog::DlgSettingsUnitsImp Class Reference
Gui::Dialog::DlgSettingsUnitsImp Class Reference
#include <DlgSettingsUnitsImp.h>
Public Slots
void on_comboBox_ViewSystem_currentIndexChanged (int index)
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Public Member Functions
DlgSettingsUnitsImp (QWidget *parent=nullptr)
Constructs a DlgSettingsUnitsImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
void loadSettings ()
void saveSettings ()
~DlgSettingsUnitsImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
virtual void changeEvent (QEvent *e)=0
Constructor & Destructor Documentation
DlgSettingsUnitsImp()
DlgSettingsUnitsImp::DlgSettingsUnitsImp (QWidget * parent = nullptr)
Constructs a DlgSettingsUnitsImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
References Gui::Dialog::Ui_DlgSettingsUnits::comboBox_FracInch, Gui::Dialog::Ui_DlgSettingsUnits::comboBox_ViewSystem, Base::UnitsApi::getDescription(), Base::NumUnitSystemTypes, Gui::Dialog::Ui_DlgSettingsUnits::setupUi(), Gui::Dialog::Ui_DlgSettingsUnits::spinBoxDecimals, and Gui::Dialog::Ui_DlgSettingsUnits::tableWidget.
~DlgSettingsUnitsImp()
DlgSettingsUnitsImp::~DlgSettingsUnitsImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void DlgSettingsUnitsImp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
References Gui::Dialog::Ui_DlgSettingsUnits::comboBox_ViewSystem, and Gui::Dialog::Ui_DlgSettingsUnits::retranslateUi().
loadSettings()
void DlgSettingsUnitsImp::loadSettings () virtual
Implements Gui::Dialog::PreferencePage.
References Gui::Dialog::Ui_DlgSettingsUnits::comboBox_FracInch, Gui::Dialog::Ui_DlgSettingsUnits::comboBox_ViewSystem, App::GetApplication(), Base::UnitsApi::getDecimals(), Base::QuantityFormat::getDefaultDenominator(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), and Gui::Dialog::Ui_DlgSettingsUnits::spinBoxDecimals.
on_comboBox_ViewSystem_currentIndexChanged
void DlgSettingsUnitsImp::on_comboBox_ViewSystem_currentIndexChanged (int index) slot
References Gui::Dialog::Ui_DlgSettingsUnits::comboBox_FracInch.
saveSettings()
void DlgSettingsUnitsImp::saveSettings () virtual
Implements Gui::Dialog::PreferencePage.
References Gui::Dialog::Ui_DlgSettingsUnits::comboBox_FracInch, Gui::Dialog::Ui_DlgSettingsUnits::comboBox_ViewSystem, App::GetApplication(), App::Application::GetParameterGroupByPath(), Base::UnitsApi::setDecimals(), Base::QuantityFormat::setDefaultDenominator(), ParameterGrp::SetInt(), and Gui::Dialog::Ui_DlgSettingsUnits::spinBoxDecimals.
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgSettingsUnitsImp.h
FreeCAD/src/Gui/DlgSettingsUnitsImp.cpp