FreeCAD: Spaceball::MotionEvent Class Reference
Spaceball::MotionEvent Class Reference
#include <SpaceballEvent.h>
Public Member Functions
MotionEvent ()
MotionEvent (const MotionEvent &in)
MotionEvent & operator= (const MotionEvent &in)
void rotations (int &xRotOut, int &yRotOut, int &zRotOut)
int rotationX ()
int rotationY ()
int rotationZ ()
void setRotations (const int &xRotIn, const int &yRotIn, const int &zRotIn)
void setTranslations (const int &xTransIn, const int &yTransIn, const int &zTransIn)
void translations (int &xTransOut, int &yTransOut, int &zTransOut)
int translationX ()
int translationY ()
int translationZ ()
Public Member Functions inherited from Spaceball::EventBase
bool isHandled ()
void setHandled (bool sig)
Static Public Attributes
static int MotionEventType = -1
Additional Inherited Members
Protected Member Functions inherited from Spaceball::EventBase
EventBase (QEvent::Type event)
Protected Attributes inherited from Spaceball::EventBase
bool handled
Constructor & Destructor Documentation
MotionEvent() [1/2]
MotionEvent::MotionEvent ()
MotionEvent() [2/2]
MotionEvent::MotionEvent (const MotionEvent & in)
References Spaceball::EventBase::handled.
Member Function Documentation
operator=()
MotionEvent & MotionEvent::operator= (const MotionEvent & in)
References Spaceball::EventBase::handled.
rotations()
void MotionEvent::rotations (int & xRotOut, int & yRotOut, int & zRotOut)
rotationX()
int Spaceball::MotionEvent::rotationX ()
Referenced by SpaceNavigatorDevice::translateEvent().
rotationY()
int Spaceball::MotionEvent::rotationY ()
Referenced by SpaceNavigatorDevice::translateEvent().
rotationZ()
int Spaceball::MotionEvent::rotationZ ()
Referenced by SpaceNavigatorDevice::translateEvent().
setRotations()
void MotionEvent::setRotations (const int & xRotIn, const int & yRotIn, const int & zRotIn)
Referenced by Gui::GUIApplicationNativeEventAware::postMotionEvent().
setTranslations()
void MotionEvent::setTranslations (const int & xTransIn, const int & yTransIn, const int & zTransIn)
Referenced by Gui::GUIApplicationNativeEventAware::postMotionEvent().
translations()
void MotionEvent::translations (int & xTransOut, int & yTransOut, int & zTransOut)
translationX()
int Spaceball::MotionEvent::translationX ()
Referenced by SpaceNavigatorDevice::translateEvent().
translationY()
int Spaceball::MotionEvent::translationY ()
Referenced by SpaceNavigatorDevice::translateEvent().
translationZ()
int Spaceball::MotionEvent::translationZ ()
Referenced by SpaceNavigatorDevice::translateEvent().
Member Data Documentation
MotionEventType
int MotionEvent::MotionEventType = -1 static
Referenced by Gui::MainWindow::event(), Gui::ViewerEventFilter::eventFilter(), Gui::GUIApplicationNativeEventAware::initSpaceball(), Gui::GUIApplication::notify(), Gui::GUIApplicationNativeEventAware::processSpaceballEvent(), and SpaceNavigatorDevice::translateEvent().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SpaceballEvent.h
Sources/FreeCAD/src/Gui/SpaceballEvent.cpp