FreeCAD: GCS::ConstraintEllipseTangentLine Class Reference
GCS::ConstraintEllipseTangentLine Class Reference
#include <Constraints.h>
Public Member Functions
ConstraintEllipseTangentLine (Line &l, Ellipse &e)
virtual double error ()
virtual ConstraintType getTypeId ()
virtual double grad (double *)
virtual void rescale (double coef=1.)
Public Member Functions inherited from GCS::Constraint
Constraint ()
int findParamInPvec (double *param)
int getTag ()
bool isDriving () const
virtual double maxStep (MAP_pD_D &dir, double lim=1.)
VEC_pD params ()
void redirectParams (MAP_pD_pD redirectionmap)
void revertParams ()
void setDriving (bool isdriving)
void setTag (int tagId)
virtual ~Constraint ()
Constructor & Destructor Documentation
ConstraintEllipseTangentLine()
GCS::ConstraintEllipseTangentLine::ConstraintEllipseTangentLine (Line & l, Ellipse & e)
References GCS::Line::PushOwnParams(), GCS::Ellipse::PushOwnParams(), and rescale().
Member Function Documentation
error()
double GCS::ConstraintEllipseTangentLine::error () virtual
Reimplemented from GCS::Constraint.
Referenced by grad().
getTypeId()
ConstraintType GCS::ConstraintEllipseTangentLine::getTypeId (void) virtual
Reimplemented from GCS::Constraint.
References GCS::TangentEllipseLine.
grad()
double GCS::ConstraintEllipseTangentLine::grad (double * param) virtual
Reimplemented from GCS::Constraint.
References error(), GCS::Constraint::findParamInPvec(), and draftguitools.gui_annotationstyleeditor::param.
rescale()
void GCS::ConstraintEllipseTangentLine::rescale (double coef = 1.) virtual
Reimplemented from GCS::Constraint.
Referenced by ConstraintEllipseTangentLine().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Constraints.h
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Constraints.cpp