FreeCAD: Mod.PartDesign.Scripts.Gear Namespace Reference
Mod.PartDesign.Scripts.Gear Namespace Reference
Functions
def compute ()
def hide ()
def proceed ()
Variables
App = FreeCAD
c1 = QtGui.QCheckBox("Create as a Mesh")
commentFont = QtGui.QFont("Times",8,True)
dialog = QtGui.QDialog()
e1 = QtGui.QLabel("(for faster rendering)")
Gui = FreeCADGui
l1 = QtGui.QLineEdit()
l2 = QtGui.QLineEdit()
l3 = QtGui.QLineEdit()
l4 = QtGui.QLineEdit()
l5 = QtGui.QLineEdit()
l6 = QtGui.QLineEdit()
l7 = QtGui.QLineEdit()
la = QtGui.QVBoxLayout(dialog)
okbox = QtGui.QDialogButtonBox(dialog)
t1 = QtGui.QLabel("Number of teeth (N)")
t2 = QtGui.QLabel("Circular pitch (p)")
t3 = QtGui.QLabel("Pressure angle (alfa)")
t4 = QtGui.QLabel("Tooth height factor (y)")
t5 = QtGui.QLabel("Tooth clearance (c)")
t6 = QtGui.QLabel("Tooth lateral clearance (j)")
t7 = QtGui.QLabel("Gear width")
Function Documentation
compute()
def Mod.PartDesign.Scripts.Gear.compute ()
References Mod.PartDesign.Scripts.Gear.hide().
Referenced by Mod.PartDesign.Scripts.Gear.proceed().
hide()
def Mod.PartDesign.Scripts.Gear.hide ()
Referenced by Mod.PartDesign.Scripts.Gear.compute(), and Mod.PartDesign.Scripts.Gear.proceed().
proceed()
def Mod.PartDesign.Scripts.Gear.proceed ()
References Mod.PartDesign.Scripts.Gear.compute(), and Mod.PartDesign.Scripts.Gear.hide().
Variable Documentation
App
Mod.PartDesign.Scripts.Gear.App = FreeCAD
c1
Mod.PartDesign.Scripts.Gear.c1 = QtGui.QCheckBox("Create as a Mesh")
commentFont
Mod.PartDesign.Scripts.Gear.commentFont = QtGui.QFont("Times",8,True)
dialog
Mod.PartDesign.Scripts.Gear.dialog = QtGui.QDialog()
e1
Mod.PartDesign.Scripts.Gear.e1 = QtGui.QLabel("(for faster rendering)")
Gui
Mod.PartDesign.Scripts.Gear.Gui = FreeCADGui
l1
Mod.PartDesign.Scripts.Gear.l1 = QtGui.QLineEdit()
l2
Mod.PartDesign.Scripts.Gear.l2 = QtGui.QLineEdit()
l3
Mod.PartDesign.Scripts.Gear.l3 = QtGui.QLineEdit()
l4
Mod.PartDesign.Scripts.Gear.l4 = QtGui.QLineEdit()
l5
Mod.PartDesign.Scripts.Gear.l5 = QtGui.QLineEdit()
l6
Mod.PartDesign.Scripts.Gear.l6 = QtGui.QLineEdit()
l7
Mod.PartDesign.Scripts.Gear.l7 = QtGui.QLineEdit()
la
Mod.PartDesign.Scripts.Gear.la = QtGui.QVBoxLayout(dialog)
okbox
Mod.PartDesign.Scripts.Gear.okbox = QtGui.QDialogButtonBox(dialog)
t1
Mod.PartDesign.Scripts.Gear.t1 = QtGui.QLabel("Number of teeth (N)")
t2
Mod.PartDesign.Scripts.Gear.t2 = QtGui.QLabel("Circular pitch (p)")
t3
Mod.PartDesign.Scripts.Gear.t3 = QtGui.QLabel("Pressure angle (alfa)")
t4
Mod.PartDesign.Scripts.Gear.t4 = QtGui.QLabel("Tooth height factor (y)")
t5
Mod.PartDesign.Scripts.Gear.t5 = QtGui.QLabel("Tooth clearance (c)")
t6
Mod.PartDesign.Scripts.Gear.t6 = QtGui.QLabel("Tooth lateral clearance (j)")
t7
Mod.PartDesign.Scripts.Gear.t7 = QtGui.QLabel("Gear width")