FreeCAD: PathGui::DlgProcessorChooser Class Reference
PathGui::DlgProcessorChooser Class Reference
#include <DlgProcessorChooser.h>
Public Member Functions
void accept ()
DlgProcessorChooser (std::vector< std::string > &scriptnames, bool withArguments=false)
std::string getArguments ()
std::string getProcessor ()
~DlgProcessorChooser ()
Constructor & Destructor Documentation
DlgProcessorChooser()
DlgProcessorChooser::DlgProcessorChooser (std::vector< std::string > & scriptnames, bool withArguments = false)
References Ui_DlgProcessorChooser::argsLabel, Ui_DlgProcessorChooser::argsLineEdit, Ui_DlgProcessorChooser::comboBox, and Ui_DlgProcessorChooser::setupUi().
~DlgProcessorChooser()
DlgProcessorChooser::~DlgProcessorChooser ()
Member Function Documentation
accept()
void DlgProcessorChooser::accept (void)
References Ui_DlgProcessorChooser::argsLineEdit, and Ui_DlgProcessorChooser::comboBox.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
getArguments()
std::string DlgProcessorChooser::getArguments ()
getProcessor()
std::string DlgProcessorChooser::getProcessor ()
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Path/Gui/DlgProcessorChooser.h
FreeCAD/src/Mod/Path/Gui/DlgProcessorChooser.cpp