FreeCAD: InspectionGui::ViewProviderInspection Class Reference
InspectionGui::ViewProviderInspection Class Reference
#include <ViewProviderInspection.h>
Public Member Functions
void attach (App::DocumentObject *pcFeat)
std::vector< std::string > getDisplayModes (void) const
Returns a list of all possible modes.
SoSeparator * getFrontRoot (void) const
Returns a color bar.
QIcon getIcon () const
deliver the icon shown in the tree view
virtual void hide (void)
Hide the object in the view.
void OnChange (Base::Subject< int > &rCaller, int rcReason)
Once the color bar settings has been changed this method gets called to update the feature's representation.
void setDisplayMode (const char *ModeName)
Sets the viewing mode.
virtual void show (void)
Show the object in the view.
void updateData (const App::Property *)
Update colorbar after recomputation of distances.
ViewProviderInspection ()
virtual ~ViewProviderInspection ()
Public Member Functions inherited from Gui::ViewProviderDocumentObject
virtual void attach (App::DocumentObject *pcObject)
virtual bool canDelete (App::DocumentObject *obj) const override
Asks the view provider if the given object can be deleted.
virtual bool canDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const override
Query object dropping with full qualified name.
virtual void forceUpdate (bool enable=true)
virtual bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const override
return the coin node detail and path to the node of the subname
Gui::Document * getDocument () const
Get the GUI document to this ViewProvider object.
virtual bool getElementPicked (const SoPickedPoint *, std::string &subname) const override
return a hit element given the picked point which contains the full node path
App::DocumentObject * getObject (void) const
Get the object of this ViewProvider object.
PyObject * getPyObject () override
Get the python wrapper for that ViewProvider.
virtual void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const override
Get a list of TaskBoxes associated with this object.
virtual const char * getTransactionText () const override
Is called by the tree if the user double clicks on the object.
virtual void hide (void) override
Hide the object in the view.
virtual bool isUpdateForced () const
virtual void reattach (App::DocumentObject *)
virtual int replaceObject (App::DocumentObject *, App::DocumentObject *) override
Replace an object to the view provider by drag and drop.
void setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
virtual void show (void) override
Show the object in the view.
virtual bool showInTree () const override
Tell the tree view if this object should appear there.
virtual void update (const App::Property *) override
update the content of the ViewProvider this method have to implement the recalculation of the ViewProvider.
void updateView ()
Run a redraw.
ViewProviderDocumentObject ()
constructor.
virtual ~ViewProviderDocumentObject ()
destructor.
virtual void startRestoring ()
virtual void finishRestoring ()
virtual bool removeDynamicProperty (const char *prop) override
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
virtual ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=nullptr, bool recursive=false) const
Return the linked view object.
virtual std::string getFullName () const override
virtual bool allowOverride (const App::DocumentObject &) const
Allow this class to be used as an override for the original view provider of the given object.
void setShowable (bool enable)
bool isShowable () const
void startDefaultEditMode ()
Start the edit mode with ViewProvider::Default.
Public Member Functions inherited from Gui::ViewProvider
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual std::vector< App::DocumentObject * > claimChildren3D (void) const
deliver the children belonging to this object this method is used to deliver the objects to the 3DView which should be grouped under its scene graph.
SoSeparator * getAnnotation (void)
virtual SoSeparator * getBackRoot (void) const
virtual SoGroup * getChildRoot (void) const
virtual SoSeparator * getFrontRoot (void) const
SoSwitch * getModeSwitch (void) const
virtual SoSeparator * getRoot (void) const
SoTransform * getTransformNode () const
ViewProvider ()
constructor.
virtual ~ViewProvider ()
destructor.
virtual bool useNewSelectionModel (void) const
indicates if the ViewProvider use the new Selection model
virtual bool isSelectable (void) const
virtual std::string getElement (const SoDetail *) const
return a hit element to the selection path or 0
virtual SoDetail * getDetail (const char *) const
return the coin node detail of the subelement
int partialRender (const std::vector< std::string > &subelements, bool clear)
partial rendering setup
virtual std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const
virtual std::vector< Base::Vector3d > getSelectionShape (const char *Element) const
return the highlight lines for a given element or the whole shape
Base::BoundBox3d getBoundingBox (const char *subname=nullptr, bool transform=true, MDIView *view=nullptr) const
Return the bound box of this view object.
virtual bool onDelete (const std::vector< std::string > &subNames)
Get called if the object is about to get deleted.
virtual void beforeDelete ()
Called before deletion.
virtual bool canDragObjects () const
Check whether children can be removed from the view provider by drag and drop.
virtual bool canDragObject (App::DocumentObject *) const
Check whether the object can be removed from the view provider by drag and drop.
virtual void dragObject (App::DocumentObject *)
Remove a child from the view provider by drag and drop.
virtual bool canDropObjects () const
Check whether objects can be added to the view provider by drag and drop or drop only.
virtual bool canDropObject (App::DocumentObject *) const
Check whether the object can be dropped to the view provider by drag and drop or drop only.
virtual bool canDragAndDropObject (App::DocumentObject *) const
Return false to force drop only operation for a given object.
virtual void dropObject (App::DocumentObject *)
Add an object to the view provider by drag and drop.
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
Add an object with full qualified name to the view provider by drag and drop.
virtual bool canRemoveChildrenFromRoot () const
Tell the tree view to remove children items from the tree root.
std::string getActiveDisplayMode (void) const
virtual const char * getDefaultDisplayMode () const
get the default display mode
virtual bool isShow (void) const
checks whether the view provider is visible or not
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
virtual void setOverrideMode (const std::string &mode)
Overrides the display mode with mode.
const std::string getOverrideMode ()
virtual bool keyPressed (bool pressed, int key)
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
virtual bool doubleClicked (void)
is called by the tree if the user double clicks on the object
virtual bool mouseMove (const SbVec2s &cursorPos, View3DInventorViewer *viewer)
is called when the provider is in edit and the mouse is moved
virtual bool mouseButtonPressed (int button, bool pressed, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
is called when the Provider is in edit and the mouse is clicked
virtual bool mouseWheelEvent (int delta, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
virtual void setupContextMenu (QMenu *, QObject *, const char *)
set up the context-menu with the supported edit modes
virtual ViewProvider * startEditing (int ModNum=0)
bool isEditing () const
void finishEditing ()
virtual void setEditViewer (View3DInventorViewer *, int ModNum)
adjust viewer settings when editing a view provider
virtual void unsetEditViewer (View3DInventorViewer *)
restores viewer settings when leaving editing mode
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
virtual QIcon mergeColorfulOverlayIcons (const QIcon &orig) const
virtual std::vector< App::DocumentObject * > claimChildren (void) const
deliver the children belonging to this object this method is used to deliver the objects to the tree framework which should be grouped under its label.
virtual std::map< std::string, App::Color > getElementColors (const char *element=nullptr) const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
virtual MDIView * getMDIView () const
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
virtual const char * detachFromDocument ()
virtual bool isAttachedToDocument () const
TransactionalObject (void)
Constructor.
virtual ~TransactionalObject ()
Public Member Functions inherited from App::ExtensionContainer
ExtensionIterator extensionBegin ()
ExtensionContainer ()
ExtensionIterator extensionEnd ()
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
void registerExtension (Base::Type extension, App::Extension *ext)
virtual ~ExtensionContainer ()
virtual Property * getPropertyByName (const char *name) const override
find a property by its name
virtual const char * getPropertyName (const Property *prop) const override
get the name of a property
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
virtual void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
virtual short getPropertyType (const Property *prop) const override
get the Type of a Property
virtual short getPropertyType (const char *name) const override
get the Type of a named Property
virtual const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
Public Member Functions inherited from App::PropertyContainer
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false)
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual void editProperty (const char *)
virtual App::Property * getDynamicPropertyByName (const char *name) const
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual std::string getFullName () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Property * getPropertyByName (const char *name) const
find a property by its name
virtual const char * getPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * getPropertyGroup (const Property *prop) const
get the Group of a Property
virtual void getPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual const char * getPropertyName (const Property *prop) const
get the name of a property
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
const char * getPropertyPrefix () const
virtual short getPropertyType (const char *name) const
get the Type of a named Property
virtual short getPropertyType (const Property *prop) const
get the Type of a Property
bool isHidden (const char *name) const
check if the named property is hidden
bool isHidden (const Property *prop) const
check if the property is hidden
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isReadOnly (const Property *prop) const
check if the property is read-only
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus)
PropertyContainer ()
A constructor.
virtual bool removeDynamicProperty (const char *name)
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
void setPropertyPrefix (const char *prefix)
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
virtual ~PropertyContainer ()
A destructor.
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Base::Observer< int >
virtual const char * Name ()
This method can be reimplemented from the concrete Observer and returns the name of the observer.
Observer ()
A constructor.
virtual void OnChange (Subject< int > &rCaller, int rcReason)=0
This method need to be reimplemented from the concrete Observer and get called by the observed class.
virtual void OnDestroy (Subject< int > &rCaller)
This method need to be reimplemented from the concrete Observer and get called by the observed class.
virtual ~Observer ()
A destructor.
Static Public Member Functions
static void inspectCallback (void *ud, SoEventCallback *n)
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Public Attributes
App::PropertyBool OutsideGrayed
App::PropertyFloatConstraint PointSize
Public Attributes inherited from Gui::ViewProviderDocumentObject
App::PropertyEnumeration DisplayMode
App::PropertyEnumeration OnTopWhenSelected
App::PropertyEnumeration SelectionStyle
App::PropertyBool ShowInTree
App::PropertyBool Visibility
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
Protected Member Functions
QString inspectDistance (const SoPickedPoint *pp) const
void onChanged (const App::Property *prop)
Gets called by the container whenever a property has been changed.
void setDistances ()
Protected Member Functions inherited from Gui::ViewProviderDocumentObject
virtual bool isAttachedToDocument () const override
virtual const char * detachFromDocument () override
virtual void onPropertyStatusChanged (const App::Property &prop, unsigned long oldStatus) override
get called when a property status has changed
virtual void setModeSwitch () override
Turn on mode switch.
void addDefaultAction (QMenu *, const QString &)
Adds a menu item and bind it with startDefaultEditMode().
Gui::MDIView * getActiveView () const
Gui::MDIView * getEditingView () const
Gui::MDIView * getInventorView () const
Gui::MDIView * getViewOfNode (SoNode *node) const
virtual void onBeforeChange (const App::Property *prop) override
get called before the value is changed
SoNode * findFrontRootOfType (const SoType &type) const
Searches in all view providers that are attached to an object that is part of the same document as the object this view provider is attached to for an front root of type.
Protected Member Functions inherited from Gui::ViewProvider
virtual bool setEdit (int ModNum)
is called by the document when the provider goes in edit mode
virtual void unsetEdit (int ModNum)
is called when you lose the edit mode
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
virtual QIcon mergeGreyableOverlayIcons (const QIcon &orig) const
bool checkRecursion (SoNode *)
Helper method to check that the node is valid, i.e.
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
Helper method to get picked entities while editing.
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
Helper method to get picked entities while editing.
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData (void) const
virtual void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container.
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
virtual void onBeforeChange (const Property *)
get called before the value is changed
virtual void onChanged (const Property *)
get called by the container when a property has changed
Protected Attributes
Gui::SoFCColorBar * pcColorBar
SoMaterial * pcColorMat
SoSeparator * pcColorRoot
SoDrawStyle * pcColorStyle
SoCoordinate3 * pcCoords
SoGroup * pcLinkRoot
SoMaterialBinding * pcMatBinding
SoDrawStyle * pcPointStyle
Protected Attributes inherited from Gui::ViewProviderDocumentObject
App::DocumentObject * pcObject
Gui::Document * pcDocument
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation
The root separator for annotations.
ViewProviderPy * pyViewObject
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Additional Inherited Members
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0 , Transform , Cutting , Color }
Public Types inherited from App::ExtensionContainer
typedef std::map< Base::Type, App::Extension * >::iterator ExtensionIterator
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Author
Werner Mayer
Constructor & Destructor Documentation
ViewProviderInspection()
ViewProviderInspection::ViewProviderInspection ()
References Base::Subject< _MessageType >::Attach(), App::Prop_Hidden, App::Prop_None, and App::Prop_Output.
~ViewProviderInspection()
ViewProviderInspection::~ViewProviderInspection () virtual
References Base::Subject< _MessageType >::Detach(), pcColorBar, pcColorMat, pcColorRoot, pcCoords, pcLinkRoot, pcMatBinding, and pcPointStyle.
Member Function Documentation
attach()
void ViewProviderInspection::attach (App::DocumentObject * pcFeat) virtual
Reimplemented from Gui::ViewProviderDocumentObject.
References Gui::ViewProvider::addDisplayMaskMode(), Base::Subject< _MessageType >::Attach(), Base::Subject< _MessageType >::Detach(), Gui::ViewProviderDocumentObject::findFrontRootOfType(), Gui::SoFCColorBar::getMaxValue(), Gui::SoFCColorBar::getMinValue(), Base::Subject< _MessageType >::Notify(), pcColorBar, pcColorMat, pcColorRoot, pcLinkRoot, pcMatBinding, and Gui::SoFCColorBar::setRange().
getDisplayModes()
std::vector< std::string > ViewProviderInspection::getDisplayModes (void) const virtual
Returns a list of all possible modes.
Reimplemented from Gui::ViewProvider.
getFrontRoot()
SoSeparator * ViewProviderInspection::getFrontRoot (void) const virtual
Returns a color bar.
Reimplemented from Gui::ViewProvider.
References pcColorRoot.
getIcon()
QIcon ViewProviderInspection::getIcon (void) const virtual
deliver the icon shown in the tree view
Reimplemented from Gui::ViewProvider.
References Base::Persistence::getClassTypeId(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), App::ExtensionContainer::getPropertyByName(), Base::Persistence::getTypeId(), Gui::Application::Instance, Base::Type::isDerivedFrom(), and Gui::ViewProviderDocumentObject::pcObject.
Referenced by ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), and ArchSectionPlane.SectionPlaneTaskPanel::update().
hide()
void ViewProviderInspection::hide (void) virtual
Hide the object in the view.
Reimplemented from Gui::ViewProviderDocumentObject.
References pcColorStyle.
Referenced by ArchComponent.ArchSelectionObserver::addSelection(), Mod.Show.mTempoVis.TempoVis::hide_all_dependencies(), Mod.Show.mTempoVis.TempoVis::hide_all_dependent(), PathScripts.PathToolEdit.ToolEditorImage::setupUI(), and PathScripts.PathToolEdit.ToolEditorImage::updateTool().
inspectCallback()
void ViewProviderInspection::inspectCallback (void * ud, SoEventCallback * n) static
References InspectionGui::ViewProviderProxyObject::addFlag(), Base::Console(), Base::Persistence::getClassTypeId(), Gui::getMainWindow(), Base::Persistence::getTypeId(), inspectCallback(), inspectDistance(), Base::Type::isDerivedFrom(), Base::ConsoleSingleton::Message(), Gui::MainWindow::setPaneText(), and Gui::ToolTip::showText().
Referenced by inspectCallback().
inspectDistance()
QString ViewProviderInspection::inspectDistance (const SoPickedPoint * pp) const protected
References InspectionGui::calcWeights(), DraftVecUtils::dist(), Base::Persistence::getClassTypeId(), App::ExtensionContainer::getPropertyByName(), Base::Persistence::getTypeId(), Base::Type::isDerivedFrom(), and Gui::ViewProviderDocumentObject::pcObject.
Referenced by inspectCallback().
OnChange()
void ViewProviderInspection::OnChange (Base::Subject< int > & rCaller, int rcReason) virtual
Once the color bar settings has been changed this method gets called to update the feature's representation.
Implements Base::Observer< int >.
References Gui::ViewProviderDocumentObject::setActiveMode().
onChanged()
void ViewProviderInspection::onChanged (const App::Property * prop) protected virtual
Gets called by the container whenever a property has been changed.
Reimplemented from Gui::ViewProviderDocumentObject.
References App::PropertyFloat::getValue(), App::PropertyBool::getValue(), Base::Subject< _MessageType >::Notify(), OutsideGrayed, pcColorBar, pcPointStyle, PointSize, and Gui::SoFCColorBar::setOutsideGrayed().
Referenced by ArchStructure.CommandStructuralSystem::Activated(), draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSite.Compass::buildCoordinates(), draftobjects.wire.Wire::execute(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchPanel.ViewProviderPanelSheet::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), and draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData().
setDisplayMode()
void ViewProviderInspection::setDisplayMode (const char * ModeName) virtual
Sets the viewing mode.
Reimplemented from Gui::ViewProvider.
References Gui::ViewProvider::setDisplayMaskMode(), and setDistances().
setDistances()
void ViewProviderInspection::setDistances () protected
References App::Color::b, App::Color::g, Base::Persistence::getClassTypeId(), Gui::SoFCColorBar::getColor(), Base::Type::getName(), App::ExtensionContainer::getPropertyByName(), Base::Persistence::getTypeId(), Gui::SoFCColorBar::isVisible(), pcColorBar, pcColorMat, pcCoords, pcMatBinding, Gui::ViewProviderDocumentObject::pcObject, and App::Color::r.
Referenced by setDisplayMode(), and updateData().
show()
void ViewProviderInspection::show (void) virtual
Show the object in the view.
Reimplemented from Gui::ViewProviderDocumentObject.
References pcColorStyle.
Referenced by Mod.Show.mTempoVis.TempoVis::show_all_dependencies(), and Mod.Show.mTempoVis.TempoVis::show_all_dependent().
updateData()
void ViewProviderInspection::updateData (const App::Property * prop) virtual
Update colorbar after recomputation of distances.
Reimplemented from Gui::ViewProvider.
References Gui::coinRemoveAllChildren(), Base::Type::fromName(), App::GetApplication(), Base::Persistence::getClassTypeId(), ParameterGrp::GetFloat(), App::Property::getName(), App::Application::GetParameterGroupByPath(), App::ExtensionContainer::getPropertyByName(), Base::Persistence::getTypeId(), Base::Type::isDerivedFrom(), Base::BoundBox3< _Precision >::LengthX(), Base::BoundBox3< _Precision >::LengthY(), Base::BoundBox3< _Precision >::LengthZ(), Base::Subject< _MessageType >::Notify(), pcColorBar, pcCoords, pcLinkRoot, Gui::ViewProviderDocumentObject::pcObject, pcPointStyle, setDistances(), Gui::SoFCColorBar::setRange(), and updateData().
Referenced by ArchStructure.CommandStructuralSystem::Activated(), PathScripts.PathJobDlg.JobCreate::exec_(), draftviewproviders.view_dimension.ViewProviderLinearDimension::onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension::onChanged(), draftviewproviders.view_wire.ViewProviderWire::onChanged(), PathScripts.PathOpGui.TaskPanelPage::pageUpdateData(), PathScripts.PathPropertyBagGui.TaskPanel::setupUi(), PathScripts.PathSetupSheetGui.OpTaskPanel::setupUi(), and updateData().
Member Data Documentation
OutsideGrayed
App::PropertyBool InspectionGui::ViewProviderInspection::OutsideGrayed
Referenced by onChanged().
pcColorBar
Gui::SoFCColorBar* InspectionGui::ViewProviderInspection::pcColorBar protected
Referenced by attach(), onChanged(), setDistances(), updateData(), and ~ViewProviderInspection().
pcColorMat
SoMaterial* InspectionGui::ViewProviderInspection::pcColorMat protected
Referenced by attach(), setDistances(), and ~ViewProviderInspection().
pcColorRoot
SoSeparator* InspectionGui::ViewProviderInspection::pcColorRoot protected
Referenced by attach(), getFrontRoot(), and ~ViewProviderInspection().
pcColorStyle
SoDrawStyle* InspectionGui::ViewProviderInspection::pcColorStyle protected
Referenced by hide(), and show().
pcCoords
SoCoordinate3* InspectionGui::ViewProviderInspection::pcCoords protected
Referenced by setDistances(), updateData(), and ~ViewProviderInspection().
pcLinkRoot
SoGroup* InspectionGui::ViewProviderInspection::pcLinkRoot protected
Referenced by attach(), updateData(), and ~ViewProviderInspection().
pcMatBinding
SoMaterialBinding* InspectionGui::ViewProviderInspection::pcMatBinding protected
Referenced by attach(), setDistances(), and ~ViewProviderInspection().
pcPointStyle
SoDrawStyle* InspectionGui::ViewProviderInspection::pcPointStyle protected
Referenced by onChanged(), updateData(), and ~ViewProviderInspection().
PointSize
App::PropertyFloatConstraint InspectionGui::ViewProviderInspection::PointSize
Referenced by onChanged().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Inspection/Gui/ViewProviderInspection.h
FreeCAD/src/Mod/Inspection/Gui/ViewProviderInspection.cpp