FreeCAD: FemGui::TaskDlgMeshShapeNetgen Class Reference
FemGui::TaskDlgMeshShapeNetgen Class Reference
simulation dialog for the TaskView
#include <TaskDlgMeshShapeNetgen.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void clicked (int)
is called by the framework if an button is clicked which has no accept or rject role
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
returns for Close and Help button
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual void open ()
is called the TaskView when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgMeshShapeNetgen (FemGui::ViewProviderFemMeshShapeNetgen *)
~TaskDlgMeshShapeNetgen ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
ButtonPosition buttonPosition () const
bool canClose () const
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Protected Attributes
Fem::FemMeshShapeNetgenObject * FemMeshShapeNetgenObject
TaskTetParameter * param
FemGui::ViewProviderFemMeshShapeNetgen * ViewProviderFemMeshShapeNetgen
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
simulation dialog for the TaskView
Constructor & Destructor Documentation
TaskDlgMeshShapeNetgen()
TaskDlgMeshShapeNetgen::TaskDlgMeshShapeNetgen (FemGui::ViewProviderFemMeshShapeNetgen * obj)
References Gui::TaskView::TaskDialog::Content, FemMeshShapeNetgenObject, and param.
~TaskDlgMeshShapeNetgen()
TaskDlgMeshShapeNetgen::~TaskDlgMeshShapeNetgen ()
Member Function Documentation
accept()
bool TaskDlgMeshShapeNetgen::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Command::commitCommand(), Base::Console(), FemMeshShapeNetgenObject, Gui::getMainWindow(), App::DocumentObject::getStatusString(), App::PropertyLink::getValue(), Gui::Command::Gui, Gui::Application::hideViewProvider(), Gui::Application::Instance, param, App::DocumentObject::recomputeFeature(), Gui::WaitCursor::restoreCursor(), Fem::FemMeshShapeObject::Shape, FemGui::TaskTetParameter::touched, and Base::ConsoleSingleton::Warning().
Referenced by PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
clicked()
void TaskDlgMeshShapeNetgen::clicked (int button) virtual
is called by the framework if an button is clicked which has no accept or rject role
Reimplemented from Gui::TaskView::TaskDialog.
References Base::Console(), Fem::FemMeshShapeNetgenObject::execute(), FemMeshShapeNetgenObject, param, FemGui::TaskTetParameter::setInfo(), FemGui::TaskTetParameter::touched, and Base::ConsoleSingleton::Warning().
getStandardButtons()
virtual QDialogButtonBox::StandardButtons FemGui::TaskDlgMeshShapeNetgen::getStandardButtons (void) const virtual
returns for Close and Help button
Reimplemented from Gui::TaskView::TaskDialog.
helpRequested()
void TaskDlgMeshShapeNetgen::helpRequested () virtual
is called by the framework if the user press the help button
Reimplemented from Gui::TaskView::TaskDialog.
open()
void TaskDlgMeshShapeNetgen::open () virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Command::hasPendingCommand(), and Gui::Command::openCommand().
reject()
bool TaskDlgMeshShapeNetgen::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Command::abortCommand(), and Gui::Command::Gui.
Referenced by PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
Member Data Documentation
FemMeshShapeNetgenObject
Fem::FemMeshShapeNetgenObject* FemGui::TaskDlgMeshShapeNetgen::FemMeshShapeNetgenObject protected
Referenced by accept(), clicked(), and TaskDlgMeshShapeNetgen().
param
TaskTetParameter* FemGui::TaskDlgMeshShapeNetgen::param protected
Referenced by accept(), clicked(), and TaskDlgMeshShapeNetgen().
ViewProviderFemMeshShapeNetgen
FemGui::ViewProviderFemMeshShapeNetgen* FemGui::TaskDlgMeshShapeNetgen::ViewProviderFemMeshShapeNetgen protected
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Fem/Gui/TaskDlgMeshShapeNetgen.h
Sources/FreeCAD/src/Mod/Fem/Gui/TaskDlgMeshShapeNetgen.cpp