FreeCAD: Gui::Dialog::DownloadModel Class Reference
Gui::Dialog::DownloadModel Class Reference
#include <DownloadManager.h>
Public Member Functions
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
DownloadModel (DownloadManager *downloadManager, QObject *parent=nullptr)
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
int rowCount (const QModelIndex &parent=QModelIndex()) const
Friends
class DownloadManager
Constructor & Destructor Documentation
DownloadModel()
DownloadModel::DownloadModel (DownloadManager * downloadManager, QObject * parent = nullptr)
Member Function Documentation
data()
QVariant DownloadModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
References rowCount().
Referenced by Mod.Show.mTempoVis.TempoVis::activateWorkbench(), Mod.Show.SceneDetail.SceneDetail::apply_data(), importIFClegacy.IfcSchema::capitalize(), Mod.Show.mTempoVis.TempoVis::forget(), Mod.Show.mTempoVis.TempoVis::forgetDetail(), Mod.Show.mTempoVis.TempoVis::has(), ArchSchedule.CommandArchSchedule::IsActive(), importIFClegacy.IfcSchema::readEntities(), importIFClegacy.IfcSchema::readTypes(), Mod.Show.mTempoVis.TempoVis::restore(), Mod.Show.mTempoVis.TempoVis::save(), Mod.Show.mTempoVis.TempoVis::stored_val(), FeaturePython.ViewProviderOctahedron::updateData(), and Dice3DS.dom3ds.UndefinedChunk::write().
removeRows()
bool DownloadModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex())
Referenced by Gui::Dialog::DownloadManager::cleanup().
rowCount()
int DownloadModel::rowCount (const QModelIndex & parent = QModelIndex()) const
Referenced by package_list.PackageListItemModel::append_item(), package_list.PackageListItemModel::clear(), and data().
Friends And Related Function Documentation
DownloadManager
friend class DownloadManager friend
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DownloadManager.h
FreeCAD/src/Gui/DownloadManager.cpp