FreeCAD: PathTests.TestPathToolBit.TestPathToolBit Class Reference
PathTests.TestPathToolBit.TestPathToolBit Class Reference
Public Member Functions
def test (self)
def test00 (self)
def test01 (self)
def test02 (self)
def test03 (self)
def test04 (self)
def test10 (self)
def test11 (self)
def test12 (self)
def test13 (self)
def test14 (self)
def test20 (self)
def test21 (self)
def test22 (self)
def test23 (self)
def test24 (self)
Public Member Functions inherited from PathTests.PathTestUtils.PathTestBase
def assertArc (self, edge, pt1, pt2, direction="CW")
def assertCircle (self, edge, pt, r)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertCommandEqual (self, c1, c2)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertEdgeShapesMatch (self, e1, e2)
def assertEqualLocale (self, s1, s2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertPlacement (self, p1, p2)
def assertPointsMatch (self, pts0, pts1)
def assertRoughly (self, f1, f2, error=0.00001)
Member Function Documentation
test()
def PathTests.TestPathToolBit.TestPathToolBit.test (self)
Log test setup directory structure
References PathTests.TestPathToolBit.printTree().
test00()
def PathTests.TestPathToolBit.TestPathToolBit.test00 (self)
Find a tool shape from file name
Referenced by PathTests.TestPathTool.TestPathTool.test01(), PathTests.TestPathToolController.TestPathToolController.test01(), PathTests.TestPathTooltable.TestPathTooltable.test01(), PathTests.TestPathTool.TestPathTool.test02(), and PathTests.TestPathTooltable.TestPathTooltable.test02().
test01()
def PathTests.TestPathToolBit.TestPathToolBit.test01 (self)
Not find a relative path shape if not stored in default location
test02()
def PathTests.TestPathToolBit.TestPathToolBit.test02 (self)
Find a relative path shape if it's local to a bit path
References PathTests.TestPathToolBit.testToolBit(), and PathTests.TestPathToolBit.testToolShape().
test03()
def PathTests.TestPathToolBit.TestPathToolBit.test03 (self)
Not find a tool shape from an invalid absolute path.
References PathTests.TestPathToolBit.testToolShape().
test04()
def PathTests.TestPathToolBit.TestPathToolBit.test04 (self)
Find a tool shape from a valid absolute path.
References PathTests.TestPathToolBit.testToolShape().
test10()
def PathTests.TestPathToolBit.TestPathToolBit.test10 (self)
Find a tool bit from file name
test11()
def PathTests.TestPathToolBit.TestPathToolBit.test11 (self)
Not find a relative path bit if not stored in default location
test12()
def PathTests.TestPathToolBit.TestPathToolBit.test12 (self)
Find a relative path bit if it's local to a library path
References PathTests.TestPathToolBit.testToolBit(), and PathTests.TestPathToolBit.testToolLibrary().
test13()
def PathTests.TestPathToolBit.TestPathToolBit.test13 (self)
Not find a tool bit from an invalid absolute path.
References PathTests.TestPathToolBit.testToolBit().
test14()
def PathTests.TestPathToolBit.TestPathToolBit.test14 (self)
Find a tool bit from a valid absolute path.
References PathTests.TestPathToolBit.testToolBit().
test20()
def PathTests.TestPathToolBit.TestPathToolBit.test20 (self)
Find a tool library from file name
test21()
def PathTests.TestPathToolBit.TestPathToolBit.test21 (self)
Not find a relative path library if not stored in default location
test22()
def PathTests.TestPathToolBit.TestPathToolBit.test22 (self)
[skipped] Find a relative path library if it's local to <what?>
test23()
def PathTests.TestPathToolBit.TestPathToolBit.test23 (self)
Not find a tool library from an invalid absolute path.
References PathTests.TestPathToolBit.testToolLibrary().
test24()
def PathTests.TestPathToolBit.TestPathToolBit.test24 (self)
Find a tool library from a valid absolute path.
References PathTests.TestPathToolBit.testToolBit().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Path/PathTests/TestPathToolBit.py