FreeCAD: App::PropertyIntegerConstraint Class Reference
App::PropertyIntegerConstraint Class Reference
Constraint integer properties This property fulfills the need of a constraint integer.
#include <PropertyStandard.h>
Classes
struct Constraints
Constraint methods.
Public Member Functions
const Constraints * getConstraints (void) const
get the constraint struct
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
long getMaximum () const
long getMinimum () const
long getStepSize () const
PropertyIntegerConstraint ()
Standard constructor.
void setConstraints (const Constraints *sConstraint)
setting the boundaries This sets the constraint struct.
virtual void setPyObject (PyObject *)
virtual ~PropertyIntegerConstraint ()
destructor
Public Member Functions inherited from App::PropertyInteger
virtual Property * Copy (void) const
Returns a new copy of the property (mainly for Undo/Redo and transactions)
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
virtual const boost::any getPathValue (const App::ObjectIdentifier &) const
Get value of property.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
long getValue (void) const
This method returns a string representation of the property.
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
virtual void Paste (const Property &from)
Paste the value from the property (mainly for Undo/Redo and transactions)
PropertyInteger ()
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual void setPyObject (PyObject *)
void setValue (long)
Sets the property.
virtual ~PropertyInteger ()
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual Property * Copy (void) const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
int64_t getID () const
Return a unique ID for the property.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const char * getName (void) const
Get the name of this property in the belonging container With hasName() it can be checked beforehand if a valid name is set.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
bool hasName () const
Check if the property has a name set.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , Busy = 15 ,
CopyOnChange = 16 , UserEdit = 17 , PropStaticBegin = 21 , PropDynamic = 21 ,
PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 , PropTransient = 25 ,
PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 , User1 = 28 ,
User2 = 29 , User3 = 30 , User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Check if the passed name is valid.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Detailed Description
Constraint integer properties This property fulfills the need of a constraint integer.
It holds basically a state (integer) and a struct of boundaries. If the boundaries is not set it acts basically like an IntegerProperty and does no checking. The constraints struct can be created on the heap or build in.
Constructor & Destructor Documentation
PropertyIntegerConstraint()
PropertyIntegerConstraint::PropertyIntegerConstraint ()
Standard constructor.
~PropertyIntegerConstraint()
PropertyIntegerConstraint::~PropertyIntegerConstraint () virtual
destructor
Member Function Documentation
getConstraints()
const PropertyIntegerConstraint::Constraints * PropertyIntegerConstraint::getConstraints (void) const
get the constraint struct
getEditorName()
virtual const char * App::PropertyIntegerConstraint::getEditorName (void) const virtual
Get the class name of the associated property editor item.
Reimplemented from App::PropertyInteger.
getMaximum()
long PropertyIntegerConstraint::getMaximum () const
getMinimum()
long PropertyIntegerConstraint::getMinimum () const
getStepSize()
long PropertyIntegerConstraint::getStepSize () const
setConstraints()
void PropertyIntegerConstraint::setConstraints (const Constraints * sConstraint)
setting the boundaries This sets the constraint struct.
It can be dynamically allocated or set as a static in the class the property belongs to:
const Constraints percent = {0,100,1}
Referenced by App::FeatureTest::FeatureTest(), PartDesign::LinearPattern::LinearPattern(), PartDesign::PolarPattern::PolarPattern(), setPyObject(), PartDesignGui::ViewProviderDatumCoordinateSystem::ViewProviderDatumCoordinateSystem(), and Gui::ViewProviderGeometryObject::ViewProviderGeometryObject().
setPyObject()
void PropertyIntegerConstraint::setPyObject (PyObject * value) virtual
Reimplemented from App::PropertyInteger.
References App::Property::aboutToSetValue(), App::Property::hasSetValue(), and setConstraints().
The documentation for this class was generated from the following files:
FreeCAD/src/App/PropertyStandard.h
FreeCAD/src/App/PropertyStandard.cpp