FreeCAD: Part::Hyperbola2dPy Class Reference
Part::Hyperbola2dPy Class Reference
The python export class for Geom2dHyperbola.
#include <Hyperbola2dPy.h>
Public Types
typedef Geom2dHyperbola * PointerType
Public Types inherited from Part::Conic2dPy
typedef Geom2dConic * PointerType
Public Types inherited from Part::Curve2dPy
typedef Geom2dCurve * PointerType
Public Types inherited from Part::Geometry2dPy
typedef Geometry2d * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
Hyperbola2dPy (Geom2dHyperbola *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Part::Conic2dPy
Conic2dPy (Geom2dConic *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
Py::Object getLocation (void) const
getter for the Location attribute
void setLocation (Py::Object arg)
setter for the Location attribute
Py::Float getEccentricity (void) const
getter for the Eccentricity attribute
Py::Object getXAxis (void) const
getter for the XAxis attribute
void setXAxis (Py::Object arg)
setter for the XAxis attribute
Py::Object getYAxis (void) const
getter for the YAxis attribute
void setYAxis (Py::Object arg)
setter for the YAxis attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geom2dConic * getGeom2dConicPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Part::Curve2dPy
Curve2dPy (Geom2dCurve *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * reverse (PyObject *args)
implementer for the reverse() method
PyObject * toShape (PyObject *args)
implementer for the toShape() method
PyObject * discretize (PyObject *args, PyObject *kwd)
implementer for the discretize() method
PyObject * length (PyObject *args)
implementer for the length() method
PyObject * parameterAtDistance (PyObject *args)
implementer for the parameterAtDistance() method
PyObject * value (PyObject *args)
implementer for the value() method
PyObject * tangent (PyObject *args)
implementer for the tangent() method
PyObject * parameter (PyObject *args)
implementer for the parameter() method
PyObject * normal (PyObject *args)
implementer for the normal() method
PyObject * curvature (PyObject *args)
implementer for the curvature() method
PyObject * centerOfCurvature (PyObject *args)
implementer for the centerOfCurvature() method
PyObject * intersectCC (PyObject *args)
implementer for the intersectCC() method
PyObject * toBSpline (PyObject *args)
implementer for the toBSpline() method
PyObject * approximateBSpline (PyObject *args)
implementer for the approximateBSpline() method
Py::String getContinuity (void) const
getter for the Continuity attribute
Py::Boolean getClosed (void) const
getter for the Closed attribute
Py::Boolean getPeriodic (void) const
getter for the Periodic attribute
Py::Float getFirstParameter (void) const
getter for the FirstParameter attribute
Py::Float getLastParameter (void) const
getter for the LastParameter attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geom2dCurve * getGeom2dCurvePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Part::Geometry2dPy
Geometry2dPy (Geometry2d *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geometry2d * getGeometry2dPtr (void) const
getter for the object handled by this class
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * copy (PyObject *args)
implementer for the copy() method
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::Conic2dPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_getLocation (PyObject *self, void *closure)
getter callback for the Location attribute
static int staticCallback_setLocation (PyObject *self, PyObject *value, void *closure)
setter callback for the Location attribute
static PyObject * staticCallback_getEccentricity (PyObject *self, void *closure)
getter callback for the Eccentricity attribute
static int staticCallback_setEccentricity (PyObject *self, PyObject *value, void *closure)
setter callback for the Eccentricity attribute
static PyObject * staticCallback_getXAxis (PyObject *self, void *closure)
getter callback for the XAxis attribute
static int staticCallback_setXAxis (PyObject *self, PyObject *value, void *closure)
setter callback for the XAxis attribute
static PyObject * staticCallback_getYAxis (PyObject *self, void *closure)
getter callback for the YAxis attribute
static int staticCallback_setYAxis (PyObject *self, PyObject *value, void *closure)
setter callback for the YAxis attribute
Static Public Member Functions inherited from Part::Curve2dPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_reverse (PyObject *self, PyObject *args)
callback for the reverse() method
static PyObject * staticCallback_toShape (PyObject *self, PyObject *args)
callback for the toShape() method
static PyObject * staticCallback_discretize (PyObject *self, PyObject *args, PyObject *kwd)
callback for the discretize() method
static PyObject * staticCallback_length (PyObject *self, PyObject *args)
callback for the length() method
static PyObject * staticCallback_parameterAtDistance (PyObject *self, PyObject *args)
callback for the parameterAtDistance() method
static PyObject * staticCallback_value (PyObject *self, PyObject *args)
callback for the value() method
static PyObject * staticCallback_tangent (PyObject *self, PyObject *args)
callback for the tangent() method
static PyObject * staticCallback_parameter (PyObject *self, PyObject *args)
callback for the parameter() method
static PyObject * staticCallback_normal (PyObject *self, PyObject *args)
callback for the normal() method
static PyObject * staticCallback_curvature (PyObject *self, PyObject *args)
callback for the curvature() method
static PyObject * staticCallback_centerOfCurvature (PyObject *self, PyObject *args)
callback for the centerOfCurvature() method
static PyObject * staticCallback_intersectCC (PyObject *self, PyObject *args)
callback for the intersectCC() method
static PyObject * staticCallback_toBSpline (PyObject *self, PyObject *args)
callback for the toBSpline() method
static PyObject * staticCallback_approximateBSpline (PyObject *self, PyObject *args)
callback for the approximateBSpline() method
static PyObject * staticCallback_getContinuity (PyObject *self, void *closure)
getter callback for the Continuity attribute
static int staticCallback_setContinuity (PyObject *self, PyObject *value, void *closure)
setter callback for the Continuity attribute
static PyObject * staticCallback_getClosed (PyObject *self, void *closure)
getter callback for the Closed attribute
static int staticCallback_setClosed (PyObject *self, PyObject *value, void *closure)
setter callback for the Closed attribute
static PyObject * staticCallback_getPeriodic (PyObject *self, void *closure)
getter callback for the Periodic attribute
static int staticCallback_setPeriodic (PyObject *self, PyObject *value, void *closure)
setter callback for the Periodic attribute
static PyObject * staticCallback_getFirstParameter (PyObject *self, void *closure)
getter callback for the FirstParameter attribute
static int staticCallback_setFirstParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the FirstParameter attribute
static PyObject * staticCallback_getLastParameter (PyObject *self, void *closure)
getter callback for the LastParameter attribute
static int staticCallback_setLastParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the LastParameter attribute
Static Public Member Functions inherited from Part::Geometry2dPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of Hyperbola2dPy.
static PyMethodDef Methods []
Methods structure of Hyperbola2dPy.
static PyTypeObject Type
Type structure of Hyperbola2dPy.
Static Public Attributes inherited from Part::Conic2dPy
static PyGetSetDef GetterSetter []
Attribute structure of Conic2dPy.
static PyMethodDef Methods []
Methods structure of Conic2dPy.
static PyTypeObject Type
Type structure of Conic2dPy.
Static Public Attributes inherited from Part::Curve2dPy
static PyGetSetDef GetterSetter []
Attribute structure of Curve2dPy.
static PyMethodDef Methods []
Methods structure of Curve2dPy.
static PyTypeObject Type
Type structure of Curve2dPy.
Static Public Attributes inherited from Part::Geometry2dPy
static PyGetSetDef GetterSetter []
Attribute structure of Geometry2dPy.
static PyMethodDef Methods []
Methods structure of Geometry2dPy.
static PyTypeObject Type
Type structure of Geometry2dPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~Hyperbola2dPy ()
Protected Member Functions inherited from Part::Conic2dPy
~Conic2dPy ()
Protected Member Functions inherited from Part::Curve2dPy
~Curve2dPy ()
Protected Member Functions inherited from Part::Geometry2dPy
~Geometry2dPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object attributes
Py::Float getMajorRadius (void) const
getter for the MajorRadius attribute
void setMajorRadius (Py::Float arg)
setter for the MajorRadius attribute
Py::Float getMinorRadius (void) const
getter for the MinorRadius attribute
void setMinorRadius (Py::Float arg)
setter for the MinorRadius attribute
Py::Float getFocal (void) const
getter for the Focal attribute
Py::Object getFocus1 (void) const
getter for the Focus1 attribute
Py::Object getFocus2 (void) const
getter for the Focus2 attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geom2dHyperbola * getGeom2dHyperbolaPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getMajorRadius (PyObject *self, void *closure)
getter callback for the MajorRadius attribute
static int staticCallback_setMajorRadius (PyObject *self, PyObject *value, void *closure)
setter callback for the MajorRadius attribute
static PyObject * staticCallback_getMinorRadius (PyObject *self, void *closure)
getter callback for the MinorRadius attribute
static int staticCallback_setMinorRadius (PyObject *self, PyObject *value, void *closure)
setter callback for the MinorRadius attribute
static PyObject * staticCallback_getFocal (PyObject *self, void *closure)
getter callback for the Focal attribute
static int staticCallback_setFocal (PyObject *self, PyObject *value, void *closure)
setter callback for the Focal attribute
static PyObject * staticCallback_getFocus1 (PyObject *self, void *closure)
getter callback for the Focus1 attribute
static int staticCallback_setFocus1 (PyObject *self, PyObject *value, void *closure)
setter callback for the Focus1 attribute
static PyObject * staticCallback_getFocus2 (PyObject *self, void *closure)
getter callback for the Focus2 attribute
static int staticCallback_setFocus2 (PyObject *self, PyObject *value, void *closure)
setter callback for the Focus2 attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Geom2dHyperbola.
Member Typedef Documentation
PointerType
typedef Geom2dHyperbola* Part::Hyperbola2dPy::PointerType
Constructor & Destructor Documentation
~Hyperbola2dPy()
Hyperbola2dPy::~Hyperbola2dPy () protected
Hyperbola2dPy()
Hyperbola2dPy::Hyperbola2dPy (Geom2dHyperbola * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getCustomAttributes()
PyObject * Hyperbola2dPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getFocal()
Py::Float Hyperbola2dPy::getFocal (void) const
getter for the Focal attribute
References getGeom2dHyperbolaPtr().
Referenced by staticCallback_getFocal().
getFocus1()
Py::Object Hyperbola2dPy::getFocus1 (void) const
getter for the Focus1 attribute
References getGeom2dHyperbolaPtr().
Referenced by staticCallback_getFocus1().
getFocus2()
Py::Object Hyperbola2dPy::getFocus2 (void) const
getter for the Focus2 attribute
References getGeom2dHyperbolaPtr().
Referenced by staticCallback_getFocus2().
getGeom2dHyperbolaPtr()
Geom2dHyperbola * Hyperbola2dPy::getGeom2dHyperbolaPtr (void) const
getter for the object handled by this class
Referenced by getFocal(), getFocus1(), getFocus2(), getMajorRadius(), getMinorRadius(), PyInit(), setMajorRadius(), and setMinorRadius().
getMajorRadius()
Py::Float Hyperbola2dPy::getMajorRadius (void) const
getter for the MajorRadius attribute
References getGeom2dHyperbolaPtr().
Referenced by staticCallback_getMajorRadius().
getMinorRadius()
Py::Float Hyperbola2dPy::getMinorRadius (void) const
getter for the MinorRadius attribute
References getGeom2dHyperbolaPtr().
Referenced by staticCallback_getMinorRadius().
GetType()
virtual PyTypeObject* Part::Hyperbola2dPy::GetType (void) virtual
Reimplemented from Part::Conic2dPy.
PyInit()
int Hyperbola2dPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::Conic2dPy.
References getGeom2dHyperbolaPtr(), Part::PartExceptionOCCError, and Type.
PyMake()
PyObject * Hyperbola2dPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References Hyperbola2dPy().
representation()
std::string Hyperbola2dPy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int Hyperbola2dPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setMajorRadius()
void Hyperbola2dPy::setMajorRadius (Py::Float arg)
setter for the MajorRadius attribute
References getGeom2dHyperbolaPtr().
Referenced by staticCallback_setMajorRadius().
setMinorRadius()
void Hyperbola2dPy::setMinorRadius (Py::Float arg)
setter for the MinorRadius attribute
References getGeom2dHyperbolaPtr().
Referenced by staticCallback_setMinorRadius().
staticCallback_getFocal()
PyObject * Hyperbola2dPy::staticCallback_getFocal (PyObject * self, void * closure) static
getter callback for the Focal attribute
References Base::BaseExceptionFreeCADError, getFocal(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFocus1()
PyObject * Hyperbola2dPy::staticCallback_getFocus1 (PyObject * self, void * closure) static
getter callback for the Focus1 attribute
References Base::BaseExceptionFreeCADError, getFocus1(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFocus2()
PyObject * Hyperbola2dPy::staticCallback_getFocus2 (PyObject * self, void * closure) static
getter callback for the Focus2 attribute
References Base::BaseExceptionFreeCADError, getFocus2(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMajorRadius()
PyObject * Hyperbola2dPy::staticCallback_getMajorRadius (PyObject * self, void * closure) static
getter callback for the MajorRadius attribute
References Base::BaseExceptionFreeCADError, getMajorRadius(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMinorRadius()
PyObject * Hyperbola2dPy::staticCallback_getMinorRadius (PyObject * self, void * closure) static
getter callback for the MinorRadius attribute
References Base::BaseExceptionFreeCADError, getMinorRadius(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setFocal()
int Hyperbola2dPy::staticCallback_setFocal (PyObject * self, PyObject * value, void * closure) static
setter callback for the Focal attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setFocus1()
int Hyperbola2dPy::staticCallback_setFocus1 (PyObject * self, PyObject * value, void * closure) static
setter callback for the Focus1 attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setFocus2()
int Hyperbola2dPy::staticCallback_setFocus2 (PyObject * self, PyObject * value, void * closure) static
setter callback for the Focus2 attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setMajorRadius()
int Hyperbola2dPy::staticCallback_setMajorRadius (PyObject * self, PyObject * value, void * closure) static
setter callback for the MajorRadius attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setMajorRadius().
staticCallback_setMinorRadius()
int Hyperbola2dPy::staticCallback_setMinorRadius (PyObject * self, PyObject * value, void * closure) static
setter callback for the MinorRadius attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setMinorRadius().
Member Data Documentation
GetterSetter
PyGetSetDef Hyperbola2dPy::GetterSetter static
Attribute structure of Hyperbola2dPy.
Methods
PyMethodDef Hyperbola2dPy::Methods static
Initial value:
= {
    {NULL, NULL, 0, NULL}
}
Methods structure of Hyperbola2dPy.
Type
PyTypeObject Hyperbola2dPy::Type static
Type structure of Hyperbola2dPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), Part::ArcOfHyperbola2dPy::PyInit(), PyInit(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/Geom2d/Hyperbola2dPy.h
Sources/FreeCAD/src/Mod/Part/App/Geom2d/Hyperbola2dPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/Geom2d/Hyperbola2dPy.cpp