FreeCAD: TechDrawGui::TaskWeldingSymbol Class Reference
TechDrawGui::TaskWeldingSymbol Class Reference
#include <TaskWeldingSymbol.h>
Public Slots
void onArrowSymbolClicked ()
void onArrowSymbolCreateClicked ()
void onArrowTextChanged ()
void onDirectorySelected (const QString &newDir)
void onFlipSidesClicked ()
void onFlipSidesCreateClicked ()
void onOtherEraseClicked ()
void onOtherEraseCreateClicked ()
void onOtherSymbolClicked ()
void onOtherSymbolCreateClicked ()
void onOtherTextChanged ()
void onSymbolSelected (QString symbolPath, QString source)
void onWeldingChanged ()
Public Member Functions
virtual bool accept ()
void enableTaskButtons (bool b)
virtual bool reject ()
void saveButtons (QPushButton *btnOK, QPushButton *btnCancel)
TaskWeldingSymbol (TechDraw::DrawLeaderLine *baseFeat)
TaskWeldingSymbol (TechDraw::DrawWeldSymbol *weldFeat)
void updateTask ()
~TaskWeldingSymbol ()
Protected Member Functions
void changeEvent (QEvent *e)
void collectArrowData (void)
void collectOtherData (void)
TechDraw::DrawWeldSymbol * createWeldingSymbol (void)
void getTileFeats (void)
std::string prefSymbolDir ()
void setUiEdit ()
void setUiPrimary (void)
void updateTiles (void)
void updateWeldingSymbol (void)
Protected Attributes
QString m_currDir
Constructor & Destructor Documentation
TaskWeldingSymbol() [1/2]
TaskWeldingSymbol::TaskWeldingSymbol (TechDraw::DrawLeaderLine * baseFeat)
References draftgeoutils.intersections::connect(), onArrowSymbolCreateClicked(), onDirectorySelected(), onFlipSidesCreateClicked(), onOtherEraseCreateClicked(), onOtherSymbolCreateClicked(), and setUiPrimary().
TaskWeldingSymbol() [2/2]
TaskWeldingSymbol::TaskWeldingSymbol (TechDraw::DrawWeldSymbol * weldFeat)
References draftgeoutils.intersections::connect(), Base::Console(), Base::ConsoleSingleton::Error(), Base::Persistence::getClassTypeId(), App::PropertyLink::getValue(), TechDraw::DrawWeldSymbol::Leader, onArrowSymbolClicked(), onArrowTextChanged(), onDirectorySelected(), onFlipSidesClicked(), onOtherEraseClicked(), onOtherSymbolClicked(), onOtherTextChanged(), onWeldingChanged(), and setUiEdit().
~TaskWeldingSymbol()
TaskWeldingSymbol::~TaskWeldingSymbol ()
Member Function Documentation
accept()
bool TaskWeldingSymbol::accept (void) virtual
References Gui::Command::commitCommand(), Base::Console(), createWeldingSymbol(), Base::ConsoleSingleton::Error(), Gui::Command::Gui, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, App::DocumentObject::recomputeFeature(), Gui::Command::updateActive(), updateTiles(), and updateWeldingSymbol().
Referenced by TechDrawGui::TaskDlgWeldingSymbol::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void TaskWeldingSymbol::changeEvent (QEvent * e) protected
collectArrowData()
void TaskWeldingSymbol::collectArrowData (void) protected
References TechDrawGui::TileImage::arrowSide, TechDrawGui::TileImage::centerText, TechDrawGui::TileImage::col, TechDrawGui::TileImage::leftText, TechDrawGui::TileImage::rightText, TechDrawGui::TileImage::row, TechDrawGui::TileImage::symbolPath, TechDrawGui::TileImage::tileName, and TechDrawGui::TileImage::toBeSaved.
Referenced by updateTiles().
collectOtherData()
void TaskWeldingSymbol::collectOtherData (void) protected
References TechDrawGui::TileImage::arrowSide, TechDrawGui::TileImage::centerText, TechDrawGui::TileImage::col, TechDrawGui::TileImage::leftText, TechDrawGui::TileImage::rightText, TechDrawGui::TileImage::row, TechDrawGui::TileImage::symbolPath, TechDrawGui::TileImage::tileName, and TechDrawGui::TileImage::toBeSaved.
Referenced by updateTiles().
createWeldingSymbol()
TechDraw::DrawWeldSymbol * TaskWeldingSymbol::createWeldingSymbol (void) protected
References Base::Tools::escapeEncodeString(), TechDraw::DrawView::findParentPage(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), and App::Document::getUniqueObjectName().
Referenced by accept().
enableTaskButtons()
void TaskWeldingSymbol::enableTaskButtons (bool b)
getTileFeats()
void TaskWeldingSymbol::getTileFeats (void) protected
References TechDraw::DrawWeldSymbol::getTiles(), App::PropertyInteger::getValue(), and TechDraw::DrawTile::TileRow.
Referenced by setUiEdit(), and updateTiles().
onArrowSymbolClicked
void TaskWeldingSymbol::onArrowSymbolClicked () slot
References draftgeoutils.intersections::connect(), m_currDir, onSymbolSelected(), TechDraw::DrawView::requestPaint(), and updateTiles().
Referenced by TaskWeldingSymbol().
onArrowSymbolCreateClicked
void TaskWeldingSymbol::onArrowSymbolCreateClicked () slot
References draftgeoutils.intersections::connect(), m_currDir, and onSymbolSelected().
Referenced by TaskWeldingSymbol().
onArrowTextChanged
void TaskWeldingSymbol::onArrowTextChanged () slot
References TechDraw::DrawView::requestPaint(), and updateTiles().
Referenced by TaskWeldingSymbol().
onDirectorySelected
void TaskWeldingSymbol::onDirectorySelected (const QString & newDir) slot
References m_currDir.
Referenced by TaskWeldingSymbol().
onFlipSidesClicked
void TaskWeldingSymbol::onFlipSidesClicked () slot
References App::PropertyString::getValue(), TechDraw::DrawView::requestPaint(), TechDraw::DrawTileWeld::SymbolFile, and updateTiles().
Referenced by TaskWeldingSymbol().
onFlipSidesCreateClicked
void TaskWeldingSymbol::onFlipSidesCreateClicked () slot
Referenced by TaskWeldingSymbol().
onOtherEraseClicked
void TaskWeldingSymbol::onOtherEraseClicked () slot
References TechDrawGui::TileImage::init(), TechDraw::DrawView::requestPaint(), and updateTiles().
Referenced by TaskWeldingSymbol().
onOtherEraseCreateClicked
void TaskWeldingSymbol::onOtherEraseCreateClicked () slot
References TechDrawGui::TileImage::init().
Referenced by TaskWeldingSymbol().
onOtherSymbolClicked
void TaskWeldingSymbol::onOtherSymbolClicked () slot
References draftgeoutils.intersections::connect(), m_currDir, onSymbolSelected(), TechDraw::DrawView::requestPaint(), and updateTiles().
Referenced by TaskWeldingSymbol().
onOtherSymbolCreateClicked
void TaskWeldingSymbol::onOtherSymbolCreateClicked () slot
References draftgeoutils.intersections::connect(), m_currDir, and onSymbolSelected().
Referenced by TaskWeldingSymbol().
onOtherTextChanged
void TaskWeldingSymbol::onOtherTextChanged () slot
References TechDraw::DrawView::requestPaint(), and updateTiles().
Referenced by TaskWeldingSymbol().
onSymbolSelected
void TaskWeldingSymbol::onSymbolSelected (QString symbolPath, QString source) slot
Referenced by onArrowSymbolClicked(), onArrowSymbolCreateClicked(), onOtherSymbolClicked(), and onOtherSymbolCreateClicked().
onWeldingChanged
void TaskWeldingSymbol::onWeldingChanged () slot
References TechDraw::DrawView::requestPaint(), and updateWeldingSymbol().
Referenced by TaskWeldingSymbol().
prefSymbolDir()
std::string TechDrawGui::TaskWeldingSymbol::prefSymbolDir () protected
reject()
bool TaskWeldingSymbol::reject (void) virtual
References Gui::Command::Gui.
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), TechDrawGui::TaskDlgWeldingSymbol::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
saveButtons()
void TaskWeldingSymbol::saveButtons (QPushButton * btnOK, QPushButton * btnCancel)
Referenced by TechDrawGui::TaskDlgWeldingSymbol::modifyStandardButtons().
setUiEdit()
void TaskWeldingSymbol::setUiEdit (void) protected
References TechDraw::DrawWeldSymbol::AllAround, TechDraw::DrawWeldSymbol::AlternatingWeld, TechDraw::DrawTileWeld::CenterText, TechDraw::DrawWeldSymbol::FieldWeld, getTileFeats(), App::PropertyString::getValue(), App::PropertyBool::getValue(), TechDraw::DrawTileWeld::LeftText, m_currDir, TechDraw::DrawTileWeld::RightText, TechDraw::DrawTileWeld::SymbolFile, TechDraw::DrawWeldSymbol::TailText, and TechDrawGui::PreferencesGui::weldingDirectory().
Referenced by TaskWeldingSymbol().
setUiPrimary()
void TaskWeldingSymbol::setUiPrimary (void) protected
References TechDrawGui::TileImage::init(), m_currDir, and TechDrawGui::PreferencesGui::weldingDirectory().
Referenced by TaskWeldingSymbol().
updateTask()
void TaskWeldingSymbol::updateTask ()
updateTiles()
void TaskWeldingSymbol::updateTiles (void) protected
References TechDrawGui::TileImage::centerText, TechDrawGui::TileImage::col, collectArrowData(), collectOtherData(), Base::Console(), Base::Tools::escapeEncodeString(), App::DocumentObject::getNameInDocument(), getTileFeats(), TechDrawGui::TileImage::leftText, Base::ConsoleSingleton::Message(), TechDrawGui::TileImage::rightText, App::PropertyString::setValue(), TechDraw::DrawTileWeld::SymbolFile, TechDrawGui::TileImage::symbolPath, and TechDrawGui::TileImage::toBeSaved.
Referenced by accept(), onArrowSymbolClicked(), onArrowTextChanged(), onFlipSidesClicked(), onOtherEraseClicked(), onOtherSymbolClicked(), and onOtherTextChanged().
updateWeldingSymbol()
void TaskWeldingSymbol::updateWeldingSymbol (void) protected
References Base::Tools::escapeEncodeString(), and App::DocumentObject::getNameInDocument().
Referenced by accept(), and onWeldingChanged().
Member Data Documentation
m_currDir
QString TechDrawGui::TaskWeldingSymbol::m_currDir protected
Referenced by onArrowSymbolClicked(), onArrowSymbolCreateClicked(), onDirectorySelected(), onOtherSymbolClicked(), onOtherSymbolCreateClicked(), setUiEdit(), and setUiPrimary().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/TaskWeldingSymbol.h
FreeCAD/src/Mod/TechDraw/Gui/TaskWeldingSymbol.cpp