FreeCAD: MeshCore::MeshRefPointToPoints Class Reference
MeshCore::MeshRefPointToPoints Class Reference
The MeshRefPointToPoints builds up a structure to have access to all neighbour points
of a point.
#include <Algorithm.h>
Public Member Functions
void AddNeighbour (unsigned long, unsigned long)
float GetAverageEdgeLength (unsigned long) const
Base::Vector3f GetNormal (unsigned long) const
MeshRefPointToPoints (const MeshKernel &rclM)
Construction.
const std::set< unsigned long > & operator[] (unsigned long) const
void Rebuild (void)
Rebuilds up data structure.
void RemoveNeighbour (unsigned long, unsigned long)
~MeshRefPointToPoints (void)
Destruction.
Detailed Description
The MeshRefPointToPoints builds up a structure to have access to all neighbour points
of a point.
Two points are neighbours if there is an edge indexing both points.
Note
If the underlying mesh kernel gets changed this structure becomes invalid and must be rebuilt.
Constructor & Destructor Documentation
MeshRefPointToPoints()
MeshCore::MeshRefPointToPoints::MeshRefPointToPoints (const MeshKernel & rclM)
Construction.
~MeshRefPointToPoints()
MeshCore::MeshRefPointToPoints::~MeshRefPointToPoints (void)
Destruction.
Member Function Documentation
AddNeighbour()
void MeshRefPointToPoints::AddNeighbour (unsigned long pos, unsigned long facet)
GetAverageEdgeLength()
float MeshRefPointToPoints::GetAverageEdgeLength (unsigned long index) const
References Base::Distance().
GetNormal()
Base::Vector3f MeshRefPointToPoints::GetNormal (unsigned long pos) const
References MeshCore::Approximation::AddPoint(), MeshCore::PlaneFit::Fit(), MeshCore::PlaneFit::GetNormal(), and Base::Vector3< _Precision >::Normalize().
operator[]()
const std::set< unsigned long > & MeshRefPointToPoints::operator[] (unsigned long pos) const
Rebuild()
void MeshRefPointToPoints::Rebuild (void)
Rebuilds up data structure.
RemoveNeighbour()
void MeshRefPointToPoints::RemoveNeighbour (unsigned long pos, unsigned long facet)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Algorithm.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Algorithm.cpp