FreeCAD: CAreaOrderer Class Reference
CAreaOrderer Class Reference
#include <AreaOrderer.h>
Public Member Functions
CAreaOrderer ()
void Insert (std::shared_ptr< CCurve > pcurve)
CArea ResultArea () const
Public Attributes
std::shared_ptr< CInnerCurves > m_top_level
Constructor & Destructor Documentation
CAreaOrderer()
CAreaOrderer::CAreaOrderer ()
Member Function Documentation
Insert()
void CAreaOrderer::Insert (std::shared_ptr< CCurve > pcurve)
References CInnerCurves::area_orderer, CCurve::IsClockwise(), m_top_level, and CCurve::Reverse().
Referenced by CArea::Reorder().
ResultArea()
CArea CAreaOrderer::ResultArea () const
References m_top_level.
Member Data Documentation
m_top_level
std::shared_ptr<CInnerCurves> CAreaOrderer::m_top_level
Referenced by Insert(), CArea::Reorder(), and ResultArea().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Path/libarea/AreaOrderer.h
Sources/FreeCAD/src/Mod/Path/libarea/AreaOrderer.cpp