FreeCAD: Gui::DocumentObjectData Class Reference
Gui::DocumentObjectData Class Reference
Public Types
typedef boost::signals2::scoped_connection Connection
Public Member Functions
DocumentObjectData (DocumentItem *docItem, ViewProviderDocumentObject *vpd)
const char * getTreeName () const
void slotChangeIcon ()
void slotChangeStatusTip (const QString &tip)
void slotChangeToolTip (const QString &tip)
void testStatus (bool resetStatus=false)
bool updateChildren (bool checkVisibility)
void updateChildren (DocumentObjectDataPtr other)
Public Attributes
std::vector< App::DocumentObject * > children
std::set< App::DocumentObject * > childSet
Connection connectIcon
Connection connectStat
Connection connectTool
DocumentItem * docItem
bool itemHidden
DocumentObjectItems items
std::string label
std::string label2
bool removeChildrenFromRoot
DocumentObjectItem * rootItem
ViewProviderDocumentObject * viewObject
Member Typedef Documentation
Connection
typedef boost::signals2::scoped_connection Gui::DocumentObjectData::Connection
Constructor & Destructor Documentation
DocumentObjectData()
Gui::DocumentObjectData::DocumentObjectData (DocumentItem * docItem, ViewProviderDocumentObject * vpd)
References draftgeoutils.faces::bind(), Gui::ViewProvider::canRemoveChildrenFromRoot(), connectIcon, connectStat, connectTool, Gui::ViewProviderDocumentObject::getObject(), App::PropertyString::getValue(), itemHidden, App::DocumentObject::Label, App::DocumentObject::Label2, label2, removeChildrenFromRoot, Gui::ViewProviderDocumentObject::showInTree(), Gui::ViewProvider::signalChangeIcon, Gui::ViewProvider::signalChangeStatusTip, Gui::ViewProvider::signalChangeToolTip, slotChangeIcon(), slotChangeStatusTip(), slotChangeToolTip(), and viewObject.
Member Function Documentation
getTreeName()
const char* Gui::DocumentObjectData::getTreeName () const
References docItem, and Gui::DocumentItem::getTreeName().
slotChangeIcon()
void Gui::DocumentObjectData::slotChangeIcon ()
References testStatus().
Referenced by DocumentObjectData().
slotChangeStatusTip()
void Gui::DocumentObjectData::slotChangeStatusTip (const QString & tip)
References items.
Referenced by DocumentObjectData().
slotChangeToolTip()
void Gui::DocumentObjectData::slotChangeToolTip (const QString & tip)
References items.
Referenced by DocumentObjectData().
testStatus()
void Gui::DocumentObjectData::testStatus (bool resetStatus = false)
References items.
Referenced by slotChangeIcon().
updateChildren() [1/2]
bool Gui::DocumentObjectData::updateChildren (bool checkVisibility)
References children, childSet, Gui::ViewProvider::claimChildren(), docItem, Gui::DocumentItem::document(), Gui::Document::getDocument(), Gui::ViewProviderDocumentObject::getObject(), Gui::DocumentItem::getViewProvider(), Gui::DocumentItem::isObjectShowable(), Gui::ViewProviderDocumentObject::setShowable(), and viewObject.
updateChildren() [2/2]
void Gui::DocumentObjectData::updateChildren (DocumentObjectDataPtr other)
References children, and childSet.
Member Data Documentation
children
std::vector<App::DocumentObject*> Gui::DocumentObjectData::children
Referenced by prototype.Node::addtofreecad(), prototype.Node::pprint(), prototype.Node::pprint2(), prototype.Node::rlen(), and updateChildren().
childSet
std::set<App::DocumentObject*> Gui::DocumentObjectData::childSet
Referenced by updateChildren().
connectIcon
Connection Gui::DocumentObjectData::connectIcon
Referenced by DocumentObjectData().
connectStat
Connection Gui::DocumentObjectData::connectStat
Referenced by DocumentObjectData().
connectTool
Connection Gui::DocumentObjectData::connectTool
Referenced by DocumentObjectData().
docItem
DocumentItem* Gui::DocumentObjectData::docItem
Referenced by getTreeName(), and updateChildren().
itemHidden
bool Gui::DocumentObjectData::itemHidden
Referenced by DocumentObjectData().
items
DocumentObjectItems Gui::DocumentObjectData::items
Referenced by slotChangeStatusTip(), slotChangeToolTip(), testStatus(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
label
std::string Gui::DocumentObjectData::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
label2
std::string Gui::DocumentObjectData::label2
Referenced by DocumentObjectData().
removeChildrenFromRoot
bool Gui::DocumentObjectData::removeChildrenFromRoot
Referenced by DocumentObjectData().
rootItem
DocumentObjectItem* Gui::DocumentObjectData::rootItem
viewObject
ViewProviderDocumentObject* Gui::DocumentObjectData::viewObject
Referenced by BasicShapes.ViewProviderShapes.TaskTubeUI::accept(), DocumentObjectData(), BasicShapes.ViewProviderShapes.TaskTubeUI::onChangeHeight(), BasicShapes.ViewProviderShapes.TaskTubeUI::onChangeInnerRadius(), BasicShapes.ViewProviderShapes.TaskTubeUI::onChangeOuterRadius(), BasicShapes.ViewProviderShapes.TaskTubeUI::reject(), and updateChildren().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/Tree.cpp