FreeCAD: CustomReportEvent Class Reference
CustomReportEvent Class Reference
The CustomReportEvent class is used to send report events in the methods Log(), Error(), Warning() and Message() of the ReportOutput class to itself instead of printing the messages directly in its text view.
Public Member Functions
CustomReportEvent (ReportHighlighter::Paragraph p, const QString &s)
const QString & message () const
ReportHighlighter::Paragraph messageType () const
~CustomReportEvent ()
Detailed Description
The CustomReportEvent class is used to send report events in the methods Log(), Error(), Warning() and Message() of the ReportOutput class to itself instead of printing the messages directly in its text view.
This makes the methods Log(), Error(), Warning() and Message() thread-safe.
Author
Werner Mayer
Constructor & Destructor Documentation
CustomReportEvent()
CustomReportEvent::CustomReportEvent (ReportHighlighter::Paragraph p, const QString & s)
~CustomReportEvent()
CustomReportEvent::~CustomReportEvent ()
Member Function Documentation
message()
const QString& CustomReportEvent::message () const
Referenced by Gui::DockWnd::ReportOutput::customEvent().
messageType()
ReportHighlighter::Paragraph CustomReportEvent::messageType () const
Referenced by Gui::DockWnd::ReportOutput::customEvent(), and Gui::DockWnd::ReportOutputObserver::eventFilter().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/ReportView.cpp