FreeCAD: TechDrawGui::TaskLeaderLine Class Reference
TechDrawGui::TaskLeaderLine Class Reference
#include <TaskLeaderLine.h>
Public Slots
void onCancelEditClicked (bool b)
void onTrackerClicked (bool b)
void onTrackerFinished (std::vector< QPointF > pts, QGIView *qgParent)
Public Member Functions
virtual bool accept ()
void enableTaskButtons (bool b)
virtual bool getCreateMode (void)
void recomputeFeature ()
virtual bool reject ()
void saveButtons (QPushButton *btnOK, QPushButton *btnCancel)
virtual void setCreateMode (bool b)
TaskLeaderLine (TechDraw::DrawView *baseFeat, TechDraw::DrawPage *page)
TaskLeaderLine (TechDrawGui::ViewProviderLeader *leadVP)
void updateTask ()
~TaskLeaderLine ()
Protected Slots
void onPointEditComplete (void)
Protected Member Functions
void abandonEditSession (void)
void blockButtons (bool b)
void changeEvent (QEvent *e)
void commonFeatureUpdate (void)
void createLeaderFeature (std::vector< Base::Vector3d > converted)
void enableTextUi (bool b)
void enableVPUi (bool b)
QGIView * findParentQGIV ()
int getPrefArrowStyle ()
App::Color prefLineColor (void)
double prefWeight () const
void removeFeature (void)
void removeTracker (void)
void restoreState (void)
void saveState (void)
void setEditCursor (QCursor c)
void setUiEdit (void)
void setUiPrimary (void)
void startTracker (void)
void trackerPointsFromQPoints (std::vector< QPointF > pts)
void updateLeaderFeature ()
Constructor & Destructor Documentation
TaskLeaderLine() [1/2]
TaskLeaderLine::TaskLeaderLine (TechDraw::DrawView * baseFeat, TechDraw::DrawPage * page)
References draftgeoutils.intersections::connect(), Base::Console(), Base::ConsoleSingleton::Error(), TechDrawGui::QGVPage::findQViewForDocObj(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), TechDrawGui::ViewProviderPage::getMDIViewPage(), TechDrawGui::MDIViewPage::getQGVPage(), Gui::Document::getViewProvider(), Gui::Application::Instance, TechDrawGui::MDIViewPage::m_scene, onCancelEditClicked(), onTrackerClicked(), and setUiPrimary().
TaskLeaderLine() [2/2]
TaskLeaderLine::TaskLeaderLine (TechDrawGui::ViewProviderLeader * leadVP)
References draftgeoutils.intersections::connect(), Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::DrawView::findParentPage(), TechDrawGui::QGVPage::findQViewForDocObj(), Base::Persistence::getClassTypeId(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), TechDrawGui::ViewProviderLeader::getFeature(), TechDrawGui::ViewProviderPage::getMDIViewPage(), TechDrawGui::MDIViewPage::getQGVPage(), App::PropertyLink::getValue(), App::PropertyQuantity::getValue(), Gui::Document::getViewProvider(), TechDrawGui::Rez::guiX(), Gui::Application::Instance, TechDraw::DrawLeaderLine::LeaderParent, TechDrawGui::MDIViewPage::m_scene, onCancelEditClicked(), onTrackerClicked(), saveState(), setUiEdit(), TechDraw::DrawView::X, and TechDraw::DrawView::Y.
~TaskLeaderLine()
TaskLeaderLine::~TaskLeaderLine ()
Member Function Documentation
abandonEditSession()
void TaskLeaderLine::abandonEditSession (void) protected
References TechDrawGui::QGILeaderLine::abandonEdit(), enableTaskButtons(), Gui::getMainWindow(), setEditCursor(), and Gui::MainWindow::showMessage().
Referenced by accept(), onCancelEditClicked(), and reject().
accept()
bool TaskLeaderLine::accept (void) virtual
References abandonEditSession(), createLeaderFeature(), getCreateMode(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::Command::Gui, Gui::Application::Instance, removeTracker(), and updateLeaderFeature().
Referenced by TechDrawGui::TaskDlgLeaderLine::accept().
blockButtons()
void TechDrawGui::TaskLeaderLine::blockButtons (bool b) protected
changeEvent()
void TaskLeaderLine::changeEvent (QEvent * e) protected
commonFeatureUpdate()
void TaskLeaderLine::commonFeatureUpdate (void) protected
References TechDraw::DrawLeaderLine::EndSymbol, App::PropertyEnumeration::setValue(), and TechDraw::DrawLeaderLine::StartSymbol.
Referenced by createLeaderFeature(), and updateLeaderFeature().
createLeaderFeature()
void TaskLeaderLine::createLeaderFeature (std::vector< Base::Vector3d > converted) protected
References TechDraw::DrawLeaderLine::adjustLastSegment(), TechDrawGui::Rez::appX(), TechDraw::DrawLeaderLine::AutoHorizontal, Gui::Command::commitCommand(), commonFeatureUpdate(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), App::Document::getUniqueObjectName(), App::PropertyBool::getValue(), TechDrawGui::QGIView::getViewProvider(), Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, TechDraw::DrawView::requestPaint(), TechDraw::DrawView::setPosition(), App::Color::setValue(), App::PropertyListsT< T, ListT, ParentT >::setValues(), App::DocumentObject::touch(), Gui::Command::updateActive(), TechDraw::DrawLeaderLine::WayPoints, Base::Vector3< _Precision >::x, and Base::Vector3< _Precision >::y.
Referenced by accept().
enableTaskButtons()
void TaskLeaderLine::enableTaskButtons (bool b)
Referenced by abandonEditSession(), onCancelEditClicked(), onPointEditComplete(), onTrackerClicked(), and onTrackerFinished().
enableTextUi()
void TechDrawGui::TaskLeaderLine::enableTextUi (bool b) protected
enableVPUi()
void TaskLeaderLine::enableVPUi (bool b) protected
Referenced by setUiEdit(), and setUiPrimary().
findParentQGIV()
QGIView * TaskLeaderLine::findParentQGIV () protected
References TechDrawGui::ViewProviderDrawingView::getQView(), and TechDrawGui::QGIView::getViewProvider().
getCreateMode()
virtual bool TechDrawGui::TaskLeaderLine::getCreateMode (void) virtual
Referenced by accept(), onTrackerClicked(), and reject().
getPrefArrowStyle()
int TaskLeaderLine::getPrefArrowStyle () protected
References TechDrawGui::PreferencesGui::dimArrowStyle().
Referenced by setUiPrimary().
onCancelEditClicked
void TaskLeaderLine::onCancelEditClicked (bool b) slot
References abandonEditSession(), enableTaskButtons(), TechDraw::DrawView::requestPaint(), and setEditCursor().
Referenced by TaskLeaderLine().
onPointEditComplete
void TaskLeaderLine::onPointEditComplete (void) protected slot
References enableTaskButtons().
Referenced by onTrackerClicked().
onTrackerClicked
void TaskLeaderLine::onTrackerClicked (bool b) slot
References TechDrawGui::QGILeaderLine::closeEdit(), draftgeoutils.intersections::connect(), Base::Console(), enableTaskButtons(), Base::ConsoleSingleton::Error(), TechDrawGui::QGVPage::findQViewForDocObj(), getCreateMode(), Gui::getMainWindow(), TechDrawGui::MDIViewPage::getQGVPage(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Base::ConsoleSingleton::Message(), onPointEditComplete(), setEditCursor(), Gui::MainWindow::showMessage(), TechDrawGui::QGILeaderLine::startPathEdit(), startTracker(), TechDrawGui::QGTracker::terminateDrawing(), and TechDraw::DrawLeaderLine::WayPoints.
Referenced by TaskLeaderLine().
onTrackerFinished
void TaskLeaderLine::onTrackerFinished (std::vector< QPointF > pts, QGIView * qgParent) slot
References Base::Console(), enableTaskButtons(), Base::ConsoleSingleton::Error(), Gui::getMainWindow(), TechDrawGui::QGIView::getScale(), Base::ConsoleSingleton::Message(), draftfunctions.scale::scale(), setEditCursor(), Gui::MainWindow::showMessage(), TechDrawGui::QGTracker::sleep(), and trackerPointsFromQPoints().
Referenced by startTracker().
prefLineColor()
App::Color TaskLeaderLine::prefLineColor (void) protected
References TechDrawGui::PreferencesGui::leaderColor().
Referenced by setUiPrimary().
prefWeight()
double TaskLeaderLine::prefWeight () const protected
References TechDraw::LineGroup::lineGroupFactory().
Referenced by setUiPrimary().
recomputeFeature()
void TaskLeaderLine::recomputeFeature ()
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), and App::Document::recomputeFeature().
reject()
bool TaskLeaderLine::reject (void) virtual
References abandonEditSession(), getCreateMode(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::Command::Gui, Gui::Application::Instance, removeFeature(), removeTracker(), and restoreState().
Referenced by TechDrawGui::TaskDlgLeaderLine::reject().
removeFeature()
void TaskLeaderLine::removeFeature (void) protected
References Gui::Application::activeDocument(), Base::Console(), App::DocumentObject::getNameInDocument(), Gui::Document::getUndoVector(), Gui::Command::Gui, Gui::Command::hasPendingCommand(), Gui::Application::Instance, Base::ConsoleSingleton::Log(), Base::ConsoleSingleton::Message(), and Gui::Document::undo().
Referenced by reject().
removeTracker()
void TaskLeaderLine::removeTracker (void) protected
Referenced by accept(), and reject().
restoreState()
void TaskLeaderLine::restoreState (void) protected
References App::PropertyQuantity::setValue(), App::PropertyListsT< T, ListT, ParentT >::setValues(), TechDraw::DrawLeaderLine::WayPoints, TechDraw::DrawView::X, and TechDraw::DrawView::Y.
Referenced by reject().
saveButtons()
void TaskLeaderLine::saveButtons (QPushButton * btnOK, QPushButton * btnCancel)
Referenced by TechDrawGui::TaskDlgLeaderLine::modifyStandardButtons().
saveState()
void TaskLeaderLine::saveState (void) protected
References App::PropertyQuantity::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), TechDraw::DrawLeaderLine::WayPoints, TechDraw::DrawView::X, and TechDraw::DrawView::Y.
Referenced by TaskLeaderLine().
setCreateMode()
virtual void TechDrawGui::TaskLeaderLine::setCreateMode (bool b) virtual
setEditCursor()
void TaskLeaderLine::setEditCursor (QCursor c) protected
References TechDrawGui::QGVPage::findQViewForDocObj().
Referenced by abandonEditSession(), onCancelEditClicked(), onTrackerClicked(), onTrackerFinished(), and startTracker().
setUiEdit()
void TaskLeaderLine::setUiEdit (void) protected
References App::Color::asValue(), TechDrawGui::ViewProviderLeader::Color, draftgeoutils.intersections::connect(), enableVPUi(), TechDraw::DrawLeaderLine::EndSymbol, Base::Tools::fromStdString(), App::DocumentObject::getNameInDocument(), App::PropertyLink::getValue(), App::PropertyEnumeration::getValue(), App::PropertyColor::getValue(), App::PropertyQuantity::getValue(), TechDraw::DrawLeaderLine::LeaderParent, TechDrawGui::ViewProviderLeader::LineStyle, TechDrawGui::ViewProviderLeader::LineWidth, TechDrawGui::DrawGuiUtil::loadArrowBox(), and TechDraw::DrawLeaderLine::StartSymbol.
Referenced by TaskLeaderLine().
setUiPrimary()
void TaskLeaderLine::setUiPrimary (void) protected
References enableVPUi(), Base::Tools::fromStdString(), App::DocumentObject::getNameInDocument(), getPrefArrowStyle(), Base::Unit::Length, TechDrawGui::DrawGuiUtil::loadArrowBox(), prefLineColor(), and prefWeight().
Referenced by TaskLeaderLine().
startTracker()
void TaskLeaderLine::startTracker (void) protected
References draftgeoutils.intersections::connect(), Gui::getMainWindow(), onTrackerFinished(), setEditCursor(), and Gui::MainWindow::showMessage().
Referenced by onTrackerClicked().
trackerPointsFromQPoints()
void TaskLeaderLine::trackerPointsFromQPoints (std::vector< QPointF > pts) protected
Referenced by onTrackerFinished().
updateLeaderFeature()
void TaskLeaderLine::updateLeaderFeature (void) protected
References TechDrawGui::ViewProviderLeader::Color, Gui::Command::commitCommand(), commonFeatureUpdate(), TechDrawGui::ViewProviderLeader::LineStyle, TechDrawGui::ViewProviderLeader::LineWidth, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, TechDraw::DrawView::requestPaint(), App::PropertyEnumeration::setValue(), App::PropertyColor::setValue(), App::Color::setValue(), App::PropertyQuantity::setValue(), and Gui::Command::updateActive().
Referenced by accept().
updateTask()
void TaskLeaderLine::updateTask ()
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/TaskLeaderLine.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/TaskLeaderLine.cpp