FreeCAD: App::DocumentObjectWeakPtrT::Private Class Reference
App::DocumentObjectWeakPtrT::Private Class Reference
Public Types
typedef boost::signals2::scoped_connection Connection
Public Member Functions
void createdObject (const App::DocumentObject &obj) noexcept
void deletedDocument (const App::Document &doc)
void deletedObject (const App::DocumentObject &obj) noexcept
App::DocumentObject * get () const noexcept
Private (App::DocumentObject *obj)
void reset ()
void set (App::DocumentObject *obj)
Public Attributes
Connection connectApplicationDeletedDocument
Connection connectDocumentCreatedObject
Connection connectDocumentDeletedObject
bool indocument
App::DocumentObject * object
Member Typedef Documentation
Connection
typedef boost::signals2::scoped_connection App::DocumentObjectWeakPtrT::Private::Connection
Constructor & Destructor Documentation
Private()
App::DocumentObjectWeakPtrT::Private::Private (App::DocumentObject * obj)
References App::DocumentObjectWeakPtrT::Private::set().
Member Function Documentation
createdObject()
void App::DocumentObjectWeakPtrT::Private::createdObject (const App::DocumentObject & obj) noexcept
References App::DocumentObjectWeakPtrT::Private::indocument.
Referenced by App::DocumentObjectWeakPtrT::Private::set().
deletedDocument()
void App::DocumentObjectWeakPtrT::Private::deletedDocument (const App::Document & doc)
References App::DocumentObjectWeakPtrT::Private::reset().
Referenced by App::DocumentObjectWeakPtrT::Private::set().
deletedObject()
void App::DocumentObjectWeakPtrT::Private::deletedObject (const App::DocumentObject & obj) noexcept
References App::DocumentObjectWeakPtrT::Private::indocument.
Referenced by App::DocumentObjectWeakPtrT::Private::set().
get()
App::DocumentObject* App::DocumentObjectWeakPtrT::Private::get () const noexcept
References App::DocumentObjectWeakPtrT::Private::indocument, and App::DocumentObjectWeakPtrT::Private::object.
Referenced by draftguitools.gui_trackers.editTracker::move().
reset()
void App::DocumentObjectWeakPtrT::Private::reset ()
References App::DocumentObjectWeakPtrT::Private::connectApplicationDeletedDocument, App::DocumentObjectWeakPtrT::Private::connectDocumentCreatedObject, App::DocumentObjectWeakPtrT::Private::connectDocumentDeletedObject, and App::DocumentObjectWeakPtrT::Private::indocument.
Referenced by App::DocumentObjectWeakPtrT::Private::deletedDocument(), and draftguitools.gui_trackers.gridTracker::set().
set()
void App::DocumentObjectWeakPtrT::Private::set (App::DocumentObject * obj)
References draftgeoutils.faces::bind(), App::DocumentObjectWeakPtrT::Private::connectApplicationDeletedDocument, App::DocumentObjectWeakPtrT::Private::connectDocumentCreatedObject, App::DocumentObjectWeakPtrT::Private::connectDocumentDeletedObject, App::DocumentObjectWeakPtrT::Private::createdObject(), App::DocumentObjectWeakPtrT::Private::deletedDocument(), App::DocumentObjectWeakPtrT::Private::deletedObject(), App::GetApplication(), App::DocumentObjectWeakPtrT::Private::indocument, and App::Application::signalDeleteDocument.
Referenced by draftguitools.gui_trackers.editTracker::move(), and App::DocumentObjectWeakPtrT::Private::Private().
Member Data Documentation
connectApplicationDeletedDocument
Connection App::DocumentObjectWeakPtrT::Private::connectApplicationDeletedDocument
Referenced by App::DocumentObjectWeakPtrT::Private::reset(), and App::DocumentObjectWeakPtrT::Private::set().
connectDocumentCreatedObject
Connection App::DocumentObjectWeakPtrT::Private::connectDocumentCreatedObject
Referenced by App::DocumentObjectWeakPtrT::Private::reset(), and App::DocumentObjectWeakPtrT::Private::set().
connectDocumentDeletedObject
Connection App::DocumentObjectWeakPtrT::Private::connectDocumentDeletedObject
Referenced by App::DocumentObjectWeakPtrT::Private::reset(), and App::DocumentObjectWeakPtrT::Private::set().
indocument
bool App::DocumentObjectWeakPtrT::Private::indocument
Referenced by App::DocumentObjectWeakPtrT::Private::createdObject(), App::DocumentObjectWeakPtrT::Private::deletedObject(), App::DocumentObjectWeakPtrT::Private::get(), App::DocumentObjectWeakPtrT::Private::reset(), and App::DocumentObjectWeakPtrT::Private::set().
object
App::DocumentObject* App::DocumentObjectWeakPtrT::Private::object
Referenced by ArchIFCView.IfcContextUI::accept(), App::DocumentObjectWeakPtrT::Private::get(), ArchIFCView.IfcContextUI::prefillMapConversionForm(), importIFCHelper.ProjectImporter::setAttributes(), and importIFCHelper.ProjectImporter::setComplexAttributes().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/App/DocumentObserver.cpp