FreeCAD: Gui::UrlLabel Class Reference
Gui::UrlLabel Class Reference
A text label where a url can specified.
#include <Widgets.h>
Public Slots
void setLaunchExternal (bool l)
void setUrl (const QString &u)
Signals
void linkClicked (QString url)
Public Member Functions
bool launchExternal () const
QString url () const
UrlLabel (QWidget *parent=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
virtual ~UrlLabel ()
Protected Member Functions
void mouseReleaseEvent (QMouseEvent *)
Properties
bool launchExternal
QString url
Detailed Description
A text label where a url can specified.
When the user clicks on the text label the system browser gets opened with the specified url.
This can be used for e.g. in the about dialog where the url of the maintainer of an application can be specified.
Author
Werner Mayer
Constructor & Destructor Documentation
UrlLabel()
UrlLabel::UrlLabel (QWidget * parent = nullptr, Qt::WindowFlags f = Qt::WindowFlags())
~UrlLabel()
UrlLabel::~UrlLabel () virtual
Member Function Documentation
launchExternal()
bool Gui::UrlLabel::launchExternal () const
linkClicked
void Gui::UrlLabel::linkClicked (QString url) signal
Referenced by mouseReleaseEvent(), and SketcherGui::TaskSketcherMessages::TaskSketcherMessages().
mouseReleaseEvent()
void UrlLabel::mouseReleaseEvent (QMouseEvent *) protected
References linkClicked().
setLaunchExternal
void Gui::UrlLabel::setLaunchExternal (bool l) slot
setUrl
void UrlLabel::setUrl (const QString & u) slot
Referenced by Gui::Dialog::AboutDialog::setupLabels().
url()
QString UrlLabel::url () const
Referenced by addonmanager_macro.Macro::fill_details_from_wiki(), Addon.Addon::set_metadata(), Addon.Addon::to_cache(), and Addon.Addon::verify_url_and_branch().
Property Documentation
launchExternal
bool Gui::UrlLabel::launchExternal read write
url
QString Gui::UrlLabel::url read write
Referenced by addonmanager_macro.Macro::fill_details_from_wiki(), Addon.Addon::set_metadata(), Addon.Addon::to_cache(), and Addon.Addon::verify_url_and_branch().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/Widgets.h
FreeCAD/src/Gui/Widgets.cpp