FreeCAD: femexamples.constraint_tie Namespace Reference
femexamples.constraint_tie Namespace Reference
Functions
def get_information ()
def init_doc (doc=None)
def setup (doc=None, solvertype="ccxtools")
Variables
string mesh_name = "Mesh"
Function Documentation
get_information()
def femexamples.constraint_tie.get_information ()
init_doc()
def femexamples.constraint_tie.init_doc (doc = None)
Referenced by femexamples.constraint_tie.setup().
setup()
def femexamples.constraint_tie.setup (doc = None, solvertype = "ccxtools")
References femexamples.constraint_tie.init_doc(), ObjectsFem.makeAnalysis(), ObjectsFem.makeConstraintFixed(), ObjectsFem.makeConstraintForce(), ObjectsFem.makeConstraintTie(), ObjectsFem.makeMaterialSolid(), ObjectsFem.makeMeshGmsh(), ObjectsFem.makeSolverCalculix(), and ObjectsFem.makeSolverCalculixCcxTools().
Variable Documentation
mesh_name
string femexamples.constraint_tie.mesh_name = "Mesh"