FreeCAD: Part::CirclePy Class Reference
Part::CirclePy Class Reference
The python export class for GeomCircle.
#include <CirclePy.h>
Public Types
typedef GeomCircle * PointerType
Public Types inherited from Part::ConicPy
typedef GeomConic * PointerType
Public Types inherited from Part::GeometryCurvePy
typedef GeomCurve * PointerType
Public Types inherited from Part::GeometryPy
typedef Geometry * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
CirclePy (GeomCircle *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Part::ConicPy
ConicPy (GeomConic *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
Py::Object getLocation (void) const
getter for the Location attribute
void setLocation (Py::Object arg)
setter for the Location attribute
Py::Object getCenter (void) const
getter for the Center attribute
void setCenter (Py::Object arg)
setter for the Center attribute
Py::Float getEccentricity (void) const
getter for the Eccentricity attribute
Py::Float getAngleXU (void) const
getter for the AngleXU attribute
void setAngleXU (Py::Float arg)
setter for the AngleXU attribute
Py::Object getAxis (void) const
getter for the Axis attribute
void setAxis (Py::Object arg)
setter for the Axis attribute
Py::Object getXAxis (void) const
getter for the XAxis attribute
void setXAxis (Py::Object arg)
setter for the XAxis attribute
Py::Object getYAxis (void) const
getter for the YAxis attribute
void setYAxis (Py::Object arg)
setter for the YAxis attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomConic * getGeomConicPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Part::GeometryCurvePy
GeometryCurvePy (GeomCurve *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * toShape (PyObject *args)
implementer for the toShape() method
PyObject * discretize (PyObject *args, PyObject *kwd)
implementer for the discretize() method
PyObject * getD0 (PyObject *args)
implementer for the getD0() method
PyObject * getD1 (PyObject *args)
implementer for the getD1() method
PyObject * getD2 (PyObject *args)
implementer for the getD2() method
PyObject * getD3 (PyObject *args)
implementer for the getD3() method
PyObject * getDN (PyObject *args)
implementer for the getDN() method
PyObject * length (PyObject *args)
implementer for the length() method
PyObject * parameterAtDistance (PyObject *args)
implementer for the parameterAtDistance() method
PyObject * value (PyObject *args)
implementer for the value() method
PyObject * tangent (PyObject *args)
implementer for the tangent() method
PyObject * makeRuledSurface (PyObject *args)
implementer for the makeRuledSurface() method
PyObject * intersect2d (PyObject *args)
implementer for the intersect2d() method
PyObject * continuityWith (PyObject *args)
implementer for the continuityWith() method
PyObject * parameter (PyObject *args)
implementer for the parameter() method
PyObject * normal (PyObject *args)
implementer for the normal() method
PyObject * curvature (PyObject *args)
implementer for the curvature() method
PyObject * centerOfCurvature (PyObject *args)
implementer for the centerOfCurvature() method
PyObject * intersect (PyObject *args)
implementer for the intersect() method
PyObject * intersectCS (PyObject *args)
implementer for the intersectCS() method
PyObject * intersectCC (PyObject *args)
implementer for the intersectCC() method
PyObject * toBSpline (PyObject *args)
implementer for the toBSpline() method
PyObject * toNurbs (PyObject *args)
implementer for the toNurbs() method
PyObject * trim (PyObject *args)
implementer for the trim() method
PyObject * approximateBSpline (PyObject *args)
implementer for the approximateBSpline() method
PyObject * reverse (PyObject *args)
implementer for the reverse() method
PyObject * reversedParameter (PyObject *args)
implementer for the reversedParameter() method
PyObject * isPeriodic (PyObject *args)
implementer for the isPeriodic() method
PyObject * period (PyObject *args)
implementer for the period() method
PyObject * isClosed (PyObject *args)
implementer for the isClosed() method
Py::String getContinuity (void) const
getter for the Continuity attribute
Py::Float getFirstParameter (void) const
getter for the FirstParameter attribute
Py::Float getLastParameter (void) const
getter for the LastParameter attribute
Py::Object getRotation (void) const
getter for the Rotation attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomCurve * getGeomCurvePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Part::GeometryPy
GeometryPy (Geometry *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * clone (PyObject *args)
implementer for the clone() method
PyObject * hasExtensionOfType (PyObject *args)
implementer for the hasExtensionOfType() method
PyObject * hasExtensionOfName (PyObject *args)
implementer for the hasExtensionOfName() method
PyObject * getExtensionOfType (PyObject *args)
implementer for the getExtensionOfType() method
PyObject * getExtensionOfName (PyObject *args)
implementer for the getExtensionOfName() method
PyObject * setExtension (PyObject *args)
implementer for the setExtension() method
PyObject * deleteExtensionOfType (PyObject *args)
implementer for the deleteExtensionOfType() method
PyObject * deleteExtensionOfName (PyObject *args)
implementer for the deleteExtensionOfName() method
PyObject * getExtensions (PyObject *args)
implementer for the getExtensions() method
Py::String getTag (void) const
getter for the Tag attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geometry * getGeometryPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::ConicPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_getLocation (PyObject *self, void *closure)
getter callback for the Location attribute
static int staticCallback_setLocation (PyObject *self, PyObject *value, void *closure)
setter callback for the Location attribute
static PyObject * staticCallback_getCenter (PyObject *self, void *closure)
getter callback for the Center attribute
static int staticCallback_setCenter (PyObject *self, PyObject *value, void *closure)
setter callback for the Center attribute
static PyObject * staticCallback_getEccentricity (PyObject *self, void *closure)
getter callback for the Eccentricity attribute
static int staticCallback_setEccentricity (PyObject *self, PyObject *value, void *closure)
setter callback for the Eccentricity attribute
static PyObject * staticCallback_getAngleXU (PyObject *self, void *closure)
getter callback for the AngleXU attribute
static int staticCallback_setAngleXU (PyObject *self, PyObject *value, void *closure)
setter callback for the AngleXU attribute
static PyObject * staticCallback_getAxis (PyObject *self, void *closure)
getter callback for the Axis attribute
static int staticCallback_setAxis (PyObject *self, PyObject *value, void *closure)
setter callback for the Axis attribute
static PyObject * staticCallback_getXAxis (PyObject *self, void *closure)
getter callback for the XAxis attribute
static int staticCallback_setXAxis (PyObject *self, PyObject *value, void *closure)
setter callback for the XAxis attribute
static PyObject * staticCallback_getYAxis (PyObject *self, void *closure)
getter callback for the YAxis attribute
static int staticCallback_setYAxis (PyObject *self, PyObject *value, void *closure)
setter callback for the YAxis attribute
Static Public Member Functions inherited from Part::GeometryCurvePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_toShape (PyObject *self, PyObject *args)
callback for the toShape() method
static PyObject * staticCallback_discretize (PyObject *self, PyObject *args, PyObject *kwd)
callback for the discretize() method
static PyObject * staticCallback_getD0 (PyObject *self, PyObject *args)
callback for the getD0() method
static PyObject * staticCallback_getD1 (PyObject *self, PyObject *args)
callback for the getD1() method
static PyObject * staticCallback_getD2 (PyObject *self, PyObject *args)
callback for the getD2() method
static PyObject * staticCallback_getD3 (PyObject *self, PyObject *args)
callback for the getD3() method
static PyObject * staticCallback_getDN (PyObject *self, PyObject *args)
callback for the getDN() method
static PyObject * staticCallback_length (PyObject *self, PyObject *args)
callback for the length() method
static PyObject * staticCallback_parameterAtDistance (PyObject *self, PyObject *args)
callback for the parameterAtDistance() method
static PyObject * staticCallback_value (PyObject *self, PyObject *args)
callback for the value() method
static PyObject * staticCallback_tangent (PyObject *self, PyObject *args)
callback for the tangent() method
static PyObject * staticCallback_makeRuledSurface (PyObject *self, PyObject *args)
callback for the makeRuledSurface() method
static PyObject * staticCallback_intersect2d (PyObject *self, PyObject *args)
callback for the intersect2d() method
static PyObject * staticCallback_continuityWith (PyObject *self, PyObject *args)
callback for the continuityWith() method
static PyObject * staticCallback_parameter (PyObject *self, PyObject *args)
callback for the parameter() method
static PyObject * staticCallback_normal (PyObject *self, PyObject *args)
callback for the normal() method
static PyObject * staticCallback_curvature (PyObject *self, PyObject *args)
callback for the curvature() method
static PyObject * staticCallback_centerOfCurvature (PyObject *self, PyObject *args)
callback for the centerOfCurvature() method
static PyObject * staticCallback_intersect (PyObject *self, PyObject *args)
callback for the intersect() method
static PyObject * staticCallback_intersectCS (PyObject *self, PyObject *args)
callback for the intersectCS() method
static PyObject * staticCallback_intersectCC (PyObject *self, PyObject *args)
callback for the intersectCC() method
static PyObject * staticCallback_toBSpline (PyObject *self, PyObject *args)
callback for the toBSpline() method
static PyObject * staticCallback_toNurbs (PyObject *self, PyObject *args)
callback for the toNurbs() method
static PyObject * staticCallback_trim (PyObject *self, PyObject *args)
callback for the trim() method
static PyObject * staticCallback_approximateBSpline (PyObject *self, PyObject *args)
callback for the approximateBSpline() method
static PyObject * staticCallback_reverse (PyObject *self, PyObject *args)
callback for the reverse() method
static PyObject * staticCallback_reversedParameter (PyObject *self, PyObject *args)
callback for the reversedParameter() method
static PyObject * staticCallback_isPeriodic (PyObject *self, PyObject *args)
callback for the isPeriodic() method
static PyObject * staticCallback_period (PyObject *self, PyObject *args)
callback for the period() method
static PyObject * staticCallback_isClosed (PyObject *self, PyObject *args)
callback for the isClosed() method
static PyObject * staticCallback_getContinuity (PyObject *self, void *closure)
getter callback for the Continuity attribute
static int staticCallback_setContinuity (PyObject *self, PyObject *value, void *closure)
setter callback for the Continuity attribute
static PyObject * staticCallback_getFirstParameter (PyObject *self, void *closure)
getter callback for the FirstParameter attribute
static int staticCallback_setFirstParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the FirstParameter attribute
static PyObject * staticCallback_getLastParameter (PyObject *self, void *closure)
getter callback for the LastParameter attribute
static int staticCallback_setLastParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the LastParameter attribute
static PyObject * staticCallback_getRotation (PyObject *self, void *closure)
getter callback for the Rotation attribute
static int staticCallback_setRotation (PyObject *self, PyObject *value, void *closure)
setter callback for the Rotation attribute
Static Public Member Functions inherited from Part::GeometryPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_clone (PyObject *self, PyObject *args)
callback for the clone() method
static PyObject * staticCallback_hasExtensionOfType (PyObject *self, PyObject *args)
callback for the hasExtensionOfType() method
static PyObject * staticCallback_hasExtensionOfName (PyObject *self, PyObject *args)
callback for the hasExtensionOfName() method
static PyObject * staticCallback_getExtensionOfType (PyObject *self, PyObject *args)
callback for the getExtensionOfType() method
static PyObject * staticCallback_getExtensionOfName (PyObject *self, PyObject *args)
callback for the getExtensionOfName() method
static PyObject * staticCallback_setExtension (PyObject *self, PyObject *args)
callback for the setExtension() method
static PyObject * staticCallback_deleteExtensionOfType (PyObject *self, PyObject *args)
callback for the deleteExtensionOfType() method
static PyObject * staticCallback_deleteExtensionOfName (PyObject *self, PyObject *args)
callback for the deleteExtensionOfName() method
static PyObject * staticCallback_getExtensions (PyObject *self, PyObject *args)
callback for the getExtensions() method
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of CirclePy.
static PyMethodDef Methods []
Methods structure of CirclePy.
static PyTypeObject Type
Type structure of CirclePy.
Static Public Attributes inherited from Part::ConicPy
static PyGetSetDef GetterSetter []
Attribute structure of ConicPy.
static PyMethodDef Methods []
Methods structure of ConicPy.
static PyTypeObject Type
Type structure of ConicPy.
Static Public Attributes inherited from Part::GeometryCurvePy
static PyGetSetDef GetterSetter []
Attribute structure of GeometryCurvePy.
static PyMethodDef Methods []
Methods structure of GeometryCurvePy.
static PyTypeObject Type
Type structure of GeometryCurvePy.
Static Public Attributes inherited from Part::GeometryPy
static PyGetSetDef GetterSetter []
Attribute structure of GeometryPy.
static PyMethodDef Methods []
Methods structure of GeometryPy.
static PyTypeObject Type
Type structure of GeometryPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~CirclePy ()
Protected Member Functions inherited from Part::ConicPy
~ConicPy ()
Protected Member Functions inherited from Part::GeometryCurvePy
~GeometryCurvePy ()
Protected Member Functions inherited from Part::GeometryPy
~GeometryPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object attributes
Py::Float getRadius (void) const
getter for the Radius attribute
void setRadius (Py::Float arg)
setter for the Radius attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomCircle * getGeomCirclePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getRadius (PyObject *self, void *closure)
getter callback for the Radius attribute
static int staticCallback_setRadius (PyObject *self, PyObject *value, void *closure)
setter callback for the Radius attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeomCircle.
Member Typedef Documentation
PointerType
typedef GeomCircle* Part::CirclePy::PointerType
Constructor & Destructor Documentation
~CirclePy()
CirclePy::~CirclePy () protected
CirclePy()
CirclePy::CirclePy (GeomCircle * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getCustomAttributes()
PyObject * CirclePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getGeomCirclePtr()
GeomCircle * CirclePy::getGeomCirclePtr (void) const
getter for the object handled by this class
Referenced by getRadius(), PyInit(), Part::CylinderPy::PyInit(), representation(), and setRadius().
getRadius()
Py::Float CirclePy::getRadius (void) const
getter for the Radius attribute
References getGeomCirclePtr().
Referenced by staticCallback_getRadius().
GetType()
virtual PyTypeObject* Part::CirclePy::GetType (void) virtual
Reimplemented from Part::ConicPy.
PyInit()
int CirclePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::ConicPy.
References DraftVecUtils::dist(), getGeomCirclePtr(), Part::PartExceptionOCCError, Base::VectorPy::Type, Type, and Part::GeometryCurvePy::value().
PyMake()
PyObject * CirclePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References CirclePy().
representation()
std::string CirclePy::representation (void) const
References getGeomCirclePtr().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int CirclePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setRadius()
void CirclePy::setRadius (Py::Float arg)
setter for the Radius attribute
References getGeomCirclePtr().
Referenced by staticCallback_setRadius().
staticCallback_getRadius()
PyObject * CirclePy::staticCallback_getRadius (PyObject * self, void * closure) static
getter callback for the Radius attribute
References Base::BaseExceptionFreeCADError, getRadius(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setRadius()
int CirclePy::staticCallback_setRadius (PyObject * self, PyObject * value, void * closure) static
setter callback for the Radius attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setRadius().
Member Data Documentation
GetterSetter
PyGetSetDef CirclePy::GetterSetter static
Initial value:
= {
    {"Radius",
        (getter) staticCallback_getRadius,
        (setter) staticCallback_setRadius,
        "The radius of the circle.",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of CirclePy.
Methods
PyMethodDef CirclePy::Methods static
Initial value:
= {
    {NULL, NULL, 0, NULL}
}
Methods structure of CirclePy.
Type
PyTypeObject CirclePy::Type static
Type structure of CirclePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), Part::ArcOfCirclePy::PyInit(), Part::ArcPy::PyInit(), PyInit(), and Part::CylinderPy::PyInit().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/CirclePy.h
Sources/FreeCAD/src/Mod/Part/App/CirclePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/CirclePy.cpp