FreeCAD: Gui::SoGLVBOActivatedElement Class Reference
Gui::SoGLVBOActivatedElement Class Reference
#include <SoFCInteractiveElement.h>
Public Member Functions
virtual SoElement * copyMatchInfo (void) const
virtual void init (SoState *state)
virtual SbBool matches (const SoElement *element) const
virtual void pop (SoState *state, const SoElement *prevTopElement)
virtual void push (SoState *state)
Static Public Member Functions
static void get (SoState *state, SbBool &active)
static void initClass (void)
static void set (SoState *state, SbBool)
Protected Member Functions
virtual ~SoGLVBOActivatedElement ()
Protected Attributes
SbBool active
Constructor & Destructor Documentation
~SoGLVBOActivatedElement()
SoGLVBOActivatedElement::~SoGLVBOActivatedElement () protected virtual
Member Function Documentation
copyMatchInfo()
SoElement * SoGLVBOActivatedElement::copyMatchInfo (void) const virtual
get()
void SoGLVBOActivatedElement::get (SoState * state, SbBool & active) static
References active.
Referenced by MeshGui::SoFCIndexedFaceSet::GLRender(), PartGui::SoBrepFaceSet::GLRender(), and draftguitools.gui_trackers.editTracker::move().
init()
void SoGLVBOActivatedElement::init (SoState * state) virtual
References active.
Referenced by DocumentObject.DocumentObject::onChanged().
initClass()
void SoGLVBOActivatedElement::initClass (void) static
Referenced by Gui::SoFCDB::init().
matches()
SbBool SoGLVBOActivatedElement::matches (const SoElement * element) const virtual
pop()
void SoGLVBOActivatedElement::pop (SoState * state, const SoElement * prevTopElement) virtual
push()
void SoGLVBOActivatedElement::push (SoState * state) virtual
set()
void SoGLVBOActivatedElement::set (SoState * state, SbBool active) static
References active.
Referenced by draftguitools.gui_trackers.editTracker::move(), and Gui::View3DInventorViewer::renderScene().
Member Data Documentation
active
SbBool Gui::SoGLVBOActivatedElement::active protected
Referenced by draftguitools.gui_shapestrings.ShapeString::action(), draftguitools.gui_texts.Text::action(), get(), init(), and set().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SoFCInteractiveElement.h
Sources/FreeCAD/src/Gui/SoFCInteractiveElement.cpp