FreeCAD: Gui::Dialog::Ui_TextureMapping Class Reference
Gui::Dialog::Ui_TextureMapping Class Reference
#include <ui_TextureMapping.h>
Public Member Functions
void retranslateUi (QDialog *Gui__Dialog__TextureMapping)
void setupUi (QDialog *Gui__Dialog__TextureMapping)
Public Attributes
QCheckBox * checkEnv
QCheckBox * checkGlobal
Gui::FileChooser * fileChooser
QGridLayout * gridLayout
QGridLayout * gridLayout_2
QGroupBox * groupBox
Member Function Documentation
retranslateUi()
void Gui::Dialog::Ui_TextureMapping::retranslateUi (QDialog * Gui__Dialog__TextureMapping)
References checkEnv, checkGlobal, groupBox, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), Gui::Dialog::TextureMapping::changeEvent(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::Dialog::Ui_TextureMapping::setupUi (QDialog * Gui__Dialog__TextureMapping)
References checkEnv, checkGlobal, fileChooser, gridLayout, gridLayout_2, groupBox, and retranslateUi().
Referenced by Gui::Dialog::TextureMapping::TextureMapping().
Member Data Documentation
checkEnv
QCheckBox* Gui::Dialog::Ui_TextureMapping::checkEnv
Referenced by retranslateUi(), and setupUi().
checkGlobal
QCheckBox* Gui::Dialog::Ui_TextureMapping::checkGlobal
Referenced by retranslateUi(), setupUi(), and Gui::Dialog::TextureMapping::TextureMapping().
fileChooser
Gui::FileChooser* Gui::Dialog::Ui_TextureMapping::fileChooser
Referenced by setupUi(), and Gui::Dialog::TextureMapping::TextureMapping().
gridLayout
QGridLayout* Gui::Dialog::Ui_TextureMapping::gridLayout
Referenced by setupUi().
gridLayout_2
QGridLayout* Gui::Dialog::Ui_TextureMapping::gridLayout_2
Referenced by setupUi().
groupBox
QGroupBox* Gui::Dialog::Ui_TextureMapping::groupBox
Referenced by retranslateUi(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_TextureMapping.h