FreeCAD: ClipperLib::Clipper Class Reference
ClipperLib::Clipper Class Reference
#include <clipper.hpp>
Public Member Functions
Clipper (int initOptions=0)
bool Execute (ClipType clipType, Paths &solution, PolyFillType subjFillType=pftEvenOdd, PolyFillType clipFillType=pftEvenOdd)
bool Execute (ClipType clipType, PolyTree &polytree, PolyFillType subjFillType=pftEvenOdd, PolyFillType clipFillType=pftEvenOdd)
bool ReverseSolution ()
void ReverseSolution (bool value)
bool StrictlySimple ()
void StrictlySimple (bool value)
~Clipper ()
Public Member Functions inherited from ClipperLib::ClipperBase
bool AddPath (const Path &pg, PolyType PolyTyp, bool Closed)
bool AddPaths (const Paths &ppg, PolyType PolyTyp, bool Closed)
virtual void Clear ()
ClipperBase ()
IntRect GetBounds ()
bool PreserveCollinear ()
void PreserveCollinear (bool value)
virtual ~ClipperBase ()
Protected Member Functions
virtual bool ExecuteInternal ()
void Reset ()
Protected Member Functions inherited from ClipperLib::ClipperBase
TEdge * AddBoundsToLML (TEdge *e, bool IsClosed)
void AscendToMax (TEdge *&E, bool Appending, bool IsClosed)
TEdge * DescendToMin (TEdge *&E)
void DisposeLocalMinimaList ()
void DoMinimaLML (TEdge *E1, TEdge *E2, bool IsClosed)
void PopLocalMinima ()
TEdge * ProcessBound (TEdge *E, bool IsClockwise)
Additional Inherited Members
Protected Types inherited from ClipperLib::ClipperBase
typedef std::vector< LocalMinimum > MinimaList
Protected Attributes inherited from ClipperLib::ClipperBase
MinimaList::iterator m_CurrentLM
EdgeList m_edges
bool m_HasOpenPaths
MinimaList m_MinimaList
bool m_PreserveCollinear
bool m_UseFullRange
Constructor & Destructor Documentation
Clipper()
ClipperLib::Clipper::Clipper (int initOptions = 0)
References ClipperLib::ctIntersection, ClipperLib::ioPreserveCollinear, ClipperLib::ioReverseSolution, ClipperLib::ioStrictlySimple, ClipperLib::ClipperBase::m_HasOpenPaths, ClipperLib::ClipperBase::m_PreserveCollinear, ClipperLib::ClipperBase::m_UseFullRange, and ClipperLib::pftEvenOdd.
~Clipper()
ClipperLib::Clipper::~Clipper ()
References ClipperLib::ClipperBase::Clear().
Member Function Documentation
Execute() [1/2]
bool ClipperLib::Clipper::Execute (ClipType clipType, Paths & solution, PolyFillType subjFillType = pftEvenOdd, PolyFillType clipFillType = pftEvenOdd)
References ExecuteInternal(), and ClipperLib::ClipperBase::m_HasOpenPaths.
Referenced by PathScripts.PathJobCmd.CommandJobCreate::Activated(), AdaptivePath::Adaptive2d::Execute(), ClipperLib::ClipperOffset::Execute(), and PathScripts.PathJobCmd.CommandJobTemplateExport::SaveDialog().
Execute() [2/2]
bool ClipperLib::Clipper::Execute (ClipType clipType, PolyTree & polytree, PolyFillType subjFillType = pftEvenOdd, PolyFillType clipFillType = pftEvenOdd)
References ExecuteInternal().
Referenced by PathScripts.PathJobCmd.CommandJobCreate::Activated(), and PathScripts.PathJobCmd.CommandJobTemplateExport::SaveDialog().
ExecuteInternal()
bool ClipperLib::Clipper::ExecuteInternal () protected virtual
References ClipperLib::Area(), ClipperLib::OutRec::IsHole, ClipperLib::OutRec::IsOpen, ClipperLib::ClipperBase::m_CurrentLM, ClipperLib::ClipperBase::m_MinimaList, ClipperLib::OutRec::Pts, Reset(), and ClipperLib::ReversePolyPtLinks().
Referenced by Execute().
Reset()
void ClipperLib::Clipper::Reset () protected virtual
Reimplemented from ClipperLib::ClipperBase.
References ClipperLib::ClipperBase::m_MinimaList, and ClipperLib::ClipperBase::Reset().
Referenced by ExecuteInternal().
ReverseSolution() [1/2]
bool ClipperLib::Clipper::ReverseSolution ()
Referenced by ClipperLib::ClipperOffset::Execute().
ReverseSolution() [2/2]
void ClipperLib::Clipper::ReverseSolution (bool value)
StrictlySimple() [1/2]
bool ClipperLib::Clipper::StrictlySimple ()
Referenced by CArea::Clip(), CArea::Intersect(), ClipperLib::SimplifyPolygon(), ClipperLib::SimplifyPolygons(), CArea::Subtract(), CArea::Union(), CArea::UniteCurves(), and CArea::Xor().
StrictlySimple() [2/2]
void ClipperLib::Clipper::StrictlySimple (bool value)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Path/libarea/clipper.hpp
Sources/FreeCAD/src/Mod/Path/libarea/clipper.cpp