FreeCAD: zipios::ZipInputStream Class Reference
zipios::ZipInputStream Class Reference
ZipInputStream is an istream that gets it's input from a zip file.
#include <zipinputstream.h>
Public Member Functions
int available ()
void close ()
Closes the istream.
void closeEntry ()
Closes the current entry, and positions the stream read pointer at the beginning of the next entry (if there is one).
ConstEntryPointer getNextEntry ()
Opens the next entry in the zip archive and returns a const pointer to a FileEntry object for the entry.
ZipInputStream (const std::string &filename, std::streampos pos=0)
ZipInputStream constructor.
ZipInputStream (std::istream &is, std::streampos pos=0)
ZipInputStream constructor.
virtual ~ZipInputStream ()
Destructor.
Detailed Description
ZipInputStream is an istream that gets it's input from a zip file.
The interface approximates the interface of the Java ZipInputStream.
Constructor & Destructor Documentation
ZipInputStream() [1/2]
zipios::ZipInputStream::ZipInputStream (std::istream & is, std::streampos pos = 0) explicit
ZipInputStream constructor.
Parameters
is istream from which the compressed zip archive can be read.
pos position to reposition the istream to before reading.
ZipInputStream() [2/2]
zipios::ZipInputStream::ZipInputStream (const std::string & filename, std::streampos pos = 0) explicit
ZipInputStream constructor.
Parameters
filename filename of a valid zip file.
pos position to reposition the istream to before reading.
References Base::FileInfo::toStdWString().
~ZipInputStream()
zipios::ZipInputStream::~ZipInputStream () virtual
Destructor.
Member Function Documentation
available()
int zipios::ZipInputStream::available ()
close()
void zipios::ZipInputStream::close ()
Closes the istream.
References zipios::ZipInputStreambuf::close().
Referenced by femexamples.examplesgui.FemExamples::reject().
closeEntry()
void zipios::ZipInputStream::closeEntry ()
Closes the current entry, and positions the stream read pointer at the beginning of the next entry (if there is one).
References zipios::ZipInputStreambuf::closeEntry().
getNextEntry()
ConstEntryPointer zipios::ZipInputStream::getNextEntry ()
Opens the next entry in the zip archive and returns a const pointer to a FileEntry object for the entry.
Returns
a const FileEntry * containing information about the (now) current entry.
References zipios::ZipInputStreambuf::getNextEntry().
Referenced by Base::XMLReader::readFiles().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/zipios++/zipinputstream.h
Sources/FreeCAD/src/zipios++/zipinputstream.cpp