FreeCAD: Gui::ViewProviderOriginGroupExtension Class Reference
Gui::ViewProviderOriginGroupExtension Class Reference
#include <ViewProviderOriginGroupExtension.h>
Public Member Functions
virtual void extensionAttach (App::DocumentObject *pcObject) override
virtual std::vector< App::DocumentObject * > extensionClaimChildren (void) const override
virtual std::vector< App::DocumentObject * > extensionClaimChildren3D (void) const override
virtual void extensionUpdateData (const App::Property *prop) override
void updateOriginSize ()
ViewProviderOriginGroupExtension (void)
Constructor.
virtual ~ViewProviderOriginGroupExtension ()
Public Member Functions inherited from Gui::ViewProviderGeoFeatureGroupExtension
virtual void extensionAttach (App::DocumentObject *pcObject) override
virtual std::vector< App::DocumentObject * > extensionClaimChildren (void) const override
virtual std::vector< App::DocumentObject * > extensionClaimChildren3D (void) const override
virtual void extensionFinishRestoring () override
virtual SoSeparator * extensionGetBackRoot () const override
virtual SoGroup * extensionGetChildRoot (void) const override
virtual std::vector< std::string > extensionGetDisplayModes (void) const override
virtual SoSeparator * extensionGetFrontRoot () const override
virtual void extensionHide (void) override
Hide the object in the view: suppresses behavior of DocumentObjectGroup.
virtual void extensionSetDisplayMode (const char *ModeName) override
virtual void extensionShow (void) override
Show the object in the view: suppresses behavior of DocumentObjectGroup.
virtual void extensionUpdateData (const App::Property *) override
ViewProviderGeoFeatureGroupExtension (void)
Constructor.
virtual ~ViewProviderGeoFeatureGroupExtension ()
Public Member Functions inherited from Gui::ViewProviderGroupExtension
virtual bool extensionCanDragObject (App::DocumentObject *) const override
virtual bool extensionCanDragObjects () const override
virtual bool extensionCanDropObject (App::DocumentObject *) const override
virtual bool extensionCanDropObjects () const override
virtual std::vector< App::DocumentObject * > extensionClaimChildren (void) const override
virtual void extensionDragObject (App::DocumentObject *) override
virtual void extensionDropObject (App::DocumentObject *) override
virtual void extensionHide (void) override
Hides the view provider.
virtual bool extensionOnDelete (const std::vector< std::string > &) override
virtual void extensionShow (void) override
Shows the view provider.
ViewProviderGroupExtension (void)
Constructor.
virtual ~ViewProviderGroupExtension ()
Public Member Functions inherited from Gui::ViewProviderExtension
virtual void extensionAttach (App::DocumentObject *)
virtual void extensionBeforeDelete ()
virtual bool extensionCanDragAndDropObject (App::DocumentObject *) const
virtual bool extensionCanDragObject (App::DocumentObject *) const
virtual bool extensionCanDragObjects () const
virtual bool extensionCanDropObject (App::DocumentObject *) const
virtual bool extensionCanDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const
virtual bool extensionCanDropObjects () const
virtual std::vector< App::DocumentObject * > extensionClaimChildren (void) const
virtual std::vector< App::DocumentObject * > extensionClaimChildren3D (void) const
virtual void extensionDragObject (App::DocumentObject *)
virtual void extensionDropObject (App::DocumentObject *)
virtual std::string extensionDropObjectEx (App::DocumentObject *obj, App::DocumentObject *, const char *, const std::vector< std::string > &)
virtual void extensionFinishRestoring ()
virtual SoSeparator * extensionGetBackRoot (void) const
virtual SoGroup * extensionGetChildRoot (void) const
virtual bool extensionGetDetailPath (const char *, SoFullPath *, SoDetail *&) const
virtual std::vector< std::string > extensionGetDisplayModes (void) const
virtual bool extensionGetElementPicked (const SoPickedPoint *, std::string &) const
virtual SoSeparator * extensionGetFrontRoot (void) const
virtual void extensionHide (void)
Hides the view provider.
virtual QIcon extensionMergeColorfullOverlayIcons (const QIcon &orig) const
virtual QIcon extensionMergeGreyableOverlayIcons (const QIcon &orig) const
virtual void extensionModeSwitchChange (void)
virtual bool extensionOnDelete (const std::vector< std::string > &)
virtual void extensionReattach (App::DocumentObject *)
virtual int extensionReplaceObject (App::DocumentObject *, App::DocumentObject *)
virtual void extensionSetDisplayMode (const char *)
virtual void extensionSetupContextMenu (QMenu *, QObject *, const char *)
virtual void extensionShow (void)
Shows the view provider.
virtual void extensionStartRestoring ()
virtual void extensionUpdateData (const App::Property *)
Gui::ViewProviderDocumentObject * getExtendedViewProvider ()
const Gui::ViewProviderDocumentObject * getExtendedViewProvider () const
virtual PyObject * getExtensionPyObject ()
bool ignoreOverlayIcon () const
void setIgnoreOverlayIcon (bool on)
ViewProviderExtension ()
virtual ~ViewProviderExtension ()
Public Member Functions inherited from App::Extension
Extension ()
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
virtual PyObject * getExtensionPyObject ()
virtual void initExtension (App::ExtensionContainer *obj)
bool isPythonExtension ()
std::string name () const
virtual ~Extension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Protected Member Functions
void slotChangedObjectApp (const App::DocumentObject &obj)
void slotChangedObjectGui (const Gui::ViewProviderDocumentObject &obj)
Protected Member Functions inherited from App::Extension
virtual void extensionOnChanged (const Property *p)
void initExtensionType (Base::Type type)
Additional Inherited Members
Static Protected Member Functions inherited from App::Extension
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::ViewProviderGeoFeatureGroupExtension
SoSeparator * pcGroupBack
SoGroup * pcGroupChildren
SoSeparator * pcGroupFront
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Constructor & Destructor Documentation
ViewProviderOriginGroupExtension()
ViewProviderOriginGroupExtension::ViewProviderOriginGroupExtension (void)
Constructor.
~ViewProviderOriginGroupExtension()
ViewProviderOriginGroupExtension::~ViewProviderOriginGroupExtension () virtual
Member Function Documentation
extensionAttach()
void ViewProviderOriginGroupExtension::extensionAttach (App::DocumentObject * pcObject) override virtual
Reimplemented from Gui::ViewProviderGeoFeatureGroupExtension.
References draftgeoutils.faces::bind(), Gui::ViewProviderGeoFeatureGroupExtension::extensionAttach(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::Application::Instance, App::Document::signalChangedObject, Gui::Document::signalChangedObject, slotChangedObjectApp(), and slotChangedObjectGui().
extensionClaimChildren()
std::vector< App::DocumentObject * > ViewProviderOriginGroupExtension::extensionClaimChildren (void) const override virtual
Reimplemented from Gui::ViewProviderGeoFeatureGroupExtension.
References Gui::ViewProviderGeoFeatureGroupExtension::extensionClaimChildren().
extensionClaimChildren3D()
std::vector< App::DocumentObject * > ViewProviderOriginGroupExtension::extensionClaimChildren3D (void) const override virtual
Reimplemented from Gui::ViewProviderGeoFeatureGroupExtension.
References Gui::ViewProviderGeoFeatureGroupExtension::extensionClaimChildren3D().
extensionUpdateData()
void ViewProviderOriginGroupExtension::extensionUpdateData (const App::Property * prop) override virtual
Reimplemented from Gui::ViewProviderGeoFeatureGroupExtension.
References Gui::ViewProviderGeoFeatureGroupExtension::extensionUpdateData(), Gui::ViewProviderExtension::getExtendedViewProvider(), App::ExtensionContainer::getExtensionByType(), Gui::ViewProviderDocumentObject::getObject(), and updateOriginSize().
slotChangedObjectApp()
void ViewProviderOriginGroupExtension::slotChangedObjectApp (const App::DocumentObject & obj) protected
References Gui::ViewProviderExtension::getExtendedViewProvider(), App::ExtensionContainer::getExtensionByType(), Gui::ViewProviderDocumentObject::getObject(), and updateOriginSize().
Referenced by extensionAttach().
slotChangedObjectGui()
void ViewProviderOriginGroupExtension::slotChangedObjectGui (const Gui::ViewProviderDocumentObject & obj) protected
References Base::Persistence::getClassTypeId(), Gui::ViewProviderExtension::getExtendedViewProvider(), App::ExtensionContainer::getExtensionByType(), Gui::ViewProviderDocumentObject::getObject(), Base::BaseClass::isDerivedFrom(), and updateOriginSize().
Referenced by extensionAttach().
updateOriginSize()
void ViewProviderOriginGroupExtension::updateOriginSize ()
References Base::Console(), Gui::ViewProviderOrigin::defaultSize(), Base::ConsoleSingleton::Error(), Base::Persistence::getClassTypeId(), Gui::ViewProviderDocumentObject::getDocument(), Gui::ViewProviderExtension::getExtendedViewProvider(), App::ExtensionContainer::getExtensionByType(), Gui::ViewProviderDocumentObject::getObject(), Gui::ViewProvider::getRoot(), Gui::Document::getViewOfViewProvider(), Gui::Application::getViewProvider(), Gui::Application::Instance, Base::BaseClass::isDerivedFrom(), App::Document::Restoring, App::PropertyVector::setValue(), Gui::ViewProviderOrigin::Size, OfflineRenderingUtils::viewer(), and Base::Exception::what().
Referenced by extensionUpdateData(), slotChangedObjectApp(), and slotChangedObjectGui().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/ViewProviderOriginGroupExtension.h
FreeCAD/src/Gui/ViewProviderOriginGroupExtension.cpp