FreeCAD: TechDraw::PATLineSpec Class Reference
TechDraw::PATLineSpec Class Reference
PATLineSpec is the result of parsing a singleline from PAT file into accessible parameters.
#include <HatchLine.h>
Public Member Functions
void dump (const char *title)
double getAngle (void)
DashSpec getDashParms (void)
double getInterval (void)
double getIntervalX (void)
X component of distance between lines.
double getIntervalY (void)
Y component of distance between lines.
double getLength (void)
double getOffset (void)
Base::Vector3d getOrigin (void)
double getSlope (void)
bool isDashed (void)
void load (std::string &lineSpec)
PATLineSpec ()
PATLineSpec (std::string &lineSpec)
~PATLineSpec ()
Static Public Member Functions
static bool findPatternStart (std::ifstream &inFile, std::string &parmName)
static std::vector< std::string > getPatternList (std::string &parmFile)
static std::vector< PATLineSpec > getSpecsForPattern (std::string &parmFile, std::string &parmName)
static std::vector< std::string > loadPatternDef (std::ifstream &inFile)
Detailed Description
PATLineSpec is the result of parsing a singleline from PAT file into accessible parameters.
Constructor & Destructor Documentation
PATLineSpec() [1/2]
PATLineSpec::PATLineSpec ()
PATLineSpec() [2/2]
PATLineSpec::PATLineSpec (std::string & lineSpec)
References load().
~PATLineSpec()
PATLineSpec::~PATLineSpec ()
Member Function Documentation
dump()
void PATLineSpec::dump (const char * title)
References Base::Console(), TechDraw::DashSpec::dump(), TechDraw::DrawUtil::formatVector(), and Base::ConsoleSingleton::Message().
findPatternStart()
bool PATLineSpec::findPatternStart (std::ifstream & inFile, std::string & parmName) static
Referenced by getSpecsForPattern().
getAngle()
double TechDraw::PATLineSpec::getAngle (void)
Referenced by TechDraw::LineSet::calcApparentStart(), getIntervalX(), getIntervalY(), getSlope(), and TechDraw::DrawGeomHatch::makeEdgeOverlay().
getDashParms()
DashSpec TechDraw::PATLineSpec::getDashParms (void)
getInterval()
double TechDraw::PATLineSpec::getInterval (void)
Referenced by getIntervalX(), getIntervalY(), and TechDraw::DrawGeomHatch::makeEdgeOverlay().
getIntervalX()
double PATLineSpec::getIntervalX (void)
X component of distance between lines.
References getAngle(), and getInterval().
Referenced by TechDraw::DrawGeomHatch::makeEdgeOverlay().
getIntervalY()
double PATLineSpec::getIntervalY (void)
Y component of distance between lines.
References getAngle(), and getInterval().
getLength()
double TechDraw::PATLineSpec::getLength (void)
getOffset()
double TechDraw::PATLineSpec::getOffset (void)
getOrigin()
Base::Vector3d TechDraw::PATLineSpec::getOrigin (void)
Referenced by TechDraw::DrawGeomHatch::makeEdgeOverlay().
getPatternList()
std::vector< std::string > PATLineSpec::getPatternList (std::string & parmFile) static
References Base::Console(), and Base::ConsoleSingleton::Message().
getSlope()
double PATLineSpec::getSlope (void)
References DraftVecUtils::angle(), and getAngle().
Referenced by TechDraw::LineSet::calcApparentStart(), and TechDraw::DrawGeomHatch::makeEdgeOverlay().
getSpecsForPattern()
std::vector< PATLineSpec > PATLineSpec::getSpecsForPattern (std::string & parmFile, std::string & parmName) static
References Base::Console(), findPatternStart(), loadPatternDef(), and Base::ConsoleSingleton::Message().
Referenced by TechDraw::DrawGeomHatch::getDecodedSpecsFromFile().
isDashed()
bool PATLineSpec::isDashed (void)
References TechDraw::DashSpec::empty().
Referenced by TechDraw::LineSet::isDashed().
load()
void PATLineSpec::load (std::string & lineSpec)
References Base::Console(), and Base::ConsoleSingleton::Message().
Referenced by PATLineSpec().
loadPatternDef()
std::vector< std::string > PATLineSpec::loadPatternDef (std::ifstream & inFile) static
Referenced by getSpecsForPattern().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/App/HatchLine.h
Sources/FreeCAD/src/Mod/TechDraw/App/HatchLine.cpp