FreeCAD: GCS::SubSystem Class Reference
GCS::SubSystem Class Reference
#include <SubSystem.h>
Public Member Functions
void analyse (Eigen::MatrixXd &J, Eigen::MatrixXd &ker, Eigen::MatrixXd &img)
void applySolution ()
void calcGrad (Eigen::VectorXd &grad)
void calcGrad (VEC_pD &params, Eigen::VectorXd &grad)
void calcJacobi (Eigen::MatrixXd &jacobi)
void calcJacobi (VEC_pD &params, Eigen::MatrixXd &jacobi)
void calcResidual (Eigen::VectorXd &r)
void calcResidual (Eigen::VectorXd &r, double &err)
int cSize ()
double error ()
void getConstraintList (std::vector< Constraint * > &clist_)
void getParamList (VEC_pD &plistOut)
void getParamMap (MAP_pD_pD &pmapOut)
void getParams (Eigen::VectorXd &xOut)
void getParams (VEC_pD &params, Eigen::VectorXd &xOut)
double maxStep (Eigen::VectorXd &xdir)
double maxStep (VEC_pD &params, Eigen::VectorXd &xdir)
void printResidual ()
int pSize ()
void redirectParams ()
void report ()
void revertParams ()
void setParams (Eigen::VectorXd &xIn)
void setParams (VEC_pD &params, Eigen::VectorXd &xIn)
SubSystem (std::vector< Constraint * > &clist_, VEC_pD &params)
SubSystem (std::vector< Constraint * > &clist_, VEC_pD &params, MAP_pD_pD &reductionmap)
~SubSystem ()
Constructor & Destructor Documentation
SubSystem() [1/2]
GCS::SubSystem::SubSystem (std::vector< Constraint * > & clist_, VEC_pD & params)
SubSystem() [2/2]
GCS::SubSystem::SubSystem (std::vector< Constraint * > & clist_, VEC_pD & params, MAP_pD_pD & reductionmap)
~SubSystem()
GCS::SubSystem::~SubSystem ()
Member Function Documentation
analyse()
void GCS::SubSystem::analyse (Eigen::MatrixXd & J, Eigen::MatrixXd & ker, Eigen::MatrixXd & img)
applySolution()
void GCS::SubSystem::applySolution ()
calcGrad() [1/2]
void GCS::SubSystem::calcGrad (Eigen::VectorXd & grad)
References calcGrad().
calcGrad() [2/2]
void GCS::SubSystem::calcGrad (VEC_pD & params, Eigen::VectorXd & grad)
Referenced by calcGrad(), and GCS::System::solve().
calcJacobi() [1/2]
void GCS::SubSystem::calcJacobi (Eigen::MatrixXd & jacobi)
References calcJacobi().
calcJacobi() [2/2]
void GCS::SubSystem::calcJacobi (VEC_pD & params, Eigen::MatrixXd & jacobi)
Referenced by calcJacobi(), and GCS::System::solve().
calcResidual() [1/2]
void GCS::SubSystem::calcResidual (Eigen::VectorXd & r)
Referenced by GCS::System::solve().
calcResidual() [2/2]
void GCS::SubSystem::calcResidual (Eigen::VectorXd & r, double & err)
cSize()
int GCS::SubSystem::cSize ()
Referenced by GCS::System::solve().
error()
double GCS::SubSystem::error ()
Referenced by GCS::lineSearch(), femmesh.gmshtools.GmshTools::read_and_set_new_mesh(), FreeCADInit.FCADLogger::report(), femmesh.gmshtools.GmshTools::run_gmsh_with_geo(), and GCS::System::solve().
getConstraintList()
void GCS::SubSystem::getConstraintList (std::vector< Constraint * > & clist_)
getParamList()
void GCS::SubSystem::getParamList (VEC_pD & plistOut)
Referenced by GCS::System::solve().
getParamMap()
void GCS::SubSystem::getParamMap (MAP_pD_pD & pmapOut)
getParams() [1/2]
void GCS::SubSystem::getParams (Eigen::VectorXd & xOut)
getParams() [2/2]
void GCS::SubSystem::getParams (VEC_pD & params, Eigen::VectorXd & xOut)
Referenced by GCS::lineSearch(), and GCS::System::solve().
maxStep() [1/2]
double GCS::SubSystem::maxStep (Eigen::VectorXd & xdir)
References maxStep().
maxStep() [2/2]
double GCS::SubSystem::maxStep (VEC_pD & params, Eigen::VectorXd & xdir)
Referenced by GCS::lineSearch(), maxStep(), and GCS::System::solve().
printResidual()
void GCS::SubSystem::printResidual ()
pSize()
int GCS::SubSystem::pSize ()
Referenced by GCS::System::solve().
redirectParams()
void GCS::SubSystem::redirectParams ()
Referenced by GCS::System::solve().
report()
void GCS::SubSystem::report ()
Referenced by femsolver.run.Check::check_geos_beamsection_and_shellthickness(), femsolver.run.Check::check_geos_beamsection_no(), femsolver.run.Check::check_geos_beamsection_single(), femsolver.run.Check::check_geos_shellthickness_no(), femsolver.run.Check::check_geos_shellthickness_single(), femsolver.run.Check::check_material_exists(), femsolver.run.Check::check_material_single(), femsolver.run.Check::check_mesh_exists(), femsolver.elmer.tasks.Check::checkEquations(), femsolver.elmer.tasks.Prepare::checkHandled(), femsolver.elmer.tasks.Check::checkMeshType(), femsolver.run.Check::checkSupported(), femsolver.calculix.tasks.Check::run(), femsolver.elmer.tasks.Prepare::run(), femsolver.elmer.tasks.Solve::run(), femsolver.elmer.tasks.Results::run(), femsolver.run.Machine::run(), and femsolver.task.Task::start().
revertParams()
void GCS::SubSystem::revertParams ()
Referenced by GCS::System::solve().
setParams() [1/2]
void GCS::SubSystem::setParams (Eigen::VectorXd & xIn)
setParams() [2/2]
void GCS::SubSystem::setParams (VEC_pD & params, Eigen::VectorXd & xIn)
Referenced by GCS::lineSearch(), and GCS::System::solve().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/App/planegcs/SubSystem.h
FreeCAD/src/Mod/Sketcher/App/planegcs/SubSystem.cpp