FreeCAD: Gui::PreferencePack Class Reference
Gui::PreferencePack Class Reference
of user preferences stored in files on disk
#include <PreferencePackManager.h>
Public Member Functions
bool apply () const
Apply the PreferencePack over the top of the current preferences set.
App::Metadata metadata () const
Get the complete metadata object for this preference pack.
std::string name () const
Get the name of the PreferencePack.
PreferencePack (const boost::filesystem::path &path, const App::Metadata &metadata)
Construct a preferencePack from a directory.
~PreferencePack ()=default
Detailed Description
of user preferences stored in files on disk
Constructor & Destructor Documentation
PreferencePack()
PreferencePack::PreferencePack (const boost::filesystem::path & path, const App::Metadata & metadata)
Construct a preferencePack from a directory.
Parameters
path A path to a mod directory that contains a preferencePack
metadata The metadata from the package.xml file describing this preferencePack
~PreferencePack()
Gui::PreferencePack::~PreferencePack () default
Member Function Documentation
apply()
bool PreferencePack::apply () const
Apply the PreferencePack over the top of the current preferences set.
Returns
True if the preferencePack was applied, or false if not
References Base::Console(), App::GetApplication(), App::Application::getUserAppDataDir(), App::Application::GetUserParameter(), Base::Interpreter(), ParameterManager::LoadDocument(), Base::ConsoleSingleton::Message(), Base::InterpreterSingleton::runFile(), and ParameterManager::SaveDocument().
metadata()
App::Metadata Gui::PreferencePack::metadata () const
Get the complete metadata object for this preference pack.
Referenced by Addon.Addon::contains_macro(), Addon.Addon::contains_preference_pack(), Addon.Addon::contains_workbench(), Addon.Addon::get_cached_icon_filename(), and Addon.Addon::set_metadata().
name()
std::string PreferencePack::name () const
Get the name of the PreferencePack.
Referenced by draftguitools.gui_groups.Ui_AddNamedGroup::accept(), prototype.Node::addtofreecad(), Addon.Addon::disable(), Addon.Addon::enable(), addonmanager_macro.Macro::filename(), gzip_utf8.GzipFile::filename(), addonmanager_macro.Macro::fill_details_from_code(), addonmanager_macro.Macro::fill_details_from_wiki(), Addon.Addon::get_cached_icon_filename(), ifc4.ifcapproval::hasidentifierorname(), addonmanager_macro.Macro::install(), Addon.Addon::is_disabled(), femsolver.elmer.sifio.Section::keys(), automotive_design.si_unit::named_unit_dimensions(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::output(), prototype.Node::pprint(), prototype.Node::pprint2(), PathScripts.PathSetupSheetGui.OpTaskPanel::propertyGroup(), PathScripts.PathSetupSheetGui.OpTaskPanel::propertyName(), PathScripts.PathJobGui.TaskPanel::reject(), addonmanager_macro.Macro::remove(), Addon.Addon::to_cache(), ifc2x3.ifcexternalreference::wr1(), ifc2x3.ifcdocumentreference::wr1(), ifc4.ifcexternalreference::wr1(), ifc4.ifcdocumentreference::wr1(), and automotive_design.general_property_association::wr2().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/PreferencePackManager.h
FreeCAD/src/Gui/PreferencePackManager.cpp