FreeCAD: PendingLine Class Reference
PendingLine Class Reference
Public Member Functions
void cancel ()
PendingLine (MacroManager::LineType type, const char *line)
~PendingLine ()
Constructor & Destructor Documentation
PendingLine()
PendingLine::PendingLine (MacroManager::LineType type, const char * line)
References Gui::MacroManager::addLine(), Gui::Application::Instance, and Gui::Application::macroManager().
~PendingLine()
PendingLine::~PendingLine ()
Member Function Documentation
cancel()
void PendingLine::cancel ()
References Gui::MacroManager::addLine(), Gui::MacroManager::Cmt, Gui::Application::Instance, and Gui::Application::macroManager().
Referenced by DraftGui.DraftToolBar::finish(), Gui::Command::invoke(), DraftGui.DraftToolBar::offUi(), and DraftGui.DraftToolBar::pointUi().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/Command.cpp