FreeCAD: Gui::SelectionLogDisabler Class Reference
Gui::SelectionLogDisabler Class Reference
Helper class to disable logging selection action to MacroManager.
#include <Selection.h>
Public Member Functions
SelectionLogDisabler (bool silent=false)
~SelectionLogDisabler ()
Detailed Description
Helper class to disable logging selection action to MacroManager.
Constructor & Destructor Documentation
SelectionLogDisabler()
Gui::SelectionLogDisabler::SelectionLogDisabler (bool silent = false)
References Gui::SelectionSingleton::disableCommandLog(), and Gui::Selection().
~SelectionLogDisabler()
Gui::SelectionLogDisabler::~SelectionLogDisabler ()
References Gui::SelectionSingleton::enableCommandLog(), and Gui::Selection().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/Selection.h