FreeCAD: PartDesignGui::ReferenceSelection Class Reference
PartDesignGui::ReferenceSelection Class Reference
#include <ReferenceSelection.h>
Public Member Functions
bool allow (App::Document *pDoc, App::DocumentObject *pObj, const char *sSubName)
Allow the user to pick only edges or faces (or both) from the defined support Optionally restrict the selection to planar edges/faces.
ReferenceSelection (const App::DocumentObject *support_, const bool edge_, const bool plane_, const bool planar_, const bool point_=false, bool whole_=false)
Public Member Functions inherited from Gui::SelectionFilterGate
SelectionFilterGate (const char *filter)
construct with the filter string
SelectionFilterGate (SelectionFilter *filter)
~SelectionFilterGate ()
Public Member Functions inherited from Gui::SelectionGate
virtual ~SelectionGate ()
Additional Inherited Members
Public Attributes inherited from Gui::SelectionGate
std::string notAllowedReason
notAllowedReason is a string that sets the message to be displayed in statusbar for cluing the user on why is the selection not allowed.
Protected Member Functions inherited from Gui::SelectionFilterGate
SelectionFilterGate ()
Protected Attributes inherited from Gui::SelectionFilterGate
SelectionFilter * Filter
Constructor & Destructor Documentation
ReferenceSelection()
PartDesignGui::ReferenceSelection::ReferenceSelection (const App::DocumentObject * support_, const bool edge_, const bool plane_, const bool planar_, const bool point_ = false, bool whole_ = false)
Member Function Documentation
allow()
bool ReferenceSelection::allow (App::Document * pDoc, App::DocumentObject * pObj, const char * sSubName) virtual
Allow the user to pick only edges or faces (or both) from the defined support Optionally restrict the selection to planar edges/faces.
Reimplemented from Gui::SelectionFilterGate.
References PartDesign::Body::findBodyOf(), PartDesignGui::getActivePart(), PartDesignGui::getBody(), Base::Persistence::getClassTypeId(), App::ExtensionContainer::getExtensionByType(), App::OriginGroupExtension::getGroupOfObject(), App::OriginGroupExtension::getOrigin(), Base::Persistence::getTypeId(), App::Origin::hasObject(), App::OriginGroupExtension::hasObject(), and Base::Type::isDerivedFrom().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/PartDesign/Gui/ReferenceSelection.h
Sources/FreeCAD/src/Mod/PartDesign/Gui/ReferenceSelection.cpp