FreeCAD: MED::TTGrilleInfo< eVersion > Struct Template Reference
MED::TTGrilleInfo< eVersion > Struct Template Reference
#include <MED_TStructures.hxx>
Public Member Functions
virtual std::string GetCoordName (TInt theId) const
Get name of the coordinate dimension by its order number.
virtual std::string GetCoordUnit (TInt theId) const
Get name of unit for the coordinate dimension by its order number.
virtual void SetCoordName (TInt theId, const std::string &theValue)
Set name of the coordinate dimension by its order number.
virtual void SetCoordUnit (TInt theId, const std::string &theValue)
Set name of unit for the coordinate dimension by its order number.
TTGrilleInfo (const PMeshInfo &theMeshInfo, const EGrilleType &type)
TTGrilleInfo (const PMeshInfo &theMeshInfo, const EGrilleType &type, const MED::TIntVector &nbNodeVec)
TTGrilleInfo (const PMeshInfo &theMeshInfo, const EGrilleType &type, const TInt nnoeuds)
TTGrilleInfo (const PMeshInfo &theMeshInfo, const PGrilleInfo &theInfo)
Public Member Functions inherited from MED::TGrilleInfo
TIntVector GetConn (TInt theId, const bool isSub=false)
Gives ids of nodes for mesh cell or sub-cell by its number, array index from 0.
TNodeCoord GetCoord (TInt theId)
Gives coordinates for mesh node by its number, array index from 0.
EEntiteMaillage GetEntity ()
Return geometry of subcells (calculated from mesh dimension)
TInt GetFamNum (TInt theId) const
Get number of a MED FAMILY by order number of the mesh element.
TInt GetFamNumNode (TInt theId) const
Get number of a MED FAMILY by order number of the mesh node.
TInt GetFamSubNum (TInt theId) const
Get number of a MED FAMILY by order number of sub element.
EGeometrieElement GetGeom ()
Return count of all entities of <mesh dimension-1>
TIntVector GetGrilleStructure ()
Gets grille structure.
const TIntVector & GetGrilleStructure () const
Gets grille structure(const version)
EGrilleType GetGrilleType ()
Gets grille type.
const EGrilleType & GetGrilleType () const
Gets grille type (const version)
TFloatVector & GetIndexes (TInt theAxisNumber)
Gets a Table of indexes for certain axe.
const TFloatVector & GetIndexes (TInt theAxisNumber) const
Gets a Table of indexes for certain axe(const version)
TIndexes & GetMapOfIndexes ()
Gets a map of Tables.
const TIndexes & GetMapOfIndexes () const
Gets a map of Tables (const version)
const PMeshInfo & GetMeshInfo () const
TInt GetNbCells ()
Return count of all points.
TInt GetNbIndexes (TInt theAxisNumber)
Gets a number of indices per axe.
TInt GetNbNodes ()
TInt GetNbSubCells ()
Return count of all cells.
TNodeCoord & GetNodeCoord ()
const TNodeCoord & GetNodeCoord () const
Gives coordinates for mesh nodes (const version)
EEntiteMaillage GetSubEntity ()
Return entity (eMAILLE)
EGeometrieElement GetSubGeom ()
Return geometry of cells (calculated from mesh dimension)
void SetFamNum (TInt theId, TInt theVal)
Set number of a MED FAMILY for the mesh element with the order number.
void SetFamNumNode (TInt theId, TInt theVal)
Set number of a MED FAMILY for the mesh node with the order number.
void SetFamSubNum (TInt theId, TInt theVal)
Set number of a MED FAMILY for theId-th sub element.
void SetGrilleStructure (TInt theAxis, TInt theNb)
Sets the grille structure of theAxis axe to theNb.
void SetGrilleType (EGrilleType theGrilleType)
Sets grille type.
Public Member Functions inherited from MED::TModeSwitchInfo
EModeSwitch GetModeSwitch () const
TModeSwitchInfo ()
To construct instance of the class by default.
TModeSwitchInfo (EModeSwitch theModeSwitch)
To construct instance of the class.
Public Member Functions inherited from MED::TBase
virtual ~TBase ()
Additional Inherited Members
Public Attributes inherited from MED::TGrilleInfo
TNodeCoord myCoord
Contains all nodal coordinates, now used only for eGRILLE_STANDARD.
TString myCoordNames
Contains names for the coordinate dimensions.
TString myCoordUnits
Contains units for the coordinate dimensions.
TElemNum myFamNum
TElemNum myFamNumNode
TElemNum myFamSubNum
TIntVector myGrilleStructure
Return sub entity.
EGrilleType myGrilleType
Defines grille type (eGRILLE_CARTESIENNE,eGRILLE_POLAIRE,eGRILLE_STANDARD)
TIndexes myIndixes
Map of index of axes and Table of indexes for certain axe, now used for eGRILLE_CARTESIENNE and eGRILLE_POLAIRE.
PMeshInfo myMeshInfo
Public Attributes inherited from MED::TModeSwitchInfo
EModeSwitch myModeSwitch
Keeps the.
Constructor & Destructor Documentation
TTGrilleInfo() [1/4]
template<EVersion eVersion> MED::TTGrilleInfo< eVersion >::TTGrilleInfo (const PMeshInfo & theMeshInfo, const PGrilleInfo & theInfo)
References MED::TGrilleInfo::myCoord, MED::TGrilleInfo::myCoordNames, MED::TGrilleInfo::myCoordUnits, MED::TGrilleInfo::myFamNum, MED::TGrilleInfo::myFamNumNode, MED::TGrilleInfo::myGrilleStructure, MED::TGrilleInfo::myGrilleType, MED::TGrilleInfo::myIndixes, and MED::TGrilleInfo::myMeshInfo.
TTGrilleInfo() [2/4]
template<EVersion eVersion> MED::TTGrilleInfo< eVersion >::TTGrilleInfo (const PMeshInfo & theMeshInfo, const EGrilleType & type, const TInt nnoeuds)
References MED::eGRILLE_STANDARD, MED::TGrilleInfo::myCoord, MED::TGrilleInfo::myCoordNames, MED::TGrilleInfo::myCoordUnits, MED::TGrilleInfo::myFamNumNode, MED::TGrilleInfo::myGrilleStructure, and MED::TGrilleInfo::myMeshInfo.
TTGrilleInfo() [3/4]
template<EVersion eVersion> MED::TTGrilleInfo< eVersion >::TTGrilleInfo (const PMeshInfo & theMeshInfo, const EGrilleType & type)
References MED::eGRILLE_STANDARD, MED::TGrilleInfo::myCoordNames, MED::TGrilleInfo::myCoordUnits, MED::TGrilleInfo::myGrilleStructure, and MED::TGrilleInfo::myMeshInfo.
TTGrilleInfo() [4/4]
template<EVersion eVersion> MED::TTGrilleInfo< eVersion >::TTGrilleInfo (const PMeshInfo & theMeshInfo, const EGrilleType & type, const MED::TIntVector & nbNodeVec)
References MED::eGRILLE_STANDARD, MED::TGrilleInfo::myCoordNames, MED::TGrilleInfo::myCoordUnits, MED::TGrilleInfo::myGrilleStructure, MED::TGrilleInfo::myIndixes, and MED::TGrilleInfo::myMeshInfo.
Member Function Documentation
GetCoordName()
template<EVersion eVersion> virtual std::string MED::TTGrilleInfo< eVersion >::GetCoordName (TInt theId) const virtual
Get name of the coordinate dimension by its order number.
Implements MED::TGrilleInfo.
References MED::GetString(), and MED::TGrilleInfo::myCoordNames.
GetCoordUnit()
template<EVersion eVersion> virtual std::string MED::TTGrilleInfo< eVersion >::GetCoordUnit (TInt theId) const virtual
Get name of unit for the coordinate dimension by its order number.
Implements MED::TGrilleInfo.
References MED::GetString(), and MED::TGrilleInfo::myCoordUnits.
SetCoordName()
template<EVersion eVersion> virtual void MED::TTGrilleInfo< eVersion >::SetCoordName (TInt theId, const std::string & theValue) virtual
Set name of the coordinate dimension by its order number.
Implements MED::TGrilleInfo.
References MED::TGrilleInfo::myCoordNames, and MED::SetString().
SetCoordUnit()
template<EVersion eVersion> virtual void MED::TTGrilleInfo< eVersion >::SetCoordUnit (TInt theId, const std::string & theValue) virtual
Set name of unit for the coordinate dimension by its order number.
Implements MED::TGrilleInfo.
References MED::TGrilleInfo::myCoordUnits, and MED::SetString().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/MED_TStructures.hxx