FreeCAD: Gui::RubberbandSelection Class Reference
Gui::RubberbandSelection Class Reference
The selection mouse model class Draws a rectangle for selection.
#include <MouseSelection.h>
Public Member Functions
virtual void initialize ()
implement this in derived classes
RubberbandSelection ()
void setColor (float r, float g, float b, float a=1.0)
virtual void terminate (bool abort=false)
implement this in derived classes
virtual ~RubberbandSelection ()
Public Member Functions inherited from Gui::BaseMouseSelection
BaseMouseSelection ()
virtual ~BaseMouseSelection ()
Public Member Functions inherited from Gui::AbstractMouseSelection
AbstractMouseSelection ()
const std::vector< SbVec2s > & getPositions () const
void grabMouseModel (Gui::View3DInventorViewer *)
virtual void initialize ()=0
implement this in derived classes
void redraw ()
void releaseMouseModel (bool abort=false)
SelectionRole selectedRole () const
virtual void terminate (bool abort=false)=0
implement this in derived classes
virtual ~AbstractMouseSelection (void)
int handleEvent (const SoEvent *const ev, const SbViewportRegion &vp)
Protected Member Functions
virtual void draw ()
draw the rectangle
virtual int keyboardEvent (const SoKeyboardEvent *const e)
virtual int locationEvent (const SoLocation2Event *const e, const QPoint &pos)
virtual int mouseButtonEvent (const SoMouseButtonEvent *const e, const QPoint &pos)
Protected Member Functions inherited from Gui::AbstractMouseSelection
Protected Attributes
Gui::Rubberband rubberband
Protected Attributes inherited from Gui::AbstractMouseSelection
QCursor m_cPrevCursor
int m_iXold
int m_iYold
int m_iXnew
int m_iYnew
SelectionRole m_selectedRole
Additional Inherited Members
Public Types inherited from Gui::AbstractMouseSelection
enum {
Continue =0 , Restart =1 , Finish =2 , Cancel =3 ,
Ignore =4
}
Detailed Description
The selection mouse model class Draws a rectangle for selection.
Author
Werner Mayer
Constructor & Destructor Documentation
RubberbandSelection()
RubberbandSelection::RubberbandSelection ()
References rubberband, and Gui::Rubberband::setColor().
~RubberbandSelection()
RubberbandSelection::~RubberbandSelection () virtual
Member Function Documentation
draw()
void RubberbandSelection::draw () protected virtual
draw the rectangle
Reimplemented from Gui::AbstractMouseSelection.
Referenced by locationEvent().
initialize()
void RubberbandSelection::initialize () virtual
implement this in derived classes
Implements Gui::AbstractMouseSelection.
References Gui::View3DInventorViewer::Image, rubberband, Gui::Rubberband::setViewer(), and Gui::Rubberband::setWorking().
keyboardEvent()
int RubberbandSelection::keyboardEvent (const SoKeyboardEvent *const e) protected virtual
Reimplemented from Gui::AbstractMouseSelection.
References Gui::AbstractMouseSelection::Continue.
locationEvent()
int RubberbandSelection::locationEvent (const SoLocation2Event *const e, const QPoint & pos) protected virtual
Reimplemented from Gui::AbstractMouseSelection.
References Gui::AbstractMouseSelection::Continue, draw(), Gui::AbstractMouseSelection::m_iXnew, Gui::AbstractMouseSelection::m_iXold, Gui::AbstractMouseSelection::m_iYnew, Gui::AbstractMouseSelection::m_iYold, rubberband, and Gui::Rubberband::setCoords().
mouseButtonEvent()
int RubberbandSelection::mouseButtonEvent (const SoMouseButtonEvent *const e, const QPoint & pos) protected virtual
Reimplemented from Gui::AbstractMouseSelection.
References Gui::AbstractMouseSelection::Continue, Gui::AbstractMouseSelection::Finish, Gui::AbstractMouseSelection::m_iXnew, Gui::AbstractMouseSelection::m_iXold, Gui::AbstractMouseSelection::m_iYnew, Gui::AbstractMouseSelection::m_iYold, Gui::AbstractMouseSelection::releaseMouseModel(), rubberband, and Gui::Rubberband::setWorking().
setColor()
void RubberbandSelection::setColor (float r, float g, float b, float a = 1.0)
References rubberband, and Gui::Rubberband::setColor().
terminate()
void RubberbandSelection::terminate (bool abort = false) virtual
implement this in derived classes
Implements Gui::AbstractMouseSelection.
Reimplemented in Gui::BoxZoomSelection.
References Gui::View3DInventorViewer::Native, and rubberband.
Referenced by Gui::BoxZoomSelection::terminate(), and addonmanager_workers.CacheMacroCode::update_and_advance().
Member Data Documentation
rubberband
Gui::Rubberband Gui::RubberbandSelection::rubberband protected
Referenced by initialize(), locationEvent(), mouseButtonEvent(), Gui::RectangleSelection::RectangleSelection(), RubberbandSelection(), setColor(), and terminate().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/MouseSelection.h
FreeCAD/src/Gui/MouseSelection.cpp