FreeCAD: iisFreeCADTaskPanelScheme Class Reference
iisFreeCADTaskPanelScheme Class Reference
#include <iisfreecadscheme.h>
Public Member Functions
iisFreeCADTaskPanelScheme (QObject *parent=0)
~iisFreeCADTaskPanelScheme ()
Public Member Functions inherited from iisTaskPanelScheme
iisTaskPanelScheme (QObject *parent=0)
~iisTaskPanelScheme ()
Static Public Member Functions
static iisTaskPanelScheme * defaultScheme ()
Static Public Member Functions inherited from iisTaskPanelScheme
static iisTaskPanelScheme * defaultScheme ()
Protected Member Functions
QPixmap drawFoldIcon (const QPalette &) const
Static Protected Attributes
static iisFreeCADTaskPanelScheme * myDefaultXPScheme = 0
Static Protected Attributes inherited from iisTaskPanelScheme
static iisTaskPanelScheme * myDefaultScheme = 0
Additional Inherited Members
Public Attributes inherited from iisTaskPanelScheme
QBrush groupBackground
QPen groupBorder
int groupFoldDelay
int groupFoldSteps
bool headerAnimation
QBrush headerBackground
QPen headerBorder
QIcon headerButtonFold
QIcon headerButtonFoldOver
QSize headerButtonSize
QIcon headerButtonUnfold
QIcon headerButtonUnfoldOver
iisIconLabelScheme headerLabelScheme
int headerSize
QBrush panelBackground
iisIconLabelScheme taskLabelScheme
Constructor & Destructor Documentation
iisFreeCADTaskPanelScheme()
iisFreeCADTaskPanelScheme::iisFreeCADTaskPanelScheme (QObject * parent = 0)
References drawFoldIcon(), iisTaskPanelScheme::groupBackground, iisTaskPanelScheme::groupBorder, iisTaskPanelScheme::headerAnimation, iisTaskPanelScheme::headerBackground, iisTaskPanelScheme::headerBorder, iisTaskPanelScheme::headerButtonFold, iisTaskPanelScheme::headerButtonFoldOver, iisTaskPanelScheme::headerButtonSize, iisTaskPanelScheme::headerButtonUnfold, iisTaskPanelScheme::headerButtonUnfoldOver, iisTaskPanelScheme::headerLabelScheme, iisTaskPanelScheme::headerSize, iisIconLabelScheme::iconSize, iisTaskPanelScheme::panelBackground, iisTaskPanelScheme::taskLabelScheme, iisIconLabelScheme::text, and iisIconLabelScheme::textOver.
Referenced by defaultScheme().
~iisFreeCADTaskPanelScheme()
iisFreeCADTaskPanelScheme::~iisFreeCADTaskPanelScheme ()
Member Function Documentation
defaultScheme()
iisTaskPanelScheme * iisFreeCADTaskPanelScheme::defaultScheme () static
References iisFreeCADTaskPanelScheme(), and myDefaultXPScheme.
Referenced by Gui::TaskView::TaskView::TaskView().
drawFoldIcon()
QPixmap iisFreeCADTaskPanelScheme::drawFoldIcon (const QPalette & p) const protected
Referenced by iisFreeCADTaskPanelScheme().
Member Data Documentation
myDefaultXPScheme
iisFreeCADTaskPanelScheme * iisFreeCADTaskPanelScheme::myDefaultXPScheme = 0 static protected
Referenced by defaultScheme().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/iisTaskPanel/src/iisfreecadscheme.h
Sources/FreeCAD/src/Gui/iisTaskPanel/src/iisfreecadscheme.cpp