FreeCAD: UNV2420 Namespace Reference
UNV2420 Namespace Reference
Classes
struct TRecord
Typedefs
typedef int TCSLabel
typedef std::vector< TRecord > TDataSet
Enumerations
enum { Cartesian =0, Cylindrical, Spherical }
Functions
MESHDRIVERUNV_EXPORT void Read (std::ifstream &in_stream, std::string &part_name, TDataSet &theDataSet)
MESHDRIVERUNV_EXPORT void Write (std::ofstream &out_stream, const std::string &part_name)
Typedef Documentation
TCSLabel
typedef int UNV2420::TCSLabel
TDataSet
typedef std::vector<TRecord> UNV2420::TDataSet
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
Cartesian
Cylindrical
Spherical
Function Documentation
Read()
void UNV2420::Read (std::ifstream & in_stream, std::string & part_name, TDataSet & theDataSet)
References UNV::beginning_of_dataset(), UNV2420::TRecord::coord_sys_color, UNV2420::TRecord::coord_sys_label, UNV2420::TRecord::coord_sys_name, UNV2420::TRecord::coord_sys_type, UNV::D_to_e(), UNV2420::TRecord::isIdentityMatrix(), UNV2420::TRecord::matrix, and UNV::read_line().
Referenced by DriverUNV_R_SMDS_Mesh::Perform().
Write()
void UNV2420::Write (std::ofstream & out_stream, const std::string & part_name)
Referenced by DriverUNV_W_SMDS_Mesh::Perform().