FreeCAD: plotUtils.Paths Namespace Reference
plotUtils.Paths Namespace Reference
Functions
def iconsPath ()
def modulePath ()
def translationsPath ()
Function Documentation
iconsPath()
def plotUtils.Paths.iconsPath ()
returns the current Plot module icons path.
References plotUtils.Paths.modulePath().
modulePath()
def plotUtils.Paths.modulePath ()
returns the current Plot module path.
Referenced by plotUtils.Paths.iconsPath(), and plotUtils.Paths.translationsPath().
translationsPath()
def plotUtils.Paths.translationsPath ()
returns the current Plot module translations path.
References plotUtils.Paths.modulePath().