FreeCAD: Gui::View3DInventorPy Class Reference
Gui::View3DInventorPy Class Reference
#include <View3DPy.h>
Public Types
using BaseType = Py::PythonExtension< View3DInventorPy >
Public Member Functions
Py::Object addDraggerCallback (const Py::Tuple &)
Py::Object addEventCallback (const Py::Tuple &)
Py::Object addEventCallbackPivy (const Py::Tuple &)
Py::Object boxZoom (const Py::Tuple &, const Py::Dict &)
Py::Object cast_to_base (const Py::Tuple &)
Py::Object dump (const Py::Tuple &)
Py::Object dumpNode (const Py::Tuple &)
Py::Object fitAll (const Py::Tuple &)
Py::Object getActiveObject (const Py::Tuple &)
Py::Object getattr (const char *)
Py::Object getCamera (const Py::Tuple &)
Py::Object getCameraNode (const Py::Tuple &)
Py::Object getCameraOrientation (const Py::Tuple &)
Py::Object getCameraType (const Py::Tuple &)
Py::Object getCornerCrossSize (const Py::Tuple &args)
Py::Object getCursorPos (const Py::Tuple &)
Py::Object getNavigationType (const Py::Tuple &)
Py::Object getObjectInfo (const Py::Tuple &)
Py::Object getObjectsInfo (const Py::Tuple &)
Py::Object getPointOnFocalPlane (const Py::Tuple &)
Py::Object getPointOnScreen (const Py::Tuple &)
Py::Object getSceneGraph (const Py::Tuple &)
Py::Object getSize (const Py::Tuple &)
Py::Object getStereoType (const Py::Tuple &)
View3DInventor * getView3DIventorPtr ()
Py::Object getViewDirection (const Py::Tuple &)
Py::Object getViewer (const Py::Tuple &)
Py::Object getViewProvidersOfType (const Py::Tuple &)
Py::Object graphicsView (const Py::Tuple &args)
Py::Object hasAxisCross (const Py::Tuple &)
Py::Object hasClippingPlane (const Py::Tuple &args)
Py::Object isAnimationEnabled (const Py::Tuple &)
Py::Object isCornerCrossVisible (const Py::Tuple &args)
Py::Object isPopupMenuEnabled (const Py::Tuple &)
Py::Object listCameraTypes (const Py::Tuple &)
Py::Object listNavigationTypes (const Py::Tuple &)
Py::Object listStereoTypes (const Py::Tuple &)
Py::Object projectPointToLine (const Py::Tuple &)
Py::Object redraw (const Py::Tuple &)
Py::Object removeAnnotation (const Py::Tuple &)
Py::Object removeDraggerCallback (const Py::Tuple &)
Py::Object removeEventCallback (const Py::Tuple &)
Py::Object removeEventCallbackPivy (const Py::Tuple &)
Py::Object repr ()
Py::Object saveImage (const Py::Tuple &)
Py::Object saveVectorGraphic (const Py::Tuple &)
Py::Object setActiveObject (const Py::Tuple &)
Py::Object setAnimationEnabled (const Py::Tuple &)
Py::Object setAnnotation (const Py::Tuple &)
int setattr (const char *, const Py::Object &)
Py::Object setAxisCross (const Py::Tuple &)
Py::Object setCamera (const Py::Tuple &)
Py::Object setCameraOrientation (const Py::Tuple &)
Py::Object setCameraType (const Py::Tuple &)
Py::Object setCornerCrossSize (const Py::Tuple &args)
Py::Object setCornerCrossVisible (const Py::Tuple &args)
Py::Object setName (const Py::Tuple &)
Py::Object setNavigationType (const Py::Tuple &)
Py::Object setPopupMenuEnabled (const Py::Tuple &)
Py::Object setStereoType (const Py::Tuple &)
Py::Object setViewDirection (const Py::Tuple &)
Py::Object startAnimating (const Py::Tuple &)
Py::Object stopAnimating (const Py::Tuple &)
Py::Object toggleClippingPlane (const Py::Tuple &args, const Py::Dict &)
View3DInventorPy (View3DInventor *vi)
Py::Object viewBottom (const Py::Tuple &)
Py::Object viewDefaultOrientation (const Py::Tuple &)
Py::Object viewDimetric (const Py::Tuple &)
Py::Object viewFront (const Py::Tuple &)
Py::Object viewIsometric (const Py::Tuple &)
Py::Object viewLeft (const Py::Tuple &)
Py::Object viewPosition (const Py::Tuple &)
Py::Object viewRear (const Py::Tuple &)
Py::Object viewRight (const Py::Tuple &)
Py::Object viewRotateLeft (const Py::Tuple &)
Py::Object viewRotateRight (const Py::Tuple &)
Py::Object viewTop (const Py::Tuple &)
Py::Object viewTrimetric (const Py::Tuple &)
Py::Object zoomIn (const Py::Tuple &)
Py::Object zoomOut (const Py::Tuple &)
~View3DInventorPy ()
Static Public Member Functions
static void init_type ()
Member Typedef Documentation
BaseType
using Gui::View3DInventorPy::BaseType = Py::PythonExtension<View3DInventorPy>
Constructor & Destructor Documentation
View3DInventorPy()
View3DInventorPy::View3DInventorPy (View3DInventor * vi)
~View3DInventorPy()
View3DInventorPy::~View3DInventorPy ()
Member Function Documentation
addDraggerCallback()
Py::Object View3DInventorPy::addDraggerCallback (const Py::Tuple & args)
References Base::InterpreterSingleton::convertSWIGPointerObj(), and Base::Interpreter().
Referenced by init_type().
addEventCallback()
Py::Object View3DInventorPy::addEventCallback (const Py::Tuple & args)
References Gui::View3DInventorViewer::addEventCallback(), getView3DIventorPtr(), and Gui::View3DInventor::getViewer().
Referenced by init_type().
addEventCallbackPivy()
Py::Object View3DInventorPy::addEventCallbackPivy (const Py::Tuple & args)
References Gui::View3DInventorViewer::addEventCallback(), Base::InterpreterSingleton::convertSWIGPointerObj(), getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Base::Interpreter().
Referenced by init_type().
boxZoom()
Py::Object View3DInventorPy::boxZoom (const Py::Tuple & args, const Py::Dict & kwds)
References Gui::View3DInventorViewer::boxZoom(), getView3DIventorPtr(), and Gui::View3DInventor::getViewer().
Referenced by init_type().
cast_to_base()
Py::Object View3DInventorPy::cast_to_base (const Py::Tuple &)
References Gui::MDIViewPy::create(), and getView3DIventorPtr().
Referenced by init_type().
dump()
Py::Object View3DInventorPy::dump (const Py::Tuple & args)
References Gui::View3DInventor::dump(), and getView3DIventorPtr().
Referenced by init_type().
dumpNode()
Py::Object View3DInventorPy::dumpNode (const Py::Tuple & args)
References Base::InterpreterSingleton::convertSWIGPointerObj(), Base::Interpreter(), and Gui::SoFCDB::writeNodesToString().
Referenced by init_type().
fitAll()
Py::Object View3DInventorPy::fitAll (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::viewAll().
Referenced by init_type().
getActiveObject()
Py::Object View3DInventorPy::getActiveObject (const Py::Tuple & args)
References Gui::MDIView::getActiveObject(), App::DocumentObject::getPyObject(), and getView3DIventorPtr().
Referenced by init_type().
getattr()
Py::Object View3DInventorPy::getattr (const char * attr)
References Gui::MDIView::getActiveObject(), App::DocumentObject::getPyObject(), and getView3DIventorPtr().
getCamera()
Py::Object View3DInventorPy::getCamera (const Py::Tuple & args)
References getView3DIventorPtr(), and Gui::View3DInventor::getViewer().
Referenced by init_type().
getCameraNode()
Py::Object View3DInventorPy::getCameraNode (const Py::Tuple & args)
References Base::InterpreterSingleton::createSWIGPointerObj(), getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Base::Interpreter().
Referenced by init_type().
getCameraOrientation()
Py::Object View3DInventorPy::getCameraOrientation (const Py::Tuple & args)
References Gui::View3DInventorViewer::getCameraOrientation(), getView3DIventorPtr(), and Gui::View3DInventor::getViewer().
Referenced by init_type().
getCameraType()
Py::Object View3DInventorPy::getCameraType (const Py::Tuple & args)
References getView3DIventorPtr(), and Gui::View3DInventor::getViewer().
Referenced by init_type().
getCornerCrossSize()
Py::Object View3DInventorPy::getCornerCrossSize (const Py::Tuple & args)
References Gui::View3DInventorViewer::getFeedbackSize(), getView3DIventorPtr(), and Gui::View3DInventor::getViewer().
Referenced by init_type().
getCursorPos()
Py::Object View3DInventorPy::getCursorPos (const Py::Tuple & args)
References getView3DIventorPtr().
Referenced by init_type().
getNavigationType()
Py::Object View3DInventorPy::getNavigationType (const Py::Tuple &)
References Base::Type::getName(), Base::BaseClass::getTypeId(), getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::navigationStyle().
Referenced by init_type().
getObjectInfo()
Py::Object View3DInventorPy::getObjectInfo (const Py::Tuple & args)
References Gui::SoFCDocumentObjectAction::componentName, Gui::SoFCDocumentObjectAction::documentName, Base::Persistence::getClassTypeId(), Gui::View3DInventorViewer::getDocument(), App::DocumentObject::getDocument(), Gui::ViewProvider::getElementPicked(), App::Document::getName(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), getSceneGraph(), getView3DIventorPtr(), getViewer(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::getViewProviderByPath(), Base::BaseClass::isDerivedFrom(), Gui::SoFCDocumentObjectAction::isHandled(), Gui::ViewProvider::isSelectable(), Gui::SoFCDocumentObjectAction::objectName, App::GeoFeature::resolveElement(), and Gui::ViewProvider::useNewSelectionModel().
Referenced by init_type().
getObjectsInfo()
Py::Object View3DInventorPy::getObjectsInfo (const Py::Tuple & args)
References Gui::SoFCDocumentObjectAction::componentName, Gui::SoFCDocumentObjectAction::documentName, Base::Persistence::getClassTypeId(), Gui::View3DInventorViewer::getDocument(), App::DocumentObject::getDocument(), Gui::ViewProvider::getElementPicked(), App::Document::getName(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), getSceneGraph(), getView3DIventorPtr(), getViewer(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::getViewProviderByPath(), Base::BaseClass::isDerivedFrom(), Gui::SoFCDocumentObjectAction::isHandled(), Gui::ViewProvider::isSelectable(), Gui::SoFCDocumentObjectAction::objectName, App::GeoFeature::resolveElement(), and Gui::ViewProvider::useNewSelectionModel().
Referenced by init_type().
getPointOnFocalPlane()
Py::Object View3DInventorPy::getPointOnFocalPlane (const Py::Tuple & args)
References Gui::View3DInventorViewer::getPointOnFocalPlane(), getView3DIventorPtr(), and Gui::View3DInventor::getViewer().
Referenced by init_type().
getPointOnScreen()
Py::Object View3DInventorPy::getPointOnScreen (const Py::Tuple & args)
References Gui::View3DInventorViewer::getPointOnScreen(), getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and draftgeoutils.general::vec().
Referenced by init_type().
getSceneGraph()
Py::Object View3DInventorPy::getSceneGraph (const Py::Tuple & args)
References Base::InterpreterSingleton::createSWIGPointerObj(), getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Base::Interpreter().
Referenced by getObjectInfo(), getObjectsInfo(), and init_type().
getSize()
Py::Object View3DInventorPy::getSize (const Py::Tuple & args)
References getView3DIventorPtr(), and Gui::View3DInventor::getViewer().
Referenced by init_type().
getStereoType()
Py::Object View3DInventorPy::getStereoType (const Py::Tuple & args)
References getView3DIventorPtr(), and getViewer().
Referenced by init_type().
getView3DIventorPtr()
View3DInventor * View3DInventorPy::getView3DIventorPtr ()
Referenced by addEventCallback(), addEventCallbackPivy(), boxZoom(), cast_to_base(), dump(), fitAll(), getActiveObject(), getattr(), getCamera(), getCameraNode(), getCameraOrientation(), getCameraType(), getCornerCrossSize(), getCursorPos(), getNavigationType(), getObjectInfo(), getObjectsInfo(), getPointOnFocalPlane(), getPointOnScreen(), getSceneGraph(), getSize(), getStereoType(), getViewDirection(), getViewer(), getViewProvidersOfType(), graphicsView(), hasAxisCross(), hasClippingPlane(), isAnimationEnabled(), isCornerCrossVisible(), isPopupMenuEnabled(), projectPointToLine(), redraw(), removeAnnotation(), removeEventCallback(), removeEventCallbackPivy(), repr(), saveImage(), saveVectorGraphic(), setActiveObject(), setAnimationEnabled(), setAnnotation(), setattr(), setAxisCross(), setCamera(), setCameraOrientation(), setCameraType(), setCornerCrossSize(), setCornerCrossVisible(), setName(), setNavigationType(), setPopupMenuEnabled(), setStereoType(), setViewDirection(), startAnimating(), stopAnimating(), toggleClippingPlane(), viewBottom(), viewDefaultOrientation(), viewDimetric(), viewFront(), viewIsometric(), viewLeft(), viewPosition(), viewRear(), viewRight(), viewRotateLeft(), viewRotateRight(), viewTop(), viewTrimetric(), zoomIn(), and zoomOut().
getViewDirection()
Py::Object View3DInventorPy::getViewDirection (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventorViewer::getViewDirection(), and Gui::View3DInventor::getViewer().
Referenced by init_type().
getViewer()
Py::Object View3DInventorPy::getViewer (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and OfflineRenderingUtils::viewer().
Referenced by getObjectInfo(), getObjectsInfo(), getStereoType(), graphicsView(), hasClippingPlane(), and init_type().
getViewProvidersOfType()
Py::Object View3DInventorPy::getViewProvidersOfType (const Py::Tuple & args)
References Base::Type::fromName(), getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::getViewProvidersOfType().
Referenced by init_type().
graphicsView()
Py::Object View3DInventorPy::graphicsView (const Py::Tuple & args)
References Gui::PythonWrapper::fromQWidget(), getView3DIventorPtr(), getViewer(), and Gui::PythonWrapper::loadWidgetsModule().
Referenced by init_type().
hasAxisCross()
Py::Object View3DInventorPy::hasAxisCross (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::hasAxisCross().
Referenced by init_type().
hasClippingPlane()
Py::Object View3DInventorPy::hasClippingPlane (const Py::Tuple & args)
References getView3DIventorPtr(), getViewer(), and hasClippingPlane().
Referenced by hasClippingPlane(), and init_type().
init_type()
void View3DInventorPy::init_type (void) static
References addDraggerCallback(), addEventCallback(), addEventCallbackPivy(), boxZoom(), cast_to_base(), dump(), dumpNode(), fitAll(), getActiveObject(), getCamera(), getCameraNode(), getCameraOrientation(), getCameraType(), getCornerCrossSize(), getCursorPos(), getNavigationType(), getObjectInfo(), getObjectsInfo(), getPointOnFocalPlane(), getPointOnScreen(), getSceneGraph(), getSize(), getStereoType(), getViewDirection(), getViewer(), getViewProvidersOfType(), graphicsView(), hasAxisCross(), hasClippingPlane(), isAnimationEnabled(), isCornerCrossVisible(), isPopupMenuEnabled(), listCameraTypes(), listNavigationTypes(), listStereoTypes(), projectPointToLine(), redraw(), removeAnnotation(), removeDraggerCallback(), removeEventCallback(), removeEventCallbackPivy(), saveImage(), saveVectorGraphic(), setActiveObject(), setAnimationEnabled(), setAnnotation(), setAxisCross(), setCamera(), setCameraOrientation(), setCameraType(), setCornerCrossSize(), setCornerCrossVisible(), setName(), setNavigationType(), setPopupMenuEnabled(), setStereoType(), setViewDirection(), startAnimating(), stopAnimating(), toggleClippingPlane(), viewBottom(), viewDefaultOrientation(), viewDimetric(), viewFront(), viewIsometric(), viewLeft(), viewPosition(), viewRear(), viewRight(), viewRotateLeft(), viewRotateRight(), viewTop(), viewTrimetric(), zoomIn(), and zoomOut().
Referenced by Gui::Application::Application().
isAnimationEnabled()
Py::Object View3DInventorPy::isAnimationEnabled (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::isAnimationEnabled().
Referenced by init_type().
isCornerCrossVisible()
Py::Object View3DInventorPy::isCornerCrossVisible (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::isFeedbackVisible().
Referenced by init_type().
isPopupMenuEnabled()
Py::Object View3DInventorPy::isPopupMenuEnabled (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::isPopupMenuEnabled().
Referenced by init_type().
listCameraTypes()
Py::Object View3DInventorPy::listCameraTypes (const Py::Tuple & args)
Referenced by init_type().
listNavigationTypes()
Py::Object View3DInventorPy::listNavigationTypes (const Py::Tuple &)
References Base::Type::getAllDerivedFrom(), and Base::BaseClass::getClassTypeId().
Referenced by init_type().
listStereoTypes()
Py::Object View3DInventorPy::listStereoTypes (const Py::Tuple & args)
Referenced by init_type().
projectPointToLine()
Py::Object View3DInventorPy::projectPointToLine (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::projectPointToLine().
Referenced by init_type().
redraw()
Py::Object View3DInventorPy::redraw (const Py::Tuple & args)
References getView3DIventorPtr(), and Gui::View3DInventor::getViewer().
Referenced by init_type(), and draftguitools.gui_trimex.Trimex::trimObject().
removeAnnotation()
Py::Object View3DInventorPy::removeAnnotation (const Py::Tuple & args)
References Gui::Document::getAnnotationViewProvider(), Gui::BaseView::getGuiDocument(), getView3DIventorPtr(), and Gui::Document::removeAnnotationViewProvider().
Referenced by init_type().
removeDraggerCallback()
Py::Object View3DInventorPy::removeDraggerCallback (const Py::Tuple & args)
References Base::InterpreterSingleton::convertSWIGPointerObj(), and Base::Interpreter().
Referenced by init_type().
removeEventCallback()
Py::Object View3DInventorPy::removeEventCallback (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::removeEventCallback().
Referenced by init_type().
removeEventCallbackPivy()
Py::Object View3DInventorPy::removeEventCallbackPivy (const Py::Tuple & args)
References Base::InterpreterSingleton::convertSWIGPointerObj(), getView3DIventorPtr(), Gui::View3DInventor::getViewer(), Base::Interpreter(), and Gui::View3DInventorViewer::removeEventCallback().
Referenced by init_type().
repr()
Py::Object View3DInventorPy::repr ()
References getView3DIventorPtr().
saveImage()
Py::Object View3DInventorPy::saveImage (const Py::Tuple & args)
References Gui::View3DInventorViewer::getNumSamples(), getView3DIventorPtr(), Gui::View3DInventor::getViewer(), Gui::SoFCOffscreenRenderer::instance(), Gui::View3DInventorViewer::savePicture(), and Gui::SoFCOffscreenRenderer::writeToImageFile().
Referenced by init_type().
saveVectorGraphic()
Py::Object View3DInventorPy::saveVectorGraphic (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), Base::FileInfo::hasExtension(), and Gui::View3DInventorViewer::saveGraphic().
Referenced by init_type().
setActiveObject()
Py::Object View3DInventorPy::setActiveObject (const Py::Tuple & args)
References getView3DIventorPtr(), and Gui::MDIView::setActiveObject().
Referenced by init_type().
setAnimationEnabled()
Py::Object View3DInventorPy::setAnimationEnabled (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::setAnimationEnabled().
Referenced by init_type().
setAnnotation()
Py::Object View3DInventorPy::setAnnotation (const Py::Tuple & args)
References Gui::BaseView::getGuiDocument(), getView3DIventorPtr(), and Gui::Document::setAnnotationViewProvider().
Referenced by init_type().
setattr()
int View3DInventorPy::setattr (const char * attr, const Py::Object & value)
References getView3DIventorPtr().
setAxisCross()
Py::Object View3DInventorPy::setAxisCross (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::setAxisCross().
Referenced by init_type().
setCamera()
Py::Object View3DInventorPy::setCamera (const Py::Tuple & args)
References getView3DIventorPtr(), and Gui::View3DInventor::setCamera().
Referenced by init_type().
setCameraOrientation()
Py::Object View3DInventorPy::setCameraOrientation (const Py::Tuple & args)
References Base::Rotation::getValue(), getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::setCameraOrientation().
Referenced by init_type().
setCameraType()
Py::Object View3DInventorPy::setCameraType (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::setCameraType().
Referenced by init_type().
setCornerCrossSize()
Py::Object View3DInventorPy::setCornerCrossSize (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::setFeedbackSize().
Referenced by init_type().
setCornerCrossVisible()
Py::Object View3DInventorPy::setCornerCrossVisible (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::setFeedbackVisibility().
Referenced by init_type().
setName()
Py::Object View3DInventorPy::setName (const Py::Tuple & args)
References getView3DIventorPtr().
Referenced by init_type().
setNavigationType()
Py::Object View3DInventorPy::setNavigationType (const Py::Tuple & args)
References Base::Type::fromName(), getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::setNavigationType().
Referenced by init_type().
setPopupMenuEnabled()
Py::Object View3DInventorPy::setPopupMenuEnabled (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::setPopupMenuEnabled().
Referenced by init_type().
setStereoType()
Py::Object View3DInventorPy::setStereoType (const Py::Tuple & args)
References getView3DIventorPtr(), and Gui::View3DInventor::getViewer().
Referenced by init_type().
setViewDirection()
Py::Object View3DInventorPy::setViewDirection (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::setViewDirection().
Referenced by init_type().
startAnimating()
Py::Object View3DInventorPy::startAnimating (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::startAnimating().
Referenced by init_type().
stopAnimating()
Py::Object View3DInventorPy::stopAnimating (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::stopAnimating().
Referenced by init_type().
toggleClippingPlane()
Py::Object View3DInventorPy::toggleClippingPlane (const Py::Tuple & args, const Py::Dict & kwds)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::toggleClippingPlane().
Referenced by init_type().
viewBottom()
Py::Object View3DInventorPy::viewBottom (const Py::Tuple & args)
References Gui::Camera::Bottom, getView3DIventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::rotation(), and Gui::View3DInventorViewer::setCameraOrientation().
Referenced by init_type().
viewDefaultOrientation()
Py::Object View3DInventorPy::viewDefaultOrientation (const Py::Tuple & args)
References Gui::Camera::Bottom, Gui::Camera::Dimetric, Gui::Camera::Front, App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetFloat(), App::Application::GetParameterGroupByPath(), getView3DIventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::Isometric, Gui::Camera::Left, Gui::Camera::Rear, Gui::Camera::Right, Gui::Camera::rotation(), Gui::Camera::Top, and Gui::Camera::Trimetric.
Referenced by init_type().
viewDimetric()
Py::Object View3DInventorPy::viewDimetric (const Py::Tuple & args)
References Gui::Camera::Dimetric, getView3DIventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::rotation(), and Gui::View3DInventorViewer::setCameraOrientation().
Referenced by init_type().
viewFront()
Py::Object View3DInventorPy::viewFront (const Py::Tuple & args)
References Gui::Camera::Front, getView3DIventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::rotation(), and Gui::View3DInventorViewer::setCameraOrientation().
Referenced by init_type().
viewIsometric()
Py::Object View3DInventorPy::viewIsometric (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::Isometric, Gui::Camera::rotation(), and Gui::View3DInventorViewer::setCameraOrientation().
Referenced by init_type().
viewLeft()
Py::Object View3DInventorPy::viewLeft (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::Left, Gui::Camera::rotation(), and Gui::View3DInventorViewer::setCameraOrientation().
Referenced by init_type().
viewPosition()
Py::Object View3DInventorPy::viewPosition (const Py::Tuple & args)
References Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Rotation::getValue(), getView3DIventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::moveCameraTo().
Referenced by init_type().
viewRear()
Py::Object View3DInventorPy::viewRear (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::Rear, Gui::Camera::rotation(), and Gui::View3DInventorViewer::setCameraOrientation().
Referenced by init_type().
viewRight()
Py::Object View3DInventorPy::viewRight (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::Right, Gui::Camera::rotation(), and Gui::View3DInventorViewer::setCameraOrientation().
Referenced by init_type().
viewRotateLeft()
Py::Object View3DInventorPy::viewRotateLeft (const Py::Tuple & args)
References getView3DIventorPtr(), and Gui::View3DInventor::getViewer().
Referenced by init_type().
viewRotateRight()
Py::Object View3DInventorPy::viewRotateRight (const Py::Tuple & args)
References getView3DIventorPtr(), and Gui::View3DInventor::getViewer().
Referenced by init_type().
viewTop()
Py::Object View3DInventorPy::viewTop (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::rotation(), Gui::View3DInventorViewer::setCameraOrientation(), and Gui::Camera::Top.
Referenced by init_type().
viewTrimetric()
Py::Object View3DInventorPy::viewTrimetric (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::rotation(), Gui::View3DInventorViewer::setCameraOrientation(), and Gui::Camera::Trimetric.
Referenced by init_type().
zoomIn()
Py::Object View3DInventorPy::zoomIn (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::navigationStyle(), and Gui::NavigationStyle::zoomIn().
Referenced by init_type().
zoomOut()
Py::Object View3DInventorPy::zoomOut (const Py::Tuple & args)
References getView3DIventorPtr(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::navigationStyle(), and Gui::NavigationStyle::zoomOut().
Referenced by init_type().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/View3DPy.h
FreeCAD/src/Gui/View3DPy.cpp