FreeCAD: WebGui::BrowserView Class Reference
WebGui::BrowserView Class Reference
A special view class which sends the messages from the application to the editor and embeds it in a window.
#include <BrowserView.h>
Public Member Functions
BrowserView (QWidget *parent)
Constructs a BrowserView which is a child of 'parent', with the name 'name'.
bool canClose (void)
Checking on close state.
const char * getName (void) const
returns the name of the view (important for messages)
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
void load (const char *URL)
void load (const QUrl &url)
void OnChange (Base::Subject< const char * > &rCaller, const char *rcReason)
bool onHasMsg (const char *pMsg) const
Checks if the action pMsg is available.
bool onMsg (const char *pMsg, const char **ppReturn)
Runs the action specified by pMsg.
void setHtml (const QString &HtmlCode, const QUrl &BaseUrl)
void stop (void)
QUrl url () const
~BrowserView ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::MDIView
virtual bool canClose (void)
overwrite when checking on close state
virtual void deleteSelf ()
delete itself
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
View constructor Attach the view to the given document.
virtual bool onHasMsg (const char *pMsg) const
Message handler test.
virtual bool onMsg (const char *pMsg, const char **ppReturn)
Message handler.
virtual void onRelabel (Gui::Document *pDoc)
get called when the document is updated
virtual void viewAll ()
~MDIView ()
View destructor Detach the view from the document, if attached.
virtual QStringList undoActions () const
virtual QStringList redoActions () const
QSize minimumSizeHint () const
virtual void setCurrentViewMode (ViewMode mode)
If b is set to FullScreen the MDI view is displayed in full screen mode, if b is set to TopLevel then it is displayed as an own top-level window, otherwise (Normal) as tabbed window.
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=nullptr, std::string *subname=nullptr) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr) const
virtual bool containsViewProvider (const ViewProvider *) const
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
virtual void print ()
Print content of view.
virtual void printPdf ()
Print to PDF file.
virtual void printPreview ()
Show a preview dialog.
void savePrinterSettings (QPrinter *printer)
Save the printer configuration.
void restorePrinterSettings (QPrinter *printer)
Restore the printer configuration.
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=nullptr)
View constructor Attach the view to the given document.
virtual ~BaseView ()
View destructor Detach the view from the document, if attached!
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose (void)
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive (void) const
indicates if the view is in passive mode
virtual void onUpdate (void)
get called when the document is updated
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Gui::WindowParameter
ParameterGrp::handle getWindowParameter (void)
return the parameter group of this window
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason)
bool setGroupName (const char *name)
Sets the group of the window to name.
WindowParameter (const char *name)
virtual ~WindowParameter ()
Protected Slots
bool chckHostAllowed (const QString &host)
void onDownloadRequested (const QNetworkRequest &request)
void onLinkHovered (const QString &link, const QString &title, const QString &textContent)
void onLoadFinished (bool)
void onLoadProgress (int)
void onLoadStarted ()
void onOpenLinkInExternalBrowser (const QUrl &url)
void onOpenLinkInNewWindow (const QUrl &)
void onUnsupportedContent (QNetworkReply *reply)
void onUpdateBrowserActions ()
void onViewSource (const QUrl &url)
void urlFilter (const QUrl &url)
Protected Slots inherited from Gui::MDIView
virtual void windowStateChanged (MDIView *)
This method gets called from the main window this view is attached to whenever the window state of the active view changes.
Additional Inherited Members
Public Types inherited from Gui::MDIView
enum ViewMode { Child , TopLevel , FullScreen }
MDI view mode enum.
Public Slots inherited from Gui::MDIView
virtual void setOverrideCursor (const QCursor &)
virtual void restoreOverrideCursor ()
virtual void print (QPrinter *printer)
Signals inherited from Gui::MDIView
void message (const QString &, int)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter (void)
get the parameters
Protected Member Functions inherited from Gui::MDIView
void closeEvent (QCloseEvent *e)
void changeEvent (QEvent *e)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::MDIView
PyObject * pythonObject
Protected Attributes inherited from Gui::BaseView
bool bIsDetached
bool bIsPassive
Detailed Description
A special view class which sends the messages from the application to the editor and embeds it in a window.
Constructor & Destructor Documentation
BrowserView()
BrowserView::BrowserView (QWidget * parent)
Constructs a BrowserView which is a child of 'parent', with the name 'name'.
References draftgeoutils.intersections::connect(), and App::Application::getUserAppDataDir().
~BrowserView()
BrowserView::~BrowserView ()
Destroys the object and frees any allocated resources.
Member Function Documentation
canClose()
bool BrowserView::canClose (void) virtual
Checking on close state.
Reimplemented from Gui::MDIView.
chckHostAllowed
bool BrowserView::chckHostAllowed (const QString & host) protected slot
getName()
const char * WebGui::BrowserView::getName (void) const virtual
returns the name of the view (important for messages)
Reimplemented from Gui::BaseView.
getPyObject()
PyObject * BrowserView::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Gui::MDIView.
References Base::BaseClass::init(), and WebGui::BrowserViewPy::init_type().
load() [1/2]
void BrowserView::load (const char * URL)
References load(), and url().
Referenced by WebGui::UrlWidget::keyPressEvent(), load(), WebGui::BrowserViewPy::load(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::loadDefaults(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle(), and urlFilter().
load() [2/2]
void BrowserView::load (const QUrl & url)
References stop(), and url().
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::loadDefaults(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle().
OnChange()
void BrowserView::OnChange (Base::Subject< const char * > & rCaller, const char * rcReason)
onDownloadRequested
void BrowserView::onDownloadRequested (const QNetworkRequest & request) protected slot
References Gui::Dialog::DownloadManager::download(), App::GetApplication(), Gui::Dialog::DownloadManager::getInstance(), Gui::getMainWindow(), Gui::MainWindow::loadUrls(), and url().
onHasMsg()
bool BrowserView::onHasMsg (const char * pMsg) const virtual
Checks if the action pMsg is available.
This is for enabling/disabling the corresponding buttons or menu items for this action.
Reimplemented from Gui::MDIView.
onLinkHovered
void BrowserView::onLinkHovered (const QString & link, const QString & title, const QString & textContent) protected slot
References Gui::getMainWindow(), Gui::MainWindow::showMessage(), and url().
onLoadFinished
void BrowserView::onLoadFinished (bool ok) protected slot
References Gui::getMainWindow(), and Gui::MainWindow::showMessage().
onLoadProgress
void BrowserView::onLoadProgress (int step) protected slot
References Gui::SequencerBar::getProgressBar(), and Gui::SequencerBar::instance().
onLoadStarted
void BrowserView::onLoadStarted () protected slot
References Gui::getMainWindow(), Gui::SequencerBar::getProgressBar(), Gui::SequencerBar::instance(), and Gui::MainWindow::showMessage().
onMsg()
bool BrowserView::onMsg (const char * pMsg, const char ** ppReturn) virtual
Runs the action specified by pMsg.
Reimplemented from Gui::MDIView.
References WebGui::UrlWidget::display(), and stop().
onOpenLinkInExternalBrowser
void BrowserView::onOpenLinkInExternalBrowser (const QUrl & url) protected slot
References url().
onOpenLinkInNewWindow
void BrowserView::onOpenLinkInNewWindow (const QUrl & url) protected slot
References Gui::MainWindow::addWindow(), Gui::getMainWindow(), Gui::MainWindow::setActiveWindow(), and url().
onUnsupportedContent
void BrowserView::onUnsupportedContent (QNetworkReply * reply) protected slot
References Gui::Dialog::DownloadManager::download(), and Gui::Dialog::DownloadManager::getInstance().
onUpdateBrowserActions
void BrowserView::onUpdateBrowserActions () protected slot
References Gui::CommandManager::getCommandByName(), and Gui::Command::testActive().
onViewSource
void BrowserView::onViewSource (const QUrl & url) protected slot
References Gui::MainWindow::addWindow(), Gui::getMainWindow(), and url().
setHtml()
void BrowserView::setHtml (const QString & HtmlCode, const QUrl & BaseUrl)
References stop().
Referenced by WebGui::BrowserViewPy::setHtml().
stop()
void BrowserView::stop (void)
Referenced by ArchPanel.NestTaskPanel::accept(), load(), onMsg(), ArchPanel.NestTaskPanel::reject(), setHtml(), WebGui::BrowserViewPy::stop(), and urlFilter().
url()
QUrl BrowserView::url () const
Referenced by WebGui::UrlWidget::display(), addonmanager_macro.Macro::fill_details_from_wiki(), load(), onDownloadRequested(), onLinkHovered(), onOpenLinkInExternalBrowser(), onOpenLinkInNewWindow(), onViewSource(), Addon.Addon::set_metadata(), Addon.Addon::to_cache(), WebGui::BrowserViewPy::url(), urlFilter(), and Addon.Addon::verify_url_and_branch().
urlFilter
void BrowserView::urlFilter (const QUrl & url) protected slot
References Base::Tools::escapeEncodeFilename(), Gui::getMainWindow(), Gui::Command::Gui, load(), App::Document::PartialRestore, App::Document::RestoreError, stop(), and url().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Web/Gui/BrowserView.h
FreeCAD/src/Mod/Web/Gui/BrowserView.cpp