FreeCAD: exportIFCStructuralTools Namespace Reference
exportIFCStructuralTools Namespace Reference
Functions
def associates (ifcfile, aobj, sobj)
def createStructuralContext (ifcfile)
def createStructuralCurve (ifcfile, ifcbin, curve)
def createStructuralGroup (ifcfile)
def createStructuralMember (ifcfile, ifcbin, obj)
def createStructuralNode (ifcfile, ifcbin, point)
def getStructuralContext (ifcfile)
def setup (ifcfile, ifcbin, scale)
Variables
bool ALLOW_LINEAR_OBJECTS = True
float scaling = 1.0
dictionary structural_curves = {}
dictionary structural_nodes = {}
Function Documentation
associates()
def exportIFCStructuralTools.associates (ifcfile, aobj, sobj)
Associates an arch object with a struct object
Referenced by exportIFC.export().
createStructuralContext()
def exportIFCStructuralTools.createStructuralContext (ifcfile)
Creates an additional geometry context for structural objects. Returns the new context
Referenced by setup().
createStructuralCurve()
def exportIFCStructuralTools.createStructuralCurve (ifcfile, ifcbin, curve)
Creates a structural connection for a curve
References getStructuralContext().
Referenced by createStructuralMember().
createStructuralGroup()
def exportIFCStructuralTools.createStructuralGroup (ifcfile)
Assigns all structural objects found in the file to the structural model
Referenced by exportIFC.export().
createStructuralMember()
def exportIFCStructuralTools.createStructuralMember (ifcfile, ifcbin, obj)
Creates a structural member if possible. Returns the member
References createStructuralCurve(), createStructuralNode(), and getStructuralContext().
Referenced by exportIFC.export().
createStructuralNode()
def exportIFCStructuralTools.createStructuralNode (ifcfile, ifcbin, point)
Creates a connection node at the given point
References getStructuralContext().
Referenced by createStructuralMember().
getStructuralContext()
def exportIFCStructuralTools.getStructuralContext (ifcfile)
Returns the structural context from the file
Referenced by createStructuralCurve(), createStructuralMember(), and createStructuralNode().
setup()
def exportIFCStructuralTools.setup (ifcfile, ifcbin, scale)
Creates all the needed setup for structural model.
References createStructuralContext().
Referenced by exportIFC.export().
Variable Documentation
ALLOW_LINEAR_OBJECTS
bool exportIFCStructuralTools.ALLOW_LINEAR_OBJECTS = True
scaling
float exportIFCStructuralTools.scaling = 1.0
structural_curves
dictionary exportIFCStructuralTools.structural_curves = {}
structural_nodes
dictionary exportIFCStructuralTools.structural_nodes = {}