FreeCAD: Raytracing::PovTools Class Reference
Raytracing::PovTools Class Reference
#include <PovTools.h>
Static Public Member Functions
static std::string getCamera (const CamDef &Cam, int width=800, int height=600)
returns the given camera position as povray defines in a file
static void transferToArray (const TopoDS_Face &aFace, gp_Vec **vertices, gp_Vec **vertexnormals, long **cons, int &nbNodesInFace, int &nbTriInFace)
static void writeCamera (const char *FileName, const CamDef &Cam)
writes the given camera position as povray defines in a file
static void writeCameraVec (const char *FileName, const std::vector< CamDef > &CamVec)
writes the given camera positions as povray defines in a file
static void writeData (const char *FileName, const char *PartName, const Data::ComplexGeoData *, float fMeshDeviation=0.1)
write a given shape as povray file to disk
static void writeShape (const char *FileName, const char *PartName, const TopoDS_Shape &Shape, float fMeshDeviation=0.1)
write a given shape as povray file to disk
static void writeShape (std::ostream &out, const char *PartName, const TopoDS_Shape &Shape, float fMeshDeviation=0.1)
write a given shape as povray in a stream
static void writeShapeCSV (const char *FileName, const TopoDS_Shape &Shape, float fMeshDeviation, float fLength)
write a given shape as points and normal Vectors in a comma separated format
Member Function Documentation
getCamera()
std::string PovTools::getCamera (const CamDef & Cam, int width = 800, int height = 600) static
returns the given camera position as povray defines in a file
References Raytracing::CamDef::CamPos, Raytracing::CamDef::LookAt, and Raytracing::CamDef::Up.
transferToArray()
void PovTools::transferToArray (const TopoDS_Face & aFace, gp_Vec ** vertices, gp_Vec ** vertexnormals, long ** cons, int & nbNodesInFace, int & nbTriInFace) static
References Base::Console(), Base::ConsoleSingleton::Log(), and draftgeoutils.general::v1().
Referenced by Raytracing::LuxTools::writeShape().
writeCamera()
void PovTools::writeCamera (const char * FileName, const CamDef & Cam) static
writes the given camera position as povray defines in a file
Referenced by ArchBuildingPart.ViewProviderBuildingPart::setupContextMenu(), and draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::setupContextMenu().
writeCameraVec()
void PovTools::writeCameraVec (const char * FileName, const std::vector< CamDef > & CamVec) static
writes the given camera positions as povray defines in a file
writeData()
void PovTools::writeData (const char * FileName, const char * PartName, const Data::ComplexGeoData * data, float fMeshDeviation = 0.1) static
write a given shape as povray file to disk
writeShape() [1/2]
void PovTools::writeShape (const char * FileName, const char * PartName, const TopoDS_Shape & Shape, float fMeshDeviation = 0.1) static
write a given shape as povray file to disk
Referenced by Raytracing::RayFeature::execute().
writeShape() [2/2]
void PovTools::writeShape (std::ostream & out, const char * PartName, const TopoDS_Shape & Shape, float fMeshDeviation = 0.1) static
write a given shape as povray in a stream
References Base::Console(), Base::ConsoleSingleton::Log(), and Base::SequencerLauncher::next().
writeShapeCSV()
void PovTools::writeShapeCSV (const char * FileName, const TopoDS_Shape & Shape, float fMeshDeviation, float fLength) static
write a given shape as points and normal Vectors in a comma separated format
References Base::Console(), Base::ConsoleSingleton::Log(), and Base::SequencerLauncher::next().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Raytracing/App/PovTools.h
Sources/FreeCAD/src/Mod/Raytracing/App/PovTools.cpp