FreeCAD: PartDesignGui::TaskDlgBooleanParameters Class Reference
PartDesignGui::TaskDlgBooleanParameters Class Reference
simulation dialog for the TaskView
#include <TaskBooleanParameters.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void clicked (int)
is called by the framework if an button is clicked which has no accept or reject role
ViewProviderBoolean * getBooleanView () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
returns for Close and Help button
virtual bool isAllowedAlterDocument (void) const
is called by the framework if the user presses the help button
virtual void open ()
is called the TaskView when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgBooleanParameters (ViewProviderBoolean *BooleanView)
~TaskDlgBooleanParameters ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
tells the framework which buttons are wished for the dialog
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Protected Attributes
ViewProviderBoolean * BooleanView
TaskBooleanParameters * parameter
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
simulation dialog for the TaskView
Constructor & Destructor Documentation
TaskDlgBooleanParameters()
TaskDlgBooleanParameters::TaskDlgBooleanParameters (ViewProviderBoolean * BooleanView)
References BooleanView, Gui::TaskView::TaskDialog::Content, and parameter.
~TaskDlgBooleanParameters()
TaskDlgBooleanParameters::~TaskDlgBooleanParameters ()
Member Function Documentation
accept()
bool TaskDlgBooleanParameters::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References BooleanView, Gui::Command::commitCommand(), Gui::Command::Doc, PartDesignGui::TaskBooleanParameters::getBodies(), Gui::ViewProviderDocumentObject::getObject(), Gui::Command::getObjectCmd(), PartDesignGui::TaskBooleanParameters::getType(), Gui::Command::Gui, parameter, App::PropertyBool::setValue(), and Gui::ViewProviderDocumentObject::Visibility.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
clicked()
void TaskDlgBooleanParameters::clicked (int) virtual
is called by the framework if an button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
getBooleanView()
ViewProviderBoolean * PartDesignGui::TaskDlgBooleanParameters::getBooleanView () const
References BooleanView.
Referenced by PartDesignGui::ViewProviderBoolean::setEdit().
getStandardButtons()
virtual QDialogButtonBox::StandardButtons PartDesignGui::TaskDlgBooleanParameters::getStandardButtons (void) const virtual
returns for Close and Help button
Reimplemented from Gui::TaskView::TaskDialog.
isAllowedAlterDocument()
virtual bool PartDesignGui::TaskDlgBooleanParameters::isAllowedAlterDocument (void) const virtual
is called by the framework if the user presses the help button
Reimplemented from Gui::TaskView::TaskDialog.
open()
void TaskDlgBooleanParameters::open () virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
reject()
bool TaskDlgBooleanParameters::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Command::abortCommand(), Gui::Application::activeDocument(), BooleanView, Gui::ViewProviderDocumentObject::getObject(), Gui::Command::Gui, and Gui::Application::Instance.
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
Member Data Documentation
BooleanView
ViewProviderBoolean* PartDesignGui::TaskDlgBooleanParameters::BooleanView protected
Referenced by accept(), getBooleanView(), reject(), and TaskDlgBooleanParameters().
parameter
TaskBooleanParameters* PartDesignGui::TaskDlgBooleanParameters::parameter protected
Referenced by accept(), Mod.Test.Document.DocumentObserverCases.Observer::slotAbortTransaction(), Mod.Test.Document.DocumentObserverCases.Observer::slotActivateDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotActivateDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotAddedDynamicExtension(), Mod.Test.Document.DocumentObserverCases.Observer::slotAppendDynamicProperty(), Mod.Test.Document.DocumentObserverCases.Observer::slotBeforeAddingDynamicExtension(), Mod.Test.Document.DocumentObserverCases.Observer::slotBeforeChangeDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotBeforeChangeObject(), Mod.Test.Document.DocumentObserverCases.Observer::slotChangedDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotChangedObject(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotChangedObject(), Mod.Test.Document.DocumentObserverCases.Observer::slotChangePropertyEditor(), Mod.Test.Document.DocumentObserverCases.Observer::slotCommitTransaction(), Mod.Test.Document.DocumentObserverCases.Observer::slotCreatedDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotCreatedDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotCreatedObject(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotCreatedObject(), Mod.Test.Document.DocumentObserverCases.Observer::slotDeletedDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotDeletedDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotDeletedObject(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotDeletedObject(), Mod.Test.Document.DocumentObserverCases.Observer::slotFinishSaveDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotInEdit(), Mod.Test.Document.DocumentObserverCases.Observer::slotOpenTransaction(), Mod.Test.Document.DocumentObserverCases.Observer::slotRecomputedDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotRecomputedObject(), Mod.Test.Document.DocumentObserverCases.Observer::slotRedoDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotRelabelDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotRelabelDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotRemoveDynamicProperty(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotRenameDocument(), Mod.Test.Document.DocumentObserverCases.GuiObserver::slotResetEdit(), Mod.Test.Document.DocumentObserverCases.Observer::slotStartSaveDocument(), Mod.Test.Document.DocumentObserverCases.Observer::slotUndoDocument(), and TaskDlgBooleanParameters().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/PartDesign/Gui/TaskBooleanParameters.h
FreeCAD/src/Mod/PartDesign/Gui/TaskBooleanParameters.cpp