FreeCAD: Part::Geom2dLineSegment Class Reference
Part::Geom2dLineSegment Class Reference
#include <Geometry2d.h>
Public Member Functions
virtual Geometry2d * clone (void) const
returns a cloned object
Geom2dLineSegment ()
Base::Vector2d getEndPoint () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
Base::Vector2d getStartPoint () const
const Handle (Geom2d_Geometry) &handle() const
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
void setHandle (const Handle(Geom2d_TrimmedCurve)&)
void setPoints (const Base::Vector2d &p1, const Base::Vector2d &p2)
virtual ~Geom2dLineSegment ()
Public Member Functions inherited from Part::Geom2dCurve
bool closestParameter (const Base::Vector2d &point, double &u) const
bool closestParameterToBasicCurve (const Base::Vector2d &point, double &u) const
Base::Vector2d firstDerivativeAtParameter (double u) const
Geom2dCurve ()
bool normal (double u, gp_Dir2d &dir) const
Base::Vector2d pointAtParameter (double u) const
Base::Vector2d secondDerivativeAtParameter (double u) const
bool tangent (double u, gp_Dir2d &) const
virtual TopoDS_Shape toShape () const
virtual ~Geom2dCurve ()
Public Member Functions inherited from Part::Geometry2d
virtual ~Geometry2d ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Protected Member Functions inherited from Part::Geometry2d
Geometry2d ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
Geom2dLineSegment()
Geom2dLineSegment::Geom2dLineSegment ()
~Geom2dLineSegment()
Geom2dLineSegment::~Geom2dLineSegment () virtual
Member Function Documentation
clone()
virtual Geometry2d* Part::Geom2dLineSegment::clone (void) const virtual
returns a cloned object
Implements Part::Geometry2d.
Referenced by ArchPanel.CommandPanelSheet::Activated(), and Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated().
getEndPoint()
Base::Vector2d Part::Geom2dLineSegment::getEndPoint () const
getMemSize()
unsigned int Geom2dLineSegment::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Part::Geometry2d.
getPyObject()
PyObject * Geom2dLineSegment::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
References draftmake.make_clone::clone.
getStartPoint()
Base::Vector2d Part::Geom2dLineSegment::getStartPoint () const
Handle()
const Part::Geom2dLineSegment::Handle (Geom2d_Geometry) const & virtual
Implements Part::Geometry2d.
Restore()
void Geom2dLineSegment::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Part::Geometry2d.
References Base::XMLReader::getAttributeAsFloat(), Base::XMLReader::readElement(), and Part::Geometry2d::Restore().
Save()
void Geom2dLineSegment::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from Part::Geometry2d.
References Base::Writer::ind(), Part::Geometry2d::Save(), Base::Writer::Stream(), Base::Vector2d::x, and Base::Vector2d::y.
setHandle()
void Geom2dLineSegment::setHandle (const Handle(Geom2d_TrimmedCurve)& c)
Referenced by Part::Geom2dTrimmedCurve::getPyObject().
setPoints()
void Part::Geom2dLineSegment::setPoints (const Base::Vector2d & p1, const Base::Vector2d & p2)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/App/Geometry2d.h
Sources/FreeCAD/src/Mod/Part/App/Geometry2d.cpp