FreeCAD: PathTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator Class Reference
PathTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator Class Reference
Public Member Functions
def test00 (self)
def test01 (self)
def test02 (self)
def test03 (self)
def test04 (self)
def test10 (self)
def test11 (self)
Public Member Functions inherited from PathTests.PathTestUtils.PathTestBase
def assertArc (self, edge, pt1, pt2, direction="CW")
def assertCircle (self, edge, pt, r)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertCommandEqual (self, c1, c2)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertEdgeShapesMatch (self, e1, e2)
def assertEqualLocale (self, s1, s2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertPlacement (self, p1, p2)
def assertPointsMatch (self, pts0, pts1)
def assertRoughly (self, f1, f2, error=0.00001)
Detailed Description
Test thread milling generator.
Member Function Documentation
test00()
def PathTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator.test00 (self)
Verify thread commands for a single thread
References PathTests.PathTestUtils.PathTestBase.assertCoincide().
Referenced by PathTests.TestPathTool.TestPathTool.test01(), PathTests.TestPathToolController.TestPathToolController.test01(), PathTests.TestPathTooltable.TestPathTooltable.test01(), PathTests.TestPathTool.TestPathTool.test02(), and PathTests.TestPathTooltable.TestPathTooltable.test02().
test01()
def PathTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator.test01 (self)
Verify thread commands for a thwo threads
References PathTests.PathTestUtils.PathTestBase.assertCoincide().
test02()
def PathTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator.test02 (self)
Verify thread commands for a one and a half threads
References PathTests.PathTestUtils.PathTestBase.assertCoincide().
test03()
def PathTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator.test03 (self)
Verify thread commands for a one and 3 quarter threads
References PathTests.PathTestUtils.PathTestBase.assertCoincide().
test04()
def PathTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator.test04 (self)
Verify thread commands for a one and 3 quarter threads - CCW
References PathTests.PathTestUtils.PathTestBase.assertCoincide().
test10()
def PathTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator.test10 (self)
Verify lead in/out commands for a single thread
References PathTests.PathTestUtils.PathTestBase.assertCoincide().
test11()
def PathTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator.test11 (self)
Verify lead in/out commands for one and a half threads
References PathTests.PathTestUtils.PathTestBase.assertCoincide().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Path/PathTests/TestPathThreadMillingGenerator.py