FreeCAD: Ui_DownloadItem Class Reference
Ui_DownloadItem Class Reference
#include <ui_DownloadItem.h>
Public Member Functions
void retranslateUi (QWidget *DownloadItem)
void setupUi (QWidget *DownloadItem)
Public Attributes
SqueezeLabel * downloadInfoLabel
QLabel * fileIcon
SqueezeLabel * fileNameLabel
QHBoxLayout * horizontalLayout
QPushButton * openButton
QProgressBar * progressBar
QPushButton * stopButton
QPushButton * tryAgainButton
QVBoxLayout * verticalLayout
QVBoxLayout * verticalLayout_2
QSpacerItem * verticalSpacer
QSpacerItem * verticalSpacer_2
Member Function Documentation
retranslateUi()
void Ui_DownloadItem::retranslateUi (QWidget * DownloadItem)
References downloadInfoLabel, fileIcon, fileNameLabel, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Ui_DownloadItem::setupUi (QWidget * DownloadItem)
References downloadInfoLabel, fileIcon, fileNameLabel, horizontalLayout, openButton, progressBar, retranslateUi(), stopButton, tryAgainButton, verticalLayout, verticalLayout_2, verticalSpacer, and verticalSpacer_2.
Referenced by Gui::Dialog::DownloadItem::DownloadItem().
Member Data Documentation
downloadInfoLabel
SqueezeLabel* Ui_DownloadItem::downloadInfoLabel
Referenced by Gui::Dialog::DownloadItem::DownloadItem(), retranslateUi(), and setupUi().
fileIcon
QLabel* Ui_DownloadItem::fileIcon
Referenced by retranslateUi(), and setupUi().
fileNameLabel
SqueezeLabel* Ui_DownloadItem::fileNameLabel
Referenced by retranslateUi(), and setupUi().
horizontalLayout
QHBoxLayout* Ui_DownloadItem::horizontalLayout
Referenced by setupUi().
openButton
QPushButton* Ui_DownloadItem::openButton
Referenced by Gui::Dialog::DownloadItem::DownloadItem(), and setupUi().
progressBar
QProgressBar* Ui_DownloadItem::progressBar
Referenced by Gui::Dialog::DownloadItem::downloading(), Gui::Dialog::DownloadItem::DownloadItem(), Mod.Test.unittestgui.TkTestRunner::notifyTestFinished(), and setupUi().
stopButton
QPushButton* Ui_DownloadItem::stopButton
Referenced by Gui::Dialog::DownloadItem::downloadedSuccessfully(), Gui::Dialog::DownloadItem::DownloadItem(), and setupUi().
tryAgainButton
QPushButton* Ui_DownloadItem::tryAgainButton
Referenced by Gui::Dialog::DownloadItem::downloadedSuccessfully(), Gui::Dialog::DownloadItem::DownloadItem(), and setupUi().
verticalLayout
QVBoxLayout* Ui_DownloadItem::verticalLayout
Referenced by setupUi().
verticalLayout_2
QVBoxLayout* Ui_DownloadItem::verticalLayout_2
Referenced by setupUi().
verticalSpacer
QSpacerItem* Ui_DownloadItem::verticalSpacer
Referenced by setupUi().
verticalSpacer_2
QSpacerItem* Ui_DownloadItem::verticalSpacer_2
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_DownloadItem.h