FreeCAD: ExpressionCompleterModel Class Reference
ExpressionCompleterModel Class Reference
Classes
union Info
Public Member Functions
int columnCount (const QModelIndex &) const
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
ExpressionCompleterModel (QObject *parent, const App::DocumentObject *obj, bool noProperty)
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
QModelIndex parent (const QModelIndex &index) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
void setDocumentObject (const App::DocumentObject *obj)
void setNoProperty (bool enabled)
Static Public Member Functions
static Info getInfo (const QModelIndex &index)
static void * infoId (const Info &info)
Constructor & Destructor Documentation
ExpressionCompleterModel()
ExpressionCompleterModel::ExpressionCompleterModel (QObject * parent, const App::DocumentObject * obj, bool noProperty)
Member Function Documentation
columnCount()
int ExpressionCompleterModel::columnCount (const QModelIndex &) const
data()
QVariant ExpressionCompleterModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
Referenced by Mod.Show.mTempoVis.TempoVis::activateWorkbench(), Mod.Show.SceneDetail.SceneDetail::apply_data(), importIFClegacy.IfcSchema::capitalize(), Mod.Show.mTempoVis.TempoVis::forget(), Mod.Show.mTempoVis.TempoVis::forgetDetail(), Mod.Show.mTempoVis.TempoVis::has(), ArchSchedule.CommandArchSchedule::IsActive(), importIFClegacy.IfcSchema::readEntities(), importIFClegacy.IfcSchema::readTypes(), Mod.Show.mTempoVis.TempoVis::restore(), Mod.Show.mTempoVis.TempoVis::save(), Mod.Show.mTempoVis.TempoVis::stored_val(), FeaturePython.ViewProviderOctahedron::updateData(), and Dice3DS.dom3ds.UndefinedChunk::write().
getInfo()
static Info ExpressionCompleterModel::getInfo (const QModelIndex & index) static
References ExpressionCompleterModel::Info::d, and ExpressionCompleterModel::Info::doc.
index()
QModelIndex ExpressionCompleterModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::addSegment(), Dice3DS.dom3ds.FileLikeBuffer::advance(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::begin(), Spreadsheet_legacy.MathParser::getValue(), Spreadsheet_legacy.MathParser::hasNext(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::interval(), PathScripts.PathJobDlg.JobCreate::item1ValueChanged(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::length(), Spreadsheet_legacy.MathParser::parseAddition(), Spreadsheet_legacy.MathParser::parseMultiplication(), Spreadsheet_legacy.MathParser::parseNegative(), Spreadsheet_legacy.MathParser::parseNumber(), Spreadsheet_legacy.MathParser::parseParenthesis(), Spreadsheet_legacy.MathParser::parseVariable(), Spreadsheet_legacy.MathParser::peek(), Dice3DS.dom3ds.FileLikeBuffer::read(), Dice3DS.dom3ds.FileLikeBuffer::read_fbuf(), Dice3DS.dom3ds.FileLikeBuffer::read_rest(), Dice3DS.dom3ds.FileLikeBuffer::read_to_nul(), Dice3DS.dom3ds.FileLikeBuffer::room_for_chunks(), Dice3DS.dom3ds.FileLikeBuffer::seek(), PathScripts.PathJobDlg.JobCreate::setupColumnEditor(), Spreadsheet_legacy.MathParser::skipWhitespace(), Dice3DS.dom3ds.FileLikeBuffer::tell(), automotive_design.index_expression::wr1(), and automotive_design.index_expression::wr2().
infoId()
static void* ExpressionCompleterModel::infoId (const Info & info) static
References ExpressionCompleterModel::Info::d32, ExpressionCompleterModel::Info::doc, ExpressionCompleterModel::Info::obj, and ExpressionCompleterModel::Info::ptr.
parent()
QModelIndex ExpressionCompleterModel::parent (const QModelIndex & index) const
References ExpressionCompleterModel::Info::d, ExpressionCompleterModel::Info::doc, and ExpressionCompleterModel::Info::obj.
Referenced by PathScripts.PathSimulatorGui.CAMSimTaskUi::accept(), Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium(), PathScripts.PathSimulatorGui.CAMSimTaskUi::reject(), and PathScripts.PathOpGui.TaskPanelPage::setParent().
rowCount()
int ExpressionCompleterModel::rowCount (const QModelIndex & parent = QModelIndex()) const
setDocumentObject()
void ExpressionCompleterModel::setDocumentObject (const App::DocumentObject * obj)
setNoProperty()
void ExpressionCompleterModel::setNoProperty (bool enabled)
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/ExpressionCompleter.cpp