FreeCAD: SMESHDS_Script Class Reference
SMESHDS_Script Class Reference
#include <SMESHDS_Script.hxx>
Public Member Functions
void Add0DElement (int New0DElementID, int idnode)
void AddBall (int NewBallID, int node, double diameter)
void AddEdge (int NewEdgeID, int idnode1, int idnode2)
void AddEdge (int NewEdgeID, int n1, int n2, int n12)
void AddFace (int NewFaceID, int idnode1, int idnode2, int idnode3)
void AddFace (int NewFaceID, int idnode1, int idnode2, int idnode3, int idnode4)
void AddFace (int NewFaceID, int n1, int n2, int n3, int n12, int n23, int n31)
void AddFace (int NewFaceID, int n1, int n2, int n3, int n12, int n23, int n31, int nCenter)
void AddFace (int NewFaceID, int n1, int n2, int n3, int n4, int n12, int n23, int n34, int n41)
void AddFace (int NewFaceID, int n1, int n2, int n3, int n4, int n12, int n23, int n34, int n41, int nCenter)
void AddNode (int NewNodeID, double x, double y, double z)
void AddPolygonalFace (const int NewFaceID, const std::vector< int > &nodes_ids)
void AddPolyhedralVolume (const int NewVolID, const std::vector< int > &nodes_ids, const std::vector< int > &quantities)
void AddQuadPolygonalFace (const int NewFaceID, const std::vector< int > &nodes_ids)
void AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4)
void AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4, int idnode5)
void AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6)
void AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6, int idnode7, int idnode8)
void AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6, int idnode7, int idnode8, int idnode9, int idnode10, int idnode11, int idnode12)
void AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n12, int n23, int n31, int n14, int n24, int n34)
void AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n5, int n12, int n23, int n34, int n41, int n15, int n25, int n35, int n45)
void AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n5, int n6, int n12, int n23, int n31, int n45, int n56, int n64, int n14, int n25, int n36)
void AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n12, int n23, int n34, int n41, int n56, int n67, int n78, int n85, int n15, int n26, int n37, int n48)
void AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n12, int n23, int n34, int n41, int n56, int n67, int n78, int n85, int n15, int n26, int n37, int n48, int n1234, int n1256, int n2367, int n3478, int n1458, int n5678, int nCenter)
void ChangeElementNodes (int ElementID, int nodes[], int nbnodes)
void ChangePolyhedronNodes (const int ElementID, const std::vector< int > &nodes_ids, const std::vector< int > &quantities)
void Clear ()
void ClearMesh ()
const std::list< SMESHDS_Command * > & GetCommands ()
bool IsModified ()
void MoveNode (int NewNodeID, double x, double y, double z)
void RemoveElement (int ElementID)
void RemoveNode (int NodeID)
void Renumber (const bool isNodes, const int startID, const int deltaID)
void SetModified (bool theModified)
SMESHDS_Script (bool theIsEmbeddedMode)
~SMESHDS_Script ()
Constructor & Destructor Documentation
SMESHDS_Script()
SMESHDS_Script::SMESHDS_Script (bool theIsEmbeddedMode)
~SMESHDS_Script()
SMESHDS_Script::~SMESHDS_Script ()
References Clear().
Member Function Documentation
Add0DElement()
void SMESHDS_Script::Add0DElement (int New0DElementID, int idnode)
References SMESHDS_Command::Add0DElement().
Referenced by SMESHDS_Mesh::Add0DElement(), and SMESHDS_Mesh::Add0DElementWithID().
AddBall()
void SMESHDS_Script::AddBall (int NewBallID, int node, double diameter)
References SMESHDS_Command::AddBall().
Referenced by SMESHDS_Mesh::AddBall(), and SMESHDS_Mesh::AddBallWithID().
AddEdge() [1/2]
void SMESHDS_Script::AddEdge (int NewEdgeID, int idnode1, int idnode2)
References SMESHDS_Command::AddEdge().
Referenced by SMESHDS_Mesh::AddEdge(), and SMESHDS_Mesh::AddEdgeWithID().
AddEdge() [2/2]
void SMESHDS_Script::AddEdge (int NewEdgeID, int n1, int n2, int n12)
References SMESHDS_Command::AddEdge().
AddFace() [1/6]
void SMESHDS_Script::AddFace (int NewFaceID, int idnode1, int idnode2, int idnode3)
References SMESHDS_Command::AddFace().
Referenced by SMESHDS_Mesh::AddFace(), and SMESHDS_Mesh::AddFaceWithID().
AddFace() [2/6]
void SMESHDS_Script::AddFace (int NewFaceID, int idnode1, int idnode2, int idnode3, int idnode4)
References SMESHDS_Command::AddFace().
AddFace() [3/6]
void SMESHDS_Script::AddFace (int NewFaceID, int n1, int n2, int n3, int n12, int n23, int n31)
References SMESHDS_Command::AddFace().
AddFace() [4/6]
void SMESHDS_Script::AddFace (int NewFaceID, int n1, int n2, int n3, int n12, int n23, int n31, int nCenter)
References SMESHDS_Command::AddFace().
AddFace() [5/6]
void SMESHDS_Script::AddFace (int NewFaceID, int n1, int n2, int n3, int n4, int n12, int n23, int n34, int n41)
References SMESHDS_Command::AddFace().
AddFace() [6/6]
void SMESHDS_Script::AddFace (int NewFaceID, int n1, int n2, int n3, int n4, int n12, int n23, int n34, int n41, int nCenter)
References SMESHDS_Command::AddFace().
AddNode()
void SMESHDS_Script::AddNode (int NewNodeID, double x, double y, double z)
References SMESHDS_Command::AddNode().
Referenced by SMESHDS_Mesh::AddNode(), and SMESHDS_Mesh::AddNodeWithID().
AddPolygonalFace()
void SMESHDS_Script::AddPolygonalFace (const int NewFaceID, const std::vector< int > & nodes_ids)
References SMESHDS_Command::AddPolygonalFace().
Referenced by SMESHDS_Mesh::AddPolygonalFace(), and SMESHDS_Mesh::AddPolygonalFaceWithID().
AddPolyhedralVolume()
void SMESHDS_Script::AddPolyhedralVolume (const int NewVolID, const std::vector< int > & nodes_ids, const std::vector< int > & quantities)
References SMESHDS_Command::AddPolyhedralVolume().
Referenced by SMESHDS_Mesh::AddPolyhedralVolume(), and SMESHDS_Mesh::AddPolyhedralVolumeWithID().
AddQuadPolygonalFace()
void SMESHDS_Script::AddQuadPolygonalFace (const int NewFaceID, const std::vector< int > & nodes_ids)
References SMESHDS_Command::AddQuadPolygonalFace().
Referenced by SMESHDS_Mesh::AddQuadPolygonalFace(), and SMESHDS_Mesh::AddQuadPolygonalFaceWithID().
AddVolume() [1/10]
void SMESHDS_Script::AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4)
References SMESHDS_Command::AddVolume().
Referenced by SMESHDS_Mesh::AddVolume(), and SMESHDS_Mesh::AddVolumeWithID().
AddVolume() [2/10]
void SMESHDS_Script::AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4, int idnode5)
References SMESHDS_Command::AddVolume().
AddVolume() [3/10]
void SMESHDS_Script::AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6)
References SMESHDS_Command::AddVolume().
AddVolume() [4/10]
void SMESHDS_Script::AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6, int idnode7, int idnode8)
References SMESHDS_Command::AddVolume().
AddVolume() [5/10]
void SMESHDS_Script::AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6, int idnode7, int idnode8, int idnode9, int idnode10, int idnode11, int idnode12)
References SMESHDS_Command::AddVolume().
AddVolume() [6/10]
void SMESHDS_Script::AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n12, int n23, int n31, int n14, int n24, int n34)
References SMESHDS_Command::AddVolume().
AddVolume() [7/10]
void SMESHDS_Script::AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n5, int n12, int n23, int n34, int n41, int n15, int n25, int n35, int n45)
References SMESHDS_Command::AddVolume().
AddVolume() [8/10]
void SMESHDS_Script::AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n5, int n6, int n12, int n23, int n31, int n45, int n56, int n64, int n14, int n25, int n36)
References SMESHDS_Command::AddVolume().
AddVolume() [9/10]
void SMESHDS_Script::AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n12, int n23, int n34, int n41, int n56, int n67, int n78, int n85, int n15, int n26, int n37, int n48)
References SMESHDS_Command::AddVolume().
AddVolume() [10/10]
void SMESHDS_Script::AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n12, int n23, int n34, int n41, int n56, int n67, int n78, int n85, int n15, int n26, int n37, int n48, int n1234, int n1256, int n2367, int n3478, int n1458, int n5678, int nCenter)
References SMESHDS_Command::AddVolume().
ChangeElementNodes()
void SMESHDS_Script::ChangeElementNodes (int ElementID, int nodes[], int nbnodes)
References SMESHDS_Command::ChangeElementNodes().
Referenced by SMESHDS_Mesh::ChangeElementNodes().
ChangePolyhedronNodes()
void SMESHDS_Script::ChangePolyhedronNodes (const int ElementID, const std::vector< int > & nodes_ids, const std::vector< int > & quantities)
References SMESHDS_Command::ChangePolyhedronNodes().
Referenced by SMESHDS_Mesh::ChangePolyhedronNodes().
Clear()
void SMESHDS_Script::Clear ()
Referenced by ClearMesh(), SMESHDS_Mesh::ClearScript(), and ~SMESHDS_Script().
ClearMesh()
void SMESHDS_Script::ClearMesh ()
References Clear().
Referenced by SMESHDS_Mesh::ClearMesh().
GetCommands()
const list< SMESHDS_Command * > & SMESHDS_Script::GetCommands ()
IsModified()
bool SMESHDS_Script::IsModified ()
MoveNode()
void SMESHDS_Script::MoveNode (int NewNodeID, double x, double y, double z)
References SMESHDS_Command::MoveNode().
Referenced by SMESHDS_Mesh::MoveNode().
RemoveElement()
void SMESHDS_Script::RemoveElement (int ElementID)
References SMESHDS_Command::RemoveElement().
Referenced by SMESHDS_Mesh::RemoveElement(), and SMESHDS_Mesh::RemoveFreeElement().
RemoveNode()
void SMESHDS_Script::RemoveNode (int NodeID)
References SMESHDS_Command::RemoveNode().
Referenced by SMESHDS_Mesh::RemoveFreeNode(), and SMESHDS_Mesh::RemoveNode().
Renumber()
void SMESHDS_Script::Renumber (const bool isNodes, const int startID, const int deltaID)
References SMESHDS_Command::Renumber().
SetModified()
void SMESHDS_Script::SetModified (bool theModified)
Referenced by SMESHDS_Mesh::compactMesh().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESHDS_Script.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESHDS/SMESHDS_Script.cpp