FreeCAD: Path::TooltablePy Class Reference
Path::TooltablePy Class Reference
The python export class for Tooltable.
#include <TooltablePy.h>
Public Types
typedef Tooltable * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
TooltablePy (Tooltable *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of TooltablePy.
static PyMethodDef Methods []
Methods structure of TooltablePy.
static PyTypeObject Type
Type structure of TooltablePy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~TooltablePy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * addTools (PyObject *args)
implementer for the addTools() method
PyObject * getTool (PyObject *args)
implementer for the getTool() method
PyObject * setTool (PyObject *args)
implementer for the setTool() method
PyObject * deleteTool (PyObject *args)
implementer for the deleteTool() method
PyObject * setFromTemplate (PyObject *args)
implementer for the setFromTemplate() method
PyObject * templateAttrs (PyObject *args)
implementer for the templateAttrs() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_addTools (PyObject *self, PyObject *args)
callback for the addTools() method
static PyObject * staticCallback_getTool (PyObject *self, PyObject *args)
callback for the getTool() method
static PyObject * staticCallback_setTool (PyObject *self, PyObject *args)
callback for the setTool() method
static PyObject * staticCallback_deleteTool (PyObject *self, PyObject *args)
callback for the deleteTool() method
static PyObject * staticCallback_setFromTemplate (PyObject *self, PyObject *args)
callback for the setFromTemplate() method
static PyObject * staticCallback_templateAttrs (PyObject *self, PyObject *args)
callback for the templateAttrs() method
callbacks and implementers for the python object attributes
Py::String getName (void) const
getter for the Name attribute
void setName (Py::String arg)
setter for the Name attribute
Py::Int getVersion (void) const
getter for the Version attribute
void setVersion (Py::Int arg)
setter for the Version attribute
Py::Dict getTools (void) const
getter for the Tools attribute
void setTools (Py::Dict arg)
setter for the Tools attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Tooltable * getTooltablePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getName (PyObject *self, void *closure)
getter callback for the Name attribute
static int staticCallback_setName (PyObject *self, PyObject *value, void *closure)
setter callback for the Name attribute
static PyObject * staticCallback_getVersion (PyObject *self, void *closure)
getter callback for the Version attribute
static int staticCallback_setVersion (PyObject *self, PyObject *value, void *closure)
setter callback for the Version attribute
static PyObject * staticCallback_getTools (PyObject *self, void *closure)
getter callback for the Tools attribute
static int staticCallback_setTools (PyObject *self, PyObject *value, void *closure)
setter callback for the Tools attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Tooltable.
Member Typedef Documentation
PointerType
typedef Tooltable* Path::TooltablePy::PointerType
Constructor & Destructor Documentation
~TooltablePy()
TooltablePy::~TooltablePy () protected
TooltablePy()
TooltablePy::TooltablePy (Tooltable * pcObject, PyTypeObject * T = &Type)
Referenced by copy(), and PyMake().
Member Function Documentation
addTools()
PyObject * TooltablePy::addTools (PyObject * args)
implementer for the addTools() method
References Path::Tooltable::addTool(), Base::BaseExceptionFreeCADError, getTooltablePtr(), and Path::ToolPy::Type.
Referenced by staticCallback_addTools().
copy()
PyObject * TooltablePy::copy (PyObject * args)
implementer for the copy() method
References getTooltablePtr(), and TooltablePy().
Referenced by staticCallback_copy().
deleteTool()
PyObject * TooltablePy::deleteTool (PyObject * args)
implementer for the deleteTool() method
References Base::BaseExceptionFreeCADError, Path::Tooltable::deleteTool(), and getTooltablePtr().
Referenced by staticCallback_deleteTool().
getCustomAttributes()
PyObject * TooltablePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getName()
Py::String TooltablePy::getName (void) const
getter for the Name attribute
References getTooltablePtr().
Referenced by staticCallback_getName().
getTool()
PyObject * TooltablePy::getTool (PyObject * args)
implementer for the getTool() method
References Base::BaseExceptionFreeCADError, Path::Tooltable::getTool(), and getTooltablePtr().
Referenced by staticCallback_getTool().
getTools()
Py::Dict TooltablePy::getTools (void) const
getter for the Tools attribute
References getTooltablePtr().
Referenced by staticCallback_getTools().
getTooltablePtr()
Tooltable * TooltablePy::getTooltablePtr (void) const
getter for the object handled by this class
Referenced by addTools(), copy(), deleteTool(), getName(), getTool(), getTools(), getVersion(), PyInit(), representation(), setName(), Path::PropertyTooltable::setPyObject(), setTool(), setTools(), setVersion(), and templateAttrs().
GetType()
virtual PyTypeObject* Path::TooltablePy::GetType (void) virtual
Reimplemented from Base::PersistencePy.
getVersion()
Py::Int TooltablePy::getVersion (void) const
getter for the Version attribute
References getTooltablePtr().
Referenced by staticCallback_getVersion().
PyInit()
int TooltablePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PersistencePy.
References Path::Tooltable::addTool(), getTooltablePtr(), setTools(), and Path::ToolPy::Type.
PyMake()
PyObject * TooltablePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References TooltablePy().
representation()
std::string TooltablePy::representation (void) const
References Path::Tooltable::getSize(), and getTooltablePtr().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int TooltablePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setFromTemplate()
PyObject * TooltablePy::setFromTemplate (PyObject * args)
implementer for the setFromTemplate() method
References setTools().
Referenced by staticCallback_setFromTemplate().
setName()
void TooltablePy::setName (Py::String arg)
setter for the Name attribute
References getTooltablePtr(), and Path::Tooltable::Name.
Referenced by staticCallback_setName().
setTool()
PyObject * TooltablePy::setTool (PyObject * args)
implementer for the setTool() method
References Base::BaseExceptionFreeCADError, getTooltablePtr(), Path::Tooltable::setTool(), and Path::ToolPy::Type.
Referenced by staticCallback_setTool().
setTools()
void TooltablePy::setTools (Py::Dict arg)
setter for the Tools attribute
References getTooltablePtr(), Path::ToolPy::setFromTemplate(), Path::Tooltable::setTool(), Path::Tooltable::Tools, and Path::ToolPy::Type.
Referenced by PyInit(), setFromTemplate(), and staticCallback_setTools().
setVersion()
void TooltablePy::setVersion (Py::Int arg)
setter for the Version attribute
References getTooltablePtr(), and Path::Tooltable::Version.
Referenced by staticCallback_setVersion().
staticCallback_addTools()
PyObject * TooltablePy::staticCallback_addTools (PyObject * self, PyObject * args) static
callback for the addTools() method
References addTools(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_copy()
PyObject * TooltablePy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copy(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_deleteTool()
PyObject * TooltablePy::staticCallback_deleteTool (PyObject * self, PyObject * args) static
callback for the deleteTool() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, deleteTool(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getName()
PyObject * TooltablePy::staticCallback_getName (PyObject * self, void * closure) static
getter callback for the Name attribute
References Base::BaseExceptionFreeCADError, getName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTool()
PyObject * TooltablePy::staticCallback_getTool (PyObject * self, PyObject * args) static
callback for the getTool() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getTool(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getTools()
PyObject * TooltablePy::staticCallback_getTools (PyObject * self, void * closure) static
getter callback for the Tools attribute
References Base::BaseExceptionFreeCADError, getTools(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVersion()
PyObject * TooltablePy::staticCallback_getVersion (PyObject * self, void * closure) static
getter callback for the Version attribute
References Base::BaseExceptionFreeCADError, getVersion(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setFromTemplate()
PyObject * TooltablePy::staticCallback_setFromTemplate (PyObject * self, PyObject * args) static
callback for the setFromTemplate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setFromTemplate(), and Base::PyObjectBase::startNotify().
staticCallback_setName()
int TooltablePy::staticCallback_setName (PyObject * self, PyObject * value, void * closure) static
setter callback for the Name attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setName().
staticCallback_setTool()
PyObject * TooltablePy::staticCallback_setTool (PyObject * self, PyObject * args) static
callback for the setTool() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setTool(), and Base::PyObjectBase::startNotify().
staticCallback_setTools()
int TooltablePy::staticCallback_setTools (PyObject * self, PyObject * value, void * closure) static
setter callback for the Tools attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setTools().
staticCallback_setVersion()
int TooltablePy::staticCallback_setVersion (PyObject * self, PyObject * value, void * closure) static
setter callback for the Version attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setVersion().
staticCallback_templateAttrs()
PyObject * TooltablePy::staticCallback_templateAttrs (PyObject * self, PyObject * args) static
callback for the templateAttrs() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and templateAttrs().
templateAttrs()
PyObject * TooltablePy::templateAttrs (PyObject * args)
implementer for the templateAttrs() method
References getTooltablePtr(), and Path::ToolPy::templateAttrs().
Referenced by staticCallback_templateAttrs().
Member Data Documentation
GetterSetter
PyGetSetDef TooltablePy::GetterSetter static
Initial value:
= {
    {"Name",
        (getter) staticCallback_getName,
        (setter) staticCallback_setName,
        "the name of this tool table",
        NULL
    },
    {"Version",
        (getter) staticCallback_getVersion,
        (setter) staticCallback_setVersion,
        "the version of this tooltable",
        NULL
    },
    {"Tools",
        (getter) staticCallback_getTools,
        (setter) staticCallback_setTools,
        "the dictionary of tools of this table",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of TooltablePy.
Methods
PyMethodDef TooltablePy::Methods static
Methods structure of TooltablePy.
Type
PyTypeObject TooltablePy::Type static
Type structure of TooltablePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), and Path::PropertyTooltable::setPyObject().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/TooltablePy.h
Sources/FreeCAD/src/Mod/Path/App/TooltablePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/TooltablePy.cpp