FreeCAD: VISCOUS_3D::_Curvature Struct Reference
VISCOUS_3D::_Curvature Struct Reference
Public Member Functions
double lenDelta (double len) const
double lenDeltaByDist (double dist) const
Static Public Member Functions
static _Curvature * New (double avgNormProj, double avgDist)
Detailed Description
Structure used to take into account surface curvature while smoothing
Member Function Documentation
lenDelta()
double VISCOUS_3D::_Curvature::lenDelta (double len) const
Referenced by VISCOUS_3D::_LayerEdge::Smooth().
lenDeltaByDist()
double VISCOUS_3D::_Curvature::lenDeltaByDist (double dist) const
References DraftVecUtils::dist().
Referenced by VISCOUS_3D::_LayerEdge::SmoothOnEdge().
New()
static _Curvature * VISCOUS_3D::_Curvature::New (double avgNormProj, double avgDist) static
Referenced by VISCOUS_3D::_SolidData::PrepareEdgesToSmoothOnFace(), and VISCOUS_3D::_LayerEdge::SetDataByNeighbors().
The documentation for this struct was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_ViscousLayers.cpp