FreeCAD: PartDesignGui::TaskExtrudeParameters Class Reference
PartDesignGui::TaskExtrudeParameters Class Reference
#include <TaskExtrudeParameters.h>
Public Types
enum class Modes {
Dimension , ThroughAll , ToLast = ThroughAll , ToFirst ,
ToFace , TwoDimensions
}
enum class Type { Pad , Pocket }
Public Member Functions
void addAxisToCombo (App::DocumentObject *linkObj, std::string linkSubname, QString itemText, bool hasSketch=true)
void applyParameters (QString facename)
void fillDirectionCombo ()
virtual void saveHistory () override
save field history
TaskExtrudeParameters (ViewProviderSketchBased *SketchBasedView, QWidget *parent, const std::string &pixmapname, const QString &parname)
~TaskExtrudeParameters ()
Public Member Functions inherited from PartDesignGui::TaskSketchBasedParameters
TaskSketchBasedParameters (PartDesignGui::ViewProvider *vp, QWidget *parent, const std::string &pixmapname, const QString &parname)
~TaskSketchBasedParameters ()
Public Member Functions inherited from PartDesignGui::TaskFeatureParameters
virtual void apply ()
apply changes made in the parameters input to the model via commands
void recomputeFeature ()
virtual void saveHistory (void)
save field history
TaskFeatureParameters (PartDesignGui::ViewProvider *vp, QWidget *parent, const std::string &pixmapname, const QString &parname)
virtual ~TaskFeatureParameters ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::DocumentObserver
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Protected Slots
void onAlongSketchNormalChanged (bool)
void onButtonFace (const bool pressed=true)
void onDirectionCBChanged (int)
void onDirectionToggled (bool)
void onFaceName (const QString &text)
void onLength2Changed (double)
void onLengthChanged (double)
void onMidplaneChanged (bool)
virtual void onModeChanged (int)
void onOffsetChanged (double)
void onReversedChanged (bool)
void onTaper2Changed (double)
void onTaperChanged (double)
void onXDirectionEditChanged (double)
void onYDirectionEditChanged (double)
void onZDirectionEditChanged (double)
Protected Slots inherited from PartDesignGui::TaskFeatureParameters
void onUpdateView (bool on)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Member Functions
void changeEvent (QEvent *e) override
bool getAlongSketchNormal (void) const
bool getCustom (void) const
QString getFaceName (void) const
bool getMidplane (void) const
int getMode (void) const
double getOffset (void) const
void getReferenceAxis (App::DocumentObject *&obj, std::vector< std::string > &sub) const
std::string getReferenceAxis (void) const
bool getReversed (void) const
double getXDirection (void) const
double getYDirection (void) const
double getZDirection (void) const
void onSelectionChanged (const Gui::SelectionChanges &msg) override
void readValuesFromHistory ()
void setCheckboxes (Modes mode, Type type)
void setDirectionMode (int index)
void setupDialog ()
virtual void translateModeList (int index)
void updateDirectionEdits (void)
virtual void updateUI (int index)
Protected Member Functions inherited from PartDesignGui::TaskSketchBasedParameters
void exitSelectionMode ()
virtual void finishReferenceSelection (App::DocumentObject *profile, App::DocumentObject *base)
QString getFaceReference (const QString &obj, const QString &sub) const
QString make2DLabel (const App::DocumentObject *section, const std::vector< std::string > &subValues)
Create a label for the 2D feature: the objects name if it's already 2D, or the subelement's name if the object is a solid.
QVariant objectNameByLabel (const QString &label, const QVariant &suggest) const
Try to find the name of a feature with the given label.
const QString onAddSelection (const Gui::SelectionChanges &msg)
void onSelectionChanged (const Gui::SelectionChanges &msg)=0
void onSelectReference (AllowSelectionFlags)
onSelectReference Start reference selection mode to allow to select objects of the type defined with AllowSelectionFlags. If AllowSelection::NONE is passed the selection mode is finished.
QVariant setUpToFace (const QString &text)
virtual void startReferenceSelection (App::DocumentObject *profile, App::DocumentObject *base)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Protected Attributes
std::vector< std::unique_ptr< App::PropertyLinkSub > > axesInList
App::PropertyLinkSub * propReferenceAxis
QWidget * proxy
bool selectionFace
std::unique_ptr< Ui_TaskPadPocketParameters > ui
Protected Attributes inherited from PartDesignGui::TaskFeatureParameters
bool blockUpdate
Lock updateUI(), applying changes to the underlying feature and calling recomputeFeature()
PartDesignGui::ViewProvider * vp
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Member Enumeration Documentation
Modes
enum class PartDesignGui::TaskExtrudeParameters::Modes strong
Enumerator
Dimension
ThroughAll
ToLast
ToFirst
ToFace
TwoDimensions
Type
enum class PartDesignGui::TaskExtrudeParameters::Type strong
Enumerator
Pad
Pocket
Constructor & Destructor Documentation
TaskExtrudeParameters()
TaskExtrudeParameters::TaskExtrudeParameters (ViewProviderSketchBased * SketchBasedView, QWidget * parent, const std::string & pixmapname, const QString & parname)
References QSint::ActionGroup::groupLayout(), proxy, and ui.
~TaskExtrudeParameters()
TaskExtrudeParameters::~TaskExtrudeParameters ()
Member Function Documentation
addAxisToCombo()
void TaskExtrudeParameters::addAxisToCombo (App::DocumentObject * linkObj, std::string linkSubname, QString itemText, bool hasSketch = true)
References axesInList, App::PropertyLinkSub::setValue(), and ui.
Referenced by fillDirectionCombo().
applyParameters()
void TaskExtrudeParameters::applyParameters (QString facename)
References getAlongSketchNormal(), getCustom(), getMidplane(), getMode(), Gui::ViewProviderDocumentObject::getObject(), getOffset(), getReferenceAxis(), getReversed(), getXDirection(), getYDirection(), getZDirection(), ui, and PartDesignGui::TaskFeatureParameters::vp.
Referenced by PartDesignGui::TaskPadParameters::apply(), and PartDesignGui::TaskPocketParameters::apply().
changeEvent()
void TaskExtrudeParameters::changeEvent (QEvent * e) override protected
References draftfunctions.offset::offset(), proxy, translateModeList(), and ui.
fillDirectionCombo()
void TaskExtrudeParameters::fillDirectionCombo ()
References addAxisToCombo(), axesInList, PartDesignGui::TaskFeatureParameters::blockUpdate, Gui::ViewProviderDocumentObject::getObject(), PartDesignGui::getRefStr(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), PartDesign::ProfileBased::Profile, propReferenceAxis, ui, and PartDesignGui::TaskFeatureParameters::vp.
getAlongSketchNormal()
bool TaskExtrudeParameters::getAlongSketchNormal (void) const protected
References ui.
Referenced by applyParameters().
getCustom()
bool TaskExtrudeParameters::getCustom (void) const protected
References ui.
Referenced by applyParameters().
getFaceName()
QString TaskExtrudeParameters::getFaceName (void) const protected
References PartDesignGui::TaskSketchBasedParameters::getFaceReference(), and ui.
Referenced by PartDesignGui::TaskPadParameters::apply(), and PartDesignGui::TaskPocketParameters::apply().
getMidplane()
bool TaskExtrudeParameters::getMidplane (void) const protected
References ui.
Referenced by applyParameters().
getMode()
int TaskExtrudeParameters::getMode (void) const protected
References ui.
Referenced by PartDesignGui::TaskPadParameters::apply(), PartDesignGui::TaskPocketParameters::apply(), and applyParameters().
getOffset()
double TaskExtrudeParameters::getOffset (void) const protected
References ui.
Referenced by applyParameters(), draftguitools.gui_selectplane.Draft_SelectPlane::display(), draftguitools.gui_selectplane.Draft_SelectPlane::handle(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickAlign(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickFront(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickSide(), and draftguitools.gui_selectplane.Draft_SelectPlane::onClickTop().
getReferenceAxis() [1/2]
void TaskExtrudeParameters::getReferenceAxis (App::DocumentObject *& obj, std::vector< std::string > & sub) const protected
References axesInList, App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), App::Document::isIn(), ui, and PartDesignGui::TaskFeatureParameters::vp.
getReferenceAxis() [2/2]
std::string TaskExtrudeParameters::getReferenceAxis (void) const protected
References PartDesignGui::buildLinkSingleSubPythonStr(), and getReferenceAxis().
Referenced by applyParameters(), and getReferenceAxis().
getReversed()
bool TaskExtrudeParameters::getReversed (void) const protected
References ui.
Referenced by applyParameters().
getXDirection()
double TaskExtrudeParameters::getXDirection (void) const protected
References ui.
Referenced by applyParameters().
getYDirection()
double TaskExtrudeParameters::getYDirection (void) const protected
References ui.
Referenced by applyParameters().
getZDirection()
double TaskExtrudeParameters::getZDirection (void) const protected
References ui.
Referenced by applyParameters().
onAlongSketchNormalChanged
void TaskExtrudeParameters::onAlongSketchNormalChanged (bool on) protected slot
References Gui::ViewProviderDocumentObject::getObject(), and PartDesignGui::TaskFeatureParameters::vp.
onButtonFace
void TaskExtrudeParameters::onButtonFace (const bool pressed = true) protected slot
References PartDesignGui::FACE, PartDesignGui::NONE, PartDesignGui::TaskSketchBasedParameters::onSelectReference(), selectionFace, and ui.
Referenced by onSelectionChanged(), and setCheckboxes().
onDirectionCBChanged
void TaskExtrudeParameters::onDirectionCBChanged (int num) protected slot
References axesInList, PartDesignGui::CIRCLE, Base::Console(), PartDesignGui::EDGE, Base::ConsoleSingleton::Error(), PartDesignGui::TaskSketchBasedParameters::exitSelectionMode(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), PartDesignGui::TaskSketchBasedParameters::onSelectReference(), App::PropertyLinkSub::Paste(), PartDesignGui::PLANAR, propReferenceAxis, selectionFace, setDirectionMode(), updateDirectionEdits(), and PartDesignGui::TaskFeatureParameters::vp.
onDirectionToggled
void TaskExtrudeParameters::onDirectionToggled (bool on) protected slot
References ui.
Referenced by setupDialog().
onFaceName
void TaskExtrudeParameters::onFaceName (const QString & text) protected slot
References PartDesignGui::TaskSketchBasedParameters::objectNameByLabel(), PartDesignGui::TaskSketchBasedParameters::setUpToFace(), and ui.
onLength2Changed
void TaskExtrudeParameters::onLength2Changed (double len) protected slot
References Gui::ViewProviderDocumentObject::getObject(), and PartDesignGui::TaskFeatureParameters::vp.
onLengthChanged
void TaskExtrudeParameters::onLengthChanged (double len) protected slot
References Gui::ViewProviderDocumentObject::getObject(), and PartDesignGui::TaskFeatureParameters::vp.
onMidplaneChanged
void TaskExtrudeParameters::onMidplaneChanged (bool on) protected slot
References Gui::ViewProviderDocumentObject::getObject(), ui, and PartDesignGui::TaskFeatureParameters::vp.
onModeChanged
void TaskExtrudeParameters::onModeChanged (int) protected virtual slot
onOffsetChanged
void TaskExtrudeParameters::onOffsetChanged (double len) protected slot
References Gui::ViewProviderDocumentObject::getObject(), and PartDesignGui::TaskFeatureParameters::vp.
onReversedChanged
void TaskExtrudeParameters::onReversedChanged (bool on) protected slot
References Gui::ViewProviderDocumentObject::getObject(), ui, updateDirectionEdits(), and PartDesignGui::TaskFeatureParameters::vp.
onSelectionChanged()
void TaskExtrudeParameters::onSelectionChanged (const Gui::SelectionChanges & msg) override protected virtual
Implements PartDesignGui::TaskSketchBasedParameters.
References Gui::SelectionChanges::AddSelection, Gui::SelectionChanges::ClrSelection, PartDesignGui::TaskSketchBasedParameters::onAddSelection(), onButtonFace(), selectionFace, and ui.
onTaper2Changed
void TaskExtrudeParameters::onTaper2Changed (double angle) protected slot
References Gui::ViewProviderDocumentObject::getObject(), and PartDesignGui::TaskFeatureParameters::vp.
onTaperChanged
void TaskExtrudeParameters::onTaperChanged (double angle) protected slot
References Gui::ViewProviderDocumentObject::getObject(), and PartDesignGui::TaskFeatureParameters::vp.
onXDirectionEditChanged
void TaskExtrudeParameters::onXDirectionEditChanged (double len) protected slot
References Gui::ViewProviderDocumentObject::getObject(), updateDirectionEdits(), and PartDesignGui::TaskFeatureParameters::vp.
onYDirectionEditChanged
void TaskExtrudeParameters::onYDirectionEditChanged (double len) protected slot
References Gui::ViewProviderDocumentObject::getObject(), updateDirectionEdits(), and PartDesignGui::TaskFeatureParameters::vp.
onZDirectionEditChanged
void TaskExtrudeParameters::onZDirectionEditChanged (double len) protected slot
References Gui::ViewProviderDocumentObject::getObject(), updateDirectionEdits(), and PartDesignGui::TaskFeatureParameters::vp.
readValuesFromHistory()
void TaskExtrudeParameters::readValuesFromHistory () protected
References ui.
Referenced by PartDesignGui::TaskPadParameters::TaskPadParameters(), and PartDesignGui::TaskPocketParameters::TaskPocketParameters().
saveHistory()
void TaskExtrudeParameters::saveHistory (void) override virtual
save field history
Reimplemented from PartDesignGui::TaskFeatureParameters.
References ui.
setCheckboxes()
void TaskExtrudeParameters::setCheckboxes (Modes mode, Type type) protected
References Dimension, onButtonFace(), Pad, Pocket, ThroughAll, ToFace, ToFirst, ToLast, TwoDimensions, and ui.
setDirectionMode()
void TaskExtrudeParameters::setDirectionMode (int index) protected
References Gui::ViewProviderDocumentObject::getObject(), ui, and PartDesignGui::TaskFeatureParameters::vp.
Referenced by onDirectionCBChanged().
setupDialog()
void TaskExtrudeParameters::setupDialog () protected
References Base::UnitsApi::getDecimals(), Gui::ViewProviderDocumentObject::getObject(), PartDesign::Feature::isDatum(), onDirectionToggled(), App::ObjectIdentifier::parse(), propReferenceAxis, PartDesign::FeatureExtrude::ReferenceAxis, translateModeList(), ui, updateUI(), and PartDesignGui::TaskFeatureParameters::vp.
Referenced by PartDesignGui::TaskPadParameters::TaskPadParameters(), and PartDesignGui::TaskPocketParameters::TaskPocketParameters().
translateModeList()
void TaskExtrudeParameters::translateModeList (int index) protected virtual
Referenced by changeEvent(), and setupDialog().
updateDirectionEdits()
void TaskExtrudeParameters::updateDirectionEdits (void) protected
References Gui::ViewProviderDocumentObject::getObject(), ui, and PartDesignGui::TaskFeatureParameters::vp.
Referenced by onDirectionCBChanged(), onReversedChanged(), onXDirectionEditChanged(), onYDirectionEditChanged(), and onZDirectionEditChanged().
updateUI()
void TaskExtrudeParameters::updateUI (int index) protected virtual
Referenced by Mod.PartDesign.FeatureHole.TaskHole.TaskHole::checkCounterbore(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::checkCountersink(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::checkCustom(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::checkCustomThreadLength(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::checkThreaded(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::comboFinishNorm(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::comboNorm(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::comboNormBoltWasher(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::comboNormDia(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::comboThreadDia(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::comboThreadNorm(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::comboTolerance(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::comboType(), PathScripts.PathPropertyBagGui.PropertyCreate::exec_(), PathScripts.PathDressupDragknife.TaskPanel::getFields(), PathScripts.PathToolBitEdit.ToolBitEditor::refresh(), PathScripts.PathToolEdit.ToolEditor::refresh(), PathScripts.PathDressupAxisMap.TaskPanel::setFields(), PathScripts.PathDressupDogbone.TaskPanel::setFields(), PathScripts.PathDressupDragknife.TaskPanel::setFields(), PathScripts.PathDressupZCorrect.TaskPanel::setFields(), PathScripts.PathSetupSheetGui.OpsDefaultEditor::setFields(), PathScripts.PathSetupSheetGui.GlobalEditor::setFields(), setupDialog(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::setupUi(), PathScripts.PathSetupSheetGui.OpsDefaultEditor::setupUi(), PathScripts.PathToolBitEdit.ToolBitEditor::setupUI(), PathScripts.PathToolEdit.ToolEditor::setupUI(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::spinDepth(), PathScripts.PathDressupDogbone.TaskPanel::updateModel(), PathScripts.PathDressupZCorrect.TaskPanel::updateModel(), PathScripts.PathSetupSheetGui.OpsDefaultEditor::updateModel(), PathScripts.PathSetupSheetGui.GlobalEditor::updateModel(), and PathScripts.PathToolEdit.ToolEditor::updateToolType().
Member Data Documentation
axesInList
std::vector<std::unique_ptr<App::PropertyLinkSub> > PartDesignGui::TaskExtrudeParameters::axesInList protected
Referenced by addAxisToCombo(), fillDirectionCombo(), getReferenceAxis(), and onDirectionCBChanged().
propReferenceAxis
App::PropertyLinkSub* PartDesignGui::TaskExtrudeParameters::propReferenceAxis protected
Referenced by fillDirectionCombo(), onDirectionCBChanged(), and setupDialog().
proxy
QWidget* PartDesignGui::TaskExtrudeParameters::proxy protected
Referenced by changeEvent(), and TaskExtrudeParameters().
selectionFace
bool PartDesignGui::TaskExtrudeParameters::selectionFace protected
Referenced by onButtonFace(), onDirectionCBChanged(), and onSelectionChanged().
ui
std::unique_ptr<Ui_TaskPadPocketParameters> PartDesignGui::TaskExtrudeParameters::ui protected
Referenced by draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_shapestrings.ShapeString::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_arcs.Arc::Activated(), draftguitools.gui_circulararray.CircularArray::Activated(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_ellipses.Ellipse::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_move.Move::Activated(), draftguitools.gui_orthoarray.OrthoArray::Activated(), draftguitools.gui_polararray.PolarArray::Activated(), draftguitools.gui_polygons.Polygon::Activated(), draftguitools.gui_rectangles.Rectangle::Activated(), draftguitools.gui_rotate.Rotate::Activated(), draftguitools.gui_scale.Scale::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_shapestrings.ShapeString::Activated(), draftguitools.gui_split.Split::Activated(), draftguitools.gui_styles.ApplyStyle::Activated(), draftguitools.gui_texts.Text::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_array_simple.Array::Activated(), draftguitools.gui_fillets.Fillet::Activated(), addAxisToCombo(), draftguitools.gui_stretch.Stretch::addPoint(), draftguitools.gui_ellipses.Ellipse::appendPoint(), draftguitools.gui_rectangles.Rectangle::appendPoint(), applyParameters(), package_details.PackageDetails::branch_changed(), changeEvent(), DraftGui.DraftToolBar::changeEvent(), draftguitools.gui_circulararray.CircularArray::click(), draftguitools.gui_orthoarray.OrthoArray::click(), draftguitools.gui_polararray.PolarArray::click(), draftguitools.gui_dimensions.Dimension::createObject(), package_details.PackageDetails::disable_clicked(), package_details.PackageDetails::display_repo_status(), draftguitools.gui_polygons.Polygon::drawPolygon(), package_details.PackageDetails::enable_clicked(), draftguitools.gui_edit.Edit::endEditing(), change_branch.ChangeBranchDialog::exec(), fillDirectionCombo(), draftguitools.gui_base_original.DraftTool::finish(), draftguitools.gui_fillets.Fillet::finish(), draftguitools.gui_dimensions.Dimension::finish(), draftguitools.gui_edit.Edit::finish(), draftguitools.gui_trimex.Trimex::finish(), draftguitools.gui_arcs.Arc::finish(), draftguitools.gui_beziers.BezCurve::finish(), draftguitools.gui_beziers.CubicBezCurve::finish(), draftguitools.gui_ellipses.Ellipse::finish(), draftguitools.gui_lines.Line::finish(), draftguitools.gui_mirror.Mirror::finish(), draftguitools.gui_move.Move::finish(), draftguitools.gui_polygons.Polygon::finish(), draftguitools.gui_rectangles.Rectangle::finish(), draftguitools.gui_rotate.Rotate::finish(), draftguitools.gui_splines.BSpline::finish(), draftguitools.gui_texts.Text::finish(), draftguitools.gui_points.Point::finish(), draftguitools.gui_shapestrings.ShapeString::finish(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_subelements.SubelementHighlight::get_selection(), getAlongSketchNormal(), getCustom(), getFaceName(), getMidplane(), getMode(), getOffset(), getReferenceAxis(), getReversed(), draftguitools.gui_base_original.DraftTool::getStrings(), getXDirection(), getYDirection(), getZDirection(), draftguitools.gui_move.Move::handle_mouse_click_event(), package_details.PackageDetails::load_finished(), package_details.PackageDetails::load_progress(), package_details.PackageDetails::load_started(), package_details.PackageDetails::long_load_running(), package_details.PackageDetails::macro_readme_updated(), draftguitools.gui_circulararray.CircularArray::move(), draftguitools.gui_points.Point::move(), draftguitools.gui_polararray.PolarArray::move(), draftguitools.gui_move.Move::move(), draftguitools.gui_arcs.Arc::numericInput(), draftguitools.gui_polygons.Polygon::numericInput(), draftguitools.gui_rotate.Rotate::numericInput(), draftguitools.gui_shapestrings.ShapeString::numericInput(), draftguitools.gui_arcs.Arc::numericRadius(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), onButtonFace(), onDirectionToggled(), onFaceName(), onMidplaneChanged(), onReversedChanged(), onSelectionChanged(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_groups.AddToGroup::proceed(), draftguitools.gui_groups.SetAutoGroup::proceed(), readValuesFromHistory(), draftguitools.gui_rotate.Rotate::rotate(), package_details.PackageDetails::run_javascript(), saveHistory(), draftguitools.gui_fillets.Fillet::set_chamfer(), package_details.PackageDetails::set_change_branch_button_state(), draftguitools.gui_fillets.Fillet::set_delete(), package_details.PackageDetails::set_disable_button_state(), draftguitools.gui_move.Move::set_ghosts(), draftguitools.gui_rotate.Rotate::set_ghosts(), draftguitools.gui_rotate.Rotate::set_start_point(), package_list.PackageList::set_view_style(), setCheckboxes(), setDirectionMode(), setupDialog(), package_details.PackageDetails::show_error_for(), package_details.PackageDetails::show_package(), package_details.PackageDetails::show_repo(), package_details.PackageDetails::show_workbench(), draftguitools.gui_edit.Edit::startEditing(), TaskExtrudeParameters(), PartDesignGui::TaskPadParameters::TaskPadParameters(), PartDesignGui::TaskPocketParameters::TaskPocketParameters(), package_list.PackageList::update_text_filter(), updateDirectionEdits(), and draftguitools.gui_edit.Edit::updateTrackerAndGhost().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/PartDesign/Gui/TaskExtrudeParameters.h
FreeCAD/src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp