FreeCAD: CDxfWrite Class Reference
CDxfWrite Class Reference
#include <dxf.h>
Public Member Functions
void addBlockName (std::string s, std::string blkRecordHandle)
CDxfWrite (const char *filepath)
CDxfWrite (const char *filepath)
CDxfWrite (const char *filepath)
void endRun (void)
assemble pieces into output file
bool Failed ()
bool Failed ()
bool Failed ()
std::string getLayerName ()
void init (void)
void makeBlockRecordTableBody (void)
void makeBlockRecordTableHead (void)
void makeBlockSectionHead (void)
void makeLayerTable (void)
void setLayerName (std::string s)
void setPolyOverride (bool b)
void setVersion (int v)
void writeAngularDim (const double *textMidPoint, const double *lineDefPoint, const double *startExt1, const double *endExt1, const double *startExt2, const double *endExt2, const char *dimText)
void writeAngularDimBlock (const double *textMidPoint, const double *lineDefPoint, const double *startExt1, const double *endExt1, const double *startExt2, const double *endExt2, const char *dimText)
void writeArc (const double *s, const double *e, const double *c, bool dir)
void WriteArc (const double *s, const double *e, const double *c, bool dir, const char *layer_name)
void WriteArc (const double *s, const double *e, const double *c, bool dir, const char *layer_name)
void writeBlocksSection (void)
void writeBlockTrailer (void)
void writeCircle (const double *c, double radius)
void WriteCircle (const double *c, double radius, const char *layer_name)
void WriteCircle (const double *c, double radius, const char *layer_name)
void writeClassesSection (void)
void writeDiametricDim (const double *textMidPoint, const double *arcPoint1, const double *arcPoint2, const char *dimText)
void writeDiametricDimBlock (const double *textMidPoint, const double *arcPoint1, const double *arcPoint2, const char *dimText)
void writeDimBlockPreamble ()
void WriteEllipse (const double *c, double major_radius, double minor_radius, double rotation, double start_angle, double end_angle, bool dir, const char *layer_name)
void WriteEllipse (const double *c, double major_radius, double minor_radius, double rotation, double start_angle, double end_angle, bool dir, const char *layer_name)
void writeEllipse (const double *c, double major_radius, double minor_radius, double rotation, double start_angle, double end_angle, bool endIsCW)
void writeEntitiesSection (void)
void writeHeaderSection (void)
void writeLine (const double *s, const double *e)
void WriteLine (const double *s, const double *e, const char *layer_name)
void WriteLine (const double *s, const double *e, const char *layer_name)
void writeLinearDim (const double *textMidPoint, const double *lineDefPoint, const double *extLine1, const double *extLine2, const char *dimText, int type)
void writeLinearDimBlock (const double *textMidPoint, const double *lineDefPoint, const double *extLine1, const double *extLine2, const char *dimText, int type)
void writeLWPolyLine (const LWPolyDataOut &pd)
void writeObjectsSection (void)
void writePoint (const double *)
void WritePoint (const double *, const char *)
void WritePoint (const double *, const char *)
void writePolyline (const LWPolyDataOut &pd)
void writeRadialDim (const double *centerPoint, const double *textMidPoint, const double *arcPoint, const char *dimText)
void writeRadialDimBlock (const double *centerPoint, const double *textMidPoint, const double *arcPoint, const char *dimText)
void writeSpline (const SplineDataOut &sd)
void writeTablesSection (void)
void writeText (const char *text, const double *location1, const double *location2, const double height, const int horizJust)
void writeVertex (double x, double y, double z)
~CDxfWrite ()
~CDxfWrite ()
~CDxfWrite ()
Protected Member Functions
std::string getBlkRecordHandle (void)
std::string getBlockHandle (void)
std::string getEntityHandle (void)
std::string getHandle (void)
std::string getLayerHandle (void)
std::string getPlateFile (std::string fileSpec)
copy boiler plate file
void putArrow (Base::Vector3d arrowPos, Base::Vector3d barb1Pos, Base::Vector3d barb2Pos, std::ostringstream *outStream, const std::string handle, const std::string ownerHandle)
void putLine (const Base::Vector3d s, const Base::Vector3d e, std::ostringstream *outStream, const std::string handle, const std::string ownerHandle)
void putText (const char *text, const Base::Vector3d location1, const Base::Vector3d location2, const double height, const int horizJust, std::ostringstream *outStream, const std::string handle, const std::string ownerHandle)
void setDataDir (std::string s)
Protected Attributes
int m_blkRecordHandle
std::vector< std::string > m_blkRecordList
int m_blockHandle
std::vector< std::string > m_blockList
std::string m_currentBlock
std::string m_dataDir
int m_entityHandle
int m_handle
int m_layerHandle
std::vector< std::string > m_layerList
std::string m_layerName
std::string m_optionSource
bool m_polyOverride
std::string m_saveBlkRecordHandle
std::string m_saveBlockRecordTableHandle
std::string m_saveModelSpaceHandle
std::string m_savePaperSpaceHandle
int m_version
Constructor & Destructor Documentation
CDxfWrite() [1/3]
CDxfWrite::CDxfWrite (const char * filepath)
~CDxfWrite() [1/3]
CDxfWrite::~CDxfWrite ()
CDxfWrite() [2/3]
CDxfWrite::CDxfWrite (const char * filepath)
~CDxfWrite() [2/3]
CDxfWrite::~CDxfWrite ()
CDxfWrite() [3/3]
CDxfWrite::CDxfWrite (const char * filepath)
~CDxfWrite() [3/3]
CDxfWrite::~CDxfWrite ()
Member Function Documentation
addBlockName()
void CDxfWrite::addBlockName (std::string s, std::string blkRecordHandle)
References m_blkRecordList, and m_blockList.
Referenced by writeDimBlockPreamble().
endRun()
void CDxfWrite::endRun (void)
assemble pieces into output file
References makeBlockRecordTableBody(), makeLayerTable(), writeBlocksSection(), writeClassesSection(), writeEntitiesSection(), writeObjectsSection(), and writeTablesSection().
Failed() [1/3]
bool CDxfWrite::Failed ()
Failed() [2/3]
bool CDxfWrite::Failed ()
Failed() [3/3]
bool CDxfWrite::Failed ()
getBlkRecordHandle()
std::string CDxfWrite::getBlkRecordHandle (void) protected
References getHandle().
Referenced by makeBlockRecordTableHead(), and writeDimBlockPreamble().
getBlockHandle()
std::string CDxfWrite::getBlockHandle (void) protected
References getHandle().
Referenced by makeBlockSectionHead(), writeAngularDimBlock(), writeBlockTrailer(), writeDiametricDimBlock(), writeDimBlockPreamble(), writeLinearDimBlock(), and writeRadialDimBlock().
getEntityHandle()
std::string CDxfWrite::getEntityHandle (void) protected
References getHandle().
Referenced by writeAngularDim(), writeArc(), writeCircle(), writeDiametricDim(), writeEllipse(), writeLine(), writeLinearDim(), writeLWPolyLine(), writePoint(), writePolyline(), writeRadialDim(), writeSpline(), writeText(), and writeVertex().
getHandle()
std::string CDxfWrite::getHandle (void) protected
References m_handle.
Referenced by getBlkRecordHandle(), getBlockHandle(), getEntityHandle(), and getLayerHandle().
getLayerHandle()
std::string CDxfWrite::getLayerHandle (void) protected
References getHandle().
Referenced by makeLayerTable().
getLayerName()
std::string CDxfWrite::getLayerName ()
Referenced by putLine(), putText(), writeAngularDim(), writeArc(), writeBlockTrailer(), writeCircle(), writeDiametricDim(), writeDimBlockPreamble(), writeEllipse(), writeLinearDim(), writeLWPolyLine(), writePoint(), writePolyline(), writeRadialDim(), writeSpline(), and writeVertex().
getPlateFile()
std::string CDxfWrite::getPlateFile (std::string fileSpec) protected
copy boiler plate file
References Base::Console(), Base::FileInfo::filePath(), Base::FileInfo::isReadable(), and Base::ConsoleSingleton::Message().
Referenced by writeBlocksSection(), writeClassesSection(), writeEntitiesSection(), writeHeaderSection(), writeObjectsSection(), and writeTablesSection().
init()
void CDxfWrite::init (void)
References makeBlockRecordTableHead(), makeBlockSectionHead(), and writeHeaderSection().
Referenced by DocumentObject.DocumentObject::onChanged().
makeBlockRecordTableBody()
void CDxfWrite::makeBlockRecordTableBody (void)
References m_blkRecordList, m_blockList, m_saveBlockRecordTableHandle, and m_version.
Referenced by endRun().
makeBlockRecordTableHead()
void CDxfWrite::makeBlockRecordTableHead (void)
References getBlkRecordHandle(), m_blockList, m_saveBlockRecordTableHandle, m_saveModelSpaceHandle, m_savePaperSpaceHandle, and m_version.
Referenced by init().
makeBlockSectionHead()
void CDxfWrite::makeBlockSectionHead (void)
References getBlockHandle(), m_currentBlock, m_saveModelSpaceHandle, m_savePaperSpaceHandle, and m_version.
Referenced by init().
makeLayerTable()
void CDxfWrite::makeLayerTable (void)
References getLayerHandle(), m_layerList, and m_version.
Referenced by endRun().
putArrow()
void CDxfWrite::putArrow (Base::Vector3d arrowPos, Base::Vector3d barb1Pos, Base::Vector3d barb2Pos, std::ostringstream * outStream, const std::string handle, const std::string ownerHandle) protected
References m_version, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by writeAngularDimBlock(), writeDiametricDimBlock(), writeLinearDimBlock(), and writeRadialDimBlock().
putLine()
void CDxfWrite::putLine (const Base::Vector3d s, const Base::Vector3d e, std::ostringstream * outStream, const std::string handle, const std::string ownerHandle) protected
References getLayerName(), and m_version.
Referenced by writeDiametricDimBlock(), writeLine(), writeLinearDimBlock(), and writeRadialDimBlock().
putText()
void CDxfWrite::putText (const char * text, const Base::Vector3d location1, const Base::Vector3d location2, const double height, const int horizJust, std::ostringstream * outStream, const std::string handle, const std::string ownerHandle) protected
References getLayerName(), m_version, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by writeAngularDimBlock(), writeDiametricDimBlock(), writeLinearDimBlock(), writeRadialDimBlock(), and writeText().
setDataDir()
void CDxfWrite::setDataDir (std::string s) protected
Referenced by Import::ImpExpDxfWrite::setOptions().
setLayerName()
void CDxfWrite::setLayerName (std::string s)
References m_layerList, and m_layerName.
setPolyOverride()
void CDxfWrite::setPolyOverride (bool b)
setVersion()
void CDxfWrite::setVersion (int v)
writeAngularDim()
void CDxfWrite::writeAngularDim (const double * textMidPoint, const double * lineDefPoint, const double * startExt1, const double * endExt1, const double * startExt2, const double * endExt2, const char * dimText)
References getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, m_version, writeAngularDimBlock(), writeBlockTrailer(), and writeDimBlockPreamble().
Referenced by Import::ImpExpDxfWrite::exportAngularDim().
writeAngularDimBlock()
void CDxfWrite::writeAngularDimBlock (const double * textMidPoint, const double * lineDefPoint, const double * startExt1, const double * endExt1, const double * startExt2, const double * endExt2, const char * dimText)
References getBlockHandle(), m_saveBlkRecordHandle, m_version, Base::Vector3< _Precision >::Normalize(), putArrow(), putText(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by writeAngularDim().
writeArc()
void CDxfWrite::writeArc (const double * s, const double * e, const double * c, bool dir)
References getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, and m_version.
Referenced by Import::ImpExpDxfWrite::exportArc().
WriteArc() [1/2]
void CDxfWrite::WriteArc (const double * s, const double * e, const double * c, bool dir, const char * layer_name)
WriteArc() [2/2]
void CDxfWrite::WriteArc (const double * s, const double * e, const double * c, bool dir, const char * layer_name)
writeBlocksSection()
void CDxfWrite::writeBlocksSection (void)
References getPlateFile(), m_dataDir, and m_version.
Referenced by endRun().
writeBlockTrailer()
void CDxfWrite::writeBlockTrailer (void)
References getBlockHandle(), getLayerName(), m_saveBlkRecordHandle, and m_version.
Referenced by writeAngularDim(), writeDiametricDim(), writeLinearDim(), and writeRadialDim().
writeCircle()
void CDxfWrite::writeCircle (const double * c, double radius)
References getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, and m_version.
Referenced by Import::ImpExpDxfWrite::exportCircle().
WriteCircle() [1/2]
void CDxfWrite::WriteCircle (const double * c, double radius, const char * layer_name)
WriteCircle() [2/2]
void CDxfWrite::WriteCircle (const double * c, double radius, const char * layer_name)
writeClassesSection()
void CDxfWrite::writeClassesSection (void)
References getPlateFile(), m_dataDir, and m_version.
Referenced by endRun().
writeDiametricDim()
void CDxfWrite::writeDiametricDim (const double * textMidPoint, const double * arcPoint1, const double * arcPoint2, const char * dimText)
References getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, m_version, writeBlockTrailer(), writeDiametricDimBlock(), and writeDimBlockPreamble().
Referenced by Import::ImpExpDxfWrite::exportDiametricDim().
writeDiametricDimBlock()
void CDxfWrite::writeDiametricDimBlock (const double * textMidPoint, const double * arcPoint1, const double * arcPoint2, const char * dimText)
References getBlockHandle(), m_saveBlkRecordHandle, Base::Vector3< _Precision >::Normalize(), putArrow(), putLine(), putText(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by writeDiametricDim().
writeDimBlockPreamble()
void CDxfWrite::writeDimBlockPreamble (void)
References addBlockName(), getBlkRecordHandle(), getBlockHandle(), getLayerName(), m_currentBlock, m_saveBlkRecordHandle, and m_version.
Referenced by writeAngularDim(), writeDiametricDim(), writeLinearDim(), and writeRadialDim().
WriteEllipse() [1/2]
void CDxfWrite::WriteEllipse (const double * c, double major_radius, double minor_radius, double rotation, double start_angle, double end_angle, bool dir, const char * layer_name)
WriteEllipse() [2/2]
void CDxfWrite::WriteEllipse (const double * c, double major_radius, double minor_radius, double rotation, double start_angle, double end_angle, bool dir, const char * layer_name)
writeEllipse()
void CDxfWrite::writeEllipse (const double * c, double major_radius, double minor_radius, double rotation, double start_angle, double end_angle, bool endIsCW)
References getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, and m_version.
Referenced by Import::ImpExpDxfWrite::exportEllipse(), and Import::ImpExpDxfWrite::exportEllipseArc().
writeEntitiesSection()
void CDxfWrite::writeEntitiesSection (void)
References getPlateFile(), m_dataDir, and m_version.
Referenced by endRun().
writeHeaderSection()
void CDxfWrite::writeHeaderSection (void)
References App::Application::Config(), getPlateFile(), m_dataDir, and m_version.
Referenced by init().
writeLine()
void CDxfWrite::writeLine (const double * s, const double * e)
References getEntityHandle(), m_saveModelSpaceHandle, and putLine().
Referenced by Import::ImpExpDxfWrite::exportLine().
WriteLine() [1/2]
void CDxfWrite::WriteLine (const double * s, const double * e, const char * layer_name)
WriteLine() [2/2]
void CDxfWrite::WriteLine (const double * s, const double * e, const char * layer_name)
writeLinearDim()
void CDxfWrite::writeLinearDim (const double * textMidPoint, const double * lineDefPoint, const double * extLine1, const double * extLine2, const char * dimText, int type)
References getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, m_version, writeBlockTrailer(), writeDimBlockPreamble(), and writeLinearDimBlock().
Referenced by Import::ImpExpDxfWrite::exportLinearDim().
writeLinearDimBlock()
void CDxfWrite::writeLinearDimBlock (const double * textMidPoint, const double * lineDefPoint, const double * extLine1, const double * extLine2, const char * dimText, int type)
References Base::Vector3< _Precision >::DistanceToLineSegment(), Base::Vector3< _Precision >::GetAngle(), getBlockHandle(), m_saveBlkRecordHandle, Base::Vector3< _Precision >::Normalize(), putArrow(), putLine(), and putText().
Referenced by writeLinearDim().
writeLWPolyLine()
void CDxfWrite::writeLWPolyLine (const LWPolyDataOut & pd)
References LWPolyDataOut::Bulge, LWPolyDataOut::EndWidth, LWPolyDataOut::Flag, getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, m_version, LWPolyDataOut::nVert, LWPolyDataOut::StartWidth, and LWPolyDataOut::Verts.
Referenced by Import::ImpExpDxfWrite::exportLWPoly().
writeObjectsSection()
void CDxfWrite::writeObjectsSection (void)
References getPlateFile(), m_dataDir, and m_version.
Referenced by endRun().
writePoint()
void CDxfWrite::writePoint (const double * s)
References getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, and m_version.
Referenced by Import::ImpExpDxfWrite::exportShape().
WritePoint() [1/2]
void CDxfWrite::WritePoint (const double * s, const char * layer_name)
WritePoint() [2/2]
void CDxfWrite::WritePoint (const double * , const char *)
writePolyline()
void CDxfWrite::writePolyline (const LWPolyDataOut & pd)
References getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, m_version, and LWPolyDataOut::Verts.
Referenced by Import::ImpExpDxfWrite::exportPolyline().
writeRadialDim()
void CDxfWrite::writeRadialDim (const double * centerPoint, const double * textMidPoint, const double * arcPoint, const char * dimText)
References getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, m_version, writeBlockTrailer(), writeDimBlockPreamble(), and writeRadialDimBlock().
Referenced by Import::ImpExpDxfWrite::exportRadialDim().
writeRadialDimBlock()
void CDxfWrite::writeRadialDimBlock (const double * centerPoint, const double * textMidPoint, const double * arcPoint, const char * dimText)
References getBlockHandle(), m_saveBlkRecordHandle, Base::Vector3< _Precision >::Normalize(), putArrow(), putLine(), putText(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by writeRadialDim().
writeSpline()
void CDxfWrite::writeSpline (const SplineDataOut & sd)
References SplineDataOut::control, SplineDataOut::control_points, SplineDataOut::degree, SplineDataOut::fit, SplineDataOut::flag, getEntityHandle(), getLayerName(), SplineDataOut::knot, SplineDataOut::knots, m_saveModelSpaceHandle, m_version, and SplineDataOut::weight.
Referenced by Import::ImpExpDxfWrite::exportBSpline().
writeTablesSection()
void CDxfWrite::writeTablesSection (void)
References getPlateFile(), m_dataDir, and m_version.
Referenced by endRun().
writeText()
void CDxfWrite::writeText (const char * text, const double * location1, const double * location2, const double height, const int horizJust)
References getEntityHandle(), m_saveModelSpaceHandle, and putText().
Referenced by Import::ImpExpDxfWrite::exportText().
writeVertex()
void CDxfWrite::writeVertex (double x, double y, double z)
References getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, and m_version.
Member Data Documentation
m_blkRecordHandle
int CDxfWrite::m_blkRecordHandle protected
m_blkRecordList
std::vector<std::string> CDxfWrite::m_blkRecordList protected
Referenced by addBlockName(), and makeBlockRecordTableBody().
m_blockHandle
int CDxfWrite::m_blockHandle protected
m_blockList
std::vector<std::string> CDxfWrite::m_blockList protected
Referenced by addBlockName(), makeBlockRecordTableBody(), and makeBlockRecordTableHead().
m_currentBlock
std::string CDxfWrite::m_currentBlock protected
Referenced by makeBlockSectionHead(), and writeDimBlockPreamble().
m_dataDir
std::string CDxfWrite::m_dataDir protected
Referenced by writeBlocksSection(), writeClassesSection(), writeEntitiesSection(), writeHeaderSection(), writeObjectsSection(), and writeTablesSection().
m_entityHandle
int CDxfWrite::m_entityHandle protected
m_handle
int CDxfWrite::m_handle protected
Referenced by getHandle().
m_layerHandle
int CDxfWrite::m_layerHandle protected
m_layerList
std::vector<std::string> CDxfWrite::m_layerList protected
Referenced by makeLayerTable(), and setLayerName().
m_layerName
std::string CDxfWrite::m_layerName protected
Referenced by setLayerName().
m_optionSource
std::string CDxfWrite::m_optionSource protected
m_polyOverride
bool CDxfWrite::m_polyOverride protected
Referenced by Import::ImpExpDxfWrite::exportShape(), and Import::ImpExpDxfWrite::setOptions().
m_saveBlkRecordHandle
std::string CDxfWrite::m_saveBlkRecordHandle protected
Referenced by writeAngularDimBlock(), writeBlockTrailer(), writeDiametricDimBlock(), writeDimBlockPreamble(), writeLinearDimBlock(), and writeRadialDimBlock().
m_saveBlockRecordTableHandle
std::string CDxfWrite::m_saveBlockRecordTableHandle protected
Referenced by makeBlockRecordTableBody(), and makeBlockRecordTableHead().
m_saveModelSpaceHandle
std::string CDxfWrite::m_saveModelSpaceHandle protected
Referenced by makeBlockRecordTableHead(), makeBlockSectionHead(), writeAngularDim(), writeArc(), writeCircle(), writeDiametricDim(), writeEllipse(), writeLine(), writeLinearDim(), writeLWPolyLine(), writePoint(), writePolyline(), writeRadialDim(), writeSpline(), writeText(), and writeVertex().
m_savePaperSpaceHandle
std::string CDxfWrite::m_savePaperSpaceHandle protected
Referenced by makeBlockRecordTableHead(), and makeBlockSectionHead().
m_version
int CDxfWrite::m_version protected
Referenced by Import::ImpExpDxfWrite::exportShape(), makeBlockRecordTableBody(), makeBlockRecordTableHead(), makeBlockSectionHead(), makeLayerTable(), putArrow(), putLine(), putText(), Import::ImpExpDxfWrite::setOptions(), writeAngularDim(), writeAngularDimBlock(), writeArc(), writeBlocksSection(), writeBlockTrailer(), writeCircle(), writeClassesSection(), writeDiametricDim(), writeDimBlockPreamble(), writeEllipse(), writeEntitiesSection(), writeHeaderSection(), writeLinearDim(), writeLWPolyLine(), writeObjectsSection(), writePoint(), writePolyline(), writeRadialDim(), writeSpline(), writeTablesSection(), and writeVertex().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Draft/App/dxf.h
Sources/FreeCAD/src/Mod/Draft/App/dxf.cpp