FreeCAD: TechDraw::ShapeExtractor Class Reference
TechDraw::ShapeExtractor Class Reference
#include <ShapeExtractor.h>
Static Public Member Functions
static Base::Vector3d getLocation3dFromFeat (App::DocumentObject *obj)
static TopoDS_Shape getShapes (const std::vector< App::DocumentObject * > links)
static std::vector< TopoDS_Shape > getShapes2d (const std::vector< App::DocumentObject * > links)
static std::vector< TopoDS_Shape > getShapesFromObject (const App::DocumentObject *docObj)
static TopoDS_Shape getShapesFused (const std::vector< App::DocumentObject * > links)
static std::vector< TopoDS_Shape > getXShapes (const App::Link *xLink)
static bool is2dObject (App::DocumentObject *obj)
static bool isDraftPoint (App::DocumentObject *obj)
static bool isEdgeType (App::DocumentObject *obj)
static bool isPointType (App::DocumentObject *obj)
static bool prefAdd2d (void)
static TopoDS_Shape stripInfiniteShapes (TopoDS_Shape inShape)
Member Function Documentation
getLocation3dFromFeat()
Base::Vector3d ShapeExtractor::getLocation3dFromFeat (App::DocumentObject * obj) static
References Part::PropertyPartShape::getShape(), Part::TopoShape::getShape(), App::GeoFeature::globalPlacement(), isPointType(), Data::ComplexGeoData::setPlacement(), Part::Feature::Shape, and TechDraw::DrawUtil::vertex2Vector().
Referenced by TechDraw::LandmarkDimension::execute(), TechDraw::LandmarkDimension::get2DPoints(), and TechDraw::LandmarkDimension::onDocumentRestored().
getShapes()
TopoDS_Shape ShapeExtractor::getShapes (const std::vector< App::DocumentObject * > links) static
References Base::Console(), Base::ConsoleSingleton::Error(), Base::Persistence::getClassTypeId(), Part::Feature::getShape(), getShapesFromObject(), getXShapes(), and stripInfiniteShapes().
Referenced by ArchBuildingPart.BuildingPart::execute(), getShapesFused(), and TechDraw::DrawViewPart::getSourceShape().
getShapes2d()
std::vector< TopoDS_Shape > ShapeExtractor::getShapes2d (const std::vector< App::DocumentObject * > links) static
References Base::Persistence::getClassTypeId(), Part::PropertyPartShape::getShape(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::GeoFeature::globalPlacement(), App::GroupExtension::Group, is2dObject(), prefAdd2d(), and Part::Feature::Shape.
Referenced by TechDraw::DrawViewPart::getSourceShape2d().
getShapesFromObject()
std::vector< TopoDS_Shape > ShapeExtractor::getShapesFromObject (const App::DocumentObject * docObj) static
References Base::Console(), Base::ConsoleSingleton::Error(), Base::Persistence::getClassTypeId(), App::DocumentObject::getNameInDocument(), App::ExtensionContainer::getPropertyByName(), Part::PropertyPartShape::getShape(), getShapesFromObject(), Base::Persistence::getTypeId(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::GeoFeature::globalPlacement(), App::GroupExtension::Group, Base::Type::isDerivedFrom(), Base::ConsoleSingleton::Log(), and Part::Feature::Shape.
Referenced by getShapes(), and getShapesFromObject().
getShapesFused()
TopoDS_Shape ShapeExtractor::getShapesFused (const std::vector< App::DocumentObject * > links) static
References Base::Console(), Base::ConsoleSingleton::Error(), and getShapes().
Referenced by TechDraw::DrawViewPart::getSourceShapeFused().
getXShapes()
std::vector< TopoDS_Shape > ShapeExtractor::getXShapes (const App::Link * xLink) static
References Base::Console(), Base::Persistence::getClassTypeId(), App::LinkBaseExtension::getLink(), App::LinkBaseExtension::getLinkedChildren(), App::LinkBaseExtension::getScaleVector(), Part::Feature::getShape(), App::LinkBaseExtension::hasPlacement(), Base::ConsoleSingleton::Message(), Base::Matrix4D::scale(), and Base::Placement::toMatrix().
Referenced by getShapes().
is2dObject()
bool ShapeExtractor::is2dObject (App::DocumentObject * obj) static
References isEdgeType(), and isPointType().
Referenced by getShapes2d().
isDraftPoint()
bool ShapeExtractor::isDraftPoint (App::DocumentObject * obj) static
References App::PropertyPythonObject::toString().
Referenced by isPointType().
isEdgeType()
bool ShapeExtractor::isEdgeType (App::DocumentObject * obj) static
Referenced by is2dObject().
isPointType()
bool ShapeExtractor::isPointType (App::DocumentObject * obj) static
References Base::Persistence::getClassTypeId(), and isDraftPoint().
Referenced by getLocation3dFromFeat(), and is2dObject().
prefAdd2d()
bool ShapeExtractor::prefAdd2d (void) static
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by getShapes2d().
stripInfiniteShapes()
TopoDS_Shape ShapeExtractor::stripInfiniteShapes (TopoDS_Shape inShape) static
References draftfunctions.move::move(), and stripInfiniteShapes().
Referenced by getShapes(), and stripInfiniteShapes().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/App/ShapeExtractor.h
FreeCAD/src/Mod/TechDraw/App/ShapeExtractor.cpp