FreeCAD: SMDS_SetIterator< VALUE, VALUE_SET_ITERATOR, ACCESSOR, VALUE_FILTER > Class Template Reference
SMDS_SetIterator< VALUE, VALUE_SET_ITERATOR, ACCESSOR, VALUE_FILTER > Class Template Reference
SMDS_Iterator iterating over abstract set of values like STL containers.
#include <SMDS_SetIterator.hxx>
Public Member Functions
virtual void init (const VALUE_SET_ITERATOR &begin, const VALUE_SET_ITERATOR &end, const VALUE_FILTER &filter=VALUE_FILTER())
Initialization.
virtual bool more ()
Return true iff there are other object in this iterator.
virtual VALUE next ()
Return the current object and step to the next one.
SMDS_SetIterator (const VALUE_SET_ITERATOR &begin, const VALUE_SET_ITERATOR &end, const VALUE_FILTER &filter=VALUE_FILTER())
Public Member Functions inherited from SMDS_Iterator< VALUE >
virtual bool more ()=0
Return true if and only if there are other object in this iterator.
virtual VALUE next ()=0
Return the current object and step to the next one.
virtual void remove ()
Delete the current element and step to the next one.
virtual ~SMDS_Iterator ()
Provide virtual destructor just for case if some derived iterator must have a destructor.
Detailed Description
template<typename VALUE, typename VALUE_SET_ITERATOR, typename ACCESSOR = SMDS::SimpleAccessor<VALUE,VALUE_SET_ITERATOR>, typename VALUE_FILTER = SMDS::PassAllValueFilter<VALUE>>
class SMDS_SetIterator< VALUE, VALUE_SET_ITERATOR, ACCESSOR, VALUE_FILTER >
SMDS_Iterator iterating over abstract set of values like STL containers.
BE CAREFUL: iterator pointed value is static_cast'ed to VALUE
Constructor & Destructor Documentation
SMDS_SetIterator()
template<typename VALUE , typename VALUE_SET_ITERATOR , typename ACCESSOR = SMDS::SimpleAccessor<VALUE,VALUE_SET_ITERATOR>, typename VALUE_FILTER = SMDS::PassAllValueFilter<VALUE>> SMDS_SetIterator< VALUE, VALUE_SET_ITERATOR, ACCESSOR, VALUE_FILTER >::SMDS_SetIterator (const VALUE_SET_ITERATOR & begin, const VALUE_SET_ITERATOR & end, const VALUE_FILTER & filter = VALUE_FILTER())
References SMDS_SetIterator< VALUE, VALUE_SET_ITERATOR, ACCESSOR, VALUE_FILTER >::init().
Member Function Documentation
init()
template<typename VALUE , typename VALUE_SET_ITERATOR , typename ACCESSOR = SMDS::SimpleAccessor<VALUE,VALUE_SET_ITERATOR>, typename VALUE_FILTER = SMDS::PassAllValueFilter<VALUE>> virtual void SMDS_SetIterator< VALUE, VALUE_SET_ITERATOR, ACCESSOR, VALUE_FILTER >::init (const VALUE_SET_ITERATOR & begin, const VALUE_SET_ITERATOR & end, const VALUE_FILTER & filter = VALUE_FILTER()) virtual
Initialization.
References SMDS_SetIterator< VALUE, VALUE_SET_ITERATOR, ACCESSOR, VALUE_FILTER >::more(), and SMDS_SetIterator< VALUE, VALUE_SET_ITERATOR, ACCESSOR, VALUE_FILTER >::next().
Referenced by DocumentObject.DocumentObject::onChanged(), and SMDS_SetIterator< VALUE, VALUE_SET_ITERATOR, ACCESSOR, VALUE_FILTER >::SMDS_SetIterator().
more()
template<typename VALUE , typename VALUE_SET_ITERATOR , typename ACCESSOR = SMDS::SimpleAccessor<VALUE,VALUE_SET_ITERATOR>, typename VALUE_FILTER = SMDS::PassAllValueFilter<VALUE>> virtual bool SMDS_SetIterator< VALUE, VALUE_SET_ITERATOR, ACCESSOR, VALUE_FILTER >::more () virtual
Return true iff there are other object in this iterator.
Implements SMDS_Iterator< VALUE >.
Referenced by StdMeshers_CompositeHexa_3D::Evaluate(), SMDS_SetIterator< VALUE, VALUE_SET_ITERATOR, ACCESSOR, VALUE_FILTER >::init(), and SMDS_SetIterator< VALUE, VALUE_SET_ITERATOR, ACCESSOR, VALUE_FILTER >::next().
next()
template<typename VALUE , typename VALUE_SET_ITERATOR , typename ACCESSOR = SMDS::SimpleAccessor<VALUE,VALUE_SET_ITERATOR>, typename VALUE_FILTER = SMDS::PassAllValueFilter<VALUE>> virtual VALUE SMDS_SetIterator< VALUE, VALUE_SET_ITERATOR, ACCESSOR, VALUE_FILTER >::next () virtual
Return the current object and step to the next one.
Implements SMDS_Iterator< VALUE >.
References SMDS_SetIterator< VALUE, VALUE_SET_ITERATOR, ACCESSOR, VALUE_FILTER >::more().
Referenced by SMDS_SetIterator< VALUE, VALUE_SET_ITERATOR, ACCESSOR, VALUE_FILTER >::init().
The documentation for this class was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_SetIterator.hxx