FreeCAD: App::PropertyInteger Class Reference
App::PropertyInteger Class Reference
Integer properties This is the father of all properties handling Integers.
#include <PropertyStandard.h>
Public Member Functions
virtual Property * Copy (void) const
Returns a new copy of the property (mainly for Undo/Redo and transactions)
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
virtual const boost::any getPathValue (const App::ObjectIdentifier &) const
Get value of property.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
long getValue (void) const
This method returns a string representation of the property.
virtual void Paste (const Property &from)
Paste the value from the property (mainly for Undo/Redo and transactions)
PropertyInteger ()
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual void setPyObject (PyObject *)
void setValue (long)
Sets the property.
virtual ~PropertyInteger ()
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
const char * getName (void) const
get the name of this property in the belonging container
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, PropStaticBegin = 21,
PropDynamic = 21, PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24,
PropTransient = 25, PropHidden = 26, PropOutput = 27, PropStaticEnd = 28,
User1 = 28, User2 = 29, User3 = 30, User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Detailed Description
Integer properties This is the father of all properties handling Integers.
Constructor & Destructor Documentation
PropertyInteger()
PropertyInteger::PropertyInteger ()
~PropertyInteger()
PropertyInteger::~PropertyInteger () virtual
Member Function Documentation
Copy()
Property * PropertyInteger::Copy (void) const virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
getEditorName()
virtual const char* App::PropertyInteger::getEditorName (void) const virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
Reimplemented in App::PropertyIntegerConstraint.
getMemSize()
virtual unsigned int App::PropertyInteger::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
See also
Base::Persistence
Reimplemented from App::Property.
getPathValue()
virtual const boost::any App::PropertyInteger::getPathValue (const App::ObjectIdentifier & path) const virtual
Get value of property.
Reimplemented from App::Property.
getPyObject()
PyObject * PropertyInteger::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
getValue()
long PropertyInteger::getValue (void) const
This method returns a string representation of the property.
Referenced by TechDraw::DrawViewPart::buildGeometryObject(), PartGui::DlgPrimitives::DlgPrimitives(), TechDrawGui::QGIWeldSymbol::drawTile(), App::FunctionExpression::evalAggregate(), App::FeatureTest::execute(), Mesh::FillHoles::execute(), Mesh::RemoveComponents::execute(), Part::Loft::execute(), PartDesign::Prism::execute(), Points::Structured::execute(), Surface::Filling::execute(), TechDraw::DrawViewDimExtent::execute(), Surface::Extend::execute(), PartGui::ViewProviderPartExt::getElementColors(), FemGui::TaskFemConstraint::getScale(), Path::FeatureAreaView::getShapes(), TechDrawGui::QGIWeldSymbol::getTileFeats(), TechDrawGui::TaskWeldingSymbol::getTileFeats(), PartDesign::Scaled::getTransformations(), PartDesign::LinearPattern::getTransformations(), PartDesign::PolarPattern::getTransformations(), TechDraw::DrawTile::handleChangedPropertyType(), TechDraw::DrawViewAnnotation::handleChangedPropertyType(), TechDrawGui::ViewProviderLeader::handleChangedPropertyType(), TechDrawGui::ViewProviderRichAnno::handleChangedPropertyType(), PartDesignGui::ViewProviderDatumCoordinateSystem::onChanged(), Gui::ViewProviderGeometryObject::onChanged(), Gui::ViewProviderMeasureDistance::onChanged(), Fem::ConstraintPressure::onChanged(), FemGui::ViewProviderFemConstraint::onChanged(), FemGui::ViewProviderFemMesh::onChanged(), MeshGui::ViewProviderMesh::onChanged(), PartDesignGui::ViewProviderDatumPoint::onChanged(), Sandbox::SandboxObject::onChanged(), PartGui::ViewProviderPartExt::onChanged(), PartDesignGui::TaskBoxPrimitives::TaskBoxPrimitives(), FemGui::TaskTetParameter::TaskTetParameter(), FemGui::ViewProviderFemConstraintContact::updateData(), FemGui::ViewProviderFemConstraintDisplacement::updateData(), FemGui::ViewProviderFemConstraintFixed::updateData(), FemGui::ViewProviderFemConstraintFluidBoundary::updateData(), FemGui::ViewProviderFemConstraintForce::updateData(), FemGui::ViewProviderFemConstraintHeatflux::updateData(), FemGui::ViewProviderFemConstraintPlaneRotation::updateData(), FemGui::ViewProviderFemConstraintPressure::updateData(), FemGui::ViewProviderFemConstraintTemperature::updateData(), FemGui::ViewProviderFemConstraintTransform::updateData(), FemGui::ViewProviderFemMesh::updateData(), PartGui::ViewProviderChamfer::updateData(), Gui::PropertyEditor::PropertyIntegerItem::value(), Gui::PropertyEditor::PropertyIntegerConstraintItem::value(), and PartDesignGui::ViewProviderDatumCoordinateSystem::ViewProviderDatumCoordinateSystem().
Paste()
void PropertyInteger::Paste (const Property & from) virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Restore()
void PropertyInteger::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References Base::XMLReader::getAttributeAsInteger(), and Base::XMLReader::readElement().
Referenced by TechDraw::DrawTile::handleChangedPropertyType(), TechDraw::DrawViewAnnotation::handleChangedPropertyType(), TechDrawGui::ViewProviderLeader::handleChangedPropertyType(), and TechDrawGui::ViewProviderRichAnno::handleChangedPropertyType().
Save()
void PropertyInteger::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References Base::Writer::ind(), and Base::Writer::Stream().
setPathValue()
void PropertyInteger::setPathValue (const App::ObjectIdentifier & path, const boost::any & value) virtual
Set value of property.
Reimplemented from App::Property.
setPyObject()
void PropertyInteger::setPyObject (PyObject * value) virtual
Reimplemented from Base::BaseClass.
Reimplemented in App::PropertyIntegerConstraint.
setValue()
void PropertyInteger::setValue (long lValue)
Sets the property.
Referenced by App::FeatureTest::execute(), TechDraw::DrawTile::handleChangedPropertyType(), Gui::ViewProviderGeometryObject::onChanged(), Fem::ConstraintContact::onChanged(), Fem::ConstraintDisplacement::onChanged(), Fem::ConstraintFixed::onChanged(), Fem::ConstraintFluidBoundary::onChanged(), Fem::ConstraintForce::onChanged(), Fem::ConstraintHeatflux::onChanged(), Fem::ConstraintInitialTemperature::onChanged(), Fem::ConstraintPlaneRotation::onChanged(), Fem::ConstraintPressure::onChanged(), Fem::ConstraintTemperature::onChanged(), Fem::ConstraintTransform::onChanged(), PartDesignGui::ViewProviderDatumPoint::onChanged(), PartDesignGui::TaskBoxPrimitives::onPrismPolygonChanged(), TechDraw::DrawWeldSymbol::onSettingDocument(), Sandbox::SandboxObject::resetValue(), Sandbox::DocumentTestThread::run(), Spreadsheet::Sheet::setIntegerProperty(), Sandbox::SandboxObject::setIntValue(), PartDesignGui::ViewProviderDatum::ViewProviderDatum(), and PartGui::DlgProjectionOnSurface::~DlgProjectionOnSurface().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/App/PropertyStandard.h
Sources/FreeCAD/src/App/PropertyStandard.cpp