FreeCAD: InspectionGui Namespace Reference
InspectionGui Namespace Reference
Namespaces
namespace Ui
Classes
class Module
class SingleSelectionItem
class Ui_VisualInspection
class ViewProviderInspection
class ViewProviderInspectionGroup
class ViewProviderProxyObject
class VisualInspection
class Workbench
Functions
float calcArea (const SbVec3f &v1, const SbVec3f &v2, const SbVec3f &v3)
bool calcWeights (const SbVec3f &v1, const SbVec3f &v2, const SbVec3f &v3, const SbVec3f &p, float &w0, float &w1, float &w2)
PyObject * initModule ()
Function Documentation
calcArea()
float InspectionGui::calcArea (const SbVec3f & v1, const SbVec3f & v2, const SbVec3f & v3)
References draftgeoutils.general::v1().
Referenced by calcWeights().
calcWeights()
bool InspectionGui::calcWeights (const SbVec3f & v1, const SbVec3f & v2, const SbVec3f & v3, const SbVec3f & p, float & w0, float & w1, float & w2)
References calcArea().
Referenced by InspectionGui::ViewProviderInspection::inspectDistance().
initModule()
PyObject * InspectionGui::initModule ()
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().