FreeCAD: SketcherGui::DrawSketchHandlerExternal Class Reference
SketcherGui::DrawSketchHandlerExternal Class Reference
#include <DrawSketchHandlerExternal.h>
Public Member Functions
DrawSketchHandlerExternal ()=default
virtual void mouseMove (Base::Vector2d onSketchPos) override
virtual bool onSelectionChanged (const Gui::SelectionChanges &msg) override
virtual bool pressButton (Base::Vector2d onSketchPos) override
virtual bool releaseButton (Base::Vector2d onSketchPos) override
virtual ~DrawSketchHandlerExternal ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void activate (ViewProviderSketch *)
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::PointPos::none, bool createowncommand=true)
void deactivate ()
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual void mouseMove (Base::Vector2d onSketchPos)=0
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual bool pressButton (Base::Vector2d onSketchPos)=0
virtual void quit (void)
virtual void registerPressedKey (bool, int)
virtual bool releaseButton (Base::Vector2d onSketchPos)=0
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
virtual QString getCrosshairCursorSVGName () const
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
void updateCursor ()
updates the actCursor with the icon by calling getCrosshairCursorSVGName(), enabling to set data member dependent icons (i.e.
void unsetCursor (void)
restitutes the cursor that was in use at the moment of starting the DrawSketchHandler (i.e. oldCursor)
void applyCursor (void)
restitutes the DSH cached cursor (e.g. without any tail due to autoconstraints, ...)
unsigned long getCrosshairColor ()
returns the color to be used for the crosshair (configurable as a parameter)
qreal devicePixelRatio ()
functions to set the cursor to a given svgName (to be migrated to NVI style)
void drawEdit (const std::vector< Base::Vector2d > &EditCurve)
void drawEdit (const std::list< std::vector< Base::Vector2d > > &list)
void drawEdit (const std::vector< Part::Geometry * > &geometries)
void drawEditMarkers (const std::vector< Base::Vector2d > &EditMarkers, unsigned int augmentationlevel=0)
void setAxisPickStyle (bool on)
void moveCursorToSketchPoint (Base::Vector2d point)
void preselectAtPoint (Base::Vector2d point)
void drawPositionAtCursor (const Base::Vector2d &position)
void drawDirectionAtCursor (const Base::Vector2d &position, const Base::Vector2d &origin)
int getPreselectPoint (void) const
int getPreselectCurve (void) const
int getPreselectCross (void) const
Sketcher::SketchObject * getSketchObject ()
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
Protected Attributes inherited from SketcherGui::DrawSketchHandler
ViewProviderSketch * sketchgui
QCursor oldCursor
QCursor actCursor
QPixmap actCursorPixmap
Constructor & Destructor Documentation
DrawSketchHandlerExternal()
SketcherGui::DrawSketchHandlerExternal::DrawSketchHandlerExternal () default
~DrawSketchHandlerExternal()
virtual SketcherGui::DrawSketchHandlerExternal::~DrawSketchHandlerExternal () virtual
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
mouseMove()
virtual void SketcherGui::DrawSketchHandlerExternal::mouseMove (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::applyCursor(), and Gui::Selection().
onSelectionChanged()
virtual bool SketcherGui::DrawSketchHandlerExternal::onSelectionChanged (const Gui::SelectionChanges & msg) override virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), Gui::SelectionChanges::AddSelection, Gui::SelectionSingleton::clearSelection(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Base::Console(), Base::ConsoleSingleton::Error(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::Document::getObject(), Gui::ViewProviderDocumentObject::getObject(), Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, Gui::Selection(), SketcherGui::DrawSketchHandler::sketchgui, and SketcherGui::tryAutoRecomputeIfNotSolve().
pressButton()
virtual bool SketcherGui::DrawSketchHandlerExternal::pressButton (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
releaseButton()
virtual bool SketcherGui::DrawSketchHandlerExternal::releaseButton (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/DrawSketchHandlerExternal.h