FreeCAD: AdaptivePath::PerfCounter Class Reference
AdaptivePath::PerfCounter Class Reference
Public Member Functions
void DumpResults ()
PerfCounter (string p_name)
void Start ()
void Stop ()
Constructor & Destructor Documentation
PerfCounter()
AdaptivePath::PerfCounter::PerfCounter (string p_name)
Member Function Documentation
DumpResults()
void AdaptivePath::PerfCounter::DumpResults ()
Start()
void AdaptivePath::PerfCounter::Start ()
Referenced by PathScripts.PathDressupDogbone.Chord::arcCommand(), PathScripts.PathDressupDogbone.Chord::asLine(), PathScripts.PathDressupDogbone.Chord::asVector(), femtaskpanels.task_solver_ccxtools._TaskPanel::calculixFinished(), femtaskpanels.task_solver_ccxtools._TaskPanel::check_prerequisites_helper(), femtaskpanels.task_mesh_gmsh._TaskPanel::console_log(), AdaptivePath::ClearedArea::ExpandCleared(), femtaskpanels.task_solver_ccxtools._TaskPanel::femConsoleMessage(), PathScripts.PathDressupDogbone.Chord::isANoopMove(), PathScripts.PathDressupDogbone.Chord::isAPlungeMove(), AdaptivePath::EngagePoint::nextEngagePoint(), femtaskpanels.task_solver_ccxtools._TaskPanel::runCalculix(), femtaskpanels.task_mesh_gmsh._TaskPanel::update_timer_text(), and femtaskpanels.task_solver_ccxtools._TaskPanel::UpdateText().
Stop()
void AdaptivePath::PerfCounter::Stop ()
Referenced by AdaptivePath::ClearedArea::ExpandCleared(), and AdaptivePath::EngagePoint::nextEngagePoint().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Path/libarea/Adaptive.cpp