FreeCAD: SketcherGui::ConstraintMultiFilterDialog Class Reference
SketcherGui::ConstraintMultiFilterDialog Class Reference
#include <ConstraintMultiFilterDialog.h>
Public Slots
void on_checkAllButton_clicked (bool)
void on_listMultiFilter_itemChanged (QListWidgetItem *item)
void on_uncheckAllButton_clicked (bool)
Public Member Functions
ConstraintMultiFilterDialog (void)
FilterValueBitset getMultiFilter ()
void setMultiFilter (const FilterValueBitset &bitset)
~ConstraintMultiFilterDialog ()
Protected Member Functions
void setCheckStateAll (Qt::CheckState)
Constructor & Destructor Documentation
ConstraintMultiFilterDialog()
ConstraintMultiFilterDialog::ConstraintMultiFilterDialog (void)
~ConstraintMultiFilterDialog()
ConstraintMultiFilterDialog::~ConstraintMultiFilterDialog ()
Member Function Documentation
getMultiFilter()
FilterValueBitset ConstraintMultiFilterDialog::getMultiFilter ()
Referenced by SketcherGui::TaskSketcherConstraints::on_multipleFilterButton_clicked().
on_checkAllButton_clicked
void ConstraintMultiFilterDialog::on_checkAllButton_clicked (bool) slot
References setCheckStateAll().
on_listMultiFilter_itemChanged
void ConstraintMultiFilterDialog::on_listMultiFilter_itemChanged (QListWidgetItem * item) slot
References SketcherGui::ConstraintFilter::filterAggregates, and SketcherGui::ConstraintFilter::FilterValueLength.
on_uncheckAllButton_clicked
void ConstraintMultiFilterDialog::on_uncheckAllButton_clicked (bool) slot
References setCheckStateAll().
setCheckStateAll()
void ConstraintMultiFilterDialog::setCheckStateAll (Qt::CheckState state) protected
Referenced by on_checkAllButton_clicked(), and on_uncheckAllButton_clicked().
setMultiFilter()
void ConstraintMultiFilterDialog::setMultiFilter (const FilterValueBitset & bitset)
Referenced by SketcherGui::TaskSketcherConstraints::on_multipleFilterButton_clicked().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/Gui/ConstraintMultiFilterDialog.h
FreeCAD/src/Mod/Sketcher/Gui/ConstraintMultiFilterDialog.cpp