FreeCAD: Plot Namespace Reference
Plot Namespace Reference
Classes
class Line
class Plot
Functions
def addNavigationToolbar ()
def addNewAxes (rect=None, frameon=True, patchcolor='none')
def axes ()
def axesList ()
def closePlot ()
def delNavigationToolbar ()
def figure (winTitle="plot")
def getMainWindow ()
def getMdiArea ()
def getPlot ()
def grid (status=True)
def legend (status=True, pos=None, fontsize=None)
def plot (x, y, name=None)
def removeSerie (index)
def save (path, figsize=None, dpi=None)
def series ()
def title (string)
def xlabel (string)
def ylabel (string)
Variables
msg
Function Documentation
addNavigationToolbar()
def Plot.addNavigationToolbar ()
Add the matplotlib QT navigation toolbar to the plot.
References getPlot().
addNewAxes()
def Plot.addNewAxes (rect = None, frameon = True, patchcolor = 'none')
Add new axes to plot, setting it as the active one.
Keyword arguments:
rect -- Axes area, None to copy from the last axes data.
frameon -- True to show frame, False otherwise.
patchcolor -- Patch color, 'none' for transparent plot.
References getPlot().
Referenced by plotAxes.TaskPanel.TaskPanel.onNew(), shipCapacityCurve.PlotAux.Plot.plot(), shipHydrostatics.PlotAux.Plot.plotCoeffs(), shipHydrostatics.PlotAux.Plot.plotStability(), and shipHydrostatics.PlotAux.Plot.plotVolume().
axes()
def Plot.axes ()
Return the active plot axes.
References getPlot().
Referenced by shipGZ.PlotAux.Plot.plot(), and shipAreasCurve.PlotAux.Plot.plot().
axesList()
def Plot.axesList ()
Return the plot axes sets list.
References getPlot().
Referenced by shipHydrostatics.PlotAux.Plot.plotCoeffs(), shipHydrostatics.PlotAux.Plot.plotStability(), and shipHydrostatics.PlotAux.Plot.plotVolume().
closePlot()
def Plot.closePlot ()
 closePlot(): Close the active plot window.
References getMdiArea().
delNavigationToolbar()
def Plot.delNavigationToolbar ()
Remove the matplotlib QT navigation toolbar from the plot.
References getPlot().
figure()
def Plot.figure (winTitle = "plot")
Create a new plot subwindow/tab.
Keyword arguments:
winTitle -- Plot tab title.
References getMdiArea().
Referenced by shipCapacityCurve.PlotAux.Plot.plot(), shipGZ.PlotAux.Plot.plot(), shipAreasCurve.PlotAux.Plot.plot(), plot(), shipHydrostatics.PlotAux.Plot.plotCoeffs(), shipHydrostatics.PlotAux.Plot.plotStability(), and shipHydrostatics.PlotAux.Plot.plotVolume().
getMainWindow()
def Plot.getMainWindow ()
 Return the FreeCAD main window.
Referenced by getMdiArea().
getMdiArea()
def Plot.getMdiArea ()
 Return FreeCAD MdiArea.
References getMainWindow().
Referenced by closePlot(), figure(), and getPlot().
getPlot()
def Plot.getPlot ()
 Return the selected Plot document if exist.
References getMdiArea().
Referenced by plotSave.TaskPanel.TaskPanel.accept(), PlotGui.Grid.Activated(), PlotGui.Legend.Activated(), addNavigationToolbar(), addNewAxes(), axes(), axesList(), delNavigationToolbar(), grid(), legend(), plotAxes.TaskPanel.TaskPanel.onAlign(), plotAxes.TaskPanel.TaskPanel.onAxesId(), plotLabels.TaskPanel.TaskPanel.onAxesId(), plotSeries.TaskPanel.TaskPanel.onColor(), plotSeries.TaskPanel.TaskPanel.onData(), plotPositions.TaskPanel.TaskPanel.onData(), plotAxes.TaskPanel.TaskPanel.onDims(), plotLabels.TaskPanel.TaskPanel.onFontSizes(), plotLabels.TaskPanel.TaskPanel.onLabels(), plotAxes.TaskPanel.TaskPanel.onMdiArea(), plotLabels.TaskPanel.TaskPanel.onMdiArea(), plotPositions.TaskPanel.TaskPanel.onMdiArea(), plotSave.TaskPanel.TaskPanel.onMdiArea(), plotSeries.TaskPanel.TaskPanel.onMdiArea(), plotAxes.TaskPanel.TaskPanel.onNew(), plotAxes.TaskPanel.TaskPanel.onOffset(), plotAxes.TaskPanel.TaskPanel.onRemove(), plotSeries.TaskPanel.TaskPanel.onRemove(), plotAxes.TaskPanel.TaskPanel.onScales(), plot(), removeSerie(), save(), series(), title(), plotAxes.TaskPanel.TaskPanel.updateUI(), plotLabels.TaskPanel.TaskPanel.updateUI(), plotPositions.TaskPanel.TaskPanel.updateUI(), plotSave.TaskPanel.TaskPanel.updateUI(), plotSeries.TaskPanel.TaskPanel.updateUI(), xlabel(), and ylabel().
grid()
def Plot.grid (status = True)
Show/Hide the grid from the active plot.
Keyword arguments:
status -- True if grid must be shown, False otherwise.
References getPlot().
Referenced by PlotGui.Grid.Activated(), shipCapacityCurve.PlotAux.Plot.plot(), shipGZ.PlotAux.Plot.plot(), shipAreasCurve.PlotAux.Plot.plot(), shipHydrostatics.PlotAux.Plot.plotCoeffs(), shipHydrostatics.PlotAux.Plot.plotStability(), and shipHydrostatics.PlotAux.Plot.plotVolume().
legend()
def Plot.legend (status = True, pos = None, fontsize = None)
Show/Hide the legend from the active plot.
Keyword arguments:
status -- True if legend must be shown, False otherwise.
pos -- Legend position.
fontsize -- Font size
References getPlot(), and series().
Referenced by PlotGui.Legend.Activated(), plotPositions.TaskPanel.TaskPanel.onData(), shipHydrostatics.PlotAux.Plot.plotCoeffs(), shipHydrostatics.PlotAux.Plot.plotStability(), and shipHydrostatics.PlotAux.Plot.plotVolume().
plot()
def Plot.plot (x, y, name = None)
Plots a new serie (as line plot)
Keyword arguments:
x -- X values
y -- Y values
name -- Data serie name (for legend).
References figure(), and getPlot().
Referenced by shipCapacityCurve.PlotAux.Plot.plot(), shipGZ.PlotAux.Plot.plot(), shipAreasCurve.PlotAux.Plot.plot(), shipHydrostatics.PlotAux.Plot.plotCoeffs(), shipHydrostatics.PlotAux.Plot.plotStability(), and shipHydrostatics.PlotAux.Plot.plotVolume().
removeSerie()
def Plot.removeSerie (index)
Remove a data serie from the active plot.
Keyword arguments:
index -- Index of the serie to remove.
References getPlot().
Referenced by plotSeries.TaskPanel.TaskPanel.onRemove().
save()
def Plot.save (path, figsize = None, dpi = None)
Save plot.
Keyword arguments:
path -- Destination file path.
figsize -- w,h figure size tuple in inches.
dpi -- Dots per inch.
References getPlot().
Referenced by plotSave.TaskPanel.TaskPanel.accept().
series()
def Plot.series ()
Return all the lines from a selected plot.
References getPlot().
Referenced by legend(), plotSeries.TaskPanel.TaskPanel.onColor(), plotSeries.TaskPanel.TaskPanel.onData(), plotSeries.TaskPanel.TaskPanel.onRemove(), plotSeries.TaskPanel.TaskPanel.setList(), and plotSeries.TaskPanel.TaskPanel.updateUI().
title()
def Plot.title (string)
Setup the plot title.
Keyword arguments:
string -- Plot title.
References getPlot().
Referenced by plotLabels.TaskPanel.TaskPanel.onLabels().
xlabel()
def Plot.xlabel (string)
Setup the x label.
Keyword arguments:
string -- Title to set.
References getPlot().
Referenced by plotLabels.TaskPanel.TaskPanel.onLabels(), plotAxes.TaskPanel.TaskPanel.onOffset(), shipCapacityCurve.PlotAux.Plot.plot(), shipGZ.PlotAux.Plot.plot(), shipAreasCurve.PlotAux.Plot.plot(), shipHydrostatics.PlotAux.Plot.plotCoeffs(), shipHydrostatics.PlotAux.Plot.plotStability(), and shipHydrostatics.PlotAux.Plot.plotVolume().
ylabel()
def Plot.ylabel (string)
Setup the y label.
Keyword arguments:
string -- Title to set.
References getPlot().
Referenced by plotLabels.TaskPanel.TaskPanel.onLabels(), plotAxes.TaskPanel.TaskPanel.onOffset(), shipCapacityCurve.PlotAux.Plot.plot(), shipGZ.PlotAux.Plot.plot(), shipAreasCurve.PlotAux.Plot.plot(), shipHydrostatics.PlotAux.Plot.plotCoeffs(), shipHydrostatics.PlotAux.Plot.plotStability(), and shipHydrostatics.PlotAux.Plot.plotVolume().
Variable Documentation
msg
Plot.msg
Initial value:
 =  PySide.QtGui.QApplication.translate(
         "plot_console",
         "matplotlib not found, so Plot module can not be loaded",
         None)