FreeCAD: Sketcher::ExternalGeometryExtensionPy Class Reference
Sketcher::ExternalGeometryExtensionPy Class Reference
The python export class for ExternalGeometryExtension.
#include <ExternalGeometryExtensionPy.h>
Public Types
typedef ExternalGeometryExtension * PointerType
Public Types inherited from Part::GeometryExtensionPy
typedef GeometryExtension * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
ExternalGeometryExtensionPy (ExternalGeometryExtension *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Part::GeometryExtensionPy
GeometryExtensionPy (GeometryExtension *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * copy (PyObject *args)
implementer for the copy() method
Py::String getName (void) const
getter for the Name attribute
void setName (Py::String arg)
setter for the Name attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeometryExtension * getGeometryExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::GeometryExtensionPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_getName (PyObject *self, void *closure)
getter callback for the Name attribute
static int staticCallback_setName (PyObject *self, PyObject *value, void *closure)
setter callback for the Name attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of ExternalGeometryExtensionPy.
static PyMethodDef Methods []
Methods structure of ExternalGeometryExtensionPy.
static PyTypeObject Type
Type structure of ExternalGeometryExtensionPy.
Static Public Attributes inherited from Part::GeometryExtensionPy
static PyGetSetDef GetterSetter []
Attribute structure of GeometryExtensionPy.
static PyMethodDef Methods []
Methods structure of GeometryExtensionPy.
static PyTypeObject Type
Type structure of GeometryExtensionPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~ExternalGeometryExtensionPy ()
Protected Member Functions inherited from Part::GeometryExtensionPy
~GeometryExtensionPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * testFlag (PyObject *args)
implementer for the testFlag() method
PyObject * setFlag (PyObject *args)
implementer for the setFlag() method
static PyObject * staticCallback_testFlag (PyObject *self, PyObject *args)
callback for the testFlag() method
static PyObject * staticCallback_setFlag (PyObject *self, PyObject *args)
callback for the setFlag() method
callbacks and implementers for the python object attributes
Py::String getRef (void) const
getter for the Ref attribute
void setRef (Py::String arg)
setter for the Ref attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ExternalGeometryExtension * getExternalGeometryExtensionPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getRef (PyObject *self, void *closure)
getter callback for the Ref attribute
static int staticCallback_setRef (PyObject *self, PyObject *value, void *closure)
setter callback for the Ref attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for ExternalGeometryExtension.
Member Typedef Documentation
PointerType
typedef ExternalGeometryExtension* Sketcher::ExternalGeometryExtensionPy::PointerType
Constructor & Destructor Documentation
~ExternalGeometryExtensionPy()
ExternalGeometryExtensionPy::~ExternalGeometryExtensionPy () protected
ExternalGeometryExtensionPy()
ExternalGeometryExtensionPy::ExternalGeometryExtensionPy (ExternalGeometryExtension * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getCustomAttributes()
PyObject * ExternalGeometryExtensionPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getExternalGeometryExtensionPtr()
ExternalGeometryExtension * ExternalGeometryExtensionPy::getExternalGeometryExtensionPtr (void) const
getter for the object handled by this class
Referenced by getRef(), representation(), setFlag(), setRef(), and testFlag().
getRef()
Py::String ExternalGeometryExtensionPy::getRef (void) const
getter for the Ref attribute
References getExternalGeometryExtensionPtr().
Referenced by staticCallback_getRef().
GetType()
virtual PyTypeObject* Sketcher::ExternalGeometryExtensionPy::GetType (void) virtual
Reimplemented from Part::GeometryExtensionPy.
PyInit()
int ExternalGeometryExtensionPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::GeometryExtensionPy.
PyMake()
PyObject * ExternalGeometryExtensionPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References ExternalGeometryExtensionPy().
representation()
std::string ExternalGeometryExtensionPy::representation (void) const
References Sketcher::ExternalGeometryExtension::flag2str, getExternalGeometryExtensionPtr(), Part::GeometryExtension::getName(), Part::GeometryExtensionPy::getName(), Sketcher::ExternalGeometryExtension::getRef(), Sketcher::ExternalGeometryExtension::NumFlags, and testFlag().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int ExternalGeometryExtensionPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setFlag()
PyObject * ExternalGeometryExtensionPy::setFlag (PyObject * args)
implementer for the setFlag() method
References getExternalGeometryExtensionPtr(), and Sketcher::ExternalGeometryExtension::setFlag().
Referenced by staticCallback_setFlag().
setRef()
void ExternalGeometryExtensionPy::setRef (Py::String arg)
setter for the Ref attribute
References getExternalGeometryExtensionPtr(), and Sketcher::ExternalGeometryExtension::setRef().
Referenced by staticCallback_setRef().
staticCallback_getRef()
PyObject * ExternalGeometryExtensionPy::staticCallback_getRef (PyObject * self, void * closure) static
getter callback for the Ref attribute
References Base::BaseExceptionFreeCADError, getRef(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setFlag()
PyObject * ExternalGeometryExtensionPy::staticCallback_setFlag (PyObject * self, PyObject * args) static
callback for the setFlag() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setFlag(), and Base::PyObjectBase::startNotify().
staticCallback_setRef()
int ExternalGeometryExtensionPy::staticCallback_setRef (PyObject * self, PyObject * value, void * closure) static
setter callback for the Ref attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setRef().
staticCallback_testFlag()
PyObject * ExternalGeometryExtensionPy::staticCallback_testFlag (PyObject * self, PyObject * args) static
callback for the testFlag() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and testFlag().
testFlag()
PyObject * ExternalGeometryExtensionPy::testFlag (PyObject * args)
implementer for the testFlag() method
References getExternalGeometryExtensionPtr().
Referenced by representation(), and staticCallback_testFlag().
Member Data Documentation
GetterSetter
PyGetSetDef ExternalGeometryExtensionPy::GetterSetter static
Initial value:
= {
    {"Ref",
        (getter) staticCallback_getRef,
        (setter) staticCallback_setRef,
        "\n                returns the reference string of this external geometry.\n            ",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of ExternalGeometryExtensionPy.
Methods
PyMethodDef ExternalGeometryExtensionPy::Methods static
Initial value:
= {
    {"testFlag",
        reinterpret_cast<PyCFunction>( staticCallback_testFlag ),
        METH_VARARGS,
        "returns a boolean indicating whether the given bit is set."
    },
    {"setFlag",
        reinterpret_cast<PyCFunction>( staticCallback_setFlag ),
        METH_VARARGS,
        "sets the given bit to true/false."
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of ExternalGeometryExtensionPy.
Type
PyTypeObject ExternalGeometryExtensionPy::Type static
Type structure of ExternalGeometryExtensionPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Sketcher/App/ExternalGeometryExtensionPy.h
Sources/FreeCAD/src/Mod/Sketcher/App/ExternalGeometryExtensionPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Sketcher/App/ExternalGeometryExtensionPy.cpp