FreeCAD: TechDrawGui::TaskDlgHatch Class Reference
TechDrawGui::TaskDlgHatch Class Reference
#include <TaskHatch.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void clicked (int)
is called by the framework if an button is clicked which has no accept or reject role
const ViewProviderHatch * getViewProvider () const
virtual void helpRequested ()
is called by the framework if the user presses the help button
virtual bool isAllowedAlterDocument (void) const
virtual void open ()
is called the TaskView when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setCreateMode (bool b)
TaskDlgHatch (TechDraw::DrawHatch *inHatch, TechDrawGui::ViewProviderHatch *inVp, bool mode)
void update ()
~TaskDlgHatch ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
ButtonPosition buttonPosition () const
bool canClose () const
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
tells the framework which buttons are wished for the dialog
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Protected Attributes
const ViewProviderHatch * viewProvider
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Constructor & Destructor Documentation
TaskDlgHatch()
TaskDlgHatch::TaskDlgHatch (TechDraw::DrawHatch * inHatch, TechDrawGui::ViewProviderHatch * inVp, bool mode)
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
~TaskDlgHatch()
TaskDlgHatch::~TaskDlgHatch ()
Member Function Documentation
accept()
bool TaskDlgHatch::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References TechDrawGui::TaskHatch::accept().
clicked()
void TaskDlgHatch::clicked (int i) virtual
is called by the framework if an button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
getViewProvider()
const ViewProviderHatch* TechDrawGui::TaskDlgHatch::getViewProvider () const
References viewProvider.
Referenced by TechDrawGui::ViewProviderHatch::setEdit().
helpRequested()
virtual void TechDrawGui::TaskDlgHatch::helpRequested () virtual
is called by the framework if the user presses the help button
Reimplemented from Gui::TaskView::TaskDialog.
isAllowedAlterDocument()
virtual bool TechDrawGui::TaskDlgHatch::isAllowedAlterDocument (void) const virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
open()
void TaskDlgHatch::open () virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
reject()
bool TaskDlgHatch::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References TechDrawGui::TaskHatch::reject().
setCreateMode()
void TaskDlgHatch::setCreateMode (bool b)
References TechDrawGui::TaskHatch::setCreateMode().
Referenced by TechDrawGui::ViewProviderHatch::setEdit().
update()
void TaskDlgHatch::update ()
Referenced by ArchAxis.CommandArchGrid::IsActive().
Member Data Documentation
viewProvider
const ViewProviderHatch* TechDrawGui::TaskDlgHatch::viewProvider protected
Referenced by getViewProvider().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/TaskHatch.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/TaskHatch.cpp