FreeCAD: feminout.exportNastranMesh Namespace Reference
feminout.exportNastranMesh Namespace Reference
Functions
def export (objectslist, filename)
def get_export_element_type (femmesh, femelement_table=None)
def get_pynastran_mesh (femnodes_mesh, femelement_table, export_element_type)
def write (fem_mesh, filename)
Variables
string missing_code_pnynasmesh
dictionary nastran_ele_types
Function Documentation
export()
def feminout.exportNastranMesh.export (objectslist, filename)
References feminout.exportNastranMesh.write().
get_export_element_type()
def feminout.exportNastranMesh.get_export_element_type (femmesh, femelement_table = None)
Referenced by feminout.exportNastranMesh.write().
get_pynastran_mesh()
def feminout.exportNastranMesh.get_pynastran_mesh (femnodes_mesh, femelement_table, export_element_type)
Referenced by feminout.exportNastranMesh.write().
write()
def feminout.exportNastranMesh.write (fem_mesh, filename)
directly write a FemMesh to a pyNastran mesh file format
fem_mesh: a FemMesh
References feminout.exportNastranMesh.get_export_element_type(), and feminout.exportNastranMesh.get_pynastran_mesh().
Referenced by feminout.exportNastranMesh.export().
Variable Documentation
missing_code_pnynasmesh
string feminout.exportNastranMesh.missing_code_pnynasmesh
Initial value:
=  """
model.sol = 101  # is this needed?
# case control
from pyNastran.bdf.bdf import CaseControlDeck
cc = CaseControlDeck([
    #"ECHO = NONE",
    "TITLE = pyNastran for generating solverinput for for Mystran",
    #"SUBCASE 1",
])
model.case_control_deck = cc\n\n
"""
nastran_ele_types
dictionary feminout.exportNastranMesh.nastran_ele_types
Initial value:
=  {
    "tetra4": "ctetra4",
    "tetra10": "ctetra10",
    "hexa8": None,
    "hexa20": None,
    "tria3": "ctria3",
    "tria6": None,
    "quad4": "cquad4",
    "quad8": None,
    "seg2": "cbar",
    "seg3": None,
    "None": None,
}