FreeCAD: PartGui::ResultModel Class Reference
PartGui::ResultModel Class Reference
#include <TaskCheckGeometry.h>
Public Member Functions
virtual int columnCount (const QModelIndex &parent) const
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
ResultEntry * getEntry (const QModelIndex &index)
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
QModelIndex index (int row, int column, const QModelIndex &parent) const
QModelIndex parent (const QModelIndex &child) const
ResultModel (QObject *parent=nullptr)
virtual int rowCount (const QModelIndex &parent) const
void setResults (ResultEntry *resultsIn)
~ResultModel ()
Constructor & Destructor Documentation
ResultModel()
ResultModel::ResultModel (QObject * parent = nullptr)
~ResultModel()
ResultModel::~ResultModel ()
Member Function Documentation
columnCount()
int ResultModel::columnCount (const QModelIndex & parent) const virtual
References parent().
data()
QVariant ResultModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
References PartGui::ResultEntry::error, PartGui::ResultEntry::name, and PartGui::ResultEntry::type.
Referenced by Mod.Show.mTempoVis.TempoVis::activateWorkbench(), Mod.Show.SceneDetail.SceneDetail::apply_data(), importIFClegacy.IfcSchema::capitalize(), Mod.Show.mTempoVis.TempoVis::forget(), Mod.Show.mTempoVis.TempoVis::forgetDetail(), Mod.Show.mTempoVis.TempoVis::has(), ArchSchedule.CommandArchSchedule::IsActive(), importIFClegacy.IfcSchema::readEntities(), importIFClegacy.IfcSchema::readTypes(), Mod.Show.mTempoVis.TempoVis::restore(), Mod.Show.mTempoVis.TempoVis::save(), Mod.Show.mTempoVis.TempoVis::stored_val(), FeaturePython.ViewProviderOctahedron::updateData(), and Dice3DS.dom3ds.UndefinedChunk::write().
getEntry()
ResultEntry * ResultModel::getEntry (const QModelIndex & index)
headerData()
QVariant ResultModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
index()
QModelIndex ResultModel::index (int row, int column, const QModelIndex & parent) const
References PartGui::ResultEntry::children, and parent().
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::addSegment(), Dice3DS.dom3ds.FileLikeBuffer::advance(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::begin(), Spreadsheet_legacy.MathParser::getValue(), Spreadsheet_legacy.MathParser::hasNext(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::interval(), PathScripts.PathJobDlg.JobCreate::item1ValueChanged(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::length(), Spreadsheet_legacy.MathParser::parseAddition(), Spreadsheet_legacy.MathParser::parseMultiplication(), Spreadsheet_legacy.MathParser::parseNegative(), Spreadsheet_legacy.MathParser::parseNumber(), Spreadsheet_legacy.MathParser::parseParenthesis(), Spreadsheet_legacy.MathParser::parseVariable(), Spreadsheet_legacy.MathParser::peek(), Dice3DS.dom3ds.FileLikeBuffer::read(), Dice3DS.dom3ds.FileLikeBuffer::read_fbuf(), Dice3DS.dom3ds.FileLikeBuffer::read_rest(), Dice3DS.dom3ds.FileLikeBuffer::read_to_nul(), Dice3DS.dom3ds.FileLikeBuffer::room_for_chunks(), Dice3DS.dom3ds.FileLikeBuffer::seek(), package_list.PackageListItemModel::setData(), PathScripts.PathJobDlg.JobCreate::setupColumnEditor(), Spreadsheet_legacy.MathParser::skipWhitespace(), Dice3DS.dom3ds.FileLikeBuffer::tell(), package_list.PackageListItemModel::update_item_icon(), package_list.PackageListItemModel::update_item_status(), automotive_design.index_expression::wr1(), and automotive_design.index_expression::wr2().
parent()
QModelIndex ResultModel::parent (const QModelIndex & child) const
References PartGui::ResultEntry::children, and PartGui::ResultEntry::parent.
Referenced by PathScripts.PathSimulatorGui.CAMSimTaskUi::accept(), columnCount(), Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium(), index(), PathScripts.PathSimulatorGui.CAMSimTaskUi::reject(), rowCount(), and PathScripts.PathOpGui.TaskPanelPage::setParent().
rowCount()
int ResultModel::rowCount (const QModelIndex & parent) const virtual
References PartGui::ResultEntry::children, and parent().
Referenced by package_list.PackageListItemModel::append_item(), and package_list.PackageListItemModel::clear().
setResults()
void ResultModel::setResults (ResultEntry * resultsIn)
Referenced by PartGui::TaskCheckGeometryResults::goCheck().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/TaskCheckGeometry.h
FreeCAD/src/Mod/Part/Gui/TaskCheckGeometry.cpp