FreeCAD: ConstraintItem Class Reference
ConstraintItem Class Reference
Public Member Functions
ConstraintItem (const Sketcher::SketchObject *s, ViewProviderSketch *sketchview, int ConstNbr)
Sketcher::ConstraintType constraintType () const
QVariant data (int role) const
bool isActive () const
bool isDimensional () const
bool isDriving () const
bool isEnforceable () const
bool isInVirtualSpace () const
void setData (int role, const QVariant &value)
void updateVirtualSpaceStatus ()
~ConstraintItem ()
Public Attributes
int ConstraintNbr
const Sketcher::SketchObject * sketch
const ViewProviderSketch * sketchView
QVariant value
Constructor & Destructor Documentation
ConstraintItem()
ConstraintItem::ConstraintItem (const Sketcher::SketchObject * s, ViewProviderSketch * sketchview, int ConstNbr)
References updateVirtualSpaceStatus().
~ConstraintItem()
ConstraintItem::~ConstraintItem ()
Member Function Documentation
constraintType()
Sketcher::ConstraintType ConstraintItem::constraintType () const
References ConstraintNbr, Sketcher::SketchObject::Constraints, and sketch.
data()
QVariant ConstraintItem::data (int role) const
References Sketcher::Constraint::AlignmentType, Sketcher::Angle, Gui::BitmapFactory(), Sketcher::Block, Sketcher::Coincident, ConstraintNbr, Sketcher::SketchObject::Constraints, Sketcher::PropertyConstraintList::createPath(), Sketcher::Diameter, DraftVecUtils::dist(), Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, Sketcher::EllipseFocus1, Sketcher::EllipseFocus2, Sketcher::EllipseMajorDiameter, Sketcher::EllipseMinorDiameter, Sketcher::Equal, App::PropertyExpressionEngine::ExpressionInfo::expression, Sketcher::Constraint::First, Sketcher::Constraint::FirstPos, Base::Tools::fromStdString(), App::GetApplication(), ParameterGrp::GetBool(), Sketcher::PropertyConstraintList::getConstraintName(), App::DocumentObject::getExpression(), App::Application::GetParameterGroupByPath(), Sketcher::Constraint::getPresentationValue(), Sketcher::PropertyConstraintList::getSize(), Base::Quantity::getUserString(), Base::Quantity::getValue(), Sketcher::Horizontal, Sketcher::InternalAlignment, Sketcher::Constraint::isActive, Sketcher::Constraint::isDriving, Sketcher::Constraint::Name, Sketcher::Parallel, Sketcher::Perpendicular, Sketcher::PointOnObject, Sketcher::Radius, Sketcher::Constraint::Second, Sketcher::Constraint::SecondPos, sketch, Sketcher::SnellsLaw, Sketcher::Symmetric, Sketcher::Tangent, Sketcher::Constraint::Third, Sketcher::Constraint::ThirdPos, Sketcher::Constraint::Type, Sketcher::Undef, value, Sketcher::Vertical, and Sketcher::Weight.
Referenced by Mod.Show.mTempoVis.TempoVis::activateWorkbench(), Mod.Show.SceneDetail.SceneDetail::apply_data(), importIFClegacy.IfcSchema::capitalize(), Mod.Show.mTempoVis.TempoVis::forget(), Mod.Show.mTempoVis.TempoVis::forgetDetail(), Mod.Show.mTempoVis.TempoVis::has(), ArchSchedule.CommandArchSchedule::IsActive(), SketcherGui::TaskSketcherConstraints::on_listWidgetConstraints_itemChanged(), importIFClegacy.IfcSchema::readEntities(), importIFClegacy.IfcSchema::readTypes(), Mod.Show.mTempoVis.TempoVis::restore(), Mod.Show.mTempoVis.TempoVis::save(), Mod.Show.mTempoVis.TempoVis::stored_val(), FeaturePython.ViewProviderOctahedron::updateData(), and Dice3DS.dom3ds.UndefinedChunk::write().
isActive()
bool ConstraintItem::isActive (void) const
References ConstraintNbr, Sketcher::SketchObject::Constraints, and sketch.
Referenced by SketcherGui::ConstraintView::contextMenuEvent(), and SketcherGui::ConstraintView::updateActiveStatus().
isDimensional()
bool ConstraintItem::isDimensional () const
References ConstraintNbr, Sketcher::SketchObject::Constraints, and sketch.
Referenced by SketcherGui::ConstraintView::contextMenuEvent(), and SketcherGui::TaskSketcherConstraints::on_listWidgetConstraints_itemActivated().
isDriving()
bool ConstraintItem::isDriving () const
References ConstraintNbr, Sketcher::SketchObject::Constraints, and sketch.
Referenced by SketcherGui::ConstraintView::updateDrivingStatus().
isEnforceable()
bool ConstraintItem::isEnforceable () const
References Sketcher::Angle, Sketcher::Block, Sketcher::Coincident, ConstraintNbr, Sketcher::SketchObject::Constraints, Sketcher::Diameter, Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, Sketcher::Equal, Sketcher::Constraint::First, Sketcher::Horizontal, Sketcher::InternalAlignment, Sketcher::NumConstraintTypes, Sketcher::Parallel, Sketcher::Perpendicular, Sketcher::PointOnObject, Sketcher::Radius, Sketcher::Constraint::Second, sketch, Sketcher::SnellsLaw, Sketcher::Symmetric, Sketcher::Tangent, Sketcher::Constraint::Third, Sketcher::Constraint::Type, Sketcher::Vertical, and Sketcher::Weight.
Referenced by SketcherGui::ConstraintView::contextMenuEvent().
isInVirtualSpace()
bool ConstraintItem::isInVirtualSpace () const
References ConstraintNbr, Sketcher::SketchObject::Constraints, and sketch.
Referenced by updateVirtualSpaceStatus().
setData()
void ConstraintItem::setData (int role, const QVariant & value)
References value.
Referenced by package_list.PackageListItemModel::update_item_icon(), and package_list.PackageListItemModel::update_item_status().
updateVirtualSpaceStatus()
void ConstraintItem::updateVirtualSpaceStatus ()
References SketcherGui::ViewProviderSketch::getIsShownVirtualSpace(), isInVirtualSpace(), and sketchView.
Referenced by ConstraintItem().
Member Data Documentation
ConstraintNbr
int ConstraintItem::ConstraintNbr
Referenced by constraintType(), data(), isActive(), isDimensional(), isDriving(), isEnforceable(), isInVirtualSpace(), SketcherGui::TaskSketcherConstraints::on_listWidgetConstraints_itemActivated(), SketcherGui::TaskSketcherConstraints::on_listWidgetConstraints_itemChanged(), SketcherGui::TaskSketcherConstraints::on_listWidgetConstraints_itemSelectionChanged(), SketcherGui::TaskSketcherConstraints::onSelectionChanged(), ExpressionDelegate::paint(), and SketcherGui::ConstraintView::swapNamedOfSelectedItems().
sketch
const Sketcher::SketchObject* ConstraintItem::sketch
Referenced by Mod.PartDesign.WizardShaft.ShaftFeature.ShaftFeature::addSegment(), constraintType(), data(), isActive(), isDimensional(), isDriving(), isEnforceable(), isInVirtualSpace(), ExpressionDelegate::paint(), SketcherGui::ConstraintView::swapNamedOfSelectedItems(), and Mod.PartDesign.WizardShaft.ShaftFeature.ShaftFeature::updateSegment().
sketchView
const ViewProviderSketch* ConstraintItem::sketchView
Referenced by updateVirtualSpaceStatus().
value
QVariant ConstraintItem::value
Referenced by data(), PathScripts.PathProperty.Property::displayString(), PathScripts.PathProperty.PropertyQuantity::displayString(), PathScripts.PathSetupSheetOpPrototype.Property::displayString(), PathScripts.PathSetupSheetOpPrototype.PropertyQuantity::displayString(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), PathScripts.PathProperty.Property::getValue(), PathScripts.PathSetupSheetOpPrototype.Property::getValue(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), setData(), PathScripts.PathProperty.Property::setValue(), and PathScripts.PathSetupSheetOpPrototype.Property::setValue().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp