FreeCAD: MeshGui::Annotation Class Reference
MeshGui::Annotation Class Reference
Public Member Functions
Annotation (Gui::ViewProviderDocumentObject *vp, const QString &s, const SbVec3f &p, const SbVec3f &n)
void show ()
~Annotation ()
Static Public Member Functions
static void run (void *data, SoSensor *sensor)
Constructor & Destructor Documentation
Annotation()
MeshGui::Annotation::Annotation (Gui::ViewProviderDocumentObject * vp, const QString & s, const SbVec3f & p, const SbVec3f & n)
~Annotation()
MeshGui::Annotation::~Annotation ()
Member Function Documentation
run()
static void MeshGui::Annotation::run (void * data, SoSensor * sensor) static
References show().
Referenced by femexamples.examplesgui.FemExamples::clicked(), MeshGui::ViewProviderMeshCurvature::curvatureInfoCallback(), and femsolver.task.Task::protector().
show()
void MeshGui::Annotation::show (void)
References App::AnnotationLabel::BasePosition, Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::DocumentObject::Label, App::AnnotationLabel::LabelText, App::PropertyVector::setValue(), App::PropertyString::setValue(), App::PropertyStringList::setValues(), and App::AnnotationLabel::TextPosition.
Referenced by run(), Mod.Show.mTempoVis.TempoVis::show_all_dependencies(), and Mod.Show.mTempoVis.TempoVis::show_all_dependent().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Mesh/Gui/ViewProviderCurvature.cpp