FreeCAD: Gui::SoFCEnableHighlightAction Class Reference
Gui::SoFCEnableHighlightAction Class Reference
The SoFCEnableHighlightAction class is used to inform an SoFCSelection node whether preselection is enabled or disabled.
#include <SoFCSelectionAction.h>
Public Member Functions
SoFCEnableHighlightAction (const SbBool &sel)
~SoFCEnableHighlightAction ()
Static Public Member Functions
static void finish (void)
static void initClass ()
The order of the defined SO_ACTION_ADD_METHOD statements is very important.
Public Attributes
const SbBool & highlight
Protected Member Functions
virtual void beginTraversal (SoNode *node)
Detailed Description
The SoFCEnableHighlightAction class is used to inform an SoFCSelection node whether preselection is enabled or disabled.
Author
Werner Mayer
Constructor & Destructor Documentation
SoFCEnableHighlightAction()
SoFCEnableHighlightAction::SoFCEnableHighlightAction (const SbBool & sel)
~SoFCEnableHighlightAction()
SoFCEnableHighlightAction::~SoFCEnableHighlightAction ()
Member Function Documentation
beginTraversal()
void SoFCEnableHighlightAction::beginTraversal (SoNode * node) protected virtual
finish()
void SoFCEnableHighlightAction::finish (void) static
Referenced by drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), draftguitools.gui_shapestrings.ShapeString::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_split.Split::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_edit.Edit::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_selectplane.Draft_SelectPlane::checkSelection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_labels.Label::create(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_shapestrings.ShapeString::createObject(), draftguitools.gui_texts.Text::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::escape(), Gui::SoFCDB::finish(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_fillets.Fillet::numericRadius(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickAlign(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickAuto(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickCenter(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickFront(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickMove(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickPrevious(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickSide(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickTop(), draftguitools.gui_array_simple.Array::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
initClass()
void SoFCEnableHighlightAction::initClass (void) static
The order of the defined SO_ACTION_ADD_METHOD statements is very important.
First the base classes and afterwards subclasses of them must be listed, otherwise the registered methods of subclasses will be overridden. For more details see the thread in the Coin3d forum https://www.coin3d.org/pipermail/coin-discuss/2004-May/004346.html. This means that SoSwitch must be listed after SoGroup and SoFCSelection after SoSeparator because both classes inherits the others.
Referenced by Gui::SoFCDB::init().
Member Data Documentation
highlight
const SbBool& Gui::SoFCEnableHighlightAction::highlight
Referenced by Gui::SoFCSelection::doAction(), and Gui::SoFCUnifiedSelection::doAction().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SoFCSelectionAction.h
Sources/FreeCAD/src/Gui/SoFCSelectionAction.cpp