FreeCAD: Gui::NS::IdleState Class Reference
Gui::NS::IdleState Class Reference
Public Types
typedef sc::custom_reaction< NS::Event > reactions
Public Member Functions
IdleState (my_context ctx)
sc::result react (const NS::Event &ev)
virtual ~IdleState ()
Member Typedef Documentation
reactions
typedef sc::custom_reaction<NS::Event> Gui::NS::IdleState::reactions
Constructor & Destructor Documentation
IdleState()
Gui::NS::IdleState::IdleState (my_context ctx)
References Base::Console(), Gui::NavigationStyle::IDLE, and Base::ConsoleSingleton::Log().
~IdleState()
virtual Gui::NS::IdleState::~IdleState () virtual
Member Function Documentation
react()
sc::result Gui::NS::IdleState::react (const NS::Event & ev)
References Gui::NS::Event::asKeyboardEvent(), Gui::NS::Event::flags, Gui::NavigationStyle::IDLE, Gui::NS::Event::inventor_event, Gui::NS::Event::isGestureActive(), Gui::NS::Event::isGestureEvent(), Gui::NS::Event::isKeyboardEvent(), Gui::NS::Event::isMotion3Event(), Gui::NS::Event::isMouseButtonEvent(), Gui::NS::Event::isPress(), Gui::NS::Event::mbstate(), Gui::NavigationStyle::SEEK_MODE, Gui::NavigationStyle::SEEK_WAIT_MODE, and Gui::NavigationStyle::SPINNING.
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/GestureNavigationStyle.cpp