FreeCAD: App::Property Class Reference
App::Property Class Reference abstract
Base class of all properties This is the father of all properties.
#include <Property.h>
Public Types
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , Busy = 15 ,
CopyOnChange = 16 , UserEdit = 17 , PropStaticBegin = 21 , PropDynamic = 21 ,
PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 , PropTransient = 25 ,
PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 , User1 = 28 ,
User2 = 29 , User3 = 30 , User4 = 31
}
Public Member Functions
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual Property * Copy (void) const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
int64_t getID () const
Return a unique ID for the property.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const char * getName (void) const
Get the name of this property in the belonging container With hasName() it can be checked beforehand if a valid name is set.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
bool hasName () const
Check if the property has a name set.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Check if the passed name is valid.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Public Attributes
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Protected Attributes
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Friends
class DynamicProperty
class PropertyContainer
struct PropertyData
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Base class of all properties This is the father of all properties.
Properties are objects which are used in the document tree to parametrize e.g. features and their graphical output. They are also used to gain access from the scripting facility. /par This abstract base class defines all methods shared by all possible properties. It is also possible to define user properties and use them in the framework...
Member Enumeration Documentation
Status
enum App::Property::Status
Enumerator
Touched
Immutable
ReadOnly
Hidden
Transient
MaterialEdit
NoMaterialListEdit
Output
LockDynamic
NoModify
PartialTrigger
NoRecompute
Single
Ordered
EvalOnRestore
Busy
CopyOnChange
UserEdit
PropStaticBegin
PropDynamic
PropNoPersist
PropNoRecompute
PropReadOnly
PropTransient
PropHidden
PropOutput
PropStaticEnd
User1
User2
User3
User4
Constructor & Destructor Documentation
Property()
Property::Property ()
~Property()
Property::~Property () virtual
Member Function Documentation
aboutToSetChildValue()
virtual void App::Property::aboutToSetChildValue (Property &) virtual
Called before a child property changing value.
Reimplemented in App::PropertyXLinkContainer, and App::PropertyXLinkSubList.
Referenced by App::PropertyXLink::aboutToSetValue().
aboutToSetValue()
void Property::aboutToSetValue (void) protected virtual
Gets called by all setValue() methods before the value has changed.
Reimplemented in App::PropertyFileIncluded, and App::PropertyXLink.
References App::PropertyContainer::onBeforeChange().
Referenced by App::PropertyXLinkSubList::aboutToSetChildValue(), App::PropertyFileIncluded::aboutToSetValue(), App::PropertyXLink::aboutToSetValue(), Sketcher::PropertyConstraintList::acceptGeometry(), App::PropertyLinkSubList::addValue(), App::PropertyXLinkContainer::breakLink(), Fem::PropertyFemMesh::Paste(), Fem::PropertyPostDataObject::Paste(), Mesh::PropertyNormalList::Paste(), Mesh::PropertyCurvatureList::Paste(), Mesh::PropertyMeshKernel::Paste(), Part::PropertyPartShape::Paste(), Path::PropertyPath::Paste(), Path::PropertyTool::Paste(), Path::PropertyTooltable::Paste(), Points::PropertyGreyValueList::Paste(), Points::PropertyNormalList::Paste(), Points::PropertyCurvatureList::Paste(), Points::PropertyPointKernel::Paste(), Robot::PropertyTrajectory::Paste(), App::PropertyMatrix::Paste(), App::PropertyPlacementLink::Paste(), App::PropertyPythonObject::Paste(), App::PropertyInteger::Paste(), App::PropertyPath::Paste(), App::PropertyIntegerSet::Paste(), App::PropertyMap::Paste(), App::PropertyFloat::Paste(), App::PropertyUUID::Paste(), App::PropertyBool::Paste(), App::PropertyColor::Paste(), App::PropertyMaterial::Paste(), Inspection::PropertyDistanceList::Paste(), Part::PropertyShapeHistory::Paste(), Part::PropertyFilletEdges::Paste(), Spreadsheet::PropertySpreadsheetQuantity::Paste(), App::PropertyVector::Paste(), App::PropertyPlacement::Paste(), App::PropertyRotation::Paste(), App::PropertyXLinkSubList::Paste(), App::PropertyPersistentObject::Paste(), App::PropertyExpressionEngine::renameExpressions(), App::PropertyMatrix::Restore(), App::PropertyPythonObject::Restore(), App::PropertyEnumeration::Restore(), App::PropertyString::Restore(), App::PropertyMaterial::Restore(), Mesh::PropertyMeshKernel::Restore(), Points::PropertyPointKernel::Restore(), App::PropertyVector::Restore(), App::PropertyPlacement::Restore(), App::PropertyRotation::Restore(), App::PropertyPythonObject::RestoreDocFile(), Fem::PropertyFemMesh::RestoreDocFile(), Fem::PropertyPostDataObject::RestoreDocFile(), Mesh::PropertyMeshKernel::RestoreDocFile(), Path::PropertyPath::RestoreDocFile(), Points::PropertyPointKernel::RestoreDocFile(), Fem::PropertyPostDataObject::scale(), Sketcher::PropertyConstraintList::set1Value(), Part::PropertyGeometryList::set1Value(), App::PropertyMaterial::setAmbientColor(), App::PropertyMaterial::setDiffuseColor(), App::PropertyMaterial::setEmissiveColor(), App::PropertyEnumeration::setEnums(), App::PropertyEnumeration::setEnumVector(), App::PropertyQuantity::setPathValue(), Sketcher::PropertyConstraintList::setPathValue(), Mesh::PropertyMeshKernel::setPointIndices(), App::PropertyPythonObject::setPyObject(), App::PropertyInteger::setPyObject(), App::PropertyEnumeration::setPyObject(), App::PropertyIntegerConstraint::setPyObject(), App::PropertyFloat::setPyObject(), App::PropertyFloatConstraint::setPyObject(), App::PropertyQuantity::setPyObject(), App::PropertyMaterial::setShininess(), App::PropertyMaterial::setSpecularColor(), App::PropertyMaterial::setTransparency(), App::PropertyLink::setValue(), App::PropertyLinkSub::setValue(), App::PropertyBool::setValue(), TechDraw::PropertyCenterLineList::setValue(), App::PropertyMatrix::setValue(), App::PropertyPlacement::setValue(), App::PropertyRotation::setValue(), App::PropertyUUID::setValue(), App::PropertyVector::setValue(), Mesh::PropertyNormalList::setValue(), Points::PropertyNormalList::setValue(), App::PropertyPath::setValue(), App::PropertyString::setValue(), App::PropertyPersistentObject::setValue(), App::PropertyEnumeration::setValue(), App::PropertyColor::setValue(), Sketcher::PropertyConstraintList::setValue(), Mesh::PropertyCurvatureList::setValue(), Points::PropertyCurvatureList::setValue(), Fem::PropertyFemMesh::setValue(), Part::PropertyGeometryList::setValue(), TechDraw::PropertyGeomFormatList::setValue(), App::PropertyMaterial::setValue(), Mesh::PropertyMeshKernel::setValue(), Points::PropertyPointKernel::setValue(), Part::PropertyShapeHistory::setValue(), App::PropertyMap::setValue(), Path::PropertyTool::setValue(), Path::PropertyPath::setValue(), Path::PropertyTooltable::setValue(), Part::PropertyPartShape::setValue(), Robot::PropertyTrajectory::setValue(), Fem::PropertyPostDataObject::setValue(), TechDraw::PropertyCosmeticEdgeList::setValue(), TechDraw::PropertyCosmeticVertexList::setValue(), App::PropertyLinkSubList::setValue(), App::PropertyFloat::setValue(), Inspection::PropertyDistanceList::setValue(), Points::PropertyGreyValueList::setValue(), Spreadsheet::PropertyColumnWidths::setValue(), Part::PropertyFilletEdges::setValue(), Spreadsheet::PropertyRowHeights::setValue(), App::PropertyInteger::setValue(), App::PropertyIntegerSet::setValue(), App::PropertyPythonObject::setValue(), Fem::PropertyFemMesh::setValuePtr(), Mesh::PropertyMeshKernel::setValuePtr(), Spreadsheet::PropertyColumnWidths::setValues(), Spreadsheet::PropertyRowHeights::setValues(), App::PropertyMap::setValues(), App::PropertyIntegerSet::setValues(), Mesh::PropertyNormalList::setValues(), Points::PropertyNormalList::setValues(), TechDraw::PropertyCenterLineList::setValues(), TechDraw::PropertyCosmeticEdgeList::setValues(), TechDraw::PropertyCosmeticVertexList::setValues(), Mesh::PropertyCurvatureList::setValues(), Points::PropertyCurvatureList::setValues(), App::PropertyLinkSubList::setValues(), Part::PropertyFilletEdges::setValues(), Inspection::PropertyDistanceList::setValues(), Points::PropertyGreyValueList::setValues(), TechDraw::PropertyGeomFormatList::setValues(), Part::PropertyShapeHistory::setValues(), Sketcher::PropertyConstraintList::setValues(), Part::PropertyGeometryList::setValues(), Mesh::PropertyMeshKernel::startEditing(), Points::PropertyPointKernel::startEditing(), Mesh::PropertyMeshKernel::swapMesh(), Fem::PropertyFemMesh::transformGeometry(), Mesh::PropertyNormalList::transformGeometry(), Mesh::PropertyCurvatureList::transformGeometry(), Mesh::PropertyMeshKernel::transformGeometry(), Part::PropertyPartShape::transformGeometry(), Points::PropertyNormalList::transformGeometry(), Points::PropertyCurvatureList::transformGeometry(), and Points::PropertyPointKernel::transformGeometry().
afterRestore()
virtual void App::Property::afterRestore () virtual
Called at the beginning of Document::afterRestore()
This function is called without dependency sorting, because some types of link property can only reconstructs the linking information inside this function.
One example use case of this function is PropertyLinkSub that uses afterRestore() to parse and restore subname references, which may contain sub-object reference from external document, and there will be special mapping required during object import.
Another example is PropertyExpressionEngine which only parse the restored expression in afterRestore(). The reason, in addition to subname mapping like PropertyLinkSub, is that it can handle document name adjustment as well. It internally relies on PropertyXLink to store the external document path for external linking. When the external document is restored, its internal name may change due to name conflict with existing documents. PropertyExpressionEngine can now auto adjust external references without any problem.
Reimplemented in App::PropertyExpressionEngine, App::PropertyLinkSub, App::PropertyLinkSubList, App::PropertyXLink, App::PropertyXLinkSubList, App::PropertyXLinkContainer, and Spreadsheet::PropertySheet.
canonicalPath()
ObjectIdentifier Property::canonicalPath (const App::ObjectIdentifier & p) const virtual
Convert p to a canonical representation of it.
Reimplemented in App::PropertyExpressionEngine, and Sketcher::PropertyConstraintList.
Referenced by Gui::ExpressionBinding::bind().
Copy()
Property * Property::Copy (void) const pure virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implemented in App::PropertyFileIncluded, Mesh::PropertyNormalList, Mesh::PropertyCurvatureList, Mesh::PropertyMeshKernel, Points::PropertyGreyValueList, Points::PropertyNormalList, Points::PropertyCurvatureList, Points::PropertyPointKernel, App::PropertyRotation, App::PropertyMatrix, App::PropertyPlacementLink, App::PropertyPythonObject, App::PropertyInteger, App::PropertyPath, App::PropertyEnumeration, App::PropertyIntegerSet, App::PropertyMap, App::PropertyFloat, App::PropertyString, App::PropertyUUID, App::PropertyBool, App::PropertyColor, App::PropertyMaterial, Fem::PropertyFemMesh, Fem::PropertyPostDataObject, Inspection::PropertyDistanceList, Part::PropertyGeometryList, Part::PropertyPartShape, Part::PropertyShapeHistory, Part::PropertyFilletEdges, Path::PropertyPath, Path::PropertyTool, Path::PropertyTooltable, Robot::PropertyTrajectory, Spreadsheet::PropertyColumnWidths, Spreadsheet::PropertyRowHeights, Spreadsheet::PropertySpreadsheetQuantity, TechDraw::PropertyCenterLineList, TechDraw::PropertyCosmeticEdgeList, TechDraw::PropertyCosmeticVertexList, TechDraw::PropertyGeomFormatList, App::PropertyExpressionEngine, App::PropertyVector, App::PropertyVectorList, App::PropertyPlacement, App::PropertyPlacementList, App::PropertyLink, App::PropertyLinkList, App::PropertyLinkSub, App::PropertyLinkSubList, App::PropertyXLink, App::PropertyXLinkSubList, App::PropertyIntegerList, App::PropertyFloatList, App::PropertyStringList, App::PropertyBoolList, App::PropertyColorList, App::PropertyMaterialList, App::PropertyPersistentObject, Sketcher::PropertyConstraintList, and Spreadsheet::PropertySheet.
Referenced by App::TransactionObject::addOrRemoveProperty(), App::LinkBaseExtension::checkCopyOnChange(), PartGui::ViewProviderCustom::onChanged(), SketcherGui::ViewProviderCustom::onChanged(), and App::TransactionObject::setProperty().
destroy()
void Property::destroy (Property * p) static
For safe deleting of a dynamic property.
References App::PropertyCleaner::add().
Referenced by App::DynamicProperty::removeDynamicProperty().
getContainer()
PropertyContainer * App::Property::getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
Referenced by App::TransactionObject::addOrRemoveProperty(), App::PropertyLinkSubList::addValue(), App::PropertyExpressionEngine::adjustLink(), App::PropertyExpressionEngine::afterRestore(), App::PropertyLink::breakLink(), App::PropertyLinkList::breakLink(), App::PropertyLinkSub::breakLink(), App::PropertyLinkSubList::breakLink(), App::PropertyXLinkSubList::breakLink(), App::PropertyXLinkContainer::breakLink(), App::PropertyExpressionEngine::canonicalPath(), App::PropertyXLinkContainer::clearDeps(), App::PropertyLinkSub::CopyOnImportExternal(), App::PropertyLinkSubList::CopyOnImportExternal(), App::PropertyXLink::CopyOnImportExternal(), App::PropertyLinkSub::CopyOnLabelChange(), App::PropertyLinkSubList::CopyOnLabelChange(), App::PropertyXLink::CopyOnLabelChange(), App::PropertyLink::CopyOnLinkReplace(), App::PropertyLinkList::CopyOnLinkReplace(), App::PropertyLinkSub::CopyOnLinkReplace(), App::PropertyLinkSubList::CopyOnLinkReplace(), App::PropertyXLink::CopyOnLinkReplace(), App::PropertyExpressionEngine::execute(), App::PropertyFileIncluded::getDocTransientPath(), getPaths(), Part::PropertyPartShape::getPaths(), App::PropertyExpressionEngine::getPathsToDocumentObject(), App::PropertyExpressionEngine::hasSetValue(), App::PropertyLinkBase::hasSetValue(), Spreadsheet::PropertySheet::insertColumns(), Spreadsheet::PropertySheet::insertRows(), App::LinkBaseExtension::isCopyOnChangeProperty(), App::GeoFeatureGroupExtension::isLinkValid(), App::ObjectIdentifier::ObjectIdentifier(), PartGui::ViewProviderPartExt::onChanged(), PartGui::PropertyEnumAttacherItem::openTask(), App::DocumentObjectT::operator=(), Spreadsheet::PropertySheet::removeColumns(), Spreadsheet::PropertySheet::removeRows(), App::PropertyLink::resetLink(), App::PropertyString::Restore(), App::PropertyLink::Restore(), App::PropertyLinkList::Restore(), App::PropertyLinkSub::Restore(), App::PropertyLinkSubList::Restore(), App::PropertyXLink::Restore(), Fem::PropertyPostDataObject::RestoreDocFile(), Path::PropertyPath::RestoreDocFile(), App::PropertyXLink::restoreLink(), App::PropertyString::Save(), App::PropertyLinkSub::Save(), App::PropertyLinkSubList::Save(), App::PropertyXLink::Save(), App::PropertyXLinkContainer::Save(), Fem::PropertyPostDataObject::SaveDocFile(), App::PropertyLinkList::set1Value(), Spreadsheet::Cell::setAlias(), App::PropertyXLink::setAllowPartial(), Spreadsheet::PropertySheet::setPathValue(), App::TransactionObject::setProperty(), App::LinkBaseExtension::setProperty(), Part::PropertyGeometryList::setPyObject(), App::PropertyLinkList::setSize(), App::PropertyLink::setValue(), App::PropertyXLink::setValue(), App::PropertyLinkSub::setValue(), App::PropertyString::setValue(), App::PropertyLinkSubList::setValue(), App::PropertyLinkList::setValues(), App::PropertyLinkSubList::setValues(), Gui::RecoveryWriter::shouldWrite(), App::PropertyXLinkContainer::updateDeps(), App::PropertyExpressionEngine::updateElementReference(), Spreadsheet::PropertySheet::updateElementReference(), App::PropertyLinkSubList::updateElementReference(), App::PropertyLinkSubList::upgrade(), App::PropertyXLinkSubList::upgrade(), App::PropertyXLinkSub::upgrade(), App::PropertyLinkList::~PropertyLinkList(), App::PropertyLinkSub::~PropertyLinkSub(), and App::PropertyLinkSubList::~PropertyLinkSubList().
getDocumentation()
const char * Property::getDocumentation (void) const
Get the documentation of this property.
References App::PropertyContainer::getPropertyDocumentation().
Referenced by App::DynamicProperty::addProperty(), and Gui::PropertyEditor::PropertyItem::toolTip().
getEditorName()
virtual const char * App::Property::getEditorName (void) const virtual
Get the class name of the associated property editor item.
Reimplemented in App::PropertyFile, App::PropertyFileIncluded, Mesh::PropertyMeshKernel, App::PropertyRotation, App::PropertyVectorDistance, App::PropertyPosition, App::PropertyDirection, App::PropertyMatrix, App::PropertyInteger, App::PropertyPath, App::PropertyEnumeration, App::PropertyIntegerConstraint, App::PropertyFloat, App::PropertyFloatConstraint, App::PropertyPrecision, App::PropertyString, App::PropertyFont, App::PropertyBool, App::PropertyColor, App::PropertyMaterial, App::PropertyQuantity, App::PropertyQuantityConstraint, App::PropertyAngle, Fem::PropertyFemMesh, App::PropertyVector, App::PropertyVectorList, App::PropertyPlacement, App::PropertyLink, App::PropertyLinkList, App::PropertyLinkSub, App::PropertyLinkSubList, App::PropertyXLinkSub, App::PropertyXLinkSubList, App::PropertyIntegerList, App::PropertyFloatList, App::PropertyStringList, App::PropertyMaterialList, and Sketcher::PropertyConstraintList.
getFullName()
std::string Property::getFullName () const
References App::PropertyContainer::getFullName().
Referenced by SpreadsheetGui::DlgSheetConf::accept(), StdCmdExpression::copyExpressions(), App::PropertyExpressionEngine::execute(), Gui::ViewProviderDocumentObject::onChanged(), Spreadsheet::PropertySheet::pasteCells(), App::PropertyEnumeration::setEnums(), App::PropertyEnumeration::setEnumVector(), Sketcher::SketchObject::setExpression(), Spreadsheet::PropertySheet::setPathValue(), App::PropertyEnumeration::setPyObject(), Gui::Document::slotChangedObject(), and Gui::Document::slotChangePropertyEditor().
getGroup()
const char * Property::getGroup (void) const
Get the group of this property.
References App::PropertyContainer::getPropertyGroup().
Referenced by App::DynamicProperty::addProperty(), App::LinkBaseExtension::isCopyOnChangeProperty(), Part::Primitive::onChanged(), and App::LinkBaseExtension::setupCopyOnChange().
getID()
int64_t App::Property::getID () const
Return a unique ID for the property.
The ID of a property is generated from a monotonically increasing internal counter. The intention of the ID is to be used as a key for mapping, instead of using the raw pointer. Because, it is possible for the runtime memory allocator to reuse just deleted memory, which will cause hard to debug problem if use pointer as key.
Referenced by App::TransactionObject::addOrRemoveProperty(), and App::TransactionObject::setProperty().
getMemSize()
virtual unsigned int App::Property::getMemSize (void) const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
See also
Base::Persistence
Implements Base::Persistence.
Reimplemented in App::PropertyFileIncluded, Mesh::PropertyNormalList, Mesh::PropertyCurvatureList, Mesh::PropertyMeshKernel, Points::PropertyGreyValueList, Points::PropertyNormalList, Points::PropertyCurvatureList, Points::PropertyPointKernel, App::PropertyRotation, App::PropertyMatrix, App::PropertyPythonObject, App::PropertyInteger, App::PropertyPath, App::PropertyIntegerSet, App::PropertyMap, App::PropertyFloat, App::PropertyString, App::PropertyUUID, App::PropertyBool, App::PropertyColor, App::PropertyMaterial, Fem::PropertyFemMesh, Fem::PropertyPostDataObject, Inspection::PropertyDistanceList, Part::PropertyGeometryList, Part::PropertyPartShape, Part::PropertyShapeHistory, Part::PropertyFilletEdges, Path::PropertyPath, Path::PropertyTool, Path::PropertyTooltable, Robot::PropertyTrajectory, TechDraw::PropertyCenterLineList, TechDraw::PropertyCosmeticEdgeList, TechDraw::PropertyCosmeticVertexList, TechDraw::PropertyGeomFormatList, App::PropertyExpressionEngine, App::PropertyVector, App::PropertyVectorList, App::PropertyPlacement, App::PropertyPlacementList, App::PropertyLink, App::PropertyLinkList, App::PropertyLinkSub, App::PropertyLinkSubList, App::PropertyXLinkSubList, App::PropertyIntegerList, App::PropertyFloatList, App::PropertyStringList, App::PropertyBoolList, App::PropertyColorList, App::PropertyMaterialList, App::PropertyPersistentObject, Sketcher::PropertyConstraintList, and Spreadsheet::PropertySheet.
Referenced by App::PropertyFileIncluded::getMemSize(), and isSame().
getName()
const char * Property::getName (void) const
Get the name of this property in the belonging container With hasName() it can be checked beforehand if a valid name is set.
Note
If no name is set this function returns an empty string, i.e. "".
Referenced by App::DynamicProperty::addProperty(), Gui::PropertyEditor::PropertyModel::appendProperty(), Gui::PropertyEditor::PropertyModel::buildUp(), Sketcher::PropertyConstraintList::canonicalPath(), PartDesignGui::TaskHoleParameters::changedObject(), App::LinkBaseExtension::checkCopyOnChange(), PartDesign::SubShapeBinder::checkCopyOnChange(), PartGui::ViewProviderSplineExtension::extensionUpdateData(), Sketcher::PropertyConstraintList::getConstraint(), getPaths(), Part::PropertyPartShape::getPaths(), Sketcher::PropertyConstraintList::getPyPathValue(), TechDraw::DrawView::handleChangedPropertyType(), Spreadsheet::PropertySheet::isBindingPath(), App::ObjectIdentifier::ObjectIdentifier(), PartGui::ViewProviderCustom::onChanged(), SketcherGui::ViewProviderCustom::onChanged(), PartDesign::Boolean::onChanged(), Gui::PropertyView::onTimer(), App::DocumentObjectT::operator=(), App::PropertyContainer::Restore(), Inspection::PropertyDistanceList::Save(), Mesh::PropertyNormalList::Save(), Mesh::PropertyCurvatureList::Save(), Part::PropertyFilletEdges::Save(), Points::PropertyGreyValueList::Save(), Points::PropertyNormalList::Save(), Points::PropertyCurvatureList::Save(), App::PropertyVectorList::Save(), App::PropertyPlacementList::Save(), App::PropertyFloatList::Save(), App::PropertyColorList::Save(), App::PropertyMaterialList::Save(), Sketcher::PropertyConstraintList::setPathValue(), App::LinkBaseExtension::setProperty(), ShapeCache::slotChanged(), Gui::Document::slotChangedObject(), Spreadsheet::SheetObserver::slotChangedObject(), App::PropertyLinkBase::tryReplaceLink(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), Gui::ViewProviderAnnotation::updateData(), Gui::ViewProviderAnnotationLabel::updateData(), Gui::ViewProviderInventorObject::updateData(), Gui::ViewProviderMeasureDistance::updateData(), Gui::ViewProviderVRMLObject::updateData(), FemGui::ViewProviderFemConstraintBearing::updateData(), FemGui::ViewProviderFemConstraintContact::updateData(), FemGui::ViewProviderFemConstraintDisplacement::updateData(), FemGui::ViewProviderFemConstraintFixed::updateData(), FemGui::ViewProviderFemConstraintFluidBoundary::updateData(), FemGui::ViewProviderFemConstraintForce::updateData(), FemGui::ViewProviderFemConstraintGear::updateData(), FemGui::ViewProviderFemConstraintHeatflux::updateData(), FemGui::ViewProviderFemConstraintPlaneRotation::updateData(), FemGui::ViewProviderFemConstraintPressure::updateData(), FemGui::ViewProviderFemConstraintPulley::updateData(), FemGui::ViewProviderFemConstraintSpring::updateData(), FemGui::ViewProviderFemConstraintTemperature::updateData(), FemGui::ViewProviderFemConstraintTransform::updateData(), FemGui::ViewProviderFemPostFunctionProvider::updateData(), InspectionGui::ViewProviderInspection::updateData(), PartDesignGui::ViewProviderDatumCoordinateSystem::updateData(), PartDesignGui::ViewProviderDatumLine::updateData(), PartDesignGui::ViewProviderDatumPlane::updateData(), Gui::ViewProviderDragger::updateData(), PartGui::ViewProviderPartExt::updateData(), PartDesignGui::ViewProvider::updateData(), FemGui::ViewProviderFemPostPipeline::updateData(), App::PropertyXLink::upgrade(), App::PropertyXLinkSubList::upgrade(), App::PropertyXLinkSub::upgrade(), and App::ObjectIdentifier::verify().
getPaths()
void Property::getPaths (std::vector< App::ObjectIdentifier > & paths) const virtual
Get valid paths for this property; used by auto completer.
Reimplemented in Fem::PropertyPostDataObject, Part::PropertyPartShape, Sketcher::PropertyConstraintList, App::PropertyVector, App::PropertyPlacement, and App::PropertyRotation.
References getContainer(), and getName().
getPathValue()
const boost::any Property::getPathValue (const App::ObjectIdentifier & path) const virtual
Get value of property.
Reimplemented in App::PropertyInteger, App::PropertyEnumeration, App::PropertyFloat, App::PropertyString, App::PropertyBool, App::PropertyQuantity, App::PropertyExpressionEngine, Sketcher::PropertyConstraintList, Spreadsheet::PropertySheet, App::PropertyVector, App::PropertyPlacement, and App::PropertyRotation.
Referenced by App::PropertyExpressionEngine::execute(), App::PropertyVector::getPathValue(), App::PropertyPlacement::getPathValue(), App::PropertyRotation::getPathValue(), App::ObjectIdentifier::getValue(), and App::PropertyExpressionEngine::setValue().
getPyPathValue()
virtual bool App::Property::getPyPathValue (const App::ObjectIdentifier & , Py::Object &) const virtual
Get Python value of property.
Reimplemented in Sketcher::PropertyConstraintList, App::PropertyEnumeration, App::PropertyVector, App::PropertyPlacement, and App::PropertyRotation.
Referenced by App::ObjectIdentifier::getPyValue().
getStatus()
unsigned long App::Property::getStatus () const
return the status bits
Referenced by App::TransactionObject::addOrRemoveProperty(), and App::TransactionObject::setProperty().
getType()
short Property::getType (void) const
Get the type of the property in the container.
References Hidden, NoRecompute, Output, ReadOnly, and Transient.
Referenced by App::DynamicProperty::addProperty(), App::DynamicProperty::getPropertyType(), App::PropertyContainer::getPropertyType(), Gui::PropertyView::isPropertyHidden(), Gui::LinkView::onLinkedUpdateData(), App::LinkBaseExtension::update(), PathScripts.PathToolEdit.ToolEditor::updateToolType(), and PathScripts.PathToolEdit.ToolEditor::updateUI().
hasName()
bool Property::hasName () const
Check if the property has a name set.
If no name is set then getName() will return an empty string
References isValidName().
Referenced by App::DynamicProperty::addProperty(), App::ObjectIdentifier::ObjectIdentifier(), and App::DocumentObjectT::operator=().
hasSetChildValue()
virtual void App::Property::hasSetChildValue (Property &) virtual
Called when a child property has changed value.
Reimplemented in Spreadsheet::PropertySheet, and App::PropertyXLinkSubList.
Referenced by App::PropertyXLink::hasSetValue().
hasSetValue()
void Property::hasSetValue (void) protected virtual
Gets called by all setValue() methods after the value has changed.
Reimplemented in App::PropertyExpressionEngine, App::PropertyLinkBase, App::PropertyXLink, and Spreadsheet::PropertySheet.
References Busy, App::PropertyContainer::onChanged(), signalChanged, StatusBits, testStatus(), and Touched.
Referenced by Sketcher::PropertyConstraintList::acceptGeometry(), Mesh::PropertyMeshKernel::finishEditing(), Points::PropertyPointKernel::finishEditing(), App::PropertyLinkBase::hasSetValue(), Fem::PropertyFemMesh::Paste(), Fem::PropertyPostDataObject::Paste(), Mesh::PropertyNormalList::Paste(), Mesh::PropertyCurvatureList::Paste(), Mesh::PropertyMeshKernel::Paste(), Part::PropertyPartShape::Paste(), Path::PropertyPath::Paste(), Path::PropertyTool::Paste(), Path::PropertyTooltable::Paste(), Points::PropertyGreyValueList::Paste(), Points::PropertyNormalList::Paste(), Points::PropertyCurvatureList::Paste(), Points::PropertyPointKernel::Paste(), Robot::PropertyTrajectory::Paste(), App::PropertyFileIncluded::Paste(), App::PropertyMatrix::Paste(), App::PropertyPythonObject::Paste(), App::PropertyInteger::Paste(), App::PropertyPath::Paste(), App::PropertyIntegerSet::Paste(), App::PropertyMap::Paste(), App::PropertyFloat::Paste(), App::PropertyUUID::Paste(), App::PropertyBool::Paste(), App::PropertyColor::Paste(), App::PropertyMaterial::Paste(), Inspection::PropertyDistanceList::Paste(), Part::PropertyShapeHistory::Paste(), Part::PropertyFilletEdges::Paste(), Spreadsheet::PropertySpreadsheetQuantity::Paste(), App::PropertyVector::Paste(), App::PropertyPlacement::Paste(), App::PropertyRotation::Paste(), App::PropertyPersistentObject::Paste(), App::PropertyFileIncluded::Restore(), App::PropertyMatrix::Restore(), App::PropertyPythonObject::Restore(), App::PropertyEnumeration::Restore(), App::PropertyString::Restore(), App::PropertyMaterial::Restore(), Mesh::PropertyMeshKernel::Restore(), Points::PropertyPointKernel::Restore(), App::PropertyVector::Restore(), App::PropertyPlacement::Restore(), App::PropertyRotation::Restore(), App::PropertyFileIncluded::RestoreDocFile(), App::PropertyPythonObject::RestoreDocFile(), Fem::PropertyFemMesh::RestoreDocFile(), Fem::PropertyPostDataObject::RestoreDocFile(), Mesh::PropertyMeshKernel::RestoreDocFile(), Path::PropertyPath::RestoreDocFile(), Points::PropertyPointKernel::RestoreDocFile(), Fem::PropertyPostDataObject::scale(), Sketcher::PropertyConstraintList::set1Value(), Part::PropertyGeometryList::set1Value(), App::PropertyMaterial::setAmbientColor(), App::PropertyMaterial::setDiffuseColor(), App::PropertyMaterial::setEmissiveColor(), App::PropertyEnumeration::setEnums(), App::PropertyEnumeration::setEnumVector(), Sketcher::PropertyConstraintList::setPathValue(), Mesh::PropertyMeshKernel::setPointIndices(), App::PropertyPythonObject::setPyObject(), App::PropertyInteger::setPyObject(), App::PropertyEnumeration::setPyObject(), App::PropertyIntegerConstraint::setPyObject(), App::PropertyFloat::setPyObject(), App::PropertyFloatConstraint::setPyObject(), App::PropertyQuantity::setPyObject(), App::PropertyMaterial::setShininess(), App::PropertyMaterial::setSpecularColor(), App::PropertyMaterial::setTransparency(), App::PropertyBool::setValue(), TechDraw::PropertyCenterLineList::setValue(), App::PropertyMatrix::setValue(), App::PropertyPlacement::setValue(), App::PropertyRotation::setValue(), App::PropertyUUID::setValue(), App::PropertyVector::setValue(), Mesh::PropertyNormalList::setValue(), Points::PropertyNormalList::setValue(), App::PropertyPath::setValue(), App::PropertyFileIncluded::setValue(), App::PropertyString::setValue(), App::PropertyPersistentObject::setValue(), App::PropertyEnumeration::setValue(), App::PropertyColor::setValue(), Sketcher::PropertyConstraintList::setValue(), Mesh::PropertyCurvatureList::setValue(), Points::PropertyCurvatureList::setValue(), Fem::PropertyFemMesh::setValue(), Part::PropertyGeometryList::setValue(), TechDraw::PropertyGeomFormatList::setValue(), App::PropertyMaterial::setValue(), Mesh::PropertyMeshKernel::setValue(), Points::PropertyPointKernel::setValue(), Part::PropertyShapeHistory::setValue(), App::PropertyMap::setValue(), Path::PropertyTool::setValue(), Path::PropertyPath::setValue(), Path::PropertyTooltable::setValue(), Part::PropertyPartShape::setValue(), Robot::PropertyTrajectory::setValue(), Fem::PropertyPostDataObject::setValue(), TechDraw::PropertyCosmeticEdgeList::setValue(), TechDraw::PropertyCosmeticVertexList::setValue(), App::PropertyFloat::setValue(), Inspection::PropertyDistanceList::setValue(), Points::PropertyGreyValueList::setValue(), Spreadsheet::PropertyColumnWidths::setValue(), Part::PropertyFilletEdges::setValue(), Spreadsheet::PropertyRowHeights::setValue(), App::PropertyInteger::setValue(), App::PropertyIntegerSet::setValue(), App::PropertyPythonObject::setValue(), Fem::PropertyFemMesh::setValuePtr(), Mesh::PropertyMeshKernel::setValuePtr(), Spreadsheet::PropertyColumnWidths::setValues(), Spreadsheet::PropertyRowHeights::setValues(), App::PropertyMap::setValues(), App::PropertyIntegerSet::setValues(), Mesh::PropertyNormalList::setValues(), Points::PropertyNormalList::setValues(), TechDraw::PropertyCenterLineList::setValues(), TechDraw::PropertyCosmeticEdgeList::setValues(), TechDraw::PropertyCosmeticVertexList::setValues(), Mesh::PropertyCurvatureList::setValues(), Points::PropertyCurvatureList::setValues(), Part::PropertyFilletEdges::setValues(), Inspection::PropertyDistanceList::setValues(), Points::PropertyGreyValueList::setValues(), TechDraw::PropertyGeomFormatList::setValues(), Part::PropertyShapeHistory::setValues(), Sketcher::PropertyConstraintList::setValues(), Part::PropertyGeometryList::setValues(), Mesh::PropertyMeshKernel::swapMesh(), Fem::PropertyFemMesh::transformGeometry(), Mesh::PropertyNormalList::transformGeometry(), Mesh::PropertyCurvatureList::transformGeometry(), Mesh::PropertyMeshKernel::transformGeometry(), Part::PropertyPartShape::transformGeometry(), Points::PropertyNormalList::transformGeometry(), Points::PropertyCurvatureList::transformGeometry(), and Points::PropertyPointKernel::transformGeometry().
isReadOnly()
bool App::Property::isReadOnly () const
References ReadOnly.
Referenced by Gui::ExpressionBinding::apply(), PartDesignGui::TaskHoleParameters::apply(), Gui::QuantitySpinBox::apply(), PartDesignGui::TaskHoleParameters::changedObject(), and PartDesignGui::TaskHoleParameters::TaskHoleParameters().
isSame()
bool Property::isSame (const Property & other) const virtual
Compare if this property has the same content as the given one.
Reimplemented in App::PropertyFileIncluded, App::PropertyMatrix, App::PropertyInteger, App::PropertyPath, App::PropertyEnumeration, App::PropertyIntegerSet, App::PropertyMap, App::PropertyFloat, App::PropertyString, App::PropertyUUID, App::PropertyFont, App::PropertyBool, App::PropertyColor, App::PropertyMaterial, App::PropertyQuantity, App::PropertyListsT< T, ListT, ParentT >, App::PropertyListsT< bool, boost::dynamic_bitset<> >, App::PropertyListsT< Color >, App::PropertyListsT< double >, App::PropertyListsT< long >, App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >, App::PropertyListsT< Material >, App::PropertyListsT< Base::Placement >, App::PropertyListsT< std::string >, App::PropertyListsT< Base::Vector3d >, App::PropertyVector, App::PropertyPlacement, and App::PropertyLinkBase.
References getMemSize(), Base::StringWriter::getString(), Base::Persistence::getTypeId(), and Base::Persistence::Save().
isSinglePrecision()
bool App::Property::isSinglePrecision () const
Gets precision of properties using floating point numbers.
References Single.
Referenced by App::PropertyVectorList::RestoreDocFile(), App::PropertyPlacementList::RestoreDocFile(), App::PropertyFloatList::RestoreDocFile(), App::PropertyVectorList::SaveDocFile(), App::PropertyPlacementList::SaveDocFile(), and App::PropertyFloatList::SaveDocFile().
isTouched()
bool App::Property::isTouched (void) const
Test if this property is touched.
Referenced by Part::PrismExtension::extensionMustExecute(), App::RangeExpression::isTouched(), Inspection::Feature::mustExecute(), Mesh::Curvature::mustExecute(), Mesh::FixDefects::mustExecute(), Mesh::Export::mustExecute(), Mesh::Import::mustExecute(), Mesh::SegmentByMesh::mustExecute(), Mesh::SetOperations::mustExecute(), Mesh::Sphere::mustExecute(), Mesh::Ellipsoid::mustExecute(), Mesh::Cylinder::mustExecute(), Mesh::Cone::mustExecute(), Mesh::Torus::mustExecute(), Mesh::Cube::mustExecute(), Part::Compound::mustExecute(), Part::Mirroring::mustExecute(), Part::Boolean::mustExecute(), Part::Box::mustExecute(), Part::Circle::mustExecute(), Part::MultiCommon::mustExecute(), Part::CurveNet::mustExecute(), Part::MultiFuse::mustExecute(), Part::ImportBrep::mustExecute(), Part::ImportIges::mustExecute(), Part::ImportStep::mustExecute(), Part::Section::mustExecute(), Part::FilletBase::mustExecute(), Part::RuledSurface::mustExecute(), Part::Loft::mustExecute(), Part::Sweep::mustExecute(), Part::Thickness::mustExecute(), Part::Vertex::mustExecute(), Part::Line::mustExecute(), Part::Plane::mustExecute(), Part::Sphere::mustExecute(), Part::Ellipsoid::mustExecute(), Part::Cylinder::mustExecute(), Part::Prism::mustExecute(), Part::RegularPolygon::mustExecute(), Part::Cone::mustExecute(), Part::Torus::mustExecute(), Part::Helix::mustExecute(), Part::Spiral::mustExecute(), Part::Wedge::mustExecute(), Part::Ellipse::mustExecute(), PartDesign::FeatureExtrude::mustExecute(), PartDesign::Fillet::mustExecute(), PartDesign::Groove::mustExecute(), PartDesign::Helix::mustExecute(), PartDesign::Hole::mustExecute(), PartDesign::LinearPattern::mustExecute(), PartDesign::Loft::mustExecute(), PartDesign::Mirrored::mustExecute(), PartDesign::MultiTransform::mustExecute(), PartDesign::Pipe::mustExecute(), PartDesign::PolarPattern::mustExecute(), PartDesign::Box::mustExecute(), PartDesign::Cylinder::mustExecute(), PartDesign::Sphere::mustExecute(), PartDesign::Cone::mustExecute(), PartDesign::Ellipsoid::mustExecute(), PartDesign::Torus::mustExecute(), PartDesign::Prism::mustExecute(), PartDesign::Wedge::mustExecute(), PartDesign::Revolution::mustExecute(), PartDesign::Scaled::mustExecute(), PartDesign::ProfileBased::mustExecute(), PartDesign::Thickness::mustExecute(), PartDesign::Transformed::mustExecute(), Raytracing::LuxFeature::mustExecute(), Raytracing::LuxProject::mustExecute(), Raytracing::RayFeature::mustExecute(), Raytracing::RayProject::mustExecute(), Sketcher::SketchObjectSF::mustExecute(), Surface::Cut::mustExecute(), Surface::Filling::mustExecute(), Surface::GeomFillSurface::mustExecute(), Surface::Sewing::mustExecute(), TechDraw::DrawRichAnno::mustExecute(), TechDraw::DrawViewClip::mustExecute(), TechDraw::DrawViewCollection::mustExecute(), TechDraw::DrawViewSpreadsheet::mustExecute(), Part::Extrusion::mustExecute(), Part::Face::mustExecute(), Part::Offset::mustExecute(), Part::Offset2D::mustExecute(), Part::Revolution::mustExecute(), PartDesign::Body::mustExecute(), PartDesign::FeatureAddSub::mustExecute(), PartDesign::Boolean::mustExecute(), PartDesign::Chamfer::mustExecute(), Sketcher::SketchObject::mustExecute(), Surface::Extend::mustExecute(), TechDraw::DrawGeomHatch::mustExecute(), TechDraw::DrawHatch::mustExecute(), TechDraw::DrawLeaderLine::mustExecute(), TechDraw::DrawPage::mustExecute(), TechDraw::DrawProjGroup::mustExecute(), TechDraw::DrawProjGroupItem::mustExecute(), TechDraw::DrawView::mustExecute(), TechDraw::DrawViewArch::mustExecute(), TechDraw::DrawViewBalloon::mustExecute(), TechDraw::DrawViewDetail::mustExecute(), TechDraw::DrawViewDimension::mustExecute(), TechDraw::DrawViewDraft::mustExecute(), TechDraw::DrawViewImage::mustExecute(), TechDraw::DrawViewMulti::mustExecute(), TechDraw::DrawViewPart::mustExecute(), TechDraw::DrawViewSection::mustExecute(), TechDraw::DrawViewSymbol::mustExecute(), App::Origin::mustExecute(), Fem::FemPostClipFilter::mustExecute(), Fem::FemPostDataAlongLineFilter::mustExecute(), Fem::FemPostDataAtPointFilter::mustExecute(), Fem::FemPostScalarClipFilter::mustExecute(), Fem::FemPostWarpVectorFilter::mustExecute(), Fem::FemPostCutFilter::mustExecute(), Fem::FemPostPipeline::mustExecute(), PartDesign::FeatureBase::mustExecute(), Sandbox::SandboxObject::mustExecute(), PartDesign::ShapeBinder::mustExecute(), and TechDrawGui::MDIViewPage::updateTemplate().
isValidName()
bool Property::isValidName (const char * name) static
Check if the passed name is valid.
If name is null or an empty string it's considered invalid, and valid otherwise.
Referenced by hasName(), App::LinkBaseExtension::setProperty(), and ShapeCache::slotChanged().
onContainerRestored()
virtual void App::Property::onContainerRestored () virtual
Called before calling DocumentObject::onDocumentRestored()
This function is called after finished calling Property::afterRestore() of all properties of objects. By then, the object dependency information is assumed ready. So, unlike Property::afterRestore(), this function is called on objects with dependency order.
Reimplemented in App::PropertyExpressionEngine, App::PropertyLinkSub, App::PropertyLinkSubList, App::PropertyXLink, App::PropertyXLinkSubList, and Spreadsheet::PropertySheet.
Paste()
void Property::Paste (const Property & from) pure virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implemented in Fem::PropertyFemMesh, Fem::PropertyPostDataObject, Mesh::PropertyNormalList, Mesh::PropertyCurvatureList, Mesh::PropertyMeshKernel, Part::PropertyGeometryList, Part::PropertyPartShape, Path::PropertyPath, Path::PropertyTool, Path::PropertyTooltable, Points::PropertyGreyValueList, Points::PropertyNormalList, Points::PropertyCurvatureList, Points::PropertyPointKernel, Robot::PropertyTrajectory, Spreadsheet::PropertyRowHeights, TechDraw::PropertyCenterLineList, TechDraw::PropertyCosmeticEdgeList, TechDraw::PropertyCosmeticVertexList, TechDraw::PropertyGeomFormatList, Sketcher::PropertyConstraintList, App::PropertyFileIncluded, App::PropertyMatrix, App::PropertyPlacementLink, App::PropertyPythonObject, App::PropertyInteger, App::PropertyPath, App::PropertyEnumeration, App::PropertyIntegerSet, App::PropertyMap, App::PropertyFloat, App::PropertyString, App::PropertyUUID, App::PropertyBool, App::PropertyColor, App::PropertyMaterial, App::PropertyExpressionEngine, App::PropertyVector, App::PropertyVectorList, App::PropertyPlacement, App::PropertyPlacementList, App::PropertyRotation, App::PropertyLink, App::PropertyLinkList, App::PropertyLinkSub, App::PropertyLinkSubList, App::PropertyXLink, App::PropertyXLinkSubList, App::PropertyIntegerList, App::PropertyFloatList, App::PropertyStringList, App::PropertyBoolList, App::PropertyColorList, App::PropertyMaterialList, and App::PropertyPersistentObject.
Referenced by PartDesignGui::TaskFeaturePick::makeCopy(), and PartDesignGui::ViewProviderBody::unifyVisualProperty().
purgeTouched()
void App::Property::purgeTouched (void)
Reset this property touched.
Referenced by TechDraw::DrawProjGroup::addProjection(), TechDraw::DrawView::checkScale(), TechDraw::DrawProjGroup::execute(), TechDraw::DrawProjGroupItem::execute(), TechDraw::DrawViewDetail::execute(), TechDraw::DrawViewPart::execute(), TechDraw::DrawViewSection::execute(), TechDraw::DrawView::handleXYLock(), TechDraw::DrawViewBalloon::handleXYLock(), TechDraw::DrawView::onChanged(), TechDraw::DrawViewDetail::onChanged(), Gui::Application::reopen(), PathGui::ViewProviderPath::updateShowConstraints(), PathGui::ViewProviderPath::updateVisual(), and TechDraw::DrawView::validateScale().
setContainer()
void Property::setContainer (PropertyContainer * Father)
Is called by the framework to set the father (container)
Referenced by App::DynamicProperty::addDynamicProperty(), Part::Chamfer::execute(), Part::Compound::execute(), Part::Fillet::execute(), Part::Part2DObject::handleChangedPropertyType(), TechDraw::DrawPage::handleChangedPropertyType(), TechDraw::DrawView::handleChangedPropertyType(), PartGui::ViewProviderPartExt::onChanged(), App::PropertyLinkSubList::upgrade(), App::PropertyXLinkSubList::upgrade(), App::PropertyXLinkSub::upgrade(), and Gui::ViewProviderDocumentObject::~ViewProviderDocumentObject().
setPathValue()
void Property::setPathValue (const App::ObjectIdentifier & path, const boost::any & value) virtual
Set value of property.
Reimplemented in App::PropertyInteger, App::PropertyEnumeration, App::PropertyFloat, App::PropertyString, App::PropertyBool, App::PropertyQuantity, Sketcher::PropertyConstraintList, Spreadsheet::PropertySheet, App::PropertyPlacement, and App::PropertyRotation.
Referenced by App::PropertyExpressionEngine::execute(), App::PropertyPlacement::setPathValue(), and App::PropertyRotation::setPathValue().
setReadOnly()
void Property::setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
References ReadOnly, and setStatus().
Referenced by PartDesign::FeatureExtrude::computeDirection(), PartDesign::Pad::execute(), Part::AttachExtension::extensionOnChanged(), PartDesign::Hole::Hole(), PartDesign::Line::onChanged(), PartDesign::Plane::onChanged(), PartDesign::Hole::onChanged(), Part::Revolution::onChanged(), TechDraw::DrawViewDimension::onChanged(), and Part::AttachExtension::onExtendedDocumentRestored().
setSinglePrecision()
void App::Property::setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
References Single.
setStatus()
void Property::setStatus (Status pos, bool on)
References setStatusValue(), and StatusBits.
Referenced by SpreadsheetGui::DlgSheetConf::accept(), MeshGui::ViewProviderMesh::attach(), TechDraw::DrawViewAnnotation::DrawViewAnnotation(), TechDraw::DrawViewBalloon::DrawViewBalloon(), TechDraw::DrawViewDimension::DrawViewDimension(), TechDraw::DrawViewDimExtent::DrawViewDimExtent(), Part::AttachExtension::extensionOnChanged(), Part::Circle::handleChangedPropertyName(), Part::Ellipse::handleChangedPropertyName(), TechDraw::DrawView::handleXYLock(), TechDraw::DrawViewBalloon::handleXYLock(), Part::Box::onChanged(), PartDesign::ProfileBased::onChanged(), TechDraw::DrawView::onChanged(), TechDraw::DrawViewDetail::onChanged(), PartDesign::FeatureBase::onDocumentRestored(), Part::AttachExtension::onExtendedDocumentRestored(), Part::Box::Restore(), Gui::ViewProviderLink::setElementColors(), App::LinkBaseExtension::setProperty(), setReadOnly(), TechDraw::DrawView::setScaleAttribute(), MeshGui::ViewProviderMesh::updateData(), TechDrawGui::ViewProviderRichAnno::updateData(), Gui::ViewProviderLink::updateDataPrivate(), PartDesign::Chamfer::updateProperties(), PartDesignGui::ViewProviderDatum::ViewProviderDatum(), Gui::ViewProviderLink::ViewProviderLink(), and Gui::ViewProviderTextDocument::ViewProviderTextDocument().
setStatusValue()
void Property::setStatusValue (unsigned long status)
References Busy, Hidden, App::PropertyContainer::onPropertyStatusChanged(), PropDynamic, PropHidden, PropNoPersist, PropNoRecompute, PropOutput, PropReadOnly, PropTransient, ReadOnly, and StatusBits.
Referenced by App::TransactionObject::applyChn(), App::PropertyContainer::Restore(), Part::Box::Restore(), and setStatus().
testStatus()
bool App::Property::testStatus (Status pos) const
Referenced by Gui::PropertyEditor::PropertyModel::appendProperty(), PartDesignGui::ViewProviderBody::canDropObjects(), App::GeoFeatureGroupExtension::extensionOnChanged(), App::GroupExtension::extensionOnChanged(), App::LinkBaseExtension::extensionOnChanged(), App::PropertyMaterial::getEditorName(), App::PropertyMaterialList::getEditorName(), TechDraw::DrawView::handleXYLock(), TechDraw::DrawViewBalloon::handleXYLock(), hasSetValue(), App::LinkBaseExtension::isCopyOnChangeProperty(), Gui::PropertyView::isPropertyHidden(), Part::Box::onChanged(), Gui::ViewProviderDocumentObject::onChanged(), PartDesign::SubShapeBinder::onChanged(), Gui::LinkView::onLinkedUpdateData(), Gui::PropertyView::onTimer(), Gui::ViewProviderDocumentObject::removeDynamicProperty(), Part::Circle::Restore(), Part::Ellipse::Restore(), Gui::Document::slotChangedObject(), App::LinkBaseExtension::update(), and Gui::ViewProviderLink::updateDataPrivate().
touch()
void Property::touch ()
Property status handling.
Set the property touched
References App::PropertyContainer::onChanged(), StatusBits, and Touched.
Referenced by Sketcher::SketchObject::addCopy(), Sketcher::SketchObject::addSymmetric(), Spreadsheet::PropertySheet::afterRestore(), Gui::ViewProviderPythonFeatureImp::attach(), Sketcher::SketchObject::carbonCopy(), Sketcher::PropertyConstraintList::checkGeometry(), Sketcher::SketchObject::convertToNURBS(), Sketcher::SketchObject::deleteAllGeometry(), Sketcher::SketchObject::delGeometriesExclusiveList(), Sketcher::SketchObject::delGeometry(), App::Document::Document(), Gui::ViewProviderTextDocument::doubleClicked(), Fem::Constraint::execute(), Part::Feature::execute(), Part::Chamfer::execute(), Part::Compound::execute(), Part::Fillet::execute(), TechDraw::DrawTemplate::execute(), Sketcher::SketchObject::insertBSplineKnot(), Spreadsheet::PropertySheet::invalidateDependants(), Sketcher::SketchObject::modifyBSplineKnotMultiplicity(), Fem::ConstraintBearing::onChanged(), Fem::ConstraintGear::onChanged(), Fem::ConstraintPulley::onChanged(), Fem::ConstraintTransform::onChanged(), TechDraw::DrawViewDimension::onChanged(), Fem::Constraint::onDocumentRestored(), Fem::FemPostPlaneFunction::onDocumentRestored(), Part::Datum::onDocumentRestored(), PartDesign::Body::onDocumentRestored(), App::VRMLObject::RestoreDocFile(), App::Document::saveAs(), Gui::AlignmentGroup::setAlignable(), Sketcher::SketchObject::setUpSketch(), Sketcher::SketchObject::solve(), PartGui::ViewProviderPartExt::unsetHighlightedEdges(), PartGui::ViewProviderPartExt::unsetHighlightedFaces(), PartGui::ViewProviderPartExt::unsetHighlightedPoints(), PathGui::ViewProviderPath::updateVisual(), and PartGui::ViewProviderPartExt::ViewProviderPartExt().
verifyPath()
void Property::verifyPath (const App::ObjectIdentifier & p) const protected virtual
Verify a path for the current property.
Referenced by App::PropertyFloat::getPathValue(), App::PropertyString::getPathValue(), App::PropertyBool::getPathValue(), App::PropertyInteger::setPathValue(), App::PropertyFloat::setPathValue(), App::PropertyString::setPathValue(), and App::PropertyBool::setPathValue().
Friends And Related Function Documentation
DynamicProperty
friend class DynamicProperty friend
PropertyContainer
friend class PropertyContainer friend
PropertyData
friend struct PropertyData friend
Member Data Documentation
signalChanged
boost::signals2::signal<void (const App::Property&)> App::Property::signalChanged
Referenced by hasSetValue().
StatusBits
std::bitset<32> App::Property::StatusBits protected
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
The bits and their meaning are listed below: 0 - object is marked as 'touched' 1 - object is marked as 'immutable' 2 - object is marked as 'read-only' (for property editor) 3 - object is marked as 'hidden' (for property editor)
Referenced by App::PropertyFileIncluded::aboutToSetValue(), App::DynamicProperty::addDynamicProperty(), App::PropertyFileIncluded::Copy(), hasSetValue(), App::PropertyContainer::Restore(), setStatus(), setStatusValue(), and touch().
The documentation for this class was generated from the following files:
FreeCAD/src/App/Property.h
FreeCAD/src/App/Property.cpp