FreeCAD: U32 Struct Reference
U32 Struct Reference
#include <U32.h>
Public Member Functions
operator uint32_t () const
void read (Context &cont)
U32 ()
U32 (Context &cont)
U32 (uint32_t ui)
Constructor & Destructor Documentation
U32() [1/3]
U32::U32 ()
U32() [2/3]
U32::U32 (uint32_t ui)
U32() [3/3]
U32::U32 (Context & cont)
References read().
Member Function Documentation
operator uint32_t()
U32::operator uint32_t () const
read()
void U32::read (Context & cont)
References Context::Strm.
Referenced by TOC_Entry::read(), gzip_utf8.GzipFile::readline(), gzip_utf8.GzipFile::seek(), and U32().
The documentation for this struct was generated from the following file:
FreeCAD/src/Mod/JtReader/App/JrJt/U32.h