FreeCAD: Part::TopoShapePy Class Reference
Part::TopoShapePy Class Reference
The python export class for TopoShape.
#include <TopoShapePy.h>
Public Types
typedef TopoShape * PointerType
Public Types inherited from Data::ComplexGeoDataPy
typedef ComplexGeoData * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
TopoShapePy (TopoShape *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Data::ComplexGeoDataPy
ComplexGeoDataPy (ComplexGeoData *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getFacesFromSubelement (PyObject *args)
implementer for the getFacesFromSubelement() method
Py::Object getBoundBox (void) const
getter for the BoundBox attribute
Py::Object getPlacement (void) const
getter for the Placement attribute
void setPlacement (Py::Object arg)
setter for the Placement attribute
Py::Object getMatrix (void) const
getter for the Matrix attribute
void setMatrix (Py::Object arg)
setter for the Matrix attribute
Py::Int getTag (void) const
getter for the Tag attribute
void setTag (Py::Int arg)
setter for the Tag attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ComplexGeoData * getComplexGeoDataPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Data::ComplexGeoDataPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_getFacesFromSubelement (PyObject *self, PyObject *args)
callback for the getFacesFromSubelement() method
static PyObject * staticCallback_getBoundBox (PyObject *self, void *closure)
getter callback for the BoundBox attribute
static int staticCallback_setBoundBox (PyObject *self, PyObject *value, void *closure)
setter callback for the BoundBox attribute
static PyObject * staticCallback_getPlacement (PyObject *self, void *closure)
getter callback for the Placement attribute
static int staticCallback_setPlacement (PyObject *self, PyObject *value, void *closure)
setter callback for the Placement attribute
static PyObject * staticCallback_getMatrix (PyObject *self, void *closure)
getter callback for the Matrix attribute
static int staticCallback_setMatrix (PyObject *self, PyObject *value, void *closure)
setter callback for the Matrix attribute
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of TopoShapePy.
static PyMethodDef Methods []
Methods structure of TopoShapePy.
static PyTypeObject Type
Type structure of TopoShapePy.
Static Public Attributes inherited from Data::ComplexGeoDataPy
static PyGetSetDef GetterSetter []
Attribute structure of ComplexGeoDataPy.
static PyMethodDef Methods []
Methods structure of ComplexGeoDataPy.
static PyTypeObject Type
Type structure of ComplexGeoDataPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~TopoShapePy ()
Protected Member Functions inherited from Data::ComplexGeoDataPy
~ComplexGeoDataPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * read (PyObject *args)
implementer for the read() method
PyObject * writeInventor (PyObject *args, PyObject *kwd)
implementer for the writeInventor() method
PyObject * exportIges (PyObject *args)
implementer for the exportIges() method
PyObject * exportStep (PyObject *args)
implementer for the exportStep() method
PyObject * exportBrep (PyObject *args)
implementer for the exportBrep() method
PyObject * exportBinary (PyObject *args)
implementer for the exportBinary() method
PyObject * exportBrepToString (PyObject *args)
implementer for the exportBrepToString() method
PyObject * dumpToString (PyObject *args)
implementer for the dumpToString() method
PyObject * exportStl (PyObject *args)
implementer for the exportStl() method
PyObject * importBrep (PyObject *args)
implementer for the importBrep() method
PyObject * importBinary (PyObject *args)
implementer for the importBinary() method
PyObject * importBrepFromString (PyObject *args)
implementer for the importBrepFromString() method
PyObject * extrude (PyObject *args)
implementer for the extrude() method
PyObject * revolve (PyObject *args)
implementer for the revolve() method
PyObject * check (PyObject *args)
implementer for the check() method
PyObject * fuse (PyObject *args)
implementer for the fuse() method
PyObject * multiFuse (PyObject *args)
implementer for the multiFuse() method
PyObject * oldFuse (PyObject *args)
implementer for the oldFuse() method
PyObject * common (PyObject *args)
implementer for the common() method
PyObject * section (PyObject *args)
implementer for the section() method
PyObject * slices (PyObject *args)
implementer for the slices() method
PyObject * slice (PyObject *args)
implementer for the slice() method
PyObject * cut (PyObject *args)
implementer for the cut() method
PyObject * generalFuse (PyObject *args)
implementer for the generalFuse() method
PyObject * sewShape (PyObject *args)
implementer for the sewShape() method
PyObject * childShapes (PyObject *args)
implementer for the childShapes() method
PyObject * ancestorsOfType (PyObject *args)
implementer for the ancestorsOfType() method
PyObject * removeInternalWires (PyObject *args)
implementer for the removeInternalWires() method
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * transformGeometry (PyObject *args)
implementer for the transformGeometry() method
PyObject * transformShape (PyObject *args)
implementer for the transformShape() method
PyObject * transformed (PyObject *args, PyObject *kwd)
implementer for the transformed() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * translated (PyObject *args)
implementer for the translated() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * rotated (PyObject *args)
implementer for the rotated() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * scaled (PyObject *args)
implementer for the scaled() method
PyObject * makeFillet (PyObject *args)
implementer for the makeFillet() method
PyObject * makeChamfer (PyObject *args)
implementer for the makeChamfer() method
PyObject * makeThickness (PyObject *args)
implementer for the makeThickness() method
PyObject * makeOffsetShape (PyObject *args, PyObject *kwd)
implementer for the makeOffsetShape() method
PyObject * makeOffset2D (PyObject *args, PyObject *kwd)
implementer for the makeOffset2D() method
PyObject * makeWires (PyObject *args)
implementer for the makeWires() method
PyObject * reverse (PyObject *args)
implementer for the reverse() method
PyObject * reversed (PyObject *args)
implementer for the reversed() method
PyObject * complement (PyObject *args)
implementer for the complement() method
PyObject * nullify (PyObject *args)
implementer for the nullify() method
PyObject * isClosed (PyObject *args)
implementer for the isClosed() method
PyObject * isPartner (PyObject *args)
implementer for the isPartner() method
PyObject * isSame (PyObject *args)
implementer for the isSame() method
PyObject * isEqual (PyObject *args)
implementer for the isEqual() method
PyObject * isNull (PyObject *args)
implementer for the isNull() method
PyObject * isValid (PyObject *args)
implementer for the isValid() method
PyObject * isCoplanar (PyObject *args)
implementer for the isCoplanar() method
PyObject * isInfinite (PyObject *args)
implementer for the isInfinite() method
PyObject * findPlane (PyObject *args)
implementer for the findPlane() method
PyObject * fix (PyObject *args)
implementer for the fix() method
PyObject * hashCode (PyObject *args)
implementer for the hashCode() method
PyObject * tessellate (PyObject *args)
implementer for the tessellate() method
PyObject * project (PyObject *args)
implementer for the project() method
PyObject * makeParallelProjection (PyObject *args)
implementer for the makeParallelProjection() method
PyObject * makePerspectiveProjection (PyObject *args)
implementer for the makePerspectiveProjection() method
PyObject * reflectLines (PyObject *args, PyObject *kwd)
implementer for the reflectLines() method
PyObject * makeShapeFromMesh (PyObject *args)
implementer for the makeShapeFromMesh() method
PyObject * toNurbs (PyObject *args)
implementer for the toNurbs() method
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * cleaned (PyObject *args)
implementer for the cleaned() method
PyObject * replaceShape (PyObject *args)
implementer for the replaceShape() method
PyObject * removeShape (PyObject *args)
implementer for the removeShape() method
PyObject * defeaturing (PyObject *args)
implementer for the defeaturing() method
PyObject * isInside (PyObject *args)
implementer for the isInside() method
PyObject * removeSplitter (PyObject *args)
implementer for the removeSplitter() method
PyObject * proximity (PyObject *args)
implementer for the proximity() method
PyObject * distToShape (PyObject *args)
implementer for the distToShape() method
PyObject * getElement (PyObject *args)
implementer for the getElement() method
PyObject * countElement (PyObject *args)
implementer for the countElement() method
PyObject * getTolerance (PyObject *args)
implementer for the getTolerance() method
PyObject * overTolerance (PyObject *args)
implementer for the overTolerance() method
PyObject * inTolerance (PyObject *args)
implementer for the inTolerance() method
PyObject * globalTolerance (PyObject *args)
implementer for the globalTolerance() method
PyObject * fixTolerance (PyObject *args)
implementer for the fixTolerance() method
PyObject * limitTolerance (PyObject *args)
implementer for the limitTolerance() method
PyObject * optimalBoundingBox (PyObject *args)
implementer for the optimalBoundingBox() method
static PyObject * staticCallback___getstate__ (PyObject *self, PyObject *args)
callback for the getstate() method
static PyObject * staticCallback___setstate__ (PyObject *self, PyObject *args)
callback for the setstate() method
static PyObject * staticCallback_read (PyObject *self, PyObject *args)
callback for the read() method
static PyObject * staticCallback_writeInventor (PyObject *self, PyObject *args, PyObject *kwd)
callback for the writeInventor() method
static PyObject * staticCallback_exportIges (PyObject *self, PyObject *args)
callback for the exportIges() method
static PyObject * staticCallback_exportStep (PyObject *self, PyObject *args)
callback for the exportStep() method
static PyObject * staticCallback_exportBrep (PyObject *self, PyObject *args)
callback for the exportBrep() method
static PyObject * staticCallback_exportBinary (PyObject *self, PyObject *args)
callback for the exportBinary() method
static PyObject * staticCallback_exportBrepToString (PyObject *self, PyObject *args)
callback for the exportBrepToString() method
static PyObject * staticCallback_dumpToString (PyObject *self, PyObject *args)
callback for the dumpToString() method
static PyObject * staticCallback_exportStl (PyObject *self, PyObject *args)
callback for the exportStl() method
static PyObject * staticCallback_importBrep (PyObject *self, PyObject *args)
callback for the importBrep() method
static PyObject * staticCallback_importBinary (PyObject *self, PyObject *args)
callback for the importBinary() method
static PyObject * staticCallback_importBrepFromString (PyObject *self, PyObject *args)
callback for the importBrepFromString() method
static PyObject * staticCallback_extrude (PyObject *self, PyObject *args)
callback for the extrude() method
static PyObject * staticCallback_revolve (PyObject *self, PyObject *args)
callback for the revolve() method
static PyObject * staticCallback_check (PyObject *self, PyObject *args)
callback for the check() method
static PyObject * staticCallback_fuse (PyObject *self, PyObject *args)
callback for the fuse() method
static PyObject * staticCallback_multiFuse (PyObject *self, PyObject *args)
callback for the multiFuse() method
static PyObject * staticCallback_oldFuse (PyObject *self, PyObject *args)
callback for the oldFuse() method
static PyObject * staticCallback_common (PyObject *self, PyObject *args)
callback for the common() method
static PyObject * staticCallback_section (PyObject *self, PyObject *args)
callback for the section() method
static PyObject * staticCallback_slices (PyObject *self, PyObject *args)
callback for the slices() method
static PyObject * staticCallback_slice (PyObject *self, PyObject *args)
callback for the slice() method
static PyObject * staticCallback_cut (PyObject *self, PyObject *args)
callback for the cut() method
static PyObject * staticCallback_generalFuse (PyObject *self, PyObject *args)
callback for the generalFuse() method
static PyObject * staticCallback_sewShape (PyObject *self, PyObject *args)
callback for the sewShape() method
static PyObject * staticCallback_childShapes (PyObject *self, PyObject *args)
callback for the childShapes() method
static PyObject * staticCallback_ancestorsOfType (PyObject *self, PyObject *args)
callback for the ancestorsOfType() method
static PyObject * staticCallback_removeInternalWires (PyObject *self, PyObject *args)
callback for the removeInternalWires() method
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_transformGeometry (PyObject *self, PyObject *args)
callback for the transformGeometry() method
static PyObject * staticCallback_transformShape (PyObject *self, PyObject *args)
callback for the transformShape() method
static PyObject * staticCallback_transformed (PyObject *self, PyObject *args, PyObject *kwd)
callback for the transformed() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_translated (PyObject *self, PyObject *args)
callback for the translated() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_rotated (PyObject *self, PyObject *args)
callback for the rotated() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_scaled (PyObject *self, PyObject *args)
callback for the scaled() method
static PyObject * staticCallback_makeFillet (PyObject *self, PyObject *args)
callback for the makeFillet() method
static PyObject * staticCallback_makeChamfer (PyObject *self, PyObject *args)
callback for the makeChamfer() method
static PyObject * staticCallback_makeThickness (PyObject *self, PyObject *args)
callback for the makeThickness() method
static PyObject * staticCallback_makeOffsetShape (PyObject *self, PyObject *args, PyObject *kwd)
callback for the makeOffsetShape() method
static PyObject * staticCallback_makeOffset2D (PyObject *self, PyObject *args, PyObject *kwd)
callback for the makeOffset2D() method
static PyObject * staticCallback_makeWires (PyObject *self, PyObject *args)
callback for the makeWires() method
static PyObject * staticCallback_reverse (PyObject *self, PyObject *args)
callback for the reverse() method
static PyObject * staticCallback_reversed (PyObject *self, PyObject *args)
callback for the reversed() method
static PyObject * staticCallback_complement (PyObject *self, PyObject *args)
callback for the complement() method
static PyObject * staticCallback_nullify (PyObject *self, PyObject *args)
callback for the nullify() method
static PyObject * staticCallback_isClosed (PyObject *self, PyObject *args)
callback for the isClosed() method
static PyObject * staticCallback_isPartner (PyObject *self, PyObject *args)
callback for the isPartner() method
static PyObject * staticCallback_isSame (PyObject *self, PyObject *args)
callback for the isSame() method
static PyObject * staticCallback_isEqual (PyObject *self, PyObject *args)
callback for the isEqual() method
static PyObject * staticCallback_isNull (PyObject *self, PyObject *args)
callback for the isNull() method
static PyObject * staticCallback_isValid (PyObject *self, PyObject *args)
callback for the isValid() method
static PyObject * staticCallback_isCoplanar (PyObject *self, PyObject *args)
callback for the isCoplanar() method
static PyObject * staticCallback_isInfinite (PyObject *self, PyObject *args)
callback for the isInfinite() method
static PyObject * staticCallback_findPlane (PyObject *self, PyObject *args)
callback for the findPlane() method
static PyObject * staticCallback_fix (PyObject *self, PyObject *args)
callback for the fix() method
static PyObject * staticCallback_hashCode (PyObject *self, PyObject *args)
callback for the hashCode() method
static PyObject * staticCallback_tessellate (PyObject *self, PyObject *args)
callback for the tessellate() method
static PyObject * staticCallback_project (PyObject *self, PyObject *args)
callback for the project() method
static PyObject * staticCallback_makeParallelProjection (PyObject *self, PyObject *args)
callback for the makeParallelProjection() method
static PyObject * staticCallback_makePerspectiveProjection (PyObject *self, PyObject *args)
callback for the makePerspectiveProjection() method
static PyObject * staticCallback_reflectLines (PyObject *self, PyObject *args, PyObject *kwd)
callback for the reflectLines() method
static PyObject * staticCallback_makeShapeFromMesh (PyObject *self, PyObject *args)
callback for the makeShapeFromMesh() method
static PyObject * staticCallback_toNurbs (PyObject *self, PyObject *args)
callback for the toNurbs() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_cleaned (PyObject *self, PyObject *args)
callback for the cleaned() method
static PyObject * staticCallback_replaceShape (PyObject *self, PyObject *args)
callback for the replaceShape() method
static PyObject * staticCallback_removeShape (PyObject *self, PyObject *args)
callback for the removeShape() method
static PyObject * staticCallback_defeaturing (PyObject *self, PyObject *args)
callback for the defeaturing() method
static PyObject * staticCallback_isInside (PyObject *self, PyObject *args)
callback for the isInside() method
static PyObject * staticCallback_removeSplitter (PyObject *self, PyObject *args)
callback for the removeSplitter() method
static PyObject * staticCallback_proximity (PyObject *self, PyObject *args)
callback for the proximity() method
static PyObject * staticCallback_distToShape (PyObject *self, PyObject *args)
callback for the distToShape() method
static PyObject * staticCallback_getElement (PyObject *self, PyObject *args)
callback for the getElement() method
static PyObject * staticCallback_countElement (PyObject *self, PyObject *args)
callback for the countElement() method
static PyObject * staticCallback_getTolerance (PyObject *self, PyObject *args)
callback for the getTolerance() method
static PyObject * staticCallback_overTolerance (PyObject *self, PyObject *args)
callback for the overTolerance() method
static PyObject * staticCallback_inTolerance (PyObject *self, PyObject *args)
callback for the inTolerance() method
static PyObject * staticCallback_globalTolerance (PyObject *self, PyObject *args)
callback for the globalTolerance() method
static PyObject * staticCallback_fixTolerance (PyObject *self, PyObject *args)
callback for the fixTolerance() method
static PyObject * staticCallback_limitTolerance (PyObject *self, PyObject *args)
callback for the limitTolerance() method
static PyObject * staticCallback_optimalBoundingBox (PyObject *self, PyObject *args)
callback for the optimalBoundingBox() method
callbacks and implementers for the python object attributes
Py::String getShapeType (void) const
getter for the ShapeType attribute
Py::String getOrientation (void) const
getter for the Orientation attribute
void setOrientation (Py::String arg)
setter for the Orientation attribute
Py::List getFaces (void) const
getter for the Faces attribute
Py::List getVertexes (void) const
getter for the Vertexes attribute
Py::List getShells (void) const
getter for the Shells attribute
Py::List getSolids (void) const
getter for the Solids attribute
Py::List getCompSolids (void) const
getter for the CompSolids attribute
Py::List getEdges (void) const
getter for the Edges attribute
Py::List getWires (void) const
getter for the Wires attribute
Py::List getCompounds (void) const
getter for the Compounds attribute
Py::List getSubShapes (void) const
getter for the SubShapes attribute
Py::Float getLength (void) const
getter for the Length attribute
Py::Float getArea (void) const
getter for the Area attribute
Py::Float getVolume (void) const
getter for the Volume attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
TopoShape * getTopoShapePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getShapeType (PyObject *self, void *closure)
getter callback for the ShapeType attribute
static int staticCallback_setShapeType (PyObject *self, PyObject *value, void *closure)
setter callback for the ShapeType attribute
static PyObject * staticCallback_getOrientation (PyObject *self, void *closure)
getter callback for the Orientation attribute
static int staticCallback_setOrientation (PyObject *self, PyObject *value, void *closure)
setter callback for the Orientation attribute
static PyObject * staticCallback_getFaces (PyObject *self, void *closure)
getter callback for the Faces attribute
static int staticCallback_setFaces (PyObject *self, PyObject *value, void *closure)
setter callback for the Faces attribute
static PyObject * staticCallback_getVertexes (PyObject *self, void *closure)
getter callback for the Vertexes attribute
static int staticCallback_setVertexes (PyObject *self, PyObject *value, void *closure)
setter callback for the Vertexes attribute
static PyObject * staticCallback_getShells (PyObject *self, void *closure)
getter callback for the Shells attribute
static int staticCallback_setShells (PyObject *self, PyObject *value, void *closure)
setter callback for the Shells attribute
static PyObject * staticCallback_getSolids (PyObject *self, void *closure)
getter callback for the Solids attribute
static int staticCallback_setSolids (PyObject *self, PyObject *value, void *closure)
setter callback for the Solids attribute
static PyObject * staticCallback_getCompSolids (PyObject *self, void *closure)
getter callback for the CompSolids attribute
static int staticCallback_setCompSolids (PyObject *self, PyObject *value, void *closure)
setter callback for the CompSolids attribute
static PyObject * staticCallback_getEdges (PyObject *self, void *closure)
getter callback for the Edges attribute
static int staticCallback_setEdges (PyObject *self, PyObject *value, void *closure)
setter callback for the Edges attribute
static PyObject * staticCallback_getWires (PyObject *self, void *closure)
getter callback for the Wires attribute
static int staticCallback_setWires (PyObject *self, PyObject *value, void *closure)
setter callback for the Wires attribute
static PyObject * staticCallback_getCompounds (PyObject *self, void *closure)
getter callback for the Compounds attribute
static int staticCallback_setCompounds (PyObject *self, PyObject *value, void *closure)
setter callback for the Compounds attribute
static PyObject * staticCallback_getSubShapes (PyObject *self, void *closure)
getter callback for the SubShapes attribute
static int staticCallback_setSubShapes (PyObject *self, PyObject *value, void *closure)
setter callback for the SubShapes attribute
static PyObject * staticCallback_getLength (PyObject *self, void *closure)
getter callback for the Length attribute
static int staticCallback_setLength (PyObject *self, PyObject *value, void *closure)
setter callback for the Length attribute
static PyObject * staticCallback_getArea (PyObject *self, void *closure)
getter callback for the Area attribute
static int staticCallback_setArea (PyObject *self, PyObject *value, void *closure)
setter callback for the Area attribute
static PyObject * staticCallback_getVolume (PyObject *self, void *closure)
getter callback for the Volume attribute
static int staticCallback_setVolume (PyObject *self, PyObject *value, void *closure)
setter callback for the Volume attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for TopoShape.
Member Typedef Documentation
PointerType
typedef TopoShape* Part::TopoShapePy::PointerType
Constructor & Destructor Documentation
~TopoShapePy()
TopoShapePy::~TopoShapePy () protected
TopoShapePy()
TopoShapePy::TopoShapePy (TopoShape * pcObject, PyTypeObject * T = &Type)
Referenced by common(), cut(), fuse(), makeChamfer(), makeFillet(), Part::TopoShapeFacePy::makeOffset(), Part::TopoShapeWirePy::makeOffset(), makeOffsetShape(), makeParallelProjection(), makePerspectiveProjection(), Part::TopoShapeWirePy::makePipe(), Part::TopoShapeWirePy::makePipeShell(), mirror(), multiFuse(), oldFuse(), project(), PyMake(), reflectLines(), removeSplitter(), section(), toNurbs(), and transformGeometry().
Member Function Documentation
ancestorsOfType()
PyObject * TopoShapePy::ancestorsOfType (PyObject * args)
implementer for the ancestorsOfType() method
References Part::buildShapeEnumTypeMap(), Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, Part::shape2pyshape(), and Type.
Referenced by staticCallback_ancestorsOfType().
check()
PyObject * TopoShapePy::check (PyObject * args)
implementer for the check() method
References getTopoShapePtr().
Referenced by Part::TopoShapeShellPy::add(), Part::TopoShapeShellPy::PyInit(), and staticCallback_check().
childShapes()
PyObject * TopoShapePy::childShapes (PyObject * args)
implementer for the childShapes() method
References Part::TopoShape::getShape(), getTopoShapePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_childShapes().
cleaned()
PyObject * TopoShapePy::cleaned (PyObject * args)
implementer for the cleaned() method
References Part::TopoShape::getShape(), getTopoShapePtr(), GetType(), and Part::TopoShape::setShape().
Referenced by staticCallback_cleaned().
common()
PyObject * TopoShapePy::common (PyObject * args)
implementer for the common() method
References Part::TopoShape::common(), Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, draftutils.utils::tolerance(), TopoShapePy(), and Type.
Referenced by staticCallback_common().
complement()
PyObject * TopoShapePy::complement (PyObject * args)
implementer for the complement() method
References Part::TopoShape::getShape(), getTopoShapePtr(), and Part::TopoShape::setShape().
Referenced by staticCallback_complement().
copy()
PyObject * TopoShapePy::copy (PyObject * args)
implementer for the copy() method
References Part::TopoShape::getShape(), getTopoShapePtr(), GetType(), and Part::TopoShape::setShape().
Referenced by staticCallback_copy(), transformed(), and transformShape().
countElement()
PyObject * TopoShapePy::countElement (PyObject * args)
implementer for the countElement() method
References getTopoShapePtr().
Referenced by staticCallback_countElement().
cut()
PyObject * TopoShapePy::cut (PyObject * args)
implementer for the cut() method
References Part::TopoShape::cut(), Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, draftutils.utils::tolerance(), TopoShapePy(), and Type.
Referenced by staticCallback_cut().
defeaturing()
PyObject * TopoShapePy::defeaturing (PyObject * args)
implementer for the defeaturing() method
References Part::TopoShape::defeaturing(), getTopoShapePtr(), GetType(), Part::PartExceptionOCCError, and Part::TopoShape::setShape().
Referenced by staticCallback_defeaturing().
distToShape()
PyObject * TopoShapePy::distToShape (PyObject * args)
implementer for the distToShape() method
References Base::Console(), Part::TopoShape::getShape(), getTopoShapePtr(), Base::ConsoleSingleton::Message(), DraftVecUtils::tup(), Type, and draftgeoutils.general::v1().
Referenced by staticCallback_distToShape().
dumpToString()
PyObject * TopoShapePy::dumpToString (PyObject * args)
implementer for the dumpToString() method
References Part::TopoShape::dump(), getTopoShapePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_dumpToString().
exportBinary()
PyObject * TopoShapePy::exportBinary (PyObject * args)
implementer for the exportBinary() method
References Part::TopoShape::exportBinary(), getTopoShapePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_exportBinary().
exportBrep()
PyObject * TopoShapePy::exportBrep (PyObject * args)
implementer for the exportBrep() method
References Part::TopoShape::exportBrep(), getTopoShapePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_exportBrep().
exportBrepToString()
PyObject * TopoShapePy::exportBrepToString (PyObject * args)
implementer for the exportBrepToString() method
References Part::TopoShape::exportBrep(), getTopoShapePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_exportBrepToString().
exportIges()
PyObject * TopoShapePy::exportIges (PyObject * args)
implementer for the exportIges() method
References Part::TopoShape::exportIges(), getTopoShapePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_exportIges().
exportStep()
PyObject * TopoShapePy::exportStep (PyObject * args)
implementer for the exportStep() method
References Part::TopoShape::exportStep(), getTopoShapePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_exportStep().
exportStl()
PyObject * TopoShapePy::exportStl (PyObject * args)
implementer for the exportStl() method
References Part::TopoShape::exportStl(), getTopoShapePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_exportStl().
extrude()
PyObject * TopoShapePy::extrude (PyObject * args)
implementer for the extrude() method
References getTopoShapePtr(), Part::TopoShape::makePrism(), Part::PartExceptionOCCError, Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_extrude().
findPlane()
PyObject * TopoShapePy::findPlane (PyObject * args)
implementer for the findPlane() method
References getTopoShapePtr().
Referenced by Part::TopoShapeFacePy::makeOffset(), Part::TopoShapeWirePy::makeOffset(), and staticCallback_findPlane().
fix()
PyObject * TopoShapePy::fix (PyObject * args)
implementer for the fix() method
References getTopoShapePtr().
Referenced by fixTolerance(), limitTolerance(), staticCallback_fix(), and Part::TopoShapeFacePy::validate().
fixTolerance()
PyObject * TopoShapePy::fixTolerance (PyObject * args)
implementer for the fixTolerance() method
References fix(), Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, Part::TopoShapeEdgePy::Type, Part::TopoShapeFacePy::Type, Type, Part::TopoShapeVertexPy::Type, and Part::TopoShapeWirePy::Type.
Referenced by staticCallback_fixTolerance().
fuse()
PyObject * TopoShapePy::fuse (PyObject * args)
implementer for the fuse() method
References Part::TopoShape::fuse(), Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, draftutils.utils::tolerance(), TopoShapePy(), and Type.
Referenced by staticCallback_fuse().
generalFuse()
PyObject * TopoShapePy::generalFuse (PyObject * args)
implementer for the generalFuse() method
References Part::TopoShape::generalFuse(), getTopoShapePtr(), Part::PartExceptionOCCError, Part::shape2pyshape(), draftutils.utils::tolerance(), and Type.
Referenced by staticCallback_generalFuse().
getArea()
Py::Float TopoShapePy::getArea (void) const
getter for the Area attribute
References Part::TopoShape::getShape(), and getTopoShapePtr().
Referenced by staticCallback_getArea().
getCompounds()
Py::List TopoShapePy::getCompounds (void) const
getter for the Compounds attribute
References getTopoShapePtr(), and Base::PyObjectBase::setNotTracking().
Referenced by staticCallback_getCompounds().
getCompSolids()
Py::List TopoShapePy::getCompSolids (void) const
getter for the CompSolids attribute
References getTopoShapePtr(), and Base::PyObjectBase::setNotTracking().
Referenced by staticCallback_getCompSolids().
getCustomAttributes()
PyObject * TopoShapePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
References Part::TopoShape::getSubShape(), getTopoShapePtr(), and Part::shape2pyshape().
getEdges()
Py::List TopoShapePy::getEdges (void) const
getter for the Edges attribute
References getTopoShapePtr(), and Base::PyObjectBase::setNotTracking().
Referenced by staticCallback_getEdges().
getElement()
PyObject * TopoShapePy::getElement (PyObject * args)
implementer for the getElement() method
References getTopoShapePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getElement().
getFaces()
Py::List TopoShapePy::getFaces (void) const
getter for the Faces attribute
References getTopoShapePtr().
Referenced by staticCallback_getFaces().
getLength()
Py::Float TopoShapePy::getLength (void) const
getter for the Length attribute
References Part::TopoShape::getShape(), and getTopoShapePtr().
Referenced by staticCallback_getLength().
getOrientation()
Py::String TopoShapePy::getOrientation (void) const
getter for the Orientation attribute
References Base::BaseExceptionFreeCADError, Part::TopoShape::getShape(), and getTopoShapePtr().
Referenced by staticCallback_getOrientation().
getShapeType()
Py::String TopoShapePy::getShapeType (void) const
getter for the ShapeType attribute
References Base::BaseExceptionFreeCADError, Part::TopoShape::getShape(), and getTopoShapePtr().
Referenced by staticCallback_getShapeType().
getShells()
Py::List TopoShapePy::getShells (void) const
getter for the Shells attribute
References getTopoShapePtr().
Referenced by staticCallback_getShells().
getSolids()
Py::List TopoShapePy::getSolids (void) const
getter for the Solids attribute
References getTopoShapePtr(), and Base::PyObjectBase::setNotTracking().
Referenced by staticCallback_getSolids().
getSubShapes()
Py::List TopoShapePy::getSubShapes (void) const
getter for the SubShapes attribute
References getTopoShapePtr(), and Part::shape2pyshape().
Referenced by staticCallback_getSubShapes().
getTolerance()
PyObject * TopoShapePy::getTolerance (PyObject * args)
implementer for the getTolerance() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, draftutils.utils::tolerance(), Part::TopoShapeEdgePy::Type, Part::TopoShapeFacePy::Type, Type, Part::TopoShapeShellPy::Type, and Part::TopoShapeVertexPy::Type.
Referenced by staticCallback_getTolerance().
getTopoShapePtr()
TopoShape * TopoShapePy::getTopoShapePtr (void) const
getter for the object handled by this class
Referenced by ancestorsOfType(), check(), childShapes(), cleaned(), common(), complement(), copy(), countElement(), cut(), defeaturing(), distToShape(), dumpToString(), exportBinary(), exportBrep(), exportBrepToString(), exportIges(), exportStep(), exportStl(), extrude(), findPlane(), fix(), fixTolerance(), fuse(), generalFuse(), getArea(), getCompounds(), getCompSolids(), getCustomAttributes(), getEdges(), getElement(), getFaces(), getLength(), getOrientation(), Part::getPyShapes(), getShapeType(), getShells(), getSolids(), getSubShapes(), getTolerance(), getVertexes(), getVolume(), getWires(), globalTolerance(), hashCode(), importBinary(), importBrep(), importBrepFromString(), inTolerance(), isClosed(), isCoplanar(), isEqual(), isInfinite(), isInside(), isNull(), isPartner(), isSame(), isValid(), limitTolerance(), makeChamfer(), makeFillet(), makeOffset2D(), makeOffsetShape(), makeParallelProjection(), makePerspectiveProjection(), makeShapeFromMesh(), makeThickness(), makeWires(), mirror(), multiFuse(), nullify(), oldFuse(), optimalBoundingBox(), overTolerance(), project(), proximity(), PyInit(), read(), reflectLines(), removeInternalWires(), removeShape(), removeSplitter(), replaceShape(), representation(), reverse(), reversed(), revolve(), rotate(), rotated(), scale(), scaled(), section(), setOrientation(), Part::PropertyPartShape::setPyObject(), sewShape(), slice(), slices(), tessellate(), toNurbs(), transformed(), transformGeometry(), transformShape(), translate(), translated(), and writeInventor().
GetType()
virtual PyTypeObject* Part::TopoShapePy::GetType (void) virtual
Reimplemented from Data::ComplexGeoDataPy.
Reimplemented in Part::TopoShapeWirePy, Part::TopoShapeVertexPy, Part::TopoShapeSolidPy, Part::TopoShapeShellPy, Part::TopoShapeFacePy, Part::TopoShapeEdgePy, Part::TopoShapeCompSolidPy, and Part::TopoShapeCompoundPy.
Referenced by cleaned(), copy(), defeaturing(), removeShape(), replaceShape(), and reversed().
getVertexes()
Py::List TopoShapePy::getVertexes (void) const
getter for the Vertexes attribute
References getTopoShapePtr(), and Base::PyObjectBase::setNotTracking().
Referenced by staticCallback_getVertexes().
getVolume()
Py::Float TopoShapePy::getVolume (void) const
getter for the Volume attribute
References Part::TopoShape::getShape(), and getTopoShapePtr().
Referenced by staticCallback_getVolume().
getWires()
Py::List TopoShapePy::getWires (void) const
getter for the Wires attribute
References getTopoShapePtr().
Referenced by staticCallback_getWires().
globalTolerance()
PyObject * TopoShapePy::globalTolerance (PyObject * args)
implementer for the globalTolerance() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, and draftutils.utils::tolerance().
Referenced by staticCallback_globalTolerance().
hashCode()
PyObject * TopoShapePy::hashCode (PyObject * args)
implementer for the hashCode() method
References Part::TopoShape::getShape(), and getTopoShapePtr().
Referenced by staticCallback_hashCode().
importBinary()
PyObject * TopoShapePy::importBinary (PyObject * args)
implementer for the importBinary() method
References getTopoShapePtr(), Part::TopoShape::importBinary(), and Part::PartExceptionOCCError.
Referenced by staticCallback_importBinary().
importBrep()
PyObject * TopoShapePy::importBrep (PyObject * args)
implementer for the importBrep() method
References getTopoShapePtr(), Part::TopoShape::importBrep(), and Part::PartExceptionOCCError.
Referenced by staticCallback_importBrep().
importBrepFromString()
PyObject * TopoShapePy::importBrepFromString (PyObject * args)
implementer for the importBrepFromString() method
References getTopoShapePtr(), Part::TopoShape::importBrep(), and Part::PartExceptionOCCError.
Referenced by staticCallback_importBrepFromString().
inTolerance()
PyObject * TopoShapePy::inTolerance (PyObject * args)
implementer for the inTolerance() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, Part::shape2pyshape(), Part::TopoShapeEdgePy::Type, Part::TopoShapeFacePy::Type, Type, Part::TopoShapeShellPy::Type, and Part::TopoShapeVertexPy::Type.
Referenced by staticCallback_inTolerance().
isClosed()
PyObject * TopoShapePy::isClosed (PyObject * args)
implementer for the isClosed() method
References getTopoShapePtr().
Referenced by staticCallback_isClosed().
isCoplanar()
PyObject * TopoShapePy::isCoplanar (PyObject * args)
implementer for the isCoplanar() method
References getTopoShapePtr(), and Type.
Referenced by staticCallback_isCoplanar().
isEqual()
PyObject * TopoShapePy::isEqual (PyObject * args)
implementer for the isEqual() method
References Part::TopoShape::getShape(), getTopoShapePtr(), and Type.
Referenced by staticCallback_isEqual().
isInfinite()
PyObject * TopoShapePy::isInfinite (PyObject * args)
implementer for the isInfinite() method
References getTopoShapePtr().
Referenced by staticCallback_isInfinite().
isInside()
PyObject * TopoShapePy::isInside (PyObject * args)
implementer for the isInside() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, draftutils.utils::tolerance(), Base::VectorPy::Type, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by staticCallback_isInside().
isNull()
PyObject * TopoShapePy::isNull (PyObject * args)
implementer for the isNull() method
References getTopoShapePtr(), and Part::TopoShape::isNull().
Referenced by staticCallback_isNull().
isPartner()
PyObject * TopoShapePy::isPartner (PyObject * args)
implementer for the isPartner() method
References Part::TopoShape::getShape(), getTopoShapePtr(), and Type.
Referenced by staticCallback_isPartner().
isSame()
PyObject * TopoShapePy::isSame (PyObject * args)
implementer for the isSame() method
References Part::TopoShape::getShape(), getTopoShapePtr(), and Type.
Referenced by staticCallback_isSame().
isValid()
PyObject * TopoShapePy::isValid (PyObject * args)
implementer for the isValid() method
References getTopoShapePtr(), and Base::PyObjectBase::isValid().
limitTolerance()
PyObject * TopoShapePy::limitTolerance (PyObject * args)
implementer for the limitTolerance() method
References fix(), Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, Part::TopoShapeEdgePy::Type, Part::TopoShapeFacePy::Type, Type, Part::TopoShapeVertexPy::Type, and Part::TopoShapeWirePy::Type.
Referenced by staticCallback_limitTolerance().
makeChamfer()
PyObject * TopoShapePy::makeChamfer (PyObject * args)
implementer for the makeChamfer() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, TopoShapePy(), and Type.
Referenced by staticCallback_makeChamfer().
makeFillet()
PyObject * TopoShapePy::makeFillet (PyObject * args)
implementer for the makeFillet() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, TopoShapePy(), and Type.
Referenced by staticCallback_makeFillet().
makeOffset2D()
PyObject * TopoShapePy::makeOffset2D (PyObject * args, PyObject * kwd)
implementer for the makeOffset2D() method
References getTopoShapePtr(), Part::TopoShape::makeOffset2D(), draftfunctions.offset::offset(), and Part::shape2pyshape().
Referenced by staticCallback_makeOffset2D().
makeOffsetShape()
PyObject * TopoShapePy::makeOffsetShape (PyObject * args, PyObject * kwd)
implementer for the makeOffsetShape() method
References getTopoShapePtr(), Part::TopoShape::makeOffsetShape(), draftfunctions.offset::offset(), Part::PartExceptionOCCError, draftutils.utils::tolerance(), and TopoShapePy().
Referenced by staticCallback_makeOffsetShape().
makeParallelProjection()
PyObject * TopoShapePy::makeParallelProjection (PyObject * args)
implementer for the makeParallelProjection() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, TopoShapePy(), Base::VectorPy::Type, Type, and draftgeoutils.general::vec().
Referenced by staticCallback_makeParallelProjection().
makePerspectiveProjection()
PyObject * TopoShapePy::makePerspectiveProjection (PyObject * args)
implementer for the makePerspectiveProjection() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, TopoShapePy(), Base::VectorPy::Type, Type, and draftgeoutils.general::vec().
Referenced by staticCallback_makePerspectiveProjection().
makeShapeFromMesh()
PyObject * TopoShapePy::makeShapeFromMesh (PyObject * args)
implementer for the makeShapeFromMesh() method
References getTopoShapePtr(), Part::TopoShape::setFaces(), draftutils.utils::tolerance(), DraftVecUtils::tup(), and draftgeoutils.general::vec().
Referenced by staticCallback_makeShapeFromMesh().
makeThickness()
PyObject * TopoShapePy::makeThickness (PyObject * args)
implementer for the makeThickness() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::TopoShape::makeThickSolid(), draftfunctions.offset::offset(), Part::PartExceptionOCCError, draftutils.utils::tolerance(), and Type.
Referenced by staticCallback_makeThickness().
makeWires()
PyObject * TopoShapePy::makeWires (PyObject * args)
implementer for the makeWires() method
References getTopoShapePtr(), and Part::shape2pyshape().
Referenced by staticCallback_makeWires().
mirror()
PyObject * TopoShapePy::mirror (PyObject * args)
implementer for the mirror() method
References getTopoShapePtr(), Part::TopoShape::mirror(), Part::PartExceptionOCCError, TopoShapePy(), Base::VectorPy::Type, draftgeoutils.general::v1(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by staticCallback_mirror().
multiFuse()
PyObject * TopoShapePy::multiFuse (PyObject * args)
implementer for the multiFuse() method
References Part::TopoShape::fuse(), getTopoShapePtr(), Part::PartExceptionOCCError, draftutils.utils::tolerance(), TopoShapePy(), and Type.
Referenced by staticCallback_multiFuse().
nullify()
PyObject * TopoShapePy::nullify (PyObject * args)
implementer for the nullify() method
References Part::TopoShape::getShape(), getTopoShapePtr(), and Part::TopoShape::setShape().
Referenced by staticCallback_nullify().
oldFuse()
PyObject * TopoShapePy::oldFuse (PyObject * args)
implementer for the oldFuse() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::TopoShape::oldFuse(), Part::PartExceptionOCCError, TopoShapePy(), and Type.
Referenced by staticCallback_oldFuse().
optimalBoundingBox()
PyObject * TopoShapePy::optimalBoundingBox (PyObject * args)
implementer for the optimalBoundingBox() method
References Part::TopoShape::getShape(), getTopoShapePtr(), and Base::BoundBox3< _Precision >::MinX.
Referenced by staticCallback_optimalBoundingBox().
overTolerance()
PyObject * TopoShapePy::overTolerance (PyObject * args)
implementer for the overTolerance() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, Part::shape2pyshape(), Part::TopoShapeEdgePy::Type, Part::TopoShapeFacePy::Type, Type, Part::TopoShapeShellPy::Type, and Part::TopoShapeVertexPy::Type.
Referenced by staticCallback_overTolerance().
project()
PyObject * TopoShapePy::project (PyObject * args)
implementer for the project() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, TopoShapePy(), and Type.
Referenced by staticCallback_project().
proximity()
PyObject * TopoShapePy::proximity (PyObject * args)
implementer for the proximity() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, and Type.
Referenced by staticCallback_proximity().
PyInit()
int TopoShapePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Data::ComplexGeoDataPy.
Reimplemented in Part::TopoShapeWirePy, Part::TopoShapeVertexPy, Part::TopoShapeSolidPy, Part::TopoShapeShellPy, Part::TopoShapeFacePy, Part::TopoShapeEdgePy, Part::TopoShapeCompSolidPy, and Part::TopoShapeCompoundPy.
References Part::getPyShapes(), getTopoShapePtr(), Part::TopoShape::setShape(), Part::GeometryPy::Type, and Type.
PyMake()
PyObject * TopoShapePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References TopoShapePy().
read()
PyObject * TopoShapePy::read (PyObject * args)
implementer for the read() method
References getTopoShapePtr(), and Part::TopoShape::read().
Referenced by staticCallback_read().
reflectLines()
PyObject * TopoShapePy::reflectLines (PyObject * args, PyObject * kwds)
implementer for the reflectLines() method
from pivy import coin
rot=Gui.ActiveDocument.ActiveView.getCameraOrientation() vdir=App.Vector(0,0,-1) vdir=rot.multVec(vdir) udir=App.Vector(0,1,0) udir=rot.multVec(udir)
pos=Gui.ActiveDocument.ActiveView.getCameraNode().position.getValue().getValue() pos=App.Vector(*pos)
shape=App.ActiveDocument.ActiveObject.Shape reflect=shape.reflectLines(ViewDir=vdir, ViewPos=pos, UpDir=udir) Part.show(reflect)
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, TopoShapePy(), Base::VectorPy::Type, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by staticCallback_reflectLines().
removeInternalWires()
PyObject * TopoShapePy::removeInternalWires (PyObject * args)
implementer for the removeInternalWires() method
References getTopoShapePtr(), Part::PartExceptionOCCError, and Part::TopoShape::removeInternalWires().
Referenced by staticCallback_removeInternalWires().
removeShape()
PyObject * TopoShapePy::removeShape (PyObject * args)
implementer for the removeShape() method
References getTopoShapePtr(), GetType(), Part::PartExceptionOCCError, Part::TopoShape::removeShape(), and Part::TopoShape::setShape().
Referenced by staticCallback_removeShape().
removeSplitter()
PyObject * TopoShapePy::removeSplitter (PyObject * args)
implementer for the removeSplitter() method
References getTopoShapePtr(), Part::PartExceptionOCCError, Part::TopoShape::removeSplitter(), and TopoShapePy().
Referenced by staticCallback_removeSplitter().
replaceShape()
PyObject * TopoShapePy::replaceShape (PyObject * args)
implementer for the replaceShape() method
References getTopoShapePtr(), GetType(), Part::PartExceptionOCCError, Part::TopoShape::replaceShape(), and Part::TopoShape::setShape().
Referenced by staticCallback_replaceShape().
representation()
std::string TopoShapePy::representation (void) const
References getTopoShapePtr().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
reverse()
PyObject * TopoShapePy::reverse (PyObject * args)
implementer for the reverse() method
References Part::TopoShape::getShape(), getTopoShapePtr(), and Part::TopoShape::setShape().
Referenced by staticCallback_reverse().
reversed()
PyObject * TopoShapePy::reversed (PyObject * args)
implementer for the reversed() method
References Part::TopoShape::getShape(), getTopoShapePtr(), GetType(), and Part::TopoShape::setShape().
Referenced by staticCallback_reversed().
revolve()
PyObject * TopoShapePy::revolve (PyObject * args)
implementer for the revolve() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, Part::TopoShape::revolve(), Base::VectorPy::Type, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by staticCallback_revolve().
rotate()
PyObject * TopoShapePy::rotate (PyObject * args)
implementer for the rotate() method
References DraftVecUtils::angle(), Part::TopoShape::getShape(), getTopoShapePtr(), Base::PyObjectBase::IncRef(), and Part::TopoShape::setShape().
Referenced by rotated(), and staticCallback_rotate().
rotated()
PyObject * TopoShapePy::rotated (PyObject * args)
implementer for the rotated() method
References getTopoShapePtr(), rotate(), and Part::shape2pyshape().
Referenced by staticCallback_rotated().
scale()
PyObject * TopoShapePy::scale (PyObject * args)
implementer for the scale() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Base::PyObjectBase::IncRef(), Part::TopoShape::setShape(), Base::VectorPy::Type, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by scaled(), and staticCallback_scale().
scaled()
PyObject * TopoShapePy::scaled (PyObject * args)
implementer for the scaled() method
References getTopoShapePtr(), scale(), and Part::shape2pyshape().
Referenced by staticCallback_scaled().
section()
PyObject * TopoShapePy::section (PyObject * args)
implementer for the section() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, Part::TopoShape::section(), draftutils.utils::tolerance(), TopoShapePy(), and Type.
Referenced by staticCallback_section().
setCustomAttributes()
int TopoShapePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setOrientation()
void TopoShapePy::setOrientation (Py::String arg)
setter for the Orientation attribute
References Base::BaseExceptionFreeCADError, Part::TopoShape::getShape(), getTopoShapePtr(), and Part::TopoShape::setShape().
Referenced by staticCallback_setOrientation().
sewShape()
PyObject * TopoShapePy::sewShape (PyObject * args)
implementer for the sewShape() method
References getTopoShapePtr(), Part::PartExceptionOCCError, and Part::TopoShape::sewShape().
Referenced by staticCallback_sewShape().
slice()
PyObject * TopoShapePy::slice (PyObject * args)
implementer for the slice() method
References getTopoShapePtr(), Part::PartExceptionOCCError, Part::TopoShape::slice(), Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by slices(), and staticCallback_slice().
slices()
PyObject * TopoShapePy::slices (PyObject * args)
implementer for the slices() method
References DraftVecUtils::dist(), getTopoShapePtr(), Part::PartExceptionOCCError, slice(), Part::TopoShape::slices(), Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_slices().
staticCallback___getstate__()
PyObject * TopoShapePy::staticCallback___getstate__ (PyObject * self, PyObject * args) static
callback for the getstate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback___setstate__()
PyObject * TopoShapePy::staticCallback___setstate__ (PyObject * self, PyObject * args) static
callback for the setstate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_ancestorsOfType()
PyObject * TopoShapePy::staticCallback_ancestorsOfType (PyObject * self, PyObject * args) static
callback for the ancestorsOfType() method
References ancestorsOfType(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_check()
PyObject * TopoShapePy::staticCallback_check (PyObject * self, PyObject * args) static
callback for the check() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, check(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_childShapes()
PyObject * TopoShapePy::staticCallback_childShapes (PyObject * self, PyObject * args) static
callback for the childShapes() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, childShapes(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_cleaned()
PyObject * TopoShapePy::staticCallback_cleaned (PyObject * self, PyObject * args) static
callback for the cleaned() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, cleaned(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_common()
PyObject * TopoShapePy::staticCallback_common (PyObject * self, PyObject * args) static
callback for the common() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, common(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_complement()
PyObject * TopoShapePy::staticCallback_complement (PyObject * self, PyObject * args) static
callback for the complement() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, complement(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_copy()
PyObject * TopoShapePy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copy(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_countElement()
PyObject * TopoShapePy::staticCallback_countElement (PyObject * self, PyObject * args) static
callback for the countElement() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, countElement(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_cut()
PyObject * TopoShapePy::staticCallback_cut (PyObject * self, PyObject * args) static
callback for the cut() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, cut(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_defeaturing()
PyObject * TopoShapePy::staticCallback_defeaturing (PyObject * self, PyObject * args) static
callback for the defeaturing() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, defeaturing(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_distToShape()
PyObject * TopoShapePy::staticCallback_distToShape (PyObject * self, PyObject * args) static
callback for the distToShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, distToShape(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_dumpToString()
PyObject * TopoShapePy::staticCallback_dumpToString (PyObject * self, PyObject * args) static
callback for the dumpToString() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, dumpToString(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_exportBinary()
PyObject * TopoShapePy::staticCallback_exportBinary (PyObject * self, PyObject * args) static
callback for the exportBinary() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, exportBinary(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_exportBrep()
PyObject * TopoShapePy::staticCallback_exportBrep (PyObject * self, PyObject * args) static
callback for the exportBrep() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, exportBrep(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_exportBrepToString()
PyObject * TopoShapePy::staticCallback_exportBrepToString (PyObject * self, PyObject * args) static
callback for the exportBrepToString() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, exportBrepToString(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_exportIges()
PyObject * TopoShapePy::staticCallback_exportIges (PyObject * self, PyObject * args) static
callback for the exportIges() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, exportIges(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_exportStep()
PyObject * TopoShapePy::staticCallback_exportStep (PyObject * self, PyObject * args) static
callback for the exportStep() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, exportStep(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_exportStl()
PyObject * TopoShapePy::staticCallback_exportStl (PyObject * self, PyObject * args) static
callback for the exportStl() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, exportStl(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_extrude()
PyObject * TopoShapePy::staticCallback_extrude (PyObject * self, PyObject * args) static
callback for the extrude() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, extrude(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_findPlane()
PyObject * TopoShapePy::staticCallback_findPlane (PyObject * self, PyObject * args) static
callback for the findPlane() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, findPlane(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_fix()
PyObject * TopoShapePy::staticCallback_fix (PyObject * self, PyObject * args) static
callback for the fix() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, fix(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_fixTolerance()
PyObject * TopoShapePy::staticCallback_fixTolerance (PyObject * self, PyObject * args) static
callback for the fixTolerance() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, fixTolerance(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_fuse()
PyObject * TopoShapePy::staticCallback_fuse (PyObject * self, PyObject * args) static
callback for the fuse() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, fuse(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_generalFuse()
PyObject * TopoShapePy::staticCallback_generalFuse (PyObject * self, PyObject * args) static
callback for the generalFuse() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, generalFuse(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getArea()
PyObject * TopoShapePy::staticCallback_getArea (PyObject * self, void * closure) static
getter callback for the Area attribute
References Base::BaseExceptionFreeCADError, getArea(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCompounds()
PyObject * TopoShapePy::staticCallback_getCompounds (PyObject * self, void * closure) static
getter callback for the Compounds attribute
References Base::BaseExceptionFreeCADError, getCompounds(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCompSolids()
PyObject * TopoShapePy::staticCallback_getCompSolids (PyObject * self, void * closure) static
getter callback for the CompSolids attribute
References Base::BaseExceptionFreeCADError, getCompSolids(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getEdges()
PyObject * TopoShapePy::staticCallback_getEdges (PyObject * self, void * closure) static
getter callback for the Edges attribute
References Base::BaseExceptionFreeCADError, getEdges(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getElement()
PyObject * TopoShapePy::staticCallback_getElement (PyObject * self, PyObject * args) static
callback for the getElement() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getElement(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFaces()
PyObject * TopoShapePy::staticCallback_getFaces (PyObject * self, void * closure) static
getter callback for the Faces attribute
References Base::BaseExceptionFreeCADError, getFaces(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getLength()
PyObject * TopoShapePy::staticCallback_getLength (PyObject * self, void * closure) static
getter callback for the Length attribute
References Base::BaseExceptionFreeCADError, getLength(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getOrientation()
PyObject * TopoShapePy::staticCallback_getOrientation (PyObject * self, void * closure) static
getter callback for the Orientation attribute
References Base::BaseExceptionFreeCADError, getOrientation(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getShapeType()
PyObject * TopoShapePy::staticCallback_getShapeType (PyObject * self, void * closure) static
getter callback for the ShapeType attribute
References Base::BaseExceptionFreeCADError, getShapeType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getShells()
PyObject * TopoShapePy::staticCallback_getShells (PyObject * self, void * closure) static
getter callback for the Shells attribute
References Base::BaseExceptionFreeCADError, getShells(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSolids()
PyObject * TopoShapePy::staticCallback_getSolids (PyObject * self, void * closure) static
getter callback for the Solids attribute
References Base::BaseExceptionFreeCADError, getSolids(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSubShapes()
PyObject * TopoShapePy::staticCallback_getSubShapes (PyObject * self, void * closure) static
getter callback for the SubShapes attribute
References Base::BaseExceptionFreeCADError, getSubShapes(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTolerance()
PyObject * TopoShapePy::staticCallback_getTolerance (PyObject * self, PyObject * args) static
callback for the getTolerance() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getTolerance(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVertexes()
PyObject * TopoShapePy::staticCallback_getVertexes (PyObject * self, void * closure) static
getter callback for the Vertexes attribute
References Base::BaseExceptionFreeCADError, getVertexes(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVolume()
PyObject * TopoShapePy::staticCallback_getVolume (PyObject * self, void * closure) static
getter callback for the Volume attribute
References Base::BaseExceptionFreeCADError, getVolume(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getWires()
PyObject * TopoShapePy::staticCallback_getWires (PyObject * self, void * closure) static
getter callback for the Wires attribute
References Base::BaseExceptionFreeCADError, getWires(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_globalTolerance()
PyObject * TopoShapePy::staticCallback_globalTolerance (PyObject * self, PyObject * args) static
callback for the globalTolerance() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, globalTolerance(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_hashCode()
PyObject * TopoShapePy::staticCallback_hashCode (PyObject * self, PyObject * args) static
callback for the hashCode() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hashCode(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_importBinary()
PyObject * TopoShapePy::staticCallback_importBinary (PyObject * self, PyObject * args) static
callback for the importBinary() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, importBinary(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_importBrep()
PyObject * TopoShapePy::staticCallback_importBrep (PyObject * self, PyObject * args) static
callback for the importBrep() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, importBrep(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_importBrepFromString()
PyObject * TopoShapePy::staticCallback_importBrepFromString (PyObject * self, PyObject * args) static
callback for the importBrepFromString() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, importBrepFromString(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_inTolerance()
PyObject * TopoShapePy::staticCallback_inTolerance (PyObject * self, PyObject * args) static
callback for the inTolerance() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, inTolerance(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isClosed()
PyObject * TopoShapePy::staticCallback_isClosed (PyObject * self, PyObject * args) static
callback for the isClosed() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isClosed(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isCoplanar()
PyObject * TopoShapePy::staticCallback_isCoplanar (PyObject * self, PyObject * args) static
callback for the isCoplanar() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isCoplanar(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isEqual()
PyObject * TopoShapePy::staticCallback_isEqual (PyObject * self, PyObject * args) static
callback for the isEqual() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isEqual(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isInfinite()
PyObject * TopoShapePy::staticCallback_isInfinite (PyObject * self, PyObject * args) static
callback for the isInfinite() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isInfinite(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isInside()
PyObject * TopoShapePy::staticCallback_isInside (PyObject * self, PyObject * args) static
callback for the isInside() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isInside(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isNull()
PyObject * TopoShapePy::staticCallback_isNull (PyObject * self, PyObject * args) static
callback for the isNull() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isNull(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isPartner()
PyObject * TopoShapePy::staticCallback_isPartner (PyObject * self, PyObject * args) static
callback for the isPartner() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isPartner(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isSame()
PyObject * TopoShapePy::staticCallback_isSame (PyObject * self, PyObject * args) static
callback for the isSame() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isSame(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isValid()
PyObject * TopoShapePy::staticCallback_isValid (PyObject * self, PyObject * args) static
callback for the isValid() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_limitTolerance()
PyObject * TopoShapePy::staticCallback_limitTolerance (PyObject * self, PyObject * args) static
callback for the limitTolerance() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), limitTolerance(), and Base::PyObjectBase::PyObjectBase().
staticCallback_makeChamfer()
PyObject * TopoShapePy::staticCallback_makeChamfer (PyObject * self, PyObject * args) static
callback for the makeChamfer() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), makeChamfer(), and Base::PyObjectBase::PyObjectBase().
staticCallback_makeFillet()
PyObject * TopoShapePy::staticCallback_makeFillet (PyObject * self, PyObject * args) static
callback for the makeFillet() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), makeFillet(), and Base::PyObjectBase::PyObjectBase().
staticCallback_makeOffset2D()
PyObject * TopoShapePy::staticCallback_makeOffset2D (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the makeOffset2D() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), makeOffset2D(), and Base::PyObjectBase::PyObjectBase().
staticCallback_makeOffsetShape()
PyObject * TopoShapePy::staticCallback_makeOffsetShape (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the makeOffsetShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), makeOffsetShape(), and Base::PyObjectBase::PyObjectBase().
staticCallback_makeParallelProjection()
PyObject * TopoShapePy::staticCallback_makeParallelProjection (PyObject * self, PyObject * args) static
callback for the makeParallelProjection() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), makeParallelProjection(), and Base::PyObjectBase::PyObjectBase().
staticCallback_makePerspectiveProjection()
PyObject * TopoShapePy::staticCallback_makePerspectiveProjection (PyObject * self, PyObject * args) static
callback for the makePerspectiveProjection() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), makePerspectiveProjection(), and Base::PyObjectBase::PyObjectBase().
staticCallback_makeShapeFromMesh()
PyObject * TopoShapePy::staticCallback_makeShapeFromMesh (PyObject * self, PyObject * args) static
callback for the makeShapeFromMesh() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), makeShapeFromMesh(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_makeThickness()
PyObject * TopoShapePy::staticCallback_makeThickness (PyObject * self, PyObject * args) static
callback for the makeThickness() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), makeThickness(), and Base::PyObjectBase::PyObjectBase().
staticCallback_makeWires()
PyObject * TopoShapePy::staticCallback_makeWires (PyObject * self, PyObject * args) static
callback for the makeWires() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), makeWires(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_mirror()
PyObject * TopoShapePy::staticCallback_mirror (PyObject * self, PyObject * args) static
callback for the mirror() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), mirror(), and Base::PyObjectBase::PyObjectBase().
staticCallback_multiFuse()
PyObject * TopoShapePy::staticCallback_multiFuse (PyObject * self, PyObject * args) static
callback for the multiFuse() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), multiFuse(), and Base::PyObjectBase::PyObjectBase().
staticCallback_nullify()
PyObject * TopoShapePy::staticCallback_nullify (PyObject * self, PyObject * args) static
callback for the nullify() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), nullify(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_oldFuse()
PyObject * TopoShapePy::staticCallback_oldFuse (PyObject * self, PyObject * args) static
callback for the oldFuse() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), oldFuse(), and Base::PyObjectBase::PyObjectBase().
staticCallback_optimalBoundingBox()
PyObject * TopoShapePy::staticCallback_optimalBoundingBox (PyObject * self, PyObject * args) static
callback for the optimalBoundingBox() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), optimalBoundingBox(), and Base::PyObjectBase::PyObjectBase().
staticCallback_overTolerance()
PyObject * TopoShapePy::staticCallback_overTolerance (PyObject * self, PyObject * args) static
callback for the overTolerance() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), overTolerance(), and Base::PyObjectBase::PyObjectBase().
staticCallback_project()
PyObject * TopoShapePy::staticCallback_project (PyObject * self, PyObject * args) static
callback for the project() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), project(), and Base::PyObjectBase::PyObjectBase().
staticCallback_proximity()
PyObject * TopoShapePy::staticCallback_proximity (PyObject * self, PyObject * args) static
callback for the proximity() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), proximity(), and Base::PyObjectBase::PyObjectBase().
staticCallback_read()
PyObject * TopoShapePy::staticCallback_read (PyObject * self, PyObject * args) static
callback for the read() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), read(), and Base::PyObjectBase::startNotify().
staticCallback_reflectLines()
PyObject * TopoShapePy::staticCallback_reflectLines (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the reflectLines() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and reflectLines().
staticCallback_removeInternalWires()
PyObject * TopoShapePy::staticCallback_removeInternalWires (PyObject * self, PyObject * args) static
callback for the removeInternalWires() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeInternalWires(), and Base::PyObjectBase::startNotify().
staticCallback_removeShape()
PyObject * TopoShapePy::staticCallback_removeShape (PyObject * self, PyObject * args) static
callback for the removeShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and removeShape().
staticCallback_removeSplitter()
PyObject * TopoShapePy::staticCallback_removeSplitter (PyObject * self, PyObject * args) static
callback for the removeSplitter() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and removeSplitter().
staticCallback_replaceShape()
PyObject * TopoShapePy::staticCallback_replaceShape (PyObject * self, PyObject * args) static
callback for the replaceShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and replaceShape().
staticCallback_reverse()
PyObject * TopoShapePy::staticCallback_reverse (PyObject * self, PyObject * args) static
callback for the reverse() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), reverse(), and Base::PyObjectBase::startNotify().
staticCallback_reversed()
PyObject * TopoShapePy::staticCallback_reversed (PyObject * self, PyObject * args) static
callback for the reversed() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), reversed(), and Base::PyObjectBase::startNotify().
staticCallback_revolve()
PyObject * TopoShapePy::staticCallback_revolve (PyObject * self, PyObject * args) static
callback for the revolve() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and revolve().
staticCallback_rotate()
PyObject * TopoShapePy::staticCallback_rotate (PyObject * self, PyObject * args) static
callback for the rotate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), rotate(), and Base::PyObjectBase::startNotify().
staticCallback_rotated()
PyObject * TopoShapePy::staticCallback_rotated (PyObject * self, PyObject * args) static
callback for the rotated() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), rotated(), and Base::PyObjectBase::startNotify().
staticCallback_scale()
PyObject * TopoShapePy::staticCallback_scale (PyObject * self, PyObject * args) static
callback for the scale() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), scale(), and Base::PyObjectBase::startNotify().
staticCallback_scaled()
PyObject * TopoShapePy::staticCallback_scaled (PyObject * self, PyObject * args) static
callback for the scaled() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), scaled(), and Base::PyObjectBase::startNotify().
staticCallback_section()
PyObject * TopoShapePy::staticCallback_section (PyObject * self, PyObject * args) static
callback for the section() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and section().
staticCallback_setArea()
int TopoShapePy::staticCallback_setArea (PyObject * self, PyObject * value, void * closure) static
setter callback for the Area attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setCompounds()
int TopoShapePy::staticCallback_setCompounds (PyObject * self, PyObject * value, void * closure) static
setter callback for the Compounds attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setCompSolids()
int TopoShapePy::staticCallback_setCompSolids (PyObject * self, PyObject * value, void * closure) static
setter callback for the CompSolids attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setEdges()
int TopoShapePy::staticCallback_setEdges (PyObject * self, PyObject * value, void * closure) static
setter callback for the Edges attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setFaces()
int TopoShapePy::staticCallback_setFaces (PyObject * self, PyObject * value, void * closure) static
setter callback for the Faces attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setLength()
int TopoShapePy::staticCallback_setLength (PyObject * self, PyObject * value, void * closure) static
setter callback for the Length attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setOrientation()
int TopoShapePy::staticCallback_setOrientation (PyObject * self, PyObject * value, void * closure) static
setter callback for the Orientation attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setOrientation().
staticCallback_setShapeType()
int TopoShapePy::staticCallback_setShapeType (PyObject * self, PyObject * value, void * closure) static
setter callback for the ShapeType attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setShells()
int TopoShapePy::staticCallback_setShells (PyObject * self, PyObject * value, void * closure) static
setter callback for the Shells attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setSolids()
int TopoShapePy::staticCallback_setSolids (PyObject * self, PyObject * value, void * closure) static
setter callback for the Solids attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setSubShapes()
int TopoShapePy::staticCallback_setSubShapes (PyObject * self, PyObject * value, void * closure) static
setter callback for the SubShapes attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setVertexes()
int TopoShapePy::staticCallback_setVertexes (PyObject * self, PyObject * value, void * closure) static
setter callback for the Vertexes attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setVolume()
int TopoShapePy::staticCallback_setVolume (PyObject * self, PyObject * value, void * closure) static
setter callback for the Volume attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setWires()
int TopoShapePy::staticCallback_setWires (PyObject * self, PyObject * value, void * closure) static
setter callback for the Wires attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_sewShape()
PyObject * TopoShapePy::staticCallback_sewShape (PyObject * self, PyObject * args) static
callback for the sewShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), sewShape(), and Base::PyObjectBase::startNotify().
staticCallback_slice()
PyObject * TopoShapePy::staticCallback_slice (PyObject * self, PyObject * args) static
callback for the slice() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and slice().
staticCallback_slices()
PyObject * TopoShapePy::staticCallback_slices (PyObject * self, PyObject * args) static
callback for the slices() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and slices().
staticCallback_tessellate()
PyObject * TopoShapePy::staticCallback_tessellate (PyObject * self, PyObject * args) static
callback for the tessellate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and tessellate().
staticCallback_toNurbs()
PyObject * TopoShapePy::staticCallback_toNurbs (PyObject * self, PyObject * args) static
callback for the toNurbs() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and toNurbs().
staticCallback_transformed()
PyObject * TopoShapePy::staticCallback_transformed (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the transformed() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and transformed().
staticCallback_transformGeometry()
PyObject * TopoShapePy::staticCallback_transformGeometry (PyObject * self, PyObject * args) static
callback for the transformGeometry() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and transformGeometry().
staticCallback_transformShape()
PyObject * TopoShapePy::staticCallback_transformShape (PyObject * self, PyObject * args) static
callback for the transformShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and transformShape().
staticCallback_translate()
PyObject * TopoShapePy::staticCallback_translate (PyObject * self, PyObject * args) static
callback for the translate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and translate().
staticCallback_translated()
PyObject * TopoShapePy::staticCallback_translated (PyObject * self, PyObject * args) static
callback for the translated() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and translated().
staticCallback_writeInventor()
PyObject * TopoShapePy::staticCallback_writeInventor (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the writeInventor() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and writeInventor().
tessellate()
PyObject * TopoShapePy::tessellate (PyObject * args)
implementer for the tessellate() method
References Part::TopoShape::getFaces(), getTopoShapePtr(), Part::PartExceptionOCCError, and draftutils.utils::tolerance().
Referenced by staticCallback_tessellate().
toNurbs()
PyObject * TopoShapePy::toNurbs (PyObject * args)
implementer for the toNurbs() method
References getTopoShapePtr(), Part::PartExceptionOCCError, Part::TopoShape::toNurbs(), and TopoShapePy().
Referenced by staticCallback_toNurbs().
transformed()
PyObject * TopoShapePy::transformed (PyObject * args, PyObject * kwd)
implementer for the transformed() method
References copy(), getTopoShapePtr(), Part::shape2pyshape(), and Base::MatrixPy::Type.
Referenced by staticCallback_transformed().
transformGeometry()
PyObject * TopoShapePy::transformGeometry (PyObject * args)
implementer for the transformGeometry() method
References getTopoShapePtr(), Part::PartExceptionOCCError, TopoShapePy(), Part::TopoShape::transformGShape(), and Base::MatrixPy::Type.
Referenced by staticCallback_transformGeometry().
transformShape()
PyObject * TopoShapePy::transformShape (PyObject * args)
implementer for the transformShape() method
References copy(), getTopoShapePtr(), Base::PyObjectBase::IncRef(), Part::TopoShape::transformShape(), and Base::MatrixPy::Type.
Referenced by staticCallback_transformShape().
translate()
PyObject * TopoShapePy::translate (PyObject * args)
implementer for the translate() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Base::PyObjectBase::IncRef(), Part::TopoShape::setShape(), Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_translate(), and translated().
translated()
PyObject * TopoShapePy::translated (PyObject * args)
implementer for the translated() method
References getTopoShapePtr(), Part::shape2pyshape(), and translate().
Referenced by staticCallback_translated().
writeInventor()
PyObject * TopoShapePy::writeInventor (PyObject * args, PyObject * kwd)
implementer for the writeInventor() method
References Part::TopoShape::exportFaceSet(), Part::TopoShape::exportLineSet(), getTopoShapePtr(), App::PropertyListsT< T, ListT, ParentT >::getValues(), and App::PropertyListsT< T, ListT, ParentT >::setPyObject().
Referenced by staticCallback_writeInventor().
Member Data Documentation
GetterSetter
PyGetSetDef TopoShapePy::GetterSetter static
Attribute structure of TopoShapePy.
Methods
PyMethodDef TopoShapePy::Methods static
Methods structure of TopoShapePy.
Type
PyTypeObject TopoShapePy::Type static
Type structure of TopoShapePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), Part::TopoShapeCompoundPy::add(), Part::TopoShapeWirePy::add(), Part::BRepOffsetAPI_MakePipeShellPy::add(), Path::AreaPy::add(), Fem::FemMeshPy::addHypothesis(), ArchStructure.StructSelectionObserver::addSelection(), ancestorsOfType(), PathSimulator::PathSimPy::BeginSimulation(), ArchSite.Compass::buildCoordinates(), Part::buildShapeEnumTypeMap(), common(), cut(), Part::TopoShapeFacePy::cutHoles(), distToShape(), fixTolerance(), fuse(), generalFuse(), Part::BRepOffsetAPI_MakePipeShellPy::generated(), Part::getPyShapes(), Attacher::AttachEnginePy::getRefTypeOfShape(), getTolerance(), Part::MakePrismPy::init(), Part::UnifySameDomainPy::initialize(), inTolerance(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), isCoplanar(), isEqual(), isPartner(), isSame(), Part::UnifySameDomainPy::keepShape(), limitTolerance(), makeChamfer(), makeFillet(), makeParallelProjection(), makePerspectiveProjection(), Part::TopoShapeWirePy::makePipe(), Part::TopoShapeWirePy::makePipeShell(), Path::AreaPy::makeSections(), makeThickness(), multiFuse(), Part::TopoShapeSolidPy::offsetFaces(), oldFuse(), overTolerance(), Part::MakePrismPy::perform(), Part::MakePrismPy::performFromEnd(), Part::MakePrismPy::performUntilHeight(), project(), proximity(), Part::MakePrismPy::PyInit(), Part::UnifySameDomainPy::PyInit(), Part::TopoShapeCompoundPy::PyInit(), Part::TopoShapeEdgePy::PyInit(), Part::TopoShapeFacePy::PyInit(), PyInit(), Part::TopoShapeSolidPy::PyInit(), Part::TopoShapeVertexPy::PyInit(), Part::TopoShapeWirePy::PyInit(), Part::BRepOffsetAPI_MakePipeShellPy::PyMake(), Part::BRepOffsetAPI_MakePipeShellPy::remove(), section(), Part::BRepOffsetAPI_MakePipeShellPy::setAuxiliarySpine(), Fem::SMESH_HypothesisPy< T >::setParametersByMesh(), Path::AreaPy::setPlane(), Part::TopoShape::setPyObject(), Part::PropertyPartShape::setPyObject(), Fem::FemMeshPy::setShape(), Part::BRepOffsetAPI_MakePipeShellPy::setSpineSupport(), PathSimulator::PathSimPy::SetToolShape(), Path::AreaPy::setWorkplane(), and Path::FeatureAreaPy::setWorkPlane().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/TopoShapePy.h
Sources/FreeCAD/src/Mod/Part/App/TopoShapePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/TopoShapePy.cpp