FreeCAD: Gui::DocumentPy Class Reference
Gui::DocumentPy Class Reference
The python export class for Document.
#include <DocumentPy.h>
Public Types
typedef Document * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
DocumentPy (Document *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of DocumentPy.
static PyMethodDef Methods []
Methods structure of DocumentPy.
static PyTypeObject Type
Type structure of DocumentPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~DocumentPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * show (PyObject *args)
implementer for the show() method
PyObject * hide (PyObject *args)
implementer for the hide() method
PyObject * setPos (PyObject *args)
implementer for the setPos() method
PyObject * setEdit (PyObject *args)
implementer for the setEdit() method
PyObject * getInEdit (PyObject *args)
implementer for the getInEdit() method
PyObject * resetEdit (PyObject *args)
implementer for the resetEdit() method
PyObject * addAnnotation (PyObject *args)
implementer for the addAnnotation() method
PyObject * update (PyObject *args)
implementer for the update() method
PyObject * getObject (PyObject *args)
implementer for the getObject() method
PyObject * activeObject (PyObject *args)
implementer for the activeObject() method
PyObject * activeView (PyObject *args)
implementer for the activeView() method
PyObject * mdiViewsOfType (PyObject *args)
implementer for the mdiViewsOfType() method
PyObject * sendMsgToViews (PyObject *args)
implementer for the sendMsgToViews() method
PyObject * mergeProject (PyObject *args)
implementer for the mergeProject() method
PyObject * toggleTreeItem (PyObject *args)
implementer for the toggleTreeItem() method
PyObject * scrollToTreeItem (PyObject *args)
implementer for the scrollToTreeItem() method
PyObject * toggleInSceneGraph (PyObject *args)
implementer for the toggleInSceneGraph() method
static PyObject * staticCallback_show (PyObject *self, PyObject *args)
callback for the show() method
static PyObject * staticCallback_hide (PyObject *self, PyObject *args)
callback for the hide() method
static PyObject * staticCallback_setPos (PyObject *self, PyObject *args)
callback for the setPos() method
static PyObject * staticCallback_setEdit (PyObject *self, PyObject *args)
callback for the setEdit() method
static PyObject * staticCallback_getInEdit (PyObject *self, PyObject *args)
callback for the getInEdit() method
static PyObject * staticCallback_resetEdit (PyObject *self, PyObject *args)
callback for the resetEdit() method
static PyObject * staticCallback_addAnnotation (PyObject *self, PyObject *args)
callback for the addAnnotation() method
static PyObject * staticCallback_update (PyObject *self, PyObject *args)
callback for the update() method
static PyObject * staticCallback_getObject (PyObject *self, PyObject *args)
callback for the getObject() method
static PyObject * staticCallback_activeObject (PyObject *self, PyObject *args)
callback for the activeObject() method
static PyObject * staticCallback_activeView (PyObject *self, PyObject *args)
callback for the activeView() method
static PyObject * staticCallback_mdiViewsOfType (PyObject *self, PyObject *args)
callback for the mdiViewsOfType() method
static PyObject * staticCallback_sendMsgToViews (PyObject *self, PyObject *args)
callback for the sendMsgToViews() method
static PyObject * staticCallback_mergeProject (PyObject *self, PyObject *args)
callback for the mergeProject() method
static PyObject * staticCallback_toggleTreeItem (PyObject *self, PyObject *args)
callback for the toggleTreeItem() method
static PyObject * staticCallback_scrollToTreeItem (PyObject *self, PyObject *args)
callback for the scrollToTreeItem() method
static PyObject * staticCallback_toggleInSceneGraph (PyObject *self, PyObject *args)
callback for the toggleInSceneGraph() method
callbacks and implementers for the python object attributes
Py::Object getActiveObject (void) const
getter for the ActiveObject attribute
void setActiveObject (Py::Object arg)
setter for the ActiveObject attribute
Py::Object getActiveView (void) const
getter for the ActiveView attribute
void setActiveView (Py::Object arg)
setter for the ActiveView attribute
Py::Object getEditingTransform (void) const
getter for the EditingTransform attribute
void setEditingTransform (Py::Object arg)
setter for the EditingTransform attribute
Py::Object getInEditInfo (void) const
getter for the InEditInfo attribute
void setInEditInfo (Py::Object arg)
setter for the InEditInfo attribute
Py::Int getEditMode (void) const
getter for the EditMode attribute
Py::Object getDocument (void) const
getter for the Document attribute
Py::Boolean getTransacting (void) const
getter for the Transacting attribute
Py::Boolean getModified (void) const
getter for the Modified attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Document * getDocumentPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getActiveObject (PyObject *self, void *closure)
getter callback for the ActiveObject attribute
static int staticCallback_setActiveObject (PyObject *self, PyObject *value, void *closure)
setter callback for the ActiveObject attribute
static PyObject * staticCallback_getActiveView (PyObject *self, void *closure)
getter callback for the ActiveView attribute
static int staticCallback_setActiveView (PyObject *self, PyObject *value, void *closure)
setter callback for the ActiveView attribute
static PyObject * staticCallback_getEditingTransform (PyObject *self, void *closure)
getter callback for the EditingTransform attribute
static int staticCallback_setEditingTransform (PyObject *self, PyObject *value, void *closure)
setter callback for the EditingTransform attribute
static PyObject * staticCallback_getInEditInfo (PyObject *self, void *closure)
getter callback for the InEditInfo attribute
static int staticCallback_setInEditInfo (PyObject *self, PyObject *value, void *closure)
setter callback for the InEditInfo attribute
static PyObject * staticCallback_getEditMode (PyObject *self, void *closure)
getter callback for the EditMode attribute
static int staticCallback_setEditMode (PyObject *self, PyObject *value, void *closure)
setter callback for the EditMode attribute
static PyObject * staticCallback_getDocument (PyObject *self, void *closure)
getter callback for the Document attribute
static int staticCallback_setDocument (PyObject *self, PyObject *value, void *closure)
setter callback for the Document attribute
static PyObject * staticCallback_getTransacting (PyObject *self, void *closure)
getter callback for the Transacting attribute
static int staticCallback_setTransacting (PyObject *self, PyObject *value, void *closure)
setter callback for the Transacting attribute
static PyObject * staticCallback_getModified (PyObject *self, void *closure)
getter callback for the Modified attribute
static int staticCallback_setModified (PyObject *self, PyObject *value, void *closure)
setter callback for the Modified attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Document.
Member Typedef Documentation
PointerType
typedef Document* Gui::DocumentPy::PointerType
Constructor & Destructor Documentation
~DocumentPy()
DocumentPy::~DocumentPy () protected
DocumentPy()
DocumentPy::DocumentPy (Document * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
activeObject()
PyObject * DocumentPy::activeObject (PyObject * args)
implementer for the activeObject() method
References App::Document::getActiveObject(), Gui::Document::getDocument(), getDocumentPtr(), Gui::ViewProvider::getPyObject(), and Gui::Document::getViewProvider().
Referenced by staticCallback_activeObject().
activeView()
PyObject * DocumentPy::activeView (PyObject * args)
implementer for the activeView() method
References Gui::Document::getActiveView(), getDocumentPtr(), and Gui::MDIView::getPyObject().
Referenced by staticCallback_activeView().
addAnnotation()
PyObject * DocumentPy::addAnnotation (PyObject * args)
implementer for the addAnnotation() method
References Gui::ViewProviderExtern::adjustDocumentName(), getDocument(), getDocumentPtr(), Gui::Document::setAnnotationViewProvider(), and Gui::ViewProviderExtern::setModeByFile().
Referenced by staticCallback_addAnnotation().
getActiveObject()
Py::Object DocumentPy::getActiveObject (void) const
getter for the ActiveObject attribute
References App::Document::getActiveObject(), Gui::Document::getDocument(), getDocumentPtr(), Gui::ViewProvider::getPyObject(), and Gui::Document::getViewProvider().
Referenced by staticCallback_getActiveObject().
getActiveView()
Py::Object DocumentPy::getActiveView (void) const
getter for the ActiveView attribute
References Gui::Document::getActiveView(), and getDocumentPtr().
Referenced by staticCallback_getActiveView().
getCustomAttributes()
PyObject * DocumentPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
References getDocumentPtr(), and Gui::Document::getViewProviderByName().
getDocument()
Py::Object DocumentPy::getDocument (void) const
getter for the Document attribute
References Gui::Document::getDocument(), and getDocumentPtr().
Referenced by addAnnotation(), and staticCallback_getDocument().
getDocumentPtr()
Document * DocumentPy::getDocumentPtr (void) const
getter for the object handled by this class
Referenced by activeObject(), activeView(), addAnnotation(), getActiveObject(), getActiveView(), getCustomAttributes(), getDocument(), getEditingTransform(), getEditMode(), getInEdit(), getInEditInfo(), getModified(), getObject(), getTransacting(), hide(), mdiViewsOfType(), mergeProject(), representation(), resetEdit(), scrollToTreeItem(), sendMsgToViews(), setCustomAttributes(), setEdit(), setEditingTransform(), setInEditInfo(), setPos(), show(), toggleInSceneGraph(), toggleTreeItem(), and update().
getEditingTransform()
Py::Object DocumentPy::getEditingTransform (void) const
getter for the EditingTransform attribute
References getDocumentPtr().
Referenced by staticCallback_getEditingTransform().
getEditMode()
Py::Int DocumentPy::getEditMode (void) const
getter for the EditMode attribute
References getDocumentPtr(), and Gui::Document::getInEdit().
Referenced by staticCallback_getEditMode().
getInEdit()
PyObject * DocumentPy::getInEdit (PyObject * args)
implementer for the getInEdit() method
References getDocumentPtr(), Gui::Document::getInEdit(), and Gui::ViewProvider::getPyObject().
Referenced by staticCallback_getInEdit().
getInEditInfo()
Py::Object DocumentPy::getInEditInfo (void) const
getter for the InEditInfo attribute
References getDocumentPtr(), Gui::Document::getInEdit(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), and App::DocumentObject::getPyObject().
Referenced by staticCallback_getInEditInfo().
getModified()
Py::Boolean DocumentPy::getModified (void) const
getter for the Modified attribute
References getDocumentPtr().
Referenced by staticCallback_getModified().
getObject()
PyObject * DocumentPy::getObject (PyObject * args)
implementer for the getObject() method
References getDocumentPtr(), Gui::ViewProvider::getPyObject(), and Gui::Document::getViewProviderByName().
Referenced by staticCallback_getObject().
getTransacting()
Py::Boolean DocumentPy::getTransacting (void) const
getter for the Transacting attribute
References getDocumentPtr().
Referenced by staticCallback_getTransacting().
GetType()
virtual PyTypeObject* Gui::DocumentPy::GetType (void) virtual
Reimplemented from Base::PersistencePy.
hide()
PyObject * DocumentPy::hide (PyObject * args)
implementer for the hide() method
References getDocumentPtr(), and Gui::Document::setHide().
Referenced by Mod.Show.mTempoVis.TempoVis::hide_all_dependencies(), Mod.Show.mTempoVis.TempoVis::hide_all_dependent(), and staticCallback_hide().
mdiViewsOfType()
PyObject * DocumentPy::mdiViewsOfType (PyObject * args)
implementer for the mdiViewsOfType() method
References Base::Type::badType(), Base::BaseExceptionFreeCADError, Base::Type::fromName(), getDocumentPtr(), and Gui::Document::getMDIViewsOfType().
Referenced by staticCallback_mdiViewsOfType().
mergeProject()
PyObject * DocumentPy::mergeProject (PyObject * args)
implementer for the mergeProject() method
References Gui::Document::getDocument(), getDocumentPtr(), and Gui::MergeDocuments::importObjects().
Referenced by staticCallback_mergeProject().
PyInit()
int DocumentPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PersistencePy.
PyMake()
PyObject * DocumentPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string DocumentPy::representation (void) const
References getDocumentPtr().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
resetEdit()
PyObject * DocumentPy::resetEdit (PyObject * args)
implementer for the resetEdit() method
References getDocumentPtr(), and Gui::Document::resetEdit().
Referenced by staticCallback_resetEdit().
scrollToTreeItem()
PyObject * DocumentPy::scrollToTreeItem (PyObject * args)
implementer for the scrollToTreeItem() method
References getDocumentPtr(), Gui::Document::signalScrollToObject, and Gui::ViewProviderDocumentObjectPy::Type.
Referenced by staticCallback_scrollToTreeItem().
sendMsgToViews()
PyObject * DocumentPy::sendMsgToViews (PyObject * args)
implementer for the sendMsgToViews() method
References getDocumentPtr(), and Gui::Document::sendMsgToViews().
Referenced by staticCallback_sendMsgToViews().
setActiveObject()
void DocumentPy::setActiveObject (Py::Object arg)
setter for the ActiveObject attribute
Referenced by staticCallback_setActiveObject().
setActiveView()
void DocumentPy::setActiveView (Py::Object arg)
setter for the ActiveView attribute
Referenced by staticCallback_setActiveView().
setCustomAttributes()
int DocumentPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
References getDocumentPtr(), and Gui::Document::getViewProviderByName().
setEdit()
PyObject * DocumentPy::setEdit (PyObject * args)
implementer for the setEdit() method
References Base::BaseExceptionFreeCADError, Gui::Document::getDocument(), getDocumentPtr(), App::Document::getObject(), Gui::Application::getViewProvider(), Gui::ViewProviderPy::getViewProviderPtr(), Gui::Application::Instance, Gui::Document::setEdit(), App::DocumentObjectPy::Type, and Gui::ViewProviderPy::Type.
Referenced by ArchAxis.ViewProviderArchGrid::doubleClicked(), ArchReference.ViewProviderArchReference::doubleClicked(), draftviewproviders.view_dimension.ViewProviderDimensionBase::doubleClicked(), PathScripts.PathSetupSheetGui.ViewProvider::doubleClicked(), PathScripts.PathToolBitGui.ViewProvider::doubleClicked(), Spreadsheet_legacy.ViewProviderSpreadsheet::doubleClicked(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), PathScripts.PathIconViewProvider.ViewProvider::setupContextMenu(), PathScripts.PathJobGui.ViewProvider::setupContextMenu(), PathScripts.PathOpGui.ViewProvider::setupContextMenu(), PathScripts.PathToolControllerGui.ViewProvider::setupContextMenu(), and staticCallback_setEdit().
setEditingTransform()
void DocumentPy::setEditingTransform (Py::Object arg)
setter for the EditingTransform attribute
References getDocumentPtr(), Base::MatrixPy::getMatrixPtr(), Gui::Document::setEditingTransform(), and Base::MatrixPy::Type.
Referenced by staticCallback_setEditingTransform().
setInEditInfo()
void DocumentPy::setInEditInfo (Py::Object arg)
setter for the InEditInfo attribute
References getDocumentPtr(), Gui::Document::setInEdit(), and Gui::ViewProviderDocumentObjectPy::Type.
Referenced by staticCallback_setInEditInfo().
setPos()
PyObject * DocumentPy::setPos (PyObject * args)
implementer for the setPos() method
References getDocumentPtr(), Gui::Document::setPos(), and Base::MatrixPy::Type.
Referenced by staticCallback_setPos().
show()
PyObject * DocumentPy::show (PyObject * args)
implementer for the show() method
References getDocumentPtr(), and Gui::Document::setShow().
Referenced by Mod.Show.mTempoVis.TempoVis::show_all_dependencies(), Mod.Show.mTempoVis.TempoVis::show_all_dependent(), and staticCallback_show().
staticCallback_activeObject()
PyObject * DocumentPy::staticCallback_activeObject (PyObject * self, PyObject * args) static
callback for the activeObject() method
References activeObject(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_activeView()
PyObject * DocumentPy::staticCallback_activeView (PyObject * self, PyObject * args) static
callback for the activeView() method
References activeView(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addAnnotation()
PyObject * DocumentPy::staticCallback_addAnnotation (PyObject * self, PyObject * args) static
callback for the addAnnotation() method
References addAnnotation(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getActiveObject()
PyObject * DocumentPy::staticCallback_getActiveObject (PyObject * self, void * closure) static
getter callback for the ActiveObject attribute
References Base::BaseExceptionFreeCADError, getActiveObject(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getActiveView()
PyObject * DocumentPy::staticCallback_getActiveView (PyObject * self, void * closure) static
getter callback for the ActiveView attribute
References Base::BaseExceptionFreeCADError, getActiveView(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getDocument()
PyObject * DocumentPy::staticCallback_getDocument (PyObject * self, void * closure) static
getter callback for the Document attribute
References Base::BaseExceptionFreeCADError, getDocument(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getEditingTransform()
PyObject * DocumentPy::staticCallback_getEditingTransform (PyObject * self, void * closure) static
getter callback for the EditingTransform attribute
References Base::BaseExceptionFreeCADError, getEditingTransform(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getEditMode()
PyObject * DocumentPy::staticCallback_getEditMode (PyObject * self, void * closure) static
getter callback for the EditMode attribute
References Base::BaseExceptionFreeCADError, getEditMode(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getInEdit()
PyObject * DocumentPy::staticCallback_getInEdit (PyObject * self, PyObject * args) static
callback for the getInEdit() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getInEdit(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getInEditInfo()
PyObject * DocumentPy::staticCallback_getInEditInfo (PyObject * self, void * closure) static
getter callback for the InEditInfo attribute
References Base::BaseExceptionFreeCADError, getInEditInfo(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getModified()
PyObject * DocumentPy::staticCallback_getModified (PyObject * self, void * closure) static
getter callback for the Modified attribute
References Base::BaseExceptionFreeCADError, getModified(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getObject()
PyObject * DocumentPy::staticCallback_getObject (PyObject * self, PyObject * args) static
callback for the getObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getObject(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getTransacting()
PyObject * DocumentPy::staticCallback_getTransacting (PyObject * self, void * closure) static
getter callback for the Transacting attribute
References Base::BaseExceptionFreeCADError, getTransacting(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_hide()
PyObject * DocumentPy::staticCallback_hide (PyObject * self, PyObject * args) static
callback for the hide() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hide(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_mdiViewsOfType()
PyObject * DocumentPy::staticCallback_mdiViewsOfType (PyObject * self, PyObject * args) static
callback for the mdiViewsOfType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), mdiViewsOfType(), and Base::PyObjectBase::PyObjectBase().
staticCallback_mergeProject()
PyObject * DocumentPy::staticCallback_mergeProject (PyObject * self, PyObject * args) static
callback for the mergeProject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), mergeProject(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_resetEdit()
PyObject * DocumentPy::staticCallback_resetEdit (PyObject * self, PyObject * args) static
callback for the resetEdit() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), resetEdit(), and Base::PyObjectBase::startNotify().
staticCallback_scrollToTreeItem()
PyObject * DocumentPy::staticCallback_scrollToTreeItem (PyObject * self, PyObject * args) static
callback for the scrollToTreeItem() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), scrollToTreeItem(), and Base::PyObjectBase::startNotify().
staticCallback_sendMsgToViews()
PyObject * DocumentPy::staticCallback_sendMsgToViews (PyObject * self, PyObject * args) static
callback for the sendMsgToViews() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), sendMsgToViews(), and Base::PyObjectBase::startNotify().
staticCallback_setActiveObject()
int DocumentPy::staticCallback_setActiveObject (PyObject * self, PyObject * value, void * closure) static
setter callback for the ActiveObject attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setActiveObject().
staticCallback_setActiveView()
int DocumentPy::staticCallback_setActiveView (PyObject * self, PyObject * value, void * closure) static
setter callback for the ActiveView attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setActiveView().
staticCallback_setDocument()
int DocumentPy::staticCallback_setDocument (PyObject * self, PyObject * value, void * closure) static
setter callback for the Document attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setEdit()
PyObject * DocumentPy::staticCallback_setEdit (PyObject * self, PyObject * args) static
callback for the setEdit() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setEdit(), and Base::PyObjectBase::startNotify().
staticCallback_setEditingTransform()
int DocumentPy::staticCallback_setEditingTransform (PyObject * self, PyObject * value, void * closure) static
setter callback for the EditingTransform attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setEditingTransform().
staticCallback_setEditMode()
int DocumentPy::staticCallback_setEditMode (PyObject * self, PyObject * value, void * closure) static
setter callback for the EditMode attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setInEditInfo()
int DocumentPy::staticCallback_setInEditInfo (PyObject * self, PyObject * value, void * closure) static
setter callback for the InEditInfo attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setInEditInfo().
staticCallback_setModified()
int DocumentPy::staticCallback_setModified (PyObject * self, PyObject * value, void * closure) static
setter callback for the Modified attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPos()
PyObject * DocumentPy::staticCallback_setPos (PyObject * self, PyObject * args) static
callback for the setPos() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setPos(), and Base::PyObjectBase::startNotify().
staticCallback_setTransacting()
int DocumentPy::staticCallback_setTransacting (PyObject * self, PyObject * value, void * closure) static
setter callback for the Transacting attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_show()
PyObject * DocumentPy::staticCallback_show (PyObject * self, PyObject * args) static
callback for the show() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), show(), and Base::PyObjectBase::startNotify().
staticCallback_toggleInSceneGraph()
PyObject * DocumentPy::staticCallback_toggleInSceneGraph (PyObject * self, PyObject * args) static
callback for the toggleInSceneGraph() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and toggleInSceneGraph().
staticCallback_toggleTreeItem()
PyObject * DocumentPy::staticCallback_toggleTreeItem (PyObject * self, PyObject * args) static
callback for the toggleTreeItem() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and toggleTreeItem().
staticCallback_update()
PyObject * DocumentPy::staticCallback_update (PyObject * self, PyObject * args) static
callback for the update() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and update().
toggleInSceneGraph()
PyObject * DocumentPy::toggleInSceneGraph (PyObject * args)
implementer for the toggleInSceneGraph() method
References getDocumentPtr(), Gui::Document::toggleInSceneGraph(), and Gui::ViewProviderPy::Type.
Referenced by staticCallback_toggleInSceneGraph().
toggleTreeItem()
PyObject * DocumentPy::toggleTreeItem (PyObject * args)
implementer for the toggleTreeItem() method
References Gui::ExpandItem, getDocumentPtr(), App::DocumentObject::getSubObject(), Gui::Document::getViewProvider(), Gui::Document::signalExpandObject, and App::DocumentObjectPy::Type.
Referenced by staticCallback_toggleTreeItem().
update()
PyObject * DocumentPy::update (PyObject * args)
implementer for the update() method
References getDocumentPtr(), and Gui::Document::onUpdate().
Referenced by ArchAxis.AxisSystemTaskPanel::addElement(), ArchComponent.ComponentTaskPanel::addElement(), ArchSectionPlane.SectionPlaneTaskPanel::addElement(), DraftGui.FacebinderTaskPanel::addElement(), femtaskpanels.task_result_mechanical._TaskPanel::calculate(), Spreadsheet_legacy.SpreadsheetView::changeCell(), draftguitools.gui_edit.Edit::endEditing(), draftguitools.gui_trackers.boxTracker::height(), ArchAxis.CommandArchGrid::IsActive(), draftguitools.gui_trackers.rectangleTracker::p3(), Plot.Plot::plot(), Spreadsheet_legacy.SpreadsheetView::recompute(), ArchAxis.AxisSystemTaskPanel::removeElement(), ArchComponent.ComponentTaskPanel::removeElement(), ArchSectionPlane.SectionPlaneTaskPanel::removeElement(), DraftGui.FacebinderTaskPanel::removeElement(), draftguitools.gui_trackers.gridTracker::reset(), ArchNesting.Nester::run(), and staticCallback_update().
Member Data Documentation
GetterSetter
PyGetSetDef DocumentPy::GetterSetter static
Attribute structure of DocumentPy.
Methods
PyMethodDef DocumentPy::Methods static
Methods structure of DocumentPy.
Type
PyTypeObject DocumentPy::Type static
Type structure of DocumentPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), Gui::Application::Application(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Gui/DocumentPy.h
Sources/FreeCAD/src/Gui/DocumentPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Gui/DocumentPy.cpp