FreeCAD: Base::MatrixPy Class Reference
Base::MatrixPy Class Reference
The python export class for Matrix.
#include <MatrixPy.h>
Public Types
typedef Matrix4D * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
MatrixPy (Matrix4D *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
additional declarations and methods for the wrapper class
MatrixPy (const Matrix4D &mat, PyTypeObject *T=&Type)
Matrix4D value () const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * richCompare (PyObject *v, PyObject *w, int op)
callbacks and implementers for the python object number protocol
static PyObject * number_add_handler (PyObject *self, PyObject *other)
callback for the number_add_handler
static PyObject * number_subtract_handler (PyObject *self, PyObject *other)
callback for the number_subtract_handler
static PyObject * number_multiply_handler (PyObject *self, PyObject *other)
callback for the number_multiply_handler
static PyObject * number_divide_handler (PyObject *self, PyObject *other)
callback for the number_divide_handler
static PyObject * number_remainder_handler (PyObject *self, PyObject *other)
callback for the number_remainder_handler
static PyObject * number_divmod_handler (PyObject *self, PyObject *other)
callback for the number_divmod_handler
static PyObject * number_power_handler (PyObject *self, PyObject *other, PyObject *modulo)
callback for the number_power_handler
static PyObject * number_negative_handler (PyObject *self)
callback for the number_negative_handler
static PyObject * number_positive_handler (PyObject *self)
callback for the number_positive_handler
static PyObject * number_absolute_handler (PyObject *self)
callback for the number_absolute_handler
static int number_nonzero_handler (PyObject *self)
callback for the number_nonzero_handler
static PyObject * number_invert_handler (PyObject *self)
callback for the number_invert_handler
static PyObject * number_lshift_handler (PyObject *self, PyObject *other)
callback for the number_lshift_handler
static PyObject * number_rshift_handler (PyObject *self, PyObject *other)
callback for the number_rshift_handler
static PyObject * number_and_handler (PyObject *self, PyObject *other)
callback for the number_and_handler
static PyObject * number_xor_handler (PyObject *self, PyObject *other)
callback for the number_xor_handler
static PyObject * number_or_handler (PyObject *self, PyObject *other)
callback for the number_or_handler
static int number_coerce_handler (PyObject **self, PyObject **other)
callback for the number_coerce_handler
static PyObject * number_int_handler (PyObject *self)
callback for the number_int_handler
static PyObject * number_long_handler (PyObject *self)
callback for the number_long_handler
static PyObject * number_float_handler (PyObject *self)
callback for the number_float_handler
static PyObject * number_oct_handler (PyObject *self)
callback for the number_oct_handler
static PyObject * number_hex_handler (PyObject *self)
callback for the number_hex_handler
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of MatrixPy.
static PyMethodDef Methods []
Methods structure of MatrixPy.
static PyNumberMethods Number []
static PyTypeObject Type
Type structure of MatrixPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~MatrixPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
static PyObject * staticCallback_move (PyObject *self, PyObject *args)
callback for the move() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_hasScale (PyObject *self, PyObject *args)
callback for the hasScale() method
static PyObject * staticCallback_unity (PyObject *self, PyObject *args)
callback for the unity() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_rotateX (PyObject *self, PyObject *args)
callback for the rotateX() method
static PyObject * staticCallback_rotateY (PyObject *self, PyObject *args)
callback for the rotateY() method
static PyObject * staticCallback_rotateZ (PyObject *self, PyObject *args)
callback for the rotateZ() method
static PyObject * staticCallback_multiply (PyObject *self, PyObject *args)
callback for the multiply() method
static PyObject * staticCallback_multVec (PyObject *self, PyObject *args)
callback for the multVec() method
static PyObject * staticCallback_invert (PyObject *self, PyObject *args)
callback for the invert() method
static PyObject * staticCallback_inverse (PyObject *self, PyObject *args)
callback for the inverse() method
static PyObject * staticCallback_transpose (PyObject *self, PyObject *args)
callback for the transpose() method
static PyObject * staticCallback_transposed (PyObject *self, PyObject *args)
callback for the transposed() method
static PyObject * staticCallback_determinant (PyObject *self, PyObject *args)
callback for the determinant() method
static PyObject * staticCallback_isOrthogonal (PyObject *self, PyObject *args)
callback for the isOrthogonal() method
static PyObject * staticCallback_submatrix (PyObject *self, PyObject *args)
callback for the submatrix() method
static PyObject * staticCallback_analyze (PyObject *self, PyObject *args)
callback for the analyze() method
PyObject * move (PyObject *args)
implementer for the move() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * hasScale (PyObject *args)
implementer for the hasScale() method
PyObject * unity (PyObject *args)
implementer for the unity() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * rotateX (PyObject *args)
implementer for the rotateX() method
PyObject * rotateY (PyObject *args)
implementer for the rotateY() method
PyObject * rotateZ (PyObject *args)
implementer for the rotateZ() method
PyObject * multiply (PyObject *args)
implementer for the multiply() method
PyObject * multVec (PyObject *args)
implementer for the multVec() method
PyObject * invert (PyObject *args)
implementer for the invert() method
PyObject * inverse (PyObject *args)
implementer for the inverse() method
PyObject * transpose (PyObject *args)
implementer for the transpose() method
PyObject * transposed (PyObject *args)
implementer for the transposed() method
PyObject * determinant (PyObject *args)
implementer for the determinant() method
PyObject * isOrthogonal (PyObject *args)
implementer for the isOrthogonal() method
PyObject * submatrix (PyObject *args)
implementer for the submatrix() method
PyObject * analyze (PyObject *args)
implementer for the analyze() method
callbacks and implementers for the python object attributes
static PyObject * staticCallback_getA11 (PyObject *self, void *closure)
getter callback for the A11 attribute
static int staticCallback_setA11 (PyObject *self, PyObject *value, void *closure)
setter callback for the A11 attribute
static PyObject * staticCallback_getA12 (PyObject *self, void *closure)
getter callback for the A12 attribute
static int staticCallback_setA12 (PyObject *self, PyObject *value, void *closure)
setter callback for the A12 attribute
static PyObject * staticCallback_getA13 (PyObject *self, void *closure)
getter callback for the A13 attribute
static int staticCallback_setA13 (PyObject *self, PyObject *value, void *closure)
setter callback for the A13 attribute
static PyObject * staticCallback_getA14 (PyObject *self, void *closure)
getter callback for the A14 attribute
static int staticCallback_setA14 (PyObject *self, PyObject *value, void *closure)
setter callback for the A14 attribute
static PyObject * staticCallback_getA21 (PyObject *self, void *closure)
getter callback for the A21 attribute
static int staticCallback_setA21 (PyObject *self, PyObject *value, void *closure)
setter callback for the A21 attribute
static PyObject * staticCallback_getA22 (PyObject *self, void *closure)
getter callback for the A22 attribute
static int staticCallback_setA22 (PyObject *self, PyObject *value, void *closure)
setter callback for the A22 attribute
static PyObject * staticCallback_getA23 (PyObject *self, void *closure)
getter callback for the A23 attribute
static int staticCallback_setA23 (PyObject *self, PyObject *value, void *closure)
setter callback for the A23 attribute
static PyObject * staticCallback_getA24 (PyObject *self, void *closure)
getter callback for the A24 attribute
static int staticCallback_setA24 (PyObject *self, PyObject *value, void *closure)
setter callback for the A24 attribute
static PyObject * staticCallback_getA31 (PyObject *self, void *closure)
getter callback for the A31 attribute
static int staticCallback_setA31 (PyObject *self, PyObject *value, void *closure)
setter callback for the A31 attribute
static PyObject * staticCallback_getA32 (PyObject *self, void *closure)
getter callback for the A32 attribute
static int staticCallback_setA32 (PyObject *self, PyObject *value, void *closure)
setter callback for the A32 attribute
static PyObject * staticCallback_getA33 (PyObject *self, void *closure)
getter callback for the A33 attribute
static int staticCallback_setA33 (PyObject *self, PyObject *value, void *closure)
setter callback for the A33 attribute
static PyObject * staticCallback_getA34 (PyObject *self, void *closure)
getter callback for the A34 attribute
static int staticCallback_setA34 (PyObject *self, PyObject *value, void *closure)
setter callback for the A34 attribute
static PyObject * staticCallback_getA41 (PyObject *self, void *closure)
getter callback for the A41 attribute
static int staticCallback_setA41 (PyObject *self, PyObject *value, void *closure)
setter callback for the A41 attribute
static PyObject * staticCallback_getA42 (PyObject *self, void *closure)
getter callback for the A42 attribute
static int staticCallback_setA42 (PyObject *self, PyObject *value, void *closure)
setter callback for the A42 attribute
static PyObject * staticCallback_getA43 (PyObject *self, void *closure)
getter callback for the A43 attribute
static int staticCallback_setA43 (PyObject *self, PyObject *value, void *closure)
setter callback for the A43 attribute
static PyObject * staticCallback_getA44 (PyObject *self, void *closure)
getter callback for the A44 attribute
static int staticCallback_setA44 (PyObject *self, PyObject *value, void *closure)
setter callback for the A44 attribute
static PyObject * staticCallback_getA (PyObject *self, void *closure)
getter callback for the A attribute
static int staticCallback_setA (PyObject *self, PyObject *value, void *closure)
setter callback for the A attribute
Py::Float getA11 (void) const
getter for the A11 attribute
void setA11 (Py::Float arg)
setter for the A11 attribute
Py::Float getA12 (void) const
getter for the A12 attribute
void setA12 (Py::Float arg)
setter for the A12 attribute
Py::Float getA13 (void) const
getter for the A13 attribute
void setA13 (Py::Float arg)
setter for the A13 attribute
Py::Float getA14 (void) const
getter for the A14 attribute
void setA14 (Py::Float arg)
setter for the A14 attribute
Py::Float getA21 (void) const
getter for the A21 attribute
void setA21 (Py::Float arg)
setter for the A21 attribute
Py::Float getA22 (void) const
getter for the A22 attribute
void setA22 (Py::Float arg)
setter for the A22 attribute
Py::Float getA23 (void) const
getter for the A23 attribute
void setA23 (Py::Float arg)
setter for the A23 attribute
Py::Float getA24 (void) const
getter for the A24 attribute
void setA24 (Py::Float arg)
setter for the A24 attribute
Py::Float getA31 (void) const
getter for the A31 attribute
void setA31 (Py::Float arg)
setter for the A31 attribute
Py::Float getA32 (void) const
getter for the A32 attribute
void setA32 (Py::Float arg)
setter for the A32 attribute
Py::Float getA33 (void) const
getter for the A33 attribute
void setA33 (Py::Float arg)
setter for the A33 attribute
Py::Float getA34 (void) const
getter for the A34 attribute
void setA34 (Py::Float arg)
setter for the A34 attribute
Py::Float getA41 (void) const
getter for the A41 attribute
void setA41 (Py::Float arg)
setter for the A41 attribute
Py::Float getA42 (void) const
getter for the A42 attribute
void setA42 (Py::Float arg)
setter for the A42 attribute
Py::Float getA43 (void) const
getter for the A43 attribute
void setA43 (Py::Float arg)
setter for the A43 attribute
Py::Float getA44 (void) const
getter for the A44 attribute
void setA44 (Py::Float arg)
setter for the A44 attribute
Py::Sequence getA (void) const
getter for the A attribute
void setA (Py::Sequence arg)
setter for the A attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Matrix4D * getMatrixPtr (void) const
getter for the object handled by this class
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Matrix.
Member Typedef Documentation
PointerType
typedef Matrix4D* Base::MatrixPy::PointerType
Constructor & Destructor Documentation
~MatrixPy()
MatrixPy::~MatrixPy () protected
MatrixPy() [1/2]
MatrixPy::MatrixPy (Matrix4D * pcObject, PyTypeObject * T = &Type)
Referenced by inverse(), multiply(), number_add_handler(), number_multiply_handler(), number_power_handler(), number_subtract_handler(), PyMake(), submatrix(), and transposed().
MatrixPy() [2/2]
Base::MatrixPy::MatrixPy (const Matrix4D & mat, PyTypeObject * T = &Type)
Member Function Documentation
analyze()
PyObject * MatrixPy::analyze (PyObject * args)
implementer for the analyze() method
References Base::Matrix4D::analyse(), and getMatrixPtr().
Referenced by staticCallback_analyze().
determinant()
PyObject * MatrixPy::determinant (PyObject * args)
implementer for the determinant() method
References getMatrixPtr().
Referenced by inverse(), invert(), and staticCallback_determinant().
getA()
Py::Sequence MatrixPy::getA (void) const
getter for the A attribute
References Base::Matrix4D::getMatrix(), getMatrixPtr(), and draftfunctions.move::move().
Referenced by staticCallback_getA().
getA11()
Py::Float MatrixPy::getA11 (void) const
getter for the A11 attribute
References getMatrixPtr().
Referenced by staticCallback_getA11().
getA12()
Py::Float MatrixPy::getA12 (void) const
getter for the A12 attribute
References getMatrixPtr().
Referenced by staticCallback_getA12().
getA13()
Py::Float MatrixPy::getA13 (void) const
getter for the A13 attribute
References getMatrixPtr().
Referenced by staticCallback_getA13().
getA14()
Py::Float MatrixPy::getA14 (void) const
getter for the A14 attribute
References getMatrixPtr().
Referenced by staticCallback_getA14().
getA21()
Py::Float MatrixPy::getA21 (void) const
getter for the A21 attribute
References getMatrixPtr().
Referenced by staticCallback_getA21().
getA22()
Py::Float MatrixPy::getA22 (void) const
getter for the A22 attribute
References getMatrixPtr().
Referenced by staticCallback_getA22().
getA23()
Py::Float MatrixPy::getA23 (void) const
getter for the A23 attribute
References getMatrixPtr().
Referenced by staticCallback_getA23().
getA24()
Py::Float MatrixPy::getA24 (void) const
getter for the A24 attribute
References getMatrixPtr().
Referenced by staticCallback_getA24().
getA31()
Py::Float MatrixPy::getA31 (void) const
getter for the A31 attribute
References getMatrixPtr().
Referenced by staticCallback_getA31().
getA32()
Py::Float MatrixPy::getA32 (void) const
getter for the A32 attribute
References getMatrixPtr().
Referenced by staticCallback_getA32().
getA33()
Py::Float MatrixPy::getA33 (void) const
getter for the A33 attribute
References getMatrixPtr().
Referenced by staticCallback_getA33().
getA34()
Py::Float MatrixPy::getA34 (void) const
getter for the A34 attribute
References getMatrixPtr().
Referenced by staticCallback_getA34().
getA41()
Py::Float MatrixPy::getA41 (void) const
getter for the A41 attribute
References getMatrixPtr().
Referenced by staticCallback_getA41().
getA42()
Py::Float MatrixPy::getA42 (void) const
getter for the A42 attribute
References getMatrixPtr().
Referenced by staticCallback_getA42().
getA43()
Py::Float MatrixPy::getA43 (void) const
getter for the A43 attribute
References getMatrixPtr().
Referenced by staticCallback_getA43().
getA44()
Py::Float MatrixPy::getA44 (void) const
getter for the A44 attribute
References getMatrixPtr().
Referenced by staticCallback_getA44().
getCustomAttributes()
PyObject * MatrixPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getMatrixPtr()
Matrix4D * MatrixPy::getMatrixPtr (void) const
getter for the object handled by this class
Referenced by analyze(), determinant(), getA(), getA11(), getA12(), getA13(), getA14(), getA21(), getA22(), getA23(), getA24(), getA31(), getA32(), getA33(), getA34(), getA41(), getA42(), getA43(), getA44(), App::FeaturePythonImp::getLinkedObject(), App::FeaturePythonImp::getSubObject(), hasScale(), inverse(), invert(), isOrthogonal(), move(), multiply(), multVec(), representation(), rotateX(), rotateY(), rotateZ(), scale(), setA(), setA11(), setA12(), setA13(), setA14(), setA21(), setA22(), setA23(), setA24(), setA31(), setA32(), setA33(), setA34(), setA41(), setA42(), setA43(), setA44(), Gui::DocumentPy::setEditingTransform(), Gui::LinkViewPy::setTransform(), submatrix(), transform(), transpose(), transposed(), and unity().
GetType()
virtual PyTypeObject* Base::MatrixPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
hasScale()
PyObject * MatrixPy::hasScale (PyObject * args)
implementer for the hasScale() method
References getMatrixPtr().
Referenced by staticCallback_hasScale().
inverse()
PyObject * MatrixPy::inverse (PyObject * args)
implementer for the inverse() method
References Base::BaseExceptionFreeCADError, determinant(), getMatrixPtr(), and MatrixPy().
Referenced by staticCallback_inverse().
invert()
PyObject * MatrixPy::invert (PyObject * args)
implementer for the invert() method
References Base::BaseExceptionFreeCADError, determinant(), getMatrixPtr(), and Base::Matrix4D::inverseGauss().
Referenced by PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart(), and staticCallback_invert().
isOrthogonal()
PyObject * MatrixPy::isOrthogonal (PyObject * args)
implementer for the isOrthogonal() method
References getMatrixPtr(), and Base::Matrix4D::transpose().
Referenced by staticCallback_isOrthogonal().
move()
PyObject * MatrixPy::move (PyObject * args)
implementer for the move() method
References getMatrixPtr(), Base::VectorPy::getVectorPtr(), Base::Matrix4D::move(), Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by draftguitools.gui_circulararray.CircularArray::Activated(), draftguitools.gui_polararray.PolarArray::Activated(), and staticCallback_move().
multiply()
PyObject * MatrixPy::multiply (PyObject * args)
implementer for the multiply() method
References Base::BaseExceptionFreeCADError, getMatrixPtr(), MatrixPy(), Type, Base::VectorPy::Type, value(), Base::VectorPy::value(), and draftgeoutils.general::vec().
Referenced by PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart(), and staticCallback_multiply().
multVec()
PyObject * MatrixPy::multVec (PyObject * args)
implementer for the multVec() method
References getMatrixPtr(), Base::Matrix4D::multVec(), Base::VectorPy::Type, value(), and draftgeoutils.general::vec().
Referenced by staticCallback_multVec().
number_absolute_handler()
PyObject * MatrixPy::number_absolute_handler (PyObject * self) static
callback for the number_absolute_handler
number_add_handler()
PyObject * MatrixPy::number_add_handler (PyObject * self, PyObject * other) static
callback for the number_add_handler
References MatrixPy(), Type, and value().
number_and_handler()
PyObject * MatrixPy::number_and_handler (PyObject * self, PyObject * other) static
callback for the number_and_handler
number_coerce_handler()
int MatrixPy::number_coerce_handler (PyObject ** self, PyObject ** other) static
callback for the number_coerce_handler
number_divide_handler()
PyObject * MatrixPy::number_divide_handler (PyObject * self, PyObject * other) static
callback for the number_divide_handler
number_divmod_handler()
PyObject * MatrixPy::number_divmod_handler (PyObject * self, PyObject * other) static
callback for the number_divmod_handler
number_float_handler()
PyObject * MatrixPy::number_float_handler (PyObject * self) static
callback for the number_float_handler
number_hex_handler()
PyObject * MatrixPy::number_hex_handler (PyObject * self) static
callback for the number_hex_handler
number_int_handler()
PyObject * MatrixPy::number_int_handler (PyObject * self) static
callback for the number_int_handler
number_invert_handler()
PyObject * MatrixPy::number_invert_handler (PyObject * self) static
callback for the number_invert_handler
number_long_handler()
PyObject * MatrixPy::number_long_handler (PyObject * self) static
callback for the number_long_handler
number_lshift_handler()
PyObject * MatrixPy::number_lshift_handler (PyObject * self, PyObject * other) static
callback for the number_lshift_handler
number_multiply_handler()
PyObject * MatrixPy::number_multiply_handler (PyObject * self, PyObject * other) static
callback for the number_multiply_handler
References MatrixPy(), Type, Base::PlacementPy::Type, Base::RotationPy::Type, Base::VectorPy::Type, and value().
number_negative_handler()
PyObject * MatrixPy::number_negative_handler (PyObject * self) static
callback for the number_negative_handler
number_nonzero_handler()
int MatrixPy::number_nonzero_handler (PyObject * self) static
callback for the number_nonzero_handler
number_oct_handler()
PyObject * MatrixPy::number_oct_handler (PyObject * self) static
callback for the number_oct_handler
number_or_handler()
PyObject * MatrixPy::number_or_handler (PyObject * self, PyObject * other) static
callback for the number_or_handler
number_positive_handler()
PyObject * MatrixPy::number_positive_handler (PyObject * self) static
callback for the number_positive_handler
number_power_handler()
PyObject * MatrixPy::number_power_handler (PyObject * self, PyObject * other, PyObject * modulo) static
callback for the number_power_handler
References Base::BaseExceptionFreeCADError, MatrixPy(), Type, and value().
number_remainder_handler()
PyObject * MatrixPy::number_remainder_handler (PyObject * self, PyObject * other) static
callback for the number_remainder_handler
number_rshift_handler()
PyObject * MatrixPy::number_rshift_handler (PyObject * self, PyObject * other) static
callback for the number_rshift_handler
number_subtract_handler()
PyObject * MatrixPy::number_subtract_handler (PyObject * self, PyObject * other) static
callback for the number_subtract_handler
References MatrixPy(), Type, and value().
number_xor_handler()
PyObject * MatrixPy::number_xor_handler (PyObject * self, PyObject * other) static
callback for the number_xor_handler
PyInit()
int MatrixPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
References Base::BaseExceptionFreeCADError, Type, and value().
PyMake()
PyObject * MatrixPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References MatrixPy().
representation()
std::string MatrixPy::representation (void) const
References getMatrixPtr().
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
richCompare()
PyObject * MatrixPy::richCompare (PyObject * v, PyObject * w, int op) static
References Type, and value().
rotateX()
PyObject * MatrixPy::rotateX (PyObject * args)
implementer for the rotateX() method
References Base::Unit::Angle, getMatrixPtr(), Base::QuantityPy::getValueAs(), Base::Quantity::Radian, Base::Matrix4D::rotX(), and Base::QuantityPy::Type.
Referenced by staticCallback_rotateX().
rotateY()
PyObject * MatrixPy::rotateY (PyObject * args)
implementer for the rotateY() method
References Base::Unit::Angle, getMatrixPtr(), Base::QuantityPy::getValueAs(), Base::Quantity::Radian, Base::Matrix4D::rotY(), and Base::QuantityPy::Type.
Referenced by staticCallback_rotateY().
rotateZ()
PyObject * MatrixPy::rotateZ (PyObject * args)
implementer for the rotateZ() method
References Base::Unit::Angle, getMatrixPtr(), Base::QuantityPy::getValueAs(), Base::Quantity::Radian, Base::Matrix4D::rotZ(), and Base::QuantityPy::Type.
Referenced by staticCallback_rotateZ().
scale()
PyObject * MatrixPy::scale (PyObject * args)
implementer for the scale() method
References getMatrixPtr(), Base::VectorPy::getVectorPtr(), Base::Matrix4D::scale(), Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by App::FunctionExpression::evaluate(), automotive_design.cartesian_transformation_operator::scl(), config_control_design.cartesian_transformation_operator::scl(), ifc2x3.ifccartesiantransformationoperator::scl(), ifc4.ifccartesiantransformationoperator::scl(), and staticCallback_scale().
setA()
void MatrixPy::setA (Py::Sequence arg)
setter for the A attribute
References Base::Matrix4D::getMatrix(), getMatrixPtr(), and Base::Matrix4D::setMatrix().
Referenced by staticCallback_setA().
setA11()
void MatrixPy::setA11 (Py::Float arg)
setter for the A11 attribute
References getMatrixPtr().
Referenced by staticCallback_setA11().
setA12()
void MatrixPy::setA12 (Py::Float arg)
setter for the A12 attribute
References getMatrixPtr().
Referenced by staticCallback_setA12().
setA13()
void MatrixPy::setA13 (Py::Float arg)
setter for the A13 attribute
References getMatrixPtr().
Referenced by staticCallback_setA13().
setA14()
void MatrixPy::setA14 (Py::Float arg)
setter for the A14 attribute
References getMatrixPtr().
Referenced by staticCallback_setA14().
setA21()
void MatrixPy::setA21 (Py::Float arg)
setter for the A21 attribute
References getMatrixPtr().
Referenced by staticCallback_setA21().
setA22()
void MatrixPy::setA22 (Py::Float arg)
setter for the A22 attribute
References getMatrixPtr().
Referenced by staticCallback_setA22().
setA23()
void MatrixPy::setA23 (Py::Float arg)
setter for the A23 attribute
References getMatrixPtr().
Referenced by staticCallback_setA23().
setA24()
void MatrixPy::setA24 (Py::Float arg)
setter for the A24 attribute
References getMatrixPtr().
Referenced by staticCallback_setA24().
setA31()
void MatrixPy::setA31 (Py::Float arg)
setter for the A31 attribute
References getMatrixPtr().
Referenced by staticCallback_setA31().
setA32()
void MatrixPy::setA32 (Py::Float arg)
setter for the A32 attribute
References getMatrixPtr().
Referenced by staticCallback_setA32().
setA33()
void MatrixPy::setA33 (Py::Float arg)
setter for the A33 attribute
References getMatrixPtr().
Referenced by staticCallback_setA33().
setA34()
void MatrixPy::setA34 (Py::Float arg)
setter for the A34 attribute
References getMatrixPtr().
Referenced by staticCallback_setA34().
setA41()
void MatrixPy::setA41 (Py::Float arg)
setter for the A41 attribute
References getMatrixPtr().
Referenced by staticCallback_setA41().
setA42()
void MatrixPy::setA42 (Py::Float arg)
setter for the A42 attribute
References getMatrixPtr().
Referenced by staticCallback_setA42().
setA43()
void MatrixPy::setA43 (Py::Float arg)
setter for the A43 attribute
References getMatrixPtr().
Referenced by staticCallback_setA43().
setA44()
void MatrixPy::setA44 (Py::Float arg)
setter for the A44 attribute
References getMatrixPtr().
Referenced by staticCallback_setA44().
setCustomAttributes()
int MatrixPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_analyze()
PyObject * MatrixPy::staticCallback_analyze (PyObject * self, PyObject * args) static
callback for the analyze() method
References analyze(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_determinant()
PyObject * MatrixPy::staticCallback_determinant (PyObject * self, PyObject * args) static
callback for the determinant() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, determinant(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_getA()
PyObject * MatrixPy::staticCallback_getA (PyObject * self, void * closure) static
getter callback for the A attribute
References Base::BaseExceptionFreeCADError, getA(), and Base::PyObjectBase::isValid().
staticCallback_getA11()
PyObject * MatrixPy::staticCallback_getA11 (PyObject * self, void * closure) static
getter callback for the A11 attribute
References Base::BaseExceptionFreeCADError, getA11(), and Base::PyObjectBase::isValid().
staticCallback_getA12()
PyObject * MatrixPy::staticCallback_getA12 (PyObject * self, void * closure) static
getter callback for the A12 attribute
References Base::BaseExceptionFreeCADError, getA12(), and Base::PyObjectBase::isValid().
staticCallback_getA13()
PyObject * MatrixPy::staticCallback_getA13 (PyObject * self, void * closure) static
getter callback for the A13 attribute
References Base::BaseExceptionFreeCADError, getA13(), and Base::PyObjectBase::isValid().
staticCallback_getA14()
PyObject * MatrixPy::staticCallback_getA14 (PyObject * self, void * closure) static
getter callback for the A14 attribute
References Base::BaseExceptionFreeCADError, getA14(), and Base::PyObjectBase::isValid().
staticCallback_getA21()
PyObject * MatrixPy::staticCallback_getA21 (PyObject * self, void * closure) static
getter callback for the A21 attribute
References Base::BaseExceptionFreeCADError, getA21(), and Base::PyObjectBase::isValid().
staticCallback_getA22()
PyObject * MatrixPy::staticCallback_getA22 (PyObject * self, void * closure) static
getter callback for the A22 attribute
References Base::BaseExceptionFreeCADError, getA22(), and Base::PyObjectBase::isValid().
staticCallback_getA23()
PyObject * MatrixPy::staticCallback_getA23 (PyObject * self, void * closure) static
getter callback for the A23 attribute
References Base::BaseExceptionFreeCADError, getA23(), and Base::PyObjectBase::isValid().
staticCallback_getA24()
PyObject * MatrixPy::staticCallback_getA24 (PyObject * self, void * closure) static
getter callback for the A24 attribute
References Base::BaseExceptionFreeCADError, getA24(), and Base::PyObjectBase::isValid().
staticCallback_getA31()
PyObject * MatrixPy::staticCallback_getA31 (PyObject * self, void * closure) static
getter callback for the A31 attribute
References Base::BaseExceptionFreeCADError, getA31(), and Base::PyObjectBase::isValid().
staticCallback_getA32()
PyObject * MatrixPy::staticCallback_getA32 (PyObject * self, void * closure) static
getter callback for the A32 attribute
References Base::BaseExceptionFreeCADError, getA32(), and Base::PyObjectBase::isValid().
staticCallback_getA33()
PyObject * MatrixPy::staticCallback_getA33 (PyObject * self, void * closure) static
getter callback for the A33 attribute
References Base::BaseExceptionFreeCADError, getA33(), and Base::PyObjectBase::isValid().
staticCallback_getA34()
PyObject * MatrixPy::staticCallback_getA34 (PyObject * self, void * closure) static
getter callback for the A34 attribute
References Base::BaseExceptionFreeCADError, getA34(), and Base::PyObjectBase::isValid().
staticCallback_getA41()
PyObject * MatrixPy::staticCallback_getA41 (PyObject * self, void * closure) static
getter callback for the A41 attribute
References Base::BaseExceptionFreeCADError, getA41(), and Base::PyObjectBase::isValid().
staticCallback_getA42()
PyObject * MatrixPy::staticCallback_getA42 (PyObject * self, void * closure) static
getter callback for the A42 attribute
References Base::BaseExceptionFreeCADError, getA42(), and Base::PyObjectBase::isValid().
staticCallback_getA43()
PyObject * MatrixPy::staticCallback_getA43 (PyObject * self, void * closure) static
getter callback for the A43 attribute
References Base::BaseExceptionFreeCADError, getA43(), and Base::PyObjectBase::isValid().
staticCallback_getA44()
PyObject * MatrixPy::staticCallback_getA44 (PyObject * self, void * closure) static
getter callback for the A44 attribute
References Base::BaseExceptionFreeCADError, getA44(), and Base::PyObjectBase::isValid().
staticCallback_hasScale()
PyObject * MatrixPy::staticCallback_hasScale (PyObject * self, PyObject * args) static
callback for the hasScale() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hasScale(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_inverse()
PyObject * MatrixPy::staticCallback_inverse (PyObject * self, PyObject * args) static
callback for the inverse() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, inverse(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_invert()
PyObject * MatrixPy::staticCallback_invert (PyObject * self, PyObject * args) static
callback for the invert() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, invert(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_isOrthogonal()
PyObject * MatrixPy::staticCallback_isOrthogonal (PyObject * self, PyObject * args) static
callback for the isOrthogonal() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), isOrthogonal(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_move()
PyObject * MatrixPy::staticCallback_move (PyObject * self, PyObject * args) static
callback for the move() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), move(), and Base::PyObjectBase::startNotify().
staticCallback_multiply()
PyObject * MatrixPy::staticCallback_multiply (PyObject * self, PyObject * args) static
callback for the multiply() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), multiply(), and Base::PyObjectBase::startNotify().
staticCallback_multVec()
PyObject * MatrixPy::staticCallback_multVec (PyObject * self, PyObject * args) static
callback for the multVec() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and multVec().
staticCallback_rotateX()
PyObject * MatrixPy::staticCallback_rotateX (PyObject * self, PyObject * args) static
callback for the rotateX() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), rotateX(), and Base::PyObjectBase::startNotify().
staticCallback_rotateY()
PyObject * MatrixPy::staticCallback_rotateY (PyObject * self, PyObject * args) static
callback for the rotateY() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), rotateY(), and Base::PyObjectBase::startNotify().
staticCallback_rotateZ()
PyObject * MatrixPy::staticCallback_rotateZ (PyObject * self, PyObject * args) static
callback for the rotateZ() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), rotateZ(), and Base::PyObjectBase::startNotify().
staticCallback_scale()
PyObject * MatrixPy::staticCallback_scale (PyObject * self, PyObject * args) static
callback for the scale() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), scale(), and Base::PyObjectBase::startNotify().
staticCallback_setA()
int MatrixPy::staticCallback_setA (PyObject * self, PyObject * value, void * closure) static
setter callback for the A attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setA().
staticCallback_setA11()
int MatrixPy::staticCallback_setA11 (PyObject * self, PyObject * value, void * closure) static
setter callback for the A11 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setA11().
staticCallback_setA12()
int MatrixPy::staticCallback_setA12 (PyObject * self, PyObject * value, void * closure) static
setter callback for the A12 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setA12().
staticCallback_setA13()
int MatrixPy::staticCallback_setA13 (PyObject * self, PyObject * value, void * closure) static
setter callback for the A13 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setA13().
staticCallback_setA14()
int MatrixPy::staticCallback_setA14 (PyObject * self, PyObject * value, void * closure) static
setter callback for the A14 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setA14().
staticCallback_setA21()
int MatrixPy::staticCallback_setA21 (PyObject * self, PyObject * value, void * closure) static
setter callback for the A21 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setA21().
staticCallback_setA22()
int MatrixPy::staticCallback_setA22 (PyObject * self, PyObject * value, void * closure) static
setter callback for the A22 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setA22().
staticCallback_setA23()
int MatrixPy::staticCallback_setA23 (PyObject * self, PyObject * value, void * closure) static
setter callback for the A23 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setA23().
staticCallback_setA24()
int MatrixPy::staticCallback_setA24 (PyObject * self, PyObject * value, void * closure) static
setter callback for the A24 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setA24().
staticCallback_setA31()
int MatrixPy::staticCallback_setA31 (PyObject * self, PyObject * value, void * closure) static
setter callback for the A31 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setA31().
staticCallback_setA32()
int MatrixPy::staticCallback_setA32 (PyObject * self, PyObject * value, void * closure) static
setter callback for the A32 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setA32().
staticCallback_setA33()
int MatrixPy::staticCallback_setA33 (PyObject * self, PyObject * value, void * closure) static
setter callback for the A33 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setA33().
staticCallback_setA34()
int MatrixPy::staticCallback_setA34 (PyObject * self, PyObject * value, void * closure) static
setter callback for the A34 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setA34().
staticCallback_setA41()
int MatrixPy::staticCallback_setA41 (PyObject * self, PyObject * value, void * closure) static
setter callback for the A41 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setA41().
staticCallback_setA42()
int MatrixPy::staticCallback_setA42 (PyObject * self, PyObject * value, void * closure) static
setter callback for the A42 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setA42().
staticCallback_setA43()
int MatrixPy::staticCallback_setA43 (PyObject * self, PyObject * value, void * closure) static
setter callback for the A43 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setA43().
staticCallback_setA44()
int MatrixPy::staticCallback_setA44 (PyObject * self, PyObject * value, void * closure) static
setter callback for the A44 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setA44().
staticCallback_submatrix()
PyObject * MatrixPy::staticCallback_submatrix (PyObject * self, PyObject * args) static
callback for the submatrix() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::startNotify(), and submatrix().
staticCallback_transform()
PyObject * MatrixPy::staticCallback_transform (PyObject * self, PyObject * args) static
callback for the transform() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::startNotify(), and transform().
staticCallback_transpose()
PyObject * MatrixPy::staticCallback_transpose (PyObject * self, PyObject * args) static
callback for the transpose() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::startNotify(), and transpose().
staticCallback_transposed()
PyObject * MatrixPy::staticCallback_transposed (PyObject * self, PyObject * args) static
callback for the transposed() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and transposed().
staticCallback_unity()
PyObject * MatrixPy::staticCallback_unity (PyObject * self, PyObject * args) static
callback for the unity() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::startNotify(), and unity().
submatrix()
PyObject * MatrixPy::submatrix (PyObject * args)
implementer for the submatrix() method
References getMatrixPtr(), and MatrixPy().
Referenced by staticCallback_submatrix().
transform()
PyObject * MatrixPy::transform (PyObject * args)
implementer for the transform() method
References getMatrixPtr(), Base::VectorPy::getVectorPtr(), Base::Matrix4D::transform(), Type, Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by importSVG.svgHandler::applyTrans(), importSVG.svgHandler::characters(), importSVG.svgHandler::endElement(), ArchSite.Compass::locate(), ArchSite.Compass::rotate(), ArchSite.Compass::scale(), and staticCallback_transform().
transpose()
PyObject * MatrixPy::transpose (PyObject * args)
implementer for the transpose() method
References getMatrixPtr(), and Base::Matrix4D::transpose().
Referenced by staticCallback_transpose().
transposed()
PyObject * MatrixPy::transposed (PyObject * args)
implementer for the transposed() method
References getMatrixPtr(), and MatrixPy().
Referenced by staticCallback_transposed().
unity()
PyObject * MatrixPy::unity (PyObject * args)
implementer for the unity() method
References getMatrixPtr(), and Base::Matrix4D::setToUnity().
Referenced by staticCallback_unity().
value()
Matrix4D Base::MatrixPy::value () const
Referenced by PathScripts.PathProperty.Property::displayString(), PathScripts.PathProperty.PropertyQuantity::displayString(), PathScripts.PathSetupSheetOpPrototype.Property::displayString(), PathScripts.PathSetupSheetOpPrototype.PropertyQuantity::displayString(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), PathScripts.PathProperty.Property::getValue(), PathScripts.PathSetupSheetOpPrototype.Property::getValue(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), multiply(), multVec(), number_add_handler(), number_multiply_handler(), number_power_handler(), number_subtract_handler(), PyInit(), richCompare(), App::PropertyMatrix::setPyObject(), App::PropertyPlacement::setPyObject(), Robot::Robot6AxisPy::setTcp(), PathScripts.PathProperty.Property::setValue(), and PathScripts.PathSetupSheetOpPrototype.Property::setValue().
Member Data Documentation
GetterSetter
PyGetSetDef MatrixPy::GetterSetter static
Attribute structure of MatrixPy.
Methods
PyMethodDef MatrixPy::Methods static
Methods structure of MatrixPy.
Number
PyNumberMethods MatrixPy::Number static
Type
PyTypeObject MatrixPy::Type static
Type structure of MatrixPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), App::FunctionExpression::evaluate(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), App::FeaturePythonImp::getLinkedObject(), App::DocumentObjectPy::getLinkedObject(), App::FeaturePythonImp::getSubObject(), App::DocumentObjectPy::getSubObject(), Gui::ViewProviderLink::initDraggingPlacement(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), multiply(), number_add_handler(), number_multiply_handler(), Base::PlacementPy::number_multiply_handler(), Base::RotationPy::number_multiply_handler(), number_power_handler(), number_subtract_handler(), PyInit(), Base::PlacementPy::PyInit(), Base::RotationPy::PyInit(), richCompare(), draftobjects.layer.Layer::set_properties(), Base::RotationPy::setCustomAttributes(), Gui::DocumentPy::setEditingTransform(), Data::ComplexGeoDataPy::setMatrix(), Gui::DocumentPy::setPos(), ArchReference.ArchReference::setProperties(), App::PropertyMatrix::setPyObject(), App::PropertyPlacement::setPyObject(), Robot::Robot6AxisPy::setTcp(), Gui::LinkViewPy::setTransform(), Gui::ViewProviderPy::setTransformation(), Gui::View3DInventorViewerPy::setupEditingRoot(), transform(), Mesh::MeshPy::transform(), Part::GeometryPy::transform(), Sketcher::ExternalGeometryFacadePy::transform(), Sketcher::GeometryFacadePy::transform(), Base::BoundBoxPy::transformed(), Part::TopoShapePy::transformed(), Part::TopoShapePy::transformGeometry(), and Part::TopoShapePy::transformShape().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Base/MatrixPy.h
Sources/FreeCAD/src/Base/MatrixPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Base/MatrixPy.cpp