FreeCAD: MTextEdit Class Reference
MTextEdit Class Reference
#include <mtextedit.h>
Public Member Functions
void dropImage (const QImage &image, const QString &format)
MTextEdit (QWidget *parent)
Protected Member Functions
bool canInsertFromMimeData (const QMimeData *source) const
QMimeData * createMimeDataFromSelection () const
void insertFromMimeData (const QMimeData *source)
Constructor & Destructor Documentation
MTextEdit()
MTextEdit::MTextEdit (QWidget * parent)
Member Function Documentation
canInsertFromMimeData()
bool MTextEdit::canInsertFromMimeData (const QMimeData * source) const protected
createMimeDataFromSelection()
QMimeData * MTextEdit::createMimeDataFromSelection () const protected
dropImage()
void MTextEdit::dropImage (const QImage & image, const QString & format)
Referenced by insertFromMimeData(), and MRichTextEdit::insertImage().
insertFromMimeData()
void MTextEdit::insertFromMimeData (const QMimeData * source) protected
References dropImage().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/mtextedit.h
FreeCAD/src/Mod/TechDraw/Gui/mtextedit.cpp