FreeCAD: I32 Struct Reference
I32 Struct Reference
#include <I32.h>
Public Member Functions
I32 ()
I32 (Context &cont)
operator int32_t () const
void read (Context &cont)
Constructor & Destructor Documentation
I32() [1/2]
I32::I32 ()
I32() [2/2]
I32::I32 (Context & cont)
References read().
Member Function Documentation
operator int32_t()
I32::operator int32_t () const
read()
void I32::read (Context & cont)
References Context::Strm.
Referenced by I32(), Segment_Header::read(), TOC_Entry::read(), Element_Header::read(), gzip_utf8.GzipFile::readline(), and gzip_utf8.GzipFile::seek().
The documentation for this struct was generated from the following file:
FreeCAD/src/Mod/JtReader/App/JrJt/I32.h