FreeCAD: Gui::SplitView3DInventor Class Reference
Gui::SplitView3DInventor Class Reference
The SplitView3DInventor class allows to create a window with two or more Inventor views.
#include <SplitView3DInventor.h>
Public Member Functions
SplitView3DInventor (int views, Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
~SplitView3DInventor ()
Public Member Functions inherited from Gui::AbstractSplitView
AbstractSplitView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
virtual bool containsViewProvider (const ViewProvider *) const
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
virtual void deleteSelf ()
delete itself
virtual const char * getName (void) const
returns the name of the view (important for messages)
PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
int getSize ()
View3DInventorViewer * getViewer (unsigned int) const
virtual void OnChange (ParameterGrp::SubjectType &rCaller, ParameterGrp::MessageType Reason)
Observer message from the ParameterGrp.
virtual bool onHasMsg (const char *pMsg) const
Message handler test.
virtual bool onMsg (const char *pMsg, const char **ppReturn)
Message handler.
virtual void onUpdate (void)
get called when the document is updated
void setOverrideCursor (const QCursor &)
void setPyObject (PyObject *)
~AbstractSplitView ()
Public Member Functions inherited from Gui::MDIView
virtual bool canClose (void)
overwrite when checking on close state
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
View constructor Attach the view to the given document.
virtual void onRelabel (Gui::Document *pDoc)
get called when the document is updated
virtual void viewAll ()
~MDIView ()
View destructor Detach the view from the document, if attached.
virtual void print ()
Print content of view.
virtual void printPdf ()
Print to PDF file.
virtual void printPreview ()
Show a preview dialog.
QSize minimumSizeHint () const
virtual void setCurrentViewMode (ViewMode mode)
If b is set to FullScreen the MDI view is displayed in full screen mode, if b is set to TopLevel then it is displayed as an own top-level window, otherwise (Normal) as tabbed window.
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=0, std::string *subname=0) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=0)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=0) const
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=0)
View constructor Attach the view to the given document.
virtual ~BaseView ()
View destructor Detach the view from the document, if attached!
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose (void)
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive (void) const
indicates if the view is in passive mode
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual Type getTypeId (void) const
bool isDerivedFrom (const Type type) const
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Public Types inherited from Gui::MDIView
enum ViewMode { Child, TopLevel, FullScreen }
MDI view mode enum.
Public Slots inherited from Gui::MDIView
virtual void print (QPrinter *printer)
virtual void restoreOverrideCursor ()
Signals inherited from Gui::MDIView
void message (const QString &, int)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Protected Slots inherited from Gui::MDIView
virtual void windowStateChanged (MDIView *)
This method gets called from the main window this view is attached to whenever the window state of the active view changes.
Protected Member Functions inherited from Gui::AbstractSplitView
void setupSettings ()
Protected Member Functions inherited from Gui::MDIView
void closeEvent (QCloseEvent *e)
void changeEvent (QEvent *e)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::AbstractSplitView
ParameterGrp::handle hGrp
handle to the viewer parameter group
Protected Attributes inherited from Gui::MDIView
PyObject * pythonObject
Protected Attributes inherited from Gui::BaseView
bool bIsDetached
bool bIsPassive
Detailed Description
The SplitView3DInventor class allows to create a window with two or more Inventor views.
Author
Werner Mayer
Constructor & Destructor Documentation
SplitView3DInventor()
SplitView3DInventor::SplitView3DInventor (int views, Gui::Document * pcDocument, QWidget * parent, Qt::WindowFlags wflags = Qt::WindowFlags())
References Base::Subject< _MessageType >::Attach(), App::GetApplication(), Gui::View3DInventorViewer::getNumSamples(), and App::Application::GetParameterGroupByPath().
~SplitView3DInventor()
SplitView3DInventor::~SplitView3DInventor ()
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SplitView3DInventor.h
Sources/FreeCAD/src/Gui/SplitView3DInventor.cpp