FreeCAD: Gui::TaskView::Ui_TaskSelectLinkProperty Class Reference
Gui::TaskView::Ui_TaskSelectLinkProperty Class Reference
#include <ui_TaskSelectLinkProperty.h>
Public Member Functions
void retranslateUi (QWidget *Gui__TaskView__TaskSelectLinkProperty)
void setupUi (QWidget *Gui__TaskView__TaskSelectLinkProperty)
Public Attributes
QToolButton * Add
QToolButton * Help
QHBoxLayout * horizontalLayout
QSpacerItem * horizontalSpacer
QToolButton * Invert
QListWidget * listWidget
QToolButton * Remove
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void Gui::TaskView::Ui_TaskSelectLinkProperty::retranslateUi (QWidget * Gui__TaskView__TaskSelectLinkProperty)
References Add, Help, Invert, Remove, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), Gui::TaskView::TaskSelectLinkProperty::changeEvent(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::TaskView::Ui_TaskSelectLinkProperty::setupUi (QWidget * Gui__TaskView__TaskSelectLinkProperty)
References Add, Help, horizontalLayout, horizontalSpacer, Invert, listWidget, Remove, retranslateUi(), and verticalLayout.
Referenced by Gui::TaskView::TaskSelectLinkProperty::TaskSelectLinkProperty().
Member Data Documentation
Add
QToolButton* Gui::TaskView::Ui_TaskSelectLinkProperty::Add
Referenced by retranslateUi(), setupUi(), and Gui::TaskView::TaskSelectLinkProperty::TaskSelectLinkProperty().
QToolButton* Gui::TaskView::Ui_TaskSelectLinkProperty::Help
Referenced by retranslateUi(), setupUi(), and Gui::TaskView::TaskSelectLinkProperty::TaskSelectLinkProperty().
horizontalLayout
QHBoxLayout* Gui::TaskView::Ui_TaskSelectLinkProperty::horizontalLayout
Referenced by setupUi().
horizontalSpacer
QSpacerItem* Gui::TaskView::Ui_TaskSelectLinkProperty::horizontalSpacer
Referenced by setupUi().
Invert
QToolButton* Gui::TaskView::Ui_TaskSelectLinkProperty::Invert
Referenced by retranslateUi(), setupUi(), and Gui::TaskView::TaskSelectLinkProperty::TaskSelectLinkProperty().
listWidget
QListWidget* Gui::TaskView::Ui_TaskSelectLinkProperty::listWidget
Referenced by setupUi().
Remove
QToolButton* Gui::TaskView::Ui_TaskSelectLinkProperty::Remove
Referenced by retranslateUi(), setupUi(), and Gui::TaskView::TaskSelectLinkProperty::TaskSelectLinkProperty().
verticalLayout
QVBoxLayout* Gui::TaskView::Ui_TaskSelectLinkProperty::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_TaskSelectLinkProperty.h