FreeCAD: TechDrawGui::QGIDrawingTemplate Class Reference
TechDrawGui::QGIDrawingTemplate Class Reference
#include <QGIDrawingTemplate.h>
Public Types
enum { Type = QGraphicsItem::UserType + 151 }
Public Types inherited from TechDrawGui::QGITemplate
enum { Type = QGraphicsItem::UserType + 150 }
Public Member Functions
void clearContents ()
void draw ()
QGIDrawingTemplate (QGraphicsScene *)
int type () const
virtual void updateView (bool update=false)
~QGIDrawingTemplate ()
Public Member Functions inherited from TechDrawGui::QGITemplate
void clearContents ()
TechDraw::DrawTemplate * getTemplate ()
std::vector< TemplateTextField * > getTextFields (void)
qreal getY ()
QGITemplate (QGraphicsScene *)
void setTemplate (TechDraw::DrawTemplate *obj)
int type () const
~QGITemplate ()
Protected Member Functions
TechDraw::DrawParametricTemplate * getParametricTemplate ()
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value)
Protected Attributes
QGraphicsPathItem * pathItem
Protected Attributes inherited from TechDrawGui::QGITemplate
TechDraw::DrawTemplate * pageTemplate
std::vector< TemplateTextField * > textFields
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGIDrawingTemplate()
QGIDrawingTemplate::QGIDrawingTemplate (QGraphicsScene * scene)
References pathItem.
~QGIDrawingTemplate()
QGIDrawingTemplate::~QGIDrawingTemplate ()
References pathItem.
Member Function Documentation
clearContents()
void QGIDrawingTemplate::clearContents ()
draw()
void QGIDrawingTemplate::draw (void) virtual
Implements TechDrawGui::QGITemplate.
References TechDraw::GENERIC, TechDraw::DrawParametricTemplate::getGeometry(), getParametricTemplate(), pathItem, and TechDraw::Generic::points.
Referenced by updateView().
getParametricTemplate()
TechDraw::DrawParametricTemplate * QGIDrawingTemplate::getParametricTemplate () protected
References Base::Persistence::getClassTypeId(), Base::BaseClass::isDerivedFrom(), and TechDrawGui::QGITemplate::pageTemplate.
Referenced by draw().
itemChange()
QVariant QGIDrawingTemplate::itemChange (GraphicsItemChange change, const QVariant & value) protected virtual
Reimplemented from TechDrawGui::QGITemplate.
type()
int TechDrawGui::QGIDrawingTemplate::type (void) const
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
updateView()
void QGIDrawingTemplate::updateView (bool update = false) virtual
Reimplemented from TechDrawGui::QGITemplate.
References draw().
Member Data Documentation
pathItem
QGraphicsPathItem* TechDrawGui::QGIDrawingTemplate::pathItem protected
Referenced by draw(), QGIDrawingTemplate(), and ~QGIDrawingTemplate().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGIDrawingTemplate.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGIDrawingTemplate.cpp