FreeCAD: Base::PersistencePy Class Reference
Base::PersistencePy Class Reference
The python export class for Persistence.
#include <PersistencePy.h>
Public Types
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
callbacks and implementers for the python object attributes
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Persistence.
Member Typedef Documentation
PointerType
typedef Persistence* Base::PersistencePy::PointerType
Constructor & Destructor Documentation
~PersistencePy()
PersistencePy::~PersistencePy () protected
PersistencePy()
PersistencePy::PersistencePy (Persistence * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
dumpContent()
PyObject * PersistencePy::dumpContent (PyObject * args, PyObject * kwd)
implementer for the dumpContent() method
References Base::Persistence::dumpToStream(), and getPersistencePtr().
Referenced by staticCallback_dumpContent().
getContent()
Py::String PersistencePy::getContent (void) const
getter for the Content attribute
References getPersistencePtr(), Base::StringWriter::getString(), Base::Persistence::Save(), and Base::Writer::setForceXML().
Referenced by staticCallback_getContent().
getCustomAttributes()
PyObject * PersistencePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getMemSize()
Py::Int PersistencePy::getMemSize (void) const
getter for the MemSize attribute
References getPersistencePtr().
Referenced by staticCallback_getMemSize().
getPersistencePtr()
Persistence * PersistencePy::getPersistencePtr (void) const
getter for the object handled by this class
Referenced by dumpContent(), getContent(), getMemSize(), and restoreContent().
GetType()
virtual PyTypeObject* Base::PersistencePy::GetType (void) virtual
Reimplemented from Base::BaseClassPy.
Reimplemented in TechDraw::DrawWeldSymbolPy, TechDraw::DrawViewSymbolPy, TechDraw::DrawViewPy, TechDraw::DrawViewPartPy, TechDraw::DrawViewDimExtentPy, TechDraw::DrawViewDimensionPy, TechDraw::DrawViewCollectionPy, TechDraw::DrawViewClipPy, TechDraw::DrawViewAnnotationPy, TechDraw::DrawTileWeldPy, TechDraw::DrawTilePy, TechDraw::DrawTemplatePy, TechDraw::DrawSVGTemplatePy, TechDraw::DrawRichAnnoPy, TechDraw::DrawProjGroupPy, TechDraw::DrawProjGroupItemPy, TechDraw::DrawParametricTemplatePy, TechDraw::DrawPagePy, TechDraw::DrawLeaderLinePy, TechDraw::DrawHatchPy, TechDraw::DrawGeomHatchPy, Spreadsheet::SheetPy, Spreadsheet::PropertySheetPy, Spreadsheet::PropertyRowHeightsPy, Spreadsheet::PropertyColumnWidthsPy, Sketcher::SketchPy, Sketcher::SketchObjectSFPy, Sketcher::SketchObjectPy, Sketcher::ConstraintPy, Robot::WaypointPy, Robot::TrajectoryPy, Robot::RobotObjectPy, Robot::Robot6AxisPy, Points::PointsPy, Path::TooltablePy, Path::ToolPy, Path::PathPy, Path::FeaturePathCompoundPy, Path::FeatureAreaPy, Path::CommandPy, PartDesignGui::ViewProviderPy, PartDesign::FeaturePy, PartDesign::BodyPy, Part::TrimmedCurvePy, Part::ToroidPy, Part::TopoShapeWirePy, Part::TopoShapeVertexPy, Part::TopoShapeSolidPy, Part::TopoShapeShellPy, Part::TopoShapePy, Part::TopoShapeFacePy, Part::TopoShapeEdgePy, Part::TopoShapeCompSolidPy, Part::TopoShapeCompoundPy, Part::SurfaceOfRevolutionPy, Part::SurfaceOfExtrusionPy, Part::SpherePy, Part::RectangularTrimmedSurfacePy, Part::PointPy, Part::PlateSurfacePy, Part::PlanePy, Part::PartFeaturePy, Part::Part2DObjectPy, Part::ParabolaPy, Part::OffsetSurfacePy, Part::OffsetCurvePy, Part::LineSegmentPy, Part::LinePy, Part::HyperbolaPy, Part::GeometrySurfacePy, Part::GeometryPy, Part::GeometryCurvePy, Part::EllipsePy, Part::CylinderPy, Part::ConicPy, Part::ConePy, Part::CirclePy, Part::BSplineSurfacePy, Part::BSplineCurvePy, Part::BoundedCurvePy, Part::BodyBasePy, Part::BezierSurfacePy, Part::BezierCurvePy, Part::ArcPy, Part::ArcOfParabolaPy, Part::ArcOfHyperbolaPy, Part::ArcOfEllipsePy, Part::ArcOfConicPy, Part::ArcOfCirclePy, MeshGui::ViewProviderMeshPy, Mesh::MeshPy, Mesh::MeshFeaturePy, FemGui::ViewProviderFemMeshPy, Fem::FemPostPipelinePy, Fem::FemMeshPy, Gui::ViewProviderPy, Gui::ViewProviderLinkPy, Gui::ViewProviderDocumentObjectPy, Gui::DocumentPy, App::PropertyContainerPy, App::PartPy, App::GeoFeaturePy, App::ExtensionContainerPy, App::DocumentPy, App::DocumentObjectPy, App::DocumentObjectGroupPy, and Data::ComplexGeoDataPy.
PyInit()
int PersistencePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::BaseClassPy.
Reimplemented in TechDraw::DrawWeldSymbolPy, TechDraw::DrawViewSymbolPy, TechDraw::DrawViewPy, TechDraw::DrawViewPartPy, TechDraw::DrawViewDimExtentPy, TechDraw::DrawViewDimensionPy, TechDraw::DrawViewCollectionPy, TechDraw::DrawViewClipPy, TechDraw::DrawViewAnnotationPy, TechDraw::DrawTileWeldPy, TechDraw::DrawTilePy, TechDraw::DrawTemplatePy, TechDraw::DrawSVGTemplatePy, TechDraw::DrawRichAnnoPy, TechDraw::DrawProjGroupPy, TechDraw::DrawProjGroupItemPy, TechDraw::DrawParametricTemplatePy, TechDraw::DrawPagePy, TechDraw::DrawLeaderLinePy, TechDraw::DrawHatchPy, TechDraw::DrawGeomHatchPy, Spreadsheet::SheetPy, Spreadsheet::PropertySheetPy, Spreadsheet::PropertyRowHeightsPy, Spreadsheet::PropertyColumnWidthsPy, Sketcher::SketchPy, Sketcher::SketchObjectSFPy, Sketcher::SketchObjectPy, Sketcher::ConstraintPy, Robot::WaypointPy, Robot::TrajectoryPy, Robot::RobotObjectPy, Robot::Robot6AxisPy, Points::PointsPy, Path::TooltablePy, Path::ToolPy, Path::PathPy, Path::FeaturePathCompoundPy, Path::FeatureAreaPy, Path::CommandPy, PartDesignGui::ViewProviderPy, PartDesign::FeaturePy, PartDesign::BodyPy, Part::TrimmedCurvePy, Part::ToroidPy, Part::TopoShapeWirePy, Part::TopoShapeVertexPy, Part::TopoShapeSolidPy, Part::TopoShapeShellPy, Part::TopoShapePy, Part::TopoShapeFacePy, Part::TopoShapeEdgePy, Part::TopoShapeCompSolidPy, Part::TopoShapeCompoundPy, Part::SurfaceOfRevolutionPy, Part::SurfaceOfExtrusionPy, Part::SpherePy, Part::RectangularTrimmedSurfacePy, Part::PointPy, Part::PlateSurfacePy, Part::PlanePy, Part::PartFeaturePy, Part::Part2DObjectPy, Part::ParabolaPy, Part::OffsetSurfacePy, Part::OffsetCurvePy, Part::LineSegmentPy, Part::LinePy, Part::HyperbolaPy, Part::GeometrySurfacePy, Part::GeometryPy, Part::GeometryCurvePy, Part::EllipsePy, Part::CylinderPy, Part::ConicPy, Part::ConePy, Part::CirclePy, Part::BSplineSurfacePy, Part::BSplineCurvePy, Part::BoundedCurvePy, Part::BodyBasePy, Part::BezierSurfacePy, Part::BezierCurvePy, Part::ArcPy, Part::ArcOfParabolaPy, Part::ArcOfHyperbolaPy, Part::ArcOfEllipsePy, Part::ArcOfConicPy, Part::ArcOfCirclePy, MeshGui::ViewProviderMeshPy, Mesh::MeshPy, Mesh::MeshFeaturePy, FemGui::ViewProviderFemMeshPy, Fem::FemPostPipelinePy, Fem::FemMeshPy, Gui::ViewProviderPy, Gui::ViewProviderLinkPy, Gui::ViewProviderDocumentObjectPy, Gui::DocumentPy, App::PropertyContainerPy, App::PartPy, App::GeoFeaturePy, App::ExtensionContainerPy, App::DocumentPy, App::DocumentObjectPy, App::DocumentObjectGroupPy, and Data::ComplexGeoDataPy.
PyMake()
PyObject * PersistencePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string PersistencePy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
restoreContent()
PyObject * PersistencePy::restoreContent (PyObject * args)
implementer for the restoreContent() method
References getPersistencePtr(), and Base::Persistence::restoreFromStream().
Referenced by staticCallback_restoreContent().
setCustomAttributes()
int PersistencePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_dumpContent()
PyObject * PersistencePy::staticCallback_dumpContent (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the dumpContent() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, dumpContent(), and Base::PyObjectBase::isValid().
staticCallback_getContent()
PyObject * PersistencePy::staticCallback_getContent (PyObject * self, void * closure) static
getter callback for the Content attribute
References Base::BaseExceptionFreeCADError, getContent(), and Base::PyObjectBase::isValid().
staticCallback_getMemSize()
PyObject * PersistencePy::staticCallback_getMemSize (PyObject * self, void * closure) static
getter callback for the MemSize attribute
References Base::BaseExceptionFreeCADError, getMemSize(), and Base::PyObjectBase::isValid().
staticCallback_restoreContent()
PyObject * PersistencePy::staticCallback_restoreContent (PyObject * self, PyObject * args) static
callback for the restoreContent() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), restoreContent(), and Base::PyObjectBase::startNotify().
staticCallback_setContent()
int PersistencePy::staticCallback_setContent (PyObject * self, PyObject * value, void * closure) static
setter callback for the Content attribute
References Base::PyObjectBase::isValid().
staticCallback_setMemSize()
int PersistencePy::staticCallback_setMemSize (PyObject * self, PyObject * value, void * closure) static
setter callback for the MemSize attribute
References Base::PyObjectBase::isValid().
Member Data Documentation
GetterSetter
PyGetSetDef PersistencePy::GetterSetter static
Initial value:
= {
    {"Content",
        (getter) staticCallback_getContent,
        (setter) staticCallback_setContent,
        "Content of the object in XML representation",
        NULL
    },
    {"MemSize",
        (getter) staticCallback_getMemSize,
        (setter) staticCallback_setMemSize,
        "Memory size of the object in byte",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of PersistencePy.
Methods
PyMethodDef PersistencePy::Methods static
Initial value:
= {
    {"dumpContent",
        reinterpret_cast<PyCFunction>(reinterpret_cast<void (*) (void)>( staticCallback_dumpContent )),
        METH_VARARGS|METH_KEYWORDS,
        "Dumps the content of the object, both the XML representation as well as the additional datafiles  \nrequired, into a byte representation. It will be returned as byte array.\ndumpContent() -- returns a byte array with full content\ndumpContent(Compression=1-9) -- Sets the data compression from 0 (no) to 9 (max)\n                "
    },
    {"restoreContent",
        reinterpret_cast<PyCFunction>( staticCallback_restoreContent ),
        METH_VARARGS,
        "Restore the content of the object from a byte representation as stored by \"dumpContent\".\nIt could be restored from any python object implementing the buffer protocol.\nrestoreContent(buffer) -- restores from the given byte array\n                "
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of PersistencePy.
Type
PyTypeObject PersistencePy::Type static
Type structure of PersistencePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Base/PersistencePy.h
Sources/FreeCAD/src/Base/PersistencePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Base/PersistencePy.cpp