FreeCAD: Part::PropertyPartShape Class Reference
Part::PropertyPartShape Class Reference
The part shape property class.
#include <PropertyTopoShape.h>
Public Member Functions
PropertyPartShape ()
~PropertyPartShape ()
Getter/setter
void setValue (const TopoShape &)
set the part shape
void setValue (const TopoDS_Shape &)
set the part shape
const TopoDS_Shape & getValue (void) const
get the part shape
const TopoShape & getShape () const
const Data::ComplexGeoData * getComplexData () const
Modification
void setTransform (const Base::Matrix4D &rclTrf)
Set the placement of the geometry.
Base::Matrix4D getTransform () const
Get the placement of the geometry.
void transformGeometry (const Base::Matrix4D &rclMat)
Transform the real shape data.
Getting basic geometric entities
Base::BoundBox3d getBoundingBox () const
Returns the bounding box around the underlying mesh kernel.
Python interface
PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
void setPyObject (PyObject *value)
Public Member Functions inherited from App::PropertyComplexGeoData
PropertyComplexGeoData ()
virtual ~PropertyComplexGeoData ()
Public Member Functions inherited from App::PropertyGeometry
PropertyGeometry ()
virtual ~PropertyGeometry ()
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual Property * Copy (void) const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
int64_t getID () const
Return a unique ID for the property.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const char * getName (void) const
Get the name of this property in the belonging container With hasName() it can be checked beforehand if a valid name is set.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
bool hasName () const
Check if the property has a name set.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Save/restore
void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
void SaveDocFile (Base::Writer &writer) const
This method is used to save large amounts of data to a binary file.
void RestoreDocFile (Base::Reader &reader)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
App::Property * Copy (void) const
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const App::Property &from)
Paste the value from the property (mainly for Undo/Redo and transactions)
unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , Busy = 15 ,
CopyOnChange = 16 , UserEdit = 17 , PropStaticBegin = 21 , PropDynamic = 21 ,
PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 , PropTransient = 25 ,
PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 , User1 = 28 ,
User2 = 29 , User3 = 30 , User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Check if the passed name is valid.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Detailed Description
The part shape property class.
Author
Werner Mayer
Constructor & Destructor Documentation
PropertyPartShape()
PropertyPartShape::PropertyPartShape ()
Referenced by Copy().
~PropertyPartShape()
PropertyPartShape::~PropertyPartShape ()
Member Function Documentation
Copy()
App::Property * PropertyPartShape::Copy (void) const virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References PropertyPartShape().
getBoundingBox()
Base::BoundBox3d PropertyPartShape::getBoundingBox () const virtual
Returns the bounding box around the underlying mesh kernel.
Implements App::PropertyComplexGeoData.
Referenced by PartGui::SectionCut::SectionCut(), and PartGui::ViewProviderMirror::setEdit().
getComplexData()
const Data::ComplexGeoData * PropertyPartShape::getComplexData () const virtual
Implements App::PropertyComplexGeoData.
getMemSize()
unsigned int PropertyPartShape::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
See also
Base::Persistence
Reimplemented from App::Property.
getPaths()
void PropertyPartShape::getPaths (std::vector< App::ObjectIdentifier > & paths) const virtual
Get valid paths for this property; used by auto completer.
Reimplemented from App::Property.
References App::Property::getContainer(), App::Property::getName(), and App::ObjectIdentifier::Component::SimpleComponent().
getPyObject()
PyObject * PropertyPartShape::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
References Base::PyObjectBase::setConst().
getShape()
const TopoShape & PropertyPartShape::getShape () const
Referenced by PartGui::DlgProjectionOnSurface::EdgeSelection::allow(), PartGui::DlgProjectionOnSurface::FaceSelection::allow(), PartDesign::ShapeBinder::buildShapeFromReferences(), Drawing::FeatureProjection::execute(), Inspection::Feature::execute(), PartDesign::Loft::execute(), PartDesign::Pipe::execute(), PartDesign::Transformed::execute(), Path::FeatureArea::execute(), Path::FeatureShape::execute(), Surface::Cut::execute(), Surface::Filling::execute(), Surface::Sewing::execute(), TechDraw::FeatureProjection::execute(), PartDesign::Body::execute(), PartDesign::Boolean::execute(), Surface::Extend::execute(), Surface::Sections::execute(), PartDesign::FeatureAddSub::getAddSubShape(), PartDesign::DressUp::getAddSubShape(), PartDesign::ProfileBased::getAxis(), Fem::Constraint::getBasePoint(), PartDesign::Feature::getBaseTopoShape(), Fem::Constraint::getCylinder(), Fem::Constraint::getDirection(), TechDraw::ShapeExtractor::getLocation3dFromFeat(), Fem::Constraint::getPoints(), PartDesign::ProfileBased::getProfileWires(), Part::Datum::getShape(), TechDraw::ShapeExtractor::getShapes2d(), TechDraw::ShapeExtractor::getShapesFromObject(), Part::Feature::getSubObject(), PartDesign::ProfileBased::getSupportFace(), PartDesign::MultiTransform::getTransformations(), PartDesign::LinearPattern::getTransformations(), PartDesign::Mirrored::getTransformations(), PartDesign::PolarPattern::getTransformations(), PartDesign::ProfileBased::getUpToFaceFromLinkSub(), PartDesign::ProfileBased::getVerifiedFace(), Surface::GeomFillSurface::getWire(), PartDesignGui::TaskFeaturePick::makeCopy(), Fem::Constraint::onChanged(), Fem::ConstraintBearing::onChanged(), Part::Feature::onChanged(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), FemGui::TaskFemConstraintGear::onSelectionChanged(), SurfaceGui::FillingPanel::open(), Sketcher::SketchObject::rebuildExternalGeometry(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), and Sketcher::SketchObject::validateExternalLinks().
getTransform()
Base::Matrix4D PropertyPartShape::getTransform (void) const virtual
Get the placement of the geometry.
Implements App::PropertyGeometry.
getValue()
const TopoDS_Shape & PropertyPartShape::getValue (void) const
get the part shape
Referenced by PartGui::CrossSections::apply(), PartDesign::ShapeBinder::buildShapeFromReferences(), Fem::FemMeshShapeNetgenObject::execute(), Fem::FemMeshShapeObject::execute(), Inspection::Feature::execute(), PartDesign::FeatureBase::execute(), PartDesign::Loft::execute(), PartDesign::Pipe::execute(), PartDesign::Boolean::execute(), PartDesign::Feature::getBaseShape(), Sketcher::SketchAnalysis::getOpenVertices(), PartDesign::ProfileBased::getProfileWires(), PartDesignGui::TaskFeaturePick::makeCopy(), Part::Feature::onChanged(), Import::ExportOCAF::reallocateFreeShape(), PartDesign::ProfileBased::remapSupportShape(), Sketcher::SketchObject::restoreFinished(), Import::ExportOCAF::saveShape(), PartDesign::SubShapeBinder::update(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderMultiFuse::updateData(), PartGui::ViewProviderMultiCommon::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderFillet::updateData(), and PartGui::ViewProviderChamfer::updateData().
Paste()
void PropertyPartShape::Paste (const App::Property & from) virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Restore()
void PropertyPartShape::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References Base::XMLReader::addFile(), Base::XMLReader::getAttribute(), and Base::XMLReader::readElement().
RestoreDocFile()
void PropertyPartShape::RestoreDocFile (Base::Reader &) virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Base::Persistence.
References App::GetApplication(), ParameterGrp::GetBool(), Base::Reader::getFileName(), App::Application::GetParameterGroupByPath(), Base::FileInfo::hasExtension(), and setValue().
Save()
void PropertyPartShape::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References Base::Writer::addFile(), Base::Writer::getMode(), Base::Writer::ind(), Base::Writer::isForceXML(), and Base::Writer::Stream().
SaveDocFile()
void PropertyPartShape::SaveDocFile (Base::Writer &) const virtual
This method is used to save large amounts of data to a binary file.
Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) << "\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
void PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Base::Persistence.
References App::GetApplication(), ParameterGrp::GetBool(), Base::Writer::getMode(), App::Application::GetParameterGroupByPath(), and Base::Writer::Stream().
setPyObject()
void PropertyPartShape::setPyObject (PyObject * value) virtual
Reimplemented from Base::BaseClass.
References setValue().
setTransform()
void PropertyPartShape::setTransform (const Base::Matrix4D & rclTrf) virtual
Set the placement of the geometry.
Implements App::PropertyGeometry.
Referenced by Part::Feature::onChanged().
setValue() [1/2]
void PropertyPartShape::setValue (const TopoDS_Shape & sh)
set the part shape
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
setValue() [2/2]
void PropertyPartShape::setValue (const TopoShape & sh)
set the part shape
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Referenced by ReverseEngineeringGui::Segmentation::accept(), DraftUtils::DraftDxfRead::AddGraphics(), Import::ImpExpDxfRead::AddGraphics(), DraftUtils::DraftDxfRead::AddObject(), Import::ImpExpDxfRead::AddObject(), Surface::GeomFillSurface::createFace(), PartDesign::Pad::execute(), PartDesign::Pocket::execute(), PartDesign::FeaturePrimitive::execute(), Drawing::FeatureProjection::execute(), Part::Chamfer::execute(), Part::Compound::execute(), Part::Fillet::execute(), Part::FeatureGeometrySet::execute(), Part::Mirroring::execute(), Part::Boolean::execute(), Part::Box::execute(), Part::Circle::execute(), Part::MultiCommon::execute(), Part::CurveNet::execute(), Part::MultiFuse::execute(), Part::ImportBrep::execute(), Part::ImportIges::execute(), Part::ImportStep::execute(), Part::RuledSurface::execute(), Part::Loft::execute(), Part::Sweep::execute(), Part::Thickness::execute(), Part::Refine::execute(), Part::Reverse::execute(), Part::Vertex::execute(), Part::Line::execute(), Part::Plane::execute(), Part::Sphere::execute(), Part::Ellipsoid::execute(), Part::Cylinder::execute(), Part::Prism::execute(), Part::RegularPolygon::execute(), Part::Cone::execute(), Part::Torus::execute(), Part::Helix::execute(), Part::Spiral::execute(), Part::Wedge::execute(), Part::Ellipse::execute(), PartDesign::FeatureBase::execute(), PartDesign::Fillet::execute(), PartDesign::Groove::execute(), PartDesign::Helix::execute(), PartDesign::Hole::execute(), PartDesign::Loft::execute(), PartDesign::Pipe::execute(), PartDesign::Revolution::execute(), PartDesign::Thickness::execute(), PartDesign::Transformed::execute(), Path::FeatureArea::execute(), Path::FeatureAreaView::execute(), Surface::Cut::execute(), Surface::Filling::execute(), Surface::Sewing::execute(), TechDraw::FeatureProjection::execute(), Part::Extrusion::execute(), Part::Face::execute(), Part::Offset::execute(), Part::Offset2D::execute(), Part::Revolution::execute(), PartDesign::Body::execute(), PartDesign::Boolean::execute(), PartDesign::Chamfer::execute(), PartDesign::ShapeBinder::execute(), Sketcher::SketchObject::execute(), Surface::Extend::execute(), Surface::Sections::execute(), PartDesign::DressUp::getAddSubShape(), Part::ImportIgesParts(), Part::ImportStepParts(), Import::ImportOCAF2::loadShapes(), PartDesignGui::TaskFeaturePick::makeCopy(), PartDesign::DressUp::onChanged(), RestoreDocFile(), Sketcher::SketchObject::restoreFinished(), PartDesign::SubShapeBinder::setLinks(), setPyObject(), Path::FeatureArea::setWorkPlane(), and Path::Area::showShape().
transformGeometry()
void PropertyPartShape::transformGeometry (const Base::Matrix4D & rclMat) virtual
Transform the real shape data.
Implements App::PropertyComplexGeoData.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/App/PropertyTopoShape.h
FreeCAD/src/Mod/Part/App/PropertyTopoShape.cpp