FreeCAD: PartGui::Ui_DlgPartImportStep Class Reference
PartGui::Ui_DlgPartImportStep Class Reference
#include <ui_DlgPartImportStep.h>
Public Member Functions
void retranslateUi (QDialog *PartGui__DlgPartImportStep)
void setupUi (QDialog *PartGui__DlgPartImportStep)
Public Attributes
QDialogButtonBox * buttonBox
QLineEdit * FileName
QGridLayout * gridLayout
QGridLayout * gridLayout_2
QGroupBox * GroupBox5
QPushButton * SearchFile
Member Function Documentation
retranslateUi()
void PartGui::Ui_DlgPartImportStep::retranslateUi (QDialog * PartGui__DlgPartImportStep)
References FileName, GroupBox5, SearchFile, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void PartGui::Ui_DlgPartImportStep::setupUi (QDialog * PartGui__DlgPartImportStep)
References buttonBox, FileName, gridLayout, gridLayout_2, GroupBox5, retranslateUi(), and SearchFile.
Member Data Documentation
buttonBox
QDialogButtonBox* PartGui::Ui_DlgPartImportStep::buttonBox
Referenced by PathScripts.PathGetPoint.TaskPanel::getPoint(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::modifyStandardButtons(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::pageDirtyChanged(), PathScripts.PathGetPoint.TaskPanel::pointFinish(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setClean(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setDirty(), and setupUi().
FileName
QLineEdit* PartGui::Ui_DlgPartImportStep::FileName
Referenced by retranslateUi(), and setupUi().
gridLayout
QGridLayout* PartGui::Ui_DlgPartImportStep::gridLayout
Referenced by setupUi().
gridLayout_2
QGridLayout* PartGui::Ui_DlgPartImportStep::gridLayout_2
Referenced by setupUi().
GroupBox5
QGroupBox* PartGui::Ui_DlgPartImportStep::GroupBox5
Referenced by retranslateUi(), and setupUi().
SearchFile
QPushButton* PartGui::Ui_DlgPartImportStep::SearchFile
Referenced by retranslateUi(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Part/Gui/ui_DlgPartImportStep.h