FreeCAD: TechDraw::Circle Class Reference
TechDraw::Circle Class Reference
#include <Geometry.h>
Public Member Functions
Circle (Base::Vector3d center, double radius)
Circle (const TopoDS_Edge &e)
Circle (void)
virtual void Restore (Base::XMLReader &r) override
virtual void Save (Base::Writer &w) const override
virtual std::string toString (void) const override
~Circle ()=default
Public Member Functions inherited from TechDraw::BaseGeom
BaseGeom ()
bool closed (void)
BaseGeom * copy ()
std::string dump ()
std::vector< Base::Vector3d > findEndPoints ()
std::string getCosmeticTag (void)
Base::Vector3d getEndPoint ()
Base::Vector3d getMidPoint ()
std::vector< Base::Vector3d > getQuads ()
Base::Vector3d getStartPoint ()
boost::uuids::uuid getTag () const
virtual std::string getTagAsString (void) const
double minDist (Base::Vector3d p)
Base::Vector3d nearPoint (Base::Vector3d p)
Base::Vector3d nearPoint (const BaseGeom *p)
find point on me nearest to p
void setCosmeticTag (std::string t)
void source (int s)
int source (void)
void sourceIndex (int si)
int sourceIndex (void)
virtual ~BaseGeom ()=default
Public Attributes
Base::Vector3d center
double radius
Public Attributes inherited from TechDraw::BaseGeom
edgeClass classOfEdge
bool cosmetic
ExtractionType extractType
GeomType geomType
bool hlrVisible
TopoDS_Edge occEdge
int ref3D
bool reversed
Additional Inherited Members
Static Public Member Functions inherited from TechDraw::BaseGeom
static BaseGeom * baseFactory (TopoDS_Edge edge)
Convert 1 OCC edge into 1 BaseGeom (static factory method)
static bool validateEdge (TopoDS_Edge edge)
Protected Member Functions inherited from TechDraw::BaseGeom
void createNewTag ()
Protected Attributes inherited from TechDraw::BaseGeom
std::string cosmeticTag
int m_source
int m_sourceIndex
boost::uuids::uuid tag
Constructor & Destructor Documentation
Circle() [1/3]
Circle::Circle (void)
References center, TechDraw::CIRCLE, TechDraw::BaseGeom::geomType, and radius.
Circle() [2/3]
Circle::Circle (const TopoDS_Edge & e)
References center, TechDraw::CIRCLE, TechDraw::BaseGeom::geomType, TechDraw::BaseGeom::occEdge, and radius.
Circle() [3/3]
Circle::Circle (Base::Vector3d center, double radius)
References center, TechDraw::CIRCLE, TechDraw::BaseGeom::geomType, TechDraw::BaseGeom::occEdge, and radius.
~Circle()
TechDraw::Circle::~Circle () default
Member Function Documentation
Restore()
void Circle::Restore (Base::XMLReader & r) override virtual
Reimplemented from TechDraw::BaseGeom.
Reimplemented in TechDraw::AOC.
References center, Base::XMLReader::getAttributeAsFloat(), radius, Base::XMLReader::readElement(), TechDraw::BaseGeom::Restore(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by TechDraw::CosmeticEdge::Restore(), TechDraw::CenterLine::Restore(), and TechDraw::AOC::Restore().
Save()
void Circle::Save (Base::Writer & w) const override virtual
Reimplemented from TechDraw::BaseGeom.
Reimplemented in TechDraw::AOC.
References center, Base::Writer::ind(), radius, TechDraw::BaseGeom::Save(), Base::Writer::Stream(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by TechDraw::CosmeticEdge::Save(), TechDraw::CenterLine::Save(), and TechDraw::AOC::Save().
toString()
std::string Circle::toString (void) const override virtual
Reimplemented from TechDraw::BaseGeom.
Reimplemented in TechDraw::AOC.
References center, radius, TechDraw::BaseGeom::toString(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by TechDraw::AOC::toString().
Member Data Documentation
center
Base::Vector3d TechDraw::Circle::center
Referenced by TechDraw::AOC::AOC(), Circle(), TechDraw::CosmeticEdge::CosmeticEdge(), PathScripts.PathDressupAxisMap.ObjectDressup::execute(), TechDrawGui::QGIViewPart::geomToPainterPath(), PathScripts.PathDressupAxisMap.ObjectDressup::onChanged(), TechDraw::CosmeticEdge::Restore(), Restore(), Save(), and toString().
radius
double TechDraw::Circle::radius
Referenced by TechDraw::AOC::AOC(), Circle(), TechDraw::CosmeticEdge::CosmeticEdge(), TechDrawGui::QGIViewPart::geomToPainterPath(), TechDraw::CosmeticEdge::Restore(), Restore(), Save(), TechDraw::CosmeticEdgePy::setCenter(), and toString().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/App/Geometry.h
Sources/FreeCAD/src/Mod/TechDraw/App/Geometry.cpp