FreeCAD: PathScripts.PathMillFace.ObjectFace Class Reference
PathScripts.PathMillFace.ObjectFace Class Reference
Public Member Functions
def areaOpOnChanged (self, obj, prop)
def areaOpSetDefaultValues (self, obj, job)
def areaOpShapes (self, obj)
def getAllIncludedFaces (self, base, env, faceZ)
def initPocketOp (self, obj)
def isPocket (self, b, f, w)
def pocketInvertExtraOffset (self)
Public Member Functions inherited from PathScripts.PathPocketBase.ObjectPocket
def areaOpAreaParams (self, obj, isHole)
def areaOpFeatures (self, obj)
def areaOpPathParams (self, obj, isHole)
def areaOpRetractTool (self, obj)
def areaOpUseProjection (self, obj)
def initAreaOp (self, obj)
def pocketOpFeatures (self, obj)
Public Member Functions inherited from PathScripts.PathAreaOp.ObjectOp
def applyInverseAngle (self, obj, clnBase, clnStock, axis, angle)
def applyRotationalAnalysis (self, obj, base, angle, axis, subCount)
def areaOpOnDocumentRestored (self, obj)
def areaOpShapeForDepths (self, obj, job)
def cloneBaseAndStock (self, obj, base, angle, axis, subCount)
def faceRotationAnalysis (self, obj, norm, surf)
def getFaceNormAndSurf (self, face)
def guiMessage (self, title, msg, show=False)
def initOperation (self, obj)
def isFaceUp (self, base, face)
def opDetermineRotationRadii (self, obj)
def opExecute (self, obj, getsim=False)
def opFeatures (self, obj)
def opOnChanged (self, obj, prop)
def opOnDocumentRestored (self, obj)
def opSetDefaultValues (self, obj, job)
def setupAdditionalProperties (self, obj)
def sortTuplesByIndex (self, TupleList, tagIdx)
def useTempJobClones (self, cloneName)
def visualAxis (self)
def warnDisabledAxis (self, obj, axis, sub='')
Public Member Functions inherited from PathScripts.PathOp.ObjectOp
def addBase (self, obj, base, sub)
def addBaseProperty (self, obj)
def addOpValues (self, obj, values)
def applyExpression (self, obj, prop, expr)
def execute (self, obj)
def getCycleTimeEstimate (self, obj)
def getJob (self, obj)
def isToolSupported (self, obj, tool)
def onChanged (self, obj, prop)
def onDocumentRestored (self, obj)
def opExecute (self, obj)
def opRejectAddBase (self, obj, base, sub)
def opUpdateDepths (self, obj)
def sanitizeBase (self, obj)
def setDefaultValues (self, obj)
def setEditorModes (self, obj, features)
def updateDepths (self, obj, ignoreErrors=False)
Public Attributes
removalshapes
Public Attributes inherited from PathScripts.PathAreaOp.ObjectOp
axialFeed
axialRapid
cloneNames
depthparams
endVector
guiMsgs
initWithRotation
leadIn
rotateFlag
rotStartDepth
stockBB
tempObjectNames
Public Attributes inherited from PathScripts.PathOp.ObjectOp
addNewProps
commandlist
horizFeed
horizRapid
job
model
radius
stock
tool
vertFeed
vertRapid
Detailed Description
Proxy object for Mill Facing operation.
Member Function Documentation
areaOpOnChanged()
def PathScripts.PathMillFace.ObjectFace.areaOpOnChanged (self, obj, prop)
areaOpOnChanged(obj, prop) ... facing specific depths calculation.
Reimplemented from PathScripts.PathAreaOp.ObjectOp.
Referenced by PathScripts.PathAreaOp.ObjectOp.opOnChanged().
areaOpSetDefaultValues()
def PathScripts.PathMillFace.ObjectFace.areaOpSetDefaultValues (self, obj, job)
areaOpSetDefaultValues(obj, job) ... initialize mill facing properties
Reimplemented from PathScripts.PathAreaOp.ObjectOp.
Referenced by PathScripts.PathProfile.ObjectProfile.areaOpOnDocumentRestored().
areaOpShapes()
def PathScripts.PathMillFace.ObjectFace.areaOpShapes (self, obj)
areaOpShapes(obj) ... return top face
Reimplemented from PathScripts.PathAreaOp.ObjectOp.
References PathScripts.PathAreaOp.ObjectOp.depthparams.
getAllIncludedFaces()
def PathScripts.PathMillFace.ObjectFace.getAllIncludedFaces (self, base, env, faceZ)
initPocketOp()
def PathScripts.PathMillFace.ObjectFace.initPocketOp (self, obj)
initPocketOp(obj) ... create facing specific properties
Reimplemented from PathScripts.PathPocketBase.ObjectPocket.
Referenced by PathScripts.PathPocketShape.ObjectPocket.areaOpOnDocumentRestored(), PathScripts.PathPocketBase.ObjectPocket.initAreaOp(), and PathScripts.PathPocket.ObjectPocket.opOnDocumentRestored().
isPocket()
def PathScripts.PathMillFace.ObjectFace.isPocket (self, b, f, w)
pocketInvertExtraOffset()
def PathScripts.PathMillFace.ObjectFace.pocketInvertExtraOffset (self)
pocketInvertExtraOffset() ... return True if ExtraOffset's direction is inward.
Can safely be overwritten by subclass.
Reimplemented from PathScripts.PathPocketBase.ObjectPocket.
Referenced by PathScripts.PathPocketBase.ObjectPocket.areaOpAreaParams().
Member Data Documentation
removalshapes
PathScripts.PathMillFace.ObjectFace.removalshapes
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Path/PathScripts/PathMillFace.py