FreeCAD: MeshCore::MeshKernel Class Reference
MeshCore::MeshKernel Class Reference
The MeshKernel class is the basic class that holds the data points, the edges and the facets describing a mesh object.
#include <MeshKernel.h>
Public Member Functions
MeshKernel (const MeshKernel &rclMesh)
Construction.
MeshKernel (void)
Construction.
~MeshKernel (void)
Destruction.
I/O methods
void Write (std::ostream &rclOut) const
Binary streaming of data.
void Read (std::istream &rclIn)
Querying
unsigned long CountFacets (void) const
Returns the number of facets.
unsigned long CountEdges (void) const
Returns the number of edge.
unsigned long CountPoints (void) const
unsigned int GetMemSize (void) const
Returns the number of required memory in bytes.
const Base::BoundBox3f & GetBoundBox (void) const
Determines the bounding box.
void RecalcBoundBox (void)
Forces a recalculation of the bounding box.
MeshPoint GetPoint (unsigned long ulIndex) const
Returns the point at the given index.
std::vector< Base::Vector3f > CalcVertexNormals () const
Returns an array of the vertex normals of the mesh.
std::vector< Base::Vector3f > GetFacetNormals (const std::vector< unsigned long > &) const
MeshGeomFacet GetFacet (unsigned long ulIndex) const
Returns the facet at the given index.
MeshGeomFacet GetFacet (const MeshFacet &rclFacet) const
void GetFacetPoints (unsigned long ulFaIndex, unsigned long &rclP0, unsigned long &rclP1, unsigned long &rclP2) const
Returns the point indices of the given facet index.
std::vector< unsigned long > GetFacetPoints (const std::vector< unsigned long > &) const
Returns the point indices of the given facet indices.
std::vector< unsigned long > GetPointFacets (const std::vector< unsigned long > &) const
Returns the facet indices that share the given point indices.
void GetFacetNeighbours (unsigned long ulIndex, unsigned long &rulNIdx0, unsigned long &rulNIdx1, unsigned long &rulNIdx2) const
Returns the indices of the neighbour facets of the given facet index.
std::vector< unsigned long > HasFacets (const MeshPointIterator &rclIter) const
Determines all facets that are associated to this point.
bool IsValid (void) const
Returns true if the data structure is valid.
const MeshPointArray & GetPoints (void) const
Returns the array of all data points.
MeshPointArray GetPoints (const std::vector< unsigned long > &) const
Returns an array of points to the given indices.
MeshPointModifier ModifyPoints ()
Returns a modifier for the point array.
const MeshFacetArray & GetFacets (void) const
Returns the array of all facets.
MeshFacetArray GetFacets (const std::vector< unsigned long > &) const
Returns an array of facets to the given indices.
MeshFacetModifier ModifyFacets ()
Returns a modifier for the facet array.
void GetEdges (std::vector< MeshGeomEdge > &) const
Returns the array of all edges.
Evaluation
float GetSurface () const
Calculates the surface area of the mesh object.
float GetSurface (const std::vector< unsigned long > &aSegment) const
Calculates the surface area of the segment defined by aSegment.
float GetVolume () const
Calculates the volume of the mesh object.
bool HasOpenEdges () const
Checks whether the mesh has open edges.
bool HasNonManifolds () const
Checks whether the mesh has non.manifold edges.
bool HasSelfIntersections () const
Checks whether the mesh intersects itself.
Facet visitors
The MeshKernel class provides different methods to visit "topologic connected" facets to a given start facet.
Two facets are regarded as "topologic connected" if they share a common edge or a common point. All methods expect a MeshFacetVisitor as argument that can decide to continue or to stop. If there is no topologic neighbour facet any more being not marked as "VISIT" the algorithm stops anyway.
See also
MeshFacetVisitor, MeshOrientationVisitor, MeshSearchNeighbourFacetsVisitor and MeshTopFacetVisitor.
unsigned long VisitNeighbourFacets (MeshFacetVisitor &rclFVisitor, unsigned long ulStartFacet) const
This method visits all neighbour facets, i.e facets that share a common edge starting from the facet associated to index ulStartFacet.
unsigned long VisitNeighbourFacetsOverCorners (MeshFacetVisitor &rclFVisitor, unsigned long ulStartFacet) const
Does basically the same as the method above unless the facets that share just a common point are regared as neighbours.
Point visitors
The MeshKernel class provides a method to visit neighbour points to a given start point.
Two points are regarded as neighbours if they share an edge. The method expects a MeshPointVisitor as argument that can decide to continue or to stop. If there is no topologic neighbour point any more being not marked as "VISIT" the algorithm stops anyway.
unsigned long VisitNeighbourPoints (MeshPointVisitor &rclPVisitor, unsigned long ulStartPoint) const
This method visits all neighbour points starting from the point associated to index ulStartPoint.
Iterators
The iterator methods are provided for convenience.
They return an iterator object that points to the first element in the appropriate list.
MeshKernel mesh = ...
// iterate over all facets
for (MeshFacetIterator it = mesh.FacetIterator(); it.More(); it.Next())
...
An iterator can also be used in the following way
MeshKernel mesh = ...
// iterate over all facets
MeshFacetIterator it(mesh);
for (it.Init(); it.More(); it.Next())
...
MeshFacetIterator FacetIterator () const
Returns an iterator object to go over all facets.
MeshPointIterator PointIterator () const
Returns an iterator object to go over all points.
Modification
class MeshPointIterator
class MeshFacetIterator
class MeshFastFacetIterator
class MeshAlgorithm
class MeshTopoAlgorithm
class MeshFixDuplicatePoints
class MeshBuilder
class MeshTrimming
MeshKernel & operator+= (const MeshGeomFacet &rclSFacet)
Adds a single facet to the data structure.
void AddFacet (const MeshGeomFacet &rclSFacet)
Adds a single facet to the data structure.
MeshKernel & operator+= (const std::vector< MeshGeomFacet > &rclFAry)
Adds an array of facets to the data structure.
void AddFacets (const std::vector< MeshGeomFacet > &rclFAry)
Adds an array of facets to the data structure.
unsigned long AddFacets (const std::vector< MeshFacet > &rclFAry, bool checkManifolds)
Adds an array of topologic facets to the data structure without inserting new points.
unsigned long AddFacets (const std::vector< MeshFacet > &rclFAry, const std::vector< Base::Vector3f > &rclPAry, bool checkManifolds)
Adds new points and facets to the data structure.
void Merge (const MeshKernel &rKernel)
Adds all facets and referenced points to the underlying mesh structure.
void Merge (const MeshPointArray &rPoints, const MeshFacetArray &rFaces)
This method is provided for convenience that directly accepts the point and facet arrays.
bool DeleteFacet (const MeshFacetIterator &rclIter)
Deletes the facet the iterator points to.
bool DeleteFacet (unsigned long ulInd)
Does basically the same as the method above unless that the index of the facet is given.
void DeleteFacets (const std::vector< unsigned long > &raulFacets)
Removes several facets from the data structure.
bool DeletePoint (const MeshPointIterator &rclIter)
Deletes the point the iterator points to.
bool DeletePoint (unsigned long ulInd)
Does basically the same as the method above unless that the index of the facet is given.
void DeletePoints (const std::vector< unsigned long > &raulPoints)
Removes several points from the data structure.
void RemoveInvalids ()
Removes all as INVALID marked points and facets from the structure.
void RebuildNeighbours (void)
Rebuilds the neighbour indices for all facets.
void Cleanup ()
Removes unreferenced points or facets with invalid indices from the mesh.
void Clear (void)
Clears the whole data structure.
MeshKernel & operator= (const std::vector< MeshGeomFacet > &rclFAry)
Replaces the current data structure with the structure built up of the array of triangles given in rclFAry.
MeshKernel & operator= (const MeshKernel &rclMesh)
Assignment operator.
void Assign (const MeshPointArray &rPoints, const MeshFacetArray &rFaces, bool checkNeighbourHood=false)
This allows to assign the mesh structure directly.
void Adopt (MeshPointArray &rPoints, MeshFacetArray &rFaces, bool checkNeighbourHood=false)
This method does basically the same as Assign() unless that it swaps the content of both arrays.
void Swap (MeshKernel &mesh)
Swaps the content of this kernel and mesh.
void operator*= (const Base::Matrix4D &rclMat)
Transform the data structure with the given transformation matrix.
void Transform (const Base::Matrix4D &rclMat)
Transform the data structure with the given transformation matrix.
void MovePoint (unsigned long ulPtIndex, const Base::Vector3f &rclTrans)
Moves the point at the given index along the vector rclTrans.
void SetPoint (unsigned long ulPtIndex, const Base::Vector3f &rPoint)
Sets the point at the given index to the new rPoint.
void SetPoint (unsigned long ulPtIndex, float x, float y, float z)
Sets the point at the given index to the new rPoint.
void Smooth (int iterations, float d_max)
Smoothes the mesh kernel.
void CutFacets (const MeshFacetGrid &rclGrid, const Base::ViewProjMethod *pclP, const Base::Polygon2d &rclPoly, bool bCutInner, std::vector< MeshGeomFacet > &raclFacets)
CheckFacets() is invoked within this method and all found facets get deleted from the mesh structure.
void CutFacets (const MeshFacetGrid &rclGrid, const Base::ViewProjMethod *pclP, const Base::Polygon2d &rclPoly, bool bCutInner, std::vector< unsigned long > &raclCutted)
Does basically the same as method above unless that the facets to be deleted are returned with their index number in the facet array of the mesh structure.
void RebuildNeighbours (unsigned long)
Rebuilds the neighbour indices for subset of all facets from index index on.
void ErasePoint (unsigned long ulIndex, unsigned long ulFacetIndex, bool bOnlySetInvalid=false)
Checks if this point is associated to no other facet and deletes if so.
void AdjustNormal (MeshFacet &rclFacet, const Base::Vector3f &rclNormal)
Adjusts the facet's orierntation to the given normal direction.
Base::Vector3f GetNormal (const MeshFacet &rclFacet) const
Calculates the normal to the given facet.
Base::Vector3f GetGravityPoint (const MeshFacet &rclFacet) const
Calculates the gravity point to the given facet.
Detailed Description
The MeshKernel class is the basic class that holds the data points, the edges and the facets describing a mesh object.
The bounding box is calculated during the buildup of the data structure and gets only re-caclulated after insertion of new facets but not after removal of facets.
This class provides only some rudimental querying methods.
Constructor & Destructor Documentation
MeshKernel() [1/2]
MeshKernel::MeshKernel (void)
Construction.
MeshKernel() [2/2]
MeshKernel::MeshKernel (const MeshKernel & rclMesh)
Construction.
~MeshKernel()
MeshCore::MeshKernel::~MeshKernel (void)
Destruction.
Member Function Documentation
AddFacet()
void MeshKernel::AddFacet (const MeshGeomFacet & rclSFacet)
Adds a single facet to the data structure.
This method is very slow and should be called occasionally only. This does the same as the += operator above.
References AdjustNormal(), and MeshCore::MeshGeomFacet::GetNormal().
Referenced by operator+=().
AddFacets() [1/3]
unsigned long MeshKernel::AddFacets (const std::vector< MeshFacet > & rclFAry, bool checkManifolds)
Adds an array of topologic facets to the data structure without inserting new points.
Facets which would create non-manifolds are not inserted. The client programmer must make sure that the referenced point indices are correct and that no geometric overlaps can be created. The method returns the total number of facets. This method might be useful to close gaps or fill up holes in a mesh.
Note
This method is quite expensive and should be rarely used.
References CountFacets(), CountPoints(), MeshCore::MeshPoint::INVALID, MeshCore::MeshFacet::INVALID, and RebuildNeighbours().
AddFacets() [2/3]
unsigned long MeshKernel::AddFacets (const std::vector< MeshFacet > & rclFAry, const std::vector< Base::Vector3f > & rclPAry, bool checkManifolds)
Adds new points and facets to the data structure.
The client programmer must make sure that all new points are referenced by the new facets. All points in rclPAry get copied at the end of the internal point array to keep their order. The point indices of the facets must be related to the internal point array, not the passed array rclPAry.
Example: We have a mesh with p points and f facets where we want append new points and facets to. Let's assume that the first facet of rclFAry references the 1st, 2nd and 3rd points of rclPAry then its indices must be p, p+1, p+2 – not 0,1,2. This is due to the fact that facets of rclFAry can also reference point indices of the internal point array.
Note
This method is quite expensive and should be rarely used.
References AddFacets().
AddFacets() [3/3]
void MeshKernel::AddFacets (const std::vector< MeshGeomFacet > & rclFAry)
Adds an array of facets to the data structure.
This method keeps temporarily set properties and flags. This does the same as the += operator above.
References Merge().
Referenced by AddFacets(), MeshPart::CurveProjectorWithToolMesh::Do(), MeshPart::MeshAlgos::LoftOnCurve(), and operator+=().
AdjustNormal()
void MeshCore::MeshKernel::AdjustNormal (MeshFacet & rclFacet, const Base::Vector3f & rclNormal) protected
Adjusts the facet's orierntation to the given normal direction.
References MeshCore::MeshFacet::FlipNormal().
Referenced by AddFacet().
Adopt()
void MeshKernel::Adopt (MeshPointArray & rPoints, MeshFacetArray & rFaces, bool checkNeighbourHood = false)
This method does basically the same as Assign() unless that it swaps the content of both arrays.
These arrays may be empty after assigning to the kernel. This method is a convenient way to build up the mesh structure from outside and assign to a mesh kernel without copying the data. Especially for huge meshes this saves memory and increases speed.
References RebuildNeighbours(), and RecalcBoundBox().
Referenced by MeshPart::Mesher::createMesh(), MeshGui::SoFCMeshNode::readInstance(), Mesh::PropertyMeshKernel::Restore(), and MeshCore::MeshSimplify::simplify().
Assign()
void MeshKernel::Assign (const MeshPointArray & rPoints, const MeshFacetArray & rFaces, bool checkNeighbourHood = false)
This allows to assign the mesh structure directly.
The caller must make sure that the point indices are correctly set but the neighbourhood gets checked and corrected if checkNeighbourHood is true.
References RebuildNeighbours(), and RecalcBoundBox().
CalcVertexNormals()
std::vector< Base::Vector3f > MeshKernel::CalcVertexNormals () const
Returns an array of the vertex normals of the mesh.
A vertex normal gets calculated by summarizing the normals of the associated facets.
References CountFacets(), CountPoints(), GetFacetPoints(), and GetPoint().
Cleanup()
void MeshKernel::Cleanup ()
Removes unreferenced points or facets with invalid indices from the mesh.
References MeshCore::MeshCleanup::RemoveInvalids().
Clear()
void MeshKernel::Clear (void)
Clears the whole data structure.
CountEdges()
unsigned long MeshKernel::CountEdges (void) const
Returns the number of edge.
Referenced by MeshGui::DlgEvaluateMeshImp::showInformation(), and MeshGui::PropertyMeshKernelItem::value().
CountFacets()
unsigned long MeshCore::MeshKernel::CountFacets (void) const
Returns the number of facets.
Referenced by AddFacets(), CalcVertexNormals(), MeshCore::MeshTrimming::CheckFacets(), Mesh::MeshPy::collapseEdge(), MeshCore::MeshCurvature::ComputePerVertex(), MeshGui::ViewProviderMeshBuilder::createMesh(), MeshGui::ViewProviderMesh::getVisibleFacets(), MeshCore::MeshCurvature::MeshCurvature(), MeshGui::ViewProviderMesh::segmentMesh(), MeshGui::DlgEvaluateMeshImp::showInformation(), Mesh::MeshPy::splitEdge(), Mesh::MeshPy::splitFacet(), MeshGui::ViewProviderMesh::splitMesh(), Mesh::MeshPy::swapEdge(), MeshCore::MeshFacetGrid::Validate(), MeshGui::PropertyMeshKernelItem::value(), and Write().
CountPoints()
unsigned long MeshCore::MeshKernel::CountPoints (void) const
Referenced by AddFacets(), CalcVertexNormals(), MeshCore::MeshCurvature::ComputePerVertex(), MeshGui::ViewProviderMeshBuilder::createMesh(), MeshGui::ViewProviderMesh::fillHole(), MeshGui::DlgEvaluateMeshImp::showInformation(), MeshCore::PlaneFitSmoothing::Smooth(), MeshCore::PlaneFitSmoothing::SmoothPoints(), MeshCore::MeshPointGrid::Validate(), MeshGui::PropertyMeshKernelItem::value(), and Write().
CutFacets() [1/2]
void MeshKernel::CutFacets (const MeshFacetGrid & rclGrid, const Base::ViewProjMethod * pclP, const Base::Polygon2d & rclPoly, bool bCutInner, std::vector< MeshGeomFacet > & raclFacets)
CheckFacets() is invoked within this method and all found facets get deleted from the mesh structure.
The facets to be deleted are returned with their geometric representation.
See also
CheckFacets().
References DeleteFacets(), GetFacet(), and MeshAlgorithm.
CutFacets() [2/2]
void MeshKernel::CutFacets (const MeshFacetGrid & rclGrid, const Base::ViewProjMethod * pclP, const Base::Polygon2d & rclPoly, bool bCutInner, std::vector< unsigned long > & raclCutted)
Does basically the same as method above unless that the facets to be deleted are returned with their index number in the facet array of the mesh structure.
References DeleteFacets(), and MeshAlgorithm.
DeleteFacet() [1/2]
bool MeshKernel::DeleteFacet (const MeshFacetIterator & rclIter)
Deletes the facet the iterator points to.
The deletion of a facet requires the following steps:
Mark the neighbour index of all neighbour facets to the deleted facet as invalid
Adjust the indices of the neighbour facets of all facets.
If there is no neighbour facet check if the points can be deleted. True is returned if the facet could be deleted.
Note
This method is very slow and should only be called occasionally.
After deletion of the facet rclIter becomes invalid and must not be used before setting to a new position.
References ErasePoint(), and MeshCore::MeshFacetIterator::Position().
Referenced by DeleteFacet(), and DeletePoint().
DeleteFacet() [2/2]
bool MeshKernel::DeleteFacet (unsigned long ulInd)
Does basically the same as the method above unless that the index of the facet is given.
References DeleteFacet(), and MeshCore::MeshFacetIterator::Set().
DeleteFacets()
void MeshKernel::DeleteFacets (const std::vector< unsigned long > & raulFacets)
Removes several facets from the data structure.
Note
This method overwrites the free usable property of each mesh point.
This method also removes points from the structure that are no longer referenced by the facets.
This method is very slow and should only be called occasionally.
References RecalcBoundBox(), RemoveInvalids(), and MeshCore::MeshFacet::SetInvalid().
Referenced by CutFacets().
DeletePoint() [1/2]
bool MeshKernel::DeletePoint (const MeshPointIterator & rclIter)
Deletes the point the iterator points to.
The deletion of a point requires the following step:
Find all associated facets to this point.
Delete these facets. True is returned if the point could be deleted.
Note
This method is very slow and should only be called occasionally.
After deletion of the point rclIter becomes invalid and must not be used before setting to a new position.
References MeshCore::MeshPointIterator::Begin(), DeleteFacet(), and MeshCore::MeshFacetIterator::End().
Referenced by DeletePoint().
DeletePoint() [2/2]
bool MeshKernel::DeletePoint (unsigned long ulInd)
Does basically the same as the method above unless that the index of the facet is given.
References DeletePoint(), and MeshCore::MeshPointIterator::Set().
DeletePoints()
void MeshKernel::DeletePoints (const std::vector< unsigned long > & raulPoints)
Removes several points from the data structure.
Note
This method overwrites the free usable property of each mesh point.
References MeshCore::MeshPoint::IsValid(), RecalcBoundBox(), RemoveInvalids(), and MeshCore::MeshPoint::SetInvalid().
ErasePoint()
void MeshKernel::ErasePoint (unsigned long ulIndex, unsigned long ulFacetIndex, bool bOnlySetInvalid = false) protected
Checks if this point is associated to no other facet and deletes if so.
The point indices of the facets get adjusted. ulIndex is the index of the point to be deleted. ulFacetIndex is the index of the quasi deleted facet and is ignored. If bOnlySetInvalid is true the point doesn't get deleted but marked as invalid.
Referenced by DeleteFacet().
FacetIterator()
MeshFacetIterator MeshKernel::FacetIterator () const
Returns an iterator object to go over all facets.
References MeshCore::MeshFacetIterator::Begin().
GetBoundBox()
const Base::BoundBox3f& MeshCore::MeshKernel::GetBoundBox (void) const
Determines the bounding box.
Referenced by MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), and Inspection::InspectNominalFastMesh::InspectNominalFastMesh().
GetEdges()
void MeshKernel::GetEdges (std::vector< MeshGeomEdge > & edges) const
Returns the array of all edges.
Notice: The Edgelist will be temporary generated. Changes on the mesh structure does not affect the Edgelist
GetFacet() [1/2]
MeshGeomFacet MeshCore::MeshKernel::GetFacet (const MeshFacet & rclFacet) const
References MeshCore::MeshGeomFacet::CalcNormal().
GetFacet() [2/2]
MeshGeomFacet MeshCore::MeshKernel::GetFacet (unsigned long ulIndex) const
Returns the facet at the given index.
This method is rather slow and should be called occasionally only. For fast access the MeshFacetIterator interface should be used.
References MeshCore::MeshGeomFacet::CalcNormal().
Referenced by MeshCore::MeshDistancePlanarSegment::AddFacet(), MeshCore::MeshDistanceGenericSurfaceFitSegment::AddFacet(), MeshCore::MeshPlaneVisitor::AllowVisit(), MeshCore::MeshTrimByPlane::CheckFacets(), MeshCore::MeshTrimming::CheckFacets(), MeshCore::FacetCurvature::Compute(), CutFacets(), Mesh::SegmentByMesh::execute(), MeshGui::ViewProviderMesh::faceInfo(), Mesh::FacetPy::getArea(), Mesh::FacetPy::getAspectRatio(), Mesh::FacetPy::getAspectRatio2(), Mesh::FacetPy::getCircumCircle(), Mesh::FacetPy::getInCircle(), Mesh::FacetPy::getRoundness(), MeshGui::ViewProviderMesh::getVisibleFacets(), MeshCore::MeshDistancePlanarSegment::Initialize(), MeshCore::MeshDistanceGenericSurfaceFitSegment::Initialize(), Mesh::FacetPy::isDeformed(), Mesh::FacetPy::isDegenerated(), MeshCore::MeshPlaneVisitor::MeshPlaneVisitor(), MeshCore::MeshProjection::projectLineOnMesh(), MeshCore::MeshDistancePlanarSegment::TestFacet(), MeshCore::MeshDistanceGenericSurfaceFitSegment::TestFacet(), MeshCore::MeshDistanceGenericSurfaceFitSegment::TestInitialFacet(), MeshCore::MeshTrimByPlane::TrimFacets(), and MeshCore::MeshPlaneVisitor::Visit().
GetFacetNeighbours()
void MeshCore::MeshKernel::GetFacetNeighbours (unsigned long ulIndex, unsigned long & rulNIdx0, unsigned long & rulNIdx1, unsigned long & rulNIdx2) const
Returns the indices of the neighbour facets of the given facet index.
GetFacetNormals()
std::vector< Base::Vector3f > MeshKernel::GetFacetNormals (const std::vector< unsigned long > & facets) const
References Base::Vector3< _Precision >::Normalize().
Referenced by ReverseEngineeringGui::SegmentationManual::Private::findGeometry().
GetFacetPoints() [1/2]
std::vector< unsigned long > MeshKernel::GetFacetPoints (const std::vector< unsigned long > & facets) const
Returns the point indices of the given facet indices.
References GetFacetPoints().
GetFacetPoints() [2/2]
void MeshCore::MeshKernel::GetFacetPoints (unsigned long ulFaIndex, unsigned long & rclP0, unsigned long & rclP1, unsigned long & rclP2) const
Returns the point indices of the given facet index.
Referenced by ReverseEngineeringGui::Segmentation::accept(), MeshCore::PointCollector::Append(), MeshCore::FitPointCollector::Append(), CalcVertexNormals(), and GetFacetPoints().
GetFacets() [1/2]
MeshFacetArray MeshKernel::GetFacets (const std::vector< unsigned long > & indices) const
Returns an array of facets to the given indices.
The indices must not be out of range.
GetFacets() [2/2]
const MeshFacetArray& MeshCore::MeshKernel::GetFacets (void) const
Returns the array of all facets.
Referenced by Mesh::MeshPy::collapseEdge(), MeshCore::MeshCurvature::ComputePerVertex(), MeshGui::ViewProviderMeshBuilder::createMesh(), MeshGui::MeshSelection::deleteSelectionBorder(), MeshGui::ViewProviderMesh::faceInfo(), MeshCore::MeshSegmentAlgorithm::FindSegments(), MeshGui::ViewProviderMesh::invertSelection(), MeshGui::ViewProviderMesh::isFacetSelected(), MeshGui::ViewProviderIndexedFaceSet::showOpenEdges(), MeshGui::ViewProviderMeshFaceSet::showOpenEdges(), MeshGui::ViewProviderMeshNode::showOpenEdges(), MeshCore::MeshSimplify::simplify(), Mesh::MeshPy::splitEdge(), and Mesh::MeshPy::swapEdge().
GetGravityPoint()
Base::Vector3f MeshCore::MeshKernel::GetGravityPoint (const MeshFacet & rclFacet) const protected
Calculates the gravity point to the given facet.
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
GetMemSize()
unsigned int MeshCore::MeshKernel::GetMemSize (void) const
Returns the number of required memory in bytes.
GetNormal()
Base::Vector3f MeshCore::MeshKernel::GetNormal (const MeshFacet & rclFacet) const protected
Calculates the normal to the given facet.
References Base::Vector3< _Precision >::Normalize().
GetPoint()
MeshPoint MeshCore::MeshKernel::GetPoint (unsigned long ulIndex) const
Returns the point at the given index.
This method is rather slow and should be called occasionally only. For fast access the MeshPointIterator interfsce should be used.
Referenced by CalcVertexNormals().
GetPointFacets()
std::vector< unsigned long > MeshKernel::GetPointFacets (const std::vector< unsigned long > & points) const
Returns the facet indices that share the given point indices.
References MeshCore::MeshPoint::IsFlag(), MeshAlgorithm, MeshCore::MeshPoint::SetFlag(), MeshCore::MeshPoint::TMP0, and MeshCore::MeshFacet::TMP0.
GetPoints() [1/2]
MeshPointArray MeshKernel::GetPoints (const std::vector< unsigned long > & indices) const
Returns an array of points to the given indices.
The indices must not be out of range.
GetPoints() [2/2]
const MeshPointArray& MeshCore::MeshKernel::GetPoints (void) const
Returns the array of all data points.
Referenced by ReverseEngineeringGui::Segmentation::accept(), MeshCore::FacetCurvature::Compute(), MeshGui::ViewProviderMeshBuilder::createMesh(), MeshGui::MeshSelection::deleteSelectionBorder(), ReverseEngineeringGui::SegmentationManual::Private::findGeometry(), MeshGui::ViewProviderMeshNode::showOpenEdges(), MeshCore::MeshSimplify::simplify(), MeshCore::PlaneFitSmoothing::Smooth(), MeshCore::PlaneFitSmoothing::SmoothPoints(), and MeshCore::LaplaceSmoothing::Umbrella().
GetSurface() [1/2]
float MeshKernel::GetSurface () const
Calculates the surface area of the mesh object.
References MeshCore::MeshGeomFacet::Area(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshFacetIterator::More(), and MeshCore::MeshFacetIterator::Next().
GetSurface() [2/2]
float MeshKernel::GetSurface (const std::vector< unsigned long > & aSegment) const
Calculates the surface area of the segment defined by aSegment.
References MeshCore::MeshGeomFacet::Area(), and MeshCore::MeshFacetIterator::Set().
GetVolume()
float MeshKernel::GetVolume () const
Calculates the volume of the mesh object.
Therefore the mesh must be a solid, if not 0 is returned.
References MeshCore::MeshFacetIterator::Init(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
HasFacets()
std::vector< unsigned long > MeshKernel::HasFacets (const MeshPointIterator & rclIter) const
Determines all facets that are associated to this point.
This method is very slow and should be called occasionally only.
References MeshCore::MeshPointIterator::Position().
HasNonManifolds()
bool MeshKernel::HasNonManifolds () const
Checks whether the mesh has non.manifold edges.
An edge is regarded as non-manifolds if it shares more than two facets.
References MeshCore::MeshEvalTopology::Evaluate().
HasOpenEdges()
bool MeshKernel::HasOpenEdges () const
Checks whether the mesh has open edges.
References MeshCore::MeshEvalSolid::Evaluate().
HasSelfIntersections()
bool MeshKernel::HasSelfIntersections () const
Checks whether the mesh intersects itself.
References MeshCore::MeshEvalSelfIntersection::Evaluate().
IsValid()
bool MeshCore::MeshKernel::IsValid (void) const
Returns true if the data structure is valid.
Referenced by RemoveInvalids().
Merge() [1/2]
void MeshKernel::Merge (const MeshKernel & rKernel)
Adds all facets and referenced points to the underlying mesh structure.
The client programmer must be sure that both meshes don't have geometric overlaps, otherwise the resulting mesh might be invalid, i.e. has self-intersections.
Note
The method guarantees that the order of the arrays of the underlying mesh and of the given array is kept.
Not all points of rKernel are necessarily appended to the underlying mesh but only these points which are referenced by facets of rKernel.
Referenced by AddFacets(), and Mesh::MeshObject::meshFromSegment().
Merge() [2/2]
void MeshKernel::Merge (const MeshPointArray & rPoints, const MeshFacetArray & rFaces)
This method is provided for convenience that directly accepts the point and facet arrays.
Note
Not all points of rPoints are necessarily appended to the underlying mesh but only these points which are referenced by facets of rFaces.
References RebuildNeighbours().
ModifyFacets()
MeshFacetModifier MeshCore::MeshKernel::ModifyFacets ()
Returns a modifier for the facet array.
ModifyPoints()
MeshPointModifier MeshCore::MeshKernel::ModifyPoints ()
Returns a modifier for the point array.
MovePoint()
void MeshCore::MeshKernel::MovePoint (unsigned long ulPtIndex, const Base::Vector3f & rclTrans)
Moves the point at the given index along the vector rclTrans.
operator*=()
void MeshKernel::operator*= (const Base::Matrix4D & rclMat)
Transform the data structure with the given transformation matrix.
References Transform().
operator+=() [1/2]
MeshKernel & MeshKernel::operator+= (const MeshGeomFacet & rclSFacet)
Adds a single facet to the data structure.
This method is very slow and should be called occasionally only.
References AddFacet().
operator+=() [2/2]
MeshKernel & MeshKernel::operator+= (const std::vector< MeshGeomFacet > & rclFAry)
Adds an array of facets to the data structure.
This method keeps temporarily set properties and flags.
References AddFacets().
operator=() [1/2]
MeshKernel & MeshKernel::operator= (const MeshKernel & rclMesh)
Assignment operator.
operator=() [2/2]
MeshKernel & MeshKernel::operator= (const std::vector< MeshGeomFacet > & rclFAry)
Replaces the current data structure with the structure built up of the array of triangles given in rclFAry.
References MeshCore::MeshBuilder::AddFacet(), MeshCore::MeshBuilder::Finish(), and MeshCore::MeshBuilder::Initialize().
PointIterator()
MeshPointIterator MeshKernel::PointIterator () const
Returns an iterator object to go over all points.
References MeshCore::MeshPointIterator::Begin().
Read()
void MeshKernel::Read (std::istream & rclIn)
References Base::Stream::BigEndian, Base::SwapEndian(), and draftgeoutils.general::v1().
RebuildNeighbours() [1/2]
void MeshKernel::RebuildNeighbours (unsigned long index) protected
Rebuilds the neighbour indices for subset of all facets from index index on.
References MeshCore::Edge_Index::f, MeshCore::Edge_Index::p0, MeshCore::Edge_Index::p1, MeshCore::parallel_sort(), and MeshCore::MeshFacet::Side().
RebuildNeighbours() [2/2]
void MeshKernel::RebuildNeighbours (void)
Rebuilds the neighbour indices for all facets.
Referenced by AddFacets(), Adopt(), Assign(), Merge(), and Mesh::MeshPy::rebuildNeighbourHood().
RecalcBoundBox()
void MeshKernel::RecalcBoundBox (void)
Forces a recalculation of the bounding box.
This method should be called after the removal of points.or after a transformation of the data structure.
Referenced by Adopt(), Assign(), DeleteFacets(), and DeletePoints().
RemoveInvalids()
void MeshKernel::RemoveInvalids ()
Removes all as INVALID marked points and facets from the structure.
References IsValid().
Referenced by DeleteFacets(), and DeletePoints().
SetPoint() [1/2]
void MeshCore::MeshKernel::SetPoint (unsigned long ulPtIndex, const Base::Vector3f & rPoint)
Sets the point at the given index to the new rPoint.
Referenced by Mesh::PropertyMeshKernel::setPointIndices(), MeshCore::PlaneFitSmoothing::Smooth(), MeshCore::PlaneFitSmoothing::SmoothPoints(), and MeshCore::LaplaceSmoothing::Umbrella().
SetPoint() [2/2]
void MeshCore::MeshKernel::SetPoint (unsigned long ulPtIndex, float x, float y, float z)
Sets the point at the given index to the new rPoint.
Smooth()
void MeshKernel::Smooth (int iterations, float d_max)
Smoothes the mesh kernel.
References MeshCore::LaplaceSmoothing::Smooth().
Swap()
void MeshKernel::Swap (MeshKernel & mesh)
Swaps the content of this kernel and mesh.
Transform()
void MeshKernel::Transform (const Base::Matrix4D & rclMat)
Transform the data structure with the given transformation matrix.
It does exactly the same as the '*=' operator.
Referenced by MeshPartGui::CrossSections::apply(), MeshPartGui::CurveOnMeshHandler::Private::createGrid(), Mesh::MeshObject::crossSections(), Mesh::MeshObject::inner(), Mesh::MeshObject::intersect(), operator*=(), Mesh::MeshObject::outer(), MeshGui::ViewProviderMesh::partMeshCallback(), Mesh::MeshPy::rotate(), MeshGui::ViewProviderMesh::segmMeshCallback(), Mesh::MeshObject::subtract(), Mesh::MeshPy::transform(), Mesh::MeshObject::transformGeometry(), Mesh::MeshPy::translate(), and Mesh::MeshObject::unite().
VisitNeighbourFacets()
unsigned long MeshKernel::VisitNeighbourFacets (MeshFacetVisitor & rclFVisitor, unsigned long ulStartFacet) const
This method visits all neighbour facets, i.e facets that share a common edge starting from the facet associated to index ulStartFacet.
All facets having set the VISIT flag are ignored. Therefore the user have to set or unset this flag if needed. All facets that get visited during this algorithm are marked as VISIT and the Visit() method of the given MeshFacetVisitor gets invoked. If there are no unvisited neighbours any more the algorithms returns immediately and returns the number of visited facets.
Note
For the start facet ulStartFacet MeshFacetVisitor::Visit() does not get invoked though the facet gets marked as VISIT.
References MeshCore::MeshFacetVisitor::AllowVisit(), MeshCore::MeshFacet::VISIT, and MeshCore::MeshFacetVisitor::Visit().
Referenced by MeshGui::ViewProviderMesh::deselectComponent(), Mesh::SegmentByMesh::execute(), MeshCore::MeshSegmentAlgorithm::FindSegments(), and MeshGui::ViewProviderMesh::selectComponent().
VisitNeighbourFacetsOverCorners()
unsigned long MeshKernel::VisitNeighbourFacetsOverCorners (MeshFacetVisitor & rclFVisitor, unsigned long ulStartFacet) const
Does basically the same as the method above unless the facets that share just a common point are regared as neighbours.
References MeshCore::MeshFacetArray::SetFlag(), MeshCore::MeshFacet::VISIT, and MeshCore::MeshFacetVisitor::Visit().
VisitNeighbourPoints()
unsigned long MeshKernel::VisitNeighbourPoints (MeshPointVisitor & rclPVisitor, unsigned long ulStartPoint) const
This method visits all neighbour points starting from the point associated to index ulStartPoint.
All points having set the VISIT flag are ignored. Therefore the user have to set or unset this flag if needed before the algorithm starts. All points that get visited during this algorithm are marked as VISIT and the Visit() method of the given MeshPointVisitor gets invoked. If there are no unvisited neighbours any more the algorithms returns immediately and returns the number of visited points.
Note
For the start facet ulStartPoint MeshPointVisitor::Visit() does not get invoked though the point gets marked as VISIT.
References MeshCore::MeshPoint::VISIT, and MeshCore::MeshPointVisitor::Visit().
Write()
void MeshKernel::Write (std::ostream & rclOut) const
Binary streaming of data.
References CountFacets(), and CountPoints().
Friends And Related Function Documentation
MeshAlgorithm
friend class MeshAlgorithm friend
Referenced by CutFacets(), and GetPointFacets().
MeshBuilder
friend class MeshBuilder friend
MeshFacetIterator
friend class MeshFacetIterator friend
MeshFastFacetIterator
friend class MeshFastFacetIterator friend
MeshFixDuplicatePoints
friend class MeshFixDuplicatePoints friend
MeshPointIterator
friend class MeshPointIterator friend
MeshTopoAlgorithm
friend class MeshTopoAlgorithm friend
MeshTrimming
friend class MeshTrimming friend
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/MeshKernel.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Evaluation.cpp
Sources/FreeCAD/src/Mod/Mesh/App/Core/MeshKernel.cpp
Sources/FreeCAD/src/Mod/Mesh/App/Core/Visitor.cpp