FreeCAD: Gui::SoVRMLAction Class Reference
Gui::SoVRMLAction Class Reference
#include <SoFCUnifiedSelection.h>
Public Member Functions
SbBool isOverrideMode () const
void setOverrideMode (SbBool)
SoVRMLAction ()
~SoVRMLAction ()
Static Public Member Functions
static void initClass ()
Detailed Description
Author
Werner Mayer
Constructor & Destructor Documentation
SoVRMLAction()
SoVRMLAction::SoVRMLAction ()
~SoVRMLAction()
SoVRMLAction::~SoVRMLAction ()
Member Function Documentation
initClass()
void SoVRMLAction::initClass (void) static
Referenced by Gui::SoFCDB::init().
isOverrideMode()
SbBool SoVRMLAction::isOverrideMode () const
setOverrideMode()
void SoVRMLAction::setOverrideMode (SbBool on)
Referenced by Gui::SoFCDB::writeToVRML(), and Gui::SoFCDB::writeToX3D().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/SoFCUnifiedSelection.h
FreeCAD/src/Gui/SoFCUnifiedSelection.cpp