FreeCAD: TechDrawGui::TaskRestoreLines Class Reference
TechDrawGui::TaskRestoreLines Class Reference
#include <TaskLineDecor.h>
Public Member Functions
virtual bool accept ()
virtual bool reject ()
TaskRestoreLines (TechDraw::DrawViewPart *partFeat, TechDrawGui::TaskLineDecor *parent)
~TaskRestoreLines ()
Protected Slots
void onAllPressed (void)
void onCenterPressed (void)
void onCosmeticPressed (void)
void onGeometryPressed (void)
Protected Member Functions
void changeEvent (QEvent *e)
int countInvisibleCenters (void)
int countInvisibleCosmetics (void)
int countInvisibleGeoms (void)
int countInvisibleLines (void)
void initUi (void)
void restoreInvisibleCenters (void)
void restoreInvisibleCosmetics (void)
void restoreInvisibleGeoms (void)
void restoreInvisibleLines (void)
Constructor & Destructor Documentation
TaskRestoreLines()
TaskRestoreLines::TaskRestoreLines (TechDraw::DrawViewPart * partFeat, TechDrawGui::TaskLineDecor * parent)
References draftgeoutils.intersections::connect(), initUi(), onAllPressed(), onCenterPressed(), onCosmeticPressed(), and onGeometryPressed().
~TaskRestoreLines()
TaskRestoreLines::~TaskRestoreLines ()
Member Function Documentation
accept()
bool TaskRestoreLines::accept (void) virtual
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void TaskRestoreLines::changeEvent (QEvent * e) protected
countInvisibleCenters()
int TaskRestoreLines::countInvisibleCenters (void) protected
References TechDraw::CosmeticExtension::CenterLines, and TechDraw::PropertyCenterLineList::getValues().
Referenced by countInvisibleLines(), and initUi().
countInvisibleCosmetics()
int TaskRestoreLines::countInvisibleCosmetics (void) protected
References TechDraw::CosmeticExtension::CosmeticEdges, and TechDraw::PropertyCosmeticEdgeList::getValues().
Referenced by countInvisibleLines(), and initUi().
countInvisibleGeoms()
int TaskRestoreLines::countInvisibleGeoms (void) protected
References TechDraw::CosmeticExtension::GeomFormats, and TechDraw::PropertyGeomFormatList::getValues().
Referenced by countInvisibleLines(), and initUi().
countInvisibleLines()
int TaskRestoreLines::countInvisibleLines (void) protected
References countInvisibleCenters(), countInvisibleCosmetics(), and countInvisibleGeoms().
Referenced by initUi(), onCenterPressed(), onCosmeticPressed(), and onGeometryPressed().
initUi()
void TaskRestoreLines::initUi (void) protected
References countInvisibleCenters(), countInvisibleCosmetics(), countInvisibleGeoms(), and countInvisibleLines().
Referenced by TaskRestoreLines().
onAllPressed
void TaskRestoreLines::onAllPressed (void) protected slot
References onCenterPressed(), onCosmeticPressed(), and onGeometryPressed().
Referenced by TaskRestoreLines().
onCenterPressed
void TaskRestoreLines::onCenterPressed (void) protected slot
References countInvisibleLines(), and restoreInvisibleCenters().
Referenced by onAllPressed(), and TaskRestoreLines().
onCosmeticPressed
void TaskRestoreLines::onCosmeticPressed (void) protected slot
References countInvisibleLines(), and restoreInvisibleCosmetics().
Referenced by onAllPressed(), and TaskRestoreLines().
onGeometryPressed
void TaskRestoreLines::onGeometryPressed (void) protected slot
References countInvisibleLines(), and restoreInvisibleGeoms().
Referenced by onAllPressed(), and TaskRestoreLines().
reject()
bool TaskRestoreLines::reject (void) virtual
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
restoreInvisibleCenters()
void TaskRestoreLines::restoreInvisibleCenters (void) protected
References TechDrawGui::TaskLineDecor::apply(), TechDraw::CosmeticExtension::CenterLines, TechDraw::PropertyCenterLineList::getValues(), and TechDraw::PropertyCenterLineList::setValues().
Referenced by onCenterPressed(), and restoreInvisibleLines().
restoreInvisibleCosmetics()
void TaskRestoreLines::restoreInvisibleCosmetics (void) protected
References TechDrawGui::TaskLineDecor::apply(), TechDraw::CosmeticExtension::CosmeticEdges, TechDraw::PropertyCosmeticEdgeList::getValues(), and TechDraw::PropertyCosmeticEdgeList::setValues().
Referenced by onCosmeticPressed(), and restoreInvisibleLines().
restoreInvisibleGeoms()
void TaskRestoreLines::restoreInvisibleGeoms (void) protected
References TechDrawGui::TaskLineDecor::apply(), TechDraw::CosmeticExtension::GeomFormats, TechDraw::PropertyGeomFormatList::getValues(), and TechDraw::PropertyGeomFormatList::setValues().
Referenced by onGeometryPressed(), and restoreInvisibleLines().
restoreInvisibleLines()
void TaskRestoreLines::restoreInvisibleLines (void) protected
References restoreInvisibleCenters(), restoreInvisibleCosmetics(), and restoreInvisibleGeoms().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/TaskLineDecor.h
FreeCAD/src/Mod/TechDraw/Gui/TaskLineDecor.cpp