FreeCAD: Ui_TaskFemConstraintPlaneRotation Class Reference
Ui_TaskFemConstraintPlaneRotation Class Reference
#include <ui_TaskFemConstraintPlaneRotation.h>
Public Member Functions
void retranslateUi (QWidget *TaskFemConstraintPlaneRotation)
void setupUi (QWidget *TaskFemConstraintPlaneRotation)
Public Attributes
QToolButton * btnAdd
QToolButton * btnRemove
QHBoxLayout * hLayout1
QLabel * lbl_info
QListWidget * lw_references
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void Ui_TaskFemConstraintPlaneRotation::retranslateUi (QWidget * TaskFemConstraintPlaneRotation)
References btnAdd, btnRemove, lbl_info, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Ui_TaskFemConstraintPlaneRotation::setupUi (QWidget * TaskFemConstraintPlaneRotation)
References btnAdd, btnRemove, hLayout1, lbl_info, lw_references, retranslateUi(), and verticalLayout.
Referenced by FemGui::TaskFemConstraintPlaneRotation::TaskFemConstraintPlaneRotation().
Member Data Documentation
btnAdd
QToolButton* Ui_TaskFemConstraintPlaneRotation::btnAdd
Referenced by retranslateUi(), setupUi(), and FemGui::TaskFemConstraintPlaneRotation::TaskFemConstraintPlaneRotation().
btnRemove
QToolButton* Ui_TaskFemConstraintPlaneRotation::btnRemove
Referenced by retranslateUi(), setupUi(), and FemGui::TaskFemConstraintPlaneRotation::TaskFemConstraintPlaneRotation().
hLayout1
QHBoxLayout* Ui_TaskFemConstraintPlaneRotation::hLayout1
Referenced by setupUi().
lbl_info
QLabel* Ui_TaskFemConstraintPlaneRotation::lbl_info
Referenced by retranslateUi(), and setupUi().
lw_references
QListWidget* Ui_TaskFemConstraintPlaneRotation::lw_references
Referenced by FemGui::TaskFemConstraintPlaneRotation::getReferences(), setupUi(), and FemGui::TaskFemConstraintPlaneRotation::TaskFemConstraintPlaneRotation().
verticalLayout
QVBoxLayout* Ui_TaskFemConstraintPlaneRotation::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Fem/Gui/ui_TaskFemConstraintPlaneRotation.h