FreeCAD: Gui::DockWnd::ReportView Class Reference
Gui::DockWnd::ReportView Class Reference
Report view containing an output window and a very simple Python console.
#include <ReportView.h>
Public Member Functions
ReportView (QWidget *parent=0)
Constructs a ReportView which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
~ReportView ()
Destroys the object and frees any allocated resources.
Protected Member Functions
void changeEvent (QEvent *e)
Detailed Description
Report view containing an output window and a very simple Python console.
See also
ReportOutput
PythonConsole
Author
Werner Mayer
Constructor & Destructor Documentation
ReportView()
ReportView::ReportView (QWidget * parent = 0)
Constructs a ReportView which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
References Gui::BitmapFactory(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), and ParameterGrp::GetInt().
~ReportView()
ReportView::~ReportView ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void ReportView::changeEvent (QEvent * e) protected
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/ReportView.h
Sources/FreeCAD/src/Gui/ReportView.cpp