FreeCAD: MeshPart::MeshAlgos Class Reference
MeshPart::MeshAlgos Class Reference
The mesh algorithms container class.
#include <MeshAlgos.h>
Static Public Member Functions
static MeshCore::MeshKernel * boolean (MeshCore::MeshKernel *Mesh1, MeshCore::MeshKernel *Mesh2, MeshCore::MeshKernel *pResult, int Type=0)
makes a boolean add The int Type stears the boolean oberation: 0=add;1=intersection;2=diff
static void coarsen (MeshCore::MeshKernel *Mesh, float f)
Coarsen the mesh.
static void cutByCurve (MeshCore::MeshKernel *pMesh, const std::vector< CurveProjector::FaceSplitEdge > &vSplitEdges)
static void cutByShape (const TopoDS_Shape &aShape, const MeshCore::MeshKernel *pMesh, MeshCore::MeshKernel *pToolMesh)
static void GetSampledCurves (const TopoDS_Edge &aEdge, std::vector< Base::Vector3f > &rclPoints, unsigned long ulNbOfPoints=30)
helper to discredicice a Edge...
static void LoftOnCurve (MeshCore::MeshKernel &ResultMesh, const TopoDS_Shape &Shape, const std::vector< Base::Vector3f > &poly, const Base::Vector3f &up=Base::Vector3f(0, 0, 1), float MaxSize=0.1)
creates a mesh loft on base of a curve and an up vector
static void offset (MeshCore::MeshKernel *Mesh, float fSize)
Calculate per Vertex normals and adds the Normal property bag.
static void offsetSpecial (MeshCore::MeshKernel *Mesh, float fSize, float zmax, float zmin)
static void offsetSpecial2 (MeshCore::MeshKernel *Mesh, float fSize)
Detailed Description
The mesh algorithms container class.
Member Function Documentation
boolean()
MeshCore::MeshKernel * MeshAlgos::boolean (MeshCore::MeshKernel * Mesh1, MeshCore::MeshKernel * Mesh2, MeshCore::MeshKernel * pResult, int Type = 0) static
makes a boolean add The int Type stears the boolean oberation: 0=add;1=intersection;2=diff
coarsen()
void MeshAlgos::coarsen (MeshCore::MeshKernel * Mesh, float f) static
Coarsen the mesh.
cutByCurve()
void MeshAlgos::cutByCurve (MeshCore::MeshKernel * pMesh, const std::vector< CurveProjector::FaceSplitEdge > & vSplitEdges) static
References MeshCore::MeshTopoAlgorithm::SplitFacet().
cutByShape()
void MeshAlgos::cutByShape (const TopoDS_Shape & aShape, const MeshCore::MeshKernel * pMesh, MeshCore::MeshKernel * pToolMesh) static
GetSampledCurves()
static void MeshPart::MeshAlgos::GetSampledCurves (const TopoDS_Edge & aEdge, std::vector< Base::Vector3f > & rclPoints, unsigned long ulNbOfPoints = 30) static
helper to discredicice a Edge...
LoftOnCurve()
void MeshAlgos::LoftOnCurve (MeshCore::MeshKernel & ResultMesh, const TopoDS_Shape & Shape, const std::vector< Base::Vector3f > & poly, const Base::Vector3f & up = Base::Vector3f(0,0,1), float MaxSize = 0.1) static
creates a mesh loft on base of a curve and an up vector
References MeshCore::MeshKernel::AddFacets(), Base::Vector3< _Precision >::Normalize(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
offset()
void MeshAlgos::offset (MeshCore::MeshKernel * Mesh, float fSize) static
Calculate per Vertex normals and adds the Normal property bag.
Referenced by gzip_utf8.GzipFile::read(), gzip_utf8.GzipFile::readline(), gzip_utf8.GzipFile::rewind(), gzip_utf8.GzipFile::seek(), DraftGui.DraftToolBar::taskUi(), and gzip_utf8.GzipFile::write().
offsetSpecial()
void MeshAlgos::offsetSpecial (MeshCore::MeshKernel * Mesh, float fSize, float zmax, float zmin) static
References Base::Vector3< _Precision >::Normalize(), and Base::Vector3< _Precision >::z.
offsetSpecial2()
void MeshAlgos::offsetSpecial2 (MeshCore::MeshKernel * Mesh, float fSize) static
References Base::Builder3D::addSingleLine(), Base::Builder3D::addSinglePoint(), MeshCore::MeshTopoAlgorithm::Cleanup(), MeshCore::MeshTopoAlgorithm::CollapseFacet(), MeshCore::MeshGeomFacet::GetGravityPoint(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), MeshCore::MeshGeomFacet::GetNormal(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshGeomFacet::IsFlag(), Base::Vector3< _Precision >::Length(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), Base::Vector3< _Precision >::Normalize(), MeshCore::MeshFacetIterator::Position(), and Base::Builder3D::saveToLog().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/MeshPart/App/MeshAlgos.h
Sources/FreeCAD/src/Mod/MeshPart/App/MeshAlgos.cpp