FreeCAD: Gui::SoTextLabel Class Reference
Gui::SoTextLabel Class Reference
A text label with a background color.
#include <SoTextLabel.h>
Public Member Functions
SoTextLabel ()
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFBool background
SoSFColor backgroundColor
SoSFFloat frameSize
Protected Member Functions
virtual void GLRender (SoGLRenderAction *action)
Renders the label.
virtual ~SoTextLabel ()
Detailed Description
A text label with a background color.
Author
Werner Mayer
Constructor & Destructor Documentation
SoTextLabel()
SoTextLabel::SoTextLabel ()
References background, backgroundColor, and frameSize.
~SoTextLabel()
virtual Gui::SoTextLabel::~SoTextLabel () protected virtual
Member Function Documentation
GLRender()
void SoTextLabel::GLRender (SoGLRenderAction * action) protected virtual
Renders the label.
References background, backgroundColor, frameSize, and draftgeoutils.general::v1().
initClass()
void SoTextLabel::initClass (void) static
s="""
  #Inventor V2.1 ascii
  Annotation {
    Translation { translation 4 0 0 }
    FontStyle {
        size 20
        style BOLD
    }
    BaseColor {
        rgb 0.0 0.0 0.0
    }
    SoTextLabel { string ["Text label", "Second line"] backgroundColor 1.0 0.447059 0.337255}
  }
"""
App.ActiveDocument.addObject("App::InventorObject","iv").Buffer=s
Referenced by Gui::SoFCDB::init().
Member Data Documentation
background
SoSFBool Gui::SoTextLabel::background
Referenced by GLRender(), and SoTextLabel().
backgroundColor
SoSFColor Gui::SoTextLabel::backgroundColor (void)
Referenced by GLRender(), and SoTextLabel().
frameSize
SoSFFloat Gui::SoTextLabel::frameSize
Referenced by GLRender(), and SoTextLabel().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SoTextLabel.h
Sources/FreeCAD/src/Gui/SoTextLabel.cpp