FreeCAD: MeshGui::CylinderFitParameter Class Reference
MeshGui::CylinderFitParameter Class Reference
Public Member Functions
CylinderFitParameter ()
virtual std::vector< float > getParameter (FitParameter::Points pts) const
virtual ~CylinderFitParameter ()
Public Member Functions inherited from MeshGui::FitParameter
virtual std::vector< float > getParameter (Points) const =0
virtual ~FitParameter ()
Constructor & Destructor Documentation
CylinderFitParameter()
MeshGui::CylinderFitParameter::CylinderFitParameter ()
~CylinderFitParameter()
virtual MeshGui::CylinderFitParameter::~CylinderFitParameter () virtual
Member Function Documentation
getParameter()
virtual std::vector< float > MeshGui::CylinderFitParameter::getParameter (FitParameter::Points pts) const virtual
Implements MeshGui::FitParameter.
References MeshCore::Approximation::AddPoints(), Gui::Command::App, Base::Console(), Base::Distance(), MeshCore::CylinderFit::Fit(), MeshCore::CylinderFit::GetAxis(), MeshCore::CylinderFit::GetBounding(), MeshCore::Approximation::GetGravity(), MeshCore::CylinderFit::GetInitialAxisFromNormals(), MeshCore::CylinderFit::GetRadius(), Base::ConsoleSingleton::Message(), MeshGui::FitParameter::Points::normals, MeshGui::FitParameter::Points::points, MeshCore::CylinderFit::SetInitialValues(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Mesh/Gui/SegmentationBestFit.cpp