FreeCAD: PartGui::SoBrepEdgeSet Class Reference
PartGui::SoBrepEdgeSet Class Reference
#include <SoBrepEdgeSet.h>
Classes
struct SelContext
Public Member Functions
SoBrepEdgeSet ()
Static Public Member Functions
static void initClass ()
Protected Member Functions
virtual SoDetail * createLineSegmentDetail (SoRayPickAction *action, const SoPrimitiveVertex *v1, const SoPrimitiveVertex *v2, SoPickedPoint *pp)
virtual void doAction (SoAction *action)
virtual void getBoundingBox (SoGetBoundingBoxAction *action)
virtual void GLRender (SoGLRenderAction *action)
virtual void GLRenderBelowPath (SoGLRenderAction *action)
virtual ~SoBrepEdgeSet ()
Constructor & Destructor Documentation
SoBrepEdgeSet()
SoBrepEdgeSet::SoBrepEdgeSet ()
~SoBrepEdgeSet()
virtual PartGui::SoBrepEdgeSet::~SoBrepEdgeSet () protected virtual
Member Function Documentation
createLineSegmentDetail()
SoDetail * SoBrepEdgeSet::createLineSegmentDetail (SoRayPickAction * action, const SoPrimitiveVertex * v1, const SoPrimitiveVertex * v2, SoPickedPoint * pp) protected virtual
doAction()
void SoBrepEdgeSet::doAction (SoAction * action) protected virtual
References Gui::SoSelectionElementAction::All, Gui::SoSelectionElementAction::Append, Gui::SoFCSelectionCounter::checkAction(), Gui::SoFCSelectionRoot::getActionContext(), Gui::SoHighlightElementAction::getColor(), Gui::SoSelectionElementAction::getColor(), Gui::SoHighlightElementAction::getElement(), Gui::SoSelectionElementAction::getElement(), Gui::SoSelectionElementAction::getType(), Gui::SoHighlightElementAction::isHighlighted(), Gui::SoSelectionElementAction::isSecondary(), Gui::SoSelectionElementAction::Remove, and Gui::SoFCSelectionRoot::removeActionContext().
getBoundingBox()
void SoBrepEdgeSet::getBoundingBox (SoGetBoundingBoxAction * action) protected virtual
GLRender()
void SoBrepEdgeSet::GLRender (SoGLRenderAction * action) protected virtual
References Gui::SoFCSelectionCounter::checkRenderCache().
GLRenderBelowPath()
void SoBrepEdgeSet::GLRenderBelowPath (SoGLRenderAction * action) protected virtual
initClass()
void SoBrepEdgeSet::initClass (void) static
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/SoBrepEdgeSet.h
FreeCAD/src/Mod/Part/Gui/SoBrepEdgeSet.cpp