FreeCAD: Link Struct Reference
Link Struct Reference
Public Member Functions
bool Contains (int n) const
bool IsConnected (const Link &other) const
Link ()
Link (int _n1, int _n2)
Public Attributes
int n1
int n2
Detailed Description
Link - a pair of integer numbers
Constructor & Destructor Documentation
Link() [1/2]
Link::Link (int _n1, int _n2)
Link() [2/2]
Link::Link ()
Member Function Documentation
Contains()
bool Link::Contains (int n) const
References n1, and n2.
Referenced by NETGENPlugin_Mesher::FixFaceMesh(), and IsConnected().
IsConnected()
bool Link::IsConnected (const Link & other) const
References Contains(), n1, and n2.
Referenced by NETGENPlugin_Mesher::FixFaceMesh().
Member Data Documentation
n1
int Link::n1
Referenced by Contains(), NETGENPlugin_Mesher::FixFaceMesh(), and IsConnected().
n2
int Link::n2
Referenced by Contains(), NETGENPlugin_Mesher::FixFaceMesh(), and IsConnected().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/src/NETGENPlugin/NETGENPlugin_Mesher.cpp