FreeCAD: FeaturePython.ViewProviderMesh Class Reference
FeaturePython.ViewProviderMesh Class Reference
Public Member Functions
def attach (self, obj)
def getDefaultDisplayMode (self)
def getIcon (self)
Member Function Documentation
attach()
def FeaturePython.ViewProviderMesh.attach (self, obj)
 Setup the scene sub-graph of the view provider, this method is mandatory
getDefaultDisplayMode()
def FeaturePython.ViewProviderMesh.getDefaultDisplayMode (self)
 Return the name of the default display mode. It must be defined in getDisplayModes.
getIcon()
def FeaturePython.ViewProviderMesh.getIcon (self)
 Return the icon in XMP format which will appear in the tree view. This method is optional
        and if not defined a default icon is shown.
Referenced by ArchAxisSystem.AxisSystemTaskPanel.update(), ArchComponent.ComponentTaskPanel.update(), and ArchSectionPlane.SectionPlaneTaskPanel.update().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/TemplatePyMod/FeaturePython.py