FreeCAD: SMDS_VtkCellIteratorToUNV Class Reference
SMDS_VtkCellIteratorToUNV Class Reference
#include <SMDS_VtkCellIterator.hxx>
Public Member Functions
virtual bool more ()
Return true if and only if there are other object in this iterator.
virtual const SMDS_MeshNode * next ()
Return the current object and step to the next one.
SMDS_VtkCellIteratorToUNV (SMDS_Mesh *mesh, int vtkCellId, SMDSAbs_EntityType aType)
virtual ~SMDS_VtkCellIteratorToUNV ()
Public Member Functions inherited from SMDS_Iterator< const SMDS_MeshNode * >
virtual bool more ()=0
Return true if and only if there are other object in this iterator.
virtual const SMDS_MeshNode * next ()=0
Return the current object and step to the next one.
virtual void remove ()
Delete the current element and step to the next one.
virtual ~SMDS_Iterator ()
Provide virtual destructor just for case if some derived iterator must have a destructor.
Additional Inherited Members
Protected Member Functions inherited from SMDS_VtkCellIterator
SMDS_VtkCellIterator ()
void exchange (vtkIdType a, vtkIdType b)
virtual bool more ()
Return true if and only if there are other object in this iterator.
virtual const SMDS_MeshElement * next ()
Return the current object and step to the next one.
SMDS_VtkCellIterator (SMDS_Mesh *mesh, int vtkCellId, SMDSAbs_EntityType aType)
virtual ~SMDS_VtkCellIterator ()
Protected Member Functions inherited from SMDS_Iterator< const SMDS_MeshElement * >
virtual bool more ()=0
Return true if and only if there are other object in this iterator.
virtual const SMDS_MeshElement * next ()=0
Return the current object and step to the next one.
virtual void remove ()
Delete the current element and step to the next one.
virtual ~SMDS_Iterator ()
Provide virtual destructor just for case if some derived iterator must have a destructor.
Constructor & Destructor Documentation
SMDS_VtkCellIteratorToUNV()
SMDS_VtkCellIteratorToUNV::SMDS_VtkCellIteratorToUNV (SMDS_Mesh * mesh, int vtkCellId, SMDSAbs_EntityType aType)
References SMDS_MeshCell::interlacedSmdsOrder().
~SMDS_VtkCellIteratorToUNV()
SMDS_VtkCellIteratorToUNV::~SMDS_VtkCellIteratorToUNV () virtual
Member Function Documentation
more()
bool SMDS_VtkCellIteratorToUNV::more () virtual
Return true if and only if there are other object in this iterator.
Reimplemented from SMDS_VtkCellIterator.
References SMDS_VtkCellIterator::more().
next()
const SMDS_MeshNode * SMDS_VtkCellIteratorToUNV::next () virtual
Return the current object and step to the next one.
Reimplemented from SMDS_VtkCellIterator.
References SMDS_VtkCellIterator::next().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_VtkCellIterator.hxx
FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_VtkCellIterator.cpp