FreeCAD: MeshCore::MeshFixCorruptedFacets Class Reference
MeshCore::MeshFixCorruptedFacets Class Reference
The MeshFixCorruptedFacets class fixes corrupted facets by removing them from the mesh structure.
#include <Degeneration.h>
Public Member Functions
bool Fixup ()
Removes corrupted facets.
MeshFixCorruptedFacets (MeshKernel &rclM)
Construction.
~MeshFixCorruptedFacets ()
Destruction.
Public Member Functions inherited from MeshCore::MeshValidation
MeshValidation (MeshKernel &rclB)
virtual ~MeshValidation ()
Detailed Description
The MeshFixCorruptedFacets class fixes corrupted facets by removing them from the mesh structure.
See also
MeshEvalCorruptedFacets
Author
Werner Mayer
Constructor & Destructor Documentation
MeshFixCorruptedFacets()
MeshCore::MeshFixCorruptedFacets::MeshFixCorruptedFacets (MeshKernel & rclM)
Construction.
~MeshFixCorruptedFacets()
MeshCore::MeshFixCorruptedFacets::~MeshFixCorruptedFacets ()
Destruction.
Member Function Documentation
Fixup()
bool MeshFixCorruptedFacets::Fixup () virtual
Removes corrupted facets.
Implements MeshCore::MeshValidation.
References MeshCore::MeshGeomFacet::Area(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), MeshCore::MeshFacetIterator::Position(), MeshCore::MeshTopoAlgorithm::RemoveCorruptedFacet(), and MeshCore::MeshFacetIterator::Set().
Referenced by Mesh::MeshObject::validateIndices().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Degeneration.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Degeneration.cpp