FreeCAD: PartDesignGui::TaskTransformedParameters Class Reference
PartDesignGui::TaskTransformedParameters Class Reference abstract
The transformed subclasses will be used in two different modes:
#include <TaskTransformedParameters.h>
Public Member Functions
virtual void apply ()=0
void exitSelectionMode ()
App::DocumentObject * getBaseObject () const
Get the TransformedFeature object associated with this task.
const std::vector< App::DocumentObject * > & getOriginals (void) const
Returns the originals property of associated top feeature object.
App::DocumentObject * getSketchObject () const
Get the sketch object of the first original either of the object associated with this feature or with the parent feature (MultiTransform mode)
int getTransactionID () const
void setupTransaction ()
TaskTransformedParameters (TaskMultiTransformParameters *parentTask)
Constructor for task with parent task (MultiTransform mode)
TaskTransformedParameters (ViewProviderTransformed *TransformedView, QWidget *parent=0)
Constructor for task with ViewProvider.
virtual ~TaskTransformedParameters ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (QWidget *parent=0)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (QWidget *parent=0)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockConnection (bool block)
void detachSelection ()
Detaches from the selection.
bool isConnectionAttached () const
bool isConnectionBlocked () const
SelectionObserver (bool attach=true, int resolve=1)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, int resolve=1)
Constructor.
virtual ~SelectionObserver ()
Public Member Functions inherited from Gui::DocumentObserver
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
virtual ~DocumentObserver ()
Protected Types
enum selectionModes { none , addFeature , removeFeature , reference }
Protected Slots
PartDesign::Transformed * getTopTransformedObject () const
Returns the base transformed object For stand alone features it will be objects associated with this object For features inside multitransform it will be the base multitransform object.
PartDesignGui::ViewProviderTransformed * getTopTransformedView () const
Returns the base transformation view provider For stand alone features it will be view provider associated with this object For features inside multitransform it will be the view provider of the multitransform object.
void indexesMoved ()
void onButtonAddFeature (const bool checked)
void onButtonRemoveFeature (const bool checked)
virtual void onFeatureDeleted (void)=0
virtual void onSubTaskButtonOK ()
Connect the subTask OK button to the MultiTransform task.
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Member Functions
virtual void addObject (App::DocumentObject *)
void addReferenceSelectionGate (bool edge, bool face, bool planar=true, bool whole=false)
virtual void changeEvent (QEvent *e)=0
void checkVisibility ()
virtual void clearButtons ()=0
void fillAxisCombo (ComboLinks &combolinks, Part::Part2DObject *sketch)
void fillPlanesCombo (ComboLinks &combolinks, Part::Part2DObject *sketch)
PartDesign::Transformed * getObject () const
Returns the base transformation For stand alone features it will be objects associated with the view provider For features inside multitransform it will be the parent's multitransform object.
int getUpdateViewTimeout () const
void hideBase ()
void hideObject ()
bool isViewUpdated () const
virtual void onSelectionChanged (const Gui::SelectionChanges &msg)=0
bool originalSelected (const Gui::SelectionChanges &msg)
void recomputeFeature ()
Recompute either this feature or the parent feature (MultiTransform mode)
virtual void removeObject (App::DocumentObject *)
void showBase ()
void showObject ()
virtual void slotDeletedObject (const Gui::ViewProviderDocumentObject &Obj)
Notifies when the object is about to be removed.
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Static Protected Member Functions
static void removeItemFromListWidget (QListWidget *widget, const QString &itemstr)
Protected Attributes
bool blockUpdate
Lock updateUI(), applying changes to the underlying feature and calling recomputeFeature()
bool insideMultiTransform
Flag indicating whether this object is a container for MultiTransform.
TaskMultiTransformParameters * parentTask
The MultiTransform parent task of this task.
QWidget * proxy
selectionModes selectionMode
int transactionID = 0
ViewProviderTransformed * TransformedView
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
The transformed subclasses will be used in two different modes:
As a stand-alone feature
As a container that stores transformation info for a MultiTransform feature. In this case the flag insideMultiTransform is set to true. Because in the second case there is no ViewProvider, some special methods are required to access the underlying FeatureTransformed object in two different ways.
Member Enumeration Documentation
selectionModes
enum PartDesignGui::TaskTransformedParameters::selectionModes protected
Enumerator
none
addFeature
removeFeature
reference
Constructor & Destructor Documentation
TaskTransformedParameters() [1/2]
TaskTransformedParameters::TaskTransformedParameters (ViewProviderTransformed * TransformedView, QWidget * parent = 0)
Constructor for task with ViewProvider.
References App::Application::getActiveTransaction(), and App::GetApplication().
TaskTransformedParameters() [2/2]
TaskTransformedParameters::TaskTransformedParameters (TaskMultiTransformParameters * parentTask)
Constructor for task with parent task (MultiTransform mode)
References none, and selectionMode.
~TaskTransformedParameters()
TaskTransformedParameters::~TaskTransformedParameters () virtual
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
addObject()
void TaskTransformedParameters::addObject (App::DocumentObject *) protected virtual
Reimplemented in PartDesignGui::TaskPolarPatternParameters, PartDesignGui::TaskMultiTransformParameters, PartDesignGui::TaskMirroredParameters, and PartDesignGui::TaskLinearPatternParameters.
Referenced by ArchPanel.NestTaskPanel::getContainer(), ArchPanel.NestTaskPanel::getShapes(), and originalSelected().
addReferenceSelectionGate()
void TaskTransformedParameters::addReferenceSelectionGate (bool edge, bool face, bool planar = true, bool whole = false) protected
References Gui::SelectionSingleton::addSelectionGate(), getBaseObject(), getTopTransformedObject(), and Gui::Selection().
apply()
virtual void PartDesignGui::TaskTransformedParameters::apply () pure virtual
Implemented in PartDesignGui::TaskScaledParameters, PartDesignGui::TaskPolarPatternParameters, PartDesignGui::TaskMultiTransformParameters, PartDesignGui::TaskMirroredParameters, and PartDesignGui::TaskLinearPatternParameters.
Referenced by PartDesignGui::TaskDlgScaledParameters::accept().
changeEvent()
virtual void PartDesignGui::TaskTransformedParameters::changeEvent (QEvent * e) protected pure virtual
Implemented in PartDesignGui::TaskScaledParameters, PartDesignGui::TaskPolarPatternParameters, PartDesignGui::TaskMultiTransformParameters, PartDesignGui::TaskMirroredParameters, and PartDesignGui::TaskLinearPatternParameters.
checkVisibility()
void TaskTransformedParameters::checkVisibility () protected
References getBaseObject(), Base::Persistence::getClassTypeId(), and getObject().
Referenced by onButtonRemoveFeature().
clearButtons()
virtual void PartDesignGui::TaskTransformedParameters::clearButtons () protected pure virtual
Implemented in PartDesignGui::TaskScaledParameters, PartDesignGui::TaskPolarPatternParameters, PartDesignGui::TaskMultiTransformParameters, PartDesignGui::TaskMirroredParameters, and PartDesignGui::TaskLinearPatternParameters.
Referenced by exitSelectionMode().
exitSelectionMode()
void TaskTransformedParameters::exitSelectionMode ()
References clearButtons(), none, Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), selectionMode, and showObject().
Referenced by PartDesignGui::TaskDlgTransformedParameters::accept(), onButtonAddFeature(), onButtonRemoveFeature(), PartDesignGui::TaskLinearPatternParameters::onSelectionChanged(), PartDesignGui::TaskMirroredParameters::onSelectionChanged(), PartDesignGui::TaskMultiTransformParameters::onSelectionChanged(), PartDesignGui::TaskPolarPatternParameters::onSelectionChanged(), PartDesignGui::TaskScaledParameters::onSelectionChanged(), and PartDesignGui::TaskDlgTransformedParameters::reject().
fillAxisCombo()
void TaskTransformedParameters::fillAxisCombo (ComboLinks & combolinks, Part::Part2DObject * sketch) protected
References PartDesignGui::ComboLinks::addLink(), PartDesignGui::ComboLinks::clear(), Base::Console(), Base::ConsoleSingleton::Error(), PartDesign::Body::findBodyOf(), Part::Part2DObject::getAxisCount(), getObject(), App::OriginGroupExtension::getOrigin(), App::Origin::getX(), App::Origin::getY(), App::Origin::getZ(), and Base::Exception::what().
fillPlanesCombo()
void TaskTransformedParameters::fillPlanesCombo (ComboLinks & combolinks, Part::Part2DObject * sketch) protected
References PartDesignGui::ComboLinks::addLink(), PartDesignGui::ComboLinks::clear(), Base::Console(), Base::ConsoleSingleton::Error(), PartDesign::Body::findBodyOf(), Part::Part2DObject::getAxisCount(), getObject(), App::OriginGroupExtension::getOrigin(), App::Origin::getXY(), App::Origin::getXZ(), App::Origin::getYZ(), and Base::Exception::what().
getBaseObject()
App::DocumentObject * TaskTransformedParameters::getBaseObject () const
Get the TransformedFeature object associated with this task.
References PartDesign::Feature::getBaseObject(), PartDesign::Feature::getFeatureBody(), and getTopTransformedObject().
Referenced by addReferenceSelectionGate(), checkVisibility(), hideBase(), and showBase().
getObject()
PartDesign::Transformed * TaskTransformedParameters::getObject (void) const protected
Returns the base transformation For stand alone features it will be objects associated with the view provider For features inside multitransform it will be the parent's multitransform object.
References Gui::ViewProviderDocumentObject::getObject(), PartDesignGui::TaskMultiTransformParameters::getSubFeature(), insideMultiTransform, parentTask, and TransformedView.
Referenced by checkVisibility(), fillAxisCombo(), fillPlanesCombo(), indexesMoved(), PartDesignGui::TaskLinearPatternParameters::onSelectionChanged(), PartDesignGui::TaskMirroredParameters::onSelectionChanged(), PartDesignGui::TaskPolarPatternParameters::onSelectionChanged(), originalSelected(), setupTransaction(), PartDesignGui::TaskLinearPatternParameters::~TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::~TaskMirroredParameters(), and PartDesignGui::TaskPolarPatternParameters::~TaskPolarPatternParameters().
getOriginals()
const std::vector<App::DocumentObject*>& PartDesignGui::TaskTransformedParameters::getOriginals (void) const
Returns the originals property of associated top feeature object.
getSketchObject()
App::DocumentObject * TaskTransformedParameters::getSketchObject () const
Get the sketch object of the first original either of the object associated with this feature or with the parent feature (MultiTransform mode)
References PartDesign::Transformed::getSketchObject(), and getTopTransformedObject().
getTopTransformedObject
PartDesign::Transformed * TaskTransformedParameters::getTopTransformedObject () const protected slot
Returns the base transformed object For stand alone features it will be objects associated with this object For features inside multitransform it will be the base multitransform object.
References Base::Persistence::getClassTypeId(), Gui::ViewProviderDocumentObject::getObject(), and getTopTransformedView().
Referenced by addReferenceSelectionGate(), getBaseObject(), getSketchObject(), hideObject(), and showObject().
getTopTransformedView
PartDesignGui::ViewProviderTransformed * TaskTransformedParameters::getTopTransformedView () const protected slot
Returns the base transformation view provider For stand alone features it will be view provider associated with this object For features inside multitransform it will be the view provider of the multitransform object.
References insideMultiTransform, parentTask, and TransformedView.
Referenced by getTopTransformedObject(), and recomputeFeature().
getTransactionID()
int PartDesignGui::TaskTransformedParameters::getTransactionID () const
References transactionID.
getUpdateViewTimeout()
int TaskTransformedParameters::getUpdateViewTimeout () const protected
hideBase()
void TaskTransformedParameters::hideBase () protected
References getBaseObject().
hideObject()
void TaskTransformedParameters::hideObject () protected
References getTopTransformedObject().
Referenced by onButtonAddFeature().
indexesMoved
void TaskTransformedParameters::indexesMoved () protected slot
References App::DocumentObject::getDocument(), getObject(), App::Document::getObject(), App::PropertyListsT< T, ListT, ParentT >::getValues(), PartDesign::Transformed::Originals, recomputeFeature(), setupTransaction(), and App::PropertyLinkList::setValues().
Referenced by PartDesignGui::TaskMultiTransformParameters::TaskMultiTransformParameters().
isViewUpdated()
bool TaskTransformedParameters::isViewUpdated () const protected
References blockUpdate.
onButtonAddFeature
void TaskTransformedParameters::onButtonAddFeature (const bool checked) protected slot
References addFeature, Gui::SelectionSingleton::clearSelection(), exitSelectionMode(), hideObject(), Gui::Selection(), selectionMode, and showBase().
Referenced by PartDesignGui::TaskMultiTransformParameters::TaskMultiTransformParameters().
onButtonRemoveFeature
void TaskTransformedParameters::onButtonRemoveFeature (const bool checked) protected slot
References checkVisibility(), Gui::SelectionSingleton::clearSelection(), exitSelectionMode(), removeFeature, Gui::Selection(), and selectionMode.
Referenced by PartDesignGui::TaskMultiTransformParameters::TaskMultiTransformParameters().
onFeatureDeleted
virtual void PartDesignGui::TaskTransformedParameters::onFeatureDeleted (void) protected pure virtual slot
onSelectionChanged()
virtual void PartDesignGui::TaskTransformedParameters::onSelectionChanged (const Gui::SelectionChanges & msg) protected pure virtual
Implements Gui::SelectionObserver.
Implemented in PartDesignGui::TaskScaledParameters, PartDesignGui::TaskPolarPatternParameters, PartDesignGui::TaskMultiTransformParameters, PartDesignGui::TaskMirroredParameters, and PartDesignGui::TaskLinearPatternParameters.
onSubTaskButtonOK
virtual void PartDesignGui::TaskTransformedParameters::onSubTaskButtonOK () protected virtual slot
Connect the subTask OK button to the MultiTransform task.
Referenced by PartDesignGui::TaskLinearPatternParameters::TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::TaskMirroredParameters(), PartDesignGui::TaskPolarPatternParameters::TaskPolarPatternParameters(), and PartDesignGui::TaskScaledParameters::TaskScaledParameters().
originalSelected()
bool TaskTransformedParameters::originalSelected (const Gui::SelectionChanges & msg) protected
References addFeature, addObject(), Gui::SelectionChanges::AddSelection, DraftVecUtils::find(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), getObject(), App::Document::getObject(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Base::BaseClass::isDerivedFrom(), PartDesign::Transformed::Originals, recomputeFeature(), removeFeature, removeObject(), selectionMode, setupTransaction(), and App::PropertyLinkList::setValues().
Referenced by PartDesignGui::TaskLinearPatternParameters::onSelectionChanged(), PartDesignGui::TaskMirroredParameters::onSelectionChanged(), PartDesignGui::TaskMultiTransformParameters::onSelectionChanged(), PartDesignGui::TaskPolarPatternParameters::onSelectionChanged(), and PartDesignGui::TaskScaledParameters::onSelectionChanged().
recomputeFeature()
void TaskTransformedParameters::recomputeFeature () protected
Recompute either this feature or the parent feature (MultiTransform mode)
References getTopTransformedView(), and PartDesignGui::ViewProviderTransformed::recomputeFeature().
Referenced by indexesMoved(), PartDesignGui::TaskLinearPatternParameters::onSelectionChanged(), PartDesignGui::TaskMirroredParameters::onSelectionChanged(), PartDesignGui::TaskPolarPatternParameters::onSelectionChanged(), and originalSelected().
removeItemFromListWidget()
void TaskTransformedParameters::removeItemFromListWidget (QListWidget * widget, const QString & itemstr) static protected
Referenced by PartDesignGui::TaskScaledParameters::onSelectionChanged(), PartDesignGui::TaskLinearPatternParameters::removeObject(), PartDesignGui::TaskMirroredParameters::removeObject(), PartDesignGui::TaskMultiTransformParameters::removeObject(), and PartDesignGui::TaskPolarPatternParameters::removeObject().
removeObject()
void TaskTransformedParameters::removeObject (App::DocumentObject *) protected virtual
Reimplemented in PartDesignGui::TaskPolarPatternParameters, PartDesignGui::TaskMultiTransformParameters, PartDesignGui::TaskMirroredParameters, and PartDesignGui::TaskLinearPatternParameters.
Referenced by originalSelected().
setupTransaction()
void TaskTransformedParameters::setupTransaction ()
References App::Application::getActiveTransaction(), App::GetApplication(), getObject(), App::Application::setActiveTransaction(), and transactionID.
Referenced by indexesMoved(), PartDesignGui::TaskLinearPatternParameters::onSelectionChanged(), PartDesignGui::TaskMirroredParameters::onSelectionChanged(), PartDesignGui::TaskPolarPatternParameters::onSelectionChanged(), and originalSelected().
showBase()
void TaskTransformedParameters::showBase () protected
References getBaseObject().
Referenced by onButtonAddFeature().
showObject()
void TaskTransformedParameters::showObject () protected
References getTopTransformedObject().
Referenced by exitSelectionMode().
slotDeletedObject()
void TaskTransformedParameters::slotDeletedObject (const Gui::ViewProviderDocumentObject & Obj) protected virtual
Notifies when the object is about to be removed.
Reimplemented from Gui::DocumentObserver.
References TransformedView.
Member Data Documentation
blockUpdate
bool PartDesignGui::TaskTransformedParameters::blockUpdate protected
Lock updateUI(), applying changes to the underlying feature and calling recomputeFeature()
Referenced by isViewUpdated(), PartDesignGui::TaskLinearPatternParameters::TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::TaskMirroredParameters(), PartDesignGui::TaskPolarPatternParameters::TaskPolarPatternParameters(), and PartDesignGui::TaskScaledParameters::TaskScaledParameters().
insideMultiTransform
bool PartDesignGui::TaskTransformedParameters::insideMultiTransform protected
Flag indicating whether this object is a container for MultiTransform.
Referenced by getObject(), and getTopTransformedView().
parentTask
TaskMultiTransformParameters* PartDesignGui::TaskTransformedParameters::parentTask protected
The MultiTransform parent task of this task.
Referenced by getObject(), getTopTransformedView(), PartDesignGui::TaskLinearPatternParameters::TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::TaskMirroredParameters(), PartDesignGui::TaskPolarPatternParameters::TaskPolarPatternParameters(), and PartDesignGui::TaskScaledParameters::TaskScaledParameters().
proxy
QWidget* PartDesignGui::TaskTransformedParameters::proxy protected
Referenced by PartDesignGui::TaskLinearPatternParameters::changeEvent(), PartDesignGui::TaskMirroredParameters::changeEvent(), PartDesignGui::TaskMultiTransformParameters::changeEvent(), PartDesignGui::TaskPolarPatternParameters::changeEvent(), PartDesignGui::TaskScaledParameters::changeEvent(), PartDesignGui::TaskLinearPatternParameters::TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::TaskMirroredParameters(), PartDesignGui::TaskMultiTransformParameters::TaskMultiTransformParameters(), PartDesignGui::TaskPolarPatternParameters::TaskPolarPatternParameters(), PartDesignGui::TaskScaledParameters::TaskScaledParameters(), PartDesignGui::TaskLinearPatternParameters::~TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::~TaskMirroredParameters(), PartDesignGui::TaskMultiTransformParameters::~TaskMultiTransformParameters(), PartDesignGui::TaskPolarPatternParameters::~TaskPolarPatternParameters(), and PartDesignGui::TaskScaledParameters::~TaskScaledParameters().
selectionMode
selectionModes PartDesignGui::TaskTransformedParameters::selectionMode protected
Referenced by Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonRef1(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonRef2(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonSupport(), exitSelectionMode(), onButtonAddFeature(), onButtonRemoveFeature(), PartDesignGui::TaskLinearPatternParameters::onSelectionChanged(), PartDesignGui::TaskMirroredParameters::onSelectionChanged(), PartDesignGui::TaskPolarPatternParameters::onSelectionChanged(), PartDesignGui::TaskScaledParameters::onSelectionChanged(), originalSelected(), PartDesignGui::TaskLinearPatternParameters::TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::TaskMirroredParameters(), PartDesignGui::TaskPolarPatternParameters::TaskPolarPatternParameters(), and TaskTransformedParameters().
transactionID
int PartDesignGui::TaskTransformedParameters::transactionID = 0 protected
Referenced by getTransactionID(), and setupTransaction().
TransformedView
ViewProviderTransformed* PartDesignGui::TaskTransformedParameters::TransformedView protected
Referenced by PartDesignGui::TaskLinearPatternParameters::apply(), PartDesignGui::TaskPolarPatternParameters::apply(), PartDesignGui::TaskScaledParameters::apply(), getObject(), getTopTransformedView(), PartDesignGui::TaskMultiTransformParameters::getTransformFeatures(), slotDeletedObject(), and PartDesignGui::TaskMultiTransformParameters::TaskMultiTransformParameters().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/PartDesign/Gui/TaskTransformedParameters.h
Sources/FreeCAD/src/Mod/PartDesign/Gui/TaskTransformedParameters.cpp