FreeCAD: TechDrawGui::TaskLinkDim Class Reference
TechDrawGui::TaskLinkDim Class Reference
#include <TaskLinkDim.h>
Public Member Functions
bool accept ()
bool reject ()
TaskLinkDim (std::vector< App::DocumentObject * > parts, std::vector< std::string > &subs, TechDraw::DrawPage *page)
~TaskLinkDim ()
Protected Slots
void onCurrentItemChanged (QTreeWidgetItem *, QTreeWidgetItem *)
Protected Member Functions
void changeEvent (QEvent *e)
bool dimReferencesSelection (const TechDraw::DrawViewDimension *dim) const
does this dim already have a reference to the selection?
void loadAvailDims ()
void loadToTree (const TechDraw::DrawViewDimension *dim, const bool selected, Gui::Document *guiDoc)
void updateDims ()
Constructor & Destructor Documentation
TaskLinkDim()
TaskLinkDim::TaskLinkDim (std::vector< App::DocumentObject * > parts, std::vector< std::string > & subs, TechDraw::DrawPage * page)
References draftgeoutils.intersections::connect(), loadAvailDims(), and onCurrentItemChanged().
~TaskLinkDim()
TaskLinkDim::~TaskLinkDim ()
Member Function Documentation
accept()
bool TaskLinkDim::accept (void)
References updateDims().
Referenced by TechDrawGui::TaskDlgLinkDim::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void TaskLinkDim::changeEvent (QEvent * e) protected
dimReferencesSelection()
bool TaskLinkDim::dimReferencesSelection (const TechDraw::DrawViewDimension * dim) const protected
does this dim already have a reference to the selection?
References App::PropertyLinkSubList::getSubValues(), App::PropertyLinkSubList::getValues(), TechDraw::DrawViewDimension::has3DReferences(), and TechDraw::DrawViewDimension::References3D.
Referenced by loadAvailDims(), and updateDims().
loadAvailDims()
void TaskLinkDim::loadAvailDims () protected
References dimReferencesSelection(), Base::Persistence::getClassTypeId(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), TechDraw::DrawViewDimension::getRefType(), TechDraw::DrawViewDimension::getRefTypeSubElements(), App::PropertyListsT< T, ListT, ParentT >::getValues(), TechDraw::DrawViewDimension::has3DReferences(), Gui::Application::Instance, loadToTree(), and TechDraw::DrawPage::Views.
Referenced by TaskLinkDim().
loadToTree()
void TaskLinkDim::loadToTree (const TechDraw::DrawViewDimension * dim, const bool selected, Gui::Document * guiDoc) protected
References Gui::ViewProvider::getIcon(), App::DocumentObject::getNameInDocument(), App::PropertyString::getValue(), Gui::Document::getViewProvider(), and App::DocumentObject::Label.
Referenced by loadAvailDims().
onCurrentItemChanged
void TaskLinkDim::onCurrentItemChanged (QTreeWidgetItem * current, QTreeWidgetItem * previous) protected slot
Referenced by TaskLinkDim().
reject()
bool TaskLinkDim::reject (void)
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), TechDrawGui::TaskDlgLinkDim::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
updateDims()
void TaskLinkDim::updateDims () protected
References TechDraw::DrawViewDimension::clear3DMeasurements(), dimReferencesSelection(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), Gui::Command::Gui, TechDraw::DrawViewDimension::References3D, App::PropertyLinkSubList::setValue(), and App::PropertyLinkSubList::setValues().
Referenced by accept().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/TaskLinkDim.h
FreeCAD/src/Mod/TechDraw/Gui/TaskLinkDim.cpp