FreeCAD: TechDrawGui::DlgPageChooser Class Reference
TechDrawGui::DlgPageChooser Class Reference
#include <DlgPageChooser.h>
Public Member Functions
void accept ()
DlgPageChooser (const std::vector< std::string > labels, const std::vector< std::string > names, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
std::string getSelection () const
void reject ()
~DlgPageChooser ()
Destroys the object and frees any allocated resources.
Constructor & Destructor Documentation
DlgPageChooser()
DlgPageChooser::DlgPageChooser (const std::vector< std::string > labels, const std::vector< std::string > names, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
References draftgeoutils.intersections::connect().
~DlgPageChooser()
DlgPageChooser::~DlgPageChooser ()
Destroys the object and frees any allocated resources.
Member Function Documentation
accept()
void DlgPageChooser::accept (void)
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
getSelection()
std::string DlgPageChooser::getSelection (void) const
References TechDrawGui::Ui_DlgPageChooser::lwPages.
Referenced by TechDrawGui::DrawGuiUtil::findPage(), and femguiutils.selection_widgets._Selector::setHelpText().
reject()
void DlgPageChooser::reject (void)
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/DlgPageChooser.h
FreeCAD/src/Mod/TechDraw/Gui/DlgPageChooser.cpp