FreeCAD: App::PropertyColor Class Reference
App::PropertyColor Class Reference
Color properties This is the father of all properties handling colors.
#include <PropertyStandard.h>
Public Member Functions
virtual Property * Copy (void) const
Returns a new copy of the property (mainly for Undo/Redo and transactions)
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
const Color & getValue (void) const
This method returns a string representation of the property.
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
virtual void Paste (const Property &from)
Paste the value from the property (mainly for Undo/Redo and transactions)
PropertyColor ()
A constructor.
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
virtual void setPyObject (PyObject *)
void setValue (const Color &col)
Sets the property.
void setValue (float r, float g, float b, float a=0.0f)
void setValue (uint32_t rgba)
virtual ~PropertyColor ()
A destructor.
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual Property * Copy (void) const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
int64_t getID () const
Return a unique ID for the property.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const char * getName (void) const
Get the name of this property in the belonging container With hasName() it can be checked beforehand if a valid name is set.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
bool hasName () const
Check if the property has a name set.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , Busy = 15 ,
CopyOnChange = 16 , UserEdit = 17 , PropStaticBegin = 21 , PropDynamic = 21 ,
PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 , PropTransient = 25 ,
PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 , User1 = 28 ,
User2 = 29 , User3 = 30 , User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Check if the passed name is valid.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Detailed Description
Color properties This is the father of all properties handling colors.
Constructor & Destructor Documentation
PropertyColor()
PropertyColor::PropertyColor ()
A constructor.
A more elaborate description of the constructor.
Referenced by Copy().
~PropertyColor()
PropertyColor::~PropertyColor () virtual
A destructor.
A more elaborate description of the destructor.
Member Function Documentation
Copy()
Property * PropertyColor::Copy (void) const virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References PropertyColor().
getEditorName()
virtual const char * App::PropertyColor::getEditorName (void) const virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
getMemSize()
virtual unsigned int App::PropertyColor::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
See also
Base::Persistence
Reimplemented from App::Property.
getPyObject()
PyObject * PropertyColor::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
getValue()
const Color & PropertyColor::getValue (void) const
This method returns a string representation of the property.
Referenced by MeshGui::ViewProviderFace::attach(), MeshGui::ViewProviderMesh::deselectFacet(), Gui::ViewProviderAnnotationLabel::drawImage(), TechDrawGui::QGIViewSection::drawSectionFace(), TechDrawGui::QGIViewPart::drawViewPart(), Drawing::FeatureViewAnnotation::execute(), Drawing::FeatureViewSpreadsheet::execute(), Raytracing::LuxFeature::execute(), Raytracing::RayFeature::execute(), TechDraw::DrawViewDraft::execute(), ImportGui::ExportOCAFGui::findColors(), PartGui::ViewProviderPartExt::getElementColors(), TechDrawGui::TaskGeomHatch::getParameters(), App::PropertyColorList::getPyValue(), TechDraw::DrawViewSpreadsheet::getSheetImage(), PartDesignGui::ViewProviderShapeBinder::highlightReferences(), SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), PartDesignGui::ViewProviderDressUp::highlightReferences(), FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences(), SurfaceGui::ViewProviderFilling::highlightReferences(), SurfaceGui::ViewProviderSections::highlightReferences(), MeshGui::ViewProviderMesh::highlightSegments(), MeshGui::ViewProviderMesh::highlightSelection(), Gui::ViewProviderAnnotation::onChanged(), Gui::ViewProviderAnnotationLabel::onChanged(), Gui::ViewProviderGeometryObject::onChanged(), Gui::ViewProviderMeasureDistance::onChanged(), FemGui::ViewProviderFemConstraint::onChanged(), FemGui::ViewProviderFemMesh::onChanged(), MeshGui::ViewProviderMesh::onChanged(), MeshGui::ViewProviderMeshNode::onChanged(), PathGui::ViewProviderPath::onChanged(), PartGui::ViewProviderPartExt::onChanged(), TechDrawGui::QGIViewDimension::prefNormalColor(), PartGui::FaceColors::Private::Private(), FemGui::ViewProviderFemMesh::resetColorByElementId(), FemGui::ViewProviderFemMesh::resetColorByNodeId(), MeshGui::ViewProviderMesh::resetFacetTransparency(), TechDrawGui::TaskHatch::saveHatchState(), MeshGui::ViewProviderMesh::setFacetTransparency(), TechDrawGui::TaskLeaderLine::setUiEdit(), TechDrawGui::TaskRichAnno::setUiEdit(), TechDrawGui::TaskBalloon::TaskBalloon(), TechDrawGui::TaskDimension::TaskDimension(), MeshGui::ViewProviderMesh::tryColorPerVertexOrFace(), MeshGui::ViewProviderMesh::unhighlightSelection(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderChamfer::updateData(), and PartGui::ViewProviderPartExt::ViewProviderPartExt().
isSame()
virtual bool App::PropertyColor::isSame (const Property & other) const virtual
Compare if this property has the same content as the given one.
Reimplemented from App::Property.
References Base::Persistence::getTypeId().
Paste()
void PropertyColor::Paste (const Property & from) virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Restore()
void PropertyColor::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References Base::XMLReader::getAttributeAsUnsigned(), Base::XMLReader::readElement(), and setValue().
Save()
void PropertyColor::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References Base::Writer::ind(), and Base::Writer::Stream().
setPyObject()
void PropertyColor::setPyObject (PyObject * value) virtual
Reimplemented from Base::BaseClass.
References App::Color::a, App::Color::b, App::Color::g, App::Color::r, App::Color::setPackedValue(), and setValue().
Referenced by App::PropertyColorList::getPyValue().
setValue() [1/3]
void PropertyColor::setValue (const Color & col)
Sets the property.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Referenced by TechDrawGui::TaskHatch::createHatch(), TechDrawGui::ViewProviderViewSection::getParameters(), Gui::ViewProviderGeometryObject::onChanged(), PartGui::ViewProviderPartExt::onChanged(), PartDesignGui::ViewProviderSubShapeBinder::onChanged(), TechDrawGui::TaskGeomHatch::reject(), Restore(), TechDrawGui::TaskHatch::restoreHatchState(), setPyObject(), TechDrawGui::TaskRichAnno::updateAnnoFeature(), FemGui::ViewProviderFemConstraintFluidBoundary::updateData(), TechDrawGui::TaskHatch::updateHatch(), TechDrawGui::TaskLeaderLine::updateLeaderFeature(), TechDrawGui::TaskGeomHatch::updateValues(), PartDesignGui::ViewProviderDatum::ViewProviderDatum(), and FemGui::ViewProviderFemMesh::ViewProviderFemMesh().
setValue() [2/3]
void PropertyColor::setValue (float r, float g, float b, float a = 0.0f)
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
setValue() [3/3]
void PropertyColor::setValue (uint32_t rgba)
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
The documentation for this class was generated from the following files:
FreeCAD/src/App/PropertyStandard.h
FreeCAD/src/App/PropertyStandard.cpp