FreeCAD: PathScripts.PathDressup Namespace Reference
PathScripts.PathDressup Namespace Reference
Functions
def baseOp (path)
def hasEntryMethod (path)
def selection ()
def toolController (path)
Function Documentation
baseOp()
def PathScripts.PathDressup.baseOp (path)
baseOp(path) ... return the base operation underlying the given path
Referenced by PathScripts.PathDressup.toolController(), and PathCommands.translate().
hasEntryMethod()
def PathScripts.PathDressup.hasEntryMethod (path)
hasEntryDressup(path) ... returns true if the given object already has an entry method attached.
selection()
def PathScripts.PathDressup.selection ()
isActive() ... return True if a dressup command is possible.
toolController()
def PathScripts.PathDressup.toolController (path)
toolController(path) ... return the tool controller from the base op.
References PathScripts.PathDressup.baseOp().