FreeCAD: VISCOUS_2D Namespace Reference
VISCOUS_2D Namespace Reference
Classes
struct _LayerEdge
Edge normal to FACE boundary, connecting a point on EDGE (_uvOut) and a point of a layer internal boundary (_uvIn)
struct _PolyLine
Poly line composed of _Segment's of one EDGE. It's used to detect intersection of inflated layers by intersecting _Segment's in 2D.
struct _ProxyMeshHolder
SMESH_subMeshEventListener used to store _ProxyMeshOfFace, computed by _ViscousBuilder2D, in a SMESH_subMesh of the FACE. This is to delete _ProxyMeshOfFace when StdMeshers_ViscousLayers2D hypothesis is modified.
struct _ProxyMeshOfFace
Proxy Mesh of FACE with viscous layers. It's needed only to redefine newSubmesh().
struct _Segment
Segment connecting inner ends of two _LayerEdge's.
struct _SegmentIntersection
Intersector of _Segment's.
struct _SegmentTree
Tree of _Segment's used for a faster search of _Segment's.
class _ViscousBuilder2D
Builder of viscous layers.
Typedefs
typedef int TGeomID
typedef StdMeshers_ViscousLayers2D THypVL
typedef map< const SMDS_MeshNode *, _LayerEdge *, TIDCompare > TNode2Edge
Functions
bool findHyps (SMESH_Mesh &theMesh, const TopoDS_Face &theFace, vector< const StdMeshers_ViscousLayers2D * > &theHyps, vector< TopoDS_Shape > &theAssignedTo)
Returns StdMeshers_ViscousLayers2D for the FACE.
int getEdgesToIgnore (const StdMeshers_ViscousLayers2D *theHyp, const TopoDS_Shape &theFace, const SMESHDS_Mesh *theMesh, set< int > &theEdgeIds)
Returns ids of EDGEs not to create Viscous Layers on.
Typedef Documentation
TGeomID
typedef int VISCOUS_2D::TGeomID
THypVL
typedef StdMeshers_ViscousLayers2D VISCOUS_2D::THypVL
TNode2Edge
typedef map< const SMDS_MeshNode*, _LayerEdge*, TIDCompare > VISCOUS_2D::TNode2Edge
Function Documentation
findHyps()
bool VISCOUS_2D::findHyps (SMESH_Mesh & theMesh, const TopoDS_Face & theFace, vector< const StdMeshers_ViscousLayers2D * > & theHyps, vector< TopoDS_Shape > & theAssignedTo)
Returns StdMeshers_ViscousLayers2D for the FACE.
References findHyps(), SMESH_Mesh::GetHypotheses(), StdMeshers_ViscousLayers2D::GetHypType(), and SMESH_HypoFilter::HasName().
Referenced by StdMeshers_ViscousLayers2D::CheckHypothesis(), StdMeshers_ViscousLayers2D::Compute(), and findHyps().
getEdgesToIgnore()
int VISCOUS_2D::getEdgesToIgnore (const StdMeshers_ViscousLayers2D * theHyp, const TopoDS_Shape & theFace, const SMESHDS_Mesh * theMesh, set< int > & theEdgeIds)
Returns ids of EDGEs not to create Viscous Layers on.
Parameters
[in] theHyp - the hypothesis, holding edges either to ignore or not to.
[in] theFace - the FACE whose EDGEs are checked.
[in] theMesh - the mesh.
[in,out] theEdgeIds - container returning EDGEs to ignore.
Returns
int - number of found EDGEs of the FACE.
References StdMeshers_ViscousLayers::GetBndShapes(), getEdgesToIgnore(), SMESHDS_Mesh::IndexToShape(), SMESH_MesherHelper::IsSubShape(), StdMeshers_ViscousLayers::IsToIgnoreShapes(), and SMESHDS_Mesh::ShapeToIndex().
Referenced by getEdgesToIgnore().