FreeCAD: PartGui::Location Class Reference
PartGui::Location Class Reference
#include <DlgPrimitives.h>
Public Member Functions
Location (QWidget *parent=nullptr, Part::Feature *feature=nullptr)
QString toPlacement () const
~Location ()
Constructor & Destructor Documentation
Location()
Location::Location (QWidget * parent = nullptr, Part::Feature * feature = nullptr)
References Base::Unit::Angle, draftgeoutils.intersections::connect(), Base::Placement::getPosition(), App::PropertyPlacement::getValue(), Base::Unit::Length, App::GeoFeature::Placement, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
~Location()
Location::~Location ()
References PartGui::getViewer(), Gui::SoFCUnifiedSelection::selectionMode, and OfflineRenderingUtils::viewer().
Member Function Documentation
toPlacement()
QString Location::toPlacement () const
References Base::UnitsApi::getDecimals(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/Gui/DlgPrimitives.h
Sources/FreeCAD/src/Mod/Part/Gui/DlgPrimitives.cpp