FreeCAD: femexamples.boxanalysis_static Namespace Reference
femexamples.boxanalysis_static Namespace Reference
Functions
def get_information ()
def init_doc (doc=None)
def setup (doc=None, solvertype="ccxtools")
def setup_base (doc=None, solvertype="ccxtools")
Variables
string mesh_name = "Mesh"
Function Documentation
get_information()
def femexamples.boxanalysis_static.get_information ()
init_doc()
def femexamples.boxanalysis_static.init_doc (doc = None)
Referenced by femexamples.boxanalysis_static.setup_base().
setup()
def femexamples.boxanalysis_static.setup (doc = None, solvertype = "ccxtools")
References ObjectsFem.makeConstraintFixed(), ObjectsFem.makeConstraintForce(), ObjectsFem.makeConstraintPressure(), ObjectsFem.makeEquationElasticity(), ObjectsFem.makeSolverCalculix(), ObjectsFem.makeSolverCalculixCcxTools(), ObjectsFem.makeSolverElmer(), and femexamples.boxanalysis_static.setup_base().
setup_base()
def femexamples.boxanalysis_static.setup_base (doc = None, solvertype = "ccxtools")
References femexamples.boxanalysis_static.init_doc(), ObjectsFem.makeAnalysis(), ObjectsFem.makeMaterialSolid(), and ObjectsFem.makeMeshGmsh().
Referenced by femexamples.boxanalysis_static.setup().
Variable Documentation
mesh_name
string femexamples.boxanalysis_static.mesh_name = "Mesh"