FreeCAD: Robot::Robot6AxisPy Class Reference
Robot::Robot6AxisPy Class Reference
The python export class for Robot6Axis.
#include <Robot6AxisPy.h>
Public Types
typedef Robot6Axis * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Robot6AxisPy (Robot6Axis *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of Robot6AxisPy.
static PyMethodDef Methods []
Methods structure of Robot6AxisPy.
static PyTypeObject Type
Type structure of Robot6AxisPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~Robot6AxisPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * check (PyObject *args)
implementer for the check() method
static PyObject * staticCallback_check (PyObject *self, PyObject *args)
callback for the check() method
callbacks and implementers for the python object attributes
Py::Float getAxis1 (void) const
getter for the Axis1 attribute
void setAxis1 (Py::Float arg)
setter for the Axis1 attribute
Py::Float getAxis2 (void) const
getter for the Axis2 attribute
void setAxis2 (Py::Float arg)
setter for the Axis2 attribute
Py::Float getAxis3 (void) const
getter for the Axis3 attribute
void setAxis3 (Py::Float arg)
setter for the Axis3 attribute
Py::Float getAxis4 (void) const
getter for the Axis4 attribute
void setAxis4 (Py::Float arg)
setter for the Axis4 attribute
Py::Float getAxis5 (void) const
getter for the Axis5 attribute
void setAxis5 (Py::Float arg)
setter for the Axis5 attribute
Py::Float getAxis6 (void) const
getter for the Axis6 attribute
void setAxis6 (Py::Float arg)
setter for the Axis6 attribute
Py::Object getTcp (void) const
getter for the Tcp attribute
void setTcp (Py::Object arg)
setter for the Tcp attribute
Py::Object getBase (void) const
getter for the Base attribute
void setBase (Py::Object arg)
setter for the Base attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Robot6Axis * getRobot6AxisPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getAxis1 (PyObject *self, void *closure)
getter callback for the Axis1 attribute
static int staticCallback_setAxis1 (PyObject *self, PyObject *value, void *closure)
setter callback for the Axis1 attribute
static PyObject * staticCallback_getAxis2 (PyObject *self, void *closure)
getter callback for the Axis2 attribute
static int staticCallback_setAxis2 (PyObject *self, PyObject *value, void *closure)
setter callback for the Axis2 attribute
static PyObject * staticCallback_getAxis3 (PyObject *self, void *closure)
getter callback for the Axis3 attribute
static int staticCallback_setAxis3 (PyObject *self, PyObject *value, void *closure)
setter callback for the Axis3 attribute
static PyObject * staticCallback_getAxis4 (PyObject *self, void *closure)
getter callback for the Axis4 attribute
static int staticCallback_setAxis4 (PyObject *self, PyObject *value, void *closure)
setter callback for the Axis4 attribute
static PyObject * staticCallback_getAxis5 (PyObject *self, void *closure)
getter callback for the Axis5 attribute
static int staticCallback_setAxis5 (PyObject *self, PyObject *value, void *closure)
setter callback for the Axis5 attribute
static PyObject * staticCallback_getAxis6 (PyObject *self, void *closure)
getter callback for the Axis6 attribute
static int staticCallback_setAxis6 (PyObject *self, PyObject *value, void *closure)
setter callback for the Axis6 attribute
static PyObject * staticCallback_getTcp (PyObject *self, void *closure)
getter callback for the Tcp attribute
static int staticCallback_setTcp (PyObject *self, PyObject *value, void *closure)
setter callback for the Tcp attribute
static PyObject * staticCallback_getBase (PyObject *self, void *closure)
getter callback for the Base attribute
static int staticCallback_setBase (PyObject *self, PyObject *value, void *closure)
setter callback for the Base attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Robot6Axis.
Member Typedef Documentation
PointerType
typedef Robot6Axis* Robot::Robot6AxisPy::PointerType
Constructor & Destructor Documentation
~Robot6AxisPy()
Robot6AxisPy::~Robot6AxisPy () protected
Robot6AxisPy()
Robot6AxisPy::Robot6AxisPy (Robot6Axis * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
check()
PyObject * Robot6AxisPy::check (PyObject * args)
implementer for the check() method
Referenced by staticCallback_check().
getAxis1()
Py::Float Robot6AxisPy::getAxis1 (void) const
getter for the Axis1 attribute
References getRobot6AxisPtr().
Referenced by staticCallback_getAxis1().
getAxis2()
Py::Float Robot6AxisPy::getAxis2 (void) const
getter for the Axis2 attribute
References getRobot6AxisPtr().
Referenced by staticCallback_getAxis2().
getAxis3()
Py::Float Robot6AxisPy::getAxis3 (void) const
getter for the Axis3 attribute
References getRobot6AxisPtr().
Referenced by staticCallback_getAxis3().
getAxis4()
Py::Float Robot6AxisPy::getAxis4 (void) const
getter for the Axis4 attribute
References getRobot6AxisPtr().
Referenced by staticCallback_getAxis4().
getAxis5()
Py::Float Robot6AxisPy::getAxis5 (void) const
getter for the Axis5 attribute
References getRobot6AxisPtr().
Referenced by staticCallback_getAxis5().
getAxis6()
Py::Float Robot6AxisPy::getAxis6 (void) const
getter for the Axis6 attribute
References getRobot6AxisPtr().
Referenced by staticCallback_getAxis6().
getBase()
Py::Object Robot6AxisPy::getBase (void) const
getter for the Base attribute
Referenced by staticCallback_getBase().
getCustomAttributes()
PyObject * Robot6AxisPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getRobot6AxisPtr()
Robot6Axis * Robot6AxisPy::getRobot6AxisPtr (void) const
getter for the object handled by this class
Referenced by getAxis1(), getAxis2(), getAxis3(), getAxis4(), getAxis5(), getAxis6(), getTcp(), representation(), setAxis1(), setAxis2(), setAxis3(), setAxis4(), setAxis5(), setAxis6(), and setTcp().
getTcp()
Py::Object Robot6AxisPy::getTcp (void) const
getter for the Tcp attribute
References getRobot6AxisPtr().
Referenced by staticCallback_getTcp().
GetType()
virtual PyTypeObject* Robot::Robot6AxisPy::GetType (void) virtual
Reimplemented from Base::PersistencePy.
PyInit()
int Robot6AxisPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PersistencePy.
PyMake()
PyObject * Robot6AxisPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References Robot6AxisPy().
representation()
std::string Robot6AxisPy::representation (void) const
References Robot::Robot6Axis::getAxis(), Base::Placement::getPosition(), getRobot6AxisPtr(), Robot::Robot6Axis::getTcp(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setAxis1()
void Robot6AxisPy::setAxis1 (Py::Float arg)
setter for the Axis1 attribute
References getRobot6AxisPtr(), and Robot::Robot6Axis::setAxis().
Referenced by staticCallback_setAxis1().
setAxis2()
void Robot6AxisPy::setAxis2 (Py::Float arg)
setter for the Axis2 attribute
References getRobot6AxisPtr(), and Robot::Robot6Axis::setAxis().
Referenced by staticCallback_setAxis2().
setAxis3()
void Robot6AxisPy::setAxis3 (Py::Float arg)
setter for the Axis3 attribute
References getRobot6AxisPtr(), and Robot::Robot6Axis::setAxis().
Referenced by staticCallback_setAxis3().
setAxis4()
void Robot6AxisPy::setAxis4 (Py::Float arg)
setter for the Axis4 attribute
References getRobot6AxisPtr(), and Robot::Robot6Axis::setAxis().
Referenced by staticCallback_setAxis4().
setAxis5()
void Robot6AxisPy::setAxis5 (Py::Float arg)
setter for the Axis5 attribute
References getRobot6AxisPtr(), and Robot::Robot6Axis::setAxis().
Referenced by staticCallback_setAxis5().
setAxis6()
void Robot6AxisPy::setAxis6 (Py::Float arg)
setter for the Axis6 attribute
References getRobot6AxisPtr(), and Robot::Robot6Axis::setAxis().
Referenced by staticCallback_setAxis6().
setBase()
void Robot6AxisPy::setBase (Py::Object arg)
setter for the Base attribute
Referenced by staticCallback_setBase().
setCustomAttributes()
int Robot6AxisPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setTcp()
void Robot6AxisPy::setTcp (Py::Object arg)
setter for the Tcp attribute
References Base::Placement::fromMatrix(), Base::PlacementPy::getPlacementPtr(), getRobot6AxisPtr(), Robot::Robot6Axis::setTo(), Base::MatrixPy::Type, Base::PlacementPy::Type, and Base::MatrixPy::value().
Referenced by staticCallback_setTcp().
staticCallback_check()
PyObject * Robot6AxisPy::staticCallback_check (PyObject * self, PyObject * args) static
callback for the check() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, check(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getAxis1()
PyObject * Robot6AxisPy::staticCallback_getAxis1 (PyObject * self, void * closure) static
getter callback for the Axis1 attribute
References Base::BaseExceptionFreeCADError, getAxis1(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getAxis2()
PyObject * Robot6AxisPy::staticCallback_getAxis2 (PyObject * self, void * closure) static
getter callback for the Axis2 attribute
References Base::BaseExceptionFreeCADError, getAxis2(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getAxis3()
PyObject * Robot6AxisPy::staticCallback_getAxis3 (PyObject * self, void * closure) static
getter callback for the Axis3 attribute
References Base::BaseExceptionFreeCADError, getAxis3(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getAxis4()
PyObject * Robot6AxisPy::staticCallback_getAxis4 (PyObject * self, void * closure) static
getter callback for the Axis4 attribute
References Base::BaseExceptionFreeCADError, getAxis4(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getAxis5()
PyObject * Robot6AxisPy::staticCallback_getAxis5 (PyObject * self, void * closure) static
getter callback for the Axis5 attribute
References Base::BaseExceptionFreeCADError, getAxis5(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getAxis6()
PyObject * Robot6AxisPy::staticCallback_getAxis6 (PyObject * self, void * closure) static
getter callback for the Axis6 attribute
References Base::BaseExceptionFreeCADError, getAxis6(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getBase()
PyObject * Robot6AxisPy::staticCallback_getBase (PyObject * self, void * closure) static
getter callback for the Base attribute
References Base::BaseExceptionFreeCADError, getBase(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTcp()
PyObject * Robot6AxisPy::staticCallback_getTcp (PyObject * self, void * closure) static
getter callback for the Tcp attribute
References Base::BaseExceptionFreeCADError, getTcp(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setAxis1()
int Robot6AxisPy::staticCallback_setAxis1 (PyObject * self, PyObject * value, void * closure) static
setter callback for the Axis1 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setAxis1().
staticCallback_setAxis2()
int Robot6AxisPy::staticCallback_setAxis2 (PyObject * self, PyObject * value, void * closure) static
setter callback for the Axis2 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setAxis2().
staticCallback_setAxis3()
int Robot6AxisPy::staticCallback_setAxis3 (PyObject * self, PyObject * value, void * closure) static
setter callback for the Axis3 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setAxis3().
staticCallback_setAxis4()
int Robot6AxisPy::staticCallback_setAxis4 (PyObject * self, PyObject * value, void * closure) static
setter callback for the Axis4 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setAxis4().
staticCallback_setAxis5()
int Robot6AxisPy::staticCallback_setAxis5 (PyObject * self, PyObject * value, void * closure) static
setter callback for the Axis5 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setAxis5().
staticCallback_setAxis6()
int Robot6AxisPy::staticCallback_setAxis6 (PyObject * self, PyObject * value, void * closure) static
setter callback for the Axis6 attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setAxis6().
staticCallback_setBase()
int Robot6AxisPy::staticCallback_setBase (PyObject * self, PyObject * value, void * closure) static
setter callback for the Base attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setBase().
staticCallback_setTcp()
int Robot6AxisPy::staticCallback_setTcp (PyObject * self, PyObject * value, void * closure) static
setter callback for the Tcp attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setTcp().
Member Data Documentation
GetterSetter
PyGetSetDef Robot6AxisPy::GetterSetter static
Attribute structure of Robot6AxisPy.
Methods
PyMethodDef Robot6AxisPy::Methods static
Initial value:
= {
    {"check",
        reinterpret_cast<PyCFunction>( staticCallback_check ),
        METH_VARARGS,
        "Checks the shape and report errors in the shape structure.\nThis is a more detailed check as done in isValid()."
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of Robot6AxisPy.
Type
PyTypeObject Robot6AxisPy::Type static
Type structure of Robot6AxisPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Robot/App/Robot6AxisPy.h
Sources/FreeCAD/src/Mod/Robot/App/Robot6AxisPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Robot/App/Robot6AxisPy.cpp