FreeCAD: PathScripts.post.slic3r_pre Namespace Reference
PathScripts.post.slic3r_pre Namespace Reference
Functions
def insert (filename, docname)
def open (filename)
def parse (inputstring)
Variables
pythonopen = open
Function Documentation
insert()
def PathScripts.post.slic3r_pre.insert (filename, docname)
References PathScripts.post.slic3r_pre.parse(), and PathScripts.post.slic3r_pre.pythonopen.
Referenced by PathScripts.post.slic3r_pre.open().
open()
def PathScripts.post.slic3r_pre.open (filename)
References PathScripts.post.slic3r_pre.insert().
parse()
def PathScripts.post.slic3r_pre.parse (inputstring)
Referenced by PathScripts.post.slic3r_pre.insert().
Variable Documentation
pythonopen
PathScripts.post.slic3r_pre.pythonopen = open
Referenced by PathScripts.post.slic3r_pre.insert().