FreeCAD: PathScripts.post.jtech_post Namespace Reference
PathScripts.post.jtech_post Namespace Reference
Functions
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
def processArguments (argstring)
Variables
action
string COMMAND_SPACE = " "
default
help
int LINENR = 100
string MACHINE_NAME = "JTECH Photonic Laser"
bool MODAL = False
now = datetime.datetime.now()
bool OUTPUT_COMMENTS = True
tuple OUTPUT_DOUBLES
bool OUTPUT_HEADER = True
bool OUTPUT_LINE_NUMBERS = False
parser = argparse.ArgumentParser(prog="jtech", add_help=False)
string POST_FEED
string POST_OPERATION = """"""
string POSTAMBLE
int POWER_ON_DELAY = 0
string PRE_FEED
string PRE_OPERATION = """"""
string PREAMBLE
int PRECISION = 3
pythonopen = open
bool SHOW_EDITOR = True
string TOOL_CHANGE = """"""
string TOOLTIP
TOOLTIP_ARGS = parser.format_help()
string UNIT_FORMAT = "mm"
string UNIT_SPEED_FORMAT = "mm/min"
string UNITS = "G21"
Function Documentation
export()
def PathScripts.post.jtech_post.export (objectslist, filename, argstring)
References PathScripts.post.jtech_post.linenumber(), PathScripts.post.jtech_post.parse(), PathScripts.post.jtech_post.processArguments(), and PathScripts.post.jtech_post.pythonopen.
linenumber()
def PathScripts.post.jtech_post.linenumber ()
Referenced by PathScripts.post.jtech_post.export(), and PathScripts.post.jtech_post.parse().
parse()
def PathScripts.post.jtech_post.parse (pathobj)
References PathScripts.post.jtech_post.linenumber(), and PathScripts.post.jtech_post.parse().
Referenced by PathScripts.post.jtech_post.export(), and PathScripts.post.jtech_post.parse().
processArguments()
def PathScripts.post.jtech_post.processArguments (argstring)
Referenced by PathScripts.post.jtech_post.export().
Variable Documentation
action
PathScripts.post.jtech_post.action
COMMAND_SPACE
string PathScripts.post.jtech_post.COMMAND_SPACE = " "
default
PathScripts.post.jtech_post.default
help
PathScripts.post.jtech_post.help
LINENR
int PathScripts.post.jtech_post.LINENR = 100
MACHINE_NAME
string PathScripts.post.jtech_post.MACHINE_NAME = "JTECH Photonic Laser"
MODAL
bool PathScripts.post.jtech_post.MODAL = False
now
PathScripts.post.jtech_post.now = datetime.datetime.now()
OUTPUT_COMMENTS
bool PathScripts.post.jtech_post.OUTPUT_COMMENTS = True
OUTPUT_DOUBLES
tuple PathScripts.post.jtech_post.OUTPUT_DOUBLES
Initial value:
=  (
    True  # if false duplicate axis values are suppressed if the same as previous line.
)
OUTPUT_HEADER
bool PathScripts.post.jtech_post.OUTPUT_HEADER = True
OUTPUT_LINE_NUMBERS
bool PathScripts.post.jtech_post.OUTPUT_LINE_NUMBERS = False
parser
PathScripts.post.jtech_post.parser = argparse.ArgumentParser(prog="jtech", add_help=False)
POST_FEED
string PathScripts.post.jtech_post.POST_FEED
Initial value:
=  """M05
"""
POST_OPERATION
string PathScripts.post.jtech_post.POST_OPERATION = """"""
POSTAMBLE
string PathScripts.post.jtech_post.POSTAMBLE
Initial value:
=  """M05 S0
M2
"""
POWER_ON_DELAY
int PathScripts.post.jtech_post.POWER_ON_DELAY = 0
PRE_FEED
string PathScripts.post.jtech_post.PRE_FEED
Initial value:
=  """M03
G4 P{}
"""
PRE_OPERATION
string PathScripts.post.jtech_post.PRE_OPERATION = """"""
PREAMBLE
string PathScripts.post.jtech_post.PREAMBLE
Initial value:
=  """M05 S0
G90
"""
PRECISION
int PathScripts.post.jtech_post.PRECISION = 3
pythonopen
PathScripts.post.jtech_post.pythonopen = open
Referenced by PathScripts.post.jtech_post.export().
SHOW_EDITOR
bool PathScripts.post.jtech_post.SHOW_EDITOR = True
TOOL_CHANGE
string PathScripts.post.jtech_post.TOOL_CHANGE = """"""
TOOLTIP
string PathScripts.post.jtech_post.TOOLTIP
Initial value:
=  """
This is a postprocessor file for the Path workbench. It is used to
take a pseudo-gcode fragment outputted by a Path object, and output
real GCode suitable for a jtech photonics laser. This postprocessor, once placed
in the appropriate PathScripts folder, can be used directly from inside
FreeCAD, via the GUI importer or via python scripts with:
import jtech_post
jtech_post.export(object,"/path/to/file.ngc","")
"""
TOOLTIP_ARGS
PathScripts.post.jtech_post.TOOLTIP_ARGS = parser.format_help()
UNIT_FORMAT
string PathScripts.post.jtech_post.UNIT_FORMAT = "mm"
UNIT_SPEED_FORMAT
string PathScripts.post.jtech_post.UNIT_SPEED_FORMAT = "mm/min"
UNITS
string PathScripts.post.jtech_post.UNITS = "G21"