FreeCAD: SketcherGui::GeometryLayerParameters Class Reference
SketcherGui::GeometryLayerParameters Class Reference
Helper class to store geometry layers configuration.
#include <EditModeCoinManagerParameters.h>
Public Member Functions
GeometryLayerParameters ()
int getCoinLayer (int logicallayer)
void reset ()
Public Attributes
int CoinLayers = 1
Detailed Description
Helper class to store geometry layers configuration.
CoinLayers is the number of * Coin * Geometry Layers. This is not necessarily the number of Geometry layers (logical layers).
Logical layers (as stored in GeometryFacade) define a grouping of geometries. However, this does not mean that they are represented in coin in different layers. Only when there is a reason for such mapping is done so. For example, when the geometry have different drawing parameters.
This means that there may be:
A N:N relationship between logical layers and coin layers.
A M:N relationship between logical layers and coin layers (M<N), including a 1:N relationship.
Constructor & Destructor Documentation
GeometryLayerParameters()
SketcherGui::GeometryLayerParameters::GeometryLayerParameters ()
References reset().
Member Function Documentation
getCoinLayer()
int SketcherGui::GeometryLayerParameters::getCoinLayer (int logicallayer)
Referenced by SketcherGui::EditModeGeometryCoinConverter::convert().
reset()
void SketcherGui::GeometryLayerParameters::reset (void)
References CoinLayers.
Referenced by GeometryLayerParameters(), and draftguitools.gui_trackers.gridTracker::set().
Member Data Documentation
CoinLayers
int SketcherGui::GeometryLayerParameters::CoinLayers = 1
Referenced by SketcherGui::EditModeGeometryCoinConverter::convert(), SketcherGui::EditModeGeometryCoinManager::createEditModeInventorNodes(), SketcherGui::EditModeCoinManager::detectPreselection(), SketcherGui::EditModeGeometryCoinManager::processGeometry(), reset(), SketcherGui::EditModeConstraintCoinManager::updateConstraintColor(), and SketcherGui::EditModeGeometryCoinManager::updateGeometryColor().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.h