FreeCAD: VISCOUS_2D::_SegmentTree Struct Reference
VISCOUS_2D::_SegmentTree Struct Reference
Tree of _Segment's used for a faster search of _Segment's.
Public Types
typedef boost::shared_ptr< _SegmentTree > Ptr
Public Types inherited from SMESH_Quadtree
typedef SMESH_Tree< Bnd_B2d, 4 > TBaseTree
Public Types inherited from SMESH_Tree< Bnd_B2d, 4 >
typedef Bnd_B2d box_type
Public Member Functions
void GetSegmentsNear (const _Segment &seg, vector< const _Segment * > &found)
Return elements which can include the point.
void GetSegmentsNear (const gp_Ax2d &ray, vector< const _Segment * > &found)
Return segments intersecting a ray.
Public Member Functions inherited from SMESH_Quadtree
double maxSize () const
Compute the bigger dimension of my box.
SMESH_Quadtree (SMESH_TreeLimit *limit=0)
Public Member Functions inherited from SMESH_Tree< Bnd_B2d, 4 >
void compute ()
Compute the Tree.
const box_type * getBox () const
int getHeight (const bool full=true) const
Return height of the tree, full or from this level to topest leaf.
bool isLeaf () const
Tell if Tree is a leaf or not An inheriting class can influence it via myIsLeaf protected field.
int level () const
virtual double maxSize () const=0
SMESH_Tree (SMESH_TreeLimit *limit=0)
virtual ~SMESH_Tree ()
SMESH_Tree Destructor.
Protected Member Functions
void buildChildrenData ()
Redistrubute _segments among children.
Bnd_B2d * buildRootBox ()
Return the maximal bnd box.
_SegmentTree * newChild () const
Protected Member Functions inherited from SMESH_Quadtree
virtual Bnd_B2d * newChildBox (int childIndex) const
Allocate a bndbox according to childIndex. childIndex is zero based.
Protected Member Functions inherited from SMESH_Tree< Bnd_B2d, 4 >
void buildChildren ()
Build the children boxes and call buildChildrenData()
virtual void buildChildrenData ()=0
virtual box_type * buildRootBox ()=0
virtual SMESH_Tree * newChild () const=0
virtual box_type * newChildBox (int childIndex) const=0
Additional Inherited Members
Static Public Member Functions inherited from SMESH_Tree< Bnd_B2d, 4 >
static int nbChildren ()
Protected Attributes inherited from SMESH_Tree< Bnd_B2d, 4 >
box_type * myBox
SMESH_Tree ** myChildren
SMESH_Tree * myFather
bool myIsLeaf
int myLevel
const SMESH_TreeLimit * myLimit
Detailed Description
Tree of _Segment's used for a faster search of _Segment's.
Member Typedef Documentation
Ptr
typedef boost::shared_ptr< _SegmentTree > VISCOUS_2D::_SegmentTree::Ptr
Member Function Documentation
buildChildrenData()
void _SegmentTree::buildChildrenData () protected virtual
Redistrubute _segments among children.
Implements SMESH_Tree< Bnd_B2d, 4 >.
References SMESHUtils::FreeVector(), SMESH_Tree< Bnd_B2d, 4 >::getBox(), SMESH_Tree< Bnd_B2d, 4 >::myChildren, SMESH_Tree< BND_BOX, NB_CHILDREN >::myIsLeaf, and SMESH_Tree< Bnd_B2d, 4 >::nbChildren().
buildRootBox()
_SegmentTree::box_type * _SegmentTree::buildRootBox () protected virtual
Return the maximal bnd box.
Implements SMESH_Tree< Bnd_B2d, 4 >.
GetSegmentsNear() [1/2]
void _SegmentTree::GetSegmentsNear (const _Segment & seg, vector< const _Segment * > & found)
Return elements which can include the point.
References SMESH_Tree< Bnd_B2d, 4 >::getBox(), GetSegmentsNear(), SMESH_Tree< Bnd_B2d, 4 >::isLeaf(), SMESH_Tree< Bnd_B2d, 4 >::myChildren, and SMESH_Tree< Bnd_B2d, 4 >::nbChildren().
Referenced by GetSegmentsNear().
GetSegmentsNear() [2/2]
void _SegmentTree::GetSegmentsNear (const gp_Ax2d & ray, vector< const _Segment * > & found)
Return segments intersecting a ray.
References SMESH_Tree< Bnd_B2d, 4 >::getBox(), GetSegmentsNear(), SMESH_Tree< Bnd_B2d, 4 >::isLeaf(), SMESH_Tree< Bnd_B2d, 4 >::myChildren, and SMESH_Tree< Bnd_B2d, 4 >::nbChildren().
newChild()
_SegmentTree * VISCOUS_2D::_SegmentTree::newChild () const protected virtual
Implements SMESH_Tree< Bnd_B2d, 4 >.
The documentation for this struct was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_ViscousLayers2D.cpp