FreeCAD: TechDrawGui::TaskLineDecor Class Reference
TechDrawGui::TaskLineDecor Class Reference
#include <TaskLineDecor.h>
Public Member Functions
virtual bool accept ()
void apply (bool b)
bool apply (void)
virtual bool reject ()
TaskLineDecor (TechDraw::DrawViewPart *partFeat, std::vector< std::string > edgeNames)
~TaskLineDecor ()
Protected Slots
void onColorChanged (void)
void onStyleChanged (void)
void onVisibleChanged (void)
void onWeightChanged (void)
Protected Member Functions
void applyDecorations (void)
void changeEvent (QEvent *e)
void getDefaults (void)
void initUi (void)
Constructor & Destructor Documentation
TaskLineDecor()
TaskLineDecor::TaskLineDecor (TechDraw::DrawViewPart * partFeat, std::vector< std::string > edgeNames)
References draftgeoutils.intersections::connect(), getDefaults(), initUi(), onColorChanged(), onStyleChanged(), onVisibleChanged(), and onWeightChanged().
~TaskLineDecor()
TaskLineDecor::~TaskLineDecor ()
Member Function Documentation
accept()
bool TaskLineDecor::accept (void) virtual
References apply(), applyDecorations(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::Command::Gui, Gui::Application::Instance, and TechDraw::DrawView::requestPaint().
Referenced by TechDrawGui::TaskDlgLineDecor::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
apply() [1/2]
void TechDrawGui::TaskLineDecor::apply (bool b)
apply() [2/2]
bool TechDrawGui::TaskLineDecor::apply (void)
Referenced by accept(), TechDrawGui::TaskRestoreLines::restoreInvisibleCenters(), TechDrawGui::TaskRestoreLines::restoreInvisibleCosmetics(), and TechDrawGui::TaskRestoreLines::restoreInvisibleGeoms().
applyDecorations()
void TaskLineDecor::applyDecorations (void) protected
References TechDraw::CosmeticExtension::addGeomFormat(), TechDraw::CosmeticExtension::getCenterLineBySelection(), TechDraw::CosmeticExtension::getCosmeticEdgeBySelection(), TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::CosmeticExtension::getGeomFormatBySelection(), TechDraw::LineFormat::m_color, TechDraw::CosmeticEdge::m_format, TechDraw::CenterLine::m_format, TechDraw::GeomFormat::m_format, TechDraw::LineFormat::m_style, TechDraw::LineFormat::m_visible, and TechDraw::LineFormat::m_weight.
Referenced by accept(), onColorChanged(), onStyleChanged(), onVisibleChanged(), and onWeightChanged().
changeEvent()
void TaskLineDecor::changeEvent (QEvent * e) protected
getDefaults()
void TaskLineDecor::getDefaults (void) protected
References TechDraw::CosmeticExtension::getCenterLineBySelection(), TechDraw::CosmeticExtension::getCosmeticEdgeBySelection(), TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::CosmeticExtension::getGeomFormatBySelection(), TechDrawGui::QGIView::getViewProvider(), TechDraw::LineFormat::m_color, TechDraw::CosmeticEdge::m_format, TechDraw::CenterLine::m_format, TechDraw::GeomFormat::m_format, TechDraw::LineFormat::m_style, TechDraw::LineFormat::m_visible, and TechDraw::LineFormat::m_weight.
Referenced by TaskLineDecor().
initUi()
void TaskLineDecor::initUi (void) protected
References App::Color::asValue(), Base::Tools::fromStdString(), and App::DocumentObject::getNameInDocument().
Referenced by TaskLineDecor().
onColorChanged
void TaskLineDecor::onColorChanged (void) protected slot
References applyDecorations(), TechDraw::DrawView::requestPaint(), and App::Color::setValue().
Referenced by TaskLineDecor().
onStyleChanged
void TaskLineDecor::onStyleChanged (void) protected slot
References applyDecorations(), and TechDraw::DrawView::requestPaint().
Referenced by TaskLineDecor().
onVisibleChanged
void TaskLineDecor::onVisibleChanged (void) protected slot
References applyDecorations(), and TechDraw::DrawView::requestPaint().
Referenced by TaskLineDecor().
onWeightChanged
void TaskLineDecor::onWeightChanged (void) protected slot
References applyDecorations(), and TechDraw::DrawView::requestPaint().
Referenced by TaskLineDecor().
reject()
bool TaskLineDecor::reject (void) virtual
References Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::Command::Gui, and Gui::Application::Instance.
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), TechDrawGui::TaskDlgLineDecor::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/TaskLineDecor.h
FreeCAD/src/Mod/TechDraw/Gui/TaskLineDecor.cpp