FreeCAD: Fem::FemPostPipelinePy Class Reference
Fem::FemPostPipelinePy Class Reference
The python export class for FemPostPipeline.
#include <FemPostPipelinePy.h>
Public Types
typedef FemPostPipeline * PointerType
Public Types inherited from App::GeoFeaturePy
typedef GeoFeature * PointerType
Public Types inherited from App::DocumentObjectPy
typedef DocumentObject * PointerType
Public Types inherited from App::ExtensionContainerPy
typedef ExtensionContainer * PointerType
Public Types inherited from App::PropertyContainerPy
typedef PropertyContainer * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
FemPostPipelinePy (FemPostPipeline *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
FemPostPipeline * getFemPostPipelinePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from App::GeoFeaturePy
GeoFeaturePy (GeoFeature *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeoFeature * getGeoFeaturePtr (void) const
getter for the object handled by this class
PyObject * getPaths (PyObject *args)
implementer for the getPaths() method
PyObject * getGlobalPlacement (PyObject *args)
implementer for the getGlobalPlacement() method
PyObject * getPropertyNameOfGeometry (PyObject *args)
implementer for the getPropertyNameOfGeometry() method
PyObject * getPropertyOfGeometry (PyObject *args)
implementer for the getPropertyOfGeometry() method
Public Member Functions inherited from App::DocumentObjectPy
DocumentObjectPy (DocumentObject *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * addProperty (PyObject *args)
implementer for the addProperty() method
PyObject * removeProperty (PyObject *args)
implementer for the removeProperty() method
PyObject * supportedProperties (PyObject *args)
implementer for the supportedProperties() method
PyObject * touch (PyObject *args)
implementer for the touch() method
PyObject * purgeTouched (PyObject *args)
implementer for the purgeTouched() method
PyObject * enforceRecompute (PyObject *args)
implementer for the enforceRecompute() method
PyObject * setExpression (PyObject *args)
implementer for the setExpression() method
PyObject * evalExpression (PyObject *args)
implementer for the evalExpression() method
PyObject * recompute (PyObject *args)
implementer for the recompute() method
PyObject * getStatusString (PyObject *args)
implementer for the getStatusString() method
PyObject * isValid (PyObject *args)
implementer for the isValid() method
PyObject * getSubObject (PyObject *args, PyObject *kwd)
implementer for the getSubObject() method
PyObject * getSubObjectList (PyObject *args)
implementer for the getSubObjectList() method
PyObject * getSubObjects (PyObject *args)
implementer for the getSubObjects() method
PyObject * getLinkedObject (PyObject *args, PyObject *kwd)
implementer for the getLinkedObject() method
PyObject * setElementVisible (PyObject *args)
implementer for the setElementVisible() method
PyObject * isElementVisible (PyObject *args)
implementer for the isElementVisible() method
PyObject * hasChildElement (PyObject *args)
implementer for the hasChildElement() method
PyObject * getParentGroup (PyObject *args)
implementer for the getParentGroup() method
PyObject * getParentGeoFeatureGroup (PyObject *args)
implementer for the getParentGeoFeatureGroup() method
PyObject * getPathsByOutList (PyObject *args)
implementer for the getPathsByOutList() method
PyObject * resolve (PyObject *args)
implementer for the resolve() method
PyObject * resolveSubElement (PyObject *args)
implementer for the resolveSubElement() method
PyObject * adjustRelativeLinks (PyObject *args)
implementer for the adjustRelativeLinks() method
Py::List getOutList (void) const
getter for the OutList attribute
Py::List getOutListRecursive (void) const
getter for the OutListRecursive attribute
Py::List getInList (void) const
getter for the InList attribute
Py::List getInListRecursive (void) const
getter for the InListRecursive attribute
Py::String getFullName (void) const
getter for the FullName attribute
Py::String getName (void) const
getter for the Name attribute
Py::Object getDocument (void) const
getter for the Document attribute
Py::List getState (void) const
getter for the State attribute
Py::Object getViewObject (void) const
getter for the ViewObject attribute
Py::Boolean getMustExecute (void) const
getter for the MustExecute attribute
Py::Int getID (void) const
getter for the ID attribute
Py::Boolean getRemoving (void) const
getter for the Removing attribute
Py::List getParents (void) const
getter for the Parents attribute
Py::String getOldLabel (void) const
getter for the OldLabel attribute
Py::Boolean getNoTouch (void) const
getter for the NoTouch attribute
void setNoTouch (Py::Boolean arg)
setter for the NoTouch attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
DocumentObject * getDocumentObjectPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from App::ExtensionContainerPy
ExtensionContainerPy (ExtensionContainer *pcObject, PyTypeObject *T=&Type)
int finalization ()
int initialization ()
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ExtensionContainer * getExtensionContainerPtr (void) const
getter for the object handled by this class
PyObject * addExtension (PyObject *args)
implementer for the addExtension() method
PyObject * hasExtension (PyObject *args)
implementer for the hasExtension() method
Public Member Functions inherited from App::PropertyContainerPy
PropertyContainerPy (PropertyContainer *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getPropertyByName (PyObject *args)
implementer for the getPropertyByName() method
PyObject * getPropertyTouchList (PyObject *args)
implementer for the getPropertyTouchList() method
PyObject * getTypeOfProperty (PyObject *args)
implementer for the getTypeOfProperty() method
PyObject * getTypeIdOfProperty (PyObject *args)
implementer for the getTypeIdOfProperty() method
PyObject * setEditorMode (PyObject *args)
implementer for the setEditorMode() method
PyObject * getEditorMode (PyObject *args)
implementer for the getEditorMode() method
PyObject * getGroupOfProperty (PyObject *args)
implementer for the getGroupOfProperty() method
PyObject * setPropertyStatus (PyObject *args)
implementer for the setPropertyStatus() method
PyObject * getPropertyStatus (PyObject *args)
implementer for the getPropertyStatus() method
PyObject * getDocumentationOfProperty (PyObject *args)
implementer for the getDocumentationOfProperty() method
PyObject * dumpPropertyContent (PyObject *args, PyObject *kwd)
implementer for the dumpPropertyContent() method
PyObject * restorePropertyContent (PyObject *args)
implementer for the restorePropertyContent() method
Py::List getPropertiesList (void) const
getter for the PropertiesList attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
PropertyContainer * getPropertyContainerPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::GeoFeaturePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_getPaths (PyObject *self, PyObject *args)
callback for the getPaths() method
static PyObject * staticCallback_getGlobalPlacement (PyObject *self, PyObject *args)
callback for the getGlobalPlacement() method
static PyObject * staticCallback_getPropertyNameOfGeometry (PyObject *self, PyObject *args)
callback for the getPropertyNameOfGeometry() method
static PyObject * staticCallback_getPropertyOfGeometry (PyObject *self, PyObject *args)
callback for the getPropertyOfGeometry() method
Static Public Member Functions inherited from App::DocumentObjectPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_addProperty (PyObject *self, PyObject *args)
callback for the addProperty() method
static PyObject * staticCallback_removeProperty (PyObject *self, PyObject *args)
callback for the removeProperty() method
static PyObject * staticCallback_supportedProperties (PyObject *self, PyObject *args)
callback for the supportedProperties() method
static PyObject * staticCallback_touch (PyObject *self, PyObject *args)
callback for the touch() method
static PyObject * staticCallback_purgeTouched (PyObject *self, PyObject *args)
callback for the purgeTouched() method
static PyObject * staticCallback_enforceRecompute (PyObject *self, PyObject *args)
callback for the enforceRecompute() method
static PyObject * staticCallback_setExpression (PyObject *self, PyObject *args)
callback for the setExpression() method
static PyObject * staticCallback_evalExpression (PyObject *self, PyObject *args)
callback for the evalExpression() method
static PyObject * staticCallback_recompute (PyObject *self, PyObject *args)
callback for the recompute() method
static PyObject * staticCallback_getStatusString (PyObject *self, PyObject *args)
callback for the getStatusString() method
static PyObject * staticCallback_isValid (PyObject *self, PyObject *args)
callback for the isValid() method
static PyObject * staticCallback_getSubObject (PyObject *self, PyObject *args, PyObject *kwd)
callback for the getSubObject() method
static PyObject * staticCallback_getSubObjectList (PyObject *self, PyObject *args)
callback for the getSubObjectList() method
static PyObject * staticCallback_getSubObjects (PyObject *self, PyObject *args)
callback for the getSubObjects() method
static PyObject * staticCallback_getLinkedObject (PyObject *self, PyObject *args, PyObject *kwd)
callback for the getLinkedObject() method
static PyObject * staticCallback_setElementVisible (PyObject *self, PyObject *args)
callback for the setElementVisible() method
static PyObject * staticCallback_isElementVisible (PyObject *self, PyObject *args)
callback for the isElementVisible() method
static PyObject * staticCallback_hasChildElement (PyObject *self, PyObject *args)
callback for the hasChildElement() method
static PyObject * staticCallback_getParentGroup (PyObject *self, PyObject *args)
callback for the getParentGroup() method
static PyObject * staticCallback_getParentGeoFeatureGroup (PyObject *self, PyObject *args)
callback for the getParentGeoFeatureGroup() method
static PyObject * staticCallback_getPathsByOutList (PyObject *self, PyObject *args)
callback for the getPathsByOutList() method
static PyObject * staticCallback_resolve (PyObject *self, PyObject *args)
callback for the resolve() method
static PyObject * staticCallback_resolveSubElement (PyObject *self, PyObject *args)
callback for the resolveSubElement() method
static PyObject * staticCallback_adjustRelativeLinks (PyObject *self, PyObject *args)
callback for the adjustRelativeLinks() method
static PyObject * staticCallback_getOutList (PyObject *self, void *closure)
getter callback for the OutList attribute
static int staticCallback_setOutList (PyObject *self, PyObject *value, void *closure)
setter callback for the OutList attribute
static PyObject * staticCallback_getOutListRecursive (PyObject *self, void *closure)
getter callback for the OutListRecursive attribute
static int staticCallback_setOutListRecursive (PyObject *self, PyObject *value, void *closure)
setter callback for the OutListRecursive attribute
static PyObject * staticCallback_getInList (PyObject *self, void *closure)
getter callback for the InList attribute
static int staticCallback_setInList (PyObject *self, PyObject *value, void *closure)
setter callback for the InList attribute
static PyObject * staticCallback_getInListRecursive (PyObject *self, void *closure)
getter callback for the InListRecursive attribute
static int staticCallback_setInListRecursive (PyObject *self, PyObject *value, void *closure)
setter callback for the InListRecursive attribute
static PyObject * staticCallback_getFullName (PyObject *self, void *closure)
getter callback for the FullName attribute
static int staticCallback_setFullName (PyObject *self, PyObject *value, void *closure)
setter callback for the FullName attribute
static PyObject * staticCallback_getName (PyObject *self, void *closure)
getter callback for the Name attribute
static int staticCallback_setName (PyObject *self, PyObject *value, void *closure)
setter callback for the Name attribute
static PyObject * staticCallback_getDocument (PyObject *self, void *closure)
getter callback for the Document attribute
static int staticCallback_setDocument (PyObject *self, PyObject *value, void *closure)
setter callback for the Document attribute
static PyObject * staticCallback_getState (PyObject *self, void *closure)
getter callback for the State attribute
static int staticCallback_setState (PyObject *self, PyObject *value, void *closure)
setter callback for the State attribute
static PyObject * staticCallback_getViewObject (PyObject *self, void *closure)
getter callback for the ViewObject attribute
static int staticCallback_setViewObject (PyObject *self, PyObject *value, void *closure)
setter callback for the ViewObject attribute
static PyObject * staticCallback_getMustExecute (PyObject *self, void *closure)
getter callback for the MustExecute attribute
static int staticCallback_setMustExecute (PyObject *self, PyObject *value, void *closure)
setter callback for the MustExecute attribute
static PyObject * staticCallback_getID (PyObject *self, void *closure)
getter callback for the ID attribute
static int staticCallback_setID (PyObject *self, PyObject *value, void *closure)
setter callback for the ID attribute
static PyObject * staticCallback_getRemoving (PyObject *self, void *closure)
getter callback for the Removing attribute
static int staticCallback_setRemoving (PyObject *self, PyObject *value, void *closure)
setter callback for the Removing attribute
static PyObject * staticCallback_getParents (PyObject *self, void *closure)
getter callback for the Parents attribute
static int staticCallback_setParents (PyObject *self, PyObject *value, void *closure)
setter callback for the Parents attribute
static PyObject * staticCallback_getOldLabel (PyObject *self, void *closure)
getter callback for the OldLabel attribute
static int staticCallback_setOldLabel (PyObject *self, PyObject *value, void *closure)
setter callback for the OldLabel attribute
static PyObject * staticCallback_getNoTouch (PyObject *self, void *closure)
getter callback for the NoTouch attribute
static int staticCallback_setNoTouch (PyObject *self, PyObject *value, void *closure)
setter callback for the NoTouch attribute
Static Public Member Functions inherited from App::ExtensionContainerPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_addExtension (PyObject *self, PyObject *args)
callback for the addExtension() method
static PyObject * staticCallback_hasExtension (PyObject *self, PyObject *args)
callback for the hasExtension() method
Static Public Member Functions inherited from App::PropertyContainerPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_getPropertyByName (PyObject *self, PyObject *args)
callback for the getPropertyByName() method
static PyObject * staticCallback_getPropertyTouchList (PyObject *self, PyObject *args)
callback for the getPropertyTouchList() method
static PyObject * staticCallback_getTypeOfProperty (PyObject *self, PyObject *args)
callback for the getTypeOfProperty() method
static PyObject * staticCallback_getTypeIdOfProperty (PyObject *self, PyObject *args)
callback for the getTypeIdOfProperty() method
static PyObject * staticCallback_setEditorMode (PyObject *self, PyObject *args)
callback for the setEditorMode() method
static PyObject * staticCallback_getEditorMode (PyObject *self, PyObject *args)
callback for the getEditorMode() method
static PyObject * staticCallback_getGroupOfProperty (PyObject *self, PyObject *args)
callback for the getGroupOfProperty() method
static PyObject * staticCallback_setPropertyStatus (PyObject *self, PyObject *args)
callback for the setPropertyStatus() method
static PyObject * staticCallback_getPropertyStatus (PyObject *self, PyObject *args)
callback for the getPropertyStatus() method
static PyObject * staticCallback_getDocumentationOfProperty (PyObject *self, PyObject *args)
callback for the getDocumentationOfProperty() method
static PyObject * staticCallback_dumpPropertyContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpPropertyContent() method
static PyObject * staticCallback_restorePropertyContent (PyObject *self, PyObject *args)
callback for the restorePropertyContent() method
static PyObject * staticCallback_getPropertiesList (PyObject *self, void *closure)
getter callback for the PropertiesList attribute
static int staticCallback_setPropertiesList (PyObject *self, PyObject *value, void *closure)
setter callback for the PropertiesList attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of FemPostPipelinePy.
static PyMethodDef Methods []
Methods structure of FemPostPipelinePy.
static PyTypeObject Type
Type structure of FemPostPipelinePy.
Static Public Attributes inherited from App::GeoFeaturePy
static PyGetSetDef GetterSetter []
Attribute structure of GeoFeaturePy.
static PyMethodDef Methods []
Methods structure of GeoFeaturePy.
static PyTypeObject Type
Type structure of GeoFeaturePy.
Static Public Attributes inherited from App::DocumentObjectPy
static PyGetSetDef GetterSetter []
Attribute structure of DocumentObjectPy.
static PyMethodDef Methods []
Methods structure of DocumentObjectPy.
static PyTypeObject Type
Type structure of DocumentObjectPy.
Static Public Attributes inherited from App::ExtensionContainerPy
static PyGetSetDef GetterSetter []
Attribute structure of ExtensionContainerPy.
static PyMethodDef Methods []
Methods structure of ExtensionContainerPy.
static PyTypeObject Type
Type structure of ExtensionContainerPy.
Static Public Attributes inherited from App::PropertyContainerPy
static PyGetSetDef GetterSetter []
Attribute structure of PropertyContainerPy.
static PyMethodDef Methods []
Methods structure of PropertyContainerPy.
static PyTypeObject Type
Type structure of PropertyContainerPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~FemPostPipelinePy ()
Protected Member Functions inherited from App::GeoFeaturePy
~GeoFeaturePy ()
Protected Member Functions inherited from App::DocumentObjectPy
~DocumentObjectPy ()
Protected Member Functions inherited from App::ExtensionContainerPy
~ExtensionContainerPy ()
Protected Member Functions inherited from App::PropertyContainerPy
~PropertyContainerPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * read (PyObject *args)
implementer for the read() method
PyObject * load (PyObject *args)
implementer for the load() method
PyObject * getLastPostObject (PyObject *args)
implementer for the getLastPostObject() method
PyObject * holdsPostObject (PyObject *args)
implementer for the holdsPostObject() method
static PyObject * staticCallback_read (PyObject *self, PyObject *args)
callback for the read() method
static PyObject * staticCallback_load (PyObject *self, PyObject *args)
callback for the load() method
static PyObject * staticCallback_getLastPostObject (PyObject *self, PyObject *args)
callback for the getLastPostObject() method
static PyObject * staticCallback_holdsPostObject (PyObject *self, PyObject *args)
callback for the holdsPostObject() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for FemPostPipeline.
Member Typedef Documentation
PointerType
typedef FemPostPipeline* Fem::FemPostPipelinePy::PointerType
Constructor & Destructor Documentation
~FemPostPipelinePy()
FemPostPipelinePy::~FemPostPipelinePy () protected
FemPostPipelinePy()
FemPostPipelinePy::FemPostPipelinePy (FemPostPipeline * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
getCustomAttributes()
PyObject * FemPostPipelinePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getFemPostPipelinePtr()
FemPostPipeline * FemPostPipelinePy::getFemPostPipelinePtr (void) const
getter for the object handled by this class
Referenced by getLastPostObject(), holdsPostObject(), load(), and read().
getLastPostObject()
PyObject * FemPostPipelinePy::getLastPostObject (PyObject * args)
implementer for the getLastPostObject() method
References getFemPostPipelinePtr(), Fem::FemPostPipeline::getLastPostObject(), and App::GeoFeature::getPyObject().
Referenced by staticCallback_getLastPostObject().
GetType()
virtual PyTypeObject* Fem::FemPostPipelinePy::GetType (void) virtual
Reimplemented from App::GeoFeaturePy.
holdsPostObject()
PyObject * FemPostPipelinePy::holdsPostObject (PyObject * args)
implementer for the holdsPostObject() method
References Base::Persistence::getClassTypeId(), App::DocumentObjectPy::getDocumentObjectPtr(), getFemPostPipelinePtr(), Fem::FemPostPipeline::holdsPostObject(), and App::DocumentObjectPy::Type.
Referenced by staticCallback_holdsPostObject().
load()
PyObject * FemPostPipelinePy::load (PyObject * args)
implementer for the load() method
References Base::Persistence::getClassTypeId(), App::DocumentObjectPy::getDocumentObjectPtr(), getFemPostPipelinePtr(), Fem::FemPostPipeline::load(), and App::DocumentObjectPy::Type.
Referenced by staticCallback_load().
PyInit()
int FemPostPipelinePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from App::GeoFeaturePy.
PyMake()
PyObject * FemPostPipelinePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
read()
PyObject * FemPostPipelinePy::read (PyObject * args)
implementer for the read() method
References getFemPostPipelinePtr(), and Fem::FemPostPipeline::read().
Referenced by gzip_utf8.GzipFile::readline(), gzip_utf8.GzipFile::seek(), and staticCallback_read().
representation()
std::string FemPostPipelinePy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int FemPostPipelinePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_getLastPostObject()
PyObject * FemPostPipelinePy::staticCallback_getLastPostObject (PyObject * self, PyObject * args) static
callback for the getLastPostObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getLastPostObject(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_holdsPostObject()
PyObject * FemPostPipelinePy::staticCallback_holdsPostObject (PyObject * self, PyObject * args) static
callback for the holdsPostObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, holdsPostObject(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_load()
PyObject * FemPostPipelinePy::staticCallback_load (PyObject * self, PyObject * args) static
callback for the load() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), load(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_read()
PyObject * FemPostPipelinePy::staticCallback_read (PyObject * self, PyObject * args) static
callback for the read() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), read(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef FemPostPipelinePy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of FemPostPipelinePy.
Methods
PyMethodDef FemPostPipelinePy::Methods static
Initial value:
= {
    {"read",
        reinterpret_cast<PyCFunction>( staticCallback_read ),
        METH_VARARGS,
        "Read in vtk file"
    },
    {"load",
        reinterpret_cast<PyCFunction>( staticCallback_load ),
        METH_VARARGS,
        "Load a result object"
    },
    {"getLastPostObject",
        reinterpret_cast<PyCFunction>( staticCallback_getLastPostObject ),
        METH_VARARGS,
        "Get the last post-processing object"
    },
    {"holdsPostObject",
        reinterpret_cast<PyCFunction>( staticCallback_holdsPostObject ),
        METH_VARARGS,
        "Check if this pipeline holds a given post-processing object"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of FemPostPipelinePy.
Type
PyTypeObject FemPostPipelinePy::Type static
Type structure of FemPostPipelinePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Fem/App/FemPostPipelinePy.h
Sources/FreeCAD/src/Mod/Fem/App/FemPostPipelinePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Fem/App/FemPostPipelinePy.cpp