FreeCAD: FemGui::Ui_DlgSettingsFemMaterialImp Class Reference
FemGui::Ui_DlgSettingsFemMaterialImp Class Reference
#include <ui_DlgSettingsFemMaterial.h>
Public Member Functions
void retranslateUi (QWidget *FemGui__DlgSettingsFemMaterialImp)
void setupUi (QWidget *FemGui__DlgSettingsFemMaterialImp)
Public Attributes
Gui::PrefCheckBox * cb_delete_duplicates
Gui::PrefCheckBox * cb_sort_by_resources
Gui::PrefCheckBox * cb_use_built_in_materials
Gui::PrefCheckBox * cb_use_mat_from_config_dir
Gui::PrefCheckBox * cb_use_mat_from_custom_dir
Gui::PrefFileChooser * fc_custom_mat_dir
QGroupBox * gb_4_materials
QGroupBox * gb_4_materials_2
QGridLayout * gridLayout
QLabel * l_custom_mat_dir
QVBoxLayout * verticalLayout
QVBoxLayout * verticalLayout_2
QVBoxLayout * verticalLayout_3
QVBoxLayout * verticalLayout_6
QSpacerItem * verticalSpacer
Member Function Documentation
retranslateUi()
void FemGui::Ui_DlgSettingsFemMaterialImp::retranslateUi (QWidget * FemGui__DlgSettingsFemMaterialImp)
References cb_delete_duplicates, cb_sort_by_resources, cb_use_built_in_materials, cb_use_mat_from_config_dir, cb_use_mat_from_custom_dir, gb_4_materials, gb_4_materials_2, l_custom_mat_dir, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void FemGui::Ui_DlgSettingsFemMaterialImp::setupUi (QWidget * FemGui__DlgSettingsFemMaterialImp)
References cb_delete_duplicates, cb_sort_by_resources, cb_use_built_in_materials, cb_use_mat_from_config_dir, cb_use_mat_from_custom_dir, draftgeoutils.intersections::connect(), Gui::FileChooser::Directory, fc_custom_mat_dir, gb_4_materials, gb_4_materials_2, gridLayout, l_custom_mat_dir, retranslateUi(), Gui::FileChooser::setMode(), verticalLayout, verticalLayout_2, verticalLayout_3, verticalLayout_6, and verticalSpacer.
Member Data Documentation
cb_delete_duplicates
Gui::PrefCheckBox* FemGui::Ui_DlgSettingsFemMaterialImp::cb_delete_duplicates
Referenced by retranslateUi(), and setupUi().
cb_sort_by_resources
Gui::PrefCheckBox* FemGui::Ui_DlgSettingsFemMaterialImp::cb_sort_by_resources
Referenced by retranslateUi(), and setupUi().
cb_use_built_in_materials
Gui::PrefCheckBox* FemGui::Ui_DlgSettingsFemMaterialImp::cb_use_built_in_materials
Referenced by retranslateUi(), and setupUi().
cb_use_mat_from_config_dir
Gui::PrefCheckBox* FemGui::Ui_DlgSettingsFemMaterialImp::cb_use_mat_from_config_dir
Referenced by retranslateUi(), and setupUi().
cb_use_mat_from_custom_dir
Gui::PrefCheckBox* FemGui::Ui_DlgSettingsFemMaterialImp::cb_use_mat_from_custom_dir
Referenced by retranslateUi(), and setupUi().
fc_custom_mat_dir
Gui::PrefFileChooser* FemGui::Ui_DlgSettingsFemMaterialImp::fc_custom_mat_dir
Referenced by setupUi().
gb_4_materials
QGroupBox* FemGui::Ui_DlgSettingsFemMaterialImp::gb_4_materials
Referenced by retranslateUi(), and setupUi().
gb_4_materials_2
QGroupBox* FemGui::Ui_DlgSettingsFemMaterialImp::gb_4_materials_2
Referenced by retranslateUi(), and setupUi().
gridLayout
QGridLayout* FemGui::Ui_DlgSettingsFemMaterialImp::gridLayout
Referenced by setupUi().
l_custom_mat_dir
QLabel* FemGui::Ui_DlgSettingsFemMaterialImp::l_custom_mat_dir
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* FemGui::Ui_DlgSettingsFemMaterialImp::verticalLayout
Referenced by setupUi().
verticalLayout_2
QVBoxLayout* FemGui::Ui_DlgSettingsFemMaterialImp::verticalLayout_2
Referenced by setupUi().
verticalLayout_3
QVBoxLayout* FemGui::Ui_DlgSettingsFemMaterialImp::verticalLayout_3
Referenced by setupUi().
verticalLayout_6
QVBoxLayout* FemGui::Ui_DlgSettingsFemMaterialImp::verticalLayout_6
Referenced by setupUi().
verticalSpacer
QSpacerItem* FemGui::Ui_DlgSettingsFemMaterialImp::verticalSpacer
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Fem/Gui/ui_DlgSettingsFemMaterial.h