FreeCAD: Gui::TreeWidgetEditDelegate Class Reference
Gui::TreeWidgetEditDelegate Class Reference
TreeWidget item delegate for editing.
#include <Tree.h>
Public Member Functions
virtual QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &, const QModelIndex &index) const
TreeWidgetEditDelegate (QObject *parent=0)
Detailed Description
TreeWidget item delegate for editing.
Constructor & Destructor Documentation
TreeWidgetEditDelegate()
TreeWidgetEditDelegate::TreeWidgetEditDelegate (QObject * parent = 0)
Member Function Documentation
createEditor()
QWidget * TreeWidgetEditDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & , const QModelIndex & index) const virtual
References Gui::ExpLineEdit::bind(), App::GetApplication(), Gui::ViewProviderDocumentObject::getObject(), App::DocumentObject::Label2, Gui::DocumentObjectItem::object(), Gui::TreeWidget::ObjectType, App::Application::setActiveTransaction(), and Gui::ExpressionBinding::setAutoApply().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Tree.h
Sources/FreeCAD/src/Gui/Tree.cpp