FreeCAD: TechDraw::Vertex Class Reference
TechDraw::Vertex Class Reference
#include <Geometry.h>
Public Member Functions
virtual void dump (const char *title="")
boost::uuids::uuid getTag () const
virtual std::string getTagAsString (void) const
bool isEqual (const Vertex &v, double tol)
void point (Base::Vector3d v)
Base::Vector3d point (void) const
virtual void Restore (Base::XMLReader &)
virtual void Save (Base::Writer &) const
Vertex ()
Vertex (Base::Vector3d v)
Vertex (const Vertex *v)
Vertex (double x, double y)
double x ()
double y ()
virtual ~Vertex ()
Public Attributes
bool cosmetic
int cosmeticLink
std::string cosmeticTag
ExtractionType extractType
bool hlrVisible
bool isCenter
TopoDS_Vertex occVertex
Base::Vector3d pnt
int ref3D
bool reference
Protected Member Functions
void assignTag (const TechDraw::Vertex *v)
void createNewTag ()
Protected Attributes
boost::uuids::uuid tag
Constructor & Destructor Documentation
Vertex() [1/4]
Vertex::Vertex ()
References cosmetic, cosmeticLink, cosmeticTag, createNewTag(), extractType, hlrVisible, isCenter, occVertex, pnt, ref3D, and reference.
Vertex() [2/4]
Vertex::Vertex (const Vertex * v)
References cosmetic, cosmeticLink, cosmeticTag, createNewTag(), extractType, hlrVisible, isCenter, occVertex, pnt, ref3D, and reference.
Vertex() [3/4]
Vertex::Vertex (double x, double y)
References cosmetic, cosmeticLink, cosmeticTag, createNewTag(), extractType, hlrVisible, isCenter, occVertex, pnt, ref3D, and reference.
Vertex() [4/4]
Vertex::Vertex (Base::Vector3d v)
~Vertex()
virtual TechDraw::Vertex::~Vertex () virtual
Member Function Documentation
assignTag()
void TechDraw::Vertex::assignTag (const TechDraw::Vertex * v) protected
createNewTag()
void Vertex::createNewTag () protected
References tag.
Referenced by Vertex().
dump()
void Vertex::dump (const char * title = "") virtual
Reimplemented in TechDraw::CosmeticVertex.
References Base::Console(), cosmetic, cosmeticLink, cosmeticTag, TechDraw::DrawUtil::formatVector(), hlrVisible, Base::ConsoleSingleton::Message(), and pnt.
getTag()
boost::uuids::uuid Vertex::getTag () const
References tag.
Referenced by getTagAsString().
getTagAsString()
std::string Vertex::getTagAsString (void) const virtual
Reimplemented in TechDraw::CosmeticVertex.
References getTag().
Referenced by Save().
isEqual()
bool Vertex::isEqual (const Vertex & v, double tol)
References DraftVecUtils::dist(), and pnt.
point() [1/2]
void TechDraw::Vertex::point (Base::Vector3d v)
Referenced by draftguitools.gui_arcs.Arc::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_shapestrings.ShapeString::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_split.Split::action(), draftguitools.gui_texts.Text::action(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_circulararray.CircularArray::click(), draftguitools.gui_orthoarray.OrthoArray::click(), draftguitools.gui_points.Point::click(), draftguitools.gui_polararray.PolarArray::click(), PathScripts.PathGetPoint.TaskPanel::getPoint(), draftguitools.gui_scale.Scale::handle_mouse_click_event(), draftguitools.gui_move.Move::handle_mouse_click_event(), draftguitools.gui_rotate.Rotate::handle_mouse_click_event(), draftguitools.gui_move.Move::handle_mouse_move_event(), draftguitools.gui_rotate.Rotate::handle_mouse_move_event(), draftguitools.gui_scale.Scale::handle_mouse_move_event(), draftguitools.gui_circulararray.CircularArray::move(), draftguitools.gui_points.Point::move(), draftguitools.gui_polararray.PolarArray::move(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_points.Point::numericInput(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_rotate.Rotate::set_center(), draftguitools.gui_dimensions.Dimension::set_constraint_node(), draftguitools.gui_rotate.Rotate::set_rotation_angle(), draftguitools.gui_trimex.Trimex::trimObject(), and PathScripts.PathGetPoint.TaskPanel::updatePoint().
point() [2/2]
Base::Vector3d TechDraw::Vertex::point (void) const
References Base::Vector3< _Precision >::x, and Base::Vector3< _Precision >::y.
Referenced by draftguitools.gui_arcs.Arc::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_shapestrings.ShapeString::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_split.Split::action(), draftguitools.gui_texts.Text::action(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_circulararray.CircularArray::click(), draftguitools.gui_orthoarray.OrthoArray::click(), draftguitools.gui_points.Point::click(), draftguitools.gui_polararray.PolarArray::click(), PathScripts.PathGetPoint.TaskPanel::getPoint(), draftguitools.gui_scale.Scale::handle_mouse_click_event(), draftguitools.gui_move.Move::handle_mouse_click_event(), draftguitools.gui_rotate.Rotate::handle_mouse_click_event(), draftguitools.gui_move.Move::handle_mouse_move_event(), draftguitools.gui_rotate.Rotate::handle_mouse_move_event(), draftguitools.gui_scale.Scale::handle_mouse_move_event(), draftguitools.gui_circulararray.CircularArray::move(), draftguitools.gui_points.Point::move(), draftguitools.gui_polararray.PolarArray::move(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_points.Point::numericInput(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_rotate.Rotate::set_center(), draftguitools.gui_dimensions.Dimension::set_constraint_node(), draftguitools.gui_rotate.Rotate::set_rotation_angle(), TechDraw::CosmeticVertex::toString(), draftguitools.gui_trimex.Trimex::trimObject(), and PathScripts.PathGetPoint.TaskPanel::updatePoint().
Restore()
void Vertex::Restore (Base::XMLReader & reader) virtual
Reimplemented in TechDraw::CosmeticVertex.
References cosmetic, cosmeticLink, cosmeticTag, extractType, Base::XMLReader::getAttribute(), Base::XMLReader::getAttributeAsFloat(), Base::XMLReader::getAttributeAsInteger(), hlrVisible, occVertex, pnt, Base::XMLReader::readElement(), ref3D, tag, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by TechDraw::CosmeticVertex::Restore().
Save()
void Vertex::Save (Base::Writer & writer) const virtual
Reimplemented in TechDraw::CosmeticVertex.
References cosmetic, cosmeticLink, cosmeticTag, extractType, getTagAsString(), hlrVisible, Base::Writer::ind(), isCenter, pnt, ref3D, Base::Writer::Stream(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by TechDraw::CosmeticVertex::Save().
x()
double TechDraw::Vertex::x ()
References Base::Vector3< _Precision >::x.
Referenced by Mod.PartDesign.Scripts.FilletArc.Vector::add(), DraftGui.DraftToolBar::changeXValue(), importSVG.svgHandler::characters(), PathScripts.PathInspect.GCodeEditorDialog::cleanup(), Mod.PartDesign.Scripts.FilletArc.Vector::cross(), PathScripts.PostUtils.GCodeEditorDialog::done(), Mod.PartDesign.Scripts.FilletArc.Vector::dot(), Mod.PartDesign.Scripts.FilletArc.Vector::length(), Mod.PartDesign.Scripts.FilletArc.Vector::mult(), Mod.PartDesign.Scripts.FilletArc.Vector::norm(), PathScripts.PathDressupHoldingTags.Tag::originAt(), DraftGui.DraftToolBar::pointUi(), DraftGui.DraftToolBar::reset_ui_values(), Mod.PartDesign.Scripts.FilletArc.Vector::sub(), DraftGui.DraftToolBar::update_cartesian_coords(), DraftGui.DraftToolBar::update_spherical_coords(), DraftGui.DraftToolBar::updateSnapper(), DraftGui.DraftToolBar::validatePoint(), and automotive_design.right_angular_wedge::wr1().
y()
double TechDraw::Vertex::y ()
References Base::Vector3< _Precision >::y.
Referenced by Mod.PartDesign.Scripts.FilletArc.Vector::add(), DraftGui.DraftToolBar::changeYValue(), importSVG.svgHandler::characters(), PathScripts.PathInspect.GCodeEditorDialog::cleanup(), Mod.PartDesign.Scripts.FilletArc.Vector::cross(), PathScripts.PostUtils.GCodeEditorDialog::done(), Mod.PartDesign.Scripts.FilletArc.Vector::dot(), Mod.PartDesign.Scripts.FilletArc.Vector::length(), Mod.PartDesign.Scripts.FilletArc.Vector::mult(), Mod.PartDesign.Scripts.FilletArc.Vector::norm(), PathScripts.PathDressupHoldingTags.Tag::originAt(), DraftGui.DraftToolBar::pointUi(), DraftGui.DraftToolBar::reset_ui_values(), Mod.PartDesign.Scripts.FilletArc.Vector::sub(), DraftGui.DraftToolBar::update_cartesian_coords(), DraftGui.DraftToolBar::update_spherical_coords(), DraftGui.DraftToolBar::updateSnapper(), and DraftGui.DraftToolBar::validatePoint().
Member Data Documentation
cosmetic
bool TechDraw::Vertex::cosmetic
Referenced by TechDraw::CosmeticVertex::CosmeticVertex(), dump(), Restore(), Save(), and Vertex().
cosmeticLink
int TechDraw::Vertex::cosmeticLink
Referenced by dump(), Restore(), Save(), and Vertex().
cosmeticTag
std::string TechDraw::Vertex::cosmeticTag
Referenced by dump(), Restore(), Save(), and Vertex().
extractType
ExtractionType TechDraw::Vertex::extractType
Referenced by Restore(), Save(), and Vertex().
hlrVisible
bool TechDraw::Vertex::hlrVisible
Referenced by TechDraw::CosmeticVertex::CosmeticVertex(), dump(), Restore(), Save(), and Vertex().
isCenter
bool TechDraw::Vertex::isCenter
Referenced by Save(), and Vertex().
occVertex
TopoDS_Vertex TechDraw::Vertex::occVertex
Referenced by Restore(), and Vertex().
pnt
Base::Vector3d TechDraw::Vertex::pnt
Referenced by dump(), isEqual(), Restore(), Save(), TechDraw::CosmeticVertex::scaled(), and Vertex().
ref3D
int TechDraw::Vertex::ref3D
Referenced by Restore(), Save(), and Vertex().
reference
bool TechDraw::Vertex::reference
Referenced by Vertex().
tag
boost::uuids::uuid TechDraw::Vertex::tag protected
Referenced by PathScripts.PathDressupHoldingTags.MapWireToTag::add(), PathScripts.PathDressupHoldingTags.MapWireToTag::cleanupEdges(), PathScripts.PathDressupHoldingTags.MapWireToTag::commandsForEdges(), createNewTag(), Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.ChunkBase::dump_header(), getTag(), ArchPanel.PanelCut::getWires(), Restore(), PathScripts.PathDressupHoldingTags.MapWireToTag::shell(), and FreeCADInit.FCADLogger::trace().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/App/Geometry.h
FreeCAD/src/Mod/TechDraw/App/Geometry.cpp