FreeCAD: GCS::ConstraintPointOnEllipse Class Reference
GCS::ConstraintPointOnEllipse Class Reference
#include <Constraints.h>
Public Member Functions
ConstraintPointOnEllipse (Point &p, ArcOfEllipse &a)
ConstraintPointOnEllipse (Point &p, Ellipse &e)
virtual double error ()
virtual ConstraintType getTypeId ()
virtual double grad (double *)
virtual void rescale (double coef=1.)
Public Member Functions inherited from GCS::Constraint
Constraint ()
int findParamInPvec (double *param)
int getTag ()
bool isDriving () const
virtual double maxStep (MAP_pD_D &dir, double lim=1.)
VEC_pD params ()
void redirectParams (MAP_pD_pD redirectionmap)
void revertParams ()
void setDriving (bool isdriving)
void setTag (int tagId)
virtual ~Constraint ()
Constructor & Destructor Documentation
ConstraintPointOnEllipse() [1/2]
GCS::ConstraintPointOnEllipse::ConstraintPointOnEllipse (Point & p, Ellipse & e)
References rescale().
ConstraintPointOnEllipse() [2/2]
GCS::ConstraintPointOnEllipse::ConstraintPointOnEllipse (Point & p, ArcOfEllipse & a)
Member Function Documentation
error()
double GCS::ConstraintPointOnEllipse::error () virtual
Reimplemented from GCS::Constraint.
Referenced by femmesh.gmshtools.GmshTools::read_and_set_new_mesh(), FreeCADInit.FCADLogger::report(), and femmesh.gmshtools.GmshTools::run_gmsh_with_geo().
getTypeId()
ConstraintType GCS::ConstraintPointOnEllipse::getTypeId (void) virtual
Reimplemented from GCS::Constraint.
References GCS::PointOnEllipse.
grad()
double GCS::ConstraintPointOnEllipse::grad (double * param) virtual
Reimplemented from GCS::Constraint.
rescale()
void GCS::ConstraintPointOnEllipse::rescale (double coef = 1.) virtual
Reimplemented from GCS::Constraint.
Referenced by ConstraintPointOnEllipse().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Constraints.h
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Constraints.cpp