FreeCAD: DrawSketchHandlerExtend Class Reference
DrawSketchHandlerExtend Class Reference
Public Types
enum SelectMode { STATUS_SEEK_First, STATUS_SEEK_Second }
Public Member Functions
virtual void activated (ViewProviderSketch *sketchgui)
DrawSketchHandlerExtend ()
virtual void mouseMove (Base::Vector2d onSketchPos)
virtual bool pressButton (Base::Vector2d onSketchPos)
virtual bool releaseButton (Base::Vector2d onSketchPos)
virtual ~DrawSketchHandlerExtend ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::none, bool createowncommand=true)
virtual void deactivated (ViewProviderSketch *)
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual void quit (void)
virtual void registerPressedKey (bool, int)
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Attributes
int BaseGeoId
std::vector< Base::Vector2d > EditCurve
bool ExtendFromStart
ExtendSelection * filterGate = nullptr
double Increment
SelectMode Mode
bool SavedExtendFromStart
std::vector< AutoConstraint > SugConstr
Protected Attributes inherited from SketcherGui::DrawSketchHandler
QCursor actCursor
QPixmap actCursorPixmap
QCursor oldCursor
ViewProviderSketch * sketchgui
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
void addCursorTail (std::vector< QPixmap > &pixmaps)
void applyCursor (QCursor &newCursor)
void applyCursor (void)
qreal devicePixelRatio ()
unsigned long getCrosshairColor ()
void setCrosshairColor ()
void setCrosshairCursor (const char *svgName)
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
Sets a cursor for 3D inventor view.
void setSvgCursor (const QString &svgName, int x, int y, const std::map< unsigned long, unsigned long > &colorMapping=std::map< unsigned long, unsigned long >())
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
void unsetCursor (void)
Member Enumeration Documentation
SelectMode
enum DrawSketchHandlerExtend::SelectMode
Enumerator
STATUS_SEEK_First
STATUS_SEEK_Second
Constructor & Destructor Documentation
DrawSketchHandlerExtend()
DrawSketchHandlerExtend::DrawSketchHandlerExtend ()
~DrawSketchHandlerExtend()
virtual DrawSketchHandlerExtend::~DrawSketchHandlerExtend () virtual
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
activated()
virtual void DrawSketchHandlerExtend::activated (ViewProviderSketch * sketchgui) virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References Gui::SelectionSingleton::addSelectionGate(), Gui::SelectionSingleton::clearSelection(), filterGate, Gui::ViewProviderDocumentObject::getObject(), Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), SketcherGui::DrawSketchHandler::setCrosshairCursor(), and SketcherGui::DrawSketchHandler::sketchgui.
mouseMove()
virtual void DrawSketchHandlerExtend::mouseMove (Base::Vector2d onSketchPos) virtual
If in-curve, the intuitive behavior is for the line to shrink an amount from the original click-point.
If out-of-curve, the intuitive behavior is for the closest line endpoint to expand.
Implements SketcherGui::DrawSketchHandler.
References BaseGeoId, Base::Vector2d::Distance(), SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, ExtendFromStart, Base::Vector2d::GetAngle(), Base::Persistence::getClassTypeId(), Part::GeomLineSegment::getEndPoint(), Sketcher::SketchObject::getGeometry(), SketcherGui::ViewProviderSketch::getPreselectCurve(), SketcherGui::ViewProviderSketch::getSketchObject(), Part::GeomLineSegment::getStartPoint(), Base::Persistence::getTypeId(), Increment, Base::Vector2d::Length(), Mode, Base::Vector2d::ProjectToLine(), SketcherGui::DrawSketchHandler::renderSuggestConstraintsCursor(), SavedExtendFromStart, SketcherGui::DrawSketchHandler::seekAutoConstraint(), SketcherGui::DrawSketchHandler::sketchgui, STATUS_SEEK_Second, SugConstr, Base::Vector2d::x, Base::Vector3< _Precision >::x, Base::Vector2d::y, and Base::Vector3< _Precision >::y.
pressButton()
virtual bool DrawSketchHandlerExtend::pressButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
releaseButton()
virtual bool DrawSketchHandlerExtend::releaseButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), SketcherGui::DrawSketchHandler::applyCursor(), BaseGeoId, Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Base::Console(), SketcherGui::DrawSketchHandler::createAutoConstraints(), Base::Vector2d::Distance(), SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, Sketcher::end, Base::ConsoleSingleton::Error(), ExtendFromStart, filterGate, App::GetApplication(), ParameterGrp::GetBool(), Base::Persistence::getClassTypeId(), Part::GeomLineSegment::getEndPoint(), Sketcher::SketchObject::getGeometry(), Gui::ViewProviderDocumentObject::getObject(), App::Application::GetParameterGroupByPath(), SketcherGui::ViewProviderSketch::getPreselectCurve(), SketcherGui::ViewProviderSketch::getSketchObject(), Part::GeomLineSegment::getStartPoint(), Base::Persistence::getTypeId(), Increment, Mode, Gui::Command::openCommand(), SketcherGui::ViewProviderSketch::purgeHandler(), draftutils.translate::QT_TRANSLATE_NOOP, SavedExtendFromStart, SketcherGui::ExtendSelection::setDisabled(), SketcherGui::DrawSketchHandler::sketchgui, Sketcher::start, STATUS_SEEK_First, STATUS_SEEK_Second, SugConstr, Gui::Command::updateActive(), Base::Vector2d::x, Base::Vector3< _Precision >::x, Base::Vector2d::y, and Base::Vector3< _Precision >::y.
Member Data Documentation
BaseGeoId
int DrawSketchHandlerExtend::BaseGeoId protected
Referenced by mouseMove(), and releaseButton().
EditCurve
std::vector<Base::Vector2d> DrawSketchHandlerExtend::EditCurve protected
Referenced by mouseMove(), and releaseButton().
ExtendFromStart
bool DrawSketchHandlerExtend::ExtendFromStart protected
Referenced by mouseMove(), and releaseButton().
filterGate
ExtendSelection* DrawSketchHandlerExtend::filterGate = nullptr protected
Referenced by activated(), and releaseButton().
Increment
double DrawSketchHandlerExtend::Increment protected
Referenced by mouseMove(), and releaseButton().
Mode
SelectMode DrawSketchHandlerExtend::Mode protected
Referenced by mouseMove(), and releaseButton().
SavedExtendFromStart
bool DrawSketchHandlerExtend::SavedExtendFromStart protected
Referenced by mouseMove(), and releaseButton().
SugConstr
std::vector<AutoConstraint> DrawSketchHandlerExtend::SugConstr protected
Referenced by mouseMove(), and releaseButton().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/Gui/CommandCreateGeo.cpp