FreeCAD: Part::PlanePy Class Reference
Part::PlanePy Class Reference
The python export class for GeomPlane.
#include <PlanePy.h>
Public Types
typedef GeomPlane * PointerType
Public Types inherited from Part::GeometrySurfacePy
typedef GeomSurface * PointerType
Public Types inherited from Part::GeometryPy
typedef Geometry * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
PlanePy (GeomPlane *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Part::GeometrySurfacePy
GeometrySurfacePy (GeomSurface *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * toShape (PyObject *args)
implementer for the toShape() method
PyObject * getD0 (PyObject *args)
implementer for the getD0() method
PyObject * getDN (PyObject *args)
implementer for the getDN() method
PyObject * value (PyObject *args)
implementer for the value() method
PyObject * tangent (PyObject *args)
implementer for the tangent() method
PyObject * normal (PyObject *args)
implementer for the normal() method
PyObject * projectPoint (PyObject *args, PyObject *kwd)
implementer for the projectPoint() method
PyObject * isUmbillic (PyObject *args)
implementer for the isUmbillic() method
PyObject * curvature (PyObject *args)
implementer for the curvature() method
PyObject * curvatureDirections (PyObject *args)
implementer for the curvatureDirections() method
PyObject * bounds (PyObject *args)
implementer for the bounds() method
PyObject * isPlanar (PyObject *args)
implementer for the isPlanar() method
PyObject * uIso (PyObject *args)
implementer for the uIso() method
PyObject * vIso (PyObject *args)
implementer for the vIso() method
PyObject * isUPeriodic (PyObject *args)
implementer for the isUPeriodic() method
PyObject * isVPeriodic (PyObject *args)
implementer for the isVPeriodic() method
PyObject * isUClosed (PyObject *args)
implementer for the isUClosed() method
PyObject * isVClosed (PyObject *args)
implementer for the isVClosed() method
PyObject * UPeriod (PyObject *args)
implementer for the UPeriod() method
PyObject * VPeriod (PyObject *args)
implementer for the VPeriod() method
PyObject * parameter (PyObject *args)
implementer for the parameter() method
PyObject * toBSpline (PyObject *args, PyObject *kwd)
implementer for the toBSpline() method
PyObject * intersect (PyObject *args)
implementer for the intersect() method
PyObject * intersectSS (PyObject *args)
implementer for the intersectSS() method
Py::String getContinuity (void) const
getter for the Continuity attribute
Py::Object getRotation (void) const
getter for the Rotation attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomSurface * getGeomSurfacePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Part::GeometryPy
GeometryPy (Geometry *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * clone (PyObject *args)
implementer for the clone() method
PyObject * hasExtensionOfType (PyObject *args)
implementer for the hasExtensionOfType() method
PyObject * hasExtensionOfName (PyObject *args)
implementer for the hasExtensionOfName() method
PyObject * getExtensionOfType (PyObject *args)
implementer for the getExtensionOfType() method
PyObject * getExtensionOfName (PyObject *args)
implementer for the getExtensionOfName() method
PyObject * setExtension (PyObject *args)
implementer for the setExtension() method
PyObject * deleteExtensionOfType (PyObject *args)
implementer for the deleteExtensionOfType() method
PyObject * deleteExtensionOfName (PyObject *args)
implementer for the deleteExtensionOfName() method
PyObject * getExtensions (PyObject *args)
implementer for the getExtensions() method
Py::String getTag (void) const
getter for the Tag attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geometry * getGeometryPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::GeometrySurfacePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_toShape (PyObject *self, PyObject *args)
callback for the toShape() method
static PyObject * staticCallback_getD0 (PyObject *self, PyObject *args)
callback for the getD0() method
static PyObject * staticCallback_getDN (PyObject *self, PyObject *args)
callback for the getDN() method
static PyObject * staticCallback_value (PyObject *self, PyObject *args)
callback for the value() method
static PyObject * staticCallback_tangent (PyObject *self, PyObject *args)
callback for the tangent() method
static PyObject * staticCallback_normal (PyObject *self, PyObject *args)
callback for the normal() method
static PyObject * staticCallback_projectPoint (PyObject *self, PyObject *args, PyObject *kwd)
callback for the projectPoint() method
static PyObject * staticCallback_isUmbillic (PyObject *self, PyObject *args)
callback for the isUmbillic() method
static PyObject * staticCallback_curvature (PyObject *self, PyObject *args)
callback for the curvature() method
static PyObject * staticCallback_curvatureDirections (PyObject *self, PyObject *args)
callback for the curvatureDirections() method
static PyObject * staticCallback_bounds (PyObject *self, PyObject *args)
callback for the bounds() method
static PyObject * staticCallback_isPlanar (PyObject *self, PyObject *args)
callback for the isPlanar() method
static PyObject * staticCallback_uIso (PyObject *self, PyObject *args)
callback for the uIso() method
static PyObject * staticCallback_vIso (PyObject *self, PyObject *args)
callback for the vIso() method
static PyObject * staticCallback_isUPeriodic (PyObject *self, PyObject *args)
callback for the isUPeriodic() method
static PyObject * staticCallback_isVPeriodic (PyObject *self, PyObject *args)
callback for the isVPeriodic() method
static PyObject * staticCallback_isUClosed (PyObject *self, PyObject *args)
callback for the isUClosed() method
static PyObject * staticCallback_isVClosed (PyObject *self, PyObject *args)
callback for the isVClosed() method
static PyObject * staticCallback_UPeriod (PyObject *self, PyObject *args)
callback for the UPeriod() method
static PyObject * staticCallback_VPeriod (PyObject *self, PyObject *args)
callback for the VPeriod() method
static PyObject * staticCallback_parameter (PyObject *self, PyObject *args)
callback for the parameter() method
static PyObject * staticCallback_toBSpline (PyObject *self, PyObject *args, PyObject *kwd)
callback for the toBSpline() method
static PyObject * staticCallback_intersect (PyObject *self, PyObject *args)
callback for the intersect() method
static PyObject * staticCallback_intersectSS (PyObject *self, PyObject *args)
callback for the intersectSS() method
static PyObject * staticCallback_getContinuity (PyObject *self, void *closure)
getter callback for the Continuity attribute
static int staticCallback_setContinuity (PyObject *self, PyObject *value, void *closure)
setter callback for the Continuity attribute
static PyObject * staticCallback_getRotation (PyObject *self, void *closure)
getter callback for the Rotation attribute
static int staticCallback_setRotation (PyObject *self, PyObject *value, void *closure)
setter callback for the Rotation attribute
Static Public Member Functions inherited from Part::GeometryPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_clone (PyObject *self, PyObject *args)
callback for the clone() method
static PyObject * staticCallback_hasExtensionOfType (PyObject *self, PyObject *args)
callback for the hasExtensionOfType() method
static PyObject * staticCallback_hasExtensionOfName (PyObject *self, PyObject *args)
callback for the hasExtensionOfName() method
static PyObject * staticCallback_getExtensionOfType (PyObject *self, PyObject *args)
callback for the getExtensionOfType() method
static PyObject * staticCallback_getExtensionOfName (PyObject *self, PyObject *args)
callback for the getExtensionOfName() method
static PyObject * staticCallback_setExtension (PyObject *self, PyObject *args)
callback for the setExtension() method
static PyObject * staticCallback_deleteExtensionOfType (PyObject *self, PyObject *args)
callback for the deleteExtensionOfType() method
static PyObject * staticCallback_deleteExtensionOfName (PyObject *self, PyObject *args)
callback for the deleteExtensionOfName() method
static PyObject * staticCallback_getExtensions (PyObject *self, PyObject *args)
callback for the getExtensions() method
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of PlanePy.
static PyMethodDef Methods []
Methods structure of PlanePy.
static PyTypeObject Type
Type structure of PlanePy.
Static Public Attributes inherited from Part::GeometrySurfacePy
static PyGetSetDef GetterSetter []
Attribute structure of GeometrySurfacePy.
static PyMethodDef Methods []
Methods structure of GeometrySurfacePy.
static PyTypeObject Type
Type structure of GeometrySurfacePy.
Static Public Attributes inherited from Part::GeometryPy
static PyGetSetDef GetterSetter []
Attribute structure of GeometryPy.
static PyMethodDef Methods []
Methods structure of GeometryPy.
static PyTypeObject Type
Type structure of GeometryPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~PlanePy ()
Protected Member Functions inherited from Part::GeometrySurfacePy
~GeometrySurfacePy ()
Protected Member Functions inherited from Part::GeometryPy
~GeometryPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object attributes
Py::Object getPosition (void) const
getter for the Position attribute
void setPosition (Py::Object arg)
setter for the Position attribute
Py::Object getAxis (void) const
getter for the Axis attribute
void setAxis (Py::Object arg)
setter for the Axis attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomPlane * getGeomPlanePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getPosition (PyObject *self, void *closure)
getter callback for the Position attribute
static int staticCallback_setPosition (PyObject *self, PyObject *value, void *closure)
setter callback for the Position attribute
static PyObject * staticCallback_getAxis (PyObject *self, void *closure)
getter callback for the Axis attribute
static int staticCallback_setAxis (PyObject *self, PyObject *value, void *closure)
setter callback for the Axis attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeomPlane.
Member Typedef Documentation
PointerType
typedef GeomPlane* Part::PlanePy::PointerType
Constructor & Destructor Documentation
~PlanePy()
PlanePy::~PlanePy () protected
PlanePy()
PlanePy::PlanePy (GeomPlane * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getAxis()
Py::Object PlanePy::getAxis (void) const
getter for the Axis attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getAxis().
getCustomAttributes()
PyObject * PlanePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getGeomPlanePtr()
GeomPlane * PlanePy::getGeomPlanePtr (void) const
getter for the object handled by this class
Referenced by getPosition(), and setPosition().
getPosition()
Py::Object PlanePy::getPosition (void) const
getter for the Position attribute
References getGeomPlanePtr().
Referenced by staticCallback_getPosition().
GetType()
virtual PyTypeObject* Part::PlanePy::GetType (void) virtual
Reimplemented from Part::GeometrySurfacePy.
PyInit()
int PlanePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::GeometrySurfacePy.
References DraftVecUtils::dist(), Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, Base::VectorPy::Type, Type, and Part::GeometrySurfacePy::value().
PyMake()
PyObject * PlanePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References PlanePy().
representation()
std::string PlanePy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setAxis()
void PlanePy::setAxis (Py::Object arg)
setter for the Axis attribute
References Part::GeometryPy::getGeometryPtr(), Base::VectorPy::Type, and Part::GeometrySurfacePy::value().
Referenced by staticCallback_setAxis().
setCustomAttributes()
int PlanePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setPosition()
void PlanePy::setPosition (Py::Object arg)
setter for the Position attribute
References getGeomPlanePtr(), Base::VectorPy::Type, and Part::GeometrySurfacePy::value().
Referenced by staticCallback_setPosition().
staticCallback_getAxis()
PyObject * PlanePy::staticCallback_getAxis (PyObject * self, void * closure) static
getter callback for the Axis attribute
References Base::BaseExceptionFreeCADError, getAxis(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPosition()
PyObject * PlanePy::staticCallback_getPosition (PyObject * self, void * closure) static
getter callback for the Position attribute
References Base::BaseExceptionFreeCADError, getPosition(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setAxis()
int PlanePy::staticCallback_setAxis (PyObject * self, PyObject * value, void * closure) static
setter callback for the Axis attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setAxis().
staticCallback_setPosition()
int PlanePy::staticCallback_setPosition (PyObject * self, PyObject * value, void * closure) static
setter callback for the Position attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setPosition().
Member Data Documentation
GetterSetter
PyGetSetDef PlanePy::GetterSetter static
Initial value:
= {
    {"Position",
        (getter) staticCallback_getPosition,
        (setter) staticCallback_setPosition,
        "Returns the position point of this plane.",
        NULL
    },
    {"Axis",
        (getter) staticCallback_getAxis,
        (setter) staticCallback_setAxis,
        "Returns the axis of this plane.",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of PlanePy.
Methods
PyMethodDef PlanePy::Methods static
Initial value:
= {
    {NULL, NULL, 0, NULL}
}
Methods structure of PlanePy.
Type
PyTypeObject PlanePy::Type static
Type structure of PlanePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), Part::GeometryCurvePy::intersect2d(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), and PyInit().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/PlanePy.h
Sources/FreeCAD/src/Mod/Part/App/PlanePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/PlanePy.cpp