FreeCAD: TechDrawGui::Ui_TaskRestoreLines Class Reference
TechDrawGui::Ui_TaskRestoreLines Class Reference
#include <ui_TaskRestoreLines.h>
Public Member Functions
void retranslateUi (QWidget *TechDrawGui__TaskRestoreLines)
void setupUi (QWidget *TechDrawGui__TaskRestoreLines)
Public Attributes
QGridLayout * gridLayout
QLabel * l_All
QLabel * l_Center
QLabel * l_Cosmetic
QLabel * l_Geometry
QPushButton * pb_All
QPushButton * pb_Center
QPushButton * pb_Cosmetic
QPushButton * pb_Geometry
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void TechDrawGui::Ui_TaskRestoreLines::retranslateUi (QWidget * TechDrawGui__TaskRestoreLines)
References l_All, l_Center, l_Cosmetic, l_Geometry, pb_All, pb_Center, pb_Cosmetic, pb_Geometry, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void TechDrawGui::Ui_TaskRestoreLines::setupUi (QWidget * TechDrawGui__TaskRestoreLines)
References gridLayout, l_All, l_Center, l_Cosmetic, l_Geometry, pb_All, pb_Center, pb_Cosmetic, pb_Geometry, retranslateUi(), and verticalLayout.
Member Data Documentation
gridLayout
QGridLayout* TechDrawGui::Ui_TaskRestoreLines::gridLayout
Referenced by setupUi().
l_All
QLabel* TechDrawGui::Ui_TaskRestoreLines::l_All
Referenced by retranslateUi(), and setupUi().
l_Center
QLabel* TechDrawGui::Ui_TaskRestoreLines::l_Center
Referenced by retranslateUi(), and setupUi().
l_Cosmetic
QLabel* TechDrawGui::Ui_TaskRestoreLines::l_Cosmetic
Referenced by retranslateUi(), and setupUi().
l_Geometry
QLabel* TechDrawGui::Ui_TaskRestoreLines::l_Geometry
Referenced by retranslateUi(), and setupUi().
pb_All
QPushButton* TechDrawGui::Ui_TaskRestoreLines::pb_All
Referenced by retranslateUi(), and setupUi().
pb_Center
QPushButton* TechDrawGui::Ui_TaskRestoreLines::pb_Center
Referenced by retranslateUi(), and setupUi().
pb_Cosmetic
QPushButton* TechDrawGui::Ui_TaskRestoreLines::pb_Cosmetic
Referenced by retranslateUi(), and setupUi().
pb_Geometry
QPushButton* TechDrawGui::Ui_TaskRestoreLines::pb_Geometry
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* TechDrawGui::Ui_TaskRestoreLines::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/TechDraw/Gui/ui_TaskRestoreLines.h