FreeCAD: PathScripts.PathDressupHoldingTags Namespace Reference
PathScripts.PathDressupHoldingTags Namespace Reference
Classes
class MapWireToTag
class ObjectTagDressup
class PathData
class Tag
Functions
def Create (baseObject, name="DressupTag")
def debugCone (vector, r1, r2, height, label, color=None)
def debugCylinder (vector, r, height, label, color=None)
def debugEdge (edge, prefix, force=False)
def debugMarker (vector, label, color=None, radius=0.5)
Variables
Part = LazyLoader("Part", globals(), "Part")
translate = FreeCAD.Qt.translate
Function Documentation
Create()
def PathScripts.PathDressupHoldingTags.Create (baseObject, name = "DressupTag")
Create(basePath, name='DressupTag') ... create tag dressup object for the given base path.
References PathScripts.PathDressupHoldingTags.Create().
Referenced by PathScripts.PathDressupHoldingTags.Create().
debugCone()
def PathScripts.PathDressupHoldingTags.debugCone (vector, r1, r2, height, label, color = None)
debugCylinder()
def PathScripts.PathDressupHoldingTags.debugCylinder (vector, r, height, label, color = None)
debugEdge()
def PathScripts.PathDressupHoldingTags.debugEdge (edge, prefix, force = False)
Referenced by PathScripts.PathDressupHoldingTags.MapWireToTag.add(), PathScripts.PathDressupHoldingTags.MapWireToTag.addEdge(), PathScripts.PathDressupHoldingTags.MapWireToTag.cleanupEdges(), PathScripts.PathDressupHoldingTags.MapWireToTag.commandsForEdges(), PathScripts.PathDressupHoldingTags.ObjectTagDressup.createPath(), PathScripts.PathDressupHoldingTags.Tag.nextIntersectionClosestTo(), PathScripts.PathDressupHoldingTags.MapWireToTag.orderAndFlipEdges(), and PathScripts.PathDressupHoldingTags.PathData.pointIsOnPath().
debugMarker()
def PathScripts.PathDressupHoldingTags.debugMarker (vector, label, color = None, radius = 0.5)
Variable Documentation
Part
PathScripts.PathDressupHoldingTags.Part = LazyLoader("Part", globals(), "Part")
translate
PathScripts.PathDressupHoldingTags.translate = FreeCAD.Qt.translate