FreeCAD: SMDS_EdgePosition Class Reference
SMDS_EdgePosition Class Reference
#include <SMDS_EdgePosition.hxx>
Public Member Functions
SMDS_TypeOfPosition GetTypeOfPosition () const
double GetUParameter () const
void SetUParameter (double aUparam)
SMDS_EdgePosition (const double aUParam=0)
Public Member Functions inherited from SMDS_Position
virtual int GetDim () const
virtual ~SMDS_Position ()
Additional Inherited Members
Protected Member Functions inherited from SMDS_Position
SMDS_Position ()
Constructor & Destructor Documentation
SMDS_EdgePosition()
SMDS_EdgePosition::SMDS_EdgePosition (const double aUParam = 0)
Member Function Documentation
GetTypeOfPosition()
SMDS_TypeOfPosition SMDS_EdgePosition::GetTypeOfPosition () const virtual
Implements SMDS_Position.
GetUParameter()
double SMDS_EdgePosition::GetUParameter () const
Referenced by SMESH_MeshEditor::ExtrusionAlongTrack(), SMESH_Algo::GetNodeParamOnEdge(), SMESH_MesherHelper::GetNodeU(), SMESH_MesherHelper::GetNodeUV(), SMESH_Algo::GetSortedNodesOnEdge(), StdMeshers_FaceSide::GetUVPtStruct(), SMESH_Pattern::Load(), StdMeshers_Penta_3D::MakeNodes(), and VISCOUS_3D::_LayerEdge::SetNewLength2d().
SetUParameter()
void SMDS_EdgePosition::SetUParameter (double aUparam)
Referenced by VISCOUS_3D::_LayerEdge::SetNewLength2d().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_EdgePosition.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_EdgePosition.cpp