FreeCAD: PartDesignGui::TaskShapeBinder Class Reference
PartDesignGui::TaskShapeBinder Class Reference
#include <TaskShapeBinder.h>
Public Member Functions
void accept ()
TaskShapeBinder (ViewProviderShapeBinder *view, bool newObj=false, QWidget *parent=nullptr)
~TaskShapeBinder ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Protected Types
enum selectionModes { none , refAdd , refRemove , refObjAdd }
Protected Member Functions
void changeEvent (QEvent *e)
bool referenceSelected (const Gui::SelectionChanges &msg) const
void removeFromListWidget (QListWidget *w, QString name)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Protected Attributes
selectionModes selectionMode = none
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Member Enumeration Documentation
selectionModes
enum PartDesignGui::TaskShapeBinder::selectionModes protected
Enumerator
none
refAdd
refRemove
refObjAdd
Constructor & Destructor Documentation
TaskShapeBinder()
TaskShapeBinder::TaskShapeBinder (ViewProviderShapeBinder * view, bool newObj = false, QWidget * parent = nullptr)
References Gui::BitmapFactory(), and QSint::ActionGroup::groupLayout().
~TaskShapeBinder()
TaskShapeBinder::~TaskShapeBinder ()
Member Function Documentation
accept()
void TaskShapeBinder::accept (void)
References App::DocumentObject::getDocument(), App::Document::getName(), App::PropertyLinkSubList::getValue(), referenceSelected(), refObjAdd, selectionMode, and PartDesign::ShapeBinder::Support.
Referenced by PartDesignGui::TaskDlgShapeBinder::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void TaskShapeBinder::changeEvent (QEvent * e) protected
referenceSelected()
bool TaskShapeBinder::referenceSelected (const Gui::SelectionChanges & msg) const protected
References Gui::SelectionChanges::AddSelection, DraftVecUtils::find(), Base::Persistence::getClassTypeId(), PartDesign::ShapeBinder::getFilteredReferences(), refAdd, refObjAdd, refRemove, selectionMode, and PartDesign::ShapeBinder::Support.
Referenced by accept().
removeFromListWidget()
void TaskShapeBinder::removeFromListWidget (QListWidget * w, QString name) protected
Member Data Documentation
selectionMode
selectionModes PartDesignGui::TaskShapeBinder::selectionMode = none protected
Referenced by accept(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonRef1(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonRef2(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonSupport(), and referenceSelected().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/PartDesign/Gui/TaskShapeBinder.h
FreeCAD/src/Mod/PartDesign/Gui/TaskShapeBinder.cpp