FreeCAD: TechDraw::GeomFormatPy Class Reference
TechDraw::GeomFormatPy Class Reference
The python export class for GeomFormat.
#include <GeomFormatPy.h>
Public Types
typedef GeomFormat * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
GeomFormatPy (GeomFormat *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of GeomFormatPy.
static PyMethodDef Methods []
Methods structure of GeomFormatPy.
static PyTypeObject Type
Type structure of GeomFormatPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~GeomFormatPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * clone (PyObject *args)
implementer for the clone() method
PyObject * copy (PyObject *args)
implementer for the copy() method
static PyObject * staticCallback_clone (PyObject *self, PyObject *args)
callback for the clone() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
callbacks and implementers for the python object attributes
Py::String getTag (void) const
getter for the Tag attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomFormat * getGeomFormatPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeomFormat.
Member Typedef Documentation
PointerType
typedef GeomFormat* TechDraw::GeomFormatPy::PointerType
Constructor & Destructor Documentation
~GeomFormatPy()
GeomFormatPy::~GeomFormatPy () protected
GeomFormatPy()
GeomFormatPy::GeomFormatPy (GeomFormat * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
clone()
PyObject * GeomFormatPy::clone (PyObject * args)
implementer for the clone() method
References TechDraw::GeomFormat::clone(), getGeomFormatPtr(), and GetType().
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchComponent.Component::execute(), ArchCurtainWall.CurtainWall::execute(), ArchTruss.Truss::execute(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated(), staticCallback_clone(), and PathTests.TestPathHelix.TestPathHelix::test04().
copy()
PyObject * GeomFormatPy::copy (PyObject * args)
implementer for the copy() method
References TechDraw::GeomFormat::copy(), getGeomFormatPtr(), and GetType().
Referenced by staticCallback_copy().
getCustomAttributes()
PyObject * GeomFormatPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getGeomFormatPtr()
GeomFormat * GeomFormatPy::getGeomFormatPtr (void) const
getter for the object handled by this class
Referenced by clone(), copy(), getTag(), and TechDraw::PropertyGeomFormatList::setPyObject().
getTag()
Py::String GeomFormatPy::getTag (void) const
getter for the Tag attribute
References getGeomFormatPtr().
Referenced by staticCallback_getTag().
GetType()
virtual PyTypeObject* TechDraw::GeomFormatPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
Referenced by clone(), and copy().
PyInit()
int GeomFormatPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
PyMake()
PyObject * GeomFormatPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string GeomFormatPy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int GeomFormatPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_clone()
PyObject * GeomFormatPy::staticCallback_clone (PyObject * self, PyObject * args) static
callback for the clone() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, clone(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_copy()
PyObject * GeomFormatPy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copy(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTag()
PyObject * GeomFormatPy::staticCallback_getTag (PyObject * self, void * closure) static
getter callback for the Tag attribute
References Base::BaseExceptionFreeCADError, getTag(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setTag()
int GeomFormatPy::staticCallback_setTag (PyObject * self, PyObject * value, void * closure) static
setter callback for the Tag attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
Member Data Documentation
GetterSetter
PyGetSetDef GeomFormatPy::GetterSetter static
Initial value:
= {
    {"Tag",
        (getter) staticCallback_getTag,
        (setter) staticCallback_setTag,
        "Gives the tag of the GeomFormat as string.",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of GeomFormatPy.
Methods
PyMethodDef GeomFormatPy::Methods static
Initial value:
= {
    {"clone",
        reinterpret_cast<PyCFunction>( staticCallback_clone ),
        METH_VARARGS,
        "Create a clone of this geomformat"
    },
    {"copy",
        reinterpret_cast<PyCFunction>( staticCallback_copy ),
        METH_VARARGS,
        "Create a copy of this geomformat"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of GeomFormatPy.
Type
PyTypeObject GeomFormatPy::Type static
Type structure of GeomFormatPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/TechDraw/App/GeomFormatPy.h
Sources/FreeCAD/src/Mod/TechDraw/App/GeomFormatPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/TechDraw/App/GeomFormatPy.cpp