FreeCAD: Gui::Dialog::DlgSettingsLazyLoadedImp Class Reference
Gui::Dialog::DlgSettingsLazyLoadedImp Class Reference
The DlgSettingsLazyLoadedImp class implements a pseudo-preference page explain why the remaining preference pages aren't loaded yet, and to help the user do so on demand.
#include <DlgSettingsLazyLoadedImp.h>
Public Member Functions
DlgSettingsLazyLoadedImp (QWidget *parent=nullptr)
Constructs a DlgSettingsLazyLoadedImp.
void loadSettings ()
void saveSettings ()
~DlgSettingsLazyLoadedImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Slots
void onLoadClicked (const QString &wbName)
Protected Member Functions
void buildUnloadedWorkbenchList ()
Build the list of unloaded workbenches.
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
virtual void changeEvent (QEvent *e)=0
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Detailed Description
The DlgSettingsLazyLoadedImp class implements a pseudo-preference page explain why the remaining preference pages aren't loaded yet, and to help the user do so on demand.
Author
Jürgen Riegel
Constructor & Destructor Documentation
DlgSettingsLazyLoadedImp()
DlgSettingsLazyLoadedImp::DlgSettingsLazyLoadedImp (QWidget * parent = nullptr)
Constructs a DlgSettingsLazyLoadedImp.
~DlgSettingsLazyLoadedImp()
DlgSettingsLazyLoadedImp::~DlgSettingsLazyLoadedImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
buildUnloadedWorkbenchList()
void DlgSettingsLazyLoadedImp::buildUnloadedWorkbenchList () protected
Build the list of unloaded workbenches.
References draftgeoutils.intersections::connect(), DraftVecUtils::find(), Gui::Application::Instance, Gui::WorkbenchManager::instance(), onLoadClicked(), Gui::Application::workbenches(), Gui::Application::workbenchIcon(), Gui::Application::workbenchMenuText(), and Gui::Application::workbenchToolTip().
Referenced by loadSettings(), and onLoadClicked().
changeEvent()
void DlgSettingsLazyLoadedImp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
loadSettings()
void DlgSettingsLazyLoadedImp::loadSettings () virtual
Implements Gui::Dialog::PreferencePage.
References buildUnloadedWorkbenchList(), App::Application::Config(), App::GetApplication(), and App::Application::GetParameterGroupByPath().
onLoadClicked
void DlgSettingsLazyLoadedImp::onLoadClicked (const QString & wbName) protected slot
References Gui::Application::activateWorkbench(), Gui::WorkbenchManager::active(), buildUnloadedWorkbenchList(), Gui::Application::Instance, Gui::WorkbenchManager::instance(), and Gui::Workbench::name().
Referenced by buildUnloadedWorkbenchList().
saveSettings()
void DlgSettingsLazyLoadedImp::saveSettings () virtual
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), and App::Application::GetParameterGroupByPath().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgSettingsLazyLoadedImp.h
FreeCAD/src/Gui/DlgSettingsLazyLoadedImp.cpp