FreeCAD: Gui::Flag Class Reference
Gui::Flag Class Reference
#include <Flag.h>
Public Member Functions
void drawLine (Gui::View3DInventorViewer *, int tox, int toy)
Flag (QWidget *parent=0)
const SbVec3f & getOrigin () const
void setOrigin (const SbVec3f &)
void setText (const QString &)
QSize sizeHint () const
~Flag ()
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *)
void initializeGL ()
void mouseMoveEvent (QMouseEvent *)
void mousePressEvent (QMouseEvent *)
void paintEvent (QPaintEvent *)
void paintGL ()
void resizeEvent (QResizeEvent *)
void resizeGL (int width, int height)
Detailed Description
Author
Werner Mayer
Constructor & Destructor Documentation
Flag()
Flag::Flag (QWidget * parent = 0)
~Flag()
Flag::~Flag ()
Member Function Documentation
contextMenuEvent()
void Flag::contextMenuEvent (QContextMenuEvent * e) protected
References draftutils.gui_utils::select().
drawLine()
void Flag::drawLine (Gui::View3DInventorViewer * v, int tox, int toy)
References Gui::GLPainter::begin().
getOrigin()
const SbVec3f & Flag::getOrigin () const
initializeGL()
void Flag::initializeGL () protected
mouseMoveEvent()
void Flag::mouseMoveEvent (QMouseEvent * e) protected
References draftfunctions.move::move(), and OfflineRenderingUtils::viewer().
mousePressEvent()
void Flag::mousePressEvent (QMouseEvent * e) protected
paintEvent()
void Flag::paintEvent (QPaintEvent * e) protected
paintGL()
void Flag::paintGL () protected
resizeEvent()
void Flag::resizeEvent (QResizeEvent * e) protected
resizeGL()
void Flag::resizeGL (int width, int height) protected
setOrigin()
void Flag::setOrigin (const SbVec3f & v)
setText()
void Flag::setText (const QString & t)
Referenced by InspectionGui::ViewProviderProxyObject::addFlag(), and MeshGui::ViewProviderMesh::faceInfoCallback().
sizeHint()
QSize Flag::sizeHint () const
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Flag.h
Sources/FreeCAD/src/Gui/Flag.cpp