FreeCAD: MED::TTFamilyInfo< eVersion > Struct Template Reference
MED::TTFamilyInfo< eVersion > Struct Template Reference
#include <MED_TStructures.hxx>
Public Types
typedef TTNameInfo< eVersion > TNameInfoBase
Public Member Functions
virtual std::string GetAttrDesc (TInt theId) const
Get value of the MED FAMILY attribute by its number.
virtual std::string GetGroupName (TInt theId) const
Gets name of a bound MED GROUP by its number.
virtual void SetAttrDesc (TInt theId, const std::string &theValue)
Set value of the MED FAMILY attribute by its number.
virtual void SetGroupName (TInt theId, const std::string &theValue)
Sets name of the defined MED GROUP by its number.
TTFamilyInfo (const PMeshInfo &theMeshInfo, const PFamilyInfo &theInfo)
TTFamilyInfo (const PMeshInfo &theMeshInfo, const std::string &theValue, TInt theId, const TStringSet &theGroupNames, const TStringVector &theAttrDescs, const TIntVector &theAttrIds, const TIntVector &theAttrVals)
TTFamilyInfo (const PMeshInfo &theMeshInfo, TInt theNbGroup, TInt theNbAttr, TInt theId, const std::string &theValue)
Public Member Functions inherited from MED::TFamilyInfo
TInt GetAttrId (TInt theId) const
Get MED FAMILY attribute by its number.
TInt GetAttrVal (TInt theId) const
Get MED FAMILY attribute by its number.
TInt GetId () const
Gets number of the MED FAMILY.
const PMeshInfo & GetMeshInfo () const
Get a reference to corresponding MED Mesh.
TInt GetNbAttr () const
Gets number of attached attributes for the MED FAMILY.
TInt GetNbGroup () const
Gets number of MED GROUPS the MED FAMILY is bound to.
void SetAttrId (TInt theId, TInt theVal)
Set MED FAMILY attribute by its number.
void SetAttrVal (TInt theId, TInt theVal)
Set MED FAMILY attribute by its number.
void SetId (TInt theId)
Public Member Functions inherited from MED::TBase
virtual ~TBase ()
Public Member Functions inherited from MED::TTNameInfo< eVersion >
virtual std::string GetName () const
Gets its name.
virtual void SetName (const std::string &theValue)
Set a new name.
virtual void SetName (const TString &theValue)
Set a new name.
TTNameInfo (const std::string &theValue)
Additional Inherited Members
Public Attributes inherited from MED::TFamilyInfo
TString myAttrDesc
Defines sequence of the names of the MED Family attributes.
TFamAttr myAttrId
Defines sequence of the indexes of the MED Family attributes.
TFamAttr myAttrVal
Defines sequence of the values of the MED Family attributes.
TString myGroupNames
Contains sequence of the names for the MED Groups connected to.
TInt myId
An unique index of the MED FAMILY.
PMeshInfo myMeshInfo
A reference to correspondig MED Mesh.
TInt myNbAttr
Defines number of the MED Family attributes
TInt myNbGroup
Define number of the MED FAMILY.
Public Attributes inherited from MED::TNameInfo
TString myName
Keeps its name.
Member Typedef Documentation
TNameInfoBase
template<EVersion eVersion> typedef TTNameInfo<eVersion> MED::TTFamilyInfo< eVersion >::TNameInfoBase
Constructor & Destructor Documentation
TTFamilyInfo() [1/3]
template<EVersion eVersion> MED::TTFamilyInfo< eVersion >::TTFamilyInfo (const PMeshInfo & theMeshInfo, const PFamilyInfo & theInfo)
References MED::TFamilyInfo::myAttrDesc, MED::TFamilyInfo::myAttrId, MED::TFamilyInfo::myAttrVal, MED::TFamilyInfo::myGroupNames, MED::TFamilyInfo::myId, MED::TFamilyInfo::myMeshInfo, MED::TFamilyInfo::myNbAttr, MED::TFamilyInfo::myNbGroup, MED::TTFamilyInfo< eVersion >::SetAttrDesc(), and MED::TTFamilyInfo< eVersion >::SetGroupName().
TTFamilyInfo() [2/3]
template<EVersion eVersion> MED::TTFamilyInfo< eVersion >::TTFamilyInfo (const PMeshInfo & theMeshInfo, TInt theNbGroup, TInt theNbAttr, TInt theId, const std::string & theValue)
References MED::TFamilyInfo::myAttrDesc, MED::TFamilyInfo::myAttrId, MED::TFamilyInfo::myAttrVal, MED::TFamilyInfo::myGroupNames, MED::TFamilyInfo::myId, MED::TFamilyInfo::myMeshInfo, MED::TFamilyInfo::myNbAttr, and MED::TFamilyInfo::myNbGroup.
TTFamilyInfo() [3/3]
template<EVersion eVersion> MED::TTFamilyInfo< eVersion >::TTFamilyInfo (const PMeshInfo & theMeshInfo, const std::string & theValue, TInt theId, const TStringSet & theGroupNames, const TStringVector & theAttrDescs, const TIntVector & theAttrIds, const TIntVector & theAttrVals)
References MED::TFamilyInfo::myAttrDesc, MED::TFamilyInfo::myAttrId, MED::TFamilyInfo::myAttrVal, MED::TFamilyInfo::myGroupNames, MED::TFamilyInfo::myId, MED::TFamilyInfo::myMeshInfo, MED::TFamilyInfo::myNbAttr, MED::TFamilyInfo::myNbGroup, MED::TTFamilyInfo< eVersion >::SetAttrDesc(), and MED::TTFamilyInfo< eVersion >::SetGroupName().
Member Function Documentation
GetAttrDesc()
template<EVersion eVersion> virtual std::string MED::TTFamilyInfo< eVersion >::GetAttrDesc (TInt theId) const virtual
Get value of the MED FAMILY attribute by its number.
Implements MED::TFamilyInfo.
References MED::GetString(), and MED::TFamilyInfo::myAttrDesc.
GetGroupName()
template<EVersion eVersion> virtual std::string MED::TTFamilyInfo< eVersion >::GetGroupName (TInt theId) const virtual
Gets name of a bound MED GROUP by its number.
Implements MED::TFamilyInfo.
References MED::GetString(), and MED::TFamilyInfo::myGroupNames.
SetAttrDesc()
template<EVersion eVersion> virtual void MED::TTFamilyInfo< eVersion >::SetAttrDesc (TInt theId, const std::string & theValue) virtual
Set value of the MED FAMILY attribute by its number.
Implements MED::TFamilyInfo.
References MED::TFamilyInfo::myAttrDesc, and MED::SetString().
Referenced by MED::TTFamilyInfo< eVersion >::TTFamilyInfo().
SetGroupName()
template<EVersion eVersion> virtual void MED::TTFamilyInfo< eVersion >::SetGroupName (TInt theId, const std::string & theValue) virtual
Sets name of the defined MED GROUP by its number.
Implements MED::TFamilyInfo.
References MED::TFamilyInfo::myGroupNames, and MED::SetString().
Referenced by MED::TTFamilyInfo< eVersion >::TTFamilyInfo().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/MED_TStructures.hxx