FreeCAD: Part::TopoShapeFacePy Class Reference
Part::TopoShapeFacePy Class Reference
The python export class for TopoShape.
#include <TopoShapeFacePy.h>
Public Types
typedef TopoShape * PointerType
Public Types inherited from Part::TopoShapePy
typedef TopoShape * PointerType
Public Types inherited from Data::ComplexGeoDataPy
typedef ComplexGeoData * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
TopoShapeFacePy (TopoShape *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Part::TopoShapePy
std::string representation (void) const
TopoShapePy (TopoShape *pcObject, PyTypeObject *T=&Type)
PyObject * read (PyObject *args)
implementer for the read() method
PyObject * writeInventor (PyObject *args, PyObject *kwd)
implementer for the writeInventor() method
PyObject * exportIges (PyObject *args)
implementer for the exportIges() method
PyObject * exportStep (PyObject *args)
implementer for the exportStep() method
PyObject * exportBrep (PyObject *args)
implementer for the exportBrep() method
PyObject * exportBinary (PyObject *args)
implementer for the exportBinary() method
PyObject * exportBrepToString (PyObject *args)
implementer for the exportBrepToString() method
PyObject * dumpToString (PyObject *args)
implementer for the dumpToString() method
PyObject * exportStl (PyObject *args)
implementer for the exportStl() method
PyObject * importBrep (PyObject *args)
implementer for the importBrep() method
PyObject * importBinary (PyObject *args)
implementer for the importBinary() method
PyObject * importBrepFromString (PyObject *args)
implementer for the importBrepFromString() method
PyObject * extrude (PyObject *args)
implementer for the extrude() method
PyObject * revolve (PyObject *args)
implementer for the revolve() method
PyObject * check (PyObject *args)
implementer for the check() method
PyObject * fuse (PyObject *args)
implementer for the fuse() method
PyObject * multiFuse (PyObject *args)
implementer for the multiFuse() method
PyObject * oldFuse (PyObject *args)
implementer for the oldFuse() method
PyObject * common (PyObject *args)
implementer for the common() method
PyObject * section (PyObject *args)
implementer for the section() method
PyObject * slices (PyObject *args)
implementer for the slices() method
PyObject * slice (PyObject *args)
implementer for the slice() method
PyObject * cut (PyObject *args)
implementer for the cut() method
PyObject * generalFuse (PyObject *args)
implementer for the generalFuse() method
PyObject * sewShape (PyObject *args)
implementer for the sewShape() method
PyObject * childShapes (PyObject *args)
implementer for the childShapes() method
PyObject * ancestorsOfType (PyObject *args)
implementer for the ancestorsOfType() method
PyObject * removeInternalWires (PyObject *args)
implementer for the removeInternalWires() method
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * transformGeometry (PyObject *args)
implementer for the transformGeometry() method
PyObject * transformShape (PyObject *args)
implementer for the transformShape() method
PyObject * transformed (PyObject *args, PyObject *kwd)
implementer for the transformed() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * translated (PyObject *args)
implementer for the translated() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * rotated (PyObject *args)
implementer for the rotated() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * scaled (PyObject *args)
implementer for the scaled() method
PyObject * makeFillet (PyObject *args)
implementer for the makeFillet() method
PyObject * makeChamfer (PyObject *args)
implementer for the makeChamfer() method
PyObject * makeThickness (PyObject *args)
implementer for the makeThickness() method
PyObject * makeOffsetShape (PyObject *args, PyObject *kwd)
implementer for the makeOffsetShape() method
PyObject * makeOffset2D (PyObject *args, PyObject *kwd)
implementer for the makeOffset2D() method
PyObject * makeWires (PyObject *args)
implementer for the makeWires() method
PyObject * reverse (PyObject *args)
implementer for the reverse() method
PyObject * reversed (PyObject *args)
implementer for the reversed() method
PyObject * complement (PyObject *args)
implementer for the complement() method
PyObject * nullify (PyObject *args)
implementer for the nullify() method
PyObject * isClosed (PyObject *args)
implementer for the isClosed() method
PyObject * isPartner (PyObject *args)
implementer for the isPartner() method
PyObject * isSame (PyObject *args)
implementer for the isSame() method
PyObject * isEqual (PyObject *args)
implementer for the isEqual() method
PyObject * isNull (PyObject *args)
implementer for the isNull() method
PyObject * isValid (PyObject *args)
implementer for the isValid() method
PyObject * isCoplanar (PyObject *args)
implementer for the isCoplanar() method
PyObject * isInfinite (PyObject *args)
implementer for the isInfinite() method
PyObject * findPlane (PyObject *args)
implementer for the findPlane() method
PyObject * fix (PyObject *args)
implementer for the fix() method
PyObject * hashCode (PyObject *args)
implementer for the hashCode() method
PyObject * tessellate (PyObject *args)
implementer for the tessellate() method
PyObject * project (PyObject *args)
implementer for the project() method
PyObject * makeParallelProjection (PyObject *args)
implementer for the makeParallelProjection() method
PyObject * makePerspectiveProjection (PyObject *args)
implementer for the makePerspectiveProjection() method
PyObject * reflectLines (PyObject *args, PyObject *kwd)
implementer for the reflectLines() method
PyObject * makeShapeFromMesh (PyObject *args)
implementer for the makeShapeFromMesh() method
PyObject * toNurbs (PyObject *args)
implementer for the toNurbs() method
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * cleaned (PyObject *args)
implementer for the cleaned() method
PyObject * replaceShape (PyObject *args)
implementer for the replaceShape() method
PyObject * removeShape (PyObject *args)
implementer for the removeShape() method
PyObject * defeaturing (PyObject *args)
implementer for the defeaturing() method
PyObject * isInside (PyObject *args)
implementer for the isInside() method
PyObject * removeSplitter (PyObject *args)
implementer for the removeSplitter() method
PyObject * proximity (PyObject *args)
implementer for the proximity() method
PyObject * distToShape (PyObject *args)
implementer for the distToShape() method
PyObject * getElement (PyObject *args)
implementer for the getElement() method
PyObject * countElement (PyObject *args)
implementer for the countElement() method
PyObject * getTolerance (PyObject *args)
implementer for the getTolerance() method
PyObject * overTolerance (PyObject *args)
implementer for the overTolerance() method
PyObject * inTolerance (PyObject *args)
implementer for the inTolerance() method
PyObject * globalTolerance (PyObject *args)
implementer for the globalTolerance() method
PyObject * fixTolerance (PyObject *args)
implementer for the fixTolerance() method
PyObject * limitTolerance (PyObject *args)
implementer for the limitTolerance() method
PyObject * optimalBoundingBox (PyObject *args)
implementer for the optimalBoundingBox() method
Py::String getShapeType (void) const
getter for the ShapeType attribute
Py::String getOrientation (void) const
getter for the Orientation attribute
void setOrientation (Py::String arg)
setter for the Orientation attribute
Py::List getFaces (void) const
getter for the Faces attribute
Py::List getVertexes (void) const
getter for the Vertexes attribute
Py::List getShells (void) const
getter for the Shells attribute
Py::List getSolids (void) const
getter for the Solids attribute
Py::List getCompSolids (void) const
getter for the CompSolids attribute
Py::List getEdges (void) const
getter for the Edges attribute
Py::List getWires (void) const
getter for the Wires attribute
Py::List getCompounds (void) const
getter for the Compounds attribute
Py::List getSubShapes (void) const
getter for the SubShapes attribute
Py::Float getLength (void) const
getter for the Length attribute
Py::Float getArea (void) const
getter for the Area attribute
Py::Float getVolume (void) const
getter for the Volume attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
TopoShape * getTopoShapePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Data::ComplexGeoDataPy
ComplexGeoDataPy (ComplexGeoData *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getFacesFromSubelement (PyObject *args)
implementer for the getFacesFromSubelement() method
Py::Object getBoundBox (void) const
getter for the BoundBox attribute
Py::Object getPlacement (void) const
getter for the Placement attribute
void setPlacement (Py::Object arg)
setter for the Placement attribute
Py::Object getMatrix (void) const
getter for the Matrix attribute
void setMatrix (Py::Object arg)
setter for the Matrix attribute
Py::Int getTag (void) const
getter for the Tag attribute
void setTag (Py::Int arg)
setter for the Tag attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ComplexGeoData * getComplexGeoDataPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::TopoShapePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback___getstate__ (PyObject *self, PyObject *args)
callback for the getstate() method
static PyObject * staticCallback___setstate__ (PyObject *self, PyObject *args)
callback for the setstate() method
static PyObject * staticCallback_read (PyObject *self, PyObject *args)
callback for the read() method
static PyObject * staticCallback_writeInventor (PyObject *self, PyObject *args, PyObject *kwd)
callback for the writeInventor() method
static PyObject * staticCallback_exportIges (PyObject *self, PyObject *args)
callback for the exportIges() method
static PyObject * staticCallback_exportStep (PyObject *self, PyObject *args)
callback for the exportStep() method
static PyObject * staticCallback_exportBrep (PyObject *self, PyObject *args)
callback for the exportBrep() method
static PyObject * staticCallback_exportBinary (PyObject *self, PyObject *args)
callback for the exportBinary() method
static PyObject * staticCallback_exportBrepToString (PyObject *self, PyObject *args)
callback for the exportBrepToString() method
static PyObject * staticCallback_dumpToString (PyObject *self, PyObject *args)
callback for the dumpToString() method
static PyObject * staticCallback_exportStl (PyObject *self, PyObject *args)
callback for the exportStl() method
static PyObject * staticCallback_importBrep (PyObject *self, PyObject *args)
callback for the importBrep() method
static PyObject * staticCallback_importBinary (PyObject *self, PyObject *args)
callback for the importBinary() method
static PyObject * staticCallback_importBrepFromString (PyObject *self, PyObject *args)
callback for the importBrepFromString() method
static PyObject * staticCallback_extrude (PyObject *self, PyObject *args)
callback for the extrude() method
static PyObject * staticCallback_revolve (PyObject *self, PyObject *args)
callback for the revolve() method
static PyObject * staticCallback_check (PyObject *self, PyObject *args)
callback for the check() method
static PyObject * staticCallback_fuse (PyObject *self, PyObject *args)
callback for the fuse() method
static PyObject * staticCallback_multiFuse (PyObject *self, PyObject *args)
callback for the multiFuse() method
static PyObject * staticCallback_oldFuse (PyObject *self, PyObject *args)
callback for the oldFuse() method
static PyObject * staticCallback_common (PyObject *self, PyObject *args)
callback for the common() method
static PyObject * staticCallback_section (PyObject *self, PyObject *args)
callback for the section() method
static PyObject * staticCallback_slices (PyObject *self, PyObject *args)
callback for the slices() method
static PyObject * staticCallback_slice (PyObject *self, PyObject *args)
callback for the slice() method
static PyObject * staticCallback_cut (PyObject *self, PyObject *args)
callback for the cut() method
static PyObject * staticCallback_generalFuse (PyObject *self, PyObject *args)
callback for the generalFuse() method
static PyObject * staticCallback_sewShape (PyObject *self, PyObject *args)
callback for the sewShape() method
static PyObject * staticCallback_childShapes (PyObject *self, PyObject *args)
callback for the childShapes() method
static PyObject * staticCallback_ancestorsOfType (PyObject *self, PyObject *args)
callback for the ancestorsOfType() method
static PyObject * staticCallback_removeInternalWires (PyObject *self, PyObject *args)
callback for the removeInternalWires() method
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_transformGeometry (PyObject *self, PyObject *args)
callback for the transformGeometry() method
static PyObject * staticCallback_transformShape (PyObject *self, PyObject *args)
callback for the transformShape() method
static PyObject * staticCallback_transformed (PyObject *self, PyObject *args, PyObject *kwd)
callback for the transformed() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_translated (PyObject *self, PyObject *args)
callback for the translated() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_rotated (PyObject *self, PyObject *args)
callback for the rotated() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_scaled (PyObject *self, PyObject *args)
callback for the scaled() method
static PyObject * staticCallback_makeFillet (PyObject *self, PyObject *args)
callback for the makeFillet() method
static PyObject * staticCallback_makeChamfer (PyObject *self, PyObject *args)
callback for the makeChamfer() method
static PyObject * staticCallback_makeThickness (PyObject *self, PyObject *args)
callback for the makeThickness() method
static PyObject * staticCallback_makeOffsetShape (PyObject *self, PyObject *args, PyObject *kwd)
callback for the makeOffsetShape() method
static PyObject * staticCallback_makeOffset2D (PyObject *self, PyObject *args, PyObject *kwd)
callback for the makeOffset2D() method
static PyObject * staticCallback_makeWires (PyObject *self, PyObject *args)
callback for the makeWires() method
static PyObject * staticCallback_reverse (PyObject *self, PyObject *args)
callback for the reverse() method
static PyObject * staticCallback_reversed (PyObject *self, PyObject *args)
callback for the reversed() method
static PyObject * staticCallback_complement (PyObject *self, PyObject *args)
callback for the complement() method
static PyObject * staticCallback_nullify (PyObject *self, PyObject *args)
callback for the nullify() method
static PyObject * staticCallback_isClosed (PyObject *self, PyObject *args)
callback for the isClosed() method
static PyObject * staticCallback_isPartner (PyObject *self, PyObject *args)
callback for the isPartner() method
static PyObject * staticCallback_isSame (PyObject *self, PyObject *args)
callback for the isSame() method
static PyObject * staticCallback_isEqual (PyObject *self, PyObject *args)
callback for the isEqual() method
static PyObject * staticCallback_isNull (PyObject *self, PyObject *args)
callback for the isNull() method
static PyObject * staticCallback_isValid (PyObject *self, PyObject *args)
callback for the isValid() method
static PyObject * staticCallback_isCoplanar (PyObject *self, PyObject *args)
callback for the isCoplanar() method
static PyObject * staticCallback_isInfinite (PyObject *self, PyObject *args)
callback for the isInfinite() method
static PyObject * staticCallback_findPlane (PyObject *self, PyObject *args)
callback for the findPlane() method
static PyObject * staticCallback_fix (PyObject *self, PyObject *args)
callback for the fix() method
static PyObject * staticCallback_hashCode (PyObject *self, PyObject *args)
callback for the hashCode() method
static PyObject * staticCallback_tessellate (PyObject *self, PyObject *args)
callback for the tessellate() method
static PyObject * staticCallback_project (PyObject *self, PyObject *args)
callback for the project() method
static PyObject * staticCallback_makeParallelProjection (PyObject *self, PyObject *args)
callback for the makeParallelProjection() method
static PyObject * staticCallback_makePerspectiveProjection (PyObject *self, PyObject *args)
callback for the makePerspectiveProjection() method
static PyObject * staticCallback_reflectLines (PyObject *self, PyObject *args, PyObject *kwd)
callback for the reflectLines() method
static PyObject * staticCallback_makeShapeFromMesh (PyObject *self, PyObject *args)
callback for the makeShapeFromMesh() method
static PyObject * staticCallback_toNurbs (PyObject *self, PyObject *args)
callback for the toNurbs() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_cleaned (PyObject *self, PyObject *args)
callback for the cleaned() method
static PyObject * staticCallback_replaceShape (PyObject *self, PyObject *args)
callback for the replaceShape() method
static PyObject * staticCallback_removeShape (PyObject *self, PyObject *args)
callback for the removeShape() method
static PyObject * staticCallback_defeaturing (PyObject *self, PyObject *args)
callback for the defeaturing() method
static PyObject * staticCallback_isInside (PyObject *self, PyObject *args)
callback for the isInside() method
static PyObject * staticCallback_removeSplitter (PyObject *self, PyObject *args)
callback for the removeSplitter() method
static PyObject * staticCallback_proximity (PyObject *self, PyObject *args)
callback for the proximity() method
static PyObject * staticCallback_distToShape (PyObject *self, PyObject *args)
callback for the distToShape() method
static PyObject * staticCallback_getElement (PyObject *self, PyObject *args)
callback for the getElement() method
static PyObject * staticCallback_countElement (PyObject *self, PyObject *args)
callback for the countElement() method
static PyObject * staticCallback_getTolerance (PyObject *self, PyObject *args)
callback for the getTolerance() method
static PyObject * staticCallback_overTolerance (PyObject *self, PyObject *args)
callback for the overTolerance() method
static PyObject * staticCallback_inTolerance (PyObject *self, PyObject *args)
callback for the inTolerance() method
static PyObject * staticCallback_globalTolerance (PyObject *self, PyObject *args)
callback for the globalTolerance() method
static PyObject * staticCallback_fixTolerance (PyObject *self, PyObject *args)
callback for the fixTolerance() method
static PyObject * staticCallback_limitTolerance (PyObject *self, PyObject *args)
callback for the limitTolerance() method
static PyObject * staticCallback_optimalBoundingBox (PyObject *self, PyObject *args)
callback for the optimalBoundingBox() method
static PyObject * staticCallback_getShapeType (PyObject *self, void *closure)
getter callback for the ShapeType attribute
static int staticCallback_setShapeType (PyObject *self, PyObject *value, void *closure)
setter callback for the ShapeType attribute
static PyObject * staticCallback_getOrientation (PyObject *self, void *closure)
getter callback for the Orientation attribute
static int staticCallback_setOrientation (PyObject *self, PyObject *value, void *closure)
setter callback for the Orientation attribute
static PyObject * staticCallback_getFaces (PyObject *self, void *closure)
getter callback for the Faces attribute
static int staticCallback_setFaces (PyObject *self, PyObject *value, void *closure)
setter callback for the Faces attribute
static PyObject * staticCallback_getVertexes (PyObject *self, void *closure)
getter callback for the Vertexes attribute
static int staticCallback_setVertexes (PyObject *self, PyObject *value, void *closure)
setter callback for the Vertexes attribute
static PyObject * staticCallback_getShells (PyObject *self, void *closure)
getter callback for the Shells attribute
static int staticCallback_setShells (PyObject *self, PyObject *value, void *closure)
setter callback for the Shells attribute
static PyObject * staticCallback_getSolids (PyObject *self, void *closure)
getter callback for the Solids attribute
static int staticCallback_setSolids (PyObject *self, PyObject *value, void *closure)
setter callback for the Solids attribute
static PyObject * staticCallback_getCompSolids (PyObject *self, void *closure)
getter callback for the CompSolids attribute
static int staticCallback_setCompSolids (PyObject *self, PyObject *value, void *closure)
setter callback for the CompSolids attribute
static PyObject * staticCallback_getEdges (PyObject *self, void *closure)
getter callback for the Edges attribute
static int staticCallback_setEdges (PyObject *self, PyObject *value, void *closure)
setter callback for the Edges attribute
static PyObject * staticCallback_getWires (PyObject *self, void *closure)
getter callback for the Wires attribute
static int staticCallback_setWires (PyObject *self, PyObject *value, void *closure)
setter callback for the Wires attribute
static PyObject * staticCallback_getCompounds (PyObject *self, void *closure)
getter callback for the Compounds attribute
static int staticCallback_setCompounds (PyObject *self, PyObject *value, void *closure)
setter callback for the Compounds attribute
static PyObject * staticCallback_getSubShapes (PyObject *self, void *closure)
getter callback for the SubShapes attribute
static int staticCallback_setSubShapes (PyObject *self, PyObject *value, void *closure)
setter callback for the SubShapes attribute
static PyObject * staticCallback_getLength (PyObject *self, void *closure)
getter callback for the Length attribute
static int staticCallback_setLength (PyObject *self, PyObject *value, void *closure)
setter callback for the Length attribute
static PyObject * staticCallback_getArea (PyObject *self, void *closure)
getter callback for the Area attribute
static int staticCallback_setArea (PyObject *self, PyObject *value, void *closure)
setter callback for the Area attribute
static PyObject * staticCallback_getVolume (PyObject *self, void *closure)
getter callback for the Volume attribute
static int staticCallback_setVolume (PyObject *self, PyObject *value, void *closure)
setter callback for the Volume attribute
Static Public Member Functions inherited from Data::ComplexGeoDataPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_getFacesFromSubelement (PyObject *self, PyObject *args)
callback for the getFacesFromSubelement() method
static PyObject * staticCallback_getBoundBox (PyObject *self, void *closure)
getter callback for the BoundBox attribute
static int staticCallback_setBoundBox (PyObject *self, PyObject *value, void *closure)
setter callback for the BoundBox attribute
static PyObject * staticCallback_getPlacement (PyObject *self, void *closure)
getter callback for the Placement attribute
static int staticCallback_setPlacement (PyObject *self, PyObject *value, void *closure)
setter callback for the Placement attribute
static PyObject * staticCallback_getMatrix (PyObject *self, void *closure)
getter callback for the Matrix attribute
static int staticCallback_setMatrix (PyObject *self, PyObject *value, void *closure)
setter callback for the Matrix attribute
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of TopoShapeFacePy.
static PyMethodDef Methods []
Methods structure of TopoShapeFacePy.
static PyTypeObject Type
Type structure of TopoShapeFacePy.
Static Public Attributes inherited from Part::TopoShapePy
static PyGetSetDef GetterSetter []
Attribute structure of TopoShapePy.
static PyMethodDef Methods []
Methods structure of TopoShapePy.
static PyTypeObject Type
Type structure of TopoShapePy.
Static Public Attributes inherited from Data::ComplexGeoDataPy
static PyGetSetDef GetterSetter []
Attribute structure of ComplexGeoDataPy.
static PyMethodDef Methods []
Methods structure of ComplexGeoDataPy.
static PyTypeObject Type
Type structure of ComplexGeoDataPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~TopoShapeFacePy ()
Protected Member Functions inherited from Part::TopoShapePy
~TopoShapePy ()
Protected Member Functions inherited from Data::ComplexGeoDataPy
~ComplexGeoDataPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * addWire (PyObject *args)
implementer for the addWire() method
PyObject * makeOffset (PyObject *args)
implementer for the makeOffset() method
PyObject * getUVNodes (PyObject *args)
implementer for the getUVNodes() method
PyObject * tangentAt (PyObject *args)
implementer for the tangentAt() method
PyObject * valueAt (PyObject *args)
implementer for the valueAt() method
PyObject * normalAt (PyObject *args)
implementer for the normalAt() method
PyObject * derivative1At (PyObject *args)
implementer for the derivative1At() method
PyObject * derivative2At (PyObject *args)
implementer for the derivative2At() method
PyObject * curvatureAt (PyObject *args)
implementer for the curvatureAt() method
PyObject * isPartOfDomain (PyObject *args)
implementer for the isPartOfDomain() method
PyObject * makeHalfSpace (PyObject *args)
implementer for the makeHalfSpace() method
PyObject * validate (PyObject *args)
implementer for the validate() method
PyObject * curveOnSurface (PyObject *args)
implementer for the curveOnSurface() method
PyObject * cutHoles (PyObject *args)
implementer for the cutHoles() method
static PyObject * staticCallback_addWire (PyObject *self, PyObject *args)
callback for the addWire() method
static PyObject * staticCallback_makeOffset (PyObject *self, PyObject *args)
callback for the makeOffset() method
static PyObject * staticCallback_getUVNodes (PyObject *self, PyObject *args)
callback for the getUVNodes() method
static PyObject * staticCallback_tangentAt (PyObject *self, PyObject *args)
callback for the tangentAt() method
static PyObject * staticCallback_valueAt (PyObject *self, PyObject *args)
callback for the valueAt() method
static PyObject * staticCallback_normalAt (PyObject *self, PyObject *args)
callback for the normalAt() method
static PyObject * staticCallback_derivative1At (PyObject *self, PyObject *args)
callback for the derivative1At() method
static PyObject * staticCallback_derivative2At (PyObject *self, PyObject *args)
callback for the derivative2At() method
static PyObject * staticCallback_curvatureAt (PyObject *self, PyObject *args)
callback for the curvatureAt() method
static PyObject * staticCallback_isPartOfDomain (PyObject *self, PyObject *args)
callback for the isPartOfDomain() method
static PyObject * staticCallback_makeHalfSpace (PyObject *self, PyObject *args)
callback for the makeHalfSpace() method
static PyObject * staticCallback_validate (PyObject *self, PyObject *args)
callback for the validate() method
static PyObject * staticCallback_curveOnSurface (PyObject *self, PyObject *args)
callback for the curveOnSurface() method
static PyObject * staticCallback_cutHoles (PyObject *self, PyObject *args)
callback for the cutHoles() method
callbacks and implementers for the python object attributes
Py::Float getTolerance (void) const
getter for the Tolerance attribute
void setTolerance (Py::Float arg)
setter for the Tolerance attribute
Py::Tuple getParameterRange (void) const
getter for the ParameterRange attribute
Py::Object getSurface (void) const
getter for the Surface attribute
Py::Object getWire (void) const
getter for the Wire attribute
Py::Object getOuterWire (void) const
getter for the OuterWire attribute
Py::Object getMass (void) const
getter for the Mass attribute
Py::Object getCenterOfMass (void) const
getter for the CenterOfMass attribute
Py::Object getMatrixOfInertia (void) const
getter for the MatrixOfInertia attribute
Py::Object getStaticMoments (void) const
getter for the StaticMoments attribute
Py::Dict getPrincipalProperties (void) const
getter for the PrincipalProperties attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
TopoShape * getTopoShapePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getTolerance (PyObject *self, void *closure)
getter callback for the Tolerance attribute
static int staticCallback_setTolerance (PyObject *self, PyObject *value, void *closure)
setter callback for the Tolerance attribute
static PyObject * staticCallback_getParameterRange (PyObject *self, void *closure)
getter callback for the ParameterRange attribute
static int staticCallback_setParameterRange (PyObject *self, PyObject *value, void *closure)
setter callback for the ParameterRange attribute
static PyObject * staticCallback_getSurface (PyObject *self, void *closure)
getter callback for the Surface attribute
static int staticCallback_setSurface (PyObject *self, PyObject *value, void *closure)
setter callback for the Surface attribute
static PyObject * staticCallback_getWire (PyObject *self, void *closure)
getter callback for the Wire attribute
static int staticCallback_setWire (PyObject *self, PyObject *value, void *closure)
setter callback for the Wire attribute
static PyObject * staticCallback_getOuterWire (PyObject *self, void *closure)
getter callback for the OuterWire attribute
static int staticCallback_setOuterWire (PyObject *self, PyObject *value, void *closure)
setter callback for the OuterWire attribute
static PyObject * staticCallback_getMass (PyObject *self, void *closure)
getter callback for the Mass attribute
static int staticCallback_setMass (PyObject *self, PyObject *value, void *closure)
setter callback for the Mass attribute
static PyObject * staticCallback_getCenterOfMass (PyObject *self, void *closure)
getter callback for the CenterOfMass attribute
static int staticCallback_setCenterOfMass (PyObject *self, PyObject *value, void *closure)
setter callback for the CenterOfMass attribute
static PyObject * staticCallback_getMatrixOfInertia (PyObject *self, void *closure)
getter callback for the MatrixOfInertia attribute
static int staticCallback_setMatrixOfInertia (PyObject *self, PyObject *value, void *closure)
setter callback for the MatrixOfInertia attribute
static PyObject * staticCallback_getStaticMoments (PyObject *self, void *closure)
getter callback for the StaticMoments attribute
static int staticCallback_setStaticMoments (PyObject *self, PyObject *value, void *closure)
setter callback for the StaticMoments attribute
static PyObject * staticCallback_getPrincipalProperties (PyObject *self, void *closure)
getter callback for the PrincipalProperties attribute
static int staticCallback_setPrincipalProperties (PyObject *self, PyObject *value, void *closure)
setter callback for the PrincipalProperties attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for TopoShape.
Member Typedef Documentation
PointerType
typedef TopoShape* Part::TopoShapeFacePy::PointerType
Constructor & Destructor Documentation
~TopoShapeFacePy()
TopoShapeFacePy::~TopoShapeFacePy () protected
TopoShapeFacePy()
TopoShapeFacePy::TopoShapeFacePy (TopoShape * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
addWire()
PyObject * TopoShapeFacePy::addWire (PyObject * args)
implementer for the addWire() method
TopoShapeFacePy::addWire.
circle = Part.Circle()
circle.Radius = 10
wire = Part.Wire(circle.toShape())
Part.show(wire)
circle2 = Part.Circle()
circle2.Radius = 4
wire2 = Part.Wire(circle2.toShape())
Part.show(wire2)
plane = Part.Plane()
face = plane.toShape()
face.addWire(wire)
face.Area
Part.show(face)
face.addWire(wire2.reversed())
face.Area
Part.show(face)
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::TopoShape::setShape(), and Part::TopoShapeWirePy::Type.
Referenced by staticCallback_addWire().
curvatureAt()
PyObject * TopoShapeFacePy::curvatureAt (PyObject * args)
implementer for the curvatureAt() method
References getTopoShapePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_curvatureAt().
curveOnSurface()
PyObject * TopoShapeFacePy::curveOnSurface (PyObject * args)
implementer for the curveOnSurface() method
References Base::BaseClass::getPyObject(), Part::TopoShape::getShape(), getTopoShapePtr(), Part::makeFromCurve2d(), Part::PartExceptionOCCError, and Part::TopoShapeEdgePy::Type.
Referenced by staticCallback_curveOnSurface().
cutHoles()
PyObject * TopoShapeFacePy::cutHoles (PyObject * args)
implementer for the cutHoles() method
References Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, Part::TopoShape::setShape(), and Part::TopoShapePy::Type.
Referenced by staticCallback_cutHoles().
derivative1At()
PyObject * TopoShapeFacePy::derivative1At (PyObject * args)
implementer for the derivative1At() method
References getTopoShapePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_derivative1At().
derivative2At()
PyObject * TopoShapeFacePy::derivative2At (PyObject * args)
implementer for the derivative2At() method
References getTopoShapePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_derivative2At().
getCenterOfMass()
Py::Object TopoShapeFacePy::getCenterOfMass (void) const
getter for the CenterOfMass attribute
References getTopoShapePtr().
Referenced by staticCallback_getCenterOfMass().
getCustomAttributes()
PyObject * TopoShapeFacePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getMass()
Py::Object TopoShapeFacePy::getMass (void) const
getter for the Mass attribute
References getTopoShapePtr().
Referenced by staticCallback_getMass().
getMatrixOfInertia()
Py::Object TopoShapeFacePy::getMatrixOfInertia (void) const
getter for the MatrixOfInertia attribute
References getTopoShapePtr().
Referenced by staticCallback_getMatrixOfInertia().
getOuterWire()
Py::Object TopoShapeFacePy::getOuterWire (void) const
getter for the OuterWire attribute
References Part::TopoShape::getShape(), and getTopoShapePtr().
Referenced by getWire(), and staticCallback_getOuterWire().
getParameterRange()
Py::Tuple TopoShapeFacePy::getParameterRange (void) const
getter for the ParameterRange attribute
References getTopoShapePtr().
Referenced by staticCallback_getParameterRange().
getPrincipalProperties()
Py::Dict TopoShapeFacePy::getPrincipalProperties (void) const
getter for the PrincipalProperties attribute
References Base::convertTo(), and getTopoShapePtr().
Referenced by staticCallback_getPrincipalProperties().
getStaticMoments()
Py::Object TopoShapeFacePy::getStaticMoments (void) const
getter for the StaticMoments attribute
References getTopoShapePtr().
Referenced by staticCallback_getStaticMoments().
getSurface()
Py::Object TopoShapeFacePy::getSurface (void) const
getter for the Surface attribute
References getTopoShapePtr(), and Base::PyObjectBase::setNotTracking().
Referenced by staticCallback_getSurface().
getTolerance()
Py::Float TopoShapeFacePy::getTolerance (void) const
getter for the Tolerance attribute
References getTopoShapePtr().
Referenced by staticCallback_getTolerance().
getTopoShapePtr()
TopoShape * TopoShapeFacePy::getTopoShapePtr (void) const
getter for the object handled by this class
Referenced by addWire(), curvatureAt(), curveOnSurface(), cutHoles(), derivative1At(), derivative2At(), getCenterOfMass(), getMass(), getMatrixOfInertia(), getOuterWire(), getParameterRange(), getPrincipalProperties(), getStaticMoments(), getSurface(), getTolerance(), getUVNodes(), isPartOfDomain(), makeHalfSpace(), makeOffset(), normalAt(), PyInit(), representation(), setTolerance(), tangentAt(), validate(), and valueAt().
GetType()
virtual PyTypeObject* Part::TopoShapeFacePy::GetType (void) virtual
Reimplemented from Part::TopoShapePy.
getUVNodes()
PyObject * TopoShapeFacePy::getUVNodes (PyObject * args)
implementer for the getUVNodes() method
References getTopoShapePtr().
Referenced by staticCallback_getUVNodes().
getWire()
Py::Object TopoShapeFacePy::getWire (void) const
getter for the Wire attribute
References getOuterWire().
Referenced by staticCallback_getWire().
isPartOfDomain()
PyObject * TopoShapeFacePy::isPartOfDomain (PyObject * args)
implementer for the isPartOfDomain() method
References getTopoShapePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_isPartOfDomain().
makeHalfSpace()
PyObject * TopoShapeFacePy::makeHalfSpace (PyObject * args)
implementer for the makeHalfSpace() method
References getTopoShapePtr(), Part::PartExceptionOCCError, Base::VectorPy::Type, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by staticCallback_makeHalfSpace().
makeOffset()
PyObject * TopoShapeFacePy::makeOffset (PyObject * args)
implementer for the makeOffset() method
References DraftVecUtils::dist(), Part::TopoShapePy::findPlane(), getTopoShapePtr(), Part::PartExceptionOCCError, and Part::TopoShapePy::TopoShapePy().
Referenced by staticCallback_makeOffset().
normalAt()
PyObject * TopoShapeFacePy::normalAt (PyObject * args)
implementer for the normalAt() method
References getTopoShapePtr(), Part::PartExceptionOCCError, and draftgeoutils.general::vec().
Referenced by staticCallback_normalAt().
PyInit()
int TopoShapeFacePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::TopoShapePy.
References Base::BaseExceptionFreeCADError, Part::FaceMaker::ConstructFromType(), Part::TopoShape::getShape(), getTopoShapePtr(), Part::PartExceptionOCCError, Part::TopoShape::setShape(), Part::GeometryPy::Type, Part::GeometrySurfacePy::Type, Type, Part::TopoShapePy::Type, and Part::TopoShapeWirePy::Type.
PyMake()
PyObject * TopoShapeFacePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References TopoShapeFacePy().
representation()
std::string TopoShapeFacePy::representation (void) const
References getTopoShapePtr().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int TopoShapeFacePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setTolerance()
void TopoShapeFacePy::setTolerance (Py::Float arg)
setter for the Tolerance attribute
References getTopoShapePtr().
Referenced by staticCallback_setTolerance().
staticCallback_addWire()
PyObject * TopoShapeFacePy::staticCallback_addWire (PyObject * self, PyObject * args) static
callback for the addWire() method
References addWire(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_curvatureAt()
PyObject * TopoShapeFacePy::staticCallback_curvatureAt (PyObject * self, PyObject * args) static
callback for the curvatureAt() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, curvatureAt(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_curveOnSurface()
PyObject * TopoShapeFacePy::staticCallback_curveOnSurface (PyObject * self, PyObject * args) static
callback for the curveOnSurface() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, curveOnSurface(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_cutHoles()
PyObject * TopoShapeFacePy::staticCallback_cutHoles (PyObject * self, PyObject * args) static
callback for the cutHoles() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, cutHoles(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_derivative1At()
PyObject * TopoShapeFacePy::staticCallback_derivative1At (PyObject * self, PyObject * args) static
callback for the derivative1At() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, derivative1At(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_derivative2At()
PyObject * TopoShapeFacePy::staticCallback_derivative2At (PyObject * self, PyObject * args) static
callback for the derivative2At() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, derivative2At(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCenterOfMass()
PyObject * TopoShapeFacePy::staticCallback_getCenterOfMass (PyObject * self, void * closure) static
getter callback for the CenterOfMass attribute
References Base::BaseExceptionFreeCADError, getCenterOfMass(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMass()
PyObject * TopoShapeFacePy::staticCallback_getMass (PyObject * self, void * closure) static
getter callback for the Mass attribute
References Base::BaseExceptionFreeCADError, getMass(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMatrixOfInertia()
PyObject * TopoShapeFacePy::staticCallback_getMatrixOfInertia (PyObject * self, void * closure) static
getter callback for the MatrixOfInertia attribute
References Base::BaseExceptionFreeCADError, getMatrixOfInertia(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getOuterWire()
PyObject * TopoShapeFacePy::staticCallback_getOuterWire (PyObject * self, void * closure) static
getter callback for the OuterWire attribute
References Base::BaseExceptionFreeCADError, getOuterWire(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getParameterRange()
PyObject * TopoShapeFacePy::staticCallback_getParameterRange (PyObject * self, void * closure) static
getter callback for the ParameterRange attribute
References Base::BaseExceptionFreeCADError, getParameterRange(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPrincipalProperties()
PyObject * TopoShapeFacePy::staticCallback_getPrincipalProperties (PyObject * self, void * closure) static
getter callback for the PrincipalProperties attribute
References Base::BaseExceptionFreeCADError, getPrincipalProperties(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getStaticMoments()
PyObject * TopoShapeFacePy::staticCallback_getStaticMoments (PyObject * self, void * closure) static
getter callback for the StaticMoments attribute
References Base::BaseExceptionFreeCADError, getStaticMoments(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSurface()
PyObject * TopoShapeFacePy::staticCallback_getSurface (PyObject * self, void * closure) static
getter callback for the Surface attribute
References Base::BaseExceptionFreeCADError, getSurface(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTolerance()
PyObject * TopoShapeFacePy::staticCallback_getTolerance (PyObject * self, void * closure) static
getter callback for the Tolerance attribute
References Base::BaseExceptionFreeCADError, getTolerance(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getUVNodes()
PyObject * TopoShapeFacePy::staticCallback_getUVNodes (PyObject * self, PyObject * args) static
callback for the getUVNodes() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getUVNodes(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getWire()
PyObject * TopoShapeFacePy::staticCallback_getWire (PyObject * self, void * closure) static
getter callback for the Wire attribute
References Base::BaseExceptionFreeCADError, getWire(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isPartOfDomain()
PyObject * TopoShapeFacePy::staticCallback_isPartOfDomain (PyObject * self, PyObject * args) static
callback for the isPartOfDomain() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isPartOfDomain(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_makeHalfSpace()
PyObject * TopoShapeFacePy::staticCallback_makeHalfSpace (PyObject * self, PyObject * args) static
callback for the makeHalfSpace() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), makeHalfSpace(), and Base::PyObjectBase::PyObjectBase().
staticCallback_makeOffset()
PyObject * TopoShapeFacePy::staticCallback_makeOffset (PyObject * self, PyObject * args) static
callback for the makeOffset() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), makeOffset(), and Base::PyObjectBase::PyObjectBase().
staticCallback_normalAt()
PyObject * TopoShapeFacePy::staticCallback_normalAt (PyObject * self, PyObject * args) static
callback for the normalAt() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), normalAt(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setCenterOfMass()
int TopoShapeFacePy::staticCallback_setCenterOfMass (PyObject * self, PyObject * value, void * closure) static
setter callback for the CenterOfMass attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setMass()
int TopoShapeFacePy::staticCallback_setMass (PyObject * self, PyObject * value, void * closure) static
setter callback for the Mass attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setMatrixOfInertia()
int TopoShapeFacePy::staticCallback_setMatrixOfInertia (PyObject * self, PyObject * value, void * closure) static
setter callback for the MatrixOfInertia attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setOuterWire()
int TopoShapeFacePy::staticCallback_setOuterWire (PyObject * self, PyObject * value, void * closure) static
setter callback for the OuterWire attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setParameterRange()
int TopoShapeFacePy::staticCallback_setParameterRange (PyObject * self, PyObject * value, void * closure) static
setter callback for the ParameterRange attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPrincipalProperties()
int TopoShapeFacePy::staticCallback_setPrincipalProperties (PyObject * self, PyObject * value, void * closure) static
setter callback for the PrincipalProperties attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setStaticMoments()
int TopoShapeFacePy::staticCallback_setStaticMoments (PyObject * self, PyObject * value, void * closure) static
setter callback for the StaticMoments attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setSurface()
int TopoShapeFacePy::staticCallback_setSurface (PyObject * self, PyObject * value, void * closure) static
setter callback for the Surface attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setTolerance()
int TopoShapeFacePy::staticCallback_setTolerance (PyObject * self, PyObject * value, void * closure) static
setter callback for the Tolerance attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setTolerance().
staticCallback_setWire()
int TopoShapeFacePy::staticCallback_setWire (PyObject * self, PyObject * value, void * closure) static
setter callback for the Wire attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_tangentAt()
PyObject * TopoShapeFacePy::staticCallback_tangentAt (PyObject * self, PyObject * args) static
callback for the tangentAt() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and tangentAt().
staticCallback_validate()
PyObject * TopoShapeFacePy::staticCallback_validate (PyObject * self, PyObject * args) static
callback for the validate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and validate().
staticCallback_valueAt()
PyObject * TopoShapeFacePy::staticCallback_valueAt (PyObject * self, PyObject * args) static
callback for the valueAt() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and valueAt().
tangentAt()
PyObject * TopoShapeFacePy::tangentAt (PyObject * args)
implementer for the tangentAt() method
References getTopoShapePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_tangentAt().
validate()
PyObject * TopoShapeFacePy::validate (PyObject * args)
implementer for the validate() method
References Part::TopoShapePy::fix(), getTopoShapePtr(), Part::PartExceptionOCCError, and Part::TopoShape::setShape().
Referenced by staticCallback_validate().
valueAt()
PyObject * TopoShapeFacePy::valueAt (PyObject * args)
implementer for the valueAt() method
References getTopoShapePtr().
Referenced by staticCallback_valueAt().
Member Data Documentation
GetterSetter
PyGetSetDef TopoShapeFacePy::GetterSetter static
Attribute structure of TopoShapeFacePy.
Methods
PyMethodDef TopoShapeFacePy::Methods static
Methods structure of TopoShapeFacePy.
Type
PyTypeObject TopoShapeFacePy::Type static
Type structure of TopoShapeFacePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), Part::TopoShapeShellPy::add(), Part::MakePrismPy::add(), Part::BRepOffsetAPI_MakeFillingPy::add(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), Part::buildShapeEnumTypeMap(), Part::TopoShapePy::fixTolerance(), Part::TopoShapeWirePy::fixWire(), Fem::FemMeshPy::getccxVolumesByFace(), Fem::FemMeshPy::getFacesByFace(), Fem::FemMeshPy::getNodesByFace(), Part::TopoShapePy::getTolerance(), Fem::FemMeshPy::getVolumesByFace(), Part::MakePrismPy::init(), Part::TopoShapePy::inTolerance(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), Part::TopoShapeEdgePy::isSeam(), Part::TopoShapePy::limitTolerance(), Part::BRepOffsetAPI_MakeFillingPy::loadInitSurface(), Part::TopoShapePy::overTolerance(), Part::TopoShapeEdgePy::parameterAt(), Part::TopoShapeEdgePy::parameters(), Part::MakePrismPy::PyInit(), PyInit(), Part::TopoShapeShellPy::PyInit(), and Part::Curve2dPy::toShape().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/TopoShapeFacePy.h
Sources/FreeCAD/src/Mod/Part/App/TopoShapeFacePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/TopoShapeFacePy.cpp