FreeCAD: ArchStairs Namespace Reference
ArchStairs Namespace Reference
Workbenches » Python workbenches » Arch
The Stairs object and tools.
Functions
def makeRailing (stairs)
def makeStairs (baseobj=None, length=None, width=None, height=None, steps=None, name="Stairs")
Variables
zeroMM = FreeCAD.Units.Quantity('0mm')
Detailed Description
The Stairs object and tools.
This module provides tools to build Stairs objects.
Function Documentation
makeRailing()
def ArchStairs.makeRailing (stairs)
References ArchPipe.makePipe(), DraftVecUtils.neg(), ArchComponent.Component.onDocumentRestored(), draftutils.translate.QT_TRANSLATE_NOOP, DraftVecUtils.scale(), and DraftVecUtils.scaleTo().
Referenced by makeStairs().
makeStairs()
def ArchStairs.makeStairs (baseobj = None, length = None, width = None, height = None, steps = None, name = "Stairs")
makeStairs([baseobj,length,width,height,steps]): creates a Stairs
objects with given attributes.
References makeRailing().
Variable Documentation
zeroMM
ArchStairs.zeroMM = FreeCAD.Units.Quantity('0mm')