FreeCAD: SketcherGui::SoZoomTranslation Class Reference
SketcherGui::SoZoomTranslation Class Reference
#include <SoZoomTranslation.h>
Public Member Functions
SoZoomTranslation ()
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFVec3f abPos
Protected Member Functions
virtual void callback (SoCallbackAction *action)
virtual void doAction (SoAction *action)
virtual void getBoundingBox (SoGetBoundingBoxAction *action)
virtual void getMatrix (SoGetMatrixAction *action)
virtual void getPrimitiveCount (SoGetPrimitiveCountAction *action)
float getScaleFactor (SoAction *action) const
virtual void GLRender (SoGLRenderAction *action)
virtual void pick (SoPickAction *action)
virtual ~SoZoomTranslation ()
Constructor & Destructor Documentation
SoZoomTranslation()
SoZoomTranslation::SoZoomTranslation ()
References abPos.
~SoZoomTranslation()
virtual SketcherGui::SoZoomTranslation::~SoZoomTranslation () protected virtual
Member Function Documentation
callback()
void SoZoomTranslation::callback (SoCallbackAction * action) protected virtual
References doAction().
Referenced by qtunittest.GUITestResult::addError(), Mod.Test.unittestgui.GUITestResult::addError(), qtunittest.GUITestResult::addFailure(), Mod.Test.unittestgui.GUITestResult::addFailure(), ArchStructure.StructSelectionObserver::addSelection(), PathScripts.PathCamoticsGui.CamoticsSimulation::execute(), qtunittest.GUITestResult::startTest(), Mod.Test.unittestgui.GUITestResult::startTest(), qtunittest.GUITestResult::stopTest(), and Mod.Test.unittestgui.GUITestResult::stopTest().
doAction()
void SoZoomTranslation::doAction (SoAction * action) protected virtual
References abPos, and getScaleFactor().
Referenced by callback(), getBoundingBox(), getPrimitiveCount(), GLRender(), and pick().
getBoundingBox()
void SoZoomTranslation::getBoundingBox (SoGetBoundingBoxAction * action) protected virtual
References doAction().
getMatrix()
void SoZoomTranslation::getMatrix (SoGetMatrixAction * action) protected virtual
References abPos, and getScaleFactor().
getPrimitiveCount()
void SoZoomTranslation::getPrimitiveCount (SoGetPrimitiveCountAction * action) protected virtual
References doAction().
getScaleFactor()
float SoZoomTranslation::getScaleFactor (SoAction * action) const protected
References draftfunctions.scale::scale().
Referenced by doAction(), and getMatrix().
GLRender()
void SoZoomTranslation::GLRender (SoGLRenderAction * action) protected virtual
References doAction().
initClass()
void SoZoomTranslation::initClass (void) static
pick()
void SoZoomTranslation::pick (SoPickAction * action) protected virtual
References doAction().
Member Data Documentation
abPos
SoSFVec3f SketcherGui::SoZoomTranslation::abPos
Referenced by SketcherGui::EditModeConstraintCoinManager::detectPreselectionConstr(), doAction(), SketcherGui::EditModeConstraintCoinManager::drawConstraintIcons(), getMatrix(), SketcherGui::EditModeConstraintCoinManager::processConstraints(), and SoZoomTranslation().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/Gui/SoZoomTranslation.h
FreeCAD/src/Mod/Sketcher/Gui/SoZoomTranslation.cpp