FreeCAD: MeshGui::Ui_DlgDecimating Class Reference
MeshGui::Ui_DlgDecimating Class Reference
#include <ui_DlgDecimating.h>
Public Member Functions
void retranslateUi (QWidget *MeshGui__DlgDecimating)
void setupUi (QWidget *MeshGui__DlgDecimating)
Public Attributes
QCheckBox * checkAbsolueNumber
QGridLayout * gridLayout
QGridLayout * gridLayout_2
QGridLayout * gridLayout_3
QGroupBox * groupBoxReduction
QGroupBox * groupBoxTolerance
QHBoxLayout * horizontalLayout
QSpacerItem * horizontalSpacer
QSlider * sliderReduction
QSpacerItem * spacerItem
QSpinBox * spinBoxReduction
QDoubleSpinBox * spinBoxTolerance
QLabel * textLabel1
QLabel * textLabel2
Member Function Documentation
retranslateUi()
void MeshGui::Ui_DlgDecimating::retranslateUi (QWidget * MeshGui__DlgDecimating)
References checkAbsolueNumber, groupBoxReduction, groupBoxTolerance, textLabel1, textLabel2, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void MeshGui::Ui_DlgDecimating::setupUi (QWidget * MeshGui__DlgDecimating)
References checkAbsolueNumber, gridLayout, gridLayout_2, gridLayout_3, groupBoxReduction, groupBoxTolerance, horizontalLayout, horizontalSpacer, retranslateUi(), sliderReduction, spacerItem, spinBoxReduction, spinBoxTolerance, textLabel1, and textLabel2.
Member Data Documentation
checkAbsolueNumber
QCheckBox* MeshGui::Ui_DlgDecimating::checkAbsolueNumber
Referenced by retranslateUi(), and setupUi().
gridLayout
QGridLayout* MeshGui::Ui_DlgDecimating::gridLayout
Referenced by setupUi().
gridLayout_2
QGridLayout* MeshGui::Ui_DlgDecimating::gridLayout_2
Referenced by setupUi().
gridLayout_3
QGridLayout* MeshGui::Ui_DlgDecimating::gridLayout_3
Referenced by setupUi().
groupBoxReduction
QGroupBox* MeshGui::Ui_DlgDecimating::groupBoxReduction
Referenced by retranslateUi(), and setupUi().
groupBoxTolerance
QGroupBox* MeshGui::Ui_DlgDecimating::groupBoxTolerance
Referenced by retranslateUi(), and setupUi().
horizontalLayout
QHBoxLayout* MeshGui::Ui_DlgDecimating::horizontalLayout
Referenced by setupUi().
horizontalSpacer
QSpacerItem* MeshGui::Ui_DlgDecimating::horizontalSpacer
Referenced by setupUi().
sliderReduction
QSlider* MeshGui::Ui_DlgDecimating::sliderReduction
Referenced by setupUi().
spacerItem
QSpacerItem* MeshGui::Ui_DlgDecimating::spacerItem
Referenced by setupUi().
spinBoxReduction
QSpinBox* MeshGui::Ui_DlgDecimating::spinBoxReduction
Referenced by setupUi().
spinBoxTolerance
QDoubleSpinBox* MeshGui::Ui_DlgDecimating::spinBoxTolerance
Referenced by setupUi().
textLabel1
QLabel* MeshGui::Ui_DlgDecimating::textLabel1
Referenced by retranslateUi(), and setupUi().
textLabel2
QLabel* MeshGui::Ui_DlgDecimating::textLabel2
Referenced by retranslateUi(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Mesh/Gui/ui_DlgDecimating.h