FreeCAD: FemGui::TaskPostDataAlongLine Class Reference
FemGui::TaskPostDataAlongLine Class Reference
#include <TaskPostBoxes.h>
Public Member Functions
virtual void applyPythonCode ()
TaskPostDataAlongLine (Gui::ViewProviderDocumentObject *view, QWidget *parent=0)
virtual ~TaskPostDataAlongLine ()
Public Member Functions inherited from FemGui::TaskPostBox
virtual bool isGuiTaskOnly ()
TaskPostBox (Gui::ViewProviderDocumentObject *view, const QPixmap &icon, const QString &title, QWidget *parent=0)
~TaskPostBox ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (QWidget *parent=0)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (QWidget *parent=0)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Static Public Member Functions
static void pointCallback (void *ud, SoEventCallback *n)
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Member Functions inherited from FemGui::TaskPostBox
bool autoApply ()
App::DocumentObject * getObject ()
template<typename T >
T * getTypedObject ()
template<typename T >
T * getTypedView ()
Gui::ViewProviderDocumentObject * getView ()
void recompute ()
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Static Protected Member Functions inherited from FemGui::TaskPostBox
static void updateEnumerationList (App::PropertyEnumeration &, QComboBox *box)
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskPostDataAlongLine()
TaskPostDataAlongLine::TaskPostDataAlongLine (Gui::ViewProviderDocumentObject * view, QWidget * parent = 0)
References Gui::BitmapFactory(), draftgeoutils.intersections::connect(), Base::Persistence::getClassTypeId(), FemGui::TaskPostBox::getObject(), QSint::ActionGroup::groupLayout(), FemGui::TaskPostBox::updateEnumerationList(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
~TaskPostDataAlongLine()
TaskPostDataAlongLine::~TaskPostDataAlongLine () virtual
Member Function Documentation
applyPythonCode()
void TaskPostDataAlongLine::applyPythonCode () virtual
Implements FemGui::TaskPostBox.
pointCallback()
void TaskPostDataAlongLine::pointCallback (void * ud, SoEventCallback * n) static
References FemGui::PointMarker::addPoint(), Base::Console(), FemGui::PointMarker::countPoints(), and Base::ConsoleSingleton::Message().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Fem/Gui/TaskPostBoxes.h
Sources/FreeCAD/src/Mod/Fem/Gui/TaskPostBoxes.cpp