FreeCAD: VISCOUS_2D::_Segment Struct Reference
VISCOUS_2D::_Segment Struct Reference
Segment connecting inner ends of two _LayerEdge's.
Public Member Functions
const gp_XY & p1 () const
const gp_XY & p2 () const
Detailed Description
Segment connecting inner ends of two _LayerEdge's.
Member Function Documentation
p1()
const gp_XY & VISCOUS_2D::_Segment::p1 () const
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_trackers.dimTracker::calc(), VISCOUS_2D::_SegmentIntersection::Compute(), draftguitools.gui_trackers.rectangleTracker::isInside(), and draftguitools.gui_trackers.dimTracker::update().
p2()
const gp_XY & VISCOUS_2D::_Segment::p2 () const
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_trackers.dimTracker::calc(), VISCOUS_2D::_SegmentIntersection::Compute(), draftviewproviders.view_dimension.ViewProviderLinearDimension::draw_dim_arrows(), draftguitools.gui_trackers.rectangleTracker::isInside(), and draftguitools.gui_trackers.dimTracker::update().
The documentation for this struct was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_ViscousLayers2D.cpp