FreeCAD: PartGui::CircleFromThreePoints Class Reference
PartGui::CircleFromThreePoints Class Reference
Public Member Functions
CircleFromThreePoints ()
QString command (App::Document *doc) const
bool pickedPoint (const SoPickedPoint *point)
Public Member Functions inherited from PartGui::Picker
virtual QString command (App::Document *) const =0
void createPrimitive (QWidget *widget, const QString &, Gui::Document *)
virtual bool pickedPoint (const SoPickedPoint *point)=0
Picker ()
QString toPlacement (const gp_Ax2 &) const
virtual ~Picker ()
Additional Inherited Members
Public Attributes inherited from PartGui::Picker
int exitCode
QEventLoop loop
Constructor & Destructor Documentation
CircleFromThreePoints()
PartGui::CircleFromThreePoints::CircleFromThreePoints ()
Member Function Documentation
command()
QString PartGui::CircleFromThreePoints::command (App::Document * doc) const virtual
Implements PartGui::Picker.
References PartGui::gce_ErrorStatusText(), Base::UnitsApi::getDecimals(), Base::toDegrees(), and PartGui::Picker::toPlacement().
Referenced by femcommands.manager.CommandManager::GetResources().
pickedPoint()
bool PartGui::CircleFromThreePoints::pickedPoint (const SoPickedPoint * point) virtual
Implements PartGui::Picker.
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Part/Gui/DlgPrimitives.cpp