FreeCAD: Gui::PropertyEditor::PropertyItem Class Reference
Gui::PropertyEditor::PropertyItem Class Reference
#include <PropertyItem.h>
Public Member Functions
void appendChild (PropertyItem *child)
virtual void assignProperty (const App::Property *)
virtual void bind (const App::ObjectIdentifier &_path)
virtual void bind (const App::Property &prop)
override the bind functions to ensure we issue the propertyBound() call, which is then overloaded by childs which like to be informed of a binding
PropertyItem * child (int row)
int childCount () const
int columnCount () const
virtual QWidget * createEditor (QWidget *parent, const QObject *receiver, const char *method) const
Creates the appropriate editor for this item and sets the editor to the value of overrideValue().
QWidget * createExpressionEditor (QWidget *parent, const QObject *receiver, const char *method) const
virtual QVariant data (int column, int role) const
int decimals () const
virtual QVariant editorData (QWidget *editor) const
QString expressionAsString () const
QVariant expressionEditorData (QWidget *editor) const
Qt::ItemFlags flags (int column) const
App::Property * getFirstProperty ()
const App::Property * getFirstProperty () const
const std::vector< App::Property * > & getPropertyData () const
bool hasAnyExpression () const
bool hasProperty (const App::Property *) const
void insertChild (int, PropertyItem *child)
bool isLinked () const
bool isReadOnly () const
virtual bool isSeparator () const
PropertyItem * parent () const
virtual void propertyBound ()
QString propertyName () const
void removeChildren (int from, int to)
PropertyItem::removeChildren Deletes the children in the range of [from, to].
bool removeProperty (const App::Property *)
void reset ()
int row () const
bool setData (const QVariant &value)
void setDecimals (int)
virtual void setEditorData (QWidget *editor, const QVariant &data) const
void setExpressionEditorData (QWidget *editor, const QVariant &data) const
void setLinked (bool)
void setParent (PropertyItem *parent)
void setPropertyData (const std::vector< App::Property * > &)
Sets the current property objects.
void setPropertyName (const QString &)
void setPropertyValue (const QString &)
void setReadOnly (bool)
PropertyItem * takeChild (int)
PropertyItem::takeChild Removes the child at index row but doesn't delete it.
bool testStatus (App::Property::Status pos) const
void updateData ()
~PropertyItem ()
Public Member Functions inherited from Gui::ExpressionBinding
virtual bool apply ()
virtual bool apply (const std::string &propName)
bool autoApply () const
ExpressionBinding ()
QPixmap getIcon (const char *name, const QSize &size) const
bool hasExpression () const
bool isBound () const
void setAutoApply (bool value)
virtual ~ExpressionBinding ()
Protected Member Functions
virtual QVariant decoration (const QVariant &) const
virtual QVariant displayName () const
virtual void initialize ()
virtual void onChange ()
PropertyItem ()
virtual void setValue (const QVariant &)
virtual QVariant toolTip (const App::Property *) const
virtual QVariant toString (const QVariant &) const
virtual QVariant value (const App::Property *) const
Protected Member Functions inherited from Gui::ExpressionBinding
void expressionChange (const App::ObjectIdentifier &id)
std::string getEscapedExpressionString () const
boost::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
const App::ObjectIdentifier & getPath () const
virtual void setExpression (boost::shared_ptr< App::Expression > expr)
Protected Attributes
QList< PropertyItem * > childItems
bool cleared
QString displayText
bool linked
PropertyItem * parentItem
int precision
std::vector< App::Property * > propertyItems
QString propName
bool readonly
Protected Attributes inherited from Gui::ExpressionBinding
boost::signals2::scoped_connection connection
QPalette defaultPalette
int iconHeight
QLabel * iconLabel
bool m_autoApply
Constructor & Destructor Documentation
~PropertyItem()
PropertyItem::~PropertyItem ()
PropertyItem()
PropertyItem::PropertyItem () protected
References Base::UnitsApi::getDecimals().
Member Function Documentation
appendChild()
void PropertyItem::appendChild (PropertyItem * child)
Referenced by Gui::PropertyEditor::PropertyModel::appendProperty(), Gui::PropertyEditor::PropertyModel::buildUp(), and SketcherGui::PropertyConstraintListItem::initialize().
assignProperty()
void PropertyItem::assignProperty (const App::Property *) virtual
Referenced by Gui::PropertyEditor::PropertyModel::updateProperty().
bind() [1/2]
void PropertyItem::bind (const App::ObjectIdentifier & _path) virtual
Reimplemented from Gui::ExpressionBinding.
References Gui::ExpressionBinding::bind().
bind() [2/2]
void PropertyItem::bind (const App::Property & prop) virtual
override the bind functions to ensure we issue the propertyBound() call, which is then overloaded by childs which like to be informed of a binding
Reimplemented from Gui::ExpressionBinding.
References Gui::ExpressionBinding::bind().
Referenced by SketcherGui::PropertyConstraintListItem::initialize().
child()
PropertyItem * PropertyItem::child (int row)
References value().
Referenced by Gui::PropertyEditor::PropertyModel::appendProperty(), Gui::PropertyEditor::PropertyModel::index(), Gui::PropertyEditor::PropertyModel::removeProperty(), Gui::PropertyEditor::PropertyModel::updateProperty(), Gui::PropertyEditor::PropertyPlacementItem::value(), and SketcherGui::PropertyConstraintListItem::value().
childCount()
int PropertyItem::childCount () const
Referenced by Gui::PropertyEditor::PropertyModel::appendProperty(), Gui::PropertyEditor::PropertyModel::removeProperty(), Gui::PropertyEditor::PropertyModel::rowCount(), and Gui::PropertyEditor::PropertyModel::updateProperty().
columnCount()
int PropertyItem::columnCount () const
Referenced by Gui::PropertyEditor::PropertyModel::columnCount().
createEditor()
QWidget * PropertyItem::createEditor (QWidget * parent, const QObject * receiver, const char * method) const virtual
Creates the appropriate editor for this item and sets the editor to the value of overrideValue().
Reimplemented in PartGui::PropertyEnumAttacherItem.
Referenced by Gui::PropertyEditor::PropertyItemDelegate::createEditor().
createExpressionEditor()
QWidget * PropertyItem::createExpressionEditor (QWidget * parent, const QObject * receiver, const char * method) const
References Gui::ExpLineEdit::bind(), draftgeoutils.intersections::connect(), draftfunctions.svgshapes::getPath(), and Gui::ExpressionBinding::setAutoApply().
Referenced by Gui::PropertyEditor::PropertyItemDelegate::createEditor().
data()
QVariant PropertyItem::data (int column, int role) const virtual
Reimplemented in Gui::PropertyEditor::PropertyLinkItem.
References App::Property::LockDynamic, parent(), App::Property::PropDynamic, Gui::PropertyView::showAll(), and DraftVecUtils::toString().
Referenced by Gui::PropertyEditor::PropertyModel::data(), Gui::PropertyEditor::PropertyLinkItem::data(), ArchSchedule.CommandArchSchedule::IsActive(), Gui::PropertyEditor::PropertyModel::setData(), Gui::PropertyEditor::PropertyVectorListItem::setValue(), Gui::PropertyEditor::PropertyStringListItem::setValue(), Gui::PropertyEditor::PropertyFloatListItem::setValue(), Gui::PropertyEditor::PropertyIntegerListItem::setValue(), Gui::PropertyEditor::PropertyMaterialListItem::setValue(), and Gui::PropertyEditor::PropertyVectorListItem::toString().
decimals()
int PropertyItem::decimals () const
References draftgeoutils.general::precision().
Referenced by Gui::PropertyEditor::PropertyVectorListItem::setValue(), Gui::PropertyEditor::PropertyMatrixItem::setValue(), Gui::PropertyEditor::PropertyColorItem::setValue(), Gui::PropertyEditor::PropertyMaterialItem::setValue(), Gui::PropertyEditor::PropertyMaterialListItem::setValue(), Gui::PropertyEditor::PropertyPlacementItem::toolTip(), and Gui::PropertyEditor::PropertyFloatListItem::value().
decoration()
QVariant PropertyItem::decoration (const QVariant &) const protected virtual
Reimplemented in Gui::PropertyEditor::PropertyMaterialListItem, Gui::PropertyEditor::PropertyMaterialItem, and Gui::PropertyEditor::PropertyColorItem.
displayName()
QVariant PropertyItem::displayName () const protected virtual
editorData()
QVariant PropertyItem::editorData (QWidget * editor) const virtual
Reimplemented in PartGui::PropertyEnumAttacherItem.
Referenced by Gui::PropertyEditor::PropertyItemDelegate::setModelData().
expressionAsString()
QString PropertyItem::expressionAsString () const
Referenced by Gui::PropertyEditor::PropertyPlacementItem::value().
expressionEditorData()
QVariant PropertyItem::expressionEditorData (QWidget * editor) const
Referenced by Gui::PropertyEditor::PropertyItemDelegate::setModelData().
flags()
Qt::ItemFlags PropertyItem::flags (int column) const
Referenced by Gui::PropertyEditor::PropertyModel::flags().
getFirstProperty() [1/2]
App::Property * PropertyItem::getFirstProperty ()
Referenced by PartGui::PropertyEnumAttacherItem::openTask().
getFirstProperty() [2/2]
const App::Property * PropertyItem::getFirstProperty () const
getPropertyData()
const std::vector< App::Property * > & PropertyItem::getPropertyData (void) const
Referenced by Gui::PropertyEditor::PropertyEditor::contextMenuEvent(), FemGui::PropertyFemMeshItem::value(), and MeshGui::PropertyMeshKernelItem::value().
hasAnyExpression()
bool PropertyItem::hasAnyExpression () const
References Gui::ExpressionBinding::hasExpression().
hasProperty()
bool PropertyItem::hasProperty (const App::Property * prop) const
References DraftVecUtils::find().
Referenced by Gui::PropertyEditor::PropertyModel::removeProperty(), Gui::PropertyEditor::PropertyEditor::updateEditorMode(), and Gui::PropertyEditor::PropertyModel::updateProperty().
initialize()
void PropertyItem::initialize () protected virtual
Reimplemented in SketcherGui::PropertyConstraintListItem, MeshGui::PropertyMeshKernelItem, and FemGui::PropertyFemMeshItem.
insertChild()
void PropertyItem::insertChild (int index, PropertyItem * child)
Referenced by Gui::PropertyEditor::PropertyModel::appendProperty().
isLinked()
bool PropertyItem::isLinked () const
isReadOnly()
bool PropertyItem::isReadOnly () const
Referenced by Gui::PropertyEditor::PropertyItemDelegate::createEditor(), and PartGui::PropertyEnumAttacherItem::createEditor().
isSeparator()
virtual bool Gui::PropertyEditor::PropertyItem::isSeparator () const virtual
Referenced by Gui::PropertyEditor::PropertyModel::appendProperty(), and Gui::PropertyEditor::PropertyModel::propertyPathFromIndex().
onChange()
void PropertyItem::onChange () protected virtual
Reimplemented from Gui::ExpressionBinding.
parent()
PropertyItem * PropertyItem::parent () const
Referenced by PartGui::PropertyEnumAttacherItem::createEditor(), data(), PartGui::PropertyEnumAttacherItem::openTask(), Gui::PropertyEditor::PropertyModel::parent(), Gui::PropertyEditor::PropertyModel::propertyPathFromIndex(), and setData().
propertyBound()
virtual void Gui::PropertyEditor::PropertyItem::propertyBound () virtual
Reimplemented in Gui::PropertyEditor::PropertyVectorItem.
propertyName()
QString PropertyItem::propertyName () const
References draftutils.translate::QT_TRANSLATE_NOOP.
Referenced by PathScripts.PathSetupSheetGui.OpTaskPanel::accept(), Gui::PropertyEditor::PropertyModel::appendProperty(), Gui::PropertyEditor::PropertyModel::propertyIndexFromPath(), Gui::PropertyEditor::PropertyModel::propertyPathFromIndex(), and PathScripts.PathSetupSheetGui.OpTaskPanel::setupUi().
removeChildren()
void PropertyItem::removeChildren (int from, int to)
PropertyItem::removeChildren Deletes the children in the range of [from, to].
Referenced by Gui::PropertyEditor::PropertyModel::removeRows().
removeProperty()
bool PropertyItem::removeProperty (const App::Property * prop)
References DraftVecUtils::find().
Referenced by Gui::PropertyEditor::PropertyModel::removeProperty().
reset()
void PropertyItem::reset ()
Referenced by Gui::PropertyEditor::PropertyModel::buildUp(), and draftguitools.gui_trackers.gridTracker::set().
row()
int PropertyItem::row () const
Referenced by Gui::PropertyEditor::PropertyModel::parent().
setData()
bool PropertyItem::setData (const QVariant & value)
References parent().
Referenced by Gui::PropertyEditor::PropertyModel::setData().
setDecimals()
void PropertyItem::setDecimals (int prec)
setEditorData()
void PropertyItem::setEditorData (QWidget * editor, const QVariant & data) const virtual
Reimplemented in PartGui::PropertyEnumAttacherItem, and Gui::PropertyEditor::PropertyAngleItem.
Referenced by Gui::PropertyEditor::PropertyItemDelegate::setEditorData().
setExpressionEditorData()
void PropertyItem::setExpressionEditorData (QWidget * editor, const QVariant & data) const
Referenced by Gui::PropertyEditor::PropertyItemDelegate::setEditorData().
setLinked()
void PropertyItem::setLinked (bool l)
Referenced by Gui::PropertyEditor::PropertyModel::buildUp().
setParent()
void PropertyItem::setParent (PropertyItem * parent)
Referenced by Gui::PropertyEditor::PropertyModel::appendProperty(), Gui::PropertyEditor::PropertyModel::buildUp(), SketcherGui::PropertyConstraintListItem::initialize(), FemGui::PropertyFemMeshItem::PropertyFemMeshItem(), Gui::PropertyEditor::PropertyMaterialItem::PropertyMaterialItem(), Gui::PropertyEditor::PropertyMaterialListItem::PropertyMaterialListItem(), Gui::PropertyEditor::PropertyMatrixItem::PropertyMatrixItem(), MeshGui::PropertyMeshKernelItem::PropertyMeshKernelItem(), Gui::PropertyEditor::PropertyPlacementItem::PropertyPlacementItem(), Gui::PropertyEditor::PropertyVectorDistanceItem::PropertyVectorDistanceItem(), Gui::PropertyEditor::PropertyVectorItem::PropertyVectorItem(), and takeChild().
setPropertyData()
void PropertyItem::setPropertyData (const std::vector< App::Property * > & items)
Sets the current property objects.
References draftgeoutils.faces::bind(), and App::PropertyContainer::isReadOnly().
Referenced by Gui::PropertyEditor::PropertyModel::appendProperty(), and Gui::PropertyEditor::PropertyModel::buildUp().
setPropertyName()
void PropertyItem::setPropertyName (const QString & name)
References femsolver.report::display(), and draftutils.translate::translate().
Referenced by SketcherGui::PropertyConstraintListItem::initialize().
setPropertyValue()
void PropertyItem::setPropertyValue (const QString & value)
References Gui::Command::App, Base::Console(), Base::ConsoleSingleton::Error(), Base::Persistence::getClassTypeId(), App::PropertyContainer::getPropertyPrefix(), Base::BaseClass::isDerivedFrom(), App::PropertyContainer::isReadOnly(), and App::Property::ReadOnly.
Referenced by Gui::PropertyEditor::PropertyVectorListItem::setValue(), Gui::PropertyEditor::PropertyVectorDistanceItem::setValue(), Gui::PropertyEditor::PropertyMatrixItem::setValue(), Gui::PropertyEditor::PropertyPlacementItem::setValue(), Gui::PropertyEditor::PropertyEnumItem::setValue(), Gui::PropertyEditor::PropertyStringListItem::setValue(), Gui::PropertyEditor::PropertyFloatListItem::setValue(), Gui::PropertyEditor::PropertyIntegerListItem::setValue(), Gui::PropertyEditor::PropertyColorItem::setValue(), Gui::PropertyEditor::PropertyMaterialItem::setValue(), Gui::PropertyEditor::PropertyMaterialListItem::setValue(), Gui::PropertyEditor::PropertyFileItem::setValue(), Gui::PropertyEditor::PropertyPathItem::setValue(), Gui::PropertyEditor::PropertyTransientFileItem::setValue(), and Gui::PropertyEditor::PropertyLinkItem::setValue().
setReadOnly()
void PropertyItem::setReadOnly (bool ro)
Referenced by FemGui::PropertyFemMeshItem::initialize(), and MeshGui::PropertyMeshKernelItem::initialize().
setValue()
void PropertyItem::setValue (const QVariant &) protected virtual
Reimplemented in Gui::PropertyEditor::PropertyLinkItem, SketcherGui::PropertyConstraintListItem, MeshGui::PropertyMeshKernelItem, FemGui::PropertyFemMeshItem, Gui::PropertyEditor::PropertyTransientFileItem, Gui::PropertyEditor::PropertyPathItem, Gui::PropertyEditor::PropertyFileItem, Gui::PropertyEditor::PropertyMaterialListItem, Gui::PropertyEditor::PropertyMaterialItem, Gui::PropertyEditor::PropertyColorItem, Gui::PropertyEditor::PropertyIntegerListItem, Gui::PropertyEditor::PropertyFloatListItem, Gui::PropertyEditor::PropertyStringListItem, Gui::PropertyEditor::PropertyEnumItem, Gui::PropertyEditor::PropertyPlacementItem, Gui::PropertyEditor::PropertyMatrixItem, Gui::PropertyEditor::PropertyVectorDistanceItem, Gui::PropertyEditor::PropertyVectorListItem, Gui::PropertyEditor::PropertyVectorItem, Gui::PropertyEditor::PropertyBoolItem, Gui::PropertyEditor::PropertyFloatConstraintItem, Gui::PropertyEditor::PropertyUnitItem, Gui::PropertyEditor::PropertyFloatItem, Gui::PropertyEditor::PropertyIntegerConstraintItem, Gui::PropertyEditor::PropertyIntegerItem, Gui::PropertyEditor::PropertyFontItem, and Gui::PropertyEditor::PropertyStringItem.
takeChild()
PropertyItem * PropertyItem::takeChild (int row)
PropertyItem::takeChild Removes the child at index row but doesn't delete it.
References setParent().
testStatus()
bool PropertyItem::testStatus (App::Property::Status pos) const
toolTip()
QVariant PropertyItem::toolTip (const App::Property * prop) const protected virtual
Reimplemented in MeshGui::PropertyMeshKernelItem, FemGui::PropertyFemMeshItem, Gui::PropertyEditor::PropertyTransientFileItem, Gui::PropertyEditor::PropertyPathItem, Gui::PropertyEditor::PropertyFileItem, Gui::PropertyEditor::PropertyMaterialListItem, Gui::PropertyEditor::PropertyMaterialItem, Gui::PropertyEditor::PropertyPlacementItem, and Gui::PropertyEditor::PropertyMatrixItem.
References App::Property::getDocumentation(), and draftutils.translate::translate().
toString()
QVariant PropertyItem::toString (const QVariant & prop) const protected virtual
Reimplemented in Gui::PropertyEditor::PropertyLinkItem, SketcherGui::PropertyConstraintListItem, Gui::PropertyEditor::PropertyMaterialListItem, Gui::PropertyEditor::PropertyMaterialItem, Gui::PropertyEditor::PropertyColorItem, Gui::PropertyEditor::PropertyIntegerListItem, Gui::PropertyEditor::PropertyFloatListItem, Gui::PropertyEditor::PropertyStringListItem, Gui::PropertyEditor::PropertyPlacementItem, Gui::PropertyEditor::PropertyMatrixItem, Gui::PropertyEditor::PropertyVectorDistanceItem, Gui::PropertyEditor::PropertyVectorListItem, Gui::PropertyEditor::PropertyVectorItem, Gui::PropertyEditor::PropertyAngleItem, Gui::PropertyEditor::PropertyFloatConstraintItem, Gui::PropertyEditor::PropertyUnitItem, Gui::PropertyEditor::PropertyFloatItem, Gui::PropertyEditor::PropertyIntegerConstraintItem, and Gui::PropertyEditor::PropertyIntegerItem.
Referenced by Gui::PropertyEditor::PropertyIntegerItem::toString(), and Gui::PropertyEditor::PropertyIntegerConstraintItem::toString().
updateData()
void PropertyItem::updateData ()
References App::PropertyContainer::isReadOnly(), and App::Property::ReadOnly.
Referenced by PathScripts.PathJobDlg.JobCreate::exec_(), draftviewproviders.view_dimension.ViewProviderLinearDimension::onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension::onChanged(), draftviewproviders.view_wire.ViewProviderWire::onChanged(), PathScripts.PathOpGui.TaskPanelPage::pageUpdateData(), PathScripts.PathSetupSheetGui.OpTaskPanel::setupUi(), Gui::PropertyEditor::PropertyEditor::updateEditorMode(), and Gui::PropertyEditor::PropertyModel::updateProperty().
value()
QVariant PropertyItem::value (const App::Property *) const protected virtual
Reimplemented in Gui::PropertyEditor::PropertyLinkItem, SketcherGui::PropertyConstraintListItem, MeshGui::PropertyMeshKernelItem, FemGui::PropertyFemMeshItem, Gui::PropertyEditor::PropertyTransientFileItem, Gui::PropertyEditor::PropertyPathItem, Gui::PropertyEditor::PropertyFileItem, Gui::PropertyEditor::PropertyMaterialListItem, Gui::PropertyEditor::PropertyMaterialItem, Gui::PropertyEditor::PropertyColorItem, Gui::PropertyEditor::PropertyIntegerListItem, Gui::PropertyEditor::PropertyFloatListItem, Gui::PropertyEditor::PropertyStringListItem, Gui::PropertyEditor::PropertyEnumItem, Gui::PropertyEditor::PropertyPlacementItem, Gui::PropertyEditor::PropertyMatrixItem, Gui::PropertyEditor::PropertyVectorDistanceItem, Gui::PropertyEditor::PropertyVectorListItem, Gui::PropertyEditor::PropertyVectorItem, Gui::PropertyEditor::PropertyBoolItem, Gui::PropertyEditor::PropertyFloatConstraintItem, Gui::PropertyEditor::PropertyUnitItem, Gui::PropertyEditor::PropertyFloatItem, Gui::PropertyEditor::PropertyIntegerConstraintItem, Gui::PropertyEditor::PropertyIntegerItem, Gui::PropertyEditor::PropertyFontItem, and Gui::PropertyEditor::PropertyStringItem.
Referenced by child(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), and Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue().
Member Data Documentation
childItems
QList<PropertyItem*> Gui::PropertyEditor::PropertyItem::childItems protected
cleared
bool Gui::PropertyEditor::PropertyItem::cleared protected
displayText
QString Gui::PropertyEditor::PropertyItem::displayText protected
linked
bool Gui::PropertyEditor::PropertyItem::linked protected
parentItem
PropertyItem* Gui::PropertyEditor::PropertyItem::parentItem protected
precision
int Gui::PropertyEditor::PropertyItem::precision protected
Referenced by ifc2x3.ifcgeometricrepresentationsubcontext::ifcgeometricrepresentationcontext_precision(), and ifc4.ifcgeometricrepresentationsubcontext::ifcgeometricrepresentationcontext_precision().
propertyItems
std::vector<App::Property*> Gui::PropertyEditor::PropertyItem::propertyItems protected
Referenced by Gui::PropertyEditor::PropertyLinkItem::data(), and Gui::PropertyEditor::PropertyLinkItem::toString().
propName
QString Gui::PropertyEditor::PropertyItem::propName protected
readonly
bool Gui::PropertyEditor::PropertyItem::readonly protected
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/propertyeditor/PropertyItem.h
Sources/FreeCAD/src/Gui/propertyeditor/PropertyItem.cpp