FreeCAD: App::PropertyEnumeration Class Reference
App::PropertyEnumeration Class Reference
Property wrapper around an Enumeration object.
#include <PropertyStandard.h>
Public Member Functions
virtual Property * Copy (void) const
Returns a new copy of the property (mainly for Undo/Redo and transactions)
const char * getEditorName (void) const
Get the class name of the associated property editor item.
const Enumeration & getEnum (void) const
Returns Enumeration object.
std::vector< std::string > getEnumVector (void) const
get all possible enum values as vector of strings
virtual const boost::any getPathValue (const App::ObjectIdentifier &) const
Get value of property.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
virtual bool getPyPathValue (const ObjectIdentifier &path, Py::Object &r) const
Get Python value of property.
long getValue (void) const
Returns current value of the enumeration as an integer.
const char * getValueAsString (void) const
get the value as string
bool hasEnums () const
get the pointer to the enum list
bool isPartOf (const char *value) const
checks if a string is included in the enumeration
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
bool isValid (void) const
Returns true if the instance is in a usable state.
bool isValue (const char *value) const
checks if the property is set to a certain string value
virtual void Paste (const Property &from)
Paste the value from the property (mainly for Undo/Redo and transactions)
PropertyEnumeration ()
Standard constructor.
PropertyEnumeration (const Enumeration &e)
Obvious constructor.
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
void setEditorName (const char *name)
void setEnums (const char **plEnums)
Enumeration methods.
void setEnums (const std::vector< std::string > &Enums)
setting the enumaration string as vector of strings This makes the enumeration custom.
void setEnumVector (const std::vector< std::string > &)
set enum values as vector of strings
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual void setPyObject (PyObject *)
virtual bool setPyPathValue (const App::ObjectIdentifier &path, const Py::Object &value)
void setValue (const char *value)
set the enum by a string is slower than setValue(long).
void setValue (const Enumeration &source)
Setter using Enumeration.
void setValue (long)
set directly the enum value In DEBUG checks for boundaries.
virtual ~PropertyEnumeration ()
destructor
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual Property * Copy (void) const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
int64_t getID () const
Return a unique ID for the property.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const char * getName (void) const
Get the name of this property in the belonging container With hasName() it can be checked beforehand if a valid name is set.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
bool hasName () const
Check if the property has a name set.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , Busy = 15 ,
CopyOnChange = 16 , UserEdit = 17 , PropStaticBegin = 21 , PropDynamic = 21 ,
PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 , PropTransient = 25 ,
PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 , User1 = 28 ,
User2 = 29 , User3 = 30 , User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Check if the passed name is valid.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Detailed Description
Property wrapper around an Enumeration object.
Constructor & Destructor Documentation
PropertyEnumeration() [1/2]
PropertyEnumeration::PropertyEnumeration ()
Standard constructor.
Referenced by Copy().
PropertyEnumeration() [2/2]
PropertyEnumeration::PropertyEnumeration (const Enumeration & e)
Obvious constructor.
~PropertyEnumeration()
PropertyEnumeration::~PropertyEnumeration () virtual
destructor
Member Function Documentation
Copy()
Property * PropertyEnumeration::Copy (void) const virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References PropertyEnumeration().
getEditorName()
const char * App::PropertyEnumeration::getEditorName (void) const virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
getEnum()
const Enumeration & PropertyEnumeration::getEnum (void) const
Returns Enumeration object.
Referenced by App::FeatureTest::execute().
getEnumVector()
std::vector< std::string > PropertyEnumeration::getEnumVector (void) const
get all possible enum values as vector of strings
Referenced by PartDesignGui::TaskHoleParameters::changedObject(), Save(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), PartDesignGui::TaskHoleParameters::TaskHoleParameters(), and FemGui::TaskPostBox::updateEnumerationList().
getPathValue()
const boost::any PropertyEnumeration::getPathValue (const App::ObjectIdentifier & path) const virtual
Get value of property.
Reimplemented from App::Property.
References getPyPathValue(), getValue(), getValueAsString(), and App::pyObjectToAny().
getPyObject()
PyObject * PropertyEnumeration::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
References getValueAsString().
getPyPathValue()
bool PropertyEnumeration::getPyPathValue (const ObjectIdentifier & , Py::Object &) const virtual
Get Python value of property.
Reimplemented from App::Property.
References App::PropertyString::getPyObject(), getValue(), getValueAsString(), and App::PropertyString::setValue().
Referenced by getPathValue().
getValue()
long PropertyEnumeration::getValue (void) const
Returns current value of the enumeration as an integer.
Referenced by PartGui::TaskDlgAttacher::accept(), PartDesignGui::TaskChamferParameters::apply(), PartDesignGui::TaskHelixParameters::apply(), PartDesignGui::TaskHoleParameters::changedObject(), SurfaceGui::GeomFillSurface::changeFillType(), PartDesign::SubShapeBinder::checkCopyOnChange(), Part::Extrusion::computeFinalParameters(), PartGui::ViewProvider2DObjectGrid::createGrid(), PartGui::DlgPrimitives::DlgPrimitives(), TechDrawGui::QGIViewDimension::drawAngle(), TechDrawGui::QGIViewBalloon::drawBalloon(), TechDrawGui::QGIViewDimension::drawDiameter(), TechDrawGui::QGIViewDimension::drawDistance(), Gui::ViewProviderAnnotationLabel::drawImage(), TechDrawGui::QGIViewDimension::drawRadius(), Fem::FemMeshShapeNetgenObject::execute(), Fem::FemPostScalarClipFilter::execute(), Fem::FemPostWarpVectorFilter::execute(), Fem::FemPostPipeline::execute(), Part::RuledSurface::execute(), Part::Sweep::execute(), Part::Thickness::execute(), Part::Helix::execute(), PartDesign::Helix::execute(), PartDesign::Pipe::execute(), PartDesign::Thickness::execute(), Robot::TrajectoryDressUpObject::execute(), Part::Offset::execute(), Part::Offset2D::execute(), PartDesign::Chamfer::execute(), PartDesign::SubShapeBinder::execute(), TechDraw::DrawViewArch::execute(), Part::AttachExtension::extensionOnChanged(), Gui::ViewProviderLink::finishRestoring(), PathGui::ViewProviderPath::getBoundColor(), Surface::GeomFillSurface::getFillingStyle(), getPathValue(), getPyPathValue(), PartDesign::ProfileBased::getSupportFace(), TechDrawGui::QGILeaderLine::makeLeaderPath(), PartDesign::Chamfer::mustExecute(), Gui::ViewProviderAnnotation::onChanged(), Fem::FemPostScalarClipFilter::onChanged(), Fem::FemPostWarpVectorFilter::onChanged(), Fem::FemPostPipeline::onChanged(), MeshGui::ViewProviderMesh::onChanged(), PartDesign::Line::onChanged(), PartDesign::Plane::onChanged(), PartDesign::Helix::onChanged(), PartDesign::Hole::onChanged(), PathGui::ViewProviderPath::onChanged(), PointsGui::ViewProviderPoints::onChanged(), Gui::ViewProviderDocumentObject::onChanged(), Gui::ViewProviderLink::onChanged(), PartGui::ViewProviderPartExt::onChanged(), PartDesign::SubShapeBinder::onChanged(), PartDesignGui::ViewProviderBody::onChanged(), PartDesignGui::ViewProviderBoolean::onChanged(), TechDraw::DrawViewDimension::onChanged(), TechDraw::DrawViewDimension::onDocumentRestored(), Part::AttachExtension::onExtendedDocumentRestored(), Gui::ElementColors::Private::Private(), Restore(), PartDesign::Helix::safePitch(), TechDrawGui::TaskSectionView::saveSectionState(), TechDrawGui::QGILeaderLine::setArrows(), PartDesignGui::ViewProviderBody::setDisplayMode(), SurfaceGui::GeomFillSurface::setEditedObject(), PartDesignGui::ViewProviderDatumLine::setExtents(), PartDesignGui::ViewProviderDatumPlane::setExtents(), PartDesignGui::ViewProviderBody::setOverrideMode(), TechDrawGui::TaskSectionView::setUiEdit(), TechDrawGui::TaskLeaderLine::setUiEdit(), TechDrawGui::TaskRichAnno::setUiEdit(), TechDrawGui::TaskDetail::setUiFromFeat(), TechDrawGui::TaskSectionView::setUiPrimary(), PartDesign::Pipe::setupAlgorithm(), PartDesign::SubShapeBinder::setupCopyOnChange(), PartGui::TaskAttacher::TaskAttacher(), TechDrawGui::TaskBalloon::TaskBalloon(), PartDesignGui::TaskBooleanParameters::TaskBooleanParameters(), TechDrawGui::TaskDimension::TaskDimension(), PartDesignGui::TaskHoleParameters::TaskHoleParameters(), PartDesignGui::TaskPipeOrientation::TaskPipeOrientation(), PartDesignGui::TaskPipeParameters::TaskPipeParameters(), PartDesignGui::TaskPipeScaling::TaskPipeScaling(), TechDrawGui::TaskProjGroup::TaskProjGroup(), FemGui::TaskTetParameter::TaskTetParameter(), PartDesignGui::TaskThicknessParameters::TaskThicknessParameters(), RobotGui::TaskTrajectoryDressUpParameter::TaskTrajectoryDressUpParameter(), PartGui::ThicknessWidget::ThicknessWidget(), PartDesign::SubShapeBinder::update(), Part::AttachExtension::updateAttacherVals(), PartDesignGui::ViewProviderDatumLine::updateData(), PartDesignGui::ViewProviderDatumPlane::updateData(), FemGui::TaskPostBox::updateEnumerationList(), PartDesign::Chamfer::updateProperties(), TechDrawGui::TaskProjGroup::updateTask(), and PathGui::ViewProviderPath::useNewSelectionModel().
getValueAsString()
const char * PropertyEnumeration::getValueAsString (void) const
get the value as string
Referenced by FemGui::TaskDlgFemConstraintFluidBoundary::accept(), TechDraw::DrawProjGroup::arrangeViewPointers(), TechDraw::DrawProjGroupItem::autoPosition(), PartDesignGui::TaskHoleParameters::changedObject(), TechDrawGui::QGIViewDimension::draw(), TechDrawGui::QGIViewBalloon::drawBalloon(), TechDraw::DrawProjGroup::dumpISO(), Fem::FemPostScalarClipFilter::execute(), Fem::FemPostWarpVectorFilter::execute(), PartDesign::Hole::execute(), PartDesign::Boolean::execute(), PartDesign::Helix::generateHelixPath(), TechDraw::DrawPage::getPageOrientation(), getPathValue(), getPyObject(), getPyPathValue(), FemGui::TaskFemConstraintFluidBoundary::getTurbulenceModel(), TechDraw::DrawProjGroup::getViewIndex(), TechDraw::DrawViewSection::getXDirection(), TechDrawGui::QGIProjGroup::itemChange(), Fem::ConstraintFluidBoundary::onChanged(), Fem::ConstraintTransform::onChanged(), Fem::FemPostScalarClipFilter::onChanged(), Fem::FemPostWarpVectorFilter::onChanged(), PartDesign::Hole::onChanged(), PartDesignGui::ViewProviderBody::onChanged(), TechDrawGui::ViewProviderProjGroupItem::onDelete(), TechDraw::DrawProjGroup::purgeProjections(), TechDrawGui::TaskProjGroup::saveGroupState(), TechDrawGui::TaskSectionView::saveSectionState(), Gui::ViewProviderDocumentObject::setActiveMode(), Fem::FemPostScalarClipFilter::setConstraintForField(), setEnums(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintHeatflux::TaskFemConstraintHeatflux(), FemGui::TaskFemConstraintTemperature::TaskFemConstraintTemperature(), FemGui::TaskFemConstraintTransform::TaskFemConstraintTransform(), PartDesignGui::TaskHoleParameters::TaskHoleParameters(), TechDrawGui::TaskSectionView::TaskSectionView(), TechDraw::DrawProjGroupItem::unsetupObject(), FemGui::ViewProviderFemConstraintFluidBoundary::updateData(), FemGui::ViewProviderFemConstraintTransform::updateData(), TechDrawGui::ViewProviderProjGroupItem::updateData(), TechDraw::DrawProjGroup::usedProjectionType(), and Gui::PropertyEditor::PropertyEnumItem::value().
hasEnums()
bool PropertyEnumeration::hasEnums () const
get the pointer to the enum list
isPartOf()
bool PropertyEnumeration::isPartOf (const char * value) const
checks if a string is included in the enumeration
isSame()
virtual bool App::PropertyEnumeration::isSame (const Property & other) const virtual
Compare if this property has the same content as the given one.
Reimplemented from App::Property.
References Base::Persistence::getTypeId().
isValid()
bool PropertyEnumeration::isValid (void) const
Returns true if the instance is in a usable state.
Referenced by PartDesign::Hole::onChanged(), Gui::ViewProviderDocumentObject::setActiveMode(), and Gui::PropertyEditor::PropertyEnumItem::value().
isValue()
bool PropertyEnumeration::isValue (const char * value) const
checks if the property is set to a certain string value
Referenced by TechDraw::DrawProjGroup::arrangeViewPointers(), TechDraw::DrawView::checkScale(), TechDraw::DrawProjGroup::execute(), TechDraw::DrawViewDetail::execute(), TechDraw::DrawViewDimension::execute(), TechDraw::DrawViewPart::execute(), TechDraw::DrawViewSection::execute(), TechDraw::DrawViewDimension::formatValue(), TechDraw::DrawViewDimension::getDimValue(), TechDraw::DrawViewDimension::getPrefix(), TechDraw::DrawView::getScale(), TechDraw::DrawProjGroup::getViewIndex(), TechDraw::DrawViewDimension::isMultiValueSchema(), TechDraw::DrawProjGroup::onChanged(), TechDraw::DrawView::onChanged(), TechDraw::DrawViewDetail::onChanged(), TechDraw::DrawViewDimension::onChanged(), TechDraw::DrawViewSection::onChanged(), TechDraw::DrawView::prefScale(), TechDrawGui::TaskProjGroup::scaleManuallyChanged(), TechDraw::DrawView::setScaleAttribute(), TechDrawGui::TaskDimension::TaskDimension(), TechDrawGui::TaskProjGroup::TaskProjGroup(), TechDraw::DrawView::validateScale(), and TechDrawGui::TaskProjGroup::viewToggled().
Paste()
void PropertyEnumeration::Paste (const Property & from) virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References setValue().
Restore()
void PropertyEnumeration::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References App::Property::aboutToSetValue(), Base::Console(), Base::XMLReader::getAttribute(), Base::XMLReader::getAttributeAsInteger(), getValue(), Base::XMLReader::hasAttribute(), App::Property::hasSetValue(), Base::XMLReader::readElement(), Base::XMLReader::readEndElement(), and Base::ConsoleSingleton::Warning().
Referenced by TechDraw::DrawViewBalloon::handleChangedPropertyName().
Save()
void PropertyEnumeration::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References Base::Writer::decInd(), Base::Persistence::encodeAttribute(), getEnumVector(), Base::Writer::incInd(), Base::Writer::ind(), and Base::Writer::Stream().
setEditorName()
void App::PropertyEnumeration::setEditorName (const char * name)
setEnums() [1/2]
void PropertyEnumeration::setEnums (const char ** plEnums)
Enumeration methods.
These all function as per documentation in Enumeration setting the enumaration string list The list is a NULL terminated array of pointers to a const char* string
const char enums[] = {"Black","White","Other",NULL}
References App::Property::aboutToSetValue(), App::Property::getFullName(), App::Property::hasSetValue(), and femsolver.signal::notify().
Referenced by Gui::ViewProviderDocumentObject::attach(), PartDesign::Boolean::Boolean(), PartDesign::Chamfer::Chamfer(), Fem::ConstraintFluidBoundary::ConstraintFluidBoundary(), Fem::ConstraintHeatflux::ConstraintHeatflux(), Fem::ConstraintTemperature::ConstraintTemperature(), Fem::ConstraintTransform::ConstraintTransform(), TechDraw::DrawPage::DrawPage(), TechDraw::DrawTemplate::DrawTemplate(), TechDraw::DrawViewAnnotation::DrawViewAnnotation(), TechDraw::DrawViewArch::DrawViewArch(), TechDraw::DrawViewBalloon::DrawViewBalloon(), TechDraw::DrawViewDimension::DrawViewDimension(), Part::Extrusion::Extrusion(), App::FeatureTest::FeatureTest(), Fem::FemMeshShapeNetgenObject::FemMeshShapeNetgenObject(), Fem::FemPostPipeline::FemPostPipeline(), Surface::GeomFillSurface::GeomFillSurface(), Part::Helix::Helix(), PartDesign::Helix::Helix(), PartDesign::Hole::Hole(), Fem::ConstraintFluidBoundary::onChanged(), PartDesign::Hole::onChanged(), Part::RuledSurface::RuledSurface(), App::LinkBaseExtension::setProperty(), Robot::TrajectoryDressUpObject::TrajectoryDressUpObject(), PartDesignGui::ViewProviderBoolean::ViewProviderBoolean(), TechDrawGui::ViewProviderLeader::ViewProviderLeader(), Gui::ViewProviderLink::ViewProviderLink(), PartGui::ViewProviderPartExt::ViewProviderPartExt(), TechDrawGui::ViewProviderRichAnno::ViewProviderRichAnno(), TechDrawGui::ViewProviderViewPart::ViewProviderViewPart(), and Gui::ViewProviderDocumentObject::~ViewProviderDocumentObject().
setEnums() [2/2]
void PropertyEnumeration::setEnums (const std::vector< std::string > & Enums)
setting the enumaration string as vector of strings This makes the enumeration custom.
References getValueAsString(), setEnumVector(), and setValue().
setEnumVector()
void PropertyEnumeration::setEnumVector (const std::vector< std::string > & values)
set enum values as vector of strings
References App::Property::aboutToSetValue(), App::Property::getFullName(), App::Property::hasSetValue(), and femsolver.signal::notify().
Referenced by setEnums().
setPathValue()
void PropertyEnumeration::setPathValue (const App::ObjectIdentifier & path, const boost::any & value) virtual
Set value of property.
Reimplemented from App::Property.
References App::pyObjectFromAny(), setPyObject(), and setValue().
setPyObject()
void PropertyEnumeration::setPyObject (PyObject * value) virtual
Reimplemented from Base::BaseClass.
References App::Property::aboutToSetValue(), App::Property::getFullName(), and App::Property::hasSetValue().
Referenced by setPathValue(), and setPyPathValue().
setPyPathValue()
bool PropertyEnumeration::setPyPathValue (const App::ObjectIdentifier & path, const Py::Object & value) virtual
References setPyObject().
setValue() [1/3]
void PropertyEnumeration::setValue (const char * value)
set the enum by a string is slower than setValue(long).
Use long if possible
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Referenced by Gui::ViewProviderDocumentObject::attach(), SurfaceGui::GeomFillSurface::changeFillType(), PartDesign::SubShapeBinder::checkCopyOnChange(), TechDrawGui::TaskLeaderLine::commonFeatureUpdate(), TechDraw::DrawViewArch::DrawViewArch(), Gui::ElementColors::ElementColors(), Fem::FemPostScalarClipFilter::execute(), Fem::FemPostWarpVectorFilter::execute(), TechDrawGui::ViewProviderLeader::handleChangedPropertyType(), TechDrawGui::ViewProviderRichAnno::handleChangedPropertyType(), Part::Part2DObject::handleChangedPropertyType(), PartDesignGui::TaskFeaturePick::makeCopy(), Fem::ConstraintFluidBoundary::onChanged(), TechDraw::DrawViewDimension::onChanged(), TechDrawGui::TaskDetail::onScaleTypeEdit(), Paste(), TechDraw::DrawSVGTemplate::processTemplate(), TechDrawGui::TaskProjGroup::projectionTypeChanged(), PartDesign::Plane::Restore(), TechDrawGui::TaskProjGroup::restoreGroupState(), TechDrawGui::TaskSectionView::restoreSectionState(), TechDrawGui::TaskProjGroup::scaleTypeChanged(), setEnums(), setPathValue(), TechDrawGui::TaskRichAnno::updateAnnoFeature(), TechDrawGui::TaskLeaderLine::updateLeaderFeature(), TechDraw::DrawView::validateScale(), PartDesignGui::ViewProviderDatumCoordinateSystem::ViewProviderDatumCoordinateSystem(), PointsGui::ViewProviderPoints::ViewProviderPoints(), RobotGui::TaskTrajectoryDressUpParameter::writeValues(), and Gui::ElementColors::Private::~Private().
setValue() [2/3]
void PropertyEnumeration::setValue (const Enumeration & source)
Setter using Enumeration.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
setValue() [3/3]
void PropertyEnumeration::setValue (long value)
set directly the enum value In DEBUG checks for boundaries.
Is faster than using setValue(const char*).
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
The documentation for this class was generated from the following files:
FreeCAD/src/App/PropertyStandard.h
FreeCAD/src/App/PropertyStandard.cpp