FreeCAD: TechDrawGui::TaskAlignViews Class Reference
TechDrawGui::TaskAlignViews Class Reference
#include <TaskAlignViews.h>
Public Member Functions
TaskAlignViews ()
~TaskAlignViews ()
Protected Slots
void onHorizontallyClicked ()
void onVerticallyClicked ()
Protected Member Functions
void changeEvent (QEvent *e)
void getSelectedEdges ()
void initUi (void)
Constructor & Destructor Documentation
TaskAlignViews()
TaskAlignViews::TaskAlignViews ()
References draftgeoutils.intersections::connect(), Base::Console(), initUi(), Base::ConsoleSingleton::Message(), onHorizontallyClicked(), and onVerticallyClicked().
~TaskAlignViews()
TaskAlignViews::~TaskAlignViews ()
Member Function Documentation
changeEvent()
void TaskAlignViews::changeEvent (QEvent * e) protected
getSelectedEdges()
void TaskAlignViews::getSelectedEdges () protected
References Base::Console(), draftgeoutils.general::geomType(), Base::Persistence::getClassTypeId(), TechDraw::CosmeticExtension::getCosmeticEdgeBySelection(), Gui::SelectionSingleton::getSelectionEx(), TechDraw::CosmeticEdge::m_format, TechDraw::LineFormat::m_weight, Base::ConsoleSingleton::Message(), and Gui::Selection().
Referenced by onHorizontallyClicked().
initUi()
void TaskAlignViews::initUi (void) protected
Referenced by TaskAlignViews().
onHorizontallyClicked
void TaskAlignViews::onHorizontallyClicked () protected slot
References Base::Console(), getSelectedEdges(), and Base::ConsoleSingleton::Message().
Referenced by TaskAlignViews().
onVerticallyClicked
void TaskAlignViews::onVerticallyClicked () protected slot
Referenced by TaskAlignViews().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/TaskAlignViews.h
FreeCAD/src/Mod/TechDraw/Gui/TaskAlignViews.cpp