FreeCAD: PathScripts.PathFeatureExtensions Namespace Reference
PathScripts.PathFeatureExtensions Namespace Reference
Classes
class Extension
Functions
def arcAdjustmentAngle (arc1, arc2)
def createExtension (obj, extObj, extFeature, extSub)
def endPoints (edgeOrWire)
def extendWire (feature, wire, length)
def getExtendOutlineFace (base_shape, face, extension, remHoles=False, offset_tolerance=1e-4)
def getExtensions (obj)
def getStandardAngle (x, y)
def getWaterlineFace (base_shape, face)
def includesPoint (p, pts)
def initialize_properties (obj)
def readObjExtensionFeature (obj)
def selectOffsetWire (feature, wires)
def set_default_property_values (obj, job)
def setExtensions (obj, extensions)
def SetupProperties ()
Variables
PathUtils = LazyLoader("PathScripts.PathUtils", globals(), "PathScripts.PathUtils")
translate = FreeCAD.Qt.translate
Function Documentation
arcAdjustmentAngle()
def PathScripts.PathFeatureExtensions.arcAdjustmentAngle (arc1, arc2)
arcAdjustmentAngle(arc1, arc2)...
Return adjustment angle to apply to arc2 in order to align it with arc1.
Arcs must have same center point.
References PathScripts.PathFeatureExtensions.getStandardAngle().
Referenced by PathScripts.PathFeatureExtensions.Extension.getWire().
createExtension()
def PathScripts.PathFeatureExtensions.createExtension (obj, extObj, extFeature, extSub)
Referenced by PathScripts.PathFeatureExtensions.getExtensions().
endPoints()
def PathScripts.PathFeatureExtensions.endPoints (edgeOrWire)
endPoints(edgeOrWire) ... return the first and last point of the wire or the edge, assuming the argument is not a closed wire.
Referenced by PathScripts.PathFeatureExtensions.extendWire(), and PathScripts.PathFeatureExtensions.Extension.getWire().
extendWire()
def PathScripts.PathFeatureExtensions.extendWire (feature, wire, length)
extendWire(wire, length) ... return a closed Wire which extends wire by length
References PathScripts.PathFeatureExtensions.endPoints(), PathScripts.PathFeatureExtensions.includesPoint(), and PathScripts.PathFeatureExtensions.selectOffsetWire().
Referenced by PathScripts.PathFeatureExtensions.Extension.getSubLink(), and PathScripts.PathFeatureExtensions.Extension.getWire().
getExtendOutlineFace()
def PathScripts.PathFeatureExtensions.getExtendOutlineFace (base_shape, face, extension, remHoles = False, offset_tolerance = 1e-4)
getExtendOutlineFace(obj, base_shape, face, extension, remHoles) ...
Creates an extended face for the pocket, taking into consideration lateral
collision with the greater base shape.
Arguments are:
    parent base shape of face,
    target face,
    extension magnitude,
    remove holes boolean,
    offset tolerance = 1e-4 default
The default value of 1e-4 for offset tolerance is the same default value
at getOffsetArea() function definition.
Return is an all access face extending the specified extension value from the source face.
getExtensions()
def PathScripts.PathFeatureExtensions.getExtensions (obj)
References PathScripts.PathFeatureExtensions.createExtension().
getStandardAngle()
def PathScripts.PathFeatureExtensions.getStandardAngle (x, y)
getStandardAngle(x, y)...
Return standard degree angle given x and y values of vector.
Referenced by PathScripts.PathFeatureExtensions.arcAdjustmentAngle().
getWaterlineFace()
def PathScripts.PathFeatureExtensions.getWaterlineFace (base_shape, face)
getWaterlineFace(base_shape, face) ...
Creates a waterline extension face for the target face,
taking into consideration the greater base shape.
Arguments are: parent base shape and target face.
Return is a waterline face at height of the target face.
includesPoint()
def PathScripts.PathFeatureExtensions.includesPoint (p, pts)
includesPoint(p, pts) ... answer True if the collection of pts includes the point p
Referenced by PathScripts.PathFeatureExtensions.extendWire().
initialize_properties()
def PathScripts.PathFeatureExtensions.initialize_properties (obj)
initialize_properties(obj)... Adds feature properties to object argument
References draftutils.translate.QT_TRANSLATE_NOOP.
readObjExtensionFeature()
def PathScripts.PathFeatureExtensions.readObjExtensionFeature (obj)
readObjExtensionFeature(obj)...
Return three item string tuples (base name, feature, subfeature) extracted from obj.ExtensionFeature
selectOffsetWire()
def PathScripts.PathFeatureExtensions.selectOffsetWire (feature, wires)
selectOffsetWire(feature, wires) ... returns the Wire in wires which is does not intersect with feature
Referenced by PathScripts.PathFeatureExtensions.extendWire().
set_default_property_values()
def PathScripts.PathFeatureExtensions.set_default_property_values (obj, job)
set_default_property_values(obj, job) ... set default values for feature properties
setExtensions()
def PathScripts.PathFeatureExtensions.setExtensions (obj, extensions)
SetupProperties()
def PathScripts.PathFeatureExtensions.SetupProperties ()
SetupProperties()... Returns list of feature property names
Variable Documentation
PathUtils
PathScripts.PathFeatureExtensions.PathUtils = LazyLoader("PathScripts.PathUtils", globals(), "PathScripts.PathUtils")
translate
PathScripts.PathFeatureExtensions.translate = FreeCAD.Qt.translate