FreeCAD: StdMeshers::Function Class Reference
StdMeshers::Function Class Reference abstract
#include <StdMeshers_Distribution.hxx>
Public Member Functions
Function (const int)
virtual double integral (const double, const double) const =0
virtual bool value (const double, double &) const
virtual ~Function ()
Constructor & Destructor Documentation
Function()
StdMeshers::Function::Function (const int conv)
~Function()
StdMeshers::Function::~Function () virtual
Member Function Documentation
integral()
virtual double StdMeshers::Function::integral (const double , const double) const pure virtual
Implemented in StdMeshers::FunctionExpr, StdMeshers::FunctionTable, and StdMeshers::FunctionIntegral.
Referenced by StdMeshers::FunctionIntegral::value().
value()
bool StdMeshers::Function::value (const double , double & f) const virtual
Reimplemented in StdMeshers::FunctionExpr, StdMeshers::FunctionTable, and StdMeshers::FunctionIntegral.
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), StdMeshers::FunctionIntegral::value(), StdMeshers::FunctionTable::value(), and StdMeshers::FunctionExpr::value().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_Distribution.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_Distribution.cpp