FreeCAD: Surface::ShapeValidator Class Reference
Surface::ShapeValidator Class Reference
#include <FeatureGeomFillSurface.h>
Public Member Functions
void checkAndAdd (const Part::TopoShape &ts, const char *subName, Handle(ShapeExtend_WireData) *aWire=NULL)
void checkAndAdd (const TopoDS_Shape &shape, Handle(ShapeExtend_WireData) *aWD=NULL)
void checkEdge (const TopoDS_Shape &shape)
void initValidator (void)
bool isBezier () const
int numEdges () const
ShapeValidator ()
Protected Attributes
int edgeCount
bool willBezier
Constructor & Destructor Documentation
ShapeValidator()
ShapeValidator::ShapeValidator ()
References initValidator().
Member Function Documentation
checkAndAdd() [1/2]
void ShapeValidator::checkAndAdd (const Part::TopoShape & ts, const char * subName, Handle(ShapeExtend_WireData) * aWire = NULL)
References checkAndAdd().
checkAndAdd() [2/2]
void ShapeValidator::checkAndAdd (const TopoDS_Shape & shape, Handle(ShapeExtend_WireData) * aWD = NULL)
References checkEdge().
Referenced by checkAndAdd(), and Surface::GeomFillSurface::getWire().
checkEdge()
void ShapeValidator::checkEdge (const TopoDS_Shape & shape)
References edgeCount, and willBezier.
Referenced by checkAndAdd().
initValidator()
void ShapeValidator::initValidator (void)
References edgeCount, and willBezier.
Referenced by ShapeValidator().
isBezier()
bool Surface::ShapeValidator::isBezier () const
Referenced by Surface::GeomFillSurface::getWire().
numEdges()
int Surface::ShapeValidator::numEdges () const
Referenced by Surface::GeomFillSurface::getWire().
Member Data Documentation
edgeCount
int Surface::ShapeValidator::edgeCount protected
Referenced by checkEdge(), and initValidator().
willBezier
bool Surface::ShapeValidator::willBezier protected
Referenced by checkEdge(), and initValidator().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Surface/App/FeatureGeomFillSurface.h
Sources/FreeCAD/src/Mod/Surface/App/FeatureGeomFillSurface.cpp