FreeCAD: PartDesignGui::Ui_TaskFeaturePick Class Reference
PartDesignGui::Ui_TaskFeaturePick Class Reference
#include <ui_TaskFeaturePick.h>
Public Member Functions
void retranslateUi (QWidget *PartDesignGui__TaskFeaturePick)
void setupUi (QWidget *PartDesignGui__TaskFeaturePick)
Public Attributes
QGroupBox * checkExternal
QCheckBox * checkOtherBody
QCheckBox * checkOtherPart
QCheckBox * checkUsed
QFrame * line
QListWidget * listWidget
QRadioButton * radioDependent
QRadioButton * radioIndependent
QRadioButton * radioXRef
QVBoxLayout * verticalLayout_2
QVBoxLayout * verticalLayout_4
Member Function Documentation
retranslateUi()
void PartDesignGui::Ui_TaskFeaturePick::retranslateUi (QWidget * PartDesignGui__TaskFeaturePick)
References checkExternal, checkOtherBody, checkOtherPart, checkUsed, radioDependent, radioIndependent, radioXRef, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void PartDesignGui::Ui_TaskFeaturePick::setupUi (QWidget * PartDesignGui__TaskFeaturePick)
References checkExternal, checkOtherBody, checkOtherPart, checkUsed, line, listWidget, radioDependent, radioIndependent, radioXRef, retranslateUi(), verticalLayout_2, and verticalLayout_4.
Member Data Documentation
checkExternal
QGroupBox* PartDesignGui::Ui_TaskFeaturePick::checkExternal
Referenced by retranslateUi(), and setupUi().
checkOtherBody
QCheckBox* PartDesignGui::Ui_TaskFeaturePick::checkOtherBody
Referenced by retranslateUi(), and setupUi().
checkOtherPart
QCheckBox* PartDesignGui::Ui_TaskFeaturePick::checkOtherPart
Referenced by retranslateUi(), and setupUi().
checkUsed
QCheckBox* PartDesignGui::Ui_TaskFeaturePick::checkUsed
Referenced by retranslateUi(), and setupUi().
line
QFrame* PartDesignGui::Ui_TaskFeaturePick::line
Referenced by Plot.Line::getp(), Plot.Line::setp(), setupUi(), draftguitools.gui_trackers.wireTracker::update(), and draftviewproviders.view_label.ViewProviderLabel::updateData().
listWidget
QListWidget* PartDesignGui::Ui_TaskFeaturePick::listWidget
Referenced by setupUi().
radioDependent
QRadioButton* PartDesignGui::Ui_TaskFeaturePick::radioDependent
Referenced by retranslateUi(), and setupUi().
radioIndependent
QRadioButton* PartDesignGui::Ui_TaskFeaturePick::radioIndependent
Referenced by retranslateUi(), and setupUi().
radioXRef
QRadioButton* PartDesignGui::Ui_TaskFeaturePick::radioXRef
Referenced by retranslateUi(), and setupUi().
verticalLayout_2
QVBoxLayout* PartDesignGui::Ui_TaskFeaturePick::verticalLayout_2
Referenced by setupUi().
verticalLayout_4
QVBoxLayout* PartDesignGui::Ui_TaskFeaturePick::verticalLayout_4
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/PartDesign/Gui/ui_TaskFeaturePick.h