FreeCAD: VISCOUS_3D::_Simplex Struct Reference
VISCOUS_3D::_Simplex Struct Reference
Simplex (triangle or tetrahedron) based on 1 (tria) or 2 (tet) nodes of _LayerEdge and 2 nodes of the mesh surface beening smoothed. The class is used to check validity of face or volumes around a smoothed node; it stores only 2 nodes as the other nodes are stored by _LayerEdge.
Public Member Functions
bool IsForward (const gp_XY &tgtUV, const SMDS_MeshNode *smoothedNode, const TopoDS_Face &face, SMESH_MesherHelper &helper, const double refSign) const
bool IsForward (const SMDS_MeshNode *nSrc, const gp_XYZ *pntTgt, double &vol) const
bool IsNeighbour (const _Simplex &other) const
Static Public Member Functions
static void GetSimplices (const SMDS_MeshNode *node, vector< _Simplex > &simplices, const set< TGeomID > &ingnoreShapes, const _SolidData *dataToCheckOri=0, const bool toSort=false)
Fills a vector<_Simplex >
static void SortSimplices (vector< _Simplex > &simplices)
Set neighbor simplices side by side.
Detailed Description
Simplex (triangle or tetrahedron) based on 1 (tria) or 2 (tet) nodes of _LayerEdge and 2 nodes of the mesh surface beening smoothed. The class is used to check validity of face or volumes around a smoothed node; it stores only 2 nodes as the other nodes are stored by _LayerEdge.
Member Function Documentation
GetSimplices()
void _Simplex::GetSimplices (const SMDS_MeshNode * node, vector< _Simplex > & simplices, const set< TGeomID > & ingnoreShapes, const _SolidData * dataToCheckOri = 0, const bool toSort = false) static
Fills a vector<_Simplex >
References SMDS_MeshNode::GetInverseElementIterator(), SMDS_MeshElement::GetNode(), SortSimplices(), and SMESH_MesherHelper::WrapIndex().
Referenced by VISCOUS_3D::_SolidData::PrepareEdgesToSmoothOnFace().
IsForward() [1/2]
bool VISCOUS_3D::_Simplex::IsForward (const gp_XY & tgtUV, const SMDS_MeshNode * smoothedNode, const TopoDS_Face & face, SMESH_MesherHelper & helper, const double refSign) const
References SMESH_MesherHelper::GetNodeUV(), and draftgeoutils.general::v1().
IsForward() [2/2]
bool VISCOUS_3D::_Simplex::IsForward (const SMDS_MeshNode * nSrc, const gp_XYZ * pntTgt, double & vol) const
References SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
IsNeighbour()
bool VISCOUS_3D::_Simplex::IsNeighbour (const _Simplex & other) const
SortSimplices()
void _Simplex::SortSimplices (vector< _Simplex > & simplices) static
Set neighbor simplices side by side.
Referenced by GetSimplices().
The documentation for this struct was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_ViscousLayers.cpp