FreeCAD: Path::VoronoiVertexPy Class Reference
Path::VoronoiVertexPy Class Reference
The python export class for VoronoiVertex.
#include <VoronoiVertexPy.h>
Public Types
typedef VoronoiVertex * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
VoronoiVertexPy (VoronoiVertex *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * richCompare (PyObject *v, PyObject *w, int op)
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of VoronoiVertexPy.
static PyMethodDef Methods []
Methods structure of VoronoiVertexPy.
static PyTypeObject Type
Type structure of VoronoiVertexPy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~VoronoiVertexPy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
static PyObject * staticCallback_toPoint (PyObject *self, PyObject *args)
callback for the toPoint() method
PyObject * toPoint (PyObject *args)
implementer for the toPoint() method
callbacks and implementers for the python object attributes
static PyObject * staticCallback_getIndex (PyObject *self, void *closure)
getter callback for the Index attribute
static int staticCallback_setIndex (PyObject *self, PyObject *value, void *closure)
setter callback for the Index attribute
static PyObject * staticCallback_getColor (PyObject *self, void *closure)
getter callback for the Color attribute
static int staticCallback_setColor (PyObject *self, PyObject *value, void *closure)
setter callback for the Color attribute
static PyObject * staticCallback_getX (PyObject *self, void *closure)
getter callback for the X attribute
static int staticCallback_setX (PyObject *self, PyObject *value, void *closure)
setter callback for the X attribute
static PyObject * staticCallback_getY (PyObject *self, void *closure)
getter callback for the Y attribute
static int staticCallback_setY (PyObject *self, PyObject *value, void *closure)
setter callback for the Y attribute
static PyObject * staticCallback_getIncidentEdge (PyObject *self, void *closure)
getter callback for the IncidentEdge attribute
static int staticCallback_setIncidentEdge (PyObject *self, PyObject *value, void *closure)
setter callback for the IncidentEdge attribute
Py::Long getIndex (void) const
getter for the Index attribute
Py::Long getColor (void) const
getter for the Color attribute
void setColor (Py::Long arg)
setter for the Color attribute
Py::Float getX (void) const
getter for the X attribute
Py::Float getY (void) const
getter for the Y attribute
Py::Object getIncidentEdge (void) const
getter for the IncidentEdge attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
VoronoiVertex * getVoronoiVertexPtr (void) const
getter for the object handled by this class
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for VoronoiVertex.
Member Typedef Documentation
PointerType
typedef VoronoiVertex* Path::VoronoiVertexPy::PointerType
Constructor & Destructor Documentation
~VoronoiVertexPy()
VoronoiVertexPy::~VoronoiVertexPy () protected
VoronoiVertexPy()
VoronoiVertexPy::VoronoiVertexPy (VoronoiVertex * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getColor()
Py::Long VoronoiVertexPy::getColor (void) const
getter for the Color attribute
References Path::Voronoi::ColorMask, and getVoronoiVertexPtr().
Referenced by staticCallback_getColor().
getCustomAttributes()
PyObject * VoronoiVertexPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getIncidentEdge()
Py::Object VoronoiVertexPy::getIncidentEdge (void) const
getter for the IncidentEdge attribute
Referenced by staticCallback_getIncidentEdge().
getIndex()
Py::Long VoronoiVertexPy::getIndex (void) const
getter for the Index attribute
References getVoronoiVertexPtr().
Referenced by staticCallback_getIndex().
GetType()
virtual PyTypeObject* Path::VoronoiVertexPy::GetType (void) virtual
Reimplemented from Base::BaseClassPy.
getVoronoiVertexPtr()
VoronoiVertex * VoronoiVertexPy::getVoronoiVertexPtr (void) const
getter for the object handled by this class
Referenced by getColor(), getIndex(), representation(), richCompare(), and toPoint().
getX()
Py::Float VoronoiVertexPy::getX (void) const
getter for the X attribute
Referenced by staticCallback_getX().
getY()
Py::Float VoronoiVertexPy::getY (void) const
getter for the Y attribute
Referenced by staticCallback_getY().
PyInit()
int VoronoiVertexPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::BaseClassPy.
PyMake()
PyObject * VoronoiVertexPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References VoronoiVertexPy().
representation()
std::string VoronoiVertexPy::representation (void) const
References getVoronoiVertexPtr().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
richCompare()
PyObject * VoronoiVertexPy::richCompare (PyObject * v, PyObject * w, int op) static
References Path::VoronoiVertex::dia, getVoronoiVertexPtr(), Path::VoronoiVertex::index, and Type.
setColor()
void VoronoiVertexPy::setColor (Py::Long arg)
setter for the Color attribute
References Path::Voronoi::ColorMask.
Referenced by staticCallback_setColor().
setCustomAttributes()
int VoronoiVertexPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_getColor()
PyObject * VoronoiVertexPy::staticCallback_getColor (PyObject * self, void * closure) static
getter callback for the Color attribute
References Base::BaseExceptionFreeCADError, getColor(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getIncidentEdge()
PyObject * VoronoiVertexPy::staticCallback_getIncidentEdge (PyObject * self, void * closure) static
getter callback for the IncidentEdge attribute
References Base::BaseExceptionFreeCADError, getIncidentEdge(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getIndex()
PyObject * VoronoiVertexPy::staticCallback_getIndex (PyObject * self, void * closure) static
getter callback for the Index attribute
References Base::BaseExceptionFreeCADError, getIndex(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getX()
PyObject * VoronoiVertexPy::staticCallback_getX (PyObject * self, void * closure) static
getter callback for the X attribute
References Base::BaseExceptionFreeCADError, getX(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getY()
PyObject * VoronoiVertexPy::staticCallback_getY (PyObject * self, void * closure) static
getter callback for the Y attribute
References Base::BaseExceptionFreeCADError, getY(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setColor()
int VoronoiVertexPy::staticCallback_setColor (PyObject * self, PyObject * value, void * closure) static
setter callback for the Color attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setColor().
staticCallback_setIncidentEdge()
int VoronoiVertexPy::staticCallback_setIncidentEdge (PyObject * self, PyObject * value, void * closure) static
setter callback for the IncidentEdge attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setIndex()
int VoronoiVertexPy::staticCallback_setIndex (PyObject * self, PyObject * value, void * closure) static
setter callback for the Index attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setX()
int VoronoiVertexPy::staticCallback_setX (PyObject * self, PyObject * value, void * closure) static
setter callback for the X attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setY()
int VoronoiVertexPy::staticCallback_setY (PyObject * self, PyObject * value, void * closure) static
setter callback for the Y attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_toPoint()
PyObject * VoronoiVertexPy::staticCallback_toPoint (PyObject * self, PyObject * args) static
callback for the toPoint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and toPoint().
toPoint()
PyObject * VoronoiVertexPy::toPoint (PyObject * args)
implementer for the toPoint() method
References getVoronoiVertexPtr().
Referenced by staticCallback_toPoint().
Member Data Documentation
GetterSetter
PyGetSetDef VoronoiVertexPy::GetterSetter static
Attribute structure of VoronoiVertexPy.
Methods
PyMethodDef VoronoiVertexPy::Methods static
Initial value:
= {
    {"toPoint",
        reinterpret_cast<PyCFunction>( staticCallback_toPoint ),
        METH_VARARGS,
        "Returns a Vector - or None if not possible"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of VoronoiVertexPy.
Type
PyTypeObject VoronoiVertexPy::Type static
Type structure of VoronoiVertexPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), and richCompare().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/VoronoiVertexPy.h
Sources/FreeCAD/src/Mod/Path/App/VoronoiVertexPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/VoronoiVertexPy.cpp