FreeCAD: Gui::ToolTip Class Reference
Gui::ToolTip Class Reference
Qt's tooltip does not work as expected with some classes, e.g.
#include <Widgets.h>
Static Public Member Functions
static void showText (const QPoint &pos, const QString &text, QWidget *w=0)
Protected Member Functions
bool eventFilter (QObject *o, QEvent *e)
void installEventFilter ()
void removeEventFilter ()
void timerEvent (QTimerEvent *e)
ToolTip ()
virtual ~ToolTip ()
Static Protected Member Functions
static ToolTip * instance ()
Detailed Description
Qt's tooltip does not work as expected with some classes, e.g.
when showing it in the 3d view it immediately receives a timer event to destroy itself. This class is thought to circumvent this behaviour by filtering the internal timer events.
Author
Werner Mayer
Constructor & Destructor Documentation
ToolTip()
ToolTip::ToolTip () protected
Referenced by instance().
~ToolTip()
ToolTip::~ToolTip () protected virtual
Member Function Documentation
eventFilter()
bool ToolTip::eventFilter (QObject * o, QEvent * e) protected
References removeEventFilter().
installEventFilter()
void ToolTip::installEventFilter () protected
Referenced by showText().
instance()
ToolTip * ToolTip::instance (void) static protected
References ToolTip().
Referenced by showText().
removeEventFilter()
void ToolTip::removeEventFilter () protected
Referenced by eventFilter().
showText()
void ToolTip::showText (const QPoint & pos, const QString & text, QWidget * w = 0) static
References installEventFilter(), and instance().
Referenced by MeshGui::ViewProviderMeshCurvature::curvatureInfoCallback(), InspectionGui::ViewProviderInspection::inspectCallback(), and Gui::ActionGroup::onHovered().
timerEvent()
void ToolTip::timerEvent (QTimerEvent * e) protected
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Widgets.h
Sources/FreeCAD/src/Gui/Widgets.cpp