FreeCAD: SMESH::Controls::LyingOnGeom Class Reference
SMESH::Controls::LyingOnGeom Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
virtual bool Contains (const SMESHDS_Mesh *theMeshDS, const TopoDS_Shape &theShape, const SMDS_MeshElement *theElem, TopAbs_ShapeEnum theFindShapeEnum, TopAbs_ShapeEnum theAvoidShapeEnum=TopAbs_SHAPE)
const SMESHDS_Mesh * GetMeshDS () const
TopoDS_Shape GetShape ()
double GetTolerance ()
virtual SMDSAbs_ElementType GetType () const
virtual bool IsSatisfy (long theElementId)
LyingOnGeom ()
virtual void SetGeom (const TopoDS_Shape &theShape)
virtual void SetMesh (const SMDS_Mesh *theMesh)
void SetTolerance (double)
virtual void SetType (SMDSAbs_ElementType theType)
Public Member Functions inherited from SMESH::Controls::Functor
~Functor ()
Constructor & Destructor Documentation
LyingOnGeom()
LyingOnGeom::LyingOnGeom ()
Member Function Documentation
Contains()
bool LyingOnGeom::Contains (const SMESHDS_Mesh * theMeshDS, const TopoDS_Shape & theShape, const SMDS_MeshElement * theElem, TopAbs_ShapeEnum theFindShapeEnum, TopAbs_ShapeEnum theAvoidShapeEnum = TopAbs_SHAPE) virtual
GetMeshDS()
const SMESHDS_Mesh * LyingOnGeom::GetMeshDS () const
GetShape()
TopoDS_Shape LyingOnGeom::GetShape ()
GetTolerance()
double LyingOnGeom::GetTolerance ()
GetType()
SMDSAbs_ElementType LyingOnGeom::GetType () const virtual
Implements SMESH::Controls::Predicate.
IsSatisfy()
bool LyingOnGeom::IsSatisfy (long theElementId) virtual
Implements SMESH::Controls::Predicate.
References SMDS_Mesh::FindElement(), SMDS_Mesh::FindNode(), SMDS_MeshElement::getshapeId(), SMDS_MeshElement::GetType(), and SMDS_MeshElement::nodesIterator().
SetGeom()
void LyingOnGeom::SetGeom (const TopoDS_Shape & theShape) virtual
SetMesh()
void LyingOnGeom::SetMesh (const SMDS_Mesh * theMesh) virtual
Implements SMESH::Controls::Functor.
SetTolerance()
void LyingOnGeom::SetTolerance (double theTolerance)
SetType()
void LyingOnGeom::SetType (SMDSAbs_ElementType theType) virtual
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp