FreeCAD: PathScripts.PathToolController Namespace Reference
PathScripts.PathToolController Namespace Reference
Classes
class ToolController
class ToolControllerTemplate
Functions
def Create (name="TC: Default Tool", tool=None, toolNumber=1, assignViewProvider=True, assignTool=True)
def FromTemplate (template, assignViewProvider=True)
Variables
translate = FreeCAD.Qt.translate
Function Documentation
Create()
def PathScripts.PathToolController.Create (name = "TC: Default Tool", tool = None, toolNumber = 1, assignViewProvider = True, assignTool = True)
Referenced by PathScripts.PathToolLibraryEditor.EditorPanel.copyTools(), PathScripts.PathToolControllerGui.Create(), and PathScripts.PathToolController.FromTemplate().
FromTemplate()
def PathScripts.PathToolController.FromTemplate (template, assignViewProvider = True)
References PathScripts.PathToolController.Create().
Variable Documentation
translate
PathScripts.PathToolController.translate = FreeCAD.Qt.translate