FreeCAD: PartGui::DlgProjectionOnSurface Class Reference
PartGui::DlgProjectionOnSurface Class Reference
#include <DlgProjectionOnSurface.h>
Classes
class EdgeSelection
class FaceSelection
Public Member Functions
void apply (void)
DlgProjectionOnSurface (QWidget *parent=nullptr)
void reject (void)
~DlgProjectionOnSurface ()
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Public Member Functions inherited from App::DocumentObserver
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
Additional Inherited Members
Protected Member Functions inherited from App::DocumentObserver
Document * getDocument () const
Constructor & Destructor Documentation
DlgProjectionOnSurface()
DlgProjectionOnSurface::DlgProjectionOnSurface (QWidget * parent = nullptr) explicit
References App::Document::addObject(), App::DocumentObserver::attachDocument(), PartGui::Ui_DlgProjectionOnSurface::doubleSpinBoxSolidDepth, App::Application::getActiveDocument(), App::GetApplication(), App::DocumentObject::Label, App::Document::openTransaction(), PartGui::Ui_DlgProjectionOnSurface::pushButtonAddEdge, PartGui::Ui_DlgProjectionOnSurface::pushButtonAddFace, PartGui::Ui_DlgProjectionOnSurface::pushButtonAddProjFace, PartGui::Ui_DlgProjectionOnSurface::pushButtonAddWire, PartGui::Ui_DlgProjectionOnSurface::pushButtonDirX, PartGui::Ui_DlgProjectionOnSurface::pushButtonDirY, PartGui::Ui_DlgProjectionOnSurface::pushButtonDirZ, PartGui::Ui_DlgProjectionOnSurface::pushButtonGetCurrentCamDir, PartGui::Ui_DlgProjectionOnSurface::radioButtonEdges, PartGui::Ui_DlgProjectionOnSurface::radioButtonFaces, PartGui::Ui_DlgProjectionOnSurface::radioButtonShowAll, PartGui::Ui_DlgProjectionOnSurface::setupUi(), and App::PropertyString::setValue().
~DlgProjectionOnSurface()
DlgProjectionOnSurface::~DlgProjectionOnSurface ()
References Base::Console(), Gui::Application::getViewProvider(), Gui::Application::Instance, Gui::SelectionSingleton::rmvSelectionGate(), Gui::ViewProviderGeometryObject::Selectable, Gui::Selection(), App::PropertyBool::setValue(), App::PropertyInteger::setValue(), Gui::ViewProviderGeometryObject::Transparency, and Base::ConsoleSingleton::Warning().
Member Function Documentation
apply()
void PartGui::DlgProjectionOnSurface::apply (void)
Referenced by PartGui::TaskProjectionOnSurface::accept(), and PartGui::TaskProjectionOnSurface::clicked().
reject()
void PartGui::DlgProjectionOnSurface::reject (void)
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), PartGui::TaskProjectionOnSurface::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/DlgProjectionOnSurface.h
FreeCAD/src/Mod/Part/Gui/DlgProjectionOnSurface.cpp