FreeCAD: SketcherGui::ElementView Class Reference
SketcherGui::ElementView Class Reference
#include <TaskSketcherElements.h>
Signals
void onFilterShortcutPressed ()
Public Member Functions
ElementView (QWidget *parent=nullptr)
~ElementView ()
Protected Slots
void deleteSelectedItems ()
void doAngleConstraint ()
void doBlockConstraint ()
void doDiameterConstraint ()
void doEqualConstraint ()
void doHorizontalConstraint ()
void doHorizontalDistance ()
void doLengthConstraint ()
void doLockConstraint ()
void doParallelConstraint ()
void doPerpendicularConstraint ()
void doPointCoincidence ()
void doPointOnObjectConstraint ()
void doRadiamConstraint ()
void doRadiusConstraint ()
void doSelectConstraints ()
void doSelectHAxis ()
void doSelectOrigin ()
void doSelectVAxis ()
void doSymmetricConstraint ()
void doTangentConstraint ()
void doToggleConstruction ()
void doVerticalConstraint ()
void doVerticalDistance ()
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *event)
void keyPressEvent (QKeyEvent *event)
Constructor & Destructor Documentation
ElementView()
ElementView::ElementView (QWidget * parent = nullptr) explicit
~ElementView()
ElementView::~ElementView ()
Member Function Documentation
contextMenuEvent()
void ElementView::contextMenuEvent (QContextMenuEvent * event) protected
References deleteSelectedItems(), doAngleConstraint(), doBlockConstraint(), doDiameterConstraint(), doEqualConstraint(), doHorizontalConstraint(), doHorizontalDistance(), doLengthConstraint(), doLockConstraint(), doParallelConstraint(), doPerpendicularConstraint(), doPointCoincidence(), doPointOnObjectConstraint(), doRadiamConstraint(), doRadiusConstraint(), doSelectConstraints(), doSelectHAxis(), doSelectOrigin(), doSelectVAxis(), doSymmetricConstraint(), doTangentConstraint(), doToggleConstruction(), doVerticalConstraint(), and doVerticalDistance().
deleteSelectedItems
void ElementView::deleteSelectedItems () protected slot
References App::Application::getActiveDocument(), App::GetApplication(), Gui::SelectionSingleton::getSelectionEx(), Gui::Application::getViewProvider(), Gui::Application::Instance, Gui::ViewProvider::onDelete(), and Gui::Selection().
Referenced by contextMenuEvent().
doAngleConstraint
void SketcherGui::ElementView::doAngleConstraint () protected slot
Referenced by contextMenuEvent().
doBlockConstraint
void SketcherGui::ElementView::doBlockConstraint () protected slot
Referenced by contextMenuEvent().
doDiameterConstraint
void SketcherGui::ElementView::doDiameterConstraint () protected slot
Referenced by contextMenuEvent().
doEqualConstraint
void SketcherGui::ElementView::doEqualConstraint () protected slot
Referenced by contextMenuEvent().
doHorizontalConstraint
void SketcherGui::ElementView::doHorizontalConstraint () protected slot
Referenced by contextMenuEvent().
doHorizontalDistance
void SketcherGui::ElementView::doHorizontalDistance () protected slot
Referenced by contextMenuEvent().
doLengthConstraint
void SketcherGui::ElementView::doLengthConstraint () protected slot
Referenced by contextMenuEvent().
doLockConstraint
void SketcherGui::ElementView::doLockConstraint () protected slot
Referenced by contextMenuEvent().
doParallelConstraint
void SketcherGui::ElementView::doParallelConstraint () protected slot
Referenced by contextMenuEvent().
doPerpendicularConstraint
void SketcherGui::ElementView::doPerpendicularConstraint () protected slot
Referenced by contextMenuEvent().
doPointCoincidence
void SketcherGui::ElementView::doPointCoincidence () protected slot
Referenced by contextMenuEvent().
doPointOnObjectConstraint
void SketcherGui::ElementView::doPointOnObjectConstraint () protected slot
Referenced by contextMenuEvent().
doRadiamConstraint
void SketcherGui::ElementView::doRadiamConstraint () protected slot
Referenced by contextMenuEvent().
doRadiusConstraint
void SketcherGui::ElementView::doRadiusConstraint () protected slot
Referenced by contextMenuEvent().
doSelectConstraints
void SketcherGui::ElementView::doSelectConstraints () protected slot
Referenced by contextMenuEvent().
doSelectHAxis
void SketcherGui::ElementView::doSelectHAxis () protected slot
Referenced by contextMenuEvent().
doSelectOrigin
void SketcherGui::ElementView::doSelectOrigin () protected slot
Referenced by contextMenuEvent().
doSelectVAxis
void SketcherGui::ElementView::doSelectVAxis () protected slot
Referenced by contextMenuEvent().
doSymmetricConstraint
void SketcherGui::ElementView::doSymmetricConstraint () protected slot
Referenced by contextMenuEvent().
doTangentConstraint
void SketcherGui::ElementView::doTangentConstraint () protected slot
Referenced by contextMenuEvent().
doToggleConstruction
void SketcherGui::ElementView::doToggleConstruction () protected slot
Referenced by contextMenuEvent().
doVerticalConstraint
void SketcherGui::ElementView::doVerticalConstraint () protected slot
Referenced by contextMenuEvent().
doVerticalDistance
void SketcherGui::ElementView::doVerticalDistance () protected slot
Referenced by contextMenuEvent().
keyPressEvent()
void ElementView::keyPressEvent (QKeyEvent * event) protected
References onFilterShortcutPressed().
onFilterShortcutPressed
void SketcherGui::ElementView::onFilterShortcutPressed () signal
Referenced by keyPressEvent().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/Gui/TaskSketcherElements.h
FreeCAD/src/Mod/Sketcher/Gui/TaskSketcherElements.cpp