FreeCAD: importDAE Namespace Reference
importDAE Namespace Reference
Workbenches » Python workbenches » Arch
DAE (Collada) file format importer and exporter.
Functions
def checkCollada ()
def decode (name)
def export (exportList, filename, tessellation=1, colors=None)
def insert (filename, docname)
def open (filename)
def read (filename)
def triangulate (shape)
Variables
bool DEBUG = True
range = xrange
Detailed Description
DAE (Collada) file format importer and exporter.
This module provides tools to import and export Collada (.dae) files.
Function Documentation
checkCollada()
def importDAE.checkCollada ()
Referenced by export(), insert(), and open().
decode()
def importDAE.decode (name)
Referenced by open().
export()
def importDAE.export (exportList, filename, tessellation = 1, colors = None)
export(exportList,filename,tessellation=1,colors=None) -- exports FreeCAD contents to a DAE file.
colors is an optional dictionary of objName:shapeColorTuple or objName:diffuseColorList elements
to be used in non-GUI mode if you want to be able to export colors. Tessellation is used when breaking
curved surfaces into triangles.
References checkCollada(), and triangulate().
insert()
def importDAE.insert (filename, docname)
References checkCollada(), and read().
open()
def importDAE.open (filename)
References checkCollada(), decode(), and read().
read()
def importDAE.read (filename)
Referenced by insert(), and open().
triangulate()
def importDAE.triangulate (shape)
Referenced by export(), exportIFC.getRepresentation(), and ArchCommands.removeCurves().
Variable Documentation
DEBUG
bool importDAE.DEBUG = True
range
importDAE.range = xrange