FreeCAD: App::RangeExpression Class Reference
App::RangeExpression Class Reference
#include <ExpressionParser.h>
Public Member Functions
Range getRange () const
virtual bool isTouched () const override
RangeExpression (const App::DocumentObject *_owner=0, const std::string &begin=std::string(), const std::string &end=std::string())
virtual App::Expression * simplify () const override
virtual ~RangeExpression ()
Public Member Functions inherited from App::Expression
virtual void addComponent (Component *component)
bool adjustLinks (const std::set< App::DocumentObject * > &inList)
Expression * copy () const
Expression * eval () const
Expression (const App::DocumentObject *_owner)
void getDepObjects (std::set< App::DocumentObject * > &, std::vector< std::string > *labels=0) const
std::set< App::DocumentObject * > getDepObjects (std::vector< std::string > *labels=0) const
ExpressionDeps getDeps () const
void getDeps (ExpressionDeps &deps) const
std::set< App::ObjectIdentifier > getIdentifiers () const
void getIdentifiers (std::set< App::ObjectIdentifier > &) const
App::DocumentObject * getOwner () const
Py::Object getPyValue () const
boost::any getValueAsAny () const
bool hasComponent () const
ExpressionPtr importSubNames (const std::map< std::string, std::string > &nameMap) const
bool isSame (const Expression &other) const
virtual int priority () const
ExpressionPtr replaceObject (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
std::string toString (bool persistent=false, bool checkPriority=false, int indent=0) const
void toString (std::ostream &os, bool persistent=false, bool checkPriority=false, int indent=0) const
ExpressionPtr updateLabelReference (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const
void visit (ExpressionVisitor &v)
virtual ~Expression ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId (void) const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Attributes
std::string begin
std::string end
Protected Attributes inherited from App::Expression
ComponentList components
App::DocumentObject * owner
The document object used to access unqualified variables (i.e local scope)
Additional Inherited Members
Public Types inherited from App::Expression
typedef std::vector< Component * > ComponentList
Static Public Member Functions inherited from App::Expression
static Component * createComponent (const std::string &n)
static Component * createComponent (Expression *e1, Expression *e2=0, Expression *e3=0, bool isRange=false)
static Expression * parse (const App::DocumentObject *owner, const std::string &buffer)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Public Attributes inherited from App::Expression
std::string comment
friend ExpressionVisitor
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
RangeExpression()
RangeExpression::RangeExpression (const App::DocumentObject * _owner = 0, const std::string & begin = std::string(), const std::string & end = std::string())
~RangeExpression()
virtual App::RangeExpression::~RangeExpression () virtual
Member Function Documentation
getRange()
Range RangeExpression::getRange () const
References App::DocumentObject::getPyObject(), App::Expression::owner, and App::stringToAddress().
Referenced by App::FunctionExpression::evalAggregate().
isTouched()
bool RangeExpression::isTouched (void) const override virtual
Reimplemented from App::Expression.
References App::ExtensionContainer::getPropertyByName(), App::Property::isTouched(), and App::Expression::owner.
simplify()
Expression * RangeExpression::simplify () const override virtual
Implements App::Expression.
References App::Expression::copy().
Member Data Documentation
begin
std::string App::RangeExpression::begin protected
end
std::string App::RangeExpression::end protected
Referenced by Dice3DS.dom3ds.FileLikeBuffer::advance(), Dice3DS.dom3ds.FileLikeBuffer::read_rest(), Dice3DS.dom3ds.FileLikeBuffer::read_to_nul(), Dice3DS.dom3ds.FileLikeBuffer::room_for_chunks(), and Dice3DS.dom3ds.FileLikeBuffer::seek().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/App/ExpressionParser.h
Sources/FreeCAD/src/App/Expression.cpp