FreeCAD: draftviewproviders.view_base.ViewProviderDraftPart Class Reference
draftviewproviders.view_base.ViewProviderDraftPart Class Reference
Workbenches » Python workbenches » Draft » draftviewproviders
Public Member Functions
def getIcon (self)
Public Member Functions inherited from draftviewproviders.view_base.ViewProviderDraftAlt
def claimChildren (self)
Public Member Functions inherited from draftviewproviders.view_base.ViewProviderDraft
def attach (self, vobj)
def claimChildren (self)
def execute (self, vobj)
def getDefaultDisplayMode (self)
def getDisplayModes (self, vobj)
def getIcon (self)
def onChanged (self, vobj, prop)
def setDisplayMode (self, mode)
def setEdit (self, vobj, mode=0)
def unsetEdit (self, vobj, mode=0)
def updateData (self, obj, prop)
Additional Inherited Members
Public Attributes inherited from draftviewproviders.view_base.ViewProviderDraft
Object
texcoords
texture
Detailed Description
A view provider that displays a Part icon instead of a Draft icon.
The `getIcon` method is overridden to provide `Part_3D_object.svg`.
Member Function Documentation
getIcon()
def draftviewproviders.view_base.ViewProviderDraftPart.getIcon (self)
Return the path to the icon used by the view provider.
The path can be a full path in the system, or a relative path
inside the compiled resource file.
It can also be a string that defines the icon in XPM format.
Override this method to provide a specific icon
for the object in the tree view.
By default it returns the path to the `Draft_Draft.svg` icon.
Returns
-------
str
    `':/icons/Draft_Draft.svg'`
Reimplemented from draftviewproviders.view_base.ViewProviderDraft.
Referenced by ArchAxisSystem.AxisSystemTaskPanel.update(), ArchComponent.ComponentTaskPanel.update(), and ArchSectionPlane.SectionPlaneTaskPanel.update().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Draft/draftviewproviders/view_base.py