FreeCAD: PathScripts.post.KineticNCBeamicon2_post Namespace Reference
PathScripts.post.KineticNCBeamicon2_post Namespace Reference
Functions
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
def processArguments (argstring)
Variables
action
string COMMAND_SPACE = " "
dictionary CORNER_MAX = {"x": 1000, "y": 600, "z": 300}
dictionary CORNER_MIN = {"x": 0, "y": 0, "z": 0}
default
help
int LINENR = 100
string MACHINE_NAME = "not set"
bool MODAL = False
now = datetime.datetime.now()
bool OUTPUT_COMMENTS = True
tuple OUTPUT_DOUBLES
bool OUTPUT_HEADER = True
bool OUTPUT_LINE_NUMBERS = False
parser = argparse.ArgumentParser(prog="linuxcnc", add_help=False)
string POST_OPERATION = """"""
string POSTAMBLE
string PRE_OPERATION = """"""
string PREAMBLE
int PRECISION = 3
pythonopen = open
bool SHOW_EDITOR = True
string TOOL_CHANGE
string TOOLTIP
TOOLTIP_ARGS = parser.format_help()
string UNIT_FORMAT = "mm"
string UNIT_SPEED_FORMAT = "mm/min"
string UNITS = "G21"
Function Documentation
export()
def PathScripts.post.KineticNCBeamicon2_post.export (objectslist, filename, argstring)
References PathScripts.post.KineticNCBeamicon2_post.linenumber(), PathScripts.post.KineticNCBeamicon2_post.parse(), PathScripts.post.KineticNCBeamicon2_post.processArguments(), and PathScripts.post.KineticNCBeamicon2_post.pythonopen.
linenumber()
def PathScripts.post.KineticNCBeamicon2_post.linenumber ()
Referenced by PathScripts.post.KineticNCBeamicon2_post.export(), and PathScripts.post.KineticNCBeamicon2_post.parse().
parse()
def PathScripts.post.KineticNCBeamicon2_post.parse (pathobj)
References PathScripts.post.KineticNCBeamicon2_post.linenumber(), and PathScripts.post.KineticNCBeamicon2_post.parse().
Referenced by PathScripts.post.KineticNCBeamicon2_post.export(), and PathScripts.post.KineticNCBeamicon2_post.parse().
processArguments()
def PathScripts.post.KineticNCBeamicon2_post.processArguments (argstring)
Referenced by PathScripts.post.KineticNCBeamicon2_post.export().
Variable Documentation
action
PathScripts.post.KineticNCBeamicon2_post.action
COMMAND_SPACE
string PathScripts.post.KineticNCBeamicon2_post.COMMAND_SPACE = " "
CORNER_MAX
dictionary PathScripts.post.KineticNCBeamicon2_post.CORNER_MAX = {"x": 1000, "y": 600, "z": 300}
CORNER_MIN
dictionary PathScripts.post.KineticNCBeamicon2_post.CORNER_MIN = {"x": 0, "y": 0, "z": 0}
default
PathScripts.post.KineticNCBeamicon2_post.default
help
PathScripts.post.KineticNCBeamicon2_post.help
LINENR
int PathScripts.post.KineticNCBeamicon2_post.LINENR = 100
MACHINE_NAME
string PathScripts.post.KineticNCBeamicon2_post.MACHINE_NAME = "not set"
MODAL
bool PathScripts.post.KineticNCBeamicon2_post.MODAL = False
now
PathScripts.post.KineticNCBeamicon2_post.now = datetime.datetime.now()
OUTPUT_COMMENTS
bool PathScripts.post.KineticNCBeamicon2_post.OUTPUT_COMMENTS = True
OUTPUT_DOUBLES
tuple PathScripts.post.KineticNCBeamicon2_post.OUTPUT_DOUBLES
Initial value:
=  (
    True  # if false duplicate axis values are suppressed if the same as previous line.
)
OUTPUT_HEADER
bool PathScripts.post.KineticNCBeamicon2_post.OUTPUT_HEADER = True
OUTPUT_LINE_NUMBERS
bool PathScripts.post.KineticNCBeamicon2_post.OUTPUT_LINE_NUMBERS = False
parser
PathScripts.post.KineticNCBeamicon2_post.parser = argparse.ArgumentParser(prog="linuxcnc", add_help=False)
POST_OPERATION
string PathScripts.post.KineticNCBeamicon2_post.POST_OPERATION = """"""
POSTAMBLE
string PathScripts.post.KineticNCBeamicon2_post.POSTAMBLE
Initial value:
=  """M05 M09
G17 G90 G80 G40
M30
"""
PRE_OPERATION
string PathScripts.post.KineticNCBeamicon2_post.PRE_OPERATION = """"""
PREAMBLE
string PathScripts.post.KineticNCBeamicon2_post.PREAMBLE
Initial value:
=  """%
G17 G21 G40 G49 G80 G90
M08
"""
PRECISION
int PathScripts.post.KineticNCBeamicon2_post.PRECISION = 3
pythonopen
PathScripts.post.KineticNCBeamicon2_post.pythonopen = open
Referenced by PathScripts.post.KineticNCBeamicon2_post.export().
SHOW_EDITOR
bool PathScripts.post.KineticNCBeamicon2_post.SHOW_EDITOR = True
TOOL_CHANGE
string PathScripts.post.KineticNCBeamicon2_post.TOOL_CHANGE
Initial value:
=  """M05
M09"""
TOOLTIP
string PathScripts.post.KineticNCBeamicon2_post.TOOLTIP
Initial value:
=  """
This is a postprocessor file for the Path workbench. It is used to
take a pseudo-gcode fragment outputted by a Path object, and output
real GCode suitable for the KineticNC/Beamicon2 Control Software for up to 4 Axis (3 plus rotary).
The CORNER_MAX Values are set for a mill with max travel of 1000mm in X, 600mm in Y and 300mm in Z direction.
This postprocessor, once placed in the appropriate PathScripts folder, can be used directly from inside
FreeCAD, via the GUI importer or via python scripts with:
import KineticNCBeamicon2_post
KineticNCBeamicon2_post.export(object,"/path/to/file.ncc","")
"""
TOOLTIP_ARGS
PathScripts.post.KineticNCBeamicon2_post.TOOLTIP_ARGS = parser.format_help()
UNIT_FORMAT
string PathScripts.post.KineticNCBeamicon2_post.UNIT_FORMAT = "mm"
UNIT_SPEED_FORMAT
string PathScripts.post.KineticNCBeamicon2_post.UNIT_SPEED_FORMAT = "mm/min"
UNITS
string PathScripts.post.KineticNCBeamicon2_post.UNITS = "G21"