FreeCAD: MeshGui::SegmentationBestFit Class Reference
MeshGui::SegmentationBestFit Class Reference
#include <SegmentationBestFit.h>
Public Member Functions
void accept ()
SegmentationBestFit (Mesh::Feature *mesh, QWidget *parent=0, Qt::WindowFlags fl=Qt::WindowFlags())
~SegmentationBestFit ()
Protected Member Functions
void changeEvent (QEvent *e)
Constructor & Destructor Documentation
SegmentationBestFit()
SegmentationBestFit::SegmentationBestFit (Mesh::Feature * mesh, QWidget * parent = 0, Qt::WindowFlags fl = Qt::WindowFlags())
References MeshGui::MeshSelection::setObjects().
~SegmentationBestFit()
SegmentationBestFit::~SegmentationBestFit ()
Member Function Documentation
accept()
void SegmentationBestFit::accept (void)
References App::Document::addObject(), App::Document::commitTransaction(), MeshCore::MeshSegmentAlgorithm::FindSegments(), Mesh::PropertyMeshKernel::finishEditing(), App::Application::getActiveDocument(), App::GetApplication(), App::DocumentObject::getNameInDocument(), App::PropertyString::getValue(), Mesh::PropertyMeshKernel::getValuePtr(), App::DocumentObject::Label, Mesh::Feature::Mesh, App::Document::openTransaction(), App::PropertyString::setValue(), Mesh::PropertyMeshKernel::startEditing(), and Mesh::MeshObject::swap().
Referenced by MeshGui::TaskSegmentationBestFit::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void SegmentationBestFit::changeEvent (QEvent * e) protected
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/Gui/SegmentationBestFit.h
Sources/FreeCAD/src/Mod/Mesh/Gui/SegmentationBestFit.cpp