FreeCAD: Ui_TaskMoveView Class Reference
Ui_TaskMoveView Class Reference
#include <ui_TaskMoveView.h>
Public Member Functions
void retranslateUi (QWidget *TaskMoveView)
void setupUi (QWidget *TaskMoveView)
Public Attributes
QGridLayout * gridLayout
QLineEdit * leFromPage
QLineEdit * leToPage
QLineEdit * leView
QLabel * lFromPage
QLabel * lToPage
QLabel * lViewName
QPushButton * pbFromPage
QPushButton * pbToPage
QPushButton * pbView
QVBoxLayout * verticalLayout
QSpacerItem * verticalSpacer
Member Function Documentation
retranslateUi()
void Ui_TaskMoveView::retranslateUi (QWidget * TaskMoveView)
References lFromPage, lToPage, lViewName, pbFromPage, pbToPage, pbView, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Ui_TaskMoveView::setupUi (QWidget * TaskMoveView)
References gridLayout, leFromPage, leToPage, leView, lFromPage, lToPage, lViewName, pbFromPage, pbToPage, pbView, retranslateUi(), verticalLayout, and verticalSpacer.
Member Data Documentation
gridLayout
QGridLayout* Ui_TaskMoveView::gridLayout
Referenced by setupUi().
leFromPage
QLineEdit* Ui_TaskMoveView::leFromPage
Referenced by setupUi().
leToPage
QLineEdit* Ui_TaskMoveView::leToPage
Referenced by setupUi().
leView
QLineEdit* Ui_TaskMoveView::leView
Referenced by setupUi().
lFromPage
QLabel* Ui_TaskMoveView::lFromPage
Referenced by retranslateUi(), and setupUi().
lToPage
QLabel* Ui_TaskMoveView::lToPage
Referenced by retranslateUi(), and setupUi().
lViewName
QLabel* Ui_TaskMoveView::lViewName
Referenced by retranslateUi(), and setupUi().
pbFromPage
QPushButton* Ui_TaskMoveView::pbFromPage
Referenced by retranslateUi(), and setupUi().
pbToPage
QPushButton* Ui_TaskMoveView::pbToPage
Referenced by retranslateUi(), and setupUi().
pbView
QPushButton* Ui_TaskMoveView::pbView
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* Ui_TaskMoveView::verticalLayout
Referenced by setupUi().
verticalSpacer
QSpacerItem* Ui_TaskMoveView::verticalSpacer
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/TechDraw/Gui/ui_TaskMoveView.h