FreeCAD: TechDrawGui::DlgPrefsTechDrawAnnotationImp Class Reference
TechDrawGui::DlgPrefsTechDrawAnnotationImp Class Reference
#include <DlgPrefsTechDrawAnnotationImp.h>
Public Slots
void onLineGroupChanged (int)
Updates the tooltip of the LineGroup combobox.
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Public Member Functions
DlgPrefsTechDrawAnnotationImp (QWidget *parent=nullptr)
~DlgPrefsTechDrawAnnotationImp ()
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void loadSettings ()
int prefBalloonArrow (void) const
void saveSettings ()
virtual void changeEvent (QEvent *e)=0
Constructor & Destructor Documentation
DlgPrefsTechDrawAnnotationImp()
DlgPrefsTechDrawAnnotationImp::DlgPrefsTechDrawAnnotationImp (QWidget * parent = nullptr)
References draftgeoutils.intersections::connect(), Base::Unit::Length, and onLineGroupChanged().
~DlgPrefsTechDrawAnnotationImp()
DlgPrefsTechDrawAnnotationImp::~DlgPrefsTechDrawAnnotationImp ()
Member Function Documentation
changeEvent()
void DlgPrefsTechDrawAnnotationImp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
References loadSettings(), and saveSettings().
loadSettings()
void DlgPrefsTechDrawAnnotationImp::loadSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References TechDrawGui::DrawGuiUtil::loadArrowBox(), and prefBalloonArrow().
Referenced by changeEvent().
onLineGroupChanged
void DlgPrefsTechDrawAnnotationImp::onLineGroupChanged (int index) slot
Updates the tooltip of the LineGroup combobox.
Referenced by DlgPrefsTechDrawAnnotationImp().
prefBalloonArrow()
int DlgPrefsTechDrawAnnotationImp::prefBalloonArrow (void) const protected
Referenced by loadSettings().
saveSettings()
void DlgPrefsTechDrawAnnotationImp::saveSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
Referenced by changeEvent().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotationImp.h
FreeCAD/src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotationImp.cpp