FreeCAD: Part::BuildPlateSurfacePy Class Reference
Part::BuildPlateSurfacePy Class Reference
The python export class for GeomPlate_BuildPlateSurface.
#include <BuildPlateSurfacePy.h>
Public Types
typedef GeomPlate_BuildPlateSurface * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
BuildPlateSurfacePy (GeomPlate_BuildPlateSurface *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomPlate_BuildPlateSurface * getGeomPlate_BuildPlateSurfacePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
BuildPlateSurfacePy::PyMake.
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of BuildPlateSurfacePy.
static PyMethodDef Methods []
Methods structure of BuildPlateSurfacePy.
static PyTypeObject Type
Type structure of BuildPlateSurfacePy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~BuildPlateSurfacePy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * init (PyObject *args)
implementer for the init() method
PyObject * setNbBounds (PyObject *args)
implementer for the setNbBounds() method
PyObject * loadInitSurface (PyObject *args)
implementer for the loadInitSurface() method
PyObject * surfInit (PyObject *args)
implementer for the surfInit() method
PyObject * surface (PyObject *args)
implementer for the surface() method
PyObject * add (PyObject *args)
implementer for the add() method
PyObject * perform (PyObject *args)
implementer for the perform() method
PyObject * isDone (PyObject *args)
implementer for the isDone() method
PyObject * sense (PyObject *args)
implementer for the sense() method
PyObject * order (PyObject *args)
implementer for the order() method
PyObject * curves2d (PyObject *args)
implementer for the curves2d() method
PyObject * curveConstraint (PyObject *args)
implementer for the curveConstraint() method
PyObject * pointConstraint (PyObject *args)
implementer for the pointConstraint() method
PyObject * disc2dContour (PyObject *args)
implementer for the disc2dContour() method
PyObject * disc3dContour (PyObject *args)
implementer for the disc3dContour() method
PyObject * G0Error (PyObject *args)
implementer for the G0Error() method
PyObject * G1Error (PyObject *args)
implementer for the G1Error() method
PyObject * G2Error (PyObject *args)
implementer for the G2Error() method
static PyObject * staticCallback_init (PyObject *self, PyObject *args)
callback for the init() method
static PyObject * staticCallback_setNbBounds (PyObject *self, PyObject *args)
callback for the setNbBounds() method
static PyObject * staticCallback_loadInitSurface (PyObject *self, PyObject *args)
callback for the loadInitSurface() method
static PyObject * staticCallback_surfInit (PyObject *self, PyObject *args)
callback for the surfInit() method
static PyObject * staticCallback_surface (PyObject *self, PyObject *args)
callback for the surface() method
static PyObject * staticCallback_add (PyObject *self, PyObject *args)
callback for the add() method
static PyObject * staticCallback_perform (PyObject *self, PyObject *args)
callback for the perform() method
static PyObject * staticCallback_isDone (PyObject *self, PyObject *args)
callback for the isDone() method
static PyObject * staticCallback_sense (PyObject *self, PyObject *args)
callback for the sense() method
static PyObject * staticCallback_order (PyObject *self, PyObject *args)
callback for the order() method
static PyObject * staticCallback_curves2d (PyObject *self, PyObject *args)
callback for the curves2d() method
static PyObject * staticCallback_curveConstraint (PyObject *self, PyObject *args)
callback for the curveConstraint() method
static PyObject * staticCallback_pointConstraint (PyObject *self, PyObject *args)
callback for the pointConstraint() method
static PyObject * staticCallback_disc2dContour (PyObject *self, PyObject *args)
callback for the disc2dContour() method
static PyObject * staticCallback_disc3dContour (PyObject *self, PyObject *args)
callback for the disc3dContour() method
static PyObject * staticCallback_G0Error (PyObject *self, PyObject *args)
callback for the G0Error() method
static PyObject * staticCallback_G1Error (PyObject *self, PyObject *args)
callback for the G1Error() method
static PyObject * staticCallback_G2Error (PyObject *self, PyObject *args)
callback for the G2Error() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeomPlate_BuildPlateSurface.
Member Typedef Documentation
PointerType
typedef GeomPlate_BuildPlateSurface* Part::BuildPlateSurfacePy::PointerType
Constructor & Destructor Documentation
~BuildPlateSurfacePy()
BuildPlateSurfacePy::~BuildPlateSurfacePy () protected
BuildPlateSurfacePy()
BuildPlateSurfacePy::BuildPlateSurfacePy (GeomPlate_BuildPlateSurface * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
add()
PyObject * BuildPlateSurfacePy::add (PyObject * args)
implementer for the add() method
References getGeomPlate_BuildPlateSurfacePtr(), Part::CurveConstraintPy::Type, and Part::PointConstraintPy::Type.
Referenced by staticCallback_add().
curveConstraint()
PyObject * BuildPlateSurfacePy::curveConstraint (PyObject * args)
implementer for the curveConstraint() method
References getGeomPlate_BuildPlateSurfacePtr().
Referenced by staticCallback_curveConstraint().
curves2d()
PyObject * BuildPlateSurfacePy::curves2d (PyObject * args)
implementer for the curves2d() method
References getGeomPlate_BuildPlateSurfacePtr(), and Part::makeFromCurve2d().
Referenced by staticCallback_curves2d().
disc2dContour()
PyObject * BuildPlateSurfacePy::disc2dContour (PyObject * args)
implementer for the disc2dContour() method
References getGeomPlate_BuildPlateSurfacePtr().
Referenced by staticCallback_disc2dContour().
disc3dContour()
PyObject * BuildPlateSurfacePy::disc3dContour (PyObject * args)
implementer for the disc3dContour() method
References getGeomPlate_BuildPlateSurfacePtr(), and order().
Referenced by staticCallback_disc3dContour().
G0Error()
PyObject * BuildPlateSurfacePy::G0Error (PyObject * args)
implementer for the G0Error() method
References getGeomPlate_BuildPlateSurfacePtr().
Referenced by staticCallback_G0Error().
G1Error()
PyObject * BuildPlateSurfacePy::G1Error (PyObject * args)
implementer for the G1Error() method
References getGeomPlate_BuildPlateSurfacePtr().
Referenced by staticCallback_G1Error().
G2Error()
PyObject * BuildPlateSurfacePy::G2Error (PyObject * args)
implementer for the G2Error() method
References getGeomPlate_BuildPlateSurfacePtr().
Referenced by staticCallback_G2Error().
getCustomAttributes()
PyObject * BuildPlateSurfacePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getGeomPlate_BuildPlateSurfacePtr()
GeomPlate_BuildPlateSurface * BuildPlateSurfacePy::getGeomPlate_BuildPlateSurfacePtr (void) const
getter for the object handled by this class
Referenced by add(), curveConstraint(), curves2d(), disc2dContour(), disc3dContour(), G0Error(), G1Error(), G2Error(), init(), isDone(), loadInitSurface(), order(), perform(), pointConstraint(), sense(), setNbBounds(), surface(), and surfInit().
GetType()
virtual PyTypeObject* Part::BuildPlateSurfacePy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
init()
PyObject * BuildPlateSurfacePy::init (PyObject * args)
implementer for the init() method
References getGeomPlate_BuildPlateSurfacePtr().
Referenced by DocumentObject.DocumentObject::onChanged(), and staticCallback_init().
isDone()
PyObject * BuildPlateSurfacePy::isDone (PyObject * args)
implementer for the isDone() method
References getGeomPlate_BuildPlateSurfacePtr().
Referenced by staticCallback_isDone().
loadInitSurface()
PyObject * BuildPlateSurfacePy::loadInitSurface (PyObject * args)
implementer for the loadInitSurface() method
References getGeomPlate_BuildPlateSurfacePtr(), surface(), and Part::GeometrySurfacePy::Type.
Referenced by staticCallback_loadInitSurface().
order()
PyObject * BuildPlateSurfacePy::order (PyObject * args)
implementer for the order() method
References getGeomPlate_BuildPlateSurfacePtr().
Referenced by disc3dContour(), femmesh.gmshtools.GmshTools::start_logs(), staticCallback_order(), and femmesh.gmshtools.GmshTools::write_geo().
perform()
PyObject * BuildPlateSurfacePy::perform (PyObject * args)
implementer for the perform() method
References getGeomPlate_BuildPlateSurfacePtr().
Referenced by staticCallback_perform().
pointConstraint()
PyObject * BuildPlateSurfacePy::pointConstraint (PyObject * args)
implementer for the pointConstraint() method
References getGeomPlate_BuildPlateSurfacePtr().
Referenced by staticCallback_pointConstraint().
PyInit()
int BuildPlateSurfacePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
References Base::PyObjectBase::setTwinPointer(), surface(), and Part::GeometrySurfacePy::Type.
PyMake()
PyObject * BuildPlateSurfacePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
BuildPlateSurfacePy::PyMake.
v1=App.Vector(0,0,0)
v2=App.Vector(10,0,0)
v3=App.Vector(10,10,3)
v4=App.Vector(0,10,0)
v5=App.Vector(5,5,5)
l1=Part.LineSegment(v1, v2)
l2=Part.LineSegment(v2, v3)
l3=Part.LineSegment(v3, v4)
l4=Part.LineSegment(v4, v1)
c1=Part.GeomPlate.CurveConstraint(l1)
c2=Part.GeomPlate.CurveConstraint(l2)
c3=Part.GeomPlate.CurveConstraint(l3)
c4=Part.GeomPlate.CurveConstraint(l4)
c5=Part.GeomPlate.PointConstraint(v5)
bp=Part.GeomPlate.BuildPlateSurface()
bp.add(c1)
bp.add(c2)
bp.add(c3)
bp.add(c4)
bp.add(c5)
bp.perform()
s=bp.surface()
bs=s.makeApprox()
Part.show(bs.toShape())
Part.show(l1.toShape())
Part.show(l2.toShape())
Part.show(l3.toShape())
Part.show(l4.toShape())
bp.surfInit()
References BuildPlateSurfacePy().
representation()
std::string BuildPlateSurfacePy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
sense()
PyObject * BuildPlateSurfacePy::sense (PyObject * args)
implementer for the sense() method
References getGeomPlate_BuildPlateSurfacePtr().
Referenced by staticCallback_sense(), and automotive_design.coordinated_universal_time_offset::wr3().
setCustomAttributes()
int BuildPlateSurfacePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setNbBounds()
PyObject * BuildPlateSurfacePy::setNbBounds (PyObject * args)
implementer for the setNbBounds() method
References getGeomPlate_BuildPlateSurfacePtr().
Referenced by staticCallback_setNbBounds().
staticCallback_add()
PyObject * BuildPlateSurfacePy::staticCallback_add (PyObject * self, PyObject * args) static
callback for the add() method
References add(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_curveConstraint()
PyObject * BuildPlateSurfacePy::staticCallback_curveConstraint (PyObject * self, PyObject * args) static
callback for the curveConstraint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, curveConstraint(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_curves2d()
PyObject * BuildPlateSurfacePy::staticCallback_curves2d (PyObject * self, PyObject * args) static
callback for the curves2d() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, curves2d(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_disc2dContour()
PyObject * BuildPlateSurfacePy::staticCallback_disc2dContour (PyObject * self, PyObject * args) static
callback for the disc2dContour() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, disc2dContour(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_disc3dContour()
PyObject * BuildPlateSurfacePy::staticCallback_disc3dContour (PyObject * self, PyObject * args) static
callback for the disc3dContour() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, disc3dContour(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_G0Error()
PyObject * BuildPlateSurfacePy::staticCallback_G0Error (PyObject * self, PyObject * args) static
callback for the G0Error() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, G0Error(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_G1Error()
PyObject * BuildPlateSurfacePy::staticCallback_G1Error (PyObject * self, PyObject * args) static
callback for the G1Error() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, G1Error(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_G2Error()
PyObject * BuildPlateSurfacePy::staticCallback_G2Error (PyObject * self, PyObject * args) static
callback for the G2Error() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, G2Error(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_init()
PyObject * BuildPlateSurfacePy::staticCallback_init (PyObject * self, PyObject * args) static
callback for the init() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, init(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_isDone()
PyObject * BuildPlateSurfacePy::staticCallback_isDone (PyObject * self, PyObject * args) static
callback for the isDone() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isDone(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_loadInitSurface()
PyObject * BuildPlateSurfacePy::staticCallback_loadInitSurface (PyObject * self, PyObject * args) static
callback for the loadInitSurface() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), loadInitSurface(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_order()
PyObject * BuildPlateSurfacePy::staticCallback_order (PyObject * self, PyObject * args) static
callback for the order() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), order(), and Base::PyObjectBase::PyObjectBase().
staticCallback_perform()
PyObject * BuildPlateSurfacePy::staticCallback_perform (PyObject * self, PyObject * args) static
callback for the perform() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), perform(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_pointConstraint()
PyObject * BuildPlateSurfacePy::staticCallback_pointConstraint (PyObject * self, PyObject * args) static
callback for the pointConstraint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), pointConstraint(), and Base::PyObjectBase::PyObjectBase().
staticCallback_sense()
PyObject * BuildPlateSurfacePy::staticCallback_sense (PyObject * self, PyObject * args) static
callback for the sense() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and sense().
staticCallback_setNbBounds()
PyObject * BuildPlateSurfacePy::staticCallback_setNbBounds (PyObject * self, PyObject * args) static
callback for the setNbBounds() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setNbBounds(), and Base::PyObjectBase::startNotify().
staticCallback_surface()
PyObject * BuildPlateSurfacePy::staticCallback_surface (PyObject * self, PyObject * args) static
callback for the surface() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and surface().
staticCallback_surfInit()
PyObject * BuildPlateSurfacePy::staticCallback_surfInit (PyObject * self, PyObject * args) static
callback for the surfInit() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and surfInit().
surface()
PyObject * BuildPlateSurfacePy::surface (PyObject * args)
implementer for the surface() method
References getGeomPlate_BuildPlateSurfacePtr(), and Part::makeFromSurface().
Referenced by loadInitSurface(), PyInit(), and staticCallback_surface().
surfInit()
PyObject * BuildPlateSurfacePy::surfInit (PyObject * args)
implementer for the surfInit() method
References getGeomPlate_BuildPlateSurfacePtr(), and Part::makeFromSurface().
Referenced by staticCallback_surfInit().
Member Data Documentation
GetterSetter
PyGetSetDef BuildPlateSurfacePy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of BuildPlateSurfacePy.
Methods
PyMethodDef BuildPlateSurfacePy::Methods static
Methods structure of BuildPlateSurfacePy.
Type
PyTypeObject BuildPlateSurfacePy::Type static
Type structure of BuildPlateSurfacePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeomPlate/BuildPlateSurfacePy.h
Sources/FreeCAD/src/Mod/Part/App/GeomPlate/BuildPlateSurfacePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeomPlate/BuildPlateSurfacePy.cpp