FreeCAD: UChar Struct Reference
UChar Struct Reference
#include <UChar.h>
Public Member Functions
operator uint8_t () const
void read (Context &cont)
UChar ()
UChar (Context &cont)
Constructor & Destructor Documentation
UChar() [1/2]
UChar::UChar ()
UChar() [2/2]
UChar::UChar (Context & cont)
References read().
Member Function Documentation
operator uint8_t()
UChar::operator uint8_t () const
read()
void UChar::read (Context & cont)
References Context::Strm.
Referenced by Element_Header::read(), gzip_utf8.GzipFile::readline(), gzip_utf8.GzipFile::seek(), and UChar().
The documentation for this struct was generated from the following file:
FreeCAD/src/Mod/JtReader/App/JrJt/UChar.h