FreeCAD: PathSimulator::PathSimPy Class Reference
PathSimulator::PathSimPy Class Reference
The python export class for PathSim.
#include <PathSimPy.h>
Public Types
typedef PathSim * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
PathSimPy (PathSim *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of PathSimPy.
static PyMethodDef Methods []
Methods structure of PathSimPy.
static PyTypeObject Type
Type structure of PathSimPy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~PathSimPy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * BeginSimulation (PyObject *args, PyObject *kwd)
implementer for the BeginSimulation() method
PyObject * SetToolShape (PyObject *args)
implementer for the SetToolShape() method
PyObject * GetResultMesh (PyObject *args)
implementer for the GetResultMesh() method
PyObject * ApplyCommand (PyObject *args, PyObject *kwd)
implementer for the ApplyCommand() method
static PyObject * staticCallback_BeginSimulation (PyObject *self, PyObject *args, PyObject *kwd)
callback for the BeginSimulation() method
static PyObject * staticCallback_SetToolShape (PyObject *self, PyObject *args)
callback for the SetToolShape() method
static PyObject * staticCallback_GetResultMesh (PyObject *self, PyObject *args)
callback for the GetResultMesh() method
static PyObject * staticCallback_ApplyCommand (PyObject *self, PyObject *args, PyObject *kwd)
callback for the ApplyCommand() method
callbacks and implementers for the python object attributes
Py::Object getTool (void) const
getter for the Tool attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
PathSim * getPathSimPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getTool (PyObject *self, void *closure)
getter callback for the Tool attribute
static int staticCallback_setTool (PyObject *self, PyObject *value, void *closure)
setter callback for the Tool attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for PathSim.
Member Typedef Documentation
PointerType
typedef PathSim* PathSimulator::PathSimPy::PointerType
Constructor & Destructor Documentation
~PathSimPy()
PathSimPy::~PathSimPy () protected
PathSimPy()
PathSimPy::PathSimPy (PathSim * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
ApplyCommand()
PyObject * PathSimPy::ApplyCommand (PyObject * args, PyObject * kwd)
implementer for the ApplyCommand() method
References PathSimulator::PathSim::ApplyCommand(), getPathSimPtr(), Base::PlacementPy::Type, and Path::CommandPy::Type.
Referenced by staticCallback_ApplyCommand().
BeginSimulation()
PyObject * PathSimPy::BeginSimulation (PyObject * args, PyObject * kwd)
implementer for the BeginSimulation() method
References PathSimulator::PathSim::BeginSimulation(), getPathSimPtr(), and Part::TopoShapePy::Type.
Referenced by staticCallback_BeginSimulation().
getCustomAttributes()
PyObject * PathSimPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getPathSimPtr()
PathSim * PathSimPy::getPathSimPtr (void) const
getter for the object handled by this class
Referenced by ApplyCommand(), BeginSimulation(), GetResultMesh(), and SetToolShape().
GetResultMesh()
PyObject * PathSimPy::GetResultMesh (PyObject * args)
implementer for the GetResultMesh() method
References getPathSimPtr(), PathSimulator::PathSim::m_stock, and cStock::Tessellate().
Referenced by staticCallback_GetResultMesh().
getTool()
Py::Object PathSimPy::getTool (void) const
getter for the Tool attribute
Referenced by staticCallback_getTool().
GetType()
virtual PyTypeObject* PathSimulator::PathSimPy::GetType (void) virtual
Reimplemented from Base::BaseClassPy.
PyInit()
int PathSimPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::BaseClassPy.
PyMake()
PyObject * PathSimPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References PathSimPy().
representation()
std::string PathSimPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int PathSimPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
SetToolShape()
PyObject * PathSimPy::SetToolShape (PyObject * args)
implementer for the SetToolShape() method
References getPathSimPtr(), PathSimulator::PathSim::SetToolShape(), and Part::TopoShapePy::Type.
Referenced by staticCallback_SetToolShape().
staticCallback_ApplyCommand()
PyObject * PathSimPy::staticCallback_ApplyCommand (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the ApplyCommand() method
References ApplyCommand(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_BeginSimulation()
PyObject * PathSimPy::staticCallback_BeginSimulation (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the BeginSimulation() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, BeginSimulation(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_GetResultMesh()
PyObject * PathSimPy::staticCallback_GetResultMesh (PyObject * self, PyObject * args) static
callback for the GetResultMesh() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, GetResultMesh(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getTool()
PyObject * PathSimPy::staticCallback_getTool (PyObject * self, void * closure) static
getter callback for the Tool attribute
References Base::BaseExceptionFreeCADError, getTool(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setTool()
int PathSimPy::staticCallback_setTool (PyObject * self, PyObject * value, void * closure) static
setter callback for the Tool attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_SetToolShape()
PyObject * PathSimPy::staticCallback_SetToolShape (PyObject * self, PyObject * args) static
callback for the SetToolShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), SetToolShape(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef PathSimPy::GetterSetter static
Initial value:
= {
    {"Tool",
        (getter) staticCallback_getTool,
        (setter) staticCallback_setTool,
        "Return current simulation tool.",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of PathSimPy.
Methods
PyMethodDef PathSimPy::Methods static
Initial value:
= {
    {"BeginSimulation",
        reinterpret_cast<PyCFunction>(reinterpret_cast<void (*) (void)>( staticCallback_BeginSimulation )),
        METH_VARARGS|METH_KEYWORDS,
        "BeginSimulation(stock, resolution):\n\nStart a simulation process on a box shape stock with given resolution\n"
    },
    {"SetToolShape",
        reinterpret_cast<PyCFunction>( staticCallback_SetToolShape ),
        METH_VARARGS,
        "SetToolShape(shape):\n\nSet the shape of the tool to be used for simulation\n"
    },
    {"GetResultMesh",
        reinterpret_cast<PyCFunction>( staticCallback_GetResultMesh ),
        METH_VARARGS,
        "\n          GetResultMesh():\n\n          Return the current mesh result of the simulation.\n\n        "
    },
    {"ApplyCommand",
        reinterpret_cast<PyCFunction>(reinterpret_cast<void (*) (void)>( staticCallback_ApplyCommand )),
        METH_VARARGS|METH_KEYWORDS,
        "\n          ApplyCommand(placement, command):\n\n          Apply a single path command on the stock starting from placement.\n\n        "
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of PathSimPy.
Type
PyTypeObject PathSimPy::Type static
Type structure of PathSimPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Path/PathSimulator/App/PathSimPy.h
Sources/FreeCAD/src/Mod/Path/PathSimulator/App/PathSimPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Path/PathSimulator/App/PathSimPy.cpp