FreeCAD: GCS::Circle Class Reference
GCS::Circle Class Reference
#include <Geo.h>
Public Member Functions
DeriVector2 CalculateNormal (Point &p, double *derivparam=0)
Circle ()
virtual Circle * Copy ()
virtual int PushOwnParams (VEC_pD &pvec)
virtual void ReconstructOnNewPvec (VEC_pD &pvec, int &cnt)
DeriVector2 Value (double u, double du, double *derivparam=0)
Value: returns point (vector) given the value of parameter.
virtual ~Circle ()
Public Member Functions inherited from GCS::Curve
virtual ~Curve ()
Public Attributes
Point center
double * rad
Constructor & Destructor Documentation
Circle()
GCS::Circle::Circle ()
References rad.
Referenced by Copy().
~Circle()
virtual GCS::Circle::~Circle () virtual
Member Function Documentation
CalculateNormal()
DeriVector2 Circle::CalculateNormal (Point & p, double * derivparam = 0) virtual
Implements GCS::Curve.
References center, and GCS::DeriVector2::subtr().
Copy()
Circle * Circle::Copy (void) virtual
Implements GCS::Curve.
Reimplemented in GCS::Arc.
References Circle().
PushOwnParams()
int Circle::PushOwnParams (VEC_pD & pvec) virtual
Implements GCS::Curve.
Reimplemented in GCS::Arc.
References center, rad, GCS::Point::x, and GCS::Point::y.
Referenced by GCS::Arc::PushOwnParams().
ReconstructOnNewPvec()
void Circle::ReconstructOnNewPvec (VEC_pD & pvec, int & cnt) virtual
Implements GCS::Curve.
Reimplemented in GCS::Arc.
References center, rad, GCS::Point::x, and GCS::Point::y.
Referenced by GCS::Arc::ReconstructOnNewPvec().
Value()
DeriVector2 Circle::Value (double u, double du, double * derivparam = 0) virtual
Value: returns point (vector) given the value of parameter.
Parameters
u value of parameter
du derivative of parameter by derivparam
derivparam pointer to sketch parameter to calculate the derivative for
Returns
Reimplemented from GCS::Curve.
References center, GCS::DeriVector2::multD(), rad, GCS::DeriVector2::rotate90ccw(), and GCS::DeriVector2::sum().
Member Data Documentation
center
Point GCS::Circle::center
Referenced by Sketcher::Sketch::addCircle(), GCS::System::addConstraintTangent(), CalculateNormal(), PathScripts.PathDressupAxisMap.ObjectDressup::execute(), PathScripts.PathDressupAxisMap.ObjectDressup::onChanged(), PushOwnParams(), ReconstructOnNewPvec(), and Value().
rad
double* GCS::Circle::rad
Referenced by GCS::System::addConstraintEqualRadius(), GCS::System::addConstraintTangent(), GCS::Arc::Arc(), Circle(), PushOwnParams(), ReconstructOnNewPvec(), and Value().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Geo.h
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Geo.cpp