FreeCAD: automotive_design Namespace Reference
automotive_design Namespace Reference
Classes
class abs_function
class acos_function
class action
class action_assignment
class action_directive
class action_method
class action_method_relationship
class action_property
class action_property_representation
class action_relationship
class action_request_assignment
class action_request_solution
class action_request_status
class action_resource
class action_resource_requirement
class action_resource_type
class action_status
class address
class advanced_brep_shape_representation
class advanced_face
class ahead_or_behind
class alternate_product_relationship
class amount_of_substance_measure
class amount_of_substance_measure_with_unit
class amount_of_substance_unit
class and_expression
class angle_relator
class angular_dimension
class angular_location
class angular_size
class angularity_tolerance
class annotation_curve_occurrence
class annotation_fill_area
class annotation_fill_area_occurrence
class annotation_occurrence
class annotation_occurrence_associativity
class annotation_occurrence_relationship
class annotation_plane
class annotation_subfigure_occurrence
class annotation_symbol
class annotation_symbol_occurrence
class annotation_text
class annotation_text_character
class annotation_text_occurrence
class apex
class application_context
class application_context_element
class application_context_relationship
class application_protocol_definition
class applied_action_assignment
class applied_action_request_assignment
class applied_approval_assignment
class applied_area
class applied_certification_assignment
class applied_classification_assignment
class applied_contract_assignment
class applied_date_and_time_assignment
class applied_date_assignment
class applied_document_reference
class applied_document_usage_constraint_assignment
class applied_effectivity_assignment
class applied_event_occurrence_assignment
class applied_external_identification_assignment
class applied_group_assignment
class applied_identification_assignment
class applied_ineffectivity_assignment
class applied_name_assignment
class applied_organization_assignment
class applied_organizational_project_assignment
class applied_person_and_organization_assignment
class applied_presented_item
class applied_security_classification_assignment
class applied_time_interval_assignment
class approval
class approval_assignment
class approval_date_time
class approval_person_organization
class approval_relationship
class approval_role
class approval_status
class approximation_method
class approximation_tolerance
class approximation_tolerance_deviation
class approximation_tolerance_parameter
class area_in_set
class area_measure
class area_measure_with_unit
class area_unit
class asin_function
class assembly_component_usage
class assembly_component_usage_substitute
class atan_function
class attribute_classification_assignment
class attribute_language_assignment
class attribute_value_assignment
class attribute_value_role
class axis1_placement
class axis2_placement_2d
class axis2_placement_3d
class b_spline_curve
class b_spline_curve_form
class b_spline_curve_with_knots
class b_spline_surface
class b_spline_surface_form
class b_spline_surface_with_knots
class background_colour
class barring_hole
class bead
class bead_end
class bezier_curve
class bezier_surface
class binary_boolean_expression
class binary_function_call
class binary_generic_expression
class binary_numeric_expression
class block
class boolean_defined_function
class boolean_expression
class boolean_literal
class boolean_operator
class boolean_result
class boolean_variable
class boss
class boss_top
class boundary_curve
class bounded_curve
class bounded_pcurve
class bounded_surface
class bounded_surface_curve
class box_domain
class box_height
class box_rotate_angle
class box_slant_angle
class box_width
class boxed_half_space
class brep_with_voids
class calendar_date
class camera_image
class camera_image_2d_with_scale
class camera_image_3d_with_scale
class camera_model
class camera_model_d2
class camera_model_d3
class camera_model_d3_with_hlhsr
class camera_usage
class cartesian_point
class cartesian_transformation_operator
class cartesian_transformation_operator_2d
class cartesian_transformation_operator_3d
class celsius_temperature_measure
class celsius_temperature_measure_with_unit
class central_or_parallel
class centre_of_symmetry
class certification
class certification_assignment
class certification_type
class chamfer
class chamfer_offset
class character_glyph_symbol
class characterized_class
class characterized_object
class circle
class circular_closed_profile
class circular_pattern
class circular_runout_tolerance
class class_
class class_system
class class_usage_effectivity_context_assignment
class classification_assignment
class classification_role
class closed_path_profile
class closed_shell
class coaxiality_tolerance
class colour
class colour_rgb
class colour_specification
class common_datum
class comparison_equal
class comparison_expression
class comparison_greater
class comparison_greater_equal
class comparison_less
class comparison_less_equal
class comparison_not_equal
class composite_curve
class composite_curve_on_surface
class composite_curve_segment
class composite_hole
class composite_shape_aspect
class composite_text
class composite_text_with_associated_curves
class composite_text_with_blanking_box
class composite_text_with_extent
class compound_feature
class compound_representation_item
class compound_shape_representation
class concat_expression
class concentricity_tolerance
class concept_feature_operator
class concept_feature_relationship
class concept_feature_relationship_with_condition
class conditional_concept_feature
class configurable_item
class configuration_definition
class configuration_design
class configuration_effectivity
class configuration_interpolation
class configuration_item
class configured_effectivity_assignment
class configured_effectivity_context_assignment
class conic
class conical_surface
class connected_edge_set
class connected_face_set
class connected_face_sub_set
class constructive_geometry_representation
class constructive_geometry_representation_relationship
class contact_ratio_representation
class context_dependent_invisibility
class context_dependent_measure
class context_dependent_over_riding_styled_item
class context_dependent_shape_representation
class context_dependent_unit
class contract
class contract_assignment
class contract_type
class conversion_based_unit
class coordinated_universal_time_offset
class cos_function
class count_measure
class csg_shape_representation
class csg_solid
class curve
class curve_bounded_surface
class curve_dimension
class curve_replica
class curve_style
class curve_style_font
class curve_style_font_pattern
class curve_style_rendering
class curve_swept_solid_shape_representation
class curve_tolerance_deviation
class curve_tolerance_parameter
class cylindrical_pair
class cylindrical_pair_range
class cylindrical_pair_value
class cylindrical_surface
class cylindricity_tolerance
class data_environment
class date
class date_and_time
class date_and_time_assignment
class date_assignment
class date_role
class date_time_role
class dated_effectivity
class datum
class datum_feature
class datum_feature_callout
class datum_reference
class datum_target
class datum_target_callout
class day_in_month_number
class default_tolerance_table
class default_tolerance_table_cell
class defined_character_glyph
class defined_function
class defined_symbol
class definitional_representation
class degenerate_pcurve
class degenerate_toroidal_surface
class derived_shape_aspect
class derived_unit
class derived_unit_element
class derived_unit_variable
class description_attribute
class descriptive_measure
class descriptive_representation_item
class diameter_dimension
class dimension_callout
class dimension_callout_component_relationship
class dimension_callout_relationship
class dimension_count
class dimension_curve
class dimension_curve_directed_callout
class dimension_curve_terminator
class dimension_extent_usage
class dimension_pair
class dimension_related_tolerance_zone_element
class dimension_text_associativity
class dimensional_characteristic_representation
class dimensional_exponents
class dimensional_location
class dimensional_location_with_path
class dimensional_size
class dimensional_size_with_path
class directed_action
class directed_angle
class directed_dimensional_location
class direction
class direction_shape_representation
class div_expression
class document
class document_file
class document_product_association
class document_product_equivalence
class document_reference
class document_relationship
class document_representation_type
class document_type
class document_usage_constraint
class document_usage_constraint_assignment
class document_usage_role
class draughting_annotation_occurrence
class draughting_callout
class draughting_callout_relationship
class draughting_elements
class draughting_model
class draughting_model_item_association
class draughting_pre_defined_colour
class draughting_pre_defined_curve_font
class draughting_pre_defined_text_font
class draughting_specification_reference
class draughting_subfigure_representation
class draughting_symbol_representation
class draughting_text_literal_with_delineation
class draughting_title
class drawing_definition
class drawing_revision
class drawing_revision_sequence
class drawing_sheet_layout
class drawing_sheet_revision
class drawing_sheet_revision_usage
class edge
class edge_based_wireframe_model
class edge_based_wireframe_shape_representation
class edge_curve
class edge_loop
class edge_round
class effectivity
class effectivity_assignment
class effectivity_context_assignment
class effectivity_context_role
class effectivity_relationship
class electric_current_measure
class electric_current_measure_with_unit
class electric_current_unit
class element_delivery
class elementary_surface
class ellipse
class environment
class equals_expression
class evaluated_degenerate_pcurve
class event_occurrence
class event_occurrence_assignment
class event_occurrence_context_assignment
class event_occurrence_context_role
class event_occurrence_role
class exclusive_product_concept_feature_category
class executed_action
class exp_function
class expression
class expression_conversion_based_unit
class extension
class external_identification_assignment
class external_source
class externally_defined_character_glyph
class externally_defined_class
class externally_defined_curve_font
class externally_defined_dimension_definition
class externally_defined_feature_definition
class externally_defined_general_property
class externally_defined_hatch_style
class externally_defined_item
class externally_defined_item_relationship
class externally_defined_style
class externally_defined_symbol
class externally_defined_text_font
class externally_defined_tile_style
class extruded_area_solid
class extruded_face_solid
class face
class face_based_surface_model
class face_bound
class face_outer_bound
class face_shape_representation
class face_surface
class faceted_brep
class faceted_brep_shape_representation
class feature_component_definition
class feature_component_relationship
class feature_definition
class feature_in_panel
class feature_pattern
class featured_shape
class fill_area_style
class fill_area_style_colour
class fill_area_style_hatching
class fill_area_style_tile_symbol_with_style
class fill_area_style_tiles
class fillet
class flatness_tolerance
class format_function
class founded_item
ENTITY founded_item #.
class founded_kinematic_path
class fully_constrained_pair
class functionally_defined_transformation
class gear_pair
class gear_pair_range
class gear_pair_value
class general_feature
class general_material_property
class general_property
class general_property_association
class general_property_relationship
class generic_character_glyph_symbol
class generic_expression
class generic_literal
class generic_variable
class geometric_alignment
class geometric_curve_set
class geometric_intersection
class geometric_item_specific_usage
class geometric_representation_context
class geometric_representation_item
class geometric_set
class geometric_tolerance
class geometric_tolerance_relationship
class geometric_tolerance_with_datum_reference
class geometric_tolerance_with_defined_unit
class geometrical_tolerance_callout
class geometrically_bounded_2d_wireframe_representation
class geometrically_bounded_surface_shape_representation
class geometrically_bounded_wireframe_shape_representation
class global_uncertainty_assigned_context
class global_unit_assigned_context
class group
class group_assignment
class group_relationship
class half_space_solid
class hardness_representation
class hidden_element_over_riding_styled_item
class hole_bottom
class hole_in_panel
class homokinetic_pair
class hour_in_day
class hyperbola
class id_attribute
class identification_assignment
class identification_role
class identifier
class inclusion_product_concept_feature
class index_expression
class initial_state
class instanced_feature
class int_literal
class int_numeric_variable
class int_value_function
class integer_defined_function
class interpolated_configuration_sequence
class interpolation_type
class intersection_curve
class interval_expression
class invisibility
class item_defined_transformation
class item_identified_representation_usage
class joggle
class joggle_termination
class kinematic_analysis_consistency
class kinematic_analysis_result
class kinematic_control
class kinematic_frame_background_representation
class kinematic_frame_background_representation_association
class kinematic_frame_based_transformation
class kinematic_ground_representation
class kinematic_joint
class kinematic_link
class kinematic_link_representation
class kinematic_link_representation_association
class kinematic_link_representation_relation
class kinematic_pair
class kinematic_path
class kinematic_property_definition
class kinematic_property_representation_relation
class kinematic_structure
class knot_type
class known_source
class label
class language
class language_assignment
class leader_curve
class leader_directed_callout
class leader_directed_dimension
class leader_terminator
class length_function
class length_measure
class length_measure_with_unit
class length_unit
class light_source
class light_source_ambient
class light_source_directional
class light_source_positional
class light_source_spot
class like_expression
class limit_condition
class limits_and_fits
class line
class line_profile_tolerance
class linear_dimension
class literal_number
class local_time
class location_shape_representation
class locator
class log10_function
class log2_function
class log_function
class loop
class lot_effectivity
class luminous_intensity_measure
class luminous_intensity_measure_with_unit
class luminous_intensity_unit
class make_from_usage_option
class manifold_solid_brep
class manifold_subsurface_shape_representation
class manifold_surface_shape_representation
class mapped_item
class marker_type
class mass_measure
class mass_measure_with_unit
class mass_unit
class material_designation
class material_designation_characterization
class material_property
class material_property_representation
class maximum_function
class measure_qualification
class measure_representation_item
class measure_with_unit
class mechanical_design_geometric_presentation_area
class mechanical_design_geometric_presentation_representation
class mechanism
class mechanism_base_placement
class minimum_function
class minus_expression
class minus_function
class minute_in_hour
class mod_expression
class modified_geometric_tolerance
class modified_pattern
class moments_of_inertia_representation
class month_in_year_number
class motion_link_relationship
class mult_expression
class multi_language_attribute_assignment
class multiple_arity_boolean_expression
class multiple_arity_function_call
class multiple_arity_generic_expression
class multiple_arity_numeric_expression
class name_assignment
class name_attribute
class named_unit
class named_unit_variable
class next_assembly_usage_occurrence
class ngon_closed_profile
class non_manifold_surface_shape_representation
class non_negative_length_measure
class not_expression
class null_style
class numeric_defined_function
class numeric_expression
class numeric_measure
class numeric_variable
class object_role
class odd_function
class offset_curve_2d
class offset_curve_3d
class offset_surface
class one_direction_repeat_factor
class open_path_profile
class open_shell
class or_expression
class ordinate_dimension
class organization
class organization_assignment
class organization_relationship
class organization_role
class organizational_address
class organizational_project
class organizational_project_assignment
class organizational_project_relationship
class organizational_project_role
class oriented_closed_shell
class oriented_edge
class oriented_face
class oriented_open_shell
class oriented_path
class oriented_surface
class outer_boundary_curve
class over_riding_styled_item
class package_product_concept_feature
class pair_actuator
class pair_value
class parabola
class parallel_offset
class parallelism_tolerance
class parameter_value
class parametric_representation_context
class partial_circular_profile
class path
class path_feature_component
class path_shape_representation
class pattern_offset_membership
class pattern_omit_membership
class pcurve
class perpendicular_to
class perpendicularity_tolerance
class person
class person_and_organization
class person_and_organization_address
class person_and_organization_assignment
class person_and_organization_role
class personal_address
class physically_modelled_product_definition
class placed_datum_target_feature
class placed_feature
class placement
class planar_box
class planar_curve_pair
class planar_curve_pair_range
class planar_extent
class planar_pair
class planar_pair_range
class planar_pair_value
class planar_shape_representation
class plane
class plane_angle_measure
class plane_angle_measure_with_unit
class plane_angle_unit
class plus_expression
class plus_minus_tolerance
class pocket
class pocket_bottom
class point
class point_on_curve
class point_on_planar_curve_pair
class point_on_planar_curve_pair_range
class point_on_planar_curve_pair_value
class point_on_surface
class point_on_surface_pair
class point_on_surface_pair_range
class point_on_surface_pair_value
class point_placement_shape_representation
class point_replica
class point_style
class poly_loop
class polyline
class position_tolerance
class positive_length_measure
class positive_plane_angle_measure
class positive_ratio_measure
class power_expression
class pre_defined_colour
class pre_defined_curve_font
class pre_defined_dimension_symbol
class pre_defined_geometrical_tolerance_symbol
class pre_defined_item
class pre_defined_marker
class pre_defined_point_marker_symbol
class pre_defined_presentation_style
class pre_defined_surface_condition_symbol
class pre_defined_symbol
class pre_defined_terminator_symbol
class pre_defined_text_font
class precision_qualifier
class preferred_surface_curve_representation
class presentable_text
class presentation_area
class presentation_layer_assignment
class presentation_representation
class presentation_set
class presentation_size
class presentation_style_assignment
class presentation_style_by_context
class presentation_view
class presented_item
class presented_item_representation
class prismatic_pair
class prismatic_pair_range
class prismatic_pair_value
class process_operation
class process_plan
class process_product_association
class process_property_association
class product
class product_category
class product_category_relationship
class product_class
class product_concept
class product_concept_context
class product_concept_feature
class product_concept_feature_association
class product_concept_feature_category
class product_concept_feature_category_usage
class product_concept_relationship
class product_context
class product_definition
class product_definition_context
class product_definition_context_association
class product_definition_context_role
class product_definition_effectivity
class product_definition_formation
class product_definition_formation_relationship
class product_definition_formation_with_specified_source
class product_definition_occurrence_relationship
class product_definition_process
class product_definition_relationship
class product_definition_resource
class product_definition_shape
class product_definition_substitute
class product_definition_usage
class product_definition_with_associated_documents
class product_identification
class product_or_presentation_space
class product_process_plan
class product_related_product_category
class product_specification
class projected_zone_definition
class projection_curve
class projection_directed_callout
class promissory_usage_occurrence
class property_definition
class property_definition_relationship
class property_definition_representation
class property_process
class qualified_representation_item
class qualitative_uncertainty
class quantified_assembly_component_usage
class quasi_uniform_curve
class quasi_uniform_surface
class rack_and_pinion_pair
class rack_and_pinion_pair_range
class rack_and_pinion_pair_value
class radius_dimension
class ratio_measure
class ratio_measure_with_unit
class ratio_unit
class rational_b_spline_curve
class rational_b_spline_surface
class real_defined_function
class real_literal
class real_numeric_variable
class rectangular_closed_profile
class rectangular_composite_surface
class rectangular_pattern
class rectangular_trimmed_surface
class referenced_modified_datum
class relative_event_occurrence
class rep_item_group
class reparametrised_composite_curve_segment
class replicate_feature
class representation
class representation_context
class representation_item
class representation_map
class representation_relationship
class representation_relationship_with_transformation
class requirement_for_action_resource
class resource_property
class resource_property_representation
class resource_requirement_type
class resulting_path
class retention
class revolute_pair
class revolute_pair_range
class revolute_pair_value
class revolved_area_solid
class revolved_face_solid
class rib
class right_angular_wedge
class right_circular_cone
class right_circular_cylinder
class role_association
class rolling_curve_pair
class rolling_curve_pair_value
class rolling_surface_pair
class rolling_surface_pair_value
class rotation_about_direction
class round_hole
class rounded_u_profile
class roundness_tolerance
class ruled_surface_swept_area_solid
class runout_zone_definition
class runout_zone_orientation
class runout_zone_orientation_reference_direction
class screw_pair
class screw_pair_range
class screw_pair_value
class seam_curve
class seam_edge
class second_in_minute
class security_classification
class security_classification_assignment
class security_classification_level
class serial_numbered_effectivity
class shading_curve_method
class shading_surface_method
class shape_aspect
class shape_aspect_associativity
class shape_aspect_deriving_relationship
class shape_aspect_relationship
class shape_aspect_transition
class shape_defining_relationship
class shape_definition_representation
class shape_dimension_representation
class shape_representation
class shape_representation_relationship
class shape_representation_with_parameters
class shell_based_surface_model
class si_prefix
class si_unit
class si_unit_name
class simple_boolean_expression
class simple_generic_expression
class simple_numeric_expression
class simple_pair_range
class simple_string_expression
class sin_function
class slash_expression
class sliding_curve_pair
class sliding_curve_pair_value
class sliding_surface_pair
class sliding_surface_pair_value
class slot
class slot_end
class solid_angle_measure
class solid_angle_measure_with_unit
class solid_angle_unit
class solid_model
class solid_replica
class source
class specified_higher_usage_occurrence
class sphere
class spherical_pair
class spherical_pair_range
class spherical_pair_value
class spherical_surface
class sql_mappable_defined_function
class square_root_function
class square_u_profile
class standard_uncertainty
class straightness_tolerance
class string_defined_function
class string_expression
class string_literal
class string_variable
class structured_dimension_callout
class styled_item
class subedge
class subface
class substring_expression
class surface
class surface_condition_callout
class surface_curve
class surface_curve_swept_area_solid
class surface_of_linear_extrusion
class surface_of_revolution
class surface_pair
class surface_pair_range
class surface_patch
class surface_profile_tolerance
class surface_rendering_properties
class surface_replica
class surface_side
class surface_side_style
class surface_style_boundary
class surface_style_control_grid
class surface_style_fill_area
class surface_style_parameter_line
class surface_style_reflectance_ambient
class surface_style_reflectance_ambient_diffuse
class surface_style_reflectance_ambient_diffuse_specular
class surface_style_rendering
class surface_style_rendering_with_properties
class surface_style_segmentation_curve
class surface_style_silhouette
class surface_style_transparent
class surface_style_usage
class surface_texture_representation
class surface_tolerance_deviation
class surface_tolerance_parameter
class swept_area_solid
class swept_disk_solid
class swept_face_solid
class swept_surface
class symbol_colour
class symbol_representation
class symbol_representation_map
class symbol_style
class symbol_target
class symmetric_shape_aspect
class symmetry_tolerance
class tactile_appearance_representation
class tan_function
class tangent
class taper
class tee_profile
class terminator_symbol
class text
class text_alignment
class text_delineation
class text_literal
class text_literal_with_associated_curves
class text_literal_with_blanking_box
class text_literal_with_delineation
class text_literal_with_extent
class text_path
class text_string_representation
class text_style
class text_style_for_defined_font
class text_style_with_box_characteristics
class text_style_with_mirror
class text_style_with_spacing
class thermodynamic_temperature_measure
class thermodynamic_temperature_measure_with_unit
class thermodynamic_temperature_unit
class thread
class time_interval
class time_interval_assignment
class time_interval_based_effectivity
class time_interval_role
class time_interval_with_bounds
class time_measure
class time_measure_with_unit
class time_unit
class tolerance_value
class tolerance_zone
class tolerance_zone_definition
class tolerance_zone_form
class topological_representation_item
class toroidal_surface
class torus
class total_runout_tolerance
class transition_code
class transition_feature
class trimmed_curve
class trimming_preference
class two_direction_repeat_factor
class type_qualifier
class u_direction_count
class unary_boolean_expression
class unary_function_call
class unary_generic_expression
class unary_numeric_expression
class uncertainty_assigned_representation
class uncertainty_measure_with_unit
class uncertainty_qualifier
class unconstrained_pair
class unconstrained_pair_value
class uniform_curve
class uniform_surface
class universal_pair
class universal_pair_range
class universal_pair_value
class unlimited_range
class v_direction_count
class value_function
class value_range
class value_representation_item
class variable
class variable_semantics
class vector
class vector_style
class vee_profile
class versioned_action_request
class versioned_action_request_relationship
class vertex
class vertex_loop
class vertex_point
class view_volume
class visual_appearance_representation
class volume_measure
class volume_measure_with_unit
class volume_unit
class xor_expression
class year_number
class ypr_enumeration
Functions
def acyclic (arg1, arg2)
FUNCTION acyclic #.
def acyclic_composite_text (start_composite, child_text)
FUNCTION acyclic_composite_text #.
def acyclic_curve_replica (rep, parent)
FUNCTION acyclic_curve_replica #.
def acyclic_mapped_item_usage (rep)
FUNCTION acyclic_mapped_item_usage #.
def acyclic_mapped_representation (parent_set, children_set)
FUNCTION acyclic_mapped_representation #.
def acyclic_point_replica (rep, parent)
FUNCTION acyclic_point_replica #.
def acyclic_product_category_relationship (relation, children)
FUNCTION acyclic_product_category_relationship #.
def acyclic_product_definition_relationship (relation, relatives, specific_relation)
FUNCTION acyclic_product_definition_relationship #.
def acyclic_solid_replica (rep, parent)
FUNCTION acyclic_solid_replica #.
def acyclic_surface_replica (rep, parent)
FUNCTION acyclic_surface_replica #.
def advanced_face_properties (testface)
FUNCTION advanced_face_properties #.
def aspect_ratio (p)
FUNCTION aspect_ratio #.
def assembly_shape_is_defined (assy)
FUNCTION assembly_shape_is_defined #.
def associated_surface (arg)
FUNCTION associated_surface #.
def bag_to_set (the_bag)
FUNCTION bag_to_set #.
def base_axis (dim, axis1, axis2, axis3)
FUNCTION base_axis #.
def boolean_choose (b, choice1, choice2)
FUNCTION boolean_choose #.
def build_2axes (ref_direction)
FUNCTION build_2axes #.
def build_axes (axis, ref_direction)
FUNCTION build_axes #.
def check_associative_shape_aspects (sdr)
def check_text_alignment (ct)
FUNCTION check_text_alignment #.
def check_text_font (ct)
FUNCTION check_text_font #.
def closed_shell_reversed (a_shell)
FUNCTION closed_shell_reversed #.
def conditional_reverse (p, an_item)
FUNCTION conditional_reverse #.
def constraints_composite_curve_on_surface (c)
FUNCTION constraints_composite_curve_on_surface #.
def constraints_geometry_shell_based_surface_model (m)
FUNCTION constraints_geometry_shell_based_surface_model #.
def constraints_param_b_spline (degree, up_knots, up_cp, knot_mult, knots)
FUNCTION constraints_param_b_spline #.
def constraints_rectangular_composite_surface (s)
FUNCTION constraints_rectangular_composite_surface #.
def control_characters_free (s)
FUNCTION control_characters_free #.
def convert_plane_angle_for_pair_from_radian (pair, angle_expr)
FUNCTION convert_plane_angle_for_pair_from_radian #.
def convert_spatial_to_ypr_rotation (pair, rotation)
FUNCTION convert_spatial_to_ypr_rotation #.
def coordinated_pair_link_representation (link, pair_placement)
FUNCTION coordinated_pair_link_representation #.
def cross_product (arg1, arg2)
FUNCTION cross_product #.
def curve_weights_positive (b)
FUNCTION curve_weights_positive #.
def default_tolerance_table_cell_wr2 (agg)
FUNCTION default_tolerance_table_cell_wr2 #.
def default_tolerance_table_cell_wr3 (agg)
FUNCTION default_tolerance_table_cell_wr3 #.
def default_tolerance_table_cell_wr4 (agg)
FUNCTION default_tolerance_table_cell_wr4 #.
def default_tolerance_table_cell_wr5 (agg)
FUNCTION default_tolerance_table_cell_wr5 #.
def derive_dimensional_exponents (x)
FUNCTION derive_dimensional_exponents #.
def dimension_of (item)
FUNCTION dimension_of #.
def dimensions_for_si_unit (n)
FUNCTION dimensions_for_si_unit #.
def dot_product (arg1, arg2)
FUNCTION dot_product #.
def edge_reversed (an_edge)
FUNCTION edge_reversed #.
def face_bound_reversed (a_face_bound)
FUNCTION face_bound_reversed #.
def face_reversed (a_face)
FUNCTION face_reversed #.
def first_proj_axis (z_axis, arg)
FUNCTION first_proj_axis #.
def frame_associated_to_background (frame, background)
FUNCTION frame_associated_to_background #.
def gbsf_check_curve (cv)
FUNCTION gbsf_check_curve #.
def gbsf_check_point (pnt)
FUNCTION gbsf_check_point #.
def gbsf_check_surface (sf)
FUNCTION gbsf_check_surface #.
def get_basis_surface (c)
FUNCTION get_basis_surface #.
def get_description_value (obj)
FUNCTION get_description_value #.
def get_diameter_for_round_hole (rh)
FUNCTION get_diameter_for_round_hole #.
def get_id_value (obj)
FUNCTION get_id_value #.
def get_multi_language (x)
FUNCTION get_multi_language #.
def get_name_value (obj)
FUNCTION get_name_value #.
def get_property_definition_representations (c_def_instance)
FUNCTION get_property_definition_representations #.
def get_role (obj)
FUNCTION get_role #.
def get_round_holes_for_composite_hole (sar_instance_set)
FUNCTION get_round_holes_for_composite_hole #.
def get_shape_aspect_property_definition_representations (s_a_instance)
FUNCTION get_shape_aspect_property_definition_representations #.
def get_shape_aspects (c_def_instance)
FUNCTION get_shape_aspects #.
def is_acyclic (arg)
FUNCTION is_acyclic #.
def is_int_expr (arg)
FUNCTION is_int_expr #.
def is_sql_mappable (arg)
FUNCTION is_sql_mappable #.
def item_correlation (items, c_items)
FUNCTION item_correlation #.
def item_in_context (item, cntxt)
FUNCTION item_in_context #.
def leap_year (year)
FUNCTION leap_year #.
def list_face_loops (f)
FUNCTION list_face_loops #.
def list_of_topology_reversed (a_list)
FUNCTION list_of_topology_reversed #.
def list_to_array (lis, low, u)
FUNCTION list_to_array #.
def list_to_set (l)
FUNCTION list_to_set #.
def make_array_of_array (lis, low1, u1, low2, u2)
FUNCTION make_array_of_array #.
def mixed_loop_type_set (l)
FUNCTION mixed_loop_type_set #.
def msb_shells (brep)
FUNCTION msb_shells #.
def msf_curve_check (cv)
FUNCTION msf_curve_check #.
def msf_surface_check (surf)
FUNCTION msf_surface_check #.
def nmsf_curve_check (cv)
FUNCTION nmsf_curve_check #.
def nmsf_surface_check (surf)
FUNCTION nmsf_surface_check #.
def normalise (arg)
FUNCTION normalise #.
def open_shell_reversed (a_shell)
FUNCTION open_shell_reversed #.
def orthogonal_complement (vec)
FUNCTION orthogonal_complement #.
def path_head_to_tail (a_path)
FUNCTION path_head_to_tail #.
def path_reversed (a_path)
FUNCTION path_reversed #.
def plane_angle_for_pair_in_radian (pair, angle)
FUNCTION plane_angle_for_pair_in_radian #.
def representation_of_link (link)
FUNCTION representation_of_link #.
def representations_mapped_into (rep)
FUNCTION representations_mapped_into #.
def scalar_times_vector (scalar, vec)
FUNCTION scalar_times_vector #.
def second_proj_axis (z_axis, x_axis, arg)
FUNCTION second_proj_axis #.
def set_of_topology_reversed (a_set)
FUNCTION set_of_topology_reversed #.
def shell_reversed (a_shell)
FUNCTION shell_reversed #.
def suitably_based_mechanism (mbp, mech)
FUNCTION suitably_based_mechanism #.
def surface_condition_correlation (pd, rep)
FUNCTION surface_condition_correlation #.
def surface_weights_positive (b)
FUNCTION surface_weights_positive #.
def topology_reversed (an_item)
FUNCTION topology_reversed #.
def type_check_function (the_type, sub_names, criterion)
FUNCTION type_check_function #.
def unique_link_usage (link)
FUNCTION unique_link_usage #.
def using_items (item, checked_items)
FUNCTION using_items #.
def using_representations (item)
FUNCTION using_representations #.
def valid_basis_curve_in_2d_wireframe (crv)
FUNCTION valid_basis_curve_in_2d_wireframe #.
def valid_calendar_date (date)
FUNCTION valid_calendar_date #.
def valid_geometrically_bounded_wf_curve (crv)
FUNCTION valid_geometrically_bounded_wf_curve #.
def valid_geometrically_bounded_wf_point (pnt)
FUNCTION valid_geometrically_bounded_wf_point #.
def valid_measure_value (m)
FUNCTION valid_measure_value #.
def valid_time (time)
FUNCTION valid_time #.
def valid_units (m)
FUNCTION valid_units #.
def valid_wireframe_edge_curve (crv)
FUNCTION valid_wireframe_edge_curve #.
def valid_wireframe_vertex_point (pnt)
FUNCTION valid_wireframe_vertex_point #.
def value_range_aggregate_rep_item (agg)
FUNCTION value_range_aggregate_rep_item #.
def value_range_wr1 (agg)
FUNCTION value_range_wr1 #.
def value_range_wr2 (agg)
FUNCTION value_range_wr2 #.
def value_range_wr3 (agg)
FUNCTION value_range_wr3 #.
def vector_difference (arg1, arg2)
FUNCTION vector_difference #.
def ypr_index (ypr)
FUNCTION ypr_index #.
Variables
action_item
action_request_item
annotation_plane_element
annotation_symbol_occurrence_item
annotation_text_occurrence_item
application_protocol_definition_required = Rule()
RULE application_protocol_definition_required #.
approval_item
approval_person_organization_requires_date_time = Rule()
RULE approval_person_organization_requires_date_time #.
approval_requires_approval_assignment = Rule()
RULE approval_requires_approval_assignment #.
area_or_view
attribute_language_item
attribute_type
axis2_placement
boolean_operand
box_characteristic_select
category_usage_item
certification_item
character_spacing_select
character_style_select
characterized_action_definition
characterized_definition
characterized_material_property
characterized_product_definition
characterized_resource_definition
class_usage_effectivity_context_item
classification_item
compatible_dimension = Rule()
RULE compatible_dimension #.
complex_product_requires_product_definition = Rule()
RULE complex_product_requires_product_definition #.
compound_features_of_equal_type = Rule()
RULE compound_features_of_equal_type #.
compound_item_definition
configuration_design_item
configured_effectivity_context_item
configured_effectivity_item
consistent_uncertainty = Rule()
RULE consistent_uncertainty #.
contract_item
coordinated_assembly_and_shape = Rule()
RULE coordinated_assembly_and_shape #.
csg_primitive
csg_select
curve_font_or_scaled_curve_font_select
curve_font_usage = Rule()
RULE curve_font_usage #.
curve_on_surface
curve_or_render
curve_style_font_select
date_and_time_item
date_item
date_time_or_event_occurrence
date_time_select
defined_glyph_select
defined_symbol_select
dependent_instantiable_action_directive = Rule()
RULE dependent_instantiable_action_directive #.
dependent_instantiable_action_resource_type = Rule()
RULE dependent_instantiable_action_resource_type #.
dependent_instantiable_approval_role = Rule()
RULE dependent_instantiable_approval_role #.
dependent_instantiable_attribute_value_role = Rule()
RULE dependent_instantiable_attribute_value_role #.
dependent_instantiable_classification_role = Rule()
RULE dependent_instantiable_classification_role #.
dependent_instantiable_colour_rgb = Rule()
RULE dependent_instantiable_colour_rgb #.
dependent_instantiable_contract_type = Rule()
RULE dependent_instantiable_contract_type #.
dependent_instantiable_curve_style = Rule()
RULE dependent_instantiable_curve_style #.
dependent_instantiable_date = Rule()
RULE dependent_instantiable_date #.
dependent_instantiable_date_and_time = Rule()
RULE dependent_instantiable_date_and_time #.
dependent_instantiable_date_role = Rule()
RULE dependent_instantiable_date_role #.
dependent_instantiable_date_time_role = Rule()
RULE dependent_instantiable_date_time_role #.
dependent_instantiable_derived_unit = Rule()
RULE dependent_instantiable_derived_unit #.
dependent_instantiable_dimensional_size = Rule()
RULE dependent_instantiable_dimensional_size #.
dependent_instantiable_document_usage_role = Rule()
RULE dependent_instantiable_document_usage_role #.
dependent_instantiable_effectivity_context_role = Rule()
RULE dependent_instantiable_effectivity_context_role #.
dependent_instantiable_event_occurrence_role = Rule()
RULE dependent_instantiable_event_occurrence_role #.
dependent_instantiable_externally_defined_symbol = Rule()
RULE dependent_instantiable_externally_defined_symbol #.
dependent_instantiable_fill_area_style = Rule()
RULE dependent_instantiable_fill_area_style #.
dependent_instantiable_fill_area_style_colour = Rule()
RULE dependent_instantiable_fill_area_style_colour #.
dependent_instantiable_identification_role = Rule()
RULE dependent_instantiable_identification_role #.
dependent_instantiable_measure_with_unit = Rule()
RULE dependent_instantiable_measure_with_unit #.
dependent_instantiable_named_unit = Rule()
RULE dependent_instantiable_named_unit #.
dependent_instantiable_object_role = Rule()
RULE dependent_instantiable_object_role #.
dependent_instantiable_organization_role = Rule()
RULE dependent_instantiable_organization_role #.
dependent_instantiable_organizational_project_role = Rule()
RULE dependent_instantiable_organizational_project_role #.
dependent_instantiable_person_and_organization_role = Rule()
RULE dependent_instantiable_person_and_organization_role #.
dependent_instantiable_pre_defined_colour = Rule()
RULE dependent_instantiable_pre_defined_colour #.
dependent_instantiable_pre_defined_symbol = Rule()
RULE dependent_instantiable_pre_defined_symbol #.
dependent_instantiable_precision_qualifier = Rule()
RULE dependent_instantiable_precision_qualifier #.
dependent_instantiable_presentation_style_by_context = Rule()
RULE dependent_instantiable_presentation_style_by_context #.
dependent_instantiable_product_definition_context_role = Rule()
RULE dependent_instantiable_product_definition_context_role #.
dependent_instantiable_resource_requirement_type = Rule()
RULE dependent_instantiable_resource_requirement_type #.
dependent_instantiable_retention = Rule()
RULE dependent_instantiable_retention #.
dependent_instantiable_standard_uncertainty = Rule()
RULE dependent_instantiable_standard_uncertainty #.
dependent_instantiable_symbol_colour = Rule()
RULE dependent_instantiable_symbol_colour #.
dependent_instantiable_text_style = Rule()
RULE dependent_instantiable_text_style #.
dependent_instantiable_text_style_for_defined_font = Rule()
RULE dependent_instantiable_text_style_for_defined_font #.
dependent_instantiable_time_interval_role = Rule()
RULE dependent_instantiable_time_interval_role #.
dependent_instantiable_tolerance_value = Rule()
RULE dependent_instantiable_tolerance_value #.
dependent_instantiable_type_qualifier = Rule()
RULE dependent_instantiable_type_qualifier #.
dependent_instantiable_uncertainty_qualifier = Rule()
RULE dependent_instantiable_uncertainty_qualifier #.
derived_property_select
description_attribute_select
design_constraint_requires_product_definition = Rule()
RULE design_constraint_requires_product_definition #.
dimensional_characteristic
dimensionality_is_two_or_three = Rule()
RULE dimensionality_is_two_or_three #.
direction_count_select
document_reference_item
draughting_callout_element
draughting_model_item_association_select
draughting_subfigure_representation_layers = Rule()
RULE draughting_subfigure_representation_layers #.
draughting_titled_item
drawing_sheet_annotation_layers = Rule()
RULE drawing_sheet_annotation_layers #.
drawing_sheet_layout_usage = Rule()
RULE drawing_sheet_layout_usage #.
drawing_view_annotation_layers = Rule()
RULE drawing_view_annotation_layers #.
effectivity_item
event_occurrence_item
event_occurrence_requires_event_occurrence_assignment = Rule()
RULE event_occurrence_requires_event_occurrence_assignment #.
executed_action_requires_action_status = Rule()
RULE executed_action_requires_action_status #.
external_identification_item
externally_defined_class_with_known_source_requirement = Rule()
RULE externally_defined_class_with_known_source_requirement #.
fill_area_style_tile_shape_select
fill_area_style_tile_symbol_constraint = Rule()
RULE fill_area_style_tile_symbol_constraint #.
fill_style_select
font_select
founded_item_select
full_model_change_completeness_for_action_property = Rule()
RULE full_model_change_completeness_for_action_property #.
full_model_change_completeness_for_property_definition = Rule()
RULE full_model_change_completeness_for_property_definition #.
geometric_set_select
global_length_and_angle_units_2d_or_3d = Rule()
RULE global_length_and_angle_units_2d_or_3d #.
group_item
id_attribute_select
identification_item
invisibility_context
invisible_item
kinematic_analysis_definition
kinematic_frame_background
kinematic_result
language_item
layered_item
list_of_reversible_topology_item = LIST(0,None,'reversible_topology_item', scope = schema_scope)
list_representation_item = LIST(1,None,'representation_item', scope = schema_scope)
marker_select
measure_value
motion_parameter_measure
multi_language_attribute_item
name_attribute_select
name_item
organization_item
organizational_project_item
pcurve_or_surface
person_and_organization_item
person_organization_select
person_requires_person_and_organization = Rule()
RULE person_requires_person_and_organization #.
physical_instance_requires_product_definition = Rule()
RULE physical_instance_requires_product_definition #.
plane_or_planar_box
plib_class_reference_requires_version = Rule()
RULE plib_class_reference_requires_version #.
plib_property_reference_requires_name_scope = Rule()
RULE plib_property_reference_requires_name_scope #.
plib_property_reference_requires_version = Rule()
RULE plib_property_reference_requires_version #.
presentation_layer_assignment_constraint_2d_or_3d = Rule()
RULE presentation_layer_assignment_constraint_2d_or_3d #.
presentation_representation_select
presentation_size_assignment_select
presentation_style_select
presentation_view_presented_once = Rule()
RULE presentation_view_presented_once #.
presented_item_select
product_concept_feature_requires_category = Rule()
RULE product_concept_feature_requires_category #.
product_definition_replacement_requires_effectivity_assignment = Rule()
RULE product_definition_replacement_requires_effectivity_assignment #.
product_or_formation_or_definition
product_requires_category = Rule()
RULE product_requires_category #.
product_requires_id_owner = Rule()
RULE product_requires_id_owner #.
product_requires_version = Rule()
RULE product_requires_version #.
property_or_shape_select
rendering_properties_select
represented_definition
restrict_action_resource_requirement_for_process_operation = Rule()
RULE restrict_action_resource_requirement_for_process_operation #.
restrict_alternative_definition = Rule()
RULE restrict_alternative_definition #.
restrict_applied_action_assignment = Rule()
RULE restrict_applied_action_assignment #.
restrict_applied_action_request_assignment = Rule()
RULE restrict_applied_action_request_assignment #.
restrict_applied_classification_assignment_role = Rule()
RULE restrict_applied_classification_assignment_role #.
restrict_applied_event_occurrence_assignment = Rule()
RULE restrict_applied_event_occurrence_assignment #.
restrict_applied_organizational_project_assignment = Rule()
RULE restrict_applied_organizational_project_assignment #.
restrict_approval = Rule()
RULE restrict_approval #.
restrict_camera_image_in_view = Rule()
RULE restrict_camera_image_in_view #.
restrict_centre_of_mass_representation = Rule()
RULE restrict_centre_of_mass_representation #.
restrict_class_system_assignment_for_approval_status = Rule()
RULE restrict_class_system_assignment_for_approval_status #.
restrict_class_system_assignment_for_class = Rule()
RULE restrict_class_system_assignment_for_class #.
restrict_class_system_assignment_for_descriptive_representation_item = Rule()
RULE restrict_class_system_assignment_for_descriptive_representation_item #.
restrict_class_system_assignment_for_document_type = Rule()
RULE restrict_class_system_assignment_for_document_type #.
restrict_class_system_assignment_for_security_classification_level = Rule()
RULE restrict_class_system_assignment_for_security_classification_level #.
restrict_concept_feature_operator = Rule()
RULE restrict_concept_feature_operator #.
restrict_configuration_design_for_product_class = Rule()
RULE restrict_configuration_design_for_product_class #.
restrict_default_settings = Rule()
RULE restrict_default_settings #.
restrict_default_thickness = Rule()
RULE restrict_default_thickness #.
restrict_drawing = Rule()
RULE restrict_drawing #.
restrict_effectivity_assignment_for_class_category_usage = Rule()
RULE restrict_effectivity_assignment_for_class_category_usage #.
restrict_effectivity_for_effectivity_relationship = Rule()
RULE restrict_effectivity_for_effectivity_relationship #.
restrict_effectivity_usage = Rule()
RULE restrict_effectivity_usage #.
restrict_externally_defined_item_relationship = Rule()
RULE restrict_externally_defined_item_relationship #.
restrict_group_relationship_for_general_classification_hierarchy = Rule()
RULE restrict_group_relationship_for_general_classification_hierarchy #.
restrict_group_relationship_for_specification_category = Rule()
RULE restrict_group_relationship_for_specification_category #.
restrict_multi_language_for_action = Rule()
RULE restrict_multi_language_for_action #.
restrict_multi_language_for_action_directive = Rule()
RULE restrict_multi_language_for_action_directive #.
restrict_multi_language_for_action_method = Rule()
RULE restrict_multi_language_for_action_method #.
restrict_multi_language_for_action_property = Rule()
RULE restrict_multi_language_for_action_property #.
restrict_multi_language_for_action_relationship = Rule()
RULE restrict_multi_language_for_action_relationship #.
restrict_multi_language_for_alternate_product_relationship = Rule()
RULE restrict_multi_language_for_alternate_product_relationship #.
restrict_multi_language_for_application_context = Rule()
RULE restrict_multi_language_for_application_context #.
restrict_multi_language_for_approval_relationship = Rule()
RULE restrict_multi_language_for_approval_relationship #.
restrict_multi_language_for_assembly_component_usage_substitute = Rule()
RULE restrict_multi_language_for_assembly_component_usage_substitute #.
restrict_multi_language_for_certification = Rule()
RULE restrict_multi_language_for_certification #.
restrict_multi_language_for_configuration_design = Rule()
RULE restrict_multi_language_for_configuration_design #.
restrict_multi_language_for_configuration_item = Rule()
RULE restrict_multi_language_for_configuration_item #.
restrict_multi_language_for_contract = Rule()
RULE restrict_multi_language_for_contract #.
restrict_multi_language_for_data_environment = Rule()
RULE restrict_multi_language_for_data_environment #.
restrict_multi_language_for_date_role = Rule()
RULE restrict_multi_language_for_date_role #.
restrict_multi_language_for_date_time_role = Rule()
RULE restrict_multi_language_for_date_time_role #.
restrict_multi_language_for_descriptive_representation_item = Rule()
RULE restrict_multi_language_for_descriptive_representation_item #.
restrict_multi_language_for_document_relationship = Rule()
RULE restrict_multi_language_for_document_relationship #.
restrict_multi_language_for_draughting_title = Rule()
RULE restrict_multi_language_for_draughting_title #.
restrict_multi_language_for_effectivity = Rule()
RULE restrict_multi_language_for_effectivity #.
restrict_multi_language_for_effectivity_relationship = Rule()
RULE restrict_multi_language_for_effectivity_relationship #.
restrict_multi_language_for_event_occurrence = Rule()
RULE restrict_multi_language_for_event_occurrence #.
restrict_multi_language_for_external_source = Rule()
RULE restrict_multi_language_for_external_source #.
restrict_multi_language_for_general_property = Rule()
RULE restrict_multi_language_for_general_property #.
restrict_multi_language_for_general_property_relationship = Rule()
RULE restrict_multi_language_for_general_property_relationship #.
restrict_multi_language_for_geometric_representation_item = Rule()
RULE restrict_multi_language_for_geometric_representation_item #.
restrict_multi_language_for_geometric_tolerance = Rule()
RULE restrict_multi_language_for_geometric_tolerance #.
restrict_multi_language_for_group = Rule()
RULE restrict_multi_language_for_group #.
restrict_multi_language_for_group_relationship = Rule()
RULE restrict_multi_language_for_group_relationship #.
restrict_multi_language_for_identification_role = Rule()
RULE restrict_multi_language_for_identification_role #.
restrict_multi_language_for_kinematic_pair = Rule()
RULE restrict_multi_language_for_kinematic_pair #.
restrict_multi_language_for_mapped_item = Rule()
RULE restrict_multi_language_for_mapped_item #.
restrict_multi_language_for_name_assignment = Rule()
RULE restrict_multi_language_for_name_assignment #.
restrict_multi_language_for_organization_relationship = Rule()
RULE restrict_multi_language_for_organization_relationship #.
restrict_multi_language_for_organization_role = Rule()
RULE restrict_multi_language_for_organization_role #.
restrict_multi_language_for_organizational_project = Rule()
RULE restrict_multi_language_for_organizational_project #.
restrict_multi_language_for_organizational_project_relationship = Rule()
RULE restrict_multi_language_for_organizational_project_relationship #.
restrict_multi_language_for_pair_actuator = Rule()
RULE restrict_multi_language_for_pair_actuator #.
restrict_multi_language_for_person_and_organization_role = Rule()
RULE restrict_multi_language_for_person_and_organization_role #.
restrict_multi_language_for_presentation_layer_assignment = Rule()
RULE restrict_multi_language_for_presentation_layer_assignment #.
restrict_multi_language_for_process_product_association = Rule()
RULE restrict_multi_language_for_process_product_association #.
restrict_multi_language_for_product = Rule()
RULE restrict_multi_language_for_product #.
restrict_multi_language_for_product_concept = Rule()
RULE restrict_multi_language_for_product_concept #.
restrict_multi_language_for_product_concept_feature = Rule()
RULE restrict_multi_language_for_product_concept_feature #.
restrict_multi_language_for_product_concept_feature_association = Rule()
RULE restrict_multi_language_for_product_concept_feature_association #.
restrict_multi_language_for_product_concept_relationship = Rule()
RULE restrict_multi_language_for_product_concept_relationship #.
restrict_multi_language_for_product_definition = Rule()
RULE restrict_multi_language_for_product_definition #.
restrict_multi_language_for_product_definition_formation = Rule()
RULE restrict_multi_language_for_product_definition_formation #.
restrict_multi_language_for_product_definition_formation_relationship = Rule()
RULE restrict_multi_language_for_product_definition_formation_relationship #.
restrict_multi_language_for_product_definition_relationship = Rule()
RULE restrict_multi_language_for_product_definition_relationship #.
restrict_multi_language_for_product_definition_substitute = Rule()
RULE restrict_multi_language_for_product_definition_substitute #.
restrict_multi_language_for_product_related_product_category = Rule()
RULE restrict_multi_language_for_product_related_product_category #.
restrict_multi_language_for_property_definition = Rule()
RULE restrict_multi_language_for_property_definition #.
restrict_multi_language_for_property_definition_relationship = Rule()
RULE restrict_multi_language_for_property_definition_relationship #.
restrict_multi_language_for_representation = Rule()
RULE restrict_multi_language_for_representation #.
restrict_multi_language_for_representation_relationship = Rule()
RULE restrict_multi_language_for_representation_relationship #.
restrict_multi_language_for_requirement_for_action_resource = Rule()
RULE restrict_multi_language_for_requirement_for_action_resource #.
restrict_multi_language_for_resource_property = Rule()
RULE restrict_multi_language_for_resource_property #.
restrict_multi_language_for_resource_requirement_type = Rule()
RULE restrict_multi_language_for_resource_requirement_type #.
restrict_multi_language_for_security_classification = Rule()
RULE restrict_multi_language_for_security_classification #.
restrict_multi_language_for_shape_aspect = Rule()
RULE restrict_multi_language_for_shape_aspect #.
restrict_multi_language_for_shape_aspect_relationship = Rule()
RULE restrict_multi_language_for_shape_aspect_relationship #.
restrict_multi_language_for_styled_item = Rule()
RULE restrict_multi_language_for_styled_item #.
restrict_multi_language_for_time_interval_role = Rule()
RULE restrict_multi_language_for_time_interval_role #.
restrict_multi_language_for_topological_representation_item = Rule()
RULE restrict_multi_language_for_topological_representation_item #.
restrict_multi_language_for_uncertainty_measure_with_unit = Rule()
RULE restrict_multi_language_for_uncertainty_measure_with_unit #.
restrict_multi_language_for_uncertainty_qualifier = Rule()
RULE restrict_multi_language_for_uncertainty_qualifier #.
restrict_multi_language_for_versioned_action_request = Rule()
RULE restrict_multi_language_for_versioned_action_request #.
restrict_multi_language_for_versioned_action_request_relationship = Rule()
RULE restrict_multi_language_for_versioned_action_request_relationship #.
restrict_name_assignment_for_kinematic_joint = Rule()
RULE restrict_name_assignment_for_kinematic_joint #.
restrict_name_assignment_for_kinematic_link = Rule()
RULE restrict_name_assignment_for_kinematic_link #.
restrict_name_assignment_for_kinematic_structure = Rule()
RULE restrict_name_assignment_for_kinematic_structure #.
restrict_name_for_known_source = Rule()
RULE restrict_name_for_known_source #.
restrict_part_occurrence = Rule()
RULE restrict_part_occurrence #.
restrict_process_product_association = Rule()
RULE restrict_process_product_association #.
restrict_product_categories_for_tool_part_relationship = Rule()
RULE restrict_product_categories_for_tool_part_relationship #.
restrict_product_category_for_product = Rule()
RULE restrict_product_category_for_product #.
restrict_product_definition_context_for_external_properties = Rule()
RULE restrict_product_definition_context_for_external_properties #.
restrict_product_definition_context_for_product = Rule()
RULE restrict_product_definition_context_for_product #.
restrict_product_definition_for_mating_tree = Rule()
RULE restrict_product_definition_for_mating_tree #.
restrict_product_definition_substitute = Rule()
RULE restrict_product_definition_substitute #.
restrict_product_definitions_for_product_definition_relationship = Rule()
RULE restrict_product_definitions_for_product_definition_relationship #.
restrict_properties_of_document_file = Rule()
RULE restrict_properties_of_document_file #.
restrict_properties_of_document_representation = Rule()
RULE restrict_properties_of_document_representation #.
restrict_representation_for_document_content_property = Rule()
RULE restrict_representation_for_document_content_property #.
restrict_representation_for_document_creation_property = Rule()
RULE restrict_representation_for_document_creation_property #.
restrict_representation_for_document_format_property = Rule()
RULE restrict_representation_for_document_format_property #.
restrict_representation_for_document_properties = Rule()
RULE restrict_representation_for_document_properties #.
restrict_representation_for_document_size_property = Rule()
RULE restrict_representation_for_document_size_property #.
restrict_representation_for_surface_condition = Rule()
RULE restrict_representation_for_surface_condition #.
restrict_representation_item_for_hybrid_geometric_model_3d = Rule()
RULE restrict_representation_item_for_hybrid_geometric_model_3d #.
restrict_treatment_result = Rule()
RULE restrict_treatment_result #.
restrict_version_assignment_for_action = Rule()
RULE restrict_version_assignment_for_action #.
restrict_version_assignment_for_action_directive = Rule()
RULE restrict_version_assignment_for_action_directive #.
restrict_version_assignment_for_action_method = Rule()
RULE restrict_version_assignment_for_action_method #.
restrict_version_assignment_for_applied_identification_assignment = Rule()
RULE restrict_version_assignment_for_applied_identification_assignment #.
restrict_version_assignment_for_class = Rule()
RULE restrict_version_assignment_for_class #.
restrict_version_assignment_for_configuration_item = Rule()
RULE restrict_version_assignment_for_configuration_item #.
restrict_version_assignment_for_document_file = Rule()
RULE restrict_version_assignment_for_document_file #.
restrict_version_assignment_for_draughting_model = Rule()
RULE restrict_version_assignment_for_draughting_model #.
restrict_version_assignment_for_effectivity = Rule()
RULE restrict_version_assignment_for_effectivity #.
restrict_version_assignment_for_general_property = Rule()
RULE restrict_version_assignment_for_general_property #.
restrict_version_assignment_for_mechanical_design_geometric_presentation_representation = Rule()
RULE restrict_version_assignment_for_mechanical_design_geometric_presentation_representation #.
restrict_version_assignment_for_presentation_area = Rule()
RULE restrict_version_assignment_for_presentation_area #.
restrict_version_assignment_for_product_concept = Rule()
RULE restrict_version_assignment_for_product_concept #.
restrict_version_assignment_for_product_concept_feature = Rule()
RULE restrict_version_assignment_for_product_concept_feature #.
restrict_version_assignment_for_shape_representation = Rule()
RULE restrict_version_assignment_for_shape_representation #.
restrict_viewing_plane_usage = Rule()
RULE restrict_viewing_plane_usage #.
restrict_zone_boundary = Rule()
RULE restrict_zone_boundary #.
retention_requires_retention_assignment = Rule()
RULE retention_requires_retention_assignment #.
reversible_topology
reversible_topology_item
rigid_placement
role_select
rotational_range_measure
string schema_name = 'automotive_design'
schema_scope = sys.modules[__name__]
security_classification_item
security_classification_requires_security_classification_assignment = Rule()
RULE security_classification_requires_security_classification_assignment #.
selected_instance_usage_requires_representation = Rule()
RULE selected_instance_usage_requires_representation #.
set_of_reversible_topology_item = SET(0,None,'reversible_topology_item', scope = schema_scope)
set_representation_item = SET(1,None,'representation_item', scope = schema_scope)
shape_definition
sheets_belong_to_one_drawing = Rule()
RULE sheets_belong_to_one_drawing #.
shell
size_select
source_item
spatial_rotation
specified_item
style_context_select
styled_curve = Rule()
RULE styled_curve #.
subtype_exclusiveness_action = Rule()
RULE subtype_exclusiveness_action #.
subtype_exclusiveness_characterized_object = Rule()
RULE subtype_exclusiveness_characterized_object #.
subtype_exclusiveness_classification_assignment = Rule()
RULE subtype_exclusiveness_classification_assignment #.
subtype_exclusiveness_colour = Rule()
RULE subtype_exclusiveness_colour #.
subtype_exclusiveness_compound_representation_item = Rule()
RULE subtype_exclusiveness_compound_representation_item #.
subtype_exclusiveness_document_reference = Rule()
RULE subtype_exclusiveness_document_reference #.
subtype_exclusiveness_effectivity = Rule()
RULE subtype_exclusiveness_effectivity #.
subtype_exclusiveness_effectivity_assignment = Rule()
RULE subtype_exclusiveness_effectivity_assignment #.
subtype_exclusiveness_effectivity_context_assignment = Rule()
RULE subtype_exclusiveness_effectivity_context_assignment #.
subtype_exclusiveness_externally_defined_item = Rule()
RULE subtype_exclusiveness_externally_defined_item #.
subtype_exclusiveness_feature_component_relationship = Rule()
RULE subtype_exclusiveness_feature_component_relationship #.
subtype_exclusiveness_feature_definition = Rule()
RULE subtype_exclusiveness_feature_definition #.
subtype_exclusiveness_founded_item = Rule()
RULE subtype_exclusiveness_founded_item #.
subtype_exclusiveness_geometric_tolerance = Rule()
RULE subtype_exclusiveness_geometric_tolerance #.
subtype_exclusiveness_group = Rule()
RULE subtype_exclusiveness_group #.
subtype_exclusiveness_group_assignment = Rule()
RULE subtype_exclusiveness_group_assignment #.
subtype_exclusiveness_identification_assignment = Rule()
RULE subtype_exclusiveness_identification_assignment #.
subtype_exclusiveness_mapped_item = Rule()
RULE subtype_exclusiveness_mapped_item #.
subtype_exclusiveness_pre_defined_item = Rule()
RULE subtype_exclusiveness_pre_defined_item #.
subtype_exclusiveness_pre_defined_symbol = Rule()
RULE subtype_exclusiveness_pre_defined_symbol #.
subtype_exclusiveness_presentation_area = Rule()
RULE subtype_exclusiveness_presentation_area #.
subtype_exclusiveness_presentation_representation = Rule()
RULE subtype_exclusiveness_presentation_representation #.
subtype_exclusiveness_property_definition = Rule()
RULE subtype_exclusiveness_property_definition #.
subtype_exclusiveness_property_definition_representation = Rule()
RULE subtype_exclusiveness_property_definition_representation #.
subtype_exclusiveness_replicate_feature = Rule()
RULE subtype_exclusiveness_replicate_feature #.
subtype_exclusiveness_representation = Rule()
RULE subtype_exclusiveness_representation #.
subtype_exclusiveness_representation_item = Rule()
RULE subtype_exclusiveness_representation_item #.
subtype_exclusiveness_representation_map = Rule()
RULE subtype_exclusiveness_representation_map #.
subtype_exclusiveness_representation_relationship = Rule()
RULE subtype_exclusiveness_representation_relationship #.
subtype_exclusiveness_representation_relationship_with_transformation = Rule()
RULE subtype_exclusiveness_representation_relationship_with_transformation #.
subtype_exclusiveness_shape_aspect = Rule()
RULE subtype_exclusiveness_shape_aspect #.
subtype_exclusiveness_shape_aspect_relationship = Rule()
RULE subtype_exclusiveness_shape_aspect_relationship #.
subtype_exclusiveness_shape_representation_feature_geometry = Rule()
RULE subtype_exclusiveness_shape_representation_feature_geometry #.
subtype_exclusiveness_shape_representation_geometry = Rule()
RULE subtype_exclusiveness_shape_representation_geometry #.
subtype_exclusiveness_symbol_representation = Rule()
RULE subtype_exclusiveness_symbol_representation #.
subtype_exclusiveness_transition_feature = Rule()
RULE subtype_exclusiveness_transition_feature #.
subtype_mandatory_address = Rule()
RULE subtype_mandatory_address #.
subtype_mandatory_annotation_occurrence = Rule()
RULE subtype_mandatory_annotation_occurrence #.
subtype_mandatory_camera_image = Rule()
RULE subtype_mandatory_camera_image #.
subtype_mandatory_camera_model = Rule()
RULE subtype_mandatory_camera_model #.
subtype_mandatory_colour_specification = Rule()
RULE subtype_mandatory_colour_specification #.
subtype_mandatory_configurable_item = Rule()
RULE subtype_mandatory_configurable_item #.
subtype_mandatory_document_product_association = Rule()
RULE subtype_mandatory_document_product_association #.
subtype_mandatory_draughting_callout = Rule()
RULE subtype_mandatory_draughting_callout #.
subtype_mandatory_externally_defined_item = Rule()
RULE subtype_mandatory_externally_defined_item #.
subtype_mandatory_founded_item = Rule()
RULE subtype_mandatory_founded_item #.
subtype_mandatory_geometric_tolerance = Rule()
RULE subtype_mandatory_geometric_tolerance #.
subtype_mandatory_pre_defined_colour = Rule()
RULE subtype_mandatory_pre_defined_colour #.
subtype_mandatory_pre_defined_curve_font = Rule()
RULE subtype_mandatory_pre_defined_curve_font #.
subtype_mandatory_pre_defined_item = Rule()
RULE subtype_mandatory_pre_defined_item #.
subtype_mandatory_pre_defined_symbol = Rule()
RULE subtype_mandatory_pre_defined_symbol #.
subtype_mandatory_pre_defined_text_font = Rule()
RULE subtype_mandatory_pre_defined_text_font #.
supported_item
surface_side_style_select
surface_style_element_select
symbol_style_select
terminator_symbol_constraint = Rule()
RULE terminator_symbol_constraint #.
text_font_usage = Rule()
RULE text_font_usage #.
text_or_character
text_string_representation_item
time_interval_item
tolerance_deviation_select
tolerance_method_definition
tolerance_parameter_select
tolerance_select
transformation
translational_range_measure
trimming_select
unit
value_qualifier
vector_or_direction
versioned_action_request_requires_date_and_person_or_organization = Rule()
RULE versioned_action_request_requires_date_and_person_or_organization #.
versioned_action_request_requires_status = Rule()
RULE versioned_action_request_requires_status #.
ypr_rotation = ARRAY(ypr_index(yaw),ypr_index(roll),'REAL', scope = schema_scope)
Function Documentation
acyclic()
def automotive_design.acyclic (arg1, arg2)
FUNCTION acyclic #.
        :param arg1
        :type arg1:generic_expression
        :param arg2
        :type arg2:(null)
Referenced by is_acyclic().
acyclic_composite_text()
def automotive_design.acyclic_composite_text (start_composite, child_text)
FUNCTION acyclic_composite_text #.
        :param start_composite
        :type start_composite:composite_text
        :param child_text
        :type child_text:(null)
Referenced by automotive_design.composite_text.wr1().
acyclic_curve_replica()
def automotive_design.acyclic_curve_replica (rep, parent)
FUNCTION acyclic_curve_replica #.
        :param rep
        :type rep:curve_replica
        :param parent
        :type parent:curve
Referenced by automotive_design.curve_replica.wr2().
acyclic_mapped_item_usage()
def automotive_design.acyclic_mapped_item_usage (rep)
FUNCTION acyclic_mapped_item_usage #.
        :param rep
        :type rep:representation
Referenced by automotive_design.draughting_subfigure_representation.wr4(), and automotive_design.draughting_symbol_representation.wr5().
acyclic_mapped_representation()
def automotive_design.acyclic_mapped_representation (parent_set, children_set)
FUNCTION acyclic_mapped_representation #.
        :param parent_set
        :type parent_set:(null)
        :param children_set
        :type children_set:(null)
Referenced by automotive_design.mapped_item.wr1().
acyclic_point_replica()
def automotive_design.acyclic_point_replica (rep, parent)
FUNCTION acyclic_point_replica #.
        :param rep
        :type rep:point_replica
        :param parent
        :type parent:point
Referenced by automotive_design.point_replica.wr2().
acyclic_product_category_relationship()
def automotive_design.acyclic_product_category_relationship (relation, children)
FUNCTION acyclic_product_category_relationship #.
        :param relation
        :type relation:product_category_relationship
        :param children
        :type children:(null)
References bag_to_set().
Referenced by automotive_design.product_category_relationship.wr1().
acyclic_product_definition_relationship()
def automotive_design.acyclic_product_definition_relationship (relation, relatives, specific_relation)
FUNCTION acyclic_product_definition_relationship #.
        :param relation
        :type relation:product_definition_relationship
        :param relatives
        :type relatives:(null)
        :param specific_relation
        :type specific_relation:STRING
Referenced by automotive_design.product_definition_usage.wr1().
acyclic_solid_replica()
def automotive_design.acyclic_solid_replica (rep, parent)
FUNCTION acyclic_solid_replica #.
        :param rep
        :type rep:solid_replica
        :param parent
        :type parent:solid_model
Referenced by automotive_design.solid_replica.wr1().
acyclic_surface_replica()
def automotive_design.acyclic_surface_replica (rep, parent)
FUNCTION acyclic_surface_replica #.
        :param rep
        :type rep:surface_replica
        :param parent
        :type parent:surface
Referenced by automotive_design.surface_replica.wr1().
advanced_face_properties()
def automotive_design.advanced_face_properties (testface)
FUNCTION advanced_face_properties #.
        :param testface
        :type testface:face
aspect_ratio()
def automotive_design.aspect_ratio (p)
FUNCTION aspect_ratio #.
        :param p
        :type p:planar_box
Referenced by automotive_design.camera_image_3d_with_scale.wr2(), and automotive_design.camera_image_2d_with_scale.wr2().
assembly_shape_is_defined()
def automotive_design.assembly_shape_is_defined (assy)
FUNCTION assembly_shape_is_defined #.
        :param assy
        :type assy:next_assembly_usage_occurrence
References bag_to_set().
associated_surface()
def automotive_design.associated_surface (arg)
FUNCTION associated_surface #.
        :param arg
        :type arg:pcurve_or_surface
Referenced by get_basis_surface(), automotive_design.intersection_curve.wr2(), and automotive_design.seam_curve.wr2().
bag_to_set()
def automotive_design.bag_to_set (the_bag)
FUNCTION bag_to_set #.
        :param the_bag
        :type the_bag:(null)
Referenced by acyclic_product_category_relationship(), assembly_shape_is_defined(), get_diameter_for_round_hole(), get_property_definition_representations(), get_round_holes_for_composite_hole(), get_shape_aspect_property_definition_representations(), get_shape_aspects(), representations_mapped_into(), unique_link_usage(), and automotive_design.material_property.wr1().
base_axis()
def automotive_design.base_axis (dim, axis1, axis2, axis3)
FUNCTION base_axis #.
        :param dim
        :type dim:INTEGER
        :param axis1
        :type axis1:direction
        :param axis2
        :type axis2:direction
        :param axis3
        :type axis3:direction
References dot_product(), first_proj_axis(), normalise(), orthogonal_complement(), and second_proj_axis().
Referenced by automotive_design.cartesian_transformation_operator_3d.u(), and automotive_design.cartesian_transformation_operator_2d.u().
boolean_choose()
def automotive_design.boolean_choose (b, choice1, choice2)
FUNCTION boolean_choose #.
        :param b
        :type b:BOOLEAN
        :param choice1
        :type choice1:(null)
        :param choice2
        :type choice2:(null)
Referenced by automotive_design.oriented_edge.edge_edge_end(), and automotive_design.oriented_edge.edge_edge_start().
build_2axes()
def automotive_design.build_2axes (ref_direction)
FUNCTION build_2axes #.
        :param ref_direction
        :type ref_direction:direction
References orthogonal_complement().
Referenced by automotive_design.axis2_placement_2d.p().
build_axes()
def automotive_design.build_axes (axis, ref_direction)
FUNCTION build_axes #.
        :param axis
        :type axis:direction
        :param ref_direction
        :type ref_direction:direction
References cross_product(), first_proj_axis(), and normalise().
Referenced by automotive_design.axis2_placement_3d.p().
check_associative_shape_aspects()
def automotive_design.check_associative_shape_aspects (sdr)
        :param sdr
        :type sdr:shape_definition_representation
References representations_mapped_into(), and using_representations().
check_text_alignment()
def automotive_design.check_text_alignment (ct)
FUNCTION check_text_alignment #.
        :param ct
        :type ct:composite_text
Referenced by automotive_design.draughting_annotation_occurrence.wr11().
check_text_font()
def automotive_design.check_text_font (ct)
FUNCTION check_text_font #.
        :param ct
        :type ct:composite_text
Referenced by automotive_design.draughting_annotation_occurrence.wr12().
closed_shell_reversed()
def automotive_design.closed_shell_reversed (a_shell)
FUNCTION closed_shell_reversed #.
        :param a_shell
        :type a_shell:closed_shell
Referenced by shell_reversed().
conditional_reverse()
def automotive_design.conditional_reverse (p, an_item)
FUNCTION conditional_reverse #.
        :param p
        :type p:BOOLEAN
        :param an_item
        :type an_item:reversible_topology
References topology_reversed().
Referenced by automotive_design.oriented_open_shell.connected_face_set_cfs_faces(), automotive_design.oriented_closed_shell.connected_face_set_cfs_faces(), automotive_design.oriented_face.face_bounds(), and automotive_design.oriented_path.path_edge_list().
constraints_composite_curve_on_surface()
def automotive_design.constraints_composite_curve_on_surface (c)
FUNCTION constraints_composite_curve_on_surface #.
        :param c
        :type c:composite_curve_on_surface
Referenced by automotive_design.composite_curve_on_surface.wr2().
constraints_geometry_shell_based_surface_model()
def automotive_design.constraints_geometry_shell_based_surface_model (m)
FUNCTION constraints_geometry_shell_based_surface_model #.
        :param m
        :type m:shell_based_surface_model
Referenced by automotive_design.shell_based_surface_model.wr1().
constraints_param_b_spline()
def automotive_design.constraints_param_b_spline (degree, up_knots, up_cp, knot_mult, knots)
FUNCTION constraints_param_b_spline #.
        :param degree
        :type degree:INTEGER
        :param up_knots
        :type up_knots:INTEGER
        :param up_cp
        :type up_cp:INTEGER
        :param knot_mult
        :type knot_mult:(null)
        :param knots
        :type knots:(null)
Referenced by automotive_design.b_spline_curve_with_knots.wr1(), automotive_design.b_spline_surface_with_knots.wr1(), and automotive_design.b_spline_surface_with_knots.wr2().
constraints_rectangular_composite_surface()
def automotive_design.constraints_rectangular_composite_surface (s)
FUNCTION constraints_rectangular_composite_surface #.
        :param s
        :type s:rectangular_composite_surface
Referenced by automotive_design.rectangular_composite_surface.wr2().
control_characters_free()
def automotive_design.control_characters_free (s)
FUNCTION control_characters_free #.
        :param s
        :type s:STRING
Referenced by automotive_design.presentable_text.wr1().
convert_plane_angle_for_pair_from_radian()
def automotive_design.convert_plane_angle_for_pair_from_radian (pair, angle_expr)
FUNCTION convert_plane_angle_for_pair_from_radian #.
        :param pair
        :type pair:kinematic_pair
        :param angle_expr
        :type angle_expr:REAL
Referenced by automotive_design.rack_and_pinion_pair_value.actual_rotation().
convert_spatial_to_ypr_rotation()
def automotive_design.convert_spatial_to_ypr_rotation (pair, rotation)
FUNCTION convert_spatial_to_ypr_rotation #.
        :param pair
        :type pair:kinematic_pair
        :param rotation
        :type rotation:spatial_rotation
References normalise(), and plane_angle_for_pair_in_radian().
Referenced by automotive_design.point_on_surface_pair_value.actual_orientation(), automotive_design.spherical_pair_value.actual_orientation(), and automotive_design.point_on_planar_curve_pair_value.actual_orientation().
coordinated_pair_link_representation()
def automotive_design.coordinated_pair_link_representation (link, pair_placement)
FUNCTION coordinated_pair_link_representation #.
        :param link
        :type link:kinematic_link
        :param pair_placement
        :type pair_placement:rigid_placement
References representation_of_link().
Referenced by automotive_design.kinematic_pair.wr1(), and automotive_design.kinematic_pair.wr2().
cross_product()
def automotive_design.cross_product (arg1, arg2)
FUNCTION cross_product #.
        :param arg1
        :type arg1:direction
        :param arg2
        :type arg2:direction
References normalise().
Referenced by build_axes(), first_proj_axis(), and automotive_design.axis2_placement_3d.wr4().
curve_weights_positive()
def automotive_design.curve_weights_positive (b)
FUNCTION curve_weights_positive #.
        :param b
        :type b:rational_b_spline_curve
Referenced by automotive_design.rational_b_spline_curve.wr2().
default_tolerance_table_cell_wr2()
def automotive_design.default_tolerance_table_cell_wr2 (agg)
FUNCTION default_tolerance_table_cell_wr2 #.
        :param agg
        :type agg:(null)
Referenced by automotive_design.default_tolerance_table_cell.wr2().
default_tolerance_table_cell_wr3()
def automotive_design.default_tolerance_table_cell_wr3 (agg)
FUNCTION default_tolerance_table_cell_wr3 #.
        :param agg
        :type agg:(null)
Referenced by automotive_design.default_tolerance_table_cell.wr3().
default_tolerance_table_cell_wr4()
def automotive_design.default_tolerance_table_cell_wr4 (agg)
FUNCTION default_tolerance_table_cell_wr4 #.
        :param agg
        :type agg:(null)
Referenced by automotive_design.default_tolerance_table_cell.wr4().
default_tolerance_table_cell_wr5()
def automotive_design.default_tolerance_table_cell_wr5 (agg)
FUNCTION default_tolerance_table_cell_wr5 #.
        :param agg
        :type agg:(null)
Referenced by automotive_design.default_tolerance_table_cell.wr5().
derive_dimensional_exponents()
def automotive_design.derive_dimensional_exponents (x)
FUNCTION derive_dimensional_exponents #.
        :param x
        :type x:unit
Referenced by automotive_design.conversion_based_unit.named_unit_dimensions(), valid_units(), automotive_design.area_unit.wr1(), automotive_design.volume_unit.wr1(), and automotive_design.projected_zone_definition.wr2().
dimension_of()
def automotive_design.dimension_of (item)
FUNCTION dimension_of #.
        :param item
        :type item:geometric_representation_item
References using_representations().
Referenced by automotive_design.geometric_representation_item.dim().
dimensions_for_si_unit()
def automotive_design.dimensions_for_si_unit (n)
FUNCTION dimensions_for_si_unit #.
        :param n
        :type n:si_unit_name
Referenced by automotive_design.si_unit.named_unit_dimensions().
dot_product()
def automotive_design.dot_product (arg1, arg2)
FUNCTION dot_product #.
        :param arg1
        :type arg1:direction
        :param arg2
        :type arg2:direction
References normalise().
Referenced by base_axis(), first_proj_axis(), second_proj_axis(), automotive_design.camera_model_d3.wr1(), automotive_design.extruded_face_solid.wr1(), and automotive_design.extruded_area_solid.wr1().
edge_reversed()
def automotive_design.edge_reversed (an_edge)
FUNCTION edge_reversed #.
        :param an_edge
        :type an_edge:edge
Referenced by topology_reversed().
face_bound_reversed()
def automotive_design.face_bound_reversed (a_face_bound)
FUNCTION face_bound_reversed #.
        :param a_face_bound
        :type a_face_bound:face_bound
Referenced by topology_reversed().
face_reversed()
def automotive_design.face_reversed (a_face)
FUNCTION face_reversed #.
        :param a_face
        :type a_face:face
References set_of_topology_reversed().
Referenced by topology_reversed().
first_proj_axis()
def automotive_design.first_proj_axis (z_axis, arg)
FUNCTION first_proj_axis #.
        :param z_axis
        :type z_axis:direction
        :param arg
        :type arg:direction
References cross_product(), dot_product(), normalise(), scalar_times_vector(), and vector_difference().
Referenced by base_axis(), and build_axes().
frame_associated_to_background()
def automotive_design.frame_associated_to_background (frame, background)
FUNCTION frame_associated_to_background #.
        :param frame
        :type frame:rigid_placement
        :param background
        :type background:kinematic_frame_background
Referenced by automotive_design.surface_pair.wr1(), automotive_design.planar_curve_pair.wr1(), automotive_design.point_on_planar_curve_pair.wr1(), automotive_design.point_on_surface_pair.wr1(), automotive_design.surface_pair.wr2(), and automotive_design.planar_curve_pair.wr2().
gbsf_check_curve()
def automotive_design.gbsf_check_curve (cv)
FUNCTION gbsf_check_curve #.
        :param cv
        :type cv:representation_item
References gbsf_check_surface().
Referenced by gbsf_check_point(), and gbsf_check_surface().
gbsf_check_point()
def automotive_design.gbsf_check_point (pnt)
FUNCTION gbsf_check_point #.
        :param pnt
        :type pnt:point
References gbsf_check_curve(), and gbsf_check_surface().
gbsf_check_surface()
def automotive_design.gbsf_check_surface (sf)
FUNCTION gbsf_check_surface #.
        :param sf
        :type sf:surface
References gbsf_check_curve().
Referenced by gbsf_check_curve(), and gbsf_check_point().
get_basis_surface()
def automotive_design.get_basis_surface (c)
FUNCTION get_basis_surface #.
        :param c
        :type c:curve_on_surface
References associated_surface().
Referenced by automotive_design.composite_curve_on_surface.basis_surface(), and automotive_design.surface_curve.basis_surface().
get_description_value()
def automotive_design.get_description_value (obj)
FUNCTION get_description_value #.
        :param obj
        :type obj:description_attribute_select
Referenced by automotive_design.representation.description(), automotive_design.effectivity.description(), automotive_design.application_context.description(), automotive_design.approval_role.description(), automotive_design.action_request_solution.description(), automotive_design.person_and_organization_role.description(), automotive_design.context_dependent_shape_representation.description(), automotive_design.organization_role.description(), automotive_design.property_definition_representation.description(), automotive_design.date_time_role.description(), automotive_design.external_source.description(), automotive_design.date_role.description(), automotive_design.configuration_design.description(), and automotive_design.person_and_organization.description().
get_diameter_for_round_hole()
def automotive_design.get_diameter_for_round_hole (rh)
FUNCTION get_diameter_for_round_hole #.
        :param rh
        :type rh:round_hole
References bag_to_set(), get_shape_aspect_property_definition_representations(), and get_shape_aspects().
get_id_value()
def automotive_design.get_id_value (obj)
FUNCTION get_id_value #.
        :param obj
        :type obj:id_attribute_select
Referenced by automotive_design.representation.id(), automotive_design.shape_aspect.id(), automotive_design.shape_aspect_relationship.id(), automotive_design.property_definition.id(), automotive_design.product_category.id(), automotive_design.action.id(), automotive_design.application_context.id(), automotive_design.group.id(), automotive_design.organizational_project.id(), and automotive_design.address.url().
get_multi_language()
def automotive_design.get_multi_language (x)
FUNCTION get_multi_language #.
        :param x
        :type x:multi_language_attribute_assignment
Referenced by automotive_design.multi_language_attribute_assignment.language().
get_name_value()
def automotive_design.get_name_value (obj)
FUNCTION get_name_value #.
        :param obj
        :type obj:name_attribute_select
Referenced by automotive_design.product_definition.name(), automotive_design.effectivity.name(), automotive_design.address.name(), automotive_design.derived_unit.name(), automotive_design.action_request_solution.name(), automotive_design.product_definition_substitute.name(), automotive_design.context_dependent_shape_representation.name(), automotive_design.property_definition_representation.name(), automotive_design.configuration_design.name(), and automotive_design.person_and_organization.name().
get_property_definition_representations()
def automotive_design.get_property_definition_representations (c_def_instance)
FUNCTION get_property_definition_representations #.
        :param c_def_instance
        :type c_def_instance:characterized_definition
References bag_to_set().
Referenced by automotive_design.general_feature.wr1(), automotive_design.hole_in_panel.wr2(), automotive_design.pattern_omit_membership.wr3(), and automotive_design.pattern_offset_membership.wr3().
get_role()
def automotive_design.get_role (obj)
FUNCTION get_role #.
        :param obj
        :type obj:role_select
Referenced by automotive_design.certification_assignment.role(), automotive_design.action_request_assignment.role(), automotive_design.group_assignment.role(), automotive_design.effectivity_assignment.role(), automotive_design.approval_date_time.role(), automotive_design.contract_assignment.role(), automotive_design.approval_assignment.role(), automotive_design.document_reference.role(), automotive_design.name_assignment.role(), automotive_design.action_assignment.role(), and automotive_design.security_classification_assignment.role().
get_round_holes_for_composite_hole()
def automotive_design.get_round_holes_for_composite_hole (sar_instance_set)
FUNCTION get_round_holes_for_composite_hole #.
        :param sar_instance_set
        :type sar_instance_set:(null)
References bag_to_set(), and get_shape_aspect_property_definition_representations().
get_shape_aspect_property_definition_representations()
def automotive_design.get_shape_aspect_property_definition_representations (s_a_instance)
FUNCTION get_shape_aspect_property_definition_representations #.
        :param s_a_instance
        :type s_a_instance:shape_aspect
References bag_to_set().
Referenced by get_diameter_for_round_hole(), get_round_holes_for_composite_hole(), and automotive_design.hole_bottom.wr3().
get_shape_aspects()
def automotive_design.get_shape_aspects (c_def_instance)
FUNCTION get_shape_aspects #.
        :param c_def_instance
        :type c_def_instance:characterized_definition
References bag_to_set().
Referenced by get_diameter_for_round_hole(), and automotive_design.feature_component_definition.wr1().
is_acyclic()
def automotive_design.is_acyclic (arg)
FUNCTION is_acyclic #.
        :param arg
        :type arg:generic_expression
References acyclic().
Referenced by automotive_design.generic_expression.wr1().
is_int_expr()
def automotive_design.is_int_expr (arg)
FUNCTION is_int_expr #.
        :param arg
        :type arg:numeric_expression
Referenced by automotive_design.numeric_expression.is_int(), automotive_design.odd_function.wr1(), automotive_design.index_expression.wr2(), automotive_design.substring_expression.wr3(), and automotive_design.substring_expression.wr4().
is_sql_mappable()
def automotive_design.is_sql_mappable (arg)
FUNCTION is_sql_mappable #.
        :param arg
        :type arg:expression
Referenced by automotive_design.numeric_expression.sql_mappable().
item_correlation()
def automotive_design.item_correlation (items, c_items)
FUNCTION item_correlation #.
        :param items
        :type items:(null)
        :param c_items
        :type c_items:(null)
Referenced by automotive_design.applied_organization_assignment.wr2(), automotive_design.applied_external_identification_assignment.wr2(), automotive_design.applied_group_assignment.wr2(), automotive_design.applied_identification_assignment.wr2(), automotive_design.applied_document_reference.wr2(), automotive_design.applied_organization_assignment.wr3(), automotive_design.applied_group_assignment.wr3(), automotive_design.applied_identification_assignment.wr3(), automotive_design.applied_organization_assignment.wr4(), automotive_design.applied_group_assignment.wr4(), automotive_design.applied_identification_assignment.wr4(), automotive_design.applied_identification_assignment.wr5(), and automotive_design.applied_identification_assignment.wr6().
item_in_context()
def automotive_design.item_in_context (item, cntxt)
FUNCTION item_in_context #.
        :param item
        :type item:representation_item
        :param cntxt
        :type cntxt:representation_context
Referenced by automotive_design.presentation_size.wr1(), automotive_design.representation_map.wr1(), and automotive_design.character_glyph_symbol.wr2().
leap_year()
def automotive_design.leap_year (year)
FUNCTION leap_year #.
        :param year
        :type year:INTEGER
Referenced by valid_calendar_date().
list_face_loops()
def automotive_design.list_face_loops (f)
FUNCTION list_face_loops #.
        :param f
        :type f:face
Referenced by automotive_design.face.wr1(), and automotive_design.subface.wr1().
list_of_topology_reversed()
def automotive_design.list_of_topology_reversed (a_list)
FUNCTION list_of_topology_reversed #.
        :param a_list
        :type a_list:list_of_reversible_topology_item
References topology_reversed().
Referenced by path_reversed(), and topology_reversed().
list_to_array()
def automotive_design.list_to_array (lis, low, u)
FUNCTION list_to_array #.
        :param lis
        :type lis:(null)
        :param low
        :type low:INTEGER
        :param u
        :type u:INTEGER
Referenced by automotive_design.b_spline_curve.control_points(), make_array_of_array(), and automotive_design.rational_b_spline_curve.weights().
list_to_set()
def automotive_design.list_to_set (l)
FUNCTION list_to_set #.
        :param l
        :type l:(null)
Referenced by automotive_design.face.wr1(), and automotive_design.subface.wr1().
make_array_of_array()
def automotive_design.make_array_of_array (lis, low1, u1, low2, u2)
FUNCTION make_array_of_array #.
        :param lis
        :type lis:(null)
        :param low1
        :type low1:INTEGER
        :param u1
        :type u1:INTEGER
        :param low2
        :type low2:INTEGER
        :param u2
        :type u2:INTEGER
References list_to_array().
Referenced by automotive_design.b_spline_surface.control_points(), and automotive_design.rational_b_spline_surface.weights().
mixed_loop_type_set()
def automotive_design.mixed_loop_type_set (l)
FUNCTION mixed_loop_type_set #.
        :param l
        :type l:(null)
Referenced by automotive_design.face.wr1(), and automotive_design.subface.wr1().
msb_shells()
def automotive_design.msb_shells (brep)
FUNCTION msb_shells #.
        :param brep
        :type brep:manifold_solid_brep
msf_curve_check()
def automotive_design.msf_curve_check (cv)
FUNCTION msf_curve_check #.
        :param cv
        :type cv:representation_item
References msf_surface_check().
Referenced by msf_surface_check().
msf_surface_check()
def automotive_design.msf_surface_check (surf)
FUNCTION msf_surface_check #.
        :param surf
        :type surf:surface
References msf_curve_check().
Referenced by msf_curve_check().
nmsf_curve_check()
def automotive_design.nmsf_curve_check (cv)
FUNCTION nmsf_curve_check #.
        :param cv
        :type cv:representation_item
References nmsf_surface_check().
Referenced by nmsf_surface_check().
nmsf_surface_check()
def automotive_design.nmsf_surface_check (surf)
FUNCTION nmsf_surface_check #.
        :param surf
        :type surf:surface
References nmsf_curve_check().
Referenced by nmsf_curve_check().
normalise()
def automotive_design.normalise (arg)
FUNCTION normalise #.
        :param arg
        :type arg:vector_or_direction
Referenced by base_axis(), build_axes(), convert_spatial_to_ypr_rotation(), cross_product(), dot_product(), first_proj_axis(), scalar_times_vector(), second_proj_axis(), and vector_difference().
open_shell_reversed()
def automotive_design.open_shell_reversed (a_shell)
FUNCTION open_shell_reversed #.
        :param a_shell
        :type a_shell:open_shell
Referenced by shell_reversed().
orthogonal_complement()
def automotive_design.orthogonal_complement (vec)
FUNCTION orthogonal_complement #.
        :param vec
        :type vec:direction
Referenced by base_axis(), and build_2axes().
path_head_to_tail()
def automotive_design.path_head_to_tail (a_path)
FUNCTION path_head_to_tail #.
        :param a_path
        :type a_path:path
Referenced by automotive_design.path.wr1().
path_reversed()
def automotive_design.path_reversed (a_path)
FUNCTION path_reversed #.
        :param a_path
        :type a_path:path
References list_of_topology_reversed().
Referenced by topology_reversed().
plane_angle_for_pair_in_radian()
def automotive_design.plane_angle_for_pair_in_radian (pair, angle)
FUNCTION plane_angle_for_pair_in_radian #.
        :param pair
        :type pair:kinematic_pair
        :param angle
        :type angle:REAL
Referenced by automotive_design.screw_pair_value.actual_translation(), convert_spatial_to_ypr_rotation(), and automotive_design.universal_pair.wr1().
representation_of_link()
def automotive_design.representation_of_link (link)
FUNCTION representation_of_link #.
        :param link
        :type link:kinematic_link
Referenced by coordinated_pair_link_representation(), and automotive_design.mechanism_base_placement.representation_relationship_rep_2().
representations_mapped_into()
def automotive_design.representations_mapped_into (rep)
FUNCTION representations_mapped_into #.
        :param rep
        :type rep:representation
References bag_to_set().
Referenced by check_associative_shape_aspects().
scalar_times_vector()
def automotive_design.scalar_times_vector (scalar, vec)
FUNCTION scalar_times_vector #.
        :param scalar
        :type scalar:REAL
        :param vec
        :type vec:vector_or_direction
References normalise().
Referenced by first_proj_axis(), and second_proj_axis().
second_proj_axis()
def automotive_design.second_proj_axis (z_axis, x_axis, arg)
FUNCTION second_proj_axis #.
        :param z_axis
        :type z_axis:direction
        :param x_axis
        :type x_axis:direction
        :param arg
        :type arg:direction
References dot_product(), normalise(), scalar_times_vector(), and vector_difference().
Referenced by base_axis().
set_of_topology_reversed()
def automotive_design.set_of_topology_reversed (a_set)
FUNCTION set_of_topology_reversed #.
        :param a_set
        :type a_set:set_of_reversible_topology_item
References topology_reversed().
Referenced by face_reversed(), and topology_reversed().
shell_reversed()
def automotive_design.shell_reversed (a_shell)
FUNCTION shell_reversed #.
        :param a_shell
        :type a_shell:shell
References closed_shell_reversed(), and open_shell_reversed().
Referenced by topology_reversed().
suitably_based_mechanism()
def automotive_design.suitably_based_mechanism (mbp, mech)
FUNCTION suitably_based_mechanism #.
        :param mbp
        :type mbp:mechanism_base_placement
        :param mech
        :type mech:mechanism
Referenced by automotive_design.mechanism_base_placement.wr2().
surface_condition_correlation()
def automotive_design.surface_condition_correlation (pd, rep)
FUNCTION surface_condition_correlation #.
        :param pd
        :type pd:property_definition
        :param rep
        :type rep:representation
surface_weights_positive()
def automotive_design.surface_weights_positive (b)
FUNCTION surface_weights_positive #.
        :param b
        :type b:rational_b_spline_surface
Referenced by automotive_design.rational_b_spline_surface.wr2().
topology_reversed()
def automotive_design.topology_reversed (an_item)
FUNCTION topology_reversed #.
        :param an_item
        :type an_item:reversible_topology
References edge_reversed(), face_bound_reversed(), face_reversed(), list_of_topology_reversed(), path_reversed(), set_of_topology_reversed(), and shell_reversed().
Referenced by conditional_reverse(), list_of_topology_reversed(), and set_of_topology_reversed().
type_check_function()
def automotive_design.type_check_function (the_type, sub_names, criterion)
FUNCTION type_check_function #.
        :param the_type
        :type the_type:(null)
        :param sub_names
        :type sub_names:(null)
        :param criterion
        :type criterion:INTEGER
unique_link_usage()
def automotive_design.unique_link_usage (link)
FUNCTION unique_link_usage #.
        :param link
        :type link:kinematic_link
References bag_to_set().
Referenced by automotive_design.kinematic_link.wr2().
using_items()
def automotive_design.using_items (item, checked_items)
FUNCTION using_items #.
        :param item
        :type item:founded_item_select
        :param checked_items
        :type checked_items:(null)
Referenced by automotive_design.founded_item.users(), and using_representations().
using_representations()
def automotive_design.using_representations (item)
FUNCTION using_representations #.
        :param item
        :type item:founded_item_select
References using_items().
Referenced by check_associative_shape_aspects(), dimension_of(), automotive_design.representation_item.wr1(), automotive_design.mapped_item.wr1(), and automotive_design.item_identified_representation_usage.wr1().
valid_basis_curve_in_2d_wireframe()
def automotive_design.valid_basis_curve_in_2d_wireframe (crv)
FUNCTION valid_basis_curve_in_2d_wireframe #.
        :param crv
        :type crv:curve
valid_calendar_date()
def automotive_design.valid_calendar_date (date)
FUNCTION valid_calendar_date #.
        :param date
        :type date:calendar_date
References leap_year().
Referenced by automotive_design.calendar_date.wr1().
valid_geometrically_bounded_wf_curve()
def automotive_design.valid_geometrically_bounded_wf_curve (crv)
FUNCTION valid_geometrically_bounded_wf_curve #.
        :param crv
        :type crv:curve
Referenced by valid_geometrically_bounded_wf_point().
valid_geometrically_bounded_wf_point()
def automotive_design.valid_geometrically_bounded_wf_point (pnt)
FUNCTION valid_geometrically_bounded_wf_point #.
        :param pnt
        :type pnt:point
References valid_geometrically_bounded_wf_curve().
valid_measure_value()
def automotive_design.valid_measure_value (m)
FUNCTION valid_measure_value #.
        :param m
        :type m:measure_value
Referenced by automotive_design.uncertainty_measure_with_unit.wr1().
valid_time()
def automotive_design.valid_time (time)
FUNCTION valid_time #.
        :param time
        :type time:local_time
Referenced by automotive_design.local_time.wr1().
valid_units()
def automotive_design.valid_units (m)
FUNCTION valid_units #.
        :param m
        :type m:measure_with_unit
References derive_dimensional_exponents().
Referenced by automotive_design.measure_with_unit.wr1().
valid_wireframe_edge_curve()
def automotive_design.valid_wireframe_edge_curve (crv)
FUNCTION valid_wireframe_edge_curve #.
        :param crv
        :type crv:curve
valid_wireframe_vertex_point()
def automotive_design.valid_wireframe_vertex_point (pnt)
FUNCTION valid_wireframe_vertex_point #.
        :param pnt
        :type pnt:point
value_range_aggregate_rep_item()
def automotive_design.value_range_aggregate_rep_item (agg)
FUNCTION value_range_aggregate_rep_item #.
        :param agg
        :type agg:(null)
value_range_wr1()
def automotive_design.value_range_wr1 (agg)
FUNCTION value_range_wr1 #.
        :param agg
        :type agg:(null)
Referenced by automotive_design.value_range.wr1().
value_range_wr2()
def automotive_design.value_range_wr2 (agg)
FUNCTION value_range_wr2 #.
        :param agg
        :type agg:(null)
Referenced by automotive_design.value_range.wr2().
value_range_wr3()
def automotive_design.value_range_wr3 (agg)
FUNCTION value_range_wr3 #.
        :param agg
        :type agg:(null)
Referenced by automotive_design.value_range.wr3().
vector_difference()
def automotive_design.vector_difference (arg1, arg2)
FUNCTION vector_difference #.
        :param arg1
        :type arg1:vector_or_direction
        :param arg2
        :type arg2:vector_or_direction
References normalise().
Referenced by first_proj_axis(), and second_proj_axis().
ypr_index()
def automotive_design.ypr_index (ypr)
FUNCTION ypr_index #.
        :param ypr
        :type ypr:ypr_enumeration
Variable Documentation
action_item
automotive_design.action_item
action_request_item
automotive_design.action_request_item
annotation_plane_element
automotive_design.annotation_plane_element
Initial value:
 =  SELECT(
         'draughting_callout',
         'styled_item',
         scope = schema_scope)
annotation_symbol_occurrence_item
automotive_design.annotation_symbol_occurrence_item
Initial value:
 =  SELECT(
         'annotation_symbol',
         'defined_symbol',
         scope = schema_scope)
Referenced by automotive_design.annotation_symbol_occurrence.styled_item_item().
annotation_text_occurrence_item
automotive_design.annotation_text_occurrence_item
Initial value:
 =  SELECT(
         'text_literal',
         'annotation_text',
         'annotation_text_character',
         'defined_character_glyph',
         'composite_text',
         scope = schema_scope)
Referenced by automotive_design.annotation_text_occurrence.styled_item_item().
application_protocol_definition_required
automotive_design.application_protocol_definition_required = Rule()
RULE application_protocol_definition_required #.
approval_item
automotive_design.approval_item
approval_person_organization_requires_date_time
automotive_design.approval_person_organization_requires_date_time = Rule()
RULE approval_person_organization_requires_date_time #.
approval_requires_approval_assignment
automotive_design.approval_requires_approval_assignment = Rule()
RULE approval_requires_approval_assignment #.
area_or_view
automotive_design.area_or_view
Initial value:
 =  SELECT(
         'presentation_area',
         'presentation_view',
         scope = schema_scope)
Referenced by automotive_design.background_colour.presentation().
attribute_language_item
automotive_design.attribute_language_item
attribute_type
automotive_design.attribute_type
Initial value:
 =  SELECT(
         'label',
         'text',
         scope = schema_scope)
Referenced by automotive_design.attribute_value_assignment.attribute_value().
axis2_placement
automotive_design.axis2_placement
Initial value:
 =  SELECT(
         'axis2_placement_2d',
         'axis2_placement_3d',
         scope = schema_scope)
Referenced by automotive_design.annotation_text_character.mapped_item_mapping_target(), automotive_design.annotation_text.mapped_item_mapping_target(), automotive_design.text_style_with_mirror.mirror_placement(), automotive_design.text_literal.placement(), automotive_design.planar_box.placement(), automotive_design.defined_character_glyph.placement(), automotive_design.symbol_target.placement(), automotive_design.conic.position(), and automotive_design.symbol_representation_map.representation_map_mapping_origin().
boolean_operand
automotive_design.boolean_operand
Initial value:
 =  SELECT(
         'solid_model',
         'half_space_solid',
         'csg_primitive',
         'boolean_result',
         scope = schema_scope)
Referenced by automotive_design.boolean_result.first_operand(), and automotive_design.boolean_result.second_operand().
box_characteristic_select
automotive_design.box_characteristic_select
Initial value:
 =  SELECT(
         'box_height',
         'box_width',
         'box_slant_angle',
         'box_rotate_angle',
         scope = schema_scope)
category_usage_item
automotive_design.category_usage_item
Initial value:
 =  SELECT(
         'product_class',
         scope = schema_scope)
certification_item
automotive_design.certification_item
Initial value:
 =  SELECT(
         'product_definition',
         'product_definition_formation',
         'product_definition_formation_relationship',
         'product_definition_relationship',
         scope = schema_scope)
character_spacing_select
automotive_design.character_spacing_select
Initial value:
 =  SELECT(
         'length_measure',
         'ratio_measure',
         'measure_with_unit',
         'descriptive_measure',
         scope = schema_scope)
Referenced by automotive_design.text_style_with_spacing.character_spacing().
character_style_select
automotive_design.character_style_select
Initial value:
 =  SELECT(
         'text_style_for_defined_font',
         scope = schema_scope)
Referenced by automotive_design.text_style.character_appearance().
characterized_action_definition
automotive_design.characterized_action_definition
Initial value:
 =  SELECT(
         'action',
         'action_method',
         'action_method_relationship',
         'action_relationship',
         scope = schema_scope)
Referenced by automotive_design.action_property.definition().
characterized_definition
automotive_design.characterized_definition
Initial value:
 =  SELECT(
         'characterized_object',
         'characterized_product_definition',
         'shape_definition',
         scope = schema_scope)
Referenced by automotive_design.property_definition.definition(), and automotive_design.kinematic_property_definition.ground_definition().
characterized_material_property
automotive_design.characterized_material_property
Initial value:
 =  SELECT(
         'material_property_representation',
         scope = schema_scope)
Referenced by automotive_design.material_designation_characterization.property().
characterized_product_definition
automotive_design.characterized_product_definition
Initial value:
 =  SELECT(
         'product_definition',
         'product_definition_relationship',
         scope = schema_scope)
Referenced by automotive_design.process_product_association.defined_product().
characterized_resource_definition
automotive_design.characterized_resource_definition
Initial value:
 =  SELECT(
         'action_resource',
         'action_resource_requirement',
         scope = schema_scope)
Referenced by automotive_design.resource_property.resource().
class_usage_effectivity_context_item
automotive_design.class_usage_effectivity_context_item
Initial value:
 =  SELECT(
         'product_definition',
         scope = schema_scope)
classification_item
automotive_design.classification_item
compatible_dimension
automotive_design.compatible_dimension = Rule()
RULE compatible_dimension #.
complex_product_requires_product_definition
automotive_design.complex_product_requires_product_definition = Rule()
RULE complex_product_requires_product_definition #.
compound_features_of_equal_type
automotive_design.compound_features_of_equal_type = Rule()
RULE compound_features_of_equal_type #.
compound_item_definition
automotive_design.compound_item_definition
Initial value:
 =  SELECT(
         'list_representation_item',
         'set_representation_item',
         scope = schema_scope)
Referenced by automotive_design.compound_representation_item.item_element().
configuration_design_item
automotive_design.configuration_design_item
Initial value:
 =  SELECT(
         'product_definition',
         'product_definition_formation',
         scope = schema_scope)
Referenced by automotive_design.configuration_design.design().
configured_effectivity_context_item
automotive_design.configured_effectivity_context_item
Initial value:
 =  SELECT(
         'product_concept_feature_association',
         scope = schema_scope)
configured_effectivity_item
automotive_design.configured_effectivity_item
Initial value:
 =  SELECT(
         'action_relationship',
         'process_plan',
         'product_definition',
         'product_process_plan',
         scope = schema_scope)
consistent_uncertainty
automotive_design.consistent_uncertainty = Rule()
RULE consistent_uncertainty #.
contract_item
automotive_design.contract_item
Initial value:
 =  SELECT(
         'drawing_revision',
         'executed_action',
         'product_definition_formation',
         scope = schema_scope)
coordinated_assembly_and_shape
automotive_design.coordinated_assembly_and_shape = Rule()
RULE coordinated_assembly_and_shape #.
csg_primitive
automotive_design.csg_primitive
Initial value:
 =  SELECT(
         'sphere',
         'block',
         'right_angular_wedge',
         'torus',
         'right_circular_cone',
         'right_circular_cylinder',
         scope = schema_scope)
csg_select
automotive_design.csg_select
Initial value:
 =  SELECT(
         'boolean_result',
         'csg_primitive',
         scope = schema_scope)
Referenced by automotive_design.csg_solid.tree_root_expression().
curve_font_or_scaled_curve_font_select
automotive_design.curve_font_or_scaled_curve_font_select
Initial value:
 =  SELECT(
         'curve_style_font_select',
         scope = schema_scope)
Referenced by automotive_design.curve_style.curve_font().
curve_font_usage
automotive_design.curve_font_usage = Rule()
RULE curve_font_usage #.
curve_on_surface
automotive_design.curve_on_surface
Initial value:
 =  SELECT(
         'pcurve',
         'surface_curve',
         'composite_curve_on_surface',
         scope = schema_scope)
curve_or_render
automotive_design.curve_or_render
Initial value:
 =  SELECT(
         'curve_style',
         'curve_style_rendering',
         scope = schema_scope)
Referenced by automotive_design.surface_style_boundary.style_of_boundary(), automotive_design.surface_style_control_grid.style_of_control_grid(), automotive_design.surface_style_parameter_line.style_of_parameter_lines(), automotive_design.surface_style_segmentation_curve.style_of_segmentation_curve(), and automotive_design.surface_style_silhouette.style_of_silhouette().
curve_style_font_select
automotive_design.curve_style_font_select
Initial value:
 =  SELECT(
         'curve_style_font',
         'pre_defined_curve_font',
         'externally_defined_curve_font',
         scope = schema_scope)
date_and_time_item
automotive_design.date_and_time_item
date_item
automotive_design.date_item
date_time_or_event_occurrence
automotive_design.date_time_or_event_occurrence
Initial value:
 =  SELECT(
         'date_time_select',
         'event_occurrence',
         scope = schema_scope)
Referenced by automotive_design.dated_effectivity.effectivity_end_date(), automotive_design.dated_effectivity.effectivity_start_date(), automotive_design.time_interval_with_bounds.primary_bound(), and automotive_design.time_interval_with_bounds.secondary_bound().
date_time_select
automotive_design.date_time_select
Initial value:
 =  SELECT(
         'date',
         'date_and_time',
         'local_time',
         scope = schema_scope)
Referenced by automotive_design.approval_date_time.date_time().
defined_glyph_select
automotive_design.defined_glyph_select
Initial value:
 =  SELECT(
         'externally_defined_character_glyph',
         scope = schema_scope)
Referenced by automotive_design.defined_character_glyph.definition().
defined_symbol_select
automotive_design.defined_symbol_select
Initial value:
 =  SELECT(
         'pre_defined_symbol',
         'externally_defined_symbol',
         scope = schema_scope)
Referenced by automotive_design.defined_symbol.definition().
dependent_instantiable_action_directive
automotive_design.dependent_instantiable_action_directive = Rule()
RULE dependent_instantiable_action_directive #.
dependent_instantiable_action_resource_type
automotive_design.dependent_instantiable_action_resource_type = Rule()
RULE dependent_instantiable_action_resource_type #.
dependent_instantiable_approval_role
automotive_design.dependent_instantiable_approval_role = Rule()
RULE dependent_instantiable_approval_role #.
dependent_instantiable_attribute_value_role
automotive_design.dependent_instantiable_attribute_value_role = Rule()
RULE dependent_instantiable_attribute_value_role #.
dependent_instantiable_classification_role
automotive_design.dependent_instantiable_classification_role = Rule()
RULE dependent_instantiable_classification_role #.
dependent_instantiable_colour_rgb
automotive_design.dependent_instantiable_colour_rgb = Rule()
RULE dependent_instantiable_colour_rgb #.
dependent_instantiable_contract_type
automotive_design.dependent_instantiable_contract_type = Rule()
RULE dependent_instantiable_contract_type #.
dependent_instantiable_curve_style
automotive_design.dependent_instantiable_curve_style = Rule()
RULE dependent_instantiable_curve_style #.
dependent_instantiable_date
automotive_design.dependent_instantiable_date = Rule()
RULE dependent_instantiable_date #.
dependent_instantiable_date_and_time
automotive_design.dependent_instantiable_date_and_time = Rule()
RULE dependent_instantiable_date_and_time #.
dependent_instantiable_date_role
automotive_design.dependent_instantiable_date_role = Rule()
RULE dependent_instantiable_date_role #.
dependent_instantiable_date_time_role
automotive_design.dependent_instantiable_date_time_role = Rule()
RULE dependent_instantiable_date_time_role #.
dependent_instantiable_derived_unit
automotive_design.dependent_instantiable_derived_unit = Rule()
RULE dependent_instantiable_derived_unit #.
dependent_instantiable_dimensional_size
automotive_design.dependent_instantiable_dimensional_size = Rule()
RULE dependent_instantiable_dimensional_size #.
dependent_instantiable_document_usage_role
automotive_design.dependent_instantiable_document_usage_role = Rule()
RULE dependent_instantiable_document_usage_role #.
dependent_instantiable_effectivity_context_role
automotive_design.dependent_instantiable_effectivity_context_role = Rule()
RULE dependent_instantiable_effectivity_context_role #.
dependent_instantiable_event_occurrence_role
automotive_design.dependent_instantiable_event_occurrence_role = Rule()
RULE dependent_instantiable_event_occurrence_role #.
dependent_instantiable_externally_defined_symbol
automotive_design.dependent_instantiable_externally_defined_symbol = Rule()
RULE dependent_instantiable_externally_defined_symbol #.
dependent_instantiable_fill_area_style
automotive_design.dependent_instantiable_fill_area_style = Rule()
RULE dependent_instantiable_fill_area_style #.
dependent_instantiable_fill_area_style_colour
automotive_design.dependent_instantiable_fill_area_style_colour = Rule()
RULE dependent_instantiable_fill_area_style_colour #.
dependent_instantiable_identification_role
automotive_design.dependent_instantiable_identification_role = Rule()
RULE dependent_instantiable_identification_role #.
dependent_instantiable_measure_with_unit
automotive_design.dependent_instantiable_measure_with_unit = Rule()
RULE dependent_instantiable_measure_with_unit #.
dependent_instantiable_named_unit
automotive_design.dependent_instantiable_named_unit = Rule()
RULE dependent_instantiable_named_unit #.
dependent_instantiable_object_role
automotive_design.dependent_instantiable_object_role = Rule()
RULE dependent_instantiable_object_role #.
dependent_instantiable_organization_role
automotive_design.dependent_instantiable_organization_role = Rule()
RULE dependent_instantiable_organization_role #.
dependent_instantiable_organizational_project_role
automotive_design.dependent_instantiable_organizational_project_role = Rule()
RULE dependent_instantiable_organizational_project_role #.
dependent_instantiable_person_and_organization_role
automotive_design.dependent_instantiable_person_and_organization_role = Rule()
RULE dependent_instantiable_person_and_organization_role #.
dependent_instantiable_pre_defined_colour
automotive_design.dependent_instantiable_pre_defined_colour = Rule()
RULE dependent_instantiable_pre_defined_colour #.
dependent_instantiable_pre_defined_symbol
automotive_design.dependent_instantiable_pre_defined_symbol = Rule()
RULE dependent_instantiable_pre_defined_symbol #.
dependent_instantiable_precision_qualifier
automotive_design.dependent_instantiable_precision_qualifier = Rule()
RULE dependent_instantiable_precision_qualifier #.
dependent_instantiable_presentation_style_by_context
automotive_design.dependent_instantiable_presentation_style_by_context = Rule()
RULE dependent_instantiable_presentation_style_by_context #.
dependent_instantiable_product_definition_context_role
automotive_design.dependent_instantiable_product_definition_context_role = Rule()
RULE dependent_instantiable_product_definition_context_role #.
dependent_instantiable_resource_requirement_type
automotive_design.dependent_instantiable_resource_requirement_type = Rule()
RULE dependent_instantiable_resource_requirement_type #.
dependent_instantiable_retention
automotive_design.dependent_instantiable_retention = Rule()
RULE dependent_instantiable_retention #.
dependent_instantiable_standard_uncertainty
automotive_design.dependent_instantiable_standard_uncertainty = Rule()
RULE dependent_instantiable_standard_uncertainty #.
dependent_instantiable_symbol_colour
automotive_design.dependent_instantiable_symbol_colour = Rule()
RULE dependent_instantiable_symbol_colour #.
dependent_instantiable_text_style
automotive_design.dependent_instantiable_text_style = Rule()
RULE dependent_instantiable_text_style #.
dependent_instantiable_text_style_for_defined_font
automotive_design.dependent_instantiable_text_style_for_defined_font = Rule()
RULE dependent_instantiable_text_style_for_defined_font #.
dependent_instantiable_time_interval_role
automotive_design.dependent_instantiable_time_interval_role = Rule()
RULE dependent_instantiable_time_interval_role #.
dependent_instantiable_tolerance_value
automotive_design.dependent_instantiable_tolerance_value = Rule()
RULE dependent_instantiable_tolerance_value #.
dependent_instantiable_type_qualifier
automotive_design.dependent_instantiable_type_qualifier = Rule()
RULE dependent_instantiable_type_qualifier #.
dependent_instantiable_uncertainty_qualifier
automotive_design.dependent_instantiable_uncertainty_qualifier = Rule()
RULE dependent_instantiable_uncertainty_qualifier #.
derived_property_select
automotive_design.derived_property_select
Initial value:
 =  SELECT(
         'property_definition',
         'action_property',
         'resource_property',
         scope = schema_scope)
Referenced by automotive_design.general_property_association.derived_definition().
description_attribute_select
automotive_design.description_attribute_select
Initial value:
 =  SELECT(
         'action_request_solution',
         'application_context',
         'approval_role',
         'configuration_design',
         'date_role',
         'date_time_role',
         'context_dependent_shape_representation',
         'effectivity',
         'external_source',
         'organization_role',
         'person_and_organization_role',
         'person_and_organization',
         'property_definition_representation',
         'representation',
         scope = schema_scope)
Referenced by automotive_design.description_attribute.described_item().
design_constraint_requires_product_definition
automotive_design.design_constraint_requires_product_definition = Rule()
RULE design_constraint_requires_product_definition #.
dimensional_characteristic
automotive_design.dimensional_characteristic
Initial value:
 =  SELECT(
         'dimensional_location',
         'dimensional_size',
         scope = schema_scope)
Referenced by automotive_design.dimensional_characteristic_representation.dimension(), and automotive_design.plus_minus_tolerance.toleranced_dimension().
dimensionality_is_two_or_three
automotive_design.dimensionality_is_two_or_three = Rule()
RULE dimensionality_is_two_or_three #.
direction_count_select
automotive_design.direction_count_select
Initial value:
 =  SELECT(
         'u_direction_count',
         'v_direction_count',
         scope = schema_scope)
document_reference_item
automotive_design.document_reference_item
draughting_callout_element
automotive_design.draughting_callout_element
Initial value:
 =  SELECT(
         'annotation_text_occurrence',
         'annotation_symbol_occurrence',
         'annotation_curve_occurrence',
         scope = schema_scope)
draughting_model_item_association_select
automotive_design.draughting_model_item_association_select
Initial value:
 =  SELECT(
         'annotation_occurrence',
         'draughting_callout',
         scope = schema_scope)
Referenced by automotive_design.draughting_model_item_association.item_identified_representation_usage_identified_item().
draughting_subfigure_representation_layers
automotive_design.draughting_subfigure_representation_layers = Rule()
RULE draughting_subfigure_representation_layers #.
draughting_titled_item
automotive_design.draughting_titled_item
Initial value:
 =  SELECT(
         'drawing_revision',
         'drawing_sheet_revision',
         scope = schema_scope)
drawing_sheet_annotation_layers
automotive_design.drawing_sheet_annotation_layers = Rule()
RULE drawing_sheet_annotation_layers #.
drawing_sheet_layout_usage
automotive_design.drawing_sheet_layout_usage = Rule()
RULE drawing_sheet_layout_usage #.
drawing_view_annotation_layers
automotive_design.drawing_view_annotation_layers = Rule()
RULE drawing_view_annotation_layers #.
effectivity_item
automotive_design.effectivity_item
event_occurrence_item
automotive_design.event_occurrence_item
event_occurrence_requires_event_occurrence_assignment
automotive_design.event_occurrence_requires_event_occurrence_assignment = Rule()
RULE event_occurrence_requires_event_occurrence_assignment #.
executed_action_requires_action_status
automotive_design.executed_action_requires_action_status = Rule()
RULE executed_action_requires_action_status #.
external_identification_item
automotive_design.external_identification_item
Initial value:
 =  SELECT(
         'document_file',
         'externally_defined_class',
         'externally_defined_general_property',
         'product_definition',
         scope = schema_scope)
externally_defined_class_with_known_source_requirement
automotive_design.externally_defined_class_with_known_source_requirement = Rule()
RULE externally_defined_class_with_known_source_requirement #.
fill_area_style_tile_shape_select
automotive_design.fill_area_style_tile_shape_select
Initial value:
 =  SELECT(
         'fill_area_style_tile_symbol_with_style',
         scope = schema_scope)
fill_area_style_tile_symbol_constraint
automotive_design.fill_area_style_tile_symbol_constraint = Rule()
RULE fill_area_style_tile_symbol_constraint #.
fill_style_select
automotive_design.fill_style_select
Initial value:
 =  SELECT(
         'fill_area_style_colour',
         'externally_defined_tile_style',
         'fill_area_style_tiles',
         'externally_defined_hatch_style',
         'fill_area_style_hatching',
         scope = schema_scope)
font_select
automotive_design.font_select
Initial value:
 =  SELECT(
         'pre_defined_text_font',
         'externally_defined_text_font',
         scope = schema_scope)
Referenced by automotive_design.text_literal.font().
founded_item_select
automotive_design.founded_item_select
Initial value:
 =  SELECT(
         'founded_item',
         'representation_item',
         scope = schema_scope)
full_model_change_completeness_for_action_property
automotive_design.full_model_change_completeness_for_action_property = Rule()
RULE full_model_change_completeness_for_action_property #.
full_model_change_completeness_for_property_definition
automotive_design.full_model_change_completeness_for_property_definition = Rule()
RULE full_model_change_completeness_for_property_definition #.
geometric_set_select
automotive_design.geometric_set_select
Initial value:
 =  SELECT(
         'point',
         'curve',
         'surface',
         scope = schema_scope)
global_length_and_angle_units_2d_or_3d
automotive_design.global_length_and_angle_units_2d_or_3d = Rule()
RULE global_length_and_angle_units_2d_or_3d #.
group_item
automotive_design.group_item
Initial value:
 =  SELECT(
         'geometric_representation_item',
         'mapped_item',
         'product_concept_feature',
         'shape_aspect',
         'styled_item',
         'topological_representation_item',
         scope = schema_scope)
id_attribute_select
automotive_design.id_attribute_select
Initial value:
 =  SELECT(
         'action',
         'address',
         'product_category',
         'property_definition',
         'shape_aspect',
         'shape_aspect_relationship',
         'application_context',
         'group',
         'organizational_project',
         'representation',
         scope = schema_scope)
Referenced by automotive_design.id_attribute.identified_item().
identification_item
automotive_design.identification_item
invisibility_context
automotive_design.invisibility_context
Initial value:
 =  SELECT(
         'presentation_representation',
         'presentation_set',
         scope = schema_scope)
Referenced by automotive_design.context_dependent_invisibility.presentation_context().
invisible_item
automotive_design.invisible_item
Initial value:
 =  SELECT(
         'draughting_callout',
         'presentation_layer_assignment',
         'representation',
         'styled_item',
         scope = schema_scope)
kinematic_analysis_definition
automotive_design.kinematic_analysis_definition
Initial value:
 =  SELECT(
         'interpolated_configuration_sequence',
         scope = schema_scope)
kinematic_frame_background
automotive_design.kinematic_frame_background
Initial value:
 =  SELECT(
         'point',
         'curve',
         'surface',
         scope = schema_scope)
kinematic_result
automotive_design.kinematic_result
Initial value:
 =  SELECT(
         'interpolated_configuration_sequence',
         'resulting_path',
         scope = schema_scope)
language_item
automotive_design.language_item
Initial value:
 =  SELECT(
         'representation',
         scope = schema_scope)
layered_item
automotive_design.layered_item
Initial value:
 =  SELECT(
         'presentation_representation',
         'representation_item',
         scope = schema_scope)
list_of_reversible_topology_item
automotive_design.list_of_reversible_topology_item = LIST(0,None,'reversible_topology_item', scope = schema_scope)
list_representation_item
automotive_design.list_representation_item = LIST(1,None,'representation_item', scope = schema_scope)
marker_select
automotive_design.marker_select
Initial value:
 =  SELECT(
         'marker_type',
         'pre_defined_marker',
         scope = schema_scope)
Referenced by automotive_design.point_style.marker().
measure_value
automotive_design.measure_value
Initial value:
 =  SELECT(
         'amount_of_substance_measure',
         'area_measure',
         'celsius_temperature_measure',
         'context_dependent_measure',
         'count_measure',
         'descriptive_measure',
         'electric_current_measure',
         'length_measure',
         'luminous_intensity_measure',
         'mass_measure',
         'numeric_measure',
         'non_negative_length_measure',
         'parameter_value',
         'plane_angle_measure',
         'positive_length_measure',
         'positive_plane_angle_measure',
         'positive_ratio_measure',
         'ratio_measure',
         'solid_angle_measure',
         'thermodynamic_temperature_measure',
         'time_measure',
         'volume_measure',
         scope = schema_scope)
Referenced by automotive_design.measure_with_unit.value_component(), and automotive_design.value_representation_item.value_component().
motion_parameter_measure
automotive_design.motion_parameter_measure
Initial value:
 =  SELECT(
         'parameter_value',
         'measure_with_unit',
         scope = schema_scope)
Referenced by automotive_design.configuration_definition.t_parameter().
multi_language_attribute_item
automotive_design.multi_language_attribute_item
name_attribute_select
automotive_design.name_attribute_select
Initial value:
 =  SELECT(
         'action_request_solution',
         'address',
         'configuration_design',
         'context_dependent_shape_representation',
         'derived_unit',
         'effectivity',
         'person_and_organization',
         'product_definition',
         'product_definition_substitute',
         'property_definition_representation',
         scope = schema_scope)
Referenced by automotive_design.name_attribute.named_item().
name_item
automotive_design.name_item
Initial value:
 =  SELECT(
         'kinematic_joint',
         'kinematic_link',
         'kinematic_structure',
         scope = schema_scope)
organization_item
automotive_design.organization_item
organizational_project_item
automotive_design.organizational_project_item
Initial value:
 =  SELECT(
         'assembly_component_usage',
         'configuration_item',
         'executed_action',
         'product',
         'product_concept',
         'product_definition',
         'product_definition_formation',
         scope = schema_scope)
pcurve_or_surface
automotive_design.pcurve_or_surface
Initial value:
 =  SELECT(
         'pcurve',
         'surface',
         scope = schema_scope)
person_and_organization_item
automotive_design.person_and_organization_item
person_organization_select
automotive_design.person_organization_select
Initial value:
 =  SELECT(
         'person',
         'organization',
         'person_and_organization',
         scope = schema_scope)
Referenced by automotive_design.approval_person_organization.person_organization().
person_requires_person_and_organization
automotive_design.person_requires_person_and_organization = Rule()
RULE person_requires_person_and_organization #.
physical_instance_requires_product_definition
automotive_design.physical_instance_requires_product_definition = Rule()
RULE physical_instance_requires_product_definition #.
plane_or_planar_box
automotive_design.plane_or_planar_box
Initial value:
 =  SELECT(
         'plane',
         'planar_box',
         scope = schema_scope)
Referenced by automotive_design.annotation_plane.styled_item_item().
plib_class_reference_requires_version
automotive_design.plib_class_reference_requires_version = Rule()
RULE plib_class_reference_requires_version #.
plib_property_reference_requires_name_scope
automotive_design.plib_property_reference_requires_name_scope = Rule()
RULE plib_property_reference_requires_name_scope #.
plib_property_reference_requires_version
automotive_design.plib_property_reference_requires_version = Rule()
RULE plib_property_reference_requires_version #.
presentation_layer_assignment_constraint_2d_or_3d
automotive_design.presentation_layer_assignment_constraint_2d_or_3d = Rule()
RULE presentation_layer_assignment_constraint_2d_or_3d #.
presentation_representation_select
automotive_design.presentation_representation_select
Initial value:
 =  SELECT(
         'presentation_representation',
         'presentation_set',
         scope = schema_scope)
Referenced by automotive_design.presented_item_representation.presentation().
presentation_size_assignment_select
automotive_design.presentation_size_assignment_select
Initial value:
 =  SELECT(
         'presentation_view',
         'presentation_area',
         'area_in_set',
         scope = schema_scope)
Referenced by automotive_design.presentation_size.unit().
presentation_style_select
automotive_design.presentation_style_select
Initial value:
 =  SELECT(
         'pre_defined_presentation_style',
         'point_style',
         'curve_style',
         'surface_style_usage',
         'symbol_style',
         'fill_area_style',
         'text_style',
         'approximation_tolerance',
         'externally_defined_style',
         'null_style',
         scope = schema_scope)
presentation_view_presented_once
automotive_design.presentation_view_presented_once = Rule()
RULE presentation_view_presented_once #.
presented_item_select
automotive_design.presented_item_select
Initial value:
 =  SELECT(
         'action',
         'action_method',
         'action_relationship',
         'product_concept',
         'product_concept_feature',
         'product_concept_feature_category',
         'product_definition',
         'product_definition_formation',
         'product_definition_relationship',
         scope = schema_scope)
product_concept_feature_requires_category
automotive_design.product_concept_feature_requires_category = Rule()
RULE product_concept_feature_requires_category #.
product_definition_replacement_requires_effectivity_assignment
automotive_design.product_definition_replacement_requires_effectivity_assignment = Rule()
RULE product_definition_replacement_requires_effectivity_assignment #.
product_or_formation_or_definition
automotive_design.product_or_formation_or_definition
Initial value:
 =  SELECT(
         'product',
         'product_definition_formation',
         'product_definition',
         scope = schema_scope)
Referenced by automotive_design.document_product_association.related_product().
product_requires_category
automotive_design.product_requires_category = Rule()
RULE product_requires_category #.
product_requires_id_owner
automotive_design.product_requires_id_owner = Rule()
RULE product_requires_id_owner #.
product_requires_version
automotive_design.product_requires_version = Rule()
RULE product_requires_version #.
property_or_shape_select
automotive_design.property_or_shape_select
Initial value:
 =  SELECT(
         'property_definition',
         'shape_definition',
         scope = schema_scope)
Referenced by automotive_design.process_property_association.property_or_shape().
rendering_properties_select
automotive_design.rendering_properties_select
Initial value:
 =  SELECT(
         'surface_style_reflectance_ambient',
         'surface_style_transparent',
         scope = schema_scope)
represented_definition
automotive_design.represented_definition
Initial value:
 =  SELECT(
         'general_property',
         'property_definition',
         'property_definition_relationship',
         'shape_aspect',
         'shape_aspect_relationship',
         scope = schema_scope)
Referenced by automotive_design.item_identified_representation_usage.definition(), and automotive_design.property_definition_representation.definition().
restrict_action_resource_requirement_for_process_operation
automotive_design.restrict_action_resource_requirement_for_process_operation = Rule()
RULE restrict_action_resource_requirement_for_process_operation #.
restrict_alternative_definition
automotive_design.restrict_alternative_definition = Rule()
RULE restrict_alternative_definition #.
restrict_applied_action_assignment
automotive_design.restrict_applied_action_assignment = Rule()
RULE restrict_applied_action_assignment #.
restrict_applied_action_request_assignment
automotive_design.restrict_applied_action_request_assignment = Rule()
RULE restrict_applied_action_request_assignment #.
restrict_applied_classification_assignment_role
automotive_design.restrict_applied_classification_assignment_role = Rule()
RULE restrict_applied_classification_assignment_role #.
restrict_applied_event_occurrence_assignment
automotive_design.restrict_applied_event_occurrence_assignment = Rule()
RULE restrict_applied_event_occurrence_assignment #.
restrict_applied_organizational_project_assignment
automotive_design.restrict_applied_organizational_project_assignment = Rule()
RULE restrict_applied_organizational_project_assignment #.
restrict_approval
automotive_design.restrict_approval = Rule()
RULE restrict_approval #.
restrict_camera_image_in_view
automotive_design.restrict_camera_image_in_view = Rule()
RULE restrict_camera_image_in_view #.
restrict_centre_of_mass_representation
automotive_design.restrict_centre_of_mass_representation = Rule()
RULE restrict_centre_of_mass_representation #.
restrict_class_system_assignment_for_approval_status
automotive_design.restrict_class_system_assignment_for_approval_status = Rule()
RULE restrict_class_system_assignment_for_approval_status #.
restrict_class_system_assignment_for_class
automotive_design.restrict_class_system_assignment_for_class = Rule()
RULE restrict_class_system_assignment_for_class #.
restrict_class_system_assignment_for_descriptive_representation_item
automotive_design.restrict_class_system_assignment_for_descriptive_representation_item = Rule()
RULE restrict_class_system_assignment_for_descriptive_representation_item #.
restrict_class_system_assignment_for_document_type
automotive_design.restrict_class_system_assignment_for_document_type = Rule()
RULE restrict_class_system_assignment_for_document_type #.
restrict_class_system_assignment_for_security_classification_level
automotive_design.restrict_class_system_assignment_for_security_classification_level = Rule()
RULE restrict_class_system_assignment_for_security_classification_level #.
restrict_concept_feature_operator
automotive_design.restrict_concept_feature_operator = Rule()
RULE restrict_concept_feature_operator #.
restrict_configuration_design_for_product_class
automotive_design.restrict_configuration_design_for_product_class = Rule()
RULE restrict_configuration_design_for_product_class #.
restrict_default_settings
automotive_design.restrict_default_settings = Rule()
RULE restrict_default_settings #.
restrict_default_thickness
automotive_design.restrict_default_thickness = Rule()
RULE restrict_default_thickness #.
restrict_drawing
automotive_design.restrict_drawing = Rule()
RULE restrict_drawing #.
restrict_effectivity_assignment_for_class_category_usage
automotive_design.restrict_effectivity_assignment_for_class_category_usage = Rule()
RULE restrict_effectivity_assignment_for_class_category_usage #.
restrict_effectivity_for_effectivity_relationship
automotive_design.restrict_effectivity_for_effectivity_relationship = Rule()
RULE restrict_effectivity_for_effectivity_relationship #.
restrict_effectivity_usage
automotive_design.restrict_effectivity_usage = Rule()
RULE restrict_effectivity_usage #.
restrict_externally_defined_item_relationship
automotive_design.restrict_externally_defined_item_relationship = Rule()
RULE restrict_externally_defined_item_relationship #.
restrict_group_relationship_for_general_classification_hierarchy
automotive_design.restrict_group_relationship_for_general_classification_hierarchy = Rule()
RULE restrict_group_relationship_for_general_classification_hierarchy #.
restrict_group_relationship_for_specification_category
automotive_design.restrict_group_relationship_for_specification_category = Rule()
RULE restrict_group_relationship_for_specification_category #.
restrict_multi_language_for_action
automotive_design.restrict_multi_language_for_action = Rule()
RULE restrict_multi_language_for_action #.
restrict_multi_language_for_action_directive
automotive_design.restrict_multi_language_for_action_directive = Rule()
RULE restrict_multi_language_for_action_directive #.
restrict_multi_language_for_action_method
automotive_design.restrict_multi_language_for_action_method = Rule()
RULE restrict_multi_language_for_action_method #.
restrict_multi_language_for_action_property
automotive_design.restrict_multi_language_for_action_property = Rule()
RULE restrict_multi_language_for_action_property #.
restrict_multi_language_for_action_relationship
automotive_design.restrict_multi_language_for_action_relationship = Rule()
RULE restrict_multi_language_for_action_relationship #.
restrict_multi_language_for_alternate_product_relationship
automotive_design.restrict_multi_language_for_alternate_product_relationship = Rule()
RULE restrict_multi_language_for_alternate_product_relationship #.
restrict_multi_language_for_application_context
automotive_design.restrict_multi_language_for_application_context = Rule()
RULE restrict_multi_language_for_application_context #.
restrict_multi_language_for_approval_relationship
automotive_design.restrict_multi_language_for_approval_relationship = Rule()
RULE restrict_multi_language_for_approval_relationship #.
restrict_multi_language_for_assembly_component_usage_substitute
automotive_design.restrict_multi_language_for_assembly_component_usage_substitute = Rule()
RULE restrict_multi_language_for_assembly_component_usage_substitute #.
restrict_multi_language_for_certification
automotive_design.restrict_multi_language_for_certification = Rule()
RULE restrict_multi_language_for_certification #.
restrict_multi_language_for_configuration_design
automotive_design.restrict_multi_language_for_configuration_design = Rule()
RULE restrict_multi_language_for_configuration_design #.
restrict_multi_language_for_configuration_item
automotive_design.restrict_multi_language_for_configuration_item = Rule()
RULE restrict_multi_language_for_configuration_item #.
restrict_multi_language_for_contract
automotive_design.restrict_multi_language_for_contract = Rule()
RULE restrict_multi_language_for_contract #.
restrict_multi_language_for_data_environment
automotive_design.restrict_multi_language_for_data_environment = Rule()
RULE restrict_multi_language_for_data_environment #.
restrict_multi_language_for_date_role
automotive_design.restrict_multi_language_for_date_role = Rule()
RULE restrict_multi_language_for_date_role #.
restrict_multi_language_for_date_time_role
automotive_design.restrict_multi_language_for_date_time_role = Rule()
RULE restrict_multi_language_for_date_time_role #.
restrict_multi_language_for_descriptive_representation_item
automotive_design.restrict_multi_language_for_descriptive_representation_item = Rule()
RULE restrict_multi_language_for_descriptive_representation_item #.
restrict_multi_language_for_document_relationship
automotive_design.restrict_multi_language_for_document_relationship = Rule()
RULE restrict_multi_language_for_document_relationship #.
restrict_multi_language_for_draughting_title
automotive_design.restrict_multi_language_for_draughting_title = Rule()
RULE restrict_multi_language_for_draughting_title #.
restrict_multi_language_for_effectivity
automotive_design.restrict_multi_language_for_effectivity = Rule()
RULE restrict_multi_language_for_effectivity #.
restrict_multi_language_for_effectivity_relationship
automotive_design.restrict_multi_language_for_effectivity_relationship = Rule()
RULE restrict_multi_language_for_effectivity_relationship #.
restrict_multi_language_for_event_occurrence
automotive_design.restrict_multi_language_for_event_occurrence = Rule()
RULE restrict_multi_language_for_event_occurrence #.
restrict_multi_language_for_external_source
automotive_design.restrict_multi_language_for_external_source = Rule()
RULE restrict_multi_language_for_external_source #.
restrict_multi_language_for_general_property
automotive_design.restrict_multi_language_for_general_property = Rule()
RULE restrict_multi_language_for_general_property #.
restrict_multi_language_for_general_property_relationship
automotive_design.restrict_multi_language_for_general_property_relationship = Rule()
RULE restrict_multi_language_for_general_property_relationship #.
restrict_multi_language_for_geometric_representation_item
automotive_design.restrict_multi_language_for_geometric_representation_item = Rule()
RULE restrict_multi_language_for_geometric_representation_item #.
restrict_multi_language_for_geometric_tolerance
automotive_design.restrict_multi_language_for_geometric_tolerance = Rule()
RULE restrict_multi_language_for_geometric_tolerance #.
restrict_multi_language_for_group
automotive_design.restrict_multi_language_for_group = Rule()
RULE restrict_multi_language_for_group #.
restrict_multi_language_for_group_relationship
automotive_design.restrict_multi_language_for_group_relationship = Rule()
RULE restrict_multi_language_for_group_relationship #.
restrict_multi_language_for_identification_role
automotive_design.restrict_multi_language_for_identification_role = Rule()
RULE restrict_multi_language_for_identification_role #.
restrict_multi_language_for_kinematic_pair
automotive_design.restrict_multi_language_for_kinematic_pair = Rule()
RULE restrict_multi_language_for_kinematic_pair #.
restrict_multi_language_for_mapped_item
automotive_design.restrict_multi_language_for_mapped_item = Rule()
RULE restrict_multi_language_for_mapped_item #.
restrict_multi_language_for_name_assignment
automotive_design.restrict_multi_language_for_name_assignment = Rule()
RULE restrict_multi_language_for_name_assignment #.
restrict_multi_language_for_organization_relationship
automotive_design.restrict_multi_language_for_organization_relationship = Rule()
RULE restrict_multi_language_for_organization_relationship #.
restrict_multi_language_for_organization_role
automotive_design.restrict_multi_language_for_organization_role = Rule()
RULE restrict_multi_language_for_organization_role #.
restrict_multi_language_for_organizational_project
automotive_design.restrict_multi_language_for_organizational_project = Rule()
RULE restrict_multi_language_for_organizational_project #.
restrict_multi_language_for_organizational_project_relationship
automotive_design.restrict_multi_language_for_organizational_project_relationship = Rule()
RULE restrict_multi_language_for_organizational_project_relationship #.
restrict_multi_language_for_pair_actuator
automotive_design.restrict_multi_language_for_pair_actuator = Rule()
RULE restrict_multi_language_for_pair_actuator #.
restrict_multi_language_for_person_and_organization_role
automotive_design.restrict_multi_language_for_person_and_organization_role = Rule()
RULE restrict_multi_language_for_person_and_organization_role #.
restrict_multi_language_for_presentation_layer_assignment
automotive_design.restrict_multi_language_for_presentation_layer_assignment = Rule()
RULE restrict_multi_language_for_presentation_layer_assignment #.
restrict_multi_language_for_process_product_association
automotive_design.restrict_multi_language_for_process_product_association = Rule()
RULE restrict_multi_language_for_process_product_association #.
restrict_multi_language_for_product
automotive_design.restrict_multi_language_for_product = Rule()
RULE restrict_multi_language_for_product #.
restrict_multi_language_for_product_concept
automotive_design.restrict_multi_language_for_product_concept = Rule()
RULE restrict_multi_language_for_product_concept #.
restrict_multi_language_for_product_concept_feature
automotive_design.restrict_multi_language_for_product_concept_feature = Rule()
RULE restrict_multi_language_for_product_concept_feature #.
restrict_multi_language_for_product_concept_feature_association
automotive_design.restrict_multi_language_for_product_concept_feature_association = Rule()
RULE restrict_multi_language_for_product_concept_feature_association #.
restrict_multi_language_for_product_concept_relationship
automotive_design.restrict_multi_language_for_product_concept_relationship = Rule()
RULE restrict_multi_language_for_product_concept_relationship #.
restrict_multi_language_for_product_definition
automotive_design.restrict_multi_language_for_product_definition = Rule()
RULE restrict_multi_language_for_product_definition #.
restrict_multi_language_for_product_definition_formation
automotive_design.restrict_multi_language_for_product_definition_formation = Rule()
RULE restrict_multi_language_for_product_definition_formation #.
restrict_multi_language_for_product_definition_formation_relationship
automotive_design.restrict_multi_language_for_product_definition_formation_relationship = Rule()
RULE restrict_multi_language_for_product_definition_formation_relationship #.
restrict_multi_language_for_product_definition_relationship
automotive_design.restrict_multi_language_for_product_definition_relationship = Rule()
RULE restrict_multi_language_for_product_definition_relationship #.
restrict_multi_language_for_product_definition_substitute
automotive_design.restrict_multi_language_for_product_definition_substitute = Rule()
RULE restrict_multi_language_for_product_definition_substitute #.
restrict_multi_language_for_product_related_product_category
automotive_design.restrict_multi_language_for_product_related_product_category = Rule()
RULE restrict_multi_language_for_product_related_product_category #.
restrict_multi_language_for_property_definition
automotive_design.restrict_multi_language_for_property_definition = Rule()
RULE restrict_multi_language_for_property_definition #.
restrict_multi_language_for_property_definition_relationship
automotive_design.restrict_multi_language_for_property_definition_relationship = Rule()
RULE restrict_multi_language_for_property_definition_relationship #.
restrict_multi_language_for_representation
automotive_design.restrict_multi_language_for_representation = Rule()
RULE restrict_multi_language_for_representation #.
restrict_multi_language_for_representation_relationship
automotive_design.restrict_multi_language_for_representation_relationship = Rule()
RULE restrict_multi_language_for_representation_relationship #.
restrict_multi_language_for_requirement_for_action_resource
automotive_design.restrict_multi_language_for_requirement_for_action_resource = Rule()
RULE restrict_multi_language_for_requirement_for_action_resource #.
restrict_multi_language_for_resource_property
automotive_design.restrict_multi_language_for_resource_property = Rule()
RULE restrict_multi_language_for_resource_property #.
restrict_multi_language_for_resource_requirement_type
automotive_design.restrict_multi_language_for_resource_requirement_type = Rule()
RULE restrict_multi_language_for_resource_requirement_type #.
restrict_multi_language_for_security_classification
automotive_design.restrict_multi_language_for_security_classification = Rule()
RULE restrict_multi_language_for_security_classification #.
restrict_multi_language_for_shape_aspect
automotive_design.restrict_multi_language_for_shape_aspect = Rule()
RULE restrict_multi_language_for_shape_aspect #.
restrict_multi_language_for_shape_aspect_relationship
automotive_design.restrict_multi_language_for_shape_aspect_relationship = Rule()
RULE restrict_multi_language_for_shape_aspect_relationship #.
restrict_multi_language_for_styled_item
automotive_design.restrict_multi_language_for_styled_item = Rule()
RULE restrict_multi_language_for_styled_item #.
restrict_multi_language_for_time_interval_role
automotive_design.restrict_multi_language_for_time_interval_role = Rule()
RULE restrict_multi_language_for_time_interval_role #.
restrict_multi_language_for_topological_representation_item
automotive_design.restrict_multi_language_for_topological_representation_item = Rule()
RULE restrict_multi_language_for_topological_representation_item #.
restrict_multi_language_for_uncertainty_measure_with_unit
automotive_design.restrict_multi_language_for_uncertainty_measure_with_unit = Rule()
RULE restrict_multi_language_for_uncertainty_measure_with_unit #.
restrict_multi_language_for_uncertainty_qualifier
automotive_design.restrict_multi_language_for_uncertainty_qualifier = Rule()
RULE restrict_multi_language_for_uncertainty_qualifier #.
restrict_multi_language_for_versioned_action_request
automotive_design.restrict_multi_language_for_versioned_action_request = Rule()
RULE restrict_multi_language_for_versioned_action_request #.
restrict_multi_language_for_versioned_action_request_relationship
automotive_design.restrict_multi_language_for_versioned_action_request_relationship = Rule()
RULE restrict_multi_language_for_versioned_action_request_relationship #.
restrict_name_assignment_for_kinematic_joint
automotive_design.restrict_name_assignment_for_kinematic_joint = Rule()
RULE restrict_name_assignment_for_kinematic_joint #.
restrict_name_assignment_for_kinematic_link
automotive_design.restrict_name_assignment_for_kinematic_link = Rule()
RULE restrict_name_assignment_for_kinematic_link #.
restrict_name_assignment_for_kinematic_structure
automotive_design.restrict_name_assignment_for_kinematic_structure = Rule()
RULE restrict_name_assignment_for_kinematic_structure #.
restrict_name_for_known_source
automotive_design.restrict_name_for_known_source = Rule()
RULE restrict_name_for_known_source #.
restrict_part_occurrence
automotive_design.restrict_part_occurrence = Rule()
RULE restrict_part_occurrence #.
restrict_process_product_association
automotive_design.restrict_process_product_association = Rule()
RULE restrict_process_product_association #.
restrict_product_categories_for_tool_part_relationship
automotive_design.restrict_product_categories_for_tool_part_relationship = Rule()
RULE restrict_product_categories_for_tool_part_relationship #.
restrict_product_category_for_product
automotive_design.restrict_product_category_for_product = Rule()
RULE restrict_product_category_for_product #.
restrict_product_definition_context_for_external_properties
automotive_design.restrict_product_definition_context_for_external_properties = Rule()
RULE restrict_product_definition_context_for_external_properties #.
restrict_product_definition_context_for_product
automotive_design.restrict_product_definition_context_for_product = Rule()
RULE restrict_product_definition_context_for_product #.
restrict_product_definition_for_mating_tree
automotive_design.restrict_product_definition_for_mating_tree = Rule()
RULE restrict_product_definition_for_mating_tree #.
restrict_product_definition_substitute
automotive_design.restrict_product_definition_substitute = Rule()
RULE restrict_product_definition_substitute #.
restrict_product_definitions_for_product_definition_relationship
automotive_design.restrict_product_definitions_for_product_definition_relationship = Rule()
RULE restrict_product_definitions_for_product_definition_relationship #.
restrict_properties_of_document_file
automotive_design.restrict_properties_of_document_file = Rule()
RULE restrict_properties_of_document_file #.
restrict_properties_of_document_representation
automotive_design.restrict_properties_of_document_representation = Rule()
RULE restrict_properties_of_document_representation #.
restrict_representation_for_document_content_property
automotive_design.restrict_representation_for_document_content_property = Rule()
RULE restrict_representation_for_document_content_property #.
restrict_representation_for_document_creation_property
automotive_design.restrict_representation_for_document_creation_property = Rule()
RULE restrict_representation_for_document_creation_property #.
restrict_representation_for_document_format_property
automotive_design.restrict_representation_for_document_format_property = Rule()
RULE restrict_representation_for_document_format_property #.
restrict_representation_for_document_properties
automotive_design.restrict_representation_for_document_properties = Rule()
RULE restrict_representation_for_document_properties #.
restrict_representation_for_document_size_property
automotive_design.restrict_representation_for_document_size_property = Rule()
RULE restrict_representation_for_document_size_property #.
restrict_representation_for_surface_condition
automotive_design.restrict_representation_for_surface_condition = Rule()
RULE restrict_representation_for_surface_condition #.
restrict_representation_item_for_hybrid_geometric_model_3d
automotive_design.restrict_representation_item_for_hybrid_geometric_model_3d = Rule()
RULE restrict_representation_item_for_hybrid_geometric_model_3d #.
restrict_treatment_result
automotive_design.restrict_treatment_result = Rule()
RULE restrict_treatment_result #.
restrict_version_assignment_for_action
automotive_design.restrict_version_assignment_for_action = Rule()
RULE restrict_version_assignment_for_action #.
restrict_version_assignment_for_action_directive
automotive_design.restrict_version_assignment_for_action_directive = Rule()
RULE restrict_version_assignment_for_action_directive #.
restrict_version_assignment_for_action_method
automotive_design.restrict_version_assignment_for_action_method = Rule()
RULE restrict_version_assignment_for_action_method #.
restrict_version_assignment_for_applied_identification_assignment
automotive_design.restrict_version_assignment_for_applied_identification_assignment = Rule()
RULE restrict_version_assignment_for_applied_identification_assignment #.
restrict_version_assignment_for_class
automotive_design.restrict_version_assignment_for_class = Rule()
RULE restrict_version_assignment_for_class #.
restrict_version_assignment_for_configuration_item
automotive_design.restrict_version_assignment_for_configuration_item = Rule()
RULE restrict_version_assignment_for_configuration_item #.
restrict_version_assignment_for_document_file
automotive_design.restrict_version_assignment_for_document_file = Rule()
RULE restrict_version_assignment_for_document_file #.
restrict_version_assignment_for_draughting_model
automotive_design.restrict_version_assignment_for_draughting_model = Rule()
RULE restrict_version_assignment_for_draughting_model #.
restrict_version_assignment_for_effectivity
automotive_design.restrict_version_assignment_for_effectivity = Rule()
RULE restrict_version_assignment_for_effectivity #.
restrict_version_assignment_for_general_property
automotive_design.restrict_version_assignment_for_general_property = Rule()
RULE restrict_version_assignment_for_general_property #.
restrict_version_assignment_for_mechanical_design_geometric_presentation_representation
automotive_design.restrict_version_assignment_for_mechanical_design_geometric_presentation_representation = Rule()
RULE restrict_version_assignment_for_mechanical_design_geometric_presentation_representation #.
restrict_version_assignment_for_presentation_area
automotive_design.restrict_version_assignment_for_presentation_area = Rule()
RULE restrict_version_assignment_for_presentation_area #.
restrict_version_assignment_for_product_concept
automotive_design.restrict_version_assignment_for_product_concept = Rule()
RULE restrict_version_assignment_for_product_concept #.
restrict_version_assignment_for_product_concept_feature
automotive_design.restrict_version_assignment_for_product_concept_feature = Rule()
RULE restrict_version_assignment_for_product_concept_feature #.
restrict_version_assignment_for_shape_representation
automotive_design.restrict_version_assignment_for_shape_representation = Rule()
RULE restrict_version_assignment_for_shape_representation #.
restrict_viewing_plane_usage
automotive_design.restrict_viewing_plane_usage = Rule()
RULE restrict_viewing_plane_usage #.
restrict_zone_boundary
automotive_design.restrict_zone_boundary = Rule()
RULE restrict_zone_boundary #.
retention_requires_retention_assignment
automotive_design.retention_requires_retention_assignment = Rule()
RULE retention_requires_retention_assignment #.
reversible_topology
automotive_design.reversible_topology
Initial value:
 =  SELECT(
         'reversible_topology_item',
         'list_of_reversible_topology_item',
         'set_of_reversible_topology_item',
         scope = schema_scope)
reversible_topology_item
automotive_design.reversible_topology_item
Initial value:
 =  SELECT(
         'edge',
         'path',
         'face',
         'face_bound',
         'closed_shell',
         'open_shell',
         scope = schema_scope)
rigid_placement
automotive_design.rigid_placement
Initial value:
 =  SELECT(
         'axis2_placement_3d',
         scope = schema_scope)
Referenced by automotive_design.motion_link_relationship.related_frame(), and automotive_design.kinematic_frame_based_transformation.transformator().
role_select
automotive_design.role_select
Initial value:
 =  SELECT(
         'action_assignment',
         'action_request_assignment',
         'approval_assignment',
         'approval_date_time',
         'certification_assignment',
         'contract_assignment',
         'document_reference',
         'effectivity_assignment',
         'group_assignment',
         'name_assignment',
         'security_classification_assignment',
         scope = schema_scope)
Referenced by automotive_design.role_association.item_with_role().
rotational_range_measure
automotive_design.rotational_range_measure
Initial value:
 =  SELECT(
         'plane_angle_measure',
         'unlimited_range',
         scope = schema_scope)
Referenced by automotive_design.planar_pair_range.lower_limit_actual_rotation(), automotive_design.cylindrical_pair_range.lower_limit_actual_rotation(), automotive_design.screw_pair_range.lower_limit_actual_rotation(), automotive_design.surface_pair_range.lower_limit_actual_rotation(), automotive_design.revolute_pair_range.lower_limit_actual_rotation(), automotive_design.gear_pair_range.lower_limit_actual_rotation_1(), automotive_design.universal_pair_range.lower_limit_first_rotation(), automotive_design.point_on_planar_curve_pair_range.lower_limit_pitch(), automotive_design.spherical_pair_range.lower_limit_pitch(), automotive_design.point_on_surface_pair_range.lower_limit_pitch(), automotive_design.point_on_planar_curve_pair_range.lower_limit_roll(), automotive_design.spherical_pair_range.lower_limit_roll(), automotive_design.point_on_surface_pair_range.lower_limit_roll(), automotive_design.universal_pair_range.lower_limit_second_rotation(), automotive_design.point_on_planar_curve_pair_range.lower_limit_yaw(), automotive_design.spherical_pair_range.lower_limit_yaw(), automotive_design.point_on_surface_pair_range.lower_limit_yaw(), automotive_design.planar_pair_range.upper_limit_actual_rotation(), automotive_design.cylindrical_pair_range.upper_limit_actual_rotation(), automotive_design.screw_pair_range.upper_limit_actual_rotation(), automotive_design.surface_pair_range.upper_limit_actual_rotation(), automotive_design.revolute_pair_range.upper_limit_actual_rotation(), automotive_design.gear_pair_range.upper_limit_actual_rotation_1(), automotive_design.universal_pair_range.upper_limit_first_rotation(), automotive_design.point_on_planar_curve_pair_range.upper_limit_pitch(), automotive_design.spherical_pair_range.upper_limit_pitch(), automotive_design.point_on_surface_pair_range.upper_limit_pitch(), automotive_design.point_on_planar_curve_pair_range.upper_limit_roll(), automotive_design.spherical_pair_range.upper_limit_roll(), automotive_design.point_on_surface_pair_range.upper_limit_roll(), automotive_design.universal_pair_range.upper_limit_second_rotation(), automotive_design.point_on_planar_curve_pair_range.upper_limit_yaw(), automotive_design.spherical_pair_range.upper_limit_yaw(), and automotive_design.point_on_surface_pair_range.upper_limit_yaw().
schema_name
string automotive_design.schema_name = 'automotive_design'
schema_scope
automotive_design.schema_scope = sys.modules[__name__]
security_classification_item
automotive_design.security_classification_item
security_classification_requires_security_classification_assignment
automotive_design.security_classification_requires_security_classification_assignment = Rule()
RULE security_classification_requires_security_classification_assignment #.
selected_instance_usage_requires_representation
automotive_design.selected_instance_usage_requires_representation = Rule()
RULE selected_instance_usage_requires_representation #.
set_of_reversible_topology_item
automotive_design.set_of_reversible_topology_item = SET(0,None,'reversible_topology_item', scope = schema_scope)
set_representation_item
automotive_design.set_representation_item = SET(1,None,'representation_item', scope = schema_scope)
shape_definition
automotive_design.shape_definition
Initial value:
 =  SELECT(
         'product_definition_shape',
         'shape_aspect',
         'shape_aspect_relationship',
         scope = schema_scope)
sheets_belong_to_one_drawing
automotive_design.sheets_belong_to_one_drawing = Rule()
RULE sheets_belong_to_one_drawing #.
shell
automotive_design.shell
Initial value:
 =  SELECT(
         'open_shell',
         'closed_shell',
         scope = schema_scope)
size_select
automotive_design.size_select
Initial value:
 =  SELECT(
         'positive_length_measure',
         'measure_with_unit',
         'descriptive_measure',
         scope = schema_scope)
Referenced by automotive_design.curve_style.curve_width(), and automotive_design.point_style.marker_size().
source_item
automotive_design.source_item
Initial value:
 =  SELECT(
         'identifier',
         scope = schema_scope)
Referenced by automotive_design.externally_defined_item.item_id(), and automotive_design.external_source.source_id().
spatial_rotation
automotive_design.spatial_rotation
Initial value:
 =  SELECT(
         'ypr_rotation',
         'rotation_about_direction',
         scope = schema_scope)
Referenced by automotive_design.point_on_surface_pair_value.input_orientation(), automotive_design.spherical_pair_value.input_orientation(), and automotive_design.point_on_planar_curve_pair_value.input_orientation().
specified_item
automotive_design.specified_item
Initial value:
 =  SELECT(
         'drawing_revision',
         scope = schema_scope)
style_context_select
automotive_design.style_context_select
Initial value:
 =  SELECT(
         'group',
         'presentation_layer_assignment',
         'presentation_set',
         'representation',
         'representation_item',
         'shape_representation_relationship',
         scope = schema_scope)
Referenced by automotive_design.presentation_style_by_context.style_context().
styled_curve
automotive_design.styled_curve = Rule()
RULE styled_curve #.
subtype_exclusiveness_action
automotive_design.subtype_exclusiveness_action = Rule()
RULE subtype_exclusiveness_action #.
subtype_exclusiveness_characterized_object
automotive_design.subtype_exclusiveness_characterized_object = Rule()
RULE subtype_exclusiveness_characterized_object #.
subtype_exclusiveness_classification_assignment
automotive_design.subtype_exclusiveness_classification_assignment = Rule()
RULE subtype_exclusiveness_classification_assignment #.
subtype_exclusiveness_colour
automotive_design.subtype_exclusiveness_colour = Rule()
RULE subtype_exclusiveness_colour #.
subtype_exclusiveness_compound_representation_item
automotive_design.subtype_exclusiveness_compound_representation_item = Rule()
RULE subtype_exclusiveness_compound_representation_item #.
subtype_exclusiveness_document_reference
automotive_design.subtype_exclusiveness_document_reference = Rule()
RULE subtype_exclusiveness_document_reference #.
subtype_exclusiveness_effectivity
automotive_design.subtype_exclusiveness_effectivity = Rule()
RULE subtype_exclusiveness_effectivity #.
subtype_exclusiveness_effectivity_assignment
automotive_design.subtype_exclusiveness_effectivity_assignment = Rule()
RULE subtype_exclusiveness_effectivity_assignment #.
subtype_exclusiveness_effectivity_context_assignment
automotive_design.subtype_exclusiveness_effectivity_context_assignment = Rule()
RULE subtype_exclusiveness_effectivity_context_assignment #.
subtype_exclusiveness_externally_defined_item
automotive_design.subtype_exclusiveness_externally_defined_item = Rule()
RULE subtype_exclusiveness_externally_defined_item #.
subtype_exclusiveness_feature_component_relationship
automotive_design.subtype_exclusiveness_feature_component_relationship = Rule()
RULE subtype_exclusiveness_feature_component_relationship #.
subtype_exclusiveness_feature_definition
automotive_design.subtype_exclusiveness_feature_definition = Rule()
RULE subtype_exclusiveness_feature_definition #.
subtype_exclusiveness_founded_item
automotive_design.subtype_exclusiveness_founded_item = Rule()
RULE subtype_exclusiveness_founded_item #.
subtype_exclusiveness_geometric_tolerance
automotive_design.subtype_exclusiveness_geometric_tolerance = Rule()
RULE subtype_exclusiveness_geometric_tolerance #.
subtype_exclusiveness_group
automotive_design.subtype_exclusiveness_group = Rule()
RULE subtype_exclusiveness_group #.
subtype_exclusiveness_group_assignment
automotive_design.subtype_exclusiveness_group_assignment = Rule()
RULE subtype_exclusiveness_group_assignment #.
subtype_exclusiveness_identification_assignment
automotive_design.subtype_exclusiveness_identification_assignment = Rule()
RULE subtype_exclusiveness_identification_assignment #.
subtype_exclusiveness_mapped_item
automotive_design.subtype_exclusiveness_mapped_item = Rule()
RULE subtype_exclusiveness_mapped_item #.
subtype_exclusiveness_pre_defined_item
automotive_design.subtype_exclusiveness_pre_defined_item = Rule()
RULE subtype_exclusiveness_pre_defined_item #.
subtype_exclusiveness_pre_defined_symbol
automotive_design.subtype_exclusiveness_pre_defined_symbol = Rule()
RULE subtype_exclusiveness_pre_defined_symbol #.
subtype_exclusiveness_presentation_area
automotive_design.subtype_exclusiveness_presentation_area = Rule()
RULE subtype_exclusiveness_presentation_area #.
subtype_exclusiveness_presentation_representation
automotive_design.subtype_exclusiveness_presentation_representation = Rule()
RULE subtype_exclusiveness_presentation_representation #.
subtype_exclusiveness_property_definition
automotive_design.subtype_exclusiveness_property_definition = Rule()
RULE subtype_exclusiveness_property_definition #.
subtype_exclusiveness_property_definition_representation
automotive_design.subtype_exclusiveness_property_definition_representation = Rule()
RULE subtype_exclusiveness_property_definition_representation #.
subtype_exclusiveness_replicate_feature
automotive_design.subtype_exclusiveness_replicate_feature = Rule()
RULE subtype_exclusiveness_replicate_feature #.
subtype_exclusiveness_representation
automotive_design.subtype_exclusiveness_representation = Rule()
RULE subtype_exclusiveness_representation #.
subtype_exclusiveness_representation_item
automotive_design.subtype_exclusiveness_representation_item = Rule()
RULE subtype_exclusiveness_representation_item #.
subtype_exclusiveness_representation_map
automotive_design.subtype_exclusiveness_representation_map = Rule()
RULE subtype_exclusiveness_representation_map #.
subtype_exclusiveness_representation_relationship
automotive_design.subtype_exclusiveness_representation_relationship = Rule()
RULE subtype_exclusiveness_representation_relationship #.
subtype_exclusiveness_representation_relationship_with_transformation
automotive_design.subtype_exclusiveness_representation_relationship_with_transformation = Rule()
RULE subtype_exclusiveness_representation_relationship_with_transformation #.
subtype_exclusiveness_shape_aspect
automotive_design.subtype_exclusiveness_shape_aspect = Rule()
RULE subtype_exclusiveness_shape_aspect #.
subtype_exclusiveness_shape_aspect_relationship
automotive_design.subtype_exclusiveness_shape_aspect_relationship = Rule()
RULE subtype_exclusiveness_shape_aspect_relationship #.
subtype_exclusiveness_shape_representation_feature_geometry
automotive_design.subtype_exclusiveness_shape_representation_feature_geometry = Rule()
RULE subtype_exclusiveness_shape_representation_feature_geometry #.
subtype_exclusiveness_shape_representation_geometry
automotive_design.subtype_exclusiveness_shape_representation_geometry = Rule()
RULE subtype_exclusiveness_shape_representation_geometry #.
subtype_exclusiveness_symbol_representation
automotive_design.subtype_exclusiveness_symbol_representation = Rule()
RULE subtype_exclusiveness_symbol_representation #.
subtype_exclusiveness_transition_feature
automotive_design.subtype_exclusiveness_transition_feature = Rule()
RULE subtype_exclusiveness_transition_feature #.
subtype_mandatory_address
automotive_design.subtype_mandatory_address = Rule()
RULE subtype_mandatory_address #.
subtype_mandatory_annotation_occurrence
automotive_design.subtype_mandatory_annotation_occurrence = Rule()
RULE subtype_mandatory_annotation_occurrence #.
subtype_mandatory_camera_image
automotive_design.subtype_mandatory_camera_image = Rule()
RULE subtype_mandatory_camera_image #.
subtype_mandatory_camera_model
automotive_design.subtype_mandatory_camera_model = Rule()
RULE subtype_mandatory_camera_model #.
subtype_mandatory_colour_specification
automotive_design.subtype_mandatory_colour_specification = Rule()
RULE subtype_mandatory_colour_specification #.
subtype_mandatory_configurable_item
automotive_design.subtype_mandatory_configurable_item = Rule()
RULE subtype_mandatory_configurable_item #.
subtype_mandatory_document_product_association
automotive_design.subtype_mandatory_document_product_association = Rule()
RULE subtype_mandatory_document_product_association #.
subtype_mandatory_draughting_callout
automotive_design.subtype_mandatory_draughting_callout = Rule()
RULE subtype_mandatory_draughting_callout #.
subtype_mandatory_externally_defined_item
automotive_design.subtype_mandatory_externally_defined_item = Rule()
RULE subtype_mandatory_externally_defined_item #.
subtype_mandatory_founded_item
automotive_design.subtype_mandatory_founded_item = Rule()
RULE subtype_mandatory_founded_item #.
subtype_mandatory_geometric_tolerance
automotive_design.subtype_mandatory_geometric_tolerance = Rule()
RULE subtype_mandatory_geometric_tolerance #.
subtype_mandatory_pre_defined_colour
automotive_design.subtype_mandatory_pre_defined_colour = Rule()
RULE subtype_mandatory_pre_defined_colour #.
subtype_mandatory_pre_defined_curve_font
automotive_design.subtype_mandatory_pre_defined_curve_font = Rule()
RULE subtype_mandatory_pre_defined_curve_font #.
subtype_mandatory_pre_defined_item
automotive_design.subtype_mandatory_pre_defined_item = Rule()
RULE subtype_mandatory_pre_defined_item #.
subtype_mandatory_pre_defined_symbol
automotive_design.subtype_mandatory_pre_defined_symbol = Rule()
RULE subtype_mandatory_pre_defined_symbol #.
subtype_mandatory_pre_defined_text_font
automotive_design.subtype_mandatory_pre_defined_text_font = Rule()
RULE subtype_mandatory_pre_defined_text_font #.
supported_item
automotive_design.supported_item
Initial value:
 =  SELECT(
         'action_directive',
         'action',
         'action_method',
         scope = schema_scope)
surface_side_style_select
automotive_design.surface_side_style_select
Initial value:
 =  SELECT(
         'surface_side_style',
         scope = schema_scope)
Referenced by automotive_design.surface_style_usage.style().
surface_style_element_select
automotive_design.surface_style_element_select
Initial value:
 =  SELECT(
         'surface_style_fill_area',
         'surface_style_boundary',
         'surface_style_silhouette',
         'surface_style_segmentation_curve',
         'surface_style_control_grid',
         'surface_style_parameter_line',
         'surface_style_rendering',
         scope = schema_scope)
symbol_style_select
automotive_design.symbol_style_select
Initial value:
 =  SELECT(
         'symbol_colour',
         scope = schema_scope)
Referenced by automotive_design.symbol_style.style_of_symbol().
terminator_symbol_constraint
automotive_design.terminator_symbol_constraint = Rule()
RULE terminator_symbol_constraint #.
text_font_usage
automotive_design.text_font_usage = Rule()
RULE text_font_usage #.
text_or_character
automotive_design.text_or_character
Initial value:
 =  SELECT(
         'annotation_text',
         'annotation_text_character',
         'defined_character_glyph',
         'composite_text',
         'text_literal',
         scope = schema_scope)
text_string_representation_item
automotive_design.text_string_representation_item
Initial value:
 =  SELECT(
         'text_literal',
         'annotation_text',
         'annotation_text_character',
         'defined_character_glyph',
         'composite_text',
         'axis2_placement',
         scope = schema_scope)
time_interval_item
automotive_design.time_interval_item
tolerance_deviation_select
automotive_design.tolerance_deviation_select
Initial value:
 =  SELECT(
         'curve_tolerance_deviation',
         'surface_tolerance_deviation',
         scope = schema_scope)
tolerance_method_definition
automotive_design.tolerance_method_definition
Initial value:
 =  SELECT(
         'tolerance_value',
         'limits_and_fits',
         scope = schema_scope)
Referenced by automotive_design.plus_minus_tolerance.range().
tolerance_parameter_select
automotive_design.tolerance_parameter_select
Initial value:
 =  SELECT(
         'curve_tolerance_parameter',
         'surface_tolerance_parameter',
         scope = schema_scope)
tolerance_select
automotive_design.tolerance_select
Initial value:
 =  SELECT(
         'approximation_tolerance_deviation',
         'approximation_tolerance_parameter',
         scope = schema_scope)
Referenced by automotive_design.approximation_tolerance.tolerance().
transformation
automotive_design.transformation
Initial value:
 =  SELECT(
         'item_defined_transformation',
         'functionally_defined_transformation',
         scope = schema_scope)
Referenced by automotive_design.representation_relationship_with_transformation.transformation_operator().
translational_range_measure
automotive_design.translational_range_measure
Initial value:
 =  SELECT(
         'length_measure',
         'unlimited_range',
         scope = schema_scope)
Referenced by automotive_design.cylindrical_pair_range.lower_limit_actual_translation(), automotive_design.prismatic_pair_range.lower_limit_actual_translation(), automotive_design.planar_pair_range.lower_limit_actual_translation_x(), automotive_design.planar_pair_range.lower_limit_actual_translation_y(), automotive_design.rack_and_pinion_pair_range.lower_limit_rack_displacement(), automotive_design.cylindrical_pair_range.upper_limit_actual_translation(), automotive_design.prismatic_pair_range.upper_limit_actual_translation(), automotive_design.planar_pair_range.upper_limit_actual_translation_x(), automotive_design.planar_pair_range.upper_limit_actual_translation_y(), and automotive_design.rack_and_pinion_pair_range.upper_limit_rack_displacement().
trimming_select
automotive_design.trimming_select
Initial value:
 =  SELECT(
         'cartesian_point',
         'parameter_value',
         scope = schema_scope)
unit
automotive_design.unit
Initial value:
 =  SELECT(
         'derived_unit',
         'named_unit',
         scope = schema_scope)
Referenced by automotive_design.measure_with_unit.unit_component().
value_qualifier
automotive_design.value_qualifier
Initial value:
 =  SELECT(
         'precision_qualifier',
         'type_qualifier',
         'uncertainty_qualifier',
         scope = schema_scope)
vector_or_direction
automotive_design.vector_or_direction
Initial value:
 =  SELECT(
         'vector',
         'direction',
         scope = schema_scope)
versioned_action_request_requires_date_and_person_or_organization
automotive_design.versioned_action_request_requires_date_and_person_or_organization = Rule()
RULE versioned_action_request_requires_date_and_person_or_organization #.
versioned_action_request_requires_status
automotive_design.versioned_action_request_requires_status = Rule()
RULE versioned_action_request_requires_status #.
ypr_rotation
automotive_design.ypr_rotation = ARRAY(ypr_index(yaw),ypr_index(roll),'REAL', scope = schema_scope)