FreeCAD: SpreadsheetGui::PropertiesDialog Class Reference
SpreadsheetGui::PropertiesDialog Class Reference
#include <PropertiesDialog.h>
Public Member Functions
void apply ()
PropertiesDialog (Spreadsheet::Sheet *_sheet, const std::vector< App::Range > &_ranges, QWidget *parent=nullptr)
void selectAlias ()
~PropertiesDialog ()
Constructor & Destructor Documentation
PropertiesDialog()
PropertiesDialog::PropertiesDialog (Spreadsheet::Sheet * _sheet, const std::vector< App::Range > & _ranges, QWidget * parent = nullptr) explicit
References App::Color::a, Ui_PropertiesDialog::alias, Ui_PropertiesDialog::alignBottom, Ui_PropertiesDialog::alignHCenter, Ui_PropertiesDialog::alignLeft, Ui_PropertiesDialog::alignRight, Ui_PropertiesDialog::alignTop, Ui_PropertiesDialog::alignVCenter, App::Color::b, Ui_PropertiesDialog::backgroundColor, Ui_PropertiesDialog::buttonBox, draftgeoutils.intersections::connect(), Ui_PropertiesDialog::displayUnit, Ui_PropertiesDialog::foregroundColor, Base::Tools::fromStdString(), App::Color::g, Spreadsheet::Cell::getAlias(), Spreadsheet::Cell::getAlignment(), Spreadsheet::Cell::getBackground(), Spreadsheet::Cell::getDisplayUnit(), Spreadsheet::Cell::getForeground(), Spreadsheet::Sheet::getNewCell(), Spreadsheet::Cell::getStyle(), App::Color::r, QtColorPicker::setCurrentColor(), QtColorPicker::setStandardColors(), Ui_PropertiesDialog::setupUi(), Spreadsheet::DisplayUnit::stringRep, Ui_PropertiesDialog::styleBold, Ui_PropertiesDialog::styleItalic, Ui_PropertiesDialog::styleUnderline, and Ui_PropertiesDialog::tabWidget.
~PropertiesDialog()
PropertiesDialog::~PropertiesDialog ()
Member Function Documentation
apply()
void PropertiesDialog::apply (void)
References App::Color::a, Gui::Command::abortCommand(), App::Color::b, Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Gui::Command::Doc, Base::Tools::escapedUnicodeFromUtf8(), App::Color::g, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, App::Color::r, and Spreadsheet::DisplayUnit::stringRep.
selectAlias()
void PropertiesDialog::selectAlias ()
References Ui_PropertiesDialog::alias, and Ui_PropertiesDialog::tabWidget.
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Spreadsheet/Gui/PropertiesDialog.h
FreeCAD/src/Mod/Spreadsheet/Gui/PropertiesDialog.cpp