FreeCAD: DrawSketchHandler3PointCircle Class Reference
DrawSketchHandler3PointCircle Class Reference
Public Types
enum SelectMode { STATUS_SEEK_First, STATUS_SEEK_Second, STATUS_SEEK_Third, STATUS_End }
mode table
Public Member Functions
virtual void activated (ViewProviderSketch *)
DrawSketchHandler3PointCircle ()
virtual void mouseMove (Base::Vector2d onSketchPos)
virtual bool pressButton (Base::Vector2d onSketchPos)
virtual bool releaseButton (Base::Vector2d onSketchPos)
virtual ~DrawSketchHandler3PointCircle ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::none, bool createowncommand=true)
virtual void deactivated (ViewProviderSketch *)
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual void quit (void)
virtual void registerPressedKey (bool, int)
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Attributes
Base::Vector2d CenterPoint
std::vector< Base::Vector2d > EditCurve
Base::Vector2d FirstPoint
SelectMode Mode
double N
double radius
Base::Vector2d SecondPoint
std::vector< AutoConstraint > sugConstr1
std::vector< AutoConstraint > sugConstr2
std::vector< AutoConstraint > sugConstr3
Protected Attributes inherited from SketcherGui::DrawSketchHandler
QCursor actCursor
QPixmap actCursorPixmap
QCursor oldCursor
ViewProviderSketch * sketchgui
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
void addCursorTail (std::vector< QPixmap > &pixmaps)
void applyCursor (QCursor &newCursor)
void applyCursor (void)
qreal devicePixelRatio ()
unsigned long getCrosshairColor ()
void setCrosshairColor ()
void setCrosshairCursor (const char *svgName)
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
Sets a cursor for 3D inventor view.
void setSvgCursor (const QString &svgName, int x, int y, const std::map< unsigned long, unsigned long > &colorMapping=std::map< unsigned long, unsigned long >())
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
void unsetCursor (void)
Member Enumeration Documentation
SelectMode
enum DrawSketchHandler3PointCircle::SelectMode
mode table
Enumerator
STATUS_SEEK_First
enum value -—.
STATUS_SEEK_Second
enum value -—.
STATUS_SEEK_Third
enum value -—.
STATUS_End
Constructor & Destructor Documentation
DrawSketchHandler3PointCircle()
DrawSketchHandler3PointCircle::DrawSketchHandler3PointCircle ()
~DrawSketchHandler3PointCircle()
virtual DrawSketchHandler3PointCircle::~DrawSketchHandler3PointCircle () virtual
Member Function Documentation
activated()
virtual void DrawSketchHandler3PointCircle::activated (ViewProviderSketch *) virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::setCrosshairCursor().
mouseMove()
virtual void DrawSketchHandler3PointCircle::mouseMove (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::applyCursor(), CenterPoint, SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, FirstPoint, Mode, N, radius, SketcherGui::DrawSketchHandler::renderSuggestConstraintsCursor(), SecondPoint, SketcherGui::DrawSketchHandler::seekAutoConstraint(), SketcherGui::DrawSketchHandler::setPositionText(), SketcherGui::DrawSketchHandler::sketchgui, STATUS_SEEK_First, STATUS_SEEK_Second, STATUS_SEEK_Third, sugConstr1, sugConstr2, sugConstr3, Sketcher::Tangent, Base::Vector2d::x, and Base::Vector2d::y.
pressButton()
virtual bool DrawSketchHandler3PointCircle::pressButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::applyCursor(), SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, FirstPoint, Mode, SecondPoint, SketcherGui::DrawSketchHandler::sketchgui, STATUS_End, STATUS_SEEK_First, STATUS_SEEK_Second, and STATUS_SEEK_Third.
releaseButton()
virtual bool DrawSketchHandler3PointCircle::releaseButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), SketcherGui::DrawSketchHandler::applyCursor(), CenterPoint, Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Base::Console(), SketcherGui::DrawSketchHandler::createAutoConstraints(), SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, Base::ConsoleSingleton::Error(), SketcherGui::geometryCreationMode, App::GetApplication(), ParameterGrp::GetBool(), SketcherGui::DrawSketchHandler::getHighestCurveIndex(), Gui::ViewProviderDocumentObject::getObject(), App::Application::GetParameterGroupByPath(), Mode, Sketcher::none, Gui::Command::openCommand(), SketcherGui::ViewProviderSketch::purgeHandler(), draftutils.translate::QT_TRANSLATE_NOOP, radius, SketcherGui::DrawSketchHandler::resetPositionText(), SketcherGui::DrawSketchHandler::sketchgui, STATUS_End, STATUS_SEEK_First, sugConstr1, sugConstr2, sugConstr3, SketcherGui::tryAutoRecomputeIfNotSolve(), SketcherGui::DrawSketchHandler::unsetCursor(), Base::Vector2d::x, and Base::Vector2d::y.
Member Data Documentation
CenterPoint
Base::Vector2d DrawSketchHandler3PointCircle::CenterPoint protected
Referenced by mouseMove(), and releaseButton().
EditCurve
std::vector<Base::Vector2d> DrawSketchHandler3PointCircle::EditCurve protected
Referenced by mouseMove(), pressButton(), and releaseButton().
FirstPoint
Base::Vector2d DrawSketchHandler3PointCircle::FirstPoint protected
Referenced by mouseMove(), and pressButton().
Mode
SelectMode DrawSketchHandler3PointCircle::Mode protected
Referenced by mouseMove(), pressButton(), and releaseButton().
N
double DrawSketchHandler3PointCircle::N protected
Referenced by mouseMove().
radius
double DrawSketchHandler3PointCircle::radius protected
Referenced by mouseMove(), and releaseButton().
SecondPoint
Base::Vector2d DrawSketchHandler3PointCircle::SecondPoint protected
Referenced by mouseMove(), and pressButton().
sugConstr1
std::vector<AutoConstraint> DrawSketchHandler3PointCircle::sugConstr1 protected
Referenced by mouseMove(), and releaseButton().
sugConstr2
std::vector<AutoConstraint> DrawSketchHandler3PointCircle::sugConstr2 protected
Referenced by mouseMove(), and releaseButton().
sugConstr3
std::vector<AutoConstraint> DrawSketchHandler3PointCircle::sugConstr3 protected
Referenced by mouseMove(), and releaseButton().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/Gui/CommandCreateGeo.cpp