FreeCAD: MyIterator< VALUE > Class Template Reference
MyIterator< VALUE > Class Template Reference abstract
Public Member Functions
bool more ()
Return true if and only if there are other object in this iterator.
bool more ()
Return true if and only if there are other object in this iterator.
MyIterator (const set< const SMESHDS_SubMesh * > &theSubMeshes)
MyIterator (SMDSAbs_ElementType type, const SMESHDS_SubMesh *subMesh)
const SMDS_MeshElement * next ()
Return the current object and step to the next one.
VALUE next ()
Return the current object and step to the next one.
Public Member Functions inherited from SMDS_Iterator< const SMDS_MeshElement * >
virtual bool more ()=0
Return true if and only if there are other object in this iterator.
virtual const SMDS_MeshElement * next ()=0
Return the current object and step to the next one.
virtual void remove ()
Delete the current element and step to the next one.
virtual ~SMDS_Iterator ()
Provide virtual destructor just for case if some derived iterator must have a destructor.
Public Member Functions inherited from SMDS_Iterator< VALUE >
virtual bool more ()=0
Return true if and only if there are other object in this iterator.
virtual VALUE next ()=0
Return the current object and step to the next one.
virtual void remove ()
Delete the current element and step to the next one.
virtual ~SMDS_Iterator ()
Provide virtual destructor just for case if some derived iterator must have a destructor.
Protected Member Functions
virtual boost::shared_ptr< SMDS_Iterator< VALUE > > getElements (const SMESHDS_SubMesh *) const =0
Constructor & Destructor Documentation
MyIterator() [1/2]
template<typename VALUE > MyIterator< VALUE >::MyIterator (SMDSAbs_ElementType type, const SMESHDS_SubMesh * subMesh)
References SMESHDS_SubMesh::GetElements(), SMESHDS_SubMesh::GetNodes(), and MyIterator< VALUE >::next().
MyIterator() [2/2]
template<typename VALUE > MyIterator< VALUE >::MyIterator (const set< const SMESHDS_SubMesh * > & theSubMeshes)
Member Function Documentation
getElements()
template<typename VALUE > virtual boost::shared_ptr< SMDS_Iterator< VALUE > > MyIterator< VALUE >::getElements (const SMESHDS_SubMesh *) const protected pure virtual
Implemented in MyElemIterator, and MyNodeIterator.
Referenced by MyIterator< VALUE >::more().
more() [1/2]
template<typename VALUE > bool MyIterator< VALUE >::more () virtual
Return true if and only if there are other object in this iterator.
Implements SMDS_Iterator< VALUE >.
more() [2/2]
template<typename VALUE > bool MyIterator< VALUE >::more () virtual
Return true if and only if there are other object in this iterator.
Implements SMDS_Iterator< VALUE >.
References MyIterator< VALUE >::getElements().
next() [1/2]
template<typename VALUE > const SMDS_MeshElement * MyIterator< VALUE >::next () virtual
Return the current object and step to the next one.
Implements SMDS_Iterator< VALUE >.
References SMDS_MeshElement::GetType().
Referenced by MyIterator< VALUE >::MyIterator().
next() [2/2]
template<typename VALUE > VALUE MyIterator< VALUE >::next () virtual
Return the current object and step to the next one.
Implements SMDS_Iterator< VALUE >.
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/src/SMESHDS/SMESHDS_GroupOnGeom.cpp
FreeCAD/src/3rdParty/salomesmesh/src/SMESHDS/SMESHDS_SubMesh.cpp