FreeCAD: Base::gzstreambase Class Reference
Base::gzstreambase Class Reference
#include <gzstream.h>
Public Member Functions
void close ()
gzstreambase ()
gzstreambase (const char *name, int open_mode, int comp)
void open (const char *name, int open_mode, int comp)
gzstreambuf * rdbuf ()
~gzstreambase ()
Protected Attributes
gzstreambuf buf
Constructor & Destructor Documentation
gzstreambase() [1/2]
Base::gzstreambase::gzstreambase ()
gzstreambase() [2/2]
Base::gzstreambase::gzstreambase (const char * name, int open_mode, int comp)
References open().
~gzstreambase()
Base::gzstreambase::~gzstreambase ()
Member Function Documentation
close()
void Base::gzstreambase::close ()
Referenced by femexamples.examplesgui.FemExamples::reject().
open()
void Base::gzstreambase::open (const char * name, int open_mode, int comp)
Referenced by gzstreambase(), Base::igzstream::open(), and Base::ogzstream::open().
rdbuf()
gzstreambuf* Base::gzstreambase::rdbuf ()
Referenced by Base::igzstream::rdbuf(), and Base::ogzstream::rdbuf().
Member Data Documentation
buf
gzstreambuf Base::gzstreambase::buf protected
Referenced by Dice3DS.dom3ds.FileLikeBuffer::read(), Dice3DS.dom3ds.FileLikeBuffer::read_fbuf(), Dice3DS.dom3ds.FileLikeBuffer::read_rest(), and Dice3DS.dom3ds.FileLikeBuffer::read_to_nul().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Base/gzstream.h
Sources/FreeCAD/src/Base/gzstream.cpp