FreeCAD: PathTests.TestPathToolBit Namespace Reference
PathTests.TestPathToolBit Namespace Reference
Classes
class TestPathToolBit
Functions
def printTree (path, indent)
def testToolBit (path=TestToolDir, name=TestToolBitName)
def testToolLibrary (path=TestToolDir, name=TestToolLibraryName)
def testToolShape (path=TestToolDir, name=TestToolShapeName)
Variables
TestInvalidDir
string TestToolBitName = "test-path-tool-bit-bit-00.fctb"
TestToolDir = os.path.join(os.path.dirname(os.path.realpath(__file__)), "Tools")
string TestToolLibraryName = "test-path-tool-bit-library-00.fctl"
string TestToolShapeName = "test-path-tool-bit-shape-00.fcstd"
Function Documentation
printTree()
def PathTests.TestPathToolBit.printTree (path, indent)
References PathTests.TestPathToolBit.printTree().
Referenced by PathTests.TestPathToolBit.printTree(), and PathTests.TestPathToolBit.TestPathToolBit.test().
testToolBit()
def PathTests.TestPathToolBit.testToolBit (path = TestToolDir, name = TestToolBitName)
Referenced by PathTests.TestPathToolBit.TestPathToolBit.test02(), PathTests.TestPathToolBit.TestPathToolBit.test12(), PathTests.TestPathToolBit.TestPathToolBit.test13(), PathTests.TestPathToolBit.TestPathToolBit.test14(), and PathTests.TestPathToolBit.TestPathToolBit.test24().
testToolLibrary()
def PathTests.TestPathToolBit.testToolLibrary (path = TestToolDir, name = TestToolLibraryName)
Referenced by PathTests.TestPathToolBit.TestPathToolBit.test12(), and PathTests.TestPathToolBit.TestPathToolBit.test23().
testToolShape()
def PathTests.TestPathToolBit.testToolShape (path = TestToolDir, name = TestToolShapeName)
Referenced by PathTests.TestPathToolBit.TestPathToolBit.test02(), PathTests.TestPathToolBit.TestPathToolBit.test03(), and PathTests.TestPathToolBit.TestPathToolBit.test04().
Variable Documentation
TestInvalidDir
PathTests.TestPathToolBit.TestInvalidDir
Initial value:
=  os.path.join(
    TestToolDir, "some", "silly", "path", "that", "should", "not", "exist"
)
TestToolBitName
string PathTests.TestPathToolBit.TestToolBitName = "test-path-tool-bit-bit-00.fctb"
TestToolDir
PathTests.TestPathToolBit.TestToolDir = os.path.join(os.path.dirname(os.path.realpath(__file__)), "Tools")
TestToolLibraryName
string PathTests.TestPathToolBit.TestToolLibraryName = "test-path-tool-bit-library-00.fctl"
TestToolShapeName
string PathTests.TestPathToolBit.TestToolShapeName = "test-path-tool-bit-shape-00.fcstd"