FreeCAD: PartDesignGui::TaskChamferParameters Class Reference
PartDesignGui::TaskChamferParameters Class Reference
#include <TaskChamferParameters.h>
Public Member Functions
virtual void apply ()
Apply the changes made to the object to it.
TaskChamferParameters (ViewProviderDressUp *DressUpView, QWidget *parent=nullptr)
~TaskChamferParameters ()
Public Member Functions inherited from PartDesignGui::TaskDressUpParameters
virtual void apply ()
Apply the changes made to the object to it.
Part::Feature * getBase (void) const
const std::vector< std::string > getReferences (void) const
int getTransactionID () const
void hideObject ()
void setupTransaction ()
void showObject ()
TaskDressUpParameters (ViewProviderDressUp *DressUpView, bool selectEdges, bool selectFaces, QWidget *parent=nullptr)
virtual ~TaskDressUpParameters ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Protected Member Functions
void changeEvent (QEvent *e)
virtual void clearButtons (const selectionModes notThis)
bool event (QEvent *e)
double getAngle (void) const
bool getFlipDirection (void) const
double getSize (void) const
double getSize2 (void) const
int getType (void) const
virtual void onSelectionChanged (const Gui::SelectionChanges &msg)
Protected Member Functions inherited from PartDesignGui::TaskDressUpParameters
void addAllEdges (QListWidget *listWidget)
virtual void clearButtons (const selectionModes notThis)=0
void exitSelectionMode ()
ViewProviderDressUp * getDressUpView () const
void hideOnError ()
bool KeyEvent (QEvent *e)
bool referenceSelected (const Gui::SelectionChanges &msg)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Types inherited from PartDesignGui::TaskDressUpParameters
enum selectionModes {
none , refAdd , refRemove , plane ,
line
}
Protected Slots inherited from PartDesignGui::TaskDressUpParameters
void createAddAllEdgesAction (QListWidget *parentList)
void createDeleteAction (QListWidget *parentList, QWidget *parentButton)
void doubleClicked (QListWidgetItem *item)
void itemClickedTimeout ()
void onButtonRefAdd (const bool checked)
void onButtonRefRemove (const bool checked)
virtual void onRefDeleted (void)=0
void setSelection (QListWidgetItem *current)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Static Protected Member Functions inherited from PartDesignGui::TaskDressUpParameters
static void removeItemFromListWidget (QListWidget *widget, const char *itemstr)
Protected Attributes inherited from PartDesignGui::TaskDressUpParameters
QAction * addAllEdgesAction
bool allowEdges
bool allowFaces
QAction * deleteAction
ViewProviderDressUp * DressUpView
QWidget * proxy
selectionModes selectionMode
int transactionID
bool wasDoubleClicked = false
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskChamferParameters()
TaskChamferParameters::TaskChamferParameters (ViewProviderDressUp * DressUpView, QWidget * parent = nullptr)
References PartDesignGui::TaskDressUpParameters::addAllEdgesAction, PartDesign::DressUp::Base, draftgeoutils.intersections::connect(), PartDesignGui::TaskDressUpParameters::createAddAllEdgesAction(), PartDesignGui::TaskDressUpParameters::createDeleteAction(), PartDesignGui::TaskDressUpParameters::deleteAction, PartDesignGui::TaskDressUpParameters::doubleClicked(), PartDesignGui::TaskDressUpParameters::DressUpView, Gui::ViewProviderDocumentObject::getObject(), App::PropertyLinkSub::getSubValues(), App::PropertyBool::getValue(), QSint::ActionGroup::groupLayout(), PartDesignGui::TaskDressUpParameters::hideOnError(), PartDesignGui::TaskDressUpParameters::onButtonRefAdd(), PartDesignGui::TaskDressUpParameters::onButtonRefRemove(), PartDesignGui::TaskDressUpParameters::proxy, PartDesignGui::TaskDressUpParameters::setSelection(), and PartDesign::Chamfer::UseAllEdges.
~TaskChamferParameters()
TaskChamferParameters::~TaskChamferParameters ()
References Gui::SelectionSingleton::clearSelection(), Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
apply()
void TaskChamferParameters::apply (void) virtual
Apply the changes made to the object to it.
Reimplemented from PartDesignGui::TaskDressUpParameters.
References PartDesign::Chamfer::ChamferType, PartDesignGui::TaskDressUpParameters::DressUpView, App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), and App::PropertyEnumeration::getValue().
changeEvent()
void TaskChamferParameters::changeEvent (QEvent * e) protected
References PartDesignGui::TaskDressUpParameters::proxy.
clearButtons()
void TaskChamferParameters::clearButtons (const selectionModes notThis) protected virtual
Implements PartDesignGui::TaskDressUpParameters.
References PartDesignGui::TaskDressUpParameters::DressUpView, PartDesignGui::ViewProviderDressUp::highlightReferences(), PartDesignGui::TaskDressUpParameters::refAdd, and PartDesignGui::TaskDressUpParameters::refRemove.
Referenced by onSelectionChanged().
event()
bool TaskChamferParameters::event (QEvent * e) protected
References PartDesignGui::TaskDressUpParameters::KeyEvent().
getAngle()
double TaskChamferParameters::getAngle (void) const protected
Referenced by PathScripts.PathDressupDogbone.Chord::getAngleXY(), draftguitools.gui_trackers.arcTracker::setEndPoint(), and draftguitools.gui_trackers.arcTracker::setStartPoint().
getFlipDirection()
bool TaskChamferParameters::getFlipDirection (void) const protected
getSize()
double TaskChamferParameters::getSize (void) const protected
getSize2()
double TaskChamferParameters::getSize2 (void) const protected
getType()
int TaskChamferParameters::getType (void) const protected
Referenced by PathScripts.PathToolEdit.ToolEditor::updateToolType(), and PathScripts.PathToolEdit.ToolEditor::updateUI().
onSelectionChanged()
void TaskChamferParameters::onSelectionChanged (const Gui::SelectionChanges & msg) protected virtual
Implements Gui::SelectionObserver.
References Gui::SelectionChanges::AddSelection, clearButtons(), Gui::SelectionSingleton::clearSelection(), PartDesignGui::TaskDressUpParameters::deleteAction, PartDesignGui::TaskDressUpParameters::DressUpView, PartDesignGui::TaskDressUpParameters::exitSelectionMode(), PartDesignGui::ViewProviderDressUp::highlightReferences(), PartDesignGui::TaskDressUpParameters::none, PartDesignGui::TaskDressUpParameters::refAdd, PartDesignGui::TaskDressUpParameters::referenceSelected(), PartDesignGui::TaskDressUpParameters::removeItemFromListWidget(), Gui::Selection(), and PartDesignGui::TaskDressUpParameters::selectionMode.
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/PartDesign/Gui/TaskChamferParameters.h
FreeCAD/src/Mod/PartDesign/Gui/TaskChamferParameters.cpp