FreeCAD: PathTests.TestPathGeom.TestPathGeom Class Reference
PathTests.TestPathGeom.TestPathGeom Class Reference
Public Member Functions
def test00 (self)
def test01 (self)
def test02 (self)
def test03 (self)
def test04 (self)
def test07 (self)
def test08 (self)
def test10 (self)
def test20 (self)
def test30 (self)
def test40 (self)
def test41 (self)
def test50 (self)
def test60 (self)
def test62 (self)
def test65 (self)
def test66 (self)
def test70 (self)
def test71 (self)
def test72 (self)
def test73 (self)
def test74 (self)
def test75 (self)
Public Member Functions inherited from PathTests.PathTestUtils.PathTestBase
def assertArc (self, edge, pt1, pt2, direction='CW')
def assertCircle (self, edge, pt, r)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertCommandEqual (self, c1, c2)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertEdgeShapesMatch (self, e1, e2)
def assertEqualLocale (self, s1, s2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertPlacement (self, p1, p2)
def assertPointsMatch (self, pts0, pts1)
def assertRoughly (self, f1, f2, error=0.00001)
Detailed Description
Test Path <-> Wire conversion.
Member Function Documentation
test00()
def PathTests.TestPathGeom.TestPathGeom.test00 (self)
Verify getAngle functionality.
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
Referenced by PathTests.TestPathTool.TestPathTool.test01(), PathTests.TestPathToolController.TestPathToolController.test01(), PathTests.TestPathTooltable.TestPathTooltable.test01(), PathTests.TestPathTool.TestPathTool.test02(), and PathTests.TestPathTooltable.TestPathTooltable.test02().
test01()
def PathTests.TestPathGeom.TestPathGeom.test01 (self)
Verify diffAngle functionality.
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
test02()
def PathTests.TestPathGeom.TestPathGeom.test02 (self)
Verify isVertical/isHorizontal for Vector
test03()
def PathTests.TestPathGeom.TestPathGeom.test03 (self)
Verify isVertical/isHorizontal for Edges
test04()
def PathTests.TestPathGeom.TestPathGeom.test04 (self)
Verify isVertical/isHorizontal for faces
test07()
def PathTests.TestPathGeom.TestPathGeom.test07 (self)
Verify speed interpolation works for different pitches
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
test08()
def PathTests.TestPathGeom.TestPathGeom.test08 (self)
Verify speed interpolation works for different pitches if vSpeed > hSpeed
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
test10()
def PathTests.TestPathGeom.TestPathGeom.test10 (self)
Verify proper geometry objects for G1 and G01 commands are created.
References PathTests.PathTestUtils.PathTestBase.assertLine().
test20()
def PathTests.TestPathGeom.TestPathGeom.test20 (self)
Verify proper geometry for arcs in the XY-plane are created.
References PathTests.PathTestUtils.PathTestBase.assertArc().
test30()
def PathTests.TestPathGeom.TestPathGeom.test30 (self)
Verify proper geometry for arcs with rising and fall ing Z-axis are created.
References PathTests.PathTestUtils.PathTestBase.assertCurve().
test40()
def PathTests.TestPathGeom.TestPathGeom.test40 (self)
Verify arc results in proper G2/3 command.
References PathTests.PathTestUtils.PathTestBase.assertCommandEqual().
test41()
def PathTests.TestPathGeom.TestPathGeom.test41 (self)
Verify circle results in proper G2/G3 commands.
References PathTests.PathTestUtils.PathTestBase.assertCommandEqual().
test50()
def PathTests.TestPathGeom.TestPathGeom.test50 (self)
Verify proper wire(s) aggregation from a Path.
References PathTests.PathTestUtils.PathTestBase.assertLine().
test60()
def PathTests.TestPathGeom.TestPathGeom.test60 (self)
Verify arcToHelix returns proper helix.
References PathTests.PathTestUtils.PathTestBase.assertCurve().
test62()
def PathTests.TestPathGeom.TestPathGeom.test62 (self)
Verify splitArcAt returns proper subarcs.
References PathTests.PathTestUtils.PathTestBase.assertCurve().
test65()
def PathTests.TestPathGeom.TestPathGeom.test65 (self)
Verify splitEdgeAt.
References PathTests.PathTestUtils.PathTestBase.assertCurve(), and PathTests.PathTestUtils.PathTestBase.assertLine().
test66()
def PathTests.TestPathGeom.TestPathGeom.test66 (self)
Split arc real world sample
References PathTests.PathTestUtils.PathTestBase.assertCoincide(), and PathTests.PathTestUtils.PathTestBase.assertRoughly().
test70()
def PathTests.TestPathGeom.TestPathGeom.test70 (self)
Flip a line.
References PathTests.PathTestUtils.PathTestBase.assertEdgeShapesMatch().
test71()
def PathTests.TestPathGeom.TestPathGeom.test71 (self)
Flip a line segment.
References PathTests.PathTestUtils.PathTestBase.assertEdgeShapesMatch().
test72()
def PathTests.TestPathGeom.TestPathGeom.test72 (self)
Flip a circle
References PathTests.PathTestUtils.PathTestBase.assertEdgeShapesMatch().
test73()
def PathTests.TestPathGeom.TestPathGeom.test73 (self)
Flip an arc
References PathTests.PathTestUtils.PathTestBase.assertEdgeShapesMatch().
test74()
def PathTests.TestPathGeom.TestPathGeom.test74 (self)
Flip a rotated arc
References PathTests.PathTestUtils.PathTestBase.assertEdgeShapesMatch().
test75()
def PathTests.TestPathGeom.TestPathGeom.test75 (self)
Flip a B-spline
References PathTests.PathTestUtils.PathTestBase.assertEdgeShapesMatch().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Path/PathTests/TestPathGeom.py