FreeCAD: MeshCore::MeshRefPointToFacets Class Reference
MeshCore::MeshRefPointToFacets Class Reference
The MeshRefPointToFacets builds up a structure to have access to all facets indexing a point.
#include <Algorithm.h>
Public Member Functions
void AddNeighbour (unsigned long, unsigned long)
MeshFacetArray::_TConstIterator GetFacet (unsigned long) const
std::vector< unsigned long > GetIndices (unsigned long, unsigned long) const
std::vector< unsigned long > GetIndices (unsigned long, unsigned long, unsigned long) const
Base::Vector3f GetNormal (unsigned long) const
MeshRefPointToFacets (const MeshKernel &rclM)
Construction.
std::set< unsigned long > NeighbourPoints (const std::vector< unsigned long > &, int level) const
std::set< unsigned long > NeighbourPoints (unsigned long) const
void Neighbours (unsigned long ulFacetInd, float fMaxDist, MeshCollector &collect) const
const std::set< unsigned long > & operator[] (unsigned long) const
void Rebuild (void)
Rebuilds up data structure.
void RemoveFacet (unsigned long)
void RemoveNeighbour (unsigned long, unsigned long)
~MeshRefPointToFacets (void)
Destruction.
Protected Member Functions
void SearchNeighbours (const MeshFacetArray &rFacets, unsigned long index, const Base::Vector3f &rclCenter, float fMaxDist, std::set< unsigned long > &visit, MeshCollector &collect) const
Detailed Description
The MeshRefPointToFacets builds up a structure to have access to all facets indexing a point.
Note
If the underlying mesh kernel gets changed this structure becomes invalid and must be rebuilt.
Constructor & Destructor Documentation
MeshRefPointToFacets()
MeshCore::MeshRefPointToFacets::MeshRefPointToFacets (const MeshKernel & rclM)
Construction.
~MeshRefPointToFacets()
MeshCore::MeshRefPointToFacets::~MeshRefPointToFacets (void)
Destruction.
Member Function Documentation
AddNeighbour()
void MeshRefPointToFacets::AddNeighbour (unsigned long pos, unsigned long facet)
Referenced by MeshCore::MeshRemoveNeedles::Fixup().
GetFacet()
MeshFacetArray::_TConstIterator MeshRefPointToFacets::GetFacet (unsigned long index) const
GetIndices() [1/2]
std::vector< unsigned long > MeshRefPointToFacets::GetIndices (unsigned long pos1, unsigned long pos2) const
Referenced by GetIndices().
GetIndices() [2/2]
std::vector< unsigned long > MeshRefPointToFacets::GetIndices (unsigned long pos1, unsigned long pos2, unsigned long pos3) const
References GetIndices().
GetNormal()
Base::Vector3f MeshRefPointToFacets::GetNormal (unsigned long pos) const
References Base::Vector3< _Precision >::Normalize().
NeighbourPoints() [1/2]
std::set< unsigned long > MeshRefPointToFacets::NeighbourPoints (const std::vector< unsigned long > & pt, int level) const
Referenced by MeshCore::MeshEvalDentsOnSurface::Evaluate(), MeshCore::MeshAlgorithm::FillupHole(), and MeshCore::MeshRemoveNeedles::Fixup().
NeighbourPoints() [2/2]
std::set< unsigned long > MeshRefPointToFacets::NeighbourPoints (unsigned long pos) const
Neighbours()
void MeshRefPointToFacets::Neighbours (unsigned long ulFacetInd, float fMaxDist, MeshCollector & collect) const
References SearchNeighbours().
Referenced by MeshCore::FacetCurvature::Compute().
operator[]()
const std::set< unsigned long > & MeshRefPointToFacets::operator[] (unsigned long pos) const
Rebuild()
void MeshRefPointToFacets::Rebuild (void)
Rebuilds up data structure.
RemoveFacet()
void MeshRefPointToFacets::RemoveFacet (unsigned long facetIndex)
Referenced by MeshCore::MeshRemoveNeedles::Fixup().
RemoveNeighbour()
void MeshRefPointToFacets::RemoveNeighbour (unsigned long pos, unsigned long facet)
Referenced by MeshCore::MeshRemoveNeedles::Fixup().
SearchNeighbours()
void MeshRefPointToFacets::SearchNeighbours (const MeshFacetArray & rFacets, unsigned long index, const Base::Vector3f & rclCenter, float fMaxDist, std::set< unsigned long > & visit, MeshCollector & collect) const protected
References MeshCore::MeshCollector::Append(), and Base::DistanceP2().
Referenced by Neighbours().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Algorithm.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Algorithm.cpp