FreeCAD: Gui::DockWnd::SelectionView Class Reference
Gui::DockWnd::SelectionView Class Reference
A test class.
#include <SelectionView.h>
Public Slots
void deselect (void)
void onEnablePickList ()
void onItemContextMenu (const QPoint &point)
get called when the list is right-clicked
void preselect (QListWidgetItem *item=0)
void search (const QString &text)
get called when text is entered in the search box
void select (QListWidgetItem *item=0)
different actions
void showPart (void)
void toggleSelect (QListWidgetItem *item=0)
void toPython (void)
void touch (void)
void treeSelect (void)
void validateSearch (void)
get called when enter is pressed in the search box
void zoom (void)
Public Member Functions
virtual const char * getName (void) const override
returns the name of the view (important for messages)
virtual void leaveEvent (QEvent *) override
bool onMsg (const char *pMsg, const char **ppReturn) override
Message handler.
virtual void onSelectionChanged (const SelectionChanges &msg) override
Observer message from the Selection.
virtual void onUpdate (void) override
get called when the document is changed or updated
SelectionView (Gui::Document *pcDocument, QWidget *parent=0)
A constructor.
virtual ~SelectionView ()
A destructor.
Public Member Functions inherited from Gui::DockWindow
DockWindow (Gui::Document *pcDocument=0, QWidget *parent=0)
View constructor Attach the view to the given document.
virtual ~DockWindow ()
View destructor Detach the view from the document, if attached.
virtual bool onHasMsg (const char *) const
Message handler test.
virtual bool canClose (void)
overwrite when checking on close state
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=0)
View constructor Attach the view to the given document.
virtual ~BaseView ()
View destructor Detach the view from the document, if attached!
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose (void)
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive (void) const
indicates if the view is in passive mode
virtual void onRelabel (Gui::Document *)
get called when the document is relabeled (change of its user name)
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
virtual void deleteSelf ()
delete itself
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId (void) const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockConnection (bool block)
void detachSelection ()
Detaches from the selection.
bool isConnectionAttached () const
bool isConnectionBlocked () const
SelectionObserver (bool attach=true, int resolve=1)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, int resolve=1)
Constructor.
virtual ~SelectionObserver ()
Public Attributes
QLabel * countLabel
QCheckBox * enablePickList
QListWidget * pickList
QListWidget * selectionView
Protected Member Functions
void hideEvent (QHideEvent *) override
void showEvent (QShowEvent *) override
Additional Inherited Members
Signals inherited from Gui::DockWindow
void sendCloseView (MDIView *theView)
sends a message to the document
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::BaseView
bool bIsDetached
bool bIsPassive
Detailed Description
A test class.
A more elaborate class description.
Constructor & Destructor Documentation
SelectionView()
SelectionView::SelectionView (Gui::Document * pcDocument, QWidget * parent = 0)
A constructor.
A more elaborate description of the constructor.
References Gui::BitmapFactory(), and draftgeoutils.intersections::connect().
~SelectionView()
SelectionView::~SelectionView () virtual
A destructor.
A more elaborate description of the destructor.
Member Function Documentation
deselect
void Gui::DockWnd::SelectionView::deselect (void) slot
getName()
virtual const char* Gui::DockWnd::SelectionView::getName (void) const override virtual
returns the name of the view (important for messages)
Reimplemented from Gui::DockWindow.
hideEvent()
void Gui::DockWnd::SelectionView::hideEvent (QHideEvent *) override protected
leaveEvent()
void SelectionView::leaveEvent (QEvent *) override virtual
References Gui::SelectionSingleton::rmvPreselect(), and Gui::Selection().
onEnablePickList
void Gui::DockWnd::SelectionView::onEnablePickList () slot
onItemContextMenu
void Gui::DockWnd::SelectionView::onItemContextMenu (const QPoint & point) slot
get called when the list is right-clicked
onMsg()
bool Gui::DockWnd::SelectionView::onMsg (const char * , const char **) override virtual
Message handler.
Reimplemented from Gui::DockWindow.
onSelectionChanged()
virtual void Gui::DockWnd::SelectionView::onSelectionChanged (const SelectionChanges & msg) override virtual
Observer message from the Selection.
Implements Gui::SelectionObserver.
onUpdate()
virtual void Gui::DockWnd::SelectionView::onUpdate (void) override virtual
get called when the document is changed or updated
Reimplemented from Gui::DockWindow.
Referenced by shipAreasCurve.TaskPanel.TaskPanel::initValues(), and shipAreasCurve.TaskPanel.TaskPanel::onData().
preselect
void Gui::DockWnd::SelectionView::preselect (QListWidgetItem * item = 0) slot
search
void Gui::DockWnd::SelectionView::search (const QString & text) slot
get called when text is entered in the search box
Referenced by importIFClegacy.IfcDocument::find().
select
void Gui::DockWnd::SelectionView::select (QListWidgetItem * item = 0) slot
different actions
showEvent()
void Gui::DockWnd::SelectionView::showEvent (QShowEvent *) override protected
showPart
void Gui::DockWnd::SelectionView::showPart (void) slot
toggleSelect
void Gui::DockWnd::SelectionView::toggleSelect (QListWidgetItem * item = 0) slot
toPython
void Gui::DockWnd::SelectionView::toPython (void) slot
touch
void Gui::DockWnd::SelectionView::touch (void) slot
treeSelect
void Gui::DockWnd::SelectionView::treeSelect (void) slot
validateSearch
void Gui::DockWnd::SelectionView::validateSearch (void) slot
get called when enter is pressed in the search box
zoom
void Gui::DockWnd::SelectionView::zoom (void) slot
Member Data Documentation
countLabel
QLabel* Gui::DockWnd::SelectionView::countLabel
enablePickList
QCheckBox* Gui::DockWnd::SelectionView::enablePickList
pickList
QListWidget* Gui::DockWnd::SelectionView::pickList
selectionView
QListWidget* Gui::DockWnd::SelectionView::selectionView
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SelectionView.h
Sources/FreeCAD/src/Gui/SelectionView.cpp