FreeCAD: TechDrawGui::TaskCustomizeFormat Class Reference
TechDrawGui::TaskCustomizeFormat Class Reference
#include <TaskCustomizeFormat.h>
Public Member Functions
virtual bool accept ()
virtual bool reject ()
TaskCustomizeFormat (App::DocumentObject *object)
void updateTask ()
~TaskCustomizeFormat ()
Protected Member Functions
void changeEvent (QEvent *e)
void setUiEdit (void)
Constructor & Destructor Documentation
TaskCustomizeFormat()
TaskCustomizeFormat::TaskCustomizeFormat (App::DocumentObject * object)
References setUiEdit().
~TaskCustomizeFormat()
TaskCustomizeFormat::~TaskCustomizeFormat ()
Member Function Documentation
accept()
bool TaskCustomizeFormat::accept (void) virtual
References Gui::Command::commitCommand(), TechDraw::DrawViewDimension::FormatSpec, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, App::PropertyString::setValue(), and TechDraw::DrawViewBalloon::Text.
Referenced by TechDrawGui::TaskDlgCustomizeFormat::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void TaskCustomizeFormat::changeEvent (QEvent * e) protected
reject()
bool TaskCustomizeFormat::reject (void) virtual
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), TechDrawGui::TaskDlgCustomizeFormat::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
setUiEdit()
void TaskCustomizeFormat::setUiEdit (void) protected
References draftgeoutils.intersections::connect(), and Base::Tools::fromStdString().
Referenced by TaskCustomizeFormat().
updateTask()
void TaskCustomizeFormat::updateTask ()
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/TaskCustomizeFormat.h
FreeCAD/src/Mod/TechDraw/Gui/TaskCustomizeFormat.cpp