FreeCAD: ArchFloor Namespace Reference
ArchFloor Namespace Reference
Workbenches » Python workbenches » Arch
The Floor object and tools.
Functions
def makeFloor (objectslist=None, baseobj=None, name="Floor")
Detailed Description
The Floor object and tools.
This module provides tools to build Floor objects. Floors are used to group different Arch objects situated at a same level
Function Documentation
makeFloor()
def ArchFloor.makeFloor (objectslist = None, baseobj = None, name = "Floor")
Obsolete, superseded by ArchBuildingPart.makeFloor.
Create a floor.
Create a new floor based on a group, and then adds the objects in
objectslist to the new floor.
Parameters
----------
objectslist: list of <App::DocumentObject>, optional
    The objects to add to the new floor.
baseobj:
    Unused.
name: str, optional
    The Label for the new floor.
Returns
-------
<App::DocumentObjectGroupPython>
    The created floor.
References DraftVecUtils.equals(), ArchIFC.IfcRoot.onChanged(), ArchCommands.printMessage(), draftutils.translate.QT_TRANSLATE_NOOP, and ArchIFC.IfcRoot.setProperties().