FreeCAD: SMESH::Controls::Volume Class Reference
SMESH::Controls::Volume Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
virtual double GetBadRate (double Value, int nbNodes) const
virtual SMDSAbs_ElementType GetType () const
virtual double GetValue (long theElementId)
Public Member Functions inherited from SMESH::Controls::NumericalFunctor
virtual double GetBadRate (double Value, int nbNodes) const =0
void GetHistogram (int nbIntervals, std::vector< int > &nbEvents, std::vector< double > &funValues, const std::vector< int > &elements, const double *minmax=0, const bool isLogarithmic=false)
Return histogram of functor values.
bool GetPoints (const int theId, TSequenceOfXYZ &theRes) const
long GetPrecision () const
virtual SMDSAbs_ElementType GetType () const =0
virtual double GetValue (const TSequenceOfXYZ &thePoints)
virtual double GetValue (long theElementId)
NumericalFunctor ()
double Round (const double &value)
virtual void SetMesh (const SMDS_Mesh *theMesh)
void SetPrecision (const long thePrecision)
Public Member Functions inherited from SMESH::Controls::Functor
virtual SMDSAbs_ElementType GetType () const =0
virtual void SetMesh (const SMDS_Mesh *theMesh)=0
virtual ~Functor ()
Additional Inherited Members
Static Public Member Functions inherited from SMESH::Controls::NumericalFunctor
static bool GetPoints (const SMDS_MeshElement *theElem, TSequenceOfXYZ &theRes)
Protected Attributes inherited from SMESH::Controls::NumericalFunctor
const SMDS_MeshElement * myCurrElement
const SMDS_Mesh * myMesh
long myPrecision
double myPrecisionValue
Member Function Documentation
GetBadRate()
double Volume::GetBadRate (double Value, int nbNodes) const virtual
Implements SMESH::Controls::NumericalFunctor.
GetType()
SMDSAbs_ElementType Volume::GetType () const virtual
Implements SMESH::Controls::NumericalFunctor.
GetValue()
double Volume::GetValue (long theElementId) virtual
Reimplemented from SMESH::Controls::NumericalFunctor.
References SMDS_Mesh::FindElement(), SMDS_VolumeTool::GetSize(), SMESH::Controls::NumericalFunctor::myMesh, and SMDS_VolumeTool::Set().
Referenced by NETGENPlugin_SimpleHypothesis_3D::SetParametersByMesh(), and StdMeshers_MaxElementVolume::SetParametersByMesh().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp