FreeCAD: StringCache Class Reference
StringCache Class Reference
Static Public Member Functions
static const char * New (const char *str)
Member Function Documentation
New()
static const char * StringCache::New (const char * str) static
Referenced by Gui::CommandBase::setAccel(), Gui::Command::setAppModuleName(), Gui::Command::setGroupName(), Gui::CommandBase::setMenuText(), Gui::CommandBase::setPixmap(), Gui::MacroCommand::setScriptName(), Gui::CommandBase::setStatusTip(), Gui::CommandBase::setToolTipText(), and Gui::CommandBase::setWhatsThis().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/Command.cpp