FreeCAD: SketcherGui::Ui_TaskSketcherGeneral Class Reference
SketcherGui::Ui_TaskSketcherGeneral Class Reference
#include <ui_TaskSketcherGeneral.h>
Public Member Functions
void retranslateUi (QWidget *SketcherGui__TaskSketcherGeneral)
void setupUi (QWidget *SketcherGui__TaskSketcherGeneral)
Public Attributes
Gui::PrefCheckBox * checkBoxAutoconstraints
Gui::PrefCheckBox * checkBoxGridSnap
Gui::PrefCheckBox * checkBoxRedundantAutoconstraints
Gui::PrefCheckBox * checkBoxShowGrid
Gui::PrefQuantitySpinBox * gridSize
QHBoxLayout * horizontalLayout
QLabel * label
QLabel * label_2
QListWidget * renderingOrder
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void SketcherGui::Ui_TaskSketcherGeneral::retranslateUi (QWidget * SketcherGui__TaskSketcherGeneral)
References checkBoxAutoconstraints, checkBoxGridSnap, checkBoxRedundantAutoconstraints, checkBoxShowGrid, gridSize, label_2, renderingOrder, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void SketcherGui::Ui_TaskSketcherGeneral::setupUi (QWidget * SketcherGui__TaskSketcherGeneral)
References checkBoxAutoconstraints, checkBoxGridSnap, checkBoxRedundantAutoconstraints, checkBoxShowGrid, gridSize, horizontalLayout, label_2, renderingOrder, retranslateUi(), and verticalLayout.
Member Data Documentation
checkBoxAutoconstraints
Gui::PrefCheckBox* SketcherGui::Ui_TaskSketcherGeneral::checkBoxAutoconstraints
Referenced by retranslateUi(), and setupUi().
checkBoxGridSnap
Gui::PrefCheckBox* SketcherGui::Ui_TaskSketcherGeneral::checkBoxGridSnap
Referenced by retranslateUi(), and setupUi().
checkBoxRedundantAutoconstraints
Gui::PrefCheckBox* SketcherGui::Ui_TaskSketcherGeneral::checkBoxRedundantAutoconstraints
Referenced by retranslateUi(), and setupUi().
checkBoxShowGrid
Gui::PrefCheckBox* SketcherGui::Ui_TaskSketcherGeneral::checkBoxShowGrid
Referenced by retranslateUi(), and setupUi().
gridSize
Gui::PrefQuantitySpinBox* SketcherGui::Ui_TaskSketcherGeneral::gridSize
Referenced by retranslateUi(), and setupUi().
horizontalLayout
QHBoxLayout* SketcherGui::Ui_TaskSketcherGeneral::horizontalLayout
Referenced by setupUi().
label
QLabel* SketcherGui::Ui_TaskSketcherGeneral::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
label_2
QLabel* SketcherGui::Ui_TaskSketcherGeneral::label_2
Referenced by retranslateUi(), and setupUi().
renderingOrder
QListWidget* SketcherGui::Ui_TaskSketcherGeneral::renderingOrder
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* SketcherGui::Ui_TaskSketcherGeneral::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/ui_TaskSketcherGeneral.h