FreeCAD: Gui::Dialog::Ui_DlgCreateNewPreferencePack Class Reference
Gui::Dialog::Ui_DlgCreateNewPreferencePack Class Reference
#include <ui_DlgCreateNewPreferencePack.h>
Public Member Functions
void retranslateUi (QDialog *Gui__Dialog__DlgCreateNewPreferencePack)
void setupUi (QDialog *Gui__Dialog__DlgCreateNewPreferencePack)
Public Attributes
QDialogButtonBox * buttonBox
QHBoxLayout * horizontalLayout
QLabel * label
QLineEdit * lineEdit
QTreeWidget * treeWidget
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void Gui::Dialog::Ui_DlgCreateNewPreferencePack::retranslateUi (QDialog * Gui__Dialog__DlgCreateNewPreferencePack)
References draftguitools.gui_setstyle::translate, and treeWidget.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::Dialog::Ui_DlgCreateNewPreferencePack::setupUi (QDialog * Gui__Dialog__DlgCreateNewPreferencePack)
References buttonBox, draftgeoutils.intersections::connect(), horizontalLayout, lineEdit, retranslateUi(), treeWidget, and verticalLayout.
Member Data Documentation
buttonBox
QDialogButtonBox* Gui::Dialog::Ui_DlgCreateNewPreferencePack::buttonBox
Referenced by PathScripts.PathGetPoint.TaskPanel::getPoint(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::modifyStandardButtons(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::pageDirtyChanged(), PathScripts.PathGetPoint.TaskPanel::pointFinish(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setClean(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setDirty(), and setupUi().
horizontalLayout
QHBoxLayout* Gui::Dialog::Ui_DlgCreateNewPreferencePack::horizontalLayout
Referenced by setupUi().
label
QLabel* Gui::Dialog::Ui_DlgCreateNewPreferencePack::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
lineEdit
QLineEdit* Gui::Dialog::Ui_DlgCreateNewPreferencePack::lineEdit
Referenced by Spreadsheet_legacy.SpreadsheetView::getEditLine(), Spreadsheet_legacy.SpreadsheetView::setEditLine(), setupUi(), and Spreadsheet_legacy.SpreadsheetView::wipeCell().
treeWidget
QTreeWidget* Gui::Dialog::Ui_DlgCreateNewPreferencePack::treeWidget
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* Gui::Dialog::Ui_DlgCreateNewPreferencePack::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_DlgCreateNewPreferencePack.h