FreeCAD: Gui::GuiNativeEvent Class Reference
Gui::GuiNativeEvent Class Reference
#include <GuiNativeEventWin32.h>
Public Member Functions
GuiNativeEvent (GUIApplicationNativeEventAware *app)
GuiNativeEvent (GUIApplicationNativeEventAware *app)
GuiNativeEvent (GUIApplicationNativeEventAware *app)
GuiNativeEvent (GUIApplicationNativeEventAware *app)
void initSpaceball (QMainWindow *window) override final
void initSpaceball (QMainWindow *window) override final
void initSpaceball (QMainWindow *window) override final
void initSpaceball (QMainWindow *window) override final
I3dMouseParam & MouseParams ()
const I3dMouseParam & MouseParams () const
virtual void Move3d (HANDLE device, std::vector< float > &motionData)
virtual void On3dmouseKeyDown (HANDLE device, int virtualKeyCode)
virtual void On3dmouseKeyUp (HANDLE device, int virtualKeyCode)
~GuiNativeEvent () override
~GuiNativeEvent () override
~GuiNativeEvent () override
~GuiNativeEvent () override
Public Member Functions inherited from Gui::GuiAbstractNativeEvent
GuiAbstractNativeEvent (GUIApplicationNativeEventAware *app)
virtual void initSpaceball (QMainWindow *window)=0
virtual ~GuiAbstractNativeEvent ()=0
Static Public Member Functions
static bool Is3dmouseAttached ()
static bool xcbEventFilter (void *message, long *result)
Additional Inherited Members
Static Protected Attributes inherited from Gui::GuiAbstractNativeEvent
static GUIApplicationNativeEventAware * mainApp
static std::vector< int > motionDataArray
Constructor & Destructor Documentation
GuiNativeEvent() [1/4]
Gui::GuiNativeEvent::GuiNativeEvent (Gui::GUIApplicationNativeEventAware * app)
References GuiNativeEvent().
Referenced by GuiNativeEvent().
~GuiNativeEvent() [1/4]
Gui::GuiNativeEvent::~GuiNativeEvent () override
References Base::Console(), and Base::ConsoleSingleton::Log().
GuiNativeEvent() [2/4]
Gui::GuiNativeEvent::GuiNativeEvent (GUIApplicationNativeEventAware * app)
~GuiNativeEvent() [2/4]
Gui::GuiNativeEvent::~GuiNativeEvent () override
GuiNativeEvent() [3/4]
Gui::GuiNativeEvent::GuiNativeEvent (GUIApplicationNativeEventAware * app)
~GuiNativeEvent() [3/4]
Gui::GuiNativeEvent::~GuiNativeEvent () override
GuiNativeEvent() [4/4]
Gui::GuiNativeEvent::GuiNativeEvent (GUIApplicationNativeEventAware * app)
~GuiNativeEvent() [4/4]
Gui::GuiNativeEvent::~GuiNativeEvent () override
Member Function Documentation
initSpaceball() [1/4]
void Gui::GuiNativeEvent::initSpaceball (QMainWindow * window) final override virtual
Implements Gui::GuiAbstractNativeEvent.
References draftgeoutils.intersections::connect(), Base::Console(), and Base::ConsoleSingleton::Log().
initSpaceball() [2/4]
void Gui::GuiNativeEvent::initSpaceball (QMainWindow * window) final override virtual
Implements Gui::GuiAbstractNativeEvent.
initSpaceball() [3/4]
void Gui::GuiNativeEvent::initSpaceball (QMainWindow * window) final override virtual
Implements Gui::GuiAbstractNativeEvent.
initSpaceball() [4/4]
void Gui::GuiNativeEvent::initSpaceball (QMainWindow * window) final override virtual
Implements Gui::GuiAbstractNativeEvent.
Is3dmouseAttached()
bool Gui::GuiNativeEvent::Is3dmouseAttached () static
Detect the 3D mouse
MouseParams() [1/2]
I3dMouseParam & Gui::GuiNativeEvent::MouseParams ()
Access the mouse parameters structure
MouseParams() [2/2]
const I3dMouseParam & Gui::GuiNativeEvent::MouseParams () const
Access the mouse parameters structure
Move3d()
void Gui::GuiNativeEvent::Move3d (HANDLE device, std::vector< float > & motionData) virtual
Called with the processed motion data when a 3D mouse event is received
The default implementation emits a Move3d signal with the motion data
On3dmouseKeyDown()
void Gui::GuiNativeEvent::On3dmouseKeyDown (HANDLE device, int virtualKeyCode) virtual
Called when a 3D mouse key is pressed
The default implementation emits a On3dmouseKeyDown signal with the key code.
On3dmouseKeyUp()
void Gui::GuiNativeEvent::On3dmouseKeyUp (HANDLE device, int virtualKeyCode) virtual
Called when a 3D mouse key is released
The default implementation emits a On3dmouseKeyUp signal with the key code.
xcbEventFilter()
static bool Gui::GuiNativeEvent::xcbEventFilter (void * message, long * result) static
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/3Dconnexion/GuiNativeEventLinux.h
FreeCAD/src/Gui/3Dconnexion/GuiNativeEventMac.h
FreeCAD/src/Gui/3Dconnexion/GuiNativeEventWin32.h
FreeCAD/src/Gui/3Dconnexion/GuiNativeEventLinuxX11.h
FreeCAD/src/Gui/3Dconnexion/GuiNativeEventLinux.cpp
FreeCAD/src/Gui/3Dconnexion/GuiNativeEventLinuxX11.cpp
FreeCAD/src/Gui/3Dconnexion/GuiNativeEventMac.cpp
FreeCAD/src/Gui/3Dconnexion/GuiNativeEventWin32.cpp