FreeCAD: ClipperLib::ClipperBase Class Reference
ClipperLib::ClipperBase Class Reference
#include <clipper.hpp>
Public Member Functions
bool AddPath (const Path &pg, PolyType PolyTyp, bool Closed)
bool AddPaths (const Paths &ppg, PolyType PolyTyp, bool Closed)
virtual void Clear ()
ClipperBase ()
IntRect GetBounds ()
bool PreserveCollinear ()
void PreserveCollinear (bool value)
virtual ~ClipperBase ()
Protected Types
typedef std::vector< LocalMinimum > MinimaList
Protected Member Functions
TEdge * AddBoundsToLML (TEdge *e, bool IsClosed)
void AscendToMax (TEdge *&E, bool Appending, bool IsClosed)
TEdge * DescendToMin (TEdge *&E)
void DisposeLocalMinimaList ()
void DoMinimaLML (TEdge *E1, TEdge *E2, bool IsClosed)
void PopLocalMinima ()
TEdge * ProcessBound (TEdge *E, bool IsClockwise)
virtual void Reset ()
Protected Attributes
MinimaList::iterator m_CurrentLM
EdgeList m_edges
bool m_HasOpenPaths
MinimaList m_MinimaList
bool m_PreserveCollinear
bool m_UseFullRange
Member Typedef Documentation
MinimaList
typedef std::vector<LocalMinimum> ClipperLib::ClipperBase::MinimaList protected
Constructor & Destructor Documentation
ClipperBase()
ClipperLib::ClipperBase::ClipperBase ()
References m_CurrentLM, m_HasOpenPaths, m_MinimaList, m_PreserveCollinear, and m_UseFullRange.
~ClipperBase()
ClipperLib::ClipperBase::~ClipperBase () virtual
References Clear().
Member Function Documentation
AddBoundsToLML()
TEdge* ClipperLib::ClipperBase::AddBoundsToLML (TEdge * e, bool IsClosed) protected
AddPath()
bool ClipperLib::ClipperBase::AddPath (const Path & pg, PolyType PolyTyp, bool Closed)
References ClipperLib::TEdge::Bot, ClipperLib::TEdge::Curr, ClipperLib::TEdge::Dx, ClipperLib::esLeft, ClipperLib::esRight, ClipperLib::FindNextLocMin(), ClipperLib::InitEdge(), ClipperLib::InitEdge2(), m_edges, m_HasOpenPaths, m_MinimaList, m_PreserveCollinear, m_UseFullRange, ClipperLib::TEdge::Next, ClipperLib::TEdge::NextInLML, ClipperLib::TEdge::OutIdx, ClipperLib::TEdge::Prev, ProcessBound(), ClipperLib::Pt2IsBetweenPt1AndPt3(), ClipperLib::ptClip, ClipperLib::RangeTest(), ClipperLib::RemoveEdge(), ClipperLib::ReverseHorizontal(), ClipperLib::TEdge::Side, ClipperLib::Skip, ClipperLib::SlopesEqual(), ClipperLib::TEdge::Top, ClipperLib::IntPoint::X, and ClipperLib::IntPoint::Y.
Referenced by AddPaths(), AdaptivePath::Adaptive2d::Execute(), and ClipperLib::ClipperOffset::Execute().
AddPaths()
bool ClipperLib::ClipperBase::AddPaths (const Paths & ppg, PolyType PolyTyp, bool Closed)
References AddPath().
Referenced by AdaptivePath::Adaptive2d::Execute(), ClipperLib::ClipperOffset::Execute(), ClipperLib::MinkowskiDiff(), and ClipperLib::MinkowskiSum().
AscendToMax()
void ClipperLib::ClipperBase::AscendToMax (TEdge *& E, bool Appending, bool IsClosed) protected
Clear()
void ClipperLib::ClipperBase::Clear (void) virtual
References DisposeLocalMinimaList(), m_edges, m_HasOpenPaths, and m_UseFullRange.
Referenced by AdaptivePath::Adaptive2d::Execute(), ClipperLib::Clipper::~Clipper(), and ~ClipperBase().
DescendToMin()
TEdge* ClipperLib::ClipperBase::DescendToMin (TEdge *& E) protected
DisposeLocalMinimaList()
void ClipperLib::ClipperBase::DisposeLocalMinimaList () protected
References m_CurrentLM, and m_MinimaList.
Referenced by Clear().
DoMinimaLML()
void ClipperLib::ClipperBase::DoMinimaLML (TEdge * E1, TEdge * E2, bool IsClosed) protected
GetBounds()
IntRect ClipperLib::ClipperBase::GetBounds ()
References m_MinimaList.
Referenced by ClipperLib::ClipperOffset::Execute().
PopLocalMinima()
void ClipperLib::ClipperBase::PopLocalMinima () protected
References m_CurrentLM, and m_MinimaList.
PreserveCollinear() [1/2]
bool ClipperLib::ClipperBase::PreserveCollinear ()
References m_PreserveCollinear.
PreserveCollinear() [2/2]
void ClipperLib::ClipperBase::PreserveCollinear (bool value)
References m_PreserveCollinear.
ProcessBound()
TEdge * ClipperLib::ClipperBase::ProcessBound (TEdge * E, bool IsClockwise) protected
References ClipperLib::TEdge::Bot, ClipperLib::IsHorizontal(), m_MinimaList, ClipperLib::TEdge::Next, ClipperLib::TEdge::NextInLML, ClipperLib::TEdge::OutIdx, ClipperLib::TEdge::Prev, ClipperLib::ReverseHorizontal(), ClipperLib::Skip, ClipperLib::TEdge::Top, ClipperLib::TEdge::WindDelta, ClipperLib::IntPoint::X, and ClipperLib::IntPoint::Y.
Referenced by AddPath().
Reset()
void ClipperLib::ClipperBase::Reset () protected virtual
Reimplemented in ClipperLib::Clipper.
References ClipperLib::esLeft, ClipperLib::esRight, m_CurrentLM, m_MinimaList, and ClipperLib::Unassigned.
Referenced by ClipperLib::Clipper::Reset().
Member Data Documentation
m_CurrentLM
MinimaList::iterator ClipperLib::ClipperBase::m_CurrentLM protected
Referenced by ClipperBase(), DisposeLocalMinimaList(), ClipperLib::Clipper::ExecuteInternal(), PopLocalMinima(), and Reset().
m_edges
EdgeList ClipperLib::ClipperBase::m_edges protected
Referenced by AddPath(), and Clear().
m_HasOpenPaths
bool ClipperLib::ClipperBase::m_HasOpenPaths protected
Referenced by AddPath(), Clear(), ClipperLib::Clipper::Clipper(), ClipperBase(), and ClipperLib::Clipper::Execute().
m_MinimaList
MinimaList ClipperLib::ClipperBase::m_MinimaList protected
Referenced by AddPath(), ClipperBase(), DisposeLocalMinimaList(), ClipperLib::Clipper::ExecuteInternal(), GetBounds(), PopLocalMinima(), ProcessBound(), Reset(), and ClipperLib::Clipper::Reset().
m_PreserveCollinear
bool ClipperLib::ClipperBase::m_PreserveCollinear protected
Referenced by AddPath(), ClipperLib::Clipper::Clipper(), ClipperBase(), and PreserveCollinear().
m_UseFullRange
bool ClipperLib::ClipperBase::m_UseFullRange protected
Referenced by AddPath(), Clear(), ClipperLib::Clipper::Clipper(), and ClipperBase().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Path/libarea/clipper.hpp
Sources/FreeCAD/src/Mod/Path/libarea/clipper.cpp