FreeCAD: Sketcher::ExternalGeometryFacade Class Reference
Sketcher::ExternalGeometryFacade Class Reference
#include <ExternalGeometryFacade.h>
Public Member Functions
Part::Geometry * clone (void) const
Part::Geometry * copy (void) const
void deleteExtension (Base::Type type)
void deleteExtension (const std::string &name)
virtual size_t flagSize () const override
bool getBlocked () const
bool getConstruction (void) const
std::weak_ptr< const Part::GeometryExtension > getExtension (Base::Type type) const
std::weak_ptr< const Part::GeometryExtension > getExtension (const std::string &name) const
std::vector< std::weak_ptr< const Part::GeometryExtension > > getExtensions () const
const std::string & getExternalExtensionName () const
template<typename GeometryT = Part::Geometry, typename = typename std::enable_if< std::is_base_of<Part::Geometry, typename std::decay<GeometryT>::type>::value >::type>
GeometryT * getGeometry ()
template<typename GeometryT = Part::Geometry, typename = typename std::enable_if< std::is_base_of<Part::Geometry, typename std::decay<GeometryT>::type>::value >::type>
GeometryT * getGeometry () const
virtual int getGeometryLayerId () const override
virtual long getId () const override
GeometryExtension Interface.
virtual InternalType::InternalType getInternalType () const override
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
virtual const std::string & getRef () const override
const std::string & getSketchExtensionName () const
boost::uuids::uuid getTag () const
const Handle (Geom_Geometry) &handle() const
bool hasExtension (Base::Type type) const
bool hasExtension (const std::string &name) const
virtual bool isClear () const override
void mirror (const Base::Vector3d &point)
void mirror (const Base::Vector3d &point, Base::Vector3d dir)
void rotate (const Base::Placement &plm)
void scale (const Base::Vector3d &vec, double scale)
void setBlocked (bool status=true)
void setConstruction (bool construction)
void setExtension (std::unique_ptr< Part::GeometryExtension > &&geo)
virtual void setFlag (int flag, bool v=true) override
void setGeometry (Part::Geometry *geometry)
virtual void setGeometryLayerId (int geolayer) override
virtual void setGeometryMode (int flag, bool v=true) override
virtual void setId (long id) override
virtual void setInternalType (InternalType::InternalType type) override
virtual void setRef (const std::string &ref) override
virtual bool testFlag (int flag) const override
External GeometryExtension Interface.
virtual bool testGeometryMode (int flag) const override
TopoDS_Shape toShape () const
Geometry Interface.
void transform (const Base::Matrix4D &mat)
void translate (const Base::Vector3d &vec)
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static void copyId (const Part::Geometry *src, Part::Geometry *dst)
static void ensureSketchGeometryExtensions (Part::Geometry *geometry)
static std::unique_ptr< const ExternalGeometryFacade > getFacade (const Part::Geometry *geometry)
static std::unique_ptr< ExternalGeometryFacade > getFacade (Part::Geometry *geometry)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Friends
class ExternalGeometryFacadePy
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Member Function Documentation
clone()
Part::Geometry * Sketcher::ExternalGeometryFacade::clone (void) const
References Part::Geometry::clone().
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.CommandStructuralSystem::Activated(), ArchComponent.Component::execute(), ArchCurtainWall.CurtainWall::execute(), ArchTruss.Truss::execute(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated(), and PathTests.TestPathHelix.TestPathHelix::test04().
copy()
Part::Geometry * Sketcher::ExternalGeometryFacade::copy (void) const
References Part::Geometry::copy().
copyId()
void ExternalGeometryFacade::copyId (const Part::Geometry * src, Part::Geometry * dst) static
References getFacade().
deleteExtension() [1/2]
void Sketcher::ExternalGeometryFacade::deleteExtension (Base::Type type)
deleteExtension() [2/2]
void Sketcher::ExternalGeometryFacade::deleteExtension (const std::string & name)
ensureSketchGeometryExtensions()
void ExternalGeometryFacade::ensureSketchGeometryExtensions (Part::Geometry * geometry) static
References Base::BaseClass::getClassTypeId().
flagSize()
virtual size_t Sketcher::ExternalGeometryFacade::flagSize () const override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
getBlocked()
bool Sketcher::ExternalGeometryFacade::getBlocked () const
References Sketcher::GeometryMode::Blocked.
getConstruction()
bool Sketcher::ExternalGeometryFacade::getConstruction (void) const
References Sketcher::GeometryMode::Construction.
getExtension() [1/2]
std::weak_ptr< const Part::GeometryExtension > Sketcher::ExternalGeometryFacade::getExtension (Base::Type type) const
getExtension() [2/2]
std::weak_ptr< const Part::GeometryExtension > Sketcher::ExternalGeometryFacade::getExtension (const std::string & name) const
getExtensions()
std::vector< std::weak_ptr< const Part::GeometryExtension > > Sketcher::ExternalGeometryFacade::getExtensions () const
getExternalExtensionName()
const std::string & Sketcher::ExternalGeometryFacade::getExternalExtensionName () const
getFacade() [1/2]
std::unique_ptr< const ExternalGeometryFacade > ExternalGeometryFacade::getFacade (const Part::Geometry * geometry) static
getFacade() [2/2]
std::unique_ptr< ExternalGeometryFacade > ExternalGeometryFacade::getFacade (Part::Geometry * geometry) static
Referenced by copyId().
getGeometry() [1/2]
template<typename GeometryT = Part::Geometry, typename = typename std::enable_if< std::is_base_of<Part::Geometry, typename std::decay<GeometryT>::type>::value >::type> GeometryT * Sketcher::ExternalGeometryFacade::getGeometry ()
getGeometry() [2/2]
template<typename GeometryT = Part::Geometry, typename = typename std::enable_if< std::is_base_of<Part::Geometry, typename std::decay<GeometryT>::type>::value >::type> GeometryT * Sketcher::ExternalGeometryFacade::getGeometry () const
getGeometryLayerId()
virtual int Sketcher::ExternalGeometryFacade::getGeometryLayerId () const override virtual
Implements Sketcher::ISketchGeometryExtension.
getId()
virtual long Sketcher::ExternalGeometryFacade::getId () const override virtual
GeometryExtension Interface.
Implements Sketcher::ISketchGeometryExtension.
getInternalType()
virtual InternalType::InternalType Sketcher::ExternalGeometryFacade::getInternalType () const override virtual
Implements Sketcher::ISketchGeometryExtension.
getPyObject()
PyObject * ExternalGeometryFacade::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
References ExternalGeometryFacadePy.
getRef()
virtual const std::string & Sketcher::ExternalGeometryFacade::getRef () const override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
getSketchExtensionName()
const std::string & Sketcher::ExternalGeometryFacade::getSketchExtensionName () const
getTag()
boost::uuids::uuid Sketcher::ExternalGeometryFacade::getTag () const
Handle()
const Sketcher::ExternalGeometryFacade::Handle (Geom_Geometry) const &
hasExtension() [1/2]
bool Sketcher::ExternalGeometryFacade::hasExtension (Base::Type type) const
hasExtension() [2/2]
bool Sketcher::ExternalGeometryFacade::hasExtension (const std::string & name) const
isClear()
virtual bool Sketcher::ExternalGeometryFacade::isClear () const override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
mirror() [1/2]
void Sketcher::ExternalGeometryFacade::mirror (const Base::Vector3d & point)
mirror() [2/2]
void Sketcher::ExternalGeometryFacade::mirror (const Base::Vector3d & point, Base::Vector3d dir)
rotate()
void Sketcher::ExternalGeometryFacade::rotate (const Base::Placement & plm)
Referenced by PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart(), draftguitools.gui_rotate.Rotate::numericRadius(), ArchSectionPlane.SectionPlaneTaskPanel::rotateX(), ArchSectionPlane.SectionPlaneTaskPanel::rotateY(), and ArchSectionPlane.SectionPlaneTaskPanel::rotateZ().
scale()
void Sketcher::ExternalGeometryFacade::scale (const Base::Vector3d & vec, double scale)
References draftgeoutils.general::vec().
Referenced by automotive_design.cartesian_transformation_operator::scl(), config_control_design.cartesian_transformation_operator::scl(), ifc2x3.ifccartesiantransformationoperator::scl(), and ifc4.ifccartesiantransformationoperator::scl().
setBlocked()
void Sketcher::ExternalGeometryFacade::setBlocked (bool status = true)
References Sketcher::GeometryMode::Blocked.
setConstruction()
void Sketcher::ExternalGeometryFacade::setConstruction (bool construction)
References Sketcher::GeometryMode::Construction.
setExtension()
void Sketcher::ExternalGeometryFacade::setExtension (std::unique_ptr< Part::GeometryExtension > && geo)
References draftfunctions.move::move().
setFlag()
virtual void Sketcher::ExternalGeometryFacade::setFlag (int flag, bool v = true) override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
setGeometry()
void ExternalGeometryFacade::setGeometry (Part::Geometry * geometry)
setGeometryLayerId()
virtual void Sketcher::ExternalGeometryFacade::setGeometryLayerId (int geolayer) override virtual
Implements Sketcher::ISketchGeometryExtension.
setGeometryMode()
virtual void Sketcher::ExternalGeometryFacade::setGeometryMode (int flag, bool v = true) override virtual
Implements Sketcher::ISketchGeometryExtension.
setId()
virtual void Sketcher::ExternalGeometryFacade::setId (long id) override virtual
Implements Sketcher::ISketchGeometryExtension.
setInternalType()
virtual void Sketcher::ExternalGeometryFacade::setInternalType (InternalType::InternalType type) override virtual
Implements Sketcher::ISketchGeometryExtension.
setRef()
virtual void Sketcher::ExternalGeometryFacade::setRef (const std::string & ref) override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
testFlag()
virtual bool Sketcher::ExternalGeometryFacade::testFlag (int flag) const override virtual
External GeometryExtension Interface.
Implements Sketcher::ISketchExternalGeometryExtension.
testGeometryMode()
virtual bool Sketcher::ExternalGeometryFacade::testGeometryMode (int flag) const override virtual
Implements Sketcher::ISketchGeometryExtension.
toShape()
TopoDS_Shape Sketcher::ExternalGeometryFacade::toShape () const
Geometry Interface.
transform()
void Sketcher::ExternalGeometryFacade::transform (const Base::Matrix4D & mat)
Referenced by importSVG.svgHandler::applyTrans(), importSVG.svgHandler::characters(), importSVG.svgHandler::endElement(), ArchSite.Compass::locate(), ArchSite.Compass::rotate(), and ArchSite.Compass::scale().
translate()
void Sketcher::ExternalGeometryFacade::translate (const Base::Vector3d & vec)
References draftgeoutils.general::vec().
Friends And Related Function Documentation
ExternalGeometryFacadePy
friend class ExternalGeometryFacadePy friend
Referenced by getPyObject().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/App/ExternalGeometryFacade.h
FreeCAD/src/Mod/Sketcher/App/ExternalGeometryFacade.cpp