FreeCAD: DrawSketchHandlerLineSet Class Reference
DrawSketchHandlerLineSet Class Reference
Public Types
enum SEGMENT_MODE { SEGMENT_MODE_Arc, SEGMENT_MODE_Line }
enum SELECT_MODE { STATUS_SEEK_First, STATUS_SEEK_Second, STATUS_Do, STATUS_Close }
mode table
enum SNAP_MODE { SNAP_MODE_Free, SNAP_MODE_45Degree }
enum TRANSITION_MODE { TRANSITION_MODE_Free, TRANSITION_MODE_Tangent, TRANSITION_MODE_Perpendicular_L, TRANSITION_MODE_Perpendicular_R }
Public Member Functions
virtual void activated (ViewProviderSketch *)
DrawSketchHandlerLineSet ()
virtual void mouseMove (Base::Vector2d onSketchPos)
virtual bool pressButton (Base::Vector2d onSketchPos)
virtual void quit (void)
virtual void registerPressedKey (bool pressed, int key)
virtual bool releaseButton (Base::Vector2d onSketchPos)
virtual ~DrawSketchHandlerLineSet ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::none, bool createowncommand=true)
virtual void deactivated (ViewProviderSketch *)
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Member Functions
void updateTransitionData (int GeoId, Sketcher::PointPos PosId)
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
void addCursorTail (std::vector< QPixmap > &pixmaps)
void applyCursor (QCursor &newCursor)
void applyCursor (void)
qreal devicePixelRatio ()
unsigned long getCrosshairColor ()
void setCrosshairColor ()
void setCrosshairCursor (const char *svgName)
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
Sets a cursor for 3D inventor view.
void setSvgCursor (const QString &svgName, int x, int y, const std::map< unsigned long, unsigned long > &colorMapping=std::map< unsigned long, unsigned long >())
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
void unsetCursor (void)
Protected Attributes
double arcRadius
Base::Vector2d CenterPoint
Base::Vector3d dirVec
std::vector< Base::Vector2d > EditCurve
double endAngle
int firstCurve
Sketcher::PointPos firstPosId
bool firstsegment
SELECT_MODE Mode
int previousCurve
Sketcher::PointPos previousPosId
SEGMENT_MODE SegmentMode
SNAP_MODE SnapMode
double startAngle
std::vector< AutoConstraint > sugConstr1
std::vector< AutoConstraint > sugConstr2
bool suppressTransition
TRANSITION_MODE TransitionMode
std::vector< AutoConstraint > virtualsugConstr1
Protected Attributes inherited from SketcherGui::DrawSketchHandler
QCursor actCursor
QPixmap actCursorPixmap
QCursor oldCursor
ViewProviderSketch * sketchgui
Member Enumeration Documentation
SEGMENT_MODE
enum DrawSketchHandlerLineSet::SEGMENT_MODE
Enumerator
SEGMENT_MODE_Arc
SEGMENT_MODE_Line
SELECT_MODE
enum DrawSketchHandlerLineSet::SELECT_MODE
mode table
Enumerator
STATUS_SEEK_First
enum value -—.
STATUS_SEEK_Second
enum value -—.
STATUS_Do
STATUS_Close
SNAP_MODE
enum DrawSketchHandlerLineSet::SNAP_MODE
Enumerator
SNAP_MODE_Free
SNAP_MODE_45Degree
TRANSITION_MODE
enum DrawSketchHandlerLineSet::TRANSITION_MODE
Enumerator
TRANSITION_MODE_Free
TRANSITION_MODE_Tangent
TRANSITION_MODE_Perpendicular_L
TRANSITION_MODE_Perpendicular_R
Constructor & Destructor Documentation
DrawSketchHandlerLineSet()
DrawSketchHandlerLineSet::DrawSketchHandlerLineSet ()
~DrawSketchHandlerLineSet()
virtual DrawSketchHandlerLineSet::~DrawSketchHandlerLineSet () virtual
Member Function Documentation
activated()
virtual void DrawSketchHandlerLineSet::activated (ViewProviderSketch *) virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::setCrosshairCursor().
mouseMove()
virtual void DrawSketchHandlerLineSet::mouseMove (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::applyCursor(), arcRadius, CenterPoint, dirVec, SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, endAngle, Mode, SketcherGui::DrawSketchHandler::renderSuggestConstraintsCursor(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), SEGMENT_MODE_Arc, SEGMENT_MODE_Line, SegmentMode, SketcherGui::DrawSketchHandler::setPositionText(), SketcherGui::DrawSketchHandler::sketchgui, SNAP_MODE_45Degree, SNAP_MODE_Free, startAngle, STATUS_SEEK_First, STATUS_SEEK_Second, sugConstr1, sugConstr2, suppressTransition, TRANSITION_MODE_Free, TRANSITION_MODE_Perpendicular_L, TRANSITION_MODE_Perpendicular_R, TRANSITION_MODE_Tangent, TransitionMode, Base::Vector2d::x, Base::Vector3< _Precision >::x, Base::Vector2d::y, and Base::Vector3< _Precision >::y.
Referenced by registerPressedKey(), and releaseButton().
pressButton()
virtual bool DrawSketchHandlerLineSet::pressButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::applyCursor(), Sketcher::SketchObject::arePointsCoincident(), Sketcher::Coincident, SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, Sketcher::end, firstCurve, firstPosId, App::GetApplication(), ParameterGrp::GetBool(), Base::Persistence::getClassTypeId(), Sketcher::SketchObject::getGeometry(), Sketcher::SketchObject::getGeoVertexIndex(), SketcherGui::DrawSketchHandler::getHighestCurveIndex(), App::Application::GetParameterGroupByPath(), SketcherGui::ViewProviderSketch::getPreselectCross(), SketcherGui::ViewProviderSketch::getPreselectPoint(), SketcherGui::ViewProviderSketch::getSketchObject(), Base::Persistence::getTypeId(), Mode, Sketcher::none, previousCurve, previousPosId, SketcherGui::ViewProviderSketch::purgeHandler(), SketcherGui::DrawSketchHandler::resetPositionText(), SEGMENT_MODE_Arc, SEGMENT_MODE_Line, SegmentMode, SketcherGui::DrawSketchHandler::sketchgui, SNAP_MODE_Free, Sketcher::start, STATUS_Close, STATUS_Do, STATUS_SEEK_First, STATUS_SEEK_Second, sugConstr1, suppressTransition, TRANSITION_MODE_Free, TRANSITION_MODE_Tangent, TransitionMode, SketcherGui::DrawSketchHandler::unsetCursor(), updateTransitionData(), and virtualsugConstr1.
quit()
virtual void DrawSketchHandlerLineSet::quit (void) virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::applyCursor(), SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, firstCurve, firstPosId, firstsegment, App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), Mode, Sketcher::none, previousCurve, previousPosId, SEGMENT_MODE_Line, SegmentMode, SketcherGui::DrawSketchHandler::sketchgui, SNAP_MODE_Free, STATUS_SEEK_First, suppressTransition, TRANSITION_MODE_Free, and TransitionMode.
registerPressedKey()
virtual void DrawSketchHandlerLineSet::registerPressedKey (bool pressed, int key) virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References EditCurve, Base::Persistence::getClassTypeId(), Sketcher::SketchObject::getGeometry(), SketcherGui::ViewProviderSketch::getSketchObject(), Base::Persistence::getTypeId(), Mode, mouseMove(), previousCurve, SEGMENT_MODE_Arc, SEGMENT_MODE_Line, SegmentMode, SketcherGui::DrawSketchHandler::sketchgui, SNAP_MODE_Free, STATUS_SEEK_Second, TRANSITION_MODE_Free, TRANSITION_MODE_Perpendicular_L, TRANSITION_MODE_Perpendicular_R, TRANSITION_MODE_Tangent, and TransitionMode.
releaseButton()
virtual bool DrawSketchHandlerLineSet::releaseButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), SketcherGui::DrawSketchHandler::applyCursor(), arcRadius, SketcherGui::ViewProviderSketch::Autoconstraints, SketcherGui::ViewProviderSketch::AvoidRedundant, CenterPoint, Gui::cmdAppObjectArgs(), Sketcher::Coincident, Gui::Command::commitCommand(), Base::Console(), SketcherGui::DrawSketchHandler::createAutoConstraints(), SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, Sketcher::end, endAngle, Base::ConsoleSingleton::Error(), firstCurve, firstPosId, firstsegment, SketcherGui::geometryCreationMode, App::GetApplication(), ParameterGrp::GetBool(), SketcherGui::DrawSketchHandler::getHighestCurveIndex(), Gui::ViewProviderDocumentObject::getObject(), App::Application::GetParameterGroupByPath(), App::PropertyBool::getValue(), Mode, mouseMove(), Sketcher::none, Gui::Command::openCommand(), previousCurve, previousPosId, SketcherGui::ViewProviderSketch::purgeHandler(), draftutils.translate::QT_TRANSLATE_NOOP, SketcherGui::DrawSketchHandler::resetPositionText(), SEGMENT_MODE_Arc, SEGMENT_MODE_Line, SegmentMode, SketcherGui::DrawSketchHandler::sketchgui, SNAP_MODE_45Degree, SNAP_MODE_Free, Sketcher::start, startAngle, STATUS_Close, STATUS_Do, STATUS_SEEK_First, STATUS_SEEK_Second, sugConstr1, sugConstr2, suppressTransition, TRANSITION_MODE_Free, TRANSITION_MODE_Perpendicular_L, TRANSITION_MODE_Perpendicular_R, TRANSITION_MODE_Tangent, TransitionMode, SketcherGui::tryAutoRecomputeIfNotSolve(), SketcherGui::DrawSketchHandler::unsetCursor(), updateTransitionData(), virtualsugConstr1, Base::Vector2d::x, and Base::Vector2d::y.
updateTransitionData()
void DrawSketchHandlerLineSet::updateTransitionData (int GeoId, Sketcher::PointPos PosId) protected
References dirVec, EditCurve, Part::GeomArcOfConic::getCenter(), Base::Persistence::getClassTypeId(), Part::GeomLineSegment::getEndPoint(), Part::GeomArcOfConic::getEndPoint(), Sketcher::SketchObject::getGeometry(), SketcherGui::ViewProviderSketch::getSketchObject(), Part::GeomLineSegment::getStartPoint(), Part::GeomArcOfConic::getStartPoint(), Base::Persistence::getTypeId(), Base::Vector3< _Precision >::Normalize(), Base::Vector3< _Precision >::Set(), SketcherGui::DrawSketchHandler::sketchgui, Sketcher::start, Base::Vector3< _Precision >::x, and Base::Vector3< _Precision >::y.
Referenced by pressButton(), and releaseButton().
Member Data Documentation
arcRadius
double DrawSketchHandlerLineSet::arcRadius protected
Referenced by mouseMove(), and releaseButton().
CenterPoint
Base::Vector2d DrawSketchHandlerLineSet::CenterPoint protected
Referenced by mouseMove(), and releaseButton().
dirVec
Base::Vector3d DrawSketchHandlerLineSet::dirVec protected
Referenced by mouseMove(), and updateTransitionData().
EditCurve
std::vector<Base::Vector2d> DrawSketchHandlerLineSet::EditCurve protected
Referenced by mouseMove(), pressButton(), quit(), registerPressedKey(), releaseButton(), and updateTransitionData().
endAngle
double DrawSketchHandlerLineSet::endAngle protected
Referenced by mouseMove(), and releaseButton().
firstCurve
int DrawSketchHandlerLineSet::firstCurve protected
Referenced by pressButton(), quit(), and releaseButton().
firstPosId
Sketcher::PointPos DrawSketchHandlerLineSet::firstPosId protected
Referenced by pressButton(), quit(), and releaseButton().
firstsegment
bool DrawSketchHandlerLineSet::firstsegment protected
Referenced by quit(), and releaseButton().
Mode
SELECT_MODE DrawSketchHandlerLineSet::Mode protected
Referenced by mouseMove(), pressButton(), quit(), registerPressedKey(), and releaseButton().
previousCurve
int DrawSketchHandlerLineSet::previousCurve protected
Referenced by pressButton(), quit(), registerPressedKey(), and releaseButton().
previousPosId
Sketcher::PointPos DrawSketchHandlerLineSet::previousPosId protected
Referenced by pressButton(), quit(), and releaseButton().
SegmentMode
SEGMENT_MODE DrawSketchHandlerLineSet::SegmentMode protected
Referenced by mouseMove(), pressButton(), quit(), registerPressedKey(), and releaseButton().
SnapMode
SNAP_MODE DrawSketchHandlerLineSet::SnapMode protected
startAngle
double DrawSketchHandlerLineSet::startAngle protected
Referenced by mouseMove(), and releaseButton().
sugConstr1
std::vector<AutoConstraint> DrawSketchHandlerLineSet::sugConstr1 protected
Referenced by mouseMove(), pressButton(), and releaseButton().
sugConstr2
std::vector<AutoConstraint> DrawSketchHandlerLineSet::sugConstr2 protected
Referenced by mouseMove(), and releaseButton().
suppressTransition
bool DrawSketchHandlerLineSet::suppressTransition protected
Referenced by mouseMove(), pressButton(), quit(), and releaseButton().
TransitionMode
TRANSITION_MODE DrawSketchHandlerLineSet::TransitionMode protected
Referenced by mouseMove(), pressButton(), quit(), registerPressedKey(), and releaseButton().
virtualsugConstr1
std::vector<AutoConstraint> DrawSketchHandlerLineSet::virtualsugConstr1 protected
Referenced by pressButton(), and releaseButton().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/Gui/CommandCreateGeo.cpp