FreeCAD: SMESH::Controls::ConnectedElements Class Reference
SMESH::Controls::ConnectedElements Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
ConnectedElements ()
Class ConnectedElements.
int GetNode () const
std::vector< double > GetPoint () const
virtual SMDSAbs_ElementType GetType () const
virtual bool IsSatisfy (long theElementId)
virtual void SetMesh (const SMDS_Mesh *theMesh)
void SetNode (int nodeID)
void SetPoint (double x, double y, double z)
void SetType (SMDSAbs_ElementType theType)
Public Member Functions inherited from SMESH::Controls::Functor
~Functor ()
Constructor & Destructor Documentation
ConnectedElements()
ConnectedElements::ConnectedElements ()
Class ConnectedElements.
Member Function Documentation
GetNode()
int ConnectedElements::GetNode () const
GetPoint()
std::vector< double > ConnectedElements::GetPoint () const
GetType()
SMDSAbs_ElementType ConnectedElements::GetType () const virtual
Implements SMESH::Controls::Predicate.
IsSatisfy()
bool ConnectedElements::IsSatisfy (long theElementId) virtual
Implements SMESH::Controls::Predicate.
References SMDS_Mesh::FindNode(), SMDS_MeshElement::GetID(), SMDS_MeshNode::GetInverseElementIterator(), SMESH::Controls::TMeshModifTracer::GetMesh(), SMDS_Mesh::GetMeshInfo(), SMDS_MeshElement::GetType(), SMDS_MeshInfo::NbElements(), and SMDS_MeshElement::nodesIterator().
Referenced by SetNode(), and SetPoint().
SetMesh()
void ConnectedElements::SetMesh (const SMDS_Mesh * theMesh) virtual
Implements SMESH::Controls::Functor.
References SMESH::Controls::TMeshModifTracer::IsMeshModified(), SMESH::Controls::TMeshModifTracer::SetMesh(), and SetPoint().
SetNode()
void ConnectedElements::SetNode (int nodeID)
References SMDS_Mesh::FindNode(), SMESH::Controls::TMeshModifTracer::GetMesh(), SMESH::Controls::TMeshModifTracer::IsMeshModified(), and IsSatisfy().
SetPoint()
void ConnectedElements::SetPoint (double x, double y, double z)
References SMESH_ElementSearcher::FindElementsByPoint(), SMESH_MeshAlgos::GetElementSearcher(), SMESH::Controls::TMeshModifTracer::GetMesh(), SMESH::Controls::TMeshModifTracer::IsMeshModified(), and IsSatisfy().
Referenced by SetMesh().
SetType()
void ConnectedElements::SetType (SMDSAbs_ElementType theType)
References SMESH::Controls::TMeshModifTracer::IsMeshModified().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp