FreeCAD: Measure::MeasurementPy Class Reference
Measure::MeasurementPy Class Reference
The python export class for Measurement.
#include <MeasurementPy.h>
Public Types
typedef Measurement * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
MeasurementPy (Measurement *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Measurement * getMeasurementPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of MeasurementPy.
static PyMethodDef Methods []
Methods structure of MeasurementPy.
static PyTypeObject Type
Type structure of MeasurementPy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~MeasurementPy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * addReference3D (PyObject *args)
implementer for the addReference3D() method
PyObject * has3DReferences (PyObject *args)
implementer for the has3DReferences() method
PyObject * clear (PyObject *args)
implementer for the clear() method
PyObject * delta (PyObject *args)
implementer for the delta() method
PyObject * length (PyObject *args)
implementer for the length() method
PyObject * angle (PyObject *args)
implementer for the angle() method
PyObject * radius (PyObject *args)
implementer for the radius() method
PyObject * com (PyObject *args)
implementer for the com() method
static PyObject * staticCallback_addReference3D (PyObject *self, PyObject *args)
callback for the addReference3D() method
static PyObject * staticCallback_has3DReferences (PyObject *self, PyObject *args)
callback for the has3DReferences() method
static PyObject * staticCallback_clear (PyObject *self, PyObject *args)
callback for the clear() method
static PyObject * staticCallback_delta (PyObject *self, PyObject *args)
callback for the delta() method
static PyObject * staticCallback_length (PyObject *self, PyObject *args)
callback for the length() method
static PyObject * staticCallback_angle (PyObject *self, PyObject *args)
callback for the angle() method
static PyObject * staticCallback_radius (PyObject *self, PyObject *args)
callback for the radius() method
static PyObject * staticCallback_com (PyObject *self, PyObject *args)
callback for the com() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Measurement.
Member Typedef Documentation
PointerType
typedef Measurement* Measure::MeasurementPy::PointerType
Constructor & Destructor Documentation
~MeasurementPy()
MeasurementPy::~MeasurementPy () protected
MeasurementPy()
MeasurementPy::MeasurementPy (Measurement * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
addReference3D()
PyObject * MeasurementPy::addReference3D (PyObject * args)
implementer for the addReference3D() method
References App::Application::getActiveDocument(), App::GetApplication(), getMeasurementPtr(), and App::Document::getObject().
Referenced by staticCallback_addReference3D().
angle()
PyObject * MeasurementPy::angle (PyObject * args)
implementer for the angle() method
References Measure::Measurement::angle(), and getMeasurementPtr().
Referenced by drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), PathScripts.PathDressupDogbone.Bone::adaptiveLength(), draftguitools.gui_rotate.Rotate::build_copy_subelements_command(), draftguitools.gui_rotate.Rotate::build_rotate_subelements_command(), DraftGui.DraftToolBar::changeAngleValue(), PathScripts.PathDressupDogbone.Bone::corner(), drafttaskpanels.task_polararray.TaskPanelPolarArray::create_object(), PathScripts.PathDressupHoldingTags.Tag::createSolidsAt(), PathScripts.PathDressupDogbone.Bone::distance(), draftguitools.gui_arcs.Arc::drawArc(), PathScripts.PathDressupRampEntry.ObjectDressup::execute(), PathScripts.PathDressupRampEntry.ObjectDressup::generateRamps(), draftguitools.gui_arcs.Arc::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), drafttaskpanels.task_polararray.TaskPanelPolarArray::print_messages(), draftguitools.gui_rotate.Rotate::rotate_object(), staticCallback_angle(), DraftGui.DraftToolBar::toggleAngle(), draftguitools.gui_arcs.Arc::updateAngle(), and drafttaskpanels.task_polararray.TaskPanelPolarArray::validate_input().
clear()
PyObject * MeasurementPy::clear (PyObject * args)
implementer for the clear() method
References Measure::Measurement::clear(), and getMeasurementPtr().
Referenced by staticCallback_clear().
com()
PyObject * MeasurementPy::com (PyObject * args)
implementer for the com() method
References getMeasurementPtr().
Referenced by PathScripts.post.comparams_post.saveVals::retVals(), and staticCallback_com().
delta()
PyObject * MeasurementPy::delta (PyObject * args)
implementer for the delta() method
References getMeasurementPtr().
Referenced by draftguitools.gui_scale.Scale::build_copy_subelements_command(), draftguitools.gui_scale.Scale::build_scale_subelements_command(), draftguitools.gui_scale.Scale::scale_object(), draftguitools.gui_scale.Scale::scale_with_clone(), staticCallback_delta(), Mod.Test.UnitTests.UnitBasicCases::testEnergy(), Mod.Test.UnitTests.UnitBasicCases::testImperial(), Mod.Test.UnitTests.UnitBasicCases::testSchemes(), and Mod.Test.UnitTests.UnitBasicCases::testVoltage().
getCustomAttributes()
PyObject * MeasurementPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getMeasurementPtr()
Measurement * MeasurementPy::getMeasurementPtr (void) const
getter for the object handled by this class
Referenced by addReference3D(), angle(), clear(), com(), delta(), has3DReferences(), length(), and radius().
GetType()
virtual PyTypeObject* Measure::MeasurementPy::GetType (void) virtual
Reimplemented from Base::BaseClassPy.
has3DReferences()
PyObject * MeasurementPy::has3DReferences (PyObject * args)
implementer for the has3DReferences() method
References getMeasurementPtr().
Referenced by staticCallback_has3DReferences().
length()
PyObject * MeasurementPy::length (PyObject * args)
implementer for the length() method
References getMeasurementPtr(), and Measure::Measurement::length().
Referenced by PathScripts.PathStock.StockFromBase::execute(), PathScripts.PathPocketShape.Extension::getSubLink(), PathScripts.PathPocketShape.Extension::getWire(), Mod.PartDesign.Scripts.FilletArc.Vector::norm(), and staticCallback_length().
PyInit()
int MeasurementPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::BaseClassPy.
PyMake()
PyObject * MeasurementPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References MeasurementPy().
radius()
PyObject * MeasurementPy::radius (PyObject * args)
implementer for the radius() method
References getMeasurementPtr(), and Measure::Measurement::radius().
Referenced by PathScripts.PathPocketBase.ObjectPocket::areaOpAreaParams(), PathScripts.PathProfile.ObjectProfile::areaOpAreaParams(), PathScripts.PathPocketBase.ObjectPocket::areaOpPathParams(), PathScripts.PathAreaOp.ObjectOp::areaOpSetDefaultValues(), DraftGui.DraftToolBar::changeRadiusValue(), PathScripts.PathHelix.ObjectHelix::circularHoleExecute(), PathScripts.PathDressupHoldingTags.Tag::createSolidsAt(), PathScripts.PathSurface.ObjectSurface::deleteOpVariables(), PathScripts.PathWaterline.ObjectWaterline::deleteOpVariables(), PathScripts.PathOp.ObjectOp::execute(), PathScripts.PathDressupAxisMap.TaskPanel::getFields(), PathScripts.PathHelix.ObjectHelix::helix_cut(), ifc4.ifcsweptdisksolid::innerradiussize(), draftguitools.gui_snapper.Snapper::off(), PathScripts.PathSurfaceSupport.ProcessSelectedFaces::preProcessModel(), draftguitools.gui_snapper.Snapper::showradius(), draftguitools.gui_snapper.Snapper::snapToCrossExtensions(), draftguitools.gui_snapper.Snapper::snapToExtensions(), draftguitools.gui_snapper.Snapper::snapToGrid(), draftguitools.gui_snapper.Snapper::snapToHold(), draftguitools.gui_snapper.Snapper::snapToObject(), draftguitools.gui_snapper.Snapper::snapToPolar(), staticCallback_radius(), DraftGui.DraftToolBar::taskUi(), PathScripts.PathDressupAxisMap.TaskPanel::updateUI(), DraftGui.DraftToolBar::validatePoint(), automotive_design.right_circular_cone::wr1(), automotive_design.conical_surface::wr1(), config_control_design.conical_surface::wr1(), automotive_design.swept_disk_solid::wr2(), and ifc2x3.ifcsweptdisksolid::wr2().
representation()
std::string MeasurementPy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int MeasurementPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_addReference3D()
PyObject * MeasurementPy::staticCallback_addReference3D (PyObject * self, PyObject * args) static
callback for the addReference3D() method
References addReference3D(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_angle()
PyObject * MeasurementPy::staticCallback_angle (PyObject * self, PyObject * args) static
callback for the angle() method
References angle(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_clear()
PyObject * MeasurementPy::staticCallback_clear (PyObject * self, PyObject * args) static
callback for the clear() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, clear(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_com()
PyObject * MeasurementPy::staticCallback_com (PyObject * self, PyObject * args) static
callback for the com() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, com(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_delta()
PyObject * MeasurementPy::staticCallback_delta (PyObject * self, PyObject * args) static
callback for the delta() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, delta(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_has3DReferences()
PyObject * MeasurementPy::staticCallback_has3DReferences (PyObject * self, PyObject * args) static
callback for the has3DReferences() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, has3DReferences(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_length()
PyObject * MeasurementPy::staticCallback_length (PyObject * self, PyObject * args) static
callback for the length() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), length(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_radius()
PyObject * MeasurementPy::staticCallback_radius (PyObject * self, PyObject * args) static
callback for the radius() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), radius(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef MeasurementPy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of MeasurementPy.
Methods
PyMethodDef MeasurementPy::Methods static
Methods structure of MeasurementPy.
Type
PyTypeObject MeasurementPy::Type static
Type structure of MeasurementPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Measure/App/MeasurementPy.h
Sources/FreeCAD/src/Mod/Measure/App/MeasurementPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Measure/App/MeasurementPy.cpp