FreeCAD: Measure::Measurement Class Reference
Measure::Measurement Class Reference
#include <Measurement.h>
Public Member Functions
int addReference3D (App::DocumentObject *obj, const char *subName)
add a 3D reference (obj+sub) to end of list
int addReference3D (App::DocumentObject *obj, const std::string &subName)
Add a reference.
double angle (const Base::Vector3d &param=Base::Vector3d(0, 0, 0)) const
void clear ()
Base::Vector3d delta () const
virtual unsigned int getMemSize (void) const
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
MeasureType getType ()
bool has3DReferences ()
double length () const
Base::Vector3d massCenter () const
Measurement ()
double radius () const
~Measurement ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual Type getTypeId (void) const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Attributes
App::PropertyLinkSubList References3D
Protected Member Functions
TopoDS_Shape getShape (App::DocumentObject *obj, const char *subName) const
Protected Attributes
MeasureType measureType
Py::Object PythonObject
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
Measurement()
Measurement::Measurement ()
References App::Global, and Measure::Invalid.
~Measurement()
Measurement::~Measurement ()
Member Function Documentation
addReference3D() [1/2]
int Measurement::addReference3D (App::DocumentObject * obj, const char * subName)
add a 3D reference (obj+sub) to end of list
References draftutils.utils::getType.
addReference3D() [2/2]
int Measurement::addReference3D (App::DocumentObject * obj, const std::string & subName)
Add a reference.
Referenced by TechDraw::DrawViewDimension::setAll3DMeasurement().
angle()
double Measurement::angle (const Base::Vector3d & param = Base::Vector3d(0,0,0)) const
References Base::Console(), Measure::Edges, Base::ConsoleSingleton::Error(), and Measure::Invalid.
Referenced by drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), PathScripts.PathDressupDogbone.Bone::adaptiveLength(), Measure::MeasurementPy::angle(), draftguitools.gui_rotate.Rotate::build_copy_subelements_command(), draftguitools.gui_rotate.Rotate::build_rotate_subelements_command(), DraftGui.DraftToolBar::changeAngleValue(), PathScripts.PathDressupDogbone.Bone::corner(), drafttaskpanels.task_polararray.TaskPanelPolarArray::create_object(), PathScripts.PathDressupHoldingTags.Tag::createSolidsAt(), PathScripts.PathDressupDogbone.Bone::distance(), draftguitools.gui_arcs.Arc::drawArc(), PathScripts.PathDressupRampEntry.ObjectDressup::execute(), PathScripts.PathDressupRampEntry.ObjectDressup::generateRamps(), TechDraw::DrawViewDimension::getDimValue(), draftguitools.gui_arcs.Arc::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), drafttaskpanels.task_polararray.TaskPanelPolarArray::print_messages(), draftguitools.gui_rotate.Rotate::rotate_object(), DraftGui.DraftToolBar::toggleAngle(), draftguitools.gui_arcs.Arc::updateAngle(), and drafttaskpanels.task_polararray.TaskPanelPolarArray::validate_input().
clear()
void Measurement::clear (void)
References Measure::Invalid.
Referenced by Measure::MeasurementPy::clear(), TechDraw::DrawViewDimension::clear3DMeasurements(), and TechDraw::DrawViewDimension::setAll3DMeasurement().
delta()
Base::Vector3d Measurement::delta () const
References Base::Console(), Measure::Edges, Base::ConsoleSingleton::Error(), Measure::Invalid, Measure::PointToEdge, and Measure::PointToSurface.
Referenced by draftguitools.gui_scale.Scale::build_copy_subelements_command(), draftguitools.gui_scale.Scale::build_scale_subelements_command(), draftguitools.gui_scale.Scale::scale_object(), draftguitools.gui_scale.Scale::scale_with_clone(), Mod.Test.UnitTests.UnitBasicCases::testEnergy(), Mod.Test.UnitTests.UnitBasicCases::testImperial(), Mod.Test.UnitTests.UnitBasicCases::testSchemes(), and Mod.Test.UnitTests.UnitBasicCases::testVoltage().
getMemSize()
unsigned int Measurement::getMemSize (void) const virtual
getPyObject()
PyObject * Measurement::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
getShape()
TopoDS_Shape Measurement::getShape (App::DocumentObject * obj, const char * subName) const protected
References Part::Feature::getShape().
getType()
MeasureType Measurement::getType (void)
References Measure::Edges, Part::Feature::getShape(), Measure::Invalid, Measure::Points, Measure::PointToEdge, Measure::PointToSurface, Measure::Surfaces, and Measure::Volumes.
Referenced by PathScripts.PathToolEdit.ToolEditor::updateToolType(), and PathScripts.PathToolEdit.ToolEditor::updateUI().
has3DReferences()
bool Measurement::has3DReferences ()
Referenced by TechDraw::DrawViewDimension::getDimValue(), and TechDraw::DrawViewDimension::onChanged().
length()
double Measurement::length () const
References Base::Console(), Measure::Edges, Base::ConsoleSingleton::Error(), Measure::Invalid, Measure::PointToEdge, and Measure::PointToSurface.
Referenced by PathScripts.PathStock.StockFromBase::execute(), TechDraw::DrawViewDimension::getDimValue(), PathScripts.PathPocketShape.Extension::getSubLink(), PathScripts.PathPocketShape.Extension::getWire(), Measure::MeasurementPy::length(), and Mod.PartDesign.Scripts.FilletArc.Vector::norm().
massCenter()
Base::Vector3d Measurement::massCenter () const
References Base::Console(), Base::ConsoleSingleton::Error(), Measure::Invalid, and Measure::Volumes.
radius()
double Measurement::radius () const
References Base::Console(), Measure::Edges, and Base::ConsoleSingleton::Error().
Referenced by PathScripts.PathPocketBase.ObjectPocket::areaOpAreaParams(), PathScripts.PathProfile.ObjectProfile::areaOpAreaParams(), PathScripts.PathPocketBase.ObjectPocket::areaOpPathParams(), PathScripts.PathAreaOp.ObjectOp::areaOpSetDefaultValues(), DraftGui.DraftToolBar::changeRadiusValue(), PathScripts.PathHelix.ObjectHelix::circularHoleExecute(), PathScripts.PathDressupHoldingTags.Tag::createSolidsAt(), PathScripts.PathSurface.ObjectSurface::deleteOpVariables(), PathScripts.PathWaterline.ObjectWaterline::deleteOpVariables(), PathScripts.PathOp.ObjectOp::execute(), TechDraw::DrawViewDimension::getDimValue(), PathScripts.PathDressupAxisMap.TaskPanel::getFields(), PathScripts.PathHelix.ObjectHelix::helix_cut(), ifc4.ifcsweptdisksolid::innerradiussize(), draftguitools.gui_snapper.Snapper::off(), PathScripts.PathSurfaceSupport.ProcessSelectedFaces::preProcessModel(), Measure::MeasurementPy::radius(), draftguitools.gui_snapper.Snapper::showradius(), draftguitools.gui_snapper.Snapper::snapToCrossExtensions(), draftguitools.gui_snapper.Snapper::snapToExtensions(), draftguitools.gui_snapper.Snapper::snapToGrid(), draftguitools.gui_snapper.Snapper::snapToHold(), draftguitools.gui_snapper.Snapper::snapToObject(), draftguitools.gui_snapper.Snapper::snapToPolar(), DraftGui.DraftToolBar::taskUi(), PathScripts.PathDressupAxisMap.TaskPanel::updateUI(), DraftGui.DraftToolBar::validatePoint(), automotive_design.right_circular_cone::wr1(), automotive_design.conical_surface::wr1(), config_control_design.conical_surface::wr1(), automotive_design.swept_disk_solid::wr2(), and ifc2x3.ifcsweptdisksolid::wr2().
Member Data Documentation
measureType
MeasureType Measure::Measurement::measureType protected
PythonObject
Py::Object Measure::Measurement::PythonObject protected
References3D
App::PropertyLinkSubList Measure::Measurement::References3D
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Measure/App/Measurement.h
Sources/FreeCAD/src/Mod/Measure/App/Measurement.cpp