FreeCAD: Base::ILoggerBlocker Class Reference
Base::ILoggerBlocker Class Reference
The ILoggerBlocker class This class allows to temporary block then automatically restore arbitrary message types on a particular console observer.
#include <ConsoleObserver.h>
Public Member Functions
ILoggerBlocker (const char *co, ConsoleMsgFlags msgTypes=ConsoleSingleton::MsgType_Txt|ConsoleSingleton::MsgType_Log|ConsoleSingleton::MsgType_Wrn|ConsoleSingleton::MsgType_Err)
ILoggerBlocker (ILoggerBlocker const &&)=delete
ILoggerBlocker (ILoggerBlocker const &)=delete
ILoggerBlocker & operator= (ILoggerBlocker const &&)=delete
ILoggerBlocker & operator= (ILoggerBlocker const &)=delete
~ILoggerBlocker ()
Detailed Description
The ILoggerBlocker class This class allows to temporary block then automatically restore arbitrary message types on a particular console observer.
Constructor & Destructor Documentation
ILoggerBlocker() [1/3]
Base::ILoggerBlocker::ILoggerBlocker (const char * co, ConsoleMsgFlags msgTypes = ConsoleSingleton::MsgType_Txt | ConsoleSingleton::MsgType_Log | ConsoleSingleton::MsgType_Wrn | ConsoleSingleton::MsgType_Err) explicit
References Base::Console(), and Base::ConsoleSingleton::SetEnabledMsgType().
ILoggerBlocker() [2/3]
Base::ILoggerBlocker::ILoggerBlocker (ILoggerBlocker const &) delete
ILoggerBlocker() [3/3]
Base::ILoggerBlocker::ILoggerBlocker (ILoggerBlocker const &&) delete
~ILoggerBlocker()
Base::ILoggerBlocker::~ILoggerBlocker ()
References Base::Console(), Base::ConsoleSingleton::SetEnabledMsgType(), and Base::ConsoleSingleton::Warning().
Member Function Documentation
operator=() [1/2]
ILoggerBlocker & Base::ILoggerBlocker::operator= (ILoggerBlocker const &&) delete
operator=() [2/2]
ILoggerBlocker & Base::ILoggerBlocker::operator= (ILoggerBlocker const &) delete
The documentation for this class was generated from the following file:
FreeCAD/src/Base/ConsoleObserver.h