FreeCAD: Sketcher::GeometryFacadePy Class Reference
Sketcher::GeometryFacadePy Class Reference
The python export class for GeometryFacade.
#include <GeometryFacadePy.h>
Public Types
typedef GeometryFacade * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
GeometryFacadePy (GeometryFacade *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of GeometryFacadePy.
static PyMethodDef Methods []
Methods structure of GeometryFacadePy.
static PyTypeObject Type
Type structure of GeometryFacadePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~GeometryFacadePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * testGeometryMode (PyObject *args)
implementer for the testGeometryMode() method
PyObject * setGeometryMode (PyObject *args)
implementer for the setGeometryMode() method
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * hasExtensionOfType (PyObject *args)
implementer for the hasExtensionOfType() method
PyObject * hasExtensionOfName (PyObject *args)
implementer for the hasExtensionOfName() method
PyObject * getExtensionOfType (PyObject *args)
implementer for the getExtensionOfType() method
PyObject * getExtensionOfName (PyObject *args)
implementer for the getExtensionOfName() method
PyObject * setExtension (PyObject *args)
implementer for the setExtension() method
PyObject * deleteExtensionOfType (PyObject *args)
implementer for the deleteExtensionOfType() method
PyObject * deleteExtensionOfName (PyObject *args)
implementer for the deleteExtensionOfName() method
PyObject * getExtensions (PyObject *args)
implementer for the getExtensions() method
static PyObject * staticCallback_testGeometryMode (PyObject *self, PyObject *args)
callback for the testGeometryMode() method
static PyObject * staticCallback_setGeometryMode (PyObject *self, PyObject *args)
callback for the setGeometryMode() method
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_hasExtensionOfType (PyObject *self, PyObject *args)
callback for the hasExtensionOfType() method
static PyObject * staticCallback_hasExtensionOfName (PyObject *self, PyObject *args)
callback for the hasExtensionOfName() method
static PyObject * staticCallback_getExtensionOfType (PyObject *self, PyObject *args)
callback for the getExtensionOfType() method
static PyObject * staticCallback_getExtensionOfName (PyObject *self, PyObject *args)
callback for the getExtensionOfName() method
static PyObject * staticCallback_setExtension (PyObject *self, PyObject *args)
callback for the setExtension() method
static PyObject * staticCallback_deleteExtensionOfType (PyObject *self, PyObject *args)
callback for the deleteExtensionOfType() method
static PyObject * staticCallback_deleteExtensionOfName (PyObject *self, PyObject *args)
callback for the deleteExtensionOfName() method
static PyObject * staticCallback_getExtensions (PyObject *self, PyObject *args)
callback for the getExtensions() method
callbacks and implementers for the python object attributes
Py::Long getId (void) const
getter for the Id attribute
void setId (Py::Long arg)
setter for the Id attribute
Py::String getInternalType (void) const
getter for the InternalType attribute
void setInternalType (Py::String arg)
setter for the InternalType attribute
Py::Boolean getBlocked (void) const
getter for the Blocked attribute
void setBlocked (Py::Boolean arg)
setter for the Blocked attribute
Py::Boolean getConstruction (void) const
getter for the Construction attribute
void setConstruction (Py::Boolean arg)
setter for the Construction attribute
Py::String getTag (void) const
getter for the Tag attribute
Py::Object getGeometry (void) const
getter for the Geometry attribute
void setGeometry (Py::Object arg)
setter for the Geometry attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeometryFacade * getGeometryFacadePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getId (PyObject *self, void *closure)
getter callback for the Id attribute
static int staticCallback_setId (PyObject *self, PyObject *value, void *closure)
setter callback for the Id attribute
static PyObject * staticCallback_getInternalType (PyObject *self, void *closure)
getter callback for the InternalType attribute
static int staticCallback_setInternalType (PyObject *self, PyObject *value, void *closure)
setter callback for the InternalType attribute
static PyObject * staticCallback_getBlocked (PyObject *self, void *closure)
getter callback for the Blocked attribute
static int staticCallback_setBlocked (PyObject *self, PyObject *value, void *closure)
setter callback for the Blocked attribute
static PyObject * staticCallback_getConstruction (PyObject *self, void *closure)
getter callback for the Construction attribute
static int staticCallback_setConstruction (PyObject *self, PyObject *value, void *closure)
setter callback for the Construction attribute
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
static PyObject * staticCallback_getGeometry (PyObject *self, void *closure)
getter callback for the Geometry attribute
static int staticCallback_setGeometry (PyObject *self, PyObject *value, void *closure)
setter callback for the Geometry attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeometryFacade.
Member Typedef Documentation
PointerType
typedef GeometryFacade* Sketcher::GeometryFacadePy::PointerType
Constructor & Destructor Documentation
~GeometryFacadePy()
GeometryFacadePy::~GeometryFacadePy () protected
GeometryFacadePy()
GeometryFacadePy::GeometryFacadePy (GeometryFacade * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
deleteExtensionOfName()
PyObject * GeometryFacadePy::deleteExtensionOfName (PyObject * args)
implementer for the deleteExtensionOfName() method
References Sketcher::GeometryFacade::deleteExtension(), getGeometryFacadePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_deleteExtensionOfName().
deleteExtensionOfType()
PyObject * GeometryFacadePy::deleteExtensionOfType (PyObject * args)
implementer for the deleteExtensionOfType() method
References Base::Type::badType(), Sketcher::GeometryFacade::deleteExtension(), Base::Type::fromName(), getGeometryFacadePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_deleteExtensionOfType().
getBlocked()
Py::Boolean GeometryFacadePy::getBlocked (void) const
getter for the Blocked attribute
References getGeometryFacadePtr().
Referenced by staticCallback_getBlocked().
getConstruction()
Py::Boolean GeometryFacadePy::getConstruction (void) const
getter for the Construction attribute
References getGeometryFacadePtr().
Referenced by staticCallback_getConstruction().
getCustomAttributes()
PyObject * GeometryFacadePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getExtensionOfName()
PyObject * GeometryFacadePy::getExtensionOfName (PyObject * args)
implementer for the getExtensionOfName() method
References getGeometryFacadePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getExtensionOfName().
getExtensionOfType()
PyObject * GeometryFacadePy::getExtensionOfType (PyObject * args)
implementer for the getExtensionOfType() method
References Base::Type::badType(), Base::Type::fromName(), getGeometryFacadePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getExtensionOfType().
getExtensions()
PyObject * GeometryFacadePy::getExtensions (PyObject * args)
implementer for the getExtensions() method
References Sketcher::GeometryFacade::getExtensions(), getGeometryFacadePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getExtensions().
getGeometry()
Py::Object GeometryFacadePy::getGeometry (void) const
getter for the Geometry attribute
References draftmake.make_clone::clone, getGeometryFacadePtr(), and Base::BaseClass::getPyObject().
Referenced by staticCallback_getGeometry().
getGeometryFacadePtr()
GeometryFacade * GeometryFacadePy::getGeometryFacadePtr (void) const
getter for the object handled by this class
Referenced by deleteExtensionOfName(), deleteExtensionOfType(), getBlocked(), getConstruction(), getExtensionOfName(), getExtensionOfType(), getExtensions(), getGeometry(), getId(), getInternalType(), getTag(), hasExtensionOfName(), hasExtensionOfType(), mirror(), PyInit(), representation(), rotate(), scale(), setBlocked(), setConstruction(), setExtension(), setGeometry(), Sketcher::SketchObjectPy::setGeometryFacadeList(), setGeometryMode(), setId(), setInternalType(), testGeometryMode(), transform(), and translate().
getId()
Py::Long GeometryFacadePy::getId (void) const
getter for the Id attribute
References getGeometryFacadePtr().
Referenced by staticCallback_getId().
getInternalType()
Py::String GeometryFacadePy::getInternalType (void) const
getter for the InternalType attribute
References getGeometryFacadePtr(), Sketcher::GeometryFacade::getInternalType(), Sketcher::SketchGeometryExtension::internaltype2str, and Sketcher::InternalType::NumInternalGeometryType.
Referenced by staticCallback_getInternalType().
getTag()
Py::String GeometryFacadePy::getTag (void) const
getter for the Tag attribute
References getGeometryFacadePtr().
Referenced by staticCallback_getTag().
GetType()
virtual PyTypeObject* Sketcher::GeometryFacadePy::GetType (void) virtual
Reimplemented from Base::BaseClassPy.
hasExtensionOfName()
PyObject * GeometryFacadePy::hasExtensionOfName (PyObject * args)
implementer for the hasExtensionOfName() method
References getGeometryFacadePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_hasExtensionOfName().
hasExtensionOfType()
PyObject * GeometryFacadePy::hasExtensionOfType (PyObject * args)
implementer for the hasExtensionOfType() method
References Base::Type::badType(), Base::Type::fromName(), getGeometryFacadePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_hasExtensionOfType().
mirror()
PyObject * GeometryFacadePy::mirror (PyObject * args)
implementer for the mirror() method
References getGeometryFacadePtr(), Sketcher::GeometryFacade::mirror(), Part::PartExceptionOCCError, Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_mirror().
PyInit()
int GeometryFacadePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::BaseClassPy.
References Part::Geometry::clone(), getGeometryFacadePtr(), Sketcher::GeometryFacade::setGeometry(), and Part::GeometryPy::Type.
PyMake()
PyObject * GeometryFacadePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References GeometryFacadePy().
representation()
std::string GeometryFacadePy::representation (void) const
References getGeometryFacadePtr(), and Sketcher::GeometryFacade::getId().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
rotate()
PyObject * GeometryFacadePy::rotate (PyObject * args)
implementer for the rotate() method
References getGeometryFacadePtr(), Sketcher::GeometryFacade::rotate(), and Base::PlacementPy::Type.
Referenced by staticCallback_rotate().
scale()
PyObject * GeometryFacadePy::scale (PyObject * args)
implementer for the scale() method
References getGeometryFacadePtr(), Part::PartExceptionOCCError, Sketcher::GeometryFacade::scale(), Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_scale().
setBlocked()
void GeometryFacadePy::setBlocked (Py::Boolean arg)
setter for the Blocked attribute
References getGeometryFacadePtr(), and Sketcher::GeometryFacade::setBlocked().
Referenced by staticCallback_setBlocked().
setConstruction()
void GeometryFacadePy::setConstruction (Py::Boolean arg)
setter for the Construction attribute
References getGeometryFacadePtr(), and Sketcher::GeometryFacade::setConstruction().
Referenced by staticCallback_setConstruction().
setCustomAttributes()
int GeometryFacadePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setExtension()
PyObject * GeometryFacadePy::setExtension (PyObject * args)
implementer for the setExtension() method
References getGeometryFacadePtr(), draftfunctions.move::move(), Part::PartExceptionOCCError, Sketcher::GeometryFacade::setExtension(), and Part::GeometryExtensionPy::Type.
Referenced by staticCallback_setExtension().
setGeometry()
void GeometryFacadePy::setGeometry (Py::Object arg)
setter for the Geometry attribute
References Part::Geometry::clone(), getGeometryFacadePtr(), Part::GeometryPy::getGeometryPtr(), Sketcher::GeometryFacade::setGeometry(), and Part::GeometryPy::Type.
Referenced by staticCallback_setGeometry().
setGeometryMode()
PyObject * GeometryFacadePy::setGeometryMode (PyObject * args)
implementer for the setGeometryMode() method
References getGeometryFacadePtr(), Sketcher::SketchGeometryExtension::getGeometryModeFromName(), and Sketcher::GeometryFacade::setGeometryMode().
Referenced by staticCallback_setGeometryMode().
setId()
void GeometryFacadePy::setId (Py::Long arg)
setter for the Id attribute
References getGeometryFacadePtr(), and Sketcher::GeometryFacade::setId().
Referenced by staticCallback_setId().
setInternalType()
void GeometryFacadePy::setInternalType (Py::String arg)
setter for the InternalType attribute
References getGeometryFacadePtr(), Sketcher::SketchGeometryExtension::getInternalTypeFromName(), and Sketcher::GeometryFacade::setInternalType().
Referenced by staticCallback_setInternalType().
staticCallback_deleteExtensionOfName()
PyObject * GeometryFacadePy::staticCallback_deleteExtensionOfName (PyObject * self, PyObject * args) static
callback for the deleteExtensionOfName() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, deleteExtensionOfName(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_deleteExtensionOfType()
PyObject * GeometryFacadePy::staticCallback_deleteExtensionOfType (PyObject * self, PyObject * args) static
callback for the deleteExtensionOfType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, deleteExtensionOfType(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getBlocked()
PyObject * GeometryFacadePy::staticCallback_getBlocked (PyObject * self, void * closure) static
getter callback for the Blocked attribute
References Base::BaseExceptionFreeCADError, getBlocked(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getConstruction()
PyObject * GeometryFacadePy::staticCallback_getConstruction (PyObject * self, void * closure) static
getter callback for the Construction attribute
References Base::BaseExceptionFreeCADError, getConstruction(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getExtensionOfName()
PyObject * GeometryFacadePy::staticCallback_getExtensionOfName (PyObject * self, PyObject * args) static
callback for the getExtensionOfName() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getExtensionOfName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getExtensionOfType()
PyObject * GeometryFacadePy::staticCallback_getExtensionOfType (PyObject * self, PyObject * args) static
callback for the getExtensionOfType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getExtensionOfType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getExtensions()
PyObject * GeometryFacadePy::staticCallback_getExtensions (PyObject * self, PyObject * args) static
callback for the getExtensions() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getExtensions(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getGeometry()
PyObject * GeometryFacadePy::staticCallback_getGeometry (PyObject * self, void * closure) static
getter callback for the Geometry attribute
References Base::BaseExceptionFreeCADError, getGeometry(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getId()
PyObject * GeometryFacadePy::staticCallback_getId (PyObject * self, void * closure) static
getter callback for the Id attribute
References Base::BaseExceptionFreeCADError, getId(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getInternalType()
PyObject * GeometryFacadePy::staticCallback_getInternalType (PyObject * self, void * closure) static
getter callback for the InternalType attribute
References Base::BaseExceptionFreeCADError, getInternalType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTag()
PyObject * GeometryFacadePy::staticCallback_getTag (PyObject * self, void * closure) static
getter callback for the Tag attribute
References Base::BaseExceptionFreeCADError, getTag(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_hasExtensionOfName()
PyObject * GeometryFacadePy::staticCallback_hasExtensionOfName (PyObject * self, PyObject * args) static
callback for the hasExtensionOfName() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hasExtensionOfName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_hasExtensionOfType()
PyObject * GeometryFacadePy::staticCallback_hasExtensionOfType (PyObject * self, PyObject * args) static
callback for the hasExtensionOfType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hasExtensionOfType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_mirror()
PyObject * GeometryFacadePy::staticCallback_mirror (PyObject * self, PyObject * args) static
callback for the mirror() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), mirror(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_rotate()
PyObject * GeometryFacadePy::staticCallback_rotate (PyObject * self, PyObject * args) static
callback for the rotate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), rotate(), and Base::PyObjectBase::startNotify().
staticCallback_scale()
PyObject * GeometryFacadePy::staticCallback_scale (PyObject * self, PyObject * args) static
callback for the scale() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), scale(), and Base::PyObjectBase::startNotify().
staticCallback_setBlocked()
int GeometryFacadePy::staticCallback_setBlocked (PyObject * self, PyObject * value, void * closure) static
setter callback for the Blocked attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setBlocked().
staticCallback_setConstruction()
int GeometryFacadePy::staticCallback_setConstruction (PyObject * self, PyObject * value, void * closure) static
setter callback for the Construction attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setConstruction().
staticCallback_setExtension()
PyObject * GeometryFacadePy::staticCallback_setExtension (PyObject * self, PyObject * args) static
callback for the setExtension() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setExtension(), and Base::PyObjectBase::startNotify().
staticCallback_setGeometry()
int GeometryFacadePy::staticCallback_setGeometry (PyObject * self, PyObject * value, void * closure) static
setter callback for the Geometry attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setGeometry().
staticCallback_setGeometryMode()
PyObject * GeometryFacadePy::staticCallback_setGeometryMode (PyObject * self, PyObject * args) static
callback for the setGeometryMode() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setGeometryMode(), and Base::PyObjectBase::startNotify().
staticCallback_setId()
int GeometryFacadePy::staticCallback_setId (PyObject * self, PyObject * value, void * closure) static
setter callback for the Id attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setId().
staticCallback_setInternalType()
int GeometryFacadePy::staticCallback_setInternalType (PyObject * self, PyObject * value, void * closure) static
setter callback for the InternalType attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setInternalType().
staticCallback_setTag()
int GeometryFacadePy::staticCallback_setTag (PyObject * self, PyObject * value, void * closure) static
setter callback for the Tag attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_testGeometryMode()
PyObject * GeometryFacadePy::staticCallback_testGeometryMode (PyObject * self, PyObject * args) static
callback for the testGeometryMode() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and testGeometryMode().
staticCallback_transform()
PyObject * GeometryFacadePy::staticCallback_transform (PyObject * self, PyObject * args) static
callback for the transform() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and transform().
staticCallback_translate()
PyObject * GeometryFacadePy::staticCallback_translate (PyObject * self, PyObject * args) static
callback for the translate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and translate().
testGeometryMode()
PyObject * GeometryFacadePy::testGeometryMode (PyObject * args)
implementer for the testGeometryMode() method
References getGeometryFacadePtr(), and Sketcher::SketchGeometryExtension::getGeometryModeFromName().
Referenced by staticCallback_testGeometryMode().
transform()
PyObject * GeometryFacadePy::transform (PyObject * args)
implementer for the transform() method
References getGeometryFacadePtr(), Sketcher::GeometryFacade::transform(), and Base::MatrixPy::Type.
Referenced by staticCallback_transform().
translate()
PyObject * GeometryFacadePy::translate (PyObject * args)
implementer for the translate() method
References getGeometryFacadePtr(), Part::PartExceptionOCCError, Sketcher::GeometryFacade::translate(), Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_translate().
Member Data Documentation
GetterSetter
PyGetSetDef GeometryFacadePy::GetterSetter static
Attribute structure of GeometryFacadePy.
Methods
PyMethodDef GeometryFacadePy::Methods static
Methods structure of GeometryFacadePy.
Type
PyTypeObject GeometryFacadePy::Type static
Type structure of GeometryFacadePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), and Sketcher::SketchObjectPy::setGeometryFacadeList().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Sketcher/App/GeometryFacadePy.h
Sources/FreeCAD/src/Mod/Sketcher/App/GeometryFacadePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Sketcher/App/GeometryFacadePy.cpp