FreeCAD: femviewprovider.view_constant_vacuumpermittivity.VPConstantVacuumPermittivity Class Reference
femviewprovider.view_constant_vacuumpermittivity.VPConstantVacuumPermittivity Class Reference
Public Member Functions
def getIcon (self)
Public Member Functions inherited from femviewprovider.view_base_femconstraint.VPBaseFemConstraint
def attach (self, vobj)
def getDefaultDisplayMode (self)
def getDisplayModes (self, obj)
def setDisplayMode (self, mode)
Public Member Functions inherited from femviewprovider.view_base_femobject.VPBaseFemObject
def attach (self, vobj)
def doubleClicked (self, vobj)
def getIcon (self)
def setEdit (self, vobj, mode=0, TaskPanel=None, hide_mesh=True)
def unsetEdit (self, vobj, mode=0)
Additional Inherited Members
Public Attributes inherited from femviewprovider.view_base_femconstraint.VPBaseFemConstraint
Object
Public Attributes inherited from femviewprovider.view_base_femobject.VPBaseFemObject
Object
Member Function Documentation
getIcon()
def femviewprovider.view_constant_vacuumpermittivity.VPConstantVacuumPermittivity.getIcon (self)
after load from FCStd file, self.icon does not exist, return constant path instead
Reimplemented from femviewprovider.view_base_femobject.VPBaseFemObject.
Referenced by ArchAxisSystem.AxisSystemTaskPanel.update(), ArchComponent.ComponentTaskPanel.update(), and ArchSectionPlane.SectionPlaneTaskPanel.update().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Fem/femviewprovider/view_constant_vacuumpermittivity.py