FreeCAD: TechDrawGui::TaskDlgSectionView Class Reference
TechDrawGui::TaskDlgSectionView Class Reference
#include <TaskSectionView.h>
Public Member Functions
virtual bool accept ()
is called by the framework if an button is clicked which has no accept or reject role
virtual QDialogButtonBox::StandardButtons getStandardButtons () const
tells the framework which buttons are wished for the dialog
virtual void helpRequested ()
is called by the framework if the user presses the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual void open ()
is called the TaskView when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgSectionView (TechDraw::DrawViewPart *base)
TaskDlgSectionView (TechDraw::DrawViewSection *section)
void update ()
~TaskDlgSectionView ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual bool isAllowedAlterView (void) const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Constructor & Destructor Documentation
TaskDlgSectionView() [1/2]
TaskDlgSectionView::TaskDlgSectionView (TechDraw::DrawViewPart * base)
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
TaskDlgSectionView() [2/2]
TaskDlgSectionView::TaskDlgSectionView (TechDraw::DrawViewSection * section)
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
~TaskDlgSectionView()
TaskDlgSectionView::~TaskDlgSectionView ()
Member Function Documentation
accept()
bool TaskDlgSectionView::accept (void) virtual
is called by the framework if an button is clicked which has no accept or reject role
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References TechDrawGui::TaskSectionView::accept().
getStandardButtons()
virtual QDialogButtonBox::StandardButtons TechDrawGui::TaskDlgSectionView::getStandardButtons (void) const virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
helpRequested()
virtual void TechDrawGui::TaskDlgSectionView::helpRequested () virtual
is called by the framework if the user presses the help button
Reimplemented from Gui::TaskView::TaskDialog.
isAllowedAlterDocument()
virtual bool TechDrawGui::TaskDlgSectionView::isAllowedAlterDocument (void) const virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
isAllowedAlterSelection()
virtual bool TechDrawGui::TaskDlgSectionView::isAllowedAlterSelection (void) const virtual
Indicates whether this task dialog allows other commands to modify the selection while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
open()
void TaskDlgSectionView::open () virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
reject()
bool TaskDlgSectionView::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References TechDrawGui::TaskSectionView::reject().
update()
void TaskDlgSectionView::update ()
Referenced by ArchAxis.CommandArchGrid::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/TaskSectionView.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/TaskSectionView.cpp