FreeCAD: Gui::TreeParams Class Reference
Gui::TreeParams Class Reference
Helper class to read/write tree view options.
#include <Tree.h>
Public Member Functions
void OnChange (Base::Subject< const char * > &, const char *sReason)
TreeParams ()
Static Public Member Functions
static TreeParams * Instance ()
Detailed Description
Helper class to read/write tree view options.
The parameters are stored under group "User parameter:BaseApp/Preferences/TreeView". Call TreeParams::Instance()->ParamName/setParamName() to get/set parameter. To add a new parameter, add a new line under FC_TREEPARAM_DEFS using macro
FC_TREEPARAM_DEF(parameter_name, c_type, parameter_type, default_value)
If there is special handling on parameter change, use FC_TREEPARAM_DEF2() instead, and add a function with the following signature in Tree.cpp,
void TreeParams:on<ParamName>Changed()
Constructor & Destructor Documentation
TreeParams()
TreeParams::TreeParams ()
References Base::Subject< _MessageType >::Attach(), App::GetApplication(), and App::Application::GetParameterGroupByPath().
Referenced by Instance().
Member Function Documentation
Instance()
TreeParams * TreeParams::Instance (void) static
References TreeParams().
Referenced by Gui::TreeWidget::dropEvent(), Gui::DocumentItem::findRootIndex(), Gui::TreeWidget::leaveEvent(), Gui::TreeWidget::onPreSelectTimer(), Gui::TreeWidget::onSelectionChanged(), Gui::TreeWidget::onSelectTimer(), Gui::TreeWidget::selectAll(), Gui::TreeWidget::showEvent(), Gui::TreeWidget::syncView(), and Gui::TreePanel::TreePanel().
OnChange()
FC_TREEPARAM_DEFS void TreeParams::OnChange (Base::Subject< const char * > & , const char * sReason)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Tree.h
Sources/FreeCAD/src/Gui/Tree.cpp