FreeCAD: Mesh::GTSAlgos Class Reference
Mesh::GTSAlgos Class Reference
The mesh algorithms container class.
#include <GTSAlgos.h>
Public Member Functions
void boolean (const Mesh::MeshObject &ToolMesh, int Type=0)
makes a boolean add The int Type stears the boolean oberation: 0=add;1=intersection;2=diff
void coarsen (float f)
Coarsen the mesh.
GTSAlgos (Mesh::MeshObject &Mesh)
Static Public Member Functions
static GtsSurface * createGTSSurface (const Mesh::MeshObject &Mesh)
Creates a GTS Surface from a MeshKernel.
static void fillMeshFromGTSSurface (Mesh::MeshObject &Mesh, GtsSurface *pSurface)
Creates a GTS Surface from a MeshKernel.
Detailed Description
The mesh algorithms container class.
Constructor & Destructor Documentation
GTSAlgos()
Mesh::GTSAlgos::GTSAlgos (Mesh::MeshObject & Mesh)
Member Function Documentation
boolean()
void GTSAlgos::boolean (const Mesh::MeshObject & ToolMesh, int Type = 0)
makes a boolean add The int Type stears the boolean oberation: 0=add;1=intersection;2=diff
References createGTSSurface(), and fillMeshFromGTSSurface().
coarsen()
void GTSAlgos::coarsen (float f)
Coarsen the mesh.
References createGTSSurface(), and fillMeshFromGTSSurface().
createGTSSurface()
GtsSurface * GTSAlgos::createGTSSurface (const Mesh::MeshObject & Mesh) static
Creates a GTS Surface from a MeshKernel.
References Base::Console(), and Base::ConsoleSingleton::Log().
Referenced by boolean(), and coarsen().
fillMeshFromGTSSurface()
void GTSAlgos::fillMeshFromGTSSurface (Mesh::MeshObject & Mesh, GtsSurface * pSurface) static
Creates a GTS Surface from a MeshKernel.
Referenced by boolean(), and coarsen().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/GTSAlgos.h
FreeCAD/src/Mod/Mesh/App/GTSAlgos.cpp