FreeCAD: femexamples.constraint_contact_solid_solid Namespace Reference
femexamples.constraint_contact_solid_solid Namespace Reference
Functions
def get_explanation (header="")
def get_information ()
def setup (doc=None, solvertype="ccxtools")
Function Documentation
get_explanation()
def femexamples.constraint_contact_solid_solid.get_explanation (header = "")
Referenced by femexamples.constraint_contact_solid_solid.setup().
get_information()
def femexamples.constraint_contact_solid_solid.get_information ()
Referenced by femexamples.constraint_contact_solid_solid.setup().
setup()
def femexamples.constraint_contact_solid_solid.setup (doc = None, solvertype = "ccxtools")
References femexamples.constraint_contact_solid_solid.get_explanation(), femexamples.constraint_contact_solid_solid.get_information(), ObjectsFem.makeAnalysis(), ObjectsFem.makeConstraintContact(), ObjectsFem.makeConstraintFixed(), ObjectsFem.makeConstraintPressure(), ObjectsFem.makeMaterialSolid(), ObjectsFem.makeMeshGmsh(), ObjectsFem.makeSolverCalculix(), and ObjectsFem.makeSolverCalculixCcxTools().