FreeCAD: iisWinXPTaskPanelScheme2 Class Reference
iisWinXPTaskPanelScheme2 Class Reference
#include <iiswinxptaskpanelscheme.h>
Public Member Functions
iisWinXPTaskPanelScheme2 (QObject *parent=0)
~iisWinXPTaskPanelScheme2 ()
Public Member Functions inherited from iisTaskPanelScheme
iisTaskPanelScheme (QObject *parent=0)
~iisTaskPanelScheme ()
Static Public Member Functions
static iisTaskPanelScheme * defaultScheme ()
Static Public Member Functions inherited from iisTaskPanelScheme
static iisTaskPanelScheme * defaultScheme ()
Static Protected Attributes
static iisWinXPTaskPanelScheme2 * myDefaultXPScheme = 0
Static Protected Attributes inherited from iisTaskPanelScheme
static iisTaskPanelScheme * myDefaultScheme = 0
Additional Inherited Members
Public Attributes inherited from iisTaskPanelScheme
QBrush groupBackground
QPen groupBorder
int groupFoldDelay
int groupFoldSteps
bool headerAnimation
QBrush headerBackground
QPen headerBorder
QIcon headerButtonFold
QIcon headerButtonFoldOver
QSize headerButtonSize
QIcon headerButtonUnfold
QIcon headerButtonUnfoldOver
iisIconLabelScheme headerLabelScheme
int headerSize
QBrush panelBackground
iisIconLabelScheme taskLabelScheme
Constructor & Destructor Documentation
iisWinXPTaskPanelScheme2()
iisWinXPTaskPanelScheme2::iisWinXPTaskPanelScheme2 (QObject * parent = 0)
References iisTaskPanelScheme::groupBackground, iisTaskPanelScheme::groupBorder, iisTaskPanelScheme::headerAnimation, iisTaskPanelScheme::headerBackground, iisTaskPanelScheme::headerBorder, iisTaskPanelScheme::headerButtonFold, iisTaskPanelScheme::headerButtonFoldOver, iisTaskPanelScheme::headerButtonSize, iisTaskPanelScheme::headerButtonUnfold, iisTaskPanelScheme::headerButtonUnfoldOver, iisTaskPanelScheme::headerLabelScheme, iisTaskPanelScheme::headerSize, iisIconLabelScheme::iconSize, iisTaskPanelScheme::panelBackground, iisTaskPanelScheme::taskLabelScheme, iisIconLabelScheme::text, and iisIconLabelScheme::textOver.
Referenced by defaultScheme().
~iisWinXPTaskPanelScheme2()
iisWinXPTaskPanelScheme2::~iisWinXPTaskPanelScheme2 ()
Member Function Documentation
defaultScheme()
iisTaskPanelScheme * iisWinXPTaskPanelScheme2::defaultScheme () static
References iisWinXPTaskPanelScheme2(), and myDefaultXPScheme.
Referenced by test::on_rbXP_clicked(), and SandboxGui::TaskPanelView::TaskPanelView().
Member Data Documentation
myDefaultXPScheme
iisWinXPTaskPanelScheme2 * iisWinXPTaskPanelScheme2::myDefaultXPScheme = 0 static protected
Referenced by defaultScheme().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/iisTaskPanel/src/iiswinxptaskpanelscheme.h
Sources/FreeCAD/src/Gui/iisTaskPanel/src/iiswinxptaskpanelscheme.cpp