FreeCAD: draftguitools.gui_edit_draft_objects.DraftWireGuiTools Class Reference
draftguitools.gui_edit_draft_objects.DraftWireGuiTools Class Reference
Workbenches » Python workbenches » Draft » draftguitools
Public Member Functions
def delete_point (self, obj, node_idx)
def evaluate_context_menu_action (self, edit_command, obj, node_idx, action)
def get_edit_point_context_menu (self, obj, node_idx)
def get_edit_points (self, obj)
def init_preview_object (self, obj)
def update_object_from_edit_points (self, obj, node_idx, v, alt_edit_mode=0)
def update_preview_object (self, edit_command, obj, node_idx, v)
Public Member Functions inherited from draftguitools.gui_edit_base_object.GuiTools
def get_object_style (self, obj)
def restore_object_style (self, obj, modes)
def set_object_editing_style (self, obj)
Member Function Documentation
delete_point()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.delete_point (self, obj, node_idx)
Referenced by draftguitools.gui_edit_draft_objects.DraftWireGuiTools.evaluate_context_menu_action(), and draftguitools.gui_edit_draft_objects.DraftBezCurveGuiTools.evaluate_context_menu_action().
evaluate_context_menu_action()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.evaluate_context_menu_action (self, edit_command, obj, node_idx, action)
 Do something when a Draft_Edit context menu action is triggered over a node.
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
References draftguitools.gui_edit_draft_objects.DraftWireGuiTools.delete_point().
get_edit_point_context_menu()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.get_edit_point_context_menu (self, obj, node_idx)
 Return a list of Draft_Edit context menu actions.
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
get_edit_points()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.get_edit_points (self, obj)
Return to Draft_Edit a list of vectors for the given object.
Remember to use object local coordinates system.
Parameters:
obj: the object
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
init_preview_object()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.init_preview_object (self, obj)
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
Reimplemented in draftguitools.gui_edit_draft_objects.DraftBSplineGuiTools.
update_object_from_edit_points()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.update_object_from_edit_points (self, obj, node_idx, v, alt_edit_mode = 0)
Update the object from modified Draft_Edit point.
No need to recompute at the end.
Parameters:
obj: the object
node_idx: number of the edited node
v: target vector of the node in object local coordinates system
alt_edit_mode: alternative edit mode to perform different operations
               (usually can be selected from the Draft_Edit context menu)
               default = 0
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
update_preview_object()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.update_preview_object (self, edit_command, obj, node_idx, v)
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
Reimplemented in draftguitools.gui_edit_draft_objects.DraftBSplineGuiTools.
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Draft/draftguitools/gui_edit_draft_objects.py