FreeCAD: SketcherGui::Ui_ConstraintSettingsDialog Class Reference
SketcherGui::Ui_ConstraintSettingsDialog Class Reference
#include <ui_ConstraintSettingsDialog.h>
Public Member Functions
void retranslateUi (QWidget *SketcherGui__ConstraintSettingsDialog)
void setupUi (QWidget *SketcherGui__ConstraintSettingsDialog)
Public Attributes
QDialogButtonBox * buttonBox
Gui::PrefCheckBox * extendedInformation
Gui::PrefCheckBox * filterInternalAlignment
QGridLayout * gridLayout_4
QGridLayout * gridLayout_5
QGroupBox * groupBox
QGroupBox * groupBox_2
QVBoxLayout * verticalLayout
QSpacerItem * verticalSpacer
Gui::PrefCheckBox * visualisationTrackingFilter
Member Function Documentation
retranslateUi()
void SketcherGui::Ui_ConstraintSettingsDialog::retranslateUi (QWidget * SketcherGui__ConstraintSettingsDialog)
References extendedInformation, filterInternalAlignment, groupBox, groupBox_2, draftguitools.gui_setstyle::translate, and visualisationTrackingFilter.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void SketcherGui::Ui_ConstraintSettingsDialog::setupUi (QWidget * SketcherGui__ConstraintSettingsDialog)
References buttonBox, draftgeoutils.intersections::connect(), extendedInformation, filterInternalAlignment, gridLayout_4, gridLayout_5, groupBox, groupBox_2, retranslateUi(), verticalLayout, verticalSpacer, and visualisationTrackingFilter.
Member Data Documentation
buttonBox
QDialogButtonBox* SketcherGui::Ui_ConstraintSettingsDialog::buttonBox
Referenced by PathScripts.PathGetPoint.TaskPanel::getPoint(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::modifyStandardButtons(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::pageDirtyChanged(), PathScripts.PathGetPoint.TaskPanel::pointFinish(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setClean(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setDirty(), and setupUi().
extendedInformation
Gui::PrefCheckBox* SketcherGui::Ui_ConstraintSettingsDialog::extendedInformation
Referenced by retranslateUi(), and setupUi().
filterInternalAlignment
Gui::PrefCheckBox* SketcherGui::Ui_ConstraintSettingsDialog::filterInternalAlignment
Referenced by retranslateUi(), and setupUi().
gridLayout_4
QGridLayout* SketcherGui::Ui_ConstraintSettingsDialog::gridLayout_4
Referenced by setupUi().
gridLayout_5
QGridLayout* SketcherGui::Ui_ConstraintSettingsDialog::gridLayout_5
Referenced by setupUi().
groupBox
QGroupBox* SketcherGui::Ui_ConstraintSettingsDialog::groupBox
Referenced by retranslateUi(), and setupUi().
groupBox_2
QGroupBox* SketcherGui::Ui_ConstraintSettingsDialog::groupBox_2
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* SketcherGui::Ui_ConstraintSettingsDialog::verticalLayout
Referenced by setupUi().
verticalSpacer
QSpacerItem* SketcherGui::Ui_ConstraintSettingsDialog::verticalSpacer
Referenced by setupUi().
visualisationTrackingFilter
Gui::PrefCheckBox* SketcherGui::Ui_ConstraintSettingsDialog::visualisationTrackingFilter
Referenced by retranslateUi(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/ui_ConstraintSettingsDialog.h