FreeCAD: femexamples.constraint_contact_shell_shell Namespace Reference
femexamples.constraint_contact_shell_shell Namespace Reference
Functions
def get_information ()
def init_doc (doc=None)
def setup (doc=None, solvertype="ccxtools")
Variables
string mesh_name = "Mesh"
Function Documentation
get_information()
def femexamples.constraint_contact_shell_shell.get_information ()
init_doc()
def femexamples.constraint_contact_shell_shell.init_doc (doc = None)
Referenced by femexamples.constraint_contact_shell_shell.setup().
setup()
def femexamples.constraint_contact_shell_shell.setup (doc = None, solvertype = "ccxtools")
References femexamples.constraint_contact_shell_shell.init_doc(), ObjectsFem.makeAnalysis(), ObjectsFem.makeConstraintContact(), ObjectsFem.makeConstraintFixed(), ObjectsFem.makeConstraintForce(), ObjectsFem.makeElementGeometry2D(), ObjectsFem.makeMaterialSolid(), ObjectsFem.makeMeshGmsh(), ObjectsFem.makeSolverCalculix(), and ObjectsFem.makeSolverCalculixCcxTools().
Variable Documentation
mesh_name
string femexamples.constraint_contact_shell_shell.mesh_name = "Mesh"