FreeCAD: PartGui::FilletEdgesDialog Class Reference
PartGui::FilletEdgesDialog Class Reference
#include <DlgFilletEdges.h>
Public Member Functions
void accept ()
FilletEdgesDialog (DlgFilletEdges::FilletType type, Part::FilletBase *fillet, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~FilletEdgesDialog ()
Constructor & Destructor Documentation
FilletEdgesDialog()
FilletEdgesDialog::FilletEdgesDialog (DlgFilletEdges::FilletType type, Part::FilletBase * fillet, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
References accept(), and draftgeoutils.intersections::connect().
~FilletEdgesDialog()
FilletEdgesDialog::~FilletEdgesDialog ()
Member Function Documentation
accept()
void FilletEdgesDialog::accept (void)
References PartGui::DlgFilletEdges::accept().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), FilletEdgesDialog(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/DlgFilletEdges.h
FreeCAD/src/Mod/Part/Gui/DlgFilletEdges.cpp