FreeCAD: config_control_design.geometric_representation_item Class Reference
config_control_design.geometric_representation_item Class Reference
Public Member Functions
def dim ()
def wr1 (self)
Public Member Functions inherited from config_control_design.representation_item
def name ()
def wr1 (self)
Additional Inherited Members
Public Attributes inherited from config_control_design.representation_item
name
Detailed Description
Entity geometric_representation_item definition.
    :param dim
    :type dim:dimension_count
Member Function Documentation
dim()
def config_control_design.geometric_representation_item.dim ()
References config_control_design.dimension_of().
Referenced by ifc4.ifccartesiantransformationoperator3d.axis3is3d(), ifc4.ifcaxis2placement3d.axisis3d(), ifc2x3.ifcsweptsurface.dim(), ifc2x3.ifcplacement.dim(), ifc2x3.ifccartesiantransformationoperator.dim(), ifc2x3.ifccurveboundedplane.dim(), ifc2x3.ifccompositecurvesegment.dim(), ifc2x3.ifcgeometricset.dim(), ifc2x3.ifcrectangulartrimmedsurface.dim(), ifc2x3.ifcbooleanresult.dim(), ifc2x3.ifcelementarysurface.dim(), ifc2x3.ifcpointoncurve.dim(), ifc2x3.ifcpointonsurface.dim(), ifc2x3.ifcvector.dim(), ifc4.ifccompositecurvesegment.dim(), ifc4.ifcplacement.dim(), ifc4.ifccartesiantransformationoperator.dim(), ifc4.ifcgeometricset.dim(), ifc4.ifcbooleanresult.dim(), ifc4.ifcpointoncurve.dim(), ifc4.ifcpointonsurface.dim(), ifc4.ifcvector.dim(), ifc4.ifcaxis2placement3d.refdiris3d(), ifc4.ifcfillareastylehatching.refhatchline2d(), automotive_design.axis2_placement_3d.wr2(), config_control_design.axis2_placement_3d.wr2(), ifc2x3.ifcaxis2placement3d.wr2(), ifc2x3.ifcfillareastylehatching.wr23(), automotive_design.axis2_placement_3d.wr3(), config_control_design.axis2_placement_3d.wr3(), ifc2x3.ifcaxis2placement3d.wr3(), and ifc2x3.ifccartesiantransformationoperator3d.wr4().
wr1()
def config_control_design.geometric_representation_item.wr1 (self)
Reimplemented from config_control_design.representation_item.
Reimplemented in config_control_design.cartesian_transformation_operator, config_control_design.cartesian_transformation_operator_3d, config_control_design.axis2_placement_2d, config_control_design.b_spline_surface, config_control_design.axis1_placement, config_control_design.b_spline_curve, config_control_design.rational_b_spline_curve, config_control_design.direction, config_control_design.offset_curve_3d, config_control_design.composite_curve, config_control_design.composite_curve_on_surface, config_control_design.boundary_curve, config_control_design.curve_replica, config_control_design.surface_curve, config_control_design.parabola, config_control_design.rectangular_composite_surface, config_control_design.shell_based_surface_model, config_control_design.vector, config_control_design.pcurve, config_control_design.bounded_pcurve, config_control_design.intersection_curve, config_control_design.trimmed_curve, config_control_design.bounded_surface_curve, config_control_design.shell_based_wireframe_model, config_control_design.degenerate_toroidal_surface, config_control_design.point_replica, config_control_design.rectangular_trimmed_surface, config_control_design.line, config_control_design.geometric_curve_set, config_control_design.degenerate_pcurve, config_control_design.curve_bounded_surface, config_control_design.b_spline_curve_with_knots, config_control_design.seam_curve, config_control_design.axis2_placement_3d, config_control_design.rational_b_spline_surface, config_control_design.b_spline_surface_with_knots, config_control_design.advanced_face, config_control_design.surface_replica, and config_control_design.conical_surface.
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Import/App/config_control_design.py