FreeCAD: Ui_Position Class Reference
Ui_Position Class Reference
#include <ui_DlgLocationPos.h>
Public Member Functions
void retranslateUi (QWidget *Position)
void setupUi (QWidget *Position)
Public Attributes
QCheckBox * checkBox
QComboBox * comboBoxGridSize
QHBoxLayout * horizontalLayout
QHBoxLayout * horizontalLayout_2
QHBoxLayout * horizontalLayout_3
QLabel * label
QLabel * label_2
QLabel * label_3
QDoubleSpinBox * vectorX
QDoubleSpinBox * vectorY
QDoubleSpinBox * vectorZ
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void Ui_Position::retranslateUi (QWidget * Position)
References checkBox, comboBoxGridSize, label_2, label_3, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Ui_Position::setupUi (QWidget * Position)
References checkBox, comboBoxGridSize, horizontalLayout, horizontalLayout_2, horizontalLayout_3, label_2, label_3, retranslateUi(), vectorX, vectorY, vectorZ, and verticalLayout.
Referenced by Gui::TaskBoxPosition::TaskBoxPosition().
Member Data Documentation
checkBox
QCheckBox* Ui_Position::checkBox
Referenced by retranslateUi(), and setupUi().
comboBoxGridSize
QComboBox* Ui_Position::comboBoxGridSize
Referenced by retranslateUi(), and setupUi().
horizontalLayout
QHBoxLayout* Ui_Position::horizontalLayout
Referenced by setupUi().
horizontalLayout_2
QHBoxLayout* Ui_Position::horizontalLayout_2
Referenced by setupUi().
horizontalLayout_3
QHBoxLayout* Ui_Position::horizontalLayout_3
Referenced by setupUi().
label
QLabel* Ui_Position::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
label_2
QLabel* Ui_Position::label_2
Referenced by retranslateUi(), and setupUi().
label_3
QLabel* Ui_Position::label_3
Referenced by retranslateUi(), and setupUi().
vectorX
QDoubleSpinBox* Ui_Position::vectorX
Referenced by setupUi().
vectorY
QDoubleSpinBox* Ui_Position::vectorY
Referenced by setupUi().
vectorZ
QDoubleSpinBox* Ui_Position::vectorZ
Referenced by setupUi().
verticalLayout
QVBoxLayout* Ui_Position::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_DlgLocationPos.h