FreeCAD: VISCOUS_3D::_Shrinker1D Class Reference
VISCOUS_3D::_Shrinker1D Class Reference
Shrinker of nodes on the EDGE.
Public Member Functions
void AddEdge (const _LayerEdge *e, _EdgesOnShape &eos, SMESH_MesherHelper &helper)
Keep a _LayerEdge inflated along the EDGE.
void Compute (bool set3D, SMESH_MesherHelper &helper)
Move nodes on EDGE from ends where _LayerEdge's are inflated.
void RestoreParams ()
Restore initial parameters of nodes on EDGE.
void SwapSrcTgtNodes (SMESHDS_Mesh *mesh)
Replace source nodes by target nodes in shrinked mesh edges.
Detailed Description
Shrinker of nodes on the EDGE.
Member Function Documentation
AddEdge()
void _Shrinker1D::AddEdge (const _LayerEdge * e, _EdgesOnShape & eos, SMESH_MesherHelper & helper)
Keep a _LayerEdge inflated along the EDGE.
References SMESH_MesherHelper::GetMeshDS(), SMESHDS_SubMesh::GetNodes(), SMESH_MesherHelper::GetNodeU(), SMESHDS_Mesh::MeshElements(), SMDS_MeshNode::NbInverseElements(), SMESHDS_SubMesh::NbNodes(), and VISCOUS_3D::_EdgesOnShape::SWOLType().
Compute()
void _Shrinker1D::Compute (bool set3D, SMESH_MesherHelper & helper)
Move nodes on EDGE from ends where _LayerEdge's are inflated.
References SMESH_MesherHelper::GetNodeU().
RestoreParams()
void _Shrinker1D::RestoreParams ()
Restore initial parameters of nodes on EDGE.
SwapSrcTgtNodes()
void _Shrinker1D::SwapSrcTgtNodes (SMESHDS_Mesh * mesh)
Replace source nodes by target nodes in shrinked mesh edges.
References SMESHDS_SubMesh::Contains(), and SMDS_MeshNode::GetInverseElementIterator().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_ViscousLayers.cpp