FreeCAD: StdMeshers_Reversible1D Class Reference
StdMeshers_Reversible1D Class Reference
A base of reversible 1D hypotheses.
#include <StdMeshers_Reversible1D.hxx>
Public Member Functions
const char * GetObjectEntry ()
const std::vector< int > & GetReversedEdges () const
virtual std::istream & LoadFrom (std::istream &load)
virtual std::ostream & SaveTo (std::ostream &save)
void SetObjectEntry (const char *entry)
void SetReversedEdges (const std::vector< int > &ids)
StdMeshers_Reversible1D (int hypId, int studyId, SMESH_Gen *gen)
Public Member Functions inherited from SMESH_Hypothesis
void ClearParameters ()
virtual bool DataDependOnParams () const
The returned value is used by NotifySubMeshesHypothesisModification() to decide to call subMesh->AlgoStateEngine(MODIF_HYP, hyp) or not if subMesh is ready to be computed (algo+hyp==OK) but not yet computed. True result is reasonable for example if EventListeners depend on parameters of hypothesis.
virtual int GetDim () const
SMESH_Gen * GetGen () const
char * GetLastParameters () const
virtual const char * GetLibName () const
SMESH_Mesh * GetMeshByPersistentID (int id)
Find a mesh with given persistent ID.
char * GetParameters () const
virtual int GetShapeType () const
int GetStudyId () const
virtual bool IsAuxiliary () const
Return true if me is an auxiliary hypothesis.
virtual void NotifySubMeshesHypothesisModification ()
void SetLastParameters (const char *theParameters)
void SetLibName (const char *theLibName)
void SetParameters (const char *theParameters)
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)=0
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)=0
Initialize my parameter values by the mesh built on the geometry.
SMESH_Hypothesis (int hypId, int studyId, SMESH_Gen *gen)
virtual ~SMESH_Hypothesis ()
Public Member Functions inherited from SMESHDS_Hypothesis
int GetID () const
const char * GetName () const
int GetType () const
bool IsSameName (const SMESHDS_Hypothesis &other) const
Compare types of hypotheses.
bool operator!= (const SMESHDS_Hypothesis &other) const
virtual bool operator== (const SMESHDS_Hypothesis &other) const
SMESHDS_Hypothesis (int hypId)
virtual ~SMESHDS_Hypothesis ()
Additional Inherited Members
Public Types inherited from SMESH_Hypothesis
enum Hypothesis_Status {
HYP_OK = 0, HYP_MISSING, HYP_CONCURENT, HYP_BAD_PARAMETER,
HYP_HIDDEN_ALGO, HYP_HIDING_ALGO, HYP_UNKNOWN_FATAL, HYP_INCOMPATIBLE,
HYP_NOTCONFORM, HYP_ALREADY_EXIST, HYP_BAD_DIM, HYP_BAD_SUBSHAPE,
HYP_BAD_GEOMETRY, HYP_NEED_SHAPE, HYP_INCOMPAT_HYPS
}
Public Types inherited from SMESHDS_Hypothesis
enum hypothesis_type {
PARAM_ALGO, ALGO_0D, ALGO_1D, ALGO_2D,
ALGO_3D
}
Static Public Member Functions inherited from SMESH_Hypothesis
static bool IsStatusFatal (Hypothesis_Status theStatus)
Detailed Description
A base of reversible 1D hypotheses.
Constructor & Destructor Documentation
StdMeshers_Reversible1D()
StdMeshers_Reversible1D::StdMeshers_Reversible1D (int hypId, int studyId, SMESH_Gen * gen)
Member Function Documentation
GetObjectEntry()
const char* StdMeshers_Reversible1D::GetObjectEntry ()
GetReversedEdges()
const std::vector<int>& StdMeshers_Reversible1D::GetReversedEdges () const
Referenced by StdMeshers_Regular_1D::CheckHypothesis().
LoadFrom()
std::istream & StdMeshers_Reversible1D::LoadFrom (std::istream & load) virtual
Implements SMESHDS_Hypothesis.
Reimplemented in StdMeshers_Geometric1D.
Referenced by StdMeshers_Geometric1D::LoadFrom().
SaveTo()
std::ostream & StdMeshers_Reversible1D::SaveTo (std::ostream & save) virtual
Implements SMESHDS_Hypothesis.
Reimplemented in StdMeshers_Geometric1D.
References OfflineRenderingUtils::save().
Referenced by StdMeshers_Geometric1D::SaveTo().
SetObjectEntry()
void StdMeshers_Reversible1D::SetObjectEntry (const char * entry)
SetReversedEdges()
void StdMeshers_Reversible1D::SetReversedEdges (const std::vector< int > & ids)
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_Reversible1D.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_Reversible1D.cpp