FreeCAD: Gui::UiLoaderPy Class Reference
Gui::UiLoaderPy Class Reference
#include <WidgetFactory.h>
Public Member Functions
Py::Object createWidget (const Py::Tuple &)
Py::Object load (const Py::Tuple &)
Py::Object repr ()
UiLoaderPy ()
~UiLoaderPy ()
Static Public Member Functions
static void init_type (void)
Constructor & Destructor Documentation
UiLoaderPy()
UiLoaderPy::UiLoaderPy ()
~UiLoaderPy()
UiLoaderPy::~UiLoaderPy ()
Member Function Documentation
createWidget()
Py::Object UiLoaderPy::createWidget (const Py::Tuple & args)
References Gui::UiLoader::createWidget(), Gui::PythonWrapper::fromQWidget(), Gui::PythonWrapper::getWrapperName(), Gui::PythonWrapper::loadCoreModule(), Gui::PythonWrapper::loadGuiModule(), Gui::PythonWrapper::loadWidgetsModule(), and Gui::PythonWrapper::toQObject().
Referenced by init_type().
init_type()
void UiLoaderPy::init_type (void) static
References createWidget(), and load().
Referenced by Gui::Application::Application().
load()
Py::Object UiLoaderPy::load (const Py::Tuple & args)
References Gui::PythonWrapper::createChildrenNameAttributes(), Gui::PythonWrapper::fromQWidget(), Gui::PythonWrapper::getWrapperName(), Gui::PythonWrapper::loadCoreModule(), Gui::PythonWrapper::loadGuiModule(), Gui::PythonWrapper::loadWidgetsModule(), Gui::PythonWrapper::setParent(), Gui::PythonWrapper::toCString(), and Gui::PythonWrapper::toQObject().
Referenced by init_type().
repr()
Py::Object UiLoaderPy::repr ()
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/WidgetFactory.h
Sources/FreeCAD/src/Gui/WidgetFactory.cpp