FreeCAD: TechDrawGui::QGVNavStyleCAD Class Reference
TechDrawGui::QGVNavStyleCAD Class Reference
#include <QGVNavStyleCAD.h>
Public Member Functions
virtual bool allowContextMenu (QContextMenuEvent *event) override
virtual void handleKeyReleaseEvent (QKeyEvent *event) override
virtual void handleMouseMoveEvent (QMouseEvent *event) override
virtual void handleMousePressEvent (QMouseEvent *event) override
virtual void handleMouseReleaseEvent (QMouseEvent *event) override
QGVNavStyleCAD (QGVPage *qgvp)
virtual ~QGVNavStyleCAD ()
Public Member Functions inherited from TechDrawGui::QGVNavStyle
virtual bool allowContextMenu (QContextMenuEvent *event)
QGVPage * getViewer ()
virtual void handleEnterEvent (QEvent *event)
virtual void handleFocusOutEvent (QFocusEvent *event)
virtual void handleKeyPressEvent (QKeyEvent *event)
virtual void handleKeyReleaseEvent (QKeyEvent *event)
virtual void handleLeaveEvent (QEvent *event)
virtual void handleMouseMoveEvent (QMouseEvent *event)
virtual void handleMousePressEvent (QMouseEvent *event)
virtual void handleMouseReleaseEvent (QMouseEvent *event)
virtual void handleWheelEvent (QWheelEvent *event)
virtual double mouseZoomFactor (QPoint p)
virtual void pan (QPoint p)
virtual void placeBalloon (QPoint p)
virtual void pseudoContextEvent ()
QGVNavStyle (QGVPage *qgvp)
void setViewer (QGVPage *qgvp)
virtual void startClick (Qt::MouseButton b)
virtual void startPan (QPoint p)
virtual void startZoom (QPoint p)
virtual void stopClick (void)
virtual void stopPan ()
virtual void stopZoom ()
virtual void zoom (double factor)
virtual ~QGVNavStyle ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Protected Member Functions inherited from TechDrawGui::QGVNavStyle
virtual void initialize ()
virtual void setAnchor ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from TechDrawGui::QGVNavStyle
bool altdown
bool button1down
bool button2down
bool button3down
bool ctrldown
bool invertZoom
Qt::MouseButton m_clickButton
bool m_clickPending
int m_currentmode
KeyCombination m_keyCombo
bool m_panPending
int m_reversePan
int m_reverseScroll
QCursor m_saveCursor
QGVPage * m_viewer
bool m_zoomPending
bool panningActive
QPoint panOrigin
bool shiftdown
bool zoomAtCursor
bool zoomingActive
QPoint zoomOrigin
double zoomStep
Constructor & Destructor Documentation
QGVNavStyleCAD()
TechDrawGui::QGVNavStyleCAD::QGVNavStyleCAD (QGVPage * qgvp)
~QGVNavStyleCAD()
TechDrawGui::QGVNavStyleCAD::~QGVNavStyleCAD () virtual
Member Function Documentation
allowContextMenu()
bool TechDrawGui::QGVNavStyleCAD::allowContextMenu (QContextMenuEvent * event) override virtual
Reimplemented from TechDrawGui::QGVNavStyle.
handleKeyReleaseEvent()
void TechDrawGui::QGVNavStyleCAD::handleKeyReleaseEvent (QKeyEvent * event) override virtual
Reimplemented from TechDrawGui::QGVNavStyle.
References TechDrawGui::QGVNavStyle::panningActive, TechDrawGui::QGVNavStyle::stopPan(), TechDrawGui::QGVNavStyle::stopZoom(), and TechDrawGui::QGVNavStyle::zoomingActive.
handleMouseMoveEvent()
void TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent (QMouseEvent * event) override virtual
Reimplemented from TechDrawGui::QGVNavStyle.
References TechDrawGui::QGVNavStyle::getViewer(), TechDrawGui::QGVNavStyle::m_clickPending, TechDrawGui::QGVNavStyle::m_panPending, TechDrawGui::QGVNavStyle::m_zoomPending, TechDrawGui::QGVNavStyle::mouseZoomFactor(), TechDrawGui::QGVNavStyle::pan(), TechDrawGui::QGVNavStyle::panningActive, TechDrawGui::QGVPage::setBalloonCursorPos(), TechDrawGui::QGVNavStyle::startPan(), TechDrawGui::QGVNavStyle::startZoom(), TechDrawGui::QGVNavStyle::stopClick(), TechDrawGui::QGVNavStyle::zoom(), and TechDrawGui::QGVNavStyle::zoomingActive.
handleMousePressEvent()
void TechDrawGui::QGVNavStyleCAD::handleMousePressEvent (QMouseEvent * event) override virtual
Reimplemented from TechDrawGui::QGVNavStyle.
References TechDrawGui::QGVNavStyle::startClick().
handleMouseReleaseEvent()
void TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent (QMouseEvent * event) override virtual
Reimplemented from TechDrawGui::QGVNavStyle.
References TechDrawGui::QGVNavStyle::getViewer(), TechDrawGui::QGVNavStyle::m_clickButton, TechDrawGui::QGVNavStyle::m_clickPending, TechDrawGui::QGVNavStyle::m_panPending, TechDrawGui::QGVNavStyle::m_zoomPending, TechDrawGui::QGVNavStyle::panningActive, TechDrawGui::QGVNavStyle::placeBalloon(), TechDrawGui::QGVNavStyle::stopClick(), and TechDrawGui::QGVNavStyle::stopPan().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/QGVNavStyleCAD.h
FreeCAD/src/Mod/TechDraw/Gui/QGVNavStyleCAD.cpp