FreeCAD: Gui::Dialog::DlgWorkbenchesImp Class Reference
Gui::Dialog::DlgWorkbenchesImp Class Reference
#include <DlgWorkbenchesImp.h>
Public Member Functions
DlgWorkbenchesImp (QWidget *parent=nullptr)
~DlgWorkbenchesImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::CustomizeActionPage
CustomizeActionPage (QWidget *parent=nullptr)
Construction.
virtual ~CustomizeActionPage ()
Destruction.
Static Public Member Functions
static QStringList load_disabled_workbenches ()
static QStringList load_enabled_workbenches ()
Static Public Attributes
static const QString all_workbenches = QString::fromLatin1("ALL")
Protected Slots
void on_add_all_to_enabled_workbenches_btn_clicked ()
void on_add_to_enabled_workbenches_btn_clicked ()
void on_remove_from_enabled_workbenches_btn_clicked ()
void on_shift_workbench_down_btn_clicked ()
void on_shift_workbench_up_btn_clicked ()
void on_sort_enabled_workbenches_btn_clicked ()
void onAddMacroAction (const QByteArray &)
void onModifyMacroAction (const QByteArray &)
void onRemoveMacroAction (const QByteArray &)
Protected Slots inherited from Gui::Dialog::CustomizeActionPage
virtual void onAddMacroAction (const QByteArray &)=0
virtual void onModifyMacroAction (const QByteArray &)=0
virtual void onRemoveMacroAction (const QByteArray &)=0
Protected Member Functions
void changeEvent (QEvent *e)
void hideEvent (QHideEvent *event)
Protected Member Functions inherited from Gui::Dialog::CustomizeActionPage
virtual void changeEvent (QEvent *e)=0
bool event (QEvent *e)
Constructor & Destructor Documentation
DlgWorkbenchesImp()
DlgWorkbenchesImp::DlgWorkbenchesImp (QWidget * parent = nullptr)
References Gui::Application::Instance, load_disabled_workbenches(), load_enabled_workbenches(), and Gui::Application::workbenches().
~DlgWorkbenchesImp()
DlgWorkbenchesImp::~DlgWorkbenchesImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void DlgWorkbenchesImp::changeEvent (QEvent * e) protected virtual
Implements Gui::Dialog::CustomizeActionPage.
hideEvent()
void DlgWorkbenchesImp::hideEvent (QHideEvent * event) protected
load_disabled_workbenches()
QStringList DlgWorkbenchesImp::load_disabled_workbenches () static
References App::GetApplication(), ParameterGrp::GetASCII(), and App::Application::GetParameterGroupByPath().
Referenced by DlgWorkbenchesImp().
load_enabled_workbenches()
QStringList DlgWorkbenchesImp::load_enabled_workbenches () static
References all_workbenches, App::GetApplication(), ParameterGrp::GetASCII(), App::Application::GetParameterGroupByPath(), Gui::Application::Instance, and Gui::Application::workbenches().
Referenced by DlgWorkbenchesImp().
on_add_all_to_enabled_workbenches_btn_clicked
void DlgWorkbenchesImp::on_add_all_to_enabled_workbenches_btn_clicked () protected slot
on_add_to_enabled_workbenches_btn_clicked
void DlgWorkbenchesImp::on_add_to_enabled_workbenches_btn_clicked () protected slot
on_remove_from_enabled_workbenches_btn_clicked
void DlgWorkbenchesImp::on_remove_from_enabled_workbenches_btn_clicked () protected slot
on_shift_workbench_down_btn_clicked
void DlgWorkbenchesImp::on_shift_workbench_down_btn_clicked () protected slot
on_shift_workbench_up_btn_clicked
void DlgWorkbenchesImp::on_shift_workbench_up_btn_clicked () protected slot
on_sort_enabled_workbenches_btn_clicked
void DlgWorkbenchesImp::on_sort_enabled_workbenches_btn_clicked () protected slot
onAddMacroAction
void DlgWorkbenchesImp::onAddMacroAction (const QByteArray & macro) protected slot
onModifyMacroAction
void DlgWorkbenchesImp::onModifyMacroAction (const QByteArray & macro) protected slot
onRemoveMacroAction
void DlgWorkbenchesImp::onRemoveMacroAction (const QByteArray & macro) protected slot
Member Data Documentation
all_workbenches
const QString DlgWorkbenchesImp::all_workbenches = QString::fromLatin1("ALL") static
Referenced by load_enabled_workbenches().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgWorkbenchesImp.h
FreeCAD/src/Gui/DlgWorkbenchesImp.cpp