FreeCAD: Mod.Show.Containers Namespace Reference
Mod.Show.Containers Namespace Reference
Classes
class Container
class ContainerError
class ContainerTreeError
class NotAContainerError
Functions
def ContainerChain (feat)
def ContainerOf (obj)
def CSChain (feat)
def getVisGroupOf (obj)
def isAContainer (obj, links_too=False)
def VisGroupChain (feat)
Function Documentation
ContainerChain()
def Mod.Show.Containers.ContainerChain (feat)
ContainerChain(feat): container path to feat (not including feat itself).
Last container directly contains the feature.
Example of output:  [<document>,<SuperPart>,<Part>,<Body>]
References Mod.Show.Containers.isAContainer().
Referenced by Mod.Show.Containers.CSChain(), Mod.Show.Containers.Container.hasObjectRecursive(), and Mod.Show.Containers.VisGroupChain().
ContainerOf()
def Mod.Show.Containers.ContainerOf (obj)
ContainerOf(obj): returns the container that immediately has obj.
References Mod.Show.Containers.isAContainer().
CSChain()
def Mod.Show.Containers.CSChain (feat)
References Mod.Show.Containers.ContainerChain().
getVisGroupOf()
def Mod.Show.Containers.getVisGroupOf (obj)
References Mod.Show.Containers.VisGroupChain().
isAContainer()
def Mod.Show.Containers.isAContainer (obj, links_too = False)
isAContainer(obj, links_too): returns True if obj is an object container, such as
Group, Part, Body. The important characteristic of an object being a
container is that it can be activated to receive new objects. Documents
are considered containers, too.
If links_too, App::Link objects are considered containers, too. Then, container tree
isn't necessarily a tree.
Referenced by Mod.Show.Containers.ContainerChain(), Mod.Show.Containers.ContainerOf(), Mod.Show.Containers.Container.getDynamicChildren(), Mod.Show.Containers.Container.hasObjectRecursive(), and Mod.Show.Containers.Container.self_check().
VisGroupChain()
def Mod.Show.Containers.VisGroupChain (feat)
References Mod.Show.Containers.ContainerChain().
Referenced by Mod.Show.Containers.getVisGroupOf().