FreeCAD: QSint::ActionPanel Class Reference
QSint::ActionPanel Class Reference
Class representing panels of actions similar to Windows XP task panels.
#include <actionpanel.h>
Public Member Functions
ActionPanel (QWidget *parent=nullptr)
Constructor.
void addStretch (int s=0)
Adds a spacer with width s to the ActionPanel's vertical layout.
void addWidget (QWidget *w)
Adds a widget w to the ActionPanel's vertical layout.
ActionGroup * createGroup ()
Creates and adds to the ActionPanel's vertical layout an empty ActionGroup without header.
ActionGroup * createGroup (const QPixmap &icon, const QString &title, bool expandable=true)
Creates and adds to the ActionPanel's vertical layout an empty ActionGroup with header's text set to title and icon set to icon.
ActionGroup * createGroup (const QString &title, bool expandable=true)
Creates and adds to the ActionPanel's vertical layout an empty ActionGroup with header's text set to title, but with no icon.
virtual QSize minimumSizeHint () const
void removeStretch ()
Removes the spacer – if added – from the ActionPanel's vertical layout.
void removeWidget (QWidget *w)
Removes the widget w from the ActionPanel's vertical layout.
void setScheme (ActionPanelScheme *scheme)
Sets the scheme of the panel and all the child groups to scheme.
Protected Attributes
ActionPanelScheme * myScheme
QSpacerItem * mySpacer
Detailed Description
Class representing panels of actions similar to Windows XP task panels.
Since
0.2
An example of ActionPanel
ActionPanel acts like a container for ActionGroup which in turn are containers for the actions represented by ActionLabel.
The look and fill is complete styleable via setScheme(). Currently the following schemes available: ActionPanelScheme (the default), WinXPPanelScheme and WinXPPanelScheme2 (blue Windows XP schemes), WinVistaPanelScheme (Windows Vista variation), MacPanelScheme (MacOS variation), AndroidPanelScheme (Android variation).
Constructor & Destructor Documentation
ActionPanel()
QSint::ActionPanel::ActionPanel (QWidget * parent = nullptr) explicit
Constructor.
References QSint::ActionPanelScheme::defaultScheme(), and setScheme().
Member Function Documentation
addStretch()
void QSint::ActionPanel::addStretch (int s = 0)
Adds a spacer with width s to the ActionPanel's vertical layout.
Normally you should do this after all the ActionGroups were added, in order to maintain some space below.
References mySpacer.
Referenced by Gui::TaskView::TaskView::addTaskWatcher(), and Gui::TaskView::TaskView::showDialog().
addWidget()
void QSint::ActionPanel::addWidget (QWidget * w)
Adds a widget w to the ActionPanel's vertical layout.
Referenced by Gui::TaskView::TaskView::addTaskWatcher(), createGroup(), and Gui::TaskView::TaskView::showDialog().
createGroup() [1/3]
ActionGroup * QSint::ActionPanel::createGroup ()
Creates and adds to the ActionPanel's vertical layout an empty ActionGroup without header.
References addWidget().
Referenced by ArchBuildingPart.ViewProviderBuildingPart::setupContextMenu().
createGroup() [2/3]
ActionGroup * QSint::ActionPanel::createGroup (const QPixmap & icon, const QString & title, bool expandable = true)
Creates and adds to the ActionPanel's vertical layout an empty ActionGroup with header's text set to title and icon set to icon.
If expandable set to true (default), the group can be expanded/collapsed by the user.
References addWidget().
Referenced by ArchBuildingPart.ViewProviderBuildingPart::setupContextMenu().
createGroup() [3/3]
ActionGroup * QSint::ActionPanel::createGroup (const QString & title, bool expandable = true)
Creates and adds to the ActionPanel's vertical layout an empty ActionGroup with header's text set to title, but with no icon.
If expandable set to true (default), the group can be expanded/collapsed by the user.
References addWidget().
Referenced by ArchBuildingPart.ViewProviderBuildingPart::setupContextMenu().
minimumSizeHint()
QSize QSint::ActionPanel::minimumSizeHint () const virtual
Reimplemented in Gui::TaskView::TaskPanel.
removeStretch()
void QSint::ActionPanel::removeStretch ()
Removes the spacer – if added – from the ActionPanel's vertical layout.
References mySpacer.
Referenced by Gui::TaskView::TaskView::removeDialog(), and Gui::TaskView::TaskView::removeTaskWatcher().
removeWidget()
void QSint::ActionPanel::removeWidget (QWidget * w)
Removes the widget w from the ActionPanel's vertical layout.
Referenced by Gui::TaskView::TaskView::removeDialog(), and Gui::TaskView::TaskView::removeTaskWatcher().
setScheme()
void QSint::ActionPanel::setScheme (ActionPanelScheme * scheme)
Sets the scheme of the panel and all the child groups to scheme.
By default, ActionPanelScheme::defaultScheme() is used.
References QSint::ActionPanelScheme::actionStyle, and myScheme.
Referenced by ActionPanel(), Gui::TaskView::TaskView::addTaskWatcher(), Gui::TaskView::TaskView::clearActionStyle(), Gui::TaskView::TaskView::restoreActionStyle(), Gui::TaskView::TaskView::showDialog(), and Gui::TaskView::TaskView::TaskView().
Member Data Documentation
myScheme
ActionPanelScheme* QSint::ActionPanel::myScheme protected
Referenced by setScheme().
mySpacer
QSpacerItem* QSint::ActionPanel::mySpacer protected
Referenced by addStretch(), and removeStretch().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/QSint/actionpanel/actionpanel.h
FreeCAD/src/Gui/QSint/actionpanel/actionpanel.cpp