FreeCAD: draftobjects.base.DraftObject Class Reference
draftobjects.base.DraftObject Class Reference
Workbenches » Python workbenches » Draft » draftobjects
Public Member Functions
def execute (self, obj)
def onChanged (self, obj, prop)
Public Attributes
Type
Detailed Description
The base class for Draft objects.
Parameters
----------
obj : a base C++ object
    The base object instantiated during creation,
    which commonly may be of types `Part::Part2DObjectPython`,
    `Part::FeaturePython`, or `App::FeaturePython`.
        >>> obj = App.ActiveDocument.addObject('Part::Part2DObjectPython')
        >>> DraftObject(obj)
    This class instance is stored in the `Proxy` attribute
    of the base object.
    ::
        obj.Proxy = self
tp : str, optional
    It defaults to `'Unknown'`.
    It indicates the type of this scripted object,
    which will be assigned to the Proxy's `Type` attribute.
    This is useful to distinguish different types of scripted objects
    that may be derived from the same C++ class.
Attributes
----------
Type : str
    It indicates the type of scripted object.
    Normally `Type = tp`.
    All objects have a `TypeId` attribute, but this attribute
    refers to the C++ class only. Using the `Type` attribute
    allows distinguishing among various types of objects
    derived from the same C++ class.
        >>> print(A.TypeId, "->", A.Proxy.Type)
        Part::Part2DObjectPython -> Wire
        >>> print(B.TypeId, "->", B.Proxy.Type)
        Part::Part2DObjectPython -> Circle
This class attribute is accessible through the `Proxy` object:
`obj.Proxy.Type`.
Member Function Documentation
execute()
def draftobjects.base.DraftObject.execute (self, obj)
Run this method when the object is created or recomputed.
Override this method to produce effects when the object
is newly created, and whenever the document is recomputed.
By default it does nothing.
Parameters
----------
obj : the scripted object.
    This commonly may be of types `Part::Part2DObjectPython`,
    `Part::FeaturePython`, or `App::FeaturePython`.
Reimplemented in draftobjects.wire.Wire, draftobjects.shapestring.ShapeString, draftobjects.shape2dview.Shape2DView, draftobjects.rectangle.Rectangle, draftobjects.polygon.Polygon, draftobjects.pointarray.PointArray, draftobjects.point.Point, draftobjects.pathtwistedarray.PathTwistedArray, draftobjects.patharray.PathArray, draftobjects.fillet.Fillet, draftobjects.facebinder.Facebinder, draftobjects.ellipse.Ellipse, draftobjects.drawingview.DrawingView, draftobjects.clone.Clone, draftobjects.circle.Circle, draftobjects.bspline.BSpline, draftobjects.block.Block, draftobjects.array.Array, and draftobjects.bezcurve.BezCurve.
Referenced by draftobjects.facebinder.Facebinder.addSubobjects(), PathScripts.PathDressupDogbone.ObjectDressup.boneStateList(), ArchSite.Compass.buildCoordinates(), PathScripts.PathDressupHoldingTags.ObjectTagDressup.generateTags(), ArchSchedule.CommandArchSchedule.IsActive(), Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), FeaturePython.DistanceBolt.onChanged(), PathScripts.PathStock.StockFromBase.onChanged(), PathScripts.PathStock.StockCreateBox.onChanged(), PathScripts.PathStock.StockCreateCylinder.onChanged(), draftobjects.draftlink.DraftLink.onDocumentRestored(), draftobjects.patharray.PathArray.onDocumentRestored(), and draftobjects.pathtwistedarray.PathTwistedArray.onDocumentRestored().
onChanged()
def draftobjects.base.DraftObject.onChanged (self, obj, prop)
Run this method when a property is changed.
Override this method to handle the behavior
of the object depending on changes that occur to its properties.
By default it does nothing.
Parameters
----------
obj : the scripted object.
    This commonly may be of types `Part::Part2DObjectPython`,
    `Part::FeaturePython`, or `App::FeaturePython`.
prop : str
    Name of the property that was modified.
Reimplemented in draftobjects.wire.Wire, draftobjects.pathtwistedarray.PathTwistedArray, draftobjects.patharray.PathArray, draftobjects.fillet.Fillet, draftobjects.draftlink.DraftLink, draftobjects.array.Array, draftobjects.bspline.BSpline, and draftobjects.bezcurve.BezCurve.
Referenced by draftviewproviders.view_base.ViewProviderDraft.attach(), ArchSite.Compass.buildCoordinates(), draftobjects.wire.Wire.execute(), ArchAxis.CommandArchGrid.IsActive(), draftviewproviders.view_label.ViewProviderLabel.updateData(), draftviewproviders.view_layer.ViewProviderLayer.updateData(), and draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy.updateData().
Member Data Documentation
Type
draftobjects.base.DraftObject.Type
Referenced by ArchPanel.CommandPanelSheet.Activated(), draftobjects.draft_annotation.DraftAnnotation.add_missing_properties_0v19(), ArchStructure.StructSelectionObserver.addSelection(), ArchSite.Compass.buildCoordinates(), draftobjects.layer.LayerContainer.execute(), ArchAxis.CommandArchGrid.IsActive(), ArchSchedule.CommandArchSchedule.IsActive(), and draftobjects.layer.Layer.set_properties().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Draft/draftobjects/base.py