FreeCAD: PathFeedRate Namespace Reference
PathFeedRate Namespace Reference
Functions
def setFeedRate (commandlist, ToolController)
Function Documentation
setFeedRate()
def PathFeedRate.setFeedRate (commandlist, ToolController)
Set the appropriate feed rate for a list of Path commands using the information from a Tool Controller
Every motion command in the list will have a feed rate parameter added or overwritten based
on the information stored in the tool controller. If a motion is a plunge (vertical) motion, the
VertFeed value will be used, otherwise the HorizFeed value will be used instead.
Referenced by PathScripts.PathDrilling.ObjectDrilling.circularHoleExecute(), PathScripts.PathHelix.ObjectHelix.circularHoleExecute(), and PathTests.TestPathHelpers.TestPathHelpers.test00().