FreeCAD: TechDrawGui::TaskCenterLine Class Reference
TechDrawGui::TaskCenterLine Class Reference
#include <TaskCenterLine.h>
Public Member Functions
virtual bool accept ()
void enableTaskButtons (bool b)
virtual bool getCreateMode (void)
virtual bool reject ()
void saveButtons (QPushButton *btnOK, QPushButton *btnCancel)
virtual void setCreateMode (bool b)
void setFlipped (bool b)
TaskCenterLine (TechDraw::DrawViewPart *baseFeat, TechDraw::DrawPage *page, std::string edgeName, bool editMode)
TaskCenterLine (TechDraw::DrawViewPart *baseFeat, TechDraw::DrawPage *page, std::vector< std::string > subNames, bool editMode)
void updateTask ()
~TaskCenterLine ()
Protected Member Functions
void blockButtons (bool b)
void changeEvent (QEvent *e)
void create2Lines (void)
void create2Points (void)
void createCenterLine (void)
QColor getCenterColor ()
Qt::PenStyle getCenterStyle ()
double getCenterWidth ()
double getExtendBy ()
void setUiEdit (void)
void setUiPrimary (void)
void update2Lines (void)
void update2Points (void)
void updateCenterLine (void)
Constructor & Destructor Documentation
TaskCenterLine() [1/2]
TaskCenterLine::TaskCenterLine (TechDraw::DrawViewPart * baseFeat, TechDraw::DrawPage * page, std::vector< std::string > subNames, bool editMode)
References Base::Console(), Base::ConsoleSingleton::Error(), draftgeoutils.general::geomType(), TechDraw::DrawUtil::getGeomTypeFromName(), and setUiPrimary().
TaskCenterLine() [2/2]
TaskCenterLine::TaskCenterLine (TechDraw::DrawViewPart * baseFeat, TechDraw::DrawPage * page, std::string edgeName, bool editMode)
References Base::Console(), TechDraw::CosmeticExtension::getCenterLine(), TechDraw::BaseGeom::getCosmeticTag(), TechDraw::DrawViewPart::getEdgeGeometry(), TechDraw::CenterLine::m_mode, TechDraw::CenterLine::m_type, Base::ConsoleSingleton::Message(), and setUiEdit().
~TaskCenterLine()
TaskCenterLine::~TaskCenterLine ()
Member Function Documentation
accept()
bool TaskCenterLine::accept (void) virtual
References createCenterLine(), getCreateMode(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::Command::Gui, Gui::Application::Instance, and updateCenterLine().
Referenced by TechDrawGui::TaskDlgCenterLine::accept().
blockButtons()
void TechDrawGui::TaskCenterLine::blockButtons (bool b) protected
changeEvent()
void TaskCenterLine::changeEvent (QEvent * e) protected
create2Lines()
void TechDrawGui::TaskCenterLine::create2Lines (void) protected
create2Points()
void TechDrawGui::TaskCenterLine::create2Points (void) protected
createCenterLine()
void TaskCenterLine::createCenterLine (void) protected
References TechDraw::CosmeticExtension::addCenterLine(), Gui::Command::commitCommand(), Base::Console(), Base::ConsoleSingleton::Log(), TechDraw::LineFormat::m_color, TechDraw::CenterLine::m_flip2Line, TechDraw::CenterLine::m_format, TechDraw::LineFormat::m_style, TechDraw::LineFormat::m_visible, TechDraw::LineFormat::m_weight, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, App::DocumentObject::recomputeFeature(), TechDraw::CenterLine::setExtend(), TechDraw::CenterLine::setRotate(), TechDraw::CenterLine::setShifts(), App::Color::setValue(), and Gui::Command::updateActive().
Referenced by accept().
enableTaskButtons()
void TaskCenterLine::enableTaskButtons (bool b)
getCenterColor()
QColor TaskCenterLine::getCenterColor () protected
References TechDrawGui::PreferencesGui::centerQColor().
Referenced by setUiPrimary().
getCenterStyle()
Qt::PenStyle TaskCenterLine::getCenterStyle () protected
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), and App::Application::GetUserParameter().
Referenced by setUiPrimary().
getCenterWidth()
double TaskCenterLine::getCenterWidth () protected
References App::PropertyQuantity::getValue(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::ViewProviderViewPart::IsoWidth, and TechDraw::LineGroup::lineGroupFactory().
Referenced by setUiPrimary().
getCreateMode()
virtual bool TechDrawGui::TaskCenterLine::getCreateMode (void) virtual
Referenced by accept(), and reject().
getExtendBy()
double TaskCenterLine::getExtendBy (void) protected
References App::GetApplication(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by setUiPrimary().
reject()
bool TaskCenterLine::reject (void) virtual
References getCreateMode(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), Gui::Command::Gui, and Gui::Application::Instance.
Referenced by TechDrawGui::TaskDlgCenterLine::reject().
saveButtons()
void TaskCenterLine::saveButtons (QPushButton * btnOK, QPushButton * btnCancel)
Referenced by TechDrawGui::TaskDlgCenterLine::modifyStandardButtons().
setCreateMode()
virtual void TechDrawGui::TaskCenterLine::setCreateMode (bool b) virtual
setFlipped()
void TechDrawGui::TaskCenterLine::setFlipped (bool b)
setUiEdit()
void TaskCenterLine::setUiEdit (void) protected
References Base::Unit::Angle, App::Color::asValue(), draftgeoutils.intersections::connect(), Base::Tools::fromStdString(), Base::UnitsApi::getDecimals(), App::DocumentObject::getNameInDocument(), Base::Unit::Length, TechDraw::LineFormat::m_color, TechDraw::CenterLine::m_extendBy, TechDraw::CenterLine::m_flip2Line, TechDraw::CenterLine::m_format, TechDraw::CenterLine::m_hShift, TechDraw::CenterLine::m_mode, TechDraw::CenterLine::m_rotate, TechDraw::LineFormat::m_style, TechDraw::CenterLine::m_type, TechDraw::CenterLine::m_vShift, TechDraw::LineFormat::m_weight, Base::Quantity::setUnit(), and Base::Quantity::setValue().
Referenced by TaskCenterLine().
setUiPrimary()
void TaskCenterLine::setUiPrimary (void) protected
References Base::Unit::Angle, Base::Tools::fromStdString(), getCenterColor(), getCenterStyle(), getCenterWidth(), Base::UnitsApi::getDecimals(), getExtendBy(), App::DocumentObject::getNameInDocument(), Base::Unit::Length, Base::Quantity::setUnit(), and Base::Quantity::setValue().
Referenced by TaskCenterLine().
update2Lines()
void TechDrawGui::TaskCenterLine::update2Lines (void) protected
update2Points()
void TechDrawGui::TaskCenterLine::update2Points (void) protected
updateCenterLine()
void TaskCenterLine::updateCenterLine (void) protected
References Gui::Command::commitCommand(), TechDraw::LineFormat::m_color, TechDraw::CenterLine::m_extendBy, TechDraw::CenterLine::m_flip2Line, TechDraw::CenterLine::m_format, TechDraw::CenterLine::m_hShift, TechDraw::CenterLine::m_mode, TechDraw::CenterLine::m_rotate, TechDraw::LineFormat::m_style, TechDraw::CenterLine::m_type, TechDraw::LineFormat::m_visible, TechDraw::CenterLine::m_vShift, TechDraw::LineFormat::m_weight, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, TechDraw::DrawViewPart::refreshCLGeoms(), TechDraw::DrawView::requestPaint(), App::Color::setValue(), and Gui::Command::updateActive().
Referenced by accept().
updateTask()
void TaskCenterLine::updateTask ()
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/TaskCenterLine.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/TaskCenterLine.cpp