FreeCAD: MeshCore::MeshEigensystem Class Reference
MeshCore::MeshEigensystem Class Reference
The MeshEigensystem class actually does not try to check for or fix errors but it provides methods to calculate the mesh's local coordinate system with the center of gravity as origin.
#include <Evaluation.h>
Public Member Functions
bool Evaluate ()
Evaluates the mesh kernel with respect to certain criteria.
Base::Vector3f GetBoundings () const
Returns the expansions in u, v and w of the bounding box.
MeshEigensystem (const MeshKernel &rclB)
Base::Matrix4D Transform () const
Returns the transformation matrix.
virtual ~MeshEigensystem ()
Public Member Functions inherited from MeshCore::MeshEvaluation
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()
Protected Member Functions
void CalculateLocalSystem ()
Calculates the local coordinate system defined by u, v, w and c.
Detailed Description
The MeshEigensystem class actually does not try to check for or fix errors but it provides methods to calculate the mesh's local coordinate system with the center of gravity as origin.
The local coordinate system is computed this way that u has minimum and w has maximum expansion. The local coordinate system is right-handed.
Author
Werner Mayer
Constructor & Destructor Documentation
MeshEigensystem()
MeshEigensystem::MeshEigensystem (const MeshKernel & rclB)
References Base::BoundBox3< _Precision >::LengthX().
~MeshEigensystem()
virtual MeshCore::MeshEigensystem::~MeshEigensystem () virtual
Member Function Documentation
CalculateLocalSystem()
void MeshEigensystem::CalculateLocalSystem () protected
Calculates the local coordinate system defined by u, v, w and c.
References MeshCore::Approximation::AddPoint(), MeshCore::PlaneFit::Fit(), MeshCore::PlaneFit::GetBase(), MeshCore::PlaneFit::GetDirU(), MeshCore::PlaneFit::GetDirV(), and MeshCore::PlaneFit::GetNormal().
Referenced by Evaluate().
Evaluate()
bool MeshEigensystem::Evaluate () virtual
Evaluates the mesh kernel with respect to certain criteria.
Must be reimplemented by every subclass. This pure virtual function returns false if the mesh kernel is invalid according to this criterion and true if the mesh kernel is correct.
Implements MeshCore::MeshEvaluation.
References CalculateLocalSystem(), Base::Vector3< _Precision >::Length(), and Base::Vector3< _Precision >::ProjectToLine().
Referenced by Mesh::MeshObject::getEigenSystem(), and Mesh::MeshObject::transformToEigenSystem().
GetBoundings()
Base::Vector3f MeshEigensystem::GetBoundings () const
Returns the expansions in u, v and w of the bounding box.
Referenced by Mesh::MeshObject::getEigenSystem().
Transform()
Base::Matrix4D MeshEigensystem::Transform () const
Returns the transformation matrix.
Referenced by Mesh::MeshObject::getEigenSystem(), and Mesh::MeshObject::transformToEigenSystem().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Evaluation.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Evaluation.cpp