FreeCAD: Gui::PropertyEditor::VectorListWidget Class Reference
Gui::PropertyEditor::VectorListWidget Class Reference
#include <PropertyItem.h>
Public Slots
void setValue (const QVariant &)
Signals
void valueChanged (const QVariant &)
Public Member Functions
QVariant value () const
VectorListWidget (int decimals, QWidget *parent=nullptr)
virtual ~VectorListWidget ()
Protected Member Functions
void resizeEvent (QResizeEvent *)
void showValue (const QVariant &data)
Constructor & Destructor Documentation
VectorListWidget()
VectorListWidget::VectorListWidget (int decimals, QWidget * parent = nullptr)
References draftgeoutils.intersections::connect().
~VectorListWidget()
VectorListWidget::~VectorListWidget () virtual
Member Function Documentation
resizeEvent()
void VectorListWidget::resizeEvent (QResizeEvent * e) protected
setValue
void VectorListWidget::setValue (const QVariant & val) slot
References showValue(), and valueChanged().
showValue()
void VectorListWidget::showValue (const QVariant & data) protected
Referenced by setValue().
value()
QVariant VectorListWidget::value () const
Referenced by PathScripts.PathProperty.Property::displayString(), PathScripts.PathProperty.PropertyQuantity::displayString(), PathScripts.PathSetupSheetOpPrototype.Property::displayString(), PathScripts.PathSetupSheetOpPrototype.PropertyQuantity::displayString(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), PathScripts.PathProperty.Property::getValue(), PathScripts.PathSetupSheetOpPrototype.Property::getValue(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), PathScripts.PathProperty.Property::setValue(), and PathScripts.PathSetupSheetOpPrototype.Property::setValue().
valueChanged
void Gui::PropertyEditor::VectorListWidget::valueChanged (const QVariant &) signal
Referenced by setValue().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/propertyeditor/PropertyItem.h
Sources/FreeCAD/src/Gui/propertyeditor/PropertyItem.cpp