FreeCAD: Path::Voronoi::diagram_type Class Reference
Path::Voronoi::diagram_type Class Reference
#include <Voronoi.h>
Public Types
typedef std::map< int, double > angle_map_t
typedef std::map< intptr_t, int > cell_map_type
typedef std::map< intptr_t, int > edge_map_type
typedef std::map< intptr_t, int > vertex_map_type
Public Member Functions
double angleOfSegment (int i, angle_map_t *angle=nullptr) const
diagram_type ()
double getScale () const
int index (const cell_type *cell) const
int index (const edge_type *edge) const
int index (const vertex_type *vertex) const
void reIndex ()
point_type retrievePoint (const cell_type *cell) const
segment_type retrieveSegment (const cell_type *cell) const
Base::Vector3d scaledVector (const point_type &p, double z) const
Base::Vector3d scaledVector (const vertex_type &v, double z) const
Base::Vector3d scaledVector (double x, double y, double z) const
bool segmentsAreConnected (int i, int j) const
void setScale (double s)
Public Member Functions inherited from Base::Handled
int getRefCount () const
Handled ()
const Handled & operator= (const Handled &)
void ref () const
void unref () const
virtual ~Handled ()
Public Attributes
std::vector< point_type > points
std::vector< segment_type > segments
Member Typedef Documentation
angle_map_t
typedef std::map<int, double> Path::Voronoi::diagram_type::angle_map_t
cell_map_type
typedef std::map<intptr_t, int> Path::Voronoi::diagram_type::cell_map_type
edge_map_type
typedef std::map<intptr_t, int> Path::Voronoi::diagram_type::edge_map_type
vertex_map_type
typedef std::map<intptr_t, int> Path::Voronoi::diagram_type::vertex_map_type
Constructor & Destructor Documentation
diagram_type()
Voronoi::diagram_type::diagram_type ()
Member Function Documentation
angleOfSegment()
double Voronoi::diagram_type::angleOfSegment (int i, angle_map_t * angle = nullptr) const
getScale()
double Voronoi::diagram_type::getScale () const
index() [1/3]
int Path::Voronoi::diagram_type::index (const cell_type * cell) const
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::addSegment(), Dice3DS.dom3ds.FileLikeBuffer::advance(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::begin(), Spreadsheet_legacy.MathParser::getValue(), Spreadsheet_legacy.MathParser::hasNext(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::interval(), PathScripts.PathJobDlg.JobCreate::item1ValueChanged(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::length(), Spreadsheet_legacy.MathParser::parseAddition(), Spreadsheet_legacy.MathParser::parseMultiplication(), Spreadsheet_legacy.MathParser::parseNegative(), Spreadsheet_legacy.MathParser::parseNumber(), Spreadsheet_legacy.MathParser::parseParenthesis(), Spreadsheet_legacy.MathParser::parseVariable(), Spreadsheet_legacy.MathParser::peek(), Dice3DS.dom3ds.FileLikeBuffer::read(), Dice3DS.dom3ds.FileLikeBuffer::read_fbuf(), Dice3DS.dom3ds.FileLikeBuffer::read_rest(), Dice3DS.dom3ds.FileLikeBuffer::read_to_nul(), Dice3DS.dom3ds.FileLikeBuffer::room_for_chunks(), Dice3DS.dom3ds.FileLikeBuffer::seek(), package_list.PackageListItemModel::setData(), PathScripts.PathJobDlg.JobCreate::setupColumnEditor(), Spreadsheet_legacy.MathParser::skipWhitespace(), Dice3DS.dom3ds.FileLikeBuffer::tell(), package_list.PackageListItemModel::update_item_icon(), package_list.PackageListItemModel::update_item_status(), automotive_design.index_expression::wr1(), and automotive_design.index_expression::wr2().
index() [2/3]
int Path::Voronoi::diagram_type::index (const edge_type * edge) const
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::addSegment(), Dice3DS.dom3ds.FileLikeBuffer::advance(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::begin(), Spreadsheet_legacy.MathParser::getValue(), Spreadsheet_legacy.MathParser::hasNext(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::interval(), PathScripts.PathJobDlg.JobCreate::item1ValueChanged(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::length(), Spreadsheet_legacy.MathParser::parseAddition(), Spreadsheet_legacy.MathParser::parseMultiplication(), Spreadsheet_legacy.MathParser::parseNegative(), Spreadsheet_legacy.MathParser::parseNumber(), Spreadsheet_legacy.MathParser::parseParenthesis(), Spreadsheet_legacy.MathParser::parseVariable(), Spreadsheet_legacy.MathParser::peek(), Dice3DS.dom3ds.FileLikeBuffer::read(), Dice3DS.dom3ds.FileLikeBuffer::read_fbuf(), Dice3DS.dom3ds.FileLikeBuffer::read_rest(), Dice3DS.dom3ds.FileLikeBuffer::read_to_nul(), Dice3DS.dom3ds.FileLikeBuffer::room_for_chunks(), Dice3DS.dom3ds.FileLikeBuffer::seek(), package_list.PackageListItemModel::setData(), PathScripts.PathJobDlg.JobCreate::setupColumnEditor(), Spreadsheet_legacy.MathParser::skipWhitespace(), Dice3DS.dom3ds.FileLikeBuffer::tell(), package_list.PackageListItemModel::update_item_icon(), package_list.PackageListItemModel::update_item_status(), automotive_design.index_expression::wr1(), and automotive_design.index_expression::wr2().
index() [3/3]
int Voronoi::diagram_type::index (const vertex_type * vertex) const
References Path::Voronoi::InvalidIndex.
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::addSegment(), Dice3DS.dom3ds.FileLikeBuffer::advance(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::begin(), Spreadsheet_legacy.MathParser::getValue(), Spreadsheet_legacy.MathParser::hasNext(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::interval(), PathScripts.PathJobDlg.JobCreate::item1ValueChanged(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::length(), Spreadsheet_legacy.MathParser::parseAddition(), Spreadsheet_legacy.MathParser::parseMultiplication(), Spreadsheet_legacy.MathParser::parseNegative(), Spreadsheet_legacy.MathParser::parseNumber(), Spreadsheet_legacy.MathParser::parseParenthesis(), Spreadsheet_legacy.MathParser::parseVariable(), Spreadsheet_legacy.MathParser::peek(), Dice3DS.dom3ds.FileLikeBuffer::read(), Dice3DS.dom3ds.FileLikeBuffer::read_fbuf(), Dice3DS.dom3ds.FileLikeBuffer::read_rest(), Dice3DS.dom3ds.FileLikeBuffer::read_to_nul(), Dice3DS.dom3ds.FileLikeBuffer::room_for_chunks(), Dice3DS.dom3ds.FileLikeBuffer::seek(), package_list.PackageListItemModel::setData(), PathScripts.PathJobDlg.JobCreate::setupColumnEditor(), Spreadsheet_legacy.MathParser::skipWhitespace(), Dice3DS.dom3ds.FileLikeBuffer::tell(), package_list.PackageListItemModel::update_item_icon(), package_list.PackageListItemModel::update_item_status(), automotive_design.index_expression::wr1(), and automotive_design.index_expression::wr2().
reIndex()
void Voronoi::diagram_type::reIndex ()
retrievePoint()
Voronoi::point_type Voronoi::diagram_type::retrievePoint (const cell_type * cell) const
retrieveSegment()
Voronoi::segment_type Voronoi::diagram_type::retrieveSegment (const cell_type * cell) const
scaledVector() [1/3]
Base::Vector3d Voronoi::diagram_type::scaledVector (const point_type & p, double z) const
scaledVector() [2/3]
Base::Vector3d Voronoi::diagram_type::scaledVector (const vertex_type & v, double z) const
scaledVector() [3/3]
Base::Vector3d Voronoi::diagram_type::scaledVector (double x, double y, double z) const
segmentsAreConnected()
bool Voronoi::diagram_type::segmentsAreConnected (int i, int j) const
setScale()
void Voronoi::diagram_type::setScale (double s)
Member Data Documentation
points
std::vector<point_type> Path::Voronoi::diagram_type::points
Referenced by ArchStructure.CommandStructuralSystem::Activated(), draftguitools.gui_arcs.Arc_3Points::drawArc(), draftguitools.gui_arcs.Arc_3Points::getPoint(), ArchCurtainWall.CommandArchCurtainWall::getPoint(), ArchTruss.CommandArchTruss::getPoint(), draftguitools.gui_trackers.bsplineTracker::recompute(), draftguitools.gui_trackers.bezcurveTracker::recompute(), draftguitools.gui_trackers.bsplineTracker::update(), draftguitools.gui_trackers.bezcurveTracker::update(), automotive_design.advanced_face::wr10(), and config_control_design.advanced_face::wr10().
segments
std::vector<segment_type> Path::Voronoi::diagram_type::segments
Referenced by Mod.PartDesign.WizardShaft.Shaft.Shaft::addSegment(), Mod.PartDesign.WizardShaft.ShaftFeature.ShaftFeature::addSegment(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::addSegment(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::buildFromDict(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::clone(), automotive_design.composite_curve::closed_curve(), config_control_design.composite_curve::closed_curve(), ifc2x3.ifccompositecurve::closedcurve(), ifc4.ifccompositecurve::closedcurve(), Mod.PartDesign.WizardShaft.Shaft.Shaft::editConstraint(), Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::findSegment(), Mod.PartDesign.WizardShaft.Shaft.Shaft::getConstraint(), Mod.PartDesign.WizardShaft.Shaft.Shaft::getLengthTo(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::index(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrate(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::isZero(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::lowervalue(), automotive_design.composite_curve::n_segments(), config_control_design.composite_curve::n_segments(), automotive_design.rectangular_composite_surface::n_u(), config_control_design.rectangular_composite_surface::n_u(), automotive_design.rectangular_composite_surface::n_v(), config_control_design.rectangular_composite_surface::n_v(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::negate(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::negated(), ifc2x3.ifccompositecurve::nsegments(), ifc4.ifccompositecurve::nsegments(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::output(), Mod.PartDesign.WizardShaft.Shaft.Shaft::showDiagram(), Mod.PartDesign.WizardShaft.Shaft.Shaft::updateConstraint(), Mod.PartDesign.WizardShaft.Shaft.Shaft::updateSegment(), and Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::value().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Path/App/Voronoi.h
FreeCAD/src/Mod/Path/App/Voronoi.cpp