FreeCAD: ReenGui::Ui_PoissonWidget Class Reference
ReenGui::Ui_PoissonWidget Class Reference
#include <ui_Poisson.h>
Public Member Functions
void retranslateUi (QWidget *ReenGui__PoissonWidget)
void setupUi (QWidget *ReenGui__PoissonWidget)
Public Attributes
QGridLayout * gridLayout
QGridLayout * gridLayout_2
QGroupBox * groupBox
QLabel * labelOctree
QLabel * labelSamples
QLabel * labelSolver
QSpinBox * octreeDepth
QDoubleSpinBox * samplesPerNode
QSpinBox * solverDivide
Member Function Documentation
retranslateUi()
void ReenGui::Ui_PoissonWidget::retranslateUi (QWidget * ReenGui__PoissonWidget)
References groupBox, labelOctree, labelSamples, labelSolver, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void ReenGui::Ui_PoissonWidget::setupUi (QWidget * ReenGui__PoissonWidget)
References gridLayout, gridLayout_2, groupBox, labelOctree, labelSamples, labelSolver, octreeDepth, retranslateUi(), samplesPerNode, and solverDivide.
Referenced by ReenGui::PoissonWidget::PoissonWidget().
Member Data Documentation
gridLayout
QGridLayout* ReenGui::Ui_PoissonWidget::gridLayout
Referenced by setupUi().
gridLayout_2
QGridLayout* ReenGui::Ui_PoissonWidget::gridLayout_2
Referenced by setupUi().
groupBox
QGroupBox* ReenGui::Ui_PoissonWidget::groupBox
Referenced by retranslateUi(), and setupUi().
labelOctree
QLabel* ReenGui::Ui_PoissonWidget::labelOctree
Referenced by retranslateUi(), and setupUi().
labelSamples
QLabel* ReenGui::Ui_PoissonWidget::labelSamples
Referenced by retranslateUi(), and setupUi().
labelSolver
QLabel* ReenGui::Ui_PoissonWidget::labelSolver
Referenced by retranslateUi(), and setupUi().
octreeDepth
QSpinBox* ReenGui::Ui_PoissonWidget::octreeDepth
Referenced by ReenGui::PoissonWidget::accept(), and setupUi().
samplesPerNode
QDoubleSpinBox* ReenGui::Ui_PoissonWidget::samplesPerNode
Referenced by ReenGui::PoissonWidget::accept(), and setupUi().
solverDivide
QSpinBox* ReenGui::Ui_PoissonWidget::solverDivide
Referenced by ReenGui::PoissonWidget::accept(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/ReverseEngineering/Gui/ui_Poisson.h