FreeCAD: TechDraw::CosmeticEdgePy Class Reference
TechDraw::CosmeticEdgePy Class Reference
The python export class for CosmeticEdge.
#include <CosmeticEdgePy.h>
Public Types
typedef CosmeticEdge * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
CosmeticEdgePy (CosmeticEdge *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of CosmeticEdgePy.
static PyMethodDef Methods []
Methods structure of CosmeticEdgePy.
static PyTypeObject Type
Type structure of CosmeticEdgePy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~CosmeticEdgePy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * clone (PyObject *args)
implementer for the clone() method
PyObject * copy (PyObject *args)
implementer for the copy() method
static PyObject * staticCallback_clone (PyObject *self, PyObject *args)
callback for the clone() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
callbacks and implementers for the python object attributes
Py::String getTag (void) const
getter for the Tag attribute
Py::Object getStart (void) const
getter for the Start attribute
void setStart (Py::Object arg)
setter for the Start attribute
Py::Object getEnd (void) const
getter for the End attribute
void setEnd (Py::Object arg)
setter for the End attribute
Py::Object getCenter (void) const
getter for the Center attribute
void setCenter (Py::Object arg)
setter for the Center attribute
Py::Object getRadius (void) const
getter for the Radius attribute
void setRadius (Py::Object arg)
setter for the Radius attribute
Py::Object getFormat (void) const
getter for the Format attribute
void setFormat (Py::Object arg)
setter for the Format attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
CosmeticEdge * getCosmeticEdgePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
static PyObject * staticCallback_getStart (PyObject *self, void *closure)
getter callback for the Start attribute
static int staticCallback_setStart (PyObject *self, PyObject *value, void *closure)
setter callback for the Start attribute
static PyObject * staticCallback_getEnd (PyObject *self, void *closure)
getter callback for the End attribute
static int staticCallback_setEnd (PyObject *self, PyObject *value, void *closure)
setter callback for the End attribute
static PyObject * staticCallback_getCenter (PyObject *self, void *closure)
getter callback for the Center attribute
static int staticCallback_setCenter (PyObject *self, PyObject *value, void *closure)
setter callback for the Center attribute
static PyObject * staticCallback_getRadius (PyObject *self, void *closure)
getter callback for the Radius attribute
static int staticCallback_setRadius (PyObject *self, PyObject *value, void *closure)
setter callback for the Radius attribute
static PyObject * staticCallback_getFormat (PyObject *self, void *closure)
getter callback for the Format attribute
static int staticCallback_setFormat (PyObject *self, PyObject *value, void *closure)
setter callback for the Format attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for CosmeticEdge.
Member Typedef Documentation
PointerType
typedef CosmeticEdge* TechDraw::CosmeticEdgePy::PointerType
Constructor & Destructor Documentation
~CosmeticEdgePy()
CosmeticEdgePy::~CosmeticEdgePy () protected
CosmeticEdgePy()
CosmeticEdgePy::CosmeticEdgePy (CosmeticEdge * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
clone()
PyObject * CosmeticEdgePy::clone (PyObject * args)
implementer for the clone() method
References TechDraw::CosmeticEdge::clone(), getCosmeticEdgePtr(), and GetType().
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchComponent.Component::execute(), ArchCurtainWall.CurtainWall::execute(), ArchTruss.Truss::execute(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated(), staticCallback_clone(), and PathTests.TestPathHelix.TestPathHelix::test04().
copy()
PyObject * CosmeticEdgePy::copy (PyObject * args)
implementer for the copy() method
References TechDraw::CosmeticEdge::copy(), getCosmeticEdgePtr(), and GetType().
Referenced by staticCallback_copy().
getCenter()
Py::Object CosmeticEdgePy::getCenter (void) const
getter for the Center attribute
References TechDraw::BaseGeom::geomType, getCosmeticEdgePtr(), TechDraw::DrawUtil::invertY(), TechDraw::CosmeticEdge::m_geometry, and TechDraw::CosmeticEdge::permaStart.
Referenced by staticCallback_getCenter().
getCosmeticEdgePtr()
CosmeticEdge * CosmeticEdgePy::getCosmeticEdgePtr (void) const
getter for the object handled by this class
Referenced by clone(), copy(), getCenter(), getEnd(), getFormat(), getRadius(), getStart(), getTag(), setCenter(), setEnd(), setFormat(), TechDraw::PropertyCosmeticEdgeList::setPyObject(), setRadius(), and setStart().
getCustomAttributes()
PyObject * CosmeticEdgePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getEnd()
Py::Object CosmeticEdgePy::getEnd (void) const
getter for the End attribute
References getCosmeticEdgePtr(), TechDraw::DrawUtil::invertY(), and TechDraw::CosmeticEdge::permaEnd.
Referenced by staticCallback_getEnd().
getFormat()
Py::Object CosmeticEdgePy::getFormat (void) const
getter for the Format attribute
References TechDraw::DrawUtil::colorToPyTuple(), getCosmeticEdgePtr(), TechDraw::LineFormat::m_color, TechDraw::CosmeticEdge::m_format, TechDraw::LineFormat::m_style, TechDraw::LineFormat::m_visible, and TechDraw::LineFormat::m_weight.
Referenced by staticCallback_getFormat().
getRadius()
Py::Object CosmeticEdgePy::getRadius (void) const
getter for the Radius attribute
References TechDraw::BaseGeom::geomType, getCosmeticEdgePtr(), TechDraw::CosmeticEdge::m_geometry, and TechDraw::CosmeticEdge::permaRadius.
Referenced by staticCallback_getRadius().
getStart()
Py::Object CosmeticEdgePy::getStart (void) const
getter for the Start attribute
References getCosmeticEdgePtr(), TechDraw::DrawUtil::invertY(), and TechDraw::CosmeticEdge::permaStart.
Referenced by staticCallback_getStart().
getTag()
Py::String CosmeticEdgePy::getTag (void) const
getter for the Tag attribute
References getCosmeticEdgePtr().
Referenced by staticCallback_getTag().
GetType()
virtual PyTypeObject* TechDraw::CosmeticEdgePy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
Referenced by clone(), and copy().
PyInit()
int CosmeticEdgePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
PyMake()
PyObject * CosmeticEdgePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string CosmeticEdgePy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCenter()
void CosmeticEdgePy::setCenter (Py::Object arg)
setter for the Center attribute
References TechDraw::BaseGeom::geomType, getCosmeticEdgePtr(), TechDraw::DrawUtil::invertY(), TechDraw::CosmeticEdge::m_geometry, TechDraw::CosmeticEdge::permaEnd, TechDraw::CosmeticEdge::permaRadius, TechDraw::CosmeticEdge::permaStart, TechDraw::Circle::radius, and Base::VectorPy::Type.
Referenced by draftguitools.gui_trackers.arcTracker::setBy3Points(), and staticCallback_setCenter().
setCustomAttributes()
int CosmeticEdgePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setEnd()
void CosmeticEdgePy::setEnd (Py::Object arg)
setter for the End attribute
References TechDraw::BaseGeom::baseFactory(), getCosmeticEdgePtr(), TechDraw::DrawUtil::invertY(), TechDraw::CosmeticEdge::m_geometry, TechDraw::CosmeticEdge::permaEnd, TechDraw::CosmeticEdge::permaStart, Base::VectorPy::Type, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by staticCallback_setEnd().
setFormat()
void CosmeticEdgePy::setFormat (Py::Object arg)
setter for the Format attribute
References Base::Console(), Base::ConsoleSingleton::Error(), getCosmeticEdgePtr(), TechDraw::LineFormat::m_color, TechDraw::CosmeticEdge::m_format, TechDraw::LineFormat::m_style, TechDraw::LineFormat::m_visible, TechDraw::LineFormat::m_weight, and TechDraw::DrawUtil::pyTupleToColor().
Referenced by PathScripts.PathInspect.GCodeHighlighter::highlightBlock(), PathScripts.PostUtils.GCodeHighlighter::highlightBlock(), and staticCallback_setFormat().
setRadius()
void CosmeticEdgePy::setRadius (Py::Object arg)
setter for the Radius attribute
References TechDraw::BaseGeom::geomType, getCosmeticEdgePtr(), TechDraw::CosmeticEdge::m_geometry, and TechDraw::CosmeticEdge::permaRadius.
Referenced by draftguitools.gui_trackers.arcTracker::setBy3Points(), and staticCallback_setRadius().
setStart()
void CosmeticEdgePy::setStart (Py::Object arg)
setter for the Start attribute
References TechDraw::BaseGeom::baseFactory(), getCosmeticEdgePtr(), TechDraw::DrawUtil::invertY(), TechDraw::CosmeticEdge::m_geometry, TechDraw::CosmeticEdge::permaEnd, TechDraw::CosmeticEdge::permaStart, Base::VectorPy::Type, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by staticCallback_setStart().
staticCallback_clone()
PyObject * CosmeticEdgePy::staticCallback_clone (PyObject * self, PyObject * args) static
callback for the clone() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, clone(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_copy()
PyObject * CosmeticEdgePy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copy(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCenter()
PyObject * CosmeticEdgePy::staticCallback_getCenter (PyObject * self, void * closure) static
getter callback for the Center attribute
References Base::BaseExceptionFreeCADError, getCenter(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getEnd()
PyObject * CosmeticEdgePy::staticCallback_getEnd (PyObject * self, void * closure) static
getter callback for the End attribute
References Base::BaseExceptionFreeCADError, getEnd(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFormat()
PyObject * CosmeticEdgePy::staticCallback_getFormat (PyObject * self, void * closure) static
getter callback for the Format attribute
References Base::BaseExceptionFreeCADError, getFormat(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRadius()
PyObject * CosmeticEdgePy::staticCallback_getRadius (PyObject * self, void * closure) static
getter callback for the Radius attribute
References Base::BaseExceptionFreeCADError, getRadius(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getStart()
PyObject * CosmeticEdgePy::staticCallback_getStart (PyObject * self, void * closure) static
getter callback for the Start attribute
References Base::BaseExceptionFreeCADError, getStart(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTag()
PyObject * CosmeticEdgePy::staticCallback_getTag (PyObject * self, void * closure) static
getter callback for the Tag attribute
References Base::BaseExceptionFreeCADError, getTag(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setCenter()
int CosmeticEdgePy::staticCallback_setCenter (PyObject * self, PyObject * value, void * closure) static
setter callback for the Center attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setCenter().
staticCallback_setEnd()
int CosmeticEdgePy::staticCallback_setEnd (PyObject * self, PyObject * value, void * closure) static
setter callback for the End attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setEnd().
staticCallback_setFormat()
int CosmeticEdgePy::staticCallback_setFormat (PyObject * self, PyObject * value, void * closure) static
setter callback for the Format attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setFormat().
staticCallback_setRadius()
int CosmeticEdgePy::staticCallback_setRadius (PyObject * self, PyObject * value, void * closure) static
setter callback for the Radius attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setRadius().
staticCallback_setStart()
int CosmeticEdgePy::staticCallback_setStart (PyObject * self, PyObject * value, void * closure) static
setter callback for the Start attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setStart().
staticCallback_setTag()
int CosmeticEdgePy::staticCallback_setTag (PyObject * self, PyObject * value, void * closure) static
setter callback for the Tag attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
Member Data Documentation
GetterSetter
PyGetSetDef CosmeticEdgePy::GetterSetter static
Attribute structure of CosmeticEdgePy.
Methods
PyMethodDef CosmeticEdgePy::Methods static
Initial value:
= {
    {"clone",
        reinterpret_cast<PyCFunction>( staticCallback_clone ),
        METH_VARARGS,
        "Create a clone of this CosmeticEdge"
    },
    {"copy",
        reinterpret_cast<PyCFunction>( staticCallback_copy ),
        METH_VARARGS,
        "Create a copy of this CosmeticEdge"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of CosmeticEdgePy.
Type
PyTypeObject CosmeticEdgePy::Type static
Type structure of CosmeticEdgePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/TechDraw/App/CosmeticEdgePy.h
Sources/FreeCAD/src/Mod/TechDraw/App/CosmeticEdgePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/TechDraw/App/CosmeticEdgePy.cpp