FreeCAD: Gui::Dialog::DlgParameterFind Class Reference
Gui::Dialog::DlgParameterFind Class Reference
#include <DlgParameterFind.h>
Public Member Functions
void accept ()
DlgParameterFind (DlgParameterImp *parent)
void reject ()
~DlgParameterFind ()
Destroys the object and frees any allocated resources.
Constructor & Destructor Documentation
DlgParameterFind()
DlgParameterFind::DlgParameterFind (DlgParameterImp * parent)
~DlgParameterFind()
DlgParameterFind::~DlgParameterFind ()
Destroys the object and frees any allocated resources.
Member Function Documentation
accept()
void DlgParameterFind::accept ()
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
reject()
void DlgParameterFind::reject ()
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgParameterFind.h
Sources/FreeCAD/src/Gui/DlgParameterFind.cpp