FreeCAD: Base::TypePy Class Reference
Base::TypePy Class Reference
The python export class for BaseType.
#include <TypePy.h>
Public Types
typedef BaseType * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
TypePy (BaseType *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of TypePy.
static PyMethodDef Methods []
Methods structure of TypePy.
static PyTypeObject Type
Type structure of TypePy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~TypePy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * getParent (PyObject *args)
implementer for the getParent() method
PyObject * isBad (PyObject *args)
implementer for the isBad() method
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerived (PyObject *args)
implementer for the getAllDerived() method
PyObject * createInstance (PyObject *args)
implementer for the createInstance() method
static PyObject * staticCallback_fromName (PyObject *self, PyObject *args)
callback for the fromName() method
static PyObject * fromName (PyObject *args)
implementer for the fromName() method
static PyObject * staticCallback_fromKey (PyObject *self, PyObject *args)
callback for the fromKey() method
static PyObject * fromKey (PyObject *args)
implementer for the fromKey() method
static PyObject * staticCallback_getNumTypes (PyObject *self, PyObject *args)
callback for the getNumTypes() method
static PyObject * getNumTypes (PyObject *args)
implementer for the getNumTypes() method
static PyObject * staticCallback_getBadType (PyObject *self, PyObject *args)
callback for the getBadType() method
static PyObject * getBadType (PyObject *args)
implementer for the getBadType() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
static PyObject * staticCallback_getParent (PyObject *self, PyObject *args)
callback for the getParent() method
static PyObject * staticCallback_isBad (PyObject *self, PyObject *args)
callback for the isBad() method
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerived (PyObject *self, PyObject *args)
callback for the getAllDerived() method
static PyObject * staticCallback_createInstance (PyObject *self, PyObject *args)
callback for the createInstance() method
static PyObject * staticCallback_createInstanceByName (PyObject *self, PyObject *args)
callback for the createInstanceByName() method
static PyObject * createInstanceByName (PyObject *args)
implementer for the createInstanceByName() method
callbacks and implementers for the python object attributes
Py::String getName (void) const
getter for the Name attribute
Py::Long getKey (void) const
getter for the Key attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseType * getBaseTypePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getName (PyObject *self, void *closure)
getter callback for the Name attribute
static int staticCallback_setName (PyObject *self, PyObject *value, void *closure)
setter callback for the Name attribute
static PyObject * staticCallback_getKey (PyObject *self, void *closure)
getter callback for the Key attribute
static int staticCallback_setKey (PyObject *self, PyObject *value, void *closure)
setter callback for the Key attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for BaseType.
Member Typedef Documentation
PointerType
typedef BaseType* Base::TypePy::PointerType
Constructor & Destructor Documentation
~TypePy()
TypePy::~TypePy () protected
TypePy()
TypePy::TypePy (BaseType * pcObject, PyTypeObject * T = &Type)
Referenced by fromKey(), fromName(), getAllDerived(), getAllDerivedFrom(), getBadType(), and getParent().
Member Function Documentation
createInstance()
PyObject * TypePy::createInstance (PyObject * args)
implementer for the createInstance() method
References Base::Type::createInstance(), and getBaseTypePtr().
Referenced by staticCallback_createInstance().
createInstanceByName()
PyObject * TypePy::createInstanceByName (PyObject * args) static
implementer for the createInstanceByName() method
References Base::Type::createInstanceByName().
Referenced by staticCallback_createInstanceByName().
fromKey()
PyObject * TypePy::fromKey (PyObject * args) static
implementer for the fromKey() method
References Base::Type::fromKey(), and TypePy().
Referenced by staticCallback_fromKey().
fromName()
PyObject * TypePy::fromName (PyObject * args) static
implementer for the fromName() method
References Base::Type::fromName(), and TypePy().
Referenced by staticCallback_fromName().
getAllDerived()
PyObject * TypePy::getAllDerived (PyObject * args)
implementer for the getAllDerived() method
References Base::Type::fromName(), Base::Type::getAllDerivedFrom(), getBaseTypePtr(), getName(), and TypePy().
Referenced by staticCallback_getAllDerived().
getAllDerivedFrom()
PyObject * TypePy::getAllDerivedFrom (PyObject * args) static
implementer for the getAllDerivedFrom() method
References Base::Type::fromName(), Base::Type::getAllDerivedFrom(), getBaseTypePtr(), Type, and TypePy().
Referenced by staticCallback_getAllDerivedFrom().
getBadType()
PyObject * TypePy::getBadType (PyObject * args) static
implementer for the getBadType() method
References Base::Type::badType(), and TypePy().
Referenced by staticCallback_getBadType().
getBaseTypePtr()
BaseType * TypePy::getBaseTypePtr (void) const
getter for the object handled by this class
Referenced by createInstance(), getAllDerived(), getAllDerivedFrom(), getKey(), getModule(), getName(), getParent(), isBad(), isDerivedFrom(), and representation().
getCustomAttributes()
PyObject * TypePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getKey()
Py::Long TypePy::getKey (void) const
getter for the Key attribute
References getBaseTypePtr().
Referenced by staticCallback_getKey().
getModule()
Py::String TypePy::getModule (void) const
getter for the Module attribute
References getBaseTypePtr(), and getName().
Referenced by staticCallback_getModule().
getName()
Py::String TypePy::getName (void) const
getter for the Name attribute
References getBaseTypePtr().
Referenced by getAllDerived(), getModule(), and staticCallback_getName().
getNumTypes()
PyObject * TypePy::getNumTypes (PyObject * args) static
implementer for the getNumTypes() method
References Base::Type::getNumTypes().
Referenced by staticCallback_getNumTypes().
getParent()
PyObject * TypePy::getParent (PyObject * args)
implementer for the getParent() method
References getBaseTypePtr(), Base::Type::getParent(), and TypePy().
Referenced by staticCallback_getParent().
GetType()
virtual PyTypeObject* Base::TypePy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
isBad()
PyObject * TypePy::isBad (PyObject * args)
implementer for the isBad() method
References getBaseTypePtr(), and Base::Type::isBad().
Referenced by staticCallback_isBad().
isDerivedFrom()
PyObject * TypePy::isDerivedFrom (PyObject * args)
implementer for the isDerivedFrom() method
References Base::Type::badType(), Base::Type::fromName(), getBaseTypePtr(), Base::Type::isDerivedFrom(), and Type.
Referenced by staticCallback_isDerivedFrom().
PyInit()
int TypePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
PyMake()
PyObject * TypePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string TypePy::representation (void) const
References getBaseTypePtr(), and Base::Type::getName().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int TypePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_createInstance()
PyObject * TypePy::staticCallback_createInstance (PyObject * self, PyObject * args) static
callback for the createInstance() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, createInstance(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_createInstanceByName()
PyObject * TypePy::staticCallback_createInstanceByName (PyObject * self, PyObject * args) static
callback for the createInstanceByName() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, and createInstanceByName().
staticCallback_fromKey()
PyObject * TypePy::staticCallback_fromKey (PyObject * self, PyObject * args) static
callback for the fromKey() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, and fromKey().
staticCallback_fromName()
PyObject * TypePy::staticCallback_fromName (PyObject * self, PyObject * args) static
callback for the fromName() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, and fromName().
staticCallback_getAllDerived()
PyObject * TypePy::staticCallback_getAllDerived (PyObject * self, PyObject * args) static
callback for the getAllDerived() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getAllDerived(), and Base::PyObjectBase::isValid().
staticCallback_getAllDerivedFrom()
PyObject * TypePy::staticCallback_getAllDerivedFrom (PyObject * self, PyObject * args) static
callback for the getAllDerivedFrom() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, and getAllDerivedFrom().
staticCallback_getBadType()
PyObject * TypePy::staticCallback_getBadType (PyObject * self, PyObject * args) static
callback for the getBadType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, and getBadType().
staticCallback_getKey()
PyObject * TypePy::staticCallback_getKey (PyObject * self, void * closure) static
getter callback for the Key attribute
References Base::BaseExceptionFreeCADError, getKey(), and Base::PyObjectBase::isValid().
staticCallback_getModule()
PyObject * TypePy::staticCallback_getModule (PyObject * self, void * closure) static
getter callback for the Module attribute
References Base::BaseExceptionFreeCADError, getModule(), and Base::PyObjectBase::isValid().
staticCallback_getName()
PyObject * TypePy::staticCallback_getName (PyObject * self, void * closure) static
getter callback for the Name attribute
References Base::BaseExceptionFreeCADError, getName(), and Base::PyObjectBase::isValid().
staticCallback_getNumTypes()
PyObject * TypePy::staticCallback_getNumTypes (PyObject * self, PyObject * args) static
callback for the getNumTypes() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, and getNumTypes().
staticCallback_getParent()
PyObject * TypePy::staticCallback_getParent (PyObject * self, PyObject * args) static
callback for the getParent() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getParent(), and Base::PyObjectBase::isValid().
staticCallback_isBad()
PyObject * TypePy::staticCallback_isBad (PyObject * self, PyObject * args) static
callback for the isBad() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isBad(), and Base::PyObjectBase::isValid().
staticCallback_isDerivedFrom()
PyObject * TypePy::staticCallback_isDerivedFrom (PyObject * self, PyObject * args) static
callback for the isDerivedFrom() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isDerivedFrom(), and Base::PyObjectBase::isValid().
staticCallback_setKey()
int TypePy::staticCallback_setKey (PyObject * self, PyObject * value, void * closure) static
setter callback for the Key attribute
References Base::PyObjectBase::isValid().
staticCallback_setModule()
int TypePy::staticCallback_setModule (PyObject * self, PyObject * value, void * closure) static
setter callback for the Module attribute
References Base::PyObjectBase::isValid().
staticCallback_setName()
int TypePy::staticCallback_setName (PyObject * self, PyObject * value, void * closure) static
setter callback for the Name attribute
References Base::PyObjectBase::isValid().
Member Data Documentation
GetterSetter
PyGetSetDef TypePy::GetterSetter static
Initial value:
= {
    {"Name",
        (getter) staticCallback_getName,
        (setter) staticCallback_setName,
        "The name of the type id",
        NULL
    },
    {"Key",
        (getter) staticCallback_getKey,
        (setter) staticCallback_setKey,
        "The key of the type id",
        NULL
    },
    {"Module",
        (getter) staticCallback_getModule,
        (setter) staticCallback_setModule,
        "Module in which this class is defined",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of TypePy.
Methods
PyMethodDef TypePy::Methods static
Methods structure of TypePy.
Type
PyTypeObject TypePy::Type static
Type structure of TypePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), getAllDerivedFrom(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), isDerivedFrom(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Base/TypePy.h
Sources/FreeCAD/src/Base/TypePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Base/TypePy.cpp