FreeCAD: Gui::PropertyEditor::PropertyItemDelegate Class Reference
Gui::PropertyEditor::PropertyItemDelegate Class Reference
#include <PropertyItemDelegate.h>
Public Slots
void valueChanged ()
Public Member Functions
virtual QWidget * createEditor (QWidget *, const QStyleOptionViewItem &, const QModelIndex &) const
virtual bool editorEvent (QEvent *event, QAbstractItemModel *model, const QStyleOptionViewItem &option, const QModelIndex &index)
virtual void paint (QPainter *painter, const QStyleOptionViewItem &opt, const QModelIndex &index) const
PropertyItemDelegate (QObject *parent)
virtual void setEditorData (QWidget *editor, const QModelIndex &index) const
virtual void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const
virtual QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const
~PropertyItemDelegate ()
Protected Member Functions
bool eventFilter (QObject *, QEvent *)
Constructor & Destructor Documentation
PropertyItemDelegate()
PropertyItemDelegate::PropertyItemDelegate (QObject * parent)
~PropertyItemDelegate()
PropertyItemDelegate::~PropertyItemDelegate ()
Member Function Documentation
createEditor()
QWidget * PropertyItemDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & , const QModelIndex & index) const virtual
References Gui::PropertyEditor::PropertyEditor::closeEditor(), Gui::PropertyEditor::PropertyItem::createEditor(), Gui::PropertyEditor::PropertyItem::createExpressionEditor(), Gui::PropertyEditor::PropertyItem::createPropertyEditorWidget(), Gui::PropertyEditor::PropertyItem::getPropertyData(), Gui::PropertyEditor::PropertyEditor::isBinding(), Gui::PropertyEditor::PropertyItem::isReadOnly(), Gui::PropertyEditor::PropertyItem::isSeparator(), App::Property::UserEdit, and valueChanged().
editorEvent()
bool PropertyItemDelegate::editorEvent (QEvent * event, QAbstractItemModel * model, const QStyleOptionViewItem & option, const QModelIndex & index) virtual
eventFilter()
bool PropertyItemDelegate::eventFilter (QObject * o, QEvent * ev) protected
paint()
void PropertyItemDelegate::paint (QPainter * painter, const QStyleOptionViewItem & opt, const QModelIndex & index) const virtual
setEditorData()
void PropertyItemDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const virtual
References Gui::PropertyEditor::PropertyItem::setEditorData(), Gui::PropertyEditor::PropertyItem::setExpressionEditorData(), Gui::PropertyEditor::PropertyEditorWidget::setValue(), and Gui::PropertyEditor::PropertyItemAttorney::toString().
setModelData()
void PropertyItemDelegate::setModelData (QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const virtual
References Gui::PropertyEditor::PropertyItem::editorData(), and Gui::PropertyEditor::PropertyItem::expressionEditorData().
sizeHint()
QSize PropertyItemDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
valueChanged
void PropertyItemDelegate::valueChanged () slot
Referenced by createEditor().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/propertyeditor/PropertyItemDelegate.h
FreeCAD/src/Gui/propertyeditor/PropertyItemDelegate.cpp