FreeCAD: Gui::PrefPageProducer< CLASS > Class Template Reference
Gui::PrefPageProducer< CLASS > Class Template Reference
The PrefPageProducer class is a value-based template class that provides the ability to create preference pages dynamically.
#include <WidgetFactory.h>
Public Member Functions
PrefPageProducer (const char *group)
Register a special type of preference page to the WidgetFactoryInst.
virtual void * Produce () const
Creates an instance of the specified widget.
virtual ~PrefPageProducer ()
Public Member Functions inherited from Base::AbstractProducer
AbstractProducer ()
virtual void * Produce () const =0
overwritten by a concrete producer to produce the needed object
virtual ~AbstractProducer ()
Detailed Description
template<class CLASS>
class Gui::PrefPageProducer< CLASS >
The PrefPageProducer class is a value-based template class that provides the ability to create preference pages dynamically.
Author
Werner Mayer
Constructor & Destructor Documentation
PrefPageProducer()
template<class CLASS > Gui::PrefPageProducer< CLASS >::PrefPageProducer (const char * group)
Register a special type of preference page to the WidgetFactoryInst.
References Gui::Dialog::DlgPreferencesImp::addPage(), Base::Factory::AddProducer(), and Gui::WidgetFactoryInst::instance().
~PrefPageProducer()
template<class CLASS > virtual Gui::PrefPageProducer< CLASS >::~PrefPageProducer () virtual
Member Function Documentation
Produce()
template<class CLASS > virtual void * Gui::PrefPageProducer< CLASS >::Produce () const virtual
Creates an instance of the specified widget.
Implements Base::AbstractProducer.
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/WidgetFactory.h