FreeCAD: Gui::Dialog::TextureMapping Class Reference
Gui::Dialog::TextureMapping Class Reference
#include <TextureMapping.h>
Public Member Functions
void accept ()
void reject ()
TextureMapping (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~TextureMapping ()
Protected Member Functions
void changeEvent (QEvent *e)
void keyPressEvent (QKeyEvent *e)
Constructor & Destructor Documentation
TextureMapping()
TextureMapping::TextureMapping (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
References Gui::Dialog::Ui_TextureMapping::checkGlobal, App::Application::Config(), Gui::Dialog::Ui_TextureMapping::fileChooser, App::GetApplication(), Gui::FileChooser::setFileName(), Gui::FileChooser::setFilter(), and Gui::Dialog::Ui_TextureMapping::setupUi().
~TextureMapping()
TextureMapping::~TextureMapping ()
Member Function Documentation
accept()
void TextureMapping::accept (void)
Referenced by Gui::Dialog::TaskTextureMapping::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void TextureMapping::changeEvent (QEvent * e) protected
References Gui::Dialog::Ui_TextureMapping::retranslateUi().
keyPressEvent()
void TextureMapping::keyPressEvent (QKeyEvent * e) protected
reject()
void TextureMapping::reject (void)
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), Gui::Dialog::TaskTextureMapping::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/TextureMapping.h
FreeCAD/src/Gui/TextureMapping.cpp