FreeCAD: PathScripts.PathStock Namespace Reference
PathScripts.PathStock Namespace Reference
Classes
class FakeJob
class Stock
class StockCreateBox
class StockCreateCylinder
class StockFromBase
class StockType
Functions
def CreateBox (job, extent=None, placement=None)
def CreateCylinder (job, radius=None, height=None, placement=None)
def CreateFromBase (job, neg=None, pos=None, placement=None)
def CreateFromTemplate (job, template)
def SetupStockObject (obj, stockType)
def shapeBoundBox (obj)
def TemplateAttributes (stock, includeExtent=True, includePlacement=True)
Variables
Part = LazyLoader("Part", globals(), "Part")
translate = FreeCAD.Qt.translate
Function Documentation
CreateBox()
def PathScripts.PathStock.CreateBox (job, extent = None, placement = None)
References PathScripts.PathStock.SetupStockObject(), and PathScripts.PathStock.shapeBoundBox().
Referenced by PathScripts.PathStock.CreateFromTemplate().
CreateCylinder()
def PathScripts.PathStock.CreateCylinder (job, radius = None, height = None, placement = None)
References PathScripts.PathStock.SetupStockObject(), and PathScripts.PathStock.shapeBoundBox().
Referenced by PathScripts.PathStock.CreateFromTemplate().
CreateFromBase()
def PathScripts.PathStock.CreateFromBase (job, neg = None, pos = None, placement = None)
References PathScripts.PathStock.SetupStockObject().
Referenced by PathScripts.PathStock.CreateFromTemplate().
CreateFromTemplate()
def PathScripts.PathStock.CreateFromTemplate (job, template)
References PathScripts.PathStock.CreateBox(), PathScripts.PathStock.CreateCylinder(), and PathScripts.PathStock.CreateFromBase().
SetupStockObject()
def PathScripts.PathStock.SetupStockObject (obj, stockType)
References draftutils.translate.QT_TRANSLATE_NOOP.
Referenced by PathScripts.PathStock.CreateBox(), PathScripts.PathStock.CreateCylinder(), and PathScripts.PathStock.CreateFromBase().
shapeBoundBox()
def PathScripts.PathStock.shapeBoundBox (obj)
References PathScripts.PathStock.shapeBoundBox().
Referenced by PathScripts.PathStock.CreateBox(), PathScripts.PathStock.CreateCylinder(), PathScripts.PathStock.StockFromBase.execute(), and PathScripts.PathStock.shapeBoundBox().
TemplateAttributes()
def PathScripts.PathStock.TemplateAttributes (stock, includeExtent = True, includePlacement = True)
Variable Documentation
Part
PathScripts.PathStock.Part = LazyLoader("Part", globals(), "Part")
translate
PathScripts.PathStock.translate = FreeCAD.Qt.translate