FreeCAD: Gui::RecentFilesAction Class Reference
Gui::RecentFilesAction Class Reference
The RecentFilesAction class holds a menu listed with the recent files.
#include <Action.h>
Classes
class Private
Public Member Functions
void activateFile (int)
void appendFile (const QString &)
Adds the new item to the recent files.
RecentFilesAction (Command *pcCmd, QObject *parent=0)
void resizeList (int)
virtual ~RecentFilesAction ()
Public Member Functions inherited from Gui::ActionGroup
ActionGroup (Command *pcCmd, QObject *parent=0)
Constructs an action called name with parent parent.
QList< QAction * > actions () const
QAction * addAction (const QString &)
QAction * addAction (QAction *)
void addTo (QWidget *w)
Adds this action to widget w.
int checkedAction () const
bool isExclusive () const
void setCheckedAction (int)
void setDisabled (bool)
void setDropDownMenu (bool b)
void setEnabled (bool)
Sets whether the action is enabled.
void setExclusive (bool)
void setVisible (bool)
virtual ~ActionGroup ()
Public Member Functions inherited from Gui::Action
QAction * action () const
Action (Command *pcCmd, QAction *action, QObject *parent)
Action takes ownership of the 'action' object.
Action (Command *pcCmd, QObject *parent=0)
Constructs an action called name with parent parent.
QIcon icon () const
bool isChecked () const
void setCheckable (bool)
void setChecked (bool, bool no_signal=false)
void setIcon (const QIcon &)
void setMenuRole (QAction::MenuRole menuRole)
void setShortcut (const QString &)
void setStatusTip (const QString &)
void setText (const QString &)
void setToolTip (const QString &)
void setWhatsThis (const QString &)
QKeySequence shortcut () const
QString statusTip () const
QString text () const
QString toolTip () const
QString whatsThis () const
virtual ~Action ()
Friends
class Private
Additional Inherited Members
Public Slots inherited from Gui::ActionGroup
void onActivated ()
Activates the command.
void onActivated (QAction *)
Activates the command.
void onHovered (QAction *)
void onToggled (bool)
Public Slots inherited from Gui::Action
virtual void onActivated ()
Activates the command.
virtual void onToggled (bool)
Sets whether the command is toggled.
Detailed Description
The RecentFilesAction class holds a menu listed with the recent files.
Author
Werner Mayer
Constructor & Destructor Documentation
RecentFilesAction()
RecentFilesAction::RecentFilesAction (Command * pcCmd, QObject * parent = 0)
References Private.
~RecentFilesAction()
RecentFilesAction::~RecentFilesAction () virtual
Member Function Documentation
activateFile()
void RecentFilesAction::activateFile (int id)
References Gui::getMainWindow(), Gui::SelectModule::importHandler(), Gui::Application::Instance, and Gui::Application::open().
Referenced by StdCmdRecentFiles::activated().
appendFile()
void RecentFilesAction::appendFile (const QString & filename)
Adds the new item to the recent files.
References App::Application::Config(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), App::Application::GetParameterSet(), and ParameterManager::SaveDocument().
Referenced by Gui::MainWindow::appendRecentFile().
resizeList()
void RecentFilesAction::resizeList (int size)
Friends And Related Function Documentation
Private
friend class Private friend
Referenced by RecentFilesAction().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Action.h
Sources/FreeCAD/src/Gui/Action.cpp