FreeCAD: MeshCore::LaplaceSmoothing Class Reference
MeshCore::LaplaceSmoothing Class Reference
#include <Smoothing.h>
Public Member Functions
LaplaceSmoothing (MeshKernel &)
void SetLambda (double l)
void Smooth (unsigned int)
Smooth the triangle mesh.
void SmoothPoints (unsigned int, const std::vector< PointIndex > &)
virtual ~LaplaceSmoothing ()
Public Member Functions inherited from MeshCore::AbstractSmoothing
AbstractSmoothing (MeshKernel &)
void initialize (Component comp, Continuity cont)
virtual void Smooth (unsigned int)=0
Smooth the triangle mesh.
virtual void SmoothPoints (unsigned int, const std::vector< PointIndex > &)=0
virtual ~AbstractSmoothing ()
Protected Member Functions
void Umbrella (const MeshRefPointToPoints &, const MeshRefPointToFacets &, double)
void Umbrella (const MeshRefPointToPoints &, const MeshRefPointToFacets &, double, const std::vector< PointIndex > &)
Protected Attributes
double lambda
Protected Attributes inherited from MeshCore::AbstractSmoothing
Component component
Continuity continuity
MeshKernel & kernel
float tolerance
Additional Inherited Members
Public Types inherited from MeshCore::AbstractSmoothing
enum Component { Tangential , Normal , TangentialNormal }
enum Continuity { C0 , C1 , C2 }
Constructor & Destructor Documentation
LaplaceSmoothing()
LaplaceSmoothing::LaplaceSmoothing (MeshKernel & m)
~LaplaceSmoothing()
LaplaceSmoothing::~LaplaceSmoothing () virtual
Member Function Documentation
SetLambda()
void MeshCore::LaplaceSmoothing::SetLambda (double l)
Smooth()
void LaplaceSmoothing::Smooth (unsigned int) virtual
Smooth the triangle mesh.
Implements MeshCore::AbstractSmoothing.
Reimplemented in MeshCore::TaubinSmoothing.
References MeshCore::AbstractSmoothing::kernel, lambda, and Umbrella().
Referenced by MeshGui::Segmentation::accept(), ReverseEngineeringGui::Segmentation::accept(), and MeshCore::MeshKernel::Smooth().
SmoothPoints()
void LaplaceSmoothing::SmoothPoints (unsigned int iterations, const std::vector< PointIndex > & point_indices) virtual
Implements MeshCore::AbstractSmoothing.
Reimplemented in MeshCore::TaubinSmoothing.
References MeshCore::AbstractSmoothing::kernel, lambda, and Umbrella().
Umbrella() [1/2]
void LaplaceSmoothing::Umbrella (const MeshRefPointToPoints & vv_it, const MeshRefPointToFacets & vf_it, double stepsize) protected
References MeshCore::MeshKernel::GetPoints(), MeshCore::AbstractSmoothing::kernel, and MeshCore::MeshKernel::SetPoint().
Referenced by Smooth(), MeshCore::TaubinSmoothing::Smooth(), SmoothPoints(), and MeshCore::TaubinSmoothing::SmoothPoints().
Umbrella() [2/2]
void LaplaceSmoothing::Umbrella (const MeshRefPointToPoints & vv_it, const MeshRefPointToFacets & vf_it, double stepsize, const std::vector< PointIndex > & point_indices) protected
References MeshCore::MeshKernel::GetPoints(), MeshCore::AbstractSmoothing::kernel, and MeshCore::MeshKernel::SetPoint().
Member Data Documentation
lambda
double MeshCore::LaplaceSmoothing::lambda protected
Referenced by Smooth(), MeshCore::TaubinSmoothing::Smooth(), SmoothPoints(), and MeshCore::TaubinSmoothing::SmoothPoints().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/Core/Smoothing.h
FreeCAD/src/Mod/Mesh/App/Core/Smoothing.cpp