FreeCAD: Gui::NS::InteractState Class Reference
Gui::NS::InteractState Class Reference
Public Types
typedef sc::custom_reaction< NS::Event > reactions
Public Member Functions
InteractState (my_context ctx)
sc::result react (const NS::Event &ev)
virtual ~InteractState ()
Member Typedef Documentation
reactions
typedef sc::custom_reaction<NS::Event> Gui::NS::InteractState::reactions
Constructor & Destructor Documentation
InteractState()
Gui::NS::InteractState::InteractState (my_context ctx)
References Base::Console(), Gui::NavigationStyle::INTERACT, and Base::ConsoleSingleton::Log().
~InteractState()
virtual Gui::NS::InteractState::~InteractState () virtual
Member Function Documentation
react()
sc::result Gui::NS::InteractState::react (const NS::Event & ev)
References Gui::NS::Event::flags, Gui::NS::Event::isMouseButtonEvent(), and Gui::NS::Event::mbstate().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/GestureNavigationStyle.cpp