FreeCAD: Ui_TaskDlgPathCompound Class Reference
Ui_TaskDlgPathCompound Class Reference
#include <ui_TaskDlgPathCompound.h>
Public Member Functions
void retranslateUi (QWidget *TaskDlgPathCompound)
void setupUi (QWidget *TaskDlgPathCompound)
Public Attributes
QLabel * label
QListWidget * PathsList
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void Ui_TaskDlgPathCompound::retranslateUi (QWidget * TaskDlgPathCompound)
References draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), PathGui::TaskWidgetPathCompound::changeEvent(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Ui_TaskDlgPathCompound::setupUi (QWidget * TaskDlgPathCompound)
References PathsList, retranslateUi(), and verticalLayout.
Referenced by PathGui::TaskWidgetPathCompound::TaskWidgetPathCompound().
Member Data Documentation
label
QLabel* Ui_TaskDlgPathCompound::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
PathsList
QListWidget* Ui_TaskDlgPathCompound::PathsList
Referenced by PathGui::TaskWidgetPathCompound::getList(), setupUi(), and PathGui::TaskWidgetPathCompound::TaskWidgetPathCompound().
verticalLayout
QVBoxLayout* Ui_TaskDlgPathCompound::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Path/Gui/ui_TaskDlgPathCompound.h