FreeCAD: SMESH_ProxyMesh Class Reference
SMESH_ProxyMesh Class Reference
Container of xD mesh elements substituting other ones in the input mesh of an (x+1)D algorithm.
#include <SMESH_ProxyMesh.hxx>
Classes
class SubMesh
Proxy sub-mesh.
Public Types
typedef boost::shared_ptr< SMESH_ProxyMesh > Ptr
typedef std::map< const SMDS_MeshNode *, const SMDS_MeshNode *, TIDCompare > TN2NMap
Public Member Functions
SMDS_ElemIteratorPtr GetFaces () const
Returns iterator on all faces of the mesh taking into account substitutions To be used in case of mesh without shape.
SMDS_ElemIteratorPtr GetFaces (const TopoDS_Shape &face) const
Returns iterator on all faces on the shape taking into account substitutions.
SMESH_Mesh * GetMesh () const
SMESHDS_Mesh * GetMeshDS () const
Returns mesh DS.
const SMDS_MeshNode * GetProxyNode (const SMDS_MeshNode *node) const
Returns the proxy node of a node; the input node is returned if no proxy exists.
const SubMesh * GetProxySubMesh (const TopoDS_Shape &shape) const
Returns the proxy sub-mesh of a shape; it can be NULL.
const SMESHDS_SubMesh * GetSubMesh (const TopoDS_Shape &shape) const
Returns the submesh of a shape; it can be a proxy sub-mesh.
bool IsTemporary (const SMDS_MeshElement *elem) const
Return true if the element is a temporary one.
int NbFaces () const
Return total nb of faces taking into account substitutions.
int NbProxySubMeshes () const
Returns number of proxy sub-meshes.
SMESH_ProxyMesh ()
Constructor; mesh must be set by a descendant class.
SMESH_ProxyMesh (const SMESH_Mesh &mesh)
SMESH_ProxyMesh (std::vector< SMESH_ProxyMesh::Ptr > &components)
Make a proxy mesh from components. Components become empty.
virtual ~SMESH_ProxyMesh ()
Destructor deletes proxy submeshes and tmp elemens.
Protected Member Functions
SubMesh * findProxySubMesh (int shapeIndex=0) const
Returns a proxy sub-mesh.
SubMesh * getProxySubMesh (const TopoDS_Shape &shape=TopoDS_Shape())
Returns a proxy sub-mesh; it is created if not yet exists.
SubMesh * getProxySubMesh (int shapeIndex)
Returns a proxy sub-mesh; it is created if not yet exists.
virtual SubMesh * newSubmesh (int index=0) const
void removeTmpElement (const SMDS_MeshElement *elem)
Removes tmp elements from the _mesh.
void setMesh (const SMESH_Mesh &mesh)
void setNode2Node (const SMDS_MeshNode *srcNode, const SMDS_MeshNode *proxyNode, const SubMesh *subMesh)
Set node-node correspondence.
int shapeIndex (const TopoDS_Shape &shape) const
Returns index of a shape.
void storeTmpElement (const SMDS_MeshElement *elem)
Stores tmp element residing the _mesh.
bool takeProxySubMesh (const TopoDS_Shape &shape, SMESH_ProxyMesh *proxyMesh)
Move proxy sub-mesh from other proxy mesh to this, returns true if sub-mesh found.
void takeTmpElemsInMesh (SMESH_ProxyMesh *proxyMesh)
Move tmp elements residing the _mesh from other proxy mesh to this.
Detailed Description
Container of xD mesh elements substituting other ones in the input mesh of an (x+1)D algorithm.
Member Typedef Documentation
Ptr
typedef boost::shared_ptr<SMESH_ProxyMesh> SMESH_ProxyMesh::Ptr
TN2NMap
typedef std::map<const SMDS_MeshNode*, const SMDS_MeshNode*, TIDCompare > SMESH_ProxyMesh::TN2NMap
Constructor & Destructor Documentation
SMESH_ProxyMesh() [1/3]
SMESH_ProxyMesh::SMESH_ProxyMesh ()
Constructor; mesh must be set by a descendant class.
SMESH_ProxyMesh() [2/3]
SMESH_ProxyMesh::SMESH_ProxyMesh (std::vector< SMESH_ProxyMesh::Ptr > & components)
Make a proxy mesh from components. Components become empty.
References takeTmpElemsInMesh().
SMESH_ProxyMesh() [3/3]
SMESH_ProxyMesh::SMESH_ProxyMesh (const SMESH_Mesh & mesh)
~SMESH_ProxyMesh()
SMESH_ProxyMesh::~SMESH_ProxyMesh () virtual
Destructor deletes proxy submeshes and tmp elemens.
References GetMeshDS(), and SMESHDS_Mesh::RemoveFreeElement().
Member Function Documentation
findProxySubMesh()
SMESH_ProxyMesh::SubMesh * SMESH_ProxyMesh::findProxySubMesh (int shapeIndex = 0) const protected
Returns a proxy sub-mesh.
References shapeIndex().
Referenced by StdMeshers_QuadToTriaAdaptor::Compute2ndPart(), GetProxyNode(), and takeProxySubMesh().
GetFaces() [1/2]
SMDS_ElemIteratorPtr SMESH_ProxyMesh::GetFaces () const
Returns iterator on all faces of the mesh taking into account substitutions To be used in case of mesh without shape.
References SMDS_Mesh::elementsIterator(), GetMeshDS(), and NbFaces().
Referenced by StdMeshers_QuadToTriaAdaptor::Compute().
GetFaces() [2/2]
SMDS_ElemIteratorPtr SMESH_ProxyMesh::GetFaces (const TopoDS_Shape & face) const
Returns iterator on all faces on the shape taking into account substitutions.
References GetSubMesh().
GetMesh()
SMESH_Mesh* SMESH_ProxyMesh::GetMesh () const
Referenced by VISCOUS_3D::_SolidData::GetShapeEdges(), and VISCOUS_3D::_SolidData::PrepareEdgesToSmoothOnFace().
GetMeshDS()
SMESHDS_Mesh * SMESH_ProxyMesh::GetMeshDS () const
Returns mesh DS.
Referenced by StdMeshers_QuadToTriaAdaptor::Compute2ndPart(), GetFaces(), GetProxyNode(), GetSubMesh(), VISCOUS_3D::_ViscousBuilder::MakeN2NMap(), NbFaces(), removeTmpElement(), shapeIndex(), and ~SMESH_ProxyMesh().
GetProxyNode()
const SMDS_MeshNode * SMESH_ProxyMesh::GetProxyNode (const SMDS_MeshNode * node) const
Returns the proxy node of a node; the input node is returned if no proxy exists.
References findProxySubMesh(), GetMeshDS(), SMDS_MeshNode::GetPosition(), SMDS_MeshElement::getshapeId(), SMESH_MesherHelper::GetSubShapeByNode(), SMDS_Position::GetTypeOfPosition(), and shapeIndex().
Referenced by SMESH_MesherHelper::LoadNodeColumns().
GetProxySubMesh()
const SMESH_ProxyMesh::SubMesh * SMESH_ProxyMesh::GetProxySubMesh (const TopoDS_Shape & shape) const
Returns the proxy sub-mesh of a shape; it can be NULL.
References shapeIndex().
Referenced by NETGENPlugin_Mesher::Compute(), and VISCOUS_3D::_ViscousBuilder::MakeN2NMap().
getProxySubMesh() [1/2]
SMESH_ProxyMesh::SubMesh * SMESH_ProxyMesh::getProxySubMesh (const TopoDS_Shape & shape = TopoDS_Shape()) protected
Returns a proxy sub-mesh; it is created if not yet exists.
References getProxySubMesh(), and shapeIndex().
getProxySubMesh() [2/2]
SMESH_ProxyMesh::SubMesh * SMESH_ProxyMesh::getProxySubMesh (int shapeIndex) protected
Returns a proxy sub-mesh; it is created if not yet exists.
References newSubmesh().
Referenced by StdMeshers_QuadToTriaAdaptor::Compute(), VISCOUS_3D::_MeshOfSolid::getFaceSubM(), and getProxySubMesh().
GetSubMesh()
const SMESHDS_SubMesh * SMESH_ProxyMesh::GetSubMesh (const TopoDS_Shape & shape) const
Returns the submesh of a shape; it can be a proxy sub-mesh.
References GetMeshDS(), SMESHDS_Mesh::MeshElements(), and shapeIndex().
Referenced by StdMeshers_QuadToTriaAdaptor::Compute(), GetFaces(), SMESH_MesherHelper::LoadNodeColumns(), and NbFaces().
IsTemporary()
bool SMESH_ProxyMesh::IsTemporary (const SMDS_MeshElement * elem) const
Return true if the element is a temporary one.
References SMDS_MeshElement::GetID().
Referenced by SMESH_MesherHelper::LoadNodeColumns().
NbFaces()
int SMESH_ProxyMesh::NbFaces () const
Return total nb of faces taking into account substitutions.
References DraftVecUtils::find(), GetMeshDS(), SMDS_Mesh::GetMeshInfo(), GetSubMesh(), SMDS_MeshInfo::NbEntities(), and SMDS_Mesh::NbFaces().
Referenced by GetFaces().
NbProxySubMeshes()
int SMESH_ProxyMesh::NbProxySubMeshes () const
Returns number of proxy sub-meshes.
newSubmesh()
virtual SubMesh* SMESH_ProxyMesh::newSubmesh (int index = 0) const protected virtual
Reimplemented in VISCOUS_2D::_ProxyMeshOfFace.
Referenced by getProxySubMesh().
removeTmpElement()
void SMESH_ProxyMesh::removeTmpElement (const SMDS_MeshElement * elem) protected
Removes tmp elements from the _mesh.
References SMDS_MeshElement::GetID(), GetMeshDS(), and SMESHDS_Mesh::RemoveFreeElement().
Referenced by StdMeshers_QuadToTriaAdaptor::Compute().
setMesh()
void SMESH_ProxyMesh::setMesh (const SMESH_Mesh & mesh) protected
Referenced by StdMeshers_QuadToTriaAdaptor::Compute().
setNode2Node()
void SMESH_ProxyMesh::setNode2Node (const SMDS_MeshNode * srcNode, const SMDS_MeshNode * proxyNode, const SubMesh * subMesh) protected
Set node-node correspondence.
Referenced by VISCOUS_3D::_MeshOfSolid::setNode2Node().
shapeIndex()
int SMESH_ProxyMesh::shapeIndex (const TopoDS_Shape & shape) const protected
Returns index of a shape.
References GetMeshDS().
Referenced by findProxySubMesh(), VISCOUS_3D::_MeshOfSolid::getFaceSubM(), GetProxyNode(), GetProxySubMesh(), getProxySubMesh(), GetSubMesh(), and takeProxySubMesh().
storeTmpElement()
void SMESH_ProxyMesh::storeTmpElement (const SMDS_MeshElement * elem) protected
Stores tmp element residing the _mesh.
Referenced by StdMeshers_QuadToTriaAdaptor::Compute().
takeProxySubMesh()
bool SMESH_ProxyMesh::takeProxySubMesh (const TopoDS_Shape & shape, SMESH_ProxyMesh * proxyMesh) protected
Move proxy sub-mesh from other proxy mesh to this, returns true if sub-mesh found.
References findProxySubMesh(), and shapeIndex().
Referenced by StdMeshers_QuadToTriaAdaptor::Compute().
takeTmpElemsInMesh()
void SMESH_ProxyMesh::takeTmpElemsInMesh (SMESH_ProxyMesh * proxyMesh) protected
Move tmp elements residing the _mesh from other proxy mesh to this.
Referenced by StdMeshers_QuadToTriaAdaptor::Compute(), and SMESH_ProxyMesh().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ProxyMesh.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/SMESH_ProxyMesh.cpp