FreeCAD: SketcherGui::DrawSketchHandlerBox Class Reference
SketcherGui::DrawSketchHandlerBox Class Reference
#include <DrawSketchHandlerRectangle.h>
Public Types
enum BoxMode { STATUS_SEEK_First , STATUS_SEEK_Second , STATUS_End }
mode table
enum ConstructionMethod { Diagonal , CenterAndCorner }
Public Member Functions
DrawSketchHandlerBox (ConstructionMethod constrMethod=Diagonal)
virtual void mouseMove (Base::Vector2d onSketchPos) override
virtual bool pressButton (Base::Vector2d onSketchPos) override
virtual bool releaseButton (Base::Vector2d onSketchPos) override
virtual ~DrawSketchHandlerBox ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void activate (ViewProviderSketch *)
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::PointPos::none, bool createowncommand=true)
void deactivate ()
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual void mouseMove (Base::Vector2d onSketchPos)=0
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual bool pressButton (Base::Vector2d onSketchPos)=0
virtual void quit (void)
virtual void registerPressedKey (bool, int)
virtual bool releaseButton (Base::Vector2d onSketchPos)=0
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Attributes
Base::Vector2d center
ConstructionMethod constructionMethod
std::vector< Base::Vector2d > EditCurve
BoxMode Mode
std::vector< AutoConstraint > sugConstr1
std::vector< AutoConstraint > sugConstr2
Protected Attributes inherited from SketcherGui::DrawSketchHandler
ViewProviderSketch * sketchgui
QCursor oldCursor
QCursor actCursor
QPixmap actCursorPixmap
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
virtual QString getCrosshairCursorSVGName () const
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
void updateCursor ()
updates the actCursor with the icon by calling getCrosshairCursorSVGName(), enabling to set data member dependent icons (i.e.
void unsetCursor (void)
restitutes the cursor that was in use at the moment of starting the DrawSketchHandler (i.e. oldCursor)
void applyCursor (void)
restitutes the DSH cached cursor (e.g. without any tail due to autoconstraints, ...)
unsigned long getCrosshairColor ()
returns the color to be used for the crosshair (configurable as a parameter)
qreal devicePixelRatio ()
functions to set the cursor to a given svgName (to be migrated to NVI style)
void drawEdit (const std::vector< Base::Vector2d > &EditCurve)
void drawEdit (const std::list< std::vector< Base::Vector2d > > &list)
void drawEdit (const std::vector< Part::Geometry * > &geometries)
void drawEditMarkers (const std::vector< Base::Vector2d > &EditMarkers, unsigned int augmentationlevel=0)
void setAxisPickStyle (bool on)
void moveCursorToSketchPoint (Base::Vector2d point)
void preselectAtPoint (Base::Vector2d point)
void drawPositionAtCursor (const Base::Vector2d &position)
void drawDirectionAtCursor (const Base::Vector2d &position, const Base::Vector2d &origin)
int getPreselectPoint (void) const
int getPreselectCurve (void) const
int getPreselectCross (void) const
Sketcher::SketchObject * getSketchObject ()
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
Member Enumeration Documentation
BoxMode
enum SketcherGui::DrawSketchHandlerBox::BoxMode
mode table
Enumerator
STATUS_SEEK_First
enum value -—.
STATUS_SEEK_Second
enum value -—.
STATUS_End
ConstructionMethod
enum SketcherGui::DrawSketchHandlerBox::ConstructionMethod
Enumerator
Diagonal
CenterAndCorner
Constructor & Destructor Documentation
DrawSketchHandlerBox()
SketcherGui::DrawSketchHandlerBox::DrawSketchHandlerBox (ConstructionMethod constrMethod = Diagonal)
~DrawSketchHandlerBox()
virtual SketcherGui::DrawSketchHandlerBox::~DrawSketchHandlerBox () virtual
Member Function Documentation
mouseMove()
virtual void SketcherGui::DrawSketchHandlerBox::mouseMove (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::applyCursor(), center, CenterAndCorner, constructionMethod, Diagonal, SketcherGui::DrawSketchHandler::drawEdit(), EditCurve, Mode, SketcherGui::DrawSketchHandler::renderSuggestConstraintsCursor(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), SketcherGui::DrawSketchHandler::setPositionText(), STATUS_SEEK_First, STATUS_SEEK_Second, sugConstr1, sugConstr2, Base::Vector2d::x, and Base::Vector2d::y.
pressButton()
virtual bool SketcherGui::DrawSketchHandlerBox::pressButton (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
References center, CenterAndCorner, constructionMethod, Diagonal, SketcherGui::DrawSketchHandler::drawEdit(), EditCurve, Mode, STATUS_End, STATUS_SEEK_First, STATUS_SEEK_Second, Base::Vector2d::x, and Base::Vector2d::y.
releaseButton()
virtual bool SketcherGui::DrawSketchHandlerBox::releaseButton (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), SketcherGui::DrawSketchHandler::applyCursor(), center, CenterAndCorner, Gui::Command::commitCommand(), Base::Console(), SketcherGui::Construction, constructionMethod, SketcherGui::DrawSketchHandler::createAutoConstraints(), Diagonal, Gui::Command::Doc, SketcherGui::DrawSketchHandler::drawEdit(), EditCurve, Sketcher::end, Base::ConsoleSingleton::Error(), SketcherGui::geometryCreationMode, App::GetApplication(), ParameterGrp::GetBool(), SketcherGui::DrawSketchHandler::getHighestCurveIndex(), Gui::ViewProviderDocumentObject::getObject(), Gui::Command::getObjectCmd(), App::Application::GetParameterGroupByPath(), Mode, Gui::Command::openCommand(), SketcherGui::ViewProviderSketch::purgeHandler(), draftutils.translate::QT_TRANSLATE_NOOP, SketcherGui::DrawSketchHandler::resetPositionText(), SketcherGui::DrawSketchHandler::sketchgui, Sketcher::start, STATUS_End, STATUS_SEEK_First, sugConstr1, sugConstr2, SketcherGui::tryAutoRecomputeIfNotSolve(), SketcherGui::DrawSketchHandler::unsetCursor(), Base::Vector2d::x, and Base::Vector2d::y.
Member Data Documentation
center
Base::Vector2d SketcherGui::DrawSketchHandlerBox::center protected
Referenced by drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rotate.Rotate::build_copy_subelements_command(), draftguitools.gui_scale.Scale::build_copy_subelements_command(), draftguitools.gui_rotate.Rotate::build_rotate_subelements_command(), draftguitools.gui_scale.Scale::build_scale_subelements_command(), draftguitools.gui_dimensions.Dimension::create_angle_dimension(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::create_object(), drafttaskpanels.task_polararray.TaskPanelPolarArray::create_object(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), PathScripts.PathDressupAxisMap.ObjectDressup::execute(), draftguitools.gui_rotate.Rotate::handle_mouse_move_event(), mouseMove(), draftguitools.gui_arcs.Arc::numericInput(), draftguitools.gui_polygons.Polygon::numericInput(), draftguitools.gui_rotate.Rotate::numericInput(), draftguitools.gui_arcs.Arc::numericRadius(), draftguitools.gui_polygons.Polygon::numericRadius(), PathScripts.PathDressupAxisMap.ObjectDressup::onChanged(), pressButton(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::print_messages(), drafttaskpanels.task_polararray.TaskPanelPolarArray::print_messages(), releaseButton(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reset_point(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reset_point(), draftguitools.gui_rotate.Rotate::rotate_object(), draftguitools.gui_scale.Scale::scale_object(), draftguitools.gui_rotate.Rotate::set_center(), draftguitools.gui_rotate.Rotate::set_ghosts(), and draftguitools.gui_rotate.Rotate::set_rotation_angle().
constructionMethod
ConstructionMethod SketcherGui::DrawSketchHandlerBox::constructionMethod protected
Referenced by mouseMove(), pressButton(), and releaseButton().
EditCurve
std::vector<Base::Vector2d> SketcherGui::DrawSketchHandlerBox::EditCurve protected
Referenced by mouseMove(), pressButton(), and releaseButton().
Mode
BoxMode SketcherGui::DrawSketchHandlerBox::Mode protected
Referenced by mouseMove(), pressButton(), and releaseButton().
sugConstr1
std::vector<AutoConstraint> SketcherGui::DrawSketchHandlerBox::sugConstr1 protected
Referenced by mouseMove(), and releaseButton().
sugConstr2
std::vector<AutoConstraint> SketcherGui::DrawSketchHandlerBox::sugConstr2 protected
Referenced by mouseMove(), and releaseButton().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/DrawSketchHandlerRectangle.h