FreeCAD: GUID Struct Reference
GUID Struct Reference
#include <GUID.h>
Public Member Functions
GUID ()
GUID (Context &cont)
GUID (uint32_t a1, uint16_t b1, uint16_t b2, uint8_t c1, uint8_t c2, uint8_t c3, uint8_t c4, uint8_t c5, uint8_t c6, uint8_t c7, uint8_t c8)
bool operator!= (const GUID &other) const
bool operator== (const GUID &other) const
void read (Context &cont)
std::string toString () const
Constructor & Destructor Documentation
GUID() [1/3]
GUID::GUID ()
GUID() [2/3]
GUID::GUID (uint32_t a1, uint16_t b1, uint16_t b2, uint8_t c1, uint8_t c2, uint8_t c3, uint8_t c4, uint8_t c5, uint8_t c6, uint8_t c7, uint8_t c8)
GUID() [3/3]
GUID::GUID (Context & cont)
References read().
Member Function Documentation
operator!=()
bool GUID::operator!= (const GUID & other) const
References operator==().
operator==()
bool GUID::operator== (const GUID & other) const
Referenced by operator!=().
read()
void GUID::read (Context & cont)
Referenced by GUID(), Segment_Header::read(), TOC_Entry::read(), Element_Header::read(), gzip_utf8.GzipFile::readline(), and gzip_utf8.GzipFile::seek().
toString()
std::string GUID::toString () const
Referenced by TOC_Entry::toString().
The documentation for this struct was generated from the following file:
FreeCAD/src/Mod/JtReader/App/JrJt/GUID.h