FreeCAD: App::PropertyContainer Class Reference
App::PropertyContainer Class Reference
Base class of all classes with properties.
#include <PropertyContainer.h>
Public Member Functions
virtual App::Property * addDynamicProperty (const char *type, const char *name=0, const char *group=0, const char *doc=0, short attr=0, bool ro=false, bool hidden=false)
virtual App::Property * getDynamicPropertyByName (const char *name) const
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual std::string getFullName () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Property * getPropertyByName (const char *name) const
find a property by its name
virtual const char * getPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * getPropertyGroup (const Property *prop) const
get the Group of a Property
virtual void getPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual const char * getPropertyName (const Property *prop) const
get the name of a property
const char * getPropertyPrefix () const
virtual short getPropertyType (const char *name) const
get the Type of a named Property
virtual short getPropertyType (const Property *prop) const
get the Type of a Property
bool isHidden (const char *name) const
check if the named property is hidden
bool isHidden (const Property *prop) const
check if the property is hidden
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isReadOnly (const Property *prop) const
check if the property is read-only
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus)
PropertyContainer ()
A constructor.
virtual bool removeDynamicProperty (const char *name)
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
void setPropertyPrefix (const char *prefix)
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
virtual ~PropertyContainer ()
A destructor.
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Member Functions
virtual const PropertyData & getPropertyData (void) const
virtual void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container.
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
virtual void onBeforeChange (const Property *)
get called before the value is changed
virtual void onChanged (const Property *)
get called by the container when a property has changed
Static Protected Member Functions
static const PropertyData * getPropertyDataPtr (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes
DynamicProperty dynamicProps
Friends
class DynamicProperty
class Property
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Detailed Description
Base class of all classes with properties.
Constructor & Destructor Documentation
PropertyContainer()
PropertyContainer::PropertyContainer ()
A constructor.
A more elaborate description of the constructor.
~PropertyContainer()
PropertyContainer::~PropertyContainer () virtual
A destructor.
A more elaborate description of the destructor.
Member Function Documentation
addDynamicProperty()
App::Property * PropertyContainer::addDynamicProperty (const char * type, const char * name = 0, const char * group = 0, const char * doc = 0, short attr = 0, bool ro = false, bool hidden = false) virtual
Reimplemented in Gui::ViewProviderDocumentObject, and App::DocumentObject.
References App::DynamicProperty::addDynamicProperty(), and dynamicProps.
Referenced by Gui::ViewProviderDocumentObject::addDynamicProperty(), Gui::ViewProviderPy::addProperty(), and App::TransactionObject::applyChn().
getDynamicPropertyByName()
virtual App::Property* App::PropertyContainer::getDynamicPropertyByName (const char * name) const virtual
Referenced by App::TransactionObject::applyChn(), App::DocumentObjectPy::getCustomAttributes(), Gui::ViewProviderPy::getCustomAttributes(), Gui::ViewProviderDocumentObject::removeDynamicProperty(), App::DocumentObjectPy::setCustomAttributes(), Gui::ViewProviderPy::setCustomAttributes(), and PartDesign::SubShapeBinder::update().
getDynamicPropertyData()
DynamicProperty::PropData App::PropertyContainer::getDynamicPropertyData (const Property * prop) const
Referenced by App::TransactionObject::addOrRemoveProperty(), and App::TransactionObject::setProperty().
getDynamicPropertyNames()
virtual std::vector<std::string> App::PropertyContainer::getDynamicPropertyNames () const virtual
Referenced by PartDesign::SubShapeBinder::update().
getFullName()
virtual std::string App::PropertyContainer::getFullName () const virtual
Reimplemented in Gui::ViewProviderDocumentObject, App::DocumentObject, and App::Document.
Referenced by App::Property::getFullName(), and App::PropertyLinkBase::tryReplaceLink().
getMemSize()
unsigned int PropertyContainer::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Reimplemented in Sketcher::SketchObject, App::Document, TechDraw::DrawTemplate, TechDraw::DrawSVGTemplate, and TechDraw::DrawParametricTemplate.
References getPropertyMap().
Referenced by App::Document::getMemSize().
getPropertyByName()
Property * PropertyContainer::getPropertyByName (const char * name) const virtual
find a property by its name
Reimplemented in Gui::ViewProviderLink, App::ExtensionContainer, and Spreadsheet::Sheet.
References dynamicProps, App::DynamicProperty::getDynamicPropertyByName(), App::PropertyData::getPropertyByName(), and getPropertyData().
Referenced by App::PropertyContainerPy::dumpPropertyContent(), App::DocumentPy::getCustomAttributes(), App::PropertyContainerPy::getCustomAttributes(), App::PropertyContainerPy::getDocumentationOfProperty(), App::PropertyContainerPy::getEditorMode(), App::PropertyContainerPy::getGroupOfProperty(), App::ExtensionContainer::getPropertyByName(), App::PropertyContainerPy::getPropertyByName(), App::PropertyContainerPy::getPropertyStatus(), App::PropertyContainerPy::getPropertyTouchList(), getPropertyType(), App::PropertyContainerPy::getTypeIdOfProperty(), App::PropertyContainerPy::getTypeOfProperty(), Restore(), App::PropertyContainerPy::restorePropertyContent(), App::DocumentPy::setCustomAttributes(), App::PropertyContainerPy::setCustomAttributes(), App::PropertyContainerPy::setEditorMode(), and App::PropertyContainerPy::setPropertyStatus().
getPropertyData()
const PropertyData & PropertyContainer::getPropertyData (void) const protected virtual
Reimplemented in App::Origin.
Referenced by getPropertyByName(), getPropertyDocumentation(), getPropertyGroup(), getPropertyList(), getPropertyMap(), and getPropertyName().
getPropertyDataPtr()
const PropertyData * PropertyContainer::getPropertyDataPtr (void) static protected
getPropertyDocumentation() [1/2]
const char * PropertyContainer::getPropertyDocumentation (const char * name) const virtual
get the Group of a named Property
Reimplemented in App::ExtensionContainer.
References dynamicProps, App::PropertyData::getDocumentation(), getPropertyData(), and App::DynamicProperty::getPropertyDocumentation().
getPropertyDocumentation() [2/2]
const char * PropertyContainer::getPropertyDocumentation (const Property * prop) const virtual
get the Group of a Property
Reimplemented in App::ExtensionContainer.
References dynamicProps, App::PropertyData::getDocumentation(), getPropertyData(), and App::DynamicProperty::getPropertyDocumentation().
Referenced by App::Property::getDocumentation(), App::PropertyContainerPy::getDocumentationOfProperty(), and App::ExtensionContainer::getPropertyDocumentation().
getPropertyGroup() [1/2]
const char * PropertyContainer::getPropertyGroup (const char * name) const virtual
get the Group of a named Property
Reimplemented in App::ExtensionContainer.
References dynamicProps, App::PropertyData::getGroup(), getPropertyData(), and App::DynamicProperty::getPropertyGroup().
getPropertyGroup() [2/2]
const char * PropertyContainer::getPropertyGroup (const Property * prop) const virtual
get the Group of a Property
Reimplemented in App::ExtensionContainer.
References dynamicProps, App::PropertyData::getGroup(), getPropertyData(), and App::DynamicProperty::getPropertyGroup().
Referenced by App::Property::getGroup(), App::PropertyContainerPy::getGroupOfProperty(), and App::ExtensionContainer::getPropertyGroup().
getPropertyList()
void PropertyContainer::getPropertyList (std::vector< Property * > & List) const virtual
get all properties of the class (including properties of the parent)
Reimplemented in App::ExtensionContainer, and Gui::ViewProviderLink.
References dynamicProps, getPropertyData(), App::PropertyData::getPropertyList(), and App::DynamicProperty::getPropertyList().
Referenced by App::ExtensionContainer::getPropertyList(), PartDesignGui::isAnyNonPartDesignLinksTo(), Gui::Application::reopen(), and setPropertyStatus().
getPropertyMap()
void PropertyContainer::getPropertyMap (std::map< std::string, Property * > & Map) const virtual
get all properties of the class (including properties of the parent)
Reimplemented in App::ExtensionContainer, and Gui::ViewProviderLink.
References dynamicProps, getPropertyData(), App::PropertyData::getPropertyMap(), and App::DynamicProperty::getPropertyMap().
Referenced by App::PropertyContainerPy::getCustomAttributes(), getMemSize(), App::PropertyContainerPy::getPropertiesList(), App::ExtensionContainer::getPropertyMap(), and Save().
getPropertyName()
const char * PropertyContainer::getPropertyName (const Property * prop) const virtual
get the name of a property
Reimplemented in App::ExtensionContainer.
References dynamicProps, App::PropertyData::getName(), getPropertyData(), and App::DynamicProperty::getPropertyName().
Referenced by App::ExtensionContainer::getPropertyName().
getPropertyPrefix()
const char* App::PropertyContainer::getPropertyPrefix () const
Referenced by Gui::PropertyEditor::PropertyItem::setPropertyValue().
getPropertyType() [1/2]
short PropertyContainer::getPropertyType (const char * name) const virtual
get the Type of a named Property
Reimplemented in App::ExtensionContainer.
References getPropertyByName(), and getPropertyType().
getPropertyType() [2/2]
short PropertyContainer::getPropertyType (const Property * prop) const virtual
get the Type of a Property
Reimplemented in App::ExtensionContainer.
References App::Property::getType().
Referenced by getPropertyType(), App::ExtensionContainer::getPropertyType(), isHidden(), isReadOnly(), Restore(), and Save().
handleChangedPropertyName()
void PropertyContainer::handleChangedPropertyName (Base::XMLReader & reader, const char * TypeName, const char * PropName) protected virtual
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container.
This method is typically called if the property on file has changed its name in more recent versions.
The default implementation does nothing.
Parameters
reader The XML stream to read from.
TypeName Name of property type on file.
PropName Name of property on file that does not exist in the container anymore.
Reimplemented in TechDraw::DrawViewPart, TechDraw::DrawViewBalloon, Surface::Extend, PartDesign::FeaturePrimitive, PartDesign::Boolean, Part::Part2DObject, Part::Datum, Part::BodyBase, App::LinkElement, App::Link, and Fem::FemAnalysis.
Referenced by Fem::FemAnalysis::handleChangedPropertyName(), Part::BodyBase::handleChangedPropertyName(), Surface::Extend::handleChangedPropertyName(), TechDraw::DrawViewBalloon::handleChangedPropertyName(), TechDraw::DrawViewPart::handleChangedPropertyName(), and Restore().
handleChangedPropertyType()
void PropertyContainer::handleChangedPropertyType (Base::XMLReader & reader, const char * TypeName, Property * prop) protected virtual
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
This method is typically called if the property on file has changed its type in more recent versions.
The default implementation does nothing.
Parameters
reader The XML stream to read from.
TypeName Name of property type on file.
prop Pointer to property to restore. Its type differs from TypeName.
Reimplemented in TechDraw::DrawViewBalloon, TechDraw::DrawView, TechDraw::DrawProjGroup, TechDraw::DrawPage, PartDesign::SubShapeBinder, PartDesign::ShapeBinder, Part::Part2DObject, TechDrawGui::ViewProviderViewPart, TechDrawGui::ViewProviderRichAnno, TechDrawGui::ViewProviderLeader, TechDrawGui::ViewProviderDimension, TechDrawGui::ViewProviderBalloon, TechDraw::DrawViewAnnotation, TechDraw::DrawTile, PartGui::ViewProvider2DObjectGrid, Part::Thickness, Part::Mirroring, and TechDraw::DrawViewDimension.
Referenced by PartDesign::SubShapeBinder::handleChangedPropertyType(), and Restore().
isHidden() [1/2]
bool PropertyContainer::isHidden (const char * name) const
check if the named property is hidden
References getPropertyType(), and App::Prop_Hidden.
isHidden() [2/2]
bool PropertyContainer::isHidden (const Property * prop) const
check if the property is hidden
References getPropertyType(), and App::Prop_Hidden.
Referenced by Gui::Dialog::find_placement::operator()().
isReadOnly() [1/2]
bool PropertyContainer::isReadOnly (const char * name) const
check if the named property is read-only
References getPropertyType(), and App::Prop_ReadOnly.
isReadOnly() [2/2]
bool PropertyContainer::isReadOnly (const Property * prop) const
check if the property is read-only
References getPropertyType(), and App::Prop_ReadOnly.
Referenced by Gui::Dialog::find_placement::operator()(), Gui::PropertyEditor::PropertyItem::setPropertyData(), Gui::PropertyEditor::PropertyItem::setPropertyValue(), and Gui::PropertyEditor::PropertyItem::updateData().
onBeforeChange()
virtual void App::PropertyContainer::onBeforeChange (const Property *) protected virtual
get called before the value is changed
Reimplemented in App::DocumentObject, App::Document, TechDraw::DrawPage, Part::BodyBase, Gui::ViewProviderDocumentObject, Drawing::FeaturePage, Gui::ViewProvider, and Gui::ViewProviderLink.
Referenced by App::Property::aboutToSetValue(), and Gui::ViewProvider::onBeforeChange().
onChanged()
virtual void App::PropertyContainer::onChanged (const Property *) protected virtual
get called by the container when a property has changed
Reimplemented in App::DocumentObject, App::Document, App::TextDocument, App::MeasureDistance, App::ExtensionContainer, TechDrawGui::ViewProviderTemplate, TechDrawGui::ViewProviderPage, TechDrawGui::ViewProviderHatch, TechDrawGui::ViewProviderGeomHatch, TechDrawGui::ViewProviderDrawingView, TechDraw::LandmarkDimension, TechDraw::DrawViewSymbol, TechDraw::DrawViewSection, TechDraw::DrawViewPart, TechDraw::DrawViewMulti, TechDraw::DrawViewDimension, TechDraw::DrawViewDetail, TechDraw::DrawViewBalloon, TechDraw::DrawView, TechDraw::DrawProjGroupItem, TechDraw::DrawProjGroup, TechDraw::DrawPage, TechDraw::DrawLeaderLine, TechDraw::DrawHatch, TechDraw::DrawGeomHatch, Surface::Extend, PartDesignGui::ViewProviderBoolean, PartDesignGui::ViewProviderBody, PartDesignGui::ViewProvider, PartDesign::SubShapeBinder, PartDesign::FeaturePrimitive, PartDesign::Boolean, PartDesign::Point, PartDesign::Body, PartGui::ViewProviderPartExt, Part::Primitive, Part::Feature, Part::Revolution, Part::BodyBase, Gui::ViewProviderPlacement, Gui::ViewProviderPart, Gui::ViewProviderLink, Gui::ViewProviderDocumentObject, TechDrawGui::ViewProviderViewSection, TechDrawGui::ViewProviderViewPart, TechDrawGui::ViewProviderProjGroup, TechDrawGui::ViewProviderImage, TechDraw::DrawWeldSymbol, TechDraw::DrawViewSpreadsheet, TechDraw::DrawViewImage, TechDraw::DrawViewDimExtent, TechDraw::DrawViewCollection, TechDraw::DrawViewClip, TechDraw::DrawViewAnnotation, TechDraw::DrawTileWeld, TechDraw::DrawTile, TechDraw::DrawTemplate, TechDraw::DrawSVGTemplate, TechDraw::DrawRichAnno, TechDraw::DrawParametricTemplate, SketcherGui::ViewProviderSketch, SketcherGui::ViewProviderCustom, Sandbox::SandboxObject, RobotGui::ViewProviderRobotObject, Robot::TrajectoryObject, Robot::TrajectoryDressUpObject, Robot::RobotObject, Robot::Edge2TracObject, PointsGui::ViewProviderPoints, Points::Feature, PathGui::ViewProviderPath, Path::Feature, PartDesignGui::ViewProviderDatumPoint, PartDesign::ProfileBased, PartDesign::Hole, PartDesign::DressUp, PartDesign::FeatureBase, PartDesign::Plane, PartDesign::Line, PartGui::ViewProviderSpline, PartGui::ViewProviderPartReference, PartGui::ViewProviderCustom, PartGui::ViewProvider2DObjectGrid, Part::Wedge, Part::Spiral, Part::Helix, Part::Sweep, Part::Loft, Part::RuledSurface, Part::Box, Part::Mirroring, MeshGui::ViewProviderMeshNode, MeshGui::ViewProviderMeshDefects, MeshGui::ViewProviderMeshCurvature, MeshGui::ViewProviderMesh, Mesh::Feature, InspectionGui::ViewProviderInspection, FemGui::ViewProviderFemPostObject, FemGui::ViewProviderFemPostFunction, FemGui::ViewProviderFemPostFunctionProvider, FemGui::ViewProviderFemMesh, FemGui::ViewProviderFemConstraint, Fem::FemPostPipeline, Fem::FemPostSphereFunction, Fem::FemPostPlaneFunction, Fem::FemPostFunctionProvider, Fem::FemPostCutFilter, Fem::FemPostWarpVectorFilter, Fem::FemPostScalarClipFilter, Fem::FemPostDataAtPointFilter, Fem::FemPostDataAlongLineFilter, Fem::FemPostClipFilter, Fem::FemMeshObject, Fem::ConstraintTransform, Fem::ConstraintTemperature, Fem::ConstraintPulley, Fem::ConstraintPressure, Fem::ConstraintPlaneRotation, Fem::ConstraintInitialTemperature, Fem::ConstraintHeatflux, Fem::ConstraintGear, Fem::ConstraintForce, Fem::ConstraintFluidBoundary, Fem::ConstraintFixed, Fem::ConstraintDisplacement, Fem::ConstraintContact, Fem::ConstraintBearing, Fem::Constraint, Drawing::FeatureViewSymbol, Drawing::FeaturePage, Drawing::FeatureClip, Gui::ViewProviderTextDocument, Gui::ViewProviderOriginFeature, Gui::ViewProviderOrigin, Gui::ViewProviderMeasureDistance, Gui::ViewProviderGeometryObject, Gui::ViewProviderAnnotationLabel, Gui::ViewProviderAnnotation, Gui::ViewProvider, TechDrawGui::ViewProviderWeld, TechDrawGui::ViewProviderRichAnno, TechDrawGui::ViewProviderLeader, TechDrawGui::ViewProviderDimension, TechDrawGui::ViewProviderBalloon, Sketcher::SketchObject, PartDesign::Chamfer, Surface::GeomFillSurface, PartDesignGui::ViewProviderDatumCoordinateSystem, Part::Ellipse, Part::Line, Part::Vertex, Part::Circle, and App::VRMLObject.
Referenced by draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSite.Compass::buildCoordinates(), draftobjects.wire.Wire::execute(), App::Property::hasSetValue(), ArchAxis.CommandArchGrid::IsActive(), App::ExtensionContainer::onChanged(), App::Property::touch(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchPanel.ViewProviderPanelSheet::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), and draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData().
onPropertyStatusChanged()
void PropertyContainer::onPropertyStatusChanged (const Property & prop, unsigned long oldStatus) virtual
Reimplemented in App::DocumentObject, and Gui::ViewProviderDocumentObject.
Referenced by App::Property::setStatusValue().
removeDynamicProperty()
virtual bool App::PropertyContainer::removeDynamicProperty (const char * name) virtual
Reimplemented in Gui::ViewProviderDocumentObject, and App::DocumentObject.
Referenced by App::TransactionObject::applyChn(), Gui::ViewProviderDocumentObject::removeDynamicProperty(), and Gui::ViewProviderPy::removeProperty().
Restore()
void PropertyContainer::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Reimplemented in PartDesign::Chamfer, Part::Primitive, Part::Part2DObject, App::ExtensionContainer, App::Document, Points::Feature, PartDesign::Transformed, PartDesign::ProfileBased, PartDesign::Hole, PartDesign::Fillet, PartGui::ViewProvider2DObjectGrid, Part::Box, Gui::ViewProvider, App::VRMLObject, Sketcher::SketchObject, and Robot::RobotObject.
References Base::XMLReader::clearPartialRestoreProperty(), Base::Console(), dynamicProps, Base::ConsoleSingleton::Error(), Base::XMLReader::getAttribute(), Base::XMLReader::getAttributeAsInteger(), Base::XMLReader::getAttributeAsUnsigned(), App::Property::getName(), getPropertyByName(), getPropertyType(), handleChangedPropertyName(), handleChangedPropertyType(), Base::XMLReader::hasAttribute(), App::Prop_Transient, App::Property::PropTransient, Base::XMLReader::readElement(), Base::XMLReader::readEndElement(), App::DynamicProperty::restore(), Base::XMLReader::setPartialRestore(), App::Property::setStatusValue(), App::Property::StatusBits, Base::XMLReader::testStatus(), and App::Property::Transient.
Referenced by App::Document::Restore(), and App::ExtensionContainer::Restore().
Save()
void PropertyContainer::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Reimplemented in App::ExtensionContainer, App::DocumentObject, App::Document, App::VRMLObject, Sketcher::SketchObject, and Robot::RobotObject.
References Base::Console(), Base::Writer::decInd(), dynamicProps, Base::ConsoleSingleton::Error(), getPropertyMap(), getPropertyType(), Base::Writer::incInd(), Base::Writer::ind(), App::Prop_Transient, App::Property::PropDynamic, App::Property::PropNoPersist, App::DynamicProperty::save(), Base::Writer::Stream(), and App::Property::Transient.
Referenced by App::Document::Save(), and App::ExtensionContainer::Save().
setPropertyPrefix()
void App::PropertyContainer::setPropertyPrefix (const char * prefix)
Referenced by Gui::ViewProviderLink::onChanged().
setPropertyStatus()
void PropertyContainer::setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
References getPropertyList().
Friends And Related Function Documentation
DynamicProperty
friend class DynamicProperty friend
Property
friend class Property friend
Member Data Documentation
dynamicProps
DynamicProperty App::PropertyContainer::dynamicProps protected
Referenced by addDynamicProperty(), getPropertyByName(), getPropertyDocumentation(), getPropertyGroup(), getPropertyList(), getPropertyMap(), getPropertyName(), Restore(), Part::Box::Restore(), and Save().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/App/PropertyContainer.h
Sources/FreeCAD/src/App/PropertyContainer.cpp