FreeCAD: PathTests.TestPathSetupSheet Namespace Reference
PathTests.TestPathSetupSheet Namespace Reference
Classes
class TestPathSetupSheet
Functions
def refstring (string)
Function Documentation
refstring()
def PathTests.TestPathSetupSheet.refstring (string)
Referenced by PathTests.TestPathSetupSheet.TestPathSetupSheet.test11(), PathTests.TestPathSetupSheet.TestPathSetupSheet.test12(), and PathTests.TestPathSetupSheet.TestPathSetupSheet.test13().