FreeCAD: Gui::DockWnd::ReportOutputObserver Class Reference
Gui::DockWnd::ReportOutputObserver Class Reference
Observer to enable report view on warnings / errors if not already enabled.
#include <ReportView.h>
Public Member Functions
bool eventFilter (QObject *obj, QEvent *event)
ReportOutputObserver (ReportOutput *view)
The ReportOutputObserver class is used to check if messages sent to the report view are warnings or errors, and if so and if the user has not disabled this in preferences, the report view is toggled on so the user always gets the warnings/errors.
Protected Member Functions
void showReportView (void)
Protected Attributes
QPointer< ReportOutput > reportView
Detailed Description
Observer to enable report view on warnings / errors if not already enabled.
Constructor & Destructor Documentation
ReportOutputObserver()
ReportOutputObserver::ReportOutputObserver (ReportOutput * view)
The ReportOutputObserver class is used to check if messages sent to the report view are warnings or errors, and if so and if the user has not disabled this in preferences, the report view is toggled on so the user always gets the warnings/errors.
References reportView.
Member Function Documentation
eventFilter()
bool ReportOutputObserver::eventFilter (QObject * obj, QEvent * event)
References Gui::DockWnd::ReportHighlighter::Error, Gui::DockWnd::ReportHighlighter::LogText, Gui::DockWnd::ReportHighlighter::Message, CustomReportEvent::messageType(), reportView, Gui::ReportOutputParameter::showOnError(), Gui::ReportOutputParameter::showOnLogMessage(), Gui::ReportOutputParameter::showOnMessage(), Gui::ReportOutputParameter::showOnWarning(), showReportView(), and Gui::DockWnd::ReportHighlighter::Warning.
showReportView()
void ReportOutputObserver::showReportView (void) protected
References Gui::DockWindowManager::activate(), Gui::DockWindowManager::instance(), and reportView.
Referenced by eventFilter().
Member Data Documentation
reportView
QPointer<ReportOutput> Gui::DockWnd::ReportOutputObserver::reportView protected
Referenced by eventFilter(), ReportOutputObserver(), and showReportView().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/ReportView.h
FreeCAD/src/Gui/ReportView.cpp