FreeCAD: PathScripts.post.smoothie_post Namespace Reference
PathScripts.post.smoothie_post Namespace Reference
Functions
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
def processArguments (argstring)
def sendToSmoothie (ip, GCODE, fname)
Variables
action
string COMMAND_SPACE = " "
dictionary CORNER_MAX = {"x": 500, "y": 300, "z": 300}
dictionary CORNER_MIN = {"x": 0, "y": 0, "z": 0}
default
help
IP_ADDR = None
int LINENR = 100
string MACHINE_NAME = "SmoothieBoard"
bool MODAL = False
now = datetime.datetime.now()
bool OUTPUT_COMMENTS = True
bool OUTPUT_HEADER = True
bool OUTPUT_LINE_NUMBERS = False
parser = argparse.ArgumentParser(prog="linuxcnc", add_help=False)
string POST_OPERATION = """"""
string POSTAMBLE
string PRE_OPERATION = """"""
string PREAMBLE
int PRECISION = 5
pythonopen = open
bool SHOW_EDITOR = True
float SPINDLE_SPEED = 0.0
string TOOL_CHANGE = """"""
string TOOLTIP
TOOLTIP_ARGS = parser.format_help()
string UNIT_FORMAT = "mm"
string UNIT_SPEED_FORMAT = "mm/min"
string UNITS = "G21"
bool VERBOSE = False
Function Documentation
export()
def PathScripts.post.smoothie_post.export (objectslist, filename, argstring)
References PathScripts.post.smoothie_post.linenumber(), PathScripts.post.smoothie_post.parse(), PathScripts.post.smoothie_post.processArguments(), PathScripts.post.smoothie_post.pythonopen, and PathScripts.post.smoothie_post.sendToSmoothie().
linenumber()
def PathScripts.post.smoothie_post.linenumber ()
Referenced by PathScripts.post.smoothie_post.export(), and PathScripts.post.smoothie_post.parse().
parse()
def PathScripts.post.smoothie_post.parse (pathobj)
References PathScripts.post.smoothie_post.linenumber(), and PathScripts.post.smoothie_post.parse().
Referenced by PathScripts.post.smoothie_post.export(), and PathScripts.post.smoothie_post.parse().
processArguments()
def PathScripts.post.smoothie_post.processArguments (argstring)
Referenced by PathScripts.post.smoothie_post.export().
sendToSmoothie()
def PathScripts.post.smoothie_post.sendToSmoothie (ip, GCODE, fname)
Referenced by PathScripts.post.smoothie_post.export().
Variable Documentation
action
PathScripts.post.smoothie_post.action
COMMAND_SPACE
string PathScripts.post.smoothie_post.COMMAND_SPACE = " "
CORNER_MAX
dictionary PathScripts.post.smoothie_post.CORNER_MAX = {"x": 500, "y": 300, "z": 300}
CORNER_MIN
dictionary PathScripts.post.smoothie_post.CORNER_MIN = {"x": 0, "y": 0, "z": 0}
default
PathScripts.post.smoothie_post.default
help
PathScripts.post.smoothie_post.help
IP_ADDR
PathScripts.post.smoothie_post.IP_ADDR = None
LINENR
int PathScripts.post.smoothie_post.LINENR = 100
MACHINE_NAME
string PathScripts.post.smoothie_post.MACHINE_NAME = "SmoothieBoard"
MODAL
bool PathScripts.post.smoothie_post.MODAL = False
now
PathScripts.post.smoothie_post.now = datetime.datetime.now()
OUTPUT_COMMENTS
bool PathScripts.post.smoothie_post.OUTPUT_COMMENTS = True
OUTPUT_HEADER
bool PathScripts.post.smoothie_post.OUTPUT_HEADER = True
OUTPUT_LINE_NUMBERS
bool PathScripts.post.smoothie_post.OUTPUT_LINE_NUMBERS = False
parser
PathScripts.post.smoothie_post.parser = argparse.ArgumentParser(prog="linuxcnc", add_help=False)
POST_OPERATION
string PathScripts.post.smoothie_post.POST_OPERATION = """"""
POSTAMBLE
string PathScripts.post.smoothie_post.POSTAMBLE
Initial value:
=  """M05
G17 G90
M2
"""
PRE_OPERATION
string PathScripts.post.smoothie_post.PRE_OPERATION = """"""
PREAMBLE
string PathScripts.post.smoothie_post.PREAMBLE
Initial value:
=  """G17 G90
"""
PRECISION
int PathScripts.post.smoothie_post.PRECISION = 5
pythonopen
PathScripts.post.smoothie_post.pythonopen = open
Referenced by PathScripts.post.smoothie_post.export().
SHOW_EDITOR
bool PathScripts.post.smoothie_post.SHOW_EDITOR = True
SPINDLE_SPEED
float PathScripts.post.smoothie_post.SPINDLE_SPEED = 0.0
TOOL_CHANGE
string PathScripts.post.smoothie_post.TOOL_CHANGE = """"""
TOOLTIP
string PathScripts.post.smoothie_post.TOOLTIP
Initial value:
=  """
This is a postprocessor file for the Path workbench. It is used to
take a pseudo-gcode fragment outputted by a Path object, and output
real GCode suitable for a smoothieboard. This postprocessor, once placed
in the appropriate PathScripts folder, can be used directly from inside
FreeCAD, via the GUI importer or via python scripts with:
import smoothie_post
smoothie_post.export(object,"/path/to/file.ncc","")
"""
TOOLTIP_ARGS
PathScripts.post.smoothie_post.TOOLTIP_ARGS = parser.format_help()
UNIT_FORMAT
string PathScripts.post.smoothie_post.UNIT_FORMAT = "mm"
UNIT_SPEED_FORMAT
string PathScripts.post.smoothie_post.UNIT_SPEED_FORMAT = "mm/min"
UNITS
string PathScripts.post.smoothie_post.UNITS = "G21"
VERBOSE
bool PathScripts.post.smoothie_post.VERBOSE = False