FreeCAD: Path::AreaPy Class Reference
Path::AreaPy Class Reference
The python export class for Area.
#include <AreaPy.h>
Public Types
typedef Area * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
AreaPy (Area *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of AreaPy.
static PyMethodDef Methods []
Methods structure of AreaPy.
static PyTypeObject Type
Type structure of AreaPy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~AreaPy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * add (PyObject *args, PyObject *kwd)
implementer for the add() method
PyObject * setPlane (PyObject *args)
implementer for the setPlane() method
PyObject * getShape (PyObject *args, PyObject *kwd)
implementer for the getShape() method
PyObject * makeOffset (PyObject *args, PyObject *kwd)
implementer for the makeOffset() method
PyObject * makePocket (PyObject *args, PyObject *kwd)
implementer for the makePocket() method
PyObject * makeSections (PyObject *args, PyObject *kwd)
implementer for the makeSections() method
PyObject * setParams (PyObject *args, PyObject *kwd)
implementer for the setParams() method
PyObject * setDefaultParams (PyObject *args, PyObject *kwd)
implementer for the setDefaultParams() method
PyObject * getDefaultParams (PyObject *args)
implementer for the getDefaultParams() method
PyObject * getParamsDesc (PyObject *args, PyObject *kwd)
implementer for the getParamsDesc() method
PyObject * getParams (PyObject *args)
implementer for the getParams() method
PyObject * abort (PyObject *args, PyObject *kwd)
implementer for the abort() method
static PyObject * staticCallback_add (PyObject *self, PyObject *args, PyObject *kwd)
callback for the add() method
static PyObject * staticCallback_setPlane (PyObject *self, PyObject *args)
callback for the setPlane() method
static PyObject * staticCallback_getShape (PyObject *self, PyObject *args, PyObject *kwd)
callback for the getShape() method
static PyObject * staticCallback_makeOffset (PyObject *self, PyObject *args, PyObject *kwd)
callback for the makeOffset() method
static PyObject * staticCallback_makePocket (PyObject *self, PyObject *args, PyObject *kwd)
callback for the makePocket() method
static PyObject * staticCallback_makeSections (PyObject *self, PyObject *args, PyObject *kwd)
callback for the makeSections() method
static PyObject * staticCallback_setParams (PyObject *self, PyObject *args, PyObject *kwd)
callback for the setParams() method
static PyObject * staticCallback_setDefaultParams (PyObject *self, PyObject *args, PyObject *kwd)
callback for the setDefaultParams() method
static PyObject * staticCallback_getDefaultParams (PyObject *self, PyObject *args)
callback for the getDefaultParams() method
static PyObject * staticCallback_getParamsDesc (PyObject *self, PyObject *args, PyObject *kwd)
callback for the getParamsDesc() method
static PyObject * staticCallback_getParams (PyObject *self, PyObject *args)
callback for the getParams() method
static PyObject * staticCallback_abort (PyObject *self, PyObject *args, PyObject *kwd)
callback for the abort() method
callbacks and implementers for the python object attributes
Py::List getSections (void) const
getter for the Sections attribute
Py::Object getWorkplane (void) const
getter for the Workplane attribute
void setWorkplane (Py::Object arg)
setter for the Workplane attribute
Py::List getShapes (void) const
getter for the Shapes attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Area * getAreaPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getSections (PyObject *self, void *closure)
getter callback for the Sections attribute
static int staticCallback_setSections (PyObject *self, PyObject *value, void *closure)
setter callback for the Sections attribute
static PyObject * staticCallback_getWorkplane (PyObject *self, void *closure)
getter callback for the Workplane attribute
static int staticCallback_setWorkplane (PyObject *self, PyObject *value, void *closure)
setter callback for the Workplane attribute
static PyObject * staticCallback_getShapes (PyObject *self, void *closure)
getter callback for the Shapes attribute
static int staticCallback_setShapes (PyObject *self, PyObject *value, void *closure)
setter callback for the Shapes attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Area.
Member Typedef Documentation
PointerType
typedef Area* Path::AreaPy::PointerType
Constructor & Destructor Documentation
~AreaPy()
AreaPy::~AreaPy () protected
AreaPy()
AreaPy::AreaPy (Area * pcObject, PyTypeObject * T = &Type)
Referenced by makeSections(), and PyMake().
Member Function Documentation
abort()
PyObject * AreaPy::abort (PyObject * args, PyObject * kwd)
implementer for the abort() method
Referenced by PathScripts.PathDressupLeadInOut.TaskPanel::clicked(), femsolver.run.Machine::run(), and staticCallback_abort().
add()
PyObject * AreaPy::add (PyObject * args, PyObject * kwd)
implementer for the add() method
References Path::Area::add(), getAreaPtr(), PARAM_FARG, PARAM_FIELD_STRINGS, PARAM_PY_DECLARE_INIT, PARAM_PY_FIELDS, PARAM_PY_KWDS, PARAM_REF, and Part::TopoShapePy::Type.
Referenced by staticCallback_add().
getAreaPtr()
Area * AreaPy::getAreaPtr (void) const
getter for the object handled by this class
Referenced by add(), getParams(), getSections(), getShape(), getShapes(), getWorkplane(), makeOffset(), makePocket(), makeSections(), representation(), setParams(), setPlane(), and setWorkplane().
getCustomAttributes()
PyObject * AreaPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getDefaultParams()
PyObject * AreaPy::getDefaultParams (PyObject * args)
implementer for the getDefaultParams() method
Referenced by staticCallback_getDefaultParams().
getParams()
PyObject * AreaPy::getParams (PyObject * args)
implementer for the getParams() method
References getAreaPtr(), Path::Area::getParams(), and PARAM_PY_DICT_SET_VALUE.
Referenced by staticCallback_getParams().
getParamsDesc()
PyObject * AreaPy::getParamsDesc (PyObject * args, PyObject * kwd)
implementer for the getParamsDesc() method
Referenced by staticCallback_getParamsDesc().
getSections()
Py::List AreaPy::getSections (void) const
getter for the Sections attribute
References getAreaPtr(), Path::Area::getSectionCount(), getShape(), and Part::shape2pyshape().
Referenced by staticCallback_getSections().
getShape()
PyObject * AreaPy::getShape (PyObject * args, PyObject * kwd)
implementer for the getShape() method
References Path::Area::clean(), getAreaPtr(), and Part::shape2pyshape().
Referenced by getSections(), and staticCallback_getShape().
getShapes()
Py::List AreaPy::getShapes (void) const
getter for the Shapes attribute
References getAreaPtr(), Path::Area::getChildren(), and Part::shape2pyshape().
Referenced by ArchBuildingPart.BuildingPart::execute(), and staticCallback_getShapes().
GetType()
virtual PyTypeObject* Path::AreaPy::GetType (void) virtual
Reimplemented from Base::BaseClassPy.
getWorkplane()
Py::Object AreaPy::getWorkplane (void) const
getter for the Workplane attribute
References getAreaPtr(), and Part::shape2pyshape().
Referenced by staticCallback_getWorkplane().
makeOffset()
PyObject * AreaPy::makeOffset (PyObject * args, PyObject * kwd)
implementer for the makeOffset() method
References getAreaPtr(), Path::Area::makeOffset(), PARAM_FARG, PARAM_FIELD_STRINGS, PARAM_PY_DECLARE_INIT, PARAM_PY_FIELDS, PARAM_PY_KWDS, PARAM_REF, and Part::shape2pyshape().
Referenced by staticCallback_makeOffset().
makePocket()
PyObject * AreaPy::makePocket (PyObject * args, PyObject * kwd)
implementer for the makePocket() method
References getAreaPtr(), Path::Area::makePocket(), PARAM_FARG, PARAM_FIELD_STRINGS, PARAM_PY_DECLARE_INIT, PARAM_PY_FIELDS, PARAM_PY_KWDS, PARAM_REF, and Part::shape2pyshape().
Referenced by staticCallback_makePocket().
makeSections()
PyObject * AreaPy::makeSections (PyObject * args, PyObject * kwd)
implementer for the makeSections() method
References AreaPy(), getAreaPtr(), Path::Area::makeSections(), PARAM_FARG, PARAM_FIELD_STRINGS, PARAM_PY_DECLARE_INIT, PARAM_PY_FIELDS, PARAM_PY_KWDS, PARAM_REF, and Part::TopoShapePy::Type.
Referenced by staticCallback_makeSections().
PyInit()
int AreaPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::BaseClassPy.
PyMake()
PyObject * AreaPy::PyMake (struct _typeobject * , PyObject * args, PyObject * kwd) static
References AreaPy(), and setParams().
representation()
std::string AreaPy::representation (void) const
References getAreaPtr().
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int AreaPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setDefaultParams()
PyObject * AreaPy::setDefaultParams (PyObject * args, PyObject * kwd)
implementer for the setDefaultParams() method
Referenced by staticCallback_setDefaultParams().
setParams()
PyObject * AreaPy::setParams (PyObject * args, PyObject * kwd)
implementer for the setParams() method
References getAreaPtr(), Path::Area::getParams(), PARAM_FIELD_STRINGS, PARAM_FNAME, PARAM_FOREACH, PARAM_PY_DECLARE, PARAM_PY_KWDS, PARAM_REF, and Path::Area::setParams().
Referenced by PyMake(), and staticCallback_setParams().
setPlane()
PyObject * AreaPy::setPlane (PyObject * args)
implementer for the setPlane() method
References getAreaPtr(), Path::Area::setPlane(), and Part::TopoShapePy::Type.
Referenced by staticCallback_setPlane().
setWorkplane()
void AreaPy::setWorkplane (Py::Object arg)
setter for the Workplane attribute
References getAreaPtr(), Path::Area::setPlane(), and Part::TopoShapePy::Type.
Referenced by staticCallback_setWorkplane().
staticCallback_abort()
PyObject * AreaPy::staticCallback_abort (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the abort() method
References abort(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_add()
PyObject * AreaPy::staticCallback_add (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the add() method
References add(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getDefaultParams()
PyObject * AreaPy::staticCallback_getDefaultParams (PyObject * self, PyObject * args) static
callback for the getDefaultParams() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getDefaultParams(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getParams()
PyObject * AreaPy::staticCallback_getParams (PyObject * self, PyObject * args) static
callback for the getParams() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getParams(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getParamsDesc()
PyObject * AreaPy::staticCallback_getParamsDesc (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the getParamsDesc() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getParamsDesc(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getSections()
PyObject * AreaPy::staticCallback_getSections (PyObject * self, void * closure) static
getter callback for the Sections attribute
References Base::BaseExceptionFreeCADError, getSections(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getShape()
PyObject * AreaPy::staticCallback_getShape (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the getShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getShape(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getShapes()
PyObject * AreaPy::staticCallback_getShapes (PyObject * self, void * closure) static
getter callback for the Shapes attribute
References Base::BaseExceptionFreeCADError, getShapes(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getWorkplane()
PyObject * AreaPy::staticCallback_getWorkplane (PyObject * self, void * closure) static
getter callback for the Workplane attribute
References Base::BaseExceptionFreeCADError, getWorkplane(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_makeOffset()
PyObject * AreaPy::staticCallback_makeOffset (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the makeOffset() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), makeOffset(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_makePocket()
PyObject * AreaPy::staticCallback_makePocket (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the makePocket() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), makePocket(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_makeSections()
PyObject * AreaPy::staticCallback_makeSections (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the makeSections() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), makeSections(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_setDefaultParams()
PyObject * AreaPy::staticCallback_setDefaultParams (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the setDefaultParams() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setDefaultParams(), and Base::PyObjectBase::startNotify().
staticCallback_setParams()
PyObject * AreaPy::staticCallback_setParams (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the setParams() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setParams(), and Base::PyObjectBase::startNotify().
staticCallback_setPlane()
PyObject * AreaPy::staticCallback_setPlane (PyObject * self, PyObject * args) static
callback for the setPlane() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setPlane(), and Base::PyObjectBase::startNotify().
staticCallback_setSections()
int AreaPy::staticCallback_setSections (PyObject * self, PyObject * value, void * closure) static
setter callback for the Sections attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setShapes()
int AreaPy::staticCallback_setShapes (PyObject * self, PyObject * value, void * closure) static
setter callback for the Shapes attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setWorkplane()
int AreaPy::staticCallback_setWorkplane (PyObject * self, PyObject * value, void * closure) static
setter callback for the Workplane attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setWorkplane().
Member Data Documentation
GetterSetter
PyGetSetDef AreaPy::GetterSetter static
Initial value:
= {
    {"Sections",
        (getter) staticCallback_getSections,
        (setter) staticCallback_setSections,
        "List of sections in this area.",
        NULL
    },
    {"Workplane",
        (getter) staticCallback_getWorkplane,
        (setter) staticCallback_setWorkplane,
        "The current workplane. If no plane is set, it is derived from the added shapes.",
        NULL
    },
    {"Shapes",
        (getter) staticCallback_getShapes,
        (setter) staticCallback_setShapes,
        "A list of tuple: [(shape,op), ...] containing the added shapes together with their operation code",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of AreaPy.
Methods
PyMethodDef AreaPy::Methods static
Methods structure of AreaPy.
Referenced by AreaPyModifier::AreaPyModifier().
Type
PyTypeObject AreaPy::Type static
Type structure of AreaPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/AreaPy.h
Sources/FreeCAD/src/Mod/Path/App/AreaPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/AreaPy.cpp