FreeCAD: MeshGui::Ui_DlgSettingsImportExport Class Reference
MeshGui::Ui_DlgSettingsImportExport Class Reference
#include <ui_DlgSettingsImportExport.h>
Public Member Functions
void retranslateUi (QWidget *MeshGui__DlgSettingsImportExport)
void setupUi (QWidget *MeshGui__DlgSettingsImportExport)
Public Attributes
QLineEdit * asymptoteHeight
QLineEdit * asymptoteWidth
Gui::PrefCheckBox * exportAmfCompressed
QGridLayout * gridLayout
QGridLayout * gridLayout1
QGridLayout * gridLayout2
QGridLayout * gridLayout3
QGridLayout * gridLayout4
QGroupBox * GroupBox12
QGroupBox * GroupBoxAsy
QLabel * labelAsyHeight
QLabel * labelAsyWidth
Gui::QuantitySpinBox * maxDeviationExport
QSpacerItem * spacerItem
QSpacerItem * spacerItem1
QLabel * textLabel1
Member Function Documentation
retranslateUi()
void MeshGui::Ui_DlgSettingsImportExport::retranslateUi (QWidget * MeshGui__DlgSettingsImportExport)
References exportAmfCompressed, GroupBox12, labelAsyHeight, labelAsyWidth, maxDeviationExport, textLabel1, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), MeshGui::DlgSettingsImportExport::changeEvent(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void MeshGui::Ui_DlgSettingsImportExport::setupUi (QWidget * MeshGui__DlgSettingsImportExport)
References asymptoteHeight, asymptoteWidth, exportAmfCompressed, gridLayout, gridLayout1, gridLayout2, gridLayout3, gridLayout4, GroupBox12, GroupBoxAsy, labelAsyHeight, labelAsyWidth, maxDeviationExport, retranslateUi(), Gui::QuantitySpinBox::setMaximum(), Gui::QuantitySpinBox::setMinimum(), Gui::QuantitySpinBox::setSingleStep(), Gui::QuantitySpinBox::setValue(), spacerItem, spacerItem1, and textLabel1.
Referenced by MeshGui::DlgSettingsImportExport::DlgSettingsImportExport().
Member Data Documentation
asymptoteHeight
QLineEdit* MeshGui::Ui_DlgSettingsImportExport::asymptoteHeight
Referenced by MeshGui::DlgSettingsImportExport::loadSettings(), MeshGui::DlgSettingsImportExport::saveSettings(), and setupUi().
asymptoteWidth
QLineEdit* MeshGui::Ui_DlgSettingsImportExport::asymptoteWidth
Referenced by MeshGui::DlgSettingsImportExport::loadSettings(), MeshGui::DlgSettingsImportExport::saveSettings(), and setupUi().
exportAmfCompressed
Gui::PrefCheckBox* MeshGui::Ui_DlgSettingsImportExport::exportAmfCompressed
Referenced by MeshGui::DlgSettingsImportExport::DlgSettingsImportExport(), MeshGui::DlgSettingsImportExport::loadSettings(), retranslateUi(), MeshGui::DlgSettingsImportExport::saveSettings(), and setupUi().
gridLayout
QGridLayout* MeshGui::Ui_DlgSettingsImportExport::gridLayout
Referenced by setupUi().
gridLayout1
QGridLayout* MeshGui::Ui_DlgSettingsImportExport::gridLayout1
Referenced by setupUi().
gridLayout2
QGridLayout* MeshGui::Ui_DlgSettingsImportExport::gridLayout2
Referenced by setupUi().
gridLayout3
QGridLayout* MeshGui::Ui_DlgSettingsImportExport::gridLayout3
Referenced by setupUi().
gridLayout4
QGridLayout* MeshGui::Ui_DlgSettingsImportExport::gridLayout4
Referenced by setupUi().
GroupBox12
QGroupBox* MeshGui::Ui_DlgSettingsImportExport::GroupBox12
Referenced by retranslateUi(), and setupUi().
GroupBoxAsy
QGroupBox* MeshGui::Ui_DlgSettingsImportExport::GroupBoxAsy
Referenced by setupUi().
labelAsyHeight
QLabel* MeshGui::Ui_DlgSettingsImportExport::labelAsyHeight
Referenced by retranslateUi(), and setupUi().
labelAsyWidth
QLabel* MeshGui::Ui_DlgSettingsImportExport::labelAsyWidth
Referenced by retranslateUi(), and setupUi().
maxDeviationExport
Gui::QuantitySpinBox* MeshGui::Ui_DlgSettingsImportExport::maxDeviationExport
Referenced by MeshGui::DlgSettingsImportExport::loadSettings(), retranslateUi(), MeshGui::DlgSettingsImportExport::saveSettings(), and setupUi().
spacerItem
QSpacerItem* MeshGui::Ui_DlgSettingsImportExport::spacerItem
Referenced by setupUi().
spacerItem1
QSpacerItem* MeshGui::Ui_DlgSettingsImportExport::spacerItem1
Referenced by setupUi().
textLabel1
QLabel* MeshGui::Ui_DlgSettingsImportExport::textLabel1
Referenced by retranslateUi(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Mesh/Gui/ui_DlgSettingsImportExport.h