FreeCAD: SurfaceGui::GeomFillSurface Class Reference
SurfaceGui::GeomFillSurface Class Reference
#include <TaskGeomFillSurface.h>
Classes
class EdgeSelection
Public Member Functions
bool accept ()
void checkOpenCommand ()
GeomFillSurface (ViewProviderGeomFillSurface *vp, Surface::GeomFillSurface *obj)
void open ()
bool reject ()
void setEditedObject (Surface::GeomFillSurface *obj)
~GeomFillSurface ()
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Public Member Functions inherited from Gui::DocumentObserver
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
Protected Types
enum SelectionMode { }
Protected Member Functions
void changeEvent (QEvent *e)
void changeFillType (GeomFill_FillingStyle)
void flipOrientation (QListWidgetItem *)
virtual void onSelectionChanged (const Gui::SelectionChanges &msg)
virtual void slotDeletedObject (const Gui::ViewProviderDocumentObject &Obj)
Notifies when the object is about to be removed.
virtual void slotRedoDocument (const Gui::Document &Doc)
Notifies on redo.
virtual void slotUndoDocument (const Gui::Document &Doc)
Notifies on undo.
Protected Attributes
bool checkCommand
Surface::GeomFillSurface * editedObject
SelectionMode selectionMode
Member Enumeration Documentation
SelectionMode
enum SurfaceGui::GeomFillSurface::SelectionMode protected
Enumerator
Append
Remove
Constructor & Destructor Documentation
GeomFillSurface()
SurfaceGui::GeomFillSurface::GeomFillSurface (ViewProviderGeomFillSurface * vp, Surface::GeomFillSurface * obj)
References checkCommand, draftgeoutils.intersections::connect(), SurfaceGui::Ui_GeomFillSurface::listWidget, selectionMode, setEditedObject(), and SurfaceGui::Ui_GeomFillSurface::setupUi().
Referenced by SurfaceGui::TaskGeomFillSurface::TaskGeomFillSurface().
~GeomFillSurface()
SurfaceGui::GeomFillSurface::~GeomFillSurface ()
Member Function Documentation
accept()
bool SurfaceGui::GeomFillSurface::accept (void)
References Gui::Command::commitCommand(), editedObject, App::DocumentObject::getStatusString(), Gui::Command::Gui, SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), App::DocumentObject::isValid(), SurfaceGui::Ui_GeomFillSurface::listWidget, Surface::GeomFillSurface::mustExecute(), App::DocumentObject::recomputeFeature(), Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), selectionMode, and Gui::Command::updateActive().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void SurfaceGui::GeomFillSurface::changeEvent (QEvent * e) protected
References SurfaceGui::Ui_GeomFillSurface::retranslateUi().
changeFillType()
void SurfaceGui::GeomFillSurface::changeFillType (GeomFill_FillingStyle fillType) protected
References checkOpenCommand(), Base::Console(), editedObject, Base::ConsoleSingleton::Error(), Surface::GeomFillSurface::FillType, App::DocumentObject::getStatusString(), App::PropertyEnumeration::getValue(), App::DocumentObject::isValid(), App::DocumentObject::recomputeFeature(), and App::PropertyEnumeration::setValue().
checkOpenCommand()
void SurfaceGui::GeomFillSurface::checkOpenCommand ()
References checkCommand, editedObject, App::PropertyString::getValue(), Gui::Command::hasPendingCommand(), App::DocumentObject::Label, and Gui::Command::openCommand().
Referenced by changeFillType(), onSelectionChanged(), and open().
flipOrientation()
void SurfaceGui::GeomFillSurface::flipOrientation (QListWidgetItem * item) protected
References Gui::BitmapFactory(), editedObject, SurfaceGui::Ui_GeomFillSurface::listWidget, Gui::BitmapFactoryInst::pixmap(), App::DocumentObject::recomputeFeature(), and Surface::GeomFillSurface::ReversedList.
onSelectionChanged()
void SurfaceGui::GeomFillSurface::onSelectionChanged (const Gui::SelectionChanges & msg) protected virtual
Implements Gui::SelectionObserver.
References Gui::SelectionChanges::AddSelection, Append, Gui::BitmapFactory(), Surface::GeomFillSurface::BoundaryList, checkOpenCommand(), editedObject, Gui::SelectionObject::getObject(), App::PropertyLinkSubList::getSubValues(), App::PropertyString::getValue(), App::PropertyLinkSubList::getValues(), SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), App::DocumentObject::Label, SurfaceGui::Ui_GeomFillSurface::listWidget, App::DocumentObject::recomputeFeature(), Surface::GeomFillSurface::ReversedList, selectionMode, and App::PropertyLinkSubList::setValues().
open()
void SurfaceGui::GeomFillSurface::open ()
References checkOpenCommand(), Gui::SelectionSingleton::clearSelection(), SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), and Gui::Selection().
reject()
bool SurfaceGui::GeomFillSurface::reject (void)
References Gui::Command::abortCommand(), Gui::Command::Gui, SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), selectionMode, and Gui::Command::updateActive().
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
setEditedObject()
void SurfaceGui::GeomFillSurface::setEditedObject (Surface::GeomFillSurface * obj)
References Gui::DocumentObserver::attachDocument(), Gui::BitmapFactory(), Surface::GeomFillSurface::BoundaryList, editedObject, Surface::GeomFillSurface::FillType, SurfaceGui::Ui_GeomFillSurface::fillType_coons, SurfaceGui::Ui_GeomFillSurface::fillType_curved, SurfaceGui::Ui_GeomFillSurface::fillType_stretch, App::DocumentObject::getDocument(), App::PropertyLinkSubList::getSubValues(), App::PropertyEnumeration::getValue(), App::PropertyLinkSubList::getValues(), Gui::Application::Instance, SurfaceGui::Ui_GeomFillSurface::listWidget, Gui::BitmapFactoryInst::pixmap(), and Surface::GeomFillSurface::ReversedList.
Referenced by GeomFillSurface().
slotDeletedObject()
void SurfaceGui::GeomFillSurface::slotDeletedObject (const Gui::ViewProviderDocumentObject & Obj) protected virtual
Notifies when the object is about to be removed.
Reimplemented from Gui::DocumentObserver.
References SurfaceGui::ViewProviderGeomFillSurface::highlightReferences().
slotRedoDocument()
void SurfaceGui::GeomFillSurface::slotRedoDocument (const Gui::Document & Doc) protected virtual
Notifies on redo.
Reimplemented from Gui::DocumentObserver.
References checkCommand.
slotUndoDocument()
void SurfaceGui::GeomFillSurface::slotUndoDocument (const Gui::Document & Doc) protected virtual
Notifies on undo.
Reimplemented from Gui::DocumentObserver.
References checkCommand.
Member Data Documentation
checkCommand
bool SurfaceGui::GeomFillSurface::checkCommand protected
Referenced by checkOpenCommand(), GeomFillSurface(), slotRedoDocument(), and slotUndoDocument().
editedObject
Surface::GeomFillSurface* SurfaceGui::GeomFillSurface::editedObject protected
Referenced by accept(), changeFillType(), checkOpenCommand(), flipOrientation(), onSelectionChanged(), and setEditedObject().
selectionMode
SelectionMode SurfaceGui::GeomFillSurface::selectionMode protected
Referenced by accept(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonRef1(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonRef2(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonSupport(), GeomFillSurface(), onSelectionChanged(), and reject().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Surface/Gui/TaskGeomFillSurface.h
FreeCAD/src/Mod/Surface/Gui/TaskGeomFillSurface.cpp