FreeCAD: feminout.importInpMesh Namespace Reference
feminout.importInpMesh Namespace Reference
Functions
def import_inp (filename)
def insert (filename, docname)
def open (filename)
def read (filename)
def read_inp (file_name)
Variables
pyopen = open
Function Documentation
import_inp()
def feminout.importInpMesh.import_inp (filename)
read a FEM mesh from a Z88 mesh file and insert a FreeCAD FEM Mesh object in the ActiveDocument
References feminout.importInpMesh.read().
Referenced by feminout.importInpMesh.insert().
insert()
def feminout.importInpMesh.insert (filename, docname)
References feminout.importInpMesh.import_inp().
Referenced by feminout.importInpMesh.open().
open()
def feminout.importInpMesh.open (filename)
References feminout.importInpMesh.insert().
read()
def feminout.importInpMesh.read (filename)
read a FemMesh from a inp mesh file and return the FemMesh
References feminout.importInpMesh.read_inp().
Referenced by feminout.importInpMesh.import_inp().
read_inp()
def feminout.importInpMesh.read_inp (file_name)
read .inp file
References feminout.importInpMesh.pyopen.
Referenced by feminout.importInpMesh.read().
Variable Documentation
pyopen
feminout.importInpMesh.pyopen = open
Referenced by feminout.importInpMesh.read_inp().