FreeCAD: Gui::LinkViewPy Class Reference
Gui::LinkViewPy Class Reference
The python export class for LinkView.
#include <LinkViewPy.h>
Public Types
typedef LinkView * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
LinkViewPy (LinkView *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of LinkViewPy.
static PyMethodDef Methods []
Methods structure of LinkViewPy.
static PyTypeObject Type
Type structure of LinkViewPy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~LinkViewPy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * reset (PyObject *args)
implementer for the reset() method
PyObject * setMaterial (PyObject *args)
implementer for the setMaterial() method
PyObject * setType (PyObject *args)
implementer for the setType() method
PyObject * setTransform (PyObject *args)
implementer for the setTransform() method
PyObject * setChildren (PyObject *args)
implementer for the setChildren() method
PyObject * setLink (PyObject *args)
implementer for the setLink() method
PyObject * getDetailPath (PyObject *args)
implementer for the getDetailPath() method
PyObject * getElementPicked (PyObject *args)
implementer for the getElementPicked() method
PyObject * getBoundBox (PyObject *args)
implementer for the getBoundBox() method
PyObject * getChildren (PyObject *args)
implementer for the getChildren() method
static PyObject * staticCallback_reset (PyObject *self, PyObject *args)
callback for the reset() method
static PyObject * staticCallback_setMaterial (PyObject *self, PyObject *args)
callback for the setMaterial() method
static PyObject * staticCallback_setType (PyObject *self, PyObject *args)
callback for the setType() method
static PyObject * staticCallback_setTransform (PyObject *self, PyObject *args)
callback for the setTransform() method
static PyObject * staticCallback_setChildren (PyObject *self, PyObject *args)
callback for the setChildren() method
static PyObject * staticCallback_setLink (PyObject *self, PyObject *args)
callback for the setLink() method
static PyObject * staticCallback_getDetailPath (PyObject *self, PyObject *args)
callback for the getDetailPath() method
static PyObject * staticCallback_getElementPicked (PyObject *self, PyObject *args)
callback for the getElementPicked() method
static PyObject * staticCallback_getBoundBox (PyObject *self, PyObject *args)
callback for the getBoundBox() method
static PyObject * staticCallback_getChildren (PyObject *self, PyObject *args)
callback for the getChildren() method
callbacks and implementers for the python object attributes
Py::Object getLinkedView (void) const
getter for the LinkedView attribute
Py::Object getSubNames (void) const
getter for the SubNames attribute
Py::Object getRootNode (void) const
getter for the RootNode attribute
Py::Object getOwner (void) const
getter for the Owner attribute
void setOwner (Py::Object arg)
setter for the Owner attribute
Py::Object getVisibilities (void) const
getter for the Visibilities attribute
void setVisibilities (Py::Object arg)
setter for the Visibilities attribute
Py::Int getCount (void) const
getter for the Count attribute
void setCount (Py::Int arg)
setter for the Count attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
LinkView * getLinkViewPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getLinkedView (PyObject *self, void *closure)
getter callback for the LinkedView attribute
static int staticCallback_setLinkedView (PyObject *self, PyObject *value, void *closure)
setter callback for the LinkedView attribute
static PyObject * staticCallback_getSubNames (PyObject *self, void *closure)
getter callback for the SubNames attribute
static int staticCallback_setSubNames (PyObject *self, PyObject *value, void *closure)
setter callback for the SubNames attribute
static PyObject * staticCallback_getRootNode (PyObject *self, void *closure)
getter callback for the RootNode attribute
static int staticCallback_setRootNode (PyObject *self, PyObject *value, void *closure)
setter callback for the RootNode attribute
static PyObject * staticCallback_getOwner (PyObject *self, void *closure)
getter callback for the Owner attribute
static int staticCallback_setOwner (PyObject *self, PyObject *value, void *closure)
setter callback for the Owner attribute
static PyObject * staticCallback_getVisibilities (PyObject *self, void *closure)
getter callback for the Visibilities attribute
static int staticCallback_setVisibilities (PyObject *self, PyObject *value, void *closure)
setter callback for the Visibilities attribute
static PyObject * staticCallback_getCount (PyObject *self, void *closure)
getter callback for the Count attribute
static int staticCallback_setCount (PyObject *self, PyObject *value, void *closure)
setter callback for the Count attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for LinkView.
Member Typedef Documentation
PointerType
typedef LinkView* Gui::LinkViewPy::PointerType
Constructor & Destructor Documentation
~LinkViewPy()
LinkViewPy::~LinkViewPy () protected
LinkViewPy()
LinkViewPy::LinkViewPy (LinkView * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getBoundBox()
PyObject * LinkViewPy::getBoundBox (PyObject * args)
implementer for the getBoundBox() method
References Gui::LinkView::getBoundBox(), getLinkViewPtr(), and Gui::ViewProviderDocumentObjectPy::Type.
Referenced by staticCallback_getBoundBox().
getChildren()
PyObject * LinkViewPy::getChildren (PyObject * args)
implementer for the getChildren() method
References Gui::LinkView::getChildren(), and getLinkViewPtr().
Referenced by staticCallback_getChildren().
getCount()
Py::Int LinkViewPy::getCount (void) const
getter for the Count attribute
References getLinkViewPtr().
Referenced by staticCallback_getCount().
getCustomAttributes()
PyObject * LinkViewPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getDetailPath()
PyObject * LinkViewPy::getDetailPath (PyObject * args)
implementer for the getDetailPath() method
References Base::InterpreterSingleton::convertSWIGPointerObj(), Base::InterpreterSingleton::createSWIGPointerObj(), getLinkViewPtr(), Base::Interpreter(), and Gui::LinkView::linkGetDetailPath().
Referenced by staticCallback_getDetailPath().
getElementPicked()
PyObject * LinkViewPy::getElementPicked (PyObject * args)
implementer for the getElementPicked() method
References Base::InterpreterSingleton::convertSWIGPointerObj(), getLinkViewPtr(), and Base::Interpreter().
Referenced by staticCallback_getElementPicked().
getLinkedView()
Py::Object LinkViewPy::getLinkedView (void) const
getter for the LinkedView attribute
References Gui::LinkView::getLinkedView(), and getLinkViewPtr().
Referenced by staticCallback_getLinkedView().
getLinkViewPtr()
LinkView * LinkViewPy::getLinkViewPtr (void) const
getter for the object handled by this class
Referenced by getBoundBox(), getChildren(), getCount(), getDetailPath(), getElementPicked(), getLinkedView(), getOwner(), getRootNode(), getSubNames(), getVisibilities(), reset(), setChildren(), setCount(), setLink(), setMaterial(), setOwner(), setTransform(), setType(), and setVisibilities().
getOwner()
Py::Object LinkViewPy::getOwner (void) const
getter for the Owner attribute
References getLinkViewPtr(), and Gui::LinkView::getOwner().
Referenced by staticCallback_getOwner().
getRootNode()
Py::Object LinkViewPy::getRootNode (void) const
getter for the RootNode attribute
References Base::InterpreterSingleton::createSWIGPointerObj(), Gui::LinkView::getLinkRoot(), getLinkViewPtr(), and Base::Interpreter().
Referenced by staticCallback_getRootNode().
getSubNames()
Py::Object LinkViewPy::getSubNames (void) const
getter for the SubNames attribute
References getLinkViewPtr(), and Gui::LinkView::getSubNames().
Referenced by staticCallback_getSubNames().
GetType()
virtual PyTypeObject* Gui::LinkViewPy::GetType (void) virtual
Reimplemented from Base::BaseClassPy.
getVisibilities()
Py::Object LinkViewPy::getVisibilities (void) const
getter for the Visibilities attribute
References getLinkViewPtr().
Referenced by staticCallback_getVisibilities().
PyInit()
int LinkViewPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::BaseClassPy.
PyMake()
PyObject * LinkViewPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References LinkViewPy().
representation()
std::string LinkViewPy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
reset()
PyObject * LinkViewPy::reset (PyObject * args)
implementer for the reset() method
References getLinkViewPtr().
Referenced by draftguitools.gui_trackers.gridTracker::set(), and staticCallback_reset().
setChildren()
PyObject * LinkViewPy::setChildren (PyObject * args)
implementer for the setChildren() method
References getLinkViewPtr(), App::PropertyListsT< T, ListT, ParentT >::getValue(), Gui::LinkView::setChildren(), App::PropertyBoolList::setPyObject(), and App::PropertyListsT< T, ListT, ParentT >::setPyObject().
Referenced by staticCallback_setChildren().
setCount()
void LinkViewPy::setCount (Py::Int arg)
setter for the Count attribute
References getLinkViewPtr(), and Gui::LinkView::setSize().
Referenced by staticCallback_setCount().
setCustomAttributes()
int LinkViewPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setLink()
PyObject * LinkViewPy::setLink (PyObject * args)
implementer for the setLink() method
References getLinkViewPtr(), App::PropertyListsT< T, ListT, ParentT >::getValue(), Gui::ViewProviderDocumentObjectPy::getViewProviderDocumentObjectPtr(), Gui::LinkView::setLink(), Gui::LinkView::setLinkViewObject(), App::PropertyListsT< T, ListT, ParentT >::setPyObject(), App::DocumentObjectPy::Type, and Gui::ViewProviderDocumentObjectPy::Type.
Referenced by staticCallback_setLink().
setMaterial()
PyObject * LinkViewPy::setMaterial (PyObject * args)
implementer for the setMaterial() method
References getLinkViewPtr(), App::MaterialPy::getMaterialPtr(), and App::MaterialPy::Type.
Referenced by staticCallback_setMaterial().
setOwner()
void LinkViewPy::setOwner (Py::Object arg)
setter for the Owner attribute
References getLinkViewPtr(), Gui::LinkView::setOwner(), and Gui::ViewProviderDocumentObjectPy::Type.
Referenced by staticCallback_setOwner().
setTransform()
PyObject * LinkViewPy::setTransform (PyObject * args)
implementer for the setTransform() method
References getLinkViewPtr(), Base::MatrixPy::getMatrixPtr(), and Base::MatrixPy::Type.
Referenced by staticCallback_setTransform().
setType()
PyObject * LinkViewPy::setType (PyObject * args)
implementer for the setType() method
References getLinkViewPtr(), and Gui::LinkView::setNodeType().
Referenced by staticCallback_setType().
setVisibilities()
void LinkViewPy::setVisibilities (Py::Object arg)
setter for the Visibilities attribute
References getLinkViewPtr(), and App::PropertyBoolList::setPyObject().
Referenced by staticCallback_setVisibilities().
staticCallback_getBoundBox()
PyObject * LinkViewPy::staticCallback_getBoundBox (PyObject * self, PyObject * args) static
callback for the getBoundBox() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getBoundBox(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getChildren()
PyObject * LinkViewPy::staticCallback_getChildren (PyObject * self, PyObject * args) static
callback for the getChildren() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getChildren(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCount()
PyObject * LinkViewPy::staticCallback_getCount (PyObject * self, void * closure) static
getter callback for the Count attribute
References Base::BaseExceptionFreeCADError, getCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getDetailPath()
PyObject * LinkViewPy::staticCallback_getDetailPath (PyObject * self, PyObject * args) static
callback for the getDetailPath() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getDetailPath(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getElementPicked()
PyObject * LinkViewPy::staticCallback_getElementPicked (PyObject * self, PyObject * args) static
callback for the getElementPicked() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getElementPicked(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getLinkedView()
PyObject * LinkViewPy::staticCallback_getLinkedView (PyObject * self, void * closure) static
getter callback for the LinkedView attribute
References Base::BaseExceptionFreeCADError, getLinkedView(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getOwner()
PyObject * LinkViewPy::staticCallback_getOwner (PyObject * self, void * closure) static
getter callback for the Owner attribute
References Base::BaseExceptionFreeCADError, getOwner(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRootNode()
PyObject * LinkViewPy::staticCallback_getRootNode (PyObject * self, void * closure) static
getter callback for the RootNode attribute
References Base::BaseExceptionFreeCADError, getRootNode(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSubNames()
PyObject * LinkViewPy::staticCallback_getSubNames (PyObject * self, void * closure) static
getter callback for the SubNames attribute
References Base::BaseExceptionFreeCADError, getSubNames(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVisibilities()
PyObject * LinkViewPy::staticCallback_getVisibilities (PyObject * self, void * closure) static
getter callback for the Visibilities attribute
References Base::BaseExceptionFreeCADError, getVisibilities(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_reset()
PyObject * LinkViewPy::staticCallback_reset (PyObject * self, PyObject * args) static
callback for the reset() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), reset(), and Base::PyObjectBase::startNotify().
staticCallback_setChildren()
PyObject * LinkViewPy::staticCallback_setChildren (PyObject * self, PyObject * args) static
callback for the setChildren() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setChildren(), and Base::PyObjectBase::startNotify().
staticCallback_setCount()
int LinkViewPy::staticCallback_setCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the Count attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setCount().
staticCallback_setLink()
PyObject * LinkViewPy::staticCallback_setLink (PyObject * self, PyObject * args) static
callback for the setLink() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setLink(), and Base::PyObjectBase::startNotify().
staticCallback_setLinkedView()
int LinkViewPy::staticCallback_setLinkedView (PyObject * self, PyObject * value, void * closure) static
setter callback for the LinkedView attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setMaterial()
PyObject * LinkViewPy::staticCallback_setMaterial (PyObject * self, PyObject * args) static
callback for the setMaterial() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setMaterial(), and Base::PyObjectBase::startNotify().
staticCallback_setOwner()
int LinkViewPy::staticCallback_setOwner (PyObject * self, PyObject * value, void * closure) static
setter callback for the Owner attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setOwner().
staticCallback_setRootNode()
int LinkViewPy::staticCallback_setRootNode (PyObject * self, PyObject * value, void * closure) static
setter callback for the RootNode attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setSubNames()
int LinkViewPy::staticCallback_setSubNames (PyObject * self, PyObject * value, void * closure) static
setter callback for the SubNames attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setTransform()
PyObject * LinkViewPy::staticCallback_setTransform (PyObject * self, PyObject * args) static
callback for the setTransform() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setTransform(), and Base::PyObjectBase::startNotify().
staticCallback_setType()
PyObject * LinkViewPy::staticCallback_setType (PyObject * self, PyObject * args) static
callback for the setType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setType(), and Base::PyObjectBase::startNotify().
staticCallback_setVisibilities()
int LinkViewPy::staticCallback_setVisibilities (PyObject * self, PyObject * value, void * closure) static
setter callback for the Visibilities attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setVisibilities().
Member Data Documentation
GetterSetter
PyGetSetDef LinkViewPy::GetterSetter static
Attribute structure of LinkViewPy.
Methods
PyMethodDef LinkViewPy::Methods static
Methods structure of LinkViewPy.
Type
PyTypeObject LinkViewPy::Type static
Type structure of LinkViewPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), Gui::Application::Application(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Gui/LinkViewPy.h
Sources/FreeCAD/src/Gui/LinkViewPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Gui/LinkViewPy.cpp