FreeCAD: SMESH_ProxyMesh::SubMesh Class Reference
SMESH_ProxyMesh::SubMesh Class Reference
Proxy sub-mesh.
#include <SMESH_ProxyMesh.hxx>
Public Member Functions
virtual void AddElement (const SMDS_MeshElement *e)
Store an element.
template<class ITERATOR >
void ChangeElements (ITERATOR it, ITERATOR end)
virtual void Clear ()
Deletes temporary elements.
virtual bool Contains (const SMDS_MeshElement *ME) const
Check presence of element inside it-self.
virtual SMDS_ElemIteratorPtr GetElements () const
Return elements of a proxy sub-mesh. The method is meaningful for a sub-mesh containing tmp faces.
const TN2NMap * GetNodeNodeMap () const
virtual SMDS_NodeIteratorPtr GetNodes () const
Return nodes of a proxy sub-mesh. The method is meaningful for a sub-mesh containing nodes of 2D viscous layer.
const SMDS_MeshNode * GetProxyNode (const SMDS_MeshNode *n) const
Return a proxy node or an input node.
const UVPtStructVec & GetUVPtStructVec () const
virtual int NbElements () const
Return number of elements in a proxy sub-mesh. The method is meaningful for a sub-mesh containing tmp faces.
virtual int NbNodes () const
Return number of nodes in a proxy sub-mesh. The method is meaningful for a sub-mesh containing nodes of 2D viscous layer.
SubMesh (int index=0)
virtual ~SubMesh ()
Public Member Functions inherited from SMESHDS_SubMesh
virtual void AddNode (const SMDS_MeshNode *ME)
void AddSubMesh (const SMESHDS_SubMesh *theSubMesh)
void compactList ()
bool ContainsSubMesh (const SMESHDS_SubMesh *theSubMesh) const
virtual const SMDS_MeshElement * GetElement (size_t idInShape) const
int GetID () const
virtual const SMDS_MeshNode * GetNode (size_t idInShape) const
SMESHDS_Mesh * GetParent () const
int getSize ()
SMESHDS_SubMeshIteratorPtr GetSubMeshIterator () const
virtual bool IsComplexSubmesh () const
virtual bool IsQuadratic () const
int NbSubMeshes () const
void RemoveAllSubmeshes ()
virtual bool RemoveElement (const SMDS_MeshElement *ME, bool isElemDeleted)
virtual bool RemoveNode (const SMDS_MeshNode *ME, bool isNodeDeleted)
bool RemoveSubMesh (const SMESHDS_SubMesh *theSubMesh)
SMESHDS_SubMesh (SMESHDS_Mesh *parent, int index)
Constructor.
virtual ~SMESHDS_SubMesh ()
Destructor.
Friends
class SMESH_ProxyMesh
Detailed Description
Proxy sub-mesh.
Constructor & Destructor Documentation
SubMesh()
SMESH_ProxyMesh::SubMesh::SubMesh (int index = 0)
~SubMesh()
virtual SMESH_ProxyMesh::SubMesh::~SubMesh () virtual
References SMESHDS_SubMesh::Clear().
Member Function Documentation
AddElement()
void SMESH_ProxyMesh::SubMesh::AddElement (const SMDS_MeshElement * e) virtual
Store an element.
Reimplemented from SMESHDS_SubMesh.
Referenced by StdMeshers_QuadToTriaAdaptor::Compute().
ChangeElements()
template<class ITERATOR > void SMESH_ProxyMesh::SubMesh::ChangeElements (ITERATOR it, ITERATOR end)
Referenced by StdMeshers_QuadToTriaAdaptor::Compute().
Clear()
void SMESH_ProxyMesh::SubMesh::Clear () virtual
Deletes temporary elements.
Reimplemented from SMESHDS_SubMesh.
Contains()
bool SMESH_ProxyMesh::SubMesh::Contains (const SMDS_MeshElement * ME) const virtual
Check presence of element inside it-self.
Reimplemented from SMESHDS_SubMesh.
References DraftVecUtils::find(), and SMDS_MeshElement::GetType().
GetElements()
SMDS_ElemIteratorPtr SMESH_ProxyMesh::SubMesh::GetElements () const virtual
Return elements of a proxy sub-mesh. The method is meaningful for a sub-mesh containing tmp faces.
Reimplemented from SMESHDS_SubMesh.
Referenced by VISCOUS_3D::_ViscousBuilder::MakeN2NMap().
GetNodeNodeMap()
const TN2NMap* SMESH_ProxyMesh::SubMesh::GetNodeNodeMap () const
GetNodes()
SMDS_NodeIteratorPtr SMESH_ProxyMesh::SubMesh::GetNodes () const virtual
Return nodes of a proxy sub-mesh. The method is meaningful for a sub-mesh containing nodes of 2D viscous layer.
Reimplemented from SMESHDS_SubMesh.
GetProxyNode()
const SMDS_MeshNode * SMESH_ProxyMesh::SubMesh::GetProxyNode (const SMDS_MeshNode * n) const
Return a proxy node or an input node.
GetUVPtStructVec()
const UVPtStructVec& SMESH_ProxyMesh::SubMesh::GetUVPtStructVec () const
Referenced by StdMeshers_FaceSide::GetOrderedNodes().
NbElements()
int SMESH_ProxyMesh::SubMesh::NbElements () const virtual
Return number of elements in a proxy sub-mesh. The method is meaningful for a sub-mesh containing tmp faces.
Reimplemented from SMESHDS_SubMesh.
Referenced by VISCOUS_3D::_ViscousBuilder::MakeN2NMap().
NbNodes()
int SMESH_ProxyMesh::SubMesh::NbNodes () const virtual
Return number of nodes in a proxy sub-mesh. The method is meaningful for a sub-mesh containing nodes of 2D viscous layer.
Reimplemented from SMESHDS_SubMesh.
Reimplemented in VISCOUS_2D::_ProxyMeshOfFace::_EdgeSubMesh.
Friends And Related Function Documentation
SMESH_ProxyMesh
friend class SMESH_ProxyMesh friend
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ProxyMesh.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/SMESH_ProxyMesh.cpp