FreeCAD: MeshGui::DlgSettingsImportExport Class Reference
MeshGui::DlgSettingsImportExport Class Reference
The DlgSettingsImportExportImp class implements a preference page to change settings for Importing and Exporting mesh objects.
#include <DlgSettingsImportExportImp.h>
Public Member Functions
DlgSettingsImportExport (QWidget *parent=nullptr)
~DlgSettingsImportExport ()
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void loadSettings ()
void saveSettings ()
virtual void changeEvent (QEvent *e)=0
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Detailed Description
The DlgSettingsImportExportImp class implements a preference page to change settings for Importing and Exporting mesh objects.
Constructor & Destructor Documentation
DlgSettingsImportExport()
DlgSettingsImportExport::DlgSettingsImportExport (QWidget * parent = nullptr)
References MeshGui::Ui_DlgSettingsImportExport::exportAmfCompressed, and MeshGui::Ui_DlgSettingsImportExport::setupUi().
~DlgSettingsImportExport()
DlgSettingsImportExport::~DlgSettingsImportExport ()
Member Function Documentation
changeEvent()
void DlgSettingsImportExport::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
References MeshGui::Ui_DlgSettingsImportExport::retranslateUi().
loadSettings()
void DlgSettingsImportExport::loadSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References MeshGui::Ui_DlgSettingsImportExport::asymptoteHeight, MeshGui::Ui_DlgSettingsImportExport::asymptoteWidth, MeshGui::Ui_DlgSettingsImportExport::exportAmfCompressed, App::GetApplication(), ParameterGrp::GetASCII(), App::Application::GetParameterGroupByPath(), Base::Quantity::getValue(), MeshGui::Ui_DlgSettingsImportExport::maxDeviationExport, Gui::PrefWidget::onRestore(), Gui::QuantitySpinBox::setValue(), and Gui::QuantitySpinBox::value.
saveSettings()
void DlgSettingsImportExport::saveSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References MeshGui::Ui_DlgSettingsImportExport::asymptoteHeight, MeshGui::Ui_DlgSettingsImportExport::asymptoteWidth, MeshGui::Ui_DlgSettingsImportExport::exportAmfCompressed, App::GetApplication(), App::Application::GetParameterGroupByPath(), Base::Quantity::getValue(), MeshGui::Ui_DlgSettingsImportExport::maxDeviationExport, Gui::PrefWidget::onSave(), ParameterGrp::SetASCII(), MeshCore::MeshOutput::SetAsymptoteSize(), and Gui::QuantitySpinBox::value.
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/Gui/DlgSettingsImportExportImp.h
FreeCAD/src/Mod/Mesh/Gui/DlgSettingsImportExportImp.cpp