FreeCAD: MED::TGaussInfo Struct Reference
MED::TGaussInfo Struct Reference
The class represents MED Gauss entity.
#include <MED_Structures.hxx>
Classes
struct TLess
Public Types
typedef boost::tuple< TKey, TInt > TInfo
typedef boost::tuple< EGeometrieElement, std::string > TKey
Public Member Functions
TInt GetDim () const
Gives dimension of the referenced nodes.
TCoordSlice GetGaussCoordSlice (TInt theId)
Gives coordinates for the Gauss points by its number.
TCCoordSlice GetGaussCoordSlice (TInt theId) const
Gives coordinates for the Gauss points by its number.
EGeometrieElement GetGeom () const
Let known what MED geometrical type the MED GAUSS entity belong to.
TInt GetNbGauss () const
Gives number of the Gauss Points.
TInt GetNbRef () const
Gives number of the referenced nodes.
TCoordSlice GetRefCoordSlice (TInt theId)
Gives coordinates for the referenced node by its number.
TCCoordSlice GetRefCoordSlice (TInt theId) const
Gives coordinates for the referenced node by its number.
Public Member Functions inherited from MED::TNameInfo
virtual std::string GetName () const =0
Gets its name.
virtual void SetName (const std::string &theValue)=0
Set a new name.
virtual void SetName (const TString &theValue)=0
Set a new name.
Public Member Functions inherited from MED::TBase
virtual ~TBase ()
Public Member Functions inherited from MED::TModeSwitchInfo
EModeSwitch GetModeSwitch () const
TModeSwitchInfo ()
To construct instance of the class by default.
TModeSwitchInfo (EModeSwitch theModeSwitch)
To construct instance of the class.
Public Attributes
TNodeCoord myGaussCoord
Contains coordinates for the Gauss points.
EGeometrieElement myGeom
Defines, which geometrical type the MED Gauss entity belongs to.
TNodeCoord myRefCoord
Contains coordinates for the refereced nodes.
TWeight myWeight
Contains wheights for the Gauss points.
Public Attributes inherited from MED::TNameInfo
TString myName
Keeps its name.
Public Attributes inherited from MED::TModeSwitchInfo
EModeSwitch myModeSwitch
Keeps the.
Detailed Description
The class represents MED Gauss entity.
Member Typedef Documentation
TInfo
typedef boost::tuple<TKey,TInt> MED::TGaussInfo::TInfo
TKey
typedef boost::tuple<EGeometrieElement,std::string> MED::TGaussInfo::TKey
Member Function Documentation
GetDim()
TInt MED::TGaussInfo::GetDim () const
Gives dimension of the referenced nodes.
References MED::GetDimGaussCoord().
Referenced by GetGaussCoordSlice(), GetRefCoordSlice(), and MED::TTGaussInfo< eVersion >::TTGaussInfo().
GetGaussCoordSlice() [1/2]
TCoordSlice TGaussInfo::GetGaussCoordSlice (TInt theId)
Gives coordinates for the Gauss points by its number.
References MED::eFULL_INTERLACE, GetDim(), MED::TModeSwitchInfo::GetModeSwitch(), GetNbGauss(), and myGaussCoord.
GetGaussCoordSlice() [2/2]
TCCoordSlice TGaussInfo::GetGaussCoordSlice (TInt theId) const
Gives coordinates for the Gauss points by its number.
References MED::eFULL_INTERLACE, GetDim(), MED::TModeSwitchInfo::GetModeSwitch(), and myGaussCoord.
Referenced by MED::GetGaussCoord3D().
GetGeom()
EGeometrieElement MED::TGaussInfo::GetGeom () const
Let known what MED geometrical type the MED GAUSS entity belong to.
GetNbGauss()
TInt MED::TGaussInfo::GetNbGauss () const
Gives number of the Gauss Points.
Referenced by MED::GetGaussCoord3D(), and GetGaussCoordSlice().
GetNbRef()
TInt MED::TGaussInfo::GetNbRef () const
Gives number of the referenced nodes.
References MED::GetNbRefCoord().
Referenced by MED::GetGaussCoord3D(), and MED::TTGaussInfo< eVersion >::TTGaussInfo().
GetRefCoordSlice() [1/2]
TCoordSlice TGaussInfo::GetRefCoordSlice (TInt theId)
Gives coordinates for the referenced node by its number.
References MED::eFULL_INTERLACE, GetDim(), MED::TModeSwitchInfo::GetModeSwitch(), and myRefCoord.
GetRefCoordSlice() [2/2]
TCCoordSlice TGaussInfo::GetRefCoordSlice (TInt theId) const
Gives coordinates for the referenced node by its number.
References MED::eFULL_INTERLACE, GetDim(), MED::TModeSwitchInfo::GetModeSwitch(), and myRefCoord.
Referenced by MED::GetGaussCoord3D().
Member Data Documentation
myGaussCoord
TNodeCoord MED::TGaussInfo::myGaussCoord
Contains coordinates for the Gauss points.
Referenced by GetGaussCoordSlice(), MED::V2_2::TVWrapper::GetGaussInfo(), MED::TGaussInfo::TLess::operator()(), and MED::TTGaussInfo< eVersion >::TTGaussInfo().
myGeom
EGeometrieElement MED::TGaussInfo::myGeom
Defines, which geometrical type the MED Gauss entity belongs to.
Referenced by MED::GetGaussCoord3D(), MED::TGaussInfo::TLess::operator()(), and MED::TTGaussInfo< eVersion >::TTGaussInfo().
myRefCoord
TNodeCoord MED::TGaussInfo::myRefCoord
Contains coordinates for the refereced nodes.
Referenced by MED::V2_2::TVWrapper::GetGaussInfo(), GetRefCoordSlice(), MED::TGaussInfo::TLess::operator()(), and MED::TTGaussInfo< eVersion >::TTGaussInfo().
myWeight
TWeight MED::TGaussInfo::myWeight
Contains wheights for the Gauss points.
Referenced by MED::V2_2::TVWrapper::GetGaussInfo(), and MED::TTGaussInfo< eVersion >::TTGaussInfo().
The documentation for this struct was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/MED_Structures.hxx
FreeCAD/src/3rdParty/salomesmesh/src/SMESH/MED_Structures.cpp