FreeCAD: Gui::LabelButton Class Reference
Gui::LabelButton Class Reference
The LabelButton class provides a label with a button on the right side.
#include <Widgets.h>
Public Slots
void setValue (const QVariant &)
Signals
void buttonClicked ()
void valueChanged (const QVariant &)
Public Member Functions
QPushButton * getButton () const
QLabel * getLabel () const
LabelButton (QWidget *parent=0)
Constructs a file chooser called name with the parent parent.
QVariant value () const
virtual ~LabelButton ()
Protected Slots
virtual void browse ()
Protected Member Functions
void resizeEvent (QResizeEvent *)
virtual void showValue (const QVariant &data)
Properties
QVariant value
Detailed Description
The LabelButton class provides a label with a button on the right side.
Author
Werner Mayer
Constructor & Destructor Documentation
LabelButton()
LabelButton::LabelButton (QWidget * parent = 0)
Constructs a file chooser called name with the parent parent.
References browse(), buttonClicked(), and draftgeoutils.intersections::connect().
~LabelButton()
LabelButton::~LabelButton () virtual
Member Function Documentation
browse
void LabelButton::browse () protected virtual slot
Referenced by LabelButton().
buttonClicked
void Gui::LabelButton::buttonClicked () signal
Referenced by LabelButton().
getButton()
QPushButton * LabelButton::getButton () const
getLabel()
QLabel * LabelButton::getLabel () const
resizeEvent()
void LabelButton::resizeEvent (QResizeEvent * e) protected
setValue
void LabelButton::setValue (const QVariant & val) slot
References showValue(), and valueChanged().
Referenced by PartGui::PropertyEnumAttacherItem::setEditorData().
showValue()
void LabelButton::showValue (const QVariant & data) protected virtual
Referenced by setValue().
value()
QVariant LabelButton::value () const
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), and Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue().
valueChanged
void Gui::LabelButton::valueChanged (const QVariant &) signal
Referenced by setValue().
Property Documentation
value
QVariant Gui::LabelButton::value read write
Referenced by PathScripts.PathSetupSheetOpPrototype.Property::displayString(), PathScripts.PathSetupSheetOpPrototype.PropertyQuantity::displayString(), PartGui::PropertyEnumAttacherItem::editorData(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), PathScripts.PathSetupSheetOpPrototype.Property::getValue(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), and PathScripts.PathSetupSheetOpPrototype.Property::setValue().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Widgets.h
Sources/FreeCAD/src/Gui/Widgets.cpp