FreeCAD: App::Expression::Component Struct Reference
App::Expression::Component Struct Reference
#include <ExpressionParser.h>
Public Member Functions
Component (const Component &other)
Component (const ObjectIdentifier::Component &comp)
Component (const std::string &n)
Component (Expression *e1, Expression *e2, Expression *e3, bool isRange=false)
Component * copy () const
void del (const Expression *owner, Py::Object &pyobj) const
Component * eval () const
Py::Object get (const Expression *owner, const Py::Object &pyobj) const
bool isTouched () const
Component & operator= (const Component &)=delete
void set (const Expression *owner, Py::Object &pyobj, const Py::Object &value) const
void toString (std::ostream &ss, bool persistent) const
void visit (ExpressionVisitor &v)
~Component ()
Public Attributes
ObjectIdentifier::Component comp
Expression * e1
Expression * e2
Expression * e3
Constructor & Destructor Documentation
Component() [1/4]
Expression::Component::Component (const std::string & n)
Component() [2/4]
Expression::Component::Component (Expression * e1, Expression * e2, Expression * e3, bool isRange = false)
References comp, e2, e3, and App::ObjectIdentifier::RangeComponent().
Component() [3/4]
Expression::Component::Component (const ObjectIdentifier::Component & comp)
Component() [4/4]
Expression::Component::Component (const Component & other)
~Component()
Expression::Component::~Component ()
Member Function Documentation
copy()
Expression::Component * Expression::Component::copy () const
del()
void Expression::Component::del (const Expression * owner, Py::Object & pyobj) const
References App::Expression::owner, and draftgeoutils.general::v1().
eval()
Expression::Component * Expression::Component::eval () const
get()
Py::Object Expression::Component::get (const Expression * owner, const Py::Object & pyobj) const
References App::Expression::owner, and draftgeoutils.general::v1().
Referenced by draftguitools.gui_trackers.editTracker::move().
isTouched()
bool Expression::Component::isTouched (void) const
operator=()
Component& App::Expression::Component::operator= (const Component &) delete
set()
void Expression::Component::set (const Expression * owner, Py::Object & pyobj, const Py::Object & value) const
References App::Expression::owner, and draftgeoutils.general::v1().
Referenced by draftguitools.gui_trackers.editTracker::move().
toString()
void Expression::Component::toString (std::ostream & ss, bool persistent) const
visit()
void Expression::Component::visit (ExpressionVisitor & v)
Member Data Documentation
comp
ObjectIdentifier::Component App::Expression::Component::comp
Referenced by Component().
e1
Expression* App::Expression::Component::e1
e2
Expression* App::Expression::Component::e2
Referenced by Component().
e3
Expression* App::Expression::Component::e3
Referenced by Component().
The documentation for this struct was generated from the following files:
Sources/FreeCAD/src/App/ExpressionParser.h
Sources/FreeCAD/src/App/Expression.cpp