FreeCAD: Fem::FemVTKTools Class Reference
Fem::FemVTKTools Class Reference
#include <FemVTKTools.h>
Static Public Member Functions
static void exportFreeCADResult (const App::DocumentObject *result, vtkSmartPointer< vtkDataSet > grid)
static void exportVTKMesh (const FemMesh *mesh, vtkSmartPointer< vtkUnstructuredGrid > grid, float scale=1.0)
static void importFreeCADResult (vtkSmartPointer< vtkDataSet > dataset, App::DocumentObject *result)
static void importVTKMesh (vtkSmartPointer< vtkDataSet > grid, FemMesh *mesh, float scale=1.0)
static App::DocumentObject * readResult (const char *Filename, App::DocumentObject *res=NULL)
static FemMesh * readVTKMesh (const char *filename, FemMesh *mesh)
static void writeResult (const char *filename, const App::DocumentObject *res=NULL)
static void writeVTKMesh (const char *Filename, const FemMesh *mesh)
Member Function Documentation
exportFreeCADResult()
void Fem::FemVTKTools::exportFreeCADResult (const App::DocumentObject * result, vtkSmartPointer< vtkDataSet > grid) static
References Base::Console(), Base::ConsoleSingleton::Error(), Base::Persistence::getClassTypeId(), SMDS_MeshElement::GetID(), SMESH_Mesh::GetMeshDS(), App::PropertyListsT< T, ListT, ParentT >::getSize(), Fem::FemMesh::getSMesh(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Base::BaseClass::isDerivedFrom(), Base::ConsoleSingleton::Log(), SMDS_Mesh::nodesIterator(), and draftgeoutils.general::vec().
Referenced by Fem::FemPostPipeline::load(), and writeResult().
exportVTKMesh()
void Fem::FemVTKTools::exportVTKMesh (const FemMesh * mesh, vtkSmartPointer< vtkUnstructuredGrid > grid, float scale = 1.0) static
References Base::Console(), Fem::exportFemMeshCells(), Fem::exportFemMeshFaces(), SMDS_Mesh::facesIterator(), SMDS_MeshElement::GetID(), SMESH_Mesh::GetMeshDS(), SMDS_Mesh::GetMeshInfo(), Base::ConsoleSingleton::Log(), SMDS_Mesh::nodesIterator(), SMDS_Mesh::volumesIterator(), SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
Referenced by Fem::FemPostPipeline::load(), writeResult(), and writeVTKMesh().
importFreeCADResult()
void Fem::FemVTKTools::importFreeCADResult (vtkSmartPointer< vtkDataSet > dataset, App::DocumentObject * result) static
References Base::Console(), Base::ConsoleSingleton::Error(), Base::ConsoleSingleton::Log(), Base::ConsoleSingleton::Message(), App::PropertyListsT< T, ListT, ParentT >::setValues(), and draftgeoutils.general::vec().
Referenced by readResult().
importVTKMesh()
void Fem::FemVTKTools::importVTKMesh (vtkSmartPointer< vtkDataSet > grid, FemMesh * mesh, float scale = 1.0) static
References SMESHDS_Mesh::AddFaceWithID(), SMESHDS_Mesh::AddNodeWithID(), SMESHDS_Mesh::AddVolumeWithID(), SMESHDS_Mesh::ClearMesh(), Base::Console(), Base::ConsoleSingleton::Error(), SMESH_Mesh::GetMeshDS(), and Base::ConsoleSingleton::Log().
Referenced by readResult(), and readVTKMesh().
readResult()
App::DocumentObject * Fem::FemVTKTools::readResult (const char * Filename, App::DocumentObject * res = NULL) static
References App::Document::addObject(), Base::Console(), Base::TimeInfo::diffTimeF(), Base::ConsoleSingleton::Error(), Base::Type::fromName(), App::Application::getActiveDocument(), App::Document::getActiveObject(), App::GetApplication(), importFreeCADResult(), importVTKMesh(), Base::ConsoleSingleton::Log(), Base::ConsoleSingleton::Message(), App::Application::newDocument(), App::Document::recompute(), and App::PropertyLink::setValue().
readVTKMesh()
FemMesh * Fem::FemVTKTools::readVTKMesh (const char * filename, FemMesh * mesh) static
References Base::Console(), Base::TimeInfo::diffTimeF(), Base::ConsoleSingleton::Error(), importVTKMesh(), and Base::ConsoleSingleton::Log().
Referenced by Fem::FemMesh::read().
writeResult()
void Fem::FemVTKTools::writeResult (const char * filename, const App::DocumentObject * res = NULL) static
References Base::Console(), Base::TimeInfo::diffTimeF(), Base::ConsoleSingleton::Error(), exportFreeCADResult(), exportVTKMesh(), App::Application::getActiveDocument(), App::Document::getActiveObject(), App::GetApplication(), Base::ConsoleSingleton::Log(), and Base::ConsoleSingleton::Message().
writeVTKMesh()
void Fem::FemVTKTools::writeVTKMesh (const char * Filename, const FemMesh * mesh) static
References Base::Console(), Base::TimeInfo::diffTimeF(), Base::ConsoleSingleton::Error(), exportVTKMesh(), and Base::ConsoleSingleton::Log().
Referenced by Fem::FemMesh::write().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Fem/App/FemVTKTools.h
Sources/FreeCAD/src/Mod/Fem/App/FemVTKTools.cpp