FreeCAD: PartGui::TaskMeasureLinear Class Reference
PartGui::TaskMeasureLinear Class Reference
#include <TaskDimension.h>
Public Member Functions
virtual QDialogButtonBox::StandardButtons getStandardButtons () const
tells the framework which buttons are wished for the dialog
virtual bool isAllowedAlterDocument (void) const
virtual bool needsFullSpace () const
TaskMeasureLinear ()
~TaskMeasureLinear ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
tells the framework which buttons are wished for the dialog
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Static Public Member Functions
static void buildDimension (const DimSelections &sel1, const DimSelections &sel2)
Protected Slots
void clearAllSlot (bool)
void resetDialogSlot (bool)
void selection1Slot (bool checked)
void selection2Slot (bool checked)
void selectionClearDelayedSlot ()
void toggle3dSlot (bool)
void toggleDeltaSlot (bool)
Protected Member Functions
virtual void onSelectionChanged (const Gui::SelectionChanges &msg)
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
linear dialog
Constructor & Destructor Documentation
TaskMeasureLinear()
PartGui::TaskMeasureLinear::TaskMeasureLinear ()
~TaskMeasureLinear()
PartGui::TaskMeasureLinear::~TaskMeasureLinear ()
References Gui::SelectionSingleton::clearSelection(), and Gui::Selection().
Member Function Documentation
buildDimension()
void PartGui::TaskMeasureLinear::buildDimension (const DimSelections & sel1, const DimSelections & sel2) static
References buildDimension(), Base::Console(), PartGui::DimSelections::DimSelection::documentName, App::Application::getActiveDocument(), App::GetApplication(), PartGui::getShapeFromStrings(), PartGui::goDimensionLinearNoTask(), Base::ConsoleSingleton::Message(), PartGui::DimSelections::DimSelection::objectName, PartGui::DimSelections::selections, and PartGui::DimSelections::DimSelection::subObjectName.
Referenced by buildDimension().
clearAllSlot
void PartGui::TaskMeasureLinear::clearAllSlot (bool) protected slot
References PartGui::eraseAllDimensions().
getStandardButtons()
virtual QDialogButtonBox::StandardButtons PartGui::TaskMeasureLinear::getStandardButtons (void) const virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
isAllowedAlterDocument()
virtual bool PartGui::TaskMeasureLinear::isAllowedAlterDocument (void) const virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
needsFullSpace()
virtual bool PartGui::TaskMeasureLinear::needsFullSpace () const virtual
Reimplemented from Gui::TaskView::TaskDialog.
onSelectionChanged()
void PartGui::TaskMeasureLinear::onSelectionChanged (const Gui::SelectionChanges & msg) protected virtual
Implements Gui::SelectionObserver.
References Gui::SelectionChanges::AddSelection, PartGui::DimSelections::DimSelection::documentName, PartGui::DimSelections::DimSelection::objectName, PartGui::DimSelections::DimSelection::shapeType, PartGui::DimSelections::DimSelection::subObjectName, PartGui::DimSelections::DimSelection::x, PartGui::DimSelections::DimSelection::y, and PartGui::DimSelections::DimSelection::z.
resetDialogSlot
void PartGui::TaskMeasureLinear::resetDialogSlot (bool) protected slot
References Gui::SelectionSingleton::clearSelection(), and Gui::Selection().
selection1Slot
void PartGui::TaskMeasureLinear::selection1Slot (bool checked) protected slot
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), and Gui::Selection().
selection2Slot
void PartGui::TaskMeasureLinear::selection2Slot (bool checked) protected slot
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), and Gui::Selection().
selectionClearDelayedSlot
void PartGui::TaskMeasureLinear::selectionClearDelayedSlot () protected slot
References Gui::SelectionSingleton::clearSelection(), and Gui::Selection().
toggle3dSlot
void PartGui::TaskMeasureLinear::toggle3dSlot (bool) protected slot
References PartGui::toggle3d().
toggleDeltaSlot
void PartGui::TaskMeasureLinear::toggleDeltaSlot (bool) protected slot
References PartGui::toggleDelta().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/TaskDimension.h
FreeCAD/src/Mod/Part/Gui/TaskDimension.cpp