FreeCAD: nlohmann::detail::iteration_proxy< IteratorType > Class Template Reference
nlohmann::detail::iteration_proxy< IteratorType > Class Template Reference
proxy class for the items() function
#include <json.hpp>
Public Member Functions
iteration_proxy_value< IteratorType > begin () noexcept
return iterator begin (needed for range-based for)
iteration_proxy_value< IteratorType > end () noexcept
return iterator end (needed for range-based for)
iteration_proxy (typename IteratorType::reference cont) noexcept
construct iteration proxy from a container
Detailed Description
template<typename IteratorType>
class nlohmann::detail::iteration_proxy< IteratorType >
proxy class for the items() function
Constructor & Destructor Documentation
iteration_proxy()
template<typename IteratorType > nlohmann::detail::iteration_proxy< IteratorType >::iteration_proxy (typename IteratorType::reference cont) explicit noexcept
construct iteration proxy from a container
Member Function Documentation
begin()
template<typename IteratorType > iteration_proxy_value< IteratorType > nlohmann::detail::iteration_proxy< IteratorType >::begin () noexcept
return iterator begin (needed for range-based for)
end()
template<typename IteratorType > iteration_proxy_value< IteratorType > nlohmann::detail::iteration_proxy< IteratorType >::end () noexcept
return iterator end (needed for range-based for)
Referenced by Dice3DS.dom3ds.FileLikeBuffer::advance(), Dice3DS.dom3ds.FileLikeBuffer::read_rest(), Dice3DS.dom3ds.FileLikeBuffer::read_to_nul(), Dice3DS.dom3ds.FileLikeBuffer::room_for_chunks(), and Dice3DS.dom3ds.FileLikeBuffer::seek().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/PartDesign/App/json.hpp