FreeCAD: Base::BoundBoxPy Class Reference
Base::BoundBoxPy Class Reference
The python export class for BoundBox.
#include <BoundBoxPy.h>
Public Types
typedef BoundBox3d * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
BoundBoxPy (BoundBox3d *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of BoundBoxPy.
static PyMethodDef Methods []
Methods structure of BoundBoxPy.
static PyTypeObject Type
Type structure of BoundBoxPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~BoundBoxPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * setVoid (PyObject *args)
implementer for the setVoid() method
PyObject * isValid (PyObject *args)
implementer for the isValid() method
PyObject * add (PyObject *args)
implementer for the add() method
PyObject * getPoint (PyObject *args)
implementer for the getPoint() method
PyObject * getEdge (PyObject *args)
implementer for the getEdge() method
PyObject * closestPoint (PyObject *args)
implementer for the closestPoint() method
PyObject * intersect (PyObject *args)
implementer for the intersect() method
PyObject * intersected (PyObject *args)
implementer for the intersected() method
PyObject * united (PyObject *args)
implementer for the united() method
PyObject * enlarge (PyObject *args)
implementer for the enlarge() method
PyObject * getIntersectionPoint (PyObject *args)
implementer for the getIntersectionPoint() method
PyObject * move (PyObject *args)
implementer for the move() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transformed (PyObject *args)
implementer for the transformed() method
PyObject * isCutPlane (PyObject *args)
implementer for the isCutPlane() method
PyObject * isInside (PyObject *args)
implementer for the isInside() method
static PyObject * staticCallback_setVoid (PyObject *self, PyObject *args)
callback for the setVoid() method
static PyObject * staticCallback_isValid (PyObject *self, PyObject *args)
callback for the isValid() method
static PyObject * staticCallback_add (PyObject *self, PyObject *args)
callback for the add() method
static PyObject * staticCallback_getPoint (PyObject *self, PyObject *args)
callback for the getPoint() method
static PyObject * staticCallback_getEdge (PyObject *self, PyObject *args)
callback for the getEdge() method
static PyObject * staticCallback_closestPoint (PyObject *self, PyObject *args)
callback for the closestPoint() method
static PyObject * staticCallback_intersect (PyObject *self, PyObject *args)
callback for the intersect() method
static PyObject * staticCallback_intersected (PyObject *self, PyObject *args)
callback for the intersected() method
static PyObject * staticCallback_united (PyObject *self, PyObject *args)
callback for the united() method
static PyObject * staticCallback_enlarge (PyObject *self, PyObject *args)
callback for the enlarge() method
static PyObject * staticCallback_getIntersectionPoint (PyObject *self, PyObject *args)
callback for the getIntersectionPoint() method
static PyObject * staticCallback_move (PyObject *self, PyObject *args)
callback for the move() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transformed (PyObject *self, PyObject *args)
callback for the transformed() method
static PyObject * staticCallback_isCutPlane (PyObject *self, PyObject *args)
callback for the isCutPlane() method
static PyObject * staticCallback_isInside (PyObject *self, PyObject *args)
callback for the isInside() method
callbacks and implementers for the python object attributes
Py::Object getCenter (void) const
getter for the Center attribute
Py::Float getXMax (void) const
getter for the XMax attribute
void setXMax (Py::Float arg)
setter for the XMax attribute
Py::Float getYMax (void) const
getter for the YMax attribute
void setYMax (Py::Float arg)
setter for the YMax attribute
Py::Float getZMax (void) const
getter for the ZMax attribute
void setZMax (Py::Float arg)
setter for the ZMax attribute
Py::Float getXMin (void) const
getter for the XMin attribute
void setXMin (Py::Float arg)
setter for the XMin attribute
Py::Float getYMin (void) const
getter for the YMin attribute
void setYMin (Py::Float arg)
setter for the YMin attribute
Py::Float getZMin (void) const
getter for the ZMin attribute
void setZMin (Py::Float arg)
setter for the ZMin attribute
Py::Float getXLength (void) const
getter for the XLength attribute
Py::Float getYLength (void) const
getter for the YLength attribute
Py::Float getZLength (void) const
getter for the ZLength attribute
Py::Float getDiagonalLength (void) const
getter for the DiagonalLength attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BoundBox3d * getBoundBoxPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getCenter (PyObject *self, void *closure)
getter callback for the Center attribute
static int staticCallback_setCenter (PyObject *self, PyObject *value, void *closure)
setter callback for the Center attribute
static PyObject * staticCallback_getXMax (PyObject *self, void *closure)
getter callback for the XMax attribute
static int staticCallback_setXMax (PyObject *self, PyObject *value, void *closure)
setter callback for the XMax attribute
static PyObject * staticCallback_getYMax (PyObject *self, void *closure)
getter callback for the YMax attribute
static int staticCallback_setYMax (PyObject *self, PyObject *value, void *closure)
setter callback for the YMax attribute
static PyObject * staticCallback_getZMax (PyObject *self, void *closure)
getter callback for the ZMax attribute
static int staticCallback_setZMax (PyObject *self, PyObject *value, void *closure)
setter callback for the ZMax attribute
static PyObject * staticCallback_getXMin (PyObject *self, void *closure)
getter callback for the XMin attribute
static int staticCallback_setXMin (PyObject *self, PyObject *value, void *closure)
setter callback for the XMin attribute
static PyObject * staticCallback_getYMin (PyObject *self, void *closure)
getter callback for the YMin attribute
static int staticCallback_setYMin (PyObject *self, PyObject *value, void *closure)
setter callback for the YMin attribute
static PyObject * staticCallback_getZMin (PyObject *self, void *closure)
getter callback for the ZMin attribute
static int staticCallback_setZMin (PyObject *self, PyObject *value, void *closure)
setter callback for the ZMin attribute
static PyObject * staticCallback_getXLength (PyObject *self, void *closure)
getter callback for the XLength attribute
static int staticCallback_setXLength (PyObject *self, PyObject *value, void *closure)
setter callback for the XLength attribute
static PyObject * staticCallback_getYLength (PyObject *self, void *closure)
getter callback for the YLength attribute
static int staticCallback_setYLength (PyObject *self, PyObject *value, void *closure)
setter callback for the YLength attribute
static PyObject * staticCallback_getZLength (PyObject *self, void *closure)
getter callback for the ZLength attribute
static int staticCallback_setZLength (PyObject *self, PyObject *value, void *closure)
setter callback for the ZLength attribute
static PyObject * staticCallback_getDiagonalLength (PyObject *self, void *closure)
getter callback for the DiagonalLength attribute
static int staticCallback_setDiagonalLength (PyObject *self, PyObject *value, void *closure)
setter callback for the DiagonalLength attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for BoundBox.
Member Typedef Documentation
PointerType
typedef BoundBox3d* Base::BoundBoxPy::PointerType
Constructor & Destructor Documentation
~BoundBoxPy()
BoundBoxPy::~BoundBoxPy () protected
BoundBoxPy()
BoundBoxPy::BoundBoxPy (BoundBox3d * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
add()
PyObject * BoundBoxPy::add (PyObject * args)
implementer for the add() method
References Base::BoundBox3< _Precision >::Add(), getBoundBoxPtr(), Type, and Base::VectorPy::Type.
Referenced by staticCallback_add().
closestPoint()
PyObject * BoundBoxPy::closestPoint (PyObject * args)
implementer for the closestPoint() method
References Base::BoundBox3< _Precision >::ClosestPoint(), getBoundBoxPtr(), Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_closestPoint().
enlarge()
PyObject * BoundBoxPy::enlarge (PyObject * args)
implementer for the enlarge() method
References Base::BoundBox3< _Precision >::Enlarge(), and getBoundBoxPtr().
Referenced by staticCallback_enlarge().
getBoundBoxPtr()
BoundBox3d * BoundBoxPy::getBoundBoxPtr (void) const
getter for the object handled by this class
Referenced by add(), closestPoint(), enlarge(), getCenter(), getDiagonalLength(), getEdge(), getIntersectionPoint(), getPoint(), getXLength(), getXMax(), getXMin(), getYLength(), getYMax(), getYMin(), getZLength(), getZMax(), getZMin(), intersect(), intersected(), isCutPlane(), isInside(), isValid(), move(), PyInit(), representation(), scale(), setVoid(), setXMax(), setXMin(), setYMax(), setYMin(), setZMax(), setZMin(), transformed(), and united().
getCenter()
Py::Object BoundBoxPy::getCenter (void) const
getter for the Center attribute
References getBoundBoxPtr().
Referenced by staticCallback_getCenter().
getCustomAttributes()
PyObject * BoundBoxPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getDiagonalLength()
Py::Float BoundBoxPy::getDiagonalLength (void) const
getter for the DiagonalLength attribute
References getBoundBoxPtr().
Referenced by staticCallback_getDiagonalLength().
getEdge()
PyObject * BoundBoxPy::getEdge (PyObject * args)
implementer for the getEdge() method
References Base::BoundBox3< _Precision >::CalcEdge(), and getBoundBoxPtr().
Referenced by staticCallback_getEdge().
getIntersectionPoint()
PyObject * BoundBoxPy::getIntersectionPoint (PyObject * args)
implementer for the getIntersectionPoint() method
References Base::BaseExceptionFreeCADError, draftutils.utils::epsilon(), getBoundBoxPtr(), Base::BoundBox3< _Precision >::IntersectionPoint(), and Base::VectorPy::Type.
Referenced by staticCallback_getIntersectionPoint().
getPoint()
PyObject * BoundBoxPy::getPoint (PyObject * args)
implementer for the getPoint() method
References Base::BoundBox3< _Precision >::CalcPoint(), and getBoundBoxPtr().
Referenced by draftguitools.gui_arcs.Arc_3Points::getPoint(), ArchCurtainWall.CommandArchCurtainWall::getPoint(), ArchTruss.CommandArchTruss::getPoint(), and staticCallback_getPoint().
GetType()
virtual PyTypeObject* Base::BoundBoxPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
getXLength()
Py::Float BoundBoxPy::getXLength (void) const
getter for the XLength attribute
References getBoundBoxPtr().
Referenced by staticCallback_getXLength().
getXMax()
Py::Float BoundBoxPy::getXMax (void) const
getter for the XMax attribute
References getBoundBoxPtr().
Referenced by staticCallback_getXMax().
getXMin()
Py::Float BoundBoxPy::getXMin (void) const
getter for the XMin attribute
References getBoundBoxPtr().
Referenced by staticCallback_getXMin().
getYLength()
Py::Float BoundBoxPy::getYLength (void) const
getter for the YLength attribute
References getBoundBoxPtr().
Referenced by staticCallback_getYLength().
getYMax()
Py::Float BoundBoxPy::getYMax (void) const
getter for the YMax attribute
References getBoundBoxPtr().
Referenced by staticCallback_getYMax().
getYMin()
Py::Float BoundBoxPy::getYMin (void) const
getter for the YMin attribute
References getBoundBoxPtr().
Referenced by staticCallback_getYMin().
getZLength()
Py::Float BoundBoxPy::getZLength (void) const
getter for the ZLength attribute
References getBoundBoxPtr().
Referenced by staticCallback_getZLength().
getZMax()
Py::Float BoundBoxPy::getZMax (void) const
getter for the ZMax attribute
References getBoundBoxPtr().
Referenced by staticCallback_getZMax().
getZMin()
Py::Float BoundBoxPy::getZMin (void) const
getter for the ZMin attribute
References getBoundBoxPtr().
Referenced by staticCallback_getZMin().
intersect()
PyObject * BoundBoxPy::intersect (PyObject * args)
implementer for the intersect() method
References getBoundBoxPtr(), Base::BoundBox3< _Precision >::Intersect(), Base::BoundBox3< _Precision >::IsCutLine(), Type, and Base::VectorPy::Type.
Referenced by staticCallback_intersect().
intersected()
PyObject * BoundBoxPy::intersected (PyObject * args)
implementer for the intersected() method
References getBoundBoxPtr(), Base::BoundBox3< _Precision >::Intersected(), and Type.
Referenced by staticCallback_intersected().
isCutPlane()
PyObject * BoundBoxPy::isCutPlane (PyObject * args)
implementer for the isCutPlane() method
References getBoundBoxPtr(), Base::BoundBox3< _Precision >::IsCutPlane(), and Base::VectorPy::Type.
Referenced by staticCallback_isCutPlane().
isInside()
PyObject * BoundBoxPy::isInside (PyObject * args)
implementer for the isInside() method
References getBoundBoxPtr(), Base::BoundBox3< _Precision >::IsInBox(), Type, and Base::VectorPy::Type.
Referenced by staticCallback_isInside(), and ArchVRM.Renderer::zOverlaps().
isValid()
PyObject * BoundBoxPy::isValid (PyObject * args)
implementer for the isValid() method
References getBoundBoxPtr().
move()
PyObject * BoundBoxPy::move (PyObject * args)
implementer for the move() method
References getBoundBoxPtr(), Base::BoundBox3< _Precision >::MoveX(), Base::BoundBox3< _Precision >::MoveY(), Base::BoundBox3< _Precision >::MoveZ(), Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by draftguitools.gui_circulararray.CircularArray::Activated(), draftguitools.gui_polararray.PolarArray::Activated(), and staticCallback_move().
PyInit()
int BoundBoxPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
References Base::BoundBox3< _Precision >::Add(), getBoundBoxPtr(), Base::BoundBox3< _Precision >::MaxX, Base::BoundBox3< _Precision >::MaxY, Base::BoundBox3< _Precision >::MaxZ, Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, Base::BoundBox3< _Precision >::MinZ, Type, and Base::VectorPy::Type.
PyMake()
PyObject * BoundBoxPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References BoundBoxPy().
representation()
std::string BoundBoxPy::representation (void) const
References getBoundBoxPtr(), Base::BoundBox3< _Precision >::MaxX, Base::BoundBox3< _Precision >::MaxY, Base::BoundBox3< _Precision >::MaxZ, Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, and Base::BoundBox3< _Precision >::MinZ.
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
scale()
PyObject * BoundBoxPy::scale (PyObject * args)
implementer for the scale() method
References getBoundBoxPtr(), Base::BoundBox3< _Precision >::ScaleX(), Base::BoundBox3< _Precision >::ScaleY(), Base::BoundBox3< _Precision >::ScaleZ(), Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_scale().
setCustomAttributes()
int BoundBoxPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setVoid()
PyObject * BoundBoxPy::setVoid (PyObject * args)
implementer for the setVoid() method
References getBoundBoxPtr(), and Base::BoundBox3< _Precision >::SetVoid().
Referenced by staticCallback_setVoid().
setXMax()
void BoundBoxPy::setXMax (Py::Float arg)
setter for the XMax attribute
References getBoundBoxPtr(), and Base::BoundBox3< _Precision >::MaxX.
Referenced by staticCallback_setXMax().
setXMin()
void BoundBoxPy::setXMin (Py::Float arg)
setter for the XMin attribute
References getBoundBoxPtr(), and Base::BoundBox3< _Precision >::MinX.
Referenced by staticCallback_setXMin().
setYMax()
void BoundBoxPy::setYMax (Py::Float arg)
setter for the YMax attribute
References getBoundBoxPtr(), and Base::BoundBox3< _Precision >::MaxY.
Referenced by staticCallback_setYMax().
setYMin()
void BoundBoxPy::setYMin (Py::Float arg)
setter for the YMin attribute
References getBoundBoxPtr(), and Base::BoundBox3< _Precision >::MinY.
Referenced by staticCallback_setYMin().
setZMax()
void BoundBoxPy::setZMax (Py::Float arg)
setter for the ZMax attribute
References getBoundBoxPtr(), and Base::BoundBox3< _Precision >::MaxZ.
Referenced by staticCallback_setZMax().
setZMin()
void BoundBoxPy::setZMin (Py::Float arg)
setter for the ZMin attribute
References getBoundBoxPtr(), and Base::BoundBox3< _Precision >::MinZ.
Referenced by staticCallback_setZMin().
staticCallback_add()
PyObject * BoundBoxPy::staticCallback_add (PyObject * self, PyObject * args) static
callback for the add() method
References add(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_closestPoint()
PyObject * BoundBoxPy::staticCallback_closestPoint (PyObject * self, PyObject * args) static
callback for the closestPoint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, closestPoint(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_enlarge()
PyObject * BoundBoxPy::staticCallback_enlarge (PyObject * self, PyObject * args) static
callback for the enlarge() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, enlarge(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_getCenter()
PyObject * BoundBoxPy::staticCallback_getCenter (PyObject * self, void * closure) static
getter callback for the Center attribute
References Base::BaseExceptionFreeCADError, getCenter(), and Base::PyObjectBase::isValid().
staticCallback_getDiagonalLength()
PyObject * BoundBoxPy::staticCallback_getDiagonalLength (PyObject * self, void * closure) static
getter callback for the DiagonalLength attribute
References Base::BaseExceptionFreeCADError, getDiagonalLength(), and Base::PyObjectBase::isValid().
staticCallback_getEdge()
PyObject * BoundBoxPy::staticCallback_getEdge (PyObject * self, PyObject * args) static
callback for the getEdge() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getEdge(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_getIntersectionPoint()
PyObject * BoundBoxPy::staticCallback_getIntersectionPoint (PyObject * self, PyObject * args) static
callback for the getIntersectionPoint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getIntersectionPoint(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_getPoint()
PyObject * BoundBoxPy::staticCallback_getPoint (PyObject * self, PyObject * args) static
callback for the getPoint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPoint(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_getXLength()
PyObject * BoundBoxPy::staticCallback_getXLength (PyObject * self, void * closure) static
getter callback for the XLength attribute
References Base::BaseExceptionFreeCADError, getXLength(), and Base::PyObjectBase::isValid().
staticCallback_getXMax()
PyObject * BoundBoxPy::staticCallback_getXMax (PyObject * self, void * closure) static
getter callback for the XMax attribute
References Base::BaseExceptionFreeCADError, getXMax(), and Base::PyObjectBase::isValid().
staticCallback_getXMin()
PyObject * BoundBoxPy::staticCallback_getXMin (PyObject * self, void * closure) static
getter callback for the XMin attribute
References Base::BaseExceptionFreeCADError, getXMin(), and Base::PyObjectBase::isValid().
staticCallback_getYLength()
PyObject * BoundBoxPy::staticCallback_getYLength (PyObject * self, void * closure) static
getter callback for the YLength attribute
References Base::BaseExceptionFreeCADError, getYLength(), and Base::PyObjectBase::isValid().
staticCallback_getYMax()
PyObject * BoundBoxPy::staticCallback_getYMax (PyObject * self, void * closure) static
getter callback for the YMax attribute
References Base::BaseExceptionFreeCADError, getYMax(), and Base::PyObjectBase::isValid().
staticCallback_getYMin()
PyObject * BoundBoxPy::staticCallback_getYMin (PyObject * self, void * closure) static
getter callback for the YMin attribute
References Base::BaseExceptionFreeCADError, getYMin(), and Base::PyObjectBase::isValid().
staticCallback_getZLength()
PyObject * BoundBoxPy::staticCallback_getZLength (PyObject * self, void * closure) static
getter callback for the ZLength attribute
References Base::BaseExceptionFreeCADError, getZLength(), and Base::PyObjectBase::isValid().
staticCallback_getZMax()
PyObject * BoundBoxPy::staticCallback_getZMax (PyObject * self, void * closure) static
getter callback for the ZMax attribute
References Base::BaseExceptionFreeCADError, getZMax(), and Base::PyObjectBase::isValid().
staticCallback_getZMin()
PyObject * BoundBoxPy::staticCallback_getZMin (PyObject * self, void * closure) static
getter callback for the ZMin attribute
References Base::BaseExceptionFreeCADError, getZMin(), and Base::PyObjectBase::isValid().
staticCallback_intersect()
PyObject * BoundBoxPy::staticCallback_intersect (PyObject * self, PyObject * args) static
callback for the intersect() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, intersect(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_intersected()
PyObject * BoundBoxPy::staticCallback_intersected (PyObject * self, PyObject * args) static
callback for the intersected() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, intersected(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_isCutPlane()
PyObject * BoundBoxPy::staticCallback_isCutPlane (PyObject * self, PyObject * args) static
callback for the isCutPlane() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), isCutPlane(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_isInside()
PyObject * BoundBoxPy::staticCallback_isInside (PyObject * self, PyObject * args) static
callback for the isInside() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), isInside(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_isValid()
PyObject * BoundBoxPy::staticCallback_isValid (PyObject * self, PyObject * args) static
callback for the isValid() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_move()
PyObject * BoundBoxPy::staticCallback_move (PyObject * self, PyObject * args) static
callback for the move() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), move(), and Base::PyObjectBase::startNotify().
staticCallback_scale()
PyObject * BoundBoxPy::staticCallback_scale (PyObject * self, PyObject * args) static
callback for the scale() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), scale(), and Base::PyObjectBase::startNotify().
staticCallback_setCenter()
int BoundBoxPy::staticCallback_setCenter (PyObject * self, PyObject * value, void * closure) static
setter callback for the Center attribute
References Base::PyObjectBase::isValid().
staticCallback_setDiagonalLength()
int BoundBoxPy::staticCallback_setDiagonalLength (PyObject * self, PyObject * value, void * closure) static
setter callback for the DiagonalLength attribute
References Base::PyObjectBase::isValid().
staticCallback_setVoid()
PyObject * BoundBoxPy::staticCallback_setVoid (PyObject * self, PyObject * args) static
callback for the setVoid() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), setVoid(), and Base::PyObjectBase::startNotify().
staticCallback_setXLength()
int BoundBoxPy::staticCallback_setXLength (PyObject * self, PyObject * value, void * closure) static
setter callback for the XLength attribute
References Base::PyObjectBase::isValid().
staticCallback_setXMax()
int BoundBoxPy::staticCallback_setXMax (PyObject * self, PyObject * value, void * closure) static
setter callback for the XMax attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setXMax().
staticCallback_setXMin()
int BoundBoxPy::staticCallback_setXMin (PyObject * self, PyObject * value, void * closure) static
setter callback for the XMin attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setXMin().
staticCallback_setYLength()
int BoundBoxPy::staticCallback_setYLength (PyObject * self, PyObject * value, void * closure) static
setter callback for the YLength attribute
References Base::PyObjectBase::isValid().
staticCallback_setYMax()
int BoundBoxPy::staticCallback_setYMax (PyObject * self, PyObject * value, void * closure) static
setter callback for the YMax attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setYMax().
staticCallback_setYMin()
int BoundBoxPy::staticCallback_setYMin (PyObject * self, PyObject * value, void * closure) static
setter callback for the YMin attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setYMin().
staticCallback_setZLength()
int BoundBoxPy::staticCallback_setZLength (PyObject * self, PyObject * value, void * closure) static
setter callback for the ZLength attribute
References Base::PyObjectBase::isValid().
staticCallback_setZMax()
int BoundBoxPy::staticCallback_setZMax (PyObject * self, PyObject * value, void * closure) static
setter callback for the ZMax attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setZMax().
staticCallback_setZMin()
int BoundBoxPy::staticCallback_setZMin (PyObject * self, PyObject * value, void * closure) static
setter callback for the ZMin attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setZMin().
staticCallback_transformed()
PyObject * BoundBoxPy::staticCallback_transformed (PyObject * self, PyObject * args) static
callback for the transformed() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::startNotify(), and transformed().
staticCallback_united()
PyObject * BoundBoxPy::staticCallback_united (PyObject * self, PyObject * args) static
callback for the united() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::startNotify(), and united().
transformed()
PyObject * BoundBoxPy::transformed (PyObject * args)
implementer for the transformed() method
References getBoundBoxPtr(), Base::BoundBox3< _Precision >::Transformed(), and Base::MatrixPy::Type.
Referenced by staticCallback_transformed().
united()
PyObject * BoundBoxPy::united (PyObject * args)
implementer for the united() method
References getBoundBoxPtr(), Type, and Base::BoundBox3< _Precision >::United().
Referenced by staticCallback_united().
Member Data Documentation
GetterSetter
PyGetSetDef BoundBoxPy::GetterSetter static
Attribute structure of BoundBoxPy.
Methods
PyMethodDef BoundBoxPy::Methods static
Methods structure of BoundBoxPy.
Type
PyTypeObject BoundBoxPy::Type static
Type structure of BoundBoxPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), add(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), Gui::ViewProviderLink::initDraggingPlacement(), intersect(), intersected(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), isInside(), PyInit(), draftobjects.layer.Layer::set_properties(), ArchReference.ArchReference::setProperties(), and united().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Base/BoundBoxPy.h
Sources/FreeCAD/src/Base/BoundBoxPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Base/BoundBoxPy.cpp