FreeCAD: Path::PathPy Class Reference
Path::PathPy Class Reference
The python export class for Toolpath.
#include <PathPy.h>
Public Types
typedef Toolpath * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
PathPy (Toolpath *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of PathPy.
static PyMethodDef Methods []
Methods structure of PathPy.
static PyTypeObject Type
Type structure of PathPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~PathPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * addCommands (PyObject *args)
implementer for the addCommands() method
PyObject * insertCommand (PyObject *args)
implementer for the insertCommand() method
PyObject * deleteCommand (PyObject *args)
implementer for the deleteCommand() method
PyObject * setFromGCode (PyObject *args)
implementer for the setFromGCode() method
PyObject * toGCode (PyObject *args)
implementer for the toGCode() method
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * getCycleTime (PyObject *args)
implementer for the getCycleTime() method
static PyObject * staticCallback_addCommands (PyObject *self, PyObject *args)
callback for the addCommands() method
static PyObject * staticCallback_insertCommand (PyObject *self, PyObject *args)
callback for the insertCommand() method
static PyObject * staticCallback_deleteCommand (PyObject *self, PyObject *args)
callback for the deleteCommand() method
static PyObject * staticCallback_setFromGCode (PyObject *self, PyObject *args)
callback for the setFromGCode() method
static PyObject * staticCallback_toGCode (PyObject *self, PyObject *args)
callback for the toGCode() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_getCycleTime (PyObject *self, PyObject *args)
callback for the getCycleTime() method
callbacks and implementers for the python object attributes
Py::Float getLength (void) const
getter for the Length attribute
Py::Long getSize (void) const
getter for the Size attribute
Py::List getCommands (void) const
getter for the Commands attribute
void setCommands (Py::List arg)
setter for the Commands attribute
Py::Object getCenter (void) const
getter for the Center attribute
void setCenter (Py::Object arg)
setter for the Center attribute
Py::Object getBoundBox (void) const
getter for the BoundBox attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Toolpath * getToolpathPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getLength (PyObject *self, void *closure)
getter callback for the Length attribute
static int staticCallback_setLength (PyObject *self, PyObject *value, void *closure)
setter callback for the Length attribute
static PyObject * staticCallback_getSize (PyObject *self, void *closure)
getter callback for the Size attribute
static int staticCallback_setSize (PyObject *self, PyObject *value, void *closure)
setter callback for the Size attribute
static PyObject * staticCallback_getCommands (PyObject *self, void *closure)
getter callback for the Commands attribute
static int staticCallback_setCommands (PyObject *self, PyObject *value, void *closure)
setter callback for the Commands attribute
static PyObject * staticCallback_getCenter (PyObject *self, void *closure)
getter callback for the Center attribute
static int staticCallback_setCenter (PyObject *self, PyObject *value, void *closure)
setter callback for the Center attribute
static PyObject * staticCallback_getBoundBox (PyObject *self, void *closure)
getter callback for the BoundBox attribute
static int staticCallback_setBoundBox (PyObject *self, PyObject *value, void *closure)
setter callback for the BoundBox attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Toolpath.
Member Typedef Documentation
PointerType
typedef Toolpath* Path::PathPy::PointerType
Constructor & Destructor Documentation
~PathPy()
PathPy::~PathPy () protected
PathPy()
PathPy::PathPy (Toolpath * pcObject, PyTypeObject * T = &Type)
Referenced by addCommands(), copy(), deleteCommand(), insertCommand(), and PyMake().
Member Function Documentation
addCommands()
PyObject * PathPy::addCommands (PyObject * args)
implementer for the addCommands() method
References Path::Toolpath::addCommand(), Base::BaseExceptionFreeCADError, getToolpathPtr(), PathPy(), and Path::CommandPy::Type.
Referenced by staticCallback_addCommands().
copy()
PyObject * PathPy::copy (PyObject * args)
implementer for the copy() method
References getToolpathPtr(), and PathPy().
Referenced by staticCallback_copy().
deleteCommand()
PyObject * PathPy::deleteCommand (PyObject * args)
implementer for the deleteCommand() method
References Base::BaseExceptionFreeCADError, Path::Toolpath::deleteCommand(), getToolpathPtr(), and PathPy().
Referenced by staticCallback_deleteCommand().
getBoundBox()
Py::Object PathPy::getBoundBox (void) const
getter for the BoundBox attribute
References getToolpathPtr().
Referenced by staticCallback_getBoundBox().
getCenter()
Py::Object PathPy::getCenter (void) const
getter for the Center attribute
References getToolpathPtr().
Referenced by staticCallback_getCenter().
getCommands()
Py::List PathPy::getCommands (void) const
getter for the Commands attribute
References Path::Toolpath::getSize(), and getToolpathPtr().
Referenced by staticCallback_getCommands().
getCustomAttributes()
PyObject * PathPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getCycleTime()
PyObject * PathPy::getCycleTime (PyObject * args)
implementer for the getCycleTime() method
References getToolpathPtr().
Referenced by staticCallback_getCycleTime().
getLength()
Py::Float PathPy::getLength (void) const
getter for the Length attribute
References getToolpathPtr().
Referenced by staticCallback_getLength().
getSize()
Py::Long PathPy::getSize (void) const
getter for the Size attribute
References getToolpathPtr().
Referenced by staticCallback_getSize().
getToolpathPtr()
Toolpath * PathPy::getToolpathPtr (void) const
getter for the object handled by this class
Referenced by addCommands(), copy(), deleteCommand(), getBoundBox(), getCenter(), getCommands(), getCycleTime(), getLength(), getSize(), insertCommand(), PyInit(), representation(), setCenter(), setCommands(), setFromGCode(), Path::PropertyPath::setPyObject(), and toGCode().
GetType()
virtual PyTypeObject* Path::PathPy::GetType (void) virtual
Reimplemented from Base::PersistencePy.
insertCommand()
PyObject * PathPy::insertCommand (PyObject * args)
implementer for the insertCommand() method
References Base::BaseExceptionFreeCADError, getToolpathPtr(), Path::Toolpath::insertCommand(), PathPy(), and Path::CommandPy::Type.
Referenced by staticCallback_insertCommand().
PyInit()
int PathPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PersistencePy.
References Path::Toolpath::addCommand(), getToolpathPtr(), Path::Toolpath::setFromGCode(), and Path::CommandPy::Type.
PyMake()
PyObject * PathPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References PathPy().
representation()
std::string PathPy::representation (void) const
References Path::Toolpath::getLength(), Path::Toolpath::getSize(), and getToolpathPtr().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCenter()
void PathPy::setCenter (Py::Object arg)
setter for the Center attribute
References getToolpathPtr(), and Path::Toolpath::setCenter().
Referenced by staticCallback_setCenter().
setCommands()
void PathPy::setCommands (Py::List arg)
setter for the Commands attribute
References Path::Toolpath::addCommand(), Path::Toolpath::clear(), getToolpathPtr(), and Path::CommandPy::Type.
Referenced by staticCallback_setCommands().
setCustomAttributes()
int PathPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setFromGCode()
PyObject * PathPy::setFromGCode (PyObject * args)
implementer for the setFromGCode() method
References getToolpathPtr(), and Path::Toolpath::setFromGCode().
Referenced by staticCallback_setFromGCode().
staticCallback_addCommands()
PyObject * PathPy::staticCallback_addCommands (PyObject * self, PyObject * args) static
callback for the addCommands() method
References addCommands(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_copy()
PyObject * PathPy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copy(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_deleteCommand()
PyObject * PathPy::staticCallback_deleteCommand (PyObject * self, PyObject * args) static
callback for the deleteCommand() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, deleteCommand(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getBoundBox()
PyObject * PathPy::staticCallback_getBoundBox (PyObject * self, void * closure) static
getter callback for the BoundBox attribute
References Base::BaseExceptionFreeCADError, getBoundBox(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCenter()
PyObject * PathPy::staticCallback_getCenter (PyObject * self, void * closure) static
getter callback for the Center attribute
References Base::BaseExceptionFreeCADError, getCenter(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCommands()
PyObject * PathPy::staticCallback_getCommands (PyObject * self, void * closure) static
getter callback for the Commands attribute
References Base::BaseExceptionFreeCADError, getCommands(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCycleTime()
PyObject * PathPy::staticCallback_getCycleTime (PyObject * self, PyObject * args) static
callback for the getCycleTime() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getCycleTime(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getLength()
PyObject * PathPy::staticCallback_getLength (PyObject * self, void * closure) static
getter callback for the Length attribute
References Base::BaseExceptionFreeCADError, getLength(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSize()
PyObject * PathPy::staticCallback_getSize (PyObject * self, void * closure) static
getter callback for the Size attribute
References Base::BaseExceptionFreeCADError, getSize(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_insertCommand()
PyObject * PathPy::staticCallback_insertCommand (PyObject * self, PyObject * args) static
callback for the insertCommand() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, insertCommand(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_setBoundBox()
int PathPy::staticCallback_setBoundBox (PyObject * self, PyObject * value, void * closure) static
setter callback for the BoundBox attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setCenter()
int PathPy::staticCallback_setCenter (PyObject * self, PyObject * value, void * closure) static
setter callback for the Center attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setCenter().
staticCallback_setCommands()
int PathPy::staticCallback_setCommands (PyObject * self, PyObject * value, void * closure) static
setter callback for the Commands attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setCommands().
staticCallback_setFromGCode()
PyObject * PathPy::staticCallback_setFromGCode (PyObject * self, PyObject * args) static
callback for the setFromGCode() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setFromGCode(), and Base::PyObjectBase::startNotify().
staticCallback_setLength()
int PathPy::staticCallback_setLength (PyObject * self, PyObject * value, void * closure) static
setter callback for the Length attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setSize()
int PathPy::staticCallback_setSize (PyObject * self, PyObject * value, void * closure) static
setter callback for the Size attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_toGCode()
PyObject * PathPy::staticCallback_toGCode (PyObject * self, PyObject * args) static
callback for the toGCode() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and toGCode().
toGCode()
PyObject * PathPy::toGCode (PyObject * args)
implementer for the toGCode() method
References getToolpathPtr(), and Path::Toolpath::toGCode().
Referenced by staticCallback_toGCode().
Member Data Documentation
GetterSetter
PyGetSetDef PathPy::GetterSetter static
Attribute structure of PathPy.
Methods
PyMethodDef PathPy::Methods static
Methods structure of PathPy.
Type
PyTypeObject PathPy::Type static
Type structure of PathPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), and Path::PropertyPath::setPyObject().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/PathPy.h
Sources/FreeCAD/src/Mod/Path/App/PathPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/PathPy.cpp