FreeCAD: SMDS_PolyhedralVolumeOfNodes Class Reference
SMDS_PolyhedralVolumeOfNodes Class Reference
#include <SMDS_PolyhedralVolumeOfNodes.hxx>
Public Member Functions
bool ChangeNodes (const std::vector< const SMDS_MeshNode * > &nodes, const std::vector< int > &quantities)
virtual SMDSAbs_EntityType GetEntityType () const
const SMDS_MeshNode * GetFaceNode (const int face_ind, const int node_ind) const
virtual const SMDS_MeshNode * GetNode (const int ind) const
Return node by its index.
const std::vector< int > & GetQuanities () const
virtual SMDSAbs_ElementType GetType () const
Return the type of the current element.
virtual bool IsPoly () const
virtual int NbEdges () const
Return the number of edges owned by or linked with the current element.
int NbFaceNodes (const int face_ind) const
virtual int NbFaces () const
Return the number of faces owned by or linked with the current element.
virtual int NbNodes () const
Return The number of nodes owned by the current element.
int NbUniqueNodes () const
Return nb of unique nodes.
virtual void Print (std::ostream &OS) const
SMDS_PolyhedralVolumeOfNodes (std::vector< const SMDS_MeshNode * > nodes, std::vector< int > quantities)
SMDS_ElemIteratorPtr uniqueNodesIterator () const
Return iterator on unique nodes.
Public Member Functions inherited from SMDS_VolumeOfNodes
bool ChangeNodes (const SMDS_MeshNode *nodes[], const int nbNodes)
virtual SMDSAbs_EntityType GetEntityType () const
virtual SMDSAbs_GeometryType GetGeomType () const
virtual const SMDS_MeshNode * GetNode (const int ind) const
Return node by its index.
virtual SMDSAbs_ElementType GetType () const
Return the type of the current element.
int NbEdges () const
Return the number of edges owned by or linked with the current element.
int NbFaces () const
Return the number of faces owned by or linked with the current element.
int NbNodes () const
Return The number of nodes owned by the current element.
void Print (std::ostream &OS) const
SMDS_VolumeOfNodes (const SMDS_MeshNode *node1, const SMDS_MeshNode *node2, const SMDS_MeshNode *node3, const SMDS_MeshNode *node4)
SMDS_VolumeOfNodes (const SMDS_MeshNode *node1, const SMDS_MeshNode *node2, const SMDS_MeshNode *node3, const SMDS_MeshNode *node4, const SMDS_MeshNode *node5)
SMDS_VolumeOfNodes (const SMDS_MeshNode *node1, const SMDS_MeshNode *node2, const SMDS_MeshNode *node3, const SMDS_MeshNode *node4, const SMDS_MeshNode *node5, const SMDS_MeshNode *node6)
SMDS_VolumeOfNodes (const SMDS_MeshNode *node1, const SMDS_MeshNode *node2, const SMDS_MeshNode *node3, const SMDS_MeshNode *node4, const SMDS_MeshNode *node5, const SMDS_MeshNode *node6, const SMDS_MeshNode *node7, const SMDS_MeshNode *node8)
Create an hexahedron.
~SMDS_VolumeOfNodes ()
Public Member Functions inherited from SMDS_MeshVolume
SMDSAbs_ElementType GetType () const
Return the type of the current element.
virtual vtkIdType GetVtkType () const
Public Member Functions inherited from SMDS_MeshCell
virtual bool ChangeNodes (const SMDS_MeshNode *nodes[], const int nbNodes)=0
SMDS_MeshCell ()
virtual bool vtkOrder (const SMDS_MeshNode *[], const int)
virtual ~SMDS_MeshCell ()
Public Member Functions inherited from SMDS_MeshElement
iterator begin_nodes () const
SMDS_ElemIteratorPtr edgesIterator () const
Create an iterator which iterate on edges linked with or owned by the element.
virtual SMDS_ElemIteratorPtr elementsIterator (SMDSAbs_ElementType type) const
iterator end_nodes () const
SMDS_ElemIteratorPtr facesIterator () const
Create an iterator which iterate on faces linked with or owned by the element.
virtual SMDSAbs_EntityType GetEntityType () const =0
virtual SMDSAbs_GeometryType GetGeomType () const =0
int GetID () const
int getIdInShape () const
ShortType getMeshId () const
virtual const SMDS_MeshNode * GetNode (const int ind) const
Return node by its index.
virtual int GetNodeIndex (const SMDS_MeshNode *node) const
Check if a node belongs to the element.
const SMDS_MeshNode * GetNodeWrap (const int ind) const
Return node by its index.
LongType getshapeId () const
virtual SMDSAbs_ElementType GetType () const =0
Return the type of the current element.
int getVtkId () const
virtual vtkIdType GetVtkType () const =0
virtual SMDS_ElemIteratorPtr interlacedNodesElemIterator () const
virtual SMDS_NodeIteratorPtr interlacedNodesIterator () const
virtual, redefined in vtkEdge, vtkFace and vtkVolume classes
virtual bool IsMediumNode (const SMDS_MeshNode *node) const
virtual bool IsPoly () const
virtual bool IsQuadratic () const
virtual bool IsValidIndex (const int ind) const
Return true if index of node is valid (0 <= ind < NbNodes())
virtual int NbCornerNodes () const
Return number of nodes excluding medium ones.
virtual int NbEdges () const
Return the number of edges owned by or linked with the current element.
virtual int NbFaces () const
Return the number of faces owned by or linked with the current element.
virtual int NbNodes () const
Return The number of nodes owned by the current element.
virtual SMDS_NodeIteratorPtr nodeIterator () const
SMDS_ElemIteratorPtr nodesIterator () const
Create an iterator which iterate on nodes owned by the element.
virtual SMDS_NodeIteratorPtr nodesIteratorToUNV () const
virtual, redefined in vtkEdge, vtkFace and vtkVolume classes
int WrappedIndex (const int ind) const
Return a valid node index, fixing the given one if necessary.
Public Member Functions inherited from SMDS_MeshObject
virtual ~SMDS_MeshObject ()
Protected Member Functions
SMDS_ElemIteratorPtr elementsIterator (SMDSAbs_ElementType type) const
Return Iterator of sub elements.
Protected Member Functions inherited from SMDS_VolumeOfNodes
SMDS_ElemIteratorPtr elementsIterator (SMDSAbs_ElementType type) const
Protected Member Functions inherited from SMDS_MeshCell
void exchange (const SMDS_MeshNode *nodes[], int a, int b)
Protected Member Functions inherited from SMDS_MeshElement
virtual void init (int id=-1, ShortType meshId=-1, LongType shapeId=0)
virtual void Print (std::ostream &OS) const
void setId (int id)
void setIdInShape (int id)
void setShapeId (LongType shapeId)
void setVtkId (int vtkId)
SMDS_MeshElement (int id, ShortType meshId, LongType shapeId=0)
SMDS_MeshElement (int ID=-1)
Additional Inherited Members
Public Types inherited from SMDS_MeshElement
typedef SMDS_StdIterator< const SMDS_MeshNode *, SMDS_ElemIteratorPtr > iterator
Static Public Member Functions inherited from SMDS_MeshCell
template<class VECT >
static void applyInterlace (const std::vector< int > &interlace, VECT &data)
template<class VECT >
static void applyInterlaceRev (const std::vector< int > &interlace, VECT &data)
static const std::vector< int > & fromVtkOrder (SMDSAbs_EntityType smdsType)
Return indices to transform cell connectivity from VTK to SMDS Usage: smdsIDs[i] = vtkIDs[ indices[ i ]].
static const std::vector< int > & fromVtkOrder (VTKCellType vtkType)
Return indices to transform cell connectivity from VTK to SMDS Usage: smdsIDs[i] = vtkIDs[ indices[ i ]].
static const std::vector< int > & interlacedSmdsOrder (SMDSAbs_EntityType smdsType, const size_t nbNodes=0)
Return indices to set nodes of a quadratic 1D or 2D element in interlaced order Usage: interlacedIDs[i] = smdsIDs[ indices[ i ]].
static const std::vector< int > & reverseSmdsOrder (SMDSAbs_EntityType smdsType, const size_t nbNodes=0)
Return indices to reverse an SMDS cell of given type. nbNodes is useful for polygons Usage: reverseIDs[i] = forwardIDs[ indices[ i ]].
static SMDSAbs_ElementType toSmdsType (SMDSAbs_EntityType entityType)
Return SMDSAbs_ElementType by SMDSAbs_EntityType.
static SMDSAbs_ElementType toSmdsType (SMDSAbs_GeometryType geomType)
Return SMDSAbs_ElementType by SMDSAbs_GeometryType.
static SMDSAbs_EntityType toSmdsType (VTKCellType vtkType)
Return SMDSAbs_EntityType corresponding to VTKCellType.
static const std::vector< int > & toVtkOrder (SMDSAbs_EntityType smdsType)
Return indices to transform cell connectivity from SMDS to VTK Usage: vtkIDs[i] = smdsIDs[ indices[ i ]].
static const std::vector< int > & toVtkOrder (VTKCellType vtkType)
Return indices to transform cell connectivity from SMDS to VTK Usage: vtkIDs[i] = smdsIDs[ indices[ i ]].
static VTKCellType toVtkType (SMDSAbs_EntityType vtkType)
Return VTKCellType corresponding to SMDSAbs_EntityType.
Static Public Attributes inherited from SMDS_MeshCell
static int nbCells = 0
Protected Attributes inherited from SMDS_VolumeOfNodes
int myNbNodes
const SMDS_MeshNode ** myNodes
Protected Attributes inherited from SMDS_MeshElement
int myID
Element index in vector SMDS_Mesh::myNodes or SMDS_Mesh::myCells.
int myIdInShape
Element index in SMESHDS_SubMesh vector.
ShortType myMeshId
SMDS_Mesh identification in SMESH.
LongType myShapeId
SubShape and SubMesh identification in SMESHDS.
vtkIdType myVtkID
index in vtkUnstructuredGrid
Constructor & Destructor Documentation
SMDS_PolyhedralVolumeOfNodes()
SMDS_PolyhedralVolumeOfNodes::SMDS_PolyhedralVolumeOfNodes (std::vector< const SMDS_MeshNode * > nodes, std::vector< int > quantities)
References ChangeNodes().
Member Function Documentation
ChangeNodes()
bool SMDS_PolyhedralVolumeOfNodes::ChangeNodes (const std::vector< const SMDS_MeshNode * > & nodes, const std::vector< int > & quantities)
References SMDS_VolumeOfNodes::myNbNodes, and SMDS_VolumeOfNodes::myNodes.
Referenced by SMDS_PolyhedralVolumeOfNodes().
elementsIterator()
SMDS_ElemIteratorPtr SMDS_PolyhedralVolumeOfNodes::elementsIterator (SMDSAbs_ElementType type) const protected virtual
Return Iterator of sub elements.
Reimplemented from SMDS_MeshElement.
References SMDS_MeshElement::elementsIterator().
GetEntityType()
virtual SMDSAbs_EntityType SMDS_PolyhedralVolumeOfNodes::GetEntityType () const virtual
Reimplemented from SMDS_VolumeOfNodes.
GetFaceNode()
const SMDS_MeshNode * SMDS_PolyhedralVolumeOfNodes::GetFaceNode (const int face_ind, const int node_ind) const
References NbFaceNodes().
GetNode()
const SMDS_MeshNode * SMDS_PolyhedralVolumeOfNodes::GetNode (const int ind) const virtual
Return node by its index.
Reimplemented from SMDS_VolumeOfNodes.
GetQuanities()
const std::vector< int > & SMDS_PolyhedralVolumeOfNodes::GetQuanities () const
GetType()
SMDSAbs_ElementType SMDS_PolyhedralVolumeOfNodes::GetType () const virtual
Return the type of the current element.
Reimplemented from SMDS_VolumeOfNodes.
IsPoly()
virtual bool SMDS_PolyhedralVolumeOfNodes::IsPoly () const virtual
Reimplemented from SMDS_MeshElement.
NbEdges()
int SMDS_PolyhedralVolumeOfNodes::NbEdges () const virtual
Return the number of edges owned by or linked with the current element.
Reimplemented from SMDS_MeshElement.
NbFaceNodes()
int SMDS_PolyhedralVolumeOfNodes::NbFaceNodes (const int face_ind) const
Referenced by GetFaceNode().
NbFaces()
int SMDS_PolyhedralVolumeOfNodes::NbFaces () const virtual
Return the number of faces owned by or linked with the current element.
Reimplemented from SMDS_MeshElement.
NbNodes()
int SMDS_PolyhedralVolumeOfNodes::NbNodes () const virtual
Return The number of nodes owned by the current element.
Reimplemented from SMDS_MeshElement.
NbUniqueNodes()
int SMDS_PolyhedralVolumeOfNodes::NbUniqueNodes () const
Return nb of unique nodes.
References SMDS_VolumeOfNodes::myNbNodes.
Print()
void SMDS_PolyhedralVolumeOfNodes::Print (std::ostream & OS) const virtual
Reimplemented from SMDS_MeshElement.
References SMDS_MeshElement::GetID().
uniqueNodesIterator()
SMDS_ElemIteratorPtr SMDS_PolyhedralVolumeOfNodes::uniqueNodesIterator () const
Return iterator on unique nodes.
References SMDS_VolumeOfNodes::myNbNodes, and SMDS_VolumeOfNodes::myNodes.
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_PolyhedralVolumeOfNodes.hxx
FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_PolyhedralVolumeOfNodes.cpp