FreeCAD: Base::UnitsSchemaMKS Class Reference
Base::UnitsSchemaMKS Class Reference
The UnitSchema class.
#include <UnitsSchemaMKS.h>
Public Member Functions
virtual QString schemaTranslate (const Base::Quantity &quant, double &factor, QString &unitString)
This method translates the quantity in a string as the user may expect it.
Public Member Functions inherited from Base::UnitsSchema
virtual void resetSchemaUnits ()
If you use setSchemaUnits() you also have to impment this method to undo your changes!
virtual QString schemaTranslate (const Base::Quantity &quant, double &factor, QString &unitString)=0
This method translates the quantity in a string as the user may expect it.
virtual void setSchemaUnits ()
Gets called if this schema gets activated.
QString toLocale (const Base::Quantity &quant, double factor, const QString &unitString) const
virtual ~UnitsSchema ()
Detailed Description
The UnitSchema class.
Member Function Documentation
schemaTranslate()
QString UnitsSchemaMKS::schemaTranslate (const Base::Quantity & quant, double & factor, QString & unitString) virtual
This method translates the quantity in a string as the user may expect it.
Implements Base::UnitsSchema.
References Base::Unit::Acceleration, Base::Unit::Area, Base::Unit::Density, Base::Unit::DynamicViscosity, Base::Unit::ElectricalCapacitance, Base::Unit::ElectricalConductance, Base::Unit::ElectricalConductivity, Base::Unit::ElectricalInductance, Base::Unit::ElectricalResistance, Base::Unit::ElectricCharge, Base::Unit::ElectricPotential, Base::Unit::Force, Base::Unit::Frequency, Base::Unit::getString(), Base::Quantity::getUnit(), Base::Quantity::getValue(), Base::Unit::HeatFlux, Base::Unit::KinematicViscosity, Base::Unit::Length, Base::Unit::MagneticFieldStrength, Base::Unit::MagneticFlux, Base::Unit::MagneticFluxDensity, Base::Unit::Mass, Base::Unit::Power, Base::Unit::Pressure, Base::Unit::SpecificEnergy, Base::Unit::SpecificHeat, Base::Unit::Stiffness, Base::Unit::Stress, Base::Unit::ThermalConductivity, Base::Unit::ThermalExpansionCoefficient, Base::Unit::ThermalTransferCoefficient, Base::UnitsSchema::toLocale(), Base::Unit::Velocity, Base::Unit::Volume, Base::Unit::VolumetricThermalExpansionCoefficient, and Base::Unit::Work.
The documentation for this class was generated from the following files:
FreeCAD/src/Base/UnitsSchemaMKS.h
FreeCAD/src/Base/UnitsSchemaMKS.cpp