FreeCAD: SMDS_Down1D Class Reference
SMDS_Down1D Class Reference
#include <SMDS_Downward.hxx>
Public Member Functions
virtual void getNodeIds (int cellId, std::set< int > &nodeSet)
virtual int getNodes (int cellId, int *nodevec)
virtual int getNumberOfUpCells (int cellId)
virtual const int * getUpCells (int cellId)
virtual const unsigned char * getUpTypes (int cellId)
Public Member Functions inherited from SMDS_Downward
virtual const int * getDownCells (int cellId)
virtual const unsigned char * getDownTypes (int cellId)
int getMaxId ()
virtual void getNodeIds (int cellId, std::set< int > &nodeSet)=0
virtual int getNodes (int cellId, int *nodevec)
virtual int getNumberOfDownCells (int cellId)
virtual int getNumberOfUpCells (int cellId)=0
virtual void getOrderedNodesOfFace (int cellId, std::vector< vtkIdType > &orderedNodes)
virtual const int * getUpCells (int cellId)=0
virtual const unsigned char * getUpTypes (int cellId)=0
int getVtkCellId (int cellId)
Protected Member Functions
virtual void addUpCell (int cellId, int upCellId, unsigned char aType)
Id's are downward connectivity id's.
virtual void allocate (int nbElems)
virtual void compactStorage ()
int computeFaces (int *pts, int *vtkIds, int nbcells, int *downFaces, unsigned char *downTypes)
int computeFaces (int cellId, int *vtkIds, int nbcells, int *downFaces, unsigned char *downTypes)
int computeVtkCells (int *pts, std::vector< int > &vtkIds)
int computeVtkCells (int cellId, std::vector< int > &vtkIds)
virtual int getNodeSet (int cellId, int *nodeSet)
virtual void initCell (int cellId)
void setNodes (int cellId, const int *nodeIds)
void setNodes (int cellId, int vtkId)
SMDS_Down1D (SMDS_UnstructuredGrid *grid, int nbDownCells)
~SMDS_Down1D ()
Protected Member Functions inherited from SMDS_Downward
int addCell (int vtkId=-1)
virtual void addDownCell (int cellId, int lowCellId, unsigned char aType)
Id's are downward connectivity id's.
virtual void addUpCell (int cellId, int upCellId, unsigned char aType)
Id's are downward connectivity id's.
virtual void allocate (int nbElems)=0
virtual void compactStorage ()=0
virtual int getNodeSet (int cellId, int *nodeSet)
virtual void initCell (int cellId)
SMDS_Downward (SMDS_UnstructuredGrid *grid, int nbDownCells)
virtual ~SMDS_Downward ()
Friends
class SMDS_UnstructuredGrid
Additional Inherited Members
Static Public Member Functions inherited from SMDS_Downward
static int getCellDimension (unsigned char cellType)
Constructor & Destructor Documentation
SMDS_Down1D()
SMDS_Down1D::SMDS_Down1D (SMDS_UnstructuredGrid * grid, int nbDownCells) protected
~SMDS_Down1D()
SMDS_Down1D::~SMDS_Down1D () protected
Member Function Documentation
addUpCell()
void SMDS_Down1D::addUpCell (int cellId, int upCellId, unsigned char aType) protected virtual
Id's are downward connectivity id's.
Reimplemented from SMDS_Downward.
allocate()
void SMDS_Down1D::allocate (int nbElems) protected virtual
Resize the downward connectivity storage vector if needed.
Parameters
nbElems total number of elements of the same type required
Implements SMDS_Downward.
References SMDS_Mesh::chunkSize.
compactStorage()
void SMDS_Down1D::compactStorage () protected virtual
Implements SMDS_Downward.
computeFaces() [1/2]
int SMDS_Down1D::computeFaces (int * pts, int * vtkIds, int nbcells, int * downFaces, unsigned char * downTypes) protected
Build the list of downward faces from a list of vtk cells.
Parameters
pts list of points id's defining an edge
vtkIds vector of vtk id's
downFaces vector of face id's in downward structures
downTypes vector of face types
Returns
number of downward faces
References SMDS_Downward::getCellDimension(), SMDS_Downward::getDownCells(), SMDS_Downward::getDownTypes(), SMDS_Downward::getNumberOfDownCells(), and SMDS_Down2D::isInFace().
computeFaces() [2/2]
int SMDS_Down1D::computeFaces (int cellId, int * vtkIds, int nbcells, int * downFaces, unsigned char * downTypes) protected
Build the list of downward faces from a list of vtk cells.
Parameters
cellId id of the edge in the downward structure
vtkIds vector of vtk id's
downFaces vector of face id's in downward structures
downTypes vector of face types
Returns
number of downward faces
References computeFaces().
Referenced by SMDS_UnstructuredGrid::BuildDownwardConnectivity(), and computeFaces().
computeVtkCells() [1/2]
int SMDS_Down1D::computeVtkCells (int * pts, std::vector< int > & vtkIds) protected
Build the list of vtkUnstructuredGrid cells containing the edge.
Parameters
pts list of points id's defining an edge
vtkIds vector of vtk id's
Returns
number of vtk cells (size of vector)
References SMDS_Downward::getCellDimension().
computeVtkCells() [2/2]
int SMDS_Down1D::computeVtkCells (int cellId, std::vector< int > & vtkIds) protected
Build the list of vtkUnstructuredGrid cells containing the edge. We keep in the list the cells that contains all the nodes, we keep only volumes and faces.
Parameters
cellId id of the edge in the downward structure
vtkIds vector of vtk id's
Returns
number of vtk cells (size of vector)
References computeVtkCells().
Referenced by SMDS_UnstructuredGrid::BuildDownwardConnectivity(), and computeVtkCells().
getNodeIds()
void SMDS_Down1D::getNodeIds (int cellId, std::set< int > & nodeSet) virtual
Implements SMDS_Downward.
getNodes()
virtual int SMDS_Down1D::getNodes (int cellId, int * nodevec) virtual
Reimplemented from SMDS_Downward.
getNodeSet()
int SMDS_Down1D::getNodeSet (int cellId, int * nodeSet) protected virtual
Reimplemented from SMDS_Downward.
getNumberOfUpCells()
int SMDS_Down1D::getNumberOfUpCells (int cellId) virtual
Implements SMDS_Downward.
getUpCells()
const int * SMDS_Down1D::getUpCells (int cellId) virtual
Implements SMDS_Downward.
getUpTypes()
const unsigned char * SMDS_Down1D::getUpTypes (int cellId) virtual
Implements SMDS_Downward.
initCell()
void SMDS_Down1D::initCell (int cellId) protected virtual
clear vectors used to reference 2D cells containing the edge
Parameters
cellId
Reimplemented from SMDS_Downward.
setNodes() [1/2]
void SMDS_Down1D::setNodes (int cellId, const int * nodeIds) protected
setNodes() [2/2]
void SMDS_Down1D::setNodes (int cellId, int vtkId) protected
Referenced by SMDS_UnstructuredGrid::BuildDownwardConnectivity().
Friends And Related Function Documentation
SMDS_UnstructuredGrid
friend class SMDS_UnstructuredGrid friend
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_Downward.hxx
FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_Downward.cpp