FreeCAD: zipios::ZipInputStreambuf Class Reference
zipios::ZipInputStreambuf Class Reference
ZipInputStreambuf is a zip input streambuf filter.
#include <zipinputstreambuf.h>
Public Member Functions
void close ()
Closes the streambuf.
void closeEntry ()
Closes the current entry, and positions the stream read pointer at the beginning of the next entry (if there is one).
ConstEntryPointer getNextEntry ()
Opens the next entry in the zip archive and returns a const pointer to a FileEntry object for the entry.
ZipInputStreambuf (streambuf *inbuf, int s_pos=-1, bool del_inbuf=false)
ZipInputStreambuf constructor.
virtual ~ZipInputStreambuf ()
Destructor.
Public Member Functions inherited from zipios::InflateInputStreambuf
InflateInputStreambuf (streambuf *inbuf, int s_pos=-1, bool del_inbuf=false)
InflateInputStreambuf constructor.
bool reset (int stream_position=-1)
Resets the zlib stream and purges input and output buffers.
virtual ~InflateInputStreambuf ()
Public Member Functions inherited from zipios::FilterInputStreambuf
FilterInputStreambuf (streambuf *inbuf, bool del_inbuf=false)
Constructor.
virtual ~FilterInputStreambuf ()
Destructor.
Protected Member Functions
virtual int underflow ()
Detailed Description
ZipInputStreambuf is a zip input streambuf filter.
Constructor & Destructor Documentation
ZipInputStreambuf()
zipios::ZipInputStreambuf::ZipInputStreambuf (streambuf * inbuf, int s_pos = -1, bool del_inbuf = false) explicit
ZipInputStreambuf constructor.
Parameters
inbuf the streambuf to use for input.
s_pos a position to reset the inbuf to before reading. Specify -1 to read from the current position.
del_inbuf if true is specified inbuf will be deleted, when the ZipInputStreambuf is destructed.
References getNextEntry().
~ZipInputStreambuf()
zipios::ZipInputStreambuf::~ZipInputStreambuf () virtual
Destructor.
Member Function Documentation
close()
void zipios::ZipInputStreambuf::close ()
Closes the streambuf.
Referenced by zipios::ZipInputStream::close(), and femexamples.examplesgui.FemExamples::reject().
closeEntry()
void zipios::ZipInputStreambuf::closeEntry ()
Closes the current entry, and positions the stream read pointer at the beginning of the next entry (if there is one).
Referenced by zipios::ZipInputStream::closeEntry(), and getNextEntry().
getNextEntry()
ConstEntryPointer zipios::ZipInputStreambuf::getNextEntry ()
Opens the next entry in the zip archive and returns a const pointer to a FileEntry object for the entry.
Returns
a const FileEntry * containing information about the (now) current entry.
References closeEntry(), zipios::DEFLATED, zipios::InflateInputStreambuf::reset(), and zipios::STORED.
Referenced by zipios::ZipInputStream::getNextEntry(), and ZipInputStreambuf().
underflow()
int zipios::ZipInputStreambuf::underflow () protected virtual
Reimplemented from zipios::InflateInputStreambuf.
References zipios::DEFLATED, zipios::min(), and zipios::InflateInputStreambuf::underflow().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/zipios++/zipinputstreambuf.h
Sources/FreeCAD/src/zipios++/zipinputstreambuf.cpp