FreeCAD: PathScripts.post.dumper_post Namespace Reference
PathScripts.post.dumper_post Namespace Reference
Functions
def export (objectslist, filename, argstring)
def parse (pathobj)
Variables
now = datetime.datetime.now()
pythonopen = open
bool SHOW_EDITOR = True
string TOOLTIP
Function Documentation
export()
def PathScripts.post.dumper_post.export (objectslist, filename, argstring)
References PathScripts.post.dumper_post.parse().
parse()
def PathScripts.post.dumper_post.parse (pathobj)
References PathScripts.post.dumper_post.parse().
Referenced by PathScripts.post.dumper_post.export(), and PathScripts.post.dumper_post.parse().
Variable Documentation
now
PathScripts.post.dumper_post.now = datetime.datetime.now()
pythonopen
PathScripts.post.dumper_post.pythonopen = open
SHOW_EDITOR
bool PathScripts.post.dumper_post.SHOW_EDITOR = True
TOOLTIP
string PathScripts.post.dumper_post.TOOLTIP
Initial value:
=  """
Dumper is an extremely simple postprocessor file for the Path workbench. It is used
to dump the command list from one or more Path objects for simple inspection. This post
doesn't do any manipulation of the path and doesn't write anything to disk.  It just
shows the dialog so you can see it.  Useful for debugging, but not much else.
"""