FreeCAD: Mesh::MeshPointPy Class Reference
Mesh::MeshPointPy Class Reference
The python export class for MeshPoint.
#include <MeshPointPy.h>
Public Types
typedef MeshPoint * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
MeshPointPy (MeshPoint *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of MeshPointPy.
static PyMethodDef Methods []
Methods structure of MeshPointPy.
static PyTypeObject Type
Type structure of MeshPointPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~MeshPointPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * unbound (PyObject *args)
implementer for the unbound() method
PyObject * move (PyObject *args)
implementer for the move() method
static PyObject * staticCallback_unbound (PyObject *self, PyObject *args)
callback for the unbound() method
static PyObject * staticCallback_move (PyObject *self, PyObject *args)
callback for the move() method
callbacks and implementers for the python object attributes
Py::Long getIndex (void) const
getter for the Index attribute
Py::Boolean getBound (void) const
getter for the Bound attribute
Py::Object getNormal (void) const
getter for the Normal attribute
Py::Object getVector (void) const
getter for the Vector attribute
Py::Float getx (void) const
getter for the x attribute
void setx (Py::Float arg)
setter for the x attribute
Py::Float gety (void) const
getter for the y attribute
void sety (Py::Float arg)
setter for the y attribute
Py::Float getz (void) const
getter for the z attribute
void setz (Py::Float arg)
setter for the z attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
MeshPoint * getMeshPointPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getIndex (PyObject *self, void *closure)
getter callback for the Index attribute
static int staticCallback_setIndex (PyObject *self, PyObject *value, void *closure)
setter callback for the Index attribute
static PyObject * staticCallback_getBound (PyObject *self, void *closure)
getter callback for the Bound attribute
static int staticCallback_setBound (PyObject *self, PyObject *value, void *closure)
setter callback for the Bound attribute
static PyObject * staticCallback_getNormal (PyObject *self, void *closure)
getter callback for the Normal attribute
static int staticCallback_setNormal (PyObject *self, PyObject *value, void *closure)
setter callback for the Normal attribute
static PyObject * staticCallback_getVector (PyObject *self, void *closure)
getter callback for the Vector attribute
static int staticCallback_setVector (PyObject *self, PyObject *value, void *closure)
setter callback for the Vector attribute
static PyObject * staticCallback_getx (PyObject *self, void *closure)
getter callback for the x attribute
static int staticCallback_setx (PyObject *self, PyObject *value, void *closure)
setter callback for the x attribute
static PyObject * staticCallback_gety (PyObject *self, void *closure)
getter callback for the y attribute
static int staticCallback_sety (PyObject *self, PyObject *value, void *closure)
setter callback for the y attribute
static PyObject * staticCallback_getz (PyObject *self, void *closure)
getter callback for the z attribute
static int staticCallback_setz (PyObject *self, PyObject *value, void *closure)
setter callback for the z attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for MeshPoint.
Member Typedef Documentation
PointerType
typedef MeshPoint* Mesh::MeshPointPy::PointerType
Constructor & Destructor Documentation
~MeshPointPy()
MeshPointPy::~MeshPointPy () protected
MeshPointPy()
MeshPointPy::MeshPointPy (MeshPoint * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getBound()
Py::Boolean MeshPointPy::getBound (void) const
getter for the Bound attribute
References getMeshPointPtr().
Referenced by staticCallback_getBound().
getCustomAttributes()
PyObject * MeshPointPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getIndex()
Py::Long MeshPointPy::getIndex (void) const
getter for the Index attribute
References getMeshPointPtr().
Referenced by staticCallback_getIndex().
getMeshPointPtr()
MeshPoint * MeshPointPy::getMeshPointPtr (void) const
getter for the object handled by this class
Referenced by getBound(), getIndex(), getNormal(), getx(), gety(), getz(), move(), PyInit(), representation(), setx(), sety(), setz(), and unbound().
getNormal()
Py::Object MeshPointPy::getNormal (void) const
getter for the Normal attribute
References getMeshPointPtr(), and Base::PyObjectBase::setConst().
Referenced by staticCallback_getNormal().
GetType()
virtual PyTypeObject* Mesh::MeshPointPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
getVector()
Py::Object MeshPointPy::getVector (void) const
getter for the Vector attribute
References draftgeoutils.general::vec().
Referenced by staticCallback_getVector().
getx()
Py::Float MeshPointPy::getx (void) const
getter for the x attribute
References getMeshPointPtr(), Mesh::MeshPoint::Index, Mesh::MeshPoint::isBound(), and Mesh::MeshPoint::Mesh.
Referenced by staticCallback_getx().
gety()
Py::Float MeshPointPy::gety (void) const
getter for the y attribute
References getMeshPointPtr(), Mesh::MeshPoint::Index, Mesh::MeshPoint::isBound(), and Mesh::MeshPoint::Mesh.
Referenced by staticCallback_gety().
getz()
Py::Float MeshPointPy::getz (void) const
getter for the z attribute
References getMeshPointPtr(), Mesh::MeshPoint::Index, Mesh::MeshPoint::isBound(), and Mesh::MeshPoint::Mesh.
Referenced by staticCallback_getz().
move()
PyObject * MeshPointPy::move (PyObject * args)
implementer for the move() method
References getMeshPointPtr(), Mesh::MeshPoint::Mesh, Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_move().
PyInit()
int MeshPointPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
References getMeshPointPtr().
PyMake()
PyObject * MeshPointPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References MeshPointPy().
representation()
std::string MeshPointPy::representation (void) const
References getMeshPointPtr(), Mesh::MeshPoint::Index, Mesh::MeshPoint::isBound(), Mesh::MeshPoint::Mesh, and draftgeoutils.general::vec().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int MeshPointPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setx()
void MeshPointPy::setx (Py::Float arg)
setter for the x attribute
References getMeshPointPtr(), Mesh::MeshPoint::Index, Mesh::MeshPoint::isBound(), and Mesh::MeshPoint::Mesh.
Referenced by staticCallback_setx().
sety()
void MeshPointPy::sety (Py::Float arg)
setter for the y attribute
References getMeshPointPtr(), Mesh::MeshPoint::Index, Mesh::MeshPoint::isBound(), and Mesh::MeshPoint::Mesh.
Referenced by staticCallback_sety().
setz()
void MeshPointPy::setz (Py::Float arg)
setter for the z attribute
References getMeshPointPtr(), Mesh::MeshPoint::Index, Mesh::MeshPoint::isBound(), and Mesh::MeshPoint::Mesh.
Referenced by staticCallback_setz().
staticCallback_getBound()
PyObject * MeshPointPy::staticCallback_getBound (PyObject * self, void * closure) static
getter callback for the Bound attribute
References Base::BaseExceptionFreeCADError, getBound(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getIndex()
PyObject * MeshPointPy::staticCallback_getIndex (PyObject * self, void * closure) static
getter callback for the Index attribute
References Base::BaseExceptionFreeCADError, getIndex(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNormal()
PyObject * MeshPointPy::staticCallback_getNormal (PyObject * self, void * closure) static
getter callback for the Normal attribute
References Base::BaseExceptionFreeCADError, getNormal(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVector()
PyObject * MeshPointPy::staticCallback_getVector (PyObject * self, void * closure) static
getter callback for the Vector attribute
References Base::BaseExceptionFreeCADError, getVector(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getx()
PyObject * MeshPointPy::staticCallback_getx (PyObject * self, void * closure) static
getter callback for the x attribute
References Base::BaseExceptionFreeCADError, getx(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_gety()
PyObject * MeshPointPy::staticCallback_gety (PyObject * self, void * closure) static
getter callback for the y attribute
References Base::BaseExceptionFreeCADError, gety(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getz()
PyObject * MeshPointPy::staticCallback_getz (PyObject * self, void * closure) static
getter callback for the z attribute
References Base::BaseExceptionFreeCADError, getz(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_move()
PyObject * MeshPointPy::staticCallback_move (PyObject * self, PyObject * args) static
callback for the move() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), move(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_setBound()
int MeshPointPy::staticCallback_setBound (PyObject * self, PyObject * value, void * closure) static
setter callback for the Bound attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setIndex()
int MeshPointPy::staticCallback_setIndex (PyObject * self, PyObject * value, void * closure) static
setter callback for the Index attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setNormal()
int MeshPointPy::staticCallback_setNormal (PyObject * self, PyObject * value, void * closure) static
setter callback for the Normal attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setVector()
int MeshPointPy::staticCallback_setVector (PyObject * self, PyObject * value, void * closure) static
setter callback for the Vector attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setx()
int MeshPointPy::staticCallback_setx (PyObject * self, PyObject * value, void * closure) static
setter callback for the x attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setx().
staticCallback_sety()
int MeshPointPy::staticCallback_sety (PyObject * self, PyObject * value, void * closure) static
setter callback for the y attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and sety().
staticCallback_setz()
int MeshPointPy::staticCallback_setz (PyObject * self, PyObject * value, void * closure) static
setter callback for the z attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setz().
staticCallback_unbound()
PyObject * MeshPointPy::staticCallback_unbound (PyObject * self, PyObject * args) static
callback for the unbound() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and unbound().
unbound()
PyObject * MeshPointPy::unbound (PyObject * args)
implementer for the unbound() method
References getMeshPointPtr(), Mesh::MeshPoint::Index, and Mesh::MeshPoint::Mesh.
Referenced by staticCallback_unbound().
Member Data Documentation
GetterSetter
PyGetSetDef MeshPointPy::GetterSetter static
Attribute structure of MeshPointPy.
Methods
PyMethodDef MeshPointPy::Methods static
Initial value:
= {
    {"unbound",
        reinterpret_cast<PyCFunction>( staticCallback_unbound ),
        METH_VARARGS,
        " method unbound()\nCut the connection to a MeshObject. The point becomes\nfree and is more or less a simple vector/point.\nAfter calling unbound() no topological operation will\nwork!\n                        "
    },
    {"move",
        reinterpret_cast<PyCFunction>( staticCallback_move ),
        METH_VARARGS,
        "method move(Vector)\nThis method moves the point in the mesh along the \ngiven vector. This affects the geometry of the mesh.\nBe aware that after moving point(s) the mesh can \nhave self intersections!\n              "
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of MeshPointPy.
Type
PyTypeObject MeshPointPy::Type static
Type structure of MeshPointPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Mesh/App/MeshPointPy.h
Sources/FreeCAD/src/Mod/Mesh/App/MeshPointPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Mesh/App/MeshPointPy.cpp