FreeCAD: SMESHDS_GroupOnFilter Class Reference
SMESHDS_GroupOnFilter Class Reference
Groups whose contents is dynamically updated using the filter.
#include <SMESHDS_GroupOnFilter.hxx>
Public Member Functions
virtual bool Contains (const int theID)
Checks if the element belongs to the group.
virtual bool Contains (const SMDS_MeshElement *elem)
Checks if the element belongs to the group.
virtual int Extent () const
Returns nb of elements.
template<typename IDTYPE >
int GetElementIds (IDTYPE *ids) const
virtual SMDS_ElemIteratorPtr GetElements () const
Return iterator on all elements.
std::vector< int > GetMeshInfo () const
Return info on sub-types of elements.
SMESH_PredicatePtr GetPredicate () const
virtual VTK_MTIME_TYPE GetTic () const
Return a value allowing to find out if a group has changed or not.
virtual bool IsEmpty ()
Checks emptyness.
bool IsUpToDate () const
Return false if update() is needed.
void SetPredicate (const SMESH_PredicatePtr &thePredicate)
Sets a new predicate.
SMESHDS_GroupOnFilter (const int theID, const SMESHDS_Mesh *theMesh, const SMDSAbs_ElementType theType, const SMESH_PredicatePtr &thePredicate)
Public Member Functions inherited from SMESHDS_GroupBase
virtual bool Contains (const int theID)
virtual bool Contains (const SMDS_MeshElement *elem)
virtual int Extent () const
Quantity_Color GetColor () const
int GetColorGroup () const
virtual SMDS_ElemIteratorPtr GetElements () const =0
int GetID () const
virtual int GetID (const int theIndex)
const SMESHDS_Mesh * GetMesh () const
const char * GetStoreName () const
virtual VTK_MTIME_TYPE GetTic () const =0
SMDSAbs_ElementType GetType () const
virtual bool IsEmpty ()
void SetColor (const Quantity_Color &theColor)
void SetColorGroup (int theColorGroup)
void SetStoreName (const char *theName)
virtual void SetType (SMDSAbs_ElementType theType)
SMESHDS_GroupBase (const int theID, const SMESHDS_Mesh *theMesh, const SMDSAbs_ElementType theType)
virtual ~SMESHDS_GroupBase ()
Additional Inherited Members
Static Public Member Functions inherited from SMESHDS_GroupBase
static void SetDefaultColor (const Quantity_Color &theColor)
Protected Member Functions inherited from SMESHDS_GroupBase
const SMDS_MeshElement * findInMesh (const int theID) const
void resetIterator ()
Detailed Description
Groups whose contents is dynamically updated using the filter.
Constructor & Destructor Documentation
SMESHDS_GroupOnFilter()
SMESHDS_GroupOnFilter::SMESHDS_GroupOnFilter (const int theID, const SMESHDS_Mesh * theMesh, const SMDSAbs_ElementType theType, const SMESH_PredicatePtr & thePredicate)
Creates a group based on thePredicate
References SetPredicate().
Member Function Documentation
Contains() [1/2]
bool SMESHDS_GroupOnFilter::Contains (const int theID) virtual
Checks if the element belongs to the group.
Reimplemented from SMESHDS_GroupBase.
Contains() [2/2]
bool SMESHDS_GroupOnFilter::Contains (const SMDS_MeshElement * elem) virtual
Checks if the element belongs to the group.
Reimplemented from SMESHDS_GroupBase.
References SMDS_MeshElement::GetID().
Extent()
int SMESHDS_GroupOnFilter::Extent () const virtual
Returns nb of elements.
Reimplemented from SMESHDS_GroupBase.
Referenced by GetElements(), and IsEmpty().
GetElementIds()
template<typename IDTYPE > int SMESHDS_GroupOnFilter::GetElementIds (IDTYPE * ids) const
GetElements()
SMDS_ElemIteratorPtr SMESHDS_GroupOnFilter::GetElements () const virtual
Return iterator on all elements.
Implements SMESHDS_GroupBase.
References SMDS_Mesh::elementsIterator(), Extent(), SMESHDS_GroupBase::GetMesh(), SMDS_Mesh::GetMeshInfo(), SMESHDS_GroupBase::GetType(), IsUpToDate(), and SMDS_MeshInfo::NbElements().
Referenced by IsEmpty().
GetMeshInfo()
std::vector< int > SMESHDS_GroupOnFilter::GetMeshInfo () const
Return info on sub-types of elements.
GetPredicate()
SMESH_PredicatePtr SMESHDS_GroupOnFilter::GetPredicate () const
GetTic()
VTK_MTIME_TYPE SMESHDS_GroupOnFilter::GetTic () const virtual
Return a value allowing to find out if a group has changed or not.
Implements SMESHDS_GroupBase.
References SMESHDS_GroupBase::GetMesh(), and SMDS_Mesh::GetMTime().
IsEmpty()
bool SMESHDS_GroupOnFilter::IsEmpty () virtual
Checks emptyness.
Reimplemented from SMESHDS_GroupBase.
References Extent(), GetElements(), and IsUpToDate().
IsUpToDate()
bool SMESHDS_GroupOnFilter::IsUpToDate () const
Return false if update() is needed.
References SMESHDS_GroupBase::GetMesh(), and SMDS_Mesh::GetMTime().
Referenced by GetElements(), and IsEmpty().
SetPredicate()
void SMESHDS_GroupOnFilter::SetPredicate (const SMESH_PredicatePtr & thePredicate)
Sets a new predicate.
References SMESHDS_GroupBase::GetMesh().
Referenced by SMESHDS_GroupOnFilter().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESHDS_GroupOnFilter.hxx
FreeCAD/src/3rdParty/salomesmesh/src/SMESHDS/SMESHDS_GroupOnFilter.cpp