FreeCAD: StdMeshers_ShapeShapeBiDirectionMap Struct Reference
StdMeshers_ShapeShapeBiDirectionMap Struct Reference
Struct used instead of a sole TopTools_DataMapOfShapeShape to avoid problems with bidirectional bindings.
#include <StdMeshers_ProjectionUtils.hxx>
Public Types
enum EAssocType {
UNDEF , INIT_VERTEX , PROPAGATION , PARTNER ,
CLOSE_VERTEX , COMMON_VERTEX , FEW_EF
}
Public Member Functions
bool Bind (const TopoDS_Shape &s1, const TopoDS_Shape &s2)
void Clear ()
int Extent () const
bool IsBound (const TopoDS_Shape &s, const bool isShape2=false) const
bool IsEmpty () const
const TopoDS_Shape & operator() (const TopoDS_Shape &s, const bool isShape2=false) const
void SetAssocType (EAssocType type)
StdMeshers_ShapeShapeBiDirectionMap ()
Detailed Description
Struct used instead of a sole TopTools_DataMapOfShapeShape to avoid problems with bidirectional bindings.
Member Enumeration Documentation
EAssocType
enum StdMeshers_ShapeShapeBiDirectionMap::EAssocType
Enumerator
UNDEF
INIT_VERTEX
PROPAGATION
PARTNER
CLOSE_VERTEX
COMMON_VERTEX
FEW_EF
Constructor & Destructor Documentation
StdMeshers_ShapeShapeBiDirectionMap()
StdMeshers_ShapeShapeBiDirectionMap::StdMeshers_ShapeShapeBiDirectionMap ()
Member Function Documentation
Bind()
bool StdMeshers_ShapeShapeBiDirectionMap::Bind (const TopoDS_Shape & s1, const TopoDS_Shape & s2)
Referenced by StdMeshers_Projection_3D::Compute(), StdMeshers_ProjectionUtils::FindSubShapeAssociation(), and StdMeshers_ProjectionUtils::InsertAssociation().
Clear()
void StdMeshers_ShapeShapeBiDirectionMap::Clear ()
Referenced by StdMeshers_Projection_3D::Compute().
Extent()
int StdMeshers_ShapeShapeBiDirectionMap::Extent () const
Referenced by StdMeshers_RadialPrism_3D::Compute(), and StdMeshers_ProjectionUtils::FindSubShapeAssociation().
IsBound()
bool StdMeshers_ShapeShapeBiDirectionMap::IsBound (const TopoDS_Shape & s, const bool isShape2 = false) const
Referenced by StdMeshers_Projection_1D::Compute(), StdMeshers_Projection_2D::Compute(), StdMeshers_Projection_3D::Compute(), StdMeshers_RadialPrism_3D::Compute(), StdMeshers_Projection_1D::Evaluate(), StdMeshers_Projection_2D::Evaluate(), StdMeshers_ProjectionUtils::FindMatchingNodesOnFaces(), and StdMeshers_ProjectionUtils::FindSubShapeAssociation().
IsEmpty()
bool StdMeshers_ShapeShapeBiDirectionMap::IsEmpty () const
Referenced by StdMeshers_ProjectionUtils::FindSubShapeAssociation().
operator()()
const TopoDS_Shape& StdMeshers_ShapeShapeBiDirectionMap::operator() (const TopoDS_Shape & s, const bool isShape2 = false) const
SetAssocType()
void StdMeshers_ShapeShapeBiDirectionMap::SetAssocType (EAssocType type)
References UNDEF.
Referenced by StdMeshers_ProjectionUtils::FindSubShapeAssociation().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_ProjectionUtils.hxx