FreeCAD: ReenGui::FitBSplineSurfaceWidget Class Reference
ReenGui::FitBSplineSurfaceWidget Class Reference
#include <FitBSplineSurface.h>
Classes
class Private
Public Member Functions
bool accept ()
FitBSplineSurfaceWidget (const App::DocumentObjectT &, QWidget *parent=nullptr)
~FitBSplineSurfaceWidget ()
Constructor & Destructor Documentation
FitBSplineSurfaceWidget()
FitBSplineSurfaceWidget::FitBSplineSurfaceWidget (const App::DocumentObjectT & obj, QWidget * parent = nullptr)
References ReenGui::FitBSplineSurfaceWidget::Private::obj, ReenGui::Ui_FitBSplineSurface::setupUi(), and ReenGui::FitBSplineSurfaceWidget::Private::ui.
~FitBSplineSurfaceWidget()
FitBSplineSurfaceWidget::~FitBSplineSurfaceWidget ()
Member Function Documentation
accept()
bool FitBSplineSurfaceWidget::accept (void)
References Gui::Command::abortCommand(), Gui::Command::addModule(), Gui::Command::App, ReenGui::Ui_FitBSplineSurface::bending, Gui::Command::commitCommand(), ReenGui::Ui_FitBSplineSurface::curvature, ReenGui::Ui_FitBSplineSurface::degreeU, ReenGui::Ui_FitBSplineSurface::degreeV, Gui::Command::Doc, App::DocumentObjectT::getDocumentPython(), App::DocumentObjectT::getObjectPython(), Gui::SelectionSingleton::getObjectsOfType(), ReenGui::Ui_FitBSplineSurface::gradient, ReenGui::Ui_FitBSplineSurface::groupBoxSmooth, ReenGui::Ui_FitBSplineSurface::iterations, Base::Rotation::multVec(), ReenGui::FitBSplineSurfaceWidget::Private::obj, Gui::Command::openCommand(), ReenGui::Ui_FitBSplineSurface::polesU, ReenGui::Ui_FitBSplineSurface::polesV, draftutils.translate::QT_TRANSLATE_NOOP, Gui::Selection(), ReenGui::Ui_FitBSplineSurface::sizeFactor, ReenGui::Ui_FitBSplineSurface::totalWeight, ReenGui::FitBSplineSurfaceWidget::Private::ui, Gui::Command::updateActive(), ReenGui::Ui_FitBSplineSurface::uvdir, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by ReenGui::TaskFitBSplineSurface::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/ReverseEngineering/Gui/FitBSplineSurface.h
FreeCAD/src/Mod/ReverseEngineering/Gui/FitBSplineSurface.cpp