FreeCAD: nlohmann::detail::iteration_proxy_value< IteratorType > Class Template Reference
nlohmann::detail::iteration_proxy_value< IteratorType > Class Template Reference
#include <json.hpp>
Public Types
using difference_type = std::ptrdiff_t
using iterator_category = std::input_iterator_tag
using pointer = value_type *
using reference = value_type &
using string_type = typename std::remove_cv< typename std::remove_reference< decltype(std::declval< IteratorType >().key()) >::type >::type
using value_type = iteration_proxy_value
Public Member Functions
iteration_proxy_value (IteratorType it) noexcept
const string_type & key () const
return key of the iterator
bool operator!= (const iteration_proxy_value &o) const
inequality operator (needed for range-based for)
iteration_proxy_value & operator* ()
dereference operator (needed for range-based for)
iteration_proxy_value & operator++ ()
increment operator (needed for range-based for)
bool operator== (const iteration_proxy_value &o) const
equality operator (needed for InputIterator)
IteratorType::reference value () const
return value of the iterator
Member Typedef Documentation
difference_type
template<typename IteratorType > using nlohmann::detail::iteration_proxy_value< IteratorType >::difference_type = std::ptrdiff_t
iterator_category
template<typename IteratorType > using nlohmann::detail::iteration_proxy_value< IteratorType >::iterator_category = std::input_iterator_tag
pointer
template<typename IteratorType > using nlohmann::detail::iteration_proxy_value< IteratorType >::pointer = value_type *
reference
template<typename IteratorType > using nlohmann::detail::iteration_proxy_value< IteratorType >::reference = value_type &
string_type
template<typename IteratorType > using nlohmann::detail::iteration_proxy_value< IteratorType >::string_type = typename std::remove_cv< typename std::remove_reference<decltype(std::declval<IteratorType>().key()) >::type >::type
value_type
template<typename IteratorType > using nlohmann::detail::iteration_proxy_value< IteratorType >::value_type = iteration_proxy_value
Constructor & Destructor Documentation
iteration_proxy_value()
template<typename IteratorType > nlohmann::detail::iteration_proxy_value< IteratorType >::iteration_proxy_value (IteratorType it) explicit noexcept
Member Function Documentation
key()
template<typename IteratorType > const string_type & nlohmann::detail::iteration_proxy_value< IteratorType >::key () const
return key of the iterator
References nlohmann::detail::array, nlohmann::detail::int_to_string(), and nlohmann::detail::object.
Referenced by Mod.Show.SceneDetail.SceneDetail::full_key().
operator!=()
template<typename IteratorType > bool nlohmann::detail::iteration_proxy_value< IteratorType >::operator!= (const iteration_proxy_value< IteratorType > & o) const
inequality operator (needed for range-based for)
operator*()
template<typename IteratorType > iteration_proxy_value & nlohmann::detail::iteration_proxy_value< IteratorType >::operator* ()
dereference operator (needed for range-based for)
operator++()
template<typename IteratorType > iteration_proxy_value & nlohmann::detail::iteration_proxy_value< IteratorType >::operator++ ()
increment operator (needed for range-based for)
operator==()
template<typename IteratorType > bool nlohmann::detail::iteration_proxy_value< IteratorType >::operator== (const iteration_proxy_value< IteratorType > & o) const
equality operator (needed for InputIterator)
value()
template<typename IteratorType > IteratorType::reference nlohmann::detail::iteration_proxy_value< IteratorType >::value () const
return value of the iterator
Referenced by PathScripts.PathProperty.Property::displayString(), PathScripts.PathProperty.PropertyQuantity::displayString(), PathScripts.PathSetupSheetOpPrototype.Property::displayString(), PathScripts.PathSetupSheetOpPrototype.PropertyQuantity::displayString(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), PathScripts.PathProperty.Property::getValue(), PathScripts.PathSetupSheetOpPrototype.Property::getValue(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), PathScripts.PathProperty.Property::setValue(), and PathScripts.PathSetupSheetOpPrototype.Property::setValue().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/PartDesign/App/json.hpp