FreeCAD: SMESHDS_Mesh Class Reference
SMESHDS_Mesh Class Reference
#include <SMESHDS_Mesh.hxx>
Classes
class SubMeshHolder
Public Member Functions
virtual SMDS_Mesh0DElement * Add0DElement (const SMDS_MeshNode *node)
create a Mesh0DElement and add it to the current Mesh
virtual SMDS_Mesh0DElement * Add0DElementWithID (const SMDS_MeshNode *node, int ID)
Create a new Mesh0DElement and at it to the mesh.
virtual SMDS_Mesh0DElement * Add0DElementWithID (int nodeID, int ID)
create a Mesh0DElement and add it to the current Mesh
virtual SMDS_BallElement * AddBall (const SMDS_MeshNode *n, double diameter)
create a Ball and add it to the current Mesh
virtual SMDS_BallElement * AddBallWithID (const SMDS_MeshNode *n, double diameter, int ID)
Create a new Ball and at it to the mesh.
virtual SMDS_BallElement * AddBallWithID (int n, double diameter, int ID)
create a Ball and add it to the current Mesh
int AddCompoundSubmesh (const TopoDS_Shape &S, TopAbs_ShapeEnum type=TopAbs_SHAPE)
virtual SMDS_MeshEdge * AddEdge (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2)
create a MeshEdge and add it to the current Mesh
virtual SMDS_MeshEdge * AddEdge (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n12)
virtual SMDS_MeshEdge * AddEdgeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n12, int ID)
virtual SMDS_MeshEdge * AddEdgeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, int ID)
Create a new edge and at it to the mesh.
virtual SMDS_MeshEdge * AddEdgeWithID (int n1, int n2, int ID)
create a MeshEdge and add it to the current Mesh
virtual SMDS_MeshEdge * AddEdgeWithID (int n1, int n2, int n12, int ID)
virtual SMDS_MeshFace * AddFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3)
Add a triangle defined by its nodes.
virtual SMDS_MeshFace * AddFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n31)
virtual SMDS_MeshFace * AddFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n31, const SMDS_MeshNode *nCenter)
virtual SMDS_MeshFace * AddFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4)
Add a quadrangle defined by its nodes.
virtual SMDS_MeshFace * AddFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41)
virtual SMDS_MeshFace * AddFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, const SMDS_MeshNode *nCenter)
virtual SMDS_MeshFace * AddFaceWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n31, const SMDS_MeshNode *nCenter, int ID)
virtual SMDS_MeshFace * AddFaceWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n31, int ID)
virtual SMDS_MeshFace * AddFaceWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, const SMDS_MeshNode *nCenter, int ID)
virtual SMDS_MeshFace * AddFaceWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, int ID)
virtual SMDS_MeshFace * AddFaceWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, int ID)
Add a quadrangle defined by its nodes.
virtual SMDS_MeshFace * AddFaceWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, int ID)
Add a triangle defined by its nodes.
virtual SMDS_MeshFace * AddFaceWithID (int n1, int n2, int n3, int ID)
Add a triangle defined by its nodes IDs.
virtual SMDS_MeshFace * AddFaceWithID (int n1, int n2, int n3, int n12, int n23, int n31, int ID)
virtual SMDS_MeshFace * AddFaceWithID (int n1, int n2, int n3, int n12, int n23, int n31, int nCenter, int ID)
virtual SMDS_MeshFace * AddFaceWithID (int n1, int n2, int n3, int n4, int ID)
Add a quadrangle defined by its nodes IDs.
virtual SMDS_MeshFace * AddFaceWithID (int n1, int n2, int n3, int n4, int n12, int n23, int n34, int n41, int ID)
virtual SMDS_MeshFace * AddFaceWithID (int n1, int n2, int n3, int n4, int n12, int n23, int n34, int n41, int nCenter, int ID)
void AddGroup (SMESHDS_GroupBase *theGroup)
bool AddHypothesis (const TopoDS_Shape &SS, const SMESHDS_Hypothesis *H)
virtual SMDS_MeshNode * AddNode (double x, double y, double z)
create a MeshNode and add it to the current Mesh An ID is automatically assigned to the node.
virtual SMDS_MeshNode * AddNodeWithID (double x, double y, double z, int ID)
create a MeshNode and add it to the current Mesh
virtual SMDS_MeshFace * AddPolygonalFace (const std::vector< const SMDS_MeshNode * > &nodes)
Add a polygon defined by its nodes.
virtual SMDS_MeshFace * AddPolygonalFaceWithID (const std::vector< const SMDS_MeshNode * > &nodes, const int ID)
Add a polygon defined by its nodes.
virtual SMDS_MeshFace * AddPolygonalFaceWithID (const std::vector< int > &nodes_ids, const int ID)
Add a polygon defined by its nodes IDs.
virtual SMDS_MeshVolume * AddPolyhedralVolume (const std::vector< const SMDS_MeshNode * > &nodes, const std::vector< int > &quantities)
Create a new polyhedral volume and add it to the mesh.
virtual SMDS_MeshVolume * AddPolyhedralVolumeWithID (const std::vector< const SMDS_MeshNode * > &nodes, const std::vector< int > &quantities, const int ID)
Create a new polyhedral volume and add it to the mesh.
virtual SMDS_MeshVolume * AddPolyhedralVolumeWithID (const std::vector< int > &nodes_ids, const std::vector< int > &quantities, const int ID)
Create a new polyhedral volume and add it to the mesh.
virtual SMDS_MeshFace * AddQuadPolygonalFace (const std::vector< const SMDS_MeshNode * > &nodes)
Add a quadratic polygon defined by its nodes.
virtual SMDS_MeshFace * AddQuadPolygonalFaceWithID (const std::vector< const SMDS_MeshNode * > &nodes, const int ID)
Add a quadratic polygon defined by its nodes.
virtual SMDS_MeshFace * AddQuadPolygonalFaceWithID (const std::vector< int > &nodes_ids, const int ID)
Add a quadratic polygon defined by its nodes IDs.
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4)
Create a new tetrahedron and add it to the mesh.
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n31, const SMDS_MeshNode *n14, const SMDS_MeshNode *n24, const SMDS_MeshNode *n34)
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5)
Create a new pyramid and add it to the mesh.
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, const SMDS_MeshNode *n15, const SMDS_MeshNode *n25, const SMDS_MeshNode *n35, const SMDS_MeshNode *n45)
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6)
Create a new prism and add it to the mesh.
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n31, const SMDS_MeshNode *n45, const SMDS_MeshNode *n56, const SMDS_MeshNode *n64, const SMDS_MeshNode *n14, const SMDS_MeshNode *n25, const SMDS_MeshNode *n36)
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8)
Create a new hexahedron and add it to the mesh.
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, const SMDS_MeshNode *n56, const SMDS_MeshNode *n67, const SMDS_MeshNode *n78, const SMDS_MeshNode *n85, const SMDS_MeshNode *n15, const SMDS_MeshNode *n26, const SMDS_MeshNode *n37, const SMDS_MeshNode *n48)
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, const SMDS_MeshNode *n56, const SMDS_MeshNode *n67, const SMDS_MeshNode *n78, const SMDS_MeshNode *n85, const SMDS_MeshNode *n15, const SMDS_MeshNode *n26, const SMDS_MeshNode *n37, const SMDS_MeshNode *n48, const SMDS_MeshNode *n1234, const SMDS_MeshNode *n1256, const SMDS_MeshNode *n2367, const SMDS_MeshNode *n3478, const SMDS_MeshNode *n1458, const SMDS_MeshNode *n5678, const SMDS_MeshNode *nCenter)
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8, const SMDS_MeshNode *n9, const SMDS_MeshNode *n10, const SMDS_MeshNode *n11, const SMDS_MeshNode *n12)
Create a new hexagonal prism and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n31, const SMDS_MeshNode *n14, const SMDS_MeshNode *n24, const SMDS_MeshNode *n34, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, const SMDS_MeshNode *n15, const SMDS_MeshNode *n25, const SMDS_MeshNode *n35, const SMDS_MeshNode *n45, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n31, const SMDS_MeshNode *n45, const SMDS_MeshNode *n56, const SMDS_MeshNode *n64, const SMDS_MeshNode *n14, const SMDS_MeshNode *n25, const SMDS_MeshNode *n36, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, const SMDS_MeshNode *n56, const SMDS_MeshNode *n67, const SMDS_MeshNode *n78, const SMDS_MeshNode *n85, const SMDS_MeshNode *n15, const SMDS_MeshNode *n26, const SMDS_MeshNode *n37, const SMDS_MeshNode *n48, const SMDS_MeshNode *n1234, const SMDS_MeshNode *n1256, const SMDS_MeshNode *n2367, const SMDS_MeshNode *n3478, const SMDS_MeshNode *n1458, const SMDS_MeshNode *n5678, const SMDS_MeshNode *nCenter, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8, const SMDS_MeshNode *n12, const SMDS_MeshNode *n23, const SMDS_MeshNode *n34, const SMDS_MeshNode *n41, const SMDS_MeshNode *n56, const SMDS_MeshNode *n67, const SMDS_MeshNode *n78, const SMDS_MeshNode *n85, const SMDS_MeshNode *n15, const SMDS_MeshNode *n26, const SMDS_MeshNode *n37, const SMDS_MeshNode *n48, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8, const SMDS_MeshNode *n9, const SMDS_MeshNode *n10, const SMDS_MeshNode *n11, const SMDS_MeshNode *n12, int ID)
Create a new hexagonal prism and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8, int ID)
Create a new hexahedron and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, int ID)
Create a new prism and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, int ID)
Create a new pyramid and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, int ID)
Create a new tetrahedron and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int ID)
Create a new tetrahedron and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n12, int n23, int n31, int n14, int n24, int n34, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int ID)
Create a new pyramid and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n12, int n23, int n34, int n41, int n15, int n25, int n35, int n45, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int ID)
Create a new prism and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int n12, int n23, int n31, int n45, int n56, int n64, int n14, int n25, int n36, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int ID)
Create a new hexahedron and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n12, int n23, int n34, int n41, int n56, int n67, int n78, int n85, int n15, int n26, int n37, int n48, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n12, int n23, int n34, int n41, int n56, int n67, int n78, int n85, int n15, int n26, int n37, int n48, int n1234, int n1256, int n2367, int n3478, int n1458, int n5678, int nCenter, int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n9, int n10, int n11, int n12, int ID)
Create a new hexagonal prism and add it to the mesh.
void BuildDownWardConnectivity (bool withEdges)
bool ChangeElementNodes (const SMDS_MeshElement *elem, const SMDS_MeshNode *nodes[], const int nbnodes)
bool ChangePolygonNodes (const SMDS_MeshElement *elem, std::vector< const SMDS_MeshNode * > nodes)
bool ChangePolyhedronNodes (const SMDS_MeshElement *elem, std::vector< const SMDS_MeshNode * > nodes, std::vector< int > quantities)
void CleanDownWardConnectivity ()
void ClearMesh ()
Remove all data from the mesh.
void ClearScript ()
virtual void compactMesh ()
const std::set< SMESHDS_GroupBase * > & GetGroups () const
const ShapeToHypothesis & GetHypotheses () const
const std::list< const SMESHDS_Hypothesis * > & GetHypothesis (const TopoDS_Shape &S) const
int GetNbGroups () const
int GetPersistentId () const
Return ID persistent during lifecycle.
SMESHDS_Script * GetScript ()
bool HasHypothesis (const TopoDS_Shape &S)
bool HasMeshElements (const TopoDS_Shape &S) const
const TopoDS_Shape & IndexToShape (int ShapeIndex) const
bool IsEmbeddedMode ()
bool IsGroupOfSubShapes (const TopoDS_Shape &aSubShape) const
bool IsUsedHypothesis (const SMESHDS_Hypothesis *H) const
returns true if the hypothesis is assigned to any sub-shape
int MaxShapeIndex () const
int MaxSubMeshIndex () const
Return max index of sub-mesh.
SMESHDS_SubMesh * MeshElements (const int Index) const
Return the sub mesh by Id of shape it is linked to.
SMESHDS_SubMesh * MeshElements (const TopoDS_Shape &S) const
Return the sub mesh linked to the a given TopoDS_Shape or NULL if the given TopoDS_Shape is unknown.
bool ModifyCellNodes (int smdsVolId, std::map< int, int > localClonedNodeIds)
virtual void MoveNode (const SMDS_MeshNode *, double x, double y, double z)
SMESHDS_SubMesh * NewSubMesh (int Index)
void RemoveElement (const SMDS_MeshElement *)
void RemoveFreeElement (const SMDS_MeshElement *, SMESHDS_SubMesh *, bool fromGroups=true)
void RemoveFreeNode (const SMDS_MeshNode *, SMESHDS_SubMesh *, bool fromGroups=true)
void RemoveGroup (SMESHDS_GroupBase *theGroup)
bool RemoveHypothesis (const TopoDS_Shape &S, const SMESHDS_Hypothesis *H)
virtual void RemoveNode (const SMDS_MeshNode *)
Remove a node and all the elements which own this node.
void Renumber (const bool isNodes, const int startID=1, const int deltaID=1)
void SetMeshElementOnShape (const SMDS_MeshElement *anElt, const TopoDS_Shape &S)
void SetMeshElementOnShape (const SMDS_MeshElement *anElt, int Index)
void SetNodeInVolume (const SMDS_MeshNode *aNode, const TopoDS_Shell &S)
void SetNodeInVolume (const SMDS_MeshNode *aNode, const TopoDS_Solid &S)
void SetNodeInVolume (const SMDS_MeshNode *aNode, int Index)
void SetNodeOnEdge (const SMDS_MeshNode *aNode, const TopoDS_Edge &S, double u=0.)
void SetNodeOnEdge (const SMDS_MeshNode *aNode, int Index, double u=0.)
void SetNodeOnFace (const SMDS_MeshNode *aNode, const TopoDS_Face &S, double u=0., double v=0.)
void SetNodeOnFace (const SMDS_MeshNode *aNode, int Index, double u=0., double v=0.)
void SetNodeOnVertex (const SMDS_MeshNode *aNode, const TopoDS_Vertex &S)
void SetNodeOnVertex (const SMDS_MeshNode *aNode, int Index)
void SetPersistentId (int id)
Store ID persistent during lifecycle.
int ShapeToIndex (const TopoDS_Shape &aShape) const
TopoDS_Shape ShapeToMesh () const
void ShapeToMesh (const TopoDS_Shape &S)
SMESHDS_Mesh (int theMeshID, bool theIsEmbeddedMode)
SMESHDS_SubMeshIteratorPtr SubMeshes () const
std::list< int > SubMeshIndices () const
void UnSetMeshElementOnShape (const SMDS_MeshElement *anElt, const TopoDS_Shape &S)
void UnSetNodeOnShape (const SMDS_MeshNode *aNode)
~SMESHDS_Mesh ()
Public Member Functions inherited from SMDS_Mesh
virtual SMDS_MeshFace * AddFace (const SMDS_MeshEdge *e1, const SMDS_MeshEdge *e2, const SMDS_MeshEdge *e3)
Add a triangle defined by its edges.
virtual SMDS_MeshFace * AddFace (const SMDS_MeshEdge *e1, const SMDS_MeshEdge *e2, const SMDS_MeshEdge *e3, const SMDS_MeshEdge *e4)
Add a quadrangle defined by its edges.
virtual SMDS_MeshFace * AddFaceFromVtkIds (const std::vector< vtkIdType > &vtkNodeIds)
virtual SMDS_MeshFace * AddFaceFromVtkIdsWithID (const std::vector< vtkIdType > &vtkNodeIds, const int ID)
virtual SMDS_MeshFace * AddFaceWithID (const SMDS_MeshEdge *e1, const SMDS_MeshEdge *e2, const SMDS_MeshEdge *e3, const SMDS_MeshEdge *e4, int ID)
Add a quadrangle defined by its edges.
virtual SMDS_MeshFace * AddFaceWithID (const SMDS_MeshEdge *e1, const SMDS_MeshEdge *e2, const SMDS_MeshEdge *e3, int ID)
Add a triangle defined by its edges.
SMDS_Mesh * AddSubMesh ()
Create a submesh and add it to the current mesh.
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshFace *f1, const SMDS_MeshFace *f2, const SMDS_MeshFace *f3, const SMDS_MeshFace *f4)
Create a new tetrahedron defined by its faces and add it to the mesh.
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshFace *f1, const SMDS_MeshFace *f2, const SMDS_MeshFace *f3, const SMDS_MeshFace *f4, const SMDS_MeshFace *f5)
Create a new pyramid defined by its faces and add it to the mesh.
virtual SMDS_MeshVolume * AddVolume (const SMDS_MeshFace *f1, const SMDS_MeshFace *f2, const SMDS_MeshFace *f3, const SMDS_MeshFace *f4, const SMDS_MeshFace *f5, const SMDS_MeshFace *f6)
Create a new prism defined by its faces and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeFromVtkIds (const std::vector< vtkIdType > &vtkNodeIds)
virtual SMDS_MeshVolume * AddVolumeFromVtkIdsWithID (const std::vector< vtkIdType > &vtkNodeIds, const int ID)
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshFace *f1, const SMDS_MeshFace *f2, const SMDS_MeshFace *f3, const SMDS_MeshFace *f4, const SMDS_MeshFace *f5, const SMDS_MeshFace *f6, int ID)
Create a new prism defined by its faces and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshFace *f1, const SMDS_MeshFace *f2, const SMDS_MeshFace *f3, const SMDS_MeshFace *f4, const SMDS_MeshFace *f5, int ID)
Create a new pyramid defined by its faces and add it to the mesh.
virtual SMDS_MeshVolume * AddVolumeWithID (const SMDS_MeshFace *f1, const SMDS_MeshFace *f2, const SMDS_MeshFace *f3, const SMDS_MeshFace *f4, int ID)
Create a new tetrahedron defined by its faces and add it to the mesh.
void adjustStructure ()
bool ChangeElementNodes (const SMDS_MeshElement *elem, const SMDS_MeshNode *nodes[], const int nbnodes)
bool ChangePolyhedronNodes (const SMDS_MeshElement *elem, const std::vector< const SMDS_MeshNode * > &nodes, const std::vector< int > &quantities)
virtual void Clear ()
Clear all data.
bool Contains (const SMDS_MeshElement *elem) const
void DebugStats () const
void Dump0DElements () const
void DumpEdges () const
void DumpFaces () const
void dumpGrid (string ficdump="dumpGrid")
void DumpNodes () const
void DumpVolumes () const
virtual SMDS_EdgeIteratorPtr edgesIterator (bool idInceasingOrder=false) const
Return an iterator on edges of the current mesh.
virtual SMDS_ElemIteratorPtr elementEntityIterator (SMDSAbs_EntityType type) const
virtual SMDS_ElemIteratorPtr elementGeomIterator (SMDSAbs_GeometryType type) const
virtual SMDS_ElemIteratorPtr elementsIterator (SMDSAbs_ElementType type=SMDSAbs_All) const
Return an iterator on elements of the current mesh factory.
virtual SMDS_FaceIteratorPtr facesIterator (bool idInceasingOrder=false) const
Return an iterator on faces of the current mesh.
const SMDS_Mesh0DElement * Find0DElement (int idnode) const
const SMDS_BallElement * FindBall (int idnode) const
const SMDS_MeshEdge * FindEdge (int idnode1, int idnode2) const
const SMDS_MeshEdge * FindEdge (int idnode1, int idnode2, int idnode3) const
const SMDS_MeshElement * FindElement (int IDelem) const
const SMDS_MeshFace * FindFace (const std::vector< int > &nodes_ids) const
const SMDS_MeshFace * FindFace (int idnode1, int idnode2, int idnode3) const
const SMDS_MeshFace * FindFace (int idnode1, int idnode2, int idnode3, int idnode4) const
const SMDS_MeshFace * FindFace (int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6) const
const SMDS_MeshFace * FindFace (int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6, int idnode7, int idnode8) const
const SMDS_MeshNode * FindNode (int idnode) const
Return the node whose SMDS ID is 'ID'.
const SMDS_MeshNode * FindNodeVtk (int idnode) const
Return the node whose VTK ID is 'vtkId'.
int fromVtkToSmds (int vtkid)
SMDSAbs_ElementType GetElementType (const int id, const bool iselem) const
SMDS_UnstructuredGrid * getGrid ()
actual nodes coordinates, cells definition and reverse connectivity are stored in a vtkUnstructuredGrid
double getMaxDim ()
int getMeshId ()
const SMDS_MeshInfo & GetMeshInfo () const
VTK_MTIME_TYPE GetMTime () const
get last modification timeStamp
bool hasConstructionEdges ()
Return true if this mesh create faces with edges.
bool hasConstructionFaces ()
Return true if this mesh create volumes with faces A false returned value mean that volumes are created with nodes or edges.
bool hasInverseElements ()
Return true if nodes are linked to the finit elements, they are belonging to.
void incrementCellsCapacity (int nbCells)
void incrementNodesCapacity (int nbNodes)
bool isCompacted ()
int MaxElementID () const
int MaxNodeID () const
int MinElementID () const
int MinNodeID () const
void Modified ()
modification that needs compact structure and redraw
virtual int Nb0DElements () const
Return the number of 0D elements.
virtual int NbBalls () const
Return the number of 0D elements.
virtual int NbEdges () const
Return the number of edges (including construction edges)
virtual int NbFaces () const
Return the number of faces (including construction faces)
virtual int NbNodes () const
Return the number of nodes.
virtual int NbSubMesh () const
Return the number of child mesh of this mesh.
virtual int NbVolumes () const
Return the number of volumes.
virtual SMDS_NodeIteratorPtr nodesIterator (bool idInceasingOrder=false) const
Return an iterator on nodes of the current mesh factory.
virtual void Remove0DElement (const SMDS_Mesh0DElement *elem0d)
Remove an edge and all the elements which own this edge.
virtual void RemoveEdge (const SMDS_MeshEdge *edge)
Remove an edge and all the elements which own this edge.
virtual void RemoveElement (const SMDS_MeshElement *elem, bool removenodes=false)
virtual void RemoveElement (const SMDS_MeshElement *elem, std::list< const SMDS_MeshElement * > &removedElems, std::list< const SMDS_MeshElement * > &removedNodes, const bool removenodes=false)
virtual void RemoveFace (const SMDS_MeshFace *face)
Remove an face and all the elements which own this face.
virtual void RemoveFreeElement (const SMDS_MeshElement *elem)
virtual bool RemoveFromParent ()
virtual bool RemoveSubMesh (const SMDS_Mesh *aMesh)
virtual void RemoveVolume (const SMDS_MeshVolume *volume)
Remove a volume.
void setConstructionEdges (bool)
Make this mesh creating construction edges (see hasConstructionEdges)
void setConstructionFaces (bool)
Make this mesh creating construction faces (see hasConstructionFaces)
void setInverseElements (bool)
Make this mesh creating link from nodes to elements (see hasInverseElements)
void setMyModified ()
low level modification: add, change or remove node or element
SMDS_Mesh ()
Create a new mesh object.
void updateBoundingBox ()
void updateNodeMinMax ()
virtual SMDS_VolumeIteratorPtr volumesIterator (bool idInceasingOrder=false) const
Return an iterator on volumes of the current mesh.
virtual ~SMDS_Mesh ()
Destroy the mesh and all its elements All pointer on elements owned by this mesh become illegals.
Public Member Functions inherited from SMDS_MeshObject
virtual ~SMDS_MeshObject ()
Additional Inherited Members
Public Types inherited from SMDS_Mesh
typedef std::vector< SMDS_MeshCell * > SetOfCells
typedef std::vector< SMDS_MeshNode * > SetOfNodes
Static Public Member Functions inherited from SMDS_Mesh
static int CheckMemory (const bool doNotRaise=false)
Raise an exception if free memory (ram+swap) too low.
static const SMDS_Mesh0DElement * Find0DElement (const SMDS_MeshNode *n)
static const SMDS_BallElement * FindBall (const SMDS_MeshNode *n)
static const SMDS_MeshEdge * FindEdge (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2)
static const SMDS_MeshEdge * FindEdge (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3)
static const SMDS_MeshElement * FindElement (const std::vector< const SMDS_MeshNode * > &nodes, const SMDSAbs_ElementType type=SMDSAbs_All, const bool noMedium=true)
Return element based on all given nodes.
static const SMDS_MeshFace * FindFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3)
static const SMDS_MeshFace * FindFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4)
static const SMDS_MeshFace * FindFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6)
static const SMDS_MeshFace * FindFace (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4, const SMDS_MeshNode *n5, const SMDS_MeshNode *n6, const SMDS_MeshNode *n7, const SMDS_MeshNode *n8)
static const SMDS_MeshFace * FindFace (const std::vector< const SMDS_MeshNode * > &nodes)
Static Public Attributes inherited from SMDS_Mesh
static int chunkSize = 1024
Protected Member Functions inherited from SMDS_Mesh
void addChildrenWithNodes (std::set< const SMDS_MeshElement * > &setOfChildren, const SMDS_MeshElement *element, std::set< const SMDS_MeshElement * > &nodes)
Find the children of an element that are made of given nodes.
void adjustBoundingBox (double x, double y, double z)
void adjustmyCellsCapacity (int ID)
SMDS_MeshFace * createQuadrangle (const SMDS_MeshNode *node1, const SMDS_MeshNode *node2, const SMDS_MeshNode *node3, const SMDS_MeshNode *node4, int ID)
Create a quadrangle and add it to the current mesh.
SMDS_MeshFace * createTriangle (const SMDS_MeshNode *node1, const SMDS_MeshNode *node2, const SMDS_MeshNode *node3, int ID)
Create a triangle and add it to the current mesh.
SMDS_MeshEdge * FindEdgeOrCreate (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2)
SMDS_MeshFace * FindFaceOrCreate (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3)
SMDS_MeshFace * FindFaceOrCreate (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2, const SMDS_MeshNode *n3, const SMDS_MeshNode *n4)
bool registerElement (int ID, SMDS_MeshElement *element)
Registers element with the given ID, maintains inverse connections.
SMDS_Mesh (SMDS_Mesh *parent)
Create a new child mesh Note that the tree structure of SMDS_Mesh seems to be unused in this version (2003-09-08) of SMESH.
Protected Attributes inherited from SMDS_Mesh
ObjectPool< SMDS_BallElement > * myBallPool
std::vector< int > myCellIdVtkToSmds
for cells only: index = ID in vtkUnstructuredGrid, value = ID for SMDS users
SetOfCells myCells
SMDS_MeshCells refer to vtk cells (vtk id != index in myCells),store reference to this mesh, and sub-shape.
std::list< SMDS_Mesh * > myChildren
unsigned long myCompactTime
ObjectPool< SMDS_VtkEdge > * myEdgePool
SMDS_MeshElementIDFactory * myElementIDFactory
ObjectPool< SMDS_VtkFace > * myFacePool
SMDS_UnstructuredGrid * myGrid
actual nodes coordinates, cells definition and reverse connectivity are stored in a vtkUnstructuredGrid
bool myHasConstructionEdges
bool myHasConstructionFaces
bool myHasInverseElements
SMDS_MeshInfo myInfo
int myMeshId
index of this SMDS_mesh in the static vector<SMDS_Mesh*> _meshList
bool myModified
any add, remove or change of node or cell
unsigned long myModifTime
use a counter to keep track of modifications
SMDS_MeshNodeIDFactory * myNodeIDFactory
std::vector< vtkIdType > myNodeIds
a buffer to speed up elements addition by excluding some memory allocation
int myNodeMax
int myNodeMin
ObjectPool< SMDS_MeshNode > * myNodePool
Small objects like SMDS_MeshNode are allocated by chunks to limit memory costs of new.
SetOfNodes myNodes
SMDS_MeshNodes refer to vtk nodes (vtk id = index in myNodes),store reference to this mesh, and sub-shape.
SMDS_Mesh * myParent
ObjectPool< SMDS_VtkVolume > * myVolumePool
Small objects like SMDS_VtkVolume are allocated by chunks to limit memory costs of new.
double xmax
double xmin
double ymax
double ymin
double zmax
double zmin
Constructor & Destructor Documentation
SMESHDS_Mesh()
SMESHDS_Mesh::SMESHDS_Mesh (int theMeshID, bool theIsEmbeddedMode)
References SetPersistentId().
~SMESHDS_Mesh()
SMESHDS_Mesh::~SMESHDS_Mesh ()
Member Function Documentation
Add0DElement()
SMDS_Mesh0DElement * SMESHDS_Mesh::Add0DElement (const SMDS_MeshNode * node) virtual
create a Mesh0DElement and add it to the current Mesh
Returns
: The created Mesh0DElement
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::Add0DElement(), SMESHDS_Script::Add0DElement(), and SMDS_MeshElement::GetID().
Add0DElementWithID() [1/2]
SMDS_Mesh0DElement * SMESHDS_Mesh::Add0DElementWithID (const SMDS_MeshNode * n, int ID) virtual
Create a new Mesh0DElement and at it to the mesh.
Parameters
idnode ID of the node
ID ID of the 0D element to create
Returns
The created 0D element or NULL if an element with this ID already exists or if input node is not found.
Reimplemented from SMDS_Mesh.
References Add0DElementWithID(), and SMDS_MeshElement::GetID().
Add0DElementWithID() [2/2]
SMDS_Mesh0DElement * SMESHDS_Mesh::Add0DElementWithID (int idnode, int ID) virtual
create a Mesh0DElement and add it to the current Mesh
Returns
: The created Mesh0DElement
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::Add0DElement(), and SMDS_Mesh::Add0DElementWithID().
Referenced by Add0DElementWithID().
AddBall()
SMDS_BallElement * SMESHDS_Mesh::AddBall (const SMDS_MeshNode * node, double diameter) virtual
create a Ball and add it to the current Mesh
Returns
: The created Ball
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddBall(), SMESHDS_Script::AddBall(), and SMDS_MeshElement::GetID().
AddBallWithID() [1/2]
SMDS_BallElement * SMESHDS_Mesh::AddBallWithID (const SMDS_MeshNode * n, double diameter, int ID) virtual
Create a new Ball and at it to the mesh.
Parameters
idnode ID of the node
ID ID of the 0D element to create
Returns
The created 0D element or NULL if an element with this ID already exists or if input node is not found.
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddBall(), SMDS_Mesh::AddBallWithID(), and SMDS_MeshElement::GetID().
AddBallWithID() [2/2]
SMDS_BallElement * SMESHDS_Mesh::AddBallWithID (int idnode, double diameter, int ID) virtual
create a Ball and add it to the current Mesh
Returns
: The created Ball
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddBall(), SMDS_Mesh::AddBallWithID(), and SMDS_MeshElement::GetID().
AddCompoundSubmesh()
int SMESHDS_Mesh::AddCompoundSubmesh (const TopoDS_Shape & S, TopAbs_ShapeEnum type = TopAbs_SHAPE)
References SMESHDS_SubMesh::AddSubMesh(), SMESHDS_SubMesh::IsComplexSubmesh(), IsGroupOfSubShapes(), and NewSubMesh().
Referenced by SMESHDS_GroupOnGeom::SetShape().
AddEdge() [1/2]
SMDS_MeshEdge * SMESHDS_Mesh::AddEdge (const SMDS_MeshNode * node1, const SMDS_MeshNode * node2) virtual
create a MeshEdge and add it to the current Mesh
Returns
: The created MeshEdge
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddEdge(), SMESHDS_Script::AddEdge(), and SMDS_MeshElement::GetID().
Referenced by SMESH_MesherHelper::AddEdge(), Fem::FemMeshPy::addEdge(), StdMeshers_CompositeSegment_1D::Compute(), StdMeshers_Import_1D::Compute(), StdMeshers_Import_1D2D::Compute(), StdMeshers_Projection_1D::Compute(), StdMeshers_Projection_1D2D::Compute(), StdMeshers_Regular_1D::Compute(), NETGENPlugin_Mesher::FillSMesh(), and SMESH_MeshEditor::InsertNodesIntoLink().
AddEdge() [2/2]
SMDS_MeshEdge * SMESHDS_Mesh::AddEdge (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n12) virtual
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddEdge(), SMESHDS_Script::AddEdge(), and SMDS_MeshElement::GetID().
AddEdgeWithID() [1/4]
SMDS_MeshEdge * SMESHDS_Mesh::AddEdgeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n12, int ID) virtual
Reimplemented from SMDS_Mesh.
References AddEdgeWithID(), and SMDS_MeshElement::GetID().
AddEdgeWithID() [2/4]
SMDS_MeshEdge * SMESHDS_Mesh::AddEdgeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, int ID) virtual
Create a new edge and at it to the mesh.
Parameters
idnode1 ID of the first node
idnode2 ID of the second node
ID ID of the edge to create
Returns
The created edge or NULL if an element with this ID already exists or if input nodes are not found.
Reimplemented from SMDS_Mesh.
References AddEdgeWithID(), and SMDS_MeshElement::GetID().
AddEdgeWithID() [3/4]
SMDS_MeshEdge * SMESHDS_Mesh::AddEdgeWithID (int idnode1, int idnode2, int ID) virtual
create a MeshEdge and add it to the current Mesh
Returns
: The created MeshEdge
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddEdge(), and SMDS_Mesh::AddEdgeWithID().
Referenced by SMESH_MesherHelper::AddEdge(), Fem::FemMeshPy::addEdge(), AddEdgeWithID(), DriverMED::buildMeshGrille(), and DriverGMF_Read::Perform().
AddEdgeWithID() [4/4]
SMDS_MeshEdge * SMESHDS_Mesh::AddEdgeWithID (int n1, int n2, int n12, int ID) virtual
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddEdge(), and SMDS_Mesh::AddEdgeWithID().
AddFace() [1/6]
SMDS_MeshFace * SMESHDS_Mesh::AddFace (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3) virtual
Add a triangle defined by its nodes.
An ID is automatically affected to the Created face
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddFace(), SMESHDS_Script::AddFace(), and SMDS_MeshElement::GetID().
Referenced by SMESH_MesherHelper::AddFace(), Fem::FemMeshPy::addFace(), Fem::FemMeshPy::addQuad(), StdMeshers_Import_1D2D::Compute(), StdMeshers_QuadToTriaAdaptor::Compute(), SMESH_MeshEditor::DeleteDiag(), NETGENPlugin_Mesher::FillSMesh(), SMESH_MeshEditor::InsertNodesIntoLink(), SMESH_MeshEditor::QuadToTri(), SMESH_MeshEditor::SewSideElements(), and SMESH_MeshEditor::TriToQuad().
AddFace() [2/6]
SMDS_MeshFace * SMESHDS_Mesh::AddFace (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n31) virtual
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddFace(), SMESHDS_Script::AddFace(), and SMDS_MeshElement::GetID().
AddFace() [3/6]
SMDS_MeshFace * SMESHDS_Mesh::AddFace (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n31, const SMDS_MeshNode * nCenter) virtual
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddFace(), SMESHDS_Script::AddFace(), and SMDS_MeshElement::GetID().
AddFace() [4/6]
SMDS_MeshFace * SMESHDS_Mesh::AddFace (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4) virtual
Add a quadrangle defined by its nodes.
An ID is automatically affected to the created face
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddFace(), SMESHDS_Script::AddFace(), and SMDS_MeshElement::GetID().
AddFace() [5/6]
SMDS_MeshFace * SMESHDS_Mesh::AddFace (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41) virtual
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddFace(), SMESHDS_Script::AddFace(), and SMDS_MeshElement::GetID().
AddFace() [6/6]
SMDS_MeshFace * SMESHDS_Mesh::AddFace (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, const SMDS_MeshNode * nCenter) virtual
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddFace(), SMESHDS_Script::AddFace(), and SMDS_MeshElement::GetID().
AddFaceWithID() [1/12]
SMDS_MeshFace * SMESHDS_Mesh::AddFaceWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n31, const SMDS_MeshNode * nCenter, int ID) virtual
Reimplemented from SMDS_Mesh.
References AddFaceWithID(), and SMDS_MeshElement::GetID().
AddFaceWithID() [2/12]
SMDS_MeshFace * SMESHDS_Mesh::AddFaceWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n31, int ID) virtual
Reimplemented from SMDS_Mesh.
References AddFaceWithID(), and SMDS_MeshElement::GetID().
AddFaceWithID() [3/12]
SMDS_MeshFace * SMESHDS_Mesh::AddFaceWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, const SMDS_MeshNode * nCenter, int ID) virtual
Reimplemented from SMDS_Mesh.
References AddFaceWithID(), and SMDS_MeshElement::GetID().
AddFaceWithID() [4/12]
SMDS_MeshFace * SMESHDS_Mesh::AddFaceWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, int ID) virtual
Reimplemented from SMDS_Mesh.
References AddFaceWithID(), and SMDS_MeshElement::GetID().
AddFaceWithID() [5/12]
SMDS_MeshFace * SMESHDS_Mesh::AddFaceWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, int ID) virtual
Add a quadrangle defined by its nodes.
Reimplemented from SMDS_Mesh.
References AddFaceWithID(), and SMDS_MeshElement::GetID().
AddFaceWithID() [6/12]
SMDS_MeshFace * SMESHDS_Mesh::AddFaceWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, int ID) virtual
Add a triangle defined by its nodes.
Reimplemented from SMDS_Mesh.
References AddFaceWithID(), and SMDS_MeshElement::GetID().
AddFaceWithID() [7/12]
SMDS_MeshFace * SMESHDS_Mesh::AddFaceWithID (int n1, int n2, int n3, int ID) virtual
Add a triangle defined by its nodes IDs.
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddFace(), and SMDS_Mesh::AddFaceWithID().
Referenced by SMESH_MesherHelper::AddFace(), Fem::FemMeshPy::addFace(), AddFaceWithID(), DriverMED::buildMeshGrille(), Fem::FemVTKTools::importVTKMesh(), and DriverGMF_Read::Perform().
AddFaceWithID() [8/12]
SMDS_MeshFace * SMESHDS_Mesh::AddFaceWithID (int n1, int n2, int n3, int n12, int n23, int n31, int ID) virtual
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddFace(), and SMDS_Mesh::AddFaceWithID().
AddFaceWithID() [9/12]
SMDS_MeshFace * SMESHDS_Mesh::AddFaceWithID (int n1, int n2, int n3, int n12, int n23, int n31, int nCenter, int ID) virtual
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddFace(), and SMDS_Mesh::AddFaceWithID().
AddFaceWithID() [10/12]
SMDS_MeshFace * SMESHDS_Mesh::AddFaceWithID (int n1, int n2, int n3, int n4, int ID) virtual
Add a quadrangle defined by its nodes IDs.
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddFace(), and SMDS_Mesh::AddFaceWithID().
AddFaceWithID() [11/12]
SMDS_MeshFace * SMESHDS_Mesh::AddFaceWithID (int n1, int n2, int n3, int n4, int n12, int n23, int n34, int n41, int ID) virtual
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddFace(), and SMDS_Mesh::AddFaceWithID().
AddFaceWithID() [12/12]
SMDS_MeshFace * SMESHDS_Mesh::AddFaceWithID (int n1, int n2, int n3, int n4, int n12, int n23, int n34, int n41, int nCenter, int ID) virtual
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddFace(), and SMDS_Mesh::AddFaceWithID().
AddGroup()
void SMESHDS_Mesh::AddGroup (SMESHDS_GroupBase * theGroup)
Referenced by SMESH_Mesh::AddGroup(), SMESH_Mesh::ConvertToStandalone(), and DriverGMF_Read::Perform().
AddHypothesis()
bool SMESHDS_Mesh::AddHypothesis (const TopoDS_Shape & SS, const SMESHDS_Hypothesis * H)
References DraftVecUtils::find().
Referenced by SMESH_subMesh::AlgoStateEngine().
AddNode()
SMDS_MeshNode * SMESHDS_Mesh::AddNode (double x, double y, double z) virtual
create a MeshNode and add it to the current Mesh An ID is automatically assigned to the node.
Returns
: The created node
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddNode(), SMESHDS_Script::AddNode(), and SMDS_MeshElement::GetID().
Referenced by SMESH_MesherHelper::AddNode(), Fem::FemMeshPy::addNode(), SMESH_MesherHelper::AddVolume(), NETGENPlugin_NETGEN_2D_ONLY::Compute(), StdMeshers_CompositeSegment_1D::Compute(), StdMeshers_Import_1D::Compute(), StdMeshers_Import_1D2D::Compute(), StdMeshers_Projection_1D::Compute(), StdMeshers_Projection_3D::Compute(), StdMeshers_RadialQuadrangle_1D2D::Compute(), StdMeshers_Regular_1D::Compute(), StdMeshers_Quadrangle_2D::computeQuadDominant(), StdMeshers_Quadrangle_2D::computeQuadPref(), StdMeshers_Quadrangle_2D::computeReduced(), SMESH_MeshEditor::CreateFlatElementsOnFacesGroups(), StdMeshers_Penta_3D::CreateNode(), SMESH_MeshEditor::DoubleNodes(), SMESH_MeshEditor::DoubleNodesOnGroupBoundaries(), NETGENPlugin_Mesher::FillSMesh(), SMESH_MesherHelper::GetCentralNode(), SMESH_MesherHelper::GetMediumNode(), StdMeshers_Import_1D::importMesh(), SMESH_Pattern::MakeMesh(), StdMeshers_RadialPrism_3D::makeNodeColumn(), SMESH_MeshEditor::QuadToTri(), SMESH_MeshEditor::RotationSweep(), and SMESH_MeshEditor::Transform().
AddNodeWithID()
SMDS_MeshNode * SMESHDS_Mesh::AddNodeWithID (double x, double y, double z, int ID) virtual
create a MeshNode and add it to the current Mesh
Parameters
ID : The ID of the MeshNode to create
Returns
: The created node or NULL if a node with this ID already exists
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddNode(), SMDS_Mesh::AddNodeWithID(), and SMDS_MeshElement::GetID().
Referenced by SMESH_MesherHelper::AddNode(), Fem::FemMeshPy::addNode(), DriverMED::buildMeshGrille(), Fem::FemVTKTools::importVTKMesh(), and DriverGMF_Read::Perform().
AddPolygonalFace()
SMDS_MeshFace * SMESHDS_Mesh::AddPolygonalFace (const std::vector< const SMDS_MeshNode * > & nodes) virtual
Add a polygon defined by its nodes.
An ID is automatically affected to the created face.
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddPolygonalFace(), SMDS_Mesh::AddPolygonalFace(), and SMDS_MeshElement::GetID().
Referenced by SMESH_MesherHelper::AddPolygonalFace(), StdMeshers_Import_1D2D::Compute(), SMESH_MeshEditor::InsertNodesIntoLink(), DriverMED_R_SMESHDS_Mesh::Perform(), and SMESH_MeshEditor::SewSideElements().
AddPolygonalFaceWithID() [1/2]
SMDS_MeshFace * SMESHDS_Mesh::AddPolygonalFaceWithID (const std::vector< const SMDS_MeshNode * > & nodes, const int ID) virtual
Add a polygon defined by its nodes.
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddPolygonalFace(), and SMDS_Mesh::AddPolygonalFaceWithID().
AddPolygonalFaceWithID() [2/2]
SMDS_MeshFace * SMESHDS_Mesh::AddPolygonalFaceWithID (const std::vector< int > & nodes_ids, const int ID) virtual
Add a polygon defined by its nodes IDs.
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddPolygonalFace(), and SMDS_Mesh::AddPolygonalFaceWithID().
Referenced by SMESH_MesherHelper::AddPolygonalFace(), and DriverMED_R_SMESHDS_Mesh::Perform().
AddPolyhedralVolume()
SMDS_MeshVolume * SMESHDS_Mesh::AddPolyhedralVolume (const std::vector< const SMDS_MeshNode * > & nodes, const std::vector< int > & quantities) virtual
Create a new polyhedral volume and add it to the mesh.
Returns
The created volume
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddPolyhedralVolume(), SMDS_Mesh::AddPolyhedralVolume(), and SMDS_MeshElement::GetID().
Referenced by SMESH_MesherHelper::AddPolyhedralVolume(), StdMeshers_Projection_3D::Compute(), SMESH_MeshEditor::MergeNodes(), and SMESH_MeshEditor::UpdateVolumes().
AddPolyhedralVolumeWithID() [1/2]
SMDS_MeshVolume * SMESHDS_Mesh::AddPolyhedralVolumeWithID (const std::vector< const SMDS_MeshNode * > & nodes, const std::vector< int > & quantities, const int ID) virtual
Create a new polyhedral volume and add it to the mesh.
Parameters
ID The ID of the new volume
Returns
The created volume
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddPolyhedralVolume(), and SMDS_Mesh::AddPolyhedralVolumeWithID().
AddPolyhedralVolumeWithID() [2/2]
SMDS_MeshVolume * SMESHDS_Mesh::AddPolyhedralVolumeWithID (const std::vector< int > & nodes_ids, const std::vector< int > & quantities, const int ID) virtual
Create a new polyhedral volume and add it to the mesh.
Parameters
ID The ID of the new volume
Returns
The created volume or NULL if an element with this ID already exists or if input nodes are not found.
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddPolyhedralVolume(), and SMDS_Mesh::AddPolyhedralVolumeWithID().
Referenced by SMESH_MesherHelper::AddPolyhedralVolume().
AddQuadPolygonalFace()
SMDS_MeshFace * SMESHDS_Mesh::AddQuadPolygonalFace (const std::vector< const SMDS_MeshNode * > & nodes) virtual
Add a quadratic polygon defined by its nodes.
An ID is automatically affected to the created face.
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddQuadPolygonalFace(), SMDS_Mesh::AddQuadPolygonalFace(), and SMDS_MeshElement::GetID().
Referenced by SMESH_MesherHelper::AddPolygonalFace(), and DriverMED_R_SMESHDS_Mesh::Perform().
AddQuadPolygonalFaceWithID() [1/2]
SMDS_MeshFace * SMESHDS_Mesh::AddQuadPolygonalFaceWithID (const std::vector< const SMDS_MeshNode * > & nodes, const int ID) virtual
Add a quadratic polygon defined by its nodes.
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddQuadPolygonalFace(), and SMDS_Mesh::AddQuadPolygonalFaceWithID().
AddQuadPolygonalFaceWithID() [2/2]
SMDS_MeshFace * SMESHDS_Mesh::AddQuadPolygonalFaceWithID (const std::vector< int > & nodes_ids, const int ID) virtual
Add a quadratic polygon defined by its nodes IDs.
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddQuadPolygonalFace(), and SMDS_Mesh::AddQuadPolygonalFaceWithID().
Referenced by SMESH_MesherHelper::AddPolygonalFace(), and DriverMED_R_SMESHDS_Mesh::Perform().
AddVolume() [1/10]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4) virtual
Create a new tetrahedron and add it to the mesh.
Returns
The created tetrahedron
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddVolume(), SMESHDS_Script::AddVolume(), and SMDS_MeshElement::GetID().
Referenced by SMESH_MesherHelper::AddVolume(), Fem::FemMeshPy::addVolume(), SMESH_MeshEditor::CreateFlatElementsOnFacesGroups(), NETGENPlugin_Mesher::FillSMesh(), and SMESH_MeshEditor::MergeNodes().
AddVolume() [2/10]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n31, const SMDS_MeshNode * n14, const SMDS_MeshNode * n24, const SMDS_MeshNode * n34) virtual
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddVolume(), SMESHDS_Script::AddVolume(), and SMDS_MeshElement::GetID().
AddVolume() [3/10]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5) virtual
Create a new pyramid and add it to the mesh.
Nodes 1,2,3 and 4 define the base of the pyramid
Returns
The created pyramid
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddVolume(), SMESHDS_Script::AddVolume(), and SMDS_MeshElement::GetID().
AddVolume() [4/10]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, const SMDS_MeshNode * n15, const SMDS_MeshNode * n25, const SMDS_MeshNode * n35, const SMDS_MeshNode * n45) virtual
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddVolume(), SMESHDS_Script::AddVolume(), and SMDS_MeshElement::GetID().
AddVolume() [5/10]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6) virtual
Create a new prism and add it to the mesh.
Nodes 1,2,3 is a triangle and 1,2,5,4 a quadrangle.
Returns
The created prism
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddVolume(), SMESHDS_Script::AddVolume(), and SMDS_MeshElement::GetID().
AddVolume() [6/10]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n31, const SMDS_MeshNode * n45, const SMDS_MeshNode * n56, const SMDS_MeshNode * n64, const SMDS_MeshNode * n14, const SMDS_MeshNode * n25, const SMDS_MeshNode * n36) virtual
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddVolume(), SMESHDS_Script::AddVolume(), and SMDS_MeshElement::GetID().
AddVolume() [7/10]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n7, const SMDS_MeshNode * n8) virtual
Create a new hexahedron and add it to the mesh.
Nodes 1,2,3,4 and 5,6,7,8 are quadrangle and 5,1 and 7,3 are an edges.
Returns
The created hexahedron
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddVolume(), SMESHDS_Script::AddVolume(), and SMDS_MeshElement::GetID().
AddVolume() [8/10]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n7, const SMDS_MeshNode * n8, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, const SMDS_MeshNode * n56, const SMDS_MeshNode * n67, const SMDS_MeshNode * n78, const SMDS_MeshNode * n85, const SMDS_MeshNode * n15, const SMDS_MeshNode * n26, const SMDS_MeshNode * n37, const SMDS_MeshNode * n48) virtual
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddVolume(), SMESHDS_Script::AddVolume(), and SMDS_MeshElement::GetID().
AddVolume() [9/10]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n7, const SMDS_MeshNode * n8, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, const SMDS_MeshNode * n56, const SMDS_MeshNode * n67, const SMDS_MeshNode * n78, const SMDS_MeshNode * n85, const SMDS_MeshNode * n15, const SMDS_MeshNode * n26, const SMDS_MeshNode * n37, const SMDS_MeshNode * n48, const SMDS_MeshNode * n1234, const SMDS_MeshNode * n1256, const SMDS_MeshNode * n2367, const SMDS_MeshNode * n3478, const SMDS_MeshNode * n1458, const SMDS_MeshNode * n5678, const SMDS_MeshNode * nCenter) virtual
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddVolume(), SMESHDS_Script::AddVolume(), and SMDS_MeshElement::GetID().
AddVolume() [10/10]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolume (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n7, const SMDS_MeshNode * n8, const SMDS_MeshNode * n9, const SMDS_MeshNode * n10, const SMDS_MeshNode * n11, const SMDS_MeshNode * n12) virtual
Create a new hexagonal prism and add it to the mesh.
Returns
The created prism
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::AddVolume(), SMESHDS_Script::AddVolume(), and SMDS_MeshElement::GetID().
AddVolumeWithID() [1/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n31, const SMDS_MeshNode * n14, const SMDS_MeshNode * n24, const SMDS_MeshNode * n34, int ID) virtual
Reimplemented from SMDS_Mesh.
References AddVolumeWithID(), and SMDS_MeshElement::GetID().
AddVolumeWithID() [2/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, const SMDS_MeshNode * n15, const SMDS_MeshNode * n25, const SMDS_MeshNode * n35, const SMDS_MeshNode * n45, int ID) virtual
Reimplemented from SMDS_Mesh.
References AddVolumeWithID(), and SMDS_MeshElement::GetID().
AddVolumeWithID() [3/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n31, const SMDS_MeshNode * n45, const SMDS_MeshNode * n56, const SMDS_MeshNode * n64, const SMDS_MeshNode * n14, const SMDS_MeshNode * n25, const SMDS_MeshNode * n36, int ID) virtual
Reimplemented from SMDS_Mesh.
References AddVolumeWithID(), and SMDS_MeshElement::GetID().
AddVolumeWithID() [4/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n7, const SMDS_MeshNode * n8, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, const SMDS_MeshNode * n56, const SMDS_MeshNode * n67, const SMDS_MeshNode * n78, const SMDS_MeshNode * n85, const SMDS_MeshNode * n15, const SMDS_MeshNode * n26, const SMDS_MeshNode * n37, const SMDS_MeshNode * n48, const SMDS_MeshNode * n1234, const SMDS_MeshNode * n1256, const SMDS_MeshNode * n2367, const SMDS_MeshNode * n3478, const SMDS_MeshNode * n1458, const SMDS_MeshNode * n5678, const SMDS_MeshNode * nCenter, int ID) virtual
Reimplemented from SMDS_Mesh.
References AddVolumeWithID(), and SMDS_MeshElement::GetID().
AddVolumeWithID() [5/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n7, const SMDS_MeshNode * n8, const SMDS_MeshNode * n12, const SMDS_MeshNode * n23, const SMDS_MeshNode * n34, const SMDS_MeshNode * n41, const SMDS_MeshNode * n56, const SMDS_MeshNode * n67, const SMDS_MeshNode * n78, const SMDS_MeshNode * n85, const SMDS_MeshNode * n15, const SMDS_MeshNode * n26, const SMDS_MeshNode * n37, const SMDS_MeshNode * n48, int ID) virtual
Reimplemented from SMDS_Mesh.
References AddVolumeWithID(), and SMDS_MeshElement::GetID().
AddVolumeWithID() [6/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n7, const SMDS_MeshNode * n8, const SMDS_MeshNode * n9, const SMDS_MeshNode * n10, const SMDS_MeshNode * n11, const SMDS_MeshNode * n12, int ID) virtual
Create a new hexagonal prism and add it to the mesh.
Parameters
ID The ID of the new volume
Returns
The created prism
Reimplemented from SMDS_Mesh.
References AddVolumeWithID(), and SMDS_MeshElement::GetID().
AddVolumeWithID() [7/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, const SMDS_MeshNode * n7, const SMDS_MeshNode * n8, int ID) virtual
Create a new hexahedron and add it to the mesh.
Nodes 1,2,3,4 and 5,6,7,8 are quadrangle and 5,1 and 7,3 are an edges.
Parameters
ID The ID of the new volume
Returns
The created prism or NULL if an element with this ID already exists or if input nodes are not found.
Reimplemented from SMDS_Mesh.
References AddVolumeWithID(), and SMDS_MeshElement::GetID().
AddVolumeWithID() [8/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, const SMDS_MeshNode * n6, int ID) virtual
Create a new prism and add it to the mesh.
Nodes 1,2,3 is a triangle and 1,2,5,4 a quadrangle.
Parameters
ID The ID of the new volume
Returns
The created prism
Reimplemented from SMDS_Mesh.
References AddVolumeWithID(), and SMDS_MeshElement::GetID().
AddVolumeWithID() [9/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, const SMDS_MeshNode * n5, int ID) virtual
Create a new pyramid and add it to the mesh.
Nodes 1,2,3 and 4 define the base of the pyramid
Parameters
ID The ID of the new volume
Returns
The created pyramid
Reimplemented from SMDS_Mesh.
References AddVolumeWithID(), and SMDS_MeshElement::GetID().
AddVolumeWithID() [10/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2, const SMDS_MeshNode * n3, const SMDS_MeshNode * n4, int ID) virtual
Create a new tetrahedron and add it to the mesh.
Parameters
ID The ID of the new volume
Returns
The created tetrahedron
Reimplemented from SMDS_Mesh.
References AddVolumeWithID(), and SMDS_MeshElement::GetID().
AddVolumeWithID() [11/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (int idnode1, int idnode2, int idnode3, int idnode4, int ID) virtual
Create a new tetrahedron and add it to the mesh.
Parameters
ID The ID of the new volume
Returns
The created tetrahedron or NULL if an element with this ID already exists or if input nodes are not found.
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddVolume(), and SMDS_Mesh::AddVolumeWithID().
Referenced by SMESH_MesherHelper::AddVolume(), Fem::FemMeshPy::addVolume(), AddVolumeWithID(), DriverMED::buildMeshGrille(), Fem::FemVTKTools::importVTKMesh(), and DriverGMF_Read::Perform().
AddVolumeWithID() [12/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (int n1, int n2, int n3, int n4, int n12, int n23, int n31, int n14, int n24, int n34, int ID) virtual
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddVolume(), and SMDS_Mesh::AddVolumeWithID().
AddVolumeWithID() [13/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int ID) virtual
Create a new pyramid and add it to the mesh.
Nodes 1,2,3 and 4 define the base of the pyramid
Parameters
ID The ID of the new volume
Returns
The created pyramid or NULL if an element with this ID already exists or if input nodes are not found.
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddVolume(), and SMDS_Mesh::AddVolumeWithID().
AddVolumeWithID() [14/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n12, int n23, int n34, int n41, int n15, int n25, int n35, int n45, int ID) virtual
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddVolume(), and SMDS_Mesh::AddVolumeWithID().
AddVolumeWithID() [15/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6, int ID) virtual
Create a new prism and add it to the mesh.
Nodes 1,2,3 is a triangle and 1,2,5,4 a quadrangle.
Parameters
ID The ID of the new volume
Returns
The created prism or NULL if an element with this ID already exists or if input nodes are not found.
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddVolume(), and SMDS_Mesh::AddVolumeWithID().
AddVolumeWithID() [16/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int n12, int n23, int n31, int n45, int n56, int n64, int n14, int n25, int n36, int ID) virtual
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddVolume(), and SMDS_Mesh::AddVolumeWithID().
AddVolumeWithID() [17/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6, int idnode7, int idnode8, int ID) virtual
Create a new hexahedron and add it to the mesh.
Nodes 1,2,3,4 and 5,6,7,8 are quadrangle and 5,1 and 7,3 are an edges.
Parameters
ID The ID of the new volume
Returns
The created hexahedron or NULL if an element with this ID already exists or if input nodes are not found.
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddVolume(), and SMDS_Mesh::AddVolumeWithID().
AddVolumeWithID() [18/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n12, int n23, int n34, int n41, int n56, int n67, int n78, int n85, int n15, int n26, int n37, int n48, int ID) virtual
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddVolume(), and SMDS_Mesh::AddVolumeWithID().
AddVolumeWithID() [19/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n12, int n23, int n34, int n41, int n56, int n67, int n78, int n85, int n15, int n26, int n37, int n48, int n1234, int n1256, int n2367, int n3478, int n1458, int n5678, int nCenter, int ID) virtual
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddVolume(), and SMDS_Mesh::AddVolumeWithID().
AddVolumeWithID() [20/20]
SMDS_MeshVolume * SMESHDS_Mesh::AddVolumeWithID (int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6, int idnode7, int idnode8, int idnode9, int idnode10, int idnode11, int idnode12, int ID) virtual
Create a new hexagonal prism and add it to the mesh.
Parameters
ID The ID of the new volume
Returns
The created prism or NULL if an element with this ID already exists or if input nodes are not found.
Reimplemented from SMDS_Mesh.
References SMESHDS_Script::AddVolume(), and SMDS_Mesh::AddVolumeWithID().
BuildDownWardConnectivity()
void SMESHDS_Mesh::BuildDownWardConnectivity (bool withEdges)
References SMDS_UnstructuredGrid::BuildDownwardConnectivity(), and SMDS_Mesh::myGrid.
Referenced by SMESH_MeshEditor::CreateHoleSkin(), and SMESH_MeshEditor::DoubleNodesOnGroupBoundaries().
ChangeElementNodes()
bool SMESHDS_Mesh::ChangeElementNodes (const SMDS_MeshElement * elem, const SMDS_MeshNode * nodes[], const int nbnodes)
References SMDS_Mesh::ChangeElementNodes(), SMESHDS_Script::ChangeElementNodes(), and SMDS_MeshElement::GetID().
Referenced by ChangePolygonNodes(), SMESH_MeshEditor::DoubleNodes(), SMESH_MeshEditor::InverseDiag(), SMESH_MeshEditor::MergeNodes(), SMESH_MeshEditor::Reorient(), and SMESH_MeshEditor::Transform().
ChangePolygonNodes()
bool SMESHDS_Mesh::ChangePolygonNodes (const SMDS_MeshElement * elem, std::vector< const SMDS_MeshNode * > nodes)
References ChangeElementNodes().
ChangePolyhedronNodes()
bool SMESHDS_Mesh::ChangePolyhedronNodes (const SMDS_MeshElement * elem, std::vector< const SMDS_MeshNode * > nodes, std::vector< int > quantities)
References SMESHDS_Script::ChangePolyhedronNodes(), SMDS_Mesh::ChangePolyhedronNodes(), and SMDS_MeshElement::GetID().
Referenced by SMESH_MeshEditor::Reorient().
CleanDownWardConnectivity()
void SMESHDS_Mesh::CleanDownWardConnectivity ()
References SMDS_UnstructuredGrid::CleanDownwardConnectivity(), and SMDS_Mesh::myGrid.
Referenced by SMESH_MeshEditor::DoubleNodesOnGroupBoundaries().
ClearMesh()
void SMESHDS_Mesh::ClearMesh ()
Remove all data from the mesh.
References SMDS_Mesh::Clear(), SMESHDS_Script::ClearMesh(), and SubMeshes().
Referenced by Fem::FemVTKTools::importVTKMesh().
ClearScript()
void SMESHDS_Mesh::ClearScript ()
References SMESHDS_Script::Clear().
compactMesh()
void SMESHDS_Mesh::compactMesh () virtual
Reimplemented from SMDS_Mesh.
References SMDS_UnstructuredGrid::compactGrid(), SMDS_MeshNodeIDFactory::emptyPool(), SMDS_Mesh::myCellIdVtkToSmds, SMDS_Mesh::myCells, SMDS_Mesh::myElementIDFactory, SMDS_Mesh::myGrid, SMDS_Mesh::myNodeIDFactory, SMDS_Mesh::myNodes, SMESHDS_Script::SetModified(), and SubMeshes().
Referenced by SMESH_Gen::Compute(), SMESH_Pattern::MakeMesh(), and Renumber().
GetGroups()
const std::set<SMESHDS_GroupBase*>& SMESHDS_Mesh::GetGroups () const
Referenced by SMESH_MeshEditor::AddToSameGroups(), DriverGMF_Read::Perform(), DriverGMF_Write::Perform(), SMESH_MeshEditor::RemoveElemFromGroups(), SMESH_MeshEditor::ReplaceElemInGroups(), SMESH::Controls::GroupColor::SetMesh(), and SMESH_MeshVSLink::SMESH_MeshVSLink().
GetHypotheses()
const ShapeToHypothesis& SMESHDS_Mesh::GetHypotheses () const
GetHypothesis()
const list< const SMESHDS_Hypothesis * > & SMESHDS_Mesh::GetHypothesis (const TopoDS_Shape & S) const
Referenced by SMESH_subMesh::cleanDependsOn(), and SMESH_Gen::GetAlgoState().
GetNbGroups()
int SMESHDS_Mesh::GetNbGroups () const
Referenced by SMESH::Controls::GroupColor::SetMesh().
GetPersistentId()
int SMESHDS_Mesh::GetPersistentId () const
Return ID persistent during lifecycle.
Referenced by StdMeshers_Import_1D::Compute(), StdMeshers_Import_1D2D::Compute(), SMESH_Mesh::ExportCGNS(), and StdMeshers_ImportSource1D::GetSourceMeshes().
GetScript()
SMESHDS_Script * SMESHDS_Mesh::GetScript ()
HasHypothesis()
bool SMESHDS_Mesh::HasHypothesis (const TopoDS_Shape & S)
HasMeshElements()
bool SMESHDS_Mesh::HasMeshElements (const TopoDS_Shape & S) const
References SMESHDS_TSubMeshHolder< SUBMESH >::Get().
IndexToShape()
const TopoDS_Shape & SMESHDS_Mesh::IndexToShape (int ShapeIndex) const
Referenced by NETGENPlugin_Mesher::AddIntVerticesInFaces(), NETGENPlugin_Mesher::AddIntVerticesInSolids(), StdMeshers_Quadrangle_2D::checkNbEdgesForEvaluate(), NETGENPlugin_NETGEN_3D::Compute(), StdMeshers_Import_1D2D::Compute(), NETGENPlugin_Internals::findBorderElements(), SMESH_MeshEditor::FindShape(), SMESH_MesherHelper::FixQuadraticElements(), SMESH_MesherHelper::GetCentralNode(), VISCOUS_2D::getEdgesToIgnore(), SMESH_MesherHelper::GetMediumNode(), DriverMED_W_SMESHDS_Mesh::getNodesOfMissing0DOnVert(), SMESH_MesherHelper::GetNodeU(), SMESH_MesherHelper::GetSubShapeByNode(), SMESH_MesherHelper::IsReversedSubMesh(), SMESH_MeshEditor::MakeBoundaryMesh(), SMESH_MeshEditor::QuadToTri(), StdMeshers_SegmentLengthAroundVertex::SetParametersByMesh(), SMESH_MeshEditor::Smooth(), SMESH_MeshEditor::SplitVolumes(), and SMESH_Algo::VertexNode().
IsEmbeddedMode()
bool SMESHDS_Mesh::IsEmbeddedMode ()
Referenced by StdMeshers_QuadToTriaAdaptor::Compute2ndPart().
IsGroupOfSubShapes()
bool SMESHDS_Mesh::IsGroupOfSubShapes (const TopoDS_Shape & aSubShape) const
Referenced by AddCompoundSubmesh(), and SMESH_MesherHelper::IsSubShape().
IsUsedHypothesis()
bool SMESHDS_Mesh::IsUsedHypothesis (const SMESHDS_Hypothesis * H) const
returns true if the hypothesis is assigned to any sub-shape
References DraftVecUtils::find().
Referenced by StdMeshers_ViscousLayers2D::RestoreListeners().
MaxShapeIndex()
int SMESHDS_Mesh::MaxShapeIndex () const
Referenced by StdMeshers_QuadToTriaAdaptor::Compute2ndPart(), and DriverMED_W_SMESHDS_Mesh::getNodesOfMissing0DOnVert().
MaxSubMeshIndex()
int SMESHDS_Mesh::MaxSubMeshIndex () const
Return max index of sub-mesh.
References SMESHDS_TSubMeshHolder< SUBMESH >::GetMaxID().
MeshElements() [1/2]
SMESHDS_SubMesh * SMESHDS_Mesh::MeshElements (const int Index) const
Return the sub mesh by Id of shape it is linked to.
References SMESHDS_TSubMeshHolder< SUBMESH >::Get().
MeshElements() [2/2]
SMESHDS_SubMesh * SMESHDS_Mesh::MeshElements (const TopoDS_Shape & S) const
Return the sub mesh linked to the a given TopoDS_Shape or NULL if the given TopoDS_Shape is unknown.
References SMESHDS_TSubMeshHolder< SUBMESH >::Get(), and ShapeToIndex().
Referenced by VISCOUS_3D::_Shrinker1D::AddEdge(), StdMeshers_Quadrangle_2D::check(), NETGENPlugin_NETGEN_2D_ONLY::Compute(), StdMeshers_Cartesian_3D::Compute(), StdMeshers_Hexa_3D::Compute(), StdMeshers_Import_1D::Compute(), StdMeshers_Import_1D2D::Compute(), StdMeshers_Prism_3D::Compute(), StdMeshers_Projection_1D2D::Compute(), StdMeshers_Projection_2D::Compute(), StdMeshers_RadialPrism_3D::Compute(), StdMeshers_Regular_1D::Compute(), StdMeshers_QuadToTriaAdaptor::Compute(), StdMeshers_Regular_1D::computeInternalParameters(), SMESH_MeshEditor::ConvertToQuadratic(), NETGENPlugin_Internals::findBorderElements(), StdMeshers_ProjectionUtils::FindMatchingNodesOnFaces(), SMESH_MeshEditor::FindShape(), StdMeshers_ProjectionUtils::FindSubShapeAssociation(), StdMeshers_FaceSide::GetEdgeNodes(), StdMeshers_CompositeSegment_1D::GetFaceSide(), SMESH_Algo::GetNodeParamOnEdge(), DriverMED_W_SMESHDS_Mesh::getNodesOfMissing0DOnVert(), SMESH_Algo::GetSortedNodesOnEdge(), SMESH_ProxyMesh::GetSubMesh(), SMESH_MesherHelper::IsDistorted2D(), SMESH_subMesh::IsMeshComputed(), SMESH_MesherHelper::IsQuadraticSubMesh(), SMESH_MesherHelper::IsReversedSubMesh(), SMESH_Pattern::Load(), StdMeshers_Penta_3D::LoadIJNodes(), SMESH_MesherHelper::LoadNodeColumns(), VISCOUS_3D::_ViscousBuilder::MakeN2NMap(), StdMeshers_Penta_3D::MakeNodes(), SMESH_MeshEditor::MergeNodes(), NewSubMesh(), SMESH_MeshEditor::QuadTo4Tri(), RemoveElement(), RemoveFreeElement(), RemoveFreeNode(), StdMeshers_Adaptive1D::SetParametersByMesh(), StdMeshers_AutomaticLength::SetParametersByMesh(), StdMeshers_MaxElementArea::SetParametersByMesh(), StdMeshers_MaxElementVolume::SetParametersByMesh(), StdMeshers_NumberOfSegments::SetParametersByMesh(), StdMeshers_SegmentLengthAroundVertex::SetParametersByMesh(), SMESHDS_GroupOnGeom::SetShape(), SMESH_subMesh::SMESH_subMesh(), StdMeshers_Quadrangle_2D::smooth(), SMESH_MeshEditor::Smooth(), SMESH_MeshEditor::SplitVolumes(), UnSetMeshElementOnShape(), UnSetNodeOnShape(), and SMESH_Algo::VertexNode().
ModifyCellNodes()
bool SMESHDS_Mesh::ModifyCellNodes (int vtkVolId, std::map< int, int > localClonedNodeIds)
change some nodes in cell without modifying type or internal connectivity. Nodes inverse connectivity is maintained up to date.
Parameters
vtkVolId vtk id of the cell.
localClonedNodeIds map old node id to new node id.
Returns
ok if success.
References SMDS_UnstructuredGrid::ModifyCellNodes(), and SMDS_Mesh::myGrid.
Referenced by SMESH_MeshEditor::DoubleNodesOnGroupBoundaries().
MoveNode()
void SMESHDS_Mesh::MoveNode (const SMDS_MeshNode * n, double x, double y, double z) virtual
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::MoveNode(), and SMESHDS_Script::MoveNode().
Referenced by StdMeshers_QuadToTriaAdaptor::Compute2ndPart(), SMESH_2D_Algo::FixInternalNodes(), SMESH_MesherHelper::FixQuadraticElements(), SMESH_MesherHelper::getMediumNodeOnComposedWire(), SMESH_MeshEditor::InverseDiag(), SMESH_MeshEditor::SewFreeBorder(), StdMeshers_Quadrangle_2D::smooth(), SMESH_MeshEditor::Smooth(), SMESH_MeshEditor::SplitVolumes(), and SMESH_MeshEditor::Transform().
NewSubMesh()
SMESHDS_SubMesh * SMESHDS_Mesh::NewSubMesh (int Index)
References SMESHDS_TSubMeshHolder< SUBMESH >::Add(), and MeshElements().
Referenced by AddCompoundSubmesh(), SMESH_subMesh::CreateSubMeshDS(), SetMeshElementOnShape(), SetNodeInVolume(), SetNodeOnEdge(), SetNodeOnFace(), and SetNodeOnVertex().
RemoveElement()
void SMESHDS_Mesh::RemoveElement (const SMDS_MeshElement * elt)
References SMDS_MeshElement::GetID(), SMDS_MeshElement::getshapeId(), SMDS_MeshElement::GetType(), SMDS_Mesh::hasConstructionEdges(), SMDS_Mesh::hasConstructionFaces(), MeshElements(), SMDS_Mesh::RemoveElement(), SMESHDS_Script::RemoveElement(), RemoveFreeElement(), and RemoveNode().
Referenced by SMESH_MeshEditor::DeleteDiag(), SMESH_MeshEditor::InsertNodesIntoLink(), SMESH_MeshEditor::QuadToTri(), SMESH_MeshEditor::Remove(), SMESH_MeshEditor::SewSideElements(), SMESH_MeshEditor::TriToQuad(), and SMESH_MeshEditor::UpdateVolumes().
RemoveFreeElement()
void SMESHDS_Mesh::RemoveFreeElement (const SMDS_MeshElement * elt, SMESHDS_SubMesh * subMesh, bool fromGroups = true)
References SMDS_MeshElement::GetID(), SMDS_MeshElement::getshapeId(), SMDS_MeshElement::GetType(), SMDS_Mesh::hasConstructionEdges(), SMDS_Mesh::hasConstructionFaces(), MeshElements(), SMDS_MeshGroup::Remove(), SMESHDS_SubMesh::RemoveElement(), SMESHDS_Script::RemoveElement(), SMDS_Mesh::RemoveFreeElement(), RemoveFreeNode(), and SMESHDS_Group::SMDSGroup().
Referenced by StdMeshers_Regular_1D::Compute(), SMESH_MeshEditor::ConvertToQuadratic(), SMESH_MeshEditor::MergeNodes(), SMESH_MeshEditor::QuadTo4Tri(), RemoveElement(), SMESH_ProxyMesh::removeTmpElement(), SMESH_MeshEditor::SplitVolumes(), and SMESH_ProxyMesh::~SMESH_ProxyMesh().
RemoveFreeNode()
void SMESHDS_Mesh::RemoveFreeNode (const SMDS_MeshNode * n, SMESHDS_SubMesh * subMesh, bool fromGroups = true)
Remove only the given element/node and only if it is free. Methods do not work for meshes with descendants. Implemented for fast cleaning of meshes.
References MeshElements(), SMDS_MeshGroup::Remove(), SMDS_Mesh::RemoveFreeElement(), SMESHDS_SubMesh::RemoveNode(), SMESHDS_Script::RemoveNode(), and SMESHDS_Group::SMDSGroup().
Referenced by StdMeshers_Cartesian_3D::Compute(), StdMeshers_Regular_1D::Compute(), SMESH_MeshEditor::ConvertToQuadratic(), RemoveFreeElement(), and RemoveNode().
RemoveGroup()
void SMESHDS_Mesh::RemoveGroup (SMESHDS_GroupBase * theGroup)
Referenced by SMESH_Mesh::ConvertToStandalone(), and SMESH_Mesh::RemoveGroup().
RemoveHypothesis()
bool SMESHDS_Mesh::RemoveHypothesis (const TopoDS_Shape & S, const SMESHDS_Hypothesis * H)
References DraftVecUtils::find().
Referenced by SMESH_subMesh::AlgoStateEngine().
RemoveNode()
void SMESHDS_Mesh::RemoveNode (const SMDS_MeshNode * node) virtual
Remove a node and all the elements which own this node.
Reimplemented from SMDS_Mesh.
References SMDS_Mesh::hasConstructionEdges(), SMDS_Mesh::hasConstructionFaces(), SMDS_Mesh::RemoveElement(), RemoveFreeNode(), and SMESHDS_Script::RemoveNode().
Referenced by StdMeshers_CompositeSegment_1D::Compute(), StdMeshers_Import_1D::Compute(), StdMeshers_Regular_1D::Compute(), SMESH_MeshEditor::DeleteDiag(), StdMeshers_Import_1D::Evaluate(), StdMeshers_Import_1D2D::Evaluate(), SMESH_MeshEditor::Remove(), RemoveElement(), SMESH_MeshEditor::SplitVolumes(), and SMESH_MeshEditor::TriToQuad().
Renumber()
void SMESHDS_Mesh::Renumber (const bool isNodes, const int startID = 1, const int deltaID = 1) virtual
Reimplemented from SMDS_Mesh.
References compactMesh(), and SMDS_Mesh::isCompacted().
SetMeshElementOnShape() [1/2]
void SMESHDS_Mesh::SetMeshElementOnShape (const SMDS_MeshElement * anElt, const TopoDS_Shape & S)
Referenced by SMESH_MesherHelper::AddEdge(), SMESH_MesherHelper::AddFace(), SMESH_MesherHelper::AddPolygonalFace(), SMESH_MesherHelper::AddPolyhedralVolume(), SMESH_MesherHelper::AddVolume(), StdMeshers_Cartesian_3D::Compute(), StdMeshers_CompositeSegment_1D::Compute(), StdMeshers_Import_1D::Compute(), StdMeshers_Import_1D2D::Compute(), StdMeshers_Projection_1D::Compute(), StdMeshers_Projection_1D2D::Compute(), StdMeshers_Projection_3D::Compute(), StdMeshers_RadialQuadrangle_1D2D::Compute(), StdMeshers_Regular_1D::Compute(), SMESH_MeshEditor::DeleteDiag(), NETGENPlugin_Mesher::FillSMesh(), SMESH_MesherHelper::GetCentralNode(), SMESH_MesherHelper::GetMediumNode(), SMESH_MeshEditor::InsertNodesIntoLink(), SMESH_MeshEditor::MakeBoundaryMesh(), StdMeshers_Penta_3D::MakeMeshOnFxy1(), StdMeshers_Penta_3D::MakeVolumeMesh(), SMESH_MeshEditor::MergeNodes(), SMESH_MeshEditor::QuadToTri(), SMESH_MeshEditor::SewSideElements(), SMESH_MeshEditor::TriToQuad(), and SMESH_MeshEditor::UpdateVolumes().
SetMeshElementOnShape() [2/2]
void SMESHDS_Mesh::SetMeshElementOnShape (const SMDS_MeshElement * anElt, int Index)
References NewSubMesh().
SetNodeInVolume() [1/3]
void SMESHDS_Mesh::SetNodeInVolume (const SMDS_MeshNode * aNode, const TopoDS_Shell & S)
References SMDS_SpacePosition::originSpacePosition().
Referenced by SMESH_MesherHelper::AddNode(), SMESH_MesherHelper::AddVolume(), StdMeshers_Projection_3D::Compute(), NETGENPlugin_Mesher::FillSMesh(), SMESH_MesherHelper::GetCentralNode(), SMESH_Pattern::MakeMesh(), StdMeshers_RadialPrism_3D::makeNodeColumn(), and StdMeshers_Penta_3D::MakeVolumeMesh().
SetNodeInVolume() [2/3]
void SMESHDS_Mesh::SetNodeInVolume (const SMDS_MeshNode * aNode, const TopoDS_Solid & S)
References SMDS_SpacePosition::originSpacePosition().
SetNodeInVolume() [3/3]
void SMESHDS_Mesh::SetNodeInVolume (const SMDS_MeshNode * aNode, int Index)
References NewSubMesh(), and SMDS_SpacePosition::originSpacePosition().
SetNodeOnEdge() [1/2]
void SMESHDS_Mesh::SetNodeOnEdge (const SMDS_MeshNode * aNode, const TopoDS_Edge & S, double u = 0.)
Referenced by SMESH_MesherHelper::AddNode(), StdMeshers_CompositeSegment_1D::Compute(), StdMeshers_Import_1D::Compute(), StdMeshers_Import_1D2D::Compute(), StdMeshers_Projection_1D::Compute(), StdMeshers_Projection_1D2D::Compute(), StdMeshers_RadialQuadrangle_1D2D::Compute(), StdMeshers_Regular_1D::Compute(), NETGENPlugin_Mesher::FillSMesh(), SMESH_MesherHelper::GetMediumNode(), SMESH_MesherHelper::getMediumNodeOnComposedWire(), and SMESH_Pattern::MakeMesh().
SetNodeOnEdge() [2/2]
void SMESHDS_Mesh::SetNodeOnEdge (const SMDS_MeshNode * aNode, int Index, double u = 0.)
References NewSubMesh().
SetNodeOnFace() [1/2]
void SMESHDS_Mesh::SetNodeOnFace (const SMDS_MeshNode * aNode, const TopoDS_Face & S, double u = 0., double v = 0.)
Referenced by SMESH_MesherHelper::AddNode(), NETGENPlugin_NETGEN_2D_ONLY::Compute(), StdMeshers_Import_1D2D::Compute(), StdMeshers_RadialQuadrangle_1D2D::Compute(), StdMeshers_Quadrangle_2D::computeQuadDominant(), StdMeshers_Quadrangle_2D::computeQuadPref(), StdMeshers_Quadrangle_2D::computeReduced(), NETGENPlugin_Mesher::FillSMesh(), SMESH_MesherHelper::GetCentralNode(), SMESH_MesherHelper::GetMediumNode(), SMESH_MeshEditor::InverseDiag(), SMESH_Pattern::MakeMesh(), StdMeshers_Penta_3D::MakeNodes(), and SMESH_MeshEditor::SplitVolumes().
SetNodeOnFace() [2/2]
void SMESHDS_Mesh::SetNodeOnFace (const SMDS_MeshNode * aNode, int Index, double u = 0., double v = 0.)
References NewSubMesh().
SetNodeOnVertex() [1/2]
void SMESHDS_Mesh::SetNodeOnVertex (const SMDS_MeshNode * aNode, const TopoDS_Vertex & S)
Referenced by SMESH_MesherHelper::AddNode(), StdMeshers_RadialQuadrangle_1D2D::Compute(), NETGENPlugin_Mesher::FillSMesh(), and SMESH_Pattern::MakeMesh().
SetNodeOnVertex() [2/2]
void SMESHDS_Mesh::SetNodeOnVertex (const SMDS_MeshNode * aNode, int Index)
References NewSubMesh().
SetPersistentId()
void SMESHDS_Mesh::SetPersistentId (int id)
Store ID persistent during lifecycle.
Initially it was used to have a persistent reference to the mesh from the hypothesis
References SMDS_Mesh::NbNodes().
Referenced by SMESHDS_Mesh().
ShapeToIndex()
int SMESHDS_Mesh::ShapeToIndex (const TopoDS_Shape & aShape) const
Referenced by StdMeshers_Quadrangle_2D::addEnforcedNodes(), NETGENPlugin_Mesher::AddSegmentsToMesh(), SMESH_MesherHelper::CheckNodeU(), NETGENPlugin_NETGEN_2D_ONLY::Compute(), NETGENPlugin_NETGEN_3D::Compute(), StdMeshers_CompositeSegment_1D::Compute(), StdMeshers_Import_1D::Compute(), StdMeshers_Import_1D2D::Compute(), StdMeshers_Projection_1D2D::Compute(), StdMeshers_Projection_3D::Compute(), StdMeshers_RadialPrism_3D::Compute(), StdMeshers_RadialQuadrangle_1D2D::Compute(), StdMeshers_Regular_1D::Compute(), StdMeshers_Quadrangle_2D::computeQuadDominant(), StdMeshers_Quadrangle_2D::computeQuadPref(), StdMeshers_Quadrangle_2D::computeReduced(), SMESH_subMesh::CreateSubMeshDS(), NETGENPlugin_Mesher::FillNgMesh(), NETGENPlugin_Internals::findBorderElements(), StdMeshers_ProjectionUtils::FindMatchingNodesOnFaces(), SMESH_MeshEditor::FindShape(), StdMeshers_ProjectionUtils::FindSubShapeAssociation(), NETGENPlugin_Mesher::FixIntFaces(), SMESH_MesherHelper::GetCentralNode(), VISCOUS_3D::getConcaveVertices(), VISCOUS_2D::getEdgesToIgnore(), SMESH_MesherHelper::getFaceMaxTol(), SMESH_MesherHelper::getMediumNodeOnComposedWire(), SMESH_MesherHelper::GetMediumPos(), SMESH_MesherHelper::GetNodeU(), SMESH_MesherHelper::GetProjector(), VISCOUS_3D::_SolidData::GetShapeEdges(), StdMeshers_ImportSource1D::GetSourceSubMeshes(), StdMeshers_PrismAsBlock::Init(), SMESH_MesherHelper::IsReversedSubMesh(), SMESH_MesherHelper::IsSubShape(), StdMeshers_Penta_3D::MakeBlock(), StdMeshers_Penta_3D::MakeNodes(), StdMeshers_Penta_3D::MakeVolumeMesh(), MeshElements(), NETGENPlugin_Internals::NETGENPlugin_Internals(), SMESH_MesherHelper::SetSubShape(), and StdMeshers_FaceSide::StdMeshers_FaceSide().
ShapeToMesh() [1/2]
TopoDS_Shape SMESHDS_Mesh::ShapeToMesh () const
ShapeToMesh() [2/2]
void SMESHDS_Mesh::ShapeToMesh (const TopoDS_Shape & S)
References SMESHDS_TSubMeshHolder< SUBMESH >::DeleteAll(), and SubMeshes().
Referenced by StdMeshers_Import_1D2D::Compute(), StdMeshers_Projection_2D::Compute(), SMESH_MeshEditor::FindShape(), SMESH_Gen::GetAlgoState(), SMESH_Gen::IsGlobalHypothesis(), DriverMED_W_SMESHDS_Mesh::Perform(), and SMESH_Mesh::SMESH_Mesh().
SubMeshes()
SMESHDS_SubMeshIteratorPtr SMESHDS_Mesh::SubMeshes () const
References SMESHDS_TSubMeshHolder< SUBMESH >::GetIterator().
Referenced by ClearMesh(), compactMesh(), SMESH_MeshEditor::FindShape(), DriverMED_W_SMESHDS_Mesh::Perform(), ShapeToMesh(), and SubMeshIndices().
SubMeshIndices()
list< int > SMESHDS_Mesh::SubMeshIndices () const
References SubMeshes().
Referenced by DriverMED_W_SMESHDS_Mesh::Perform().
UnSetMeshElementOnShape()
void SMESHDS_Mesh::UnSetMeshElementOnShape (const SMDS_MeshElement * anElt, const TopoDS_Shape & S)
References SMDS_MeshElement::GetType(), and MeshElements().
UnSetNodeOnShape()
void SMESHDS_Mesh::UnSetNodeOnShape (const SMDS_MeshNode * aNode)
References SMDS_MeshElement::getshapeId(), and MeshElements().
Referenced by SMESH_MesherHelper::getMediumNodeOnComposedWire().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESHDS_Mesh.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESHDS/SMESHDS_Mesh.cpp