FreeCAD: PathScripts.post.linuxcnc_post Namespace Reference
PathScripts.post.linuxcnc_post Namespace Reference
Functions
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
def processArguments (argstring)
Variables
action
string COMMAND_SPACE = " "
dictionary CORNER_MAX = {"x": 500, "y": 300, "z": 300}
dictionary CORNER_MIN = {"x": 0, "y": 0, "z": 0}
default
help
int LINENR = 100
string MACHINE_NAME = "LinuxCNC"
bool MODAL = False
now = datetime.datetime.now()
bool OUTPUT_COMMENTS = True
tuple OUTPUT_DOUBLES
bool OUTPUT_HEADER = True
bool OUTPUT_LINE_NUMBERS = False
parser = argparse.ArgumentParser(prog="linuxcnc", add_help=False)
string POST_OPERATION = """"""
string POSTAMBLE
string PRE_OPERATION = """"""
string PREAMBLE
int PRECISION = 3
pythonopen = open
bool SHOW_EDITOR = True
string TOOL_CHANGE = """"""
string TOOLTIP
TOOLTIP_ARGS = parser.format_help()
string UNIT_FORMAT = "mm"
string UNIT_SPEED_FORMAT = "mm/min"
string UNITS = "G21"
bool USE_TLO = True
Function Documentation
export()
def PathScripts.post.linuxcnc_post.export (objectslist, filename, argstring)
References PathScripts.post.linuxcnc_post.linenumber(), PathScripts.post.linuxcnc_post.parse(), PathScripts.post.linuxcnc_post.processArguments(), and PathScripts.post.linuxcnc_post.pythonopen.
linenumber()
def PathScripts.post.linuxcnc_post.linenumber ()
Referenced by PathScripts.post.linuxcnc_post.export(), and PathScripts.post.linuxcnc_post.parse().
parse()
def PathScripts.post.linuxcnc_post.parse (pathobj)
References PathScripts.post.linuxcnc_post.linenumber(), and PathScripts.post.linuxcnc_post.parse().
Referenced by PathScripts.post.linuxcnc_post.export(), and PathScripts.post.linuxcnc_post.parse().
processArguments()
def PathScripts.post.linuxcnc_post.processArguments (argstring)
Referenced by PathScripts.post.linuxcnc_post.export().
Variable Documentation
action
PathScripts.post.linuxcnc_post.action
COMMAND_SPACE
string PathScripts.post.linuxcnc_post.COMMAND_SPACE = " "
CORNER_MAX
dictionary PathScripts.post.linuxcnc_post.CORNER_MAX = {"x": 500, "y": 300, "z": 300}
CORNER_MIN
dictionary PathScripts.post.linuxcnc_post.CORNER_MIN = {"x": 0, "y": 0, "z": 0}
default
PathScripts.post.linuxcnc_post.default
help
PathScripts.post.linuxcnc_post.help
LINENR
int PathScripts.post.linuxcnc_post.LINENR = 100
MACHINE_NAME
string PathScripts.post.linuxcnc_post.MACHINE_NAME = "LinuxCNC"
MODAL
bool PathScripts.post.linuxcnc_post.MODAL = False
now
PathScripts.post.linuxcnc_post.now = datetime.datetime.now()
OUTPUT_COMMENTS
bool PathScripts.post.linuxcnc_post.OUTPUT_COMMENTS = True
OUTPUT_DOUBLES
tuple PathScripts.post.linuxcnc_post.OUTPUT_DOUBLES
Initial value:
=  (
    True  # if false duplicate axis values are suppressed if the same as previous line.
)
OUTPUT_HEADER
bool PathScripts.post.linuxcnc_post.OUTPUT_HEADER = True
OUTPUT_LINE_NUMBERS
bool PathScripts.post.linuxcnc_post.OUTPUT_LINE_NUMBERS = False
parser
PathScripts.post.linuxcnc_post.parser = argparse.ArgumentParser(prog="linuxcnc", add_help=False)
POST_OPERATION
string PathScripts.post.linuxcnc_post.POST_OPERATION = """"""
POSTAMBLE
string PathScripts.post.linuxcnc_post.POSTAMBLE
Initial value:
=  """M05
G17 G54 G90 G80 G40
M2
"""
PRE_OPERATION
string PathScripts.post.linuxcnc_post.PRE_OPERATION = """"""
PREAMBLE
string PathScripts.post.linuxcnc_post.PREAMBLE
Initial value:
=  """G17 G54 G40 G49 G80 G90
"""
PRECISION
int PathScripts.post.linuxcnc_post.PRECISION = 3
pythonopen
PathScripts.post.linuxcnc_post.pythonopen = open
Referenced by PathScripts.post.linuxcnc_post.export().
SHOW_EDITOR
bool PathScripts.post.linuxcnc_post.SHOW_EDITOR = True
TOOL_CHANGE
string PathScripts.post.linuxcnc_post.TOOL_CHANGE = """"""
TOOLTIP
string PathScripts.post.linuxcnc_post.TOOLTIP
Initial value:
=  """
This is a postprocessor file for the Path workbench. It is used to
take a pseudo-gcode fragment outputted by a Path object, and output
real GCode suitable for a linuxcnc 3 axis mill. This postprocessor, once placed
in the appropriate PathScripts folder, can be used directly from inside
FreeCAD, via the GUI importer or via python scripts with:
import linuxcnc_post
linuxcnc_post.export(object,"/path/to/file.ncc","")
"""
TOOLTIP_ARGS
PathScripts.post.linuxcnc_post.TOOLTIP_ARGS = parser.format_help()
UNIT_FORMAT
string PathScripts.post.linuxcnc_post.UNIT_FORMAT = "mm"
UNIT_SPEED_FORMAT
string PathScripts.post.linuxcnc_post.UNIT_SPEED_FORMAT = "mm/min"
UNITS
string PathScripts.post.linuxcnc_post.UNITS = "G21"
USE_TLO
bool PathScripts.post.linuxcnc_post.USE_TLO = True