FreeCAD: TechDrawGui::QGISVGTemplate Class Reference
TechDrawGui::QGISVGTemplate Class Reference
#include <QGISVGTemplate.h>
Public Types
enum { Type = QGraphicsItem::UserType + 153 }
Public Types inherited from TechDrawGui::QGITemplate
enum { Type = QGraphicsItem::UserType + 150 }
Public Member Functions
void draw ()
TechDraw::DrawSVGTemplate * getSVGTemplate ()
QGISVGTemplate (QGSPage *scene)
int type () const
virtual void updateView (bool update=false)
virtual ~QGISVGTemplate ()
Public Member Functions inherited from TechDrawGui::QGITemplate
void clearContents ()
virtual void draw ()=0
TechDraw::DrawTemplate * getTemplate ()
std::vector< TemplateTextField * > getTextFields (void)
qreal getY ()
QGITemplate (QGSPage *)
void setTemplate (TechDraw::DrawTemplate *obj)
int type () const
virtual void updateView (bool update=false)
~QGITemplate ()
Protected Member Functions
void createClickHandles (void)
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value)
void load (const QString &fileName)
void openFile (const QFile &file)
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value)
Protected Attributes
bool firstTime
QGraphicsSvgItem * m_svgItem
QSvgRenderer * m_svgRender
Protected Attributes inherited from TechDrawGui::QGITemplate
TechDraw::DrawTemplate * pageTemplate
std::vector< TemplateTextField * > textFields
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGISVGTemplate()
QGISVGTemplate::QGISVGTemplate (QGSPage * scene)
References m_svgItem, m_svgRender, and ZVALUE::SVGTEMPLATE.
~QGISVGTemplate()
QGISVGTemplate::~QGISVGTemplate () virtual
References m_svgRender.
Member Function Documentation
createClickHandles()
void QGISVGTemplate::createClickHandles (void) protected
References Base::Console(), Base::ConsoleSingleton::Error(), QDomNodeModel::fromDomNode(), App::GetApplication(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), TechDraw::DrawSVGTemplate::getHeight(), getSVGTemplate(), App::Application::GetUserParameter(), App::PropertyFileIncluded::getValue(), TechDrawGui::Rez::guiX(), Base::ConsoleSingleton::Message(), TechDraw::DrawSVGTemplate::PageResult, ZVALUE::SVGTEMPLATE, TechDrawGui::QGITemplate::textFields, QDomNodeModel::toDomNode(), and Base::ConsoleSingleton::Warning().
Referenced by load().
draw()
void QGISVGTemplate::draw (void) virtual
Implements TechDrawGui::QGITemplate.
References getSVGTemplate(), App::PropertyFileIncluded::getValue(), load(), and TechDraw::DrawSVGTemplate::PageResult.
Referenced by updateView().
getSVGTemplate()
TechDraw::DrawSVGTemplate * QGISVGTemplate::getSVGTemplate ()
References Base::Persistence::getClassTypeId(), Base::BaseClass::isDerivedFrom(), and TechDrawGui::QGITemplate::pageTemplate.
Referenced by createClickHandles(), draw(), load(), and TechDrawGui::QGSPage::postProcessXml().
itemChange()
QVariant QGISVGTemplate::itemChange (GraphicsItemChange change, const QVariant & value) protected virtual
Reimplemented from TechDrawGui::QGITemplate.
load()
void QGISVGTemplate::load (const QString & fileName) protected
References createClickHandles(), firstTime, TechDraw::DrawSVGTemplate::getHeight(), getSVGTemplate(), TechDraw::DrawSVGTemplate::getWidth(), TechDrawGui::Rez::guiX(), m_svgItem, and m_svgRender.
Referenced by draw(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::loadDefaults(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle().
openFile()
void QGISVGTemplate::openFile (const QFile & file) protected
type()
int TechDrawGui::QGISVGTemplate::type (void) const
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
updateView()
void QGISVGTemplate::updateView (bool update = false) virtual
Reimplemented from TechDrawGui::QGITemplate.
References draw().
Referenced by TechDrawGui::ViewProviderTemplate::setMarkers().
Member Data Documentation
firstTime
bool TechDrawGui::QGISVGTemplate::firstTime protected
Referenced by load().
m_svgItem
QGraphicsSvgItem* TechDrawGui::QGISVGTemplate::m_svgItem protected
Referenced by load(), and QGISVGTemplate().
m_svgRender
QSvgRenderer* TechDrawGui::QGISVGTemplate::m_svgRender protected
Referenced by load(), QGISVGTemplate(), and ~QGISVGTemplate().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/QGISVGTemplate.h
FreeCAD/src/Mod/TechDraw/Gui/QGISVGTemplate.cpp