FreeCAD: FemGui::DlgSettingsFemExportAbaqusImp Class Reference
FemGui::DlgSettingsFemExportAbaqusImp Class Reference
#include <DlgSettingsFemExportAbaqusImp.h>
Public Member Functions
DlgSettingsFemExportAbaqusImp (QWidget *parent=nullptr)
~DlgSettingsFemExportAbaqusImp ()
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void loadSettings ()
void saveSettings ()
virtual void changeEvent (QEvent *e)=0
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Constructor & Destructor Documentation
DlgSettingsFemExportAbaqusImp()
DlgSettingsFemExportAbaqusImp::DlgSettingsFemExportAbaqusImp (QWidget * parent = nullptr)
References FemGui::Ui_DlgSettingsFemExportAbaqus::setupUi().
~DlgSettingsFemExportAbaqusImp()
DlgSettingsFemExportAbaqusImp::~DlgSettingsFemExportAbaqusImp ()
Member Function Documentation
changeEvent()
void DlgSettingsFemExportAbaqusImp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
References FemGui::Ui_DlgSettingsFemExportAbaqus::comboBoxElemChoiceParam, and FemGui::Ui_DlgSettingsFemExportAbaqus::retranslateUi().
loadSettings()
void DlgSettingsFemExportAbaqusImp::loadSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References FemGui::Ui_DlgSettingsFemExportAbaqus::checkBoxWriteGroups, FemGui::Ui_DlgSettingsFemExportAbaqus::comboBoxElemChoiceParam, App::GetApplication(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), and Gui::PrefWidget::onRestore().
saveSettings()
void DlgSettingsFemExportAbaqusImp::saveSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References FemGui::Ui_DlgSettingsFemExportAbaqus::checkBoxWriteGroups, FemGui::Ui_DlgSettingsFemExportAbaqus::comboBoxElemChoiceParam, App::GetApplication(), App::Application::GetParameterGroupByPath(), Gui::PrefWidget::onSave(), and ParameterGrp::SetInt().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/DlgSettingsFemExportAbaqusImp.h
FreeCAD/src/Mod/Fem/Gui/DlgSettingsFemExportAbaqusImp.cpp