FreeCAD: femexamples.material_multiple_bendingbeam_fivefaces Namespace Reference
femexamples.material_multiple_bendingbeam_fivefaces Namespace Reference
Functions
def get_information ()
def init_doc (doc=None)
def setup (doc=None, solvertype="ccxtools")
Variables
string mesh_name = "Mesh"
Function Documentation
get_information()
def femexamples.material_multiple_bendingbeam_fivefaces.get_information ()
init_doc()
def femexamples.material_multiple_bendingbeam_fivefaces.init_doc (doc = None)
Referenced by femexamples.material_multiple_bendingbeam_fivefaces.setup().
setup()
def femexamples.material_multiple_bendingbeam_fivefaces.setup (doc = None, solvertype = "ccxtools")
References femexamples.material_multiple_bendingbeam_fivefaces.init_doc(), ObjectsFem.makeAnalysis(), ObjectsFem.makeConstraintFixed(), ObjectsFem.makeConstraintForce(), ObjectsFem.makeElementGeometry2D(), ObjectsFem.makeMaterialSolid(), ObjectsFem.makeMeshGmsh(), ObjectsFem.makeSolverCalculix(), and ObjectsFem.makeSolverCalculixCcxTools().
Variable Documentation
mesh_name
string femexamples.material_multiple_bendingbeam_fivefaces.mesh_name = "Mesh"