FreeCAD: DrawSketchHandlerLine Class Reference
DrawSketchHandlerLine Class Reference
Public Types
enum SelectMode { STATUS_SEEK_First, STATUS_SEEK_Second, STATUS_End }
mode table
Public Member Functions
virtual void activated (ViewProviderSketch *)
DrawSketchHandlerLine ()
virtual void mouseMove (Base::Vector2d onSketchPos)
virtual bool pressButton (Base::Vector2d onSketchPos)
virtual bool releaseButton (Base::Vector2d onSketchPos)
virtual ~DrawSketchHandlerLine ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::none, bool createowncommand=true)
virtual void deactivated (ViewProviderSketch *)
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual void quit (void)
virtual void registerPressedKey (bool, int)
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Attributes
std::vector< Base::Vector2d > EditCurve
SelectMode Mode
std::vector< AutoConstraint > sugConstr1
std::vector< AutoConstraint > sugConstr2
Protected Attributes inherited from SketcherGui::DrawSketchHandler
QCursor actCursor
QPixmap actCursorPixmap
QCursor oldCursor
ViewProviderSketch * sketchgui
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
void addCursorTail (std::vector< QPixmap > &pixmaps)
void applyCursor (QCursor &newCursor)
void applyCursor (void)
qreal devicePixelRatio ()
unsigned long getCrosshairColor ()
void setCrosshairColor ()
void setCrosshairCursor (const char *svgName)
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
Sets a cursor for 3D inventor view.
void setSvgCursor (const QString &svgName, int x, int y, const std::map< unsigned long, unsigned long > &colorMapping=std::map< unsigned long, unsigned long >())
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
void unsetCursor (void)
Member Enumeration Documentation
SelectMode
enum DrawSketchHandlerLine::SelectMode
mode table
Enumerator
STATUS_SEEK_First
enum value -—.
STATUS_SEEK_Second
enum value -—.
STATUS_End
Constructor & Destructor Documentation
DrawSketchHandlerLine()
DrawSketchHandlerLine::DrawSketchHandlerLine ()
~DrawSketchHandlerLine()
virtual DrawSketchHandlerLine::~DrawSketchHandlerLine () virtual
Member Function Documentation
activated()
virtual void DrawSketchHandlerLine::activated (ViewProviderSketch *) virtual
Reimplemented from SketcherGui::DrawSketchHandler.
mouseMove()
virtual void DrawSketchHandlerLine::mouseMove (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
pressButton()
virtual bool DrawSketchHandlerLine::pressButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
releaseButton()
virtual bool DrawSketchHandlerLine::releaseButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Base::Console(), Sketcher::end, Base::ConsoleSingleton::Error(), SketcherGui::geometryCreationMode, App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, Sketcher::start, and SketcherGui::tryAutoRecomputeIfNotSolve().
Member Data Documentation
EditCurve
std::vector<Base::Vector2d> DrawSketchHandlerLine::EditCurve protected
Mode
SelectMode DrawSketchHandlerLine::Mode protected
sugConstr1
std::vector<AutoConstraint> DrawSketchHandlerLine::sugConstr1 protected
sugConstr2
std::vector<AutoConstraint> DrawSketchHandlerLine::sugConstr2 protected
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/Gui/CommandCreateGeo.cpp