FreeCAD: Part::BezierCurve2dPy Class Reference
Part::BezierCurve2dPy Class Reference
The python export class for Geom2dBezierCurve.
#include <BezierCurve2dPy.h>
Public Types
typedef Geom2dBezierCurve * PointerType
Public Types inherited from Part::Curve2dPy
typedef Geom2dCurve * PointerType
Public Types inherited from Part::Geometry2dPy
typedef Geometry2d * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
BezierCurve2dPy (Geom2dBezierCurve *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Part::Curve2dPy
Curve2dPy (Geom2dCurve *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * reverse (PyObject *args)
implementer for the reverse() method
PyObject * toShape (PyObject *args)
implementer for the toShape() method
PyObject * discretize (PyObject *args, PyObject *kwd)
implementer for the discretize() method
PyObject * length (PyObject *args)
implementer for the length() method
PyObject * parameterAtDistance (PyObject *args)
implementer for the parameterAtDistance() method
PyObject * value (PyObject *args)
implementer for the value() method
PyObject * tangent (PyObject *args)
implementer for the tangent() method
PyObject * parameter (PyObject *args)
implementer for the parameter() method
PyObject * normal (PyObject *args)
implementer for the normal() method
PyObject * curvature (PyObject *args)
implementer for the curvature() method
PyObject * centerOfCurvature (PyObject *args)
implementer for the centerOfCurvature() method
PyObject * intersectCC (PyObject *args)
implementer for the intersectCC() method
PyObject * toBSpline (PyObject *args)
implementer for the toBSpline() method
PyObject * approximateBSpline (PyObject *args)
implementer for the approximateBSpline() method
Py::String getContinuity (void) const
getter for the Continuity attribute
Py::Boolean getClosed (void) const
getter for the Closed attribute
Py::Boolean getPeriodic (void) const
getter for the Periodic attribute
Py::Float getFirstParameter (void) const
getter for the FirstParameter attribute
Py::Float getLastParameter (void) const
getter for the LastParameter attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geom2dCurve * getGeom2dCurvePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Part::Geometry2dPy
Geometry2dPy (Geometry2d *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geometry2d * getGeometry2dPtr (void) const
getter for the object handled by this class
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * copy (PyObject *args)
implementer for the copy() method
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::Curve2dPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_reverse (PyObject *self, PyObject *args)
callback for the reverse() method
static PyObject * staticCallback_toShape (PyObject *self, PyObject *args)
callback for the toShape() method
static PyObject * staticCallback_discretize (PyObject *self, PyObject *args, PyObject *kwd)
callback for the discretize() method
static PyObject * staticCallback_length (PyObject *self, PyObject *args)
callback for the length() method
static PyObject * staticCallback_parameterAtDistance (PyObject *self, PyObject *args)
callback for the parameterAtDistance() method
static PyObject * staticCallback_value (PyObject *self, PyObject *args)
callback for the value() method
static PyObject * staticCallback_tangent (PyObject *self, PyObject *args)
callback for the tangent() method
static PyObject * staticCallback_parameter (PyObject *self, PyObject *args)
callback for the parameter() method
static PyObject * staticCallback_normal (PyObject *self, PyObject *args)
callback for the normal() method
static PyObject * staticCallback_curvature (PyObject *self, PyObject *args)
callback for the curvature() method
static PyObject * staticCallback_centerOfCurvature (PyObject *self, PyObject *args)
callback for the centerOfCurvature() method
static PyObject * staticCallback_intersectCC (PyObject *self, PyObject *args)
callback for the intersectCC() method
static PyObject * staticCallback_toBSpline (PyObject *self, PyObject *args)
callback for the toBSpline() method
static PyObject * staticCallback_approximateBSpline (PyObject *self, PyObject *args)
callback for the approximateBSpline() method
static PyObject * staticCallback_getContinuity (PyObject *self, void *closure)
getter callback for the Continuity attribute
static int staticCallback_setContinuity (PyObject *self, PyObject *value, void *closure)
setter callback for the Continuity attribute
static PyObject * staticCallback_getClosed (PyObject *self, void *closure)
getter callback for the Closed attribute
static int staticCallback_setClosed (PyObject *self, PyObject *value, void *closure)
setter callback for the Closed attribute
static PyObject * staticCallback_getPeriodic (PyObject *self, void *closure)
getter callback for the Periodic attribute
static int staticCallback_setPeriodic (PyObject *self, PyObject *value, void *closure)
setter callback for the Periodic attribute
static PyObject * staticCallback_getFirstParameter (PyObject *self, void *closure)
getter callback for the FirstParameter attribute
static int staticCallback_setFirstParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the FirstParameter attribute
static PyObject * staticCallback_getLastParameter (PyObject *self, void *closure)
getter callback for the LastParameter attribute
static int staticCallback_setLastParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the LastParameter attribute
Static Public Member Functions inherited from Part::Geometry2dPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of BezierCurve2dPy.
static PyMethodDef Methods []
Methods structure of BezierCurve2dPy.
static PyTypeObject Type
Type structure of BezierCurve2dPy.
Static Public Attributes inherited from Part::Curve2dPy
static PyGetSetDef GetterSetter []
Attribute structure of Curve2dPy.
static PyMethodDef Methods []
Methods structure of Curve2dPy.
static PyTypeObject Type
Type structure of Curve2dPy.
Static Public Attributes inherited from Part::Geometry2dPy
static PyGetSetDef GetterSetter []
Attribute structure of Geometry2dPy.
static PyMethodDef Methods []
Methods structure of Geometry2dPy.
static PyTypeObject Type
Type structure of Geometry2dPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~BezierCurve2dPy ()
Protected Member Functions inherited from Part::Curve2dPy
~Curve2dPy ()
Protected Member Functions inherited from Part::Geometry2dPy
~Geometry2dPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * isRational (PyObject *args)
implementer for the isRational() method
PyObject * isPeriodic (PyObject *args)
implementer for the isPeriodic() method
PyObject * isClosed (PyObject *args)
implementer for the isClosed() method
PyObject * increase (PyObject *args)
implementer for the increase() method
PyObject * insertPoleAfter (PyObject *args)
implementer for the insertPoleAfter() method
PyObject * insertPoleBefore (PyObject *args)
implementer for the insertPoleBefore() method
PyObject * removePole (PyObject *args)
implementer for the removePole() method
PyObject * segment (PyObject *args)
implementer for the segment() method
PyObject * setPole (PyObject *args)
implementer for the setPole() method
PyObject * getPole (PyObject *args)
implementer for the getPole() method
PyObject * getPoles (PyObject *args)
implementer for the getPoles() method
PyObject * setPoles (PyObject *args)
implementer for the setPoles() method
PyObject * setWeight (PyObject *args)
implementer for the setWeight() method
PyObject * getWeight (PyObject *args)
implementer for the getWeight() method
PyObject * getWeights (PyObject *args)
implementer for the getWeights() method
PyObject * getResolution (PyObject *args)
implementer for the getResolution() method
static PyObject * staticCallback_isRational (PyObject *self, PyObject *args)
callback for the isRational() method
static PyObject * staticCallback_isPeriodic (PyObject *self, PyObject *args)
callback for the isPeriodic() method
static PyObject * staticCallback_isClosed (PyObject *self, PyObject *args)
callback for the isClosed() method
static PyObject * staticCallback_increase (PyObject *self, PyObject *args)
callback for the increase() method
static PyObject * staticCallback_insertPoleAfter (PyObject *self, PyObject *args)
callback for the insertPoleAfter() method
static PyObject * staticCallback_insertPoleBefore (PyObject *self, PyObject *args)
callback for the insertPoleBefore() method
static PyObject * staticCallback_removePole (PyObject *self, PyObject *args)
callback for the removePole() method
static PyObject * staticCallback_segment (PyObject *self, PyObject *args)
callback for the segment() method
static PyObject * staticCallback_setPole (PyObject *self, PyObject *args)
callback for the setPole() method
static PyObject * staticCallback_getPole (PyObject *self, PyObject *args)
callback for the getPole() method
static PyObject * staticCallback_getPoles (PyObject *self, PyObject *args)
callback for the getPoles() method
static PyObject * staticCallback_setPoles (PyObject *self, PyObject *args)
callback for the setPoles() method
static PyObject * staticCallback_setWeight (PyObject *self, PyObject *args)
callback for the setWeight() method
static PyObject * staticCallback_getWeight (PyObject *self, PyObject *args)
callback for the getWeight() method
static PyObject * staticCallback_getWeights (PyObject *self, PyObject *args)
callback for the getWeights() method
static PyObject * staticCallback_getResolution (PyObject *self, PyObject *args)
callback for the getResolution() method
callbacks and implementers for the python object attributes
Py::Long getDegree (void) const
getter for the Degree attribute
Py::Long getMaxDegree (void) const
getter for the MaxDegree attribute
Py::Long getNbPoles (void) const
getter for the NbPoles attribute
Py::Object getStartPoint (void) const
getter for the StartPoint attribute
Py::Object getEndPoint (void) const
getter for the EndPoint attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geom2dBezierCurve * getGeom2dBezierCurvePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getDegree (PyObject *self, void *closure)
getter callback for the Degree attribute
static int staticCallback_setDegree (PyObject *self, PyObject *value, void *closure)
setter callback for the Degree attribute
static PyObject * staticCallback_getMaxDegree (PyObject *self, void *closure)
getter callback for the MaxDegree attribute
static int staticCallback_setMaxDegree (PyObject *self, PyObject *value, void *closure)
setter callback for the MaxDegree attribute
static PyObject * staticCallback_getNbPoles (PyObject *self, void *closure)
getter callback for the NbPoles attribute
static int staticCallback_setNbPoles (PyObject *self, PyObject *value, void *closure)
setter callback for the NbPoles attribute
static PyObject * staticCallback_getStartPoint (PyObject *self, void *closure)
getter callback for the StartPoint attribute
static int staticCallback_setStartPoint (PyObject *self, PyObject *value, void *closure)
setter callback for the StartPoint attribute
static PyObject * staticCallback_getEndPoint (PyObject *self, void *closure)
getter callback for the EndPoint attribute
static int staticCallback_setEndPoint (PyObject *self, PyObject *value, void *closure)
setter callback for the EndPoint attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Geom2dBezierCurve.
Member Typedef Documentation
PointerType
typedef Geom2dBezierCurve* Part::BezierCurve2dPy::PointerType
Constructor & Destructor Documentation
~BezierCurve2dPy()
BezierCurve2dPy::~BezierCurve2dPy () protected
BezierCurve2dPy()
BezierCurve2dPy::BezierCurve2dPy (Geom2dBezierCurve * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getCustomAttributes()
PyObject * BezierCurve2dPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getDegree()
Py::Long BezierCurve2dPy::getDegree (void) const
getter for the Degree attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getDegree().
getEndPoint()
Py::Object BezierCurve2dPy::getEndPoint (void) const
getter for the EndPoint attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getEndPoint().
getGeom2dBezierCurvePtr()
Geom2dBezierCurve * BezierCurve2dPy::getGeom2dBezierCurvePtr (void) const
getter for the object handled by this class
Referenced by setPoles().
getMaxDegree()
Py::Long BezierCurve2dPy::getMaxDegree (void) const
getter for the MaxDegree attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getMaxDegree().
getNbPoles()
Py::Long BezierCurve2dPy::getNbPoles (void) const
getter for the NbPoles attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getNbPoles().
getPole()
PyObject * BezierCurve2dPy::getPole (PyObject * args)
implementer for the getPole() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getPole().
getPoles()
PyObject * BezierCurve2dPy::getPoles (PyObject * args)
implementer for the getPoles() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getPoles().
getResolution()
PyObject * BezierCurve2dPy::getResolution (PyObject * args)
implementer for the getResolution() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getResolution().
getStartPoint()
Py::Object BezierCurve2dPy::getStartPoint (void) const
getter for the StartPoint attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getStartPoint().
GetType()
virtual PyTypeObject* Part::BezierCurve2dPy::GetType (void) virtual
Reimplemented from Part::Curve2dPy.
getWeight()
PyObject * BezierCurve2dPy::getWeight (PyObject * args)
implementer for the getWeight() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getWeight().
getWeights()
PyObject * BezierCurve2dPy::getWeights (PyObject * args)
implementer for the getWeights() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getWeights().
increase()
PyObject * BezierCurve2dPy::increase (PyObject * args)
implementer for the increase() method
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_increase().
insertPoleAfter()
PyObject * BezierCurve2dPy::insertPoleAfter (PyObject * args)
implementer for the insertPoleAfter() method
References Part::Geometry2dPy::getGeometry2dPtr(), Part::PartExceptionOCCError, and draftgeoutils.general::vec().
Referenced by staticCallback_insertPoleAfter().
insertPoleBefore()
PyObject * BezierCurve2dPy::insertPoleBefore (PyObject * args)
implementer for the insertPoleBefore() method
References Part::Geometry2dPy::getGeometry2dPtr(), Part::PartExceptionOCCError, and draftgeoutils.general::vec().
Referenced by staticCallback_insertPoleBefore().
isClosed()
PyObject * BezierCurve2dPy::isClosed (PyObject * args)
implementer for the isClosed() method
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_isClosed().
isPeriodic()
PyObject * BezierCurve2dPy::isPeriodic (PyObject * args)
implementer for the isPeriodic() method
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_isPeriodic().
isRational()
PyObject * BezierCurve2dPy::isRational (PyObject * args)
implementer for the isRational() method
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_isRational().
PyInit()
int BezierCurve2dPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::Curve2dPy.
PyMake()
PyObject * BezierCurve2dPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References BezierCurve2dPy().
removePole()
PyObject * BezierCurve2dPy::removePole (PyObject * args)
implementer for the removePole() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_removePole().
representation()
std::string BezierCurve2dPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
segment()
PyObject * BezierCurve2dPy::segment (PyObject * args)
implementer for the segment() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_segment().
setCustomAttributes()
int BezierCurve2dPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setPole()
PyObject * BezierCurve2dPy::setPole (PyObject * args)
implementer for the setPole() method
References Part::Geometry2dPy::getGeometry2dPtr(), Part::PartExceptionOCCError, and draftgeoutils.general::vec().
Referenced by staticCallback_setPole().
setPoles()
PyObject * BezierCurve2dPy::setPoles (PyObject * args)
implementer for the setPoles() method
References getGeom2dBezierCurvePtr(), Part::PartExceptionOCCError, Part::Geom2dBezierCurve::setHandle(), Base::Vector2d::x, and Base::Vector2d::y.
Referenced by staticCallback_setPoles().
setWeight()
PyObject * BezierCurve2dPy::setWeight (PyObject * args)
implementer for the setWeight() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setWeight().
staticCallback_getDegree()
PyObject * BezierCurve2dPy::staticCallback_getDegree (PyObject * self, void * closure) static
getter callback for the Degree attribute
References Base::BaseExceptionFreeCADError, getDegree(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getEndPoint()
PyObject * BezierCurve2dPy::staticCallback_getEndPoint (PyObject * self, void * closure) static
getter callback for the EndPoint attribute
References Base::BaseExceptionFreeCADError, getEndPoint(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMaxDegree()
PyObject * BezierCurve2dPy::staticCallback_getMaxDegree (PyObject * self, void * closure) static
getter callback for the MaxDegree attribute
References Base::BaseExceptionFreeCADError, getMaxDegree(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNbPoles()
PyObject * BezierCurve2dPy::staticCallback_getNbPoles (PyObject * self, void * closure) static
getter callback for the NbPoles attribute
References Base::BaseExceptionFreeCADError, getNbPoles(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPole()
PyObject * BezierCurve2dPy::staticCallback_getPole (PyObject * self, PyObject * args) static
callback for the getPole() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPole(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getPoles()
PyObject * BezierCurve2dPy::staticCallback_getPoles (PyObject * self, PyObject * args) static
callback for the getPoles() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPoles(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getResolution()
PyObject * BezierCurve2dPy::staticCallback_getResolution (PyObject * self, PyObject * args) static
callback for the getResolution() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getResolution(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getStartPoint()
PyObject * BezierCurve2dPy::staticCallback_getStartPoint (PyObject * self, void * closure) static
getter callback for the StartPoint attribute
References Base::BaseExceptionFreeCADError, getStartPoint(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getWeight()
PyObject * BezierCurve2dPy::staticCallback_getWeight (PyObject * self, PyObject * args) static
callback for the getWeight() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getWeight(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getWeights()
PyObject * BezierCurve2dPy::staticCallback_getWeights (PyObject * self, PyObject * args) static
callback for the getWeights() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getWeights(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_increase()
PyObject * BezierCurve2dPy::staticCallback_increase (PyObject * self, PyObject * args) static
callback for the increase() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, increase(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_insertPoleAfter()
PyObject * BezierCurve2dPy::staticCallback_insertPoleAfter (PyObject * self, PyObject * args) static
callback for the insertPoleAfter() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, insertPoleAfter(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_insertPoleBefore()
PyObject * BezierCurve2dPy::staticCallback_insertPoleBefore (PyObject * self, PyObject * args) static
callback for the insertPoleBefore() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, insertPoleBefore(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_isClosed()
PyObject * BezierCurve2dPy::staticCallback_isClosed (PyObject * self, PyObject * args) static
callback for the isClosed() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isClosed(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_isPeriodic()
PyObject * BezierCurve2dPy::staticCallback_isPeriodic (PyObject * self, PyObject * args) static
callback for the isPeriodic() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), isPeriodic(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_isRational()
PyObject * BezierCurve2dPy::staticCallback_isRational (PyObject * self, PyObject * args) static
callback for the isRational() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), isRational(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_removePole()
PyObject * BezierCurve2dPy::staticCallback_removePole (PyObject * self, PyObject * args) static
callback for the removePole() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removePole(), and Base::PyObjectBase::startNotify().
staticCallback_segment()
PyObject * BezierCurve2dPy::staticCallback_segment (PyObject * self, PyObject * args) static
callback for the segment() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), segment(), and Base::PyObjectBase::startNotify().
staticCallback_setDegree()
int BezierCurve2dPy::staticCallback_setDegree (PyObject * self, PyObject * value, void * closure) static
setter callback for the Degree attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setEndPoint()
int BezierCurve2dPy::staticCallback_setEndPoint (PyObject * self, PyObject * value, void * closure) static
setter callback for the EndPoint attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setMaxDegree()
int BezierCurve2dPy::staticCallback_setMaxDegree (PyObject * self, PyObject * value, void * closure) static
setter callback for the MaxDegree attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setNbPoles()
int BezierCurve2dPy::staticCallback_setNbPoles (PyObject * self, PyObject * value, void * closure) static
setter callback for the NbPoles attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPole()
PyObject * BezierCurve2dPy::staticCallback_setPole (PyObject * self, PyObject * args) static
callback for the setPole() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setPole(), and Base::PyObjectBase::startNotify().
staticCallback_setPoles()
PyObject * BezierCurve2dPy::staticCallback_setPoles (PyObject * self, PyObject * args) static
callback for the setPoles() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setPoles(), and Base::PyObjectBase::startNotify().
staticCallback_setStartPoint()
int BezierCurve2dPy::staticCallback_setStartPoint (PyObject * self, PyObject * value, void * closure) static
setter callback for the StartPoint attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setWeight()
PyObject * BezierCurve2dPy::staticCallback_setWeight (PyObject * self, PyObject * args) static
callback for the setWeight() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setWeight(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef BezierCurve2dPy::GetterSetter static
Attribute structure of BezierCurve2dPy.
Methods
PyMethodDef BezierCurve2dPy::Methods static
Methods structure of BezierCurve2dPy.
Type
PyTypeObject BezierCurve2dPy::Type static
Type structure of BezierCurve2dPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/Geom2d/BezierCurve2dPy.h
Sources/FreeCAD/src/Mod/Part/App/Geom2d/BezierCurve2dPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/Geom2d/BezierCurve2dPy.cpp