FreeCAD: Path::CommandPy Class Reference
Path::CommandPy Class Reference
The python export class for Command.
#include <CommandPy.h>
Public Types
typedef Command * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
CommandPy (Command *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of CommandPy.
static PyMethodDef Methods []
Methods structure of CommandPy.
static PyTypeObject Type
Type structure of CommandPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~CommandPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * toGCode (PyObject *args)
implementer for the toGCode() method
PyObject * setFromGCode (PyObject *args)
implementer for the setFromGCode() method
PyObject * transform (PyObject *args)
implementer for the transform() method
static PyObject * staticCallback_toGCode (PyObject *self, PyObject *args)
callback for the toGCode() method
static PyObject * staticCallback_setFromGCode (PyObject *self, PyObject *args)
callback for the setFromGCode() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
callbacks and implementers for the python object attributes
Py::String getName (void) const
getter for the Name attribute
void setName (Py::String arg)
setter for the Name attribute
Py::Dict getParameters (void) const
getter for the Parameters attribute
void setParameters (Py::Dict arg)
setter for the Parameters attribute
Py::Object getPlacement (void) const
getter for the Placement attribute
void setPlacement (Py::Object arg)
setter for the Placement attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Command * getCommandPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getName (PyObject *self, void *closure)
getter callback for the Name attribute
static int staticCallback_setName (PyObject *self, PyObject *value, void *closure)
setter callback for the Name attribute
static PyObject * staticCallback_getParameters (PyObject *self, void *closure)
getter callback for the Parameters attribute
static int staticCallback_setParameters (PyObject *self, PyObject *value, void *closure)
setter callback for the Parameters attribute
static PyObject * staticCallback_getPlacement (PyObject *self, void *closure)
getter callback for the Placement attribute
static int staticCallback_setPlacement (PyObject *self, PyObject *value, void *closure)
setter callback for the Placement attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Command.
Member Typedef Documentation
PointerType
typedef Command* Path::CommandPy::PointerType
Constructor & Destructor Documentation
~CommandPy()
CommandPy::~CommandPy () protected
CommandPy()
CommandPy::CommandPy (Command * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake(), and transform().
Member Function Documentation
getCommandPtr()
Command * CommandPy::getCommandPtr (void) const
getter for the object handled by this class
Referenced by getCustomAttributes(), getName(), getParameters(), getPlacement(), PyInit(), setCustomAttributes(), setFromGCode(), setName(), setParameters(), setPlacement(), toGCode(), and transform().
getCustomAttributes()
PyObject * CommandPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
References getCommandPtr().
getName()
Py::String CommandPy::getName (void) const
getter for the Name attribute
References getCommandPtr().
Referenced by staticCallback_getName().
getParameters()
Py::Dict CommandPy::getParameters (void) const
getter for the Parameters attribute
References getCommandPtr().
Referenced by staticCallback_getParameters().
getPlacement()
Py::Object CommandPy::getPlacement (void) const
getter for the Placement attribute
References getCommandPtr().
Referenced by staticCallback_getPlacement().
GetType()
virtual PyTypeObject* Path::CommandPy::GetType (void) virtual
Reimplemented from Base::PersistencePy.
PyInit()
int CommandPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PersistencePy.
References getCommandPtr(), Path::Command::Parameters, Path::Command::setFromGCode(), Path::Command::setFromPlacement(), and Base::PlacementPy::Type.
PyMake()
PyObject * CommandPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References CommandPy().
representation()
std::string CommandPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int CommandPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
References getCommandPtr(), and Path::Command::Parameters.
setFromGCode()
PyObject * CommandPy::setFromGCode (PyObject * args)
implementer for the setFromGCode() method
References getCommandPtr(), and Path::Command::setFromGCode().
Referenced by staticCallback_setFromGCode().
setName()
void CommandPy::setName (Py::String arg)
setter for the Name attribute
References getCommandPtr(), and Path::Command::Name.
Referenced by staticCallback_setName().
setParameters()
void CommandPy::setParameters (Py::Dict arg)
setter for the Parameters attribute
References getCommandPtr(), and Path::Command::Parameters.
Referenced by staticCallback_setParameters().
setPlacement()
void CommandPy::setPlacement (Py::Object arg)
setter for the Placement attribute
References getCommandPtr(), PyType_Object::o, Path::Command::setFromPlacement(), and Base::PlacementPy::Type.
Referenced by staticCallback_setPlacement().
staticCallback_getName()
PyObject * CommandPy::staticCallback_getName (PyObject * self, void * closure) static
getter callback for the Name attribute
References Base::BaseExceptionFreeCADError, getName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getParameters()
PyObject * CommandPy::staticCallback_getParameters (PyObject * self, void * closure) static
getter callback for the Parameters attribute
References Base::BaseExceptionFreeCADError, getParameters(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPlacement()
PyObject * CommandPy::staticCallback_getPlacement (PyObject * self, void * closure) static
getter callback for the Placement attribute
References Base::BaseExceptionFreeCADError, getPlacement(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setFromGCode()
PyObject * CommandPy::staticCallback_setFromGCode (PyObject * self, PyObject * args) static
callback for the setFromGCode() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setFromGCode(), and Base::PyObjectBase::startNotify().
staticCallback_setName()
int CommandPy::staticCallback_setName (PyObject * self, PyObject * value, void * closure) static
setter callback for the Name attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setName().
staticCallback_setParameters()
int CommandPy::staticCallback_setParameters (PyObject * self, PyObject * value, void * closure) static
setter callback for the Parameters attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setParameters().
staticCallback_setPlacement()
int CommandPy::staticCallback_setPlacement (PyObject * self, PyObject * value, void * closure) static
setter callback for the Placement attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setPlacement().
staticCallback_toGCode()
PyObject * CommandPy::staticCallback_toGCode (PyObject * self, PyObject * args) static
callback for the toGCode() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and toGCode().
staticCallback_transform()
PyObject * CommandPy::staticCallback_transform (PyObject * self, PyObject * args) static
callback for the transform() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and transform().
toGCode()
PyObject * CommandPy::toGCode (PyObject * args)
implementer for the toGCode() method
References getCommandPtr().
Referenced by staticCallback_toGCode().
transform()
PyObject * CommandPy::transform (PyObject * args)
implementer for the transform() method
References CommandPy(), getCommandPtr(), Path::Command::transform(), and Base::PlacementPy::Type.
Referenced by staticCallback_transform().
Member Data Documentation
GetterSetter
PyGetSetDef CommandPy::GetterSetter static
Initial value:
= {
    {"Name",
        (getter) staticCallback_getName,
        (setter) staticCallback_setName,
        "The name of the command",
        NULL
    },
    {"Parameters",
        (getter) staticCallback_getParameters,
        (setter) staticCallback_setParameters,
        "The parameters of the command",
        NULL
    },
    {"Placement",
        (getter) staticCallback_getPlacement,
        (setter) staticCallback_setPlacement,
        "The coordinates of the endpoint of the command",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of CommandPy.
Methods
PyMethodDef CommandPy::Methods static
Initial value:
= {
    {"toGCode",
        reinterpret_cast<PyCFunction>( staticCallback_toGCode ),
        METH_VARARGS,
        "toGCode(): returns a GCode representation of the command"
    },
    {"setFromGCode",
        reinterpret_cast<PyCFunction>( staticCallback_setFromGCode ),
        METH_VARARGS,
        "toGCode(): returns a GCode representation of the command"
    },
    {"transform",
        reinterpret_cast<PyCFunction>( staticCallback_transform ),
        METH_VARARGS,
        "transform(Placement): returns a copy of this command transformed by the given placement"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of CommandPy.
Type
PyTypeObject CommandPy::Type static
Type structure of CommandPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), Path::PathPy::addCommands(), ArchStructure.StructSelectionObserver::addSelection(), PathSimulator::PathSimPy::ApplyCommand(), ArchSite.Compass::buildCoordinates(), Path::PathPy::insertCommand(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), Path::PathPy::PyInit(), and Path::PathPy::setCommands().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/CommandPy.h
Sources/FreeCAD/src/Gui/CommandPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/CommandPy.cpp