FreeCAD: MeshCore::MeshPointArray Class Reference
MeshCore::MeshPointArray Class Reference
Stores all data points of the mesh structure.
#include <Elements.h>
Public Member Functions
Construction
MeshPointArray ()
MeshPointArray (PointIndex ulSize)
MeshPointArray (const MeshPointArray &)
copy-constructor
~MeshPointArray ()
Flag state
Note
All flag methods are const as they do NOT change the actual properties of the object
void SetFlag (MeshPoint::TFlagType tF) const
Sets the flag for all points.
void ResetFlag (MeshPoint::TFlagType tF) const
Resets the flag for all points.
void ResetInvalid () const
Sets all points invalid.
void SetProperty (unsigned long ulVal) const
Sets the property for all points.
MeshPointArray & operator= (const MeshPointArray &rclPAry)
void Transform (const Base::Matrix4D &)
PointIndex Get (const MeshPoint &rclPoint)
Searches for the first point index Two points are equal if the distance is less than EPSILON.
PointIndex GetOrAddIndex (const MeshPoint &rclPoint)
Searches for the first point index Two points are equal if the distance is less than EPSILON.
Detailed Description
Stores all data points of the mesh structure.
Constructor & Destructor Documentation
MeshPointArray() [1/3]
MeshCore::MeshPointArray::MeshPointArray ()
MeshPointArray() [2/3]
MeshCore::MeshPointArray::MeshPointArray (PointIndex ulSize)
MeshPointArray() [3/3]
MeshPointArray::MeshPointArray (const MeshPointArray & ary)
copy-constructor
~MeshPointArray()
MeshCore::MeshPointArray::~MeshPointArray ()
Member Function Documentation
Get()
PointIndex MeshPointArray::Get (const MeshPoint & rclPoint)
Searches for the first point index Two points are equal if the distance is less than EPSILON.
If no such points is found POINT_INDEX_MAX is returned.
References DraftVecUtils::find(), and MeshCore::POINT_INDEX_MAX.
Referenced by GetOrAddIndex().
GetOrAddIndex()
PointIndex MeshPointArray::GetOrAddIndex (const MeshPoint & rclPoint)
Searches for the first point index Two points are equal if the distance is less than EPSILON.
If no such points is found the point is added to the array at end and its index is returned.
References Get(), and MeshCore::POINT_INDEX_MAX.
operator=()
MeshPointArray & MeshPointArray::operator= (const MeshPointArray & rclPAry)
ResetFlag()
void MeshPointArray::ResetFlag (MeshPoint::TFlagType tF) const
Resets the flag for all points.
Referenced by MeshCore::MeshRemoveNeedles::Fixup().
ResetInvalid()
void MeshPointArray::ResetInvalid () const
Sets all points invalid.
Referenced by MeshCore::MeshRemoveNeedles::Fixup(), and MeshCore::MeshCleanup::RemoveInvalids().
SetFlag()
void MeshPointArray::SetFlag (MeshPoint::TFlagType tF) const
Sets the flag for all points.
Referenced by MeshCore::MeshAlgorithm::GetFacetsBorders(), and MeshCore::MeshCleanup::RemoveInvalids().
SetProperty()
void MeshPointArray::SetProperty (unsigned long ulVal) const
Sets the property for all points.
Referenced by MeshCore::MeshInput::LoadOBJ().
Transform()
void MeshPointArray::Transform (const Base::Matrix4D & mat)
References Base::Matrix4D::multVec().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/Core/Elements.h
FreeCAD/src/Mod/Mesh/App/Core/Elements.cpp