FreeCAD: SketcherGui::SketcherSettingsDisplay Class Reference
SketcherGui::SketcherSettingsDisplay Class Reference
The SketcherSettings class implements a preference page to change sketcher display settings.
#include <SketcherSettings.h>
Public Member Functions
void loadSettings ()
void saveSettings ()
SketcherSettingsDisplay (QWidget *parent=0)
~SketcherSettingsDisplay ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=0)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
Detailed Description
The SketcherSettings class implements a preference page to change sketcher display settings.
Author
Werner Mayer
Constructor & Destructor Documentation
SketcherSettingsDisplay()
SketcherSettingsDisplay::SketcherSettingsDisplay (QWidget * parent = 0)
References draftgeoutils.intersections::connect().
~SketcherSettingsDisplay()
SketcherSettingsDisplay::~SketcherSettingsDisplay ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void SketcherSettingsDisplay::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
loadSettings()
void SketcherSettingsDisplay::loadSettings () virtual
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), ParameterGrp::GetInt(), and App::Application::GetParameterGroupByPath().
saveSettings()
void SketcherSettingsDisplay::saveSettings () virtual
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetInt().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sketcher/Gui/SketcherSettings.h
Sources/FreeCAD/src/Mod/Sketcher/Gui/SketcherSettings.cpp