FreeCAD: Base::Axis Class Reference
Base::Axis Class Reference
The Axis class.
#include <Axis.h>
Public Member Functions
Axis (const Axis &)
Axis (const Vector3d &Orig, const Vector3d &Dir)
Axis (void)
default constructor
const Vector3d & getBase (void) const
const Vector3d & getDirection (void) const
void move (const Vector3d &MovVec)
bool operator!= (const Axis &) const
Axis operator* (const Placement &p) const
Axis & operator*= (const Placement &p)
Operators.
Axis & operator= (const Axis &)
bool operator== (const Axis &) const
void reverse ()
Axis reversed () const
void setBase (const Vector3d &Orig)
void setDirection (const Vector3d &Dir)
~Axis ()
Destruction.
Detailed Description
The Axis class.
Constructor & Destructor Documentation
Axis() [1/3]
Axis::Axis (void)
default constructor
Axis() [2/3]
Axis::Axis (const Axis & that)
Axis() [3/3]
Axis::Axis (const Vector3d & Orig, const Vector3d & Dir)
~Axis()
Base::Axis::~Axis ()
Destruction.
Member Function Documentation
getBase()
const Vector3d& Base::Axis::getBase (void) const
Referenced by Base::CoordinateSystem::displacement(), PartDesign::ProfileBased::getAxis(), PartDesign::Mirrored::getTransformations(), PartDesign::PolarPattern::getTransformations(), Base::AxisPy::representation(), and Base::CoordinateSystem::transformTo().
getDirection()
const Vector3d& Base::Axis::getDirection (void) const
Referenced by Base::CoordinateSystem::displacement(), PartDesign::ProfileBased::getAxis(), PartDesign::LinearPattern::getTransformations(), PartDesign::Mirrored::getTransformations(), PartDesign::PolarPattern::getTransformations(), Base::AxisPy::representation(), Base::CoordinateSystem::setXDirection(), Base::CoordinateSystem::setYDirection(), and Base::CoordinateSystem::transform().
move()
void Axis::move (const Vector3d & MovVec)
Referenced by draftguitools.gui_circulararray.CircularArray::Activated(), draftguitools.gui_polararray.PolarArray::Activated(), and Base::AxisPy::move().
operator!=()
bool Axis::operator!= (const Axis & that) const
operator*()
Axis Axis::operator* (const Placement & p) const
operator*=()
Axis & Axis::operator*= (const Placement & p)
Operators.
operator=()
Axis & Axis::operator= (const Axis & New)
operator==()
bool Axis::operator== (const Axis & that) const
reverse()
void Axis::reverse ()
reversed()
Axis Axis::reversed () const
Referenced by Base::AxisPy::reversed().
setBase()
void Base::Axis::setBase (const Vector3d & Orig)
Referenced by PartDesign::LinearPattern::getTransformations(), PartDesign::Mirrored::getTransformations(), Base::CoordinateSystem::setAxes(), Base::AxisPy::setBase(), and Base::CoordinateSystem::setPlacement().
setDirection()
void Base::Axis::setDirection (const Vector3d & Dir)
Referenced by PartDesign::LinearPattern::getTransformations(), PartDesign::Mirrored::getTransformations(), Base::CoordinateSystem::setAxes(), Base::AxisPy::setDirection(), Base::CoordinateSystem::setPlacement(), and Base::CoordinateSystem::transform().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Base/Axis.h
Sources/FreeCAD/src/Base/Axis.cpp