FreeCAD: StdMeshers_TNode Class Reference
StdMeshers_TNode Class Reference
#include <StdMeshers_Penta_3D.hxx>
Public Member Functions
int BaseNodeID () const
const SMDS_MeshNode * Node () const
const gp_XYZ & NormCoord () const
void SetBaseNodeID (const int theID)
void SetNode (const SMDS_MeshNode *theNode)
void SetNormCoord (const gp_XYZ &theXYZ)
void SetShapeSupportID (const int theID)
int ShapeSupportID () const
StdMeshers_TNode ()
Constructor & Destructor Documentation
StdMeshers_TNode()
StdMeshers_TNode::StdMeshers_TNode ()
Member Function Documentation
BaseNodeID()
int StdMeshers_TNode::BaseNodeID () const
Referenced by StdMeshers_Penta_3D::FindNodeOnShape(), StdMeshers_Penta_3D::MakeConnectingMap(), and StdMeshers_Penta_3D::MakeNodes().
Node()
const SMDS_MeshNode* StdMeshers_TNode::Node () const
Referenced by StdMeshers_Penta_3D::MakeMeshOnFxy1(), StdMeshers_Penta_3D::MakeNodes(), and StdMeshers_Penta_3D::MakeVolumeMesh().
NormCoord()
const gp_XYZ& StdMeshers_TNode::NormCoord () const
Referenced by StdMeshers_Penta_3D::MakeNodes().
SetBaseNodeID()
void StdMeshers_TNode::SetBaseNodeID (const int theID)
Referenced by StdMeshers_Penta_3D::MakeNodes().
SetNode()
void StdMeshers_TNode::SetNode (const SMDS_MeshNode * theNode)
Referenced by StdMeshers_Penta_3D::CreateNode(), StdMeshers_Penta_3D::FindNodeOnShape(), and StdMeshers_Penta_3D::MakeNodes().
SetNormCoord()
void StdMeshers_TNode::SetNormCoord (const gp_XYZ & theXYZ)
Referenced by StdMeshers_Penta_3D::MakeNodes().
SetShapeSupportID()
void StdMeshers_TNode::SetShapeSupportID (const int theID)
Referenced by StdMeshers_Penta_3D::MakeNodes().
ShapeSupportID()
int StdMeshers_TNode::ShapeSupportID () const
Referenced by StdMeshers_Penta_3D::MakeNodes(), and StdMeshers_Penta_3D::MakeVolumeMesh().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_Penta_3D.hxx