FreeCAD: draftviewproviders.view_point.ViewProviderPoint Class Reference
draftviewproviders.view_point.ViewProviderPoint Class Reference
Workbenches » Python workbenches » Draft » draftviewproviders
Public Member Functions
def getIcon (self)
def onChanged (self, vobj, prop)
Public Member Functions inherited from draftviewproviders.view_base.ViewProviderDraft
def attach (self, vobj)
def claimChildren (self)
def execute (self, vobj)
def getDefaultDisplayMode (self)
def getDisplayModes (self, vobj)
def getIcon (self)
def onChanged (self, vobj, prop)
def setDisplayMode (self, mode)
def setEdit (self, vobj, mode=0)
def unsetEdit (self, vobj, mode=0)
def updateData (self, obj, prop)
Additional Inherited Members
Public Attributes inherited from draftviewproviders.view_base.ViewProviderDraft
Object
texcoords
texture
Detailed Description
A viewprovider for the Draft Point object
Member Function Documentation
getIcon()
def draftviewproviders.view_point.ViewProviderPoint.getIcon (self)
Return the path to the icon used by the view provider.
The path can be a full path in the system, or a relative path
inside the compiled resource file.
It can also be a string that defines the icon in XPM format.
Override this method to provide a specific icon
for the object in the tree view.
By default it returns the path to the `Draft_Draft.svg` icon.
Returns
-------
str
    `':/icons/Draft_Draft.svg'`
Reimplemented from draftviewproviders.view_base.ViewProviderDraft.
Referenced by ArchAxisSystem.AxisSystemTaskPanel.update(), ArchComponent.ComponentTaskPanel.update(), and ArchSectionPlane.SectionPlaneTaskPanel.update().
onChanged()
def draftviewproviders.view_point.ViewProviderPoint.onChanged (self, vobj, prop)
Run when a view property is changed.
Override this method to handle the behavior
of the view provider depending on changes that occur to its properties
such as line color, line width, point color, point size,
draw style, shape color, transparency, and others.
This method  updates the texture and pattern if
the properties `TextureImage`, `Pattern`, `DiffuseColor`,
and `PatternSize` change.
Parameters
----------
vobj : the view provider of the scripted object.
    This is `obj.ViewObject`.
prop : str
    Name of the property that was modified.
Reimplemented from draftviewproviders.view_base.ViewProviderDraft.
Referenced by ArchStructure.CommandStructuralSystem.Activated(), draftviewproviders.view_base.ViewProviderDraft.attach(), ArchSite.Compass.buildCoordinates(), draftobjects.wire.Wire.execute(), ArchBuildingPart.ViewProviderBuildingPart.updateData(), ArchPanel.ViewProviderPanelCut.updateData(), ArchPanel.ViewProviderPanelSheet.updateData(), draftviewproviders.view_label.ViewProviderLabel.updateData(), draftviewproviders.view_layer.ViewProviderLayer.updateData(), and draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy.updateData().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Draft/draftviewproviders/view_point.py