FreeCAD: Robot Namespace Reference
Robot Namespace Reference
Classes
struct AxisDefinition
Definition of the Axis properties.
class Edge2TracObject
class Module
class PropertyTrajectory
The part shape property class.
class Robot6Axis
The representation for a 6-Axis industry grade robot.
class Robot6AxisPy
The python export class for Robot6Axis.
class RobotAlgos
Algo class for projecting shapes and creating SVG output of it.
class RobotObject
class RobotObjectPy
The python export class for RobotObject.
class Simulation
Algo class for projecting shapes and creating SVG output of it.
class Trajectory
The representation of a Trajectory.
class TrajectoryCompound
class TrajectoryDressUpObject
class TrajectoryObject
class TrajectoryPy
The python export class for Trajectory.
class Waypoint
The representation of a waypoint in a trajectory.
class WaypointPy
The python export class for Waypoint.
Functions
PyObject * initModule ()
KDL::Frame toFrame (const Base::Placement &To)
Base::Placement toPlacement (const KDL::Frame &To)
Function Documentation
initModule()
PyObject* Robot::initModule ()
toFrame()
KDL::Frame Robot::toFrame (const Base::Placement & To)
References Base::Placement::getPosition(), and Base::Placement::getRotation().
Referenced by Robot::Trajectory::generateTrajectory(), and Robot::Robot6Axis::Restore().
toPlacement()
Base::Placement Robot::toPlacement (const KDL::Frame & To)
Referenced by Robot::Trajectory::getPosition(), and Robot::Robot6Axis::Save().