FreeCAD: Gui::Dialog::DlgExpressionInput Class Reference
Gui::Dialog::DlgExpressionInput Class Reference
#include <DlgExpressionInput.h>
Public Slots
void show ()
Public Member Functions
bool discardedFormula () const
DlgExpressionInput (const App::ObjectIdentifier &_path, std::shared_ptr< const App::Expression > _expression, const Base::Unit &_impliedUnit, QWidget *parent=nullptr)
bool eventFilter (QObject *obj, QEvent *event)
QPoint expressionPosition () const
std::shared_ptr< App::Expression > getExpression () const
void setExpressionInputSize (int width, int height)
~DlgExpressionInput ()
Protected Member Functions
void mousePressEvent (QMouseEvent *)
void mouseReleaseEvent (QMouseEvent *)
void showEvent (QShowEvent *)
Constructor & Destructor Documentation
DlgExpressionInput()
DlgExpressionInput::DlgExpressionInput (const App::ObjectIdentifier & _path, std::shared_ptr< const App::Expression > _expression, const Base::Unit & _impliedUnit, QWidget * parent = nullptr) explicit
References draftgeoutils.intersections::connect(), Ui_DlgExpressionInput::discardBtn, Ui_DlgExpressionInput::expression, Base::Tools::fromStdString(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), Ui_DlgExpressionInput::horizontalSpacer_3, Gui::ExpressionLineEdit::setDocumentObject(), Ui_DlgExpressionInput::setupUi(), and Ui_DlgExpressionInput::verticalLayout.
~DlgExpressionInput()
DlgExpressionInput::~DlgExpressionInput ()
Member Function Documentation
discardedFormula()
bool Gui::Dialog::DlgExpressionInput::discardedFormula () const
eventFilter()
bool DlgExpressionInput::eventFilter (QObject * obj, QEvent * event)
References Gui::ExpressionLineEdit::completerActive(), and Ui_DlgExpressionInput::expression.
expressionPosition()
QPoint DlgExpressionInput::expressionPosition () const
References Ui_DlgExpressionInput::expression.
getExpression()
std::shared_ptr< App::Expression > Gui::Dialog::DlgExpressionInput::getExpression () const
mousePressEvent()
void DlgExpressionInput::mousePressEvent (QMouseEvent * ev) protected
References Gui::ExpressionLineEdit::completerActive(), and Ui_DlgExpressionInput::expression.
mouseReleaseEvent()
void DlgExpressionInput::mouseReleaseEvent (QMouseEvent * ev) protected
setExpressionInputSize()
void DlgExpressionInput::setExpressionInputSize (int width, int height)
References Ui_DlgExpressionInput::expression.
show
void DlgExpressionInput::show () slot
References Ui_DlgExpressionInput::expression.
Referenced by Mod.Show.mTempoVis.TempoVis::show_all_dependencies(), and Mod.Show.mTempoVis.TempoVis::show_all_dependent().
showEvent()
void DlgExpressionInput::showEvent (QShowEvent * ev) protected
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgExpressionInput.h
FreeCAD/src/Gui/DlgExpressionInput.cpp