FreeCAD: PathScripts.PathPost Namespace Reference
PathScripts.PathPost Namespace Reference
Classes
class CommandPathPost
class DlgSelectPostProcessor
Functions
def buildPostList (job)
def processFileNameSubstitutions (job, subpartname, sequencenumber, outputpath, filename, ext)
def resolveFileName (job, subpartname, sequencenumber)
Variables
LOG_MODULE = PathLog.thisModule()
translate = FreeCAD.Qt.translate
Function Documentation
buildPostList()
def PathScripts.PathPost.buildPostList (job)
Takes the job and determines the specific objects and order to
postprocess  Returns a list of objects which can be passed to
exportObjectsWith() for final posting.
Referenced by PathScripts.PathPost.CommandPathPost.Activated().
processFileNameSubstitutions()
def PathScripts.PathPost.processFileNameSubstitutions (job, subpartname, sequencenumber, outputpath, filename, ext)
Process any substitutions in the outputpath or filename.
Referenced by PathScripts.PathPost.resolveFileName().
resolveFileName()
def PathScripts.PathPost.resolveFileName (job, subpartname, sequencenumber)
References PathScripts.PathPost.processFileNameSubstitutions().
Referenced by PathScripts.PathPost.CommandPathPost.exportObjectsWith().
Variable Documentation
LOG_MODULE
PathScripts.PathPost.LOG_MODULE = PathLog.thisModule()
translate
PathScripts.PathPost.translate = FreeCAD.Qt.translate