FreeCAD: App::MaterialPy Class Reference
App::MaterialPy Class Reference
The python export class for Material.
#include <MaterialPy.h>
Public Types
typedef Material * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
MaterialPy (Material *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of MaterialPy.
static PyMethodDef Methods []
Methods structure of MaterialPy.
static PyTypeObject Type
Type structure of MaterialPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~MaterialPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * set (PyObject *args)
implementer for the set() method
static PyObject * staticCallback_set (PyObject *self, PyObject *args)
callback for the set() method
callbacks and implementers for the python object attributes
Py::Tuple getAmbientColor (void) const
getter for the AmbientColor attribute
void setAmbientColor (Py::Tuple arg)
setter for the AmbientColor attribute
Py::Tuple getDiffuseColor (void) const
getter for the DiffuseColor attribute
void setDiffuseColor (Py::Tuple arg)
setter for the DiffuseColor attribute
Py::Tuple getEmissiveColor (void) const
getter for the EmissiveColor attribute
void setEmissiveColor (Py::Tuple arg)
setter for the EmissiveColor attribute
Py::Tuple getSpecularColor (void) const
getter for the SpecularColor attribute
void setSpecularColor (Py::Tuple arg)
setter for the SpecularColor attribute
Py::Float getShininess (void) const
getter for the Shininess attribute
void setShininess (Py::Float arg)
setter for the Shininess attribute
Py::Float getTransparency (void) const
getter for the Transparency attribute
void setTransparency (Py::Float arg)
setter for the Transparency attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Material * getMaterialPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getAmbientColor (PyObject *self, void *closure)
getter callback for the AmbientColor attribute
static int staticCallback_setAmbientColor (PyObject *self, PyObject *value, void *closure)
setter callback for the AmbientColor attribute
static PyObject * staticCallback_getDiffuseColor (PyObject *self, void *closure)
getter callback for the DiffuseColor attribute
static int staticCallback_setDiffuseColor (PyObject *self, PyObject *value, void *closure)
setter callback for the DiffuseColor attribute
static PyObject * staticCallback_getEmissiveColor (PyObject *self, void *closure)
getter callback for the EmissiveColor attribute
static int staticCallback_setEmissiveColor (PyObject *self, PyObject *value, void *closure)
setter callback for the EmissiveColor attribute
static PyObject * staticCallback_getSpecularColor (PyObject *self, void *closure)
getter callback for the SpecularColor attribute
static int staticCallback_setSpecularColor (PyObject *self, PyObject *value, void *closure)
setter callback for the SpecularColor attribute
static PyObject * staticCallback_getShininess (PyObject *self, void *closure)
getter callback for the Shininess attribute
static int staticCallback_setShininess (PyObject *self, PyObject *value, void *closure)
setter callback for the Shininess attribute
static PyObject * staticCallback_getTransparency (PyObject *self, void *closure)
getter callback for the Transparency attribute
static int staticCallback_setTransparency (PyObject *self, PyObject *value, void *closure)
setter callback for the Transparency attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Material.
Member Typedef Documentation
PointerType
typedef Material* App::MaterialPy::PointerType
Constructor & Destructor Documentation
~MaterialPy()
MaterialPy::~MaterialPy () protected
MaterialPy()
MaterialPy::MaterialPy (Material * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getAmbientColor()
Py::Tuple MaterialPy::getAmbientColor (void) const
getter for the AmbientColor attribute
References getMaterialPtr().
Referenced by staticCallback_getAmbientColor().
getCustomAttributes()
PyObject * MaterialPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getDiffuseColor()
Py::Tuple MaterialPy::getDiffuseColor (void) const
getter for the DiffuseColor attribute
References getMaterialPtr().
Referenced by staticCallback_getDiffuseColor().
getEmissiveColor()
Py::Tuple MaterialPy::getEmissiveColor (void) const
getter for the EmissiveColor attribute
References getMaterialPtr().
Referenced by staticCallback_getEmissiveColor().
getMaterialPtr()
Material * MaterialPy::getMaterialPtr (void) const
getter for the object handled by this class
Referenced by getAmbientColor(), getDiffuseColor(), getEmissiveColor(), getShininess(), getSpecularColor(), getTransparency(), set(), setAmbientColor(), setDiffuseColor(), setEmissiveColor(), Gui::LinkViewPy::setMaterial(), setShininess(), setSpecularColor(), and setTransparency().
getShininess()
Py::Float MaterialPy::getShininess (void) const
getter for the Shininess attribute
References getMaterialPtr().
Referenced by staticCallback_getShininess().
getSpecularColor()
Py::Tuple MaterialPy::getSpecularColor (void) const
getter for the SpecularColor attribute
References getMaterialPtr().
Referenced by staticCallback_getSpecularColor().
getTransparency()
Py::Float MaterialPy::getTransparency (void) const
getter for the Transparency attribute
References getMaterialPtr().
Referenced by staticCallback_getTransparency().
GetType()
virtual PyTypeObject* App::MaterialPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
PyInit()
int MaterialPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
References setAmbientColor(), setDiffuseColor(), setEmissiveColor(), setShininess(), setSpecularColor(), and setTransparency().
PyMake()
PyObject * MaterialPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References MaterialPy().
representation()
std::string MaterialPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
set()
PyObject * MaterialPy::set (PyObject * args)
implementer for the set() method
References getMaterialPtr(), and App::Material::set().
Referenced by draftguitools.gui_trackers.editTracker::move(), and staticCallback_set().
setAmbientColor()
void MaterialPy::setAmbientColor (Py::Tuple arg)
setter for the AmbientColor attribute
References App::Material::ambientColor, getMaterialPtr(), and App::Color::r.
Referenced by PyInit(), and staticCallback_setAmbientColor().
setCustomAttributes()
int MaterialPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setDiffuseColor()
void MaterialPy::setDiffuseColor (Py::Tuple arg)
setter for the DiffuseColor attribute
References App::Material::diffuseColor, getMaterialPtr(), and App::Color::r.
Referenced by PyInit(), and staticCallback_setDiffuseColor().
setEmissiveColor()
void MaterialPy::setEmissiveColor (Py::Tuple arg)
setter for the EmissiveColor attribute
References App::Material::emissiveColor, getMaterialPtr(), and App::Color::r.
Referenced by PyInit(), and staticCallback_setEmissiveColor().
setShininess()
void MaterialPy::setShininess (Py::Float arg)
setter for the Shininess attribute
References getMaterialPtr(), and App::Material::shininess.
Referenced by PyInit(), and staticCallback_setShininess().
setSpecularColor()
void MaterialPy::setSpecularColor (Py::Tuple arg)
setter for the SpecularColor attribute
References getMaterialPtr(), App::Color::r, and App::Material::specularColor.
Referenced by PyInit(), and staticCallback_setSpecularColor().
setTransparency()
void MaterialPy::setTransparency (Py::Float arg)
setter for the Transparency attribute
References getMaterialPtr(), and App::Material::transparency.
Referenced by PyInit(), and staticCallback_setTransparency().
staticCallback_getAmbientColor()
PyObject * MaterialPy::staticCallback_getAmbientColor (PyObject * self, void * closure) static
getter callback for the AmbientColor attribute
References Base::BaseExceptionFreeCADError, getAmbientColor(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getDiffuseColor()
PyObject * MaterialPy::staticCallback_getDiffuseColor (PyObject * self, void * closure) static
getter callback for the DiffuseColor attribute
References Base::BaseExceptionFreeCADError, getDiffuseColor(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getEmissiveColor()
PyObject * MaterialPy::staticCallback_getEmissiveColor (PyObject * self, void * closure) static
getter callback for the EmissiveColor attribute
References Base::BaseExceptionFreeCADError, getEmissiveColor(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getShininess()
PyObject * MaterialPy::staticCallback_getShininess (PyObject * self, void * closure) static
getter callback for the Shininess attribute
References Base::BaseExceptionFreeCADError, getShininess(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSpecularColor()
PyObject * MaterialPy::staticCallback_getSpecularColor (PyObject * self, void * closure) static
getter callback for the SpecularColor attribute
References Base::BaseExceptionFreeCADError, getSpecularColor(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTransparency()
PyObject * MaterialPy::staticCallback_getTransparency (PyObject * self, void * closure) static
getter callback for the Transparency attribute
References Base::BaseExceptionFreeCADError, getTransparency(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_set()
PyObject * MaterialPy::staticCallback_set (PyObject * self, PyObject * args) static
callback for the set() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), set(), and Base::PyObjectBase::startNotify().
staticCallback_setAmbientColor()
int MaterialPy::staticCallback_setAmbientColor (PyObject * self, PyObject * value, void * closure) static
setter callback for the AmbientColor attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setAmbientColor().
staticCallback_setDiffuseColor()
int MaterialPy::staticCallback_setDiffuseColor (PyObject * self, PyObject * value, void * closure) static
setter callback for the DiffuseColor attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setDiffuseColor().
staticCallback_setEmissiveColor()
int MaterialPy::staticCallback_setEmissiveColor (PyObject * self, PyObject * value, void * closure) static
setter callback for the EmissiveColor attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setEmissiveColor().
staticCallback_setShininess()
int MaterialPy::staticCallback_setShininess (PyObject * self, PyObject * value, void * closure) static
setter callback for the Shininess attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setShininess().
staticCallback_setSpecularColor()
int MaterialPy::staticCallback_setSpecularColor (PyObject * self, PyObject * value, void * closure) static
setter callback for the SpecularColor attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setSpecularColor().
staticCallback_setTransparency()
int MaterialPy::staticCallback_setTransparency (PyObject * self, PyObject * value, void * closure) static
setter callback for the Transparency attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setTransparency().
Member Data Documentation
GetterSetter
PyGetSetDef MaterialPy::GetterSetter static
Attribute structure of MaterialPy.
Methods
PyMethodDef MaterialPy::Methods static
Initial value:
= {
    {"set",
        reinterpret_cast<PyCFunction>( staticCallback_set ),
        METH_VARARGS,
        "\nSet(string) -- Set the material.\n\nThe material must be one of the following values:\nBrass, Bronze, Copper, Gold, Pewter, Plaster, Plastic, Silver, Steel, Stone, Shiny plastic,\nSatin, Metalized, Neon GNC, Chrome, Aluminium, Obsidian, Neon PHC, Jade, Ruby or Emerald.\n                      "
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of MaterialPy.
Type
PyTypeObject MaterialPy::Type static
Type structure of MaterialPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), App::PropertyMaterialList::getPyValue(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), Gui::LinkViewPy::setMaterial(), ArchReference.ArchReference::setProperties(), and App::PropertyMaterial::setPyObject().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/App/MaterialPy.h
Sources/FreeCAD/src/App/MaterialPyImp.cpp
Sources/FreeCAD-SourceDocs/src/App/MaterialPy.cpp