FreeCAD: Gui::ReportOutputParameter Class Reference
Gui::ReportOutputParameter Class Reference
Static Public Member Functions
static bool showOnError ()
static bool showOnLogMessage ()
static bool showOnMessage ()
static bool showOnWarning ()
static void toggleShowOnError ()
static void toggleShowOnLogMessage ()
static void toggleShowOnMessage ()
static void toggleShowOnWarning ()
Member Function Documentation
showOnError()
static bool Gui::ReportOutputParameter::showOnError () static
Referenced by Gui::DockWnd::ReportOutput::contextMenuEvent(), and Gui::DockWnd::ReportOutputObserver::eventFilter().
showOnLogMessage()
static bool Gui::ReportOutputParameter::showOnLogMessage () static
Referenced by Gui::DockWnd::ReportOutput::contextMenuEvent(), and Gui::DockWnd::ReportOutputObserver::eventFilter().
showOnMessage()
static bool Gui::ReportOutputParameter::showOnMessage () static
Referenced by Gui::DockWnd::ReportOutput::contextMenuEvent(), and Gui::DockWnd::ReportOutputObserver::eventFilter().
showOnWarning()
static bool Gui::ReportOutputParameter::showOnWarning () static
Referenced by Gui::DockWnd::ReportOutput::contextMenuEvent(), and Gui::DockWnd::ReportOutputObserver::eventFilter().
toggleShowOnError()
static void Gui::ReportOutputParameter::toggleShowOnError () static
Referenced by Gui::DockWnd::ReportOutput::onToggleShowReportViewOnError().
toggleShowOnLogMessage()
static void Gui::ReportOutputParameter::toggleShowOnLogMessage () static
Referenced by Gui::DockWnd::ReportOutput::onToggleShowReportViewOnLogMessage().
toggleShowOnMessage()
static void Gui::ReportOutputParameter::toggleShowOnMessage () static
Referenced by Gui::DockWnd::ReportOutput::onToggleShowReportViewOnNormalMessage().
toggleShowOnWarning()
static void Gui::ReportOutputParameter::toggleShowOnWarning () static
Referenced by Gui::DockWnd::ReportOutput::onToggleShowReportViewOnWarning().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ReportView.cpp