FreeCAD: Gui::ViewProviderExtensionPy Class Reference
Gui::ViewProviderExtensionPy Class Reference
The python export class for ViewProviderExtension.
#include <ViewProviderExtensionPy.h>
Public Types
typedef ViewProviderExtension * PointerType
Public Types inherited from App::ExtensionPy
typedef Extension * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
ViewProviderExtensionPy (ViewProviderExtension *pcObject, PyTypeObject *T=&Type)
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ViewProviderExtension * getViewProviderExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from App::ExtensionPy
ExtensionPy (Extension *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Extension * getExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::ExtensionPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of ViewProviderExtensionPy.
static PyMethodDef Methods []
Methods structure of ViewProviderExtensionPy.
static PyTypeObject Type
Type structure of ViewProviderExtensionPy.
Static Public Attributes inherited from App::ExtensionPy
static PyGetSetDef GetterSetter []
Attribute structure of ExtensionPy.
static PyMethodDef Methods []
Methods structure of ExtensionPy.
static PyTypeObject Type
Type structure of ExtensionPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~ViewProviderExtensionPy ()
Protected Member Functions inherited from App::ExtensionPy
~ExtensionPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * setIgnoreOverlayIcon (PyObject *args)
implementer for the setIgnoreOverlayIcon() method
PyObject * ignoreOverlayIcon (PyObject *args)
implementer for the ignoreOverlayIcon() method
static PyObject * staticCallback_setIgnoreOverlayIcon (PyObject *self, PyObject *args)
callback for the setIgnoreOverlayIcon() method
static PyObject * staticCallback_ignoreOverlayIcon (PyObject *self, PyObject *args)
callback for the ignoreOverlayIcon() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for ViewProviderExtension.
Member Typedef Documentation
PointerType
typedef ViewProviderExtension* Gui::ViewProviderExtensionPy::PointerType
Constructor & Destructor Documentation
~ViewProviderExtensionPy()
ViewProviderExtensionPy::~ViewProviderExtensionPy () protected
ViewProviderExtensionPy()
ViewProviderExtensionPy::ViewProviderExtensionPy (ViewProviderExtension * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
getCustomAttributes()
PyObject * ViewProviderExtensionPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
GetType()
virtual PyTypeObject* Gui::ViewProviderExtensionPy::GetType (void) virtual
Reimplemented from App::ExtensionPy.
getViewProviderExtensionPtr()
ViewProviderExtension * ViewProviderExtensionPy::getViewProviderExtensionPtr (void) const
getter for the object handled by this class
Referenced by ignoreOverlayIcon(), and setIgnoreOverlayIcon().
ignoreOverlayIcon()
PyObject * ViewProviderExtensionPy::ignoreOverlayIcon (PyObject * args)
implementer for the ignoreOverlayIcon() method
References Base::Type::fromName(), and getViewProviderExtensionPtr().
Referenced by staticCallback_ignoreOverlayIcon().
PyInit()
int ViewProviderExtensionPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from App::ExtensionPy.
PyMake()
PyObject * ViewProviderExtensionPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string ViewProviderExtensionPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int ViewProviderExtensionPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setIgnoreOverlayIcon()
PyObject * ViewProviderExtensionPy::setIgnoreOverlayIcon (PyObject * args)
implementer for the setIgnoreOverlayIcon() method
References Base::Type::fromName(), and getViewProviderExtensionPtr().
Referenced by staticCallback_setIgnoreOverlayIcon().
staticCallback_ignoreOverlayIcon()
PyObject * ViewProviderExtensionPy::staticCallback_ignoreOverlayIcon (PyObject * self, PyObject * args) static
callback for the ignoreOverlayIcon() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, ignoreOverlayIcon(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setIgnoreOverlayIcon()
PyObject * ViewProviderExtensionPy::staticCallback_setIgnoreOverlayIcon (PyObject * self, PyObject * args) static
callback for the setIgnoreOverlayIcon() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setIgnoreOverlayIcon(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef ViewProviderExtensionPy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of ViewProviderExtensionPy.
Methods
PyMethodDef ViewProviderExtensionPy::Methods static
Initial value:
= {
    {"setIgnoreOverlayIcon",
        reinterpret_cast<PyCFunction>( staticCallback_setIgnoreOverlayIcon ),
        METH_VARARGS,
        "Ignore the overlay icon of an extension"
    },
    {"ignoreOverlayIcon",
        reinterpret_cast<PyCFunction>( staticCallback_ignoreOverlayIcon ),
        METH_VARARGS,
        "Ignore the overlay icon of an extension"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of ViewProviderExtensionPy.
Type
PyTypeObject ViewProviderExtensionPy::Type static
Type structure of ViewProviderExtensionPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Gui/ViewProviderExtensionPy.h
Sources/FreeCAD/src/Gui/ViewProviderExtensionPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Gui/ViewProviderExtensionPy.cpp