FreeCAD: e57::E57XmlParser Class Reference
e57::E57XmlParser Class Reference
#include <E57XmlParser.h>
Public Member Functions
E57XmlParser (ImageFileImplSharedPtr imf)
void init ()
void parse (InputSource &inputSource)
~E57XmlParser () override
Constructor & Destructor Documentation
E57XmlParser()
E57XmlParser::E57XmlParser (ImageFileImplSharedPtr imf)
~E57XmlParser()
E57XmlParser::~E57XmlParser () override
Member Function Documentation
init()
void E57XmlParser::init ()
Turn parser exception into E57Exception
References e57::E57_ERROR_XML_PARSER_INIT.
Referenced by DocumentObject.DocumentObject::onChanged().
parse()
void E57XmlParser::parse (InputSource & inputSource)
Referenced by BOPTools.GeneralFuseResult.GeneralFuseResult::explodeCompounds(), and BOPTools.GeneralFuseResult.GeneralFuseResult::splitAggregates().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/libE57Format/src/E57XmlParser.h
FreeCAD/src/3rdParty/libE57Format/src/E57XmlParser.cpp