FreeCAD: R4 Class Reference
R4 Class Reference
#include <Rn.h>
Public Member Functions
R4 operator* (R c) const
R4 operator*= (R c)
R4 operator+ () const
R4 operator+ (R4 P) const
R4 operator+= (R4 P)
R operator, (R4 P) const
R4 operator- () const
R4 operator- (R4 P) const
R4 operator-= (R4 P)
R4 operator/ (R c) const
R4 operator/= (R c)
R & operator[] (int i)
R4 ()
R4 (R a, R b, R c, R d)
R4 (R4 A, R4 B)
Public Member Functions inherited from R3
bool DansPave (R3 &xyzMin, R3 &xyzMax)
R3 operator* (R c) const
R3 operator*= (R c)
R3 operator+ () const
R3 operator+ (R3 P) const
R3 operator+= (R3 P)
R operator, (R3 P) const
R3 operator- () const
R3 operator- (R3 P) const
R3 operator-= (R3 P)
R3 operator/ (R c) const
R3 operator/= (R c)
R3 operator= (gp_Dir P)
R3 operator= (gp_Pnt P)
R & operator[] (int i)
R3 operator^ (R3 P) const
R3 ()
R3 (gp_Dir P)
R3 (gp_Pnt P)
R3 (gp_Vec V)
R3 (R a, R b, R c)
R3 (R3 A, R3 B)
Public Attributes
R omega
Public Attributes inherited from R3
R x
R y
R z
Friends
R4 operator* (R c, R4 P)
std::ostream & operator<< (std::ostream &f, const R4 &P)
std::ostream & operator<< (std::ostream &f, const R4 *P)
std::istream & operator>> (std::istream &f, R4 &P)
std::istream & operator>> (std::istream &f, R4 *P)
Constructor & Destructor Documentation
R4() [1/3]
R4::R4 ()
Referenced by operator*(), operator+(), operator-(), and operator/().
R4() [2/3]
R4::R4 (R a, R b, R c, R d)
R4() [3/3]
R4::R4 (R4 A, R4 B)
Member Function Documentation
operator*()
R4 R4::operator* (R c) const
References omega, and R4().
operator*=()
R4 R4::operator*= (R c)
References omega.
operator+() [1/2]
R4 R4::operator+ () const
operator+() [2/2]
R4 R4::operator+ (R4 P) const
References omega, R4(), R3::x, R3::y, and R3::z.
operator+=()
R4 R4::operator+= (R4 P)
References omega, R3::x, R3::y, and R3::z.
operator,()
R R4::operator, (R4 P) const
References omega, R3::x, R3::y, and R3::z.
operator-() [1/2]
R4 R4::operator- () const
References omega, and R4().
operator-() [2/2]
R4 R4::operator- (R4 P) const
References omega, R4(), R3::x, R3::y, and R3::z.
operator-=()
R4 R4::operator-= (R4 P)
References omega, R3::x, R3::y, and R3::z.
operator/()
R4 R4::operator/ (R c) const
References omega, and R4().
operator/=()
R4 R4::operator/= (R c)
References omega.
operator[]()
R& R4::operator[] (int i)
Friends And Related Function Documentation
operator*
R4 operator* (R c, R4 P) friend
operator<< [1/2]
std::ostream& operator<< (std::ostream & f, const R4 & P) friend
operator<< [2/2]
std::ostream& operator<< (std::ostream & f, const R4 * P) friend
operator>> [1/2]
std::istream& operator>> (std::istream & f, R4 & P) friend
operator>> [2/2]
std::istream& operator>> (std::istream & f, R4 * P) friend
Member Data Documentation
omega
R R4::omega
Referenced by operator*(), operator*=(), operator+(), operator+=(), operator,(), operator-(), operator-=(), operator/(), and operator/=().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/Rn.h