FreeCAD: Base::VectorPy Class Reference
Base::VectorPy Class Reference
The python export class for Vector.
#include <VectorPy.h>
Public Types
typedef Vector3d * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
VectorPy (Vector3d *pcObject, PyTypeObject *T=&Type)
additional declarations and methods for the wrapper class
VectorPy (const Vector3d &vec, PyTypeObject *T=&Type)
VectorPy (const Vector3f &vec, PyTypeObject *T=&Type)
Vector3d value () const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * richCompare (PyObject *v, PyObject *w, int op)
callbacks and implementers for the python object number protocol
static PyObject * number_add_handler (PyObject *self, PyObject *other)
callback for the number_add_handler
static PyObject * number_subtract_handler (PyObject *self, PyObject *other)
callback for the number_subtract_handler
static PyObject * number_multiply_handler (PyObject *self, PyObject *other)
callback for the number_multiply_handler
static PyObject * number_divide_handler (PyObject *self, PyObject *other)
callback for the number_divide_handler
static PyObject * number_remainder_handler (PyObject *self, PyObject *other)
callback for the number_remainder_handler
static PyObject * number_divmod_handler (PyObject *self, PyObject *other)
callback for the number_divmod_handler
static PyObject * number_power_handler (PyObject *self, PyObject *other, PyObject *modulo)
callback for the number_power_handler
static PyObject * number_negative_handler (PyObject *self)
callback for the number_negative_handler
static PyObject * number_positive_handler (PyObject *self)
callback for the number_positive_handler
static PyObject * number_absolute_handler (PyObject *self)
callback for the number_absolute_handler
static int number_nonzero_handler (PyObject *self)
callback for the number_nonzero_handler
static PyObject * number_invert_handler (PyObject *self)
callback for the number_invert_handler
static PyObject * number_lshift_handler (PyObject *self, PyObject *other)
callback for the number_lshift_handler
static PyObject * number_rshift_handler (PyObject *self, PyObject *other)
callback for the number_rshift_handler
static PyObject * number_and_handler (PyObject *self, PyObject *other)
callback for the number_and_handler
static PyObject * number_xor_handler (PyObject *self, PyObject *other)
callback for the number_xor_handler
static PyObject * number_or_handler (PyObject *self, PyObject *other)
callback for the number_or_handler
static int number_coerce_handler (PyObject **self, PyObject **other)
callback for the number_coerce_handler
static PyObject * number_int_handler (PyObject *self)
callback for the number_int_handler
static PyObject * number_long_handler (PyObject *self)
callback for the number_long_handler
static PyObject * number_float_handler (PyObject *self)
callback for the number_float_handler
static PyObject * number_oct_handler (PyObject *self)
callback for the number_oct_handler
static PyObject * number_hex_handler (PyObject *self)
callback for the number_hex_handler
callbacks and implementers for the python object sequence protocol
static Py_ssize_t sequence_length (PyObject *)
static PyObject * sequence_item (PyObject *, Py_ssize_t)
static PyObject * mapping_subscript (PyObject *, PyObject *)
static int sequence_ass_item (PyObject *, Py_ssize_t, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of VectorPy.
static PyMappingMethods Mapping []
static PyMethodDef Methods []
Methods structure of VectorPy.
static PyNumberMethods Number []
static PySequenceMethods Sequence []
static PyTypeObject Type
Type structure of VectorPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~VectorPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
static PyObject * staticCallback___reduce__ (PyObject *self, PyObject *args)
callback for the reduce() method
static PyObject * staticCallback_add (PyObject *self, PyObject *args)
callback for the add() method
static PyObject * staticCallback_sub (PyObject *self, PyObject *args)
callback for the sub() method
static PyObject * staticCallback_negative (PyObject *self, PyObject *args)
callback for the negative() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_multiply (PyObject *self, PyObject *args)
callback for the multiply() method
static PyObject * staticCallback_dot (PyObject *self, PyObject *args)
callback for the dot() method
static PyObject * staticCallback_cross (PyObject *self, PyObject *args)
callback for the cross() method
static PyObject * staticCallback_isOnLineSegment (PyObject *self, PyObject *args)
callback for the isOnLineSegment() method
static PyObject * staticCallback_getAngle (PyObject *self, PyObject *args)
callback for the getAngle() method
static PyObject * staticCallback_normalize (PyObject *self, PyObject *args)
callback for the normalize() method
static PyObject * staticCallback_isEqual (PyObject *self, PyObject *args)
callback for the isEqual() method
static PyObject * staticCallback_projectToLine (PyObject *self, PyObject *args)
callback for the projectToLine() method
static PyObject * staticCallback_projectToPlane (PyObject *self, PyObject *args)
callback for the projectToPlane() method
static PyObject * staticCallback_distanceToPoint (PyObject *self, PyObject *args)
callback for the distanceToPoint() method
static PyObject * staticCallback_distanceToLine (PyObject *self, PyObject *args)
callback for the distanceToLine() method
static PyObject * staticCallback_distanceToLineSegment (PyObject *self, PyObject *args)
callback for the distanceToLineSegment() method
static PyObject * staticCallback_distanceToPlane (PyObject *self, PyObject *args)
callback for the distanceToPlane() method
PyObject * add (PyObject *args)
implementer for the add() method
PyObject * sub (PyObject *args)
implementer for the sub() method
PyObject * negative (PyObject *args)
implementer for the negative() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * multiply (PyObject *args)
implementer for the multiply() method
PyObject * dot (PyObject *args)
implementer for the dot() method
PyObject * cross (PyObject *args)
implementer for the cross() method
PyObject * isOnLineSegment (PyObject *args)
implementer for the isOnLineSegment() method
PyObject * getAngle (PyObject *args)
implementer for the getAngle() method
PyObject * normalize (PyObject *args)
implementer for the normalize() method
PyObject * isEqual (PyObject *args)
implementer for the isEqual() method
PyObject * projectToLine (PyObject *args)
implementer for the projectToLine() method
PyObject * projectToPlane (PyObject *args)
implementer for the projectToPlane() method
PyObject * distanceToPoint (PyObject *args)
implementer for the distanceToPoint() method
PyObject * distanceToLine (PyObject *args)
implementer for the distanceToLine() method
PyObject * distanceToLineSegment (PyObject *args)
implementer for the distanceToLineSegment() method
PyObject * distanceToPlane (PyObject *args)
implementer for the distanceToPlane() method
callbacks and implementers for the python object attributes
static PyObject * staticCallback_getLength (PyObject *self, void *closure)
getter callback for the Length attribute
static int staticCallback_setLength (PyObject *self, PyObject *value, void *closure)
setter callback for the Length attribute
static PyObject * staticCallback_getx (PyObject *self, void *closure)
getter callback for the x attribute
static int staticCallback_setx (PyObject *self, PyObject *value, void *closure)
setter callback for the x attribute
static PyObject * staticCallback_gety (PyObject *self, void *closure)
getter callback for the y attribute
static int staticCallback_sety (PyObject *self, PyObject *value, void *closure)
setter callback for the y attribute
static PyObject * staticCallback_getz (PyObject *self, void *closure)
getter callback for the z attribute
static int staticCallback_setz (PyObject *self, PyObject *value, void *closure)
setter callback for the z attribute
Py::Float getLength (void) const
getter for the Length attribute
void setLength (Py::Float arg)
setter for the Length attribute
Py::Float getx (void) const
getter for the x attribute
void setx (Py::Float arg)
setter for the x attribute
Py::Float gety (void) const
getter for the y attribute
void sety (Py::Float arg)
setter for the y attribute
Py::Float getz (void) const
getter for the z attribute
void setz (Py::Float arg)
setter for the z attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Vector3d * getVectorPtr (void) const
getter for the object handled by this class
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Vector.
Member Typedef Documentation
PointerType
typedef Vector3d* Base::VectorPy::PointerType
Constructor & Destructor Documentation
~VectorPy()
VectorPy::~VectorPy () protected
VectorPy() [1/3]
VectorPy::VectorPy (Vector3d * pcObject, PyTypeObject * T = &Type)
Referenced by add(), cross(), distanceToLineSegment(), negative(), number_absolute_handler(), number_add_handler(), number_divide_handler(), number_multiply_handler(), number_negative_handler(), number_positive_handler(), number_remainder_handler(), number_subtract_handler(), PyMake(), and sub().
VectorPy() [2/3]
Base::VectorPy::VectorPy (const Vector3d & vec, PyTypeObject * T = &Type)
VectorPy() [3/3]
Base::VectorPy::VectorPy (const Vector3f & vec, PyTypeObject * T = &Type)
Member Function Documentation
add()
PyObject * VectorPy::add (PyObject * args)
implementer for the add() method
References Type, draftgeoutils.general::vec(), and VectorPy().
Referenced by staticCallback_add().
cross()
PyObject * VectorPy::cross (PyObject * args)
implementer for the cross() method
References Type, draftgeoutils.general::vec(), and VectorPy().
Referenced by staticCallback_cross().
distanceToLine()
PyObject * VectorPy::distanceToLine (PyObject * args)
implementer for the distanceToLine() method
References DraftVecUtils::dist(), Base::Vector3< _Precision >::DistanceToLine(), and Type.
Referenced by staticCallback_distanceToLine().
distanceToLineSegment()
PyObject * VectorPy::distanceToLineSegment (PyObject * args)
implementer for the distanceToLineSegment() method
References Base::Vector3< _Precision >::DistanceToLineSegment(), Type, and VectorPy().
Referenced by staticCallback_distanceToLineSegment().
distanceToPlane()
PyObject * VectorPy::distanceToPlane (PyObject * args)
implementer for the distanceToPlane() method
References DraftVecUtils::dist(), Base::Vector3< _Precision >::DistanceToPlane(), and Type.
Referenced by staticCallback_distanceToPlane().
distanceToPoint()
PyObject * VectorPy::distanceToPoint (PyObject * args)
implementer for the distanceToPoint() method
References DraftVecUtils::dist(), Base::Distance(), and Type.
Referenced by staticCallback_distanceToPoint().
dot()
PyObject * VectorPy::dot (PyObject * args)
implementer for the dot() method
References Type, and draftgeoutils.general::vec().
Referenced by staticCallback_dot().
getAngle()
PyObject * VectorPy::getAngle (PyObject * args)
implementer for the getAngle() method
References DraftVecUtils::angle(), Base::Vector3< _Precision >::GetAngle(), Type, and draftgeoutils.general::vec().
Referenced by PathScripts.PathDressupDogbone.Chord::getAngleXY(), draftguitools.gui_trackers.arcTracker::setEndPoint(), draftguitools.gui_trackers.arcTracker::setStartPoint(), and staticCallback_getAngle().
getCustomAttributes()
PyObject * VectorPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getLength()
Py::Float VectorPy::getLength (void) const
getter for the Length attribute
References Base::Vector3< _Precision >::Length().
Referenced by staticCallback_getLength().
GetType()
virtual PyTypeObject* Base::VectorPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
getVectorPtr()
Vector3d * VectorPy::getVectorPtr (void) const
getter for the object handled by this class
Referenced by Mesh::MeshPy::insertVertex(), Base::MatrixPy::move(), PyInit(), Base::MatrixPy::scale(), sequence_ass_item(), Mesh::PropertyNormalList::setPyObject(), Points::PropertyNormalList::setPyObject(), App::PropertyVector::setPyObject(), Mesh::MeshPy::snapVertex(), Mesh::MeshPy::splitEdge(), Mesh::MeshPy::splitFacet(), and Base::MatrixPy::transform().
getx()
Py::Float VectorPy::getx (void) const
getter for the x attribute
References Base::Vector3< _Precision >::x.
Referenced by staticCallback_getx().
gety()
Py::Float VectorPy::gety (void) const
getter for the y attribute
References Base::Vector3< _Precision >::y.
Referenced by staticCallback_gety().
getz()
Py::Float VectorPy::getz (void) const
getter for the z attribute
References Base::Vector3< _Precision >::z.
Referenced by staticCallback_getz().
isEqual()
PyObject * VectorPy::isEqual (PyObject * args)
implementer for the isEqual() method
References draftutils.utils::tolerance(), Type, and draftgeoutils.general::vec().
Referenced by staticCallback_isEqual().
isOnLineSegment()
PyObject * VectorPy::isOnLineSegment (PyObject * args)
implementer for the isOnLineSegment() method
References Base::Vector3< _Precision >::IsOnLineSegment(), and Type.
Referenced by staticCallback_isOnLineSegment().
mapping_subscript()
PyObject * VectorPy::mapping_subscript (PyObject * self, PyObject * item) static
References sequence_item(), sequence_length(), Type, and value().
multiply()
PyObject * VectorPy::multiply (PyObject * args)
implementer for the multiply() method
References Base::Vector3< _Precision >::Scale().
Referenced by PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart(), and staticCallback_multiply().
negative()
PyObject * VectorPy::negative (PyObject * args)
implementer for the negative() method
References VectorPy().
Referenced by staticCallback_negative().
normalize()
PyObject * VectorPy::normalize (PyObject * args)
implementer for the normalize() method
References Base::BaseExceptionFreeCADError, Base::Vector3< double >::epsilon(), Base::Vector3< _Precision >::Length(), and Base::Vector3< _Precision >::Normalize().
Referenced by PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart(), and staticCallback_normalize().
number_absolute_handler()
PyObject * VectorPy::number_absolute_handler (PyObject * self) static
callback for the number_absolute_handler
References Type, value(), draftgeoutils.general::vec(), and VectorPy().
number_add_handler()
PyObject * VectorPy::number_add_handler (PyObject * self, PyObject * other) static
callback for the number_add_handler
References Type, value(), and VectorPy().
number_and_handler()
PyObject * VectorPy::number_and_handler (PyObject * self, PyObject * other) static
callback for the number_and_handler
number_coerce_handler()
int VectorPy::number_coerce_handler (PyObject ** self, PyObject ** other) static
callback for the number_coerce_handler
number_divide_handler()
PyObject * VectorPy::number_divide_handler (PyObject * self, PyObject * other) static
callback for the number_divide_handler
References Type, value(), draftgeoutils.general::vec(), and VectorPy().
number_divmod_handler()
PyObject * VectorPy::number_divmod_handler (PyObject * self, PyObject * other) static
callback for the number_divmod_handler
number_float_handler()
PyObject * VectorPy::number_float_handler (PyObject * self) static
callback for the number_float_handler
number_hex_handler()
PyObject * VectorPy::number_hex_handler (PyObject * self) static
callback for the number_hex_handler
number_int_handler()
PyObject * VectorPy::number_int_handler (PyObject * self) static
callback for the number_int_handler
number_invert_handler()
PyObject * VectorPy::number_invert_handler (PyObject * self) static
callback for the number_invert_handler
number_long_handler()
PyObject * VectorPy::number_long_handler (PyObject * self) static
callback for the number_long_handler
number_lshift_handler()
PyObject * VectorPy::number_lshift_handler (PyObject * self, PyObject * other) static
callback for the number_lshift_handler
number_multiply_handler()
PyObject * VectorPy::number_multiply_handler (PyObject * self, PyObject * other) static
callback for the number_multiply_handler
References Type, value(), and VectorPy().
number_negative_handler()
PyObject * VectorPy::number_negative_handler (PyObject * self) static
callback for the number_negative_handler
References Type, value(), draftgeoutils.general::vec(), and VectorPy().
number_nonzero_handler()
int VectorPy::number_nonzero_handler (PyObject * self) static
callback for the number_nonzero_handler
number_oct_handler()
PyObject * VectorPy::number_oct_handler (PyObject * self) static
callback for the number_oct_handler
number_or_handler()
PyObject * VectorPy::number_or_handler (PyObject * self, PyObject * other) static
callback for the number_or_handler
number_positive_handler()
PyObject * VectorPy::number_positive_handler (PyObject * self) static
callback for the number_positive_handler
References Type, value(), draftgeoutils.general::vec(), and VectorPy().
number_power_handler()
PyObject * VectorPy::number_power_handler (PyObject * self, PyObject * other, PyObject * modulo) static
callback for the number_power_handler
number_remainder_handler()
PyObject * VectorPy::number_remainder_handler (PyObject * self, PyObject * other) static
callback for the number_remainder_handler
References Type, value(), and VectorPy().
number_rshift_handler()
PyObject * VectorPy::number_rshift_handler (PyObject * self, PyObject * other) static
callback for the number_rshift_handler
number_subtract_handler()
PyObject * VectorPy::number_subtract_handler (PyObject * self, PyObject * other) static
callback for the number_subtract_handler
References Type, value(), and VectorPy().
number_xor_handler()
PyObject * VectorPy::number_xor_handler (PyObject * self, PyObject * other) static
callback for the number_xor_handler
projectToLine()
PyObject * VectorPy::projectToLine (PyObject * args)
implementer for the projectToLine() method
References Base::Vector3< _Precision >::ProjectToLine(), and Type.
Referenced by staticCallback_projectToLine().
projectToPlane()
PyObject * VectorPy::projectToPlane (PyObject * args)
implementer for the projectToPlane() method
References Base::Vector3< _Precision >::ProjectToPlane(), and Type.
Referenced by staticCallback_projectToPlane().
PyInit()
int VectorPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
References getVectorPtr(), Base::Vector3< _Precision >::Set(), and Type.
PyMake()
PyObject * VectorPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References VectorPy().
representation()
std::string VectorPy::representation (void) const
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
richCompare()
PyObject * VectorPy::richCompare (PyObject * v, PyObject * w, int op) static
References Type, and value().
scale()
PyObject * VectorPy::scale (PyObject * args)
implementer for the scale() method
References Base::Vector3< _Precision >::Scale().
Referenced by staticCallback_scale().
sequence_ass_item()
int VectorPy::sequence_ass_item (PyObject * self, Py_ssize_t index, PyObject * value) static
References getVectorPtr(), and Type.
sequence_item()
PyObject * VectorPy::sequence_item (PyObject * self, Py_ssize_t index) static
References Type, and value().
Referenced by mapping_subscript().
sequence_length()
Py_ssize_t VectorPy::sequence_length (PyObject *) static
Referenced by mapping_subscript().
setCustomAttributes()
int VectorPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setLength()
void VectorPy::setLength (Py::Float arg)
setter for the Length attribute
References Base::Vector3< double >::epsilon(), Base::Vector3< _Precision >::Length(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by staticCallback_setLength().
setx()
void VectorPy::setx (Py::Float arg)
setter for the x attribute
References Base::Vector3< _Precision >::x.
Referenced by staticCallback_setx().
sety()
void VectorPy::sety (Py::Float arg)
setter for the y attribute
References Base::Vector3< _Precision >::y.
Referenced by staticCallback_sety().
setz()
void VectorPy::setz (Py::Float arg)
setter for the z attribute
References Base::Vector3< _Precision >::z.
Referenced by staticCallback_setz().
staticCallback___reduce__()
PyObject * VectorPy::staticCallback___reduce__ (PyObject * self, PyObject * args) static
callback for the reduce() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, and Base::PyObjectBase::isValid().
staticCallback_add()
PyObject * VectorPy::staticCallback_add (PyObject * self, PyObject * args) static
callback for the add() method
References add(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, and Base::PyObjectBase::isValid().
staticCallback_cross()
PyObject * VectorPy::staticCallback_cross (PyObject * self, PyObject * args) static
callback for the cross() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, cross(), and Base::PyObjectBase::isValid().
staticCallback_distanceToLine()
PyObject * VectorPy::staticCallback_distanceToLine (PyObject * self, PyObject * args) static
callback for the distanceToLine() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, distanceToLine(), and Base::PyObjectBase::isValid().
staticCallback_distanceToLineSegment()
PyObject * VectorPy::staticCallback_distanceToLineSegment (PyObject * self, PyObject * args) static
callback for the distanceToLineSegment() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, distanceToLineSegment(), and Base::PyObjectBase::isValid().
staticCallback_distanceToPlane()
PyObject * VectorPy::staticCallback_distanceToPlane (PyObject * self, PyObject * args) static
callback for the distanceToPlane() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, distanceToPlane(), and Base::PyObjectBase::isValid().
staticCallback_distanceToPoint()
PyObject * VectorPy::staticCallback_distanceToPoint (PyObject * self, PyObject * args) static
callback for the distanceToPoint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, distanceToPoint(), and Base::PyObjectBase::isValid().
staticCallback_dot()
PyObject * VectorPy::staticCallback_dot (PyObject * self, PyObject * args) static
callback for the dot() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, dot(), and Base::PyObjectBase::isValid().
staticCallback_getAngle()
PyObject * VectorPy::staticCallback_getAngle (PyObject * self, PyObject * args) static
callback for the getAngle() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getAngle(), and Base::PyObjectBase::isValid().
staticCallback_getLength()
PyObject * VectorPy::staticCallback_getLength (PyObject * self, void * closure) static
getter callback for the Length attribute
References Base::BaseExceptionFreeCADError, getLength(), and Base::PyObjectBase::isValid().
staticCallback_getx()
PyObject * VectorPy::staticCallback_getx (PyObject * self, void * closure) static
getter callback for the x attribute
References Base::BaseExceptionFreeCADError, getx(), and Base::PyObjectBase::isValid().
staticCallback_gety()
PyObject * VectorPy::staticCallback_gety (PyObject * self, void * closure) static
getter callback for the y attribute
References Base::BaseExceptionFreeCADError, gety(), and Base::PyObjectBase::isValid().
staticCallback_getz()
PyObject * VectorPy::staticCallback_getz (PyObject * self, void * closure) static
getter callback for the z attribute
References Base::BaseExceptionFreeCADError, getz(), and Base::PyObjectBase::isValid().
staticCallback_isEqual()
PyObject * VectorPy::staticCallback_isEqual (PyObject * self, PyObject * args) static
callback for the isEqual() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), isEqual(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_isOnLineSegment()
PyObject * VectorPy::staticCallback_isOnLineSegment (PyObject * self, PyObject * args) static
callback for the isOnLineSegment() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isOnLineSegment(), and Base::PyObjectBase::isValid().
staticCallback_multiply()
PyObject * VectorPy::staticCallback_multiply (PyObject * self, PyObject * args) static
callback for the multiply() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), multiply(), and Base::PyObjectBase::startNotify().
staticCallback_negative()
PyObject * VectorPy::staticCallback_negative (PyObject * self, PyObject * args) static
callback for the negative() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and negative().
staticCallback_normalize()
PyObject * VectorPy::staticCallback_normalize (PyObject * self, PyObject * args) static
callback for the normalize() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), normalize(), and Base::PyObjectBase::startNotify().
staticCallback_projectToLine()
PyObject * VectorPy::staticCallback_projectToLine (PyObject * self, PyObject * args) static
callback for the projectToLine() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), projectToLine(), and Base::PyObjectBase::startNotify().
staticCallback_projectToPlane()
PyObject * VectorPy::staticCallback_projectToPlane (PyObject * self, PyObject * args) static
callback for the projectToPlane() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), projectToPlane(), and Base::PyObjectBase::startNotify().
staticCallback_scale()
PyObject * VectorPy::staticCallback_scale (PyObject * self, PyObject * args) static
callback for the scale() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), scale(), and Base::PyObjectBase::startNotify().
staticCallback_setLength()
int VectorPy::staticCallback_setLength (PyObject * self, PyObject * value, void * closure) static
setter callback for the Length attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setLength().
staticCallback_setx()
int VectorPy::staticCallback_setx (PyObject * self, PyObject * value, void * closure) static
setter callback for the x attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setx().
staticCallback_sety()
int VectorPy::staticCallback_sety (PyObject * self, PyObject * value, void * closure) static
setter callback for the y attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and sety().
staticCallback_setz()
int VectorPy::staticCallback_setz (PyObject * self, PyObject * value, void * closure) static
setter callback for the z attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setz().
staticCallback_sub()
PyObject * VectorPy::staticCallback_sub (PyObject * self, PyObject * args) static
callback for the sub() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and sub().
sub()
PyObject * VectorPy::sub (PyObject * args)
implementer for the sub() method
References Type, draftgeoutils.general::vec(), and VectorPy().
Referenced by staticCallback_sub().
value()
Vector3d Base::VectorPy::value () const
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), mapping_subscript(), Base::MatrixPy::multiply(), number_absolute_handler(), number_add_handler(), number_divide_handler(), Base::PlacementPy::number_multiply_handler(), Base::RotationPy::number_multiply_handler(), number_multiply_handler(), number_negative_handler(), number_positive_handler(), number_remainder_handler(), number_subtract_handler(), richCompare(), and sequence_item().
Member Data Documentation
GetterSetter
PyGetSetDef VectorPy::GetterSetter static
Initial value:
= {
    {"Length",
        (getter) staticCallback_getLength,
        (setter) staticCallback_setLength,
        "Length([Float]) -> Float\n                                               gets or sets the length of this vector\n                              ",
        NULL
    },
    {"x",
        (getter) staticCallback_getx,
        (setter) staticCallback_setx,
        "x([Float]) -> Float\n                                            gets or sets the X component of this vector\n                         ",
        NULL
    },
    {"y",
        (getter) staticCallback_gety,
        (setter) staticCallback_sety,
        "y([Float]) -> Float\n                                            gets or sets the Y component of this vector\n                         ",
        NULL
    },
    {"z",
        (getter) staticCallback_getz,
        (setter) staticCallback_setz,
        "z([Float]) -> Float\n                                            gets or sets the Z component of this vector\n                         ",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of VectorPy.
Mapping
PyMappingMethods VectorPy::Mapping static
Initial value:
= { {
    sequence_length,
    mapping_subscript,
    0,
} }
Methods
PyMethodDef VectorPy::Methods static
Methods structure of VectorPy.
Number
PyNumberMethods VectorPy::Number static
Sequence
PySequenceMethods VectorPy::Sequence static
Initial value:
= { {
    sequence_length,
    0,
    0,
    sequence_item,
    0,
    sequence_ass_item,
    0,
    0,
    0,
    0
} }
Type
PyTypeObject VectorPy::Type static
Type structure of VectorPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), Base::BoundBoxPy::add(), add(), Part::BRepOffsetAPI_MakeFillingPy::add(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), Sketcher::SketchObjectPy::addCopy(), Mesh::MeshPy::addFacet(), Mesh::MeshPy::addFacets(), Sketcher::SketchObjectPy::addMove(), Points::PointsPy::addPoints(), Sketcher::SketchObjectPy::addRectangularArray(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), Base::BoundBoxPy::closestPoint(), Part::ParabolaPy::compute(), cross(), Mesh::MeshPy::crossSections(), distanceToLine(), distanceToLineSegment(), distanceToPlane(), distanceToPoint(), dot(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), Part::TopoShapePy::extrude(), Sketcher::SketchObjectPy::fillet(), getAngle(), Base::BoundBoxPy::getIntersectionPoint(), Part::TopoShapeSolidPy::getMomentOfInertia(), Gui::View3DInventorPy::getPointOnScreen(), Part::TopoShapeSolidPy::getRadiusOfGyration(), Part::MakePrismPy::init(), Part::BezierCurvePy::insertPoleAfter(), Part::BezierCurvePy::insertPoleBefore(), Mesh::MeshPy::insertVertex(), Part::BSplineCurvePy::interpolate(), Base::BoundBoxPy::intersect(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), Base::BoundBoxPy::isCutPlane(), isEqual(), Base::BoundBoxPy::isInside(), Part::TopoShapePy::isInside(), isOnLineSegment(), TechDraw::DrawViewPartPy::makeCosmeticCircle(), TechDraw::DrawViewPartPy::makeCosmeticCircleArc(), TechDraw::DrawViewPartPy::makeCosmeticLine(), TechDraw::DrawViewPartPy::makeCosmeticLine3D(), TechDraw::DrawViewPartPy::makeCosmeticVertex(), TechDraw::DrawViewPartPy::makeCosmeticVertex3d(), Part::TopoShapeFacePy::makeHalfSpace(), Part::TopoShapeShellPy::makeHalfSpace(), Part::TopoShapePy::makeParallelProjection(), Part::TopoShapePy::makePerspectiveProjection(), mapping_subscript(), Part::GeometryPy::mirror(), Part::TopoShapePy::mirror(), Sketcher::ExternalGeometryFacadePy::mirror(), Sketcher::GeometryFacadePy::mirror(), Base::AxisPy::move(), Base::BoundBoxPy::move(), Base::MatrixPy::move(), Base::PlacementPy::move(), Mesh::MeshPointPy::move(), Part::BSplineCurvePy::movePoint(), Part::BSplineSurfacePy::movePoint(), Sketcher::SketchObjectPy::movePoint(), Sketcher::SketchPy::movePoint(), Base::MatrixPy::multiply(), Base::MatrixPy::multVec(), Base::PlacementPy::multVec(), Base::RotationPy::multVec(), number_absolute_handler(), number_add_handler(), number_divide_handler(), Base::MatrixPy::number_multiply_handler(), Base::PlacementPy::number_multiply_handler(), Base::RotationPy::number_multiply_handler(), number_multiply_handler(), number_negative_handler(), number_positive_handler(), number_remainder_handler(), number_subtract_handler(), Part::GeometryCurvePy::parameter(), Part::GeometrySurfacePy::parameter(), Part::GeometrySurfacePy::projectPoint(), projectToLine(), projectToPlane(), Base::AxisPy::PyInit(), Base::BoundBoxPy::PyInit(), Base::PlacementPy::PyInit(), Base::RotationPy::PyInit(), PyInit(), Part::ArcOfCirclePy::PyInit(), Part::ArcPy::PyInit(), Part::MakePrismPy::PyInit(), Part::CirclePy::PyInit(), Part::ConePy::PyInit(), Part::CylinderPy::PyInit(), Part::EllipsePy::PyInit(), Part::PointConstraintPy::PyInit(), Part::HyperbolaPy::PyInit(), Part::LinePy::PyInit(), Part::LineSegmentPy::PyInit(), Part::OffsetCurvePy::PyInit(), Part::ParabolaPy::PyInit(), Part::PlanePy::PyInit(), Part::PointPy::PyInit(), Part::SurfaceOfExtrusionPy::PyInit(), Part::SurfaceOfRevolutionPy::PyInit(), Part::TopoShapeVertexPy::PyInit(), Part::TopoShapePy::reflectLines(), Part::TopoShapePy::revolve(), richCompare(), Base::BoundBoxPy::scale(), Base::MatrixPy::scale(), Part::GeometryPy::scale(), Part::TopoShapePy::scale(), Sketcher::ExternalGeometryFacadePy::scale(), Sketcher::GeometryFacadePy::scale(), sequence_ass_item(), sequence_item(), draftobjects.layer.Layer::set_properties(), Base::CoordinateSystemPy::setAxes(), Part::ArcOfConicPy::setAxis(), Part::ConePy::setAxis(), Part::ConicPy::setAxis(), Part::CylinderPy::setAxis(), Part::PlanePy::setAxis(), Part::SpherePy::setAxis(), Part::ToroidPy::setAxis(), Part::BRepOffsetAPI_MakePipeShellPy::setBiNormalMode(), Part::ArcOfConicPy::setCenter(), Part::ConePy::setCenter(), Part::ConicPy::setCenter(), Part::CylinderPy::setCenter(), Part::SpherePy::setCenter(), Part::ToroidPy::setCenter(), TechDraw::CosmeticEdgePy::setCenter(), Base::RotationPy::setCustomAttributes(), Part::LinePy::setDirection(), Part::SurfaceOfExtrusionPy::setDirection(), Part::SurfaceOfRevolutionPy::setDirection(), TechDraw::CosmeticEdgePy::setEnd(), Part::LineSegmentPy::setEndPoint(), Part::ArcOfConicPy::setLocation(), Part::ConicPy::setLocation(), Part::LinePy::setLocation(), Part::SurfaceOfRevolutionPy::setLocation(), FemGui::ViewProviderFemMeshPy::setNodeDisplacement(), Part::OffsetCurvePy::setOffsetDirection(), TechDraw::CosmeticVertexPy::setPoint(), Mesh::MeshPy::setPoint(), Part::BezierCurvePy::setPole(), Part::BezierSurfacePy::setPole(), Part::BSplineCurvePy::setPole(), Part::BSplineSurfacePy::setPole(), Part::PlanePy::setPosition(), ArchReference.ArchReference::setProperties(), Mesh::PropertyNormalList::setPyObject(), Points::PropertyNormalList::setPyObject(), App::PropertyVector::setPyObject(), TechDraw::CosmeticEdgePy::setStart(), Part::LineSegmentPy::setStartPoint(), Part::BRepOffsetAPI_MakePipeShellPy::setTrihedronMode(), Part::ArcOfConicPy::setXAxis(), Part::ConicPy::setXAxis(), Part::ArcOfConicPy::setYAxis(), Part::ConicPy::setYAxis(), Part::TopoShapePy::slice(), Part::TopoShapePy::slices(), Mesh::MeshPy::snapVertex(), Mesh::MeshPy::splitEdge(), Mesh::MeshPy::splitFacet(), sub(), Base::MatrixPy::transform(), Base::CoordinateSystemPy::transformTo(), Part::GeometryPy::translate(), Part::TopoShapePy::translate(), Sketcher::ExternalGeometryFacadePy::translate(), Sketcher::GeometryFacadePy::translate(), and Sketcher::SketchObjectPy::trim().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Base/VectorPy.h
Sources/FreeCAD/src/Base/VectorPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Base/VectorPy.cpp