FreeCAD: MeshPart::CurveProjectorShape Class Reference
MeshPart::CurveProjectorShape Class Reference
Project by intersection face planes with the curve.
#include <CurveProjector.h>
Public Member Functions
CurveProjectorShape (const TopoDS_Shape &aShape, const MeshKernel &pMesh)
bool findStartPoint (const MeshKernel &MeshK, const Base::Vector3f &Pnt, Base::Vector3f &Rslt, MeshCore::FacetIndex &FaceIndex)
void projectCurve (const TopoDS_Edge &aEdge, std::vector< FaceSplitEdge > &vSplitEdges)
virtual ~CurveProjectorShape ()
Public Member Functions inherited from MeshPart::CurveProjector
CurveProjector (const TopoDS_Shape &aShape, const MeshKernel &pMesh)
result_type & result (void)
void writeIntersectionPointsToFile (const char *name="export_pts.asc")
virtual ~CurveProjector ()
Protected Member Functions
virtual void Do ()
virtual void Do ()=0
Additional Inherited Members
Public Types inherited from MeshPart::CurveProjector
typedef std::map< TopoDS_Edge, std::vector< FaceSplitEdge >, TopoDSLess< TopoDS_Edge > > result_type
Protected Attributes inherited from MeshPart::CurveProjector
result_type mvEdgeSplitPoints
Detailed Description
Project by intersection face planes with the curve.
Constructor & Destructor Documentation
CurveProjectorShape()
CurveProjectorShape::CurveProjectorShape (const TopoDS_Shape & aShape, const MeshKernel & pMesh)
References Do().
~CurveProjectorShape()
virtual MeshPart::CurveProjectorShape::~CurveProjectorShape () virtual
Member Function Documentation
Do()
void CurveProjectorShape::Do (void) protected virtual
Implements MeshPart::CurveProjector.
References MeshPart::CurveProjector::mvEdgeSplitPoints, and projectCurve().
Referenced by CurveProjectorShape().
findStartPoint()
bool CurveProjectorShape::findStartPoint (const MeshKernel & MeshK, const Base::Vector3f & Pnt, Base::Vector3f & Rslt, MeshCore::FacetIndex & FaceIndex)
References MeshCore::MeshGeomFacet::Foraminate(), MeshCore::MeshGeomFacet::GetNormal(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), and MeshCore::MeshFacetIterator::Position().
Referenced by projectCurve().
projectCurve()
void CurveProjectorShape::projectCurve (const TopoDS_Edge & aEdge, std::vector< FaceSplitEdge > & vSplitEdges)
References Base::Console(), MeshCore::FACET_INDEX_MAX, findStartPoint(), MeshCore::MeshGeomFacet::GetNormal(), Base::ConsoleSingleton::Log(), MeshPart::CurveProjector::FaceSplitEdge::p1, MeshPart::CurveProjector::FaceSplitEdge::p2, MeshPart::CurveProjector::FaceSplitEdge::ulFaceIndex, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by Do().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/MeshPart/App/CurveProjector.h
FreeCAD/src/Mod/MeshPart/App/CurveProjector.cpp