FreeCAD: MeshCore::MeshEvalDuplicatePoints Class Reference
MeshCore::MeshEvalDuplicatePoints Class Reference
The MeshEvalDuplicatePoints class searches for duplicated points.
#include <Degeneration.h>
Public Member Functions
bool Evaluate ()
Merges points to one if the distance between them is less than the global MeshDefinitions::_fMinPointDistanceD1.
std::vector< unsigned long > GetIndices () const
Returns the indices of all duplicated points.
MeshEvalDuplicatePoints (const MeshKernel &rclM)
Construction.
~MeshEvalDuplicatePoints ()
Destruction.
Public Member Functions inherited from MeshCore::MeshEvaluation
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()
Detailed Description
The MeshEvalDuplicatePoints class searches for duplicated points.
A point is regarded as duplicated if the distances between x, y and z coordinates of two points is less than an epsilon (defined by MeshDefinitions::_fMinPointDistanceD1, default value=1.0e-5f).
See also
MeshFixDuplicatePoints
MeshEvalDegeneratedFacets
Author
Werner Mayer
Constructor & Destructor Documentation
MeshEvalDuplicatePoints()
MeshCore::MeshEvalDuplicatePoints::MeshEvalDuplicatePoints (const MeshKernel & rclM)
Construction.
~MeshEvalDuplicatePoints()
MeshCore::MeshEvalDuplicatePoints::~MeshEvalDuplicatePoints ()
Destruction.
Member Function Documentation
Evaluate()
bool MeshEvalDuplicatePoints::Evaluate () virtual
Merges points to one if the distance between them is less than the global MeshDefinitions::_fMinPointDistanceD1.
Implements MeshCore::MeshEvaluation.
Referenced by MeshGui::DlgEvaluateMeshImp::on_analyzeDuplicatedPointsButton_clicked(), and MeshGui::DlgEvaluateMeshImp::on_repairAllTogether_clicked().
GetIndices()
std::vector< unsigned long > MeshEvalDuplicatePoints::GetIndices () const
Returns the indices of all duplicated points.
Referenced by MeshGui::DlgEvaluateMeshImp::on_analyzeDuplicatedPointsButton_clicked().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Degeneration.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Degeneration.cpp