FreeCAD: zipios::EndOfCentralDirectory Class Reference
zipios::EndOfCentralDirectory Class Reference
The end of the Central directory structure.
#include <ziphead.h>
Public Member Functions
EndOfCentralDirectory (const string &_zip_comment="", uint16 _disk_num=0, uint16 _cdir_disk_num=0, uint16 _cdir_entries=0, uint16 _cdir_tot_entries=0, uint32 _cdir_size=0, uint32 _cdir_offset=0)
int eocdOffSetFromEnd () const
uint32 offset () const
bool read (vector< unsigned char > &buf, int pos)
void setCDirSize (uint32 size)
void setOffset (uint32 offset)
void setTotalCount (uint16 c)
uint16 totalCount () const
Friends
ostream & operator<< (ostream &os, const EndOfCentralDirectory &eocd)
Detailed Description
The end of the Central directory structure.
This structure is stored in the end of the zipfile, and contains information about the zipfile, including the position of the start of the central directory.
Constructor & Destructor Documentation
EndOfCentralDirectory()
zipios::EndOfCentralDirectory::EndOfCentralDirectory (const string & _zip_comment = "", uint16 _disk_num = 0, uint16 _cdir_disk_num = 0, uint16 _cdir_entries = 0, uint16 _cdir_tot_entries = 0, uint32 _cdir_size = 0, uint32 _cdir_offset = 0) explicit
Member Function Documentation
eocdOffSetFromEnd()
int zipios::EndOfCentralDirectory::eocdOffSetFromEnd () const
offset()
uint32 zipios::EndOfCentralDirectory::offset () const
Referenced by gzip_utf8.GzipFile::read(), gzip_utf8.GzipFile::readline(), gzip_utf8.GzipFile::rewind(), gzip_utf8.GzipFile::seek(), setOffset(), DraftGui.DraftToolBar::taskUi(), and gzip_utf8.GzipFile::write().
read()
bool zipios::EndOfCentralDirectory::read (vector< unsigned char > & buf, int pos)
References zipios::ztohl(), and zipios::ztohs().
Referenced by gzip_utf8.GzipFile::readline(), and gzip_utf8.GzipFile::seek().
setCDirSize()
void zipios::EndOfCentralDirectory::setCDirSize (uint32 size)
Referenced by zipios::ZipOutputStreambuf::writeCentralDirectory().
setOffset()
void zipios::EndOfCentralDirectory::setOffset (uint32 offset)
References offset().
Referenced by zipios::ZipOutputStreambuf::writeCentralDirectory().
setTotalCount()
void zipios::EndOfCentralDirectory::setTotalCount (uint16 c)
Referenced by zipios::ZipOutputStreambuf::writeCentralDirectory().
totalCount()
uint16 zipios::EndOfCentralDirectory::totalCount () const
Friends And Related Function Documentation
operator<<
ostream& operator<< (ostream & os, const EndOfCentralDirectory & eocd) friend
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/zipios++/ziphead.h
Sources/FreeCAD/src/zipios++/ziphead.cpp