FreeCAD: TechDrawGui::TaskDlgLeaderLine Class Reference
TechDrawGui::TaskDlgLeaderLine Class Reference
#include <TaskLeaderLine.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void clicked (int)
is called by the framework if an button is clicked which has no accept or reject role
virtual void helpRequested ()
is called by the framework if the user presses the help button
virtual bool isAllowedAlterDocument (void) const
void modifyStandardButtons (QDialogButtonBox *box)
virtual void open ()
is called the TaskView when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgLeaderLine (TechDraw::DrawView *baseFeat, TechDraw::DrawPage *page)
TaskDlgLeaderLine (TechDrawGui::ViewProviderLeader *leadVP)
void update ()
~TaskDlgLeaderLine ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
ButtonPosition buttonPosition () const
bool canClose () const
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
tells the framework which buttons are wished for the dialog
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isEscapeButtonEnabled () const
virtual bool needsFullSpace () const
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Constructor & Destructor Documentation
TaskDlgLeaderLine() [1/2]
TaskDlgLeaderLine::TaskDlgLeaderLine (TechDraw::DrawView * baseFeat, TechDraw::DrawPage * page)
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
TaskDlgLeaderLine() [2/2]
TaskDlgLeaderLine::TaskDlgLeaderLine (TechDrawGui::ViewProviderLeader * leadVP)
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
~TaskDlgLeaderLine()
TaskDlgLeaderLine::~TaskDlgLeaderLine ()
Member Function Documentation
accept()
bool TaskDlgLeaderLine::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References TechDrawGui::TaskLeaderLine::accept().
clicked()
void TaskDlgLeaderLine::clicked (int) virtual
is called by the framework if an button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
helpRequested()
virtual void TechDrawGui::TaskDlgLeaderLine::helpRequested () virtual
is called by the framework if the user presses the help button
Reimplemented from Gui::TaskView::TaskDialog.
isAllowedAlterDocument()
virtual bool TechDrawGui::TaskDlgLeaderLine::isAllowedAlterDocument (void) const virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
modifyStandardButtons()
void TaskDlgLeaderLine::modifyStandardButtons (QDialogButtonBox * box) virtual
Reimplemented from Gui::TaskView::TaskDialog.
References TechDrawGui::TaskLeaderLine::saveButtons().
open()
void TaskDlgLeaderLine::open () virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
reject()
bool TaskDlgLeaderLine::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References TechDrawGui::TaskLeaderLine::reject().
update()
void TaskDlgLeaderLine::update ()
Referenced by ArchAxis.CommandArchGrid::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/TaskLeaderLine.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/TaskLeaderLine.cpp