FreeCAD: App::LinkBaseExtensionPy Class Reference
App::LinkBaseExtensionPy Class Reference
The python export class for LinkBaseExtension.
#include <LinkBaseExtensionPy.h>
Public Types
typedef LinkBaseExtension * PointerType
Public Types inherited from App::DocumentObjectExtensionPy
typedef DocumentObjectExtension * PointerType
Public Types inherited from App::ExtensionPy
typedef Extension * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
LinkBaseExtensionPy (LinkBaseExtension *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from App::DocumentObjectExtensionPy
DocumentObjectExtensionPy (DocumentObjectExtension *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
DocumentObjectExtension * getDocumentObjectExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from App::ExtensionPy
ExtensionPy (Extension *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Extension * getExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::DocumentObjectExtensionPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::ExtensionPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of LinkBaseExtensionPy.
static PyMethodDef Methods []
Methods structure of LinkBaseExtensionPy.
static PyTypeObject Type
Type structure of LinkBaseExtensionPy.
Static Public Attributes inherited from App::DocumentObjectExtensionPy
static PyGetSetDef GetterSetter []
Attribute structure of DocumentObjectExtensionPy.
static PyMethodDef Methods []
Methods structure of DocumentObjectExtensionPy.
static PyTypeObject Type
Type structure of DocumentObjectExtensionPy.
Static Public Attributes inherited from App::ExtensionPy
static PyGetSetDef GetterSetter []
Attribute structure of ExtensionPy.
static PyMethodDef Methods []
Methods structure of ExtensionPy.
static PyTypeObject Type
Type structure of ExtensionPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~LinkBaseExtensionPy ()
Protected Member Functions inherited from App::DocumentObjectExtensionPy
~DocumentObjectExtensionPy ()
Protected Member Functions inherited from App::ExtensionPy
~ExtensionPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * configLinkProperty (PyObject *args, PyObject *kwd)
implementer for the configLinkProperty() method
PyObject * getLinkExtProperty (PyObject *args)
implementer for the getLinkExtProperty() method
PyObject * getLinkExtPropertyName (PyObject *args)
implementer for the getLinkExtPropertyName() method
PyObject * getLinkPropertyInfo (PyObject *args)
implementer for the getLinkPropertyInfo() method
PyObject * setLink (PyObject *args)
implementer for the setLink() method
PyObject * cacheChildLabel (PyObject *args)
implementer for the cacheChildLabel() method
PyObject * flattenSubname (PyObject *args)
implementer for the flattenSubname() method
PyObject * expandSubname (PyObject *args)
implementer for the expandSubname() method
static PyObject * staticCallback_configLinkProperty (PyObject *self, PyObject *args, PyObject *kwd)
callback for the configLinkProperty() method
static PyObject * staticCallback_getLinkExtProperty (PyObject *self, PyObject *args)
callback for the getLinkExtProperty() method
static PyObject * staticCallback_getLinkExtPropertyName (PyObject *self, PyObject *args)
callback for the getLinkExtPropertyName() method
static PyObject * staticCallback_getLinkPropertyInfo (PyObject *self, PyObject *args)
callback for the getLinkPropertyInfo() method
static PyObject * staticCallback_setLink (PyObject *self, PyObject *args)
callback for the setLink() method
static PyObject * staticCallback_cacheChildLabel (PyObject *self, PyObject *args)
callback for the cacheChildLabel() method
static PyObject * staticCallback_flattenSubname (PyObject *self, PyObject *args)
callback for the flattenSubname() method
static PyObject * staticCallback_expandSubname (PyObject *self, PyObject *args)
callback for the expandSubname() method
callbacks and implementers for the python object attributes
Py::List getLinkedChildren (void) const
getter for the LinkedChildren attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
LinkBaseExtension * getLinkBaseExtensionPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getLinkedChildren (PyObject *self, void *closure)
getter callback for the LinkedChildren attribute
static int staticCallback_setLinkedChildren (PyObject *self, PyObject *value, void *closure)
setter callback for the LinkedChildren attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for LinkBaseExtension.
Member Typedef Documentation
PointerType
typedef LinkBaseExtension* App::LinkBaseExtensionPy::PointerType
Constructor & Destructor Documentation
~LinkBaseExtensionPy()
LinkBaseExtensionPy::~LinkBaseExtensionPy () protected
LinkBaseExtensionPy()
LinkBaseExtensionPy::LinkBaseExtensionPy (LinkBaseExtension * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
cacheChildLabel()
PyObject * LinkBaseExtensionPy::cacheChildLabel (PyObject * args)
implementer for the cacheChildLabel() method
References App::LinkBaseExtension::cacheChildLabel(), and getLinkBaseExtensionPtr().
Referenced by staticCallback_cacheChildLabel().
configLinkProperty()
PyObject * LinkBaseExtensionPy::configLinkProperty (PyObject * args, PyObject * kwd)
implementer for the configLinkProperty() method
References getLinkBaseExtensionPtr().
Referenced by staticCallback_configLinkProperty().
expandSubname()
PyObject * LinkBaseExtensionPy::expandSubname (PyObject * args)
implementer for the expandSubname() method
References App::LinkBaseExtension::expandSubname(), and getLinkBaseExtensionPtr().
Referenced by staticCallback_expandSubname().
flattenSubname()
PyObject * LinkBaseExtensionPy::flattenSubname (PyObject * args)
implementer for the flattenSubname() method
References getLinkBaseExtensionPtr().
Referenced by staticCallback_flattenSubname().
getCustomAttributes()
PyObject * LinkBaseExtensionPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getLinkBaseExtensionPtr()
LinkBaseExtension * LinkBaseExtensionPy::getLinkBaseExtensionPtr (void) const
getter for the object handled by this class
Referenced by cacheChildLabel(), configLinkProperty(), expandSubname(), flattenSubname(), getLinkedChildren(), getLinkExtProperty(), getLinkExtPropertyName(), getLinkPropertyInfo(), representation(), and setLink().
getLinkedChildren()
Py::List LinkBaseExtensionPy::getLinkedChildren (void) const
getter for the LinkedChildren attribute
References getLinkBaseExtensionPtr().
Referenced by staticCallback_getLinkedChildren().
getLinkExtProperty()
PyObject * LinkBaseExtensionPy::getLinkExtProperty (PyObject * args)
implementer for the getLinkExtProperty() method
References getLinkBaseExtensionPtr(), App::LinkBaseExtension::getProperty(), and Base::BaseClass::getPyObject().
Referenced by staticCallback_getLinkExtProperty().
getLinkExtPropertyName()
PyObject * LinkBaseExtensionPy::getLinkExtPropertyName (PyObject * args)
implementer for the getLinkExtPropertyName() method
References App::Extension::getExtendedContainer(), getLinkBaseExtensionPtr(), and App::LinkBaseExtension::getProperty().
Referenced by staticCallback_getLinkExtPropertyName().
getLinkPropertyInfo()
PyObject * LinkBaseExtensionPy::getLinkPropertyInfo (PyObject * args)
implementer for the getLinkPropertyInfo() method
References getLinkBaseExtensionPtr().
Referenced by staticCallback_getLinkPropertyInfo().
GetType()
virtual PyTypeObject* App::LinkBaseExtensionPy::GetType (void) virtual
Reimplemented from App::DocumentObjectExtensionPy.
PyInit()
int LinkBaseExtensionPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from App::DocumentObjectExtensionPy.
PyMake()
PyObject * LinkBaseExtensionPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string LinkBaseExtensionPy::representation (void) const
References getLinkBaseExtensionPtr().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int LinkBaseExtensionPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setLink()
PyObject * LinkBaseExtensionPy::setLink (PyObject * args)
implementer for the setLink() method
References getLinkBaseExtensionPtr().
Referenced by staticCallback_setLink().
staticCallback_cacheChildLabel()
PyObject * LinkBaseExtensionPy::staticCallback_cacheChildLabel (PyObject * self, PyObject * args) static
callback for the cacheChildLabel() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, cacheChildLabel(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_configLinkProperty()
PyObject * LinkBaseExtensionPy::staticCallback_configLinkProperty (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the configLinkProperty() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, configLinkProperty(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_expandSubname()
PyObject * LinkBaseExtensionPy::staticCallback_expandSubname (PyObject * self, PyObject * args) static
callback for the expandSubname() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, expandSubname(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_flattenSubname()
PyObject * LinkBaseExtensionPy::staticCallback_flattenSubname (PyObject * self, PyObject * args) static
callback for the flattenSubname() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, flattenSubname(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getLinkedChildren()
PyObject * LinkBaseExtensionPy::staticCallback_getLinkedChildren (PyObject * self, void * closure) static
getter callback for the LinkedChildren attribute
References Base::BaseExceptionFreeCADError, getLinkedChildren(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getLinkExtProperty()
PyObject * LinkBaseExtensionPy::staticCallback_getLinkExtProperty (PyObject * self, PyObject * args) static
callback for the getLinkExtProperty() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getLinkExtProperty(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getLinkExtPropertyName()
PyObject * LinkBaseExtensionPy::staticCallback_getLinkExtPropertyName (PyObject * self, PyObject * args) static
callback for the getLinkExtPropertyName() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getLinkExtPropertyName(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getLinkPropertyInfo()
PyObject * LinkBaseExtensionPy::staticCallback_getLinkPropertyInfo (PyObject * self, PyObject * args) static
callback for the getLinkPropertyInfo() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getLinkPropertyInfo(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_setLink()
PyObject * LinkBaseExtensionPy::staticCallback_setLink (PyObject * self, PyObject * args) static
callback for the setLink() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setLink(), and Base::PyObjectBase::startNotify().
staticCallback_setLinkedChildren()
int LinkBaseExtensionPy::staticCallback_setLinkedChildren (PyObject * self, PyObject * value, void * closure) static
setter callback for the LinkedChildren attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
Member Data Documentation
GetterSetter
PyGetSetDef LinkBaseExtensionPy::GetterSetter static
Initial value:
= {
    {"LinkedChildren",
        (getter) staticCallback_getLinkedChildren,
        (setter) staticCallback_setLinkedChildren,
        "Return a flattened (in case grouped by plain group) list of linked children",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of LinkBaseExtensionPy.
Methods
PyMethodDef LinkBaseExtensionPy::Methods static
Methods structure of LinkBaseExtensionPy.
Type
PyTypeObject LinkBaseExtensionPy::Type static
Type structure of LinkBaseExtensionPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/App/LinkBaseExtensionPy.h
Sources/FreeCAD/src/App/LinkBaseExtensionPyImp.cpp
Sources/FreeCAD-SourceDocs/src/App/LinkBaseExtensionPy.cpp