FreeCAD: MeshCore::MeshTrimByPlane Class Reference
MeshCore::MeshTrimByPlane Class Reference
Trim the the facets in 3D with a plane.
#include <TrimByPlane.h>
Public Member Functions
void CheckFacets (const MeshFacetGrid &rclGrid, const Base::Vector3f &base, const Base::Vector3f &normal, std::vector< unsigned long > &trimFacets, std::vector< unsigned long > &removeFacets) const
Checks all facets for intersection with the plane and writes all touched facets into the vector.
MeshTrimByPlane (MeshKernel &mesh)
void TrimFacets (const std::vector< unsigned long > &trimFacets, const Base::Vector3f &base, const Base::Vector3f &normal, std::vector< MeshGeomFacet > &trimmedFacets)
The facets from trimFacets will be trimmed or deleted and trimmedFacets holds the newly generated facets.
~MeshTrimByPlane ()
Detailed Description
Trim the the facets in 3D with a plane.
Author
Werner Mayer
Constructor & Destructor Documentation
MeshTrimByPlane()
MeshTrimByPlane::MeshTrimByPlane (MeshKernel & mesh)
~MeshTrimByPlane()
MeshTrimByPlane::~MeshTrimByPlane ()
Member Function Documentation
CheckFacets()
void MeshTrimByPlane::CheckFacets (const MeshFacetGrid & rclGrid, const Base::Vector3f & base, const Base::Vector3f & normal, std::vector< unsigned long > & trimFacets, std::vector< unsigned long > & removeFacets) const
Checks all facets for intersection with the plane and writes all touched facets into the vector.
References Base::BoundBox3< _Precision >::CalcPoint(), MeshCore::MeshGridIterator::GetBoundBox(), MeshCore::MeshGridIterator::GetElements(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshGridIterator::Init(), MeshCore::MeshGeomFacet::IntersectWithPlane(), Base::BoundBox3< _Precision >::IsCutPlane(), MeshCore::MeshGridIterator::More(), and MeshCore::MeshGridIterator::Next().
TrimFacets()
void MeshTrimByPlane::TrimFacets (const std::vector< unsigned long > & trimFacets, const Base::Vector3f & base, const Base::Vector3f & normal, std::vector< MeshGeomFacet > & trimmedFacets)
The facets from trimFacets will be trimmed or deleted and trimmedFacets holds the newly generated facets.
References MeshCore::MeshKernel::GetFacet().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/TrimByPlane.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/TrimByPlane.cpp