FreeCAD: ArchStructure Namespace Reference
ArchStructure Namespace Reference
The Structure object and tools.
Classes
class StructSelectionObserver
class StructureTaskPanel
Functions
def makeStructuralSystem (objects=[], axes=[], name="StructuralSystem")
def makeStructure (baseobj=None, length=None, width=None, height=None, name="Structure")
def placeAlongEdge (p1, p2, horizontal=False)
Variables
list Categories = []
Presets = ArchProfile.readPresets()
Detailed Description
The Structure object and tools.
This module provides tools to build Structure objects. Structure elements are beams, columns, slabs, and other elements that have a structural function, that is, that support other parts of the building.
Function Documentation
makeStructuralSystem()
def ArchStructure.makeStructuralSystem (objects = [], axes = [], name = "StructuralSystem")
makeStructuralSystem(objects,axes): makes a structural system
based on the given objects and axes
makeStructure()
def ArchStructure.makeStructure (baseobj = None, length = None, width = None, height = None, name = "Structure")
makeStructure([obj],[length],[width],[height],[swap]): creates a
structure element based on the given profile object and the given
extrusion height. If no base object is given, you can also specify
length and width for a cubic object.
Referenced by ArchCommands.removeShape().
placeAlongEdge()
def ArchStructure.placeAlongEdge (p1, p2, horizontal = False)
placeAlongEdge(p1,p2,[horizontal]): returns a Placement positioned at p1, with Z axis oriented towards p2.
If horizontal is True, then the X axis is oriented towards p2, not the Z axis
References ArchCommands.getDefaultColor(), ArchComponent.Component.getExtrusionData(), draftguitools.gui_tool_utils.getPoint, ArchCommands.getShapeFromMesh(), ArchCommands.getStringList(), ArchComponent.Component.onChanged(), ArchComponent.ViewProviderComponent.onChanged(), ArchComponent.Component.onDocumentRestored(), draftutils.translate.QT_TRANSLATE_NOOP, ArchComponent.ViewProviderComponent.setProperties(), DraftVecUtils.toString(), and ArchComponent.ViewProviderComponent.updateData().
Variable Documentation
Categories
list ArchStructure.Categories = []
Presets
ArchStructure.Presets = ArchProfile.readPresets()