FreeCAD: SketcherGui::DrawSketchHandlerArcOfParabola Class Reference
SketcherGui::DrawSketchHandlerArcOfParabola Class Reference
#include <DrawSketchHandlerArcOfParabola.h>
Public Types
enum SelectMode {
STATUS_SEEK_First , STATUS_SEEK_Second , STATUS_SEEK_Third , STATUS_SEEK_Fourth ,
STATUS_Close
}
mode table
Public Member Functions
DrawSketchHandlerArcOfParabola ()
virtual void mouseMove (Base::Vector2d onSketchPos) override
virtual bool pressButton (Base::Vector2d onSketchPos) override
virtual bool releaseButton (Base::Vector2d) override
virtual ~DrawSketchHandlerArcOfParabola ()=default
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void activate (ViewProviderSketch *)
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::PointPos::none, bool createowncommand=true)
void deactivate ()
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual void mouseMove (Base::Vector2d onSketchPos)=0
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual bool pressButton (Base::Vector2d onSketchPos)=0
virtual void quit (void)
virtual void registerPressedKey (bool, int)
virtual bool releaseButton (Base::Vector2d onSketchPos)=0
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Attributes
double arcAngle
double arcAngle_t
Base::Vector2d axisPoint
std::vector< Base::Vector2d > EditCurve
double endAngle
Base::Vector2d endPoint
Base::Vector2d focusPoint
SelectMode Mode
double startAngle
Base::Vector2d startingPoint
std::vector< AutoConstraint > sugConstr1
std::vector< AutoConstraint > sugConstr2
std::vector< AutoConstraint > sugConstr3
std::vector< AutoConstraint > sugConstr4
Protected Attributes inherited from SketcherGui::DrawSketchHandler
ViewProviderSketch * sketchgui
QCursor oldCursor
QCursor actCursor
QPixmap actCursorPixmap
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
virtual QString getCrosshairCursorSVGName () const
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
void updateCursor ()
updates the actCursor with the icon by calling getCrosshairCursorSVGName(), enabling to set data member dependent icons (i.e.
void unsetCursor (void)
restitutes the cursor that was in use at the moment of starting the DrawSketchHandler (i.e. oldCursor)
void applyCursor (void)
restitutes the DSH cached cursor (e.g. without any tail due to autoconstraints, ...)
unsigned long getCrosshairColor ()
returns the color to be used for the crosshair (configurable as a parameter)
qreal devicePixelRatio ()
functions to set the cursor to a given svgName (to be migrated to NVI style)
void drawEdit (const std::vector< Base::Vector2d > &EditCurve)
void drawEdit (const std::list< std::vector< Base::Vector2d > > &list)
void drawEdit (const std::vector< Part::Geometry * > &geometries)
void drawEditMarkers (const std::vector< Base::Vector2d > &EditMarkers, unsigned int augmentationlevel=0)
void setAxisPickStyle (bool on)
void moveCursorToSketchPoint (Base::Vector2d point)
void preselectAtPoint (Base::Vector2d point)
void drawPositionAtCursor (const Base::Vector2d &position)
void drawDirectionAtCursor (const Base::Vector2d &position, const Base::Vector2d &origin)
int getPreselectPoint (void) const
int getPreselectCurve (void) const
int getPreselectCross (void) const
Sketcher::SketchObject * getSketchObject ()
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
Member Enumeration Documentation
SelectMode
enum SketcherGui::DrawSketchHandlerArcOfParabola::SelectMode
mode table
Enumerator
STATUS_SEEK_First
enum value -—.
STATUS_SEEK_Second
enum value -—.
STATUS_SEEK_Third
enum value -—.
STATUS_SEEK_Fourth
enum value -—.
STATUS_Close
Constructor & Destructor Documentation
DrawSketchHandlerArcOfParabola()
SketcherGui::DrawSketchHandlerArcOfParabola::DrawSketchHandlerArcOfParabola ()
~DrawSketchHandlerArcOfParabola()
virtual SketcherGui::DrawSketchHandlerArcOfParabola::~DrawSketchHandlerArcOfParabola () virtual default
Member Function Documentation
mouseMove()
virtual void SketcherGui::DrawSketchHandlerArcOfParabola::mouseMove (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::applyCursor(), arcAngle, axisPoint, SketcherGui::DrawSketchHandler::drawEdit(), EditCurve, focusPoint, Mode, SketcherGui::DrawSketchHandler::renderSuggestConstraintsCursor(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), SketcherGui::DrawSketchHandler::setPositionText(), startingPoint, STATUS_SEEK_First, STATUS_SEEK_Fourth, STATUS_SEEK_Second, STATUS_SEEK_Third, sugConstr1, sugConstr2, sugConstr3, sugConstr4, Base::Vector2d::x, and Base::Vector2d::y.
pressButton()
virtual bool SketcherGui::DrawSketchHandlerArcOfParabola::pressButton (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
References arcAngle, arcAngle_t, axisPoint, EditCurve, endPoint, focusPoint, Mode, startingPoint, STATUS_Close, STATUS_SEEK_First, STATUS_SEEK_Fourth, STATUS_SEEK_Second, and STATUS_SEEK_Third.
releaseButton()
virtual bool SketcherGui::DrawSketchHandlerArcOfParabola::releaseButton (Base::Vector2d) override virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), SketcherGui::DrawSketchHandler::applyCursor(), arcAngle, axisPoint, Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Base::Console(), SketcherGui::Construction, SketcherGui::DrawSketchHandler::createAutoConstraints(), SketcherGui::DrawSketchHandler::drawEdit(), EditCurve, Sketcher::end, endAngle, endPoint, Base::ConsoleSingleton::Error(), focusPoint, SketcherGui::geometryCreationMode, App::GetApplication(), ParameterGrp::GetBool(), SketcherGui::DrawSketchHandler::getHighestCurveIndex(), Gui::ViewProviderDocumentObject::getObject(), App::Application::GetParameterGroupByPath(), Sketcher::mid, Mode, Gui::Command::openCommand(), SketcherGui::ViewProviderSketch::purgeHandler(), draftutils.translate::QT_TRANSLATE_NOOP, SketcherGui::DrawSketchHandler::resetPositionText(), SketcherGui::DrawSketchHandler::sketchgui, Sketcher::start, startAngle, startingPoint, STATUS_Close, STATUS_SEEK_First, sugConstr1, sugConstr2, sugConstr3, sugConstr4, SketcherGui::tryAutoRecomputeIfNotSolve(), SketcherGui::DrawSketchHandler::unsetCursor(), Base::Vector2d::x, and Base::Vector2d::y.
Member Data Documentation
arcAngle
double SketcherGui::DrawSketchHandlerArcOfParabola::arcAngle protected
Referenced by mouseMove(), pressButton(), and releaseButton().
arcAngle_t
double SketcherGui::DrawSketchHandlerArcOfParabola::arcAngle_t protected
Referenced by pressButton().
axisPoint
Base::Vector2d SketcherGui::DrawSketchHandlerArcOfParabola::axisPoint protected
Referenced by mouseMove(), pressButton(), and releaseButton().
EditCurve
std::vector<Base::Vector2d> SketcherGui::DrawSketchHandlerArcOfParabola::EditCurve protected
Referenced by mouseMove(), pressButton(), and releaseButton().
endAngle
double SketcherGui::DrawSketchHandlerArcOfParabola::endAngle protected
Referenced by releaseButton().
endPoint
Base::Vector2d SketcherGui::DrawSketchHandlerArcOfParabola::endPoint protected
Referenced by pressButton(), and releaseButton().
focusPoint
Base::Vector2d SketcherGui::DrawSketchHandlerArcOfParabola::focusPoint protected
Referenced by mouseMove(), pressButton(), and releaseButton().
Mode
SelectMode SketcherGui::DrawSketchHandlerArcOfParabola::Mode protected
Referenced by mouseMove(), pressButton(), and releaseButton().
startAngle
double SketcherGui::DrawSketchHandlerArcOfParabola::startAngle protected
Referenced by releaseButton().
startingPoint
Base::Vector2d SketcherGui::DrawSketchHandlerArcOfParabola::startingPoint protected
Referenced by mouseMove(), pressButton(), and releaseButton().
sugConstr1
std::vector<AutoConstraint> SketcherGui::DrawSketchHandlerArcOfParabola::sugConstr1 protected
Referenced by mouseMove(), and releaseButton().
sugConstr2
std::vector<AutoConstraint> SketcherGui::DrawSketchHandlerArcOfParabola::sugConstr2 protected
Referenced by mouseMove(), and releaseButton().
sugConstr3
std::vector<AutoConstraint> SketcherGui::DrawSketchHandlerArcOfParabola::sugConstr3 protected
Referenced by mouseMove(), and releaseButton().
sugConstr4
std::vector<AutoConstraint> SketcherGui::DrawSketchHandlerArcOfParabola::sugConstr4 protected
Referenced by mouseMove(), and releaseButton().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfParabola.h