FreeCAD: PartGui::OffsetWidget Class Reference
PartGui::OffsetWidget Class Reference
#include <TaskOffset.h>
Classes
class Private
Public Member Functions
bool accept ()
Part::Offset * getObject () const
OffsetWidget (Part::Offset *, QWidget *parent=nullptr)
bool reject ()
~OffsetWidget ()
Constructor & Destructor Documentation
OffsetWidget()
OffsetWidget::OffsetWidget (Part::Offset * offset, QWidget * parent = nullptr)
References Gui::Command::App, Gui::QuantitySpinBox::bind(), PartGui::Ui_TaskOffset::facesButton, PartGui::Ui_TaskOffset::fillOffset, Base::Persistence::getClassTypeId(), App::PropertyFloat::getValue(), PartGui::Ui_TaskOffset::intersection, Base::BaseClass::isDerivedFrom(), PartGui::Ui_TaskOffset::joinType, Base::Unit::Length, PartGui::Ui_TaskOffset::modeType, draftfunctions.offset::offset(), PartGui::OffsetWidget::Private::offset, PartGui::Ui_TaskOffset::selfIntersection, Gui::QuantitySpinBox::setRange(), Gui::QuantitySpinBox::setSingleStep(), Gui::QuantitySpinBox::setUnit(), PartGui::Ui_TaskOffset::setupUi(), Gui::QuantitySpinBox::setValue(), PartGui::Ui_TaskOffset::spinOffset, PartGui::OffsetWidget::Private::ui, and Part::Offset::Value.
~OffsetWidget()
OffsetWidget::~OffsetWidget ()
Member Function Documentation
accept()
bool OffsetWidget::accept (void)
References Gui::QuantitySpinBox::apply(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Gui::Command::Doc, PartGui::Ui_TaskOffset::fillOffset, App::DocumentObject::getStatusString(), Base::Quantity::getValue(), Gui::Command::Gui, PartGui::Ui_TaskOffset::intersection, App::DocumentObject::isValid(), PartGui::Ui_TaskOffset::joinType, PartGui::Ui_TaskOffset::modeType, PartGui::OffsetWidget::Private::offset, PartGui::Ui_TaskOffset::selfIntersection, PartGui::Ui_TaskOffset::spinOffset, PartGui::OffsetWidget::Private::ui, and Gui::QuantitySpinBox::value.
Referenced by PartGui::TaskOffset::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
getObject()
Part::Offset * OffsetWidget::getObject (void) const
References PartGui::OffsetWidget::Private::offset.
Referenced by PartGui::TaskOffset::getObject().
reject()
bool OffsetWidget::reject (void)
References Gui::Command::abortCommand(), App::PropertyLink::getValue(), Gui::Application::getViewProvider(), Gui::Command::Gui, Gui::Application::Instance, PartGui::OffsetWidget::Private::offset, Gui::ViewProvider::show(), Part::Offset::Source, and Gui::Command::updateActive().
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), PartGui::TaskOffset::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/TaskOffset.h
FreeCAD/src/Mod/Part/Gui/TaskOffset.cpp