FreeCAD: TechDrawGui::QGMText Class Reference
TechDrawGui::QGMText Class Reference
#include <QGMText.h>
Public Types
enum { Type = QGraphicsItem::UserType + 300 }
Public Types inherited from TechDrawGui::QGCustomText
enum { Type = QGraphicsItem::UserType + 130 }
Signals
void dragFinished ()
void dragging ()
void hover (bool state)
void selected (bool state)
Public Member Functions
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0) override
QGMText (void)
virtual void setPrettyNormal () override
virtual void setPrettyPre () override
virtual void setPrettySel () override
virtual void showBox (bool b)
virtual bool showBox (void)
int type () const override
~QGMText ()
Public Member Functions inherited from TechDrawGui::QGCustomText
virtual QRectF boundingRect () const override
virtual void centerAt (double cX, double cY)
virtual void centerAt (QPointF centerPos)
virtual double getHeight (void)
virtual QColor getNormalColor (void)
virtual QColor getPreColor (void)
virtual QColor getSelectColor (void)
virtual double getWidth (void)
virtual void justifyLeftAt (double cX, double cY, bool vCenter=true)
virtual void justifyLeftAt (QPointF centerPos, bool vCenter=true)
virtual void justifyRightAt (double cX, double cY, bool vCenter=true)
virtual void justifyRightAt (QPointF centerPos, bool vCenter=true)
void makeMark (Base::Vector3d v)
void makeMark (double x, double y)
QGCustomText (QGraphicsItem *parent=nullptr)
virtual void setColor (QColor c)
void setHighlighted (bool state)
virtual void setTightBounding (bool tight)
QPointF tightBoundingAdjust () const
QRectF tightBoundingRect () const
int type () const override
~QGCustomText ()
Protected Member Functions
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions inherited from TechDrawGui::QGCustomText
Base::Reference< ParameterGrp > getParmGroup (void)
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
Additional Inherited Members
Protected Attributes inherited from TechDrawGui::QGCustomText
bool isHighlighted
QColor m_colCurrent
QColor m_colNormal
bool tightBounding
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGMText()
QGMText::QGMText (void) explicit
~QGMText()
TechDrawGui::QGMText::~QGMText ()
Member Function Documentation
dragFinished
void TechDrawGui::QGMText::dragFinished () signal
Referenced by mouseReleaseEvent().
dragging
void TechDrawGui::QGMText::dragging () signal
Referenced by itemChange().
hover
void TechDrawGui::QGMText::hover (bool state) signal
Referenced by hoverEnterEvent(), and hoverLeaveEvent().
hoverEnterEvent()
void QGMText::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected virtual
Reimplemented from TechDrawGui::QGCustomText.
References hover(), TechDrawGui::QGCustomText::hoverEnterEvent(), and setPrettyPre().
hoverLeaveEvent()
void QGMText::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected virtual
Reimplemented from TechDrawGui::QGCustomText.
References hover(), TechDrawGui::QGCustomText::hoverLeaveEvent(), and setPrettyNormal().
itemChange()
QVariant QGMText::itemChange (GraphicsItemChange change, const QVariant & value) override protected virtual
References dragging(), and TechDrawGui::QGCustomText::itemChange().
mouseMoveEvent()
void QGMText::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override protected virtual
mousePressEvent()
void QGMText::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected virtual
mouseReleaseEvent()
void QGMText::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override virtual
References dragFinished().
paint()
void QGMText::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) override virtual
Reimplemented from TechDrawGui::QGCustomText.
References TechDrawGui::QGCustomText::boundingRect(), TechDrawGui::QGCustomText::paint(), and showBox().
selected
void TechDrawGui::QGMText::selected (bool state) signal
Referenced by PathScripts.PathDressupTagGui.HoldingTagMarker::setEnabled(), and PathScripts.PathDressupTagGui.HoldingTagMarker::setSelected().
setPrettyNormal()
void QGMText::setPrettyNormal (void) override virtual
Reimplemented from TechDrawGui::QGCustomText.
References TechDrawGui::QGCustomText::setPrettyNormal().
Referenced by hoverLeaveEvent().
setPrettyPre()
void QGMText::setPrettyPre (void) override virtual
Reimplemented from TechDrawGui::QGCustomText.
References TechDrawGui::QGCustomText::setPrettyPre().
Referenced by hoverEnterEvent().
setPrettySel()
void QGMText::setPrettySel (void) override virtual
Reimplemented from TechDrawGui::QGCustomText.
References TechDrawGui::QGCustomText::setPrettySel().
showBox() [1/2]
virtual void TechDrawGui::QGMText::showBox (bool b) virtual
showBox() [2/2]
virtual bool TechDrawGui::QGMText::showBox (void) virtual
Referenced by paint().
type()
int TechDrawGui::QGMText::type (void) const override
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGMText.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGMText.cpp