FreeCAD: FreeCADGuiInit.Workbench Class Reference
FreeCADGuiInit.Workbench Class Reference
Public Member Functions
def appendCommandbar (self, name, cmds)
def appendContextMenu (self, name, cmds)
def appendMenu (self, name, cmds)
def appendToolbar (self, name, cmds)
def ContextMenu (self, recipient)
def GetClassName (self)
def getToolbarItems (self)
def Initialize (self)
def listCommandbars (self)
def listMenus (self)
def listToolbars (self)
def name (self)
def removeCommandbar (self, name)
def removeContextMenu (self, name)
def removeMenu (self, name)
def removeToolbar (self, name)
Static Public Attributes
string MenuText = ""
string ToolTip = ""
Detailed Description
The workbench base class.
Member Function Documentation
appendCommandbar()
def FreeCADGuiInit.Workbench.appendCommandbar (self, name, cmds)
Referenced by InitGui.TemplatePyModWorkbench.Initialize(), and Mod.Test.InitGui.TestWorkbench.Initialize().
appendContextMenu()
def FreeCADGuiInit.Workbench.appendContextMenu (self, name, cmds)
Referenced by InitGui.ArchWorkbench.ContextMenu(), and InitGui.DraftWorkbench.ContextMenu().
appendMenu()
def FreeCADGuiInit.Workbench.appendMenu (self, name, cmds)
Referenced by InitGui.OpenSCADWorkbench.Initialize(), InitGui.PathWorkbench.Initialize(), InitGui.PlotWorkbench.Initialize(), InitGui.ShipWorkbench.Initialize(), InitGui.TemplatePyModWorkbench.Initialize(), and Mod.Test.InitGui.TestWorkbench.Initialize().
appendToolbar()
def FreeCADGuiInit.Workbench.appendToolbar (self, name, cmds)
Referenced by InitGui.OpenSCADWorkbench.Initialize(), InitGui.PathWorkbench.Initialize(), InitGui.PlotWorkbench.Initialize(), InitGui.ShipWorkbench.Initialize(), InitGui.TemplatePyModWorkbench.Initialize(), Mod.Test.InitGui.TestWorkbench.Initialize(), and Mod.Test.Workbench.WorkbenchTestCase.testHandler().
ContextMenu()
def FreeCADGuiInit.Workbench.ContextMenu (self, recipient)
GetClassName()
def FreeCADGuiInit.Workbench.GetClassName (self)
Return the name of the associated C++ class.
Reimplemented in FreeCADGuiInit.NoneWorkbench, and FreeCADGuiInit.StandardWorkbench.
getToolbarItems()
def FreeCADGuiInit.Workbench.getToolbarItems (self)
Initialize()
def FreeCADGuiInit.Workbench.Initialize (self)
Initializes this workbench.
Reimplemented in FreeCADGuiInit.NoneWorkbench, and FreeCADGuiInit.StandardWorkbench.
listCommandbars()
def FreeCADGuiInit.Workbench.listCommandbars (self)
listMenus()
def FreeCADGuiInit.Workbench.listMenus (self)
listToolbars()
def FreeCADGuiInit.Workbench.listToolbars (self)
name()
def FreeCADGuiInit.Workbench.name (self)
removeCommandbar()
def FreeCADGuiInit.Workbench.removeCommandbar (self, name)
removeContextMenu()
def FreeCADGuiInit.Workbench.removeContextMenu (self, name)
removeMenu()
def FreeCADGuiInit.Workbench.removeMenu (self, name)
removeToolbar()
def FreeCADGuiInit.Workbench.removeToolbar (self, name)
Member Data Documentation
MenuText
string FreeCADGuiInit.Workbench.MenuText = "" static
ToolTip
string FreeCADGuiInit.Workbench.ToolTip = "" static
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/FreeCADGuiInit.py