FreeCAD: PartGui::Ui_TaskLoft Class Reference
PartGui::Ui_TaskLoft Class Reference
#include <ui_TaskLoft.h>
Public Member Functions
void retranslateUi (QWidget *PartGui__TaskLoft)
void setupUi (QWidget *PartGui__TaskLoft)
Public Attributes
QCheckBox * checkClosed
QCheckBox * checkRuledSurface
QCheckBox * checkSolid
QGridLayout * gridLayout
QSpacerItem * horizontalSpacer
Gui::ActionSelector * selector
Member Function Documentation
retranslateUi()
void PartGui::Ui_TaskLoft::retranslateUi (QWidget * PartGui__TaskLoft)
References checkClosed, checkRuledSurface, checkSolid, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void PartGui::Ui_TaskLoft::setupUi (QWidget * PartGui__TaskLoft)
References checkClosed, checkRuledSurface, checkSolid, gridLayout, horizontalSpacer, retranslateUi(), and selector.
Referenced by PartGui::LoftWidget::LoftWidget().
Member Data Documentation
checkClosed
QCheckBox* PartGui::Ui_TaskLoft::checkClosed
Referenced by PartGui::LoftWidget::accept(), retranslateUi(), and setupUi().
checkRuledSurface
QCheckBox* PartGui::Ui_TaskLoft::checkRuledSurface
Referenced by PartGui::LoftWidget::accept(), retranslateUi(), and setupUi().
checkSolid
QCheckBox* PartGui::Ui_TaskLoft::checkSolid
Referenced by PartGui::LoftWidget::accept(), retranslateUi(), and setupUi().
gridLayout
QGridLayout* PartGui::Ui_TaskLoft::gridLayout
Referenced by setupUi().
horizontalSpacer
QSpacerItem* PartGui::Ui_TaskLoft::horizontalSpacer
Referenced by setupUi().
selector
Gui::ActionSelector* PartGui::Ui_TaskLoft::selector
Referenced by PartGui::LoftWidget::accept(), PartGui::LoftWidget::LoftWidget(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Part/Gui/ui_TaskLoft.h