FreeCAD: SketcherGui::TaskDlgEditSketch Class Reference
SketcherGui::TaskDlgEditSketch Class Reference
simulation dialog for the TaskView
#include <TaskDlgEditSketch.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void clicked (int)
is called by the framework if an button is clicked which has no accept or reject role
ViewProviderSketch * getSketchView () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
returns for Close and Help button
virtual bool isAllowedAlterDocument (void) const
virtual void open ()
is called the TaskView when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgEditSketch (ViewProviderSketch *sketchView)
~TaskDlgEditSketch ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Protected Member Functions
void slotRedoDocument (const App::Document &)
void slotUndoDocument (const App::Document &)
Protected Attributes
TaskSketcherConstrains * Constraints
TaskSketcherElements * Elements
TaskSketcherGeneral * General
TaskSketcherMessages * Messages
ViewProviderSketch * sketchView
TaskSketcherSolverAdvanced * SolverAdvanced
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
simulation dialog for the TaskView
Constructor & Destructor Documentation
TaskDlgEditSketch()
TaskDlgEditSketch::TaskDlgEditSketch (ViewProviderSketch * sketchView)
References Constraints, Gui::TaskView::TaskDialog::Content, Elements, General, App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), Gui::TaskView::TaskBox::hideGroupBox(), Messages, Gui::TaskView::TaskDialog::setEscapeButtonEnabled(), sketchView, and SolverAdvanced.
~TaskDlgEditSketch()
TaskDlgEditSketch::~TaskDlgEditSketch ()
References Gui::TaskView::TaskDialog::Content, DraftVecUtils::find(), and SolverAdvanced.
Member Function Documentation
accept()
bool TaskDlgEditSketch::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
clicked()
void TaskDlgEditSketch::clicked (int) virtual
is called by the framework if an button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
getSketchView()
ViewProviderSketch* SketcherGui::TaskDlgEditSketch::getSketchView () const
Referenced by SketcherGui::ViewProviderSketch::setEdit().
getStandardButtons()
virtual QDialogButtonBox::StandardButtons SketcherGui::TaskDlgEditSketch::getStandardButtons (void) const virtual
returns for Close and Help button
Reimplemented from Gui::TaskView::TaskDialog.
isAllowedAlterDocument()
virtual bool SketcherGui::TaskDlgEditSketch::isAllowedAlterDocument (void) const virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
open()
void TaskDlgEditSketch::open () virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
reject()
bool TaskDlgEditSketch::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References Constraints, Gui::Command::Doc, Elements, General, App::GetApplication(), Gui::TaskView::TaskDialog::getDocumentName(), App::Application::GetParameterGroupByPath(), Gui::Command::Gui, Gui::TaskView::TaskBox::isGroupVisible(), Messages, ParameterGrp::SetBool(), and SolverAdvanced.
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
slotRedoDocument()
void SketcherGui::TaskDlgEditSketch::slotRedoDocument (const App::Document &) protected
slotUndoDocument()
void SketcherGui::TaskDlgEditSketch::slotUndoDocument (const App::Document &) protected
Member Data Documentation
Constraints
TaskSketcherConstrains* SketcherGui::TaskDlgEditSketch::Constraints protected
Referenced by reject(), and TaskDlgEditSketch().
Elements
TaskSketcherElements* SketcherGui::TaskDlgEditSketch::Elements protected
Referenced by reject(), and TaskDlgEditSketch().
General
TaskSketcherGeneral* SketcherGui::TaskDlgEditSketch::General protected
Referenced by reject(), and TaskDlgEditSketch().
Messages
TaskSketcherMessages* SketcherGui::TaskDlgEditSketch::Messages protected
Referenced by reject(), and TaskDlgEditSketch().
sketchView
ViewProviderSketch* SketcherGui::TaskDlgEditSketch::sketchView protected
Referenced by TaskDlgEditSketch().
SolverAdvanced
TaskSketcherSolverAdvanced* SketcherGui::TaskDlgEditSketch::SolverAdvanced protected
Referenced by reject(), TaskDlgEditSketch(), and ~TaskDlgEditSketch().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sketcher/Gui/TaskDlgEditSketch.h
Sources/FreeCAD/src/Mod/Sketcher/Gui/TaskDlgEditSketch.cpp