FreeCAD: Gui::Dialog::Ui_DlgMacroRecord Class Reference
Gui::Dialog::Ui_DlgMacroRecord Class Reference
#include <ui_DlgMacroRecord.h>
Public Member Functions
void retranslateUi (QDialog *Gui__Dialog__DlgMacroRecord)
void setupUi (QDialog *Gui__Dialog__DlgMacroRecord)
Public Attributes
QPushButton * buttonCancel
QPushButton * buttonStart
QPushButton * buttonStop
QGridLayout * gridLayout
QGroupBox * groupBox
QGroupBox * groupBox_2
QHBoxLayout * hboxLayout
QHBoxLayout * hboxLayout1
QLineEdit * lineEditMacroPath
QLineEdit * lineEditPath
QPushButton * pushButtonChooseDir
QSpacerItem * spacerItem
QVBoxLayout * vboxLayout
Member Function Documentation
retranslateUi()
void Gui::Dialog::Ui_DlgMacroRecord::retranslateUi (QDialog * Gui__Dialog__DlgMacroRecord)
References buttonCancel, buttonStart, buttonStop, groupBox, groupBox_2, pushButtonChooseDir, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::Dialog::Ui_DlgMacroRecord::setupUi (QDialog * Gui__Dialog__DlgMacroRecord)
References buttonCancel, buttonStart, buttonStop, gridLayout, groupBox, groupBox_2, hboxLayout, hboxLayout1, lineEditMacroPath, lineEditPath, pushButtonChooseDir, retranslateUi(), spacerItem, and vboxLayout.
Member Data Documentation
buttonCancel
QPushButton* Gui::Dialog::Ui_DlgMacroRecord::buttonCancel
Referenced by retranslateUi(), and setupUi().
buttonStart
QPushButton* Gui::Dialog::Ui_DlgMacroRecord::buttonStart
Referenced by retranslateUi(), and setupUi().
buttonStop
QPushButton* Gui::Dialog::Ui_DlgMacroRecord::buttonStop
Referenced by retranslateUi(), and setupUi().
gridLayout
QGridLayout* Gui::Dialog::Ui_DlgMacroRecord::gridLayout
Referenced by setupUi().
groupBox
QGroupBox* Gui::Dialog::Ui_DlgMacroRecord::groupBox
Referenced by retranslateUi(), and setupUi().
groupBox_2
QGroupBox* Gui::Dialog::Ui_DlgMacroRecord::groupBox_2
Referenced by retranslateUi(), and setupUi().
hboxLayout
QHBoxLayout* Gui::Dialog::Ui_DlgMacroRecord::hboxLayout
Referenced by setupUi().
hboxLayout1
QHBoxLayout* Gui::Dialog::Ui_DlgMacroRecord::hboxLayout1
Referenced by setupUi().
lineEditMacroPath
QLineEdit* Gui::Dialog::Ui_DlgMacroRecord::lineEditMacroPath
Referenced by setupUi().
lineEditPath
QLineEdit* Gui::Dialog::Ui_DlgMacroRecord::lineEditPath
Referenced by setupUi().
pushButtonChooseDir
QPushButton* Gui::Dialog::Ui_DlgMacroRecord::pushButtonChooseDir
Referenced by retranslateUi(), and setupUi().
spacerItem
QSpacerItem* Gui::Dialog::Ui_DlgMacroRecord::spacerItem
Referenced by setupUi().
vboxLayout
QVBoxLayout* Gui::Dialog::Ui_DlgMacroRecord::vboxLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_DlgMacroRecord.h