FreeCAD: Gui::Dialog::DlgOnlineHelpImp Class Reference
Gui::Dialog::DlgOnlineHelpImp Class Reference
This class implements the dialog for downloading the online documentation.
#include <DlgOnlineHelpImp.h>
Public Member Functions
DlgOnlineHelpImp (QWidget *parent=nullptr)
Constructs a DlgOnlineHelpImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
void loadSettings ()
void saveSettings ()
~DlgOnlineHelpImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Static Public Member Functions
static QString getStartpage ()
Returns the start page for the HelpView.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void on_lineEditDownload_fileNameSelected (const QString &)
virtual void changeEvent (QEvent *e)=0
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Detailed Description
This class implements the dialog for downloading the online documentation.
Moreover it allows to specify location of the start page an an external browser. Here you can specify to use a proxy if necessary and some more stuff.
Author
Werner Mayer
Constructor & Destructor Documentation
DlgOnlineHelpImp()
DlgOnlineHelpImp::DlgOnlineHelpImp (QWidget * parent = nullptr)
Constructs a DlgOnlineHelpImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
References getStartpage().
~DlgOnlineHelpImp()
DlgOnlineHelpImp::~DlgOnlineHelpImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void DlgOnlineHelpImp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
getStartpage()
QString DlgOnlineHelpImp::getStartpage () static
Returns the start page for the HelpView.
If none is defined the default start page "<FreeCADHome>/doc/free-cad.sourceforge.net/wiki/index.php.html" is returned.
Remarks
It is not checked if the returned page really exists.
References App::Application::getHelpDir().
Referenced by DlgOnlineHelpImp().
loadSettings()
void DlgOnlineHelpImp::loadSettings () virtual
Implements Gui::Dialog::PreferencePage.
on_lineEditDownload_fileNameSelected()
void DlgOnlineHelpImp::on_lineEditDownload_fileNameSelected (const QString & url) protected
saveSettings()
void DlgOnlineHelpImp::saveSettings () virtual
Implements Gui::Dialog::PreferencePage.
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgOnlineHelpImp.h
FreeCAD/src/Gui/DlgOnlineHelpImp.cpp