FreeCAD: femexamples.ccx_cantilever_ele_hexa20 Namespace Reference
femexamples.ccx_cantilever_ele_hexa20 Namespace Reference
Functions
def get_explanation (header="")
def get_information ()
def setup (doc=None, solvertype="ccxtools")
Function Documentation
get_explanation()
def femexamples.ccx_cantilever_ele_hexa20.get_explanation (header = "")
Referenced by femexamples.ccx_cantilever_ele_hexa20.setup().
get_information()
def femexamples.ccx_cantilever_ele_hexa20.get_information ()
Referenced by femexamples.ccx_cantilever_ele_hexa20.setup().
setup()
def femexamples.ccx_cantilever_ele_hexa20.setup (doc = None, solvertype = "ccxtools")
References femexamples.ccx_cantilever_ele_hexa20.get_explanation(), and femexamples.ccx_cantilever_ele_hexa20.get_information().