FreeCAD: PartGui::BoxSelection Class Reference
PartGui::BoxSelection Class Reference
#include <BoxSelection.h>
Classes
class FaceSelectionGate
Public Member Functions
BoxSelection ()
bool isAutoDelete () const
void setAutoDelete (bool)
void start (TopAbs_ShapeEnum shape)
~BoxSelection ()
Constructor & Destructor Documentation
BoxSelection()
BoxSelection::BoxSelection ()
~BoxSelection()
BoxSelection::~BoxSelection ()
Member Function Documentation
isAutoDelete()
bool BoxSelection::isAutoDelete () const
setAutoDelete()
void BoxSelection::setAutoDelete (bool on)
start()
void BoxSelection::start (TopAbs_ShapeEnum shape)
References Gui::getMainWindow(), Gui::View3DInventorViewer::Rubberband, and OfflineRenderingUtils::viewer().
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::asString(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::clone(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::hasStart(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::negated(), and Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::value().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/BoxSelection.h
FreeCAD/src/Mod/Part/Gui/BoxSelection.cpp