FreeCAD: ObjectPool< X > Class Template Reference
ObjectPool< X > Class Template Reference
#include <ObjectPool.hxx>
Public Member Functions
void clear ()
void destroy (X *obj)
X * getNew ()
ObjectPool (int nblk)
virtual ~ObjectPool ()
Constructor & Destructor Documentation
ObjectPool()
template<class X > ObjectPool< X >::ObjectPool (int nblk)
~ObjectPool()
template<class X > virtual ObjectPool< X >::~ObjectPool () virtual
Member Function Documentation
clear()
template<class X > void ObjectPool< X >::clear ()
Referenced by SMDS_Mesh::Clear().
destroy()
template<class X > void ObjectPool< X >::destroy (X * obj)
Referenced by SMDS_Mesh::AddBallWithID(), SMDS_Mesh::AddEdgeWithID(), SMDS_Mesh::AddFaceFromVtkIdsWithID(), SMDS_Mesh::AddFaceWithID(), SMDS_Mesh::AddPolygonalFaceWithID(), SMDS_Mesh::AddPolyhedralVolumeWithID(), SMDS_Mesh::AddQuadPolygonalFaceWithID(), SMDS_Mesh::AddVolumeFromVtkIdsWithID(), SMDS_Mesh::AddVolumeWithID(), SMDS_Mesh::createQuadrangle(), SMDS_Mesh::createTriangle(), SMDS_Mesh::FindEdgeOrCreate(), SMDS_Mesh::RemoveElement(), and SMDS_Mesh::RemoveFreeElement().
getNew()
template<class X > X* ObjectPool< X >::getNew ()
Referenced by SMDS_Mesh::AddBallWithID(), SMDS_Mesh::AddEdgeWithID(), SMDS_Mesh::AddFaceFromVtkIdsWithID(), SMDS_Mesh::AddFaceWithID(), SMDS_Mesh::AddNodeWithID(), SMDS_Mesh::AddPolygonalFaceWithID(), SMDS_Mesh::AddPolyhedralVolumeWithID(), SMDS_Mesh::AddQuadPolygonalFaceWithID(), SMDS_Mesh::AddVolumeFromVtkIdsWithID(), SMDS_Mesh::AddVolumeWithID(), SMDS_Mesh::createQuadrangle(), SMDS_Mesh::createTriangle(), and SMDS_Mesh::FindEdgeOrCreate().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/ObjectPool.hxx