FreeCAD: Gui::NS::StickyPanState Class Reference
Gui::NS::StickyPanState Class Reference
Public Types
typedef sc::custom_reaction< NS::Event > reactions
Public Member Functions
sc::result react (const NS::Event &ev)
StickyPanState (my_context ctx)
virtual ~StickyPanState ()
Member Typedef Documentation
reactions
typedef sc::custom_reaction<NS::Event> Gui::NS::StickyPanState::reactions
Constructor & Destructor Documentation
StickyPanState()
Gui::NS::StickyPanState::StickyPanState (my_context ctx)
References Base::Console(), Base::ConsoleSingleton::Log(), and Gui::NavigationStyle::PANNING.
~StickyPanState()
virtual Gui::NS::StickyPanState::~StickyPanState () virtual
Member Function Documentation
react()
sc::result Gui::NS::StickyPanState::react (const NS::Event & ev)
References Gui::NS::Event::flags, Gui::NS::Event::inventor_event, Gui::NS::Event::isLocation2Event(), Gui::NS::Event::isMouseButtonEvent(), and Gui::NS::Event::isRelease().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/GestureNavigationStyle.cpp