FreeCAD: Gui::NS::AwaitingMoveState Class Reference
Gui::NS::AwaitingMoveState Class Reference
Public Types
typedef sc::custom_reaction< NS::Event > reactions
Public Member Functions
AwaitingMoveState (my_context ctx)
sc::result react (const NS::Event &ev)
virtual ~AwaitingMoveState ()
Member Typedef Documentation
reactions
typedef sc::custom_reaction<NS::Event> Gui::NS::AwaitingMoveState::reactions
Constructor & Destructor Documentation
AwaitingMoveState()
Gui::NS::AwaitingMoveState::AwaitingMoveState (my_context ctx)
References Base::Console(), App::GetApplication(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), Gui::NavigationStyle::IDLE, and Base::ConsoleSingleton::Log().
~AwaitingMoveState()
virtual Gui::NS::AwaitingMoveState::~AwaitingMoveState () virtual
Member Function Documentation
react()
sc::result Gui::NS::AwaitingMoveState::react (const NS::Event & ev)
refire(): forwards all postponed events + this event
References Gui::NS::Event::ALTDOWN, Gui::NS::Event::flags, Gui::NS::Event::inventor_event, Gui::NS::Event::isGestureActive(), Gui::NS::Event::isLocation2Event(), Gui::NS::Event::isMouseButtonEvent(), Gui::NS::Event::isPress(), Gui::NS::Event::isRelease(), Gui::NS::Event::mbstate(), Gui::NS::Event::modifiers, and Gui::NavigationStyle::SELECTION.
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/GestureNavigationStyle.cpp