FreeCAD: automotive_design.universal_pair Class Reference
automotive_design.universal_pair Class Reference
Public Member Functions
def input_skew_angle ()
def skew_angle ()
def wr1 (self)
Public Member Functions inherited from automotive_design.kinematic_pair
def joint ()
def pair_placement_in_first_link_context ()
def pair_placement_in_second_link_context ()
def wr2 (self)
Public Member Functions inherited from automotive_design.item_defined_transformation
def description ()
def name ()
def transform_item_1 ()
def transform_item_2 ()
Public Attributes
input_skew_angle
Public Attributes inherited from automotive_design.kinematic_pair
joint
Public Attributes inherited from automotive_design.item_defined_transformation
description
name
transform_item_1
transform_item_2
Detailed Description
Entity universal_pair definition.
        :param input_skew_angle
        :type input_skew_angle:plane_angle_measure
        :param skew_angle
        :type skew_angle:plane_angle_measure
Member Function Documentation
input_skew_angle()
def automotive_design.universal_pair.input_skew_angle ()
References automotive_design.universal_pair._input_skew_angle, and automotive_design.universal_pair.input_skew_angle.
skew_angle()
def automotive_design.universal_pair.skew_angle ()
References automotive_design.universal_pair.input_skew_angle.
Referenced by automotive_design.universal_pair.wr1().
wr1()
def automotive_design.universal_pair.wr1 (self)
Reimplemented from automotive_design.kinematic_pair.
Reimplemented in automotive_design.homokinetic_pair.
References automotive_design.plane_angle_for_pair_in_radian(), and automotive_design.universal_pair.skew_angle().
Member Data Documentation
input_skew_angle
automotive_design.universal_pair.input_skew_angle
Referenced by automotive_design.universal_pair.input_skew_angle(), and automotive_design.universal_pair.skew_angle().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Import/App/automotive_design.py