FreeCAD: Ui_TaskSketcherMessages Class Reference
Ui_TaskSketcherMessages Class Reference
#include <ui_TaskSketcherMessages.h>
Public Member Functions
void retranslateUi (QWidget *TaskSketcherMessages)
void setupUi (QWidget *TaskSketcherMessages)
Public Attributes
Gui::PrefCheckBox * autoRemoveRedundants
Gui::PrefCheckBox * autoUpdate
QHBoxLayout * horizontalLayout
QHBoxLayout * horizontalLayout_2
QSpacerItem * horizontalSpacer
Gui::StatefulLabel * labelConstrainStatus
Gui::UrlLabel * labelConstrainStatusLink
QPushButton * manualUpdate
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void Ui_TaskSketcherMessages::retranslateUi (QWidget * TaskSketcherMessages)
References autoRemoveRedundants, autoUpdate, labelConstrainStatus, labelConstrainStatusLink, manualUpdate, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Ui_TaskSketcherMessages::setupUi (QWidget * TaskSketcherMessages)
References autoRemoveRedundants, autoUpdate, horizontalLayout, horizontalLayout_2, horizontalSpacer, labelConstrainStatus, labelConstrainStatusLink, manualUpdate, retranslateUi(), and verticalLayout.
Member Data Documentation
autoRemoveRedundants
Gui::PrefCheckBox* Ui_TaskSketcherMessages::autoRemoveRedundants
Referenced by retranslateUi(), and setupUi().
autoUpdate
Gui::PrefCheckBox* Ui_TaskSketcherMessages::autoUpdate
Referenced by retranslateUi(), and setupUi().
horizontalLayout
QHBoxLayout* Ui_TaskSketcherMessages::horizontalLayout
Referenced by setupUi().
horizontalLayout_2
QHBoxLayout* Ui_TaskSketcherMessages::horizontalLayout_2
Referenced by setupUi().
horizontalSpacer
QSpacerItem* Ui_TaskSketcherMessages::horizontalSpacer
Referenced by setupUi().
labelConstrainStatus
Gui::StatefulLabel* Ui_TaskSketcherMessages::labelConstrainStatus
Referenced by retranslateUi(), and setupUi().
labelConstrainStatusLink
Gui::UrlLabel* Ui_TaskSketcherMessages::labelConstrainStatusLink
Referenced by retranslateUi(), and setupUi().
manualUpdate
QPushButton* Ui_TaskSketcherMessages::manualUpdate
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* Ui_TaskSketcherMessages::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/ui_TaskSketcherMessages.h