FreeCAD: SMESH::Controls::ElemGeomType Class Reference
SMESH::Controls::ElemGeomType Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
ElemGeomType ()
SMDSAbs_GeometryType GetGeomType () const
virtual SMDSAbs_ElementType GetType () const
virtual bool IsSatisfy (long theElementId)
void SetGeomType (SMDSAbs_GeometryType theType)
virtual void SetMesh (const SMDS_Mesh *theMesh)
void SetType (SMDSAbs_ElementType theType)
Public Member Functions inherited from SMESH::Controls::Functor
~Functor ()
Constructor & Destructor Documentation
ElemGeomType()
ElemGeomType::ElemGeomType ()
References SMESH::Controls::FreeEdges::myMesh.
Member Function Documentation
GetGeomType()
SMDSAbs_GeometryType ElemGeomType::GetGeomType () const
GetType()
SMDSAbs_ElementType ElemGeomType::GetType () const virtual
Implements SMESH::Controls::Predicate.
IsSatisfy()
bool ElemGeomType::IsSatisfy (long theElementId) virtual
Implements SMESH::Controls::Predicate.
References SMDS_Mesh::FindElement(), SMDS_MeshElement::GetGeomType(), SMDS_MeshElement::GetType(), and SMESH::Controls::FreeEdges::myMesh.
SetGeomType()
void ElemGeomType::SetGeomType (SMDSAbs_GeometryType theType)
SetMesh()
void ElemGeomType::SetMesh (const SMDS_Mesh * theMesh) virtual
Implements SMESH::Controls::Functor.
References SMESH::Controls::FreeEdges::myMesh.
SetType()
void ElemGeomType::SetType (SMDSAbs_ElementType theType)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp