FreeCAD: Gui::PythonCommand Class Reference
Gui::PythonCommand Class Reference
The Python command class This is a special type of command class.
#include <Command.h>
Public Member Functions
PythonCommand (const char *name, PyObject *pcPyCommand, const char *pActivationString)
virtual ~PythonCommand ()
Public Member Functions inherited from Gui::Command
const char * beginCmdHelp (void)
returns the begin of a online help page
const char * endCmdHelp (void)
returns the end of a online help page
bool hasActiveDocument (void) const
true when there is a document
bool hasObject (const char *Name)
true when there is a document and a Feature with Name
const char * getAppModuleName (void) const
returns the name to which the command belongs
void setAppModuleName (const char *)
const char * getName () const
Get the command name.
const char * getGroupName () const
Get the name of the grouping of the command.
void setGroupName (const char *)
void testActive (void)
Get somtile called to check the state of the command.
void setEnabled (bool)
Enables or disables the command.
TriggerSource triggerSource () const
Return the current command trigger source.
void invoke (int index, TriggerSource trigger=TriggerNone)
Called to invoke the command.
void addTo (QWidget *)
adds this command to arbitrary widgets
void addToGroup (ActionGroup *, bool checkable)
void addToGroup (ActionGroup *)
Gui::Document * getActiveGuiDocument (void) const
Get pointer to the active gui document.
App::Document * getDocument (const char *Name=0) const
Get pointer to the named or active App document Returns a pointer to the named document or the active document when no name is given.
bool isViewOfType (Base::Type t) const
checks if the active view is of a special type or derived
App::DocumentObject * getObject (const char *Name) const
returns the named feature or the active one from the active document or NULL
std::string getUniqueObjectName (const char *BaseName, const App::DocumentObject *obj=0) const
Get unique Feature name from the active document.
void updateAction (int mode)
Updates the QAction with respect to the passed mode.
void setupCheckable (int iMsg)
Setup checkable actions based on current TriggerSource.
const std::string strToPython (const char *Str)
translate a string to a python string literal (needed e.g. in file names for windows...)
const std::string strToPython (const std::string &Str)
void adjustCameraPosition ()
Public Member Functions inherited from Gui::CommandBase
Action * getAction () const
Returns the Action object of this command, or 0 if it doesn't exist.
void setWhatsThis (const char *)
void setMenuText (const char *)
void setToolTipText (const char *)
void setStatusTip (const char *)
void setPixmap (const char *)
void setAccel (const char *)
Protected Member Functions
Methods reimplemented for Command Framework
virtual void activated (int iMsg)
Method which gets called when activated.
virtual bool isActive (void)
if the command is not always active
const char * getHelpUrl (void) const
Get the help URL.
virtual Action * createAction (void)
Creates the used Action.
Protected Member Functions inherited from Gui::Command
Command (const char *name)
virtual ~Command ()
void applyCommandData (const char *context, Action *)
Applies the menu text, tool and status tip to the passed action object.
const char * keySequenceToAccel (int) const
Protected Member Functions inherited from Gui::CommandBase
CommandBase (const char *sMenu, const char *sToolTip=0, const char *sWhat=0, const char *sStatus=0, const char *sPixmap=0, const char *sAccel=0)
virtual ~CommandBase ()
Methods to get the properties of the command
std::string Activation
the activation sequence
void languageChange ()
Reassigns QAction stuff after the language has changed.
const char * className () const
The C++ class name is needed as context for the translation framework.
const char * getWhatsThis () const
const char * getMenuText () const
const char * getToolTipText () const
const char * getStatusTip () const
const char * getPixmap () const
const char * getAccel () const
bool isCheckable () const
bool isChecked () const
const char * getResource (const char *sName) const
Returns the resource values.
Additional Inherited Members
Public Types inherited from Gui::Command
enum TriggerSource { TriggerNone, TriggerAction, TriggerChildAction }
Command trigger source.
enum DoCmd_Type { Doc, App, Gui }
types of application level actions for DoCommand()
Static Public Member Functions inherited from Gui::Command
static Application * getGuiApplication (void)
Get pointer to the Application Window.
static Gui::SelectionSingleton & getSelection (void)
Get a reference to the selection.
static std::string getObjectCmd (const char *Name, const App::Document *doc=0, const char *prefix=0, const char *postfix=0, bool gui=false)
returns a python command string to retrieve an object from a document
static std::string getObjectCmd (const App::DocumentObject *obj, const char *prefix=0, const char *postfix=0, bool gui=false)
returns a python command string to retrieve the given object
static void openCommand (const char *sName=0)
Open a new Undo transaction on the active document.
static void commitCommand (void)
Commit the Undo transaction on the active document.
static void abortCommand (void)
Abort the Undo transaction on the active document.
static bool hasPendingCommand (void)
Check if an Undo transaction is open on the active document.
static void updateActive (void)
Updates the (active) document (propagate changes)
static void updateAll (std::list< Gui::Document * > cList)
Updates the (all or listed) documents (propagate changes)
static bool isActiveObjectValid (void)
Checks if the active object of the active document is valid.
static void blockCommand (bool)
Blocks all command objects.
static void printPyCaller ()
Print to Python console the current Python calling source file and line number.
static void printCaller (const char *file, int line)
Print to Python console the current calling source file and line number.
static void addModule (DoCmd_Type eType, const char *sModuleName)
import an external (or own) module only once
static std::string getPythonTuple (const std::string &name, const std::vector< std::string > &subnames)
Get Python tuple from object and sub-elements.
Protected Types inherited from Gui::Command
enum CmdType {
AlterDoc = 1, Alter3DView = 2, AlterSelection = 4, ForEdit = 8,
NoTransaction = 16
}
Protected Attributes inherited from Gui::Command
const char * sAppModule
const char * sGroup
const char * sName
const char * sHelpUrl
int eType
bool bCanLog
Indicate if the command shall log to MacroManager.
Protected Attributes inherited from Gui::CommandBase
const char * sMenuText
const char * sToolTipText
const char * sWhatsThis
const char * sStatusTip
const char * sPixmap
const char * sAccel
std::string displayText
Detailed Description
The Python command class This is a special type of command class.
It's used to bind a Python command class into the FreeCAD command framework. An object of this class gets a reference to the Python command object and manages all the passing between the C++ and the Python world. This includes everything like setting resources such as bitmaps, activation or bindings to the user interface.
See also
CommandManager
Author
Jrgen Riegel
Constructor & Destructor Documentation
PythonCommand()
PythonCommand::PythonCommand (const char * name, PyObject * pcPyCommand, const char * pActivationString)
References Base::InterpreterSingleton::runMethodObject().
~PythonCommand()
PythonCommand::~PythonCommand () virtual
References Gui::Command::sName.
Member Function Documentation
activated()
void PythonCommand::activated (int iMsg) protected virtual
Method which gets called when activated.
Implements Gui::Command.
References Activation, Base::Console(), Gui::Command::Doc, Base::ConsoleSingleton::Error(), isCheckable(), Base::InterpreterSingleton::runMethod(), Base::InterpreterSingleton::runMethodVoid(), and Gui::Command::sName.
className()
const char* Gui::PythonCommand::className () const virtual
The C++ class name is needed as context for the translation framework.
Implements Gui::CommandBase.
createAction()
Action * PythonCommand::createAction (void) protected virtual
Creates the used Action.
Reimplemented from Gui::Command.
References Gui::Command::applyCommandData(), Gui::BitmapFactory(), Base::Console(), Base::ConsoleSingleton::Error(), getAccel(), Gui::getMainWindow(), Gui::Command::getName(), getResource(), isCheckable(), isChecked(), Gui::Action::setCheckable(), Gui::Action::setChecked(), Gui::Action::setIcon(), and Gui::Action::setShortcut().
getAccel()
const char * PythonCommand::getAccel () const virtual
Reimplemented from Gui::CommandBase.
References getResource().
Referenced by createAction().
getHelpUrl()
const char * PythonCommand::getHelpUrl (void) const protected virtual
Get the help URL.
Reimplemented from Gui::Command.
References Base::InterpreterSingleton::runMethodObject().
getMenuText()
const char * PythonCommand::getMenuText () const virtual
Reimplemented from Gui::CommandBase.
References getResource().
getPixmap()
const char * PythonCommand::getPixmap () const virtual
Reimplemented from Gui::CommandBase.
References getResource().
getResource()
const char * PythonCommand::getResource (const char * sName) const protected
Returns the resource values.
References Gui::Command::sName.
Referenced by createAction(), Gui::PythonGroupCommand::createAction(), getAccel(), Gui::PythonGroupCommand::getAccel(), getMenuText(), Gui::PythonGroupCommand::getMenuText(), getPixmap(), Gui::PythonGroupCommand::getPixmap(), getStatusTip(), Gui::PythonGroupCommand::getStatusTip(), getToolTipText(), Gui::PythonGroupCommand::getToolTipText(), getWhatsThis(), Gui::PythonGroupCommand::getWhatsThis(), and Gui::PythonGroupCommand::PythonGroupCommand().
getStatusTip()
const char * PythonCommand::getStatusTip () const virtual
Reimplemented from Gui::CommandBase.
References getResource().
getToolTipText()
const char * PythonCommand::getToolTipText () const virtual
Reimplemented from Gui::CommandBase.
References getResource().
getWhatsThis()
const char * PythonCommand::getWhatsThis () const virtual
Reimplemented from Gui::CommandBase.
References Gui::Command::getName(), and getResource().
isActive()
bool PythonCommand::isActive (void) protected virtual
if the command is not always active
Reimplemented from Gui::Command.
isCheckable()
bool PythonCommand::isCheckable () const
Referenced by activated(), createAction(), and Gui::PythonGroupCommand::createAction().
isChecked()
bool PythonCommand::isChecked () const
Referenced by createAction(), and Gui::PythonGroupCommand::createAction().
languageChange()
void PythonCommand::languageChange () virtual
Reassigns QAction stuff after the language has changed.
Reimplemented from Gui::Command.
References Gui::Command::applyCommandData(), and Gui::Command::getName().
Referenced by Gui::PythonGroupCommand::createAction().
Member Data Documentation
Activation
std::string Gui::PythonCommand::Activation protected
the activation sequence
Referenced by activated().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Command.h
Sources/FreeCAD/src/Gui/Command.cpp