FreeCAD: Gui::Dialog::DlgCustomizeImp Class Reference
Gui::Dialog::DlgCustomizeImp Class Reference
Dialog which contains several tab pages to customize the changeable toolbars and commandbars or to define own macro actions.
#include <DlgCustomizeImp.h>
Signals
void addMacroAction (const QByteArray &)
void modifyMacroAction (const QByteArray &)
void removeMacroAction (const QByteArray &)
Public Member Functions
void addPage (QWidget *w)
Inserts a new tab page with its caption.
DlgCustomizeImp (QWidget *parent=0, Qt::WindowFlags fl=Qt::WindowFlags())
Constructs a DlgCustomizeImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
~DlgCustomizeImp ()
Destroys the object and frees any allocated resources.
Static Public Member Functions
static void addPage (const char *className)
Adds a customize page with its class name className.
Protected Member Functions
void changeEvent (QEvent *e)
Detailed Description
Dialog which contains several tab pages to customize the changeable toolbars and commandbars or to define own macro actions.
You can extend the existing toolbars or commandbars with several commands just by drag and drop.
See also
DlgCustomCommandsImp
DlgCustomToolbarsImp
DlgCustomCmdbarsImp
DlgCustomActionsImp
Author
Werner Mayer
Constructor & Destructor Documentation
DlgCustomizeImp()
DlgCustomizeImp::DlgCustomizeImp (QWidget * parent = 0, Qt::WindowFlags fl = Qt::WindowFlags())
Constructs a DlgCustomizeImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
References addPage(), draftgeoutils.intersections::connect(), Gui::getMainWindow(), Gui::GetWidgetFactorySupplier(), and Gui::WidgetFactory().
~DlgCustomizeImp()
DlgCustomizeImp::~DlgCustomizeImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
addMacroAction
void Gui::Dialog::DlgCustomizeImp::addMacroAction (const QByteArray &) signal
addPage() [1/2]
void DlgCustomizeImp::addPage (const char * className) static
Adds a customize page with its class name className.
To create this page it must be registered in the WidgetFactory.
See also
WidgetFactory
CustomPageProducer
Referenced by Gui::CustomPageProducer< CLASS >::CustomPageProducer(), and DlgCustomizeImp().
addPage() [2/2]
void DlgCustomizeImp::addPage (QWidget * w)
Inserts a new tab page with its caption.
changeEvent()
void DlgCustomizeImp::changeEvent (QEvent * e) protected
modifyMacroAction
void Gui::Dialog::DlgCustomizeImp::modifyMacroAction (const QByteArray &) signal
removeMacroAction
void Gui::Dialog::DlgCustomizeImp::removeMacroAction (const QByteArray &) signal
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgCustomizeImp.h
Sources/FreeCAD/src/Gui/DlgCustomizeImp.cpp