FreeCAD: App::PropertyXLinkSub Class Reference
App::PropertyXLinkSub Class Reference
Link to one or more (sub)object from the same or different document.
#include <PropertyLinks.h>
Public Member Functions
virtual const char * getEditorName (void) const override
Get the class name of the associated property editor item.
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
PropertyXLinkSub (bool allowPartial=false, PropertyLinkBase *parent=nullptr)
virtual bool upgrade (Base::XMLReader &reader, const char *typeName) override
virtual ~PropertyXLinkSub ()
Public Member Functions inherited from App::PropertyXLink
virtual bool adjustLink (const std::set< App::DocumentObject * > &inList) override
Called to adjust the link to avoid potential cyclic dependency.
virtual void afterRestore () override
Called at the beginning of Document::afterRestore()
virtual int checkRestore (std::string *msg=nullptr) const override
Test if the link is restored unchanged.
virtual Property * Copy (void) const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
virtual Property * CopyOnImportExternal (const std::map< std::string, std::string > &nameMap) const override
Return a copy of the property if any changes caused by importing external object.
virtual Property * CopyOnLabelChange (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const override
Update object label reference in this property.
virtual Property * CopyOnLinkReplace (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const override
Return a copy of the property if the link replacement affects this property.
App::Document * getDocument () const
const char * getDocumentPath () const
const char * getFilePath () const
virtual void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=nullptr, bool newStyle=true) const override
Obtain the linked objects.
const char * getObjectName () const
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
const std::vector< ShadowSub > & getShadowSubs () const
const char * getSubName (bool newStyle=true) const
std::vector< std::string > getSubValues (bool newStyle) const
const std::vector< std::string > & getSubValues (void) const
std::vector< std::string > getSubValuesStartsWith (const char *, bool newStyle=false) const
bool hasSubName () const
virtual void onContainerRestored () override
Called before calling DocumentObject::onDocumentRestored()
PropertyLinkBase * parent () const
virtual void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
PropertyXLink (bool allowPartial=false, PropertyLinkBase *parent=nullptr)
virtual bool referenceChanged () const override
Test if the element reference has changed after restore.
virtual void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
virtual void setAllowPartial (bool enable) override
virtual void setPyObject (PyObject *) override
void setSubName (const char *subname)
void setSubValues (std::vector< std::string > &&SubList, std::vector< ShadowSub > &&ShadowSubList={})
void setSyncSubObject (bool enable)
void setValue (App::DocumentObject *) override
Sets the property.
void setValue (App::DocumentObject *, const char *subname)
void setValue (App::DocumentObject *, const std::vector< std::string > &SubList, std::vector< ShadowSub > &&ShadowSubList={})
void setValue (App::DocumentObject *, std::vector< std::string > &&SubList, std::vector< ShadowSub > &&ShadowSubList={})
void setValue (std::string &&filePath, std::string &&objectName, std::vector< std::string > &&SubList, std::vector< ShadowSub > &&ShadowSubList={})
virtual void updateElementReference (DocumentObject *feature, bool reverse=false, bool notify=false) override
Link type property interface APIs These APIs are moved here so that any type of property can have the property link behavior, e.g.
virtual bool upgrade (Base::XMLReader &reader, const char *typeName)
virtual ~PropertyXLink ()
Public Member Functions inherited from App::PropertyLinkGlobal
PropertyLinkGlobal ()
Public Member Functions inherited from App::PropertyLink
virtual bool adjustLink (const std::set< App::DocumentObject * > &inList) override
Called to adjust the link to avoid potential cyclic dependency.
virtual void breakLink (App::DocumentObject *obj, bool clear) override
Called to reset this link property.
virtual Property * Copy (void) const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
virtual Property * CopyOnLinkReplace (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const override
Return a copy of the property if the link replacement affects this property.
virtual const char * getEditorName (void) const override
Get the class name of the associated property editor item.
virtual void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=nullptr, bool newStyle=true) const override
Obtain the linked objects.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
App::DocumentObject * getValue (Base::Type t) const
Returns the link type checked.
App::DocumentObject * getValue (void) const
This method returns the linked DocumentObject.
template<typename _type >
_type getValue (void) const
Returns the link type checked.
virtual void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
PropertyLink ()
A constructor.
void resetLink ()
virtual void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
virtual void setPyObject (PyObject *) override
virtual void setValue (App::DocumentObject *)
Sets the property.
virtual ~PropertyLink ()
A destructor.
Public Member Functions inherited from App::PropertyLinkBase
virtual bool adjustLink (const std::set< App::DocumentObject * > &inList)=0
Called to adjust the link to avoid potential cyclic dependency.
virtual void breakLink (App::DocumentObject *obj, bool clear)=0
Called to reset this link property.
void checkLabelReferences (const std::vector< std::string > &subs, bool reset=true)
Check subnames for label registration.
virtual int checkRestore (std::string *msg=nullptr) const
Test if the link is restored unchanged.
virtual Property * CopyOnImportExternal (const std::map< std::string, std::string > &nameMap) const
Return a copy of the property if any changes caused by importing external linked object.
virtual Property * CopyOnLabelChange (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const
Update object label reference in this property.
virtual Property * CopyOnLinkReplace (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const =0
Return a copy of the property if the link replacement affects this property.
void getLinkedElements (std::map< App::DocumentObject *, std::vector< std::string > > &elements, bool newStyle=true, bool all=true) const
Helper function to return a map of linked object and its subname references.
template<class T >
void getLinkedObjects (T &inserter, bool all=false) const
Helper function to return linked objects using an std::inserter.
virtual void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=nullptr, bool newStyle=true) const =0
Obtain the linked objects.
virtual bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
std::map< App::DocumentObject *, std::vector< std::string > > linkedElements (bool newStyle=true, bool all=true) const
Helper function to return a map of linked object and its subname references.
std::vector< App::DocumentObject * > linkedObjects (bool all=false) const
Helper function to return all linked objects of this property.
PropertyLinkBase ()
virtual bool referenceChanged () const
Test if the element reference has changed after restore.
void registerLabelReferences (std::vector< std::string > &&labels, bool reset=true)
Register label reference for future object relabel update.
void setAllowExternal (bool allow)
Enable/disable temporary holding external object without throwing exception.
virtual void setAllowPartial (bool enable)
bool testFlag (int flag) const
void unregisterElementReference ()
Clear internal element reference registration.
void unregisterLabelReferences ()
Clear internal label references registration.
virtual void updateElementReference (App::DocumentObject *feature, bool reverse=false, bool notify=false)
Link type property interface APIs These APIs are moved here so that any type of property can have the property link behavior, e.g.
virtual ~PropertyLinkBase ()
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual Property * Copy (void) const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
int64_t getID () const
Return a unique ID for the property.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const char * getName (void) const
Get the name of this property in the belonging container With hasName() it can be checked beforehand if a valid name is set.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
bool hasName () const
Check if the property has a name set.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::ScopedLink
LinkScope getScope () const
Get the links scope Retrieve what kind of links are allowed.
void setScope (LinkScope scope)
Set the links scope Allows to define what kind of links are allowed.
Additional Inherited Members
Public Types inherited from App::PropertyLinkBase
enum LinkFlags {
LinkAllowExternal , LinkDetached , LinkRestoring , LinkAllowPartial ,
LinkRestoreLabel , LinkSyncSubObject
}
typedef std::pair< std::string, std::string > ShadowSub
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , Busy = 15 ,
CopyOnChange = 16 , UserEdit = 17 , PropStaticBegin = 21 , PropDynamic = 21 ,
PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 , PropTransient = 25 ,
PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 , User1 = 28 ,
User2 = 29 , User3 = 30 , User4 = 31
}
Static Public Member Functions inherited from App::PropertyXLink
static std::map< App::Document *, std::set< App::Document * > > getDocumentInList (App::Document *doc=nullptr)
static std::map< App::Document *, std::set< App::Document * > > getDocumentOutList (App::Document *doc=nullptr)
static bool hasXLink (const App::Document *doc)
static bool hasXLink (const std::vector< App::DocumentObject * > &objs, std::vector< App::Document * > *unsaved=nullptr)
static void restoreDocument (const App::Document &doc)
static bool supportXLink (const App::Property *prop)
Static Public Member Functions inherited from App::PropertyLinkBase
static void breakLinks (App::DocumentObject *link, const std::vector< App::DocumentObject * > &objs, bool clear)
Helper function for breaking link properties.
static const char * exportSubName (std::string &output, const App::DocumentObject *obj, const char *subname, bool first_obj=false)
Helper function to export a subname reference.
static void getLabelReferences (std::vector< std::string > &labels, const char *subname)
Helper function to extract labels from a subname reference.
static std::string importSubName (Base::XMLReader &reader, const char *sub, bool &restoreLabel)
Helper function to import a subname reference.
static void restoreLabelReference (const App::DocumentObject *obj, std::string &sub, ShadowSub *shadow=nullptr)
Helper function to restore label references during import.
static App::DocumentObject * tryImport (const App::Document *doc, const App::DocumentObject *obj, const std::map< std::string, std::string > &nameMap)
Helper function for link import operation.
static std::string tryImportSubName (const App::DocumentObject *obj, const char *sub, const App::Document *doc, const std::map< std::string, std::string > &nameMap)
Helper function for link import operation.
static std::pair< App::DocumentObject *, std::string > tryReplaceLink (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const char *sub=nullptr)
Helper functions.
static std::pair< App::DocumentObject *, std::vector< std::string > > tryReplaceLinkSubs (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const std::vector< std::string > &subs)
Helper function to check and replace a link with multiple subname references.
static void updateElementReferences (DocumentObject *feature, bool reverse=false)
Update all element references in all link properties of feature.
static std::string updateLabelReference (const App::DocumentObject *linked, const char *subname, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
Helper function to update subname reference on label change.
static std::vector< std::pair< Property *, std::unique_ptr< Property > > > updateLabelReferences (App::DocumentObject *obj, const char *newLabel)
Helper function to collect changed property when an object re-label.
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Check if the passed name is valid.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::PropertyXLink
virtual void aboutToSetValue () override
Gets called by all setValue() methods before the value has changed.
void copyTo (PropertyXLink &other, App::DocumentObject *linked=nullptr, std::vector< std::string > *subs=nullptr) const
void detach ()
virtual void hasSetValue () override
Gets called by all setValue() methods after the value has changed.
void restoreLink (App::DocumentObject *)
void unlink ()
Protected Member Functions inherited from App::PropertyLinkBase
virtual void hasSetValue () override
Gets called by all setValue() methods after the value has changed.
void setFlag (int flag, bool value=true)
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::PropertyXLink
DocInfoPtr docInfo
std::string docName
std::string filePath
std::string objectName
PropertyLinkBase * parentProp
std::string stamp
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Detailed Description
Link to one or more (sub)object from the same or different document.
Constructor & Destructor Documentation
PropertyXLinkSub()
PropertyXLinkSub::PropertyXLinkSub (bool allowPartial = false, PropertyLinkBase * parent = nullptr)
~PropertyXLinkSub()
PropertyXLinkSub::~PropertyXLinkSub () virtual
Member Function Documentation
getEditorName()
virtual const char * App::PropertyXLinkSub::getEditorName (void) const override virtual
Get the class name of the associated property editor item.
Reimplemented from App::PropertyLink.
getPyObject()
PyObject * PropertyXLinkSub::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from App::PropertyXLink.
References App::PropertyString::getPyObject(), App::PropertyXLink::getSubValues(), and App::PropertyString::setValue().
upgrade()
bool PropertyXLinkSub::upgrade (Base::XMLReader & reader, const char * typeName) override virtual
Reimplemented from App::PropertyXLink.
References Base::Persistence::getClassTypeId(), App::Property::getContainer(), App::Property::getName(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), App::PropertyLinkSub::Restore(), App::Property::setContainer(), App::PropertyXLink::setValue(), and App::PropertyXLink::upgrade().
The documentation for this class was generated from the following files:
FreeCAD/src/App/PropertyLinks.h
FreeCAD/src/App/PropertyLinks.cpp