FreeCAD: Ui_TaskEdge2TracParameter Class Reference
Ui_TaskEdge2TracParameter Class Reference
#include <ui_TaskEdge2TracParameter.h>
Public Member Functions
void retranslateUi (QWidget *TaskEdge2TracParameter)
void setupUi (QWidget *TaskEdge2TracParameter)
Public Attributes
QCheckBox * checkBoxOrientation
QDoubleSpinBox * doubleSpinBoxSizing
QHBoxLayout * horizontalLayout
QHBoxLayout * horizontalLayout_2
QHBoxLayout * horizontalLayout_3
QLabel * label_2
QLabel * label_Cluster
QLabel * label_Edges
QLineEdit * lineEdit_ObjectName
QPushButton * pushButton_HideShow
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void Ui_TaskEdge2TracParameter::retranslateUi (QWidget * TaskEdge2TracParameter)
References checkBoxOrientation, doubleSpinBoxSizing, label_2, label_Cluster, label_Edges, pushButton_HideShow, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Ui_TaskEdge2TracParameter::setupUi (QWidget * TaskEdge2TracParameter)
References checkBoxOrientation, doubleSpinBoxSizing, horizontalLayout, horizontalLayout_2, horizontalLayout_3, label_2, label_Cluster, label_Edges, lineEdit_ObjectName, pushButton_HideShow, retranslateUi(), and verticalLayout.
Referenced by RobotGui::TaskEdge2TracParameter::TaskEdge2TracParameter().
Member Data Documentation
checkBoxOrientation
QCheckBox* Ui_TaskEdge2TracParameter::checkBoxOrientation
Referenced by retranslateUi(), setupUi(), and RobotGui::TaskEdge2TracParameter::TaskEdge2TracParameter().
doubleSpinBoxSizing
QDoubleSpinBox* Ui_TaskEdge2TracParameter::doubleSpinBoxSizing
Referenced by retranslateUi(), setupUi(), and RobotGui::TaskEdge2TracParameter::TaskEdge2TracParameter().
horizontalLayout
QHBoxLayout* Ui_TaskEdge2TracParameter::horizontalLayout
Referenced by setupUi().
horizontalLayout_2
QHBoxLayout* Ui_TaskEdge2TracParameter::horizontalLayout_2
Referenced by setupUi().
horizontalLayout_3
QHBoxLayout* Ui_TaskEdge2TracParameter::horizontalLayout_3
Referenced by setupUi().
label_2
QLabel* Ui_TaskEdge2TracParameter::label_2
Referenced by retranslateUi(), and setupUi().
label_Cluster
QLabel* Ui_TaskEdge2TracParameter::label_Cluster
Referenced by retranslateUi(), RobotGui::TaskEdge2TracParameter::setEdgeAndClusterNbr(), and setupUi().
label_Edges
QLabel* Ui_TaskEdge2TracParameter::label_Edges
Referenced by retranslateUi(), RobotGui::TaskEdge2TracParameter::setEdgeAndClusterNbr(), and setupUi().
lineEdit_ObjectName
QLineEdit* Ui_TaskEdge2TracParameter::lineEdit_ObjectName
Referenced by RobotGui::TaskEdge2TracParameter::setHideShowObject(), and setupUi().
pushButton_HideShow
QPushButton* Ui_TaskEdge2TracParameter::pushButton_HideShow
Referenced by retranslateUi(), setupUi(), and RobotGui::TaskEdge2TracParameter::TaskEdge2TracParameter().
verticalLayout
QVBoxLayout* Ui_TaskEdge2TracParameter::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Robot/Gui/ui_TaskEdge2TracParameter.h