FreeCAD: Part::GeomConic Class Reference
Part::GeomConic Class Reference abstract
#include <Geometry.h>
Public Member Functions
virtual Geometry * copy (void) const =0
returns a copy of this object having a new randomly generated tag.
double getAngleXU (void) const
GeomConic::getAngleXU.
Base::Vector3d getCenter (void) const
getCenter
Base::Vector3d getLocation (void) const
virtual unsigned int getMemSize (void) const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual PyObject * getPyObject (void)=0
This method returns the Python wrapper for a C++ object.
const Handle (Geom_Geometry) &handle() const =0
bool isReversed () const
GeomConic::isReversed tests if an ellipse that lies in XY plane is reversed (i.e. drawn from startpoint to endpoint in CW direction instead of CCW.)
void setAngleXU (double angle)
GeomConic::setAngleXU complements getAngleXU.
void setCenter (const Base::Vector3d &Center)
setCenter
void setLocation (const Base::Vector3d &Center)
virtual ~GeomConic ()
Public Member Functions inherited from Part::GeomCurve
bool closestParameter (const Base::Vector3d &point, double &u) const
bool closestParameterToBasisCurve (const Base::Vector3d &point, double &u) const
double curvatureAt (double u) const
Base::Vector3d firstDerivativeAtParameter (double u) const
GeomCurve ()
double getFirstParameter () const
double getLastParameter () const
bool intersect (GeomCurve *c, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion()) const
double length (double u, double v) const
bool normalAt (double u, Base::Vector3d &dir) const
Base::Vector3d pointAtParameter (double u) const
void reverse (void)
Base::Vector3d secondDerivativeAtParameter (double u) const
bool tangent (double u, Base::Vector3d &dir) const
bool tangent (double u, gp_Dir &) const
GeomBSplineCurve * toBSpline (double first, double last) const
toBSpline Converts the curve to a B-spline
virtual GeomBSplineCurve * toNurbs (double first, double last) const
TopoDS_Shape toShape () const
virtual ~GeomCurve ()
Public Member Functions inherited from Part::Geometry
Geometry * clone (void) const
returns a cloned object.
void deleteExtension (Base::Type type)
void deleteExtension (std::string name)
std::weak_ptr< GeometryExtension > getExtension (Base::Type type)
std::weak_ptr< const GeometryExtension > getExtension (Base::Type type) const
std::weak_ptr< GeometryExtension > getExtension (std::string name)
std::weak_ptr< const GeometryExtension > getExtension (std::string name) const
std::vector< std::weak_ptr< const GeometryExtension > > getExtensions () const
boost::uuids::uuid getTag () const
returns the tag of the geometry object
bool hasExtension (Base::Type type) const
bool hasExtension (std::string name) const
void mirror (const Base::Vector3d &point)
void mirror (const Base::Vector3d &point, const Base::Vector3d &dir)
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
void rotate (const Base::Placement &plm)
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
void scale (const Base::Vector3d &vec, double scale)
void setExtension (std::unique_ptr< GeometryExtension > &&geo)
void transform (const Base::Matrix4D &mat)
void translate (const Base::Vector3d &vec)
virtual ~Geometry ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Member Functions
GeomConic ()
Protected Member Functions inherited from Part::Geometry
void assignTag (const Part::Geometry *)
copies the tag from the geometry passed as a parameter to this object
void copyNonTag (const Part::Geometry *)
void createNewTag ()
create a new tag for the geometry object
Geometry ()
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Protected Member Functions inherited from Part::GeomCurve
static bool intersect (const Handle(Geom_Curve) c, const Handle(Geom_Curve) c2, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion())
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Part::Geometry
std::vector< std::shared_ptr< GeometryExtension > > extensions
boost::uuids::uuid tag
Constructor & Destructor Documentation
GeomConic()
GeomConic::GeomConic () protected
~GeomConic()
GeomConic::~GeomConic () virtual
Member Function Documentation
copy()
virtual Geometry* Part::GeomConic::copy (void) const pure virtual
returns a copy of this object having a new randomly generated tag.
If you also want to copy the tag, you may use clone() instead. For creation of geometry with other handles, with or without the same tag, you may use the constructors and the sethandle functions. The tag of a geometry can be copied to another geometry using the assignTag function.
Implements Part::Geometry.
Implemented in Part::GeomParabola, Part::GeomHyperbola, Part::GeomEllipse, and Part::GeomCircle.
getAngleXU()
double GeomConic::getAngleXU (void) const
GeomConic::getAngleXU.
Returns
The angle between ellipse's major axis (in direction to focus1) and X axis of a default axis system in the plane of ellipse. The angle is counted CCW as seen when looking at the ellipse so that ellipse's axis is pointing at you. Note that this function may give unexpected results when the ellipse is in XY, but reversed, because the X axis of the default axis system is reversed compared to the global X axis. This angle, in conjunction with ellipse's axis, fully defines the orientation of the ellipse.
References Handle().
getCenter()
Base::Vector3d GeomConic::getCenter (void) const
getCenter
References Handle().
Referenced by Sketcher::Sketch::addCircle(), Sketcher::SketchObject::addCopy(), Sketcher::Sketch::addEllipse(), Sketcher::SketchObject::addSymmetric(), and SketcherGui::ViewProviderSketch::draw().
getLocation()
Base::Vector3d GeomConic::getLocation (void) const
References Handle().
getMemSize()
virtual unsigned int Part::GeomConic::getMemSize (void) const pure virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Part::Geometry.
Implemented in Part::GeomParabola, Part::GeomHyperbola, Part::GeomEllipse, and Part::GeomCircle.
getPyObject()
virtual PyObject* Part::GeomConic::getPyObject (void) pure virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Implemented in Part::GeomParabola, Part::GeomHyperbola, Part::GeomEllipse, and Part::GeomCircle.
Handle()
const Part::GeomConic::Handle (Geom_Geometry) const & pure virtual
Implements Part::Geometry.
Implemented in Part::GeomParabola, Part::GeomHyperbola, Part::GeomEllipse, and Part::GeomCircle.
Referenced by getAngleXU(), getCenter(), getLocation(), isReversed(), setAngleXU(), setCenter(), and setLocation().
isReversed()
bool GeomConic::isReversed () const
GeomConic::isReversed tests if an ellipse that lies in XY plane is reversed (i.e. drawn from startpoint to endpoint in CW direction instead of CCW.)
Returns
Returns True if the arc is CW and false if CCW.
References Handle().
setAngleXU()
void GeomConic::setAngleXU (double angle)
GeomConic::setAngleXU complements getAngleXU.
Parameters
angle
References Handle().
Referenced by Sketcher::SketchObject::rebuildExternalGeometry(), and Part::ConicPy::setAngleXU().
setCenter()
void GeomConic::setCenter (const Base::Vector3d & Center)
setCenter
References Handle(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by Sketcher::SketchObject::addCopy(), Sketcher::SketchObject::addSymmetric(), Sketcher::SketchObject::exposeInternalGeometry(), and Sketcher::SketchObject::rebuildExternalGeometry().
setLocation()
void GeomConic::setLocation (const Base::Vector3d & Center)
References Handle(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by Part::ConicPy::setCenter(), and Part::ConicPy::setLocation().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/App/Geometry.h
Sources/FreeCAD/src/Mod/Part/App/Geometry.cpp