FreeCAD: Mod.Show.mTempoVis Namespace Reference
Mod.Show.mTempoVis Namespace Reference
Classes
class JUST_SAVE
class MAINSTACK
class TempoVis
Variables
Err = lambda msg: App.Console.PrintError(msg + "\n")
Log = lambda msg: App.Console.PrintLog(msg + "\n")
int S_ACTIVE = 1
int S_EMPTY = 0
int S_INTERNAL = 3
int S_RESTORED = 2
Wrn = lambda msg: App.Console.PrintWarning(msg + "\n")
Variable Documentation
Err
Mod.Show.mTempoVis.Err = lambda msg: App.Console.PrintError(msg + "\n")
Referenced by Mod.Show.mTempoVis.TempoVis.restore(), and Mod.Show.mTempoVis.TempoVis.restoreVPProperty().
Log
Mod.Show.mTempoVis.Log = lambda msg: App.Console.PrintLog(msg + "\n")
S_ACTIVE
int Mod.Show.mTempoVis.S_ACTIVE = 1
S_EMPTY
int Mod.Show.mTempoVis.S_EMPTY = 0
S_INTERNAL
int Mod.Show.mTempoVis.S_INTERNAL = 3
S_RESTORED
int Mod.Show.mTempoVis.S_RESTORED = 2
Wrn
Mod.Show.mTempoVis.Wrn = lambda msg: App.Console.PrintWarning(msg + "\n")
Referenced by Mod.Show.mTempoVis.TempoVis.activateWorkbench(), and Mod.Show.mTempoVis.TempoVis.modifyVPProperty().