FreeCAD: SurfaceGui::FillingVertexPanel Class Reference
SurfaceGui::FillingVertexPanel Class Reference
#include <TaskFillingVertex.h>
Classes
class VertexSelection
Public Member Functions
void checkOpenCommand ()
FillingVertexPanel (ViewProviderFilling *vp, Surface::Filling *obj)
void open ()
void reject ()
void setEditedObject (Surface::Filling *obj)
~FillingVertexPanel ()
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockConnection (bool block)
void detachSelection ()
Detaches from the selection.
bool isConnectionAttached () const
bool isConnectionBlocked () const
SelectionObserver (bool attach=true, int resolve=1)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, int resolve=1)
Constructor.
virtual ~SelectionObserver ()
Public Member Functions inherited from Gui::DocumentObserver
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
virtual ~DocumentObserver ()
Protected Types
enum SelectionMode { , AppendVertex, RemoveVertex }
Protected Member Functions
void changeEvent (QEvent *e)
virtual void onSelectionChanged (const Gui::SelectionChanges &msg)
virtual void slotDeletedObject (const Gui::ViewProviderDocumentObject &Obj)
Notifies when the object is about to be removed.
virtual void slotRedoDocument (const Gui::Document &Doc)
Notifies on redo.
virtual void slotUndoDocument (const Gui::Document &Doc)
Notifies on undo.
Protected Attributes
bool checkCommand
Surface::Filling * editedObject
SelectionMode selectionMode
Member Enumeration Documentation
SelectionMode
enum SurfaceGui::FillingVertexPanel::SelectionMode protected
Enumerator
AppendVertex
RemoveVertex
Constructor & Destructor Documentation
FillingVertexPanel()
SurfaceGui::FillingVertexPanel::FillingVertexPanel (ViewProviderFilling * vp, Surface::Filling * obj)
References checkCommand, draftgeoutils.intersections::connect(), selectionMode, and setEditedObject().
~FillingVertexPanel()
SurfaceGui::FillingVertexPanel::~FillingVertexPanel ()
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
changeEvent()
void SurfaceGui::FillingVertexPanel::changeEvent (QEvent * e) protected
checkOpenCommand()
void SurfaceGui::FillingVertexPanel::checkOpenCommand ()
References checkCommand, editedObject, App::PropertyString::getValue(), Gui::Command::hasPendingCommand(), App::DocumentObject::Label, and Gui::Command::openCommand().
Referenced by onSelectionChanged(), and open().
onSelectionChanged()
void SurfaceGui::FillingVertexPanel::onSelectionChanged (const Gui::SelectionChanges & msg) protected virtual
Implements Gui::SelectionObserver.
References Gui::SelectionChanges::AddSelection, AppendVertex, checkOpenCommand(), editedObject, Gui::SelectionObject::getObject(), App::PropertyLinkSubList::getSubListValues(), App::PropertyLinkSubList::getSubValues(), App::PropertyString::getValue(), App::PropertyLinkSubList::getValues(), SurfaceGui::ViewProviderFilling::highlightReferences(), App::DocumentObject::Label, Surface::Filling::Points, App::DocumentObject::recomputeFeature(), RemoveVertex, selectionMode, App::PropertyLinkSubList::setValues(), and SurfaceGui::ViewProviderFilling::Vertex.
open()
void SurfaceGui::FillingVertexPanel::open ()
References checkOpenCommand(), Gui::SelectionSingleton::clearSelection(), editedObject, App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderFilling::highlightReferences(), Surface::Filling::Points, Gui::Selection(), and SurfaceGui::ViewProviderFilling::Vertex.
Referenced by SurfaceGui::TaskFilling::open().
reject()
void SurfaceGui::FillingVertexPanel::reject (void)
References editedObject, App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderFilling::highlightReferences(), Surface::Filling::Points, and SurfaceGui::ViewProviderFilling::Vertex.
Referenced by SurfaceGui::TaskFilling::accept(), and SurfaceGui::TaskFilling::reject().
setEditedObject()
void SurfaceGui::FillingVertexPanel::setEditedObject (Surface::Filling * obj)
References Gui::DocumentObserver::attachDocument(), editedObject, App::DocumentObject::getDocument(), App::PropertyLinkSubList::getSubValues(), App::PropertyLinkSubList::getValues(), Gui::Application::Instance, and Surface::Filling::Points.
Referenced by FillingVertexPanel().
slotDeletedObject()
void SurfaceGui::FillingVertexPanel::slotDeletedObject (const Gui::ViewProviderDocumentObject & Obj) protected virtual
Notifies when the object is about to be removed.
Reimplemented from Gui::DocumentObserver.
References editedObject, App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderFilling::highlightReferences(), Surface::Filling::Points, and SurfaceGui::ViewProviderFilling::Vertex.
slotRedoDocument()
void SurfaceGui::FillingVertexPanel::slotRedoDocument (const Gui::Document & Doc) protected virtual
Notifies on redo.
Reimplemented from Gui::DocumentObserver.
References checkCommand.
slotUndoDocument()
void SurfaceGui::FillingVertexPanel::slotUndoDocument (const Gui::Document & Doc) protected virtual
Notifies on undo.
Reimplemented from Gui::DocumentObserver.
References checkCommand.
Member Data Documentation
checkCommand
bool SurfaceGui::FillingVertexPanel::checkCommand protected
Referenced by checkOpenCommand(), FillingVertexPanel(), slotRedoDocument(), and slotUndoDocument().
editedObject
Surface::Filling* SurfaceGui::FillingVertexPanel::editedObject protected
Referenced by checkOpenCommand(), onSelectionChanged(), open(), reject(), setEditedObject(), and slotDeletedObject().
selectionMode
SelectionMode SurfaceGui::FillingVertexPanel::selectionMode protected
Referenced by FillingVertexPanel(), and onSelectionChanged().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Surface/Gui/TaskFillingVertex.h
Sources/FreeCAD/src/Mod/Surface/Gui/TaskFillingVertex.cpp