FreeCAD: Gui::Dialog::Ui_SceneInspector Class Reference
Gui::Dialog::Ui_SceneInspector Class Reference
#include <ui_SceneInspector.h>
Public Member Functions
void retranslateUi (QDialog *Gui__Dialog__SceneInspector)
void setupUi (QDialog *Gui__Dialog__SceneInspector)
Public Attributes
QPushButton * closeButton
QGridLayout * gridLayout
QHBoxLayout * horizontalLayout
QPushButton * refreshButton
QSpacerItem * spacerItem
QTreeView * treeView
Member Function Documentation
retranslateUi()
void Gui::Dialog::Ui_SceneInspector::retranslateUi (QDialog * Gui__Dialog__SceneInspector)
References closeButton, refreshButton, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), Gui::Dialog::DlgInspector::changeEvent(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::Dialog::Ui_SceneInspector::setupUi (QDialog * Gui__Dialog__SceneInspector)
References closeButton, draftgeoutils.intersections::connect(), gridLayout, horizontalLayout, refreshButton, retranslateUi(), spacerItem, and treeView.
Referenced by Gui::Dialog::DlgInspector::DlgInspector().
Member Data Documentation
closeButton
QPushButton* Gui::Dialog::Ui_SceneInspector::closeButton
Referenced by DraftGui.DraftToolBar::checkSpecialChars(), DraftGui.DraftToolBar::editUi(), DraftGui.DraftToolBar::offUi(), retranslateUi(), DraftGui.DraftToolBar::retranslateUi(), setupUi(), and DraftGui.DraftToolBar::wireUi().
gridLayout
QGridLayout* Gui::Dialog::Ui_SceneInspector::gridLayout
Referenced by setupUi().
horizontalLayout
QHBoxLayout* Gui::Dialog::Ui_SceneInspector::horizontalLayout
Referenced by setupUi().
refreshButton
QPushButton* Gui::Dialog::Ui_SceneInspector::refreshButton
Referenced by retranslateUi(), and setupUi().
spacerItem
QSpacerItem* Gui::Dialog::Ui_SceneInspector::spacerItem
Referenced by setupUi().
treeView
QTreeView* Gui::Dialog::Ui_SceneInspector::treeView
Referenced by Gui::Dialog::DlgInspector::DlgInspector(), Gui::Dialog::DlgInspector::setDocument(), Gui::Dialog::DlgInspector::setNode(), Gui::Dialog::DlgInspector::setNodeNames(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_SceneInspector.h