FreeCAD: Sandbox::DocumentThread Class Reference
Sandbox::DocumentThread Class Reference
#include <DocumentThread.h>
Public Member Functions
DocumentThread (QObject *parent=0)
~DocumentThread ()
Protected Member Functions
void run ()
Constructor & Destructor Documentation
DocumentThread()
DocumentThread::DocumentThread (QObject * parent = 0)
~DocumentThread()
DocumentThread::~DocumentThread ()
Member Function Documentation
run()
void DocumentThread::run (void) protected
References Sandbox::DocumentProtector::addObject(), App::Application::getActiveDocument(), App::GetApplication(), and Sandbox::DocumentProtector::recompute().
Referenced by femexamples.examplesgui.FemExamples::clicked(), and femsolver.task.Task::protector().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sandbox/App/DocumentThread.h
FreeCAD/src/Mod/Sandbox/App/DocumentThread.cpp