FreeCAD: MeshGui::SmoothingDialog Class Reference
MeshGui::SmoothingDialog Class Reference
Embed the panel into a dialog.
#include <DlgSmoothing.h>
Public Member Functions
int iterations () const
double lambdaStep () const
DlgSmoothing::Smooth method () const
double microStep () const
SmoothingDialog (QWidget *parent=0, Qt::WindowFlags fl=Qt::WindowFlags())
bool smoothSelection () const
~SmoothingDialog ()
Detailed Description
Embed the panel into a dialog.
Constructor & Destructor Documentation
SmoothingDialog()
SmoothingDialog::SmoothingDialog (QWidget * parent = 0, Qt::WindowFlags fl = Qt::WindowFlags())
References draftgeoutils.intersections::connect().
~SmoothingDialog()
SmoothingDialog::~SmoothingDialog ()
Member Function Documentation
iterations()
int MeshGui::SmoothingDialog::iterations () const
lambdaStep()
double MeshGui::SmoothingDialog::lambdaStep () const
method()
DlgSmoothing::Smooth MeshGui::SmoothingDialog::method () const
Referenced by PathScripts.PathDressupRampEntry.ObjectDressup::execute(), and PathScripts.PathDressupRampEntry.ObjectDressup::generateRamps().
microStep()
double MeshGui::SmoothingDialog::microStep () const
smoothSelection()
bool MeshGui::SmoothingDialog::smoothSelection () const
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/Gui/DlgSmoothing.h
Sources/FreeCAD/src/Mod/Mesh/Gui/DlgSmoothing.cpp