FreeCAD: Gui::SoGLRenderActionElement Class Reference
Gui::SoGLRenderActionElement Class Reference
#include <SoFCInteractiveElement.h>
Public Member Functions
virtual SoElement * copyMatchInfo (void) const
virtual void init (SoState *state)
virtual SbBool matches (const SoElement *element) const
virtual void pop (SoState *state, const SoElement *prevTopElement)
virtual void push (SoState *state)
Static Public Member Functions
static void get (SoState *state, SoGLRenderAction *&action)
static void initClass (void)
static void set (SoState *state, SoGLRenderAction *action)
Protected Member Functions
virtual ~SoGLRenderActionElement ()
Protected Attributes
SoGLRenderAction * glRenderAction
Constructor & Destructor Documentation
~SoGLRenderActionElement()
SoGLRenderActionElement::~SoGLRenderActionElement () protected virtual
Member Function Documentation
copyMatchInfo()
SoElement * SoGLRenderActionElement::copyMatchInfo (void) const virtual
get()
void SoGLRenderActionElement::get (SoState * state, SoGLRenderAction *& action) static
References glRenderAction.
Referenced by draftguitools.gui_trackers.editTracker::move(), and Gui::SoFCSelection::redrawHighlighted().
init()
void SoGLRenderActionElement::init (SoState * state) virtual
References glRenderAction.
Referenced by DocumentObject.DocumentObject::onChanged().
initClass()
void SoGLRenderActionElement::initClass (void) static
Referenced by Gui::SoFCDB::init().
matches()
SbBool SoGLRenderActionElement::matches (const SoElement * element) const virtual
pop()
void SoGLRenderActionElement::pop (SoState * state, const SoElement * prevTopElement) virtual
push()
void SoGLRenderActionElement::push (SoState * state) virtual
set()
void SoGLRenderActionElement::set (SoState * state, SoGLRenderAction * action) static
References glRenderAction.
Referenced by draftguitools.gui_trackers.editTracker::move(), and Gui::View3DInventorViewer::renderScene().
Member Data Documentation
glRenderAction
SoGLRenderAction* Gui::SoGLRenderActionElement::glRenderAction protected
Referenced by get(), init(), and set().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SoFCInteractiveElement.h
Sources/FreeCAD/src/Gui/SoFCInteractiveElement.cpp