FreeCAD: AdaptivePath::ClearedArea Class Reference
AdaptivePath::ClearedArea Class Reference
Public Member Functions
ClearedArea (ClipperLib::cInt p_toolRadiusScaled)
void ExpandCleared (const Path toClearToolPath)
Paths & GetBoundedClearedAreaClipped (const IntPoint &toolPos)
Paths & GetBoundedClearedPaths (const IntPoint &toolPos)
Paths & GetCleared ()
void SetClearedPaths (const Paths &paths)
Constructor & Destructor Documentation
ClearedArea()
AdaptivePath::ClearedArea::ClearedArea (ClipperLib::cInt p_toolRadiusScaled)
Member Function Documentation
ExpandCleared()
void AdaptivePath::ClearedArea::ExpandCleared (const Path toClearToolPath)
References ClipperLib::ClipperOffset::AddPath(), ClipperLib::ClipperBase::AddPaths(), ClipperLib::CleanPolygons(), ClipperLib::ClipperBase::Clear(), ClipperLib::ClipperOffset::Clear(), ClipperLib::Clipper::Execute(), ClipperLib::ClipperOffset::Execute(), AdaptivePath::Perf_ExpandCleared, AdaptivePath::PerfCounter::Start(), and AdaptivePath::PerfCounter::Stop().
GetBoundedClearedAreaClipped()
Paths & AdaptivePath::ClearedArea::GetBoundedClearedAreaClipped (const IntPoint & toolPos)
References ClipperLib::ClipperBase::AddPath(), ClipperLib::ClipperBase::AddPaths(), AdaptivePath::BoundBox::AddPoint(), ClipperLib::ClipperBase::Clear(), AdaptivePath::BoundBox::Contains(), ClipperLib::Clipper::Execute(), AdaptivePath::BoundBox::SetFirstPoint(), ClipperLib::IntPoint::X, and ClipperLib::IntPoint::Y.
GetBoundedClearedPaths()
Paths & AdaptivePath::ClearedArea::GetBoundedClearedPaths (const IntPoint & toolPos)
References AdaptivePath::BoundBox::AddPoint(), AdaptivePath::BoundBox::CollidesWith(), AdaptivePath::BoundBox::Contains(), AdaptivePath::BoundBox::SetFirstPoint(), ClipperLib::IntPoint::X, and ClipperLib::IntPoint::Y.
GetCleared()
Paths & AdaptivePath::ClearedArea::GetCleared ()
SetClearedPaths()
void AdaptivePath::ClearedArea::SetClearedPaths (const Paths & paths)
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Path/libarea/Adaptive.cpp