FreeCAD: WireJoiner::VertexInfo Struct Reference
WireJoiner::VertexInfo Struct Reference
Public Member Functions
bool operator== (const VertexInfo &other) const
const gp_Pnt & pt () const
const gp_Pnt & ptOther () const
VertexInfo (Edges::iterator it, bool start)
Public Attributes
Edges::iterator it
bool start
Constructor & Destructor Documentation
VertexInfo()
WireJoiner::VertexInfo::VertexInfo (Edges::iterator it, bool start)
Member Function Documentation
operator==()
bool WireJoiner::VertexInfo::operator== (const VertexInfo & other) const
References it, and start.
pt()
const gp_Pnt & WireJoiner::VertexInfo::pt () const
Referenced by Commands.SphereCreator::create(), PathScripts.PathGetPoint.TaskPanel::getPoint(), draftviewproviders.view_wire.ViewProviderWire::onChanged(), PathScripts.PathGetPoint.TaskPanel::pointFinish(), and PathScripts.PathGetPoint.TaskPanel::updatePoint().
ptOther()
const gp_Pnt & WireJoiner::VertexInfo::ptOther () const
Member Data Documentation
it
Edges::iterator WireJoiner::VertexInfo::it
Referenced by operator==().
start
bool WireJoiner::VertexInfo::start
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::asString(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::clone(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::hasStart(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::negated(), operator==(), and Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::value().
The documentation for this struct was generated from the following file:
FreeCAD/src/Mod/Path/App/Area.cpp