FreeCAD: SMESHDS_Command Class Reference
SMESHDS_Command Class Reference
#include <SMESHDS_Command.hxx>
Public Member Functions
void Add0DElement (int New0DElementID, int idnode)
void AddBall (int NewBallID, int node, double diameter)
Record adding a Ball.
void AddEdge (int NewEdgeID, int idnode1, int idnode2)
void AddEdge (int NewEdgeID, int n1, int n2, int n12)
void AddFace (int NewFaceID, int idnode1, int idnode2, int idnode3)
void AddFace (int NewFaceID, int idnode1, int idnode2, int idnode3, int idnode4)
void AddFace (int NewFaceID, int n1, int n2, int n3, int n12, int n23, int n31)
void AddFace (int NewFaceID, int n1, int n2, int n3, int n12, int n23, int n31, int nCenter)
void AddFace (int NewFaceID, int n1, int n2, int n3, int n4, int n12, int n23, int n34, int n41)
void AddFace (int NewFaceID, int n1, int n2, int n3, int n4, int n12, int n23, int n34, int n41, int nCenter)
void AddNode (int NewNodeID, double x, double y, double z)
void AddPolygonalFace (const int ElementID, const std::vector< int > &nodes_ids)
void AddPolyhedralVolume (const int ElementID, const std::vector< int > &nodes_ids, const std::vector< int > &quantities)
void AddQuadPolygonalFace (const int ElementID, const std::vector< int > &nodes_ids)
void AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4)
void AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4, int idnode5)
void AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6)
void AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6, int idnode7, int idnode8)
void AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6, int idnode7, int idnode8, int idnode9, int idnode10, int idnode11, int idnode12)
void AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n12, int n23, int n31, int n14, int n24, int n34)
void AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n5, int n12, int n23, int n34, int n41, int n15, int n25, int n35, int n45)
void AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n5, int n6, int n12, int n23, int n31, int n45, int n56, int n64, int n14, int n25, int n36)
void AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n12, int n23, int n34, int n41, int n56, int n67, int n78, int n85, int n15, int n26, int n37, int n48)
void AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n12, int n23, int n34, int n41, int n56, int n67, int n78, int n85, int n15, int n26, int n37, int n48, int n1234, int n1256, int n2367, int n3478, int n1458, int n5678, int nCenter)
void ChangeElementNodes (int ElementID, int nodes[], int nbnodes)
void ChangePolyhedronNodes (const int ElementID, const std::vector< int > &nodes_ids, const std::vector< int > &quantities)
const std::list< double > & GetCoords ()
const std::list< int > & GetIndexes ()
int GetNumber ()
SMESHDS_CommandType GetType ()
void MoveNode (int NewNodeID, double x, double y, double z)
void RemoveElement (int ElementID)
void RemoveNode (int NodeID)
void Renumber (const bool isNodes, const int startID, const int deltaID)
SMESHDS_Command (const SMESHDS_CommandType aType)
~SMESHDS_Command ()
Constructor & Destructor Documentation
SMESHDS_Command()
SMESHDS_Command::SMESHDS_Command (const SMESHDS_CommandType aType)
~SMESHDS_Command()
SMESHDS_Command::~SMESHDS_Command ()
Member Function Documentation
Add0DElement()
void SMESHDS_Command::Add0DElement (int New0DElementID, int idnode)
Referenced by SMESHDS_Script::Add0DElement().
AddBall()
void SMESHDS_Command::AddBall (int NewBallID, int node, double diameter)
Record adding a Ball.
Referenced by SMESHDS_Script::AddBall().
AddEdge() [1/2]
void SMESHDS_Command::AddEdge (int NewEdgeID, int idnode1, int idnode2)
Referenced by SMESHDS_Script::AddEdge().
AddEdge() [2/2]
void SMESHDS_Command::AddEdge (int NewEdgeID, int n1, int n2, int n12)
AddFace() [1/6]
void SMESHDS_Command::AddFace (int NewFaceID, int idnode1, int idnode2, int idnode3)
Referenced by SMESHDS_Script::AddFace().
AddFace() [2/6]
void SMESHDS_Command::AddFace (int NewFaceID, int idnode1, int idnode2, int idnode3, int idnode4)
AddFace() [3/6]
void SMESHDS_Command::AddFace (int NewFaceID, int n1, int n2, int n3, int n12, int n23, int n31)
AddFace() [4/6]
void SMESHDS_Command::AddFace (int NewFaceID, int n1, int n2, int n3, int n12, int n23, int n31, int nCenter)
AddFace() [5/6]
void SMESHDS_Command::AddFace (int NewFaceID, int n1, int n2, int n3, int n4, int n12, int n23, int n34, int n41)
AddFace() [6/6]
void SMESHDS_Command::AddFace (int NewFaceID, int n1, int n2, int n3, int n4, int n12, int n23, int n34, int n41, int nCenter)
AddNode()
void SMESHDS_Command::AddNode (int NewNodeID, double x, double y, double z)
Referenced by SMESHDS_Script::AddNode().
AddPolygonalFace()
void SMESHDS_Command::AddPolygonalFace (const int ElementID, const std::vector< int > & nodes_ids)
Referenced by SMESHDS_Script::AddPolygonalFace().
AddPolyhedralVolume()
void SMESHDS_Command::AddPolyhedralVolume (const int ElementID, const std::vector< int > & nodes_ids, const std::vector< int > & quantities)
Referenced by SMESHDS_Script::AddPolyhedralVolume().
AddQuadPolygonalFace()
void SMESHDS_Command::AddQuadPolygonalFace (const int ElementID, const std::vector< int > & nodes_ids)
Referenced by SMESHDS_Script::AddQuadPolygonalFace().
AddVolume() [1/10]
void SMESHDS_Command::AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4)
Referenced by SMESHDS_Script::AddVolume().
AddVolume() [2/10]
void SMESHDS_Command::AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4, int idnode5)
AddVolume() [3/10]
void SMESHDS_Command::AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6)
AddVolume() [4/10]
void SMESHDS_Command::AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6, int idnode7, int idnode8)
AddVolume() [5/10]
void SMESHDS_Command::AddVolume (int NewVolID, int idnode1, int idnode2, int idnode3, int idnode4, int idnode5, int idnode6, int idnode7, int idnode8, int idnode9, int idnode10, int idnode11, int idnode12)
AddVolume() [6/10]
void SMESHDS_Command::AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n12, int n23, int n31, int n14, int n24, int n34)
AddVolume() [7/10]
void SMESHDS_Command::AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n5, int n12, int n23, int n34, int n41, int n15, int n25, int n35, int n45)
AddVolume() [8/10]
void SMESHDS_Command::AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n5, int n6, int n12, int n23, int n31, int n45, int n56, int n64, int n14, int n25, int n36)
AddVolume() [9/10]
void SMESHDS_Command::AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n12, int n23, int n34, int n41, int n56, int n67, int n78, int n85, int n15, int n26, int n37, int n48)
AddVolume() [10/10]
void SMESHDS_Command::AddVolume (int NewVolID, int n1, int n2, int n3, int n4, int n5, int n6, int n7, int n8, int n12, int n23, int n34, int n41, int n56, int n67, int n78, int n85, int n15, int n26, int n37, int n48, int n1234, int n1256, int n2367, int n3478, int n1458, int n5678, int nCenter)
ChangeElementNodes()
void SMESHDS_Command::ChangeElementNodes (int ElementID, int nodes[], int nbnodes)
Referenced by SMESHDS_Script::ChangeElementNodes().
ChangePolyhedronNodes()
void SMESHDS_Command::ChangePolyhedronNodes (const int ElementID, const std::vector< int > & nodes_ids, const std::vector< int > & quantities)
Referenced by SMESHDS_Script::ChangePolyhedronNodes().
GetCoords()
const list< double > & SMESHDS_Command::GetCoords ()
GetIndexes()
const list< int > & SMESHDS_Command::GetIndexes ()
GetNumber()
int SMESHDS_Command::GetNumber ()
GetType()
SMESHDS_CommandType SMESHDS_Command::GetType ()
MoveNode()
void SMESHDS_Command::MoveNode (int NewNodeID, double x, double y, double z)
Referenced by SMESHDS_Script::MoveNode().
RemoveElement()
void SMESHDS_Command::RemoveElement (int ElementID)
Referenced by SMESHDS_Script::RemoveElement().
RemoveNode()
void SMESHDS_Command::RemoveNode (int NodeID)
Referenced by SMESHDS_Script::RemoveNode().
Renumber()
void SMESHDS_Command::Renumber (const bool isNodes, const int startID, const int deltaID)
Referenced by SMESHDS_Script::Renumber().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESHDS_Command.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESHDS/SMESHDS_Command.cpp