FreeCAD: Gui::TreePanel Class Reference
Gui::TreePanel Class Reference
#include <Tree.h>
Public Member Functions
bool eventFilter (QObject *obj, QEvent *ev)
TreePanel (const char *name, QWidget *parent=nullptr)
virtual ~TreePanel ()
Constructor & Destructor Documentation
TreePanel()
TreePanel::TreePanel (const char * name, QWidget * parent = nullptr)
References draftgeoutils.intersections::connect(), Gui::ExpressionParameter::instance(), Gui::TreeParams::Instance(), and Gui::ExpressionParameter::isExactMatch().
~TreePanel()
TreePanel::~TreePanel () virtual
Member Function Documentation
eventFilter()
bool TreePanel::eventFilter (QObject * obj, QEvent * ev)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Tree.h
Sources/FreeCAD/src/Gui/Tree.cpp