FreeCAD: SketcherGui::Ui_SketchMirrorDialog Class Reference
SketcherGui::Ui_SketchMirrorDialog Class Reference
#include <ui_SketchMirrorDialog.h>
Public Member Functions
void retranslateUi (QDialog *SketcherGui__SketchMirrorDialog)
void setupUi (QDialog *SketcherGui__SketchMirrorDialog)
Public Attributes
QDialogButtonBox * buttonBox
QGridLayout * gridLayout
QGroupBox * groupBox
QRadioButton * OriginRadioButton
QVBoxLayout * verticalLayout
QSpacerItem * verticalSpacer
QRadioButton * XAxisRadioButton
QRadioButton * YAxisRadioButton
Member Function Documentation
retranslateUi()
void SketcherGui::Ui_SketchMirrorDialog::retranslateUi (QDialog * SketcherGui__SketchMirrorDialog)
References groupBox, OriginRadioButton, draftguitools.gui_setstyle::translate, XAxisRadioButton, and YAxisRadioButton.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void SketcherGui::Ui_SketchMirrorDialog::setupUi (QDialog * SketcherGui__SketchMirrorDialog)
References buttonBox, draftgeoutils.intersections::connect(), gridLayout, groupBox, OriginRadioButton, retranslateUi(), verticalLayout, verticalSpacer, XAxisRadioButton, and YAxisRadioButton.
Member Data Documentation
buttonBox
QDialogButtonBox* SketcherGui::Ui_SketchMirrorDialog::buttonBox
Referenced by PathScripts.PathGetPoint.TaskPanel::getPoint(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::modifyStandardButtons(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::pageDirtyChanged(), PathScripts.PathGetPoint.TaskPanel::pointFinish(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setClean(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setDirty(), and setupUi().
gridLayout
QGridLayout* SketcherGui::Ui_SketchMirrorDialog::gridLayout
Referenced by setupUi().
groupBox
QGroupBox* SketcherGui::Ui_SketchMirrorDialog::groupBox
Referenced by retranslateUi(), and setupUi().
OriginRadioButton
QRadioButton* SketcherGui::Ui_SketchMirrorDialog::OriginRadioButton
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* SketcherGui::Ui_SketchMirrorDialog::verticalLayout
Referenced by setupUi().
verticalSpacer
QSpacerItem* SketcherGui::Ui_SketchMirrorDialog::verticalSpacer
Referenced by setupUi().
XAxisRadioButton
QRadioButton* SketcherGui::Ui_SketchMirrorDialog::XAxisRadioButton
Referenced by retranslateUi(), and setupUi().
YAxisRadioButton
QRadioButton* SketcherGui::Ui_SketchMirrorDialog::YAxisRadioButton
Referenced by retranslateUi(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/ui_SketchMirrorDialog.h