FreeCAD: Gui::Dialog::PrintModel Class Reference
Gui::Dialog::PrintModel Class Reference
#include <DlgCustomizeSpaceball.h>
Public Member Functions
virtual int columnCount (const QModelIndex &parent) const
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
PrintModel (QObject *parent, ButtonModel *buttonModelIn, CommandModel *commandModelIn)
virtual int rowCount (const QModelIndex &parent) const
Constructor & Destructor Documentation
PrintModel()
PrintModel::PrintModel (QObject * parent, ButtonModel * buttonModelIn, CommandModel * commandModelIn)
Member Function Documentation
columnCount()
int PrintModel::columnCount (const QModelIndex & parent) const virtual
data()
QVariant PrintModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
References Gui::Dialog::ButtonModel::data(), Gui::Dialog::CommandModel::data(), and Gui::Dialog::CommandModel::index().
Referenced by Mod.Show.mTempoVis.TempoVis::activateWorkbench(), Mod.Show.SceneDetail.SceneDetail::apply_data(), importIFClegacy.IfcSchema::capitalize(), Mod.Show.mTempoVis.TempoVis::forget(), Mod.Show.mTempoVis.TempoVis::forgetDetail(), Mod.Show.mTempoVis.TempoVis::has(), ArchSchedule.CommandArchSchedule::IsActive(), importIFClegacy.IfcSchema::readEntities(), importIFClegacy.IfcSchema::readTypes(), Mod.Show.mTempoVis.TempoVis::restore(), Mod.Show.mTempoVis.TempoVis::save(), Mod.Show.mTempoVis.TempoVis::stored_val(), FeaturePython.ViewProviderOctahedron::updateData(), and Dice3DS.dom3ds.UndefinedChunk::write().
headerData()
QVariant PrintModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
rowCount()
int PrintModel::rowCount (const QModelIndex & parent) const virtual
References Gui::Dialog::ButtonModel::rowCount().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgCustomizeSpaceball.h
Sources/FreeCAD/src/Gui/DlgCustomizeSpaceball.cpp