FreeCAD: TechDrawGui::QGSPage Class Reference
TechDrawGui::QGSPage Class Reference
#include <QGSPage.h>
Public Member Functions
void addBalloonToParent (QGIViewBalloon *balloon, QGIView *parent)
void addDimToParent (QGIViewDimension *dim, QGIView *parent)
QGIView * addDrawView (TechDraw::DrawView *view)
QGIView * addDrawViewAnnotation (TechDraw::DrawViewAnnotation *view)
QGIView * addDrawViewClip (TechDraw::DrawViewClip *view)
QGIView * addDrawViewCollection (TechDraw::DrawViewCollection *view)
QGIView * addDrawViewImage (TechDraw::DrawViewImage *view)
QGIView * addDrawViewSpreadsheet (TechDraw::DrawViewSpreadsheet *view)
QGIView * addDrawViewSymbol (TechDraw::DrawViewSymbol *view)
void addLeaderToParent (QGILeaderLine *lead, QGIView *parent)
QGIView * addProjectionGroup (TechDraw::DrawProjGroup *view)
int addQView (QGIView *view)
QGIView * addRichAnno (TechDraw::DrawRichAnno *anno)
QGIView * addViewBalloon (TechDraw::DrawViewBalloon *balloon)
QGIView * addViewDimension (TechDraw::DrawViewDimension *dim)
QGIView * addViewLeader (TechDraw::DrawLeaderLine *view)
QGIView * addViewPart (TechDraw::DrawViewPart *part)
QGIView * addViewSection (TechDraw::DrawViewPart *part)
QGIView * addWeldSymbol (TechDraw::DrawWeldSymbol *weld)
void createBalloon (QPointF origin, TechDraw::DrawViewPart *parent)
QGIView * findParent (QGIView *) const
QGIView * findQViewForDocObj (App::DocumentObject *obj) const
find the graphic for a DocumentObject
TechDraw::DrawPage * getDrawPage ()
QGIView * getQGIVByName (std::string name)
find the graphic for DocumentObject with name
QGITemplate * getTemplate () const
std::vector< QGIView * > getViews () const
retrieve the QGIView objects currently in the scene
void postProcessXml (QTemporaryFile &tempFile, QString filename, QString pagename)
QGSPage (ViewProviderPage *vp, QWidget *parent=nullptr)
virtual void refreshViews (void)
int removeQView (QGIView *view)
int removeQViewByName (const char *name)
void removeQViewFromScene (QGIView *view)
void removeTemplate ()
void saveSvg (QString filename)
Renders the page to SVG with filename.
void setExporting (bool enable)
void setPageTemplate (TechDraw::DrawTemplate *pageTemplate)
virtual ~QGSPage ()
Protected Member Functions
QColor getBackgroundColor ()
Protected Attributes
QGITemplate * pageTemplate
Static Protected Attributes
static QColor PreselectColor
static QColor SelectColor
Constructor & Destructor Documentation
QGSPage()
QGSPage::QGSPage (ViewProviderPage * vp, QWidget * parent = nullptr)
References TechDrawGui::ViewProviderPage::getDrawPage(), App::DocumentObject::getNameInDocument(), and TechDrawGui::ViewProviderPage::setGraphicsScene().
~QGSPage()
QGSPage::~QGSPage () virtual
Member Function Documentation
addBalloonToParent()
void QGSPage::addBalloonToParent (QGIViewBalloon * balloon, QGIView * parent)
References ZVALUE::DIMENSION.
Referenced by addViewBalloon(), and TechDrawGui::MDIViewPage::setBalloonGroups().
addDimToParent()
void QGSPage::addDimToParent (QGIViewDimension * dim, QGIView * parent)
References ZVALUE::DIMENSION.
Referenced by addViewDimension(), and TechDrawGui::MDIViewPage::setDimensionGroups().
addDrawView()
QGIView * QGSPage::addDrawView (TechDraw::DrawView * view)
References addQView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addDrawViewAnnotation()
QGIView * QGSPage::addDrawViewAnnotation (TechDraw::DrawViewAnnotation * view)
References addQView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addDrawViewClip()
QGIView * QGSPage::addDrawViewClip (TechDraw::DrawViewClip * view)
References addQView(), and TechDrawGui::Rez::guiX().
Referenced by TechDrawGui::MDIViewPage::attachView().
addDrawViewCollection()
QGIView * QGSPage::addDrawViewCollection (TechDraw::DrawViewCollection * view)
References addQView().
addDrawViewImage()
QGIView * QGSPage::addDrawViewImage (TechDraw::DrawViewImage * view)
References addQView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addDrawViewSpreadsheet()
QGIView * QGSPage::addDrawViewSpreadsheet (TechDraw::DrawViewSpreadsheet * view)
References addQView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addDrawViewSymbol()
QGIView * QGSPage::addDrawViewSymbol (TechDraw::DrawViewSymbol * view)
References addQView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addLeaderToParent()
void QGSPage::addLeaderToParent (QGILeaderLine * lead, QGIView * parent)
References ZVALUE::DIMENSION.
Referenced by addViewLeader(), and TechDrawGui::MDIViewPage::setLeaderGroups().
addProjectionGroup()
QGIView * QGSPage::addProjectionGroup (TechDraw::DrawProjGroup * view)
References addQView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addQView()
int QGSPage::addQView (QGIView * view)
References findParent(), getQGIVByName(), and TechDrawGui::Rez::guiX().
Referenced by addDrawView(), addDrawViewAnnotation(), addDrawViewClip(), addDrawViewCollection(), addDrawViewImage(), addDrawViewSpreadsheet(), addDrawViewSymbol(), addProjectionGroup(), addViewPart(), and addViewSection().
addRichAnno()
QGIView * QGSPage::addRichAnno (TechDraw::DrawRichAnno * anno)
References TechDraw::DrawRichAnno::AnnoParent, findQViewForDocObj(), App::PropertyLink::getValue(), and TechDrawGui::QGIRichAnno::updateView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addViewBalloon()
QGIView * QGSPage::addViewBalloon (TechDraw::DrawViewBalloon * balloon)
References addBalloonToParent(), and findParent().
Referenced by TechDrawGui::MDIViewPage::attachView().
addViewDimension()
QGIView * QGSPage::addViewDimension (TechDraw::DrawViewDimension * dim)
References addDimToParent(), and findParent().
Referenced by TechDrawGui::MDIViewPage::attachView().
addViewLeader()
QGIView * QGSPage::addViewLeader (TechDraw::DrawLeaderLine * view)
References addLeaderToParent(), findParent(), TechDrawGui::QGILeaderLine::setLeaderFeature(), and TechDrawGui::QGILeaderLine::updateView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addViewPart()
QGIView * QGSPage::addViewPart (TechDraw::DrawViewPart * part)
References addQView(), and findQViewForDocObj().
Referenced by TechDrawGui::MDIViewPage::attachView().
addViewSection()
QGIView * QGSPage::addViewSection (TechDraw::DrawViewPart * part)
References addQView().
Referenced by TechDrawGui::MDIViewPage::attachView().
addWeldSymbol()
QGIView * QGSPage::addWeldSymbol (TechDraw::DrawWeldSymbol * weld)
References Base::Console(), Base::ConsoleSingleton::Error(), findQViewForDocObj(), App::PropertyLink::getValue(), TechDraw::DrawWeldSymbol::Leader, TechDrawGui::QGIWeldSymbol::setFeature(), TechDrawGui::QGIView::setViewFeature(), and TechDrawGui::QGIWeldSymbol::updateView().
Referenced by TechDrawGui::MDIViewPage::attachView().
createBalloon()
void QGSPage::createBalloon (QPointF origin, TechDraw::DrawViewPart * parent)
References TechDrawGui::Rez::appPt(), Gui::Command::commitCommand(), App::DocumentObject::getDocument(), getDrawPage(), App::DocumentObject::getNameInDocument(), TechDraw::DrawPage::getNextBalloonIndex(), App::Document::getObject(), getQGIVByName(), TechDraw::DrawView::getScale(), App::Document::getUniqueObjectName(), Gui::Command::openCommand(), TechDraw::DrawViewBalloon::OriginX, TechDraw::DrawViewBalloon::OriginY, draftutils.translate::QT_TRANSLATE_NOOP, TechDraw::DrawViewBalloon::setOrigin(), App::PropertyString::setValue(), App::PropertyQuantity::setValue(), TechDraw::DrawViewBalloon::Text, TechDraw::DrawView::X, and TechDraw::DrawView::Y.
Referenced by TechDrawGui::QGVNavStyle::placeBalloon().
findParent()
QGIView * QGSPage::findParent (QGIView * view) const
References App::DocumentObject::getNameInDocument(), App::PropertyLink::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyLinkSubList::getValues(), getViews(), TechDraw::DrawLeaderLine::LeaderParent, TechDraw::DrawViewDimension::References2D, TechDraw::DrawViewBalloon::SourceView, and TechDraw::DrawViewCollection::Views.
Referenced by addQView(), addViewBalloon(), addViewDimension(), addViewLeader(), TechDrawGui::MDIViewPage::setBalloonGroups(), TechDrawGui::MDIViewPage::setDimensionGroups(), and TechDrawGui::MDIViewPage::setLeaderGroups().
findQViewForDocObj()
QGIView * QGSPage::findQViewForDocObj (App::DocumentObject * obj) const
find the graphic for a DocumentObject
References getViews().
Referenced by addRichAnno(), addViewPart(), addWeldSymbol(), TechDrawGui::MDIViewPage::fixOrphans(), TechDrawGui::TaskLeaderLine::onTrackerClicked(), TechDrawGui::MDIViewPage::selectQGIView(), TechDrawGui::TaskCosVertex::setEditCursor(), TechDrawGui::TaskLeaderLine::setEditCursor(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), and TechDrawGui::TaskRichAnno::TaskRichAnno().
getBackgroundColor()
QColor QGSPage::getBackgroundColor (void) protected
References App::Color::asValue(), App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetUnsigned(), App::Application::GetUserParameter(), and App::Color::setPackedValue().
getDrawPage()
TechDraw::DrawPage * QGSPage::getDrawPage ()
References TechDrawGui::ViewProviderPage::getDrawPage().
Referenced by createBalloon(), and TechDrawGui::DrawGuiUtil::findPage().
getQGIVByName()
QGIView * QGSPage::getQGIVByName (std::string name)
find the graphic for DocumentObject with name
References TechDrawGui::QGIView::getViewName().
Referenced by addQView(), and createBalloon().
getTemplate()
QGITemplate * QGSPage::getTemplate () const
References pageTemplate.
Referenced by TechDrawGui::ViewProviderTemplate::getQTemplate(), and TechDrawGui::MDIViewPage::updateTemplate().
getViews()
std::vector< QGIView * > QGSPage::getViews () const
retrieve the QGIView objects currently in the scene
Referenced by TechDrawGui::MDIViewPage::clearSceneSelection(), findParent(), findQViewForDocObj(), TechDrawGui::MDIViewPage::fixOrphans(), TechDrawGui::MDIViewPage::hasQView(), TechDrawGui::MDIViewPage::redraw1View(), TechDrawGui::MDIViewPage::redrawAllViews(), removeQViewByName(), TechDrawGui::MDIViewPage::setBalloonGroups(), TechDrawGui::MDIViewPage::setDimensionGroups(), and TechDrawGui::MDIViewPage::setLeaderGroups().
postProcessXml()
void QGSPage::postProcessXml (QTemporaryFile & tempFile, QString filename, QString pagename)
References Base::Console(), Base::FileInfo::fileName(), TechDrawGui::QGISVGTemplate::getSVGTemplate(), App::PropertyFileIncluded::getValue(), App::PropertyString::getValue(), TechDrawGui::Rez::guiX(), Base::ConsoleSingleton::Message(), TechDraw::DrawSVGTemplate::PageResult, pageTemplate, and TechDraw::DrawSVGTemplate::Template.
Referenced by saveSvg().
refreshViews()
void QGSPage::refreshViews (void) virtual
References TechDrawGui::QGIView::updateView().
Referenced by TechDrawGui::MDIViewPage::print(), saveSvg(), and TechDrawGui::ViewProviderPage::toggleFrameState().
removeQView()
int QGSPage::removeQView (QGIView * view)
References removeQViewFromScene().
Referenced by TechDrawGui::MDIViewPage::fixOrphans().
removeQViewByName()
int QGSPage::removeQViewByName (const char * name)
References getViews(), removeQViewFromScene(), and TechDrawGui::QGIView::type().
Referenced by TechDrawGui::MDIViewPage::onDeleteObject().
removeQViewFromScene()
void QGSPage::removeQViewFromScene (QGIView * view)
References TechDrawGui::QGIView::removeChild().
Referenced by removeQView(), and removeQViewByName().
removeTemplate()
void QGSPage::removeTemplate ()
References pageTemplate.
Referenced by setPageTemplate().
saveSvg()
void QGSPage::saveSvg (QString filename)
Renders the page to SVG with filename.
References Gui::SelectionSingleton::clearSelection(), App::DocumentObject::getDocument(), TechDrawGui::ViewProviderPage::getDrawPage(), TechDrawGui::ViewProviderPage::getFrameState(), App::Document::getName(), App::DocumentObject::getNameInDocument(), TechDraw::DrawPage::getPageHeight(), TechDraw::DrawPage::getPageWidth(), TechDrawGui::Rez::guiX(), pageTemplate, postProcessXml(), refreshViews(), OfflineRenderingUtils::render(), Gui::Selection(), setExporting(), TechDrawGui::ViewProviderPage::setFrameState(), and TechDrawGui::ViewProviderPage::setTemplateMarkers().
Referenced by TechDrawGui::MDIViewPage::saveSVG().
setExporting()
void QGSPage::setExporting (bool enable)
References TechDrawGui::QGIRichAnno::setExporting(), and TechDrawGui::QGIViewPart::setExporting().
Referenced by saveSvg().
setPageTemplate()
void QGSPage::setPageTemplate (TechDraw::DrawTemplate * pageTemplate)
References Base::Persistence::getClassTypeId(), pageTemplate, removeTemplate(), TechDrawGui::QGITemplate::setTemplate(), and TechDrawGui::QGITemplate::updateView().
Referenced by TechDrawGui::MDIViewPage::attachTemplate().
Member Data Documentation
pageTemplate
QGITemplate* TechDrawGui::QGSPage::pageTemplate protected
Referenced by getTemplate(), postProcessXml(), removeTemplate(), saveSvg(), and setPageTemplate().
PreselectColor
QColor TechDrawGui::QGSPage::PreselectColor static protected
SelectColor
QColor TechDrawGui::QGSPage::SelectColor static protected
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/QGSPage.h
FreeCAD/src/Mod/TechDraw/Gui/QGSPage.cpp