FreeCAD: WebGui::BrowserViewPy Class Reference
WebGui::BrowserViewPy Class Reference
Public Types
using BaseType = Py::PythonExtension< BrowserViewPy >
Public Member Functions
BrowserViewPy (BrowserView *view)
Py::Object cast_to_base (const Py::Tuple &)
Py::Object getattr (const char *)
BrowserView * getBrowserViewPtr ()
Py::Object load (const Py::Tuple &)
Py::Object repr ()
Py::Object setHtml (const Py::Tuple &)
Py::Object stop (const Py::Tuple &)
Py::Object url (const Py::Tuple &)
~BrowserViewPy ()
Static Public Member Functions
static void init_type ()
Member Typedef Documentation
BaseType
using WebGui::BrowserViewPy::BaseType = Py::PythonExtension<BrowserViewPy>
Constructor & Destructor Documentation
BrowserViewPy()
WebGui::BrowserViewPy::BrowserViewPy (BrowserView * view)
~BrowserViewPy()
WebGui::BrowserViewPy::~BrowserViewPy ()
Member Function Documentation
cast_to_base()
Py::Object WebGui::BrowserViewPy::cast_to_base (const Py::Tuple &)
References Gui::MDIViewPy::create().
Referenced by init_type().
getattr()
Py::Object WebGui::BrowserViewPy::getattr (const char * attr)
References getBrowserViewPtr().
getBrowserViewPtr()
BrowserView * WebGui::BrowserViewPy::getBrowserViewPtr ()
Referenced by getattr(), load(), setHtml(), stop(), and url().
init_type()
void WebGui::BrowserViewPy::init_type (void) static
References cast_to_base(), load(), setHtml(), stop(), and url().
Referenced by WebGui::BrowserView::getPyObject().
load()
Py::Object WebGui::BrowserViewPy::load (const Py::Tuple & args)
References getBrowserViewPtr(), and WebGui::BrowserView::load().
Referenced by init_type(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::loadDefaults(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle().
repr()
Py::Object WebGui::BrowserViewPy::repr ()
setHtml()
Py::Object WebGui::BrowserViewPy::setHtml (const Py::Tuple & args)
References getBrowserViewPtr(), and WebGui::BrowserView::setHtml().
Referenced by init_type().
stop()
Py::Object WebGui::BrowserViewPy::stop (const Py::Tuple & args)
References getBrowserViewPtr(), and WebGui::BrowserView::stop().
Referenced by ArchPanel.NestTaskPanel::accept(), init_type(), and ArchPanel.NestTaskPanel::reject().
url()
Py::Object WebGui::BrowserViewPy::url (const Py::Tuple & args)
References getBrowserViewPtr(), WebGui::BrowserView::url(), and url().
Referenced by addonmanager_macro.Macro::fill_details_from_wiki(), init_type(), Addon.Addon::set_metadata(), Addon.Addon::to_cache(), url(), and Addon.Addon::verify_url_and_branch().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Web/Gui/BrowserView.cpp