FreeCAD: SketcherGui::ExternalSelection Class Reference
SketcherGui::ExternalSelection Class Reference
Public Member Functions
bool allow (App::Document *pDoc, App::DocumentObject *pObj, const char *sSubName)
ExternalSelection (App::DocumentObject *obj)
Public Member Functions inherited from Gui::SelectionFilterGate
SelectionFilterGate (const char *filter)
construct with the filter string
SelectionFilterGate (SelectionFilter *filter)
~SelectionFilterGate ()
Public Member Functions inherited from Gui::SelectionGate
virtual ~SelectionGate ()
Additional Inherited Members
Public Attributes inherited from Gui::SelectionGate
std::string notAllowedReason
notAllowedReason is a string that sets the message to be displayed in statusbar for cluing the user on why is the selection not allowed.
Protected Member Functions inherited from Gui::SelectionFilterGate
SelectionFilterGate ()
Protected Attributes inherited from Gui::SelectionFilterGate
SelectionFilter * Filter
Constructor & Destructor Documentation
ExternalSelection()
SketcherGui::ExternalSelection::ExternalSelection (App::DocumentObject * obj)
Member Function Documentation
allow()
bool SketcherGui::ExternalSelection::allow (App::Document * pDoc, App::DocumentObject * pObj, const char * sSubName) virtual
Reimplemented from Gui::SelectionFilterGate.
References Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), Base::Type::isDerivedFrom(), Sketcher::SketchObject::isExternalAllowed(), Gui::SelectionGate::notAllowedReason, Sketcher::SketchObject::rlCircularReference, Sketcher::SketchObject::rlOtherBody, Sketcher::SketchObject::rlOtherDoc, and Sketcher::SketchObject::rlOtherPart.
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/Gui/CommandCreateGeo.cpp