FreeCAD: TechDrawGui::QGCustomRect Class Reference
TechDrawGui::QGCustomRect Class Reference
#include <QGCustomRect.h>
Public Types
enum { Type = QGraphicsItem::UserType + 133 }
Public Member Functions
virtual void centerAt (double cX, double cY)
virtual void centerAt (QPointF centerPos)
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr)
QGCustomRect (void)
int type () const
~QGCustomRect ()
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGCustomRect()
QGCustomRect::QGCustomRect (void) explicit
~QGCustomRect()
TechDrawGui::QGCustomRect::~QGCustomRect ()
Member Function Documentation
centerAt() [1/2]
void QGCustomRect::centerAt (double cX, double cY) virtual
centerAt() [2/2]
void QGCustomRect::centerAt (QPointF centerPos) virtual
References centerAt().
Referenced by TechDrawGui::QGIFace::buildPixHatch(), TechDrawGui::QGIFace::buildSvgHatch(), centerAt(), TechDrawGui::QGIRichAnno::QGIRichAnno(), TechDrawGui::QGIRichAnno::setTextItem(), and TechDrawGui::QGIRichAnno::updateView().
paint()
void QGCustomRect::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) virtual
type()
int TechDrawGui::QGCustomRect::type () const
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/QGCustomRect.h
FreeCAD/src/Mod/TechDraw/Gui/QGCustomRect.cpp