FreeCAD: Ui_TaskObjectName Class Reference
Ui_TaskObjectName Class Reference
#include <ui_TaskObjectName.h>
Public Member Functions
void retranslateUi (QWidget *TaskObjectName)
void setupUi (QWidget *TaskObjectName)
Public Attributes
QHBoxLayout * horizontalLayout
QLineEdit * lineEdit_ObjectName
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void Ui_TaskObjectName::retranslateUi (QWidget * TaskObjectName)
References draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Ui_TaskObjectName::setupUi (QWidget * TaskObjectName)
References horizontalLayout, lineEdit_ObjectName, retranslateUi(), and verticalLayout.
Referenced by FemGui::TaskObjectName::TaskObjectName().
Member Data Documentation
horizontalLayout
QHBoxLayout* Ui_TaskObjectName::horizontalLayout
Referenced by setupUi().
lineEdit_ObjectName
QLineEdit* Ui_TaskObjectName::lineEdit_ObjectName
Referenced by setupUi(), and FemGui::TaskObjectName::TaskObjectName().
verticalLayout
QVBoxLayout* Ui_TaskObjectName::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Fem/Gui/ui_TaskObjectName.h