FreeCAD: Gui::ControlSingleton Class Reference
Gui::ControlSingleton Class Reference
The control class.
#include <Control.h>
Public Member Functions
dialog handling
These methods are used to control the TaskDialog stuff.
void showDialog (Gui::TaskView::TaskDialog *dlg)
This method starts a task dialog in the task view.
Gui::TaskView::TaskDialog * activeDialog () const
Static Public Member Functions
static void destruct (void)
static ControlSingleton & instance (void)
task view handling
Gui::TaskView::TaskView * taskPanel () const
void showModelView ()
raising the model view
QTabWidget * tabPanel () const
get the tab panel
bool isAllowedAlterDocument (void) const
bool isAllowedAlterView (void) const
bool isAllowedAlterSelection (void) const
void accept ()
void reject ()
void closeDialog ()
void showTaskView ()
raises the task view panel
Detailed Description
The control class.
Member Function Documentation
accept
void ControlSingleton::accept () slot
References Gui::TaskView::TaskView::accept(), and taskPanel().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
activeDialog()
Gui::TaskView::TaskDialog * ControlSingleton::activeDialog () const
Referenced by Gui::TaskView::ControlPy::activeDialog(), Gui::Document::canClose(), PartGui::ViewProviderPartExt::changeFaceColors(), PartGui::goDimensionAngularRoot(), PartGui::goDimensionLinearRoot(), StdCmdEdit::isActive(), StdCmdTextureMapping::isActive(), PartGui::PropertyEnumAttacherItem::openTask(), Gui::Document::setEdit(), FemGui::ViewProviderFemConstraintBearing::setEdit(), FemGui::ViewProviderFemConstraintContact::setEdit(), FemGui::ViewProviderFemConstraintDisplacement::setEdit(), FemGui::ViewProviderFemConstraintFixed::setEdit(), FemGui::ViewProviderFemConstraintFluidBoundary::setEdit(), FemGui::ViewProviderFemConstraintForce::setEdit(), FemGui::ViewProviderFemConstraintGear::setEdit(), FemGui::ViewProviderFemConstraintHeatflux::setEdit(), FemGui::ViewProviderFemConstraintInitialTemperature::setEdit(), FemGui::ViewProviderFemConstraintPlaneRotation::setEdit(), FemGui::ViewProviderFemConstraintPressure::setEdit(), FemGui::ViewProviderFemConstraintPulley::setEdit(), FemGui::ViewProviderFemConstraintTemperature::setEdit(), FemGui::ViewProviderFemConstraintTransform::setEdit(), FemGui::ViewProviderFemPostFunction::setEdit(), FemGui::ViewProviderFemPostObject::setEdit(), PartGui::ViewProviderOffset::setEdit(), PartGui::ViewProviderThickness::setEdit(), PartDesignGui::ViewProviderHole::setEdit(), PartDesignGui::ViewProviderPrimitive::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), SurfaceGui::ViewProviderFilling::setEdit(), SurfaceGui::ViewProviderGeomFillSurface::setEdit(), SurfaceGui::ViewProviderSections::setEdit(), TechDrawGui::ViewProviderProjGroup::setEdit(), Gui::ViewProviderLink::setEdit(), PartDesignGui::ViewProvider::setEdit(), PartDesignGui::ViewProviderBoolean::setEdit(), PartDesignGui::ViewProviderDatum::setEdit(), PartDesignGui::ViewProviderShapeBinder::setEdit(), TechDrawGui::ViewProviderGeomHatch::setEdit(), TechDrawGui::ViewProviderHatch::setEdit(), and Gui::TaskView::ControlPy::showDialog().
closeDialog
void ControlSingleton::closeDialog () slot
References Gui::DockWnd::ComboView::closeDialog(), and Gui::DockWindowManager::instance().
Referenced by Gui::TaskView::ControlPy::closeDialog(), TechDrawGui::TaskSectionView::failNoObject(), PartGui::ViewProviderOffset::setEdit(), PartGui::ViewProviderThickness::setEdit(), PartDesignGui::ViewProviderHole::setEdit(), PartDesignGui::ViewProviderPrimitive::setEdit(), PartDesignGui::ViewProviderBoolean::setEdit(), PartDesignGui::ViewProviderDatum::setEdit(), Gui::ElementColors::slotDeleteDocument(), PartGui::FaceColors::slotDeleteDocument(), PartGui::FaceColors::slotDeleteObject(), Gui::ElementColors::slotDeleteObject(), PartGui::FaceColors::slotUndoDocument(), FemGui::ViewProviderFemAnalysis::unsetEdit(), FemGui::ViewProviderFemConstraint::unsetEdit(), FemGui::ViewProviderFemPostFunction::unsetEdit(), FemGui::ViewProviderFemPostObject::unsetEdit(), PartGui::ViewProviderFillet::unsetEdit(), PartGui::ViewProviderChamfer::unsetEdit(), PartGui::ViewProviderOffset::unsetEdit(), PartGui::ViewProviderPrimitive::unsetEdit(), PathGui::ViewProviderPathCompound::unsetEdit(), RobotGui::ViewProviderTrajectoryCompound::unsetEdit(), RobotGui::ViewProviderTrajectoryDressUp::unsetEdit(), SketcherGui::ViewProviderSketch::unsetEdit(), TechDrawGui::ViewProviderBalloon::unsetEdit(), TechDrawGui::ViewProviderLeader::unsetEdit(), TechDrawGui::ViewProviderProjGroup::unsetEdit(), TechDrawGui::ViewProviderProjGroupItem::unsetEdit(), TechDrawGui::ViewProviderRichAnno::unsetEdit(), TechDrawGui::ViewProviderViewPart::unsetEdit(), TechDrawGui::ViewProviderViewSection::unsetEdit(), TechDrawGui::ViewProviderWeld::unsetEdit(), Gui::ViewProviderDragger::unsetEdit(), PartDesignGui::ViewProvider::unsetEdit(), PartDesignGui::ViewProviderDatum::unsetEdit(), TechDrawGui::ViewProviderDrawingView::unsetEdit(), TechDrawGui::ViewProviderGeomHatch::unsetEdit(), TechDrawGui::ViewProviderHatch::unsetEdit(), and Gui::ViewProviderLink::unsetEditViewer().
destruct()
void ControlSingleton::destruct (void) static
instance()
ControlSingleton & ControlSingleton::instance (void) static
Referenced by Gui::Control().
isAllowedAlterDocument()
bool ControlSingleton::isAllowedAlterDocument (void) const
If a task dialog is open then it indicates whether this task dialog allows other commands to modify the document while it is open. If no task dialog is open true is returned.
References Gui::TaskView::TaskDialog::isAllowedAlterDocument().
Referenced by Gui::TaskView::ControlPy::isAllowedAlterDocument().
isAllowedAlterSelection()
bool ControlSingleton::isAllowedAlterSelection (void) const
If a task dialog is open then it indicates whether this task dialog allows other commands to modify the selection while it is open. If no task dialog is open true is returned.
References Gui::TaskView::TaskDialog::isAllowedAlterSelection().
Referenced by Gui::TaskView::ControlPy::isAllowedAlterSelection().
isAllowedAlterView()
bool ControlSingleton::isAllowedAlterView (void) const
If a task dialog is open then it indicates whether this task dialog allows other commands to modify the 3d view while it is open. If no task dialog is open true is returned.
References Gui::TaskView::TaskDialog::isAllowedAlterView().
Referenced by Gui::TaskView::ControlPy::isAllowedAlterView().
reject
void ControlSingleton::reject () slot
References Gui::TaskView::TaskView::reject(), and taskPanel().
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), FemGui::ViewProviderFemConstraintBearing::setEdit(), FemGui::ViewProviderFemConstraintFixed::setEdit(), FemGui::ViewProviderFemConstraintFluidBoundary::setEdit(), FemGui::ViewProviderFemConstraintForce::setEdit(), FemGui::ViewProviderFemConstraintGear::setEdit(), FemGui::ViewProviderFemConstraintPulley::setEdit(), FemGui::ViewProviderFemPostFunction::setEdit(), FemGui::ViewProviderFemPostObject::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), PartDesignGui::ViewProvider::setEdit(), PartDesignGui::ViewProviderShapeBinder::setEdit(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
showDialog()
void ControlSingleton::showDialog (Gui::TaskView::TaskDialog * dlg)
This method starts a task dialog in the task view.
References draftgeoutils.intersections::connect(), Gui::DockWindowManager::getDockWindow(), Gui::getMainWindow(), Gui::DockWindowManager::instance(), App::AutoTransaction::setEnable(), and Gui::DockWnd::ComboView::showDialog().
Referenced by StdCmdTransform::activated(), StdCmdPlacement::activated(), StdCmdSetAppearance::activated(), StdCmdTextureMapping::activated(), PartGui::ViewProviderPartExt::changeFaceColors(), FemGui::ViewProviderSetNodes::doubleClicked(), RobotGui::ViewProviderEdge2TracObject::doubleClicked(), PartGui::goDimensionAngularRoot(), PartGui::goDimensionLinearRoot(), PartGui::PropertyEnumAttacherItem::openTask(), FemGui::ViewProviderFemConstraintBearing::setEdit(), FemGui::ViewProviderFemConstraintContact::setEdit(), FemGui::ViewProviderFemConstraintDisplacement::setEdit(), FemGui::ViewProviderFemConstraintFixed::setEdit(), FemGui::ViewProviderFemConstraintFluidBoundary::setEdit(), FemGui::ViewProviderFemConstraintForce::setEdit(), FemGui::ViewProviderFemConstraintGear::setEdit(), FemGui::ViewProviderFemConstraintHeatflux::setEdit(), FemGui::ViewProviderFemConstraintInitialTemperature::setEdit(), FemGui::ViewProviderFemConstraintPlaneRotation::setEdit(), FemGui::ViewProviderFemConstraintPressure::setEdit(), FemGui::ViewProviderFemConstraintPulley::setEdit(), FemGui::ViewProviderFemConstraintTemperature::setEdit(), FemGui::ViewProviderFemConstraintTransform::setEdit(), FemGui::ViewProviderFemMeshShapeNetgen::setEdit(), FemGui::ViewProviderFemPostFunction::setEdit(), FemGui::ViewProviderFemPostObject::setEdit(), FemGui::ViewProviderSetNodes::setEdit(), PartGui::ViewProviderFillet::setEdit(), PartGui::ViewProviderChamfer::setEdit(), PartGui::ViewProviderOffset::setEdit(), PartGui::ViewProviderThickness::setEdit(), PartGui::ViewProviderPrimitive::setEdit(), PartDesignGui::ViewProviderHole::setEdit(), PartDesignGui::ViewProviderPrimitive::setEdit(), PathGui::ViewProviderPathCompound::setEdit(), RobotGui::ViewProviderEdge2TracObject::setEdit(), RobotGui::ViewProviderTrajectoryCompound::setEdit(), RobotGui::ViewProviderTrajectoryDressUp::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), SurfaceGui::ViewProviderFilling::setEdit(), SurfaceGui::ViewProviderGeomFillSurface::setEdit(), SurfaceGui::ViewProviderSections::setEdit(), TechDrawGui::ViewProviderBalloon::setEdit(), TechDrawGui::ViewProviderLeader::setEdit(), TechDrawGui::ViewProviderProjGroup::setEdit(), TechDrawGui::ViewProviderRichAnno::setEdit(), TechDrawGui::ViewProviderViewPart::setEdit(), TechDrawGui::ViewProviderViewSection::setEdit(), TechDrawGui::ViewProviderWeld::setEdit(), Gui::ViewProviderDragger::setEdit(), Gui::ViewProviderLink::setEdit(), PartDesignGui::ViewProvider::setEdit(), PartDesignGui::ViewProviderBoolean::setEdit(), PartDesignGui::ViewProviderDatum::setEdit(), PartDesignGui::ViewProviderShapeBinder::setEdit(), TechDrawGui::ViewProviderGeomHatch::setEdit(), TechDrawGui::ViewProviderHatch::setEdit(), Gui::ViewProviderLink::setEditViewer(), and Gui::TaskView::ControlPy::showDialog().
showModelView()
void ControlSingleton::showModelView ()
raising the model view
References Gui::DockWindowManager::instance(), and Gui::DockWnd::ComboView::showTreeView().
showTaskView
void ControlSingleton::showTaskView () slot
raises the task view panel
References Gui::DockWindowManager::instance(), and Gui::DockWnd::ComboView::showTaskView().
Referenced by PartDesignGui::Workbench::activated(), RobotGui::Workbench::activated(), and Gui::TaskView::ControlPy::showTaskView().
tabPanel()
QTabWidget * ControlSingleton::tabPanel () const
get the tab panel
References Gui::DockWnd::ComboView::getTabPanel(), and Gui::DockWindowManager::instance().
taskPanel()
Gui::TaskView::TaskView * ControlSingleton::taskPanel () const
References Gui::DockWnd::ComboView::getTaskPanel(), and Gui::DockWindowManager::instance().
Referenced by accept(), Gui::TaskView::ControlPy::addTaskWatcher(), Gui::Workbench::addTaskWatcher(), Gui::TaskView::ControlPy::clearTaskWatcher(), reject(), and Gui::Workbench::removeTaskWatcher().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Control.h
Sources/FreeCAD/src/Gui/Control.cpp