FreeCAD: PathScripts.post.comparams_post Namespace Reference
PathScripts.post.comparams_post Namespace Reference
Classes
class saveVals
Functions
def export (obj, filename, argstring)
def ffmt (num)
def fmt (num)
def lineout (command, oldvals, modal)
Variables
bool SHOW_EDITOR = True
string TOOLTIP = '''Example Post, using Path.Commands instead of Path.toGCode strings for Path gcode output.'''
Function Documentation
export()
def PathScripts.post.comparams_post.export (obj, filename, argstring)
References PathScripts.post.comparams_post.lineout().
ffmt()
def PathScripts.post.comparams_post.ffmt (num)
Referenced by PathScripts.post.comparams_post.lineout().
fmt()
def PathScripts.post.comparams_post.fmt (num)
Referenced by PathScripts.post.comparams_post.lineout().
lineout()
def PathScripts.post.comparams_post.lineout (command, oldvals, modal)
References PathScripts.post.comparams_post.ffmt(), and PathScripts.post.comparams_post.fmt().
Referenced by PathScripts.post.comparams_post.export().
Variable Documentation
SHOW_EDITOR
bool PathScripts.post.comparams_post.SHOW_EDITOR = True
TOOLTIP
string PathScripts.post.comparams_post.TOOLTIP = '''Example Post, using Path.Commands instead of Path.toGCode strings for Path gcode output.'''