FreeCAD: TechDraw::CosmeticEdge Class Reference
TechDraw::CosmeticEdge Class Reference
#include <Cosmetic.h>
Public Member Functions
CosmeticEdge * clone (void) const
CosmeticEdge * copy (void) const
CosmeticEdge ()
CosmeticEdge (Base::Vector3d p1, Base::Vector3d p2)
CosmeticEdge (CosmeticEdge *ce)
CosmeticEdge (TechDraw::BaseGeom *g)
CosmeticEdge (TopoDS_Edge e)
void dump (const char *title)
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
boost::uuids::uuid getTag () const
virtual std::string getTagAsString (void) const
void initialize (void)
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
TechDraw::BaseGeom * scaledGeometry (double scale)
virtual std::string toString (void) const
virtual ~CosmeticEdge ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from TechDraw::BaseGeom
BaseGeom ()
bool closed (void)
BaseGeom * copy ()
std::string dump ()
std::vector< Base::Vector3d > findEndPoints ()
std::string getCosmeticTag (void)
Base::Vector3d getEndPoint ()
Base::Vector3d getMidPoint ()
std::vector< Base::Vector3d > getQuads ()
Base::Vector3d getStartPoint ()
boost::uuids::uuid getTag () const
double minDist (Base::Vector3d p)
Base::Vector3d nearPoint (Base::Vector3d p)
Base::Vector3d nearPoint (const BaseGeom *p)
find point on me nearest to p
void setCosmeticTag (std::string t)
void source (int s)
int source (void)
void sourceIndex (int si)
int sourceIndex (void)
virtual ~BaseGeom ()=default
Public Attributes
LineFormat m_format
TechDraw::BaseGeom * m_geometry
Base::Vector3d permaEnd
double permaRadius
Base::Vector3d permaStart
Public Attributes inherited from TechDraw::BaseGeom
edgeClass classOfEdge
bool cosmetic
ExtractionType extractType
GeomType geomType
bool hlrVisible
TopoDS_Edge occEdge
int ref3D
bool reversed
Protected Member Functions
void assignTag (const TechDraw::CosmeticEdge *ce)
void createNewTag ()
Protected Member Functions inherited from TechDraw::BaseGeom
void createNewTag ()
Protected Attributes
Py::Object PythonObject
boost::uuids::uuid tag
Protected Attributes inherited from TechDraw::BaseGeom
std::string cosmeticTag
int m_source
int m_sourceIndex
boost::uuids::uuid tag
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from TechDraw::BaseGeom
static BaseGeom * baseFactory (TopoDS_Edge edge)
Convert 1 OCC edge into 1 BaseGeom (static factory method)
static bool validateEdge (TopoDS_Edge edge)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
CosmeticEdge() [1/5]
CosmeticEdge::CosmeticEdge ()
Referenced by copy().
CosmeticEdge() [2/5]
CosmeticEdge::CosmeticEdge (CosmeticEdge * ce)
References TechDraw::BaseGeom::copy(), initialize(), m_format, m_geometry, permaEnd, permaRadius, and permaStart.
CosmeticEdge() [3/5]
CosmeticEdge::CosmeticEdge (Base::Vector3d p1, Base::Vector3d p2)
References TechDraw::BaseGeom::baseFactory(), initialize(), TechDraw::DrawUtil::invertY(), m_geometry, permaEnd, permaStart, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
CosmeticEdge() [4/5]
CosmeticEdge::CosmeticEdge (TopoDS_Edge e)
References TechDraw::BaseGeom::baseFactory(), TechDraw::Circle::center, TechDraw::BaseGeom::geomType, TechDraw::BaseGeom::getEndPoint(), TechDraw::BaseGeom::getStartPoint(), initialize(), m_geometry, permaEnd, permaRadius, permaStart, and TechDraw::Circle::radius.
CosmeticEdge() [5/5]
CosmeticEdge::CosmeticEdge (TechDraw::BaseGeom * g)
References TechDraw::Circle::center, TechDraw::BaseGeom::getEndPoint(), TechDraw::BaseGeom::getStartPoint(), initialize(), m_geometry, permaEnd, permaRadius, permaStart, and TechDraw::Circle::radius.
~CosmeticEdge()
CosmeticEdge::~CosmeticEdge (void) virtual
References m_geometry.
Member Function Documentation
assignTag()
void CosmeticEdge::assignTag (const TechDraw::CosmeticEdge * ce) protected
References Base::Persistence::getTypeId(), and tag.
clone()
CosmeticEdge * CosmeticEdge::clone (void) const
References copy(), and tag.
Referenced by ArchPanel.CommandPanelSheet::Activated(), TechDraw::CosmeticEdgePy::clone(), ArchComponent.Component::execute(), ArchCurtainWall.CurtainWall::execute(), ArchTruss.Truss::execute(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated(), and PathTests.TestPathHelix.TestPathHelix::test04().
copy()
CosmeticEdge * CosmeticEdge::copy (void) const
References TechDraw::BaseGeom::copy(), CosmeticEdge(), m_format, and m_geometry.
Referenced by clone(), and TechDraw::CosmeticEdgePy::copy().
createNewTag()
void CosmeticEdge::createNewTag () protected
References tag.
Referenced by initialize().
dump()
void CosmeticEdge::dump (const char * title)
References Base::Console(), Base::ConsoleSingleton::Message(), and toString().
getMemSize()
unsigned int CosmeticEdge::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
getPyObject()
PyObject * CosmeticEdge::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
References PythonObject.
Referenced by TechDraw::DrawViewPartPy::getCosmeticEdge(), and TechDraw::DrawViewPartPy::getCosmeticEdgeBySelection().
getTag()
boost::uuids::uuid CosmeticEdge::getTag (void) const
References tag.
Referenced by getTagAsString().
getTagAsString()
std::string CosmeticEdge::getTagAsString (void) const virtual
Reimplemented from TechDraw::BaseGeom.
References getTag().
Referenced by TechDraw::CosmeticExtension::addCosmeticEdge(), TechDraw::GeometryObject::addCosmeticEdge(), initialize(), scaledGeometry(), and toString().
initialize()
void CosmeticEdge::initialize (void)
References TechDraw::BaseGeom::classOfEdge, TechDraw::BaseGeom::cosmetic, createNewTag(), TechDraw::ecHARD, getTagAsString(), TechDraw::BaseGeom::hlrVisible, m_geometry, TechDraw::BaseGeom::setCosmeticTag(), and TechDraw::BaseGeom::source().
Referenced by CosmeticEdge().
Restore()
void CosmeticEdge::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References TechDraw::Circle::center, Base::Console(), TechDraw::GeometryUtils::edgeFromCircle(), TechDraw::GeometryUtils::edgeFromCircleArc(), TechDraw::GeometryUtils::edgeFromGeneric(), TechDraw::AOC::endPnt, App::Color::fromHexString(), Base::XMLReader::getAttribute(), Base::XMLReader::getAttributeAsFloat(), Base::XMLReader::getAttributeAsInteger(), TechDraw::BaseGeom::getEndPoint(), TechDraw::BaseGeom::getStartPoint(), TechDraw::LineFormat::m_color, m_format, m_geometry, TechDraw::LineFormat::m_style, TechDraw::LineFormat::m_visible, TechDraw::LineFormat::m_weight, TechDraw::BaseGeom::occEdge, permaEnd, permaRadius, permaStart, TechDraw::Circle::radius, Base::XMLReader::readElement(), TechDraw::Circle::Restore(), TechDraw::AOC::Restore(), TechDraw::Generic::Restore(), TechDraw::CosmeticVertex::restoreCosmetic(), TechDraw::AOC::startPnt, and Base::ConsoleSingleton::Warning().
Referenced by TechDraw::PropertyCosmeticEdgeList::Restore().
Save()
void CosmeticEdge::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References App::Color::asHexString(), Base::Console(), TechDraw::BaseGeom::geomType, Base::Writer::ind(), TechDraw::LineFormat::m_color, m_format, m_geometry, TechDraw::LineFormat::m_style, TechDraw::LineFormat::m_visible, TechDraw::LineFormat::m_weight, TechDraw::Circle::Save(), TechDraw::AOC::Save(), TechDraw::Generic::Save(), Base::Writer::Stream(), and Base::ConsoleSingleton::Warning().
scaledGeometry()
TechDraw::BaseGeom * CosmeticEdge::scaledGeometry (double scale)
References TechDraw::BaseGeom::baseFactory(), TechDraw::BaseGeom::classOfEdge, TechDraw::BaseGeom::cosmetic, TechDraw::ecHARD, getTagAsString(), TechDraw::BaseGeom::hlrVisible, m_geometry, TechDraw::BaseGeom::occEdge, TechDraw::scaleShape(), TechDraw::BaseGeom::setCosmeticTag(), and TechDraw::BaseGeom::source().
Referenced by TechDraw::DrawViewPart::add1CEToGE(), and TechDraw::GeometryObject::addCosmeticEdge().
toString()
std::string CosmeticEdge::toString (void) const virtual
Reimplemented from TechDraw::BaseGeom.
References TechDraw::BaseGeom::geomType, getTagAsString(), m_format, m_geometry, TechDraw::LineFormat::toString(), and TechDraw::BaseGeom::toString().
Referenced by dump().
Member Data Documentation
m_format
LineFormat TechDraw::CosmeticEdge::m_format
Referenced by TechDrawGui::TaskLineDecor::applyDecorations(), copy(), CosmeticEdge(), TechDrawGui::QGIViewPart::formatGeomFromCosmetic(), TechDrawGui::TaskLineDecor::getDefaults(), TechDraw::CosmeticEdgePy::getFormat(), TechDraw::DrawViewPartPy::makeCosmeticCircle(), TechDraw::DrawViewPartPy::makeCosmeticCircleArc(), TechDraw::DrawViewPartPy::makeCosmeticLine(), TechDraw::DrawViewPartPy::makeCosmeticLine3D(), Restore(), Save(), TechDraw::CosmeticEdgePy::setFormat(), and toString().
m_geometry
TechDraw::BaseGeom* TechDraw::CosmeticEdge::m_geometry
Referenced by copy(), CosmeticEdge(), TechDraw::CosmeticEdgePy::getCenter(), TechDraw::CosmeticEdgePy::getRadius(), initialize(), Restore(), Save(), scaledGeometry(), TechDraw::CosmeticEdgePy::setCenter(), TechDraw::CosmeticEdgePy::setEnd(), TechDraw::CosmeticEdgePy::setRadius(), TechDraw::CosmeticEdgePy::setStart(), toString(), TechDrawGui::TaskCosmeticLine::updateCosmeticLine(), and ~CosmeticEdge().
permaEnd
Base::Vector3d TechDraw::CosmeticEdge::permaEnd
Referenced by CosmeticEdge(), TechDraw::CosmeticEdgePy::getEnd(), Restore(), TechDraw::CosmeticEdgePy::setCenter(), TechDraw::CosmeticEdgePy::setEnd(), TechDraw::CosmeticEdgePy::setStart(), TechDrawGui::TaskCosmeticLine::setUiEdit(), and TechDrawGui::TaskCosmeticLine::updateCosmeticLine().
permaRadius
double TechDraw::CosmeticEdge::permaRadius
Referenced by CosmeticEdge(), TechDraw::CosmeticEdgePy::getRadius(), TechDraw::DrawViewPartPy::makeCosmeticCircle(), TechDraw::DrawViewPartPy::makeCosmeticCircleArc(), Restore(), TechDraw::CosmeticEdgePy::setCenter(), and TechDraw::CosmeticEdgePy::setRadius().
permaStart
Base::Vector3d TechDraw::CosmeticEdge::permaStart
Referenced by CosmeticEdge(), TechDraw::CosmeticEdgePy::getCenter(), TechDraw::CosmeticEdgePy::getStart(), Restore(), TechDraw::CosmeticEdgePy::setCenter(), TechDraw::CosmeticEdgePy::setEnd(), TechDraw::CosmeticEdgePy::setStart(), TechDrawGui::TaskCosmeticLine::setUiEdit(), and TechDrawGui::TaskCosmeticLine::updateCosmeticLine().
PythonObject
Py::Object TechDraw::CosmeticEdge::PythonObject protected
Referenced by getPyObject().
tag
boost::uuids::uuid TechDraw::CosmeticEdge::tag protected
Referenced by PathScripts.PathDressupHoldingTags.MapWireToTag::add(), assignTag(), PathScripts.PathDressupHoldingTags.MapWireToTag::cleanupEdges(), clone(), PathScripts.PathDressupHoldingTags.MapWireToTag::commandsForEdges(), createNewTag(), Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.ChunkBase::dump_header(), getTag(), ArchPanel.PanelCut::getWires(), PathScripts.PathDressupHoldingTags.MapWireToTag::shell(), and FreeCADInit.FCADLogger::trace().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/App/Cosmetic.h
Sources/FreeCAD/src/Mod/TechDraw/App/Cosmetic.cpp