FreeCAD: SMDS_MeshNode_MyInvIterator Class Reference
SMDS_MeshNode_MyInvIterator Class Reference
Iterator on list of elements.
Public Member Functions
bool more ()
Return true if and only if there are other object in this iterator.
const SMDS_MeshElement * next ()
Return the current object and step to the next one.
SMDS_MeshNode_MyInvIterator (SMDS_Mesh *mesh, vtkIdType *cells, int ncells, SMDSAbs_ElementType type)
Public Member Functions inherited from SMDS_Iterator< const SMDS_MeshElement * >
virtual bool more ()=0
Return true if and only if there are other object in this iterator.
virtual const SMDS_MeshElement * next ()=0
Return the current object and step to the next one.
virtual void remove ()
Delete the current element and step to the next one.
virtual ~SMDS_Iterator ()
Provide virtual destructor just for case if some derived iterator must have a destructor.
Detailed Description
Iterator on list of elements.
Constructor & Destructor Documentation
SMDS_MeshNode_MyInvIterator()
SMDS_MeshNode_MyInvIterator::SMDS_MeshNode_MyInvIterator (SMDS_Mesh * mesh, vtkIdType * cells, int ncells, SMDSAbs_ElementType type)
References SMDS_Mesh::FindElement(), SMDS_Mesh::fromVtkToSmds(), and SMDS_MeshElement::GetType().
Member Function Documentation
more()
bool SMDS_MeshNode_MyInvIterator::more () virtual
Return true if and only if there are other object in this iterator.
Implements SMDS_Iterator< const SMDS_MeshElement * >.
next()
const SMDS_MeshElement * SMDS_MeshNode_MyInvIterator::next () virtual
Return the current object and step to the next one.
Implements SMDS_Iterator< const SMDS_MeshElement * >.
References SMDS_Mesh::FindElement(), and SMDS_Mesh::fromVtkToSmds().
The documentation for this class was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_MeshNode.cpp