FreeCAD: AttachmentEditor.TaskAttachmentEditor Namespace Reference
AttachmentEditor.TaskAttachmentEditor Namespace Reference
Classes
class AttachmentEditorTaskPanel
class CancelError
Functions
def getAllDependent (feature)
def GetSelectionAsLinkSubList ()
def LinkFromStr (strlink, document)
def linkSubList_convertToOldStyle (references)
def PlacementsFuzzyCompare (plm1, plm2)
def RefsFromStrList (strings, document)
def StrFromLink (feature, subname)
def StrListFromRefs (references)
def TempoVis (doc, tag)
Variables
deg = App.Units.Degree
mm = App.Units.MilliMetre
Q = App.Units.Quantity
translate = App.Qt.translate
Function Documentation
getAllDependent()
def AttachmentEditor.TaskAttachmentEditor.getAllDependent (feature)
Referenced by AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel.addSelection().
GetSelectionAsLinkSubList()
def AttachmentEditor.TaskAttachmentEditor.GetSelectionAsLinkSubList ()
LinkFromStr()
def AttachmentEditor.TaskAttachmentEditor.LinkFromStr (strlink, document)
Referenced by AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel.addSelection(), and AttachmentEditor.TaskAttachmentEditor.RefsFromStrList().
linkSubList_convertToOldStyle()
def AttachmentEditor.TaskAttachmentEditor.linkSubList_convertToOldStyle (references)
Referenced by AttachmentEditor.TaskAttachmentEditor.StrListFromRefs().
PlacementsFuzzyCompare()
def AttachmentEditor.TaskAttachmentEditor.PlacementsFuzzyCompare (plm1, plm2)
Referenced by AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel.updatePreview().
RefsFromStrList()
def AttachmentEditor.TaskAttachmentEditor.RefsFromStrList (strings, document)
input: strings as from UI. Output: list of tuples that can be assigned to PropertyLinkSubList.
References AttachmentEditor.TaskAttachmentEditor.LinkFromStr().
Referenced by AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel.parseAllRefLines().
StrFromLink()
def AttachmentEditor.TaskAttachmentEditor.StrFromLink (feature, subname)
Referenced by AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel.addSelection(), and AttachmentEditor.TaskAttachmentEditor.StrListFromRefs().
StrListFromRefs()
def AttachmentEditor.TaskAttachmentEditor.StrListFromRefs (references)
input: PropertyLinkSubList. Output: list of strings for UI.
References AttachmentEditor.TaskAttachmentEditor.linkSubList_convertToOldStyle(), and AttachmentEditor.TaskAttachmentEditor.StrFromLink().
Referenced by AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel.fillAllRefLines().
TempoVis()
def AttachmentEditor.TaskAttachmentEditor.TempoVis (doc, tag)
Variable Documentation
deg
AttachmentEditor.TaskAttachmentEditor.deg = App.Units.Degree
mm
AttachmentEditor.TaskAttachmentEditor.mm = App.Units.MilliMetre
Q
AttachmentEditor.TaskAttachmentEditor.Q = App.Units.Quantity
Referenced by AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel.attachmentOffsetChanged().
translate
AttachmentEditor.TaskAttachmentEditor.translate = App.Qt.translate