FreeCAD: PartGui::SweepWidget Class Reference
PartGui::SweepWidget Class Reference
#include <TaskSweep.h>
Classes
class Private
Public Member Functions
bool accept ()
bool reject ()
SweepWidget (QWidget *parent=nullptr)
~SweepWidget ()
Constructor & Destructor Documentation
SweepWidget()
SweepWidget::SweepWidget (QWidget * parent = nullptr)
References Gui::Command::App, Gui::ActionSelector::availableTreeWidget(), draftgeoutils.intersections::connect(), PartGui::Ui_TaskSweep::labelPath, Gui::ActionSelector::selectedTreeWidget(), PartGui::Ui_TaskSweep::selector, Gui::ActionSelector::setAvailableLabel(), Gui::ActionSelector::setSelectedLabel(), PartGui::Ui_TaskSweep::setupUi(), and PartGui::SweepWidget::Private::ui.
~SweepWidget()
SweepWidget::~SweepWidget ()
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
accept()
bool SweepWidget::accept (void)
References Gui::Command::App, PartGui::Ui_TaskSweep::buttonPath, PartGui::Ui_TaskSweep::checkFrenet, PartGui::Ui_TaskSweep::checkSolid, PartGui::SweepWidget::Private::document, Gui::Application::getDocument(), Gui::SelectionSingleton::getSelectionEx(), Part::Feature::getTopoShape(), App::PropertyString::getValue(), Gui::Application::Instance, Part::TopoShape::isNull(), App::DocumentObject::Label, draftutils.translate::QT_TRANSLATE_NOOP, Gui::ActionSelector::selectedTreeWidget(), Gui::Selection(), PartGui::Ui_TaskSweep::selector, and PartGui::SweepWidget::Private::ui.
Referenced by PartGui::TaskSweep::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
reject()
bool SweepWidget::reject (void)
References PartGui::Ui_TaskSweep::buttonPath, and PartGui::SweepWidget::Private::ui.
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), PartGui::TaskSweep::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/TaskSweep.h
FreeCAD/src/Mod/Part/Gui/TaskSweep.cpp