FreeCAD: FemGui::DlgSettingsFemZ88Imp Class Reference
FemGui::DlgSettingsFemZ88Imp Class Reference
#include <DlgSettingsFemZ88Imp.h>
Public Member Functions
DlgSettingsFemZ88Imp (QWidget *parent=nullptr)
~DlgSettingsFemZ88Imp ()
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Slots
void onfileNameChanged (QString FileName)
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void loadSettings ()
void saveSettings ()
virtual void changeEvent (QEvent *e)=0
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Constructor & Destructor Documentation
DlgSettingsFemZ88Imp()
DlgSettingsFemZ88Imp::DlgSettingsFemZ88Imp (QWidget * parent = nullptr)
References draftgeoutils.intersections::connect(), Gui::FileChooser::fileNameChanged(), and onfileNameChanged().
~DlgSettingsFemZ88Imp()
DlgSettingsFemZ88Imp::~DlgSettingsFemZ88Imp ()
Member Function Documentation
changeEvent()
void DlgSettingsFemZ88Imp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
loadSettings()
void DlgSettingsFemZ88Imp::loadSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), ParameterGrp::GetInt(), and App::Application::GetParameterGroupByPath().
onfileNameChanged
void DlgSettingsFemZ88Imp::onfileNameChanged (QString FileName) protected slot
Referenced by DlgSettingsFemZ88Imp().
saveSettings()
void DlgSettingsFemZ88Imp::saveSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetInt().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/DlgSettingsFemZ88Imp.h
FreeCAD/src/Mod/Fem/Gui/DlgSettingsFemZ88Imp.cpp