FreeCAD: GCS::ConstraintAngleViaPoint Class Reference
GCS::ConstraintAngleViaPoint Class Reference
#include <Constraints.h>
Public Member Functions
ConstraintAngleViaPoint (Curve &acrv1, Curve &acrv2, Point p, double *angle)
virtual double error ()
virtual ConstraintType getTypeId ()
virtual double grad (double *)
virtual void rescale (double coef=1.)
~ConstraintAngleViaPoint ()
Public Member Functions inherited from GCS::Constraint
Constraint ()
virtual double error ()
int findParamInPvec (double *param)
int getTag ()
virtual ConstraintType getTypeId ()
virtual double grad (double *)
bool isDriving () const
virtual double maxStep (MAP_pD_D &dir, double lim=1.)
VEC_pD params ()
void redirectParams (MAP_pD_pD redirectionmap)
virtual void rescale (double coef=1.)
void revertParams ()
void setDriving (bool isdriving)
void setTag (int tagId)
virtual ~Constraint ()
Constructor & Destructor Documentation
ConstraintAngleViaPoint()
GCS::ConstraintAngleViaPoint::ConstraintAngleViaPoint (Curve & acrv1, Curve & acrv2, Point p, double * angle)
References GCS::Curve::Copy(), GCS::Curve::PushOwnParams(), and rescale().
~ConstraintAngleViaPoint()
GCS::ConstraintAngleViaPoint::~ConstraintAngleViaPoint ()
Member Function Documentation
error()
double GCS::ConstraintAngleViaPoint::error () virtual
Reimplemented from GCS::Constraint.
References GCS::Curve::CalculateNormal(), GCS::DeriVector2::x, and GCS::DeriVector2::y.
Referenced by grad(), femmesh.gmshtools.GmshTools::read_and_set_new_mesh(), FreeCADInit.FCADLogger::report(), and femmesh.gmshtools.GmshTools::run_gmsh_with_geo().
getTypeId()
ConstraintType GCS::ConstraintAngleViaPoint::getTypeId (void) virtual
Reimplemented from GCS::Constraint.
References GCS::AngleViaPoint.
grad()
double GCS::ConstraintAngleViaPoint::grad (double * param) virtual
Reimplemented from GCS::Constraint.
References GCS::Curve::CalculateNormal(), GCS::DeriVector2::dx, GCS::DeriVector2::dy, error(), GCS::Constraint::findParamInPvec(), GCS::DeriVector2::length(), draftguitools.gui_annotationstyleeditor::param, GCS::DeriVector2::x, and GCS::DeriVector2::y.
rescale()
void GCS::ConstraintAngleViaPoint::rescale (double coef = 1.) virtual
Reimplemented from GCS::Constraint.
Referenced by ConstraintAngleViaPoint().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/App/planegcs/Constraints.h
FreeCAD/src/Mod/Sketcher/App/planegcs/Constraints.cpp