FreeCAD: PartGui::ViewProviderAttachExtension Class Reference
PartGui::ViewProviderAttachExtension Class Reference
#include <ViewProviderAttachExtension.h>
Public Member Functions
virtual QIcon extensionMergeColorfullOverlayIcons (const QIcon &orig) const override
virtual void extensionSetupContextMenu (QMenu *, QObject *, const char *) override
virtual void extensionUpdateData (const App::Property *) override
ViewProviderAttachExtension (void)
Constructor.
virtual ~ViewProviderAttachExtension ()=default
Public Member Functions inherited from Gui::ViewProviderExtension
virtual void extensionAttach (App::DocumentObject *)
virtual void extensionBeforeDelete ()
virtual bool extensionCanDragAndDropObject (App::DocumentObject *) const
virtual bool extensionCanDragObject (App::DocumentObject *) const
virtual bool extensionCanDragObjects () const
virtual bool extensionCanDropObject (App::DocumentObject *) const
virtual bool extensionCanDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const
virtual bool extensionCanDropObjects () const
virtual std::vector< App::DocumentObject * > extensionClaimChildren (void) const
virtual std::vector< App::DocumentObject * > extensionClaimChildren3D (void) const
virtual void extensionDragObject (App::DocumentObject *)
virtual void extensionDropObject (App::DocumentObject *)
virtual std::string extensionDropObjectEx (App::DocumentObject *obj, App::DocumentObject *, const char *, const std::vector< std::string > &)
virtual void extensionFinishRestoring ()
virtual SoSeparator * extensionGetBackRoot (void) const
virtual SoGroup * extensionGetChildRoot (void) const
virtual bool extensionGetDetailPath (const char *, SoFullPath *, SoDetail *&) const
virtual std::vector< std::string > extensionGetDisplayModes (void) const
virtual bool extensionGetElementPicked (const SoPickedPoint *, std::string &) const
virtual SoSeparator * extensionGetFrontRoot (void) const
virtual void extensionHide (void)
Hides the view provider.
virtual QIcon extensionMergeColorfullOverlayIcons (const QIcon &orig) const
virtual QIcon extensionMergeGreyableOverlayIcons (const QIcon &orig) const
virtual void extensionModeSwitchChange (void)
virtual bool extensionOnDelete (const std::vector< std::string > &)
virtual void extensionReattach (App::DocumentObject *)
virtual int extensionReplaceObject (App::DocumentObject *, App::DocumentObject *)
virtual void extensionSetDisplayMode (const char *)
virtual void extensionSetupContextMenu (QMenu *, QObject *, const char *)
virtual void extensionShow (void)
Shows the view provider.
virtual void extensionStartRestoring ()
virtual void extensionUpdateData (const App::Property *)
Gui::ViewProviderDocumentObject * getExtendedViewProvider ()
const Gui::ViewProviderDocumentObject * getExtendedViewProvider () const
virtual PyObject * getExtensionPyObject ()
bool ignoreOverlayIcon () const
void setIgnoreOverlayIcon (bool on)
ViewProviderExtension ()
virtual ~ViewProviderExtension ()
Public Member Functions inherited from App::Extension
Extension ()
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
virtual PyObject * getExtensionPyObject ()
virtual void initExtension (App::ExtensionContainer *obj)
bool isPythonExtension ()
std::string name () const
virtual ~Extension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Additional Inherited Members
Protected Member Functions inherited from App::Extension
virtual void extensionOnChanged (const Property *p)
void initExtensionType (Base::Type type)
Static Protected Member Functions inherited from App::Extension
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Constructor & Destructor Documentation
ViewProviderAttachExtension()
ViewProviderAttachExtension::ViewProviderAttachExtension (void)
Constructor.
~ViewProviderAttachExtension()
virtual PartGui::ViewProviderAttachExtension::~ViewProviderAttachExtension () virtual default
Member Function Documentation
extensionMergeColorfullOverlayIcons()
QIcon ViewProviderAttachExtension::extensionMergeColorfullOverlayIcons (const QIcon & orig) const override virtual
Reimplemented from Gui::ViewProviderExtension.
References Gui::BitmapFactoryInst::BottomLeft, Gui::ViewProviderExtension::getExtendedViewProvider(), App::ExtensionContainer::getExtensionByType(), Gui::ViewProviderDocumentObject::getObject(), and Gui::BitmapFactoryInst::mergePixmap().
extensionSetupContextMenu()
void ViewProviderAttachExtension::extensionSetupContextMenu (QMenu * menu, QObject * , const char *) override virtual
Reimplemented from Gui::ViewProviderExtension.
References draftgeoutils.faces::bind(), Gui::Control(), Gui::ViewProviderExtension::getExtendedViewProvider(), Gui::ViewProviderDocumentObject::getObject(), and App::ExtensionContainer::hasExtension().
extensionUpdateData()
void ViewProviderAttachExtension::extensionUpdateData (const App::Property * prop) override virtual
Reimplemented from Gui::ViewProviderExtension.
References Gui::ViewProviderExtension::getExtendedViewProvider(), App::ExtensionContainer::getExtensionByType(), Gui::ViewProviderDocumentObject::getObject(), and Gui::ViewProvider::signalChangeIcon.
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/ViewProviderAttachExtension.h
FreeCAD/src/Mod/Part/Gui/ViewProviderAttachExtension.cpp