FreeCAD: SurfaceGui::GeomFillSurface::EdgeSelection Class Reference
SurfaceGui::GeomFillSurface::EdgeSelection Class Reference
Public Member Functions
bool allow (App::Document *pDoc, App::DocumentObject *pObj, const char *sSubName)
Allow the user to pick only edges.
EdgeSelection (bool appendEdges, Surface::GeomFillSurface *editedObject)
Public Member Functions inherited from Gui::SelectionFilterGate
virtual bool allow (App::Document *, App::DocumentObject *, const char *)
SelectionFilterGate (const char *filter)
construct with the filter string
SelectionFilterGate (SelectionFilter *filter)
~SelectionFilterGate ()
Public Member Functions inherited from Gui::SelectionGate
virtual bool allow (App::Document *, App::DocumentObject *, const char *)=0
virtual ~SelectionGate ()
Additional Inherited Members
Public Attributes inherited from Gui::SelectionGate
std::string notAllowedReason
notAllowedReason is a string that sets the message to be displayed in statusbar for cluing the user on why is the selection not allowed.
Protected Member Functions inherited from Gui::SelectionFilterGate
SelectionFilterGate ()
Static Protected Member Functions inherited from Gui::SelectionFilterGate
static SelectionFilter * nullPointer ()
static const char * nullString ()
Protected Attributes inherited from Gui::SelectionFilterGate
SelectionFilter * Filter
Constructor & Destructor Documentation
EdgeSelection()
SurfaceGui::GeomFillSurface::EdgeSelection::EdgeSelection (bool appendEdges, Surface::GeomFillSurface * editedObject)
Member Function Documentation
allow()
bool SurfaceGui::GeomFillSurface::EdgeSelection::allow (App::Document * pDoc, App::DocumentObject * pObj, const char * sSubName) virtual
Allow the user to pick only edges.
Reimplemented from Gui::SelectionFilterGate.
References Surface::GeomFillSurface::BoundaryList, Base::Persistence::getClassTypeId(), App::PropertyLinkSubList::getSubListValues(), and Base::BaseClass::isDerivedFrom().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Surface/Gui/TaskGeomFillSurface.cpp