FreeCAD: FemGui::Ui_DlgSettingsFemInOutVtk Class Reference
FemGui::Ui_DlgSettingsFemInOutVtk Class Reference
#include <ui_DlgSettingsFemInOutVtk.h>
Public Member Functions
void retranslateUi (QWidget *FemGui__DlgSettingsFemInOutVtk)
void setupUi (QWidget *FemGui__DlgSettingsFemInOutVtk)
Public Attributes
Gui::PrefComboBox * comboBoxVtkImportObject
QGridLayout * girdLayout
QGridLayout * gridLayout_3
QGridLayout * gridLayout_4
QGroupBox * groupBox
QLabel * label1
QSpacerItem * verticalSpacer
Member Function Documentation
retranslateUi()
void FemGui::Ui_DlgSettingsFemInOutVtk::retranslateUi (QWidget * FemGui__DlgSettingsFemInOutVtk)
References comboBoxVtkImportObject, groupBox, label1, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), FemGui::DlgSettingsFemInOutVtkImp::changeEvent(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void FemGui::Ui_DlgSettingsFemInOutVtk::setupUi (QWidget * FemGui__DlgSettingsFemInOutVtk)
References comboBoxVtkImportObject, girdLayout, gridLayout_3, gridLayout_4, groupBox, label1, retranslateUi(), and verticalSpacer.
Referenced by FemGui::DlgSettingsFemInOutVtkImp::DlgSettingsFemInOutVtkImp().
Member Data Documentation
comboBoxVtkImportObject
Gui::PrefComboBox* FemGui::Ui_DlgSettingsFemInOutVtk::comboBoxVtkImportObject
Referenced by FemGui::DlgSettingsFemInOutVtkImp::changeEvent(), FemGui::DlgSettingsFemInOutVtkImp::loadSettings(), retranslateUi(), FemGui::DlgSettingsFemInOutVtkImp::saveSettings(), and setupUi().
girdLayout
QGridLayout* FemGui::Ui_DlgSettingsFemInOutVtk::girdLayout
Referenced by setupUi().
gridLayout_3
QGridLayout* FemGui::Ui_DlgSettingsFemInOutVtk::gridLayout_3
Referenced by setupUi().
gridLayout_4
QGridLayout* FemGui::Ui_DlgSettingsFemInOutVtk::gridLayout_4
Referenced by setupUi().
groupBox
QGroupBox* FemGui::Ui_DlgSettingsFemInOutVtk::groupBox
Referenced by retranslateUi(), and setupUi().
label1
QLabel* FemGui::Ui_DlgSettingsFemInOutVtk::label1
Referenced by retranslateUi(), and setupUi().
verticalSpacer
QSpacerItem* FemGui::Ui_DlgSettingsFemInOutVtk::verticalSpacer
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Fem/Gui/ui_DlgSettingsFemInOutVtk.h