FreeCAD: Mesh::FacetPy Class Reference
Mesh::FacetPy Class Reference
The python export class for Facet.
#include <FacetPy.h>
Public Types
typedef Facet * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
FacetPy (Facet *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of FacetPy.
static PyMethodDef Methods []
Methods structure of FacetPy.
static PyTypeObject Type
Type structure of FacetPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~FacetPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * unbound (PyObject *args)
implementer for the unbound() method
PyObject * intersect (PyObject *args)
implementer for the intersect() method
PyObject * isDegenerated (PyObject *args)
implementer for the isDegenerated() method
PyObject * isDeformed (PyObject *args)
implementer for the isDeformed() method
static PyObject * staticCallback_unbound (PyObject *self, PyObject *args)
callback for the unbound() method
static PyObject * staticCallback_intersect (PyObject *self, PyObject *args)
callback for the intersect() method
static PyObject * staticCallback_isDegenerated (PyObject *self, PyObject *args)
callback for the isDegenerated() method
static PyObject * staticCallback_isDeformed (PyObject *self, PyObject *args)
callback for the isDeformed() method
callbacks and implementers for the python object attributes
Py::Long getIndex (void) const
getter for the Index attribute
Py::Boolean getBound (void) const
getter for the Bound attribute
Py::Object getNormal (void) const
getter for the Normal attribute
Py::List getPoints (void) const
getter for the Points attribute
Py::Tuple getPointIndices (void) const
getter for the PointIndices attribute
Py::Tuple getNeighbourIndices (void) const
getter for the NeighbourIndices attribute
Py::Float getArea (void) const
getter for the Area attribute
Py::Float getAspectRatio (void) const
getter for the AspectRatio attribute
Py::Float getAspectRatio2 (void) const
getter for the AspectRatio2 attribute
Py::Float getRoundness (void) const
getter for the Roundness attribute
Py::Tuple getCircumCircle (void) const
getter for the CircumCircle attribute
Py::Tuple getInCircle (void) const
getter for the InCircle attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Facet * getFacetPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getIndex (PyObject *self, void *closure)
getter callback for the Index attribute
static int staticCallback_setIndex (PyObject *self, PyObject *value, void *closure)
setter callback for the Index attribute
static PyObject * staticCallback_getBound (PyObject *self, void *closure)
getter callback for the Bound attribute
static int staticCallback_setBound (PyObject *self, PyObject *value, void *closure)
setter callback for the Bound attribute
static PyObject * staticCallback_getNormal (PyObject *self, void *closure)
getter callback for the Normal attribute
static int staticCallback_setNormal (PyObject *self, PyObject *value, void *closure)
setter callback for the Normal attribute
static PyObject * staticCallback_getPoints (PyObject *self, void *closure)
getter callback for the Points attribute
static int staticCallback_setPoints (PyObject *self, PyObject *value, void *closure)
setter callback for the Points attribute
static PyObject * staticCallback_getPointIndices (PyObject *self, void *closure)
getter callback for the PointIndices attribute
static int staticCallback_setPointIndices (PyObject *self, PyObject *value, void *closure)
setter callback for the PointIndices attribute
static PyObject * staticCallback_getNeighbourIndices (PyObject *self, void *closure)
getter callback for the NeighbourIndices attribute
static int staticCallback_setNeighbourIndices (PyObject *self, PyObject *value, void *closure)
setter callback for the NeighbourIndices attribute
static PyObject * staticCallback_getArea (PyObject *self, void *closure)
getter callback for the Area attribute
static int staticCallback_setArea (PyObject *self, PyObject *value, void *closure)
setter callback for the Area attribute
static PyObject * staticCallback_getAspectRatio (PyObject *self, void *closure)
getter callback for the AspectRatio attribute
static int staticCallback_setAspectRatio (PyObject *self, PyObject *value, void *closure)
setter callback for the AspectRatio attribute
static PyObject * staticCallback_getAspectRatio2 (PyObject *self, void *closure)
getter callback for the AspectRatio2 attribute
static int staticCallback_setAspectRatio2 (PyObject *self, PyObject *value, void *closure)
setter callback for the AspectRatio2 attribute
static PyObject * staticCallback_getRoundness (PyObject *self, void *closure)
getter callback for the Roundness attribute
static int staticCallback_setRoundness (PyObject *self, PyObject *value, void *closure)
setter callback for the Roundness attribute
static PyObject * staticCallback_getCircumCircle (PyObject *self, void *closure)
getter callback for the CircumCircle attribute
static int staticCallback_setCircumCircle (PyObject *self, PyObject *value, void *closure)
setter callback for the CircumCircle attribute
static PyObject * staticCallback_getInCircle (PyObject *self, void *closure)
getter callback for the InCircle attribute
static int staticCallback_setInCircle (PyObject *self, PyObject *value, void *closure)
setter callback for the InCircle attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Facet.
Member Typedef Documentation
PointerType
typedef Facet* Mesh::FacetPy::PointerType
Constructor & Destructor Documentation
~FacetPy()
FacetPy::~FacetPy () protected
FacetPy()
FacetPy::FacetPy (Facet * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getArea()
Py::Float FacetPy::getArea (void) const
getter for the Area attribute
References MeshCore::MeshGeomFacet::Area(), MeshCore::MeshKernel::GetFacet(), getFacetPtr(), and Mesh::Facet::isBound().
Referenced by staticCallback_getArea().
getAspectRatio()
Py::Float FacetPy::getAspectRatio (void) const
getter for the AspectRatio attribute
References MeshCore::MeshGeomFacet::AspectRatio(), MeshCore::MeshKernel::GetFacet(), getFacetPtr(), and Mesh::Facet::isBound().
Referenced by staticCallback_getAspectRatio().
getAspectRatio2()
Py::Float FacetPy::getAspectRatio2 (void) const
getter for the AspectRatio2 attribute
References MeshCore::MeshGeomFacet::AspectRatio2(), MeshCore::MeshKernel::GetFacet(), getFacetPtr(), and Mesh::Facet::isBound().
Referenced by staticCallback_getAspectRatio2().
getBound()
Py::Boolean FacetPy::getBound (void) const
getter for the Bound attribute
References getFacetPtr().
Referenced by staticCallback_getBound().
getCircumCircle()
Py::Tuple FacetPy::getCircumCircle (void) const
getter for the CircumCircle attribute
References MeshCore::MeshGeomFacet::CenterOfCircumCircle(), MeshCore::MeshKernel::GetFacet(), getFacetPtr(), and Mesh::Facet::isBound().
Referenced by staticCallback_getCircumCircle().
getCustomAttributes()
PyObject * FacetPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getFacetPtr()
Facet * FacetPy::getFacetPtr (void) const
getter for the object handled by this class
Referenced by getArea(), getAspectRatio(), getAspectRatio2(), getBound(), getCircumCircle(), getInCircle(), getIndex(), getNeighbourIndices(), getNormal(), getPointIndices(), getPoints(), getRoundness(), intersect(), isDeformed(), isDegenerated(), representation(), and unbound().
getInCircle()
Py::Tuple FacetPy::getInCircle (void) const
getter for the InCircle attribute
References MeshCore::MeshGeomFacet::CenterOfInscribedCircle(), MeshCore::MeshKernel::GetFacet(), getFacetPtr(), and Mesh::Facet::isBound().
Referenced by staticCallback_getInCircle().
getIndex()
Py::Long FacetPy::getIndex (void) const
getter for the Index attribute
References getFacetPtr().
Referenced by staticCallback_getIndex().
getNeighbourIndices()
Py::Tuple FacetPy::getNeighbourIndices (void) const
getter for the NeighbourIndices attribute
References getFacetPtr(), and Mesh::Facet::isBound().
Referenced by staticCallback_getNeighbourIndices().
getNormal()
Py::Object FacetPy::getNormal (void) const
getter for the Normal attribute
References getFacetPtr(), and Base::PyObjectBase::setConst().
Referenced by staticCallback_getNormal().
getPointIndices()
Py::Tuple FacetPy::getPointIndices (void) const
getter for the PointIndices attribute
References getFacetPtr(), and Mesh::Facet::isBound().
Referenced by staticCallback_getPointIndices().
getPoints()
Py::List FacetPy::getPoints (void) const
getter for the Points attribute
References getFacetPtr().
Referenced by staticCallback_getPoints().
getRoundness()
Py::Float FacetPy::getRoundness (void) const
getter for the Roundness attribute
References MeshCore::MeshKernel::GetFacet(), getFacetPtr(), Mesh::Facet::isBound(), and MeshCore::MeshGeomFacet::Roundness().
Referenced by staticCallback_getRoundness().
GetType()
virtual PyTypeObject* Mesh::FacetPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
intersect()
PyObject * FacetPy::intersect (PyObject * args)
implementer for the intersect() method
References getFacetPtr(), MeshCore::MeshGeomFacet::IntersectWithFacet(), Type, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by staticCallback_intersect().
isDeformed()
PyObject * FacetPy::isDeformed (PyObject * args)
implementer for the isDeformed() method
References MeshCore::MeshKernel::GetFacet(), getFacetPtr(), Mesh::Facet::isBound(), and MeshCore::MeshGeomFacet::IsDeformed().
Referenced by staticCallback_isDeformed().
isDegenerated()
PyObject * FacetPy::isDegenerated (PyObject * args)
implementer for the isDegenerated() method
References MeshCore::MeshKernel::GetFacet(), getFacetPtr(), Mesh::Facet::isBound(), and MeshCore::MeshGeomFacet::IsDegenerated().
Referenced by staticCallback_isDegenerated().
PyInit()
int FacetPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
PyMake()
PyObject * FacetPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References FacetPy().
representation()
std::string FacetPy::representation (void) const
References getFacetPtr(), Mesh::Facet::Index, Mesh::Facet::isBound(), Mesh::Facet::NIndex, and Mesh::Facet::PIndex.
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int FacetPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_getArea()
PyObject * FacetPy::staticCallback_getArea (PyObject * self, void * closure) static
getter callback for the Area attribute
References Base::BaseExceptionFreeCADError, getArea(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getAspectRatio()
PyObject * FacetPy::staticCallback_getAspectRatio (PyObject * self, void * closure) static
getter callback for the AspectRatio attribute
References Base::BaseExceptionFreeCADError, getAspectRatio(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getAspectRatio2()
PyObject * FacetPy::staticCallback_getAspectRatio2 (PyObject * self, void * closure) static
getter callback for the AspectRatio2 attribute
References Base::BaseExceptionFreeCADError, getAspectRatio2(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getBound()
PyObject * FacetPy::staticCallback_getBound (PyObject * self, void * closure) static
getter callback for the Bound attribute
References Base::BaseExceptionFreeCADError, getBound(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCircumCircle()
PyObject * FacetPy::staticCallback_getCircumCircle (PyObject * self, void * closure) static
getter callback for the CircumCircle attribute
References Base::BaseExceptionFreeCADError, getCircumCircle(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getInCircle()
PyObject * FacetPy::staticCallback_getInCircle (PyObject * self, void * closure) static
getter callback for the InCircle attribute
References Base::BaseExceptionFreeCADError, getInCircle(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getIndex()
PyObject * FacetPy::staticCallback_getIndex (PyObject * self, void * closure) static
getter callback for the Index attribute
References Base::BaseExceptionFreeCADError, getIndex(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNeighbourIndices()
PyObject * FacetPy::staticCallback_getNeighbourIndices (PyObject * self, void * closure) static
getter callback for the NeighbourIndices attribute
References Base::BaseExceptionFreeCADError, getNeighbourIndices(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNormal()
PyObject * FacetPy::staticCallback_getNormal (PyObject * self, void * closure) static
getter callback for the Normal attribute
References Base::BaseExceptionFreeCADError, getNormal(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPointIndices()
PyObject * FacetPy::staticCallback_getPointIndices (PyObject * self, void * closure) static
getter callback for the PointIndices attribute
References Base::BaseExceptionFreeCADError, getPointIndices(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPoints()
PyObject * FacetPy::staticCallback_getPoints (PyObject * self, void * closure) static
getter callback for the Points attribute
References Base::BaseExceptionFreeCADError, getPoints(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRoundness()
PyObject * FacetPy::staticCallback_getRoundness (PyObject * self, void * closure) static
getter callback for the Roundness attribute
References Base::BaseExceptionFreeCADError, getRoundness(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_intersect()
PyObject * FacetPy::staticCallback_intersect (PyObject * self, PyObject * args) static
callback for the intersect() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, intersect(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_isDeformed()
PyObject * FacetPy::staticCallback_isDeformed (PyObject * self, PyObject * args) static
callback for the isDeformed() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), isDeformed(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_isDegenerated()
PyObject * FacetPy::staticCallback_isDegenerated (PyObject * self, PyObject * args) static
callback for the isDegenerated() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), isDegenerated(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_setArea()
int FacetPy::staticCallback_setArea (PyObject * self, PyObject * value, void * closure) static
setter callback for the Area attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setAspectRatio()
int FacetPy::staticCallback_setAspectRatio (PyObject * self, PyObject * value, void * closure) static
setter callback for the AspectRatio attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setAspectRatio2()
int FacetPy::staticCallback_setAspectRatio2 (PyObject * self, PyObject * value, void * closure) static
setter callback for the AspectRatio2 attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setBound()
int FacetPy::staticCallback_setBound (PyObject * self, PyObject * value, void * closure) static
setter callback for the Bound attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setCircumCircle()
int FacetPy::staticCallback_setCircumCircle (PyObject * self, PyObject * value, void * closure) static
setter callback for the CircumCircle attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setInCircle()
int FacetPy::staticCallback_setInCircle (PyObject * self, PyObject * value, void * closure) static
setter callback for the InCircle attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setIndex()
int FacetPy::staticCallback_setIndex (PyObject * self, PyObject * value, void * closure) static
setter callback for the Index attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setNeighbourIndices()
int FacetPy::staticCallback_setNeighbourIndices (PyObject * self, PyObject * value, void * closure) static
setter callback for the NeighbourIndices attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setNormal()
int FacetPy::staticCallback_setNormal (PyObject * self, PyObject * value, void * closure) static
setter callback for the Normal attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPointIndices()
int FacetPy::staticCallback_setPointIndices (PyObject * self, PyObject * value, void * closure) static
setter callback for the PointIndices attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPoints()
int FacetPy::staticCallback_setPoints (PyObject * self, PyObject * value, void * closure) static
setter callback for the Points attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setRoundness()
int FacetPy::staticCallback_setRoundness (PyObject * self, PyObject * value, void * closure) static
setter callback for the Roundness attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_unbound()
PyObject * FacetPy::staticCallback_unbound (PyObject * self, PyObject * args) static
callback for the unbound() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and unbound().
unbound()
PyObject * FacetPy::unbound (PyObject * args)
implementer for the unbound() method
References getFacetPtr(), Mesh::Facet::Index, and Mesh::Facet::Mesh.
Referenced by staticCallback_unbound().
Member Data Documentation
GetterSetter
PyGetSetDef FacetPy::GetterSetter static
Attribute structure of FacetPy.
Methods
PyMethodDef FacetPy::Methods static
Initial value:
= {
    {"unbound",
        reinterpret_cast<PyCFunction>( staticCallback_unbound ),
        METH_VARARGS,
        "method unbound()\nCut the connection to a MeshObject. The facet becomes\nfree and is more or less a simple facet.\nAfter calling unbound() no topological operation will\nwork!\n                        "
    },
    {"intersect",
        reinterpret_cast<PyCFunction>( staticCallback_intersect ),
        METH_VARARGS,
        "intersect(Facet) -> list \nGet a list of intersection points with another triangle.\n                    "
    },
    {"isDegenerated",
        reinterpret_cast<PyCFunction>( staticCallback_isDegenerated ),
        METH_VARARGS,
        "isDegenerated([float]) -> boolean\nReturns true if the facet is degenerated, otherwise false.\n              "
    },
    {"isDeformed",
        reinterpret_cast<PyCFunction>( staticCallback_isDeformed ),
        METH_VARARGS,
        "isDegenerated(MinAngle, MaxAngle) -> boolean\nReturns true if the facet is deformed, otherwise false.\nA triangle is considered deformed if an angle is less than MinAngle\nor higher than MaxAngle.\nThe two angles are given in radian.\n              "
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of FacetPy.
Type
PyTypeObject FacetPy::Type static
Type structure of FacetPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), Mesh::MeshPy::addFacet(), Mesh::MeshPy::addFacets(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), intersect(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Mesh/App/FacetPy.h
Sources/FreeCAD/src/Mod/Mesh/App/FacetPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Mesh/App/FacetPy.cpp