FreeCAD: ModelRefine Namespace Reference
ModelRefine Namespace Reference
Classes
class FaceAdjacencySplitter
class FaceEqualitySplitter
class FaceTypedBase
class FaceTypedBSpline
class FaceTypedCylinder
class FaceTypedPlane
class FaceTypeSplitter
class FaceUniter
class WireSort
Typedefs
typedef std::vector< TopoDS_Edge > EdgeVectorType
typedef std::vector< TopoDS_Face > FaceVectorType
typedef std::pair< TopoDS_Shape, TopoDS_Shape > ShapePairType
typedef std::vector< TopoDS_Shape > ShapeVectorType
Functions
void boundaryEdges (const FaceVectorType &faces, EdgeVectorType &edgesOut)
FaceTypedBSpline & getBSplineObject ()
FaceTypedCylinder & getCylinderObject ()
void getFaceEdges (const TopoDS_Face &face, EdgeVectorType &edges)
FaceTypedPlane & getPlaneObject ()
TopoDS_Shell removeFaces (const TopoDS_Shell &shell, const FaceVectorType &faces)
Typedef Documentation
EdgeVectorType
typedef std::vector<TopoDS_Edge> ModelRefine::EdgeVectorType
FaceVectorType
typedef std::vector<TopoDS_Face> ModelRefine::FaceVectorType
ShapePairType
typedef std::pair<TopoDS_Shape, TopoDS_Shape> ModelRefine::ShapePairType
ShapeVectorType
typedef std::vector<TopoDS_Shape> ModelRefine::ShapeVectorType
Function Documentation
boundaryEdges()
void ModelRefine::boundaryEdges (const FaceVectorType & faces, EdgeVectorType & edgesOut)
References getFaceEdges().
Referenced by ModelRefine::FaceTypedBase::boundarySplit(), and ModelRefine::FaceTypedCylinder::boundarySplit().
getBSplineObject()
FaceTypedBSpline & ModelRefine::getBSplineObject ()
Referenced by ModelRefine::FaceUniter::process().
getCylinderObject()
FaceTypedCylinder & ModelRefine::getCylinderObject ()
Referenced by ModelRefine::FaceUniter::process().
getFaceEdges()
void ModelRefine::getFaceEdges (const TopoDS_Face & face, EdgeVectorType & edges)
Referenced by boundaryEdges().
getPlaneObject()
FaceTypedPlane & ModelRefine::getPlaneObject ()
Referenced by ModelRefine::FaceUniter::process().
removeFaces()
TopoDS_Shell ModelRefine::removeFaces (const TopoDS_Shell & shell, const FaceVectorType & faces)
Referenced by ModelRefine::FaceUniter::process().