FreeCAD: Gui Namespace Reference
Gui Namespace Reference
The FreeCAD Graphical interface layer.
Namespaces
DAG
Dialog
The namespace of the FreeCAD dialogs.
DockWnd
The namespace of the dockable windows of FreeCAD.
Inventor
NS
PropertyEditor
The namespace of the property editor for FreeCAD.
TaskView
Classes
class AbstractMouseSelection
The mouse selection base class In derived classes you must implement the methods initialize() and terminate() For all drawing stuff you just have to reimplement the draw() method.
class AbstractSplitView
The SplitView3DInventor class allows to create a window with two or more Inventor views.
class AbstractSplitViewPy
class AbstractUi
The AbstractUi class Abstract base class the defines the class interface.
class AccelLineEdit
The AccelLineEdit class provides a lineedit to specfify shortcuts.
class Action
The Action class is the link between Qt's QAction class and FreeCAD's command classes (Command).
class ActionFunction
class ActionFunctionPrivate
class ActionGroup
The ActionGroup class is the link between Qt's QActionGroup class and FreeCAD's command classes (Command).
class ActionSelector
class ActionStyleEvent
This is a helper class needed when a style sheet is restored or cleared.
class ActiveObjectList
List of active or special objects This class holds a list of objects with a special name.
class AlignmentGroup
The AlignemntGroup class is the base for fixed and movable groups.
class AlignmentView
class Application
The Application main class This is the central class of the GUI.
class ApplicationIndex
struct ApplicationP
class Assistant
class AutoSaveProperty
class AutoSaver
class AxisOrigin
A class to create a Coin3D node representation of an coordinate system.
class AxisOriginPy
The python export class for AxisOrigin.
class BaseMouseSelection
The standard mouse selection class.
class BaseView
Base class of all windows belonging to a document there are two ways of belonging to a document.
class BitmapFactoryInst
class BitmapFactoryInstP
class BlankWorkbench
The BlankWorkbench class defines a complete empty workbench.
class BlenderNavigationStyle
class BoxZoomSelection
The box zoom mouse model class Draws a rectangle for box zooming.
class Breakpoint
class CADNavigationStyle
class CallTip
class CallTipsList
class Camera
class CameraAnimation
class CheckListDialog
The CheckListDialog class provides a dialog with a QListView with checkable items inside.
class ClearLineEdit
The ClearLineEdit class adds a clear button at the right side.
class CoinPtr
Convenience smart pointer to wrap coin node.
class ColorButton
Implementation of a color button.
struct ColorButtonP
class Command
The Command class.
class CommandBase
The CommandBase class This lightweight class is the base class of all commands in FreeCAD.
class CommandIconView
This class allows to drag one or more items which correspond to a Command object.
class CommandManager
The CommandManager class This class manage all available commands in FreeCAD.
class CommandPy
The python export class for Command.
class CompletionList
The CompletionList class provides a list box that pops up in a text edit if the user has pressed an accelerator to complete the current word he is typing in.
class ConsoleErrorTask
class ConsoleHistory
This class implements the history for the Python console.
class ConsoleLogTask
class ConsoleMessageTask
class ConsoleWarningTask
class ContainerDialog
The ContainerDialog class acts as a container to embed any kinds of widgets that do not inherit from QDialog.
class ControlSingleton
The control class.
class CustomMessageEvent
The CustomMessageEvent class is used to send messages as events in the methods Error(), Warning() and Message() of the StatusBarObserver class to the main window to display them on the status bar instead of printing them directly to the status bar.
class CustomPageProducer
The CustomPageProducer class is a value-based template class that provides the ability to create custom pages dynamically.
class DlgObjectSelection
class DockWidgetAction
Special action to show all dockable views – except of toolbars – in an own popup menu.
class DockWindow
Base class of all dockable windows belonging to a document there are two ways of belonging to a document.
struct DockWindowItem
class DockWindowItems
class DockWindowManager
Class that manages the widgets inside a QDockWidget.
struct DockWindowManagerP
class Document
The Gui Document This is the document on GUI level.
class DocumentIndex
class DocumentItem
The link between the tree and a document.
class DocumentModel
class DocumentModelIndex
struct DocumentModelP
class DocumentObjectData
class DocumentObjectItem
The link between the tree and a document object.
class DocumentObserver
The DocumentObserver class simplifies the step to write classes that listen to what happens inside a document.
class DocumentObserverPython
The DocumentObserverPython class is used to notify registered Python instances whenever something happens to a document, like creation, destruction, adding or removing viewproviders or when viewprovider property changes.
struct DocumentP
class DocumentPy
The python export class for Document.
class DocumentT
The DocumentT class is a helper class to store the name of a document.
class DocumentWeakPtrT
The DocumentWeakPtrT class.
class DoubleSpinBox
The DoubleSpinBox class does exactly the same as Qt's QDoubleSpinBox but has expression support.
class EditorView
A special view class which sends the messages from the application to the editor and embeds it in a window.
class EditorViewP
class ElementColors
class ExpLineEdit
The ExpLineEdit class provides a lineedit that support expressing binding.
class ExpressionBinding
class ExpressionBindingPy
class ExpressionCompleter
The ExpressionCompleter class extends the QCompleter class to provide a completer model of documentobject names and properties.
class ExpressionLineEdit
class ExpressionParameter
class ExpressionTextEdit
class FileChooser
The FileChooser class provides a lineedit with a button on the right side to specify a file or directory.
class FileDialog
The FileDialog class provides dialogs that allow users to select files or directories.
class FileIconProvider
The FileIconProvider class provides icons for FileDialog to use.
class FileOptionsDialog
The FileOptionsDialog class provides an extensible file dialog with an additional widget either at the right or at the bottom, that can be shown or hidden with the 'Extended' button.
class FixedGroup
The FixedGroup class can be used for a fixed group of views.
class Flag
class FlagLayout
class FormatString
class FreehandSelection
The freehand selection class.
class GestureNavigationStyle
class GLFlagWindow
class GLGraphicsItem
class GLOverlayWidget
class GLPainter
class GraphicsScene
class GraphicsView
class GraphicsView3D
class GraphvizView
class GraphvizWorker
The GraphvizWorker class.
class GroupCommand
Class to help implement a group command.
class GuiAbstractNativeEvent
class GUIApplication
Override QCoreApplication::notify() to fetch exceptions in Qt widgets properly that are not handled in the event handler or slot.
class GUIApplicationNativeEventAware
class GUIConsole
The console window class This class opens a console window when instantiated and redirects the stdio streams to it as long it exists.
class GuiNativeEvent
class GUISingleApplication
class HttpServer
The HttpServer class implements a simple HTTP server.
class InputField
The InputField class The input field widget handles all around user input of Quantities.
class InputValidator
class InteractiveInterpreter
This class implements an interactive Python interpreter.
struct InteractiveInterpreterP
class IntSpinBox
The IntSpinBox class does exactly the same as Qt's QSpinBox but has expression support.
class InventorNavigationStyle
class ItemViewSelection
class LabelButton
The LabelButton class provides a label with a button on the right side.
class LabelEditor
class LineMarker
class LinkInfo
class LinkOwner
class LinkView
class LinkViewPy
The python export class for LinkView.
class LocationDialog
This is the abstract base dialog class that defines the interface for specifying a direction vector by the user.
class LocationDialogImp
This template class is a subclass of LocationDialog using LocationUi and implements the pure virtual methods of its base class.
class LocationDialogUi
This is the template class that implements the interface of LocationDialog.
class LocationDialogUiImp
This is a subclass of LocationDialog using AbstractUi that implements the pure virtual methods of its base class.
class LocationImpUi
This is the template class that implements the interface of AbstractUi.
class LocationUi
This template class does basically the same as LocationDialogUi unless that it doesn inherit from a widget but only from the UI_-generated class.
class LocationWidget
class MacroCommand
The script command class This is a special type of command class.
class MacroManager
Macro recording and play back management The purpos of this class is to handle record function calls from a command and save it in a macro file (so far).
class MainWindow
The MainWindow class provides a main window with menu bar, toolbars, dockable windows, a status bar and mainly a workspace for the MDI windows.
struct MainWindowP
class ManualAlignment
class MayaGestureNavigationStyle
class MDITabbar
class MDIView
Base class of all windows belonging to a document.
class MDIViewPy
class MenuItem
class MenuManager
The MenuManager class is responsible for the creation of menus and context menus and appending them to the main window.
class MergeDocuments
class MovableGroup
The FixedGroup class can be used for a fixed group of views.
class MovableGroupModel
The MovableGroupModel class keeps an array of movable groups.
class NavigationStyle
The navigation style base class.
class NavigationStyleEvent
struct NavigationStyleP
class NetworkRetriever
The NetworkRetriever class encapsulates the GNU tool wget.
struct NetworkRetrieverP
struct Node_Block
struct Node_Object
struct Node_Slice
class NoneWorkbench
The NoneWorkbench class defines a slim workbench.
class OpenCascadeNavigationStyle
class OpenGLBuffer
class OpenGLMultiBuffer
class OutputStderr
Python class for redirection of stderr to FreeCAD's output console window.
class OutputStdout
Python class for redirection of stdout to FreeCAD's output console window.
class PickedPoint
class PointMarker
class PolyClipSelection
The poly clip mouse model class Create a polygon.
class Polyline
class PolyPickerSelection
The poly picker mouse selection class Create a polygon.
class PrefCheckBox
The PrefCheckBox class.
class PrefColorButton
The PrefColorButton class.
class PrefComboBox
The PrefComboBox class.
class PrefDoubleSpinBox
The PrefDoubleSpinBox class.
class PrefFileChooser
The PrefFileChooser class.
class PrefFontBox
The PrefFontBox class.
class PrefLineEdit
The PrefLineEdit class.
class PrefPageProducer
The PrefPageProducer class is a value-based template class that provides the ability to create preference pages dynamically.
class PrefPagePyProducer
The PrefPagePyProducer class provides the ability to create preference pages dynamically from a Python class.
class PrefPageUiProducer
The PrefPageUiProducer class provides the ability to create preference pages dynamically from an external UI file.
class PrefQuantitySpinBox
The PrefQuantitySpinBox class.
class PrefQuantitySpinBoxPrivate
class PrefRadioButton
The PrefRadioButton class.
class PrefSlider
The PrefSlider class.
class PrefSpinBox
The PrefSpinBox class.
class PrefUnitSpinBox
The PrefUnitSpinBox class.
class PrefWidget
The preference widget class.
class ProgressBar
struct ProgressBarPrivate
class ProgressDialog
class ProjectWidget
Tree view that allows drag & drop of document objects.
class PropertyListEditor
class PropertyView
The property view class.
class PyResource
The PyResource class provides an interface to create widgets or to load .ui files from Python.
class PySideUicModule
class PythonBaseWorkbench
The PythonBaseWorkbench class allows the manipulation of the workbench from Python.
class PythonBlankWorkbench
class PythonCommand
The Python command class This is a special type of command class.
class PythonConsole
class PythonConsoleHighlighter
Syntax highlighter for Python console.
struct PythonConsoleP
class PythonDebugExcept
class PythonDebugger
struct PythonDebuggerP
class PythonDebuggerPy
class PythonDebugModule
class PythonDebugStderr
class PythonDebugStdout
class PythonEditor
Python text editor with syntax highlighting.
struct PythonEditorP
class PythonEditorView
class PythonGroupCommand
The Python group command class.
class PythonOnlineHelp
Returns the content of an HTML page which gets sent to the client to be displayed.
class PythonRedirector
class PythonStderr
Python class for redirection of stderr to FreeCAD's Python console window.
class PythonStdin
Python class for redirection of stdin to an input dialog of Qt.
class PythonStdout
Python class for redirection of stdout to FreeCAD's Python console window.
class PythonSyntaxHighlighter
Syntax highlighter for Python.
class PythonSyntaxHighlighterP
class PythonWorkbench
The PythonWorkbench class allows the manipulation of the workbench from Python.
class PythonWorkbenchPy
The python export class for PythonBaseWorkbench.
class PythonWrapper
class QtTools
The QtTools class Helper class to reduce adding a lot of extra QT_VERSION checks to client code.
class QuantitySpinBox
class QuantitySpinBoxPrivate
class RawInputEventFilter
class RDragger
Rotation Dragger.
class RecentFilesAction
The RecentFilesAction class holds a menu listed with the recent files.
class RecentMacrosAction
The RecentMacrosAction class holds a menu listed with the recent macros that were executed, edited, or created.
class RecoveryRunnable
class RecoveryWriter
class RectangleSelection
The selection mouse model class Draws a rectangle for selection.
class RedoAction
The RedoAction class reimplements a special behaviour to make a menu appearing when the button with the arrow is clicked.
class RevitNavigationStyle
class Rubberband
class RubberbandSelection
The selection mouse model class Draws a rectangle for selection.
class RunningState
class SceneEventFilter
class SelectionChanges
Transport the changes of the Selection This class transports closer information what was changed in the selection.
class SelectionFilter
Selection filter definition This class builds up a type/count tree out of a string to test very fast a selection or object/subelement type against it.
class SelectionFilterGate
Filter object for the SelectionSengleton This object is a link between the selection filter class and the selection singleton.
class SelectionFilterGatePython
A Python wrapper around SelectionFilterPy to implement the SelectionGate interface.
class SelectionFilterPy
Python binding for SelectionFilter class.
class SelectionGate
SelectionGate The selection gate allows or disallows selection of certain types.
class SelectionGateFilterExternal
SelectionGateFilterExternal The selection gate disallows any external object.
class SelectionGatePython
A wrapper around a Python class that implements the SelectionGate interface.
class SelectionLogDisabler
Helper class to disable logging selection action to MacroManager.
class SelectionObject
The Selection object class.
class SelectionObjectPy
The python export class for SelectionObject.
class SelectionObserver
The SelectionObserver class simplifies the step to write classes that listen to what happens to the selection.
class SelectionObserverPython
The SelectionObserverPython class implements a mechanism to register a Python class instance implementing the required interface in order to be notified on selection changes.
class SelectionSingleton
The Selection class The selection singleton keeps track of the selection state of the whole application.
class SelectModule
The SelectModule class provides a list of radio buttons to choose the module that should handle a certain file type.
class SequencerBar
FreeCAD's progress bar for long operations To see how to use the progress bar have a look at the following examples:
struct SequencerBarPrivate
class SequencerDialog
struct SequencerDialogPrivate
class SignalConnect
The SignalConnect class provides the abitlity to make a connection between the callback function of a Python object and the slot onExecute().
class SoAutoZoomTranslation
class SoAxisCrossKit
class SoBoxSelectionRenderAction
The SoBoxSelectionRenderAction class renders the scene with highlighted boxes around selections.
class SoBoxSelectionRenderActionP
class SoFCBackgroundGradient
class SoFCBoundingBox
A subclass of SoShape used to create an axis aligned wire frame box based on the minBounds and maxBounds fields.
class SoFCColorBar
The color bar class that redirects all calls to its handled color bars.
class SoFCColorBarBase
The abstract color bar base class to get most important information on how to convert a scalar to an RGB color.
class SoFCColorBarProxyObject
class SoFCColorGradient
class SoFCColorLegend
class SoFCCSysDragger
Coordinate System Dragger.
class SoFCDB
The FreeCAD database class to initialize all our own Inventor nodes.
class SoFCDocumentAction
The SoFCDocumentAction class is used to inform an SoFCSelection node when a document has been renamed.
class SoFCDocumentObjectAction
The SoFCDocumentObjectAction class is used to get the name of the document, object and component at a certain position of an SoFCSelection node.
class SoFCEnableHighlightAction
The SoFCEnableHighlightAction class is used to inform an SoFCSelection node whether preselection is enabled or disabled.
class SoFCEnableSelectionAction
The SoFCEnableSelectionAction class is used to inform an SoFCSelection node whether selection is enabled or disabled.
class SoFCHighlightAction
The SoFCHighlightAction class is used to inform an SoFCSelection node whether an object gets highlighted.
class SoFCHighlightColorAction
The SoFCHighlightColorAction class is used to inform an SoFCSelection node which preselection color is used.
class SoFCInteractiveElement
class SoFCOffscreenRenderer
The SoFCOffscreenRenderer class is used for rendering scenes in offscreen buffers.
class SoFCPathAnnotation
class SoFCSelection
Selection node This node does the complete highlighting and selection together with the viewer.
class SoFCSelectionAction
The SoFCSelectionAction class is used to inform an SoFCSelection node whether an object gets selected.
class SoFCSelectionColorAction
The SoFCSelectionColorAction class is used to inform an SoFCSelection node which selection color is used.
struct SoFCSelectionContext
struct SoFCSelectionContextBase
struct SoFCSelectionContextEx
class SoFCSelectionCounter
class SoFCSelectionRoot
class SoFCSeparator
class SoFCUnifiedSelection
Unified Selection node This is the new selection node for the 3D Viewer which will gradually remove all the low level selection nodes in the view provider.
class SoFCVectorizeSVGAction
class SoFCVectorizeSVGActionP
class SoFCVectorizeU3DAction
class SoFCVectorizeU3DActionP
class SoFrameLabel
class SoGLRenderActionElement
class SoGLSelectAction
The SoGLSelectAction class is used to get all data under a selected area.
class SoGLVBOActivatedElement
class SoGLWidgetElement
class SoGLWidgetNode
class SoHighlightElementAction
class SoQtOffscreenRenderer
class SoRegPoint
class SoSelectionElementAction
class SoShapeScale
class SoSkipBoundingGroup
This is a special group node which must be defined to ignore bounding box actions.
class SoStringLabel
class SoSVGVectorOutput
class SoTextLabel
A text label with a background color.
class SoU3DVectorOutput
class SoUpdateVBOAction
Helper class no notify nodes to update VBO.
class SoVisibleFaceAction
class SoVRMLAction
class SplashObserver
Displays all messages at startup inside the splash screen.
class SplashScreen
This widget provides a splash screen that can be shown during application startup.
class SplitView3DInventor
The SplitView3DInventor class allows to create a window with two or more Inventor views.
class StatusBarObserver
The status bar observer displays the text on the status bar of the main window in an appropriate color.
class StatusWidget
class StdCmdDescription
class StdCmdDownloadOnlineHelp
class StdCmdPythonHelp
class StdWorkbench
The StdWorkbench class defines the standard menus, toolbars, commandbars etc.
class SyntaxHighlighter
Abstract Syntax highlighter.
class SyntaxHighlighterP
class TaskBoxAngle
class TaskBoxPosition
class TaskCSysDragger
class TaskDlgRelocation
class TaskElementColors
class TDragger
Translation Dragger.
class Tessellator
class TestConsoleObserver
class TestWorkbench
struct TextBlockData
class TextDocumentEditorView
class TextEdit
class TextEditor
struct TextEditorP
class Thumbnail
class TimerFunction
class TimerFunctionPrivate
class ToolBarAction
Special action to show all toolbars in an own popup menu.
class ToolBarItem
class ToolBarManager
The ToolBarManager class is responsible for the creation of toolbars and appending them to the main window.
class ToolBoxManager
The ToolBoxManager class is responsible for the creation of command bars and appending them to the toolbox window.
class ToolTip
Qt's tooltip does not work as expected with some classes, e.g.
class TouchpadNavigationStyle
class TransactionViewProvider
class TranslateManip
class Translator
class TranslatorP
class TreeDockWidget
The dock window containing the tree view.
class TreePanel
class TreeParams
Helper class to read/write tree view options.
class TreeView
class TreeWidget
Tree view that allows drag & drop of document objects.
class TreeWidgetEditDelegate
TreeWidget item delegate for editing.
class UiLoader
The UiLoader class provides the abitlity to use the widget factory framework of FreeCAD within the framework provided by Qt.
class UiLoaderPy
class UIntSpinBox
The UIntSpinBox class does basically the same as Qt's QSpinBox unless that it works with unsigned int's instead.
class UIntSpinBoxPrivate
class UndoAction
The UndoAction class reimplements a special behaviour to make a menu appearing when the button with the arrow is clicked.
class UnsignedValidator
A validator that allows only input of unsigned int values in the range from 0 to UINT_MAX.
class UrlHandler
class UrlLabel
A text label where a url can specified.
class UserNavigationStyle
Sub-classes of this class appear in the preference dialog where users can choose their favorite navigation style.
class VectorListEditor
class VectorTableDelegate
class VectorTableModel
class View3DInventor
The 3D view window It consists out of the 3D view.
class View3DInventorPy
class View3DInventorViewer
GUI view into a 3D scene provided by View3DInventor.
class View3DInventorViewerPy
Python interface for View3DInventorViewer.
class ViewerEventFilter
class ViewParams
Convenient class to obtain view provider related parameters.
class ViewProvider
General interface for all visual stuff in FreeCAD This class is used to generate and handle all around visualizing and presenting objects from the FreeCAD App layer to the user.
class ViewProviderAnnotation
class ViewProviderAnnotationLabel
This is a different implementation of an annotation object which uses an SoImage node instead of an SoText2 or SoAsciiText node.
class ViewProviderBuilder
class ViewProviderColorBuilder
class ViewProviderDocumentObject
class ViewProviderDocumentObjectGroup
class ViewProviderDocumentObjectPy
The python export class for ViewProviderDocumentObject.
class ViewProviderDragger
The base class for all view providers modifying the placement of a geometric feature.
class ViewProviderExtension
Extension with special viewprovider calls.
class ViewProviderExtensionPy
The python export class for ViewProviderExtension.
class ViewProviderExtensionPythonT
Generic Python extension class which allows to behave every extension derived class as Python extension – simply by subclassing.
class ViewProviderExtern
class ViewProviderFeature
class ViewProviderGeoFeatureGroup
class ViewProviderGeoFeatureGroupExtension
class ViewProviderGeometryObject
The base class for all view providers that display geometric data, like mesh, point clouds and shapes.
class ViewProviderGroupExtension
class ViewProviderIndex
class ViewProviderInventorObject
class ViewProviderLine
class ViewProviderLink
class ViewProviderLinkObserver
class ViewProviderLinkPy
The python export class for ViewProviderLink.
class ViewProviderMaterialObject
class ViewProviderMeasureDistance
class ViewProviderOrigin
class ViewProviderOriginFeature
View provider associated with an App::OriginFeature.
class ViewProviderOriginGroup
class ViewProviderOriginGroupExtension
class ViewProviderPart
class ViewProviderPlacement
class ViewProviderPlane
class ViewProviderPointMarker
class ViewProviderPy
The python export class for ViewProvider.
class ViewProviderPythonFeatureImp
class ViewProviderPythonFeatureT
class ViewProviderT
The ViewProviderT class is a helper class to store the names of a view provider and its document.
class ViewProviderTextDocument
class ViewProviderVRMLObject
class ViewProviderWeakPtrT
The ViewProviderWeakPtrT class.
class ViewVolumeProjection
class WaitCursor
This class sets a waitcursor automatically while a slow operation is running.
class WaitCursorP
class WheelEventFilter
class WidgetFactoryInst
The widget factory provides methods for the dynamic creation of widgets.
class WidgetFactorySupplier
The widget factory supplier class registers all kinds of preference pages and widgets.
class WidgetProducer
The WidgetProducer class is a value-based template class that provides the ability to create widgets dynamically.
class WindowAction
class WindowParameter
Adapter class to the parameter of FreeCAD for all windows Retrieve the parameter group of the specific window by the windowname.
class Workbench
This is the base class for the workbench facility.
class WorkbenchActionEvent
The WorkbenchActionEvent class is used to send an event of which workbench must be activated.
class WorkbenchComboBox
class WorkbenchFactoryInst
The workbench factory provides methods for the dynamic creation of special workbenches for each module.
class WorkbenchGroup
The WorkbenchGroup class represents a list of workbenches.
class WorkbenchManager
The WorkbenchManager class manages all workbench objects.
class WorkbenchProducer
The WorkbenchProducer template class allows the registration and the creation of workbench classes.
class WorkbenchPy
The python export class for Workbench.
class XMLMergeReader
Typedefs
typedef QPair< QString, bool > CheckListItem
typedef std::shared_ptr< DocumentObjectData > DocumentObjectDataPtr
typedef boost::graph_traits< Graph >::edge_descriptor Edge
typedef boost::adjacency_list< boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::no_property, boost::no_property, boost::listS > Graph
typedef boost::intrusive_ptr< LinkInfo > LinkInfoPtr
typedef std::shared_ptr< SoFCSelectionContextBase > SoFCSelectionContextBasePtr
typedef std::shared_ptr< SoFCSelectionContextEx > SoFCSelectionContextExPtr
typedef std::shared_ptr< SoFCSelectionContext > SoFCSelectionContextPtr
typedef std::list< std::string > TStringList
typedef std::map< std::string, std::string > TStringMap
typedef boost::graph_traits< Graph >::vertex_descriptor Vertex
typedef ViewProviderPythonFeatureT< ViewProviderDocumentObjectGroup > ViewProviderDocumentObjectGroupPython
typedef ViewProviderExtensionPythonT< Gui::ViewProviderExtension > ViewProviderExtensionPython
typedef ViewProviderExtensionPythonT< Gui::ViewProviderGeoFeatureGroupExtension > ViewProviderGeoFeatureGroupExtensionPython
typedef ViewProviderPythonFeatureT< ViewProviderGeoFeatureGroup > ViewProviderGeoFeatureGroupPython
typedef ViewProviderExtensionPythonT< Gui::ViewProviderGroupExtension > ViewProviderGroupExtensionPython
typedef ViewProviderPythonFeatureT< ViewProviderLink > ViewProviderLinkPython
typedef ViewProviderPythonFeatureT< ViewProviderMaterialObject > ViewProviderMaterialObjectPython
typedef ViewProviderExtensionPythonT< Gui::ViewProviderOriginGroupExtension > ViewProviderOriginGroupExtensionPython
typedef ViewProviderPythonFeatureT< ViewProviderPart > ViewProviderPartPython
typedef ViewProviderPythonFeatureT< ViewProviderPlacement > ViewProviderPlacementPython
typedef ViewProviderPythonFeatureT< ViewProviderDocumentObject > ViewProviderPythonFeature
typedef ViewProviderPythonFeatureT< ViewProviderGeometryObject > ViewProviderPythonGeometry
Enumerations
enum HighlightMode {
HighlightMode::Underlined, HighlightMode::Italic, HighlightMode::Overlined, HighlightMode::Bold,
HighlightMode::Blue, HighlightMode::LightBlue, HighlightMode::UserDefined
}
highlight modes for the tree items
enum SelectionRole { ,
Inner = 1, Outer = 2, Split = 3, Custom0 = 4,
Custom1 = 5, Custom2 = 6
}
enum TreeItemMode { TreeItemMode::ExpandItem, TreeItemMode::ExpandPath, TreeItemMode::CollapseItem, TreeItemMode::ToggleItem }
highlight modes for the tree items
enum ViewStatus {
UpdateData = 0, Detach = 1, isRestoring = 2, UpdatingView = 3,
TouchDocument = 4
}
Functions
void addNodes (Graph &graph, std::map< SoNode *, Vertex > &vertexNodeMap, SoNode *node)
BitmapFactoryInst & BitmapFactory (void)
Get the global instance.
template<typename T >
void cmdAppDocument (const App::Document *doc, T &&cmd)
Runs a command for accessing App.Document attribute or method This function is an alternative to FCMD_DOC_CMD.
template<typename T >
void cmdAppDocument (const App::DocumentObject *obj, T &&cmd)
Runs a command for accessing an object's App::Document attribute or method This function is an alternative to FCMD_OBJ_DOC_CMD.
template<typename T >
void cmdAppObject (const App::DocumentObject *obj, T &&cmd)
Runs a command for accessing an document object's attribute or method This function is an alternative to FCMD_OBJ_CMD.
template<typename... Args>
void cmdAppObjectArgs (const App::DocumentObject *obj, const std::string &cmd, Args &&... args)
Runs a command for accessing a document object's attribute or method This function is an alternative to FCMD_OBJ_CMD2.
void cmdAppObjectHide (const App::DocumentObject *obj)
Hides an object.
void cmdAppObjectShow (const App::DocumentObject *obj)
Shows an object.
template<typename T >
void cmdGuiDocument (const App::Document *doc, T &&cmd)
Runs a command for accessing App.Document attribute or method.
template<typename T >
void cmdGuiDocument (const App::DocumentObject *obj, T &&cmd)
Runs a command for accessing an object's Gui::Document attribute or method This function is an alternative to FCMD_VOBJ_DOC_CMD.
template<typename T >
void cmdGuiObject (const App::DocumentObject *obj, T &&cmd)
Runs a command for accessing an view object's attribute or method This function is an alternative to FCMD_VOBJ_CMD.
template<typename... Args>
void cmdGuiObjectArgs (const App::DocumentObject *obj, const std::string &cmd, Args &&... args)
Runs a command for accessing a view object's attribute or method This function is an alternative to FCMD_VOBJ_CMD2.
void cmdSetEdit (const App::DocumentObject *obj)
Runs a command to start editing a give object This function is an alternative to FCMD_SET_EDIT.
void coinRemoveAllChildren (SoGroup *node)
Helper function to deal with bug in SoNode::removeAllChildren()
ControlSingleton & Control (void)
Get the global instance.
template<typename... Args>
void copyVisualT (Args &&... args)
Copy visual attributes from a source to a target object.
void CreateDocCommands (void)
void CreateFeatCommands (void)
void CreateLinkCommands (void)
void CreateMacroCommands (void)
void CreateStdCommands (void)
void CreateStructureCommands (void)
void CreateTestCommands (void)
void CreateViewStdCommands (void)
void CreateWindowStdCommands (void)
bool cursorBeyond (const QTextCursor &cursor, const QTextCursor &limit, int shift=0)
cursorBeyond checks if cursor is at a valid position to accept keyEvents.
template<typename... Args>
void doCommandT (Gui::Command::DoCmd_Type cmdType, const std::string &cmd, Args &&... args)
Runs a command.
static PyObject * FreeCADGui_exportSubgraph (PyObject *, PyObject *args)
static PyObject * FreeCADGui_getSoDBVersion (PyObject *, PyObject *args)
static PyObject * FreeCADGui_subgraphFromObject (PyObject *, PyObject *args)
MainWindow * getMainWindow ()
template<typename qttype >
PyTypeObject * getPyTypeObjectForTypeName ()
WidgetFactorySupplier & GetWidgetFactorySupplier ()
bool OpenURLInBrowser (const char *URL)
opens a URL in the system Browser
static const QChar promptEnd (QLatin1Char(' '))
int promptLength (const QString &lineStr)
void * qt_getCppPointer (const Py::Object &pyobject, const char *shiboken, const char *unwrap)
const char * qt_identifyType (QObject *ptr, const char *pyside)
template<typename qttype >
Py::Object qt_wrapInstance (qttype object, const char *className, const char *shiboken, const char *pyside, const char *wrap)
std::array< std::pair< double, std::string >, 3 > schemaTranslatePoint (double x, double y, double z, double precision)
SelectionSingleton & Selection (void)
Get the global instance.
QString stripPromptFrom (const QString &lineStr)
bool validateInput (QWidget *parent, const QString &input)
WidgetFactoryInst & WidgetFactory ()
WorkbenchFactoryInst & WorkbenchFactory ()
Variables
struct PyMethodDef FreeCADGui_methods []
Detailed Description
The FreeCAD Graphical interface layer.
This namespace includes the grafical interface of FreeCAD like:
The main window
3D View
Tree
and so on......
Typedef Documentation
CheckListItem
typedef QPair<QString, bool> Gui::CheckListItem
DocumentObjectDataPtr
typedef std::shared_ptr<DocumentObjectData> Gui::DocumentObjectDataPtr
Edge
typedef boost::graph_traits<Graph>::edge_descriptor Gui::Edge
Graph
typedef boost::adjacency_list< boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::no_property, boost::no_property, boost::listS > Gui::Graph
LinkInfoPtr
typedef boost::intrusive_ptr<LinkInfo> Gui::LinkInfoPtr
SoFCSelectionContextBasePtr
typedef std::shared_ptr<SoFCSelectionContextBase> Gui::SoFCSelectionContextBasePtr
SoFCSelectionContextExPtr
typedef std::shared_ptr<SoFCSelectionContextEx> Gui::SoFCSelectionContextExPtr
SoFCSelectionContextPtr
typedef std::shared_ptr<SoFCSelectionContext> Gui::SoFCSelectionContextPtr
TStringList
typedef std::list<std::string> Gui::TStringList
TStringMap
typedef std::map<std::string, std::string> Gui::TStringMap
Vertex
typedef boost::graph_traits<Graph>::vertex_descriptor Gui::Vertex
ViewProviderDocumentObjectGroupPython
typedef ViewProviderPythonFeatureT<ViewProviderDocumentObjectGroup> Gui::ViewProviderDocumentObjectGroupPython
ViewProviderExtensionPython
typedef ViewProviderExtensionPythonT<Gui::ViewProviderExtension> Gui::ViewProviderExtensionPython
ViewProviderGeoFeatureGroupExtensionPython
typedef ViewProviderExtensionPythonT<Gui::ViewProviderGeoFeatureGroupExtension> Gui::ViewProviderGeoFeatureGroupExtensionPython
ViewProviderGeoFeatureGroupPython
typedef ViewProviderPythonFeatureT<ViewProviderGeoFeatureGroup> Gui::ViewProviderGeoFeatureGroupPython
ViewProviderGroupExtensionPython
typedef ViewProviderExtensionPythonT<Gui::ViewProviderGroupExtension> Gui::ViewProviderGroupExtensionPython
ViewProviderLinkPython
typedef ViewProviderPythonFeatureT<ViewProviderLink> Gui::ViewProviderLinkPython
ViewProviderMaterialObjectPython
typedef ViewProviderPythonFeatureT<ViewProviderMaterialObject> Gui::ViewProviderMaterialObjectPython
ViewProviderOriginGroupExtensionPython
typedef ViewProviderExtensionPythonT<Gui::ViewProviderOriginGroupExtension> Gui::ViewProviderOriginGroupExtensionPython
ViewProviderPartPython
typedef ViewProviderPythonFeatureT<ViewProviderPart> Gui::ViewProviderPartPython
ViewProviderPlacementPython
typedef ViewProviderPythonFeatureT<ViewProviderPlacement> Gui::ViewProviderPlacementPython
ViewProviderPythonFeature
typedef ViewProviderPythonFeatureT<ViewProviderDocumentObject> Gui::ViewProviderPythonFeature
ViewProviderPythonGeometry
typedef ViewProviderPythonFeatureT<ViewProviderGeometryObject> Gui::ViewProviderPythonGeometry
Enumeration Type Documentation
HighlightMode
enum Gui::HighlightMode strong
highlight modes for the tree items
Enumerator
Underlined
Italic
Overlined
Bold
Blue
LightBlue
UserDefined
SelectionRole
enum Gui::SelectionRole
Enumerator
Inner
Outer
Split
Custom0
Custom1
Custom2
TreeItemMode
enum Gui::TreeItemMode strong
highlight modes for the tree items
Enumerator
ExpandItem
ExpandPath
CollapseItem
ToggleItem
ViewStatus
enum Gui::ViewStatus
Enumerator
UpdateData
Detach
isRestoring
UpdatingView
TouchDocument
Function Documentation
addNodes()
void Gui::addNodes (Graph & graph, std::map< SoNode *, Vertex > & vertexNodeMap, SoNode * node)
Referenced by Gui::ViewProvider::checkRecursion().
BitmapFactory()
BitmapFactoryInst& Gui::BitmapFactory (void)
Get the global instance.
References Gui::BitmapFactoryInst::instance().
Referenced by Gui::ActionSelector::ActionSelector(), StdViewScreenShot::activated(), DrawSketchHandlerGenConstraint::activated(), Gui::RecentMacrosAction::activateFile(), Gui::ElementColors::Private::addItem(), Gui::ClearLineEdit::ClearLineEdit(), Gui::StdCmdDownloadOnlineHelp::createAction(), Gui::Command::createAction(), Gui::PythonCommand::createAction(), Gui::PythonGroupCommand::createAction(), Gui::MacroCommand::createAction(), StdCmdUndo::createAction(), StdCmdRedo::createAction(), StdCmdWorkbench::createAction(), StdCmdDrawStyle::createAction(), Gui::Dialog::ButtonModel::data(), Gui::Dialog::CommandModel::data(), ConstraintItem::data(), PartGui::DimensionControl::DimensionControl(), Gui::Dialog::DlgCustomToolbars::DlgCustomToolbars(), Gui::DocumentIndex::DocumentIndex(), Gui::ViewProviderAnnotationLabel::drawImage(), SurfaceGui::GeomFillSurface::flipOrientation(), Gui::ViewProviderPythonFeatureImp::getIcon(), MeshGui::ViewProviderMesh::getIcon(), MeshGui::ViewProviderMeshCurvature::getIcon(), PathGui::ViewProviderPath::getIcon(), Gui::ExpressionBinding::getIcon(), ExpressionDelegate::getIcon(), Gui::LinkInfo::getIcon(), Gui::ViewProvider::getIcon(), PartGui::ViewProviderBoolean::getIcon(), PartGui::ViewProviderMultiFuse::getIcon(), PartGui::ViewProviderMultiCommon::getIcon(), PartGui::ViewProviderSpline::getIcon(), PartDesignGui::ViewProviderLoft::getIcon(), PartDesignGui::ViewProviderPipe::getIcon(), PartDesignGui::ViewProviderPrimitive::getIcon(), PathGui::ViewProviderPathCompound::getIcon(), PathGui::ViewProviderPathShape::getIcon(), SurfaceGui::ViewProviderFilling::getIcon(), SurfaceGui::ViewProviderGeomFillSurface::getIcon(), SurfaceGui::ViewProviderSections::getIcon(), SurfaceGui::ViewProviderExtend::getIcon(), Gui::ViewProviderDocumentObjectGroup::getIcon(), Gui::ViewProviderLink::getIcon(), Gui::ViewProviderLink::getOverlayPixmap(), Gui::Dialog::IconDialog::IconDialog(), Gui::Dialog::IconFolders::IconFolders(), Gui::Dialog::DlgPropertyLink::init(), Gui::PythonGroupCommand::languageChange(), Gui::MainWindow::MainWindow(), Gui::BitmapFactoryInst::mergePixmap(), Gui::DAG::Model::Model(), Gui::Dialog::DlgCustomActionsImp::on_actionListWidget_itemActivated(), Gui::Dialog::DlgCustomActionsImp::on_buttonReplaceAction_clicked(), Gui::Dialog::DlgCustomKeyboardImp::on_categoryBox_activated(), Gui::Dialog::DlgCustomToolbars::on_categoryBox_activated(), Gui::Dialog::DlgMacroExecuteImp::on_createButton_clicked(), Gui::Dialog::DlgMacroExecuteImp::on_editButton_clicked(), Gui::Dialog::DlgCustomKeyboardImp::on_editShortcut_textChanged(), Gui::Dialog::DlgCustomCommandsImp::onAddMacroAction(), Gui::Dialog::DlgCustomKeyboardImp::onAddMacroAction(), Gui::Dialog::DlgCustomToolbars::onAddMacroAction(), Gui::Dialog::DlgCustomCommandsImp::onGroupActivated(), Gui::Dialog::DlgCustomCommandsImp::onModifyMacroAction(), Gui::Dialog::DlgCustomKeyboardImp::onModifyMacroAction(), Gui::Dialog::DlgCustomToolbars::onModifyMacroAction(), ImageGui::ImageOrientationDialog::onPreview(), SketcherGui::SketchOrientationDialog::onPreview(), SurfaceGui::GeomFillSurface::onSelectionChanged(), Gui::Dialog::ParameterBool::ParameterBool(), Gui::Dialog::ParameterFloat::ParameterFloat(), Gui::Dialog::ParameterInt::ParameterInt(), Gui::Dialog::ParameterText::ParameterText(), Gui::Dialog::ParameterUInt::ParameterUInt(), SketcherGui::ViewProviderSketch::renderConstrIcon(), Gui::DockWnd::ReportView::ReportView(), Gui::Application::runApplication(), Gui::Application::sAddIcon(), Gui::Application::sAddIconPath(), Gui::Application::sAddResPath(), Gui::Thumbnail::SaveDocFile(), Gui::DockWnd::SelectionView::SelectionView(), SketcherGui::ViewProviderSketch::sendConstraintIconToCoin(), SurfaceGui::GeomFillSurface::setEditedObject(), SketcherGui::DrawSketchHandler::setSvgCursor(), Gui::GroupCommand::setup(), Gui::AlignmentView::setupHeadUpDisplay(), Gui::Application::sGetIcon(), Gui::PythonDebugger::showDebugMarker(), Gui::DockWnd::ComboView::showDialog(), DrawingGui::ViewProviderDrawingPage::showDrawingView(), TechDrawGui::ViewProviderPage::showMDIViewPage(), SpreadsheetGui::ViewProviderSheet::showSpreadsheetView(), Gui::CallTipsList::showTips(), Gui::Application::sInsert(), Gui::Application::sIsIconCached(), Gui::Application::sOpen(), Gui::MainWindow::splashImage(), SketcherGui::DrawSketchHandler::suggestedConstraintsPixmaps(), FemGui::TaskAnalysisInfo::TaskAnalysisInfo(), PartGui::TaskAttacher::TaskAttacher(), PartGui::TaskBooleanOperation::TaskBooleanOperation(), PartDesignGui::TaskBooleanParameters::TaskBooleanParameters(), PartGui::TaskChamferEdges::TaskChamferEdges(), PartGui::TaskCheckGeometryDialog::TaskCheckGeometryDialog(), FemGui::TaskCreateNodeSet::TaskCreateNodeSet(), MeshPartGui::TaskCrossSections::TaskCrossSections(), PartGui::TaskCrossSections::TaskCrossSections(), TechDrawGui::TaskDlgActiveView::TaskDlgActiveView(), TechDrawGui::TaskDlgBalloon::TaskDlgBalloon(), TechDrawGui::TaskDlgCenterLine::TaskDlgCenterLine(), TechDrawGui::TaskDlgCosmeticLine::TaskDlgCosmeticLine(), TechDrawGui::TaskDlgCosVertex::TaskDlgCosVertex(), TechDrawGui::TaskDlgDetail::TaskDlgDetail(), TechDrawGui::TaskDlgGeomHatch::TaskDlgGeomHatch(), TechDrawGui::TaskDlgHatch::TaskDlgHatch(), TechDrawGui::TaskDlgLeaderLine::TaskDlgLeaderLine(), TechDrawGui::TaskDlgLineDecor::TaskDlgLineDecor(), TechDrawGui::TaskDlgLinkDim::TaskDlgLinkDim(), DrawingGui::TaskDlgOrthoViews::TaskDlgOrthoViews(), TechDrawGui::TaskDlgProjGroup::TaskDlgProjGroup(), TechDrawGui::TaskDlgRichAnno::TaskDlgRichAnno(), TechDrawGui::TaskDlgSectionView::TaskDlgSectionView(), TechDrawGui::TaskDlgWeldingSymbol::TaskDlgWeldingSymbol(), FemGui::TaskDriver::TaskDriver(), RobotGui::TaskEdge2TracParameter::TaskEdge2TracParameter(), PartGui::TaskExtrusion::TaskExtrusion(), PartDesignGui::TaskFeatureParameters::TaskFeatureParameters(), FemGui::TaskFemConstraint::TaskFemConstraint(), PartGui::TaskFilletEdges::TaskFilletEdges(), SurfaceGui::TaskFilling::TaskFilling(), ReenGui::TaskFitBSplineSurface::TaskFitBSplineSurface(), SurfaceGui::TaskGeomFillSurface::TaskGeomFillSurface(), PartGui::TaskLoft::TaskLoft(), PartGui::TaskMirroring::TaskMirroring(), FemGui::TaskObjectName::TaskObjectName(), PartGui::TaskOffset::TaskOffset(), SandboxGui::TaskPanelView::TaskPanelView(), ReenGui::TaskPoisson::TaskPoisson(), FemGui::TaskPostClip::TaskPostClip(), FemGui::TaskPostCut::TaskPostCut(), FemGui::TaskPostDataAlongLine::TaskPostDataAlongLine(), FemGui::TaskPostDataAtPoint::TaskPostDataAtPoint(), FemGui::TaskPostDisplay::TaskPostDisplay(), FemGui::TaskPostFunction::TaskPostFunction(), FemGui::TaskPostScalarClip::TaskPostScalarClip(), FemGui::TaskPostWarpVector::TaskPostWarpVector(), PartGui::TaskProjectionOnSurface::TaskProjectionOnSurface(), PartGui::TaskRevolution::TaskRevolution(), RobotGui::TaskRobot6Axis::TaskRobot6Axis(), RobotGui::TaskRobotControl::TaskRobotControl(), RobotGui::TaskRobotMessages::TaskRobotMessages(), SurfaceGui::TaskSections::TaskSections(), Gui::TaskView::TaskSelectLinkProperty::TaskSelectLinkProperty(), PartDesignGui::TaskShapeBinder::TaskShapeBinder(), PartGui::TaskShapeBuilder::TaskShapeBuilder(), PartGui::TaskSweep::TaskSweep(), FemGui::TaskTetParameter::TaskTetParameter(), PartGui::TaskThickness::TaskThickness(), RobotGui::TaskTrajectory::TaskTrajectory(), RobotGui::TaskTrajectoryDressUpParameter::TaskTrajectoryDressUpParameter(), Gui::TaskView::TaskWatcherCommands::TaskWatcherCommands(), Gui::TaskView::TaskWatcherPython::TaskWatcherPython(), PathGui::TaskWidgetPathCompound::TaskWidgetPathCompound(), Gui::DocumentObjectItem::testStatus(), Gui::TreeWidget::TreeWidget(), CmdSketcherConstrainLock::updateAction(), CmdSketcherConstrainDistance::updateAction(), CmdSketcherConstrainDistanceX::updateAction(), CmdSketcherConstrainDistanceY::updateAction(), CmdSketcherConstrainRadius::updateAction(), CmdSketcherConstrainDiameter::updateAction(), CmdSketcherConstrainAngle::updateAction(), ImageGui::ViewProviderImagePlane::updateData(), Gui::Application::workbenchIcon(), and Gui::SoFCOffscreenRenderer::writeToImage().
cmdAppDocument() [1/2]
template<typename T > void Gui::cmdAppDocument (const App::Document * doc, T && cmd)
Runs a command for accessing App.Document attribute or method This function is an alternative to FCMD_DOC_CMD.
Parameters
doc pointer to a document
cmd command string, streamable
See also
_cmdDocument()
Example:
cmdAppDocument(doc, std::stringstream() << "getObject('" << objName << "')");
Translates to command (assuming doc's name is 'DocName', and and objName contains value 'ObjName'):
App.getDocument('DocName').getObject('ObjName')
References Gui::Command::Doc.
Referenced by PartDesignGui::TaskDlgFeatureParameters::accept(), PartDesignGui::TaskDlgPipeParameters::accept(), CmdTestCmdFuncs::activated(), and SpreadsheetGui::SheetView::editingFinished().
cmdAppDocument() [2/2]
template<typename T > void Gui::cmdAppDocument (const App::DocumentObject * obj, T && cmd)
Runs a command for accessing an object's App::Document attribute or method This function is an alternative to FCMD_OBJ_DOC_CMD.
Parameters
obj pointer to a DocumentObject
cmd command string, streamable
References Gui::Command::Doc.
cmdAppObject()
template<typename T > void Gui::cmdAppObject (const App::DocumentObject * obj, T && cmd)
Runs a command for accessing an document object's attribute or method This function is an alternative to FCMD_OBJ_CMD.
Parameters
obj pointer to a DocumentObject
cmd command string, streamable
See also
_cmdObject()
References Gui::Command::Doc.
Referenced by PartGui::TaskDlgAttacher::accept(), CmdTestCmdFuncs::activated(), cmdAppObjectHide(), and cmdAppObjectShow().
cmdAppObjectArgs()
template<typename... Args> void Gui::cmdAppObjectArgs (const App::DocumentObject * obj, const std::string & cmd, Args &&... args)
Runs a command for accessing a document object's attribute or method This function is an alternative to FCMD_OBJ_CMD2.
Parameters
cmd command string, supporting printf like formatter
obj pointer to a DocumentObject
Example:
cmdAppObjectArgs(obj, "Visibility = %s", visible ? "True" : "False");
Translates to command (assuming obj's document name is 'DocName', obj's name is 'ObjName', and visible is true):
App.getDocument('DocName').getObject('ObjName').Visibility = True
References Base::Console(), Gui::Command::Doc, Base::ConsoleSingleton::Error(), and Gui::FormatString::toStr().
Referenced by PartGui::TaskDlgAttacher::accept(), PartGui::OffsetWidget::accept(), PartGui::ThicknessWidget::accept(), CmdTestCmdFuncs::activated(), CmdSketcherConstrainHorizontal::activated(), CmdSketcherConstrainVertical::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainCoincident::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainPointOnObject::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), SpreadsheetGui::PropertiesDialog::apply(), CmdSketcherConstrainHorizontal::applyConstraint(), CmdSketcherConstrainVertical::applyConstraint(), CmdSketcherConstrainLock::applyConstraint(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainCoincident::applyConstraint(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainPointOnObject::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainParallel::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), SketcherGui::DrawSketchHandler::createAutoConstraints(), SpreadsheetGui::SheetView::editingFinished(), SpreadsheetGui::SheetTableView::insertColumns(), SpreadsheetGui::SheetTableView::insertRows(), SketcherGui::makeTangentToArcOfEllipseviaNewPoint(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), SketcherGui::makeTangentToArcOfParabolaviaNewPoint(), SketcherGui::makeTangentToEllipseviaNewPoint(), SketcherGui::ViewProviderSketch::mouseButtonPressed(), SketcherGui::TaskSketcherConstrains::on_listWidgetConstraints_itemChanged(), SketcherGui::ViewProviderSketch::onDelete(), DrawSketchHandlerExternal::onSelectionChanged(), DrawSketchHandlerCarbonCopy::onSelectionChanged(), DrawSketchHandlerBSpline::pressButton(), DrawSketchHandlerCoincident::releaseButton(), DrawSketchHandlerLine::releaseButton(), DrawSketchHandlerLineSet::releaseButton(), DrawSketchHandlerArc::releaseButton(), DrawSketchHandler3PointArc::releaseButton(), DrawSketchHandlerCircle::releaseButton(), DrawSketchHandlerArcOfEllipse::releaseButton(), DrawSketchHandler3PointCircle::releaseButton(), DrawSketchHandlerPoint::releaseButton(), DrawSketchHandlerFillet::releaseButton(), DrawSketchHandlerTrimming::releaseButton(), DrawSketchHandlerExtend::releaseButton(), DrawSketchHandlerCopy::releaseButton(), DrawSketchHandlerRectangularArray::releaseButton(), DrawSketchHandlerArcOfHyperbola::releaseButton(), DrawSketchHandlerArcOfParabola::releaseButton(), DrawSketchHandlerBSpline::releaseButton(), SpreadsheetGui::SheetTableView::removeColumns(), SpreadsheetGui::SheetTableView::removeRows(), and SketcherGui::ConstraintView::swapNamedOfSelectedItems().
cmdAppObjectHide()
void Gui::cmdAppObjectHide (const App::DocumentObject * obj)
Hides an object.
References cmdAppObject().
Referenced by PartDesignGui::TaskDlgFeatureParameters::accept(), and CmdTestCmdFuncs::activated().
cmdAppObjectShow()
void Gui::cmdAppObjectShow (const App::DocumentObject * obj)
Shows an object.
References cmdAppObject().
Referenced by CmdTestCmdFuncs::activated().
cmdGuiDocument() [1/2]
template<typename T > void Gui::cmdGuiDocument (const App::Document * doc, T && cmd)
Runs a command for accessing App.Document attribute or method.
Parameters
doc pointer to a document
cmd command string, streamable
See also
_cmdDocument()
Example:
cmdGuiDocument(doc, std::stringstream() << "getObject('" << objName << "')");
Translates to command (assuming doc's name is 'DocName', and and objName contains value 'ObjName'):
Gui.getDocument('DocName').getObject('ObjName')
References Gui::Command::Gui.
Referenced by PartGui::TaskDlgAttacher::accept(), PartDesignGui::TaskDlgFeatureParameters::accept(), PartDesignGui::TaskDlgPipeParameters::accept(), and CmdTestCmdFuncs::activated().
cmdGuiDocument() [2/2]
template<typename T > void Gui::cmdGuiDocument (const App::DocumentObject * obj, T && cmd)
Runs a command for accessing an object's Gui::Document attribute or method This function is an alternative to FCMD_VOBJ_DOC_CMD.
Parameters
obj pointer to a DocumentObject
cmd command string, streamable
References Gui::Command::Gui.
cmdGuiObject()
template<typename T > void Gui::cmdGuiObject (const App::DocumentObject * obj, T && cmd)
Runs a command for accessing an view object's attribute or method This function is an alternative to FCMD_VOBJ_CMD.
Parameters
obj pointer to a DocumentObject
cmd command string, streamable
See also
_cmdObject()
References Gui::Command::Gui.
Referenced by CmdTestCmdFuncs::activated(), and PartDesignGui::TaskPipeParameters::~TaskPipeParameters().
cmdGuiObjectArgs()
template<typename... Args> void Gui::cmdGuiObjectArgs (const App::DocumentObject * obj, const std::string & cmd, Args &&... args)
Runs a command for accessing a view object's attribute or method This function is an alternative to FCMD_VOBJ_CMD2.
Parameters
cmd command string, supporting printf like formatter
obj pointer to a DocumentObject
See also
cmdAppObjectArgs()
References Base::Console(), Base::ConsoleSingleton::Error(), Gui::Command::Gui, and Gui::FormatString::toStr().
Referenced by CmdTestCmdFuncs::activated().
cmdSetEdit()
void Gui::cmdSetEdit (const App::DocumentObject * obj)
Runs a command to start editing a give object This function is an alternative to FCMD_SET_EDIT.
Parameters
obj pointer to a DocumentObject
Unlike other helper functions, this one editing the object using the current active document, instead of the object's owner document. This allows in-place editing an object, which may be brought in through linking to an external group.
References Gui::Command::Gui.
Referenced by CmdTestCmdFuncs::activated().
coinRemoveAllChildren()
void Gui::coinRemoveAllChildren (SoGroup * node)
Helper function to deal with bug in SoNode::removeAllChildren()
See also
https://bitbucket.org/Coin3D/coin/pull-requests/119/fix-sochildlist-auditing/diff
References coinRemoveAllChildren().
Referenced by Gui::View3DInventorViewer::checkGroupOnTop(), Gui::View3DInventorViewer::clearGroupOnTop(), coinRemoveAllChildren(), Gui::ManualAlignment::continueAlignment(), PartGui::ViewProvider2DObjectGrid::createGrid(), Gui::LinkInfo::detach(), SketcherGui::ViewProviderSketch::draw(), Gui::View3DInventorViewer::eraseAllDimensions(), PartGui::ViewProviderSplineExtension::extensionUpdateData(), Gui::LinkInfo::getSnapshot(), PartGui::ViewProvider2DObjectGrid::onChanged(), Gui::ManualAlignment::onClear(), SketcherGui::ViewProviderSketch::rebuildConstraintsVisual(), Gui::SoFCColorGradient::rebuildGradient(), PartDesignGui::ViewProviderTransformed::recomputeFeature(), Gui::ManualAlignment::reset(), RobotGui::ViewProviderRobotObject::resetDragger(), Gui::LinkView::resetRoot(), Gui::Application::sCoinRemoveAllChildren(), Gui::LinkView::setChildren(), Gui::SoFCColorLegend::setColorModel(), Gui::SoFCColorLegend::setMarkerLabel(), Gui::SoFCPathAnnotation::setPath(), Gui::View3DInventorViewer::setupEditingRoot(), MeshGui::MeshFillHole::startEditing(), Gui::LinkView::SubInfo::unlink(), Gui::LinkView::Element::unlink(), PartGui::ViewProvider2DObjectGrid::unsetEdit(), PartGui::ViewProviderMirror::unsetEdit(), SketcherGui::ViewProviderSketch::unsetEdit(), PartDesignGui::ViewProviderTransformed::unsetEdit(), Gui::LinkInfo::updateChildren(), Gui::ViewProviderInventorObject::updateData(), Gui::ViewProviderVRMLObject::updateData(), FemGui::ViewProviderFemConstraintBearing::updateData(), FemGui::ViewProviderFemConstraintContact::updateData(), FemGui::ViewProviderFemConstraintFixed::updateData(), FemGui::ViewProviderFemConstraintFluidBoundary::updateData(), FemGui::ViewProviderFemConstraintForce::updateData(), FemGui::ViewProviderFemConstraintGear::updateData(), FemGui::ViewProviderFemConstraintHeatflux::updateData(), FemGui::ViewProviderFemConstraintPlaneRotation::updateData(), FemGui::ViewProviderFemConstraintPressure::updateData(), FemGui::ViewProviderFemConstraintPulley::updateData(), FemGui::ViewProviderFemConstraintTemperature::updateData(), FemGui::ViewProviderFemConstraintTransform::updateData(), InspectionGui::ViewProviderInspection::updateData(), MeshGui::ViewProviderMeshCurvature::updateData(), MeshGui::ViewProviderMeshFaceSet::updateData(), PartGui::ViewProvider2DObjectGrid::updateData(), PartGui::ViewProviderCurveNet::updateData(), RobotGui::ViewProviderRobotObject::updateData(), PartGui::ViewProviderSpline::updateData(), Gui::LinkView::updateLink(), and Gui::View3DInventorViewer::~View3DInventorViewer().
Control()
ControlSingleton& Gui::Control (void)
Get the global instance.
References Gui::ControlSingleton::instance().
Referenced by PartDesignGui::Workbench::activated(), RobotGui::Workbench::activated(), StdCmdTransform::activated(), StdCmdPlacement::activated(), StdCmdSetAppearance::activated(), StdCmdTextureMapping::activated(), Gui::TaskView::ControlPy::activeDialog(), Gui::TaskView::ControlPy::addTaskWatcher(), Gui::Workbench::addTaskWatcher(), Gui::Document::canClose(), PartGui::ViewProviderPartExt::changeFaceColors(), Gui::TaskView::ControlPy::clearTaskWatcher(), Gui::TaskView::ControlPy::closeDialog(), FemGui::ViewProviderSetNodes::doubleClicked(), RobotGui::ViewProviderEdge2TracObject::doubleClicked(), PartGui::ViewProviderAttachExtension::extensionSetupContextMenu(), TechDrawGui::TaskSectionView::failNoObject(), PartGui::goDimensionAngularRoot(), PartGui::goDimensionLinearRoot(), StdCmdTransform::isActive(), StdCmdPlacement::isActive(), StdCmdEdit::isActive(), StdCmdSetAppearance::isActive(), StdCmdToggleNavigation::isActive(), StdCmdTextureMapping::isActive(), Gui::TaskView::ControlPy::isAllowedAlterDocument(), Gui::TaskView::ControlPy::isAllowedAlterSelection(), Gui::TaskView::ControlPy::isAllowedAlterView(), PartGui::PropertyEnumAttacherItem::openTask(), Gui::Workbench::removeTaskWatcher(), Gui::Document::setEdit(), FemGui::ViewProviderFemConstraintBearing::setEdit(), FemGui::ViewProviderFemConstraintContact::setEdit(), FemGui::ViewProviderFemConstraintDisplacement::setEdit(), FemGui::ViewProviderFemConstraintFixed::setEdit(), FemGui::ViewProviderFemConstraintFluidBoundary::setEdit(), FemGui::ViewProviderFemConstraintForce::setEdit(), FemGui::ViewProviderFemConstraintGear::setEdit(), FemGui::ViewProviderFemConstraintHeatflux::setEdit(), FemGui::ViewProviderFemConstraintInitialTemperature::setEdit(), FemGui::ViewProviderFemConstraintPlaneRotation::setEdit(), FemGui::ViewProviderFemConstraintPressure::setEdit(), FemGui::ViewProviderFemConstraintPulley::setEdit(), FemGui::ViewProviderFemConstraintTemperature::setEdit(), FemGui::ViewProviderFemConstraintTransform::setEdit(), FemGui::ViewProviderFemMeshShapeNetgen::setEdit(), FemGui::ViewProviderFemPostFunction::setEdit(), FemGui::ViewProviderFemPostObject::setEdit(), FemGui::ViewProviderSetNodes::setEdit(), PartGui::ViewProviderFillet::setEdit(), PartGui::ViewProviderChamfer::setEdit(), PartGui::ViewProviderOffset::setEdit(), PartGui::ViewProviderThickness::setEdit(), PartGui::ViewProviderPrimitive::setEdit(), PartDesignGui::ViewProviderHole::setEdit(), PartDesignGui::ViewProviderPrimitive::setEdit(), PathGui::ViewProviderPathCompound::setEdit(), RobotGui::ViewProviderEdge2TracObject::setEdit(), RobotGui::ViewProviderTrajectoryCompound::setEdit(), RobotGui::ViewProviderTrajectoryDressUp::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), SurfaceGui::ViewProviderFilling::setEdit(), SurfaceGui::ViewProviderGeomFillSurface::setEdit(), SurfaceGui::ViewProviderSections::setEdit(), TechDrawGui::ViewProviderBalloon::setEdit(), TechDrawGui::ViewProviderLeader::setEdit(), TechDrawGui::ViewProviderProjGroup::setEdit(), TechDrawGui::ViewProviderRichAnno::setEdit(), TechDrawGui::ViewProviderViewPart::setEdit(), TechDrawGui::ViewProviderViewSection::setEdit(), TechDrawGui::ViewProviderWeld::setEdit(), Gui::ViewProviderDragger::setEdit(), Gui::ViewProviderLink::setEdit(), PartDesignGui::ViewProvider::setEdit(), PartDesignGui::ViewProviderBoolean::setEdit(), PartDesignGui::ViewProviderDatum::setEdit(), PartDesignGui::ViewProviderShapeBinder::setEdit(), TechDrawGui::ViewProviderGeomHatch::setEdit(), TechDrawGui::ViewProviderHatch::setEdit(), Gui::ViewProviderLink::setEditViewer(), Gui::TaskView::ControlPy::showDialog(), Gui::TaskView::ControlPy::showTaskView(), Gui::ElementColors::slotDeleteDocument(), PartGui::FaceColors::slotDeleteDocument(), PartDesignGui::TaskFeaturePick::slotDeleteDocument(), PartGui::FaceColors::slotDeleteObject(), Gui::ElementColors::slotDeleteObject(), PartGui::FaceColors::slotUndoDocument(), PartDesignGui::TaskFeaturePick::slotUndoDocument(), Gui::Command::testActive(), FemGui::ViewProviderFemAnalysis::unsetEdit(), FemGui::ViewProviderFemConstraint::unsetEdit(), FemGui::ViewProviderFemPostFunction::unsetEdit(), FemGui::ViewProviderFemPostObject::unsetEdit(), PartGui::ViewProviderFillet::unsetEdit(), PartGui::ViewProviderChamfer::unsetEdit(), PartGui::ViewProviderOffset::unsetEdit(), PartGui::ViewProviderThickness::unsetEdit(), PartGui::ViewProviderPrimitive::unsetEdit(), PathGui::ViewProviderPathCompound::unsetEdit(), RobotGui::ViewProviderTrajectoryCompound::unsetEdit(), RobotGui::ViewProviderTrajectoryDressUp::unsetEdit(), SketcherGui::ViewProviderSketch::unsetEdit(), SurfaceGui::ViewProviderFilling::unsetEdit(), SurfaceGui::ViewProviderGeomFillSurface::unsetEdit(), SurfaceGui::ViewProviderSections::unsetEdit(), TechDrawGui::ViewProviderBalloon::unsetEdit(), TechDrawGui::ViewProviderLeader::unsetEdit(), TechDrawGui::ViewProviderProjGroup::unsetEdit(), TechDrawGui::ViewProviderProjGroupItem::unsetEdit(), TechDrawGui::ViewProviderRichAnno::unsetEdit(), TechDrawGui::ViewProviderViewPart::unsetEdit(), TechDrawGui::ViewProviderViewSection::unsetEdit(), TechDrawGui::ViewProviderWeld::unsetEdit(), Gui::ViewProviderDragger::unsetEdit(), PartDesignGui::ViewProvider::unsetEdit(), PartDesignGui::ViewProviderDatum::unsetEdit(), TechDrawGui::ViewProviderDrawingView::unsetEdit(), TechDrawGui::ViewProviderGeomHatch::unsetEdit(), TechDrawGui::ViewProviderHatch::unsetEdit(), and Gui::ViewProviderLink::unsetEditViewer().
copyVisualT()
template<typename... Args> void Gui::copyVisualT (Args &&... args)
Copy visual attributes from a source to a target object.
Referenced by CmdTestCmdFuncs::activated().
CreateDocCommands()
void Gui::CreateDocCommands (void)
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by Gui::Application::createStandardOperations().
CreateFeatCommands()
void Gui::CreateFeatCommands (void)
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by Gui::Application::createStandardOperations().
CreateLinkCommands()
void Gui::CreateLinkCommands (void)
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by Gui::Application::createStandardOperations().
CreateMacroCommands()
void Gui::CreateMacroCommands (void)
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by Gui::Application::createStandardOperations().
CreateStdCommands()
void Gui::CreateStdCommands (void)
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by Gui::Application::createStandardOperations().
CreateStructureCommands()
void Gui::CreateStructureCommands (void)
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by Gui::Application::createStandardOperations().
CreateTestCommands()
void Gui::CreateTestCommands (void)
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by Gui::Application::createStandardOperations().
CreateViewStdCommands()
void Gui::CreateViewStdCommands (void)
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), App::GetApplication(), App::Application::GetParameterGroupByPath(), Gui::Application::Instance, and ParameterGrp::SetASCII().
Referenced by Gui::Application::createStandardOperations().
CreateWindowStdCommands()
void Gui::CreateWindowStdCommands (void)
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by Gui::Application::createStandardOperations().
cursorBeyond()
bool Gui::cursorBeyond (const QTextCursor & cursor, const QTextCursor & limit, int shift = 0)
cursorBeyond checks if cursor is at a valid position to accept keyEvents.
Parameters
cursor - cursor to check
limit - cursor that marks the begin of the input region
shift - offset for shifting the limit for non-selection cursors [default: 0]
Returns
true if a keyEvent is ok at cursor's position, false otherwise
Referenced by Gui::PythonConsole::contextMenuEvent(), and Gui::PythonConsole::keyPressEvent().
doCommandT()
template<typename... Args> void Gui::doCommandT (Gui::Command::DoCmd_Type cmdType, const std::string & cmd, Args &&... args)
Runs a command.
Parameters
cmdType command type
cmd command string, supporting printf like formatter
Example:
doCommandT(Gui::Command::Gui, "Gui.getDocument(%s).getObject(%s).Visibility = %s", "DocName", "ObjName", visible?"True":"False");
Translates to command (assuming obj's document name is 'DocName', obj's name is 'ObjName', and visible is true):
Gui.getDocument('DocName').getObject('ObjName').Visibility = True
References Base::Console(), Base::ConsoleSingleton::Error(), and Gui::FormatString::toStr().
Referenced by CmdTestCmdFuncs::activated().
FreeCADGui_exportSubgraph()
static PyObject* Gui::FreeCADGui_exportSubgraph (PyObject * , PyObject * args) static
References Base::InterpreterSingleton::convertSWIGPointerObj(), Base::Interpreter(), Gui::SoFCDB::writeNodesToString(), and Gui::SoFCDB::writeToVRML().
FreeCADGui_getSoDBVersion()
static PyObject* Gui::FreeCADGui_getSoDBVersion (PyObject * , PyObject * args) static
FreeCADGui_subgraphFromObject()
static PyObject* Gui::FreeCADGui_subgraphFromObject (PyObject * , PyObject * args) static
References Gui::ViewProviderDocumentObject::attach(), Base::Type::createInstanceByName(), Base::InterpreterSingleton::createSWIGPointerObj(), Base::Persistence::getClassTypeId(), Gui::ViewProvider::getDisplayModes(), App::ExtensionContainer::getPropertyByName(), Gui::ViewProvider::getRoot(), Base::Persistence::getTypeId(), Base::Interpreter(), Gui::ViewProvider::setDisplayMode(), App::DocumentObjectPy::Type, and Gui::ViewProvider::updateData().
getMainWindow()
MainWindow* Gui::getMainWindow ()
References Gui::MainWindow::getInstance().
Referenced by TechDrawGui::TaskCosVertex::abandonEditSession(), TechDrawGui::TaskLeaderLine::abandonEditSession(), Gui::Dialog::AboutDialog::AboutDialog(), Gui::Dialog::DlgActivateWindowImp::accept(), Gui::Dialog::DlgMacroExecuteImp::accept(), FemGui::TaskDlgMeshShapeNetgen::accept(), PartDesignGui::TaskDlgDatumParameters::accept(), PartDesignGui::TaskDlgFeatureParameters::accept(), PartDesignGui::TaskDlgPipeParameters::accept(), Gui::Dialog::DlgAddProperty::accept(), SketcherCopy::activate(), Gui::BlankWorkbench::activated(), RobotGui::Workbench::activated(), SpreadsheetGui::Workbench::activated(), Gui::MacroCommand::activated(), StdCmdOpen::activated(), StdCmdImport::activated(), StdCmdExport::activated(), StdCmdMergeProjects::activated(), StdCmdDependencyGraph::activated(), StdCmdRevert::activated(), StdCmdProjectInfo::activated(), StdCmdProjectUtil::activated(), StdCmdPrint::activated(), StdCmdPrintPreview::activated(), StdCmdPrintPdf::activated(), StdCmdQuit::activated(), StdCmdCopy::activated(), StdCmdPaste::activated(), StdCmdDuplicateSelection::activated(), StdCmdDelete::activated(), StdCmdRefresh::activated(), StdCmdEdit::activated(), StdCmdLinkMakeGroup::activated(), StdCmdLinkMake::activated(), StdCmdLinkMakeRelative::activated(), StdCmdLinkImport::activated(), StdCmdLinkImportAll::activated(), StdCmdLinkSelectLinked::activated(), StdCmdLinkSelectLinkedFinal::activated(), StdCmdLinkSelectAllLinks::activated(), StdCmdDlgMacroRecord::activated(), StdCmdDlgMacroExecute::activated(), StdCmdWorkbench::activated(), StdCmdAbout::activated(), StdCmdDlgParameter::activated(), StdCmdDlgPreferences::activated(), StdCmdDlgCustomize::activated(), StdCmdCommandLine::activated(), StdCmdOnlineHelp::activated(), StdCmdMeasurementSimple::activated(), StdCmdUnitsCalculator::activated(), Std_TestQM::activated(), CmdTestMDI1::activated(), CmdTestMDI2::activated(), CmdTestMDI3::activated(), StdOrthographicCamera::activated(), StdPerspectiveCamera::activated(), StdCmdViewSaveCamera::activated(), StdCmdViewRestoreCamera::activated(), StdCmdToggleClipPlane::activated(), StdCmdSetAppearance::activated(), StdMainFullscreen::activated(), StdViewDockUndockFullscreen::activated(), StdViewScreenShot::activated(), StdCmdToggleNavigation::activated(), StdCmdAxisCross::activated(), StdViewZoomIn::activated(), StdViewZoomOut::activated(), StdViewBoxZoom::activated(), StdBoxSelection::activated(), StdBoxElementSelection::activated(), StdCmdTreeCollapse::activated(), StdCmdTreeExpand::activated(), StdCmdTreeSelectAllInstances::activated(), StdCmdSceneInspector::activated(), StdCmdDemoMode::activated(), StdTreeDrag::activated(), StdCmdArrangeIcons::activated(), StdCmdTileWindows::activated(), StdCmdCascadeWindows::activated(), StdCmdCloseActiveWindow::activated(), StdCmdCloseAllWindows::activated(), StdCmdActivateNextWindow::activated(), StdCmdActivatePrevWindow::activated(), StdCmdWindows::activated(), StdCmdUserInterface::activated(), StdCmdStatusBar::activated(), Gui::StdCmdDownloadOnlineHelp::activated(), Gui::StdCmdPythonHelp::activated(), CmdSandboxMeshLoader::activated(), CmdSketcherConstrainHorizontal::activated(), CmdSketcherConstrainVertical::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainCoincident::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainPointOnObject::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), draftguitools.gui_annotationstyleeditor.AnnotationStyleEditor::Activated(), Gui::RecentFilesAction::activateFile(), Gui::RecentMacrosAction::activateFile(), Gui::Application::activateWorkbench(), SketcherGui::DrawSketchHandler::addCursorTail(), Gui::Dialog::DlgCustomToolbarsImp::addCustomCommand(), Gui::Dialog::DlgCustomToolbarsImp::addCustomToolbar(), Gui::DockWindowManager::addDockWindow(), Gui::MacroManager::addLine(), Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::addSelections(), Gui::DockWidgetAction::addTo(), Gui::ToolBarAction::addTo(), Gui::WindowAction::addTo(), Gui::ManualAlignment::align(), CmdSketcherConstrainHorizontal::applyConstraint(), CmdSketcherConstrainVertical::applyConstraint(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainPointOnObject::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainParallel::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), SketcherGui::DrawSketchHandler::applyCursor(), RemoteDebugger::attachToRemoteDebugger(), SpreadsheetGui::ViewProviderSheet::beforeDelete(), Gui::ProgressBar::canAbort(), Gui::ProgressDialog::canAbort(), Gui::ManualAlignment::cancel(), Gui::Document::canClose(), Gui::MainWindow::changeEvent(), Gui::MDIView::changeEvent(), Gui::Application::checkForPreviousCrashes(), FemGui::ViewProviderFemConstraint::checkForWizard(), Gui::SelectionSingleton::clearCompleteSelection(), Gui::SelectionSingleton::clearSelection(), Gui::Document::cloneView(), Gui::EditorView::closeEvent(), Gui::TextDocumentEditorView::closeEvent(), Gui::GUIApplication::commitData(), Gui::PropertyEditor::PropertyEditor::contextMenuEvent(), Gui::ManualAlignment::continueAlignment(), Gui::StdCmdDownloadOnlineHelp::createAction(), Gui::Command::createAction(), Gui::GroupCommand::createAction(), Gui::PythonCommand::createAction(), Gui::PythonGroupCommand::createAction(), Gui::MacroCommand::createAction(), StdCmdUndo::createAction(), StdCmdRedo::createAction(), StdCmdExpression::createAction(), StdCmdLinkMakeGroup::createAction(), StdCmdWorkbench::createAction(), StdCmdRecentFiles::createAction(), StdCmdRecentMacros::createAction(), StdCmdAbout::createAction(), StdCmdFreezeViews::createAction(), StdCmdDrawStyle::createAction(), StdViewDockUndockFullscreen::createAction(), StdCmdDockViewMenu::createAction(), StdCmdToolBarMenu::createAction(), StdCmdStatusBar::createAction(), StdCmdWindowsMenu::createAction(), Gui::MainWindow::createMimeDataFromSelection(), Gui::Document::createView(), MeshGui::ViewProviderMeshCurvature::curvatureInfoCallback(), InspectionGui::ViewProviderProxyObject::customEvent(), Gui::SoFCColorGradient::customize(), Gui::BlankWorkbench::deactivated(), Gui::MDIView::deleteSelf(), PartDesignGui::WorkflowManager::determineWorkflow(), draftguitools.gui_snapper.Snapper::device_pixel_ratio(), SketcherGui::DrawSketchHandler::devicePixelRatio(), femsolver.report::displayGui(), Gui::DocumentObjectItem::displayStatusInfo(), Gui::Dialog::DlgActivateWindowImp::DlgActivateWindowImp(), Gui::Dialog::DlgCustomizeImp::DlgCustomizeImp(), MeshGui::DlgEvaluateMeshImp::DlgEvaluateMeshImp(), Gui::Dialog::DlgPreferencesImp::DlgPreferencesImp(), Gui::ViewProviderTextDocument::doubleClicked(), DrawingGui::ViewProviderDrawingPage::doubleClicked(), SpreadsheetGui::ViewProviderSheet::doubleClicked(), TechDrawGui::ViewProviderPage::doubleClicked(), Gui::TDragger::drag(), Gui::RDragger::drag(), Gui::View3DInventor::dropEvent(), Gui::View3DInventorViewer::dropEvent(), Gui::TreeWidget::dropEvent(), Gui::EditorView::EditorView(), Gui::ProgressBar::eventFilter(), FilterStatusBar::eventFilter(), SketcherGui::EditDatumDialog::exec(), Gui::SelectModule::exportHandler(), Gui::Application::exportTo(), Gui::ViewProviderGroupExtension::extensionOnDelete(), TechDrawGui::TaskSectionView::failNoObject(), draftutils.utils::filter_objects_for_modifiers(), TechDrawGui::DrawGuiUtil::findPage(), Gui::ManualAlignment::finish(), draftguitools.gui_snaps::get_snap_statusbar_widget(), draftguitools.gui_snapper.Snapper::get_snap_toolbar(), Gui::Document::getActiveView(), PartDesignGui::getBody(), PartDesignGui::getBodyFor(), Gui::Dialog::DownloadManager::getInstance(), PartDesignGui::getPartFor(), PartDesignGui::getReferencedSelection(), PartGui::TaskCheckGeometryResults::goCheck(), Gui::SoFCSelection::handleEvent(), draftutils.init_draft_statusbar::hide_draft_statusbar(), Gui::PythonDebugger::hideDebugMarker(), Gui::Application::importFrom(), Gui::SelectModule::importHandler(), draftutils.init_draft_statusbar::init_draft_statusbar_scale(), draftutils.init_draft_statusbar::init_draft_statusbar_snap(), Gui::MainWindow::insertFromMimeData(), InspectionGui::ViewProviderInspection::inspectCallback(), MeshGui::DockEvaluateMeshImp::instance(), TestGui::UnitTestDialog::instance(), Gui::Command::invoke(), StdCmdPaste::isActive(), CmdTestMDI1::isActive(), CmdTestMDI2::isActive(), CmdTestMDI3::isActive(), StdOrthographicCamera::isActive(), StdPerspectiveCamera::isActive(), StdCmdFreezeViews::isActive(), StdCmdToggleClipPlane::isActive(), StdViewDock::isActive(), StdViewUndock::isActive(), StdViewFullscreen::isActive(), StdViewDockUndockFullscreen::isActive(), StdCmdToggleNavigation::isActive(), StdCmdAxisCross::isActive(), StdViewZoomIn::isActive(), StdViewZoomOut::isActive(), StdCmdMeasureDistance::isActive(), StdCmdTextureMapping::isActive(), StdCmdArrangeIcons::isActive(), StdCmdTileWindows::isActive(), StdCmdCascadeWindows::isActive(), StdCmdCloseActiveWindow::isActive(), StdCmdCloseAllWindows::isActive(), StdCmdActivateNextWindow::isActive(), StdCmdActivatePrevWindow::isActive(), StdCmdStatusBar::isActive(), draftutils.init_draft_statusbar::label_to_scale(), Gui::Dialog::AboutDialog::linkActivated(), Gui::Dialog::DlgGeneralImp::loadSettings(), StartGui::Workbench::loadStartPage(), draftguitools.gui_snapper.Snapper::makeSnapToolBar(), Gui::DAG::Model::mouseDoubleClickEvent(), Gui::TreeView::mouseDoubleClickEvent(), Gui::Dialog::DlgCustomToolbarsImp::moveDownCustomCommand(), Gui::Dialog::DlgCustomToolbarsImp::moveUpCustomCommand(), PartDesignGui::needActiveBodyError(), Gui::Dialog::DlgMacroRecordImp::on_buttonStart_clicked(), Gui::Dialog::DlgMacroExecuteImp::on_createButton_clicked(), Gui::Dialog::DlgMacroExecuteImp::on_editButton_clicked(), PartGui::DlgPartImportIgesImp::onChooseFileName(), PartGui::DlgPartImportStepImp::onChooseFileName(), TechDrawGui::ViewProviderLeader::onDelete(), TechDrawGui::ViewProviderProjGroup::onDelete(), TechDrawGui::ViewProviderProjGroupItem::onDelete(), TechDrawGui::ViewProviderViewPart::onDelete(), TechDrawGui::ViewProviderWeld::onDelete(), TechDrawGui::ViewProviderPage::onDelete(), TechDrawGui::ViewProviderTemplate::onDelete(), WebGui::BrowserView::onDownloadRequested(), Gui::Dialog::UndoDialog::onFetchInfo(), Gui::Dialog::RedoDialog::onFetchInfo(), Gui::PythonConsole::onInsertFileName(), Gui::Application::onLastWindowClosed(), WebGui::BrowserView::onLinkClicked(), WebGui::BrowserView::onLinkHovered(), WebGui::BrowserView::onLoadFinished(), WebGui::BrowserView::onLoadStarted(), WebGui::BrowserView::onOpenLinkInNewWindow(), Gui::TreeWidget::onStartEditing(), TechDrawGui::TaskCosVertex::onTrackerClicked(), TechDrawGui::TaskLeaderLine::onTrackerClicked(), TechDrawGui::TaskLeaderLine::onTrackerFinished(), WebGui::BrowserView::onViewSource(), Gui::Application::open(), OpenURLInBrowser(), SpreadsheetGui::SheetTableView::pasteClipboard(), StdCmdExpression::pasteExpressions(), Gui::View3DInventorViewer::printDimension(), TechDrawGui::MDIViewPage::printPdf(), Gui::ManualAlignment::probePickedCallback(), DrawSketchHandlerFillet::releaseButton(), Gui::Dialog::DlgCustomToolbarsImp::removeCustomCommand(), Gui::Dialog::DlgCustomToolbarsImp::removeCustomToolbar(), Gui::TaskView::TaskView::removeDialog(), Gui::DockWindowManager::removeDockWindow(), TechDrawGui::ViewProviderPage::removeMDIView(), Gui::Dialog::DlgCustomToolbarsImp::renameCustomToolbar(), Gui::SequencerBar::resetData(), Gui::MenuManager::retranslate(), Gui::SelectionSingleton::rmvPreselect(), Gui::SelectionSingleton::rmvSelection(), Gui::Application::runApplication(), Gui::Document::save(), Gui::Document::saveAll(), Gui::Document::saveAs(), Gui::Document::saveCopy(), Gui::AutoSaver::saveDocument(), TechDrawGui::MDIViewPage::saveDXF(), Gui::Dialog::DlgGeneralImp::saveSettings(), TechDrawGui::MDIViewPage::saveSVG(), Gui::Application::sCreateViewer(), Gui::PropertyEditor::LinkSelection::select(), Gui::SelectionSingleton::selStackGoBack(), Gui::SelectionSingleton::selStackGoForward(), Gui::Application::sendHasMsgToActiveView(), Gui::Application::sendHasMsgToFocusView(), Gui::StatusBarObserver::SendLog(), Gui::Application::sendMsgToActiveView(), Gui::Application::sendMsgToFocusView(), Gui::SequencerDialog::SequencerDialog(), Gui::Application::setActiveDocument(), Gui::Document::setActiveView(), Gui::Document::setActiveWindow(), SpreadsheetGui::WorkbenchHelper::setBackgroundColor(), Gui::View3DInventor::setCurrentViewMode(), Gui::MDIView::setCurrentViewMode(), SketcherGui::DrawSketchHandler::setCursor(), draftguitools.gui_snapper.Snapper::setCursor(), Gui::Document::setEdit(), FemGui::ViewProviderFemMeshShapeNetgen::setEdit(), RaytracingGui::ViewProviderLux::setEdit(), RaytracingGui::ViewProviderPovray::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), SpreadsheetGui::ViewProviderSheet::setEdit(), femsolver.solverbase.ViewProxy::setEdit(), Gui::Application::setEditDocument(), SpreadsheetGui::WorkbenchHelper::setForegroundColor(), Gui::SelectionSingleton::setPreselect(), Gui::SelectionSingleton::setPreselectCoord(), Gui::SelectionSingleton::setSelection(), Gui::PropertyView::setShowAll(), Gui::StdCmdDescription::setSource(), Gui::Application::setStyleSheet(), Gui::SequencerBar::setText(), Gui::DockWindowManager::setup(), Gui::MenuManager::setup(), Gui::ToolBarManager::setup(), Gui::Application::sGetMainWindow(), SpreadsheetGui::SheetView::SheetView(), draftguitools.gui_snapper.Snapper::show(), draftutils.init_draft_statusbar::show_draft_statusbar(), Gui::PythonDebugger::showDebugMarker(), Gui::ControlSingleton::showDialog(), Gui::TaskView::TaskView::showDialog(), DrawingGui::ViewProviderDrawingPage::showDrawingView(), Gui::EditorView::showEvent(), Gui::TextDocumentEditorView::showEvent(), Gui::ManualAlignment::showInstructions(), TechDrawGui::ViewProviderPage::showMDIViewPage(), Gui::Dialog::DlgCheckableMessageBox::showMessage(), Gui::SequencerBar::showRemainingTime(), SpreadsheetGui::ViewProviderSheet::showSpreadsheetView(), TechDrawGui::MDIViewPage::showStatusMsg(), Gui::Application::sInsert(), Gui::Application::slotActivatedObject(), Gui::Application::slotActiveDocument(), Gui::Document::slotChangedObject(), Gui::Application::slotChangedObject(), Gui::SelectionSingleton::slotDeletedObject(), Gui::Document::slotRecomputed(), Gui::Document::slotRedoDocument(), Gui::Document::slotTouchedObject(), Gui::Document::slotUndoDocument(), Gui::Application::sOpen(), Gui::Application::sSetActiveDocument(), Gui::Application::sShowPreferences(), PartGui::BoxSelection::start(), Gui::ManualAlignment::startAlignment(), TechDrawGui::TaskCosVertex::startTracker(), TechDrawGui::TaskLeaderLine::startTracker(), SketcherGui::DrawSketchHandler::suggestedConstraintsPixmaps(), Gui::MainWindow::switchToTopLevelMode(), Gui::ToolBarManager::toolBars(), Gui::Application::tryClose(), SketcherGui::DrawSketchHandler::unsetCursor(), SketcherGui::ViewProviderSketch::unsetEdit(), Gui::CommandPy::update(), MeshPartGui::CurveOnMeshHandler::Private::vertexCallback(), InspectionGui::VisualInspection::VisualInspection(), SandboxGui::Workbench::Workbench(), Gui::WorkbenchComboBox::WorkbenchComboBox(), Gui::MDIView::~MDIView(), Gui::View3DInventorViewer::~View3DInventorViewer(), and SpreadsheetGui::ViewProviderSheet::~ViewProviderSheet().
getPyTypeObjectForTypeName()
template<typename qttype > PyTypeObject* Gui::getPyTypeObjectForTypeName ()
GetWidgetFactorySupplier()
WidgetFactorySupplier& Gui::GetWidgetFactorySupplier ()
References Gui::WidgetFactorySupplier::instance().
Referenced by Gui::Application::Application(), and Gui::Dialog::DlgCustomizeImp::DlgCustomizeImp().
OpenURLInBrowser()
bool Gui::OpenURLInBrowser (const char * URL)
opens a URL in the system Browser
References getMainWindow().
Referenced by StdCmdOnlineHelpWebsite::activated(), StdCmdFreeCADWebsite::activated(), StdCmdFreeCADUserHub::activated(), StdCmdFreeCADPowerUserHub::activated(), StdCmdFreeCADForum::activated(), StdCmdFreeCADFAQ::activated(), and StdCmdPythonWebsite::activated().
promptEnd()
static const QChar Gui::promptEnd (QLatin1Char(' ')) static
Referenced by promptLength().
promptLength()
int Gui::promptLength (const QString & lineStr)
References promptEnd().
Referenced by Gui::PythonConsole::inputBegin(), and stripPromptFrom().
qt_getCppPointer()
void* Gui::qt_getCppPointer (const Py::Object & pyobject, const char * shiboken, const char * unwrap)
Referenced by Gui::PythonWrapper::toQGraphicsItem(), and Gui::PythonWrapper::toQObject().
qt_identifyType()
const char* Gui::qt_identifyType (QObject * ptr, const char * pyside)
Referenced by Gui::PythonWrapper::createChildrenNameAttributes().
qt_wrapInstance()
template<typename qttype > Py::Object Gui::qt_wrapInstance (qttype object, const char * className, const char * shiboken, const char * pyside, const char * wrap)
schemaTranslatePoint()
std::array< std::pair< double, std::string >, 3 > Gui::schemaTranslatePoint (double x, double y, double z, double precision)
References Base::Quantity::MilliMetre, Base::UnitsApi::schemaTranslate(), and Base::Quantity::setValue().
Referenced by Gui::SoFCSelection::handleEvent(), and Gui::SelectionSingleton::setPreselectCoord().
Selection()
SelectionSingleton& Gui::Selection (void)
Get the global instance.
References Selection().
Referenced by DrawingGui::TaskProjection::accept(), MeshGui::TaskDecimating::accept(), MeshPartGui::Tessellation::accept(), ReenGui::FitBSplineSurfaceWidget::accept(), SurfaceGui::FillingPanel::accept(), SurfaceGui::FillingEdgePanel::accept(), SurfaceGui::GeomFillSurface::accept(), SurfaceGui::SectionsPanel::accept(), StdCmdExport::activated(), StdCmdDuplicateSelection::activated(), StdCmdSelectAll::activated(), StdCmdDelete::activated(), StdCmdPlacement::activated(), StdCmdTransformManip::activated(), StdCmdAlignment::activated(), StdCmdEdit::activated(), StdCmdExpression::activated(), StdCmdLinkMakeGroup::activated(), StdCmdLinkMake::activated(), StdCmdLinkMakeRelative::activated(), StdCmdLinkSelectLinked::activated(), StdCmdLinkSelectLinkedFinal::activated(), StdCmdLinkSelectAllLinks::activated(), StdCmdToggleVisibility::activated(), StdCmdToggleSelectability::activated(), StdCmdShowSelection::activated(), StdCmdHideSelection::activated(), StdCmdSelectVisibleObjects::activated(), StdCmdTreeSelectAllInstances::activated(), StdCmdSelBack::activated(), StdCmdSelForward::activated(), StdTreeDrag::activated(), DrawSketchHandlerGenConstraint::activated(), DrawSketchHandlerCoincident::activated(), DrawSketchHandlerFillet::activated(), DrawSketchHandlerTrimming::activated(), DrawSketchHandlerExtend::activated(), DrawSketchHandlerExternal::activated(), DrawSketchHandlerCarbonCopy::activated(), PartGui::FaceColors::Private::addFacesToSelection(), PartDesignGui::TaskTransformedParameters::addReferenceSelectionGate(), Gui::ElementColors::Private::apply(), MeshPartGui::CrossSections::apply(), PartGui::CrossSections::apply(), Gui::Dialog::DlgPropertyLink::attachObserver(), Gui::SelectionObserver::attachSelection(), PartGui::ViewProviderPartExt::changeFaceColors(), Gui::View3DInventorViewer::checkGroupOnTop(), Gui::SoFCSelectionCounter::checkRenderCache(), SketcherGui::ConstraintView::contextMenuEvent(), Gui::DAG::Model::contextMenuEvent(), Gui::MainWindow::createMimeDataFromSelection(), SketcherGui::ViewProviderSketch::deleteSelected(), SketcherGui::ConstraintView::deleteSelectedItems(), SketcherGui::ElementView::deleteSelectedItems(), Gui::Dialog::DlgPropertyLink::detachObserver(), Gui::SelectionObserver::detachSelection(), SketcherGui::ViewProviderSketch::detectPreselection(), Gui::Dialog::DlgDisplayPropertiesImp::DlgDisplayPropertiesImp(), PartGui::DlgExtrusion::DlgExtrusion(), PartGui::DlgFilletEdges::DlgFilletEdges(), PartGui::DlgRevolution::DlgRevolution(), Gui::SoFCSelection::doAction(), Gui::SoFCUnifiedSelection::doAction(), SketcherGui::ViewProviderSketch::doBoxSelection(), PartDesignGui::TaskDressUpParameters::doubleClicked(), Gui::TreeWidget::dropEvent(), Gui::ElementColors::ElementColors(), PartGui::evaluateAngularPreSelection(), PartGui::evaluateLinearPreSelection(), PartDesignGui::TaskDressUpParameters::exitSelectionMode(), PartDesignGui::TaskTransformedParameters::exitSelectionMode(), Gui::Application::exportTo(), PartGui::FaceColors::FaceColors(), PartGui::DlgFilletEdges::findShapes(), Gui::Command::getSelection(), PartGui::TaskCheckGeometryResults::goCheck(), PartGui::goDimensionAngularRoot(), PartGui::goDimensionLinearRoot(), Gui::SoFCSelection::handleEvent(), Gui::SoFCUnifiedSelection::handleEvent(), Gui::MainWindow::insertFromMimeData(), StdCmdExpression::isActive(), StdCmdCopy::isActive(), StdCmdDuplicateSelection::isActive(), StdCmdDelete::isActive(), StdCmdTransformManip::isActive(), StdCmdAlignment::isActive(), StdCmdEdit::isActive(), StdCmdLinkMakeRelative::isActive(), StdCmdLinkSelectAllLinks::isActive(), StdCmdToggleVisibility::isActive(), StdCmdToggleSelectability::isActive(), StdCmdShowSelection::isActive(), StdCmdHideSelection::isActive(), StdCmdSetAppearance::isActive(), StdCmdTreeSelectAllInstances::isActive(), StdCmdSelBack::isActive(), StdCmdSelForward::isActive(), Gui::TreeWidget::itemSearch(), Gui::Dialog::DlgPropertyLink::leaveEvent(), Gui::ElementColors::leaveEvent(), Gui::DockWnd::SelectionView::leaveEvent(), Gui::TreeWidget::leaveEvent(), SketcherGui::TaskSketcherElements::leaveEvent(), Gui::SelectionFilter::match(), PartGui::Mirroring::Mirroring(), SketcherGui::ViewProviderSketch::mouseButtonPressed(), DrawSketchHandlerExternal::mouseMove(), DrawSketchHandlerCarbonCopy::mouseMove(), Gui::DAG::Model::mousePressEvent(), SketcherGui::TaskSketcherConstrains::on_listWidgetConstraints_itemSelectionChanged(), SketcherGui::TaskSketcherElements::on_listWidgetElements_currentFilterChanged(), SketcherGui::TaskSketcherElements::on_listWidgetElements_filterShortcutPressed(), SketcherGui::TaskSketcherElements::on_listWidgetElements_itemEntered(), SketcherGui::TaskSketcherElements::on_listWidgetElements_itemSelectionChanged(), PartDesignGui::TaskTransformedParameters::onButtonAddFeature(), PartDesignGui::TaskDressUpParameters::onButtonRefAdd(), FemGui::TaskFemConstraint::onButtonReference(), PartDesignGui::TaskDressUpParameters::onButtonRefRemove(), PartDesignGui::TaskTransformedParameters::onButtonRemoveFeature(), SketcherGui::ViewProviderSketch::onDelete(), PartDesignGui::TaskFeaturePick::onItemSelectionChanged(), Gui::TreeWidget::onPreSelectTimer(), Gui::ElementColors::Private::onSelectionChanged(), MeshInfoWatcher::onSelectionChanged(), FemGui::TaskCreateNodeSet::onSelectionChanged(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), FemGui::TaskFemConstraintGear::onSelectionChanged(), PartDesignGui::TaskChamferParameters::onSelectionChanged(), PartDesignGui::TaskDraftParameters::onSelectionChanged(), PartDesignGui::TaskFeaturePick::onSelectionChanged(), PartDesignGui::TaskFilletParameters::onSelectionChanged(), PartDesignGui::TaskThicknessParameters::onSelectionChanged(), DrawSketchHandlerExternal::onSelectionChanged(), DrawSketchHandlerCarbonCopy::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), TechDrawGui::MDIViewPage::onSelectionChanged(), PartDesignGui::TaskSketchBasedParameters::onSelectReference(), Gui::TreeWidget::onSelectTimer(), Gui::PropertyView::onTimer(), SurfaceGui::FillingPanel::open(), SurfaceGui::FillingEdgePanel::open(), SurfaceGui::FillingVertexPanel::open(), SurfaceGui::GeomFillSurface::open(), SurfaceGui::SectionsPanel::open(), MeshGui::ParametersDialog::ParametersDialog(), Gui::Dialog::Placement::Placement(), TechDrawGui::MDIViewPage::preSelectionChanged(), TechDrawGui::MDIViewPage::print(), Gui::NavigationStyle::processEvent(), SketcherGui::ViewProviderSketch::purgeHandler(), SketcherGui::DrawSketchHandler::quit(), SurfaceGui::FillingPanel::reject(), SurfaceGui::FillingEdgePanel::reject(), SurfaceGui::GeomFillSurface::reject(), SurfaceGui::SectionsPanel::reject(), DrawSketchHandlerGenConstraint::releaseButton(), DrawSketchHandlerCoincident::releaseButton(), DrawSketchHandlerFillet::releaseButton(), Gui::SelectionObjectPy::remove(), MeshGui::RemoveComponents::RemoveComponents(), Gui::ElementColors::Private::reset(), PartGui::TaskMeasureLinear::resetDialogSlot(), PartGui::TaskMeasureAngular::resetDialogSlot(), DrawSketchHandlerGenConstraint::resetOngoingSequences(), Gui::SelectionSingleton::sAddSelection(), Gui::SelectionSingleton::sAddSelectionGate(), TechDrawGui::QGVPage::saveSvg(), TechDrawGui::MDIViewPage::sceneSelectionChanged(), Gui::SelectionSingleton::sClearSelection(), Gui::SelectionSingleton::sCountObjectsOfType(), Gui::TreeWidget::scrollItemToTop(), ReverseEngineeringGui::SegmentationManual::SegmentationManual(), Gui::PropertyEditor::LinkSelection::select(), Gui::View3DInventorViewer::selectAll(), Gui::TreeWidget::selectAll(), Selection(), PartGui::TaskMeasureLinear::selection1Slot(), PartGui::TaskMeasureAngular::selection1Slot(), PartGui::TaskMeasureLinear::selection2Slot(), PartGui::TaskMeasureAngular::selection2Slot(), Gui::DAG::Model::selectionChanged(), PartGui::TaskMeasureLinear::selectionClearDelayedSlot(), PartGui::TaskMeasureAngular::selectionClearDelayedSlot(), Gui::SelectionLogDisabler::SelectionLogDisabler(), Gui::DocumentItem::selectItems(), Gui::SelectionSingleton::sEnablePickedList(), Gui::View3DInventorViewer::setDocument(), Gui::Document::setEdit(), FemGui::ViewProviderFemConstraintBearing::setEdit(), FemGui::ViewProviderFemConstraintContact::setEdit(), FemGui::ViewProviderFemConstraintDisplacement::setEdit(), FemGui::ViewProviderFemConstraintFixed::setEdit(), FemGui::ViewProviderFemConstraintFluidBoundary::setEdit(), FemGui::ViewProviderFemConstraintForce::setEdit(), FemGui::ViewProviderFemConstraintGear::setEdit(), FemGui::ViewProviderFemConstraintHeatflux::setEdit(), FemGui::ViewProviderFemConstraintInitialTemperature::setEdit(), FemGui::ViewProviderFemConstraintPlaneRotation::setEdit(), FemGui::ViewProviderFemConstraintPressure::setEdit(), FemGui::ViewProviderFemConstraintPulley::setEdit(), FemGui::ViewProviderFemConstraintTemperature::setEdit(), FemGui::ViewProviderFemConstraintTransform::setEdit(), FemGui::ViewProviderFemMeshShapeNetgen::setEdit(), PartGui::ViewProviderOffset::setEdit(), PartGui::ViewProviderThickness::setEdit(), PartDesignGui::ViewProviderHole::setEdit(), PartDesignGui::ViewProviderPrimitive::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), TechDrawGui::ViewProviderBalloon::setEdit(), TechDrawGui::ViewProviderLeader::setEdit(), TechDrawGui::ViewProviderProjGroup::setEdit(), TechDrawGui::ViewProviderRichAnno::setEdit(), TechDrawGui::ViewProviderViewPart::setEdit(), TechDrawGui::ViewProviderViewSection::setEdit(), TechDrawGui::ViewProviderWeld::setEdit(), Gui::ViewProviderLink::setEdit(), PartDesignGui::ViewProvider::setEdit(), PartDesignGui::ViewProviderBoolean::setEdit(), PartDesignGui::ViewProviderDatum::setEdit(), PartDesignGui::ViewProviderShapeBinder::setEdit(), PartDesignGui::ViewProviderSubShapeBinder::setEdit(), TechDrawGui::ViewProviderGeomHatch::setEdit(), TechDrawGui::ViewProviderHatch::setEdit(), PartDesignGui::TaskDressUpParameters::setSelection(), FemGui::TaskFemConstraint::setSelection(), TechDrawGui::MDIViewPage::setTreeToSceneSelect(), SketcherGui::SketchSelection::setUp(), MeshGui::Workbench::setupContextMenu(), PartDesignGui::Workbench::setupContextMenu(), Gui::StdWorkbench::setupContextMenu(), PartGui::DlgFilletEdges::setupFillet(), Gui::SelectionSingleton::sGetCompleteSelection(), Gui::SelectionSingleton::sGetPickedList(), Gui::SelectionSingleton::sGetPreselection(), Gui::SelectionSingleton::sGetSelection(), Gui::SelectionSingleton::sGetSelectionEx(), Gui::SelectionSingleton::sGetSelectionFromStack(), PartGui::ShapeBuilderWidget::ShapeBuilderWidget(), Gui::SelectionSingleton::sHasSelection(), Gui::SelectionSingleton::sHasSubSelection(), Gui::TaskView::TaskWatcherCommandsEmptySelection::shouldShow(), Gui::SelectionSingleton::sIsSelected(), Gui::Application::slotDeleteDocument(), Gui::SelectionSingleton::sPushSelStack(), Gui::SelectionSingleton::sRemoveSelection(), Gui::SelectionSingleton::sRemoveSelectionGate(), Gui::SelectionSingleton::sRemPreselection(), Gui::SelectionSingleton::sSetPreselection(), Gui::SelectionSingleton::sSetVisible(), PartGui::BoxSelection::start(), SketcherGui::SuggestAutoMapMode(), Gui::SelectionSingleton::sUpdateSelection(), Gui::TaskView::TaskAppearance::TaskAppearance(), PartDesignGui::TaskDatumParameters::TaskDatumParameters(), MeshGui::TaskDecimating::TaskDecimating(), DrawingGui::TaskOrthoViews::TaskOrthoViews(), Gui::TaskView::TaskSelectLinkProperty::TaskSelectLinkProperty(), Gui::TaskView::TaskSketcherCreateCommands::TaskSketcherCreateCommands(), SketcherGui::TaskSketcherGeneral::TaskSketcherGeneral(), MeshGui::TaskSmoothing::TaskSmoothing(), Gui::TaskView::TaskView::TaskView(), FemGui::ViewProviderFemConstraint::unsetEdit(), SketcherGui::ViewProviderSketch::unsetEdit(), PartDesignGui::ViewProvider::unsetEdit(), Gui::DocumentItem::updateItemSelection(), Gui::View3DInventorViewer::viewSelection(), Gui::Dialog::DlgDisplayPropertiesImp::~DlgDisplayPropertiesImp(), PartGui::DlgExtrusion::~DlgExtrusion(), PartGui::DlgFilletEdges::~DlgFilletEdges(), PartGui::DlgProjectionOnSurface::~DlgProjectionOnSurface(), PartGui::DlgRevolution::~DlgRevolution(), DrawSketchHandlerCarbonCopy::~DrawSketchHandlerCarbonCopy(), DrawSketchHandlerCoincident::~DrawSketchHandlerCoincident(), DrawSketchHandlerExtend::~DrawSketchHandlerExtend(), DrawSketchHandlerExternal::~DrawSketchHandlerExternal(), DrawSketchHandlerFillet::~DrawSketchHandlerFillet(), DrawSketchHandlerGenConstraint::~DrawSketchHandlerGenConstraint(), DrawSketchHandlerTrimming::~DrawSketchHandlerTrimming(), Gui::ElementColors::~ElementColors(), PartGui::FaceColors::~FaceColors(), SurfaceGui::FillingEdgePanel::~FillingEdgePanel(), SurfaceGui::FillingVertexPanel::~FillingVertexPanel(), Gui::SelectionLogDisabler::~SelectionLogDisabler(), PartGui::ShapeBuilderWidget::~ShapeBuilderWidget(), PartGui::SweepWidget::~SweepWidget(), Gui::TaskView::TaskAppearance::~TaskAppearance(), PartDesignGui::TaskChamferParameters::~TaskChamferParameters(), PartGui::TaskCheckGeometryResults::~TaskCheckGeometryResults(), FemGui::TaskCreateNodeSet::~TaskCreateNodeSet(), PartDesignGui::TaskDatumParameters::~TaskDatumParameters(), PartDesignGui::TaskDraftParameters::~TaskDraftParameters(), PartDesignGui::TaskDressUpParameters::~TaskDressUpParameters(), PartDesignGui::TaskFilletParameters::~TaskFilletParameters(), PartGui::TaskMeasureAngular::~TaskMeasureAngular(), PartGui::TaskMeasureLinear::~TaskMeasureLinear(), Gui::TaskView::TaskSelectLinkProperty::~TaskSelectLinkProperty(), PartDesignGui::TaskSketchBasedParameters::~TaskSketchBasedParameters(), Gui::TaskView::TaskSketcherCreateCommands::~TaskSketcherCreateCommands(), SketcherGui::TaskSketcherGeneral::~TaskSketcherGeneral(), PartDesignGui::TaskThicknessParameters::~TaskThicknessParameters(), PartDesignGui::TaskTransformedParameters::~TaskTransformedParameters(), Gui::TaskView::TaskView::~TaskView(), and PartGui::ThicknessWidget::~ThicknessWidget().
stripPromptFrom()
QString Gui::stripPromptFrom (const QString & lineStr)
References promptLength().
Referenced by Gui::PythonConsole::createMimeDataFromSelection(), and Gui::PythonConsole::keyPressEvent().
validateInput()
bool Gui::validateInput (QWidget * parent, const QString & input)
Referenced by Gui::Dialog::ParameterValue::onCreateBoolItem(), Gui::Dialog::ParameterValue::onCreateFloatItem(), Gui::Dialog::ParameterValue::onCreateIntItem(), Gui::Dialog::ParameterGroup::onCreateSubgroup(), Gui::Dialog::ParameterValue::onCreateTextItem(), Gui::Dialog::ParameterValue::onCreateUIntItem(), Gui::Dialog::ParameterGroupItem::setData(), and Gui::Dialog::ParameterValueItem::setData().
WidgetFactory()
WidgetFactoryInst& Gui::WidgetFactory ()
References Gui::WidgetFactoryInst::instance().
Referenced by Gui::UiLoader::createWidget(), and Gui::Dialog::DlgCustomizeImp::DlgCustomizeImp().
WorkbenchFactory()
WorkbenchFactoryInst& Gui::WorkbenchFactory ()
References Gui::WorkbenchFactoryInst::instance().
Variable Documentation
FreeCADGui_methods
struct PyMethodDef Gui::FreeCADGui_methods[]
Initial value:
= {
    {"subgraphFromObject",FreeCADGui_subgraphFromObject,METH_VARARGS,
     "subgraphFromObject(object) -> Node\n\n"
     "Return the Inventor subgraph to an object"},
    {"exportSubgraph",FreeCADGui_exportSubgraph,METH_VARARGS,
     "exportSubgraph(Node, File or Buffer, [Format='VRML']) -> None\n\n"
     "Exports the sub-graph in the requested format"
     "The format string can be VRML or IV"},
    {"getSoDBVersion",FreeCADGui_getSoDBVersion,METH_VARARGS,
     "getSoDBVersion() -> String\n\n"
     "Return a text string containing the name\n"
     "of the Coin library and version information"},
    {NULL, NULL, 0, NULL}
}
Referenced by Gui::Application::Application().