FreeCAD: Gui::Dialog::DlgRunExternal Class Reference
Gui::Dialog::DlgRunExternal Class Reference
The DlgRunExternal class implements a dialog to start and control external programs to edit FreeCAD controlled content.
#include <DlgRunExternal.h>
Public Member Functions
DlgRunExternal (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
Constructs a DlgRunExternal which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
int Do (void)
virtual ~DlgRunExternal ()
Destroys the object and frees any allocated resources.
Public Attributes
QStringList arguments
QString ProcName
Protected Slots
virtual void abort (void)
virtual void accept (void)
virtual void advanced (void)
void finished (int exitCode, QProcess::ExitStatus exitStatus)
void on_chooseProgram_clicked ()
virtual void reject (void)
Protected Attributes
bool advancedHidden
QProcess process
Detailed Description
The DlgRunExternal class implements a dialog to start and control external programs to edit FreeCAD controlled content.
Author
Jürgen Riegel
Constructor & Destructor Documentation
DlgRunExternal()
DlgRunExternal::DlgRunExternal (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Constructs a DlgRunExternal which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
References abort(), accept(), advanced(), Gui::Dialog::Ui_DlgRunExternal::buttonAbort, Gui::Dialog::Ui_DlgRunExternal::buttonAccept, Gui::Dialog::Ui_DlgRunExternal::buttonAdvanced, Gui::Dialog::Ui_DlgRunExternal::buttonDiscard, draftgeoutils.intersections::connect(), Gui::Dialog::Ui_DlgRunExternal::extensionWidget, finished(), Gui::Dialog::Ui_DlgRunExternal::gridLayout, process, reject(), and Gui::Dialog::Ui_DlgRunExternal::setupUi().
~DlgRunExternal()
DlgRunExternal::~DlgRunExternal () virtual
Destroys the object and frees any allocated resources.
Member Function Documentation
abort
void DlgRunExternal::abort (void) protected virtual slot
References process, and reject().
Referenced by PathPythonGui.simple_edit_panel.SimpleEditPanel::clicked(), DlgRunExternal(), and femsolver.run.Machine::run().
accept
void DlgRunExternal::accept (void) protected virtual slot
Referenced by femexamples.examplesgui.FemExamples::clicked(), DlgRunExternal(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
advanced
void DlgRunExternal::advanced (void) protected virtual slot
References advancedHidden, and Gui::Dialog::Ui_DlgRunExternal::extensionWidget.
Referenced by DlgRunExternal().
Do()
int DlgRunExternal::Do (void)
References arguments, Gui::Dialog::Ui_DlgRunExternal::buttonAccept, Gui::Dialog::Ui_DlgRunExternal::buttonDiscard, process, ProcName, Gui::Dialog::Ui_DlgRunExternal::programName, and Gui::Dialog::Ui_DlgRunExternal::programPath.
Referenced by Gui::Dialog::DlgEditFileIncludePropertyExternal::Do().
finished
void DlgRunExternal::finished (int exitCode, QProcess::ExitStatus exitStatus) protected slot
References Gui::Dialog::Ui_DlgRunExternal::buttonAbort, Gui::Dialog::Ui_DlgRunExternal::buttonAccept, and Gui::Dialog::Ui_DlgRunExternal::buttonDiscard.
Referenced by femtools.ccxtools.FemToolsCcx::ccx_run(), and DlgRunExternal().
on_chooseProgram_clicked
void DlgRunExternal::on_chooseProgram_clicked () protected slot
References Gui::Dialog::Ui_DlgRunExternal::programPath.
reject
void DlgRunExternal::reject (void) protected virtual slot
Referenced by abort(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), DlgRunExternal(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
Member Data Documentation
advancedHidden
bool Gui::Dialog::DlgRunExternal::advancedHidden protected
Referenced by advanced().
arguments
QStringList Gui::Dialog::DlgRunExternal::arguments
Referenced by prototype.Node::addtofreecad(), Gui::Dialog::DlgEditFileIncludePropertyExternal::Do(), Do(), prototype.Node::pprint(), and prototype.Node::pprint2().
process
QProcess Gui::Dialog::DlgRunExternal::process protected
Referenced by abort(), DlgRunExternal(), and Do().
ProcName
QString Gui::Dialog::DlgRunExternal::ProcName
Referenced by Do().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgRunExternal.h
FreeCAD/src/Gui/DlgRunExternal.cpp