FreeCAD: SMESH_Mesh Class Reference
SMESH_Mesh Class Reference
#include <SMESH_Mesh.hxx>
Classes
class SubMeshHolder
struct TCallUp
Public Types
typedef boost::shared_ptr< SMDS_Iterator< SMESH_Group * > > GroupIteratorPtr
typedef TopTools_IndexedDataMapOfShapeListOfShape TAncestorMap
Return data map of descendant to ancestor shapes.
Public Member Functions
SMESH_Group * AddGroup (const SMDSAbs_ElementType theType, const char *theName, int &theId, const TopoDS_Shape &theShape=TopoDS_Shape(), const SMESH_PredicatePtr &thePredicate=SMESH_PredicatePtr())
SMESH_Group * AddGroup (SMESHDS_GroupBase *groupDS)
Creates a group based on an existing SMESHDS group. Group ID should be unique.
SMESH_Hypothesis::Hypothesis_Status AddHypothesis (const TopoDS_Shape &aSubShape, int anHypId, std::string *error=0)
int CGNSToMesh (const char *theFileName, const int theMeshIndex, std::string &theMeshName)
Reads the given mesh from the CGNS file.
void Clear ()
Remove all nodes and elements.
void ClearLog ()
void ClearMeshOrder ()
remove submesh order from Mesh
void ClearSubMesh (const int theShapeId)
Remove all nodes and elements of indicated shape.
SMESH_Group * ConvertToStandalone (int theGroupID)
Convert group on geometry into standalone group.
int DATToMesh (const char *theFileName)
ostream & Dump (ostream &save)
void ExportCGNS (const char *file, const SMESHDS_Mesh *mesh, const char *meshName=0)
Export the mesh to the CGNS file.
void ExportDAT (const char *file, const SMESHDS_Mesh *meshPart=0)
Export the mesh to a DAT file.
void ExportGMF (const char *file, const SMESHDS_Mesh *mesh, bool withRequiredGroups=true)
Export the mesh to a GMF file.
void ExportMED (const char *theFile, const char *theMeshName=NULL, bool theAutoGroups=true, int theVersion=0, const SMESHDS_Mesh *theMeshPart=0, bool theAutoDimension=false, bool theAddODOnVertices=false)
Export the mesh to a med file.
void ExportSAUV (const char *file, const char *theMeshName=NULL, bool theAutoGroups=true)
Export the mesh to a SAUV file.
void ExportSTL (const char *file, const bool isascii, const SMESHDS_Mesh *meshPart=0)
Export the mesh to an STL file.
void ExportUNV (const char *file, const SMESHDS_Mesh *meshPart=0)
Export the mesh to an UNV file.
SMESH_Mesh * FindMesh (int meshId) const
Return a mesh by id.
const TAncestorMap & GetAncestorMap () const
const TopTools_ListOfShape & GetAncestors (const TopoDS_Shape &theSubShape) const
Return list of ancestors of theSubShape in the order that lower dimention shapes come first.
bool GetAutoColor ()
double GetComputeProgress () const
Return a ratio of "compute cost" of computed sub-meshes to the whole "compute cost".
SMDSAbs_ElementType GetElementType (const int id, const bool iselem)
SMESH_Gen * GetGen ()
SMESH_Group * GetGroup (const int theGroupID)
Return a group by ID.
std::list< int > GetGroupIds () const
Return IDs of all groups.
GroupIteratorPtr GetGroups () const
Return iterator on all existing groups.
std::list< SMESH_subMesh * > GetGroupSubMeshesContaining (const TopoDS_Shape &shape) const
Return submeshes of groups containing the given subshape.
int GetHypotheses (const SMESH_subMesh *aSubMesh, const SMESH_HypoFilter &aFilter, std::list< const SMESHDS_Hypothesis * > &aHypList, const bool andAncestors, std::list< TopoDS_Shape > *assignedTo=0) const
Return hypotheses assigned to the shape of a sub-mesh.
int GetHypotheses (const TopoDS_Shape &aSubShape, const SMESH_HypoFilter &aFilter, std::list< const SMESHDS_Hypothesis * > &aHypList, const bool andAncestors, std::list< TopoDS_Shape > *assignedTo=0) const
Return hypotheses assigned to the shape.
SMESH_Hypothesis * GetHypothesis (const int aHypID) const
Return a hypothesis by its ID.
const SMESH_Hypothesis * GetHypothesis (const SMESH_subMesh *aSubMesh, const SMESH_HypoFilter &aFilter, const bool andAncestors, TopoDS_Shape *assignedTo=0) const
Return the hypothesis assigned to the shape of a sub-mesh.
const SMESH_Hypothesis * GetHypothesis (const TopoDS_Shape &aSubShape, const SMESH_HypoFilter &aFilter, const bool andAncestors, TopoDS_Shape *assignedTo=0) const
Return the hypothesis assigned to the shape.
const std::list< const SMESHDS_Hypothesis * > & GetHypothesisList (const TopoDS_Shape &aSubShape) const
int GetId () const
bool GetIsModified () const
const std::list< SMESHDS_Command * > & GetLog ()
SMESHDS_Mesh * GetMeshDS ()
const SMESHDS_Mesh * GetMeshDS () const
const TListOfListOfInt & GetMeshOrder () const
return submesh order if any
double GetShapeDiagonalSize () const
Return diagonal size of bounding box of shape to mesh.
TopoDS_Shape GetShapeToMesh () const
Return geometry to be meshed. (It may be a PseudoShape()!)
SMESH_subMesh * GetSubMesh (const TopoDS_Shape &aSubShape)
SMESH_subMesh * GetSubMeshContaining (const int aShapeID) const
SMESH_subMesh * GetSubMeshContaining (const TopoDS_Shape &aSubShape) const
SMESH_ComputeErrorPtr GMFToMesh (const char *theFileName, bool theMakeRequiredGroups=true)
Fill its data by reading a GMF file.
bool HasDuplicatedGroupNamesMED ()
Check group names for duplications. Consider maximum group name length stored in MED file.
bool HasModificationsToDiscard () const
Return true if the mesh has been edited since a total re-compute and those modifications may prevent successful partial re-compute. As a side effect reset _isModified flag if mesh is empty.
bool HasShapeToMesh () const
Return true if there is a geometry to be meshed, not PseudoShape()
bool IsMainShape (const TopoDS_Shape &theShape) const
bool IsNotConformAllowed () const
check if a hypothesis alowing notconform mesh is present
bool IsOrderOK (const SMESH_subMesh *smBefore, const SMESH_subMesh *smAfter) const
Return true if given order of sub-meshes is OK.
bool IsUsedHypothesis (SMESHDS_Hypothesis *anHyp, const SMESH_subMesh *aSubMesh)
Return True if anHyp is used to mesh aSubShape.
void Load ()
Load mesh from study file.
int MEDToMesh (const char *theFileName, const char *theMeshName)
bool MeshExists (int meshId) const
Return true if a mesh with given id exists.
int Nb0DElements () const
Return number of edges of given order in the mesh.
int NbBalls () const
Return number of ball elements in the mesh.
int NbBiQuadQuadrangles () const
Return number of biquadratic quadrangles in the mesh.
int NbBiQuadTriangles () const
Return number of biquadratic triangles in the mesh.
int NbEdges (SMDSAbs_ElementOrder order=ORDER_ANY) const
Return number of edges of given order in the mesh.
int NbFaces (SMDSAbs_ElementOrder order=ORDER_ANY) const
Return number of faces of given order in the mesh.
int NbGroup () const
int NbHexagonalPrisms () const
Return number of hexagonal prisms in the mesh.
int NbHexas (SMDSAbs_ElementOrder order=ORDER_ANY) const
Return number of hexahedrons of given order in the mesh.
int NbMeshes () const
Returns number of meshes in the Study, that is supposed to be equal to SMESHDS_Document::NbMeshes()
int NbNodes () const
Return number of nodes in the mesh.
int NbPolygons (SMDSAbs_ElementOrder order=ORDER_ANY) const
Return the number of polygonal faces in the mesh.
int NbPolyhedrons () const
Return number of polyhedrons in the mesh.
int NbPrisms (SMDSAbs_ElementOrder order=ORDER_ANY) const
Return number of prisms (penthahedrons) of given order in the mesh.
int NbPyramids (SMDSAbs_ElementOrder order=ORDER_ANY) const
Return number of pyramids of given order in the mesh.
int NbQuadrangles (SMDSAbs_ElementOrder order=ORDER_ANY) const
Return the number nodes faces in the mesh.
int NbSubMesh () const
Return number of submeshes in the mesh.
int NbTetras (SMDSAbs_ElementOrder order=ORDER_ANY) const
Return number of tetrahedrons of given order in the mesh.
int NbTriangles (SMDSAbs_ElementOrder order=ORDER_ANY) const
Return the number of faces in the mesh.
int NbTriQuadraticHexas () const
Return number of triquadratic hexahedrons in the mesh.
int NbVolumes (SMDSAbs_ElementOrder order=ORDER_ANY) const
Return number of volumes of given order in the mesh.
void NotifySubMeshesHypothesisModification (const SMESH_Hypothesis *theChangedHyp)
Say all submeshes that theChangedHyp has been modified.
bool RemoveGroup (const int theGroupID)
SMESH_Hypothesis::Hypothesis_Status RemoveHypothesis (const TopoDS_Shape &aSubShape, int anHypId)
void SetAutoColor (bool theAutoColor)
void SetCallUp (TCallUp *upCaller)
Set a caller of methods at level of CORBA API implementation. The set upCaller will be deleted by SMESH_Mesh.
void SetIsModified (bool isModified)
Set the flag meaning that the mesh has been edited "manually". It is to set to false after Clear() and to set to true by MeshEditor.
void SetMeshOrder (const TListOfListOfInt &theOrder)
remove submesh order from Mesh
void ShapeToMesh (const TopoDS_Shape &aShape)
Set geometry to be meshed.
SMESH_Mesh (int theLocalId, int theStudyId, SMESH_Gen *theGen, bool theIsEmbeddedMode, SMESHDS_Document *theDocument)
bool SortByMeshOrder (std::vector< SMESH_subMesh * > &theListToSort) const
sort submeshes according to stored mesh order
int STLToMesh (const char *theFileName)
bool SynchronizeGroups ()
Creates SMESH_Groups for not wrapped SMESHDS_Groups.
int UNVToMesh (const char *theFileName)
virtual ~SMESH_Mesh ()
Static Public Member Functions
static double GetShapeDiagonalSize (const TopoDS_Shape &aShape)
Return diagonal size of bounding box of a shape.
static const TopoDS_Solid & PseudoShape ()
Return a solid which is returned by GetShapeToMesh() if a real geometry to be meshed was not set.
Protected Member Functions
SMESH_Mesh ()
Constructor of SMESH_Mesh being a base of some descendant class.
SMESH_Mesh (const SMESH_Mesh &)
Member Typedef Documentation
GroupIteratorPtr
typedef boost::shared_ptr< SMDS_Iterator<SMESH_Group*> > SMESH_Mesh::GroupIteratorPtr
TAncestorMap
typedef TopTools_IndexedDataMapOfShapeListOfShape SMESH_Mesh::TAncestorMap
Return data map of descendant to ancestor shapes.
Constructor & Destructor Documentation
SMESH_Mesh() [1/3]
SMESH_Mesh::SMESH_Mesh (int theLocalId, int theStudyId, SMESH_Gen * theGen, bool theIsEmbeddedMode, SMESHDS_Document * theDocument)
References SMESHDS_Document::NewMesh(), PseudoShape(), and SMESHDS_Mesh::ShapeToMesh().
~SMESH_Mesh()
SMESH_Mesh::~SMESH_Mesh () virtual
References draftgeoutils.faces::bind(), Clear(), GetSubMeshContaining(), studyContextStruct::mapMesh, and SMESH_subMesh::MESH_ENTITY_REMOVED.
SMESH_Mesh() [2/3]
SMESH_Mesh::SMESH_Mesh () protected
Constructor of SMESH_Mesh being a base of some descendant class.
SMESH_Mesh() [3/3]
SMESH_Mesh::SMESH_Mesh (const SMESH_Mesh &) protected
Member Function Documentation
AddGroup() [1/2]
SMESH_Group * SMESH_Mesh::AddGroup (const SMDSAbs_ElementType theType, const char * theName, int & theId, const TopoDS_Shape & theShape = TopoDS_Shape(), const SMESH_PredicatePtr & thePredicate = SMESH_PredicatePtr())
References SMESHDS_Mesh::AddGroup(), SMESH_Group::GetGroupDS(), and GetMeshDS().
Referenced by SMESH_MeshEditor::CreateFlatElementsOnFacesGroups(), SMESH_MeshEditor::CreateHoleSkin(), SMESH_MeshEditor::DoubleNodesOnGroupBoundaries(), StdMeshers_Import_1D::importMesh(), MEDToMesh(), and UNVToMesh().
AddGroup() [2/2]
SMESH_Group * SMESH_Mesh::AddGroup (SMESHDS_GroupBase * groupDS)
Creates a group based on an existing SMESHDS group. Group ID should be unique.
References SMESHDS_Mesh::AddGroup(), SMESH_Group::GetGroupDS(), SMESHDS_GroupBase::GetID(), and GetMeshDS().
AddHypothesis()
SMESH_Hypothesis::Hypothesis_Status SMESH_Mesh::AddHypothesis (const TopoDS_Shape & aSubShape, int anHypId, std::string * error = 0)
References SMESH_subMesh::ADD_ALGO, SMESH_subMesh::ADD_FATHER_ALGO, SMESH_subMesh::ADD_FATHER_HYP, SMESH_subMesh::ADD_HYP, SMESH_subMesh::AlgoStateEngine(), SMESH_subMesh::CheckConcurentHypothesis(), SMESH_subMesh::DumpAlgoState(), SMESH_subMesh::GetComputeError(), SMESH_subMesh::getDependsOnIterator(), SMESH_Hypothesis::GetDim(), GetHypothesis(), SMESH_subMesh::GetId(), SMESHDS_Hypothesis::GetName(), SMESH_Gen::GetShapeDim(), GetSubMesh(), SMESHDS_Hypothesis::GetType(), HasModificationsToDiscard(), SMESH_Hypothesis::HYP_BAD_SUBSHAPE, SMESH_Hypothesis::HYP_CONCURENT, SMESH_Hypothesis::HYP_INCOMPATIBLE, SMESH_subMesh::IsApplicableHypotesis(), IsMainShape(), SMESH_Hypothesis::IsStatusFatal(), SMESHDS_Hypothesis::PARAM_ALGO, SMESH_subMesh::REMOVE_ALGO, SMESH_subMesh::REMOVE_HYP, and SMESH_subMesh::SubMeshesAlgoStateEngine().
CGNSToMesh()
int SMESH_Mesh::CGNSToMesh (const char * theFileName, const int theMeshIndex, std::string & theMeshName)
Reads the given mesh from the CGNS file.
Parameters
theFileName - name of the file
Return values
int - Driver_Mesh::Status
References Driver_Mesh::DRS_FAIL, and SynchronizeGroups().
Clear()
void SMESH_Mesh::Clear ()
Remove all nodes and elements.
References SMESH_subMesh::CHECK_COMPUTE_STATE, SMESH_subMesh::CLEAN, GetShapeToMesh(), GetSubMeshContaining(), and HasShapeToMesh().
Referenced by ~SMESH_Mesh().
ClearLog()
void SMESH_Mesh::ClearLog ()
ClearMeshOrder()
void SMESH_Mesh::ClearMeshOrder ()
remove submesh order from Mesh
ClearSubMesh()
void SMESH_Mesh::ClearSubMesh (const int theShapeId)
Remove all nodes and elements of indicated shape.
References SMESH_subMesh::CHECK_COMPUTE_STATE, SMESH_subMesh::CLEAN, and GetSubMeshContaining().
ConvertToStandalone()
SMESH_Group * SMESH_Mesh::ConvertToStandalone (int theGroupID)
Convert group on geometry into standalone group.
References SMESHDS_Group::Add(), SMESHDS_Mesh::AddGroup(), SMESHDS_GroupBase::GetColor(), SMESHDS_GroupBase::GetElements(), SMESH_Group::GetGroupDS(), GetMeshDS(), SMESH_Group::GetName(), SMESHDS_GroupBase::GetType(), SMESHDS_Mesh::RemoveGroup(), and SMESHDS_GroupBase::SetColor().
DATToMesh()
int SMESH_Mesh::DATToMesh (const char * theFileName)
References DriverDAT_R_SMDS_Mesh::Perform(), Driver_Mesh::SetFile(), Driver_SMDS_Mesh::SetMesh(), and Driver_Mesh::SetMeshId().
Dump()
ostream & SMESH_Mesh::Dump (ostream & save)
References NbEdges(), NbFaces(), NbHexas(), NbNodes(), NbPolygons(), NbPolyhedrons(), NbPrisms(), NbPyramids(), NbQuadrangles(), NbTetras(), NbTriangles(), NbVolumes(), and OfflineRenderingUtils::save().
Referenced by Fem::FemMeshPy::representation().
ExportCGNS()
void SMESH_Mesh::ExportCGNS (const char * file, const SMESHDS_Mesh * mesh, const char * meshName = 0)
Export the mesh to the CGNS file.
References Driver_Mesh::DRS_FAIL, Driver_Mesh::DRS_OK, and SMESHDS_Mesh::GetPersistentId().
ExportDAT()
void SMESH_Mesh::ExportDAT (const char * file, const SMESHDS_Mesh * meshPart = 0)
Export the mesh to a DAT file.
References DriverDAT_W_SMDS_Mesh::Perform(), Driver_Mesh::SetFile(), Driver_SMDS_Mesh::SetMesh(), and Driver_Mesh::SetMeshId().
ExportGMF()
void SMESH_Mesh::ExportGMF (const char * file, const SMESHDS_Mesh * mesh, bool withRequiredGroups = true)
Export the mesh to a GMF file.
References DriverGMF_Write::Perform(), DriverGMF_Write::SetExportRequiredGroups(), Driver_Mesh::SetFile(), and Driver_SMESHDS_Mesh::SetMesh().
ExportMED()
void SMESH_Mesh::ExportMED (const char * file, const char * theMeshName = NULL, bool theAutoGroups = true, int theVersion = 0, const SMESHDS_Mesh * meshPart = 0, bool theAutoDimension = false, bool theAddODOnVertices = false)
Export the mesh to a med file.
Parameters
[in] file - name of the MED file
[in] theMeshName - name of this mesh
[in] theAutoGroups - boolean parameter for creating/not creating the groups Group_On_All_Nodes, Group_On_All_Faces, ... ; the typical use is auto_groups=false.
[in] theVersion - defines the version of format of MED file, that will be created
[in] meshPart - mesh data to export
[in] theAutoDimension - if true, a space dimension of a MED mesh can be either
1D if all mesh nodes lie on OX coordinate axis, or
2D if all mesh nodes lie on XOY coordinate plane, or
3D in the rest cases. If theAutoDimension is false, the space dimension is always 3.
Returns
int - mesh index in the file
References DriverMED_W_SMESHDS_Mesh::AddGroup(), DriverMED_W_SMESHDS_Mesh::AddGroupOfEdges(), DriverMED_W_SMESHDS_Mesh::AddGroupOfFaces(), DriverMED_W_SMESHDS_Mesh::AddGroupOfNodes(), DriverMED_W_SMESHDS_Mesh::AddGroupOfVolumes(), DriverMED_W_SMESHDS_Mesh::AddODOnVertices(), SMESH_Group::GetGroupDS(), SMESH_Group::GetName(), SMESHDS_GroupBase::GetType(), DriverMED_W_SMESHDS_Mesh::Perform(), DriverMED_W_SMESHDS_Mesh::SetAutoDimension(), DriverMED_W_SMESHDS_Mesh::SetFile(), Driver_SMESHDS_Mesh::SetMesh(), Driver_Mesh::SetMeshId(), Driver_Mesh::SetMeshName(), SMESHDS_GroupBase::SetStoreName(), and SMESH::throwSalomeEx().
Referenced by ExportSAUV().
ExportSAUV()
void SMESH_Mesh::ExportSAUV (const char * file, const char * theMeshName = NULL, bool theAutoGroups = true)
Export the mesh to a SAUV file.
References ExportMED().
ExportSTL()
void SMESH_Mesh::ExportSTL (const char * file, const bool isascii, const SMESHDS_Mesh * meshPart = 0)
Export the mesh to an STL file.
References DriverSTL_W_SMDS_Mesh::Perform(), Driver_Mesh::SetFile(), DriverSTL_W_SMDS_Mesh::SetIsAscii(), Driver_SMDS_Mesh::SetMesh(), and Driver_Mesh::SetMeshId().
ExportUNV()
void SMESH_Mesh::ExportUNV (const char * file, const SMESHDS_Mesh * meshPart = 0)
Export the mesh to an UNV file.
References DriverUNV_W_SMDS_Mesh::AddGroup(), SMESH_Group::GetGroupDS(), SMESH_Group::GetName(), DriverUNV_W_SMDS_Mesh::Perform(), Driver_Mesh::SetFile(), Driver_SMDS_Mesh::SetMesh(), Driver_Mesh::SetMeshId(), and SMESHDS_GroupBase::SetStoreName().
FindMesh()
SMESH_Mesh * SMESH_Mesh::FindMesh (int meshId) const
Return a mesh by id.
GetAncestorMap()
const TAncestorMap& SMESH_Mesh::GetAncestorMap () const
Referenced by StdMeshers_ProjectionUtils::FindSubShapeAssociation().
GetAncestors()
const TopTools_ListOfShape & SMESH_Mesh::GetAncestors (const TopoDS_Shape & theSubShape) const
Return list of ancestors of theSubShape in the order that lower dimention shapes come first.
Referenced by StdMeshers_Projection_1D::CheckHypothesis(), StdMeshers_Projection_2D::Compute(), StdMeshers_ProjectionUtils::FindSubShapeAssociation(), StdMeshers_ProjectionUtils::GetEdgeByVertices(), SMESH_MesherHelper::GetNodeUV(), and StdMeshers_ProjectionUtils::GetPropagationEdge().
GetAutoColor()
bool SMESH_Mesh::GetAutoColor ()
GetComputeProgress()
double SMESH_Mesh::GetComputeProgress () const
Return a ratio of "compute cost" of computed sub-meshes to the whole "compute cost".
References SMESH_subMesh::DependsOn(), SMESH_subMesh::FAILED_TO_COMPUTE, SMESH_subMesh::GetAlgo(), SMESH_subMesh::GetComputeCost(), SMESH_subMesh::GetComputeState(), GetId(), SMESH_subMesh::GetId(), GetSubMeshContaining(), and SMESH_subMesh::IsEmpty().
GetElementType()
SMDSAbs_ElementType SMESH_Mesh::GetElementType (const int id, const bool iselem)
Referenced by Fem::FemMeshPy::getElementType().
GetGen()
SMESH_Gen* SMESH_Mesh::GetGen ()
Referenced by StdMeshers_Regular_1D::CheckHypothesis(), StdMeshers_Hexa_3D::Compute(), StdMeshers_Hexa_3D::Evaluate(), TNodeDistributor::GetDistributor(), and StdMeshers_CompositeSegment_1D::GetFaceSide().
GetGroup()
SMESH_Group * SMESH_Mesh::GetGroup (const int theGroupID)
Return a group by ID.
Referenced by Fem::FemMeshPy::getGroupElements(), and Fem::FemMeshPy::getGroupElementType().
GetGroupIds()
list< int > SMESH_Mesh::GetGroupIds () const
Return IDs of all groups.
Referenced by Fem::FemMeshPy::getGroups().
GetGroups()
SMESH_Mesh::GroupIteratorPtr SMESH_Mesh::GetGroups () const
Return iterator on all existing groups.
Referenced by StdMeshers_QuadToTriaAdaptor::Compute(), SMESH_MeshEditor::CreateHoleSkin(), and StdMeshers_Import_1D::importMesh().
GetGroupSubMeshesContaining()
list< SMESH_subMesh * > SMESH_Mesh::GetGroupSubMeshesContaining (const TopoDS_Shape & shape) const
Return submeshes of groups containing the given subshape.
Return sub-meshes of groups containing the given sub-shape.
References GetSubMeshContaining(), SMESH_subMesh::GetSubMeshDS(), SMESH_subMesh::GetSubShape(), SMESHDS_SubMesh::IsComplexSubmesh(), and SMESH_MesherHelper::IsSubShape().
GetHypotheses() [1/2]
int SMESH_Mesh::GetHypotheses (const SMESH_subMesh * aSubMesh, const SMESH_HypoFilter & aFilter, std::list< const SMESHDS_Hypothesis * > & aHypList, const bool andAncestors, std::list< TopoDS_Shape > * assignedTo = 0) const
Return hypotheses assigned to the shape of a sub-mesh.
Parameters
aSubShape - the sub-mesh to check
aFilter - the hypothesis filter
aHypList - the list of the found hypotheses
andAncestors - flag to check hypos assigned to ancestors of the shape
Return values
int - number of unique hypos in aHypList
References SMESH_subMesh::GetAncestors(), SMESH_subMesh::GetSubShape(), SMESH_HypoFilter::IsOk(), and SortByMeshOrder().
GetHypotheses() [2/2]
int SMESH_Mesh::GetHypotheses (const TopoDS_Shape & aSubShape, const SMESH_HypoFilter & aFilter, std::list< const SMESHDS_Hypothesis * > & aHypList, const bool andAncestors, std::list< TopoDS_Shape > * assignedTo = 0) const
Return hypotheses assigned to the shape.
Parameters
aSubShape - the shape to check
aFilter - the hypothesis filter
aHypList - the list of the found hypotheses
andAncestors - flag to check hypos assigned to ancestors of the shape
Return values
int - number of unique hypos in aHypList
References GetSubMesh().
Referenced by StdMeshers_Regular_1D::CheckHypothesis(), VISCOUS_2D::findHyps(), SMESH_Algo::GetAppliedHypothesis(), SMESH_Algo::GetUsedHypothesis(), StdMeshers_Regular_1D::GetUsedHypothesis(), IsUsedHypothesis(), and NotifySubMeshesHypothesisModification().
GetHypothesis() [1/3]
SMESH_Hypothesis * SMESH_Mesh::GetHypothesis (const int aHypID) const
Return a hypothesis by its ID.
References studyContextStruct::mapHypothesis.
GetHypothesis() [2/3]
const SMESH_Hypothesis * SMESH_Mesh::GetHypothesis (const SMESH_subMesh * aSubMesh, const SMESH_HypoFilter & aFilter, const bool andAncestors, TopoDS_Shape * assignedTo = 0) const
Return the hypothesis assigned to the shape of a sub-mesh.
Parameters
aSubMesh - the sub-mesh to check
aFilter - the hypothesis filter
andAncestors - flag to check hypos assigned to ancestors of the shape
assignedTo - to return the shape the found hypo is assigned to
Return values
SMESH_Hypothesis* - the first hypo passed through aFilter
References SMESH_subMesh::GetAncestors(), SMESH_subMesh::GetSubShape(), SMESH_HypoFilter::IsOk(), and SortByMeshOrder().
GetHypothesis() [3/3]
const SMESH_Hypothesis * SMESH_Mesh::GetHypothesis (const TopoDS_Shape & aSubShape, const SMESH_HypoFilter & aFilter, const bool andAncestors, TopoDS_Shape * assignedTo = 0) const
Return the hypothesis assigned to the shape.
Parameters
aSubShape - the shape to check
aFilter - the hypothesis filter
andAncestors - flag to check hypos assigned to ancestors of the shape
assignedTo - to return the shape the found hypo is assigned to
Return values
SMESH_Hypothesis* - the first hypo passed through aFilter
References GetSubMesh().
Referenced by AddHypothesis(), SMESH_Gen::Compute(), SMESH_Gen::Evaluate(), SMESH_Gen::GetAlgo(), TNodeDistributor::GetDistributor(), StdMeshers_Quadrangle_2D::getEnforcedUV(), StdMeshers_Regular_1D::getVertexHyp(), SMESH_Gen::IsGlobalHypothesis(), IsNotConformAllowed(), and StdMeshers_ProjectionUtils::SourceNotComputedError().
GetHypothesisList()
const list< const SMESHDS_Hypothesis * > & SMESH_Mesh::GetHypothesisList (const TopoDS_Shape & aSubShape) const
GetId()
int SMESH_Mesh::GetId () const
Referenced by GetComputeProgress().
GetIsModified()
bool SMESH_Mesh::GetIsModified () const
GetLog()
const list< SMESHDS_Command * > & SMESH_Mesh::GetLog ()
GetMeshDS() [1/2]
SMESHDS_Mesh* SMESH_Mesh::GetMeshDS ()
Referenced by AddGroup(), NETGENPlugin_Mesher::AddIntVerticesInFaces(), NETGENPlugin_Mesher::AddIntVerticesInSolids(), StdMeshers_QuadToTriaAdaptor::CheckIntersection(), StdMeshers_Quadrangle_2D::checkNbEdgesForEvaluate(), SMESH_Gen::Compute(), NETGENPlugin_NETGEN_2D_ONLY::Compute(), NETGENPlugin_NETGEN_3D::Compute(), StdMeshers_Cartesian_3D::Compute(), StdMeshers_CompositeSegment_1D::Compute(), StdMeshers_Hexa_3D::Compute(), StdMeshers_Import_1D::Compute(), StdMeshers_Import_1D2D::Compute(), StdMeshers_Prism_3D::Compute(), StdMeshers_Projection_1D::Compute(), StdMeshers_Projection_1D2D::Compute(), StdMeshers_Projection_2D::Compute(), StdMeshers_Projection_3D::Compute(), StdMeshers_RadialPrism_3D::Compute(), StdMeshers_RadialQuadrangle_1D2D::Compute(), StdMeshers_Regular_1D::Compute(), StdMeshers_QuadToTriaAdaptor::Compute(), StdMeshers_QuadToTriaAdaptor::Compute2ndPart(), StdMeshers_Regular_1D::computeInternalParameters(), StdMeshers_Quadrangle_2D::computeQuadDominant(), StdMeshers_Quadrangle_2D::computeQuadPref(), StdMeshers_Quadrangle_2D::computeReduced(), ConvertToStandalone(), SMESH_MeshEditor::CreateFlatElementsOnFacesGroups(), SMESH_MeshEditor::CreateHoleSkin(), StdMeshers_Penta_3D::CreateNode(), SMESH_MeshEditor::DoubleNodesOnGroupBoundaries(), StdMeshers_Projection_1D::Evaluate(), Fem::FemVTKTools::exportFreeCADResult(), Fem::FemVTKTools::exportVTKMesh(), SMESH_MeshEditor::ExtrusionAlongTrack(), NETGENPlugin_Mesher::FillSMesh(), StdMeshers_ProjectionUtils::FindMatchingNodesOnFaces(), StdMeshers_Penta_3D::FindNodeOnShape(), StdMeshers_ProjectionUtils::FindSubShapeAssociation(), NETGENPlugin_Mesher::FixIntFaces(), SMESH_MeshVSLink::Get3DGeom(), SMESH_Gen::GetAlgoState(), Fem::FemMeshPy::getEdges(), Fem::FemMeshPy::getFaces(), StdMeshers_CompositeSegment_1D::GetFaceSide(), StdMeshers_FaceSide::GetFaceWires(), SMESH_MeshVSLink::GetGeom(), SMESH_MeshVSLink::GetGeomType(), SMESH_MeshEditor::GetHexaFacetsToSplit(), Fem::FemMeshPy::getIdByElementType(), Fem::FemMeshPy::getNodeById(), Fem::FemMeshPy::getNodes(), SMESH_MeshVSLink::GetNodesByElement(), SMESH_MeshVSLink::GetNormal(), VISCOUS_3D::_SolidData::GetShapeEdges(), StdMeshers_ImportSource1D::GetSourceSubMeshes(), Fem::FemMeshPy::getVolumes(), StdMeshers_Import_1D::importMesh(), Fem::FemVTKTools::importVTKMesh(), SMESH_Gen::IsGlobalHypothesis(), SMESH_MesherHelper::IsStructured(), SMESH_MesherHelper::IsSubShape(), SMESH_Pattern::Load(), StdMeshers_Penta_3D::MakeBlock(), SMESH_Pattern::MakeMesh(), StdMeshers_Penta_3D::MakeMeshOnFxy1(), StdMeshers_Penta_3D::MakeNodes(), StdMeshers_Penta_3D::MakeVolumeMesh(), NotifySubMeshesHypothesisModification(), RemoveGroup(), StdMeshers_ViscousLayers2D::RestoreListeners(), StdMeshers_Adaptive1D::SetParametersByMesh(), StdMeshers_Geometric1D::SetParametersByMesh(), SMESH_MeshVSLink::SMESH_MeshVSLink(), and SMESH_MeshEditor::Transform().
GetMeshDS() [2/2]
const SMESHDS_Mesh* SMESH_Mesh::GetMeshDS () const
GetMeshOrder()
const TListOfListOfInt & SMESH_Mesh::GetMeshOrder () const
return submesh order if any
GetShapeDiagonalSize() [1/2]
double SMESH_Mesh::GetShapeDiagonalSize () const
Return diagonal size of bounding box of shape to mesh.
References GetShapeToMesh().
Referenced by StdMeshers_Regular_1D::CheckHypothesis(), and StdMeshers_NumberOfLayers::SetParametersByDefaults().
GetShapeDiagonalSize() [2/2]
double SMESH_Mesh::GetShapeDiagonalSize (const TopoDS_Shape & aShape) static
Return diagonal size of bounding box of a shape.
References GEOMUtils::PreciseBoundingBox().
GetShapeToMesh()
TopoDS_Shape SMESH_Mesh::GetShapeToMesh () const
Return geometry to be meshed. (It may be a PseudoShape()!)
Referenced by Fem::FemMeshPy::addHypothesis(), Clear(), SMESH_Gen::Compute(), StdMeshers_QuadToTriaAdaptor::Compute(), NETGENPlugin_NETGEN_2D_ONLY::Compute(), NETGENPlugin_NETGEN_3D::Compute(), StdMeshers_Regular_1D::Compute(), SMESH_MeshEditor::ConvertFromQuadratic(), SMESH_MeshEditor::ConvertToQuadratic(), SMESH_MeshEditor::ExtrusionAlongTrack(), SMESH_MesherHelper::FixQuadraticElements(), SMESH_Gen::GetAlgo(), GetShapeDiagonalSize(), StdMeshers_ImportSource1D::GetSourceSubMeshes(), and NETGENPlugin_Hypothesis::SetParametersByDefaults().
GetSubMesh()
SMESH_subMesh * SMESH_Mesh::GetSubMesh (const TopoDS_Shape & aSubShape)
Get or Create the SMESH_subMesh object implementation
References SMESH_subMesh::getDependsOnIterator().
Referenced by AddHypothesis(), NETGENPlugin_Mesher::AddIntVerticesInFaces(), NETGENPlugin_Mesher::AddIntVerticesInSolids(), StdMeshers_Quadrangle_2D::check(), StdMeshers_Import_1D::CheckHypothesis(), StdMeshers_Quadrangle_2D::checkNbEdgesForEvaluate(), SMESH_Gen::Compute(), NETGENPlugin_NETGEN_2D_ONLY::Compute(), StdMeshers_CompositeSegment_1D::Compute(), StdMeshers_Import_1D2D::Compute(), StdMeshers_Prism_3D::Compute(), StdMeshers_Projection_1D::Compute(), StdMeshers_Projection_1D2D::Compute(), StdMeshers_Projection_2D::Compute(), StdMeshers_Projection_3D::Compute(), StdMeshers_Quadrangle_2D::Compute(), StdMeshers_RadialQuadrangle_1D2D::Compute(), StdMeshers_ViscousLayers2D::Compute(), StdMeshers_ViscousLayers::Compute(), StdMeshers_Quadrangle_2D::computeQuadDominant(), SMESH_Gen::Evaluate(), NETGENPlugin_NETGEN_2D_ONLY::Evaluate(), NETGENPlugin_NETGEN_3D::Evaluate(), StdMeshers_CompositeHexa_3D::Evaluate(), StdMeshers_Hexa_3D::Evaluate(), StdMeshers_HexaFromSkin_3D::Evaluate(), StdMeshers_Import_1D::Evaluate(), StdMeshers_Import_1D2D::Evaluate(), StdMeshers_MEFISTO_2D::Evaluate(), StdMeshers_Penta_3D::Evaluate(), StdMeshers_PolygonPerFace_2D::Evaluate(), StdMeshers_Prism_3D::Evaluate(), StdMeshers_Projection_1D::Evaluate(), StdMeshers_Projection_1D2D::Evaluate(), StdMeshers_Projection_2D::Evaluate(), StdMeshers_Projection_3D::Evaluate(), StdMeshers_Quadrangle_2D::Evaluate(), StdMeshers_RadialPrism_3D::Evaluate(), StdMeshers_RadialQuadrangle_1D2D::Evaluate(), StdMeshers_Regular_1D::Evaluate(), StdMeshers_Quadrangle_2D::evaluateQuadPref(), SMESH_MeshEditor::ExtrusionAlongTrack(), NETGENPlugin_Mesher::FillNgMesh(), SMESH_MesherHelper::FixQuadraticElements(), SMESH_Gen::GetAlgo(), SMESH_Gen::GetAlgoState(), StdMeshers_Quadrangle_2D::getEnforcedUV(), GetHypotheses(), GetHypothesis(), StdMeshers_ImportSource1D::GetSourceSubMeshes(), StdMeshers_ProjectionUtils::MakeComputed(), StdMeshers_Penta_3D::MakeMeshOnFxy1(), SMESH_Algo::NumberOfPoints(), RemoveHypothesis(), StdMeshers_ViscousLayers2D::RestoreListeners(), StdMeshers_CompositeSegment_1D::SetEventListener(), StdMeshers_ProjectionUtils::SetEventListener(), and VISCOUS_3D::ToClearSubWithMain().
GetSubMeshContaining() [1/2]
SMESH_subMesh * SMESH_Mesh::GetSubMeshContaining (const int aShapeID) const
Get the SMESH_subMesh object implementation. Dont create it, return null if it does not exist.
GetSubMeshContaining() [2/2]
SMESH_subMesh * SMESH_Mesh::GetSubMeshContaining (const TopoDS_Shape & aSubShape) const
Get the SMESH_subMesh object implementation. Dont create it, return null if it does not exist.
Referenced by Clear(), StdMeshers_Penta_3D::ClearMeshOnFxy1(), ClearSubMesh(), StdMeshers_Regular_1D::computeInternalParameters(), SMESH_MeshEditor::ConvertFromQuadratic(), SMESH_MeshEditor::ConvertToQuadratic(), StdMeshers_Hexa_3D::Evaluate(), StdMeshers_Penta_3D::FindNodeOnShape(), SMESH_MesherHelper::FixQuadraticElements(), GetComputeProgress(), GetGroupSubMeshesContaining(), StdMeshers_Propagation::GetPropagationSource(), StdMeshers_ImportSource1D::GetSourceSubMeshes(), StdMeshers_Import_1D::getSubMeshOfCopiedMesh(), StdMeshers_Penta_3D::MakeBlock(), StdMeshers_Penta_3D::MakeMeshOnFxy1(), StdMeshers_Penta_3D::MakeNodes(), StdMeshers_Penta_3D::MakeVolumeMesh(), SMESH_MeshEditor::MergeNodes(), NETGENPlugin_SimpleHypothesis_2D::SetParametersByMesh(), NETGENPlugin_SimpleHypothesis_3D::SetParametersByMesh(), SortByMeshOrder(), and ~SMESH_Mesh().
GMFToMesh()
SMESH_ComputeErrorPtr SMESH_Mesh::GMFToMesh (const char * theFileName, bool theMakeRequiredGroups = true)
Fill its data by reading a GMF file.
References Driver_Mesh::GetError(), DriverGMF_Read::Perform(), Driver_Mesh::SetFile(), DriverGMF_Read::SetMakeRequiredGroups(), Driver_SMESHDS_Mesh::SetMesh(), and SynchronizeGroups().
HasDuplicatedGroupNamesMED()
bool SMESH_Mesh::HasDuplicatedGroupNamesMED ()
Check group names for duplications. Consider maximum group name length stored in MED file.
Check if any groups of the same type have equal names.
References SMESH_Group::GetGroupDS(), SMESH_Group::GetName(), and SMESHDS_GroupBase::GetType().
HasModificationsToDiscard()
bool SMESH_Mesh::HasModificationsToDiscard () const
Return true if the mesh has been edited since a total re-compute and those modifications may prevent successful partial re-compute. As a side effect reset _isModified flag if mesh is empty.
References SMESH_subMesh::GetSubShape(), SMESH_subMesh::IsMeshComputed(), and NbNodes().
Referenced by AddHypothesis(), NotifySubMeshesHypothesisModification(), RemoveHypothesis(), and SetIsModified().
HasShapeToMesh()
bool SMESH_Mesh::HasShapeToMesh () const
Return true if there is a geometry to be meshed, not PseudoShape()
Referenced by Clear(), SMESH_Gen::Compute(), NETGENPlugin_NETGEN_3D::compute(), SMESH_MeshEditor::ConvertFromQuadratic(), SMESH_MeshEditor::ConvertToQuadratic(), SMESH_Gen::Evaluate(), SMESH_MeshEditor::ExtrusionAlongTrack(), SMESH_MesherHelper::FixQuadraticElements(), SMESH_Gen::GetAlgoState(), StdMeshers_ImportSource1D::GetSourceSubMeshes(), SMESH_MesherHelper::IsQuadraticSubMesh(), SMESH_Pattern::MakeMesh(), StdMeshers_ViscousLayers2D::RestoreListeners(), NETGENPlugin_Hypothesis::SetParametersByDefaults(), and SMESH_MesherHelper::SMESH_MesherHelper().
IsMainShape()
bool SMESH_Mesh::IsMainShape (const TopoDS_Shape & theShape) const
Referenced by AddHypothesis(), StdMeshers_Projection_2D::Compute(), SMESH_Pattern::Load(), and RemoveHypothesis().
IsNotConformAllowed()
bool SMESH_Mesh::IsNotConformAllowed () const
check if a hypothesis alowing notconform mesh is present
References GetHypothesis(), and SMESH_HypoFilter::HasName().
Referenced by SMESH_Gen::GetAlgoState().
IsOrderOK()
bool SMESH_Mesh::IsOrderOK (const SMESH_subMesh * smBefore, const SMESH_subMesh * smAfter) const
Return true if given order of sub-meshes is OK.
References DraftVecUtils::find(), and SMESH_subMesh::GetId().
Referenced by SMESH_Gen::GetAlgo().
IsUsedHypothesis()
bool SMESH_Mesh::IsUsedHypothesis (SMESHDS_Hypothesis * anHyp, const SMESH_subMesh * aSubMesh)
Return True if anHyp is used to mesh aSubShape.
References DraftVecUtils::find(), SMESH_subMesh::GetAlgo(), SMESH_Algo::GetCompatibleHypoFilter(), GetHypotheses(), SMESHDS_Hypothesis::GetType(), SMESH_subMesh::IsApplicableHypotesis(), SMESH_Hypothesis::IsAuxiliary(), and SMESHDS_Hypothesis::PARAM_ALGO.
Referenced by NotifySubMeshesHypothesisModification().
Load()
void SMESH_Mesh::Load ()
Load mesh from study file.
MEDToMesh()
int SMESH_Mesh::MEDToMesh (const char * theFileName, const char * theMeshName)
References AddGroup(), DriverMED_R_SMESHDS_Mesh::GetGroup(), SMESH_Group::GetGroupDS(), DriverMED_R_SMESHDS_Mesh::GetGroupNamesAndTypes(), DriverMED_R_SMESHDS_Mesh::Perform(), Driver_Mesh::SetFile(), Driver_SMESHDS_Mesh::SetMesh(), Driver_Mesh::SetMeshId(), DriverMED_R_SMESHDS_Mesh::SetMeshName(), and SMESHDS_GroupBase::SetStoreName().
MeshExists()
bool SMESH_Mesh::MeshExists (int meshId) const
Return true if a mesh with given id exists.
Nb0DElements()
int SMESH_Mesh::Nb0DElements () const
Return number of edges of given order in the mesh.
NbBalls()
int SMESH_Mesh::NbBalls () const
Return number of ball elements in the mesh.
NbBiQuadQuadrangles()
int SMESH_Mesh::NbBiQuadQuadrangles () const
Return number of biquadratic quadrangles in the mesh.
Referenced by SMESH_MesherHelper::FixQuadraticElements().
NbBiQuadTriangles()
int SMESH_Mesh::NbBiQuadTriangles () const
Return number of biquadratic triangles in the mesh.
Referenced by SMESH_MesherHelper::FixQuadraticElements().
NbEdges()
int SMESH_Mesh::NbEdges (SMDSAbs_ElementOrder order = ORDER_ANY) const
Return number of edges of given order in the mesh.
Referenced by Dump(), SMESH_MeshEditor::ExtrusionAlongTrack(), SMESH_MeshEditor::ExtrusionSweep(), SMESH_MeshEditor::FindCoincidentNodes(), SMESH_MesherHelper::IsQuadraticMesh(), and SMESH_MeshEditor::RotationSweep().
NbFaces()
int SMESH_Mesh::NbFaces (SMDSAbs_ElementOrder order = ORDER_ANY) const
Return number of faces of given order in the mesh.
Referenced by FemGui::ViewProviderFEMMeshBuilder::createMesh(), Dump(), StdMeshers_HexaFromSkin_3D::Evaluate(), SMESH_MeshEditor::ExtrusionSweep(), SMESH_MeshEditor::FindCoincidentNodes(), SMESH_MesherHelper::IsQuadraticMesh(), SMESH_MesherHelper::IsQuadraticSubMesh(), and SMESH_MeshEditor::RotationSweep().
NbGroup()
int SMESH_Mesh::NbGroup () const
NbHexagonalPrisms()
int SMESH_Mesh::NbHexagonalPrisms () const
Return number of hexagonal prisms in the mesh.
NbHexas()
int SMESH_Mesh::NbHexas (SMDSAbs_ElementOrder order = ORDER_ANY) const
Return number of hexahedrons of given order in the mesh.
Referenced by Dump(), and SMESH_MeshEditor::GetHexaFacetsToSplit().
NbMeshes()
int SMESH_Mesh::NbMeshes () const
Returns number of meshes in the Study, that is supposed to be equal to SMESHDS_Document::NbMeshes()
NbNodes()
int SMESH_Mesh::NbNodes () const
Return number of nodes in the mesh.
Referenced by Dump(), and HasModificationsToDiscard().
NbPolygons()
int SMESH_Mesh::NbPolygons (SMDSAbs_ElementOrder order = ORDER_ANY) const
Return the number of polygonal faces in the mesh.
Referenced by Dump().
NbPolyhedrons()
int SMESH_Mesh::NbPolyhedrons () const
Return number of polyhedrons in the mesh.
Referenced by Dump().
NbPrisms()
int SMESH_Mesh::NbPrisms (SMDSAbs_ElementOrder order = ORDER_ANY) const
Return number of prisms (penthahedrons) of given order in the mesh.
Referenced by Dump().
NbPyramids()
int SMESH_Mesh::NbPyramids (SMDSAbs_ElementOrder order = ORDER_ANY) const
Return number of pyramids of given order in the mesh.
Referenced by Dump().
NbQuadrangles()
int SMESH_Mesh::NbQuadrangles (SMDSAbs_ElementOrder order = ORDER_ANY) const
Return the number nodes faces in the mesh.
Referenced by StdMeshers_QuadToTriaAdaptor::Compute(), NETGENPlugin_NETGEN_3D::Compute(), StdMeshers_Prism_3D::Compute(), and Dump().
NbSubMesh()
int SMESH_Mesh::NbSubMesh () const
Return number of submeshes in the mesh.
NbTetras()
int SMESH_Mesh::NbTetras (SMDSAbs_ElementOrder order = ORDER_ANY) const
Return number of tetrahedrons of given order in the mesh.
Referenced by Dump().
NbTriangles()
int SMESH_Mesh::NbTriangles (SMDSAbs_ElementOrder order = ORDER_ANY) const
Return the number of faces in the mesh.
Referenced by StdMeshers_Hexa_3D::Compute(), and Dump().
NbTriQuadraticHexas()
int SMESH_Mesh::NbTriQuadraticHexas () const
Return number of triquadratic hexahedrons in the mesh.
Referenced by SMESH_MesherHelper::FixQuadraticElements().
NbVolumes()
int SMESH_Mesh::NbVolumes (SMDSAbs_ElementOrder order = ORDER_ANY) const
Return number of volumes of given order in the mesh.
Referenced by Dump(), SMESH_MeshEditor::ExtrusionSweep(), SMESH_MeshEditor::FindCoincidentNodes(), SMESH_Pattern::Load(), and SMESH_MeshEditor::RotationSweep().
NotifySubMeshesHypothesisModification()
void SMESH_Mesh::NotifySubMeshesHypothesisModification (const SMESH_Hypothesis * theChangedHyp)
Say all submeshes that theChangedHyp has been modified.
References SMESH_subMesh::COMPUTE_OK, SMESH_Hypothesis::DataDependOnParams(), SMESH_subMesh::FAILED_TO_COMPUTE, DraftVecUtils::find(), SMESH_subMesh::GetAlgo(), SMESH_subMesh::GetAlgoState(), SMESH_Algo::GetCompatibleHypoFilter(), SMESH_subMesh::GetComputeState(), GetHypotheses(), GetMeshDS(), SMESH_subMesh::GetSubShape(), HasModificationsToDiscard(), SMESH_subMesh::IsApplicableHypotesis(), SMESH_Hypothesis::IsAuxiliary(), SMESH_HypoFilter::IsOk(), IsUsedHypothesis(), SMESH_subMesh::MISSING_HYP, SMESH_subMesh::MODIF_HYP, and SMDS_Mesh::Modified().
PseudoShape()
const TopoDS_Solid & SMESH_Mesh::PseudoShape () static
Return a solid which is returned by GetShapeToMesh() if a real geometry to be meshed was not set.
Referenced by ShapeToMesh(), and SMESH_Mesh().
RemoveGroup()
bool SMESH_Mesh::RemoveGroup (const int theGroupID)
References GetMeshDS(), and SMESHDS_Mesh::RemoveGroup().
Referenced by SMESH_MeshEditor::DoubleNodesOnGroupBoundaries().
RemoveHypothesis()
SMESH_Hypothesis::Hypothesis_Status SMESH_Mesh::RemoveHypothesis (const TopoDS_Shape & aSubShape, int anHypId)
References SMESH_subMesh::AlgoStateEngine(), SMESH_subMesh::CheckConcurentHypothesis(), SMESH_subMesh::DumpAlgoState(), SMESH_subMesh::getDependsOnIterator(), SMESH_Hypothesis::GetDim(), SMESH_Gen::GetShapeDim(), GetSubMesh(), SMESHDS_Hypothesis::GetType(), HasModificationsToDiscard(), SMESH_Hypothesis::HYP_CONCURENT, SMESH_Hypothesis::HYP_OK, SMESH_subMesh::IsApplicableHypotesis(), IsMainShape(), SMESH_Hypothesis::IsStatusFatal(), studyContextStruct::mapHypothesis, SMESHDS_Hypothesis::PARAM_ALGO, SMESH_subMesh::REMOVE_ALGO, SMESH_subMesh::REMOVE_FATHER_ALGO, SMESH_subMesh::REMOVE_FATHER_HYP, SMESH_subMesh::REMOVE_HYP, and SMESH_subMesh::SubMeshesAlgoStateEngine().
SetAutoColor()
void SMESH_Mesh::SetAutoColor (bool theAutoColor)
Auto color functionality
SetCallUp()
void SMESH_Mesh::SetCallUp (TCallUp * upCaller)
Set a caller of methods at level of CORBA API implementation. The set upCaller will be deleted by SMESH_Mesh.
SetIsModified()
void SMESH_Mesh::SetIsModified (bool isModified)
Set the flag meaning that the mesh has been edited "manually". It is to set to false after Clear() and to set to true by MeshEditor.
References HasModificationsToDiscard().
SetMeshOrder()
void SMESH_Mesh::SetMeshOrder (const TListOfListOfInt & theOrder)
remove submesh order from Mesh
ShapeToMesh()
void SMESH_Mesh::ShapeToMesh (const TopoDS_Shape & aShape)
Set geometry to be meshed.
References PseudoShape().
Referenced by Fem::FemMeshShapeNetgenObject::execute(), Fem::FemMeshShapeObject::execute(), and Fem::FemMeshPy::setShape().
SortByMeshOrder()
bool SMESH_Mesh::SortByMeshOrder (std::vector< SMESH_subMesh * > & theListToSort) const
sort submeshes according to stored mesh order
Parameters
theListToSort in out list to be sorted
Returns
FALSE if nothing sorted
References DraftVecUtils::find(), SMESHDS_SubMesh::GetID(), and GetSubMeshContaining().
Referenced by SMESH_Gen::Compute(), SMESH_Gen::Evaluate(), GetHypotheses(), and GetHypothesis().
STLToMesh()
int SMESH_Mesh::STLToMesh (const char * theFileName)
References DriverSTL_R_SMDS_Mesh::Perform(), Driver_Mesh::SetFile(), Driver_SMDS_Mesh::SetMesh(), and Driver_Mesh::SetMeshId().
SynchronizeGroups()
bool SMESH_Mesh::SynchronizeGroups ()
Creates SMESH_Groups for not wrapped SMESHDS_Groups.
Return values
bool - true if new SMESH_Groups have been created
References SMESHDS_GroupBase::GetID().
Referenced by CGNSToMesh(), and GMFToMesh().
UNVToMesh()
int SMESH_Mesh::UNVToMesh (const char * theFileName)
consult DriverMED_R_SMESHDS_Mesh::ReadStatus for returned value
References SMDS_MeshGroup::Add(), AddGroup(), DriverUNV_R_SMDS_Mesh::GetGroup(), SMESH_Group::GetGroupDS(), DriverUNV_R_SMDS_Mesh::GetGroupNamesMap(), SMDS_MeshGroup::GetType(), SMDS_MeshElement::GetType(), SMDS_MeshGroup::InitIterator(), SMDS_MeshGroup::InitSubGroupsIterator(), SMDS_MeshGroup::More(), SMDS_MeshGroup::MoreSubGroups(), SMDS_MeshGroup::Next(), SMDS_MeshGroup::NextSubGroup(), DriverUNV_R_SMDS_Mesh::Perform(), Driver_Mesh::SetFile(), Driver_SMDS_Mesh::SetMesh(), Driver_Mesh::SetMeshId(), SMESHDS_GroupBase::SetStoreName(), SMESHDS_Group::SetType(), and SMESHDS_Group::SMDSGroup().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_Mesh.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/SMESH_Mesh.cpp