FreeCAD: shipAreasCurve.PlotAux.Plot Class Reference
shipAreasCurve.PlotAux.Plot Class Reference
Public Member Functions
def plot (self, x, y, disp, xcb, ship)
def spreadSheet (self, x, y, ship)
Member Function Documentation
plot()
def shipAreasCurve.PlotAux.Plot.plot (self, x, y, disp, xcb, ship)
 Perform the areas curve plot.
@param x X coordinates.
@param y Transversal areas.
@param disp Ship displacement.
@param xcb Buoyancy center length.
@param ship Active ship instance.
@return True if error happens.
References Plot.axes(), Plot.figure(), Plot.grid(), Plot.plot(), Plot.xlabel(), and Plot.ylabel().
Referenced by Mod.PartDesign.WizardShaft.ShaftDiagram.Diagram.update().
spreadSheet()
def shipAreasCurve.PlotAux.Plot.spreadSheet (self, x, y, ship)
 Write the output data file.
@param x X coordinates.
@param y Transversal areas.
@param ship Active ship instance.
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Ship/shipAreasCurve/PlotAux.py