FreeCAD: Gui::PrefDoubleSpinBox Class Reference
Gui::PrefDoubleSpinBox Class Reference
The PrefDoubleSpinBox class.
#include <PrefWidgets.h>
Public Member Functions
PrefDoubleSpinBox (QWidget *parent=nullptr)
virtual ~PrefDoubleSpinBox ()
Public Member Functions inherited from Gui::PrefWidget
QByteArray entryName () const
Returns the widget's preference name.
virtual void OnChange (Base::Subject< const char * > &rCaller, const char *sReason)
This method is called if one or more values in the parameter settings are changed where getParamGrp() points to.
void onRestore ()
Restores the preferences of the widget.
void onSave ()
Saves the current preferences of the widget.
QByteArray paramGrpPath () const
Returns the widget's preferences path.
void setEntryName (const QByteArray &name)
Sets the preference name to name.
void setParamGrpPath (const QByteArray &path)
Sets the preference path to path.
void setPrefEntry (const QByteArray &name)
Does the same as setEntryName().
void setPrefPath (const QByteArray &name)
Does the same as setParamGrpPath().
Public Member Functions inherited from Gui::WindowParameter
ParameterGrp::handle getWindowParameter (void)
return the parameter group of this window
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason)
bool setGroupName (const char *name)
Sets the group of the window to name.
WindowParameter (const char *name)
virtual ~WindowParameter ()
Protected Member Functions
void restorePreferences ()
Restores the preferences Must be reimplemented in any subclasses.
void savePreferences ()
Save the preferences Must be reimplemented in any subclasses.
Protected Member Functions inherited from Gui::PrefWidget
void failedToRestore (const QString &) const
Print warning that restoring failed.
void failedToSave (const QString &) const
Print warning that saving failed.
PrefWidget ()
Constructs a preference widget.
virtual void restorePreferences ()=0
Restores the preferences Must be reimplemented in any subclasses.
virtual void savePreferences ()=0
Save the preferences Must be reimplemented in any subclasses.
virtual ~PrefWidget ()
Destroys the widget and detaches it from its parameter group.
Properties
QByteArray prefEntry
QByteArray prefPath
Additional Inherited Members
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter (void)
get the parameters
Detailed Description
The PrefDoubleSpinBox class.
Author
Werner Mayer
Constructor & Destructor Documentation
PrefDoubleSpinBox()
PrefDoubleSpinBox::PrefDoubleSpinBox (QWidget * parent = nullptr)
~PrefDoubleSpinBox()
PrefDoubleSpinBox::~PrefDoubleSpinBox () virtual
Member Function Documentation
restorePreferences()
void PrefDoubleSpinBox::restorePreferences () protected virtual
Restores the preferences Must be reimplemented in any subclasses.
Implements Gui::PrefWidget.
References Gui::PrefWidget::entryName(), Gui::PrefWidget::failedToRestore(), ParameterGrp::GetFloat(), Gui::WindowParameter::getWindowParameter(), and draftgeoutils.general::isNull().
savePreferences()
void PrefDoubleSpinBox::savePreferences () protected virtual
Save the preferences Must be reimplemented in any subclasses.
Implements Gui::PrefWidget.
References Gui::PrefWidget::entryName(), Gui::PrefWidget::failedToSave(), Gui::WindowParameter::getWindowParameter(), draftgeoutils.general::isNull(), and ParameterGrp::SetFloat().
Property Documentation
prefEntry
QByteArray Gui::PrefDoubleSpinBox::prefEntry read write
prefPath
QByteArray Gui::PrefDoubleSpinBox::prefPath read write
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/PrefWidgets.h
FreeCAD/src/Gui/PrefWidgets.cpp