FreeCAD: DrawSketchHandlerEllipse Class Reference
DrawSketchHandlerEllipse Class Reference
This class handles user interaction to draw and save the ellipse.
Public Types
enum ConstructionMethod { CENTER_PERIAPSIS_B , PERIAPSIS_APOAPSIS_B }
Construction methods, describes the method used to construct the ellipse.
enum SelectMode {
STATUS_SEEK_PERIAPSIS , STATUS_SEEK_APOAPSIS , STATUS_SEEK_CENTROID , STATUS_SEEK_A ,
STATUS_SEEK_B , STATUS_Close
}
Mode table, describes what step of the process we are in.
Public Member Functions
virtual void activated (ViewProviderSketch *)
Slot called when the create ellipse command is activated.
DrawSketchHandlerEllipse (int constructionMethod)
virtual void mouseMove (Base::Vector2d onSketchPos)
Updates the ellipse when the cursor moves.
virtual bool pressButton (Base::Vector2d onSketchPos)
Changes drawing mode on user-click.
virtual bool releaseButton (Base::Vector2d onSketchPos)
Calls saveEllipse() after last user input.
virtual ~DrawSketchHandlerEllipse ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::none, bool createowncommand=true)
virtual void deactivated (ViewProviderSketch *)
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual void quit (void)
virtual void registerPressedKey (bool, int)
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Attributes
std::vector< AutoConstraint > sugConstr1
std::vector< AutoConstraint > sugConstr2
std::vector< AutoConstraint > sugConstr3
Protected Attributes inherited from SketcherGui::DrawSketchHandler
QCursor actCursor
QPixmap actCursorPixmap
QCursor oldCursor
ViewProviderSketch * sketchgui
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
void addCursorTail (std::vector< QPixmap > &pixmaps)
void applyCursor (QCursor &newCursor)
void applyCursor (void)
qreal devicePixelRatio ()
unsigned long getCrosshairColor ()
void setCrosshairColor ()
void setCrosshairCursor (const char *svgName)
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
Sets a cursor for 3D inventor view.
void setSvgCursor (const QString &svgName, int x, int y, const std::map< unsigned long, unsigned long > &colorMapping=std::map< unsigned long, unsigned long >())
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
void unsetCursor (void)
Detailed Description
This class handles user interaction to draw and save the ellipse.
Two construction methods are implemented: -Periapsis, apoapsis, and b; and -Center, periapsis, and b.
The first method limits the ellipse to a circle, while the second method allows for swapping of the semi-major and semi-minor axes.
We use three reference frames in this class. The first (and primary), is the cartesian frame of the sketcher; all our work begins and ends in this frame. The second is the perifocal frame of the ellipse using polar coordinates. We use this frame for naming conventions and working with the ellipse. The last is a rotated right-handed cartesian frame centered at the ellipse center with the +X direction towards periapsis, +Z out of screen.
When working with an ellipse in the perifocal frame, the following equations are useful:
Member Enumeration Documentation
ConstructionMethod
enum DrawSketchHandlerEllipse::ConstructionMethod
Construction methods, describes the method used to construct the ellipse.
Enumerator
CENTER_PERIAPSIS_B
enum value, click on center, then periapsis, then b point.
PERIAPSIS_APOAPSIS_B
enum value, click on periapsis, then apoapsis, then b point.
SelectMode
enum DrawSketchHandlerEllipse::SelectMode
Mode table, describes what step of the process we are in.
Enumerator
STATUS_SEEK_PERIAPSIS
enum value, looking for click to set periapsis.
STATUS_SEEK_APOAPSIS
enum value, looking for click to set apoapsis.
STATUS_SEEK_CENTROID
enum value, looking for click to set centroid.
STATUS_SEEK_A
enum value, looking for click to set a.
STATUS_SEEK_B
enum value, looking for click to set b.
STATUS_Close
enum value, finalizing and saving ellipse.
Constructor & Destructor Documentation
DrawSketchHandlerEllipse()
DrawSketchHandlerEllipse::DrawSketchHandlerEllipse (int constructionMethod)
~DrawSketchHandlerEllipse()
virtual DrawSketchHandlerEllipse::~DrawSketchHandlerEllipse () virtual
Member Function Documentation
activated()
virtual void DrawSketchHandlerEllipse::activated (ViewProviderSketch *) virtual
Slot called when the create ellipse command is activated.
Parameters
sketchgui A pointer to the active sketch
Reimplemented from SketcherGui::DrawSketchHandler.
References CENTER_PERIAPSIS_B, PERIAPSIS_APOAPSIS_B, SketcherGui::DrawSketchHandler::setCrosshairCursor(), STATUS_SEEK_CENTROID, and STATUS_SEEK_PERIAPSIS.
mouseMove()
virtual void DrawSketchHandlerEllipse::mouseMove (Base::Vector2d onSketchPos) virtual
Updates the ellipse when the cursor moves.
Parameters
onSketchPos the position of the cursor on the sketch
Implements SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::applyCursor(), SketcherGui::ViewProviderSketch::drawEdit(), PERIAPSIS_APOAPSIS_B, SketcherGui::DrawSketchHandler::renderSuggestConstraintsCursor(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), SketcherGui::DrawSketchHandler::setPositionText(), SketcherGui::DrawSketchHandler::sketchgui, STATUS_SEEK_A, STATUS_SEEK_APOAPSIS, STATUS_SEEK_B, STATUS_SEEK_CENTROID, STATUS_SEEK_PERIAPSIS, sugConstr1, sugConstr2, and sugConstr3.
pressButton()
virtual bool DrawSketchHandlerEllipse::pressButton (Base::Vector2d onSketchPos) virtual
Changes drawing mode on user-click.
Parameters
onSketchPos the position of the cursor on the sketch
Returns
Implements SketcherGui::DrawSketchHandler.
References PERIAPSIS_APOAPSIS_B, STATUS_Close, STATUS_SEEK_APOAPSIS, STATUS_SEEK_B, STATUS_SEEK_CENTROID, and STATUS_SEEK_PERIAPSIS.
releaseButton()
virtual bool DrawSketchHandlerEllipse::releaseButton (Base::Vector2d onSketchPos) virtual
Calls saveEllipse() after last user input.
Parameters
onSketchPos the position of the cursor on the sketch
Returns
Implements SketcherGui::DrawSketchHandler.
References CENTER_PERIAPSIS_B, App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), PERIAPSIS_APOAPSIS_B, STATUS_Close, STATUS_SEEK_CENTROID, and STATUS_SEEK_PERIAPSIS.
Member Data Documentation
sugConstr1
std::vector<AutoConstraint> DrawSketchHandlerEllipse::sugConstr1 protected
Referenced by mouseMove().
sugConstr2
std::vector<AutoConstraint> DrawSketchHandlerEllipse::sugConstr2 protected
Referenced by mouseMove().
sugConstr3
std::vector<AutoConstraint> DrawSketchHandlerEllipse::sugConstr3 protected
Referenced by mouseMove().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/Gui/CommandCreateGeo.cpp