FreeCAD: TechDrawGui::QGEPath Class Reference
TechDrawGui::QGEPath Class Reference
#include <QGEPath.h>
Public Types
enum { Type = QGraphicsItem::UserType + 301 }
Public Types inherited from TechDrawGui::QGIPrimPath
enum { Type = QGraphicsItem::UserType + 170 }
Public Slots
void onDoubleClick (QPointF pos, int markerIndex)
void onDragFinished (QPointF pos, int index)
void onDragging (QPointF pos, int index)
void onEndEdit (void)
Signals
void hover (bool state)
void pointsUpdated (QPointF attach, std::vector< QPointF > deltas)
void selected (bool state)
Public Member Functions
virtual QRectF boundingRect () const override
void clearMarkers ()
void drawGhost (void)
void dumpGhostPoints (const char *text)
void dumpMarkerPos (const char *text)
std::vector< QPointF > getDeltasFromLeader (void)
double getScale (void)
void inEdit (bool b)
bool inEdit (void)
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0) override
QGEPath (QGILeaderLine *leader)
void setEndAdjust (double adjust)
void setPoints (std::vector< QPointF > pts)
void setScale (double s)
void setStartAdjust (double adjust)
virtual QPainterPath shape () const override
void showMarkers (std::vector< QPointF > points)
void startPathEdit (std::vector< QPointF > pathPoints)
int type () const override
void updateParent ()
virtual ~QGEPath ()
Public Member Functions inherited from TechDrawGui::QGIPrimPath
QColor getFillColor (void)
Qt::BrushStyle getFillStyle ()
Qt::PenStyle getStyle ()
virtual double getWidth ()
QGIPrimPath ()
void resetFill ()
virtual void setCapStyle (Qt::PenCapStyle c)
void setFill (QBrush b)
void setFill (QColor c, Qt::BrushStyle s)
void setFillColor (QColor c)
void setFillOverride (bool b)
void setFillStyle (Qt::BrushStyle f)
void setHighlighted (bool state)
virtual void setNormalColor (QColor c)
virtual void setPrettyNormal ()
virtual void setPrettyPre ()
virtual void setPrettySel ()
void setStyle (int s)
void setStyle (Qt::PenStyle s)
virtual void setWidth (double w)
int type () const override
~QGIPrimPath ()
Protected Member Functions
double getEdgeFuzz (void) const
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
Protected Member Functions inherited from TechDrawGui::QGIPrimPath
virtual QColor getNormalColor (void)
Base::Reference< ParameterGrp > getParmGroup (void)
virtual QColor getPreColor (void)
virtual QColor getSelectColor (void)
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) override
virtual Qt::PenCapStyle prefCapStyle (void)
Protected Attributes
double m_endAdj
QGIPrimPath * m_ghost
std::vector< QPointF > m_ghostPoints
bool m_inEdit
std::vector< QGMarker * > m_markers
QGILeaderLine * m_parentLeader
double m_scale
double m_startAdj
Protected Attributes inherited from TechDrawGui::QGIPrimPath
bool isHighlighted
QBrush m_brush
Qt::PenCapStyle m_capStyle
QColor m_colCurrent
QColor m_colDefFill
QColor m_colNormal
QColor m_colNormalFill
bool m_colOverride
QColor m_fillColorCurrent
bool m_fillOverride
Qt::BrushStyle m_fillStyleCurrent
QPen m_pen
Qt::PenStyle m_styleCurrent
Qt::BrushStyle m_styleDef
Qt::BrushStyle m_styleNormal
Qt::BrushStyle m_styleSelect
double m_width
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGEPath()
QGEPath::QGEPath (QGILeaderLine * leader) explicit
References m_ghost, TechDrawGui::QGIPrimPath::QGIPrimPath(), TechDrawGui::QGIPrimPath::setNormalColor(), TechDrawGui::QGIPrimPath::setPrettyNormal(), and TechDrawGui::QGIPrimPath::setStyle().
~QGEPath()
virtual TechDrawGui::QGEPath::~QGEPath () virtual
Member Function Documentation
boundingRect()
QRectF QGEPath::boundingRect () const override virtual
References shape().
clearMarkers()
void QGEPath::clearMarkers ()
References m_markers.
Referenced by TechDrawGui::QGILeaderLine::abandonEdit(), onEndEdit(), and showMarkers().
drawGhost()
void QGEPath::drawGhost (void)
References m_ghost, and m_ghostPoints.
Referenced by onDragFinished().
dumpGhostPoints()
void QGEPath::dumpGhostPoints (const char * text)
References Base::Console(), TechDraw::DrawUtil::formatVector(), m_ghostPoints, and Base::ConsoleSingleton::Message().
dumpMarkerPos()
void QGEPath::dumpMarkerPos (const char * text)
References Base::Console(), TechDraw::DrawUtil::formatVector(), m_markers, and Base::ConsoleSingleton::Message().
getDeltasFromLeader()
std::vector< QPointF > QGEPath::getDeltasFromLeader (void)
References Base::Console(), TechDrawGui::QGILeaderLine::getFeature(), App::PropertyListsT< T, ListT, ParentT >::getValues(), TechDrawGui::Rez::guiX(), m_parentLeader, Base::ConsoleSingleton::Message(), Base::ConsoleSingleton::Warning(), TechDraw::DrawLeaderLine::WayPoints, Base::Vector3< _Precision >::x, and Base::Vector3< _Precision >::y.
getEdgeFuzz()
double QGEPath::getEdgeFuzz (void) const protected
References TechDrawGui::PreferencesGui::edgeFuzz().
Referenced by shape().
getScale()
double TechDrawGui::QGEPath::getScale (void)
hover
void TechDrawGui::QGEPath::hover (bool state) signal
Referenced by hoverEnterEvent(), and hoverLeaveEvent().
hoverEnterEvent()
void QGEPath::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected virtual
Reimplemented from TechDrawGui::QGIPrimPath.
References hover(), TechDrawGui::QGIPrimPath::hoverEnterEvent(), and TechDrawGui::QGIPrimPath::setPrettyPre().
hoverLeaveEvent()
void QGEPath::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected virtual
Reimplemented from TechDrawGui::QGIPrimPath.
References hover(), and TechDrawGui::QGIPrimPath::setPrettyNormal().
inEdit() [1/2]
void TechDrawGui::QGEPath::inEdit (bool b)
Referenced by TechDrawGui::QGILeaderLine::draw(), and TechDrawGui::QGILeaderLine::startPathEdit().
inEdit() [2/2]
bool TechDrawGui::QGEPath::inEdit (void)
Referenced by onEndEdit(), showMarkers(), startPathEdit(), and updateParent().
itemChange()
QVariant QGEPath::itemChange (GraphicsItemChange change, const QVariant & value) override protected virtual
Reimplemented from TechDrawGui::QGIPrimPath.
References TechDrawGui::QGIPrimPath::itemChange(), selected(), TechDrawGui::QGIPrimPath::setPrettyNormal(), and TechDrawGui::QGIPrimPath::setPrettySel().
onDoubleClick
void QGEPath::onDoubleClick (QPointF pos, int markerIndex) slot
References onEndEdit().
Referenced by showMarkers().
onDragFinished
void QGEPath::onDragFinished (QPointF pos, int index) slot
References drawGhost(), and m_ghostPoints.
Referenced by showMarkers().
onDragging
void QGEPath::onDragging (QPointF pos, int index) slot
Referenced by showMarkers().
onEndEdit
void QGEPath::onEndEdit (void) slot
References clearMarkers(), inEdit(), m_ghost, and updateParent().
Referenced by TechDrawGui::QGILeaderLine::closeEdit(), onDoubleClick(), and showMarkers().
paint()
void QGEPath::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) override virtual
Reimplemented from TechDrawGui::QGIPrimPath.
References TechDrawGui::QGIPrimPath::paint().
pointsUpdated
void TechDrawGui::QGEPath::pointsUpdated (QPointF attach, std::vector< QPointF > deltas) signal
Referenced by updateParent().
selected
void TechDrawGui::QGEPath::selected (bool state) signal
Referenced by itemChange(), PathScripts.PathDressupTagGui.HoldingTagMarker::setEnabled(), and PathScripts.PathDressupTagGui.HoldingTagMarker::setSelected().
setEndAdjust()
void QGEPath::setEndAdjust (double adjust)
References TechDrawGui::Rez::guiX(), and m_endAdj.
setPoints()
void TechDrawGui::QGEPath::setPoints (std::vector< QPointF > pts)
setScale()
void TechDrawGui::QGEPath::setScale (double s)
Referenced by TechDrawGui::QGILeaderLine::startPathEdit().
setStartAdjust()
void QGEPath::setStartAdjust (double adjust)
References TechDrawGui::Rez::guiX(), and m_startAdj.
shape()
QPainterPath QGEPath::shape (void) const override virtual
Reimplemented from TechDrawGui::QGIPrimPath.
References getEdgeFuzz().
Referenced by draftguitools.gui_offset.Offset::action(), boundingRect(), PathScripts.PathSurfaceSupport.PathGeometryGenerator::generatePathGeometry(), and draftguitools.gui_offset.Offset::numericRadius().
showMarkers()
void QGEPath::showMarkers (std::vector< QPointF > points)
References clearMarkers(), draftgeoutils.intersections::connect(), Base::Console(), inEdit(), m_markers, Base::ConsoleSingleton::Message(), onDoubleClick(), onDragFinished(), onDragging(), onEndEdit(), and ZVALUE::VERTEX.
Referenced by startPathEdit().
startPathEdit()
void QGEPath::startPathEdit (std::vector< QPointF > pathPoints)
References inEdit(), m_ghostPoints, and showMarkers().
Referenced by TechDrawGui::QGILeaderLine::startPathEdit().
type()
int TechDrawGui::QGEPath::type () const override
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
updateParent()
void QGEPath::updateParent (void)
References inEdit(), m_ghostPoints, and pointsUpdated().
Referenced by onEndEdit().
Member Data Documentation
m_endAdj
double TechDrawGui::QGEPath::m_endAdj protected
Referenced by setEndAdjust().
m_ghost
QGIPrimPath* TechDrawGui::QGEPath::m_ghost protected
Referenced by drawGhost(), onEndEdit(), and QGEPath().
m_ghostPoints
std::vector<QPointF> TechDrawGui::QGEPath::m_ghostPoints protected
Referenced by drawGhost(), dumpGhostPoints(), onDragFinished(), startPathEdit(), and updateParent().
m_inEdit
bool TechDrawGui::QGEPath::m_inEdit protected
m_markers
std::vector<QGMarker*> TechDrawGui::QGEPath::m_markers protected
Referenced by clearMarkers(), dumpMarkerPos(), and showMarkers().
m_parentLeader
QGILeaderLine* TechDrawGui::QGEPath::m_parentLeader protected
Referenced by getDeltasFromLeader().
m_scale
double TechDrawGui::QGEPath::m_scale protected
m_startAdj
double TechDrawGui::QGEPath::m_startAdj protected
Referenced by setStartAdjust().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGEPath.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGEPath.cpp