FreeCAD: TechDrawGui::DlgPrefsTechDrawColorsImp Class Reference
TechDrawGui::DlgPrefsTechDrawColorsImp Class Reference
#include <DlgPrefsTechDrawColorsImp.h>
Public Member Functions
DlgPrefsTechDrawColorsImp (QWidget *parent=nullptr)
~DlgPrefsTechDrawColorsImp ()
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void loadSettings ()
void saveSettings ()
virtual void changeEvent (QEvent *e)=0
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Constructor & Destructor Documentation
DlgPrefsTechDrawColorsImp()
DlgPrefsTechDrawColorsImp::DlgPrefsTechDrawColorsImp (QWidget * parent = nullptr)
~DlgPrefsTechDrawColorsImp()
DlgPrefsTechDrawColorsImp::~DlgPrefsTechDrawColorsImp ()
Member Function Documentation
changeEvent()
void DlgPrefsTechDrawColorsImp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
References loadSettings(), and saveSettings().
loadSettings()
void DlgPrefsTechDrawColorsImp::loadSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
Referenced by changeEvent().
saveSettings()
void DlgPrefsTechDrawColorsImp::saveSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
Referenced by changeEvent().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/DlgPrefsTechDrawColorsImp.h
FreeCAD/src/Mod/TechDraw/Gui/DlgPrefsTechDrawColorsImp.cpp