FreeCAD: colorcodeshapes Namespace Reference
colorcodeshapes Namespace Reference
Functions
def colorcodeshapes (objs)
def mostbasiccompound (comp)
def shapedict (shapelst)
def shapeset (shapelst)
Function Documentation
colorcodeshapes()
def colorcodeshapes.colorcodeshapes (objs)
References mostbasiccompound().
Referenced by OpenSCADCommands.ColorCodeShape.Activated().
mostbasiccompound()
def colorcodeshapes.mostbasiccompound (comp)
searches for the most basic shape in a Compound
References shapeset().
Referenced by colorcodeshapes().
shapedict()
def colorcodeshapes.shapedict (shapelst)
shapeset()
def colorcodeshapes.shapeset (shapelst)
Referenced by mostbasiccompound().