FreeCAD: Gui::GUISingleApplication Class Reference
Gui::GUISingleApplication Class Reference
#include <GuiApplication.h>
Classes
class Private
Signals
void messageReceived (const QList< QByteArray > &)
Public Member Functions
GUISingleApplication (int &argc, char **argv)
bool isRunning () const
bool sendMessage (const QByteArray &message, int timeout=5000)
virtual ~GUISingleApplication ()
Public Member Functions inherited from Gui::GUIApplication
GUIApplication (int &argc, char **argv)
bool notify (QObject *receiver, QEvent *event)
Make forwarding events exception-safe and get more detailed information where an unhandled exception comes from.
virtual ~GUIApplication ()
Public Member Functions inherited from Gui::GUIApplicationNativeEventAware
GUIApplicationNativeEventAware (int &argc, char *argv[])
void initSpaceball (QMainWindow *window)
bool isSpaceballPresent () const
void postButtonEvent (int buttonNumber, int buttonPress)
void postMotionEvent (std::vector< int > motionDataArray)
bool processSpaceballEvent (QObject *object, QEvent *event)
void setSpaceballPresent (bool present)
~GUIApplicationNativeEventAware ()
Additional Inherited Members
Public Slots inherited from Gui::GUIApplication
void commitData (QSessionManager &manager)
Public Attributes inherited from Gui::GUIApplication
std::shared_ptr< Base::SystemExitException > caughtException
Pointer to exceptions caught in Qt event handler.
Protected Member Functions inherited from Gui::GUIApplication
bool event (QEvent *event)
Constructor & Destructor Documentation
GUISingleApplication()
GUISingleApplication::GUISingleApplication (int & argc, char ** argv) explicit
References draftgeoutils.intersections::connect().
~GUISingleApplication()
GUISingleApplication::~GUISingleApplication () virtual
Member Function Documentation
isRunning()
bool GUISingleApplication::isRunning () const
Referenced by Gui::Application::runApplication(), and addonmanager_workers.InstallWorkbenchWorker::update_status().
messageReceived
void Gui::GUISingleApplication::messageReceived (const QList< QByteArray > &) signal
sendMessage()
bool GUISingleApplication::sendMessage (const QByteArray & message, int timeout = 5000)
Referenced by Gui::Application::runApplication().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/GuiApplication.h
FreeCAD/src/Gui/GuiApplication.cpp