FreeCAD: TechDrawGui::MDIViewPage Class Reference
TechDrawGui::MDIViewPage Class Reference
#include <MDIViewPage.h>
Public Slots
void onTimer ()
void saveDXF (void)
void savePDF (void)
void saveSVG (void)
void sceneSelectionChanged ()
update Tree Selection from QGraphicsScene selection
void toggleFrame (void)
void toggleKeepUpdated (void)
void viewAll ()
Public Slots inherited from Gui::MDIView
virtual void setOverrideCursor (const QCursor &)
virtual void restoreOverrideCursor ()
Public Member Functions
void addChildrenToPage (void)
bool addView (const App::DocumentObject *obj)
void attachTemplate (TechDraw::DrawTemplate *obj)
void blockSelection (bool isBlocked)
void centerOnPage (void)
void clearSceneSelection ()
void fixOrphans (bool force=false)
PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
QGVPage * getQGVPage (void)
QPointF getTemplateCenter (TechDraw::DrawTemplate *obj)
void matchSceneRectToTemplate (void)
MDIViewPage (ViewProviderPage *page, Gui::Document *doc, QWidget *parent=0)
bool onHasMsg (const char *pMsg) const
Message handler test.
bool onMsg (const char *pMsg, const char **ppReturn)
Message handler.
void onSelectionChanged (const Gui::SelectionChanges &msg)
Observer message from the Tree Selection mechanism.
void preSelectionChanged (const QPoint &pos)
void print ()
Print content of view.
void print (QPrinter *printer)
void printPdf ()
Print to PDF file.
void printPdf (std::string file)
void printPreview ()
Show a preview dialog.
void redraw1View (TechDraw::DrawView *dv)
void redrawAllViews (void)
void saveDXF (std::string file)
void savePDF (std::string file)
void saveSVG (std::string file)
void selectQGIView (App::DocumentObject *obj, bool state)
QGraphicsScene selection routines.
void setDocumentName (const std::string &)
void setDocumentObject (const std::string &)
void setTabText (std::string t)
void updateTemplate (bool force=false)
virtual ~MDIViewPage ()
Public Member Functions inherited from Gui::MDIView
virtual bool canClose (void)
overwrite when checking on close state
virtual void deleteSelf ()
delete itself
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
View constructor Attach the view to the given document.
virtual void onRelabel (Gui::Document *pDoc)
get called when the document is updated
virtual void viewAll ()
~MDIView ()
View destructor Detach the view from the document, if attached.
QSize minimumSizeHint () const
virtual void setCurrentViewMode (ViewMode mode)
If b is set to FullScreen the MDI view is displayed in full screen mode, if b is set to TopLevel then it is displayed as an own top-level window, otherwise (Normal) as tabbed window.
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=0, std::string *subname=0) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=0)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=0) const
virtual bool containsViewProvider (const ViewProvider *) const
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=0)
View constructor Attach the view to the given document.
virtual ~BaseView ()
View destructor Detach the view from the document, if attached!
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose (void)
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive (void) const
indicates if the view is in passive mode
virtual void onUpdate (void)
get called when the document is updated
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
virtual const char * getName (void) const
returns the name of the view (important for messages)
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual Type getTypeId (void) const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockConnection (bool block)
void detachSelection ()
Detaches from the selection.
bool isConnectionAttached () const
bool isConnectionBlocked () const
SelectionObserver (bool attach=true, int resolve=1)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, int resolve=1)
Constructor.
virtual ~SelectionObserver ()
Static Public Member Functions
static MDIViewPage * getFromScene (const QGraphicsScene *scene)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Public Attributes
QGraphicsScene * m_scene
Protected Types
typedef boost::signals2::connection Connection
Protected Member Functions
bool attachView (App::DocumentObject *obj)
Attaches view of obj to m_view. Returns true on success, false otherwise.
void closeEvent (QCloseEvent *)
bool compareSelections (std::vector< Gui::SelectionObject > treeSel, QList< QGraphicsItem * > sceneSel)
void contextMenuEvent (QContextMenuEvent *event)
void findMissingViews (const std::vector< App::DocumentObject * > &list, std::vector< App::DocumentObject * > &missing)
QPrinter::PaperSize getPaperSize (int w, int h) const
bool hasQView (App::DocumentObject *obj)
Helper function.
void onDeleteObject (const App::DocumentObject &obj)
bool orphanExists (const char *viewName, const std::vector< App::DocumentObject * > &list)
Helper function.
void sceneSelectionManager (void)
maintain QGScene selected items in selection order
void setBalloonGroups (void)
void setDimensionGroups (void)
void setLeaderGroups (void)
void setTreeToSceneSelect (void)
void showStatusMsg (const char *s1, const char *s2, const char *s3) const
Protected Member Functions inherited from Gui::MDIView
void closeEvent (QCloseEvent *e)
void changeEvent (QEvent *e)
Protected Attributes
Connection connectDeletedObject
Protected Attributes inherited from Gui::MDIView
PyObject * pythonObject
Protected Attributes inherited from Gui::BaseView
bool bIsDetached
bool bIsPassive
Additional Inherited Members
Public Types inherited from Gui::MDIView
enum ViewMode { Child, TopLevel, FullScreen }
MDI view mode enum.
Signals inherited from Gui::MDIView
void message (const QString &, int)
Protected Slots inherited from Gui::MDIView
virtual void windowStateChanged (MDIView *)
This method gets called from the main window this view is attached to whenever the window state of the active view changes.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Member Typedef Documentation
Connection
typedef boost::signals2::connection TechDrawGui::MDIViewPage::Connection protected
Constructor & Destructor Documentation
MDIViewPage()
MDIViewPage::MDIViewPage (ViewProviderPage * page, Gui::Document * doc, QWidget * parent = 0)
References draftgeoutils.faces::bind(), draftgeoutils.intersections::connect(), onDeleteObject(), and App::Document::signalDeletedObject.
~MDIViewPage()
MDIViewPage::~MDIViewPage () virtual
References connectDeletedObject.
Member Function Documentation
addChildrenToPage()
void MDIViewPage::addChildrenToPage (void)
References attachTemplate(), attachView(), TechDrawGui::ViewProviderPage::getDrawPage(), App::PropertyLink::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), matchSceneRectToTemplate(), setBalloonGroups(), setDimensionGroups(), setLeaderGroups(), TechDraw::DrawPage::Template, viewAll(), TechDraw::DrawPage::Views, and TechDraw::DrawViewCollection::Views.
addView()
bool MDIViewPage::addView (const App::DocumentObject * obj)
References attachView().
Referenced by TechDrawGui::ViewProviderDrawingView::onGuiRepaint().
attachTemplate()
void MDIViewPage::attachTemplate (TechDraw::DrawTemplate * obj)
References getPaperSize(), and TechDrawGui::QGVPage::setPageTemplate().
Referenced by addChildrenToPage(), and TechDrawGui::ViewProviderTemplate::updateData().
attachView()
bool MDIViewPage::attachView (App::DocumentObject * obj) protected
Attaches view of obj to m_view. Returns true on success, false otherwise.
References TechDrawGui::QGVPage::addDrawView(), TechDrawGui::QGVPage::addDrawViewAnnotation(), TechDrawGui::QGVPage::addDrawViewClip(), TechDrawGui::QGVPage::addDrawViewImage(), TechDrawGui::QGVPage::addDrawViewSpreadsheet(), TechDrawGui::QGVPage::addDrawViewSymbol(), TechDrawGui::QGVPage::addProjectionGroup(), TechDrawGui::QGVPage::addRichAnno(), TechDrawGui::QGVPage::addViewBalloon(), TechDrawGui::QGVPage::addViewDimension(), TechDrawGui::QGVPage::addViewLeader(), TechDrawGui::QGVPage::addViewPart(), TechDrawGui::QGVPage::addViewSection(), TechDrawGui::QGVPage::addWeldSymbol(), Base::Console(), Base::Persistence::getClassTypeId(), and Base::ConsoleSingleton::Log().
Referenced by addChildrenToPage(), addView(), and fixOrphans().
blockSelection()
void MDIViewPage::blockSelection (bool isBlocked)
Referenced by clearSceneSelection(), closeEvent(), TechDrawGui::ViewProviderDrawingView::hide(), onDeleteObject(), onSelectionChanged(), TechDrawGui::QGIViewPart::removePrimitives(), selectQGIView(), and setTreeToSceneSelect().
centerOnPage()
void MDIViewPage::centerOnPage (void)
References TechDrawGui::ViewProviderPage::getDrawPage(), getTemplateCenter(), App::PropertyLink::getValue(), and TechDraw::DrawPage::Template.
clearSceneSelection()
void MDIViewPage::clearSceneSelection ()
References blockSelection(), TechDrawGui::QGIViewBalloon::getBalloonLabel(), TechDrawGui::QGIViewDimension::getDatumLabel(), TechDrawGui::QGVPage::getViews(), TechDrawGui::QGIView::setGroupSelection(), and TechDrawGui::QGIView::updateView().
Referenced by onSelectionChanged().
closeEvent()
void MDIViewPage::closeEvent (QCloseEvent * ev) protected
References blockSelection(), Gui::SelectionObserver::detachSelection(), and Gui::ViewProvider::hide().
compareSelections()
bool MDIViewPage::compareSelections (std::vector< Gui::SelectionObject > treeSel, QList< QGraphicsItem * > sceneSel) protected
References Base::Persistence::getClassTypeId(), and TechDrawGui::QGIView::getViewNameAsString().
Referenced by sceneSelectionChanged().
contextMenuEvent()
void MDIViewPage::contextMenuEvent (QContextMenuEvent * event) protected
findMissingViews()
void MDIViewPage::findMissingViews (const std::vector< App::DocumentObject * > & list, std::vector< App::DocumentObject * > & missing) protected
References Base::Persistence::getClassTypeId(), App::PropertyListsT< T, ListT, ParentT >::getValues(), hasQView(), and TechDraw::DrawViewCollection::Views.
fixOrphans()
void MDIViewPage::fixOrphans (bool force = false)
References attachView(), TechDrawGui::QGVPage::findQViewForDocObj(), TechDraw::DrawPage::getAllViews(), Gui::BaseView::getAppDocument(), TechDrawGui::ViewProviderPage::getDrawPage(), App::DocumentObject::getNameInDocument(), TechDrawGui::QGVPage::getViews(), and TechDrawGui::QGVPage::removeQView().
Referenced by onTimer().
getFromScene()
MDIViewPage * MDIViewPage::getFromScene (const QGraphicsScene * scene) static
Referenced by TechDrawGui::QGIView::getMDIViewPage().
getPaperSize()
QPrinter::PaperSize MDIViewPage::getPaperSize (int w, int h) const protected
Referenced by attachTemplate(), and print().
getPyObject()
PyObject * MDIViewPage::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Gui::MDIView.
References Gui::MDIView::getPyObject().
getQGVPage()
QGVPage* TechDrawGui::MDIViewPage::getQGVPage (void)
Referenced by TechDrawGui::DrawGuiUtil::findPage(), TechDrawGui::QGIView::getGraphicsView(), TechDrawGui::ViewProviderTemplate::getQTemplate(), TechDrawGui::ViewProviderDrawingView::getQView(), TechDrawGui::TaskLeaderLine::onTrackerClicked(), TechDrawGui::TaskCosVertex::TaskCosVertex(), TechDrawGui::TaskDetail::TaskDetail(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), and TechDrawGui::TaskRichAnno::TaskRichAnno().
getTemplateCenter()
QPointF MDIViewPage::getTemplateCenter (TechDraw::DrawTemplate * obj)
References TechDrawGui::Rez::guiX().
Referenced by centerOnPage().
hasQView()
bool MDIViewPage::hasQView (App::DocumentObject * obj) protected
Helper function.
References TechDrawGui::QGVPage::getViews().
Referenced by findMissingViews().
matchSceneRectToTemplate()
void MDIViewPage::matchSceneRectToTemplate (void)
References TechDrawGui::ViewProviderPage::getDrawPage(), App::PropertyLink::getValue(), TechDrawGui::Rez::guiX(), and TechDraw::DrawPage::Template.
Referenced by addChildrenToPage().
onDeleteObject()
void MDIViewPage::onDeleteObject (const App::DocumentObject & obj) protected
References blockSelection(), Base::Persistence::getClassTypeId(), and TechDrawGui::QGVPage::removeQViewByName().
Referenced by MDIViewPage().
onHasMsg()
bool MDIViewPage::onHasMsg (const char * pMsg) const virtual
Message handler test.
Reimplemented from Gui::MDIView.
References Gui::BaseView::getAppDocument().
onMsg()
bool MDIViewPage::onMsg (const char * pMsg, const char ** ppReturn) virtual
Message handler.
receive a message
Reimplemented from Gui::MDIView.
References Gui::BaseView::getGuiDocument(), Gui::Command::updateActive(), and viewAll().
onSelectionChanged()
void MDIViewPage::onSelectionChanged (const Gui::SelectionChanges & msg) virtual
Observer message from the Tree Selection mechanism.
invoked by selection change made in Tree via father MDIView
Implements Gui::SelectionObserver.
References Gui::SelectionChanges::AddSelection, blockSelection(), clearSceneSelection(), Gui::SelectionChanges::ClrSelection, Base::Console(), Base::Persistence::getClassTypeId(), Gui::SelectionSingleton::getSelection(), Base::ConsoleSingleton::Log(), Gui::Selection(), selectQGIView(), and Gui::SelectionChanges::SetSelection.
onTimer
void MDIViewPage::onTimer () slot
References fixOrphans().
orphanExists()
bool MDIViewPage::orphanExists (const char * viewName, const std::vector< App::DocumentObject * > & list) protected
Helper function.
References Base::Persistence::getClassTypeId(), App::PropertyListsT< T, ListT, ParentT >::getValues(), and TechDraw::DrawViewCollection::Views.
preSelectionChanged()
void MDIViewPage::preSelectionChanged (const QPoint & pos)
References App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), TechDrawGui::QGIEdge::getProjIndex(), TechDrawGui::QGIVertex::getProjIndex(), Gui::Selection(), and Gui::SelectionSingleton::setPreselect().
print() [1/2]
void MDIViewPage::print () virtual
Print content of view.
Reimplemented from Gui::MDIView.
Referenced by printPdf(), and printPreview().
print() [2/2]
void MDIViewPage::print (QPrinter * printer) virtual
Reimplemented from Gui::MDIView.
References Gui::SelectionObserver::blockConnection(), Gui::SelectionSingleton::clearSelection(), TechDrawGui::ViewProviderPage::getDrawPage(), TechDrawGui::ViewProviderPage::getFrameState(), getPaperSize(), App::PropertyLink::getValue(), TechDrawGui::Rez::guiX(), TechDrawGui::QGVPage::refreshViews(), Gui::Selection(), TechDrawGui::ViewProviderPage::setFrameState(), TechDrawGui::ViewProviderPage::setTemplateMarkers(), and TechDraw::DrawPage::Template.
printPdf() [1/2]
void MDIViewPage::printPdf () virtual
Print to PDF file.
Reimplemented from Gui::MDIView.
References Gui::getMainWindow(), and Gui::FileDialog::getSaveFileName().
Referenced by savePDF().
printPdf() [2/2]
void MDIViewPage::printPdf (std::string file)
References Base::Console(), print(), and Base::ConsoleSingleton::Warning().
printPreview()
void MDIViewPage::printPreview () virtual
Show a preview dialog.
Reimplemented from Gui::MDIView.
References draftgeoutils.intersections::connect(), and print().
redraw1View()
void MDIViewPage::redraw1View (TechDraw::DrawView * dv)
References App::DocumentObject::getNameInDocument(), and TechDrawGui::QGVPage::getViews().
redrawAllViews()
void MDIViewPage::redrawAllViews (void)
References TechDrawGui::QGVPage::getViews().
saveDXF() [1/2]
void MDIViewPage::saveDXF (std::string file)
References Gui::Command::commitCommand(), Gui::Command::Doc, Base::Tools::escapeEncodeFilename(), TechDrawGui::ViewProviderPage::getDrawPage(), App::DocumentObject::getNameInDocument(), Gui::Command::openCommand(), and draftutils.translate::QT_TRANSLATE_NOOP.
saveDXF [2/2]
void MDIViewPage::saveDXF (void) slot
References Gui::getMainWindow(), and Gui::FileDialog::getSaveFileName().
savePDF() [1/2]
void MDIViewPage::savePDF (std::string file)
References printPdf().
savePDF [2/2]
void MDIViewPage::savePDF (void) slot
References printPdf().
saveSVG() [1/2]
void MDIViewPage::saveSVG (std::string file)
References Base::Console(), TechDrawGui::QGVPage::saveSvg(), and Base::ConsoleSingleton::Warning().
saveSVG [2/2]
void MDIViewPage::saveSVG (void) slot
References Gui::SelectionObserver::blockConnection(), Gui::getMainWindow(), Gui::FileDialog::getSaveFileName(), and TechDrawGui::QGVPage::saveSvg().
sceneSelectionChanged
void MDIViewPage::sceneSelectionChanged () slot
update Tree Selection from QGraphicsScene selection
References compareSelections(), Gui::SelectionSingleton::getSelectionEx(), sceneSelectionManager(), Gui::Selection(), and setTreeToSceneSelect().
sceneSelectionManager()
void MDIViewPage::sceneSelectionManager (void) protected
maintain QGScene selected items in selection order
Referenced by sceneSelectionChanged().
selectQGIView()
void MDIViewPage::selectQGIView (App::DocumentObject * obj, bool state)
QGraphicsScene selection routines.
Update QGIView's selection state based on Selection made outside Drawing Interface.
References blockSelection(), and TechDrawGui::QGVPage::findQViewForDocObj().
Referenced by onSelectionChanged().
setBalloonGroups()
void MDIViewPage::setBalloonGroups (void) protected
References TechDrawGui::QGVPage::addBalloonToParent(), TechDrawGui::QGVPage::findParent(), and TechDrawGui::QGVPage::getViews().
Referenced by addChildrenToPage().
setDimensionGroups()
void MDIViewPage::setDimensionGroups (void) protected
References TechDrawGui::QGVPage::addDimToParent(), TechDrawGui::QGVPage::findParent(), and TechDrawGui::QGVPage::getViews().
Referenced by addChildrenToPage().
setDocumentName()
void MDIViewPage::setDocumentName (const std::string & name)
setDocumentObject()
void MDIViewPage::setDocumentObject (const std::string & name)
setLeaderGroups()
void MDIViewPage::setLeaderGroups (void) protected
References TechDrawGui::QGVPage::addLeaderToParent(), TechDrawGui::QGVPage::findParent(), and TechDrawGui::QGVPage::getViews().
Referenced by addChildrenToPage().
setTabText()
void MDIViewPage::setTabText (std::string t)
References Gui::BaseView::isPassive().
setTreeToSceneSelect()
void MDIViewPage::setTreeToSceneSelect (void) protected
References Gui::SelectionSingleton::addSelection(), Gui::SelectionObserver::blockConnection(), blockSelection(), Gui::SelectionSingleton::clearSelection(), App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), TechDrawGui::QGIEdge::getProjIndex(), TechDrawGui::QGIVertex::getProjIndex(), TechDrawGui::QGIView::getViewObject(), App::DocumentObject::isRemoving(), Gui::Selection(), and showStatusMsg().
Referenced by sceneSelectionChanged().
showStatusMsg()
void MDIViewPage::showStatusMsg (const char * s1, const char * s2, const char * s3) const protected
References Gui::getMainWindow(), and Gui::MainWindow::showMessage().
Referenced by setTreeToSceneSelect().
toggleFrame
void MDIViewPage::toggleFrame (void) slot
References TechDrawGui::ViewProviderPage::toggleFrameState().
toggleKeepUpdated
void MDIViewPage::toggleKeepUpdated (void) slot
References TechDrawGui::ViewProviderPage::getDrawPage(), App::PropertyBool::getValue(), TechDraw::DrawPage::KeepUpdated, and App::PropertyBool::setValue().
updateTemplate()
void MDIViewPage::updateTemplate (bool force = false)
References Base::Console(), Base::Persistence::getClassTypeId(), TechDrawGui::ViewProviderPage::getDrawPage(), App::DocumentObject::getNameInDocument(), TechDrawGui::QGVPage::getTemplate(), App::PropertyLink::getValue(), Base::BaseClass::isDerivedFrom(), App::DocumentObject::isTouched(), App::Property::isTouched(), Base::ConsoleSingleton::Log(), TechDrawGui::QGITemplate::setTemplate(), TechDraw::DrawPage::Template, and TechDrawGui::QGITemplate::updateView().
viewAll
void MDIViewPage::viewAll (void) slot
Referenced by addChildrenToPage(), onMsg(), and TechDrawGui::ViewProviderTemplate::updateData().
Member Data Documentation
connectDeletedObject
Connection TechDrawGui::MDIViewPage::connectDeletedObject protected
Referenced by ~MDIViewPage().
m_scene
QGraphicsScene* TechDrawGui::MDIViewPage::m_scene
Referenced by TechDrawGui::TaskCosVertex::TaskCosVertex(), TechDrawGui::TaskDetail::TaskDetail(), and TechDrawGui::TaskLeaderLine::TaskLeaderLine().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/MDIViewPage.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/MDIViewPage.cpp