FreeCAD: PythonStdOutput Class Reference
PythonStdOutput Class Reference
Public Member Functions
Py::Object flush (const Py::Tuple &)
PythonStdOutput ()
Py::Object write (const Py::Tuple &)
~PythonStdOutput ()
Static Public Member Functions
static void init_type (void)
Constructor & Destructor Documentation
PythonStdOutput()
PythonStdOutput::PythonStdOutput ()
~PythonStdOutput()
PythonStdOutput::~PythonStdOutput ()
Member Function Documentation
flush()
Py::Object PythonStdOutput::flush (const Py::Tuple &)
Referenced by init_type().
init_type()
static void PythonStdOutput::init_type (void) static
References flush(), and write().
Referenced by Base::InterpreterSingleton::init().
write()
Py::Object PythonStdOutput::write (const Py::Tuple &)
Referenced by init_type(), and gzip_utf8.GzipFile::seek().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Base/Interpreter.cpp