FreeCAD: Gui::CommandPy Class Reference
Gui::CommandPy Class Reference
The python export class for Command.
#include <CommandPy.h>
Public Types
typedef Command * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
CommandPy (Command *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Command * getCommandPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of CommandPy.
static PyMethodDef Methods []
Methods structure of CommandPy.
static PyTypeObject Type
Type structure of CommandPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~CommandPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * run (PyObject *args)
implementer for the run() method
PyObject * isActive (PyObject *args)
implementer for the isActive() method
PyObject * getShortcut (PyObject *args)
implementer for the getShortcut() method
PyObject * setShortcut (PyObject *args)
implementer for the setShortcut() method
PyObject * resetShortcut (PyObject *args)
implementer for the resetShortcut() method
PyObject * getInfo (PyObject *args)
implementer for the getInfo() method
PyObject * getAction (PyObject *args)
implementer for the getAction() method
static PyObject * staticCallback_get (PyObject *self, PyObject *args)
callback for the get() method
static PyObject * get (PyObject *args)
implementer for the get() method
static PyObject * staticCallback_update (PyObject *self, PyObject *args)
callback for the update() method
static PyObject * update (PyObject *args)
implementer for the update() method
static PyObject * staticCallback_listAll (PyObject *self, PyObject *args)
callback for the listAll() method
static PyObject * listAll (PyObject *args)
implementer for the listAll() method
static PyObject * staticCallback_listByShortcut (PyObject *self, PyObject *args)
callback for the listByShortcut() method
static PyObject * listByShortcut (PyObject *args)
implementer for the listByShortcut() method
static PyObject * staticCallback_run (PyObject *self, PyObject *args)
callback for the run() method
static PyObject * staticCallback_isActive (PyObject *self, PyObject *args)
callback for the isActive() method
static PyObject * staticCallback_getShortcut (PyObject *self, PyObject *args)
callback for the getShortcut() method
static PyObject * staticCallback_setShortcut (PyObject *self, PyObject *args)
callback for the setShortcut() method
static PyObject * staticCallback_resetShortcut (PyObject *self, PyObject *args)
callback for the resetShortcut() method
static PyObject * staticCallback_getInfo (PyObject *self, PyObject *args)
callback for the getInfo() method
static PyObject * staticCallback_getAction (PyObject *self, PyObject *args)
callback for the getAction() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Command.
Member Typedef Documentation
PointerType
typedef Command* Gui::CommandPy::PointerType
Constructor & Destructor Documentation
~CommandPy()
CommandPy::~CommandPy () protected
CommandPy()
CommandPy::CommandPy (Command * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
get()
PyObject * CommandPy::get (PyObject * args) static
implementer for the get() method
Referenced by draftguitools.gui_trackers.editTracker::move(), and staticCallback_get().
getAction()
PyObject * CommandPy::getAction (PyObject * args)
implementer for the getAction() method
References Base::BaseExceptionFreeCADError, Gui::PythonWrapper::fromQObject(), Gui::CommandBase::getAction(), and Gui::PythonWrapper::loadWidgetsModule().
Referenced by staticCallback_getAction().
getCommandPtr()
Command * CommandPy::getCommandPtr (void) const
getter for the object handled by this class
getCustomAttributes()
PyObject* Gui::CommandPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getInfo()
PyObject * CommandPy::getInfo (PyObject * args)
implementer for the getInfo() method
References Base::BaseExceptionFreeCADError, Gui::CommandBase::getAction(), Gui::CommandBase::getMenuText(), Gui::CommandBase::getPixmap(), Gui::CommandBase::getStatusTip(), Gui::CommandBase::getToolTipText(), and Gui::CommandBase::getWhatsThis().
Referenced by staticCallback_getInfo().
getShortcut()
PyObject * CommandPy::getShortcut (PyObject * args)
implementer for the getShortcut() method
References Base::BaseExceptionFreeCADError, Gui::CommandBase::getAction(), and Gui::Action::shortcut().
Referenced by staticCallback_getShortcut().
GetType()
virtual PyTypeObject* Gui::CommandPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
isActive()
PyObject * CommandPy::isActive (PyObject * args)
implementer for the isActive() method
References Base::BaseExceptionFreeCADError, and Gui::Command::isActive().
Referenced by staticCallback_isActive().
listAll()
PyObject * CommandPy::listAll (PyObject * args) static
implementer for the listAll() method
Referenced by staticCallback_listAll().
listByShortcut()
PyObject * CommandPy::listByShortcut (PyObject * args) static
implementer for the listByShortcut() method
Referenced by staticCallback_listByShortcut().
PyInit()
int CommandPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
PyMake()
PyObject * CommandPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string Gui::CommandPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
resetShortcut()
PyObject * CommandPy::resetShortcut (PyObject * args)
implementer for the resetShortcut() method
test to see if we successfully reset the shortcut by loading it back and comparing
References Base::BaseExceptionFreeCADError, Gui::CommandBase::getAccel(), Gui::CommandBase::getAction(), ParameterGrp::GetGroup(), Gui::Command::getName(), and ParameterGrp::RemoveASCII().
Referenced by staticCallback_resetShortcut().
run()
PyObject * CommandPy::run (PyObject * args)
implementer for the run() method
References Base::BaseExceptionFreeCADError, and Gui::Command::invoke().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femsolver.task.Task::protector(), and staticCallback_run().
setCustomAttributes()
int Gui::CommandPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setShortcut()
PyObject * CommandPy::setShortcut (PyObject * args)
implementer for the setShortcut() method
avoid cluttering parameters unnecessarily by saving only when new shortcut is not the default shortcut remove spaces to handle cases such as shortcut = "C,L" or "C, L"
References Base::BaseExceptionFreeCADError, Gui::CommandBase::getAccel(), Gui::CommandBase::getAction(), ParameterGrp::GetGroup(), Gui::Command::getName(), ParameterGrp::RemoveASCII(), and ParameterGrp::SetASCII().
Referenced by staticCallback_setShortcut().
staticCallback_get()
PyObject * CommandPy::staticCallback_get (PyObject * self, PyObject * args) static
callback for the get() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, and get().
staticCallback_getAction()
PyObject * CommandPy::staticCallback_getAction (PyObject * self, PyObject * args) static
callback for the getAction() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getAction(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getInfo()
PyObject * CommandPy::staticCallback_getInfo (PyObject * self, PyObject * args) static
callback for the getInfo() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getInfo(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getShortcut()
PyObject * CommandPy::staticCallback_getShortcut (PyObject * self, PyObject * args) static
callback for the getShortcut() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getShortcut(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_isActive()
PyObject * CommandPy::staticCallback_isActive (PyObject * self, PyObject * args) static
callback for the isActive() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isActive(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_listAll()
PyObject * CommandPy::staticCallback_listAll (PyObject * self, PyObject * args) static
callback for the listAll() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, and listAll().
staticCallback_listByShortcut()
PyObject * CommandPy::staticCallback_listByShortcut (PyObject * self, PyObject * args) static
callback for the listByShortcut() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, and listByShortcut().
staticCallback_resetShortcut()
PyObject * CommandPy::staticCallback_resetShortcut (PyObject * self, PyObject * args) static
callback for the resetShortcut() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), resetShortcut(), and Base::PyObjectBase::startNotify().
staticCallback_run()
PyObject * CommandPy::staticCallback_run (PyObject * self, PyObject * args) static
callback for the run() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), run(), and Base::PyObjectBase::startNotify().
staticCallback_setShortcut()
PyObject * CommandPy::staticCallback_setShortcut (PyObject * self, PyObject * args) static
callback for the setShortcut() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setShortcut(), and Base::PyObjectBase::startNotify().
staticCallback_update()
PyObject * CommandPy::staticCallback_update (PyObject * self, PyObject * args) static
callback for the update() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, and update().
update()
PyObject * CommandPy::update (PyObject * args) static
implementer for the update() method
References Gui::getMainWindow(), and Gui::MainWindow::updateActions().
Referenced by ArchAxis.AxisSystemTaskPanel::addElement(), ArchComponent.ComponentTaskPanel::addElement(), ArchSectionPlane.SectionPlaneTaskPanel::addElement(), DraftGui.FacebinderTaskPanel::addElement(), femtaskpanels.task_result_mechanical._TaskPanel::calculate(), Spreadsheet_legacy.SpreadsheetView::changeCell(), draftguitools.gui_edit.Edit::endEditing(), draftguitools.gui_trackers.boxTracker::height(), ArchAxis.CommandArchGrid::IsActive(), draftguitools.gui_trackers.rectangleTracker::p3(), Plot.Plot::plot(), Spreadsheet_legacy.SpreadsheetView::recompute(), ArchAxis.AxisSystemTaskPanel::removeElement(), ArchComponent.ComponentTaskPanel::removeElement(), ArchSectionPlane.SectionPlaneTaskPanel::removeElement(), DraftGui.FacebinderTaskPanel::removeElement(), draftguitools.gui_trackers.gridTracker::reset(), ArchNesting.Nester::run(), and staticCallback_update().
Member Data Documentation
GetterSetter
PyGetSetDef CommandPy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of CommandPy.
Methods
PyMethodDef CommandPy::Methods static
Methods structure of CommandPy.
Type
PyTypeObject CommandPy::Type static
Type structure of CommandPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), Gui::Application::Application(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Gui/CommandPy.h
Sources/FreeCAD/src/Gui/CommandPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Gui/CommandPy.cpp