FreeCAD: PathScripts.post.mach3_mach4_post Namespace Reference
PathScripts.post.mach3_mach4_post Namespace Reference
Functions
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
def processArguments (argstring)
Variables
action
string COMMAND_SPACE = " "
dictionary CORNER_MAX = {'x': 500, 'y': 300, 'z': 300}
dictionary CORNER_MIN = {'x': 0, 'y': 0, 'z': 0}
default
help
int LINENR = 100
string MACHINE_NAME = "mach3_4"
bool MODAL = False
now = datetime.datetime.now()
bool OUTPUT_COMMENTS = True
bool OUTPUT_DOUBLES = True
bool OUTPUT_HEADER = True
bool OUTPUT_LINE_NUMBERS = False
parser = argparse.ArgumentParser(prog='mach3_4', add_help=False)
string POST_OPERATION = ''''''
string POSTAMBLE
string PRE_OPERATION = ''''''
string PREAMBLE
int PRECISION = 3
pythonopen = open
bool SHOW_EDITOR = True
string TOOL_CHANGE = ''''''
string TOOLTIP
TOOLTIP_ARGS = parser.format_help()
string UNIT_FORMAT = 'mm'
string UNIT_SPEED_FORMAT = 'mm/min'
string UNITS = "G21"
bool USE_TLO = True
Function Documentation
export()
def PathScripts.post.mach3_mach4_post.export (objectslist, filename, argstring)
References PathScripts.post.mach3_mach4_post.linenumber(), PathScripts.post.mach3_mach4_post.parse(), PathScripts.post.mach3_mach4_post.processArguments(), and PathScripts.post.mach3_mach4_post.pythonopen.
linenumber()
def PathScripts.post.mach3_mach4_post.linenumber ()
Referenced by PathScripts.post.mach3_mach4_post.export(), and PathScripts.post.mach3_mach4_post.parse().
parse()
def PathScripts.post.mach3_mach4_post.parse (pathobj)
References PathScripts.post.mach3_mach4_post.linenumber().
Referenced by PathScripts.post.mach3_mach4_post.export().
processArguments()
def PathScripts.post.mach3_mach4_post.processArguments (argstring)
Referenced by PathScripts.post.mach3_mach4_post.export().
Variable Documentation
action
PathScripts.post.mach3_mach4_post.action
COMMAND_SPACE
string PathScripts.post.mach3_mach4_post.COMMAND_SPACE = " "
CORNER_MAX
dictionary PathScripts.post.mach3_mach4_post.CORNER_MAX = {'x': 500, 'y': 300, 'z': 300}
CORNER_MIN
dictionary PathScripts.post.mach3_mach4_post.CORNER_MIN = {'x': 0, 'y': 0, 'z': 0}
default
PathScripts.post.mach3_mach4_post.default
help
PathScripts.post.mach3_mach4_post.help
LINENR
int PathScripts.post.mach3_mach4_post.LINENR = 100
MACHINE_NAME
string PathScripts.post.mach3_mach4_post.MACHINE_NAME = "mach3_4"
MODAL
bool PathScripts.post.mach3_mach4_post.MODAL = False
now
PathScripts.post.mach3_mach4_post.now = datetime.datetime.now()
OUTPUT_COMMENTS
bool PathScripts.post.mach3_mach4_post.OUTPUT_COMMENTS = True
OUTPUT_DOUBLES
bool PathScripts.post.mach3_mach4_post.OUTPUT_DOUBLES = True
OUTPUT_HEADER
bool PathScripts.post.mach3_mach4_post.OUTPUT_HEADER = True
OUTPUT_LINE_NUMBERS
bool PathScripts.post.mach3_mach4_post.OUTPUT_LINE_NUMBERS = False
parser
PathScripts.post.mach3_mach4_post.parser = argparse.ArgumentParser(prog='mach3_4', add_help=False)
POST_OPERATION
string PathScripts.post.mach3_mach4_post.POST_OPERATION = ''''''
POSTAMBLE
string PathScripts.post.mach3_mach4_post.POSTAMBLE
Initial value:
 =  '''M05
 G17 G54 G90 G80 G40
 M2
 '''
PRE_OPERATION
string PathScripts.post.mach3_mach4_post.PRE_OPERATION = ''''''
PREAMBLE
string PathScripts.post.mach3_mach4_post.PREAMBLE
Initial value:
 =  '''G17 G54 G40 G49 G80 G90
 '''
PRECISION
int PathScripts.post.mach3_mach4_post.PRECISION = 3
pythonopen
PathScripts.post.mach3_mach4_post.pythonopen = open
Referenced by PathScripts.post.mach3_mach4_post.export().
SHOW_EDITOR
bool PathScripts.post.mach3_mach4_post.SHOW_EDITOR = True
TOOL_CHANGE
string PathScripts.post.mach3_mach4_post.TOOL_CHANGE = ''''''
TOOLTIP
string PathScripts.post.mach3_mach4_post.TOOLTIP
Initial value:
 =  '''
 This is a postprocessor file for the Path workbench. It is used to
 take a pseudo-gcode fragment outputted by a Path object, and output
 real GCode suitable for a mach3_4 3 axis mill. This postprocessor, once placed
 in the appropriate PathScripts folder, can be used directly from inside
 FreeCAD, via the GUI importer or via python scripts with:
 import mach3_4_post
 mach3_4_post.export(object,"/path/to/file.ncc","")
 '''
TOOLTIP_ARGS
PathScripts.post.mach3_mach4_post.TOOLTIP_ARGS = parser.format_help()
UNIT_FORMAT
string PathScripts.post.mach3_mach4_post.UNIT_FORMAT = 'mm'
UNIT_SPEED_FORMAT
string PathScripts.post.mach3_mach4_post.UNIT_SPEED_FORMAT = 'mm/min'
UNITS
string PathScripts.post.mach3_mach4_post.UNITS = "G21"
USE_TLO
bool PathScripts.post.mach3_mach4_post.USE_TLO = True