FreeCAD: StdMeshers::FunctionTable Class Reference
StdMeshers::FunctionTable Class Reference
#include <StdMeshers_Distribution.hxx>
Public Member Functions
FunctionTable (const std::vector< double > &, const int)
virtual double integral (const double, const double) const
virtual bool value (const double, double &) const
virtual ~FunctionTable ()
Public Member Functions inherited from StdMeshers::Function
Function (const int)
virtual ~Function ()
Constructor & Destructor Documentation
FunctionTable()
StdMeshers::FunctionTable::FunctionTable (const std::vector< double > & data, const int conv)
~FunctionTable()
StdMeshers::FunctionTable::~FunctionTable () virtual
Member Function Documentation
integral()
double StdMeshers::FunctionTable::integral (const double a, const double b) const virtual
Implements StdMeshers::Function.
value()
bool StdMeshers::FunctionTable::value (const double t, double & f) const virtual
Reimplemented from StdMeshers::Function.
References StdMeshers::Function::value().
Referenced by PathScripts.PathProperty.Property::displayString(), PathScripts.PathProperty.PropertyQuantity::displayString(), PathScripts.PathSetupSheetOpPrototype.Property::displayString(), PathScripts.PathSetupSheetOpPrototype.PropertyQuantity::displayString(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), PathScripts.PathProperty.Property::getValue(), PathScripts.PathSetupSheetOpPrototype.Property::getValue(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), PathScripts.PathProperty.Property::setValue(), and PathScripts.PathSetupSheetOpPrototype.Property::setValue().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_Distribution.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_Distribution.cpp