FreeCAD: Gui::SoGLWidgetNode Class Reference
Gui::SoGLWidgetNode Class Reference
#include <SoFCInteractiveElement.h>
Public Member Functions
virtual void doAction (SoAction *action)
virtual void GLRender (SoGLRenderAction *action)
SoGLWidgetNode (void)
Static Public Member Functions
static void initClass (void)
Public Attributes
QtGLWidget * window
Protected Member Functions
virtual ~SoGLWidgetNode ()
Constructor & Destructor Documentation
SoGLWidgetNode()
SoGLWidgetNode::SoGLWidgetNode (void)
Constructor.
~SoGLWidgetNode()
SoGLWidgetNode::~SoGLWidgetNode () protected virtual
Destructor.
Member Function Documentation
doAction()
void SoGLWidgetNode::doAction (SoAction * action) virtual
References Gui::SoGLWidgetElement::set().
Referenced by GLRender().
GLRender()
void SoGLWidgetNode::GLRender (SoGLRenderAction * action) virtual
References doAction().
initClass()
void SoGLWidgetNode::initClass (void) static
Referenced by Gui::SoFCDB::init().
Member Data Documentation
window
QtGLWidget* Gui::SoGLWidgetNode::window
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SoFCInteractiveElement.h
Sources/FreeCAD/src/Gui/SoFCInteractiveElement.cpp