FreeCAD: Gui::CommandIconView Class Reference
Gui::CommandIconView Class Reference
This class allows to drag one or more items which correspond to a Command object.
#include <Widgets.h>
Signals
void emitSelectionChanged (const QString &)
Emits this signal if selection has changed.
Public Member Functions
CommandIconView (QWidget *parent=nullptr)
Constructs an empty command view with parent parent.
virtual ~CommandIconView ()
Destroys the icon view and deletes all items.
Protected Slots
void onSelectionChanged (QListWidgetItem *item, QListWidgetItem *)
This slot is called when a new item becomes current.
Protected Member Functions
void startDrag (Qt::DropActions supportedActions)
Stores the name of the selected commands for drag and drop.
Detailed Description
This class allows to drag one or more items which correspond to a Command object.
The dragged items can be dropped onto the Gui::PythonConsole.
See also
CommandViewItem, Command
Author
Werner Mayer
Constructor & Destructor Documentation
CommandIconView()
CommandIconView::CommandIconView (QWidget * parent = nullptr)
Constructs an empty command view with parent parent.
References draftgeoutils.intersections::connect(), and onSelectionChanged().
~CommandIconView()
CommandIconView::~CommandIconView () virtual
Destroys the icon view and deletes all items.
Member Function Documentation
emitSelectionChanged
void Gui::CommandIconView::emitSelectionChanged (const QString &) signal
Emits this signal if selection has changed.
Referenced by onSelectionChanged().
onSelectionChanged
void CommandIconView::onSelectionChanged (QListWidgetItem * item, QListWidgetItem *) protected slot
This slot is called when a new item becomes current.
item is the new current item (or 0 if no item is now current). This slot emits the emitSelectionChanged() signal for its part.
References emitSelectionChanged().
Referenced by CommandIconView().
startDrag()
void CommandIconView::startDrag (Qt::DropActions supportedActions) protected
Stores the name of the selected commands for drag and drop.
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/Widgets.h
FreeCAD/src/Gui/Widgets.cpp