FreeCAD: Gui::WorkbenchFactoryInst Class Reference
Gui::WorkbenchFactoryInst Class Reference
The workbench factory provides methods for the dynamic creation of special workbenches for each module.
#include <WorkbenchFactory.h>
Public Member Functions
Workbench * createWorkbench (const char *sName) const
Creates the workbench with name.
std::list< std::string > workbenches () const
Returns a list of all registered workbench classes.
Public Member Functions inherited from Base::Factory
void AddProducer (const char *sClassName, AbstractProducer *pcProducer)
Adds a new prducer instance.
std::list< std::string > CanProduce () const
returns a list of all registered producer
bool CanProduce (const char *sClassName) const
returns true if there is a producer for this class registered
Static Public Member Functions
static void destruct ()
Destructs the sole instance.
static WorkbenchFactoryInst & instance ()
The one and only instance.
Additional Inherited Members
Protected Member Functions inherited from Base::Factory
Factory (void)
construction
void * Produce (const char *sClassName) const
produce a class with the given name
virtual ~Factory ()
destruction
Detailed Description
The workbench factory provides methods for the dynamic creation of special workbenches for each module.
To create these workbenches once they must be registered through a subclass of WorkbenchProducer.
Note
To create workbenches you should use the API of WorkbenchManager.
Author
Werner Mayer
Member Function Documentation
createWorkbench()
Workbench * WorkbenchFactoryInst::createWorkbench (const char * sName) const
Creates the workbench with name.
If no such workbench is registered 0 is returned.
References Base::Factory::Produce(), and Gui::Workbench::setName().
destruct()
void WorkbenchFactoryInst::destruct (void) static
Destructs the sole instance.
instance()
WorkbenchFactoryInst & WorkbenchFactoryInst::instance (void) static
The one and only instance.
Referenced by Gui::WorkbenchFactory().
workbenches()
std::list< std::string > WorkbenchFactoryInst::workbenches (void) const
Returns a list of all registered workbench classes.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/WorkbenchFactory.h
Sources/FreeCAD/src/Gui/WorkbenchFactory.cpp