FreeCAD: MeshCore::SetOperations Class Reference
MeshCore::SetOperations Class Reference
The MeshAlgorithm class provides algorithms base on meshes.
#include <SetOperations.h>
Public Types
enum OperationType {
Union , Intersect , Difference , Inner ,
Outer
}
Public Member Functions
void Do ()
Cut this mesh with another one.
SetOperations (const MeshKernel &cutMesh1, const MeshKernel &cutMesh2, MeshKernel &result, OperationType opType, float minDistanceToPoint=1e-5f)
Construction.
virtual ~SetOperations (void)
Destruction.
Detailed Description
The MeshAlgorithm class provides algorithms base on meshes.
Member Enumeration Documentation
OperationType
enum MeshCore::SetOperations::OperationType
Enumerator
Union
Intersect
Difference
Inner
Outer
Constructor & Destructor Documentation
SetOperations()
SetOperations::SetOperations (const MeshKernel & cutMesh1, const MeshKernel & cutMesh2, MeshKernel & result, OperationType opType, float minDistanceToPoint = 1e-5f)
Construction.
~SetOperations()
SetOperations::~SetOperations (void) virtual
Destruction.
Member Function Documentation
Do()
void SetOperations::Do (void)
Cut this mesh with another one.
The result is a list of polylines If the distance of the polyline to one of the points is less than minDistanceToPoint the polyline goes direct to the point
References Difference, Inner, Intersect, Outer, MeshCore::MeshDefinitions::SetMinPointDistance(), and Union.
Referenced by Mesh::SetOperations::execute(), Mesh::MeshObject::inner(), Mesh::MeshObject::intersect(), Mesh::MeshObject::outer(), Mesh::MeshObject::subtract(), and Mesh::MeshObject::unite().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/SetOperations.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/SetOperations.cpp