FreeCAD: Gui::ViewProviderPythonFeatureT< ViewProviderT > Class Template Reference
Gui::ViewProviderPythonFeatureT< ViewProviderT > Class Template Reference
#include <ViewProviderPythonFeature.h>
Public Member Functions
std::vector< App::DocumentObject * > claimChildren () const override
QIcon getIcon () const override
ViewProviderPythonFeatureT ()
constructor.
virtual ~ViewProviderPythonFeatureT ()
destructor.
Nodes
virtual SoSeparator * getRoot () const override
virtual SoSeparator * getFrontRoot () const override
virtual SoSeparator * getBackRoot () const override
Selection handling
virtual bool useNewSelectionModel () const override
virtual bool getElementPicked (const SoPickedPoint *pp, std::string &subname) const override
virtual std::string getElement (const SoDetail *det) const override
virtual SoDetail * getDetail (const char *name) const override
virtual bool getDetailPath (const char *name, SoFullPath *path, bool append, SoDetail *&det) const override
virtual std::vector< Base::Vector3d > getSelectionShape (const char *Element) const override
Update data methods
virtual void attach (App::DocumentObject *obj) override
virtual void updateData (const App::Property *prop) override
virtual void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &c) const override
virtual bool onDelete (const std::vector< std::string > &sub) override
virtual bool canDelete (App::DocumentObject *obj) const override
Restoring view provider from document load
virtual void startRestoring () override
virtual void finishRestoring () override
Drag and drop
virtual bool canDragObjects () const override
Returns true if the view provider generally supports dragging objects.
virtual bool canDragObject (App::DocumentObject *obj) const override
Check whether the object can be removed from the view provider by drag and drop.
virtual void dragObject (App::DocumentObject *obj) override
Starts to drag the object.
virtual bool canDropObjects () const override
Returns true if the view provider generally accepts dropping of objects.
virtual bool canDropObject (App::DocumentObject *obj) const override
Check whether the object can be dropped to the view provider by drag and drop.
virtual void dropObject (App::DocumentObject *obj) override
If the dropped object type is accepted the object will be added as child.
virtual bool canDragAndDropObject (App::DocumentObject *obj) const override
Return false to force drop only operation for a give object.
virtual bool canDropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements) const override
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements) override
Add an object with full qualified name to the view provider by drag and drop.
Public Member Functions inherited from Gui::ViewProviderT
std::string getAppDocumentPython () const
Document * getDocument () const
const std::string & getDocumentName () const
std::string getGuiDocumentPython () const
template<typename T >
T * getObjectAs () const
const std::string & getObjectName () const
std::string getObjectPython () const
ViewProviderDocumentObject * getViewProvider () const
void operator= (const ViewProviderDocumentObject *)
ViewProviderT & operator= (const ViewProviderT &)
ViewProviderT & operator= (ViewProviderT &&)
bool operator== (const ViewProviderT &) const
ViewProviderT ()
ViewProviderT (const ViewProviderDocumentObject *)
ViewProviderT (const ViewProviderT &)
ViewProviderT (ViewProviderT &&)
~ViewProviderT ()
Display methods
virtual bool isShow () const override
Returns true if the icon must always appear enabled in the tree view.
virtual const char * getDefaultDisplayMode () const override
get the default display mode
virtual std::vector< std::string > getDisplayModes (void) const override
returns a list of all possible modes
virtual void setDisplayMode (const char *ModeName) override
set the display mode
virtual bool canRemoveChildrenFromRoot () const override
PyObject * getPyObject () override
virtual bool canAddToSceneGraph () const override
virtual void setupContextMenu (QMenu *menu, QObject *recipient, const char *member) override
ViewProviderPythonFeatureT (const ViewProviderPythonFeatureT &)=delete
ViewProviderPythonFeatureT (ViewProviderPythonFeatureT &&)=delete
ViewProviderPythonFeatureT & operator= (const ViewProviderPythonFeatureT &)=delete
ViewProviderPythonFeatureT & operator= (ViewProviderPythonFeatureT &&)=delete
virtual void onChanged (const App::Property *prop) override
virtual bool setEdit (int ModNum) override
is called by the document when the provider goes in edit mode
virtual void unsetEdit (int ModNum) override
is called when you lose the edit mode
virtual void setEditViewer (View3DInventorViewer *viewer, int ModNum) override
virtual void unsetEditViewer (View3DInventorViewer *viewer) override
virtual std::string getDropPrefix () const override
virtual int replaceObject (App::DocumentObject *oldObj, App::DocumentObject *newObj) override
virtual ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=nullptr, bool recursive=false) const override
virtual void editProperty (const char *propName) override
virtual bool doubleClicked (void) override
virtual void setOverrideMode (const std::string &mode) override
Constructor & Destructor Documentation
ViewProviderPythonFeatureT() [1/3]
template<class ViewProviderT > Gui::ViewProviderPythonFeatureT< ViewProviderT >::ViewProviderPythonFeatureT ()
constructor.
~ViewProviderPythonFeatureT()
template<class ViewProviderT > virtual Gui::ViewProviderPythonFeatureT< ViewProviderT >::~ViewProviderPythonFeatureT () virtual
destructor.
ViewProviderPythonFeatureT() [2/3]
template<class ViewProviderT > Gui::ViewProviderPythonFeatureT< ViewProviderT >::ViewProviderPythonFeatureT (const ViewProviderPythonFeatureT< ViewProviderT > &) delete
ViewProviderPythonFeatureT() [3/3]
template<class ViewProviderT > Gui::ViewProviderPythonFeatureT< ViewProviderT >::ViewProviderPythonFeatureT (ViewProviderPythonFeatureT< ViewProviderT > &&) delete
Member Function Documentation
attach()
template<class ViewProviderT > virtual void Gui::ViewProviderPythonFeatureT< ViewProviderT >::attach (App::DocumentObject * obj) override virtual
canAddToSceneGraph()
template<class ViewProviderT > virtual bool Gui::ViewProviderPythonFeatureT< ViewProviderT >::canAddToSceneGraph () const override virtual
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::canAddToSceneGraph(), and Gui::ViewProviderPythonFeatureImp::Rejected.
Referenced by Gui::ViewProviderPythonFeatureT< ViewProviderT >::onChanged().
canDelete()
template<class ViewProviderT > virtual bool Gui::ViewProviderPythonFeatureT< ViewProviderT >::canDelete (App::DocumentObject * obj) const override virtual
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::canDelete(), and Gui::ViewProviderPythonFeatureImp::Rejected.
canDragAndDropObject()
template<class ViewProviderT > virtual bool Gui::ViewProviderPythonFeatureT< ViewProviderT >::canDragAndDropObject (App::DocumentObject * obj) const override virtual
Return false to force drop only operation for a give object.
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::canDragAndDropObject(), and Gui::ViewProviderPythonFeatureImp::Rejected.
canDragObject()
template<class ViewProviderT > virtual bool Gui::ViewProviderPythonFeatureT< ViewProviderT >::canDragObject (App::DocumentObject * obj) const override virtual
Check whether the object can be removed from the view provider by drag and drop.
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::canDragObject(), and Gui::ViewProviderPythonFeatureImp::Rejected.
canDragObjects()
template<class ViewProviderT > virtual bool Gui::ViewProviderPythonFeatureT< ViewProviderT >::canDragObjects () const override virtual
Returns true if the view provider generally supports dragging objects.
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::canDragObjects(), and Gui::ViewProviderPythonFeatureImp::Rejected.
canDropObject()
template<class ViewProviderT > virtual bool Gui::ViewProviderPythonFeatureT< ViewProviderT >::canDropObject (App::DocumentObject * obj) const override virtual
Check whether the object can be dropped to the view provider by drag and drop.
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::canDropObject(), and Gui::ViewProviderPythonFeatureImp::Rejected.
canDropObjectEx()
template<class ViewProviderT > virtual bool Gui::ViewProviderPythonFeatureT< ViewProviderT >::canDropObjectEx (App::DocumentObject * obj, App::DocumentObject * owner, const char * subname, const std::vector< std::string > & elements) const override virtual
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::canDropObjectEx(), and Gui::ViewProviderPythonFeatureImp::Rejected.
canDropObjects()
template<class ViewProviderT > virtual bool Gui::ViewProviderPythonFeatureT< ViewProviderT >::canDropObjects () const override virtual
Returns true if the view provider generally accepts dropping of objects.
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::canDropObjects(), and Gui::ViewProviderPythonFeatureImp::Rejected.
canRemoveChildrenFromRoot()
template<class ViewProviderT > virtual bool Gui::ViewProviderPythonFeatureT< ViewProviderT >::canRemoveChildrenFromRoot () const override virtual
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::canRemoveChildrenFromRoot(), and Gui::ViewProviderPythonFeatureImp::NotImplemented.
claimChildren()
template<class ViewProviderT > std::vector< App::DocumentObject * > Gui::ViewProviderPythonFeatureT< ViewProviderT >::claimChildren (void) const override
References Gui::ViewProviderPythonFeatureImp::claimChildren().
Referenced by femviewprovider.view_mesh_gmsh.VPMeshGmsh::onDelete(), femviewprovider.view_result_mechanical.VPResultMechanical::onDelete(), BOPTools.JoinFeatures.ViewProviderConnect::onDelete(), BOPTools.SplitFeatures.ViewProviderBooleanFragments::onDelete(), BOPTools.SplitFeatures.ViewProviderSlice::onDelete(), and BOPTools.SplitFeatures.ViewProviderXOR::onDelete().
doubleClicked()
template<class ViewProviderT > virtual bool Gui::ViewProviderPythonFeatureT< ViewProviderT >::doubleClicked (void) override protected virtual
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::doubleClicked(), and Gui::ViewProviderPythonFeatureImp::Rejected.
dragObject()
template<class ViewProviderT > virtual void Gui::ViewProviderPythonFeatureT< ViewProviderT >::dragObject (App::DocumentObject * obj) override virtual
Starts to drag the object.
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::dragObject(), and Gui::ViewProviderPythonFeatureImp::Rejected.
dropObject()
template<class ViewProviderT > virtual void Gui::ViewProviderPythonFeatureT< ViewProviderT >::dropObject (App::DocumentObject * obj) override virtual
If the dropped object type is accepted the object will be added as child.
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::dropObject(), and Gui::ViewProviderPythonFeatureImp::Rejected.
dropObjectEx()
template<class ViewProviderT > virtual std::string Gui::ViewProviderPythonFeatureT< ViewProviderT >::dropObjectEx (App::DocumentObject * obj, App::DocumentObject * owner, const char * subname, const std::vector< std::string > & elements) override virtual
Add an object with full qualified name to the view provider by drag and drop.
References Gui::ViewProviderPythonFeatureImp::dropObjectEx().
editProperty()
template<class ViewProviderT > virtual void Gui::ViewProviderPythonFeatureT< ViewProviderT >::editProperty (const char * propName) override protected virtual
References Gui::ViewProviderPythonFeatureImp::editProperty().
finishRestoring()
template<class ViewProviderT > virtual void Gui::ViewProviderPythonFeatureT< ViewProviderT >::finishRestoring () override virtual
References Gui::ViewProviderPythonFeatureImp::finishRestoring().
getBackRoot()
template<class ViewProviderT > virtual SoSeparator * Gui::ViewProviderPythonFeatureT< ViewProviderT >::getBackRoot (void) const override virtual
getDefaultDisplayMode()
template<class ViewProviderT > virtual const char * Gui::ViewProviderPythonFeatureT< ViewProviderT >::getDefaultDisplayMode () const override virtual
get the default display mode
References Gui::ViewProviderPythonFeatureImp::getDefaultDisplayMode().
getDetail()
template<class ViewProviderT > virtual SoDetail * Gui::ViewProviderPythonFeatureT< ViewProviderT >::getDetail (const char * name) const override virtual
References Gui::ViewProviderPythonFeatureImp::getDetail().
getDetailPath()
template<class ViewProviderT > virtual bool Gui::ViewProviderPythonFeatureT< ViewProviderT >::getDetailPath (const char * name, SoFullPath * path, bool append, SoDetail *& det) const override virtual
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::getDetailPath(), and Gui::ViewProviderPythonFeatureImp::NotImplemented.
getDisplayModes()
template<class ViewProviderT > virtual std::vector< std::string > Gui::ViewProviderPythonFeatureT< ViewProviderT >::getDisplayModes (void) const override virtual
returns a list of all possible modes
References Gui::ViewProviderPythonFeatureImp::getDisplayModes().
getDropPrefix()
template<class ViewProviderT > virtual std::string Gui::ViewProviderPythonFeatureT< ViewProviderT >::getDropPrefix () const override protected virtual
References Gui::ViewProviderPythonFeatureImp::getDropPrefix().
getElement()
template<class ViewProviderT > virtual std::string Gui::ViewProviderPythonFeatureT< ViewProviderT >::getElement (const SoDetail * det) const override virtual
References Gui::ViewProviderPythonFeatureImp::getElement().
getElementPicked()
template<class ViewProviderT > virtual bool Gui::ViewProviderPythonFeatureT< ViewProviderT >::getElementPicked (const SoPickedPoint * pp, std::string & subname) const override virtual
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::getElementPicked(), and Gui::ViewProviderPythonFeatureImp::NotImplemented.
getFrontRoot()
template<class ViewProviderT > virtual SoSeparator * Gui::ViewProviderPythonFeatureT< ViewProviderT >::getFrontRoot (void) const override virtual
getIcon()
template<class ViewProviderT > QIcon Gui::ViewProviderPythonFeatureT< ViewProviderT >::getIcon (void) const override
References Gui::ViewProviderPythonFeatureImp::getIcon().
Referenced by ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), and ArchSectionPlane.SectionPlaneTaskPanel::update().
getLinkedViewProvider()
template<class ViewProviderT > virtual ViewProviderDocumentObject * Gui::ViewProviderPythonFeatureT< ViewProviderT >::getLinkedViewProvider (std::string * subname = nullptr, bool recursive = false) const override protected virtual
References Gui::ViewProviderPythonFeatureImp::getLinkedViewProvider().
getPyObject()
template<class ViewProviderT > PyObject * Gui::ViewProviderPythonFeatureT< ViewProviderT >::getPyObject (void) override
getRoot()
template<class ViewProviderT > virtual SoSeparator * Gui::ViewProviderPythonFeatureT< ViewProviderT >::getRoot (void) const override virtual
getSelectionShape()
template<class ViewProviderT > virtual std::vector< Base::Vector3d > Gui::ViewProviderPythonFeatureT< ViewProviderT >::getSelectionShape (const char * Element) const override virtual
getTaskViewContent()
template<class ViewProviderT > virtual void Gui::ViewProviderPythonFeatureT< ViewProviderT >::getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > & c) const override virtual
isShow()
template<class ViewProviderT > virtual bool Gui::ViewProviderPythonFeatureT< ViewProviderT >::isShow (void) const override virtual
Returns true if the icon must always appear enabled in the tree view.
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::isShow(), and Gui::ViewProviderPythonFeatureImp::Rejected.
onChanged()
template<class ViewProviderT > virtual void Gui::ViewProviderPythonFeatureT< ViewProviderT >::onChanged (const App::Property * prop) override protected virtual
References Gui::ViewProviderPythonFeatureImp::attach(), Gui::ViewProviderPythonFeatureT< ViewProviderT >::canAddToSceneGraph(), Gui::ViewProviderT::getDocument(), App::PropertyPythonObject::getValue(), Gui::ViewProviderPythonFeatureImp::init(), Gui::isRestoring, Gui::ViewProviderPythonFeatureImp::onChanged(), and Gui::Document::toggleInSceneGraph().
Referenced by ArchStructure.CommandStructuralSystem::Activated(), draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSite.Compass::buildCoordinates(), draftobjects.wire.Wire::execute(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchPanel.ViewProviderPanelSheet::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), and draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData().
onDelete()
template<class ViewProviderT > virtual bool Gui::ViewProviderPythonFeatureT< ViewProviderT >::onDelete (const std::vector< std::string > & sub) override virtual
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::onDelete(), and Gui::ViewProviderPythonFeatureImp::Rejected.
operator=() [1/2]
template<class ViewProviderT > ViewProviderPythonFeatureT & Gui::ViewProviderPythonFeatureT< ViewProviderT >::operator= (const ViewProviderPythonFeatureT< ViewProviderT > &) delete
operator=() [2/2]
template<class ViewProviderT > ViewProviderPythonFeatureT & Gui::ViewProviderPythonFeatureT< ViewProviderT >::operator= (ViewProviderPythonFeatureT< ViewProviderT > &&) delete
replaceObject()
template<class ViewProviderT > virtual int Gui::ViewProviderPythonFeatureT< ViewProviderT >::replaceObject (App::DocumentObject * oldObj, App::DocumentObject * newObj) override protected virtual
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::Rejected, and Gui::ViewProviderPythonFeatureImp::replaceObject().
setDisplayMode()
template<class ViewProviderT > virtual void Gui::ViewProviderPythonFeatureT< ViewProviderT >::setDisplayMode (const char * ModeName) override virtual
set the display mode
References Gui::ViewProviderPythonFeatureImp::setDisplayMode().
setEdit()
template<class ViewProviderT > virtual bool Gui::ViewProviderPythonFeatureT< ViewProviderT >::setEdit (int ModNum) override protected virtual
is called by the document when the provider goes in edit mode
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::Rejected, and Gui::ViewProviderPythonFeatureImp::setEdit().
Referenced by ArchGrid.ViewProviderArchGrid::doubleClicked(), ArchReference.ViewProviderArchReference::doubleClicked(), draftviewproviders.view_dimension.ViewProviderDimensionBase::doubleClicked(), draftviewproviders.view_hatch.ViewProviderDraftHatch::doubleClicked(), draftviewproviders.view_text.ViewProviderText::doubleClicked(), PathScripts.PathPropertyBagGui.ViewProvider::doubleClicked(), PathScripts.PathSetupSheetGui.ViewProvider::doubleClicked(), PathScripts.PathToolBitGui.ViewProvider::doubleClicked(), Spreadsheet_legacy.ViewProviderSpreadsheet::doubleClicked(), ArchSchedule.CommandArchSchedule::IsActive(), PathScripts.PathIconViewProvider.ViewProvider::setupContextMenu(), PathScripts.PathJobGui.ViewProvider::setupContextMenu(), PathScripts.PathOpGui.ViewProvider::setupContextMenu(), and PathScripts.PathToolControllerGui.ViewProvider::setupContextMenu().
setEditViewer()
template<class ViewProviderT > virtual void Gui::ViewProviderPythonFeatureT< ViewProviderT >::setEditViewer (View3DInventorViewer * viewer, int ModNum) override protected virtual
References Gui::ViewProviderPythonFeatureImp::NotImplemented, Gui::ViewProviderPythonFeatureImp::setEditViewer(), and OfflineRenderingUtils::viewer().
setOverrideMode()
template<class ViewProviderT > virtual void Gui::ViewProviderPythonFeatureT< ViewProviderT >::setOverrideMode (const std::string & mode) override protected virtual
setupContextMenu()
template<class ViewProviderT > virtual void Gui::ViewProviderPythonFeatureT< ViewProviderT >::setupContextMenu (QMenu * menu, QObject * recipient, const char * member) override virtual
References Gui::ViewProviderPythonFeatureImp::setupContextMenu().
startRestoring()
template<class ViewProviderT > virtual void Gui::ViewProviderPythonFeatureT< ViewProviderT >::startRestoring () override virtual
References Gui::ViewProviderPythonFeatureImp::startRestoring().
unsetEdit()
template<class ViewProviderT > virtual void Gui::ViewProviderPythonFeatureT< ViewProviderT >::unsetEdit (int ModNum) override protected virtual
is called when you lose the edit mode
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::Rejected, and Gui::ViewProviderPythonFeatureImp::unsetEdit().
Referenced by PathScripts.PathJobGui.ViewProvider::uneditObject().
unsetEditViewer()
template<class ViewProviderT > virtual void Gui::ViewProviderPythonFeatureT< ViewProviderT >::unsetEditViewer (View3DInventorViewer * viewer) override protected virtual
References Gui::ViewProviderPythonFeatureImp::NotImplemented, Gui::ViewProviderPythonFeatureImp::unsetEditViewer(), and OfflineRenderingUtils::viewer().
updateData()
template<class ViewProviderT > virtual void Gui::ViewProviderPythonFeatureT< ViewProviderT >::updateData (const App::Property * prop) override virtual
References Gui::ViewProviderPythonFeatureImp::updateData().
Referenced by ArchStructure.CommandStructuralSystem::Activated(), PathScripts.PathJobDlg.JobCreate::exec_(), draftviewproviders.view_dimension.ViewProviderLinearDimension::onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension::onChanged(), draftviewproviders.view_wire.ViewProviderWire::onChanged(), PathScripts.PathOpGui.TaskPanelPage::pageUpdateData(), PathScripts.PathPropertyBagGui.TaskPanel::setupUi(), and PathScripts.PathSetupSheetGui.OpTaskPanel::setupUi().
useNewSelectionModel()
template<class ViewProviderT > virtual bool Gui::ViewProviderPythonFeatureT< ViewProviderT >::useNewSelectionModel (void) const override virtual
References Gui::ViewProviderPythonFeatureImp::Accepted, Gui::ViewProviderPythonFeatureImp::Rejected, and Gui::ViewProviderPythonFeatureImp::useNewSelectionModel().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ViewProviderPythonFeature.h