FreeCAD: Point Class Reference
Point Class Reference
#include <Point.h>
Public Member Functions
double dist (const Point &p) const
double length () const
double normalize ()
bool operator!= (const Point &p) const
double operator* (const Point &p) const
const Point operator* (double d) const
const Point operator+ (const Point &p) const
const Point operator- (const Point &p) const
Point operator- (void) const
const Point operator/ (double d) const
bool operator== (const Point &p) const
double operator^ (const Point &p) const
Point operator~ (void) const
Point ()
Point (const double *p)
Point (const Point &p0, const Point &p1)
Point (double X, double Y)
void Rotate (double angle)
void Rotate (double cosa, double sina)
void Transform (const geoff_geometry::Matrix &m)
Public Attributes
double x
double y
Static Public Attributes
static double tolerance = 0.001
Constructor & Destructor Documentation
Point() [1/4]
Point::Point ()
Referenced by operator*(), operator+(), operator-(), operator/(), and operator~().
Point() [2/4]
Point::Point (double X, double Y)
Point() [3/4]
Point::Point (const double * p)
Point() [4/4]
Point::Point (const Point & p0, const Point & p1)
Member Function Documentation
dist()
double Point::dist (const Point & p) const
References x, and y.
Referenced by CArc::AlmostALine(), CArea::ChangeStartToNearest(), Line::Dist(), Span::GetArea(), Span::GetBox(), GetCurveItem::GetCurve(), CArc::GetSegments(), Span::Length(), CArea::NearestPoint(), Span::NearestPoint(), CCurve::NearestPoint(), and CCurve::PointToPerim().
length()
double Point::length () const
Referenced by PathScripts.PathStock.StockFromBase::execute(), PathScripts.PathPocketShape.Extension::getSubLink(), PathScripts.PathPocketShape.Extension::getWire(), Span::MidPerim(), Mod.PartDesign.Scripts.FilletArc.Vector::norm(), and normalize().
normalize()
double Point::normalize ()
References length().
Referenced by Line::Dist(), PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart(), Span::IncludedAngle(), Span::MidPerim(), and CCurve::OffsetForward().
operator!=()
bool Point::operator!= (const Point & p) const
operator*() [1/2]
double Point::operator* (const Point & p) const
operator*() [2/2]
const Point Point::operator* (double d) const
References Point().
operator+()
const Point Point::operator+ (const Point & p) const
References Point().
operator-() [1/2]
const Point Point::operator- (const Point & p) const
References Point().
operator-() [2/2]
Point Point::operator- (void) const
References Point().
operator/()
const Point Point::operator/ (double d) const
References Point().
operator==()
bool Point::operator== (const Point & p) const
References tolerance.
operator^()
double Point::operator^ (const Point & p) const
operator~()
Point Point::operator~ (void) const
References Point().
Rotate() [1/2]
void Point::Rotate (double angle)
References Rotate().
Referenced by Rotate().
Rotate() [2/2]
void Point::Rotate (double cosa, double sina)
References y.
Referenced by CArc::MidParam(), and Span::MidParam().
Transform()
void Point::Transform (const geoff_geometry::Matrix & m)
Member Data Documentation
tolerance
double Point::tolerance = 0.001 static
Referenced by femtaskpanels.task_constraint_tie._TaskPanel::accept(), CArc::AlmostALine(), CArea::ChangeStartToNearest(), operator==(), CCurve::RemoveTinySpans(), and femtaskpanels.task_constraint_tie._TaskPanel::tolerance_changed().
x
double Point::x
Referenced by Mod.PartDesign.Scripts.FilletArc.Vector::add(), DraftGui.DraftToolBar::changeAngleValue(), DraftGui.DraftToolBar::changeXValue(), importSVG.svgHandler::characters(), CCurve::CheckForArc(), DraftGui.DraftToolBar::checkSpecialChars(), Circle::Circle(), PathScripts.PathInspect.GCodeEditorDialog::cleanup(), Mod.PartDesign.Scripts.FilletArc.Vector::cross(), dist(), PathScripts.PostUtils.GCodeEditorDialog::done(), Mod.PartDesign.Scripts.FilletArc.Vector::dot(), Span::GetArea(), CArc::GetSegments(), CArc::IncludedAngle(), CBox2D::Insert(), Mod.PartDesign.Scripts.FilletArc.Vector::length(), CBox2D::MaxX(), CBox2D::MinX(), Mod.PartDesign.Scripts.FilletArc.Vector::mult(), Mod.PartDesign.Scripts.FilletArc.Vector::norm(), CCurve::Offset(), PathScripts.PathDressupHoldingTags.Tag::originAt(), DraftGui.DraftToolBar::pointUi(), Part::GeomPoint::Save(), Part::Geom2dPoint::Save(), CArc::SetDirWithPoint(), Mod.PartDesign.Scripts.FilletArc.Vector::sub(), DraftGui.DraftToolBar::taskUi(), CCurve::UnFitArcs(), DraftGui.DraftToolBar::updateSnapper(), DraftGui.DraftToolBar::validatePoint(), CBox2D::Width(), and automotive_design.right_angular_wedge::wr1().
y
double Point::y
Referenced by Mod.PartDesign.Scripts.FilletArc.Vector::add(), DraftGui.DraftToolBar::changeAngleValue(), DraftGui.DraftToolBar::changeYValue(), importSVG.svgHandler::characters(), CCurve::CheckForArc(), DraftGui.DraftToolBar::checkSpecialChars(), Circle::Circle(), PathScripts.PathInspect.GCodeEditorDialog::cleanup(), Mod.PartDesign.Scripts.FilletArc.Vector::cross(), dist(), PathScripts.PostUtils.GCodeEditorDialog::done(), Mod.PartDesign.Scripts.FilletArc.Vector::dot(), Span::GetArea(), CArc::GetSegments(), CBox2D::Height(), CArc::IncludedAngle(), CBox2D::Insert(), Mod.PartDesign.Scripts.FilletArc.Vector::length(), CBox2D::MaxY(), CBox2D::MinY(), Mod.PartDesign.Scripts.FilletArc.Vector::mult(), Mod.PartDesign.Scripts.FilletArc.Vector::norm(), CCurve::Offset(), PathScripts.PathDressupHoldingTags.Tag::originAt(), DraftGui.DraftToolBar::pointUi(), Rotate(), Part::GeomPoint::Save(), Part::Geom2dPoint::Save(), CArc::SetDirWithPoint(), Mod.PartDesign.Scripts.FilletArc.Vector::sub(), DraftGui.DraftToolBar::taskUi(), CCurve::UnFitArcs(), DraftGui.DraftToolBar::updateSnapper(), and DraftGui.DraftToolBar::validatePoint().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Path/libarea/Point.h
Sources/FreeCAD/src/Mod/Path/libarea/Curve.cpp