FreeCAD: ReverseEngineeringGui::Segmentation Class Reference
ReverseEngineeringGui::Segmentation Class Reference
#include <Segmentation.h>
Public Member Functions
void accept ()
Segmentation (Mesh::Feature *mesh, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~Segmentation ()
Protected Member Functions
void changeEvent (QEvent *e)
Constructor & Destructor Documentation
Segmentation()
Segmentation::Segmentation (Mesh::Feature * mesh, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
~Segmentation()
Segmentation::~Segmentation ()
Member Function Documentation
accept()
void Segmentation::accept (void)
References App::Document::addObject(), MeshCore::Approximation::AddPoints(), App::Document::commitTransaction(), MeshCore::MeshCurvature::ComputePerVertex(), Base::Console(), Base::ConsoleSingleton::Error(), App::DocumentObjectWeakPtrT::expired(), MeshCore::MeshSegmentAlgorithm::FindSegments(), Mesh::PropertyMeshKernel::finishEditing(), MeshCore::PlaneFit::Fit(), App::DocumentObjectWeakPtrT::get(), App::Application::getActiveDocument(), App::GetApplication(), MeshCore::PlaneFit::GetBase(), MeshCore::MeshCurvature::GetCurvature(), MeshCore::MeshAlgorithm::GetFacetBorders(), MeshCore::MeshKernel::GetFacetPoints(), MeshCore::MeshAlgorithm::GetFacetsFlag(), App::DocumentObject::getNameInDocument(), MeshCore::PlaneFit::GetNormal(), MeshCore::MeshKernel::GetPoints(), App::PropertyString::getValue(), App::GroupExtension::Group, draftgeoutils.geometry::isPlanar, App::DocumentObject::Label, Part::FaceMakerCheese::makeFace(), Mesh::Feature::Mesh, App::Document::openTransaction(), App::GroupExtension::removeObjects(), MeshCore::MeshAlgorithm::ResetFacetsFlag(), MeshCore::MeshAlgorithm::SetFacetFlag(), App::PropertyString::setValue(), Part::PropertyPartShape::setValue(), App::PropertyLinkList::setValues(), Part::Feature::Shape, MeshCore::LaplaceSmoothing::Smooth(), Mesh::PropertyMeshKernel::startEditing(), Mesh::MeshObject::swap(), MeshCore::MeshFacet::TMP0, and Base::ConsoleSingleton::Warning().
Referenced by ReverseEngineeringGui::TaskSegmentation::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void Segmentation::changeEvent (QEvent * e) protected
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/ReverseEngineering/Gui/Segmentation.h
FreeCAD/src/Mod/ReverseEngineering/Gui/Segmentation.cpp