FreeCAD: Part::Geom2dLine Class Reference
Part::Geom2dLine Class Reference
#include <Geometry2d.h>
Public Member Functions
virtual Geometry2d * clone (void) const
returns a cloned object
Geom2dLine ()
Geom2dLine (const Base::Vector2d &Pos, const Base::Vector2d &Dir)
Geom2dLine (const Handle(Geom2d_Line)&)
Base::Vector2d getDir (void) const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Base::Vector2d getPos (void) const
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
const Handle (Geom2d_Geometry) &handle() const
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
void setLine (const Base::Vector2d &Pos, const Base::Vector2d &Dir)
virtual ~Geom2dLine ()
Public Member Functions inherited from Part::Geom2dCurve
bool closestParameter (const Base::Vector2d &point, double &u) const
bool closestParameterToBasicCurve (const Base::Vector2d &point, double &u) const
Base::Vector2d firstDerivativeAtParameter (double u) const
Geom2dCurve ()
bool normal (double u, gp_Dir2d &dir) const
Base::Vector2d pointAtParameter (double u) const
Base::Vector2d secondDerivativeAtParameter (double u) const
bool tangent (double u, gp_Dir2d &) const
virtual TopoDS_Shape toShape () const
virtual ~Geom2dCurve ()
Public Member Functions inherited from Part::Geometry2d
virtual Geometry2d * clone (void) const =0
returns a cloned object
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual const Handle (Geom2d_Geometry) &handle() const =0
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
virtual TopoDS_Shape toShape () const =0
virtual ~Geometry2d ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Protected Member Functions inherited from Part::Geometry2d
Geometry2d ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
Geom2dLine() [1/3]
Geom2dLine::Geom2dLine ()
Geom2dLine() [2/3]
Geom2dLine::Geom2dLine (const Handle(Geom2d_Line)& l)
References Handle().
Geom2dLine() [3/3]
Geom2dLine::Geom2dLine (const Base::Vector2d & Pos, const Base::Vector2d & Dir)
References Base::Vector2d::x, and Base::Vector2d::y.
~Geom2dLine()
Geom2dLine::~Geom2dLine () virtual
Member Function Documentation
clone()
virtual Geometry2d * Part::Geom2dLine::clone (void) const virtual
returns a cloned object
Implements Part::Geometry2d.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.CommandStructuralSystem::Activated(), ArchComponent.Component::execute(), ArchCurtainWall.CurtainWall::execute(), ArchTruss.Truss::execute(), getPyObject(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated(), and PathTests.TestPathHelix.TestPathHelix::test04().
getDir()
Base::Vector2d Geom2dLine::getDir (void) const
getMemSize()
virtual unsigned int Part::Geom2dLine::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Part::Geometry2d.
getPos()
Base::Vector2d Geom2dLine::getPos (void) const
getPyObject()
PyObject * Geom2dLine::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
References clone().
Handle()
const Part::Geom2dLine::Handle (Geom2d_Geometry) const & virtual
Implements Part::Geometry2d.
Referenced by Geom2dLine().
Restore()
virtual void Part::Geom2dLine::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Part::Geometry2d.
Save()
virtual void Part::Geom2dLine::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from Part::Geometry2d.
setLine()
void Geom2dLine::setLine (const Base::Vector2d & Pos, const Base::Vector2d & Dir)
References Base::Vector2d::x, and Base::Vector2d::y.
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/App/Geometry2d.h
FreeCAD/src/Mod/Part/App/Geometry2d.cpp