FreeCAD: MeshCore::MeshDistancePlanarSegment Class Reference
MeshCore::MeshDistancePlanarSegment Class Reference
#include <Segmentation.h>
Public Member Functions
void AddFacet (const MeshFacet &rclFacet)
const char * GetType () const
void Initialize (FacetIndex)
MeshDistancePlanarSegment (const MeshKernel &mesh, unsigned long minFacets, float tol)
bool TestFacet (const MeshFacet &rclFacet) const
virtual ~MeshDistancePlanarSegment ()
Public Member Functions inherited from MeshCore::MeshDistanceSurfaceSegment
MeshDistanceSurfaceSegment (const MeshKernel &mesh, unsigned long minFacets, float tol)
Public Member Functions inherited from MeshCore::MeshSurfaceSegment
virtual void AddFacet (const MeshFacet &rclFacet)
void AddSegment (const std::vector< FacetIndex > &)
MeshSegment FindSegment (FacetIndex) const
const std::vector< MeshSegment > & GetSegments () const
virtual const char * GetType () const =0
virtual void Initialize (FacetIndex)
MeshSurfaceSegment (unsigned long minFacets)
virtual bool TestFacet (const MeshFacet &rclFacet) const =0
virtual bool TestInitialFacet (FacetIndex) const
virtual ~MeshSurfaceSegment ()
Protected Attributes
Base::Vector3f basepoint
PlaneFit * fitter
Base::Vector3f normal
Protected Attributes inherited from MeshCore::MeshDistanceSurfaceSegment
const MeshKernel & kernel
float tolerance
Protected Attributes inherited from MeshCore::MeshSurfaceSegment
unsigned long minFacets
std::vector< MeshSegment > segments
Constructor & Destructor Documentation
MeshDistancePlanarSegment()
MeshDistancePlanarSegment::MeshDistancePlanarSegment (const MeshKernel & mesh, unsigned long minFacets, float tol)
~MeshDistancePlanarSegment()
MeshDistancePlanarSegment::~MeshDistancePlanarSegment () virtual
References fitter.
Member Function Documentation
AddFacet()
void MeshDistancePlanarSegment::AddFacet (const MeshFacet & rclFacet) virtual
Reimplemented from MeshCore::MeshSurfaceSegment.
References MeshCore::Approximation::AddPoint(), fitter, MeshCore::MeshKernel::GetFacet(), and MeshCore::MeshDistanceSurfaceSegment::kernel.
GetType()
const char * MeshCore::MeshDistancePlanarSegment::GetType (void) const virtual
Implements MeshCore::MeshSurfaceSegment.
Initialize()
void MeshDistancePlanarSegment::Initialize (FacetIndex index) virtual
Reimplemented from MeshCore::MeshSurfaceSegment.
References MeshCore::Approximation::AddPoint(), basepoint, MeshCore::Approximation::Clear(), fitter, MeshCore::MeshKernel::GetFacet(), MeshCore::MeshDistanceSurfaceSegment::kernel, and normal.
TestFacet()
bool MeshDistancePlanarSegment::TestFacet (const MeshFacet & rclFacet) const virtual
Implements MeshCore::MeshSurfaceSegment.
References MeshCore::Approximation::Done(), MeshCore::PlaneFit::Fit(), fitter, MeshCore::PlaneFit::GetDistanceToPlane(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshDistanceSurfaceSegment::kernel, and MeshCore::MeshDistanceSurfaceSegment::tolerance.
Member Data Documentation
basepoint
Base::Vector3f MeshCore::MeshDistancePlanarSegment::basepoint protected
Referenced by draftguitools.gui_snapper.Snapper::constrain(), Initialize(), and draftguitools.gui_snapper.Snapper::unconstrain().
fitter
PlaneFit* MeshCore::MeshDistancePlanarSegment::fitter protected
Referenced by AddFacet(), Initialize(), TestFacet(), and ~MeshDistancePlanarSegment().
normal
Base::Vector3f MeshCore::MeshDistancePlanarSegment::normal protected
Referenced by draftguitools.gui_trackers.arcTracker::getAngle(), draftguitools.gui_trackers.arcTracker::getDeviation(), Initialize(), draftguitools.gui_trackers.arcTracker::recompute(), and draftguitools.gui_trackers.arcTracker::setBy3Points().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/Core/Segmentation.h
FreeCAD/src/Mod/Mesh/App/Core/Segmentation.cpp