FreeCAD: MeshGui::SoFCMeshObjectNode Class Reference
MeshGui::SoFCMeshObjectNode Class Reference
#include <SoFCMeshObject.h>
Public Member Functions
virtual void callback (SoCallbackAction *action)
virtual void doAction (SoAction *action)
virtual void getBoundingBox (SoGetBoundingBoxAction *action)
virtual void getPrimitiveCount (SoGetPrimitiveCountAction *action)
virtual void GLRender (SoGLRenderAction *action)
virtual void pick (SoPickAction *action)
SoFCMeshObjectNode (void)
Static Public Member Functions
static void initClass (void)
Public Attributes
SoSFMeshObject mesh
Protected Member Functions
virtual ~SoFCMeshObjectNode ()
Constructor & Destructor Documentation
SoFCMeshObjectNode()
SoFCMeshObjectNode::SoFCMeshObjectNode (void)
Constructor.
~SoFCMeshObjectNode()
SoFCMeshObjectNode::~SoFCMeshObjectNode () protected virtual
Destructor.
Member Function Documentation
callback()
void SoFCMeshObjectNode::callback (SoCallbackAction * action) virtual
References doAction().
Referenced by qtunittest.GUITestResult::addError(), Mod.Test.unittestgui.GUITestResult::addError(), qtunittest.GUITestResult::addFailure(), Mod.Test.unittestgui.GUITestResult::addFailure(), ArchStructure.StructSelectionObserver::addSelection(), qtunittest.GUITestResult::startTest(), Mod.Test.unittestgui.GUITestResult::startTest(), qtunittest.GUITestResult::stopTest(), and Mod.Test.unittestgui.GUITestResult::stopTest().
doAction()
void SoFCMeshObjectNode::doAction (SoAction * action) virtual
References mesh, and MeshGui::SoFCMeshObjectElement::set().
Referenced by callback(), getBoundingBox(), getPrimitiveCount(), GLRender(), and pick().
getBoundingBox()
void SoFCMeshObjectNode::getBoundingBox (SoGetBoundingBoxAction * action) virtual
References doAction().
getPrimitiveCount()
void SoFCMeshObjectNode::getPrimitiveCount (SoGetPrimitiveCountAction * action) virtual
References doAction().
GLRender()
void SoFCMeshObjectNode::GLRender (SoGLRenderAction * action) virtual
References doAction().
initClass()
void SoFCMeshObjectNode::initClass (void) static
pick()
void SoFCMeshObjectNode::pick (SoPickAction * action) virtual
References doAction().
Member Data Documentation
mesh
SoSFMeshObject MeshGui::SoFCMeshObjectNode::mesh
Referenced by femtools.ccxtools.FemToolsCcx::check_prerequisites(), doAction(), femtools.ccxtools.FemToolsCcx::has_no_material_assigned(), femtools.ccxtools.FemToolsCcx::has_nonpositive_jacobians(), femsolver.fenics.fenics_tools.XDMFReader::readCellExpression(), femsolver.fenics.fenics_tools.XDMFReader::readFacetFunction(), femsolver.fenics.fenics_tools.XDMFReader::readMesh(), femsolver.fenics.fenics_tools.XDMFReader::resetMesh(), MengerSponge.MengerThread::run(), MeshTestsApp.MeshSplitTestCases::testSplitFacetOnOneEdge(), MeshTestsApp.MeshSplitTestCases::testSplitFacetOnTwoEdges_01(), MeshTestsApp.MeshSplitTestCases::testSplitFacetOnTwoEdges_02(), MeshTestsApp.MeshSplitTestCases::testSplitFacetOnTwoEdges_10(), MeshTestsApp.MeshSplitTestCases::testSplitFacetOnTwoEdges_12(), MeshTestsApp.MeshSplitTestCases::testSplitFacetOnTwoEdges_20(), MeshTestsApp.MeshSplitTestCases::testSplitFacetOnTwoEdges_21(), MeshTestsApp.MeshSplitTestCases::testSplitFacetOnTwoEdges_5teps(), MeshGui::ViewProviderMeshObject::updateData(), MeshGui::ViewProviderMeshFaceSet::updateData(), and femtools.ccxtools.FemToolsCcx::write_inp_file().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCMeshObject.h
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCMeshObject.cpp