FreeCAD: Gui::Dialog::SceneModel Class Reference
Gui::Dialog::SceneModel Class Reference
Stores data representing scenegraph nodes.
#include <SceneInspector.h>
Public Member Functions
int columnCount (const QModelIndex &parent=QModelIndex()) const
Tree structure: column count is 1.
Qt::ItemFlags flags (const QModelIndex &index) const
returns standard parent's flags
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
returns empty QVariant, unless orientation == Qt::Horizontal, role == Qt::DisplayRole and section == 0 where it returns "Inventor Tree"
SceneModel (QObject *parent)
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
header data not used: returns false
void setNode (SoNode *node)
insert the first node in tree
void setNodeNames (const QHash< SoNode *, QString > &names)
set names per node
virtual ~SceneModel ()
Detailed Description
Stores data representing scenegraph nodes.
Constructor & Destructor Documentation
SceneModel()
SceneModel::SceneModel (QObject * parent)
~SceneModel()
SceneModel::~SceneModel () virtual
Member Function Documentation
columnCount()
int SceneModel::columnCount (const QModelIndex & parent = QModelIndex()) const
Tree structure: column count is 1.
flags()
Qt::ItemFlags SceneModel::flags (const QModelIndex & index) const
returns standard parent's flags
headerData()
QVariant SceneModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
returns empty QVariant, unless orientation == Qt::Horizontal, role == Qt::DisplayRole and section == 0 where it returns "Inventor Tree"
setHeaderData()
bool SceneModel::setHeaderData (int section, Qt::Orientation orientation, const QVariant & value, int role = Qt::EditRole)
header data not used: returns false
Referenced by setNode().
setNode()
void SceneModel::setNode (SoNode * node)
insert the first node in tree
References setHeaderData().
Referenced by Gui::Dialog::DlgInspector::setNode().
setNodeNames()
void SceneModel::setNodeNames (const QHash< SoNode *, QString > & names)
set names per node
Referenced by Gui::Dialog::DlgInspector::setNodeNames().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SceneInspector.h
Sources/FreeCAD/src/Gui/SceneInspector.cpp