FreeCAD: PlmXmlParser Namespace Reference
PlmXmlParser Namespace Reference
Functions
def addAssembly (asmElement)
def addPart (partElement)
def addReference (refElement)
def insert (filename, docname)
def main ()
def open (fileName)
def parse (fileName)
def ParseUserData (element)
def resolveRefs ()
Variables
FreeCAD_Doc = None
list FreeCAD_ObjList = []
bool FreeCAD_On = False
Function Documentation
addAssembly()
def PlmXmlParser.addAssembly (asmElement)
References ParseUserData().
Referenced by parse().
addPart()
def PlmXmlParser.addPart (partElement)
References ParseUserData().
Referenced by parse().
addReference()
def PlmXmlParser.addReference (refElement)
References ParseUserData().
Referenced by parse().
insert()
def PlmXmlParser.insert (filename, docname)
called when freecad imports an PlmXml file
References parse(), and resolveRefs().
main()
def PlmXmlParser.main ()
References parse().
Referenced by parse().
open()
def PlmXmlParser.open (fileName)
called when freecad opens an PlmXml file
References parse(), and resolveRefs().
parse()
def PlmXmlParser.parse (fileName)
References addAssembly(), addPart(), addReference(), main(), and ParseUserData().
Referenced by insert(), main(), and open().
ParseUserData()
def PlmXmlParser.ParseUserData (element)
Referenced by addAssembly(), addPart(), addReference(), and parse().
resolveRefs()
def PlmXmlParser.resolveRefs ()
Referenced by insert(), and open().
Variable Documentation
FreeCAD_Doc
PlmXmlParser.FreeCAD_Doc = None
FreeCAD_ObjList
list PlmXmlParser.FreeCAD_ObjList = []
FreeCAD_On
bool PlmXmlParser.FreeCAD_On = False