FreeCAD: Ui_TaskActiveView Class Reference
Ui_TaskActiveView Class Reference
#include <ui_TaskActiveView.h>
Public Member Functions
void retranslateUi (QWidget *TaskActiveView)
void setupUi (QWidget *TaskActiveView)
Public Attributes
QCheckBox * cbbg
QComboBox * cbMode
Gui::ColorButton * ccBgColor
QGridLayout * gridLayout
QSpacerItem * horizontalSpacer
QLabel * label
QLabel * label_2
QLabel * label_3
QLabel * label_4
QLabel * label_5
Gui::QuantitySpinBox * qsbBorder
Gui::QuantitySpinBox * qsbHeight
Gui::QuantitySpinBox * qsbWeight
Gui::QuantitySpinBox * qsbWidth
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void Ui_TaskActiveView::retranslateUi (QWidget * TaskActiveView)
References cbbg, cbMode, ccBgColor, label_2, label_3, label_4, label_5, qsbBorder, qsbHeight, qsbWeight, qsbWidth, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Ui_TaskActiveView::setupUi (QWidget * TaskActiveView)
References cbbg, cbMode, ccBgColor, draftgeoutils.intersections::connect(), gridLayout, horizontalSpacer, label_2, label_3, label_4, label_5, qsbBorder, qsbHeight, qsbWeight, qsbWidth, retranslateUi(), Gui::QuantitySpinBox::setMinimum(), Gui::QuantitySpinBox::setSingleStep(), Gui::QuantitySpinBox::setValue(), and verticalLayout.
Member Data Documentation
cbbg
QCheckBox* Ui_TaskActiveView::cbbg
Referenced by retranslateUi(), and setupUi().
cbMode
QComboBox* Ui_TaskActiveView::cbMode
Referenced by retranslateUi(), and setupUi().
ccBgColor
Gui::ColorButton* Ui_TaskActiveView::ccBgColor
Referenced by retranslateUi(), and setupUi().
gridLayout
QGridLayout* Ui_TaskActiveView::gridLayout
Referenced by setupUi().
horizontalSpacer
QSpacerItem* Ui_TaskActiveView::horizontalSpacer
Referenced by setupUi().
label
QLabel* Ui_TaskActiveView::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
label_2
QLabel* Ui_TaskActiveView::label_2
Referenced by retranslateUi(), and setupUi().
label_3
QLabel* Ui_TaskActiveView::label_3
Referenced by retranslateUi(), and setupUi().
label_4
QLabel* Ui_TaskActiveView::label_4
Referenced by retranslateUi(), and setupUi().
label_5
QLabel* Ui_TaskActiveView::label_5
Referenced by retranslateUi(), and setupUi().
qsbBorder
Gui::QuantitySpinBox* Ui_TaskActiveView::qsbBorder
Referenced by retranslateUi(), and setupUi().
qsbHeight
Gui::QuantitySpinBox* Ui_TaskActiveView::qsbHeight
Referenced by retranslateUi(), and setupUi().
qsbWeight
Gui::QuantitySpinBox* Ui_TaskActiveView::qsbWeight
Referenced by retranslateUi(), and setupUi().
qsbWidth
Gui::QuantitySpinBox* Ui_TaskActiveView::qsbWidth
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* Ui_TaskActiveView::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/TechDraw/Gui/ui_TaskActiveView.h