FreeCAD: Points::E57Reader Class Reference
Points::E57Reader Class Reference
#include <PointsAlgos.h>
Public Member Functions
E57Reader (const bool &Color, const bool &State, const float &Distance)
void read (const std::string &filename)
~E57Reader ()
Public Member Functions inherited from Points::Reader
void clear ()
const std::vector< App::Color > & getColors () const
int getHeight () const
const std::vector< float > & getIntensities () const
const std::vector< Base::Vector3f > & getNormals () const
const PointKernel & getPoints () const
int getWidth () const
bool hasColors () const
bool hasIntensities () const
bool hasNormals () const
bool hasProperties () const
bool isStructured () const
virtual void read (const std::string &filename)=0
Reader ()
virtual ~Reader ()
Protected Attributes
bool checkState
float minDistance
bool useColor
Protected Attributes inherited from Points::Reader
std::vector< App::Color > colors
int height
std::vector< float > intensity
std::vector< Base::Vector3f > normals
PointKernel points
int width
Constructor & Destructor Documentation
E57Reader()
E57Reader::E57Reader (const bool & Color, const bool & State, const float & Distance)
References checkState, minDistance, and useColor.
~E57Reader()
E57Reader::~E57Reader ()
Member Function Documentation
read()
void E57Reader::read (const std::string & filename) virtual
Implements Points::Reader.
References checkState, e57::VectorNode::childCount(), Points::Reader::colors, Base::Console(), Base::Distance(), e57::E57_FLOAT, e57::E57_INTEGER, e57::E57_SCALED_INTEGER, Base::ConsoleSingleton::Error(), e57::StructureNode::get(), e57::VectorNode::get(), Points::Reader::intensity, e57::StructureNode::isDefined(), minDistance, e57::CompressedVectorNode::prototype(), App::Color::r, e57::CompressedVectorReader::read(), e57::CompressedVectorNode::reader(), e57::ImageFile::root(), useColor, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by gzip_utf8.GzipFile::readline(), and gzip_utf8.GzipFile::seek().
Member Data Documentation
checkState
bool Points::E57Reader::checkState protected
Referenced by E57Reader(), and read().
minDistance
float Points::E57Reader::minDistance protected
Referenced by E57Reader(), and read().
useColor
bool Points::E57Reader::useColor protected
Referenced by E57Reader(), and read().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Points/App/PointsAlgos.h
FreeCAD/src/Mod/Points/App/PointsAlgos.cpp