FreeCAD: SMESH::Controls::BelongToGeom Class Reference
SMESH::Controls::BelongToGeom Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
BelongToGeom ()
const SMESHDS_Mesh * GetMeshDS () const
TopoDS_Shape GetShape ()
double GetTolerance ()
virtual SMDSAbs_ElementType GetType () const
virtual bool IsSatisfy (long theElementId)
virtual void SetGeom (const TopoDS_Shape &theShape)
virtual void SetMesh (const SMDS_Mesh *theMesh)
void SetTolerance (double)
virtual void SetType (SMDSAbs_ElementType theType)
virtual SMDSAbs_ElementType GetType () const =0
virtual bool IsSatisfy (long theElementId)=0
Public Member Functions inherited from SMESH::Controls::Functor
virtual SMDSAbs_ElementType GetType () const =0
virtual void SetMesh (const SMDS_Mesh *theMesh)=0
virtual ~Functor ()
Constructor & Destructor Documentation
BelongToGeom()
BelongToGeom::BelongToGeom ()
Member Function Documentation
GetMeshDS()
const SMESHDS_Mesh * BelongToGeom::GetMeshDS () const
GetShape()
TopoDS_Shape BelongToGeom::GetShape ()
GetTolerance()
double BelongToGeom::GetTolerance ()
GetType()
SMDSAbs_ElementType BelongToGeom::GetType () const virtual
Implements SMESH::Controls::Predicate.
IsSatisfy()
bool BelongToGeom::IsSatisfy (long theElementId) virtual
Implements SMESH::Controls::Predicate.
References SMDS_Mesh::FindElement(), SMDS_Mesh::FindNode(), SMDS_MeshNode::GetPosition(), SMDS_MeshElement::getshapeId(), SMDS_MeshElement::GetType(), and SMDS_Position::GetTypeOfPosition().
SetGeom()
void BelongToGeom::SetGeom (const TopoDS_Shape & theShape) virtual
SetMesh()
void BelongToGeom::SetMesh (const SMDS_Mesh * theMesh) virtual
Implements SMESH::Controls::Functor.
SetTolerance()
void BelongToGeom::SetTolerance (double theTolerance)
SetType()
void BelongToGeom::SetType (SMDSAbs_ElementType theType) virtual
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp