FreeCAD: Gui::AbstractMouseSelection Class Reference
Gui::AbstractMouseSelection Class Reference abstract
The mouse selection base class In derived classes you must implement the methods initialize() and terminate() For all drawing stuff you just have to reimplement the draw() method.
#include <MouseSelection.h>
Public Types
enum {
Continue =0 , Restart =1 , Finish =2 , Cancel =3 ,
Ignore =4
}
Public Member Functions
AbstractMouseSelection ()
const std::vector< SbVec2s > & getPositions () const
void grabMouseModel (Gui::View3DInventorViewer *)
virtual void initialize ()=0
implement this in derived classes
void redraw ()
void releaseMouseModel (void)
SelectionRole selectedRole () const
virtual void terminate ()=0
implement this in derived classes
virtual ~AbstractMouseSelection (void)
Mouse events
QCursor m_cPrevCursor
int m_iXold
int m_iYold
int m_iXnew
int m_iYnew
SelectionRole m_selectedRole
int handleEvent (const SoEvent *const ev, const SbViewportRegion &vp)
virtual int mouseButtonEvent (const SoMouseButtonEvent *const, const QPoint &)
virtual int locationEvent (const SoLocation2Event *const, const QPoint &)
virtual int keyboardEvent (const SoKeyboardEvent *const)
virtual void draw ()
drawing stuff
Detailed Description
The mouse selection base class In derived classes you must implement the methods initialize() and terminate() For all drawing stuff you just have to reimplement the draw() method.
In general you need not to do anything else.
Author
Werner Mayer and Jürgen Riegel
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Continue
Restart
Finish
Cancel
Ignore
Constructor & Destructor Documentation
AbstractMouseSelection()
AbstractMouseSelection::AbstractMouseSelection ()
References m_iXnew, m_iXold, m_iYnew, m_iYold, and m_selectedRole.
~AbstractMouseSelection()
virtual Gui::AbstractMouseSelection::~AbstractMouseSelection (void) virtual
Member Function Documentation
draw()
virtual void Gui::AbstractMouseSelection::draw () protected virtual
drawing stuff
Reimplemented in SandboxGui::DrawingPlane, Gui::RubberbandSelection, and Gui::PolyPickerSelection.
getPositions()
const std::vector<SbVec2s>& Gui::AbstractMouseSelection::getPositions () const
Referenced by Gui::PolyPickerSelection::popupMenu(), Gui::PolyClipSelection::popupMenu(), Gui::FreehandSelection::popupMenu(), and Gui::NavigationStyle::processEvent().
grabMouseModel()
void AbstractMouseSelection::grabMouseModel (Gui::View3DInventorViewer * viewer)
References initialize(), m_cPrevCursor, and OfflineRenderingUtils::viewer().
Referenced by Gui::NavigationStyle::startSelection().
handleEvent()
int AbstractMouseSelection::handleEvent (const SoEvent *const ev, const SbViewportRegion & vp)
References Continue, keyboardEvent(), locationEvent(), mouseButtonEvent(), and Restart.
Referenced by Gui::NavigationStyle::processEvent().
initialize()
virtual void Gui::AbstractMouseSelection::initialize () pure virtual
implement this in derived classes
Implemented in SandboxGui::DrawingPlane, Gui::RubberbandSelection, and Gui::PolyPickerSelection.
Referenced by grabMouseModel().
keyboardEvent()
virtual int Gui::AbstractMouseSelection::keyboardEvent (const SoKeyboardEvent * const) protected virtual
Reimplemented in SandboxGui::DrawingPlane, Gui::RubberbandSelection, and Gui::PolyPickerSelection.
Referenced by handleEvent().
locationEvent()
virtual int Gui::AbstractMouseSelection::locationEvent (const SoLocation2Event * const , const QPoint &) protected virtual
Reimplemented in SandboxGui::DrawingPlane, Gui::RubberbandSelection, Gui::FreehandSelection, and Gui::PolyPickerSelection.
Referenced by handleEvent().
mouseButtonEvent()
virtual int Gui::AbstractMouseSelection::mouseButtonEvent (const SoMouseButtonEvent * const , const QPoint &) protected virtual
Reimplemented in SandboxGui::DrawingPlane, Gui::RubberbandSelection, Gui::FreehandSelection, and Gui::PolyPickerSelection.
Referenced by handleEvent().
redraw()
void AbstractMouseSelection::redraw ()
Referenced by Gui::NavigationStyle::redraw(), and draftguitools.gui_trimex.Trimex::trimObject().
releaseMouseModel()
void AbstractMouseSelection::releaseMouseModel (void)
References m_cPrevCursor, and terminate().
Referenced by Gui::PolyPickerSelection::mouseButtonEvent(), Gui::FreehandSelection::mouseButtonEvent(), Gui::RubberbandSelection::mouseButtonEvent(), and Gui::NavigationStyle::stopSelection().
selectedRole()
SelectionRole Gui::AbstractMouseSelection::selectedRole () const
Referenced by Gui::NavigationStyle::processEvent().
terminate()
virtual void Gui::AbstractMouseSelection::terminate () pure virtual
implement this in derived classes
Implemented in SandboxGui::DrawingPlane, Gui::BoxZoomSelection, Gui::RubberbandSelection, and Gui::PolyPickerSelection.
Referenced by releaseMouseModel().
Member Data Documentation
m_cPrevCursor
QCursor Gui::AbstractMouseSelection::m_cPrevCursor protected
Referenced by grabMouseModel(), Gui::PolyPickerSelection::mouseButtonEvent(), Gui::FreehandSelection::mouseButtonEvent(), and releaseMouseModel().
m_iXnew
int Gui::AbstractMouseSelection::m_iXnew protected
Referenced by AbstractMouseSelection(), Gui::PolyPickerSelection::locationEvent(), Gui::FreehandSelection::locationEvent(), Gui::RubberbandSelection::locationEvent(), Gui::PolyPickerSelection::mouseButtonEvent(), Gui::FreehandSelection::mouseButtonEvent(), Gui::RubberbandSelection::mouseButtonEvent(), and Gui::BoxZoomSelection::terminate().
m_iXold
int Gui::AbstractMouseSelection::m_iXold protected
Referenced by AbstractMouseSelection(), Gui::FreehandSelection::locationEvent(), Gui::RubberbandSelection::locationEvent(), Gui::PolyPickerSelection::mouseButtonEvent(), Gui::FreehandSelection::mouseButtonEvent(), Gui::RubberbandSelection::mouseButtonEvent(), and Gui::BoxZoomSelection::terminate().
m_iYnew
int Gui::AbstractMouseSelection::m_iYnew protected
Referenced by AbstractMouseSelection(), Gui::PolyPickerSelection::locationEvent(), Gui::FreehandSelection::locationEvent(), Gui::RubberbandSelection::locationEvent(), Gui::PolyPickerSelection::mouseButtonEvent(), Gui::FreehandSelection::mouseButtonEvent(), Gui::RubberbandSelection::mouseButtonEvent(), and Gui::BoxZoomSelection::terminate().
m_iYold
int Gui::AbstractMouseSelection::m_iYold protected
Referenced by AbstractMouseSelection(), Gui::FreehandSelection::locationEvent(), Gui::RubberbandSelection::locationEvent(), Gui::PolyPickerSelection::mouseButtonEvent(), Gui::FreehandSelection::mouseButtonEvent(), Gui::RubberbandSelection::mouseButtonEvent(), and Gui::BoxZoomSelection::terminate().
m_selectedRole
SelectionRole Gui::AbstractMouseSelection::m_selectedRole protected
Referenced by AbstractMouseSelection(), and Gui::PolyClipSelection::popupMenu().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/MouseSelection.h
Sources/FreeCAD/src/Gui/MouseSelection.cpp