FreeCAD: ModelRefine::FaceTypedBSpline Class Reference
ModelRefine::FaceTypedBSpline Class Reference
#include <modelRefine.h>
Public Member Functions
virtual TopoDS_Face buildFace (const FaceVectorType &faces) const
virtual GeomAbs_SurfaceType getType () const
virtual bool isEqual (const TopoDS_Face &faceOne, const TopoDS_Face &faceTwo) const
virtual TopoDS_Face buildFace (const FaceVectorType &faces) const =0
virtual GeomAbs_SurfaceType getType () const =0
virtual bool isEqual (const TopoDS_Face &faceOne, const TopoDS_Face &faceTwo) const =0
Friends
FaceTypedBSpline & getBSplineObject ()
Additional Inherited Members
Static Public Member Functions inherited from ModelRefine::FaceTypedBase
static GeomAbs_SurfaceType getFaceType (const TopoDS_Face &faceIn)
Protected Member Functions inherited from ModelRefine::FaceTypedBase
virtual void boundarySplit (const FaceVectorType &facesIn, std::vector< EdgeVectorType > &boundariesOut) const
FaceTypedBase (const GeomAbs_SurfaceType &typeIn)
Protected Attributes inherited from ModelRefine::FaceTypedBase
GeomAbs_SurfaceType surfaceType
Member Function Documentation
buildFace()
TopoDS_Face FaceTypedBSpline::buildFace (const FaceVectorType & faces) const virtual
Implements ModelRefine::FaceTypedBase.
References ModelRefine::FaceTypedBase::boundarySplit().
getType()
GeomAbs_SurfaceType FaceTypedBSpline::getType (void) const virtual
Implements ModelRefine::FaceTypedBase.
Referenced by PathScripts.PathToolEdit.ToolEditor::updateToolType(), and PathScripts.PathToolEdit.ToolEditor::updateUI().
isEqual()
bool FaceTypedBSpline::isEqual (const TopoDS_Face & faceOne, const TopoDS_Face & faceTwo) const virtual
Implements ModelRefine::FaceTypedBase.
References Base::Console(), and Base::ConsoleSingleton::Message().
Friends And Related Function Documentation
getBSplineObject
FaceTypedBSpline & getBSplineObject () friend
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/App/modelRefine.h
FreeCAD/src/Mod/Part/App/modelRefine.cpp