FreeCAD: Gui::Rubberband Class Reference
Gui::Rubberband Class Reference
#include <GLPainter.h>
Public Member Functions
bool isWorking ()
void paintGL ()
Rubberband ()
Rubberband (View3DInventorViewer *v)
void setColor (float r, float g, float b, float a)
void setCoords (int x1, int y1, int x2, int y2)
void setLineStipple (bool on)
void setViewer (View3DInventorViewer *v)
void setWorking (bool on)
~Rubberband ()
Public Member Functions inherited from Gui::GLGraphicsItem
GLGraphicsItem ()
virtual void paintGL ()=0
virtual ~GLGraphicsItem ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
Rubberband() [1/2]
Rubberband::Rubberband (View3DInventorViewer * v)
Rubberband() [2/2]
Rubberband::Rubberband ()
~Rubberband()
Rubberband::~Rubberband ()
Member Function Documentation
isWorking()
bool Gui::Rubberband::isWorking ()
paintGL()
void Rubberband::paintGL () virtual
Implements Gui::GLGraphicsItem.
setColor()
void Rubberband::setColor (float r, float g, float b, float a)
Referenced by Gui::RectangleSelection::RectangleSelection(), Gui::RubberbandSelection::RubberbandSelection(), and Gui::RubberbandSelection::setColor().
setCoords()
void Rubberband::setCoords (int x1, int y1, int x2, int y2)
Referenced by Gui::RubberbandSelection::locationEvent().
setLineStipple()
void Rubberband::setLineStipple (bool on)
setViewer()
void Rubberband::setViewer (View3DInventorViewer * v)
Referenced by Gui::RubberbandSelection::initialize().
setWorking()
void Rubberband::setWorking (bool on)
Referenced by Gui::RubberbandSelection::initialize(), and Gui::RubberbandSelection::mouseButtonEvent().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/GLPainter.h
FreeCAD/src/Gui/GLPainter.cpp