FreeCAD: Gui::PythonWorkbenchPy Class Reference
Gui::PythonWorkbenchPy Class Reference
The python export class for PythonBaseWorkbench.
#include <PythonWorkbenchPy.h>
Public Types
typedef PythonBaseWorkbench * PointerType
Public Types inherited from Gui::WorkbenchPy
typedef Workbench * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
PythonWorkbenchPy (PythonBaseWorkbench *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
PythonBaseWorkbench * getPythonBaseWorkbenchPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Gui::WorkbenchPy
std::string representation (void) const
WorkbenchPy (Workbench *pcObject, PyTypeObject *T=&Type)
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Workbench * getWorkbenchPtr (void) const
getter for the object handled by this class
PyObject * name (PyObject *args)
implementer for the name() method
PyObject * activate (PyObject *args)
implementer for the activate() method
PyObject * listToolbars (PyObject *args)
implementer for the listToolbars() method
PyObject * getToolbarItems (PyObject *args)
implementer for the getToolbarItems() method
PyObject * listCommandbars (PyObject *args)
implementer for the listCommandbars() method
PyObject * listMenus (PyObject *args)
implementer for the listMenus() method
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Gui::WorkbenchPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_name (PyObject *self, PyObject *args)
callback for the name() method
static PyObject * staticCallback_activate (PyObject *self, PyObject *args)
callback for the activate() method
static PyObject * staticCallback_listToolbars (PyObject *self, PyObject *args)
callback for the listToolbars() method
static PyObject * staticCallback_getToolbarItems (PyObject *self, PyObject *args)
callback for the getToolbarItems() method
static PyObject * staticCallback_listCommandbars (PyObject *self, PyObject *args)
callback for the listCommandbars() method
static PyObject * staticCallback_listMenus (PyObject *self, PyObject *args)
callback for the listMenus() method
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of PythonWorkbenchPy.
static PyMethodDef Methods []
Methods structure of PythonWorkbenchPy.
static PyTypeObject Type
Type structure of PythonWorkbenchPy.
Static Public Attributes inherited from Gui::WorkbenchPy
static PyGetSetDef GetterSetter []
Attribute structure of WorkbenchPy.
static PyMethodDef Methods []
Methods structure of WorkbenchPy.
static PyTypeObject Type
Type structure of WorkbenchPy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~PythonWorkbenchPy ()
Protected Member Functions inherited from Gui::WorkbenchPy
~WorkbenchPy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * appendMenu (PyObject *args)
implementer for the appendMenu() method
PyObject * removeMenu (PyObject *args)
implementer for the removeMenu() method
PyObject * appendContextMenu (PyObject *args)
implementer for the appendContextMenu() method
PyObject * removeContextMenu (PyObject *args)
implementer for the removeContextMenu() method
PyObject * appendToolbar (PyObject *args)
implementer for the appendToolbar() method
PyObject * removeToolbar (PyObject *args)
implementer for the removeToolbar() method
PyObject * appendCommandbar (PyObject *args)
implementer for the appendCommandbar() method
PyObject * removeCommandbar (PyObject *args)
implementer for the removeCommandbar() method
PyObject * AppendMenu (PyObject *args)
implementer for the AppendMenu() method
PyObject * RemoveMenu (PyObject *args)
implementer for the RemoveMenu() method
PyObject * ListMenus (PyObject *args)
implementer for the ListMenus() method
PyObject * AppendContextMenu (PyObject *args)
implementer for the AppendContextMenu() method
PyObject * RemoveContextMenu (PyObject *args)
implementer for the RemoveContextMenu() method
PyObject * AppendToolbar (PyObject *args)
implementer for the AppendToolbar() method
PyObject * RemoveToolbar (PyObject *args)
implementer for the RemoveToolbar() method
PyObject * ListToolbars (PyObject *args)
implementer for the ListToolbars() method
PyObject * AppendCommandbar (PyObject *args)
implementer for the AppendCommandbar() method
PyObject * RemoveCommandbar (PyObject *args)
implementer for the RemoveCommandbar() method
PyObject * ListCommandbars (PyObject *args)
implementer for the ListCommandbars() method
static PyObject * staticCallback_appendMenu (PyObject *self, PyObject *args)
callback for the appendMenu() method
static PyObject * staticCallback_removeMenu (PyObject *self, PyObject *args)
callback for the removeMenu() method
static PyObject * staticCallback_appendContextMenu (PyObject *self, PyObject *args)
callback for the appendContextMenu() method
static PyObject * staticCallback_removeContextMenu (PyObject *self, PyObject *args)
callback for the removeContextMenu() method
static PyObject * staticCallback_appendToolbar (PyObject *self, PyObject *args)
callback for the appendToolbar() method
static PyObject * staticCallback_removeToolbar (PyObject *self, PyObject *args)
callback for the removeToolbar() method
static PyObject * staticCallback_appendCommandbar (PyObject *self, PyObject *args)
callback for the appendCommandbar() method
static PyObject * staticCallback_removeCommandbar (PyObject *self, PyObject *args)
callback for the removeCommandbar() method
static PyObject * staticCallback_AppendMenu (PyObject *self, PyObject *args)
callback for the AppendMenu() method
static PyObject * staticCallback_RemoveMenu (PyObject *self, PyObject *args)
callback for the RemoveMenu() method
static PyObject * staticCallback_ListMenus (PyObject *self, PyObject *args)
callback for the ListMenus() method
static PyObject * staticCallback_AppendContextMenu (PyObject *self, PyObject *args)
callback for the AppendContextMenu() method
static PyObject * staticCallback_RemoveContextMenu (PyObject *self, PyObject *args)
callback for the RemoveContextMenu() method
static PyObject * staticCallback_AppendToolbar (PyObject *self, PyObject *args)
callback for the AppendToolbar() method
static PyObject * staticCallback_RemoveToolbar (PyObject *self, PyObject *args)
callback for the RemoveToolbar() method
static PyObject * staticCallback_ListToolbars (PyObject *self, PyObject *args)
callback for the ListToolbars() method
static PyObject * staticCallback_AppendCommandbar (PyObject *self, PyObject *args)
callback for the AppendCommandbar() method
static PyObject * staticCallback_RemoveCommandbar (PyObject *self, PyObject *args)
callback for the RemoveCommandbar() method
static PyObject * staticCallback_ListCommandbars (PyObject *self, PyObject *args)
callback for the ListCommandbars() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for PythonBaseWorkbench.
Member Typedef Documentation
PointerType
typedef PythonBaseWorkbench* Gui::PythonWorkbenchPy::PointerType
Constructor & Destructor Documentation
~PythonWorkbenchPy()
PythonWorkbenchPy::~PythonWorkbenchPy () protected
PythonWorkbenchPy()
PythonWorkbenchPy::PythonWorkbenchPy (PythonBaseWorkbench * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
appendCommandbar()
PyObject * PythonWorkbenchPy::appendCommandbar (PyObject * args)
implementer for the appendCommandbar() method
Appends a new command bar.
References Gui::PythonBaseWorkbench::appendCommandbar(), and getPythonBaseWorkbenchPtr().
Referenced by AppendCommandbar(), InitGui.TemplatePyModWorkbench::Initialize(), Mod.Test.InitGui.TestWorkbench::Initialize(), and staticCallback_appendCommandbar().
AppendCommandbar()
PyObject * PythonWorkbenchPy::AppendCommandbar (PyObject * args)
implementer for the AppendCommandbar() method
References appendCommandbar().
Referenced by staticCallback_AppendCommandbar().
appendContextMenu()
PyObject * PythonWorkbenchPy::appendContextMenu (PyObject * args)
implementer for the appendContextMenu() method
Appends new context menu items.
References Gui::PythonBaseWorkbench::appendContextMenu(), and getPythonBaseWorkbenchPtr().
Referenced by AppendContextMenu(), InitGui.ArchWorkbench::ContextMenu(), InitGui.DraftWorkbench::ContextMenu(), and staticCallback_appendContextMenu().
AppendContextMenu()
PyObject * PythonWorkbenchPy::AppendContextMenu (PyObject * args)
implementer for the AppendContextMenu() method
References appendContextMenu().
Referenced by staticCallback_AppendContextMenu().
appendMenu()
PyObject * PythonWorkbenchPy::appendMenu (PyObject * args)
implementer for the appendMenu() method
Appends a new menu.
References Gui::PythonBaseWorkbench::appendMenu(), and getPythonBaseWorkbenchPtr().
Referenced by AppendMenu(), InitGui.OpenSCADWorkbench::Initialize(), InitGui.PathWorkbench::Initialize(), InitGui.PlotWorkbench::Initialize(), InitGui.ShipWorkbench::Initialize(), InitGui.TemplatePyModWorkbench::Initialize(), Mod.Test.InitGui.TestWorkbench::Initialize(), and staticCallback_appendMenu().
AppendMenu()
PyObject * PythonWorkbenchPy::AppendMenu (PyObject * args)
implementer for the AppendMenu() method
References appendMenu().
Referenced by staticCallback_AppendMenu().
appendToolbar()
PyObject * PythonWorkbenchPy::appendToolbar (PyObject * args)
implementer for the appendToolbar() method
Appends a new toolbar.
References Gui::PythonBaseWorkbench::appendToolbar(), and getPythonBaseWorkbenchPtr().
Referenced by AppendToolbar(), InitGui.OpenSCADWorkbench::Initialize(), InitGui.PathWorkbench::Initialize(), InitGui.PlotWorkbench::Initialize(), InitGui.ShipWorkbench::Initialize(), InitGui.TemplatePyModWorkbench::Initialize(), Mod.Test.InitGui.TestWorkbench::Initialize(), staticCallback_appendToolbar(), and Mod.Test.Workbench.WorkbenchTestCase::testHandler().
AppendToolbar()
PyObject * PythonWorkbenchPy::AppendToolbar (PyObject * args)
implementer for the AppendToolbar() method
References appendToolbar().
Referenced by staticCallback_AppendToolbar().
getCustomAttributes()
PyObject * PythonWorkbenchPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getPythonBaseWorkbenchPtr()
PythonBaseWorkbench * PythonWorkbenchPy::getPythonBaseWorkbenchPtr (void) const
getter for the object handled by this class
Referenced by appendCommandbar(), appendContextMenu(), appendMenu(), appendToolbar(), removeCommandbar(), removeContextMenu(), removeMenu(), and removeToolbar().
GetType()
virtual PyTypeObject* Gui::PythonWorkbenchPy::GetType (void) virtual
Reimplemented from Gui::WorkbenchPy.
ListCommandbars()
PyObject * PythonWorkbenchPy::ListCommandbars (PyObject * args)
implementer for the ListCommandbars() method
References Gui::WorkbenchPy::listCommandbars().
Referenced by staticCallback_ListCommandbars().
ListMenus()
PyObject * PythonWorkbenchPy::ListMenus (PyObject * args)
implementer for the ListMenus() method
References Gui::WorkbenchPy::listMenus().
Referenced by staticCallback_ListMenus().
ListToolbars()
PyObject * PythonWorkbenchPy::ListToolbars (PyObject * args)
implementer for the ListToolbars() method
References Gui::WorkbenchPy::listToolbars().
Referenced by staticCallback_ListToolbars().
PyInit()
int PythonWorkbenchPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Gui::WorkbenchPy.
PyMake()
PyObject * PythonWorkbenchPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
removeCommandbar()
PyObject * PythonWorkbenchPy::removeCommandbar (PyObject * args)
implementer for the removeCommandbar() method
Removes a command bar.
References getPythonBaseWorkbenchPtr(), and Gui::PythonBaseWorkbench::removeCommandbar().
Referenced by RemoveCommandbar(), and staticCallback_removeCommandbar().
RemoveCommandbar()
PyObject * PythonWorkbenchPy::RemoveCommandbar (PyObject * args)
implementer for the RemoveCommandbar() method
References removeCommandbar().
Referenced by staticCallback_RemoveCommandbar().
removeContextMenu()
PyObject * PythonWorkbenchPy::removeContextMenu (PyObject * args)
implementer for the removeContextMenu() method
Removes a context menu.
References getPythonBaseWorkbenchPtr(), and Gui::PythonBaseWorkbench::removeContextMenu().
Referenced by RemoveContextMenu(), and staticCallback_removeContextMenu().
RemoveContextMenu()
PyObject * PythonWorkbenchPy::RemoveContextMenu (PyObject * args)
implementer for the RemoveContextMenu() method
References removeContextMenu().
Referenced by staticCallback_RemoveContextMenu().
removeMenu()
PyObject * PythonWorkbenchPy::removeMenu (PyObject * args)
implementer for the removeMenu() method
Removes a menu.
References getPythonBaseWorkbenchPtr(), and Gui::PythonBaseWorkbench::removeMenu().
Referenced by RemoveMenu(), and staticCallback_removeMenu().
RemoveMenu()
PyObject * PythonWorkbenchPy::RemoveMenu (PyObject * args)
implementer for the RemoveMenu() method
References removeMenu().
Referenced by staticCallback_RemoveMenu().
removeToolbar()
PyObject * PythonWorkbenchPy::removeToolbar (PyObject * args)
implementer for the removeToolbar() method
Removes a toolbar.
References getPythonBaseWorkbenchPtr(), and Gui::PythonBaseWorkbench::removeToolbar().
Referenced by RemoveToolbar(), and staticCallback_removeToolbar().
RemoveToolbar()
PyObject * PythonWorkbenchPy::RemoveToolbar (PyObject * args)
implementer for the RemoveToolbar() method
References removeToolbar().
Referenced by staticCallback_RemoveToolbar().
representation()
std::string PythonWorkbenchPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int PythonWorkbenchPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_appendCommandbar()
PyObject * PythonWorkbenchPy::staticCallback_appendCommandbar (PyObject * self, PyObject * args) static
callback for the appendCommandbar() method
References appendCommandbar(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_AppendCommandbar()
PyObject * PythonWorkbenchPy::staticCallback_AppendCommandbar (PyObject * self, PyObject * args) static
callback for the AppendCommandbar() method
References AppendCommandbar(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_appendContextMenu()
PyObject * PythonWorkbenchPy::staticCallback_appendContextMenu (PyObject * self, PyObject * args) static
callback for the appendContextMenu() method
References appendContextMenu(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_AppendContextMenu()
PyObject * PythonWorkbenchPy::staticCallback_AppendContextMenu (PyObject * self, PyObject * args) static
callback for the AppendContextMenu() method
References AppendContextMenu(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_appendMenu()
PyObject * PythonWorkbenchPy::staticCallback_appendMenu (PyObject * self, PyObject * args) static
callback for the appendMenu() method
References appendMenu(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_AppendMenu()
PyObject * PythonWorkbenchPy::staticCallback_AppendMenu (PyObject * self, PyObject * args) static
callback for the AppendMenu() method
References AppendMenu(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_appendToolbar()
PyObject * PythonWorkbenchPy::staticCallback_appendToolbar (PyObject * self, PyObject * args) static
callback for the appendToolbar() method
References appendToolbar(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_AppendToolbar()
PyObject * PythonWorkbenchPy::staticCallback_AppendToolbar (PyObject * self, PyObject * args) static
callback for the AppendToolbar() method
References AppendToolbar(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_ListCommandbars()
PyObject * PythonWorkbenchPy::staticCallback_ListCommandbars (PyObject * self, PyObject * args) static
callback for the ListCommandbars() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), ListCommandbars(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_ListMenus()
PyObject * PythonWorkbenchPy::staticCallback_ListMenus (PyObject * self, PyObject * args) static
callback for the ListMenus() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), ListMenus(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_ListToolbars()
PyObject * PythonWorkbenchPy::staticCallback_ListToolbars (PyObject * self, PyObject * args) static
callback for the ListToolbars() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), ListToolbars(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_removeCommandbar()
PyObject * PythonWorkbenchPy::staticCallback_removeCommandbar (PyObject * self, PyObject * args) static
callback for the removeCommandbar() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeCommandbar(), and Base::PyObjectBase::startNotify().
staticCallback_RemoveCommandbar()
PyObject * PythonWorkbenchPy::staticCallback_RemoveCommandbar (PyObject * self, PyObject * args) static
callback for the RemoveCommandbar() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), RemoveCommandbar(), and Base::PyObjectBase::startNotify().
staticCallback_removeContextMenu()
PyObject * PythonWorkbenchPy::staticCallback_removeContextMenu (PyObject * self, PyObject * args) static
callback for the removeContextMenu() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeContextMenu(), and Base::PyObjectBase::startNotify().
staticCallback_RemoveContextMenu()
PyObject * PythonWorkbenchPy::staticCallback_RemoveContextMenu (PyObject * self, PyObject * args) static
callback for the RemoveContextMenu() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), RemoveContextMenu(), and Base::PyObjectBase::startNotify().
staticCallback_removeMenu()
PyObject * PythonWorkbenchPy::staticCallback_removeMenu (PyObject * self, PyObject * args) static
callback for the removeMenu() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeMenu(), and Base::PyObjectBase::startNotify().
staticCallback_RemoveMenu()
PyObject * PythonWorkbenchPy::staticCallback_RemoveMenu (PyObject * self, PyObject * args) static
callback for the RemoveMenu() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), RemoveMenu(), and Base::PyObjectBase::startNotify().
staticCallback_removeToolbar()
PyObject * PythonWorkbenchPy::staticCallback_removeToolbar (PyObject * self, PyObject * args) static
callback for the removeToolbar() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeToolbar(), and Base::PyObjectBase::startNotify().
staticCallback_RemoveToolbar()
PyObject * PythonWorkbenchPy::staticCallback_RemoveToolbar (PyObject * self, PyObject * args) static
callback for the RemoveToolbar() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), RemoveToolbar(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef PythonWorkbenchPy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of PythonWorkbenchPy.
Methods
PyMethodDef PythonWorkbenchPy::Methods static
Methods structure of PythonWorkbenchPy.
Type
PyTypeObject PythonWorkbenchPy::Type static
Type structure of PythonWorkbenchPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Gui/PythonWorkbenchPy.h
Sources/FreeCAD/src/Gui/PythonWorkbenchPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Gui/PythonWorkbenchPy.cpp