FreeCAD: Gui::GraphicsView3D Class Reference
Gui::GraphicsView3D Class Reference
#include <GLGraphicsView.h>
Public Member Functions
GraphicsScene * getScene ()
GraphicsView3D (Gui::Document *doc, QWidget *parent=0)
virtual void OnChange (ParameterGrp::SubjectType &rCaller, ParameterGrp::MessageType Reason)
virtual ~GraphicsView3D ()
Public Member Functions inherited from Gui::MDIView
virtual bool canClose (void)
overwrite when checking on close state
virtual void deleteSelf ()
delete itself
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
View constructor Attach the view to the given document.
virtual bool onHasMsg (const char *pMsg) const
Message handler test.
virtual bool onMsg (const char *pMsg, const char **ppReturn)
Message handler.
virtual void onRelabel (Gui::Document *pDoc)
get called when the document is updated
virtual void viewAll ()
~MDIView ()
View destructor Detach the view from the document, if attached.
virtual void print ()
Print content of view.
virtual void printPdf ()
Print to PDF file.
virtual void printPreview ()
Show a preview dialog.
QSize minimumSizeHint () const
virtual void setCurrentViewMode (ViewMode mode)
If b is set to FullScreen the MDI view is displayed in full screen mode, if b is set to TopLevel then it is displayed as an own top-level window, otherwise (Normal) as tabbed window.
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=0, std::string *subname=0) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=0)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=0) const
virtual bool containsViewProvider (const ViewProvider *) const
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=0)
View constructor Attach the view to the given document.
virtual ~BaseView ()
View destructor Detach the view from the document, if attached!
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose (void)
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive (void) const
indicates if the view is in passive mode
virtual void onUpdate (void)
get called when the document is updated
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
virtual const char * getName (void) const
returns the name of the view (important for messages)
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual Type getTypeId (void) const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Public Types inherited from Gui::MDIView
enum ViewMode { Child , TopLevel , FullScreen }
MDI view mode enum.
Public Slots inherited from Gui::MDIView
virtual void print (QPrinter *printer)
virtual void setOverrideCursor (const QCursor &)
virtual void restoreOverrideCursor ()
Signals inherited from Gui::MDIView
void message (const QString &, int)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Protected Slots inherited from Gui::MDIView
virtual void windowStateChanged (MDIView *)
This method gets called from the main window this view is attached to whenever the window state of the active view changes.
Protected Member Functions inherited from Gui::MDIView
void closeEvent (QCloseEvent *e)
void changeEvent (QEvent *e)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::MDIView
PyObject * pythonObject
Protected Attributes inherited from Gui::BaseView
bool bIsDetached
bool bIsPassive
Constructor & Destructor Documentation
GraphicsView3D()
GraphicsView3D::GraphicsView3D (Gui::Document * doc, QWidget * parent = 0)
References Base::Subject< _MessageType >::Attach(), App::GetApplication(), Base::Persistence::getClassTypeId(), Gui::GraphicsScene::getEventFilter(), App::Application::GetParameterGroupByPath(), OnChange(), Gui::GraphicsScene::setNavigationModeFile(), Gui::GraphicsScene::setSceneGraph(), and Gui::GraphicsScene::viewAll().
~GraphicsView3D()
GraphicsView3D::~GraphicsView3D () virtual
References Base::Subject< _MessageType >::Detach().
Member Function Documentation
getScene()
GraphicsScene* Gui::GraphicsView3D::getScene ()
OnChange()
void GraphicsView3D::OnChange (ParameterGrp::SubjectType & rCaller, ParameterGrp::MessageType Reason) virtual
References Base::Type::fromName(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), Base::BaseClass::getClassTypeId(), ParameterGrp::GetFloat(), ParameterGrp::GetInt(), Gui::BaseView::getName(), ParameterGrp::GetUnsigned(), and Gui::GraphicsScene::setBackgroundColor().
Referenced by GraphicsView3D().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sandbox/Gui/GLGraphicsView.h
Sources/FreeCAD/src/Mod/Sandbox/Gui/GLGraphicsView.cpp