FreeCAD: Mesh::Segment Class Reference
Mesh::Segment Class Reference
#include <Segment.h>
Classes
class const_facet_iterator
Public Member Functions
void addIndices (const std::vector< FacetIndex > &inds)
const_facet_iterator facets_begin () const
const_facet_iterator facets_end () const
const std::string & getColor () const
const std::vector< FacetIndex > & getIndices () const
const std::string & getName () const
bool isEmpty () const
bool isSaved () const
const Segment & operator= (const Segment &)
bool operator== (const Segment &) const
void removeIndices (const std::vector< FacetIndex > &inds)
void save (bool on)
Segment (const MeshObject *, bool mod)
Segment (const MeshObject *, const std::vector< FacetIndex > &inds, bool mod)
Segment (const Segment &)
void setColor (const std::string &c)
void setName (const std::string &n)
Friends
class MeshObject
Constructor & Destructor Documentation
Segment() [1/3]
Segment::Segment (const MeshObject * mesh, bool mod)
Segment() [2/3]
Segment::Segment (const MeshObject * mesh, const std::vector< FacetIndex > & inds, bool mod)
Segment() [3/3]
Segment::Segment (const Segment & s)
Member Function Documentation
addIndices()
void Segment::addIndices (const std::vector< FacetIndex > & inds)
Referenced by MeshPart::BrepMesh::create().
facets_begin()
const_facet_iterator Mesh::Segment::facets_begin () const
facets_end()
const_facet_iterator Mesh::Segment::facets_end () const
getColor()
const std::string & Mesh::Segment::getColor (void) const
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::getPrefColor(), MeshGui::ViewProviderMesh::highlightSegments(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::setValues().
getIndices()
const std::vector< FacetIndex > & Segment::getIndices () const
Referenced by Mesh::MergeExporter::addMesh(), MeshGui::SoFCMeshSegmentShape::computeBBox(), MeshGui::SoFCMeshSegmentShape::getPrimitiveCount(), and MeshGui::ViewProviderMesh::highlightSegments().
getName()
const std::string & Mesh::Segment::getName (void) const
Referenced by Mesh::MergeExporter::addMesh().
isEmpty()
bool Mesh::Segment::isEmpty (void) const
isSaved()
bool Mesh::Segment::isSaved () const
Referenced by Mesh::MergeExporter::addMesh().
operator=()
const Segment & Segment::operator= (const Segment & s)
operator==()
bool Segment::operator== (const Segment & s) const
Referenced by Mesh::Segment::const_facet_iterator::operator!=().
removeIndices()
void Segment::removeIndices (const std::vector< FacetIndex > & inds)
save()
void Mesh::Segment::save (bool on)
Referenced by MeshPart::BrepMesh::create(), Mod.Show.mTempoVis.TempoVis::modify(), Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle(), Mod.Show.mTempoVis.TempoVis::saveCamera(), and Mesh::MergeExporter::~MergeExporter().
setColor()
void Mesh::Segment::setColor (const std::string & c)
Referenced by MeshPart::BrepMesh::create().
setName()
void Mesh::Segment::setName (const std::string & n)
Referenced by Mesh::MergeExporter::addMesh(), and MeshPart::BrepMesh::create().
Friends And Related Function Documentation
MeshObject
friend class MeshObject friend
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/Segment.h
FreeCAD/src/Mod/Mesh/App/Segment.cpp