FreeCAD: Base::Vector2dPy Class Reference
Base::Vector2dPy Class Reference
#include <GeometryPyCXX.h>
Public Member Functions
Py::Object getattro (const Py::String &name_)
virtual Py::Object repr ()
int setattro (const Py::String &name_, const Py::Object &value)
void setValue (const Vector2d &n)
void setValue (double x, double y)
const Vector2d & value () const
Vector2dPy (Py::PythonClassInstance *self, Py::Tuple &args, Py::Dict &kwds)
virtual ~Vector2dPy ()
Static Public Member Functions
static Py::PythonType & behaviors ()
static bool check (PyObject *p)
static Py::PythonClassObject< Vector2dPy > create (const Vector2d &)
static Py::PythonClassObject< Vector2dPy > create (double x, double y)
static void init_type ()
static PyTypeObject * type_object ()
methods for group handling
virtual Py::Object number_negative ()
virtual Py::Object number_positive ()
virtual Py::Object number_absolute ()
virtual Py::Object number_invert ()
virtual Py::Object number_int ()
virtual Py::Object number_float ()
virtual Py::Object number_long ()
virtual Py::Object number_add (const Py::Object &)
virtual Py::Object number_subtract (const Py::Object &)
virtual Py::Object number_multiply (const Py::Object &)
virtual Py::Object number_remainder (const Py::Object &)
virtual Py::Object number_divmod (const Py::Object &)
virtual Py::Object number_lshift (const Py::Object &)
virtual Py::Object number_rshift (const Py::Object &)
virtual Py::Object number_and (const Py::Object &)
virtual Py::Object number_xor (const Py::Object &)
virtual Py::Object number_or (const Py::Object &)
virtual Py::Object number_power (const Py::Object &, const Py::Object &)
Py::Object isNull (const Py::Tuple &)
Py::Object length (const Py::Tuple &)
Py::Object atan2 (const Py::Tuple &)
Py::Object square (const Py::Tuple &)
Py::Object scale (const Py::Tuple &)
Py::Object rotate (const Py::Tuple &)
Py::Object normalize (const Py::Tuple &)
Py::Object perpendicular (const Py::Tuple &)
Py::Object distance (const Py::Tuple &)
Py::Object isEqual (const Py::Tuple &)
Py::Object getAngle (const Py::Tuple &)
Py::Object projectToLine (const Py::Tuple &)
Constructor & Destructor Documentation
Vector2dPy()
Base::Vector2dPy::Vector2dPy (Py::PythonClassInstance * self, Py::Tuple & args, Py::Dict & kwds)
~Vector2dPy()
Base::Vector2dPy::~Vector2dPy () virtual
Member Function Documentation
atan2()
Py::Object Base::Vector2dPy::atan2 (const Py::Tuple &)
behaviors()
Py::PythonType & Base::Vector2dPy::behaviors () static
check()
bool Base::Vector2dPy::check (PyObject * p) static
Referenced by femsolver.run.Machine::reset().
create() [1/2]
Py::PythonClassObject< Vector2dPy > Base::Vector2dPy::create (const Vector2d & v) static
References create().
Referenced by draftguitools.gui_labels.Label::action(), create(), number_absolute(), number_add(), number_multiply(), number_negative(), number_positive(), and number_subtract().
create() [2/2]
Py::PythonClassObject< Vector2dPy > Base::Vector2dPy::create (double x, double y) static
Referenced by draftguitools.gui_labels.Label::action().
distance()
Py::Object Base::Vector2dPy::distance (const Py::Tuple & args)
Referenced by PathScripts.PathDressupDogbone.Bone::adaptiveLength(), and PathScripts.PathDressupDogbone.Bone::corner().
getAngle()
Py::Object Base::Vector2dPy::getAngle (const Py::Tuple & args)
Referenced by PathScripts.PathDressupDogbone.Chord::getAngleXY(), draftguitools.gui_trackers.arcTracker::setEndPoint(), and draftguitools.gui_trackers.arcTracker::setStartPoint().
getattro()
Py::Object Base::Vector2dPy::getattro (const Py::String & name_)
init_type()
void Base::Vector2dPy::init_type (void) static
References draftgeoutils.general::isNull().
isEqual()
Py::Object Base::Vector2dPy::isEqual (const Py::Tuple & args)
isNull()
Py::Object Base::Vector2dPy::isNull (const Py::Tuple & args)
length()
Py::Object Base::Vector2dPy::length (const Py::Tuple &)
Referenced by PathScripts.PathStock.StockFromBase::execute(), PathScripts.PathDressupDogbone.ObjectDressup::execute(), PathScripts.PathFeatureExtensions.Extension::getSubLink(), PathScripts.PathFeatureExtensions.Extension::getWire(), and Mod.PartDesign.Scripts.FilletArc.Vector::norm().
normalize()
Py::Object Base::Vector2dPy::normalize (const Py::Tuple &)
Referenced by PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), and PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart().
number_absolute()
Py::Object Base::Vector2dPy::number_absolute () virtual
References create().
number_add()
Py::Object Base::Vector2dPy::number_add (const Py::Object & py) virtual
References create().
number_and()
Py::Object Base::Vector2dPy::number_and (const Py::Object &) virtual
number_divmod()
Py::Object Base::Vector2dPy::number_divmod (const Py::Object &) virtual
number_float()
Py::Object Base::Vector2dPy::number_float () virtual
number_int()
Py::Object Base::Vector2dPy::number_int () virtual
number_invert()
Py::Object Base::Vector2dPy::number_invert () virtual
number_long()
Py::Object Base::Vector2dPy::number_long () virtual
number_lshift()
Py::Object Base::Vector2dPy::number_lshift (const Py::Object &) virtual
number_multiply()
Py::Object Base::Vector2dPy::number_multiply (const Py::Object & py) virtual
References create(), and type_object().
number_negative()
Py::Object Base::Vector2dPy::number_negative () virtual
References create().
number_or()
Py::Object Base::Vector2dPy::number_or (const Py::Object &) virtual
number_positive()
Py::Object Base::Vector2dPy::number_positive () virtual
References create().
number_power()
Py::Object Base::Vector2dPy::number_power (const Py::Object & , const Py::Object &) virtual
number_remainder()
Py::Object Base::Vector2dPy::number_remainder (const Py::Object &) virtual
number_rshift()
Py::Object Base::Vector2dPy::number_rshift (const Py::Object &) virtual
number_subtract()
Py::Object Base::Vector2dPy::number_subtract (const Py::Object & py) virtual
References create().
number_xor()
Py::Object Base::Vector2dPy::number_xor (const Py::Object &) virtual
perpendicular()
Py::Object Base::Vector2dPy::perpendicular (const Py::Tuple & args)
References femsolver.elmer.equations.elasticity::create(), and Base::Vector2d::Perpendicular().
projectToLine()
Py::Object Base::Vector2dPy::projectToLine (const Py::Tuple & args)
repr()
Py::Object Base::Vector2dPy::repr () virtual
rotate()
Py::Object Base::Vector2dPy::rotate (const Py::Tuple & args)
Referenced by PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart(), draftguitools.gui_rotate.Rotate::numericRadius(), ArchSectionPlane.SectionPlaneTaskPanel::rotateX(), ArchSectionPlane.SectionPlaneTaskPanel::rotateY(), and ArchSectionPlane.SectionPlaneTaskPanel::rotateZ().
scale()
Py::Object Base::Vector2dPy::scale (const Py::Tuple & args)
Referenced by automotive_design.cartesian_transformation_operator::scl(), config_control_design.cartesian_transformation_operator::scl(), ifc2x3.ifccartesiantransformationoperator::scl(), and ifc4.ifccartesiantransformationoperator::scl().
setattro()
int Base::Vector2dPy::setattro (const Py::String & name_, const Py::Object & value)
setValue() [1/2]
void Base::Vector2dPy::setValue (const Vector2d & n)
setValue() [2/2]
void Base::Vector2dPy::setValue (double x, double y)
square()
Py::Object Base::Vector2dPy::square (const Py::Tuple &)
type_object()
PyTypeObject * Base::Vector2dPy::type_object () static
Referenced by number_multiply().
value()
const Vector2d & Base::Vector2dPy::value () const
Referenced by PathScripts.PathProperty.Property::displayString(), PathScripts.PathProperty.PropertyQuantity::displayString(), PathScripts.PathSetupSheetOpPrototype.Property::displayString(), PathScripts.PathSetupSheetOpPrototype.PropertyQuantity::displayString(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), PathScripts.PathProperty.Property::getValue(), PathScripts.PathSetupSheetOpPrototype.Property::getValue(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), PathScripts.PathProperty.Property::setValue(), and PathScripts.PathSetupSheetOpPrototype.Property::setValue().
The documentation for this class was generated from the following files:
FreeCAD/src/Base/GeometryPyCXX.h
FreeCAD/src/Base/GeometryPyCXX.cpp