FreeCAD: DrawSketchHandlerBSpline Class Reference
DrawSketchHandlerBSpline Class Reference
Public Types
enum SELECT_MODE { STATUS_SEEK_FIRST_CONTROLPOINT, STATUS_SEEK_ADDITIONAL_CONTROLPOINTS, STATUS_CLOSE }
modes
Public Member Functions
virtual void activated (ViewProviderSketch *)
DrawSketchHandlerBSpline (int constructionMethod)
virtual void mouseMove (Base::Vector2d onSketchPos)
virtual bool pressButton (Base::Vector2d onSketchPos)
virtual void quit (void)
virtual bool releaseButton (Base::Vector2d)
virtual ~DrawSketchHandlerBSpline ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::none, bool createowncommand=true)
virtual void deactivated (ViewProviderSketch *)
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual void registerPressedKey (bool, int)
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Attributes
int ConstrMethod
int CurrentConstraint
std::vector< Base::Vector2d > EditCurve
int FirstPoleGeoId
bool IsClosed
SELECT_MODE Mode
std::vector< std::vector< AutoConstraint > > sugConstr
Protected Attributes inherited from SketcherGui::DrawSketchHandler
QCursor actCursor
QPixmap actCursorPixmap
QCursor oldCursor
ViewProviderSketch * sketchgui
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
void addCursorTail (std::vector< QPixmap > &pixmaps)
void applyCursor (QCursor &newCursor)
void applyCursor (void)
qreal devicePixelRatio ()
unsigned long getCrosshairColor ()
void setCrosshairColor ()
void setCrosshairCursor (const char *svgName)
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
Sets a cursor for 3D inventor view.
void setSvgCursor (const QString &svgName, int x, int y, const std::map< unsigned long, unsigned long > &colorMapping=std::map< unsigned long, unsigned long >())
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
void unsetCursor (void)
Member Enumeration Documentation
SELECT_MODE
enum DrawSketchHandlerBSpline::SELECT_MODE
modes
Enumerator
STATUS_SEEK_FIRST_CONTROLPOINT
STATUS_SEEK_ADDITIONAL_CONTROLPOINTS
STATUS_CLOSE
Constructor & Destructor Documentation
DrawSketchHandlerBSpline()
DrawSketchHandlerBSpline::DrawSketchHandlerBSpline (int constructionMethod)
References sugConstr.
~DrawSketchHandlerBSpline()
virtual DrawSketchHandlerBSpline::~DrawSketchHandlerBSpline () virtual
Member Function Documentation
activated()
virtual void DrawSketchHandlerBSpline::activated (ViewProviderSketch *) virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::setCrosshairCursor().
mouseMove()
virtual void DrawSketchHandlerBSpline::mouseMove (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::applyCursor(), CurrentConstraint, SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, Mode, SketcherGui::DrawSketchHandler::renderSuggestConstraintsCursor(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), SketcherGui::DrawSketchHandler::setPositionText(), SketcherGui::DrawSketchHandler::sketchgui, STATUS_SEEK_ADDITIONAL_CONTROLPOINTS, STATUS_SEEK_FIRST_CONTROLPOINT, and sugConstr.
pressButton()
virtual bool DrawSketchHandlerBSpline::pressButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), Gui::cmdAppObjectArgs(), Sketcher::Coincident, Base::Console(), ConstrMethod, SketcherGui::DrawSketchHandler::createAutoConstraints(), CurrentConstraint, EditCurve, Base::ConsoleSingleton::Error(), FirstPoleGeoId, SketcherGui::DrawSketchHandler::getHighestCurveIndex(), Gui::ViewProviderDocumentObject::getObject(), IsClosed, Sketcher::mid, Mode, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, SketcherGui::DrawSketchHandler::sketchgui, STATUS_CLOSE, STATUS_SEEK_ADDITIONAL_CONTROLPOINTS, STATUS_SEEK_FIRST_CONTROLPOINT, and sugConstr.
quit()
virtual void DrawSketchHandlerBSpline::quit (void) virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), SketcherGui::DrawSketchHandler::applyCursor(), CurrentConstraint, SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, App::GetApplication(), ParameterGrp::GetBool(), Gui::ViewProviderDocumentObject::getObject(), App::Application::GetParameterGroupByPath(), IsClosed, Mode, releaseButton(), SketcherGui::DrawSketchHandler::sketchgui, STATUS_CLOSE, STATUS_SEEK_FIRST_CONTROLPOINT, sugConstr, and SketcherGui::tryAutoRecomputeIfNotSolve().
releaseButton()
virtual bool DrawSketchHandlerBSpline::releaseButton (Base::Vector2d) virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), SketcherGui::DrawSketchHandler::applyCursor(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Base::Console(), Sketcher::SketchObject::Constraints, ConstrMethod, CurrentConstraint, Gui::Command::Doc, SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, Sketcher::end, Base::ConsoleSingleton::Error(), FirstPoleGeoId, SketcherGui::geometryCreationMode, App::GetApplication(), ParameterGrp::GetBool(), SketcherGui::DrawSketchHandler::getHighestCurveIndex(), Gui::ViewProviderDocumentObject::getObject(), Gui::Command::getObjectCmd(), App::Application::GetParameterGroupByPath(), Sketcher::PropertyConstraintList::getValues(), IsClosed, Sketcher::mid, Mode, SketcherGui::ViewProviderSketch::purgeHandler(), SketcherGui::DrawSketchHandler::resetPositionText(), SketcherGui::DrawSketchHandler::sketchgui, Sketcher::start, STATUS_CLOSE, STATUS_SEEK_FIRST_CONTROLPOINT, sugConstr, SketcherGui::tryAutoRecomputeIfNotSolve(), and SketcherGui::DrawSketchHandler::unsetCursor().
Referenced by quit().
Member Data Documentation
ConstrMethod
int DrawSketchHandlerBSpline::ConstrMethod protected
Referenced by pressButton(), and releaseButton().
CurrentConstraint
int DrawSketchHandlerBSpline::CurrentConstraint protected
Referenced by mouseMove(), pressButton(), quit(), and releaseButton().
EditCurve
std::vector<Base::Vector2d> DrawSketchHandlerBSpline::EditCurve protected
Referenced by mouseMove(), pressButton(), quit(), and releaseButton().
FirstPoleGeoId
int DrawSketchHandlerBSpline::FirstPoleGeoId protected
Referenced by pressButton(), and releaseButton().
IsClosed
bool DrawSketchHandlerBSpline::IsClosed protected
Referenced by pressButton(), quit(), and releaseButton().
Mode
SELECT_MODE DrawSketchHandlerBSpline::Mode protected
Referenced by mouseMove(), pressButton(), quit(), and releaseButton().
sugConstr
std::vector<std::vector<AutoConstraint> > DrawSketchHandlerBSpline::sugConstr protected
Referenced by DrawSketchHandlerBSpline(), mouseMove(), pressButton(), quit(), and releaseButton().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/Gui/CommandCreateGeo.cpp