FreeCAD: Gui::Dialog::RedoDialog Class Reference
Gui::Dialog::RedoDialog Class Reference
This class implements the redo dialog.
#include <DlgUndoRedo.h>
Public Member Functions
RedoDialog (QWidget *parent=0)
Constructs a UndoRedoDialog which is a child of 'parent', with the name 'name'.
virtual ~RedoDialog ()
Destroys the object and frees any allocated resources.
Protected Slots
void onFetchInfo ()
This method fetches the undo / redo information from the active document and shows it in the undo / redo dialog.
void onSelected ()
Closes the dialog and sends the message 'Redo' to the currently active MDI view.
Detailed Description
This class implements the redo dialog.
Author
Werner Mayer
Constructor & Destructor Documentation
RedoDialog()
RedoDialog::RedoDialog (QWidget * parent = 0)
Constructs a UndoRedoDialog which is a child of 'parent', with the name 'name'.
'
References draftgeoutils.intersections::connect(), and onFetchInfo().
~RedoDialog()
RedoDialog::~RedoDialog () virtual
Destroys the object and frees any allocated resources.
Member Function Documentation
onFetchInfo
void RedoDialog::onFetchInfo () protected slot
This method fetches the undo / redo information from the active document and shows it in the undo / redo dialog.
References Gui::MainWindow::activeWindow(), Gui::BaseView::getGuiDocument(), Gui::getMainWindow(), Gui::Document::getRedoVector(), onSelected(), Gui::EditorView::redoActions(), Gui::TextDocumentEditorView::redoActions(), and draftutils.translate::translate().
Referenced by RedoDialog().
onSelected
void RedoDialog::onSelected () protected slot
Closes the dialog and sends the message 'Redo' to the currently active MDI view.
References Gui::Application::Instance, and Gui::Application::sendMsgToActiveView().
Referenced by onFetchInfo().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgUndoRedo.h
Sources/FreeCAD/src/Gui/DlgUndoRedo.cpp