FreeCAD: SMESH::Controls::NumericalFunctor Class Reference
SMESH::Controls::NumericalFunctor Class Reference abstract
#include <SMESH_ControlsDef.hxx>
Public Member Functions
virtual double GetBadRate (double Value, int nbNodes) const =0
void GetHistogram (int nbIntervals, std::vector< int > &nbEvents, std::vector< double > &funValues, const std::vector< int > &elements, const double *minmax=0, const bool isLogarithmic=false)
Return histogram of functor values.
bool GetPoints (const int theId, TSequenceOfXYZ &theRes) const
long GetPrecision () const
virtual SMDSAbs_ElementType GetType () const =0
virtual double GetValue (const TSequenceOfXYZ &thePoints)
virtual double GetValue (long theElementId)
NumericalFunctor ()
double Round (const double &value)
virtual void SetMesh (const SMDS_Mesh *theMesh)
void SetPrecision (const long thePrecision)
Public Member Functions inherited from SMESH::Controls::Functor
~Functor ()
Static Public Member Functions
static bool GetPoints (const SMDS_MeshElement *theElem, TSequenceOfXYZ &theRes)
Protected Attributes
const SMDS_MeshElement * myCurrElement
const SMDS_Mesh * myMesh
long myPrecision
double myPrecisionValue
Constructor & Destructor Documentation
NumericalFunctor()
NumericalFunctor::NumericalFunctor ()
References myPrecision.
Member Function Documentation
GetBadRate()
virtual double SMESH::Controls::NumericalFunctor::GetBadRate (double Value, int nbNodes) const pure virtual
Implemented in SMESH::Controls::BallDiameter, SMESH::Controls::MultiConnection2D, SMESH::Controls::MultiConnection, SMESH::Controls::Length2D, SMESH::Controls::Length, SMESH::Controls::Area, SMESH::Controls::Skew, SMESH::Controls::Taper, SMESH::Controls::Warping, SMESH::Controls::AspectRatio3D, SMESH::Controls::AspectRatio, SMESH::Controls::MinimumAngle, SMESH::Controls::MaxElementLength3D, SMESH::Controls::MaxElementLength2D, and SMESH::Controls::Volume.
GetHistogram()
void NumericalFunctor::GetHistogram (int nbIntervals, std::vector< int > & nbEvents, std::vector< double > & funValues, const std::vector< int > & elements, const double * minmax = 0, const bool isLogarithmic = false)
Return histogram of functor values.
Parameters
nbIntervals - number of intervals
nbEvents - number of mesh elements having values within i-th interval
funValues - boundaries of intervals
elements - elements to check vulue of; empty list means "of all"
minmax - boundaries of diapason of values to divide into intervals
References SMDS_Mesh::elementsIterator(), SMDS_Mesh::GetMeshInfo(), GetType(), GetValue(), myMesh, and SMDS_MeshInfo::NbElements().
GetPoints() [1/2]
bool NumericalFunctor::GetPoints (const int theId, TSequenceOfXYZ & theRes) const
References SMESH::Controls::TSequenceOfXYZ::clear(), SMDS_Mesh::FindElement(), SMDS_MeshElement::GetType(), and myMesh.
Referenced by GetValue(), SMESH::Controls::MaxElementLength2D::GetValue(), SMESH::Controls::MaxElementLength3D::GetValue(), SMESH::Controls::AspectRatio::GetValue(), SMESH::Controls::AspectRatio3D::GetValue(), SMESH::Controls::Length2D::GetValue(), NETGENPlugin_SimpleHypothesis_2D::SetParametersByMesh(), StdMeshers_MaxElementArea::SetParametersByMesh(), and SMESH_MeshEditor::Smooth().
GetPoints() [2/2]
bool NumericalFunctor::GetPoints (const SMDS_MeshElement * theElem, TSequenceOfXYZ & theRes) static
References SMESH::Controls::TSequenceOfXYZ::clear(), SMDS_MeshElement::GetType(), SMDS_MeshElement::IsQuadratic(), SMDS_MeshElement::NbNodes(), SMDS_MeshElement::nodesIterator(), SMESH::Controls::TSequenceOfXYZ::push_back(), SMESH::Controls::TSequenceOfXYZ::reserve(), and SMESH::Controls::TSequenceOfXYZ::setElement().
GetPrecision()
long NumericalFunctor::GetPrecision () const
References myPrecision.
GetType()
virtual SMDSAbs_ElementType SMESH::Controls::NumericalFunctor::GetType () const pure virtual
Implements SMESH::Controls::Functor.
Implemented in SMESH::Controls::BallDiameter, SMESH::Controls::MultiConnection2D, SMESH::Controls::MultiConnection, SMESH::Controls::Length2D, SMESH::Controls::Length, SMESH::Controls::Area, SMESH::Controls::Skew, SMESH::Controls::Taper, SMESH::Controls::Warping, SMESH::Controls::AspectRatio3D, SMESH::Controls::AspectRatio, SMESH::Controls::MinimumAngle, SMESH::Controls::MaxElementLength3D, SMESH::Controls::MaxElementLength2D, and SMESH::Controls::Volume.
Referenced by GetHistogram().
GetValue() [1/2]
virtual double SMESH::Controls::NumericalFunctor::GetValue (const TSequenceOfXYZ & thePoints) virtual
Reimplemented in SMESH::Controls::MultiConnection2D, SMESH::Controls::MultiConnection, SMESH::Controls::Length, SMESH::Controls::Area, SMESH::Controls::Skew, SMESH::Controls::Taper, SMESH::Controls::Warping, SMESH::Controls::AspectRatio3D, SMESH::Controls::AspectRatio, SMESH::Controls::MinimumAngle, and SMESH::Controls::MaxElementLength2D.
GetValue() [2/2]
double NumericalFunctor::GetValue (long theElementId) virtual
Reimplemented in SMESH::Controls::BallDiameter, SMESH::Controls::MultiConnection2D, SMESH::Controls::MultiConnection, SMESH::Controls::Length2D, SMESH::Controls::AspectRatio3D, SMESH::Controls::AspectRatio, SMESH::Controls::MaxElementLength3D, SMESH::Controls::MaxElementLength2D, and SMESH::Controls::Volume.
References SMDS_Mesh::FindElement(), GetPoints(), myCurrElement, myMesh, and Round().
Referenced by GetHistogram().
Round()
double NumericalFunctor::Round (const double & value)
References myPrecision, and myPrecisionValue.
Referenced by GetValue(), SMESH::Controls::AspectRatio::GetValue(), and SMESH::Controls::AspectRatio3D::GetValue().
SetMesh()
void NumericalFunctor::SetMesh (const SMDS_Mesh * theMesh) virtual
Implements SMESH::Controls::Functor.
References myMesh.
Referenced by NETGENPlugin_SimpleHypothesis_3D::SetParametersByMesh().
SetPrecision()
void NumericalFunctor::SetPrecision (const long thePrecision)
References myPrecision, and myPrecisionValue.
Member Data Documentation
myCurrElement
const SMDS_MeshElement* SMESH::Controls::NumericalFunctor::myCurrElement protected
Referenced by GetValue(), SMESH::Controls::AspectRatio::GetValue(), and SMESH::Controls::AspectRatio3D::GetValue().
myMesh
const SMDS_Mesh* SMESH::Controls::NumericalFunctor::myMesh protected
Referenced by SMESH::Controls::BadOrientedVolume::BadOrientedVolume(), SMESH::Controls::CoincidentElements::CoincidentElements(), SMESH::Controls::FreeBorders::FreeBorders(), SMESH::Controls::FreeEdges::FreeEdges(), GetHistogram(), GetPoints(), GetValue(), SMESH::Controls::Volume::GetValue(), SMESH::Controls::MaxElementLength3D::GetValue(), SMESH::Controls::AspectRatio::GetValue(), SMESH::Controls::AspectRatio3D::GetValue(), SMESH::Controls::MultiConnection::GetValue(), SMESH::Controls::MultiConnection2D::GetValue(), SMESH::Controls::BallDiameter::GetValue(), SMESH::Controls::MultiConnection2D::GetValues(), SMESH::Controls::Length2D::GetValues(), SMESH::Controls::CoincidentElements::IsSatisfy(), SMESH::Controls::FreeBorders::IsSatisfy(), SMESH::Controls::BadOrientedVolume::IsSatisfy(), SMESH::Controls::BareBorderVolume::IsSatisfy(), SMESH::Controls::BareBorderFace::IsSatisfy(), SMESH::Controls::OverConstrainedVolume::IsSatisfy(), SMESH::Controls::OverConstrainedFace::IsSatisfy(), SMESH::Controls::FreeEdges::IsSatisfy(), SetMesh(), SMESH::Controls::CoincidentElements::SetMesh(), SMESH::Controls::FreeBorders::SetMesh(), SMESH::Controls::BadOrientedVolume::SetMesh(), and SMESH::Controls::FreeEdges::SetMesh().
myPrecision
long SMESH::Controls::NumericalFunctor::myPrecision protected
Referenced by GetPrecision(), SMESH::Controls::MaxElementLength2D::GetValue(), SMESH::Controls::MaxElementLength3D::GetValue(), SMESH::Controls::Length2D::GetValue(), NumericalFunctor(), Round(), and SetPrecision().
myPrecisionValue
double SMESH::Controls::NumericalFunctor::myPrecisionValue protected
Referenced by Round(), and SetPrecision().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp