FreeCAD: CArea Class Reference
CArea Class Reference
#include <Area.h>
Public Member Functions
void append (const CCurve &curve)
void ChangeStartToNearest (const Point *pstart=NULL, double min_dist=1.0)
void Clip (ClipperLib::ClipType op, const CArea *a, ClipperLib::PolyFillType subjFillType=ClipperLib::pftEvenOdd, ClipperLib::PolyFillType clipFillType=ClipperLib::pftEvenOdd)
void CurveIntersections (const CCurve &curve, std::list< Point > &pts) const
void FitArcs ()
double GetArea (bool always_add=false) const
void GetBox (CBox2D &box)
void InsideCurves (const CCurve &curve, std::list< CCurve > &curves_inside) const
void Intersect (const CArea &a2)
void MakeOnePocketCurve (std::list< CCurve > &curve_list, const CAreaPocketParams &params) const
void MakePocketToolpath (std::list< CCurve > &toolpath, const CAreaPocketParams &params) const
void move (CCurve &&curve)
Point NearestPoint (const Point &p) const
unsigned int num_curves ()
void Offset (double inwards_value)
void OffsetWithClipper (double offset, ClipperLib::JoinType joinType=ClipperLib::jtRound, ClipperLib::EndType endType=ClipperLib::etOpenRound, double miterLimit=5.0, double roundPrecision=0.0)
void PopulateClipper (ClipperLib::Clipper &c, ClipperLib::PolyType type) const
void Reorder ()
void SpanIntersections (const Span &span, std::list< Point > &pts) const
void Split (std::list< CArea > &m_areas) const
void SplitAndMakePocketToolpath (std::list< CCurve > &toolpath, const CAreaPocketParams &params) const
void Subtract (const CArea &a2)
void Thicken (double value)
void Union (const CArea &a2)
void Xor (const CArea &a2)
Static Public Member Functions
static bool HolesLinked ()
static CArea UniteCurves (std::list< CCurve > &curves)
Public Attributes
std::list< CCurve > m_curves
Static Public Attributes
static double m_accuracy = 0.01
static double m_after_MakeOffsets_length = 0.0
static double m_clipper_clean_distance = 0.0
static double m_clipper_scale = 10000.0
static bool m_clipper_simple = false
static bool m_fit_arcs = true
static double m_MakeOffsets_increment = 0.0
static int m_max_arc_points = 100
static int m_min_arc_points = 4
static bool m_please_abort = false
static double m_processing_done = 0.0
static bool m_set_processing_length_in_split = false
static double m_single_area_processing_length = 0.0
static double m_split_processing_length = 0.0
static double m_units = 1.0
Member Function Documentation
append()
void CArea::append (const CCurve & curve)
Referenced by Path::Area::addWire(), CCurve::CurveIntersections(), CCurve::Offset(), and ThickLine::ThickLine().
ChangeStartToNearest()
void CArea::ChangeStartToNearest (const Point * pstart = NULL, double min_dist = 1.0)
References Point::dist(), DraftVecUtils::dist(), CCurve::IsClosed(), m_curves, CCurve::m_vertices, CCurve::NearestPoint(), and Point::tolerance.
Clip()
void CArea::Clip (ClipperLib::ClipType op, const CArea * a, ClipperLib::PolyFillType subjFillType = ClipperLib::pftEvenOdd, ClipperLib::PolyFillType clipFillType = ClipperLib::pftEvenOdd)
References ClipperLib::ClosedPathsFromPolyTree(), m_clipper_simple, ClipperLib::OpenPathsFromPolyTree(), PopulateClipper(), ClipperLib::ptClip, ClipperLib::ptSubject, and ClipperLib::Clipper::StrictlySimple().
CurveIntersections()
void CArea::CurveIntersections (const CCurve & curve, std::list< Point > & pts) const
References CCurve::GetSpans(), and SpanIntersections().
Referenced by InsideCurves().
FitArcs()
void CArea::FitArcs ()
References CCurve::FitArcs(), and m_curves.
Referenced by Path::Area::toShape().
GetArea()
double CArea::GetArea (bool always_add = false) const
References CCurve::GetArea(), and m_curves.
Referenced by MakeOnePocketCurve().
GetBox()
void CArea::GetBox (CBox2D & box)
References CCurve::GetBox(), and m_curves.
HolesLinked()
bool CArea::HolesLinked () static
Referenced by Split().
InsideCurves()
void CArea::InsideCurves (const CCurve & curve, std::list< CCurve > & curves_inside) const
References CurveIntersections(), CCurve::ExtractSeparateCurves(), CCurve::Perim(), and CCurve::PerimToPoint().
Intersect()
void CArea::Intersect (const CArea & a2)
References ClipperLib::ctIntersection, m_clipper_simple, ClipperLib::ptClip, ClipperLib::ptSubject, and ClipperLib::Clipper::StrictlySimple().
MakeOnePocketCurve()
void CArea::MakeOnePocketCurve (std::list< CCurve > & curve_list, const CAreaPocketParams & params) const
References GetArea(), GetCurveItem::GetCurve(), CurveTree::inners, m_after_MakeOffsets_length, m_curves, m_MakeOffsets_increment, m_please_abort, m_processing_done, m_single_area_processing_length, CCurve::m_vertices, CurveTree::MakeOffsets(), Offset(), CurveTree::offset_islands, and GetCurveItem::to_do_list.
MakePocketToolpath()
void CArea::MakePocketToolpath (std::list< CCurve > & toolpath, const CAreaPocketParams & params) const
References m_curves, m_please_abort, m_processing_done, m_single_area_processing_length, Offset(), and Split().
Referenced by SplitAndMakePocketToolpath().
move()
void CArea::move (CCurve && curve)
References m_curves, and draftfunctions.move::move().
Referenced by draftguitools.gui_circulararray.CircularArray::Activated(), draftguitools.gui_polararray.PolarArray::Activated(), and Path::Area::addWire().
NearestPoint()
Point CArea::NearestPoint (const Point & p) const
References Point::dist(), DraftVecUtils::dist(), m_curves, and CCurve::NearestPoint().
num_curves()
unsigned int CArea::num_curves ()
References m_curves.
Offset()
void CArea::Offset (double inwards_value)
References m_units, and Reorder().
Referenced by MakeOnePocketCurve(), and MakePocketToolpath().
OffsetWithClipper()
void CArea::OffsetWithClipper (double offset, ClipperLib::JoinType joinType = ClipperLib::jtRound, ClipperLib::EndType endType = ClipperLib::etOpenRound, double miterLimit = 5.0, double roundPrecision = 0.0)
References ClipperLib::ClipperOffset::AddPath(), ClipperLib::etClosedPolygon, ClipperLib::ClipperOffset::Execute(), m_accuracy, m_clipper_scale, m_curves, m_min_arc_points, m_units, and Reorder().
PopulateClipper()
void CArea::PopulateClipper (ClipperLib::Clipper & c, ClipperLib::PolyType type) const
References CCurve::IsClosed(), m_curves, and ClipperLib::ptClip.
Referenced by Clip().
Reorder()
void CArea::Reorder ()
References CAreaOrderer::Insert(), m_curves, m_processing_done, m_set_processing_length_in_split, m_split_processing_length, and CAreaOrderer::m_top_level.
Referenced by Path::Area::addShape(), Offset(), OffsetWithClipper(), Split(), and Thicken().
SpanIntersections()
void CArea::SpanIntersections (const Span & span, std::list< Point > & pts) const
References m_curves, and CCurve::SpanIntersections().
Referenced by CurveIntersections().
Split()
void CArea::Split (std::list< CArea > & m_areas) const
References HolesLinked(), CCurve::IsClockwise(), m_curves, m_please_abort, and Reorder().
Referenced by MakePocketToolpath(), and SplitAndMakePocketToolpath().
SplitAndMakePocketToolpath()
void CArea::SplitAndMakePocketToolpath (std::list< CCurve > & toolpath, const CAreaPocketParams & params) const
References m_processing_done, m_set_processing_length_in_split, m_single_area_processing_length, m_split_processing_length, m_units, MakePocketToolpath(), and Split().
Subtract()
void CArea::Subtract (const CArea & a2)
References ClipperLib::ctDifference, m_clipper_simple, ClipperLib::ptClip, ClipperLib::ptSubject, and ClipperLib::Clipper::StrictlySimple().
Thicken()
void CArea::Thicken (double value)
References m_units, and Reorder().
Referenced by ThickLine::ThickLine().
Union()
void CArea::Union (const CArea & a2)
References ClipperLib::ctUnion, m_clipper_simple, ClipperLib::ptClip, ClipperLib::ptSubject, and ClipperLib::Clipper::StrictlySimple().
UniteCurves()
CArea CArea::UniteCurves (std::list< CCurve > & curves) static
References ClipperLib::ctUnion, m_clipper_simple, ClipperLib::pftNonZero, ClipperLib::ptSubject, and ClipperLib::Clipper::StrictlySimple().
Xor()
void CArea::Xor (const CArea & a2)
References ClipperLib::ctXor, m_clipper_simple, ClipperLib::ptClip, ClipperLib::ptSubject, and ClipperLib::Clipper::StrictlySimple().
Member Data Documentation
m_accuracy
double CArea::m_accuracy = 0.01 static
Referenced by CCurve::CheckForArc(), OffsetWithClipper(), and CCurve::UnFitArcs().
m_after_MakeOffsets_length
double CArea::m_after_MakeOffsets_length = 0.0 static
Referenced by MakeOnePocketCurve().
m_clipper_clean_distance
double CArea::m_clipper_clean_distance = 0.0 static
m_clipper_scale
double CArea::m_clipper_scale = 10000.0 static
Referenced by DoubleAreaPoint::DoubleAreaPoint(), DoubleAreaPoint::int_point(), and OffsetWithClipper().
m_clipper_simple
bool CArea::m_clipper_simple = false static
Referenced by Clip(), Intersect(), Subtract(), Union(), UniteCurves(), and Xor().
m_curves
std::list<CCurve> CArea::m_curves
Referenced by Path::Area::addShape(), Path::Area::addToBuild(), Path::Area::build(), ChangeStartToNearest(), FitArcs(), GetArea(), CInnerCurves::GetArea(), GetBox(), MakeOnePocketCurve(), MakePocketToolpath(), move(), NearestPoint(), num_curves(), OffsetWithClipper(), AreaDxfRead::OnReadArc(), AreaDxfRead::OnReadLine(), PopulateClipper(), Reorder(), SpanIntersections(), and Split().
m_fit_arcs
bool CArea::m_fit_arcs = true static
m_MakeOffsets_increment
double CArea::m_MakeOffsets_increment = 0.0 static
Referenced by MakeOnePocketCurve().
m_max_arc_points
int CArea::m_max_arc_points = 100 static
m_min_arc_points
int CArea::m_min_arc_points = 4 static
Referenced by OffsetWithClipper().
m_please_abort
bool CArea::m_please_abort = false static
Referenced by GetCurveItem::GetCurve(), MakeOnePocketCurve(), MakePocketToolpath(), and Split().
m_processing_done
double CArea::m_processing_done = 0.0 static
Referenced by MakeOnePocketCurve(), MakePocketToolpath(), Reorder(), and SplitAndMakePocketToolpath().
m_set_processing_length_in_split
bool CArea::m_set_processing_length_in_split = false static
Referenced by Reorder(), and SplitAndMakePocketToolpath().
m_single_area_processing_length
double CArea::m_single_area_processing_length = 0.0 static
Referenced by MakeOnePocketCurve(), MakePocketToolpath(), and SplitAndMakePocketToolpath().
m_split_processing_length
double CArea::m_split_processing_length = 0.0 static
Referenced by Reorder(), and SplitAndMakePocketToolpath().
m_units
double CArea::m_units = 1.0 static
Referenced by CCurve::CheckForArc(), GetCurveItem::GetCurve(), Offset(), OffsetWithClipper(), SplitAndMakePocketToolpath(), Thicken(), and CCurve::UnFitArcs().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Path/libarea/Area.h
FreeCAD/src/Mod/Path/libarea/Area.cpp
FreeCAD/src/Mod/Path/libarea/AreaClipper.cpp
FreeCAD/src/Mod/Path/libarea/AreaPocket.cpp