FreeCAD: PathTests.TestPathVoronoi.TestPathVoronoi Class Reference
PathTests.TestPathVoronoi.TestPathVoronoi Class Reference
Public Member Functions
def setUp (self)
def test00 (self)
def test10 (self)
def test20 (self)
def test50 (self)
def test51 (self)
def test52 (self)
def test60 (self)
def test61 (self)
def test62 (self)
Public Member Functions inherited from PathTests.PathTestUtils.PathTestBase
def assertArc (self, edge, pt1, pt2, direction="CW")
def assertCircle (self, edge, pt, r)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertCommandEqual (self, c1, c2)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertEdgeShapesMatch (self, e1, e2)
def assertEqualLocale (self, s1, s2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertPlacement (self, p1, p2)
def assertPointsMatch (self, pts0, pts1)
def assertRoughly (self, f1, f2, error=0.00001)
Member Function Documentation
setUp()
def PathTests.TestPathVoronoi.TestPathVoronoi.setUp (self)
References PathTests.TestPathVoronoi.initVD().
test00()
def PathTests.TestPathVoronoi.TestPathVoronoi.test00 (self)
Check vertex comparison
Referenced by PathTests.TestPathTool.TestPathTool.test01(), PathTests.TestPathToolController.TestPathToolController.test01(), PathTests.TestPathTooltable.TestPathTooltable.test01(), PathTests.TestPathTool.TestPathTool.test02(), and PathTests.TestPathTooltable.TestPathTooltable.test02().
test10()
def PathTests.TestPathVoronoi.TestPathVoronoi.test10 (self)
Check edge comparison
test20()
def PathTests.TestPathVoronoi.TestPathVoronoi.test20 (self)
Check cell comparison
test50()
def PathTests.TestPathVoronoi.TestPathVoronoi.test50 (self)
Check toShape for linear edges
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
test51()
def PathTests.TestPathVoronoi.TestPathVoronoi.test51 (self)
Check toShape for linear edges with set z
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
test52()
def PathTests.TestPathVoronoi.TestPathVoronoi.test52 (self)
Check toShape for linear edges with varying z
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
test60()
def PathTests.TestPathVoronoi.TestPathVoronoi.test60 (self)
Check toShape for curved edges
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
test61()
def PathTests.TestPathVoronoi.TestPathVoronoi.test61 (self)
Check toShape for curved edges with set z
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
test62()
def PathTests.TestPathVoronoi.TestPathVoronoi.test62 (self)
Check toShape for curved edges with varying z
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Path/PathTests/TestPathVoronoi.py