FreeCAD: nlohmann::detail::parser< BasicJsonType, InputAdapterType > Class Template Reference
nlohmann::detail::parser< BasicJsonType, InputAdapterType > Class Template Reference
syntax analysis
#include <json.hpp>
Public Member Functions
bool accept (const bool strict=true)
public accept interface
void parse (const bool strict, BasicJsonType &result)
public parser interface
parser (InputAdapterType &&adapter, const parser_callback_t< BasicJsonType > cb=nullptr, const bool allow_exceptions_=true, const bool skip_comments=false)
a parser reading from an input adapter
template<typename SAX >
bool sax_parse (SAX *sax, const bool strict=true)
Detailed Description
template<typename BasicJsonType, typename InputAdapterType>
class nlohmann::detail::parser< BasicJsonType, InputAdapterType >
syntax analysis
This class implements a recursive descent parser.
Constructor & Destructor Documentation
parser()
template<typename BasicJsonType , typename InputAdapterType > nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parser (InputAdapterType && adapter, const parser_callback_t< BasicJsonType > cb = nullptr, const bool allow_exceptions_ = true, const bool skip_comments = false) explicit
a parser reading from an input adapter
Member Function Documentation
accept()
template<typename BasicJsonType , typename InputAdapterType > bool nlohmann::detail::parser< BasicJsonType, InputAdapterType >::accept (const bool strict = true)
public accept interface
Parameters
[in] strict whether to expect the last token to be EOF
Returns
whether the input is a proper JSON text
References nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse(), and nlohmann::detail::strict.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
parse()
template<typename BasicJsonType , typename InputAdapterType > void nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse (const bool strict, BasicJsonType & result)
public parser interface
Parameters
[in] strict whether to expect the last token to be EOF
[in,out] result parsed JSON value
Exceptions
parse_error.101 in case of an unexpected token
parse_error.102 if to_unicode fails or surrogate error
parse_error.103 if to_unicode fails
References nlohmann::detail::parse_error::create(), nlohmann::detail::discarded, nlohmann::detail::json_sax_dom_parser< BasicJsonType >::is_errored(), nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >::is_errored(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::parse_error(), nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >::parse_error(), and nlohmann::detail::strict.
Referenced by BOPTools.GeneralFuseResult.GeneralFuseResult::explodeCompounds(), and BOPTools.GeneralFuseResult.GeneralFuseResult::splitAggregates().
sax_parse()
template<typename BasicJsonType , typename InputAdapterType > template<typename SAX > bool nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse (SAX * sax, const bool strict = true)
References nlohmann::detail::parse_error::create(), and nlohmann::detail::strict.
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::accept().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/PartDesign/App/json.hpp