FreeCAD: TechDraw::DrawProjGroup Class Reference
TechDraw::DrawProjGroup Class Reference
Class super-container for managing a collection of DrawProjGroupItem Page Features.
#include <DrawProjGroup.h>
Public Member Functions
App::DocumentObject * addProjection (const char *viewProjType)
Adds a projection to the group.
double calculateAutomaticScale () const
DrawProjGroup ()
Constructor.
Base::BoundBox3d getBoundingBox () const
Anchor Element to align views to.
DrawProjGroupItem * getProjItem (const char *viewProjType) const
App::DocumentObject * getProjObj (const char *viewProjType) const
virtual QRectF getRect (void) const override
Base::Vector3d getXYPosition (const char *viewTypeCStr)
bool hasProjection (const char *viewProjType) const
Check if container has a view of a specific type.
short mustExecute () const override
mustExecute We call this method to check if the object was modified to be invoked.
int purgeProjections ()
int removeProjection (const char *viewProjType)
Removes a projection from the group.
~DrawProjGroup ()
Public Member Functions inherited from TechDraw::DrawViewCollection
int addView (DrawView *view)
int countChildren ()
DrawViewCollection ()
Constructor.
virtual App::DocumentObjectExecReturn * execute (void)
recalculate the Feature
virtual QRectF getRect (void) const
virtual const char * getViewProviderName (void) const
returns the type name of the ViewProvider
bool isUnsetting (void)
void lockChildren (void)
short mustExecute () const
mustExecute We call this method to check if the object was modified to be invoked.
virtual void onDocumentRestored ()
get called after a document has been fully restored
void rebuildViewList (void)
int removeView (DrawView *view)
virtual void unsetupObject ()
get called when object is going to be removed from the document
virtual ~DrawViewCollection ()
Public Member Functions inherited from TechDraw::DrawView
DrawView (void)
Constructor.
virtual ~DrawView ()
bool isInClip ()
DrawViewClip * getClipGroup (void)
virtual DrawPage * findParentPage () const
virtual std::vector< DrawPage * > findAllParentPages () const
virtual int countParentPages () const
DrawView::countParentPages Fixes a crash in TechDraw when user creates duplicate page without dependencies In fixOrphans() we check how many parent pages an object has before deleting in case it is also a child of another duplicate page.
virtual double autoScale (void) const
virtual double autoScale (double w, double h) const
virtual bool checkFit (void) const
virtual bool checkFit (DrawPage *) const
check if View is too big for page
virtual void setPosition (double x, double y, bool force=false)
virtual bool keepUpdated (void)
virtual double getScale (void) const
void checkScale (void)
void requestPaint (void)
virtual void handleXYLock (void)
virtual bool isLocked (void) const
virtual bool showLock (void) const
std::vector< TechDraw::DrawLeaderLine * > getLeaders (void) const
void setScaleAttribute ()
Public Member Functions inherited from App::DocumentObject
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
virtual bool adjustRelativeLinks (const std::set< App::DocumentObject * > &inList, std::set< App::DocumentObject * > *visited=nullptr)
Called to adjust link properties to avoid cyclic links.
virtual bool allowDuplicateLabel () const
virtual bool canLinkProperties () const
virtual int canLoadPartial () const
allow partial loading of dependent objects
void clearExpression (const ObjectIdentifier &path)
void clearOutListCache () const
clear internal out list cache
virtual const char * detachFromDocument () override
DocumentObject (void)
Constructor.
void enforceRecompute ()
Enforce this document object to be recomputed.
App::Document * getDocument (void) const
gets the document in which this Object is handled
std::string getExportName (bool forced=false) const
returns the name that is safe to be exported to other document
virtual const PropertyExpressionEngine::ExpressionInfo getExpression (const ObjectIdentifier &path) const
virtual std::string getFullName () const override
Return the object full name of the form DocName::ObjName.
DocumentObjectGroup * getGroup () const
get group if object is part of a group, otherwise 0 is returned
long getID () const
Return the object ID that is unique within its owner document.
const std::vector< App::DocumentObject * > & getInList (void) const
std::set< App::DocumentObject * > getInListEx (bool recursive) const
Return a set of all objects linking to this object, including possible external parent objects.
void getInListEx (std::set< App::DocumentObject * > &inSet, bool recursive, std::vector< App::DocumentObject * > *inList=nullptr) const
Get a set of all objects linking to this object, including possible external parent objects.
std::vector< App::DocumentObject * > getInListRecursive (void) const
get all objects link directly or indirectly to this object
virtual DocumentObject * getLinkedObject (bool recurse=true, Base::Matrix4D *mat=nullptr, bool transform=false, int depth=0) const
Return the linked object with optional transformation.
const char * getNameInDocument (void) const
returns the name which is set in the document for this object (not the name property!)
const std::string & getOldLabel () const
const std::vector< App::DocumentObject * > & getOutList () const
returns a list of objects this object is pointing to by Links
std::vector< App::DocumentObject * > getOutList (int option) const
void getOutList (int option, std::vector< App::DocumentObject * > &res) const
std::vector< App::DocumentObject * > getOutListOfProperty (App::Property *) const
returns a list of objects linked by the property
std::vector< App::DocumentObject * > getOutListRecursive (void) const
returns a list of objects this object is pointing to by Links and all further descended
std::vector< std::pair< App::DocumentObject *, std::string > > getParents (int depth=0) const
Obtain top parents and subnames of this object using its InList.
std::vector< std::list< App::DocumentObject * > > getPathsByOutList (App::DocumentObject *to) const
get all possible paths from this to another object following the OutList
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
unsigned long getStatus () const
return the status bits
const char * getStatusString (void) const
get the status Message
virtual DocumentObject * getSubObject (const char *subname, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
Get the sub element/object by name.
std::vector< DocumentObject * > getSubObjectList (const char *subname) const
Return a list of objects referenced by a given subname including this object.
virtual std::vector< std::string > getSubObjects (int reason=0) const
Return name reference of all sub-objects.
virtual const char * getViewProviderName (void) const
returns the type name of the ViewProvider
virtual const char * getViewProviderNameOverride () const
This function is introduced to allow Python feature override its view provider.
const char * getViewProviderNameStored () const
virtual bool hasChildElement () const
return true to activate tree view group object handling and element visibility
virtual bool isAttachedToDocument () const override
virtual int isElementVisible (const char *element) const
Get sub-element visibility.
bool isError (void) const
set this feature to error
int isExporting () const
bool isInInList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the InList
bool isInInListRecursive (DocumentObject *objToTest) const
test if this object is in the InList and recursive further down
bool isInOutList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the OutList
bool isInOutListRecursive (DocumentObject *objToTest) const
test if the given object is in the OutList and recursive further down
bool isRecomputing () const
returns true if this objects is currently recomputing
bool isRemoving () const
returns true if this objects is currently removed from the document
bool isRestoring () const
returns true if this objects is currently restoring from file
bool isTouched (void) const
test if this document object is touched
bool isValid (void) const
virtual short mustExecute (void) const
mustExecute We call this method to check if the object was modified to be invoked.
bool mustRecompute (void) const
Test if this document object must be recomputed.
virtual void onBeforeChangeLabel (std::string &newLabel)
virtual void onLostLinkToObject (DocumentObject *)
Called in case of losing a link Get called by the document when a object got deleted a link property of this object ist pointing to.
virtual void onUpdateElementReference (const Property *)
void purgeError (void)
remove the error from the object
void purgeTouched (void)
reset this document object touched
bool recomputeFeature (bool recursive=false)
Recompute only this feature.
virtual bool redirectSubName (std::ostringstream &ss, DocumentObject *topParent, DocumentObject *child) const
Allow object to redirect a subname path.
virtual bool removeDynamicProperty (const char *prop) override
virtual void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths)
App::DocumentObject * resolve (const char *subname, App::DocumentObject **parent=nullptr, std::string *childName=nullptr, const char **subElement=nullptr, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
Resolve the last document object referenced in the subname.
App::DocumentObject * resolveRelativeLink (std::string &subname, App::DocumentObject *&link, std::string &linkSub) const
Resolve a link reference that is relative to this object reference.
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
virtual int setElementVisible (const char *element, bool visible)
Child element handling.
virtual void setExpression (const ObjectIdentifier &path, std::shared_ptr< App::Expression > expr)
void setStatus (ObjectStatus pos, bool on)
bool testIfLinkDAGCompatible (App::PropertyLinkSub &linkTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSubList &linksTo) const
bool testIfLinkDAGCompatible (const std::vector< DocumentObject * > &linksTo) const
bool testIfLinkDAGCompatible (DocumentObject *linkTo) const
testIfLinkIsDAG tests a link that is about to be created for circular references.
bool testStatus (ObjectStatus pos) const
void touch (bool noRecompute=false)
Set the property touched -> changed, cause recomputation in Update()
virtual ~DocumentObject ()
Public Member Functions inherited from App::TransactionalObject
virtual const char * detachFromDocument ()
virtual bool isAttachedToDocument () const
TransactionalObject (void)
Constructor.
virtual ~TransactionalObject ()
Public Member Functions inherited from App::ExtensionContainer
ExtensionIterator extensionBegin ()
ExtensionContainer ()
ExtensionIterator extensionEnd ()
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
void registerExtension (Base::Type extension, App::Extension *ext)
virtual ~ExtensionContainer ()
virtual Property * getPropertyByName (const char *name) const override
find a property by its name
virtual const char * getPropertyName (const Property *prop) const override
get the name of a property
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
virtual void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
virtual short getPropertyType (const Property *prop) const override
get the Type of a Property
virtual short getPropertyType (const char *name) const override
get the Type of a named Property
virtual const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
virtual void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
Public Member Functions inherited from App::PropertyContainer
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false)
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual void editProperty (const char *)
virtual App::Property * getDynamicPropertyByName (const char *name) const
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual std::string getFullName () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Property * getPropertyByName (const char *name) const
find a property by its name
virtual const char * getPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * getPropertyGroup (const Property *prop) const
get the Group of a Property
virtual void getPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual const char * getPropertyName (const Property *prop) const
get the name of a property
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
const char * getPropertyPrefix () const
virtual short getPropertyType (const char *name) const
get the Type of a named Property
virtual short getPropertyType (const Property *prop) const
get the Type of a Property
bool isHidden (const char *name) const
check if the named property is hidden
bool isHidden (const Property *prop) const
check if the property is hidden
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isReadOnly (const Property *prop) const
check if the property is read-only
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus)
PropertyContainer ()
A constructor.
virtual bool removeDynamicProperty (const char *name)
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
void setPropertyPrefix (const char *prefix)
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
virtual ~PropertyContainer ()
A destructor.
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Attributes
App::PropertyLink Anchor
App::PropertyBool AutoDistribute
Whether projcetion group view are automatically distributed or not.
App::PropertyEnumeration ProjectionType
App::PropertyLinkList Source
App::PropertyLength spacingX
Default horizontal spacing between adjacent views on Drawing, in mm.
App::PropertyLength spacingY
Default vertical spacing between adjacent views on Drawing, in mm.
App::PropertyXLinkList XSource
Public Attributes inherited from TechDraw::DrawViewCollection
App::PropertyLinkList Views
Public Attributes inherited from TechDraw::DrawView
App::PropertyString Caption
App::PropertyBool LockPosition
App::PropertyAngle Rotation
App::PropertyFloatConstraint Scale
App::PropertyEnumeration ScaleType
App::PropertyDistance X
App::PropertyDistance Y
boost::signals2::signal< void(const DrawView *)> signalGuiPaint
Public Attributes inherited from App::DocumentObject
PropertyExpressionEngine ExpressionEngine
PropertyString Label
PropertyString Label2
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChange
signal before changing a property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChanged
signal on changed property of this object
PropertyBool Visibility
Allow control visibility status in App name space.
methods override Feature
static const char * ProjectionTypeEnums []
Allowed projection types - either Document, First Angle or Third Angle.
bool m_lockScale
virtual App::DocumentObjectExecReturn * execute (void) override
recalculate the Feature
virtual const char * getViewProviderName (void) const override
returns the type name of the ViewProvider
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
App::Enumeration usedProjectionType (void)
Determines either "First Angle" or "Third Angle".
bool hasAnchor (void)
void setAnchorDirection (Base::Vector3d dir)
Base::Vector3d getAnchorDirection (void)
TechDraw::DrawProjGroupItem * getAnchor (void)
std::pair< Base::Vector3d, Base::Vector3d > getDirsFromFront (DrawProjGroupItem *view)
std::pair< Base::Vector3d, Base::Vector3d > getDirsFromFront (std::string viewType)
void updateSecondaryDirs ()
void rotate (const std::string &rotationdirection)
void spin (const std::string &spindirection)
void dumpISO (const char *title)
std::vector< DrawProjGroupItem * > getViewsAsDPGI ()
void recomputeChildren (void)
void updateChildrenScale (void)
void autoPositionChildren (void)
void updateChildrenEnforce (void)
std::vector< App::DocumentObject * > getAllSources (void) const
void onChanged (const App::Property *prop) override
get called by the container when a property was changed
bool checkViewProjType (const char *in)
Annoying helper - keep in sync with DrawProjGroupItem::TypeEnums.
void arrangeViewPointers (DrawProjGroupItem *viewPtrs[10]) const
void makeViewBbs (DrawProjGroupItem *viewPtrs[10], Base::BoundBox3d bboxes[10], bool documentScale=true) const
Populates array of 10 BoundBox3d's given DrawProjGroupItem *s.
void minimumBbViews (DrawProjGroupItem *viewPtrs[10], double &width, double &height) const
Helper for calculateAutomaticScale.
TechDraw::DrawPage * getPage (void) const
Returns pointer to our page, or NULL if it couldn't be located.
void updateChildrenSource (void)
void updateChildrenLock (void)
void updateViews (void)
int getViewIndex (const char *viewTypeCStr) const
int getDefProjConv (void) const
Base::Vector3d dir2vec (gp_Dir d)
gp_Dir vec2dir (Base::Vector3d v)
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, App::Property *prop) override
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
Additional Inherited Members
Public Types inherited from App::DocumentObject
enum GSReason { GS_DEFAULT , GS_SELECT }
reason of calling getSubObjects()
enum OutListOption { OutListNoExpression = 1 , OutListNoHidden = 2 , OutListNoXLinked = 4 }
DAG handling This part of the interface deals with viewing the document as a DAG (directed acyclic graph).
Public Types inherited from App::ExtensionContainer
typedef std::map< Base::Type, App::Extension * >::iterator ExtensionIterator
Static Public Member Functions inherited from App::DocumentObject
static const char * hasHiddenMarker (const char *subname)
Check if the subname reference ends with hidden marker.
static const std::string & hiddenMarker ()
Special marker to mark the object as hidden.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Public Attributes inherited from App::DocumentObject
static DocumentObjectExecReturn * StdReturn
Protected Member Functions inherited from TechDraw::DrawViewCollection
void onChanged (const App::Property *prop)
get called by the container when a property was changed
Protected Member Functions inherited from TechDraw::DrawView
virtual void validateScale ()
int prefScaleType (void)
double prefScale (void)
Protected Member Functions inherited from App::DocumentObject
virtual App::DocumentObjectExecReturn * execute (void)
get called by the document to recompute this feature Normally this method get called in the processing of Document::recompute().
App::DocumentObjectExecReturn * executeExtensions ()
Executes the extensions of a document object.
virtual void onBeforeChange (const Property *prop) override
get called before the value is changed
virtual void onChanged (const Property *prop) override
get called by the container when a property was changed
virtual void onDocumentRestored ()
get called after a document has been fully restored
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus) override
get called when a property status has changed
virtual void onSettingDocument ()
get called after setting the document
virtual void onUndoRedoFinished ()
get called after an undo/redo transaction is finished
virtual App::DocumentObjectExecReturn * recompute (void)
recompute only this object
void resetError (void)
void setDocument (App::Document *doc)
void setError (void)
virtual void setupObject ()
get called after a brand new object was created
virtual void unsetupObject ()
get called when object is going to be removed from the document
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData (void) const
virtual void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container.
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
virtual void onBeforeChange (const Property *)
get called before the value is changed
virtual void onChanged (const Property *)
get called by the container when a property has changed
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from TechDraw::DrawViewCollection
bool nowUnsetting
Protected Attributes inherited from TechDraw::DrawView
std::string pageFeatName
bool autoPos
bool mouseMove
Protected Attributes inherited from App::DocumentObject
std::string oldLabel
Old label; used for renaming expressions.
const std::string * pcNameInDocument
Py::SmartPtr PythonObject
python object of this class and all descendent
std::bitset< 32 > StatusBits
Status bits of the document object The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Detailed Description
Class super-container for managing a collection of DrawProjGroupItem Page Features.
Constructor & Destructor Documentation
DrawProjGroup()
DrawProjGroup::DrawProjGroup (void)
Constructor.
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), App::Global, App::Property::Hidden, and App::Prop_None.
~DrawProjGroup()
DrawProjGroup::~DrawProjGroup ()
Member Function Documentation
addProjection()
App::DocumentObject * DrawProjGroup::addProjection (const char * viewProjType)
Adds a projection to the group.
Returns
pointer to the new view
References TechDraw::DrawViewCollection::addView(), Anchor, checkViewProjType(), Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::DrawView::findParentPage(), getDirsFromFront(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::Document::getUniqueObjectName(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyXLinkSubList::getValues(), hasProjection(), Base::ConsoleSingleton::Log(), App::Property::purgeTouched(), App::Property::ReadOnly, TechDraw::DrawView::requestPaint(), App::PropertyLink::setValue(), Source, and XSource.
Referenced by TechDrawGui::TaskProjGroup::restoreGroupState().
arrangeViewPointers()
void DrawProjGroup::arrangeViewPointers (DrawProjGroupItem * viewPtrs[10]) const protected
References Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::DrawView::findParentPage(), getDefProjConv(), App::DocumentObject::getNameInDocument(), App::PropertyEnumeration::getValueAsString(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyEnumeration::isValue(), Base::ConsoleSingleton::Log(), TechDraw::DrawPage::ProjectionType, ProjectionType, ProjectionTypeEnums, TechDraw::DrawViewCollection::Views, and Base::ConsoleSingleton::Warning().
Referenced by calculateAutomaticScale(), getRect(), and getXYPosition().
autoPositionChildren()
void DrawProjGroup::autoPositionChildren (void)
References App::PropertyListsT< T, ListT, ParentT >::getValues(), and TechDraw::DrawViewCollection::Views.
Referenced by execute().
calculateAutomaticScale()
double DrawProjGroup::calculateAutomaticScale () const
References arrangeViewPointers(), Base::Console(), App::DocumentObject::getNameInDocument(), getPage(), TechDraw::DrawPage::getPageHeight(), TechDraw::DrawPage::getPageWidth(), App::PropertyQuantity::getValue(), Base::ConsoleSingleton::Log(), minimumBbViews(), TechDraw::DrawUtil::sensibleScale(), spacingX, and spacingY.
Referenced by TechDrawGui::TaskProjGroup::scaleTypeChanged().
checkViewProjType()
bool DrawProjGroup::checkViewProjType (const char * in) protected
Annoying helper - keep in sync with DrawProjGroupItem::TypeEnums.
Returns
true iff 'in' is a valid name for an orthographic/isometric view
Referenced by addProjection(), and removeProjection().
dir2vec()
Base::Vector3d DrawProjGroup::dir2vec (gp_Dir d) protected
Referenced by getDirsFromFront().
dumpISO()
void DrawProjGroup::dumpISO (const char * title)
dumps the current iso DPGI's
References Base::Console(), TechDraw::DrawUtil::formatVector(), App::PropertyEnumeration::getValueAsString(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Base::ConsoleSingleton::Message(), TechDraw::DrawProjGroupItem::Type, and TechDraw::DrawViewCollection::Views.
execute()
App::DocumentObjectExecReturn * DrawProjGroup::execute (void) override virtual
recalculate the Feature
Reimplemented from TechDraw::DrawViewCollection.
References Anchor, autoPositionChildren(), TechDraw::DrawView::autoScale(), TechDraw::DrawView::checkFit(), TechDraw::DrawViewCollection::execute(), getAllSources(), getPage(), App::PropertyLink::getValue(), App::PropertyEnumeration::isValue(), TechDraw::DrawView::keepUpdated(), m_lockScale, App::Property::purgeTouched(), TechDraw::DrawView::Scale, TechDraw::DrawView::ScaleType, App::PropertyFloat::setValue(), App::DocumentObject::StdReturn, and updateChildrenScale().
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), PathScripts.PathDressupDogbone.ObjectDressup::boneStateList(), ArchSite.Compass::buildCoordinates(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::generateTags(), ArchPanel.PanelCut::getWires(), ArchSchedule.CommandArchSchedule::IsActive(), Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), FeaturePython.DistanceBolt::onChanged(), PathScripts.PathStock.StockFromBase::onChanged(), PathScripts.PathStock.StockCreateBox::onChanged(), PathScripts.PathStock.StockCreateCylinder::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), draftobjects.patharray.PathArray::onDocumentRestored(), and draftobjects.pathtwistedarray.PathTwistedArray::onDocumentRestored().
getAllSources()
std::vector< App::DocumentObject * > DrawProjGroup::getAllSources (void) const
References App::PropertyXLinkSubList::getLinks(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Source, and XSource.
Referenced by execute().
getAnchor()
TechDraw::DrawProjGroupItem * DrawProjGroup::getAnchor (void)
References Anchor, and App::PropertyLink::getValue().
Referenced by getDirsFromFront(), TechDrawGui::ViewProviderProjGroupItem::onDelete(), rotate(), TechDrawGui::TaskProjGroup::saveGroupState(), spin(), and updateSecondaryDirs().
getAnchorDirection()
Base::Vector3d DrawProjGroup::getAnchorDirection (void)
References Anchor, Base::Console(), TechDraw::DrawViewPart::Direction, App::PropertyVector::getValue(), App::PropertyLink::getValue(), and Base::ConsoleSingleton::Log().
Referenced by TechDrawGui::TaskProjGroup::setUiPrimary().
getBoundingBox()
Base::BoundBox3d DrawProjGroup::getBoundingBox () const
Anchor Element to align views to.
References Base::BoundBox3< _Precision >::Add(), Anchor, Base::Console(), TechDraw::DrawViewPart::getBoundingBox(), Base::Persistence::getClassTypeId(), App::DocumentObject::getNameInDocument(), TechDraw::DrawView::getScale(), App::PropertyLink::getValue(), App::PropertyQuantity::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Base::ConsoleSingleton::Log(), Base::BoundBox3< _Precision >::MoveX(), Base::BoundBox3< _Precision >::MoveY(), Base::BoundBox3< _Precision >::ScaleX(), Base::BoundBox3< _Precision >::ScaleY(), Base::BoundBox3< _Precision >::ScaleZ(), TechDraw::DrawViewCollection::Views, TechDraw::DrawView::X, and TechDraw::DrawView::Y.
getDefProjConv()
int DrawProjGroup::getDefProjConv (void) const protected
References TechDraw::Preferences::projectionAngle().
Referenced by arrangeViewPointers(), and getViewIndex().
getDirsFromFront() [1/2]
std::pair< Base::Vector3d, Base::Vector3d > DrawProjGroup::getDirsFromFront (DrawProjGroupItem * view)
References getDirsFromFront().
Referenced by addProjection(), getDirsFromFront(), rotate(), and updateSecondaryDirs().
getDirsFromFront() [2/2]
std::pair< Base::Vector3d, Base::Vector3d > DrawProjGroup::getDirsFromFront (std::string viewType)
References Base::Console(), dir2vec(), TechDraw::DrawViewPart::Direction, Base::ConsoleSingleton::Error(), getAnchor(), App::DocumentObject::getNameInDocument(), TechDraw::DrawViewPart::getProjectionCS(), App::PropertyVector::getValue(), App::PropertyString::getValue(), TechDraw::DrawProjGroupItem::getXDirection(), App::DocumentObject::Label, and Base::ConsoleSingleton::Warning().
getPage()
TechDraw::DrawPage * DrawProjGroup::getPage (void) const protected
Returns pointer to our page, or NULL if it couldn't be located.
References TechDraw::DrawView::findParentPage().
Referenced by calculateAutomaticScale(), execute(), onChanged(), and usedProjectionType().
getProjItem()
DrawProjGroupItem * DrawProjGroup::getProjItem (const char * viewProjType) const
References Base::Console(), App::DocumentObject::getNameInDocument(), getProjObj(), and Base::ConsoleSingleton::Log().
getProjObj()
App::DocumentObject * DrawProjGroup::getProjObj (const char * viewProjType) const
References Base::Console(), App::DocumentObject::getNameInDocument(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Base::ConsoleSingleton::Log(), and TechDraw::DrawViewCollection::Views.
Referenced by getProjItem().
getPyObject()
PyObject * DrawProjGroup::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from TechDraw::DrawView.
References App::DocumentObject::PythonObject.
getRect()
QRectF DrawProjGroup::getRect (void) const override virtual
Reimplemented from TechDraw::DrawViewCollection.
References arrangeViewPointers(), TechDraw::DrawUtil::fpCompare(), TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), minimumBbViews(), spacingX, and spacingY.
getViewIndex()
int DrawProjGroup::getViewIndex (const char * viewTypeCStr) const protected
References Base::Console(), TechDraw::DrawView::findParentPage(), getDefProjConv(), App::DocumentObject::getNameInDocument(), App::PropertyEnumeration::getValueAsString(), App::PropertyEnumeration::isValue(), TechDraw::DrawPage::ProjectionType, ProjectionType, ProjectionTypeEnums, and Base::ConsoleSingleton::Warning().
Referenced by getXYPosition().
getViewProviderName()
virtual const char * TechDraw::DrawProjGroup::getViewProviderName (void) const override virtual
returns the type name of the ViewProvider
Reimplemented from TechDraw::DrawViewCollection.
getViewsAsDPGI()
std::vector< DrawProjGroupItem * > DrawProjGroup::getViewsAsDPGI ()
References App::PropertyListsT< T, ListT, ParentT >::getValues(), and TechDraw::DrawViewCollection::Views.
getXYPosition()
Base::Vector3d DrawProjGroup::getXYPosition (const char * viewTypeCStr)
References arrangeViewPointers(), AutoDistribute, Base::Console(), App::PropertyBool::getValue(), App::PropertyQuantity::getValue(), getViewIndex(), Base::BoundBox3< _Precision >::IsValid(), TechDraw::DrawView::LockPosition, makeViewBbs(), Base::ConsoleSingleton::Message(), spacingX, spacingY, TechDraw::DrawView::X, and TechDraw::DrawView::Y.
handleChangedPropertyType()
void DrawProjGroup::handleChangedPropertyType (Base::XMLReader & reader, const char * TypeName, App::Property * prop) override protected virtual
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
This method is typically called if the property on file has changed its type in more recent versions.
The default implementation does nothing.
Parameters
reader The XML stream to read from.
TypeName Name of property type on file.
prop Pointer to property to restore. Its type differs from TypeName.
Reimplemented from TechDraw::DrawView.
References App::PropertyFloat::getValue(), TechDraw::DrawView::handleChangedPropertyType(), App::PropertyFloat::Restore(), App::PropertyQuantity::setValue(), spacingX, and spacingY.
hasAnchor()
bool DrawProjGroup::hasAnchor (void)
References Anchor, and App::PropertyLink::getValue().
hasProjection()
bool DrawProjGroup::hasProjection (const char * viewProjType) const
Check if container has a view of a specific type.
References Base::Console(), App::DocumentObject::getNameInDocument(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Base::ConsoleSingleton::Log(), and TechDraw::DrawViewCollection::Views.
Referenced by addProjection(), TechDrawGui::ViewProviderProjGroupItem::onDelete(), removeProjection(), TechDrawGui::TaskProjGroup::setupViewCheckboxes(), and TechDrawGui::TaskProjGroup::viewToggled().
makeViewBbs()
void DrawProjGroup::makeViewBbs (DrawProjGroupItem * viewPtrs[10], Base::BoundBox3d bboxes[10], bool documentScale = true) const protected
Populates array of 10 BoundBox3d's given DrawProjGroupItem *s.
If documentScale is set, then returned bounding boxes are scaled as in the Drawing. Otherwise, the dimensions are as in object space.
References TechDraw::DrawViewPart::getBoundingBox(), TechDraw::DrawProjGroupItem::getScale(), Base::BoundBox3< _Precision >::ScaleX(), Base::BoundBox3< _Precision >::ScaleY(), and Base::BoundBox3< _Precision >::ScaleZ().
Referenced by getXYPosition(), and minimumBbViews().
minimumBbViews()
void DrawProjGroup::minimumBbViews (DrawProjGroupItem * viewPtrs[10], double & width, double & height) const protected
Helper for calculateAutomaticScale.
Returns a width and height in object-space scale, for the enabled views without accounting for their actual X and Y positions or borders.
References Base::BoundBox3< _Precision >::LengthX(), and makeViewBbs().
Referenced by calculateAutomaticScale(), and getRect().
mustExecute()
short DrawProjGroup::mustExecute () const override virtual
mustExecute We call this method to check if the object was modified to be invoked.
If the object label or an argument is modified. If we must recompute the object - to call the method execute(). 0: no recomputation is needed 1: recomputation needed
Remarks
If an object is marked as 'touched' then this does not necessarily mean that it will be recomputed. It only means that all objects that link it (i.e. its InList) will be recomputed.
Reimplemented from TechDraw::DrawView.
References Anchor, AutoDistribute, App::DocumentObject::isRestoring(), App::Property::isTouched(), TechDraw::DrawView::LockPosition, TechDraw::DrawViewCollection::mustExecute(), ProjectionType, TechDraw::DrawView::Scale, TechDraw::DrawView::ScaleType, Source, spacingX, spacingY, TechDraw::DrawViewCollection::Views, and XSource.
onChanged()
void DrawProjGroup::onChanged (const App::Property * prop) override protected virtual
get called by the container when a property was changed
Reimplemented from TechDraw::DrawView.
References Base::Console(), TechDraw::DrawUtil::fpCompare(), getPage(), TechDraw::DrawView::getScale(), App::PropertyFloat::getValue(), App::PropertyQuantity::getValue(), App::DocumentObject::isRestoring(), App::PropertyEnumeration::isValue(), TechDraw::DrawView::LockPosition, Base::ConsoleSingleton::Log(), m_lockScale, TechDraw::DrawViewCollection::onChanged(), ProjectionType, App::DocumentObject::purgeTouched(), TechDraw::DrawView::Rotation, TechDraw::DrawPage::Scale, TechDraw::DrawView::Scale, TechDraw::DrawView::ScaleType, App::PropertyFloat::setValue(), App::PropertyQuantity::setValue(), Source, spacingX, spacingY, updateChildrenEnforce(), updateChildrenLock(), updateChildrenScale(), updateChildrenSource(), and XSource.
Referenced by ArchStructure.CommandStructuralSystem::Activated(), draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSite.Compass::buildCoordinates(), draftobjects.wire.Wire::execute(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchPanel.ViewProviderPanelSheet::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), and draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData().
purgeProjections()
int DrawProjGroup::purgeProjections ()
References Base::Console(), TechDraw::DrawView::findParentPage(), App::DocumentObject::getNameInDocument(), App::PropertyEnumeration::getValueAsString(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Base::ConsoleSingleton::Log(), removeProjection(), TechDraw::DrawProjGroupItem::Type, and TechDraw::DrawViewCollection::Views.
Referenced by TechDrawGui::TaskProjGroup::restoreGroupState().
recomputeChildren()
void DrawProjGroup::recomputeChildren (void)
References App::PropertyListsT< T, ListT, ParentT >::getValues(), and TechDraw::DrawViewCollection::Views.
Referenced by TechDrawGui::TaskProjGroup::accept(), TechDrawGui::TaskProjGroup::apply(), and updateSecondaryDirs().
removeProjection()
int DrawProjGroup::removeProjection (const char * viewProjType)
Removes a projection from the group.
Returns
number of projections remaining
References checkViewProjType(), Base::Console(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::PropertyListsT< T, ListT, ParentT >::getValues(), hasProjection(), Base::ConsoleSingleton::Log(), App::Document::removeObject(), TechDraw::DrawViewCollection::removeView(), and TechDraw::DrawViewCollection::Views.
Referenced by purgeProjections(), and TechDrawGui::TaskProjGroup::viewToggled().
rotate()
void DrawProjGroup::rotate (const std::string & rotationdirection)
References TechDraw::DrawViewPart::Direction, getAnchor(), getDirsFromFront(), App::PropertyVector::setValue(), updateSecondaryDirs(), and TechDraw::DrawViewPart::XDirection.
Referenced by PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart(), draftguitools.gui_rotate.Rotate::numericRadius(), TechDrawGui::TaskProjGroup::rotateButtonClicked(), ArchSectionPlane.SectionPlaneTaskPanel::rotateX(), ArchSectionPlane.SectionPlaneTaskPanel::rotateY(), and ArchSectionPlane.SectionPlaneTaskPanel::rotateZ().
setAnchorDirection()
void DrawProjGroup::setAnchorDirection (Base::Vector3d dir)
References Anchor, TechDraw::DrawViewPart::Direction, App::PropertyLink::getValue(), and App::PropertyVector::setValue().
spin()
void DrawProjGroup::spin (const std::string & spindirection)
References DraftVecUtils::angle(), TechDraw::DrawViewPart::Direction, getAnchor(), App::PropertyVector::getValue(), TechDraw::DrawProjGroupItem::getXDirection(), App::PropertyVector::setValue(), updateSecondaryDirs(), TechDraw::DrawUtil::vecRotate(), and TechDraw::DrawViewPart::XDirection.
Referenced by TechDrawGui::TaskProjGroup::rotateButtonClicked().
updateChildrenEnforce()
void DrawProjGroup::updateChildrenEnforce (void)
References Base::Console(), App::DocumentObject::getNameInDocument(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Base::ConsoleSingleton::Log(), and TechDraw::DrawViewCollection::Views.
Referenced by onChanged().
updateChildrenLock()
void DrawProjGroup::updateChildrenLock (void) protected
tell children DPGIs that parent DPG has changed LockPosition (really for benefit of QGIV on Gui side)
References Base::Console(), App::DocumentObject::getNameInDocument(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Base::ConsoleSingleton::Log(), and TechDraw::DrawViewCollection::Views.
Referenced by onChanged().
updateChildrenScale()
void DrawProjGroup::updateChildrenScale (void)
tell children DPGIs that parent DPG has changed Scale
References Base::Console(), App::DocumentObject::getNameInDocument(), TechDraw::DrawView::getScale(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Base::ConsoleSingleton::Log(), and TechDraw::DrawViewCollection::Views.
Referenced by execute(), and onChanged().
updateChildrenSource()
void DrawProjGroup::updateChildrenSource (void) protected
tell children DPGIs that parent DPG has changed Source
References Base::Console(), App::DocumentObject::getNameInDocument(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyXLinkSubList::getValues(), Base::ConsoleSingleton::Log(), Source, TechDraw::DrawViewCollection::Views, and XSource.
Referenced by onChanged().
updateSecondaryDirs()
void DrawProjGroup::updateSecondaryDirs ()
References TechDraw::Bottom, Base::Console(), TechDraw::DrawViewPart::Direction, TechDraw::Front, TechDraw::FrontBottomLeft, TechDraw::FrontBottomRight, TechDraw::FrontTopLeft, TechDraw::FrontTopRight, getAnchor(), getDirsFromFront(), App::PropertyVector::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), TechDraw::DrawProjGroupItem::getXDirection(), TechDraw::Left, Base::ConsoleSingleton::Message(), TechDraw::Rear, recomputeChildren(), TechDraw::Right, TechDraw::Top, and TechDraw::DrawViewCollection::Views.
Referenced by rotate(), and spin().
updateViews()
void DrawProjGroup::updateViews (void) protected
References Base::Console(), App::DocumentObject::getNameInDocument(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Base::ConsoleSingleton::Log(), and TechDraw::DrawViewCollection::Views.
usedProjectionType()
App::Enumeration DrawProjGroup::usedProjectionType (void)
Determines either "First Angle" or "Third Angle".
References getPage(), App::PropertyEnumeration::getValueAsString(), App::Enumeration::isValue(), TechDraw::DrawPage::ProjectionType, ProjectionType, ProjectionTypeEnums, and App::Enumeration::setValue().
vec2dir()
gp_Dir DrawProjGroup::vec2dir (Base::Vector3d v) protected
Member Data Documentation
Anchor
App::PropertyLink TechDraw::DrawProjGroup::Anchor
Referenced by addProjection(), execute(), getAnchor(), getAnchorDirection(), TechDrawGui::QGIProjGroup::getAnchorQItem(), getBoundingBox(), hasAnchor(), mustExecute(), setAnchorDirection(), and TechDraw::DrawProjGroupItem::unsetupObject().
AutoDistribute
App::PropertyBool TechDraw::DrawProjGroup::AutoDistribute
Whether projcetion group view are automatically distributed or not.
Referenced by TechDrawGui::TaskProjGroup::AutoDistributeClicked(), getXYPosition(), mustExecute(), TechDrawGui::TaskProjGroup::restoreGroupState(), TechDrawGui::TaskProjGroup::saveGroupState(), and TechDrawGui::TaskProjGroup::TaskProjGroup().
m_lockScale
bool TechDraw::DrawProjGroup::m_lockScale protected
Referenced by execute(), and onChanged().
ProjectionType
App::PropertyEnumeration TechDraw::DrawProjGroup::ProjectionType
Referenced by arrangeViewPointers(), getViewIndex(), mustExecute(), onChanged(), TechDrawGui::TaskProjGroup::projectionTypeChanged(), TechDrawGui::TaskProjGroup::restoreGroupState(), TechDrawGui::TaskProjGroup::saveGroupState(), TechDrawGui::TaskProjGroup::TaskProjGroup(), and usedProjectionType().
ProjectionTypeEnums
const char * DrawProjGroup::ProjectionTypeEnums static
Initial value:
= {"First Angle",
                                                    "Third Angle",
                                                    "Default",
                                                    nullptr}
Allowed projection types - either Document, First Angle or Third Angle.
Referenced by arrangeViewPointers(), getViewIndex(), and usedProjectionType().
Source
App::PropertyLinkList TechDraw::DrawProjGroup::Source
Referenced by addProjection(), getAllSources(), mustExecute(), onChanged(), TechDrawGui::TaskProjGroup::saveGroupState(), and updateChildrenSource().
spacingX
App::PropertyLength TechDraw::DrawProjGroup::spacingX
Default horizontal spacing between adjacent views on Drawing, in mm.
Referenced by calculateAutomaticScale(), getRect(), getXYPosition(), handleChangedPropertyType(), mustExecute(), onChanged(), TechDrawGui::TaskProjGroup::restoreGroupState(), TechDrawGui::TaskProjGroup::saveGroupState(), TechDrawGui::TaskProjGroup::spacingChanged(), and TechDrawGui::TaskProjGroup::TaskProjGroup().
spacingY
App::PropertyLength TechDraw::DrawProjGroup::spacingY
Default vertical spacing between adjacent views on Drawing, in mm.
Referenced by calculateAutomaticScale(), getRect(), getXYPosition(), handleChangedPropertyType(), mustExecute(), onChanged(), TechDrawGui::TaskProjGroup::restoreGroupState(), TechDrawGui::TaskProjGroup::saveGroupState(), TechDrawGui::TaskProjGroup::spacingChanged(), and TechDrawGui::TaskProjGroup::TaskProjGroup().
XSource
App::PropertyXLinkList TechDraw::DrawProjGroup::XSource
Referenced by addProjection(), getAllSources(), mustExecute(), onChanged(), and updateChildrenSource().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/App/DrawProjGroup.h
FreeCAD/src/Mod/TechDraw/App/DrawProjGroup.cpp