FreeCAD: MeshGui::SoFCMeshPickNode Class Reference
MeshGui::SoFCMeshPickNode Class Reference
#include <SoFCMeshObject.h>
Public Member Functions
void notify (SoNotList *)
virtual void pick (SoPickAction *action)
virtual void rayPick (SoRayPickAction *action)
SoFCMeshPickNode (void)
Static Public Member Functions
static void initClass (void)
Public Attributes
SoSFMeshObject mesh
Protected Member Functions
virtual ~SoFCMeshPickNode ()
Constructor & Destructor Documentation
SoFCMeshPickNode()
SoFCMeshPickNode::SoFCMeshPickNode (void)
Constructor.
~SoFCMeshPickNode()
SoFCMeshPickNode::~SoFCMeshPickNode () protected virtual
Destructor.
Member Function Documentation
initClass()
void SoFCMeshPickNode::initClass (void) static
notify()
void SoFCMeshPickNode::notify (SoNotList * list)
References MeshCore::MeshAlgorithm::GetAverageEdgeLength(), Mesh::MeshObject::getKernel(), and mesh.
pick()
void SoFCMeshPickNode::pick (SoPickAction * action) virtual
References Mesh::MeshObject::getKernel(), mesh, MeshCore::MeshAlgorithm::NearestFacetOnRay(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
rayPick()
void SoFCMeshPickNode::rayPick (SoRayPickAction * action) virtual
Member Data Documentation
mesh
SoSFMeshObject MeshGui::SoFCMeshPickNode::mesh
Referenced by MeshGui::ViewProviderFace::attach(), notify(), pick(), and MengerSponge.MengerThread::run().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCMeshObject.h
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCMeshObject.cpp