FreeCAD: TechDrawGui::Grabber3d Class Reference
TechDrawGui::Grabber3d Class Reference
Utility functions for obtaining 3d window image.
#include <Grabber3d.h>
Static Public Member Functions
static double copyActiveViewToSvgFile (App::Document *appDoc, std::string fileSpec, double outWidth=138.5, double outHeight=95.0, bool paintBackground=true, const QColor &bgcolor=QColor(Qt::white), double lineWidth=1.0, double border=0.0, int mode=0)
static SoSeparator * copySceneGraph (SoNode *sgIn)
static void execVectorizeAction (Gui::View3DInventorViewer *viewer, SoVectorizeAction *va, double width, double height, bool paintBackground, const QColor &bgcolor, double lineWidth, double border)
static double getPaperScale (Gui::View3DInventorViewer *viewer, double pWidth, double pHeight)
static double getViewerScale (Gui::View3DInventorViewer *viewer)
static void postProcessSvg (std::string fileSpec)
Detailed Description
Utility functions for obtaining 3d window image.
Member Function Documentation
copyActiveViewToSvgFile()
double Grabber3d::copyActiveViewToSvgFile (App::Document * appDoc, std::string fileSpec, double outWidth = 138.5, double outHeight = 95.0, bool paintBackground = true, const QColor & bgcolor = QColor(Qt::white), double lineWidth = 1.0, double border = 0.0, int mode = 0) static
References Base::Console(), Base::ConsoleSingleton::Error(), Gui::Document::getActiveView(), Gui::Application::getDocument(), Gui::View3DInventor::getViewer(), Gui::Application::Instance, Base::ConsoleSingleton::Log(), Gui::View3DInventorViewer::setCameraType(), Gui::View3DInventorViewer::setSceneGraph(), OfflineRenderingUtils::viewer(), and Base::ConsoleSingleton::Warning().
Referenced by TechDrawGui::TaskActiveView::createActiveView().
copySceneGraph()
SoSeparator * Grabber3d::copySceneGraph (SoNode * sgIn) static
execVectorizeAction()
void Grabber3d::execVectorizeAction (Gui::View3DInventorViewer * viewer, SoVectorizeAction * va, double width, double height, bool paintBackground, const QColor & bgcolor, double lineWidth, double border) static
References Gui::SoFCVectorizeSVGAction::setBackgroundState(), Gui::SoFCVectorizeSVGAction::setLineWidth(), Gui::SoFCVectorizeSVGAction::setUseMM(), and OfflineRenderingUtils::viewer().
getPaperScale()
double Grabber3d::getPaperScale (Gui::View3DInventorViewer * viewer, double pWidth, double pHeight) static
References Base::Console(), Base::ConsoleSingleton::Log(), and OfflineRenderingUtils::viewer().
getViewerScale()
double Grabber3d::getViewerScale (Gui::View3DInventorViewer * viewer) static
References OfflineRenderingUtils::viewer().
postProcessSvg()
void Grabber3d::postProcessSvg (std::string fileSpec) static
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/Grabber3d.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/Grabber3d.cpp