FreeCAD: QSint::TaskGroup Class Reference
QSint::TaskGroup Class Reference
#include <taskgroup_p.h>
Public Member Functions
bool addActionLabel (ActionLabel *label, bool addToLayout, bool addStretch)
bool addWidget (QWidget *widget, bool addToLayout, bool addStretch)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *scheme)
TaskGroup (QWidget *parent, bool hasHeader=false)
QPixmap transparentRender ()
Protected Member Functions
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
virtual void paintEvent (QPaintEvent *event)
Protected Attributes
bool myHasHeader
ActionPanelScheme * myScheme
Constructor & Destructor Documentation
TaskGroup()
QSint::TaskGroup::TaskGroup (QWidget * parent, bool hasHeader = false)
References QSint::ActionPanelScheme::defaultScheme(), and setScheme().
Member Function Documentation
addActionLabel()
bool QSint::TaskGroup::addActionLabel (ActionLabel * label, bool addToLayout, bool addStretch)
References addWidget().
Referenced by QSint::ActionGroup::addAction(), and QSint::ActionGroup::addActionLabel().
addWidget()
bool QSint::TaskGroup::addWidget (QWidget * widget, bool addToLayout, bool addStretch)
References groupLayout().
Referenced by addActionLabel(), and QSint::ActionGroup::addWidget().
groupLayout()
QBoxLayout * QSint::TaskGroup::groupLayout ()
Referenced by addWidget(), and QSint::ActionGroup::groupLayout().
keyPressEvent()
void QSint::TaskGroup::keyPressEvent (QKeyEvent * event) protected virtual
keyReleaseEvent()
void QSint::TaskGroup::keyReleaseEvent (QKeyEvent * event) protected virtual
paintEvent()
void QSint::TaskGroup::paintEvent (QPaintEvent * event) protected virtual
setScheme()
void QSint::TaskGroup::setScheme (ActionPanelScheme * scheme)
References QSint::ActionPanelScheme::actionStyle, and myScheme.
Referenced by QSint::ActionGroup::setScheme(), and TaskGroup().
transparentRender()
QPixmap QSint::TaskGroup::transparentRender ()
References OfflineRenderingUtils::render().
Referenced by QSint::ActionGroup::showHide().
Member Data Documentation
myHasHeader
bool QSint::TaskGroup::myHasHeader protected
myScheme
ActionPanelScheme* QSint::TaskGroup::myScheme protected
Referenced by setScheme().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/QSint/actionpanel/taskgroup_p.h
FreeCAD/src/Gui/QSint/actionpanel/taskgroup_p.cpp