FreeCAD: Gui::FlagLayout Class Reference
Gui::FlagLayout Class Reference
#include <Flag.h>
Public Types
enum Position { TopLeft , TopRight , BottomLeft , BottomRight }
Public Member Functions
void add (QLayoutItem *item, Position position)
void addItem (QLayoutItem *item)
void addWidget (QWidget *widget, Position position)
int count () const
Qt::Orientations expandingDirections () const
FlagLayout (int spacing=-1)
FlagLayout (QWidget *parent, int margin=0, int spacing=-1)
bool hasHeightForWidth () const
QLayoutItem * itemAt (int index) const
QSize minimumSize () const
void setGeometry (const QRect &rect)
QSize sizeHint () const
QLayoutItem * takeAt (int index)
~FlagLayout ()
Member Enumeration Documentation
Position
enum Gui::FlagLayout::Position
Enumerator
TopLeft
TopRight
BottomLeft
BottomRight
Constructor & Destructor Documentation
FlagLayout() [1/2]
FlagLayout::FlagLayout (QWidget * parent, int margin = 0, int spacing = -1)
FlagLayout() [2/2]
FlagLayout::FlagLayout (int spacing = -1)
~FlagLayout()
FlagLayout::~FlagLayout ()
References takeAt().
Member Function Documentation
add()
void FlagLayout::add (QLayoutItem * item, Position position)
Referenced by addItem(), and addWidget().
addItem()
void FlagLayout::addItem (QLayoutItem * item)
References add(), and TopLeft.
addWidget()
void FlagLayout::addWidget (QWidget * widget, Position position)
References add().
count()
int FlagLayout::count () const
Referenced by importDXF.dxfcounter::incr(), importSVG.svgHandler::startElement(), Mod.Test.BaseTests.ConsoleTestCase::testAsynchronPrintFromThread(), and Mod.Test.BaseTests.ConsoleTestCase::testSynchronPrintFromThread().
expandingDirections()
Qt::Orientations FlagLayout::expandingDirections () const
hasHeightForWidth()
bool FlagLayout::hasHeightForWidth () const
itemAt()
QLayoutItem * FlagLayout::itemAt (int index) const
minimumSize()
QSize FlagLayout::minimumSize () const
setGeometry()
void FlagLayout::setGeometry (const QRect & rect)
References BottomLeft, BottomRight, TopLeft, and TopRight.
sizeHint()
QSize FlagLayout::sizeHint () const
takeAt()
QLayoutItem * FlagLayout::takeAt (int index)
Referenced by ~FlagLayout().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Flag.h
Sources/FreeCAD/src/Gui/Flag.cpp