FreeCAD: Spreadsheet_legacy Namespace Reference
Spreadsheet_legacy Namespace Reference
Classes
class _Command_Spreadsheet_Controller
class _Command_Spreadsheet_Create
class _Command_Spreadsheet_PropertyController
class MathParser
class Spreadsheet
class SpreadsheetController
class SpreadsheetPropertyController
class SpreadsheetView
class ViewProviderSpreadsheet
class ViewProviderSpreadsheetController
class ViewProviderSpreadsheetPropertyController
Functions
def addSpreadsheetView (view)
def export (exportList, filename)
def insert (filename, docname)
def makeSpreadsheet ()
def makeSpreadsheetController (spreadsheet, cell=None, direction=None)
def makeSpreadsheetPropertyController (spreadsheet, object=None, prop=None, cell=None)
def open (filename)
def read (filename)
Variables
bool DEBUG = True
pyopen = open
Function Documentation
addSpreadsheetView()
def Spreadsheet_legacy.addSpreadsheetView (view)
export()
def Spreadsheet_legacy.export (exportList, filename)
References pyopen.
insert()
def Spreadsheet_legacy.insert (filename, docname)
References read().
makeSpreadsheet()
def Spreadsheet_legacy.makeSpreadsheet ()
Referenced by read().
makeSpreadsheetController()
def Spreadsheet_legacy.makeSpreadsheetController (spreadsheet, cell = None, direction = None)
makeSpreadsheetController(spreadsheet,[cell,direction]): adds a
controller to the given spreadsheet. Call can be a starting cell such as "A5",
and direction can be "Horizontal" or "Vertical".
makeSpreadsheetPropertyController()
def Spreadsheet_legacy.makeSpreadsheetPropertyController (spreadsheet, object = None, prop = None, cell = None)
makeSpreadsheetPropertyController(spreadsheet,[object,prop,cell]): adds a
property controller, targeting the given object if any, to the given spreadsheet.
You can give a property (such as "Length" or "Proxy.Length") and a cell address
(such as "B6").
open()
def Spreadsheet_legacy.open (filename)
References read().
read()
def Spreadsheet_legacy.read (filename)
References makeSpreadsheet(), and pyopen.
Referenced by insert(), and open().
Variable Documentation
DEBUG
bool Spreadsheet_legacy.DEBUG = True
pyopen
Spreadsheet_legacy.pyopen = open
Referenced by export(), and read().