FreeCAD: Gui::Dialog::DlgCreateNewPreferencePackImp Class Reference
Gui::Dialog::DlgCreateNewPreferencePackImp Class Reference
A dialog to request a preferencePack name and a set of preferencePack templates.
#include <DlgPreferencePackManagementImp.h>
Public Member Functions
DlgCreateNewPreferencePackImp (QWidget *parent=nullptr)
Constructs a Gui::Dialog::DlgCreateNewPreferencePackImp as a child of 'parent'.
std::string preferencePackName () const
std::vector< PreferencePackManager::TemplateFile > selectedTemplates () const
void setPreferencePackNames (const std::vector< std::string > &usedNames)
void setPreferencePackTemplates (const std::vector< PreferencePackManager::TemplateFile > &availableTemplates)
~DlgCreateNewPreferencePackImp ()
Protected Slots
void accept () override
void on_lineEdit_textEdited (const QString &text)
void onItemChanged (QTreeWidgetItem *item, int column)
Detailed Description
A dialog to request a preferencePack name and a set of preferencePack templates.
Author
Chris Hennes
Constructor & Destructor Documentation
DlgCreateNewPreferencePackImp()
DlgCreateNewPreferencePackImp::DlgCreateNewPreferencePackImp (QWidget * parent = nullptr)
Constructs a Gui::Dialog::DlgCreateNewPreferencePackImp as a child of 'parent'.
References draftgeoutils.intersections::connect(), and onItemChanged().
~DlgCreateNewPreferencePackImp()
DlgCreateNewPreferencePackImp::~DlgCreateNewPreferencePackImp ()
Member Function Documentation
accept
void Gui::Dialog::DlgCreateNewPreferencePackImp::accept () override protected slot
References DraftVecUtils::find().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
on_lineEdit_textEdited
void DlgCreateNewPreferencePackImp::on_lineEdit_textEdited (const QString & text) protected slot
onItemChanged
void DlgCreateNewPreferencePackImp::onItemChanged (QTreeWidgetItem * item, int column) protected slot
Referenced by DlgCreateNewPreferencePackImp().
preferencePackName()
std::string DlgCreateNewPreferencePackImp::preferencePackName () const
selectedTemplates()
std::vector< Gui::PreferencePackManager::TemplateFile > DlgCreateNewPreferencePackImp::selectedTemplates () const
setPreferencePackNames()
void Gui::Dialog::DlgCreateNewPreferencePackImp::setPreferencePackNames (const std::vector< std::string > & usedNames)
setPreferencePackTemplates()
void DlgCreateNewPreferencePackImp::setPreferencePackTemplates (const std::vector< PreferencePackManager::TemplateFile > & availableTemplates)
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgCreateNewPreferencePackImp.h
FreeCAD/src/Gui/DlgCreateNewPreferencePackImp.cpp