FreeCAD: TechDrawGui::TaskSelectLineAttributes Class Reference
TechDrawGui::TaskSelectLineAttributes Class Reference
#include <TaskSelectLineAttributes.h>
Public Member Functions
virtual bool accept ()
virtual bool reject ()
TaskSelectLineAttributes (lineAttributes *ptActiveAttributes)
void updateTask ()
~TaskSelectLineAttributes ()
Protected Member Functions
void changeEvent (QEvent *e)
void setUiEdit (void)
Constructor & Destructor Documentation
TaskSelectLineAttributes()
TaskSelectLineAttributes::TaskSelectLineAttributes (lineAttributes * ptActiveAttributes)
References setUiEdit().
~TaskSelectLineAttributes()
TaskSelectLineAttributes::~TaskSelectLineAttributes ()
Member Function Documentation
accept()
bool TaskSelectLineAttributes::accept (void) virtual
References TechDrawGui::lineAttributes::setStyle().
Referenced by TechDrawGui::TaskDlgSelectLineAttributes::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void TaskSelectLineAttributes::changeEvent (QEvent * e) protected
reject()
bool TaskSelectLineAttributes::reject (void) virtual
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), TechDrawGui::TaskDlgSelectLineAttributes::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
setUiEdit()
void TaskSelectLineAttributes::setUiEdit (void) protected
References TechDrawGui::lineAttributes::getStyle().
Referenced by TaskSelectLineAttributes().
updateTask()
void TaskSelectLineAttributes::updateTask ()
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/TaskSelectLineAttributes.h
FreeCAD/src/Mod/TechDraw/Gui/TaskSelectLineAttributes.cpp