FreeCAD: SMESH_ElementSearcher Struct Reference
SMESH_ElementSearcher Struct Reference abstract
Searcher for elements.
#include <SMESH_MeshAlgos.hxx>
Public Member Functions
virtual const SMDS_MeshElement * FindClosestTo (const gp_Pnt &point, SMDSAbs_ElementType type)=0
Return an element most close to the given point.
virtual int FindElementsByPoint (const gp_Pnt &point, SMDSAbs_ElementType type, std::vector< const SMDS_MeshElement * > &foundElems)=0
Find elements of given type where the given point is IN or ON. Returns nb of found elements and elements them-selves.
virtual void GetElementsNearLine (const gp_Ax1 &line, SMDSAbs_ElementType type, std::vector< const SMDS_MeshElement * > &foundElems)=0
Return elements possibly intersecting the line.
virtual TopAbs_State GetPointState (const gp_Pnt &point)=0
Find out if the given point is out of closed 2D mesh.
virtual ~SMESH_ElementSearcher ()
Implementation of search for the elements by point and of classification of point in 2D mesh.
Detailed Description
Searcher for elements.
Constructor & Destructor Documentation
~SMESH_ElementSearcher()
SMESH_ElementSearcher::~SMESH_ElementSearcher () virtual
Implementation of search for the elements by point and of classification of point in 2D mesh.
Member Function Documentation
FindClosestTo()
virtual const SMDS_MeshElement * SMESH_ElementSearcher::FindClosestTo (const gp_Pnt & point, SMDSAbs_ElementType type) pure virtual
Return an element most close to the given point.
Implemented in SMESH_ElementSearcherImpl.
Referenced by SMESH_MeshEditor::GetHexaFacetsToSplit().
FindElementsByPoint()
virtual int SMESH_ElementSearcher::FindElementsByPoint (const gp_Pnt & point, SMDSAbs_ElementType type, std::vector< const SMDS_MeshElement * > & foundElems) pure virtual
Find elements of given type where the given point is IN or ON. Returns nb of found elements and elements them-selves.
'ALL' type means elements of any type excluding nodes and 0D elements
Implemented in SMESH_ElementSearcherImpl.
GetElementsNearLine()
virtual void SMESH_ElementSearcher::GetElementsNearLine (const gp_Ax1 & line, SMDSAbs_ElementType type, std::vector< const SMDS_MeshElement * > & foundElems) pure virtual
Return elements possibly intersecting the line.
Implemented in SMESH_ElementSearcherImpl.
Referenced by StdMeshers_QuadToTriaAdaptor::CheckIntersection(), StdMeshers_QuadToTriaAdaptor::Compute(), StdMeshers_QuadToTriaAdaptor::Compute2ndPart(), and VISCOUS_3D::_LayerEdge::FindIntersection().
GetPointState()
virtual TopAbs_State SMESH_ElementSearcher::GetPointState (const gp_Pnt & point) pure virtual
Find out if the given point is out of closed 2D mesh.
Implemented in SMESH_ElementSearcherImpl.
Referenced by StdMeshers_QuadToTriaAdaptor::Compute().
The documentation for this struct was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_MeshAlgos.hxx
FreeCAD/src/3rdParty/salomesmesh/src/SMESH/SMESH_MeshAlgos.cpp