FreeCAD: Sandbox::DocumentProtector Class Reference
Sandbox::DocumentProtector Class Reference
#include <DocumentProtector.h>
Public Member Functions
App::DocumentObject * addObject (const std::string &type, const std::string &name="")
DocumentProtector (App::Document *)
void recompute ()
void removeObject (const std::string &name)
~DocumentProtector ()
Public Member Functions inherited from App::DocumentObserver
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
Static Public Member Functions
static void init ()
Additional Inherited Members
Protected Member Functions inherited from App::DocumentObserver
Document * getDocument () const
Constructor & Destructor Documentation
DocumentProtector()
DocumentProtector::DocumentProtector (App::Document * doc)
~DocumentProtector()
DocumentProtector::~DocumentProtector ()
Member Function Documentation
addObject()
App::DocumentObject * DocumentProtector::addObject (const std::string & type, const std::string & name = "")
References App::DocumentObserver::getDocument(), Sandbox::DocumentReceiver::globalInstance(), and Sandbox::DocumentReceiver::postEventAndWait().
Referenced by ArchBuildingPart.BuildingPart::autogroup(), ArchPanel.NestTaskPanel::getContainer(), ArchPanel.NestTaskPanel::getShapes(), Sandbox::DocumentThread::run(), and Sandbox::DocumentTestThread::run().
init()
void DocumentProtector::init (void) static
References Sandbox::DocumentReceiver::globalInstance().
Referenced by DocumentObject.DocumentObject::onChanged().
recompute()
void DocumentProtector::recompute (void)
References App::DocumentObserver::getDocument(), Sandbox::DocumentReceiver::globalInstance(), and Sandbox::DocumentReceiver::postEventAndWait().
Referenced by Sandbox::DocumentThread::run(), Sandbox::DocumentTestThread::run(), draftguitools.gui_trackers.arcTracker::setApertureAngle(), draftguitools.gui_trackers.arcTracker::setEndAngle(), draftguitools.gui_trackers.arcTracker::setStartAngle(), draftguitools.gui_trackers.bsplineTracker::update(), and draftguitools.gui_trackers.bezcurveTracker::update().
removeObject()
void DocumentProtector::removeObject (const std::string & name)
References App::DocumentObserver::getDocument(), Sandbox::DocumentReceiver::globalInstance(), and Sandbox::DocumentReceiver::postEventAndWait().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sandbox/App/DocumentProtector.h
FreeCAD/src/Mod/Sandbox/App/DocumentProtector.cpp