FreeCAD: MyGroupIterator Class Reference
MyGroupIterator Class Reference
Public Member Functions
bool more ()
Return true if and only if there are other object in this iterator.
MyGroupIterator (const SMDS_MeshGroup &group)
const SMDS_MeshElement * next ()
Return the current object and step to the next one.
Public Member Functions inherited from SMDS_Iterator< const SMDS_MeshElement * >
virtual bool more ()=0
Return true if and only if there are other object in this iterator.
virtual const SMDS_MeshElement * next ()=0
Return the current object and step to the next one.
virtual void remove ()
Delete the current element and step to the next one.
virtual ~SMDS_Iterator ()
Provide virtual destructor just for case if some derived iterator must have a destructor.
Constructor & Destructor Documentation
MyGroupIterator()
MyGroupIterator::MyGroupIterator (const SMDS_MeshGroup & group)
References SMDS_MeshGroup::InitIterator().
Member Function Documentation
more()
bool MyGroupIterator::more () virtual
Return true if and only if there are other object in this iterator.
Implements SMDS_Iterator< const SMDS_MeshElement * >.
References SMDS_MeshGroup::More().
next()
const SMDS_MeshElement * MyGroupIterator::next () virtual
Return the current object and step to the next one.
Implements SMDS_Iterator< const SMDS_MeshElement * >.
References SMDS_MeshGroup::Next().
The documentation for this class was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/src/SMESHDS/SMESHDS_Group.cpp