FreeCAD: Part::Feature Class Reference
Part::Feature Class Reference
Base class of all shape feature classes in FreeCAD.
#include <PartFeature.h>
Public Member Functions
Feature (void)
Constructor.
virtual ~Feature ()
Public Member Functions inherited from App::GeoFeature
GeoFeature (void)
Constructor.
virtual std::pair< std::string, std::string > getElementName (const char *name, ElementNameType type=Normal) const
Return the new and old style sub-element name.
virtual const PropertyComplexGeoData * getPropertyOfGeometry () const
This method returns the main property of a geometric object that holds the actual geometry.
virtual PyObject * getPyObject (void)
getPyObject returns the Python binding object
Base::Placement globalPlacement () const
Calculates the placement in the global reference coordinate system.
virtual void transformPlacement (const Base::Placement &transform)
transformPlacement applies transform to placement of this shape.
virtual ~GeoFeature ()
Public Member Functions inherited from App::DocumentObject
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
virtual bool adjustRelativeLinks (const std::set< App::DocumentObject * > &inList, std::set< App::DocumentObject * > *visited=nullptr)
Called to adjust link properties to avoid cyclic links.
virtual bool allowDuplicateLabel () const
virtual bool canLinkProperties () const
virtual int canLoadPartial () const
allow partial loading of dependent objects
void clearExpression (const ObjectIdentifier &path)
void clearOutListCache () const
clear internal out list cache
virtual const char * detachFromDocument () override
DocumentObject (void)
Constructor.
void enforceRecompute ()
Enforce this document object to be recomputed.
App::Document * getDocument (void) const
gets the document in which this Object is handled
std::string getExportName (bool forced=false) const
returns the name that is safe to be exported to other document
virtual const PropertyExpressionEngine::ExpressionInfo getExpression (const ObjectIdentifier &path) const
virtual std::string getFullName () const override
Return the object full name of the form DocName::ObjName.
DocumentObjectGroup * getGroup () const
get group if object is part of a group, otherwise 0 is returned
long getID () const
Return the object ID that is unique within its owner document.
const std::vector< App::DocumentObject * > & getInList (void) const
std::set< App::DocumentObject * > getInListEx (bool recursive) const
Return a set of all objects linking to this object, including possible external parent objects.
void getInListEx (std::set< App::DocumentObject * > &inSet, bool recursive, std::vector< App::DocumentObject * > *inList=nullptr) const
Get a set of all objects linking to this object, including possible external parent objects.
std::vector< App::DocumentObject * > getInListRecursive (void) const
get all objects link directly or indirectly to this object
virtual DocumentObject * getLinkedObject (bool recurse=true, Base::Matrix4D *mat=nullptr, bool transform=false, int depth=0) const
Return the linked object with optional transformation.
const char * getNameInDocument (void) const
returns the name which is set in the document for this object (not the name property!)
const std::string & getOldLabel () const
const std::vector< App::DocumentObject * > & getOutList () const
returns a list of objects this object is pointing to by Links
std::vector< App::DocumentObject * > getOutList (int option) const
void getOutList (int option, std::vector< App::DocumentObject * > &res) const
std::vector< App::DocumentObject * > getOutListOfProperty (App::Property *) const
returns a list of objects linked by the property
std::vector< App::DocumentObject * > getOutListRecursive (void) const
returns a list of objects this object is pointing to by Links and all further descended
std::vector< std::pair< App::DocumentObject *, std::string > > getParents (int depth=0) const
Obtain top parents and subnames of this object using its InList.
std::vector< std::list< App::DocumentObject * > > getPathsByOutList (App::DocumentObject *to) const
get all possible paths from this to another object following the OutList
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
unsigned long getStatus () const
return the status bits
const char * getStatusString (void) const
get the status Message
virtual DocumentObject * getSubObject (const char *subname, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
Get the sub element/object by name.
std::vector< DocumentObject * > getSubObjectList (const char *subname) const
Return a list of objects referenced by a given subname including this object.
virtual std::vector< std::string > getSubObjects (int reason=0) const
Return name reference of all sub-objects.
virtual const char * getViewProviderName (void) const
returns the type name of the ViewProvider
virtual const char * getViewProviderNameOverride () const
This function is introduced to allow Python feature override its view provider.
const char * getViewProviderNameStored () const
virtual bool hasChildElement () const
return true to activate tree view group object handling and element visibility
virtual bool isAttachedToDocument () const override
virtual int isElementVisible (const char *element) const
Get sub-element visibility.
bool isError (void) const
set this feature to error
int isExporting () const
bool isInInList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the InList
bool isInInListRecursive (DocumentObject *objToTest) const
test if this object is in the InList and recursive further down
bool isInOutList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the OutList
bool isInOutListRecursive (DocumentObject *objToTest) const
test if the given object is in the OutList and recursive further down
bool isRecomputing () const
returns true if this objects is currently recomputing
bool isRemoving () const
returns true if this objects is currently removed from the document
bool isRestoring () const
returns true if this objects is currently restoring from file
bool isTouched (void) const
test if this document object is touched
bool isValid (void) const
virtual short mustExecute (void) const
mustExecute We call this method to check if the object was modified to be invoked.
bool mustRecompute (void) const
Test if this document object must be recomputed.
virtual void onBeforeChangeLabel (std::string &newLabel)
virtual void onLostLinkToObject (DocumentObject *)
Called in case of losing a link Get called by the document when a object got deleted a link property of this object ist pointing to.
virtual void onUpdateElementReference (const Property *)
void purgeError (void)
remove the error from the object
void purgeTouched (void)
reset this document object touched
bool recomputeFeature (bool recursive=false)
Recompute only this feature.
virtual bool redirectSubName (std::ostringstream &ss, DocumentObject *topParent, DocumentObject *child) const
Allow object to redirect a subname path.
virtual bool removeDynamicProperty (const char *prop) override
virtual void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths)
App::DocumentObject * resolve (const char *subname, App::DocumentObject **parent=nullptr, std::string *childName=nullptr, const char **subElement=nullptr, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
Resolve the last document object referenced in the subname.
App::DocumentObject * resolveRelativeLink (std::string &subname, App::DocumentObject *&link, std::string &linkSub) const
Resolve a link reference that is relative to this object reference.
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
virtual int setElementVisible (const char *element, bool visible)
Child element handling.
virtual void setExpression (const ObjectIdentifier &path, std::shared_ptr< App::Expression > expr)
void setStatus (ObjectStatus pos, bool on)
bool testIfLinkDAGCompatible (App::PropertyLinkSub &linkTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSubList &linksTo) const
bool testIfLinkDAGCompatible (const std::vector< DocumentObject * > &linksTo) const
bool testIfLinkDAGCompatible (DocumentObject *linkTo) const
testIfLinkIsDAG tests a link that is about to be created for circular references.
bool testStatus (ObjectStatus pos) const
void touch (bool noRecompute=false)
Set the property touched -> changed, cause recomputation in Update()
virtual ~DocumentObject ()
Public Member Functions inherited from App::TransactionalObject
virtual const char * detachFromDocument ()
virtual bool isAttachedToDocument () const
TransactionalObject (void)
Constructor.
virtual ~TransactionalObject ()
Public Member Functions inherited from App::ExtensionContainer
ExtensionIterator extensionBegin ()
ExtensionContainer ()
ExtensionIterator extensionEnd ()
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
void registerExtension (Base::Type extension, App::Extension *ext)
virtual ~ExtensionContainer ()
virtual Property * getPropertyByName (const char *name) const override
find a property by its name
virtual const char * getPropertyName (const Property *prop) const override
get the name of a property
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
virtual void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
virtual short getPropertyType (const Property *prop) const override
get the Type of a Property
virtual short getPropertyType (const char *name) const override
get the Type of a named Property
virtual const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
virtual void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
Public Member Functions inherited from App::PropertyContainer
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false)
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual void editProperty (const char *)
virtual App::Property * getDynamicPropertyByName (const char *name) const
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual std::string getFullName () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Property * getPropertyByName (const char *name) const
find a property by its name
virtual const char * getPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * getPropertyGroup (const Property *prop) const
get the Group of a Property
virtual void getPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual const char * getPropertyName (const Property *prop) const
get the name of a property
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
const char * getPropertyPrefix () const
virtual short getPropertyType (const char *name) const
get the Type of a named Property
virtual short getPropertyType (const Property *prop) const
get the Type of a Property
bool isHidden (const char *name) const
check if the named property is hidden
bool isHidden (const Property *prop) const
check if the property is hidden
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isReadOnly (const Property *prop) const
check if the property is read-only
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus)
PropertyContainer ()
A constructor.
virtual bool removeDynamicProperty (const char *name)
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
void setPropertyPrefix (const char *prefix)
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
virtual ~PropertyContainer ()
A destructor.
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Attributes
PropertyPartShape Shape
Public Attributes inherited from App::GeoFeature
PropertyPlacement Placement
Public Attributes inherited from App::DocumentObject
PropertyExpressionEngine ExpressionEngine
PropertyString Label
PropertyString Label2
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChange
signal before changing a property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChanged
signal on changed property of this object
PropertyBool Visibility
Allow control visibility status in App name space.
methods override feature
virtual short mustExecute () const override
mustExecute We call this method to check if the object was modified to be invoked.
virtual const char * getViewProviderName () const override
returns the type name of the ViewProvider
virtual const App::PropertyComplexGeoData * getPropertyOfGeometry () const override
This method returns the main property of a geometric object that holds the actual geometry.
virtual PyObject * getPyObject () override
getPyObject returns the Python binding object
TopLoc_Location getLocation () const
virtual DocumentObject * getSubObject (const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const override
Get the sub element/object by name.
static TopoDS_Shape getShape (const App::DocumentObject *obj, const char *subname=nullptr, bool needSubElement=false, Base::Matrix4D *pmat=nullptr, App::DocumentObject **owner=nullptr, bool resolveLink=true, bool transform=true)
Convenience function to extract shape from fully qualified subname.
static TopoShape getTopoShape (const App::DocumentObject *obj, const char *subname=nullptr, bool needSubElement=false, Base::Matrix4D *pmat=nullptr, App::DocumentObject **owner=nullptr, bool resolveLink=true, bool transform=true, bool noElementMap=false)
static void clearShapeCache ()
static App::DocumentObject * getShapeOwner (const App::DocumentObject *obj, const char *subname=nullptr)
static bool hasShapeOwner (const App::DocumentObject *obj, const char *subname=nullptr)
virtual App::DocumentObjectExecReturn * recompute () override
recompute only this object
virtual App::DocumentObjectExecReturn * execute () override
recalculate the feature
virtual void onChanged (const App::Property *prop) override
get called by the container when a property was changed
ShapeHistory buildHistory (BRepBuilderAPI_MakeShape &, TopAbs_ShapeEnum type, const TopoDS_Shape &newS, const TopoDS_Shape &oldS)
Build a history of changes MakeShape: The operation that created the changes, e.g.
ShapeHistory joinHistory (const ShapeHistory &, const ShapeHistory &)
Additional Inherited Members
Public Types inherited from App::GeoFeature
enum ElementNameType { Normal =0 , Import =1 , Export =2 }
Specify the type of element name to return when calling getElementName()
Public Types inherited from App::DocumentObject
enum GSReason { GS_DEFAULT , GS_SELECT }
reason of calling getSubObjects()
enum OutListOption { OutListNoExpression = 1 , OutListNoHidden = 2 , OutListNoXLinked = 4 }
DAG handling This part of the interface deals with viewing the document as a DAG (directed acyclic graph).
Public Types inherited from App::ExtensionContainer
typedef std::map< Base::Type, App::Extension * >::iterator ExtensionIterator
Static Public Member Functions inherited from App::GeoFeature
static DocumentObject * resolveElement (App::DocumentObject *obj, const char *subname, std::pair< std::string, std::string > &elementName, bool append=false, ElementNameType type=Normal, const DocumentObject *filter=nullptr, const char **element=nullptr, GeoFeature **geo=nullptr)
Resolve both the new and old style element name.
Static Public Member Functions inherited from App::DocumentObject
static const char * hasHiddenMarker (const char *subname)
Check if the subname reference ends with hidden marker.
static const std::string & hiddenMarker ()
Special marker to mark the object as hidden.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Public Attributes inherited from App::DocumentObject
static DocumentObjectExecReturn * StdReturn
Protected Member Functions inherited from App::DocumentObject
virtual App::DocumentObjectExecReturn * execute (void)
get called by the document to recompute this feature Normally this method get called in the processing of Document::recompute().
App::DocumentObjectExecReturn * executeExtensions ()
Executes the extensions of a document object.
virtual void onBeforeChange (const Property *prop) override
get called before the value is changed
virtual void onChanged (const Property *prop) override
get called by the container when a property was changed
virtual void onDocumentRestored ()
get called after a document has been fully restored
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus) override
get called when a property status has changed
virtual void onSettingDocument ()
get called after setting the document
virtual void onUndoRedoFinished ()
get called after an undo/redo transaction is finished
virtual App::DocumentObjectExecReturn * recompute (void)
recompute only this object
void resetError (void)
void setDocument (App::Document *doc)
void setError (void)
virtual void setupObject ()
get called after a brand new object was created
virtual void unsetupObject ()
get called when object is going to be removed from the document
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData (void) const
virtual void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container.
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
virtual void onBeforeChange (const Property *)
get called before the value is changed
virtual void onChanged (const Property *)
get called by the container when a property has changed
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::DocumentObject
std::string oldLabel
Old label; used for renaming expressions.
const std::string * pcNameInDocument
Py::SmartPtr PythonObject
python object of this class and all descendent
std::bitset< 32 > StatusBits
Status bits of the document object The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Detailed Description
Base class of all shape feature classes in FreeCAD.
Constructor & Destructor Documentation
Feature()
Feature::Feature (void)
Constructor.
~Feature()
Feature::~Feature () virtual
Member Function Documentation
buildHistory()
ShapeHistory Feature::buildHistory (BRepBuilderAPI_MakeShape & mkShape, TopAbs_ShapeEnum type, const TopoDS_Shape & newS, const TopoDS_Shape & oldS) protected
Build a history of changes MakeShape: The operation that created the changes, e.g.
BRepAlgoAPI_Common type: The type of object we are interested in, e.g. TopAbs_FACE newS: The new shape that was created by the operation oldS: The original shape prior to the operation
References Part::ShapeHistory::shapeMap, and Part::ShapeHistory::type.
Referenced by Part::Chamfer::execute(), Part::Fillet::execute(), Part::Boolean::execute(), Part::MultiCommon::execute(), and Part::MultiFuse::execute().
clearShapeCache()
void Feature::clearShapeCache () static
References ShapeCache::cache.
execute()
App::DocumentObjectExecReturn * Feature::execute (void) override protected virtual
recalculate the feature
Reimplemented from App::DocumentObject.
Reimplemented in PartDesign::Pad, PartDesign::Pocket, PartDesign::FeaturePrimitive, Drawing::FeatureProjection, Part::CustomFeature, Part::Chamfer, Part::Compound, Part::Fillet, Part::FeatureGeometrySet, Part::Mirroring, Part::Boolean, Part::Box, Part::Circle, Part::MultiCommon, Part::CurveNet, Part::MultiFuse, Part::ImportBrep, Part::ImportIges, Part::ImportStep, Part::Polygon, Part::RuledSurface, Part::Loft, Part::Sweep, Part::Thickness, Part::Refine, Part::Reverse, Part::Vertex, Part::Line, Part::Plane, Part::Sphere, Part::Ellipsoid, Part::Cylinder, Part::Prism, Part::RegularPolygon, Part::Cone, Part::Torus, Part::Helix, Part::Spiral, Part::Wedge, Part::Ellipse, PartDesign::FeatureBase, PartDesign::Draft, PartDesign::Fillet, PartDesign::Groove, PartDesign::Helix, PartDesign::Hole, PartDesign::Loft, PartDesign::Pipe, PartDesign::Box, PartDesign::Cylinder, PartDesign::Sphere, PartDesign::Cone, PartDesign::Ellipsoid, PartDesign::Torus, PartDesign::Prism, PartDesign::Wedge, PartDesign::Revolution, PartDesign::Thickness, PartDesign::Transformed, Path::FeatureArea, Path::FeatureAreaView, Sketcher::SketchObjectSF, Surface::Cut, Surface::Filling, Surface::GeomFillSurface, Surface::Sewing, TechDraw::FeatureProjection, Part::Extrusion, Part::Face, Part::Offset, Part::Offset2D, Part::Revolution, Part::Part2DObject, Part::Primitive, PartDesign::Body, PartDesign::Boolean, PartDesign::Chamfer, PartDesign::ShapeBinder, PartDesign::SubShapeBinder, Sketcher::SketchObject, Surface::Extend, and Surface::Sections.
References Shape, and App::Property::touch().
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), PathScripts.PathDressupDogbone.ObjectDressup::boneStateList(), ArchSite.Compass::buildCoordinates(), PartDesign::FeaturePrimitive::execute(), Part::Part2DObject::execute(), Part::Primitive::execute(), PartDesign::ShapeBinder::execute(), PartDesign::SubShapeBinder::execute(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::generateTags(), ArchPanel.PanelCut::getWires(), ArchSchedule.CommandArchSchedule::IsActive(), Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), FeaturePython.DistanceBolt::onChanged(), PathScripts.PathStock.StockFromBase::onChanged(), PathScripts.PathStock.StockCreateBox::onChanged(), PathScripts.PathStock.StockCreateCylinder::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), draftobjects.patharray.PathArray::onDocumentRestored(), and draftobjects.pathtwistedarray.PathTwistedArray::onDocumentRestored().
getLocation()
TopLoc_Location Feature::getLocation (void) const
References DraftVecUtils::angle(), Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Rotation::getValue(), App::PropertyPlacement::getValue(), App::GeoFeature::Placement, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by PartDesign::Pad::execute(), PartDesign::Pocket::execute(), PartDesign::FeaturePrimitive::execute(), PartDesign::Groove::execute(), PartDesign::Helix::execute(), PartDesign::Hole::execute(), PartDesign::Loft::execute(), PartDesign::Pipe::execute(), PartDesign::Revolution::execute(), PartDesign::Transformed::execute(), PartDesign::Helix::generateHelixPath(), PartDesign::DressUp::getAddSubShape(), PartDesign::LinearPattern::getTransformations(), PartDesign::Mirrored::getTransformations(), PartDesign::PolarPattern::getTransformations(), and Sketcher::SketchObject::split().
getPropertyOfGeometry()
const App::PropertyComplexGeoData * Feature::getPropertyOfGeometry () const override virtual
This method returns the main property of a geometric object that holds the actual geometry.
For a part object this is the Shape property, for a mesh object the Mesh property and so on. The default implementation returns null.
Reimplemented from App::GeoFeature.
References Shape.
getPyObject()
PyObject * Feature::getPyObject (void) override virtual
getPyObject returns the Python binding object
Returns
the Python binding object
Reimplemented from App::GeoFeature.
Reimplemented in Part::BodyBase, Part::Primitive, PartDesign::FeaturePrimitive, PartDesign::Feature, Path::FeatureArea, PartDesign::Body, and Sketcher::SketchObject.
References App::DocumentObject::PythonObject.
Referenced by Part::ImportStepParts().
getShape()
TopoDS_Shape Feature::getShape (const App::DocumentObject * obj, const char * subname = nullptr, bool needSubElement = false, Base::Matrix4D * pmat = nullptr, App::DocumentObject ** owner = nullptr, bool resolveLink = true, bool transform = true) static
Convenience function to extract shape from fully qualified subname.
Parameters
obj the parent object
subname dot separated full qualified subname
needSubElement whether to ignore the non-object subelement reference inside subname
pmat used as current transformation on input, and return the accumulated transformation on output
owner return the owner of the shape returned
resolveLink if true, resolve link(s) of the returned 'owner' by calling its getLinkedObject(true) function
transform if true, apply obj's transformation. Set to false if pmat already include obj's transformation matrix.
References Part::TopoShape::getShape(), and getTopoShape().
Referenced by Part::Extrusion::calculateShapeNormal(), PartGui::evaluateAngularPreSelection(), PartGui::evaluateLinearPreSelection(), Part::Chamfer::execute(), Part::Compound::execute(), Part::Fillet::execute(), Part::Mirroring::execute(), Part::Boolean::execute(), Part::MultiCommon::execute(), Part::MultiFuse::execute(), Part::Loft::execute(), Part::Sweep::execute(), Part::Reverse::execute(), Part::Extrusion::execute(), Part::Face::execute(), Part::Offset::execute(), Part::Revolution::execute(), Part::Extrusion::fetchAxisLink(), Part::Revolution::fetchAxisLink(), TechDrawGui::DrawGuiUtil::getProjDirFromFace(), Measure::Measurement::getShape(), PartGui::getShapeFromStrings(), TechDraw::ShapeExtractor::getShapes(), PartDesign::Scaled::getTransformations(), Measure::Measurement::getType(), TechDraw::ShapeExtractor::getXShapes(), PartGui::TaskCheckGeometryResults::goCheck(), and PartGui::ViewProviderPartExt::updateVisual().
getShapeOwner()
App::DocumentObject * Feature::getShapeOwner (const App::DocumentObject * obj, const char * subname = nullptr) static
References App::DocumentObject::getLinkedObject(), and App::DocumentObject::getSubObject().
Referenced by PartDesignGui::ReferenceSelection::allow(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderMultiFuse::updateData(), PartGui::ViewProviderMultiCommon::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderFillet::updateData(), and PartGui::ViewProviderChamfer::updateData().
getSubObject()
App::DocumentObject * Feature::getSubObject (const char * subname, PyObject ** pyObj, Base::Matrix4D * mat, bool transform, int depth) const override virtual
Get the sub element/object by name.
Parameters
subname a string which is dot separated name to refer to a sub element or object. An empty string can be used to refer to the object itself
pyObj if non zero, returns the python object corresponding to this sub object. The actual type of this python object is implementation dependent. For example, The current implementation of Part::Feature will return the TopoShapePy, event if there is no sub-element reference, in which case it returns the whole shape.
mat If non zero, it is used as the current transformation matrix on input. And output as the accumulated transformation up until and include the transformation applied by the final object reference in subname. For Part::Feature, the transformation is applied to the TopoShape inside pyObj before returning.
transform if false, then it will not apply the object's own transformation to mat, which lets you override the object's placement (and possibly scale).
depth depth limitation as hint for cyclic link detection
Returns
The last document object referred in subname. If subname is empty, then it shall return itself. If subname is invalid, then it shall return zero.
Reimplemented from App::DocumentObject.
Reimplemented in Part::Datum, PartDesign::Body, PartDesign::CoordinateSystem, and PartDesign::SubShapeBinder.
References App::GetApplication(), ParameterGrp::GetBool(), App::DocumentObject::getFullName(), App::Application::GetParameterGroupByPath(), Part::PropertyPartShape::getShape(), App::DocumentObject::getSubObject(), App::PropertyPlacement::getValue(), Part::TopoShape::hasSubShape(), Data::ComplexGeoData::isMappedElement(), App::GeoFeature::Placement, Shape, Part::shape2pyshape(), and Base::Placement::toMatrix().
Referenced by PartDesign::Body::getSubObject(), and PartDesign::SubShapeBinder::getSubObject().
getTopoShape()
TopoShape Feature::getTopoShape (const App::DocumentObject * obj, const char * subname = nullptr, bool needSubElement = false, Base::Matrix4D * pmat = nullptr, App::DocumentObject ** owner = nullptr, bool resolveLink = true, bool transform = true, bool noElementMap = false) static
Referenced by MeshPartGui::Tessellation::accept(), PartGui::SweepWidget::accept(), PartGui::DlgExtrusion::EdgeSelection::allow(), PartGui::DlgRevolution::EdgeSelection::allow(), PartGui::SweepWidget::Private::EdgeSelection::allow(), PartGui::CrossSections::apply(), PartGui::DlgExtrusion::apply(), Part::Sweep::execute(), Part::Thickness::execute(), Part::Offset2D::execute(), Part::Extrusion::fetchAxisLink(), Part::Revolution::fetchAxisLink(), PartGui::DlgExtrusion::findShapes(), PartGui::ViewProviderPartExt::getModelPoints(), PartDesign::ProfileBased::getProfileShape(), getShape(), PartGui::getShapesFromSelection(), PartGui::hasShapesInSelection(), Import::ImportOCAF2::loadShapes(), PartDesign::SubShapeBinder::update(), and MeshPartGui::Mesh2ShapeGmsh::writeProject().
getViewProviderName()
const char * Feature::getViewProviderName (void) const override virtual
returns the type name of the ViewProvider
Reimplemented from App::DocumentObject.
Reimplemented in PartDesign::Feature, PartDesign::FeatureBase, PartDesign::Pad, Part::CustomFeature, Part::Chamfer, Part::Compound, Part::Fillet, Part::FeatureGeometrySet, Part::Mirroring, Part::Boolean, Part::Box, Part::Circle, Part::MultiCommon, Part::CurveNet, Part::MultiFuse, Part::ImportBrep, Part::ImportIges, Part::ImportStep, Part::Spline, Part::FeatureExt, Part::RuledSurface, Part::Loft, Part::Sweep, Part::Thickness, Part::Refine, Part::Reverse, Part::Vertex, Part::Line, Part::Plane, Part::Sphere, Part::Ellipsoid, Part::Cylinder, Part::Prism, Part::RegularPolygon, Part::Cone, Part::Torus, Part::Helix, Part::Spiral, Part::Wedge, Part::Ellipse, PartDesign::Line, PartDesign::Plane, PartDesign::Draft, PartDesign::Fillet, PartDesign::Groove, PartDesign::Helix, PartDesign::Hole, PartDesign::LinearPattern, PartDesign::Loft, PartDesign::Mirrored, PartDesign::MultiTransform, PartDesign::Pipe, PartDesign::Pocket, PartDesign::PolarPattern, PartDesign::Revolution, PartDesign::Scaled, PartDesign::Thickness, Path::FeatureArea, Path::FeatureAreaView, Surface::Filling, Surface::GeomFillSurface, Part::Extrusion, Part::Face, Part::Offset, Part::Offset2D, Part::Revolution, Part::Part2DObject, PartDesign::Body, PartDesign::CoordinateSystem, PartDesign::Point, PartDesign::Boolean, PartDesign::Chamfer, PartDesign::FeaturePrimitive, PartDesign::ShapeBinder, PartDesign::SubShapeBinder, Sketcher::SketchObject, Surface::Extend, Surface::Sections, and Part::Datum.
hasShapeOwner()
static bool Part::Feature::hasShapeOwner (const App::DocumentObject * obj, const char * subname = nullptr) static
joinHistory()
ShapeHistory Feature::joinHistory (const ShapeHistory & oldH, const ShapeHistory & newH) protected
References Part::ShapeHistory::shapeMap, and Part::ShapeHistory::type.
Referenced by Part::Boolean::execute(), Part::MultiCommon::execute(), and Part::MultiFuse::execute().
mustExecute()
short Feature::mustExecute () const override virtual
mustExecute We call this method to check if the object was modified to be invoked.
If the object label or an argument is modified. If we must recompute the object - to call the method execute(). 0: no recomputation is needed 1: recomputation needed
Remarks
If an object is marked as 'touched' then this does not necessarily mean that it will be recomputed. It only means that all objects that link it (i.e. its InList) will be recomputed.
Reimplemented from App::DocumentObject.
Reimplemented in Part::Compound, Part::Mirroring, Part::Boolean, Part::Box, Part::Circle, Part::MultiCommon, Part::CurveNet, Part::MultiFuse, Part::ImportBrep, Part::ImportIges, Part::ImportStep, Part::Polygon, Part::Section, Part::FilletBase, Part::RuledSurface, Part::Loft, Part::Sweep, Part::Thickness, Part::Vertex, Part::Line, Part::Plane, Part::Sphere, Part::Ellipsoid, Part::Cylinder, Part::Prism, Part::RegularPolygon, Part::Cone, Part::Torus, Part::Helix, Part::Spiral, Part::Wedge, Part::Ellipse, PartDesign::Feature, PartDesign::Draft, PartDesign::DressUp, PartDesign::FeatureExtrude, PartDesign::Fillet, PartDesign::Groove, PartDesign::Helix, PartDesign::Hole, PartDesign::LinearPattern, PartDesign::Loft, PartDesign::Mirrored, PartDesign::MultiTransform, PartDesign::Pipe, PartDesign::PolarPattern, PartDesign::Box, PartDesign::Cylinder, PartDesign::Sphere, PartDesign::Cone, PartDesign::Ellipsoid, PartDesign::Torus, PartDesign::Prism, PartDesign::Wedge, PartDesign::Revolution, PartDesign::Scaled, PartDesign::ProfileBased, PartDesign::Thickness, PartDesign::Transformed, Sketcher::SketchObjectSF, Surface::Cut, Surface::Filling, Surface::GeomFillSurface, Surface::Sewing, Part::Extrusion, Part::Face, Part::Offset, Part::Offset2D, Part::Revolution, Part::Primitive, PartDesign::Body, PartDesign::FeatureAddSub, PartDesign::Boolean, PartDesign::Chamfer, Sketcher::SketchObject, Surface::Extend, Part::CustomFeature, PartDesign::FeatureBase, Path::FeatureArea, and PartDesign::ShapeBinder.
Referenced by SurfaceGui::SectionsPanel::accept(), Part::Circle::mustExecute(), PartDesign::Feature::mustExecute(), Part::Face::mustExecute(), Part::Primitive::mustExecute(), PartDesign::Body::mustExecute(), Part::CustomFeature::mustExecute(), PartDesign::FeatureBase::mustExecute(), Path::FeatureArea::mustExecute(), and PartDesign::ShapeBinder::mustExecute().
onChanged()
void Feature::onChanged (const App::Property * prop) override protected virtual
get called by the container when a property was changed
Reimplemented from App::DocumentObject.
Reimplemented in Part::Circle, Part::Vertex, Part::Line, Part::Ellipse, Surface::GeomFillSurface, PartDesign::Chamfer, Sketcher::SketchObject, Part::Mirroring, Part::Box, Part::RuledSurface, Part::Loft, Part::Sweep, Part::Helix, Part::Spiral, Part::Wedge, PartDesign::Line, PartDesign::Plane, PartDesign::FeatureBase, PartDesign::DressUp, PartDesign::Helix, PartDesign::Hole, PartDesign::ProfileBased, Part::BodyBase, Part::Revolution, Part::Primitive, PartDesign::Body, PartDesign::Point, PartDesign::Boolean, PartDesign::FeaturePrimitive, PartDesign::ShapeBinder, PartDesign::SubShapeBinder, and Surface::Extend.
References Base::Placement::fromMatrix(), Part::PropertyPartShape::getShape(), Part::TopoShape::getTransform(), App::PropertyPlacement::getValue(), Part::PropertyPartShape::getValue(), App::DocumentObject::isRecomputing(), App::GeoFeature::Placement, Part::PropertyPartShape::setTransform(), App::PropertyPlacement::setValue(), Shape, and Base::Placement::toMatrix().
Referenced by ArchStructure.CommandStructuralSystem::Activated(), draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSite.Compass::buildCoordinates(), draftobjects.wire.Wire::execute(), Part::Circle::onChanged(), Surface::GeomFillSurface::onChanged(), Sketcher::SketchObject::onChanged(), Part::Mirroring::onChanged(), Part::RuledSurface::onChanged(), Part::Loft::onChanged(), Part::Sweep::onChanged(), PartDesign::FeatureBase::onChanged(), PartDesign::DressUp::onChanged(), PartDesign::ProfileBased::onChanged(), Part::BodyBase::onChanged(), Part::Revolution::onChanged(), Part::Primitive::onChanged(), PartDesign::Point::onChanged(), PartDesign::Boolean::onChanged(), PartDesign::FeaturePrimitive::onChanged(), PartDesign::ShapeBinder::onChanged(), PartDesign::SubShapeBinder::onChanged(), Surface::Extend::onChanged(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchPanel.ViewProviderPanelSheet::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), and draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData().
recompute()
App::DocumentObjectExecReturn * Feature::recompute (void) override protected virtual
recompute only this object
Reimplemented from App::DocumentObject.
References App::DocumentObject::recompute(), and App::DocumentObjectExecReturn::Why.
Referenced by Part::Circle::onChanged(), Part::Vertex::onChanged(), Part::Line::onChanged(), Part::Ellipse::onChanged(), Part::Mirroring::onChanged(), Part::Box::onChanged(), Part::Helix::onChanged(), Part::Spiral::onChanged(), Part::Wedge::onChanged(), Part::Primitive::onChanged(), draftguitools.gui_trackers.arcTracker::setApertureAngle(), draftguitools.gui_trackers.arcTracker::setEndAngle(), draftguitools.gui_trackers.arcTracker::setStartAngle(), draftguitools.gui_trackers.bsplineTracker::update(), and draftguitools.gui_trackers.bezcurveTracker::update().
Member Data Documentation
Shape
PropertyPartShape Part::Feature::Shape
Referenced by ReverseEngineeringGui::Segmentation::accept(), DraftUtils::DraftDxfRead::AddGraphics(), Import::ImpExpDxfRead::AddGraphics(), DraftUtils::DraftDxfRead::AddObject(), Import::ImpExpDxfRead::AddObject(), PartGui::DlgProjectionOnSurface::EdgeSelection::allow(), PartGui::DlgProjectionOnSurface::FaceSelection::allow(), PartGui::CrossSections::apply(), PartDesign::ShapeBinder::buildShapeFromReferences(), Surface::GeomFillSurface::createFace(), PartDesign::Pad::execute(), PartDesign::Pocket::execute(), execute(), PartDesign::FeaturePrimitive::execute(), Drawing::FeatureProjection::execute(), Fem::FemMeshShapeNetgenObject::execute(), Fem::FemMeshShapeObject::execute(), Inspection::Feature::execute(), Part::Chamfer::execute(), Part::Compound::execute(), Part::Fillet::execute(), Part::FeatureGeometrySet::execute(), Part::Mirroring::execute(), Part::Boolean::execute(), Part::Box::execute(), Part::Circle::execute(), Part::MultiCommon::execute(), Part::CurveNet::execute(), Part::MultiFuse::execute(), Part::ImportBrep::execute(), Part::ImportIges::execute(), Part::ImportStep::execute(), Part::RuledSurface::execute(), Part::Loft::execute(), Part::Sweep::execute(), Part::Thickness::execute(), Part::Refine::execute(), Part::Reverse::execute(), Part::Vertex::execute(), Part::Line::execute(), Part::Plane::execute(), Part::Sphere::execute(), Part::Ellipsoid::execute(), Part::Cylinder::execute(), Part::Prism::execute(), Part::RegularPolygon::execute(), Part::Cone::execute(), Part::Torus::execute(), Part::Helix::execute(), Part::Spiral::execute(), Part::Wedge::execute(), Part::Ellipse::execute(), PartDesign::FeatureBase::execute(), PartDesign::Fillet::execute(), PartDesign::Groove::execute(), PartDesign::Helix::execute(), PartDesign::Hole::execute(), PartDesign::Loft::execute(), PartDesign::Pipe::execute(), PartDesign::Revolution::execute(), PartDesign::Thickness::execute(), PartDesign::Transformed::execute(), Path::FeatureArea::execute(), Path::FeatureAreaView::execute(), Path::FeatureShape::execute(), Surface::Cut::execute(), Surface::Filling::execute(), Surface::Sewing::execute(), TechDraw::FeatureProjection::execute(), Part::Extrusion::execute(), Part::Face::execute(), Part::Offset::execute(), Part::Offset2D::execute(), Part::Revolution::execute(), PartDesign::Body::execute(), PartDesign::Boolean::execute(), PartDesign::Chamfer::execute(), PartDesign::ShapeBinder::execute(), Sketcher::SketchObject::execute(), Surface::Extend::execute(), Surface::Sections::execute(), PartDesign::DressUp::getAddSubShape(), PartDesign::ProfileBased::getAxis(), Fem::Constraint::getBasePoint(), PartDesign::Feature::getBaseShape(), PartDesign::Feature::getBaseTopoShape(), Fem::Constraint::getCylinder(), Fem::Constraint::getDirection(), TechDraw::ShapeExtractor::getLocation3dFromFeat(), Sketcher::SketchAnalysis::getOpenVertices(), Fem::Constraint::getPoints(), PartDesign::ProfileBased::getProfileWires(), getPropertyOfGeometry(), Part::Datum::getShape(), TechDraw::ShapeExtractor::getShapes2d(), TechDraw::ShapeExtractor::getShapesFromObject(), getSubObject(), PartDesign::ProfileBased::getSupportFace(), PartDesign::LinearPattern::getTransformations(), PartDesign::Mirrored::getTransformations(), PartDesign::PolarPattern::getTransformations(), PartDesign::ProfileBased::getUpToFaceFromLinkSub(), PartDesign::ProfileBased::getVerifiedFace(), Surface::GeomFillSurface::getWire(), Part::ImportIgesParts(), Part::ImportStepParts(), Import::ImportOCAF2::loadShapes(), PartDesignGui::TaskFeaturePick::makeCopy(), Fem::Constraint::onChanged(), Fem::ConstraintBearing::onChanged(), Part::Box::onChanged(), PartDesign::DressUp::onChanged(), onChanged(), PartDesign::Point::onChanged(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), FemGui::TaskFemConstraintGear::onSelectionChanged(), SurfaceGui::FillingPanel::open(), Import::ExportOCAF::reallocateFreeShape(), Sketcher::SketchObject::rebuildExternalGeometry(), PartDesign::ProfileBased::remapSupportShape(), Part::Box::Restore(), Sketcher::SketchObject::restoreFinished(), Import::ExportOCAF::saveShape(), PartGui::SectionCut::SectionCut(), PartGui::ViewProviderMirror::setEdit(), PartDesign::SubShapeBinder::setLinks(), Path::Area::showShape(), PartDesignGui::ViewProviderBody::slotChangedObjectApp(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), PartDesign::SubShapeBinder::update(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderMultiFuse::updateData(), PartGui::ViewProviderMultiCommon::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderFillet::updateData(), PartGui::ViewProviderChamfer::updateData(), and Sketcher::SketchObject::validateExternalLinks().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/App/PartFeature.h
FreeCAD/src/Mod/Part/App/PartFeature.cpp