FreeCAD: Gui::Dialog::DlgSettingsColorGradientImp Class Reference
Gui::Dialog::DlgSettingsColorGradientImp Class Reference
The DlgSettingsColorGradientImp class implements a preference page to change settings for the color gradient bar.
#include <DlgSettingsColorGradientImp.h>
Public Member Functions
void accept ()
DlgSettingsColorGradientImp (QWidget *parent=0, Qt::WindowFlags fl=Qt::WindowFlags())
Constructs a DlgSettingsColorGradientImp as a child of 'parent', with the name 'name' and widget flags set to 'f'.
~DlgSettingsColorGradientImp ()
Destroys the object and frees any allocated resources.
Color model
void setColorModel (App::ColorGradient::TColorModel tModel)
App::ColorGradient::TColorModel colorModel () const
Color style
void setColorStyle (App::ColorGradient::TStyle tStyle)
App::ColorGradient::TStyle colorStyle () const
Display mode
void setOutGrayed (bool grayed)
bool isOutGrayed () const
void setOutInvisible (bool invisible)
bool isOutInvisible () const
Parameter range and scale
void setRange (float fMin, float fMax)
void getRange (float &fMin, float &fMax) const
void setNumberOfLabels (int)
int numberOfLabels () const
void setNumberOfDecimals (int)
int numberOfDecimals () const
Detailed Description
The DlgSettingsColorGradientImp class implements a preference page to change settings for the color gradient bar.
Author
Werner Mayer
Constructor & Destructor Documentation
DlgSettingsColorGradientImp()
DlgSettingsColorGradientImp::DlgSettingsColorGradientImp (QWidget * parent = 0, Qt::WindowFlags fl = Qt::WindowFlags())
Constructs a DlgSettingsColorGradientImp as a child of 'parent', with the name 'name' and widget flags set to 'f'.
~DlgSettingsColorGradientImp()
DlgSettingsColorGradientImp::~DlgSettingsColorGradientImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
accept()
void DlgSettingsColorGradientImp::accept (void)
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
colorModel()
App::ColorGradient::TColorModel DlgSettingsColorGradientImp::colorModel () const
References App::ColorGradient::GRAY, App::ColorGradient::INVERSE_GRAY, App::ColorGradient::INVERSE_TRIA, and App::ColorGradient::TRIA.
Referenced by Gui::SoFCColorGradient::customize().
colorStyle()
App::ColorGradient::TStyle DlgSettingsColorGradientImp::colorStyle () const
References App::ColorGradient::FLOW, and App::ColorGradient::ZERO_BASED.
Referenced by Gui::SoFCColorGradient::customize().
getRange()
void DlgSettingsColorGradientImp::getRange (float & fMin, float & fMax) const
Referenced by Gui::SoFCColorGradient::customize().
isOutGrayed()
bool DlgSettingsColorGradientImp::isOutGrayed () const
Referenced by Gui::SoFCColorGradient::customize().
isOutInvisible()
bool DlgSettingsColorGradientImp::isOutInvisible () const
Referenced by Gui::SoFCColorGradient::customize().
numberOfDecimals()
int DlgSettingsColorGradientImp::numberOfDecimals () const
Referenced by Gui::SoFCColorGradient::customize(), and setRange().
numberOfLabels()
int DlgSettingsColorGradientImp::numberOfLabels () const
Referenced by Gui::SoFCColorGradient::customize().
setColorModel()
void DlgSettingsColorGradientImp::setColorModel (App::ColorGradient::TColorModel tModel)
References App::ColorGradient::GRAY, App::ColorGradient::INVERSE_GRAY, App::ColorGradient::INVERSE_TRIA, and App::ColorGradient::TRIA.
Referenced by Gui::SoFCColorGradient::customize().
setColorStyle()
void DlgSettingsColorGradientImp::setColorStyle (App::ColorGradient::TStyle tStyle)
References App::ColorGradient::FLOW, and App::ColorGradient::ZERO_BASED.
Referenced by Gui::SoFCColorGradient::customize().
setNumberOfDecimals()
void DlgSettingsColorGradientImp::setNumberOfDecimals (int val)
Referenced by Gui::SoFCColorGradient::customize().
setNumberOfLabels()
void DlgSettingsColorGradientImp::setNumberOfLabels (int val)
Referenced by Gui::SoFCColorGradient::customize().
setOutGrayed()
void DlgSettingsColorGradientImp::setOutGrayed (bool grayed)
Referenced by Gui::SoFCColorGradient::customize().
setOutInvisible()
void DlgSettingsColorGradientImp::setOutInvisible (bool invisible)
Referenced by Gui::SoFCColorGradient::customize().
setRange()
void DlgSettingsColorGradientImp::setRange (float fMin, float fMax)
References numberOfDecimals(), and DraftVecUtils::toString().
Referenced by Gui::SoFCColorGradient::customize().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgSettingsColorGradientImp.h
Sources/FreeCAD/src/Gui/DlgSettingsColorGradientImp.cpp