FreeCAD: FemGui::TaskCreateNodeSet Class Reference
FemGui::TaskCreateNodeSet Class Reference
#include <TaskCreateNodeSet.h>
Public Member Functions
TaskCreateNodeSet (Fem::FemSetNodesObject *pcObject, QWidget *parent=nullptr)
~TaskCreateNodeSet ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Public Attributes
ViewProviderFemMesh * MeshViewProvider
std::set< long > tempSet
Protected Types
enum selectionModes { none , PickElement }
Protected Member Functions
void DefineNodes (const Base::Polygon2d &polygon, const Gui::ViewVolumeProjection &proj, bool)
virtual void onSelectionChanged (const Gui::SelectionChanges &msg)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Static Protected Member Functions
static void DefineNodesCallback (void *ud, SoEventCallback *n)
Protected Attributes
Fem::FemSetNodesObject * pcObject
enum FemGui::TaskCreateNodeSet::selectionModes selectionMode
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Member Enumeration Documentation
selectionModes
enum FemGui::TaskCreateNodeSet::selectionModes protected
Enumerator
none
PickElement
Constructor & Destructor Documentation
TaskCreateNodeSet()
TaskCreateNodeSet::TaskCreateNodeSet (Fem::FemSetNodesObject * pcObject, QWidget * parent = nullptr)
References Gui::BitmapFactory(), Ui_TaskCreateNodeSet::comboBox, draftgeoutils.intersections::connect(), Fem::FemSetObject::FemMesh, App::PropertyLink::getValue(), App::PropertyIntegerSet::getValues(), Gui::Application::getViewProvider(), Ui_TaskCreateNodeSet::groupBox_AngleSearch, QSint::ActionGroup::groupLayout(), Gui::Application::Instance, MeshViewProvider, Fem::FemSetNodesObject::Nodes, pcObject, FemGui::ViewProviderFemMesh::setHighlightNodes(), Ui_TaskCreateNodeSet::setupUi(), tempSet, Ui_TaskCreateNodeSet::toolButton_Pick, and Ui_TaskCreateNodeSet::toolButton_Poly.
~TaskCreateNodeSet()
TaskCreateNodeSet::~TaskCreateNodeSet ()
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
DefineNodes()
void TaskCreateNodeSet::DefineNodes (const Base::Polygon2d & polygon, const Gui::ViewVolumeProjection & proj, bool inner) protected
References Ui_TaskCreateNodeSet::checkBox_Add, Fem::FemSetObject::FemMesh, SMDS_MeshElement::GetID(), App::PropertyLink::getValue(), MeshViewProvider, pcObject, FemGui::ViewProviderFemMesh::setHighlightNodes(), tempSet, draftgeoutils.general::vec(), SMDS_MeshNode::X(), Base::Vector3< _Precision >::x, SMDS_MeshNode::Y(), Base::Vector3< _Precision >::y, and SMDS_MeshNode::Z().
Referenced by DefineNodesCallback().
DefineNodesCallback()
void TaskCreateNodeSet::DefineNodesCallback (void * ud, SoEventCallback * n) static protected
References DefineNodes(), and DefineNodesCallback().
Referenced by DefineNodesCallback().
onSelectionChanged()
void TaskCreateNodeSet::onSelectionChanged (const Gui::SelectionChanges & msg) protected virtual
Implements Gui::SelectionObserver.
References Gui::SelectionChanges::AddSelection, Ui_TaskCreateNodeSet::checkBox_Add, Base::Console(), Fem::FemSetObject::FemMesh, App::PropertyLink::getValue(), MeshViewProvider, Base::ConsoleSingleton::Message(), none, pcObject, Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), selectionMode, FemGui::ViewProviderFemMesh::setHighlightNodes(), and tempSet.
Member Data Documentation
MeshViewProvider
ViewProviderFemMesh* FemGui::TaskCreateNodeSet::MeshViewProvider
Referenced by FemGui::TaskDlgCreateNodeSet::accept(), DefineNodes(), onSelectionChanged(), FemGui::TaskDlgCreateNodeSet::reject(), and TaskCreateNodeSet().
pcObject
Fem::FemSetNodesObject* FemGui::TaskCreateNodeSet::pcObject protected
Referenced by DefineNodes(), onSelectionChanged(), and TaskCreateNodeSet().
selectionMode
enum FemGui::TaskCreateNodeSet::selectionModes FemGui::TaskCreateNodeSet::selectionMode protected
Referenced by Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonRef1(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonRef2(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonSupport(), and onSelectionChanged().
tempSet
std::set<long> FemGui::TaskCreateNodeSet::tempSet
Referenced by FemGui::TaskDlgCreateNodeSet::accept(), DefineNodes(), onSelectionChanged(), and TaskCreateNodeSet().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/TaskCreateNodeSet.h
FreeCAD/src/Mod/Fem/Gui/TaskCreateNodeSet.cpp