FreeCAD: SMESH_Array1< TheItemType > Class Template Reference
SMESH_Array1< TheItemType > Class Template Reference
Purpose: The class Array1 represents unidimensional arrays of fixed size known at run time.
#include <SMESH_Array1.hxx>
Classes
class Iterator
Implementation of the Iterator interface.
Public Member Functions
virtual void Assign (const NCollection_BaseCollection< TheItemType > &theOther)
Assign (any collection to this array)
TheItemType & ChangeValue (const Standard_Integer theIndex)
Variable value access.
void Init (const TheItemType &theValue)
Initialise the items with theValue.
Standard_Boolean IsAllocated (void) const
IsAllocated flag - for naming compatibility.
Standard_Boolean IsDeletable (void) const
myDeletable flag
Standard_Integer Length (void) const
Length query (the same)
Standard_Integer Lower (void) const
Lower bound.
TheItemType & operator() (const Standard_Integer theIndex)
operator() - alias to ChangeValue
const TheItemType & operator() (const Standard_Integer theIndex) const
operator() - alias to Value
SMESH_Array1 & operator= (const SMESH_Array1 &theOther)
operator= (array to array)
void SetValue (const Standard_Integer theIndex, const TheItemType &theItem)
Set value.
virtual Standard_Integer Size (void) const
Size query.
SMESH_Array1 (const SMESH_Array1 &theOther)
Copy constructor.
SMESH_Array1 (const Standard_Integer theLower, const Standard_Integer theUpper)
Constructor.
SMESH_Array1 (const TheItemType &theBegin, const Standard_Integer theLower, const Standard_Integer theUpper)
C array-based constructor.
Standard_Integer Upper (void) const
Upper bound.
const TheItemType & Value (const Standard_Integer theIndex) const
Constant value access.
~SMESH_Array1 (void)
Destructor - releases the memory.
Protected Attributes
TheItemType * myData
Pointer to '0'th array item.
Standard_Boolean myDeletable
Flag showing who allocated the array.
Standard_Integer myLowerBound
Standard_Integer myUpperBound
Detailed Description
template<class TheItemType>
class SMESH_Array1< TheItemType >
Purpose: The class Array1 represents unidimensional arrays of fixed size known at run time.
The range of the index is user defined. An array1 can be constructed with a "C array". This functionality is useful to call methods expecting an Array1. It allows to carry the bounds inside the arrays.
Examples: Item tab[100]; // An example with a C array Array1OfItem ttab (tab[0],1,100);
Array1OfItem tttab (ttab(10),10,20); // a slice of ttab
If you want to reindex an array from 1 to Length do :
Array1 tab1(tab(tab.Lower()),1,tab.Length());
Warning: Programs client of such a class must be independent of the range of the first element. Then, a C++ for loop must be written like this
for (i = A.Lower(); i <= A.Upper(); i++)
Changes: In comparison to TCollection the flag isAllocated was renamed into myDeletable (alike in the Array2). For naming compatibility the method IsAllocated remained in class along with IsDeletable.
Constructor & Destructor Documentation
SMESH_Array1() [1/3]
template<class TheItemType > SMESH_Array1< TheItemType >::SMESH_Array1 (const Standard_Integer theLower, const Standard_Integer theUpper)
Constructor.
References SMESH_Array1< TheItemType >::Length(), and SMESH_Array1< TheItemType >::myData.
SMESH_Array1() [2/3]
template<class TheItemType > SMESH_Array1< TheItemType >::SMESH_Array1 (const SMESH_Array1< TheItemType > & theOther)
Copy constructor.
References SMESH_Array1< TheItemType >::Length(), SMESH_Array1< TheItemType >::myData, and SMESH_Array1< TheItemType >::myLowerBound.
SMESH_Array1() [3/3]
template<class TheItemType > SMESH_Array1< TheItemType >::SMESH_Array1 (const TheItemType & theBegin, const Standard_Integer theLower, const Standard_Integer theUpper)
C array-based constructor.
References SMESH_Array1< TheItemType >::myData.
~SMESH_Array1()
template<class TheItemType > SMESH_Array1< TheItemType >::~SMESH_Array1 (void)
Destructor - releases the memory.
References SMESH_Array1< TheItemType >::myData, SMESH_Array1< TheItemType >::myDeletable, and SMESH_Array1< TheItemType >::myLowerBound.
Member Function Documentation
Assign()
template<class TheItemType > virtual void SMESH_Array1< TheItemType >::Assign (const NCollection_BaseCollection< TheItemType > & theOther) virtual
Assign (any collection to this array)
References SMESH_Array1< TheItemType >::Length(), SMESH_Array1< TheItemType >::myData, SMESH_Array1< TheItemType >::myLowerBound, and SMESH_Array1< TheItemType >::myUpperBound.
ChangeValue()
template<class TheItemType > TheItemType & SMESH_Array1< TheItemType >::ChangeValue (const Standard_Integer theIndex)
Variable value access.
References SMESH_Array1< TheItemType >::myData, and SMESH_Array1< TheItemType >::myUpperBound.
Referenced by SMESH_Array1< TheItemType >::Iterator::ChangeValue(), and SMESH_Array1< TheItemType >::operator()().
Init()
template<class TheItemType > void SMESH_Array1< TheItemType >::Init (const TheItemType & theValue)
Initialise the items with theValue.
References SMESH_Array1< TheItemType >::myData, SMESH_Array1< TheItemType >::myLowerBound, and SMESH_Array1< TheItemType >::myUpperBound.
IsAllocated()
template<class TheItemType > Standard_Boolean SMESH_Array1< TheItemType >::IsAllocated (void) const
IsAllocated flag - for naming compatibility.
References SMESH_Array1< TheItemType >::myDeletable.
IsDeletable()
template<class TheItemType > Standard_Boolean SMESH_Array1< TheItemType >::IsDeletable (void) const
myDeletable flag
References SMESH_Array1< TheItemType >::myDeletable.
Length()
template<class TheItemType > Standard_Integer SMESH_Array1< TheItemType >::Length (void) const
Length query (the same)
References SMESH_Array1< TheItemType >::myLowerBound, and SMESH_Array1< TheItemType >::myUpperBound.
Referenced by ArchStructure.CommandStructuralSystem::Activated(), SMESH_Array1< TheItemType >::Assign(), ArchPanel.CommandPanel::getPoint(), SMESH_Array1< TheItemType >::operator=(), ArchPanel.CommandPanel::setLength(), SMESH_Array1< TheItemType >::Size(), SMESH_Array1< TheItemType >::SMESH_Array1(), and ArchPanel.CommandPanel::update().
Lower()
template<class TheItemType > Standard_Integer SMESH_Array1< TheItemType >::Lower (void) const
Lower bound.
References SMESH_Array1< TheItemType >::myLowerBound.
Referenced by SMESH_Array1< TheItemType >::Iterator::Init().
operator()() [1/2]
template<class TheItemType > TheItemType & SMESH_Array1< TheItemType >::operator() (const Standard_Integer theIndex)
operator() - alias to ChangeValue
References SMESH_Array1< TheItemType >::ChangeValue().
operator()() [2/2]
template<class TheItemType > const TheItemType & SMESH_Array1< TheItemType >::operator() (const Standard_Integer theIndex) const
operator() - alias to Value
References SMESH_Array1< TheItemType >::Value().
operator=()
template<class TheItemType > SMESH_Array1 & SMESH_Array1< TheItemType >::operator= (const SMESH_Array1< TheItemType > & theOther)
operator= (array to array)
References SMESH_Array1< TheItemType >::Length(), SMESH_Array1< TheItemType >::myData, SMESH_Array1< TheItemType >::myLowerBound, and SMESH_Array1< TheItemType >::myUpperBound.
SetValue()
template<class TheItemType > void SMESH_Array1< TheItemType >::SetValue (const Standard_Integer theIndex, const TheItemType & theItem)
Set value.
References SMESH_Array1< TheItemType >::myData, and SMESH_Array1< TheItemType >::myUpperBound.
Size()
template<class TheItemType > virtual Standard_Integer SMESH_Array1< TheItemType >::Size (void) const virtual
Size query.
References SMESH_Array1< TheItemType >::Length().
Upper()
template<class TheItemType > Standard_Integer SMESH_Array1< TheItemType >::Upper (void) const
Upper bound.
References SMESH_Array1< TheItemType >::myUpperBound.
Referenced by SMESH_Array1< TheItemType >::Iterator::More().
Value()
template<class TheItemType > const TheItemType & SMESH_Array1< TheItemType >::Value (const Standard_Integer theIndex) const
Constant value access.
References SMESH_Array1< TheItemType >::myData, and SMESH_Array1< TheItemType >::myUpperBound.
Referenced by SMESH_Array1< TheItemType >::operator()(), and SMESH_Array1< TheItemType >::Iterator::Value().
Member Data Documentation
myData
template<class TheItemType > TheItemType* SMESH_Array1< TheItemType >::myData protected
Pointer to '0'th array item.
Referenced by SMESH_Array1< TheItemType >::Assign(), SMESH_Array1< TheItemType >::ChangeValue(), SMESH_Array1< TheItemType >::Init(), SMESH_Array1< TheItemType >::operator=(), SMESH_Array1< TheItemType >::SetValue(), SMESH_Array1< TheItemType >::SMESH_Array1(), SMESH_Array1< TheItemType >::Value(), and SMESH_Array1< TheItemType >::~SMESH_Array1().
myDeletable
template<class TheItemType > Standard_Boolean SMESH_Array1< TheItemType >::myDeletable protected
Flag showing who allocated the array.
Referenced by SMESH_Array1< TheItemType >::IsAllocated(), SMESH_Array1< TheItemType >::IsDeletable(), and SMESH_Array1< TheItemType >::~SMESH_Array1().
myLowerBound
template<class TheItemType > Standard_Integer SMESH_Array1< TheItemType >::myLowerBound protected
Referenced by SMESH_Array1< TheItemType >::Assign(), SMESH_Array1< TheItemType >::Init(), SMESH_Array1< TheItemType >::Length(), SMESH_Array1< TheItemType >::Lower(), SMESH_Array1< TheItemType >::operator=(), SMESH_Array1< TheItemType >::SMESH_Array1(), and SMESH_Array1< TheItemType >::~SMESH_Array1().
myUpperBound
template<class TheItemType > Standard_Integer SMESH_Array1< TheItemType >::myUpperBound protected
Referenced by SMESH_Array1< TheItemType >::Assign(), SMESH_Array1< TheItemType >::ChangeValue(), SMESH_Array1< TheItemType >::Init(), SMESH_Array1< TheItemType >::Length(), SMESH_Array1< TheItemType >::operator=(), SMESH_Array1< TheItemType >::SetValue(), SMESH_Array1< TheItemType >::Upper(), and SMESH_Array1< TheItemType >::Value().
The documentation for this class was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_Array1.hxx