FreeCAD: Gui::PythonEditor Class Reference
Gui::PythonEditor Class Reference
Python text editor with syntax highlighting.
#include <PythonEditor.h>
Public Slots
void onComment ()
Inserts a '#' at the beginning of each selected line or the current line if nothing is selected.
void onUncomment ()
Removes the leading '#' from each selected line or the current line if nothing is selected.
void setFileName (const QString &)
void startDebug ()
Public Member Functions
void hideDebugMarker ()
PythonEditor (QWidget *parent=0)
Constructs a PythonEditor which is a child of 'parent' and does the syntax highlighting for the Python language.
void showDebugMarker (int line)
void toggleBreakpoint ()
~PythonEditor ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::TextEditor
void lineNumberAreaPaintEvent (QPaintEvent *)
int lineNumberAreaWidth ()
void OnChange (Base::Subject< const char * > &rCaller, const char *rcReason)
Sets the font, font size and tab size of the editor.
void setSyntaxHighlighter (SyntaxHighlighter *)
TextEditor (QWidget *parent=0)
Constructs a TextEditor which is a child of 'parent' and does the syntax highlighting for the Python language.
~TextEditor ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::TextEdit
TextEdit (QWidget *parent=0)
Constructs a TextEdit which is a child of 'parent'.
virtual ~TextEdit ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::WindowParameter
ParameterGrp::handle getWindowParameter (void)
return the parameter group of this window
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason)
bool setGroupName (const char *name)
Sets the group of the window to name.
WindowParameter (const char *name)
virtual ~WindowParameter ()
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *e)
Pops up the context menu with some extensions.
void drawMarker (int line, int x, int y, QPainter *)
Protected Member Functions inherited from Gui::TextEditor
QWidget * getMarker () const
void keyPressEvent (QKeyEvent *e)
void paintEvent (QPaintEvent *e)
Draw a beam in the line where the cursor is.
void resizeEvent (QResizeEvent *e)
Protected Member Functions inherited from Gui::TextEdit
void keyPressEvent (QKeyEvent *)
Set the approproriate item of the completion box or hide it, if needed.
Additional Inherited Members
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter (void)
get the parameters
Detailed Description
Python text editor with syntax highlighting.
Author
Werner Mayer
Constructor & Destructor Documentation
PythonEditor()
PythonEditor::PythonEditor (QWidget * parent = 0)
Constructs a PythonEditor which is a child of 'parent' and does the syntax highlighting for the Python language.
References draftgeoutils.intersections::connect(), onComment(), onUncomment(), and Gui::TextEditor::setSyntaxHighlighter().
~PythonEditor()
PythonEditor::~PythonEditor ()
Destroys the object and frees any allocated resources.
References Base::Subject< _MessageType >::Detach(), and Gui::WindowParameter::getWindowParameter().
Member Function Documentation
contextMenuEvent()
void PythonEditor::contextMenuEvent (QContextMenuEvent * e) protected
Pops up the context menu with some extensions.
References onComment(), and onUncomment().
drawMarker()
void PythonEditor::drawMarker (int line, int x, int y, QPainter * p) protected virtual
Reimplemented from Gui::TextEditor.
References Gui::PythonEditorP::breakpoint, Gui::Breakpoint::checkLine(), Gui::PythonEditorP::debugger, Gui::PythonEditorP::debugLine, Gui::PythonEditorP::debugMarker, Gui::PythonEditorP::debugRect, Gui::PythonEditorP::filename, and Gui::PythonDebugger::getBreakpoint().
hideDebugMarker()
void PythonEditor::hideDebugMarker ()
References Gui::PythonEditorP::debugLine, and Gui::TextEditor::getMarker().
onComment
void PythonEditor::onComment () slot
Inserts a '#' at the beginning of each selected line or the current line if nothing is selected.
Referenced by contextMenuEvent(), and PythonEditor().
onUncomment
void PythonEditor::onUncomment () slot
Removes the leading '#' from each selected line or the current line if nothing is selected.
In case a line hasn't a leading '#' then this line is skipped.
Referenced by contextMenuEvent(), and PythonEditor().
setFileName
void PythonEditor::setFileName (const QString & fn) slot
References Gui::PythonEditorP::filename.
showDebugMarker()
void PythonEditor::showDebugMarker (int line)
References Gui::PythonEditorP::debugLine, and Gui::TextEditor::getMarker().
startDebug
void PythonEditor::startDebug () slot
References Gui::PythonEditorP::debugger, Gui::PythonEditorP::filename, Gui::PythonDebugger::runFile(), Gui::PythonDebugger::start(), and Gui::PythonDebugger::stop().
toggleBreakpoint()
void PythonEditor::toggleBreakpoint ()
References Gui::PythonEditorP::debugger, Gui::PythonEditorP::filename, Gui::TextEditor::getMarker(), and Gui::PythonDebugger::toggleBreakpoint().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/PythonEditor.h
Sources/FreeCAD/src/Gui/PythonEditor.cpp