FreeCAD: SketcherGui::Ui_TaskSketcherElements Class Reference
SketcherGui::Ui_TaskSketcherElements Class Reference
#include <ui_TaskSketcherElements.h>
Public Member Functions
void retranslateUi (QWidget *SketcherGui__TaskSketcherElements)
void setupUi (QWidget *SketcherGui__TaskSketcherElements)
Public Attributes
QCheckBox * autoSwitchBox
QComboBox * comboBoxElementFilter
QComboBox * comboBoxModeFilter
QLabel * Explanation
QHBoxLayout * horizontalLayout
QHBoxLayout * horizontalLayout1
QLabel * label
QLabel * label1
ElementView * listWidgetElements
QCheckBox * namingBox
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void SketcherGui::Ui_TaskSketcherElements::retranslateUi (QWidget * SketcherGui__TaskSketcherElements)
References autoSwitchBox, comboBoxElementFilter, comboBoxModeFilter, label1, namingBox, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void SketcherGui::Ui_TaskSketcherElements::setupUi (QWidget * SketcherGui__TaskSketcherElements)
References autoSwitchBox, comboBoxElementFilter, comboBoxModeFilter, Explanation, horizontalLayout, horizontalLayout1, label1, listWidgetElements, namingBox, retranslateUi(), and verticalLayout.
Member Data Documentation
autoSwitchBox
QCheckBox* SketcherGui::Ui_TaskSketcherElements::autoSwitchBox
Referenced by retranslateUi(), and setupUi().
comboBoxElementFilter
QComboBox* SketcherGui::Ui_TaskSketcherElements::comboBoxElementFilter
Referenced by retranslateUi(), and setupUi().
comboBoxModeFilter
QComboBox* SketcherGui::Ui_TaskSketcherElements::comboBoxModeFilter
Referenced by retranslateUi(), and setupUi().
Explanation
QLabel* SketcherGui::Ui_TaskSketcherElements::Explanation
Referenced by setupUi().
horizontalLayout
QHBoxLayout* SketcherGui::Ui_TaskSketcherElements::horizontalLayout
Referenced by setupUi().
horizontalLayout1
QHBoxLayout* SketcherGui::Ui_TaskSketcherElements::horizontalLayout1
Referenced by setupUi().
label
QLabel* SketcherGui::Ui_TaskSketcherElements::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
label1
QLabel* SketcherGui::Ui_TaskSketcherElements::label1
Referenced by retranslateUi(), and setupUi().
listWidgetElements
ElementView* SketcherGui::Ui_TaskSketcherElements::listWidgetElements
Referenced by setupUi().
namingBox
QCheckBox* SketcherGui::Ui_TaskSketcherElements::namingBox
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* SketcherGui::Ui_TaskSketcherElements::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/ui_TaskSketcherElements.h