FreeCAD: feminout.importZ88Mesh Namespace Reference
feminout.importZ88Mesh Namespace Reference
Functions
def export (objectslist, filename)
def get_z88_element_type (femmesh, femelement_table=None)
def import_z88_mesh (filename, analysis=None, docname=None)
def insert (filename, docname)
def open (filename)
def read (filename)
def read_z88_mesh (z88_mesh_input)
def write (fem_mesh, filename)
def write_z88_mesh_to_file (femnodes_mesh, femelement_table, z88_element_type, f)
Variables
pyopen = open
dictionary z88_ele_types
Function Documentation
export()
def feminout.importZ88Mesh.export (objectslist, filename)
References feminout.importZ88Mesh.get_z88_element_type(), feminout.importZ88Mesh.pyopen, and feminout.importZ88Mesh.write_z88_mesh_to_file().
get_z88_element_type()
def feminout.importZ88Mesh.get_z88_element_type (femmesh, femelement_table = None)
Referenced by feminout.importZ88Mesh.export(), and feminout.importZ88Mesh.write().
import_z88_mesh()
def feminout.importZ88Mesh.import_z88_mesh (filename, analysis = None, docname = None)
read a FEM mesh from a Z88 mesh file and
insert a FreeCAD FEM Mesh object in the ActiveDocument
References feminout.importZ88Mesh.read().
Referenced by feminout.importZ88Mesh.insert().
insert()
def feminout.importZ88Mesh.insert (filename, docname)
called when freecad wants to import a file
a FEM mesh object is created in a existing document
References feminout.importZ88Mesh.import_z88_mesh().
Referenced by feminout.importZ88Mesh.open().
open()
def feminout.importZ88Mesh.open (filename)
called when freecad opens a file
a FEM mesh object is created in a new document
References feminout.importZ88Mesh.insert().
read()
def feminout.importZ88Mesh.read (filename)
read a FemMesh from a Z88 mesh file and return the FemMesh
References feminout.importZ88Mesh.read_z88_mesh().
Referenced by feminout.importZ88Mesh.import_z88_mesh().
read_z88_mesh()
def feminout.importZ88Mesh.read_z88_mesh (z88_mesh_input)
 reads a z88 mesh file z88i1.txt (Z88OSV14) or z88structure.txt (Z88AuroraV3)
    and extracts the nodes and elements
References feminout.importZ88Mesh.pyopen.
Referenced by feminout.importZ88Mesh.read().
write()
def feminout.importZ88Mesh.write (fem_mesh, filename)
directly write a FemMesh to a Z88 mesh file format
fem_mesh: a FemMesh
References feminout.importZ88Mesh.get_z88_element_type(), feminout.importZ88Mesh.pyopen, and feminout.importZ88Mesh.write_z88_mesh_to_file().
write_z88_mesh_to_file()
def feminout.importZ88Mesh.write_z88_mesh_to_file (femnodes_mesh, femelement_table, z88_element_type, f)
Referenced by feminout.importZ88Mesh.export(), and feminout.importZ88Mesh.write().
Variable Documentation
pyopen
feminout.importZ88Mesh.pyopen = open
Referenced by feminout.importZ88Mesh.export(), feminout.importZ88Mesh.read_z88_mesh(), and feminout.importZ88Mesh.write().
z88_ele_types
dictionary feminout.importZ88Mesh.z88_ele_types
Initial value:
=  {
    "tetra4": 17,
    "tetra10": 16,
    "hexa8": 1,
    "hexa20": 10,
    "tria3": 0,  # no tria3 available in Z88
    "tria6": 24,
    "quad4": 0,  # no quad4 available in Z88
    "quad8": 23,
    "seg2": 4,  # 3D Truss element
    "seg3": 4,  # 3D Truss element
    "None": 0,
}