FreeCAD: SMESH_Array1< TheItemType >::Iterator Class Reference
SMESH_Array1< TheItemType >::Iterator Class Reference
Implementation of the Iterator interface.
#include <SMESH_Array1.hxx>
Public Member Functions
virtual TheItemType & ChangeValue (void) const
Variable value access.
void Init (const SMESH_Array1 &theArray)
Initialisation.
Iterator (const SMESH_Array1 &theArray)
Constructor with initialisation.
Iterator (void)
Empty constructor - for later Init.
virtual Standard_Boolean More (void) const
Check end.
virtual void Next (void)
Make step.
void * operator new (size_t theSize, const Handle(NCollection_BaseAllocator)&theAllocator)
Operator new for allocating iterators.
virtual const TheItemType & Value (void) const
Constant value access.
Detailed Description
template<class TheItemType>
class SMESH_Array1< TheItemType >::Iterator
Implementation of the Iterator interface.
Constructor & Destructor Documentation
Iterator() [1/2]
template<class TheItemType > SMESH_Array1< TheItemType >::Iterator::Iterator (void)
Empty constructor - for later Init.
Iterator() [2/2]
template<class TheItemType > SMESH_Array1< TheItemType >::Iterator::Iterator (const SMESH_Array1 & theArray)
Constructor with initialisation.
Member Function Documentation
ChangeValue()
template<class TheItemType > virtual TheItemType& SMESH_Array1< TheItemType >::Iterator::ChangeValue (void) const virtual
Variable value access.
References SMESH_Array1< TheItemType >::ChangeValue().
Init()
template<class TheItemType > void SMESH_Array1< TheItemType >::Iterator::Init (const SMESH_Array1 & theArray)
Initialisation.
References SMESH_Array1< TheItemType >::Lower().
More()
template<class TheItemType > virtual Standard_Boolean SMESH_Array1< TheItemType >::Iterator::More (void) const virtual
Check end.
References SMESH_Array1< TheItemType >::Upper().
Next()
template<class TheItemType > virtual void SMESH_Array1< TheItemType >::Iterator::Next (void) virtual
Make step.
operator new()
template<class TheItemType > void* SMESH_Array1< TheItemType >::Iterator::operator new (size_t theSize, const Handle(NCollection_BaseAllocator)& theAllocator)
Operator new for allocating iterators.
Value()
template<class TheItemType > virtual const TheItemType& SMESH_Array1< TheItemType >::Iterator::Value (void) const virtual
Constant value access.
References SMESH_Array1< TheItemType >::Value().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_Array1.hxx