FreeCAD: VISCOUS_3D::PyDump Struct Reference
VISCOUS_3D::PyDump Struct Reference
Public Member Functions
void Finish ()
PyDump (SMESH_Mesh &)
Constructor & Destructor Documentation
PyDump()
VISCOUS_3D::PyDump::PyDump (SMESH_Mesh &)
Member Function Documentation
Finish()
void VISCOUS_3D::PyDump::Finish ()
References Finish().
Referenced by VISCOUS_3D::_ViscousBuilder::Compute(), and Finish().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_ViscousLayers.cpp