FreeCAD: Gui::Dialog::DockablePlacement Class Reference
Gui::Dialog::DockablePlacement Class Reference
#include <Placement.h>
Public Member Functions
void accept ()
DockablePlacement (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
void reject ()
~DockablePlacement ()
Public Member Functions inherited from Gui::Dialog::Placement
void accept ()
void bindObject ()
Base::Vector3d getDirection () const
Base::Placement getPlacement () const
Placement (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
void reject ()
void setPlacement (const Base::Placement &)
void showDefaultButtons (bool)
~Placement ()
Public Member Functions inherited from Gui::LocationDialog
virtual Base::Vector3d getDirection () const =0
Base::Vector3d getUserDirection (bool *ok=nullptr) const
Additional Inherited Members
Signals inherited from Gui::Dialog::Placement
void directionChanged ()
void placementChanged (const QVariant &, bool, bool)
Protected Member Functions inherited from Gui::Dialog::Placement
void changeEvent (QEvent *e)
void keyPressEvent (QKeyEvent *)
void open ()
Protected Member Functions inherited from Gui::LocationDialog
virtual void changeEvent (QEvent *e)=0
LocationDialog (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
virtual ~LocationDialog ()
Constructor & Destructor Documentation
DockablePlacement()
DockablePlacement::DockablePlacement (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
References Gui::DockWindowManager::addDockWindow(), and Gui::DockWindowManager::instance().
~DockablePlacement()
DockablePlacement::~DockablePlacement ()
Member Function Documentation
accept()
void DockablePlacement::accept (void)
References Gui::Dialog::Placement::accept(), Gui::DockWindowManager::instance(), and Gui::DockWindowManager::removeDockWindow().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
reject()
void DockablePlacement::reject (void)
References Gui::DockWindowManager::instance(), Gui::Dialog::Placement::reject(), and Gui::DockWindowManager::removeDockWindow().
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/Placement.h
FreeCAD/src/Gui/Placement.cpp