FreeCAD: femguiutils.migrate_gui.FemMigrateGui Class Reference
femguiutils.migrate_gui.FemMigrateGui Class Reference
Public Member Functions
def create_module (self, spec)
def exec_module (self, module)
def find_module (self, fullname, path)
def load_module (self, module)
Member Function Documentation
create_module()
def femguiutils.migrate_gui.FemMigrateGui.create_module (self, spec)
exec_module()
def femguiutils.migrate_gui.FemMigrateGui.exec_module (self, module)
References femguiutils.migrate_gui.FemMigrateGui.load_module().
find_module()
def femguiutils.migrate_gui.FemMigrateGui.find_module (self, fullname, path)
load_module()
def femguiutils.migrate_gui.FemMigrateGui.load_module (self, module)
Referenced by femguiutils.migrate_gui.FemMigrateGui.exec_module(), and femtools.migrate_app.FemMigrateApp.exec_module().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Fem/femguiutils/migrate_gui.py