FreeCAD: MeshGui::SoFCMeshObjectElement Class Reference
MeshGui::SoFCMeshObjectElement Class Reference
#include <SoFCMeshObject.h>
Public Member Functions
virtual void init (SoState *state)
virtual void print (FILE *file) const
Static Public Member Functions
static const Mesh::MeshObject * get (SoState *const state)
static const SoFCMeshObjectElement * getInstance (SoState *state)
static void initClass (void)
static void set (SoState *const state, SoNode *const node, const Mesh::MeshObject *const mesh)
Protected Member Functions
virtual ~SoFCMeshObjectElement ()
Protected Attributes
const Mesh::MeshObject * mesh
Constructor & Destructor Documentation
~SoFCMeshObjectElement()
SoFCMeshObjectElement::~SoFCMeshObjectElement () protected virtual
Member Function Documentation
get()
const Mesh::MeshObject * SoFCMeshObjectElement::get (SoState *const state) static
References getInstance(), and mesh.
Referenced by MeshGui::SoFCMeshObjectShape::computeBBox(), MeshGui::SoFCMeshSegmentShape::computeBBox(), MeshGui::SoFCMeshObjectBoundary::computeBBox(), MeshGui::SoFCMeshObjectShape::generatePrimitives(), MeshGui::SoFCMeshSegmentShape::generatePrimitives(), MeshGui::SoFCMeshObjectBoundary::generatePrimitives(), MeshGui::SoFCMeshObjectShape::getPrimitiveCount(), MeshGui::SoFCMeshSegmentShape::getPrimitiveCount(), MeshGui::SoFCMeshObjectBoundary::getPrimitiveCount(), MeshGui::SoFCMeshObjectShape::GLRender(), MeshGui::SoFCMeshSegmentShape::GLRender(), MeshGui::SoFCMeshObjectBoundary::GLRender(), and draftguitools.gui_trackers.editTracker::move().
getInstance()
const SoFCMeshObjectElement * SoFCMeshObjectElement::getInstance (SoState * state) static
Referenced by get().
init()
void SoFCMeshObjectElement::init (SoState * state) virtual
References mesh.
Referenced by DocumentObject.DocumentObject::onChanged().
initClass()
void SoFCMeshObjectElement::initClass (void) static
print()
void SoFCMeshObjectElement::print (FILE * file) const virtual
set()
void SoFCMeshObjectElement::set (SoState *const state, SoNode *const node, const Mesh::MeshObject *const mesh) static
References mesh.
Referenced by MeshGui::SoFCMeshObjectNode::doAction(), and draftguitools.gui_trackers.editTracker::move().
Member Data Documentation
mesh
const Mesh::MeshObject* MeshGui::SoFCMeshObjectElement::mesh protected
Referenced by femtools.ccxtools.FemToolsCcx::check_prerequisites(), get(), femtools.ccxtools.FemToolsCcx::has_no_material_assigned(), femtools.ccxtools.FemToolsCcx::has_nonpositive_jacobians(), init(), femsolver.fenics.fenics_tools.XDMFReader::readCellExpression(), femsolver.fenics.fenics_tools.XDMFReader::readFacetFunction(), femsolver.fenics.fenics_tools.XDMFReader::readMesh(), femsolver.fenics.fenics_tools.XDMFReader::resetMesh(), MengerSponge.MengerThread::run(), set(), MeshTestsApp.MeshSplitTestCases::testSplitFacetOnOneEdge(), MeshTestsApp.MeshSplitTestCases::testSplitFacetOnTwoEdges_01(), MeshTestsApp.MeshSplitTestCases::testSplitFacetOnTwoEdges_02(), MeshTestsApp.MeshSplitTestCases::testSplitFacetOnTwoEdges_10(), MeshTestsApp.MeshSplitTestCases::testSplitFacetOnTwoEdges_12(), MeshTestsApp.MeshSplitTestCases::testSplitFacetOnTwoEdges_20(), MeshTestsApp.MeshSplitTestCases::testSplitFacetOnTwoEdges_21(), MeshTestsApp.MeshSplitTestCases::testSplitFacetOnTwoEdges_5teps(), and femtools.ccxtools.FemToolsCcx::write_inp_file().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCMeshObject.h
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCMeshObject.cpp