FreeCAD: Inspection::MeshInspectGrid Class Reference
Inspection::MeshInspectGrid Class Reference
Public Member Functions
MeshInspectGrid (const MeshCore::MeshKernel &mesh, float fGridLen, const Base::Matrix4D &m)
void Validate (const MeshCore::MeshKernel &)
Validates the grid structure and rebuilds it if needed.
void Validate (void)
bool Verify () const
Verifies the grid structure and returns false if inconsistencies are found.
Public Member Functions inherited from MeshCore::MeshGrid
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::vector< unsigned long > &raulElements, bool bDelDoubles=true) const
Searches for elements lying in the intersection area of the grid and the bounding box.
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::set< unsigned long > &raulElementss) const
Searches for elements lying in the intersection area of the grid and the bounding box.
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::vector< unsigned long > &raulElements, const Base::Vector3f &rclOrg, float fMaxDist, bool bDelDoubles=true) const
Searches for elements lying in the intersection area of the grid and the bounding box.
void SearchNearestFromPoint (const Base::Vector3f &rclPt, std::set< unsigned long > &rclInd) const
Searches for the nearest grids that contain elements from a point, the result are grid indices.
unsigned long GetElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ, std::set< unsigned long > &raclInd) const
Returns the indices of the elements in the given grid.
unsigned long GetElements (const Base::Vector3f &rclPoint, std::vector< unsigned long > &aulFacets) const
virtual void GetGridLengths (float &rfLenX, float &rfLenY, float &rfLenZ) const
Returns the lengths of the grid elements in x,y and z direction.
virtual void GetCtGrids (unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
Returns the number of grid elements in x,y and z direction.
Base::BoundBox3f GetBoundBox (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
Returns the bounding box of a given grid element.
Base::BoundBox3f GetBoundBox (void) const
Returns the bounding box of the whole.
Base::BoundBox3f GetMeshBoundBox (void) const
Returns an extended bounding box of the mesh object.
unsigned long GetIndexToPosition (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
Returns an index for the given grid position.
bool GetPositionToIndex (unsigned long id, unsigned long &ulX, unsigned long &ulY, unsigned long &ulZ) const
Returns the grid position to the given index.
unsigned long GetCtElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
Returns the number of elements in a given grid.
bool CheckPosition (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
Checks whether the point is inside the grid.
virtual void Position (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
Returns the indices of the grid this point lies in.
bool CheckPos (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
Checks if this is a valid grid position.
void GetHull (unsigned long ulX, unsigned long ulY, unsigned long ulZ, unsigned long ulDistance, std::set< unsigned long > &raclInd) const
Get the indices of all elements lying in the grids around a given grid with distance ulDistance.
virtual ~MeshGrid (void)
Destruction.
virtual void Attach (const MeshKernel &rclM)
Attaches the mesh kernel to this grid, an already attached mesh gets detached.
virtual void Rebuild (unsigned long ulPerGrid=MESH_CT_GRID, unsigned long ulMaxGrid=MESH_MAX_GRIDS)
Rebuilds the grid structure.
virtual void Rebuild (int iCtGridPerAxis=MESH_CT_GRID_PER_AXIS)
Rebuilds the grid structure.
virtual void Rebuild (unsigned long ulX, unsigned long ulY, unsigned long ulZ)
Rebuilds the grid structure.
Protected Member Functions
void AddFacet (const MeshCore::MeshGeomFacet &rclFacet, unsigned long ulFacetIndex)
void CalculateGridLength (int)
Calculates the grid length dependent on the number of grids per axis.
void CalculateGridLength (unsigned long, unsigned long)
Calculates the grid length dependent on maximum number of grids.
unsigned long HasElements (void) const
Returns the number of stored elements.
void InitGrid (void)
Initializes the size of the internal structure.
void Pos (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
void RebuildGrid (void)
Rebuilds the grid structure.
Protected Member Functions inherited from MeshCore::MeshGrid
virtual void Clear (void)
Deletes the grid structure.
MeshGrid (const MeshKernel &rclM)
Construction.
MeshGrid (void)
Construction.
Constructor & Destructor Documentation
MeshInspectGrid()
Inspection::MeshInspectGrid::MeshInspectGrid (const MeshCore::MeshKernel & mesh, float fGridLen, const Base::Matrix4D & m)
References Base::BoundBox3< _Precision >::LengthX(), Base::BoundBox3< _Precision >::LengthY(), Base::BoundBox3< _Precision >::LengthZ(), MeshCore::MeshGrid::Rebuild(), and Base::BoundBox3< _Precision >::Transformed().
Member Function Documentation
AddFacet()
void Inspection::MeshInspectGrid::AddFacet (const MeshCore::MeshGeomFacet & rclFacet, unsigned long ulFacetIndex) protected
References Base::BoundBox3< _Precision >::Add(), MeshCore::MeshGrid::GetBoundBox(), MeshCore::MeshGeomFacet::IntersectBoundingBox(), Base::BoundBox3< _Precision >::MaxX, Base::BoundBox3< _Precision >::MaxY, Base::BoundBox3< _Precision >::MaxZ, Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, Base::BoundBox3< _Precision >::MinZ, and Pos().
Referenced by RebuildGrid().
CalculateGridLength() [1/2]
void Inspection::MeshInspectGrid::CalculateGridLength (int iCtGridPerAxis) protected virtual
Calculates the grid length dependent on the number of grids per axis.
Reimplemented from MeshCore::MeshGrid.
CalculateGridLength() [2/2]
void Inspection::MeshInspectGrid::CalculateGridLength (unsigned long ulCtGrid, unsigned long ulMaxGrids) protected virtual
Calculates the grid length dependent on maximum number of grids.
Reimplemented from MeshCore::MeshGrid.
HasElements()
unsigned long Inspection::MeshInspectGrid::HasElements (void) const protected virtual
Returns the number of stored elements.
Must be implemented in sub-classes.
Implements MeshCore::MeshGrid.
InitGrid()
void Inspection::MeshInspectGrid::InitGrid (void) protected virtual
Initializes the size of the internal structure.
Reimplemented from MeshCore::MeshGrid.
References Base::BoundBox3< _Precision >::LengthX(), Base::BoundBox3< _Precision >::LengthY(), Base::BoundBox3< _Precision >::LengthZ(), Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, Base::BoundBox3< _Precision >::MinZ, and Base::BoundBox3< _Precision >::Transformed().
Referenced by RebuildGrid().
Pos()
void Inspection::MeshInspectGrid::Pos (const Base::Vector3f & rclPoint, unsigned long & rulX, unsigned long & rulY, unsigned long & rulZ) const protected
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by AddFacet().
RebuildGrid()
void Inspection::MeshInspectGrid::RebuildGrid (void) protected virtual
Rebuilds the grid structure.
Must be implemented in sub-classes.
Implements MeshCore::MeshGrid.
References AddFacet(), MeshCore::MeshFacetIterator::Init(), InitGrid(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), and MeshCore::MeshFacetIterator::Transform().
Validate() [1/2]
void Inspection::MeshInspectGrid::Validate (const MeshCore::MeshKernel & rclM) virtual
Validates the grid structure and rebuilds it if needed.
Must be implemented in sub-classes.
Implements MeshCore::MeshGrid.
Validate() [2/2]
void Inspection::MeshInspectGrid::Validate (void)
Verify()
bool Inspection::MeshInspectGrid::Verify () const virtual
Verifies the grid structure and returns false if inconsistencies are found.
Implements MeshCore::MeshGrid.
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Inspection/App/InspectionFeature.cpp