FreeCAD: Gui::Dialog::DlgSettings3DViewImp Class Reference
Gui::Dialog::DlgSettings3DViewImp Class Reference
The DlgSettings3DViewImp class implements a preference page to change settings for the Inventor viewer.
#include <DlgSettings3DViewImp.h>
Public Member Functions
DlgSettings3DViewImp (QWidget *parent=0)
Constructs a DlgSettings3DViewImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
void loadSettings ()
void saveSettings ()
~DlgSettings3DViewImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=0)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
Detailed Description
The DlgSettings3DViewImp class implements a preference page to change settings for the Inventor viewer.
Author
Jürgen Riegel
Constructor & Destructor Documentation
DlgSettings3DViewImp()
DlgSettings3DViewImp::DlgSettings3DViewImp (QWidget * parent = 0)
Constructs a DlgSettings3DViewImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
~DlgSettings3DViewImp()
DlgSettings3DViewImp::~DlgSettings3DViewImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void DlgSettings3DViewImp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
loadSettings()
void DlgSettings3DViewImp::loadSettings () virtual
Implements Gui::Dialog::PreferencePage.
References Base::clamp(), draftgeoutils.intersections::connect(), App::GetApplication(), ParameterGrp::GetInt(), and App::Application::GetParameterGroupByPath().
saveSettings()
void DlgSettings3DViewImp::saveSettings () virtual
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetInt().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgSettings3DViewImp.h
Sources/FreeCAD/src/Gui/DlgSettings3DViewImp.cpp