FreeCAD: SMESHDS_Group Class Reference
SMESHDS_Group Class Reference
#include <SMESHDS_Group.hxx>
Public Member Functions
bool Add (const int theID)
bool Add (const SMDS_MeshElement *theElem)
void Clear ()
virtual bool Contains (const int theID)
virtual bool Contains (const SMDS_MeshElement *elem)
virtual int Extent () const
virtual SMDS_ElemIteratorPtr GetElements () const
virtual VTK_MTIME_TYPE GetTic () const
Return a value allowing to find out if a group has changed or not.
virtual bool IsEmpty ()
bool Remove (const int theID)
virtual void SetType (SMDSAbs_ElementType theType)
SMDS_MeshGroup & SMDSGroup ()
SMESHDS_Group (const int theID, const SMESHDS_Mesh *theMesh, const SMDSAbs_ElementType theType)
Public Member Functions inherited from SMESHDS_GroupBase
virtual bool Contains (const int theID)
virtual bool Contains (const SMDS_MeshElement *elem)
virtual int Extent () const
Quantity_Color GetColor () const
int GetColorGroup () const
virtual SMDS_ElemIteratorPtr GetElements () const =0
int GetID () const
virtual int GetID (const int theIndex)
const SMESHDS_Mesh * GetMesh () const
const char * GetStoreName () const
virtual VTK_MTIME_TYPE GetTic () const =0
SMDSAbs_ElementType GetType () const
virtual bool IsEmpty ()
void SetColor (const Quantity_Color &theColor)
void SetColorGroup (int theColorGroup)
void SetStoreName (const char *theName)
virtual void SetType (SMDSAbs_ElementType theType)
SMESHDS_GroupBase (const int theID, const SMESHDS_Mesh *theMesh, const SMDSAbs_ElementType theType)
virtual ~SMESHDS_GroupBase ()
Additional Inherited Members
Static Public Member Functions inherited from SMESHDS_GroupBase
static void SetDefaultColor (const Quantity_Color &theColor)
Protected Member Functions inherited from SMESHDS_GroupBase
const SMDS_MeshElement * findInMesh (const int theID) const
void resetIterator ()
Constructor & Destructor Documentation
SMESHDS_Group()
SMESHDS_Group::SMESHDS_Group (const int theID, const SMESHDS_Mesh * theMesh, const SMDSAbs_ElementType theType)
Member Function Documentation
Add() [1/2]
bool SMESHDS_Group::Add (const int theID)
References Add(), and SMESHDS_GroupBase::findInMesh().
Referenced by Add(), Fem::FemMesh::addGroupElements(), SMESH_Mesh::ConvertToStandalone(), SMESH_MeshEditor::CreateFlatElementsOnFacesGroups(), SMESH_MeshEditor::CreateHoleSkin(), and SMESH_MeshEditor::DoubleNodesOnGroupBoundaries().
Add() [2/2]
bool SMESHDS_Group::Add (const SMDS_MeshElement * theElem)
References SMDS_MeshGroup::Add(), SMDS_MeshGroup::Contains(), SMDS_MeshElement::GetType(), SMDS_MeshGroup::IsEmpty(), SMESHDS_GroupBase::resetIterator(), and SetType().
Clear()
void SMESHDS_Group::Clear ()
References SMDS_MeshGroup::Clear(), and SMESHDS_GroupBase::resetIterator().
Contains() [1/2]
bool SMESHDS_Group::Contains (const int theID) virtual
Reimplemented from SMESHDS_GroupBase.
References SMDS_MeshGroup::Contains(), and SMESHDS_GroupBase::findInMesh().
Referenced by Fem::FemMesh::addGroupElements(), and SMESH_MeshEditor::CreateHoleSkin().
Contains() [2/2]
bool SMESHDS_Group::Contains (const SMDS_MeshElement * elem) virtual
Reimplemented from SMESHDS_GroupBase.
References SMDS_MeshGroup::Contains().
Extent()
int SMESHDS_Group::Extent () const virtual
Reimplemented from SMESHDS_GroupBase.
References SMDS_MeshGroup::Extent().
GetElements()
SMDS_ElemIteratorPtr SMESHDS_Group::GetElements () const virtual
Implements SMESHDS_GroupBase.
Referenced by SMESH_MeshEditor::CreateHoleSkin().
GetTic()
VTK_MTIME_TYPE SMESHDS_Group::GetTic () const virtual
Return a value allowing to find out if a group has changed or not.
Implements SMESHDS_GroupBase.
References SMDS_MeshGroup::Tic().
IsEmpty()
bool SMESHDS_Group::IsEmpty () virtual
Reimplemented from SMESHDS_GroupBase.
References SMDS_MeshGroup::IsEmpty().
Remove()
bool SMESHDS_Group::Remove (const int theID)
References SMDS_MeshGroup::Contains(), SMESHDS_GroupBase::findInMesh(), SMDS_MeshGroup::Remove(), and SMESHDS_GroupBase::resetIterator().
SetType()
void SMESHDS_Group::SetType (SMDSAbs_ElementType theType) virtual
Reimplemented from SMESHDS_GroupBase.
References SMDS_MeshGroup::GetType(), SMESHDS_GroupBase::GetType(), SMDS_MeshGroup::IsEmpty(), SMDS_MeshGroup::SetType(), and SMESHDS_GroupBase::SetType().
Referenced by Add(), and SMESH_Mesh::UNVToMesh().
SMDSGroup()
SMDS_MeshGroup & SMESHDS_Group::SMDSGroup ()
Referenced by SMESH_MeshEditor::AddToSameGroups(), DriverMED_R_SMESHDS_Mesh::GetGroup(), StdMeshers_Import_1D::importMesh(), SMESHDS_Mesh::RemoveFreeElement(), SMESHDS_Mesh::RemoveFreeNode(), SMESH_MeshEditor::ReplaceElemInGroups(), and SMESH_Mesh::UNVToMesh().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESHDS_Group.hxx
FreeCAD/src/3rdParty/salomesmesh/src/SMESHDS/SMESHDS_Group.cpp