FreeCAD: PathScripts.PathThreadMilling.ObjectThreadMilling Class Reference
PathScripts.PathThreadMilling.ObjectThreadMilling Class Reference
Public Member Functions
def circularHoleExecute (self, obj, holes)
def circularHoleFeatures (self, obj)
def executeThreadMill (self, obj, loc, gcode, zStart, zFinal, pitch)
def initCircularHoleOperation (self, obj)
def isToolSupported (self, obj, tool)
def opSetDefaultValues (self, obj, job)
def threadDirectionCmd (self, obj)
def threadFinalDepth (self, obj)
def threadPassRadii (self, obj)
def threadSetup (self, obj)
def threadStartDepth (self, obj)
Public Member Functions inherited from PathScripts.PathCircularHoleBase.ObjectOp
def applyInverseAngle (self, obj, clnBase, clnStock, axis, angle)
def applyRotationalAnalysis (self, obj, base, angle, axis, subCount)
def baseIsArchPanel (self, obj, base)
def calculateStartFinalDepths (self, obj, shape, stock)
def cloneBaseAndStock (self, obj, base, angle, axis, subCount)
def faceRotationAnalysis (self, obj, norm, surf)
def findAllHoles (self, obj)
def findHoles (self, obj, baseobject)
def getArchPanelEdge (self, obj, base, sub)
def getFaceNormAndSurf (self, face)
def guiMessage (self, title, msg, show=False)
def holeDiameter (self, obj, base, sub)
def holePosition (self, obj, base, sub)
def initOperation (self, obj)
def isFaceUp (self, base, face)
def isHoleEnabled (self, obj, base, sub)
def opDetermineRotationRadii (self, obj)
def opExecute (self, obj)
def opFeatures (self, obj)
def process_base_geometry_with_rotation (self, obj, p, subCount)
def process_nonloop_sublist (self, obj, base, sub)
def sortTuplesByIndex (self, TupleList, tagIdx)
def useTempJobClones (self, cloneName)
def visualAxis (self)
def warnDisabledAxis (self, obj, axis, sub='')
Public Member Functions inherited from PathScripts.PathOp.ObjectOp
def addBase (self, obj, base, sub)
def addBaseProperty (self, obj)
def addOpValues (self, obj, values)
def applyExpression (self, obj, prop, expr)
def execute (self, obj)
def getCycleTimeEstimate (self, obj)
def getJob (self, obj)
def onChanged (self, obj, prop)
def onDocumentRestored (self, obj)
def opOnChanged (self, obj, prop)
def opOnDocumentRestored (self, obj)
def opRejectAddBase (self, obj, base, sub)
def opUpdateDepths (self, obj)
def setDefaultValues (self, obj)
def setEditorModes (self, obj, features)
def updateDepths (self, obj, ignoreErrors=False)
Static Public Attributes
string DirectionClimb = 'Climb'
string DirectionConventional = 'Conventional'
list Directions = [DirectionClimb, DirectionConventional]
string LeftHand = 'LeftHand'
string RightHand = 'RightHand'
list ThreadOrientations = [LeftHand, RightHand]
string ThreadTypeCustom = 'Custom'
string ThreadTypeImperialInternal = 'Imperial - internal'
string ThreadTypeMetricInternal = 'Metric - internal'
list ThreadTypes = [ThreadTypeCustom, ThreadTypeMetricInternal, ThreadTypeImperialInternal]
Static Public Attributes inherited from PathScripts.PathCircularHoleBase.ObjectOp
bool defValsSet = False
bool docRestored = False
initOpFinalDepth = None
initOpStartDepth = None
bool initWithRotation = False
Additional Inherited Members
Public Attributes inherited from PathScripts.PathCircularHoleBase.ObjectOp
axialFeed
axialRapid
clearHeight
cloneNames
guiMsgs
rotateFlag
safeHeight
stockBB
Public Attributes inherited from PathScripts.PathOp.ObjectOp
addNewProps
commandlist
horizFeed
horizRapid
job
model
radius
stock
tool
vertFeed
vertRapid
Detailed Description
Proxy object for thread milling operation.
Member Function Documentation
circularHoleExecute()
def PathScripts.PathThreadMilling.ObjectThreadMilling.circularHoleExecute (self, obj, holes)
circularHoleExecute(obj, holes) ... implement processing of holes.
holes is a list of dictionaries with 'x', 'y' and 'r' specified for each hole.
Note that for Vertexes, non-circular Edges and Locations r=0.
Must be overwritten by subclasses.
Reimplemented from PathScripts.PathCircularHoleBase.ObjectOp.
References PathScripts.PathOp.ObjectOp.commandlist, PathScripts.PathThreadMilling.ObjectThreadMilling.executeThreadMill(), PathScripts.PathOp.ObjectOp.isToolSupported(), PathScripts.PathThreadMilling.ObjectThreadMilling.threadSetup(), and PathScripts.PathOp.ObjectOp.tool.
circularHoleFeatures()
def PathScripts.PathThreadMilling.ObjectThreadMilling.circularHoleFeatures (self, obj)
circularHoleFeatures(obj) ... overwrite to add operations specific features.
Can safely be overwritten by subclasses.
Reimplemented from PathScripts.PathCircularHoleBase.ObjectOp.
executeThreadMill()
def PathScripts.PathThreadMilling.ObjectThreadMilling.executeThreadMill (self, obj, loc, gcode, zStart, zFinal, pitch)
References PathScripts.PathOp.ObjectOp.commandlist, PathScripts.PathOp.ObjectOp.horizFeed, PathScripts.PathThreadMilling.internalThreadCommands(), PathScripts.PathThreadMilling.threadPasses(), PathScripts.PathOp.ObjectOp.tool, and PathScripts.PathOp.ObjectOp.vertRapid.
Referenced by PathScripts.PathThreadMilling.ObjectThreadMilling.circularHoleExecute().
initCircularHoleOperation()
def PathScripts.PathThreadMilling.ObjectThreadMilling.initCircularHoleOperation (self, obj)
initCircularHoleOperation(obj) ... overwrite if the subclass needs initialisation.
Can safely be overwritten by subclasses.
Reimplemented from PathScripts.PathCircularHoleBase.ObjectOp.
References PathScripts.PathThreadMilling.ObjectThreadMilling.Directions, PathScripts.PathThreadMilling.ObjectThreadMilling.ThreadOrientations, and PathScripts.PathThreadMilling.ObjectThreadMilling.ThreadTypes.
isToolSupported()
def PathScripts.PathThreadMilling.ObjectThreadMilling.isToolSupported (self, obj, tool)
Thread milling only supports thread milling cutters.
Reimplemented from PathScripts.PathOp.ObjectOp.
opSetDefaultValues()
def PathScripts.PathThreadMilling.ObjectThreadMilling.opSetDefaultValues (self, obj, job)
opSetDefaultValues(obj, job) ... overwrite to set initial default values.
Called after the receiver has been fully created with all properties.
Can safely be overwritten by subclasses.
Reimplemented from PathScripts.PathOp.ObjectOp.
References PathScripts.PathThreadMilling.ObjectThreadMilling.DirectionClimb, PathScripts.PathThreadMilling.ObjectThreadMilling.RightHand, and PathScripts.PathThreadMilling.ObjectThreadMilling.ThreadTypeMetricInternal.
threadDirectionCmd()
def PathScripts.PathThreadMilling.ObjectThreadMilling.threadDirectionCmd (self, obj)
References PathScripts.PathThreadMilling.ObjectThreadMilling.DirectionClimb, and PathScripts.PathThreadMilling.ObjectThreadMilling.RightHand.
threadFinalDepth()
def PathScripts.PathThreadMilling.ObjectThreadMilling.threadFinalDepth (self, obj)
References PathScripts.PathThreadMilling.ObjectThreadMilling.DirectionClimb, and PathScripts.PathThreadMilling.ObjectThreadMilling.RightHand.
threadPassRadii()
def PathScripts.PathThreadMilling.ObjectThreadMilling.threadPassRadii (self, obj)
References PathScripts.PathOp.ObjectOp.tool.
threadSetup()
def PathScripts.PathThreadMilling.ObjectThreadMilling.threadSetup (self, obj)
References PathScripts.PathThreadMilling.ObjectThreadMilling.DirectionClimb, and PathScripts.PathThreadMilling.ObjectThreadMilling.RightHand.
Referenced by PathScripts.PathThreadMilling.ObjectThreadMilling.circularHoleExecute().
threadStartDepth()
def PathScripts.PathThreadMilling.ObjectThreadMilling.threadStartDepth (self, obj)
References PathScripts.PathThreadMilling.ObjectThreadMilling.DirectionClimb, and PathScripts.PathThreadMilling.ObjectThreadMilling.RightHand.
Member Data Documentation
DirectionClimb
string PathScripts.PathThreadMilling.ObjectThreadMilling.DirectionClimb = 'Climb' static
Referenced by PathScripts.PathThreadMilling.ObjectThreadMilling.opSetDefaultValues(), PathScripts.PathThreadMilling.ObjectThreadMilling.threadDirectionCmd(), PathScripts.PathThreadMilling.ObjectThreadMilling.threadFinalDepth(), PathScripts.PathThreadMilling.ObjectThreadMilling.threadSetup(), and PathScripts.PathThreadMilling.ObjectThreadMilling.threadStartDepth().
DirectionConventional
string PathScripts.PathThreadMilling.ObjectThreadMilling.DirectionConventional = 'Conventional' static
Directions
list PathScripts.PathThreadMilling.ObjectThreadMilling.Directions = [DirectionClimb, DirectionConventional] static
Referenced by PathScripts.PathThreadMilling.ObjectThreadMilling.initCircularHoleOperation().
LeftHand
string PathScripts.PathThreadMilling.ObjectThreadMilling.LeftHand = 'LeftHand' static
RightHand
string PathScripts.PathThreadMilling.ObjectThreadMilling.RightHand = 'RightHand' static
Referenced by PathScripts.PathThreadMilling.ObjectThreadMilling.opSetDefaultValues(), PathScripts.PathThreadMilling.ObjectThreadMilling.threadDirectionCmd(), PathScripts.PathThreadMilling.ObjectThreadMilling.threadFinalDepth(), PathScripts.PathThreadMilling.ObjectThreadMilling.threadSetup(), and PathScripts.PathThreadMilling.ObjectThreadMilling.threadStartDepth().
ThreadOrientations
list PathScripts.PathThreadMilling.ObjectThreadMilling.ThreadOrientations = [LeftHand, RightHand] static
Referenced by PathScripts.PathThreadMilling.ObjectThreadMilling.initCircularHoleOperation().
ThreadTypeCustom
string PathScripts.PathThreadMilling.ObjectThreadMilling.ThreadTypeCustom = 'Custom' static
ThreadTypeImperialInternal
string PathScripts.PathThreadMilling.ObjectThreadMilling.ThreadTypeImperialInternal = 'Imperial - internal' static
ThreadTypeMetricInternal
string PathScripts.PathThreadMilling.ObjectThreadMilling.ThreadTypeMetricInternal = 'Metric - internal' static
Referenced by PathScripts.PathThreadMilling.ObjectThreadMilling.opSetDefaultValues().
ThreadTypes
list PathScripts.PathThreadMilling.ObjectThreadMilling.ThreadTypes = [ThreadTypeCustom, ThreadTypeMetricInternal, ThreadTypeImperialInternal] static
Referenced by PathScripts.PathThreadMilling.ObjectThreadMilling.initCircularHoleOperation().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Path/PathScripts/PathThreadMilling.py