FreeCAD: App::PropertyData::OffsetBase Struct Reference
App::PropertyData::OffsetBase Struct Reference
#include <PropertyContainer.h>
Public Member Functions
char * getOffset () const
short int getOffsetTo (const App::Property *prop) const
OffsetBase (const App::Extension *container)
OffsetBase (const App::PropertyContainer *container)
Constructor & Destructor Documentation
OffsetBase() [1/2]
App::PropertyData::OffsetBase::OffsetBase (const App::PropertyContainer * container)
OffsetBase() [2/2]
App::PropertyData::OffsetBase::OffsetBase (const App::Extension * container)
Member Function Documentation
getOffset()
char * App::PropertyData::OffsetBase::getOffset () const
Referenced by draftguitools.gui_selectplane.Draft_SelectPlane::display(), App::PropertyData::getPropertyByName(), App::PropertyData::getPropertyList(), App::PropertyData::getPropertyMap(), App::PropertyData::getPropertyNamedList(), draftguitools.gui_selectplane.Draft_SelectPlane::handle(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickAlign(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickFront(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickSide(), and draftguitools.gui_selectplane.Draft_SelectPlane::onClickTop().
getOffsetTo()
short int App::PropertyData::OffsetBase::getOffsetTo (const App::Property * prop) const
Referenced by App::PropertyData::addProperty(), and App::PropertyData::findProperty().
The documentation for this struct was generated from the following file:
FreeCAD/src/App/PropertyContainer.h