FreeCAD: Gui::ExpressionBindingPy Class Reference
Gui::ExpressionBindingPy Class Reference
#include <ExpressionBindingPy.h>
Public Member Functions
Py::Object apply (const Py::Tuple &)
Py::Object autoApply (const Py::Tuple &)
Py::Object bind (const Py::Tuple &)
ExpressionBindingPy (ExpressionBinding *)
Py::Object hasExpression (const Py::Tuple &)
Py::Object isBound (const Py::Tuple &)
Py::Object repr ()
Py::Object setAutoApply (const Py::Tuple &)
~ExpressionBindingPy ()
Static Public Member Functions
static void init_type (void)
Constructor & Destructor Documentation
ExpressionBindingPy()
ExpressionBindingPy::ExpressionBindingPy (ExpressionBinding * expr)
~ExpressionBindingPy()
ExpressionBindingPy::~ExpressionBindingPy ()
Member Function Documentation
apply()
Py::Object ExpressionBindingPy::apply (const Py::Tuple & args)
References Gui::ExpressionBinding::apply().
Referenced by init_type().
autoApply()
Py::Object ExpressionBindingPy::autoApply (const Py::Tuple & args)
References Gui::ExpressionBinding::autoApply().
Referenced by init_type().
bind()
Py::Object ExpressionBindingPy::bind (const Py::Tuple & args)
References Gui::ExpressionBinding::bind(), and App::ObjectIdentifier::parse().
Referenced by init_type().
hasExpression()
Py::Object ExpressionBindingPy::hasExpression (const Py::Tuple & args)
References Gui::ExpressionBinding::hasExpression().
Referenced by init_type().
init_type()
void ExpressionBindingPy::init_type (void) static
References apply(), autoApply(), bind(), hasExpression(), isBound(), and setAutoApply().
Referenced by Gui::Application::Application().
isBound()
Py::Object ExpressionBindingPy::isBound (const Py::Tuple & args)
References Gui::ExpressionBinding::isBound().
Referenced by init_type().
repr()
Py::Object ExpressionBindingPy::repr ()
setAutoApply()
Py::Object ExpressionBindingPy::setAutoApply (const Py::Tuple & args)
References Gui::ExpressionBinding::setAutoApply().
Referenced by init_type().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/ExpressionBindingPy.h
FreeCAD/src/Gui/ExpressionBindingPy.cpp