FreeCAD: Gui::ToolBarManager Class Reference
Gui::ToolBarManager Class Reference
The ToolBarManager class is responsible for the creation of toolbars and appending them to the main window.
#include <ToolBarManager.h>
Public Member Functions
void restoreState () const
void retranslate () const
void saveState () const
void setup (ToolBarItem *)
Sets up the toolbars of a given workbench.
Static Public Member Functions
static void destruct ()
static ToolBarManager * getInstance ()
The one and only instance.
Protected Member Functions
QAction * findAction (const QList< QAction * > &, const QString &) const
QToolBar * findToolBar (const QList< QToolBar * > &, const QString &) const
void setup (ToolBarItem *, QToolBar *) const
ToolBarManager ()
QList< QToolBar * > toolBars () const
Returns a list of all currently existing toolbars.
~ToolBarManager ()
Detailed Description
The ToolBarManager class is responsible for the creation of toolbars and appending them to the main window.
See also
ToolBoxManager
MenuManager
Author
Werner Mayer
Constructor & Destructor Documentation
ToolBarManager()
ToolBarManager::ToolBarManager () protected
Referenced by getInstance().
~ToolBarManager()
ToolBarManager::~ToolBarManager () protected
Member Function Documentation
destruct()
void ToolBarManager::destruct (void) static
Referenced by Gui::WorkbenchManager::~WorkbenchManager().
findAction()
QAction * ToolBarManager::findAction (const QList< QAction * > & acts, const QString & item) const protected
Referenced by setup().
findToolBar()
QToolBar * ToolBarManager::findToolBar (const QList< QToolBar * > & toolbars, const QString & item) const protected
Referenced by restoreState(), saveState(), and setup().
getInstance()
ToolBarManager * ToolBarManager::getInstance () static
The one and only instance.
References ToolBarManager().
Referenced by Gui::Workbench::activate(), Gui::MainWindow::loadWindowSettings(), Gui::Workbench::retranslate(), and Gui::MainWindow::saveWindowSettings().
restoreState()
void ToolBarManager::restoreState () const
References findToolBar(), App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), and toolBars().
Referenced by Gui::MainWindow::loadWindowSettings().
retranslate()
void ToolBarManager::retranslate () const
References toolBars(), and draftutils.translate::translate().
Referenced by Gui::Workbench::retranslate().
saveState()
void ToolBarManager::saveState () const
References findToolBar(), App::GetApplication(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), ParameterGrp::SetBool(), and toolBars().
Referenced by Gui::MainWindow::saveWindowSettings(), and setup().
setup() [1/2]
void ToolBarManager::setup (ToolBarItem * toolBarItems)
Sets up the toolbars of a given workbench.
References findToolBar(), App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), Gui::ToolBarItem::getItems(), Gui::getMainWindow(), App::Application::GetUserParameter(), saveState(), ParameterGrp::SetBool(), toolBars(), and draftutils.translate::translate().
Referenced by Gui::Workbench::activate(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::doExecute(), PathScripts.PathDressupDogbone.ObjectDressup::execute(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::generateTags(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::pointAtBottom(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::pointIsOnPath(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::setXyEnabled(), and PathScripts.PathDressupHoldingTags.ObjectTagDressup::supportsTagGeneration().
setup() [2/2]
void ToolBarManager::setup (ToolBarItem * item, QToolBar * toolbar) const protected
References Gui::CommandManager::addTo(), Gui::Application::commandManager(), findAction(), Gui::ToolBarItem::getItems(), and Gui::Application::Instance.
Referenced by PathScripts.PathDressupHoldingTags.ObjectTagDressup::doExecute(), PathScripts.PathDressupDogbone.ObjectDressup::execute(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::generateTags(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::pointAtBottom(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::pointIsOnPath(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::setXyEnabled(), and PathScripts.PathDressupHoldingTags.ObjectTagDressup::supportsTagGeneration().
toolBars()
QList< QToolBar * > ToolBarManager::toolBars () const protected
Returns a list of all currently existing toolbars.
References Gui::getMainWindow().
Referenced by restoreState(), retranslate(), saveState(), and setup().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/ToolBarManager.h
Sources/FreeCAD/src/Gui/ToolBarManager.cpp