FreeCAD: App::ColorLegend Class Reference
App::ColorLegend Class Reference
#include <ColorModel.h>
Public Member Functions
std::size_t addMax (const std::string &rclName)
std::size_t addMin (const std::string &rclName)
ColorLegend ()
ColorLegend (const ColorLegend &rclCL)
Color getColor (float fVal) const
Color getColor (std::size_t ulPos) const
std::size_t getColorIndex (float fVal) const
float getMaxValue () const
float getMinValue () const
uint32_t getPackedColor (std::size_t ulPos) const
std::string getText (std::size_t ulPos) const
float getValue (std::size_t ulPos) const
std::size_t hasNumberOfFields () const
bool isOutsideGrayed () const
bool operator!= (const ColorLegend &rclCL) const
ColorLegend & operator= (const ColorLegend &rclCL)
bool operator== (const ColorLegend &rclCL) const
bool remove (std::size_t ulPos)
void removeFirst ()
void removeLast ()
void resize (std::size_t ulN)
bool setColor (std::size_t ulPos, float ucRed, float ucGreen, float ucBlue)
bool setColor (std::size_t ulPos, unsigned long ulColor)
void setOutsideGrayed (bool bOS)
bool setText (std::size_t ulPos, const std::string &rclName)
bool setValue (std::size_t ulPos, float fVal)
virtual ~ColorLegend ()
Protected Attributes
std::deque< Color > colorFields
std::deque< std::string > names
bool outsideGrayed
std::deque< float > values
Constructor & Destructor Documentation
ColorLegend() [1/2]
ColorLegend::ColorLegend ()
References colorFields.
ColorLegend() [2/2]
ColorLegend::ColorLegend (const ColorLegend & rclCL)
~ColorLegend()
virtual App::ColorLegend::~ColorLegend () virtual
Member Function Documentation
addMax()
std::size_t ColorLegend::addMax (const std::string & rclName)
References App::Color::b, colorFields, App::Color::g, and App::Color::r.
addMin()
std::size_t ColorLegend::addMin (const std::string & rclName)
References App::Color::b, colorFields, App::Color::g, and App::Color::r.
Referenced by resize().
getColor() [1/2]
Color App::ColorLegend::getColor (float fVal) const
References colorFields, and outsideGrayed.
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::getPrefColor(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::setValues().
getColor() [2/2]
Color ColorLegend::getColor (std::size_t ulPos) const
References colorFields.
Referenced by getPackedColor(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::getPrefColor(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::setValues().
getColorIndex()
std::size_t App::ColorLegend::getColorIndex (float fVal) const
References colorFields.
getMaxValue()
float App::ColorLegend::getMaxValue () const
getMinValue()
float App::ColorLegend::getMinValue () const
getPackedColor()
uint32_t ColorLegend::getPackedColor (std::size_t ulPos) const
References getColor(), and App::Color::getPackedValue().
getText()
std::string ColorLegend::getText (std::size_t ulPos) const
getValue()
float ColorLegend::getValue (std::size_t ulPos) const
hasNumberOfFields()
std::size_t App::ColorLegend::hasNumberOfFields () const
isOutsideGrayed()
bool App::ColorLegend::isOutsideGrayed () const
operator!=()
bool App::ColorLegend::operator!= (const ColorLegend & rclCL) const
operator=()
ColorLegend & ColorLegend::operator= (const ColorLegend & rclCL)
References colorFields, names, outsideGrayed, and values.
operator==()
bool ColorLegend::operator== (const ColorLegend & rclCL) const
References colorFields, names, outsideGrayed, and values.
remove()
bool ColorLegend::remove (std::size_t ulPos)
References colorFields.
removeFirst()
void ColorLegend::removeFirst ()
References colorFields.
removeLast()
void ColorLegend::removeLast ()
References colorFields.
Referenced by resize().
resize()
void ColorLegend::resize (std::size_t ulN)
References addMin(), colorFields, and removeLast().
setColor() [1/2]
bool ColorLegend::setColor (std::size_t ulPos, float ucRed, float ucGreen, float ucBlue)
References colorFields.
Referenced by setColor().
setColor() [2/2]
bool ColorLegend::setColor (std::size_t ulPos, unsigned long ulColor)
References setColor().
setOutsideGrayed()
void App::ColorLegend::setOutsideGrayed (bool bOS)
setText()
bool ColorLegend::setText (std::size_t ulPos, const std::string & rclName)
setValue()
bool ColorLegend::setValue (std::size_t ulPos, float fVal)
Member Data Documentation
colorFields
std::deque<Color> App::ColorLegend::colorFields protected
Referenced by addMax(), addMin(), ColorLegend(), getColor(), getColorIndex(), operator=(), operator==(), remove(), removeFirst(), removeLast(), resize(), and setColor().
names
std::deque<std::string> App::ColorLegend::names protected
Referenced by operator=(), and operator==().
outsideGrayed
bool App::ColorLegend::outsideGrayed protected
Referenced by getColor(), operator=(), and operator==().
values
std::deque<float> App::ColorLegend::values protected
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::addInterval(), operator=(), operator==(), ifc4.ifcstructuralloadconfiguration::validlistsize(), and Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::value().
The documentation for this class was generated from the following files:
FreeCAD/src/App/ColorModel.h
FreeCAD/src/App/ColorModel.cpp