FreeCAD: Gui::SoQtOffscreenRendererPy Class Reference
Gui::SoQtOffscreenRendererPy Class Reference
#include <SoFCOffscreenRenderer.h>
Public Member Functions
Py::Object getBackgroundColor (const Py::Tuple &)
Py::Object getInternalTextureFormat (const Py::Tuple &)
Py::Object getNumPasses (const Py::Tuple &)
Py::Object getViewportRegion (const Py::Tuple &)
Py::Object getWriteImageFiletypeInfo (const Py::Tuple &)
Py::Object render (const Py::Tuple &)
Py::Object repr ()
Py::Object setBackgroundColor (const Py::Tuple &)
Py::Object setInternalTextureFormat (const Py::Tuple &)
Py::Object setNumPasses (const Py::Tuple &)
Py::Object setViewportRegion (const Py::Tuple &)
SoQtOffscreenRendererPy (const SbViewportRegion &)
Py::Object writeToImage (const Py::Tuple &)
~SoQtOffscreenRendererPy ()
Static Public Member Functions
static void init_type ()
Constructor & Destructor Documentation
SoQtOffscreenRendererPy()
SoQtOffscreenRendererPy::SoQtOffscreenRendererPy (const SbViewportRegion & vpr)
~SoQtOffscreenRendererPy()
SoQtOffscreenRendererPy::~SoQtOffscreenRendererPy ()
Member Function Documentation
getBackgroundColor()
Py::Object SoQtOffscreenRendererPy::getBackgroundColor (const Py::Tuple & args)
References Gui::SoQtOffscreenRenderer::getBackgroundColor().
Referenced by init_type().
getInternalTextureFormat()
Py::Object SoQtOffscreenRendererPy::getInternalTextureFormat (const Py::Tuple & args)
References Gui::SoQtOffscreenRenderer::internalTextureFormat().
Referenced by init_type().
getNumPasses()
Py::Object SoQtOffscreenRendererPy::getNumPasses (const Py::Tuple & args)
References Gui::SoQtOffscreenRenderer::getNumPasses().
Referenced by init_type().
getViewportRegion()
Py::Object SoQtOffscreenRendererPy::getViewportRegion (const Py::Tuple & args)
References Gui::SoQtOffscreenRenderer::getViewportRegion().
Referenced by init_type().
getWriteImageFiletypeInfo()
Py::Object SoQtOffscreenRendererPy::getWriteImageFiletypeInfo (const Py::Tuple & args)
References Gui::SoQtOffscreenRenderer::getWriteImageFiletypeInfo().
Referenced by init_type().
init_type()
void SoQtOffscreenRendererPy::init_type (void) static
References getBackgroundColor(), getInternalTextureFormat(), getNumPasses(), getViewportRegion(), getWriteImageFiletypeInfo(), render(), setBackgroundColor(), setInternalTextureFormat(), setNumPasses(), setViewportRegion(), and writeToImage().
Referenced by Gui::Application::Application().
render()
Py::Object SoQtOffscreenRendererPy::render (const Py::Tuple & args)
References Base::InterpreterSingleton::convertSWIGPointerObj(), Base::Interpreter(), and Gui::SoQtOffscreenRenderer::render().
Referenced by init_type().
repr()
Py::Object SoQtOffscreenRendererPy::repr ()
setBackgroundColor()
Py::Object SoQtOffscreenRendererPy::setBackgroundColor (const Py::Tuple & args)
References Gui::SoQtOffscreenRenderer::setBackgroundColor().
Referenced by init_type().
setInternalTextureFormat()
Py::Object SoQtOffscreenRendererPy::setInternalTextureFormat (const Py::Tuple & args)
References Gui::SoQtOffscreenRenderer::setInternalTextureFormat().
Referenced by init_type().
setNumPasses()
Py::Object SoQtOffscreenRendererPy::setNumPasses (const Py::Tuple & args)
References Gui::SoQtOffscreenRenderer::setNumPasses().
Referenced by init_type().
setViewportRegion()
Py::Object SoQtOffscreenRendererPy::setViewportRegion (const Py::Tuple & args)
References Gui::SoQtOffscreenRenderer::setViewportRegion().
Referenced by init_type().
writeToImage()
Py::Object SoQtOffscreenRendererPy::writeToImage (const Py::Tuple & args)
References Gui::SoQtOffscreenRenderer::writeToImage().
Referenced by init_type().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/SoFCOffscreenRenderer.h
FreeCAD/src/Gui/SoFCOffscreenRenderer.cpp