FreeCAD: nlohmann::detail::index_sequence< Ints > Struct Template Reference
nlohmann::detail::index_sequence< Ints > Struct Template Reference
#include <json.hpp>
Public Types
using type = index_sequence
using value_type = std::size_t
Static Public Member Functions
static constexpr std::size_t size () noexcept
Member Typedef Documentation
type
template<std::size_t... Ints> using nlohmann::detail::index_sequence< Ints >::type = index_sequence
value_type
template<std::size_t... Ints> using nlohmann::detail::index_sequence< Ints >::value_type = std::size_t
Member Function Documentation
size()
template<std::size_t... Ints> static constexpr std::size_t nlohmann::detail::index_sequence< Ints >::size (void) static constexpr noexcept
Referenced by gzip_utf8.GzipFile::close(), PathScripts.PostUtils.GCodeEditorDialog::done(), and gzip_utf8.GzipFile::write().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/Mod/PartDesign/App/json.hpp