FreeCAD: Part::MakePrismPy Class Reference
Part::MakePrismPy Class Reference
The python export class for BRepFeat_MakePrism.
#include <MakePrismPy.h>
Public Types
typedef BRepFeat_MakePrism * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
MakePrismPy (BRepFeat_MakePrism *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BRepFeat_MakePrism * getBRepFeat_MakePrismPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of MakePrismPy.
static PyMethodDef Methods []
Methods structure of MakePrismPy.
static PyTypeObject Type
Type structure of MakePrismPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~MakePrismPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * init (PyObject *args, PyObject *kwd)
implementer for the init() method
PyObject * add (PyObject *args, PyObject *kwd)
implementer for the add() method
PyObject * perform (PyObject *args, PyObject *kwd)
implementer for the perform() method
PyObject * performUntilEnd (PyObject *args)
implementer for the performUntilEnd() method
PyObject * performFromEnd (PyObject *args)
implementer for the performFromEnd() method
PyObject * performThruAll (PyObject *args)
implementer for the performThruAll() method
PyObject * performUntilHeight (PyObject *args)
implementer for the performUntilHeight() method
PyObject * curves (PyObject *args)
implementer for the curves() method
PyObject * barycCurve (PyObject *args)
implementer for the barycCurve() method
PyObject * shape (PyObject *args)
implementer for the shape() method
static PyObject * staticCallback_init (PyObject *self, PyObject *args, PyObject *kwd)
callback for the init() method
static PyObject * staticCallback_add (PyObject *self, PyObject *args, PyObject *kwd)
callback for the add() method
static PyObject * staticCallback_perform (PyObject *self, PyObject *args, PyObject *kwd)
callback for the perform() method
static PyObject * staticCallback_performUntilEnd (PyObject *self, PyObject *args)
callback for the performUntilEnd() method
static PyObject * staticCallback_performFromEnd (PyObject *self, PyObject *args)
callback for the performFromEnd() method
static PyObject * staticCallback_performThruAll (PyObject *self, PyObject *args)
callback for the performThruAll() method
static PyObject * staticCallback_performUntilHeight (PyObject *self, PyObject *args)
callback for the performUntilHeight() method
static PyObject * staticCallback_curves (PyObject *self, PyObject *args)
callback for the curves() method
static PyObject * staticCallback_barycCurve (PyObject *self, PyObject *args)
callback for the barycCurve() method
static PyObject * staticCallback_shape (PyObject *self, PyObject *args)
callback for the shape() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for BRepFeat_MakePrism.
Member Typedef Documentation
PointerType
typedef BRepFeat_MakePrism* Part::MakePrismPy::PointerType
Constructor & Destructor Documentation
~MakePrismPy()
MakePrismPy::~MakePrismPy () protected
MakePrismPy()
MakePrismPy::MakePrismPy (BRepFeat_MakePrism * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
add()
PyObject * MakePrismPy::add (PyObject * args, PyObject * kwd)
implementer for the add() method
References getBRepFeat_MakePrismPtr(), Part::TopoShapeEdgePy::Type, and Part::TopoShapeFacePy::Type.
Referenced by staticCallback_add().
barycCurve()
PyObject * MakePrismPy::barycCurve (PyObject * args)
implementer for the barycCurve() method
References getBRepFeat_MakePrismPtr(), Base::BaseClass::getPyObject(), and Part::makeFromCurve().
Referenced by staticCallback_barycCurve().
curves()
PyObject * MakePrismPy::curves (PyObject * args)
implementer for the curves() method
References getBRepFeat_MakePrismPtr(), Base::BaseClass::getPyObject(), and Part::makeFromCurve().
Referenced by staticCallback_curves().
getBRepFeat_MakePrismPtr()
BRepFeat_MakePrism * MakePrismPy::getBRepFeat_MakePrismPtr (void) const
getter for the object handled by this class
Referenced by add(), barycCurve(), curves(), init(), perform(), performFromEnd(), performThruAll(), performUntilEnd(), performUntilHeight(), and shape().
getCustomAttributes()
PyObject * MakePrismPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
GetType()
virtual PyTypeObject* Part::MakePrismPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
init()
PyObject * MakePrismPy::init (PyObject * args, PyObject * kwd)
implementer for the init() method
References getBRepFeat_MakePrismPtr(), Base::VectorPy::Type, Part::TopoShapeFacePy::Type, Part::TopoShapePy::Type, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by staticCallback_init().
perform()
PyObject * MakePrismPy::perform (PyObject * args, PyObject * kwd)
implementer for the perform() method
References getBRepFeat_MakePrismPtr(), and Part::TopoShapePy::Type.
Referenced by staticCallback_perform().
performFromEnd()
PyObject * MakePrismPy::performFromEnd (PyObject * args)
implementer for the performFromEnd() method
References getBRepFeat_MakePrismPtr(), and Part::TopoShapePy::Type.
Referenced by staticCallback_performFromEnd().
performThruAll()
PyObject * MakePrismPy::performThruAll (PyObject * args)
implementer for the performThruAll() method
References getBRepFeat_MakePrismPtr().
Referenced by staticCallback_performThruAll().
performUntilEnd()
PyObject * MakePrismPy::performUntilEnd (PyObject * args)
implementer for the performUntilEnd() method
References getBRepFeat_MakePrismPtr().
Referenced by staticCallback_performUntilEnd().
performUntilHeight()
PyObject * MakePrismPy::performUntilHeight (PyObject * args)
implementer for the performUntilHeight() method
References getBRepFeat_MakePrismPtr(), and Part::TopoShapePy::Type.
Referenced by staticCallback_performUntilHeight().
PyInit()
int MakePrismPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
References Base::PyObjectBase::setTwinPointer(), Base::VectorPy::Type, Part::TopoShapeFacePy::Type, Part::TopoShapePy::Type, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
PyMake()
PyObject * MakePrismPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References MakePrismPy().
representation()
std::string MakePrismPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int MakePrismPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
shape()
PyObject * MakePrismPy::shape (PyObject * args)
implementer for the shape() method
References getBRepFeat_MakePrismPtr().
Referenced by staticCallback_shape().
staticCallback_add()
PyObject * MakePrismPy::staticCallback_add (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the add() method
References add(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_barycCurve()
PyObject * MakePrismPy::staticCallback_barycCurve (PyObject * self, PyObject * args) static
callback for the barycCurve() method
References barycCurve(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_curves()
PyObject * MakePrismPy::staticCallback_curves (PyObject * self, PyObject * args) static
callback for the curves() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, curves(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_init()
PyObject * MakePrismPy::staticCallback_init (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the init() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, init(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_perform()
PyObject * MakePrismPy::staticCallback_perform (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the perform() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), perform(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_performFromEnd()
PyObject * MakePrismPy::staticCallback_performFromEnd (PyObject * self, PyObject * args) static
callback for the performFromEnd() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), performFromEnd(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_performThruAll()
PyObject * MakePrismPy::staticCallback_performThruAll (PyObject * self, PyObject * args) static
callback for the performThruAll() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), performThruAll(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_performUntilEnd()
PyObject * MakePrismPy::staticCallback_performUntilEnd (PyObject * self, PyObject * args) static
callback for the performUntilEnd() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), performUntilEnd(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_performUntilHeight()
PyObject * MakePrismPy::staticCallback_performUntilHeight (PyObject * self, PyObject * args) static
callback for the performUntilHeight() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), performUntilHeight(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_shape()
PyObject * MakePrismPy::staticCallback_shape (PyObject * self, PyObject * args) static
callback for the shape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and shape().
Member Data Documentation
GetterSetter
PyGetSetDef MakePrismPy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of MakePrismPy.
Methods
PyMethodDef MakePrismPy::Methods static
Methods structure of MakePrismPy.
Type
PyTypeObject MakePrismPy::Type static
Type structure of MakePrismPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/BRepFeat/MakePrismPy.h
Sources/FreeCAD/src/Mod/Part/App/BRepFeat/MakePrismPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/BRepFeat/MakePrismPy.cpp