FreeCAD: Spaceball::ButtonEvent Class Reference
Spaceball::ButtonEvent Class Reference
#include <SpaceballEvent.h>
Public Member Functions
ButtonEvent ()
ButtonEvent (const ButtonEvent &in)
int buttonNumber ()
ButtonStateType buttonStatus ()
ButtonEvent & operator= (const ButtonEvent &in)
void setButtonNumber (const int &buttonNumberIn)
void setButtonStatus (const ButtonStateType &buttonStatusIn)
Public Member Functions inherited from Spaceball::EventBase
bool isHandled ()
void setHandled (bool sig)
Static Public Attributes
static int ButtonEventType = -1
Additional Inherited Members
Protected Member Functions inherited from Spaceball::EventBase
EventBase (QEvent::Type event)
Protected Attributes inherited from Spaceball::EventBase
bool handled
Constructor & Destructor Documentation
ButtonEvent() [1/2]
ButtonEvent::ButtonEvent ()
ButtonEvent() [2/2]
ButtonEvent::ButtonEvent (const ButtonEvent & in)
References Spaceball::EventBase::handled.
Member Function Documentation
buttonNumber()
int ButtonEvent::buttonNumber ()
Referenced by Gui::MainWindow::event(), and Gui::Dialog::DlgCustomizeSpaceball::event().
buttonStatus()
ButtonStateType ButtonEvent::buttonStatus ()
Referenced by Gui::MainWindow::event(), and Gui::Dialog::DlgCustomizeSpaceball::event().
operator=()
ButtonEvent & ButtonEvent::operator= (const ButtonEvent & in)
References Spaceball::EventBase::handled.
setButtonNumber()
void ButtonEvent::setButtonNumber (const int & buttonNumberIn)
Referenced by Gui::GUIApplicationNativeEventAware::postButtonEvent().
setButtonStatus()
void ButtonEvent::setButtonStatus (const ButtonStateType & buttonStatusIn)
Referenced by Gui::GUIApplicationNativeEventAware::postButtonEvent().
Member Data Documentation
ButtonEventType
int ButtonEvent::ButtonEventType = -1 static
Referenced by Gui::MainWindow::event(), Gui::Dialog::DlgCustomizeSpaceball::event(), Gui::ViewerEventFilter::eventFilter(), Gui::GUIApplicationNativeEventAware::initSpaceball(), Gui::GUIApplication::notify(), and Gui::GUIApplicationNativeEventAware::processSpaceballEvent().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SpaceballEvent.h
Sources/FreeCAD/src/Gui/SpaceballEvent.cpp