FreeCAD: Part::Geom2dConic Class Reference
Part::Geom2dConic Class Reference abstract
#include <Geometry2d.h>
Public Member Functions
virtual Geometry2d * clone (void) const =0
returns a cloned object
Base::Vector2d getLocation (void) const
virtual unsigned int getMemSize (void) const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual PyObject * getPyObject (void)=0
This method returns the Python wrapper for a C++ object.
const Handle (Geom2d_Geometry) &handle() const =0
bool isReversed () const
void setLocation (const Base::Vector2d &Center)
virtual ~Geom2dConic ()
Public Member Functions inherited from Part::Geom2dCurve
bool closestParameter (const Base::Vector2d &point, double &u) const
bool closestParameterToBasicCurve (const Base::Vector2d &point, double &u) const
Base::Vector2d firstDerivativeAtParameter (double u) const
Geom2dCurve ()
bool normal (double u, gp_Dir2d &dir) const
Base::Vector2d pointAtParameter (double u) const
Base::Vector2d secondDerivativeAtParameter (double u) const
bool tangent (double u, gp_Dir2d &) const
virtual TopoDS_Shape toShape () const
virtual ~Geom2dCurve ()
Public Member Functions inherited from Part::Geometry2d
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
virtual ~Geometry2d ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Member Functions
Geom2dConic ()
void RestoreAxis (Base::XMLReader &reader, gp_Ax22d &)
void SaveAxis (Base::Writer &writer, const gp_Ax22d &) const
Protected Member Functions inherited from Part::Geometry2d
Geometry2d ()
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
Geom2dConic()
Geom2dConic::Geom2dConic () protected
~Geom2dConic()
Geom2dConic::~Geom2dConic () virtual
Member Function Documentation
clone()
virtual Geometry2d* Part::Geom2dConic::clone (void) const pure virtual
returns a cloned object
Implements Part::Geometry2d.
Implemented in Part::Geom2dParabola, Part::Geom2dHyperbola, Part::Geom2dEllipse, and Part::Geom2dCircle.
Referenced by ArchPanel.CommandPanelSheet::Activated(), and Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated().
getLocation()
Base::Vector2d Geom2dConic::getLocation (void) const
Referenced by Part::Conic2dPy::getLocation().
getMemSize()
virtual unsigned int Part::Geom2dConic::getMemSize (void) const pure virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Part::Geometry2d.
Implemented in Part::Geom2dParabola, Part::Geom2dHyperbola, Part::Geom2dEllipse, and Part::Geom2dCircle.
getPyObject()
virtual PyObject* Part::Geom2dConic::getPyObject (void) pure virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Implemented in Part::Geom2dParabola, Part::Geom2dHyperbola, Part::Geom2dEllipse, and Part::Geom2dCircle.
Handle()
const Part::Geom2dConic::Handle (Geom2d_Geometry) const & pure virtual
Implements Part::Geometry2d.
Implemented in Part::Geom2dParabola, Part::Geom2dHyperbola, Part::Geom2dEllipse, and Part::Geom2dCircle.
isReversed()
bool Geom2dConic::isReversed () const
References Base::Vector3< _Precision >::Cross(), and Base::Vector3< _Precision >::z.
RestoreAxis()
void Geom2dConic::RestoreAxis (Base::XMLReader & reader, gp_Ax22d & axis) protected
References Base::XMLReader::getAttributeAsFloat().
SaveAxis()
void Geom2dConic::SaveAxis (Base::Writer & writer, const gp_Ax22d & axis) const protected
References Base::Writer::Stream().
setLocation()
void Geom2dConic::setLocation (const Base::Vector2d & Center)
References Base::Vector2d::x, and Base::Vector2d::y.
Referenced by Part::Conic2dPy::setLocation().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/App/Geometry2d.h
Sources/FreeCAD/src/Mod/Part/App/Geometry2d.cpp