FreeCAD: Gui::SelectionFilterPy Class Reference
Gui::SelectionFilterPy Class Reference
Python binding for SelectionFilter class.
#include <SelectionFilter.h>
Public Member Functions
Py::Object match (const Py::Tuple &)
Py::Object repr ()
Py::Object result (const Py::Tuple &)
SelectionFilterPy (const std::string &)
Py::Object setFilter (const Py::Tuple &)
Py::Object test (const Py::Tuple &)
~SelectionFilterPy ()
Static Public Member Functions
static void init_type (void)
Public Attributes
SelectionFilter filter
Detailed Description
Python binding for SelectionFilter class.
filter=Gui.Selection.Filter("SELECT Part::Feature SUBELEMENT Edge")
Gui.Selection.addSelectionGate(filter)
See also
SelectionFilter
Author
Werner Mayer
Constructor & Destructor Documentation
SelectionFilterPy()
SelectionFilterPy::SelectionFilterPy (const std::string & s)
~SelectionFilterPy()
SelectionFilterPy::~SelectionFilterPy ()
Member Function Documentation
init_type()
void SelectionFilterPy::init_type (void) static
References match(), result(), setFilter(), and test().
Referenced by Gui::Application::Application().
match()
Py::Object SelectionFilterPy::match (const Py::Tuple & args)
Referenced by init_type().
repr()
Py::Object SelectionFilterPy::repr ()
result()
Py::Object SelectionFilterPy::result (const Py::Tuple &)
Referenced by init_type().
setFilter()
Py::Object SelectionFilterPy::setFilter (const Py::Tuple & args)
Referenced by init_type().
test()
Py::Object SelectionFilterPy::test (const Py::Tuple & args)
Referenced by init_type().
Member Data Documentation
filter
SelectionFilter Gui::SelectionFilterPy::filter
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/SelectionFilter.h
FreeCAD/src/Gui/SelectionFilter.cpp