FreeCAD: App::PropertyPlacement Class Reference
App::PropertyPlacement Class Reference
Property representing a placement.
#include <PropertyGeo.h>
Public Member Functions
virtual Property * Copy (void) const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
const char * getEditorName (void) const override
Get the class name of the associated property editor item.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
void getPaths (std::vector< ObjectIdentifier > &paths) const override
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const ObjectIdentifier &path) const override
Get value of property.
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
virtual bool getPyPathValue (const ObjectIdentifier &path, Py::Object &res) const override
Get Python value of property.
const Base::Placement & getValue (void) const
This method returns a string representation of the property.
virtual bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
virtual void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
PropertyPlacement ()
A constructor.
virtual void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
void setPathValue (const ObjectIdentifier &path, const boost::any &value) override
Set value of property.
virtual void setPyObject (PyObject *) override
void setValue (const Base::Placement &pos)
Sets the property.
bool setValueIfChanged (const Base::Placement &pos, double tol=1e-7, double atol=1e-12)
Sets property only if changed.
virtual ~PropertyPlacement ()
A destructor.
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual Property * Copy (void) const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
int64_t getID () const
Return a unique ID for the property.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const char * getName (void) const
Get the name of this property in the belonging container With hasName() it can be checked beforehand if a valid name is set.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
bool hasName () const
Check if the property has a name set.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Static Public Attributes
static const Placement Null
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , Busy = 15 ,
CopyOnChange = 16 , UserEdit = 17 , PropStaticBegin = 21 , PropDynamic = 21 ,
PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 , PropTransient = 25 ,
PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 , User1 = 28 ,
User2 = 29 , User3 = 30 , User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Check if the passed name is valid.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Detailed Description
Property representing a placement.
Encapsulates a Base::Placement in a Property
Constructor & Destructor Documentation
PropertyPlacement()
PropertyPlacement::PropertyPlacement ()
A constructor.
A more elaborate description of the constructor.
Referenced by Copy().
~PropertyPlacement()
PropertyPlacement::~PropertyPlacement () virtual
A destructor.
A more elaborate description of the destructor.
Member Function Documentation
Copy()
Property * PropertyPlacement::Copy (void) const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References PropertyPlacement().
getEditorName()
const char * App::PropertyPlacement::getEditorName (void) const override virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
getMemSize()
virtual unsigned int App::PropertyPlacement::getMemSize (void) const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
See also
Base::Persistence
Reimplemented from App::Property.
getPaths()
void PropertyPlacement::getPaths (std::vector< ObjectIdentifier > & paths) const override virtual
Get valid paths for this property; used by auto completer.
Reimplemented from App::Property.
References App::ObjectIdentifier::SimpleComponent().
getPathValue()
const boost::any PropertyPlacement::getPathValue (const ObjectIdentifier & path) const override virtual
Get value of property.
Reimplemented from App::Property.
References App::Property::getPathValue(), and Base::toDegrees().
getPyObject()
PyObject * PropertyPlacement::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
getPyPathValue()
bool PropertyPlacement::getPyPathValue (const ObjectIdentifier & , Py::Object &) const override virtual
Get Python value of property.
Reimplemented from App::Property.
References DraftVecUtils::angle(), and Base::toDegrees().
getValue()
const Base::Placement & PropertyPlacement::getValue (void) const
This method returns a string representation of the property.
Referenced by PartGui::TaskDlgAttacher::accept(), Import::ExportOCAF::createNode(), RobotGui::ViewProviderRobotObject::DraggerMotionCallback(), Gui::TreeWidget::dropEvent(), Mesh::Sphere::execute(), Mesh::Ellipsoid::execute(), Mesh::Cylinder::execute(), Mesh::Cone::execute(), Mesh::Torus::execute(), Mesh::Cube::execute(), Path::FeatureCompound::execute(), Robot::TrajectoryDressUpObject::execute(), App::GeoFeatureGroupExtension::extensionGetSubObject(), App::OriginGroupExtension::extensionGetSubObject(), PartDesignGui::fixSketchSupport(), PartDesign::ProfileBased::getAxis(), Part::Datum::getBasePoint(), PartDesign::Line::getDirection(), Part::Feature::getLocation(), Part::FeatureReference::getLocation(), PartDesign::Plane::getNormal(), Sketcher::SketchAnalysis::getOpenVertices(), PartDesign::Point::getPoint(), Part::Datum::getShape(), Part::Datum::getSubObject(), Part::Feature::getSubObject(), PartDesign::Body::getSubObject(), PartDesign::CoordinateSystem::getSubObject(), PartDesign::SubShapeBinder::getSubObject(), PartDesign::LinearPattern::getTransformations(), PartDesign::Mirrored::getTransformations(), PartDesign::PolarPattern::getTransformations(), PartDesign::CoordinateSystem::getXAxis(), PartDesign::CoordinateSystem::getYAxis(), PartDesign::CoordinateSystem::getZAxis(), PartDesign::ShapeBinder::hasPlacementChanged(), Gui::ViewProviderLink::initDraggingPlacement(), Sketcher::SketchObject::isCarbonCopyAllowed(), PartGui::Location::Location(), Mesh::Feature::onChanged(), Points::Feature::onChanged(), Robot::RobotObject::onChanged(), Part::Feature::onChanged(), PartGui::SectionCut::onCutXvalueChanged(), PartGui::SectionCut::onCutYvalueChanged(), PartGui::SectionCut::onCutZvalueChanged(), Part::Compound2::onDocumentRestored(), PartDesign::DressUp::positionByBaseFeature(), PartDesign::ProfileBased::positionByPrevious(), PartDesign::MultiTransform::positionBySupport(), PartDesign::Transformed::positionBySupport(), Attacher::AttachEngine::readLinks(), Sketcher::SketchObject::rebuildExternalGeometry(), PathGui::ViewProviderPath::recomputeBoundingBox(), Robot::RobotObject::Restore(), Part::Box::Restore(), Import::ExportOCAF::saveShape(), PartGui::SectionCut::SectionCut(), RobotGui::ViewProviderRobotObject::setAxisTo(), RobotGui::ViewProviderRobotObject::setDragger(), Gui::ViewProviderDragger::setEdit(), Gui::ViewProviderDragger::setEditViewer(), PartDesignGui::ViewProviderDatumLine::setExtents(), PartDesignGui::ViewProviderDatumPlane::setExtents(), RobotGui::TaskRobot6Axis::setRobot(), RobotGui::TaskTrajectory::setTo(), RobotGui::TaskTrajectory::TaskTrajectory(), RobotGui::TaskTrajectoryDressUpParameter::TaskTrajectoryDressUpParameter(), RobotGui::TrajectorySimulate::TrajectorySimulate(), App::GeoFeatureGroupExtension::transformPlacement(), PartDesign::SubShapeBinder::update(), Gui::ViewProviderInventorObject::updateData(), Gui::ViewProviderVRMLObject::updateData(), RobotGui::ViewProviderRobotObject::updateData(), RobotGui::ViewProviderTrajectory::updateData(), and PartDesign::ShapeBinder::updatedShape().
isSame()
virtual bool App::PropertyPlacement::isSame (const Property & other) const override virtual
Compare if this property has the same content as the given one.
Reimplemented from App::Property.
References Base::Persistence::getTypeId().
Paste()
void PropertyPlacement::Paste (const Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Restore()
void PropertyPlacement::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References App::Property::aboutToSetValue(), Base::XMLReader::getAttributeAsFloat(), Base::XMLReader::hasAttribute(), App::Property::hasSetValue(), and Base::XMLReader::readElement().
Referenced by Part::AttachExtension::extHandleChangedPropertyName().
Save()
void PropertyPlacement::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References Base::Writer::ind(), Base::Writer::Stream(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
setPathValue()
void PropertyPlacement::setPathValue (const ObjectIdentifier & path, const boost::any & value) override virtual
Set value of property.
Reimplemented from App::Property.
References App::Property::setPathValue(), and Base::toRadians().
setPyObject()
void PropertyPlacement::setPyObject (PyObject * value) override virtual
Reimplemented from Base::BaseClass.
References Base::Placement::fromMatrix(), and setValue().
Referenced by App::PropertyPlacementList::getPyValue().
setValue()
void PropertyPlacement::setValue (const Base::Placement & pos)
Sets the property.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Referenced by RobotGui::ViewProviderRobotObject::DraggerMotionCallback(), Part::Reverse::execute(), PartDesign::ShapeBinder::execute(), Mesh::Feature::onChanged(), Points::Feature::onChanged(), Robot::RobotObject::onChanged(), Part::Feature::onChanged(), PartGui::SectionCut::onCutXvalueChanged(), PartGui::SectionCut::onCutYvalueChanged(), PartGui::SectionCut::onCutZvalueChanged(), Part::Compound2::onDocumentRestored(), PartDesign::DressUp::positionByBaseFeature(), PartDesign::ProfileBased::positionByPrevious(), Part::AttachExtension::positionBySupport(), PartDesign::MultiTransform::positionBySupport(), PartDesign::Transformed::positionBySupport(), Robot::RobotObject::Restore(), Part::Box::Restore(), setPyObject(), App::Origin::setupObject(), setValueIfChanged(), App::GeoFeatureGroupExtension::transformPlacement(), PartDesign::SubShapeBinder::update(), and RobotGui::TaskTrajectoryDressUpParameter::writeValues().
setValueIfChanged()
bool PropertyPlacement::setValueIfChanged (const Base::Placement & pos, double tol = 1e-7, double atol = 1e-12)
Sets property only if changed.
Parameters
pos input placement
tol position tolerance
atol angular tolerance
References setValue().
Referenced by Gui::TreeWidget::dropEvent().
Member Data Documentation
Null
const Placement App::PropertyPlacement::Null static
The documentation for this class was generated from the following files:
FreeCAD/src/App/PropertyGeo.h
FreeCAD/src/App/PropertyGeo.cpp