FreeCAD: TechDrawGui::Ui_dlgTemplateField Class Reference
TechDrawGui::Ui_dlgTemplateField Class Reference
#include <ui_DlgTemplateField.h>
Public Member Functions
void retranslateUi (QDialog *TechDrawGui__dlgTemplateField)
void setupUi (QDialog *TechDrawGui__dlgTemplateField)
Public Attributes
QDialogButtonBox * bbButtons
QFormLayout * formLayout
QLabel * label
QLabel * lblMsg
QLabel * lblName
QLineEdit * leInput
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void TechDrawGui::Ui_dlgTemplateField::retranslateUi (QDialog * TechDrawGui__dlgTemplateField)
References lblMsg, lblName, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void TechDrawGui::Ui_dlgTemplateField::setupUi (QDialog * TechDrawGui__dlgTemplateField)
References bbButtons, draftgeoutils.intersections::connect(), formLayout, lblMsg, lblName, leInput, retranslateUi(), and verticalLayout.
Member Data Documentation
bbButtons
QDialogButtonBox* TechDrawGui::Ui_dlgTemplateField::bbButtons
Referenced by setupUi().
formLayout
QFormLayout* TechDrawGui::Ui_dlgTemplateField::formLayout
Referenced by setupUi().
label
QLabel* TechDrawGui::Ui_dlgTemplateField::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
lblMsg
QLabel* TechDrawGui::Ui_dlgTemplateField::lblMsg
Referenced by retranslateUi(), and setupUi().
lblName
QLabel* TechDrawGui::Ui_dlgTemplateField::lblName
Referenced by retranslateUi(), and setupUi().
leInput
QLineEdit* TechDrawGui::Ui_dlgTemplateField::leInput
Referenced by setupUi().
verticalLayout
QVBoxLayout* TechDrawGui::Ui_dlgTemplateField::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/TechDraw/Gui/ui_DlgTemplateField.h