FreeCAD: Gui::Dialog::Ui_DlgSettingsSelection Class Reference
Gui::Dialog::Ui_DlgSettingsSelection Class Reference
#include <ui_DlgSettingsSelection.h>
Public Member Functions
void retranslateUi (QWidget *Gui__Dialog__DlgSettingsSelection)
void setupUi (QWidget *Gui__Dialog__DlgSettingsSelection)
Public Attributes
QCheckBox * checkBoxAutoExpand
QCheckBox * checkBoxAutoSwitch
QCheckBox * checkBoxPreselect
QCheckBox * checkBoxRecord
QCheckBox * checkBoxSelectionCheckBoxes
QGridLayout * gridLayout
QSpacerItem * verticalSpacer
Member Function Documentation
retranslateUi()
void Gui::Dialog::Ui_DlgSettingsSelection::retranslateUi (QWidget * Gui__Dialog__DlgSettingsSelection)
References checkBoxAutoExpand, checkBoxAutoSwitch, checkBoxPreselect, checkBoxRecord, checkBoxSelectionCheckBoxes, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::Dialog::Ui_DlgSettingsSelection::setupUi (QWidget * Gui__Dialog__DlgSettingsSelection)
References checkBoxAutoExpand, checkBoxAutoSwitch, checkBoxPreselect, checkBoxRecord, checkBoxSelectionCheckBoxes, gridLayout, retranslateUi(), and verticalSpacer.
Member Data Documentation
checkBoxAutoExpand
QCheckBox* Gui::Dialog::Ui_DlgSettingsSelection::checkBoxAutoExpand
Referenced by retranslateUi(), and setupUi().
checkBoxAutoSwitch
QCheckBox* Gui::Dialog::Ui_DlgSettingsSelection::checkBoxAutoSwitch
Referenced by retranslateUi(), and setupUi().
checkBoxPreselect
QCheckBox* Gui::Dialog::Ui_DlgSettingsSelection::checkBoxPreselect
Referenced by retranslateUi(), and setupUi().
checkBoxRecord
QCheckBox* Gui::Dialog::Ui_DlgSettingsSelection::checkBoxRecord
Referenced by retranslateUi(), and setupUi().
checkBoxSelectionCheckBoxes
QCheckBox* Gui::Dialog::Ui_DlgSettingsSelection::checkBoxSelectionCheckBoxes
Referenced by retranslateUi(), and setupUi().
gridLayout
QGridLayout* Gui::Dialog::Ui_DlgSettingsSelection::gridLayout
Referenced by setupUi().
verticalSpacer
QSpacerItem* Gui::Dialog::Ui_DlgSettingsSelection::verticalSpacer
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_DlgSettingsSelection.h