FreeCAD: TechDraw::ProjectionAlgos Class Reference
TechDraw::ProjectionAlgos Class Reference
Algo class for projecting shapes and creating SVG output of it.
#include <ProjectionAlgos.h>
Public Types
enum ExtractionType { Plain = 0 , WithHidden = 1 , WithSmooth = 2 }
typedef std::map< std::string, std::string > XmlAttributes
Public Member Functions
void execute (void)
std::string getDXF (ExtractionType type, double scale, double tolerance)
std::string getSVG (ExtractionType type, double tolerance=0.05, XmlAttributes V_style=XmlAttributes(), XmlAttributes V0_style=XmlAttributes(), XmlAttributes V1_style=XmlAttributes(), XmlAttributes H_style=XmlAttributes(), XmlAttributes H0_style=XmlAttributes(), XmlAttributes H1_style=XmlAttributes())
ProjectionAlgos (const TopoDS_Shape &Input, const Base::Vector3d &Dir)
Constructor.
virtual ~ProjectionAlgos ()
Public Attributes
const Base::Vector3d & Direction
TopoDS_Shape H
TopoDS_Shape H1
TopoDS_Shape HI
TopoDS_Shape HN
TopoDS_Shape HO
const TopoDS_Shape & Input
TopoDS_Shape V
TopoDS_Shape V1
TopoDS_Shape VI
TopoDS_Shape VN
TopoDS_Shape VO
Detailed Description
Algo class for projecting shapes and creating SVG output of it.
Member Typedef Documentation
XmlAttributes
typedef std::map<std::string,std::string> TechDraw::ProjectionAlgos::XmlAttributes
Member Enumeration Documentation
ExtractionType
enum TechDraw::ProjectionAlgos::ExtractionType
Enumerator
Plain
WithHidden
WithSmooth
Constructor & Destructor Documentation
ProjectionAlgos()
ProjectionAlgos::ProjectionAlgos (const TopoDS_Shape & Input, const Base::Vector3d & Dir)
Constructor.
References execute().
~ProjectionAlgos()
ProjectionAlgos::~ProjectionAlgos () virtual
Member Function Documentation
execute()
void ProjectionAlgos::execute (void)
References Direction, H, H1, HI, HN, HO, Input, V, V1, VI, VN, VO, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), PathScripts.PathDressupDogbone.ObjectDressup::boneStateList(), ArchSite.Compass::buildCoordinates(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::generateTags(), ArchPanel.PanelCut::getWires(), ArchSchedule.CommandArchSchedule::IsActive(), Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), FeaturePython.DistanceBolt::onChanged(), PathScripts.PathStock.StockFromBase::onChanged(), PathScripts.PathStock.StockCreateBox::onChanged(), PathScripts.PathStock.StockCreateCylinder::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), draftobjects.patharray.PathArray::onDocumentRestored(), draftobjects.pathtwistedarray.PathTwistedArray::onDocumentRestored(), and ProjectionAlgos().
getDXF()
string ProjectionAlgos::getDXF (ExtractionType type, double scale, double tolerance)
References TechDraw::DXFOutput::exportEdges(), H, H1, HO, draftutils.utils::tolerance(), V, V1, VO, WithHidden, and WithSmooth.
getSVG()
string ProjectionAlgos::getSVG (ExtractionType type, double tolerance = 0.05, XmlAttributes V_style = XmlAttributes(), XmlAttributes V0_style = XmlAttributes(), XmlAttributes V1_style = XmlAttributes(), XmlAttributes H_style = XmlAttributes(), XmlAttributes H0_style = XmlAttributes(), XmlAttributes H1_style = XmlAttributes())
References TechDraw::SVGOutput::exportEdges(), H, H1, HO, draftutils.utils::tolerance(), V, V1, VO, WithHidden, and WithSmooth.
Member Data Documentation
Direction
const Base::Vector3d& TechDraw::ProjectionAlgos::Direction
Referenced by execute().
H
TopoDS_Shape TechDraw::ProjectionAlgos::H
Referenced by TechDraw::FeatureProjection::execute(), execute(), getDXF(), and getSVG().
H1
TopoDS_Shape TechDraw::ProjectionAlgos::H1
Referenced by TechDraw::FeatureProjection::execute(), execute(), getDXF(), and getSVG().
HI
TopoDS_Shape TechDraw::ProjectionAlgos::HI
Referenced by TechDraw::FeatureProjection::execute(), and execute().
HN
TopoDS_Shape TechDraw::ProjectionAlgos::HN
Referenced by TechDraw::FeatureProjection::execute(), and execute().
HO
TopoDS_Shape TechDraw::ProjectionAlgos::HO
Referenced by TechDraw::FeatureProjection::execute(), execute(), getDXF(), and getSVG().
Input
const TopoDS_Shape& TechDraw::ProjectionAlgos::Input
Referenced by execute().
V
TopoDS_Shape TechDraw::ProjectionAlgos::V
Referenced by TechDraw::FeatureProjection::execute(), execute(), getDXF(), and getSVG().
V1
TopoDS_Shape TechDraw::ProjectionAlgos::V1
Referenced by TechDraw::FeatureProjection::execute(), execute(), getDXF(), and getSVG().
VI
TopoDS_Shape TechDraw::ProjectionAlgos::VI
Referenced by TechDraw::FeatureProjection::execute(), and execute().
VN
TopoDS_Shape TechDraw::ProjectionAlgos::VN
Referenced by TechDraw::FeatureProjection::execute(), and execute().
VO
TopoDS_Shape TechDraw::ProjectionAlgos::VO
Referenced by TechDraw::FeatureProjection::execute(), execute(), getDXF(), and getSVG().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/App/ProjectionAlgos.h
FreeCAD/src/Mod/TechDraw/App/ProjectionAlgos.cpp