FreeCAD: Part::GeomBSplineCurve Class Reference
Part::GeomBSplineCurve Class Reference
#include <Geometry.h>
Public Member Functions
bool approximate (double tol3d, int maxSegments, int maxDegree, int continuity)
GeomBSplineCurve::approximate.
virtual Geometry * copy (void) const
returns a copy of this object having a new randomly generated tag.
int countKnots () const
int countPoles () const
GeomBSplineCurve ()
GeomBSplineCurve (const Handle(Geom_BSplineCurve)&)
GeomBSplineCurve (const std::vector< Base::Vector3d > &poles, const std::vector< double > &weights, const std::vector< double > &knots, const std::vector< int > &multiplicities, int degree, bool periodic=false, bool checkrational=true)
void getCardinalSplineTangents (const std::vector< gp_Pnt > &, const std::vector< double > &, std::vector< gp_Vec > &) const
void getCardinalSplineTangents (const std::vector< gp_Pnt > &, double, std::vector< gp_Vec > &) const
int getDegree () const
std::vector< double > getKnots () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
std::vector< int > getMultiplicities () const
int getMultiplicity (int index) const
std::vector< Base::Vector3d > getPoles () const
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
std::vector< double > getWeights () const
const Handle (Geom_Geometry) &handle() const
void increaseDegree (int degree)
void increaseMultiplicity (int index, int multiplicity)
void interpolate (const std::vector< gp_Pnt > &, const std::vector< gp_Vec > &)
bool isPeriodic () const
bool isRational () const
bool join (const Handle(Geom_BSplineCurve)&)
void makeC1Continuous (double, double)
bool removeKnot (int index, int multiplicity, double tolerance=Precision::PConfusion())
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
void setHandle (const Handle(Geom_BSplineCurve)&)
void setKnot (int index, const double val, int mult=-1)
void setKnots (const std::vector< double > &knots)
void setKnots (const std::vector< double > &knots, const std::vector< int > &multiplicities)
void setPole (int index, const Base::Vector3d &, double weight=-1)
void setPoles (const std::vector< Base::Vector3d > &poles)
void setPoles (const std::vector< Base::Vector3d > &poles, const std::vector< double > &weights)
void setWeights (const std::vector< double > &weights)
std::list< Geometry * > toBiArcs (double tolerance) const
virtual ~GeomBSplineCurve ()
Public Member Functions inherited from Part::GeomBoundedCurve
GeomBoundedCurve ()
virtual Base::Vector3d getEndPoint () const
virtual Base::Vector3d getStartPoint () const
virtual ~GeomBoundedCurve ()
Public Member Functions inherited from Part::GeomCurve
bool closestParameter (const Base::Vector3d &point, double &u) const
bool closestParameterToBasisCurve (const Base::Vector3d &point, double &u) const
double curvatureAt (double u) const
Base::Vector3d firstDerivativeAtParameter (double u) const
GeomCurve ()
double getFirstParameter () const
double getLastParameter () const
bool intersect (GeomCurve *c, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion()) const
double length (double u, double v) const
bool normalAt (double u, Base::Vector3d &dir) const
Base::Vector3d pointAtParameter (double u) const
void reverse (void)
Base::Vector3d secondDerivativeAtParameter (double u) const
bool tangent (double u, Base::Vector3d &dir) const
bool tangent (double u, gp_Dir &) const
GeomBSplineCurve * toBSpline (double first, double last) const
toBSpline Converts the curve to a B-spline
virtual GeomBSplineCurve * toNurbs (double first, double last) const
TopoDS_Shape toShape () const
virtual ~GeomCurve ()
Public Member Functions inherited from Part::Geometry
Geometry * clone (void) const
returns a cloned object.
void deleteExtension (Base::Type type)
void deleteExtension (std::string name)
std::weak_ptr< GeometryExtension > getExtension (Base::Type type)
std::weak_ptr< const GeometryExtension > getExtension (Base::Type type) const
std::weak_ptr< GeometryExtension > getExtension (std::string name)
std::weak_ptr< const GeometryExtension > getExtension (std::string name) const
std::vector< std::weak_ptr< const GeometryExtension > > getExtensions () const
boost::uuids::uuid getTag () const
returns the tag of the geometry object
bool hasExtension (Base::Type type) const
bool hasExtension (std::string name) const
void mirror (const Base::Vector3d &point)
void mirror (const Base::Vector3d &point, const Base::Vector3d &dir)
void rotate (const Base::Placement &plm)
void scale (const Base::Vector3d &vec, double scale)
void setExtension (std::unique_ptr< GeometryExtension > &&geo)
void transform (const Base::Matrix4D &mat)
void translate (const Base::Vector3d &vec)
virtual ~Geometry ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Protected Member Functions inherited from Part::Geometry
void assignTag (const Part::Geometry *)
copies the tag from the geometry passed as a parameter to this object
void copyNonTag (const Part::Geometry *)
void createNewTag ()
create a new tag for the geometry object
Geometry ()
Static Protected Member Functions inherited from Part::GeomCurve
static bool intersect (const Handle(Geom_Curve) c, const Handle(Geom_Curve) c2, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion())
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Part::Geometry
std::vector< std::shared_ptr< GeometryExtension > > extensions
boost::uuids::uuid tag
Constructor & Destructor Documentation
GeomBSplineCurve() [1/3]
GeomBSplineCurve::GeomBSplineCurve ()
GeomBSplineCurve() [2/3]
GeomBSplineCurve::GeomBSplineCurve (const Handle(Geom_BSplineCurve)& b)
References setHandle().
GeomBSplineCurve() [3/3]
GeomBSplineCurve::GeomBSplineCurve (const std::vector< Base::Vector3d > & poles, const std::vector< double > & weights, const std::vector< double > & knots, const std::vector< int > & multiplicities, int degree, bool periodic = false, bool checkrational = true)
~GeomBSplineCurve()
GeomBSplineCurve::~GeomBSplineCurve () virtual
Member Function Documentation
approximate()
bool GeomBSplineCurve::approximate (double tol3d, int maxSegments, int maxDegree, int continuity)
GeomBSplineCurve::approximate.
Parameters
tol3d
maxSegments
maxDegree
continuity
Returns
true if the approximation succeeded, false otherwise
References Handle(), and setHandle().
Referenced by Part::BSplineCurvePy::approximate().
copy()
virtual Geometry* Part::GeomBSplineCurve::copy (void) const virtual
returns a copy of this object having a new randomly generated tag.
If you also want to copy the tag, you may use clone() instead. For creation of geometry with other handles, with or without the same tag, you may use the constructors and the sethandle functions. The tag of a geometry can be copied to another geometry using the assignTag function.
Implements Part::Geometry.
countKnots()
int Part::GeomBSplineCurve::countKnots () const
Referenced by Sketcher::SketchObject::deleteUnusedInternalGeometry(), Sketcher::SketchObject::exposeInternalGeometry(), and Sketcher::SketchObject::modifyBSplineKnotMultiplicity().
countPoles()
int Part::GeomBSplineCurve::countPoles () const
Referenced by Sketcher::SketchObject::deleteUnusedInternalGeometry(), Sketcher::SketchObject::exposeInternalGeometry(), and Sketcher::SketchObject::modifyBSplineKnotMultiplicity().
getCardinalSplineTangents() [1/2]
void GeomBSplineCurve::getCardinalSplineTangents (const std::vector< gp_Pnt > & p, const std::vector< double > & c, std::vector< gp_Vec > & t) const
Compute the tangents for a Cardinal spline using the the cubic Hermite spline. It uses the method for Cardinal splines.
getCardinalSplineTangents() [2/2]
void GeomBSplineCurve::getCardinalSplineTangents (const std::vector< gp_Pnt > & p, double c, std::vector< gp_Vec > & t) const
Compute the tangents for a Cardinal spline using the the cubic Hermite spline. It uses the method for Cardinal splines. It uses the same parameter for each tangent.
getDegree()
int GeomBSplineCurve::getDegree () const
Referenced by Sketcher::Sketch::addBSpline(), SketcherGui::ViewProviderSketch::draw(), Sketcher::SketchObject::modifyBSplineKnotMultiplicity(), and Save().
getKnots()
std::vector< double > GeomBSplineCurve::getKnots () const
Referenced by Sketcher::Sketch::addBSpline(), SketcherGui::ViewProviderSketch::draw(), Sketcher::SketchObject::exposeInternalGeometry(), Sketcher::SketchObject::modifyBSplineKnotMultiplicity(), and Save().
getMemSize()
unsigned int GeomBSplineCurve::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Part::Geometry.
getMultiplicities()
std::vector< int > GeomBSplineCurve::getMultiplicities () const
Referenced by Sketcher::Sketch::addBSpline(), SketcherGui::ViewProviderSketch::draw(), and Save().
getMultiplicity()
int GeomBSplineCurve::getMultiplicity (int index) const
Referenced by Sketcher::SketchObject::modifyBSplineKnotMultiplicity().
getPoles()
std::vector< Base::Vector3d > GeomBSplineCurve::getPoles () const
Referenced by Sketcher::Sketch::addBSpline(), Sketcher::SketchObject::addCopy(), Sketcher::SketchObject::addSymmetric(), SketcherGui::ViewProviderSketch::draw(), Sketcher::SketchObject::exposeInternalGeometry(), Sketcher::SketchObject::modifyBSplineKnotMultiplicity(), and Save().
getPyObject()
PyObject * GeomBSplineCurve::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
References Part::Geometry::clone().
getWeights()
std::vector< double > GeomBSplineCurve::getWeights () const
Referenced by Sketcher::Sketch::addBSpline(), SketcherGui::ViewProviderSketch::draw(), Sketcher::SketchObject::migrateSketch(), and Save().
Handle()
const Part::GeomBSplineCurve::Handle (Geom_Geometry) const & virtual
Implements Part::Geometry.
Referenced by approximate(), increaseDegree(), increaseMultiplicity(), interpolate(), removeKnot(), Restore(), and setHandle().
increaseDegree()
void GeomBSplineCurve::increaseDegree (int degree)
References Handle().
increaseMultiplicity()
void GeomBSplineCurve::increaseMultiplicity (int index, int multiplicity)
References Handle().
interpolate()
void GeomBSplineCurve::interpolate (const std::vector< gp_Pnt > & p, const std::vector< gp_Vec > & t)
Set the poles and tangents for the cubic Hermite spline
References Handle().
isPeriodic()
bool GeomBSplineCurve::isPeriodic () const
Referenced by Sketcher::Sketch::addBSpline(), SketcherGui::ViewProviderSketch::draw(), and Save().
isRational()
bool GeomBSplineCurve::isRational () const
join()
bool GeomBSplineCurve::join (const Handle(Geom_BSplineCurve)& spline)
Referenced by draftobjects.clone.Clone::execute(), and Part::BSplineCurvePy::join().
makeC1Continuous()
void GeomBSplineCurve::makeC1Continuous (double tol, double ang_tol)
Referenced by Part::BSplineCurvePy::makeC1Continuous().
removeKnot()
bool GeomBSplineCurve::removeKnot (int index, int multiplicity, double tolerance = Precision::PConfusion())
References Handle(), and draftutils.utils::tolerance().
Restore()
void GeomBSplineCurve::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Part::Geometry.
References Base::XMLReader::getAttributeAsFloat(), Base::XMLReader::getAttributeAsInteger(), Handle(), Base::XMLReader::readElement(), Base::XMLReader::readEndElement(), and Part::Geometry::Restore().
Save()
void GeomBSplineCurve::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from Part::Geometry.
References Base::Writer::decInd(), getDegree(), getKnots(), getMultiplicities(), getPoles(), getWeights(), Base::Writer::incInd(), Base::Writer::ind(), isPeriodic(), Part::Geometry::Save(), and Base::Writer::Stream().
setHandle()
void GeomBSplineCurve::setHandle (const Handle(Geom_BSplineCurve)& c)
References Handle().
Referenced by approximate(), Part::BSplineCurvePy::approximate(), Part::BSplineCurvePy::buildFromPoles(), Part::BSplineCurvePy::buildFromPolesMultsKnots(), GeomBSplineCurve(), and Part::BSplineCurvePy::interpolate().
setKnot()
void GeomBSplineCurve::setKnot (int index, const double val, int mult = -1)
Referenced by setKnots().
setKnots() [1/2]
void GeomBSplineCurve::setKnots (const std::vector< double > & knots)
References setKnot().
setKnots() [2/2]
void GeomBSplineCurve::setKnots (const std::vector< double > & knots, const std::vector< int > & multiplicities)
References setKnot().
setPole()
void Part::GeomBSplineCurve::setPole (int index, const Base::Vector3d & , double weight = -1)
Referenced by setPoles().
setPoles() [1/2]
void GeomBSplineCurve::setPoles (const std::vector< Base::Vector3d > & poles)
References setPole().
setPoles() [2/2]
void GeomBSplineCurve::setPoles (const std::vector< Base::Vector3d > & poles, const std::vector< double > & weights)
References setPole().
Referenced by Sketcher::SketchObject::addCopy(), and Sketcher::SketchObject::addSymmetric().
setWeights()
void GeomBSplineCurve::setWeights (const std::vector< double > & weights)
toBiArcs()
std::list< Geometry * > GeomBSplineCurve::toBiArcs (double tolerance) const
References draftutils.utils::tolerance().
Referenced by Part::BSplineCurvePy::toBiArcs().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/App/Geometry.h
Sources/FreeCAD/src/Mod/Part/App/BSplineCurveBiArcs.cpp
Sources/FreeCAD/src/Mod/Part/App/Geometry.cpp