FreeCAD: FemGui::TaskFemConstraintForce Class Reference
FemGui::TaskFemConstraintForce Class Reference
#include <TaskFemConstraintForce.h>
Public Member Functions
const std::string getDirectionName (void) const
const std::string getDirectionObject (void) const
double getForce (void) const
const std::string getReferences () const
bool getReverse (void) const
TaskFemConstraintForce (ViewProviderFemConstraintForce *ConstraintView, QWidget *parent=nullptr)
virtual ~TaskFemConstraintForce ()
Public Member Functions inherited from FemGui::TaskFemConstraintOnBoundary
TaskFemConstraintOnBoundary (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="")
~TaskFemConstraintOnBoundary ()
Public Member Functions inherited from FemGui::TaskFemConstraint
const std::string getReferences (const std::vector< std::string > &items) const
virtual const std::string getReferences (void) const
const std::string getScale () const
TaskFemConstraint (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="")
virtual ~TaskFemConstraint ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Protected Member Functions
virtual void changeEvent (QEvent *e)
void clearButtons (const SelectionChangeModes notThis) override
bool event (QEvent *e)
Protected Member Functions inherited from FemGui::TaskFemConstraintOnBoundary
virtual void clearButtons (const SelectionChangeModes notThis)=0
virtual void onSelectionChanged (const Gui::SelectionChanges &) override
Protected Member Functions inherited from FemGui::TaskFemConstraint
virtual void changeEvent (QEvent *e)
void createDeleteAction (QListWidget *parentList)
bool KeyEvent (QEvent *e)
virtual void keyPressEvent (QKeyEvent *ke)
const QString makeRefText (const App::DocumentObject *obj, const std::string &subName) const
const QString makeRefText (const std::string &objName, const std::string &subName) const
virtual void onSelectionChanged (const Gui::SelectionChanges &)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Types inherited from FemGui::TaskFemConstraintOnBoundary
enum class SelectionChangeModes { none , refAdd , refRemove }
Protected Types inherited from FemGui::TaskFemConstraint
enum { seldir , selref , selloc , selnone }
Protected Slots inherited from FemGui::TaskFemConstraintOnBoundary
virtual void addToSelection ()=0
void onButtonToggled (QAbstractButton *button, bool checked)
virtual void removeFromSelection ()=0
Protected Slots inherited from FemGui::TaskFemConstraint
void onButtonReference (const bool pressed=true)
void onButtonWizCancel ()
void onButtonWizOk ()
void onReferenceDeleted (const int row)
void setSelection (QListWidgetItem *item)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from FemGui::TaskFemConstraintOnBoundary
Gui::ButtonGroup * buttonGroup
enum SelectionChangeModes selChangeMode
Protected Attributes inherited from FemGui::TaskFemConstraint
Gui::WeakPtrT< ViewProviderFemConstraint > ConstraintView
QAction * deleteAction
QWidget * proxy
enum FemGui::TaskFemConstraint:: { ... } selectionMode
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskFemConstraintForce()
TaskFemConstraintForce::TaskFemConstraintForce (ViewProviderFemConstraintForce * ConstraintView, QWidget * parent = nullptr)
References Ui_TaskFemConstraintForce::btnAdd, Ui_TaskFemConstraintForce::btnRemove, Ui_TaskFemConstraintForce::buttonDirection, FemGui::TaskFemConstraintOnBoundary::buttonGroup, Ui_TaskFemConstraintForce::checkReverse, draftgeoutils.intersections::connect(), FemGui::TaskFemConstraint::ConstraintView, FemGui::TaskFemConstraint::createDeleteAction(), FemGui::TaskFemConstraint::deleteAction, Fem::ConstraintForce::Direction, Fem::ConstraintForce::Force, App::PropertyLinkSub::getSubValues(), App::PropertyLinkSubList::getSubValues(), App::PropertyLinkSub::getValue(), App::PropertyFloat::getValue(), App::PropertyBool::getValue(), App::PropertyLinkSubList::getValues(), QSint::ActionGroup::groupLayout(), Ui_TaskFemConstraintForce::lineDirection, Ui_TaskFemConstraintForce::listReferences, FemGui::TaskFemConstraint::makeRefText(), FemGui::TaskFemConstraint::proxy, FemGui::TaskFemConstraintOnBoundary::refAdd, Fem::Constraint::References, FemGui::TaskFemConstraintOnBoundary::refRemove, Fem::ConstraintForce::Reversed, Gui::QuantitySpinBox::setMaximum(), Gui::QuantitySpinBox::setMinimum(), FemGui::TaskFemConstraint::setSelection(), Ui_TaskFemConstraintForce::setupUi(), Gui::QuantitySpinBox::setValue(), and Ui_TaskFemConstraintForce::spinForce.
~TaskFemConstraintForce()
TaskFemConstraintForce::~TaskFemConstraintForce () virtual
Member Function Documentation
changeEvent()
void TaskFemConstraintForce::changeEvent (QEvent * e) protected virtual
Reimplemented from FemGui::TaskFemConstraint.
References FemGui::TaskFemConstraint::proxy, Ui_TaskFemConstraintForce::retranslateUi(), and Ui_TaskFemConstraintForce::spinForce.
clearButtons()
void TaskFemConstraintForce::clearButtons (const SelectionChangeModes notThis) override protected virtual
Implements FemGui::TaskFemConstraintOnBoundary.
References Ui_TaskFemConstraintForce::btnAdd, Ui_TaskFemConstraintForce::btnRemove, FemGui::TaskFemConstraintOnBoundary::refAdd, and FemGui::TaskFemConstraintOnBoundary::refRemove.
event()
bool TaskFemConstraintForce::event (QEvent * e) protected
References FemGui::TaskFemConstraint::KeyEvent().
getDirectionName()
const std::string TaskFemConstraintForce::getDirectionName (void) const
References Ui_TaskFemConstraintForce::lineDirection.
Referenced by FemGui::TaskDlgFemConstraintForce::accept().
getDirectionObject()
const std::string TaskFemConstraintForce::getDirectionObject (void) const
References Ui_TaskFemConstraintForce::lineDirection.
Referenced by FemGui::TaskDlgFemConstraintForce::accept().
getForce()
double TaskFemConstraintForce::getForce (void) const
References Base::Quantity::getValue(), Ui_TaskFemConstraintForce::spinForce, and Gui::QuantitySpinBox::value.
Referenced by FemGui::TaskDlgFemConstraintForce::accept().
getReferences()
const std::string TaskFemConstraintForce::getReferences (void) const virtual
Reimplemented from FemGui::TaskFemConstraint.
References FemGui::TaskFemConstraint::getReferences(), and Ui_TaskFemConstraintForce::listReferences.
getReverse()
bool TaskFemConstraintForce::getReverse (void) const
References Ui_TaskFemConstraintForce::checkReverse.
Referenced by FemGui::TaskDlgFemConstraintForce::accept().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintForce.h
FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintForce.cpp