FreeCAD: Part::CurveConstraintPy Class Reference
Part::CurveConstraintPy Class Reference
The python export class for GeomPlate_CurveConstraint.
#include <CurveConstraintPy.h>
Public Types
typedef GeomPlate_CurveConstraint * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
CurveConstraintPy (GeomPlate_CurveConstraint *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of CurveConstraintPy.
static PyMethodDef Methods []
Methods structure of CurveConstraintPy.
static PyTypeObject Type
Type structure of CurveConstraintPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~CurveConstraintPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * setOrder (PyObject *args)
implementer for the setOrder() method
PyObject * order (PyObject *args)
implementer for the order() method
PyObject * G0Criterion (PyObject *args)
implementer for the G0Criterion() method
PyObject * G1Criterion (PyObject *args)
implementer for the G1Criterion() method
PyObject * G2Criterion (PyObject *args)
implementer for the G2Criterion() method
PyObject * setG0Criterion (PyObject *args)
implementer for the setG0Criterion() method
PyObject * setG1Criterion (PyObject *args)
implementer for the setG1Criterion() method
PyObject * setG2Criterion (PyObject *args)
implementer for the setG2Criterion() method
PyObject * curve3d (PyObject *args)
implementer for the curve3d() method
PyObject * setCurve2dOnSurf (PyObject *args)
implementer for the setCurve2dOnSurf() method
PyObject * curve2dOnSurf (PyObject *args)
implementer for the curve2dOnSurf() method
PyObject * setProjectedCurve (PyObject *args)
implementer for the setProjectedCurve() method
PyObject * projectedCurve (PyObject *args)
implementer for the projectedCurve() method
static PyObject * staticCallback_setOrder (PyObject *self, PyObject *args)
callback for the setOrder() method
static PyObject * staticCallback_order (PyObject *self, PyObject *args)
callback for the order() method
static PyObject * staticCallback_G0Criterion (PyObject *self, PyObject *args)
callback for the G0Criterion() method
static PyObject * staticCallback_G1Criterion (PyObject *self, PyObject *args)
callback for the G1Criterion() method
static PyObject * staticCallback_G2Criterion (PyObject *self, PyObject *args)
callback for the G2Criterion() method
static PyObject * staticCallback_setG0Criterion (PyObject *self, PyObject *args)
callback for the setG0Criterion() method
static PyObject * staticCallback_setG1Criterion (PyObject *self, PyObject *args)
callback for the setG1Criterion() method
static PyObject * staticCallback_setG2Criterion (PyObject *self, PyObject *args)
callback for the setG2Criterion() method
static PyObject * staticCallback_curve3d (PyObject *self, PyObject *args)
callback for the curve3d() method
static PyObject * staticCallback_setCurve2dOnSurf (PyObject *self, PyObject *args)
callback for the setCurve2dOnSurf() method
static PyObject * staticCallback_curve2dOnSurf (PyObject *self, PyObject *args)
callback for the curve2dOnSurf() method
static PyObject * staticCallback_setProjectedCurve (PyObject *self, PyObject *args)
callback for the setProjectedCurve() method
static PyObject * staticCallback_projectedCurve (PyObject *self, PyObject *args)
callback for the projectedCurve() method
callbacks and implementers for the python object attributes
Py::Long getNbPoints (void) const
getter for the NbPoints attribute
void setNbPoints (Py::Long arg)
setter for the NbPoints attribute
Py::Float getFirstParameter (void) const
getter for the FirstParameter attribute
Py::Float getLastParameter (void) const
getter for the LastParameter attribute
Py::Float getLength (void) const
getter for the Length attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomPlate_CurveConstraint * getGeomPlate_CurveConstraintPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getNbPoints (PyObject *self, void *closure)
getter callback for the NbPoints attribute
static int staticCallback_setNbPoints (PyObject *self, PyObject *value, void *closure)
setter callback for the NbPoints attribute
static PyObject * staticCallback_getFirstParameter (PyObject *self, void *closure)
getter callback for the FirstParameter attribute
static int staticCallback_setFirstParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the FirstParameter attribute
static PyObject * staticCallback_getLastParameter (PyObject *self, void *closure)
getter callback for the LastParameter attribute
static int staticCallback_setLastParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the LastParameter attribute
static PyObject * staticCallback_getLength (PyObject *self, void *closure)
getter callback for the Length attribute
static int staticCallback_setLength (PyObject *self, PyObject *value, void *closure)
setter callback for the Length attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeomPlate_CurveConstraint.
Member Typedef Documentation
PointerType
typedef GeomPlate_CurveConstraint* Part::CurveConstraintPy::PointerType
Constructor & Destructor Documentation
~CurveConstraintPy()
CurveConstraintPy::~CurveConstraintPy () protected
CurveConstraintPy()
CurveConstraintPy::CurveConstraintPy (GeomPlate_CurveConstraint * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
curve2dOnSurf()
PyObject * CurveConstraintPy::curve2dOnSurf (PyObject * args)
implementer for the curve2dOnSurf() method
References getGeomPlate_CurveConstraintPtr(), Base::BaseClass::getPyObject(), and Part::makeFromCurve2d().
Referenced by staticCallback_curve2dOnSurf().
curve3d()
PyObject * CurveConstraintPy::curve3d (PyObject * args)
implementer for the curve3d() method
References getGeomPlate_CurveConstraintPtr(), Base::BaseClass::getPyObject(), and Part::makeFromCurveAdaptor().
Referenced by staticCallback_curve3d().
G0Criterion()
PyObject * CurveConstraintPy::G0Criterion (PyObject * args)
implementer for the G0Criterion() method
References getGeomPlate_CurveConstraintPtr().
Referenced by staticCallback_G0Criterion().
G1Criterion()
PyObject * CurveConstraintPy::G1Criterion (PyObject * args)
implementer for the G1Criterion() method
References getGeomPlate_CurveConstraintPtr().
Referenced by staticCallback_G1Criterion().
G2Criterion()
PyObject * CurveConstraintPy::G2Criterion (PyObject * args)
implementer for the G2Criterion() method
References getGeomPlate_CurveConstraintPtr().
Referenced by staticCallback_G2Criterion().
getCustomAttributes()
PyObject * CurveConstraintPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getFirstParameter()
Py::Float CurveConstraintPy::getFirstParameter (void) const
getter for the FirstParameter attribute
References getGeomPlate_CurveConstraintPtr().
Referenced by staticCallback_getFirstParameter().
getGeomPlate_CurveConstraintPtr()
GeomPlate_CurveConstraint * CurveConstraintPy::getGeomPlate_CurveConstraintPtr (void) const
getter for the object handled by this class
Referenced by curve2dOnSurf(), curve3d(), G0Criterion(), G1Criterion(), G2Criterion(), getFirstParameter(), getLastParameter(), getLength(), getNbPoints(), order(), projectedCurve(), setCurve2dOnSurf(), setNbPoints(), setOrder(), and setProjectedCurve().
getLastParameter()
Py::Float CurveConstraintPy::getLastParameter (void) const
getter for the LastParameter attribute
References getGeomPlate_CurveConstraintPtr().
Referenced by staticCallback_getLastParameter().
getLength()
Py::Float CurveConstraintPy::getLength (void) const
getter for the Length attribute
References getGeomPlate_CurveConstraintPtr().
Referenced by staticCallback_getLength().
getNbPoints()
Py::Long CurveConstraintPy::getNbPoints (void) const
getter for the NbPoints attribute
References getGeomPlate_CurveConstraintPtr().
Referenced by staticCallback_getNbPoints().
GetType()
virtual PyTypeObject* Part::CurveConstraintPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
order()
PyObject * CurveConstraintPy::order (PyObject * args)
implementer for the order() method
References getGeomPlate_CurveConstraintPtr().
Referenced by setOrder(), and staticCallback_order().
projectedCurve()
PyObject * CurveConstraintPy::projectedCurve (PyObject * args)
implementer for the projectedCurve() method
References getGeomPlate_CurveConstraintPtr(), Base::BaseClass::getPyObject(), and Part::makeFromCurveAdaptor2d().
Referenced by staticCallback_projectedCurve().
PyInit()
int CurveConstraintPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
References Base::Persistence::getClassTypeId(), Part::GeomCurve::getFirstParameter(), Part::GeomCurve::getLastParameter(), Base::Persistence::getTypeId(), Base::Type::isDerivedFrom(), Base::PyObjectBase::setTwinPointer(), and Part::GeometryCurvePy::Type.
PyMake()
PyObject * CurveConstraintPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References CurveConstraintPy().
representation()
std::string CurveConstraintPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCurve2dOnSurf()
PyObject * CurveConstraintPy::setCurve2dOnSurf (PyObject * args)
implementer for the setCurve2dOnSurf() method
References getGeomPlate_CurveConstraintPtr(), and Part::Curve2dPy::Type.
Referenced by staticCallback_setCurve2dOnSurf().
setCustomAttributes()
int CurveConstraintPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setG0Criterion()
PyObject * CurveConstraintPy::setG0Criterion (PyObject * args)
implementer for the setG0Criterion() method
Referenced by staticCallback_setG0Criterion().
setG1Criterion()
PyObject * CurveConstraintPy::setG1Criterion (PyObject * args)
implementer for the setG1Criterion() method
Referenced by staticCallback_setG1Criterion().
setG2Criterion()
PyObject * CurveConstraintPy::setG2Criterion (PyObject * args)
implementer for the setG2Criterion() method
Referenced by staticCallback_setG2Criterion().
setNbPoints()
void CurveConstraintPy::setNbPoints (Py::Long arg)
setter for the NbPoints attribute
References getGeomPlate_CurveConstraintPtr().
Referenced by staticCallback_setNbPoints().
setOrder()
PyObject * CurveConstraintPy::setOrder (PyObject * args)
implementer for the setOrder() method
References getGeomPlate_CurveConstraintPtr(), and order().
Referenced by staticCallback_setOrder().
setProjectedCurve()
PyObject * CurveConstraintPy::setProjectedCurve (PyObject * args)
implementer for the setProjectedCurve() method
References getGeomPlate_CurveConstraintPtr(), and Part::Curve2dPy::Type.
Referenced by staticCallback_setProjectedCurve().
staticCallback_curve2dOnSurf()
PyObject * CurveConstraintPy::staticCallback_curve2dOnSurf (PyObject * self, PyObject * args) static
callback for the curve2dOnSurf() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, curve2dOnSurf(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_curve3d()
PyObject * CurveConstraintPy::staticCallback_curve3d (PyObject * self, PyObject * args) static
callback for the curve3d() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, curve3d(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_G0Criterion()
PyObject * CurveConstraintPy::staticCallback_G0Criterion (PyObject * self, PyObject * args) static
callback for the G0Criterion() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, G0Criterion(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_G1Criterion()
PyObject * CurveConstraintPy::staticCallback_G1Criterion (PyObject * self, PyObject * args) static
callback for the G1Criterion() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, G1Criterion(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_G2Criterion()
PyObject * CurveConstraintPy::staticCallback_G2Criterion (PyObject * self, PyObject * args) static
callback for the G2Criterion() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, G2Criterion(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getFirstParameter()
PyObject * CurveConstraintPy::staticCallback_getFirstParameter (PyObject * self, void * closure) static
getter callback for the FirstParameter attribute
References Base::BaseExceptionFreeCADError, getFirstParameter(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getLastParameter()
PyObject * CurveConstraintPy::staticCallback_getLastParameter (PyObject * self, void * closure) static
getter callback for the LastParameter attribute
References Base::BaseExceptionFreeCADError, getLastParameter(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getLength()
PyObject * CurveConstraintPy::staticCallback_getLength (PyObject * self, void * closure) static
getter callback for the Length attribute
References Base::BaseExceptionFreeCADError, getLength(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNbPoints()
PyObject * CurveConstraintPy::staticCallback_getNbPoints (PyObject * self, void * closure) static
getter callback for the NbPoints attribute
References Base::BaseExceptionFreeCADError, getNbPoints(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_order()
PyObject * CurveConstraintPy::staticCallback_order (PyObject * self, PyObject * args) static
callback for the order() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), order(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_projectedCurve()
PyObject * CurveConstraintPy::staticCallback_projectedCurve (PyObject * self, PyObject * args) static
callback for the projectedCurve() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), projectedCurve(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_setCurve2dOnSurf()
PyObject * CurveConstraintPy::staticCallback_setCurve2dOnSurf (PyObject * self, PyObject * args) static
callback for the setCurve2dOnSurf() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setCurve2dOnSurf(), and Base::PyObjectBase::startNotify().
staticCallback_setFirstParameter()
int CurveConstraintPy::staticCallback_setFirstParameter (PyObject * self, PyObject * value, void * closure) static
setter callback for the FirstParameter attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setG0Criterion()
PyObject * CurveConstraintPy::staticCallback_setG0Criterion (PyObject * self, PyObject * args) static
callback for the setG0Criterion() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setG0Criterion(), and Base::PyObjectBase::startNotify().
staticCallback_setG1Criterion()
PyObject * CurveConstraintPy::staticCallback_setG1Criterion (PyObject * self, PyObject * args) static
callback for the setG1Criterion() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setG1Criterion(), and Base::PyObjectBase::startNotify().
staticCallback_setG2Criterion()
PyObject * CurveConstraintPy::staticCallback_setG2Criterion (PyObject * self, PyObject * args) static
callback for the setG2Criterion() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setG2Criterion(), and Base::PyObjectBase::startNotify().
staticCallback_setLastParameter()
int CurveConstraintPy::staticCallback_setLastParameter (PyObject * self, PyObject * value, void * closure) static
setter callback for the LastParameter attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setLength()
int CurveConstraintPy::staticCallback_setLength (PyObject * self, PyObject * value, void * closure) static
setter callback for the Length attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setNbPoints()
int CurveConstraintPy::staticCallback_setNbPoints (PyObject * self, PyObject * value, void * closure) static
setter callback for the NbPoints attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setNbPoints().
staticCallback_setOrder()
PyObject * CurveConstraintPy::staticCallback_setOrder (PyObject * self, PyObject * args) static
callback for the setOrder() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setOrder(), and Base::PyObjectBase::startNotify().
staticCallback_setProjectedCurve()
PyObject * CurveConstraintPy::staticCallback_setProjectedCurve (PyObject * self, PyObject * args) static
callback for the setProjectedCurve() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setProjectedCurve(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef CurveConstraintPy::GetterSetter static
Initial value:
= {
    {"NbPoints",
        (getter) staticCallback_getNbPoints,
        (setter) staticCallback_setNbPoints,
        "The number of points on the curve used as a\nconstraint. The default setting is 10. This parameter\naffects computation time, which increases by the cube of\nthe number of points.",
        NULL
    },
    {"FirstParameter",
        (getter) staticCallback_getFirstParameter,
        (setter) staticCallback_setFirstParameter,
        "",
        NULL
    },
    {"LastParameter",
        (getter) staticCallback_getLastParameter,
        (setter) staticCallback_setLastParameter,
        "",
        NULL
    },
    {"Length",
        (getter) staticCallback_getLength,
        (setter) staticCallback_setLength,
        "",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of CurveConstraintPy.
Methods
PyMethodDef CurveConstraintPy::Methods static
Methods structure of CurveConstraintPy.
Type
PyTypeObject CurveConstraintPy::Type static
Type structure of CurveConstraintPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), Part::BuildPlateSurfacePy::add(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeomPlate/CurveConstraintPy.h
Sources/FreeCAD/src/Mod/Part/App/GeomPlate/CurveConstraintPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeomPlate/CurveConstraintPy.cpp