FreeCAD: importSH3D Namespace Reference
importSH3D Namespace Reference
Workbenches » Python workbenches » Arch
SH3D (SweetHome3D) file format importer.
Classes
class SH3DHandler
Functions
def decode (name)
def insert (filename, docname)
def open (filename)
def read (filename)
Variables
bool DEBUG = True
pyopen = open
Detailed Description
SH3D (SweetHome3D) file format importer.
This module provides tools to import SH3D files created from Sweet Home 3D.
Function Documentation
decode()
def importSH3D.decode (name)
Referenced by open().
insert()
def importSH3D.insert (filename, docname)
References read().
open()
def importSH3D.open (filename)
References decode(), and read().
read()
def importSH3D.read (filename)
Referenced by insert(), open(), and importSH3D.SH3DHandler.startElement().
Variable Documentation
DEBUG
bool importSH3D.DEBUG = True
pyopen
importSH3D.pyopen = open
Referenced by importSH3D.SH3DHandler.startElement().