FreeCAD: TechDraw::CenterLinePy Class Reference
TechDraw::CenterLinePy Class Reference
The python export class for CenterLine.
#include <CenterLinePy.h>
Public Types
typedef CenterLine * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
CenterLinePy (CenterLine *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of CenterLinePy.
static PyMethodDef Methods []
Methods structure of CenterLinePy.
static PyTypeObject Type
Type structure of CenterLinePy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~CenterLinePy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * clone (PyObject *args)
implementer for the clone() method
PyObject * copy (PyObject *args)
implementer for the copy() method
static PyObject * staticCallback_clone (PyObject *self, PyObject *args)
callback for the clone() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
callbacks and implementers for the python object attributes
Py::String getTag (void) const
getter for the Tag attribute
Py::Long getType (void) const
getter for the Type attribute
Py::Long getMode (void) const
getter for the Mode attribute
void setMode (Py::Long arg)
setter for the Mode attribute
Py::Object getFormat (void) const
getter for the Format attribute
void setFormat (Py::Object arg)
setter for the Format attribute
Py::Float getHorizShift (void) const
getter for the HorizShift attribute
void setHorizShift (Py::Float arg)
setter for the HorizShift attribute
Py::Float getVertShift (void) const
getter for the VertShift attribute
void setVertShift (Py::Float arg)
setter for the VertShift attribute
Py::Float getRotation (void) const
getter for the Rotation attribute
void setRotation (Py::Float arg)
setter for the Rotation attribute
Py::Float getExtension (void) const
getter for the Extension attribute
void setExtension (Py::Float arg)
setter for the Extension attribute
Py::Boolean getFlip (void) const
getter for the Flip attribute
void setFlip (Py::Boolean arg)
setter for the Flip attribute
Py::Object getEdges (void) const
getter for the Edges attribute
void setEdges (Py::Object arg)
setter for the Edges attribute
Py::Object getFaces (void) const
getter for the Faces attribute
void setFaces (Py::Object arg)
setter for the Faces attribute
Py::Object getPoints (void) const
getter for the Points attribute
void setPoints (Py::Object arg)
setter for the Points attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
CenterLine * getCenterLinePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
static PyObject * staticCallback_getType (PyObject *self, void *closure)
getter callback for the Type attribute
static int staticCallback_setType (PyObject *self, PyObject *value, void *closure)
setter callback for the Type attribute
static PyObject * staticCallback_getMode (PyObject *self, void *closure)
getter callback for the Mode attribute
static int staticCallback_setMode (PyObject *self, PyObject *value, void *closure)
setter callback for the Mode attribute
static PyObject * staticCallback_getFormat (PyObject *self, void *closure)
getter callback for the Format attribute
static int staticCallback_setFormat (PyObject *self, PyObject *value, void *closure)
setter callback for the Format attribute
static PyObject * staticCallback_getHorizShift (PyObject *self, void *closure)
getter callback for the HorizShift attribute
static int staticCallback_setHorizShift (PyObject *self, PyObject *value, void *closure)
setter callback for the HorizShift attribute
static PyObject * staticCallback_getVertShift (PyObject *self, void *closure)
getter callback for the VertShift attribute
static int staticCallback_setVertShift (PyObject *self, PyObject *value, void *closure)
setter callback for the VertShift attribute
static PyObject * staticCallback_getRotation (PyObject *self, void *closure)
getter callback for the Rotation attribute
static int staticCallback_setRotation (PyObject *self, PyObject *value, void *closure)
setter callback for the Rotation attribute
static PyObject * staticCallback_getExtension (PyObject *self, void *closure)
getter callback for the Extension attribute
static int staticCallback_setExtension (PyObject *self, PyObject *value, void *closure)
setter callback for the Extension attribute
static PyObject * staticCallback_getFlip (PyObject *self, void *closure)
getter callback for the Flip attribute
static int staticCallback_setFlip (PyObject *self, PyObject *value, void *closure)
setter callback for the Flip attribute
static PyObject * staticCallback_getEdges (PyObject *self, void *closure)
getter callback for the Edges attribute
static int staticCallback_setEdges (PyObject *self, PyObject *value, void *closure)
setter callback for the Edges attribute
static PyObject * staticCallback_getFaces (PyObject *self, void *closure)
getter callback for the Faces attribute
static int staticCallback_setFaces (PyObject *self, PyObject *value, void *closure)
setter callback for the Faces attribute
static PyObject * staticCallback_getPoints (PyObject *self, void *closure)
getter callback for the Points attribute
static int staticCallback_setPoints (PyObject *self, PyObject *value, void *closure)
setter callback for the Points attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for CenterLine.
Member Typedef Documentation
PointerType
typedef CenterLine* TechDraw::CenterLinePy::PointerType
Constructor & Destructor Documentation
~CenterLinePy()
CenterLinePy::~CenterLinePy () protected
CenterLinePy()
CenterLinePy::CenterLinePy (CenterLine * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
clone()
PyObject * CenterLinePy::clone (PyObject * args)
implementer for the clone() method
References TechDraw::CenterLine::clone(), getCenterLinePtr(), and GetType().
Referenced by ArchPanel.CommandPanelSheet::Activated(), and staticCallback_clone().
copy()
PyObject * CenterLinePy::copy (PyObject * args)
implementer for the copy() method
References TechDraw::CenterLine::copy(), getCenterLinePtr(), and GetType().
Referenced by staticCallback_copy().
getCenterLinePtr()
CenterLine * CenterLinePy::getCenterLinePtr (void) const
getter for the object handled by this class
Referenced by clone(), copy(), getEdges(), getExtension(), getFaces(), getFlip(), getFormat(), getHorizShift(), getMode(), getPoints(), getRotation(), getTag(), getType(), getVertShift(), setEdges(), setExtension(), setFaces(), setFlip(), setFormat(), setHorizShift(), setMode(), setPoints(), TechDraw::PropertyCenterLineList::setPyObject(), setRotation(), and setVertShift().
getCustomAttributes()
PyObject * CenterLinePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getEdges()
Py::Object CenterLinePy::getEdges (void) const
getter for the Edges attribute
References getCenterLinePtr(), and TechDraw::CenterLine::m_edges.
Referenced by staticCallback_getEdges().
getExtension()
Py::Float CenterLinePy::getExtension (void) const
getter for the Extension attribute
References getCenterLinePtr(), and TechDraw::CenterLine::getExtend().
Referenced by staticCallback_getExtension().
getFaces()
Py::Object CenterLinePy::getFaces (void) const
getter for the Faces attribute
References getCenterLinePtr(), and TechDraw::CenterLine::m_faces.
Referenced by staticCallback_getFaces().
getFlip()
Py::Boolean CenterLinePy::getFlip (void) const
getter for the Flip attribute
References getCenterLinePtr(), and TechDraw::CenterLine::getFlip().
Referenced by staticCallback_getFlip().
getFormat()
Py::Object CenterLinePy::getFormat (void) const
getter for the Format attribute
References TechDraw::DrawUtil::colorToPyTuple(), getCenterLinePtr(), TechDraw::LineFormat::m_color, TechDraw::CenterLine::m_format, TechDraw::LineFormat::m_style, TechDraw::LineFormat::m_visible, and TechDraw::LineFormat::m_weight.
Referenced by staticCallback_getFormat().
getHorizShift()
Py::Float CenterLinePy::getHorizShift (void) const
getter for the HorizShift attribute
References getCenterLinePtr(), and TechDraw::CenterLine::getHShift().
Referenced by staticCallback_getHorizShift().
getMode()
Py::Long CenterLinePy::getMode (void) const
getter for the Mode attribute
References getCenterLinePtr(), and TechDraw::CenterLine::m_mode.
Referenced by staticCallback_getMode().
getPoints()
Py::Object CenterLinePy::getPoints (void) const
getter for the Points attribute
References getCenterLinePtr(), and TechDraw::CenterLine::m_verts.
Referenced by staticCallback_getPoints().
getRotation()
Py::Float CenterLinePy::getRotation (void) const
getter for the Rotation attribute
References getCenterLinePtr(), and TechDraw::CenterLine::getRotate().
Referenced by staticCallback_getRotation().
getTag()
Py::String CenterLinePy::getTag (void) const
getter for the Tag attribute
References getCenterLinePtr().
Referenced by staticCallback_getTag().
GetType()
virtual PyTypeObject* TechDraw::CenterLinePy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
Referenced by clone(), and copy().
getType()
Py::Long CenterLinePy::getType (void) const
getter for the Type attribute
References getCenterLinePtr(), and TechDraw::CenterLine::m_type.
Referenced by staticCallback_getType().
getVertShift()
Py::Float CenterLinePy::getVertShift (void) const
getter for the VertShift attribute
References getCenterLinePtr(), and TechDraw::CenterLine::getVShift().
Referenced by staticCallback_getVertShift().
PyInit()
int CenterLinePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
PyMake()
PyObject * CenterLinePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string CenterLinePy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int CenterLinePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setEdges()
void CenterLinePy::setEdges (Py::Object arg)
setter for the Edges attribute
References Base::Console(), Base::ConsoleSingleton::Error(), getCenterLinePtr(), and TechDraw::CenterLine::m_edges.
Referenced by staticCallback_setEdges().
setExtension()
void CenterLinePy::setExtension (Py::Float arg)
setter for the Extension attribute
References getCenterLinePtr(), and TechDraw::CenterLine::setExtend().
Referenced by staticCallback_setExtension().
setFaces()
void CenterLinePy::setFaces (Py::Object arg)
setter for the Faces attribute
References Base::Console(), Base::ConsoleSingleton::Error(), getCenterLinePtr(), and TechDraw::CenterLine::m_faces.
Referenced by staticCallback_setFaces().
setFlip()
void CenterLinePy::setFlip (Py::Boolean arg)
setter for the Flip attribute
References getCenterLinePtr(), and TechDraw::CenterLine::setFlip().
Referenced by staticCallback_setFlip().
setFormat()
void CenterLinePy::setFormat (Py::Object arg)
setter for the Format attribute
References Base::Console(), Base::ConsoleSingleton::Error(), getCenterLinePtr(), TechDraw::LineFormat::m_color, TechDraw::CenterLine::m_format, TechDraw::LineFormat::m_style, TechDraw::LineFormat::m_visible, TechDraw::LineFormat::m_weight, and TechDraw::DrawUtil::pyTupleToColor().
Referenced by PathScripts.PathInspect.GCodeHighlighter::highlightBlock(), PathScripts.PostUtils.GCodeHighlighter::highlightBlock(), and staticCallback_setFormat().
setHorizShift()
void CenterLinePy::setHorizShift (Py::Float arg)
setter for the HorizShift attribute
References getCenterLinePtr(), TechDraw::CenterLine::getVShift(), and TechDraw::CenterLine::setShifts().
Referenced by staticCallback_setHorizShift().
setMode()
void CenterLinePy::setMode (Py::Long arg)
setter for the Mode attribute
References getCenterLinePtr(), and TechDraw::CenterLine::m_mode.
Referenced by staticCallback_setMode().
setPoints()
void CenterLinePy::setPoints (Py::Object arg)
setter for the Points attribute
References Base::Console(), Base::ConsoleSingleton::Error(), getCenterLinePtr(), and TechDraw::CenterLine::m_verts.
Referenced by staticCallback_setPoints().
setRotation()
void CenterLinePy::setRotation (Py::Float arg)
setter for the Rotation attribute
References getCenterLinePtr(), and TechDraw::CenterLine::setRotate().
Referenced by staticCallback_setRotation().
setVertShift()
void CenterLinePy::setVertShift (Py::Float arg)
setter for the VertShift attribute
References getCenterLinePtr(), TechDraw::CenterLine::getHShift(), and TechDraw::CenterLine::setShifts().
Referenced by staticCallback_setVertShift().
staticCallback_clone()
PyObject * CenterLinePy::staticCallback_clone (PyObject * self, PyObject * args) static
callback for the clone() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, clone(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_copy()
PyObject * CenterLinePy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copy(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getEdges()
PyObject * CenterLinePy::staticCallback_getEdges (PyObject * self, void * closure) static
getter callback for the Edges attribute
References Base::BaseExceptionFreeCADError, getEdges(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getExtension()
PyObject * CenterLinePy::staticCallback_getExtension (PyObject * self, void * closure) static
getter callback for the Extension attribute
References Base::BaseExceptionFreeCADError, getExtension(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFaces()
PyObject * CenterLinePy::staticCallback_getFaces (PyObject * self, void * closure) static
getter callback for the Faces attribute
References Base::BaseExceptionFreeCADError, getFaces(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFlip()
PyObject * CenterLinePy::staticCallback_getFlip (PyObject * self, void * closure) static
getter callback for the Flip attribute
References Base::BaseExceptionFreeCADError, getFlip(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFormat()
PyObject * CenterLinePy::staticCallback_getFormat (PyObject * self, void * closure) static
getter callback for the Format attribute
References Base::BaseExceptionFreeCADError, getFormat(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getHorizShift()
PyObject * CenterLinePy::staticCallback_getHorizShift (PyObject * self, void * closure) static
getter callback for the HorizShift attribute
References Base::BaseExceptionFreeCADError, getHorizShift(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMode()
PyObject * CenterLinePy::staticCallback_getMode (PyObject * self, void * closure) static
getter callback for the Mode attribute
References Base::BaseExceptionFreeCADError, getMode(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPoints()
PyObject * CenterLinePy::staticCallback_getPoints (PyObject * self, void * closure) static
getter callback for the Points attribute
References Base::BaseExceptionFreeCADError, getPoints(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRotation()
PyObject * CenterLinePy::staticCallback_getRotation (PyObject * self, void * closure) static
getter callback for the Rotation attribute
References Base::BaseExceptionFreeCADError, getRotation(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTag()
PyObject * CenterLinePy::staticCallback_getTag (PyObject * self, void * closure) static
getter callback for the Tag attribute
References Base::BaseExceptionFreeCADError, getTag(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getType()
PyObject * CenterLinePy::staticCallback_getType (PyObject * self, void * closure) static
getter callback for the Type attribute
References Base::BaseExceptionFreeCADError, getType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVertShift()
PyObject * CenterLinePy::staticCallback_getVertShift (PyObject * self, void * closure) static
getter callback for the VertShift attribute
References Base::BaseExceptionFreeCADError, getVertShift(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setEdges()
int CenterLinePy::staticCallback_setEdges (PyObject * self, PyObject * value, void * closure) static
setter callback for the Edges attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setEdges().
staticCallback_setExtension()
int CenterLinePy::staticCallback_setExtension (PyObject * self, PyObject * value, void * closure) static
setter callback for the Extension attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setExtension().
staticCallback_setFaces()
int CenterLinePy::staticCallback_setFaces (PyObject * self, PyObject * value, void * closure) static
setter callback for the Faces attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setFaces().
staticCallback_setFlip()
int CenterLinePy::staticCallback_setFlip (PyObject * self, PyObject * value, void * closure) static
setter callback for the Flip attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setFlip().
staticCallback_setFormat()
int CenterLinePy::staticCallback_setFormat (PyObject * self, PyObject * value, void * closure) static
setter callback for the Format attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setFormat().
staticCallback_setHorizShift()
int CenterLinePy::staticCallback_setHorizShift (PyObject * self, PyObject * value, void * closure) static
setter callback for the HorizShift attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setHorizShift().
staticCallback_setMode()
int CenterLinePy::staticCallback_setMode (PyObject * self, PyObject * value, void * closure) static
setter callback for the Mode attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setMode().
staticCallback_setPoints()
int CenterLinePy::staticCallback_setPoints (PyObject * self, PyObject * value, void * closure) static
setter callback for the Points attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setPoints().
staticCallback_setRotation()
int CenterLinePy::staticCallback_setRotation (PyObject * self, PyObject * value, void * closure) static
setter callback for the Rotation attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setRotation().
staticCallback_setTag()
int CenterLinePy::staticCallback_setTag (PyObject * self, PyObject * value, void * closure) static
setter callback for the Tag attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setType()
int CenterLinePy::staticCallback_setType (PyObject * self, PyObject * value, void * closure) static
setter callback for the Type attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setVertShift()
int CenterLinePy::staticCallback_setVertShift (PyObject * self, PyObject * value, void * closure) static
setter callback for the VertShift attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setVertShift().
Member Data Documentation
GetterSetter
PyGetSetDef CenterLinePy::GetterSetter static
Attribute structure of CenterLinePy.
Methods
PyMethodDef CenterLinePy::Methods static
Initial value:
= {
    {"clone",
        reinterpret_cast<PyCFunction>( staticCallback_clone ),
        METH_VARARGS,
        "Create a clone of this centerline"
    },
    {"copy",
        reinterpret_cast<PyCFunction>( staticCallback_copy ),
        METH_VARARGS,
        "Create a copy of this centerline"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of CenterLinePy.
Type
PyTypeObject CenterLinePy::Type static
Type structure of CenterLinePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/TechDraw/App/CenterLinePy.h
Sources/FreeCAD/src/Mod/TechDraw/App/CenterLinePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/TechDraw/App/CenterLinePy.cpp