FreeCAD: MeshCore::MeshEvalFoldOversOnSurface Class Reference
MeshCore::MeshEvalFoldOversOnSurface Class Reference
Considers two adjacent triangles with an angle higher than 120 deg of their normals as a fold-over.
#include <Degeneration.h>
Public Member Functions
bool Evaluate ()
Evaluates the mesh kernel with respect to certain criteria.
std::vector< unsigned long > GetIndices () const
MeshEvalFoldOversOnSurface (const MeshKernel &rclM)
~MeshEvalFoldOversOnSurface ()
Public Member Functions inherited from MeshCore::MeshEvaluation
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()
Detailed Description
Considers two adjacent triangles with an angle higher than 120 deg of their normals as a fold-over.
The topology is not affected there.
Constructor & Destructor Documentation
MeshEvalFoldOversOnSurface()
MeshCore::MeshEvalFoldOversOnSurface::MeshEvalFoldOversOnSurface (const MeshKernel & rclM)
~MeshEvalFoldOversOnSurface()
MeshCore::MeshEvalFoldOversOnSurface::~MeshEvalFoldOversOnSurface ()
Member Function Documentation
Evaluate()
bool MeshEvalFoldOversOnSurface::Evaluate () virtual
Evaluates the mesh kernel with respect to certain criteria.
Must be reimplemented by every subclass. This pure virtual function returns false if the mesh kernel is invalid according to this criterion and true if the mesh kernel is correct.
Implements MeshCore::MeshEvaluation.
Referenced by MeshGui::DlgEvaluateMeshImp::on_analyzeFoldsButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_analyzeOrientationButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairAllTogether_clicked(), and Mesh::MeshObject::removeFoldsOnSurface().
GetIndices()
std::vector<unsigned long> MeshCore::MeshEvalFoldOversOnSurface::GetIndices () const
Referenced by MeshGui::DlgEvaluateMeshImp::on_analyzeFoldsButton_clicked(), and Mesh::MeshObject::removeFoldsOnSurface().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Degeneration.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Degeneration.cpp