FreeCAD: Part::BSplineSurfacePy Class Reference
Part::BSplineSurfacePy Class Reference
The python export class for GeomBSplineSurface.
#include <BSplineSurfacePy.h>
Public Types
typedef GeomBSplineSurface * PointerType
Public Types inherited from Part::GeometrySurfacePy
typedef GeomSurface * PointerType
Public Types inherited from Part::GeometryPy
typedef Geometry * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
BSplineSurfacePy (GeomBSplineSurface *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Part::GeometrySurfacePy
GeometrySurfacePy (GeomSurface *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * toShape (PyObject *args)
implementer for the toShape() method
PyObject * getD0 (PyObject *args)
implementer for the getD0() method
PyObject * getDN (PyObject *args)
implementer for the getDN() method
PyObject * value (PyObject *args)
implementer for the value() method
PyObject * tangent (PyObject *args)
implementer for the tangent() method
PyObject * normal (PyObject *args)
implementer for the normal() method
PyObject * projectPoint (PyObject *args, PyObject *kwd)
implementer for the projectPoint() method
PyObject * isUmbillic (PyObject *args)
implementer for the isUmbillic() method
PyObject * curvature (PyObject *args)
implementer for the curvature() method
PyObject * curvatureDirections (PyObject *args)
implementer for the curvatureDirections() method
PyObject * bounds (PyObject *args)
implementer for the bounds() method
PyObject * isPlanar (PyObject *args)
implementer for the isPlanar() method
PyObject * uIso (PyObject *args)
implementer for the uIso() method
PyObject * vIso (PyObject *args)
implementer for the vIso() method
PyObject * isUPeriodic (PyObject *args)
implementer for the isUPeriodic() method
PyObject * isVPeriodic (PyObject *args)
implementer for the isVPeriodic() method
PyObject * isUClosed (PyObject *args)
implementer for the isUClosed() method
PyObject * isVClosed (PyObject *args)
implementer for the isVClosed() method
PyObject * UPeriod (PyObject *args)
implementer for the UPeriod() method
PyObject * VPeriod (PyObject *args)
implementer for the VPeriod() method
PyObject * parameter (PyObject *args)
implementer for the parameter() method
PyObject * toBSpline (PyObject *args, PyObject *kwd)
implementer for the toBSpline() method
PyObject * intersect (PyObject *args)
implementer for the intersect() method
PyObject * intersectSS (PyObject *args)
implementer for the intersectSS() method
Py::String getContinuity (void) const
getter for the Continuity attribute
Py::Object getRotation (void) const
getter for the Rotation attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomSurface * getGeomSurfacePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Part::GeometryPy
GeometryPy (Geometry *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * clone (PyObject *args)
implementer for the clone() method
PyObject * hasExtensionOfType (PyObject *args)
implementer for the hasExtensionOfType() method
PyObject * hasExtensionOfName (PyObject *args)
implementer for the hasExtensionOfName() method
PyObject * getExtensionOfType (PyObject *args)
implementer for the getExtensionOfType() method
PyObject * getExtensionOfName (PyObject *args)
implementer for the getExtensionOfName() method
PyObject * setExtension (PyObject *args)
implementer for the setExtension() method
PyObject * deleteExtensionOfType (PyObject *args)
implementer for the deleteExtensionOfType() method
PyObject * deleteExtensionOfName (PyObject *args)
implementer for the deleteExtensionOfName() method
PyObject * getExtensions (PyObject *args)
implementer for the getExtensions() method
Py::String getTag (void) const
getter for the Tag attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geometry * getGeometryPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::GeometrySurfacePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_toShape (PyObject *self, PyObject *args)
callback for the toShape() method
static PyObject * staticCallback_getD0 (PyObject *self, PyObject *args)
callback for the getD0() method
static PyObject * staticCallback_getDN (PyObject *self, PyObject *args)
callback for the getDN() method
static PyObject * staticCallback_value (PyObject *self, PyObject *args)
callback for the value() method
static PyObject * staticCallback_tangent (PyObject *self, PyObject *args)
callback for the tangent() method
static PyObject * staticCallback_normal (PyObject *self, PyObject *args)
callback for the normal() method
static PyObject * staticCallback_projectPoint (PyObject *self, PyObject *args, PyObject *kwd)
callback for the projectPoint() method
static PyObject * staticCallback_isUmbillic (PyObject *self, PyObject *args)
callback for the isUmbillic() method
static PyObject * staticCallback_curvature (PyObject *self, PyObject *args)
callback for the curvature() method
static PyObject * staticCallback_curvatureDirections (PyObject *self, PyObject *args)
callback for the curvatureDirections() method
static PyObject * staticCallback_bounds (PyObject *self, PyObject *args)
callback for the bounds() method
static PyObject * staticCallback_isPlanar (PyObject *self, PyObject *args)
callback for the isPlanar() method
static PyObject * staticCallback_uIso (PyObject *self, PyObject *args)
callback for the uIso() method
static PyObject * staticCallback_vIso (PyObject *self, PyObject *args)
callback for the vIso() method
static PyObject * staticCallback_isUPeriodic (PyObject *self, PyObject *args)
callback for the isUPeriodic() method
static PyObject * staticCallback_isVPeriodic (PyObject *self, PyObject *args)
callback for the isVPeriodic() method
static PyObject * staticCallback_isUClosed (PyObject *self, PyObject *args)
callback for the isUClosed() method
static PyObject * staticCallback_isVClosed (PyObject *self, PyObject *args)
callback for the isVClosed() method
static PyObject * staticCallback_UPeriod (PyObject *self, PyObject *args)
callback for the UPeriod() method
static PyObject * staticCallback_VPeriod (PyObject *self, PyObject *args)
callback for the VPeriod() method
static PyObject * staticCallback_parameter (PyObject *self, PyObject *args)
callback for the parameter() method
static PyObject * staticCallback_toBSpline (PyObject *self, PyObject *args, PyObject *kwd)
callback for the toBSpline() method
static PyObject * staticCallback_intersect (PyObject *self, PyObject *args)
callback for the intersect() method
static PyObject * staticCallback_intersectSS (PyObject *self, PyObject *args)
callback for the intersectSS() method
static PyObject * staticCallback_getContinuity (PyObject *self, void *closure)
getter callback for the Continuity attribute
static int staticCallback_setContinuity (PyObject *self, PyObject *value, void *closure)
setter callback for the Continuity attribute
static PyObject * staticCallback_getRotation (PyObject *self, void *closure)
getter callback for the Rotation attribute
static int staticCallback_setRotation (PyObject *self, PyObject *value, void *closure)
setter callback for the Rotation attribute
Static Public Member Functions inherited from Part::GeometryPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_clone (PyObject *self, PyObject *args)
callback for the clone() method
static PyObject * staticCallback_hasExtensionOfType (PyObject *self, PyObject *args)
callback for the hasExtensionOfType() method
static PyObject * staticCallback_hasExtensionOfName (PyObject *self, PyObject *args)
callback for the hasExtensionOfName() method
static PyObject * staticCallback_getExtensionOfType (PyObject *self, PyObject *args)
callback for the getExtensionOfType() method
static PyObject * staticCallback_getExtensionOfName (PyObject *self, PyObject *args)
callback for the getExtensionOfName() method
static PyObject * staticCallback_setExtension (PyObject *self, PyObject *args)
callback for the setExtension() method
static PyObject * staticCallback_deleteExtensionOfType (PyObject *self, PyObject *args)
callback for the deleteExtensionOfType() method
static PyObject * staticCallback_deleteExtensionOfName (PyObject *self, PyObject *args)
callback for the deleteExtensionOfName() method
static PyObject * staticCallback_getExtensions (PyObject *self, PyObject *args)
callback for the getExtensions() method
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of BSplineSurfacePy.
static PyMethodDef Methods []
Methods structure of BSplineSurfacePy.
static PyTypeObject Type
Type structure of BSplineSurfacePy.
Static Public Attributes inherited from Part::GeometrySurfacePy
static PyGetSetDef GetterSetter []
Attribute structure of GeometrySurfacePy.
static PyMethodDef Methods []
Methods structure of GeometrySurfacePy.
static PyTypeObject Type
Type structure of GeometrySurfacePy.
Static Public Attributes inherited from Part::GeometryPy
static PyGetSetDef GetterSetter []
Attribute structure of GeometryPy.
static PyMethodDef Methods []
Methods structure of GeometryPy.
static PyTypeObject Type
Type structure of GeometryPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~BSplineSurfacePy ()
Protected Member Functions inherited from Part::GeometrySurfacePy
~GeometrySurfacePy ()
Protected Member Functions inherited from Part::GeometryPy
~GeometryPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * bounds (PyObject *args)
implementer for the bounds() method
PyObject * isURational (PyObject *args)
implementer for the isURational() method
PyObject * isVRational (PyObject *args)
implementer for the isVRational() method
PyObject * isUPeriodic (PyObject *args)
implementer for the isUPeriodic() method
PyObject * isVPeriodic (PyObject *args)
implementer for the isVPeriodic() method
PyObject * isUClosed (PyObject *args)
implementer for the isUClosed() method
PyObject * isVClosed (PyObject *args)
implementer for the isVClosed() method
PyObject * increaseDegree (PyObject *args)
implementer for the increaseDegree() method
PyObject * increaseUMultiplicity (PyObject *args)
implementer for the increaseUMultiplicity() method
PyObject * increaseVMultiplicity (PyObject *args)
implementer for the increaseVMultiplicity() method
PyObject * incrementUMultiplicity (PyObject *args)
implementer for the incrementUMultiplicity() method
PyObject * incrementVMultiplicity (PyObject *args)
implementer for the incrementVMultiplicity() method
PyObject * insertUKnot (PyObject *args)
implementer for the insertUKnot() method
PyObject * insertUKnots (PyObject *args)
implementer for the insertUKnots() method
PyObject * insertVKnot (PyObject *args)
implementer for the insertVKnot() method
PyObject * insertVKnots (PyObject *args)
implementer for the insertVKnots() method
PyObject * removeUKnot (PyObject *args)
implementer for the removeUKnot() method
PyObject * removeVKnot (PyObject *args)
implementer for the removeVKnot() method
PyObject * segment (PyObject *args)
implementer for the segment() method
PyObject * setUKnot (PyObject *args)
implementer for the setUKnot() method
PyObject * setVKnot (PyObject *args)
implementer for the setVKnot() method
PyObject * getUKnot (PyObject *args)
implementer for the getUKnot() method
PyObject * getVKnot (PyObject *args)
implementer for the getVKnot() method
PyObject * setUKnots (PyObject *args)
implementer for the setUKnots() method
PyObject * setVKnots (PyObject *args)
implementer for the setVKnots() method
PyObject * getUKnots (PyObject *args)
implementer for the getUKnots() method
PyObject * getVKnots (PyObject *args)
implementer for the getVKnots() method
PyObject * setPole (PyObject *args)
implementer for the setPole() method
PyObject * setPoleCol (PyObject *args)
implementer for the setPoleCol() method
PyObject * setPoleRow (PyObject *args)
implementer for the setPoleRow() method
PyObject * getPole (PyObject *args)
implementer for the getPole() method
PyObject * getPoles (PyObject *args)
implementer for the getPoles() method
PyObject * setWeight (PyObject *args)
implementer for the setWeight() method
PyObject * setWeightCol (PyObject *args)
implementer for the setWeightCol() method
PyObject * setWeightRow (PyObject *args)
implementer for the setWeightRow() method
PyObject * getWeight (PyObject *args)
implementer for the getWeight() method
PyObject * getWeights (PyObject *args)
implementer for the getWeights() method
PyObject * getPolesAndWeights (PyObject *args)
implementer for the getPolesAndWeights() method
PyObject * getResolution (PyObject *args)
implementer for the getResolution() method
PyObject * movePoint (PyObject *args)
implementer for the movePoint() method
PyObject * setUNotPeriodic (PyObject *args)
implementer for the setUNotPeriodic() method
PyObject * setVNotPeriodic (PyObject *args)
implementer for the setVNotPeriodic() method
PyObject * setUPeriodic (PyObject *args)
implementer for the setUPeriodic() method
PyObject * setVPeriodic (PyObject *args)
implementer for the setVPeriodic() method
PyObject * setUOrigin (PyObject *args)
implementer for the setUOrigin() method
PyObject * setVOrigin (PyObject *args)
implementer for the setVOrigin() method
PyObject * getUMultiplicity (PyObject *args)
implementer for the getUMultiplicity() method
PyObject * getVMultiplicity (PyObject *args)
implementer for the getVMultiplicity() method
PyObject * getUMultiplicities (PyObject *args)
implementer for the getUMultiplicities() method
PyObject * getVMultiplicities (PyObject *args)
implementer for the getVMultiplicities() method
PyObject * exchangeUV (PyObject *args)
implementer for the exchangeUV() method
PyObject * reparametrize (PyObject *args)
implementer for the reparametrize() method
PyObject * approximate (PyObject *args, PyObject *kwd)
implementer for the approximate() method
PyObject * interpolate (PyObject *args)
implementer for the interpolate() method
PyObject * buildFromPolesMultsKnots (PyObject *args, PyObject *kwd)
implementer for the buildFromPolesMultsKnots() method
PyObject * buildFromNSections (PyObject *args)
implementer for the buildFromNSections() method
static PyObject * staticCallback_bounds (PyObject *self, PyObject *args)
callback for the bounds() method
static PyObject * staticCallback_isURational (PyObject *self, PyObject *args)
callback for the isURational() method
static PyObject * staticCallback_isVRational (PyObject *self, PyObject *args)
callback for the isVRational() method
static PyObject * staticCallback_isUPeriodic (PyObject *self, PyObject *args)
callback for the isUPeriodic() method
static PyObject * staticCallback_isVPeriodic (PyObject *self, PyObject *args)
callback for the isVPeriodic() method
static PyObject * staticCallback_isUClosed (PyObject *self, PyObject *args)
callback for the isUClosed() method
static PyObject * staticCallback_isVClosed (PyObject *self, PyObject *args)
callback for the isVClosed() method
static PyObject * staticCallback_increaseDegree (PyObject *self, PyObject *args)
callback for the increaseDegree() method
static PyObject * staticCallback_increaseUMultiplicity (PyObject *self, PyObject *args)
callback for the increaseUMultiplicity() method
static PyObject * staticCallback_increaseVMultiplicity (PyObject *self, PyObject *args)
callback for the increaseVMultiplicity() method
static PyObject * staticCallback_incrementUMultiplicity (PyObject *self, PyObject *args)
callback for the incrementUMultiplicity() method
static PyObject * staticCallback_incrementVMultiplicity (PyObject *self, PyObject *args)
callback for the incrementVMultiplicity() method
static PyObject * staticCallback_insertUKnot (PyObject *self, PyObject *args)
callback for the insertUKnot() method
static PyObject * staticCallback_insertUKnots (PyObject *self, PyObject *args)
callback for the insertUKnots() method
static PyObject * staticCallback_insertVKnot (PyObject *self, PyObject *args)
callback for the insertVKnot() method
static PyObject * staticCallback_insertVKnots (PyObject *self, PyObject *args)
callback for the insertVKnots() method
static PyObject * staticCallback_removeUKnot (PyObject *self, PyObject *args)
callback for the removeUKnot() method
static PyObject * staticCallback_removeVKnot (PyObject *self, PyObject *args)
callback for the removeVKnot() method
static PyObject * staticCallback_segment (PyObject *self, PyObject *args)
callback for the segment() method
static PyObject * staticCallback_setUKnot (PyObject *self, PyObject *args)
callback for the setUKnot() method
static PyObject * staticCallback_setVKnot (PyObject *self, PyObject *args)
callback for the setVKnot() method
static PyObject * staticCallback_getUKnot (PyObject *self, PyObject *args)
callback for the getUKnot() method
static PyObject * staticCallback_getVKnot (PyObject *self, PyObject *args)
callback for the getVKnot() method
static PyObject * staticCallback_setUKnots (PyObject *self, PyObject *args)
callback for the setUKnots() method
static PyObject * staticCallback_setVKnots (PyObject *self, PyObject *args)
callback for the setVKnots() method
static PyObject * staticCallback_getUKnots (PyObject *self, PyObject *args)
callback for the getUKnots() method
static PyObject * staticCallback_getVKnots (PyObject *self, PyObject *args)
callback for the getVKnots() method
static PyObject * staticCallback_setPole (PyObject *self, PyObject *args)
callback for the setPole() method
static PyObject * staticCallback_setPoleCol (PyObject *self, PyObject *args)
callback for the setPoleCol() method
static PyObject * staticCallback_setPoleRow (PyObject *self, PyObject *args)
callback for the setPoleRow() method
static PyObject * staticCallback_getPole (PyObject *self, PyObject *args)
callback for the getPole() method
static PyObject * staticCallback_getPoles (PyObject *self, PyObject *args)
callback for the getPoles() method
static PyObject * staticCallback_setWeight (PyObject *self, PyObject *args)
callback for the setWeight() method
static PyObject * staticCallback_setWeightCol (PyObject *self, PyObject *args)
callback for the setWeightCol() method
static PyObject * staticCallback_setWeightRow (PyObject *self, PyObject *args)
callback for the setWeightRow() method
static PyObject * staticCallback_getWeight (PyObject *self, PyObject *args)
callback for the getWeight() method
static PyObject * staticCallback_getWeights (PyObject *self, PyObject *args)
callback for the getWeights() method
static PyObject * staticCallback_getPolesAndWeights (PyObject *self, PyObject *args)
callback for the getPolesAndWeights() method
static PyObject * staticCallback_getResolution (PyObject *self, PyObject *args)
callback for the getResolution() method
static PyObject * staticCallback_movePoint (PyObject *self, PyObject *args)
callback for the movePoint() method
static PyObject * staticCallback_setUNotPeriodic (PyObject *self, PyObject *args)
callback for the setUNotPeriodic() method
static PyObject * staticCallback_setVNotPeriodic (PyObject *self, PyObject *args)
callback for the setVNotPeriodic() method
static PyObject * staticCallback_setUPeriodic (PyObject *self, PyObject *args)
callback for the setUPeriodic() method
static PyObject * staticCallback_setVPeriodic (PyObject *self, PyObject *args)
callback for the setVPeriodic() method
static PyObject * staticCallback_setUOrigin (PyObject *self, PyObject *args)
callback for the setUOrigin() method
static PyObject * staticCallback_setVOrigin (PyObject *self, PyObject *args)
callback for the setVOrigin() method
static PyObject * staticCallback_getUMultiplicity (PyObject *self, PyObject *args)
callback for the getUMultiplicity() method
static PyObject * staticCallback_getVMultiplicity (PyObject *self, PyObject *args)
callback for the getVMultiplicity() method
static PyObject * staticCallback_getUMultiplicities (PyObject *self, PyObject *args)
callback for the getUMultiplicities() method
static PyObject * staticCallback_getVMultiplicities (PyObject *self, PyObject *args)
callback for the getVMultiplicities() method
static PyObject * staticCallback_exchangeUV (PyObject *self, PyObject *args)
callback for the exchangeUV() method
static PyObject * staticCallback_reparametrize (PyObject *self, PyObject *args)
callback for the reparametrize() method
static PyObject * staticCallback_approximate (PyObject *self, PyObject *args, PyObject *kwd)
callback for the approximate() method
static PyObject * staticCallback_interpolate (PyObject *self, PyObject *args)
callback for the interpolate() method
static PyObject * staticCallback_buildFromPolesMultsKnots (PyObject *self, PyObject *args, PyObject *kwd)
callback for the buildFromPolesMultsKnots() method
static PyObject * staticCallback_buildFromNSections (PyObject *self, PyObject *args)
callback for the buildFromNSections() method
callbacks and implementers for the python object attributes
Py::Long getUDegree (void) const
getter for the UDegree attribute
Py::Long getVDegree (void) const
getter for the VDegree attribute
Py::Long getMaxDegree (void) const
getter for the MaxDegree attribute
Py::Long getNbUPoles (void) const
getter for the NbUPoles attribute
Py::Long getNbVPoles (void) const
getter for the NbVPoles attribute
Py::Long getNbUKnots (void) const
getter for the NbUKnots attribute
Py::Long getNbVKnots (void) const
getter for the NbVKnots attribute
Py::Object getFirstUKnotIndex (void) const
getter for the FirstUKnotIndex attribute
Py::Object getLastUKnotIndex (void) const
getter for the LastUKnotIndex attribute
Py::Object getFirstVKnotIndex (void) const
getter for the FirstVKnotIndex attribute
Py::Object getLastVKnotIndex (void) const
getter for the LastVKnotIndex attribute
Py::List getUKnotSequence (void) const
getter for the UKnotSequence attribute
Py::List getVKnotSequence (void) const
getter for the VKnotSequence attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomBSplineSurface * getGeomBSplineSurfacePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getUDegree (PyObject *self, void *closure)
getter callback for the UDegree attribute
static int staticCallback_setUDegree (PyObject *self, PyObject *value, void *closure)
setter callback for the UDegree attribute
static PyObject * staticCallback_getVDegree (PyObject *self, void *closure)
getter callback for the VDegree attribute
static int staticCallback_setVDegree (PyObject *self, PyObject *value, void *closure)
setter callback for the VDegree attribute
static PyObject * staticCallback_getMaxDegree (PyObject *self, void *closure)
getter callback for the MaxDegree attribute
static int staticCallback_setMaxDegree (PyObject *self, PyObject *value, void *closure)
setter callback for the MaxDegree attribute
static PyObject * staticCallback_getNbUPoles (PyObject *self, void *closure)
getter callback for the NbUPoles attribute
static int staticCallback_setNbUPoles (PyObject *self, PyObject *value, void *closure)
setter callback for the NbUPoles attribute
static PyObject * staticCallback_getNbVPoles (PyObject *self, void *closure)
getter callback for the NbVPoles attribute
static int staticCallback_setNbVPoles (PyObject *self, PyObject *value, void *closure)
setter callback for the NbVPoles attribute
static PyObject * staticCallback_getNbUKnots (PyObject *self, void *closure)
getter callback for the NbUKnots attribute
static int staticCallback_setNbUKnots (PyObject *self, PyObject *value, void *closure)
setter callback for the NbUKnots attribute
static PyObject * staticCallback_getNbVKnots (PyObject *self, void *closure)
getter callback for the NbVKnots attribute
static int staticCallback_setNbVKnots (PyObject *self, PyObject *value, void *closure)
setter callback for the NbVKnots attribute
static PyObject * staticCallback_getFirstUKnotIndex (PyObject *self, void *closure)
getter callback for the FirstUKnotIndex attribute
static int staticCallback_setFirstUKnotIndex (PyObject *self, PyObject *value, void *closure)
setter callback for the FirstUKnotIndex attribute
static PyObject * staticCallback_getLastUKnotIndex (PyObject *self, void *closure)
getter callback for the LastUKnotIndex attribute
static int staticCallback_setLastUKnotIndex (PyObject *self, PyObject *value, void *closure)
setter callback for the LastUKnotIndex attribute
static PyObject * staticCallback_getFirstVKnotIndex (PyObject *self, void *closure)
getter callback for the FirstVKnotIndex attribute
static int staticCallback_setFirstVKnotIndex (PyObject *self, PyObject *value, void *closure)
setter callback for the FirstVKnotIndex attribute
static PyObject * staticCallback_getLastVKnotIndex (PyObject *self, void *closure)
getter callback for the LastVKnotIndex attribute
static int staticCallback_setLastVKnotIndex (PyObject *self, PyObject *value, void *closure)
setter callback for the LastVKnotIndex attribute
static PyObject * staticCallback_getUKnotSequence (PyObject *self, void *closure)
getter callback for the UKnotSequence attribute
static int staticCallback_setUKnotSequence (PyObject *self, PyObject *value, void *closure)
setter callback for the UKnotSequence attribute
static PyObject * staticCallback_getVKnotSequence (PyObject *self, void *closure)
getter callback for the VKnotSequence attribute
static int staticCallback_setVKnotSequence (PyObject *self, PyObject *value, void *closure)
setter callback for the VKnotSequence attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeomBSplineSurface.
Member Typedef Documentation
PointerType
typedef GeomBSplineSurface* Part::BSplineSurfacePy::PointerType
Constructor & Destructor Documentation
~BSplineSurfacePy()
BSplineSurfacePy::~BSplineSurfacePy () protected
BSplineSurfacePy()
BSplineSurfacePy::BSplineSurfacePy (GeomBSplineSurface * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake(), and reparametrize().
Member Function Documentation
approximate()
PyObject * BSplineSurfacePy::approximate (PyObject * args, PyObject * kwd)
implementer for the approximate() method
References getGeomBSplineSurfacePtr(), Part::PartExceptionOCCError, Part::GeomBSplineSurface::setHandle(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by staticCallback_approximate().
bounds()
PyObject * BSplineSurfacePy::bounds (PyObject * args)
implementer for the bounds() method
References Part::GeometryPy::getGeometryPtr(), and draftgeoutils.general::v1().
Referenced by shipCreateShip.TaskPanel.TaskPanel::onData(), and staticCallback_bounds().
buildFromNSections()
PyObject * BSplineSurfacePy::buildFromNSections (PyObject * args)
implementer for the buildFromNSections() method
import math
c = Part.Circle()
c.Radius=50
c = c.trim(0, math.pi)
e1 = Part.Ellipse()
e1.Center = (0, 0, 75)
e1.MajorRadius = 30
e1.MinorRadius = 5
e1 = e1.trim(0, math.pi)
e2 = Part.Ellipse()
e2.Center = (0, 0, 100)
e2.MajorRadius = 20
e2.MinorRadius = 5
e2 = e2.trim(0, math.pi)
bs = Part.BSplineSurface()
bs.buildFromNSections([c, e1, e2])
References getGeomBSplineSurfacePtr(), Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, Part::GeomBSplineSurface::setHandle(), and Part::GeometryCurvePy::Type.
Referenced by staticCallback_buildFromNSections().
buildFromPolesMultsKnots()
PyObject * BSplineSurfacePy::buildFromPolesMultsKnots (PyObject * args, PyObject * kwd)
implementer for the buildFromPolesMultsKnots() method
References getGeomBSplineSurfacePtr(), Part::PartExceptionOCCError, Part::GeomBSplineSurface::setHandle(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by staticCallback_buildFromPolesMultsKnots().
exchangeUV()
PyObject * BSplineSurfacePy::exchangeUV (PyObject * args)
implementer for the exchangeUV() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_exchangeUV().
getCustomAttributes()
PyObject * BSplineSurfacePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getFirstUKnotIndex()
Py::Object BSplineSurfacePy::getFirstUKnotIndex (void) const
getter for the FirstUKnotIndex attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getFirstUKnotIndex().
getFirstVKnotIndex()
Py::Object BSplineSurfacePy::getFirstVKnotIndex (void) const
getter for the FirstVKnotIndex attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getFirstVKnotIndex().
getGeomBSplineSurfacePtr()
GeomBSplineSurface * BSplineSurfacePy::getGeomBSplineSurfacePtr (void) const
getter for the object handled by this class
Referenced by approximate(), buildFromNSections(), buildFromPolesMultsKnots(), and interpolate().
getLastUKnotIndex()
Py::Object BSplineSurfacePy::getLastUKnotIndex (void) const
getter for the LastUKnotIndex attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getLastUKnotIndex().
getLastVKnotIndex()
Py::Object BSplineSurfacePy::getLastVKnotIndex (void) const
getter for the LastVKnotIndex attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getLastVKnotIndex().
getMaxDegree()
Py::Long BSplineSurfacePy::getMaxDegree (void) const
getter for the MaxDegree attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getMaxDegree().
getNbUKnots()
Py::Long BSplineSurfacePy::getNbUKnots (void) const
getter for the NbUKnots attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getNbUKnots().
getNbUPoles()
Py::Long BSplineSurfacePy::getNbUPoles (void) const
getter for the NbUPoles attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getNbUPoles().
getNbVKnots()
Py::Long BSplineSurfacePy::getNbVKnots (void) const
getter for the NbVKnots attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getNbVKnots().
getNbVPoles()
Py::Long BSplineSurfacePy::getNbVPoles (void) const
getter for the NbVPoles attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getNbVPoles().
getPole()
PyObject * BSplineSurfacePy::getPole (PyObject * args)
implementer for the getPole() method
References Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, and draftgeoutils.general::vec().
Referenced by staticCallback_getPole().
getPoles()
PyObject * BSplineSurfacePy::getPoles (PyObject * args)
implementer for the getPoles() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getPoles().
getPolesAndWeights()
PyObject * BSplineSurfacePy::getPolesAndWeights (PyObject * args)
implementer for the getPolesAndWeights() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getPolesAndWeights().
getResolution()
PyObject * BSplineSurfacePy::getResolution (PyObject * args)
implementer for the getResolution() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getResolution().
GetType()
virtual PyTypeObject* Part::BSplineSurfacePy::GetType (void) virtual
Reimplemented from Part::GeometrySurfacePy.
getUDegree()
Py::Long BSplineSurfacePy::getUDegree (void) const
getter for the UDegree attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getUDegree().
getUKnot()
PyObject * BSplineSurfacePy::getUKnot (PyObject * args)
implementer for the getUKnot() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getUKnot().
getUKnots()
PyObject * BSplineSurfacePy::getUKnots (PyObject * args)
implementer for the getUKnots() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getUKnots().
getUKnotSequence()
Py::List BSplineSurfacePy::getUKnotSequence (void) const
getter for the UKnotSequence attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getUKnotSequence().
getUMultiplicities()
PyObject * BSplineSurfacePy::getUMultiplicities (PyObject * args)
implementer for the getUMultiplicities() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getUMultiplicities().
getUMultiplicity()
PyObject * BSplineSurfacePy::getUMultiplicity (PyObject * args)
implementer for the getUMultiplicity() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getUMultiplicity().
getVDegree()
Py::Long BSplineSurfacePy::getVDegree (void) const
getter for the VDegree attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getVDegree().
getVKnot()
PyObject * BSplineSurfacePy::getVKnot (PyObject * args)
implementer for the getVKnot() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getVKnot().
getVKnots()
PyObject * BSplineSurfacePy::getVKnots (PyObject * args)
implementer for the getVKnots() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getVKnots().
getVKnotSequence()
Py::List BSplineSurfacePy::getVKnotSequence (void) const
getter for the VKnotSequence attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getVKnotSequence().
getVMultiplicities()
PyObject * BSplineSurfacePy::getVMultiplicities (PyObject * args)
implementer for the getVMultiplicities() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getVMultiplicities().
getVMultiplicity()
PyObject * BSplineSurfacePy::getVMultiplicity (PyObject * args)
implementer for the getVMultiplicity() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getVMultiplicity().
getWeight()
PyObject * BSplineSurfacePy::getWeight (PyObject * args)
implementer for the getWeight() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getWeight().
getWeights()
PyObject * BSplineSurfacePy::getWeights (PyObject * args)
implementer for the getWeights() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getWeights().
increaseDegree()
PyObject * BSplineSurfacePy::increaseDegree (PyObject * args)
implementer for the increaseDegree() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_increaseDegree().
increaseUMultiplicity()
PyObject * BSplineSurfacePy::increaseUMultiplicity (PyObject * args)
implementer for the increaseUMultiplicity() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_increaseUMultiplicity().
increaseVMultiplicity()
PyObject * BSplineSurfacePy::increaseVMultiplicity (PyObject * args)
implementer for the increaseVMultiplicity() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_increaseVMultiplicity().
incrementUMultiplicity()
PyObject * BSplineSurfacePy::incrementUMultiplicity (PyObject * args)
implementer for the incrementUMultiplicity() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_incrementUMultiplicity().
incrementVMultiplicity()
PyObject * BSplineSurfacePy::incrementVMultiplicity (PyObject * args)
implementer for the incrementVMultiplicity() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_incrementVMultiplicity().
insertUKnot()
PyObject * BSplineSurfacePy::insertUKnot (PyObject * args)
implementer for the insertUKnot() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_insertUKnot().
insertUKnots()
PyObject * BSplineSurfacePy::insertUKnots (PyObject * args)
implementer for the insertUKnots() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_insertUKnots().
insertVKnot()
PyObject * BSplineSurfacePy::insertVKnot (PyObject * args)
implementer for the insertVKnot() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_insertVKnot().
insertVKnots()
PyObject * BSplineSurfacePy::insertVKnots (PyObject * args)
implementer for the insertVKnots() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_insertVKnots().
interpolate()
PyObject * BSplineSurfacePy::interpolate (PyObject * args)
implementer for the interpolate() method
References getGeomBSplineSurfacePtr(), Part::PartExceptionOCCError, Part::GeomBSplineSurface::setHandle(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by staticCallback_interpolate().
isUClosed()
PyObject * BSplineSurfacePy::isUClosed (PyObject * args)
implementer for the isUClosed() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_isUClosed().
isUPeriodic()
PyObject * BSplineSurfacePy::isUPeriodic (PyObject * args)
implementer for the isUPeriodic() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_isUPeriodic().
isURational()
PyObject * BSplineSurfacePy::isURational (PyObject * args)
implementer for the isURational() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_isURational().
isVClosed()
PyObject * BSplineSurfacePy::isVClosed (PyObject * args)
implementer for the isVClosed() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_isVClosed().
isVPeriodic()
PyObject * BSplineSurfacePy::isVPeriodic (PyObject * args)
implementer for the isVPeriodic() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_isVPeriodic().
isVRational()
PyObject * BSplineSurfacePy::isVRational (PyObject * args)
implementer for the isVRational() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_isVRational().
movePoint()
PyObject * BSplineSurfacePy::movePoint (PyObject * args)
implementer for the movePoint() method
References Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, Base::VectorPy::Type, and Part::GeometrySurfacePy::value().
Referenced by staticCallback_movePoint().
PyInit()
int BSplineSurfacePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::GeometrySurfacePy.
PyMake()
PyObject * BSplineSurfacePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References BSplineSurfacePy().
removeUKnot()
PyObject * BSplineSurfacePy::removeUKnot (PyObject * args)
implementer for the removeUKnot() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_removeUKnot().
removeVKnot()
PyObject * BSplineSurfacePy::removeVKnot (PyObject * args)
implementer for the removeVKnot() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_removeVKnot().
reparametrize()
PyObject * BSplineSurfacePy::reparametrize (PyObject * args)
implementer for the reparametrize() method
References BSplineSurfacePy(), Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_reparametrize().
representation()
std::string BSplineSurfacePy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
segment()
PyObject * BSplineSurfacePy::segment (PyObject * args)
implementer for the segment() method
References Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, and draftgeoutils.general::v1().
Referenced by staticCallback_segment().
setCustomAttributes()
int BSplineSurfacePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setPole()
PyObject * BSplineSurfacePy::setPole (PyObject * args)
implementer for the setPole() method
References Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, Base::VectorPy::Type, Part::GeometrySurfacePy::value(), and draftgeoutils.general::vec().
Referenced by staticCallback_setPole().
setPoleCol()
PyObject * BSplineSurfacePy::setPoleCol (PyObject * args)
implementer for the setPoleCol() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setPoleCol().
setPoleRow()
PyObject * BSplineSurfacePy::setPoleRow (PyObject * args)
implementer for the setPoleRow() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setPoleRow().
setUKnot()
PyObject * BSplineSurfacePy::setUKnot (PyObject * args)
implementer for the setUKnot() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_setUKnot().
setUKnots()
PyObject * BSplineSurfacePy::setUKnots (PyObject * args)
implementer for the setUKnots() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setUKnots().
setUNotPeriodic()
PyObject * BSplineSurfacePy::setUNotPeriodic (PyObject * args)
implementer for the setUNotPeriodic() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setUNotPeriodic().
setUOrigin()
PyObject * BSplineSurfacePy::setUOrigin (PyObject * args)
implementer for the setUOrigin() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setUOrigin().
setUPeriodic()
PyObject * BSplineSurfacePy::setUPeriodic (PyObject * args)
implementer for the setUPeriodic() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setUPeriodic().
setVKnot()
PyObject * BSplineSurfacePy::setVKnot (PyObject * args)
implementer for the setVKnot() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_setVKnot().
setVKnots()
PyObject * BSplineSurfacePy::setVKnots (PyObject * args)
implementer for the setVKnots() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setVKnots().
setVNotPeriodic()
PyObject * BSplineSurfacePy::setVNotPeriodic (PyObject * args)
implementer for the setVNotPeriodic() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setVNotPeriodic().
setVOrigin()
PyObject * BSplineSurfacePy::setVOrigin (PyObject * args)
implementer for the setVOrigin() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setVOrigin().
setVPeriodic()
PyObject * BSplineSurfacePy::setVPeriodic (PyObject * args)
implementer for the setVPeriodic() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setVPeriodic().
setWeight()
PyObject * BSplineSurfacePy::setWeight (PyObject * args)
implementer for the setWeight() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setWeight().
setWeightCol()
PyObject * BSplineSurfacePy::setWeightCol (PyObject * args)
implementer for the setWeightCol() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setWeightCol().
setWeightRow()
PyObject * BSplineSurfacePy::setWeightRow (PyObject * args)
implementer for the setWeightRow() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setWeightRow().
staticCallback_approximate()
PyObject * BSplineSurfacePy::staticCallback_approximate (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the approximate() method
References approximate(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_bounds()
PyObject * BSplineSurfacePy::staticCallback_bounds (PyObject * self, PyObject * args) static
callback for the bounds() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, bounds(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_buildFromNSections()
PyObject * BSplineSurfacePy::staticCallback_buildFromNSections (PyObject * self, PyObject * args) static
callback for the buildFromNSections() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, buildFromNSections(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_buildFromPolesMultsKnots()
PyObject * BSplineSurfacePy::staticCallback_buildFromPolesMultsKnots (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the buildFromPolesMultsKnots() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, buildFromPolesMultsKnots(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_exchangeUV()
PyObject * BSplineSurfacePy::staticCallback_exchangeUV (PyObject * self, PyObject * args) static
callback for the exchangeUV() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, exchangeUV(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getFirstUKnotIndex()
PyObject * BSplineSurfacePy::staticCallback_getFirstUKnotIndex (PyObject * self, void * closure) static
getter callback for the FirstUKnotIndex attribute
References Base::BaseExceptionFreeCADError, getFirstUKnotIndex(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFirstVKnotIndex()
PyObject * BSplineSurfacePy::staticCallback_getFirstVKnotIndex (PyObject * self, void * closure) static
getter callback for the FirstVKnotIndex attribute
References Base::BaseExceptionFreeCADError, getFirstVKnotIndex(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getLastUKnotIndex()
PyObject * BSplineSurfacePy::staticCallback_getLastUKnotIndex (PyObject * self, void * closure) static
getter callback for the LastUKnotIndex attribute
References Base::BaseExceptionFreeCADError, getLastUKnotIndex(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getLastVKnotIndex()
PyObject * BSplineSurfacePy::staticCallback_getLastVKnotIndex (PyObject * self, void * closure) static
getter callback for the LastVKnotIndex attribute
References Base::BaseExceptionFreeCADError, getLastVKnotIndex(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMaxDegree()
PyObject * BSplineSurfacePy::staticCallback_getMaxDegree (PyObject * self, void * closure) static
getter callback for the MaxDegree attribute
References Base::BaseExceptionFreeCADError, getMaxDegree(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNbUKnots()
PyObject * BSplineSurfacePy::staticCallback_getNbUKnots (PyObject * self, void * closure) static
getter callback for the NbUKnots attribute
References Base::BaseExceptionFreeCADError, getNbUKnots(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNbUPoles()
PyObject * BSplineSurfacePy::staticCallback_getNbUPoles (PyObject * self, void * closure) static
getter callback for the NbUPoles attribute
References Base::BaseExceptionFreeCADError, getNbUPoles(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNbVKnots()
PyObject * BSplineSurfacePy::staticCallback_getNbVKnots (PyObject * self, void * closure) static
getter callback for the NbVKnots attribute
References Base::BaseExceptionFreeCADError, getNbVKnots(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNbVPoles()
PyObject * BSplineSurfacePy::staticCallback_getNbVPoles (PyObject * self, void * closure) static
getter callback for the NbVPoles attribute
References Base::BaseExceptionFreeCADError, getNbVPoles(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPole()
PyObject * BSplineSurfacePy::staticCallback_getPole (PyObject * self, PyObject * args) static
callback for the getPole() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPole(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPoles()
PyObject * BSplineSurfacePy::staticCallback_getPoles (PyObject * self, PyObject * args) static
callback for the getPoles() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPoles(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPolesAndWeights()
PyObject * BSplineSurfacePy::staticCallback_getPolesAndWeights (PyObject * self, PyObject * args) static
callback for the getPolesAndWeights() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPolesAndWeights(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getResolution()
PyObject * BSplineSurfacePy::staticCallback_getResolution (PyObject * self, PyObject * args) static
callback for the getResolution() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getResolution(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getUDegree()
PyObject * BSplineSurfacePy::staticCallback_getUDegree (PyObject * self, void * closure) static
getter callback for the UDegree attribute
References Base::BaseExceptionFreeCADError, getUDegree(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getUKnot()
PyObject * BSplineSurfacePy::staticCallback_getUKnot (PyObject * self, PyObject * args) static
callback for the getUKnot() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getUKnot(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getUKnots()
PyObject * BSplineSurfacePy::staticCallback_getUKnots (PyObject * self, PyObject * args) static
callback for the getUKnots() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getUKnots(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getUKnotSequence()
PyObject * BSplineSurfacePy::staticCallback_getUKnotSequence (PyObject * self, void * closure) static
getter callback for the UKnotSequence attribute
References Base::BaseExceptionFreeCADError, getUKnotSequence(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getUMultiplicities()
PyObject * BSplineSurfacePy::staticCallback_getUMultiplicities (PyObject * self, PyObject * args) static
callback for the getUMultiplicities() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getUMultiplicities(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getUMultiplicity()
PyObject * BSplineSurfacePy::staticCallback_getUMultiplicity (PyObject * self, PyObject * args) static
callback for the getUMultiplicity() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getUMultiplicity(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVDegree()
PyObject * BSplineSurfacePy::staticCallback_getVDegree (PyObject * self, void * closure) static
getter callback for the VDegree attribute
References Base::BaseExceptionFreeCADError, getVDegree(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVKnot()
PyObject * BSplineSurfacePy::staticCallback_getVKnot (PyObject * self, PyObject * args) static
callback for the getVKnot() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getVKnot(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVKnots()
PyObject * BSplineSurfacePy::staticCallback_getVKnots (PyObject * self, PyObject * args) static
callback for the getVKnots() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getVKnots(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVKnotSequence()
PyObject * BSplineSurfacePy::staticCallback_getVKnotSequence (PyObject * self, void * closure) static
getter callback for the VKnotSequence attribute
References Base::BaseExceptionFreeCADError, getVKnotSequence(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVMultiplicities()
PyObject * BSplineSurfacePy::staticCallback_getVMultiplicities (PyObject * self, PyObject * args) static
callback for the getVMultiplicities() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getVMultiplicities(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVMultiplicity()
PyObject * BSplineSurfacePy::staticCallback_getVMultiplicity (PyObject * self, PyObject * args) static
callback for the getVMultiplicity() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getVMultiplicity(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getWeight()
PyObject * BSplineSurfacePy::staticCallback_getWeight (PyObject * self, PyObject * args) static
callback for the getWeight() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getWeight(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getWeights()
PyObject * BSplineSurfacePy::staticCallback_getWeights (PyObject * self, PyObject * args) static
callback for the getWeights() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getWeights(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_increaseDegree()
PyObject * BSplineSurfacePy::staticCallback_increaseDegree (PyObject * self, PyObject * args) static
callback for the increaseDegree() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, increaseDegree(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_increaseUMultiplicity()
PyObject * BSplineSurfacePy::staticCallback_increaseUMultiplicity (PyObject * self, PyObject * args) static
callback for the increaseUMultiplicity() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, increaseUMultiplicity(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_increaseVMultiplicity()
PyObject * BSplineSurfacePy::staticCallback_increaseVMultiplicity (PyObject * self, PyObject * args) static
callback for the increaseVMultiplicity() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, increaseVMultiplicity(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_incrementUMultiplicity()
PyObject * BSplineSurfacePy::staticCallback_incrementUMultiplicity (PyObject * self, PyObject * args) static
callback for the incrementUMultiplicity() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, incrementUMultiplicity(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_incrementVMultiplicity()
PyObject * BSplineSurfacePy::staticCallback_incrementVMultiplicity (PyObject * self, PyObject * args) static
callback for the incrementVMultiplicity() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, incrementVMultiplicity(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_insertUKnot()
PyObject * BSplineSurfacePy::staticCallback_insertUKnot (PyObject * self, PyObject * args) static
callback for the insertUKnot() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, insertUKnot(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_insertUKnots()
PyObject * BSplineSurfacePy::staticCallback_insertUKnots (PyObject * self, PyObject * args) static
callback for the insertUKnots() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, insertUKnots(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_insertVKnot()
PyObject * BSplineSurfacePy::staticCallback_insertVKnot (PyObject * self, PyObject * args) static
callback for the insertVKnot() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, insertVKnot(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_insertVKnots()
PyObject * BSplineSurfacePy::staticCallback_insertVKnots (PyObject * self, PyObject * args) static
callback for the insertVKnots() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, insertVKnots(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_interpolate()
PyObject * BSplineSurfacePy::staticCallback_interpolate (PyObject * self, PyObject * args) static
callback for the interpolate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, interpolate(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_isUClosed()
PyObject * BSplineSurfacePy::staticCallback_isUClosed (PyObject * self, PyObject * args) static
callback for the isUClosed() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isUClosed(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isUPeriodic()
PyObject * BSplineSurfacePy::staticCallback_isUPeriodic (PyObject * self, PyObject * args) static
callback for the isUPeriodic() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isUPeriodic(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isURational()
PyObject * BSplineSurfacePy::staticCallback_isURational (PyObject * self, PyObject * args) static
callback for the isURational() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isURational(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isVClosed()
PyObject * BSplineSurfacePy::staticCallback_isVClosed (PyObject * self, PyObject * args) static
callback for the isVClosed() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), isVClosed(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isVPeriodic()
PyObject * BSplineSurfacePy::staticCallback_isVPeriodic (PyObject * self, PyObject * args) static
callback for the isVPeriodic() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), isVPeriodic(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isVRational()
PyObject * BSplineSurfacePy::staticCallback_isVRational (PyObject * self, PyObject * args) static
callback for the isVRational() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), isVRational(), and Base::PyObjectBase::PyObjectBase().
staticCallback_movePoint()
PyObject * BSplineSurfacePy::staticCallback_movePoint (PyObject * self, PyObject * args) static
callback for the movePoint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), movePoint(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_removeUKnot()
PyObject * BSplineSurfacePy::staticCallback_removeUKnot (PyObject * self, PyObject * args) static
callback for the removeUKnot() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeUKnot(), and Base::PyObjectBase::startNotify().
staticCallback_removeVKnot()
PyObject * BSplineSurfacePy::staticCallback_removeVKnot (PyObject * self, PyObject * args) static
callback for the removeVKnot() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeVKnot(), and Base::PyObjectBase::startNotify().
staticCallback_reparametrize()
PyObject * BSplineSurfacePy::staticCallback_reparametrize (PyObject * self, PyObject * args) static
callback for the reparametrize() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and reparametrize().
staticCallback_segment()
PyObject * BSplineSurfacePy::staticCallback_segment (PyObject * self, PyObject * args) static
callback for the segment() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), segment(), and Base::PyObjectBase::startNotify().
staticCallback_setFirstUKnotIndex()
int BSplineSurfacePy::staticCallback_setFirstUKnotIndex (PyObject * self, PyObject * value, void * closure) static
setter callback for the FirstUKnotIndex attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setFirstVKnotIndex()
int BSplineSurfacePy::staticCallback_setFirstVKnotIndex (PyObject * self, PyObject * value, void * closure) static
setter callback for the FirstVKnotIndex attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setLastUKnotIndex()
int BSplineSurfacePy::staticCallback_setLastUKnotIndex (PyObject * self, PyObject * value, void * closure) static
setter callback for the LastUKnotIndex attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setLastVKnotIndex()
int BSplineSurfacePy::staticCallback_setLastVKnotIndex (PyObject * self, PyObject * value, void * closure) static
setter callback for the LastVKnotIndex attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setMaxDegree()
int BSplineSurfacePy::staticCallback_setMaxDegree (PyObject * self, PyObject * value, void * closure) static
setter callback for the MaxDegree attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setNbUKnots()
int BSplineSurfacePy::staticCallback_setNbUKnots (PyObject * self, PyObject * value, void * closure) static
setter callback for the NbUKnots attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setNbUPoles()
int BSplineSurfacePy::staticCallback_setNbUPoles (PyObject * self, PyObject * value, void * closure) static
setter callback for the NbUPoles attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setNbVKnots()
int BSplineSurfacePy::staticCallback_setNbVKnots (PyObject * self, PyObject * value, void * closure) static
setter callback for the NbVKnots attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setNbVPoles()
int BSplineSurfacePy::staticCallback_setNbVPoles (PyObject * self, PyObject * value, void * closure) static
setter callback for the NbVPoles attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPole()
PyObject * BSplineSurfacePy::staticCallback_setPole (PyObject * self, PyObject * args) static
callback for the setPole() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setPole(), and Base::PyObjectBase::startNotify().
staticCallback_setPoleCol()
PyObject * BSplineSurfacePy::staticCallback_setPoleCol (PyObject * self, PyObject * args) static
callback for the setPoleCol() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setPoleCol(), and Base::PyObjectBase::startNotify().
staticCallback_setPoleRow()
PyObject * BSplineSurfacePy::staticCallback_setPoleRow (PyObject * self, PyObject * args) static
callback for the setPoleRow() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setPoleRow(), and Base::PyObjectBase::startNotify().
staticCallback_setUDegree()
int BSplineSurfacePy::staticCallback_setUDegree (PyObject * self, PyObject * value, void * closure) static
setter callback for the UDegree attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setUKnot()
PyObject * BSplineSurfacePy::staticCallback_setUKnot (PyObject * self, PyObject * args) static
callback for the setUKnot() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setUKnot(), and Base::PyObjectBase::startNotify().
staticCallback_setUKnots()
PyObject * BSplineSurfacePy::staticCallback_setUKnots (PyObject * self, PyObject * args) static
callback for the setUKnots() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setUKnots(), and Base::PyObjectBase::startNotify().
staticCallback_setUKnotSequence()
int BSplineSurfacePy::staticCallback_setUKnotSequence (PyObject * self, PyObject * value, void * closure) static
setter callback for the UKnotSequence attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setUNotPeriodic()
PyObject * BSplineSurfacePy::staticCallback_setUNotPeriodic (PyObject * self, PyObject * args) static
callback for the setUNotPeriodic() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setUNotPeriodic(), and Base::PyObjectBase::startNotify().
staticCallback_setUOrigin()
PyObject * BSplineSurfacePy::staticCallback_setUOrigin (PyObject * self, PyObject * args) static
callback for the setUOrigin() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setUOrigin(), and Base::PyObjectBase::startNotify().
staticCallback_setUPeriodic()
PyObject * BSplineSurfacePy::staticCallback_setUPeriodic (PyObject * self, PyObject * args) static
callback for the setUPeriodic() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setUPeriodic(), and Base::PyObjectBase::startNotify().
staticCallback_setVDegree()
int BSplineSurfacePy::staticCallback_setVDegree (PyObject * self, PyObject * value, void * closure) static
setter callback for the VDegree attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setVKnot()
PyObject * BSplineSurfacePy::staticCallback_setVKnot (PyObject * self, PyObject * args) static
callback for the setVKnot() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setVKnot(), and Base::PyObjectBase::startNotify().
staticCallback_setVKnots()
PyObject * BSplineSurfacePy::staticCallback_setVKnots (PyObject * self, PyObject * args) static
callback for the setVKnots() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setVKnots(), and Base::PyObjectBase::startNotify().
staticCallback_setVKnotSequence()
int BSplineSurfacePy::staticCallback_setVKnotSequence (PyObject * self, PyObject * value, void * closure) static
setter callback for the VKnotSequence attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setVNotPeriodic()
PyObject * BSplineSurfacePy::staticCallback_setVNotPeriodic (PyObject * self, PyObject * args) static
callback for the setVNotPeriodic() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setVNotPeriodic(), and Base::PyObjectBase::startNotify().
staticCallback_setVOrigin()
PyObject * BSplineSurfacePy::staticCallback_setVOrigin (PyObject * self, PyObject * args) static
callback for the setVOrigin() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setVOrigin(), and Base::PyObjectBase::startNotify().
staticCallback_setVPeriodic()
PyObject * BSplineSurfacePy::staticCallback_setVPeriodic (PyObject * self, PyObject * args) static
callback for the setVPeriodic() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setVPeriodic(), and Base::PyObjectBase::startNotify().
staticCallback_setWeight()
PyObject * BSplineSurfacePy::staticCallback_setWeight (PyObject * self, PyObject * args) static
callback for the setWeight() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setWeight(), and Base::PyObjectBase::startNotify().
staticCallback_setWeightCol()
PyObject * BSplineSurfacePy::staticCallback_setWeightCol (PyObject * self, PyObject * args) static
callback for the setWeightCol() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setWeightCol(), and Base::PyObjectBase::startNotify().
staticCallback_setWeightRow()
PyObject * BSplineSurfacePy::staticCallback_setWeightRow (PyObject * self, PyObject * args) static
callback for the setWeightRow() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setWeightRow(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef BSplineSurfacePy::GetterSetter static
Attribute structure of BSplineSurfacePy.
Methods
PyMethodDef BSplineSurfacePy::Methods static
Methods structure of BSplineSurfacePy.
Type
PyTypeObject BSplineSurfacePy::Type static
Type structure of BSplineSurfacePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/BSplineSurfacePy.h
Sources/FreeCAD/src/Mod/Part/App/BSplineSurfacePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/BSplineSurfacePy.cpp