FreeCAD: StartPage.StartPage Namespace Reference
StartPage.StartPage Namespace Reference
Functions
def buildCard (filename, method, arg=None)
def checkPostOpenStartPage ()
def encode (text)
def exportTestFile ()
def getDefaultIcon ()
def gethexcolor (color)
def getInfo (filename)
def handle ()
def isOpenableByFreeCAD (filename)
def postStart ()
Variables
defaulticon = None
dictionary iconbank = {}
iconprovider = QtGui.QFileIconProvider()
tempfolder = None
Function Documentation
buildCard()
def StartPage.StartPage.buildCard (filename, method, arg = None)
References StartPage.StartPage.encode(), StartPage.StartPage.getInfo(), and StartPage.StartPage.isOpenableByFreeCAD().
Referenced by StartPage.StartPage.handle().
checkPostOpenStartPage()
def StartPage.StartPage.checkPostOpenStartPage ()
References StartPage.StartPage.postStart().
encode()
def StartPage.StartPage.encode (text)
Referenced by StartPage.StartPage.buildCard(), and StartPage.StartPage.handle().
exportTestFile()
def StartPage.StartPage.exportTestFile ()
References StartPage.StartPage.handle().
getDefaultIcon()
def StartPage.StartPage.getDefaultIcon ()
Referenced by StartPage.StartPage.getInfo().
gethexcolor()
def StartPage.StartPage.gethexcolor (color)
Referenced by StartPage.StartPage.handle().
getInfo()
def StartPage.StartPage.getInfo (filename)
References StartPage.StartPage.getDefaultIcon().
Referenced by StartPage.StartPage.buildCard().
handle()
def StartPage.StartPage.handle ()
References StartPage.StartPage.buildCard(), StartPage.StartPage.encode(), and StartPage.StartPage.gethexcolor().
Referenced by StartPage.StartPage.exportTestFile().
isOpenableByFreeCAD()
def StartPage.StartPage.isOpenableByFreeCAD (filename)
Referenced by StartPage.StartPage.buildCard().
postStart()
def StartPage.StartPage.postStart ()
Referenced by StartPage.StartPage.checkPostOpenStartPage().
Variable Documentation
defaulticon
StartPage.StartPage.defaulticon = None
iconbank
dictionary StartPage.StartPage.iconbank = {}
iconprovider
StartPage.StartPage.iconprovider = QtGui.QFileIconProvider()
tempfolder
StartPage.StartPage.tempfolder = None