FreeCAD: SketcherGui::DrawSketchHandlerSlot Class Reference
SketcherGui::DrawSketchHandlerSlot Class Reference
#include <DrawSketchHandlerSlot.h>
Public Types
enum BoxMode { STATUS_SEEK_First , STATUS_SEEK_Second , STATUS_End }
mode table
enum SNAP_DIR { SNAP_DIR_Horz , SNAP_DIR_Vert }
enum SNAP_MODE { SNAP_MODE_Free , SNAP_MODE_Straight }
Public Member Functions
DrawSketchHandlerSlot ()
virtual void mouseMove (Base::Vector2d onSketchPos) override
virtual bool pressButton (Base::Vector2d onSketchPos) override
virtual bool releaseButton (Base::Vector2d onSketchPos) override
virtual ~DrawSketchHandlerSlot ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void activate (ViewProviderSketch *)
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::PointPos::none, bool createowncommand=true)
void deactivate ()
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual void mouseMove (Base::Vector2d onSketchPos)=0
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual bool pressButton (Base::Vector2d onSketchPos)=0
virtual void quit (void)
virtual void registerPressedKey (bool, int)
virtual bool releaseButton (Base::Vector2d onSketchPos)=0
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Attributes
double dx
double dy
std::vector< Base::Vector2d > EditCurve
BoxMode Mode
double r
SNAP_DIR SnapDir
SNAP_MODE SnapMode
Base::Vector2d StartPos
std::vector< AutoConstraint > sugConstr1
std::vector< AutoConstraint > sugConstr2
Protected Attributes inherited from SketcherGui::DrawSketchHandler
ViewProviderSketch * sketchgui
QCursor oldCursor
QCursor actCursor
QPixmap actCursorPixmap
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
virtual QString getCrosshairCursorSVGName () const
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
void updateCursor ()
updates the actCursor with the icon by calling getCrosshairCursorSVGName(), enabling to set data member dependent icons (i.e.
void unsetCursor (void)
restitutes the cursor that was in use at the moment of starting the DrawSketchHandler (i.e. oldCursor)
void applyCursor (void)
restitutes the DSH cached cursor (e.g. without any tail due to autoconstraints, ...)
unsigned long getCrosshairColor ()
returns the color to be used for the crosshair (configurable as a parameter)
qreal devicePixelRatio ()
functions to set the cursor to a given svgName (to be migrated to NVI style)
void drawEdit (const std::vector< Base::Vector2d > &EditCurve)
void drawEdit (const std::list< std::vector< Base::Vector2d > > &list)
void drawEdit (const std::vector< Part::Geometry * > &geometries)
void drawEditMarkers (const std::vector< Base::Vector2d > &EditMarkers, unsigned int augmentationlevel=0)
void setAxisPickStyle (bool on)
void moveCursorToSketchPoint (Base::Vector2d point)
void preselectAtPoint (Base::Vector2d point)
void drawPositionAtCursor (const Base::Vector2d &position)
void drawDirectionAtCursor (const Base::Vector2d &position, const Base::Vector2d &origin)
int getPreselectPoint (void) const
int getPreselectCurve (void) const
int getPreselectCross (void) const
Sketcher::SketchObject * getSketchObject ()
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
Member Enumeration Documentation
BoxMode
enum SketcherGui::DrawSketchHandlerSlot::BoxMode
mode table
Enumerator
STATUS_SEEK_First
enum value -—.
STATUS_SEEK_Second
enum value -—.
STATUS_End
SNAP_DIR
enum SketcherGui::DrawSketchHandlerSlot::SNAP_DIR
Enumerator
SNAP_DIR_Horz
SNAP_DIR_Vert
SNAP_MODE
enum SketcherGui::DrawSketchHandlerSlot::SNAP_MODE
Enumerator
SNAP_MODE_Free
SNAP_MODE_Straight
Constructor & Destructor Documentation
DrawSketchHandlerSlot()
SketcherGui::DrawSketchHandlerSlot::DrawSketchHandlerSlot ()
~DrawSketchHandlerSlot()
virtual SketcherGui::DrawSketchHandlerSlot::~DrawSketchHandlerSlot () virtual
Member Function Documentation
mouseMove()
virtual void SketcherGui::DrawSketchHandlerSlot::mouseMove (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::applyCursor(), SketcherGui::DrawSketchHandler::drawEdit(), dx, dy, EditCurve, Mode, SketcherGui::DrawSketchHandler::renderSuggestConstraintsCursor(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), SketcherGui::DrawSketchHandler::setPositionText(), Base::sgn(), SNAP_DIR_Horz, SNAP_DIR_Vert, SNAP_MODE_Free, SNAP_MODE_Straight, SnapDir, StartPos, STATUS_SEEK_First, STATUS_SEEK_Second, sugConstr1, sugConstr2, SketcherGui::AutoConstraint::VERTEX_NO_TANGENCY, Base::Vector2d::x, and Base::Vector2d::y.
pressButton()
virtual bool SketcherGui::DrawSketchHandlerSlot::pressButton (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
References Mode, StartPos, STATUS_End, STATUS_SEEK_First, and STATUS_SEEK_Second.
releaseButton()
virtual bool SketcherGui::DrawSketchHandlerSlot::releaseButton (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), SketcherGui::DrawSketchHandler::applyCursor(), Gui::Command::commitCommand(), Base::Console(), SketcherGui::Construction, SketcherGui::DrawSketchHandler::createAutoConstraints(), Gui::Command::Doc, SketcherGui::DrawSketchHandler::drawEdit(), dx, dy, EditCurve, Base::ConsoleSingleton::Error(), SketcherGui::geometryCreationMode, App::GetApplication(), ParameterGrp::GetBool(), SketcherGui::DrawSketchHandler::getHighestCurveIndex(), Gui::ViewProviderDocumentObject::getObject(), Gui::Command::getObjectCmd(), App::Application::GetParameterGroupByPath(), Sketcher::Horizontal, Sketcher::mid, Mode, Sketcher::none, Gui::Command::openCommand(), SketcherGui::ViewProviderSketch::purgeHandler(), draftutils.translate::QT_TRANSLATE_NOOP, SketcherGui::DrawSketchHandler::resetPositionText(), SketcherGui::DrawSketchHandler::sketchgui, SNAP_DIR_Horz, SNAP_MODE_Straight, SnapDir, StartPos, STATUS_End, STATUS_SEEK_First, sugConstr1, sugConstr2, SketcherGui::tryAutoRecompute(), SketcherGui::tryAutoRecomputeIfNotSolve(), SketcherGui::AutoConstraint::Type, SketcherGui::DrawSketchHandler::unsetCursor(), Sketcher::Vertical, Base::Vector2d::x, and Base::Vector2d::y.
Member Data Documentation
dx
double SketcherGui::DrawSketchHandlerSlot::dx protected
Referenced by mouseMove(), and releaseButton().
dy
double SketcherGui::DrawSketchHandlerSlot::dy protected
Referenced by mouseMove(), and releaseButton().
EditCurve
std::vector<Base::Vector2d> SketcherGui::DrawSketchHandlerSlot::EditCurve protected
Referenced by mouseMove(), and releaseButton().
Mode
BoxMode SketcherGui::DrawSketchHandlerSlot::Mode protected
Referenced by mouseMove(), pressButton(), and releaseButton().
r
double SketcherGui::DrawSketchHandlerSlot::r protected
SnapDir
SNAP_DIR SketcherGui::DrawSketchHandlerSlot::SnapDir protected
Referenced by mouseMove(), and releaseButton().
SnapMode
SNAP_MODE SketcherGui::DrawSketchHandlerSlot::SnapMode protected
StartPos
Base::Vector2d SketcherGui::DrawSketchHandlerSlot::StartPos protected
Referenced by mouseMove(), pressButton(), and releaseButton().
sugConstr1
std::vector<AutoConstraint> SketcherGui::DrawSketchHandlerSlot::sugConstr1 protected
Referenced by mouseMove(), and releaseButton().
sugConstr2
std::vector<AutoConstraint> SketcherGui::DrawSketchHandlerSlot::sugConstr2 protected
Referenced by mouseMove(), and releaseButton().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/DrawSketchHandlerSlot.h