FreeCAD: TechDraw::CenterLine Class Reference
TechDraw::CenterLine Class Reference
#include <Cosmetic.h>
Public Types
enum CLMODE { VERTICAL, HORIZONTAL, ALIGNED }
enum CLTYPE { FACE, EDGE, VERTEX }
Public Member Functions
CenterLine ()
CenterLine (Base::Vector3d p1, Base::Vector3d p2)
CenterLine (Base::Vector3d p1, Base::Vector3d p2, int m, double h, double v, double r, double x)
CenterLine (CenterLine *cl)
CenterLine (TechDraw::BaseGeom *bg)
CenterLine * clone (void) const
CenterLine * copy (void) const
void dump (const char *title)
double getExtend (void)
bool getFlip (void)
double getHShift (void)
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
double getRotate (void)
boost::uuids::uuid getTag () const
virtual std::string getTagAsString (void) const
double getVShift (void)
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
TechDraw::BaseGeom * scaledGeometry (TechDraw::DrawViewPart *partFeat)
void setExtend (double e)
void setFlip (bool f)
void setRotate (double r)
void setShifts (double h, double v)
std::string toString (void) const
virtual ~CenterLine ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static std::pair< Base::Vector3d, Base::Vector3d > calcEndPoints (TechDraw::DrawViewPart *partFeat, std::vector< std::string > faceNames, int mode, double ext, double m_hShift, double m_vShift, double rotate)
static std::pair< Base::Vector3d, Base::Vector3d > calcEndPoints2Lines (TechDraw::DrawViewPart *partFeat, std::vector< std::string > faceNames, int vert, double ext, double m_hShift, double m_vShift, double rotate, bool flip)
static std::pair< Base::Vector3d, Base::Vector3d > calcEndPoints2Points (TechDraw::DrawViewPart *partFeat, std::vector< std::string > faceNames, int vert, double ext, double m_hShift, double m_vShift, double rotate, bool flip)
static CenterLine * CenterLineBuilder (TechDraw::DrawViewPart *partFeat, std::vector< std::string > subs, int mode=0, bool flip=false)
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Public Attributes
std::vector< std::string > m_edges
Base::Vector3d m_end
double m_extendBy
std::vector< std::string > m_faces
bool m_flip2Line
LineFormat m_format
TechDraw::BaseGeom * m_geometry
double m_hShift
int m_mode
double m_rotate
Base::Vector3d m_start
int m_type
std::vector< std::string > m_verts
double m_vShift
Protected Member Functions
void assignTag (const TechDraw::CenterLine *cl)
void createNewTag ()
void initialize ()
Protected Attributes
Py::Object PythonObject
boost::uuids::uuid tag
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Member Enumeration Documentation
CLMODE
enum TechDraw::CenterLine::CLMODE
Enumerator
VERTICAL
HORIZONTAL
ALIGNED
CLTYPE
enum TechDraw::CenterLine::CLTYPE
Enumerator
FACE
EDGE
VERTEX
Constructor & Destructor Documentation
CenterLine() [1/5]
CenterLine::CenterLine (void)
Referenced by copy().
CenterLine() [2/5]
CenterLine::CenterLine (TechDraw::CenterLine * cl)
References initialize(), m_end, m_extendBy, m_flip2Line, m_geometry, m_hShift, m_mode, m_rotate, m_start, m_type, and m_vShift.
CenterLine() [3/5]
CenterLine::CenterLine (TechDraw::BaseGeom * bg)
References TechDraw::BaseGeom::getEndPoint(), TechDraw::BaseGeom::getStartPoint(), initialize(), m_end, m_extendBy, m_flip2Line, m_geometry, m_hShift, m_mode, m_rotate, m_start, m_type, and m_vShift.
CenterLine() [4/5]
CenterLine::CenterLine (Base::Vector3d p1, Base::Vector3d p2)
References TechDraw::BaseGeom::baseFactory(), initialize(), TechDraw::DrawUtil::invertY(), m_end, m_extendBy, m_flip2Line, m_geometry, m_hShift, m_mode, m_rotate, m_start, m_type, m_vShift, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
CenterLine() [5/5]
CenterLine::CenterLine (Base::Vector3d p1, Base::Vector3d p2, int m, double h, double v, double r, double x)
References TechDraw::BaseGeom::baseFactory(), initialize(), TechDraw::DrawUtil::invertY(), m_end, m_extendBy, m_flip2Line, m_geometry, m_hShift, m_mode, m_rotate, m_start, m_type, m_vShift, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
~CenterLine()
CenterLine::~CenterLine () virtual
Member Function Documentation
assignTag()
void CenterLine::assignTag (const TechDraw::CenterLine * cl) protected
References Base::Persistence::getTypeId(), and tag.
calcEndPoints()
std::pair< Base::Vector3d, Base::Vector3d > CenterLine::calcEndPoints (TechDraw::DrawViewPart * partFeat, std::vector< std::string > faceNames, int mode, double ext, double m_hShift, double m_vShift, double rotate) static
References Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::DrawUtil::fpCompare(), TechDraw::DrawViewPart::getFaceEdgesByIndex(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), TechDraw::DrawView::getScale(), Base::ConsoleSingleton::Message(), Base::Vector3< _Precision >::Normalize(), draftfunctions.rotate::rotate(), draftfunctions.scale::scale(), Base::ConsoleSingleton::Warning(), Base::Vector3< _Precision >::x, and Base::Vector3< _Precision >::y.
Referenced by CenterLineBuilder(), and scaledGeometry().
calcEndPoints2Lines()
std::pair< Base::Vector3d, Base::Vector3d > CenterLine::calcEndPoints2Lines (TechDraw::DrawViewPart * partFeat, std::vector< std::string > faceNames, int vert, double ext, double m_hShift, double m_vShift, double rotate, bool flip) static
References Base::Console(), TechDraw::DrawUtil::fpCompare(), TechDraw::DrawViewPart::getEdgeGeometry(), TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), TechDraw::DrawView::getScale(), Base::ConsoleSingleton::Message(), Base::Vector3< _Precision >::Normalize(), draftfunctions.rotate::rotate(), draftfunctions.scale::scale(), Base::ConsoleSingleton::Warning(), Base::Vector3< _Precision >::x, and Base::Vector3< _Precision >::y.
Referenced by CenterLineBuilder(), and scaledGeometry().
calcEndPoints2Points()
std::pair< Base::Vector3d, Base::Vector3d > CenterLine::calcEndPoints2Points (TechDraw::DrawViewPart * partFeat, std::vector< std::string > faceNames, int vert, double ext, double m_hShift, double m_vShift, double rotate, bool flip) static
References Base::Console(), TechDraw::DrawUtil::fpCompare(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), TechDraw::DrawViewPart::getProjVertexByIndex(), TechDraw::DrawView::getScale(), Base::Vector3< _Precision >::Length(), Base::Vector3< _Precision >::Normalize(), draftfunctions.rotate::rotate(), draftfunctions.scale::scale(), draftgeoutils.general::v1(), Base::ConsoleSingleton::Warning(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by CenterLineBuilder(), and scaledGeometry().
CenterLineBuilder()
CenterLine * CenterLine::CenterLineBuilder (TechDraw::DrawViewPart * partFeat, std::vector< std::string > subs, int mode = 0, bool flip = false) static
References calcEndPoints(), calcEndPoints2Lines(), calcEndPoints2Points(), Base::Console(), TechDraw::DrawUtil::formatVector(), draftgeoutils.general::geomType(), TechDraw::DrawUtil::getGeomTypeFromName(), m_edges, m_faces, m_flip2Line, m_mode, m_type, m_verts, and Base::ConsoleSingleton::Warning().
Referenced by TechDraw::DrawViewPartPy::makeCenterLine().
clone()
CenterLine * CenterLine::clone (void) const
References copy(), and tag.
Referenced by ArchPanel.CommandPanelSheet::Activated(), and TechDraw::CenterLinePy::clone().
copy()
CenterLine * CenterLine::copy (void) const
References CenterLine(), TechDraw::BaseGeom::copy(), m_edges, m_end, m_extendBy, m_faces, m_flip2Line, m_format, m_geometry, m_hShift, m_mode, m_rotate, m_start, m_type, m_verts, and m_vShift.
Referenced by clone(), and TechDraw::CenterLinePy::copy().
createNewTag()
void CenterLine::createNewTag () protected
References tag.
Referenced by initialize().
dump()
void CenterLine::dump (const char * title)
References Base::Console(), Base::ConsoleSingleton::Message(), and toString().
getExtend()
double CenterLine::getExtend (void)
References m_extendBy.
Referenced by TechDraw::CenterLinePy::getExtension().
getFlip()
bool CenterLine::getFlip (void)
References m_flip2Line.
Referenced by TechDraw::CenterLinePy::getFlip().
getHShift()
double CenterLine::getHShift (void)
References m_hShift.
Referenced by TechDraw::CenterLinePy::getHorizShift(), and TechDraw::CenterLinePy::setVertShift().
getMemSize()
unsigned int CenterLine::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
getPyObject()
PyObject * CenterLine::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
References PythonObject.
Referenced by TechDraw::DrawViewPartPy::getCenterLine(), and TechDraw::DrawViewPartPy::getCenterLineBySelection().
getRotate()
double CenterLine::getRotate (void)
References m_rotate.
Referenced by TechDraw::CenterLinePy::getRotation().
getTag()
boost::uuids::uuid CenterLine::getTag (void) const
References tag.
Referenced by getTagAsString().
getTagAsString()
std::string CenterLine::getTagAsString (void) const virtual
References getTag().
Referenced by TechDraw::CosmeticExtension::addCenterLine(), TechDraw::CosmeticExtension::getCenterLine(), initialize(), and scaledGeometry().
getVShift()
double CenterLine::getVShift (void)
References m_vShift.
Referenced by TechDraw::CenterLinePy::getVertShift(), and TechDraw::CenterLinePy::setHorizShift().
initialize()
void CenterLine::initialize (void) protected
References TechDraw::CENTERLINE, TechDraw::BaseGeom::classOfEdge, TechDraw::BaseGeom::cosmetic, createNewTag(), TechDraw::ecHARD, getTagAsString(), TechDraw::BaseGeom::hlrVisible, m_geometry, TechDraw::BaseGeom::setCosmeticTag(), and TechDraw::BaseGeom::source().
Referenced by CenterLine().
Restore()
void CenterLine::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References Base::Console(), TechDraw::GeometryUtils::edgeFromCircle(), TechDraw::GeometryUtils::edgeFromCircleArc(), TechDraw::GeometryUtils::edgeFromGeneric(), App::Color::fromHexString(), Base::XMLReader::getAttribute(), Base::XMLReader::getAttributeAsFloat(), Base::XMLReader::getAttributeAsInteger(), TechDraw::LineFormat::m_color, m_edges, m_end, m_extendBy, m_faces, m_flip2Line, m_format, m_geometry, m_hShift, m_mode, m_rotate, m_start, TechDraw::LineFormat::m_style, m_type, m_verts, TechDraw::LineFormat::m_visible, m_vShift, TechDraw::LineFormat::m_weight, TechDraw::BaseGeom::occEdge, Base::XMLReader::readElement(), Base::XMLReader::readEndElement(), TechDraw::Circle::Restore(), TechDraw::AOC::Restore(), TechDraw::Generic::Restore(), TechDraw::CosmeticVertex::restoreCosmetic(), Base::ConsoleSingleton::Warning(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by TechDraw::PropertyCenterLineList::Restore().
Save()
void CenterLine::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References App::Color::asHexString(), Base::Console(), Base::Writer::decInd(), Base::ConsoleSingleton::Error(), TechDraw::BaseGeom::geomType, Base::Writer::incInd(), Base::Writer::ind(), TechDraw::LineFormat::m_color, m_edges, m_end, m_extendBy, m_faces, m_flip2Line, m_format, m_geometry, m_hShift, m_mode, m_rotate, m_start, TechDraw::LineFormat::m_style, m_type, m_verts, TechDraw::LineFormat::m_visible, m_vShift, TechDraw::LineFormat::m_weight, Base::ConsoleSingleton::Message(), TechDraw::Circle::Save(), TechDraw::AOC::Save(), TechDraw::Generic::Save(), Base::Writer::Stream(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
scaledGeometry()
TechDraw::BaseGeom * CenterLine::scaledGeometry (TechDraw::DrawViewPart * partFeat)
References TechDraw::BaseGeom::baseFactory(), calcEndPoints(), calcEndPoints2Lines(), calcEndPoints2Points(), TechDraw::CENTERLINE, TechDraw::BaseGeom::classOfEdge, Base::Console(), TechDraw::BaseGeom::cosmetic, TechDraw::ecHARD, Base::ConsoleSingleton::Error(), TechDraw::DrawView::getScale(), getTagAsString(), TechDraw::BaseGeom::hlrVisible, Base::Vector3< _Precision >::IsEqual(), m_edges, m_extendBy, m_faces, m_flip2Line, m_geometry, m_hShift, m_mode, m_rotate, m_type, m_verts, m_vShift, Base::ConsoleSingleton::Message(), TechDraw::scaleShape(), TechDraw::BaseGeom::setCosmeticTag(), TechDraw::BaseGeom::source(), Base::ConsoleSingleton::Warning(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by TechDraw::DrawViewPart::add1CLToGE().
setExtend()
void CenterLine::setExtend (double e)
References m_extendBy.
Referenced by TechDrawGui::TaskCenterLine::createCenterLine(), and TechDraw::CenterLinePy::setExtension().
setFlip()
void CenterLine::setFlip (bool f)
References m_flip2Line.
Referenced by TechDraw::CenterLinePy::setFlip().
setRotate()
void CenterLine::setRotate (double r)
References m_rotate.
Referenced by TechDrawGui::TaskCenterLine::createCenterLine(), and TechDraw::CenterLinePy::setRotation().
setShifts()
void CenterLine::setShifts (double h, double v)
References m_hShift, and m_vShift.
Referenced by TechDrawGui::TaskCenterLine::createCenterLine(), TechDraw::CenterLinePy::setHorizShift(), and TechDraw::CenterLinePy::setVertShift().
toString()
std::string CenterLine::toString (void) const
References m_end, m_extendBy, m_faces, m_flip2Line, m_format, m_hShift, m_mode, m_rotate, m_start, m_type, m_vShift, TechDraw::LineFormat::toString(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by dump().
Member Data Documentation
m_edges
std::vector<std::string> TechDraw::CenterLine::m_edges
Referenced by CenterLineBuilder(), copy(), TechDraw::CenterLinePy::getEdges(), Restore(), Save(), scaledGeometry(), and TechDraw::CenterLinePy::setEdges().
m_end
Base::Vector3d TechDraw::CenterLine::m_end
Referenced by CenterLine(), copy(), Restore(), Save(), and toString().
m_extendBy
double TechDraw::CenterLine::m_extendBy
Referenced by CenterLine(), copy(), getExtend(), Restore(), Save(), scaledGeometry(), setExtend(), TechDrawGui::TaskCenterLine::setUiEdit(), toString(), and TechDrawGui::TaskCenterLine::updateCenterLine().
m_faces
std::vector<std::string> TechDraw::CenterLine::m_faces
Referenced by CenterLineBuilder(), copy(), TechDraw::CenterLinePy::getFaces(), Restore(), Save(), scaledGeometry(), TechDraw::CenterLinePy::setFaces(), and toString().
m_flip2Line
bool TechDraw::CenterLine::m_flip2Line
Referenced by CenterLine(), CenterLineBuilder(), copy(), TechDrawGui::TaskCenterLine::createCenterLine(), getFlip(), Restore(), Save(), scaledGeometry(), setFlip(), TechDrawGui::TaskCenterLine::setUiEdit(), toString(), and TechDrawGui::TaskCenterLine::updateCenterLine().
m_format
LineFormat TechDraw::CenterLine::m_format
Referenced by TechDrawGui::TaskLineDecor::applyDecorations(), copy(), TechDrawGui::TaskCenterLine::createCenterLine(), TechDrawGui::QGIViewPart::formatGeomFromCenterLine(), TechDrawGui::TaskLineDecor::getDefaults(), TechDraw::CenterLinePy::getFormat(), Restore(), Save(), TechDraw::CenterLinePy::setFormat(), TechDrawGui::TaskCenterLine::setUiEdit(), toString(), and TechDrawGui::TaskCenterLine::updateCenterLine().
m_geometry
TechDraw::BaseGeom* TechDraw::CenterLine::m_geometry
Referenced by CenterLine(), copy(), initialize(), Restore(), Save(), and scaledGeometry().
m_hShift
double TechDraw::CenterLine::m_hShift
Referenced by CenterLine(), copy(), getHShift(), Restore(), Save(), scaledGeometry(), setShifts(), TechDrawGui::TaskCenterLine::setUiEdit(), toString(), and TechDrawGui::TaskCenterLine::updateCenterLine().
m_mode
int TechDraw::CenterLine::m_mode
Referenced by CenterLine(), CenterLineBuilder(), copy(), TechDraw::CenterLinePy::getMode(), Restore(), Save(), scaledGeometry(), TechDraw::CenterLinePy::setMode(), TechDrawGui::TaskCenterLine::setUiEdit(), TechDrawGui::TaskCenterLine::TaskCenterLine(), toString(), and TechDrawGui::TaskCenterLine::updateCenterLine().
m_rotate
double TechDraw::CenterLine::m_rotate
Referenced by CenterLine(), copy(), getRotate(), Restore(), Save(), scaledGeometry(), setRotate(), TechDrawGui::TaskCenterLine::setUiEdit(), toString(), and TechDrawGui::TaskCenterLine::updateCenterLine().
m_start
Base::Vector3d TechDraw::CenterLine::m_start
Referenced by CenterLine(), copy(), Restore(), Save(), and toString().
m_type
int TechDraw::CenterLine::m_type
Referenced by CenterLine(), CenterLineBuilder(), copy(), TechDraw::CenterLinePy::getType(), Restore(), Save(), scaledGeometry(), TechDrawGui::TaskCenterLine::setUiEdit(), TechDrawGui::TaskCenterLine::TaskCenterLine(), toString(), and TechDrawGui::TaskCenterLine::updateCenterLine().
m_verts
std::vector<std::string> TechDraw::CenterLine::m_verts
Referenced by CenterLineBuilder(), copy(), TechDraw::CenterLinePy::getPoints(), Restore(), Save(), scaledGeometry(), and TechDraw::CenterLinePy::setPoints().
m_vShift
double TechDraw::CenterLine::m_vShift
Referenced by CenterLine(), copy(), getVShift(), Restore(), Save(), scaledGeometry(), setShifts(), TechDrawGui::TaskCenterLine::setUiEdit(), toString(), and TechDrawGui::TaskCenterLine::updateCenterLine().
PythonObject
Py::Object TechDraw::CenterLine::PythonObject protected
Referenced by getPyObject().
tag
boost::uuids::uuid TechDraw::CenterLine::tag protected
Referenced by assignTag(), clone(), createNewTag(), Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.ChunkBase::dump_header(), and getTag().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/App/Cosmetic.h
Sources/FreeCAD/src/Mod/TechDraw/App/Cosmetic.cpp