FreeCAD: femexamples.thermomech_flow1d Namespace Reference
femexamples.thermomech_flow1d Namespace Reference
Functions
def get_explanation (header="")
def get_information ()
def setup (doc=None, solvertype="ccxtools")
Function Documentation
get_explanation()
def femexamples.thermomech_flow1d.get_explanation (header = "")
Referenced by femexamples.thermomech_flow1d.setup().
get_information()
def femexamples.thermomech_flow1d.get_information ()
Referenced by femexamples.thermomech_flow1d.setup().
setup()
def femexamples.thermomech_flow1d.setup (doc = None, solvertype = "ccxtools")
References femexamples.thermomech_flow1d.get_explanation(), femexamples.thermomech_flow1d.get_information(), ObjectsFem.makeAnalysis(), ObjectsFem.makeConstraintSelfWeight(), ObjectsFem.makeElementFluid1D(), ObjectsFem.makeMaterialFluid(), ObjectsFem.makeMeshGmsh(), ObjectsFem.makeSolverCalculix(), ObjectsFem.makeSolverCalculixCcxTools(), draftmake.make_wire.makeWire, and draftgeoutils.general.vec().