FreeCAD: Part::SpherePy Class Reference
Part::SpherePy Class Reference
The python export class for GeomSphere.
#include <SpherePy.h>
Public Types
typedef GeomSphere * PointerType
Public Types inherited from Part::GeometrySurfacePy
typedef GeomSurface * PointerType
Public Types inherited from Part::GeometryPy
typedef Geometry * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
SpherePy (GeomSphere *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Part::GeometrySurfacePy
GeometrySurfacePy (GeomSurface *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * toShape (PyObject *args)
implementer for the toShape() method
PyObject * getD0 (PyObject *args)
implementer for the getD0() method
PyObject * getDN (PyObject *args)
implementer for the getDN() method
PyObject * value (PyObject *args)
implementer for the value() method
PyObject * tangent (PyObject *args)
implementer for the tangent() method
PyObject * normal (PyObject *args)
implementer for the normal() method
PyObject * projectPoint (PyObject *args, PyObject *kwd)
implementer for the projectPoint() method
PyObject * isUmbillic (PyObject *args)
implementer for the isUmbillic() method
PyObject * curvature (PyObject *args)
implementer for the curvature() method
PyObject * curvatureDirections (PyObject *args)
implementer for the curvatureDirections() method
PyObject * bounds (PyObject *args)
implementer for the bounds() method
PyObject * isPlanar (PyObject *args)
implementer for the isPlanar() method
PyObject * uIso (PyObject *args)
implementer for the uIso() method
PyObject * vIso (PyObject *args)
implementer for the vIso() method
PyObject * isUPeriodic (PyObject *args)
implementer for the isUPeriodic() method
PyObject * isVPeriodic (PyObject *args)
implementer for the isVPeriodic() method
PyObject * isUClosed (PyObject *args)
implementer for the isUClosed() method
PyObject * isVClosed (PyObject *args)
implementer for the isVClosed() method
PyObject * UPeriod (PyObject *args)
implementer for the UPeriod() method
PyObject * VPeriod (PyObject *args)
implementer for the VPeriod() method
PyObject * parameter (PyObject *args)
implementer for the parameter() method
PyObject * toBSpline (PyObject *args, PyObject *kwd)
implementer for the toBSpline() method
PyObject * intersect (PyObject *args)
implementer for the intersect() method
PyObject * intersectSS (PyObject *args)
implementer for the intersectSS() method
Py::String getContinuity (void) const
getter for the Continuity attribute
Py::Object getRotation (void) const
getter for the Rotation attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomSurface * getGeomSurfacePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Part::GeometryPy
GeometryPy (Geometry *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * clone (PyObject *args)
implementer for the clone() method
PyObject * hasExtensionOfType (PyObject *args)
implementer for the hasExtensionOfType() method
PyObject * hasExtensionOfName (PyObject *args)
implementer for the hasExtensionOfName() method
PyObject * getExtensionOfType (PyObject *args)
implementer for the getExtensionOfType() method
PyObject * getExtensionOfName (PyObject *args)
implementer for the getExtensionOfName() method
PyObject * setExtension (PyObject *args)
implementer for the setExtension() method
PyObject * deleteExtensionOfType (PyObject *args)
implementer for the deleteExtensionOfType() method
PyObject * deleteExtensionOfName (PyObject *args)
implementer for the deleteExtensionOfName() method
PyObject * getExtensions (PyObject *args)
implementer for the getExtensions() method
Py::String getTag (void) const
getter for the Tag attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geometry * getGeometryPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::GeometrySurfacePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_toShape (PyObject *self, PyObject *args)
callback for the toShape() method
static PyObject * staticCallback_getD0 (PyObject *self, PyObject *args)
callback for the getD0() method
static PyObject * staticCallback_getDN (PyObject *self, PyObject *args)
callback for the getDN() method
static PyObject * staticCallback_value (PyObject *self, PyObject *args)
callback for the value() method
static PyObject * staticCallback_tangent (PyObject *self, PyObject *args)
callback for the tangent() method
static PyObject * staticCallback_normal (PyObject *self, PyObject *args)
callback for the normal() method
static PyObject * staticCallback_projectPoint (PyObject *self, PyObject *args, PyObject *kwd)
callback for the projectPoint() method
static PyObject * staticCallback_isUmbillic (PyObject *self, PyObject *args)
callback for the isUmbillic() method
static PyObject * staticCallback_curvature (PyObject *self, PyObject *args)
callback for the curvature() method
static PyObject * staticCallback_curvatureDirections (PyObject *self, PyObject *args)
callback for the curvatureDirections() method
static PyObject * staticCallback_bounds (PyObject *self, PyObject *args)
callback for the bounds() method
static PyObject * staticCallback_isPlanar (PyObject *self, PyObject *args)
callback for the isPlanar() method
static PyObject * staticCallback_uIso (PyObject *self, PyObject *args)
callback for the uIso() method
static PyObject * staticCallback_vIso (PyObject *self, PyObject *args)
callback for the vIso() method
static PyObject * staticCallback_isUPeriodic (PyObject *self, PyObject *args)
callback for the isUPeriodic() method
static PyObject * staticCallback_isVPeriodic (PyObject *self, PyObject *args)
callback for the isVPeriodic() method
static PyObject * staticCallback_isUClosed (PyObject *self, PyObject *args)
callback for the isUClosed() method
static PyObject * staticCallback_isVClosed (PyObject *self, PyObject *args)
callback for the isVClosed() method
static PyObject * staticCallback_UPeriod (PyObject *self, PyObject *args)
callback for the UPeriod() method
static PyObject * staticCallback_VPeriod (PyObject *self, PyObject *args)
callback for the VPeriod() method
static PyObject * staticCallback_parameter (PyObject *self, PyObject *args)
callback for the parameter() method
static PyObject * staticCallback_toBSpline (PyObject *self, PyObject *args, PyObject *kwd)
callback for the toBSpline() method
static PyObject * staticCallback_intersect (PyObject *self, PyObject *args)
callback for the intersect() method
static PyObject * staticCallback_intersectSS (PyObject *self, PyObject *args)
callback for the intersectSS() method
static PyObject * staticCallback_getContinuity (PyObject *self, void *closure)
getter callback for the Continuity attribute
static int staticCallback_setContinuity (PyObject *self, PyObject *value, void *closure)
setter callback for the Continuity attribute
static PyObject * staticCallback_getRotation (PyObject *self, void *closure)
getter callback for the Rotation attribute
static int staticCallback_setRotation (PyObject *self, PyObject *value, void *closure)
setter callback for the Rotation attribute
Static Public Member Functions inherited from Part::GeometryPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_clone (PyObject *self, PyObject *args)
callback for the clone() method
static PyObject * staticCallback_hasExtensionOfType (PyObject *self, PyObject *args)
callback for the hasExtensionOfType() method
static PyObject * staticCallback_hasExtensionOfName (PyObject *self, PyObject *args)
callback for the hasExtensionOfName() method
static PyObject * staticCallback_getExtensionOfType (PyObject *self, PyObject *args)
callback for the getExtensionOfType() method
static PyObject * staticCallback_getExtensionOfName (PyObject *self, PyObject *args)
callback for the getExtensionOfName() method
static PyObject * staticCallback_setExtension (PyObject *self, PyObject *args)
callback for the setExtension() method
static PyObject * staticCallback_deleteExtensionOfType (PyObject *self, PyObject *args)
callback for the deleteExtensionOfType() method
static PyObject * staticCallback_deleteExtensionOfName (PyObject *self, PyObject *args)
callback for the deleteExtensionOfName() method
static PyObject * staticCallback_getExtensions (PyObject *self, PyObject *args)
callback for the getExtensions() method
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of SpherePy.
static PyMethodDef Methods []
Methods structure of SpherePy.
static PyTypeObject Type
Type structure of SpherePy.
Static Public Attributes inherited from Part::GeometrySurfacePy
static PyGetSetDef GetterSetter []
Attribute structure of GeometrySurfacePy.
static PyMethodDef Methods []
Methods structure of GeometrySurfacePy.
static PyTypeObject Type
Type structure of GeometrySurfacePy.
Static Public Attributes inherited from Part::GeometryPy
static PyGetSetDef GetterSetter []
Attribute structure of GeometryPy.
static PyMethodDef Methods []
Methods structure of GeometryPy.
static PyTypeObject Type
Type structure of GeometryPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~SpherePy ()
Protected Member Functions inherited from Part::GeometrySurfacePy
~GeometrySurfacePy ()
Protected Member Functions inherited from Part::GeometryPy
~GeometryPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object attributes
Py::Float getRadius (void) const
getter for the Radius attribute
void setRadius (Py::Float arg)
setter for the Radius attribute
Py::Float getArea (void) const
getter for the Area attribute
Py::Float getVolume (void) const
getter for the Volume attribute
Py::Object getCenter (void) const
getter for the Center attribute
void setCenter (Py::Object arg)
setter for the Center attribute
Py::Object getAxis (void) const
getter for the Axis attribute
void setAxis (Py::Object arg)
setter for the Axis attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomSphere * getGeomSpherePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getRadius (PyObject *self, void *closure)
getter callback for the Radius attribute
static int staticCallback_setRadius (PyObject *self, PyObject *value, void *closure)
setter callback for the Radius attribute
static PyObject * staticCallback_getArea (PyObject *self, void *closure)
getter callback for the Area attribute
static int staticCallback_setArea (PyObject *self, PyObject *value, void *closure)
setter callback for the Area attribute
static PyObject * staticCallback_getVolume (PyObject *self, void *closure)
getter callback for the Volume attribute
static int staticCallback_setVolume (PyObject *self, PyObject *value, void *closure)
setter callback for the Volume attribute
static PyObject * staticCallback_getCenter (PyObject *self, void *closure)
getter callback for the Center attribute
static int staticCallback_setCenter (PyObject *self, PyObject *value, void *closure)
setter callback for the Center attribute
static PyObject * staticCallback_getAxis (PyObject *self, void *closure)
getter callback for the Axis attribute
static int staticCallback_setAxis (PyObject *self, PyObject *value, void *closure)
setter callback for the Axis attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeomSphere.
Member Typedef Documentation
PointerType
typedef GeomSphere* Part::SpherePy::PointerType
Constructor & Destructor Documentation
~SpherePy()
SpherePy::~SpherePy () protected
SpherePy()
SpherePy::SpherePy (GeomSphere * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getArea()
Py::Float SpherePy::getArea (void) const
getter for the Area attribute
References getGeomSpherePtr().
Referenced by staticCallback_getArea().
getAxis()
Py::Object SpherePy::getAxis (void) const
getter for the Axis attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getAxis().
getCenter()
Py::Object SpherePy::getCenter (void) const
getter for the Center attribute
References getGeomSpherePtr().
Referenced by staticCallback_getCenter().
getCustomAttributes()
PyObject * SpherePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getGeomSpherePtr()
GeomSphere * SpherePy::getGeomSpherePtr (void) const
getter for the object handled by this class
Referenced by getArea(), getCenter(), getRadius(), getVolume(), PyInit(), representation(), setCenter(), and setRadius().
getRadius()
Py::Float SpherePy::getRadius (void) const
getter for the Radius attribute
References getGeomSpherePtr().
Referenced by staticCallback_getRadius().
GetType()
virtual PyTypeObject* Part::SpherePy::GetType (void) virtual
Reimplemented from Part::GeometrySurfacePy.
getVolume()
Py::Float SpherePy::getVolume (void) const
getter for the Volume attribute
References getGeomSpherePtr().
Referenced by staticCallback_getVolume().
PyInit()
int SpherePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::GeometrySurfacePy.
References getGeomSpherePtr().
PyMake()
PyObject * SpherePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References SpherePy().
representation()
std::string SpherePy::representation (void) const
References getGeomSpherePtr().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setAxis()
void SpherePy::setAxis (Py::Object arg)
setter for the Axis attribute
References Part::GeometryPy::getGeometryPtr(), Base::VectorPy::Type, and Part::GeometrySurfacePy::value().
Referenced by staticCallback_setAxis().
setCenter()
void SpherePy::setCenter (Py::Object arg)
setter for the Center attribute
References getGeomSpherePtr(), Base::VectorPy::Type, Part::GeometrySurfacePy::value(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by staticCallback_setCenter().
setCustomAttributes()
int SpherePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setRadius()
void SpherePy::setRadius (Py::Float arg)
setter for the Radius attribute
References getGeomSpherePtr().
Referenced by staticCallback_setRadius().
staticCallback_getArea()
PyObject * SpherePy::staticCallback_getArea (PyObject * self, void * closure) static
getter callback for the Area attribute
References Base::BaseExceptionFreeCADError, getArea(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getAxis()
PyObject * SpherePy::staticCallback_getAxis (PyObject * self, void * closure) static
getter callback for the Axis attribute
References Base::BaseExceptionFreeCADError, getAxis(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCenter()
PyObject * SpherePy::staticCallback_getCenter (PyObject * self, void * closure) static
getter callback for the Center attribute
References Base::BaseExceptionFreeCADError, getCenter(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRadius()
PyObject * SpherePy::staticCallback_getRadius (PyObject * self, void * closure) static
getter callback for the Radius attribute
References Base::BaseExceptionFreeCADError, getRadius(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVolume()
PyObject * SpherePy::staticCallback_getVolume (PyObject * self, void * closure) static
getter callback for the Volume attribute
References Base::BaseExceptionFreeCADError, getVolume(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setArea()
int SpherePy::staticCallback_setArea (PyObject * self, PyObject * value, void * closure) static
setter callback for the Area attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setAxis()
int SpherePy::staticCallback_setAxis (PyObject * self, PyObject * value, void * closure) static
setter callback for the Axis attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setAxis().
staticCallback_setCenter()
int SpherePy::staticCallback_setCenter (PyObject * self, PyObject * value, void * closure) static
setter callback for the Center attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setCenter().
staticCallback_setRadius()
int SpherePy::staticCallback_setRadius (PyObject * self, PyObject * value, void * closure) static
setter callback for the Radius attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setRadius().
staticCallback_setVolume()
int SpherePy::staticCallback_setVolume (PyObject * self, PyObject * value, void * closure) static
setter callback for the Volume attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
Member Data Documentation
GetterSetter
PyGetSetDef SpherePy::GetterSetter static
Attribute structure of SpherePy.
Methods
PyMethodDef SpherePy::Methods static
Initial value:
= {
    {NULL, NULL, 0, NULL}
}
Methods structure of SpherePy.
Type
PyTypeObject SpherePy::Type static
Type structure of SpherePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/SpherePy.h
Sources/FreeCAD/src/Mod/Part/App/SpherePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/SpherePy.cpp