FreeCAD: MeshGui::ViewProviderMeshPy Class Reference
MeshGui::ViewProviderMeshPy Class Reference
The python export class for ViewProviderMesh.
#include <ViewProviderMeshPy.h>
Public Types
typedef ViewProviderMesh * PointerType
Public Types inherited from Gui::ViewProviderDocumentObjectPy
typedef ViewProviderDocumentObject * PointerType
Public Types inherited from Gui::ViewProviderPy
typedef ViewProvider * PointerType
Public Types inherited from App::ExtensionContainerPy
typedef ExtensionContainer * PointerType
Public Types inherited from App::PropertyContainerPy
typedef PropertyContainer * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
ViewProviderMeshPy (ViewProviderMesh *pcObject, PyTypeObject *T=&Type)
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ViewProviderMesh * getViewProviderMeshPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Gui::ViewProviderDocumentObjectPy
std::string representation (void) const
ViewProviderDocumentObjectPy (ViewProviderDocumentObject *pcObject, PyTypeObject *T=&Type)
PyObject * update (PyObject *args)
implementer for the update() method
Py::Object getObject (void) const
getter for the Object attribute
void setObject (Py::Object arg)
setter for the Object attribute
Py::Boolean getForceUpdate (void) const
getter for the ForceUpdate attribute
void setForceUpdate (Py::Boolean arg)
setter for the ForceUpdate attribute
Py::Object getDocument (void) const
getter for the Document attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ViewProviderDocumentObject * getViewProviderDocumentObjectPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Gui::ViewProviderPy
std::string representation (void) const
ViewProviderPy (ViewProvider *pcObject, PyTypeObject *T=&Type)
PyObject * addProperty (PyObject *args)
implementer for the addProperty() method
PyObject * removeProperty (PyObject *args)
implementer for the removeProperty() method
PyObject * supportedProperties (PyObject *args)
implementer for the supportedProperties() method
PyObject * show (PyObject *args)
implementer for the show() method
PyObject * hide (PyObject *args)
implementer for the hide() method
PyObject * isVisible (PyObject *args)
implementer for the isVisible() method
PyObject * canDragObject (PyObject *args)
implementer for the canDragObject() method
PyObject * dragObject (PyObject *args)
implementer for the dragObject() method
PyObject * canDropObject (PyObject *args)
implementer for the canDropObject() method
PyObject * dropObject (PyObject *args)
implementer for the dropObject() method
PyObject * canDragAndDropObject (PyObject *args)
implementer for the canDragAndDropObject() method
PyObject * replaceObject (PyObject *args)
implementer for the replaceObject() method
PyObject * doubleClicked (PyObject *args)
implementer for the doubleClicked() method
PyObject * addDisplayMode (PyObject *args)
implementer for the addDisplayMode() method
PyObject * listDisplayModes (PyObject *args)
implementer for the listDisplayModes() method
PyObject * toString (PyObject *args)
implementer for the toString() method
PyObject * setTransformation (PyObject *args)
implementer for the setTransformation() method
PyObject * claimChildren (PyObject *args)
implementer for the claimChildren() method
PyObject * partialRender (PyObject *args)
implementer for the partialRender() method
PyObject * getElementColors (PyObject *args)
implementer for the getElementColors() method
PyObject * setElementColors (PyObject *args)
implementer for the setElementColors() method
PyObject * getElementPicked (PyObject *args)
implementer for the getElementPicked() method
PyObject * getDetailPath (PyObject *args)
implementer for the getDetailPath() method
PyObject * signalChangeIcon (PyObject *args)
implementer for the signalChangeIcon() method
PyObject * getBoundingBox (PyObject *args)
implementer for the getBoundingBox() method
Py::Object getAnnotation (void) const
getter for the Annotation attribute
void setAnnotation (Py::Object arg)
setter for the Annotation attribute
Py::Object getIcon (void) const
getter for the Icon attribute
Py::Object getRootNode (void) const
getter for the RootNode attribute
void setRootNode (Py::Object arg)
setter for the RootNode attribute
Py::Object getSwitchNode (void) const
getter for the SwitchNode attribute
void setSwitchNode (Py::Object arg)
setter for the SwitchNode attribute
Py::Int getDefaultMode (void) const
getter for the DefaultMode attribute
void setDefaultMode (Py::Int arg)
setter for the DefaultMode attribute
Py::String getIV (void) const
getter for the IV attribute
Py::Boolean getCanRemoveChildrenFromRoot (void) const
getter for the CanRemoveChildrenFromRoot attribute
Py::Boolean getLinkVisibility (void) const
getter for the LinkVisibility attribute
void setLinkVisibility (Py::Boolean arg)
setter for the LinkVisibility attribute
Py::String getDropPrefix (void) const
getter for the DropPrefix attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ViewProvider * getViewProviderPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from App::ExtensionContainerPy
ExtensionContainerPy (ExtensionContainer *pcObject, PyTypeObject *T=&Type)
int finalization ()
int initialization ()
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ExtensionContainer * getExtensionContainerPtr (void) const
getter for the object handled by this class
PyObject * addExtension (PyObject *args)
implementer for the addExtension() method
PyObject * hasExtension (PyObject *args)
implementer for the hasExtension() method
Public Member Functions inherited from App::PropertyContainerPy
PropertyContainerPy (PropertyContainer *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getPropertyByName (PyObject *args)
implementer for the getPropertyByName() method
PyObject * getPropertyTouchList (PyObject *args)
implementer for the getPropertyTouchList() method
PyObject * getTypeOfProperty (PyObject *args)
implementer for the getTypeOfProperty() method
PyObject * getTypeIdOfProperty (PyObject *args)
implementer for the getTypeIdOfProperty() method
PyObject * setEditorMode (PyObject *args)
implementer for the setEditorMode() method
PyObject * getEditorMode (PyObject *args)
implementer for the getEditorMode() method
PyObject * getGroupOfProperty (PyObject *args)
implementer for the getGroupOfProperty() method
PyObject * setPropertyStatus (PyObject *args)
implementer for the setPropertyStatus() method
PyObject * getPropertyStatus (PyObject *args)
implementer for the getPropertyStatus() method
PyObject * getDocumentationOfProperty (PyObject *args)
implementer for the getDocumentationOfProperty() method
PyObject * dumpPropertyContent (PyObject *args, PyObject *kwd)
implementer for the dumpPropertyContent() method
PyObject * restorePropertyContent (PyObject *args)
implementer for the restorePropertyContent() method
Py::List getPropertiesList (void) const
getter for the PropertiesList attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
PropertyContainer * getPropertyContainerPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Gui::ViewProviderDocumentObjectPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_update (PyObject *self, PyObject *args)
callback for the update() method
static PyObject * staticCallback_getObject (PyObject *self, void *closure)
getter callback for the Object attribute
static int staticCallback_setObject (PyObject *self, PyObject *value, void *closure)
setter callback for the Object attribute
static PyObject * staticCallback_getForceUpdate (PyObject *self, void *closure)
getter callback for the ForceUpdate attribute
static int staticCallback_setForceUpdate (PyObject *self, PyObject *value, void *closure)
setter callback for the ForceUpdate attribute
static PyObject * staticCallback_getDocument (PyObject *self, void *closure)
getter callback for the Document attribute
static int staticCallback_setDocument (PyObject *self, PyObject *value, void *closure)
setter callback for the Document attribute
Static Public Member Functions inherited from Gui::ViewProviderPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_addProperty (PyObject *self, PyObject *args)
callback for the addProperty() method
static PyObject * staticCallback_removeProperty (PyObject *self, PyObject *args)
callback for the removeProperty() method
static PyObject * staticCallback_supportedProperties (PyObject *self, PyObject *args)
callback for the supportedProperties() method
static PyObject * staticCallback_show (PyObject *self, PyObject *args)
callback for the show() method
static PyObject * staticCallback_hide (PyObject *self, PyObject *args)
callback for the hide() method
static PyObject * staticCallback_isVisible (PyObject *self, PyObject *args)
callback for the isVisible() method
static PyObject * staticCallback_canDragObject (PyObject *self, PyObject *args)
callback for the canDragObject() method
static PyObject * staticCallback_dragObject (PyObject *self, PyObject *args)
callback for the dragObject() method
static PyObject * staticCallback_canDropObject (PyObject *self, PyObject *args)
callback for the canDropObject() method
static PyObject * staticCallback_dropObject (PyObject *self, PyObject *args)
callback for the dropObject() method
static PyObject * staticCallback_canDragAndDropObject (PyObject *self, PyObject *args)
callback for the canDragAndDropObject() method
static PyObject * staticCallback_replaceObject (PyObject *self, PyObject *args)
callback for the replaceObject() method
static PyObject * staticCallback_doubleClicked (PyObject *self, PyObject *args)
callback for the doubleClicked() method
static PyObject * staticCallback_addDisplayMode (PyObject *self, PyObject *args)
callback for the addDisplayMode() method
static PyObject * staticCallback_listDisplayModes (PyObject *self, PyObject *args)
callback for the listDisplayModes() method
static PyObject * staticCallback_toString (PyObject *self, PyObject *args)
callback for the toString() method
static PyObject * staticCallback_setTransformation (PyObject *self, PyObject *args)
callback for the setTransformation() method
static PyObject * staticCallback_claimChildren (PyObject *self, PyObject *args)
callback for the claimChildren() method
static PyObject * staticCallback_partialRender (PyObject *self, PyObject *args)
callback for the partialRender() method
static PyObject * staticCallback_getElementColors (PyObject *self, PyObject *args)
callback for the getElementColors() method
static PyObject * staticCallback_setElementColors (PyObject *self, PyObject *args)
callback for the setElementColors() method
static PyObject * staticCallback_getElementPicked (PyObject *self, PyObject *args)
callback for the getElementPicked() method
static PyObject * staticCallback_getDetailPath (PyObject *self, PyObject *args)
callback for the getDetailPath() method
static PyObject * staticCallback_signalChangeIcon (PyObject *self, PyObject *args)
callback for the signalChangeIcon() method
static PyObject * staticCallback_getBoundingBox (PyObject *self, PyObject *args)
callback for the getBoundingBox() method
static PyObject * staticCallback_getAnnotation (PyObject *self, void *closure)
getter callback for the Annotation attribute
static int staticCallback_setAnnotation (PyObject *self, PyObject *value, void *closure)
setter callback for the Annotation attribute
static PyObject * staticCallback_getIcon (PyObject *self, void *closure)
getter callback for the Icon attribute
static int staticCallback_setIcon (PyObject *self, PyObject *value, void *closure)
setter callback for the Icon attribute
static PyObject * staticCallback_getRootNode (PyObject *self, void *closure)
getter callback for the RootNode attribute
static int staticCallback_setRootNode (PyObject *self, PyObject *value, void *closure)
setter callback for the RootNode attribute
static PyObject * staticCallback_getSwitchNode (PyObject *self, void *closure)
getter callback for the SwitchNode attribute
static int staticCallback_setSwitchNode (PyObject *self, PyObject *value, void *closure)
setter callback for the SwitchNode attribute
static PyObject * staticCallback_getDefaultMode (PyObject *self, void *closure)
getter callback for the DefaultMode attribute
static int staticCallback_setDefaultMode (PyObject *self, PyObject *value, void *closure)
setter callback for the DefaultMode attribute
static PyObject * staticCallback_getIV (PyObject *self, void *closure)
getter callback for the IV attribute
static int staticCallback_setIV (PyObject *self, PyObject *value, void *closure)
setter callback for the IV attribute
static PyObject * staticCallback_getCanRemoveChildrenFromRoot (PyObject *self, void *closure)
getter callback for the CanRemoveChildrenFromRoot attribute
static int staticCallback_setCanRemoveChildrenFromRoot (PyObject *self, PyObject *value, void *closure)
setter callback for the CanRemoveChildrenFromRoot attribute
static PyObject * staticCallback_getLinkVisibility (PyObject *self, void *closure)
getter callback for the LinkVisibility attribute
static int staticCallback_setLinkVisibility (PyObject *self, PyObject *value, void *closure)
setter callback for the LinkVisibility attribute
static PyObject * staticCallback_getDropPrefix (PyObject *self, void *closure)
getter callback for the DropPrefix attribute
static int staticCallback_setDropPrefix (PyObject *self, PyObject *value, void *closure)
setter callback for the DropPrefix attribute
Static Public Member Functions inherited from App::ExtensionContainerPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_addExtension (PyObject *self, PyObject *args)
callback for the addExtension() method
static PyObject * staticCallback_hasExtension (PyObject *self, PyObject *args)
callback for the hasExtension() method
Static Public Member Functions inherited from App::PropertyContainerPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_getPropertyByName (PyObject *self, PyObject *args)
callback for the getPropertyByName() method
static PyObject * staticCallback_getPropertyTouchList (PyObject *self, PyObject *args)
callback for the getPropertyTouchList() method
static PyObject * staticCallback_getTypeOfProperty (PyObject *self, PyObject *args)
callback for the getTypeOfProperty() method
static PyObject * staticCallback_getTypeIdOfProperty (PyObject *self, PyObject *args)
callback for the getTypeIdOfProperty() method
static PyObject * staticCallback_setEditorMode (PyObject *self, PyObject *args)
callback for the setEditorMode() method
static PyObject * staticCallback_getEditorMode (PyObject *self, PyObject *args)
callback for the getEditorMode() method
static PyObject * staticCallback_getGroupOfProperty (PyObject *self, PyObject *args)
callback for the getGroupOfProperty() method
static PyObject * staticCallback_setPropertyStatus (PyObject *self, PyObject *args)
callback for the setPropertyStatus() method
static PyObject * staticCallback_getPropertyStatus (PyObject *self, PyObject *args)
callback for the getPropertyStatus() method
static PyObject * staticCallback_getDocumentationOfProperty (PyObject *self, PyObject *args)
callback for the getDocumentationOfProperty() method
static PyObject * staticCallback_dumpPropertyContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpPropertyContent() method
static PyObject * staticCallback_restorePropertyContent (PyObject *self, PyObject *args)
callback for the restorePropertyContent() method
static PyObject * staticCallback_getPropertiesList (PyObject *self, void *closure)
getter callback for the PropertiesList attribute
static int staticCallback_setPropertiesList (PyObject *self, PyObject *value, void *closure)
setter callback for the PropertiesList attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of ViewProviderMeshPy.
static PyMethodDef Methods []
Methods structure of ViewProviderMeshPy.
static PyTypeObject Type
Type structure of ViewProviderMeshPy.
Static Public Attributes inherited from Gui::ViewProviderDocumentObjectPy
static PyGetSetDef GetterSetter []
Attribute structure of ViewProviderDocumentObjectPy.
static PyMethodDef Methods []
Methods structure of ViewProviderDocumentObjectPy.
static PyTypeObject Type
Type structure of ViewProviderDocumentObjectPy.
Static Public Attributes inherited from Gui::ViewProviderPy
static PyGetSetDef GetterSetter []
Attribute structure of ViewProviderPy.
static PyMethodDef Methods []
Methods structure of ViewProviderPy.
static PyTypeObject Type
Type structure of ViewProviderPy.
Static Public Attributes inherited from App::ExtensionContainerPy
static PyGetSetDef GetterSetter []
Attribute structure of ExtensionContainerPy.
static PyMethodDef Methods []
Methods structure of ExtensionContainerPy.
static PyTypeObject Type
Type structure of ExtensionContainerPy.
Static Public Attributes inherited from App::PropertyContainerPy
static PyGetSetDef GetterSetter []
Attribute structure of PropertyContainerPy.
static PyMethodDef Methods []
Methods structure of PropertyContainerPy.
static PyTypeObject Type
Type structure of PropertyContainerPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~ViewProviderMeshPy ()
Protected Member Functions inherited from Gui::ViewProviderDocumentObjectPy
~ViewProviderDocumentObjectPy ()
Protected Member Functions inherited from Gui::ViewProviderPy
~ViewProviderPy ()
Protected Member Functions inherited from App::ExtensionContainerPy
~ExtensionContainerPy ()
Protected Member Functions inherited from App::PropertyContainerPy
~PropertyContainerPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * setSelection (PyObject *args)
implementer for the setSelection() method
PyObject * addSelection (PyObject *args)
implementer for the addSelection() method
PyObject * removeSelection (PyObject *args)
implementer for the removeSelection() method
PyObject * invertSelection (PyObject *args)
implementer for the invertSelection() method
PyObject * clearSelection (PyObject *args)
implementer for the clearSelection() method
PyObject * highlightSegments (PyObject *args)
implementer for the highlightSegments() method
static PyObject * staticCallback_setSelection (PyObject *self, PyObject *args)
callback for the setSelection() method
static PyObject * staticCallback_addSelection (PyObject *self, PyObject *args)
callback for the addSelection() method
static PyObject * staticCallback_removeSelection (PyObject *self, PyObject *args)
callback for the removeSelection() method
static PyObject * staticCallback_invertSelection (PyObject *self, PyObject *args)
callback for the invertSelection() method
static PyObject * staticCallback_clearSelection (PyObject *self, PyObject *args)
callback for the clearSelection() method
static PyObject * staticCallback_highlightSegments (PyObject *self, PyObject *args)
callback for the highlightSegments() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for ViewProviderMesh.
Member Typedef Documentation
PointerType
typedef ViewProviderMesh* MeshGui::ViewProviderMeshPy::PointerType
Constructor & Destructor Documentation
~ViewProviderMeshPy()
ViewProviderMeshPy::~ViewProviderMeshPy () protected
ViewProviderMeshPy()
ViewProviderMeshPy::ViewProviderMeshPy (ViewProviderMesh * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
addSelection()
PyObject * ViewProviderMeshPy::addSelection (PyObject * args)
implementer for the addSelection() method
References MeshGui::ViewProviderMesh::addSelection(), and getViewProviderMeshPtr().
Referenced by staticCallback_addSelection().
clearSelection()
PyObject * ViewProviderMeshPy::clearSelection (PyObject * args)
implementer for the clearSelection() method
References MeshGui::ViewProviderMesh::clearSelection(), and getViewProviderMeshPtr().
Referenced by staticCallback_clearSelection().
getCustomAttributes()
PyObject * ViewProviderMeshPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
GetType()
virtual PyTypeObject* MeshGui::ViewProviderMeshPy::GetType (void) virtual
Reimplemented from Gui::ViewProviderDocumentObjectPy.
getViewProviderMeshPtr()
ViewProviderMesh * ViewProviderMeshPy::getViewProviderMeshPtr (void) const
getter for the object handled by this class
Referenced by addSelection(), clearSelection(), highlightSegments(), invertSelection(), removeSelection(), and setSelection().
highlightSegments()
PyObject * ViewProviderMeshPy::highlightSegments (PyObject * args)
implementer for the highlightSegments() method
References getViewProviderMeshPtr(), and MeshGui::ViewProviderMesh::highlightSegments().
Referenced by staticCallback_highlightSegments().
invertSelection()
PyObject * ViewProviderMeshPy::invertSelection (PyObject * args)
implementer for the invertSelection() method
References getViewProviderMeshPtr(), and MeshGui::ViewProviderMesh::invertSelection().
Referenced by staticCallback_invertSelection().
PyInit()
int ViewProviderMeshPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Gui::ViewProviderDocumentObjectPy.
PyMake()
PyObject * ViewProviderMeshPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
removeSelection()
PyObject * ViewProviderMeshPy::removeSelection (PyObject * args)
implementer for the removeSelection() method
References getViewProviderMeshPtr(), and MeshGui::ViewProviderMesh::removeSelection().
Referenced by staticCallback_removeSelection().
representation()
std::string ViewProviderMeshPy::representation (void) const
References Gui::ViewProviderDocumentObjectPy::getViewProviderDocumentObjectPtr().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int ViewProviderMeshPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setSelection()
PyObject * ViewProviderMeshPy::setSelection (PyObject * args)
implementer for the setSelection() method
References getViewProviderMeshPtr(), and MeshGui::ViewProviderMesh::setSelection().
Referenced by staticCallback_setSelection().
staticCallback_addSelection()
PyObject * ViewProviderMeshPy::staticCallback_addSelection (PyObject * self, PyObject * args) static
callback for the addSelection() method
References addSelection(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_clearSelection()
PyObject * ViewProviderMeshPy::staticCallback_clearSelection (PyObject * self, PyObject * args) static
callback for the clearSelection() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, clearSelection(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_highlightSegments()
PyObject * ViewProviderMeshPy::staticCallback_highlightSegments (PyObject * self, PyObject * args) static
callback for the highlightSegments() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, highlightSegments(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_invertSelection()
PyObject * ViewProviderMeshPy::staticCallback_invertSelection (PyObject * self, PyObject * args) static
callback for the invertSelection() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, invertSelection(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_removeSelection()
PyObject * ViewProviderMeshPy::staticCallback_removeSelection (PyObject * self, PyObject * args) static
callback for the removeSelection() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeSelection(), and Base::PyObjectBase::startNotify().
staticCallback_setSelection()
PyObject * ViewProviderMeshPy::staticCallback_setSelection (PyObject * self, PyObject * args) static
callback for the setSelection() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setSelection(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef ViewProviderMeshPy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of ViewProviderMeshPy.
Methods
PyMethodDef ViewProviderMeshPy::Methods static
Methods structure of ViewProviderMeshPy.
Type
PyTypeObject ViewProviderMeshPy::Type static
Type structure of ViewProviderMeshPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Mesh/Gui/ViewProviderMeshPy.h
Sources/FreeCAD/src/Mod/Mesh/Gui/ViewProviderMeshPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Mesh/Gui/ViewProviderMeshPy.cpp