FreeCAD: PathScripts.post.grbl_post Namespace Reference
PathScripts.post.grbl_post Namespace Reference
Functions
def drill_translate (outstring, cmd, params)
def dump (obj)
def export (objectslist, filename, argstring)
def format_outstring (strTable)
def linenumber ()
def parse (pathobj)
def processArguments (argstring)
Variables
action
string COMMAND_SPACE = " "
int CURRENT_X = 0
int CURRENT_Y = 0
int CURRENT_Z = 0
default
string DRILL_RETRACT_MODE = 'G98'
help
int
int LINEINCR = 10
int LINENR = 100
bool MODAL = False
list MOTION_COMMANDS = ['G0', 'G00', 'G1', 'G01', 'G2', 'G02', 'G3', 'G03']
string MOTION_MODE = 'G90'
bool OUTPUT_BCNC = False
bool OUTPUT_COMMENTS = True
bool OUTPUT_HEADER = True
bool OUTPUT_LINE_NUMBERS = False
bool OUTPUT_TOOL_CHANGE = False
parser = argparse.ArgumentParser(prog='grbl', add_help=False)
string POST_OPERATION = ''''''
string POSTAMBLE
string PRE_OPERATION = ''''''
string PREAMBLE
int PRECISION = 3
pythonopen = open
list RAPID_MOVES = ['G0', 'G00']
RETURN_TO = None
bool SHOW_EDITOR = True
int SPINDLE_WAIT = 0
list SUPPRESS_COMMANDS = []
string TOOL_CHANGE = ''''''
string TOOLTIP
TOOLTIP_ARGS = parser.format_help()
bool TRANSLATE_DRILL_CYCLES = False
type
string UNIT_FORMAT = 'mm'
string UNIT_SPEED_FORMAT = 'mm/min'
string UNITS = 'G21'
Function Documentation
drill_translate()
def PathScripts.post.grbl_post.drill_translate (outstring, cmd, params)
References PathScripts.post.grbl_post.format_outstring(), and PathScripts.post.grbl_post.linenumber().
Referenced by PathScripts.post.grbl_post.parse().
dump()
def PathScripts.post.grbl_post.dump (obj)
export()
def PathScripts.post.grbl_post.export (objectslist, filename, argstring)
References PathScripts.post.grbl_post.linenumber(), PathScripts.post.grbl_post.parse(), PathScripts.post.grbl_post.processArguments(), and PathScripts.post.grbl_post.pythonopen.
format_outstring()
def PathScripts.post.grbl_post.format_outstring (strTable)
Referenced by PathScripts.post.grbl_post.drill_translate(), and PathScripts.post.grbl_post.parse().
linenumber()
def PathScripts.post.grbl_post.linenumber ()
Referenced by PathScripts.post.grbl_post.drill_translate(), PathScripts.post.grbl_post.export(), and PathScripts.post.grbl_post.parse().
parse()
def PathScripts.post.grbl_post.parse (pathobj)
References PathScripts.post.grbl_post.drill_translate(), PathScripts.post.grbl_post.format_outstring(), and PathScripts.post.grbl_post.linenumber().
Referenced by PathScripts.post.grbl_post.export().
processArguments()
def PathScripts.post.grbl_post.processArguments (argstring)
References PathScripts.post.grbl_post.int.
Referenced by PathScripts.post.grbl_post.export().
Variable Documentation
action
PathScripts.post.grbl_post.action
COMMAND_SPACE
string PathScripts.post.grbl_post.COMMAND_SPACE = " "
CURRENT_X
int PathScripts.post.grbl_post.CURRENT_X = 0
CURRENT_Y
int PathScripts.post.grbl_post.CURRENT_Y = 0
CURRENT_Z
int PathScripts.post.grbl_post.CURRENT_Z = 0
default
PathScripts.post.grbl_post.default
DRILL_RETRACT_MODE
string PathScripts.post.grbl_post.DRILL_RETRACT_MODE = 'G98'
help
PathScripts.post.grbl_post.help
int
PathScripts.post.grbl_post.int
Referenced by PathScripts.post.grbl_post.processArguments().
LINEINCR
int PathScripts.post.grbl_post.LINEINCR = 10
LINENR
int PathScripts.post.grbl_post.LINENR = 100
MODAL
bool PathScripts.post.grbl_post.MODAL = False
MOTION_COMMANDS
list PathScripts.post.grbl_post.MOTION_COMMANDS = ['G0', 'G00', 'G1', 'G01', 'G2', 'G02', 'G3', 'G03']
MOTION_MODE
string PathScripts.post.grbl_post.MOTION_MODE = 'G90'
OUTPUT_BCNC
bool PathScripts.post.grbl_post.OUTPUT_BCNC = False
OUTPUT_COMMENTS
bool PathScripts.post.grbl_post.OUTPUT_COMMENTS = True
OUTPUT_HEADER
bool PathScripts.post.grbl_post.OUTPUT_HEADER = True
OUTPUT_LINE_NUMBERS
bool PathScripts.post.grbl_post.OUTPUT_LINE_NUMBERS = False
OUTPUT_TOOL_CHANGE
bool PathScripts.post.grbl_post.OUTPUT_TOOL_CHANGE = False
parser
PathScripts.post.grbl_post.parser = argparse.ArgumentParser(prog='grbl', add_help=False)
POST_OPERATION
string PathScripts.post.grbl_post.POST_OPERATION = ''''''
POSTAMBLE
string PathScripts.post.grbl_post.POSTAMBLE
Initial value:
 =  '''M5
 G17 G90
 M2
 '''
PRE_OPERATION
string PathScripts.post.grbl_post.PRE_OPERATION = ''''''
PREAMBLE
string PathScripts.post.grbl_post.PREAMBLE
Initial value:
 =  '''G17 G90
 '''
PRECISION
int PathScripts.post.grbl_post.PRECISION = 3
pythonopen
PathScripts.post.grbl_post.pythonopen = open
Referenced by PathScripts.post.grbl_post.export().
RAPID_MOVES
list PathScripts.post.grbl_post.RAPID_MOVES = ['G0', 'G00']
RETURN_TO
PathScripts.post.grbl_post.RETURN_TO = None
SHOW_EDITOR
bool PathScripts.post.grbl_post.SHOW_EDITOR = True
SPINDLE_WAIT
int PathScripts.post.grbl_post.SPINDLE_WAIT = 0
SUPPRESS_COMMANDS
list PathScripts.post.grbl_post.SUPPRESS_COMMANDS = []
TOOL_CHANGE
string PathScripts.post.grbl_post.TOOL_CHANGE = ''''''
TOOLTIP
string PathScripts.post.grbl_post.TOOLTIP
Initial value:
 =  '''
 Generate g-code from a Path that is compatible with the grbl controller.
 import grbl_post
 grbl_post.export(object, "/path/to/file.ncc")
 '''
TOOLTIP_ARGS
PathScripts.post.grbl_post.TOOLTIP_ARGS = parser.format_help()
TRANSLATE_DRILL_CYCLES
bool PathScripts.post.grbl_post.TRANSLATE_DRILL_CYCLES = False
type
PathScripts.post.grbl_post.type
UNIT_FORMAT
string PathScripts.post.grbl_post.UNIT_FORMAT = 'mm'
UNIT_SPEED_FORMAT
string PathScripts.post.grbl_post.UNIT_SPEED_FORMAT = 'mm/min'
UNITS
string PathScripts.post.grbl_post.UNITS = 'G21'