FreeCAD: ReenGui::PoissonWidget Class Reference
ReenGui::PoissonWidget Class Reference
#include <Poisson.h>
Classes
class Private
Public Member Functions
bool accept ()
PoissonWidget (const App::DocumentObjectT &, QWidget *parent=nullptr)
~PoissonWidget ()
Constructor & Destructor Documentation
PoissonWidget()
PoissonWidget::PoissonWidget (const App::DocumentObjectT & obj, QWidget * parent = nullptr)
References ReenGui::PoissonWidget::Private::obj, ReenGui::Ui_PoissonWidget::setupUi(), and ReenGui::PoissonWidget::Private::ui.
~PoissonWidget()
PoissonWidget::~PoissonWidget ()
Member Function Documentation
accept()
bool PoissonWidget::accept (void)
References Gui::Command::abortCommand(), Gui::Command::addModule(), Gui::Command::App, Gui::Command::commitCommand(), Gui::Command::Doc, App::DocumentObjectT::getDocumentPython(), App::DocumentObjectT::getObjectPython(), ReenGui::PoissonWidget::Private::obj, ReenGui::Ui_PoissonWidget::octreeDepth, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, ReenGui::Ui_PoissonWidget::samplesPerNode, ReenGui::Ui_PoissonWidget::solverDivide, ReenGui::PoissonWidget::Private::ui, and Gui::Command::updateActive().
Referenced by ReenGui::TaskPoisson::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/ReverseEngineering/Gui/Poisson.h
FreeCAD/src/Mod/ReverseEngineering/Gui/Poisson.cpp