FreeCAD: exportCSG Namespace Reference
exportCSG Namespace Reference
Functions
def center (b)
def check_multmatrix (csg, ob, x, y, z)
def export (exportList, filename)
def mesh2polyhedron (mesh)
def process_object (csg, ob)
def shape2polyhedron (shape)
def vector2d (v)
def vertexs2polygon (vertex)
Variables
conv = params.GetInt('exportConvexity', 10)
string convexity = 'convexity = %d' % conv
fa = params.GetFloat('exportFa', 12.0)
string fafs = '$fa = %f, $fs = %f' % (fa, fs)
fs = params.GetFloat('exportFs', 2.0)
bool gui = True
params = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Mod/OpenSCAD")
pythonopen = open
Function Documentation
center()
def exportCSG.center (b)
Referenced by process_object().
check_multmatrix()
def exportCSG.check_multmatrix (csg, ob, x, y, z)
Referenced by process_object().
export()
def exportCSG.export (exportList, filename)
References process_object(), and pythonopen.
mesh2polyhedron()
def exportCSG.mesh2polyhedron (mesh)
Referenced by shape2polyhedron().
process_object()
def exportCSG.process_object (csg, ob)
References center(), check_multmatrix(), process_object(), shape2polyhedron(), and vertexs2polygon().
Referenced by export(), and process_object().
shape2polyhedron()
def exportCSG.shape2polyhedron (shape)
References mesh2polyhedron().
Referenced by process_object().
vector2d()
def exportCSG.vector2d (v)
Referenced by vertexs2polygon().
vertexs2polygon()
def exportCSG.vertexs2polygon (vertex)
References vector2d().
Referenced by process_object().
Variable Documentation
conv
exportCSG.conv = params.GetInt('exportConvexity', 10)
convexity
string exportCSG.convexity = 'convexity = %d' % conv
fa
exportCSG.fa = params.GetFloat('exportFa', 12.0)
fafs
string exportCSG.fafs = '$fa = %f, $fs = %f' % (fa, fs)
fs
exportCSG.fs = params.GetFloat('exportFs', 2.0)
gui
bool exportCSG.gui = True
params
exportCSG.params = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Mod/OpenSCAD")
pythonopen
exportCSG.pythonopen = open
Referenced by export().