FreeCAD: draftguitools.gui_base_original.Creator Class Reference
draftguitools.gui_base_original.Creator Class Reference
Workbenches » Python workbenches » Draft » draftguitools
Public Member Functions
def Activated (self, name="None", noplanesetup=False)
Public Member Functions inherited from draftguitools.gui_base_original.DraftTool
def Activated (self, name="None", noplanesetup=False, is_subtool=False)
def commit (self, name, func)
def finish (self, close=False)
def getStrings (self, addrot=None)
def IsActive (self)
Public Attributes
support
Public Attributes inherited from draftguitools.gui_base_original.DraftTool
call
commitList
constrain
doc
extendedCopy
featureName
node
obj
planetrack
point
pos
support
ui
view
Detailed Description
A generic Creator tool, used by creation tools such as line or arc.
It runs the Activated method from the parent class.
If `noplanesetup` is `False`, it sets the appropriate `support` attribute
and sets the working plane with `gui_tool_utils.get_support`.
It inherits `DraftTool`, which sets up the majority of the behavior
of this class.
Member Function Documentation
Activated()
def draftguitools.gui_base_original.Creator.Activated (self, name = "None", noplanesetup = False)
Execute when the command is called.
Parameters
----------
name: str, optional
    It defaults to `'None'`.
    It is the `featureName` of the object, to know what is being run.
noplanesetup: bool, optional
    It defaults to `False`.
    If it is `False` it will set up the working plane
    by running `App.DraftWorkingPlane.setup()`.
Reimplemented from draftguitools.gui_base_original.DraftTool.
Reimplemented in draftguitools.gui_arcs.Arc, draftguitools.gui_beziers.BezCurve, draftguitools.gui_beziers.CubicBezCurve, draftguitools.gui_dimensions.Dimension, draftguitools.gui_ellipses.Ellipse, draftguitools.gui_facebinders.Facebinder, draftguitools.gui_labels.Label, draftguitools.gui_lines.Wire, draftguitools.gui_points.Point, draftguitools.gui_polygons.Polygon, draftguitools.gui_rectangles.Rectangle, draftguitools.gui_shapestrings.ShapeString, draftguitools.gui_splines.BSpline, draftguitools.gui_texts.Text, draftguitools.gui_fillets.Fillet, and draftguitools.gui_lines.Line.
References draftguitools.gui_base_original.Creator.Activated().
Referenced by ArchStructure.CommandStructuralSystem.Activated(), draftguitools.gui_base_original.Creator.Activated(), draftguitools.gui_arcs.Arc.finish(), draftguitools.gui_beziers.BezCurve.finish(), draftguitools.gui_beziers.CubicBezCurve.finish(), draftguitools.gui_ellipses.Ellipse.finish(), draftguitools.gui_lines.Line.finish(), draftguitools.gui_mirror.Mirror.finish(), draftguitools.gui_move.Move.finish(), draftguitools.gui_polygons.Polygon.finish(), draftguitools.gui_rectangles.Rectangle.finish(), draftguitools.gui_rotate.Rotate.finish(), draftguitools.gui_splines.BSpline.finish(), draftguitools.gui_texts.Text.finish(), draftguitools.gui_points.Point.finish(), draftguitools.gui_shapestrings.ShapeString.finish(), draftguitools.gui_arcs.Arc_3Points.getPoint(), and ArchPanel.CommandPanel.getPoint().
Member Data Documentation
support
draftguitools.gui_base_original.Creator.support
Referenced by draftguitools.gui_beziers.BezCurve.action(), draftguitools.gui_ellipses.Ellipse.action(), draftguitools.gui_lines.Line.action(), draftguitools.gui_rectangles.Rectangle.action(), draftguitools.gui_splines.BSpline.action(), and draftguitools.gui_base_original.DraftTool.getStrings().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Draft/draftguitools/gui_base_original.py