FreeCAD: femexamples.thermomech_bimetall Namespace Reference
femexamples.thermomech_bimetall Namespace Reference
Functions
def get_information ()
def init_doc (doc=None)
def setup (doc=None, solvertype="ccxtools")
Variables
string mesh_name = "Mesh"
Function Documentation
get_information()
def femexamples.thermomech_bimetall.get_information ()
init_doc()
def femexamples.thermomech_bimetall.init_doc (doc = None)
Referenced by femexamples.thermomech_bimetall.setup().
setup()
def femexamples.thermomech_bimetall.setup (doc = None, solvertype = "ccxtools")
References femexamples.thermomech_bimetall.init_doc(), ObjectsFem.makeAnalysis(), ObjectsFem.makeConstraintFixed(), ObjectsFem.makeConstraintInitialTemperature(), ObjectsFem.makeConstraintTemperature(), ObjectsFem.makeEquationElasticity(), ObjectsFem.makeEquationHeat(), ObjectsFem.makeMaterialSolid(), ObjectsFem.makeMeshGmsh(), ObjectsFem.makeSolverCalculix(), ObjectsFem.makeSolverCalculixCcxTools(), and ObjectsFem.makeSolverElmer().
Variable Documentation
mesh_name
string femexamples.thermomech_bimetall.mesh_name = "Mesh"