FreeCAD: Part::GeometryDefaultExtension< T > Class Template Reference
Part::GeometryDefaultExtension< T > Class Template Reference
#include <GeometryDefaultExtension.h>
Public Member Functions
virtual std::unique_ptr< Part::GeometryExtension > copy (void) const override
void * create ()
void * create ()
void * create ()
void * create ()
GeometryDefaultExtension ()
GeometryDefaultExtension ()
GeometryDefaultExtension ()
GeometryDefaultExtension (const T &val, std::string name=std::string())
PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
const T & getValue () const
void setValue (const T &val)
virtual ~GeometryDefaultExtension () override=default
Public Member Functions inherited from Part::GeometryPersistenceExtension
void Restore (Base::XMLReader &)
void Save (Base::Writer &) const
virtual ~GeometryPersistenceExtension ()=default
Public Member Functions inherited from Part::GeometryExtension
virtual std::unique_ptr< GeometryExtension > copy (void) const =0
PyObject * copyPyObject () const
const std::string & getName () const
virtual PyObject * getPyObject (void)=0
This method returns the Python wrapper for a C++ object.
virtual void notifyAttachment (Part::Geometry *)
void setName (const std::string &str)
virtual ~GeometryExtension ()=default
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Member Functions
virtual void copyAttributes (Part::GeometryExtension *cpy) const override
void restoreAttributes (Base::XMLReader &reader)
void restoreAttributes (Base::XMLReader &reader)
void restoreAttributes (Base::XMLReader &reader)
virtual void restoreAttributes (Base::XMLReader &reader) override
virtual void saveAttributes (Base::Writer &writer) const override
virtual void restoreAttributes (Base::XMLReader &)
virtual void saveAttributes (Base::Writer &writer) const
Protected Member Functions inherited from Part::GeometryExtension
virtual void copyAttributes (Part::GeometryExtension *cpy) const
GeometryExtension ()
GeometryExtension (const GeometryExtension &obj)=default
GeometryExtension & operator= (const GeometryExtension &obj)=default
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
GeometryDefaultExtension() [1/4]
template<typename T > Part::GeometryDefaultExtension< T >::GeometryDefaultExtension
GeometryDefaultExtension() [2/4]
template<typename T > GeometryDefaultExtension::GeometryDefaultExtension (const T & val, std::string name = std::string())
References Part::GeometryExtension::setName().
~GeometryDefaultExtension()
template<typename T > virtual Part::GeometryDefaultExtension< T >::~GeometryDefaultExtension () override virtual default
GeometryDefaultExtension() [3/4]
Part::GeometryDefaultExtension< long >::GeometryDefaultExtension ()
GeometryDefaultExtension() [4/4]
Part::GeometryDefaultExtension< double >::GeometryDefaultExtension ()
Member Function Documentation
copy()
template<typename T > std::unique_ptr< Part::GeometryExtension > GeometryDefaultExtension::copy (void) const override virtual
Implements Part::GeometryExtension.
References draftfunctions.move::move().
copyAttributes()
template<typename T > void GeometryDefaultExtension::copyAttributes (Part::GeometryExtension * cpy) const override protected virtual
Reimplemented from Part::GeometryExtension.
References Part::GeometryExtension::copyAttributes().
create() [1/4]
void * Part::GeometryDefaultExtension< long >::create ()
Referenced by draftguitools.gui_labels.Label::action().
create() [2/4]
void * Part::GeometryDefaultExtension< std::string >::create ()
Referenced by draftguitools.gui_labels.Label::action().
create() [3/4]
void * Part::GeometryDefaultExtension< bool >::create ()
Referenced by draftguitools.gui_labels.Label::action().
create() [4/4]
void * Part::GeometryDefaultExtension< double >::create ()
Referenced by draftguitools.gui_labels.Label::action().
getPyObject() [1/5]
PyObject * Part::GeometryDefaultExtension< long >::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
getPyObject() [2/5]
PyObject * Part::GeometryDefaultExtension< std::string >::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
getPyObject() [3/5]
PyObject * Part::GeometryDefaultExtension< bool >::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
getPyObject() [4/5]
PyObject * Part::GeometryDefaultExtension< double >::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
getPyObject() [5/5]
template<typename T > PyObject * GeometryDefaultExtension::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
getValue()
template<typename T > const T & Part::GeometryDefaultExtension< T >::getValue (void) const
restoreAttributes() [1/4]
void Part::GeometryDefaultExtension< long >::restoreAttributes (Base::XMLReader & reader) protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
References Base::XMLReader::getAttributeAsInteger(), and Part::GeometryPersistenceExtension::restoreAttributes().
restoreAttributes() [2/4]
void Part::GeometryDefaultExtension< bool >::restoreAttributes (Base::XMLReader & reader) protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
References Base::XMLReader::getAttributeAsInteger(), and Part::GeometryPersistenceExtension::restoreAttributes().
restoreAttributes() [3/4]
void Part::GeometryDefaultExtension< double >::restoreAttributes (Base::XMLReader & reader) protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
References Base::XMLReader::getAttributeAsFloat(), and Part::GeometryPersistenceExtension::restoreAttributes().
restoreAttributes() [4/4]
template<typename T > void GeometryDefaultExtension::restoreAttributes (Base::XMLReader & reader) override protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
References Base::XMLReader::getAttribute(), and Part::GeometryPersistenceExtension::restoreAttributes().
saveAttributes()
template<typename T > void GeometryDefaultExtension::saveAttributes (Base::Writer & writer) const override protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
References Part::GeometryPersistenceExtension::saveAttributes(), and Base::Writer::Stream().
setValue()
template<typename T > void Part::GeometryDefaultExtension< T >::setValue (const T & val)
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/App/GeometryDefaultExtension.h
FreeCAD/src/Mod/Part/App/GeometryDefaultExtension.cpp