FreeCAD: MeshCore::MeshEvalNeighbourhood Class Reference
MeshCore::MeshEvalNeighbourhood Class Reference
The MeshEvalNeighbourhood class checks if the neighbourhood among the facets is set correctly.
#include <Evaluation.h>
Public Member Functions
bool Evaluate ()
Evaluates the mesh kernel with respect to certain criteria.
std::vector< FacetIndex > GetIndices () const
MeshEvalNeighbourhood (const MeshKernel &rclB)
~MeshEvalNeighbourhood ()
Public Member Functions inherited from MeshCore::MeshEvaluation
virtual bool Evaluate ()=0
Evaluates the mesh kernel with respect to certain criteria.
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()
Detailed Description
The MeshEvalNeighbourhood class checks if the neighbourhood among the facets is set correctly.
Author
Werner Mayer
Constructor & Destructor Documentation
MeshEvalNeighbourhood()
MeshCore::MeshEvalNeighbourhood::MeshEvalNeighbourhood (const MeshKernel & rclB)
~MeshEvalNeighbourhood()
MeshCore::MeshEvalNeighbourhood::~MeshEvalNeighbourhood ()
Member Function Documentation
Evaluate()
bool MeshEvalNeighbourhood::Evaluate () virtual
Evaluates the mesh kernel with respect to certain criteria.
Must be reimplemented by every subclass. This pure virtual function returns false if the mesh kernel is invalid according to this criterion and true if the mesh kernel is correct.
Implements MeshCore::MeshEvaluation.
References MeshCore::Edge_Index::f, MeshCore::FACET_INDEX_MAX, Base::SequencerLauncher::next(), MeshCore::Edge_Index::p0, MeshCore::Edge_Index::p1, MeshCore::POINT_INDEX_MAX, and MeshCore::MeshFacet::Side().
Referenced by Mesh::MeshObject::hasInvalidNeighbourhood(), Mesh::MeshObject::load(), MeshGui::DlgEvaluateMeshImp::on_analyzeIndicesButton_clicked(), and MeshGui::DlgEvaluateMeshImp::on_repairAllTogether_clicked().
GetIndices()
std::vector< FacetIndex > MeshEvalNeighbourhood::GetIndices () const
References MeshCore::Edge_Index::f, MeshCore::FACET_INDEX_MAX, Base::SequencerLauncher::next(), MeshCore::Edge_Index::p0, MeshCore::Edge_Index::p1, MeshCore::POINT_INDEX_MAX, and MeshCore::MeshFacet::Side().
Referenced by MeshGui::DlgEvaluateMeshImp::on_analyzeIndicesButton_clicked().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/Core/Evaluation.h
FreeCAD/src/Mod/Mesh/App/Core/Evaluation.cpp