FreeCAD: SketcherGui::TaskSketcherGeneral Class Reference
SketcherGui::TaskSketcherGeneral Class Reference
#include <TaskSketcherGeneral.h>
Public Slots
void onRenderOrderChanged ()
void onSetGridSize (double val)
void onToggleAutoconstraints (bool on)
void onToggleAvoidRedundant (bool)
void onToggleGridSnap (bool on)
void onToggleGridView (bool on)
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Public Member Functions
void OnChange (Gui::SelectionSingleton::SubjectType &rCaller, Gui::SelectionSingleton::MessageType Reason)
Observer message from the Selection.
TaskSketcherGeneral (ViewProviderSketch *sketchView)
~TaskSketcherGeneral ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Additional Inherited Members
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskSketcherGeneral()
TaskSketcherGeneral::TaskSketcherGeneral (ViewProviderSketch * sketchView)
References Base::Subject< _MessageType >::Attach(), SketcherGui::ViewProviderSketch::Autoconstraints, SketcherGui::ViewProviderSketch::AvoidRedundant, draftgeoutils.faces::bind(), SketcherGui::SketcherGeneralWidget::checkAutoconstraints(), SketcherGui::SketcherGeneralWidget::checkAvoidRedundant(), SketcherGui::SketcherGeneralWidget::checkGridSnap(), SketcherGui::SketcherGeneralWidget::checkGridView(), draftgeoutils.intersections::connect(), SketcherGui::SketcherGeneralWidget::enableAvoidRedundant(), SketcherGui::SketcherGeneralWidget::enableGridSettings(), App::PropertyBool::getValue(), App::PropertyQuantity::getValue(), PartGui::ViewProvider2DObjectGrid::GridSize, PartGui::ViewProvider2DObjectGrid::GridSnap, QSint::ActionGroup::groupLayout(), Gui::Application::Instance, SketcherGui::SketcherGeneralWidget::loadSettings(), onRenderOrderChanged(), onSetGridSize(), onToggleAutoconstraints(), onToggleAvoidRedundant(), onToggleGridSnap(), onToggleGridView(), Gui::Selection(), SketcherGui::SketcherGeneralWidget::setGridSize(), and PartGui::ViewProvider2DObjectGrid::ShowGrid.
~TaskSketcherGeneral()
TaskSketcherGeneral::~TaskSketcherGeneral ()
References Base::Subject< _MessageType >::Detach(), and Gui::Selection().
Member Function Documentation
OnChange()
void SketcherGui::TaskSketcherGeneral::OnChange (Gui::SelectionSingleton::SubjectType & rCaller, Gui::SelectionSingleton::MessageType Reason)
Observer message from the Selection.
onRenderOrderChanged
DOXERR void TaskSketcherGeneral::onRenderOrderChanged () slot
References SketcherGui::SketcherGeneralWidget::saveOrderingOrder(), and SketcherGui::ViewProviderSketch::updateColor().
Referenced by TaskSketcherGeneral().
onSetGridSize
void TaskSketcherGeneral::onSetGridSize (double val) slot
References PartGui::ViewProvider2DObjectGrid::GridSize, and App::PropertyQuantity::setValue().
Referenced by TaskSketcherGeneral().
onToggleAutoconstraints
void TaskSketcherGeneral::onToggleAutoconstraints (bool on) slot
References SketcherGui::ViewProviderSketch::Autoconstraints, SketcherGui::SketcherGeneralWidget::enableAvoidRedundant(), and App::PropertyBool::setValue().
Referenced by TaskSketcherGeneral().
onToggleAvoidRedundant
void TaskSketcherGeneral::onToggleAvoidRedundant (bool on) slot
References SketcherGui::ViewProviderSketch::AvoidRedundant, and App::PropertyBool::setValue().
Referenced by TaskSketcherGeneral().
onToggleGridSnap
void TaskSketcherGeneral::onToggleGridSnap (bool on) slot
References PartGui::ViewProvider2DObjectGrid::GridSnap, and App::PropertyBool::setValue().
Referenced by TaskSketcherGeneral().
onToggleGridView
void TaskSketcherGeneral::onToggleGridView (bool on) slot
References SketcherGui::SketcherGeneralWidget::enableGridSettings(), App::PropertyBool::setValue(), and PartGui::ViewProvider2DObjectGrid::ShowGrid.
Referenced by TaskSketcherGeneral().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/Gui/TaskSketcherGeneral.h
FreeCAD/src/Mod/Sketcher/Gui/TaskSketcherGeneral.cpp