FreeCAD: TestGui::UnitTestDialog Class Reference
TestGui::UnitTestDialog Class Reference
#include <UnitTestImp.h>
Public Slots
void on_aboutButton_clicked ()
Shows the about dialog.
void on_helpButton_clicked ()
Shows the help dialog.
void on_startButton_clicked ()
Runs the unit tests.
void on_treeViewFailure_itemDoubleClicked (QTreeWidgetItem *item, int column)
Opens a dialog to display a detailed description about the error.
Public Member Functions
void addUnitTest (const QString &unit)
Adds a unit test.
void clearErrorList ()
Emtpies the error listview.
void clearUnitTests ()
Clears the unit tests.
QString getUnitTest () const
Returns the unit test.
void insertError (const QString &failure, const QString &details)
Inserts an item with text failure to the listview.
void reject ()
Closes and resets this dialog.
void reset ()
Resets this dialog.
void setErrorCount (int)
Sets the number of faulty tests to ct.
void setFailCount (int)
Sets the number of failed tests to ct.
void setProgressFraction (float fraction, const QString &=QString())
Sets the progress of the progress bar whereas fraction is in between 0.0 and 1.0.
void setRemainCount (int)
Sets the number of remaining tests to ct.
void setRunCount (int)
Sets the number of performed tests to ct.
void setStatusText (const QString &text)
Sets the text in the status bar.
void setUnitTest (const QString &unit)
Sets the unit test.
void showErrorDialog (const char *title, const char *message)
Shows an error dialog with title and message.
Static Public Member Functions
static void destruct ()
Destructs the instance of this dialog.
static bool hasInstance ()
Returns true if an instance of this dialog exists, false otherwise.
static UnitTestDialog * instance ()
Creates and returns the one and only instance of this dialog.
Protected Member Functions
void setProgressColor (const QColor &col)
Sets the color to the progressbar to col.
UnitTestDialog (QWidget *parent=0, Qt::WindowFlags f=Qt::WindowFlags())
Constructs a TestGui::UnitTestDialog as a child of 'parent', with the name 'name' and widget flags set to 'f'.
~UnitTestDialog ()
Destroys the object and frees any allocated resources.
Constructor & Destructor Documentation
UnitTestDialog()
UnitTestDialog::UnitTestDialog (QWidget * parent = 0, Qt::WindowFlags f = Qt::WindowFlags()) protected
Constructs a TestGui::UnitTestDialog as a child of 'parent', with the name 'name' and widget flags set to 'f'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
References femsolver.elmer.equations.elasticity::create(), and setProgressColor().
Referenced by instance().
~UnitTestDialog()
UnitTestDialog::~UnitTestDialog () protected
Destroys the object and frees any allocated resources.
Member Function Documentation
addUnitTest()
void UnitTestDialog::addUnitTest (const QString & unit)
Adds a unit test.
If a test with name unit already is added then nothing happens.
Referenced by TestGui::UnitTestDialogPy::addUnitTest(), and setUnitTest().
clearErrorList()
void UnitTestDialog::clearErrorList ()
Emtpies the error listview.
Referenced by TestGui::UnitTestDialogPy::clearErrorList().
clearUnitTests()
void UnitTestDialog::clearUnitTests ()
Clears the unit tests.
Referenced by TestGui::UnitTestDialogPy::clearUnitTests().
destruct()
void UnitTestDialog::destruct (void) static
Destructs the instance of this dialog.
getUnitTest()
QString UnitTestDialog::getUnitTest () const
Returns the unit test.
hasInstance()
bool UnitTestDialog::hasInstance () static
Returns true if an instance of this dialog exists, false otherwise.
insertError()
void UnitTestDialog::insertError (const QString & failure, const QString & details)
Inserts an item with text failure to the listview.
details will be shown when double-clicking on the matching listitem.
Referenced by TestGui::UnitTestDialogPy::insertError().
instance()
UnitTestDialog * UnitTestDialog::instance (void) static
Creates and returns the one and only instance of this dialog.
References Gui::getMainWindow(), and UnitTestDialog().
Referenced by TestGui::UnitTestDialogPy::addUnitTest(), TestGui::UnitTestDialogPy::clearErrorList(), TestGui::UnitTestDialogPy::clearUnitTests(), TestGui::UnitTestDialogPy::errorDialog(), TestGui::UnitTestDialogPy::getUnitTest(), TestGui::UnitTestDialogPy::insertError(), TestGui::UnitTestDialogPy::setErrorCount(), TestGui::UnitTestDialogPy::setFailCount(), TestGui::UnitTestDialogPy::setProgressFrac(), TestGui::UnitTestDialogPy::setRemainCount(), TestGui::UnitTestDialogPy::setRunCount(), TestGui::UnitTestDialogPy::setStatusText(), and TestGui::UnitTestDialogPy::setUnitTest().
on_aboutButton_clicked
void UnitTestDialog::on_aboutButton_clicked () slot
Shows the about dialog.
on_helpButton_clicked
void UnitTestDialog::on_helpButton_clicked () slot
Shows the help dialog.
on_startButton_clicked
void UnitTestDialog::on_startButton_clicked () slot
Runs the unit tests.
References Base::Interpreter(), reset(), Base::InterpreterSingleton::runString(), setProgressColor(), and showErrorDialog().
on_treeViewFailure_itemDoubleClicked
void UnitTestDialog::on_treeViewFailure_itemDoubleClicked (QTreeWidgetItem * item, int column) slot
Opens a dialog to display a detailed description about the error.
reject()
void UnitTestDialog::reject (void)
Closes and resets this dialog.
References reset().
reset()
void UnitTestDialog::reset (void)
Resets this dialog.
Referenced by on_startButton_clicked(), and reject().
setErrorCount()
void UnitTestDialog::setErrorCount (int ct)
Sets the number of faulty tests to ct.
Referenced by TestGui::UnitTestDialogPy::setErrorCount().
setFailCount()
void UnitTestDialog::setFailCount (int ct)
Sets the number of failed tests to ct.
Referenced by TestGui::UnitTestDialogPy::setFailCount().
setProgressColor()
void UnitTestDialog::setProgressColor (const QColor & col) protected
Sets the color to the progressbar to col.
Referenced by on_startButton_clicked(), setProgressFraction(), and UnitTestDialog().
setProgressFraction()
void UnitTestDialog::setProgressFraction (float fraction, const QString & color = QString())
Sets the progress of the progress bar whereas fraction is in between 0.0 and 1.0.
It also sets the color of the progress bar to red if a failure or error in the unit test occurred.
References setProgressColor().
Referenced by TestGui::UnitTestDialogPy::setProgressFrac().
setRemainCount()
void UnitTestDialog::setRemainCount (int ct)
Sets the number of remaining tests to ct.
Referenced by TestGui::UnitTestDialogPy::setRemainCount().
setRunCount()
void UnitTestDialog::setRunCount (int ct)
Sets the number of performed tests to ct.
Referenced by TestGui::UnitTestDialogPy::setRunCount().
setStatusText()
void UnitTestDialog::setStatusText (const QString & text)
Sets the text in the status bar.
Referenced by TestGui::UnitTestDialogPy::setStatusText().
setUnitTest()
void UnitTestDialog::setUnitTest (const QString & unit)
Sets the unit test.
If the item is not there yet it gets added.
References addUnitTest().
Referenced by TestGui::UnitTestDialogPy::setUnitTest().
showErrorDialog()
void UnitTestDialog::showErrorDialog (const char * title, const char * message)
Shows an error dialog with title and message.
Referenced by TestGui::UnitTestDialogPy::errorDialog(), and on_startButton_clicked().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Test/Gui/UnitTestImp.h
Sources/FreeCAD/src/Mod/Test/Gui/UnitTestImp.cpp