FreeCAD: Gui::Dialog::Ui_DlgActivateWindow Class Reference
Gui::Dialog::Ui_DlgActivateWindow Class Reference
#include <ui_DlgActivateWindow.h>
Public Member Functions
void retranslateUi (QDialog *Gui__Dialog__DlgActivateWindow)
void setupUi (QDialog *Gui__Dialog__DlgActivateWindow)
Public Attributes
QDialogButtonBox * buttonBox
QGridLayout * gridLayout
QTreeWidget * treeWidget
Member Function Documentation
retranslateUi()
void Gui::Dialog::Ui_DlgActivateWindow::retranslateUi (QDialog * Gui__Dialog__DlgActivateWindow)
References draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::Dialog::Ui_DlgActivateWindow::setupUi (QDialog * Gui__Dialog__DlgActivateWindow)
References buttonBox, draftgeoutils.intersections::connect(), gridLayout, retranslateUi(), and treeWidget.
Referenced by Gui::Dialog::DlgActivateWindowImp::DlgActivateWindowImp().
Member Data Documentation
buttonBox
QDialogButtonBox* Gui::Dialog::Ui_DlgActivateWindow::buttonBox
Referenced by Gui::Dialog::DlgActivateWindowImp::DlgActivateWindowImp(), PathScripts.PathGetPoint.TaskPanel::getPoint(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::modifyStandardButtons(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::pageDirtyChanged(), PathScripts.PathGetPoint.TaskPanel::pointFinish(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setClean(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setDirty(), and setupUi().
gridLayout
QGridLayout* Gui::Dialog::Ui_DlgActivateWindow::gridLayout
Referenced by setupUi().
treeWidget
QTreeWidget* Gui::Dialog::Ui_DlgActivateWindow::treeWidget
Referenced by Gui::Dialog::DlgActivateWindowImp::accept(), Gui::Dialog::DlgActivateWindowImp::DlgActivateWindowImp(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_DlgActivateWindow.h