FreeCAD: PartGui::SoBrepPointSet Class Reference
PartGui::SoBrepPointSet Class Reference
#include <SoBrepPointSet.h>
Public Member Functions
SoBrepPointSet ()
Static Public Member Functions
static void initClass ()
Protected Member Functions
virtual void doAction (SoAction *action)
virtual void getBoundingBox (SoGetBoundingBoxAction *action)
virtual void GLRender (SoGLRenderAction *action)
virtual void GLRenderBelowPath (SoGLRenderAction *action)
virtual ~SoBrepPointSet ()
Constructor & Destructor Documentation
SoBrepPointSet()
SoBrepPointSet::SoBrepPointSet ()
~SoBrepPointSet()
virtual PartGui::SoBrepPointSet::~SoBrepPointSet () protected virtual
Member Function Documentation
doAction()
void SoBrepPointSet::doAction (SoAction * action) protected virtual
References Gui::SoSelectionElementAction::All, Gui::SoSelectionElementAction::Append, Gui::SoFCSelectionCounter::checkAction(), Gui::SoFCSelectionRoot::getActionContext(), Gui::SoHighlightElementAction::getColor(), Gui::SoSelectionElementAction::getColor(), Gui::SoHighlightElementAction::getElement(), Gui::SoSelectionElementAction::getElement(), Gui::SoSelectionElementAction::getType(), Gui::SoHighlightElementAction::isHighlighted(), Gui::SoSelectionElementAction::isSecondary(), Gui::SoSelectionElementAction::Remove, and Gui::SoFCSelectionRoot::removeActionContext().
getBoundingBox()
void SoBrepPointSet::getBoundingBox (SoGetBoundingBoxAction * action) protected virtual
GLRender()
void SoBrepPointSet::GLRender (SoGLRenderAction * action) protected virtual
References Gui::SoFCSelectionCounter::checkRenderCache().
GLRenderBelowPath()
void SoBrepPointSet::GLRenderBelowPath (SoGLRenderAction * action) protected virtual
initClass()
void SoBrepPointSet::initClass (void) static
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/Gui/SoBrepPointSet.h
Sources/FreeCAD/src/Mod/Part/Gui/SoBrepPointSet.cpp