FreeCAD: PartGui::LoftWidget Class Reference
PartGui::LoftWidget Class Reference
#include <TaskLoft.h>
Classes
class Private
Public Member Functions
bool accept ()
LoftWidget (QWidget *parent=nullptr)
bool reject ()
~LoftWidget ()
Constructor & Destructor Documentation
LoftWidget()
LoftWidget::LoftWidget (QWidget * parent = nullptr)
References Gui::Command::App, Gui::ActionSelector::availableTreeWidget(), draftgeoutils.intersections::connect(), Gui::ActionSelector::selectedTreeWidget(), PartGui::Ui_TaskLoft::selector, Gui::ActionSelector::setAvailableLabel(), Gui::ActionSelector::setSelectedLabel(), PartGui::Ui_TaskLoft::setupUi(), and PartGui::LoftWidget::Private::ui.
~LoftWidget()
LoftWidget::~LoftWidget ()
Member Function Documentation
accept()
bool LoftWidget::accept (void)
References Gui::Command::App, PartGui::Ui_TaskLoft::checkClosed, PartGui::Ui_TaskLoft::checkRuledSurface, PartGui::Ui_TaskLoft::checkSolid, PartGui::LoftWidget::Private::document, Gui::Application::getDocument(), Gui::Application::Instance, draftutils.translate::QT_TRANSLATE_NOOP, Gui::ActionSelector::selectedTreeWidget(), PartGui::Ui_TaskLoft::selector, and PartGui::LoftWidget::Private::ui.
Referenced by PartGui::TaskLoft::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
reject()
bool LoftWidget::reject (void)
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), PartGui::TaskLoft::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/TaskLoft.h
FreeCAD/src/Mod/Part/Gui/TaskLoft.cpp