FreeCAD: zipios::ZipCDirEntry Class Reference
zipios::ZipCDirEntry Class Reference
Specialization of ZipLocalEntry, that add fields for storing the extra information, that is only present in the entries in the zip central directory and not in the local entry headers.
#include <ziphead.h>
Public Member Functions
virtual FileEntry * clone () const
Create a heap allocated clone of the object this method is called for.
int getCDirHeaderSize () const
virtual string getComment () const
Returns the comment of the entry, if it has one.
virtual uint32 getLocalHeaderOffset () const
virtual void setComment (const string &comment)
Sets the comment field for the FileEntry.
void setDefaultWriter ()
virtual void setLocalHeaderOffset (uint32 offset)
virtual string toString () const
Returns a human-readable string representation of the entry.
ZipCDirEntry (const string &_filename="", const string &_file_comment="", const vector< unsigned char > &_extra_field=vector< unsigned char >())
virtual ~ZipCDirEntry ()
Public Member Functions inherited from zipios::ZipLocalEntry
virtual uint32 getCompressedSize () const
Returns the compressed size of the entry.
virtual uint32 getCrc () const
Returns the Crc for the entry, if it has one.
virtual vector< unsigned char > getExtra () const
Returns a vector of bytes of extra data that may be stored with the entry.
virtual string getFileName () const
Returns the filename of the entry.
int getLocalHeaderSize () const
virtual StorageMethod getMethod () const
Returns the method used to store the entry in the FileCollection.
virtual string getName () const
Returns the full filename of the entry, including a path if the entry is stored in a subfolder.
virtual uint32 getSize () const
Returns the (uncompressed) size of the entry data.
virtual int getTime () const
Returns the date and time of FIXME: what?
virtual bool isDirectory () const
Returns true if the entry is a directory.
virtual bool isValid () const
Any method or operator that initializes a FileEntry may set a flag, that specifies whether the read entry is valid or not.
virtual void setCompressedSize (uint32 size)
Set the compressed size field of the entry.
virtual void setCrc (uint32 crc)
Sets the crc field.
void setDefaultExtract ()
virtual void setExtra (const vector< unsigned char > &extra)
Sets the extra field.
virtual void setMethod (StorageMethod method)
Sets the storage method field for the entry.
virtual void setName (const string &name)
Sets the name field for the entry.
virtual void setSize (uint32 size)
Sets the size field for the entry.
virtual void setTime (int time)
Sets the time field for the entry.
bool trailingDataDescriptor () const
ZipLocalEntry (const string &_filename="", const vector< unsigned char > &_extra_field=vector< unsigned char >())
virtual ~ZipLocalEntry ()
Public Member Functions inherited from zipios::FileEntry
virtual ~FileEntry ()
FileEntry destructor.
Friends
ostream & operator<< (ostream &os, const ZipCDirEntry &zcdh)
bool operator== (const ZipLocalEntry &zlh, const ZipCDirEntry &ze)
istream & operator>> (istream &is, ZipCDirEntry &zcdh)
Additional Inherited Members
Protected Member Functions inherited from zipios::FileEntry
void ref () const
unsigned int unref () const
Protected Attributes inherited from zipios::ZipLocalEntry
uint16 compress_method
uint32 compress_size
uint32 crc_32
vector< unsigned char > extra_field
uint16 extra_field_len
uint16 extract_version
string filename
uint16 filename_len
uint16 gp_bitfield
uint16 last_mod_fdate
uint16 last_mod_ftime
uint32 uncompress_size
Static Protected Attributes inherited from zipios::ZipLocalEntry
static const uint32 signature = 0x04034b50
Detailed Description
Specialization of ZipLocalEntry, that add fields for storing the extra information, that is only present in the entries in the zip central directory and not in the local entry headers.
Constructor & Destructor Documentation
ZipCDirEntry()
zipios::ZipCDirEntry::ZipCDirEntry (const string & _filename = "", const string & _file_comment = "", const vector< unsigned char > & _extra_field = vector< unsigned char >())
Referenced by clone().
~ZipCDirEntry()
virtual zipios::ZipCDirEntry::~ZipCDirEntry () virtual
Member Function Documentation
clone()
FileEntry * zipios::ZipCDirEntry::clone () const virtual
Create a heap allocated clone of the object this method is called for.
The caller is responsible for deallocating the clone when he is done with it.
Returns
A heap allocated copy of the object this method is called for.
Reimplemented from zipios::ZipLocalEntry.
References ZipCDirEntry().
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchComponent.Component::execute(), ArchCurtainWall.CurtainWall::execute(), ArchTruss.Truss::execute(), and Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated().
getCDirHeaderSize()
int zipios::ZipCDirEntry::getCDirHeaderSize () const
References zipios::ZipLocalEntry::extra_field, and zipios::ZipLocalEntry::filename.
getComment()
string zipios::ZipCDirEntry::getComment () const virtual
Returns the comment of the entry, if it has one.
Otherwise it returns an empty string.
Returns
the comment associated with the entry, if there is one.
Reimplemented from zipios::ZipLocalEntry.
getLocalHeaderOffset()
uint32 zipios::ZipCDirEntry::getLocalHeaderOffset () const virtual
Referenced by zipios::ZipOutputStreambuf::updateEntryHeaderInfo().
setComment()
void zipios::ZipCDirEntry::setComment (const string & comment) virtual
Sets the comment field for the FileEntry.
Parameters
comment string with the new comment.
Reimplemented from zipios::ZipLocalEntry.
setDefaultWriter()
void zipios::ZipCDirEntry::setDefaultWriter ()
setLocalHeaderOffset()
void zipios::ZipCDirEntry::setLocalHeaderOffset (uint32 offset) virtual
References draftfunctions.offset::offset().
Referenced by zipios::ZipOutputStreambuf::putNextEntry().
toString()
string zipios::ZipCDirEntry::toString () const virtual
Returns a human-readable string representation of the entry.
Returns
a human-readable string representation of the entry.
Reimplemented from zipios::ZipLocalEntry.
References zipios::ZipLocalEntry::compress_size, zipios::ZipLocalEntry::filename, zipios::OutputStringStream::str(), and zipios::ZipLocalEntry::uncompress_size.
Friends And Related Function Documentation
operator<<
ostream& operator<< (ostream & os, const ZipCDirEntry & zcdh) friend
operator==
bool operator== (const ZipLocalEntry & zlh, const ZipCDirEntry & ze) friend
operator>>
istream& operator>> (istream & is, ZipCDirEntry & zcdh) friend
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/zipios++/ziphead.h
Sources/FreeCAD/src/zipios++/ziphead.cpp