FreeCAD: Mesh::AmfExporter Class Reference
Mesh::AmfExporter Class Reference
Used for exporting to Additive Manufacturing File (AMF) format.
#include <Exporter.h>
Public Member Functions
bool addMesh (const MeshCore::MeshKernel &kernel, const std::map< std::string, std::string > &meta)
bool addMeshFeat (App::DocumentObject *obj) override
bool addPartFeat (App::DocumentObject *obj, float tol) override
AmfExporter (std::string fileName, const std::map< std::string, std::string > &meta, bool compress=true)
Writes AMF header.
~AmfExporter ()
Writes AMF footer.
Public Member Functions inherited from Mesh::Exporter
bool addAppGroup (App::DocumentObject *obj, float tol)
Recursively adds objects from App::Part & App::DocumentObjectGroup.
bool addObject (App::DocumentObject *obj, float tol)
Exporter ()
virtual ~Exporter ()=default
Additional Inherited Members
Static Public Member Functions inherited from Mesh::Exporter
static bool isSupported (App::DocumentObject *obj)
Static Protected Member Functions inherited from Mesh::Exporter
static std::string xmlEscape (const std::string &input)
Does some simple escaping of characters for XML-type exports.
Protected Attributes inherited from Mesh::Exporter
const Base::Type appPartId
const Base::Type groupExtensionId
const Base::Type meshFeatId
Detailed Description
Used for exporting to Additive Manufacturing File (AMF) format.
The constructor and destructor write the beginning and end of the AMF, add____() is used to add geometry
Constructor & Destructor Documentation
AmfExporter()
AmfExporter::AmfExporter (std::string fileName, const std::map< std::string, std::string > & meta, bool compress = true)
Writes AMF header.
meta information passed in is applied at the <amf> tag level
References Base::FileInfo::dirPath(), Base::FileInfo::exists(), Base::FileInfo::fileName(), Base::FileInfo::filePath(), and Base::FileInfo::isWritable().
~AmfExporter()
AmfExporter::~AmfExporter ()
Writes AMF footer.
Member Function Documentation
addMesh()
bool AmfExporter::addMesh (const MeshCore::MeshKernel & kernel, const std::map< std::string, std::string > & meta)
meta is included for the AMF object created
References MeshCore::MeshKernel::CountFacets(), and MeshCore::MeshFacetIterator::End().
Referenced by addMeshFeat(), and addPartFeat().
addMeshFeat()
bool AmfExporter::addMeshFeat (App::DocumentObject * obj) override virtual
Implements Mesh::Exporter.
References addMesh(), MeshCore::MeshKernel::Transform(), and Mesh::Exporter::xmlEscape().
addPartFeat()
bool AmfExporter::addPartFeat (App::DocumentObject * obj, float tol) override virtual
Implements Mesh::Exporter.
References addMesh(), Base::Persistence::getClassTypeId(), MeshCore::MeshKernel::Transform(), and Mesh::Exporter::xmlEscape().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Exporter.h
Sources/FreeCAD/src/Mod/Mesh/App/Exporter.cpp