FreeCAD: Part::BRepOffsetAPI_MakeFillingPy Class Reference
Part::BRepOffsetAPI_MakeFillingPy Class Reference
The python export class for BRepOffsetAPI_MakeFilling.
#include <BRepOffsetAPI_MakeFillingPy.h>
Public Types
typedef BRepOffsetAPI_MakeFilling * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
BRepOffsetAPI_MakeFillingPy (BRepOffsetAPI_MakeFilling *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BRepOffsetAPI_MakeFilling * getBRepOffsetAPI_MakeFillingPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
BRepOffsetAPI_MakeFillingPy::PyMake.
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of BRepOffsetAPI_MakeFillingPy.
static PyMethodDef Methods []
Methods structure of BRepOffsetAPI_MakeFillingPy.
static PyTypeObject Type
Type structure of BRepOffsetAPI_MakeFillingPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~BRepOffsetAPI_MakeFillingPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * setConstrParam (PyObject *args, PyObject *kwd)
implementer for the setConstrParam() method
PyObject * setResolParam (PyObject *args, PyObject *kwd)
implementer for the setResolParam() method
PyObject * setApproxParam (PyObject *args, PyObject *kwd)
implementer for the setApproxParam() method
PyObject * loadInitSurface (PyObject *args)
implementer for the loadInitSurface() method
PyObject * add (PyObject *args, PyObject *kwd)
implementer for the add() method
PyObject * build (PyObject *args)
implementer for the build() method
PyObject * isDone (PyObject *args)
implementer for the isDone() method
PyObject * G0Error (PyObject *args)
implementer for the G0Error() method
PyObject * G1Error (PyObject *args)
implementer for the G1Error() method
PyObject * G2Error (PyObject *args)
implementer for the G2Error() method
PyObject * shape (PyObject *args)
implementer for the shape() method
static PyObject * staticCallback_setConstrParam (PyObject *self, PyObject *args, PyObject *kwd)
callback for the setConstrParam() method
static PyObject * staticCallback_setResolParam (PyObject *self, PyObject *args, PyObject *kwd)
callback for the setResolParam() method
static PyObject * staticCallback_setApproxParam (PyObject *self, PyObject *args, PyObject *kwd)
callback for the setApproxParam() method
static PyObject * staticCallback_loadInitSurface (PyObject *self, PyObject *args)
callback for the loadInitSurface() method
static PyObject * staticCallback_add (PyObject *self, PyObject *args, PyObject *kwd)
callback for the add() method
static PyObject * staticCallback_build (PyObject *self, PyObject *args)
callback for the build() method
static PyObject * staticCallback_isDone (PyObject *self, PyObject *args)
callback for the isDone() method
static PyObject * staticCallback_G0Error (PyObject *self, PyObject *args)
callback for the G0Error() method
static PyObject * staticCallback_G1Error (PyObject *self, PyObject *args)
callback for the G1Error() method
static PyObject * staticCallback_G2Error (PyObject *self, PyObject *args)
callback for the G2Error() method
static PyObject * staticCallback_shape (PyObject *self, PyObject *args)
callback for the shape() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for BRepOffsetAPI_MakeFilling.
Member Typedef Documentation
PointerType
typedef BRepOffsetAPI_MakeFilling* Part::BRepOffsetAPI_MakeFillingPy::PointerType
Constructor & Destructor Documentation
~BRepOffsetAPI_MakeFillingPy()
BRepOffsetAPI_MakeFillingPy::~BRepOffsetAPI_MakeFillingPy () protected
BRepOffsetAPI_MakeFillingPy()
BRepOffsetAPI_MakeFillingPy::BRepOffsetAPI_MakeFillingPy (BRepOffsetAPI_MakeFilling * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
add()
PyObject * BRepOffsetAPI_MakeFillingPy::add (PyObject * args, PyObject * kwd)
implementer for the add() method
References getBRepOffsetAPI_MakeFillingPtr(), Base::VectorPy::Type, Part::TopoShapeEdgePy::Type, Part::TopoShapeFacePy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_add().
build()
PyObject * BRepOffsetAPI_MakeFillingPy::build (PyObject * args)
implementer for the build() method
References getBRepOffsetAPI_MakeFillingPtr().
Referenced by staticCallback_build().
G0Error()
PyObject * BRepOffsetAPI_MakeFillingPy::G0Error (PyObject * args)
implementer for the G0Error() method
References getBRepOffsetAPI_MakeFillingPtr().
Referenced by staticCallback_G0Error().
G1Error()
PyObject * BRepOffsetAPI_MakeFillingPy::G1Error (PyObject * args)
implementer for the G1Error() method
References getBRepOffsetAPI_MakeFillingPtr().
Referenced by staticCallback_G1Error().
G2Error()
PyObject * BRepOffsetAPI_MakeFillingPy::G2Error (PyObject * args)
implementer for the G2Error() method
References getBRepOffsetAPI_MakeFillingPtr().
Referenced by staticCallback_G2Error().
getBRepOffsetAPI_MakeFillingPtr()
BRepOffsetAPI_MakeFilling * BRepOffsetAPI_MakeFillingPy::getBRepOffsetAPI_MakeFillingPtr (void) const
getter for the object handled by this class
Referenced by add(), build(), G0Error(), G1Error(), G2Error(), isDone(), loadInitSurface(), setApproxParam(), setConstrParam(), setResolParam(), and shape().
getCustomAttributes()
PyObject * BRepOffsetAPI_MakeFillingPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
GetType()
virtual PyTypeObject* Part::BRepOffsetAPI_MakeFillingPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
isDone()
PyObject * BRepOffsetAPI_MakeFillingPy::isDone (PyObject * args)
implementer for the isDone() method
References getBRepOffsetAPI_MakeFillingPtr().
Referenced by staticCallback_isDone().
loadInitSurface()
PyObject * BRepOffsetAPI_MakeFillingPy::loadInitSurface (PyObject * args)
implementer for the loadInitSurface() method
References getBRepOffsetAPI_MakeFillingPtr(), shape(), and Part::TopoShapeFacePy::Type.
Referenced by staticCallback_loadInitSurface().
PyInit()
int BRepOffsetAPI_MakeFillingPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
References Base::PyObjectBase::setTwinPointer().
PyMake()
PyObject * BRepOffsetAPI_MakeFillingPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
BRepOffsetAPI_MakeFillingPy::PyMake.
v1=App.Vector(0,0,0)
v2=App.Vector(10,0,0)
v3=App.Vector(10,10,3)
v4=App.Vector(0,10,0)
v5=App.Vector(5,5,5)
l1=Part.makeLine(v1, v2)
l2=Part.makeLine(v2, v3)
l3=Part.makeLine(v3, v4)
l4=Part.makeLine(v4, v1)
bp=Part.BRepOffsetAPI.MakeFilling()
bp.add(l1, 0, True)
bp.add(l2, 0, True)
bp.add(l3, 0, True)
bp.add(l4, 0, True)
bp.add(v5)
bp.build()
s=bp.shape()
Part.show(s)
Part.show(l1)
Part.show(l2)
Part.show(l3)
Part.show(l4)
bp.surfInit()
References BRepOffsetAPI_MakeFillingPy().
representation()
std::string BRepOffsetAPI_MakeFillingPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setApproxParam()
PyObject * BRepOffsetAPI_MakeFillingPy::setApproxParam (PyObject * args, PyObject * kwd)
implementer for the setApproxParam() method
References getBRepOffsetAPI_MakeFillingPtr().
Referenced by staticCallback_setApproxParam().
setConstrParam()
PyObject * BRepOffsetAPI_MakeFillingPy::setConstrParam (PyObject * args, PyObject * kwd)
implementer for the setConstrParam() method
References getBRepOffsetAPI_MakeFillingPtr().
Referenced by staticCallback_setConstrParam().
setCustomAttributes()
int BRepOffsetAPI_MakeFillingPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setResolParam()
PyObject * BRepOffsetAPI_MakeFillingPy::setResolParam (PyObject * args, PyObject * kwd)
implementer for the setResolParam() method
References getBRepOffsetAPI_MakeFillingPtr().
Referenced by staticCallback_setResolParam().
shape()
PyObject * BRepOffsetAPI_MakeFillingPy::shape (PyObject * args)
implementer for the shape() method
References getBRepOffsetAPI_MakeFillingPtr().
Referenced by loadInitSurface(), and staticCallback_shape().
staticCallback_add()
PyObject * BRepOffsetAPI_MakeFillingPy::staticCallback_add (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the add() method
References add(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_build()
PyObject * BRepOffsetAPI_MakeFillingPy::staticCallback_build (PyObject * self, PyObject * args) static
callback for the build() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, build(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_G0Error()
PyObject * BRepOffsetAPI_MakeFillingPy::staticCallback_G0Error (PyObject * self, PyObject * args) static
callback for the G0Error() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, G0Error(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_G1Error()
PyObject * BRepOffsetAPI_MakeFillingPy::staticCallback_G1Error (PyObject * self, PyObject * args) static
callback for the G1Error() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, G1Error(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_G2Error()
PyObject * BRepOffsetAPI_MakeFillingPy::staticCallback_G2Error (PyObject * self, PyObject * args) static
callback for the G2Error() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, G2Error(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_isDone()
PyObject * BRepOffsetAPI_MakeFillingPy::staticCallback_isDone (PyObject * self, PyObject * args) static
callback for the isDone() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), isDone(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_loadInitSurface()
PyObject * BRepOffsetAPI_MakeFillingPy::staticCallback_loadInitSurface (PyObject * self, PyObject * args) static
callback for the loadInitSurface() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), loadInitSurface(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_setApproxParam()
PyObject * BRepOffsetAPI_MakeFillingPy::staticCallback_setApproxParam (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the setApproxParam() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setApproxParam(), and Base::PyObjectBase::startNotify().
staticCallback_setConstrParam()
PyObject * BRepOffsetAPI_MakeFillingPy::staticCallback_setConstrParam (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the setConstrParam() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setConstrParam(), and Base::PyObjectBase::startNotify().
staticCallback_setResolParam()
PyObject * BRepOffsetAPI_MakeFillingPy::staticCallback_setResolParam (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the setResolParam() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setResolParam(), and Base::PyObjectBase::startNotify().
staticCallback_shape()
PyObject * BRepOffsetAPI_MakeFillingPy::staticCallback_shape (PyObject * self, PyObject * args) static
callback for the shape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), shape(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef BRepOffsetAPI_MakeFillingPy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of BRepOffsetAPI_MakeFillingPy.
Methods
PyMethodDef BRepOffsetAPI_MakeFillingPy::Methods static
Methods structure of BRepOffsetAPI_MakeFillingPy.
Type
PyTypeObject BRepOffsetAPI_MakeFillingPy::Type static
Type structure of BRepOffsetAPI_MakeFillingPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/BRepOffsetAPI_MakeFillingPy.h
Sources/FreeCAD/src/Mod/Part/App/BRepOffsetAPI_MakeFillingPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/BRepOffsetAPI_MakeFillingPy.cpp