FreeCAD: FemGui::TaskFemConstraint Class Reference
FemGui::TaskFemConstraint Class Reference
#include <TaskFemConstraint.h>
Public Member Functions
const std::string getReferences (const std::vector< std::string > &items) const
virtual const std::string getReferences (void) const
const std::string getScale () const
TaskFemConstraint (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="")
virtual ~TaskFemConstraint ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Protected Types
enum { seldir , selref , selloc , selnone }
Protected Slots
void onButtonReference (const bool pressed=true)
void onButtonWizCancel ()
void onButtonWizOk ()
void onReferenceDeleted (const int row)
void setSelection (QListWidgetItem *item)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Member Functions
virtual void changeEvent (QEvent *e)
void createDeleteAction (QListWidget *parentList)
bool KeyEvent (QEvent *e)
virtual void keyPressEvent (QKeyEvent *ke)
const QString makeRefText (const App::DocumentObject *obj, const std::string &subName) const
const QString makeRefText (const std::string &objName, const std::string &subName) const
virtual void onSelectionChanged (const Gui::SelectionChanges &)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Protected Attributes
Gui::WeakPtrT< ViewProviderFemConstraint > ConstraintView
QAction * deleteAction
QWidget * proxy
enum FemGui::TaskFemConstraint:: { ... } selectionMode
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
seldir
selref
selloc
selnone
Constructor & Destructor Documentation
TaskFemConstraint()
TaskFemConstraint::TaskFemConstraint (ViewProviderFemConstraint * ConstraintView, QWidget * parent = nullptr, const char * pixmapname = "")
References Gui::BitmapFactory(), draftgeoutils.intersections::connect(), ConstraintView, onButtonWizCancel(), onButtonWizOk(), selectionMode, and selref.
~TaskFemConstraint()
virtual FemGui::TaskFemConstraint::~TaskFemConstraint () virtual
Member Function Documentation
changeEvent()
virtual void FemGui::TaskFemConstraint::changeEvent (QEvent * e) protected virtual
Reimplemented in FemGui::TaskFemConstraintBearing, FemGui::TaskFemConstraintContact, FemGui::TaskFemConstraintDisplacement, FemGui::TaskFemConstraintFixed, FemGui::TaskFemConstraintFluidBoundary, FemGui::TaskFemConstraintForce, FemGui::TaskFemConstraintGear, FemGui::TaskFemConstraintHeatflux, FemGui::TaskFemConstraintInitialTemperature, FemGui::TaskFemConstraintPlaneRotation, FemGui::TaskFemConstraintPressure, FemGui::TaskFemConstraintPulley, FemGui::TaskFemConstraintSpring, FemGui::TaskFemConstraintTemperature, and FemGui::TaskFemConstraintTransform.
createDeleteAction()
void TaskFemConstraint::createDeleteAction (QListWidget * parentList) protected
References deleteAction.
Referenced by FemGui::TaskFemConstraintBearing::TaskFemConstraintBearing(), FemGui::TaskFemConstraintDisplacement::TaskFemConstraintDisplacement(), FemGui::TaskFemConstraintFixed::TaskFemConstraintFixed(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintForce::TaskFemConstraintForce(), FemGui::TaskFemConstraintHeatflux::TaskFemConstraintHeatflux(), FemGui::TaskFemConstraintPlaneRotation::TaskFemConstraintPlaneRotation(), FemGui::TaskFemConstraintPressure::TaskFemConstraintPressure(), FemGui::TaskFemConstraintSpring::TaskFemConstraintSpring(), FemGui::TaskFemConstraintTemperature::TaskFemConstraintTemperature(), and FemGui::TaskFemConstraintTransform::TaskFemConstraintTransform().
getReferences() [1/2]
const std::string TaskFemConstraint::getReferences (const std::vector< std::string > & items) const
getReferences() [2/2]
virtual const std::string FemGui::TaskFemConstraint::getReferences (void) const virtual
Reimplemented in FemGui::TaskFemConstraintBearing, FemGui::TaskFemConstraintContact, FemGui::TaskFemConstraintDisplacement, FemGui::TaskFemConstraintFixed, FemGui::TaskFemConstraintFluidBoundary, FemGui::TaskFemConstraintForce, FemGui::TaskFemConstraintHeatflux, FemGui::TaskFemConstraintPlaneRotation, FemGui::TaskFemConstraintPressure, FemGui::TaskFemConstraintSpring, FemGui::TaskFemConstraintTemperature, and FemGui::TaskFemConstraintTransform.
Referenced by FemGui::TaskDlgFemConstraint::accept(), FemGui::TaskFemConstraintBearing::getReferences(), FemGui::TaskFemConstraintContact::getReferences(), FemGui::TaskFemConstraintDisplacement::getReferences(), FemGui::TaskFemConstraintFixed::getReferences(), FemGui::TaskFemConstraintFluidBoundary::getReferences(), FemGui::TaskFemConstraintForce::getReferences(), FemGui::TaskFemConstraintHeatflux::getReferences(), FemGui::TaskFemConstraintPlaneRotation::getReferences(), FemGui::TaskFemConstraintPressure::getReferences(), FemGui::TaskFemConstraintSpring::getReferences(), FemGui::TaskFemConstraintTemperature::getReferences(), and FemGui::TaskFemConstraintTransform::getReferences().
getScale()
const std::string TaskFemConstraint::getScale () const
References ConstraintView, App::PropertyInteger::getValue(), and Fem::Constraint::Scale.
Referenced by FemGui::TaskDlgFemConstraintContact::accept(), FemGui::TaskDlgFemConstraintDisplacement::accept(), FemGui::TaskDlgFemConstraintFixed::accept(), FemGui::TaskDlgFemConstraintFluidBoundary::accept(), FemGui::TaskDlgFemConstraintForce::accept(), FemGui::TaskDlgFemConstraintHeatflux::accept(), FemGui::TaskDlgFemConstraintInitialTemperature::accept(), FemGui::TaskDlgFemConstraintPlaneRotation::accept(), FemGui::TaskDlgFemConstraintPressure::accept(), FemGui::TaskDlgFemConstraintSpring::accept(), FemGui::TaskDlgFemConstraintTemperature::accept(), and FemGui::TaskDlgFemConstraintTransform::accept().
KeyEvent()
bool TaskFemConstraint::KeyEvent (QEvent * e) protected
References deleteAction.
Referenced by FemGui::TaskFemConstraintBearing::event(), FemGui::TaskFemConstraintDisplacement::event(), FemGui::TaskFemConstraintFixed::event(), FemGui::TaskFemConstraintFluidBoundary::event(), FemGui::TaskFemConstraintForce::event(), FemGui::TaskFemConstraintHeatflux::event(), FemGui::TaskFemConstraintPlaneRotation::event(), FemGui::TaskFemConstraintPressure::event(), FemGui::TaskFemConstraintSpring::event(), FemGui::TaskFemConstraintTemperature::event(), and FemGui::TaskFemConstraintTransform::event().
keyPressEvent()
void TaskFemConstraint::keyPressEvent (QKeyEvent * ke) protected virtual
References ConstraintView.
makeRefText() [1/2]
const QString TaskFemConstraint::makeRefText (const App::DocumentObject * obj, const std::string & subName) const protected
makeRefText() [2/2]
const QString TaskFemConstraint::makeRefText (const std::string & objName, const std::string & subName) const protected
Referenced by FemGui::TaskFemConstraintBearing::onSelectionChanged(), FemGui::TaskFemConstraintGear::onSelectionChanged(), FemGui::TaskFemConstraintBearing::TaskFemConstraintBearing(), FemGui::TaskFemConstraintContact::TaskFemConstraintContact(), FemGui::TaskFemConstraintDisplacement::TaskFemConstraintDisplacement(), FemGui::TaskFemConstraintFixed::TaskFemConstraintFixed(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintForce::TaskFemConstraintForce(), FemGui::TaskFemConstraintGear::TaskFemConstraintGear(), FemGui::TaskFemConstraintHeatflux::TaskFemConstraintHeatflux(), FemGui::TaskFemConstraintPlaneRotation::TaskFemConstraintPlaneRotation(), FemGui::TaskFemConstraintPressure::TaskFemConstraintPressure(), FemGui::TaskFemConstraintSpring::TaskFemConstraintSpring(), FemGui::TaskFemConstraintTemperature::TaskFemConstraintTemperature(), and FemGui::TaskFemConstraintTransform::TaskFemConstraintTransform().
onButtonReference
void TaskFemConstraint::onButtonReference (const bool pressed = true) protected slot
References Gui::SelectionSingleton::clearSelection(), Gui::Selection(), selectionMode, selnone, and selref.
Referenced by FemGui::TaskFemConstraintBearing::onSelectionChanged(), and FemGui::TaskFemConstraintBearing::TaskFemConstraintBearing().
onButtonWizCancel
void TaskFemConstraint::onButtonWizCancel () protected slot
References ConstraintView, App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), onButtonWizOk(), and App::Document::removeObject().
Referenced by TaskFemConstraint().
onButtonWizOk
void TaskFemConstraint::onButtonWizOk () protected slot
References Gui::Application::activeDocument(), ConstraintView, Gui::Application::Instance, and Gui::Document::resetEdit().
Referenced by onButtonWizCancel(), and TaskFemConstraint().
onReferenceDeleted
void TaskFemConstraint::onReferenceDeleted (const int row) protected slot
References ConstraintView, App::PropertyLinkSubList::getSubValues(), App::PropertyLinkSubList::getValues(), Fem::Constraint::References, and App::PropertyLinkSubList::setValues().
onSelectionChanged()
virtual void FemGui::TaskFemConstraint::onSelectionChanged (const Gui::SelectionChanges &) protected virtual
Implements Gui::SelectionObserver.
Reimplemented in FemGui::TaskFemConstraintOnBoundary, FemGui::TaskFemConstraintBearing, and FemGui::TaskFemConstraintGear.
setSelection
void TaskFemConstraint::setSelection (QListWidgetItem * item) protected slot
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), ConstraintView, and Gui::Selection().
Referenced by FemGui::TaskFemConstraintContact::TaskFemConstraintContact(), FemGui::TaskFemConstraintDisplacement::TaskFemConstraintDisplacement(), FemGui::TaskFemConstraintFixed::TaskFemConstraintFixed(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintForce::TaskFemConstraintForce(), FemGui::TaskFemConstraintHeatflux::TaskFemConstraintHeatflux(), FemGui::TaskFemConstraintPlaneRotation::TaskFemConstraintPlaneRotation(), FemGui::TaskFemConstraintPressure::TaskFemConstraintPressure(), FemGui::TaskFemConstraintSpring::TaskFemConstraintSpring(), FemGui::TaskFemConstraintTemperature::TaskFemConstraintTemperature(), and FemGui::TaskFemConstraintTransform::TaskFemConstraintTransform().
Member Data Documentation
ConstraintView
Gui::WeakPtrT<ViewProviderFemConstraint> FemGui::TaskFemConstraint::ConstraintView protected
Referenced by getScale(), keyPressEvent(), FemGui::TaskFemConstraintOnBoundary::onButtonToggled(), onButtonWizCancel(), onButtonWizOk(), onReferenceDeleted(), FemGui::TaskFemConstraintOnBoundary::onSelectionChanged(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), FemGui::TaskFemConstraintGear::onSelectionChanged(), setSelection(), TaskFemConstraint(), FemGui::TaskFemConstraintBearing::TaskFemConstraintBearing(), FemGui::TaskFemConstraintContact::TaskFemConstraintContact(), FemGui::TaskFemConstraintDisplacement::TaskFemConstraintDisplacement(), FemGui::TaskFemConstraintFixed::TaskFemConstraintFixed(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintForce::TaskFemConstraintForce(), FemGui::TaskFemConstraintGear::TaskFemConstraintGear(), FemGui::TaskFemConstraintHeatflux::TaskFemConstraintHeatflux(), FemGui::TaskFemConstraintInitialTemperature::TaskFemConstraintInitialTemperature(), FemGui::TaskFemConstraintOnBoundary::TaskFemConstraintOnBoundary(), FemGui::TaskFemConstraintPlaneRotation::TaskFemConstraintPlaneRotation(), FemGui::TaskFemConstraintPressure::TaskFemConstraintPressure(), FemGui::TaskFemConstraintPulley::TaskFemConstraintPulley(), FemGui::TaskFemConstraintSpring::TaskFemConstraintSpring(), FemGui::TaskFemConstraintTemperature::TaskFemConstraintTemperature(), FemGui::TaskFemConstraintTransform::TaskFemConstraintTransform(), and FemGui::TaskFemConstraintOnBoundary::~TaskFemConstraintOnBoundary().
deleteAction
QAction* FemGui::TaskFemConstraint::deleteAction protected
Referenced by createDeleteAction(), KeyEvent(), FemGui::TaskFemConstraintBearing::TaskFemConstraintBearing(), FemGui::TaskFemConstraintDisplacement::TaskFemConstraintDisplacement(), FemGui::TaskFemConstraintFixed::TaskFemConstraintFixed(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintForce::TaskFemConstraintForce(), FemGui::TaskFemConstraintHeatflux::TaskFemConstraintHeatflux(), FemGui::TaskFemConstraintPlaneRotation::TaskFemConstraintPlaneRotation(), FemGui::TaskFemConstraintPressure::TaskFemConstraintPressure(), FemGui::TaskFemConstraintSpring::TaskFemConstraintSpring(), FemGui::TaskFemConstraintTemperature::TaskFemConstraintTemperature(), and FemGui::TaskFemConstraintTransform::TaskFemConstraintTransform().
proxy
QWidget* FemGui::TaskFemConstraint::proxy protected
Referenced by FemGui::TaskFemConstraintBearing::changeEvent(), FemGui::TaskFemConstraintFluidBoundary::changeEvent(), FemGui::TaskFemConstraintForce::changeEvent(), FemGui::TaskFemConstraintGear::changeEvent(), FemGui::TaskFemConstraintHeatflux::changeEvent(), FemGui::TaskFemConstraintPulley::changeEvent(), FemGui::TaskFemConstraintBearing::TaskFemConstraintBearing(), FemGui::TaskFemConstraintContact::TaskFemConstraintContact(), FemGui::TaskFemConstraintDisplacement::TaskFemConstraintDisplacement(), FemGui::TaskFemConstraintFixed::TaskFemConstraintFixed(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintForce::TaskFemConstraintForce(), FemGui::TaskFemConstraintHeatflux::TaskFemConstraintHeatflux(), FemGui::TaskFemConstraintInitialTemperature::TaskFemConstraintInitialTemperature(), FemGui::TaskFemConstraintPlaneRotation::TaskFemConstraintPlaneRotation(), FemGui::TaskFemConstraintPressure::TaskFemConstraintPressure(), FemGui::TaskFemConstraintSpring::TaskFemConstraintSpring(), FemGui::TaskFemConstraintTemperature::TaskFemConstraintTemperature(), and FemGui::TaskFemConstraintTransform::TaskFemConstraintTransform().
enum { ... } FemGui::TaskFemConstraint::selectionMode
Referenced by Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonRef1(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonRef2(), Mod.PartDesign.FeatureHole.TaskHole.TaskHole::buttonSupport(), onButtonReference(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), FemGui::TaskFemConstraintGear::onSelectionChanged(), and TaskFemConstraint().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/TaskFemConstraint.h
FreeCAD/src/Mod/Fem/Gui/TaskFemConstraint.cpp