FreeCAD: SMDS_VtkCellIterator Class Reference
SMDS_VtkCellIterator Class Reference
#include <SMDS_VtkCellIterator.hxx>
Public Member Functions
void exchange (vtkIdType a, vtkIdType b)
virtual bool more ()
Return true if and only if there are other object in this iterator.
virtual const SMDS_MeshElement * next ()
Return the current object and step to the next one.
SMDS_VtkCellIterator (SMDS_Mesh *mesh, int vtkCellId, SMDSAbs_EntityType aType)
virtual ~SMDS_VtkCellIterator ()
Public Member Functions inherited from SMDS_Iterator< VALUE >
virtual void remove ()
Delete the current element and step to the next one.
virtual ~SMDS_Iterator ()
Provide virtual destructor just for case if some derived iterator must have a destructor.
Protected Member Functions
SMDS_VtkCellIterator ()
Constructor & Destructor Documentation
SMDS_VtkCellIterator() [1/2]
SMDS_VtkCellIterator::SMDS_VtkCellIterator (SMDS_Mesh * mesh, int vtkCellId, SMDSAbs_EntityType aType)
References SMDS_MeshCell::fromVtkOrder().
~SMDS_VtkCellIterator()
SMDS_VtkCellIterator::~SMDS_VtkCellIterator () virtual
SMDS_VtkCellIterator() [2/2]
SMDS_VtkCellIterator::SMDS_VtkCellIterator () protected
Member Function Documentation
exchange()
void SMDS_VtkCellIterator::exchange (vtkIdType a, vtkIdType b)
more()
bool SMDS_VtkCellIterator::more () virtual
Return true if and only if there are other object in this iterator.
Implements SMDS_Iterator< VALUE >.
Reimplemented in SMDS_VtkCellIteratorPolyH, and SMDS_VtkCellIteratorToUNV.
Referenced by SMDS_VtkCellIteratorToUNV::more().
next()
const SMDS_MeshElement * SMDS_VtkCellIterator::next () virtual
Return the current object and step to the next one.
Implements SMDS_Iterator< VALUE >.
Reimplemented in SMDS_VtkCellIteratorToUNV.
Referenced by SMDS_VtkCellIteratorToUNV::next().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_VtkCellIterator.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_VtkCellIterator.cpp