FreeCAD: femexamples.square_pipe_end_twisted_nodeforces Namespace Reference
femexamples.square_pipe_end_twisted_nodeforces Namespace Reference
Functions
def get_information ()
def init_doc (doc=None)
def setup (doc=None, solvertype="ccxtools")
Variables
string mesh_name = "Mesh"
Function Documentation
get_information()
def femexamples.square_pipe_end_twisted_nodeforces.get_information ()
init_doc()
def femexamples.square_pipe_end_twisted_nodeforces.init_doc (doc = None)
Referenced by femexamples.square_pipe_end_twisted_nodeforces.setup().
setup()
def femexamples.square_pipe_end_twisted_nodeforces.setup (doc = None, solvertype = "ccxtools")
References femexamples.square_pipe_end_twisted_nodeforces.init_doc(), ObjectsFem.makeAnalysis(), ObjectsFem.makeConstraintFixed(), ObjectsFem.makeConstraintForce(), ObjectsFem.makeElementGeometry2D(), ObjectsFem.makeMaterialSolid(), ObjectsFem.makeMeshGmsh(), ObjectsFem.makeSolverCalculix(), and ObjectsFem.makeSolverCalculixCcxTools().
Variable Documentation
mesh_name
string femexamples.square_pipe_end_twisted_nodeforces.mesh_name = "Mesh"