FreeCAD: SketcherGui::SketchOrientationDialog Class Reference
SketcherGui::SketchOrientationDialog Class Reference
#include <SketchOrientationDialog.h>
Public Member Functions
void accept ()
SketchOrientationDialog (void)
~SketchOrientationDialog ()
Public Attributes
int DirType
Base::Placement Pos
Protected Slots
void onPreview ()
Constructor & Destructor Documentation
SketchOrientationDialog()
SketchOrientationDialog::SketchOrientationDialog (void)
References draftgeoutils.intersections::connect(), DirType, and onPreview().
~SketchOrientationDialog()
SketchOrientationDialog::~SketchOrientationDialog ()
Member Function Documentation
accept()
void SketchOrientationDialog::accept (void)
References DirType, and Pos.
onPreview
void SketchOrientationDialog::onPreview () protected slot
References Gui::BitmapFactory().
Referenced by SketchOrientationDialog().
Member Data Documentation
DirType
int SketcherGui::SketchOrientationDialog::DirType
Referenced by accept(), and SketchOrientationDialog().
Pos
Base::Placement SketcherGui::SketchOrientationDialog::Pos
Referenced by accept().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sketcher/Gui/SketchOrientationDialog.h
Sources/FreeCAD/src/Mod/Sketcher/Gui/SketchOrientationDialog.cpp