FreeCAD: MaterialEditor.MaterialsDelegate Class Reference
MaterialEditor.MaterialsDelegate Class Reference
Public Member Functions
def createEditor (self, parent, option, index)
def setEditorData (self, editor, index)
Detailed Description
provides display and editing facilities for data items from a model.
Member Function Documentation
createEditor()
def MaterialEditor.MaterialsDelegate.createEditor (self, parent, option, index)
returns the widget used to change data from the model.
References MaterialEditor.matProperWidget().
setEditorData()
def MaterialEditor.MaterialsDelegate.setEditorData (self, editor, index)
provides the widget with data to manipulate.
References MaterialEditor.MaterialsDelegate.setEditorData().
Referenced by MaterialEditor.MaterialsDelegate.setEditorData().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Material/MaterialEditor.py