FreeCAD: TestSketcherApp Namespace Reference
TestSketcherApp Namespace Reference
Classes
class SketcherSolverTestCases
Functions
def CreateBoxSketchSet (SketchFeature)
def CreateCircleSketch (SketchFeature, center, radius)
def CreateRectangleSketch (SketchFeature, corner, lengths)
def CreateSlotPlateInnerSet (SketchFeature)
def CreateSlotPlateSet (SketchFeature)
Variables
App = FreeCAD
Function Documentation
CreateBoxSketchSet()
def TestSketcherApp.CreateBoxSketchSet (SketchFeature)
CreateCircleSketch()
def TestSketcherApp.CreateCircleSketch (SketchFeature, center, radius)
Referenced by Mod.PartDesign.PartDesignTests.TestPipe.TestPipe.testSimpleSubtractivePipeCase().
CreateRectangleSketch()
def TestSketcherApp.CreateRectangleSketch (SketchFeature, corner, lengths)
Referenced by Mod.PartDesign.PartDesignTests.TestLinearPattern.TestLinearPattern.testHorizontalSketchAxisLinearPattern(), Mod.PartDesign.PartDesignTests.TestPolarPattern.TestPolarPattern.testHorizontalSketchAxisPolarPattern(), Mod.PartDesign.PartDesignTests.TestMirrored.TestMirrored.testMirroredOffsetFailureCase(), Mod.PartDesign.PartDesignTests.TestPad.TestPad.testPadToFaceCase(), Mod.PartDesign.PartDesignTests.TestPad.TestPad.testPadToFirstCase(), Mod.PartDesign.PartDesignTests.TestPad.TestPad.testPadtoLastCase(), Mod.PartDesign.PartDesignTests.TestPad.TestPad.testPadTwoDimensionsCase(), Mod.PartDesign.PartDesignTests.TestPocket.TestPocket.testPocketThroughAllCase(), Mod.PartDesign.PartDesignTests.TestPocket.TestPocket.testPocketToFaceCase(), Mod.PartDesign.PartDesignTests.TestPocket.TestPocket.testPocketToFirstCase(), Mod.PartDesign.PartDesignTests.TestLinearPattern.TestLinearPattern.testVerticalSketchAxisLinearPattern(), and Mod.PartDesign.PartDesignTests.TestPolarPattern.TestPolarPattern.testVerticalSketchAxisPolarPattern().
CreateSlotPlateInnerSet()
def TestSketcherApp.CreateSlotPlateInnerSet (SketchFeature)
CreateSlotPlateSet()
def TestSketcherApp.CreateSlotPlateSet (SketchFeature)
Referenced by PathTests.TestPathUtil.TestPathUtil.test03().
Variable Documentation
App
TestSketcherApp.App = FreeCAD