FreeCAD: Gui::PrefColorButton Class Reference
Gui::PrefColorButton Class Reference
The PrefColorButton class.
#include <PrefWidgets.h>
Public Member Functions
PrefColorButton (QWidget *parent=0)
virtual ~PrefColorButton ()
Public Member Functions inherited from Gui::ColorButton
bool allowChangeColor () const
bool autoChangeColor () const
QColor color () const
Returns the current color of the button.
ColorButton (QWidget *parent=0)
Constructs a colored button called name with parent parent.
bool drawFrame () const
bool isModal () const
void setAllowChangeColor (bool)
void setAutoChangeColor (bool)
void setColor (const QColor &)
Sets the color c to the button.
void setDrawFrame (bool)
void setModal (bool)
~ColorButton ()
Destroys the button.
Public Member Functions inherited from Gui::PrefWidget
QByteArray entryName () const
Returns the widget's preference name.
virtual void OnChange (Base::Subject< const char * > &rCaller, const char *sReason)
This method is called if one or more values in the parameter settings are changed where getParamGrp() points to.
void onRestore ()
Restores the preferences of the widget.
void onSave ()
Saves the current preferences of the widget.
QByteArray paramGrpPath () const
Returns the widget's preferences path.
void setEntryName (const QByteArray &name)
Sets the preference name to name.
void setParamGrpPath (const QByteArray &path)
Sets the preference path to path.
Public Member Functions inherited from Gui::WindowParameter
ParameterGrp::handle getWindowParameter (void)
return the parameter group of this window
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason)
bool setGroupName (const char *name)
Sets the group of the window to name.
WindowParameter (const char *name)
virtual ~WindowParameter ()
Protected Member Functions
void restorePreferences ()
Restores the preferences Must be reimplemented in any subclasses.
void savePreferences ()
Save the preferences Must be reimplemented in any subclasses.
Protected Member Functions inherited from Gui::ColorButton
void paintEvent (QPaintEvent *)
Draws the button label.
Protected Member Functions inherited from Gui::PrefWidget
void failedToRestore (const QString &) const
Print warning that restoring failed.
void failedToSave (const QString &) const
Print warning that saving failed.
PrefWidget ()
Constructs a preference widget.
virtual ~PrefWidget ()
Destroys the widget and detaches it from its parameter group.
Properties
QByteArray prefEntry
QByteArray prefPath
Properties inherited from Gui::ColorButton
bool allowChangeColor
QColor color
bool drawFrame
Additional Inherited Members
Public Slots inherited from Gui::ColorButton
void onChooseColor ()
Opens a QColorDialog to set a new color.
Signals inherited from Gui::ColorButton
void changed ()
Emits this signal when color has changed.
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter (void)
get the parameters
Detailed Description
The PrefColorButton class.
Author
Werner Mayer
Constructor & Destructor Documentation
PrefColorButton()
PrefColorButton::PrefColorButton (QWidget * parent = 0)
~PrefColorButton()
PrefColorButton::~PrefColorButton () virtual
Member Function Documentation
restorePreferences()
void PrefColorButton::restorePreferences () protected virtual
Restores the preferences Must be reimplemented in any subclasses.
Implements Gui::PrefWidget.
References Gui::ColorButton::color, Gui::PrefWidget::entryName(), Gui::PrefWidget::failedToRestore(), ParameterGrp::GetUnsigned(), Gui::WindowParameter::getWindowParameter(), draftgeoutils.general::isNull(), and Gui::ColorButton::setColor().
savePreferences()
void PrefColorButton::savePreferences () protected virtual
Save the preferences Must be reimplemented in any subclasses.
Implements Gui::PrefWidget.
References Gui::ColorButton::color, Gui::PrefWidget::entryName(), Gui::PrefWidget::failedToSave(), Gui::WindowParameter::getWindowParameter(), draftgeoutils.general::isNull(), and ParameterGrp::SetUnsigned().
Property Documentation
prefEntry
QByteArray Gui::PrefColorButton::prefEntry read write
prefPath
QByteArray Gui::PrefColorButton::prefPath read write
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/PrefWidgets.h
Sources/FreeCAD/src/Gui/PrefWidgets.cpp