FreeCAD: SMESHDS_SubMesh Class Reference
SMESHDS_SubMesh Class Reference
#include <SMESHDS_SubMesh.hxx>
Public Member Functions
virtual void AddElement (const SMDS_MeshElement *ME)
virtual void AddNode (const SMDS_MeshNode *ME)
void AddSubMesh (const SMESHDS_SubMesh *theSubMesh)
virtual void Clear ()
void compactList ()
virtual bool Contains (const SMDS_MeshElement *ME) const
bool ContainsSubMesh (const SMESHDS_SubMesh *theSubMesh) const
virtual const SMDS_MeshElement * GetElement (size_t idInShape) const
virtual SMDS_ElemIteratorPtr GetElements () const
int GetID () const
virtual const SMDS_MeshNode * GetNode (size_t idInShape) const
virtual SMDS_NodeIteratorPtr GetNodes () const
SMESHDS_Mesh * GetParent () const
int getSize ()
SMESHDS_SubMeshIteratorPtr GetSubMeshIterator () const
virtual bool IsComplexSubmesh () const
virtual bool IsQuadratic () const
virtual int NbElements () const
virtual int NbNodes () const
int NbSubMeshes () const
void RemoveAllSubmeshes ()
virtual bool RemoveElement (const SMDS_MeshElement *ME, bool isElemDeleted)
virtual bool RemoveNode (const SMDS_MeshNode *ME, bool isNodeDeleted)
bool RemoveSubMesh (const SMESHDS_SubMesh *theSubMesh)
SMESHDS_SubMesh (SMESHDS_Mesh *parent, int index)
Constructor.
virtual ~SMESHDS_SubMesh ()
Destructor.
Constructor & Destructor Documentation
SMESHDS_SubMesh()
SMESHDS_SubMesh::SMESHDS_SubMesh (SMESHDS_Mesh * parent, int index)
Constructor.
~SMESHDS_SubMesh()
SMESHDS_SubMesh::~SMESHDS_SubMesh () virtual
Destructor.
Member Function Documentation
AddElement()
void SMESHDS_SubMesh::AddElement (const SMDS_MeshElement * ME) virtual
Reimplemented in SMESH_ProxyMesh::SubMesh.
References SMDS_MeshElement::GetID(), SMDS_MeshElement::getIdInShape(), SMDS_MeshElement::getshapeId(), SMDS_MeshElement::GetType(), SMDS_MeshElement::setIdInShape(), and SMDS_MeshElement::setShapeId().
Referenced by SMESH_MeshEditor::ConvertToQuadratic(), DriverMED_R_SMESHDS_Mesh::GetSubMesh(), StdMeshers_Import_1D::importMesh(), SMESH_MeshEditor::MergeNodes(), SMESH_MeshEditor::SplitBiQuadraticIntoLinear(), and SMESH_MeshEditor::SplitVolumes().
AddNode()
void SMESHDS_SubMesh::AddNode (const SMDS_MeshNode * ME) virtual
References SMDS_MeshElement::setIdInShape(), and SMDS_MeshElement::setShapeId().
Referenced by DriverMED_R_SMESHDS_Mesh::GetSubMesh(), and StdMeshers_Import_1D::importMesh().
AddSubMesh()
void SMESHDS_SubMesh::AddSubMesh (const SMESHDS_SubMesh * theSubMesh)
Referenced by SMESHDS_Mesh::AddCompoundSubmesh().
Clear()
void SMESHDS_SubMesh::Clear () virtual
Reimplemented in SMESH_ProxyMesh::SubMesh.
Referenced by SMESH_ProxyMesh::SubMesh::~SubMesh().
compactList()
void SMESHDS_SubMesh::compactList ()
References SMDS_MeshElement::setIdInShape().
Contains()
bool SMESHDS_SubMesh::Contains (const SMDS_MeshElement * ME) const virtual
Reimplemented in SMESH_ProxyMesh::SubMesh.
References SMDS_MeshElement::getIdInShape(), and SMDS_MeshElement::GetType().
Referenced by SMESHDS_GroupOnGeom::Contains(), SMESH_MeshEditor::ConvertToQuadratic(), NETGENPlugin_Internals::findBorderElements(), StdMeshers_ProjectionUtils::FindMatchingNodesOnFaces(), SMESH_MeshEditor::FindShape(), SMESH_MesherHelper::LoadNodeColumns(), SMESH_MeshEditor::Smooth(), SMESH_MeshEditor::SplitVolumes(), and VISCOUS_3D::_Shrinker1D::SwapSrcTgtNodes().
ContainsSubMesh()
bool SMESHDS_SubMesh::ContainsSubMesh (const SMESHDS_SubMesh * theSubMesh) const
GetElement()
const SMDS_MeshElement * SMESHDS_SubMesh::GetElement (size_t idInShape) const virtual
GetElements()
SMDS_ElemIteratorPtr SMESHDS_SubMesh::GetElements () const virtual
Reimplemented in SMESH_ProxyMesh::SubMesh.
Referenced by SMESH_Algo::addBadInputElements(), StdMeshers_Quadrangle_2D::check(), NETGENPlugin_NETGEN_2D_ONLY::Compute(), NETGENPlugin_NETGEN_3D::Compute(), StdMeshers_Projection_1D::Compute(), StdMeshers_Projection_1D2D::Compute(), StdMeshers_Projection_2D::Compute(), StdMeshers_Projection_3D::Compute(), StdMeshers_RadialPrism_3D::Compute(), StdMeshers_QuadToTriaAdaptor::Compute(), StdMeshers_QuadToTriaAdaptor::Compute2ndPart(), StdMeshers_Projection_1D::Evaluate(), StdMeshers_Projection_1D2D::Evaluate(), StdMeshers_Projection_2D::Evaluate(), StdMeshers_Projection_3D::Evaluate(), SMESH_MeshEditor::ExtrusionAlongTrack(), NETGENPlugin_Mesher::FillNgMesh(), StdMeshers_ProjectionUtils::FindMatchingNodesOnFaces(), SMESH_2D_Algo::FixInternalNodes(), StdMeshers_FaceSide::GetEdgeNodes(), MyElemIterator::getElements(), SMESH_Algo::GetMeshError(), SMESH_Algo::GetNodeParamOnEdge(), SMESH_MesherHelper::IsDistorted2D(), SMESH_MesherHelper::IsReversedSubMesh(), SMESH_MesherHelper::IsSameElemGeometry(), SMESH_Pattern::Load(), StdMeshers_Penta_3D::LoadIJNodes(), SMESH_MesherHelper::LoadNodeColumns(), StdMeshers_Penta_3D::MakeBlock(), StdMeshers_Penta_3D::MakeMeshOnFxy1(), VISCOUS_3D::_ViscousBuilder::MakeN2NMap(), StdMeshers_Penta_3D::MakeVolumeMesh(), MyIterator< const SMDS_MeshNode * >::MyIterator(), NETGENPlugin_SimpleHypothesis_2D::SetParametersByMesh(), NETGENPlugin_SimpleHypothesis_3D::SetParametersByMesh(), StdMeshers_Adaptive1D::SetParametersByMesh(), StdMeshers_MaxElementArea::SetParametersByMesh(), StdMeshers_MaxElementVolume::SetParametersByMesh(), and SMESH_Algo::VertexNode().
GetID()
int SMESHDS_SubMesh::GetID () const
Referenced by DriverMED_Family::MakeFamilies(), SMESH_Mesh::SortByMeshOrder(), SMESH_MeshEditor::SplitVolumes(), and SMESH_Algo::VertexNode().
GetNode()
const SMDS_MeshNode * SMESHDS_SubMesh::GetNode (size_t idInShape) const virtual
GetNodes()
SMDS_NodeIteratorPtr SMESHDS_SubMesh::GetNodes () const virtual
Reimplemented in SMESH_ProxyMesh::SubMesh.
Referenced by SMESH_Algo::addBadInputElements(), VISCOUS_3D::_Shrinker1D::AddEdge(), StdMeshers_Projection_1D::Compute(), StdMeshers_Projection_2D::Compute(), SMESH_MeshEditor::ExtrusionAlongTrack(), NETGENPlugin_Mesher::FillNgMesh(), NETGENPlugin_Internals::findBorderElements(), StdMeshers_ProjectionUtils::FindMatchingNodesOnFaces(), StdMeshers_Penta_3D::FindNodeOnShape(), StdMeshers_FaceSide::GetEdgeNodes(), MyNodeIterator::getElements(), SMESH_Algo::GetNodeParamOnEdge(), SMESH_Algo::GetSortedNodesOnEdge(), SMESH_Pattern::Load(), StdMeshers_Penta_3D::LoadIJNodes(), StdMeshers_MEFISTO_2D::LoadPoints(), StdMeshers_Penta_3D::MakeMeshOnFxy1(), StdMeshers_Penta_3D::MakeNodes(), MyIterator< const SMDS_MeshNode * >::MyIterator(), StdMeshers_SegmentLengthAroundVertex::SetParametersByMesh(), StdMeshers_Quadrangle_2D::smooth(), and SMESH_MeshEditor::Smooth().
GetParent()
SMESHDS_Mesh* SMESHDS_SubMesh::GetParent () const
Referenced by SMESH_Algo::VertexNode().
getSize()
int SMESHDS_SubMesh::getSize ()
GetSubMeshIterator()
SMESHDS_SubMeshIteratorPtr SMESHDS_SubMesh::GetSubMeshIterator () const
IsComplexSubmesh()
virtual bool SMESHDS_SubMesh::IsComplexSubmesh () const virtual
Referenced by SMESHDS_Mesh::AddCompoundSubmesh(), SMESH_Mesh::GetGroupSubMeshesContaining(), DriverMED_Family::MakeFamilies(), and StdMeshers_ProjectionUtils::SetEventListener().
IsQuadratic()
bool SMESHDS_SubMesh::IsQuadratic () const virtual
Referenced by NETGENPlugin_Mesher::FillNgMesh().
NbElements()
int SMESHDS_SubMesh::NbElements () const virtual
Reimplemented in SMESH_ProxyMesh::SubMesh.
Referenced by NETGENPlugin_Mesher::Compute(), StdMeshers_Hexa_3D::Compute(), StdMeshers_Prism_3D::Compute(), StdMeshers_Projection_1D2D::Compute(), StdMeshers_Projection_2D::Compute(), StdMeshers_QuadToTriaAdaptor::Compute2ndPart(), StdMeshers_Regular_1D::computeInternalParameters(), StdMeshers_Projection_1D2D::Evaluate(), NETGENPlugin_Internals::findBorderElements(), StdMeshers_ProjectionUtils::FindMatchingNodesOnFaces(), SMESH_2D_Algo::FixInternalNodes(), StdMeshers_FaceSide::GetEdgeNodes(), SMESH_Algo::GetSortedNodesOnEdge(), StdMeshers_Import_1D::importMesh(), SMESH_MesherHelper::IsDistorted2D(), SMESH_MesherHelper::IsStructured(), SMESH_Pattern::Load(), SMESH_MesherHelper::LoadNodeColumns(), StdMeshers_Penta_3D::MakeBlock(), VISCOUS_3D::_ViscousBuilder::MakeN2NMap(), NETGENPlugin_SimpleHypothesis_2D::SetParametersByMesh(), StdMeshers_AutomaticLength::SetParametersByMesh(), StdMeshers_NumberOfSegments::SetParametersByMesh(), SMESH_MeshEditor::Smooth(), SMESH_subMesh::SubMeshesComputed(), and SMESH_Algo::VertexNode().
NbNodes()
int SMESHDS_SubMesh::NbNodes () const virtual
Reimplemented in VISCOUS_2D::_ProxyMeshOfFace::_EdgeSubMesh, and SMESH_ProxyMesh::SubMesh.
Referenced by VISCOUS_3D::_Shrinker1D::AddEdge(), NETGENPlugin_Mesher::Compute(), StdMeshers_Projection_2D::Compute(), StdMeshers_Regular_1D::computeInternalParameters(), SMESH_subMesh::ComputeStateEngine(), StdMeshers_Projection_1D2D::Evaluate(), StdMeshers_Projection_2D::Evaluate(), StdMeshers_Projection_3D::Evaluate(), StdMeshers_ProjectionUtils::FindMatchingNodesOnFaces(), StdMeshers_FaceSide::GetEdgeNodes(), SMESH_Algo::GetSortedNodesOnEdge(), StdMeshers_Import_1D::importMesh(), SMESH_Pattern::Load(), StdMeshers_Penta_3D::LoadIJNodes(), StdMeshers_Penta_3D::MakeMeshOnFxy1(), StdMeshers_Penta_3D::MakeNodes(), SMESH_Algo::NumberOfPoints(), StdMeshers_SegmentLengthAroundVertex::SetParametersByMesh(), and SMESH_subMesh::SubMeshesComputed().
NbSubMeshes()
int SMESHDS_SubMesh::NbSubMeshes () const
RemoveAllSubmeshes()
void SMESHDS_SubMesh::RemoveAllSubmeshes ()
RemoveElement()
bool SMESHDS_SubMesh::RemoveElement (const SMDS_MeshElement * ME, bool isElemDeleted) virtual
References SMDS_MeshElement::getIdInShape(), SMDS_MeshElement::getshapeId(), SMDS_MeshElement::setIdInShape(), and SMDS_MeshElement::setShapeId().
Referenced by SMESHDS_Mesh::RemoveFreeElement().
RemoveNode()
bool SMESHDS_SubMesh::RemoveNode (const SMDS_MeshNode * ME, bool isNodeDeleted) virtual
References SMDS_MeshElement::setIdInShape(), and SMDS_MeshElement::setShapeId().
Referenced by StdMeshers_Import_1D2D::Compute(), StdMeshers_Projection_1D2D::Compute(), SMESHDS_Mesh::RemoveFreeNode(), and SMESH_MeshEditor::SplitVolumes().
RemoveSubMesh()
bool SMESHDS_SubMesh::RemoveSubMesh (const SMESHDS_SubMesh * theSubMesh)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESHDS_SubMesh.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESHDS/SMESHDS_SubMesh.cpp