FreeCAD: Gui::WindowAction Class Reference
Gui::WindowAction Class Reference
#include <Action.h>
Public Member Functions
void addTo (QWidget *w)
Adds this action to widget w.
WindowAction (Command *pcCmd, QObject *parent=0)
virtual ~WindowAction ()
Public Member Functions inherited from Gui::ActionGroup
ActionGroup (Command *pcCmd, QObject *parent=0)
Constructs an action called name with parent parent.
QList< QAction * > actions () const
QAction * addAction (const QString &)
QAction * addAction (QAction *)
int checkedAction () const
bool isExclusive () const
void setCheckedAction (int)
void setDisabled (bool)
void setDropDownMenu (bool b)
void setEnabled (bool)
Sets whether the action is enabled.
void setExclusive (bool)
void setVisible (bool)
virtual ~ActionGroup ()
Public Member Functions inherited from Gui::Action
QAction * action () const
Action (Command *pcCmd, QAction *action, QObject *parent)
Action takes ownership of the 'action' object.
Action (Command *pcCmd, QObject *parent=0)
Constructs an action called name with parent parent.
QIcon icon () const
bool isChecked () const
void setCheckable (bool)
void setChecked (bool, bool no_signal=false)
void setIcon (const QIcon &)
void setMenuRole (QAction::MenuRole menuRole)
void setShortcut (const QString &)
void setStatusTip (const QString &)
void setText (const QString &)
void setToolTip (const QString &)
void setWhatsThis (const QString &)
QKeySequence shortcut () const
QString statusTip () const
QString text () const
QString toolTip () const
QString whatsThis () const
virtual ~Action ()
Additional Inherited Members
Public Slots inherited from Gui::ActionGroup
void onActivated ()
Activates the command.
void onActivated (QAction *)
Activates the command.
void onHovered (QAction *)
void onToggled (bool)
Public Slots inherited from Gui::Action
virtual void onActivated ()
Activates the command.
virtual void onToggled (bool)
Sets whether the command is toggled.
Detailed Description
Author
Werner Mayer
Constructor & Destructor Documentation
WindowAction()
WindowAction::WindowAction (Command * pcCmd, QObject * parent = 0)
~WindowAction()
WindowAction::~WindowAction () virtual
Member Function Documentation
addTo()
void WindowAction::addTo (QWidget * w) virtual
Adds this action to widget w.
Reimplemented from Gui::ActionGroup.
References draftgeoutils.intersections::connect(), and Gui::getMainWindow().
Referenced by Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Action.h
Sources/FreeCAD/src/Gui/Action.cpp