FreeCAD: MeshCore::MeshTrimming Class Reference
MeshCore::MeshTrimming Class Reference
Checks the facets in 2D and then trim them in 3D.
#include <Trim.h>
Public Types
enum TMode { INNER , OUTER }
Public Member Functions
void CheckFacets (const MeshFacetGrid &rclGrid, std::vector< unsigned long > &raulFacets) const
Checks all facets for intersection with the polygon and writes all touched facets into the vector.
MeshTrimming (MeshKernel &mesh, const Base::ViewProjMethod *pclProj, const Base::Polygon2d &rclPoly)
void SetInnerOrOuter (TMode tMode)
Setter: Trimm INNER or OUTER.
void TrimFacets (const std::vector< unsigned long > &raulFacets, std::vector< MeshGeomFacet > &aclNewFacets)
The facets from raulFacets will be trimmed or deleted and aclNewFacets gives the new generated facets.
~MeshTrimming ()
Detailed Description
Checks the facets in 2D and then trim them in 3D.
Member Enumeration Documentation
TMode
enum MeshCore::MeshTrimming::TMode
Enumerator
INNER
OUTER
Constructor & Destructor Documentation
MeshTrimming()
MeshTrimming::MeshTrimming (MeshKernel & mesh, const Base::ViewProjMethod * pclProj, const Base::Polygon2d & rclPoly)
~MeshTrimming()
MeshTrimming::~MeshTrimming ()
Member Function Documentation
CheckFacets()
void MeshTrimming::CheckFacets (const MeshFacetGrid & rclGrid, std::vector< unsigned long > & raulFacets) const
Checks all facets for intersection with the polygon and writes all touched facets into the vector.
References Base::Polygon2d::CalcBoundBox(), MeshCore::MeshKernel::CountFacets(), MeshCore::MeshGridIterator::GetBoundBox(), MeshCore::MeshGridIterator::GetElements(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshGridIterator::Init(), MeshCore::MeshFacetIterator::Init(), Base::BoundBox2d::Intersect(), MeshCore::MeshGridIterator::More(), MeshCore::MeshFacetIterator::More(), Base::SequencerLauncher::next(), MeshCore::MeshGridIterator::Next(), MeshCore::MeshFacetIterator::Next(), MeshCore::MeshFacetIterator::Position(), and Base::BoundBox3< _Precision >::ProjectBox().
SetInnerOrOuter()
void MeshTrimming::SetInnerOrOuter (TMode tMode)
Setter: Trimm INNER or OUTER.
References INNER, and OUTER.
TrimFacets()
void MeshTrimming::TrimFacets (const std::vector< unsigned long > & raulFacets, std::vector< MeshGeomFacet > & aclNewFacets)
The facets from raulFacets will be trimmed or deleted and aclNewFacets gives the new generated facets.
References Base::SequencerLauncher::next().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Trim.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Trim.cpp