FreeCAD: SMESH_HypoFilter Class Reference
SMESH_HypoFilter Class Reference
#include <SMESH_HypoFilter.hxx>
Classes
struct ApplicablePredicate
struct DimPredicate
struct InstancePredicate
struct IsAssignedToPredicate
struct IsAuxiliaryPredicate
struct IsMoreLocalThanPredicate
struct NamePredicate
struct templPredicate
struct TypePredicate
Public Member Functions
SMESH_HypoFilter & And (SMESH_HypoPredicate *aPredicate)
SMESH_HypoFilter & AndNot (SMESH_HypoPredicate *aPredicate)
SMESH_HypoFilter & Init (SMESH_HypoPredicate *aPredicate, bool notNegate=true)
bool IsAny () const
return true if contains no predicates
bool IsEmpty () const
bool IsOk (const SMESH_Hypothesis *aHyp, const TopoDS_Shape &aShape) const
check aHyp or/and aShape it is assigned to
SMESH_HypoFilter & Or (SMESH_HypoPredicate *aPredicate)
SMESH_HypoFilter & OrNot (SMESH_HypoPredicate *aPredicate)
SMESH_HypoFilter ()
SMESH_HypoFilter (SMESH_HypoPredicate *aPredicate, bool notNegate=true)
~SMESH_HypoFilter ()
Public Member Functions inherited from SMESH_HypoPredicate
virtual ~SMESH_HypoPredicate ()
Static Public Member Functions
static SMESH_HypoPredicate * HasDim (const int theDim)
static SMESH_HypoPredicate * HasName (const std::string &theName)
static SMESH_HypoPredicate * HasType (const int theHypType)
static SMESH_HypoPredicate * Is (const SMESH_Hypothesis *theHypo)
static SMESH_HypoPredicate * IsAlgo ()
static SMESH_HypoPredicate * IsApplicableTo (const TopoDS_Shape &theShape)
static SMESH_HypoPredicate * IsAssignedTo (const TopoDS_Shape &theShape)
static SMESH_HypoPredicate * IsAuxiliary ()
static SMESH_HypoPredicate * IsGlobal (const TopoDS_Shape &theMainShape)
static SMESH_HypoPredicate * IsMoreLocalThan (const TopoDS_Shape &theShape, const SMESH_Mesh &theMesh)
Protected Types
enum Comparison { EQUAL , NOT_EQUAL , MORE , LESS }
enum Logical { AND , AND_NOT , OR , OR_NOT }
Protected Member Functions
void add (Logical bool_op, SMESH_HypoPredicate *pred)
SMESH_HypoFilter (const SMESH_HypoFilter &other)
Protected Attributes
int myNbPredicates
SMESH_HypoPredicate * myPredicates [100]
Member Enumeration Documentation
Comparison
enum SMESH_HypoFilter::Comparison protected
Enumerator
EQUAL
NOT_EQUAL
MORE
LESS
Logical
enum SMESH_HypoFilter::Logical protected
Enumerator
AND
AND_NOT
OR
OR_NOT
Constructor & Destructor Documentation
SMESH_HypoFilter() [1/3]
SMESH_HypoFilter::SMESH_HypoFilter ()
SMESH_HypoFilter() [2/3]
SMESH_HypoFilter::SMESH_HypoFilter (SMESH_HypoPredicate * aPredicate, bool notNegate = true) explicit
References add(), AND, and AND_NOT.
~SMESH_HypoFilter()
SMESH_HypoFilter::~SMESH_HypoFilter ()
References myNbPredicates, and myPredicates.
SMESH_HypoFilter() [3/3]
SMESH_HypoFilter::SMESH_HypoFilter (const SMESH_HypoFilter & other) protected
Member Function Documentation
add()
void SMESH_HypoFilter::add (Logical bool_op, SMESH_HypoPredicate * pred) protected
Referenced by And(), AndNot(), Init(), Or(), OrNot(), and SMESH_HypoFilter().
And()
SMESH_HypoFilter & SMESH_HypoFilter::And (SMESH_HypoPredicate * aPredicate)
References add(), and AND.
Referenced by SMESH_subMesh::AlgoStateEngine(), SMESH_subMesh::getSimilarAttached(), and StdMeshers_ProjectionUtils::MakeComputed().
AndNot()
SMESH_HypoFilter & SMESH_HypoFilter::AndNot (SMESH_HypoPredicate * aPredicate)
References add(), and AND_NOT.
Referenced by SMESH_subMesh::AlgoStateEngine(), SMESH_Algo::GetCompatibleHypoFilter(), and SMESH_subMesh::getSimilarAttached().
HasDim()
SMESH_HypoPredicate * SMESH_HypoFilter::HasDim (const int theDim) static
References EQUAL.
Referenced by SMESH_subMesh::getSimilarAttached(), and StdMeshers_ProjectionUtils::MakeComputed().
HasName()
SMESH_HypoPredicate * SMESH_HypoFilter::HasName (const std::string & theName) static
Referenced by VISCOUS_2D::findHyps(), StdMeshers_Propagation::GetFilter(), SMESH_subMesh::getSimilarAttached(), StdMeshers_Regular_1D::getVertexHyp(), and SMESH_Mesh::IsNotConformAllowed().
HasType()
SMESH_HypoPredicate * SMESH_HypoFilter::HasType (const int theHypType) static
References EQUAL.
Referenced by SMESH_subMesh::AlgoStateEngine(), and SMESH_subMesh::getSimilarAttached().
Init()
SMESH_HypoFilter & SMESH_HypoFilter::Init (SMESH_HypoPredicate * aPredicate, bool notNegate = true)
References add(), AND, AND_NOT, myNbPredicates, and myPredicates.
Referenced by SMESH_subMesh::AlgoStateEngine(), and SMESH_subMesh::getSimilarAttached().
Is()
SMESH_HypoPredicate * SMESH_HypoFilter::Is (const SMESH_Hypothesis * theHypo) static
Referenced by SMESH_subMesh::AlgoStateEngine(), StdMeshers_Quadrangle_2D::getEnforcedUV(), SMESH_MesherHelper::GetShapeOfHypothesis(), SMESH_subMesh::getSimilarAttached(), and SMESH_Gen::IsGlobalHypothesis().
IsAlgo()
SMESH_HypoPredicate * SMESH_HypoFilter::IsAlgo () static
References MORE, and SMESHDS_Hypothesis::PARAM_ALGO.
Referenced by SMESH_subMesh::AlgoStateEngine(), SMESH_Gen::Compute(), SMESH_Gen::Evaluate(), SMESH_Gen::GetAlgo(), StdMeshers_ProjectionUtils::MakeComputed(), and StdMeshers_ProjectionUtils::SourceNotComputedError().
IsAny()
bool SMESH_HypoFilter::IsAny () const
return true if contains no predicates
IsApplicableTo()
SMESH_HypoPredicate * SMESH_HypoFilter::IsApplicableTo (const TopoDS_Shape & theShape) static
Referenced by SMESH_subMesh::AlgoStateEngine(), SMESH_Gen::Compute(), SMESH_Gen::Evaluate(), and SMESH_subMesh::getSimilarAttached().
IsAssignedTo()
SMESH_HypoPredicate * SMESH_HypoFilter::IsAssignedTo (const TopoDS_Shape & theShape) static
IsAuxiliary()
SMESH_HypoPredicate * SMESH_HypoFilter::IsAuxiliary () static
Referenced by SMESH_Algo::GetCompatibleHypoFilter(), SMESH_subMesh::getSimilarAttached(), and StdMeshers_Regular_1D::GetUsedHypothesis().
IsEmpty()
bool SMESH_HypoFilter::IsEmpty () const
Referenced by StdMeshers_Propagation::GetFilter(), and IsOk().
IsGlobal()
SMESH_HypoPredicate * SMESH_HypoFilter::IsGlobal (const TopoDS_Shape & theMainShape) static
IsMoreLocalThan()
SMESH_HypoPredicate * SMESH_HypoFilter::IsMoreLocalThan (const TopoDS_Shape & theShape, const SMESH_Mesh & theMesh) static
Referenced by SMESH_Gen::Compute(), and SMESH_Gen::Evaluate().
IsOk()
bool SMESH_HypoFilter::IsOk (const SMESH_Hypothesis * aHyp, const TopoDS_Shape & aShape) const virtual
check aHyp or/and aShape it is assigned to
Implements SMESH_HypoPredicate.
References AND, AND_NOT, IsEmpty(), SMESH_HypoPredicate::IsOk(), myNbPredicates, myPredicates, OR, and OR_NOT.
Referenced by StdMeshers_Regular_1D::CheckHypothesis(), SMESH_Mesh::GetHypotheses(), SMESH_Mesh::GetHypothesis(), and SMESH_Mesh::NotifySubMeshesHypothesisModification().
Or()
SMESH_HypoFilter & SMESH_HypoFilter::Or (SMESH_HypoPredicate * aPredicate)
References add(), and OR.
OrNot()
SMESH_HypoFilter & SMESH_HypoFilter::OrNot (SMESH_HypoPredicate * aPredicate)
References add(), and OR_NOT.
Member Data Documentation
myNbPredicates
int SMESH_HypoFilter::myNbPredicates protected
Referenced by Init(), IsOk(), and ~SMESH_HypoFilter().
myPredicates
SMESH_HypoPredicate* SMESH_HypoFilter::myPredicates[100] protected
Referenced by Init(), IsOk(), and ~SMESH_HypoFilter().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_HypoFilter.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/SMESH_HypoFilter.cpp