FreeCAD: SMESH::Controls::BareBorderFace Class Reference
SMESH::Controls::BareBorderFace Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
BareBorderFace ()
virtual SMDSAbs_ElementType GetType () const
virtual bool IsSatisfy (long theElementId)
virtual void SetMesh (const SMDS_Mesh *theMesh)
Public Member Functions inherited from SMESH::Controls::Functor
virtual ~Functor ()
Protected Attributes
std::vector< const SMDS_MeshNode * > myLinkNodes
const SMDS_Mesh * myMesh
Constructor & Destructor Documentation
BareBorderFace()
SMESH::Controls::BareBorderFace::BareBorderFace ()
Member Function Documentation
GetType()
virtual SMDSAbs_ElementType SMESH::Controls::BareBorderFace::GetType () const virtual
Implements SMESH::Controls::Predicate.
IsSatisfy()
bool BareBorderFace::IsSatisfy (long theElementId) virtual
Implements SMESH::Controls::Predicate.
References SMDS_Mesh::FindElement(), SMDS_MeshNode::GetInverseElementIterator(), SMDS_MeshElement::GetNode(), and SMESH::Controls::NumericalFunctor::myMesh.
SetMesh()
virtual void SMESH::Controls::BareBorderFace::SetMesh (const SMDS_Mesh * theMesh) virtual
Implements SMESH::Controls::Functor.
Member Data Documentation
myLinkNodes
std::vector< const SMDS_MeshNode* > SMESH::Controls::BareBorderFace::myLinkNodes protected
myMesh
const SMDS_Mesh* SMESH::Controls::BareBorderFace::myMesh protected
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp