FreeCAD: SMDS_MeshIDFactory Class Reference
SMDS_MeshIDFactory Class Reference
#include <SMDS_MeshIDFactory.hxx>
Public Member Functions
void adjustMaxId (int ID)
virtual void Clear ()
virtual void emptyPool (int maxId)
int GetFreeID ()
SMDS_Mesh * GetMesh ()
bool isPoolIdEmpty ()
virtual void ReleaseID (int ID, int vtkId=-1)
void SetMesh (SMDS_Mesh *mesh)
Public Member Functions inherited from SMDS_MeshObject
virtual ~SMDS_MeshObject ()
Protected Member Functions
SMDS_MeshIDFactory ()
Protected Attributes
int myMaxID
SMDS_Mesh * myMesh
std::set< int > myPoolOfID
Constructor & Destructor Documentation
SMDS_MeshIDFactory()
SMDS_MeshIDFactory::SMDS_MeshIDFactory () protected
Member Function Documentation
adjustMaxId()
void SMDS_MeshIDFactory::adjustMaxId (int ID)
Referenced by SMDS_Mesh::AddNodeWithID().
Clear()
void SMDS_MeshIDFactory::Clear () virtual
Reimplemented in SMDS_MeshNodeIDFactory, and SMDS_MeshElementIDFactory.
References myMaxID, and myPoolOfID.
Referenced by SMDS_MeshElementIDFactory::Clear(), and SMDS_MeshNodeIDFactory::Clear().
emptyPool()
void SMDS_MeshIDFactory::emptyPool (int maxId) virtual
Reimplemented in SMDS_MeshNodeIDFactory.
References myMaxID, and myPoolOfID.
Referenced by SMDS_MeshNodeIDFactory::emptyPool().
GetFreeID()
int SMDS_MeshIDFactory::GetFreeID ()
References myMaxID, and myPoolOfID.
Referenced by SMDS_MeshElementIDFactory::GetFreeID(), and SMDS_MeshNodeIDFactory::GetFreeID().
GetMesh()
SMDS_Mesh * SMDS_MeshIDFactory::GetMesh ()
References myMesh.
Referenced by SMDS_MeshElementIDFactory::MeshElement(), and SMDS_MeshNodeIDFactory::MeshElement().
isPoolIdEmpty()
bool SMDS_MeshIDFactory::isPoolIdEmpty ()
ReleaseID()
void SMDS_MeshIDFactory::ReleaseID (int ID, int vtkId = -1) virtual
Reimplemented in SMDS_MeshNodeIDFactory, and SMDS_MeshElementIDFactory.
References myMaxID, and myPoolOfID.
Referenced by SMDS_MeshElementIDFactory::ReleaseID(), and SMDS_MeshNodeIDFactory::ReleaseID().
SetMesh()
void SMDS_MeshIDFactory::SetMesh (SMDS_Mesh * mesh)
References myMesh.
Referenced by SMDS_Mesh::SMDS_Mesh().
Member Data Documentation
myMaxID
int SMDS_MeshIDFactory::myMaxID protected
Referenced by Clear(), emptyPool(), GetFreeID(), and ReleaseID().
myMesh
SMDS_Mesh* SMDS_MeshIDFactory::myMesh protected
Referenced by SMDS_MeshElementIDFactory::BindID(), SMDS_MeshElementIDFactory::Clear(), SMDS_MeshElementIDFactory::elementsIterator(), SMDS_MeshNodeIDFactory::elementsIterator(), GetMesh(), SMDS_MeshElementIDFactory::MeshElement(), SMDS_MeshElementIDFactory::ReleaseID(), SMDS_MeshNodeIDFactory::ReleaseID(), SMDS_MeshElementIDFactory::SetInVtkGrid(), SetMesh(), SMDS_MeshElementIDFactory::updateMinMax(), and SMDS_MeshNodeIDFactory::updateMinMax().
myPoolOfID
std::set<int> SMDS_MeshIDFactory::myPoolOfID protected
Referenced by Clear(), emptyPool(), GetFreeID(), and ReleaseID().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_MeshIDFactory.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_MeshIDFactory.cpp