FreeCAD: Prism_3D::TNode Struct Reference
Prism_3D::TNode Struct Reference
Structure containing node relative data.
#include <StdMeshers_Prism_3D.hxx>
Public Member Functions
gp_XYZ & ChangeParams () const
gp_XYZ GetCoords () const
gp_XYZ GetParams () const
SMDS_TypeOfPosition GetPositionType () const
bool HasParams () const
bool IsNeighbor (const TNode &other) const
Return true if this node and other one belong to one face.
bool operator< (const TNode &other) const
TNode (const SMDS_MeshNode *node=0)
Public Attributes
const SMDS_MeshNode * myNode
gp_XYZ myParams
Detailed Description
Structure containing node relative data.
Constructor & Destructor Documentation
TNode()
Prism_3D::TNode::TNode (const SMDS_MeshNode * node = 0)
Member Function Documentation
ChangeParams()
gp_XYZ& Prism_3D::TNode::ChangeParams () const
References myParams.
GetCoords()
gp_XYZ Prism_3D::TNode::GetCoords () const
References myNode, SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
GetParams()
gp_XYZ Prism_3D::TNode::GetParams () const
References myParams.
GetPositionType()
SMDS_TypeOfPosition Prism_3D::TNode::GetPositionType () const
References SMDS_MeshNode::GetPosition(), SMDS_Position::GetTypeOfPosition(), and myNode.
HasParams()
bool Prism_3D::TNode::HasParams () const
References myParams.
IsNeighbor()
bool Prism_3D::TNode::IsNeighbor (const TNode & other) const
Return true if this node and other one belong to one face.
References SMDS_MeshNode::GetInverseElementIterator(), and myNode.
operator<()
bool Prism_3D::TNode::operator< (const TNode & other) const
References SMDS_MeshElement::GetID(), and myNode.
Member Data Documentation
myNode
const SMDS_MeshNode* Prism_3D::TNode::myNode
Referenced by GetCoords(), GetPositionType(), IsNeighbor(), and operator<().
myParams
gp_XYZ Prism_3D::TNode::myParams mutable
Referenced by ChangeParams(), GetParams(), and HasParams().
The documentation for this struct was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_Prism_3D.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_Prism_3D.cpp