FreeCAD: MeshCore::QuasiDelaunayTriangulator Class Reference
MeshCore::QuasiDelaunayTriangulator Class Reference
#include <Triangulation.h>
Public Member Functions
QuasiDelaunayTriangulator ()
~QuasiDelaunayTriangulator ()
Public Member Functions inherited from MeshCore::EarClippingTriangulator
EarClippingTriangulator ()
~EarClippingTriangulator ()
Public Member Functions inherited from MeshCore::AbstractPolygonTriangulator
AbstractPolygonTriangulator ()
std::vector< Base::Vector3f > AddedPoints () const
The triangulation algorithm may create new points when calling Triangulate().
virtual void Discard ()
const std::vector< MeshFacet > & GetFacets () const
Returns the topologic facets of the polygon.
std::vector< unsigned long > GetInfo () const
Get information about the polygons that were processed.
float GetLength () const
Returns the length of the polygon.
std::vector< Base::Vector3f > GetPolygon () const
Get the polygon points to be triangulated.
Base::Matrix4D GetTransformToFitPlane () const
Computes the best-fit plane and returns a transformation matrix built out of the axes of the plane.
virtual MeshGeomFacet GetTriangle (const MeshPointArray &, const MeshFacet &) const
Returns the triangle to a given topologic facet.
const std::vector< MeshGeomFacet > & GetTriangles () const
Returns the geometric triangles of the polygon.
TriangulationVerifier * GetVerifier () const
virtual bool NeedsReindexing () const
Usually the created faces use the indices of the polygon points from [0, n].
virtual void PostProcessing (const std::vector< Base::Vector3f > &)
If points were added then we get the 3D points by projecting the added 2D points onto a surface which fits into the given points.
std::vector< Base::Vector3f > ProjectToFitPlane ()
If the points of the polygon set by SetPolygon() doesn't lie in a plane this method can be used to project the points in a common plane.
virtual void Reset ()
Resets some internals.
void SetIndices (const std::vector< unsigned long > &d)
void SetPolygon (const std::vector< Base::Vector3f > &raclPoints)
Sets the polygon to be triangulated.
void SetVerifier (TriangulationVerifier *v)
Set a verifier object that checks if the generated triangulation can be accepted and added to the mesh kernel.
bool TriangulatePolygon ()
Computes the triangulation of a polygon.
virtual ~AbstractPolygonTriangulator ()
Protected Member Functions
bool Triangulate ()
Computes the triangulation of a polygon.
Protected Member Functions inherited from MeshCore::AbstractPolygonTriangulator
void Done ()
Constructor & Destructor Documentation
QuasiDelaunayTriangulator()
QuasiDelaunayTriangulator::QuasiDelaunayTriangulator ()
~QuasiDelaunayTriangulator()
QuasiDelaunayTriangulator::~QuasiDelaunayTriangulator ()
Member Function Documentation
Triangulate()
bool QuasiDelaunayTriangulator::Triangulate () protected virtual
Computes the triangulation of a polygon.
The resulting facets can be accessed by GetTriangles() or GetFacets().
Reimplemented from MeshCore::EarClippingTriangulator.
References MeshCore::MeshGeomFacet::MaximumAngle(), MeshCore::MeshFacet::Side(), and MeshCore::EarClippingTriangulator::Triangulate().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Triangulation.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Triangulation.cpp