FreeCAD: SMESH::Controls::OverConstrainedVolume Class Reference
SMESH::Controls::OverConstrainedVolume Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
virtual SMDSAbs_ElementType GetType () const
virtual bool IsSatisfy (long theElementId)
OverConstrainedVolume ()
virtual void SetMesh (const SMDS_Mesh *theMesh)
virtual SMDSAbs_ElementType GetType () const =0
virtual bool IsSatisfy (long theElementId)=0
Public Member Functions inherited from SMESH::Controls::Functor
virtual SMDSAbs_ElementType GetType () const =0
virtual void SetMesh (const SMDS_Mesh *theMesh)=0
virtual ~Functor ()
Protected Attributes
const SMDS_Mesh * myMesh
Constructor & Destructor Documentation
OverConstrainedVolume()
SMESH::Controls::OverConstrainedVolume::OverConstrainedVolume ()
Member Function Documentation
GetType()
virtual SMDSAbs_ElementType SMESH::Controls::OverConstrainedVolume::GetType () const virtual
Implements SMESH::Controls::Predicate.
IsSatisfy()
bool OverConstrainedVolume::IsSatisfy (long theElementId) virtual
Implements SMESH::Controls::Predicate.
References SMDS_Mesh::FindElement(), SMDS_VolumeTool::IsFreeFace(), SMESH::Controls::NumericalFunctor::myMesh, SMDS_VolumeTool::NbFaces(), and SMDS_VolumeTool::Set().
SetMesh()
virtual void SMESH::Controls::OverConstrainedVolume::SetMesh (const SMDS_Mesh * theMesh) virtual
Implements SMESH::Controls::Functor.
Member Data Documentation
myMesh
const SMDS_Mesh* SMESH::Controls::OverConstrainedVolume::myMesh protected
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp