FreeCAD: SMDS_MeshInfo Class Reference
SMDS_MeshInfo Class Reference
#include <SMDS_MeshInfo.hxx>
Public Member Functions
void Clear ()
int Nb0DElements () const
int NbBalls () const
int NbBiQuadQuadrangles () const
int NbBiQuadTriangles () const
int NbEdges (SMDSAbs_ElementOrder order=ORDER_ANY) const
int NbElements (SMDSAbs_ElementType type=SMDSAbs_All) const
int NbElements (SMDSAbs_EntityType type) const
int NbElements (SMDSAbs_GeometryType type) const
int NbElementsOfGeom (SMDSAbs_GeometryType geom) const
int NbEntities (SMDSAbs_EntityType type) const
int NbFaces (SMDSAbs_ElementOrder order=ORDER_ANY) const
int NbHexas (SMDSAbs_ElementOrder order=ORDER_ANY) const
int NbHexPrisms (SMDSAbs_ElementOrder order=ORDER_ANY) const
int NbNodes () const
int NbPolygons (SMDSAbs_ElementOrder order=ORDER_ANY) const
int NbPolyhedrons () const
int NbPrisms (SMDSAbs_ElementOrder order=ORDER_ANY) const
int NbPyramids (SMDSAbs_ElementOrder order=ORDER_ANY) const
int NbQuadrangles (SMDSAbs_ElementOrder order=ORDER_ANY) const
int NbTetras (SMDSAbs_ElementOrder order=ORDER_ANY) const
int NbTriangles (SMDSAbs_ElementOrder order=ORDER_ANY) const
int NbTriQuadHexas () const
int NbVolumes (SMDSAbs_ElementOrder order=ORDER_ANY) const
SMDS_MeshInfo & operator= (const SMDS_MeshInfo &other)
SMDS_MeshInfo ()
Protected Member Functions
void addWithPoly (const SMDS_MeshElement *el)
void setNb (const SMDSAbs_EntityType geomType, const int nb)
Friends
class SMDS_Mesh
Constructor & Destructor Documentation
SMDS_MeshInfo()
SMDS_MeshInfo::SMDS_MeshInfo ()
Member Function Documentation
addWithPoly()
void SMDS_MeshInfo::addWithPoly (const SMDS_MeshElement * el) protected
References SMDS_MeshElement::GetEntityType().
Clear()
void SMDS_MeshInfo::Clear ()
Referenced by SMDS_Mesh::Clear().
Nb0DElements()
int SMDS_MeshInfo::Nb0DElements () const
Referenced by SMDS_Mesh::Nb0DElements(), and DriverMED_W_SMESHDS_Mesh::Perform().
NbBalls()
int SMDS_MeshInfo::NbBalls () const
Referenced by SMDS_Mesh::NbBalls(), and DriverMED_W_SMESHDS_Mesh::Perform().
NbBiQuadQuadrangles()
int SMDS_MeshInfo::NbBiQuadQuadrangles () const
Referenced by DriverMED_W_SMESHDS_Mesh::Perform().
NbBiQuadTriangles()
int SMDS_MeshInfo::NbBiQuadTriangles () const
Referenced by DriverMED_W_SMESHDS_Mesh::Perform().
NbEdges()
int SMDS_MeshInfo::NbEdges (SMDSAbs_ElementOrder order = ORDER_ANY) const
Referenced by SMDS_Mesh::NbEdges(), and DriverMED_W_SMESHDS_Mesh::Perform().
NbElements() [1/3]
int SMDS_MeshInfo::NbElements (SMDSAbs_ElementType type = SMDSAbs_All) const
Referenced by SMESHDS_GroupOnFilter::GetElements(), SMESH::Controls::NumericalFunctor::GetHistogram(), SMESH_ElementSearcherImpl::getTolerance(), SMESH::Controls::ConnectedElements::IsSatisfy(), and DriverGMF_Read::Perform().
NbElements() [2/3]
int SMDS_MeshInfo::NbElements (SMDSAbs_EntityType type) const
NbElements() [3/3]
int SMDS_MeshInfo::NbElements (SMDSAbs_GeometryType type) const
NbElementsOfGeom()
int SMDS_MeshInfo::NbElementsOfGeom (SMDSAbs_GeometryType geom) const
NbEntities()
int SMDS_MeshInfo::NbEntities (SMDSAbs_EntityType type) const
Referenced by StdMeshers_Import_1D::Evaluate(), StdMeshers_Import_1D2D::Evaluate(), and SMESH_ProxyMesh::NbFaces().
NbFaces()
int SMDS_MeshInfo::NbFaces (SMDSAbs_ElementOrder order = ORDER_ANY) const
References NbQuadrangles(), and NbTriangles().
Referenced by SMESH_Pattern::Load(), and SMDS_Mesh::NbFaces().
NbHexas()
int SMDS_MeshInfo::NbHexas (SMDSAbs_ElementOrder order = ORDER_ANY) const
Referenced by SMDS_UnstructuredGrid::BuildDownwardConnectivity(), NbVolumes(), and DriverMED_W_SMESHDS_Mesh::Perform().
NbHexPrisms()
int SMDS_MeshInfo::NbHexPrisms (SMDSAbs_ElementOrder order = ORDER_ANY) const
Referenced by SMDS_UnstructuredGrid::BuildDownwardConnectivity(), NbVolumes(), and DriverMED_W_SMESHDS_Mesh::Perform().
NbNodes()
int SMDS_MeshInfo::NbNodes () const
Referenced by SMESH_ElementSearcherImpl::getTolerance(), SMDS_Mesh::NbNodes(), and DriverGMF_Read::Perform().
NbPolygons()
int SMDS_MeshInfo::NbPolygons (SMDSAbs_ElementOrder order = ORDER_ANY) const
Referenced by DriverMED_W_SMESHDS_Mesh::Perform().
NbPolyhedrons()
int SMDS_MeshInfo::NbPolyhedrons () const
Referenced by DriverMED_W_SMESHDS_Mesh::Perform().
NbPrisms()
int SMDS_MeshInfo::NbPrisms (SMDSAbs_ElementOrder order = ORDER_ANY) const
Referenced by SMDS_UnstructuredGrid::BuildDownwardConnectivity(), NbVolumes(), and DriverMED_W_SMESHDS_Mesh::Perform().
NbPyramids()
int SMDS_MeshInfo::NbPyramids (SMDSAbs_ElementOrder order = ORDER_ANY) const
Referenced by SMDS_UnstructuredGrid::BuildDownwardConnectivity(), NbVolumes(), and DriverMED_W_SMESHDS_Mesh::Perform().
NbQuadrangles()
int SMDS_MeshInfo::NbQuadrangles (SMDSAbs_ElementOrder order = ORDER_ANY) const
Referenced by NbFaces(), and DriverMED_W_SMESHDS_Mesh::Perform().
NbTetras()
int SMDS_MeshInfo::NbTetras (SMDSAbs_ElementOrder order = ORDER_ANY) const
Referenced by SMDS_UnstructuredGrid::BuildDownwardConnectivity(), NbVolumes(), and DriverMED_W_SMESHDS_Mesh::Perform().
NbTriangles()
int SMDS_MeshInfo::NbTriangles (SMDSAbs_ElementOrder order = ORDER_ANY) const
Referenced by NbFaces(), and DriverMED_W_SMESHDS_Mesh::Perform().
NbTriQuadHexas()
int SMDS_MeshInfo::NbTriQuadHexas () const
Referenced by DriverMED_W_SMESHDS_Mesh::Perform().
NbVolumes()
int SMDS_MeshInfo::NbVolumes (SMDSAbs_ElementOrder order = ORDER_ANY) const
References NbHexas(), NbHexPrisms(), NbPrisms(), NbPyramids(), and NbTetras().
Referenced by SMDS_Mesh::NbVolumes().
operator=()
SMDS_MeshInfo & SMDS_MeshInfo::operator= (const SMDS_MeshInfo & other)
setNb()
void SMDS_MeshInfo::setNb (const SMDSAbs_EntityType geomType, const int nb) protected
References draftgeoutils.general::geomType().
Friends And Related Function Documentation
SMDS_Mesh
friend class SMDS_Mesh friend
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_MeshInfo.hxx