FreeCAD: SMESH::Controls::ElementsOnSurface Class Reference
SMESH::Controls::ElementsOnSurface Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
ElementsOnSurface ()
double GetTolerance () const
virtual SMDSAbs_ElementType GetType () const
bool GetUseBoundaries () const
virtual bool IsSatisfy (long theElementId)
virtual void SetMesh (const SMDS_Mesh *theMesh)
void SetSurface (const TopoDS_Shape &theShape, const SMDSAbs_ElementType theType)
void SetTolerance (const double theToler)
void SetUseBoundaries (bool theUse)
~ElementsOnSurface ()
Public Member Functions inherited from SMESH::Controls::Functor
~Functor ()
Constructor & Destructor Documentation
ElementsOnSurface()
ElementsOnSurface::ElementsOnSurface ()
~ElementsOnSurface()
ElementsOnSurface::~ElementsOnSurface ()
Member Function Documentation
GetTolerance()
double ElementsOnSurface::GetTolerance () const
GetType()
SMDSAbs_ElementType ElementsOnSurface::GetType () const virtual
Implements SMESH::Controls::Predicate.
GetUseBoundaries()
bool SMESH::Controls::ElementsOnSurface::GetUseBoundaries () const
IsSatisfy()
bool ElementsOnSurface::IsSatisfy (long theElementId) virtual
Implements SMESH::Controls::Predicate.
SetMesh()
void ElementsOnSurface::SetMesh (const SMDS_Mesh * theMesh) virtual
Implements SMESH::Controls::Functor.
References SMESH::Controls::TMeshModifTracer::IsMeshModified(), and SMESH::Controls::TMeshModifTracer::SetMesh().
SetSurface()
void ElementsOnSurface::SetSurface (const TopoDS_Shape & theShape, const SMDSAbs_ElementType theType)
Referenced by SetUseBoundaries().
SetTolerance()
void ElementsOnSurface::SetTolerance (const double theToler)
SetUseBoundaries()
void ElementsOnSurface::SetUseBoundaries (bool theUse)
References SetSurface().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp