FreeCAD: PartGui::FilletRadiusModel Class Reference
PartGui::FilletRadiusModel Class Reference
#include <DlgFilletEdges.h>
Signals
void toggleCheckState (const QModelIndex &)
Public Member Functions
QVariant data (const QModelIndex &, int role=Qt::DisplayRole) const
FilletRadiusModel (QObject *parent=0)
Qt::ItemFlags flags (const QModelIndex &index) const
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
void updateCheckStates ()
Constructor & Destructor Documentation
FilletRadiusModel()
FilletRadiusModel::FilletRadiusModel (QObject * parent = 0)
Member Function Documentation
data()
QVariant FilletRadiusModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
Referenced by Mod.Show.mTempoVis.TempoVis::activateWorkbench(), Mod.Show.SceneDetail.SceneDetail::apply_data(), importIFClegacy.IfcSchema::capitalize(), Mod.Show.mTempoVis.TempoVis::forget(), Mod.Show.mTempoVis.TempoVis::forgetDetail(), Mod.Show.mTempoVis.TempoVis::has(), ArchSchedule.CommandArchSchedule::IsActive(), importIFClegacy.IfcSchema::readEntities(), importIFClegacy.IfcSchema::readTypes(), Mod.Show.mTempoVis.TempoVis::restore(), Mod.Show.mTempoVis.TempoVis::save(), Mod.Show.mTempoVis.TempoVis::stored_val(), FeaturePython.ViewProviderOctahedron::updateData(), and Dice3DS.dom3ds.UndefinedChunk::write().
flags()
Qt::ItemFlags FilletRadiusModel::flags (const QModelIndex & index) const
setData()
bool FilletRadiusModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole)
References toggleCheckState().
toggleCheckState
void PartGui::FilletRadiusModel::toggleCheckState (const QModelIndex &) signal
Referenced by setData().
updateCheckStates()
void FilletRadiusModel::updateCheckStates ()
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/Gui/DlgFilletEdges.h
Sources/FreeCAD/src/Mod/Part/Gui/DlgFilletEdges.cpp