FreeCAD: Base::PlacementPy Class Reference
Base::PlacementPy Class Reference
The python export class for Placement.
#include <PlacementPy.h>
Public Types
typedef Placement * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
PlacementPy (Placement *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
additional declarations and methods for the wrapper class
PlacementPy (const Placement &pla, PyTypeObject *T=&Type)
Placement value () const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * richCompare (PyObject *v, PyObject *w, int op)
callbacks and implementers for the python object number protocol
static PyObject * number_add_handler (PyObject *self, PyObject *other)
callback for the number_add_handler
static PyObject * number_subtract_handler (PyObject *self, PyObject *other)
callback for the number_subtract_handler
static PyObject * number_multiply_handler (PyObject *self, PyObject *other)
callback for the number_multiply_handler
static PyObject * number_divide_handler (PyObject *self, PyObject *other)
callback for the number_divide_handler
static PyObject * number_remainder_handler (PyObject *self, PyObject *other)
callback for the number_remainder_handler
static PyObject * number_divmod_handler (PyObject *self, PyObject *other)
callback for the number_divmod_handler
static PyObject * number_power_handler (PyObject *self, PyObject *other, PyObject *modulo)
callback for the number_power_handler
static PyObject * number_negative_handler (PyObject *self)
callback for the number_negative_handler
static PyObject * number_positive_handler (PyObject *self)
callback for the number_positive_handler
static PyObject * number_absolute_handler (PyObject *self)
callback for the number_absolute_handler
static int number_nonzero_handler (PyObject *self)
callback for the number_nonzero_handler
static PyObject * number_invert_handler (PyObject *self)
callback for the number_invert_handler
static PyObject * number_lshift_handler (PyObject *self, PyObject *other)
callback for the number_lshift_handler
static PyObject * number_rshift_handler (PyObject *self, PyObject *other)
callback for the number_rshift_handler
static PyObject * number_and_handler (PyObject *self, PyObject *other)
callback for the number_and_handler
static PyObject * number_xor_handler (PyObject *self, PyObject *other)
callback for the number_xor_handler
static PyObject * number_or_handler (PyObject *self, PyObject *other)
callback for the number_or_handler
static int number_coerce_handler (PyObject **self, PyObject **other)
callback for the number_coerce_handler
static PyObject * number_int_handler (PyObject *self)
callback for the number_int_handler
static PyObject * number_long_handler (PyObject *self)
callback for the number_long_handler
static PyObject * number_float_handler (PyObject *self)
callback for the number_float_handler
static PyObject * number_oct_handler (PyObject *self)
callback for the number_oct_handler
static PyObject * number_hex_handler (PyObject *self)
callback for the number_hex_handler
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of PlacementPy.
static PyMethodDef Methods []
Methods structure of PlacementPy.
static PyNumberMethods Number []
static PyTypeObject Type
Type structure of PlacementPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~PlacementPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_move (PyObject *self, PyObject *args)
callback for the move() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_multiply (PyObject *self, PyObject *args)
callback for the multiply() method
static PyObject * staticCallback_multVec (PyObject *self, PyObject *args)
callback for the multVec() method
static PyObject * staticCallback_toMatrix (PyObject *self, PyObject *args)
callback for the toMatrix() method
static PyObject * staticCallback_inverse (PyObject *self, PyObject *args)
callback for the inverse() method
static PyObject * staticCallback_pow (PyObject *self, PyObject *args)
callback for the pow() method
static PyObject * staticCallback_sclerp (PyObject *self, PyObject *args)
callback for the sclerp() method
static PyObject * staticCallback_slerp (PyObject *self, PyObject *args)
callback for the slerp() method
static PyObject * staticCallback_isIdentity (PyObject *self, PyObject *args)
callback for the isIdentity() method
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * move (PyObject *args)
implementer for the move() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * multiply (PyObject *args)
implementer for the multiply() method
PyObject * multVec (PyObject *args)
implementer for the multVec() method
PyObject * toMatrix (PyObject *args)
implementer for the toMatrix() method
PyObject * inverse (PyObject *args)
implementer for the inverse() method
PyObject * pow (PyObject *args)
implementer for the pow() method
PyObject * sclerp (PyObject *args)
implementer for the sclerp() method
PyObject * slerp (PyObject *args)
implementer for the slerp() method
PyObject * isIdentity (PyObject *args)
implementer for the isIdentity() method
callbacks and implementers for the python object attributes
static PyObject * staticCallback_getBase (PyObject *self, void *closure)
getter callback for the Base attribute
static int staticCallback_setBase (PyObject *self, PyObject *value, void *closure)
setter callback for the Base attribute
static PyObject * staticCallback_getRotation (PyObject *self, void *closure)
getter callback for the Rotation attribute
static int staticCallback_setRotation (PyObject *self, PyObject *value, void *closure)
setter callback for the Rotation attribute
static PyObject * staticCallback_getMatrix (PyObject *self, void *closure)
getter callback for the Matrix attribute
static int staticCallback_setMatrix (PyObject *self, PyObject *value, void *closure)
setter callback for the Matrix attribute
Py::Object getBase (void) const
getter for the Base attribute
void setBase (Py::Object arg)
setter for the Base attribute
Py::Object getRotation (void) const
getter for the Rotation attribute
void setRotation (Py::Object arg)
setter for the Rotation attribute
Py::Object getMatrix (void) const
getter for the Matrix attribute
void setMatrix (Py::Object arg)
setter for the Matrix attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Placement * getPlacementPtr (void) const
getter for the object handled by this class
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Placement.
Member Typedef Documentation
PointerType
typedef Placement* Base::PlacementPy::PointerType
Constructor & Destructor Documentation
~PlacementPy()
PlacementPy::~PlacementPy () protected
PlacementPy() [1/2]
PlacementPy::PlacementPy (Placement * pcObject, PyTypeObject * T = &Type)
Referenced by copy(), inverse(), multiply(), number_multiply_handler(), number_power_handler(), pow(), PyMake(), sclerp(), and slerp().
PlacementPy() [2/2]
Base::PlacementPy::PlacementPy (const Placement & pla, PyTypeObject * T = &Type)
Member Function Documentation
copy()
PyObject * PlacementPy::copy (PyObject * args)
implementer for the copy() method
References getPlacementPtr(), and PlacementPy().
Referenced by staticCallback_copy().
getBase()
Py::Object PlacementPy::getBase (void) const
getter for the Base attribute
References getPlacementPtr().
Referenced by staticCallback_getBase().
getCustomAttributes()
PyObject * PlacementPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getMatrix()
Py::Object PlacementPy::getMatrix (void) const
getter for the Matrix attribute
References getPlacementPtr(), and toMatrix().
Referenced by staticCallback_getMatrix().
getPlacementPtr()
Placement * PlacementPy::getPlacementPtr (void) const
getter for the object handled by this class
Referenced by copy(), getBase(), getMatrix(), getRotation(), inverse(), isIdentity(), move(), Base::AxisPy::multiply(), multiply(), multVec(), pow(), PyInit(), richCompare(), rotate(), sclerp(), Attacher::AttachEnginePy::setAttachmentOffset(), setBase(), Gui::ViewProviderLinkPy::setDraggingPlacement(), setMatrix(), Fem::PropertyFemMesh::setPyObject(), setRotation(), Robot::Robot6AxisPy::setTcp(), Gui::ViewProviderPy::setTransformation(), slerp(), and toMatrix().
getRotation()
Py::Object PlacementPy::getRotation (void) const
getter for the Rotation attribute
References getPlacementPtr().
Referenced by staticCallback_getRotation().
GetType()
virtual PyTypeObject* Base::PlacementPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
inverse()
PyObject * PlacementPy::inverse (PyObject * args)
implementer for the inverse() method
References getPlacementPtr(), Base::Placement::inverse(), and PlacementPy().
Referenced by staticCallback_inverse().
isIdentity()
PyObject * PlacementPy::isIdentity (PyObject * args)
implementer for the isIdentity() method
References getPlacementPtr(), and Base::Placement::isIdentity().
Referenced by ArchComponent.Component::applyShape(), ArchComponent.Component::getExtrusionData(), ArchComponent.Component::processSubShapes(), and staticCallback_isIdentity().
move()
PyObject * PlacementPy::move (PyObject * args)
implementer for the move() method
References getPlacementPtr(), Base::Placement::move(), Base::VectorPy::Type, value(), and draftgeoutils.general::vec().
Referenced by draftguitools.gui_circulararray.CircularArray::Activated(), draftguitools.gui_polararray.PolarArray::Activated(), staticCallback_move(), and translate().
multiply()
PyObject * PlacementPy::multiply (PyObject * args)
implementer for the multiply() method
References getPlacementPtr(), PlacementPy(), and Type.
Referenced by PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart(), and staticCallback_multiply().
multVec()
PyObject * PlacementPy::multVec (PyObject * args)
implementer for the multVec() method
References getPlacementPtr(), Base::Placement::multVec(), Base::VectorPy::Type, value(), and draftgeoutils.general::vec().
Referenced by staticCallback_multVec().
number_absolute_handler()
PyObject * PlacementPy::number_absolute_handler (PyObject * self) static
callback for the number_absolute_handler
number_add_handler()
PyObject * PlacementPy::number_add_handler (PyObject * self, PyObject * other) static
callback for the number_add_handler
number_and_handler()
PyObject * PlacementPy::number_and_handler (PyObject * self, PyObject * other) static
callback for the number_and_handler
number_coerce_handler()
int PlacementPy::number_coerce_handler (PyObject ** self, PyObject ** other) static
callback for the number_coerce_handler
number_divide_handler()
PyObject * PlacementPy::number_divide_handler (PyObject * self, PyObject * other) static
callback for the number_divide_handler
number_divmod_handler()
PyObject * PlacementPy::number_divmod_handler (PyObject * self, PyObject * other) static
callback for the number_divmod_handler
number_float_handler()
PyObject * PlacementPy::number_float_handler (PyObject * self) static
callback for the number_float_handler
number_hex_handler()
PyObject * PlacementPy::number_hex_handler (PyObject * self) static
callback for the number_hex_handler
number_int_handler()
PyObject * PlacementPy::number_int_handler (PyObject * self) static
callback for the number_int_handler
number_invert_handler()
PyObject * PlacementPy::number_invert_handler (PyObject * self) static
callback for the number_invert_handler
number_long_handler()
PyObject * PlacementPy::number_long_handler (PyObject * self) static
callback for the number_long_handler
number_lshift_handler()
PyObject * PlacementPy::number_lshift_handler (PyObject * self, PyObject * other) static
callback for the number_lshift_handler
number_multiply_handler()
PyObject * PlacementPy::number_multiply_handler (PyObject * self, PyObject * other) static
callback for the number_multiply_handler
References PlacementPy(), Base::MatrixPy::Type, Type, Base::RotationPy::Type, Base::VectorPy::Type, value(), and Base::VectorPy::value().
number_negative_handler()
PyObject * PlacementPy::number_negative_handler (PyObject * self) static
callback for the number_negative_handler
number_nonzero_handler()
int PlacementPy::number_nonzero_handler (PyObject * self) static
callback for the number_nonzero_handler
number_oct_handler()
PyObject * PlacementPy::number_oct_handler (PyObject * self) static
callback for the number_oct_handler
number_or_handler()
PyObject * PlacementPy::number_or_handler (PyObject * self, PyObject * other) static
callback for the number_or_handler
number_positive_handler()
PyObject * PlacementPy::number_positive_handler (PyObject * self) static
callback for the number_positive_handler
number_power_handler()
PyObject * PlacementPy::number_power_handler (PyObject * self, PyObject * other, PyObject * modulo) static
callback for the number_power_handler
References PlacementPy(), DraftVecUtils::tup(), Type, and value().
number_remainder_handler()
PyObject * PlacementPy::number_remainder_handler (PyObject * self, PyObject * other) static
callback for the number_remainder_handler
number_rshift_handler()
PyObject * PlacementPy::number_rshift_handler (PyObject * self, PyObject * other) static
callback for the number_rshift_handler
number_subtract_handler()
PyObject * PlacementPy::number_subtract_handler (PyObject * self, PyObject * other) static
callback for the number_subtract_handler
number_xor_handler()
PyObject * PlacementPy::number_xor_handler (PyObject * self, PyObject * other) static
callback for the number_xor_handler
pow()
PyObject * PlacementPy::pow (PyObject * args)
implementer for the pow() method
References getPlacementPtr(), PlacementPy(), and Base::Placement::pow().
Referenced by staticCallback_pow().
PyInit()
int PlacementPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
References DraftVecUtils::angle(), Base::BaseExceptionFreeCADError, Base::Placement::fromMatrix(), getPlacementPtr(), Base::Placement::setPosition(), Base::Placement::setRotation(), Base::MatrixPy::Type, Type, Base::RotationPy::Type, Base::VectorPy::Type, and value().
PyMake()
PyObject * PlacementPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References PlacementPy().
representation()
std::string PlacementPy::representation (void) const
References Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Rotation::getYawPitchRoll(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
richCompare()
PyObject * PlacementPy::richCompare (PyObject * v, PyObject * w, int op) static
References getPlacementPtr(), and Type.
rotate()
PyObject * PlacementPy::rotate (PyObject * args)
implementer for the rotate() method
References DraftVecUtils::angle(), and getPlacementPtr().
Referenced by PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart(), draftguitools.gui_rotate.Rotate::numericRadius(), ArchSectionPlane.SectionPlaneTaskPanel::rotateX(), ArchSectionPlane.SectionPlaneTaskPanel::rotateY(), ArchSectionPlane.SectionPlaneTaskPanel::rotateZ(), and staticCallback_rotate().
sclerp()
PyObject * PlacementPy::sclerp (PyObject * args)
implementer for the sclerp() method
References getPlacementPtr(), PlacementPy(), Base::Placement::sclerp(), Type, and value().
Referenced by staticCallback_sclerp().
setBase()
void PlacementPy::setBase (Py::Object arg)
setter for the Base attribute
References getPlacementPtr(), Base::Placement::setPosition(), and Base::toVector().
Referenced by staticCallback_setBase().
setCustomAttributes()
int PlacementPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setMatrix()
void PlacementPy::setMatrix (Py::Object arg)
setter for the Matrix attribute
References Base::Placement::fromMatrix(), and getPlacementPtr().
Referenced by staticCallback_setMatrix().
setRotation()
void PlacementPy::setRotation (Py::Object arg)
setter for the Rotation attribute
References getPlacementPtr(), and Base::Placement::setRotation().
Referenced by staticCallback_setRotation().
slerp()
PyObject * PlacementPy::slerp (PyObject * args)
implementer for the slerp() method
References getPlacementPtr(), PlacementPy(), Base::Placement::slerp(), Type, and value().
Referenced by staticCallback_slerp().
staticCallback_copy()
PyObject * PlacementPy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copy(), and Base::PyObjectBase::isValid().
staticCallback_getBase()
PyObject * PlacementPy::staticCallback_getBase (PyObject * self, void * closure) static
getter callback for the Base attribute
References Base::BaseExceptionFreeCADError, getBase(), and Base::PyObjectBase::isValid().
staticCallback_getMatrix()
PyObject * PlacementPy::staticCallback_getMatrix (PyObject * self, void * closure) static
getter callback for the Matrix attribute
References Base::BaseExceptionFreeCADError, getMatrix(), and Base::PyObjectBase::isValid().
staticCallback_getRotation()
PyObject * PlacementPy::staticCallback_getRotation (PyObject * self, void * closure) static
getter callback for the Rotation attribute
References Base::BaseExceptionFreeCADError, getRotation(), and Base::PyObjectBase::isValid().
staticCallback_inverse()
PyObject * PlacementPy::staticCallback_inverse (PyObject * self, PyObject * args) static
callback for the inverse() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, inverse(), and Base::PyObjectBase::isValid().
staticCallback_isIdentity()
PyObject * PlacementPy::staticCallback_isIdentity (PyObject * self, PyObject * args) static
callback for the isIdentity() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isIdentity(), and Base::PyObjectBase::isValid().
staticCallback_move()
PyObject * PlacementPy::staticCallback_move (PyObject * self, PyObject * args) static
callback for the move() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), move(), and Base::PyObjectBase::startNotify().
staticCallback_multiply()
PyObject * PlacementPy::staticCallback_multiply (PyObject * self, PyObject * args) static
callback for the multiply() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and multiply().
staticCallback_multVec()
PyObject * PlacementPy::staticCallback_multVec (PyObject * self, PyObject * args) static
callback for the multVec() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and multVec().
staticCallback_pow()
PyObject * PlacementPy::staticCallback_pow (PyObject * self, PyObject * args) static
callback for the pow() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and pow().
staticCallback_rotate()
PyObject * PlacementPy::staticCallback_rotate (PyObject * self, PyObject * args) static
callback for the rotate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), rotate(), and Base::PyObjectBase::startNotify().
staticCallback_sclerp()
PyObject * PlacementPy::staticCallback_sclerp (PyObject * self, PyObject * args) static
callback for the sclerp() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and sclerp().
staticCallback_setBase()
int PlacementPy::staticCallback_setBase (PyObject * self, PyObject * value, void * closure) static
setter callback for the Base attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setBase().
staticCallback_setMatrix()
int PlacementPy::staticCallback_setMatrix (PyObject * self, PyObject * value, void * closure) static
setter callback for the Matrix attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setMatrix().
staticCallback_setRotation()
int PlacementPy::staticCallback_setRotation (PyObject * self, PyObject * value, void * closure) static
setter callback for the Rotation attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setRotation().
staticCallback_slerp()
PyObject * PlacementPy::staticCallback_slerp (PyObject * self, PyObject * args) static
callback for the slerp() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and slerp().
staticCallback_toMatrix()
PyObject * PlacementPy::staticCallback_toMatrix (PyObject * self, PyObject * args) static
callback for the toMatrix() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and toMatrix().
staticCallback_translate()
PyObject * PlacementPy::staticCallback_translate (PyObject * self, PyObject * args) static
callback for the translate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::startNotify(), and translate().
toMatrix()
PyObject * PlacementPy::toMatrix (PyObject * args)
implementer for the toMatrix() method
References getPlacementPtr(), and Base::Placement::toMatrix().
Referenced by getMatrix(), and staticCallback_toMatrix().
translate()
PyObject * PlacementPy::translate (PyObject * args)
implementer for the translate() method
References move().
Referenced by staticCallback_translate().
value()
Placement Base::PlacementPy::value () const
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), move(), multVec(), number_multiply_handler(), number_power_handler(), PyInit(), sclerp(), and slerp().
Member Data Documentation
GetterSetter
PyGetSetDef PlacementPy::GetterSetter static
Initial value:
= {
    {"Base",
        (getter) staticCallback_getBase,
        (setter) staticCallback_setBase,
        "Vector to the Base Position of the Placement",
        NULL
    },
    {"Rotation",
        (getter) staticCallback_getRotation,
        (setter) staticCallback_setRotation,
        "Orientation of the placement expressed as rotation",
        NULL
    },
    {"Matrix",
        (getter) staticCallback_getMatrix,
        (setter) staticCallback_setMatrix,
        "Set/get matrix representation of this placement",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of PlacementPy.
Methods
PyMethodDef PlacementPy::Methods static
Methods structure of PlacementPy.
Number
PyNumberMethods PlacementPy::Number static
Type
PyTypeObject PlacementPy::Type static
Type structure of PlacementPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), PathSimulator::PathSimPy::ApplyCommand(), ArchSite.Compass::buildCoordinates(), Attacher::AttachEnginePy::calculateAttachedPlacement(), App::FunctionExpression::evaluate(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), Gui::ViewProviderLink::initDraggingPlacement(), Robot::TrajectoryPy::insertWaypoints(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), Base::AxisPy::multiply(), multiply(), Base::MatrixPy::number_multiply_handler(), number_multiply_handler(), Base::RotationPy::number_multiply_handler(), number_power_handler(), PyInit(), Path::CommandPy::PyInit(), Robot::WaypointPy::PyInit(), richCompare(), Part::GeometryPy::rotate(), Sketcher::ExternalGeometryFacadePy::rotate(), Sketcher::GeometryFacadePy::rotate(), sclerp(), draftobjects.layer.Layer::set_properties(), Attacher::AttachEnginePy::setAttachmentOffset(), Gui::ViewProviderLinkPy::setDraggingPlacement(), Data::ComplexGeoDataPy::setPlacement(), Path::CommandPy::setPlacement(), Base::CoordinateSystemPy::setPlacement(), Robot::WaypointPy::setPos(), ArchReference.ArchReference::setProperties(), App::PropertyPlacement::setPyObject(), Fem::PropertyFemMesh::setPyObject(), Robot::Robot6AxisPy::setTcp(), Fem::FemMeshPy::setTransform(), Gui::ViewProviderPy::setTransformation(), slerp(), Gui::View3DInventorPy::toggleClippingPlane(), Base::CoordinateSystemPy::transform(), Path::CommandPy::transform(), and Gui::View3DInventorPy::viewPosition().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Base/PlacementPy.h
Sources/FreeCAD/src/Base/PlacementPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Base/PlacementPy.cpp