FreeCAD: MeshGui::DlgRegularSolidImp Class Reference
MeshGui::DlgRegularSolidImp Class Reference
#include <DlgRegularSolidImp.h>
Public Slots
void on_createSolidButton_clicked ()
Builds a mesh solid from the currently active solid type.
Public Member Functions
DlgRegularSolidImp (QWidget *parent=0, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgRegularSolidImp ()
Destroys the object and frees any allocated resources.
Protected Member Functions
void changeEvent (QEvent *e)
Constructor & Destructor Documentation
DlgRegularSolidImp()
DlgRegularSolidImp::DlgRegularSolidImp (QWidget * parent = 0, Qt::WindowFlags fl = Qt::WindowFlags())
References Gui::Command::Doc.
~DlgRegularSolidImp()
DlgRegularSolidImp::~DlgRegularSolidImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void DlgRegularSolidImp::changeEvent (QEvent * e) protected
on_createSolidButton_clicked
void DlgRegularSolidImp::on_createSolidButton_clicked () slot
Builds a mesh solid from the currently active solid type.
References Gui::Application::activeDocument(), Gui::Document::commitCommand(), Gui::Command::Doc, App::Application::getActiveDocument(), App::GetApplication(), Base::UnitsApi::getDecimals(), Gui::Command::Gui, Gui::Application::Instance, and Gui::Document::openCommand().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/Gui/DlgRegularSolidImp.h
Sources/FreeCAD/src/Mod/Mesh/Gui/DlgRegularSolidImp.cpp