FreeCAD: Gui::WorkbenchPy Class Reference
Gui::WorkbenchPy Class Reference
The python export class for Workbench.
#include <WorkbenchPy.h>
Public Types
typedef Workbench * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
WorkbenchPy (Workbench *pcObject, PyTypeObject *T=&Type)
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Workbench * getWorkbenchPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of WorkbenchPy.
static PyMethodDef Methods []
Methods structure of WorkbenchPy.
static PyTypeObject Type
Type structure of WorkbenchPy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~WorkbenchPy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * name (PyObject *args)
implementer for the name() method
PyObject * activate (PyObject *args)
implementer for the activate() method
PyObject * listToolbars (PyObject *args)
implementer for the listToolbars() method
PyObject * getToolbarItems (PyObject *args)
implementer for the getToolbarItems() method
PyObject * listCommandbars (PyObject *args)
implementer for the listCommandbars() method
PyObject * listMenus (PyObject *args)
implementer for the listMenus() method
static PyObject * staticCallback_name (PyObject *self, PyObject *args)
callback for the name() method
static PyObject * staticCallback_activate (PyObject *self, PyObject *args)
callback for the activate() method
static PyObject * staticCallback_listToolbars (PyObject *self, PyObject *args)
callback for the listToolbars() method
static PyObject * staticCallback_getToolbarItems (PyObject *self, PyObject *args)
callback for the getToolbarItems() method
static PyObject * staticCallback_listCommandbars (PyObject *self, PyObject *args)
callback for the listCommandbars() method
static PyObject * staticCallback_listMenus (PyObject *self, PyObject *args)
callback for the listMenus() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Workbench.
Member Typedef Documentation
PointerType
typedef Workbench* Gui::WorkbenchPy::PointerType
Constructor & Destructor Documentation
~WorkbenchPy()
WorkbenchPy::~WorkbenchPy () protected
WorkbenchPy()
WorkbenchPy::WorkbenchPy (Workbench * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
activate()
PyObject * WorkbenchPy::activate (PyObject * args)
implementer for the activate() method
Activates the workbench object.
References Gui::WorkbenchManager::activate(), Base::BaseClassPy::getTypeId(), getWorkbenchPtr(), Gui::WorkbenchManager::instance(), and Gui::Workbench::name().
Referenced by ArchBuildingPart.ViewProviderBuildingPart::doubleClicked(), draftviewproviders.view_layer.ViewProviderLayer::setupContextMenu(), and staticCallback_activate().
getCustomAttributes()
PyObject * WorkbenchPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getToolbarItems()
PyObject * WorkbenchPy::getToolbarItems (PyObject * args)
implementer for the getToolbarItems() method
Shows a dict of all toolbars and their commands.
References Gui::Workbench::getToolbarItems(), and getWorkbenchPtr().
Referenced by staticCallback_getToolbarItems().
GetType()
virtual PyTypeObject* Gui::WorkbenchPy::GetType (void) virtual
Reimplemented from Base::BaseClassPy.
Reimplemented in Gui::PythonWorkbenchPy.
getWorkbenchPtr()
Workbench * WorkbenchPy::getWorkbenchPtr (void) const
getter for the object handled by this class
Referenced by activate(), getToolbarItems(), listCommandbars(), listMenus(), listToolbars(), and name().
listCommandbars()
PyObject * WorkbenchPy::listCommandbars (PyObject * args)
implementer for the listCommandbars() method
Shows a list of all command bars.
References getWorkbenchPtr(), and Gui::Workbench::listCommandbars().
Referenced by Gui::PythonWorkbenchPy::ListCommandbars(), and staticCallback_listCommandbars().
listMenus()
PyObject * WorkbenchPy::listMenus (PyObject * args)
implementer for the listMenus() method
Shows a list of all menus.
References getWorkbenchPtr(), and Gui::Workbench::listMenus().
Referenced by Gui::PythonWorkbenchPy::ListMenus(), and staticCallback_listMenus().
listToolbars()
PyObject * WorkbenchPy::listToolbars (PyObject * args)
implementer for the listToolbars() method
Shows a list of all toolbars.
References getWorkbenchPtr(), and Gui::Workbench::listToolbars().
Referenced by Gui::PythonWorkbenchPy::ListToolbars(), and staticCallback_listToolbars().
name()
PyObject * WorkbenchPy::name (PyObject * args)
implementer for the name() method
Retrieves the workbench name.
References getWorkbenchPtr().
Referenced by prototype.Node::addtofreecad(), addonmanager_macro.Macro::filename(), gzip_utf8.GzipFile::filename(), ifc4.ifcapproval::hasidentifierorname(), femsolver.elmer.sifio.Section::keys(), automotive_design.si_unit::named_unit_dimensions(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::output(), prototype.Node::pprint(), prototype.Node::pprint2(), PathScripts.PathSetupSheetGui.OpTaskPanel::propertyGroup(), PathScripts.PathSetupSheetGui.OpTaskPanel::propertyName(), addonmanager_workers.CheckSingleWorker::run(), staticCallback_name(), ifc2x3.ifcexternalreference::wr1(), ifc2x3.ifcdocumentreference::wr1(), ifc4.ifcexternalreference::wr1(), ifc4.ifcdocumentreference::wr1(), and automotive_design.general_property_association::wr2().
PyInit()
int WorkbenchPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::BaseClassPy.
Reimplemented in Gui::PythonWorkbenchPy.
PyMake()
PyObject * WorkbenchPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string WorkbenchPy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int WorkbenchPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_activate()
PyObject * WorkbenchPy::staticCallback_activate (PyObject * self, PyObject * args) static
callback for the activate() method
References activate(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getToolbarItems()
PyObject * WorkbenchPy::staticCallback_getToolbarItems (PyObject * self, PyObject * args) static
callback for the getToolbarItems() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getToolbarItems(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_listCommandbars()
PyObject * WorkbenchPy::staticCallback_listCommandbars (PyObject * self, PyObject * args) static
callback for the listCommandbars() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), listCommandbars(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_listMenus()
PyObject * WorkbenchPy::staticCallback_listMenus (PyObject * self, PyObject * args) static
callback for the listMenus() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), listMenus(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_listToolbars()
PyObject * WorkbenchPy::staticCallback_listToolbars (PyObject * self, PyObject * args) static
callback for the listToolbars() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), listToolbars(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_name()
PyObject * WorkbenchPy::staticCallback_name (PyObject * self, PyObject * args) static
callback for the name() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), name(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef WorkbenchPy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of WorkbenchPy.
Methods
PyMethodDef WorkbenchPy::Methods static
Methods structure of WorkbenchPy.
Type
PyTypeObject WorkbenchPy::Type static
Type structure of WorkbenchPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Gui/WorkbenchPy.h
Sources/FreeCAD/src/Gui/WorkbenchPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Gui/WorkbenchPy.cpp