FreeCAD: femexamples.thermomech_spine Namespace Reference
femexamples.thermomech_spine Namespace Reference
Functions
def get_explanation (header="")
def get_information ()
def setup (doc=None, solvertype="ccxtools")
Function Documentation
get_explanation()
def femexamples.thermomech_spine.get_explanation (header = "")
Referenced by femexamples.thermomech_spine.setup().
get_information()
def femexamples.thermomech_spine.get_information ()
Referenced by femexamples.thermomech_spine.setup().
setup()
def femexamples.thermomech_spine.setup (doc = None, solvertype = "ccxtools")
References femexamples.thermomech_spine.get_explanation(), femexamples.thermomech_spine.get_information(), ObjectsFem.makeAnalysis(), ObjectsFem.makeConstraintFixed(), ObjectsFem.makeConstraintHeatflux(), ObjectsFem.makeConstraintInitialTemperature(), ObjectsFem.makeConstraintTemperature(), ObjectsFem.makeMaterialSolid(), ObjectsFem.makeMeshGmsh(), ObjectsFem.makeSolverCalculix(), and ObjectsFem.makeSolverCalculixCcxTools().