FreeCAD: FaceQuadStruct::SideIterator Struct Reference
FaceQuadStruct::SideIterator Struct Reference
#include <StdMeshers_Quadrangle_2D.hxx>
Public Member Functions
int Count () const
void Init (const Side &side)
bool More () const
void Next ()
UVPtStruct & operator[] (int i)
SideIterator ()
UVPtStruct & UVPt () const
Public Attributes
int counter
int dPtr
const UVPtStruct * uvEnd
const UVPtStruct * uvPtr
Constructor & Destructor Documentation
SideIterator()
FaceQuadStruct::SideIterator::SideIterator ()
Member Function Documentation
Count()
int FaceQuadStruct::SideIterator::Count () const
References counter.
Referenced by StdMeshers_Quadrangle_2D::setNormalizedGrid().
Init()
void FaceQuadStruct::SideIterator::Init (const Side & side)
References dPtr, FaceQuadStruct::side, uvEnd, and uvPtr.
Referenced by StdMeshers_Quadrangle_2D::computeQuadPref(), and StdMeshers_Quadrangle_2D::setNormalizedGrid().
More()
bool FaceQuadStruct::SideIterator::More (void) const
References uvEnd, and uvPtr.
Referenced by StdMeshers_Quadrangle_2D::setNormalizedGrid().
Next()
void FaceQuadStruct::SideIterator::Next (void)
References counter, dPtr, and uvPtr.
Referenced by StdMeshers_Quadrangle_2D::setNormalizedGrid().
operator[]()
UVPtStruct& FaceQuadStruct::SideIterator::operator[] (int i)
References dPtr, and uvPtr.
UVPt()
UVPtStruct& FaceQuadStruct::SideIterator::UVPt () const
References uvPtr.
Referenced by StdMeshers_Quadrangle_2D::setNormalizedGrid().
Member Data Documentation
counter
int FaceQuadStruct::SideIterator::counter
Referenced by Count(), and Next().
dPtr
int FaceQuadStruct::SideIterator::dPtr
Referenced by Init(), Next(), and operator[]().
uvEnd
const UVPtStruct * FaceQuadStruct::SideIterator::uvEnd
Referenced by Init(), and More().
uvPtr
const UVPtStruct* FaceQuadStruct::SideIterator::uvPtr
Referenced by Init(), More(), Next(), operator[](), and UVPt().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_Quadrangle_2D.hxx