FreeCAD: SMDS_MeshElementIDFactory Class Reference
SMDS_MeshElementIDFactory Class Reference
#include <SMDS_MeshElementIDFactory.hxx>
Public Member Functions
bool BindID (int ID, SMDS_MeshElement *elem)
virtual void Clear ()
SMDS_ElemIteratorPtr elementsIterator () const
virtual int GetFreeID ()
SMDS_MeshElement * MeshElement (int ID)
virtual void ReleaseID (int ID, int vtkId=-1)
int SetInVtkGrid (SMDS_MeshElement *elem)
SMDS_MeshElementIDFactory ()
Public Member Functions inherited from SMDS_MeshNodeIDFactory
bool BindID (int ID, SMDS_MeshElement *elem)
SMDS_ElemIteratorPtr elementsIterator () const
virtual void emptyPool (int maxId)
int GetMaxID () const
int GetMinID () const
SMDS_MeshElement * MeshElement (int ID)
SMDS_MeshNodeIDFactory ()
Public Member Functions inherited from SMDS_MeshIDFactory
void adjustMaxId (int ID)
int GetFreeID ()
SMDS_Mesh * GetMesh ()
bool isPoolIdEmpty ()
void SetMesh (SMDS_Mesh *mesh)
Public Member Functions inherited from SMDS_MeshObject
virtual ~SMDS_MeshObject ()
Protected Member Functions
void updateMinMax () const
void updateMinMax (int id) const
Protected Member Functions inherited from SMDS_MeshNodeIDFactory
void updateMinMax () const
void updateMinMax (int id) const
Protected Member Functions inherited from SMDS_MeshIDFactory
SMDS_MeshIDFactory ()
Friends
class SMDS_Mesh
Additional Inherited Members
Protected Attributes inherited from SMDS_MeshNodeIDFactory
int myMax
int myMin
Protected Attributes inherited from SMDS_MeshIDFactory
int myMaxID
SMDS_Mesh * myMesh
std::set< int > myPoolOfID
Constructor & Destructor Documentation
SMDS_MeshElementIDFactory()
SMDS_MeshElementIDFactory::SMDS_MeshElementIDFactory ()
Member Function Documentation
BindID()
bool SMDS_MeshElementIDFactory::BindID (int ID, SMDS_MeshElement * elem)
References SMDS_MeshIDFactory::myMesh, SMDS_Mesh::registerElement(), and SetInVtkGrid().
Referenced by SMDS_Mesh::Add0DElementWithID().
Clear()
void SMDS_MeshElementIDFactory::Clear () virtual
Reimplemented from SMDS_MeshNodeIDFactory.
References SMDS_MeshIDFactory::Clear(), SMDS_Mesh::myCellIdVtkToSmds, SMDS_MeshNodeIDFactory::myMax, SMDS_MeshIDFactory::myMesh, and SMDS_MeshNodeIDFactory::myMin.
Referenced by SMDS_Mesh::Clear().
elementsIterator()
SMDS_ElemIteratorPtr SMDS_MeshElementIDFactory::elementsIterator () const
References SMDS_Mesh::elementsIterator(), and SMDS_MeshIDFactory::myMesh.
GetFreeID()
int SMDS_MeshElementIDFactory::GetFreeID () virtual
Reimplemented from SMDS_MeshNodeIDFactory.
References SMDS_MeshIDFactory::GetFreeID(), and MeshElement().
Referenced by SMDS_Mesh::Add0DElement(), SMDS_Mesh::AddBall(), SMDS_Mesh::AddEdge(), SMDS_Mesh::AddFace(), SMDS_Mesh::AddFaceFromVtkIds(), SMDS_Mesh::AddFaceWithID(), SMDS_Mesh::AddPolygonalFace(), SMDS_Mesh::AddPolyhedralVolume(), SMDS_Mesh::AddQuadPolygonalFace(), SMDS_Mesh::AddVolume(), SMDS_Mesh::AddVolumeFromVtkIds(), SMDS_Mesh::AddVolumeWithID(), SMDS_Mesh::FindEdgeOrCreate(), and SMDS_Mesh::FindFaceOrCreate().
MeshElement()
SMDS_MeshElement * SMDS_MeshElementIDFactory::MeshElement (int ID)
References SMDS_Mesh::FindElement(), SMDS_MeshIDFactory::GetMesh(), SMDS_Mesh::myCells, and SMDS_MeshIDFactory::myMesh.
Referenced by SMDS_Mesh::GetElementType(), and GetFreeID().
ReleaseID()
void SMDS_MeshElementIDFactory::ReleaseID (int ID, int vtkId = -1) virtual
Reimplemented from SMDS_MeshNodeIDFactory.
References SMDS_Mesh::myCellIdVtkToSmds, SMDS_MeshNodeIDFactory::myMax, SMDS_MeshIDFactory::myMesh, SMDS_MeshNodeIDFactory::myMin, SMDS_MeshIDFactory::ReleaseID(), and SMDS_Mesh::setMyModified().
Referenced by SMDS_Mesh::AddFaceFromVtkIds(), SMDS_Mesh::AddPolyhedralVolume(), SMDS_Mesh::AddVolume(), SMDS_Mesh::AddVolumeFromVtkIds(), SMDS_Mesh::Clear(), SMDS_Mesh::RemoveElement(), SMDS_Mesh::RemoveFreeElement(), and SMDS_Mesh::~SMDS_Mesh().
SetInVtkGrid()
int SMDS_MeshElementIDFactory::SetInVtkGrid (SMDS_MeshElement * elem)
References SMDS_Mesh::getGrid(), SMDS_MeshElement::getVtkId(), SMDS_MeshIDFactory::myMesh, SMDS_MeshElement::nodesIterator(), and SMDS_MeshElement::setVtkId().
Referenced by BindID(), and SMDS_Mesh::registerElement().
updateMinMax() [1/2]
void SMDS_MeshElementIDFactory::updateMinMax () const protected
References SMDS_Mesh::myCells, SMDS_MeshNodeIDFactory::myMax, SMDS_MeshIDFactory::myMesh, and SMDS_MeshNodeIDFactory::myMin.
Referenced by SMDS_Mesh::registerElement().
updateMinMax() [2/2]
void SMDS_MeshElementIDFactory::updateMinMax (int id) const protected
Friends And Related Function Documentation
SMDS_Mesh
friend class SMDS_Mesh friend
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_MeshElementIDFactory.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_MeshElementIDFactory.cpp