FreeCAD: Gui::LinkView::SubInfo Class Reference
Gui::LinkView::SubInfo Class Reference
Public Member Functions
bool isLinked () const
void link (App::DocumentObject *obj)
virtual void onLinkedIconChange (LinkInfoPtr) override
SubInfo (LinkView &handle)
virtual void unlink (LinkInfoPtr info=LinkInfoPtr()) override
~SubInfo ()
Public Member Functions inherited from Gui::LinkOwner
virtual void onLinkedUpdateData (LinkInfoPtr, const App::Property *)
Public Attributes
LinkView & handle
LinkInfoPtr linkInfo
friend LinkView
CoinPtr< SoSeparator > pcNode
CoinPtr< SoTransform > pcTransform
std::set< std::string > subElements
Additional Inherited Members
Protected Member Functions inherited from Gui::LinkOwner
virtual ~LinkOwner ()
Constructor & Destructor Documentation
SubInfo()
Gui::LinkView::SubInfo::SubInfo (LinkView & handle)
References Gui::LinkView::SubInfo::pcNode, and Gui::LinkView::SubInfo::pcTransform.
~SubInfo()
Gui::LinkView::SubInfo::~SubInfo ()
References Gui::LinkView::getLinkRoot(), Gui::LinkView::SubInfo::handle, Gui::LinkView::SubInfo::pcNode, and Gui::LinkView::SubInfo::unlink().
Member Function Documentation
isLinked()
bool Gui::LinkView::SubInfo::isLinked () const
References Gui::LinkView::SubInfo::linkInfo.
Referenced by Gui::LinkView::SubInfo::link().
link()
void Gui::LinkView::SubInfo::link (App::DocumentObject * obj)
References Gui::LinkInfo::get(), Gui::LinkView::SubInfo::isLinked(), Gui::LinkView::SubInfo::linkInfo, Gui::LinkView::SubInfo::pcNode, Gui::LinkView::SnapshotTransform, and Gui::LinkView::SubInfo::unlink().
Referenced by draftguitools.gui_dimensions.Dimension::create_linear_dimension_obj(), draftguitools.gui_dimensions.Dimension::create_radial_dimension_obj(), draftguitools.gui_dimensions.Dimension::createObject(), and draftguitools.gui_dimensions.Dimension::set_selection().
onLinkedIconChange()
virtual void Gui::LinkView::SubInfo::onLinkedIconChange (LinkInfoPtr) override virtual
Reimplemented from Gui::LinkOwner.
References Gui::LinkView::autoSubLink, Gui::LinkView::SubInfo::handle, Gui::LinkView::linkInfo, Gui::LinkView::onLinkedIconChange(), and Gui::LinkView::subInfo.
unlink()
virtual void Gui::LinkView::SubInfo::unlink (LinkInfoPtr info = LinkInfoPtr()) override virtual
Reimplemented from Gui::LinkOwner.
References Gui::coinRemoveAllChildren(), Gui::LinkView::SubInfo::linkInfo, Gui::LinkView::SubInfo::pcNode, and Gui::LinkView::SubInfo::pcTransform.
Referenced by Gui::LinkView::SubInfo::link(), and Gui::LinkView::SubInfo::~SubInfo().
Member Data Documentation
handle
LinkView& Gui::LinkView::SubInfo::handle
Referenced by draftguitools.gui_selectplane.Draft_SelectPlane::checkSelection(), Gui::LinkView::SubInfo::onLinkedIconChange(), and Gui::LinkView::SubInfo::~SubInfo().
linkInfo
LinkInfoPtr Gui::LinkView::SubInfo::linkInfo
Referenced by Gui::LinkView::SubInfo::isLinked(), Gui::LinkView::SubInfo::link(), and Gui::LinkView::SubInfo::unlink().
LinkView
friend Gui::LinkView::SubInfo::LinkView
pcNode
CoinPtr<SoSeparator> Gui::LinkView::SubInfo::pcNode
Referenced by Gui::LinkView::SubInfo::link(), Gui::LinkView::SubInfo::SubInfo(), Gui::LinkView::SubInfo::unlink(), and Gui::LinkView::SubInfo::~SubInfo().
pcTransform
CoinPtr<SoTransform> Gui::LinkView::SubInfo::pcTransform
Referenced by Gui::LinkView::SubInfo::SubInfo(), and Gui::LinkView::SubInfo::unlink().
subElements
std::set<std::string> Gui::LinkView::SubInfo::subElements
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/ViewProviderLink.cpp