FreeCAD: MeshCore::CylinderSurfaceFit Class Reference
MeshCore::CylinderSurfaceFit Class Reference
#include <Segmentation.h>
Public Member Functions
void AddTriangle (const MeshGeomFacet &)
CylinderSurfaceFit ()
CylinderSurfaceFit (const Base::Vector3f &b, const Base::Vector3f &a, float r)
CylinderSurfaceFit::CylinderSurfaceFit Set a predefined cylinder. Internal cylinder fits are not done, then.
bool Done () const
float Fit ()
float GetDistanceToSurface (const Base::Vector3f &) const
const char * GetType () const
void Initialize (const MeshGeomFacet &)
std::vector< float > Parameters () const
bool TestTriangle (const MeshGeomFacet &) const
~CylinderSurfaceFit ()
Public Member Functions inherited from MeshCore::AbstractSurfaceFit
AbstractSurfaceFit ()
virtual void AddTriangle (const MeshGeomFacet &)=0
virtual bool Done () const =0
virtual float Fit ()=0
virtual float GetDistanceToSurface (const Base::Vector3f &) const =0
virtual const char * GetType () const =0
virtual void Initialize (const MeshGeomFacet &)=0
virtual std::vector< float > Parameters () const =0
virtual bool TestTriangle (const MeshGeomFacet &) const =0
virtual ~AbstractSurfaceFit ()
Constructor & Destructor Documentation
CylinderSurfaceFit() [1/2]
CylinderSurfaceFit::CylinderSurfaceFit ()
References Base::Vector3< _Precision >::Set().
CylinderSurfaceFit() [2/2]
CylinderSurfaceFit::CylinderSurfaceFit (const Base::Vector3f & b, const Base::Vector3f & a, float r)
CylinderSurfaceFit::CylinderSurfaceFit Set a predefined cylinder. Internal cylinder fits are not done, then.
~CylinderSurfaceFit()
CylinderSurfaceFit::~CylinderSurfaceFit ()
Member Function Documentation
AddTriangle()
void CylinderSurfaceFit::AddTriangle (const MeshGeomFacet & tria) virtual
Implements MeshCore::AbstractSurfaceFit.
References MeshCore::Approximation::AddPoint().
Done()
bool CylinderSurfaceFit::Done () const virtual
Implements MeshCore::AbstractSurfaceFit.
References MeshCore::Approximation::Done().
Fit()
float CylinderSurfaceFit::Fit () virtual
Implements MeshCore::AbstractSurfaceFit.
References MeshCore::CylinderFit::Fit(), MeshCore::CylinderFit::GetAxis(), MeshCore::CylinderFit::GetBase(), and MeshCore::CylinderFit::GetRadius().
GetDistanceToSurface()
float CylinderSurfaceFit::GetDistanceToSurface (const Base::Vector3f & pnt) const virtual
Implements MeshCore::AbstractSurfaceFit.
References DraftVecUtils::dist(), Base::Vector3< _Precision >::DistanceToLine(), and MeshCore::Approximation::Done().
GetType()
const char * MeshCore::CylinderSurfaceFit::GetType (void) const virtual
Implements MeshCore::AbstractSurfaceFit.
Initialize()
void CylinderSurfaceFit::Initialize (const MeshGeomFacet & tria) virtual
Implements MeshCore::AbstractSurfaceFit.
References MeshCore::Approximation::AddPoint(), and MeshCore::Approximation::Clear().
Parameters()
std::vector< float > CylinderSurfaceFit::Parameters () const virtual
Implements MeshCore::AbstractSurfaceFit.
References MeshCore::CylinderFit::GetAxis(), MeshCore::CylinderFit::GetBase(), MeshCore::CylinderFit::GetRadius(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
TestTriangle()
bool CylinderSurfaceFit::TestTriangle (const MeshGeomFacet & tria) const virtual
Implements MeshCore::AbstractSurfaceFit.
References Base::Vector3< _Precision >::Dot(), and MeshCore::MeshGeomFacet::GetNormal().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/Core/Segmentation.h
FreeCAD/src/Mod/Mesh/App/Core/Segmentation.cpp