FreeCAD: TechDrawGui::QGIBalloonLabel Class Reference
TechDrawGui::QGIBalloonLabel Class Reference
#include <QGIViewBalloon.h>
Public Types
enum { Type = QGraphicsItem::UserType + 141 }
Signals
void dragFinished ()
void dragging (bool)
void hover (bool state)
void selected (bool state)
Public Member Functions
virtual QRectF boundingRect () const override
QGCustomText * getDimText (void)
QFont getFont (void)
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QGIBalloonLabel ()
void setColor (QColor c)
void setDimString (QString t)
void setDimString (QString t, qreal maxWidth)
void setDimText (QGCustomText *newText)
void setFont (QFont f)
void setLabelCenter ()
void setPosFromCenter (const double &xCenter, const double &yCenter)
void setPrettyNormal (void)
void setPrettyPre (void)
void setPrettySel (void)
int type () const override
double X () const
double Y () const
virtual ~QGIBalloonLabel ()=default
Public Attributes
bool hasHover
QGIViewBalloon * parent
std::vector< int > seps
bool verticalSep
Protected Member Functions
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) override
Protected Attributes
QColor m_colNormal
bool m_ctrl
bool m_drag
QGCustomText * m_labelText
double posX
double posY
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGIBalloonLabel()
QGIBalloonLabel::QGIBalloonLabel ()
References hasHover, m_ctrl, m_drag, m_labelText, parent, posX, posY, and verticalSep.
~QGIBalloonLabel()
virtual TechDrawGui::QGIBalloonLabel::~QGIBalloonLabel () virtual default
Member Function Documentation
boundingRect()
QRectF QGIBalloonLabel::boundingRect () const override virtual
dragFinished
void TechDrawGui::QGIBalloonLabel::dragFinished () signal
Referenced by mouseReleaseEvent().
dragging
void TechDrawGui::QGIBalloonLabel::dragging (bool) signal
Referenced by itemChange().
getDimText()
QGCustomText * TechDrawGui::QGIBalloonLabel::getDimText (void)
References m_labelText.
Referenced by TechDrawGui::QGIViewBalloon::drawBalloon().
getFont()
QFont TechDrawGui::QGIBalloonLabel::getFont (void)
References m_labelText.
Referenced by TechDrawGui::QGIViewBalloon::placeBalloon(), and TechDrawGui::QGIViewBalloon::updateBalloon().
hover
void TechDrawGui::QGIBalloonLabel::hover (bool state) signal
Referenced by hoverEnterEvent(), and hoverLeaveEvent().
hoverEnterEvent()
void QGIBalloonLabel::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected virtual
References hasHover, hover(), setPrettyPre(), and setPrettySel().
hoverLeaveEvent()
void QGIBalloonLabel::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected virtual
References hasHover, hover(), setPrettyNormal(), and setPrettySel().
itemChange()
QVariant QGIBalloonLabel::itemChange (GraphicsItemChange change, const QVariant & value) override protected virtual
References dragging(), m_ctrl, m_drag, selected(), setLabelCenter(), setPrettyNormal(), and setPrettySel().
mouseDoubleClickEvent()
void QGIBalloonLabel::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override protected virtual
References TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), and Gui::ViewProviderDocumentObject::startDefaultEditMode().
mouseMoveEvent()
void QGIBalloonLabel::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override protected virtual
mousePressEvent()
void QGIBalloonLabel::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected virtual
References m_ctrl, and m_drag.
mouseReleaseEvent()
void QGIBalloonLabel::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override virtual
References dragFinished(), m_ctrl, and m_drag.
paint()
void QGIBalloonLabel::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override virtual
selected
void TechDrawGui::QGIBalloonLabel::selected (bool state) signal
Referenced by itemChange(), PathScripts.PathDressupTagGui.HoldingTagMarker::setEnabled(), and PathScripts.PathDressupTagGui.HoldingTagMarker::setSelected().
setColor()
void QGIBalloonLabel::setColor (QColor c)
References m_colNormal, m_labelText, and TechDrawGui::QGCustomText::setColor().
Referenced by TechDrawGui::QGIViewBalloon::QGIViewBalloon(), TechDrawGui::QGIViewBalloon::setViewPartFeature(), and TechDrawGui::QGIViewBalloon::updateView().
setDimString() [1/2]
void QGIBalloonLabel::setDimString (QString t)
References m_labelText.
Referenced by TechDrawGui::QGIViewBalloon::placeBalloon(), TechDrawGui::QGIViewBalloon::setViewPartFeature(), TechDrawGui::QGIViewBalloon::updateBalloon(), and TechDrawGui::QGIViewBalloon::updateView().
setDimString() [2/2]
void QGIBalloonLabel::setDimString (QString t, qreal maxWidth)
References m_labelText.
setDimText()
void TechDrawGui::QGIBalloonLabel::setDimText (QGCustomText * newText)
References m_labelText.
setFont()
void QGIBalloonLabel::setFont (QFont f)
References m_labelText.
Referenced by TechDrawGui::QGIViewBalloon::placeBalloon(), and TechDrawGui::QGIViewBalloon::updateBalloon().
setLabelCenter()
void QGIBalloonLabel::setLabelCenter ()
References TechDrawGui::QGCustomText::boundingRect(), m_labelText, posX, and posY.
Referenced by itemChange().
setPosFromCenter()
void QGIBalloonLabel::setPosFromCenter (const double & xCenter, const double & yCenter)
References TechDrawGui::QGCustomText::boundingRect(), and m_labelText.
Referenced by TechDrawGui::QGIViewBalloon::placeBalloon(), TechDrawGui::QGIViewBalloon::QGIViewBalloon(), TechDrawGui::QGIViewBalloon::setViewPartFeature(), and TechDrawGui::QGIViewBalloon::updateBalloon().
setPrettyNormal()
void QGIBalloonLabel::setPrettyNormal (void)
References m_labelText, and TechDrawGui::QGCustomText::setPrettyNormal().
Referenced by hoverLeaveEvent(), itemChange(), and TechDrawGui::QGIViewBalloon::QGIViewBalloon().
setPrettyPre()
void QGIBalloonLabel::setPrettyPre (void)
References m_labelText, and TechDrawGui::QGCustomText::setPrettyPre().
Referenced by hoverEnterEvent().
setPrettySel()
void QGIBalloonLabel::setPrettySel (void)
References m_labelText, and TechDrawGui::QGCustomText::setPrettySel().
Referenced by hoverEnterEvent(), hoverLeaveEvent(), and itemChange().
type()
int TechDrawGui::QGIBalloonLabel::type (void) const override
References Type.
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
X()
double TechDrawGui::QGIBalloonLabel::X () const
References posX.
Referenced by TechDrawGui::QGIViewBalloon::balloonLabelDragFinished(), TechDrawGui::QGIViewBalloon::drawBalloon(), PathMachineState.MachineState::getPosition(), and PathMachineState.MachineState::getState().
Y()
double TechDrawGui::QGIBalloonLabel::Y () const
References posY.
Referenced by TechDrawGui::QGIViewBalloon::balloonLabelDragFinished(), TechDrawGui::QGIViewBalloon::drawBalloon(), PathMachineState.MachineState::getPosition(), and PathMachineState.MachineState::getState().
Member Data Documentation
hasHover
bool TechDrawGui::QGIBalloonLabel::hasHover
Referenced by hoverEnterEvent(), hoverLeaveEvent(), and QGIBalloonLabel().
m_colNormal
QColor TechDrawGui::QGIBalloonLabel::m_colNormal protected
Referenced by setColor().
m_ctrl
bool TechDrawGui::QGIBalloonLabel::m_ctrl protected
Referenced by itemChange(), mousePressEvent(), mouseReleaseEvent(), and QGIBalloonLabel().
m_drag
bool TechDrawGui::QGIBalloonLabel::m_drag protected
Referenced by itemChange(), mousePressEvent(), mouseReleaseEvent(), and QGIBalloonLabel().
m_labelText
QGCustomText* TechDrawGui::QGIBalloonLabel::m_labelText protected
Referenced by getDimText(), getFont(), QGIBalloonLabel(), setColor(), setDimString(), setDimText(), setFont(), setLabelCenter(), setPosFromCenter(), setPrettyNormal(), setPrettyPre(), and setPrettySel().
parent
QGIViewBalloon* TechDrawGui::QGIBalloonLabel::parent
Referenced by PathScripts.PathSimulatorGui.CAMSimTaskUi::accept(), Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium(), QGIBalloonLabel(), TechDrawGui::QGIViewBalloon::QGIViewBalloon(), PathScripts.PathSimulatorGui.CAMSimTaskUi::reject(), and PathScripts.PathOpGui.TaskPanelPage::setParent().
posX
double TechDrawGui::QGIBalloonLabel::posX protected
Referenced by QGIBalloonLabel(), setLabelCenter(), and X().
posY
double TechDrawGui::QGIBalloonLabel::posY protected
Referenced by QGIBalloonLabel(), setLabelCenter(), and Y().
seps
std::vector<int> TechDrawGui::QGIBalloonLabel::seps
Referenced by TechDrawGui::QGIViewBalloon::drawBalloon(), and TechDrawGui::QGIViewBalloon::updateBalloon().
verticalSep
bool TechDrawGui::QGIBalloonLabel::verticalSep
Referenced by TechDrawGui::QGIViewBalloon::drawBalloon(), QGIBalloonLabel(), and TechDrawGui::QGIViewBalloon::updateBalloon().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/QGIViewBalloon.h
FreeCAD/src/Mod/TechDraw/Gui/QGIViewBalloon.cpp