FreeCAD: TechDrawGui::QGIWeldSymbol Class Reference
TechDrawGui::QGIWeldSymbol Class Reference
#include <QGIWeldSymbol.h>
Public Types
enum { Type = QGraphicsItem::UserType + 340 }
Public Types inherited from TechDrawGui::QGIView
enum { Type = QGraphicsItem::UserType + 101 }
Public Member Functions
virtual QRectF boundingRect () const override
virtual void drawBorder () override
double getEdgeFuzz (void) const
virtual TechDraw::DrawWeldSymbol * getFeature (void)
QPointF getKinkPoint (void)
QPointF getTailPoint (void)
void getTileFeats (void)
QPointF getTileOrigin (void)
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0) override
QGIWeldSymbol (QGILeaderLine *myParent=nullptr)
virtual void setFeature (TechDraw::DrawWeldSymbol *feat)
virtual void setPrettyNormal ()
virtual void setPrettyPre ()
virtual void setPrettySel ()
virtual QPainterPath shape (void) const override
int type () const override
virtual void updateView (bool update=false) override
~QGIWeldSymbol ()=default
Public Member Functions inherited from TechDrawGui::QGIView
virtual void addArbitraryItem (QGraphicsItem *qgi)
void alignTo (QGraphicsItem *, const QString &alignment)
virtual void drawCaption (void)
QGIViewClip * getClipGroup (void)
virtual QColor getCurrentColor (void)
virtual bool getFrameState (void)
MDIViewPage * getMDIViewPage (void) const
virtual QColor getNormalColor (void)
virtual QColor getPreColor (void)
double getScale (void)
virtual QColor getSelectColor (void)
virtual QColor getSettingColor (void)
const char * getViewName () const
const std::string getViewNameAsString () const
TechDraw::DrawView * getViewObject () const
virtual void isVisible (bool state)
virtual bool isVisible (void)
void makeMark (Base::Vector3d v, QColor c=Qt::red)
void makeMark (double x, double y, QColor c=Qt::red)
void makeMark (QPointF p, QColor c=Qt::red)
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) override
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
QGIView ()
virtual void removeChild (QGIView *child)
virtual void rotateView (void)
virtual void setGroupSelection (bool b)
void setLocked (bool b)
virtual void setSettingColor (QColor c)
void setViewFeature (TechDraw::DrawView *obj)
virtual void toggleCache (bool state)
int type () const override
virtual ~QGIView ()
void setPosition (qreal x, qreal y)
Methods to ensure that Y-Coordinates are orientated correctly.
qreal getY ()
bool isInnerView ()
void isInnerView (bool state)
double getYInClip (double y)
Protected Member Functions
virtual QRectF customBoundingRect () const
virtual void draw () override
void drawAllAround (void)
void drawFieldFlag ()
void drawTailText (void)
void drawTile (TechDraw::DrawTileWeld *tileFeat)
std::vector< QGITile * > getQGITiles (void) const
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
double prefArrowSize ()
double prefFontSize (void) const
virtual QColor prefNormalColor ()
void removeQGITiles (void)
Protected Member Functions inherited from TechDrawGui::QGIView
virtual QRectF customChildrenBoundingRect (void) const
void dumpRect (const char *text, QRectF r)
Base::Reference< ParameterGrp > getParmGroupCol (void)
QGIView * getQGIVByName (std::string name)
Protected Attributes
QGIVertex * m_allAround
TechDraw::DrawTileWeld * m_arrowFeat
std::string m_arrowName
bool m_blockDraw
QGIPrimPath * m_fieldFlag
QFont m_font
TechDraw::DrawLeaderLine * m_leadFeat
TechDraw::DrawTileWeld * m_otherFeat
std::string m_otherName
QGILeaderLine * m_qgLead
QGCustomText * m_tailText
TechDraw::DrawWeldSymbol * m_weldFeat
std::string m_weldFeatName
Protected Attributes inherited from TechDrawGui::QGIView
QHash< QString, QGraphicsItem * > alignHash
QGCustomBorder * m_border
QBrush m_brush
QGICaption * m_caption
QColor m_colCurrent
QColor m_colNormal
QColor m_colPre
QColor m_colSel
QColor m_colSetting
QPen m_decorPen
QFont m_font
bool m_innerView
QGCustomLabel * m_label
QGCustomImage * m_lock
bool m_locked
double m_lockHeight
double m_lockWidth
QPen m_pen
std::string viewName
TechDraw::DrawView * viewObj
Additional Inherited Members
Public Slots inherited from TechDrawGui::QGIView
virtual void onSourceChange (TechDraw::DrawView *newParent)
Static Public Member Functions inherited from TechDrawGui::QGIView
static int calculateFontPixelSize (double sizeInMillimetres)
static int calculateFontPixelWidth (const QFont &font)
static double getDimFontSize (void)
static QGVPage * getGraphicsView (TechDraw::DrawView *dv)
static QString getPrefFont (void)
static double getPrefFontSize (void)
static Gui::ViewProvider * getViewProvider (App::DocumentObject *obj)
Public Attributes inherited from TechDrawGui::QGIView
boost::signals2::signal< void(QGIView *, QPointF)> signalSelectPoint
Static Public Attributes inherited from TechDrawGui::QGIView
static const double DefaultFontSizeInMM = 5.0
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGIWeldSymbol()
QGIWeldSymbol::QGIWeldSymbol (QGILeaderLine * myParent = nullptr) explicit
References ZVALUE::DIMENSION, TechDrawGui::QGILeaderLine::getFeature(), m_allAround, TechDrawGui::QGIView::m_colCurrent, TechDrawGui::QGIView::m_colSetting, m_fieldFlag, m_leadFeat, m_qgLead, m_tailText, prefNormalColor(), TechDrawGui::QGIPrimPath::setFill(), and setPrettyNormal().
~QGIWeldSymbol()
TechDrawGui::QGIWeldSymbol::~QGIWeldSymbol () default
Member Function Documentation
boundingRect()
QRectF QGIWeldSymbol::boundingRect () const override virtual
Reimplemented from TechDrawGui::QGIView.
References customBoundingRect().
customBoundingRect()
QRectF QGIWeldSymbol::customBoundingRect () const protected virtual
References TechDrawGui::QGCustomText::boundingRect(), getQGITiles(), m_allAround, m_fieldFlag, and m_tailText.
Referenced by boundingRect().
draw()
void QGIWeldSymbol::draw (void) override protected virtual
Reimplemented from TechDrawGui::QGIView.
References drawAllAround(), drawFieldFlag(), drawTailText(), drawTile(), getTileFeats(), TechDrawGui::QGIView::isVisible(), m_arrowFeat, m_otherFeat, and removeQGITiles().
Referenced by updateView().
drawAllAround()
void QGIWeldSymbol::drawAllAround (void) protected
References ZVALUE::DIMENSION, TechDrawGui::PreferencesGui::dimFontSizePX(), TechDrawGui::QGIView::getCurrentColor(), getFeature(), getKinkPoint(), TechDrawGui::QGILeaderLine::getLineWidth(), m_allAround, m_qgLead, TechDrawGui::QGIPrimPath::setFill(), TechDrawGui::QGIPrimPath::setNormalColor(), TechDrawGui::QGIVertex::setRadius(), and TechDrawGui::QGIPrimPath::setWidth().
Referenced by draw().
drawBorder()
void QGIWeldSymbol::drawBorder (void) override virtual
Reimplemented from TechDrawGui::QGIView.
drawFieldFlag()
void QGIWeldSymbol::drawFieldFlag () protected
References ZVALUE::DIMENSION, TechDrawGui::PreferencesGui::dimFontSizePX(), getFeature(), getKinkPoint(), TechDrawGui::QGILeaderLine::getLineWidth(), m_fieldFlag, m_qgLead, and TechDrawGui::QGIPrimPath::setWidth().
Referenced by draw().
drawTailText()
void QGIWeldSymbol::drawTailText (void) protected
References TechDrawGui::QGCustomText::boundingRect(), TechDrawGui::QGIView::calculateFontPixelSize(), ZVALUE::DIMENSION, TechDrawGui::ViewProviderWeld::Font, Base::Tools::fromStdString(), TechDrawGui::QGIView::getCurrentColor(), getFeature(), getTailPoint(), App::PropertyString::getValue(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::QGCustomText::justifyLeftAt(), TechDrawGui::QGCustomText::justifyRightAt(), m_font, m_tailText, prefArrowSize(), TechDrawGui::QGCustomText::setColor(), and TechDraw::DrawWeldSymbol::TailText.
Referenced by draw().
drawTile()
void QGIWeldSymbol::drawTile (TechDraw::DrawTileWeld * tileFeat) protected
References TechDraw::DrawWeldSymbol::AlternatingWeld, TechDrawGui::QGIView::calculateFontPixelSize(), TechDraw::DrawTileWeld::CenterText, Base::Console(), ZVALUE::DIMENSION, TechDrawGui::QGITile::draw(), TechDrawGui::ViewProviderWeld::Font, TechDrawGui::QGIView::getCurrentColor(), TechDraw::DrawLeaderLine::getScale(), getTileOrigin(), App::PropertyInteger::getValue(), App::PropertyString::getValue(), App::PropertyBool::getValue(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), TechDraw::DrawWeldSymbol::isTailRightSide(), TechDraw::DrawTileWeld::LeftText, m_leadFeat, m_weldFeat, Base::ConsoleSingleton::Message(), TechDraw::DrawTileWeld::RightText, TechDrawGui::QGITile::setAltWeld(), TechDrawGui::QGIDecoration::setColor(), TechDrawGui::QGITile::setFont(), TechDrawGui::QGITile::setTailRight(), TechDrawGui::QGITile::setTilePosition(), TechDrawGui::QGITile::setTileScale(), TechDrawGui::QGITile::setTileTextCenter(), TechDrawGui::QGITile::setTileTextLeft(), TechDrawGui::QGITile::setTileTextRight(), TechDraw::DrawTile::TileColumn, and TechDraw::DrawTile::TileRow.
Referenced by draw().
getEdgeFuzz()
double TechDrawGui::QGIWeldSymbol::getEdgeFuzz (void) const
getFeature()
TechDraw::DrawWeldSymbol * QGIWeldSymbol::getFeature (void) virtual
References m_weldFeat.
Referenced by drawAllAround(), drawFieldFlag(), drawTailText(), getTileFeats(), and updateView().
getKinkPoint()
QPointF QGIWeldSymbol::getKinkPoint (void)
References TechDraw::DrawLeaderLine::getKinkPoint(), m_leadFeat, Base::Vector3< _Precision >::x, and Base::Vector3< _Precision >::y.
Referenced by drawAllAround(), and drawFieldFlag().
getQGITiles()
std::vector< QGITile * > QGIWeldSymbol::getQGITiles (void) const protected
Referenced by customBoundingRect(), removeQGITiles(), setPrettyNormal(), setPrettyPre(), and setPrettySel().
getTailPoint()
QPointF QGIWeldSymbol::getTailPoint (void)
References TechDraw::DrawLeaderLine::getTailPoint(), m_leadFeat, Base::Vector3< _Precision >::x, and Base::Vector3< _Precision >::y.
Referenced by drawTailText().
getTileFeats()
void QGIWeldSymbol::getTileFeats (void)
References getFeature(), TechDraw::DrawWeldSymbol::getTiles(), App::PropertyInteger::getValue(), m_arrowFeat, m_otherFeat, and TechDraw::DrawTile::TileRow.
Referenced by draw().
getTileOrigin()
QPointF QGIWeldSymbol::getTileOrigin (void)
References TechDraw::DrawLeaderLine::getTileOrigin(), m_leadFeat, Base::Vector3< _Precision >::x, and Base::Vector3< _Precision >::y.
Referenced by drawTile().
hoverEnterEvent()
void QGIWeldSymbol::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected virtual
Reimplemented from TechDrawGui::QGIView.
References TechDrawGui::QGIView::getPreColor(), TechDrawGui::QGIView::getSelectColor(), TechDrawGui::QGIView::hoverEnterEvent(), TechDrawGui::QGIView::m_colCurrent, setPrettyPre(), and setPrettySel().
hoverLeaveEvent()
void QGIWeldSymbol::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected virtual
Reimplemented from TechDrawGui::QGIView.
References TechDrawGui::QGIView::getSelectColor(), TechDrawGui::QGIView::hoverLeaveEvent(), TechDrawGui::QGIView::m_colCurrent, TechDrawGui::QGIView::m_colNormal, setPrettyNormal(), and setPrettySel().
itemChange()
QVariant QGIWeldSymbol::itemChange (GraphicsItemChange change, const QVariant & value) override protected virtual
Reimplemented from TechDrawGui::QGIView.
References TechDrawGui::QGIView::itemChange(), setPrettyNormal(), and setPrettySel().
paint()
void QGIWeldSymbol::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) override virtual
Reimplemented from TechDrawGui::QGIView.
References TechDrawGui::QGIView::paint().
prefArrowSize()
double QGIWeldSymbol::prefArrowSize () protected
References TechDrawGui::PreferencesGui::dimArrowSize().
Referenced by drawTailText().
prefFontSize()
double QGIWeldSymbol::prefFontSize (void) const protected
prefNormalColor()
QColor QGIWeldSymbol::prefNormalColor (void) protected virtual
References TechDrawGui::PreferencesGui::leaderQColor(), and TechDrawGui::QGIView::m_colNormal.
Referenced by QGIWeldSymbol().
removeQGITiles()
void QGIWeldSymbol::removeQGITiles (void) protected
References getQGITiles().
Referenced by draw().
setFeature()
void QGIWeldSymbol::setFeature (TechDraw::DrawWeldSymbol * feat) virtual
References App::DocumentObject::getNameInDocument(), m_weldFeat, and m_weldFeatName.
Referenced by TechDrawGui::QGVPage::addWeldSymbol().
setPrettyNormal()
void QGIWeldSymbol::setPrettyNormal (void) virtual
References getQGITiles(), m_allAround, TechDrawGui::QGIView::m_colCurrent, TechDrawGui::QGIView::m_colNormal, m_fieldFlag, m_tailText, TechDrawGui::QGCustomText::setColor(), TechDrawGui::QGIPrimPath::setNormalColor(), TechDrawGui::QGCustomText::setPrettyNormal(), and TechDrawGui::QGIPrimPath::setPrettyNormal().
Referenced by hoverLeaveEvent(), itemChange(), and QGIWeldSymbol().
setPrettyPre()
void QGIWeldSymbol::setPrettyPre (void) virtual
References TechDrawGui::QGIView::getPreColor(), getQGITiles(), m_allAround, TechDrawGui::QGIView::m_colCurrent, m_fieldFlag, m_tailText, TechDrawGui::QGCustomText::setColor(), TechDrawGui::QGIPrimPath::setNormalColor(), TechDrawGui::QGCustomText::setPrettyPre(), and TechDrawGui::QGIPrimPath::setPrettyPre().
Referenced by hoverEnterEvent().
setPrettySel()
void QGIWeldSymbol::setPrettySel (void) virtual
References getQGITiles(), TechDrawGui::QGIView::getSelectColor(), m_allAround, TechDrawGui::QGIView::m_colCurrent, m_fieldFlag, m_tailText, TechDrawGui::QGCustomText::setColor(), TechDrawGui::QGIPrimPath::setNormalColor(), TechDrawGui::QGCustomText::setPrettySel(), and TechDrawGui::QGIPrimPath::setPrettySel().
Referenced by hoverEnterEvent(), hoverLeaveEvent(), and itemChange().
shape()
QPainterPath QGIWeldSymbol::shape (void) const override virtual
type()
int TechDrawGui::QGIWeldSymbol::type (void) const override
updateView()
void QGIWeldSymbol::updateView (bool update = false) override virtual
Reimplemented from TechDrawGui::QGIView.
References Base::Console(), draw(), getFeature(), TechDrawGui::QGIView::getViewObject(), and Base::ConsoleSingleton::Warning().
Referenced by TechDrawGui::QGVPage::addWeldSymbol().
Member Data Documentation
m_allAround
QGIVertex* TechDrawGui::QGIWeldSymbol::m_allAround protected
Referenced by customBoundingRect(), drawAllAround(), QGIWeldSymbol(), setPrettyNormal(), setPrettyPre(), and setPrettySel().
m_arrowFeat
TechDraw::DrawTileWeld* TechDrawGui::QGIWeldSymbol::m_arrowFeat protected
Referenced by draw(), and getTileFeats().
m_arrowName
std::string TechDrawGui::QGIWeldSymbol::m_arrowName protected
m_blockDraw
bool TechDrawGui::QGIWeldSymbol::m_blockDraw protected
m_fieldFlag
QGIPrimPath* TechDrawGui::QGIWeldSymbol::m_fieldFlag protected
Referenced by customBoundingRect(), drawFieldFlag(), QGIWeldSymbol(), setPrettyNormal(), setPrettyPre(), and setPrettySel().
m_font
QFont TechDrawGui::QGIWeldSymbol::m_font protected
Referenced by drawTailText().
m_leadFeat
TechDraw::DrawLeaderLine* TechDrawGui::QGIWeldSymbol::m_leadFeat protected
Referenced by drawTile(), getKinkPoint(), getTailPoint(), getTileOrigin(), and QGIWeldSymbol().
m_otherFeat
TechDraw::DrawTileWeld* TechDrawGui::QGIWeldSymbol::m_otherFeat protected
Referenced by draw(), and getTileFeats().
m_otherName
std::string TechDrawGui::QGIWeldSymbol::m_otherName protected
m_qgLead
QGILeaderLine* TechDrawGui::QGIWeldSymbol::m_qgLead protected
Referenced by drawAllAround(), drawFieldFlag(), and QGIWeldSymbol().
m_tailText
QGCustomText* TechDrawGui::QGIWeldSymbol::m_tailText protected
Referenced by customBoundingRect(), drawTailText(), QGIWeldSymbol(), setPrettyNormal(), setPrettyPre(), and setPrettySel().
m_weldFeat
TechDraw::DrawWeldSymbol* TechDrawGui::QGIWeldSymbol::m_weldFeat protected
Referenced by drawTile(), getFeature(), and setFeature().
m_weldFeatName
std::string TechDrawGui::QGIWeldSymbol::m_weldFeatName protected
Referenced by setFeature().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGIWeldSymbol.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGIWeldSymbol.cpp