FreeCAD: geoff_geometry Namespace Reference
geoff_geometry Namespace Reference
Classes
class Box
class Box3d
class Circle
class CLine
class Kurve
class Line
class Matrix
class Plane
class Point
class Point3d
class Span
class SpanDataObject
class SpanVertex
class spVertex
class Triangle3d
class Vector2d
class Vector3d
Enumerations
enum GENERAL_MESSAGES {
MES_TITLE = 0, MES_UNFINISHEDCODING, MES_ERRORFILENAME, MES_LOGFILE,
MES_LOGFILE1, MES_P4CMENU, MES_P4CMENUHINT
}
enum GEOMETRY_ERROR_MESSAGES {
MES_DIFFSCALE = 1000, MES_POINTONCENTRE, MES_INVALIDARC, MES_LOFTUNEQUALSPANCOUNT,
MES_EQUALSPANCOUNTFAILED, MES_CANNOTTRIMSPAN, MES_INDEXOUTOFRANGE, MES_BAD_VERTEX_NUMBER,
MES_BAD_REF_OFFSET, MES_BAD_SEC_OFFSET, MES_ROLLINGBALL4AXIS_ERROR, MES_INPUT_EQUALSPANCOUNT,
MES_INVALIDPLANE
}
enum MESSAGE_GROUPS { GENERAL_MESSAGES, GEOMETRY_ERROR_MESSAGES, PARAMSPMP }
enum OFFSET_METHODS { NO_ELIMINATION = 0, BASIC_OFFSET, ROLLINGBALL_OFFSET }
enum SPAN_IDS { UNMARKED = 0xe0000000, ROLL_AROUND, INTERSECTION, FULL_CIRCLE_KURVE }
enum UNITS_TYPE { MM = 0, METRES, INCHES }
Functions
Point Along (const CLine &s, double d)
Point Along (const CLine &s, double d, const Point &p)
Point Along (const CLine &s, double d, Point &p)
int apolloniusProblem (int AT1, const Circle &c1, int AT2, const Circle &c2, int AT3, const Circle &c3, Circle &Solution1, Circle &Solution2)
int apolloniusProblem (int AT1, const Circle &c1, int AT2, const Circle &c2, int AT3, const CLine &cl3, Circle &Solution1, Circle &Solution2)
int apolloniusProblem (int AT1, const Circle &c1, int AT2, const CLine &cl2, int AT3, const CLine &cl3, Circle &Solution1, Circle &Solution2)
int ArcArcIntof (const Span &arc0, const Span &arc1, Point &pLeft, Point &pRight)
Point Around (const Circle &c, double d, const Point &p)
Point AtAngle (const Circle &c, double angle)
CLine AtAngle (double angle, const Point &p0, const CLine &s)
double atn360 (double dy, double dx)
int biarc (CLine &cl0, CLine &cl1, Span *sp0, Span *sp1)
static void bubblesort (vector< Point > &p, vector< double > &d)
int corner (const Span &span, const Span &next, double cpTol=CPTANGENTTOL)
int corner (const Vector2d &v0, const Vector2d &v1, double cpTol)
double CPTOL (double offset, double maxOffset)
double Degrees (double radians)
double Dist (const Circle &c, const Point &p)
double Dist (const Circle &c0, const Circle &c1)
double Dist (const CLine &s, const Circle &c)
double Dist (const Line &l, const Point3d &p, Point3d &pnear, double &t)
double Dist (const Point &p0, const Circle &c, const Point &p1)
double Dist (const Point3d *p, const Vector3d *vl, const Point3d *pf)
double Dist (const Span &sp, const Point &p, Point &pnear)
double DistSq (const Point3d *p, const Vector3d *vl, const Point3d *pf)
static bool DoesIntersInterfere (const Point &pInt, const Kurve &k, double offset)
static Kurve eliminateLoops (const Kurve &k, const Kurve &originalk, double offset, int &ret)
int EqualiseSpanCount (Kurve &k1, Kurve &k2, Kurve &k1equal, Kurve &k2equal, bool equalise_same_span_count)
void EqualiseSpanCountAfterOffset (Kurve &k1, Kurve &k2, Kurve &k1Out, Kurve &k2Out)
void EqualiseSpanCountAfterOffsetFromRollAround (Kurve &k1, Kurve &k2, Kurve &k1Out, Kurve &k2Out)
void FAILURE (const std::wstring &str)
void FAILURE (const wchar_t *str)
bool FEQ (double a, double b, double tolerance=TOLERANCE)
bool FEQZ (double a, double tolerance=TIGHT_TOLERANCE)
bool FNE (double a, double b, double tolerance=TOLERANCE)
bool FNEZ (double a, double tolerance=TIGHT_TOLERANCE)
const wchar_t * getMessage (const wchar_t *original)
double IncludedAngle (const CLine &s0, const CLine &s1, int dir=1)
double IncludedAngle (const Vector2d &v0, const Vector2d &v1, int dir)
double IncludedAngle (const Vector3d &v0, const Vector3d &v1, const Vector3d &normal, int dir)
int Intof (const Circle &c0, const Circle &c1, Point &pLeft, Point &pRight)
Point Intof (const CLine &s0, const CLine &s1)
int Intof (const Line &l0, const Line &l1, Point3d &intof)
int Intof (const Span &sp0, const Span &sp1, Point &p0, Point &p1, double t[4])
Point Intof (int intMode, const Circle &c0, const Circle &c1)
Point Intof (int intMode, const Circle &c0, const Circle &c1, Point &otherInters)
Point Intof (int NF, const CLine &s, const Circle &c)
Point Intof (int NF, const CLine &s, const Circle &c, Point &otherInters)
Point IntofIso (Span &one, Span &two, Span &three)
Line IsPtsLine (const double *a, int n, double tolerance, double *deviation)
int LineArcIntof (const Span &line, const Span &arc, Point &p0, Point &p1, double t[4])
int LineLineIntof (const Span &sp0, const Span &sp1, Point &p, double t[2])
Point Mid (const Point &p0, const Point &p1, double factor)
Point Mid (const Span &sp)
void MinMax (const Point &p, Point &pmin, Point &pmax)
void MinMax (const Point3d &p, Point3d &pmin, Point3d &pmax)
double mm (double value)
Point3d Near (const Line &l, const Point3d &p, double &t)
CLine Normal (const CLine &s)
CLine Normal (const CLine &s, const Point &p)
Point On (const Circle &c, const Point &p)
Point On (const CLine &s, const Point &p)
bool OnSpan (const Span &sp, const Point &p)
bool OnSpan (const Span &sp, const Point &p, bool nearPoints, Point &pNear, Point &pOnSpan)
ostream & operator<< (ostream &op, Point3d &p)
wostream & operator<< (wostream &op, Circle &c)
wostream & operator<< (wostream &op, CLine &cl)
wostream & operator<< (wostream &op, Plane &pl)
wostream & operator<< (wostream &op, Point &p)
wostream & operator<< (wostream &op, Span &sp)
wostream & operator<< (wostream &op, Vector2d &v)
wostream & operator<< (wostream &op, Vector3d &v)
CLine Parallel (const CLine &cl, const Point &p)
CLine Parallel (const CLine &s0, Point &p)
Circle Parallel (int side, const Circle &c0, double distance)
CLine Parallel (int side, const CLine &s0, double distance)
Point Polar (const Point &p, double angle, double r)
int quadratic (double a, double b, double c, double &x0, double &x1)
double Radians (double degrees)
Point Rel (const Point &p, double x0, double y0)
void set_Tolerances (int mode)
static int Split (double tolerance, double angle, double radius, int dir)
void tangential_arc (const Point &p0, const Point &p1, const Vector2d &v0, Point &c, int &dir)
CLine Tanto (int AT, const Circle &c, const Point &p)
CLine Tanto (int AT, const Circle &c, double angle, const CLine &s0)
CLine Tanto (int AT0, const Circle &c0, int AT1, const Circle &c)
Circle Tanto (int AT1, CLine &s1, int AT2, CLine &s2, double rad)
Circle Tanto (int AT1, CLine s1, int AT2, CLine s2, int AT3, CLine s3)
Circle Tanto (int AT1, const CLine &s1, int AT2, const CLine &s2, double rad)
Circle Tanto (int AT1, const CLine &s1, int AT2, const CLine &s2, int AT3, const CLine &s3)
Circle Tanto (int LR, int AT0, const Circle &c0, const Point &p, double rad)
Circle Tanto (int LR, int AT0, const Circle &c0, int AT1, const Circle &c1, double rad)
Circle Tanto (int LR, int AT1, const Circle &c1, int AT2, const Circle &c2, int AT3, const Circle c3)
Circle Tanto (int NF, CLine &s0, Point &p, double rad)
Circle Tanto (int NF, const CLine &s0, const Point &p, double rad)
Circle Tanto (int NF, int AT0, const CLine &s0, int AT1, const Circle &c1, double rad)
Circle Thro (const Point &p0, const Point &p1)
Circle Thro (const Point &p0, const Point &p1, const Point &p2)
Circle Thro (int LR, const Point &p0, const Point &p1, double rad)
Point XonCLine (CLine &s, double xval)
Point XonCLine (const CLine &s, double xval)
Point YonCLine (CLine &s, double yval)
Point YonCLine (const CLine &s, double yval)
Variables
double COS_SMALL_ANGLE
double RESOLUTION = 1.0e-06
double SIN_SMALL_ANGLE
double SMALL_ANGLE
double TIGHT_TOLERANCE = 1.0e-09
double TOLERANCE = 1.0e-06
double TOLERANCE_SQ = TOLERANCE * TOLERANCE
double UNIT_VECTOR_TOLERANCE = 1.0e-10
Matrix UnitMatrix
int UNITS = MM
Enumeration Type Documentation
GENERAL_MESSAGES
enum geoff_geometry::GENERAL_MESSAGES
Enumerator
MES_TITLE
MES_UNFINISHEDCODING
MES_ERRORFILENAME
MES_LOGFILE
MES_LOGFILE1
MES_P4CMENU
MES_P4CMENUHINT
GEOMETRY_ERROR_MESSAGES
enum geoff_geometry::GEOMETRY_ERROR_MESSAGES
Enumerator
MES_DIFFSCALE
MES_POINTONCENTRE
MES_INVALIDARC
MES_LOFTUNEQUALSPANCOUNT
MES_EQUALSPANCOUNTFAILED
MES_CANNOTTRIMSPAN
MES_INDEXOUTOFRANGE
MES_BAD_VERTEX_NUMBER
MES_BAD_REF_OFFSET
MES_BAD_SEC_OFFSET
MES_ROLLINGBALL4AXIS_ERROR
MES_INPUT_EQUALSPANCOUNT
MES_INVALIDPLANE
MESSAGE_GROUPS
enum geoff_geometry::MESSAGE_GROUPS
Enumerator
GENERAL_MESSAGES
GEOMETRY_ERROR_MESSAGES
PARAMSPMP
OFFSET_METHODS
enum geoff_geometry::OFFSET_METHODS
Enumerator
NO_ELIMINATION
BASIC_OFFSET
ROLLINGBALL_OFFSET
SPAN_IDS
enum geoff_geometry::SPAN_IDS
Enumerator
UNMARKED
ROLL_AROUND
INTERSECTION
FULL_CIRCLE_KURVE
UNITS_TYPE
enum geoff_geometry::UNITS_TYPE
Enumerator
MM
METRES
INCHES
Function Documentation
Along() [1/3]
Point geoff_geometry::Along (const CLine & s, double d)
Referenced by Along(), Thro(), and YonCLine().
Along() [2/3]
Point geoff_geometry::Along (const CLine & s, double d, const Point & p)
References Along(), Around(), AtAngle(), On(), and Tanto().
Along() [3/3]
Point geoff_geometry::Along (const CLine & s, double d, Point & p)
apolloniusProblem() [1/3]
int geoff_geometry::apolloniusProblem (int AT1, const Circle & c1, int AT2, const Circle & c2, int AT3, const Circle & c3, Circle & Solution1, Circle & Solution2)
References apolloniusProblem().
Referenced by apolloniusProblem().
apolloniusProblem() [2/3]
int geoff_geometry::apolloniusProblem (int AT1, const Circle & c1, int AT2, const Circle & c2, int AT3, const CLine & cl3, Circle & Solution1, Circle & Solution2)
References apolloniusProblem().
apolloniusProblem() [3/3]
int geoff_geometry::apolloniusProblem (int AT1, const Circle & c1, int AT2, const CLine & cl2, int AT3, const CLine & cl3, Circle & Solution1, Circle & Solution2)
References apolloniusProblem().
ArcArcIntof()
int geoff_geometry::ArcArcIntof (const Span & arc0, const Span & arc1, Point & pLeft, Point & pRight)
References Intof(), geoff_geometry::Point::ok, geoff_geometry::Span::OnSpan(), geoff_geometry::Span::p1, geoff_geometry::Span::pc, and geoff_geometry::Span::radius.
Referenced by Intof().
Around()
Point geoff_geometry::Around (const Circle & c, double d, const Point & p)
References geoff_geometry::Vector2d::getx(), geoff_geometry::Vector2d::gety(), geoff_geometry::CLine::ok, TOLERANCE, and geoff_geometry::CLine::v.
Referenced by Along().
AtAngle() [1/2]
Point geoff_geometry::AtAngle (const Circle & c, double angle)
AtAngle() [2/2]
CLine geoff_geometry::AtAngle (double angle, const Point & p0, const CLine & s)
Referenced by Along(), and Tanto().
atn360()
double geoff_geometry::atn360 (double dy, double dx)
References atn360().
Referenced by atn360(), and Dist().
biarc()
int geoff_geometry::biarc (CLine & cl0, CLine & cl1, Span * sp0, Span * sp1)
References biarc().
Referenced by biarc().
bubblesort()
static void geoff_geometry::bubblesort (vector< Point > & p, vector< double > & d) static
Referenced by geoff_geometry::Kurve::Intof().
corner() [1/2]
int geoff_geometry::corner (const Span & span, const Span & next, double cpTol = CPTANGENTTOL)
References corner(), and geoff_geometry::Span::vs.
corner() [2/2]
int geoff_geometry::corner (const Vector2d & v0, const Vector2d & v1, double cpTol)
References corner(), and draftgeoutils.general::v1().
Referenced by corner().
CPTOL()
double geoff_geometry::CPTOL (double offset, double maxOffset)
References CPTOL(), draftfunctions.offset::offset(), and RESOLUTION.
Referenced by CPTOL().
Degrees()
double geoff_geometry::Degrees (double radians)
References Degrees().
Referenced by Degrees().
Dist() [1/7]
double geoff_geometry::Dist (const Circle & c, const Point & p)
References Dist(), and On().
Dist() [2/7]
double geoff_geometry::Dist (const Circle & c0, const Circle & c1)
References geoff_geometry::Point::Dist(), Dist(), geoff_geometry::Circle::pc, and geoff_geometry::Circle::radius.
Dist() [3/7]
double geoff_geometry::Dist (const CLine & s, const Circle & c)
References Dist().
Dist() [4/7]
double geoff_geometry::Dist (const Line & l, const Point3d & p, Point3d & pnear, double & t)
References Near().
Dist() [5/7]
double geoff_geometry::Dist (const Point & p0, const Circle & c, const Point & p1)
References atn360(), Dist(), geoff_geometry::Point::x, and geoff_geometry::Point::y.
Referenced by Dist(), DoesIntersInterfere(), geoff_geometry::Kurve::Intof(), and Intof().
Dist() [6/7]
double geoff_geometry::Dist (const Point3d * p, const Vector3d * vl, const Point3d * pf)
returns the distance of pf from the line given by p,vl vl must be normalised
References geoff_geometry::Vector3d::magnitude().
Dist() [7/7]
double geoff_geometry::Dist (const Span & sp, const Point & p, Point & pnear)
References geoff_geometry::Span::dir, geoff_geometry::Point::Dist(), Dist(), DraftVecUtils::dist(), geoff_geometry::Span::length, geoff_geometry::Span::OnSpan(), geoff_geometry::Span::p0, geoff_geometry::Span::p1, geoff_geometry::Span::pc, geoff_geometry::Span::radius, and TOLERANCE.
DistSq()
double geoff_geometry::DistSq (const Point3d * p, const Vector3d * vl, const Point3d * pf)
returns the distance squared of pf from the line given by p,vl vl must be normalised
References geoff_geometry::Vector3d::magnitudeSq().
DoesIntersInterfere()
static bool geoff_geometry::DoesIntersInterfere (const Point & pInt, const Kurve & k, double offset) static
References geoff_geometry::Span::dir, Dist(), geoff_geometry::Kurve::Get(), geoff_geometry::Kurve::nSpans(), geoff_geometry::Span::p0, geoff_geometry::Span::p1, geoff_geometry::Span::pc, geoff_geometry::Span::SetProperties(), and TOLERANCE.
Referenced by eliminateLoops().
eliminateLoops()
static Kurve geoff_geometry::eliminateLoops (const Kurve & k, const Kurve & originalk, double offset, int & ret) static
References geoff_geometry::Kurve::Add(), geoff_geometry::Kurve::AddSpanID(), geoff_geometry::Span::dir, geoff_geometry::Point::Dist(), DoesIntersInterfere(), geoff_geometry::Kurve::Get(), geoff_geometry::Kurve::GetSpanID(), geoff_geometry::Span::ID, geoff_geometry::Span::Intof(), geoff_geometry::Span::length, geoff_geometry::Kurve::nSpans(), geoff_geometry::Span::p0, geoff_geometry::Span::p1, geoff_geometry::Span::pc, geoff_geometry::Span::SetProperties(), geoff_geometry::Kurve::Start(), and TOLERANCE.
Referenced by geoff_geometry::Kurve::OffsetMethod1().
EqualiseSpanCount()
int geoff_geometry::EqualiseSpanCount (Kurve & k1, Kurve & k2, Kurve & k1equal, Kurve & k2equal, bool equalise_same_span_count)
References EqualiseSpanCount().
Referenced by EqualiseSpanCount().
EqualiseSpanCountAfterOffset()
void geoff_geometry::EqualiseSpanCountAfterOffset (Kurve & k1, Kurve & k2, Kurve & k1Out, Kurve & k2Out)
References EqualiseSpanCountAfterOffset().
Referenced by EqualiseSpanCountAfterOffset().
EqualiseSpanCountAfterOffsetFromRollAround()
void geoff_geometry::EqualiseSpanCountAfterOffsetFromRollAround (Kurve & k1, Kurve & k2, Kurve & k1Out, Kurve & k2Out)
References EqualiseSpanCountAfterOffsetFromRollAround().
Referenced by EqualiseSpanCountAfterOffsetFromRollAround().
FAILURE() [1/2]
void geoff_geometry::FAILURE (const std::wstring & str)
FAILURE() [2/2]
void geoff_geometry::FAILURE (const wchar_t * str)
Referenced by geoff_geometry::Kurve::Add(), geoff_geometry::Kurve::AddIndex(), geoff_geometry::Kurve::Area(), geoff_geometry::Kurve::Get(), geoff_geometry::Kurve::GetIndex(), geoff_geometry::Matrix::GetRotation(), geoff_geometry::Kurve::GetSpanID(), geoff_geometry::Matrix::Inverse(), geoff_geometry::Kurve::minmax(), geoff_geometry::Kurve::Offset(), geoff_geometry::Kurve::OffsetMethod1(), On(), geoff_geometry::Span::OnSpan(), geoff_geometry::Kurve::Perim(), geoff_geometry::Kurve::Replace(), set_Tolerances(), geoff_geometry::Vector3d::setCartesianAxes(), geoff_geometry::Span::SetProperties(), geoff_geometry::Span::Transform(), geoff_geometry::Circle::Transform(), and geoff_geometry::Vector2d::Vector2d().
FEQ()
bool geoff_geometry::FEQ (double a, double b, double tolerance = TOLERANCE)
References FEQ(), and draftutils.utils::tolerance().
Referenced by FEQ(), geoff_geometry::Circle::operator==(), geoff_geometry::Matrix::operator==(), geoff_geometry::Vector2d::operator==(), geoff_geometry::Vector3d::operator==(), and geoff_geometry::Kurve::Part().
FEQZ()
bool geoff_geometry::FEQZ (double a, double tolerance = TIGHT_TOLERANCE)
References FEQZ(), and draftutils.utils::tolerance().
Referenced by geoff_geometry::Line::atZ(), FEQZ(), geoff_geometry::Triangle3d::Intof(), geoff_geometry::Kurve::OffsetISOMethod(), geoff_geometry::Vector2d::Rotate(), and geoff_geometry::Vector2d::Vector2d().
FNE()
bool geoff_geometry::FNE (double a, double b, double tolerance = TOLERANCE)
References FNE(), and draftutils.utils::tolerance().
Referenced by FNE(), geoff_geometry::Span::OnSpan(), geoff_geometry::Point::operator==(), geoff_geometry::Point3d::operator==(), and geoff_geometry::Span::SetProperties().
FNEZ()
bool geoff_geometry::FNEZ (double a, double tolerance = TIGHT_TOLERANCE)
References FNEZ(), and draftutils.utils::tolerance().
Referenced by FNEZ(), and geoff_geometry::Span::Offset().
getMessage()
const wchar_t * geoff_geometry::getMessage (const wchar_t * original)
Referenced by geoff_geometry::Kurve::Area(), geoff_geometry::Kurve::Get(), geoff_geometry::Kurve::GetSpanID(), geoff_geometry::Matrix::Inverse(), geoff_geometry::Kurve::minmax(), On(), geoff_geometry::Kurve::Perim(), geoff_geometry::Kurve::Replace(), geoff_geometry::Span::SetProperties(), and geoff_geometry::Circle::Transform().
IncludedAngle() [1/3]
double geoff_geometry::IncludedAngle (const CLine & s0, const CLine & s1, int dir = 1)
IncludedAngle() [2/3]
double geoff_geometry::IncludedAngle (const Vector2d & v0, const Vector2d & v1, int dir)
References UNIT_VECTOR_TOLERANCE, and draftgeoutils.general::v1().
Referenced by geoff_geometry::Span::OnSpan(), and geoff_geometry::Span::SetProperties().
IncludedAngle() [3/3]
double geoff_geometry::IncludedAngle (const Vector3d & v0, const Vector3d & v1, const Vector3d & normal, int dir)
References draftgeoutils.general::v1().
Intof() [1/8]
int geoff_geometry::Intof (const Circle & c0, const Circle & c1, Point & pLeft, Point & pRight)
References Intof(), geoff_geometry::Circle::pc, geoff_geometry::Circle::radius, and TOLERANCE_SQ.
Intof() [2/8]
Point geoff_geometry::Intof (const CLine & s0, const CLine & s1)
Referenced by ArcArcIntof(), geoff_geometry::CLine::Intof(), geoff_geometry::Line::Intof(), geoff_geometry::Span::Intof(), geoff_geometry::Circle::Intof(), Intof(), Mid(), Tanto(), Thro(), XonCLine(), and YonCLine().
Intof() [3/8]
int geoff_geometry::Intof (const Line & l0, const Line & l1, Point3d & intof)
References geoff_geometry::Line::box, Dist(), geoff_geometry::Vector3d::getx(), geoff_geometry::Vector3d::gety(), geoff_geometry::Vector3d::getz(), geoff_geometry::Line::length, geoff_geometry::Box3d::outside(), geoff_geometry::Line::p0, TOLERANCE, and geoff_geometry::Line::v.
Intof() [4/8]
int geoff_geometry::Intof (const Span & sp0, const Span & sp1, Point & p0, Point & p1, double t[4])
References ArcArcIntof(), geoff_geometry::Span::box, geoff_geometry::Span::dir, LineArcIntof(), LineLineIntof(), and geoff_geometry::Box::outside().
Intof() [5/8]
Point geoff_geometry::Intof (int intMode, const Circle & c0, const Circle & c1)
References Intof().
Intof() [6/8]
Point geoff_geometry::Intof (int intMode, const Circle & c0, const Circle & c1, Point & otherInters)
References Intof().
Intof() [7/8]
Point geoff_geometry::Intof (int NF, const CLine & s, const Circle & c)
References Intof().
Intof() [8/8]
Point geoff_geometry::Intof (int NF, const CLine & s, const Circle & c, Point & otherInters)
References quadratic().
IntofIso()
Point geoff_geometry::IntofIso (Span & one, Span & two, Span & three)
References IntofIso().
Referenced by IntofIso().
IsPtsLine()
Line geoff_geometry::IsPtsLine (const double * a, int n, double tolerance, double * deviation)
References geoff_geometry::Point3d::Dist(), geoff_geometry::Line::Near(), geoff_geometry::Line::ok, and draftutils.utils::tolerance().
LineArcIntof()
int geoff_geometry::LineArcIntof (const Span & line, const Span & arc, Point & p0, Point & p1, double t[4])
References geoff_geometry::Point::ok, geoff_geometry::Span::p0, geoff_geometry::Span::p1, quadratic(), TOLERANCE, and draftgeoutils.general::v1().
Referenced by Intof().
LineLineIntof()
int geoff_geometry::LineLineIntof (const Span & sp0, const Span & sp1, Point & p, double t[2])
References geoff_geometry::Span::length, geoff_geometry::Point::ok, geoff_geometry::Span::p0, geoff_geometry::Span::p1, TOLERANCE, UNIT_VECTOR_TOLERANCE, and draftgeoutils.general::v1().
Referenced by Intof().
Mid() [1/2]
Point geoff_geometry::Mid (const Point & p0, const Point & p1, double factor)
Referenced by geoff_geometry::Span::Mid(), geoff_geometry::Point::Mid(), Mid(), On(), and Thro().
Mid() [2/2]
Point geoff_geometry::Mid (const Span & sp)
References Intof(), Mid(), geoff_geometry::CLine::ok, and geoff_geometry::CLine::v.
MinMax() [1/2]
void geoff_geometry::MinMax (const Point & p, Point & pmin, Point & pmax)
References MinMax(), geoff_geometry::Point::x, and geoff_geometry::Point::y.
Referenced by geoff_geometry::Line::minmax(), MinMax(), geoff_geometry::Kurve::minmax(), and geoff_geometry::Span::minmax().
MinMax() [2/2]
void geoff_geometry::MinMax (const Point3d & p, Point3d & pmin, Point3d & pmax)
References MinMax(), geoff_geometry::Point3d::x, geoff_geometry::Point3d::y, and geoff_geometry::Point3d::z.
mm()
double geoff_geometry::mm (double value)
References INCHES, METRES, and UNITS.
Near()
Point3d geoff_geometry::Near (const Line & l, const Point3d & p, double & t)
Referenced by Dist().
Normal() [1/2]
CLine geoff_geometry::Normal (const CLine & s)
Normal() [2/2]
CLine geoff_geometry::Normal (const CLine & s, const Point & p)
On() [1/2]
Point geoff_geometry::On (const Circle & c, const Point & p)
References geoff_geometry::Point::Dist(), FAILURE(), getMessage(), Mid(), and TOLERANCE.
On() [2/2]
Point geoff_geometry::On (const CLine & s, const Point & p)
Referenced by Along(), Dist(), and OnSpan().
OnSpan() [1/2]
bool geoff_geometry::OnSpan (const Span & sp, const Point & p)
OnSpan() [2/2]
bool geoff_geometry::OnSpan (const Span & sp, const Point & p, bool nearPoints, Point & pNear, Point & pOnSpan)
References geoff_geometry::Span::dir, geoff_geometry::CLine::Dist(), geoff_geometry::Span::length, On(), geoff_geometry::Span::OnSpan(), geoff_geometry::Span::p0, geoff_geometry::Span::p1, geoff_geometry::Span::pc, geoff_geometry::Span::radius, TOLERANCE, and geoff_geometry::Span::vs.
operator<<() [1/8]
ostream& geoff_geometry::operator<< (ostream & op, Point3d & p)
operator<<() [2/8]
wostream& geoff_geometry::operator<< (wostream & op, Circle & c)
operator<<() [3/8]
wostream& geoff_geometry::operator<< (wostream & op, CLine & cl)
References geoff_geometry::CLine::ok, geoff_geometry::CLine::p, and geoff_geometry::CLine::v.
operator<<() [4/8]
wostream& geoff_geometry::operator<< (wostream & op, Plane & pl)
References geoff_geometry::Plane::d, geoff_geometry::Plane::normal, and geoff_geometry::Plane::ok.
operator<<() [5/8]
wostream& geoff_geometry::operator<< (wostream & op, Point & p)
operator<<() [6/8]
wostream& geoff_geometry::operator<< (wostream & op, Span & sp)
References geoff_geometry::Span::dir, geoff_geometry::Span::p0, geoff_geometry::Span::p1, geoff_geometry::Span::pc, and geoff_geometry::Span::radius.
operator<<() [7/8]
wostream& geoff_geometry::operator<< (wostream & op, Vector2d & v)
operator<<() [8/8]
wostream& geoff_geometry::operator<< (wostream & op, Vector3d & v)
Parallel() [1/4]
CLine geoff_geometry::Parallel (const CLine & cl, const Point & p)
References Thro().
Parallel() [2/4]
CLine geoff_geometry::Parallel (const CLine & s0, Point & p)
Parallel() [3/4]
Circle geoff_geometry::Parallel (int side, const Circle & c0, double distance)
References geoff_geometry::Circle::pc, and geoff_geometry::Circle::radius.
Parallel() [4/4]
CLine geoff_geometry::Parallel (int side, const CLine & s0, double distance)
Polar()
Point geoff_geometry::Polar (const Point & p, double angle, double r)
quadratic()
int geoff_geometry::quadratic (double a, double b, double c, double & x0, double & x1)
References draftutils.utils::epsilon(), METRES, quadratic(), and UNITS.
Referenced by Intof(), LineArcIntof(), and quadratic().
Radians()
double geoff_geometry::Radians (double degrees)
References Radians().
Referenced by Radians().
Rel()
Point geoff_geometry::Rel (const Point & p, double x0, double y0)
set_Tolerances()
void geoff_geometry::set_Tolerances (int mode)
References FAILURE(), INCHES, METRES, MM, RESOLUTION, TIGHT_TOLERANCE, TOLERANCE, TOLERANCE_SQ, UNIT_VECTOR_TOLERANCE, and UNITS.
Split()
static int geoff_geometry::Split (double tolerance, double angle, double radius, int dir) static
References draftutils.utils::tolerance().
Referenced by geoff_geometry::Span::Split().
tangential_arc()
void geoff_geometry::tangential_arc (const Point & p0, const Point & p1, const Vector2d & v0, Point & c, int & dir)
References geoff_geometry::Point::Dist(), geoff_geometry::Vector3d::getz(), geoff_geometry::Plane::Intof(), geoff_geometry::Line::p0, geoff_geometry::Line::Shortest(), and draftgeoutils.general::v1().
Tanto() [1/13]
CLine geoff_geometry::Tanto (int AT, const Circle & c, const Point & p)
References TOLERANCE.
Referenced by Along(), geoff_geometry::Circle::Tanto(), and Tanto().
Tanto() [2/13]
CLine geoff_geometry::Tanto (int AT, const Circle & c, double angle, const CLine & s0)
References AtAngle().
Tanto() [3/13]
CLine geoff_geometry::Tanto (int AT0, const Circle & c0, int AT1, const Circle & c)
References geoff_geometry::Circle::pc, geoff_geometry::Circle::radius, and Tanto().
Tanto() [4/13]
Circle geoff_geometry::Tanto (int AT1, CLine & s1, int AT2, CLine & s2, double rad)
References Intof(), geoff_geometry::Point::ok, and Tanto().
Tanto() [5/13]
Circle geoff_geometry::Tanto (int AT1, CLine s1, int AT2, CLine s2, int AT3, CLine s3)
References geoff_geometry::CLine::c(), geoff_geometry::Vector2d::getx(), geoff_geometry::Vector2d::gety(), Intof(), Tanto(), UNIT_VECTOR_TOLERANCE, and geoff_geometry::CLine::v.
Tanto() [6/13]
Circle geoff_geometry::Tanto (int AT1, const CLine & s1, int AT2, const CLine & s2, double rad)
References Tanto().
Tanto() [7/13]
Circle geoff_geometry::Tanto (int AT1, const CLine & s1, int AT2, const CLine & s2, int AT3, const CLine & s3)
References Tanto().
Tanto() [8/13]
Circle geoff_geometry::Tanto (int LR, int AT0, const Circle & c0, const Point & p, double rad)
References Intof(), geoff_geometry::Point::ok, geoff_geometry::Circle::radius, and Tanto().
Tanto() [9/13]
Circle geoff_geometry::Tanto (int LR, int AT0, const Circle & c0, int AT1, const Circle & c1, double rad)
References Intof(), geoff_geometry::Point::ok, geoff_geometry::Circle::radius, and Tanto().
Tanto() [10/13]
Circle geoff_geometry::Tanto (int LR, int AT1, const Circle & c1, int AT2, const Circle & c2, int AT3, const Circle c3)
References Tanto().
Tanto() [11/13]
Circle geoff_geometry::Tanto (int NF, CLine & s0, Point & p, double rad)
References geoff_geometry::CLine::Dist(), Intof(), and Tanto().
Tanto() [12/13]
Circle geoff_geometry::Tanto (int NF, const CLine & s0, const Point & p, double rad)
References Tanto(), and Thro().
Tanto() [13/13]
Circle geoff_geometry::Tanto (int NF, int AT0, const CLine & s0, int AT1, const Circle & c1, double rad)
References Intof(), geoff_geometry::Point::ok, geoff_geometry::Circle::radius, and Tanto().
Thro() [1/3]
Circle geoff_geometry::Thro (const Point & p0, const Point & p1)
References geoff_geometry::Point::Dist(), geoff_geometry::Point::Mid(), and Thro().
Thro() [2/3]
Circle geoff_geometry::Thro (const Point & p0, const Point & p1, const Point & p2)
References geoff_geometry::Point::Dist(), Intof(), Mid(), geoff_geometry::CLine::ok, and Thro().
Thro() [3/3]
Circle geoff_geometry::Thro (int LR, const Point & p0, const Point & p1, double rad)
References Along(), geoff_geometry::Point::Dist(), Mid(), geoff_geometry::CLine::ok, and Thro().
Referenced by Parallel(), Tanto(), and Thro().
XonCLine() [1/2]
Point geoff_geometry::XonCLine (CLine & s, double xval)
References Intof().
Referenced by XonCLine().
XonCLine() [2/2]
Point geoff_geometry::XonCLine (const CLine & s, double xval)
References XonCLine().
YonCLine() [1/2]
Point geoff_geometry::YonCLine (CLine & s, double yval)
References Intof().
Referenced by YonCLine().
YonCLine() [2/2]
Point geoff_geometry::YonCLine (const CLine & s, double yval)
References Along(), Intof(), and YonCLine().
Variable Documentation
COS_SMALL_ANGLE
double geoff_geometry::COS_SMALL_ANGLE extern
RESOLUTION
double geoff_geometry::RESOLUTION = 1.0e-06
Referenced by CPTOL(), and set_Tolerances().
SIN_SMALL_ANGLE
double geoff_geometry::SIN_SMALL_ANGLE extern
SMALL_ANGLE
double geoff_geometry::SMALL_ANGLE extern
TIGHT_TOLERANCE
double geoff_geometry::TIGHT_TOLERANCE = 1.0e-09
Referenced by geoff_geometry::Vector2d::normalise(), geoff_geometry::Matrix::operator==(), and set_Tolerances().
TOLERANCE
double geoff_geometry::TOLERANCE = 1.0e-06
Referenced by geoff_geometry::Kurve::Add(), Around(), Dist(), DoesIntersInterfere(), eliminateLoops(), geoff_geometry::Kurve::Intof(), Intof(), geoff_geometry::Line::Line(), LineArcIntof(), LineLineIntof(), geoff_geometry::Span::Near(), geoff_geometry::Kurve::Near(), geoff_geometry::CLine::Normalise(), geoff_geometry::Kurve::OffsetMethod1(), On(), geoff_geometry::Span::OnSpan(), OnSpan(), geoff_geometry::Circle::operator==(), geoff_geometry::Point::operator==(), geoff_geometry::Point3d::operator==(), set_Tolerances(), geoff_geometry::Span::SetProperties(), and Tanto().
TOLERANCE_SQ
double geoff_geometry::TOLERANCE_SQ = TOLERANCE * TOLERANCE
Referenced by Intof(), and set_Tolerances().
UNIT_VECTOR_TOLERANCE
double geoff_geometry::UNIT_VECTOR_TOLERANCE = 1.0e-10
Referenced by IncludedAngle(), geoff_geometry::Plane::Intof(), LineLineIntof(), geoff_geometry::Vector3d::operator==(), set_Tolerances(), and Tanto().
UnitMatrix
Matrix geoff_geometry::UnitMatrix
UNITS
int geoff_geometry::UNITS = MM
Referenced by mm(), quadratic(), and set_Tolerances().