FreeCAD: FeaturePython.MeshFeature Class Reference
FeaturePython.MeshFeature Class Reference
Public Member Functions
def execute (self, fp)
def onChanged (self, fp, prop)
Member Function Documentation
execute()
def FeaturePython.MeshFeature.execute (self, fp)
 Print a short message when doing a recomputation, this method is mandatory
Referenced by ArchSite.Compass.buildCoordinates(), ArchSchedule.CommandArchSchedule.IsActive(), and FeaturePython.DistanceBolt.onChanged().
onChanged()
def FeaturePython.MeshFeature.onChanged (self, fp, prop)
 Print the name of the property that has changed
Referenced by ArchSite.Compass.buildCoordinates(), and ArchAxis.CommandArchGrid.IsActive().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/TemplatePyMod/FeaturePython.py