FreeCAD: Swig_1_3_33 Namespace Reference
Swig_1_3_33 Namespace Reference
Functions
void cleanupSWIG_T (const char *TypeName)
int convertSWIGPointerObj_T (const char *TypeName, PyObject *obj, void **ptr, int flags)
int createSWIGPointerObj_T (const char *TypeName, void *obj, PyObject **ptr, int own)
Function Documentation
cleanupSWIG_T()
void Swig_1_3_33::cleanupSWIG_T (const char * TypeName)
Referenced by Base::InterpreterSingleton::cleanupSWIG().
convertSWIGPointerObj_T()
int Swig_1_3_33::convertSWIGPointerObj_T (const char * TypeName, PyObject * obj, void ** ptr, int flags)
Referenced by Base::InterpreterSingleton::convertSWIGPointerObj().
createSWIGPointerObj_T()
int Swig_1_3_33::createSWIGPointerObj_T (const char * TypeName, void * obj, PyObject ** ptr, int own)
Referenced by Base::InterpreterSingleton::createSWIGPointerObj().