FreeCAD: MeshGui::Ui_DlgEvaluateSettings Class Reference
MeshGui::Ui_DlgEvaluateSettings Class Reference
#include <ui_DlgEvaluateSettings.h>
Public Member Functions
void retranslateUi (QDialog *MeshGui__DlgEvaluateSettings)
void setupUi (QDialog *MeshGui__DlgEvaluateSettings)
Public Attributes
QDialogButtonBox * buttonBox
QCheckBox * checkDegenerated
QCheckBox * checkFolds
QCheckBox * checkNonmanifoldPoints
QGridLayout * gridLayout
QGridLayout * gridLayout_2
QGroupBox * groupBox
QSpacerItem * verticalSpacer
Member Function Documentation
retranslateUi()
void MeshGui::Ui_DlgEvaluateSettings::retranslateUi (QDialog * MeshGui__DlgEvaluateSettings)
References checkDegenerated, checkFolds, checkNonmanifoldPoints, groupBox, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void MeshGui::Ui_DlgEvaluateSettings::setupUi (QDialog * MeshGui__DlgEvaluateSettings)
References buttonBox, checkDegenerated, checkFolds, checkNonmanifoldPoints, draftgeoutils.intersections::connect(), gridLayout, gridLayout_2, groupBox, retranslateUi(), and verticalSpacer.
Referenced by MeshGui::DlgEvaluateSettings::DlgEvaluateSettings().
Member Data Documentation
buttonBox
QDialogButtonBox* MeshGui::Ui_DlgEvaluateSettings::buttonBox
Referenced by PathScripts.PathGetPoint.TaskPanel::getPoint(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::modifyStandardButtons(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::pageDirtyChanged(), PathScripts.PathGetPoint.TaskPanel::pointFinish(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setClean(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setDirty(), and setupUi().
checkDegenerated
QCheckBox* MeshGui::Ui_DlgEvaluateSettings::checkDegenerated
Referenced by MeshGui::DlgEvaluateSettings::isDegeneratedFacetsChecked(), retranslateUi(), MeshGui::DlgEvaluateSettings::setDegeneratedFacetsChecked(), and setupUi().
checkFolds
QCheckBox* MeshGui::Ui_DlgEvaluateSettings::checkFolds
Referenced by MeshGui::DlgEvaluateSettings::isFoldsChecked(), retranslateUi(), MeshGui::DlgEvaluateSettings::setFoldsChecked(), and setupUi().
checkNonmanifoldPoints
QCheckBox* MeshGui::Ui_DlgEvaluateSettings::checkNonmanifoldPoints
Referenced by MeshGui::DlgEvaluateSettings::isNonmanifoldPointsChecked(), retranslateUi(), MeshGui::DlgEvaluateSettings::setNonmanifoldPointsChecked(), and setupUi().
gridLayout
QGridLayout* MeshGui::Ui_DlgEvaluateSettings::gridLayout
Referenced by setupUi().
gridLayout_2
QGridLayout* MeshGui::Ui_DlgEvaluateSettings::gridLayout_2
Referenced by setupUi().
groupBox
QGroupBox* MeshGui::Ui_DlgEvaluateSettings::groupBox
Referenced by retranslateUi(), and setupUi().
verticalSpacer
QSpacerItem* MeshGui::Ui_DlgEvaluateSettings::verticalSpacer
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Mesh/Gui/ui_DlgEvaluateSettings.h