FreeCAD: StdMeshers_CompositeHexa_3D Class Reference
StdMeshers_CompositeHexa_3D Class Reference
Computes hexahedral mesh on a box with composite sides.
#include <StdMeshers_CompositeHexa_3D.hxx>
Public Member Functions
virtual bool CheckHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, Hypothesis_Status &aStatus)
always return true
virtual bool Compute (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape)
Computes hexahedral mesh on a box with composite sides.
virtual bool Evaluate (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, MapShapeNbElems &aResMap)
StdMeshers_CompositeHexa_3D (int hypId, int studyId, SMESH_Gen *gen)
Constructor.
Public Member Functions inherited from SMESH_3D_Algo
SMESH_3D_Algo (int hypId, int studyId, SMESH_Gen *gen)
SMESH_3D_Algo (int hypId, int studyId, SMESH_Gen *gen)
virtual ~SMESH_3D_Algo ()
Public Member Functions inherited from SMESH_Algo
virtual void CancelCompute ()
Sets _computeCanceled to true. It's usage depends on implementation of a particular mesher.
virtual bool Compute (SMESH_Mesh &aMesh, SMESH_MesherHelper *aHelper)
Computes mesh without geometry.
const std::list< const SMESHDS_Hypothesis * > & GetAppliedHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, const bool ignoreAuxiliary=true) const
Returns a list of compatible hypotheses assigned to a shape in a mesh.
const SMESH_HypoFilter * GetCompatibleHypoFilter (const bool ignoreAuxiliary) const
Returns the filter recognizing only compatible hypotheses.
const std::vector< std::string > & GetCompatibleHypothesis ()
Returns all types of compatible hypotheses.
SMESH_ComputeErrorPtr GetComputeError () const
return compute error
const Features & GetFeatures () const
virtual double GetProgress () const
If possible, returns progress of computation [0.,1.].
double GetProgressByTic () const
Return compute progress by nb of calls of this method.
virtual const std::list< const SMESHDS_Hypothesis * > & GetUsedHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, const bool ignoreAuxiliary=true) const
Returns a list of compatible hypotheses used to mesh a shape.
void InitComputeError ()
initialize compute error etc. before call of Compute()
virtual std::istream & LoadFrom (std::istream &load)
Loads nothing from a stream.
bool NeedDiscreteBoundary () const
bool NeedLowerHyps (int dim) const
bool NeedShape () const
int NumberOfPoints (SMESH_Mesh &aMesh, const TopoDS_Wire &W)
bool OnlyUnaryInput () const
virtual std::ostream & SaveTo (std::ostream &save)
Saves nothing in a stream.
virtual void SetEventListener (SMESH_subMesh *subMesh)
Sets event listener to submeshes if necessary.
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)
Just return false as the algorithm does not hold parameters values.
SMESH_Algo (int hypId, int studyId, SMESH_Gen *gen)
Creates algorithm.
std::vector< SMESH_subMesh * > & SubMeshesToCompute ()
virtual void SubmeshRestored (SMESH_subMesh *subMesh)
Allow algo to do something after persistent restoration.
bool SupportSubmeshes () const
virtual ~ SMESH_Algo ()
Destructor.
Public Member Functions inherited from SMESH_Hypothesis
void ClearParameters ()
virtual bool DataDependOnParams () const
The returned value is used by NotifySubMeshesHypothesisModification() to decide to call subMesh->AlgoStateEngine(MODIF_HYP, hyp) or not if subMesh is ready to be computed (algo+hyp==OK) but not yet computed. True result is reasonable for example if EventListeners depend on parameters of hypothesis.
virtual int GetDim () const
SMESH_Gen * GetGen () const
char * GetLastParameters () const
virtual const char * GetLibName () const
SMESH_Mesh * GetMeshByPersistentID (int id)
Find a mesh with given persistent ID.
char * GetParameters () const
virtual int GetShapeType () const
int GetStudyId () const
virtual bool IsAuxiliary () const
Return true if me is an auxiliary hypothesis.
virtual void NotifySubMeshesHypothesisModification ()
void SetLastParameters (const char *theParameters)
void SetLibName (const char *theLibName)
void SetParameters (const char *theParameters)
SMESH_Hypothesis (int hypId, int studyId, SMESH_Gen *gen)
virtual ~SMESH_Hypothesis ()
Public Member Functions inherited from SMESHDS_Hypothesis
int GetID () const
const char * GetName () const
int GetType () const
bool IsSameName (const SMESHDS_Hypothesis &other) const
Compare types of hypotheses.
bool operator!= (const SMESHDS_Hypothesis &other) const
virtual bool operator== (const SMESHDS_Hypothesis &other) const
SMESHDS_Hypothesis (int hypId)
virtual ~SMESHDS_Hypothesis ()
Additional Inherited Members
Public Types inherited from SMESH_Algo
enum EMeshError { MEr_OK = 0, MEr_HOLES, MEr_BAD_ORI, MEr_EMPTY }
Public Types inherited from SMESH_Hypothesis
enum Hypothesis_Status {
HYP_OK = 0, HYP_MISSING, HYP_CONCURENT, HYP_BAD_PARAMETER,
HYP_HIDDEN_ALGO, HYP_HIDING_ALGO, HYP_UNKNOWN_FATAL, HYP_INCOMPATIBLE,
HYP_NOTCONFORM, HYP_ALREADY_EXIST, HYP_BAD_DIM, HYP_BAD_SUBSHAPE,
HYP_BAD_GEOMETRY, HYP_NEED_SHAPE, HYP_INCOMPAT_HYPS
}
Public Types inherited from SMESHDS_Hypothesis
enum hypothesis_type {
PARAM_ALGO, ALGO_0D, ALGO_1D, ALGO_2D,
ALGO_3D
}
Static Public Member Functions inherited from SMESH_Algo
static GeomAbs_Shape Continuity (TopoDS_Edge E1, TopoDS_Edge E2)
Return continuity of two edges.
static double EdgeLength (const TopoDS_Edge &E)
Compute length of an edge.
static const Features & GetFeatures (const std::string &algoType)
Returns a structure describing algorithm features.
static EMeshError GetMeshError (SMESH_subMesh *subMesh)
Finds topological errors of a sub-mesh.
static bool GetNodeParamOnEdge (const SMESHDS_Mesh *theMesh, const TopoDS_Edge &theEdge, std::vector< double > &theParams)
Fill vector of node parameters on geometrical edge, including vertex nodes.
static bool GetSortedNodesOnEdge (const SMESHDS_Mesh *theMesh, const TopoDS_Edge &theEdge, const bool ignoreMediumNodes, std::map< double, const SMDS_MeshNode * > &theNodes, const SMDSAbs_ElementType typeToCheck=SMDSAbs_All)
Fill map of node parameter on geometrical edge to node it-self.
static bool IsContinuous (const TopoDS_Edge &E1, const TopoDS_Edge &E2)
Return true if an edge can be considered as a continuation of another.
static bool isDegenerated (const TopoDS_Edge &E)
Return true if an edge has no 3D curve.
static bool IsStraight (const TopoDS_Edge &E, const bool degenResult=false)
Return true if an edge can be considered straight.
static const SMDS_MeshNode * VertexNode (const TopoDS_Vertex &V, const SMESH_Mesh *mesh)
Return the node built on a vertex. A node moved to other geometry by MergeNodes() is also returned.
static const SMDS_MeshNode * VertexNode (const TopoDS_Vertex &V, const SMESHDS_Mesh *meshDS)
Return the node built on a vertex.
static const SMDS_MeshNode * VertexNode (const TopoDS_Vertex &V, const SMESHDS_SubMesh *edgeSM, const SMESH_Mesh *mesh, const bool checkV=true)
Return the node built on a vertex. A node moved to other geometry by MergeNodes() is also returned.
Static Public Member Functions inherited from SMESH_Hypothesis
static bool IsStatusFatal (Hypothesis_Status theStatus)
Protected Member Functions inherited from SMESH_Algo
void addBadInputElement (const SMDS_MeshElement *elem)
store a bad input element preventing computation, which may be a temporary one i.e. not residing the mesh, then it will be deleted by InitComputeError()
void addBadInputElements (const SMESHDS_SubMesh *sm, const bool addNodes=false)
bool error (const SMESH_Comment &comment="")
store COMPERR_ALGO_FAILED error and comment and then return false
bool error (int error, const SMESH_Comment &comment="")
store error and comment and then return (error == COMPERR_OK)
bool error (SMESH_ComputeErrorPtr error)
store error and return error->IsOK()
Detailed Description
Computes hexahedral mesh on a box with composite sides.
The algorithm expects faces of a box to be meshed with quadrangles so that opposite box sides have equal number of quadrangles.
Constructor & Destructor Documentation
StdMeshers_CompositeHexa_3D()
StdMeshers_CompositeHexa_3D::StdMeshers_CompositeHexa_3D (int hypId, int studyId, SMESH_Gen * gen)
Constructor.
Member Function Documentation
CheckHypothesis()
bool StdMeshers_CompositeHexa_3D::CheckHypothesis (SMESH_Mesh & aMesh, const TopoDS_Shape & aShape, Hypothesis_Status & aStatus) virtual
always return true
Implements SMESH_Algo.
References SMESH_Hypothesis::HYP_OK.
Compute()
bool StdMeshers_CompositeHexa_3D::Compute (SMESH_Mesh & theMesh, const TopoDS_Shape & theShape) virtual
Computes hexahedral mesh on a box with composite sides.
Parameters
aMesh - mesh to compute
aShape - shape to mesh
Return values
bool - succes sign
Implements SMESH_Algo.
References SMESH_MesherHelper::AddNode(), SMESH_MesherHelper::AddVolume(), SMESH_Algo::error(), SMESH_Block::ID_E00z, SMESH_Block::ID_E01z, SMESH_Block::ID_E0y0, SMESH_Block::ID_E0y1, SMESH_Block::ID_E10z, SMESH_Block::ID_E11z, SMESH_Block::ID_E1y0, SMESH_Block::ID_E1y1, SMESH_Block::ID_Ex00, SMESH_Block::ID_Ex01, SMESH_Block::ID_Ex10, SMESH_Block::ID_Ex11, SMESH_Block::ID_F0yz, SMESH_Block::ID_F1yz, SMESH_Block::ID_Fx0z, SMESH_Block::ID_Fx1z, SMESH_Block::ID_Fxy0, SMESH_Block::ID_Fxy1, SMESH_Block::ID_Shell, SMESH_Block::ID_V000, SMESH_Block::ID_V001, SMESH_Block::ID_V010, SMESH_Block::ID_V011, SMESH_Block::ID_V100, SMESH_Block::ID_V101, SMESH_Block::ID_V110, SMESH_Block::ID_V111, SMESH_MesherHelper::IsQuadraticSubMesh(), SMESH_MesherHelper::SetElementsOnShape(), and SMESH_Block::ShellPoint().
Referenced by StdMeshers_Hexa_3D::Compute().
Evaluate()
bool StdMeshers_CompositeHexa_3D::Evaluate (SMESH_Mesh & theMesh, const TopoDS_Shape & theShape, MapShapeNbElems & aResMap) virtual
Evaluate
Implements SMESH_Algo.
References SMESH_Mesh::GetSubMesh().
Referenced by StdMeshers_Hexa_3D::Evaluate().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_CompositeHexa_3D.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_CompositeHexa_3D.cpp