FreeCAD: Gui::DocumentObjectItem Class Reference
Gui::DocumentObjectItem Class Reference
The link between the tree and a document object.
#include <Tree.h>
Public Member Functions
void displayStatusInfo ()
DocumentObjectItem (DocumentItem *ownerDocItem, DocumentObjectDataPtr data)
App::DocumentObject * getFullSubName (std::ostringstream &str, DocumentObjectItem *parent=0) const
const char * getName () const
DocumentItem * getOwnerDocument () const
DocumentItem * getParentDocument () const
DocumentObjectItem * getParentItem () const
App::DocumentObject * getRelativeParent (std::ostringstream &str, DocumentObjectItem *cousin, App::DocumentObject **topParent=0, std::string *topSubname=0) const
int getSubName (std::ostringstream &str, App::DocumentObject *&topParent) const
TreeWidget * getTree () const
const char * getTreeName () const
bool isChildOfItem (DocumentObjectItem *)
int isGroup () const
bool isLink () const
bool isLinkFinal () const
int isParentGroup () const
bool isParentLink () const
Gui::ViewProviderDocumentObject * object () const
bool requiredAtRoot (bool excludeSelf=true) const
void restoreBackground ()
void setData (int column, int role, const QVariant &value)
void setExpandedStatus (bool)
void setHighlight (bool set, HighlightMode mode=HighlightMode::LightBlue)
void testStatus (bool resetStatus)
void testStatus (bool resetStatus, QIcon &icon1, QIcon &icon2)
~DocumentObjectItem ()
Friends
class DocumentItem
class TreeWidget
Detailed Description
The link between the tree and a document object.
Every object in the document gets its associated DocumentObjectItem which controls the visibility and the functions of the object.
Author
Werner Mayer
Constructor & Destructor Documentation
DocumentObjectItem()
DocumentObjectItem::DocumentObjectItem (DocumentItem * ownerDocItem, DocumentObjectDataPtr data)
~DocumentObjectItem()
DocumentObjectItem::~DocumentObjectItem ()
References Gui::DocumentItem::getTree().
Member Function Documentation
displayStatusInfo()
void DocumentObjectItem::displayStatusInfo ()
References Gui::MainWindow::Err, Gui::getMainWindow(), Base::Type::getName(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), App::DocumentObject::getStatusString(), Base::Persistence::getTypeId(), App::DocumentObject::isError(), App::DocumentObject::mustExecute(), object(), Gui::MainWindow::showMessage(), Gui::MainWindow::showStatus(), and draftutils.translate::translate().
getFullSubName()
App::DocumentObject * DocumentObjectItem::getFullSubName (std::ostringstream & str, DocumentObjectItem * parent = 0) const
References getName(), Gui::ViewProviderDocumentObject::getObject(), getParentItem(), isGroup(), and object().
getName()
const char * DocumentObjectItem::getName (void) const
References App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), and object().
Referenced by Gui::DocumentItem::findItem(), getFullSubName(), getRelativeParent(), and setData().
getOwnerDocument()
DocumentItem * DocumentObjectItem::getOwnerDocument () const
Referenced by Gui::TreeWidget::dropEvent(), Gui::TreeWidget::mouseDoubleClickEvent(), Gui::TreeWidget::onShowHidden(), Gui::TreeWidget::onStartEditing(), Gui::DocumentItem::populateItem(), requiredAtRoot(), setExpandedStatus(), and testStatus().
getParentDocument()
DocumentItem * DocumentObjectItem::getParentDocument () const
References Gui::TreeWidget::getDocumentItem(), and getTree().
getParentItem()
DocumentObjectItem * DocumentObjectItem::getParentItem () const
References Gui::TreeWidget::ObjectType.
Referenced by Gui::TreeWidget::dragMoveEvent(), Gui::TreeWidget::dropEvent(), getFullSubName(), getSubName(), isGroup(), isParentGroup(), isParentLink(), requiredAtRoot(), testStatus(), and Gui::DocumentItem::updateItemSelection().
getRelativeParent()
App::DocumentObject * DocumentObjectItem::getRelativeParent (std::ostringstream & str, DocumentObjectItem * cousin, App::DocumentObject ** topParent = 0, std::string * topSubname = 0) const
References getName(), and getSubName().
getSubName()
int DocumentObjectItem::getSubName (std::ostringstream & str, App::DocumentObject *& topParent) const
References getParentItem().
Referenced by Gui::TreeWidget::dropEvent(), getRelativeParent(), Gui::TreeWidget::onPreSelectTimer(), Gui::DocumentItem::slotExpandObject(), Gui::DocumentItem::slotHighlightObject(), and Gui::DocumentItem::updateItemSelection().
getTree()
TreeWidget * DocumentObjectItem::getTree () const
Referenced by getParentDocument(), and testStatus().
getTreeName()
const char * DocumentObjectItem::getTreeName () const
isChildOfItem()
bool DocumentObjectItem::isChildOfItem (DocumentObjectItem * item)
Referenced by Gui::DocumentItem::populateItem().
isGroup()
int DocumentObjectItem::isGroup () const
References App::DocumentObject::getLinkedObject(), Gui::ViewProviderDocumentObject::getObject(), getParentItem(), and object().
Referenced by Gui::TreeWidget::dropEvent(), getFullSubName(), and Gui::DocumentItem::updateItemSelection().
isLink()
bool DocumentObjectItem::isLink () const
References App::DocumentObject::getLinkedObject(), Gui::ViewProviderDocumentObject::getObject(), and object().
isLinkFinal()
bool DocumentObjectItem::isLinkFinal () const
References App::DocumentObject::getLinkedObject(), Gui::ViewProviderDocumentObject::getObject(), and object().
isParentGroup()
int DocumentObjectItem::isParentGroup () const
References getParentItem().
Referenced by Gui::DocumentItem::findItemByObject(), and Gui::DocumentItem::getTopParent().
isParentLink()
bool DocumentObjectItem::isParentLink () const
References getParentItem().
object()
Gui::ViewProviderDocumentObject * DocumentObjectItem::object () const
Referenced by Gui::TreeWidget::contextMenuEvent(), Gui::TreeWidgetEditDelegate::createEditor(), displayStatusInfo(), Gui::TreeWidget::dragMoveEvent(), Gui::TreeWidget::dropEvent(), Gui::DocumentItem::findItem(), getFullSubName(), getName(), Gui::TreeWidget::getSelection(), isGroup(), isLink(), isLinkFinal(), Gui::TreeWidget::mimeData(), Gui::TreeWidget::mouseDoubleClickEvent(), Gui::TreeWidget::onCreateGroup(), Gui::TreeWidget::onFinishEditing(), Gui::TreeWidget::onMarkRecompute(), Gui::TreeWidget::onPreSelectTimer(), Gui::TreeWidget::onRecomputeObject(), Gui::TreeWidget::onStartEditing(), Gui::DocumentItem::populateItem(), Gui::DocumentItem::selectItems(), setData(), setExpandedStatus(), Gui::DocumentItem::slotResetEdit(), testStatus(), and Gui::DocumentItem::updateItemSelection().
requiredAtRoot()
bool DocumentObjectItem::requiredAtRoot (bool excludeSelf = true) const
References getOwnerDocument(), and getParentItem().
Referenced by Gui::DocumentItem::populateItem().
restoreBackground()
void DocumentObjectItem::restoreBackground ()
setData()
void DocumentObjectItem::setData (int column, int role, const QVariant & value)
References getName(), Gui::ViewProviderDocumentObject::getObject(), and object().
Referenced by Gui::DocumentItem::slotResetEdit(), and testStatus().
setExpandedStatus()
void DocumentObjectItem::setExpandedStatus (bool on)
References App::Expand, Gui::ViewProviderDocumentObject::getObject(), getOwnerDocument(), object(), and App::DocumentObject::setStatus().
setHighlight()
void DocumentObjectItem::setHighlight (bool set, Gui::HighlightMode high = HighlightMode::LightBlue)
References App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), ParameterGrp::GetUnsigned(), and Gui::UserDefined.
Referenced by Gui::DocumentItem::populateItem(), and Gui::DocumentItem::slotHighlightObject().
testStatus() [1/2]
void DocumentObjectItem::testStatus (bool resetStatus)
References testStatus().
testStatus() [2/2]
void DocumentObjectItem::testStatus (bool resetStatus, QIcon & icon1, QIcon & icon2)
References Gui::BitmapFactory(), Gui::BitmapFactoryInst::BottomRight, Gui::DocumentItem::document(), Gui::ViewProviderDocumentObject::getDocument(), Gui::ViewProvider::getIcon(), App::DocumentObject::getLinkedObject(), App::DocumentObject::getNameInDocument(), App::GroupExtension::getObject(), Gui::ViewProviderDocumentObject::getObject(), getOwnerDocument(), getParentItem(), getTree(), App::DocumentObject::isElementVisible(), App::DocumentObject::isError(), Gui::ViewProvider::isShow(), App::DocumentObject::isTouched(), Gui::BitmapFactoryInst::merge(), App::DocumentObject::mustExecute(), object(), setData(), Gui::ViewProviderDocumentObject::showInTree(), Gui::BitmapFactoryInst::TopLeft, and Gui::BitmapFactoryInst::TopRight.
Referenced by Gui::DocumentItem::createNewItem(), and testStatus().
Friends And Related Function Documentation
DocumentItem
friend class DocumentItem friend
TreeWidget
friend class TreeWidget friend
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Tree.h
Sources/FreeCAD/src/Gui/Tree.cpp