FreeCAD: Gui::PythonDebugStderr Class Reference
Gui::PythonDebugStderr Class Reference
#include <PythonDebugger.h>
Public Member Functions
PythonDebugStderr ()
Py::Object repr ()
Py::Object write (const Py::Tuple &)
~PythonDebugStderr ()
Static Public Member Functions
static void init_type (void)
Detailed Description
Author
Werner Mayer
Constructor & Destructor Documentation
PythonDebugStderr()
PythonDebugStderr::PythonDebugStderr ()
~PythonDebugStderr()
PythonDebugStderr::~PythonDebugStderr ()
Member Function Documentation
init_type()
void PythonDebugStderr::init_type (void) static
References write().
Referenced by Gui::PythonDebugModule::init_module().
repr()
Py::Object PythonDebugStderr::repr ()
write()
Py::Object PythonDebugStderr::write (const Py::Tuple & args)
References Base::Console(), and Base::ConsoleSingleton::Error().
Referenced by init_type(), and gzip_utf8.GzipFile::seek().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/PythonDebugger.h
Sources/FreeCAD/src/Gui/PythonDebugger.cpp