FreeCAD: Sketcher::SketchGeometryExtension Class Reference
Sketcher::SketchGeometryExtension Class Reference
#include <SketchGeometryExtension.h>
Public Member Functions
virtual std::unique_ptr< Part::GeometryExtension > copy (void) const override
virtual long getId () const override
virtual InternalType::InternalType getInternalType () const override
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
virtual void setGeometryMode (int flag, bool v=true) override
virtual void setId (long id) override
virtual void setInternalType (InternalType::InternalType type) override
SketchGeometryExtension ()
SketchGeometryExtension (long cid)
virtual bool testGeometryMode (int flag) const override
virtual ~SketchGeometryExtension () override=default
Public Member Functions inherited from Part::GeometryPersistenceExtension
void Restore (Base::XMLReader &)
void Save (Base::Writer &) const
virtual ~GeometryPersistenceExtension ()=default
Public Member Functions inherited from Part::GeometryExtension
PyObject * copyPyObject () const
const std::string & getName () const
virtual void notifyAttachment (Part::Geometry *)
void setName (const std::string &str)
virtual ~GeometryExtension ()=default
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual Type getTypeId (void) const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static bool getGeometryModeFromName (std::string str, GeometryMode::GeometryMode &type)
static bool getInternalTypeFromName (std::string str, InternalType::InternalType &type)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Public Attributes
constexpr static std::array< const char *, GeometryMode::NumGeometryMode > geometrymode2str {{ "Blocked", "Construction" }}
constexpr static std::array< const char *, InternalType::NumInternalGeometryType > internaltype2str {{ "None", "EllipseMajorDiameter", "EllipseMinorDiameter","EllipseFocus1", "EllipseFocus2", "HyperbolaMajor", "HyperbolaMinor", "HyperbolaFocus", "ParabolaFocus", "BSplineControlPoint", "BSplineKnotPoint" }}
Protected Member Functions
virtual void copyAttributes (Part::GeometryExtension *cpy) const override
virtual void restoreAttributes (Base::XMLReader &reader) override
virtual void saveAttributes (Base::Writer &writer) const override
Protected Member Functions inherited from Part::GeometryExtension
GeometryExtension ()
GeometryExtension (const GeometryExtension &obj)=default
GeometryExtension & operator= (const GeometryExtension &obj)=default
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
SketchGeometryExtension() [1/2]
SketchGeometryExtension::SketchGeometryExtension ()
Referenced by getPyObject().
SketchGeometryExtension() [2/2]
SketchGeometryExtension::SketchGeometryExtension (long cid)
~SketchGeometryExtension()
virtual Sketcher::SketchGeometryExtension::~SketchGeometryExtension () override virtual default
Member Function Documentation
copy()
std::unique_ptr< Part::GeometryExtension > SketchGeometryExtension::copy (void) const override virtual
Implements Part::GeometryExtension.
References copyAttributes(), and draftfunctions.move::move().
copyAttributes()
void SketchGeometryExtension::copyAttributes (Part::GeometryExtension * cpy) const override protected virtual
Reimplemented from Part::GeometryExtension.
References Part::GeometryExtension::copyAttributes().
Referenced by copy().
getGeometryModeFromName()
bool SketchGeometryExtension::getGeometryModeFromName (std::string str, GeometryMode::GeometryMode & type) static
References Sketcher::end, and geometrymode2str.
Referenced by Sketcher::GeometryFacadePy::setGeometryMode(), and Sketcher::GeometryFacadePy::testGeometryMode().
getId()
virtual long Sketcher::SketchGeometryExtension::getId () const override virtual
Implements Sketcher::ISketchGeometryExtension.
Referenced by Sketcher::SketchGeometryExtensionPy::representation().
getInternalType()
virtual InternalType::InternalType Sketcher::SketchGeometryExtension::getInternalType () const override virtual
Implements Sketcher::ISketchGeometryExtension.
Referenced by Sketcher::SketchGeometryExtensionPy::getInternalType().
getInternalTypeFromName()
bool SketchGeometryExtension::getInternalTypeFromName (std::string str, InternalType::InternalType & type) static
References Sketcher::end, and internaltype2str.
Referenced by Sketcher::ExternalGeometryFacadePy::setInternalType(), Sketcher::GeometryFacadePy::setInternalType(), and Sketcher::SketchGeometryExtensionPy::setInternalType().
getPyObject()
PyObject * SketchGeometryExtension::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
References SketchGeometryExtension().
restoreAttributes()
void SketchGeometryExtension::restoreAttributes (Base::XMLReader & reader) override protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
References Base::XMLReader::getAttribute(), Base::XMLReader::getAttributeAsInteger(), Base::XMLReader::hasAttribute(), and Part::GeometryPersistenceExtension::restoreAttributes().
saveAttributes()
void SketchGeometryExtension::saveAttributes (Base::Writer & writer) const override protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
References Part::GeometryPersistenceExtension::saveAttributes(), and Base::Writer::Stream().
setGeometryMode()
virtual void Sketcher::SketchGeometryExtension::setGeometryMode (int flag, bool v = true) override virtual
Implements Sketcher::ISketchGeometryExtension.
Referenced by Sketcher::SketchGeometryExtensionPy::setBlocked(), Sketcher::SketchGeometryExtensionPy::setConstruction(), and Sketcher::SketchGeometryExtensionPy::setGeometryMode().
setId()
virtual void Sketcher::SketchGeometryExtension::setId (long id) override virtual
Implements Sketcher::ISketchGeometryExtension.
Referenced by Sketcher::SketchGeometryExtensionPy::PyInit(), and Sketcher::SketchGeometryExtensionPy::setId().
setInternalType()
virtual void Sketcher::SketchGeometryExtension::setInternalType (InternalType::InternalType type) override virtual
Implements Sketcher::ISketchGeometryExtension.
Referenced by Sketcher::SketchGeometryExtensionPy::setInternalType().
testGeometryMode()
virtual bool Sketcher::SketchGeometryExtension::testGeometryMode (int flag) const override virtual
Implements Sketcher::ISketchGeometryExtension.
Member Data Documentation
geometrymode2str
constexpr std::array< const char *, GeometryMode::NumGeometryMode > SketchGeometryExtension::geometrymode2str {{ "Blocked", "Construction" }} static constexpr
Referenced by getGeometryModeFromName().
internaltype2str
constexpr std::array< const char *, InternalType::NumInternalGeometryType > SketchGeometryExtension::internaltype2str {{ "None", "EllipseMajorDiameter", "EllipseMinorDiameter","EllipseFocus1", "EllipseFocus2", "HyperbolaMajor", "HyperbolaMinor", "HyperbolaFocus", "ParabolaFocus", "BSplineControlPoint", "BSplineKnotPoint" }} static constexpr
Referenced by Sketcher::ExternalGeometryFacadePy::getInternalType(), Sketcher::GeometryFacadePy::getInternalType(), Sketcher::SketchGeometryExtensionPy::getInternalType(), and getInternalTypeFromName().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sketcher/App/SketchGeometryExtension.h
Sources/FreeCAD/src/Mod/Sketcher/App/SketchGeometryExtension.cpp