FreeCAD: SMESH::Controls::MultiConnection2D Class Reference
SMESH::Controls::MultiConnection2D Class Reference
#include <SMESH_ControlsDef.hxx>
Classes
struct Value
Public Types
typedef std::map< Value, int > MValues
Public Member Functions
virtual double GetBadRate (double Value, int nbNodes) const
virtual SMDSAbs_ElementType GetType () const
virtual double GetValue (const TSequenceOfXYZ &thePoints)
virtual double GetValue (long theElementId)
void GetValues (MValues &theValues)
Public Member Functions inherited from SMESH::Controls::NumericalFunctor
void GetHistogram (int nbIntervals, std::vector< int > &nbEvents, std::vector< double > &funValues, const std::vector< int > &elements, const double *minmax=0, const bool isLogarithmic=false)
Return histogram of functor values.
bool GetPoints (const int theId, TSequenceOfXYZ &theRes) const
long GetPrecision () const
NumericalFunctor ()
double Round (const double &value)
virtual void SetMesh (const SMDS_Mesh *theMesh)
void SetPrecision (const long thePrecision)
Public Member Functions inherited from SMESH::Controls::Functor
virtual ~Functor ()
Additional Inherited Members
Static Public Member Functions inherited from SMESH::Controls::NumericalFunctor
static bool GetPoints (const SMDS_MeshElement *theElem, TSequenceOfXYZ &theRes)
Protected Attributes inherited from SMESH::Controls::NumericalFunctor
const SMDS_MeshElement * myCurrElement
const SMDS_Mesh * myMesh
long myPrecision
double myPrecisionValue
Member Typedef Documentation
MValues
typedef std::map<Value,int> SMESH::Controls::MultiConnection2D::MValues
Member Function Documentation
GetBadRate()
double MultiConnection2D::GetBadRate (double Value, int nbNodes) const virtual
Implements SMESH::Controls::NumericalFunctor.
GetType()
SMDSAbs_ElementType MultiConnection2D::GetType () const virtual
Implements SMESH::Controls::NumericalFunctor.
GetValue() [1/2]
double MultiConnection2D::GetValue (const TSequenceOfXYZ & thePoints) virtual
Reimplemented from SMESH::Controls::NumericalFunctor.
GetValue() [2/2]
double MultiConnection2D::GetValue (long theElementId) virtual
Reimplemented from SMESH::Controls::NumericalFunctor.
References SMDS_Mesh::FindElement(), SMDS_MeshElement::GetID(), SMDS_MeshNode::GetInverseElementIterator(), SMDS_MeshElement::GetType(), SMESH::Controls::NumericalFunctor::myMesh, SMDS_MeshElement::NbNodes(), and SMDS_MeshElement::nodesIterator().
GetValues()
void MultiConnection2D::GetValues (MValues & theValues)
References SMDS_Mesh::facesIterator(), SMDS_MeshElement::GetID(), SMDS_MeshElement::IsQuadratic(), SMESH::Controls::NumericalFunctor::myMesh, and SMDS_MeshElement::nodesIterator().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp