FreeCAD: DrawSketchHandlerCircle Class Reference
DrawSketchHandlerCircle Class Reference
Public Types
enum SelectMode { STATUS_SEEK_First, STATUS_SEEK_Second, STATUS_Close }
mode table
Public Member Functions
virtual void activated (ViewProviderSketch *)
DrawSketchHandlerCircle ()
virtual void mouseMove (Base::Vector2d onSketchPos)
virtual bool pressButton (Base::Vector2d onSketchPos)
virtual bool releaseButton (Base::Vector2d onSketchPos)
virtual ~DrawSketchHandlerCircle ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::none, bool createowncommand=true)
virtual void deactivated (ViewProviderSketch *)
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual void quit (void)
virtual void registerPressedKey (bool, int)
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Attributes
std::vector< Base::Vector2d > EditCurve
SelectMode Mode
std::vector< AutoConstraint > sugConstr1
std::vector< AutoConstraint > sugConstr2
Protected Attributes inherited from SketcherGui::DrawSketchHandler
QCursor actCursor
QPixmap actCursorPixmap
QCursor oldCursor
ViewProviderSketch * sketchgui
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
void addCursorTail (std::vector< QPixmap > &pixmaps)
void applyCursor (QCursor &newCursor)
void applyCursor (void)
qreal devicePixelRatio ()
unsigned long getCrosshairColor ()
void setCrosshairColor ()
void setCrosshairCursor (const char *svgName)
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
Sets a cursor for 3D inventor view.
void setSvgCursor (const QString &svgName, int x, int y, const std::map< unsigned long, unsigned long > &colorMapping=std::map< unsigned long, unsigned long >())
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
void unsetCursor (void)
Member Enumeration Documentation
SelectMode
enum DrawSketchHandlerCircle::SelectMode
mode table
Enumerator
STATUS_SEEK_First
enum value -—.
STATUS_SEEK_Second
enum value -—.
STATUS_Close
Constructor & Destructor Documentation
DrawSketchHandlerCircle()
DrawSketchHandlerCircle::DrawSketchHandlerCircle ()
~DrawSketchHandlerCircle()
virtual DrawSketchHandlerCircle::~DrawSketchHandlerCircle () virtual
Member Function Documentation
activated()
virtual void DrawSketchHandlerCircle::activated (ViewProviderSketch *) virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::setCrosshairCursor().
mouseMove()
virtual void DrawSketchHandlerCircle::mouseMove (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::applyCursor(), SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, Mode, SketcherGui::DrawSketchHandler::renderSuggestConstraintsCursor(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), SketcherGui::DrawSketchHandler::setPositionText(), SketcherGui::DrawSketchHandler::sketchgui, STATUS_SEEK_First, STATUS_SEEK_Second, sugConstr1, sugConstr2, Base::Vector2d::x, and Base::Vector2d::y.
pressButton()
virtual bool DrawSketchHandlerCircle::pressButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References EditCurve, Mode, STATUS_Close, STATUS_SEEK_First, and STATUS_SEEK_Second.
releaseButton()
virtual bool DrawSketchHandlerCircle::releaseButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), SketcherGui::DrawSketchHandler::applyCursor(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Base::Console(), SketcherGui::DrawSketchHandler::createAutoConstraints(), SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, Base::ConsoleSingleton::Error(), SketcherGui::geometryCreationMode, App::GetApplication(), ParameterGrp::GetBool(), SketcherGui::DrawSketchHandler::getHighestCurveIndex(), Gui::ViewProviderDocumentObject::getObject(), App::Application::GetParameterGroupByPath(), Sketcher::mid, Mode, Sketcher::none, Gui::Command::openCommand(), SketcherGui::ViewProviderSketch::purgeHandler(), draftutils.translate::QT_TRANSLATE_NOOP, SketcherGui::DrawSketchHandler::resetPositionText(), SketcherGui::DrawSketchHandler::sketchgui, STATUS_Close, STATUS_SEEK_First, sugConstr1, sugConstr2, SketcherGui::tryAutoRecomputeIfNotSolve(), and SketcherGui::DrawSketchHandler::unsetCursor().
Member Data Documentation
EditCurve
std::vector<Base::Vector2d> DrawSketchHandlerCircle::EditCurve protected
Referenced by mouseMove(), pressButton(), and releaseButton().
Mode
SelectMode DrawSketchHandlerCircle::Mode protected
Referenced by mouseMove(), pressButton(), and releaseButton().
sugConstr1
std::vector<AutoConstraint> DrawSketchHandlerCircle::sugConstr1 protected
Referenced by mouseMove(), and releaseButton().
sugConstr2
std::vector<AutoConstraint> DrawSketchHandlerCircle::sugConstr2 protected
Referenced by mouseMove(), and releaseButton().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/Gui/CommandCreateGeo.cpp