FreeCAD: cSimTool Class Reference
cSimTool Class Reference
#include <VolSim.h>
Public Member Functions
cSimTool (const TopoDS_Shape &toolShape, float res)
float GetToolProfileAt (float pos)
bool isInside (const TopoDS_Shape &toolShape, Base::Vector3d pnt, float res)
~cSimTool ()
Public Attributes
float length
std::vector< toolShapePoint > m_toolShape
float radius
Constructor & Destructor Documentation
cSimTool()
cSimTool::cSimTool (const TopoDS_Shape & toolShape, float res)
References toolShapePoint::heightPos, isInside(), m_toolShape, radius, toolShapePoint::radiusPos, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
~cSimTool()
cSimTool::~cSimTool ()
Member Function Documentation
GetToolProfileAt()
float cSimTool::GetToolProfileAt (float pos)
References m_toolShape, and radius.
Referenced by cStock::ApplyCircularTool(), and cStock::ApplyLinearTool().
isInside()
bool cSimTool::isInside (const TopoDS_Shape & toolShape, Base::Vector3d pnt, float res)
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by cSimTool().
Member Data Documentation
length
float cSimTool::length
Referenced by Mod.PartDesign.Scripts.FilletArc.Vector::norm().
m_toolShape
std::vector< toolShapePoint > cSimTool::m_toolShape
Referenced by cSimTool(), and GetToolProfileAt().
radius
float cSimTool::radius
Referenced by cStock::ApplyCircularTool(), cStock::ApplyLinearTool(), cSimTool(), and GetToolProfileAt().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Path/PathSimulator/App/VolSim.h
Sources/FreeCAD/src/Mod/Path/PathSimulator/App/VolSim.cpp