FreeCAD: PartGui::Ui_DlgBooleanOperation Class Reference
PartGui::Ui_DlgBooleanOperation Class Reference
#include <ui_DlgBooleanOperation.h>
Public Member Functions
void retranslateUi (QWidget *PartGui__DlgBooleanOperation)
void setupUi (QWidget *PartGui__DlgBooleanOperation)
Public Attributes
QRadioButton * diffButton
QTreeWidget * firstShape
QGridLayout * gridLayout
QGridLayout * gridLayout1
QGroupBox * groupBox
QSpacerItem * horizontalSpacer
QRadioButton * interButton
QTreeWidget * secondShape
QRadioButton * sectionButton
QPushButton * swapButton
QRadioButton * unionButton
Member Function Documentation
retranslateUi()
void PartGui::Ui_DlgBooleanOperation::retranslateUi (QWidget * PartGui__DlgBooleanOperation)
References diffButton, firstShape, groupBox, interButton, secondShape, sectionButton, swapButton, draftguitools.gui_setstyle::translate, and unionButton.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void PartGui::Ui_DlgBooleanOperation::setupUi (QWidget * PartGui__DlgBooleanOperation)
References diffButton, firstShape, gridLayout, gridLayout1, groupBox, horizontalSpacer, interButton, retranslateUi(), secondShape, sectionButton, swapButton, and unionButton.
Member Data Documentation
diffButton
QRadioButton* PartGui::Ui_DlgBooleanOperation::diffButton
Referenced by retranslateUi(), and setupUi().
firstShape
QTreeWidget* PartGui::Ui_DlgBooleanOperation::firstShape
Referenced by retranslateUi(), and setupUi().
gridLayout
QGridLayout* PartGui::Ui_DlgBooleanOperation::gridLayout
Referenced by setupUi().
gridLayout1
QGridLayout* PartGui::Ui_DlgBooleanOperation::gridLayout1
Referenced by setupUi().
groupBox
QGroupBox* PartGui::Ui_DlgBooleanOperation::groupBox
Referenced by retranslateUi(), and setupUi().
horizontalSpacer
QSpacerItem* PartGui::Ui_DlgBooleanOperation::horizontalSpacer
Referenced by setupUi().
interButton
QRadioButton* PartGui::Ui_DlgBooleanOperation::interButton
Referenced by retranslateUi(), and setupUi().
secondShape
QTreeWidget* PartGui::Ui_DlgBooleanOperation::secondShape
Referenced by retranslateUi(), and setupUi().
sectionButton
QRadioButton* PartGui::Ui_DlgBooleanOperation::sectionButton
Referenced by retranslateUi(), and setupUi().
swapButton
QPushButton* PartGui::Ui_DlgBooleanOperation::swapButton
Referenced by retranslateUi(), and setupUi().
unionButton
QRadioButton* PartGui::Ui_DlgBooleanOperation::unionButton
Referenced by retranslateUi(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Part/Gui/ui_DlgBooleanOperation.h