FreeCAD: SMESH_Block::TEdge Class Reference
SMESH_Block::TEdge Class Reference
#include <SMESH_Block.hxx>
Public Member Functions
int CoordInd () const
double EndParam (int i) const
Adaptor3d_Curve * GetCurve () const
double GetU (const gp_XYZ &theParams) const
const gp_XYZ & NodeXYZ (int i) const
gp_XYZ Point (const gp_XYZ &theParams) const
void Set (const int edgeID, Adaptor3d_Curve *curve, const bool isForward)
Set edge data.
void Set (const int edgeID, const gp_XYZ &node1, const gp_XYZ &node2)
Set coordinates of nodes at edge ends to work with mesh block.
TEdge ()
~TEdge ()
Destructor.
Constructor & Destructor Documentation
TEdge()
SMESH_Block::TEdge::TEdge ()
~TEdge()
SMESH_Block::TEdge::~TEdge ()
Destructor.
Member Function Documentation
CoordInd()
int SMESH_Block::TEdge::CoordInd () const
EndParam()
double SMESH_Block::TEdge::EndParam (int i) const
GetCurve()
Adaptor3d_Curve* SMESH_Block::TEdge::GetCurve () const
Referenced by StdMeshers_PrismAsBlock::Init().
GetU()
double SMESH_Block::TEdge::GetU (const gp_XYZ & theParams) const
NodeXYZ()
const gp_XYZ& SMESH_Block::TEdge::NodeXYZ (int i) const
Referenced by SMESH_Block::TFace::Set().
Point()
gp_XYZ SMESH_Block::TEdge::Point (const gp_XYZ & theParams) const
Referenced by SMESH_Block::ComputeParameters().
Set() [1/2]
void SMESH_Block::TEdge::Set (const int edgeID, Adaptor3d_Curve * curve, const bool isForward)
Set edge data.
Parameters
edgeID - block sub-shape ID
curve - edge geometry
isForward - is curve orientation coincides with edge orientation in the block
References SMESH_Block::GetCoordIndOnEdge().
Referenced by StdMeshers_PrismAsBlock::Init(), SMESH_Block::LoadBlockShapes(), and SMESH_Block::LoadMeshBlock().
Set() [2/2]
void SMESH_Block::TEdge::Set (const int edgeID, const gp_XYZ & node1, const gp_XYZ & node2)
Set coordinates of nodes at edge ends to work with mesh block.
Parameters
edgeID - block sub-shape ID
node1 - coordinates of node with lower ID
node2 - coordinates of node with upper ID
References SMESH_Block::GetCoordIndOnEdge().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_Block.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/SMESH_Block.cpp