FreeCAD: NaviCubeImplementation Class Reference
NaviCubeImplementation Class Reference
Public Types
enum {
TEX_FRONT = 1 , TEX_REAR , TEX_TOP , TEX_BOTTOM ,
TEX_LEFT , TEX_RIGHT , TEX_FRONT_FACE , TEX_CORNER_FACE ,
TEX_EDGE_FACE , TEX_FRONT_TOP , TEX_FRONT_BOTTOM , TEX_FRONT_LEFT ,
TEX_FRONT_RIGHT , TEX_REAR_TOP , TEX_REAR_BOTTOM , TEX_REAR_LEFT ,
TEX_REAR_RIGHT , TEX_TOP_LEFT , TEX_TOP_RIGHT , TEX_BOTTOM_LEFT ,
TEX_BOTTOM_RIGHT , TEX_BOTTOM_RIGHT_REAR , TEX_BOTTOM_FRONT_RIGHT , TEX_BOTTOM_LEFT_FRONT ,
TEX_BOTTOM_REAR_LEFT , TEX_TOP_RIGHT_FRONT , TEX_TOP_FRONT_LEFT , TEX_TOP_LEFT_REAR ,
TEX_TOP_REAR_RIGHT , TEX_ARROW_NORTH , TEX_ARROW_SOUTH , TEX_ARROW_EAST ,
TEX_ARROW_WEST , TEX_ARROW_RIGHT , TEX_ARROW_LEFT , TEX_DOT_BACKSIDE ,
TEX_VIEW_MENU_ICON , TEX_VIEW_MENU_FACE
}
enum { DIR_UP , DIR_RIGHT , DIR_OUT }
enum { SHAPE_SQUARE , SHAPE_EDGE , SHAPE_CORNER }
Public Member Functions
void createContextMenu (const std::vector< std::string > &cmd)
void drawNaviCube ()
void drawNaviCube (bool picking)
NaviCubeImplementation (Gui::View3DInventorViewer *)
virtual void OnChange (ParameterGrp::SubjectType &rCaller, ParameterGrp::MessageType Reason)
Observer message from the ParameterGrp.
bool processSoEvent (const SoEvent *ev)
virtual ~NaviCubeImplementation ()
Public Attributes
QColor m_BorderColor
double m_BorderWidth
QColor m_ButtonColor
vector< int > m_Buttons
NaviCube::Corner m_Corner = NaviCube::TopRightCorner
int m_CubeWidgetPosX = 0
int m_CubeWidgetPosY = 0
int m_CubeWidgetSize = 0
bool m_Dragging = false
vector< Face * > m_Faces
QColor m_FrontFaceColor
vector< QOpenGLTexture * > m_glTextures
QColor m_HiliteColor
int m_HiliteId = 0
vector< GLubyte > m_IndexArray
QMenu * m_Menu
bool m_MightDrag = false
bool m_MouseDown = false
bool m_NaviCubeInitialised = false
int m_OverSample = 4
QtGLFramebufferObject * m_PickingFramebuffer
int m_PrevHeight = 0
int m_PrevWidth = 0
QColor m_TextColor
vector< Vector2f > m_TextureCoordArray
map< int, GLuint > m_Textures
vector< Vector3f > m_VertexArray
vector< Vector3f > m_VertexArray2
Gui::View3DInventorViewer * m_View3DInventorViewer
Static Public Attributes
static vector< string > m_commands
static vector< string > m_labels
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
TEX_FRONT
TEX_REAR
TEX_TOP
TEX_BOTTOM
TEX_LEFT
TEX_RIGHT
TEX_FRONT_FACE
TEX_CORNER_FACE
TEX_EDGE_FACE
TEX_FRONT_TOP
TEX_FRONT_BOTTOM
TEX_FRONT_LEFT
TEX_FRONT_RIGHT
TEX_REAR_TOP
TEX_REAR_BOTTOM
TEX_REAR_LEFT
TEX_REAR_RIGHT
TEX_TOP_LEFT
TEX_TOP_RIGHT
TEX_BOTTOM_LEFT
TEX_BOTTOM_RIGHT
TEX_BOTTOM_RIGHT_REAR
TEX_BOTTOM_FRONT_RIGHT
TEX_BOTTOM_LEFT_FRONT
TEX_BOTTOM_REAR_LEFT
TEX_TOP_RIGHT_FRONT
TEX_TOP_FRONT_LEFT
TEX_TOP_LEFT_REAR
TEX_TOP_REAR_RIGHT
TEX_ARROW_NORTH
TEX_ARROW_SOUTH
TEX_ARROW_EAST
TEX_ARROW_WEST
TEX_ARROW_RIGHT
TEX_ARROW_LEFT
TEX_DOT_BACKSIDE
TEX_VIEW_MENU_ICON
TEX_VIEW_MENU_FACE
anonymous enum
anonymous enum
Enumerator
DIR_UP
DIR_RIGHT
DIR_OUT
anonymous enum
anonymous enum
Enumerator
SHAPE_SQUARE
SHAPE_EDGE
SHAPE_CORNER
Constructor & Destructor Documentation
NaviCubeImplementation()
NaviCubeImplementation::NaviCubeImplementation (Gui::View3DInventorViewer * viewer)
References Base::Subject< _MessageType >::Attach(), App::GetApplication(), App::Application::GetParameterGroupByPath(), m_Menu, m_PickingFramebuffer, m_View3DInventorViewer, OnChange(), and OfflineRenderingUtils::viewer().
~NaviCubeImplementation()
NaviCubeImplementation::~NaviCubeImplementation () virtual
References Base::Subject< _MessageType >::Detach(), App::GetApplication(), App::Application::GetParameterGroupByPath(), m_Faces, m_glTextures, m_Menu, and m_PickingFramebuffer.
Member Function Documentation
createContextMenu()
void NaviCubeImplementation::createContextMenu (const std::vector< std::string > & cmd)
References Gui::Command::addTo(), Gui::CommandManager::getCommandByName(), and m_Menu.
Referenced by NaviCube::createContextMenu().
drawNaviCube() [1/2]
void NaviCubeImplementation::drawNaviCube ()
References drawNaviCube(), m_CubeWidgetPosX, m_CubeWidgetPosY, and m_CubeWidgetSize.
Referenced by drawNaviCube(), and NaviCube::drawNaviCube().
drawNaviCube() [2/2]
void NaviCubeImplementation::drawNaviCube (bool picking)
References App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), m_BorderColor, m_BorderWidth, m_ButtonColor, m_Buttons, m_Faces, m_HiliteColor, m_HiliteId, m_IndexArray, m_NaviCubeInitialised, m_TextureCoordArray, m_Textures, m_VertexArray, m_VertexArray2, m_View3DInventorViewer, TEX_FRONT_FACE, TEX_VIEW_MENU_FACE, and TEX_VIEW_MENU_ICON.
OnChange()
void NaviCubeImplementation::OnChange (ParameterGrp::SubjectType & rCaller, ParameterGrp::MessageType Reason) virtual
Observer message from the ParameterGrp.
References m_BorderColor, m_BorderWidth, m_ButtonColor, m_CubeWidgetSize, m_FrontFaceColor, m_HiliteColor, and m_TextColor.
Referenced by NaviCubeImplementation().
processSoEvent()
bool NaviCubeImplementation::processSoEvent (const SoEvent * ev)
Referenced by NaviCube::processSoEvent().
Member Data Documentation
m_BorderColor
QColor NaviCubeImplementation::m_BorderColor
Referenced by drawNaviCube(), and OnChange().
m_BorderWidth
double NaviCubeImplementation::m_BorderWidth
Referenced by drawNaviCube(), and OnChange().
m_ButtonColor
QColor NaviCubeImplementation::m_ButtonColor
Referenced by drawNaviCube(), and OnChange().
m_Buttons
vector<int> NaviCubeImplementation::m_Buttons
Referenced by drawNaviCube().
m_commands
vector< string > NaviCubeImplementation::m_commands static
Referenced by NaviCube::setNaviCubeCommands().
m_Corner
NaviCube::Corner NaviCubeImplementation::m_Corner = NaviCube::TopRightCorner
Referenced by NaviCube::setCorner().
m_CubeWidgetPosX
int NaviCubeImplementation::m_CubeWidgetPosX = 0
Referenced by drawNaviCube().
m_CubeWidgetPosY
int NaviCubeImplementation::m_CubeWidgetPosY = 0
Referenced by drawNaviCube().
m_CubeWidgetSize
int NaviCubeImplementation::m_CubeWidgetSize = 0
Referenced by drawNaviCube(), and OnChange().
m_Dragging
bool NaviCubeImplementation::m_Dragging = false
m_Faces
vector<Face*> NaviCubeImplementation::m_Faces
Referenced by drawNaviCube(), and ~NaviCubeImplementation().
m_FrontFaceColor
QColor NaviCubeImplementation::m_FrontFaceColor
Referenced by OnChange().
m_glTextures
vector<QOpenGLTexture*> NaviCubeImplementation::m_glTextures
Referenced by ~NaviCubeImplementation().
m_HiliteColor
QColor NaviCubeImplementation::m_HiliteColor
Referenced by drawNaviCube(), and OnChange().
m_HiliteId
int NaviCubeImplementation::m_HiliteId = 0
Referenced by drawNaviCube().
m_IndexArray
vector<GLubyte> NaviCubeImplementation::m_IndexArray
Referenced by drawNaviCube().
m_labels
vector< string > NaviCubeImplementation::m_labels static
Referenced by NaviCube::setNaviCubeLabels().
m_Menu
QMenu* NaviCubeImplementation::m_Menu
Referenced by createContextMenu(), NaviCubeImplementation(), and ~NaviCubeImplementation().
m_MightDrag
bool NaviCubeImplementation::m_MightDrag = false
m_MouseDown
bool NaviCubeImplementation::m_MouseDown = false
m_NaviCubeInitialised
bool NaviCubeImplementation::m_NaviCubeInitialised = false
Referenced by drawNaviCube().
m_OverSample
int NaviCubeImplementation::m_OverSample = 4
m_PickingFramebuffer
QtGLFramebufferObject* NaviCubeImplementation::m_PickingFramebuffer
Referenced by NaviCubeImplementation(), and ~NaviCubeImplementation().
m_PrevHeight
int NaviCubeImplementation::m_PrevHeight = 0
Referenced by NaviCube::setCorner().
m_PrevWidth
int NaviCubeImplementation::m_PrevWidth = 0
Referenced by NaviCube::setCorner().
m_TextColor
QColor NaviCubeImplementation::m_TextColor
Referenced by OnChange().
m_TextureCoordArray
vector<Vector2f> NaviCubeImplementation::m_TextureCoordArray
Referenced by drawNaviCube().
m_Textures
map<int, GLuint> NaviCubeImplementation::m_Textures
Referenced by drawNaviCube().
m_VertexArray
vector<Vector3f> NaviCubeImplementation::m_VertexArray
Referenced by drawNaviCube().
m_VertexArray2
vector<Vector3f> NaviCubeImplementation::m_VertexArray2
Referenced by drawNaviCube().
m_View3DInventorViewer
Gui::View3DInventorViewer* NaviCubeImplementation::m_View3DInventorViewer
Referenced by drawNaviCube(), and NaviCubeImplementation().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/NaviCube.cpp