FreeCAD: Gui::ProgressBar Class Reference
Gui::ProgressBar Class Reference
#include <ProgressBar.h>
Public Slots
bool canAbort () const
void setMinimumDuration (int ms)
Sets the time that must pass before the progress bar appears to ms.
Public Member Functions
bool eventFilter (QObject *o, QEvent *e)
Handles all incoming events while the progress bar is running.
int minimumDuration () const
Returns the time in milliseconds that must pass before the progress bar appears.
ProgressBar (SequencerBar *s, QWidget *parent=0)
Construction.
~ProgressBar ()
Destruction.
Protected Slots
void aboutToHide ()
void aboutToShow ()
void delayedShow ()
Protected Member Functions
void hideEvent (QHideEvent *)
void showEvent (QShowEvent *)
for internal use only
class SequencerBar
Constructor & Destructor Documentation
ProgressBar()
ProgressBar::ProgressBar (SequencerBar * s, QWidget * parent = 0)
Construction.
References draftgeoutils.intersections::connect(), delayedShow(), Gui::ProgressBarPrivate::delayShowTimer, Gui::ProgressBarPrivate::minimumDuration, and Gui::ProgressBarPrivate::observeEventFilter.
~ProgressBar()
ProgressBar::~ProgressBar ()
Destruction.
References delayedShow(), and Gui::ProgressBarPrivate::delayShowTimer.
Member Function Documentation
aboutToHide
void ProgressBar::aboutToHide () protected slot
Referenced by Gui::SequencerBar::resetData().
aboutToShow
void ProgressBar::aboutToShow () protected slot
References Gui::ProgressBarPrivate::delayShowTimer, and Gui::ProgressBarPrivate::minimumDuration.
Referenced by Gui::SequencerBar::startStep().
canAbort
bool ProgressBar::canAbort () const slot
References Gui::getMainWindow().
Referenced by Gui::SequencerBar::checkAbort(), and Gui::SequencerBar::nextStep().
delayedShow
void ProgressBar::delayedShow () protected slot
References Base::SequencerBase::isRunning(), and Base::SequencerBase::wasCanceled().
Referenced by ProgressBar(), and ~ProgressBar().
eventFilter()
bool ProgressBar::eventFilter (QObject * o, QEvent * e)
Handles all incoming events while the progress bar is running.
All key and mouse events are ignored to block user input.
References Gui::getMainWindow(), Gui::ProgressBarPrivate::isModalDialog(), Base::SequencerBase::isRunning(), Gui::ProgressBarPrivate::observeEventFilter, Gui::SequencerBar::resetData(), and Base::SequencerBase::tryToCancel().
hideEvent()
void ProgressBar::hideEvent (QHideEvent * e) protected
References Gui::ProgressBarPrivate::delayShowTimer.
minimumDuration()
int ProgressBar::minimumDuration () const
Returns the time in milliseconds that must pass before the progress bar appears.
References Gui::ProgressBarPrivate::minimumDuration.
setMinimumDuration
void ProgressBar::setMinimumDuration (int ms) slot
Sets the time that must pass before the progress bar appears to ms.
References Gui::ProgressBarPrivate::delayShowTimer, and Gui::ProgressBarPrivate::minimumDuration.
showEvent()
void ProgressBar::showEvent (QShowEvent * e) protected
References Gui::ProgressBarPrivate::delayShowTimer.
Friends And Related Function Documentation
SequencerBar
friend class SequencerBar friend
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/ProgressBar.h
Sources/FreeCAD/src/Gui/ProgressBar.cpp