FreeCAD: SketcherGui::Ui_TaskSketcherConstraints Class Reference
SketcherGui::Ui_TaskSketcherConstraints Class Reference
#include <ui_TaskSketcherConstraints.h>
Public Member Functions
void retranslateUi (QWidget *SketcherGui__TaskSketcherConstraints)
void setupUi (QWidget *SketcherGui__TaskSketcherConstraints)
Public Attributes
QComboBox * comboBoxFilter
QPushButton * hideAllButton
QHBoxLayout * horizontalLayout
QHBoxLayout * horizontalLayout_3
QLabel * label
ConstraintView * listWidgetConstraints
QPushButton * multipleFilterButton
QPushButton * settingsDialogButton
QPushButton * showAllButton
QVBoxLayout * verticalLayout
QToolButton * visibilityButton
Member Function Documentation
retranslateUi()
void SketcherGui::Ui_TaskSketcherConstraints::retranslateUi (QWidget * SketcherGui__TaskSketcherConstraints)
References comboBoxFilter, hideAllButton, multipleFilterButton, settingsDialogButton, showAllButton, draftguitools.gui_setstyle::translate, and visibilityButton.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void SketcherGui::Ui_TaskSketcherConstraints::setupUi (QWidget * SketcherGui__TaskSketcherConstraints)
References comboBoxFilter, hideAllButton, horizontalLayout, horizontalLayout_3, listWidgetConstraints, multipleFilterButton, retranslateUi(), settingsDialogButton, showAllButton, verticalLayout, and visibilityButton.
Member Data Documentation
comboBoxFilter
QComboBox* SketcherGui::Ui_TaskSketcherConstraints::comboBoxFilter
Referenced by retranslateUi(), and setupUi().
hideAllButton
QPushButton* SketcherGui::Ui_TaskSketcherConstraints::hideAllButton
Referenced by retranslateUi(), and setupUi().
horizontalLayout
QHBoxLayout* SketcherGui::Ui_TaskSketcherConstraints::horizontalLayout
Referenced by setupUi().
horizontalLayout_3
QHBoxLayout* SketcherGui::Ui_TaskSketcherConstraints::horizontalLayout_3
Referenced by setupUi().
label
QLabel* SketcherGui::Ui_TaskSketcherConstraints::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
listWidgetConstraints
ConstraintView* SketcherGui::Ui_TaskSketcherConstraints::listWidgetConstraints
Referenced by setupUi().
multipleFilterButton
QPushButton* SketcherGui::Ui_TaskSketcherConstraints::multipleFilterButton
Referenced by retranslateUi(), and setupUi().
settingsDialogButton
QPushButton* SketcherGui::Ui_TaskSketcherConstraints::settingsDialogButton
Referenced by retranslateUi(), and setupUi().
showAllButton
QPushButton* SketcherGui::Ui_TaskSketcherConstraints::showAllButton
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* SketcherGui::Ui_TaskSketcherConstraints::verticalLayout
Referenced by setupUi().
visibilityButton
QToolButton* SketcherGui::Ui_TaskSketcherConstraints::visibilityButton
Referenced by retranslateUi(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/ui_TaskSketcherConstraints.h