FreeCAD: App::DocumentObjectObserver Class Reference
App::DocumentObjectObserver Class Reference
The DocumentObjectObserver class checks for a list of objects which of them get removed.
#include <DocumentObserver.h>
Public Types
typedef std::set< App::DocumentObject * >::const_iterator const_iterator
Public Member Functions
void addToObservation (App::DocumentObject *)
const_iterator begin () const
DocumentObjectObserver ()
Constructor.
const_iterator end () const
void removeFromObservation (App::DocumentObject *)
virtual ~DocumentObjectObserver ()
Public Member Functions inherited from App::DocumentObserver
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
Additional Inherited Members
Protected Member Functions inherited from App::DocumentObserver
Document * getDocument () const
Detailed Description
The DocumentObjectObserver class checks for a list of objects which of them get removed.
Author
Werner Mayer
Member Typedef Documentation
const_iterator
typedef std::set<App::DocumentObject*>::const_iterator App::DocumentObjectObserver::const_iterator
Constructor & Destructor Documentation
DocumentObjectObserver()
DocumentObjectObserver::DocumentObjectObserver ()
Constructor.
~DocumentObjectObserver()
DocumentObjectObserver::~DocumentObjectObserver () virtual
Member Function Documentation
addToObservation()
void DocumentObjectObserver::addToObservation (App::DocumentObject * obj)
begin()
DocumentObjectObserver::const_iterator DocumentObjectObserver::begin () const
end()
DocumentObjectObserver::const_iterator DocumentObjectObserver::end () const
Referenced by Dice3DS.dom3ds.FileLikeBuffer::advance(), Dice3DS.dom3ds.FileLikeBuffer::read_rest(), Dice3DS.dom3ds.FileLikeBuffer::read_to_nul(), Dice3DS.dom3ds.FileLikeBuffer::room_for_chunks(), and Dice3DS.dom3ds.FileLikeBuffer::seek().
removeFromObservation()
void DocumentObjectObserver::removeFromObservation (App::DocumentObject * obj)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/App/DocumentObserver.h
Sources/FreeCAD/src/App/DocumentObserver.cpp