FreeCAD: PartDesignGui::TaskDlgFeatureParameters Class Reference
PartDesignGui::TaskDlgFeatureParameters Class Reference
A common base for sketch based, dressup and other solid parameters dialogs.
#include <TaskFeatureParameters.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgFeatureParameters (PartDesignGui::ViewProvider *vp)
PartDesignGui::ViewProvider * viewProvider () const
Returns the view provider dialog is runed for.
virtual ~TaskDlgFeatureParameters ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
tells the framework which buttons are wished for the dialog
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Protected Attributes
PartDesignGui::ViewProvider * vp
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
A common base for sketch based, dressup and other solid parameters dialogs.
Constructor & Destructor Documentation
TaskDlgFeatureParameters()
TaskDlgFeatureParameters::TaskDlgFeatureParameters (PartDesignGui::ViewProvider * vp)
References vp.
~TaskDlgFeatureParameters()
TaskDlgFeatureParameters::~TaskDlgFeatureParameters () virtual
Member Function Documentation
accept()
bool TaskDlgFeatureParameters::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Reimplemented in PartDesignGui::TaskDlgChamferParameters, PartDesignGui::TaskDlgDraftParameters, PartDesignGui::TaskDlgDressUpParameters, PartDesignGui::TaskDlgFilletParameters, PartDesignGui::TaskDlgLoftParameters, PartDesignGui::TaskDlgMirroredParameters, PartDesignGui::TaskDlgMultiTransformParameters, PartDesignGui::TaskDlgPipeParameters, PartDesignGui::TaskDlgScaledParameters, PartDesignGui::TaskDlgSketchBasedParameters, PartDesignGui::TaskDlgThicknessParameters, and PartDesignGui::TaskDlgTransformedParameters.
References Gui::cmdAppDocument(), Gui::cmdAppObjectHide(), Gui::cmdGuiDocument(), Gui::Command::commitCommand(), Gui::TaskView::TaskDialog::Content, Base::Persistence::getClassTypeId(), Gui::TaskView::TaskDialog::getDialogContent(), Gui::getMainWindow(), Base::Type::getName(), Gui::ViewProviderDocumentObject::getObject(), App::DocumentObject::getStatusString(), Base::Persistence::getTypeId(), Base::Type::isDerivedFrom(), App::DocumentObject::isValid(), draftguitools.gui_annotationstyleeditor::param, draftguitools.gui_setstyle::translate, and vp.
Referenced by PartDesignGui::TaskDlgDressUpParameters::accept(), PartDesignGui::TaskDlgMultiTransformParameters::accept(), PartDesignGui::TaskDlgSketchBasedParameters::accept(), PartDesignGui::TaskDlgTransformedParameters::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
reject()
bool TaskDlgFeatureParameters::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Reimplemented in PartDesignGui::TaskDlgDressUpParameters, PartDesignGui::TaskDlgSketchBasedParameters, and PartDesignGui::TaskDlgTransformedParameters.
References Gui::Command::abortCommand(), Gui::cmdAppDocument(), Gui::cmdGuiDocument(), App::DocumentObjectWeakPtrT::expired(), PartDesign::Body::findBodyOf(), PartDesign::Feature::getBaseObject(), Gui::TaskView::TaskDialog::getDialogContent(), App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyLink::getValue(), Gui::Application::getViewProvider(), Gui::Application::Instance, draftguitools.gui_annotationstyleeditor::param, Gui::ViewProvider::show(), Part::BodyBase::Tip, and vp.
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), PartDesignGui::TaskDlgDressUpParameters::reject(), PartDesignGui::TaskDlgSketchBasedParameters::reject(), PartDesignGui::TaskDlgTransformedParameters::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
viewProvider()
PartDesignGui::ViewProvider * PartDesignGui::TaskDlgFeatureParameters::viewProvider () const
Returns the view provider dialog is runed for.
References vp.
Referenced by PathScripts.PathDressupDogbone.TaskPanel::cleanup(), PathPythonGui.simple_edit_panel.SimpleEditPanel::cleanup(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::cleanup(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::cleanup(), PartDesignGui::ViewProvider::setEdit(), PathScripts.PathDressupDogbone.TaskPanel::setupUi(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::setupUi(), PathScripts.PathDressupDogbone.TaskPanel::updateBoneList(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::updateTagsView(), and PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::whenTagSelectionChanged().
Member Data Documentation
vp
PartDesignGui::ViewProvider* PartDesignGui::TaskDlgFeatureParameters::vp protected
Referenced by PartDesignGui::TaskDlgChamferParameters::accept(), PartDesignGui::TaskDlgDraftParameters::accept(), PartDesignGui::TaskDlgDressUpParameters::accept(), accept(), PartDesignGui::TaskDlgFilletParameters::accept(), PartDesignGui::TaskDlgLoftParameters::accept(), PartDesignGui::TaskDlgMirroredParameters::accept(), PartDesignGui::TaskDlgMultiTransformParameters::accept(), PartDesignGui::TaskDlgSketchBasedParameters::accept(), PartDesignGui::TaskDlgThicknessParameters::accept(), PartDesignGui::TaskDlgDressUpParameters::getDressUpView(), PartDesignGui::TaskDlgHelixParameters::getHelixView(), PartDesignGui::TaskDlgHoleParameters::getHoleView(), PartDesignGui::TaskDlgLoftParameters::getLoftView(), PartDesignGui::TaskDlgPadParameters::getPadView(), PartDesignGui::TaskDlgPocketParameters::getPocketView(), PartDesignGui::TaskDlgRevolutionParameters::getRevolutionView(), PartDesignGui::TaskDlgTransformedParameters::getTransformedView(), PartDesignGui::TaskDlgPipeParameters::onButtonToggled(), reject(), PartDesignGui::TaskDlgSketchBasedParameters::reject(), TaskDlgFeatureParameters(), PartDesignGui::TaskDlgHoleParameters::TaskDlgHoleParameters(), PartDesignGui::TaskDlgPadParameters::TaskDlgPadParameters(), PartDesignGui::TaskDlgPocketParameters::TaskDlgPocketParameters(), PartDesignGui::TaskDlgTransformedParameters::TaskDlgTransformedParameters(), and viewProvider().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/PartDesign/Gui/TaskFeatureParameters.h
FreeCAD/src/Mod/PartDesign/Gui/TaskFeatureParameters.cpp