FreeCAD: Gui::SelectionObserverPython Class Reference
Gui::SelectionObserverPython Class Reference
The SelectionObserverPython class implements a mechanism to register a Python class instance implementing the required interface in order to be notified on selection changes.
#include <Selection.h>
Public Member Functions
SelectionObserverPython (const Py::Object &obj, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserverPython ()
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Static Public Member Functions
static void addObserver (const Py::Object &obj, ResolveMode resolve=ResolveMode::OldStyleElement)
static void removeObserver (const Py::Object &obj)
Detailed Description
The SelectionObserverPython class implements a mechanism to register a Python class instance implementing the required interface in order to be notified on selection changes.
Author
Werner Mayer
Constructor & Destructor Documentation
SelectionObserverPython()
SelectionObserverPython::SelectionObserverPython (const Py::Object & obj, ResolveMode resolve = ResolveMode::OldStyleElement)
Constructor.
Referenced by addObserver().
~SelectionObserverPython()
SelectionObserverPython::~SelectionObserverPython () virtual
Member Function Documentation
addObserver()
void SelectionObserverPython::addObserver (const Py::Object & obj, ResolveMode resolve = ResolveMode::OldStyleElement) static
References SelectionObserverPython().
Referenced by Gui::SelectionSingleton::sAddSelObserver().
removeObserver()
void SelectionObserverPython::removeObserver (const Py::Object & obj) static
Referenced by Gui::SelectionSingleton::sRemSelObserver().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/Selection.h
FreeCAD/src/Gui/Selection.cpp