FreeCAD: MeshCore::AbstractPolygonTriangulator Class Reference
MeshCore::AbstractPolygonTriangulator Class Reference abstract
#include <Triangulation.h>
Public Member Functions
AbstractPolygonTriangulator ()
std::vector< Base::Vector3f > AddedPoints () const
The triangulation algorithm may create new points when calling Triangulate().
virtual void Discard ()
const std::vector< MeshFacet > & GetFacets () const
Returns the topologic facets of the polygon.
std::vector< unsigned long > GetInfo () const
Get information about the polygons that were processed.
float GetLength () const
Returns the length of the polygon.
std::vector< Base::Vector3f > GetPolygon () const
Get the polygon points to be triangulated.
Base::Matrix4D GetTransformToFitPlane () const
Computes the best-fit plane and returns a transformation matrix built out of the axes of the plane.
virtual MeshGeomFacet GetTriangle (const MeshPointArray &, const MeshFacet &) const
Returns the triangle to a given topologic facet.
const std::vector< MeshGeomFacet > & GetTriangles () const
Returns the geometric triangles of the polygon.
TriangulationVerifier * GetVerifier () const
virtual bool NeedsReindexing () const
Usually the created faces use the indices of the polygon points from [0, n].
virtual void PostProcessing (const std::vector< Base::Vector3f > &)
If points were added then we get the 3D points by projecting the added 2D points onto a surface which fits into the given points.
std::vector< Base::Vector3f > ProjectToFitPlane ()
If the points of the polygon set by SetPolygon() doesn't lie in a plane this method can be used to project the points in a common plane.
virtual void Reset ()
Resets some internals.
void SetIndices (const std::vector< unsigned long > &d)
void SetPolygon (const std::vector< Base::Vector3f > &raclPoints)
Sets the polygon to be triangulated.
void SetVerifier (TriangulationVerifier *v)
Set a verifier object that checks if the generated triangulation can be accepted and added to the mesh kernel.
bool TriangulatePolygon ()
Computes the triangulation of a polygon.
virtual ~AbstractPolygonTriangulator ()
Protected Member Functions
void Done ()
virtual bool Triangulate ()=0
Computes the triangulation of a polygon.
Constructor & Destructor Documentation
AbstractPolygonTriangulator()
AbstractPolygonTriangulator::AbstractPolygonTriangulator ()
~AbstractPolygonTriangulator()
AbstractPolygonTriangulator::~AbstractPolygonTriangulator () virtual
Member Function Documentation
AddedPoints()
std::vector< Base::Vector3f > AbstractPolygonTriangulator::AddedPoints () const
The triangulation algorithm may create new points when calling Triangulate().
This method returns these added points.
Note
: Make sure to have called PostProcessing() before using this method if you want the surface points the new points are lying on.
Referenced by MeshCore::MeshAlgorithm::FillupHole().
Discard()
void AbstractPolygonTriangulator::Discard () virtual
Referenced by MeshCore::MeshAlgorithm::FillupHole().
Done()
void AbstractPolygonTriangulator::Done () protected
Referenced by TriangulatePolygon().
GetFacets()
const std::vector<MeshFacet>& MeshCore::AbstractPolygonTriangulator::GetFacets (void) const
Returns the topologic facets of the polygon.
Referenced by MeshGui::ViewProviderMesh::createToolMesh(), MeshCore::MeshAlgorithm::FillupHole(), MeshCore::FlatTriangulator::Triangulate(), and MeshCore::ConstraintDelaunayTriangulator::Triangulate().
GetInfo()
std::vector< unsigned long > AbstractPolygonTriangulator::GetInfo () const
Get information about the polygons that were processed.
It returns an array of the number of edges for each closed polygon.
GetLength()
float AbstractPolygonTriangulator::GetLength () const
Returns the length of the polygon.
References Base::Distance().
GetPolygon()
std::vector< Base::Vector3f > AbstractPolygonTriangulator::GetPolygon () const
Get the polygon points to be triangulated.
The points may be projected onto its average plane.
Referenced by MeshCore::MeshAlgorithm::FillupHole(), MeshCore::FlatTriangulator::Triangulate(), and MeshCore::ConstraintDelaunayTriangulator::Triangulate().
GetTransformToFitPlane()
Base::Matrix4D AbstractPolygonTriangulator::GetTransformToFitPlane () const
Computes the best-fit plane and returns a transformation matrix built out of the axes of the plane.
References MeshCore::Approximation::AddPoint(), MeshCore::PlaneFit::Fit(), MeshCore::PlaneFit::GetBase(), MeshCore::PlaneFit::GetDirU(), MeshCore::PlaneFit::GetDirV(), MeshCore::PlaneFit::GetNormal(), Base::Matrix4D::setToUnity(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by Mesh::MeshPy::cut(), ProjectToFitPlane(), and Mesh::MeshPy::trim().
GetTriangle()
MeshGeomFacet AbstractPolygonTriangulator::GetTriangle (const MeshPointArray & points, const MeshFacet & facet) const virtual
Returns the triangle to a given topologic facet.
Referenced by MeshCore::MeshAlgorithm::FillupHole().
GetTriangles()
const std::vector<MeshGeomFacet>& MeshCore::AbstractPolygonTriangulator::GetTriangles () const
Returns the geometric triangles of the polygon.
Referenced by MeshCore::FlatTriangulator::Triangulate(), and MeshCore::ConstraintDelaunayTriangulator::Triangulate().
GetVerifier()
TriangulationVerifier * AbstractPolygonTriangulator::GetVerifier () const
Referenced by MeshCore::MeshAlgorithm::FillupHole().
NeedsReindexing()
virtual bool MeshCore::AbstractPolygonTriangulator::NeedsReindexing () const virtual
Usually the created faces use the indices of the polygon points from [0, n].
If the faces should be appended to an existing mesh they may need to be reindexed from the calling instance. However, there may other algorithms that directly use the indices of the mesh and thus do not need to be touched afterwards. In this case the method should be reimplemented to return false.
Referenced by MeshCore::MeshAlgorithm::FillupHole(), and MeshCore::MeshTopoAlgorithm::FillupHoles().
PostProcessing()
void AbstractPolygonTriangulator::PostProcessing (const std::vector< Base::Vector3f > & points) virtual
If points were added then we get the 3D points by projecting the added 2D points onto a surface which fits into the given points.
Reimplemented in MeshCore::FlatTriangulator.
References MeshCore::Approximation::AddPoint(), MeshCore::Approximation::CountPoints(), MeshCore::PolynomialFit::Fit(), Base::Vector3< _Precision >::TransformToCoordinateSystem(), and MeshCore::PolynomialFit::Value().
Referenced by MeshCore::MeshAlgorithm::FillupHole().
ProjectToFitPlane()
std::vector< Base::Vector3f > AbstractPolygonTriangulator::ProjectToFitPlane ()
If the points of the polygon set by SetPolygon() doesn't lie in a plane this method can be used to project the points in a common plane.
References GetTransformToFitPlane().
Referenced by Mesh::MeshPy::cut(), MeshCore::EarClippingTriangulator::Triangulate(), MeshCore::FlatTriangulator::Triangulate(), MeshCore::ConstraintDelaunayTriangulator::Triangulate(), and Mesh::MeshPy::trim().
Reset()
void AbstractPolygonTriangulator::Reset () virtual
Resets some internals.
The default implementation does nothing.
SetIndices()
void MeshCore::AbstractPolygonTriangulator::SetIndices (const std::vector< unsigned long > & d)
Referenced by MeshCore::MeshAlgorithm::FillupHole().
SetPolygon()
void AbstractPolygonTriangulator::SetPolygon (const std::vector< Base::Vector3f > & raclPoints)
Sets the polygon to be triangulated.
Referenced by MeshGui::ViewProviderMesh::createToolMesh(), Mesh::MeshPy::cut(), MeshCore::MeshAlgorithm::FillupHole(), MeshCore::FlatTriangulator::Triangulate(), MeshCore::ConstraintDelaunayTriangulator::Triangulate(), and Mesh::MeshPy::trim().
SetVerifier()
void AbstractPolygonTriangulator::SetVerifier (TriangulationVerifier * v)
Set a verifier object that checks if the generated triangulation can be accepted and added to the mesh kernel.
The triangulator takes ownership of the passed verifier.
Referenced by MeshGui::ViewProviderMesh::fillHole().
Triangulate()
virtual bool MeshCore::AbstractPolygonTriangulator::Triangulate () protected pure virtual
Computes the triangulation of a polygon.
The resulting facets can be accessed by GetTriangles() or GetFacets().
Implemented in MeshCore::ConstraintDelaunayTriangulator, MeshCore::FlatTriangulator, MeshCore::DelaunayTriangulator, MeshCore::QuasiDelaunayTriangulator, and MeshCore::EarClippingTriangulator.
Referenced by TriangulatePolygon().
TriangulatePolygon()
bool AbstractPolygonTriangulator::TriangulatePolygon ()
Computes the triangulation of a polygon.
The resulting facets can be accessed by GetTriangles() or GetFacets().
References Base::Console(), Done(), Base::ConsoleSingleton::Log(), and Triangulate().
Referenced by MeshGui::ViewProviderMesh::createToolMesh(), MeshCore::MeshAlgorithm::FillupHole(), MeshCore::FlatTriangulator::Triangulate(), and MeshCore::ConstraintDelaunayTriangulator::Triangulate().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Triangulation.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Triangulation.cpp