FreeCAD: GCS::ArcOfEllipse Class Reference
GCS::ArcOfEllipse Class Reference
#include <Geo.h>
Public Member Functions
ArcOfEllipse ()
virtual ArcOfEllipse * Copy ()
virtual int PushOwnParams (VEC_pD &pvec)
virtual void ReconstructOnNewPvec (VEC_pD &pvec, int &cnt)
virtual ~ArcOfEllipse ()
Public Member Functions inherited from GCS::Ellipse
DeriVector2 CalculateNormal (Point &p, double *derivparam=0)
Ellipse ()
virtual double getRadMaj ()
virtual double getRadMaj (const DeriVector2 &center, const DeriVector2 &f1, double b, double db, double &ret_dRadMaj)
virtual double getRadMaj (double *derivparam, double &ret_dRadMaj)
DeriVector2 Value (double u, double du, double *derivparam=0)
Value: returns point (vector) given the value of parameter.
virtual ~Ellipse ()
Public Member Functions inherited from GCS::MajorRadiusConic
virtual ~MajorRadiusConic ()
Public Member Functions inherited from GCS::Curve
virtual ~Curve ()
Public Attributes
Point end
double * endAngle
Point start
double * startAngle
Public Attributes inherited from GCS::Ellipse
Point center
Point focus1
double * radmin
Constructor & Destructor Documentation
ArcOfEllipse()
GCS::ArcOfEllipse::ArcOfEllipse ()
References endAngle, GCS::Ellipse::radmin, and startAngle.
Referenced by Copy().
~ArcOfEllipse()
virtual GCS::ArcOfEllipse::~ArcOfEllipse () virtual
Member Function Documentation
Copy()
ArcOfEllipse * GCS::ArcOfEllipse::Copy (void) virtual
Reimplemented from GCS::Ellipse.
References ArcOfEllipse().
PushOwnParams()
int GCS::ArcOfEllipse::PushOwnParams (VEC_pD & pvec) virtual
Reimplemented from GCS::Ellipse.
References endAngle, GCS::Ellipse::PushOwnParams(), and startAngle.
ReconstructOnNewPvec()
void GCS::ArcOfEllipse::ReconstructOnNewPvec (VEC_pD & pvec, int & cnt) virtual
Reimplemented from GCS::Ellipse.
References endAngle, GCS::Ellipse::ReconstructOnNewPvec(), and startAngle.
Member Data Documentation
end
Point GCS::ArcOfEllipse::end
endAngle
double* GCS::ArcOfEllipse::endAngle
Referenced by ArcOfEllipse(), PushOwnParams(), and ReconstructOnNewPvec().
start
Point GCS::ArcOfEllipse::start
Referenced by Sketcher::Sketch::addArcOfEllipse().
startAngle
double* GCS::ArcOfEllipse::startAngle
Referenced by ArcOfEllipse(), PushOwnParams(), and ReconstructOnNewPvec().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Geo.h
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Geo.cpp