FreeCAD: Gui::Dialog::DlgSettingsEditorImp Class Reference
Gui::Dialog::DlgSettingsEditorImp Class Reference
#include <DlgEditorImp.h>
Public Member Functions
DlgSettingsEditorImp (QWidget *parent=0)
Constructs a DlgSettingsEditorImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
void loadSettings ()
void saveSettings ()
~DlgSettingsEditorImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=0)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Slots
void on_colorButton_changed ()
Updates the color map if a color was changed.
void on_displayItems_currentItemChanged (QTreeWidgetItem *i)
Searches for the color value corresponding to name in current editor settings ColorMap and assigns it to the color button.
void on_fontFamily_activated (const QString &)
void on_fontSize_valueChanged (const QString &)
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
Constructor & Destructor Documentation
DlgSettingsEditorImp()
DlgSettingsEditorImp::DlgSettingsEditorImp (QWidget * parent = 0)
Constructs a DlgSettingsEditorImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
References Gui::Dialog::DlgSettingsEditorP::colormap.
~DlgSettingsEditorImp()
DlgSettingsEditorImp::~DlgSettingsEditorImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void DlgSettingsEditorImp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
References Gui::Dialog::DlgSettingsEditorP::colormap.
loadSettings()
void DlgSettingsEditorImp::loadSettings () virtual
Implements Gui::Dialog::PreferencePage.
References Gui::Dialog::DlgSettingsEditorP::colormap, ParameterGrp::GetASCII(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), ParameterGrp::GetUnsigned(), on_fontFamily_activated(), and Gui::SyntaxHighlighter::setColor().
on_colorButton_changed
void DlgSettingsEditorImp::on_colorButton_changed () protected slot
Updates the color map if a color was changed.
References Gui::Dialog::DlgSettingsEditorP::colormap, and Gui::SyntaxHighlighter::setColor().
on_displayItems_currentItemChanged
void DlgSettingsEditorImp::on_displayItems_currentItemChanged (QTreeWidgetItem * item) protected slot
Searches for the color value corresponding to name in current editor settings ColorMap and assigns it to the color button.
See also
Gui::ColorButton
References Gui::Dialog::DlgSettingsEditorP::colormap.
on_fontFamily_activated
void DlgSettingsEditorImp::on_fontFamily_activated (const QString & fontFamily) protected slot
Referenced by loadSettings(), and on_fontSize_valueChanged().
on_fontSize_valueChanged
void DlgSettingsEditorImp::on_fontSize_valueChanged (const QString &) protected slot
References on_fontFamily_activated().
saveSettings()
void DlgSettingsEditorImp::saveSettings () virtual
Implements Gui::Dialog::PreferencePage.
References Gui::Dialog::DlgSettingsEditorP::colormap, Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), ParameterGrp::SetASCII(), ParameterGrp::SetInt(), and ParameterGrp::SetUnsigned().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgEditorImp.h
Sources/FreeCAD/src/Gui/DlgEditorImp.cpp