FreeCAD: AutoSaver Class Reference
AutoSaver Class Reference
#include <DownloadItem.h>
Public Slots
void changeOccurred ()
Public Member Functions
AutoSaver (QObject *parent)
void saveIfNecessary ()
~AutoSaver ()
Protected Member Functions
void timerEvent (QTimerEvent *event)
Constructor & Destructor Documentation
AutoSaver()
AutoSaver::AutoSaver (QObject * parent)
~AutoSaver()
AutoSaver::~AutoSaver ()
Member Function Documentation
changeOccurred
void AutoSaver::changeOccurred () slot
References saveIfNecessary().
saveIfNecessary()
void AutoSaver::saveIfNecessary ()
Referenced by changeOccurred(), and timerEvent().
timerEvent()
void AutoSaver::timerEvent (QTimerEvent * event) protected
References saveIfNecessary().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DownloadItem.h
Sources/FreeCAD/src/Gui/DownloadItem.cpp