FreeCAD: Gui::AxisOriginPy Class Reference
Gui::AxisOriginPy Class Reference
The python export class for AxisOrigin.
#include <AxisOriginPy.h>
Public Types
typedef AxisOrigin * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
AxisOriginPy (AxisOrigin *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of AxisOriginPy.
static PyMethodDef Methods []
Methods structure of AxisOriginPy.
static PyTypeObject Type
Type structure of AxisOriginPy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~AxisOriginPy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * getElementPicked (PyObject *args)
implementer for the getElementPicked() method
PyObject * getDetailPath (PyObject *args)
implementer for the getDetailPath() method
static PyObject * staticCallback_getElementPicked (PyObject *self, PyObject *args)
callback for the getElementPicked() method
static PyObject * staticCallback_getDetailPath (PyObject *self, PyObject *args)
callback for the getDetailPath() method
callbacks and implementers for the python object attributes
Py::Float getAxisLength (void) const
getter for the AxisLength attribute
void setAxisLength (Py::Float arg)
setter for the AxisLength attribute
Py::Float getLineWidth (void) const
getter for the LineWidth attribute
void setLineWidth (Py::Float arg)
setter for the LineWidth attribute
Py::Float getPointSize (void) const
getter for the PointSize attribute
void setPointSize (Py::Float arg)
setter for the PointSize attribute
Py::Float getScale (void) const
getter for the Scale attribute
void setScale (Py::Float arg)
setter for the Scale attribute
Py::Tuple getPlane (void) const
getter for the Plane attribute
void setPlane (Py::Tuple arg)
setter for the Plane attribute
Py::Dict getLabels (void) const
getter for the Labels attribute
void setLabels (Py::Dict arg)
setter for the Labels attribute
Py::Object getNode (void) const
getter for the Node attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
AxisOrigin * getAxisOriginPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getAxisLength (PyObject *self, void *closure)
getter callback for the AxisLength attribute
static int staticCallback_setAxisLength (PyObject *self, PyObject *value, void *closure)
setter callback for the AxisLength attribute
static PyObject * staticCallback_getLineWidth (PyObject *self, void *closure)
getter callback for the LineWidth attribute
static int staticCallback_setLineWidth (PyObject *self, PyObject *value, void *closure)
setter callback for the LineWidth attribute
static PyObject * staticCallback_getPointSize (PyObject *self, void *closure)
getter callback for the PointSize attribute
static int staticCallback_setPointSize (PyObject *self, PyObject *value, void *closure)
setter callback for the PointSize attribute
static PyObject * staticCallback_getScale (PyObject *self, void *closure)
getter callback for the Scale attribute
static int staticCallback_setScale (PyObject *self, PyObject *value, void *closure)
setter callback for the Scale attribute
static PyObject * staticCallback_getPlane (PyObject *self, void *closure)
getter callback for the Plane attribute
static int staticCallback_setPlane (PyObject *self, PyObject *value, void *closure)
setter callback for the Plane attribute
static PyObject * staticCallback_getLabels (PyObject *self, void *closure)
getter callback for the Labels attribute
static int staticCallback_setLabels (PyObject *self, PyObject *value, void *closure)
setter callback for the Labels attribute
static PyObject * staticCallback_getNode (PyObject *self, void *closure)
getter callback for the Node attribute
static int staticCallback_setNode (PyObject *self, PyObject *value, void *closure)
setter callback for the Node attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for AxisOrigin.
Member Typedef Documentation
PointerType
typedef AxisOrigin* Gui::AxisOriginPy::PointerType
Constructor & Destructor Documentation
~AxisOriginPy()
AxisOriginPy::~AxisOriginPy () protected
AxisOriginPy()
AxisOriginPy::AxisOriginPy (AxisOrigin * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getAxisLength()
Py::Float AxisOriginPy::getAxisLength (void) const
getter for the AxisLength attribute
References getAxisOriginPtr().
Referenced by staticCallback_getAxisLength().
getAxisOriginPtr()
AxisOrigin * AxisOriginPy::getAxisOriginPtr (void) const
getter for the object handled by this class
Referenced by getAxisLength(), getDetailPath(), getElementPicked(), getLabels(), getLineWidth(), getNode(), getPlane(), getPointSize(), getScale(), setAxisLength(), setLabels(), setLineWidth(), setPlane(), setPointSize(), and setScale().
getCustomAttributes()
PyObject * AxisOriginPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getDetailPath()
PyObject * AxisOriginPy::getDetailPath (PyObject * args)
implementer for the getDetailPath() method
References Base::InterpreterSingleton::convertSWIGPointerObj(), Base::InterpreterSingleton::createSWIGPointerObj(), getAxisOriginPtr(), and Base::Interpreter().
Referenced by staticCallback_getDetailPath().
getElementPicked()
PyObject * AxisOriginPy::getElementPicked (PyObject * args)
implementer for the getElementPicked() method
References Base::InterpreterSingleton::convertSWIGPointerObj(), getAxisOriginPtr(), and Base::Interpreter().
Referenced by staticCallback_getElementPicked().
getLabels()
Py::Dict AxisOriginPy::getLabels (void) const
getter for the Labels attribute
References getAxisOriginPtr().
Referenced by staticCallback_getLabels().
getLineWidth()
Py::Float AxisOriginPy::getLineWidth (void) const
getter for the LineWidth attribute
References getAxisOriginPtr().
Referenced by staticCallback_getLineWidth().
getNode()
Py::Object AxisOriginPy::getNode (void) const
getter for the Node attribute
References Base::InterpreterSingleton::createSWIGPointerObj(), getAxisOriginPtr(), Gui::AxisOrigin::getNode(), and Base::Interpreter().
Referenced by staticCallback_getNode(), and draftguitools.gui_trackers.ghostTracker::update().
getPlane()
Py::Tuple AxisOriginPy::getPlane (void) const
getter for the Plane attribute
References getAxisOriginPtr(), and Gui::AxisOrigin::getPlane().
Referenced by staticCallback_getPlane().
getPointSize()
Py::Float AxisOriginPy::getPointSize (void) const
getter for the PointSize attribute
References getAxisOriginPtr().
Referenced by staticCallback_getPointSize().
getScale()
Py::Float AxisOriginPy::getScale (void) const
getter for the Scale attribute
References getAxisOriginPtr().
Referenced by staticCallback_getScale().
GetType()
virtual PyTypeObject* Gui::AxisOriginPy::GetType (void) virtual
Reimplemented from Base::BaseClassPy.
PyInit()
int AxisOriginPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::BaseClassPy.
PyMake()
PyObject * AxisOriginPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References AxisOriginPy().
representation()
std::string AxisOriginPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setAxisLength()
void AxisOriginPy::setAxisLength (Py::Float arg)
setter for the AxisLength attribute
References getAxisOriginPtr(), and Gui::AxisOrigin::setAxisLength().
Referenced by staticCallback_setAxisLength().
setCustomAttributes()
int AxisOriginPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setLabels()
void AxisOriginPy::setLabels (Py::Dict arg)
setter for the Labels attribute
References getAxisOriginPtr(), and Gui::AxisOrigin::setLabels().
Referenced by staticCallback_setLabels().
setLineWidth()
void AxisOriginPy::setLineWidth (Py::Float arg)
setter for the LineWidth attribute
References getAxisOriginPtr(), and Gui::AxisOrigin::setLineWidth().
Referenced by staticCallback_setLineWidth().
setPlane()
void AxisOriginPy::setPlane (Py::Tuple arg)
setter for the Plane attribute
References getAxisOriginPtr(), and Gui::AxisOrigin::setPlane().
Referenced by staticCallback_setPlane().
setPointSize()
void AxisOriginPy::setPointSize (Py::Float arg)
setter for the PointSize attribute
References getAxisOriginPtr(), and Gui::AxisOrigin::setPointSize().
Referenced by staticCallback_setPointSize().
setScale()
void AxisOriginPy::setScale (Py::Float arg)
setter for the Scale attribute
References getAxisOriginPtr(), and Gui::AxisOrigin::setScale().
Referenced by staticCallback_setScale().
staticCallback_getAxisLength()
PyObject * AxisOriginPy::staticCallback_getAxisLength (PyObject * self, void * closure) static
getter callback for the AxisLength attribute
References Base::BaseExceptionFreeCADError, getAxisLength(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getDetailPath()
PyObject * AxisOriginPy::staticCallback_getDetailPath (PyObject * self, PyObject * args) static
callback for the getDetailPath() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getDetailPath(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getElementPicked()
PyObject * AxisOriginPy::staticCallback_getElementPicked (PyObject * self, PyObject * args) static
callback for the getElementPicked() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getElementPicked(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getLabels()
PyObject * AxisOriginPy::staticCallback_getLabels (PyObject * self, void * closure) static
getter callback for the Labels attribute
References Base::BaseExceptionFreeCADError, getLabels(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getLineWidth()
PyObject * AxisOriginPy::staticCallback_getLineWidth (PyObject * self, void * closure) static
getter callback for the LineWidth attribute
References Base::BaseExceptionFreeCADError, getLineWidth(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNode()
PyObject * AxisOriginPy::staticCallback_getNode (PyObject * self, void * closure) static
getter callback for the Node attribute
References Base::BaseExceptionFreeCADError, getNode(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPlane()
PyObject * AxisOriginPy::staticCallback_getPlane (PyObject * self, void * closure) static
getter callback for the Plane attribute
References Base::BaseExceptionFreeCADError, getPlane(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPointSize()
PyObject * AxisOriginPy::staticCallback_getPointSize (PyObject * self, void * closure) static
getter callback for the PointSize attribute
References Base::BaseExceptionFreeCADError, getPointSize(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getScale()
PyObject * AxisOriginPy::staticCallback_getScale (PyObject * self, void * closure) static
getter callback for the Scale attribute
References Base::BaseExceptionFreeCADError, getScale(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setAxisLength()
int AxisOriginPy::staticCallback_setAxisLength (PyObject * self, PyObject * value, void * closure) static
setter callback for the AxisLength attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setAxisLength().
staticCallback_setLabels()
int AxisOriginPy::staticCallback_setLabels (PyObject * self, PyObject * value, void * closure) static
setter callback for the Labels attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setLabels().
staticCallback_setLineWidth()
int AxisOriginPy::staticCallback_setLineWidth (PyObject * self, PyObject * value, void * closure) static
setter callback for the LineWidth attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setLineWidth().
staticCallback_setNode()
int AxisOriginPy::staticCallback_setNode (PyObject * self, PyObject * value, void * closure) static
setter callback for the Node attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPlane()
int AxisOriginPy::staticCallback_setPlane (PyObject * self, PyObject * value, void * closure) static
setter callback for the Plane attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setPlane().
staticCallback_setPointSize()
int AxisOriginPy::staticCallback_setPointSize (PyObject * self, PyObject * value, void * closure) static
setter callback for the PointSize attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setPointSize().
staticCallback_setScale()
int AxisOriginPy::staticCallback_setScale (PyObject * self, PyObject * value, void * closure) static
setter callback for the Scale attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setScale().
Member Data Documentation
GetterSetter
PyGetSetDef AxisOriginPy::GetterSetter static
Attribute structure of AxisOriginPy.
Methods
PyMethodDef AxisOriginPy::Methods static
Initial value:
= {
    {"getElementPicked",
        reinterpret_cast<PyCFunction>( staticCallback_getElementPicked ),
        METH_VARARGS,
        "getElementPicked(pickPoint): return the picked subelement"
    },
    {"getDetailPath",
        reinterpret_cast<PyCFunction>( staticCallback_getDetailPath ),
        METH_VARARGS,
        "\ngetDetailPath(subname,path): return Coin detail and path of an subelement\n\nsubelement: dot separated string reference to the sub element\npPath: output coin path leading to the returned element detail\n                "
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of AxisOriginPy.
Type
PyTypeObject AxisOriginPy::Type static
Type structure of AxisOriginPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), Gui::Application::Application(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Gui/AxisOriginPy.h
Sources/FreeCAD/src/Gui/AxisOriginPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Gui/AxisOriginPy.cpp