FreeCAD: TechDraw::LineSet Class Reference
TechDraw::LineSet Class Reference
a LineSet is all the generated edges for 1 PATLineSpec for 1 Face
#include <HatchLine.h>
Public Member Functions
Base::Vector3d calcApparentStart (TechDraw::BaseGeomPtr g)
calculates the apparent start point (ie start of overlay line) for dashed lines
Base::Vector3d findAtomStart (void)
double getAngle (void)
Bnd_Box getBBox (void)
DashSpec getDashSpec (void)
TopoDS_Edge getEdge (int i)
std::vector< TopoDS_Edge > getEdges (void)
std::vector< TechDraw::BaseGeomPtr > getGeoms (void)
double getInterval (void)
double getIntervalX (void)
double getIntervalY (void)
Base::Vector3d getLineOrigin (void)
double getMaxX (void)
double getMaxY (void)
double getMinX (void)
double getMinY (void)
double getOffset (void)
Base::Vector3d getOrigin (void)
PATLineSpec getPATLineSpec (void)
double getPatternLength (void)
Base::Vector3d getPatternStartPoint (TechDraw::BaseGeomPtr g, double &offset, double scale=1.0)
double getSlope (void)
Base::Vector3d getUnitDir (void)
Base::Vector3d getUnitOrtho (void)
bool isDashed (void)
LineSet ()
void setBBox (const Bnd_Box &bb)
void setEdges (std::vector< TopoDS_Edge > e)
void setGeoms (std::vector< TechDraw::BaseGeomPtr > g)
void setPATLineSpec (const PATLineSpec &s)
~LineSet ()
Detailed Description
a LineSet is all the generated edges for 1 PATLineSpec for 1 Face
Constructor & Destructor Documentation
LineSet()
TechDraw::LineSet::LineSet ()
~LineSet()
TechDraw::LineSet::~LineSet ()
Member Function Documentation
calcApparentStart()
Base::Vector3d LineSet::calcApparentStart (TechDraw::BaseGeomPtr g)
calculates the apparent start point (ie start of overlay line) for dashed lines
References TechDraw::PATLineSpec::getAngle(), getMinX(), getMinY(), getPATLineSpec(), and TechDraw::PATLineSpec::getSlope().
Referenced by getPatternStartPoint().
findAtomStart()
Base::Vector3d LineSet::findAtomStart (void)
References getAngle(), getMinX(), getMinY(), getOrigin(), getSlope(), Base::Vector3< _Precision >::x, and Base::Vector3< _Precision >::y.
Referenced by getPatternStartPoint().
getAngle()
double TechDraw::LineSet::getAngle (void)
Referenced by findAtomStart(), PathScripts.PathDressupDogbone.Chord::getAngleXY(), getPatternStartPoint(), draftguitools.gui_trackers.arcTracker::setEndPoint(), and draftguitools.gui_trackers.arcTracker::setStartPoint().
getBBox()
Bnd_Box TechDraw::LineSet::getBBox (void)
getDashSpec()
DashSpec TechDraw::LineSet::getDashSpec (void)
Referenced by TechDrawGui::QGIFace::geomToLine(), TechDrawGui::QGIFace::geomToStubbyLine(), and TechDrawGui::QGIFace::lineSetToFillItems().
getEdge()
TopoDS_Edge TechDraw::LineSet::getEdge (int i)
getEdges()
std::vector< TopoDS_Edge > TechDraw::LineSet::getEdges (void)
getGeoms()
std::vector< TechDraw::BaseGeomPtr > TechDraw::LineSet::getGeoms (void)
Referenced by TechDrawGui::QGIFace::lineSetToFillItems().
getInterval()
double TechDraw::LineSet::getInterval (void)
Referenced by getPatternStartPoint().
getIntervalX()
double TechDraw::LineSet::getIntervalX (void)
Referenced by getPatternStartPoint().
getIntervalY()
double TechDraw::LineSet::getIntervalY (void)
Referenced by getPatternStartPoint().
getLineOrigin()
Base::Vector3d TechDraw::LineSet::getLineOrigin (void)
getMaxX()
double LineSet::getMaxX (void)
getMaxY()
double LineSet::getMaxY (void)
getMinX()
double LineSet::getMinX (void)
Referenced by calcApparentStart(), and findAtomStart().
getMinY()
double LineSet::getMinY (void)
Referenced by calcApparentStart(), and findAtomStart().
getOffset()
double TechDraw::LineSet::getOffset (void)
Referenced by draftguitools.gui_selectplane.Draft_SelectPlane::display(), getPatternStartPoint(), draftguitools.gui_selectplane.Draft_SelectPlane::handle(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickAlign(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickFront(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickSide(), and draftguitools.gui_selectplane.Draft_SelectPlane::onClickTop().
getOrigin()
Base::Vector3d TechDraw::LineSet::getOrigin (void)
Referenced by findAtomStart(), and getPatternStartPoint().
getPATLineSpec()
PATLineSpec TechDraw::LineSet::getPATLineSpec (void)
Referenced by calcApparentStart().
getPatternLength()
double TechDraw::LineSet::getPatternLength (void)
Referenced by getPatternStartPoint().
getPatternStartPoint()
Base::Vector3d LineSet::getPatternStartPoint (TechDraw::BaseGeomPtr g, double & offset, double scale = 1.0)
References calcApparentStart(), Base::Console(), findAtomStart(), getAngle(), getInterval(), getIntervalX(), getIntervalY(), getOffset(), getOrigin(), getPatternLength(), getUnitDir(), getUnitOrtho(), Base::ConsoleSingleton::Log(), Base::Vector3< _Precision >::x, and Base::Vector3< _Precision >::y.
Referenced by TechDrawGui::QGIFace::lineSetToFillItems().
getSlope()
double TechDraw::LineSet::getSlope (void)
Referenced by findAtomStart().
getUnitDir()
Base::Vector3d LineSet::getUnitDir (void)
Referenced by TechDrawGui::QGIFace::geomToStubbyLine(), getPatternStartPoint(), and getUnitOrtho().
getUnitOrtho()
Base::Vector3d LineSet::getUnitOrtho (void)
References getUnitDir().
Referenced by getPatternStartPoint().
isDashed()
bool LineSet::isDashed (void)
References TechDraw::PATLineSpec::isDashed().
Referenced by TechDrawGui::QGIFace::lineSetToFillItems().
setBBox()
void TechDraw::LineSet::setBBox (const Bnd_Box & bb)
setEdges()
void TechDraw::LineSet::setEdges (std::vector< TopoDS_Edge > e)
setGeoms()
void TechDraw::LineSet::setGeoms (std::vector< TechDraw::BaseGeomPtr > g)
setPATLineSpec()
void TechDraw::LineSet::setPATLineSpec (const PATLineSpec & s)
Referenced by TechDraw::DrawGeomHatch::makeLineSets(), and TechDraw::DrawViewSection::makeLineSets().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/App/HatchLine.h
FreeCAD/src/Mod/TechDraw/App/HatchLine.cpp