FreeCAD: Part::GeometryCurvePy Class Reference
Part::GeometryCurvePy Class Reference
The python export class for GeomCurve.
#include <GeometryCurvePy.h>
Public Types
typedef GeomCurve * PointerType
Public Types inherited from Part::GeometryPy
typedef Geometry * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
GeometryCurvePy (GeomCurve *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Part::GeometryPy
GeometryPy (Geometry *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * clone (PyObject *args)
implementer for the clone() method
PyObject * hasExtensionOfType (PyObject *args)
implementer for the hasExtensionOfType() method
PyObject * hasExtensionOfName (PyObject *args)
implementer for the hasExtensionOfName() method
PyObject * getExtensionOfType (PyObject *args)
implementer for the getExtensionOfType() method
PyObject * getExtensionOfName (PyObject *args)
implementer for the getExtensionOfName() method
PyObject * setExtension (PyObject *args)
implementer for the setExtension() method
PyObject * deleteExtensionOfType (PyObject *args)
implementer for the deleteExtensionOfType() method
PyObject * deleteExtensionOfName (PyObject *args)
implementer for the deleteExtensionOfName() method
PyObject * getExtensions (PyObject *args)
implementer for the getExtensions() method
Py::String getTag (void) const
getter for the Tag attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geometry * getGeometryPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::GeometryPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_clone (PyObject *self, PyObject *args)
callback for the clone() method
static PyObject * staticCallback_hasExtensionOfType (PyObject *self, PyObject *args)
callback for the hasExtensionOfType() method
static PyObject * staticCallback_hasExtensionOfName (PyObject *self, PyObject *args)
callback for the hasExtensionOfName() method
static PyObject * staticCallback_getExtensionOfType (PyObject *self, PyObject *args)
callback for the getExtensionOfType() method
static PyObject * staticCallback_getExtensionOfName (PyObject *self, PyObject *args)
callback for the getExtensionOfName() method
static PyObject * staticCallback_setExtension (PyObject *self, PyObject *args)
callback for the setExtension() method
static PyObject * staticCallback_deleteExtensionOfType (PyObject *self, PyObject *args)
callback for the deleteExtensionOfType() method
static PyObject * staticCallback_deleteExtensionOfName (PyObject *self, PyObject *args)
callback for the deleteExtensionOfName() method
static PyObject * staticCallback_getExtensions (PyObject *self, PyObject *args)
callback for the getExtensions() method
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of GeometryCurvePy.
static PyMethodDef Methods []
Methods structure of GeometryCurvePy.
static PyTypeObject Type
Type structure of GeometryCurvePy.
Static Public Attributes inherited from Part::GeometryPy
static PyGetSetDef GetterSetter []
Attribute structure of GeometryPy.
static PyMethodDef Methods []
Methods structure of GeometryPy.
static PyTypeObject Type
Type structure of GeometryPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~GeometryCurvePy ()
Protected Member Functions inherited from Part::GeometryPy
~GeometryPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * toShape (PyObject *args)
implementer for the toShape() method
PyObject * discretize (PyObject *args, PyObject *kwd)
implementer for the discretize() method
PyObject * getD0 (PyObject *args)
implementer for the getD0() method
PyObject * getD1 (PyObject *args)
implementer for the getD1() method
PyObject * getD2 (PyObject *args)
implementer for the getD2() method
PyObject * getD3 (PyObject *args)
implementer for the getD3() method
PyObject * getDN (PyObject *args)
implementer for the getDN() method
PyObject * length (PyObject *args)
implementer for the length() method
PyObject * parameterAtDistance (PyObject *args)
implementer for the parameterAtDistance() method
PyObject * value (PyObject *args)
implementer for the value() method
PyObject * tangent (PyObject *args)
implementer for the tangent() method
PyObject * makeRuledSurface (PyObject *args)
implementer for the makeRuledSurface() method
PyObject * intersect2d (PyObject *args)
implementer for the intersect2d() method
PyObject * continuityWith (PyObject *args)
implementer for the continuityWith() method
PyObject * parameter (PyObject *args)
implementer for the parameter() method
PyObject * normal (PyObject *args)
implementer for the normal() method
PyObject * curvature (PyObject *args)
implementer for the curvature() method
PyObject * centerOfCurvature (PyObject *args)
implementer for the centerOfCurvature() method
PyObject * intersect (PyObject *args)
implementer for the intersect() method
PyObject * intersectCS (PyObject *args)
implementer for the intersectCS() method
PyObject * intersectCC (PyObject *args)
implementer for the intersectCC() method
PyObject * toBSpline (PyObject *args)
implementer for the toBSpline() method
PyObject * toNurbs (PyObject *args)
implementer for the toNurbs() method
PyObject * trim (PyObject *args)
implementer for the trim() method
PyObject * approximateBSpline (PyObject *args)
implementer for the approximateBSpline() method
PyObject * reverse (PyObject *args)
implementer for the reverse() method
PyObject * reversedParameter (PyObject *args)
implementer for the reversedParameter() method
PyObject * isPeriodic (PyObject *args)
implementer for the isPeriodic() method
PyObject * period (PyObject *args)
implementer for the period() method
PyObject * isClosed (PyObject *args)
implementer for the isClosed() method
static PyObject * staticCallback_toShape (PyObject *self, PyObject *args)
callback for the toShape() method
static PyObject * staticCallback_discretize (PyObject *self, PyObject *args, PyObject *kwd)
callback for the discretize() method
static PyObject * staticCallback_getD0 (PyObject *self, PyObject *args)
callback for the getD0() method
static PyObject * staticCallback_getD1 (PyObject *self, PyObject *args)
callback for the getD1() method
static PyObject * staticCallback_getD2 (PyObject *self, PyObject *args)
callback for the getD2() method
static PyObject * staticCallback_getD3 (PyObject *self, PyObject *args)
callback for the getD3() method
static PyObject * staticCallback_getDN (PyObject *self, PyObject *args)
callback for the getDN() method
static PyObject * staticCallback_length (PyObject *self, PyObject *args)
callback for the length() method
static PyObject * staticCallback_parameterAtDistance (PyObject *self, PyObject *args)
callback for the parameterAtDistance() method
static PyObject * staticCallback_value (PyObject *self, PyObject *args)
callback for the value() method
static PyObject * staticCallback_tangent (PyObject *self, PyObject *args)
callback for the tangent() method
static PyObject * staticCallback_makeRuledSurface (PyObject *self, PyObject *args)
callback for the makeRuledSurface() method
static PyObject * staticCallback_intersect2d (PyObject *self, PyObject *args)
callback for the intersect2d() method
static PyObject * staticCallback_continuityWith (PyObject *self, PyObject *args)
callback for the continuityWith() method
static PyObject * staticCallback_parameter (PyObject *self, PyObject *args)
callback for the parameter() method
static PyObject * staticCallback_normal (PyObject *self, PyObject *args)
callback for the normal() method
static PyObject * staticCallback_curvature (PyObject *self, PyObject *args)
callback for the curvature() method
static PyObject * staticCallback_centerOfCurvature (PyObject *self, PyObject *args)
callback for the centerOfCurvature() method
static PyObject * staticCallback_intersect (PyObject *self, PyObject *args)
callback for the intersect() method
static PyObject * staticCallback_intersectCS (PyObject *self, PyObject *args)
callback for the intersectCS() method
static PyObject * staticCallback_intersectCC (PyObject *self, PyObject *args)
callback for the intersectCC() method
static PyObject * staticCallback_toBSpline (PyObject *self, PyObject *args)
callback for the toBSpline() method
static PyObject * staticCallback_toNurbs (PyObject *self, PyObject *args)
callback for the toNurbs() method
static PyObject * staticCallback_trim (PyObject *self, PyObject *args)
callback for the trim() method
static PyObject * staticCallback_approximateBSpline (PyObject *self, PyObject *args)
callback for the approximateBSpline() method
static PyObject * staticCallback_reverse (PyObject *self, PyObject *args)
callback for the reverse() method
static PyObject * staticCallback_reversedParameter (PyObject *self, PyObject *args)
callback for the reversedParameter() method
static PyObject * staticCallback_isPeriodic (PyObject *self, PyObject *args)
callback for the isPeriodic() method
static PyObject * staticCallback_period (PyObject *self, PyObject *args)
callback for the period() method
static PyObject * staticCallback_isClosed (PyObject *self, PyObject *args)
callback for the isClosed() method
callbacks and implementers for the python object attributes
Py::String getContinuity (void) const
getter for the Continuity attribute
Py::Float getFirstParameter (void) const
getter for the FirstParameter attribute
Py::Float getLastParameter (void) const
getter for the LastParameter attribute
Py::Object getRotation (void) const
getter for the Rotation attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomCurve * getGeomCurvePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getContinuity (PyObject *self, void *closure)
getter callback for the Continuity attribute
static int staticCallback_setContinuity (PyObject *self, PyObject *value, void *closure)
setter callback for the Continuity attribute
static PyObject * staticCallback_getFirstParameter (PyObject *self, void *closure)
getter callback for the FirstParameter attribute
static int staticCallback_setFirstParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the FirstParameter attribute
static PyObject * staticCallback_getLastParameter (PyObject *self, void *closure)
getter callback for the LastParameter attribute
static int staticCallback_setLastParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the LastParameter attribute
static PyObject * staticCallback_getRotation (PyObject *self, void *closure)
getter callback for the Rotation attribute
static int staticCallback_setRotation (PyObject *self, PyObject *value, void *closure)
setter callback for the Rotation attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeomCurve.
Member Typedef Documentation
PointerType
typedef GeomCurve* Part::GeometryCurvePy::PointerType
Constructor & Destructor Documentation
~GeometryCurvePy()
GeometryCurvePy::~GeometryCurvePy () protected
GeometryCurvePy()
GeometryCurvePy::GeometryCurvePy (GeomCurve * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
approximateBSpline()
PyObject * GeometryCurvePy::approximateBSpline (PyObject * args)
implementer for the approximateBSpline() method
References Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, and draftutils.utils::tolerance().
Referenced by staticCallback_approximateBSpline().
centerOfCurvature()
PyObject * GeometryCurvePy::centerOfCurvature (PyObject * args)
implementer for the centerOfCurvature() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_centerOfCurvature().
continuityWith()
PyObject * GeometryCurvePy::continuityWith (PyObject * args)
implementer for the continuityWith() method
References getGeomCurvePtr(), Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, and Type.
Referenced by staticCallback_continuityWith().
curvature()
PyObject * GeometryCurvePy::curvature (PyObject * args)
implementer for the curvature() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by discretize(), and staticCallback_curvature().
discretize()
PyObject * GeometryCurvePy::discretize (PyObject * args, PyObject * kwd)
implementer for the discretize() method
References curvature(), Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_discretize().
getContinuity()
Py::String GeometryCurvePy::getContinuity (void) const
getter for the Continuity attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getContinuity().
getCustomAttributes()
PyObject * GeometryCurvePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getD0()
PyObject * GeometryCurvePy::getD0 (PyObject * args)
implementer for the getD0() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getD0().
getD1()
PyObject * GeometryCurvePy::getD1 (PyObject * args)
implementer for the getD1() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getD1().
getD2()
PyObject * GeometryCurvePy::getD2 (PyObject * args)
implementer for the getD2() method
References Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, and draftgeoutils.general::v1().
Referenced by staticCallback_getD2().
getD3()
PyObject * GeometryCurvePy::getD3 (PyObject * args)
implementer for the getD3() method
References Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, and draftgeoutils.general::v1().
Referenced by staticCallback_getD3().
getDN()
PyObject * GeometryCurvePy::getDN (PyObject * args)
implementer for the getDN() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getDN().
getFirstParameter()
Py::Float GeometryCurvePy::getFirstParameter (void) const
getter for the FirstParameter attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getFirstParameter().
getGeomCurvePtr()
GeomCurve * GeometryCurvePy::getGeomCurvePtr (void) const
getter for the object handled by this class
Referenced by continuityWith(), intersectCC(), toBSpline(), and toNurbs().
getLastParameter()
Py::Float GeometryCurvePy::getLastParameter (void) const
getter for the LastParameter attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getLastParameter().
getRotation()
Py::Object GeometryCurvePy::getRotation (void) const
getter for the Rotation attribute
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_getRotation().
GetType()
virtual PyTypeObject* Part::GeometryCurvePy::GetType (void) virtual
Reimplemented from Part::GeometryPy.
Reimplemented in Part::TrimmedCurvePy, Part::ParabolaPy, Part::OffsetCurvePy, Part::LineSegmentPy, Part::LinePy, Part::HyperbolaPy, Part::EllipsePy, Part::ConicPy, Part::CirclePy, Part::BSplineCurvePy, Part::BoundedCurvePy, Part::BezierCurvePy, Part::ArcPy, Part::ArcOfParabolaPy, Part::ArcOfHyperbolaPy, Part::ArcOfEllipsePy, Part::ArcOfConicPy, and Part::ArcOfCirclePy.
intersect()
PyObject * GeometryCurvePy::intersect (PyObject * args)
implementer for the intersect() method
References Part::GeometryPy::getGeometryPtr(), intersectCC(), intersectCS(), Type, and Part::GeometrySurfacePy::Type.
Referenced by staticCallback_intersect().
intersect2d()
PyObject * GeometryCurvePy::intersect2d (PyObject * args)
implementer for the intersect2d() method
References Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, Type, and Part::PlanePy::Type.
Referenced by staticCallback_intersect2d().
intersectCC()
PyObject * GeometryCurvePy::intersectCC (PyObject * args)
implementer for the intersectCC() method
References getGeomCurvePtr(), Part::GeomCurve::intersect(), and Type.
Referenced by intersect(), and staticCallback_intersectCC().
intersectCS()
PyObject * GeometryCurvePy::intersectCS (PyObject * args)
implementer for the intersectCS() method
References Part::GeometryPy::getGeometryPtr(), Part::makeGeometryCurvePy(), and Part::GeometrySurfacePy::Type.
Referenced by intersect(), Part::GeometrySurfacePy::intersect(), and staticCallback_intersectCS().
isClosed()
PyObject * GeometryCurvePy::isClosed (PyObject * args)
implementer for the isClosed() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_isClosed().
isPeriodic()
PyObject * GeometryCurvePy::isPeriodic (PyObject * args)
implementer for the isPeriodic() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_isPeriodic().
length()
PyObject * GeometryCurvePy::length (PyObject * args)
implementer for the length() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_length().
makeRuledSurface()
PyObject * GeometryCurvePy::makeRuledSurface (PyObject * args)
implementer for the makeRuledSurface() method
References Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, and Type.
Referenced by staticCallback_makeRuledSurface().
normal()
PyObject * GeometryCurvePy::normal (PyObject * args)
implementer for the normal() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by Part::ParabolaPy::PyInit(), Part::ArcOfEllipsePy::representation(), Part::ArcOfHyperbolaPy::representation(), Part::ArcOfParabolaPy::representation(), and staticCallback_normal().
parameter()
PyObject * GeometryCurvePy::parameter (PyObject * args)
implementer for the parameter() method
References Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, and Base::VectorPy::Type.
Referenced by Part::BSplineCurvePy::getCardinalSplineTangents(), and staticCallback_parameter().
parameterAtDistance()
PyObject * GeometryCurvePy::parameterAtDistance (PyObject * args)
implementer for the parameterAtDistance() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_parameterAtDistance().
period()
PyObject * GeometryCurvePy::period (PyObject * args)
implementer for the period() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_period().
PyInit()
int GeometryCurvePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::GeometryPy.
Reimplemented in Part::TrimmedCurvePy, Part::ParabolaPy, Part::OffsetCurvePy, Part::LineSegmentPy, Part::LinePy, Part::HyperbolaPy, Part::EllipsePy, Part::ConicPy, Part::CirclePy, Part::BSplineCurvePy, Part::BoundedCurvePy, Part::BezierCurvePy, Part::ArcPy, Part::ArcOfParabolaPy, Part::ArcOfHyperbolaPy, Part::ArcOfEllipsePy, Part::ArcOfConicPy, and Part::ArcOfCirclePy.
PyMake()
PyObject * GeometryCurvePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string GeometryCurvePy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
reverse()
PyObject * GeometryCurvePy::reverse (PyObject * args)
implementer for the reverse() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_reverse().
reversedParameter()
PyObject * GeometryCurvePy::reversedParameter (PyObject * args)
implementer for the reversedParameter() method
References Part::GeometryPy::getGeometryPtr().
Referenced by staticCallback_reversedParameter().
setCustomAttributes()
int GeometryCurvePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_approximateBSpline()
PyObject * GeometryCurvePy::staticCallback_approximateBSpline (PyObject * self, PyObject * args) static
callback for the approximateBSpline() method
References approximateBSpline(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_centerOfCurvature()
PyObject * GeometryCurvePy::staticCallback_centerOfCurvature (PyObject * self, PyObject * args) static
callback for the centerOfCurvature() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, centerOfCurvature(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_continuityWith()
PyObject * GeometryCurvePy::staticCallback_continuityWith (PyObject * self, PyObject * args) static
callback for the continuityWith() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, continuityWith(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_curvature()
PyObject * GeometryCurvePy::staticCallback_curvature (PyObject * self, PyObject * args) static
callback for the curvature() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, curvature(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_discretize()
PyObject * GeometryCurvePy::staticCallback_discretize (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the discretize() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, discretize(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getContinuity()
PyObject * GeometryCurvePy::staticCallback_getContinuity (PyObject * self, void * closure) static
getter callback for the Continuity attribute
References Base::BaseExceptionFreeCADError, getContinuity(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getD0()
PyObject * GeometryCurvePy::staticCallback_getD0 (PyObject * self, PyObject * args) static
callback for the getD0() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getD0(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getD1()
PyObject * GeometryCurvePy::staticCallback_getD1 (PyObject * self, PyObject * args) static
callback for the getD1() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getD1(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getD2()
PyObject * GeometryCurvePy::staticCallback_getD2 (PyObject * self, PyObject * args) static
callback for the getD2() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getD2(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getD3()
PyObject * GeometryCurvePy::staticCallback_getD3 (PyObject * self, PyObject * args) static
callback for the getD3() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getD3(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getDN()
PyObject * GeometryCurvePy::staticCallback_getDN (PyObject * self, PyObject * args) static
callback for the getDN() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getDN(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFirstParameter()
PyObject * GeometryCurvePy::staticCallback_getFirstParameter (PyObject * self, void * closure) static
getter callback for the FirstParameter attribute
References Base::BaseExceptionFreeCADError, getFirstParameter(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getLastParameter()
PyObject * GeometryCurvePy::staticCallback_getLastParameter (PyObject * self, void * closure) static
getter callback for the LastParameter attribute
References Base::BaseExceptionFreeCADError, getLastParameter(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRotation()
PyObject * GeometryCurvePy::staticCallback_getRotation (PyObject * self, void * closure) static
getter callback for the Rotation attribute
References Base::BaseExceptionFreeCADError, getRotation(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_intersect()
PyObject * GeometryCurvePy::staticCallback_intersect (PyObject * self, PyObject * args) static
callback for the intersect() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, intersect(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_intersect2d()
PyObject * GeometryCurvePy::staticCallback_intersect2d (PyObject * self, PyObject * args) static
callback for the intersect2d() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, intersect2d(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_intersectCC()
PyObject * GeometryCurvePy::staticCallback_intersectCC (PyObject * self, PyObject * args) static
callback for the intersectCC() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, intersectCC(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_intersectCS()
PyObject * GeometryCurvePy::staticCallback_intersectCS (PyObject * self, PyObject * args) static
callback for the intersectCS() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, intersectCS(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isClosed()
PyObject * GeometryCurvePy::staticCallback_isClosed (PyObject * self, PyObject * args) static
callback for the isClosed() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isClosed(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isPeriodic()
PyObject * GeometryCurvePy::staticCallback_isPeriodic (PyObject * self, PyObject * args) static
callback for the isPeriodic() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isPeriodic(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_length()
PyObject * GeometryCurvePy::staticCallback_length (PyObject * self, PyObject * args) static
callback for the length() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), length(), and Base::PyObjectBase::PyObjectBase().
staticCallback_makeRuledSurface()
PyObject * GeometryCurvePy::staticCallback_makeRuledSurface (PyObject * self, PyObject * args) static
callback for the makeRuledSurface() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), makeRuledSurface(), and Base::PyObjectBase::PyObjectBase().
staticCallback_normal()
PyObject * GeometryCurvePy::staticCallback_normal (PyObject * self, PyObject * args) static
callback for the normal() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), normal(), and Base::PyObjectBase::PyObjectBase().
staticCallback_parameter()
PyObject * GeometryCurvePy::staticCallback_parameter (PyObject * self, PyObject * args) static
callback for the parameter() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), parameter(), and Base::PyObjectBase::PyObjectBase().
staticCallback_parameterAtDistance()
PyObject * GeometryCurvePy::staticCallback_parameterAtDistance (PyObject * self, PyObject * args) static
callback for the parameterAtDistance() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), parameterAtDistance(), and Base::PyObjectBase::PyObjectBase().
staticCallback_period()
PyObject * GeometryCurvePy::staticCallback_period (PyObject * self, PyObject * args) static
callback for the period() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), period(), and Base::PyObjectBase::PyObjectBase().
staticCallback_reverse()
PyObject * GeometryCurvePy::staticCallback_reverse (PyObject * self, PyObject * args) static
callback for the reverse() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), reverse(), and Base::PyObjectBase::startNotify().
staticCallback_reversedParameter()
PyObject * GeometryCurvePy::staticCallback_reversedParameter (PyObject * self, PyObject * args) static
callback for the reversedParameter() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and reversedParameter().
staticCallback_setContinuity()
int GeometryCurvePy::staticCallback_setContinuity (PyObject * self, PyObject * value, void * closure) static
setter callback for the Continuity attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setFirstParameter()
int GeometryCurvePy::staticCallback_setFirstParameter (PyObject * self, PyObject * value, void * closure) static
setter callback for the FirstParameter attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setLastParameter()
int GeometryCurvePy::staticCallback_setLastParameter (PyObject * self, PyObject * value, void * closure) static
setter callback for the LastParameter attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setRotation()
int GeometryCurvePy::staticCallback_setRotation (PyObject * self, PyObject * value, void * closure) static
setter callback for the Rotation attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_tangent()
PyObject * GeometryCurvePy::staticCallback_tangent (PyObject * self, PyObject * args) static
callback for the tangent() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and tangent().
staticCallback_toBSpline()
PyObject * GeometryCurvePy::staticCallback_toBSpline (PyObject * self, PyObject * args) static
callback for the toBSpline() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and toBSpline().
staticCallback_toNurbs()
PyObject * GeometryCurvePy::staticCallback_toNurbs (PyObject * self, PyObject * args) static
callback for the toNurbs() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and toNurbs().
staticCallback_toShape()
PyObject * GeometryCurvePy::staticCallback_toShape (PyObject * self, PyObject * args) static
callback for the toShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and toShape().
staticCallback_trim()
PyObject * GeometryCurvePy::staticCallback_trim (PyObject * self, PyObject * args) static
callback for the trim() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and trim().
staticCallback_value()
PyObject * GeometryCurvePy::staticCallback_value (PyObject * self, PyObject * args) static
callback for the value() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and value().
tangent()
PyObject * GeometryCurvePy::tangent (PyObject * args)
implementer for the tangent() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_tangent().
toBSpline()
PyObject * GeometryCurvePy::toBSpline (PyObject * args)
implementer for the toBSpline() method
References getGeomCurvePtr(), Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, and Part::GeomCurve::toBSpline().
Referenced by staticCallback_toBSpline().
toNurbs()
PyObject * GeometryCurvePy::toNurbs (PyObject * args)
implementer for the toNurbs() method
References getGeomCurvePtr(), Part::GeometryPy::getGeometryPtr(), Part::PartExceptionOCCError, and Part::GeomCurve::toNurbs().
Referenced by staticCallback_toNurbs().
toShape()
PyObject * GeometryCurvePy::toShape (PyObject * args)
implementer for the toShape() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_toShape().
trim()
PyObject * GeometryCurvePy::trim (PyObject * args)
implementer for the trim() method
References Part::GeometryPy::getGeometryPtr(), Part::makeTrimmedCurvePy(), and Part::PartExceptionOCCError.
Referenced by Part::ArcOfConicPy::getAxis(), Part::ArcOfCirclePy::getCircle(), Part::ArcOfEllipsePy::getEllipse(), Part::ArcOfHyperbolaPy::getHyperbola(), Part::ArcOfParabolaPy::getParabola(), Part::ArcOfConicPy::getXAxis(), Part::ArcOfConicPy::getYAxis(), Part::ArcOfCirclePy::representation(), Part::ArcOfEllipsePy::representation(), Part::ArcOfHyperbolaPy::representation(), Part::ArcOfParabolaPy::representation(), Part::ArcOfConicPy::setAxis(), Part::ArcOfConicPy::setXAxis(), Part::ArcOfConicPy::setYAxis(), and staticCallback_trim().
value()
PyObject * GeometryCurvePy::value (PyObject * args)
implementer for the value() method
References Part::GeometryPy::getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by Part::BezierCurvePy::insertPoleAfter(), Part::BezierCurvePy::insertPoleBefore(), Part::BSplineCurvePy::movePoint(), Part::ArcOfCirclePy::PyInit(), Part::ArcPy::PyInit(), Part::CirclePy::PyInit(), Part::EllipsePy::PyInit(), Part::HyperbolaPy::PyInit(), Part::LinePy::PyInit(), Part::LineSegmentPy::PyInit(), Part::OffsetCurvePy::PyInit(), Part::ParabolaPy::PyInit(), Part::ArcOfConicPy::setAxis(), Part::ConicPy::setAxis(), Part::ArcOfConicPy::setCenter(), Part::ConicPy::setCenter(), Part::LinePy::setDirection(), Part::LineSegmentPy::setEndPoint(), Part::ArcOfConicPy::setLocation(), Part::ConicPy::setLocation(), Part::LinePy::setLocation(), Part::OffsetCurvePy::setOffsetDirection(), Part::BezierCurvePy::setPole(), Part::BSplineCurvePy::setPole(), Part::LineSegmentPy::setStartPoint(), Part::ArcOfConicPy::setXAxis(), Part::ConicPy::setXAxis(), Part::ArcOfConicPy::setYAxis(), Part::ConicPy::setYAxis(), and staticCallback_value().
Member Data Documentation
GetterSetter
PyGetSetDef GeometryCurvePy::GetterSetter static
Initial value:
= {
    {"Continuity",
        (getter) staticCallback_getContinuity,
        (setter) staticCallback_setContinuity,
        "\n                                     Returns the global continuity of the curve.\n                           ",
        NULL
    },
    {"FirstParameter",
        (getter) staticCallback_getFirstParameter,
        (setter) staticCallback_setFirstParameter,
        "\n                                     Returns the value of the first parameter.\n                             ",
        NULL
    },
    {"LastParameter",
        (getter) staticCallback_getLastParameter,
        (setter) staticCallback_setLastParameter,
        "\n                                     Returns the value of the last parameter.\n                              ",
        NULL
    },
    {"Rotation",
        (getter) staticCallback_getRotation,
        (setter) staticCallback_setRotation,
        "Returns a rotation object to describe the orientation for curve that supports it",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of GeometryCurvePy.
Methods
PyMethodDef GeometryCurvePy::Methods static
Methods structure of GeometryCurvePy.
Type
PyTypeObject GeometryCurvePy::Type static
Type structure of GeometryCurvePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), Part::BSplineSurfacePy::buildFromNSections(), continuityWith(), intersect(), Part::GeometrySurfacePy::intersect(), intersect2d(), intersectCC(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), makeRuledSurface(), and Part::CurveConstraintPy::PyInit().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeometryCurvePy.h
Sources/FreeCAD/src/Mod/Part/App/GeometryCurvePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeometryCurvePy.cpp