FreeCAD: SMDS_MeshGroup Class Reference
SMDS_MeshGroup Class Reference
#include <SMDS_MeshGroup.hxx>
Public Member Functions
bool Add (const SMDS_MeshElement *theElem)
const SMDS_MeshGroup * AddSubGroup (const SMDSAbs_ElementType theType=SMDSAbs_All)
void Clear ()
bool Contains (const SMDS_MeshElement *theElem) const
int Extent () const
const SMDS_Mesh * GetMesh () const
SMDSAbs_ElementType GetType () const
void InitIterator () const
void InitSubGroupsIterator () const
bool IsEmpty () const
bool More () const
bool MoreSubGroups () const
const SMDS_MeshElement * Next () const
const SMDS_MeshGroup * NextSubGroup () const
bool Remove (const SMDS_MeshElement *theElem)
virtual bool RemoveFromParent ()
virtual bool RemoveSubGroup (const SMDS_MeshGroup *theGroup)
void SetType (const SMDSAbs_ElementType theType)
SMDS_MeshGroup (const SMDS_Mesh *theMesh, const SMDSAbs_ElementType theType=SMDSAbs_All)
int SubGroupsNb () const
int Tic () const
Public Member Functions inherited from SMDS_MeshObject
virtual ~SMDS_MeshObject ()
Constructor & Destructor Documentation
SMDS_MeshGroup()
SMDS_MeshGroup::SMDS_MeshGroup (const SMDS_Mesh * theMesh, const SMDSAbs_ElementType theType = SMDSAbs_All)
Referenced by AddSubGroup().
Member Function Documentation
Add()
bool SMDS_MeshGroup::Add (const SMDS_MeshElement * theElem)
References SMDS_MeshElement::GetType().
Referenced by SMESHDS_Group::Add(), SMESH_MeshEditor::AddToSameGroups(), DriverMED_R_SMESHDS_Mesh::GetGroup(), StdMeshers_Import_1D::importMesh(), DriverUNV_R_SMDS_Mesh::Perform(), SMESH_MeshEditor::ReplaceElemInGroups(), and SMESH_Mesh::UNVToMesh().
AddSubGroup()
const SMDS_MeshGroup * SMDS_MeshGroup::AddSubGroup (const SMDSAbs_ElementType theType = SMDSAbs_All)
References SMDS_MeshGroup().
Referenced by DriverUNV_R_SMDS_Mesh::Perform().
Clear()
void SMDS_MeshGroup::Clear ()
Referenced by SMESHDS_Group::Clear().
Contains()
bool SMDS_MeshGroup::Contains (const SMDS_MeshElement * theElem) const
Referenced by SMESHDS_Group::Add(), SMESHDS_Group::Contains(), and SMESHDS_Group::Remove().
Extent()
int SMDS_MeshGroup::Extent () const
Referenced by SMESHDS_Group::Extent().
GetMesh()
const SMDS_Mesh* SMDS_MeshGroup::GetMesh () const
GetType()
SMDSAbs_ElementType SMDS_MeshGroup::GetType () const
Referenced by SMESHDS_Group::SetType(), and SMESH_Mesh::UNVToMesh().
InitIterator()
void SMDS_MeshGroup::InitIterator () const
Referenced by MyGroupIterator::MyGroupIterator(), and SMESH_Mesh::UNVToMesh().
InitSubGroupsIterator()
void SMDS_MeshGroup::InitSubGroupsIterator () const
Referenced by SMESH_Mesh::UNVToMesh().
IsEmpty()
bool SMDS_MeshGroup::IsEmpty () const
Referenced by SMESHDS_Group::Add(), SMESHDS_Group::IsEmpty(), SetType(), and SMESHDS_Group::SetType().
More()
bool SMDS_MeshGroup::More () const
Referenced by MyGroupIterator::more(), and SMESH_Mesh::UNVToMesh().
MoreSubGroups()
bool SMDS_MeshGroup::MoreSubGroups () const
Referenced by SMESH_Mesh::UNVToMesh().
Next()
const SMDS_MeshElement* SMDS_MeshGroup::Next () const
Referenced by MyGroupIterator::next(), and SMESH_Mesh::UNVToMesh().
NextSubGroup()
const SMDS_MeshGroup* SMDS_MeshGroup::NextSubGroup () const
Referenced by SMESH_Mesh::UNVToMesh().
Remove()
bool SMDS_MeshGroup::Remove (const SMDS_MeshElement * theElem)
Referenced by SMESHDS_Group::Remove(), SMESH_MeshEditor::RemoveElemFromGroups(), SMESHDS_Mesh::RemoveFreeElement(), and SMESHDS_Mesh::RemoveFreeNode().
RemoveFromParent()
bool SMDS_MeshGroup::RemoveFromParent () virtual
References RemoveSubGroup().
RemoveSubGroup()
bool SMDS_MeshGroup::RemoveSubGroup (const SMDS_MeshGroup * theGroup) virtual
Referenced by RemoveFromParent().
SetType()
void SMDS_MeshGroup::SetType (const SMDSAbs_ElementType theType)
References IsEmpty().
Referenced by SMESHDS_Group::SetType().
SubGroupsNb()
int SMDS_MeshGroup::SubGroupsNb () const
Tic()
int SMDS_MeshGroup::Tic () const
Referenced by SMESHDS_Group::GetTic().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_MeshGroup.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_MeshGroup.cpp