FreeCAD: MeshGui::RemoveComponents Class Reference
MeshGui::RemoveComponents Class Reference
Non-modal dialog to de/select components, regions, the complete or single faces of a mesh and delete them.
#include <RemoveComponents.h>
Public Slots
void on_cbDeselectComp_toggled (bool)
void on_cbSelectComp_toggled (bool)
void on_deselectAll_clicked ()
void on_deselectComponents_clicked ()
void on_deselectRegion_clicked ()
void on_deselectTriangle_clicked ()
void on_screenTriangles_toggled (bool)
void on_selectAll_clicked ()
void on_selectComponents_clicked ()
void on_selectRegion_clicked ()
void on_selectTriangle_clicked ()
void on_visibleTriangles_toggled (bool)
Public Member Functions
void deleteSelection ()
void invertSelection ()
void reject ()
RemoveComponents (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~RemoveComponents ()
Protected Member Functions
void changeEvent (QEvent *e)
Detailed Description
Non-modal dialog to de/select components, regions, the complete or single faces of a mesh and delete them.
Author
Werner Mayer
Constructor & Destructor Documentation
RemoveComponents()
RemoveComponents::RemoveComponents (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
References Gui::SelectionSingleton::clearSelection(), MeshGui::Ui_RemoveComponents::screenTriangles, Gui::Selection(), MeshGui::MeshSelection::setCheckOnlyPointToUserTriangles(), MeshGui::MeshSelection::setCheckOnlyVisibleTriangles(), MeshGui::MeshSelection::setEnabledViewerSelection(), MeshGui::Ui_RemoveComponents::setupUi(), MeshGui::Ui_RemoveComponents::spDeselectComp, MeshGui::Ui_RemoveComponents::spSelectComp, and MeshGui::Ui_RemoveComponents::visibleTriangles.
~RemoveComponents()
RemoveComponents::~RemoveComponents ()
Member Function Documentation
changeEvent()
void RemoveComponents::changeEvent (QEvent * e) protected
References MeshGui::Ui_RemoveComponents::retranslateUi().
deleteSelection()
void RemoveComponents::deleteSelection ()
References Gui::Application::activeDocument(), MeshGui::MeshSelection::deleteSelection(), Gui::Application::Instance, and draftutils.translate::QT_TRANSLATE_NOOP.
Referenced by MeshGui::TaskRemoveComponents::clicked().
invertSelection()
void RemoveComponents::invertSelection ()
References MeshGui::MeshSelection::invertSelection().
Referenced by MeshGui::TaskRemoveComponents::clicked().
on_cbDeselectComp_toggled
void RemoveComponents::on_cbDeselectComp_toggled (bool on) slot
References MeshGui::MeshSelection::setRemoveComponentOnClick().
on_cbSelectComp_toggled
void RemoveComponents::on_cbSelectComp_toggled (bool on) slot
References MeshGui::MeshSelection::setAddComponentOnClick().
on_deselectAll_clicked
void RemoveComponents::on_deselectAll_clicked () slot
References MeshGui::MeshSelection::clearSelection().
on_deselectComponents_clicked
void RemoveComponents::on_deselectComponents_clicked () slot
References MeshGui::MeshSelection::deselectComponent(), and MeshGui::Ui_RemoveComponents::spDeselectComp.
on_deselectRegion_clicked
void RemoveComponents::on_deselectRegion_clicked () slot
References MeshGui::MeshSelection::startDeselection().
on_deselectTriangle_clicked
void RemoveComponents::on_deselectTriangle_clicked () slot
References MeshGui::Ui_RemoveComponents::cbDeselectComp, MeshGui::MeshSelection::deselectTriangle(), and MeshGui::MeshSelection::setRemoveComponentOnClick().
on_screenTriangles_toggled
void RemoveComponents::on_screenTriangles_toggled (bool on) slot
References MeshGui::MeshSelection::setCheckOnlyPointToUserTriangles().
on_selectAll_clicked
void RemoveComponents::on_selectAll_clicked () slot
References MeshGui::MeshSelection::fullSelection().
on_selectComponents_clicked
void RemoveComponents::on_selectComponents_clicked () slot
References MeshGui::MeshSelection::selectComponent(), and MeshGui::Ui_RemoveComponents::spSelectComp.
on_selectRegion_clicked
void RemoveComponents::on_selectRegion_clicked () slot
References MeshGui::MeshSelection::startSelection().
on_selectTriangle_clicked
void RemoveComponents::on_selectTriangle_clicked () slot
References MeshGui::Ui_RemoveComponents::cbSelectComp, MeshGui::MeshSelection::selectTriangle(), and MeshGui::MeshSelection::setAddComponentOnClick().
on_visibleTriangles_toggled
void RemoveComponents::on_visibleTriangles_toggled (bool on) slot
References MeshGui::MeshSelection::setCheckOnlyVisibleTriangles().
reject()
void RemoveComponents::reject (void)
References MeshGui::MeshSelection::clearSelection(), and MeshGui::MeshSelection::setEnabledViewerSelection().
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), MeshGui::TaskRemoveComponents::clicked(), femexamples.examplesgui.FemExamples::clicked(), MeshGui::RemoveComponentsDialog::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/Gui/RemoveComponents.h
FreeCAD/src/Mod/Mesh/Gui/RemoveComponents.cpp