FreeCAD: PartGui::Mirroring Class Reference
PartGui::Mirroring Class Reference
#include <Mirroring.h>
Public Member Functions
bool accept ()
Mirroring (QWidget *parent=0)
~Mirroring ()
Protected Member Functions
void changeEvent (QEvent *e)
Constructor & Destructor Documentation
Mirroring()
Mirroring::Mirroring (QWidget * parent = 0)
References Gui::ItemViewSelection::applyFrom(), Base::Persistence::getClassTypeId(), draftutils.utils::getObjectsOfType, Base::Unit::Length, and Gui::Selection().
~Mirroring()
Mirroring::~Mirroring ()
Member Function Documentation
accept()
bool Mirroring::accept (void)
References Gui::Command::App, App::Document::commitTransaction(), App::Document::countObjectsOfType(), Base::Tools::escapedUnicodeFromUtf8(), Base::Type::fromName(), App::GetApplication(), App::Application::getDocument(), App::Document::openTransaction(), and App::Document::recompute().
Referenced by PartGui::TaskMirroring::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void Mirroring::changeEvent (QEvent * e) protected
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/Gui/Mirroring.h
Sources/FreeCAD/src/Mod/Part/Gui/Mirroring.cpp