FreeCAD: RobotGui::TrajectorySimulate Class Reference
RobotGui::TrajectorySimulate Class Reference
#include <TrajectorySimulate.h>
Public Member Functions
TrajectorySimulate (Robot::RobotObject *pcRobotObject, Robot::TrajectoryObject *pcTrajectoryObject, QWidget *parent=0)
~TrajectorySimulate ()
Protected Member Functions
void setTo (void)
Protected Attributes
bool block
float duration
bool Run
Robot::Simulation sim
float timePos
QTimer * timer
ViewProviderRobotObject * ViewProv
Constructor & Destructor Documentation
TrajectorySimulate()
TrajectorySimulate::TrajectorySimulate (Robot::RobotObject * pcRobotObject, Robot::TrajectoryObject * pcTrajectoryObject, QWidget * parent = 0)
References Robot::Waypoint::Accelaration, Gui::Application::activeDocument(), Robot::Waypoint::CIRC, draftgeoutils.intersections::connect(), Robot::Waypoint::Cont, duration, Robot::Trajectory::getDuration(), Robot::Trajectory::getSize(), App::PropertyPlacement::getValue(), Robot::PropertyTrajectory::getValue(), Gui::Document::getViewProvider(), Robot::Trajectory::getWaypoint(), Gui::Application::Instance, Robot::Waypoint::LINE, Robot::Waypoint::Name, Robot::Waypoint::PTP, setTo(), sim, timer, Robot::RobotObject::Tool, Robot::Simulation::Tool, Robot::TrajectoryObject::Trajectory, Robot::Waypoint::Type, Robot::Waypoint::UNDEF, Robot::Waypoint::Velocity, and ViewProv.
~TrajectorySimulate()
TrajectorySimulate::~TrajectorySimulate ()
Member Function Documentation
setTo()
void TrajectorySimulate::setTo (void) protected
References Robot::Simulation::Axis, Robot::Robot6Axis::getTcp(), Robot::Simulation::Rob, RobotGui::ViewProviderRobotObject::setAxisTo(), Robot::Simulation::setToTime(), sim, timePos, and ViewProv.
Referenced by TrajectorySimulate().
Member Data Documentation
block
bool RobotGui::TrajectorySimulate::block protected
Referenced by AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::attachmentOffsetChanged(), AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::checkBoxFlipClicked(), AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::fillAllRefLines(), AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::lineRefChanged(), AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::modeSelected(), AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::readParameters(), AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::refButtonClicked(), AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::updateListOfModes(), and AttachmentEditor.TaskAttachmentEditor.AttachmentEditorTaskPanel::updateRefButtons().
duration
float RobotGui::TrajectorySimulate::duration protected
Referenced by TrajectorySimulate(), and automotive_design.time_interval_with_bounds::wr1().
Run
bool RobotGui::TrajectorySimulate::Run protected
sim
Robot::Simulation RobotGui::TrajectorySimulate::sim protected
Referenced by setTo(), and TrajectorySimulate().
timePos
float RobotGui::TrajectorySimulate::timePos protected
Referenced by setTo().
timer
QTimer* RobotGui::TrajectorySimulate::timer protected
Referenced by ArchReference.ViewProviderArchReference::checkChanges(), PathScripts.PathSimulatorGui.PathSimulation::EndSimulation(), shipHydrostatics.TaskPanel.TaskPanel::externalFaces(), ArchReference.ViewProviderArchReference::onDelete(), PathScripts.PathSimulatorGui.PathSimulation::onSpeedBarChange(), PathScripts.PathSimulatorGui.PathSimulation::SimFF(), PathScripts.PathSimulatorGui.PathSimulation::SimPause(), PathScripts.PathSimulatorGui.PathSimulation::SimPlay(), and TrajectorySimulate().
ViewProv
ViewProviderRobotObject* RobotGui::TrajectorySimulate::ViewProv protected
Referenced by setTo(), and TrajectorySimulate().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Robot/Gui/TrajectorySimulate.h
Sources/FreeCAD/src/Mod/Robot/Gui/TrajectorySimulate.cpp