FreeCAD: Gui::SoFCBoundingBox Class Reference
Gui::SoFCBoundingBox Class Reference
A subclass of SoShape used to create an axis aligned wire frame box based on the minBounds and maxBounds fields.
#include <SoFCBoundingBox.h>
Public Member Functions
SoFCBoundingBox ()
Static Public Member Functions
static void finish ()
static void initClass ()
Public Attributes
SoSFBool coordsOn
If true, the coordinates are displayed at each vertex.
SoSFBool dimensionsOn
If true, the dimensions are displayed in x,y and z direction.
SoSFVec3f maxBounds
maximum box coordinates
SoSFVec3f minBounds
minimum box coordinates
Protected Member Functions
virtual void computeBBox (SoAction *action, SbBox3f &box, SbVec3f &center)
virtual void generatePrimitives (SoAction *action)
virtual void GLRender (SoGLRenderAction *action)
virtual ~SoFCBoundingBox ()
Detailed Description
A subclass of SoShape used to create an axis aligned wire frame box based on the minBounds and maxBounds fields.
The class also has a field which can be toggled on or off for displaying text coordinate labels at the vertices of the box.
Note
Original source are taken from http://www.wheatchex.com/projects/openinventor/bbox/BoundingBox.h and http://www.wheatchex.com/projects/openinventor/bbox/BoundingBox.cpp
Date
November 12th, 2001
Author
Josh Grant
Constructor & Destructor Documentation
SoFCBoundingBox()
SoFCBoundingBox::SoFCBoundingBox ()
References coordsOn, dimensionsOn, maxBounds, and minBounds.
~SoFCBoundingBox()
SoFCBoundingBox::~SoFCBoundingBox () protected virtual
Member Function Documentation
computeBBox()
void SoFCBoundingBox::computeBBox (SoAction * action, SbBox3f & box, SbVec3f & center) protected virtual
References maxBounds, and minBounds.
finish()
void SoFCBoundingBox::finish (void) static
Referenced by drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), draftguitools.gui_shapestrings.ShapeString::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_split.Split::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_edit.Edit::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_selectplane.Draft_SelectPlane::checkSelection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_labels.Label::create(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_shapestrings.ShapeString::createObject(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::escape(), Gui::SoFCDB::finish(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_arcs.Arc_3Points::getPoint(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_fillets.Fillet::numericRadius(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickAlign(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickAuto(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickCenter(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickFront(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickMove(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickPrevious(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickSide(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickTop(), draftguitools.gui_array_simple.Array::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
generatePrimitives()
void SoFCBoundingBox::generatePrimitives (SoAction * action) protected virtual
GLRender()
void SoFCBoundingBox::GLRender (SoGLRenderAction * action) protected virtual
References coordsOn, dimensionsOn, maxBounds, and minBounds.
initClass()
void SoFCBoundingBox::initClass (void) static
Referenced by Gui::SoFCDB::init().
Member Data Documentation
coordsOn
SoSFBool Gui::SoFCBoundingBox::coordsOn
If true, the coordinates are displayed at each vertex.
Referenced by GLRender(), Gui::ViewProviderGeometryObject::showBoundingBox(), and SoFCBoundingBox().
dimensionsOn
SoSFBool Gui::SoFCBoundingBox::dimensionsOn
If true, the dimensions are displayed in x,y and z direction.
Referenced by GLRender(), Gui::ViewProviderGeometryObject::showBoundingBox(), and SoFCBoundingBox().
maxBounds
SoSFVec3f Gui::SoFCBoundingBox::maxBounds
maximum box coordinates
Referenced by computeBBox(), GLRender(), PathGui::ViewProviderPath::recomputeBoundingBox(), SoFCBoundingBox(), and Gui::ViewProviderGeometryObject::updateData().
minBounds
SoSFVec3f Gui::SoFCBoundingBox::minBounds
minimum box coordinates
Referenced by computeBBox(), GLRender(), PathGui::ViewProviderPath::recomputeBoundingBox(), SoFCBoundingBox(), and Gui::ViewProviderGeometryObject::updateData().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/SoFCBoundingBox.h
FreeCAD/src/Gui/SoFCBoundingBox.cpp