FreeCAD: UNV2417 Namespace Reference
UNV2417 Namespace Reference
Classes
struct TRecord
Typedefs
typedef std::map< TGroupId, TRecord > TDataSet
typedef int TGroupId
typedef std::vector< int > TListOfId
Functions
void Read (std::ifstream &in_stream, TDataSet &theDataSet)
void ReadGroup (const std::string &myGroupLabel, std::ifstream &in_stream, TDataSet &theDataSet)
void Write (std::ofstream &out_stream, const TDataSet &theDataSet)
Typedef Documentation
TDataSet
typedef std::map<TGroupId, TRecord> UNV2417::TDataSet
TGroupId
typedef int UNV2417::TGroupId
TListOfId
typedef std::vector<int> UNV2417::TListOfId
Function Documentation
Read()
void UNV2417::Read (std::ifstream & in_stream, TDataSet & theDataSet)
References ReadGroup().
Referenced by DriverUNV_R_SMDS_Mesh::Perform().
ReadGroup()
void UNV2417::ReadGroup (const std::string & myGroupLabel, std::ifstream & in_stream, TDataSet & theDataSet)
References UNV2417::TRecord::ElementList, UNV2417::TRecord::GroupName, and UNV2417::TRecord::NodeList.
Referenced by Read().
Write()
void UNV2417::Write (std::ofstream & out_stream, const TDataSet & theDataSet)
References UNV2417::TRecord::ElementList, UNV2417::TRecord::GroupName, and UNV2417::TRecord::NodeList.
Referenced by DriverUNV_W_SMDS_Mesh::Perform().