FreeCAD: MeshGui::SoSFMeshPointArray Class Reference
MeshGui::SoSFMeshPointArray Class Reference
#include <SoFCMeshVertex.h>
Public Member Functions
void setValue (const MeshCore::MeshPointArray &p)
Static Public Member Functions
static void initClass (void)
Protected Member Functions
int getNumValuesPerLine () const
SbBool read1Value (SoInput *in, unsigned long idx)
SbBool readBinaryValues (SoInput *in, unsigned long numarg)
void write1Value (SoOutput *out, unsigned long idx) const
void writeBinaryValues (SoOutput *out) const
Member Function Documentation
getNumValuesPerLine()
int SoSFMeshPointArray::getNumValuesPerLine () const protected
initClass()
void SoSFMeshPointArray::initClass (void) static
read1Value()
SbBool SoSFMeshPointArray::read1Value (SoInput * in, unsigned long idx) protected
Referenced by readBinaryValues().
readBinaryValues()
SbBool SoSFMeshPointArray::readBinaryValues (SoInput * in, unsigned long numarg) protected
References read1Value().
setValue()
void SoSFMeshPointArray::setValue (const MeshCore::MeshPointArray & p)
write1Value()
void SoSFMeshPointArray::write1Value (SoOutput * out, unsigned long idx) const protected
Referenced by writeBinaryValues().
writeBinaryValues()
void SoSFMeshPointArray::writeBinaryValues (SoOutput * out) const protected
References write1Value().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCMeshVertex.h
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCMeshVertex.cpp