FreeCAD: TechDrawGui::QGICenterLine Class Reference
TechDrawGui::QGICenterLine Class Reference
#include <QGICenterLine.h>
Public Types
enum { Type = QGraphicsItem::UserType + 174 }
Public Types inherited from TechDrawGui::QGIDecoration
enum { Type = QGraphicsItem::UserType + 173 }
Public Member Functions
virtual void draw ()
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr)
QGICenterLine ()
void setBounds (double x1, double y1, double x2, double y2)
void setIntersection (bool isIntersecting)
int type () const
~QGICenterLine ()
Public Member Functions inherited from TechDrawGui::QGIDecoration
virtual QRectF boundingRect () const
virtual void draw ()
QColor getColor (void)
void makeMark (Base::Vector3d v)
void makeMark (double x, double y)
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr)
QGIDecoration (void)
void setColor (QColor c)
void setFill (Qt::BrushStyle bs)
void setStyle (Qt::PenStyle s)
void setWidth (double w)
int type () const
~QGIDecoration ()
Protected Member Functions
QColor getCenterColor ()
Qt::PenStyle getCenterStyle ()
void makeLine ()
void setTools ()
Protected Member Functions inherited from TechDrawGui::QGIDecoration
virtual QColor prefNormalColor (void)
virtual QColor prefPreColor (void)
virtual QColor prefSelectColor (void)
void setPrettyNormal ()
void setPrettyPre ()
void setPrettySel ()
Additional Inherited Members
Protected Attributes inherited from TechDrawGui::QGIDecoration
QBrush m_brush
Qt::BrushStyle m_brushCurrent
QColor m_colCurrent
QColor m_colNormal
QPen m_pen
Qt::PenStyle m_styleCurrent
double m_width
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGICenterLine()
QGICenterLine::QGICenterLine () explicit
References getCenterColor(), getCenterStyle(), TechDrawGui::QGIDecoration::setColor(), TechDrawGui::QGIDecoration::setStyle(), and TechDrawGui::QGIDecoration::setWidth().
~QGICenterLine()
TechDrawGui::QGICenterLine::~QGICenterLine ()
Member Function Documentation
draw()
void QGICenterLine::draw (void) virtual
Reimplemented from TechDrawGui::QGIDecoration.
References makeLine().
Referenced by TechDrawGui::QGIViewPart::drawCenterLines().
getCenterColor()
QColor QGICenterLine::getCenterColor () protected
References TechDrawGui::PreferencesGui::centerQColor().
Referenced by QGICenterLine().
getCenterStyle()
Qt::PenStyle QGICenterLine::getCenterStyle () protected
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), and App::Application::GetUserParameter().
Referenced by QGICenterLine().
makeLine()
void QGICenterLine::makeLine () protected
Referenced by draw().
paint()
void QGICenterLine::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) virtual
Reimplemented from TechDrawGui::QGIDecoration.
References TechDrawGui::QGIDecoration::paint(), and setTools().
setBounds()
void QGICenterLine::setBounds (double x1, double y1, double x2, double y2)
Referenced by TechDrawGui::QGIViewPart::drawCenterLines().
setIntersection()
void QGICenterLine::setIntersection (bool isIntersecting)
Set the intersection style for the centerline. If isIntersecting is set to true, the middle of the centerline will be the middle of a dash - therefore if two lines intersect, they will form a cross. If isIntersecting is set to false, the middle of the centerline will be a dot.
Referenced by TechDrawGui::QGIViewPart::drawCenterLines().
setTools()
void QGICenterLine::setTools () protected
References TechDrawGui::QGIDecoration::m_colCurrent, TechDrawGui::QGIDecoration::m_pen, TechDrawGui::QGIDecoration::m_styleCurrent, and TechDrawGui::QGIDecoration::m_width.
Referenced by paint().
type()
int TechDrawGui::QGICenterLine::type () const
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/QGICenterLine.h
FreeCAD/src/Mod/TechDraw/Gui/QGICenterLine.cpp