FreeCAD: ArchCutPlane Namespace Reference
ArchCutPlane Namespace Reference
Workbenches » Python workbenches » Arch
The Cut plane object and tools.
Functions
def cutComponentwithPlane (archObject, cutPlane, sideFace)
def getPlanWithLine (line)
Detailed Description
The Cut plane object and tools.
This module handles the Cut Plane object
Function Documentation
cutComponentwithPlane()
def ArchCutPlane.cutComponentwithPlane (archObject, cutPlane, sideFace)
cut object from a plan define by a face, Behind = 0 , front = 1
References ArchCommands.getCutVolume(), getPlanWithLine(), and ArchCommands.removeComponents().
getPlanWithLine()
def ArchCutPlane.getPlanWithLine (line)
Function to make a plane along Normal plan
Referenced by cutComponentwithPlane().