FreeCAD: App::PropertyQuantity Class Reference
App::PropertyQuantity Class Reference
Float with Unit property This is a property for float with a predefined Unit associated.
#include <PropertyUnits.h>
Public Member Functions
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
Base::Quantity getQuantityValue (void) const
const Base::Unit & getUnit (void) const
double getValue (void) const
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
PropertyQuantity (void)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual void setPyObject (PyObject *)
void setUnit (const Base::Unit &u)
void setValue (double lValue)
virtual ~PropertyQuantity ()
Public Member Functions inherited from App::PropertyFloat
virtual Property * Copy (void) const
Returns a new copy of the property (mainly for Undo/Redo and transactions)
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
double getValue (void) const
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
virtual void Paste (const Property &from)
Paste the value from the property (mainly for Undo/Redo and transactions)
PropertyFloat (void)
Value Constructor Construct with explicit Values.
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual void setPyObject (PyObject *)
void setValue (double lValue)
virtual ~PropertyFloat ()
A destructor.
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual Property * Copy (void) const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
int64_t getID () const
Return a unique ID for the property.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const char * getName (void) const
Get the name of this property in the belonging container With hasName() it can be checked beforehand if a valid name is set.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
bool hasName () const
Check if the property has a name set.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Member Functions
Base::Quantity createQuantityFromPy (PyObject *value)
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , Busy = 15 ,
CopyOnChange = 16 , UserEdit = 17 , PropStaticBegin = 21 , PropDynamic = 21 ,
PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 , PropTransient = 25 ,
PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 , User1 = 28 ,
User2 = 29 , User3 = 30 , User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Check if the passed name is valid.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Detailed Description
Float with Unit property This is a property for float with a predefined Unit associated.
Constructor & Destructor Documentation
PropertyQuantity()
App::PropertyQuantity::PropertyQuantity (void)
~PropertyQuantity()
virtual App::PropertyQuantity::~PropertyQuantity () virtual
Member Function Documentation
createQuantityFromPy()
Base::Quantity PropertyQuantity::createQuantityFromPy (PyObject * value) protected
Referenced by setPyObject(), and App::PropertyQuantityConstraint::setPyObject().
getEditorName()
const char * PropertyQuantity::getEditorName (void) const virtual
Get the class name of the associated property editor item.
Reimplemented from App::PropertyFloat.
Reimplemented in App::PropertyQuantityConstraint, and App::PropertyAngle.
getPathValue()
const boost::any PropertyQuantity::getPathValue (const App::ObjectIdentifier & path) const virtual
Get value of property.
Reimplemented from App::PropertyFloat.
getPyObject()
PyObject * PropertyQuantity::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from App::PropertyFloat.
getQuantityValue()
Base::Quantity PropertyQuantity::getQuantityValue (void) const
Referenced by SpreadsheetGui::SheetModel::data(), PartGui::DlgPrimitives::DlgPrimitives(), App::FunctionExpression::evalAggregate(), PartDesignGui::TaskBoxPrimitives::onCylinderXSkewChanged(), PartDesignGui::TaskBoxPrimitives::onCylinderYSkewChanged(), PartDesignGui::TaskBoxPrimitives::onPrismXSkewChanged(), and PartDesignGui::TaskBoxPrimitives::onPrismYSkewChanged().
getUnit()
const Base::Unit & App::PropertyQuantity::getUnit (void) const
Referenced by SpreadsheetGui::SheetModel::data(), Spreadsheet::Cell::getFormattedQuantity(), TechDraw::DrawViewDimension::onChanged(), and Gui::ExpressionSpinBox::openFormulaDialog().
getValue()
double App::PropertyQuantity::getValue (void) const
References App::PropertyFloat::getValue().
Referenced by PartDesignGui::TaskHelixParameters::apply(), Gui::InputField::bind(), TechDraw::DrawViewPart::buildGeometryObject(), TechDraw::DrawProjGroup::calculateAutomaticScale(), PartDesignGui::TaskHoleParameters::changedObject(), Part::Extrusion::computeFinalParameters(), PartGui::ViewProvider2DObjectGrid::createGrid(), Gui::PointMarker::customEvent(), SpreadsheetGui::SheetModel::data(), TechDraw::DrawViewDetail::detailExec(), TechDrawGui::QGILeaderLine::draw(), TechDrawGui::QGIViewBalloon::drawBalloon(), TechDrawGui::QGIViewClip::drawClip(), TechDrawGui::QGIViewPart::drawHighlight(), TechDrawGui::QGIViewPart::drawPainterPath(), TechDrawGui::QGIViewSection::drawSectionFace(), TechDrawGui::QGIViewPart::drawSectionLine(), TechDrawGui::QGIViewPart::drawViewPart(), Mesh::Sphere::execute(), Mesh::Ellipsoid::execute(), Mesh::Cylinder::execute(), Mesh::Cone::execute(), Mesh::Torus::execute(), Mesh::Cube::execute(), PartDesign::Pad::execute(), PartDesign::Pocket::execute(), Part::Box::execute(), Part::Circle::execute(), Part::Thickness::execute(), Part::Vertex::execute(), Part::Line::execute(), Part::Plane::execute(), Part::Sphere::execute(), Part::Ellipsoid::execute(), Part::Cylinder::execute(), Part::Prism::execute(), Part::RegularPolygon::execute(), Part::Cone::execute(), Part::Torus::execute(), Part::Helix::execute(), Part::Spiral::execute(), Part::Wedge::execute(), Part::Ellipse::execute(), PartDesign::Fillet::execute(), PartDesign::Groove::execute(), PartDesign::Helix::execute(), PartDesign::Hole::execute(), PartDesign::Box::execute(), PartDesign::Cylinder::execute(), PartDesign::Sphere::execute(), PartDesign::Cone::execute(), PartDesign::Ellipsoid::execute(), PartDesign::Torus::execute(), PartDesign::Prism::execute(), PartDesign::Wedge::execute(), PartDesign::Revolution::execute(), PartDesign::Thickness::execute(), Robot::TrajectoryDressUpObject::execute(), PartDesign::Chamfer::execute(), TechDraw::DrawViewArch::execute(), TechDraw::DrawViewMulti::execute(), PartDesign::Helix::generateHelixPath(), TechDrawGui::TaskDetail::getAnchorScene(), TechDrawGui::QGILeaderLine::getAttachFromFeature(), TechDraw::DrawLeaderLine::getAttachPoint(), TechDraw::DrawProjGroup::getBoundingBox(), TechDrawGui::TaskCenterLine::getCenterWidth(), TechDraw::DrawViewDimension::getFormattedDimensionValue(), TechDraw::DrawViewDimension::getFormattedToleranceValue(), TechDraw::DrawViewDimension::getFormattedToleranceValues(), TechDraw::DrawSVGTemplate::getHeight(), TechDraw::DrawTemplate::getHeight(), TechDraw::DrawViewBalloon::getOrigin(), TechDraw::DrawViewBalloon::getOriginOffset(), TechDraw::DrawViewAnnotation::getRect(), TechDraw::DrawViewClip::getRect(), TechDraw::DrawProjGroup::getRect(), PartDesign::LinearPattern::getTransformations(), PartDesign::PolarPattern::getTransformations(), TechDraw::DrawSVGTemplate::getWidth(), TechDraw::DrawTemplate::getWidth(), TechDraw::DrawProjGroup::getXYPosition(), TechDraw::DrawViewDimension::handleChangedPropertyType(), PartDesign::Helix::handleChangedPropertyType(), TechDraw::DrawView::handleChangedPropertyType(), TechDraw::DrawViewBalloon::handleChangedPropertyType(), TechDraw::DrawViewDimension::hasOverUnderTolerance(), PartDesign::FeatureExtrude::hasTaperedAngle(), TechDraw::DrawViewDimension::haveTolerance(), PartGui::ViewProviderPartExt::loadParameter(), TechDraw::DrawViewPart::makeGeometryForShape(), Part::PrismExtension::makePrism(), Gui::ViewProviderAnnotation::onChanged(), Fem::FemPostSphereFunction::onChanged(), PartDesign::Hole::onChanged(), TechDraw::DrawProjGroup::onChanged(), TechDraw::DrawViewDimension::onChanged(), PartGui::SectionCut::onCutXvalueChanged(), PartGui::SectionCut::onCutYvalueChanged(), PartGui::SectionCut::onCutZvalueChanged(), TechDrawGui::TaskDetail::onHighlightMoved(), TechDrawGui::TaskCosVertex::onTrackerFinished(), Part::Box::Restore(), Part::Circle::Restore(), Part::Ellipse::Restore(), TechDrawGui::QGIView::rotateView(), TechDrawGui::QGIViewAnnotation::rotateView(), TechDrawGui::QGIViewImage::rotateView(), TechDrawGui::QGIViewSymbol::rotateView(), PartDesign::Helix::safePitch(), TechDrawGui::TaskProjGroup::saveGroupState(), TechDrawGui::TaskLeaderLine::saveState(), PartGui::SectionCut::SectionCut(), TechDraw::DrawViewSection::sectionExec(), TechDraw::DrawViewSection::sectionLineEnds(), PartDesignGui::ViewProviderDatumLine::setExtents(), PartDesignGui::ViewProviderDatumPlane::setExtents(), TechDrawGui::ViewProviderPage::setGrid(), TechDrawGui::QGILeaderLine::setLeaderFeature(), TechDraw::DrawView::setPosition(), TechDrawGui::TaskLeaderLine::setUiEdit(), TechDrawGui::TaskRichAnno::setUiEdit(), TechDrawGui::QGIViewBalloon::setViewPartFeature(), TechDrawGui::TaskBalloon::TaskBalloon(), PartDesignGui::TaskBoxPrimitives::TaskBoxPrimitives(), TechDrawGui::TaskDimension::TaskDimension(), PartDesignGui::TaskDraftParameters::TaskDraftParameters(), PartDesignGui::TaskFilletParameters::TaskFilletParameters(), PartDesignGui::TaskHoleParameters::TaskHoleParameters(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), TechDrawGui::TaskProjGroup::TaskProjGroup(), PartDesignGui::TaskRevolutionParameters::TaskRevolutionParameters(), TechDrawGui::TaskRichAnno::TaskRichAnno(), SketcherGui::TaskSketcherGeneral::TaskSketcherGeneral(), PartDesignGui::TaskThicknessParameters::TaskThicknessParameters(), RobotGui::TaskTrajectoryDressUpParameter::TaskTrajectoryDressUpParameter(), PartGui::ThicknessWidget::ThicknessWidget(), PartDesignGui::ViewProviderAddSub::updateAddSubShapeIndicator(), ImageGui::ViewProviderImagePlane::updateData(), PartDesignGui::ViewProviderDatumLine::updateData(), PartDesignGui::ViewProviderDatumPlane::updateData(), TechDrawGui::QGIView::updateView(), and PartGui::ViewProviderPartExt::updateVisual().
isSame()
virtual bool App::PropertyQuantity::isSame (const Property & other) const virtual
Compare if this property has the same content as the given one.
Reimplemented from App::PropertyFloat.
References Base::Persistence::getTypeId().
setPathValue()
void PropertyQuantity::setPathValue (const App::ObjectIdentifier & path, const boost::any & value) virtual
Set value of property.
Reimplemented from App::PropertyFloat.
References App::Property::aboutToSetValue(), App::anyToQuantity(), and setValue().
setPyObject()
void PropertyQuantity::setPyObject (PyObject * value) virtual
Reimplemented from App::PropertyFloat.
Reimplemented in App::PropertyQuantityConstraint.
References App::Property::aboutToSetValue(), createQuantityFromPy(), Base::Quantity::getUnit(), Base::Quantity::getValue(), App::Property::hasSetValue(), and App::PropertyFloat::setValue().
setUnit()
void App::PropertyQuantity::setUnit (const Base::Unit & u)
Referenced by PartDesign::Chamfer::Chamfer(), TechDraw::DrawViewDimension::DrawViewDimension(), App::FeatureTest::FeatureTest(), PartDesign::Fillet::Fillet(), TechDraw::DrawViewDimension::onChanged(), TechDraw::DrawViewDimension::onDocumentRestored(), and Spreadsheet::Sheet::setQuantityProperty().
setValue()
void App::PropertyQuantity::setValue (double lValue)
References App::PropertyFloat::setValue().
Referenced by TechDraw::DrawProjGroupItem::autoPosition(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::QGSPage::createBalloon(), App::MeasureDistance::execute(), PartDesign::Helix::execute(), TechDraw::DrawViewDimension::handleChangedPropertyType(), Mesh::Sphere::handleChangedPropertyType(), Part::Thickness::handleChangedPropertyType(), PartDesign::Helix::handleChangedPropertyType(), TechDraw::DrawViewAnnotation::handleChangedPropertyType(), TechDrawGui::ViewProviderBalloon::handleChangedPropertyType(), TechDrawGui::ViewProviderDimension::handleChangedPropertyType(), TechDrawGui::ViewProviderLeader::handleChangedPropertyType(), TechDrawGui::ViewProviderRichAnno::handleChangedPropertyType(), TechDrawGui::ViewProviderViewPart::handleChangedPropertyType(), TechDraw::DrawProjGroup::handleChangedPropertyType(), TechDraw::DrawView::handleChangedPropertyType(), TechDraw::DrawViewBalloon::handleChangedPropertyType(), PartGui::ViewProviderPartExt::loadParameter(), PartDesignGui::TaskBoxPrimitives::onBoxHeightChanged(), PartDesignGui::TaskBoxPrimitives::onBoxLengthChanged(), PartDesignGui::TaskBoxPrimitives::onBoxWidthChanged(), PartDesign::Hole::onChanged(), TechDraw::DrawProjGroup::onChanged(), TechDraw::DrawViewDimension::onChanged(), PartDesignGui::TaskBoxPrimitives::onConeAngleChanged(), PartDesignGui::TaskBoxPrimitives::onConeHeightChanged(), PartDesignGui::TaskBoxPrimitives::onConeRadius1Changed(), PartDesignGui::TaskBoxPrimitives::onConeRadius2Changed(), PartDesignGui::TaskBoxPrimitives::onCylinderAngleChanged(), PartDesignGui::TaskBoxPrimitives::onCylinderHeightChanged(), PartDesignGui::TaskBoxPrimitives::onCylinderRadiusChanged(), PartDesignGui::TaskBoxPrimitives::onCylinderXSkewChanged(), PartDesignGui::TaskBoxPrimitives::onCylinderYSkewChanged(), PartDesignGui::TaskBoxPrimitives::onEllipsoidAngle1Changed(), PartDesignGui::TaskBoxPrimitives::onEllipsoidAngle2Changed(), PartDesignGui::TaskBoxPrimitives::onEllipsoidAngle3Changed(), PartDesignGui::TaskBoxPrimitives::onEllipsoidRadius1Changed(), PartDesignGui::TaskBoxPrimitives::onEllipsoidRadius2Changed(), PartDesignGui::TaskBoxPrimitives::onEllipsoidRadius3Changed(), PartDesignGui::TaskBoxPrimitives::onPrismCircumradiusChanged(), PartDesignGui::TaskBoxPrimitives::onPrismHeightChanged(), PartDesignGui::TaskBoxPrimitives::onPrismXSkewChanged(), PartDesignGui::TaskBoxPrimitives::onPrismYSkewChanged(), SketcherGui::TaskSketcherGeneral::onSetGridSize(), PartDesignGui::TaskBoxPrimitives::onSphereAngle1Changed(), PartDesignGui::TaskBoxPrimitives::onSphereAngle2Changed(), PartDesignGui::TaskBoxPrimitives::onSphereAngle3Changed(), PartDesignGui::TaskBoxPrimitives::onSphereRadiusChanged(), PartDesignGui::TaskBoxPrimitives::onTorusAngle1Changed(), PartDesignGui::TaskBoxPrimitives::onTorusAngle2Changed(), PartDesignGui::TaskBoxPrimitives::onTorusAngle3Changed(), PartDesignGui::TaskBoxPrimitives::onTorusRadius1Changed(), PartDesignGui::TaskBoxPrimitives::onTorusRadius2Changed(), PartDesignGui::TaskBoxPrimitives::onWedgeX2maxChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeX2minChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeXmaxChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeXminChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeYmaxChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeYminChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeZ2maxChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeZ2minChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeZmaxChanged(), PartDesignGui::TaskBoxPrimitives::onWedgeZminChanged(), TechDraw::DrawSVGTemplate::processTemplate(), PartDesign::Helix::proposeParameters(), Part::Box::Restore(), Part::Circle::Restore(), Part::Ellipse::Restore(), TechDrawGui::TaskProjGroup::restoreGroupState(), TechDrawGui::TaskLeaderLine::restoreState(), PartDesignGui::ViewProviderDatumPlane::setExtents(), TechDraw::DrawViewBalloon::setOrigin(), setPathValue(), TechDraw::DrawView::setPosition(), Spreadsheet::Sheet::setQuantityProperty(), TechDrawGui::TaskProjGroup::spacingChanged(), TechDrawGui::TaskRichAnno::updateAnnoFeature(), TechDrawGui::TaskLeaderLine::updateLeaderFeature(), and RobotGui::TaskTrajectoryDressUpParameter::writeValues().
The documentation for this class was generated from the following files:
FreeCAD/src/App/PropertyUnits.h
FreeCAD/src/App/PropertyUnits.cpp