FreeCAD: Gui::Dialog::Ui_DlgChooseIcon Class Reference
Gui::Dialog::Ui_DlgChooseIcon Class Reference
#include <ui_DlgChooseIcon.h>
Public Member Functions
void retranslateUi (QDialog *Gui__Dialog__DlgChooseIcon)
void setupUi (QDialog *Gui__Dialog__DlgChooseIcon)
Public Attributes
QPushButton * addButton
QDialogButtonBox * buttonBox
QGridLayout * gridLayout
QHBoxLayout * horizontalLayout
QListWidget * listWidget
QSpacerItem * spacerItem
Member Function Documentation
retranslateUi()
void Gui::Dialog::Ui_DlgChooseIcon::retranslateUi (QDialog * Gui__Dialog__DlgChooseIcon)
References addButton, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::Dialog::Ui_DlgChooseIcon::setupUi (QDialog * Gui__Dialog__DlgChooseIcon)
References addButton, buttonBox, draftgeoutils.intersections::connect(), gridLayout, horizontalLayout, listWidget, retranslateUi(), and spacerItem.
Referenced by Gui::Dialog::IconDialog::IconDialog().
Member Data Documentation
addButton
QPushButton* Gui::Dialog::Ui_DlgChooseIcon::addButton
Referenced by ArchComponent.ComponentTaskPanel::check(), Gui::Dialog::IconDialog::IconDialog(), retranslateUi(), ArchCommands.SurveyTaskPanel::retranslateUi(), ArchAxisSystem.AxisSystemTaskPanel::retranslateUi(), ArchComponent.ComponentTaskPanel::retranslateUi(), ArchSectionPlane.SectionPlaneTaskPanel::retranslateUi(), DraftGui.FacebinderTaskPanel::retranslateUi(), and setupUi().
buttonBox
QDialogButtonBox* Gui::Dialog::Ui_DlgChooseIcon::buttonBox
Referenced by PathScripts.PathGetPoint.TaskPanel::getPoint(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::modifyStandardButtons(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::pageDirtyChanged(), PathScripts.PathGetPoint.TaskPanel::pointFinish(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setClean(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setDirty(), and setupUi().
gridLayout
QGridLayout* Gui::Dialog::Ui_DlgChooseIcon::gridLayout
Referenced by setupUi().
horizontalLayout
QHBoxLayout* Gui::Dialog::Ui_DlgChooseIcon::horizontalLayout
Referenced by setupUi().
listWidget
QListWidget* Gui::Dialog::Ui_DlgChooseIcon::listWidget
Referenced by Gui::Dialog::IconDialog::currentItem(), Gui::Dialog::IconDialog::IconDialog(), Gui::Dialog::IconDialog::resizeEvent(), and setupUi().
spacerItem
QSpacerItem* Gui::Dialog::Ui_DlgChooseIcon::spacerItem
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_DlgChooseIcon.h