FreeCAD: InspectionGui::ViewProviderProxyObject Class Reference
InspectionGui::ViewProviderProxyObject Class Reference
Public Member Functions
void customEvent (QEvent *)
ViewProviderProxyObject (QWidget *w)
~ViewProviderProxyObject ()
Static Public Member Functions
static void addFlag (Gui::View3DInventorViewer *view, const QString &text, const SoPickedPoint *point)
Constructor & Destructor Documentation
ViewProviderProxyObject()
InspectionGui::ViewProviderProxyObject::ViewProviderProxyObject (QWidget * w)
~ViewProviderProxyObject()
InspectionGui::ViewProviderProxyObject::~ViewProviderProxyObject ()
Member Function Documentation
addFlag()
static void InspectionGui::ViewProviderProxyObject::addFlag (Gui::View3DInventorViewer * view, const QString & text, const SoPickedPoint * point) static
References Gui::GLFlagWindow::addFlag(), Gui::FlagLayout::BottomLeft, Base::BaseClass::getClassTypeId(), and Gui::Flag::setText().
Referenced by InspectionGui::ViewProviderInspection::inspectCallback().
customEvent()
void InspectionGui::ViewProviderProxyObject::customEvent (QEvent *)
References Gui::getMainWindow().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Inspection/Gui/ViewProviderInspection.cpp