FreeCAD: Gui::TaskView::Ui_TaskAppearance Class Reference
Gui::TaskView::Ui_TaskAppearance Class Reference
#include <ui_TaskAppearance.h>
Public Member Functions
void retranslateUi (QWidget *Gui__TaskView__TaskAppearance)
void setupUi (QWidget *Gui__TaskView__TaskAppearance)
Public Attributes
QComboBox * changeMode
QComboBox * changePlot
QHBoxLayout * hboxLayout
QHBoxLayout * hboxLayout1
QHBoxLayout * hboxLayout2
QHBoxLayout * hboxLayout3
QHBoxLayout * hboxLayout4
QSlider * horizontalSlider
QSpacerItem * spacerItem
QSpacerItem * spacerItem1
QSpinBox * spinLineWidth
QSpinBox * spinPointSize
QSpinBox * spinTransparency
QLabel * textLabel1
QLabel * textLabel1_2
QLabel * textLabel1_3
QLabel * textLabel2
QLabel * textLabel3
QVBoxLayout * vboxLayout
Member Function Documentation
retranslateUi()
void Gui::TaskView::Ui_TaskAppearance::retranslateUi (QWidget * Gui__TaskView__TaskAppearance)
References textLabel1, textLabel1_2, textLabel1_3, textLabel2, textLabel3, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), Gui::TaskView::TaskAppearance::changeEvent(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::TaskView::Ui_TaskAppearance::setupUi (QWidget * Gui__TaskView__TaskAppearance)
References changeMode, changePlot, draftgeoutils.intersections::connect(), hboxLayout, hboxLayout1, hboxLayout2, hboxLayout3, hboxLayout4, horizontalSlider, retranslateUi(), spacerItem, spacerItem1, spinLineWidth, spinPointSize, spinTransparency, textLabel1, textLabel1_2, textLabel1_3, textLabel2, textLabel3, and vboxLayout.
Referenced by Gui::TaskView::TaskAppearance::TaskAppearance().
Member Data Documentation
changeMode
QComboBox* Gui::TaskView::Ui_TaskAppearance::changeMode
Referenced by setupUi().
changePlot
QComboBox* Gui::TaskView::Ui_TaskAppearance::changePlot
Referenced by setupUi(), and Gui::TaskView::TaskAppearance::TaskAppearance().
hboxLayout
QHBoxLayout* Gui::TaskView::Ui_TaskAppearance::hboxLayout
Referenced by setupUi().
hboxLayout1
QHBoxLayout* Gui::TaskView::Ui_TaskAppearance::hboxLayout1
Referenced by setupUi().
hboxLayout2
QHBoxLayout* Gui::TaskView::Ui_TaskAppearance::hboxLayout2
Referenced by setupUi().
hboxLayout3
QHBoxLayout* Gui::TaskView::Ui_TaskAppearance::hboxLayout3
Referenced by setupUi().
hboxLayout4
QHBoxLayout* Gui::TaskView::Ui_TaskAppearance::hboxLayout4
Referenced by setupUi().
horizontalSlider
QSlider* Gui::TaskView::Ui_TaskAppearance::horizontalSlider
Referenced by setupUi().
spacerItem
QSpacerItem* Gui::TaskView::Ui_TaskAppearance::spacerItem
Referenced by setupUi().
spacerItem1
QSpacerItem* Gui::TaskView::Ui_TaskAppearance::spacerItem1
Referenced by setupUi().
spinLineWidth
QSpinBox* Gui::TaskView::Ui_TaskAppearance::spinLineWidth
Referenced by setupUi().
spinPointSize
QSpinBox* Gui::TaskView::Ui_TaskAppearance::spinPointSize
Referenced by setupUi().
spinTransparency
QSpinBox* Gui::TaskView::Ui_TaskAppearance::spinTransparency
Referenced by setupUi().
textLabel1
QLabel* Gui::TaskView::Ui_TaskAppearance::textLabel1
Referenced by retranslateUi(), and setupUi().
textLabel1_2
QLabel* Gui::TaskView::Ui_TaskAppearance::textLabel1_2
Referenced by retranslateUi(), and setupUi().
textLabel1_3
QLabel* Gui::TaskView::Ui_TaskAppearance::textLabel1_3
Referenced by retranslateUi(), setupUi(), and Gui::TaskView::TaskAppearance::TaskAppearance().
textLabel2
QLabel* Gui::TaskView::Ui_TaskAppearance::textLabel2
Referenced by retranslateUi(), and setupUi().
textLabel3
QLabel* Gui::TaskView::Ui_TaskAppearance::textLabel3
Referenced by retranslateUi(), and setupUi().
vboxLayout
QVBoxLayout* Gui::TaskView::Ui_TaskAppearance::vboxLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_TaskAppearance.h