FreeCAD: femviewprovider.view_constraint_electrostaticpotential.VPConstraintElectroStaticPotential Class Reference
femviewprovider.view_constraint_electrostaticpotential.VPConstraintElectroStaticPotential Class Reference
Public Member Functions
def setEdit (self, vobj, mode=0)
Public Member Functions inherited from femviewprovider.view_base_femconstraint.VPBaseFemConstraint
def attach (self, vobj)
def getDefaultDisplayMode (self)
def getDisplayModes (self, obj)
def setDisplayMode (self, mode)
Public Member Functions inherited from femviewprovider.view_base_femobject.VPBaseFemObject
def doubleClicked (self, vobj)
def getIcon (self)
def setEdit (self, vobj, mode=0, TaskPanel=None, hide_mesh=True)
def unsetEdit (self, vobj, mode=0)
Additional Inherited Members
Public Attributes inherited from femviewprovider.view_base_femconstraint.VPBaseFemConstraint
Object
Public Attributes inherited from femviewprovider.view_base_femobject.VPBaseFemObject
Object
Member Function Documentation
setEdit()
def femviewprovider.view_constraint_electrostaticpotential.VPConstraintElectroStaticPotential.setEdit (self, vobj, mode = 0)
Referenced by draftviewproviders.view_dimension.ViewProviderDimensionBase.doubleClicked(), PathScripts.PathSetupSheetGui.ViewProvider.doubleClicked(), PathScripts.PathToolBitGui.ViewProvider.doubleClicked(), Spreadsheet_legacy.ViewProviderSpreadsheet.doubleClicked(), ArchAxis.CommandArchGrid.IsActive(), ArchSchedule.CommandArchSchedule.IsActive(), PathScripts.PathIconViewProvider.ViewProvider.setupContextMenu(), PathScripts.PathJobGui.ViewProvider.setupContextMenu(), PathScripts.PathOpGui.ViewProvider.setupContextMenu(), and PathScripts.PathToolControllerGui.ViewProvider.setupContextMenu().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Fem/femviewprovider/view_constraint_electrostaticpotential.py