FreeCAD: Base::PyException Class Reference
Base::PyException Class Reference
#include <Interpreter.h>
Public Member Functions
const std::string & getErrorType () const
virtual PyObject * getPyExceptionType (void) const override
returns the corresponding python exception type
const std::string & getStackTrace () const
this function returns the stack trace
PyException ()
constructor does the whole job
PyException (const Py::Object &obj)
void raiseException ()
void ReportException () const override
Reports exception. It includes a mechanism to only report an exception once.
virtual void setPyException () const override
Sets the Python error indicator and an error message.
~PyException () throw ()
Public Member Functions inherited from Base::Exception
std::string getFile () const
std::string getFunction () const
int getLine () const
std::string getMessage () const
virtual PyObject * getPyExceptionType () const
returns the corresponding python exception type
virtual PyObject * getPyObject ()
returns a Python dictionary containing the exception data
bool getReported () const
bool getTranslatable () const
virtual Base::Type getTypeId (void) const
Exception & operator= (const Exception &inst)
virtual void ReportException () const
Reports exception. It includes a mechanism to only report an exception once.
void setDebugInformation (const std::string &file, const int line, const std::string &function)
setter methods for including debug information intended to use via macro for autofilling of debugging information
void setMessage (const char *sMessage)
void setMessage (const std::string &sMessage)
virtual void setPyException () const
Sets the Python error indicator and an error message.
virtual void setPyObject (PyObject *pydict)
returns sets the exception data from a Python dictionary
void setReported (bool reported)
void setTranslatable (bool translatable)
virtual const char * what () const throw ()
virtual ~Exception () throw ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static void ThrowException ()
this method determines if the original exception can be reconstructed or not, if yes throws the reconstructed version if not, throws a generic PyException.
Static Public Member Functions inherited from Base::Exception
static void * create (void)
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Additional Inherited Members
Protected Member Functions inherited from Base::Exception
Exception ()
Exception (const char *sMessage)
Exception (const Exception &inst)
Exception (const std::string &sMessage)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
PyException() [1/2]
PyException::PyException ()
constructor does the whole job
References Base::Exception::setPyObject().
PyException() [2/2]
PyException::PyException (const Py::Object & obj)
~PyException()
PyException::~PyException () throw ()
Member Function Documentation
getErrorType()
const std::string & Base::PyException::getErrorType () const
Referenced by setPyException().
getPyExceptionType()
virtual PyObject * Base::PyException::getPyExceptionType (void) const override virtual
returns the corresponding python exception type
Reimplemented from Base::Exception.
Referenced by setPyException().
getStackTrace()
const std::string & Base::PyException::getStackTrace () const
this function returns the stack trace
Referenced by setPyException().
raiseException()
void PyException::raiseException ()
References Base::ExceptionFactory::Instance(), Base::PyExc_FC_FreeCADAbort, and Base::ExceptionFactory::raiseException().
Referenced by ThrowException().
ReportException()
void PyException::ReportException () const override virtual
Reports exception. It includes a mechanism to only report an exception once.
Reimplemented from Base::Exception.
References Base::Console(), Base::ConsoleSingleton::Error(), and Base::Exception::what().
Referenced by Gui::GestureNavigationStyle::onRollGesture(), and ThrowException().
setPyException()
void PyException::setPyException () const override virtual
Sets the Python error indicator and an error message.
Reimplemented from Base::Exception.
References getErrorType(), getPyExceptionType(), getStackTrace(), and Base::Exception::what().
ThrowException()
void PyException::ThrowException () static
this method determines if the original exception can be reconstructed or not, if yes throws the reconstructed version if not, throws a generic PyException.
References raiseException(), and ReportException().
Referenced by App::ObjectIdentifier::Component::del(), Gui::ViewProviderPythonFeatureImp::dropObject(), Gui::ViewProviderPythonFeatureImp::dropObjectEx(), App::FeaturePythonImp::execute(), App::ObjectIdentifier::Component::get(), App::ObjectIdentifier::getPyValue(), App::ObjectIdentifier::getValue(), Base::InterpreterSingleton::runString(), Base::InterpreterSingleton::runStringWithKey(), App::ObjectIdentifier::Component::set(), and App::ObjectIdentifier::setValue().
The documentation for this class was generated from the following files:
FreeCAD/src/Base/Interpreter.h
FreeCAD/src/Base/Interpreter.cpp