FreeCAD: Gui::PrefPageUiProducer Class Reference
Gui::PrefPageUiProducer Class Reference
The PrefPageUiProducer class provides the ability to create preference pages dynamically from an external UI file.
#include <WidgetFactory.h>
Public Member Functions
PrefPageUiProducer (const char *filename, const char *group)
Register a special type of preference page to the WidgetFactoryInst.
virtual void * Produce () const
Creates an instance of the specified widget.
virtual ~PrefPageUiProducer ()
Public Member Functions inherited from Base::AbstractProducer
AbstractProducer ()
virtual void * Produce () const =0
overwritten by a concrete producer to produce the needed object
virtual ~AbstractProducer ()
Detailed Description
The PrefPageUiProducer class provides the ability to create preference pages dynamically from an external UI file.
Author
Werner Mayer
Constructor & Destructor Documentation
PrefPageUiProducer()
PrefPageUiProducer::PrefPageUiProducer (const char * filename, const char * group)
Register a special type of preference page to the WidgetFactoryInst.
References Gui::Dialog::DlgPreferencesImp::addPage(), Base::Factory::AddProducer(), and Gui::WidgetFactoryInst::instance().
~PrefPageUiProducer()
PrefPageUiProducer::~PrefPageUiProducer () virtual
Member Function Documentation
Produce()
void * PrefPageUiProducer::Produce () const virtual
Creates an instance of the specified widget.
Implements Base::AbstractProducer.
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/WidgetFactory.h
FreeCAD/src/Gui/WidgetFactory.cpp