FreeCAD: Inspection::InspectNominalFastMesh Class Reference
Inspection::InspectNominalFastMesh Class Reference
#include <InspectionFeature.h>
Public Member Functions
virtual float getDistance (const Base::Vector3f &) const
This algorithm is not that exact as that from InspectNominalMesh but is by factors faster and sufficient for many cases.
InspectNominalFastMesh (const Mesh::MeshObject &rMesh, float offset)
~InspectNominalFastMesh ()
Public Member Functions inherited from Inspection::InspectNominalGeometry
virtual float getDistance (const Base::Vector3f &) const =0
InspectNominalGeometry ()
virtual ~InspectNominalGeometry ()
Protected Attributes
unsigned long max_level
Constructor & Destructor Documentation
InspectNominalFastMesh()
InspectNominalFastMesh::InspectNominalFastMesh (const Mesh::MeshObject & rMesh, float offset)
References MeshCore::MeshAlgorithm::GetAverageEdgeLength(), MeshCore::MeshKernel::GetBoundBox(), Mesh::MeshObject::getKernel(), Mesh::MeshObject::getTransform(), max_level, and Base::BoundBox3< _Precision >::Transformed().
~InspectNominalFastMesh()
InspectNominalFastMesh::~InspectNominalFastMesh ()
Member Function Documentation
getDistance()
float InspectNominalFastMesh::getDistance (const Base::Vector3f & point) const virtual
This algorithm is not that exact as that from InspectNominalMesh but is by factors faster and sufficient for many cases.
Implements Inspection::InspectNominalGeometry.
References MeshCore::MeshGeomFacet::DistanceToPoint(), MeshCore::MeshGeomFacet::GetNormal(), max_level, and MeshCore::MeshGeomFacet::Transform().
Member Data Documentation
max_level
unsigned long Inspection::InspectNominalFastMesh::max_level protected
Referenced by getDistance(), and InspectNominalFastMesh().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Inspection/App/InspectionFeature.h
FreeCAD/src/Mod/Inspection/App/InspectionFeature.cpp