FreeCAD: PartDesignGui::TaskDlgScaledParameters Class Reference
PartDesignGui::TaskDlgScaledParameters Class Reference
simulation dialog for the TaskView
#include <TaskScaledParameters.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
TaskDlgScaledParameters (ViewProviderScaled *ScaledView)
virtual ~TaskDlgScaledParameters ()
Public Member Functions inherited from PartDesignGui::TaskDlgTransformedParameters
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
ViewProviderTransformed * getTransformedView () const
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgTransformedParameters (ViewProviderTransformed *TransformedView)
virtual ~TaskDlgTransformedParameters ()
Public Member Functions inherited from PartDesignGui::TaskDlgFeatureParameters
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgFeatureParameters (PartDesignGui::ViewProvider *vp)
PartDesignGui::ViewProvider * viewProvider () const
Returns the view provider dialog is runed for.
virtual ~TaskDlgFeatureParameters ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
tells the framework which buttons are wished for the dialog
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from PartDesignGui::TaskDlgTransformedParameters
TaskTransformedMessages * message
TaskTransformedParameters * parameter
Protected Attributes inherited from PartDesignGui::TaskDlgFeatureParameters
PartDesignGui::ViewProvider * vp
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
simulation dialog for the TaskView
Constructor & Destructor Documentation
TaskDlgScaledParameters()
TaskDlgScaledParameters::TaskDlgScaledParameters (ViewProviderScaled * ScaledView)
References Gui::TaskView::TaskDialog::Content, and PartDesignGui::TaskDlgTransformedParameters::parameter.
~TaskDlgScaledParameters()
virtual PartDesignGui::TaskDlgScaledParameters::~TaskDlgScaledParameters () virtual
Member Function Documentation
accept()
bool TaskDlgScaledParameters::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from PartDesignGui::TaskDlgTransformedParameters.
References PartDesignGui::TaskDlgTransformedParameters::accept(), PartDesignGui::TaskTransformedParameters::apply(), and PartDesignGui::TaskDlgTransformedParameters::parameter.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/PartDesign/Gui/TaskScaledParameters.h
FreeCAD/src/Mod/PartDesign/Gui/TaskScaledParameters.cpp