FreeCAD: SMESH_TNodeXYZ Struct Reference
SMESH_TNodeXYZ Struct Reference
SMDS_MeshNode -> gp_XYZ convertor.
#include <SMESH_TypeDefs.hxx>
Public Member Functions
double Distance (const SMDS_MeshNode *n) const
bool operator== (const SMESH_TNodeXYZ &other) const
bool Set (const SMDS_MeshElement *e=0)
SMESH_TNodeXYZ (const SMDS_MeshElement *e=0)
double SquareDistance (const SMDS_MeshNode *n) const
Detailed Description
SMDS_MeshNode -> gp_XYZ convertor.
Constructor & Destructor Documentation
SMESH_TNodeXYZ()
SMESH_TNodeXYZ::SMESH_TNodeXYZ (const SMDS_MeshElement * e = 0)
References Set().
Referenced by Distance(), and SquareDistance().
Member Function Documentation
Distance()
double SMESH_TNodeXYZ::Distance (const SMDS_MeshNode * n) const
References SMESH_TNodeXYZ().
Referenced by NETGENPlugin_Mesher::AddSegmentsToMesh(), SMESH_2D_Algo::FixInternalNodes(), SMESH_ElementSearcherImpl::getTolerance(), and VISCOUS_3D::_LayerEdge::SmoothOnEdge().
operator==()
bool SMESH_TNodeXYZ::operator== (const SMESH_TNodeXYZ & other) const
Set()
bool SMESH_TNodeXYZ::Set (const SMDS_MeshElement * e = 0)
References SMDS_MeshNode::GetXYZ().
Referenced by NETGENPlugin_Mesher::FillNgMesh(), and SMESH_TNodeXYZ().
SquareDistance()
double SMESH_TNodeXYZ::SquareDistance (const SMDS_MeshNode * n) const
References SMESH_TNodeXYZ().
Referenced by StdMeshers_Adaptive1D::SetParametersByMesh().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_TypeDefs.hxx