FreeCAD: Ui_TaskFemConstraintFixed Class Reference
Ui_TaskFemConstraintFixed Class Reference
#include <ui_TaskFemConstraintFixed.h>
Public Member Functions
void retranslateUi (QWidget *TaskFemConstraintFixed)
void setupUi (QWidget *TaskFemConstraintFixed)
Public Attributes
QToolButton * btnAdd
QToolButton * btnRemove
QHBoxLayout * hLayout1
QLabel * lbl_info
QListWidget * lw_references
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void Ui_TaskFemConstraintFixed::retranslateUi (QWidget * TaskFemConstraintFixed)
References btnAdd, btnRemove, lbl_info, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Ui_TaskFemConstraintFixed::setupUi (QWidget * TaskFemConstraintFixed)
References btnAdd, btnRemove, hLayout1, lbl_info, lw_references, retranslateUi(), and verticalLayout.
Referenced by FemGui::TaskFemConstraintFixed::TaskFemConstraintFixed().
Member Data Documentation
btnAdd
QToolButton* Ui_TaskFemConstraintFixed::btnAdd
Referenced by FemGui::TaskFemConstraintFixed::clearButtons(), retranslateUi(), setupUi(), and FemGui::TaskFemConstraintFixed::TaskFemConstraintFixed().
btnRemove
QToolButton* Ui_TaskFemConstraintFixed::btnRemove
Referenced by FemGui::TaskFemConstraintFixed::clearButtons(), retranslateUi(), setupUi(), and FemGui::TaskFemConstraintFixed::TaskFemConstraintFixed().
hLayout1
QHBoxLayout* Ui_TaskFemConstraintFixed::hLayout1
Referenced by setupUi().
lbl_info
QLabel* Ui_TaskFemConstraintFixed::lbl_info
Referenced by retranslateUi(), and setupUi().
lw_references
QListWidget* Ui_TaskFemConstraintFixed::lw_references
Referenced by FemGui::TaskFemConstraintFixed::getReferences(), setupUi(), and FemGui::TaskFemConstraintFixed::TaskFemConstraintFixed().
verticalLayout
QVBoxLayout* Ui_TaskFemConstraintFixed::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Fem/Gui/ui_TaskFemConstraintFixed.h