FreeCAD: Gui::MDITabbar Class Reference
Gui::MDITabbar Class Reference
Public Member Functions
MDITabbar (QWidget *parent=nullptr)
~MDITabbar ()
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *e)
Constructor & Destructor Documentation
MDITabbar()
Gui::MDITabbar::MDITabbar (QWidget * parent = nullptr)
~MDITabbar()
Gui::MDITabbar::~MDITabbar ()
Member Function Documentation
contextMenuEvent()
void Gui::MDITabbar::contextMenuEvent (QContextMenuEvent * e) protected
References Gui::Command::addTo(), Gui::Application::commandManager(), Gui::CommandManager::getCommandByName(), and Gui::Application::Instance.
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/MainWindow.cpp