FreeCAD: App::PropertyVectorList Class Reference
App::PropertyVectorList Class Reference
#include <PropertyGeo.h>
Public Member Functions
virtual Property * Copy (void) const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
const char * getEditorName (void) const override
Get the class name of the associated property editor item.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
virtual void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
PropertyVectorList ()
A constructor.
virtual void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Base::Reader &reader) override
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
virtual void SaveDocFile (Base::Writer &writer) const override
This method is used to save large amounts of data to a binary file.
void setValue (double x, double y, double z)
virtual ~PropertyVectorList ()
A destructor.
Public Member Functions inherited from App::PropertyListsT< Base::Vector3d >
virtual int getSize (void) const override
const std::vector< Base::Vector3d > & getValue (void) const
const std::vector< Base::Vector3d > & getValues (void) const
virtual bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
const_reference operator[] (int idx) const
virtual void set1Value (int index, const_reference value)
virtual void setPyObject (PyObject *value) override
virtual void setSize (int newSize) override
virtual void setSize (int newSize, const_reference def)
void setValue (const std::vector< Base::Vector3d > &newValues=std::vector< Base::Vector3d >())
void setValue (const_reference value)
virtual void setValues (const std::vector< Base::Vector3d > &newValues=std::vector< Base::Vector3d >())
Public Member Functions inherited from App::PropertyLists
bool isOrderRelevant () const
void setOrderRelevant (bool on)
virtual void setPyObject (PyObject *obj) override
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual Property * Copy (void) const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
int64_t getID () const
Return a unique ID for the property.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const char * getName (void) const
Get the name of this property in the belonging container With hasName() it can be checked beforehand if a valid name is set.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
bool hasName () const
Check if the property has a name set.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::PropertyListsBase
void clearTouchList ()
virtual int getSize (void) const =0
const std::set< int > & getTouchList () const
virtual void setSize (int newSize)=0
Protected Member Functions
Base::Vector3d getPyValue (PyObject *) const override
Protected Member Functions inherited from App::PropertyListsT< Base::Vector3d >
virtual Base::Vector3d getPyValue (PyObject *item) const=0
void setPyValues (const std::vector< PyObject * > &vals, const std::vector< int > &indices) override
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
virtual void setPyValues (const std::vector< PyObject * > &vals, const std::vector< int > &indices)
Protected Member Functions inherited from App::AtomicPropertyChangeInterface< PropertyListsT< Base::Vector3d, std::vector< Base::Vector3d >, PropertyLists > >
AtomicPropertyChangeInterface ()
Additional Inherited Members
Public Types inherited from App::PropertyListsT< Base::Vector3d >
typedef AtomicPropertyChangeInterface< PropertyListsT< Base::Vector3d, std::vector< Base::Vector3d >, PropertyLists > >::AtomicPropertyChange atomic_change
typedef ListT::const_reference const_reference
typedef std::vector< Base::Vector3d > list_type
typedef PropertyLists parent_type
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , Busy = 15 ,
CopyOnChange = 16 , UserEdit = 17 , PropStaticBegin = 21 , PropDynamic = 21 ,
PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 , PropTransient = 25 ,
PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 , User1 = 28 ,
User2 = 29 , User3 = 30 , User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Check if the passed name is valid.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Public Attributes inherited from App::PropertyListsT< Base::Vector3d >
friend atomic_change
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Protected Attributes inherited from App::AtomicPropertyChangeInterface< PropertyListsT< Base::Vector3d, std::vector< Base::Vector3d >, PropertyLists > >
bool hasChanged
int signalCounter
Counter for invoking transaction start/stop.
Constructor & Destructor Documentation
PropertyVectorList()
PropertyVectorList::PropertyVectorList ()
A constructor.
A more elaborate description of the constructor.
Referenced by Copy().
~PropertyVectorList()
PropertyVectorList::~PropertyVectorList () virtual
A destructor.
A more elaborate description of the destructor.
Member Function Documentation
Copy()
Property * PropertyVectorList::Copy (void) const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References PropertyVectorList().
getEditorName()
const char * App::PropertyVectorList::getEditorName (void) const override virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
getMemSize()
unsigned int PropertyVectorList::getMemSize (void) const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
See also
Base::Persistence
Reimplemented from App::Property.
getPyObject()
PyObject * PropertyVectorList::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
References App::PropertyListsT< Base::Vector3d >::getSize().
getPyValue()
Base::Vector3d PropertyVectorList::getPyValue (PyObject * item) const override protected virtual
Implements App::PropertyListsT< Base::Vector3d >.
References App::PropertyVector::setPyObject().
Paste()
void PropertyVectorList::Paste (const Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References App::PropertyListsT< Base::Vector3d >::setValues().
Restore()
void PropertyVectorList::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References Base::XMLReader::addFile(), Base::XMLReader::getAttribute(), and Base::XMLReader::readElement().
RestoreDocFile()
void PropertyVectorList::RestoreDocFile (Base::Reader &) override virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Base::Persistence.
References App::Property::isSinglePrecision(), and App::PropertyListsT< Base::Vector3d >::setValues().
Save()
void PropertyVectorList::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References Base::Writer::addFile(), App::Property::getName(), Base::Writer::ind(), Base::Writer::isForceXML(), and Base::Writer::Stream().
SaveDocFile()
void PropertyVectorList::SaveDocFile (Base::Writer &) const override virtual
This method is used to save large amounts of data to a binary file.
Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) << "\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
void PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Base::Persistence.
References App::PropertyListsT< Base::Vector3d >::getSize(), App::Property::isSinglePrecision(), and Base::Writer::Stream().
setValue()
void PropertyVectorList::setValue (double x, double y, double z)
References setValue().
Referenced by setValue().
The documentation for this class was generated from the following files:
FreeCAD/src/App/PropertyGeo.h
FreeCAD/src/App/PropertyGeo.cpp