FreeCAD: FemGui::DlgSettingsFemInOutVtkImp Class Reference
FemGui::DlgSettingsFemInOutVtkImp Class Reference
#include <DlgSettingsFemInOutVtkImp.h>
Public Member Functions
DlgSettingsFemInOutVtkImp (QWidget *parent=nullptr)
~DlgSettingsFemInOutVtkImp ()
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void loadSettings ()
void saveSettings ()
virtual void changeEvent (QEvent *e)=0
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Constructor & Destructor Documentation
DlgSettingsFemInOutVtkImp()
DlgSettingsFemInOutVtkImp::DlgSettingsFemInOutVtkImp (QWidget * parent = nullptr)
References FemGui::Ui_DlgSettingsFemInOutVtk::setupUi().
~DlgSettingsFemInOutVtkImp()
DlgSettingsFemInOutVtkImp::~DlgSettingsFemInOutVtkImp ()
Member Function Documentation
changeEvent()
void DlgSettingsFemInOutVtkImp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
References FemGui::Ui_DlgSettingsFemInOutVtk::comboBoxVtkImportObject, and FemGui::Ui_DlgSettingsFemInOutVtk::retranslateUi().
loadSettings()
void DlgSettingsFemInOutVtkImp::loadSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References FemGui::Ui_DlgSettingsFemInOutVtk::comboBoxVtkImportObject, App::GetApplication(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), and Gui::PrefWidget::onRestore().
saveSettings()
void DlgSettingsFemInOutVtkImp::saveSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References FemGui::Ui_DlgSettingsFemInOutVtk::comboBoxVtkImportObject, App::GetApplication(), App::Application::GetParameterGroupByPath(), Gui::PrefWidget::onSave(), and ParameterGrp::SetInt().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/DlgSettingsFemInOutVtkImp.h
FreeCAD/src/Mod/Fem/Gui/DlgSettingsFemInOutVtkImp.cpp