FreeCAD: App::DocumentObjectWeakPtrT Class Reference
App::DocumentObjectWeakPtrT Class Reference
The DocumentObjectWeakPtrT class.
#include <DocumentObserver.h>
Classes
class Private
Public Member Functions
DocumentObjectWeakPtrT (App::DocumentObject *)
bool expired () const noexcept
expired
template<typename T >
T * get () const noexcept
bool operator!= (const DocumentObjectWeakPtrT &p) const noexcept
operator !=
App::DocumentObject * operator* () const noexcept
operator *
App::DocumentObject * operator-> () const noexcept
operator ->
DocumentObjectWeakPtrT & operator= (App::DocumentObject *p)
operator = Assignment operator
bool operator== (const DocumentObjectWeakPtrT &p) const noexcept
operator ==
void reset ()
reset Releases the reference to the managed object. After the call *this manages no object.
~DocumentObjectWeakPtrT ()
Detailed Description
The DocumentObjectWeakPtrT class.
Constructor & Destructor Documentation
DocumentObjectWeakPtrT()
DocumentObjectWeakPtrT::DocumentObjectWeakPtrT (App::DocumentObject * obj)
~DocumentObjectWeakPtrT()
DocumentObjectWeakPtrT::~DocumentObjectWeakPtrT ()
Member Function Documentation
expired()
bool DocumentObjectWeakPtrT::expired () const noexcept
expired
Returns
true if the managed object has already been deleted, false otherwise.
Referenced by ReverseEngineeringGui::Segmentation::accept(), PartGui::DlgPrimitives::accept(), PartGui::DlgPrimitives::reject(), PartDesignGui::TaskDlgFeatureParameters::reject(), and PartDesignGui::TaskDlgSketchBasedParameters::reject().
get()
template<typename T > T * App::DocumentObjectWeakPtrT::get () const noexcept
Get a pointer to the object or 0 if it doesn't exist any more or the type doesn't match.
Referenced by ReverseEngineeringGui::Segmentation::accept(), FemGui::TaskPostBox::getTypedObject(), and draftguitools.gui_trackers.editTracker::move().
operator!=()
bool DocumentObjectWeakPtrT::operator!= (const DocumentObjectWeakPtrT & p) const noexcept
operator !=
Returns
true if both objects are inequal, false otherwise
operator*()
App::DocumentObject * DocumentObjectWeakPtrT::operator* () const noexcept
operator *
Returns
pointer to the document object
operator->()
App::DocumentObject * DocumentObjectWeakPtrT::operator-> () const noexcept
operator ->
Returns
pointer to the document object
operator=()
DocumentObjectWeakPtrT & DocumentObjectWeakPtrT::operator= (App::DocumentObject * p)
operator = Assignment operator
operator==()
bool DocumentObjectWeakPtrT::operator== (const DocumentObjectWeakPtrT & p) const noexcept
operator ==
Returns
true if both objects are equal, false otherwise
reset()
void DocumentObjectWeakPtrT::reset ()
reset Releases the reference to the managed object. After the call *this manages no object.
Referenced by draftguitools.gui_trackers.gridTracker::set().
The documentation for this class was generated from the following files:
FreeCAD/src/App/DocumentObserver.h
FreeCAD/src/App/DocumentObserver.cpp