FreeCAD: MeshCore::MeshEvalFoldsOnSurface Class Reference
MeshCore::MeshEvalFoldsOnSurface Class Reference
If the angle between the adjacent triangles of a triangle is lower then 90 deg but the angles between both of these adjacent triangles is higher than 90 deg we have a fold.
#include <Degeneration.h>
Public Member Functions
bool Evaluate ()
Evaluates the mesh kernel with respect to certain criteria.
std::vector< unsigned long > GetIndices () const
MeshEvalFoldsOnSurface (const MeshKernel &rclM)
~MeshEvalFoldsOnSurface ()
Public Member Functions inherited from MeshCore::MeshEvaluation
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()
Detailed Description
If the angle between the adjacent triangles of a triangle is lower then 90 deg but the angles between both of these adjacent triangles is higher than 90 deg we have a fold.
The topology is not affected but the geometry is broken.
Constructor & Destructor Documentation
MeshEvalFoldsOnSurface()
MeshCore::MeshEvalFoldsOnSurface::MeshEvalFoldsOnSurface (const MeshKernel & rclM)
~MeshEvalFoldsOnSurface()
MeshCore::MeshEvalFoldsOnSurface::~MeshEvalFoldsOnSurface ()
Member Function Documentation
Evaluate()
bool MeshEvalFoldsOnSurface::Evaluate () virtual
Evaluates the mesh kernel with respect to certain criteria.
Must be reimplemented by every subclass. This pure virtual function returns false if the mesh kernel is invalid according to this criterion and true if the mesh kernel is correct.
Implements MeshCore::MeshEvaluation.
Referenced by MeshGui::DlgEvaluateMeshImp::on_analyzeFoldsButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairAllTogether_clicked(), and Mesh::MeshObject::removeFoldsOnSurface().
GetIndices()
std::vector< unsigned long > MeshEvalFoldsOnSurface::GetIndices () const
Referenced by MeshGui::DlgEvaluateMeshImp::on_analyzeFoldsButton_clicked(), and Mesh::MeshObject::removeFoldsOnSurface().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Degeneration.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Degeneration.cpp