FreeCAD: Gui::WorkbenchGroup Class Reference
Gui::WorkbenchGroup Class Reference
The WorkbenchGroup class represents a list of workbenches.
#include <Action.h>
Public Member Functions
void addTo (QWidget *w)
Adds this action to widget w.
void refreshWorkbenchList ()
void slotActivateWorkbench (const char *)
void slotAddWorkbench (const char *)
void slotRemoveWorkbench (const char *)
WorkbenchGroup (Command *pcCmd, QObject *parent)
Creates an action for the command pcCmd to load the workbench name when it gets activated.
virtual ~WorkbenchGroup ()
Public Member Functions inherited from Gui::ActionGroup
ActionGroup (Command *pcCmd, QObject *parent=0)
Constructs an action called name with parent parent.
QList< QAction * > actions () const
QAction * addAction (const QString &)
QAction * addAction (QAction *)
int checkedAction () const
bool isExclusive () const
void setCheckedAction (int)
void setDisabled (bool)
void setDropDownMenu (bool b)
void setEnabled (bool)
Sets whether the action is enabled.
void setExclusive (bool)
void setVisible (bool)
virtual ~ActionGroup ()
Public Member Functions inherited from Gui::Action
QAction * action () const
Action (Command *pcCmd, QAction *action, QObject *parent)
Action takes ownership of the 'action' object.
Action (Command *pcCmd, QObject *parent=0)
Constructs an action called name with parent parent.
QIcon icon () const
bool isChecked () const
void setCheckable (bool)
void setChecked (bool, bool no_signal=false)
void setIcon (const QIcon &)
void setMenuRole (QAction::MenuRole menuRole)
void setShortcut (const QString &)
void setStatusTip (const QString &)
void setText (const QString &)
void setToolTip (const QString &)
void setWhatsThis (const QString &)
QKeySequence shortcut () const
QString statusTip () const
QString text () const
QString toolTip () const
QString whatsThis () const
virtual ~Action ()
Protected Member Functions
void customEvent (QEvent *e)
Additional Inherited Members
Public Slots inherited from Gui::ActionGroup
void onActivated ()
Activates the command.
void onActivated (QAction *)
Activates the command.
void onHovered (QAction *)
void onToggled (bool)
Public Slots inherited from Gui::Action
virtual void onActivated ()
Activates the command.
virtual void onToggled (bool)
Sets whether the command is toggled.
Detailed Description
The WorkbenchGroup class represents a list of workbenches.
When it is added to a menu a submenu gets created, if added to a toolbar a combo box gets created.
Author
Werner Mayer
Constructor & Destructor Documentation
WorkbenchGroup()
WorkbenchGroup::WorkbenchGroup (Command * pcCmd, QObject * parent)
Creates an action for the command pcCmd to load the workbench name when it gets activated.
References Gui::Action::action(), draftgeoutils.faces::bind(), Gui::Application::Instance, Gui::Application::signalActivateWorkbench, Gui::Application::signalAddWorkbench, Gui::Application::signalRemoveWorkbench, slotActivateWorkbench(), slotAddWorkbench(), and slotRemoveWorkbench().
~WorkbenchGroup()
WorkbenchGroup::~WorkbenchGroup () virtual
Member Function Documentation
addTo()
void WorkbenchGroup::addTo (QWidget * w) virtual
Adds this action to widget w.
Reimplemented from Gui::ActionGroup.
References draftgeoutils.intersections::connect(), Gui::ActionGroup::onActivated(), and refreshWorkbenchList().
Referenced by Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium().
customEvent()
void WorkbenchGroup::customEvent (QEvent * e) protected
References Gui::WorkbenchActionEvent::action().
refreshWorkbenchList()
void WorkbenchGroup::refreshWorkbenchList ()
References Gui::Application::Instance, and Gui::Application::workbenches().
Referenced by addTo().
slotActivateWorkbench()
void WorkbenchGroup::slotActivateWorkbench (const char *)
Referenced by WorkbenchGroup().
slotAddWorkbench()
void WorkbenchGroup::slotAddWorkbench (const char * name)
References Gui::Application::Instance, Gui::Application::workbenchIcon(), Gui::Application::workbenchMenuText(), and Gui::Application::workbenchToolTip().
Referenced by WorkbenchGroup().
slotRemoveWorkbench()
void WorkbenchGroup::slotRemoveWorkbench (const char * name)
Referenced by WorkbenchGroup().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Action.h
Sources/FreeCAD/src/Gui/Action.cpp