FreeCAD: Sketcher::SketchObjectPy Class Reference
Sketcher::SketchObjectPy Class Reference
The python export class for SketchObject.
#include <SketchObjectPy.h>
Public Types
typedef SketchObject * PointerType
Public Types inherited from Part::Part2DObjectPy
typedef Part2DObject * PointerType
Public Types inherited from Part::PartFeaturePy
typedef Feature * PointerType
Public Types inherited from App::GeoFeaturePy
typedef GeoFeature * PointerType
Public Types inherited from App::DocumentObjectPy
typedef DocumentObject * PointerType
Public Types inherited from App::ExtensionContainerPy
typedef ExtensionContainer * PointerType
Public Types inherited from App::PropertyContainerPy
typedef PropertyContainer * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
SketchObjectPy (SketchObject *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Part::Part2DObjectPy
Part2DObjectPy (Part2DObject *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Part2DObject * getPart2DObjectPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Part::PartFeaturePy
PartFeaturePy (Feature *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Feature * getFeaturePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from App::GeoFeaturePy
GeoFeaturePy (GeoFeature *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeoFeature * getGeoFeaturePtr (void) const
getter for the object handled by this class
PyObject * getPaths (PyObject *args)
implementer for the getPaths() method
PyObject * getGlobalPlacement (PyObject *args)
implementer for the getGlobalPlacement() method
PyObject * getPropertyNameOfGeometry (PyObject *args)
implementer for the getPropertyNameOfGeometry() method
PyObject * getPropertyOfGeometry (PyObject *args)
implementer for the getPropertyOfGeometry() method
Public Member Functions inherited from App::DocumentObjectPy
DocumentObjectPy (DocumentObject *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * addProperty (PyObject *args)
implementer for the addProperty() method
PyObject * removeProperty (PyObject *args)
implementer for the removeProperty() method
PyObject * supportedProperties (PyObject *args)
implementer for the supportedProperties() method
PyObject * touch (PyObject *args)
implementer for the touch() method
PyObject * purgeTouched (PyObject *args)
implementer for the purgeTouched() method
PyObject * enforceRecompute (PyObject *args)
implementer for the enforceRecompute() method
PyObject * setExpression (PyObject *args)
implementer for the setExpression() method
PyObject * evalExpression (PyObject *args)
implementer for the evalExpression() method
PyObject * recompute (PyObject *args)
implementer for the recompute() method
PyObject * getStatusString (PyObject *args)
implementer for the getStatusString() method
PyObject * isValid (PyObject *args)
implementer for the isValid() method
PyObject * getSubObject (PyObject *args, PyObject *kwd)
implementer for the getSubObject() method
PyObject * getSubObjectList (PyObject *args)
implementer for the getSubObjectList() method
PyObject * getSubObjects (PyObject *args)
implementer for the getSubObjects() method
PyObject * getLinkedObject (PyObject *args, PyObject *kwd)
implementer for the getLinkedObject() method
PyObject * setElementVisible (PyObject *args)
implementer for the setElementVisible() method
PyObject * isElementVisible (PyObject *args)
implementer for the isElementVisible() method
PyObject * hasChildElement (PyObject *args)
implementer for the hasChildElement() method
PyObject * getParentGroup (PyObject *args)
implementer for the getParentGroup() method
PyObject * getParentGeoFeatureGroup (PyObject *args)
implementer for the getParentGeoFeatureGroup() method
PyObject * getPathsByOutList (PyObject *args)
implementer for the getPathsByOutList() method
PyObject * resolve (PyObject *args)
implementer for the resolve() method
PyObject * resolveSubElement (PyObject *args)
implementer for the resolveSubElement() method
PyObject * adjustRelativeLinks (PyObject *args)
implementer for the adjustRelativeLinks() method
Py::List getOutList (void) const
getter for the OutList attribute
Py::List getOutListRecursive (void) const
getter for the OutListRecursive attribute
Py::List getInList (void) const
getter for the InList attribute
Py::List getInListRecursive (void) const
getter for the InListRecursive attribute
Py::String getFullName (void) const
getter for the FullName attribute
Py::String getName (void) const
getter for the Name attribute
Py::Object getDocument (void) const
getter for the Document attribute
Py::List getState (void) const
getter for the State attribute
Py::Object getViewObject (void) const
getter for the ViewObject attribute
Py::Boolean getMustExecute (void) const
getter for the MustExecute attribute
Py::Int getID (void) const
getter for the ID attribute
Py::Boolean getRemoving (void) const
getter for the Removing attribute
Py::List getParents (void) const
getter for the Parents attribute
Py::String getOldLabel (void) const
getter for the OldLabel attribute
Py::Boolean getNoTouch (void) const
getter for the NoTouch attribute
void setNoTouch (Py::Boolean arg)
setter for the NoTouch attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
DocumentObject * getDocumentObjectPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from App::ExtensionContainerPy
ExtensionContainerPy (ExtensionContainer *pcObject, PyTypeObject *T=&Type)
int finalization ()
int initialization ()
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ExtensionContainer * getExtensionContainerPtr (void) const
getter for the object handled by this class
PyObject * addExtension (PyObject *args)
implementer for the addExtension() method
PyObject * hasExtension (PyObject *args)
implementer for the hasExtension() method
Public Member Functions inherited from App::PropertyContainerPy
PropertyContainerPy (PropertyContainer *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getPropertyByName (PyObject *args)
implementer for the getPropertyByName() method
PyObject * getPropertyTouchList (PyObject *args)
implementer for the getPropertyTouchList() method
PyObject * getTypeOfProperty (PyObject *args)
implementer for the getTypeOfProperty() method
PyObject * getTypeIdOfProperty (PyObject *args)
implementer for the getTypeIdOfProperty() method
PyObject * setEditorMode (PyObject *args)
implementer for the setEditorMode() method
PyObject * getEditorMode (PyObject *args)
implementer for the getEditorMode() method
PyObject * getGroupOfProperty (PyObject *args)
implementer for the getGroupOfProperty() method
PyObject * setPropertyStatus (PyObject *args)
implementer for the setPropertyStatus() method
PyObject * getPropertyStatus (PyObject *args)
implementer for the getPropertyStatus() method
PyObject * getDocumentationOfProperty (PyObject *args)
implementer for the getDocumentationOfProperty() method
PyObject * dumpPropertyContent (PyObject *args, PyObject *kwd)
implementer for the dumpPropertyContent() method
PyObject * restorePropertyContent (PyObject *args)
implementer for the restorePropertyContent() method
Py::List getPropertiesList (void) const
getter for the PropertiesList attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
PropertyContainer * getPropertyContainerPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::Part2DObjectPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::PartFeaturePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::GeoFeaturePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_getPaths (PyObject *self, PyObject *args)
callback for the getPaths() method
static PyObject * staticCallback_getGlobalPlacement (PyObject *self, PyObject *args)
callback for the getGlobalPlacement() method
static PyObject * staticCallback_getPropertyNameOfGeometry (PyObject *self, PyObject *args)
callback for the getPropertyNameOfGeometry() method
static PyObject * staticCallback_getPropertyOfGeometry (PyObject *self, PyObject *args)
callback for the getPropertyOfGeometry() method
Static Public Member Functions inherited from App::DocumentObjectPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_addProperty (PyObject *self, PyObject *args)
callback for the addProperty() method
static PyObject * staticCallback_removeProperty (PyObject *self, PyObject *args)
callback for the removeProperty() method
static PyObject * staticCallback_supportedProperties (PyObject *self, PyObject *args)
callback for the supportedProperties() method
static PyObject * staticCallback_touch (PyObject *self, PyObject *args)
callback for the touch() method
static PyObject * staticCallback_purgeTouched (PyObject *self, PyObject *args)
callback for the purgeTouched() method
static PyObject * staticCallback_enforceRecompute (PyObject *self, PyObject *args)
callback for the enforceRecompute() method
static PyObject * staticCallback_setExpression (PyObject *self, PyObject *args)
callback for the setExpression() method
static PyObject * staticCallback_evalExpression (PyObject *self, PyObject *args)
callback for the evalExpression() method
static PyObject * staticCallback_recompute (PyObject *self, PyObject *args)
callback for the recompute() method
static PyObject * staticCallback_getStatusString (PyObject *self, PyObject *args)
callback for the getStatusString() method
static PyObject * staticCallback_isValid (PyObject *self, PyObject *args)
callback for the isValid() method
static PyObject * staticCallback_getSubObject (PyObject *self, PyObject *args, PyObject *kwd)
callback for the getSubObject() method
static PyObject * staticCallback_getSubObjectList (PyObject *self, PyObject *args)
callback for the getSubObjectList() method
static PyObject * staticCallback_getSubObjects (PyObject *self, PyObject *args)
callback for the getSubObjects() method
static PyObject * staticCallback_getLinkedObject (PyObject *self, PyObject *args, PyObject *kwd)
callback for the getLinkedObject() method
static PyObject * staticCallback_setElementVisible (PyObject *self, PyObject *args)
callback for the setElementVisible() method
static PyObject * staticCallback_isElementVisible (PyObject *self, PyObject *args)
callback for the isElementVisible() method
static PyObject * staticCallback_hasChildElement (PyObject *self, PyObject *args)
callback for the hasChildElement() method
static PyObject * staticCallback_getParentGroup (PyObject *self, PyObject *args)
callback for the getParentGroup() method
static PyObject * staticCallback_getParentGeoFeatureGroup (PyObject *self, PyObject *args)
callback for the getParentGeoFeatureGroup() method
static PyObject * staticCallback_getPathsByOutList (PyObject *self, PyObject *args)
callback for the getPathsByOutList() method
static PyObject * staticCallback_resolve (PyObject *self, PyObject *args)
callback for the resolve() method
static PyObject * staticCallback_resolveSubElement (PyObject *self, PyObject *args)
callback for the resolveSubElement() method
static PyObject * staticCallback_adjustRelativeLinks (PyObject *self, PyObject *args)
callback for the adjustRelativeLinks() method
static PyObject * staticCallback_getOutList (PyObject *self, void *closure)
getter callback for the OutList attribute
static int staticCallback_setOutList (PyObject *self, PyObject *value, void *closure)
setter callback for the OutList attribute
static PyObject * staticCallback_getOutListRecursive (PyObject *self, void *closure)
getter callback for the OutListRecursive attribute
static int staticCallback_setOutListRecursive (PyObject *self, PyObject *value, void *closure)
setter callback for the OutListRecursive attribute
static PyObject * staticCallback_getInList (PyObject *self, void *closure)
getter callback for the InList attribute
static int staticCallback_setInList (PyObject *self, PyObject *value, void *closure)
setter callback for the InList attribute
static PyObject * staticCallback_getInListRecursive (PyObject *self, void *closure)
getter callback for the InListRecursive attribute
static int staticCallback_setInListRecursive (PyObject *self, PyObject *value, void *closure)
setter callback for the InListRecursive attribute
static PyObject * staticCallback_getFullName (PyObject *self, void *closure)
getter callback for the FullName attribute
static int staticCallback_setFullName (PyObject *self, PyObject *value, void *closure)
setter callback for the FullName attribute
static PyObject * staticCallback_getName (PyObject *self, void *closure)
getter callback for the Name attribute
static int staticCallback_setName (PyObject *self, PyObject *value, void *closure)
setter callback for the Name attribute
static PyObject * staticCallback_getDocument (PyObject *self, void *closure)
getter callback for the Document attribute
static int staticCallback_setDocument (PyObject *self, PyObject *value, void *closure)
setter callback for the Document attribute
static PyObject * staticCallback_getState (PyObject *self, void *closure)
getter callback for the State attribute
static int staticCallback_setState (PyObject *self, PyObject *value, void *closure)
setter callback for the State attribute
static PyObject * staticCallback_getViewObject (PyObject *self, void *closure)
getter callback for the ViewObject attribute
static int staticCallback_setViewObject (PyObject *self, PyObject *value, void *closure)
setter callback for the ViewObject attribute
static PyObject * staticCallback_getMustExecute (PyObject *self, void *closure)
getter callback for the MustExecute attribute
static int staticCallback_setMustExecute (PyObject *self, PyObject *value, void *closure)
setter callback for the MustExecute attribute
static PyObject * staticCallback_getID (PyObject *self, void *closure)
getter callback for the ID attribute
static int staticCallback_setID (PyObject *self, PyObject *value, void *closure)
setter callback for the ID attribute
static PyObject * staticCallback_getRemoving (PyObject *self, void *closure)
getter callback for the Removing attribute
static int staticCallback_setRemoving (PyObject *self, PyObject *value, void *closure)
setter callback for the Removing attribute
static PyObject * staticCallback_getParents (PyObject *self, void *closure)
getter callback for the Parents attribute
static int staticCallback_setParents (PyObject *self, PyObject *value, void *closure)
setter callback for the Parents attribute
static PyObject * staticCallback_getOldLabel (PyObject *self, void *closure)
getter callback for the OldLabel attribute
static int staticCallback_setOldLabel (PyObject *self, PyObject *value, void *closure)
setter callback for the OldLabel attribute
static PyObject * staticCallback_getNoTouch (PyObject *self, void *closure)
getter callback for the NoTouch attribute
static int staticCallback_setNoTouch (PyObject *self, PyObject *value, void *closure)
setter callback for the NoTouch attribute
Static Public Member Functions inherited from App::ExtensionContainerPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_addExtension (PyObject *self, PyObject *args)
callback for the addExtension() method
static PyObject * staticCallback_hasExtension (PyObject *self, PyObject *args)
callback for the hasExtension() method
Static Public Member Functions inherited from App::PropertyContainerPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_getPropertyByName (PyObject *self, PyObject *args)
callback for the getPropertyByName() method
static PyObject * staticCallback_getPropertyTouchList (PyObject *self, PyObject *args)
callback for the getPropertyTouchList() method
static PyObject * staticCallback_getTypeOfProperty (PyObject *self, PyObject *args)
callback for the getTypeOfProperty() method
static PyObject * staticCallback_getTypeIdOfProperty (PyObject *self, PyObject *args)
callback for the getTypeIdOfProperty() method
static PyObject * staticCallback_setEditorMode (PyObject *self, PyObject *args)
callback for the setEditorMode() method
static PyObject * staticCallback_getEditorMode (PyObject *self, PyObject *args)
callback for the getEditorMode() method
static PyObject * staticCallback_getGroupOfProperty (PyObject *self, PyObject *args)
callback for the getGroupOfProperty() method
static PyObject * staticCallback_setPropertyStatus (PyObject *self, PyObject *args)
callback for the setPropertyStatus() method
static PyObject * staticCallback_getPropertyStatus (PyObject *self, PyObject *args)
callback for the getPropertyStatus() method
static PyObject * staticCallback_getDocumentationOfProperty (PyObject *self, PyObject *args)
callback for the getDocumentationOfProperty() method
static PyObject * staticCallback_dumpPropertyContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpPropertyContent() method
static PyObject * staticCallback_restorePropertyContent (PyObject *self, PyObject *args)
callback for the restorePropertyContent() method
static PyObject * staticCallback_getPropertiesList (PyObject *self, void *closure)
getter callback for the PropertiesList attribute
static int staticCallback_setPropertiesList (PyObject *self, PyObject *value, void *closure)
setter callback for the PropertiesList attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of SketchObjectPy.
static PyMethodDef Methods []
Methods structure of SketchObjectPy.
static PyTypeObject Type
Type structure of SketchObjectPy.
Static Public Attributes inherited from Part::Part2DObjectPy
static PyGetSetDef GetterSetter []
Attribute structure of Part2DObjectPy.
static PyMethodDef Methods []
Methods structure of Part2DObjectPy.
static PyTypeObject Type
Type structure of Part2DObjectPy.
Static Public Attributes inherited from Part::PartFeaturePy
static PyGetSetDef GetterSetter []
Attribute structure of PartFeaturePy.
static PyMethodDef Methods []
Methods structure of PartFeaturePy.
static PyTypeObject Type
Type structure of PartFeaturePy.
Static Public Attributes inherited from App::GeoFeaturePy
static PyGetSetDef GetterSetter []
Attribute structure of GeoFeaturePy.
static PyMethodDef Methods []
Methods structure of GeoFeaturePy.
static PyTypeObject Type
Type structure of GeoFeaturePy.
Static Public Attributes inherited from App::DocumentObjectPy
static PyGetSetDef GetterSetter []
Attribute structure of DocumentObjectPy.
static PyMethodDef Methods []
Methods structure of DocumentObjectPy.
static PyTypeObject Type
Type structure of DocumentObjectPy.
Static Public Attributes inherited from App::ExtensionContainerPy
static PyGetSetDef GetterSetter []
Attribute structure of ExtensionContainerPy.
static PyMethodDef Methods []
Methods structure of ExtensionContainerPy.
static PyTypeObject Type
Type structure of ExtensionContainerPy.
Static Public Attributes inherited from App::PropertyContainerPy
static PyGetSetDef GetterSetter []
Attribute structure of PropertyContainerPy.
static PyMethodDef Methods []
Methods structure of PropertyContainerPy.
static PyTypeObject Type
Type structure of PropertyContainerPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~SketchObjectPy ()
Protected Member Functions inherited from Part::Part2DObjectPy
~Part2DObjectPy ()
Protected Member Functions inherited from Part::PartFeaturePy
~PartFeaturePy ()
Protected Member Functions inherited from App::GeoFeaturePy
~GeoFeaturePy ()
Protected Member Functions inherited from App::DocumentObjectPy
~DocumentObjectPy ()
Protected Member Functions inherited from App::ExtensionContainerPy
~ExtensionContainerPy ()
Protected Member Functions inherited from App::PropertyContainerPy
~PropertyContainerPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * solve (PyObject *args)
implementer for the solve() method
PyObject * addGeometry (PyObject *args)
implementer for the addGeometry() method
PyObject * delGeometry (PyObject *args)
implementer for the delGeometry() method
PyObject * deleteAllGeometry (PyObject *args)
implementer for the deleteAllGeometry() method
PyObject * deleteAllConstraints (PyObject *args)
implementer for the deleteAllConstraints() method
PyObject * toggleConstruction (PyObject *args)
implementer for the toggleConstruction() method
PyObject * setConstruction (PyObject *args)
implementer for the setConstruction() method
PyObject * addConstraint (PyObject *args)
implementer for the addConstraint() method
PyObject * delConstraint (PyObject *args)
implementer for the delConstraint() method
PyObject * renameConstraint (PyObject *args)
implementer for the renameConstraint() method
PyObject * getIndexByName (PyObject *args)
implementer for the getIndexByName() method
PyObject * carbonCopy (PyObject *args)
implementer for the carbonCopy() method
PyObject * addExternal (PyObject *args)
implementer for the addExternal() method
PyObject * delExternal (PyObject *args)
implementer for the delExternal() method
PyObject * delConstraintOnPoint (PyObject *args)
implementer for the delConstraintOnPoint() method
PyObject * setDatum (PyObject *args)
implementer for the setDatum() method
PyObject * getDatum (PyObject *args)
implementer for the getDatum() method
PyObject * setDriving (PyObject *args)
implementer for the setDriving() method
PyObject * setDatumsDriving (PyObject *args)
implementer for the setDatumsDriving() method
PyObject * moveDatumsToEnd (PyObject *args)
implementer for the moveDatumsToEnd() method
PyObject * getDriving (PyObject *args)
implementer for the getDriving() method
PyObject * toggleDriving (PyObject *args)
implementer for the toggleDriving() method
PyObject * setVirtualSpace (PyObject *args)
implementer for the setVirtualSpace() method
PyObject * getVirtualSpace (PyObject *args)
implementer for the getVirtualSpace() method
PyObject * toggleVirtualSpace (PyObject *args)
implementer for the toggleVirtualSpace() method
PyObject * setActive (PyObject *args)
implementer for the setActive() method
PyObject * getActive (PyObject *args)
implementer for the getActive() method
PyObject * toggleActive (PyObject *args)
implementer for the toggleActive() method
PyObject * movePoint (PyObject *args)
implementer for the movePoint() method
PyObject * getPoint (PyObject *args)
implementer for the getPoint() method
PyObject * getGeoVertexIndex (PyObject *args)
implementer for the getGeoVertexIndex() method
PyObject * getAxis (PyObject *args)
implementer for the getAxis() method
PyObject * fillet (PyObject *args)
implementer for the fillet() method
PyObject * trim (PyObject *args)
implementer for the trim() method
PyObject * extend (PyObject *args)
implementer for the extend() method
PyObject * addSymmetric (PyObject *args)
implementer for the addSymmetric() method
PyObject * addCopy (PyObject *args)
implementer for the addCopy() method
PyObject * addMove (PyObject *args)
implementer for the addMove() method
PyObject * addRectangularArray (PyObject *args)
implementer for the addRectangularArray() method
PyObject * ExposeInternalGeometry (PyObject *args)
implementer for the ExposeInternalGeometry() method
PyObject * DeleteUnusedInternalGeometry (PyObject *args)
implementer for the DeleteUnusedInternalGeometry() method
PyObject * exposeInternalGeometry (PyObject *args)
implementer for the exposeInternalGeometry() method
PyObject * deleteUnusedInternalGeometry (PyObject *args)
implementer for the deleteUnusedInternalGeometry() method
PyObject * convertToNURBS (PyObject *args)
implementer for the convertToNURBS() method
PyObject * increaseBSplineDegree (PyObject *args)
implementer for the increaseBSplineDegree() method
PyObject * decreaseBSplineDegree (PyObject *args)
implementer for the decreaseBSplineDegree() method
PyObject * modifyBSplineKnotMultiplicity (PyObject *args)
implementer for the modifyBSplineKnotMultiplicity() method
PyObject * calculateAngleViaPoint (PyObject *args)
implementer for the calculateAngleViaPoint() method
PyObject * isPointOnCurve (PyObject *args)
implementer for the isPointOnCurve() method
PyObject * calculateConstraintError (PyObject *args)
implementer for the calculateConstraintError() method
PyObject * changeConstraintsLocking (PyObject *args)
implementer for the changeConstraintsLocking() method
PyObject * getGeometryWithDependentParameters (PyObject *args)
implementer for the getGeometryWithDependentParameters() method
PyObject * autoconstraint (PyObject *args)
implementer for the autoconstraint() method
PyObject * detectMissingPointOnPointConstraints (PyObject *args)
implementer for the detectMissingPointOnPointConstraints() method
PyObject * analyseMissingPointOnPointCoincident (PyObject *args)
implementer for the analyseMissingPointOnPointCoincident() method
PyObject * detectMissingVerticalHorizontalConstraints (PyObject *args)
implementer for the detectMissingVerticalHorizontalConstraints() method
PyObject * detectMissingEqualityConstraints (PyObject *args)
implementer for the detectMissingEqualityConstraints() method
PyObject * makeMissingPointOnPointCoincident (PyObject *args)
implementer for the makeMissingPointOnPointCoincident() method
PyObject * makeMissingVerticalHorizontal (PyObject *args)
implementer for the makeMissingVerticalHorizontal() method
PyObject * makeMissingEquality (PyObject *args)
implementer for the makeMissingEquality() method
PyObject * autoRemoveRedundants (PyObject *args)
implementer for the autoRemoveRedundants() method
PyObject * setGeometryId (PyObject *args)
implementer for the setGeometryId() method
PyObject * getGeometryId (PyObject *args)
implementer for the getGeometryId() method
static PyObject * staticCallback_solve (PyObject *self, PyObject *args)
callback for the solve() method
static PyObject * staticCallback_addGeometry (PyObject *self, PyObject *args)
callback for the addGeometry() method
static PyObject * staticCallback_delGeometry (PyObject *self, PyObject *args)
callback for the delGeometry() method
static PyObject * staticCallback_deleteAllGeometry (PyObject *self, PyObject *args)
callback for the deleteAllGeometry() method
static PyObject * staticCallback_deleteAllConstraints (PyObject *self, PyObject *args)
callback for the deleteAllConstraints() method
static PyObject * staticCallback_toggleConstruction (PyObject *self, PyObject *args)
callback for the toggleConstruction() method
static PyObject * staticCallback_setConstruction (PyObject *self, PyObject *args)
callback for the setConstruction() method
static PyObject * staticCallback_addConstraint (PyObject *self, PyObject *args)
callback for the addConstraint() method
static PyObject * staticCallback_delConstraint (PyObject *self, PyObject *args)
callback for the delConstraint() method
static PyObject * staticCallback_renameConstraint (PyObject *self, PyObject *args)
callback for the renameConstraint() method
static PyObject * staticCallback_getIndexByName (PyObject *self, PyObject *args)
callback for the getIndexByName() method
static PyObject * staticCallback_carbonCopy (PyObject *self, PyObject *args)
callback for the carbonCopy() method
static PyObject * staticCallback_addExternal (PyObject *self, PyObject *args)
callback for the addExternal() method
static PyObject * staticCallback_delExternal (PyObject *self, PyObject *args)
callback for the delExternal() method
static PyObject * staticCallback_delConstraintOnPoint (PyObject *self, PyObject *args)
callback for the delConstraintOnPoint() method
static PyObject * staticCallback_setDatum (PyObject *self, PyObject *args)
callback for the setDatum() method
static PyObject * staticCallback_getDatum (PyObject *self, PyObject *args)
callback for the getDatum() method
static PyObject * staticCallback_setDriving (PyObject *self, PyObject *args)
callback for the setDriving() method
static PyObject * staticCallback_setDatumsDriving (PyObject *self, PyObject *args)
callback for the setDatumsDriving() method
static PyObject * staticCallback_moveDatumsToEnd (PyObject *self, PyObject *args)
callback for the moveDatumsToEnd() method
static PyObject * staticCallback_getDriving (PyObject *self, PyObject *args)
callback for the getDriving() method
static PyObject * staticCallback_toggleDriving (PyObject *self, PyObject *args)
callback for the toggleDriving() method
static PyObject * staticCallback_setVirtualSpace (PyObject *self, PyObject *args)
callback for the setVirtualSpace() method
static PyObject * staticCallback_getVirtualSpace (PyObject *self, PyObject *args)
callback for the getVirtualSpace() method
static PyObject * staticCallback_toggleVirtualSpace (PyObject *self, PyObject *args)
callback for the toggleVirtualSpace() method
static PyObject * staticCallback_setActive (PyObject *self, PyObject *args)
callback for the setActive() method
static PyObject * staticCallback_getActive (PyObject *self, PyObject *args)
callback for the getActive() method
static PyObject * staticCallback_toggleActive (PyObject *self, PyObject *args)
callback for the toggleActive() method
static PyObject * staticCallback_movePoint (PyObject *self, PyObject *args)
callback for the movePoint() method
static PyObject * staticCallback_getPoint (PyObject *self, PyObject *args)
callback for the getPoint() method
static PyObject * staticCallback_getGeoVertexIndex (PyObject *self, PyObject *args)
callback for the getGeoVertexIndex() method
static PyObject * staticCallback_getAxis (PyObject *self, PyObject *args)
callback for the getAxis() method
static PyObject * staticCallback_fillet (PyObject *self, PyObject *args)
callback for the fillet() method
static PyObject * staticCallback_trim (PyObject *self, PyObject *args)
callback for the trim() method
static PyObject * staticCallback_extend (PyObject *self, PyObject *args)
callback for the extend() method
static PyObject * staticCallback_addSymmetric (PyObject *self, PyObject *args)
callback for the addSymmetric() method
static PyObject * staticCallback_addCopy (PyObject *self, PyObject *args)
callback for the addCopy() method
static PyObject * staticCallback_addMove (PyObject *self, PyObject *args)
callback for the addMove() method
static PyObject * staticCallback_addRectangularArray (PyObject *self, PyObject *args)
callback for the addRectangularArray() method
static PyObject * staticCallback_ExposeInternalGeometry (PyObject *self, PyObject *args)
callback for the ExposeInternalGeometry() method
static PyObject * staticCallback_DeleteUnusedInternalGeometry (PyObject *self, PyObject *args)
callback for the DeleteUnusedInternalGeometry() method
static PyObject * staticCallback_exposeInternalGeometry (PyObject *self, PyObject *args)
callback for the exposeInternalGeometry() method
static PyObject * staticCallback_deleteUnusedInternalGeometry (PyObject *self, PyObject *args)
callback for the deleteUnusedInternalGeometry() method
static PyObject * staticCallback_convertToNURBS (PyObject *self, PyObject *args)
callback for the convertToNURBS() method
static PyObject * staticCallback_increaseBSplineDegree (PyObject *self, PyObject *args)
callback for the increaseBSplineDegree() method
static PyObject * staticCallback_decreaseBSplineDegree (PyObject *self, PyObject *args)
callback for the decreaseBSplineDegree() method
static PyObject * staticCallback_modifyBSplineKnotMultiplicity (PyObject *self, PyObject *args)
callback for the modifyBSplineKnotMultiplicity() method
static PyObject * staticCallback_calculateAngleViaPoint (PyObject *self, PyObject *args)
callback for the calculateAngleViaPoint() method
static PyObject * staticCallback_isPointOnCurve (PyObject *self, PyObject *args)
callback for the isPointOnCurve() method
static PyObject * staticCallback_calculateConstraintError (PyObject *self, PyObject *args)
callback for the calculateConstraintError() method
static PyObject * staticCallback_changeConstraintsLocking (PyObject *self, PyObject *args)
callback for the changeConstraintsLocking() method
static PyObject * staticCallback_getGeometryWithDependentParameters (PyObject *self, PyObject *args)
callback for the getGeometryWithDependentParameters() method
static PyObject * staticCallback_autoconstraint (PyObject *self, PyObject *args)
callback for the autoconstraint() method
static PyObject * staticCallback_detectMissingPointOnPointConstraints (PyObject *self, PyObject *args)
callback for the detectMissingPointOnPointConstraints() method
static PyObject * staticCallback_analyseMissingPointOnPointCoincident (PyObject *self, PyObject *args)
callback for the analyseMissingPointOnPointCoincident() method
static PyObject * staticCallback_detectMissingVerticalHorizontalConstraints (PyObject *self, PyObject *args)
callback for the detectMissingVerticalHorizontalConstraints() method
static PyObject * staticCallback_detectMissingEqualityConstraints (PyObject *self, PyObject *args)
callback for the detectMissingEqualityConstraints() method
static PyObject * staticCallback_makeMissingPointOnPointCoincident (PyObject *self, PyObject *args)
callback for the makeMissingPointOnPointCoincident() method
static PyObject * staticCallback_makeMissingVerticalHorizontal (PyObject *self, PyObject *args)
callback for the makeMissingVerticalHorizontal() method
static PyObject * staticCallback_makeMissingEquality (PyObject *self, PyObject *args)
callback for the makeMissingEquality() method
static PyObject * staticCallback_autoRemoveRedundants (PyObject *self, PyObject *args)
callback for the autoRemoveRedundants() method
static PyObject * staticCallback_setGeometryId (PyObject *self, PyObject *args)
callback for the setGeometryId() method
static PyObject * staticCallback_getGeometryId (PyObject *self, PyObject *args)
callback for the getGeometryId() method
callbacks and implementers for the python object attributes
Py::List getMissingPointOnPointConstraints (void) const
getter for the MissingPointOnPointConstraints attribute
void setMissingPointOnPointConstraints (Py::List arg)
setter for the MissingPointOnPointConstraints attribute
Py::List getMissingVerticalHorizontalConstraints (void) const
getter for the MissingVerticalHorizontalConstraints attribute
void setMissingVerticalHorizontalConstraints (Py::List arg)
setter for the MissingVerticalHorizontalConstraints attribute
Py::List getMissingLineEqualityConstraints (void) const
getter for the MissingLineEqualityConstraints attribute
void setMissingLineEqualityConstraints (Py::List arg)
setter for the MissingLineEqualityConstraints attribute
Py::List getMissingRadiusConstraints (void) const
getter for the MissingRadiusConstraints attribute
void setMissingRadiusConstraints (Py::List arg)
setter for the MissingRadiusConstraints attribute
Py::List getOpenVertices (void) const
getter for the OpenVertices attribute
Py::Long getConstraintCount (void) const
getter for the ConstraintCount attribute
Py::Long getGeometryCount (void) const
getter for the GeometryCount attribute
Py::Long getAxisCount (void) const
getter for the AxisCount attribute
Py::List getGeometryFacadeList (void) const
getter for the GeometryFacadeList attribute
void setGeometryFacadeList (Py::List arg)
setter for the GeometryFacadeList attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
SketchObject * getSketchObjectPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getMissingPointOnPointConstraints (PyObject *self, void *closure)
getter callback for the MissingPointOnPointConstraints attribute
static int staticCallback_setMissingPointOnPointConstraints (PyObject *self, PyObject *value, void *closure)
setter callback for the MissingPointOnPointConstraints attribute
static PyObject * staticCallback_getMissingVerticalHorizontalConstraints (PyObject *self, void *closure)
getter callback for the MissingVerticalHorizontalConstraints attribute
static int staticCallback_setMissingVerticalHorizontalConstraints (PyObject *self, PyObject *value, void *closure)
setter callback for the MissingVerticalHorizontalConstraints attribute
static PyObject * staticCallback_getMissingLineEqualityConstraints (PyObject *self, void *closure)
getter callback for the MissingLineEqualityConstraints attribute
static int staticCallback_setMissingLineEqualityConstraints (PyObject *self, PyObject *value, void *closure)
setter callback for the MissingLineEqualityConstraints attribute
static PyObject * staticCallback_getMissingRadiusConstraints (PyObject *self, void *closure)
getter callback for the MissingRadiusConstraints attribute
static int staticCallback_setMissingRadiusConstraints (PyObject *self, PyObject *value, void *closure)
setter callback for the MissingRadiusConstraints attribute
static PyObject * staticCallback_getOpenVertices (PyObject *self, void *closure)
getter callback for the OpenVertices attribute
static int staticCallback_setOpenVertices (PyObject *self, PyObject *value, void *closure)
setter callback for the OpenVertices attribute
static PyObject * staticCallback_getConstraintCount (PyObject *self, void *closure)
getter callback for the ConstraintCount attribute
static int staticCallback_setConstraintCount (PyObject *self, PyObject *value, void *closure)
setter callback for the ConstraintCount attribute
static PyObject * staticCallback_getGeometryCount (PyObject *self, void *closure)
getter callback for the GeometryCount attribute
static int staticCallback_setGeometryCount (PyObject *self, PyObject *value, void *closure)
setter callback for the GeometryCount attribute
static PyObject * staticCallback_getAxisCount (PyObject *self, void *closure)
getter callback for the AxisCount attribute
static int staticCallback_setAxisCount (PyObject *self, PyObject *value, void *closure)
setter callback for the AxisCount attribute
static PyObject * staticCallback_getGeometryFacadeList (PyObject *self, void *closure)
getter callback for the GeometryFacadeList attribute
static int staticCallback_setGeometryFacadeList (PyObject *self, PyObject *value, void *closure)
setter callback for the GeometryFacadeList attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for SketchObject.
Member Typedef Documentation
PointerType
typedef SketchObject* Sketcher::SketchObjectPy::PointerType
Constructor & Destructor Documentation
~SketchObjectPy()
SketchObjectPy::~SketchObjectPy () protected
SketchObjectPy()
SketchObjectPy::SketchObjectPy (SketchObject * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
addConstraint()
PyObject * SketchObjectPy::addConstraint (PyObject * args)
implementer for the addConstraint() method
References Sketcher::SketchObject::addConstraint(), Sketcher::SketchObject::addConstraints(), Sketcher::SketchObject::Constraints, Sketcher::SketchObject::evaluateConstraint(), getSketchObjectPtr(), Sketcher::SketchObject::setUpSketch(), Sketcher::SketchObject::solve(), App::Property::touch(), and Sketcher::ConstraintPy::Type.
Referenced by staticCallback_addConstraint().
addCopy()
PyObject * SketchObjectPy::addCopy (PyObject * args)
implementer for the addCopy() method
References Sketcher::SketchObject::addCopy(), getSketchObjectPtr(), and Base::VectorPy::Type.
Referenced by staticCallback_addCopy().
addExternal()
PyObject * SketchObjectPy::addExternal (PyObject * args)
implementer for the addExternal() method
References Sketcher::SketchObject::addExternal(), App::DocumentObject::getDocument(), App::Document::getObject(), getSketchObjectPtr(), and Sketcher::SketchObject::isExternalAllowed().
Referenced by staticCallback_addExternal().
addGeometry()
PyObject * SketchObjectPy::addGeometry (PyObject * args)
implementer for the addGeometry() method
References Sketcher::SketchObject::addGeometry(), Base::Persistence::getClassTypeId(), Base::Type::getName(), getSketchObjectPtr(), Base::Persistence::getTypeId(), Part::GeomArcOfCircle::setHandle(), Part::GeomArcOfEllipse::setHandle(), trim(), and Part::GeometryPy::Type.
Referenced by staticCallback_addGeometry().
addMove()
PyObject * SketchObjectPy::addMove (PyObject * args)
implementer for the addMove() method
References Sketcher::SketchObject::addCopy(), getSketchObjectPtr(), and Base::VectorPy::Type.
Referenced by staticCallback_addMove().
addRectangularArray()
PyObject * SketchObjectPy::addRectangularArray (PyObject * args)
implementer for the addRectangularArray() method
References Sketcher::SketchObject::addCopy(), getSketchObjectPtr(), and Base::VectorPy::Type.
Referenced by staticCallback_addRectangularArray().
addSymmetric()
PyObject * SketchObjectPy::addSymmetric (PyObject * args)
implementer for the addSymmetric() method
References Sketcher::SketchObject::addSymmetric(), getSketchObjectPtr(), and Sketcher::none.
Referenced by staticCallback_addSymmetric().
analyseMissingPointOnPointCoincident()
PyObject * SketchObjectPy::analyseMissingPointOnPointCoincident (PyObject * args)
implementer for the analyseMissingPointOnPointCoincident() method
References Sketcher::SketchObject::analyseMissingPointOnPointCoincident(), and getSketchObjectPtr().
Referenced by staticCallback_analyseMissingPointOnPointCoincident().
autoconstraint()
PyObject * SketchObjectPy::autoconstraint (PyObject * args)
implementer for the autoconstraint() method
References getSketchObjectPtr().
Referenced by staticCallback_autoconstraint().
autoRemoveRedundants()
PyObject * SketchObjectPy::autoRemoveRedundants (PyObject * args)
implementer for the autoRemoveRedundants() method
References Sketcher::SketchObject::autoRemoveRedundants(), and getSketchObjectPtr().
Referenced by staticCallback_autoRemoveRedundants().
calculateAngleViaPoint()
PyObject * SketchObjectPy::calculateAngleViaPoint (PyObject * args)
implementer for the calculateAngleViaPoint() method
References getSketchObjectPtr().
Referenced by staticCallback_calculateAngleViaPoint().
calculateConstraintError()
PyObject * SketchObjectPy::calculateConstraintError (PyObject * args)
implementer for the calculateConstraintError() method
References getSketchObjectPtr().
Referenced by staticCallback_calculateConstraintError().
carbonCopy()
PyObject * SketchObjectPy::carbonCopy (PyObject * args)
implementer for the carbonCopy() method
References Sketcher::SketchObject::carbonCopy(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::Document::getObject(), getSketchObjectPtr(), Base::Persistence::getTypeId(), and Sketcher::SketchObject::isExternalAllowed().
Referenced by staticCallback_carbonCopy().
changeConstraintsLocking()
PyObject * SketchObjectPy::changeConstraintsLocking (PyObject * args)
implementer for the changeConstraintsLocking() method
References getSketchObjectPtr().
Referenced by staticCallback_changeConstraintsLocking().
convertToNURBS()
PyObject * SketchObjectPy::convertToNURBS (PyObject * args)
implementer for the convertToNURBS() method
References getSketchObjectPtr().
Referenced by staticCallback_convertToNURBS().
decreaseBSplineDegree()
PyObject * SketchObjectPy::decreaseBSplineDegree (PyObject * args)
implementer for the decreaseBSplineDegree() method
References Sketcher::SketchObject::decreaseBSplineDegree(), and getSketchObjectPtr().
Referenced by staticCallback_decreaseBSplineDegree().
delConstraint()
PyObject * SketchObjectPy::delConstraint (PyObject * args)
implementer for the delConstraint() method
References getSketchObjectPtr().
Referenced by staticCallback_delConstraint().
delConstraintOnPoint()
PyObject * SketchObjectPy::delConstraintOnPoint (PyObject * args)
implementer for the delConstraintOnPoint() method
References getSketchObjectPtr().
Referenced by staticCallback_delConstraintOnPoint().
deleteAllConstraints()
PyObject * SketchObjectPy::deleteAllConstraints (PyObject * args)
implementer for the deleteAllConstraints() method
References getSketchObjectPtr().
Referenced by staticCallback_deleteAllConstraints().
deleteAllGeometry()
PyObject * SketchObjectPy::deleteAllGeometry (PyObject * args)
implementer for the deleteAllGeometry() method
References getSketchObjectPtr().
Referenced by staticCallback_deleteAllGeometry().
DeleteUnusedInternalGeometry()
PyObject * SketchObjectPy::DeleteUnusedInternalGeometry (PyObject * args)
implementer for the DeleteUnusedInternalGeometry() method
References deleteUnusedInternalGeometry(), and getSketchObjectPtr().
Referenced by staticCallback_DeleteUnusedInternalGeometry().
deleteUnusedInternalGeometry()
PyObject * SketchObjectPy::deleteUnusedInternalGeometry (PyObject * args)
implementer for the deleteUnusedInternalGeometry() method
References getSketchObjectPtr().
Referenced by DeleteUnusedInternalGeometry(), and staticCallback_deleteUnusedInternalGeometry().
delExternal()
PyObject * SketchObjectPy::delExternal (PyObject * args)
implementer for the delExternal() method
References getSketchObjectPtr().
Referenced by staticCallback_delExternal().
delGeometry()
PyObject * SketchObjectPy::delGeometry (PyObject * args)
implementer for the delGeometry() method
References getSketchObjectPtr().
Referenced by staticCallback_delGeometry().
detectMissingEqualityConstraints()
PyObject * SketchObjectPy::detectMissingEqualityConstraints (PyObject * args)
implementer for the detectMissingEqualityConstraints() method
References getSketchObjectPtr().
Referenced by staticCallback_detectMissingEqualityConstraints().
detectMissingPointOnPointConstraints()
PyObject * SketchObjectPy::detectMissingPointOnPointConstraints (PyObject * args)
implementer for the detectMissingPointOnPointConstraints() method
References getSketchObjectPtr().
Referenced by staticCallback_detectMissingPointOnPointConstraints().
detectMissingVerticalHorizontalConstraints()
PyObject * SketchObjectPy::detectMissingVerticalHorizontalConstraints (PyObject * args)
implementer for the detectMissingVerticalHorizontalConstraints() method
References getSketchObjectPtr().
Referenced by staticCallback_detectMissingVerticalHorizontalConstraints().
ExposeInternalGeometry()
PyObject * SketchObjectPy::ExposeInternalGeometry (PyObject * args)
implementer for the ExposeInternalGeometry() method
References exposeInternalGeometry(), and getSketchObjectPtr().
Referenced by staticCallback_ExposeInternalGeometry().
exposeInternalGeometry()
PyObject * SketchObjectPy::exposeInternalGeometry (PyObject * args)
implementer for the exposeInternalGeometry() method
References getSketchObjectPtr().
Referenced by ExposeInternalGeometry(), and staticCallback_exposeInternalGeometry().
extend()
PyObject * SketchObjectPy::extend (PyObject * args)
implementer for the extend() method
References getSketchObjectPtr().
Referenced by staticCallback_extend().
fillet()
PyObject * SketchObjectPy::fillet (PyObject * args)
implementer for the fillet() method
References Sketcher::SketchObject::fillet(), getSketchObjectPtr(), trim(), and Base::VectorPy::Type.
Referenced by staticCallback_fillet().
getActive()
PyObject * SketchObjectPy::getActive (PyObject * args)
implementer for the getActive() method
References getSketchObjectPtr().
Referenced by staticCallback_getActive().
getAxis()
PyObject * SketchObjectPy::getAxis (PyObject * args)
implementer for the getAxis() method
References getSketchObjectPtr().
Referenced by staticCallback_getAxis().
getAxisCount()
Py::Long SketchObjectPy::getAxisCount (void) const
getter for the AxisCount attribute
References getSketchObjectPtr().
Referenced by staticCallback_getAxisCount().
getConstraintCount()
Py::Long SketchObjectPy::getConstraintCount (void) const
getter for the ConstraintCount attribute
References getSketchObjectPtr().
Referenced by staticCallback_getConstraintCount().
getCustomAttributes()
PyObject * SketchObjectPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getDatum()
PyObject * SketchObjectPy::getDatum (PyObject * args)
implementer for the getDatum() method
References Base::Unit::Angle, Sketcher::Angle, Sketcher::SketchObject::Constraints, Sketcher::Diameter, Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, Sketcher::PropertyConstraintList::getConstraintName(), getSketchObjectPtr(), Sketcher::Constraint::getValue(), Base::Quantity::getValue(), Sketcher::PropertyConstraintList::getValues(), Base::Unit::Length, Sketcher::Radius, Base::Quantity::setUnit(), Base::Quantity::setValue(), and Sketcher::Constraint::Type.
Referenced by staticCallback_getDatum().
getDriving()
PyObject * SketchObjectPy::getDriving (PyObject * args)
implementer for the getDriving() method
References getSketchObjectPtr().
Referenced by staticCallback_getDriving().
getGeometryCount()
Py::Long SketchObjectPy::getGeometryCount (void) const
getter for the GeometryCount attribute
References getSketchObjectPtr().
Referenced by staticCallback_getGeometryCount().
getGeometryFacadeList()
Py::List SketchObjectPy::getGeometryFacadeList (void) const
getter for the GeometryFacadeList attribute
References draftmake.make_clone::clone, Sketcher::SketchObject::Geometry, Sketcher::GeometryFacade::getFacade(), and getSketchObjectPtr().
Referenced by staticCallback_getGeometryFacadeList().
getGeometryId()
PyObject * SketchObjectPy::getGeometryId (PyObject * args)
implementer for the getGeometryId() method
References getSketchObjectPtr().
Referenced by staticCallback_getGeometryId().
getGeometryWithDependentParameters()
PyObject * SketchObjectPy::getGeometryWithDependentParameters (PyObject * args)
implementer for the getGeometryWithDependentParameters() method
References Sketcher::end, Sketcher::SketchObject::getGeometryWithDependentParameters(), getSketchObjectPtr(), Sketcher::none, and Sketcher::start.
Referenced by staticCallback_getGeometryWithDependentParameters().
getGeoVertexIndex()
PyObject * SketchObjectPy::getGeoVertexIndex (PyObject * args)
implementer for the getGeoVertexIndex() method
References getSketchObjectPtr().
Referenced by staticCallback_getGeoVertexIndex().
getIndexByName()
PyObject * SketchObjectPy::getIndexByName (PyObject * args)
implementer for the getIndexByName() method
References Sketcher::SketchObject::Constraints, getSketchObjectPtr(), and Sketcher::PropertyConstraintList::getValues().
Referenced by staticCallback_getIndexByName().
getMissingLineEqualityConstraints()
Py::List SketchObjectPy::getMissingLineEqualityConstraints (void) const
getter for the MissingLineEqualityConstraints attribute
References Sketcher::end, Sketcher::SketchObject::getMissingLineEqualityConstraints(), getSketchObjectPtr(), Sketcher::none, and Sketcher::start.
Referenced by staticCallback_getMissingLineEqualityConstraints().
getMissingPointOnPointConstraints()
Py::List SketchObjectPy::getMissingPointOnPointConstraints (void) const
getter for the MissingPointOnPointConstraints attribute
References Sketcher::end, Sketcher::SketchObject::getMissingPointOnPointConstraints(), getSketchObjectPtr(), Sketcher::none, and Sketcher::start.
Referenced by staticCallback_getMissingPointOnPointConstraints().
getMissingRadiusConstraints()
Py::List SketchObjectPy::getMissingRadiusConstraints (void) const
getter for the MissingRadiusConstraints attribute
References Sketcher::end, Sketcher::SketchObject::getMissingRadiusConstraints(), getSketchObjectPtr(), Sketcher::none, and Sketcher::start.
Referenced by staticCallback_getMissingRadiusConstraints().
getMissingVerticalHorizontalConstraints()
Py::List SketchObjectPy::getMissingVerticalHorizontalConstraints (void) const
getter for the MissingVerticalHorizontalConstraints attribute
References Sketcher::end, Sketcher::SketchObject::getMissingVerticalHorizontalConstraints(), getSketchObjectPtr(), Sketcher::none, and Sketcher::start.
Referenced by staticCallback_getMissingVerticalHorizontalConstraints().
getOpenVertices()
Py::List SketchObjectPy::getOpenVertices (void) const
getter for the OpenVertices attribute
References Sketcher::SketchObject::getOpenVertices(), and getSketchObjectPtr().
Referenced by staticCallback_getOpenVertices().
getPoint()
PyObject * SketchObjectPy::getPoint (PyObject * args)
implementer for the getPoint() method
References getSketchObjectPtr().
Referenced by staticCallback_getPoint().
getSketchObjectPtr()
SketchObject * SketchObjectPy::getSketchObjectPtr (void) const
getter for the object handled by this class
Referenced by addConstraint(), addCopy(), addExternal(), addGeometry(), addMove(), addRectangularArray(), addSymmetric(), analyseMissingPointOnPointCoincident(), autoconstraint(), autoRemoveRedundants(), calculateAngleViaPoint(), calculateConstraintError(), carbonCopy(), changeConstraintsLocking(), convertToNURBS(), decreaseBSplineDegree(), delConstraint(), delConstraintOnPoint(), deleteAllConstraints(), deleteAllGeometry(), DeleteUnusedInternalGeometry(), deleteUnusedInternalGeometry(), delExternal(), delGeometry(), detectMissingEqualityConstraints(), detectMissingPointOnPointConstraints(), detectMissingVerticalHorizontalConstraints(), ExposeInternalGeometry(), exposeInternalGeometry(), extend(), fillet(), getActive(), getAxis(), getAxisCount(), getConstraintCount(), getDatum(), getDriving(), getGeometryCount(), getGeometryFacadeList(), getGeometryId(), getGeometryWithDependentParameters(), getGeoVertexIndex(), getIndexByName(), getMissingLineEqualityConstraints(), getMissingPointOnPointConstraints(), getMissingRadiusConstraints(), getMissingVerticalHorizontalConstraints(), getOpenVertices(), getPoint(), getVirtualSpace(), increaseBSplineDegree(), isPointOnCurve(), makeMissingEquality(), makeMissingPointOnPointCoincident(), makeMissingVerticalHorizontal(), modifyBSplineKnotMultiplicity(), moveDatumsToEnd(), movePoint(), renameConstraint(), setActive(), setConstruction(), setCustomAttributes(), setDatum(), setDatumsDriving(), setDriving(), setGeometryFacadeList(), setGeometryId(), setMissingLineEqualityConstraints(), setMissingPointOnPointConstraints(), setMissingRadiusConstraints(), setMissingVerticalHorizontalConstraints(), setVirtualSpace(), solve(), toggleActive(), toggleConstruction(), toggleDriving(), toggleVirtualSpace(), and trim().
GetType()
virtual PyTypeObject* Sketcher::SketchObjectPy::GetType (void) virtual
Reimplemented from Part::Part2DObjectPy.
getVirtualSpace()
PyObject * SketchObjectPy::getVirtualSpace (PyObject * args)
implementer for the getVirtualSpace() method
References getSketchObjectPtr().
Referenced by staticCallback_getVirtualSpace().
increaseBSplineDegree()
PyObject * SketchObjectPy::increaseBSplineDegree (PyObject * args)
implementer for the increaseBSplineDegree() method
References getSketchObjectPtr().
Referenced by staticCallback_increaseBSplineDegree().
isPointOnCurve()
PyObject * SketchObjectPy::isPointOnCurve (PyObject * args)
implementer for the isPointOnCurve() method
References Sketcher::Constraint::GeoUndef, and getSketchObjectPtr().
Referenced by staticCallback_isPointOnCurve().
makeMissingEquality()
PyObject * SketchObjectPy::makeMissingEquality (PyObject * args)
implementer for the makeMissingEquality() method
References getSketchObjectPtr(), and Sketcher::SketchObject::makeMissingEquality().
Referenced by staticCallback_makeMissingEquality().
makeMissingPointOnPointCoincident()
PyObject * SketchObjectPy::makeMissingPointOnPointCoincident (PyObject * args)
implementer for the makeMissingPointOnPointCoincident() method
References getSketchObjectPtr(), and Sketcher::SketchObject::makeMissingPointOnPointCoincident().
Referenced by staticCallback_makeMissingPointOnPointCoincident().
makeMissingVerticalHorizontal()
PyObject * SketchObjectPy::makeMissingVerticalHorizontal (PyObject * args)
implementer for the makeMissingVerticalHorizontal() method
References getSketchObjectPtr(), and Sketcher::SketchObject::makeMissingVerticalHorizontal().
Referenced by staticCallback_makeMissingVerticalHorizontal().
modifyBSplineKnotMultiplicity()
PyObject * SketchObjectPy::modifyBSplineKnotMultiplicity (PyObject * args)
implementer for the modifyBSplineKnotMultiplicity() method
References getSketchObjectPtr().
Referenced by staticCallback_modifyBSplineKnotMultiplicity().
moveDatumsToEnd()
PyObject * SketchObjectPy::moveDatumsToEnd (PyObject * args)
implementer for the moveDatumsToEnd() method
References getSketchObjectPtr().
Referenced by staticCallback_moveDatumsToEnd().
movePoint()
PyObject * SketchObjectPy::movePoint (PyObject * args)
implementer for the movePoint() method
References getSketchObjectPtr(), Sketcher::SketchObject::movePoint(), and Base::VectorPy::Type.
Referenced by staticCallback_movePoint().
PyInit()
int SketchObjectPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::Part2DObjectPy.
PyMake()
PyObject * SketchObjectPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
renameConstraint()
PyObject * SketchObjectPy::renameConstraint (PyObject * args)
implementer for the renameConstraint() method
References Sketcher::Constraint::clone(), Sketcher::SketchObject::Constraints, getSketchObjectPtr(), Sketcher::PropertyConstraintList::getValues(), Sketcher::Constraint::Name, Sketcher::PropertyConstraintList::set1Value(), and Sketcher::PropertyConstraintList::validConstraintName().
Referenced by staticCallback_renameConstraint().
representation()
std::string SketchObjectPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setActive()
PyObject * SketchObjectPy::setActive (PyObject * args)
implementer for the setActive() method
References getSketchObjectPtr().
Referenced by staticCallback_setActive().
setConstruction()
PyObject * SketchObjectPy::setConstruction (PyObject * args)
implementer for the setConstruction() method
References getSketchObjectPtr().
Referenced by staticCallback_setConstruction().
setCustomAttributes()
int SketchObjectPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
References App::ExtensionContainer::getPropertyByName(), App::ExtensionContainer::getPropertyType(), getSketchObjectPtr(), App::Prop_ReadOnly, Sketcher::SketchObject::rebuildVertexIndex(), Base::BaseClass::setPyObject(), and Type.
setDatum()
PyObject * SketchObjectPy::setDatum (PyObject * args)
implementer for the setDatum() method
References Base::Unit::Angle, Sketcher::SketchObject::Constraints, getSketchObjectPtr(), Base::Quantity::getUnit(), Base::Quantity::getUserString(), Base::Quantity::getValue(), Sketcher::PropertyConstraintList::getValues(), Sketcher::SketchObject::setDatum(), Base::Quantity::setValue(), and Base::QuantityPy::Type.
Referenced by staticCallback_setDatum().
setDatumsDriving()
PyObject * SketchObjectPy::setDatumsDriving (PyObject * args)
implementer for the setDatumsDriving() method
References getSketchObjectPtr().
Referenced by staticCallback_setDatumsDriving().
setDriving()
PyObject * SketchObjectPy::setDriving (PyObject * args)
implementer for the setDriving() method
References getSketchObjectPtr().
Referenced by staticCallback_setDriving().
setGeometryFacadeList()
void SketchObjectPy::setGeometryFacadeList (Py::List arg)
setter for the GeometryFacadeList attribute
References Sketcher::SketchObject::Geometry, Sketcher::GeometryFacade::getGeometry(), Sketcher::GeometryFacadePy::getGeometryFacadePtr(), getSketchObjectPtr(), draftfunctions.move::move(), and Sketcher::GeometryFacadePy::Type.
Referenced by staticCallback_setGeometryFacadeList().
setGeometryId()
PyObject * SketchObjectPy::setGeometryId (PyObject * args)
implementer for the setGeometryId() method
References getSketchObjectPtr().
Referenced by staticCallback_setGeometryId().
setMissingLineEqualityConstraints()
void SketchObjectPy::setMissingLineEqualityConstraints (Py::List arg)
setter for the MissingLineEqualityConstraints attribute
References Sketcher::end, Sketcher::Equal, Sketcher::ConstraintIds::First, getSketchObjectPtr(), Sketcher::mid, Sketcher::none, Sketcher::SketchObject::setMissingLineEqualityConstraints(), and Sketcher::start.
Referenced by staticCallback_setMissingLineEqualityConstraints().
setMissingPointOnPointConstraints()
void SketchObjectPy::setMissingPointOnPointConstraints (Py::List arg)
setter for the MissingPointOnPointConstraints attribute
References Sketcher::end, Sketcher::ConstraintIds::First, getSketchObjectPtr(), Sketcher::mid, Sketcher::none, Sketcher::SketchObject::setMissingPointOnPointConstraints(), and Sketcher::start.
Referenced by staticCallback_setMissingPointOnPointConstraints().
setMissingRadiusConstraints()
void SketchObjectPy::setMissingRadiusConstraints (Py::List arg)
setter for the MissingRadiusConstraints attribute
References Sketcher::end, Sketcher::Equal, Sketcher::ConstraintIds::First, getSketchObjectPtr(), Sketcher::mid, Sketcher::none, Sketcher::SketchObject::setMissingRadiusConstraints(), and Sketcher::start.
Referenced by staticCallback_setMissingRadiusConstraints().
setMissingVerticalHorizontalConstraints()
void SketchObjectPy::setMissingVerticalHorizontalConstraints (Py::List arg)
setter for the MissingVerticalHorizontalConstraints attribute
References Sketcher::end, Sketcher::ConstraintIds::First, getSketchObjectPtr(), Sketcher::mid, Sketcher::none, Sketcher::SketchObject::setMissingVerticalHorizontalConstraints(), and Sketcher::start.
Referenced by staticCallback_setMissingVerticalHorizontalConstraints().
setVirtualSpace()
PyObject * SketchObjectPy::setVirtualSpace (PyObject * args)
implementer for the setVirtualSpace() method
References getSketchObjectPtr().
Referenced by staticCallback_setVirtualSpace().
solve()
PyObject * SketchObjectPy::solve (PyObject * args)
implementer for the solve() method
References getSketchObjectPtr(), and Sketcher::SketchObject::solve().
Referenced by staticCallback_solve().
staticCallback_addConstraint()
PyObject * SketchObjectPy::staticCallback_addConstraint (PyObject * self, PyObject * args) static
callback for the addConstraint() method
References addConstraint(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addCopy()
PyObject * SketchObjectPy::staticCallback_addCopy (PyObject * self, PyObject * args) static
callback for the addCopy() method
References addCopy(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addExternal()
PyObject * SketchObjectPy::staticCallback_addExternal (PyObject * self, PyObject * args) static
callback for the addExternal() method
References addExternal(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addGeometry()
PyObject * SketchObjectPy::staticCallback_addGeometry (PyObject * self, PyObject * args) static
callback for the addGeometry() method
References addGeometry(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addMove()
PyObject * SketchObjectPy::staticCallback_addMove (PyObject * self, PyObject * args) static
callback for the addMove() method
References addMove(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addRectangularArray()
PyObject * SketchObjectPy::staticCallback_addRectangularArray (PyObject * self, PyObject * args) static
callback for the addRectangularArray() method
References addRectangularArray(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addSymmetric()
PyObject * SketchObjectPy::staticCallback_addSymmetric (PyObject * self, PyObject * args) static
callback for the addSymmetric() method
References addSymmetric(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_analyseMissingPointOnPointCoincident()
PyObject * SketchObjectPy::staticCallback_analyseMissingPointOnPointCoincident (PyObject * self, PyObject * args) static
callback for the analyseMissingPointOnPointCoincident() method
References analyseMissingPointOnPointCoincident(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_autoconstraint()
PyObject * SketchObjectPy::staticCallback_autoconstraint (PyObject * self, PyObject * args) static
callback for the autoconstraint() method
References autoconstraint(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_autoRemoveRedundants()
PyObject * SketchObjectPy::staticCallback_autoRemoveRedundants (PyObject * self, PyObject * args) static
callback for the autoRemoveRedundants() method
References autoRemoveRedundants(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_calculateAngleViaPoint()
PyObject * SketchObjectPy::staticCallback_calculateAngleViaPoint (PyObject * self, PyObject * args) static
callback for the calculateAngleViaPoint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, calculateAngleViaPoint(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_calculateConstraintError()
PyObject * SketchObjectPy::staticCallback_calculateConstraintError (PyObject * self, PyObject * args) static
callback for the calculateConstraintError() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, calculateConstraintError(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_carbonCopy()
PyObject * SketchObjectPy::staticCallback_carbonCopy (PyObject * self, PyObject * args) static
callback for the carbonCopy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, carbonCopy(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_changeConstraintsLocking()
PyObject * SketchObjectPy::staticCallback_changeConstraintsLocking (PyObject * self, PyObject * args) static
callback for the changeConstraintsLocking() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, changeConstraintsLocking(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_convertToNURBS()
PyObject * SketchObjectPy::staticCallback_convertToNURBS (PyObject * self, PyObject * args) static
callback for the convertToNURBS() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, convertToNURBS(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_decreaseBSplineDegree()
PyObject * SketchObjectPy::staticCallback_decreaseBSplineDegree (PyObject * self, PyObject * args) static
callback for the decreaseBSplineDegree() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, decreaseBSplineDegree(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_delConstraint()
PyObject * SketchObjectPy::staticCallback_delConstraint (PyObject * self, PyObject * args) static
callback for the delConstraint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, delConstraint(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_delConstraintOnPoint()
PyObject * SketchObjectPy::staticCallback_delConstraintOnPoint (PyObject * self, PyObject * args) static
callback for the delConstraintOnPoint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, delConstraintOnPoint(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_deleteAllConstraints()
PyObject * SketchObjectPy::staticCallback_deleteAllConstraints (PyObject * self, PyObject * args) static
callback for the deleteAllConstraints() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, deleteAllConstraints(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_deleteAllGeometry()
PyObject * SketchObjectPy::staticCallback_deleteAllGeometry (PyObject * self, PyObject * args) static
callback for the deleteAllGeometry() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, deleteAllGeometry(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_DeleteUnusedInternalGeometry()
PyObject * SketchObjectPy::staticCallback_DeleteUnusedInternalGeometry (PyObject * self, PyObject * args) static
callback for the DeleteUnusedInternalGeometry() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, DeleteUnusedInternalGeometry(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_deleteUnusedInternalGeometry()
PyObject * SketchObjectPy::staticCallback_deleteUnusedInternalGeometry (PyObject * self, PyObject * args) static
callback for the deleteUnusedInternalGeometry() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, deleteUnusedInternalGeometry(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_delExternal()
PyObject * SketchObjectPy::staticCallback_delExternal (PyObject * self, PyObject * args) static
callback for the delExternal() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, delExternal(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_delGeometry()
PyObject * SketchObjectPy::staticCallback_delGeometry (PyObject * self, PyObject * args) static
callback for the delGeometry() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, delGeometry(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_detectMissingEqualityConstraints()
PyObject * SketchObjectPy::staticCallback_detectMissingEqualityConstraints (PyObject * self, PyObject * args) static
callback for the detectMissingEqualityConstraints() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, detectMissingEqualityConstraints(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_detectMissingPointOnPointConstraints()
PyObject * SketchObjectPy::staticCallback_detectMissingPointOnPointConstraints (PyObject * self, PyObject * args) static
callback for the detectMissingPointOnPointConstraints() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, detectMissingPointOnPointConstraints(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_detectMissingVerticalHorizontalConstraints()
PyObject * SketchObjectPy::staticCallback_detectMissingVerticalHorizontalConstraints (PyObject * self, PyObject * args) static
callback for the detectMissingVerticalHorizontalConstraints() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, detectMissingVerticalHorizontalConstraints(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_ExposeInternalGeometry()
PyObject * SketchObjectPy::staticCallback_ExposeInternalGeometry (PyObject * self, PyObject * args) static
callback for the ExposeInternalGeometry() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, ExposeInternalGeometry(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_exposeInternalGeometry()
PyObject * SketchObjectPy::staticCallback_exposeInternalGeometry (PyObject * self, PyObject * args) static
callback for the exposeInternalGeometry() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, exposeInternalGeometry(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_extend()
PyObject * SketchObjectPy::staticCallback_extend (PyObject * self, PyObject * args) static
callback for the extend() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, extend(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_fillet()
PyObject * SketchObjectPy::staticCallback_fillet (PyObject * self, PyObject * args) static
callback for the fillet() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, fillet(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getActive()
PyObject * SketchObjectPy::staticCallback_getActive (PyObject * self, PyObject * args) static
callback for the getActive() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getActive(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getAxis()
PyObject * SketchObjectPy::staticCallback_getAxis (PyObject * self, PyObject * args) static
callback for the getAxis() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getAxis(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getAxisCount()
PyObject * SketchObjectPy::staticCallback_getAxisCount (PyObject * self, void * closure) static
getter callback for the AxisCount attribute
References Base::BaseExceptionFreeCADError, getAxisCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getConstraintCount()
PyObject * SketchObjectPy::staticCallback_getConstraintCount (PyObject * self, void * closure) static
getter callback for the ConstraintCount attribute
References Base::BaseExceptionFreeCADError, getConstraintCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getDatum()
PyObject * SketchObjectPy::staticCallback_getDatum (PyObject * self, PyObject * args) static
callback for the getDatum() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getDatum(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getDriving()
PyObject * SketchObjectPy::staticCallback_getDriving (PyObject * self, PyObject * args) static
callback for the getDriving() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getDriving(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getGeometryCount()
PyObject * SketchObjectPy::staticCallback_getGeometryCount (PyObject * self, void * closure) static
getter callback for the GeometryCount attribute
References Base::BaseExceptionFreeCADError, getGeometryCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getGeometryFacadeList()
PyObject * SketchObjectPy::staticCallback_getGeometryFacadeList (PyObject * self, void * closure) static
getter callback for the GeometryFacadeList attribute
References Base::BaseExceptionFreeCADError, getGeometryFacadeList(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getGeometryId()
PyObject * SketchObjectPy::staticCallback_getGeometryId (PyObject * self, PyObject * args) static
callback for the getGeometryId() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getGeometryId(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getGeometryWithDependentParameters()
PyObject * SketchObjectPy::staticCallback_getGeometryWithDependentParameters (PyObject * self, PyObject * args) static
callback for the getGeometryWithDependentParameters() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getGeometryWithDependentParameters(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getGeoVertexIndex()
PyObject * SketchObjectPy::staticCallback_getGeoVertexIndex (PyObject * self, PyObject * args) static
callback for the getGeoVertexIndex() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getGeoVertexIndex(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getIndexByName()
PyObject * SketchObjectPy::staticCallback_getIndexByName (PyObject * self, PyObject * args) static
callback for the getIndexByName() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getIndexByName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMissingLineEqualityConstraints()
PyObject * SketchObjectPy::staticCallback_getMissingLineEqualityConstraints (PyObject * self, void * closure) static
getter callback for the MissingLineEqualityConstraints attribute
References Base::BaseExceptionFreeCADError, getMissingLineEqualityConstraints(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMissingPointOnPointConstraints()
PyObject * SketchObjectPy::staticCallback_getMissingPointOnPointConstraints (PyObject * self, void * closure) static
getter callback for the MissingPointOnPointConstraints attribute
References Base::BaseExceptionFreeCADError, getMissingPointOnPointConstraints(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMissingRadiusConstraints()
PyObject * SketchObjectPy::staticCallback_getMissingRadiusConstraints (PyObject * self, void * closure) static
getter callback for the MissingRadiusConstraints attribute
References Base::BaseExceptionFreeCADError, getMissingRadiusConstraints(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMissingVerticalHorizontalConstraints()
PyObject * SketchObjectPy::staticCallback_getMissingVerticalHorizontalConstraints (PyObject * self, void * closure) static
getter callback for the MissingVerticalHorizontalConstraints attribute
References Base::BaseExceptionFreeCADError, getMissingVerticalHorizontalConstraints(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getOpenVertices()
PyObject * SketchObjectPy::staticCallback_getOpenVertices (PyObject * self, void * closure) static
getter callback for the OpenVertices attribute
References Base::BaseExceptionFreeCADError, getOpenVertices(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPoint()
PyObject * SketchObjectPy::staticCallback_getPoint (PyObject * self, PyObject * args) static
callback for the getPoint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPoint(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVirtualSpace()
PyObject * SketchObjectPy::staticCallback_getVirtualSpace (PyObject * self, PyObject * args) static
callback for the getVirtualSpace() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getVirtualSpace(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_increaseBSplineDegree()
PyObject * SketchObjectPy::staticCallback_increaseBSplineDegree (PyObject * self, PyObject * args) static
callback for the increaseBSplineDegree() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, increaseBSplineDegree(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_isPointOnCurve()
PyObject * SketchObjectPy::staticCallback_isPointOnCurve (PyObject * self, PyObject * args) static
callback for the isPointOnCurve() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), isPointOnCurve(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_makeMissingEquality()
PyObject * SketchObjectPy::staticCallback_makeMissingEquality (PyObject * self, PyObject * args) static
callback for the makeMissingEquality() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), makeMissingEquality(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_makeMissingPointOnPointCoincident()
PyObject * SketchObjectPy::staticCallback_makeMissingPointOnPointCoincident (PyObject * self, PyObject * args) static
callback for the makeMissingPointOnPointCoincident() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), makeMissingPointOnPointCoincident(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_makeMissingVerticalHorizontal()
PyObject * SketchObjectPy::staticCallback_makeMissingVerticalHorizontal (PyObject * self, PyObject * args) static
callback for the makeMissingVerticalHorizontal() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), makeMissingVerticalHorizontal(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_modifyBSplineKnotMultiplicity()
PyObject * SketchObjectPy::staticCallback_modifyBSplineKnotMultiplicity (PyObject * self, PyObject * args) static
callback for the modifyBSplineKnotMultiplicity() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), modifyBSplineKnotMultiplicity(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_moveDatumsToEnd()
PyObject * SketchObjectPy::staticCallback_moveDatumsToEnd (PyObject * self, PyObject * args) static
callback for the moveDatumsToEnd() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), moveDatumsToEnd(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_movePoint()
PyObject * SketchObjectPy::staticCallback_movePoint (PyObject * self, PyObject * args) static
callback for the movePoint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), movePoint(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_renameConstraint()
PyObject * SketchObjectPy::staticCallback_renameConstraint (PyObject * self, PyObject * args) static
callback for the renameConstraint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), renameConstraint(), and Base::PyObjectBase::startNotify().
staticCallback_setActive()
PyObject * SketchObjectPy::staticCallback_setActive (PyObject * self, PyObject * args) static
callback for the setActive() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setActive(), and Base::PyObjectBase::startNotify().
staticCallback_setAxisCount()
int SketchObjectPy::staticCallback_setAxisCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the AxisCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setConstraintCount()
int SketchObjectPy::staticCallback_setConstraintCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the ConstraintCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setConstruction()
PyObject * SketchObjectPy::staticCallback_setConstruction (PyObject * self, PyObject * args) static
callback for the setConstruction() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setConstruction(), and Base::PyObjectBase::startNotify().
staticCallback_setDatum()
PyObject * SketchObjectPy::staticCallback_setDatum (PyObject * self, PyObject * args) static
callback for the setDatum() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setDatum(), and Base::PyObjectBase::startNotify().
staticCallback_setDatumsDriving()
PyObject * SketchObjectPy::staticCallback_setDatumsDriving (PyObject * self, PyObject * args) static
callback for the setDatumsDriving() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setDatumsDriving(), and Base::PyObjectBase::startNotify().
staticCallback_setDriving()
PyObject * SketchObjectPy::staticCallback_setDriving (PyObject * self, PyObject * args) static
callback for the setDriving() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setDriving(), and Base::PyObjectBase::startNotify().
staticCallback_setGeometryCount()
int SketchObjectPy::staticCallback_setGeometryCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the GeometryCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setGeometryFacadeList()
int SketchObjectPy::staticCallback_setGeometryFacadeList (PyObject * self, PyObject * value, void * closure) static
setter callback for the GeometryFacadeList attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setGeometryFacadeList().
staticCallback_setGeometryId()
PyObject * SketchObjectPy::staticCallback_setGeometryId (PyObject * self, PyObject * args) static
callback for the setGeometryId() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setGeometryId(), and Base::PyObjectBase::startNotify().
staticCallback_setMissingLineEqualityConstraints()
int SketchObjectPy::staticCallback_setMissingLineEqualityConstraints (PyObject * self, PyObject * value, void * closure) static
setter callback for the MissingLineEqualityConstraints attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setMissingLineEqualityConstraints().
staticCallback_setMissingPointOnPointConstraints()
int SketchObjectPy::staticCallback_setMissingPointOnPointConstraints (PyObject * self, PyObject * value, void * closure) static
setter callback for the MissingPointOnPointConstraints attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setMissingPointOnPointConstraints().
staticCallback_setMissingRadiusConstraints()
int SketchObjectPy::staticCallback_setMissingRadiusConstraints (PyObject * self, PyObject * value, void * closure) static
setter callback for the MissingRadiusConstraints attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setMissingRadiusConstraints().
staticCallback_setMissingVerticalHorizontalConstraints()
int SketchObjectPy::staticCallback_setMissingVerticalHorizontalConstraints (PyObject * self, PyObject * value, void * closure) static
setter callback for the MissingVerticalHorizontalConstraints attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setMissingVerticalHorizontalConstraints().
staticCallback_setOpenVertices()
int SketchObjectPy::staticCallback_setOpenVertices (PyObject * self, PyObject * value, void * closure) static
setter callback for the OpenVertices attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setVirtualSpace()
PyObject * SketchObjectPy::staticCallback_setVirtualSpace (PyObject * self, PyObject * args) static
callback for the setVirtualSpace() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setVirtualSpace(), and Base::PyObjectBase::startNotify().
staticCallback_solve()
PyObject * SketchObjectPy::staticCallback_solve (PyObject * self, PyObject * args) static
callback for the solve() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), solve(), and Base::PyObjectBase::startNotify().
staticCallback_toggleActive()
PyObject * SketchObjectPy::staticCallback_toggleActive (PyObject * self, PyObject * args) static
callback for the toggleActive() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and toggleActive().
staticCallback_toggleConstruction()
PyObject * SketchObjectPy::staticCallback_toggleConstruction (PyObject * self, PyObject * args) static
callback for the toggleConstruction() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and toggleConstruction().
staticCallback_toggleDriving()
PyObject * SketchObjectPy::staticCallback_toggleDriving (PyObject * self, PyObject * args) static
callback for the toggleDriving() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and toggleDriving().
staticCallback_toggleVirtualSpace()
PyObject * SketchObjectPy::staticCallback_toggleVirtualSpace (PyObject * self, PyObject * args) static
callback for the toggleVirtualSpace() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and toggleVirtualSpace().
staticCallback_trim()
PyObject * SketchObjectPy::staticCallback_trim (PyObject * self, PyObject * args) static
callback for the trim() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and trim().
toggleActive()
PyObject * SketchObjectPy::toggleActive (PyObject * args)
implementer for the toggleActive() method
References getSketchObjectPtr().
Referenced by staticCallback_toggleActive().
toggleConstruction()
PyObject * SketchObjectPy::toggleConstruction (PyObject * args)
implementer for the toggleConstruction() method
References getSketchObjectPtr().
Referenced by staticCallback_toggleConstruction().
toggleDriving()
PyObject * SketchObjectPy::toggleDriving (PyObject * args)
implementer for the toggleDriving() method
References getSketchObjectPtr().
Referenced by staticCallback_toggleDriving().
toggleVirtualSpace()
PyObject * SketchObjectPy::toggleVirtualSpace (PyObject * args)
implementer for the toggleVirtualSpace() method
References getSketchObjectPtr().
Referenced by staticCallback_toggleVirtualSpace().
trim()
PyObject * SketchObjectPy::trim (PyObject * args)
implementer for the trim() method
References getSketchObjectPtr(), Sketcher::SketchObject::trim(), and Base::VectorPy::Type.
Referenced by addGeometry(), fillet(), and staticCallback_trim().
Member Data Documentation
GetterSetter
PyGetSetDef SketchObjectPy::GetterSetter static
Attribute structure of SketchObjectPy.
Methods
PyMethodDef SketchObjectPy::Methods static
Methods structure of SketchObjectPy.
Type
PyTypeObject SketchObjectPy::Type static
Type structure of SketchObjectPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), and setCustomAttributes().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Sketcher/App/SketchObjectPy.h
Sources/FreeCAD/src/Mod/Sketcher/App/SketchObjectPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Sketcher/App/SketchObjectPy.cpp