FreeCAD: GCS::Arc Class Reference
GCS::Arc Class Reference
#include <Geo.h>
Public Member Functions
Arc ()
virtual Arc * Copy ()
virtual int PushOwnParams (VEC_pD &pvec)
virtual void ReconstructOnNewPvec (VEC_pD &pvec, int &cnt)
virtual ~Arc ()
Public Member Functions inherited from GCS::Circle
DeriVector2 CalculateNormal (Point &p, double *derivparam=0)
Circle ()
DeriVector2 Value (double u, double du, double *derivparam=0)
Value: returns point (vector) given the value of parameter.
virtual ~Circle ()
Public Member Functions inherited from GCS::Curve
virtual ~Curve ()
Public Attributes
Point end
double * endAngle
Point start
double * startAngle
Public Attributes inherited from GCS::Circle
Point center
double * rad
Constructor & Destructor Documentation
Arc()
GCS::Arc::Arc ()
References endAngle, GCS::Circle::rad, and startAngle.
Referenced by Copy().
~Arc()
virtual GCS::Arc::~Arc () virtual
Member Function Documentation
Copy()
Arc * GCS::Arc::Copy (void) virtual
Reimplemented from GCS::Circle.
References Arc().
PushOwnParams()
int GCS::Arc::PushOwnParams (VEC_pD & pvec) virtual
Reimplemented from GCS::Circle.
References endAngle, GCS::Circle::PushOwnParams(), and startAngle.
ReconstructOnNewPvec()
void GCS::Arc::ReconstructOnNewPvec (VEC_pD & pvec, int & cnt) virtual
Reimplemented from GCS::Circle.
References endAngle, GCS::Circle::ReconstructOnNewPvec(), and startAngle.
Member Data Documentation
end
Point GCS::Arc::end
endAngle
double* GCS::Arc::endAngle
Referenced by Arc(), PushOwnParams(), and ReconstructOnNewPvec().
start
Point GCS::Arc::start
Referenced by Sketcher::Sketch::addArc().
startAngle
double* GCS::Arc::startAngle
Referenced by Arc(), PushOwnParams(), and ReconstructOnNewPvec().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Geo.h
Sources/FreeCAD/src/Mod/Sketcher/App/planegcs/Geo.cpp