FreeCAD: ifc2x3 Namespace Reference
ifc2x3 Namespace Reference
Classes
class ifc2dcompositecurve
class ifcabsorbeddosemeasure
class ifcaccelerationmeasure
class ifcactionrequest
class ifcactionsourcetypeenum
class ifcactiontypeenum
class ifcactor
class ifcactorrole
class ifcactuatortype
class ifcactuatortypeenum
class ifcaddress
class ifcaddresstypeenum
class ifcaheadorbehind
class ifcairterminalboxtype
class ifcairterminalboxtypeenum
class ifcairterminaltype
class ifcairterminaltypeenum
class ifcairtoairheatrecoverytype
class ifcairtoairheatrecoverytypeenum
class ifcalarmtype
class ifcalarmtypeenum
class ifcamountofsubstancemeasure
class ifcanalysismodeltypeenum
class ifcanalysistheorytypeenum
class ifcangulardimension
class ifcangularvelocitymeasure
class ifcannotation
class ifcannotationcurveoccurrence
class ifcannotationfillarea
class ifcannotationfillareaoccurrence
class ifcannotationoccurrence
class ifcannotationsurface
class ifcannotationsurfaceoccurrence
class ifcannotationsymboloccurrence
class ifcannotationtextoccurrence
class ifcapplication
class ifcappliedvalue
class ifcappliedvaluerelationship
class ifcapproval
class ifcapprovalactorrelationship
class ifcapprovalpropertyrelationship
class ifcapprovalrelationship
class ifcarbitraryclosedprofiledef
class ifcarbitraryopenprofiledef
class ifcarbitraryprofiledefwithvoids
class ifcareameasure
class ifcarithmeticoperatorenum
class ifcassemblyplaceenum
class ifcasset
class ifcasymmetricishapeprofiledef
class ifcaxis1placement
class ifcaxis2placement2d
class ifcaxis2placement3d
class ifcbeam
class ifcbeamtype
class ifcbeamtypeenum
class ifcbenchmarkenum
class ifcbeziercurve
class ifcblobtexture
class ifcblock
class ifcboilertype
class ifcboilertypeenum
class ifcboolean
class ifcbooleanclippingresult
class ifcbooleanoperator
class ifcbooleanresult
class ifcboundarycondition
class ifcboundaryedgecondition
class ifcboundaryfacecondition
class ifcboundarynodecondition
class ifcboundarynodeconditionwarping
class ifcboundedcurve
class ifcboundedsurface
class ifcboundingbox
class ifcboxalignment
class ifcboxedhalfspace
class ifcbsplinecurve
class ifcbsplinecurveform
class ifcbuilding
class ifcbuildingelement
class ifcbuildingelementcomponent
class ifcbuildingelementpart
class ifcbuildingelementproxy
class ifcbuildingelementproxytype
class ifcbuildingelementproxytypeenum
class ifcbuildingelementtype
class ifcbuildingstorey
class ifccablecarrierfittingtype
class ifccablecarrierfittingtypeenum
class ifccablecarriersegmenttype
class ifccablecarriersegmenttypeenum
class ifccablesegmenttype
class ifccablesegmenttypeenum
class ifccalendardate
class ifccartesianpoint
class ifccartesiantransformationoperator
class ifccartesiantransformationoperator2d
class ifccartesiantransformationoperator2dnonuniform
class ifccartesiantransformationoperator3d
class ifccartesiantransformationoperator3dnonuniform
class ifccenterlineprofiledef
class ifcchamferedgefeature
class ifcchangeactionenum
class ifcchillertype
class ifcchillertypeenum
class ifccircle
class ifccirclehollowprofiledef
class ifccircleprofiledef
class ifcclassification
class ifcclassificationitem
class ifcclassificationitemrelationship
class ifcclassificationnotation
class ifcclassificationnotationfacet
class ifcclassificationreference
class ifcclosedshell
class ifccoiltype
class ifccoiltypeenum
class ifccolourrgb
class ifccolourspecification
class ifccolumn
class ifccolumntype
class ifccolumntypeenum
class ifccomplexproperty
class ifccompositecurve
class ifccompositecurvesegment
class ifccompositeprofiledef
class ifccompressortype
class ifccompressortypeenum
class ifccondensertype
class ifccondensertypeenum
class ifccondition
class ifcconditioncriterion
class ifcconic
class ifcconnectedfaceset
class ifcconnectioncurvegeometry
class ifcconnectiongeometry
class ifcconnectionpointeccentricity
class ifcconnectionpointgeometry
class ifcconnectionportgeometry
class ifcconnectionsurfacegeometry
class ifcconnectiontypeenum
class ifcconstraint
class ifcconstraintaggregationrelationship
class ifcconstraintclassificationrelationship
class ifcconstraintenum
class ifcconstraintrelationship
class ifcconstructionequipmentresource
class ifcconstructionmaterialresource
class ifcconstructionproductresource
class ifcconstructionresource
class ifccontextdependentmeasure
class ifccontextdependentunit
class ifccontrol
class ifccontrollertype
class ifccontrollertypeenum
class ifcconversionbasedunit
class ifccooledbeamtype
class ifccooledbeamtypeenum
class ifccoolingtowertype
class ifccoolingtowertypeenum
class ifccoordinateduniversaltimeoffset
class ifccostitem
class ifccostschedule
class ifccostscheduletypeenum
class ifccostvalue
class ifccountmeasure
class ifccovering
class ifccoveringtype
class ifccoveringtypeenum
class ifccranerailashapeprofiledef
class ifccranerailfshapeprofiledef
class ifccrewresource
class ifccsgprimitive3d
class ifccsgsolid
class ifccshapeprofiledef
class ifccurrencyenum
class ifccurrencyrelationship
class ifccurtainwall
class ifccurtainwalltype
class ifccurtainwalltypeenum
class ifccurvaturemeasure
class ifccurve
class ifccurveboundedplane
class ifccurvestyle
class ifccurvestylefont
class ifccurvestylefontandscaling
class ifccurvestylefontpattern
class ifcdampertype
class ifcdampertypeenum
class ifcdataoriginenum
class ifcdateandtime
class ifcdayinmonthnumber
class ifcdaylightsavinghour
class ifcdefinedsymbol
class ifcderivedprofiledef
class ifcderivedunit
class ifcderivedunitelement
class ifcderivedunitenum
class ifcdescriptivemeasure
class ifcdiameterdimension
class ifcdimensionalexponents
class ifcdimensioncalloutrelationship
class ifcdimensioncount
class ifcdimensioncurve
class ifcdimensioncurvedirectedcallout
class ifcdimensioncurveterminator
class ifcdimensionextentusage
class ifcdimensionpair
class ifcdirection
class ifcdirectionsenseenum
class ifcdiscreteaccessory
class ifcdiscreteaccessorytype
class ifcdistributionchamberelement
class ifcdistributionchamberelementtype
class ifcdistributionchamberelementtypeenum
class ifcdistributioncontrolelement
class ifcdistributioncontrolelementtype
class ifcdistributionelement
class ifcdistributionelementtype
class ifcdistributionflowelement
class ifcdistributionflowelementtype
class ifcdistributionport
class ifcdocumentconfidentialityenum
class ifcdocumentelectronicformat
class ifcdocumentinformation
class ifcdocumentinformationrelationship
class ifcdocumentreference
class ifcdocumentstatusenum
class ifcdoor
class ifcdoorliningproperties
class ifcdoorpaneloperationenum
class ifcdoorpanelpositionenum
class ifcdoorpanelproperties
class ifcdoorstyle
class ifcdoorstyleconstructionenum
class ifcdoorstyleoperationenum
class ifcdoseequivalentmeasure
class ifcdraughtingcallout
class ifcdraughtingcalloutrelationship
class ifcdraughtingpredefinedcolour
class ifcdraughtingpredefinedcurvefont
class ifcdraughtingpredefinedtextfont
class ifcductfittingtype
class ifcductfittingtypeenum
class ifcductsegmenttype
class ifcductsegmenttypeenum
class ifcductsilencertype
class ifcductsilencertypeenum
class ifcdynamicviscositymeasure
class ifcedge
class ifcedgecurve
class ifcedgefeature
class ifcedgeloop
class ifcelectricalbaseproperties
class ifcelectricalcircuit
class ifcelectricalelement
class ifcelectricappliancetype
class ifcelectricappliancetypeenum
class ifcelectriccapacitancemeasure
class ifcelectricchargemeasure
class ifcelectricconductancemeasure
class ifcelectriccurrentenum
class ifcelectriccurrentmeasure
class ifcelectricdistributionpoint
class ifcelectricdistributionpointfunctionenum
class ifcelectricflowstoragedevicetype
class ifcelectricflowstoragedevicetypeenum
class ifcelectricgeneratortype
class ifcelectricgeneratortypeenum
class ifcelectricheatertype
class ifcelectricheatertypeenum
class ifcelectricmotortype
class ifcelectricmotortypeenum
class ifcelectricresistancemeasure
class ifcelectrictimecontroltype
class ifcelectrictimecontroltypeenum
class ifcelectricvoltagemeasure
class ifcelement
class ifcelementarysurface
class ifcelementassembly
class ifcelementassemblytypeenum
class ifcelementcomponent
class ifcelementcomponenttype
class ifcelementcompositionenum
class ifcelementquantity
class ifcelementtype
class ifcellipse
class ifcellipseprofiledef
class ifcenergyconversiondevice
class ifcenergyconversiondevicetype
class ifcenergymeasure
class ifcenergyproperties
class ifcenergysequenceenum
class ifcenvironmentalimpactcategoryenum
class ifcenvironmentalimpactvalue
class ifcequipmentelement
class ifcequipmentstandard
class ifcevaporativecoolertype
class ifcevaporativecoolertypeenum
class ifcevaporatortype
class ifcevaporatortypeenum
class ifcextendedmaterialproperties
class ifcexternallydefinedhatchstyle
class ifcexternallydefinedsurfacestyle
class ifcexternallydefinedsymbol
class ifcexternallydefinedtextfont
class ifcexternalreference
class ifcextrudedareasolid
class ifcface
class ifcfacebasedsurfacemodel
class ifcfacebound
class ifcfaceouterbound
class ifcfacesurface
class ifcfacetedbrep
class ifcfacetedbrepwithvoids
class ifcfailureconnectioncondition
class ifcfantype
class ifcfantypeenum
class ifcfastener
class ifcfastenertype
class ifcfeatureelement
class ifcfeatureelementaddition
class ifcfeatureelementsubtraction
class ifcfillareastyle
class ifcfillareastylehatching
class ifcfillareastyletiles
class ifcfillareastyletilesymbolwithstyle
class ifcfiltertype
class ifcfiltertypeenum
class ifcfiresuppressionterminaltype
class ifcfiresuppressionterminaltypeenum
class ifcflowcontroller
class ifcflowcontrollertype
class ifcflowdirectionenum
class ifcflowfitting
class ifcflowfittingtype
class ifcflowinstrumenttype
class ifcflowinstrumenttypeenum
class ifcflowmetertype
class ifcflowmetertypeenum
class ifcflowmovingdevice
class ifcflowmovingdevicetype
class ifcflowsegment
class ifcflowsegmenttype
class ifcflowstoragedevice
class ifcflowstoragedevicetype
class ifcflowterminal
class ifcflowterminaltype
class ifcflowtreatmentdevice
class ifcflowtreatmentdevicetype
class ifcfluidflowproperties
class ifcfontstyle
class ifcfontvariant
class ifcfontweight
class ifcfooting
class ifcfootingtypeenum
class ifcforcemeasure
class ifcfrequencymeasure
class ifcfuelproperties
class ifcfurnishingelement
class ifcfurnishingelementtype
class ifcfurniturestandard
class ifcfurnituretype
class ifcgasterminaltype
class ifcgasterminaltypeenum
class ifcgeneralmaterialproperties
class ifcgeneralprofileproperties
class ifcgeometriccurveset
class ifcgeometricprojectionenum
class ifcgeometricrepresentationcontext
class ifcgeometricrepresentationitem
class ifcgeometricrepresentationsubcontext
class ifcgeometricset
class ifcgloballyuniqueid
class ifcglobalorlocalenum
class ifcgrid
class ifcgridaxis
class ifcgridplacement
class ifcgroup
class ifchalfspacesolid
class ifcheatexchangertype
class ifcheatexchangertypeenum
class ifcheatfluxdensitymeasure
class ifcheatingvaluemeasure
class ifchourinday
class ifchumidifiertype
class ifchumidifiertypeenum
class ifchygroscopicmaterialproperties
class ifcidentifier
class ifcilluminancemeasure
class ifcimagetexture
class ifcinductancemeasure
class ifcinteger
class ifcintegercountratemeasure
class ifcinternalorexternalenum
class ifcinventory
class ifcinventorytypeenum
class ifcionconcentrationmeasure
class ifcirregulartimeseries
class ifcirregulartimeseriesvalue
class ifcishapeprofiledef
class ifcisothermalmoisturecapacitymeasure
class ifcjunctionboxtype
class ifcjunctionboxtypeenum
class ifckinematicviscositymeasure
class ifclabel
class ifclaborresource
class ifclamptype
class ifclamptypeenum
class ifclayersetdirectionenum
class ifclengthmeasure
class ifclibraryinformation
class ifclibraryreference
class ifclightdistributioncurveenum
class ifclightdistributiondata
class ifclightemissionsourceenum
class ifclightfixturetype
class ifclightfixturetypeenum
class ifclightintensitydistribution
class ifclightsource
class ifclightsourceambient
class ifclightsourcedirectional
class ifclightsourcegoniometric
class ifclightsourcepositional
class ifclightsourcespot
class ifcline
class ifclineardimension
class ifclinearforcemeasure
class ifclinearmomentmeasure
class ifclinearstiffnessmeasure
class ifclinearvelocitymeasure
class ifcloadgrouptypeenum
class ifclocalplacement
class ifclocaltime
class ifclogical
class ifclogicaloperatorenum
class ifcloop
class ifclshapeprofiledef
class ifcluminousfluxmeasure
class ifcluminousintensitydistributionmeasure
class ifcluminousintensitymeasure
class ifcmagneticfluxdensitymeasure
class ifcmagneticfluxmeasure
class ifcmanifoldsolidbrep
class ifcmappeditem
class ifcmassdensitymeasure
class ifcmassflowratemeasure
class ifcmassmeasure
class ifcmassperlengthmeasure
class ifcmaterial
class ifcmaterialclassificationrelationship
class ifcmaterialdefinitionrepresentation
class ifcmateriallayer
class ifcmateriallayerset
class ifcmateriallayersetusage
class ifcmateriallist
class ifcmaterialproperties
class ifcmeasurewithunit
class ifcmechanicalconcretematerialproperties
class ifcmechanicalfastener
class ifcmechanicalfastenertype
class ifcmechanicalmaterialproperties
class ifcmechanicalsteelmaterialproperties
class ifcmember
class ifcmembertype
class ifcmembertypeenum
class ifcmetric
class ifcminuteinhour
class ifcmodulusofelasticitymeasure
class ifcmodulusoflinearsubgradereactionmeasure
class ifcmodulusofrotationalsubgradereactionmeasure
class ifcmodulusofsubgradereactionmeasure
class ifcmoisturediffusivitymeasure
class ifcmolecularweightmeasure
class ifcmomentofinertiameasure
class ifcmonetarymeasure
class ifcmonetaryunit
class ifcmonthinyearnumber
class ifcmotorconnectiontype
class ifcmotorconnectiontypeenum
class ifcmove
class ifcnamedunit
class ifcnormalisedratiomeasure
class ifcnullstyle
class ifcnumericmeasure
class ifcobject
class ifcobjectdefinition
class ifcobjective
class ifcobjectiveenum
class ifcobjectplacement
class ifcobjecttypeenum
class ifcoccupant
class ifcoccupanttypeenum
class ifcoffsetcurve2d
class ifcoffsetcurve3d
class ifconedirectionrepeatfactor
class ifcopeningelement
class ifcopenshell
class ifcopticalmaterialproperties
class ifcorderaction
class ifcorganization
class ifcorganizationrelationship
class ifcorientededge
class ifcoutlettype
class ifcoutlettypeenum
class ifcownerhistory
class ifcparameterizedprofiledef
class ifcparametervalue
class ifcpath
class ifcperformancehistory
class ifcpermeablecoveringoperationenum
class ifcpermeablecoveringproperties
class ifcpermit
class ifcperson
class ifcpersonandorganization
class ifcphmeasure
class ifcphysicalcomplexquantity
class ifcphysicalorvirtualenum
class ifcphysicalquantity
class ifcphysicalsimplequantity
class ifcpile
class ifcpileconstructionenum
class ifcpiletypeenum
class ifcpipefittingtype
class ifcpipefittingtypeenum
class ifcpipesegmenttype
class ifcpipesegmenttypeenum
class ifcpixeltexture
class ifcplacement
class ifcplanarbox
class ifcplanarextent
class ifcplanarforcemeasure
class ifcplane
class ifcplaneanglemeasure
class ifcplate
class ifcplatetype
class ifcplatetypeenum
class ifcpoint
class ifcpointoncurve
class ifcpointonsurface
class ifcpolygonalboundedhalfspace
class ifcpolyline
class ifcpolyloop
class ifcport
class ifcpositivelengthmeasure
class ifcpositiveplaneanglemeasure
class ifcpositiveratiomeasure
class ifcpostaladdress
class ifcpowermeasure
class ifcpredefinedcolour
class ifcpredefinedcurvefont
class ifcpredefineddimensionsymbol
class ifcpredefineditem
class ifcpredefinedpointmarkersymbol
class ifcpredefinedsymbol
class ifcpredefinedterminatorsymbol
class ifcpredefinedtextfont
class ifcpresentabletext
class ifcpresentationlayerassignment
class ifcpresentationlayerwithstyle
class ifcpresentationstyle
class ifcpresentationstyleassignment
class ifcpressuremeasure
class ifcprocedure
class ifcproceduretypeenum
class ifcprocess
class ifcproduct
class ifcproductdefinitionshape
class ifcproductrepresentation
class ifcproductsofcombustionproperties
class ifcprofiledef
class ifcprofileproperties
class ifcprofiletypeenum
class ifcproject
class ifcprojectedortruelengthenum
class ifcprojectioncurve
class ifcprojectionelement
class ifcprojectorder
class ifcprojectorderrecord
class ifcprojectorderrecordtypeenum
class ifcprojectordertypeenum
class ifcproperty
class ifcpropertyboundedvalue
class ifcpropertyconstraintrelationship
class ifcpropertydefinition
class ifcpropertydependencyrelationship
class ifcpropertyenumeratedvalue
class ifcpropertyenumeration
class ifcpropertylistvalue
class ifcpropertyreferencevalue
class ifcpropertyset
class ifcpropertysetdefinition
class ifcpropertysinglevalue
class ifcpropertysourceenum
class ifcpropertytablevalue
class ifcprotectivedevicetype
class ifcprotectivedevicetypeenum
class ifcproxy
class ifcpumptype
class ifcpumptypeenum
class ifcquantityarea
class ifcquantitycount
class ifcquantitylength
class ifcquantitytime
class ifcquantityvolume
class ifcquantityweight
class ifcradioactivitymeasure
class ifcradiusdimension
class ifcrailing
class ifcrailingtype
class ifcrailingtypeenum
class ifcramp
class ifcrampflight
class ifcrampflighttype
class ifcrampflighttypeenum
class ifcramptypeenum
class ifcratiomeasure
class ifcrationalbeziercurve
class ifcreal
class ifcrectanglehollowprofiledef
class ifcrectangleprofiledef
class ifcrectangularpyramid
class ifcrectangulartrimmedsurface
class ifcreferencesvaluedocument
class ifcreflectancemethodenum
class ifcregulartimeseries
class ifcreinforcementbarproperties
class ifcreinforcementdefinitionproperties
class ifcreinforcingbar
class ifcreinforcingbarroleenum
class ifcreinforcingbarsurfaceenum
class ifcreinforcingelement
class ifcreinforcingmesh
class ifcrelaggregates
class ifcrelassigns
class ifcrelassignstasks
class ifcrelassignstoactor
class ifcrelassignstocontrol
class ifcrelassignstogroup
class ifcrelassignstoprocess
class ifcrelassignstoproduct
class ifcrelassignstoprojectorder
class ifcrelassignstoresource
class ifcrelassociates
class ifcrelassociatesappliedvalue
class ifcrelassociatesapproval
class ifcrelassociatesclassification
class ifcrelassociatesconstraint
class ifcrelassociatesdocument
class ifcrelassociateslibrary
class ifcrelassociatesmaterial
class ifcrelassociatesprofileproperties
class ifcrelationship
class ifcrelaxation
class ifcrelconnects
class ifcrelconnectselements
class ifcrelconnectspathelements
class ifcrelconnectsports
class ifcrelconnectsporttoelement
class ifcrelconnectsstructuralactivity
class ifcrelconnectsstructuralelement
class ifcrelconnectsstructuralmember
class ifcrelconnectswitheccentricity
class ifcrelconnectswithrealizingelements
class ifcrelcontainedinspatialstructure
class ifcrelcoversbldgelements
class ifcrelcoversspaces
class ifcreldecomposes
class ifcreldefines
class ifcreldefinesbyproperties
class ifcreldefinesbytype
class ifcrelfillselement
class ifcrelflowcontrolelements
class ifcrelinteractionrequirements
class ifcrelnests
class ifcreloccupiesspaces
class ifcreloverridesproperties
class ifcrelprojectselement
class ifcrelreferencedinspatialstructure
class ifcrelschedulescostitems
class ifcrelsequence
class ifcrelservicesbuildings
class ifcrelspaceboundary
class ifcrelvoidselement
class ifcrepresentation
class ifcrepresentationcontext
class ifcrepresentationitem
class ifcrepresentationmap
class ifcresource
class ifcresourceconsumptionenum
class ifcrevolvedareasolid
class ifcribplatedirectionenum
class ifcribplateprofileproperties
class ifcrightcircularcone
class ifcrightcircularcylinder
class ifcroleenum
class ifcroof
class ifcrooftypeenum
class ifcroot
class ifcrotationalfrequencymeasure
class ifcrotationalmassmeasure
class ifcrotationalstiffnessmeasure
class ifcroundededgefeature
class ifcroundedrectangleprofiledef
class ifcsanitaryterminaltype
class ifcsanitaryterminaltypeenum
class ifcscheduletimecontrol
class ifcsecondinminute
class ifcsectionalareaintegralmeasure
class ifcsectionedspine
class ifcsectionmodulusmeasure
class ifcsectionproperties
class ifcsectionreinforcementproperties
class ifcsectiontypeenum
class ifcsensortype
class ifcsensortypeenum
class ifcsequenceenum
class ifcservicelife
class ifcservicelifefactor
class ifcservicelifefactortypeenum
class ifcservicelifetypeenum
class ifcshapeaspect
class ifcshapemodel
class ifcshaperepresentation
class ifcshearmodulusmeasure
class ifcshellbasedsurfacemodel
class ifcsimpleproperty
class ifcsiprefix
class ifcsite
class ifcsiunit
class ifcsiunitname
class ifcslab
class ifcslabtype
class ifcslabtypeenum
class ifcslippageconnectioncondition
class ifcsolidanglemeasure
class ifcsolidmodel
class ifcsoundpowermeasure
class ifcsoundpressuremeasure
class ifcsoundproperties
class ifcsoundscaleenum
class ifcsoundvalue
class ifcspace
class ifcspaceheatertype
class ifcspaceheatertypeenum
class ifcspaceprogram
class ifcspacethermalloadproperties
class ifcspacetype
class ifcspacetypeenum
class ifcspatialstructureelement
class ifcspatialstructureelementtype
class ifcspecificheatcapacitymeasure
class ifcspecularexponent
class ifcspecularroughness
class ifcsphere
class ifcstackterminaltype
class ifcstackterminaltypeenum
class ifcstair
class ifcstairflight
class ifcstairflighttype
class ifcstairflighttypeenum
class ifcstairtypeenum
class ifcstateenum
class ifcstructuralaction
class ifcstructuralactivity
class ifcstructuralanalysismodel
class ifcstructuralconnection
class ifcstructuralconnectioncondition
class ifcstructuralcurveconnection
class ifcstructuralcurvemember
class ifcstructuralcurvemembervarying
class ifcstructuralcurvetypeenum
class ifcstructuralitem
class ifcstructurallinearaction
class ifcstructurallinearactionvarying
class ifcstructuralload
class ifcstructuralloadgroup
class ifcstructuralloadlinearforce
class ifcstructuralloadplanarforce
class ifcstructuralloadsingledisplacement
class ifcstructuralloadsingledisplacementdistortion
class ifcstructuralloadsingleforce
class ifcstructuralloadsingleforcewarping
class ifcstructuralloadstatic
class ifcstructuralloadtemperature
class ifcstructuralmember
class ifcstructuralplanaraction
class ifcstructuralplanaractionvarying
class ifcstructuralpointaction
class ifcstructuralpointconnection
class ifcstructuralpointreaction
class ifcstructuralprofileproperties
class ifcstructuralreaction
class ifcstructuralresultgroup
class ifcstructuralsteelprofileproperties
class ifcstructuralsurfaceconnection
class ifcstructuralsurfacemember
class ifcstructuralsurfacemembervarying
class ifcstructuralsurfacetypeenum
class ifcstructureddimensioncallout
class ifcstyleditem
class ifcstyledrepresentation
class ifcstylemodel
class ifcsubcontractresource
class ifcsubedge
class ifcsurface
class ifcsurfacecurvesweptareasolid
class ifcsurfaceoflinearextrusion
class ifcsurfaceofrevolution
class ifcsurfaceside
class ifcsurfacestyle
class ifcsurfacestylelighting
class ifcsurfacestylerefraction
class ifcsurfacestylerendering
class ifcsurfacestyleshading
class ifcsurfacestylewithtextures
class ifcsurfacetexture
class ifcsurfacetextureenum
class ifcsweptareasolid
class ifcsweptdisksolid
class ifcsweptsurface
class ifcswitchingdevicetype
class ifcswitchingdevicetypeenum
class ifcsymbolstyle
class ifcsystem
class ifcsystemfurnitureelementtype
class ifctable
class ifctablerow
class ifctanktype
class ifctanktypeenum
class ifctask
class ifctelecomaddress
class ifctemperaturegradientmeasure
class ifctendon
class ifctendonanchor
class ifctendontypeenum
class ifcterminatorsymbol
class ifctext
class ifctextalignment
class ifctextdecoration
class ifctextfontname
class ifctextliteral
class ifctextliteralwithextent
class ifctextpath
class ifctextstyle
class ifctextstylefontmodel
class ifctextstylefordefinedfont
class ifctextstyletextmodel
class ifctextstylewithboxcharacteristics
class ifctexttransformation
class ifctexturecoordinate
class ifctexturecoordinategenerator
class ifctexturemap
class ifctexturevertex
class ifcthermaladmittancemeasure
class ifcthermalconductivitymeasure
class ifcthermalexpansioncoefficientmeasure
class ifcthermalloadsourceenum
class ifcthermalloadtypeenum
class ifcthermalmaterialproperties
class ifcthermalresistancemeasure
class ifcthermaltransmittancemeasure
class ifcthermodynamictemperaturemeasure
class ifctimemeasure
class ifctimeseries
class ifctimeseriesdatatypeenum
class ifctimeseriesreferencerelationship
class ifctimeseriesschedule
class ifctimeseriesscheduletypeenum
class ifctimeseriesvalue
class ifctimestamp
class ifctopologicalrepresentationitem
class ifctopologyrepresentation
class ifctorquemeasure
class ifctransformertype
class ifctransformertypeenum
class ifctransitioncode
class ifctransportelement
class ifctransportelementtype
class ifctransportelementtypeenum
class ifctrapeziumprofiledef
class ifctrimmedcurve
class ifctrimmingpreference
class ifctshapeprofiledef
class ifctubebundletype
class ifctubebundletypeenum
class ifctwodirectionrepeatfactor
class ifctypeobject
class ifctypeproduct
class ifcunitaryequipmenttype
class ifcunitaryequipmenttypeenum
class ifcunitassignment
class ifcunitenum
class ifcushapeprofiledef
class ifcvalvetype
class ifcvalvetypeenum
class ifcvaporpermeabilitymeasure
class ifcvector
class ifcvertex
class ifcvertexbasedtexturemap
class ifcvertexloop
class ifcvertexpoint
class ifcvibrationisolatortype
class ifcvibrationisolatortypeenum
class ifcvirtualelement
class ifcvirtualgridintersection
class ifcvolumemeasure
class ifcvolumetricflowratemeasure
class ifcwall
class ifcwallstandardcase
class ifcwalltype
class ifcwalltypeenum
class ifcwarpingconstantmeasure
class ifcwarpingmomentmeasure
class ifcwasteterminaltype
class ifcwasteterminaltypeenum
class ifcwaterproperties
class ifcwindow
class ifcwindowliningproperties
class ifcwindowpaneloperationenum
class ifcwindowpanelpositionenum
class ifcwindowpanelproperties
class ifcwindowstyle
class ifcwindowstyleconstructionenum
class ifcwindowstyleoperationenum
class ifcworkcontrol
class ifcworkcontroltypeenum
class ifcworkplan
class ifcworkschedule
class ifcyearnumber
class ifczone
class ifczshapeprofiledef
Functions
def ifcaddtobeginoflist (ascalar, alist)
FUNCTION ifcaddtobeginoflist #.
def ifcbaseaxis (dim, axis1, axis2, axis3)
FUNCTION ifcbaseaxis #.
def ifcbooleanchoose (b, choice1, choice2)
FUNCTION ifcbooleanchoose #.
def ifcbuild2axes (refdirection)
FUNCTION ifcbuild2axes #.
def ifcbuildaxes (axis, refdirection)
FUNCTION ifcbuildaxes #.
def ifccorrectdimensions (m, dim)
FUNCTION ifccorrectdimensions #.
def ifccorrectfillareastyle (styles)
FUNCTION ifccorrectfillareastyle #.
def ifccorrectlocalplacement (axisplacement, relplacement)
FUNCTION ifccorrectlocalplacement #.
def ifccorrectobjectassignment (constraint, objects)
FUNCTION ifccorrectobjectassignment #.
def ifccorrectunitassignment (units)
FUNCTION ifccorrectunitassignment #.
def ifccrossproduct (arg1, arg2)
FUNCTION ifccrossproduct #.
def ifccurvedim (curve)
FUNCTION ifccurvedim #.
def ifccurveweightspositive (b)
FUNCTION ifccurveweightspositive #.
def ifcderivedimensionalexponents (unitelements)
FUNCTION ifcderivedimensionalexponents #.
def ifcdimensionsforsiunit (n)
FUNCTION ifcdimensionsforsiunit #.
def ifcdotproduct (arg1, arg2)
FUNCTION ifcdotproduct #.
def ifcfirstprojaxis (zaxis, arg)
FUNCTION ifcfirstprojaxis #.
def ifcleapyear (year)
FUNCTION ifcleapyear #.
def ifclisttoarray (lis, low, u)
FUNCTION ifclisttoarray #.
def ifcloopheadtotail (aloop)
FUNCTION ifcloopheadtotail #.
def ifcmlstotalthickness (layerset)
FUNCTION ifcmlstotalthickness #.
def ifcnormalise (arg)
def ifcorthogonalcomplement (vec)
FUNCTION ifcorthogonalcomplement #.
def ifcpathheadtotail (apath)
FUNCTION ifcpathheadtotail #.
def ifcsameaxis2placement (ap1, ap2, epsilon)
FUNCTION ifcsameaxis2placement #.
def ifcsamecartesianpoint (cp1, cp2, epsilon)
FUNCTION ifcsamecartesianpoint #.
def ifcsamedirection (dir1, dir2, epsilon)
FUNCTION ifcsamedirection #.
def ifcsamevalidprecision (epsilon1, epsilon2)
FUNCTION ifcsamevalidprecision #.
def ifcsamevalue (value1, value2, epsilon)
FUNCTION ifcsamevalue #.
def ifcscalartimesvector (scalar, vec)
FUNCTION ifcscalartimesvector #.
def ifcsecondprojaxis (zaxis, xaxis, arg)
FUNCTION ifcsecondprojaxis #.
def ifcshaperepresentationtypes (reptype, items)
FUNCTION ifcshaperepresentationtypes #.
def ifctopologyrepresentationtypes (reptype, items)
FUNCTION ifctopologyrepresentationtypes #.
def ifcuniquepropertyname (properties)
FUNCTION ifcuniquepropertyname #.
def ifcvalidcalendardate (date)
FUNCTION ifcvalidcalendardate #.
def ifcvalidtime (time)
FUNCTION ifcvalidtime #.
def ifcvectordifference (arg1, arg2)
FUNCTION ifcvectordifference #.
def ifcvectorsum (arg1, arg2)
FUNCTION ifcvectorsum #.
Variables
ifcactorselect
ifcappliedvalueselect
ifcaxis2placement
ifcbooleanoperand
ifccharacterstyleselect
ifcclassificationnotationselect
ifccolour
ifccolourorfactor
ifccomplexnumber = ARRAY(1,2,'REAL', scope = schema_scope)
ifccompoundplaneanglemeasure = LIST(3,4,'INTEGER', scope = schema_scope)
ifcconditioncriterionselect
ifccsgselect
ifccurvefontorscaledcurvefontselect
ifccurveoredgecurve
ifccurvestylefontselect
ifcdatetimeselect
ifcdefinedsymbolselect
ifcderivedmeasurevalue
ifcdocumentselect
ifcdraughtingcalloutelement
ifcfillareastyletileshapeselect
ifcfillstyleselect
ifcgeometricsetselect
ifchatchlinedistanceselect
ifclayereditem
ifclibraryselect
ifclightdistributiondatasourceselect
ifcmaterialselect
ifcmeasurevalue
ifcmetricvalueselect
ifcobjectreferenceselect
ifcorientationselect
ifcpointorvertexpoint
ifcpresentationstyleselect
ifcrepresentationcontextsamewcs = Rule()
RULE ifcrepresentationcontextsamewcs #.
ifcshell
ifcsimplevalue
ifcsingleprojectinstance = Rule()
RULE ifcsingleprojectinstance #.
ifcsizeselect
ifcspecularhighlightselect
ifcstructuralactivityassignmentselect
ifcsurfaceorfacesurface
ifcsurfacestyleelementselect
ifcsymbolstyleselect
ifctextfontselect
ifctextstyleselect
ifctrimmingselect
ifcunit
ifcvalue
ifcvectorordirection
string schema_name = 'ifc2x3'
schema_scope = sys.modules[__name__]
Function Documentation
ifcaddtobeginoflist()
def ifc2x3.ifcaddtobeginoflist (ascalar, alist)
FUNCTION ifcaddtobeginoflist #.
        :param ascalar
        :type ascalar:(null)
        :param alist
        :type alist:(null)
Referenced by ifc2x3.ifcstructuralplanaractionvarying.varyingappliedloads(), ifc2x3.ifcstructurallinearactionvarying.varyingappliedloads(), and ifc2x3.ifcstructuralsurfacemembervarying.varyingthickness().
ifcbaseaxis()
def ifc2x3.ifcbaseaxis (dim, axis1, axis2, axis3)
FUNCTION ifcbaseaxis #.
        :param dim
        :type dim:INTEGER
        :param axis1
        :type axis1:ifcdirection
        :param axis2
        :type axis2:ifcdirection
        :param axis3
        :type axis3:ifcdirection
References ifcdotproduct(), ifcfirstprojaxis(), ifcnormalise(), ifcorthogonalcomplement(), and ifcsecondprojaxis().
Referenced by ifc2x3.ifccartesiantransformationoperator3d.u(), and ifc2x3.ifccartesiantransformationoperator2d.u().
ifcbooleanchoose()
def ifc2x3.ifcbooleanchoose (b, choice1, choice2)
FUNCTION ifcbooleanchoose #.
        :param b
        :type b:BOOLEAN
        :param choice1
        :type choice1:(null)
        :param choice2
        :type choice2:(null)
Referenced by ifc2x3.ifcorientededge.ifcedge_edgeend(), and ifc2x3.ifcorientededge.ifcedge_edgestart().
ifcbuild2axes()
def ifc2x3.ifcbuild2axes (refdirection)
FUNCTION ifcbuild2axes #.
        :param refdirection
        :type refdirection:ifcdirection
References ifcorthogonalcomplement().
Referenced by ifc2x3.ifcaxis2placement2d.p().
ifcbuildaxes()
def ifc2x3.ifcbuildaxes (axis, refdirection)
FUNCTION ifcbuildaxes #.
        :param axis
        :type axis:ifcdirection
        :param refdirection
        :type refdirection:ifcdirection
References ifccrossproduct(), ifcfirstprojaxis(), and ifcnormalise().
Referenced by ifc2x3.ifcaxis2placement3d.p().
ifccorrectdimensions()
def ifc2x3.ifccorrectdimensions (m, dim)
FUNCTION ifccorrectdimensions #.
        :param m
        :type m:ifcunitenum
        :param dim
        :type dim:ifcdimensionalexponents
Referenced by ifc2x3.ifcnamedunit.wr1().
ifccorrectfillareastyle()
def ifc2x3.ifccorrectfillareastyle (styles)
FUNCTION ifccorrectfillareastyle #.
        :param styles
        :type styles:(null)
Referenced by ifc2x3.ifcfillareastyle.wr13().
ifccorrectlocalplacement()
def ifc2x3.ifccorrectlocalplacement (axisplacement, relplacement)
FUNCTION ifccorrectlocalplacement #.
        :param axisplacement
        :type axisplacement:ifcaxis2placement
        :param relplacement
        :type relplacement:ifcobjectplacement
Referenced by ifc2x3.ifclocalplacement.wr21().
ifccorrectobjectassignment()
def ifc2x3.ifccorrectobjectassignment (constraint, objects)
FUNCTION ifccorrectobjectassignment #.
        :param constraint
        :type constraint:ifcobjecttypeenum
        :param objects
        :type objects:(null)
Referenced by ifc2x3.ifcrelassigns.wr1().
ifccorrectunitassignment()
def ifc2x3.ifccorrectunitassignment (units)
FUNCTION ifccorrectunitassignment #.
        :param units
        :type units:(null)
Referenced by ifc2x3.ifcunitassignment.wr01().
ifccrossproduct()
def ifc2x3.ifccrossproduct (arg1, arg2)
FUNCTION ifccrossproduct #.
        :param arg1
        :type arg1:ifcdirection
        :param arg2
        :type arg2:ifcdirection
References ifcnormalise().
Referenced by ifcbuildaxes(), ifcfirstprojaxis(), and ifc2x3.ifcaxis2placement3d.wr4().
ifccurvedim()
def ifc2x3.ifccurvedim (curve)
FUNCTION ifccurvedim #.
        :param curve
        :type curve:ifccurve
Referenced by ifc2x3.ifccurve.dim().
ifccurveweightspositive()
def ifc2x3.ifccurveweightspositive (b)
FUNCTION ifccurveweightspositive #.
        :param b
        :type b:ifcrationalbeziercurve
Referenced by ifc2x3.ifcrationalbeziercurve.wr2().
ifcderivedimensionalexponents()
def ifc2x3.ifcderivedimensionalexponents (unitelements)
FUNCTION ifcderivedimensionalexponents #.
        :param unitelements
        :type unitelements:(null)
Referenced by ifc2x3.ifcderivedunit.dimensions().
ifcdimensionsforsiunit()
def ifc2x3.ifcdimensionsforsiunit (n)
FUNCTION ifcdimensionsforsiunit #.
        :param n
        :type n:ifcsiunitname
Referenced by ifc2x3.ifcsiunit.ifcnamedunit_dimensions().
ifcdotproduct()
def ifc2x3.ifcdotproduct (arg1, arg2)
FUNCTION ifcdotproduct #.
        :param arg1
        :type arg1:ifcdirection
        :param arg2
        :type arg2:ifcdirection
References ifcnormalise().
Referenced by ifcbaseaxis(), ifcfirstprojaxis(), ifcsecondprojaxis(), and ifc2x3.ifcextrudedareasolid.wr31().
ifcfirstprojaxis()
def ifc2x3.ifcfirstprojaxis (zaxis, arg)
FUNCTION ifcfirstprojaxis #.
        :param zaxis
        :type zaxis:ifcdirection
        :param arg
        :type arg:ifcdirection
References ifccrossproduct(), ifcdotproduct(), ifcnormalise(), ifcscalartimesvector(), and ifcvectordifference().
Referenced by ifcbaseaxis(), and ifcbuildaxes().
ifcleapyear()
def ifc2x3.ifcleapyear (year)
FUNCTION ifcleapyear #.
        :param year
        :type year:INTEGER
Referenced by ifcvalidcalendardate().
ifclisttoarray()
def ifc2x3.ifclisttoarray (lis, low, u)
FUNCTION ifclisttoarray #.
        :param lis
        :type lis:(null)
        :param low
        :type low:INTEGER
        :param u
        :type u:INTEGER
Referenced by ifc2x3.ifcbsplinecurve.controlpoints(), and ifc2x3.ifcrationalbeziercurve.weights().
ifcloopheadtotail()
def ifc2x3.ifcloopheadtotail (aloop)
FUNCTION ifcloopheadtotail #.
        :param aloop
        :type aloop:ifcedgeloop
Referenced by ifc2x3.ifcedgeloop.wr2().
ifcmlstotalthickness()
def ifc2x3.ifcmlstotalthickness (layerset)
FUNCTION ifcmlstotalthickness #.
        :param layerset
        :type layerset:ifcmateriallayerset
Referenced by ifc2x3.ifcmateriallayerset.totalthickness().
ifcnormalise()
def ifc2x3.ifcnormalise (arg)
        :param arg
        :type arg:ifcvectorordirection
Referenced by ifcbaseaxis(), ifcbuildaxes(), ifccrossproduct(), ifcdotproduct(), ifcfirstprojaxis(), ifcscalartimesvector(), ifcsecondprojaxis(), ifcvectordifference(), ifcvectorsum(), and ifc2x3.ifcaxis1placement.z().
ifcorthogonalcomplement()
def ifc2x3.ifcorthogonalcomplement (vec)
FUNCTION ifcorthogonalcomplement #.
        :param vec
        :type vec:ifcdirection
Referenced by ifcbaseaxis(), and ifcbuild2axes().
ifcpathheadtotail()
def ifc2x3.ifcpathheadtotail (apath)
FUNCTION ifcpathheadtotail #.
        :param apath
        :type apath:ifcpath
Referenced by ifc2x3.ifcpath.wr1().
ifcsameaxis2placement()
def ifc2x3.ifcsameaxis2placement (ap1, ap2, epsilon)
FUNCTION ifcsameaxis2placement #.
        :param ap1
        :type ap1:ifcaxis2placement
        :param ap2
        :type ap2:ifcaxis2placement
        :param epsilon
        :type epsilon:REAL
References ifcsamecartesianpoint(), and ifcsamedirection().
ifcsamecartesianpoint()
def ifc2x3.ifcsamecartesianpoint (cp1, cp2, epsilon)
FUNCTION ifcsamecartesianpoint #.
        :param cp1
        :type cp1:ifccartesianpoint
        :param cp2
        :type cp2:ifccartesianpoint
        :param epsilon
        :type epsilon:REAL
References ifcsamevalue().
Referenced by ifcsameaxis2placement().
ifcsamedirection()
def ifc2x3.ifcsamedirection (dir1, dir2, epsilon)
FUNCTION ifcsamedirection #.
        :param dir1
        :type dir1:ifcdirection
        :param dir2
        :type dir2:ifcdirection
        :param epsilon
        :type epsilon:REAL
References ifcsamevalue().
Referenced by ifcsameaxis2placement().
ifcsamevalidprecision()
def ifc2x3.ifcsamevalidprecision (epsilon1, epsilon2)
FUNCTION ifcsamevalidprecision #.
        :param epsilon1
        :type epsilon1:REAL
        :param epsilon2
        :type epsilon2:REAL
ifcsamevalue()
def ifc2x3.ifcsamevalue (value1, value2, epsilon)
FUNCTION ifcsamevalue #.
        :param value1
        :type value1:REAL
        :param value2
        :type value2:REAL
        :param epsilon
        :type epsilon:REAL
Referenced by ifcsamecartesianpoint(), and ifcsamedirection().
ifcscalartimesvector()
def ifc2x3.ifcscalartimesvector (scalar, vec)
FUNCTION ifcscalartimesvector #.
        :param scalar
        :type scalar:REAL
        :param vec
        :type vec:ifcvectorordirection
References ifcnormalise().
Referenced by ifcfirstprojaxis(), and ifcsecondprojaxis().
ifcsecondprojaxis()
def ifc2x3.ifcsecondprojaxis (zaxis, xaxis, arg)
FUNCTION ifcsecondprojaxis #.
        :param zaxis
        :type zaxis:ifcdirection
        :param xaxis
        :type xaxis:ifcdirection
        :param arg
        :type arg:ifcdirection
References ifcdotproduct(), ifcnormalise(), ifcscalartimesvector(), and ifcvectordifference().
Referenced by ifcbaseaxis().
ifcshaperepresentationtypes()
def ifc2x3.ifcshaperepresentationtypes (reptype, items)
FUNCTION ifcshaperepresentationtypes #.
        :param reptype
        :type reptype:STRING
        :param items
        :type items:(null)
Referenced by ifc2x3.ifcshaperepresentation.wr24().
ifctopologyrepresentationtypes()
def ifc2x3.ifctopologyrepresentationtypes (reptype, items)
FUNCTION ifctopologyrepresentationtypes #.
        :param reptype
        :type reptype:STRING
        :param items
        :type items:(null)
Referenced by ifc2x3.ifctopologyrepresentation.wr23().
ifcuniquepropertyname()
def ifc2x3.ifcuniquepropertyname (properties)
FUNCTION ifcuniquepropertyname #.
        :param properties
        :type properties:(null)
Referenced by ifc2x3.ifccomplexproperty.wr22(), and ifc2x3.ifcpropertyset.wr32().
ifcvalidcalendardate()
def ifc2x3.ifcvalidcalendardate (date)
FUNCTION ifcvalidcalendardate #.
        :param date
        :type date:ifccalendardate
References ifcleapyear().
Referenced by ifc2x3.ifccalendardate.wr21().
ifcvalidtime()
def ifc2x3.ifcvalidtime (time)
FUNCTION ifcvalidtime #.
        :param time
        :type time:ifclocaltime
Referenced by ifc2x3.ifclocaltime.wr21().
ifcvectordifference()
def ifc2x3.ifcvectordifference (arg1, arg2)
FUNCTION ifcvectordifference #.
        :param arg1
        :type arg1:ifcvectorordirection
        :param arg2
        :type arg2:ifcvectorordirection
References ifcnormalise().
Referenced by ifcfirstprojaxis(), and ifcsecondprojaxis().
ifcvectorsum()
def ifc2x3.ifcvectorsum (arg1, arg2)
FUNCTION ifcvectorsum #.
        :param arg1
        :type arg1:ifcvectorordirection
        :param arg2
        :type arg2:ifcvectorordirection
References ifcnormalise().
Variable Documentation
ifcactorselect
ifc2x3.ifcactorselect
Initial value:
 =  SELECT(
         'ifcorganization',
         'ifcperson',
         'ifcpersonandorganization',
         scope = schema_scope)
Referenced by ifc2x3.ifcapprovalactorrelationship.actor(), ifc2x3.ifcconstraint.creatingactor(), ifc2x3.ifcdocumentinformation.documentowner(), ifc2x3.ifcinventory.jurisdiction(), ifc2x3.ifcasset.owner(), ifc2x3.ifccostschedule.preparedby(), ifc2x3.ifcsubcontractresource.subcontractor(), ifc2x3.ifccostschedule.submittedby(), ifc2x3.ifcactor.theactor(), and ifc2x3.ifcasset.user().
ifcappliedvalueselect
ifc2x3.ifcappliedvalueselect
Initial value:
 =  SELECT(
         'ifcratiomeasure',
         'ifcmeasurewithunit',
         'ifcmonetarymeasure',
         scope = schema_scope)
Referenced by ifc2x3.ifcappliedvalue.appliedvalue().
ifcaxis2placement
ifc2x3.ifcaxis2placement
Initial value:
 =  SELECT(
         'ifcaxis2placement2d',
         'ifcaxis2placement3d',
         scope = schema_scope)
Referenced by ifc2x3.ifcconnectionportgeometry.locationatrelatedelement(), ifc2x3.ifcconnectionportgeometry.locationatrelatingelement(), ifc2x3.ifcrepresentationmap.mappingorigin(), ifc2x3.ifcplanarbox.placement(), ifc2x3.ifctextliteral.placement(), ifc2x3.ifcconic.position(), ifc2x3.ifclocalplacement.relativeplacement(), and ifc2x3.ifcgeometricrepresentationcontext.worldcoordinatesystem().
ifcbooleanoperand
ifc2x3.ifcbooleanoperand
Initial value:
 =  SELECT(
         'ifcsolidmodel',
         'ifchalfspacesolid',
         'ifcbooleanresult',
         'ifccsgprimitive3d',
         scope = schema_scope)
Referenced by ifc2x3.ifcbooleanresult.firstoperand(), and ifc2x3.ifcbooleanresult.secondoperand().
ifccharacterstyleselect
ifc2x3.ifccharacterstyleselect
Initial value:
 =  SELECT(
         'ifctextstylefordefinedfont',
         scope = schema_scope)
Referenced by ifc2x3.ifctextstyle.textcharacterappearance().
ifcclassificationnotationselect
ifc2x3.ifcclassificationnotationselect
Initial value:
 =  SELECT(
         'ifcclassificationnotation',
         'ifcclassificationreference',
         scope = schema_scope)
Referenced by ifc2x3.ifcrelassociatesclassification.relatingclassification().
ifccolour
ifc2x3.ifccolour
Initial value:
 =  SELECT(
         'ifccolourspecification',
         'ifcpredefinedcolour',
         scope = schema_scope)
Referenced by ifc2x3.ifctextstylefordefinedfont.backgroundcolour(), ifc2x3.ifctextstylefordefinedfont.colour(), and ifc2x3.ifccurvestyle.curvecolour().
ifccolourorfactor
ifc2x3.ifccolourorfactor
Initial value:
 =  SELECT(
         'ifccolourrgb',
         'ifcnormalisedratiomeasure',
         scope = schema_scope)
Referenced by ifc2x3.ifcsurfacestylerendering.diffusecolour(), ifc2x3.ifcsurfacestylerendering.diffusetransmissioncolour(), ifc2x3.ifcsurfacestylerendering.reflectioncolour(), ifc2x3.ifcsurfacestylerendering.specularcolour(), and ifc2x3.ifcsurfacestylerendering.transmissioncolour().
ifccomplexnumber
ifc2x3.ifccomplexnumber = ARRAY(1,2,'REAL', scope = schema_scope)
ifccompoundplaneanglemeasure
ifc2x3.ifccompoundplaneanglemeasure = LIST(3,4,'INTEGER', scope = schema_scope)
ifcconditioncriterionselect
ifc2x3.ifcconditioncriterionselect
Initial value:
 =  SELECT(
         'ifclabel',
         'ifcmeasurewithunit',
         scope = schema_scope)
Referenced by ifc2x3.ifcconditioncriterion.criterion().
ifccsgselect
ifc2x3.ifccsgselect
Initial value:
 =  SELECT(
         'ifcbooleanresult',
         'ifccsgprimitive3d',
         scope = schema_scope)
Referenced by ifc2x3.ifccsgsolid.treerootexpression().
ifccurvefontorscaledcurvefontselect
ifc2x3.ifccurvefontorscaledcurvefontselect
Initial value:
 =  SELECT(
         'ifccurvestylefontselect',
         'ifccurvestylefontandscaling',
         scope = schema_scope)
Referenced by ifc2x3.ifccurvestyle.curvefont().
ifccurveoredgecurve
ifc2x3.ifccurveoredgecurve
Initial value:
 =  SELECT(
         'ifcboundedcurve',
         'ifcedgecurve',
         scope = schema_scope)
Referenced by ifc2x3.ifcconnectioncurvegeometry.curveonrelatedelement(), and ifc2x3.ifcconnectioncurvegeometry.curveonrelatingelement().
ifccurvestylefontselect
ifc2x3.ifccurvestylefontselect
Initial value:
 =  SELECT(
         'ifcpredefinedcurvefont',
         'ifccurvestylefont',
         scope = schema_scope)
Referenced by ifc2x3.ifccurvestylefontandscaling.curvefont().
ifcdatetimeselect
ifc2x3.ifcdatetimeselect
Initial value:
 =  SELECT(
         'ifccalendardate',
         'ifclocaltime',
         'ifcdateandtime',
         scope = schema_scope)
Referenced by ifc2x3.ifcscheduletimecontrol.actualfinish(), ifc2x3.ifcscheduletimecontrol.actualstart(), ifc2x3.ifcappliedvalue.applicabledate(), ifc2x3.ifcapproval.approvaldatetime(), ifc2x3.ifcworkcontrol.creationdate(), ifc2x3.ifcconstraint.creationtime(), ifc2x3.ifcconditioncriterion.criteriondatetime(), ifc2x3.ifcscheduletimecontrol.earlyfinish(), ifc2x3.ifcscheduletimecontrol.earlystart(), ifc2x3.ifctimeseries.endtime(), ifc2x3.ifcworkcontrol.finishtime(), ifc2x3.ifcappliedvalue.fixeduntildate(), ifc2x3.ifcscheduletimecontrol.latefinish(), ifc2x3.ifcscheduletimecontrol.latestart(), ifc2x3.ifcscheduletimecontrol.schedulefinish(), ifc2x3.ifcscheduletimecontrol.schedulestart(), ifc2x3.ifcworkcontrol.starttime(), ifc2x3.ifctimeseries.starttime(), ifc2x3.ifcscheduletimecontrol.statustime(), ifc2x3.ifccostschedule.submittedon(), ifc2x3.ifcirregulartimeseriesvalue.timestamp(), and ifc2x3.ifccostschedule.updatedate().
ifcdefinedsymbolselect
ifc2x3.ifcdefinedsymbolselect
Initial value:
 =  SELECT(
         'ifcpredefinedsymbol',
         'ifcexternallydefinedsymbol',
         scope = schema_scope)
Referenced by ifc2x3.ifcdefinedsymbol.definition().
ifcderivedmeasurevalue
ifc2x3.ifcderivedmeasurevalue
Referenced by ifc2x3.ifcfluidflowproperties.flowratesinglevalue(), and ifc2x3.ifcsoundvalue.soundlevelsinglevalue().
ifcdocumentselect
ifc2x3.ifcdocumentselect
Initial value:
 =  SELECT(
         'ifcdocumentreference',
         'ifcdocumentinformation',
         scope = schema_scope)
Referenced by ifc2x3.ifcreferencesvaluedocument.referenceddocument(), and ifc2x3.ifcrelassociatesdocument.relatingdocument().
ifcdraughtingcalloutelement
ifc2x3.ifcdraughtingcalloutelement
Initial value:
 =  SELECT(
         'ifcannotationcurveoccurrence',
         'ifcannotationtextoccurrence',
         'ifcannotationsymboloccurrence',
         scope = schema_scope)
ifcfillareastyletileshapeselect
ifc2x3.ifcfillareastyletileshapeselect
Initial value:
 =  SELECT(
         'ifcfillareastyletilesymbolwithstyle',
         scope = schema_scope)
ifcfillstyleselect
ifc2x3.ifcfillstyleselect
Initial value:
 =  SELECT(
         'ifcfillareastylehatching',
         'ifcfillareastyletiles',
         'ifccolour',
         'ifcexternallydefinedhatchstyle',
         scope = schema_scope)
ifcgeometricsetselect
ifc2x3.ifcgeometricsetselect
Initial value:
 =  SELECT(
         'ifcpoint',
         'ifccurve',
         'ifcsurface',
         scope = schema_scope)
ifchatchlinedistanceselect
ifc2x3.ifchatchlinedistanceselect
Initial value:
 =  SELECT(
         'ifconedirectionrepeatfactor',
         'ifcpositivelengthmeasure',
         scope = schema_scope)
Referenced by ifc2x3.ifcfillareastylehatching.startofnexthatchline().
ifclayereditem
ifc2x3.ifclayereditem
Initial value:
 =  SELECT(
         'ifcrepresentationitem',
         'ifcrepresentation',
         scope = schema_scope)
ifclibraryselect
ifc2x3.ifclibraryselect
Initial value:
 =  SELECT(
         'ifclibraryreference',
         'ifclibraryinformation',
         scope = schema_scope)
Referenced by ifc2x3.ifcrelassociateslibrary.relatinglibrary().
ifclightdistributiondatasourceselect
ifc2x3.ifclightdistributiondatasourceselect
Initial value:
 =  SELECT(
         'ifcexternalreference',
         'ifclightintensitydistribution',
         scope = schema_scope)
Referenced by ifc2x3.ifclightsourcegoniometric.lightdistributiondatasource().
ifcmaterialselect
ifc2x3.ifcmaterialselect
Initial value:
 =  SELECT(
         'ifcmaterial',
         'ifcmateriallist',
         'ifcmateriallayersetusage',
         'ifcmateriallayerset',
         'ifcmateriallayer',
         scope = schema_scope)
Referenced by ifc2x3.ifcrelassociatesmaterial.relatingmaterial().
ifcmeasurevalue
ifc2x3.ifcmeasurevalue
Initial value:
 =  SELECT(
         'ifcvolumemeasure',
         'ifctimemeasure',
         'ifcthermodynamictemperaturemeasure',
         'ifcsolidanglemeasure',
         'ifcpositiveratiomeasure',
         'ifcratiomeasure',
         'ifcpositiveplaneanglemeasure',
         'ifcplaneanglemeasure',
         'ifcparametervalue',
         'ifcnumericmeasure',
         'ifcmassmeasure',
         'ifcpositivelengthmeasure',
         'ifclengthmeasure',
         'ifcelectriccurrentmeasure',
         'ifcdescriptivemeasure',
         'ifccountmeasure',
         'ifccontextdependentmeasure',
         'ifcareameasure',
         'ifcamountofsubstancemeasure',
         'ifcluminousintensitymeasure',
         'ifcnormalisedratiomeasure',
         'ifccomplexnumber',
         scope = schema_scope)
Referenced by ifc2x3.ifcservicelifefactor.lowervalue(), ifc2x3.ifcservicelifefactor.mostusedvalue(), and ifc2x3.ifcservicelifefactor.uppervalue().
ifcmetricvalueselect
ifc2x3.ifcmetricvalueselect
Initial value:
 =  SELECT(
         'ifcdatetimeselect',
         'ifcmeasurewithunit',
         'ifctable',
         'ifctext',
         'ifctimeseries',
         'ifccostvalue',
         scope = schema_scope)
Referenced by ifc2x3.ifcmetric.datavalue().
ifcobjectreferenceselect
ifc2x3.ifcobjectreferenceselect
Initial value:
 =  SELECT(
         'ifcmaterial',
         'ifcperson',
         'ifcdateandtime',
         'ifcmateriallist',
         'ifcorganization',
         'ifccalendardate',
         'ifclocaltime',
         'ifcpersonandorganization',
         'ifcmateriallayer',
         'ifcexternalreference',
         'ifctimeseries',
         'ifcaddress',
         'ifcappliedvalue',
         scope = schema_scope)
Referenced by ifc2x3.ifcpropertyreferencevalue.propertyreference().
ifcorientationselect
ifc2x3.ifcorientationselect
Initial value:
 =  SELECT(
         'ifcplaneanglemeasure',
         'ifcdirection',
         scope = schema_scope)
Referenced by ifc2x3.ifcrelassociatesprofileproperties.profileorientation().
ifcpointorvertexpoint
ifc2x3.ifcpointorvertexpoint
Initial value:
 =  SELECT(
         'ifcpoint',
         'ifcvertexpoint',
         scope = schema_scope)
Referenced by ifc2x3.ifcconnectionpointgeometry.pointonrelatedelement(), and ifc2x3.ifcconnectionpointgeometry.pointonrelatingelement().
ifcpresentationstyleselect
ifc2x3.ifcpresentationstyleselect
Initial value:
 =  SELECT(
         'ifcnullstyle',
         'ifccurvestyle',
         'ifcsymbolstyle',
         'ifcfillareastyle',
         'ifctextstyle',
         'ifcsurfacestyle',
         scope = schema_scope)
ifcrepresentationcontextsamewcs
ifc2x3.ifcrepresentationcontextsamewcs = Rule()
RULE ifcrepresentationcontextsamewcs #.
ifcshell
ifc2x3.ifcshell
Initial value:
 =  SELECT(
         'ifcclosedshell',
         'ifcopenshell',
         scope = schema_scope)
ifcsimplevalue
ifc2x3.ifcsimplevalue
Initial value:
 =  SELECT(
         'ifcinteger',
         'ifcreal',
         'ifcboolean',
         'ifcidentifier',
         'ifctext',
         'ifclabel',
         'ifclogical',
         scope = schema_scope)
ifcsingleprojectinstance
ifc2x3.ifcsingleprojectinstance = Rule()
RULE ifcsingleprojectinstance #.
ifcsizeselect
ifc2x3.ifcsizeselect
Initial value:
 =  SELECT(
         'ifcratiomeasure',
         'ifclengthmeasure',
         'ifcdescriptivemeasure',
         'ifcpositivelengthmeasure',
         'ifcnormalisedratiomeasure',
         'ifcpositiveratiomeasure',
         scope = schema_scope)
Referenced by ifc2x3.ifctextstylewithboxcharacteristics.characterspacing(), ifc2x3.ifccurvestyle.curvewidth(), ifc2x3.ifctextstylefontmodel.fontsize(), ifc2x3.ifctextstyletextmodel.letterspacing(), ifc2x3.ifctextstyletextmodel.lineheight(), ifc2x3.ifctextstyletextmodel.textindent(), and ifc2x3.ifctextstyletextmodel.wordspacing().
ifcspecularhighlightselect
ifc2x3.ifcspecularhighlightselect
Initial value:
 =  SELECT(
         'ifcspecularexponent',
         'ifcspecularroughness',
         scope = schema_scope)
Referenced by ifc2x3.ifcsurfacestylerendering.specularhighlight().
ifcstructuralactivityassignmentselect
ifc2x3.ifcstructuralactivityassignmentselect
Initial value:
 =  SELECT(
         'ifcstructuralitem',
         'ifcelement',
         scope = schema_scope)
Referenced by ifc2x3.ifcrelconnectsstructuralactivity.relatingelement().
ifcsurfaceorfacesurface
ifc2x3.ifcsurfaceorfacesurface
Initial value:
 =  SELECT(
         'ifcsurface',
         'ifcfacesurface',
         'ifcfacebasedsurfacemodel',
         scope = schema_scope)
Referenced by ifc2x3.ifcconnectionsurfacegeometry.surfaceonrelatedelement(), and ifc2x3.ifcconnectionsurfacegeometry.surfaceonrelatingelement().
ifcsurfacestyleelementselect
ifc2x3.ifcsurfacestyleelementselect
Initial value:
 =  SELECT(
         'ifcsurfacestyleshading',
         'ifcsurfacestylelighting',
         'ifcsurfacestylewithtextures',
         'ifcexternallydefinedsurfacestyle',
         'ifcsurfacestylerefraction',
         scope = schema_scope)
ifcsymbolstyleselect
ifc2x3.ifcsymbolstyleselect
Initial value:
 =  SELECT(
         'ifccolour',
         scope = schema_scope)
Referenced by ifc2x3.ifcsymbolstyle.styleofsymbol().
ifctextfontselect
ifc2x3.ifctextfontselect
Initial value:
 =  SELECT(
         'ifcpredefinedtextfont',
         'ifcexternallydefinedtextfont',
         scope = schema_scope)
Referenced by ifc2x3.ifctextstyle.textfontstyle().
ifctextstyleselect
ifc2x3.ifctextstyleselect
Initial value:
 =  SELECT(
         'ifctextstylewithboxcharacteristics',
         'ifctextstyletextmodel',
         scope = schema_scope)
Referenced by ifc2x3.ifctextstyle.textstyle().
ifctrimmingselect
ifc2x3.ifctrimmingselect
Initial value:
 =  SELECT(
         'ifccartesianpoint',
         'ifcparametervalue',
         scope = schema_scope)
ifcunit
ifc2x3.ifcunit
Initial value:
 =  SELECT(
         'ifcderivedunit',
         'ifcnamedunit',
         'ifcmonetaryunit',
         scope = schema_scope)
Referenced by ifc2x3.ifcpropertytablevalue.definedunit(), ifc2x3.ifcpropertytablevalue.definingunit(), ifc2x3.ifcpropertyenumeration.unit(), ifc2x3.ifcpropertylistvalue.unit(), ifc2x3.ifcpropertyboundedvalue.unit(), ifc2x3.ifctimeseries.unit(), ifc2x3.ifcpropertysinglevalue.unit(), and ifc2x3.ifcmeasurewithunit.unitcomponent().
ifcvalue
ifc2x3.ifcvalue
Initial value:
 =  SELECT(
         'ifcmeasurevalue',
         'ifcsimplevalue',
         'ifcderivedmeasurevalue',
         scope = schema_scope)
Referenced by ifc2x3.ifcpropertyboundedvalue.lowerboundvalue(), ifc2x3.ifcpropertysinglevalue.nominalvalue(), ifc2x3.ifcpropertyboundedvalue.upperboundvalue(), and ifc2x3.ifcmeasurewithunit.valuecomponent().
ifcvectorordirection
ifc2x3.ifcvectorordirection
Initial value:
 =  SELECT(
         'ifcdirection',
         'ifcvector',
         scope = schema_scope)
schema_name
string ifc2x3.schema_name = 'ifc2x3'
schema_scope
ifc2x3.schema_scope = sys.modules[__name__]