FreeCAD: Mod.Show.SceneDetails.ObjectClipPlane Namespace Reference
Mod.Show.SceneDetails.ObjectClipPlane Namespace Reference
Classes
class ObjectClipPlane
Functions
def clipPlane (obj, enable, placement=None, offset=0, tv=None)
def getClipPlaneNode (viewprovider, make_if_missing=True)
def placement2plane (placement, offset)
Function Documentation
clipPlane()
def Mod.Show.SceneDetails.ObjectClipPlane.clipPlane (obj, enable, placement = None, offset = 0, tv = None)
getClipPlaneNode()
def Mod.Show.SceneDetails.ObjectClipPlane.getClipPlaneNode (viewprovider, make_if_missing = True)
Referenced by Mod.Show.SceneDetails.ObjectClipPlane.ObjectClipPlane.apply_data(), and Mod.Show.SceneDetails.ObjectClipPlane.ObjectClipPlane.scene_value().
placement2plane()
def Mod.Show.SceneDetails.ObjectClipPlane.placement2plane (placement, offset)
returns tuple (normal, D) for making coin plane.
Referenced by Mod.Show.SceneDetails.ObjectClipPlane.ObjectClipPlane.val().