FreeCAD: Gui::NS::Event Class Reference
Gui::NS::Event Class Reference
Classes
struct Flags
Public Types
enum {
BUTTON1DOWN = 0x00000100, BUTTON2DOWN = 0x00000001, BUTTON3DOWN = 0x00000010, CTRLDOWN = 0x00100000,
SHIFTDOWN = 0x01000000, ALTDOWN = 0x00010000, MASKBUTTONS = BUTTON1DOWN | BUTTON2DOWN | BUTTON3DOWN, MASKMODIFIERS = CTRLDOWN | SHIFTDOWN | ALTDOWN
}
Public Member Functions
const SoGestureEvent * asGestureEvent () const
const SoKeyboardEvent * asKeyboardEvent () const
const SoLocation2Event * asLocation2Event () const
const SoMouseButtonEvent * asMouseButtonEvent () const
Event ()
bool isGestureActive () const
bool isGestureEvent () const
bool isKeyboardEvent () const
bool isLocation2Event () const
bool isMotion3Event () const
bool isMouseButtonEvent () const
bool isPress (int button_index) const
bool isRelease (int button_index) const
unsigned int kbdstate () const
void log () const
unsigned int mbstate () const
virtual ~Event ()
Public Attributes
std::shared_ptr< Flags > flags
const SoEvent * inventor_event
unsigned int modifiers
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
BUTTON1DOWN
BUTTON2DOWN
BUTTON3DOWN
CTRLDOWN
SHIFTDOWN
ALTDOWN
MASKBUTTONS
MASKMODIFIERS
Constructor & Destructor Documentation
Event()
Gui::NS::Event::Event ()
~Event()
virtual Gui::NS::Event::~Event () virtual
Member Function Documentation
asGestureEvent()
const SoGestureEvent* Gui::NS::Event::asGestureEvent () const
References inventor_event.
Referenced by isGestureActive(), log(), and Gui::NS::GestureState::react().
asKeyboardEvent()
const SoKeyboardEvent* Gui::NS::Event::asKeyboardEvent () const
References inventor_event.
Referenced by Gui::NS::IdleState::react().
asLocation2Event()
const SoLocation2Event* Gui::NS::Event::asLocation2Event () const
References inventor_event.
asMouseButtonEvent()
const SoMouseButtonEvent* Gui::NS::Event::asMouseButtonEvent () const
References inventor_event.
Referenced by isPress(), isRelease(), Gui::GestureNavigationStyle::EventQueue::post(), and Gui::GestureNavigationStyle::processSoEvent().
isGestureActive()
bool Gui::NS::Event::isGestureActive () const
References asGestureEvent(), isGestureEvent(), SoGestureEvent::SbGSStart, and SoGestureEvent::SbGSUpdate.
Referenced by Gui::NS::IdleState::react(), Gui::NS::AwaitingMoveState::react(), and Gui::NS::AwaitingReleaseState::react().
isGestureEvent()
bool Gui::NS::Event::isGestureEvent () const
References inventor_event.
Referenced by isGestureActive(), log(), Gui::GestureNavigationStyle::processSoEvent(), Gui::NS::IdleState::react(), and Gui::NS::GestureState::react().
isKeyboardEvent()
bool Gui::NS::Event::isKeyboardEvent () const
References inventor_event.
Referenced by Gui::NS::IdleState::react().
isLocation2Event()
bool Gui::NS::Event::isLocation2Event () const
References inventor_event.
Referenced by Gui::NS::AwaitingMoveState::react(), Gui::NS::RotateState::react(), Gui::NS::PanState::react(), Gui::NS::StickyPanState::react(), Gui::NS::TiltState::react(), Gui::NS::GestureState::react(), and Gui::NS::AwaitingReleaseState::react().
isMotion3Event()
bool Gui::NS::Event::isMotion3Event () const
References inventor_event.
Referenced by Gui::NS::IdleState::react().
isMouseButtonEvent()
bool Gui::NS::Event::isMouseButtonEvent () const
References inventor_event.
Referenced by isPress(), isRelease(), log(), Gui::GestureNavigationStyle::processSoEvent(), Gui::NS::IdleState::react(), Gui::NS::AwaitingMoveState::react(), Gui::NS::RotateState::react(), Gui::NS::PanState::react(), Gui::NS::StickyPanState::react(), Gui::NS::TiltState::react(), Gui::NS::GestureState::react(), Gui::NS::AwaitingReleaseState::react(), and Gui::NS::InteractState::react().
isPress()
bool Gui::NS::Event::isPress (int button_index) const
References asMouseButtonEvent(), and isMouseButtonEvent().
Referenced by log(), Gui::NS::IdleState::react(), Gui::NS::AwaitingMoveState::react(), and Gui::NS::AwaitingReleaseState::react().
isRelease()
bool Gui::NS::Event::isRelease (int button_index) const
References asMouseButtonEvent(), and isMouseButtonEvent().
Referenced by log(), Gui::GestureNavigationStyle::processSoEvent(), Gui::NS::AwaitingMoveState::react(), Gui::NS::StickyPanState::react(), and Gui::NS::AwaitingReleaseState::react().
kbdstate()
unsigned int Gui::NS::Event::kbdstate () const
References MASKMODIFIERS, and modifiers.
log()
void Gui::NS::Event::log () const
References asGestureEvent(), Base::Console(), inventor_event, isGestureEvent(), isMouseButtonEvent(), isPress(), isRelease(), Base::ConsoleSingleton::Log(), modifiers, SoGestureEvent::SbGSEnd, SoGestureEvent::SbGSStart, and SoGestureEvent::SbGSUpdate.
Referenced by Gui::GestureNavigationStyle::EventQueue::post(), and Gui::NS::NaviMachine::processEvent().
mbstate()
unsigned int Gui::NS::Event::mbstate () const
References MASKBUTTONS, and modifiers.
Referenced by Gui::NS::IdleState::react(), Gui::NS::AwaitingMoveState::react(), Gui::NS::RotateState::react(), Gui::NS::PanState::react(), Gui::NS::TiltState::react(), Gui::NS::GestureState::react(), Gui::NS::AwaitingReleaseState::react(), and Gui::NS::InteractState::react().
Member Data Documentation
flags
std::shared_ptr<Flags> Gui::NS::Event::flags
Referenced by Gui::GestureNavigationStyle::EventQueue::post(), Gui::GestureNavigationStyle::processSoEvent(), Gui::NS::IdleState::react(), Gui::NS::AwaitingMoveState::react(), Gui::NS::RotateState::react(), Gui::NS::PanState::react(), Gui::NS::StickyPanState::react(), Gui::NS::TiltState::react(), Gui::NS::GestureState::react(), Gui::NS::AwaitingReleaseState::react(), and Gui::NS::InteractState::react().
inventor_event
const SoEvent* Gui::NS::Event::inventor_event
Referenced by asGestureEvent(), asKeyboardEvent(), asLocation2Event(), asMouseButtonEvent(), isGestureEvent(), isKeyboardEvent(), isLocation2Event(), isMotion3Event(), isMouseButtonEvent(), log(), Gui::GestureNavigationStyle::processSoEvent(), Gui::NS::IdleState::react(), Gui::NS::AwaitingMoveState::react(), Gui::NS::RotateState::react(), Gui::NS::PanState::react(), Gui::NS::StickyPanState::react(), Gui::NS::TiltState::react(), and Gui::NS::GestureState::react().
modifiers
unsigned int Gui::NS::Event::modifiers
Referenced by kbdstate(), log(), mbstate(), Gui::GestureNavigationStyle::processSoEvent(), and Gui::NS::AwaitingMoveState::react().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/GestureNavigationStyle.cpp