FreeCAD: Gui::Dialog::Ui_DlgRevertToBackupConfig Class Reference
Gui::Dialog::Ui_DlgRevertToBackupConfig Class Reference
#include <ui_DlgRevertToBackupConfig.h>
Public Member Functions
void retranslateUi (QDialog *Gui__Dialog__DlgRevertToBackupConfig)
void setupUi (QDialog *Gui__Dialog__DlgRevertToBackupConfig)
Public Attributes
QDialogButtonBox * buttonBox
QLabel * label
QLabel * label_2
QListWidget * listWidget
QVBoxLayout * verticalLayout
QSpacerItem * verticalSpacer
Member Function Documentation
retranslateUi()
void Gui::Dialog::Ui_DlgRevertToBackupConfig::retranslateUi (QDialog * Gui__Dialog__DlgRevertToBackupConfig)
References label_2, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::Dialog::Ui_DlgRevertToBackupConfig::setupUi (QDialog * Gui__Dialog__DlgRevertToBackupConfig)
References buttonBox, draftgeoutils.intersections::connect(), label_2, listWidget, retranslateUi(), verticalLayout, and verticalSpacer.
Member Data Documentation
buttonBox
QDialogButtonBox* Gui::Dialog::Ui_DlgRevertToBackupConfig::buttonBox
Referenced by PathScripts.PathGetPoint.TaskPanel::getPoint(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::modifyStandardButtons(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::pageDirtyChanged(), PathScripts.PathGetPoint.TaskPanel::pointFinish(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setClean(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setDirty(), and setupUi().
label
QLabel* Gui::Dialog::Ui_DlgRevertToBackupConfig::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
label_2
QLabel* Gui::Dialog::Ui_DlgRevertToBackupConfig::label_2
Referenced by retranslateUi(), and setupUi().
listWidget
QListWidget* Gui::Dialog::Ui_DlgRevertToBackupConfig::listWidget
Referenced by setupUi().
verticalLayout
QVBoxLayout* Gui::Dialog::Ui_DlgRevertToBackupConfig::verticalLayout
Referenced by setupUi().
verticalSpacer
QSpacerItem* Gui::Dialog::Ui_DlgRevertToBackupConfig::verticalSpacer
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_DlgRevertToBackupConfig.h