FreeCAD: Gui::UiLoader Class Reference
Gui::UiLoader Class Reference
The UiLoader class provides the abitlity to use the widget factory framework of FreeCAD within the framework provided by Qt.
#include <WidgetFactory.h>
Public Member Functions
QWidget * createWidget (const QString &className, QWidget *parent=0, const QString &name=QString())
Creates a widget of the type className with the parent parent.
UiLoader (QObject *parent=0)
virtual ~UiLoader ()
Detailed Description
The UiLoader class provides the abitlity to use the widget factory framework of FreeCAD within the framework provided by Qt.
This class extends QUiLoader by the creation of FreeCAD specific widgets.
Author
Werner Mayer
Constructor & Destructor Documentation
UiLoader()
UiLoader::UiLoader (QObject * parent = 0)
~UiLoader()
UiLoader::~UiLoader () virtual
Member Function Documentation
createWidget()
QWidget * UiLoader::createWidget (const QString & className, QWidget * parent = 0, const QString & name = QString())
Creates a widget of the type className with the parent parent.
For more details see the documentation to QWidgetFactory.
References Gui::WidgetFactoryInst::createWidget(), and Gui::WidgetFactory().
Referenced by Gui::UiLoaderPy::createWidget().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/WidgetFactory.h
Sources/FreeCAD/src/Gui/WidgetFactory.cpp