FreeCAD: Gui::FileIconProvider Class Reference
Gui::FileIconProvider Class Reference
The FileIconProvider class provides icons for FileDialog to use.
#include <FileDialog.h>
Public Member Functions
FileIconProvider ()
Constructs an empty file icon provider called name, with the parent parent.
QIcon icon (const QFileInfo &info) const
QIcon icon (IconType type) const
QString type (const QFileInfo &info) const
~FileIconProvider ()
Detailed Description
The FileIconProvider class provides icons for FileDialog to use.
Author
Werner Mayer
Constructor & Destructor Documentation
FileIconProvider()
FileIconProvider::FileIconProvider ()
Constructs an empty file icon provider called name, with the parent parent.
~FileIconProvider()
FileIconProvider::~FileIconProvider ()
Member Function Documentation
icon() [1/2]
QIcon FileIconProvider::icon (const QFileInfo & info) const
References icon().
Referenced by addonmanager_macro.Macro::clean_icon(), addonmanager_macro.Macro::fill_details_from_wiki(), PathScripts.PathIconViewProvider.ViewProvider::getIcon(), PathScripts.PathOpGui.TaskPanelPage::getIcon(), addonmanager_macro.Macro::install(), addonmanager_macro.Macro::parse_wiki_page_for_icon(), and addonmanager_macro.Macro::remove().
icon() [2/2]
QIcon FileIconProvider::icon (IconType type) const
Referenced by addonmanager_macro.Macro::clean_icon(), addonmanager_macro.Macro::fill_details_from_wiki(), PathScripts.PathIconViewProvider.ViewProvider::getIcon(), PathScripts.PathOpGui.TaskPanelPage::getIcon(), icon(), addonmanager_macro.Macro::install(), addonmanager_macro.Macro::parse_wiki_page_for_icon(), and addonmanager_macro.Macro::remove().
type()
QString FileIconProvider::type (const QFileInfo & info) const
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/FileDialog.h
FreeCAD/src/Gui/FileDialog.cpp