FreeCAD: TechDrawGui::QGCustomBorder Class Reference
TechDrawGui::QGCustomBorder Class Reference
#include <QGCustomBorder.h>
Public Types
enum { Type = QGraphicsItem::UserType + 136 }
Public Member Functions
virtual void centerAt (double cX, double cY)
virtual void centerAt (QPointF centerPos)
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr)
QGCustomBorder (void)
int type () const
~QGCustomBorder ()
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGCustomBorder()
QGCustomBorder::QGCustomBorder (void) explicit
~QGCustomBorder()
TechDrawGui::QGCustomBorder::~QGCustomBorder ()
Member Function Documentation
centerAt() [1/2]
void QGCustomBorder::centerAt (double cX, double cY) virtual
centerAt() [2/2]
void QGCustomBorder::centerAt (QPointF centerPos) virtual
References centerAt().
Referenced by centerAt().
paint()
void QGCustomBorder::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) virtual
type()
int TechDrawGui::QGCustomBorder::type () const
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/QGCustomBorder.h
FreeCAD/src/Mod/TechDraw/Gui/QGCustomBorder.cpp