FreeCAD: Gui::Dialog::PropertyPage Class Reference
Gui::Dialog::PropertyPage Class Reference abstract
Base class for property pages.
#include <PropertyPage.h>
Public Member Functions
bool isModified ()
Returns whether the page was modified or not.
void onApply ()
Applies all changes calling apply() and resets the modified state.
void onCancel ()
Discards all changes calling cancel() and resets the modified state.
void onReset ()
Resets to the default values.
PropertyPage (QWidget *parent=nullptr)
Construction.
void setModified (bool b)
Sets the page to be modified.
virtual ~PropertyPage ()
Destruction.
Protected Slots
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Protected Member Functions
virtual void apply ()
Applies all changes.
virtual void cancel ()
Discards all changes.
virtual void reset ()
Resets to the default values.
Detailed Description
Base class for property pages.
Author
Werner Mayer
Constructor & Destructor Documentation
PropertyPage()
PropertyPage::PropertyPage (QWidget * parent = nullptr)
Construction.
~PropertyPage()
PropertyPage::~PropertyPage () virtual
Destruction.
Member Function Documentation
apply()
void PropertyPage::apply () protected virtual
Applies all changes.
Reimplement this in your subclasses.
Referenced by onApply().
cancel()
void PropertyPage::cancel (void) protected virtual
Discards all changes.
Reimplement this in your subclasses.
Referenced by DraftGui.DraftToolBar::finish(), DraftGui.DraftToolBar::offUi(), onCancel(), and DraftGui.DraftToolBar::pointUi().
isModified()
bool PropertyPage::isModified ()
Returns whether the page was modified or not.
Referenced by onApply(), and onCancel().
loadSettings
virtual void Gui::Dialog::PropertyPage::loadSettings () protected pure virtual slot
onApply()
void PropertyPage::onApply ()
Applies all changes calling apply() and resets the modified state.
References apply(), isModified(), and setModified().
onCancel()
void PropertyPage::onCancel ()
Discards all changes calling cancel() and resets the modified state.
References cancel(), isModified(), and setModified().
onReset()
void PropertyPage::onReset ()
Resets to the default values.
References reset().
reset()
void PropertyPage::reset () protected virtual
Resets to the default values.
Reimplement this in your subclasses.
Referenced by onReset(), and draftguitools.gui_trackers.gridTracker::set().
saveSettings
virtual void Gui::Dialog::PropertyPage::saveSettings () protected pure virtual slot
setModified()
void PropertyPage::setModified (bool b)
Sets the page to be modified.
Referenced by onApply(), and onCancel().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/PropertyPage.h
FreeCAD/src/Gui/PropertyPage.cpp