FreeCAD: AdaptivePath::Adaptive2d Class Reference
AdaptivePath::Adaptive2d Class Reference
#include <Adaptive.hpp>
Public Member Functions
Adaptive2d ()
std::list< AdaptiveOutput > Execute (const DPaths &stockPaths, const DPaths &paths, std::function< bool(TPaths)> progressCallbackFn)
Public Attributes
bool forceInsideOut = true
double helixRampDiameter = 0
double keepToolDownDistRatio = 3.0
OperationType opType = OperationType::otClearingInside
double stepOverFactor = 0.2
double stockToLeave = 0
double tolerance = 0.1
double toolDiameter = 5
Friends
class EngagePoint
Constructor & Destructor Documentation
Adaptive2d()
AdaptivePath::Adaptive2d::Adaptive2d ()
Member Function Documentation
Execute()
std::list< AdaptiveOutput > AdaptivePath::Adaptive2d::Execute (const DPaths & stockPaths, const DPaths & paths, std::function< bool(TPaths)> progressCallbackFn)
tool bounds
offset back outwards - corner rounding
References ClipperLib::ClipperOffset::AddPath(), ClipperLib::ClipperBase::AddPath(), ClipperLib::ClipperOffset::AddPaths(), ClipperLib::ClipperBase::AddPaths(), AdaptivePath::appendDirectChildPaths(), AdaptivePath::CleanPath(), ClipperLib::ClipperBase::Clear(), ClipperLib::ClipperOffset::Clear(), AdaptivePath::ConnectPaths(), AdaptivePath::DeduplicatePaths(), ClipperLib::Clipper::Execute(), ClipperLib::ClipperOffset::Execute(), AdaptivePath::getPathNestingLevel(), draftfunctions.offset::offset(), ClipperLib::ReversePaths(), ClipperLib::SimplifyPolygons(), draftutils.utils::tolerance(), and ClipperLib::TranslatePath().
Referenced by PathScripts.PathJobCmd.CommandJobCreate::Activated(), and PathScripts.PathJobCmd.CommandJobTemplateExport::SaveDialog().
Friends And Related Function Documentation
EngagePoint
friend class EngagePoint friend
Member Data Documentation
forceInsideOut
bool AdaptivePath::Adaptive2d::forceInsideOut = true
helixRampDiameter
double AdaptivePath::Adaptive2d::helixRampDiameter = 0
keepToolDownDistRatio
double AdaptivePath::Adaptive2d::keepToolDownDistRatio = 3.0
opType
OperationType AdaptivePath::Adaptive2d::opType = OperationType::otClearingInside
stepOverFactor
double AdaptivePath::Adaptive2d::stepOverFactor = 0.2
stockToLeave
double AdaptivePath::Adaptive2d::stockToLeave = 0
tolerance
double AdaptivePath::Adaptive2d::tolerance = 0.1
toolDiameter
double AdaptivePath::Adaptive2d::toolDiameter = 5
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Path/libarea/Adaptive.hpp
Sources/FreeCAD/src/Mod/Path/libarea/Adaptive.cpp