FreeCAD: ifc4 Namespace Reference
ifc4 Namespace Reference
Classes
class ifcabsorbeddosemeasure
class ifcaccelerationmeasure
class ifcactionrequest
class ifcactionrequesttypeenum
class ifcactionsourcetypeenum
class ifcactiontypeenum
class ifcactor
class ifcactorrole
class ifcactuator
class ifcactuatortype
class ifcactuatortypeenum
class ifcaddress
class ifcaddresstypeenum
class ifcadvancedbrep
class ifcadvancedbrepwithvoids
class ifcadvancedface
class ifcairterminal
class ifcairterminalbox
class ifcairterminalboxtype
class ifcairterminalboxtypeenum
class ifcairterminaltype
class ifcairterminaltypeenum
class ifcairtoairheatrecovery
class ifcairtoairheatrecoverytype
class ifcairtoairheatrecoverytypeenum
class ifcalarm
class ifcalarmtype
class ifcalarmtypeenum
class ifcamountofsubstancemeasure
class ifcanalysismodeltypeenum
class ifcanalysistheorytypeenum
class ifcangularvelocitymeasure
class ifcannotation
class ifcannotationfillarea
class ifcapplication
class ifcappliedvalue
class ifcapproval
class ifcapprovalrelationship
class ifcarbitraryclosedprofiledef
class ifcarbitraryopenprofiledef
class ifcarbitraryprofiledefwithvoids
class ifcareadensitymeasure
class ifcareameasure
class ifcarithmeticoperatorenum
class ifcassemblyplaceenum
class ifcasset
class ifcasymmetricishapeprofiledef
class ifcaudiovisualappliance
class ifcaudiovisualappliancetype
class ifcaudiovisualappliancetypeenum
class ifcaxis1placement
class ifcaxis2placement2d
class ifcaxis2placement3d
class ifcbeam
class ifcbeamstandardcase
class ifcbeamtype
class ifcbeamtypeenum
class ifcbenchmarkenum
class ifcblobtexture
class ifcblock
class ifcboiler
class ifcboilertype
class ifcboilertypeenum
class ifcboolean
class ifcbooleanclippingresult
class ifcbooleanoperator
class ifcbooleanresult
class ifcboundarycondition
class ifcboundarycurve
class ifcboundaryedgecondition
class ifcboundaryfacecondition
class ifcboundarynodecondition
class ifcboundarynodeconditionwarping
class ifcboundedcurve
class ifcboundedsurface
class ifcboundingbox
class ifcboxalignment
class ifcboxedhalfspace
class ifcbsplinecurve
class ifcbsplinecurveform
class ifcbsplinecurvewithknots
class ifcbsplinesurface
class ifcbsplinesurfaceform
class ifcbsplinesurfacewithknots
class ifcbuilding
class ifcbuildingelement
class ifcbuildingelementpart
class ifcbuildingelementparttype
class ifcbuildingelementparttypeenum
class ifcbuildingelementproxy
class ifcbuildingelementproxytype
class ifcbuildingelementproxytypeenum
class ifcbuildingelementtype
class ifcbuildingstorey
class ifcbuildingsystem
class ifcbuildingsystemtypeenum
class ifcburner
class ifcburnertype
class ifcburnertypeenum
class ifccablecarrierfitting
class ifccablecarrierfittingtype
class ifccablecarrierfittingtypeenum
class ifccablecarriersegment
class ifccablecarriersegmenttype
class ifccablecarriersegmenttypeenum
class ifccablefitting
class ifccablefittingtype
class ifccablefittingtypeenum
class ifccablesegment
class ifccablesegmenttype
class ifccablesegmenttypeenum
class ifccardinalpointreference
class ifccartesianpoint
class ifccartesianpointlist
class ifccartesianpointlist3d
class ifccartesiantransformationoperator
class ifccartesiantransformationoperator2d
class ifccartesiantransformationoperator2dnonuniform
class ifccartesiantransformationoperator3d
class ifccartesiantransformationoperator3dnonuniform
class ifccenterlineprofiledef
class ifcchangeactionenum
class ifcchiller
class ifcchillertype
class ifcchillertypeenum
class ifcchimney
class ifcchimneytype
class ifcchimneytypeenum
class ifccircle
class ifccirclehollowprofiledef
class ifccircleprofiledef
class ifccivilelement
class ifccivilelementtype
class ifcclassification
class ifcclassificationreference
class ifcclosedshell
class ifccoil
class ifccoiltype
class ifccoiltypeenum
class ifccolourrgb
class ifccolourrgblist
class ifccolourspecification
class ifccolumn
class ifccolumnstandardcase
class ifccolumntype
class ifccolumntypeenum
class ifccommunicationsappliance
class ifccommunicationsappliancetype
class ifccommunicationsappliancetypeenum
class ifccomplexproperty
class ifccomplexpropertytemplate
class ifccomplexpropertytemplatetypeenum
class ifccompositecurve
class ifccompositecurveonsurface
class ifccompositecurvesegment
class ifccompositeprofiledef
class ifccompressor
class ifccompressortype
class ifccompressortypeenum
class ifccondenser
class ifccondensertype
class ifccondensertypeenum
class ifcconic
class ifcconnectedfaceset
class ifcconnectioncurvegeometry
class ifcconnectiongeometry
class ifcconnectionpointeccentricity
class ifcconnectionpointgeometry
class ifcconnectionsurfacegeometry
class ifcconnectiontypeenum
class ifcconnectionvolumegeometry
class ifcconstraint
class ifcconstraintenum
class ifcconstructionequipmentresource
class ifcconstructionequipmentresourcetype
class ifcconstructionequipmentresourcetypeenum
class ifcconstructionmaterialresource
class ifcconstructionmaterialresourcetype
class ifcconstructionmaterialresourcetypeenum
class ifcconstructionproductresource
class ifcconstructionproductresourcetype
class ifcconstructionproductresourcetypeenum
class ifcconstructionresource
class ifcconstructionresourcetype
class ifccontext
class ifccontextdependentmeasure
class ifccontextdependentunit
class ifccontrol
class ifccontroller
class ifccontrollertype
class ifccontrollertypeenum
class ifcconversionbasedunit
class ifcconversionbasedunitwithoffset
class ifccooledbeam
class ifccooledbeamtype
class ifccooledbeamtypeenum
class ifccoolingtower
class ifccoolingtowertype
class ifccoolingtowertypeenum
class ifccoordinateoperation
class ifccoordinatereferencesystem
class ifccostitem
class ifccostitemtypeenum
class ifccostschedule
class ifccostscheduletypeenum
class ifccostvalue
class ifccountmeasure
class ifccovering
class ifccoveringtype
class ifccoveringtypeenum
class ifccrewresource
class ifccrewresourcetype
class ifccrewresourcetypeenum
class ifccsgprimitive3d
class ifccsgsolid
class ifccshapeprofiledef
class ifccurrencyrelationship
class ifccurtainwall
class ifccurtainwalltype
class ifccurtainwalltypeenum
class ifccurvaturemeasure
class ifccurve
class ifccurveboundedplane
class ifccurveboundedsurface
class ifccurveinterpolationenum
class ifccurvestyle
class ifccurvestylefont
class ifccurvestylefontandscaling
class ifccurvestylefontpattern
class ifccylindricalsurface
class ifcdamper
class ifcdampertype
class ifcdampertypeenum
class ifcdataoriginenum
class ifcdate
class ifcdatetime
class ifcdayinmonthnumber
class ifcdayinweeknumber
class ifcderivedprofiledef
class ifcderivedunit
class ifcderivedunitelement
class ifcderivedunitenum
class ifcdescriptivemeasure
class ifcdimensionalexponents
class ifcdimensioncount
class ifcdirection
class ifcdirectionsenseenum
class ifcdiscreteaccessory
class ifcdiscreteaccessorytype
class ifcdiscreteaccessorytypeenum
class ifcdistributionchamberelement
class ifcdistributionchamberelementtype
class ifcdistributionchamberelementtypeenum
class ifcdistributioncircuit
class ifcdistributioncontrolelement
class ifcdistributioncontrolelementtype
class ifcdistributionelement
class ifcdistributionelementtype
class ifcdistributionflowelement
class ifcdistributionflowelementtype
class ifcdistributionport
class ifcdistributionporttypeenum
class ifcdistributionsystem
class ifcdistributionsystemenum
class ifcdocumentconfidentialityenum
class ifcdocumentinformation
class ifcdocumentinformationrelationship
class ifcdocumentreference
class ifcdocumentstatusenum
class ifcdoor
class ifcdoorliningproperties
class ifcdoorpaneloperationenum
class ifcdoorpanelpositionenum
class ifcdoorpanelproperties
class ifcdoorstandardcase
class ifcdoorstyle
class ifcdoorstyleconstructionenum
class ifcdoorstyleoperationenum
class ifcdoortype
class ifcdoortypeenum
class ifcdoortypeoperationenum
class ifcdoseequivalentmeasure
class ifcdraughtingpredefinedcolour
class ifcdraughtingpredefinedcurvefont
class ifcductfitting
class ifcductfittingtype
class ifcductfittingtypeenum
class ifcductsegment
class ifcductsegmenttype
class ifcductsegmenttypeenum
class ifcductsilencer
class ifcductsilencertype
class ifcductsilencertypeenum
class ifcduration
class ifcdynamicviscositymeasure
class ifcedge
class ifcedgecurve
class ifcedgeloop
class ifcelectricappliance
class ifcelectricappliancetype
class ifcelectricappliancetypeenum
class ifcelectriccapacitancemeasure
class ifcelectricchargemeasure
class ifcelectricconductancemeasure
class ifcelectriccurrentmeasure
class ifcelectricdistributionboard
class ifcelectricdistributionboardtype
class ifcelectricdistributionboardtypeenum
class ifcelectricflowstoragedevice
class ifcelectricflowstoragedevicetype
class ifcelectricflowstoragedevicetypeenum
class ifcelectricgenerator
class ifcelectricgeneratortype
class ifcelectricgeneratortypeenum
class ifcelectricmotor
class ifcelectricmotortype
class ifcelectricmotortypeenum
class ifcelectricresistancemeasure
class ifcelectrictimecontrol
class ifcelectrictimecontroltype
class ifcelectrictimecontroltypeenum
class ifcelectricvoltagemeasure
class ifcelement
class ifcelementarysurface
class ifcelementassembly
class ifcelementassemblytype
class ifcelementassemblytypeenum
class ifcelementcomponent
class ifcelementcomponenttype
class ifcelementcompositionenum
class ifcelementquantity
class ifcelementtype
class ifcellipse
class ifcellipseprofiledef
class ifcenergyconversiondevice
class ifcenergyconversiondevicetype
class ifcenergymeasure
class ifcengine
class ifcenginetype
class ifcenginetypeenum
class ifcevaporativecooler
class ifcevaporativecoolertype
class ifcevaporativecoolertypeenum
class ifcevaporator
class ifcevaporatortype
class ifcevaporatortypeenum
class ifcevent
class ifceventtime
class ifceventtriggertypeenum
class ifceventtype
class ifceventtypeenum
class ifcextendedproperties
class ifcexternalinformation
class ifcexternallydefinedhatchstyle
class ifcexternallydefinedsurfacestyle
class ifcexternallydefinedtextfont
class ifcexternalreference
class ifcexternalreferencerelationship
class ifcexternalspatialelement
class ifcexternalspatialelementtypeenum
class ifcexternalspatialstructureelement
class ifcextrudedareasolid
class ifcextrudedareasolidtapered
class ifcface
class ifcfacebasedsurfacemodel
class ifcfacebound
class ifcfaceouterbound
class ifcfacesurface
class ifcfacetedbrep
class ifcfacetedbrepwithvoids
class ifcfailureconnectioncondition
class ifcfan
class ifcfantype
class ifcfantypeenum
class ifcfastener
class ifcfastenertype
class ifcfastenertypeenum
class ifcfeatureelement
class ifcfeatureelementaddition
class ifcfeatureelementsubtraction
class ifcfillareastyle
class ifcfillareastylehatching
class ifcfillareastyletiles
class ifcfilter
class ifcfiltertype
class ifcfiltertypeenum
class ifcfiresuppressionterminal
class ifcfiresuppressionterminaltype
class ifcfiresuppressionterminaltypeenum
class ifcfixedreferencesweptareasolid
class ifcflowcontroller
class ifcflowcontrollertype
class ifcflowdirectionenum
class ifcflowfitting
class ifcflowfittingtype
class ifcflowinstrument
class ifcflowinstrumenttype
class ifcflowinstrumenttypeenum
class ifcflowmeter
class ifcflowmetertype
class ifcflowmetertypeenum
class ifcflowmovingdevice
class ifcflowmovingdevicetype
class ifcflowsegment
class ifcflowsegmenttype
class ifcflowstoragedevice
class ifcflowstoragedevicetype
class ifcflowterminal
class ifcflowterminaltype
class ifcflowtreatmentdevice
class ifcflowtreatmentdevicetype
class ifcfontstyle
class ifcfontvariant
class ifcfontweight
class ifcfooting
class ifcfootingtype
class ifcfootingtypeenum
class ifcforcemeasure
class ifcfrequencymeasure
class ifcfurnishingelement
class ifcfurnishingelementtype
class ifcfurniture
class ifcfurnituretype
class ifcfurnituretypeenum
class ifcgeographicelement
class ifcgeographicelementtype
class ifcgeographicelementtypeenum
class ifcgeometriccurveset
class ifcgeometricprojectionenum
class ifcgeometricrepresentationcontext
class ifcgeometricrepresentationitem
class ifcgeometricrepresentationsubcontext
class ifcgeometricset
class ifcgloballyuniqueid
class ifcglobalorlocalenum
class ifcgrid
class ifcgridaxis
class ifcgridplacement
class ifcgridtypeenum
class ifcgroup
class ifchalfspacesolid
class ifcheatexchanger
class ifcheatexchangertype
class ifcheatexchangertypeenum
class ifcheatfluxdensitymeasure
class ifcheatingvaluemeasure
class ifchumidifier
class ifchumidifiertype
class ifchumidifiertypeenum
class ifcidentifier
class ifcilluminancemeasure
class ifcimagetexture
class ifcindexedcolourmap
class ifcindexedtexturemap
class ifcindexedtriangletexturemap
class ifcinductancemeasure
class ifcinteger
class ifcintegercountratemeasure
class ifcinterceptor
class ifcinterceptortype
class ifcinterceptortypeenum
class ifcinternalorexternalenum
class ifcinventory
class ifcinventorytypeenum
class ifcionconcentrationmeasure
class ifcirregulartimeseries
class ifcirregulartimeseriesvalue
class ifcishapeprofiledef
class ifcisothermalmoisturecapacitymeasure
class ifcjunctionbox
class ifcjunctionboxtype
class ifcjunctionboxtypeenum
class ifckinematicviscositymeasure
class ifcknottype
class ifclabel
class ifclaborresource
class ifclaborresourcetype
class ifclaborresourcetypeenum
class ifclagtime
class ifclamp
class ifclamptype
class ifclamptypeenum
class ifclanguageid
class ifclayersetdirectionenum
class ifclengthmeasure
class ifclibraryinformation
class ifclibraryreference
class ifclightdistributioncurveenum
class ifclightdistributiondata
class ifclightemissionsourceenum
class ifclightfixture
class ifclightfixturetype
class ifclightfixturetypeenum
class ifclightintensitydistribution
class ifclightsource
class ifclightsourceambient
class ifclightsourcedirectional
class ifclightsourcegoniometric
class ifclightsourcepositional
class ifclightsourcespot
class ifcline
class ifclinearforcemeasure
class ifclinearmomentmeasure
class ifclinearstiffnessmeasure
class ifclinearvelocitymeasure
class ifcloadgrouptypeenum
class ifclocalplacement
class ifclogical
class ifclogicaloperatorenum
class ifcloop
class ifclshapeprofiledef
class ifcluminousfluxmeasure
class ifcluminousintensitydistributionmeasure
class ifcluminousintensitymeasure
class ifcmagneticfluxdensitymeasure
class ifcmagneticfluxmeasure
class ifcmanifoldsolidbrep
class ifcmapconversion
class ifcmappeditem
class ifcmassdensitymeasure
class ifcmassflowratemeasure
class ifcmassmeasure
class ifcmassperlengthmeasure
class ifcmaterial
class ifcmaterialclassificationrelationship
class ifcmaterialconstituent
class ifcmaterialconstituentset
class ifcmaterialdefinition
class ifcmaterialdefinitionrepresentation
class ifcmateriallayer
class ifcmateriallayerset
class ifcmateriallayersetusage
class ifcmateriallayerwithoffsets
class ifcmateriallist
class ifcmaterialprofile
class ifcmaterialprofileset
class ifcmaterialprofilesetusage
class ifcmaterialprofilesetusagetapering
class ifcmaterialprofilewithoffsets
class ifcmaterialproperties
class ifcmaterialrelationship
class ifcmaterialusagedefinition
class ifcmeasurewithunit
class ifcmechanicalfastener
class ifcmechanicalfastenertype
class ifcmechanicalfastenertypeenum
class ifcmedicaldevice
class ifcmedicaldevicetype
class ifcmedicaldevicetypeenum
class ifcmember
class ifcmemberstandardcase
class ifcmembertype
class ifcmembertypeenum
class ifcmetric
class ifcmirroredprofiledef
class ifcmodulusofelasticitymeasure
class ifcmodulusoflinearsubgradereactionmeasure
class ifcmodulusofrotationalsubgradereactionmeasure
class ifcmodulusofsubgradereactionmeasure
class ifcmoisturediffusivitymeasure
class ifcmolecularweightmeasure
class ifcmomentofinertiameasure
class ifcmonetarymeasure
class ifcmonetaryunit
class ifcmonthinyearnumber
class ifcmotorconnection
class ifcmotorconnectiontype
class ifcmotorconnectiontypeenum
class ifcnamedunit
class ifcnonnegativelengthmeasure
class ifcnormalisedratiomeasure
class ifcnullstyle
class ifcnumericmeasure
class ifcobject
class ifcobjectdefinition
class ifcobjective
class ifcobjectiveenum
class ifcobjectplacement
class ifcobjecttypeenum
class ifcoccupant
class ifcoccupanttypeenum
class ifcoffsetcurve2d
class ifcoffsetcurve3d
class ifcopeningelement
class ifcopeningelementtypeenum
class ifcopeningstandardcase
class ifcopenshell
class ifcorganization
class ifcorganizationrelationship
class ifcorientededge
class ifcouterboundarycurve
class ifcoutlet
class ifcoutlettype
class ifcoutlettypeenum
class ifcownerhistory
class ifcparameterizedprofiledef
class ifcparametervalue
class ifcpath
class ifcpcurve
class ifcperformancehistory
class ifcperformancehistorytypeenum
class ifcpermeablecoveringoperationenum
class ifcpermeablecoveringproperties
class ifcpermit
class ifcpermittypeenum
class ifcperson
class ifcpersonandorganization
class ifcphmeasure
class ifcphysicalcomplexquantity
class ifcphysicalorvirtualenum
class ifcphysicalquantity
class ifcphysicalsimplequantity
class ifcpile
class ifcpileconstructionenum
class ifcpiletype
class ifcpiletypeenum
class ifcpipefitting
class ifcpipefittingtype
class ifcpipefittingtypeenum
class ifcpipesegment
class ifcpipesegmenttype
class ifcpipesegmenttypeenum
class ifcpixeltexture
class ifcplacement
class ifcplanarbox
class ifcplanarextent
class ifcplanarforcemeasure
class ifcplane
class ifcplaneanglemeasure
class ifcplate
class ifcplatestandardcase
class ifcplatetype
class ifcplatetypeenum
class ifcpoint
class ifcpointoncurve
class ifcpointonsurface
class ifcpolygonalboundedhalfspace
class ifcpolyline
class ifcpolyloop
class ifcport
class ifcpositivelengthmeasure
class ifcpositiveplaneanglemeasure
class ifcpositiveratiomeasure
class ifcpostaladdress
class ifcpowermeasure
class ifcpredefinedcolour
class ifcpredefinedcurvefont
class ifcpredefineditem
class ifcpredefinedproperties
class ifcpredefinedpropertyset
class ifcpredefinedtextfont
class ifcpresentabletext
class ifcpresentationitem
class ifcpresentationlayerassignment
class ifcpresentationlayerwithstyle
class ifcpresentationstyle
class ifcpresentationstyleassignment
class ifcpressuremeasure
class ifcprocedure
class ifcproceduretype
class ifcproceduretypeenum
class ifcprocess
class ifcproduct
class ifcproductdefinitionshape
class ifcproductrepresentation
class ifcprofiledef
class ifcprofileproperties
class ifcprofiletypeenum
class ifcproject
class ifcprojectedcrs
class ifcprojectedortruelengthenum
class ifcprojectionelement
class ifcprojectionelementtypeenum
class ifcprojectlibrary
class ifcprojectorder
class ifcprojectordertypeenum
class ifcproperty
class ifcpropertyabstraction
class ifcpropertyboundedvalue
class ifcpropertydefinition
class ifcpropertydependencyrelationship
class ifcpropertyenumeratedvalue
class ifcpropertyenumeration
class ifcpropertylistvalue
class ifcpropertyreferencevalue
class ifcpropertyset
class ifcpropertysetdefinition
class ifcpropertysettemplate
class ifcpropertysettemplatetypeenum
class ifcpropertysinglevalue
class ifcpropertytablevalue
class ifcpropertytemplate
class ifcpropertytemplatedefinition
class ifcprotectivedevice
class ifcprotectivedevicetrippingunit
class ifcprotectivedevicetrippingunittype
class ifcprotectivedevicetrippingunittypeenum
class ifcprotectivedevicetype
class ifcprotectivedevicetypeenum
class ifcproxy
class ifcpump
class ifcpumptype
class ifcpumptypeenum
class ifcquantityarea
class ifcquantitycount
class ifcquantitylength
class ifcquantityset
class ifcquantitytime
class ifcquantityvolume
class ifcquantityweight
class ifcradioactivitymeasure
class ifcrailing
class ifcrailingtype
class ifcrailingtypeenum
class ifcramp
class ifcrampflight
class ifcrampflighttype
class ifcrampflighttypeenum
class ifcramptype
class ifcramptypeenum
class ifcratiomeasure
class ifcrationalbsplinecurvewithknots
class ifcrationalbsplinesurfacewithknots
class ifcreal
class ifcrectanglehollowprofiledef
class ifcrectangleprofiledef
class ifcrectangularpyramid
class ifcrectangulartrimmedsurface
class ifcrecurrencepattern
class ifcrecurrencetypeenum
class ifcreference
class ifcreflectancemethodenum
class ifcregulartimeseries
class ifcreinforcementbarproperties
class ifcreinforcementdefinitionproperties
class ifcreinforcingbar
class ifcreinforcingbarroleenum
class ifcreinforcingbarsurfaceenum
class ifcreinforcingbartype
class ifcreinforcingbartypeenum
class ifcreinforcingelement
class ifcreinforcingelementtype
class ifcreinforcingmesh
class ifcreinforcingmeshtype
class ifcreinforcingmeshtypeenum
class ifcrelaggregates
class ifcrelassigns
class ifcrelassignstoactor
class ifcrelassignstocontrol
class ifcrelassignstogroup
class ifcrelassignstogroupbyfactor
class ifcrelassignstoprocess
class ifcrelassignstoproduct
class ifcrelassignstoresource
class ifcrelassociates
class ifcrelassociatesapproval
class ifcrelassociatesclassification
class ifcrelassociatesconstraint
class ifcrelassociatesdocument
class ifcrelassociateslibrary
class ifcrelassociatesmaterial
class ifcrelationship
class ifcrelconnects
class ifcrelconnectselements
class ifcrelconnectspathelements
class ifcrelconnectsports
class ifcrelconnectsporttoelement
class ifcrelconnectsstructuralactivity
class ifcrelconnectsstructuralmember
class ifcrelconnectswitheccentricity
class ifcrelconnectswithrealizingelements
class ifcrelcontainedinspatialstructure
class ifcrelcoversbldgelements
class ifcrelcoversspaces
class ifcreldeclares
class ifcreldecomposes
class ifcreldefines
class ifcreldefinesbyobject
class ifcreldefinesbyproperties
class ifcreldefinesbytemplate
class ifcreldefinesbytype
class ifcrelfillselement
class ifcrelflowcontrolelements
class ifcrelinterfereselements
class ifcrelnests
class ifcrelprojectselement
class ifcrelreferencedinspatialstructure
class ifcrelsequence
class ifcrelservicesbuildings
class ifcrelspaceboundary
class ifcrelspaceboundary1stlevel
class ifcrelspaceboundary2ndlevel
class ifcrelvoidselement
class ifcreparametrisedcompositecurvesegment
class ifcrepresentation
class ifcrepresentationcontext
class ifcrepresentationitem
class ifcrepresentationmap
class ifcresource
class ifcresourceapprovalrelationship
class ifcresourceconstraintrelationship
class ifcresourcelevelrelationship
class ifcresourcetime
class ifcrevolvedareasolid
class ifcrevolvedareasolidtapered
class ifcrightcircularcone
class ifcrightcircularcylinder
class ifcroleenum
class ifcroof
class ifcrooftype
class ifcrooftypeenum
class ifcroot
class ifcrotationalfrequencymeasure
class ifcrotationalmassmeasure
class ifcrotationalstiffnessmeasure
class ifcroundedrectangleprofiledef
class ifcsanitaryterminal
class ifcsanitaryterminaltype
class ifcsanitaryterminaltypeenum
class ifcschedulingtime
class ifcsectionalareaintegralmeasure
class ifcsectionedspine
class ifcsectionmodulusmeasure
class ifcsectionproperties
class ifcsectionreinforcementproperties
class ifcsectiontypeenum
class ifcsensor
class ifcsensortype
class ifcsensortypeenum
class ifcsequenceenum
class ifcshadingdevice
class ifcshadingdevicetype
class ifcshadingdevicetypeenum
class ifcshapeaspect
class ifcshapemodel
class ifcshaperepresentation
class ifcshearmodulusmeasure
class ifcshellbasedsurfacemodel
class ifcsimpleproperty
class ifcsimplepropertytemplate
class ifcsimplepropertytemplatetypeenum
class ifcsiprefix
class ifcsite
class ifcsiunit
class ifcsiunitname
class ifcslab
class ifcslabelementedcase
class ifcslabstandardcase
class ifcslabtype
class ifcslabtypeenum
class ifcslippageconnectioncondition
class ifcsolardevice
class ifcsolardevicetype
class ifcsolardevicetypeenum
class ifcsolidanglemeasure
class ifcsolidmodel
class ifcsoundpowerlevelmeasure
class ifcsoundpowermeasure
class ifcsoundpressurelevelmeasure
class ifcsoundpressuremeasure
class ifcspace
class ifcspaceheater
class ifcspaceheatertype
class ifcspaceheatertypeenum
class ifcspacetype
class ifcspacetypeenum
class ifcspatialelement
class ifcspatialelementtype
class ifcspatialstructureelement
class ifcspatialstructureelementtype
class ifcspatialzone
class ifcspatialzonetype
class ifcspatialzonetypeenum
class ifcspecificheatcapacitymeasure
class ifcspecularexponent
class ifcspecularroughness
class ifcsphere
class ifcstackterminal
class ifcstackterminaltype
class ifcstackterminaltypeenum
class ifcstair
class ifcstairflight
class ifcstairflighttype
class ifcstairflighttypeenum
class ifcstairtype
class ifcstairtypeenum
class ifcstateenum
class ifcstructuralaction
class ifcstructuralactivity
class ifcstructuralanalysismodel
class ifcstructuralconnection
class ifcstructuralconnectioncondition
class ifcstructuralcurveaction
class ifcstructuralcurveactivitytypeenum
class ifcstructuralcurveconnection
class ifcstructuralcurvemember
class ifcstructuralcurvemembertypeenum
class ifcstructuralcurvemembervarying
class ifcstructuralcurvereaction
class ifcstructuralitem
class ifcstructurallinearaction
class ifcstructuralload
class ifcstructuralloadcase
class ifcstructuralloadconfiguration
class ifcstructuralloadgroup
class ifcstructuralloadlinearforce
class ifcstructuralloadorresult
class ifcstructuralloadplanarforce
class ifcstructuralloadsingledisplacement
class ifcstructuralloadsingledisplacementdistortion
class ifcstructuralloadsingleforce
class ifcstructuralloadsingleforcewarping
class ifcstructuralloadstatic
class ifcstructuralloadtemperature
class ifcstructuralmember
class ifcstructuralplanaraction
class ifcstructuralpointaction
class ifcstructuralpointconnection
class ifcstructuralpointreaction
class ifcstructuralreaction
class ifcstructuralresultgroup
class ifcstructuralsurfaceaction
class ifcstructuralsurfaceactivitytypeenum
class ifcstructuralsurfaceconnection
class ifcstructuralsurfacemember
class ifcstructuralsurfacemembertypeenum
class ifcstructuralsurfacemembervarying
class ifcstructuralsurfacereaction
class ifcstyleditem
class ifcstyledrepresentation
class ifcstylemodel
class ifcsubcontractresource
class ifcsubcontractresourcetype
class ifcsubcontractresourcetypeenum
class ifcsubedge
class ifcsurface
class ifcsurfacecurvesweptareasolid
class ifcsurfacefeature
class ifcsurfacefeaturetypeenum
class ifcsurfaceoflinearextrusion
class ifcsurfaceofrevolution
class ifcsurfacereinforcementarea
class ifcsurfaceside
class ifcsurfacestyle
class ifcsurfacestylelighting
class ifcsurfacestylerefraction
class ifcsurfacestylerendering
class ifcsurfacestyleshading
class ifcsurfacestylewithtextures
class ifcsurfacetexture
class ifcsweptareasolid
class ifcsweptdisksolid
class ifcsweptdisksolidpolygonal
class ifcsweptsurface
class ifcswitchingdevice
class ifcswitchingdevicetype
class ifcswitchingdevicetypeenum
class ifcsystem
class ifcsystemfurnitureelement
class ifcsystemfurnitureelementtype
class ifcsystemfurnitureelementtypeenum
class ifctable
class ifctablecolumn
class ifctablerow
class ifctank
class ifctanktype
class ifctanktypeenum
class ifctask
class ifctaskdurationenum
class ifctasktime
class ifctasktimerecurring
class ifctasktype
class ifctasktypeenum
class ifctelecomaddress
class ifctemperaturegradientmeasure
class ifctemperaturerateofchangemeasure
class ifctendon
class ifctendonanchor
class ifctendonanchortype
class ifctendonanchortypeenum
class ifctendontype
class ifctendontypeenum
class ifctessellatedfaceset
class ifctessellateditem
class ifctext
class ifctextalignment
class ifctextdecoration
class ifctextfontname
class ifctextliteral
class ifctextliteralwithextent
class ifctextpath
class ifctextstyle
class ifctextstylefontmodel
class ifctextstylefordefinedfont
class ifctextstyletextmodel
class ifctexttransformation
class ifctexturecoordinate
class ifctexturecoordinategenerator
class ifctexturemap
class ifctexturevertex
class ifctexturevertexlist
class ifcthermaladmittancemeasure
class ifcthermalconductivitymeasure
class ifcthermalexpansioncoefficientmeasure
class ifcthermalresistancemeasure
class ifcthermaltransmittancemeasure
class ifcthermodynamictemperaturemeasure
class ifctime
class ifctimemeasure
class ifctimeperiod
class ifctimeseries
class ifctimeseriesdatatypeenum
class ifctimeseriesvalue
class ifctimestamp
class ifctopologicalrepresentationitem
class ifctopologyrepresentation
class ifctorquemeasure
class ifctransformer
class ifctransformertype
class ifctransformertypeenum
class ifctransitioncode
class ifctransportelement
class ifctransportelementtype
class ifctransportelementtypeenum
class ifctrapeziumprofiledef
class ifctriangulatedfaceset
class ifctrimmedcurve
class ifctrimmingpreference
class ifctshapeprofiledef
class ifctubebundle
class ifctubebundletype
class ifctubebundletypeenum
class ifctypeobject
class ifctypeprocess
class ifctypeproduct
class ifctyperesource
class ifcunitarycontrolelement
class ifcunitarycontrolelementtype
class ifcunitarycontrolelementtypeenum
class ifcunitaryequipment
class ifcunitaryequipmenttype
class ifcunitaryequipmenttypeenum
class ifcunitassignment
class ifcunitenum
class ifcurireference
class ifcushapeprofiledef
class ifcvalve
class ifcvalvetype
class ifcvalvetypeenum
class ifcvaporpermeabilitymeasure
class ifcvector
class ifcvertex
class ifcvertexloop
class ifcvertexpoint
class ifcvibrationisolator
class ifcvibrationisolatortype
class ifcvibrationisolatortypeenum
class ifcvirtualelement
class ifcvirtualgridintersection
class ifcvoidingfeature
class ifcvoidingfeaturetypeenum
class ifcvolumemeasure
class ifcvolumetricflowratemeasure
class ifcwall
class ifcwallelementedcase
class ifcwallstandardcase
class ifcwalltype
class ifcwalltypeenum
class ifcwarpingconstantmeasure
class ifcwarpingmomentmeasure
class ifcwasteterminal
class ifcwasteterminaltype
class ifcwasteterminaltypeenum
class ifcwindow
class ifcwindowliningproperties
class ifcwindowpaneloperationenum
class ifcwindowpanelpositionenum
class ifcwindowpanelproperties
class ifcwindowstandardcase
class ifcwindowstyle
class ifcwindowstyleconstructionenum
class ifcwindowstyleoperationenum
class ifcwindowtype
class ifcwindowtypeenum
class ifcwindowtypepartitioningenum
class ifcworkcalendar
class ifcworkcalendartypeenum
class ifcworkcontrol
class ifcworkplan
class ifcworkplantypeenum
class ifcworkschedule
class ifcworkscheduletypeenum
class ifcworktime
class ifczone
class ifczshapeprofiledef
Functions
def ifcbaseaxis (dim, axis1, axis2, axis3)
FUNCTION ifcbaseaxis #.
def ifcbooleanchoose (b, choice1, choice2)
FUNCTION ifcbooleanchoose #.
def ifcbuild2axes (refdirection)
FUNCTION ifcbuild2axes #.
def ifcbuildaxes (axis, refdirection)
FUNCTION ifcbuildaxes #.
def ifcconstraintsparambspline (degree, upknots, upcp, knotmult, knots)
FUNCTION ifcconstraintsparambspline #.
def ifcconvertdirectioninto2d (direction)
FUNCTION ifcconvertdirectioninto2d #.
def ifccorrectdimensions (m, dim)
FUNCTION ifccorrectdimensions #.
def ifccorrectfillareastyle (styles)
FUNCTION ifccorrectfillareastyle #.
def ifccorrectlocalplacement (axisplacement, relplacement)
FUNCTION ifccorrectlocalplacement #.
def ifccorrectobjectassignment (constraint, objects)
FUNCTION ifccorrectobjectassignment #.
def ifccorrectunitassignment (units)
FUNCTION ifccorrectunitassignment #.
def ifccrossproduct (arg1, arg2)
FUNCTION ifccrossproduct #.
def ifccurvedim (curve)
FUNCTION ifccurvedim #.
def ifccurveweightspositive (b)
FUNCTION ifccurveweightspositive #.
def ifcderivedimensionalexponents (unitelements)
FUNCTION ifcderivedimensionalexponents #.
def ifcdimensionsforsiunit (n)
FUNCTION ifcdimensionsforsiunit #.
def ifcdotproduct (arg1, arg2)
FUNCTION ifcdotproduct #.
def ifcfirstprojaxis (zaxis, arg)
FUNCTION ifcfirstprojaxis #.
def ifcgetbasissurface (c)
FUNCTION ifcgetbasissurface #.
def ifclisttoarray (lis, low, u)
FUNCTION ifclisttoarray #.
def ifcloopheadtotail (aloop)
FUNCTION ifcloopheadtotail #.
def ifcmakearrayofarray (lis, low1, u1, low2, u2)
FUNCTION ifcmakearrayofarray #.
def ifcmlstotalthickness (layerset)
FUNCTION ifcmlstotalthickness #.
def ifcnormalise (arg)
def ifcorthogonalcomplement (vec)
FUNCTION ifcorthogonalcomplement #.
def ifcpathheadtotail (apath)
FUNCTION ifcpathheadtotail #.
def ifcsameaxis2placement (ap1, ap2, epsilon)
FUNCTION ifcsameaxis2placement #.
def ifcsamecartesianpoint (cp1, cp2, epsilon)
FUNCTION ifcsamecartesianpoint #.
def ifcsamedirection (dir1, dir2, epsilon)
FUNCTION ifcsamedirection #.
def ifcsamevalidprecision (epsilon1, epsilon2)
FUNCTION ifcsamevalidprecision #.
def ifcsamevalue (value1, value2, epsilon)
FUNCTION ifcsamevalue #.
def ifcscalartimesvector (scalar, vec)
FUNCTION ifcscalartimesvector #.
def ifcsecondprojaxis (zaxis, xaxis, arg)
FUNCTION ifcsecondprojaxis #.
def ifcshaperepresentationtypes (reptype, items)
FUNCTION ifcshaperepresentationtypes #.
def ifcsurfaceweightspositive (b)
FUNCTION ifcsurfaceweightspositive #.
def ifctaperedsweptareaprofiles (startarea, endarea)
FUNCTION ifctaperedsweptareaprofiles #.
def ifctopologyrepresentationtypes (reptype, items)
FUNCTION ifctopologyrepresentationtypes #.
def ifcuniquepropertyname (properties)
FUNCTION ifcuniquepropertyname #.
def ifcuniquepropertytemplatenames (properties)
FUNCTION ifcuniquepropertytemplatenames #.
def ifcuniquequantitynames (properties)
FUNCTION ifcuniquequantitynames #.
def ifcvectordifference (arg1, arg2)
FUNCTION ifcvectordifference #.
def ifcvectorsum (arg1, arg2)
FUNCTION ifcvectorsum #.
Variables
ifcactorselect
ifcappliedvalueselect
ifcaxis2placement
ifcbendingparameterselect
ifcbooleanoperand
ifcclassificationreferenceselect
ifcclassificationselect
ifccolour
ifccolourorfactor
ifccomplexnumber = ARRAY(1,2,'REAL', scope = schema_scope)
ifccompoundplaneanglemeasure = LIST(3,4,'INTEGER', scope = schema_scope)
ifccoordinatereferencesystemselect
ifccsgselect
ifccurvefontorscaledcurvefontselect
ifccurveonsurface
ifccurveoredgecurve
ifccurvestylefontselect
ifcdefinitionselect
ifcderivedmeasurevalue
ifcdocumentselect
ifcfillstyleselect
ifcgeometricsetselect
ifcgridplacementdirectionselect
ifchatchlinedistanceselect
ifclayereditem
ifclibraryselect
ifclightdistributiondatasourceselect
ifcmaterialselect
ifcmeasurevalue
ifcmetricvalueselect
ifcmodulusofrotationalsubgradereactionselect
ifcmodulusofsubgradereactionselect
ifcmodulusoftranslationalsubgradereactionselect
ifcobjectreferenceselect
ifcpointorvertexpoint
ifcpresentationstyleselect
ifcprocessselect
ifcproductrepresentationselect
ifcproductselect
ifcpropertysetdefinitionselect
ifcpropertysetdefinitionset = SET(1,None,'ifcpropertysetdefinition', scope = schema_scope)
ifcrepresentationcontextsamewcs = Rule()
RULE ifcrepresentationcontextsamewcs #.
ifcresourceobjectselect
ifcresourceselect
ifcrotationalstiffnessselect
ifcshell
ifcsimplevalue
ifcsingleprojectinstance = Rule()
RULE ifcsingleprojectinstance #.
ifcsizeselect
ifcsolidorshell
ifcspaceboundaryselect
ifcspecularhighlightselect
ifcstructuralactivityassignmentselect
ifcstyleassignmentselect
ifcsurfaceorfacesurface
ifcsurfacestyleelementselect
ifctextfontselect
ifctimeorratioselect
ifctranslationalstiffnessselect
ifctrimmingselect
ifcunit
ifcvalue
ifcvectorordirection
ifcwarpingstiffnessselect
string schema_name = 'ifc4'
schema_scope = sys.modules[__name__]
Function Documentation
ifcbaseaxis()
def ifc4.ifcbaseaxis (dim, axis1, axis2, axis3)
FUNCTION ifcbaseaxis #.
        :param dim
        :type dim:INTEGER
        :param axis1
        :type axis1:ifcdirection
        :param axis2
        :type axis2:ifcdirection
        :param axis3
        :type axis3:ifcdirection
References ifcdotproduct(), ifcfirstprojaxis(), ifcnormalise(), ifcorthogonalcomplement(), and ifcsecondprojaxis().
Referenced by ifc4.ifccartesiantransformationoperator3d.u(), and ifc4.ifccartesiantransformationoperator2d.u().
ifcbooleanchoose()
def ifc4.ifcbooleanchoose (b, choice1, choice2)
FUNCTION ifcbooleanchoose #.
        :param b
        :type b:BOOLEAN
        :param choice1
        :type choice1:(null)
        :param choice2
        :type choice2:(null)
Referenced by ifc4.ifcorientededge.ifcedge_edgeend(), and ifc4.ifcorientededge.ifcedge_edgestart().
ifcbuild2axes()
def ifc4.ifcbuild2axes (refdirection)
FUNCTION ifcbuild2axes #.
        :param refdirection
        :type refdirection:ifcdirection
References ifcorthogonalcomplement().
Referenced by ifc4.ifcaxis2placement2d.p().
ifcbuildaxes()
def ifc4.ifcbuildaxes (axis, refdirection)
FUNCTION ifcbuildaxes #.
        :param axis
        :type axis:ifcdirection
        :param refdirection
        :type refdirection:ifcdirection
References ifccrossproduct(), ifcfirstprojaxis(), and ifcnormalise().
Referenced by ifc4.ifcaxis2placement3d.p().
ifcconstraintsparambspline()
def ifc4.ifcconstraintsparambspline (degree, upknots, upcp, knotmult, knots)
FUNCTION ifcconstraintsparambspline #.
        :param degree
        :type degree:INTEGER
        :param upknots
        :type upknots:INTEGER
        :param upcp
        :type upcp:INTEGER
        :param knotmult
        :type knotmult:(null)
        :param knots
        :type knots:(null)
Referenced by ifc4.ifcbsplinecurvewithknots.consistentbspline(), ifc4.ifcbsplinesurfacewithknots.udirectionconstraints(), and ifc4.ifcbsplinesurfacewithknots.vdirectionconstraints().
ifcconvertdirectioninto2d()
def ifc4.ifcconvertdirectioninto2d (direction)
FUNCTION ifcconvertdirectioninto2d #.
        :param direction
        :type direction:ifcdirection
Referenced by ifc4.ifcgeometricrepresentationsubcontext.ifcgeometricrepresentationcontext_truenorth().
ifccorrectdimensions()
def ifc4.ifccorrectdimensions (m, dim)
FUNCTION ifccorrectdimensions #.
        :param m
        :type m:ifcunitenum
        :param dim
        :type dim:ifcdimensionalexponents
Referenced by ifc4.ifcnamedunit.wr1().
ifccorrectfillareastyle()
def ifc4.ifccorrectfillareastyle (styles)
FUNCTION ifccorrectfillareastyle #.
        :param styles
        :type styles:(null)
Referenced by ifc4.ifcfillareastyle.consistenthatchstyledef().
ifccorrectlocalplacement()
def ifc4.ifccorrectlocalplacement (axisplacement, relplacement)
FUNCTION ifccorrectlocalplacement #.
        :param axisplacement
        :type axisplacement:ifcaxis2placement
        :param relplacement
        :type relplacement:ifcobjectplacement
Referenced by ifc4.ifclocalplacement.wr21().
ifccorrectobjectassignment()
def ifc4.ifccorrectobjectassignment (constraint, objects)
FUNCTION ifccorrectobjectassignment #.
        :param constraint
        :type constraint:ifcobjecttypeenum
        :param objects
        :type objects:(null)
Referenced by ifc4.ifcrelassigns.wr1().
ifccorrectunitassignment()
def ifc4.ifccorrectunitassignment (units)
FUNCTION ifccorrectunitassignment #.
        :param units
        :type units:(null)
Referenced by ifc4.ifcunitassignment.wr01().
ifccrossproduct()
def ifc4.ifccrossproduct (arg1, arg2)
FUNCTION ifccrossproduct #.
        :param arg1
        :type arg1:ifcdirection
        :param arg2
        :type arg2:ifcdirection
References ifcnormalise().
Referenced by ifc4.ifcaxis2placement3d.axistorefdirposition(), ifcbuildaxes(), and ifcfirstprojaxis().
ifccurvedim()
def ifc4.ifccurvedim (curve)
FUNCTION ifccurvedim #.
        :param curve
        :type curve:ifccurve
Referenced by ifc4.ifccurve.dim().
ifccurveweightspositive()
def ifc4.ifccurveweightspositive (b)
FUNCTION ifccurveweightspositive #.
        :param b
        :type b:ifcrationalbsplinecurvewithknots
Referenced by ifc4.ifcrationalbsplinecurvewithknots.weightsgreaterzero().
ifcderivedimensionalexponents()
def ifc4.ifcderivedimensionalexponents (unitelements)
FUNCTION ifcderivedimensionalexponents #.
        :param unitelements
        :type unitelements:(null)
Referenced by ifc4.ifcderivedunit.dimensions().
ifcdimensionsforsiunit()
def ifc4.ifcdimensionsforsiunit (n)
FUNCTION ifcdimensionsforsiunit #.
        :param n
        :type n:ifcsiunitname
Referenced by ifc4.ifcsiunit.ifcnamedunit_dimensions().
ifcdotproduct()
def ifc4.ifcdotproduct (arg1, arg2)
FUNCTION ifcdotproduct #.
        :param arg1
        :type arg1:ifcdirection
        :param arg2
        :type arg2:ifcdirection
References ifcnormalise().
Referenced by ifcbaseaxis(), ifcfirstprojaxis(), ifcsecondprojaxis(), and ifc4.ifcextrudedareasolid.validextrusiondirection().
ifcfirstprojaxis()
def ifc4.ifcfirstprojaxis (zaxis, arg)
FUNCTION ifcfirstprojaxis #.
        :param zaxis
        :type zaxis:ifcdirection
        :param arg
        :type arg:ifcdirection
References ifccrossproduct(), ifcdotproduct(), ifcnormalise(), ifcscalartimesvector(), and ifcvectordifference().
Referenced by ifcbaseaxis(), and ifcbuildaxes().
ifcgetbasissurface()
def ifc4.ifcgetbasissurface (c)
FUNCTION ifcgetbasissurface #.
        :param c
        :type c:ifccurveonsurface
Referenced by ifc4.ifccompositecurveonsurface.basissurface().
ifclisttoarray()
def ifc4.ifclisttoarray (lis, low, u)
FUNCTION ifclisttoarray #.
        :param lis
        :type lis:(null)
        :param low
        :type low:INTEGER
        :param u
        :type u:INTEGER
Referenced by ifc4.ifcbsplinecurve.controlpoints(), ifcmakearrayofarray(), and ifc4.ifcrationalbsplinecurvewithknots.weights().
ifcloopheadtotail()
def ifc4.ifcloopheadtotail (aloop)
FUNCTION ifcloopheadtotail #.
        :param aloop
        :type aloop:ifcedgeloop
Referenced by ifc4.ifcedgeloop.iscontinuous().
ifcmakearrayofarray()
def ifc4.ifcmakearrayofarray (lis, low1, u1, low2, u2)
FUNCTION ifcmakearrayofarray #.
        :param lis
        :type lis:(null)
        :param low1
        :type low1:INTEGER
        :param u1
        :type u1:INTEGER
        :param low2
        :type low2:INTEGER
        :param u2
        :type u2:INTEGER
References ifclisttoarray().
Referenced by ifc4.ifcbsplinesurface.controlpoints(), and ifc4.ifcrationalbsplinesurfacewithknots.weights().
ifcmlstotalthickness()
def ifc4.ifcmlstotalthickness (layerset)
FUNCTION ifcmlstotalthickness #.
        :param layerset
        :type layerset:ifcmateriallayerset
Referenced by ifc4.ifcmateriallayerset.totalthickness().
ifcnormalise()
def ifc4.ifcnormalise (arg)
        :param arg
        :type arg:ifcvectorordirection
Referenced by ifcbaseaxis(), ifcbuildaxes(), ifccrossproduct(), ifcdotproduct(), ifcfirstprojaxis(), ifcscalartimesvector(), ifcsecondprojaxis(), ifcvectordifference(), ifcvectorsum(), and ifc4.ifcaxis1placement.z().
ifcorthogonalcomplement()
def ifc4.ifcorthogonalcomplement (vec)
FUNCTION ifcorthogonalcomplement #.
        :param vec
        :type vec:ifcdirection
Referenced by ifcbaseaxis(), and ifcbuild2axes().
ifcpathheadtotail()
def ifc4.ifcpathheadtotail (apath)
FUNCTION ifcpathheadtotail #.
        :param apath
        :type apath:ifcpath
Referenced by ifc4.ifcpath.iscontinuous().
ifcsameaxis2placement()
def ifc4.ifcsameaxis2placement (ap1, ap2, epsilon)
FUNCTION ifcsameaxis2placement #.
        :param ap1
        :type ap1:ifcaxis2placement
        :param ap2
        :type ap2:ifcaxis2placement
        :param epsilon
        :type epsilon:REAL
References ifcsamecartesianpoint(), and ifcsamedirection().
ifcsamecartesianpoint()
def ifc4.ifcsamecartesianpoint (cp1, cp2, epsilon)
FUNCTION ifcsamecartesianpoint #.
        :param cp1
        :type cp1:ifccartesianpoint
        :param cp2
        :type cp2:ifccartesianpoint
        :param epsilon
        :type epsilon:REAL
References ifcsamevalue().
Referenced by ifcsameaxis2placement().
ifcsamedirection()
def ifc4.ifcsamedirection (dir1, dir2, epsilon)
FUNCTION ifcsamedirection #.
        :param dir1
        :type dir1:ifcdirection
        :param dir2
        :type dir2:ifcdirection
        :param epsilon
        :type epsilon:REAL
References ifcsamevalue().
Referenced by ifcsameaxis2placement().
ifcsamevalidprecision()
def ifc4.ifcsamevalidprecision (epsilon1, epsilon2)
FUNCTION ifcsamevalidprecision #.
        :param epsilon1
        :type epsilon1:REAL
        :param epsilon2
        :type epsilon2:REAL
ifcsamevalue()
def ifc4.ifcsamevalue (value1, value2, epsilon)
FUNCTION ifcsamevalue #.
        :param value1
        :type value1:REAL
        :param value2
        :type value2:REAL
        :param epsilon
        :type epsilon:REAL
Referenced by ifcsamecartesianpoint(), and ifcsamedirection().
ifcscalartimesvector()
def ifc4.ifcscalartimesvector (scalar, vec)
FUNCTION ifcscalartimesvector #.
        :param scalar
        :type scalar:REAL
        :param vec
        :type vec:ifcvectorordirection
References ifcnormalise().
Referenced by ifcfirstprojaxis(), and ifcsecondprojaxis().
ifcsecondprojaxis()
def ifc4.ifcsecondprojaxis (zaxis, xaxis, arg)
FUNCTION ifcsecondprojaxis #.
        :param zaxis
        :type zaxis:ifcdirection
        :param xaxis
        :type xaxis:ifcdirection
        :param arg
        :type arg:ifcdirection
References ifcdotproduct(), ifcnormalise(), ifcscalartimesvector(), and ifcvectordifference().
Referenced by ifcbaseaxis().
ifcshaperepresentationtypes()
def ifc4.ifcshaperepresentationtypes (reptype, items)
FUNCTION ifcshaperepresentationtypes #.
        :param reptype
        :type reptype:STRING
        :param items
        :type items:(null)
Referenced by ifc4.ifcshaperepresentation.wr24().
ifcsurfaceweightspositive()
def ifc4.ifcsurfaceweightspositive (b)
FUNCTION ifcsurfaceweightspositive #.
        :param b
        :type b:ifcrationalbsplinesurfacewithknots
Referenced by ifc4.ifcrationalbsplinesurfacewithknots.weightvaluesgreaterzero().
ifctaperedsweptareaprofiles()
def ifc4.ifctaperedsweptareaprofiles (startarea, endarea)
FUNCTION ifctaperedsweptareaprofiles #.
        :param startarea
        :type startarea:ifcprofiledef
        :param endarea
        :type endarea:ifcprofiledef
Referenced by ifc4.ifcrevolvedareasolidtapered.correctprofileassignment(), and ifc4.ifcextrudedareasolidtapered.correctprofileassignment().
ifctopologyrepresentationtypes()
def ifc4.ifctopologyrepresentationtypes (reptype, items)
FUNCTION ifctopologyrepresentationtypes #.
        :param reptype
        :type reptype:STRING
        :param items
        :type items:(null)
Referenced by ifc4.ifctopologyrepresentation.wr23().
ifcuniquepropertyname()
def ifc4.ifcuniquepropertyname (properties)
FUNCTION ifcuniquepropertyname #.
        :param properties
        :type properties:(null)
Referenced by ifc4.ifcpropertyset.uniquepropertynames(), and ifc4.ifccomplexproperty.wr22().
ifcuniquepropertytemplatenames()
def ifc4.ifcuniquepropertytemplatenames (properties)
FUNCTION ifcuniquepropertytemplatenames #.
        :param properties
        :type properties:(null)
Referenced by ifc4.ifcpropertysettemplate.uniquepropertynames(), and ifc4.ifccomplexpropertytemplate.uniquepropertynames().
ifcuniquequantitynames()
def ifc4.ifcuniquequantitynames (properties)
FUNCTION ifcuniquequantitynames #.
        :param properties
        :type properties:(null)
Referenced by ifc4.ifcelementquantity.uniquequantitynames(), and ifc4.ifcphysicalcomplexquantity.uniquequantitynames().
ifcvectordifference()
def ifc4.ifcvectordifference (arg1, arg2)
FUNCTION ifcvectordifference #.
        :param arg1
        :type arg1:ifcvectorordirection
        :param arg2
        :type arg2:ifcvectorordirection
References ifcnormalise().
Referenced by ifcfirstprojaxis(), and ifcsecondprojaxis().
ifcvectorsum()
def ifc4.ifcvectorsum (arg1, arg2)
FUNCTION ifcvectorsum #.
        :param arg1
        :type arg1:ifcvectorordirection
        :param arg2
        :type arg2:ifcvectorordirection
References ifcnormalise().
Variable Documentation
ifcactorselect
ifc4.ifcactorselect
Initial value:
 =  SELECT(
         'ifcorganization',
         'ifcperson',
         'ifcpersonandorganization',
         scope = schema_scope)
Referenced by ifc4.ifcconstraint.creatingactor(), ifc4.ifcdocumentinformation.documentowner(), ifc4.ifcapproval.givingapproval(), ifc4.ifcinventory.jurisdiction(), ifc4.ifcasset.owner(), ifc4.ifclibraryinformation.publisher(), ifc4.ifcapproval.requestingapproval(), ifc4.ifcactor.theactor(), and ifc4.ifcasset.user().
ifcappliedvalueselect
ifc4.ifcappliedvalueselect
Initial value:
 =  SELECT(
         'ifcmeasurewithunit',
         'ifcreference',
         'ifcvalue',
         scope = schema_scope)
Referenced by ifc4.ifcappliedvalue.appliedvalue().
ifcaxis2placement
ifc4.ifcaxis2placement
Initial value:
 =  SELECT(
         'ifcaxis2placement2d',
         'ifcaxis2placement3d',
         scope = schema_scope)
Referenced by ifc4.ifcrepresentationmap.mappingorigin(), ifc4.ifcplanarbox.placement(), ifc4.ifctextliteral.placement(), ifc4.ifcconic.position(), ifc4.ifclocalplacement.relativeplacement(), and ifc4.ifcgeometricrepresentationcontext.worldcoordinatesystem().
ifcbendingparameterselect
ifc4.ifcbendingparameterselect
Initial value:
 =  SELECT(
         'ifclengthmeasure',
         'ifcplaneanglemeasure',
         scope = schema_scope)
ifcbooleanoperand
ifc4.ifcbooleanoperand
Initial value:
 =  SELECT(
         'ifcbooleanresult',
         'ifccsgprimitive3d',
         'ifchalfspacesolid',
         'ifcsolidmodel',
         scope = schema_scope)
Referenced by ifc4.ifcbooleanresult.firstoperand(), and ifc4.ifcbooleanresult.secondoperand().
ifcclassificationreferenceselect
ifc4.ifcclassificationreferenceselect
Initial value:
 =  SELECT(
         'ifcclassification',
         'ifcclassificationreference',
         scope = schema_scope)
Referenced by ifc4.ifcclassificationreference.referencedsource().
ifcclassificationselect
ifc4.ifcclassificationselect
Initial value:
 =  SELECT(
         'ifcclassification',
         'ifcclassificationreference',
         scope = schema_scope)
Referenced by ifc4.ifcrelassociatesclassification.relatingclassification().
ifccolour
ifc4.ifccolour
Initial value:
 =  SELECT(
         'ifccolourspecification',
         'ifcpredefinedcolour',
         scope = schema_scope)
Referenced by ifc4.ifctextstylefordefinedfont.backgroundcolour(), ifc4.ifctextstylefordefinedfont.colour(), and ifc4.ifccurvestyle.curvecolour().
ifccolourorfactor
ifc4.ifccolourorfactor
Initial value:
 =  SELECT(
         'ifccolourrgb',
         'ifcnormalisedratiomeasure',
         scope = schema_scope)
Referenced by ifc4.ifcsurfacestylerendering.diffusecolour(), ifc4.ifcsurfacestylerendering.diffusetransmissioncolour(), ifc4.ifcsurfacestylerendering.reflectioncolour(), ifc4.ifcsurfacestylerendering.specularcolour(), and ifc4.ifcsurfacestylerendering.transmissioncolour().
ifccomplexnumber
ifc4.ifccomplexnumber = ARRAY(1,2,'REAL', scope = schema_scope)
ifccompoundplaneanglemeasure
ifc4.ifccompoundplaneanglemeasure = LIST(3,4,'INTEGER', scope = schema_scope)
ifccoordinatereferencesystemselect
ifc4.ifccoordinatereferencesystemselect
Initial value:
 =  SELECT(
         'ifccoordinatereferencesystem',
         'ifcgeometricrepresentationcontext',
         scope = schema_scope)
Referenced by ifc4.ifccoordinateoperation.sourcecrs().
ifccsgselect
ifc4.ifccsgselect
Initial value:
 =  SELECT(
         'ifcbooleanresult',
         'ifccsgprimitive3d',
         scope = schema_scope)
Referenced by ifc4.ifccsgsolid.treerootexpression().
ifccurvefontorscaledcurvefontselect
ifc4.ifccurvefontorscaledcurvefontselect
Initial value:
 =  SELECT(
         'ifccurvestylefontandscaling',
         'ifccurvestylefontselect',
         scope = schema_scope)
Referenced by ifc4.ifccurvestyle.curvefont().
ifccurveonsurface
ifc4.ifccurveonsurface
Initial value:
 =  SELECT(
         'ifccompositecurveonsurface',
         'ifcpcurve',
         scope = schema_scope)
ifccurveoredgecurve
ifc4.ifccurveoredgecurve
Initial value:
 =  SELECT(
         'ifcboundedcurve',
         'ifcedgecurve',
         scope = schema_scope)
Referenced by ifc4.ifcconnectioncurvegeometry.curveonrelatedelement(), and ifc4.ifcconnectioncurvegeometry.curveonrelatingelement().
ifccurvestylefontselect
ifc4.ifccurvestylefontselect
Initial value:
 =  SELECT(
         'ifccurvestylefont',
         'ifcpredefinedcurvefont',
         scope = schema_scope)
Referenced by ifc4.ifccurvestylefontandscaling.curvefont().
ifcdefinitionselect
ifc4.ifcdefinitionselect
Initial value:
 =  SELECT(
         'ifcobjectdefinition',
         'ifcpropertydefinition',
         scope = schema_scope)
ifcderivedmeasurevalue
ifc4.ifcderivedmeasurevalue
ifcdocumentselect
ifc4.ifcdocumentselect
Initial value:
 =  SELECT(
         'ifcdocumentinformation',
         'ifcdocumentreference',
         scope = schema_scope)
Referenced by ifc4.ifcrelassociatesdocument.relatingdocument().
ifcfillstyleselect
ifc4.ifcfillstyleselect
Initial value:
 =  SELECT(
         'ifccolour',
         'ifcexternallydefinedhatchstyle',
         'ifcfillareastylehatching',
         'ifcfillareastyletiles',
         scope = schema_scope)
ifcgeometricsetselect
ifc4.ifcgeometricsetselect
Initial value:
 =  SELECT(
         'ifccurve',
         'ifcpoint',
         'ifcsurface',
         scope = schema_scope)
ifcgridplacementdirectionselect
ifc4.ifcgridplacementdirectionselect
Initial value:
 =  SELECT(
         'ifcdirection',
         'ifcvirtualgridintersection',
         scope = schema_scope)
Referenced by ifc4.ifcgridplacement.placementrefdirection().
ifchatchlinedistanceselect
ifc4.ifchatchlinedistanceselect
Initial value:
 =  SELECT(
         'ifcpositivelengthmeasure',
         'ifcvector',
         scope = schema_scope)
Referenced by ifc4.ifcfillareastylehatching.startofnexthatchline().
ifclayereditem
ifc4.ifclayereditem
Initial value:
 =  SELECT(
         'ifcrepresentation',
         'ifcrepresentationitem',
         scope = schema_scope)
ifclibraryselect
ifc4.ifclibraryselect
Initial value:
 =  SELECT(
         'ifclibraryinformation',
         'ifclibraryreference',
         scope = schema_scope)
Referenced by ifc4.ifcrelassociateslibrary.relatinglibrary().
ifclightdistributiondatasourceselect
ifc4.ifclightdistributiondatasourceselect
Initial value:
 =  SELECT(
         'ifcexternalreference',
         'ifclightintensitydistribution',
         scope = schema_scope)
Referenced by ifc4.ifclightsourcegoniometric.lightdistributiondatasource().
ifcmaterialselect
ifc4.ifcmaterialselect
Initial value:
 =  SELECT(
         'ifcmaterialdefinition',
         'ifcmateriallist',
         'ifcmaterialusagedefinition',
         scope = schema_scope)
Referenced by ifc4.ifcrelassociatesmaterial.relatingmaterial().
ifcmeasurevalue
ifc4.ifcmeasurevalue
Initial value:
 =  SELECT(
         'ifcamountofsubstancemeasure',
         'ifcareameasure',
         'ifccomplexnumber',
         'ifccontextdependentmeasure',
         'ifccountmeasure',
         'ifcdescriptivemeasure',
         'ifcelectriccurrentmeasure',
         'ifclengthmeasure',
         'ifcluminousintensitymeasure',
         'ifcmassmeasure',
         'ifcnonnegativelengthmeasure',
         'ifcnormalisedratiomeasure',
         'ifcnumericmeasure',
         'ifcparametervalue',
         'ifcplaneanglemeasure',
         'ifcpositivelengthmeasure',
         'ifcpositiveplaneanglemeasure',
         'ifcpositiveratiomeasure',
         'ifcratiomeasure',
         'ifcsolidanglemeasure',
         'ifcthermodynamictemperaturemeasure',
         'ifctimemeasure',
         'ifcvolumemeasure',
         scope = schema_scope)
ifcmetricvalueselect
ifc4.ifcmetricvalueselect
Initial value:
 =  SELECT(
         'ifcappliedvalue',
         'ifcmeasurewithunit',
         'ifcreference',
         'ifctable',
         'ifctimeseries',
         'ifcvalue',
         scope = schema_scope)
Referenced by ifc4.ifcmetric.datavalue().
ifcmodulusofrotationalsubgradereactionselect
ifc4.ifcmodulusofrotationalsubgradereactionselect
Initial value:
 =  SELECT(
         'ifcboolean',
         'ifcmodulusofrotationalsubgradereactionmeasure',
         scope = schema_scope)
Referenced by ifc4.ifcboundaryedgecondition.rotationalstiffnessbylengthx(), ifc4.ifcboundaryedgecondition.rotationalstiffnessbylengthy(), and ifc4.ifcboundaryedgecondition.rotationalstiffnessbylengthz().
ifcmodulusofsubgradereactionselect
ifc4.ifcmodulusofsubgradereactionselect
Initial value:
 =  SELECT(
         'ifcboolean',
         'ifcmodulusofsubgradereactionmeasure',
         scope = schema_scope)
Referenced by ifc4.ifcboundaryfacecondition.translationalstiffnessbyareax(), ifc4.ifcboundaryfacecondition.translationalstiffnessbyareay(), and ifc4.ifcboundaryfacecondition.translationalstiffnessbyareaz().
ifcmodulusoftranslationalsubgradereactionselect
ifc4.ifcmodulusoftranslationalsubgradereactionselect
Initial value:
 =  SELECT(
         'ifcboolean',
         'ifcmodulusoflinearsubgradereactionmeasure',
         scope = schema_scope)
Referenced by ifc4.ifcboundaryedgecondition.translationalstiffnessbylengthx(), ifc4.ifcboundaryedgecondition.translationalstiffnessbylengthy(), and ifc4.ifcboundaryedgecondition.translationalstiffnessbylengthz().
ifcobjectreferenceselect
ifc4.ifcobjectreferenceselect
Initial value:
 =  SELECT(
         'ifcaddress',
         'ifcappliedvalue',
         'ifcexternalreference',
         'ifcmaterialdefinition',
         'ifcorganization',
         'ifcperson',
         'ifcpersonandorganization',
         'ifctable',
         'ifctimeseries',
         scope = schema_scope)
Referenced by ifc4.ifcpropertyreferencevalue.propertyreference().
ifcpointorvertexpoint
ifc4.ifcpointorvertexpoint
Initial value:
 =  SELECT(
         'ifcpoint',
         'ifcvertexpoint',
         scope = schema_scope)
Referenced by ifc4.ifcconnectionpointgeometry.pointonrelatedelement(), and ifc4.ifcconnectionpointgeometry.pointonrelatingelement().
ifcpresentationstyleselect
ifc4.ifcpresentationstyleselect
Initial value:
 =  SELECT(
         'ifccurvestyle',
         'ifcfillareastyle',
         'ifcnullstyle',
         'ifcsurfacestyle',
         'ifctextstyle',
         scope = schema_scope)
ifcprocessselect
ifc4.ifcprocessselect
Initial value:
 =  SELECT(
         'ifcprocess',
         'ifctypeprocess',
         scope = schema_scope)
Referenced by ifc4.ifcrelassignstoprocess.relatingprocess().
ifcproductrepresentationselect
ifc4.ifcproductrepresentationselect
Initial value:
 =  SELECT(
         'ifcproductdefinitionshape',
         'ifcrepresentationmap',
         scope = schema_scope)
Referenced by ifc4.ifcshapeaspect.partofproductdefinitionshape().
ifcproductselect
ifc4.ifcproductselect
Initial value:
 =  SELECT(
         'ifcproduct',
         'ifctypeproduct',
         scope = schema_scope)
Referenced by ifc4.ifcrelassignstoproduct.relatingproduct().
ifcpropertysetdefinitionselect
ifc4.ifcpropertysetdefinitionselect
Initial value:
 =  SELECT(
         'ifcpropertysetdefinition',
         'ifcpropertysetdefinitionset',
         scope = schema_scope)
Referenced by ifc4.ifcreldefinesbyproperties.relatingpropertydefinition().
ifcpropertysetdefinitionset
ifc4.ifcpropertysetdefinitionset = SET(1,None,'ifcpropertysetdefinition', scope = schema_scope)
ifcrepresentationcontextsamewcs
ifc4.ifcrepresentationcontextsamewcs = Rule()
RULE ifcrepresentationcontextsamewcs #.
ifcresourceobjectselect
ifc4.ifcresourceobjectselect
Initial value:
 =  SELECT(
         'ifcactorrole',
         'ifcappliedvalue',
         'ifcapproval',
         'ifcconstraint',
         'ifccontextdependentunit',
         'ifcconversionbasedunit',
         'ifcexternalinformation',
         'ifcexternalreference',
         'ifcmaterialdefinition',
         'ifcorganization',
         'ifcperson',
         'ifcpersonandorganization',
         'ifcphysicalquantity',
         'ifcprofiledef',
         'ifcpropertyabstraction',
         'ifctimeseries',
         scope = schema_scope)
ifcresourceselect
ifc4.ifcresourceselect
Initial value:
 =  SELECT(
         'ifcresource',
         'ifctyperesource',
         scope = schema_scope)
Referenced by ifc4.ifcrelassignstoresource.relatingresource().
ifcrotationalstiffnessselect
ifc4.ifcrotationalstiffnessselect
Initial value:
 =  SELECT(
         'ifcboolean',
         'ifcrotationalstiffnessmeasure',
         scope = schema_scope)
Referenced by ifc4.ifcboundarynodecondition.rotationalstiffnessx(), ifc4.ifcboundarynodecondition.rotationalstiffnessy(), and ifc4.ifcboundarynodecondition.rotationalstiffnessz().
ifcshell
ifc4.ifcshell
Initial value:
 =  SELECT(
         'ifcclosedshell',
         'ifcopenshell',
         scope = schema_scope)
ifcsimplevalue
ifc4.ifcsimplevalue
Initial value:
 =  SELECT(
         'ifcboolean',
         'ifcdate',
         'ifcdatetime',
         'ifcduration',
         'ifcidentifier',
         'ifcinteger',
         'ifclabel',
         'ifclogical',
         'ifcreal',
         'ifctext',
         'ifctime',
         'ifctimestamp',
         scope = schema_scope)
ifcsingleprojectinstance
ifc4.ifcsingleprojectinstance = Rule()
RULE ifcsingleprojectinstance #.
ifcsizeselect
ifc4.ifcsizeselect
Initial value:
 =  SELECT(
         'ifcdescriptivemeasure',
         'ifclengthmeasure',
         'ifcnormalisedratiomeasure',
         'ifcpositivelengthmeasure',
         'ifcpositiveratiomeasure',
         'ifcratiomeasure',
         scope = schema_scope)
Referenced by ifc4.ifccurvestyle.curvewidth(), ifc4.ifctextstylefontmodel.fontsize(), ifc4.ifctextstyletextmodel.letterspacing(), ifc4.ifctextstyletextmodel.lineheight(), ifc4.ifctextstyletextmodel.textindent(), and ifc4.ifctextstyletextmodel.wordspacing().
ifcsolidorshell
ifc4.ifcsolidorshell
Initial value:
 =  SELECT(
         'ifcclosedshell',
         'ifcsolidmodel',
         scope = schema_scope)
Referenced by ifc4.ifcconnectionvolumegeometry.volumeonrelatedelement(), and ifc4.ifcconnectionvolumegeometry.volumeonrelatingelement().
ifcspaceboundaryselect
ifc4.ifcspaceboundaryselect
Initial value:
 =  SELECT(
         'ifcexternalspatialelement',
         'ifcspace',
         scope = schema_scope)
Referenced by ifc4.ifcrelspaceboundary.relatingspace().
ifcspecularhighlightselect
ifc4.ifcspecularhighlightselect
Initial value:
 =  SELECT(
         'ifcspecularexponent',
         'ifcspecularroughness',
         scope = schema_scope)
Referenced by ifc4.ifcsurfacestylerendering.specularhighlight().
ifcstructuralactivityassignmentselect
ifc4.ifcstructuralactivityassignmentselect
Initial value:
 =  SELECT(
         'ifcelement',
         'ifcstructuralitem',
         scope = schema_scope)
Referenced by ifc4.ifcrelconnectsstructuralactivity.relatingelement().
ifcstyleassignmentselect
ifc4.ifcstyleassignmentselect
Initial value:
 =  SELECT(
         'ifcpresentationstyle',
         'ifcpresentationstyleassignment',
         scope = schema_scope)
ifcsurfaceorfacesurface
ifc4.ifcsurfaceorfacesurface
Initial value:
 =  SELECT(
         'ifcfacebasedsurfacemodel',
         'ifcfacesurface',
         'ifcsurface',
         scope = schema_scope)
Referenced by ifc4.ifcconnectionsurfacegeometry.surfaceonrelatedelement(), and ifc4.ifcconnectionsurfacegeometry.surfaceonrelatingelement().
ifcsurfacestyleelementselect
ifc4.ifcsurfacestyleelementselect
Initial value:
 =  SELECT(
         'ifcexternallydefinedsurfacestyle',
         'ifcsurfacestylelighting',
         'ifcsurfacestylerefraction',
         'ifcsurfacestyleshading',
         'ifcsurfacestylewithtextures',
         scope = schema_scope)
ifctextfontselect
ifc4.ifctextfontselect
Initial value:
 =  SELECT(
         'ifcexternallydefinedtextfont',
         'ifcpredefinedtextfont',
         scope = schema_scope)
Referenced by ifc4.ifctextstyle.textfontstyle().
ifctimeorratioselect
ifc4.ifctimeorratioselect
Initial value:
 =  SELECT(
         'ifcduration',
         'ifcratiomeasure',
         scope = schema_scope)
Referenced by ifc4.ifclagtime.lagvalue().
ifctranslationalstiffnessselect
ifc4.ifctranslationalstiffnessselect
Initial value:
 =  SELECT(
         'ifcboolean',
         'ifclinearstiffnessmeasure',
         scope = schema_scope)
Referenced by ifc4.ifcboundarynodecondition.translationalstiffnessx(), ifc4.ifcboundarynodecondition.translationalstiffnessy(), and ifc4.ifcboundarynodecondition.translationalstiffnessz().
ifctrimmingselect
ifc4.ifctrimmingselect
Initial value:
 =  SELECT(
         'ifccartesianpoint',
         'ifcparametervalue',
         scope = schema_scope)
ifcunit
ifc4.ifcunit
Initial value:
 =  SELECT(
         'ifcderivedunit',
         'ifcmonetaryunit',
         'ifcnamedunit',
         scope = schema_scope)
Referenced by ifc4.ifcpropertytablevalue.definedunit(), ifc4.ifcpropertytablevalue.definingunit(), ifc4.ifcsimplepropertytemplate.primaryunit(), ifc4.ifcsimplepropertytemplate.secondaryunit(), ifc4.ifcpropertyenumeration.unit(), ifc4.ifcpropertylistvalue.unit(), ifc4.ifcpropertyboundedvalue.unit(), ifc4.ifctimeseries.unit(), ifc4.ifcpropertysinglevalue.unit(), ifc4.ifctablecolumn.unit(), and ifc4.ifcmeasurewithunit.unitcomponent().
ifcvalue
ifc4.ifcvalue
Initial value:
 =  SELECT(
         'ifcderivedmeasurevalue',
         'ifcmeasurevalue',
         'ifcsimplevalue',
         scope = schema_scope)
Referenced by ifc4.ifcpropertyboundedvalue.lowerboundvalue(), ifc4.ifcpropertysinglevalue.nominalvalue(), ifc4.ifcpropertyboundedvalue.setpointvalue(), ifc4.ifcpropertyboundedvalue.upperboundvalue(), and ifc4.ifcmeasurewithunit.valuecomponent().
ifcvectorordirection
ifc4.ifcvectorordirection
Initial value:
 =  SELECT(
         'ifcdirection',
         'ifcvector',
         scope = schema_scope)
ifcwarpingstiffnessselect
ifc4.ifcwarpingstiffnessselect
Initial value:
 =  SELECT(
         'ifcboolean',
         'ifcwarpingmomentmeasure',
         scope = schema_scope)
Referenced by ifc4.ifcboundarynodeconditionwarping.warpingstiffness().
schema_name
string ifc4.schema_name = 'ifc4'
schema_scope
ifc4.schema_scope = sys.modules[__name__]