FreeCAD: StdMeshers_QuadFromMedialAxis_1D2D::Algo1D Class Reference
StdMeshers_QuadFromMedialAxis_1D2D::Algo1D Class Reference
1D algo
Public Member Functions
Algo1D (int studyId, SMESH_Gen *gen)
virtual bool CheckHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, SMESH_Hypothesis::Hypothesis_Status &aStatus)
Check hypothesis definition to mesh a shape.
void ComputeDistribution (SMESH_MesherHelper &theHelper, const gp_Pnt &thePnt1, const gp_Pnt &thePnt2, list< double > &theParams)
virtual const list< const SMESHDS_Hypothesis * > & GetUsedHypothesis (SMESH_Mesh &, const TopoDS_Shape &, const bool)
void SetRadialDistribution (const SMESHDS_Hypothesis *hyp)
void SetSegmentLength (double len)
Public Member Functions inherited from StdMeshers_Regular_1D
virtual void CancelCompute ()
Pass CancelCompute() to a child algorithm.
virtual bool CheckHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, SMESH_Hypothesis::Hypothesis_Status &aStatus)
Check hypothesis definition to mesh a shape.
virtual bool Compute (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape)
Computes mesh on a shape.
virtual bool Evaluate (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, MapShapeNbElems &aResMap)
evaluates size of prospective mesh on a shape
virtual const std::list< const SMESHDS_Hypothesis * > & GetUsedHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, const bool=true)
virtual void SetEventListener (SMESH_subMesh *subMesh)
Sets event listener to submeshes if necessary.
StdMeshers_Regular_1D (int hypId, int studyId, SMESH_Gen *gen)
void SubmeshRestored (SMESH_subMesh *subMesh)
Allow algo to do something after persistent restoration.
virtual ~StdMeshers_Regular_1D ()
Public Member Functions inherited from SMESH_1D_Algo
SMESH_1D_Algo (int hypId, int studyId, SMESH_Gen *gen)
SMESH_1D_Algo (int hypId, int studyId, SMESH_Gen *gen)
virtual ~SMESH_1D_Algo ()
Public Member Functions inherited from SMESH_Algo
virtual void CancelCompute ()
Sets _computeCanceled to true. It's usage depends on implementation of a particular mesher.
virtual bool CheckHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, SMESH_Hypothesis::Hypothesis_Status &aStatus)=0
Check hypothesis definition to mesh a shape.
virtual bool Compute (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape)=0
Computes mesh on a shape.
virtual bool Compute (SMESH_Mesh &aMesh, SMESH_MesherHelper *aHelper)
Computes mesh without geometry.
virtual bool Evaluate (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, MapShapeNbElems &aResMap)=0
evaluates size of prospective mesh on a shape
const std::list< const SMESHDS_Hypothesis * > & GetAppliedHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, const bool ignoreAuxiliary=true) const
Returns a list of compatible hypotheses assigned to a shape in a mesh.
const SMESH_HypoFilter * GetCompatibleHypoFilter (const bool ignoreAuxiliary) const
Returns the filter recognizing only compatible hypotheses.
const std::vector< std::string > & GetCompatibleHypothesis ()
Returns all types of compatible hypotheses.
SMESH_ComputeErrorPtr GetComputeError () const
return compute error
const Features & GetFeatures () const
virtual double GetProgress () const
If possible, returns progress of computation [0.,1.].
double GetProgressByTic () const
Return compute progress by nb of calls of this method.
virtual const std::list< const SMESHDS_Hypothesis * > & GetUsedHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, const bool ignoreAuxiliary=true) const
Returns a list of compatible hypotheses used to mesh a shape.
void InitComputeError ()
initialize compute error etc. before call of Compute()
virtual std::istream & LoadFrom (std::istream &load)
Loads nothing from a stream.
bool NeedDiscreteBoundary () const
bool NeedLowerHyps (int dim) const
bool NeedShape () const
int NumberOfPoints (SMESH_Mesh &aMesh, const TopoDS_Wire &W)
bool OnlyUnaryInput () const
virtual std::ostream & SaveTo (std::ostream &save)
Saves nothing in a stream.
virtual void SetEventListener (SMESH_subMesh *subMesh)
Sets event listener to submeshes if necessary.
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)
Just return false as the algorithm does not hold parameters values.
SMESH_Algo (int hypId, int studyId, SMESH_Gen *gen)
Creates algorithm.
std::vector< SMESH_subMesh * > & SubMeshesToCompute ()
virtual void SubmeshRestored (SMESH_subMesh *subMesh)
Allow algo to do something after persistent restoration.
bool SupportSubmeshes () const
virtual ~SMESH_Algo ()
Destructor.
Public Member Functions inherited from SMESH_Hypothesis
void ClearParameters ()
virtual bool DataDependOnParams () const
The returned value is used by NotifySubMeshesHypothesisModification() to decide to call subMesh->AlgoStateEngine(MODIF_HYP, hyp) or not if subMesh is ready to be computed (algo+hyp==OK) but not yet computed. True result is reasonable for example if EventListeners depend on parameters of hypothesis.
virtual int GetDim () const
SMESH_Gen * GetGen () const
char * GetLastParameters () const
virtual const char * GetLibName () const
SMESH_Mesh * GetMeshByPersistentID (int id)
Find a mesh with given persistent ID.
char * GetParameters () const
virtual int GetShapeType () const
int GetStudyId () const
virtual bool IsAuxiliary () const
Return true if me is an auxiliary hypothesis.
virtual void NotifySubMeshesHypothesisModification ()
void SetLastParameters (const char *theParameters)
void SetLibName (const char *theLibName)
void SetParameters (const char *theParameters)
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)=0
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)=0
Initialize my parameter values by the mesh built on the geometry.
SMESH_Hypothesis (int hypId, int studyId, SMESH_Gen *gen)
virtual ~SMESH_Hypothesis ()
Public Member Functions inherited from SMESHDS_Hypothesis
int GetID () const
const char * GetName () const
int GetType () const
bool IsSameName (const SMESHDS_Hypothesis &other) const
Compare types of hypotheses.
virtual std::istream & LoadFrom (std::istream &load)=0
bool operator!= (const SMESHDS_Hypothesis &other) const
virtual bool operator== (const SMESHDS_Hypothesis &other) const
virtual std::ostream & SaveTo (std::ostream &save)=0
SMESHDS_Hypothesis (int hypId)
virtual ~SMESHDS_Hypothesis ()
Additional Inherited Members
Public Types inherited from SMESH_Algo
enum EMeshError { MEr_OK = 0 , MEr_HOLES , MEr_BAD_ORI , MEr_EMPTY }
Public Types inherited from SMESH_Hypothesis
enum Hypothesis_Status {
HYP_OK = 0 , HYP_MISSING , HYP_CONCURENT , HYP_BAD_PARAMETER ,
HYP_HIDDEN_ALGO , HYP_HIDING_ALGO , HYP_UNKNOWN_FATAL , HYP_INCOMPATIBLE ,
HYP_NOTCONFORM , HYP_ALREADY_EXIST , HYP_BAD_DIM , HYP_BAD_SUBSHAPE ,
HYP_BAD_GEOMETRY , HYP_NEED_SHAPE , HYP_INCOMPAT_HYPS
}
Public Types inherited from SMESHDS_Hypothesis
enum hypothesis_type {
PARAM_ALGO , ALGO_0D , ALGO_1D , ALGO_2D ,
ALGO_3D
}
Static Public Member Functions inherited from SMESH_Algo
static GeomAbs_Shape Continuity (TopoDS_Edge E1, TopoDS_Edge E2)
Return continuity of two edges.
static double EdgeLength (const TopoDS_Edge &E)
Compute length of an edge.
static const Features & GetFeatures (const std::string &algoType)
Returns a structure describing algorithm features.
static EMeshError GetMeshError (SMESH_subMesh *subMesh)
Finds topological errors of a sub-mesh.
static bool GetNodeParamOnEdge (const SMESHDS_Mesh *theMesh, const TopoDS_Edge &theEdge, std::vector< double > &theParams)
Fill vector of node parameters on geometrical edge, including vertex nodes.
static bool GetSortedNodesOnEdge (const SMESHDS_Mesh *theMesh, const TopoDS_Edge &theEdge, const bool ignoreMediumNodes, std::map< double, const SMDS_MeshNode * > &theNodes, const SMDSAbs_ElementType typeToCheck=SMDSAbs_All)
Fill map of node parameter on geometrical edge to node it-self.
static bool IsContinuous (const TopoDS_Edge &E1, const TopoDS_Edge &E2)
Return true if an edge can be considered as a continuation of another.
static bool isDegenerated (const TopoDS_Edge &E)
Return true if an edge has no 3D curve.
static bool IsStraight (const TopoDS_Edge &E, const bool degenResult=false)
Return true if an edge can be considered straight.
static const SMDS_MeshNode * VertexNode (const TopoDS_Vertex &V, const SMESH_Mesh *mesh)
Return the node built on a vertex. A node moved to other geometry by MergeNodes() is also returned.
static const SMDS_MeshNode * VertexNode (const TopoDS_Vertex &V, const SMESHDS_Mesh *meshDS)
Return the node built on a vertex.
static const SMDS_MeshNode * VertexNode (const TopoDS_Vertex &V, const SMESHDS_SubMesh *edgeSM, const SMESH_Mesh *mesh, const bool checkV=true)
Return the node built on a vertex. A node moved to other geometry by MergeNodes() is also returned.
Static Public Member Functions inherited from SMESH_Hypothesis
static bool IsStatusFatal (Hypothesis_Status theStatus)
Protected Types inherited from StdMeshers_Regular_1D
enum HypothesisType {
LOCAL_LENGTH , MAX_LENGTH , NB_SEGMENTS , BEG_END_LENGTH ,
DEFLECTION , ARITHMETIC_1D , FIXED_POINTS_1D , ADAPTIVE ,
GEOMETRIC_1D , NONE
}
enum IValueIndex { NB_SEGMENTS_IND = 0 , DISTR_TYPE_IND = 1 , CONV_MODE_IND = 2 }
enum SValueIndex { EXPR_FUNC_IND = 0 }
enum ValueIndex {
SCALE_FACTOR_IND = 0 , BEG_LENGTH_IND = 0 , END_LENGTH_IND = 1 , DEFLECTION_IND = 0 ,
PRECISION_IND = 1
}
enum VValueIndex { TAB_FUNC_IND = 0 }
Protected Member Functions inherited from StdMeshers_Regular_1D
virtual bool computeInternalParameters (SMESH_Mesh &theMesh, Adaptor3d_Curve &theC3d, double theLength, double theFirstU, double theLastU, std::list< double > &theParameters, const bool theReverse, bool theConsiderPropagation=false)
virtual void redistributeNearVertices (SMESH_Mesh &theMesh, Adaptor3d_Curve &theC3d, double theLength, std::list< double > &theParameters, const TopoDS_Vertex &theVf, const TopoDS_Vertex &theVl)
Tune parameters to fit "SegmentLengthAroundVertex" hypothesis.
Protected Member Functions inherited from SMESH_Algo
void addBadInputElement (const SMDS_MeshElement *elem)
store a bad input element preventing computation, which may be a temporary one i.e. not residing the mesh, then it will be deleted by InitComputeError()
void addBadInputElements (const SMESHDS_SubMesh *sm, const bool addNodes=false)
bool error (const SMESH_Comment &comment="")
store COMPERR_ALGO_FAILED error and comment and then return false
bool error (int error, const SMESH_Comment &comment="")
store error and comment and then return (error == COMPERR_OK)
bool error (SMESH_ComputeErrorPtr error)
store error and return error->IsOK()
Static Protected Member Functions inherited from StdMeshers_Regular_1D
static const StdMeshers_SegmentLengthAroundVertex * getVertexHyp (SMESH_Mesh &theMesh, const TopoDS_Vertex &theV)
Return StdMeshers_SegmentLengthAroundVertex assigned to vertex.
Detailed Description
1D algo
Constructor & Destructor Documentation
Algo1D()
StdMeshers_QuadFromMedialAxis_1D2D::Algo1D::Algo1D (int studyId, SMESH_Gen * gen)
Member Function Documentation
CheckHypothesis()
virtual bool StdMeshers_QuadFromMedialAxis_1D2D::Algo1D::CheckHypothesis (SMESH_Mesh & aMesh, const TopoDS_Shape & aShape, SMESH_Hypothesis::Hypothesis_Status & aStatus) virtual
Check hypothesis definition to mesh a shape.
Parameters
aMesh - the mesh
aShape - the shape
aStatus - check result
Return values
bool - true if hypothesis is well defined
Textual description of a problem can be stored in _comment field.
Reimplemented from StdMeshers_Regular_1D.
References StdMeshers_Regular_1D::CheckHypothesis().
Referenced by ComputeDistribution().
ComputeDistribution()
void StdMeshers_QuadFromMedialAxis_1D2D::Algo1D::ComputeDistribution (SMESH_MesherHelper & theHelper, const gp_Pnt & thePnt1, const gp_Pnt & thePnt2, list< double > & theParams)
References CheckHypothesis(), StdMeshers_Regular_1D::computeInternalParameters(), and SMESH_MesherHelper::GetMesh().
GetUsedHypothesis()
virtual const list< const SMESHDS_Hypothesis * > & StdMeshers_QuadFromMedialAxis_1D2D::Algo1D::GetUsedHypothesis (SMESH_Mesh & aMesh, const TopoDS_Shape & aShape, const bool ignoreAuxiliary) virtual
See comments in SMESH_Algo.cxx
Reimplemented from StdMeshers_Regular_1D.
SetRadialDistribution()
void StdMeshers_QuadFromMedialAxis_1D2D::Algo1D::SetRadialDistribution (const SMESHDS_Hypothesis * hyp)
References StdMeshers_Regular_1D::DISTR_TYPE_IND, StdMeshers_Regular_1D::NB_SEGMENTS, and StdMeshers_Regular_1D::NB_SEGMENTS_IND.
SetSegmentLength()
void StdMeshers_QuadFromMedialAxis_1D2D::Algo1D::SetSegmentLength (double len)
References StdMeshers_Regular_1D::BEG_LENGTH_IND, StdMeshers_Regular_1D::LOCAL_LENGTH, and StdMeshers_Regular_1D::PRECISION_IND.
The documentation for this class was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_QuadFromMedialAxis_1D2D.cpp