FreeCAD: ImageGui::GLImageBox Class Reference
ImageGui::GLImageBox Class Reference
#include <OpenGLImageBox.h>
Public Slots
void handleLoggedMessage (const QOpenGLDebugMessage &debugMessage)
Signals
void drawGraphics ()
void drawGraphics ()
Public Member Functions
void clearColorMap ()
void clearColorMap ()
void clearImage ()
void clearImage ()
int createColorMap (int numEntriesReq=0, bool Initialise=true)
int createColorMap (int numEntriesReq=0, bool Initialise=true)
int createImageCopy (void *pSrcPixelData, unsigned long width, unsigned long height, int format, unsigned short numSigBitsPerSample, int displayMode=IV_DISPLAY_RESET)
int createImageCopy (void *pSrcPixelData, unsigned long width, unsigned long height, int format, unsigned short numSigBitsPerSample, int displayMode=IV_DISPLAY_RESET)
void fixBasePosCurr ()
void fixBasePosCurr ()
void getCentrePoint (int &ICx, int &ICy)
void getCentrePoint (int &ICx, int &ICy)
Image::ImageBase * getImageBasePtr ()
Image::ImageBase * getImageBasePtr ()
int getImageFormat ()
int getImageFormat ()
unsigned short getImageNumSamplesPerPix ()
unsigned short getImageNumSamplesPerPix ()
int getImageSample (int x, int y, unsigned short sampleIndex, double &value)
int getImageSample (int x, int y, unsigned short sampleIndex, double &value)
int getNumColorMapEntries () const
int getNumColorMapEntries () const
double getZoomFactor ()
double getZoomFactor ()
GLImageBox (QWidget *parent=0, const QGLWidget *shareWidget=0, Qt::WindowFlags f=0)
GLImageBox (QWidget *parent=0, Qt::WindowFlags f=Qt::WindowFlags())
double ICToWC_X (double ImageX)
double ICToWC_X (double ImageX)
double ICToWC_Y (double ImageY)
double ICToWC_Y (double ImageY)
unsigned int pixValToMapIndex (double PixVal)
unsigned int pixValToMapIndex (double PixVal)
int pointImageTo (void *pSrcPixelData, unsigned long width, unsigned long height, int format, unsigned short numSigBitsPerSample, bool takeOwnership, int displayMode=IV_DISPLAY_RESET)
int pointImageTo (void *pSrcPixelData, unsigned long width, unsigned long height, int format, unsigned short numSigBitsPerSample, bool takeOwnership, int displayMode=IV_DISPLAY_RESET)
void redraw ()
void redraw ()
void relMoveWC (int WCdx, int WCdy)
void relMoveWC (int WCdx, int WCdy)
void renderText (int x, int y, const QString &str, const QFont &fnt=QFont())
int setColorMapAlphaValue (int index, float value)
int setColorMapAlphaValue (int index, float value)
int setColorMapBlueValue (int index, float value)
int setColorMapBlueValue (int index, float value)
int setColorMapGreenValue (int index, float value)
int setColorMapGreenValue (int index, float value)
int setColorMapRedValue (int index, float value)
int setColorMapRedValue (int index, float value)
int setColorMapRGBAValue (int index, float red, float green, float blue, float alpha=1.0)
int setColorMapRGBAValue (int index, float red, float green, float blue, float alpha=1.0)
void setNormal ()
void setNormal ()
void setZoomFactor (double zoomFactor, bool useCentrePt=false, int ICx=0, int ICy=0)
void setZoomFactor (double zoomFactor, bool useCentrePt=false, int ICx=0, int ICy=0)
void stretchToFit ()
void stretchToFit ()
double WCToIC_X (double WidgetX)
double WCToIC_X (double WidgetX)
double WCToIC_Y (double WidgetY)
double WCToIC_Y (double WidgetY)
void zoom (int power, bool useCentrePt=false, int ICx=0, int ICy=0)
void zoom (int power, bool useCentrePt=false, int ICx=0, int ICy=0)
~GLImageBox ()
~GLImageBox ()
Constructor & Destructor Documentation
GLImageBox() [1/2]
GLImageBox::GLImageBox (QWidget * parent = 0, const QGLWidget * shareWidget = 0, Qt::WindowFlags f = 0)
~GLImageBox() [1/2]
GLImageBox::~GLImageBox ()
GLImageBox() [2/2]
GLImageBox::GLImageBox (QWidget * parent = 0, Qt::WindowFlags f = Qt::WindowFlags())
~GLImageBox() [2/2]
ImageGui::GLImageBox::~GLImageBox ()
Member Function Documentation
clearColorMap() [1/2]
void GLImageBox::clearColorMap ()
Referenced by createColorMap().
clearColorMap() [2/2]
void ImageGui::GLImageBox::clearColorMap ()
clearImage() [1/2]
void GLImageBox::clearImage ()
clearImage() [2/2]
void ImageGui::GLImageBox::clearImage ()
createColorMap() [1/2]
int GLImageBox::createColorMap (int numEntriesReq = 0, bool Initialise = true)
References clearColorMap().
createColorMap() [2/2]
int ImageGui::GLImageBox::createColorMap (int numEntriesReq = 0, bool Initialise = true)
createImageCopy() [1/2]
int GLImageBox::createImageCopy (void * pSrcPixelData, unsigned long width, unsigned long height, int format, unsigned short numSigBitsPerSample, int displayMode = IV_DISPLAY_RESET)
createImageCopy() [2/2]
int ImageGui::GLImageBox::createImageCopy (void * pSrcPixelData, unsigned long width, unsigned long height, int format, unsigned short numSigBitsPerSample, int displayMode = IV_DISPLAY_RESET)
drawGraphics [1/2]
void ImageGui::GLImageBox::drawGraphics () signal
drawGraphics [2/2]
void ImageGui::GLImageBox::drawGraphics () signal
fixBasePosCurr() [1/2]
void GLImageBox::fixBasePosCurr ()
fixBasePosCurr() [2/2]
void ImageGui::GLImageBox::fixBasePosCurr ()
getCentrePoint() [1/2]
void GLImageBox::getCentrePoint (int & ICx, int & ICy)
References WCToIC_X(), and WCToIC_Y().
Referenced by setZoomFactor().
getCentrePoint() [2/2]
void ImageGui::GLImageBox::getCentrePoint (int & ICx, int & ICy)
getImageBasePtr() [1/2]
Image::ImageBase* ImageGui::GLImageBox::getImageBasePtr ()
getImageBasePtr() [2/2]
Image::ImageBase* ImageGui::GLImageBox::getImageBasePtr ()
getImageFormat() [1/2]
int GLImageBox::getImageFormat ()
getImageFormat() [2/2]
int ImageGui::GLImageBox::getImageFormat ()
getImageNumSamplesPerPix() [1/2]
unsigned short GLImageBox::getImageNumSamplesPerPix ()
getImageNumSamplesPerPix() [2/2]
unsigned short ImageGui::GLImageBox::getImageNumSamplesPerPix ()
getImageSample() [1/2]
int GLImageBox::getImageSample (int x, int y, unsigned short sampleIndex, double & value)
getImageSample() [2/2]
int ImageGui::GLImageBox::getImageSample (int x, int y, unsigned short sampleIndex, double & value)
getNumColorMapEntries() [1/2]
int ImageGui::GLImageBox::getNumColorMapEntries () const
Referenced by pixValToMapIndex().
getNumColorMapEntries() [2/2]
int ImageGui::GLImageBox::getNumColorMapEntries () const
getZoomFactor() [1/2]
double ImageGui::GLImageBox::getZoomFactor ()
getZoomFactor() [2/2]
double ImageGui::GLImageBox::getZoomFactor ()
handleLoggedMessage
void GLImageBox::handleLoggedMessage (const QOpenGLDebugMessage & debugMessage) slot
ICToWC_X() [1/2]
double GLImageBox::ICToWC_X (double ImageX)
ICToWC_X() [2/2]
double ImageGui::GLImageBox::ICToWC_X (double ImageX)
ICToWC_Y() [1/2]
double GLImageBox::ICToWC_Y (double ImageY)
ICToWC_Y() [2/2]
double ImageGui::GLImageBox::ICToWC_Y (double ImageY)
pixValToMapIndex() [1/2]
unsigned int GLImageBox::pixValToMapIndex (double PixVal)
References getNumColorMapEntries().
pixValToMapIndex() [2/2]
unsigned int ImageGui::GLImageBox::pixValToMapIndex (double PixVal)
pointImageTo() [1/2]
int GLImageBox::pointImageTo (void * pSrcPixelData, unsigned long width, unsigned long height, int format, unsigned short numSigBitsPerSample, bool takeOwnership, int displayMode = IV_DISPLAY_RESET)
pointImageTo() [2/2]
int ImageGui::GLImageBox::pointImageTo (void * pSrcPixelData, unsigned long width, unsigned long height, int format, unsigned short numSigBitsPerSample, bool takeOwnership, int displayMode = IV_DISPLAY_RESET)
redraw() [1/2]
void GLImageBox::redraw (void)
Referenced by draftguitools.gui_trimex.Trimex::trimObject().
redraw() [2/2]
void ImageGui::GLImageBox::redraw ()
Referenced by draftguitools.gui_trimex.Trimex::trimObject().
relMoveWC() [1/2]
void GLImageBox::relMoveWC (int WCdx, int WCdy)
relMoveWC() [2/2]
void ImageGui::GLImageBox::relMoveWC (int WCdx, int WCdy)
renderText()
void GLImageBox::renderText (int x, int y, const QString & str, const QFont & fnt = QFont())
References femsolver.elmer.sifio::isValid().
setColorMapAlphaValue() [1/2]
int GLImageBox::setColorMapAlphaValue (int index, float value)
setColorMapAlphaValue() [2/2]
int ImageGui::GLImageBox::setColorMapAlphaValue (int index, float value)
setColorMapBlueValue() [1/2]
int GLImageBox::setColorMapBlueValue (int index, float value)
setColorMapBlueValue() [2/2]
int ImageGui::GLImageBox::setColorMapBlueValue (int index, float value)
setColorMapGreenValue() [1/2]
int GLImageBox::setColorMapGreenValue (int index, float value)
setColorMapGreenValue() [2/2]
int ImageGui::GLImageBox::setColorMapGreenValue (int index, float value)
setColorMapRedValue() [1/2]
int GLImageBox::setColorMapRedValue (int index, float value)
setColorMapRedValue() [2/2]
int ImageGui::GLImageBox::setColorMapRedValue (int index, float value)
setColorMapRGBAValue() [1/2]
int GLImageBox::setColorMapRGBAValue (int index, float red, float green, float blue, float alpha = 1.0)
setColorMapRGBAValue() [2/2]
int ImageGui::GLImageBox::setColorMapRGBAValue (int index, float red, float green, float blue, float alpha = 1.0)
setNormal() [1/2]
void GLImageBox::setNormal ()
References setZoomFactor().
setNormal() [2/2]
void ImageGui::GLImageBox::setNormal ()
setZoomFactor() [1/2]
void GLImageBox::setZoomFactor (double zoomFactor, bool useCentrePt = false, int ICx = 0, int ICy = 0)
References getCentrePoint().
Referenced by setNormal().
setZoomFactor() [2/2]
void ImageGui::GLImageBox::setZoomFactor (double zoomFactor, bool useCentrePt = false, int ICx = 0, int ICy = 0)
stretchToFit() [1/2]
void GLImageBox::stretchToFit ()
stretchToFit() [2/2]
void ImageGui::GLImageBox::stretchToFit ()
WCToIC_X() [1/2]
double GLImageBox::WCToIC_X (double WidgetX)
Referenced by getCentrePoint().
WCToIC_X() [2/2]
double ImageGui::GLImageBox::WCToIC_X (double WidgetX)
WCToIC_Y() [1/2]
double GLImageBox::WCToIC_Y (double WidgetY)
Referenced by getCentrePoint().
WCToIC_Y() [2/2]
double ImageGui::GLImageBox::WCToIC_Y (double WidgetY)
zoom() [1/2]
void ImageGui::GLImageBox::zoom (int power, bool useCentrePt = false, int ICx = 0, int ICy = 0)
zoom() [2/2]
void ImageGui::GLImageBox::zoom (int power, bool useCentrePt = false, int ICx = 0, int ICy = 0)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Image/Gui/GLImageBox.h
Sources/FreeCAD/src/Mod/Image/Gui/OpenGLImageBox.h
Sources/FreeCAD/src/Mod/Image/Gui/GLImageBox.cpp
Sources/FreeCAD/src/Mod/Image/Gui/OpenGLImageBox.cpp