FreeCAD: Part::Geometry2d Class Reference
Part::Geometry2d Class Reference abstract
#include <Geometry2d.h>
Public Member Functions
virtual Geometry2d * clone (void) const =0
returns a cloned object
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual const Handle (Geom2d_Geometry) &handle() const =0
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
virtual TopoDS_Shape toShape () const =0
virtual ~Geometry2d ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Member Functions
Geometry2d ()
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
~Geometry2d()
Geometry2d::~Geometry2d () virtual
Geometry2d()
Geometry2d::Geometry2d () protected
Member Function Documentation
clone()
virtual Geometry2d* Part::Geometry2d::clone (void) const pure virtual
returns a cloned object
Implemented in Part::Geom2dArcOfConic, Part::Geom2dConic, Part::Geom2dTrimmedCurve, Part::Geom2dOffsetCurve, Part::Geom2dLineSegment, Part::Geom2dLine, Part::Geom2dArcOfParabola, Part::Geom2dParabola, Part::Geom2dArcOfHyperbola, Part::Geom2dHyperbola, Part::Geom2dArcOfEllipse, Part::Geom2dEllipse, Part::Geom2dArcOfCircle, Part::Geom2dCircle, Part::Geom2dBSplineCurve, Part::Geom2dBezierCurve, and Part::Geom2dPoint.
Referenced by ArchPanel.CommandPanelSheet::Activated(), Part::Geometry2dPy::copy(), ArchComponent.Component::execute(), ArchCurtainWall.CurtainWall::execute(), ArchTruss.Truss::execute(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated(), and PathTests.TestPathHelix.TestPathHelix::test04().
getMemSize()
unsigned int Geometry2d::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Reimplemented in Part::Geom2dArcOfConic, Part::Geom2dConic, Part::Geom2dTrimmedCurve, Part::Geom2dOffsetCurve, Part::Geom2dLineSegment, Part::Geom2dLine, Part::Geom2dArcOfParabola, Part::Geom2dParabola, Part::Geom2dArcOfHyperbola, Part::Geom2dHyperbola, Part::Geom2dArcOfEllipse, Part::Geom2dEllipse, Part::Geom2dArcOfCircle, Part::Geom2dCircle, Part::Geom2dBSplineCurve, Part::Geom2dBezierCurve, and Part::Geom2dPoint.
Handle()
virtual const Part::Geometry2d::Handle (Geom2d_Geometry) const & pure virtual
Implemented in Part::Geom2dArcOfConic, Part::Geom2dConic, Part::Geom2dTrimmedCurve, Part::Geom2dOffsetCurve, Part::Geom2dLineSegment, Part::Geom2dLine, Part::Geom2dArcOfParabola, Part::Geom2dParabola, Part::Geom2dArcOfHyperbola, Part::Geom2dHyperbola, Part::Geom2dArcOfEllipse, Part::Geom2dEllipse, Part::Geom2dArcOfCircle, Part::Geom2dCircle, Part::Geom2dBSplineCurve, Part::Geom2dBezierCurve, and Part::Geom2dPoint.
Restore()
void Geometry2d::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Reimplemented in Part::Geom2dTrimmedCurve, Part::Geom2dOffsetCurve, Part::Geom2dLineSegment, Part::Geom2dLine, Part::Geom2dArcOfParabola, Part::Geom2dParabola, Part::Geom2dArcOfHyperbola, Part::Geom2dHyperbola, Part::Geom2dArcOfEllipse, Part::Geom2dEllipse, Part::Geom2dArcOfCircle, Part::Geom2dCircle, Part::Geom2dBSplineCurve, Part::Geom2dBezierCurve, and Part::Geom2dPoint.
Referenced by Part::Geom2dPoint::Restore(), Part::Geom2dCircle::Restore(), Part::Geom2dArcOfCircle::Restore(), Part::Geom2dEllipse::Restore(), Part::Geom2dArcOfEllipse::Restore(), Part::Geom2dHyperbola::Restore(), Part::Geom2dArcOfHyperbola::Restore(), Part::Geom2dParabola::Restore(), Part::Geom2dArcOfParabola::Restore(), and Part::Geom2dLineSegment::Restore().
Save()
void Geometry2d::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Reimplemented in Part::Geom2dTrimmedCurve, Part::Geom2dOffsetCurve, Part::Geom2dLineSegment, Part::Geom2dLine, Part::Geom2dArcOfParabola, Part::Geom2dParabola, Part::Geom2dArcOfHyperbola, Part::Geom2dHyperbola, Part::Geom2dArcOfEllipse, Part::Geom2dEllipse, Part::Geom2dArcOfCircle, Part::Geom2dCircle, Part::Geom2dBSplineCurve, Part::Geom2dBezierCurve, and Part::Geom2dPoint.
Referenced by Part::Geom2dPoint::Save(), Part::Geom2dCircle::Save(), Part::Geom2dArcOfCircle::Save(), Part::Geom2dEllipse::Save(), Part::Geom2dArcOfEllipse::Save(), Part::Geom2dHyperbola::Save(), Part::Geom2dArcOfHyperbola::Save(), Part::Geom2dParabola::Save(), Part::Geom2dArcOfParabola::Save(), and Part::Geom2dLineSegment::Save().
toShape()
virtual TopoDS_Shape Part::Geometry2d::toShape () const pure virtual
Implemented in Part::Geom2dCurve, and Part::Geom2dPoint.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/App/Geometry2d.h
Sources/FreeCAD/src/Mod/Part/App/Geometry2d.cpp