FreeCAD: InspectionGui::VisualInspection Class Reference
InspectionGui::VisualInspection Class Reference
#include <VisualInspection.h>
Public Member Functions
void accept ()
VisualInspection (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
Constructs a VisualInspection as a child of 'parent', with the name 'name' and widget flags set to 'f'.
~VisualInspection ()
Protected Slots
void loadSettings ()
void onActivateItem (QTreeWidgetItem *)
void saveSettings ()
Constructor & Destructor Documentation
VisualInspection()
VisualInspection::VisualInspection (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Constructs a VisualInspection as a child of 'parent', with the name 'name' and widget flags set to 'f'.
References InspectionGui::Ui_VisualInspection::buttonBox, draftgeoutils.intersections::connect(), Base::Type::fromName(), App::Application::getActiveDocument(), App::GetApplication(), Gui::Application::getDocument(), Gui::getMainWindow(), Draft::gui, Gui::Application::Instance, Base::Unit::Length, loadSettings(), onActivateItem(), InspectionGui::Ui_VisualInspection::searchRadius, InspectionGui::SingleSelectionItem::setCompetitiveItem(), Gui::QuantitySpinBox::setRange(), Gui::QuantitySpinBox::setUnit(), InspectionGui::Ui_VisualInspection::setupUi(), InspectionGui::Ui_VisualInspection::textLabel2, InspectionGui::Ui_VisualInspection::thickness, InspectionGui::Ui_VisualInspection::treeWidgetActual, and InspectionGui::Ui_VisualInspection::treeWidgetNominal.
~VisualInspection()
VisualInspection::~VisualInspection ()
Member Function Documentation
accept()
void VisualInspection::accept (void)
References Gui::Application::activeDocument(), Gui::Command::App, Base::Quantity::getValue(), Gui::Application::Instance, onActivateItem(), draftutils.translate::QT_TRANSLATE_NOOP, saveSettings(), InspectionGui::Ui_VisualInspection::searchRadius, InspectionGui::Ui_VisualInspection::thickness, InspectionGui::Ui_VisualInspection::treeWidgetActual, InspectionGui::Ui_VisualInspection::treeWidgetNominal, and Gui::QuantitySpinBox::value.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
loadSettings
void VisualInspection::loadSettings () protected slot
References App::GetApplication(), App::Application::GetParameterGroupByPath(), Base::Quantity::getValue(), InspectionGui::Ui_VisualInspection::searchRadius, Gui::QuantitySpinBox::setValue(), InspectionGui::Ui_VisualInspection::thickness, and Gui::QuantitySpinBox::value.
Referenced by VisualInspection().
onActivateItem
void VisualInspection::onActivateItem (QTreeWidgetItem * item) protected slot
References InspectionGui::SingleSelectionItem::getCompetitiveItem(), InspectionGui::Ui_VisualInspection::treeWidgetActual, and InspectionGui::Ui_VisualInspection::treeWidgetNominal.
Referenced by accept(), and VisualInspection().
saveSettings
void VisualInspection::saveSettings () protected slot
References App::GetApplication(), App::Application::GetParameterGroupByPath(), Base::Quantity::getValue(), InspectionGui::Ui_VisualInspection::searchRadius, InspectionGui::Ui_VisualInspection::thickness, and Gui::QuantitySpinBox::value.
Referenced by accept().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Inspection/Gui/VisualInspection.h
FreeCAD/src/Mod/Inspection/Gui/VisualInspection.cpp