FreeCAD: Idf Namespace Reference
Idf Namespace Reference
Functions
def insert (filename, docname)
def mid_point (prev_vertex, vertex, angle)
def open (filename)
End config section do not touch code below #.
def Per_point (prev_vertex, vertex)
def place_steps (doc, placement, board_thickness)
def Process_board_outline (doc, board_outline, drills, board_thickness)
def Process_comp_outline (doc, comp_outline, comp_height)
def process_emn (doc, filename)
def process_emp (doc, filename, placement, board_thickness)
def split_records (line_record)
def toQuaternion (heading, attitude, bank)
Variables
int EmpDisplayMode = 2
int IDF_diag = 0
string IDF_diag_path = "/tmp"
int IDF_sort = 0
float ignore_hole_size = 0.5
string model_tab_filename = FreeCAD.getHomePath()+ "Mod/Idf/Idflibs/footprints_models.csv"
Script version dated 19-Jan-2012 #.
pythonopen = open
string step_path = FreeCAD.getHomePath()+ "Mod/Idf/Idflibs/"
path to directory containing step models
Function Documentation
insert()
def Idf.insert (filename, docname)
called when freecad imports an Emn file
References process_emn().
mid_point()
def Idf.mid_point (prev_vertex, vertex, angle)
mid_point(prev_vertex,vertex,angle)-> mid_vertex
   returns mid point on arc of angle between prev_vertex and vertex
Referenced by Process_board_outline(), and Process_comp_outline().
open()
def Idf.open (filename)
End config section do not touch code below #.
called when freecad opens an Emn file
References process_emn().
Per_point()
def Idf.Per_point (prev_vertex, vertex)
Per_point(center,vertex)->per point
   returns opposite perimeter point of circle
Referenced by Process_board_outline(), and Process_comp_outline().
place_steps()
def Idf.place_steps (doc, placement, board_thickness)
 place_steps(doc,placement,board_thickness)->place step models on board
    list of models and path to step files is set at start of this script
             model_tab_filename= "" &   step_path=""
References pythonopen, split_records(), and toQuaternion().
Referenced by process_emn().
Process_board_outline()
def Idf.Process_board_outline (doc, board_outline, drills, board_thickness)
Process_board_outline(doc,board_outline,drills,board_thickness)-> number proccesed loops
    adds emn geometry from emn file
References mid_point(), and Per_point().
Referenced by process_emn().
Process_comp_outline()
def Idf.Process_comp_outline (doc, comp_outline, comp_height)
Process_comp_outline(doc,comp_outline,comp_height)->part shape
   Create solid component shape base on its outline
References mid_point(), and Per_point().
Referenced by process_emp().
process_emn()
def Idf.process_emn (doc, filename)
process_emn(document, filename)-> adds emn geometry from emn file
References place_steps(), Process_board_outline(), process_emp(), pythonopen, and split_records().
Referenced by insert(), and open().
process_emp()
def Idf.process_emp (doc, filename, placement, board_thickness)
process_emp(doc,filename,placement,board_thickness) -> place components from emn file to board
References Process_comp_outline(), pythonopen, split_records(), and toQuaternion().
Referenced by process_emn().
split_records()
def Idf.split_records (line_record)
split_records(line_record)-> list of strings(records)
   standard separator list separator is space, records containing encapsulated by "
Referenced by place_steps(), process_emn(), and process_emp().
toQuaternion()
def Idf.toQuaternion (heading, attitude, bank)
toQuaternion(heading, attitude,bank)->FreeCAD.Base.Rotation(Quternion)
Referenced by place_steps(), and process_emp().
Variable Documentation
EmpDisplayMode
int Idf.EmpDisplayMode = 2
IDF_diag
int Idf.IDF_diag = 0
IDF_diag_path
string Idf.IDF_diag_path = "/tmp"
IDF_sort
int Idf.IDF_sort = 0
ignore_hole_size
float Idf.ignore_hole_size = 0.5
model_tab_filename
string Idf.model_tab_filename = FreeCAD.getHomePath()+ "Mod/Idf/Idflibs/footprints_models.csv"
Script version dated 19-Jan-2012 #.
Configuration parameters below - use standard slashes / #
path to table file (simple comma separated values)
pythonopen
Idf.pythonopen = open
Referenced by place_steps(), process_emn(), and process_emp().
step_path
string Idf.step_path = FreeCAD.getHomePath()+ "Mod/Idf/Idflibs/"
path to directory containing step models