FreeCAD: Gui::Dialog::Ui_DlgPreferences Class Reference
Gui::Dialog::Ui_DlgPreferences Class Reference
#include <ui_DlgPreferences.h>
Public Member Functions
void retranslateUi (QDialog *Gui__Dialog__DlgPreferences)
void setupUi (QDialog *Gui__Dialog__DlgPreferences)
Public Attributes
QDialogButtonBox * buttonBox
QGridLayout * gridLayout
QHBoxLayout * hboxLayout
QListWidget * listBox
QStackedWidget * tabWidgetStack
Member Function Documentation
retranslateUi()
void Gui::Dialog::Ui_DlgPreferences::retranslateUi (QDialog * Gui__Dialog__DlgPreferences)
References draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::Dialog::Ui_DlgPreferences::setupUi (QDialog * Gui__Dialog__DlgPreferences)
References buttonBox, draftgeoutils.intersections::connect(), gridLayout, hboxLayout, listBox, retranslateUi(), and tabWidgetStack.
Member Data Documentation
buttonBox
QDialogButtonBox* Gui::Dialog::Ui_DlgPreferences::buttonBox
Referenced by PathScripts.PathGetPoint.TaskPanel::getPoint(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::modifyStandardButtons(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanel::pageDirtyChanged(), PathScripts.PathGetPoint.TaskPanel::pointFinish(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setClean(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::setDirty(), and setupUi().
gridLayout
QGridLayout* Gui::Dialog::Ui_DlgPreferences::gridLayout
Referenced by setupUi().
hboxLayout
QHBoxLayout* Gui::Dialog::Ui_DlgPreferences::hboxLayout
Referenced by setupUi().
listBox
QListWidget* Gui::Dialog::Ui_DlgPreferences::listBox
Referenced by setupUi().
tabWidgetStack
QStackedWidget* Gui::Dialog::Ui_DlgPreferences::tabWidgetStack
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_DlgPreferences.h