FreeCAD: PartGui::TaskCheckGeometryResults Class Reference
PartGui::TaskCheckGeometryResults Class Reference
#include <TaskCheckGeometry.h>
Public Member Functions
QString getShapeContentString ()
void goCheck ()
TaskCheckGeometryResults (QWidget *parent=0)
~TaskCheckGeometryResults ()
Constructor & Destructor Documentation
TaskCheckGeometryResults()
TaskCheckGeometryResults::TaskCheckGeometryResults (QWidget * parent = 0)
~TaskCheckGeometryResults()
TaskCheckGeometryResults::~TaskCheckGeometryResults ()
References Gui::SelectionSingleton::clearSelection(), and Gui::Selection().
Member Function Documentation
getShapeContentString()
QString TaskCheckGeometryResults::getShapeContentString ()
Referenced by PartGui::TaskCheckGeometryDialog::TaskCheckGeometryDialog().
goCheck()
void TaskCheckGeometryResults::goCheck ()
References PartGui::ResultEntry::children, PartGui::ResultEntry::error, App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), Gui::getMainWindow(), Gui::ViewProvider::getRoot(), Gui::SelectionSingleton::getSelection(), Part::Feature::getShape(), App::Application::GetUserParameter(), Gui::Application::getViewProvider(), PartGui::goSetupResultBoundingBox(), Gui::Application::Instance, PartGui::ResultEntry::name, PartGui::ResultEntry::parent, Gui::Selection(), PartGui::ResultModel::setResults(), PartGui::ResultEntry::shape, PartGui::ResultEntry::type, and PartGui::ResultEntry::viewProviderRoot.
Referenced by PartGui::TaskCheckGeometryDialog::TaskCheckGeometryDialog().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/Gui/TaskCheckGeometry.h
Sources/FreeCAD/src/Mod/Part/Gui/TaskCheckGeometry.cpp