FreeCAD: KDTree::squared_difference_counted< _Tp, _Dist > Struct Template Reference
KDTree::squared_difference_counted< _Tp, _Dist > Struct Template Reference
#include <function.hpp>
Public Types
typedef _Dist distance_type
Public Member Functions
long & count () const
distance_type operator() (const _Tp &__a, const _Tp &__b) const
void reset ()
squared_difference_counted ()
Member Typedef Documentation
distance_type
template<typename _Tp , typename _Dist > typedef _Dist KDTree::squared_difference_counted< _Tp, _Dist >::distance_type
Constructor & Destructor Documentation
squared_difference_counted()
template<typename _Tp , typename _Dist > KDTree::squared_difference_counted< _Tp, _Dist >::squared_difference_counted ()
Member Function Documentation
count()
template<typename _Tp , typename _Dist > long & KDTree::squared_difference_counted< _Tp, _Dist >::count () const
Referenced by importDXF.dxfcounter::incr(), importSVG.svgHandler::startElement(), Mod.Test.BaseTests.ConsoleTestCase::testAsynchronPrintFromThread(), and Mod.Test.BaseTests.ConsoleTestCase::testSynchronPrintFromThread().
operator()()
template<typename _Tp , typename _Dist > distance_type KDTree::squared_difference_counted< _Tp, _Dist >::operator() (const _Tp & __a, const _Tp & __b) const
reset()
template<typename _Tp , typename _Dist > void KDTree::squared_difference_counted< _Tp, _Dist >::reset ()
Referenced by draftguitools.gui_trackers.gridTracker::set().
The documentation for this struct was generated from the following file:
FreeCAD/src/3rdParty/libkdtree/kdtree++/function.hpp