FreeCAD: VISCOUS_2D::_ViscousBuilder2D Class Reference
VISCOUS_2D::_ViscousBuilder2D Class Reference
Builder of viscous layers.
Public Member Functions
SMESH_ProxyMesh::Ptr Compute ()
Does its job.
SMESH_ComputeErrorPtr GetError () const
Friends
class ::StdMeshers_ViscousLayers2D
Detailed Description
Builder of viscous layers.
Member Function Documentation
Compute()
SMESH_ProxyMesh::Ptr _ViscousBuilder2D::Compute ()
Does its job.
References StdMeshers_FaceSide::GetFaceWires().
Referenced by StdMeshers_ViscousLayers2D::Compute().
GetError()
SMESH_ComputeErrorPtr VISCOUS_2D::_ViscousBuilder2D::GetError () const
Referenced by StdMeshers_ViscousLayers2D::CheckHypothesis(), and StdMeshers_ViscousLayers2D::Compute().
Friends And Related Function Documentation
::StdMeshers_ViscousLayers2D
friend class ::StdMeshers_ViscousLayers2D friend
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_ViscousLayers2D.cpp