FreeCAD: Gui::SelectionObjectPy Class Reference
Gui::SelectionObjectPy Class Reference
The python export class for SelectionObject.
#include <SelectionObjectPy.h>
Public Types
typedef SelectionObject * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
SelectionObjectPy (SelectionObject *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of SelectionObjectPy.
static PyMethodDef Methods []
Methods structure of SelectionObjectPy.
static PyTypeObject Type
Type structure of SelectionObjectPy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~SelectionObjectPy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * remove (PyObject *args)
implementer for the remove() method
PyObject * isObjectTypeOf (PyObject *args)
implementer for the isObjectTypeOf() method
static PyObject * staticCallback_remove (PyObject *self, PyObject *args)
callback for the remove() method
static PyObject * staticCallback_isObjectTypeOf (PyObject *self, PyObject *args)
callback for the isObjectTypeOf() method
callbacks and implementers for the python object attributes
Py::String getObjectName (void) const
getter for the ObjectName attribute
Py::Tuple getSubElementNames (void) const
getter for the SubElementNames attribute
Py::String getFullName (void) const
getter for the FullName attribute
Py::String getTypeName (void) const
getter for the TypeName attribute
Py::String getDocumentName (void) const
getter for the DocumentName attribute
Py::Object getDocument (void) const
getter for the Document attribute
Py::Object getObject (void) const
getter for the Object attribute
Py::Tuple getSubObjects (void) const
getter for the SubObjects attribute
Py::Tuple getPickedPoints (void) const
getter for the PickedPoints attribute
Py::Boolean getHasSubObjects (void) const
getter for the HasSubObjects attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
SelectionObject * getSelectionObjectPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getObjectName (PyObject *self, void *closure)
getter callback for the ObjectName attribute
static int staticCallback_setObjectName (PyObject *self, PyObject *value, void *closure)
setter callback for the ObjectName attribute
static PyObject * staticCallback_getSubElementNames (PyObject *self, void *closure)
getter callback for the SubElementNames attribute
static int staticCallback_setSubElementNames (PyObject *self, PyObject *value, void *closure)
setter callback for the SubElementNames attribute
static PyObject * staticCallback_getFullName (PyObject *self, void *closure)
getter callback for the FullName attribute
static int staticCallback_setFullName (PyObject *self, PyObject *value, void *closure)
setter callback for the FullName attribute
static PyObject * staticCallback_getTypeName (PyObject *self, void *closure)
getter callback for the TypeName attribute
static int staticCallback_setTypeName (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeName attribute
static PyObject * staticCallback_getDocumentName (PyObject *self, void *closure)
getter callback for the DocumentName attribute
static int staticCallback_setDocumentName (PyObject *self, PyObject *value, void *closure)
setter callback for the DocumentName attribute
static PyObject * staticCallback_getDocument (PyObject *self, void *closure)
getter callback for the Document attribute
static int staticCallback_setDocument (PyObject *self, PyObject *value, void *closure)
setter callback for the Document attribute
static PyObject * staticCallback_getObject (PyObject *self, void *closure)
getter callback for the Object attribute
static int staticCallback_setObject (PyObject *self, PyObject *value, void *closure)
setter callback for the Object attribute
static PyObject * staticCallback_getSubObjects (PyObject *self, void *closure)
getter callback for the SubObjects attribute
static int staticCallback_setSubObjects (PyObject *self, PyObject *value, void *closure)
setter callback for the SubObjects attribute
static PyObject * staticCallback_getPickedPoints (PyObject *self, void *closure)
getter callback for the PickedPoints attribute
static int staticCallback_setPickedPoints (PyObject *self, PyObject *value, void *closure)
setter callback for the PickedPoints attribute
static PyObject * staticCallback_getHasSubObjects (PyObject *self, void *closure)
getter callback for the HasSubObjects attribute
static int staticCallback_setHasSubObjects (PyObject *self, PyObject *value, void *closure)
setter callback for the HasSubObjects attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for SelectionObject.
Member Typedef Documentation
PointerType
typedef SelectionObject* Gui::SelectionObjectPy::PointerType
Constructor & Destructor Documentation
~SelectionObjectPy()
SelectionObjectPy::~SelectionObjectPy () protected
SelectionObjectPy()
SelectionObjectPy::SelectionObjectPy (SelectionObject * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
getCustomAttributes()
PyObject * SelectionObjectPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getDocument()
Py::Object SelectionObjectPy::getDocument (void) const
getter for the Document attribute
References Gui::SelectionObject::getObject(), and getSelectionObjectPtr().
Referenced by staticCallback_getDocument().
getDocumentName()
Py::String SelectionObjectPy::getDocumentName (void) const
getter for the DocumentName attribute
References getSelectionObjectPtr().
Referenced by staticCallback_getDocumentName().
getFullName()
Py::String SelectionObjectPy::getFullName (void) const
getter for the FullName attribute
References getSelectionObjectPtr().
Referenced by staticCallback_getFullName().
getHasSubObjects()
Py::Boolean SelectionObjectPy::getHasSubObjects (void) const
getter for the HasSubObjects attribute
References getSelectionObjectPtr().
Referenced by staticCallback_getHasSubObjects().
getObject()
Py::Object SelectionObjectPy::getObject (void) const
getter for the Object attribute
References Gui::SelectionObject::getObject(), and getSelectionObjectPtr().
Referenced by staticCallback_getObject().
getObjectName()
Py::String SelectionObjectPy::getObjectName (void) const
getter for the ObjectName attribute
References getSelectionObjectPtr().
Referenced by staticCallback_getObjectName().
getPickedPoints()
Py::Tuple SelectionObjectPy::getPickedPoints (void) const
getter for the PickedPoints attribute
References Gui::SelectionObject::getPickedPoints(), and getSelectionObjectPtr().
Referenced by staticCallback_getPickedPoints().
getSelectionObjectPtr()
SelectionObject * SelectionObjectPy::getSelectionObjectPtr (void) const
getter for the object handled by this class
Referenced by getDocument(), getDocumentName(), getFullName(), getHasSubObjects(), getObject(), getObjectName(), getPickedPoints(), getSubElementNames(), getSubObjects(), getTypeName(), isObjectTypeOf(), and remove().
getSubElementNames()
Py::Tuple SelectionObjectPy::getSubElementNames (void) const
getter for the SubElementNames attribute
References getSelectionObjectPtr(), and Gui::SelectionObject::getSubNames().
Referenced by staticCallback_getSubElementNames().
getSubObjects()
Py::Tuple SelectionObjectPy::getSubObjects (void) const
getter for the SubObjects attribute
References Gui::SelectionObject::getObject(), and getSelectionObjectPtr().
Referenced by staticCallback_getSubObjects().
GetType()
virtual PyTypeObject* Gui::SelectionObjectPy::GetType (void) virtual
Reimplemented from Base::BaseClassPy.
getTypeName()
Py::String SelectionObjectPy::getTypeName (void) const
getter for the TypeName attribute
References getSelectionObjectPtr().
Referenced by staticCallback_getTypeName().
isObjectTypeOf()
PyObject * SelectionObjectPy::isObjectTypeOf (PyObject * args)
implementer for the isObjectTypeOf() method
References Base::Type::fromName(), getSelectionObjectPtr(), and Gui::SelectionObject::isObjectTypeOf().
Referenced by staticCallback_isObjectTypeOf().
PyInit()
int SelectionObjectPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::BaseClassPy.
PyMake()
PyObject * SelectionObjectPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
remove()
PyObject * SelectionObjectPy::remove (PyObject * args)
implementer for the remove() method
References getSelectionObjectPtr(), Gui::SelectionSingleton::rmvSelection(), and Gui::Selection().
Referenced by staticCallback_remove().
representation()
std::string SelectionObjectPy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int SelectionObjectPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_getDocument()
PyObject * SelectionObjectPy::staticCallback_getDocument (PyObject * self, void * closure) static
getter callback for the Document attribute
References Base::BaseExceptionFreeCADError, getDocument(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getDocumentName()
PyObject * SelectionObjectPy::staticCallback_getDocumentName (PyObject * self, void * closure) static
getter callback for the DocumentName attribute
References Base::BaseExceptionFreeCADError, getDocumentName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFullName()
PyObject * SelectionObjectPy::staticCallback_getFullName (PyObject * self, void * closure) static
getter callback for the FullName attribute
References Base::BaseExceptionFreeCADError, getFullName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getHasSubObjects()
PyObject * SelectionObjectPy::staticCallback_getHasSubObjects (PyObject * self, void * closure) static
getter callback for the HasSubObjects attribute
References Base::BaseExceptionFreeCADError, getHasSubObjects(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getObject()
PyObject * SelectionObjectPy::staticCallback_getObject (PyObject * self, void * closure) static
getter callback for the Object attribute
References Base::BaseExceptionFreeCADError, getObject(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getObjectName()
PyObject * SelectionObjectPy::staticCallback_getObjectName (PyObject * self, void * closure) static
getter callback for the ObjectName attribute
References Base::BaseExceptionFreeCADError, getObjectName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPickedPoints()
PyObject * SelectionObjectPy::staticCallback_getPickedPoints (PyObject * self, void * closure) static
getter callback for the PickedPoints attribute
References Base::BaseExceptionFreeCADError, getPickedPoints(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSubElementNames()
PyObject * SelectionObjectPy::staticCallback_getSubElementNames (PyObject * self, void * closure) static
getter callback for the SubElementNames attribute
References Base::BaseExceptionFreeCADError, getSubElementNames(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSubObjects()
PyObject * SelectionObjectPy::staticCallback_getSubObjects (PyObject * self, void * closure) static
getter callback for the SubObjects attribute
References Base::BaseExceptionFreeCADError, getSubObjects(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTypeName()
PyObject * SelectionObjectPy::staticCallback_getTypeName (PyObject * self, void * closure) static
getter callback for the TypeName attribute
References Base::BaseExceptionFreeCADError, getTypeName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isObjectTypeOf()
PyObject * SelectionObjectPy::staticCallback_isObjectTypeOf (PyObject * self, PyObject * args) static
callback for the isObjectTypeOf() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), isObjectTypeOf(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_remove()
PyObject * SelectionObjectPy::staticCallback_remove (PyObject * self, PyObject * args) static
callback for the remove() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), remove(), and Base::PyObjectBase::startNotify().
staticCallback_setDocument()
int SelectionObjectPy::staticCallback_setDocument (PyObject * self, PyObject * value, void * closure) static
setter callback for the Document attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setDocumentName()
int SelectionObjectPy::staticCallback_setDocumentName (PyObject * self, PyObject * value, void * closure) static
setter callback for the DocumentName attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setFullName()
int SelectionObjectPy::staticCallback_setFullName (PyObject * self, PyObject * value, void * closure) static
setter callback for the FullName attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setHasSubObjects()
int SelectionObjectPy::staticCallback_setHasSubObjects (PyObject * self, PyObject * value, void * closure) static
setter callback for the HasSubObjects attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setObject()
int SelectionObjectPy::staticCallback_setObject (PyObject * self, PyObject * value, void * closure) static
setter callback for the Object attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setObjectName()
int SelectionObjectPy::staticCallback_setObjectName (PyObject * self, PyObject * value, void * closure) static
setter callback for the ObjectName attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPickedPoints()
int SelectionObjectPy::staticCallback_setPickedPoints (PyObject * self, PyObject * value, void * closure) static
setter callback for the PickedPoints attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setSubElementNames()
int SelectionObjectPy::staticCallback_setSubElementNames (PyObject * self, PyObject * value, void * closure) static
setter callback for the SubElementNames attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setSubObjects()
int SelectionObjectPy::staticCallback_setSubObjects (PyObject * self, PyObject * value, void * closure) static
setter callback for the SubObjects attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setTypeName()
int SelectionObjectPy::staticCallback_setTypeName (PyObject * self, PyObject * value, void * closure) static
setter callback for the TypeName attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
Member Data Documentation
GetterSetter
PyGetSetDef SelectionObjectPy::GetterSetter static
Attribute structure of SelectionObjectPy.
Methods
PyMethodDef SelectionObjectPy::Methods static
Initial value:
= {
    {"remove",
        reinterpret_cast<PyCFunction>( staticCallback_remove ),
        METH_VARARGS,
        "Remove this selection item from the selection. This object becomes invalid."
    },
    {"isObjectTypeOf",
        reinterpret_cast<PyCFunction>( staticCallback_isObjectTypeOf ),
        METH_VARARGS,
        "Test for a certain father class."
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of SelectionObjectPy.
Type
PyTypeObject SelectionObjectPy::Type static
Type structure of SelectionObjectPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Gui/SelectionObjectPy.h
Sources/FreeCAD/src/Gui/SelectionObjectPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Gui/SelectionObjectPy.cpp