FreeCAD: SMESH_MeshEditor::ExtrusParam Class Reference
SMESH_MeshEditor::ExtrusParam Class Reference
#include <SMESH_MeshEditor.hxx>
Public Member Functions
SMESH_SequenceOfNode & ChangeNodes ()
ExtrusParam (const double theStep, const int theNbSteps, const int theFlags, const int theDim)
ExtrusParam (const gp_Dir &theDir, Handle(TColStd_HSequenceOfReal) theSteps, const int theFlags=0, const double theTolerance=1e-6)
ExtrusParam (const gp_Vec &theStep, const int theNbSteps, const int theFlags=0, const double theTolerance=1e-6)
int & Flags ()
int MakeNodes (SMESHDS_Mesh *mesh, const SMDS_MeshNode *srcNode, std::list< const SMDS_MeshNode * > &newNodes, const bool makeMediumNodes)
int NbSteps () const
void SetElementsToUse (const TIDSortedElemSet &elems)
bool ToMakeBoundary () const
bool ToMakeGroups () const
bool ToUseInpElemsOnly () const
Detailed Description
Generator of nodes for extrusion functionality
Constructor & Destructor Documentation
ExtrusParam() [1/3]
SMESH_MeshEditor::ExtrusParam::ExtrusParam (const gp_Vec & theStep, const int theNbSteps, const int theFlags = 0, const double theTolerance = 1e-6)
References SMESH_MeshEditor::EXTRUSION_FLAG_SEW.
ExtrusParam() [2/3]
SMESH_MeshEditor::ExtrusParam::ExtrusParam (const gp_Dir & theDir, Handle(TColStd_HSequenceOfReal) theSteps, const int theFlags = 0, const double theTolerance = 1e-6)
References SMESH_MeshEditor::EXTRUSION_FLAG_SEW.
ExtrusParam() [3/3]
SMESH_MeshEditor::ExtrusParam::ExtrusParam (const double theStep, const int theNbSteps, const int theFlags, const int theDim)
Member Function Documentation
ChangeNodes()
SMESH_SequenceOfNode& SMESH_MeshEditor::ExtrusParam::ChangeNodes ()
Flags()
int& SMESH_MeshEditor::ExtrusParam::Flags ()
MakeNodes()
int SMESH_MeshEditor::ExtrusParam::MakeNodes (SMESHDS_Mesh * mesh, const SMDS_MeshNode * srcNode, std::list< const SMDS_MeshNode * > & newNodes, const bool makeMediumNodes)
Referenced by SMESH_MeshEditor::ExtrusionSweep().
NbSteps()
int SMESH_MeshEditor::ExtrusParam::NbSteps () const
Referenced by SMESH_MeshEditor::ExtrusionSweep().
SetElementsToUse()
void SMESH_MeshEditor::ExtrusParam::SetElementsToUse (const TIDSortedElemSet & elems)
Referenced by SMESH_MeshEditor::ExtrusionSweep().
ToMakeBoundary()
bool SMESH_MeshEditor::ExtrusParam::ToMakeBoundary () const
Referenced by SMESH_MeshEditor::ExtrusionSweep().
ToMakeGroups()
bool SMESH_MeshEditor::ExtrusParam::ToMakeGroups () const
Referenced by SMESH_MeshEditor::ExtrusionSweep().
ToUseInpElemsOnly()
bool SMESH_MeshEditor::ExtrusParam::ToUseInpElemsOnly () const
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_MeshEditor.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/SMESH_MeshEditor.cpp