FreeCAD: Gui::NS::RotateState Class Reference
Gui::NS::RotateState Class Reference
Public Types
typedef sc::custom_reaction< NS::Event > reactions
Public Member Functions
sc::result react (const NS::Event &ev)
RotateState (my_context ctx)
virtual ~RotateState ()
Member Typedef Documentation
reactions
typedef sc::custom_reaction<NS::Event> Gui::NS::RotateState::reactions
Constructor & Destructor Documentation
RotateState()
Gui::NS::RotateState::RotateState (my_context ctx)
References Base::Console(), Gui::NavigationStyle::DRAGGING, and Base::ConsoleSingleton::Log().
~RotateState()
virtual Gui::NS::RotateState::~RotateState () virtual
Member Function Documentation
react()
sc::result Gui::NS::RotateState::react (const NS::Event & ev)
References Gui::NS::Event::flags, Gui::NS::Event::inventor_event, Gui::NS::Event::isLocation2Event(), Gui::NS::Event::isMouseButtonEvent(), and Gui::NS::Event::mbstate().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/GestureNavigationStyle.cpp