FreeCAD: Points::PcdReader Class Reference
Points::PcdReader Class Reference
#include <PointsAlgos.h>
Public Member Functions
PcdReader ()
void read (const std::string &filename)
~PcdReader ()
Public Member Functions inherited from Points::Reader
void clear ()
const std::vector< App::Color > & getColors () const
int getHeight () const
const std::vector< float > & getIntensities () const
const std::vector< Base::Vector3f > & getNormals () const
const PointKernel & getPoints () const
int getWidth () const
bool hasColors () const
bool hasIntensities () const
bool hasNormals () const
bool hasProperties () const
bool isStructured () const
Reader ()
virtual ~Reader ()
Additional Inherited Members
Protected Attributes inherited from Points::Reader
std::vector< App::Color > colors
int height
std::vector< float > intensity
std::vector< Base::Vector3f > normals
PointKernel points
int width
Constructor & Destructor Documentation
PcdReader()
PcdReader::PcdReader ()
~PcdReader()
PcdReader::~PcdReader ()
Member Function Documentation
read()
void PcdReader::read (const std::string & filename) virtual
Implements Points::Reader.
References Points::Reader::clear(), Points::Reader::colors, DraftVecUtils::find(), Points::Reader::intensity, Points::lzfDecompress(), and Points::Reader::normals.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Points/App/PointsAlgos.h
Sources/FreeCAD/src/Mod/Points/App/PointsAlgos.cpp