FreeCAD: Part::TangentialArc Class Reference
Part::TangentialArc Class Reference
Public Member Functions
bool isRadiusEqual (const gp_Pnt &p, double tolerance) const
Geometry * makeArc () const
double radius () const
TangentialArc (const gp_Pnt &p0, const gp_Vec &v0, const gp_Pnt &p1)
Public Attributes
gp_Dir m_a
gp_Pnt m_c
bool m_is_a_line
gp_Pnt m_p0
gp_Pnt m_p1
gp_Vec m_v0
Constructor & Destructor Documentation
TangentialArc()
Part::TangentialArc::TangentialArc (const gp_Pnt & p0, const gp_Vec & v0, const gp_Pnt & p1)
References m_a, m_c, m_is_a_line, m_p0, m_p1, m_v0, and Part::tangentialArc().
Member Function Documentation
isRadiusEqual()
bool Part::TangentialArc::isRadiusEqual (const gp_Pnt & p, double tolerance) const
References m_c, m_is_a_line, radius(), and draftutils.utils::tolerance().
makeArc()
Geometry* Part::TangentialArc::makeArc () const
References m_a, m_c, m_is_a_line, m_p0, m_p1, radius(), Part::GeomArcOfCircle::setHandle(), and Part::GeomLineSegment::setPoints().
radius()
double Part::TangentialArc::radius () const
References m_c, m_p0, and m_p1.
Referenced by PathScripts.PathPocketBase.ObjectPocket::areaOpAreaParams(), PathScripts.PathProfile.ObjectProfile::areaOpAreaParams(), PathScripts.PathPocketBase.ObjectPocket::areaOpPathParams(), PathScripts.PathAreaOp.ObjectOp::areaOpSetDefaultValues(), DraftGui.DraftToolBar::changeRadiusValue(), PathScripts.PathHelix.ObjectHelix::circularHoleExecute(), PathScripts.PathDressupHoldingTags.Tag::createSolidsAt(), PathScripts.PathSurface.ObjectSurface::deleteOpVariables(), PathScripts.PathWaterline.ObjectWaterline::deleteOpVariables(), PathScripts.PathOp.ObjectOp::execute(), PathScripts.PathDressupAxisMap.TaskPanel::getFields(), PathScripts.PathHelix.ObjectHelix::helix_cut(), ifc4.ifcsweptdisksolid::innerradiussize(), isRadiusEqual(), makeArc(), draftguitools.gui_snapper.Snapper::off(), PathScripts.PathSurfaceSupport.ProcessSelectedFaces::preProcessModel(), draftguitools.gui_snapper.Snapper::showradius(), draftguitools.gui_snapper.Snapper::snapToCrossExtensions(), draftguitools.gui_snapper.Snapper::snapToExtensions(), draftguitools.gui_snapper.Snapper::snapToGrid(), draftguitools.gui_snapper.Snapper::snapToHold(), draftguitools.gui_snapper.Snapper::snapToObject(), draftguitools.gui_snapper.Snapper::snapToPolar(), DraftGui.DraftToolBar::taskUi(), PathScripts.PathDressupAxisMap.TaskPanel::updateUI(), DraftGui.DraftToolBar::validatePoint(), automotive_design.right_circular_cone::wr1(), automotive_design.conical_surface::wr1(), config_control_design.conical_surface::wr1(), automotive_design.swept_disk_solid::wr2(), and ifc2x3.ifcsweptdisksolid::wr2().
Member Data Documentation
m_a
gp_Dir Part::TangentialArc::m_a
Referenced by makeArc(), and TangentialArc().
m_c
gp_Pnt Part::TangentialArc::m_c
Referenced by isRadiusEqual(), makeArc(), radius(), and TangentialArc().
m_is_a_line
bool Part::TangentialArc::m_is_a_line
Referenced by isRadiusEqual(), makeArc(), and TangentialArc().
m_p0
gp_Pnt Part::TangentialArc::m_p0
Referenced by makeArc(), radius(), and TangentialArc().
m_p1
gp_Pnt Part::TangentialArc::m_p1
Referenced by makeArc(), radius(), and TangentialArc().
m_v0
gp_Vec Part::TangentialArc::m_v0
Referenced by TangentialArc().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Part/App/BSplineCurveBiArcs.cpp