FreeCAD: App::PropertyLinkBase Class Reference
App::PropertyLinkBase Class Reference abstract
Parent class of all link type properties.
#include <PropertyLinks.h>
Public Types
enum LinkFlags {
LinkAllowExternal , LinkDetached , LinkRestoring , LinkAllowPartial ,
LinkRestoreLabel
}
typedef std::pair< std::string, std::string > ShadowSub
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , PropStaticBegin = 21 ,
PropDynamic = 21 , PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 ,
PropTransient = 25 , PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 ,
User1 = 28 , User2 = 29 , User3 = 30 , User4 = 31
}
Public Member Functions
virtual bool adjustLink (const std::set< App::DocumentObject * > &inList)=0
Called to adjust the link to avoid potential cyclic dependency.
virtual void breakLink (App::DocumentObject *obj, bool clear)=0
Called to reset this link property.
void checkLabelReferences (const std::vector< std::string > &subs, bool reset=true)
Check subnames for label registration.
virtual int checkRestore (std::string *msg=0) const
Test if the link is restored unchanged.
virtual Property * CopyOnImportExternal (const std::map< std::string, std::string > &nameMap) const
Return a copy of the property if any changes caused by importing external linked object.
virtual Property * CopyOnLabelChange (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const
Update object label reference in this property.
virtual Property * CopyOnLinkReplace (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const =0
Return a copy of the property if the link replacement affects this property.
void getLinkedElements (std::map< App::DocumentObject *, std::vector< std::string > > &elements, bool newStyle=true, bool all=true) const
Helper function to return a map of linked object and its subname references.
template<class T >
void getLinkedObjects (T &inserter, bool all=false) const
Helper function to return linked objects using an std::inserter.
virtual void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=0, bool newStyle=true) const =0
Obtain the linked objects.
std::map< App::DocumentObject *, std::vector< std::string > > linkedElements (bool newStyle=true, bool all=true) const
Helper function to return a map of linked object and its subname references.
std::vector< App::DocumentObject * > linkedObjects (bool all=false) const
Helper function to return all linked objects of this property.
PropertyLinkBase ()
virtual bool referenceChanged () const
Test if the element reference has changed after restore.
void registerLabelReferences (std::vector< std::string > &&labels, bool reset=true)
Register label reference for future object relabel update.
void setAllowExternal (bool allow)
Enable/disable temporary holding external object without throwing exception.
virtual void setAllowPartial (bool enable)
bool testFlag (int flag) const
void unregisterElementReference ()
Clear internal element reference registration.
void unregisterLabelReferences ()
Clear internal label references registration.
virtual void updateElementReference (App::DocumentObject *feature, bool reverse=false, bool notify=false)
Link type property interface APIs These APIs are moved here so that any type of property can have the property link behavior, e.g.
virtual ~PropertyLinkBase ()
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual Property * Copy (void) const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const char * getName (void) const
get the name of this property in the belonging container
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::ScopedLink
LinkScope getScope ()
Get the links scope Retrieve what kind of links are allowed.
void setScope (LinkScope scope)
Set the links scope Allows to define what kind of links are allowed.
Static Public Member Functions
static void breakLinks (App::DocumentObject *link, const std::vector< App::DocumentObject * > &objs, bool clear)
Helper function for breaking link properties.
static const char * exportSubName (std::string &output, const App::DocumentObject *obj, const char *subname, bool first_obj=false)
Helper function to export a subname reference.
static void getLabelReferences (std::vector< std::string > &labels, const char *subname)
Helper function to extract labels from a subname reference.
static std::string importSubName (Base::XMLReader &reader, const char *sub, bool &restoreLabel)
Helper function to import a subname reference.
static void restoreLabelReference (const App::DocumentObject *obj, std::string &sub, ShadowSub *shadow=0)
Helper function to restore label references during import.
static App::DocumentObject * tryImport (const App::Document *doc, const App::DocumentObject *obj, const std::map< std::string, std::string > &nameMap)
Helper function for link import operation.
static std::string tryImportSubName (const App::DocumentObject *obj, const char *sub, const App::Document *doc, const std::map< std::string, std::string > &nameMap)
Helper function for link import operation.
static std::pair< App::DocumentObject *, std::string > tryReplaceLink (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const char *sub=0)
Helper functions.
static std::pair< App::DocumentObject *, std::vector< std::string > > tryReplaceLinkSubs (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const std::vector< std::string > &subs)
Helper function to check and replace a link with multiple subname references.
static void updateElementReferences (DocumentObject *feature, bool reverse=false)
Update all element references in all link properties of feature.
static std::string updateLabelReference (const App::DocumentObject *linked, const char *subname, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
Helper function to update subname reference on label change.
static std::vector< std::pair< Property *, std::unique_ptr< Property > > > updateLabelReferences (App::DocumentObject *obj, const char *newLabel)
Helper function to collect changed property when an object re-label.
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Protected Member Functions
virtual void hasSetValue () override
Gets called by all setValue() methods after the value has changed.
void setFlag (int flag, bool value=true)
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Friends
class DocInfo
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Detailed Description
Parent class of all link type properties.
Member Typedef Documentation
ShadowSub
typedef std::pair<std::string,std::string> App::PropertyLinkBase::ShadowSub
Member Enumeration Documentation
LinkFlags
enum App::PropertyLinkBase::LinkFlags
Enumerator
LinkAllowExternal
LinkDetached
LinkRestoring
LinkAllowPartial
LinkRestoreLabel
Constructor & Destructor Documentation
PropertyLinkBase()
PropertyLinkBase::PropertyLinkBase ()
~PropertyLinkBase()
PropertyLinkBase::~PropertyLinkBase () virtual
References unregisterElementReference(), and unregisterLabelReferences().
Member Function Documentation
adjustLink()
virtual bool App::PropertyLinkBase::adjustLink (const std::set< App::DocumentObject * > & inList) pure virtual
Called to adjust the link to avoid potential cyclic dependency.
Parameters
inList recursive in-list of the would-be parent
Returns
Return whether the link has been adjusted
This function tries to correct the link to avoid any (sub)object inside in-list. If the adjustment is impossible, exception will be raised
Implemented in Spreadsheet::PropertySheet, App::PropertyXLinkSubList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyLinkSub, App::PropertyLinkList, App::PropertyLink, and App::PropertyExpressionEngine.
breakLink()
virtual void App::PropertyLinkBase::breakLink (App::DocumentObject * obj, bool clear) pure virtual
Called to reset this link property.
Parameters
obj reset link property if it is linked to this object
clear if true, then also reset property if the owner of this property is obj
See also
breakLinks()
Implemented in Spreadsheet::PropertySheet, App::PropertyXLinkContainer, App::PropertyXLinkSubList, App::PropertyLinkSubList, App::PropertyLinkSub, App::PropertyLinkList, and App::PropertyLink.
Referenced by breakLinks().
breakLinks()
void PropertyLinkBase::breakLinks (App::DocumentObject * link, const std::vector< App::DocumentObject * > & objs, bool clear) static
Helper function for breaking link properties.
Parameters
link reset link property if it is linked to this object
objs the objects to check for the link properties
clear if true, then also reset property if the owner of the link property is link
App::Document::breakDependency() calls this function to break the link property
References breakLink(), and App::DocInfo::breakLinks().
Referenced by App::Document::breakDependency().
checkLabelReferences()
void PropertyLinkBase::checkLabelReferences (const std::vector< std::string > & subs, bool reset = true)
Check subnames for label registration.
Parameters
subs subname references
reset if true, then calls unregisterLabelReference() before registering
Check the give subname references and extract any label reference inside (by calling getLabelReferences()), and register them.
References getLabelReferences(), draftfunctions.move::move(), registerLabelReferences(), and unregisterLabelReferences().
Referenced by App::PropertyXLink::setSubValues(), App::PropertyLinkSub::setValue(), App::PropertyLinkSubList::setValue(), and App::PropertyLinkSubList::setValues().
checkRestore()
virtual int App::PropertyLinkBase::checkRestore (std::string * msg = 0) const virtual
Test if the link is restored unchanged.
Parameters
msg optional error message
Returns
For external linked object, return 2 in case the link is missing, and 1 if the time stamp has changed.
Reimplemented in App::PropertyXLinkContainer, App::PropertyXLinkSubList, and App::PropertyXLink.
CopyOnImportExternal()
virtual Property* App::PropertyLinkBase::CopyOnImportExternal (const std::map< std::string, std::string > & nameMap) const virtual
Return a copy of the property if any changes caused by importing external linked object.
Parameters
nameMap a map from the original external object name to the imported new object name
Returns
Returns a copy of the property with the updated link reference if affected. The copy will later be assgiend to this property by calling its Paste().
Reimplemented in Spreadsheet::PropertySheet, App::PropertyXLinkSubList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyLinkSub, and App::PropertyExpressionEngine.
CopyOnLabelChange()
virtual Property* App::PropertyLinkBase::CopyOnLabelChange (App::DocumentObject * obj, const std::string & ref, const char * newLabel) const virtual
Update object label reference in this property.
Parameters
obj the object owner of the changing label
ref subname reference to old label
newLabel the future new label
Returns
Returns a copy of the property if its link reference is affected. The copy will later be assgiend to this property by calling its Paste().
Reimplemented in Spreadsheet::PropertySheet, App::PropertyXLinkSubList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyLinkSub, and App::PropertyExpressionEngine.
CopyOnLinkReplace()
virtual Property* App::PropertyLinkBase::CopyOnLinkReplace (const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj) const pure virtual
Return a copy of the property if the link replacement affects this property.
Parameters
owner the parent object whose link property is to be replace. Note that The parent may not be the container of this property. Link sub property can use this opportunity to adjust its relative links.
oldObj object to be replaced
newObj object to replace with
Returns
Return a copy of the property that is adjusted for the link replacement operation.
Implemented in Spreadsheet::PropertySheet, App::PropertyXLinkSubList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyLinkSub, App::PropertyLinkList, App::PropertyLink, and App::PropertyExpressionEngine.
exportSubName()
const char * PropertyLinkBase::exportSubName (std::string & output, const App::DocumentObject * obj, const char * subname, bool first_obj = false) static
Helper function to export a subname reference.
Parameters
output output subname if the subname is modified
obj linked object
sub input subname reference
first_obj if true, then the first object referenced in subname is obtained by searching the owner document of obj, otherwise the subname search among obj's sub-objects.
Returns
Return output.c_str() if the subname is modified for exporting otherwise, return the input subname
See also
importSubName(), restoreLabelReference()
The function go through the input subname reference and changes any sub object references inside for exporting. If the sub object is referenced by its internal object name, then the reference is changed from 'objName' to 'objName@docName'. If referenced by label, then it will be changed to 'objName@docName@' instead. importSubName() and restoreLabelReference() can be used together to restore the reference during import.
References App::GetApplication(), and App::Application::getDocument().
Referenced by App::PropertyLinkSub::Save(), App::PropertyLinkSubList::Save(), App::PropertyXLink::Save(), and App::ObjectIdentifier::toPersistentString().
getLabelReferences()
void PropertyLinkBase::getLabelReferences (std::vector< std::string > & labels, const char * subname) static
Helper function to extract labels from a subname reference.
Parameters
labels output vector of extracted labels
subname subname reference
See also
registerLabelReferences()
This function is used to extract label from subname reference for registering of label changes.
Referenced by checkLabelReferences(), and App::ObjectIdentifier::getDep().
getLinkedElements()
void App::PropertyLinkBase::getLinkedElements (std::map< App::DocumentObject *, std::vector< std::string > > & elements, bool newStyle = true, bool all = true) const
Helper function to return a map of linked object and its subname references.
getLinkedObjects()
template<class T > void App::PropertyLinkBase::getLinkedObjects (T & inserter, bool all = false) const
Helper function to return linked objects using an std::inserter.
getLinks()
virtual void App::PropertyLinkBase::getLinks (std::vector< App::DocumentObject * > & objs, bool all = false, std::vector< std::string > * subs = 0, bool newStyle = true) const pure virtual
Obtain the linked objects.
Parameters
objs hold the returned linked objects on output
all if true, then return all the linked object regardless of this LinkScope. If false, then return only if the LinkScope is not hidden.
sub if given, then return subname references.
newStyle whether to return new or old style subname reference
Implemented in App::PropertyXLinkContainer, App::PropertyXLinkSubList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyLinkSub, App::PropertyLinkList, and App::PropertyLink.
Referenced by Gui::Dialog::DlgPropertyLink::getLinksFromProperty().
hasSetValue()
void PropertyLinkBase::hasSetValue (void) override protected virtual
Gets called by all setValue() methods after the value has changed.
Reimplemented from App::Property.
Reimplemented in Spreadsheet::PropertySheet, App::PropertyXLink, and App::PropertyExpressionEngine.
References App::Property::getContainer(), and App::Property::hasSetValue().
Referenced by App::PropertyXLinkContainer::breakLink(), App::PropertyXLinkSubList::hasSetChildValue(), App::PropertyExpressionEngine::hasSetValue(), App::PropertyXLink::hasSetValue(), App::PropertyXLinkSubList::Paste(), App::PropertyLink::setValue(), App::PropertyLinkSub::setValue(), App::PropertyLinkSubList::setValue(), App::PropertyLinkSubList::setValues(), App::PropertyLinkSub::updateElementReference(), and App::PropertyLinkSubList::updateElementReference().
importSubName()
std::string PropertyLinkBase::importSubName (Base::XMLReader & reader, const char * sub, bool & restoreLabel) static
Helper function to import a subname reference.
Parameters
reader the import reader
sub input subname reference
restoreLabel output indicate whether post process is required after restore.
See also
exportSubName(), restoreLabelReference()
Returns
return either an updated subname reference or the input reference if no change. If restoreLabel is set to true on output, it means there are some label reference changes that must be corrected after restore, by calling restoreLabelReference() in property's afterRestore().
References Base::XMLReader::doNameMapping(), and Base::XMLReader::getName().
Referenced by App::ObjectIdentifier::String::checkImport(), App::PropertyLinkSub::Restore(), App::PropertyLinkSubList::Restore(), and App::PropertyXLink::Restore().
linkedElements()
std::map<App::DocumentObject*, std::vector<std::string> > App::PropertyLinkBase::linkedElements (bool newStyle = true, bool all = true) const
Helper function to return a map of linked object and its subname references.
linkedObjects()
std::vector<App::DocumentObject *> App::PropertyLinkBase::linkedObjects (bool all = false) const
Helper function to return all linked objects of this property.
referenceChanged()
virtual bool App::PropertyLinkBase::referenceChanged () const virtual
Test if the element reference has changed after restore.
Reimplemented in Spreadsheet::PropertySheet, App::PropertyXLinkSubList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyLinkSub, and App::PropertyExpressionEngine.
registerLabelReferences()
void PropertyLinkBase::registerLabelReferences (std::vector< std::string > && labels, bool reset = true)
Register label reference for future object relabel update.
Parameters
labels labels to be registered
reset if true, then calls unregisterLabelReference() before registering
References draftfunctions.move::move(), and unregisterLabelReferences().
Referenced by checkLabelReferences(), and Spreadsheet::PropertySheet::hasSetValue().
restoreLabelReference()
void PropertyLinkBase::restoreLabelReference (const App::DocumentObject * obj, std::string & sub, ShadowSub * shadow = 0) static
Helper function to restore label references during import.
Parameters
obj linked object
sub subname reference
shadow optional shadow subname reference
See also
exportSubName(), importSubName()
When exporting and importing (i.e. copy and paste) objects into the same document, the new object must be renamed, both the internal name and the label. Therefore, the link reference of the new objects must be corrected accordingly. The basic idea is that when exporting object, all object name references are changed to 'objName@docName', and label references are changed to 'objName@docName@'. During import, MergeDocument will maintain a map from objName@docName to object's new name. Object name reference can be restored on spot by consulting the map, while label reference will be restored later in property's afterRestore() function, which calls this function to do the string parsing.
References App::PropertyString::getStrValue(), App::DocumentObject::getSubObject(), and App::DocumentObject::Label.
Referenced by App::PropertyLinkSub::afterRestore(), App::PropertyLinkSubList::afterRestore(), App::PropertyXLink::afterRestore(), and App::ObjectIdentifier::String::checkImport().
setAllowExternal()
void PropertyLinkBase::setAllowExternal (bool allow)
Enable/disable temporary holding external object without throwing exception.
Warning, non-PropertyXLink related property does not have internal tracking of external objects, therefore the link will not by auto broken when external document is closed. Only use this for temporary case, or if you handle signalDeleteDocument yourself, or use one of the PropertyXLink related property.
References LinkAllowExternal, and setFlag().
Referenced by App::PropertyXLinkSubList::setPyObject(), and App::PropertyXLinkList::setPyObject().
setAllowPartial()
virtual void App::PropertyLinkBase::setAllowPartial (bool enable) virtual
Reimplemented in App::PropertyXLinkSubList, and App::PropertyXLink.
setFlag()
void App::PropertyLinkBase::setFlag (int flag, bool value = true) protected
Referenced by App::PropertyLinkSub::afterRestore(), App::PropertyLinkSubList::afterRestore(), App::PropertyXLink::afterRestore(), App::PropertyXLink::Paste(), App::PropertyLinkSub::Restore(), App::PropertyLinkSubList::Restore(), App::PropertyXLink::Restore(), App::PropertyXLinkSubList::Restore(), App::PropertyXLink::restoreLink(), setAllowExternal(), App::PropertyXLink::setAllowPartial(), App::PropertyXLinkSubList::setAllowPartial(), and App::PropertyXLink::setValue().
testFlag()
bool App::PropertyLinkBase::testFlag (int flag) const
Referenced by App::PropertyXLinkSubList::addValue(), App::PropertyLinkSub::afterRestore(), App::PropertyLinkSubList::afterRestore(), App::PropertyXLink::afterRestore(), App::PropertyXLink::checkRestore(), App::PropertyXLinkSubList::Copy(), Spreadsheet::PropertySheet::hasSetValue(), App::PropertyXLinkSubList::Paste(), App::PropertyXLink::Save(), App::PropertyXLinkSubList::Save(), App::PropertyXLinkSubList::set1Value(), App::PropertyLink::setValue(), App::PropertyLinkSub::setValue(), App::PropertyLinkSubList::setValue(), App::PropertyLinkList::setValues(), App::PropertyLinkSubList::setValues(), App::PropertyXLinkSubList::setValues(), App::PropertyXLinkContainer::updateDeps(), and App::PropertyXLinkSubList::upgrade().
tryImport()
App::DocumentObject * PropertyLinkBase::tryImport (const App::Document * doc, const App::DocumentObject * obj, const std::map< std::string, std::string > & nameMap) static
Helper function for link import operation.
Parameters
doc owner document of the imported objects
obj the linked object
nameMap a name map from source object to its imported counter part
Returns
Return the imported object if found, or the input obj if no change.
See also
tryImportSubNames
This function searches for the name map and tries to find the imported object from the given source object.
Referenced by App::PropertyLinkSub::CopyOnImportExternal(), App::PropertyLinkSubList::CopyOnImportExternal(), and App::PropertyXLink::CopyOnImportExternal().
tryImportSubName()
std::string PropertyLinkBase::tryImportSubName (const App::DocumentObject * obj, const char * sub, const App::Document * doc, const std::map< std::string, std::string > & nameMap) static
Helper function for link import operation.
Parameters
obj the linked object
sub subname reference
doc importing document
nameMap a name map from source object to its imported counter part
Returns
Return a changed subname reference, or empty string if no change.
Link import operation will go through all link property and imports all externally linked object. After import, the link property must be changed to point to the newly imported objects, which should happen inside the API CopyOnImportExternal(). This function helps to rewrite subname reference to point to the correct sub objects that are imported.
Referenced by App::PropertyLinkSub::CopyOnImportExternal(), App::PropertyLinkSubList::CopyOnImportExternal(), App::PropertyXLink::CopyOnImportExternal(), and App::Expression::importSubNames().
tryReplaceLink()
std::pair< DocumentObject *, std::string > PropertyLinkBase::tryReplaceLink (const App::PropertyContainer * owner, App::DocumentObject * obj, const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj, const char * sub = 0) static
Helper functions.
Helper function to check and replace a link
Parameters
owner the owner of the current property
obj the current linked object
parent the parent of the changing link property, may or may not be equal to owner
oldObj the object to be replaced
newObj the object to replace with
sub optional the current subname reference
Returns
Returns a pair(obj,subname). If no replacement is found, pair.first will be NULL
Say a group has one of its child object replaced with another. Any existing link sub reference that refer to the original child object through the group will be broken. This helper function is used to check and correct any link sub reference.
References App::PropertyContainer::getFullName(), App::DocumentObject::getFullName(), App::Property::getName(), App::DocumentObject::getNameInDocument(), App::DocumentObject::getSubObject(), App::PropertyString::getValue(), App::DocumentObject::Label, and draftfunctions.move::move().
Referenced by App::PropertyLink::CopyOnLinkReplace(), App::PropertyLinkList::CopyOnLinkReplace(), App::PropertyLinkSubList::CopyOnLinkReplace(), App::ObjectIdentifier::replaceObject(), and tryReplaceLinkSubs().
tryReplaceLinkSubs()
std::pair< DocumentObject *, std::vector< std::string > > PropertyLinkBase::tryReplaceLinkSubs (const App::PropertyContainer * owner, App::DocumentObject * obj, const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj, const std::vector< std::string > & subs) static
Helper function to check and replace a link with multiple subname references.
Parameters
owner the owner of the current property
obj the current linked object
parent the parent of the changing link property, may or may not be equal to owner
oldObj the object to be replaced
newObj the object to replace with
subs the current subname references
Returns
Returns the a pair(obj,subs). If no replacement is found, pair.first will be NULL
See also
tryReplaceLink()
References draftfunctions.move::move(), and tryReplaceLink().
Referenced by App::PropertyLinkSub::CopyOnLinkReplace(), and App::PropertyXLink::CopyOnLinkReplace().
unregisterElementReference()
void PropertyLinkBase::unregisterElementReference ()
Clear internal element reference registration.
Referenced by Spreadsheet::PropertySheet::hasSetValue(), App::PropertyLinkSub::onContainerRestored(), App::PropertyLinkSubList::onContainerRestored(), Spreadsheet::PropertySheet::onContainerRestored(), Spreadsheet::PropertySheet::updateElementReference(), App::PropertyLinkSubList::updateElementReference(), and ~PropertyLinkBase().
unregisterLabelReferences()
void PropertyLinkBase::unregisterLabelReferences ()
Clear internal label references registration.
Referenced by checkLabelReferences(), registerLabelReferences(), and ~PropertyLinkBase().
updateElementReference()
virtual void App::PropertyLinkBase::updateElementReference (App::DocumentObject * feature, bool reverse = false, bool notify = false) virtual
Link type property interface APIs These APIs are moved here so that any type of property can have the property link behavior, e.g.
the PropertyExpressionEngine Called to update the element reference of this link property
See also
_updateElementReference()
Reimplemented in App::PropertyXLinkSubList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyLinkSub, Spreadsheet::PropertySheet, and App::PropertyExpressionEngine.
References femsolver.signal::notify().
updateElementReferences()
void PropertyLinkBase::updateElementReferences (DocumentObject * feature, bool reverse = false) static
Update all element references in all link properties of feature.
updateLabelReference()
std::string PropertyLinkBase::updateLabelReference (const App::DocumentObject * linked, const char * subname, App::DocumentObject * obj, const std::string & ref, const char * newLabel) static
Helper function to update subname reference on label change.
Parameters
linked linked object
subname subname reference
obj the object that owns the label
ref label reference in the format of '$<old_label>.', which is the format used in subname reference for label reference. This parameter is provided for easy search of label reference.
newLabel new label
Returns
Returns an updated subname reference, or empty string if no change.
This function helps to update subname reference on label change. It is usually called inside CopyOnLabelChange(), the API for handling label change, which is called just before label change. In other word, when called, the sub object can still be reached using the original label references, but not the new labels.
References App::DocumentObject::getNameInDocument(), and App::DocumentObject::getSubObject().
Referenced by App::PropertyLinkSub::CopyOnLabelChange(), App::PropertyLinkSubList::CopyOnLabelChange(), App::PropertyXLink::CopyOnLabelChange(), and App::ObjectIdentifier::updateLabelReference().
updateLabelReferences()
std::vector< std::pair< Property *, std::unique_ptr< Property > > > PropertyLinkBase::updateLabelReferences (App::DocumentObject * obj, const char * newLabel) static
Helper function to collect changed property when an object re-label.
Parameters
obj the object that owns the label
newLabel the new label
Returns
return a map from the affected property to a copy of it with updated subname references
References draftfunctions.move::move().
Referenced by App::PropertyString::setValue().
Friends And Related Function Documentation
DocInfo
friend class DocInfo friend
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/App/PropertyLinks.h
Sources/FreeCAD/src/App/PropertyLinks.cpp