FreeCAD: prototype Namespace Reference
prototype Namespace Reference
Classes
class Node
Functions
def insert (filename, docname)
def open (filename)
def openscadmesh (doc, scadstr, objname)
def parseargs (argstring)
def parseexpression (e)
def parsenode (str1)
def readfile (filename)
Variables
dictionary dxfcache = {}
pythonopen = open
Function Documentation
insert()
def prototype.insert (filename, docname)
References readfile().
open()
def prototype.open (filename)
References readfile().
openscadmesh()
def prototype.openscadmesh (doc, scadstr, objname)
References OpenSCADUtils.callopenscadstring().
parseargs()
def prototype.parseargs (argstring)
References parseexpression().
Referenced by parsenode().
parseexpression()
def prototype.parseexpression (e)
Referenced by parseargs().
parsenode()
def prototype.parsenode (str1)
References parseargs(), and parsenode().
Referenced by parsenode().
readfile()
def prototype.readfile (filename)
References pythonopen, and OpenSCADUtils.workaroundforissue128needed().
Referenced by insert(), and open().
Variable Documentation
dxfcache
dictionary prototype.dxfcache = {}
pythonopen
prototype.pythonopen = open
Referenced by readfile().