FreeCAD: PartDesignGui::Workbench Class Reference
PartDesignGui::Workbench Class Reference
#include <Workbench.h>
Public Member Functions
virtual void activated ()
Run some actions when the workbench gets activated.
virtual void deactivated ()
Run some actions when the workbench gets deactivated.
virtual void setupContextMenu (const char *recipient, Gui::MenuItem *) const
Add custom entries to the context menu.
Workbench ()
virtual ~Workbench ()
Public Member Functions inherited from Gui::StdWorkbench
virtual void createMainWindowPopupMenu (MenuItem *) const
Sets up the contextmenu for the main window for this workbench.
StdWorkbench ()
virtual ~StdWorkbench ()
Public Member Functions inherited from Gui::Workbench
bool activate ()
Activates the workbench and adds/removes GUI elements.
void addTaskWatcher (const std::vector< Gui::TaskView::TaskWatcher * > &Watcher)
helper to add TaskWatcher to the TaskView
PyObject * getPyObject ()
The default implementation returns an instance of WorkbenchPy.
std::list< std::pair< std::string, std::list< std::string > > > getToolbarItems () const
Shows a list of all toolbars and their commands.
std::list< std::string > listCommandbars () const
std::list< std::string > listMenus () const
std::list< std::string > listToolbars () const
std::string name () const
Returns the name of the workbench object.
void removeTaskWatcher (void)
remove the added TaskWatcher
void retranslate () const
Translates the window titles of all menus, toolbars and dock windows.
void setName (const std::string &)
Set the name to the workbench object.
Workbench ()
Constructs a workbench object.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual Type getTypeId (void) const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Member Functions
Gui::ToolBarItem * setupCommandBars () const
Defines the standard command bars.
Gui::MenuItem * setupMenuBar () const
Defines the standard menus.
Gui::ToolBarItem * setupToolBars () const
Defines the standard toolbars.
Protected Member Functions inherited from Gui::StdWorkbench
virtual DockWindowItems * setupDockWindows () const
Returns a DockWindowItems structure of dock windows this workbench.
Additional Inherited Members
Static Public Member Functions inherited from Gui::Workbench
static void createLinkMenu (MenuItem *)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Author
Werner Mayer
Constructor & Destructor Documentation
Workbench()
Workbench::Workbench ()
~Workbench()
Workbench::~Workbench () virtual
Reimplemented from Gui::Workbench.
References PartDesignGui::WorkflowManager::destruct().
Member Function Documentation
activated()
void Workbench::activated () virtual
Run some actions when the workbench gets activated.
Reimplemented from Gui::Workbench.
References Gui::Workbench::activated(), Gui::Workbench::addTaskWatcher(), draftgeoutils.faces::bind(), Gui::Control(), App::GetApplication(), PartDesignGui::WorkflowManager::init(), Gui::Application::Instance, Gui::ControlSingleton::showTaskView(), Gui::Application::signalActiveDocument, App::Application::signalDeleteDocument, App::Application::signalFinishRestoreDocument, and App::Application::signalNewDocument.
deactivated()
void Workbench::deactivated () virtual
Run some actions when the workbench gets deactivated.
Reimplemented from Gui::Workbench.
References draftgeoutils.faces::bind(), Gui::Workbench::deactivated(), Gui::Command::Doc, App::GetApplication(), Gui::Application::Instance, Gui::Workbench::removeTaskWatcher(), Gui::Application::signalActiveDocument, App::Application::signalDeleteDocument, App::Application::signalFinishRestoreDocument, and App::Application::signalNewDocument.
setupCommandBars()
Gui::ToolBarItem * Workbench::setupCommandBars () const protected virtual
Defines the standard command bars.
Reimplemented from Gui::StdWorkbench.
setupContextMenu()
void Workbench::setupContextMenu (const char * recipient, Gui::MenuItem * item) const virtual
Add custom entries to the context menu.
Reimplemented from Gui::StdWorkbench.
References Gui::Application::activeView(), Part::BodyBase::BaseFeature, App::Document::countObjectsOfType(), Gui::SelectionSingleton::countObjectsOfType(), Gui::BaseView::getAppDocument(), PartDesignGui::getBodyFor(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), Gui::SelectionSingleton::getSelection(), App::PropertyLink::getValue(), Gui::MenuItem::hasItems(), App::OriginGroupExtension::hasObject(), Gui::Application::Instance, PartDesign::Body::isAllowed(), Base::BaseClass::isDerivedFrom(), PartDesignGui::isModernWorkflow(), Gui::Selection(), and Gui::StdWorkbench::setupContextMenu().
setupMenuBar()
Gui::MenuItem * Workbench::setupMenuBar () const protected virtual
Defines the standard menus.
Reimplemented from Gui::StdWorkbench.
References Gui::MenuItem::findItem(), Gui::MenuItem::insertItem(), Gui::Application::Instance, and Gui::MenuItem::setCommand().
setupToolBars()
Gui::ToolBarItem * Workbench::setupToolBars () const protected virtual
Defines the standard toolbars.
Reimplemented from Gui::StdWorkbench.
References Gui::ToolBarItem::setCommand().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/PartDesign/Gui/Workbench.h
Sources/FreeCAD/src/Mod/PartDesign/Gui/Workbench.cpp