FreeCAD: Gui::Dialog::Ui_DownloadManager Class Reference
Gui::Dialog::Ui_DownloadManager Class Reference
#include <ui_DownloadManager.h>
Public Member Functions
void retranslateUi (QDialog *Gui__Dialog__DownloadManager)
void setupUi (QDialog *Gui__Dialog__DownloadManager)
Public Attributes
QPushButton * cleanupButton
EditTableView * downloadsView
QGridLayout * gridLayout
QHBoxLayout * horizontalLayout
QSpacerItem * horizontalSpacer
QLabel * itemCount
QSpacerItem * spacerItem
Member Function Documentation
retranslateUi()
void Gui::Dialog::Ui_DownloadManager::retranslateUi (QDialog * Gui__Dialog__DownloadManager)
References cleanupButton, itemCount, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::Dialog::Ui_DownloadManager::setupUi (QDialog * Gui__Dialog__DownloadManager)
References cleanupButton, downloadsView, gridLayout, horizontalLayout, horizontalSpacer, itemCount, retranslateUi(), and spacerItem.
Member Data Documentation
cleanupButton
QPushButton* Gui::Dialog::Ui_DownloadManager::cleanupButton
Referenced by retranslateUi(), and setupUi().
downloadsView
EditTableView* Gui::Dialog::Ui_DownloadManager::downloadsView
Referenced by setupUi().
gridLayout
QGridLayout* Gui::Dialog::Ui_DownloadManager::gridLayout
Referenced by setupUi().
horizontalLayout
QHBoxLayout* Gui::Dialog::Ui_DownloadManager::horizontalLayout
Referenced by setupUi().
horizontalSpacer
QSpacerItem* Gui::Dialog::Ui_DownloadManager::horizontalSpacer
Referenced by setupUi().
itemCount
QLabel* Gui::Dialog::Ui_DownloadManager::itemCount
Referenced by retranslateUi(), and setupUi().
spacerItem
QSpacerItem* Gui::Dialog::Ui_DownloadManager::spacerItem
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_DownloadManager.h