FreeCAD: Gui::DocumentModel Class Reference
Gui::DocumentModel Class Reference
#include <DocumentModel.h>
Public Member Functions
int columnCount (const QModelIndex &parent=QModelIndex()) const
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
DocumentModel (QObject *parent)
Qt::ItemFlags flags (const QModelIndex &index) const
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
QModelIndex parent (const QModelIndex &index) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
bool setData (const QModelIndex &idx, const QVariant &value, int role)
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
virtual ~DocumentModel ()
Constructor & Destructor Documentation
DocumentModel()
DocumentModel::DocumentModel (QObject * parent)
References draftgeoutils.faces::bind(), Base::BaseClass::init(), Gui::Application::Instance, Gui::Application::signalActiveDocument, Gui::Application::signalDeleteDocument, Gui::Application::signalNewDocument, Gui::Application::signalRelabelDocument, and Gui::Application::signalRenameDocument.
~DocumentModel()
DocumentModel::~DocumentModel () virtual
Member Function Documentation
columnCount()
int DocumentModel::columnCount (const QModelIndex & parent = QModelIndex()) const
data()
QVariant DocumentModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
References data().
Referenced by Mod.Show.mTempoVis.TempoVis::activateWorkbench(), Mod.Show.SceneDetail.SceneDetail::apply_data(), importIFClegacy.IfcSchema::capitalize(), data(), Mod.Show.mTempoVis.TempoVis::forget(), Mod.Show.mTempoVis.TempoVis::forgetDetail(), Mod.Show.mTempoVis.TempoVis::has(), ArchSchedule.CommandArchSchedule::IsActive(), importIFClegacy.IfcSchema::readEntities(), importIFClegacy.IfcSchema::readTypes(), Mod.Show.mTempoVis.TempoVis::restore(), Mod.Show.mTempoVis.TempoVis::save(), Mod.Show.mTempoVis.TempoVis::stored_val(), FeaturePython.ViewProviderOctahedron::updateData(), and Dice3DS.dom3ds.UndefinedChunk::write().
flags()
Qt::ItemFlags DocumentModel::flags (const QModelIndex & index) const
References flags().
Referenced by flags().
headerData()
QVariant DocumentModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
index()
QModelIndex DocumentModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const
References parent(), and Gui::DocumentModelP::rootItem.
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::addSegment(), Dice3DS.dom3ds.FileLikeBuffer::advance(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::begin(), Spreadsheet_legacy.MathParser::getValue(), Spreadsheet_legacy.MathParser::hasNext(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::interval(), PathScripts.PathJobDlg.JobCreate::item1ValueChanged(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::length(), Spreadsheet_legacy.MathParser::parseAddition(), Spreadsheet_legacy.MathParser::parseMultiplication(), Spreadsheet_legacy.MathParser::parseNegative(), Spreadsheet_legacy.MathParser::parseNumber(), Spreadsheet_legacy.MathParser::parseParenthesis(), Spreadsheet_legacy.MathParser::parseVariable(), Spreadsheet_legacy.MathParser::peek(), Dice3DS.dom3ds.FileLikeBuffer::read(), Dice3DS.dom3ds.FileLikeBuffer::read_fbuf(), Dice3DS.dom3ds.FileLikeBuffer::read_rest(), Dice3DS.dom3ds.FileLikeBuffer::read_to_nul(), Dice3DS.dom3ds.FileLikeBuffer::room_for_chunks(), Dice3DS.dom3ds.FileLikeBuffer::seek(), package_list.PackageListItemModel::setData(), PathScripts.PathJobDlg.JobCreate::setupColumnEditor(), Spreadsheet_legacy.MathParser::skipWhitespace(), Dice3DS.dom3ds.FileLikeBuffer::tell(), package_list.PackageListItemModel::update_item_icon(), package_list.PackageListItemModel::update_item_status(), automotive_design.index_expression::wr1(), and automotive_design.index_expression::wr2().
parent()
QModelIndex DocumentModel::parent (const QModelIndex & index) const
References Gui::DocumentModelIndex::parent(), parent(), and Gui::DocumentModelP::rootItem.
Referenced by PathScripts.PathSimulatorGui.CAMSimTaskUi::accept(), Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium(), index(), parent(), PathScripts.PathSimulatorGui.CAMSimTaskUi::reject(), rowCount(), and PathScripts.PathOpGui.TaskPanelPage::setParent().
rowCount()
int DocumentModel::rowCount (const QModelIndex & parent = QModelIndex()) const
References Gui::DocumentModelIndex::childCount(), and parent().
Referenced by package_list.PackageListItemModel::append_item(), and package_list.PackageListItemModel::clear().
setData()
bool DocumentModel::setData (const QModelIndex & idx, const QVariant & value, int role)
References setData().
Referenced by setData(), package_list.PackageListItemModel::update_item_icon(), and package_list.PackageListItemModel::update_item_status().
setHeaderData()
bool DocumentModel::setHeaderData (int section, Qt::Orientation orientation, const QVariant & value, int role = Qt::EditRole)
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DocumentModel.h
FreeCAD/src/Gui/DocumentModel.cpp