FreeCAD: PartGui Namespace Reference
PartGui Namespace Reference
Namespaces
Ui
Classes
class ArcEngine
class BooleanOperationItem
class BOPProgressIndicator
class BoxSelection
class CircleFromThreePoints
class CrossSections
class DimensionAngular
class DimensionControl
class DimensionLinear
class DimSelections
class DlgBooleanOperation
class DlgChamferEdges
class DlgExtrusion
class DlgFilletEdges
class DlgImportExportIges
class DlgImportExportStep
class DlgPartBoxImp
class DlgPartCylinderImp
class DlgPartImportIgesImp
class DlgPartImportStepImp
class DlgPrimitives
class DlgProjectionOnSurface
class DlgRevolution
class DlgSettings3DViewPart
The DlgSettings3DViewPartImp class implements a preference page to change settings for the Inventor viewer.
class DlgSettingsGeneral
class DlgSettingsObjectColor
The DlgSettingsObjectColor class implements a preference page to change color settings for data objects.
class EdgeFaceSelection
class FaceColors
class FaceSelection
class FilletEdgesDialog
class FilletRadiusDelegate
class FilletRadiusModel
class Location
class LoftWidget
class Mirroring
class Module
class OffsetWidget
class Picker
class PropertyEnumAttacherItem
Custom editor item for PropertyEnumeration to open Attacher task.
class ResultEntry
class ResultModel
class ShapeBuilderWidget
class ShapeSelection
class SoBrepEdgeSet
class SoBrepFaceSet
First some words to the history and the reason why we have this class: In older FreeCAD versions we had an own Inventor node for each sub-element of a shape with its own highlight node.
class SoBrepPointSet
class SoFCControlPoints
class SteppedSelection
class SweepWidget
class TaskAttacher
class TaskBooleanOperation
class TaskChamferEdges
class TaskCheckGeometryDialog
class TaskCheckGeometryResults
class TaskCrossSections
class TaskDlgAttacher
simulation dialog for the TaskView
class TaskExtrusion
class TaskFaceColors
class TaskFilletEdges
class TaskLoft
class TaskMeasureAngular
class TaskMeasureLinear
class TaskMirroring
class TaskOffset
class TaskPrimitives
class TaskPrimitivesEdit
class TaskProjectionOnSurface
class TaskRevolution
class TaskShapeBuilder
class TaskSweep
class TaskThickness
class ThicknessWidget
class VectorAdapter
Convert to vector.
class ViewProvider2DObject
class ViewProvider2DObjectGrid
class ViewProviderAttachExtension
class ViewProviderBoolean
class ViewProviderBox
class ViewProviderChamfer
class ViewProviderCircleParametric
class ViewProviderCompound
class ViewProviderConeParametric
class ViewProviderCrossSections
class ViewProviderCurveNet
class ViewProviderCustom
class ViewProviderCylinderParametric
class ViewProviderEllipseParametric
class ViewProviderEllipsoid
class ViewProviderExtrusion
class ViewProviderFace
class ViewProviderFillet
class ViewProviderHelixParametric
class ViewProviderImport
class ViewProviderLineParametric
class ViewProviderLoft
class ViewProviderMirror
class ViewProviderMultiCommon
ViewProvider for the MultiFuse feature.
class ViewProviderMultiFuse
ViewProvider for the MultiFuse feature.
class ViewProviderOffset
class ViewProviderOffset2D
class ViewProviderPart
class ViewProviderPartExt
class ViewProviderPartReference
class ViewProviderPlaneParametric
class ViewProviderPointParametric
class ViewProviderPrimitive
class ViewProviderPrism
class ViewProviderRefine
class ViewProviderRegularPolygon
class ViewProviderReverse
class ViewProviderRevolution
class ViewProviderRuledSurface
class ViewProviderShapeBuilder
class ViewProviderSphereParametric
class ViewProviderSpiralParametric
class ViewProviderSpline
class ViewProviderSplineExtension
class ViewProviderSweep
class ViewProviderThickness
class ViewProviderTorusParametric
class ViewProviderWedge
class Workbench
Typedefs
typedef boost::signals2::connection Connection
typedef boost::tuple< TopAbs_ShapeEnum, BRepCheck_Status, ResultFunction > FunctionMapType
typedef boost::function< void(ResultEntry *entry)> ResultFunction
typedef std::shared_ptr< Ui_DlgPartBox > Ui_DlgPartBoxPtr
typedef std::shared_ptr< Ui_DlgPartCylinder > Ui_DlgPartCylinderPtr
typedef Gui::ViewProviderPythonFeatureT< ViewProvider2DObject > ViewProvider2DObjectPython
typedef Gui::ViewProviderExtensionPythonT< PartGui::ViewProviderAttachExtension > ViewProviderAttachExtensionPython
typedef Gui::ViewProviderPythonFeatureT< ViewProviderCustom > ViewProviderCustomPython
typedef Gui::ViewProviderPythonFeatureT< ViewProviderPart > ViewProviderPython
typedef Gui::ViewProviderExtensionPythonT< PartGui::ViewProviderSplineExtension > ViewProviderSplineExtensionPython
Functions
void addLinearDimensions (const BRepExtrema_DistShapeShape &measure)
QString buildSelectionName (const ResultEntry *entry, const TopoDS_Shape &shape)
bool checkForSolids (const TopoDS_Shape &shape)
gp_Vec convert (const TopoDS_Vertex &vertex)
SoNode * createLinearDimension (const gp_Pnt &point1, const gp_Pnt &point2, const SbColor &color)
void dumpLinearResults (const BRepExtrema_DistShapeShape &measure)
void ensure3dDimensionVisible ()
void ensureSomeDimensionVisible ()
void eraseAllDimensions ()
bool evaluateAngularPreSelection (VectorAdapter &vector1Out, VectorAdapter &vector2Out)
bool evaluateLinearPreSelection (TopoDS_Shape &shape1, TopoDS_Shape &shape2)
const char * gce_ErrorStatusText (gce_ErrorType et)
bool getShapeFromStrings (TopoDS_Shape &shapeOut, const std::string &doc, const std::string &object, const std::string &sub, Base::Matrix4D *mat=0)
Gui::View3DInventorViewer * getViewer ()
void goDimensionAngularNoTask (const VectorAdapter &vector1Adapter, const VectorAdapter &vector2Adapter)
void goDimensionAngularRoot ()
void goDimensionLinearNoTask (const TopoDS_Shape &shape1, const TopoDS_Shape &shape2)
void goDimensionLinearRoot ()
void goSetupResultBoundingBox (ResultEntry *entry)
void goSetupResultIntersectingWires (ResultEntry *entry)
void goSetupResultInvalidCurveSurface (ResultEntry *entry)
void goSetupResultInvalidPointCurve (ResultEntry *entry)
void goSetupResultInvalidSameParameterFlag (ResultEntry *entry)
void goSetupResultShellNotClosed (ResultEntry *entry)
void goSetupResultTypedSelection (ResultEntry *entry, const TopoDS_Shape &shape, TopAbs_ShapeEnum type)
void goSetupResultUnorientableShapeFace (ResultEntry *entry)
void goSetupResultWireNotClosed (ResultEntry *entry)
PyObject * initModule ()
void refreshDimensions ()
void toggle3d ()
void toggleDelta ()
Typedef Documentation
Connection
typedef boost::signals2::connection PartGui::Connection
FunctionMapType
typedef boost::tuple<TopAbs_ShapeEnum, BRepCheck_Status, ResultFunction> PartGui::FunctionMapType
ResultFunction
typedef boost::function<void (ResultEntry *entry)> PartGui::ResultFunction
Ui_DlgPartBoxPtr
typedef std::shared_ptr<Ui_DlgPartBox> PartGui::Ui_DlgPartBoxPtr
Ui_DlgPartCylinderPtr
typedef std::shared_ptr<Ui_DlgPartCylinder> PartGui::Ui_DlgPartCylinderPtr
ViewProvider2DObjectPython
typedef Gui::ViewProviderPythonFeatureT<ViewProvider2DObject> PartGui::ViewProvider2DObjectPython
ViewProviderAttachExtensionPython
typedef Gui::ViewProviderExtensionPythonT<PartGui::ViewProviderAttachExtension> PartGui::ViewProviderAttachExtensionPython
ViewProviderCustomPython
typedef Gui::ViewProviderPythonFeatureT<ViewProviderCustom> PartGui::ViewProviderCustomPython
ViewProviderPython
typedef Gui::ViewProviderPythonFeatureT<ViewProviderPart> PartGui::ViewProviderPython
ViewProviderSplineExtensionPython
typedef Gui::ViewProviderExtensionPythonT<PartGui::ViewProviderSplineExtension> PartGui::ViewProviderSplineExtensionPython
Function Documentation
addLinearDimensions()
void PartGui::addLinearDimensions (const BRepExtrema_DistShapeShape & measure)
adds 3d and delta dimensions to the viewer
Parameters
measure object containing the measure information.
References App::Color::asHexString(), App::Color::b, createLinearDimension(), App::Color::fromHexString(), App::Color::g, App::GetApplication(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), getViewer(), App::Color::r, and OfflineRenderingUtils::viewer().
Referenced by goDimensionLinearNoTask().
buildSelectionName()
QString PartGui::buildSelectionName (const ResultEntry * entry, const TopoDS_Shape & shape)
References PartGui::ResultEntry::name, PartGui::ResultEntry::parent, and PartGui::ResultEntry::shape.
Referenced by goSetupResultTypedSelection().
checkForSolids()
bool PartGui::checkForSolids (const TopoDS_Shape & shape)
convert()
gp_Vec PartGui::convert (const TopoDS_Vertex & vertex)
Referenced by evaluateAngularPreSelection(), and PartGui::VectorAdapter::VectorAdapter().
createLinearDimension()
SoNode * PartGui::createLinearDimension (const gp_Pnt & point1, const gp_Pnt & point2, const SbColor & color)
creates one dimension from points with color
Parameters
point1 first point
point2 second point
color color of dimension
Returns
an inventor node to add to a scenegraph
References Base::Quantity::getUserString(), and Base::Unit::Length.
Referenced by addLinearDimensions().
dumpLinearResults()
void PartGui::dumpLinearResults (const BRepExtrema_DistShapeShape & measure)
prints results of measuring to console.
Parameters
measure object containing the measure information
References Base::Console(), Base::Quantity::getUserString(), Base::Unit::Length, and Base::ConsoleSingleton::Message().
Referenced by goDimensionLinearNoTask().
ensure3dDimensionVisible()
void PartGui::ensure3dDimensionVisible ()
make sure angle measure command isn't working with 3d off. Confusing the user
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by goDimensionAngularRoot().
ensureSomeDimensionVisible()
void PartGui::ensureSomeDimensionVisible ()
make sure measure command isn't working with everything invisible. Confusing the user
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by goDimensionLinearRoot().
eraseAllDimensions()
void PartGui::eraseAllDimensions ()
erases all the dimensions in the viewer.
References Gui::Application::activeDocument(), Gui::Application::Instance, and OfflineRenderingUtils::viewer().
Referenced by PartGui::DimensionControl::clearAllSlot(), PartGui::TaskMeasureLinear::clearAllSlot(), PartGui::TaskMeasureAngular::clearAllSlot(), and refreshDimensions().
evaluateAngularPreSelection()
bool PartGui::evaluateAngularPreSelection (VectorAdapter & vector1Out, VectorAdapter & vector2Out)
examine angular pre selection
Parameters
vector1Out first shape in current selection
vector2Out second shape in current selection
Returns
signal if preselection is valid. false means vector1Out and vector2Out are invalid.
References Base::Console(), convert(), PartGui::DimSelections::Edge, draftutils.utils::epsilon(), PartGui::DimSelections::Face, App::Application::getActiveDocument(), App::GetApplication(), PartGui::VectorAdapter::getPickPoint(), Gui::SelectionSingleton::getSelection(), Part::Feature::getShape(), Base::Matrix4D::inverse(), Base::ConsoleSingleton::Message(), Gui::Selection(), and PartGui::DimSelections::Vertex.
Referenced by goDimensionAngularRoot().
evaluateLinearPreSelection()
bool PartGui::evaluateLinearPreSelection (TopoDS_Shape & shape1, TopoDS_Shape & shape2)
examine pre selection
Parameters
shape1 first shape in current selection
shape2 second shape in current selection
Returns
signal if preselection is valid. false means shape1 and shape2 are invalid.
References App::Application::getActiveDocument(), App::GetApplication(), Gui::SelectionSingleton::getSelection(), Part::Feature::getShape(), Gui::Selection(), and PartGui::DimSelections::selections.
Referenced by goDimensionLinearRoot().
gce_ErrorStatusText()
const char* PartGui::gce_ErrorStatusText (gce_ErrorType et)
Referenced by PartGui::CircleFromThreePoints::command().
getShapeFromStrings()
bool PartGui::getShapeFromStrings (TopoDS_Shape & shapeOut, const std::string & doc, const std::string & object, const std::string & sub, Base::Matrix4D * mat = 0)
find shape from selection strings
Parameters
shapeOut search results.
doc document name to search.
object object name to search.
sub sub-object name to search.
Returns
signal if the search was successful.
References App::GetApplication(), App::Application::getDocument(), App::Document::getObject(), and Part::Feature::getShape().
Referenced by PartGui::TaskMeasureLinear::buildDimension(), and PartGui::TaskMeasureAngular::onSelectionChanged().
getViewer()
Gui::View3DInventorViewer * PartGui::getViewer ()
convenience function to get the viewer
References Gui::Application::activeDocument(), Gui::Application::Instance, and OfflineRenderingUtils::viewer().
Referenced by addLinearDimensions(), goDimensionAngularNoTask(), goDimensionLinearNoTask(), and PartGui::Location::~Location().
goDimensionAngularNoTask()
void PartGui::goDimensionAngularNoTask (const VectorAdapter & vector1Adapter, const VectorAdapter & vector2Adapter)
build angular dimension
References Base::Unit::Angle, DraftVecUtils::angle(), Base::Console(), App::GetApplication(), ParameterGrp::GetGroup(), PartGui::VectorAdapter::getPickPoint(), App::Application::GetUserParameter(), getViewer(), Base::ConsoleSingleton::Message(), and OfflineRenderingUtils::viewer().
Referenced by PartGui::TaskMeasureAngular::buildDimension(), and goDimensionAngularRoot().
goDimensionAngularRoot()
void PartGui::goDimensionAngularRoot ()
start of the measure angular command
References Gui::ControlSingleton::activeDialog(), Gui::SelectionSingleton::clearSelection(), Gui::Control(), ensure3dDimensionVisible(), evaluateAngularPreSelection(), goDimensionAngularNoTask(), Gui::Selection(), and Gui::ControlSingleton::showDialog().
goDimensionLinearNoTask()
void PartGui::goDimensionLinearNoTask (const TopoDS_Shape & shape1, const TopoDS_Shape & shape2)
does the measure and create dimensions without a dialog
Parameters
shape1 first shape.
shape2 second shape.
References addLinearDimensions(), dumpLinearResults(), getViewer(), and OfflineRenderingUtils::viewer().
Referenced by PartGui::TaskMeasureLinear::buildDimension(), and goDimensionLinearRoot().
goDimensionLinearRoot()
void PartGui::goDimensionLinearRoot ()
start of the measure linear command
References Gui::ControlSingleton::activeDialog(), Gui::SelectionSingleton::clearSelection(), Gui::Control(), ensureSomeDimensionVisible(), evaluateLinearPreSelection(), goDimensionLinearNoTask(), Gui::Selection(), and Gui::ControlSingleton::showDialog().
goSetupResultBoundingBox()
void PartGui::goSetupResultBoundingBox (ResultEntry * entry)
References PartGui::ResultEntry::boxSep, PartGui::ResultEntry::boxSwitch, PartGui::ResultEntry::shape, and PartGui::ResultEntry::viewProviderRoot.
Referenced by PartGui::TaskCheckGeometryResults::goCheck(), goSetupResultIntersectingWires(), goSetupResultInvalidCurveSurface(), goSetupResultInvalidPointCurve(), goSetupResultInvalidSameParameterFlag(), goSetupResultShellNotClosed(), goSetupResultUnorientableShapeFace(), and goSetupResultWireNotClosed().
goSetupResultIntersectingWires()
void PartGui::goSetupResultIntersectingWires (ResultEntry * entry)
References goSetupResultBoundingBox(), goSetupResultTypedSelection(), and PartGui::ResultEntry::shape.
goSetupResultInvalidCurveSurface()
void PartGui::goSetupResultInvalidCurveSurface (ResultEntry * entry)
References goSetupResultBoundingBox(), goSetupResultTypedSelection(), and PartGui::ResultEntry::shape.
goSetupResultInvalidPointCurve()
void PartGui::goSetupResultInvalidPointCurve (ResultEntry * entry)
References goSetupResultBoundingBox(), goSetupResultTypedSelection(), and PartGui::ResultEntry::shape.
goSetupResultInvalidSameParameterFlag()
void PartGui::goSetupResultInvalidSameParameterFlag (ResultEntry * entry)
References goSetupResultBoundingBox(), goSetupResultTypedSelection(), and PartGui::ResultEntry::shape.
goSetupResultShellNotClosed()
void PartGui::goSetupResultShellNotClosed (ResultEntry * entry)
References goSetupResultBoundingBox(), goSetupResultTypedSelection(), and PartGui::ResultEntry::shape.
goSetupResultTypedSelection()
void PartGui::goSetupResultTypedSelection (ResultEntry * entry, const TopoDS_Shape & shape, TopAbs_ShapeEnum type)
References buildSelectionName(), and PartGui::ResultEntry::selectionStrings.
Referenced by goSetupResultIntersectingWires(), goSetupResultInvalidCurveSurface(), goSetupResultInvalidPointCurve(), goSetupResultInvalidSameParameterFlag(), goSetupResultShellNotClosed(), goSetupResultUnorientableShapeFace(), and goSetupResultWireNotClosed().
goSetupResultUnorientableShapeFace()
void PartGui::goSetupResultUnorientableShapeFace (ResultEntry * entry)
References goSetupResultBoundingBox(), goSetupResultTypedSelection(), and PartGui::ResultEntry::shape.
goSetupResultWireNotClosed()
void PartGui::goSetupResultWireNotClosed (ResultEntry * entry)
References goSetupResultBoundingBox(), goSetupResultTypedSelection(), and PartGui::ResultEntry::shape.
initModule()
PyObject* PartGui::initModule ()
refreshDimensions()
void PartGui::refreshDimensions ()
refresh all the dimensions in the viewer.
References eraseAllDimensions(), App::Application::getActiveDocument(), and App::GetApplication().
toggle3d()
void PartGui::toggle3d ()
toggles the display status of the 3d dimensions
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by PartGui::DimensionControl::toggle3dSlot(), PartGui::TaskMeasureLinear::toggle3dSlot(), and PartGui::TaskMeasureAngular::toggle3dSlot().
toggleDelta()
void PartGui::toggleDelta ()
toggles the display status of the delta dimensions
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by PartGui::DimensionControl::toggleDeltaSlot(), PartGui::TaskMeasureLinear::toggleDeltaSlot(), and PartGui::TaskMeasureAngular::toggleDeltaSlot().