FreeCAD: Path::Tool Class Reference
Path::Tool Class Reference
The representation of a single tool.
#include <Tool.h>
Public Types
enum ToolMaterial {
MATUNDEFINED, HIGHSPEEDSTEEL, HIGHCARBONTOOLSTEEL, CASTALLOY,
CARBIDE, CERAMICS, DIAMOND, SIALON
}
enum ToolType {
UNDEFINED, DRILL, CENTERDRILL, COUNTERSINK,
COUNTERBORE, FLYCUTTER, REAMER, TAP,
ENDMILL, SLOTCUTTER, BALLENDMILL, CHAMFERMILL,
CORNERROUND, ENGRAVER
}
Public Member Functions
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
Tool ()
Tool (const char *name, ToolType type=Tool::UNDEFINED, ToolMaterial material=Tool::MATUNDEFINED, double diameter=10.0, double lengthoffset=100, double flatradius=0, double cornerradius=0, double cuttingedgeangle=0, double cuttingedgeheight=0)
~Tool ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static ToolMaterial getToolMaterial (std::string mat)
static ToolType getToolType (std::string type)
static const char * MaterialName (ToolMaterial mat)
static const std::vector< std::string > ToolMaterials (void)
static const std::vector< std::string > ToolTypes (void)
static const char * TypeName (ToolType typ)
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Public Attributes
double CornerRadius
double CuttingEdgeAngle
double CuttingEdgeHeight
double Diameter
double FlatRadius
double LengthOffset
ToolMaterial Material
std::string Name
ToolType Type
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The representation of a single tool.
Member Enumeration Documentation
ToolMaterial
enum Path::Tool::ToolMaterial
Enumerator
MATUNDEFINED
HIGHSPEEDSTEEL
HIGHCARBONTOOLSTEEL
CASTALLOY
CARBIDE
CERAMICS
DIAMOND
SIALON
ToolType
enum Path::Tool::ToolType
Enumerator
UNDEFINED
DRILL
CENTERDRILL
COUNTERSINK
COUNTERBORE
FLYCUTTER
REAMER
TAP
ENDMILL
SLOTCUTTER
BALLENDMILL
CHAMFERMILL
CORNERROUND
ENGRAVER
Constructor & Destructor Documentation
Tool() [1/2]
Tool::Tool ()
Tool() [2/2]
Tool::Tool (const char * name, ToolType type = Tool::UNDEFINED, ToolMaterial material = Tool::MATUNDEFINED, double diameter = 10.0, double lengthoffset = 100, double flatradius = 0, double cornerradius = 0, double cuttingedgeangle = 0, double cuttingedgeheight = 0)
~Tool()
Tool::~Tool ()
Member Function Documentation
getMemSize()
unsigned int Tool::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
getToolMaterial()
Tool::ToolMaterial Tool::getToolMaterial (std::string mat) static
Referenced by Path::ToolPy::PyInit(), and Path::ToolPy::setMaterial().
getToolType()
Tool::ToolType Tool::getToolType (std::string type) static
Referenced by Path::ToolPy::PyInit(), and Path::ToolPy::setToolType().
MaterialName()
const char * Tool::MaterialName (Tool::ToolMaterial mat) static
Referenced by Path::ToolPy::getMaterial(), and Path::ToolPy::templateAttrs().
Restore()
void Tool::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References Base::XMLReader::getAttribute(), Base::XMLReader::getAttributeAsFloat(), Base::XMLReader::hasAttribute(), and Base::XMLReader::readElement().
Referenced by Path::Tooltable::Restore(), Path::PropertyTool::Restore(), and Path::ToolPy::setFromTemplate().
Save()
void Tool::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References Base::Writer::ind(), and Base::Writer::Stream().
ToolMaterials()
const std::vector< std::string > Tool::ToolMaterials (void) static
Referenced by Path::ToolPy::getToolMaterials().
ToolTypes()
const std::vector< std::string > Tool::ToolTypes (void) static
Referenced by Path::ToolPy::getToolTypes().
TypeName()
const char * Tool::TypeName (Tool::ToolType typ) static
Referenced by Path::ToolPy::getToolType(), and Path::ToolPy::templateAttrs().
Member Data Documentation
CornerRadius
double Path::Tool::CornerRadius
Referenced by Path::ToolPy::PyInit(), and Path::ToolPy::setCornerRadius().
CuttingEdgeAngle
double Path::Tool::CuttingEdgeAngle
Referenced by Path::ToolPy::PyInit(), and Path::ToolPy::setCuttingEdgeAngle().
CuttingEdgeHeight
double Path::Tool::CuttingEdgeHeight
Referenced by Path::ToolPy::PyInit(), and Path::ToolPy::setCuttingEdgeHeight().
Diameter
double Path::Tool::Diameter
Referenced by Path::ToolPy::PyInit(), Path::ToolPy::setDiameter(), and PathTests.TestPathDeburr.TestPathDeburr::test11().
FlatRadius
double Path::Tool::FlatRadius
Referenced by Path::ToolPy::PyInit(), and Path::ToolPy::setFlatRadius().
LengthOffset
double Path::Tool::LengthOffset
Referenced by Path::ToolPy::PyInit(), and Path::ToolPy::setLengthOffset().
Material
ToolMaterial Path::Tool::Material
Referenced by Path::ToolPy::PyInit(), and Path::ToolPy::setMaterial().
Name
std::string Path::Tool::Name
Referenced by Path::ToolPy::PyInit(), Path::ToolPy::representation(), and Path::ToolPy::setName().
Type
ToolType Path::Tool::Type
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), Path::ToolPy::PyInit(), and Path::ToolPy::setToolType().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Path/App/Tool.h
Sources/FreeCAD/src/Mod/Path/App/Tool.cpp