FreeCAD: Gui::ColorButton Class Reference
Gui::ColorButton Class Reference
Implementation of a color button.
#include <Widgets.h>
Public Slots
void onChooseColor ()
Opens a QColorDialog to set a new color.
Signals
void changed ()
Emits this signal when color has changed.
Public Member Functions
bool allowChangeColor () const
bool allowTransparency () const
bool autoChangeColor () const
QColor color () const
Returns the current color of the button.
ColorButton (QWidget *parent=nullptr)
Constructs a colored button called name with parent parent.
bool drawFrame () const
bool isModal () const
void setAllowChangeColor (bool)
void setAllowTransparency (bool)
void setAutoChangeColor (bool)
void setColor (const QColor &)
Sets the color c to the button.
void setDrawFrame (bool)
void setModal (bool)
~ColorButton ()
Destroys the button.
Protected Member Functions
void paintEvent (QPaintEvent *)
Draws the button label.
Properties
bool allowChangeColor
bool allowTransparency
QColor color
bool drawFrame
Detailed Description
Implementation of a color button.
Author
Werner Mayer
Constructor & Destructor Documentation
ColorButton()
ColorButton::ColorButton (QWidget * parent = nullptr)
Constructs a colored button called name with parent parent.
References Gui::ColorButtonP::col, draftgeoutils.intersections::connect(), and onChooseColor().
~ColorButton()
ColorButton::~ColorButton ()
Destroys the button.
Member Function Documentation
allowChangeColor()
bool ColorButton::allowChangeColor () const
References Gui::ColorButtonP::allowChange.
allowTransparency()
bool Gui::ColorButton::allowTransparency () const
autoChangeColor()
bool ColorButton::autoChangeColor () const
References Gui::ColorButtonP::autoChange.
changed
void Gui::ColorButton::changed () signal
Emits this signal when color has changed.
Referenced by onChooseColor().
color()
QColor ColorButton::color () const
Returns the current color of the button.
References Gui::ColorButtonP::col.
Referenced by ArchSite.Compass::buildCoordinates(), draftviewproviders.view_dimension.ViewProviderLinearDimension::draw_dim_arrows(), draftviewproviders.view_dimension.ViewProviderAngularDimension::draw_dim_arrows(), draftviewproviders.view_dimension.ViewProviderLinearDimension::draw_dim_overshoot(), draftviewproviders.view_dimension.ViewProviderLinearDimension::draw_ext_overshoot(), draftguitools.gui_trimex.Trimex::finish(), importSVG.svgHandler::format(), DraftGui.DraftToolBar::getcol(), DraftGui.DraftToolBar::getDefaultColor(), PathScripts.PathDressupDogbone.Marker::highlight(), PathScripts.PathDressupDogbone.Marker::lowlight(), ArchPanel.ViewProviderPanelCut::onChanged(), ArchPanel.ViewProviderPanelSheet::onChanged(), draftviewproviders.view_dimension.ViewProviderLinearDimension::onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension::onChanged(), FeaturePython.ViewProviderOctahedron::onChanged(), Mod.Test.unittestgui.ProgressBar::paint(), draftguitools.gui_trackers.editTracker::setColor(), PathScripts.PathDressupTagGui.HoldingTagMarker::setEnabled(), and DraftGui.DraftToolBar::setStyleButton().
drawFrame()
bool ColorButton::drawFrame () const
References Gui::ColorButtonP::drawFrame.
isModal()
bool ColorButton::isModal () const
References Gui::ColorButtonP::modal.
onChooseColor
void ColorButton::onChooseColor () slot
Opens a QColorDialog to set a new color.
References Gui::ColorButtonP::allowChange, Gui::ColorButtonP::allowTransparency, Gui::ColorButtonP::autoChange, Gui::ColorButtonP::cd, changed(), Gui::ColorButtonP::col, draftgeoutils.intersections::connect(), Gui::DialogOptions::dontUseNativeColorDialog(), Gui::ColorButtonP::modal, Gui::ColorButtonP::old, and setColor().
Referenced by ColorButton().
paintEvent()
void ColorButton::paintEvent (QPaintEvent * e) protected
Draws the button label.
References Gui::ColorButtonP::col, color, Gui::ColorButtonP::dirty, and Gui::ColorButtonP::drawFrame.
setAllowChangeColor()
void ColorButton::setAllowChangeColor (bool ok)
References Gui::ColorButtonP::allowChange.
setAllowTransparency()
void Gui::ColorButton::setAllowTransparency (bool allow)
Referenced by PartGui::FaceColors::FaceColors().
setAutoChangeColor()
void ColorButton::setAutoChangeColor (bool on)
References Gui::ColorButtonP::autoChange.
setColor()
void ColorButton::setColor (const QColor & c)
Sets the color c to the button.
References Gui::ColorButtonP::col, and Gui::ColorButtonP::dirty.
Referenced by onChooseColor(), PartGui::FaceColors::onSelectionChanged(), Gui::PrefColorButton::restorePreferences(), PartGui::SectionCut::SectionCut(), Ui_DlgStartPreferences::setupUi(), Gui::Dialog::Ui_DlgReportView::setupUi(), MeshGui::Ui_DlgSettingsMeshView::setupUi(), PartGui::Ui_DlgSettingsObjectColor::setupUi(), TechDrawGui::Ui_DlgPrefsTechDrawColorsImp::setupUi(), TechDrawGui::Ui_TaskBalloon::setupUi(), TechDrawGui::Ui_TaskCenterLine::setupUi(), TechDrawGui::Ui_TaskDimension::setupUi(), TechDrawGui::Ui_TaskLeaderLine::setupUi(), TechDrawGui::Ui_TaskLineDecor::setupUi(), and TechDrawGui::Ui_TaskRichAnno::setupUi().
setDrawFrame()
void ColorButton::setDrawFrame (bool ok)
References Gui::ColorButtonP::drawFrame.
setModal()
void ColorButton::setModal (bool b)
References Gui::ColorButtonP::modal.
Property Documentation
allowChangeColor
bool Gui::ColorButton::allowChangeColor read write
allowTransparency
bool Gui::ColorButton::allowTransparency read write
color
QColor Gui::ColorButton::color read write
Referenced by ArchSite.Compass::buildCoordinates(), draftviewproviders.view_dimension.ViewProviderLinearDimension::draw_dim_arrows(), draftviewproviders.view_dimension.ViewProviderAngularDimension::draw_dim_arrows(), draftviewproviders.view_dimension.ViewProviderLinearDimension::draw_dim_overshoot(), draftviewproviders.view_dimension.ViewProviderLinearDimension::draw_ext_overshoot(), draftguitools.gui_trimex.Trimex::finish(), importSVG.svgHandler::format(), DraftGui.DraftToolBar::getcol(), DraftGui.DraftToolBar::getDefaultColor(), PathScripts.PathDressupDogbone.Marker::highlight(), PathScripts.PathDressupDogbone.Marker::lowlight(), ArchPanel.ViewProviderPanelCut::onChanged(), ArchPanel.ViewProviderPanelSheet::onChanged(), draftviewproviders.view_dimension.ViewProviderLinearDimension::onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension::onChanged(), FeaturePython.ViewProviderOctahedron::onChanged(), Mod.Test.unittestgui.ProgressBar::paint(), paintEvent(), Gui::PrefColorButton::restorePreferences(), Gui::PrefColorButton::savePreferences(), draftguitools.gui_trackers.editTracker::setColor(), PathScripts.PathDressupTagGui.HoldingTagMarker::setEnabled(), and DraftGui.DraftToolBar::setStyleButton().
drawFrame
bool Gui::ColorButton::drawFrame read write
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/Widgets.h
FreeCAD/src/Gui/Widgets.cpp