FreeCAD: MeshPartGui::TaskCrossSections Class Reference
MeshPartGui::TaskCrossSections Class Reference
#include <CrossSections.h>
Public Member Functions
bool accept ()
is called by the framework if the dialog is accepted (Ok)
void clicked (int id)
is called by the framework if a button is clicked which has no accept or reject role
virtual QDialogButtonBox::StandardButtons getStandardButtons () const
tells the framework which buttons are wished for the dialog
TaskCrossSections (const Base::BoundBox3d &bb)
~TaskCrossSections ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Constructor & Destructor Documentation
TaskCrossSections()
TaskCrossSections::TaskCrossSections (const Base::BoundBox3d & bb)
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
~TaskCrossSections()
TaskCrossSections::~TaskCrossSections ()
Member Function Documentation
accept()
bool TaskCrossSections::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References MeshPartGui::CrossSections::accept().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
clicked()
void TaskCrossSections::clicked (int) virtual
is called by the framework if a button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
References MeshPartGui::CrossSections::apply().
getStandardButtons()
virtual QDialogButtonBox::StandardButtons MeshPartGui::TaskCrossSections::getStandardButtons (void) const virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/MeshPart/Gui/CrossSections.h
Sources/FreeCAD/src/Mod/MeshPart/Gui/CrossSections.cpp