FreeCAD: BOPTools Namespace Reference
BOPTools Namespace Reference
Workbenches » C++ workbenches » Part
Namespaces
namespace GeneralFuseResult
namespace JoinAPI
namespace JoinFeatures
namespace ShapeMerge
namespace SplitAPI
namespace SplitFeatures
namespace Utils
Functions
def addCommands ()
def generalFuseIsAvailable ()
def importAll ()
def reloadAll ()
Function Documentation
addCommands()
def BOPTools.addCommands ()
Referenced by reloadAll().
generalFuseIsAvailable()
def BOPTools.generalFuseIsAvailable ()
generalFuseIsAvailable(): returns True if FreeCAD's Part.Shape.generalFuse is functional.
True if Part.OCC_VERSION >= 7.0.0.
Referenced by BOPTools.JoinAPI.connect().
importAll()
def BOPTools.importAll ()
reloadAll()
def BOPTools.reloadAll ()
References addCommands().