FreeCAD: PartDesignGui::TaskDlgFeaturePick Class Reference
PartDesignGui::TaskDlgFeaturePick Class Reference
simulation dialog for the TaskView
#include <TaskFeaturePick.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void clicked (int)
is called by the framework if an button is clicked which has no accept or reject role
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
returns for Close and Help button
virtual bool isAllowedAlterDocument (void) const
is called by the framework if the user presses the help button
virtual void open ()
is called the TaskView when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void showExternal (bool val)
TaskDlgFeaturePick (std::vector< App::DocumentObject * > &objects, const std::vector< TaskFeaturePick::featureStatus > &status, std::function< bool(std::vector< App::DocumentObject * >)> acceptfunc, std::function< void(std::vector< App::DocumentObject * >)> workfunc, bool singleFeatureSelect, std::function< void(void)> abortfunc=0)
~TaskDlgFeaturePick ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
tells the framework which buttons are wished for the dialog
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Protected Attributes
std::function< void(void)> abortFunction
bool accepted
std::function< bool(std::vector< App::DocumentObject * >)> acceptFunction
TaskFeaturePick * pick
std::function< void(std::vector< App::DocumentObject * >)> workFunction
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
simulation dialog for the TaskView
Constructor & Destructor Documentation
TaskDlgFeaturePick()
TaskDlgFeaturePick::TaskDlgFeaturePick (std::vector< App::DocumentObject * > & objects, const std::vector< TaskFeaturePick::featureStatus > & status, std::function< bool(std::vector< App::DocumentObject * >)> acceptfunc, std::function< void(std::vector< App::DocumentObject * >)> workfunc, bool singleFeatureSelect, std::function< void(void)> abortfunc = 0)
References abortFunction, acceptFunction, Gui::TaskView::TaskDialog::Content, pick, and workFunction.
~TaskDlgFeaturePick()
TaskDlgFeaturePick::~TaskDlgFeaturePick ()
References abortFunction, accepted, PartDesignGui::TaskFeaturePick::buildFeatures(), Gui::TaskView::TaskDialog::Content, pick, and workFunction.
Member Function Documentation
accept()
bool TaskDlgFeaturePick::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References accepted, acceptFunction, PartDesignGui::TaskFeaturePick::getFeatures(), and pick.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
clicked()
void TaskDlgFeaturePick::clicked (int) virtual
is called by the framework if an button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
getStandardButtons()
virtual QDialogButtonBox::StandardButtons PartDesignGui::TaskDlgFeaturePick::getStandardButtons (void) const virtual
returns for Close and Help button
Reimplemented from Gui::TaskView::TaskDialog.
isAllowedAlterDocument()
virtual bool PartDesignGui::TaskDlgFeaturePick::isAllowedAlterDocument (void) const virtual
is called by the framework if the user presses the help button
Reimplemented from Gui::TaskView::TaskDialog.
open()
void TaskDlgFeaturePick::open () virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
reject()
bool TaskDlgFeaturePick::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References accepted.
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
showExternal()
void TaskDlgFeaturePick::showExternal (bool val)
References pick, and PartDesignGui::TaskFeaturePick::showExternal().
Member Data Documentation
abortFunction
std::function<void (void)> PartDesignGui::TaskDlgFeaturePick::abortFunction protected
Referenced by TaskDlgFeaturePick(), and ~TaskDlgFeaturePick().
accepted
bool PartDesignGui::TaskDlgFeaturePick::accepted protected
Referenced by accept(), reject(), and ~TaskDlgFeaturePick().
acceptFunction
std::function<bool (std::vector<App::DocumentObject*>)> PartDesignGui::TaskDlgFeaturePick::acceptFunction protected
Referenced by accept(), and TaskDlgFeaturePick().
pick
TaskFeaturePick* PartDesignGui::TaskDlgFeaturePick::pick protected
Referenced by accept(), showExternal(), TaskDlgFeaturePick(), and ~TaskDlgFeaturePick().
workFunction
std::function<void (std::vector<App::DocumentObject*>)> PartDesignGui::TaskDlgFeaturePick::workFunction protected
Referenced by TaskDlgFeaturePick(), and ~TaskDlgFeaturePick().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/PartDesign/Gui/TaskFeaturePick.h
FreeCAD/src/Mod/PartDesign/Gui/TaskFeaturePick.cpp