FreeCAD: feminout.importYamlJsonMesh Namespace Reference
feminout.importYamlJsonMesh Namespace Reference
Functions
def convert_raw_data_to_mesh_data (raw_mesh_data)
def export (objectslist, fileString)
def import_yaml_json_mesh (fileString)
def insert (filename, docname)
def open (filename)
def read (fileString)
def write (fileString, fem_mesh)
Variables
bool has_yaml = True
pyopen = open
Function Documentation
convert_raw_data_to_mesh_data()
def feminout.importYamlJsonMesh.convert_raw_data_to_mesh_data (raw_mesh_data)
Converts raw dictionary data from JSON or YAML file to proper dict
for importToolsFem.make_femmesh(mesh_data). This is necessary since
JSON and YAML save dict keys as strings while make_femmesh expects
integers.
Referenced by feminout.importYamlJsonMesh.read().
export()
def feminout.importYamlJsonMesh.export (objectslist, fileString)
References feminout.importYamlJsonMesh.write().
import_yaml_json_mesh()
def feminout.importYamlJsonMesh.import_yaml_json_mesh (fileString)
read a FemMesh from a yaml/json mesh file
insert a FreeCAD FEM Mesh object in the ActiveDocument
return the FEM mesh document object
References feminout.importYamlJsonMesh.read().
Referenced by feminout.importYamlJsonMesh.insert().
insert()
def feminout.importYamlJsonMesh.insert (filename, docname)
called when freecad wants to import a file"
a FEM mesh object is created in a existing document
References feminout.importYamlJsonMesh.import_yaml_json_mesh().
Referenced by feminout.importYamlJsonMesh.open().
open()
def feminout.importYamlJsonMesh.open (filename)
called when freecad opens a file
a FEM mesh object is created in a new document
References feminout.importYamlJsonMesh.insert().
read()
def feminout.importYamlJsonMesh.read (fileString)
read a FemMesh from a yaml/json mesh file and return the FemMesh
References feminout.importYamlJsonMesh.convert_raw_data_to_mesh_data(), and feminout.importYamlJsonMesh.pyopen.
Referenced by feminout.importYamlJsonMesh.import_yaml_json_mesh().
write()
def feminout.importYamlJsonMesh.write (fileString, fem_mesh)
directly write a FemMesh to a yaml/json mesh file
fem_mesh: a FemMesh
References feminout.importYamlJsonMesh.pyopen.
Referenced by feminout.importYamlJsonMesh.export().
Variable Documentation
has_yaml
bool feminout.importYamlJsonMesh.has_yaml = True
pyopen
feminout.importYamlJsonMesh.pyopen = open
Referenced by feminout.importYamlJsonMesh.read(), and feminout.importYamlJsonMesh.write().