FreeCAD: MED::TTFieldInfo< eVersion > Struct Template Reference
MED::TTFieldInfo< eVersion > Struct Template Reference
#include <MED_TStructures.hxx>
Public Types
typedef TTNameInfo< eVersion > TNameInfoBase
Public Member Functions
virtual std::string GetCompName (TInt theId) const
Get name of the component by its order number.
virtual std::string GetUnitName (TInt theId) const
Get unit of the component by its order number.
virtual void SetCompName (TInt theId, const std::string &theValue)
Set name for the component by its order number.
virtual void SetUnitName (TInt theId, const std::string &theValue)
Set unit for the component by its order number.
TTFieldInfo (const PMeshInfo &theMeshInfo, const PFieldInfo &theInfo)
TTFieldInfo (const PMeshInfo &theMeshInfo, TInt theNbComp, ETypeChamp theType, const std::string &theValue, EBooleen theIsLocal, TInt theNbRef)
Public Member Functions inherited from MED::TFieldInfo
EBooleen GetIsLocal () const
Let known is the MED FIELD is local or not.
const PMeshInfo & GetMeshInfo () const
Get a reference to corresponding MED Mesh.
TInt GetNbComp () const
Get number of components for the MED FIELD.
TInt GetNbRef () const
Let known number of references for the MED FIELD.
ETypeChamp GetType () const
Let known what type of the MED FIELD is used.
Public Member Functions inherited from MED::TBase
virtual ~TBase ()
Public Member Functions inherited from MED::TTNameInfo< eVersion >
virtual std::string GetName () const
Gets its name.
virtual void SetName (const std::string &theValue)
Set a new name.
virtual void SetName (const TString &theValue)
Set a new name.
TTNameInfo (const std::string &theValue)
Additional Inherited Members
Public Attributes inherited from MED::TFieldInfo
TString myCompNames
Contains names for each of MED Field components.
EBooleen myIsLocal
Defines if the MED Field is local.
PMeshInfo myMeshInfo
A reference to correspondig MED Mesh.
TInt myNbComp
Defines number of components stored in the field.
TInt myNbRef
Defines number of refereces of the field.
ETypeChamp myType
Defines type of the MED Field.
TString myUnitNames
Contains units for each of MED Field components.
Public Attributes inherited from MED::TNameInfo
TString myName
Keeps its name.
Member Typedef Documentation
TNameInfoBase
template<EVersion eVersion> typedef TTNameInfo<eVersion> MED::TTFieldInfo< eVersion >::TNameInfoBase
Constructor & Destructor Documentation
TTFieldInfo() [1/2]
template<EVersion eVersion> MED::TTFieldInfo< eVersion >::TTFieldInfo (const PMeshInfo & theMeshInfo, const PFieldInfo & theInfo)
References MED::TFieldInfo::myCompNames, MED::TFieldInfo::myIsLocal, MED::TFieldInfo::myMeshInfo, MED::TFieldInfo::myNbComp, MED::TFieldInfo::myNbRef, MED::TFieldInfo::myType, MED::TFieldInfo::myUnitNames, MED::TTFieldInfo< eVersion >::SetCompName(), and MED::TTFieldInfo< eVersion >::SetUnitName().
TTFieldInfo() [2/2]
template<EVersion eVersion> MED::TTFieldInfo< eVersion >::TTFieldInfo (const PMeshInfo & theMeshInfo, TInt theNbComp, ETypeChamp theType, const std::string & theValue, EBooleen theIsLocal, TInt theNbRef)
References MED::TFieldInfo::myCompNames, MED::TFieldInfo::myIsLocal, MED::TFieldInfo::myMeshInfo, MED::TFieldInfo::myNbComp, MED::TFieldInfo::myNbRef, MED::TFieldInfo::myType, and MED::TFieldInfo::myUnitNames.
Member Function Documentation
GetCompName()
template<EVersion eVersion> virtual std::string MED::TTFieldInfo< eVersion >::GetCompName (TInt theId) const virtual
Get name of the component by its order number.
Implements MED::TFieldInfo.
References MED::GetString(), and MED::TFieldInfo::myCompNames.
GetUnitName()
template<EVersion eVersion> virtual std::string MED::TTFieldInfo< eVersion >::GetUnitName (TInt theId) const virtual
Get unit of the component by its order number.
Implements MED::TFieldInfo.
References MED::GetString(), and MED::TFieldInfo::myUnitNames.
SetCompName()
template<EVersion eVersion> virtual void MED::TTFieldInfo< eVersion >::SetCompName (TInt theId, const std::string & theValue) virtual
Set name for the component by its order number.
Implements MED::TFieldInfo.
References MED::TFieldInfo::myCompNames, and MED::SetString().
Referenced by MED::TTFieldInfo< eVersion >::TTFieldInfo().
SetUnitName()
template<EVersion eVersion> virtual void MED::TTFieldInfo< eVersion >::SetUnitName (TInt theId, const std::string & theValue) virtual
Set unit for the component by its order number.
Implements MED::TFieldInfo.
References MED::TFieldInfo::myUnitNames, and MED::SetString().
Referenced by MED::TTFieldInfo< eVersion >::TTFieldInfo().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/MED_TStructures.hxx