FreeCAD: e57::IntegerNodeImpl Class Reference
e57::IntegerNodeImpl Class Reference
#include <IntegerNodeImpl.h>
Public Member Functions
void checkLeavesInSet (const StringSet &pathNames, NodeImplSharedPtr origin) override
IntegerNodeImpl (ImageFileImplWeakPtr destImageFile, int64_t value=0, int64_t minimum=0, int64_t maximum=0)
bool isDefined (const ustring &pathName) override
bool isTypeEquivalent (NodeImplSharedPtr ni) override
int64_t maximum ()
int64_t minimum ()
NodeType type () const override
int64_t value ()
void writeXml (ImageFileImplSharedPtr imf, CheckedFile &cf, int indent, const char *forcedFieldName=nullptr) override
~IntegerNodeImpl () override=default
Public Member Functions inherited from e57::NodeImpl
void checkBuffers (const std::vector< SourceDestBuffer > &sdbufs, bool allowMissing)
void checkImageFileOpen (const char *srcFileName, int srcLineNumber, const char *srcFunctionName) const
virtual void checkLeavesInSet (const StringSet &pathNames, NodeImplSharedPtr origin)=0
ImageFileImplSharedPtr destImageFile ()
ustring elementName () const
bool findTerminalPosition (const NodeImplSharedPtr &target, uint64_t &countFromLeft)
virtual NodeImplSharedPtr get (const ustring &pathName)
ustring imageFileName () const
bool isAttached () const
virtual bool isDefined (const ustring &pathName)=0
bool isRoot () const
bool isTypeConstrained ()
virtual bool isTypeEquivalent (NodeImplSharedPtr ni)=0
NodeImplSharedPtr parent ()
ustring pathName () const
ustring relativePathName (const NodeImplSharedPtr &origin, ustring childPathName=ustring()) const
virtual void set (const StringList &fields, unsigned level, NodeImplSharedPtr ni, bool autoPathCreate=false)
virtual void set (const ustring &pathName, NodeImplSharedPtr ni, bool autoPathCreate=false)
virtual void setAttachedRecursive ()
void setParent (NodeImplSharedPtr parent, const ustring &elementName)
virtual NodeType type () const =0
virtual void writeXml (ImageFileImplSharedPtr imf, CheckedFile &cf, int indent, const char *forcedFieldName=nullptr)=0
virtual ~NodeImpl ()=default
Additional Inherited Members
Protected Member Functions inherited from e57::NodeImpl
NodeImplSharedPtr getRoot ()
virtual NodeImplSharedPtr lookup (const ustring &)
NodeImpl (ImageFileImplWeakPtr destImageFile)
NodeImpl & operator= (NodeImpl &n)
Protected Attributes inherited from e57::NodeImpl
ImageFileImplWeakPtr destImageFile_
ustring elementName_
bool isAttached_
NodeImplWeakPtr parent_
Constructor & Destructor Documentation
IntegerNodeImpl()
e57::IntegerNodeImpl::IntegerNodeImpl (ImageFileImplWeakPtr destImageFile, int64_t value = 0, int64_t minimum = 0, int64_t maximum = 0)
Enforce the given bounds
References e57::E57_ERROR_VALUE_OUT_OF_BOUNDS, maximum(), minimum(), e57::NodeImpl::pathName(), and e57::toString().
~IntegerNodeImpl()
e57::IntegerNodeImpl::~IntegerNodeImpl () override default
Member Function Documentation
checkLeavesInSet()
void e57::IntegerNodeImpl::checkLeavesInSet (const StringSet & pathNames, NodeImplSharedPtr origin) override virtual
We are a leaf node, so verify that we are listed in set.
Implements e57::NodeImpl.
References e57::E57_ERROR_NO_BUFFER_FOR_ELEMENT, e57::NodeImpl::pathName(), and e57::NodeImpl::relativePathName().
isDefined()
bool e57::IntegerNodeImpl::isDefined (const ustring & pathName) override virtual
We have no sub-structure, so if path not empty return false
Implements e57::NodeImpl.
References e57::NodeImpl::pathName().
isTypeEquivalent()
bool e57::IntegerNodeImpl::isTypeEquivalent (NodeImplSharedPtr ni) override virtual
Same node type?
Downcast to shared_ptr<IntegerNodeImpl>
minimum must match
maximum must match
ignore value_, doesn't have to match
Types match
Implements e57::NodeImpl.
References e57::E57_INTEGER.
maximum()
int64_t e57::IntegerNodeImpl::maximum (void)
References e57::NodeImpl::checkImageFileOpen().
Referenced by IntegerNodeImpl().
minimum()
int64_t e57::IntegerNodeImpl::minimum (void)
References e57::NodeImpl::checkImageFileOpen().
Referenced by IntegerNodeImpl().
type()
NodeType e57::IntegerNodeImpl::type () const override virtual
Implements e57::NodeImpl.
References e57::E57_INTEGER.
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
value()
int64_t e57::IntegerNodeImpl::value ()
References e57::NodeImpl::checkImageFileOpen().
Referenced by PathScripts.PathProperty.Property::displayString(), PathScripts.PathProperty.PropertyQuantity::displayString(), PathScripts.PathSetupSheetOpPrototype.Property::displayString(), PathScripts.PathSetupSheetOpPrototype.PropertyQuantity::displayString(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), PathScripts.PathProperty.Property::getValue(), PathScripts.PathSetupSheetOpPrototype.Property::getValue(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), PathScripts.PathProperty.Property::setValue(), and PathScripts.PathSetupSheetOpPrototype.Property::setValue().
writeXml()
void e57::IntegerNodeImpl::writeXml (ImageFileImplSharedPtr imf, CheckedFile & cf, int indent, const char * forcedFieldName = nullptr) override virtual
Don't need to write if are default values
Write value as child text, unless it is the default value
Implements e57::NodeImpl.
References e57::NodeImpl::elementName_, and e57::space().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/libE57Format/src/IntegerNodeImpl.h
FreeCAD/src/3rdParty/libE57Format/src/IntegerNodeImpl.cpp