FreeCAD: zipios::DirectoryCollection Class Reference
zipios::DirectoryCollection Class Reference
DirectoryCollection is a FileCollection that obtains its entries from a directory.
#include <dircoll.h>
Public Member Functions
virtual FileCollection * clone () const
Create a heap allocated clone of the object this method is called for.
virtual void close ()
Closes the FileCollection.
DirectoryCollection ()
Default Constructor.
DirectoryCollection (const string &path, bool recursive=true, bool load_now=false)
Constructor.
virtual ConstEntries entries () const
Returns a vector of const pointers to the entries in the FileCollection.
virtual ConstEntryPointer getEntry (const string &name, MatchPath matchpath=MATCH) const
Returns a ConstEntryPointer to a FileEntry object for the entry with the specified name.
virtual istream * getInputStream (const ConstEntryPointer &entry)
Returns a pointer to an opened istream for the specified FileEntry.
virtual istream * getInputStream (const string &entry_name, MatchPath matchpath=MATCH)
Returns a pointer to an opened istream for the specified entry name.
virtual int size () const
Returns the number of entries in the FileCollection.
virtual ~DirectoryCollection ()
Destructor.
Public Member Functions inherited from zipios::FileCollection
FileCollection ()
FileCollection constructor.
FileCollection (const FileCollection &src)
Copy constructor.
virtual string getName () const
Returns the name of the FileCollection.
bool isValid () const
The member function returns true if the collection is valid.
const FileCollection & operator= (const FileCollection &src)
Copy assignment operator.
virtual ~FileCollection ()
FileCollection destructor.
Protected Member Functions
void load (bool recursive, const FilePath &subdir=FilePath())
void loadEntries () const
Additional Inherited Members
Public Types inherited from zipios::FileCollection
enum MatchPath { IGN, MATCH }
Detailed Description
DirectoryCollection is a FileCollection that obtains its entries from a directory.
Constructor & Destructor Documentation
DirectoryCollection() [1/2]
zipios::DirectoryCollection::DirectoryCollection () explicit
Default Constructor.
Referenced by clone().
DirectoryCollection() [2/2]
DirectoryCollection::DirectoryCollection (const string & path, bool recursive = true, bool load_now = false) explicit
Constructor.
Parameters
path A directory path name. If the name is not a valid directory the created DirectoryCollection will be invalid.
recursive
load_now Load directory into memory now. Otherwise it will be done when it is first needed.
References loadEntries().
~DirectoryCollection()
DirectoryCollection::~DirectoryCollection () virtual
Destructor.
Member Function Documentation
clone()
FileCollection * DirectoryCollection::clone () const virtual
Create a heap allocated clone of the object this method is called for.
The caller is responsible for deallocating the clone when he is done with it.
Returns
A heap allocated copy of the object this method is called for.
Implements zipios::FileCollection.
References DirectoryCollection().
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchComponent.Component::execute(), ArchCurtainWall.CurtainWall::execute(), ArchTruss.Truss::execute(), and Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated().
close()
void DirectoryCollection::close () virtual
Closes the FileCollection.
Implements zipios::FileCollection.
Referenced by femexamples.examplesgui.FemExamples::reject().
entries()
ConstEntries DirectoryCollection::entries () const virtual
Returns a vector of const pointers to the entries in the FileCollection.
Returns
a ConstEntries containing the entries of the FileCollection.
Exceptions
InvalidStateException Thrown if the collection is invalid.
Reimplemented from zipios::FileCollection.
References zipios::FileCollection::entries(), and loadEntries().
getEntry()
ConstEntryPointer DirectoryCollection::getEntry (const string & name, MatchPath matchpath = MATCH) const virtual
Returns a ConstEntryPointer to a FileEntry object for the entry with the specified name.
To ignore the path part of the filename in search of a match, specify FileCollection::IGNORE as the second argument.
Parameters
name A string containing the name of the entry to get.
matchpath Speficy MATCH, if the path should match as well, specify IGNORE, if the path should be ignored.
Returns
A ConstEntryPointer to the found entry. The returned pointer equals zero if no entry is found.
Exceptions
InvalidStateException Thrown if the collection is invalid.
Reimplemented from zipios::FileCollection.
References zipios::FileCollection::getEntry(), loadEntries(), and zipios::FileCollection::MATCH.
Referenced by getInputStream().
getInputStream() [1/2]
istream * DirectoryCollection::getInputStream (const ConstEntryPointer & entry) virtual
Returns a pointer to an opened istream for the specified FileEntry.
It is the callers responsibility to delete the stream when he is done with it. Returns 0, if there is no such FileEntry in the FileCollection.
Parameters
entry A ConstEntryPointer to the FileEntry to get an istream to.
Returns
an open istream for the specified entry. The istream is allocated on heap and it is the users responsibility to delete it when he is done with it.
Exceptions
InvalidStateException Thrown if the collection is invalid.
Implements zipios::FileCollection.
getInputStream() [2/2]
std::istream * DirectoryCollection::getInputStream (const string & entry_name, MatchPath matchpath = MATCH) virtual
Returns a pointer to an opened istream for the specified entry name.
It is the callers responsibility to delete the stream when he is done with it. Returns 0, if there is no entry with the specified name in the FileCollection.
Parameters
entry_name
matchpath Speficy MATCH, if the path should match as well, specify IGNORE, if the path should be ignored.
Returns
an open istream for the specified entry. The istream is allocated on heap and it is the users responsibility to delete it when he is done with it.
Exceptions
InvalidStateException Thrown if the collection is invalid.
Implements zipios::FileCollection.
References getEntry(), loadEntries(), and zipios::FileCollection::MATCH.
load()
void DirectoryCollection::load (bool recursive, const FilePath & subdir = FilePath()) protected
References zipios::BasicEntry::setSize().
Referenced by loadEntries().
loadEntries()
void DirectoryCollection::loadEntries () const protected
References load().
Referenced by DirectoryCollection(), entries(), getEntry(), getInputStream(), and size().
size()
int DirectoryCollection::size () const virtual
Returns the number of entries in the FileCollection.
Returns
the number of entries in the FileCollection.
Exceptions
InvalidStateException Thrown if the collection is invalid.
Reimplemented from zipios::FileCollection.
References loadEntries().
Referenced by PathScripts.PostUtils.GCodeEditorDialog::done().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/zipios++/dircoll.h
Sources/FreeCAD/src/zipios++/dircoll.cpp