FreeCAD: FemGui::DataMarker Class Reference
FemGui::DataMarker Class Reference
#include <TaskPostBoxes.h>
Signals
void PointsChanged (double x, double y, double z)
Public Member Functions
void addPoint (const SbVec3f &)
int countPoints () const
DataMarker (Gui::View3DInventorViewer *view, std::string ObjName)
~DataMarker ()
Protected Member Functions
void customEvent (QEvent *e)
Constructor & Destructor Documentation
DataMarker()
DataMarker::DataMarker (Gui::View3DInventorViewer * view, std::string ObjName)
References Gui::View3DInventorViewer::addViewProvider().
~DataMarker()
DataMarker::~DataMarker ()
References Gui::View3DInventorViewer::removeViewProvider().
Member Function Documentation
addPoint()
void DataMarker::addPoint (const SbVec3f & pt)
References countPoints(), FemGui::ViewProviderDataMarker::pCoords, and FemGui::ViewProviderDataMarker::pMarker.
Referenced by FemGui::TaskPostDataAtPoint::pointCallback().
countPoints()
int DataMarker::countPoints () const
References FemGui::ViewProviderDataMarker::pCoords.
Referenced by addPoint(), and FemGui::TaskPostDataAtPoint::pointCallback().
customEvent()
void DataMarker::customEvent (QEvent * e) protected
References Gui::Command::Doc, FemGui::ViewProviderDataMarker::pCoords, and PointsChanged().
PointsChanged
void FemGui::DataMarker::PointsChanged (double x, double y, double z) signal
Referenced by customEvent().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Fem/Gui/TaskPostBoxes.h
Sources/FreeCAD/src/Mod/Fem/Gui/TaskPostBoxes.cpp