FreeCAD: Sketcher::ExternalGeometryFacadePy Class Reference
Sketcher::ExternalGeometryFacadePy Class Reference
The python export class for ExternalGeometryFacade.
#include <ExternalGeometryFacadePy.h>
Public Types
typedef ExternalGeometryFacade * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
ExternalGeometryFacadePy (ExternalGeometryFacade *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of ExternalGeometryFacadePy.
static PyMethodDef Methods []
Methods structure of ExternalGeometryFacadePy.
static PyTypeObject Type
Type structure of ExternalGeometryFacadePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~ExternalGeometryFacadePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * testFlag (PyObject *args)
implementer for the testFlag() method
PyObject * setFlag (PyObject *args)
implementer for the setFlag() method
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * hasExtensionOfType (PyObject *args)
implementer for the hasExtensionOfType() method
PyObject * hasExtensionOfName (PyObject *args)
implementer for the hasExtensionOfName() method
PyObject * getExtensionOfType (PyObject *args)
implementer for the getExtensionOfType() method
PyObject * getExtensionOfName (PyObject *args)
implementer for the getExtensionOfName() method
PyObject * setExtension (PyObject *args)
implementer for the setExtension() method
PyObject * deleteExtensionOfType (PyObject *args)
implementer for the deleteExtensionOfType() method
PyObject * deleteExtensionOfName (PyObject *args)
implementer for the deleteExtensionOfName() method
PyObject * getExtensions (PyObject *args)
implementer for the getExtensions() method
static PyObject * staticCallback_testFlag (PyObject *self, PyObject *args)
callback for the testFlag() method
static PyObject * staticCallback_setFlag (PyObject *self, PyObject *args)
callback for the setFlag() method
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_hasExtensionOfType (PyObject *self, PyObject *args)
callback for the hasExtensionOfType() method
static PyObject * staticCallback_hasExtensionOfName (PyObject *self, PyObject *args)
callback for the hasExtensionOfName() method
static PyObject * staticCallback_getExtensionOfType (PyObject *self, PyObject *args)
callback for the getExtensionOfType() method
static PyObject * staticCallback_getExtensionOfName (PyObject *self, PyObject *args)
callback for the getExtensionOfName() method
static PyObject * staticCallback_setExtension (PyObject *self, PyObject *args)
callback for the setExtension() method
static PyObject * staticCallback_deleteExtensionOfType (PyObject *self, PyObject *args)
callback for the deleteExtensionOfType() method
static PyObject * staticCallback_deleteExtensionOfName (PyObject *self, PyObject *args)
callback for the deleteExtensionOfName() method
static PyObject * staticCallback_getExtensions (PyObject *self, PyObject *args)
callback for the getExtensions() method
callbacks and implementers for the python object attributes
Py::String getRef (void) const
getter for the Ref attribute
void setRef (Py::String arg)
setter for the Ref attribute
Py::Long getId (void) const
getter for the Id attribute
void setId (Py::Long arg)
setter for the Id attribute
Py::Boolean getConstruction (void) const
getter for the Construction attribute
void setConstruction (Py::Boolean arg)
setter for the Construction attribute
Py::String getInternalType (void) const
getter for the InternalType attribute
void setInternalType (Py::String arg)
setter for the InternalType attribute
Py::Boolean getBlocked (void) const
getter for the Blocked attribute
void setBlocked (Py::Boolean arg)
setter for the Blocked attribute
Py::String getTag (void) const
getter for the Tag attribute
Py::Object getGeometry (void) const
getter for the Geometry attribute
void setGeometry (Py::Object arg)
setter for the Geometry attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ExternalGeometryFacade * getExternalGeometryFacadePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getRef (PyObject *self, void *closure)
getter callback for the Ref attribute
static int staticCallback_setRef (PyObject *self, PyObject *value, void *closure)
setter callback for the Ref attribute
static PyObject * staticCallback_getId (PyObject *self, void *closure)
getter callback for the Id attribute
static int staticCallback_setId (PyObject *self, PyObject *value, void *closure)
setter callback for the Id attribute
static PyObject * staticCallback_getConstruction (PyObject *self, void *closure)
getter callback for the Construction attribute
static int staticCallback_setConstruction (PyObject *self, PyObject *value, void *closure)
setter callback for the Construction attribute
static PyObject * staticCallback_getInternalType (PyObject *self, void *closure)
getter callback for the InternalType attribute
static int staticCallback_setInternalType (PyObject *self, PyObject *value, void *closure)
setter callback for the InternalType attribute
static PyObject * staticCallback_getBlocked (PyObject *self, void *closure)
getter callback for the Blocked attribute
static int staticCallback_setBlocked (PyObject *self, PyObject *value, void *closure)
setter callback for the Blocked attribute
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
static PyObject * staticCallback_getGeometry (PyObject *self, void *closure)
getter callback for the Geometry attribute
static int staticCallback_setGeometry (PyObject *self, PyObject *value, void *closure)
setter callback for the Geometry attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for ExternalGeometryFacade.
Member Typedef Documentation
PointerType
typedef ExternalGeometryFacade* Sketcher::ExternalGeometryFacadePy::PointerType
Constructor & Destructor Documentation
~ExternalGeometryFacadePy()
ExternalGeometryFacadePy::~ExternalGeometryFacadePy () protected
ExternalGeometryFacadePy()
ExternalGeometryFacadePy::ExternalGeometryFacadePy (ExternalGeometryFacade * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
deleteExtensionOfName()
PyObject * ExternalGeometryFacadePy::deleteExtensionOfName (PyObject * args)
implementer for the deleteExtensionOfName() method
References Sketcher::ExternalGeometryFacade::deleteExtension(), getExternalGeometryFacadePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_deleteExtensionOfName().
deleteExtensionOfType()
PyObject * ExternalGeometryFacadePy::deleteExtensionOfType (PyObject * args)
implementer for the deleteExtensionOfType() method
References Base::Type::badType(), Sketcher::ExternalGeometryFacade::deleteExtension(), Base::Type::fromName(), getExternalGeometryFacadePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_deleteExtensionOfType().
getBlocked()
Py::Boolean ExternalGeometryFacadePy::getBlocked (void) const
getter for the Blocked attribute
References getExternalGeometryFacadePtr().
Referenced by staticCallback_getBlocked().
getConstruction()
Py::Boolean ExternalGeometryFacadePy::getConstruction (void) const
getter for the Construction attribute
References getExternalGeometryFacadePtr().
Referenced by staticCallback_getConstruction().
getCustomAttributes()
PyObject * ExternalGeometryFacadePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getExtensionOfName()
PyObject * ExternalGeometryFacadePy::getExtensionOfName (PyObject * args)
implementer for the getExtensionOfName() method
References getExternalGeometryFacadePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getExtensionOfName().
getExtensionOfType()
PyObject * ExternalGeometryFacadePy::getExtensionOfType (PyObject * args)
implementer for the getExtensionOfType() method
References Base::Type::badType(), Base::Type::fromName(), getExternalGeometryFacadePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getExtensionOfType().
getExtensions()
PyObject * ExternalGeometryFacadePy::getExtensions (PyObject * args)
implementer for the getExtensions() method
References Sketcher::ExternalGeometryFacade::getExtensions(), getExternalGeometryFacadePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getExtensions().
getExternalGeometryFacadePtr()
ExternalGeometryFacade * ExternalGeometryFacadePy::getExternalGeometryFacadePtr (void) const
getter for the object handled by this class
Referenced by deleteExtensionOfName(), deleteExtensionOfType(), getBlocked(), getConstruction(), getExtensionOfName(), getExtensionOfType(), getExtensions(), getGeometry(), getId(), getInternalType(), getRef(), getTag(), hasExtensionOfName(), hasExtensionOfType(), mirror(), PyInit(), representation(), rotate(), scale(), setBlocked(), setConstruction(), setExtension(), setFlag(), setGeometry(), setId(), setInternalType(), setRef(), testFlag(), transform(), and translate().
getGeometry()
Py::Object ExternalGeometryFacadePy::getGeometry (void) const
getter for the Geometry attribute
References draftmake.make_clone::clone, getExternalGeometryFacadePtr(), and Base::BaseClass::getPyObject().
Referenced by staticCallback_getGeometry().
getId()
Py::Long ExternalGeometryFacadePy::getId (void) const
getter for the Id attribute
References getExternalGeometryFacadePtr().
Referenced by staticCallback_getId().
getInternalType()
Py::String ExternalGeometryFacadePy::getInternalType (void) const
getter for the InternalType attribute
References getExternalGeometryFacadePtr(), Sketcher::ExternalGeometryFacade::getInternalType(), Sketcher::SketchGeometryExtension::internaltype2str, and Sketcher::InternalType::NumInternalGeometryType.
Referenced by staticCallback_getInternalType().
getRef()
Py::String ExternalGeometryFacadePy::getRef (void) const
getter for the Ref attribute
References getExternalGeometryFacadePtr().
Referenced by staticCallback_getRef().
getTag()
Py::String ExternalGeometryFacadePy::getTag (void) const
getter for the Tag attribute
References getExternalGeometryFacadePtr().
Referenced by staticCallback_getTag().
GetType()
virtual PyTypeObject* Sketcher::ExternalGeometryFacadePy::GetType (void) virtual
Reimplemented from Base::BaseClassPy.
hasExtensionOfName()
PyObject * ExternalGeometryFacadePy::hasExtensionOfName (PyObject * args)
implementer for the hasExtensionOfName() method
References getExternalGeometryFacadePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_hasExtensionOfName().
hasExtensionOfType()
PyObject * ExternalGeometryFacadePy::hasExtensionOfType (PyObject * args)
implementer for the hasExtensionOfType() method
References Base::Type::badType(), Base::Type::fromName(), getExternalGeometryFacadePtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_hasExtensionOfType().
mirror()
PyObject * ExternalGeometryFacadePy::mirror (PyObject * args)
implementer for the mirror() method
References getExternalGeometryFacadePtr(), Sketcher::ExternalGeometryFacade::mirror(), Part::PartExceptionOCCError, Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_mirror().
PyInit()
int ExternalGeometryFacadePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::BaseClassPy.
References Part::Geometry::clone(), getExternalGeometryFacadePtr(), Sketcher::ExternalGeometryFacade::setGeometry(), and Part::GeometryPy::Type.
PyMake()
PyObject * ExternalGeometryFacadePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References ExternalGeometryFacadePy().
representation()
std::string ExternalGeometryFacadePy::representation (void) const
References getExternalGeometryFacadePtr(), and Sketcher::ExternalGeometryFacade::getId().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
rotate()
PyObject * ExternalGeometryFacadePy::rotate (PyObject * args)
implementer for the rotate() method
References getExternalGeometryFacadePtr(), Sketcher::ExternalGeometryFacade::rotate(), and Base::PlacementPy::Type.
Referenced by staticCallback_rotate().
scale()
PyObject * ExternalGeometryFacadePy::scale (PyObject * args)
implementer for the scale() method
References getExternalGeometryFacadePtr(), Part::PartExceptionOCCError, Sketcher::ExternalGeometryFacade::scale(), Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_scale().
setBlocked()
void ExternalGeometryFacadePy::setBlocked (Py::Boolean arg)
setter for the Blocked attribute
References getExternalGeometryFacadePtr(), and Sketcher::ExternalGeometryFacade::setBlocked().
Referenced by staticCallback_setBlocked().
setConstruction()
void ExternalGeometryFacadePy::setConstruction (Py::Boolean arg)
setter for the Construction attribute
References Base::Persistence::getClassTypeId(), getExternalGeometryFacadePtr(), Base::BaseClassPy::getTypeId(), and Sketcher::ExternalGeometryFacade::setConstruction().
Referenced by staticCallback_setConstruction().
setCustomAttributes()
int ExternalGeometryFacadePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setExtension()
PyObject * ExternalGeometryFacadePy::setExtension (PyObject * args)
implementer for the setExtension() method
References getExternalGeometryFacadePtr(), draftfunctions.move::move(), Part::PartExceptionOCCError, Sketcher::ExternalGeometryFacade::setExtension(), and Part::GeometryExtensionPy::Type.
Referenced by staticCallback_setExtension().
setFlag()
PyObject * ExternalGeometryFacadePy::setFlag (PyObject * args)
implementer for the setFlag() method
References Sketcher::end, Sketcher::ExternalGeometryExtension::flag2str, getExternalGeometryFacadePtr(), and Sketcher::ExternalGeometryFacade::setFlag().
Referenced by staticCallback_setFlag().
setGeometry()
void ExternalGeometryFacadePy::setGeometry (Py::Object arg)
setter for the Geometry attribute
References Part::Geometry::clone(), getExternalGeometryFacadePtr(), Part::GeometryPy::getGeometryPtr(), Sketcher::ExternalGeometryFacade::setGeometry(), and Part::GeometryPy::Type.
Referenced by staticCallback_setGeometry().
setId()
void ExternalGeometryFacadePy::setId (Py::Long arg)
setter for the Id attribute
References getExternalGeometryFacadePtr(), and Sketcher::ExternalGeometryFacade::setId().
Referenced by staticCallback_setId().
setInternalType()
void ExternalGeometryFacadePy::setInternalType (Py::String arg)
setter for the InternalType attribute
References getExternalGeometryFacadePtr(), Sketcher::SketchGeometryExtension::getInternalTypeFromName(), and Sketcher::ExternalGeometryFacade::setInternalType().
Referenced by staticCallback_setInternalType().
setRef()
void ExternalGeometryFacadePy::setRef (Py::String arg)
setter for the Ref attribute
References getExternalGeometryFacadePtr(), and Sketcher::ExternalGeometryFacade::setRef().
Referenced by staticCallback_setRef().
staticCallback_deleteExtensionOfName()
PyObject * ExternalGeometryFacadePy::staticCallback_deleteExtensionOfName (PyObject * self, PyObject * args) static
callback for the deleteExtensionOfName() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, deleteExtensionOfName(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_deleteExtensionOfType()
PyObject * ExternalGeometryFacadePy::staticCallback_deleteExtensionOfType (PyObject * self, PyObject * args) static
callback for the deleteExtensionOfType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, deleteExtensionOfType(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getBlocked()
PyObject * ExternalGeometryFacadePy::staticCallback_getBlocked (PyObject * self, void * closure) static
getter callback for the Blocked attribute
References Base::BaseExceptionFreeCADError, getBlocked(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getConstruction()
PyObject * ExternalGeometryFacadePy::staticCallback_getConstruction (PyObject * self, void * closure) static
getter callback for the Construction attribute
References Base::BaseExceptionFreeCADError, getConstruction(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getExtensionOfName()
PyObject * ExternalGeometryFacadePy::staticCallback_getExtensionOfName (PyObject * self, PyObject * args) static
callback for the getExtensionOfName() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getExtensionOfName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getExtensionOfType()
PyObject * ExternalGeometryFacadePy::staticCallback_getExtensionOfType (PyObject * self, PyObject * args) static
callback for the getExtensionOfType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getExtensionOfType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getExtensions()
PyObject * ExternalGeometryFacadePy::staticCallback_getExtensions (PyObject * self, PyObject * args) static
callback for the getExtensions() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getExtensions(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getGeometry()
PyObject * ExternalGeometryFacadePy::staticCallback_getGeometry (PyObject * self, void * closure) static
getter callback for the Geometry attribute
References Base::BaseExceptionFreeCADError, getGeometry(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getId()
PyObject * ExternalGeometryFacadePy::staticCallback_getId (PyObject * self, void * closure) static
getter callback for the Id attribute
References Base::BaseExceptionFreeCADError, getId(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getInternalType()
PyObject * ExternalGeometryFacadePy::staticCallback_getInternalType (PyObject * self, void * closure) static
getter callback for the InternalType attribute
References Base::BaseExceptionFreeCADError, getInternalType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRef()
PyObject * ExternalGeometryFacadePy::staticCallback_getRef (PyObject * self, void * closure) static
getter callback for the Ref attribute
References Base::BaseExceptionFreeCADError, getRef(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTag()
PyObject * ExternalGeometryFacadePy::staticCallback_getTag (PyObject * self, void * closure) static
getter callback for the Tag attribute
References Base::BaseExceptionFreeCADError, getTag(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_hasExtensionOfName()
PyObject * ExternalGeometryFacadePy::staticCallback_hasExtensionOfName (PyObject * self, PyObject * args) static
callback for the hasExtensionOfName() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hasExtensionOfName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_hasExtensionOfType()
PyObject * ExternalGeometryFacadePy::staticCallback_hasExtensionOfType (PyObject * self, PyObject * args) static
callback for the hasExtensionOfType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hasExtensionOfType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_mirror()
PyObject * ExternalGeometryFacadePy::staticCallback_mirror (PyObject * self, PyObject * args) static
callback for the mirror() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), mirror(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_rotate()
PyObject * ExternalGeometryFacadePy::staticCallback_rotate (PyObject * self, PyObject * args) static
callback for the rotate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), rotate(), and Base::PyObjectBase::startNotify().
staticCallback_scale()
PyObject * ExternalGeometryFacadePy::staticCallback_scale (PyObject * self, PyObject * args) static
callback for the scale() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), scale(), and Base::PyObjectBase::startNotify().
staticCallback_setBlocked()
int ExternalGeometryFacadePy::staticCallback_setBlocked (PyObject * self, PyObject * value, void * closure) static
setter callback for the Blocked attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setBlocked().
staticCallback_setConstruction()
int ExternalGeometryFacadePy::staticCallback_setConstruction (PyObject * self, PyObject * value, void * closure) static
setter callback for the Construction attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setConstruction().
staticCallback_setExtension()
PyObject * ExternalGeometryFacadePy::staticCallback_setExtension (PyObject * self, PyObject * args) static
callback for the setExtension() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setExtension(), and Base::PyObjectBase::startNotify().
staticCallback_setFlag()
PyObject * ExternalGeometryFacadePy::staticCallback_setFlag (PyObject * self, PyObject * args) static
callback for the setFlag() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setFlag(), and Base::PyObjectBase::startNotify().
staticCallback_setGeometry()
int ExternalGeometryFacadePy::staticCallback_setGeometry (PyObject * self, PyObject * value, void * closure) static
setter callback for the Geometry attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setGeometry().
staticCallback_setId()
int ExternalGeometryFacadePy::staticCallback_setId (PyObject * self, PyObject * value, void * closure) static
setter callback for the Id attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setId().
staticCallback_setInternalType()
int ExternalGeometryFacadePy::staticCallback_setInternalType (PyObject * self, PyObject * value, void * closure) static
setter callback for the InternalType attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setInternalType().
staticCallback_setRef()
int ExternalGeometryFacadePy::staticCallback_setRef (PyObject * self, PyObject * value, void * closure) static
setter callback for the Ref attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setRef().
staticCallback_setTag()
int ExternalGeometryFacadePy::staticCallback_setTag (PyObject * self, PyObject * value, void * closure) static
setter callback for the Tag attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_testFlag()
PyObject * ExternalGeometryFacadePy::staticCallback_testFlag (PyObject * self, PyObject * args) static
callback for the testFlag() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and testFlag().
staticCallback_transform()
PyObject * ExternalGeometryFacadePy::staticCallback_transform (PyObject * self, PyObject * args) static
callback for the transform() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and transform().
staticCallback_translate()
PyObject * ExternalGeometryFacadePy::staticCallback_translate (PyObject * self, PyObject * args) static
callback for the translate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and translate().
testFlag()
PyObject * ExternalGeometryFacadePy::testFlag (PyObject * args)
implementer for the testFlag() method
References Sketcher::end, Sketcher::ExternalGeometryExtension::flag2str, and getExternalGeometryFacadePtr().
Referenced by staticCallback_testFlag().
transform()
PyObject * ExternalGeometryFacadePy::transform (PyObject * args)
implementer for the transform() method
References getExternalGeometryFacadePtr(), Sketcher::ExternalGeometryFacade::transform(), and Base::MatrixPy::Type.
Referenced by staticCallback_transform().
translate()
PyObject * ExternalGeometryFacadePy::translate (PyObject * args)
implementer for the translate() method
References getExternalGeometryFacadePtr(), Part::PartExceptionOCCError, Sketcher::ExternalGeometryFacade::translate(), Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_translate().
Member Data Documentation
GetterSetter
PyGetSetDef ExternalGeometryFacadePy::GetterSetter static
Attribute structure of ExternalGeometryFacadePy.
Methods
PyMethodDef ExternalGeometryFacadePy::Methods static
Methods structure of ExternalGeometryFacadePy.
Type
PyTypeObject ExternalGeometryFacadePy::Type static
Type structure of ExternalGeometryFacadePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Sketcher/App/ExternalGeometryFacadePy.h
Sources/FreeCAD/src/Mod/Sketcher/App/ExternalGeometryFacadePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Sketcher/App/ExternalGeometryFacadePy.cpp