FreeCAD: Part::Geometry Class Reference
Part::Geometry Class Reference abstract
#include <Geometry.h>
Public Member Functions
Geometry * clone (void) const
returns a cloned object.
virtual Geometry * copy (void) const =0
returns a copy of this object having a new randomly generated tag.
void deleteExtension (Base::Type type)
void deleteExtension (std::string name)
std::weak_ptr< GeometryExtension > getExtension (Base::Type type)
std::weak_ptr< const GeometryExtension > getExtension (Base::Type type) const
std::weak_ptr< GeometryExtension > getExtension (std::string name)
std::weak_ptr< const GeometryExtension > getExtension (std::string name) const
std::vector< std::weak_ptr< const GeometryExtension > > getExtensions () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
boost::uuids::uuid getTag () const
returns the tag of the geometry object
virtual const Handle (Geom_Geometry) &handle() const =0
bool hasExtension (Base::Type type) const
bool hasExtension (std::string name) const
void mirror (const Base::Vector3d &point)
void mirror (const Base::Vector3d &point, const Base::Vector3d &dir)
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
void rotate (const Base::Placement &plm)
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
void scale (const Base::Vector3d &vec, double scale)
void setExtension (std::unique_ptr< GeometryExtension > &&geo)
virtual TopoDS_Shape toShape () const =0
void transform (const Base::Matrix4D &mat)
void translate (const Base::Vector3d &vec)
virtual ~Geometry ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Member Functions
void assignTag (const Part::Geometry *)
copies the tag from the geometry passed as a parameter to this object
void copyNonTag (const Part::Geometry *)
void createNewTag ()
create a new tag for the geometry object
Geometry ()
Protected Attributes
std::vector< std::shared_ptr< GeometryExtension > > extensions
boost::uuids::uuid tag
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
~Geometry()
Geometry::~Geometry () virtual
Geometry()
Geometry::Geometry () protected
Member Function Documentation
assignTag()
void Geometry::assignTag (const Part::Geometry * geo) protected
copies the tag from the geometry passed as a parameter to this object
References Base::Persistence::getTypeId(), and tag.
clone()
Geometry * Geometry::clone (void) const
returns a cloned object.
A cloned object has the same tag (see getTag) as the original object. if you want a copy not having the same tag, you can use copy() instead. If you want a clone with another geometry handle, it is possible to clone an object and then assign another handle or to create an object via constructor and use assignTag to assign the tag of the other geometry. If you do not desire to have the same tag, then a copy can be performed by using a constructor (which will generate another tag) and then, if necessary (e.g. if the constructor did not take a handle as a parameter), set a new handle.
References copy(), and tag.
Referenced by ArchPanel.CommandPanelSheet::Activated(), Sketcher::Sketch::addArc(), Sketcher::Sketch::addArcOfEllipse(), Sketcher::Sketch::addArcOfHyperbola(), Sketcher::Sketch::addArcOfParabola(), Sketcher::Sketch::addCircle(), Sketcher::Sketch::addEllipse(), Sketcher::Sketch::addLineSegment(), Part::GeometryPy::clone(), Sketcher::ExternalGeometryFacade::clone(), Sketcher::GeometryFacade::clone(), Part::GeomBezierCurve::getPyObject(), Part::GeomBSplineCurve::getPyObject(), Part::GeomTrimmedCurve::getPyObject(), Part::GeomCircle::getPyObject(), Part::GeomArcOfCircle::getPyObject(), Part::GeomEllipse::getPyObject(), Part::GeomArcOfEllipse::getPyObject(), Part::GeomHyperbola::getPyObject(), Part::GeomArcOfHyperbola::getPyObject(), Part::GeomParabola::getPyObject(), Part::GeomArcOfParabola::getPyObject(), Part::GeomLine::getPyObject(), Part::GeomLineSegment::getPyObject(), Part::GeomOffsetCurve::getPyObject(), Part::GeomBezierSurface::getPyObject(), Part::GeomBSplineSurface::getPyObject(), Part::GeomCylinder::getPyObject(), Part::GeomCone::getPyObject(), Part::GeomSphere::getPyObject(), Part::GeomToroid::getPyObject(), Part::GeomPlane::getPyObject(), Part::GeomOffsetSurface::getPyObject(), Part::GeomPlateSurface::getPyObject(), Part::GeomTrimmedSurface::getPyObject(), Part::GeomSurfaceOfRevolution::getPyObject(), Part::GeomSurfaceOfExtrusion::getPyObject(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated(), Sketcher::SketchObject::modifyBSplineKnotMultiplicity(), Sketcher::ExternalGeometryFacadePy::PyInit(), Sketcher::GeometryFacadePy::PyInit(), Sketcher::ExternalGeometryFacadePy::setGeometry(), Sketcher::GeometryFacadePy::setGeometry(), and Part::PropertyGeometryList::setValue().
copy()
virtual Geometry* Part::Geometry::copy (void) const pure virtual
returns a copy of this object having a new randomly generated tag.
If you also want to copy the tag, you may use clone() instead. For creation of geometry with other handles, with or without the same tag, you may use the constructors and the sethandle functions. The tag of a geometry can be copied to another geometry using the assignTag function.
Implemented in Part::GeomArcOfConic, Part::GeomConic, Part::GeomSurfaceOfExtrusion, Part::GeomSurfaceOfRevolution, Part::GeomTrimmedSurface, Part::GeomPlateSurface, Part::GeomOffsetSurface, Part::GeomPlane, Part::GeomToroid, Part::GeomSphere, Part::GeomCone, Part::GeomCylinder, Part::GeomBSplineSurface, Part::GeomBezierSurface, Part::GeomOffsetCurve, Part::GeomLineSegment, Part::GeomLine, Part::GeomArcOfParabola, Part::GeomParabola, Part::GeomArcOfHyperbola, Part::GeomHyperbola, Part::GeomArcOfEllipse, Part::GeomEllipse, Part::GeomArcOfCircle, Part::GeomCircle, Part::GeomTrimmedCurve, Part::GeomBSplineCurve, Part::GeomBezierCurve, and Part::GeomPoint.
Referenced by Sketcher::SketchObject::addCopy(), Sketcher::SketchObject::addGeometry(), Sketcher::SketchObject::addSymmetric(), Sketcher::SketchObject::carbonCopy(), clone(), Part::GeometryPy::copy(), Sketcher::ExternalGeometryFacade::copy(), and Sketcher::GeometryFacade::copy().
copyNonTag()
void Geometry::copyNonTag (const Part::Geometry * src) protected
References extensions.
Referenced by Part::GeomPoint::copy(), Part::GeomCircle::copy(), Part::GeomEllipse::copy(), Part::GeomHyperbola::copy(), Part::GeomParabola::copy(), Part::GeomLine::copy(), Part::GeomOffsetCurve::copy(), and Part::GeomBezierSurface::copy().
createNewTag()
void Geometry::createNewTag () protected
create a new tag for the geometry object
References tag.
deleteExtension() [1/2]
void Geometry::deleteExtension (Base::Type type)
References extensions.
Referenced by Part::GeometryPy::deleteExtensionOfName(), and Part::GeometryPy::deleteExtensionOfType().
deleteExtension() [2/2]
void Geometry::deleteExtension (std::string name)
References extensions.
getExtension() [1/4]
std::weak_ptr< GeometryExtension > Geometry::getExtension (Base::Type type)
References extensions.
getExtension() [2/4]
std::weak_ptr< const GeometryExtension > Geometry::getExtension (Base::Type type) const
Referenced by getExtension(), SketcherGui::ViewProviderSketch::mouseMove(), Restore(), and SketcherGui::ViewProviderSketch::updateColor().
getExtension() [3/4]
std::weak_ptr< GeometryExtension > Geometry::getExtension (std::string name)
References extensions.
getExtension() [4/4]
std::weak_ptr< const GeometryExtension > Geometry::getExtension (std::string name) const
References getExtension().
getExtensions()
std::vector< std::weak_ptr< const GeometryExtension > > Geometry::getExtensions () const
References extensions.
Referenced by Part::GeometryPy::getExtensions().
getMemSize()
unsigned int Geometry::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Reimplemented in Part::GeomArcOfConic, Part::GeomConic, Part::GeomSurfaceOfExtrusion, Part::GeomSurfaceOfRevolution, Part::GeomTrimmedSurface, Part::GeomPlateSurface, Part::GeomOffsetSurface, Part::GeomPlane, Part::GeomToroid, Part::GeomSphere, Part::GeomCone, Part::GeomCylinder, Part::GeomBSplineSurface, Part::GeomBezierSurface, Part::GeomOffsetCurve, Part::GeomLineSegment, Part::GeomLine, Part::GeomArcOfParabola, Part::GeomParabola, Part::GeomArcOfHyperbola, Part::GeomHyperbola, Part::GeomArcOfEllipse, Part::GeomEllipse, Part::GeomArcOfCircle, Part::GeomCircle, Part::GeomTrimmedCurve, Part::GeomBSplineCurve, Part::GeomBezierCurve, and Part::GeomPoint.
getTag()
boost::uuids::uuid Geometry::getTag (void) const
returns the tag of the geometry object
References tag.
Handle()
virtual const Part::Geometry::Handle (Geom_Geometry) const & pure virtual
Implemented in Part::GeomArcOfConic, Part::GeomConic, Part::GeomSurfaceOfExtrusion, Part::GeomSurfaceOfRevolution, Part::GeomTrimmedSurface, Part::GeomPlateSurface, Part::GeomOffsetSurface, Part::GeomPlane, Part::GeomToroid, Part::GeomSphere, Part::GeomCone, Part::GeomCylinder, Part::GeomBSplineSurface, Part::GeomBezierSurface, Part::GeomOffsetCurve, Part::GeomLineSegment, Part::GeomLine, Part::GeomArcOfParabola, Part::GeomParabola, Part::GeomArcOfHyperbola, Part::GeomHyperbola, Part::GeomArcOfEllipse, Part::GeomEllipse, Part::GeomArcOfCircle, Part::GeomCircle, Part::GeomTrimmedCurve, Part::GeomBSplineCurve, Part::GeomBezierCurve, and Part::GeomPoint.
Referenced by Part::GeomCurve::closestParameter(), Part::GeomCurve::closestParameterToBasisCurve(), Part::GeomSurface::curvature(), Part::GeomCurve::curvatureAt(), Part::GeomSurface::curvatureDirections(), Part::GeomCurve::firstDerivativeAtParameter(), Part::GeomBoundedCurve::getEndPoint(), Part::GeomCurve::getFirstParameter(), Part::GeomCurve::getLastParameter(), Part::GeomBoundedCurve::getStartPoint(), Part::GeomCurve::intersect(), Part::GeomSurface::isUmbillic(), Part::GeomCurve::length(), Part::GeomSurface::normal(), Part::GeomCurve::normalAt(), Part::GeomCurve::pointAtParameter(), Part::GeomCurve::reverse(), Part::GeomCurve::secondDerivativeAtParameter(), Part::GeomCurve::tangent(), Part::GeomSurface::tangentU(), Part::GeomSurface::tangentV(), Part::GeomCurve::toBSpline(), Part::GeomCurve::toShape(), and Part::GeomSurface::toShape().
hasExtension() [1/2]
bool Geometry::hasExtension (Base::Type type) const
References extensions.
Referenced by SketcherGui::ViewProviderSketch::mouseMove(), Restore(), and SketcherGui::ViewProviderSketch::updateColor().
hasExtension() [2/2]
bool Geometry::hasExtension (std::string name) const
References extensions.
mirror() [1/2]
void Geometry::mirror (const Base::Vector3d & point)
Referenced by Part::GeometryPy::mirror().
mirror() [2/2]
void Geometry::mirror (const Base::Vector3d & point, const Base::Vector3d & dir)
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Restore()
void Geometry::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Reimplemented in Part::GeomSurfaceOfExtrusion, Part::GeomSurfaceOfRevolution, Part::GeomTrimmedSurface, Part::GeomPlateSurface, Part::GeomOffsetSurface, Part::GeomPlane, Part::GeomToroid, Part::GeomSphere, Part::GeomCone, Part::GeomCylinder, Part::GeomBSplineSurface, Part::GeomBezierSurface, Part::GeomOffsetCurve, Part::GeomLineSegment, Part::GeomLine, Part::GeomArcOfParabola, Part::GeomParabola, Part::GeomArcOfHyperbola, Part::GeomHyperbola, Part::GeomArcOfEllipse, Part::GeomEllipse, Part::GeomArcOfCircle, Part::GeomCircle, Part::GeomTrimmedCurve, Part::GeomBSplineCurve, Part::GeomBezierCurve, and Part::GeomPoint.
References Part::GeometryMigrationExtension::Construction, extensions, Base::Type::fromName(), Base::XMLReader::getAttribute(), Base::XMLReader::getAttributeAsInteger(), Base::BaseClass::getClassTypeId(), getExtension(), hasExtension(), Base::XMLReader::localName(), Base::XMLReader::readElement(), Base::XMLReader::readEndElement(), Part::GeometryPersistenceExtension::Restore(), and setExtension().
Referenced by Part::GeomPoint::Restore(), Part::GeomBSplineCurve::Restore(), Part::GeomCircle::Restore(), Part::GeomArcOfCircle::Restore(), Part::GeomEllipse::Restore(), Part::GeomArcOfEllipse::Restore(), Part::GeomHyperbola::Restore(), Part::GeomArcOfHyperbola::Restore(), Part::GeomParabola::Restore(), Part::GeomArcOfParabola::Restore(), Part::GeomLine::Restore(), Part::GeomLineSegment::Restore(), and Part::PropertyGeometryList::Restore().
rotate()
void Geometry::rotate (const Base::Placement & plm)
References DraftVecUtils::angle(), Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Rotation::getValue(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart(), and Part::GeometryPy::rotate().
Save()
void Geometry::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Reimplemented in Part::GeomSurfaceOfExtrusion, Part::GeomSurfaceOfRevolution, Part::GeomTrimmedSurface, Part::GeomPlateSurface, Part::GeomOffsetSurface, Part::GeomPlane, Part::GeomToroid, Part::GeomSphere, Part::GeomCone, Part::GeomCylinder, Part::GeomBSplineSurface, Part::GeomBezierSurface, Part::GeomOffsetCurve, Part::GeomLineSegment, Part::GeomLine, Part::GeomArcOfParabola, Part::GeomParabola, Part::GeomArcOfHyperbola, Part::GeomHyperbola, Part::GeomArcOfEllipse, Part::GeomEllipse, Part::GeomArcOfCircle, Part::GeomCircle, Part::GeomTrimmedCurve, Part::GeomBSplineCurve, Part::GeomBezierCurve, and Part::GeomPoint.
References Base::Writer::decInd(), extensions, Base::BaseClass::getClassTypeId(), Base::Writer::incInd(), Base::Writer::ind(), and Base::Writer::Stream().
Referenced by Part::GeomPoint::Save(), Part::GeomBSplineCurve::Save(), Part::GeomCircle::Save(), Part::GeomArcOfCircle::Save(), Part::GeomEllipse::Save(), Part::GeomArcOfEllipse::Save(), Part::GeomHyperbola::Save(), Part::GeomArcOfHyperbola::Save(), Part::GeomParabola::Save(), Part::GeomArcOfParabola::Save(), Part::GeomLine::Save(), and Part::GeomLineSegment::Save().
scale()
void Geometry::scale (const Base::Vector3d & vec, double scale)
References draftgeoutils.general::vec().
Referenced by Part::GeometryPy::scale().
setExtension()
void Geometry::setExtension (std::unique_ptr< GeometryExtension > && geo)
References extensions, and draftfunctions.move::move().
Referenced by Restore(), and Part::GeometryPy::setExtension().
toShape()
virtual TopoDS_Shape Part::Geometry::toShape () const pure virtual
Implemented in Part::GeomSurface, Part::GeomCurve, and Part::GeomPoint.
Referenced by Part::getPyShapes().
transform()
void Geometry::transform (const Base::Matrix4D & mat)
Referenced by Part::GeometryPy::transform().
translate()
void Geometry::translate (const Base::Vector3d & vec)
References draftgeoutils.general::vec().
Referenced by Part::GeometryPy::translate().
Member Data Documentation
extensions
std::vector<std::shared_ptr<GeometryExtension> > Part::Geometry::extensions protected
Referenced by copyNonTag(), deleteExtension(), getExtension(), getExtensions(), hasExtension(), Restore(), Save(), setExtension(), PathScripts.PathPocketShapeGui.TaskPanelExtensionPage::setFields(), and PathScripts.PathPocketShapeGui.TaskPanelExtensionPage::updateProxyExtensions().
tag
boost::uuids::uuid Part::Geometry::tag protected
Referenced by PathScripts.PathDressupHoldingTags.MapWireToTag::add(), assignTag(), PathScripts.PathDressupHoldingTags.MapWireToTag::cleanupEdges(), clone(), PathScripts.PathDressupHoldingTags.MapWireToTag::commandsForEdges(), createNewTag(), Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.ChunkBase::dump_header(), getTag(), and PathScripts.PathDressupHoldingTags.MapWireToTag::shell().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/App/Geometry.h
Sources/FreeCAD/src/Mod/Part/App/Geometry.cpp