FreeCAD: ArchWall Namespace Reference
ArchWall Namespace Reference
Workbenches » Python workbenches » Arch
The Wall object and tools.
Functions
def areSameWallTypes (walls)
def joinWalls (walls, delete=False)
def makeWall (baseobj=None, height=None, length=None, width=None, align="Center", face=None, name=None)
def mergeShapes (w1, w2)
Detailed Description
The Wall object and tools.
This module provides tools to build Wall objects. Walls are simple objects, usually vertical, typically obtained by giving a thickness to a base line, then extruding it vertically.
Function Documentation
areSameWallTypes()
def ArchWall.areSameWallTypes (walls)
Check if a list of walls have the same height, width and alignment.
Parameters
----------
walls: list of <ArchComponent.Component>
Returns
-------
bool
    True if the walls have the same height, width and alignment, False if
    otherwise.
References ArchComponent.ViewProviderComponent.attach(), ArchCommands.getDefaultColor(), ArchComponent.ViewProviderComponent.getDisplayModes(), ArchComponent.Component.getExtrusionData(), draftguitools.gui_tool_utils.getPoint, ArchCommands.getShapeFromMesh(), DraftVecUtils.isNull(), joinWalls(), ArchComponent.Component.onChanged(), ArchComponent.Component.onDocumentRestored(), draftutils.translate.QT_TRANSLATE_NOOP, DraftVecUtils.scaleTo(), ArchComponent.ViewProviderComponent.setDisplayMode(), and ArchComponent.ViewProviderComponent.updateData().
Referenced by joinWalls(), and mergeShapes().
joinWalls()
def ArchWall.joinWalls (walls, delete = False)
Join the given list of walls into one sketch-based wall.
Take the first wall in the list, and adds on the other walls in the list.
Return the modified first wall.
Setting delete to True, will delete the other walls. Only join walls
if the walls have the same width, height and alignment.
Parameters
----------
walls: list of <Part::FeaturePython>
    List containing the walls to add to the first wall in the list. Walls must
    be based off a base object.
delete: bool, optional
    If True, deletes the other walls in the list.
Returns
-------
<Part::FeaturePython>
References areSameWallTypes().
Referenced by areSameWallTypes().
makeWall()
def ArchWall.makeWall (baseobj = None, height = None, length = None, width = None, align = "Center", face = None, name = None)
Create a wall based on a given object, and returns the generated wall.
TODO: It is unclear what defines which units this function uses.
Parameters
----------
baseobj: <Part::PartFeature>, optional
    The base object with which to build the wall. This can be a sketch, a
    draft object, a face, or a solid. It can also be left as None.
height: float, optional
    The height of the wall.
length: float, optional
    The length of the wall. Not used if the wall is based off an object.
    Will use Arch default if left empty.
width: float, optional
    The width of the wall. Not used if the base object is a face.  Will use
    Arch default if left empty.
align: str, optional
    Either "Center", "Left", or "Right". Effects the alignment of the wall
    on its baseline.
face: int, optional
    The index number of a face on the given baseobj, to base the wall on.
name: str, optional
    The name to give to the created wall.
Returns
-------
<Part::FeaturePython>
    Returns the generated wall.
Notes
-----
Creates a new <Part::FeaturePython> object, and turns it into a parametric wall
object. This <Part::FeaturePython> object does not yet have any shape.
The wall then uses the baseobj.Shape as the basis to extrude out a wall shape,
giving the new <Part::FeaturePython> object a shape.
It then hides the original baseobj.
Referenced by ArchCommands.removeShape().
mergeShapes()
def ArchWall.mergeShapes (w1, w2)
Not currently implemented.
Return a Shape built on two walls that share same properties and have a
coincident endpoint.
References areSameWallTypes().
Referenced by ArchComponent.Component.processSubShapes().