FreeCAD: Gui::CommandBase Class Reference
Gui::CommandBase Class Reference abstract
The CommandBase class This lightweight class is the base class of all commands in FreeCAD.
#include <Command.h>
Public Member Functions
Action * getAction () const
Returns the Action object of this command, or 0 if it doesn't exist.
Methods to get the properties of the command
virtual const char * getMenuText () const
virtual const char * getToolTipText () const
virtual const char * getStatusTip () const
virtual const char * getWhatsThis () const
virtual const char * getPixmap () const
virtual const char * getAccel () const
Methods to set the properties of the command
void setWhatsThis (const char *)
void setMenuText (const char *)
void setToolTipText (const char *)
void setStatusTip (const char *)
void setPixmap (const char *)
void setAccel (const char *)
Protected Member Functions
CommandBase (const char *sMenu, const char *sToolTip=nullptr, const char *sWhat=nullptr, const char *sStatus=nullptr, const char *sPixmap=nullptr, const char *sAccel=nullptr)
virtual ~CommandBase ()
Protected Attributes
Attributes set by the inherited constructor.
They set up the most important properties of the command.
In the constructor are set default values. The real values should be set in the constructor of the inheriting class.
const char * sMenuText
const char * sToolTipText
const char * sWhatsThis
const char * sStatusTip
const char * sPixmap
const char * sAccel
std::string displayText
Methods to override when creating a new command
virtual Action * createAction (void)
Creates the used Action when adding to a widget. The default implementation does nothing.
virtual void languageChange ()=0
Reassigns QAction stuff after the language has changed.
virtual void updateAction (int mode)=0
Updates the QAction with respect to the passed mode.
virtual const char * className () const =0
The C++ class name is needed as context for the translation framework.
Detailed Description
The CommandBase class This lightweight class is the base class of all commands in FreeCAD.
It represents the link between the FreeCAD command framework and the QAction world of Qt.
Author
Werner Mayer
Constructor & Destructor Documentation
CommandBase()
CommandBase::CommandBase (const char * sMenu, const char * sToolTip = nullptr, const char * sWhat = nullptr, const char * sStatus = nullptr, const char * sPixmap = nullptr, const char * sAccel = nullptr) protected
~CommandBase()
CommandBase::~CommandBase () protected virtual
Member Function Documentation
className()
virtual const char * Gui::CommandBase::className () const pure virtual
The C++ class name is needed as context for the translation framework.
Implemented in Gui::PythonCommand, Gui::PythonGroupCommand, Gui::MacroCommand, StdCmdOpen, StdCmdImport, StdCmdExport, StdCmdMergeProjects, StdCmdDependencyGraph, StdCmdNew, StdCmdSave, StdCmdSaveAs, StdCmdSaveCopy, StdCmdSaveAll, StdCmdRevert, StdCmdProjectInfo, StdCmdProjectUtil, StdCmdPrint, StdCmdPrintPreview, StdCmdPrintPdf, StdCmdQuit, StdCmdUndo, StdCmdRedo, StdCmdCut, StdCmdCopy, StdCmdPaste, StdCmdDuplicateSelection, StdCmdSelectAll, StdCmdDelete, StdCmdRefresh, StdCmdTransform, StdCmdPlacement, StdCmdTransformManip, StdCmdAlignment, StdCmdEdit, StdCmdExpression, StdCmdLinkMakeGroup, StdCmdLinkMake, StdCmdLinkMakeRelative, StdCmdLinkReplace, StdCmdLinkUnlink, StdCmdLinkImport, StdCmdLinkImportAll, StdCmdLinkSelectLinked, StdCmdLinkSelectLinkedFinal, StdCmdLinkSelectAllLinks, StdCmdLinkSelectActions, StdCmdLinkActions, StdCmdDlgMacroRecord, StdCmdMacroStopRecord, StdCmdDlgMacroExecute, StdCmdDlgMacroExecuteDirect, StdCmdMacroAttachDebugger, StdCmdMacroStartDebug, StdCmdMacroStopDebug, StdCmdMacroStepOver, StdCmdMacroStepInto, StdCmdToggleBreakpoint, StdCmdWorkbench, StdCmdRecentFiles, StdCmdRecentMacros, StdCmdAbout, StdCmdAboutQt, StdCmdWhatsThis, StdCmdDlgParameter, StdCmdDlgPreferences, StdCmdDlgCustomize, StdCmdCommandLine, StdCmdOnlineHelp, StdCmdOnlineHelpWebsite, StdCmdFreeCADDonation, StdCmdFreeCADWebsite, StdCmdFreeCADUserHub, StdCmdFreeCADPowerUserHub, StdCmdFreeCADForum, StdCmdFreeCADFAQ, StdCmdPythonWebsite, StdCmdReportBug, StdCmdMeasurementSimple, StdCmdTextDocument, StdCmdUnitsCalculator, StdCmdUserEditMode, StdCmdPart, StdCmdGroup, Std_TestQM, Std_TestReloadQM, FCCmdTest1, FCCmdTest2, FCCmdTest3, FCCmdTest4, FCCmdTest5, FCCmdTest6, CmdTestCmdFuncs, CmdTestProgress1, CmdTestProgress2, CmdTestProgress3, CmdTestProgress4, CmdTestProgress5, CmdTestMDI1, CmdTestMDI2, CmdTestMDI3, CmdTestConsoleOutput, StdOrthographicCamera, StdPerspectiveCamera, StdCmdViewSaveCamera, StdCmdViewRestoreCamera, StdCmdFreezeViews, StdCmdToggleClipPlane, StdCmdDrawStyle, StdCmdToggleVisibility, StdCmdToggleSelectability, StdCmdShowSelection, StdCmdHideSelection, StdCmdSelectVisibleObjects, StdCmdToggleObjects, StdCmdShowObjects, StdCmdHideObjects, StdCmdSetAppearance, StdCmdViewHome, StdCmdViewBottom, StdCmdViewFront, StdCmdViewLeft, StdCmdViewRear, StdCmdViewRight, StdCmdViewTop, StdCmdViewIsometric, StdCmdViewDimetric, StdCmdViewTrimetric, StdCmdViewRotateLeft, StdCmdViewRotateRight, StdCmdViewFitAll, StdCmdViewFitSelection, StdViewDock, StdViewUndock, StdMainFullscreen, StdViewFullscreen, StdViewDockUndockFullscreen, StdCmdViewVR, StdViewScreenShot, StdCmdViewCreate, StdCmdToggleNavigation, StdCmdAxisCross, StdCmdViewExample1, StdCmdViewExample2, StdCmdViewExample3, StdCmdViewIvStereoOff, StdCmdViewIvStereoRedGreen, StdCmdViewIvStereoQuadBuff, StdCmdViewIvStereoInterleavedRows, StdCmdViewIvStereoInterleavedColumns, StdCmdViewIvIssueCamPos, StdViewZoomIn, StdViewZoomOut, StdViewBoxZoom, StdBoxSelection, StdBoxElementSelection, StdTreeSelection, StdCmdTreeCollapse, StdCmdTreeExpand, StdCmdTreeSelectAllInstances, StdCmdMeasureDistance, StdCmdSceneInspector, StdCmdTextureMapping, StdCmdDemoMode, CmdViewMeasureClearAll, CmdViewMeasureToggleAll, StdCmdSelBack, StdCmdSelForward, StdTreeDrag, StdCmdTreeViewActions, StdCmdSelBoundingBox, StdCmdArrangeIcons, StdCmdTileWindows, StdCmdCascadeWindows, StdCmdCloseActiveWindow, StdCmdCloseAllWindows, StdCmdActivateNextWindow, StdCmdActivatePrevWindow, StdCmdWindows, StdCmdUserInterface, StdCmdDockViewMenu, StdCmdToolBarMenu, StdCmdStatusBar, StdCmdWindowsMenu, ViewIsometricCmd, ViewOrthographicCmd, ViewPerspectiveCmd, ViewZoomToFitCmd, Gui::StdCmdPythonHelp, CmdSandboxEventLoop, CmdSandboxMeshLoader, CmdSketcherConstraint, CmdSketcherConstrainHorizontal, CmdSketcherConstrainVertical, CmdSketcherConstrainLock, CmdSketcherConstrainBlock, CmdSketcherConstrainCoincident, CmdSketcherConstrainDistance, CmdSketcherConstrainPointOnObject, CmdSketcherConstrainDistanceX, CmdSketcherConstrainDistanceY, CmdSketcherConstrainParallel, CmdSketcherConstrainPerpendicular, CmdSketcherConstrainTangent, CmdSketcherConstrainRadius, CmdSketcherConstrainDiameter, CmdSketcherConstrainRadiam, CmdSketcherConstrainAngle, CmdSketcherConstrainEqual, CmdSketcherConstrainSymmetric, CmdSketcherCopy, CmdSketcherClone, and CmdSketcherMove.
Referenced by Gui::StdCmdDownloadOnlineHelp::createAction(), Gui::Command::createAction(), Gui::Dialog::CommandModel::data(), Gui::Command::languageChange(), Gui::PythonGroupCommand::languageChange(), Gui::StdCmdDownloadOnlineHelp::languageChange(), Gui::Dialog::DlgCustomKeyboardImp::on_buttonReset_clicked(), Gui::Dialog::DlgCustomKeyboardImp::setShortcutOfCurrentAction(), Gui::GroupCommand::setup(), and Gui::Command::translatedGroupName().
createAction()
Action * CommandBase::createAction (void) protected virtual
Creates the used Action when adding to a widget. The default implementation does nothing.
Reimplemented in Gui::StdCmdDownloadOnlineHelp, Gui::Command, Gui::GroupCommand, Gui::PythonCommand, Gui::PythonGroupCommand, Gui::MacroCommand, StdCmdUndo, StdCmdRedo, StdCmdExpression, StdCmdLinkMakeGroup, StdCmdWorkbench, StdCmdRecentFiles, StdCmdRecentMacros, StdCmdAbout, StdCmdDlgPreferences, StdCmdUserEditMode, StdOrthographicCamera, StdPerspectiveCamera, StdCmdFreezeViews, StdCmdToggleClipPlane, StdCmdDrawStyle, StdViewDockUndockFullscreen, StdCmdSelBoundingBox, StdCmdDockViewMenu, StdCmdToolBarMenu, StdCmdStatusBar, StdCmdWindowsMenu, and Gui::StdCmdDescription.
getAccel()
virtual const char * Gui::CommandBase::getAccel () const virtual
Reimplemented in Gui::PythonCommand, and Gui::PythonGroupCommand.
Referenced by Gui::StdCmdDownloadOnlineHelp::createAction(), StdCmdUndo::createAction(), StdCmdRedo::createAction(), StdCmdWorkbench::createAction(), StdCmdAbout::createAction(), StdCmdFreezeViews::createAction(), Gui::Dialog::DlgCustomActionsImp::on_actionListWidget_itemActivated(), Gui::Dialog::DlgCustomActionsImp::on_buttonReplaceAction_clicked(), Gui::Dialog::DlgCustomKeyboardImp::on_buttonReset_clicked(), Gui::Dialog::DlgCustomKeyboardImp::on_commandTreeWidget_currentItemChanged(), and Gui::MacroCommand::save().
getAction()
Action * CommandBase::getAction () const
Returns the Action object of this command, or 0 if it doesn't exist.
Referenced by Gui::MainWindow::event(), StdCmdStatusBar::isActive(), Gui::Dialog::DlgCustomActionsImp::on_buttonReplaceAction_clicked(), Gui::Dialog::DlgCustomKeyboardImp::on_buttonReset_clicked(), Gui::Dialog::DlgCustomKeyboardImp::on_commandTreeWidget_currentItemChanged(), Gui::Dialog::DlgCustomKeyboardImp::on_editShortcut_textChanged(), Gui::Dialog::DlgCustomKeyboardImp::setShortcutOfCurrentAction(), FemGui::TaskPostClip::TaskPostClip(), FemGui::TaskPostCut::TaskPostCut(), CmdSketcherConstrainLock::updateAction(), CmdSketcherConstrainDistance::updateAction(), CmdSketcherConstrainDistanceX::updateAction(), CmdSketcherConstrainDistanceY::updateAction(), CmdSketcherConstrainRadius::updateAction(), CmdSketcherConstrainDiameter::updateAction(), CmdSketcherConstrainRadiam::updateAction(), and CmdSketcherConstrainAngle::updateAction().
getMenuText()
virtual const char * Gui::CommandBase::getMenuText () const virtual
Reimplemented in Gui::PythonCommand, and Gui::PythonGroupCommand.
Referenced by Gui::Command::applyCommandData(), Gui::StdCmdDownloadOnlineHelp::createAction(), StdCmdAbout::createAction(), StdViewDockUndockFullscreen::createAction(), Gui::Dialog::CommandModel::data(), Gui::Command::invoke(), Gui::PythonGroupCommand::languageChange(), StdCmdAbout::languageChange(), Gui::StdCmdDownloadOnlineHelp::languageChange(), Gui::Dialog::DlgCustomActionsImp::on_actionListWidget_itemActivated(), Gui::Dialog::DlgCustomActionsImp::on_buttonReplaceAction_clicked(), Gui::Dialog::DlgMacroExecuteImp::on_toolbarButton_clicked(), Gui::Dialog::DlgCustomCommandsImp::onAddMacroAction(), Gui::Dialog::DlgCustomKeyboardImp::onAddMacroAction(), Gui::Dialog::DlgCustomToolbars::onAddMacroAction(), Gui::Dialog::DlgCustomCommandsImp::onModifyMacroAction(), Gui::Dialog::DlgCustomKeyboardImp::onModifyMacroAction(), Gui::Dialog::DlgCustomToolbars::onModifyMacroAction(), Gui::Command::recreateTooltip(), Gui::MacroCommand::save(), and Gui::GroupCommand::setup().
getPixmap()
virtual const char * Gui::CommandBase::getPixmap () const virtual
Reimplemented in Gui::PythonCommand, and Gui::PythonGroupCommand.
Referenced by Gui::StdCmdDownloadOnlineHelp::createAction(), StdCmdUndo::createAction(), StdCmdRedo::createAction(), StdCmdWorkbench::createAction(), Gui::Dialog::CommandModel::data(), Gui::PythonGroupCommand::languageChange(), Gui::Dialog::DlgCustomActionsImp::on_actionListWidget_itemActivated(), Gui::Dialog::DlgCustomActionsImp::on_buttonReplaceAction_clicked(), Gui::Dialog::DlgCustomCommandsImp::onAddMacroAction(), Gui::Dialog::DlgCustomKeyboardImp::onAddMacroAction(), Gui::Dialog::DlgCustomToolbars::onAddMacroAction(), Gui::Dialog::DlgCustomCommandsImp::onModifyMacroAction(), Gui::Dialog::DlgCustomKeyboardImp::onModifyMacroAction(), Gui::Dialog::DlgCustomToolbars::onModifyMacroAction(), and Gui::MacroCommand::save().
getStatusTip()
virtual const char * Gui::CommandBase::getStatusTip () const virtual
Reimplemented in Gui::PythonCommand, and Gui::PythonGroupCommand.
Referenced by Gui::StdCmdDownloadOnlineHelp::createAction(), StdCmdAbout::createAction(), StdCmdWindowsMenu::createAction(), Gui::PythonGroupCommand::languageChange(), StdCmdAbout::languageChange(), Gui::StdCmdDownloadOnlineHelp::languageChange(), Gui::Dialog::DlgCustomActionsImp::on_actionListWidget_itemActivated(), Gui::Dialog::DlgCustomActionsImp::on_buttonReplaceAction_clicked(), Gui::Command::recreateTooltip(), and Gui::MacroCommand::save().
getToolTipText()
virtual const char * Gui::CommandBase::getToolTipText () const virtual
Reimplemented in Gui::PythonCommand, and Gui::PythonGroupCommand.
Referenced by Gui::StdCmdDownloadOnlineHelp::createAction(), StdCmdAbout::createAction(), StdCmdWindowsMenu::createAction(), Gui::Dialog::CommandModel::data(), Gui::PythonGroupCommand::languageChange(), StdCmdAbout::languageChange(), Gui::StdCmdDownloadOnlineHelp::languageChange(), Gui::Dialog::DlgCustomActionsImp::on_actionListWidget_itemActivated(), Gui::Dialog::DlgCustomActionsImp::on_buttonReplaceAction_clicked(), Gui::Dialog::DlgCustomCommandsImp::onAddMacroAction(), Gui::Dialog::DlgCustomKeyboardImp::onAddMacroAction(), Gui::Dialog::DlgCustomToolbars::onAddMacroAction(), Gui::Dialog::DlgCustomCommandsImp::onModifyMacroAction(), Gui::Dialog::DlgCustomKeyboardImp::onModifyMacroAction(), Gui::Dialog::DlgCustomToolbars::onModifyMacroAction(), Gui::Command::recreateTooltip(), and Gui::MacroCommand::save().
getWhatsThis()
virtual const char * Gui::CommandBase::getWhatsThis () const virtual
Reimplemented in Gui::PythonCommand, and Gui::PythonGroupCommand.
Referenced by Gui::Command::applyCommandData(), Gui::StdCmdDownloadOnlineHelp::createAction(), StdCmdLinkMakeGroup::createAction(), StdCmdAbout::createAction(), StdCmdUserEditMode::createAction(), StdCmdFreezeViews::createAction(), StdCmdDrawStyle::createAction(), StdCmdWindowsMenu::createAction(), StdCmdAbout::languageChange(), Gui::StdCmdDownloadOnlineHelp::languageChange(), Gui::Dialog::DlgCustomActionsImp::on_actionListWidget_itemActivated(), Gui::Dialog::DlgCustomActionsImp::on_buttonReplaceAction_clicked(), Gui::Command::recreateTooltip(), and Gui::MacroCommand::save().
languageChange()
virtual void Gui::CommandBase::languageChange () pure virtual
Reassigns QAction stuff after the language has changed.
Implemented in Gui::Command, Gui::GroupCommand, Gui::PythonCommand, Gui::PythonGroupCommand, Gui::MacroCommand, StdCmdLinkMakeGroup, StdCmdAbout, StdCmdUserEditMode, StdCmdFreezeViews, StdCmdDrawStyle, and Gui::StdCmdDownloadOnlineHelp.
setAccel()
void CommandBase::setAccel (const char * s)
References StringCache::New(), and sAccel.
Referenced by Gui::MacroCommand::load(), Gui::Dialog::DlgCustomActionsImp::on_buttonAddAction_clicked(), Gui::Dialog::DlgCustomActionsImp::on_buttonReplaceAction_clicked(), and Gui::Dialog::DlgCustomKeyboardImp::setShortcutOfCurrentAction().
setMenuText()
void CommandBase::setMenuText (const char * s)
References StringCache::New(), and sMenuText.
Referenced by Gui::MacroCommand::load(), Gui::Dialog::DlgCustomActionsImp::on_buttonAddAction_clicked(), and Gui::Dialog::DlgCustomActionsImp::on_buttonReplaceAction_clicked().
setPixmap()
void CommandBase::setPixmap (const char * s)
References StringCache::New(), and sPixmap.
Referenced by Gui::MacroCommand::load(), Gui::Dialog::DlgCustomActionsImp::on_buttonAddAction_clicked(), and Gui::Dialog::DlgCustomActionsImp::on_buttonReplaceAction_clicked().
setStatusTip()
void CommandBase::setStatusTip (const char * s)
References StringCache::New(), and sStatusTip.
Referenced by Gui::MacroCommand::load(), Gui::Dialog::DlgCustomActionsImp::on_buttonAddAction_clicked(), and Gui::Dialog::DlgCustomActionsImp::on_buttonReplaceAction_clicked().
setToolTipText()
void CommandBase::setToolTipText (const char * s)
References StringCache::New(), and sToolTipText.
Referenced by Gui::MacroCommand::load(), Gui::Dialog::DlgCustomActionsImp::on_buttonAddAction_clicked(), and Gui::Dialog::DlgCustomActionsImp::on_buttonReplaceAction_clicked().
setWhatsThis()
void CommandBase::setWhatsThis (const char * s)
References StringCache::New(), and sWhatsThis.
Referenced by Gui::MacroCommand::load(), Gui::Dialog::DlgCustomActionsImp::on_buttonAddAction_clicked(), and Gui::Dialog::DlgCustomActionsImp::on_buttonReplaceAction_clicked().
updateAction()
virtual void Gui::CommandBase::updateAction (int mode) pure virtual
Updates the QAction with respect to the passed mode.
Implemented in Gui::Command, CmdSketcherConstrainLock, CmdSketcherConstrainDistance, CmdSketcherConstrainDistanceX, CmdSketcherConstrainDistanceY, CmdSketcherConstrainRadius, CmdSketcherConstrainDiameter, CmdSketcherConstrainRadiam, and CmdSketcherConstrainAngle.
Member Data Documentation
displayText
std::string Gui::CommandBase::displayText protected
Referenced by Gui::Command::invoke().
sAccel
const char* Gui::CommandBase::sAccel protected
Referenced by CmdSketcherClone::CmdSketcherClone(), CmdSketcherConstrainAngle::CmdSketcherConstrainAngle(), CmdSketcherConstrainBlock::CmdSketcherConstrainBlock(), CmdSketcherConstrainCoincident::CmdSketcherConstrainCoincident(), CmdSketcherConstrainDiameter::CmdSketcherConstrainDiameter(), CmdSketcherConstrainDistance::CmdSketcherConstrainDistance(), CmdSketcherConstrainDistanceX::CmdSketcherConstrainDistanceX(), CmdSketcherConstrainDistanceY::CmdSketcherConstrainDistanceY(), CmdSketcherConstrainEqual::CmdSketcherConstrainEqual(), CmdSketcherConstrainHorizontal::CmdSketcherConstrainHorizontal(), CmdSketcherConstrainLock::CmdSketcherConstrainLock(), CmdSketcherConstrainParallel::CmdSketcherConstrainParallel(), CmdSketcherConstrainPerpendicular::CmdSketcherConstrainPerpendicular(), CmdSketcherConstrainPointOnObject::CmdSketcherConstrainPointOnObject(), CmdSketcherConstrainRadiam::CmdSketcherConstrainRadiam(), CmdSketcherConstrainRadius::CmdSketcherConstrainRadius(), CmdSketcherConstrainSymmetric::CmdSketcherConstrainSymmetric(), CmdSketcherConstrainTangent::CmdSketcherConstrainTangent(), CmdSketcherConstrainVertical::CmdSketcherConstrainVertical(), CmdSketcherCopy::CmdSketcherCopy(), CmdSketcherMove::CmdSketcherMove(), Gui::Command::createAction(), Gui::MacroCommand::createAction(), Gui::Command::printConflictingAccelerators(), setAccel(), StdBoxSelection::StdBoxSelection(), Gui::StdCmdDescription::StdCmdDescription(), and StdCmdFreezeViews::StdCmdFreezeViews().
sMenuText
const char* Gui::CommandBase::sMenuText protected
Referenced by CmdSandboxEventLoop::CmdSandboxEventLoop(), CmdSandboxMeshLoader::CmdSandboxMeshLoader(), CmdSketcherClone::CmdSketcherClone(), CmdSketcherConstrainAngle::CmdSketcherConstrainAngle(), CmdSketcherConstrainBlock::CmdSketcherConstrainBlock(), CmdSketcherConstrainCoincident::CmdSketcherConstrainCoincident(), CmdSketcherConstrainDiameter::CmdSketcherConstrainDiameter(), CmdSketcherConstrainDistance::CmdSketcherConstrainDistance(), CmdSketcherConstrainDistanceX::CmdSketcherConstrainDistanceX(), CmdSketcherConstrainDistanceY::CmdSketcherConstrainDistanceY(), CmdSketcherConstrainEqual::CmdSketcherConstrainEqual(), CmdSketcherConstrainHorizontal::CmdSketcherConstrainHorizontal(), CmdSketcherConstrainLock::CmdSketcherConstrainLock(), CmdSketcherConstrainParallel::CmdSketcherConstrainParallel(), CmdSketcherConstrainPerpendicular::CmdSketcherConstrainPerpendicular(), CmdSketcherConstrainPointOnObject::CmdSketcherConstrainPointOnObject(), CmdSketcherConstrainRadiam::CmdSketcherConstrainRadiam(), CmdSketcherConstrainRadius::CmdSketcherConstrainRadius(), CmdSketcherConstrainSymmetric::CmdSketcherConstrainSymmetric(), CmdSketcherConstrainTangent::CmdSketcherConstrainTangent(), CmdSketcherConstrainVertical::CmdSketcherConstrainVertical(), CmdSketcherCopy::CmdSketcherCopy(), CmdSketcherMove::CmdSketcherMove(), Gui::MacroCommand::createAction(), setMenuText(), StdBoxSelection::StdBoxSelection(), Gui::StdCmdDescription::StdCmdDescription(), Gui::StdCmdDownloadOnlineHelp::StdCmdDownloadOnlineHelp(), StdCmdDrawStyle::StdCmdDrawStyle(), StdCmdExpression::StdCmdExpression(), StdCmdFreezeViews::StdCmdFreezeViews(), StdCmdLinkActions::StdCmdLinkActions(), StdCmdLinkMakeGroup::StdCmdLinkMakeGroup(), StdCmdLinkSelectActions::StdCmdLinkSelectActions(), Gui::StdCmdPythonHelp::StdCmdPythonHelp(), StdCmdTreeViewActions::StdCmdTreeViewActions(), and StdCmdUserEditMode::StdCmdUserEditMode().
sPixmap
const char* Gui::CommandBase::sPixmap protected
Referenced by CmdSandboxEventLoop::CmdSandboxEventLoop(), CmdSandboxMeshLoader::CmdSandboxMeshLoader(), CmdSketcherClone::CmdSketcherClone(), CmdSketcherConstrainAngle::CmdSketcherConstrainAngle(), CmdSketcherConstrainBlock::CmdSketcherConstrainBlock(), CmdSketcherConstrainCoincident::CmdSketcherConstrainCoincident(), CmdSketcherConstrainDiameter::CmdSketcherConstrainDiameter(), CmdSketcherConstrainDistance::CmdSketcherConstrainDistance(), CmdSketcherConstrainDistanceX::CmdSketcherConstrainDistanceX(), CmdSketcherConstrainDistanceY::CmdSketcherConstrainDistanceY(), CmdSketcherConstrainEqual::CmdSketcherConstrainEqual(), CmdSketcherConstrainHorizontal::CmdSketcherConstrainHorizontal(), CmdSketcherConstrainLock::CmdSketcherConstrainLock(), CmdSketcherConstrainParallel::CmdSketcherConstrainParallel(), CmdSketcherConstrainPerpendicular::CmdSketcherConstrainPerpendicular(), CmdSketcherConstrainPointOnObject::CmdSketcherConstrainPointOnObject(), CmdSketcherConstrainRadiam::CmdSketcherConstrainRadiam(), CmdSketcherConstrainRadius::CmdSketcherConstrainRadius(), CmdSketcherConstrainSymmetric::CmdSketcherConstrainSymmetric(), CmdSketcherConstrainTangent::CmdSketcherConstrainTangent(), CmdSketcherConstrainVertical::CmdSketcherConstrainVertical(), CmdSketcherCopy::CmdSketcherCopy(), CmdSketcherMove::CmdSketcherMove(), Gui::Command::createAction(), Gui::MacroCommand::createAction(), setPixmap(), StdBoxSelection::StdBoxSelection(), Gui::StdCmdDownloadOnlineHelp::StdCmdDownloadOnlineHelp(), StdCmdDrawStyle::StdCmdDrawStyle(), StdCmdLinkMakeGroup::StdCmdLinkMakeGroup(), Gui::StdCmdPythonHelp::StdCmdPythonHelp(), and StdCmdUserEditMode::StdCmdUserEditMode().
sStatusTip
const char* Gui::CommandBase::sStatusTip protected
Referenced by CmdSandboxEventLoop::CmdSandboxEventLoop(), CmdSandboxMeshLoader::CmdSandboxMeshLoader(), CmdSketcherClone::CmdSketcherClone(), CmdSketcherConstrainAngle::CmdSketcherConstrainAngle(), CmdSketcherConstrainBlock::CmdSketcherConstrainBlock(), CmdSketcherConstrainCoincident::CmdSketcherConstrainCoincident(), CmdSketcherConstrainDiameter::CmdSketcherConstrainDiameter(), CmdSketcherConstrainDistance::CmdSketcherConstrainDistance(), CmdSketcherConstrainDistanceX::CmdSketcherConstrainDistanceX(), CmdSketcherConstrainDistanceY::CmdSketcherConstrainDistanceY(), CmdSketcherConstrainEqual::CmdSketcherConstrainEqual(), CmdSketcherConstrainHorizontal::CmdSketcherConstrainHorizontal(), CmdSketcherConstrainLock::CmdSketcherConstrainLock(), CmdSketcherConstrainParallel::CmdSketcherConstrainParallel(), CmdSketcherConstrainPerpendicular::CmdSketcherConstrainPerpendicular(), CmdSketcherConstrainPointOnObject::CmdSketcherConstrainPointOnObject(), CmdSketcherConstrainRadiam::CmdSketcherConstrainRadiam(), CmdSketcherConstrainRadius::CmdSketcherConstrainRadius(), CmdSketcherConstrainSymmetric::CmdSketcherConstrainSymmetric(), CmdSketcherConstrainTangent::CmdSketcherConstrainTangent(), CmdSketcherConstrainVertical::CmdSketcherConstrainVertical(), CmdSketcherCopy::CmdSketcherCopy(), CmdSketcherMove::CmdSketcherMove(), Gui::MacroCommand::createAction(), Gui::Command::recreateTooltip(), setStatusTip(), StdBoxSelection::StdBoxSelection(), Gui::StdCmdDescription::StdCmdDescription(), Gui::StdCmdDownloadOnlineHelp::StdCmdDownloadOnlineHelp(), StdCmdDrawStyle::StdCmdDrawStyle(), StdCmdExpression::StdCmdExpression(), StdCmdFreezeViews::StdCmdFreezeViews(), StdCmdLinkActions::StdCmdLinkActions(), StdCmdLinkMakeGroup::StdCmdLinkMakeGroup(), StdCmdLinkSelectActions::StdCmdLinkSelectActions(), Gui::StdCmdPythonHelp::StdCmdPythonHelp(), StdCmdTreeViewActions::StdCmdTreeViewActions(), and StdCmdUserEditMode::StdCmdUserEditMode().
sToolTipText
const char* Gui::CommandBase::sToolTipText protected
Referenced by CmdSandboxEventLoop::CmdSandboxEventLoop(), CmdSandboxMeshLoader::CmdSandboxMeshLoader(), CmdSketcherClone::CmdSketcherClone(), CmdSketcherConstrainAngle::CmdSketcherConstrainAngle(), CmdSketcherConstrainBlock::CmdSketcherConstrainBlock(), CmdSketcherConstrainCoincident::CmdSketcherConstrainCoincident(), CmdSketcherConstrainDiameter::CmdSketcherConstrainDiameter(), CmdSketcherConstrainDistance::CmdSketcherConstrainDistance(), CmdSketcherConstrainDistanceX::CmdSketcherConstrainDistanceX(), CmdSketcherConstrainDistanceY::CmdSketcherConstrainDistanceY(), CmdSketcherConstrainEqual::CmdSketcherConstrainEqual(), CmdSketcherConstrainHorizontal::CmdSketcherConstrainHorizontal(), CmdSketcherConstrainLock::CmdSketcherConstrainLock(), CmdSketcherConstrainParallel::CmdSketcherConstrainParallel(), CmdSketcherConstrainPerpendicular::CmdSketcherConstrainPerpendicular(), CmdSketcherConstrainPointOnObject::CmdSketcherConstrainPointOnObject(), CmdSketcherConstrainRadiam::CmdSketcherConstrainRadiam(), CmdSketcherConstrainRadius::CmdSketcherConstrainRadius(), CmdSketcherConstrainSymmetric::CmdSketcherConstrainSymmetric(), CmdSketcherConstrainTangent::CmdSketcherConstrainTangent(), CmdSketcherConstrainVertical::CmdSketcherConstrainVertical(), CmdSketcherCopy::CmdSketcherCopy(), CmdSketcherMove::CmdSketcherMove(), Gui::MacroCommand::createAction(), setToolTipText(), StdBoxSelection::StdBoxSelection(), Gui::StdCmdDescription::StdCmdDescription(), Gui::StdCmdDownloadOnlineHelp::StdCmdDownloadOnlineHelp(), StdCmdDrawStyle::StdCmdDrawStyle(), StdCmdExpression::StdCmdExpression(), StdCmdFreezeViews::StdCmdFreezeViews(), StdCmdLinkActions::StdCmdLinkActions(), StdCmdLinkMakeGroup::StdCmdLinkMakeGroup(), StdCmdLinkSelectActions::StdCmdLinkSelectActions(), Gui::StdCmdPythonHelp::StdCmdPythonHelp(), StdCmdTreeViewActions::StdCmdTreeViewActions(), and StdCmdUserEditMode::StdCmdUserEditMode().
sWhatsThis
const char* Gui::CommandBase::sWhatsThis protected
Referenced by CmdSandboxEventLoop::CmdSandboxEventLoop(), CmdSandboxMeshLoader::CmdSandboxMeshLoader(), CmdSketcherClone::CmdSketcherClone(), CmdSketcherConstrainAngle::CmdSketcherConstrainAngle(), CmdSketcherConstrainBlock::CmdSketcherConstrainBlock(), CmdSketcherConstrainCoincident::CmdSketcherConstrainCoincident(), CmdSketcherConstrainDiameter::CmdSketcherConstrainDiameter(), CmdSketcherConstrainDistance::CmdSketcherConstrainDistance(), CmdSketcherConstrainDistanceX::CmdSketcherConstrainDistanceX(), CmdSketcherConstrainDistanceY::CmdSketcherConstrainDistanceY(), CmdSketcherConstrainEqual::CmdSketcherConstrainEqual(), CmdSketcherConstrainHorizontal::CmdSketcherConstrainHorizontal(), CmdSketcherConstrainLock::CmdSketcherConstrainLock(), CmdSketcherConstrainParallel::CmdSketcherConstrainParallel(), CmdSketcherConstrainPerpendicular::CmdSketcherConstrainPerpendicular(), CmdSketcherConstrainPointOnObject::CmdSketcherConstrainPointOnObject(), CmdSketcherConstrainRadiam::CmdSketcherConstrainRadiam(), CmdSketcherConstrainRadius::CmdSketcherConstrainRadius(), CmdSketcherConstrainSymmetric::CmdSketcherConstrainSymmetric(), CmdSketcherConstrainTangent::CmdSketcherConstrainTangent(), CmdSketcherConstrainVertical::CmdSketcherConstrainVertical(), CmdSketcherCopy::CmdSketcherCopy(), CmdSketcherMove::CmdSketcherMove(), Gui::GroupCommand::createAction(), Gui::MacroCommand::createAction(), setWhatsThis(), StdBoxSelection::StdBoxSelection(), Gui::StdCmdDescription::StdCmdDescription(), Gui::StdCmdDownloadOnlineHelp::StdCmdDownloadOnlineHelp(), StdCmdDrawStyle::StdCmdDrawStyle(), StdCmdExpression::StdCmdExpression(), StdCmdFreezeViews::StdCmdFreezeViews(), StdCmdLinkActions::StdCmdLinkActions(), StdCmdLinkMakeGroup::StdCmdLinkMakeGroup(), StdCmdLinkSelectActions::StdCmdLinkSelectActions(), Gui::StdCmdPythonHelp::StdCmdPythonHelp(), StdCmdTreeViewActions::StdCmdTreeViewActions(), and StdCmdUserEditMode::StdCmdUserEditMode().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/Command.h
FreeCAD/src/Gui/Command.cpp