FreeCAD: MeshPartGui::CrossSections Class Reference
MeshPartGui::CrossSections Class Reference
#include <CrossSections.h>
Public Member Functions
void accept ()
void apply ()
CrossSections (const Base::BoundBox3d &bb, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~CrossSections ()
Protected Member Functions
void changeEvent (QEvent *e)
void keyPressEvent (QKeyEvent *)
Constructor & Destructor Documentation
CrossSections()
CrossSections::CrossSections (const Base::BoundBox3d & bb, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
References Gui::Application::activeDocument(), MeshPartGui::Ui_CrossSections::distance, Base::BoundBox3< _Precision >::GetCenter(), Gui::Application::Instance, Base::Unit::Length, MeshPartGui::Ui_CrossSections::position, Gui::QuantitySpinBox::setRange(), Gui::QuantitySpinBox::setUnit(), MeshPartGui::Ui_CrossSections::setupUi(), Gui::QuantitySpinBox::setValue(), and MeshPartGui::Ui_CrossSections::spinEpsilon.
~CrossSections()
CrossSections::~CrossSections ()
Member Function Documentation
accept()
void CrossSections::accept (void)
References apply().
Referenced by MeshPartGui::TaskCrossSections::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
apply()
void CrossSections::apply ()
References Gui::Command::App, draftgeoutils.faces::bind(), MeshPartGui::Ui_CrossSections::checkBoxConnect, Base::Persistence::getClassTypeId(), draftutils.utils::getObjectsOfType, Base::Quantity::getValue(), Mesh::PropertyMeshKernel::getValue(), Mesh::Feature::Mesh, MeshPartGui::Ui_CrossSections::position, MeshPartGui::MeshCrossSection::section(), MeshPartGui::Ui_CrossSections::sectionsBox, Gui::Selection(), MeshPartGui::Ui_CrossSections::spinEpsilon, MeshCore::MeshKernel::Transform(), and Gui::QuantitySpinBox::value.
Referenced by accept(), and MeshPartGui::TaskCrossSections::clicked().
changeEvent()
void CrossSections::changeEvent (QEvent * e) protected
References MeshPartGui::Ui_CrossSections::retranslateUi().
keyPressEvent()
void CrossSections::keyPressEvent (QKeyEvent * ke) protected
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/MeshPart/Gui/CrossSections.h
FreeCAD/src/Mod/MeshPart/Gui/CrossSections.cpp