FreeCAD: ModelRefine::FaceTypedCylinder Class Reference
ModelRefine::FaceTypedCylinder Class Reference
#include <modelRefine.h>
Public Member Functions
virtual TopoDS_Face buildFace (const FaceVectorType &faces) const
virtual GeomAbs_SurfaceType getType () const
virtual bool isEqual (const TopoDS_Face &faceOne, const TopoDS_Face &faceTwo) const
virtual TopoDS_Face buildFace (const FaceVectorType &faces) const =0
virtual GeomAbs_SurfaceType getType () const =0
virtual bool isEqual (const TopoDS_Face &faceOne, const TopoDS_Face &faceTwo) const =0
Protected Member Functions
virtual void boundarySplit (const FaceVectorType &facesIn, std::vector< EdgeVectorType > &boundariesOut) const
Protected Member Functions inherited from ModelRefine::FaceTypedBase
virtual void boundarySplit (const FaceVectorType &facesIn, std::vector< EdgeVectorType > &boundariesOut) const
FaceTypedBase (const GeomAbs_SurfaceType &typeIn)
Friends
FaceTypedCylinder & getCylinderObject ()
Additional Inherited Members
Static Public Member Functions inherited from ModelRefine::FaceTypedBase
static GeomAbs_SurfaceType getFaceType (const TopoDS_Face &faceIn)
Protected Attributes inherited from ModelRefine::FaceTypedBase
GeomAbs_SurfaceType surfaceType
Member Function Documentation
boundarySplit()
void FaceTypedCylinder::boundarySplit (const FaceVectorType & facesIn, std::vector< EdgeVectorType > & boundariesOut) const protected virtual
Reimplemented from ModelRefine::FaceTypedBase.
References ModelRefine::boundaryEdges().
Referenced by buildFace().
buildFace()
TopoDS_Face FaceTypedCylinder::buildFace (const FaceVectorType & faces) const virtual
Implements ModelRefine::FaceTypedBase.
References boundarySplit().
getType()
GeomAbs_SurfaceType FaceTypedCylinder::getType (void) const virtual
Implements ModelRefine::FaceTypedBase.
Referenced by PathScripts.PathToolEdit.ToolEditor::updateToolType(), and PathScripts.PathToolEdit.ToolEditor::updateUI().
isEqual()
bool FaceTypedCylinder::isEqual (const TopoDS_Face & faceOne, const TopoDS_Face & faceTwo) const virtual
Implements ModelRefine::FaceTypedBase.
Friends And Related Function Documentation
getCylinderObject
FaceTypedCylinder & getCylinderObject () friend
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/App/modelRefine.h
FreeCAD/src/Mod/Part/App/modelRefine.cpp