FreeCAD: MED::TTMeshValue< TValueType > Struct Template Reference
MED::TTMeshValue< TValueType > Struct Template Reference
The class is a helper one. It provide safe and flexible way to get access to values for a MED TimeStamp.
#include <MED_Structures.hxx>
Public Types
typedef TCSlice< TElement > TCValueSlice
typedef TVector< TCValueSlice > TCValueSliceArr
typedef TValueType::value_type TElement
typedef TValueType TValue
typedef TSlice< TElement > TValueSlice
typedef TVector< TValueSlice > TValueSliceArr
Public Member Functions
void Allocate (TInt theNbElem, TInt theNbGauss, TInt theNbComp, EModeSwitch theMode=eFULL_INTERLACE)
Initialize the class.
TValueSliceArr GetCompValueSliceArr (TInt theElemId)
Iteration through components by corresponding Gauss Points.
TCValueSliceArr GetCompValueSliceArr (TInt theElemId) const
Iteration through components by corresponding Gauss Points.
TValueSliceArr GetGaussValueSliceArr (TInt theElemId)
Iteration through Gauss Points by their components.
TCValueSliceArr GetGaussValueSliceArr (TInt theElemId) const
Iteration through Gauss Points by their components.
virtual TElement * GetPointer ()
Returns bare pointer on the internal value representation.
virtual const TElement * GetPointer () const
Returns bare pointer on the internal value representation.
virtual unsigned char * GetValuePtr ()
Returns bare pointer on the internal value representation.
Public Member Functions inherited from MED::TMeshValueBase
void Allocate (TInt theNbElem, TInt theNbGauss, TInt theNbComp, EModeSwitch theMode=eFULL_INTERLACE)
Initialize the class.
size_t GetNbGauss () const
Returns number of Gauss Points bounded with the value.
size_t GetNbVal () const
Returns MED interpretation of the value size.
size_t GetSize () const
Returns size of the value container.
size_t GetStep () const
Returns step inside of the data array.
virtual unsigned char * GetValuePtr ()=0
Returns bare pointer on the internal value representation.
TMeshValueBase ()
Public Member Functions inherited from MED::TModeSwitchInfo
EModeSwitch GetModeSwitch () const
TModeSwitchInfo ()
To construct instance of the class by default.
TModeSwitchInfo (EModeSwitch theModeSwitch)
To construct instance of the class.
Public Member Functions inherited from MED::TBase
virtual ~TBase ()
Public Attributes
TValue myValue
Public Attributes inherited from MED::TMeshValueBase
TInt myNbComp
TInt myNbElem
TInt myNbGauss
TInt myStep
Public Attributes inherited from MED::TModeSwitchInfo
EModeSwitch myModeSwitch
Keeps the.
Detailed Description
template<class TValueType>
struct MED::TTMeshValue< TValueType >
The class is a helper one. It provide safe and flexible way to get access to values for a MED TimeStamp.
Member Typedef Documentation
TCValueSlice
template<class TValueType > typedef TCSlice<TElement> MED::TTMeshValue< TValueType >::TCValueSlice
TCValueSliceArr
template<class TValueType > typedef TVector<TCValueSlice> MED::TTMeshValue< TValueType >::TCValueSliceArr
TElement
template<class TValueType > typedef TValueType::value_type MED::TTMeshValue< TValueType >::TElement
TValue
template<class TValueType > typedef TValueType MED::TTMeshValue< TValueType >::TValue
TValueSlice
template<class TValueType > typedef TSlice<TElement> MED::TTMeshValue< TValueType >::TValueSlice
TValueSliceArr
template<class TValueType > typedef TVector<TValueSlice> MED::TTMeshValue< TValueType >::TValueSliceArr
Member Function Documentation
Allocate()
template<class TValueType > void MED::TTMeshValue< TValueType >::Allocate (TInt theNbElem, TInt theNbGauss, TInt theNbComp, EModeSwitch theMode = eFULL_INTERLACE)
Initialize the class.
References MED::TMeshValueBase::Allocate(), MED::TMeshValueBase::GetStep(), and MED::TTMeshValue< TValueType >::myValue.
GetCompValueSliceArr() [1/2]
template<class TValueType > TValueSliceArr MED::TTMeshValue< TValueType >::GetCompValueSliceArr (TInt theElemId)
Iteration through components by corresponding Gauss Points.
References MED::eFULL_INTERLACE, MED::TModeSwitchInfo::GetModeSwitch(), MED::TMeshValueBase::myNbComp, MED::TMeshValueBase::myNbGauss, MED::TMeshValueBase::myStep, and MED::TTMeshValue< TValueType >::myValue.
GetCompValueSliceArr() [2/2]
template<class TValueType > TCValueSliceArr MED::TTMeshValue< TValueType >::GetCompValueSliceArr (TInt theElemId) const
Iteration through components by corresponding Gauss Points.
References MED::eFULL_INTERLACE, MED::TModeSwitchInfo::GetModeSwitch(), MED::TMeshValueBase::myNbComp, MED::TMeshValueBase::myNbGauss, MED::TMeshValueBase::myStep, and MED::TTMeshValue< TValueType >::myValue.
GetGaussValueSliceArr() [1/2]
template<class TValueType > TValueSliceArr MED::TTMeshValue< TValueType >::GetGaussValueSliceArr (TInt theElemId)
Iteration through Gauss Points by their components.
References MED::eFULL_INTERLACE, MED::TModeSwitchInfo::GetModeSwitch(), MED::TMeshValueBase::myNbComp, MED::TMeshValueBase::myNbGauss, MED::TMeshValueBase::myStep, and MED::TTMeshValue< TValueType >::myValue.
GetGaussValueSliceArr() [2/2]
template<class TValueType > TCValueSliceArr MED::TTMeshValue< TValueType >::GetGaussValueSliceArr (TInt theElemId) const
Iteration through Gauss Points by their components.
References MED::eFULL_INTERLACE, MED::TModeSwitchInfo::GetModeSwitch(), MED::TMeshValueBase::myNbComp, MED::TMeshValueBase::myNbGauss, MED::TMeshValueBase::myStep, and MED::TTMeshValue< TValueType >::myValue.
GetPointer() [1/2]
template<class TValueType > virtual TElement * MED::TTMeshValue< TValueType >::GetPointer () virtual
Returns bare pointer on the internal value representation.
References MED::TTMeshValue< TValueType >::myValue.
GetPointer() [2/2]
template<class TValueType > virtual const TElement * MED::TTMeshValue< TValueType >::GetPointer () const virtual
Returns bare pointer on the internal value representation.
References MED::TTMeshValue< TValueType >::myValue.
GetValuePtr()
template<class TValueType > virtual unsigned char * MED::TTMeshValue< TValueType >::GetValuePtr () virtual
Returns bare pointer on the internal value representation.
Implements MED::TMeshValueBase.
Member Data Documentation
myValue
template<class TValueType > TValue MED::TTMeshValue< TValueType >::myValue
Referenced by MED::TTMeshValue< TValueType >::Allocate(), MED::TTMeshValue< TValueType >::GetCompValueSliceArr(), MED::TTMeshValue< TValueType >::GetGaussValueSliceArr(), and MED::TTMeshValue< TValueType >::GetPointer().
The documentation for this struct was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/inc/MED_Structures.hxx