FreeCAD: PartGui::DlgPrimitives Class Reference
PartGui::DlgPrimitives Class Reference
#include <DlgPrimitives.h>
Public Member Functions
void accept (const QString &)
void createPrimitive (const QString &)
DlgPrimitives (QWidget *parent=nullptr, Part::Primitive *feature=nullptr)
void reject ()
~DlgPrimitives ()
Constructor & Destructor Documentation
DlgPrimitives()
DlgPrimitives::DlgPrimitives (QWidget * parent = nullptr, Part::Primitive * feature = nullptr)
References Part::Cylinder::Angle, Part::Cone::Angle, Part::Helix::Angle, Part::Sphere::Angle1, Part::Ellipsoid::Angle1, Part::Torus::Angle1, Part::Ellipse::Angle1, Part::Sphere::Angle2, Part::Ellipsoid::Angle2, Part::Torus::Angle2, Part::Ellipse::Angle2, Part::Sphere::Angle3, Part::Ellipsoid::Angle3, Part::Torus::Angle3, Part::Prism::Circumradius, Part::RegularPolygon::Circumradius, draftgeoutils.intersections::connect(), Gui::Command::Doc, DraftVecUtils::find(), Part::PrismExtension::FirstAngle, Base::Persistence::getClassTypeId(), App::PropertyQuantity::getQuantityValue(), Base::Persistence::getTypeId(), Base::Quantity::getValue(), App::PropertyInteger::getValue(), App::PropertyEnumeration::getValue(), Part::Spiral::Growth, Part::Cylinder::Height, Part::Prism::Height, Part::Cone::Height, Part::Helix::Height, Part::Helix::LocalCoord, Part::Ellipse::MajorRadius, Part::Ellipse::MinorRadius, Part::Helix::Pitch, Part::Prism::Polygon, Part::RegularPolygon::Polygon, Part::Sphere::Radius, Part::Cylinder::Radius, Part::Helix::Radius, Part::Spiral::Radius, Part::Ellipsoid::Radius1, Part::Cone::Radius1, Part::Torus::Radius1, Part::Ellipsoid::Radius2, Part::Cone::Radius2, Part::Torus::Radius2, Part::Ellipsoid::Radius3, Part::Spiral::Rotations, Part::PrismExtension::SecondAngle, Part::Line::X1, Part::Line::X2, Part::Wedge::X2max, Part::Wedge::X2min, Part::Wedge::Xmax, Part::Wedge::Xmin, Part::Line::Y1, Part::Line::Y2, Part::Wedge::Ymax, Part::Wedge::Ymin, Part::Line::Z1, Part::Line::Z2, Part::Wedge::Z2max, Part::Wedge::Z2min, Part::Wedge::Zmax, and Part::Wedge::Zmin.
~DlgPrimitives()
DlgPrimitives::~DlgPrimitives ()
Member Function Documentation
accept()
void DlgPrimitives::accept (const QString & placement)
References Gui::Command::App, App::DocumentObjectWeakPtrT::expired(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), and Base::Persistence::getTypeId().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
createPrimitive()
void DlgPrimitives::createPrimitive (const QString & placement)
References Gui::Application::activeDocument(), Gui::Document::commitCommand(), Gui::Command::Doc, App::Application::getActiveDocument(), App::GetApplication(), PartGui::getAutoGroupCommandStr(), Gui::Command::Gui, Gui::Application::Instance, and Gui::Document::openCommand().
reject()
void DlgPrimitives::reject (void)
References App::DocumentObjectWeakPtrT::expired(), and App::DocumentObject::getDocument().
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/DlgPrimitives.h
FreeCAD/src/Mod/Part/Gui/DlgPrimitives.cpp