FreeCAD: Part::GeometryPy Class Reference
Part::GeometryPy Class Reference
The python export class for Geometry.
#include <GeometryPy.h>
Public Types
typedef Geometry * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
GeometryPy (Geometry *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of GeometryPy.
static PyMethodDef Methods []
Methods structure of GeometryPy.
static PyTypeObject Type
Type structure of GeometryPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~GeometryPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * clone (PyObject *args)
implementer for the clone() method
PyObject * hasExtensionOfType (PyObject *args)
implementer for the hasExtensionOfType() method
PyObject * hasExtensionOfName (PyObject *args)
implementer for the hasExtensionOfName() method
PyObject * getExtensionOfType (PyObject *args)
implementer for the getExtensionOfType() method
PyObject * getExtensionOfName (PyObject *args)
implementer for the getExtensionOfName() method
PyObject * setExtension (PyObject *args)
implementer for the setExtension() method
PyObject * deleteExtensionOfType (PyObject *args)
implementer for the deleteExtensionOfType() method
PyObject * deleteExtensionOfName (PyObject *args)
implementer for the deleteExtensionOfName() method
PyObject * getExtensions (PyObject *args)
implementer for the getExtensions() method
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_clone (PyObject *self, PyObject *args)
callback for the clone() method
static PyObject * staticCallback_hasExtensionOfType (PyObject *self, PyObject *args)
callback for the hasExtensionOfType() method
static PyObject * staticCallback_hasExtensionOfName (PyObject *self, PyObject *args)
callback for the hasExtensionOfName() method
static PyObject * staticCallback_getExtensionOfType (PyObject *self, PyObject *args)
callback for the getExtensionOfType() method
static PyObject * staticCallback_getExtensionOfName (PyObject *self, PyObject *args)
callback for the getExtensionOfName() method
static PyObject * staticCallback_setExtension (PyObject *self, PyObject *args)
callback for the setExtension() method
static PyObject * staticCallback_deleteExtensionOfType (PyObject *self, PyObject *args)
callback for the deleteExtensionOfType() method
static PyObject * staticCallback_deleteExtensionOfName (PyObject *self, PyObject *args)
callback for the deleteExtensionOfName() method
static PyObject * staticCallback_getExtensions (PyObject *self, PyObject *args)
callback for the getExtensions() method
callbacks and implementers for the python object attributes
Py::String getTag (void) const
getter for the Tag attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geometry * getGeometryPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Geometry.
Member Typedef Documentation
PointerType
typedef Geometry* Part::GeometryPy::PointerType
Constructor & Destructor Documentation
~GeometryPy()
GeometryPy::~GeometryPy () protected
GeometryPy()
GeometryPy::GeometryPy (Geometry * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
clone()
PyObject * GeometryPy::clone (PyObject * args)
implementer for the clone() method
References Part::Geometry::clone(), getGeometryPtr(), and GetType().
Referenced by ArchPanel.CommandPanelSheet::Activated(), copy(), ArchComponent.Component::execute(), ArchCurtainWall.CurtainWall::execute(), ArchTruss.Truss::execute(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated(), staticCallback_clone(), and PathTests.TestPathHelix.TestPathHelix::test04().
copy()
PyObject * GeometryPy::copy (PyObject * args)
implementer for the copy() method
References clone(), Part::Geometry::copy(), getGeometryPtr(), and GetType().
Referenced by staticCallback_copy().
deleteExtensionOfName()
PyObject * GeometryPy::deleteExtensionOfName (PyObject * args)
implementer for the deleteExtensionOfName() method
References Part::Geometry::deleteExtension(), getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_deleteExtensionOfName().
deleteExtensionOfType()
PyObject * GeometryPy::deleteExtensionOfType (PyObject * args)
implementer for the deleteExtensionOfType() method
References Base::Type::badType(), Part::Geometry::deleteExtension(), Base::Type::fromName(), getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_deleteExtensionOfType().
getCustomAttributes()
PyObject * GeometryPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getExtensionOfName()
PyObject * GeometryPy::getExtensionOfName (PyObject * args)
implementer for the getExtensionOfName() method
References getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getExtensionOfName().
getExtensionOfType()
PyObject * GeometryPy::getExtensionOfType (PyObject * args)
implementer for the getExtensionOfType() method
References Base::Type::badType(), Base::Type::fromName(), getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getExtensionOfType().
getExtensions()
PyObject * GeometryPy::getExtensions (PyObject * args)
implementer for the getExtensions() method
References Part::Geometry::getExtensions(), getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getExtensions().
getGeometryPtr()
Geometry * GeometryPy::getGeometryPtr (void) const
getter for the object handled by this class
Referenced by Part::GeometryCurvePy::approximateBSpline(), Part::BezierSurfacePy::bounds(), Part::BSplineSurfacePy::bounds(), Part::GeometrySurfacePy::bounds(), Part::BSplineSurfacePy::buildFromNSections(), Part::GeometryCurvePy::centerOfCurvature(), clone(), Part::ParabolaPy::compute(), Part::GeometryCurvePy::continuityWith(), copy(), Part::GeometryCurvePy::curvature(), deleteExtensionOfName(), deleteExtensionOfType(), Part::GeometryCurvePy::discretize(), Part::BezierSurfacePy::exchangeUV(), Part::BSplineSurfacePy::exchangeUV(), Part::ConePy::getAxis(), Part::CylinderPy::getAxis(), Part::PlanePy::getAxis(), Part::SpherePy::getAxis(), Part::ToroidPy::getAxis(), Part::OffsetCurvePy::getBasisCurve(), Part::SurfaceOfExtrusionPy::getBasisCurve(), Part::SurfaceOfRevolutionPy::getBasisCurve(), Part::OffsetSurfacePy::getBasisSurface(), Part::RectangularTrimmedSurfacePy::getBasisSurface(), Part::GeometryCurvePy::getContinuity(), Part::GeometrySurfacePy::getContinuity(), Part::GeometryCurvePy::getD0(), Part::GeometrySurfacePy::getD0(), Part::GeometryCurvePy::getD1(), Part::GeometryCurvePy::getD2(), Part::GeometryCurvePy::getD3(), Part::BezierCurvePy::getDegree(), Part::BSplineCurvePy::getDegree(), Part::SurfaceOfExtrusionPy::getDirection(), Part::SurfaceOfRevolutionPy::getDirection(), Part::GeometryCurvePy::getDN(), Part::GeometrySurfacePy::getDN(), Part::BezierCurvePy::getEndPoint(), Part::BSplineCurvePy::getEndPoint(), getExtensionOfName(), getExtensionOfType(), getExtensions(), Part::GeometryCurvePy::getFirstParameter(), Part::BSplineCurvePy::getFirstUKnotIndex(), Part::BSplineSurfacePy::getFirstUKnotIndex(), Part::BSplineSurfacePy::getFirstVKnotIndex(), Part::ParabolaPy::getFocal(), Part::ParabolaPy::getFocus(), Part::BSplineCurvePy::getKnot(), Part::BSplineCurvePy::getKnots(), Part::BSplineCurvePy::getKnotSequence(), Part::GeometryCurvePy::getLastParameter(), Part::BSplineCurvePy::getLastUKnotIndex(), Part::BSplineSurfacePy::getLastUKnotIndex(), Part::BSplineSurfacePy::getLastVKnotIndex(), Part::SurfaceOfRevolutionPy::getLocation(), Part::BezierCurvePy::getMaxDegree(), Part::BezierSurfacePy::getMaxDegree(), Part::BSplineCurvePy::getMaxDegree(), Part::BSplineSurfacePy::getMaxDegree(), Part::BSplineCurvePy::getMultiplicities(), Part::BSplineCurvePy::getMultiplicity(), Part::BSplineCurvePy::getNbKnots(), Part::BezierCurvePy::getNbPoles(), Part::BSplineCurvePy::getNbPoles(), Part::BSplineSurfacePy::getNbUKnots(), Part::BezierSurfacePy::getNbUPoles(), Part::BSplineSurfacePy::getNbUPoles(), Part::BSplineSurfacePy::getNbVKnots(), Part::BezierSurfacePy::getNbVPoles(), Part::BSplineSurfacePy::getNbVPoles(), Part::OffsetCurvePy::getOffsetDirection(), Part::OffsetCurvePy::getOffsetValue(), Part::OffsetSurfacePy::getOffsetValue(), Part::ParabolaPy::getParameter(), Part::BezierCurvePy::getPole(), Part::BezierSurfacePy::getPole(), Part::BSplineCurvePy::getPole(), Part::BSplineSurfacePy::getPole(), Part::BezierCurvePy::getPoles(), Part::BezierSurfacePy::getPoles(), Part::BSplineCurvePy::getPoles(), Part::BSplineSurfacePy::getPoles(), Part::BSplineCurvePy::getPolesAndWeights(), Part::BSplineSurfacePy::getPolesAndWeights(), Part::getPyShapes(), Part::BezierCurvePy::getResolution(), Part::BezierSurfacePy::getResolution(), Part::BSplineCurvePy::getResolution(), Part::BSplineSurfacePy::getResolution(), Part::GeometryCurvePy::getRotation(), Part::GeometrySurfacePy::getRotation(), Part::BezierCurvePy::getStartPoint(), Part::BSplineCurvePy::getStartPoint(), getTag(), Part::BezierSurfacePy::getUDegree(), Part::BSplineSurfacePy::getUDegree(), Part::BSplineSurfacePy::getUKnot(), Part::BSplineSurfacePy::getUKnots(), Part::BSplineSurfacePy::getUKnotSequence(), Part::BSplineSurfacePy::getUMultiplicities(), Part::BSplineSurfacePy::getUMultiplicity(), Part::BezierSurfacePy::getVDegree(), Part::BSplineSurfacePy::getVDegree(), Part::BSplineSurfacePy::getVKnot(), Part::BSplineSurfacePy::getVKnots(), Part::BSplineSurfacePy::getVKnotSequence(), Part::BSplineSurfacePy::getVMultiplicities(), Part::BSplineSurfacePy::getVMultiplicity(), Part::BezierCurvePy::getWeight(), Part::BezierSurfacePy::getWeight(), Part::BSplineCurvePy::getWeight(), Part::BSplineSurfacePy::getWeight(), Part::BezierCurvePy::getWeights(), Part::BezierSurfacePy::getWeights(), Part::BSplineCurvePy::getWeights(), Part::BSplineSurfacePy::getWeights(), hasExtensionOfName(), hasExtensionOfType(), Part::BezierCurvePy::increase(), Part::BezierSurfacePy::increase(), Part::BSplineCurvePy::increaseDegree(), Part::BSplineSurfacePy::increaseDegree(), Part::BSplineCurvePy::increaseMultiplicity(), Part::BSplineSurfacePy::increaseUMultiplicity(), Part::BSplineSurfacePy::increaseVMultiplicity(), Part::BSplineCurvePy::incrementMultiplicity(), Part::BSplineSurfacePy::incrementUMultiplicity(), Part::BSplineSurfacePy::incrementVMultiplicity(), Part::BSplineCurvePy::insertKnot(), Part::BSplineCurvePy::insertKnots(), Part::BezierCurvePy::insertPoleAfter(), Part::BezierCurvePy::insertPoleBefore(), Part::BezierSurfacePy::insertPoleColAfter(), Part::BezierSurfacePy::insertPoleColBefore(), Part::BezierSurfacePy::insertPoleRowAfter(), Part::BezierSurfacePy::insertPoleRowBefore(), Part::BSplineSurfacePy::insertUKnot(), Part::BSplineSurfacePy::insertUKnots(), Part::BSplineSurfacePy::insertVKnot(), Part::BSplineSurfacePy::insertVKnots(), Part::BezierCurvePy::interpolate(), Part::GeometryCurvePy::intersect(), Part::GeometrySurfacePy::intersect(), Part::GeometryCurvePy::intersect2d(), Part::GeometryCurvePy::intersectCS(), Part::GeometrySurfacePy::intersectSS(), Part::BezierCurvePy::isClosed(), Part::BSplineCurvePy::isClosed(), Part::GeometryCurvePy::isClosed(), Part::BezierCurvePy::isPeriodic(), Part::BSplineCurvePy::isPeriodic(), Part::GeometryCurvePy::isPeriodic(), Part::GeometrySurfacePy::isPlanar(), Part::BezierCurvePy::isRational(), Part::BSplineCurvePy::isRational(), Part::BezierSurfacePy::isUClosed(), Part::BSplineSurfacePy::isUClosed(), Part::GeometrySurfacePy::isUClosed(), Part::BezierSurfacePy::isUPeriodic(), Part::BSplineSurfacePy::isUPeriodic(), Part::GeometrySurfacePy::isUPeriodic(), Part::BezierSurfacePy::isURational(), Part::BSplineSurfacePy::isURational(), Part::BezierSurfacePy::isVClosed(), Part::BSplineSurfacePy::isVClosed(), Part::GeometrySurfacePy::isVClosed(), Part::BezierSurfacePy::isVPeriodic(), Part::BSplineSurfacePy::isVPeriodic(), Part::GeometrySurfacePy::isVPeriodic(), Part::BezierSurfacePy::isVRational(), Part::BSplineSurfacePy::isVRational(), Part::GeometryCurvePy::length(), Part::GeometryCurvePy::makeRuledSurface(), mirror(), Part::BSplineCurvePy::movePoint(), Part::BSplineSurfacePy::movePoint(), Part::GeometryCurvePy::normal(), Part::GeometryCurvePy::parameter(), Part::GeometrySurfacePy::parameter(), Part::GeometryCurvePy::parameterAtDistance(), Part::GeometryCurvePy::period(), Part::GeometrySurfacePy::projectPoint(), Part::ConePy::PyInit(), Part::OffsetCurvePy::PyInit(), Part::OffsetSurfacePy::PyInit(), Part::PlanePy::PyInit(), Part::PlateSurfacePy::PyInit(), Part::SurfaceOfExtrusionPy::PyInit(), Part::SurfaceOfRevolutionPy::PyInit(), Part::BSplineCurvePy::removeKnot(), Part::BezierCurvePy::removePole(), Part::BezierSurfacePy::removePoleCol(), Part::BezierSurfacePy::removePoleRow(), Part::BSplineSurfacePy::removeUKnot(), Part::BSplineSurfacePy::removeVKnot(), Part::BSplineSurfacePy::reparametrize(), Part::GeometryCurvePy::reverse(), Part::GeometryCurvePy::reversedParameter(), rotate(), scale(), Part::BezierCurvePy::segment(), Part::BezierSurfacePy::segment(), Part::BSplineCurvePy::segment(), Part::BSplineSurfacePy::segment(), Part::ConePy::setAxis(), Part::CylinderPy::setAxis(), Part::PlanePy::setAxis(), Part::SpherePy::setAxis(), Part::ToroidPy::setAxis(), Part::OffsetCurvePy::setBasisCurve(), Part::SurfaceOfExtrusionPy::setBasisCurve(), Part::SurfaceOfRevolutionPy::setBasisCurve(), Part::OffsetSurfacePy::setBasisSurface(), Part::SurfaceOfExtrusionPy::setDirection(), Part::SurfaceOfRevolutionPy::setDirection(), setExtension(), Part::ParabolaPy::setFocal(), Sketcher::ExternalGeometryFacadePy::setGeometry(), Sketcher::GeometryFacadePy::setGeometry(), Part::BSplineCurvePy::setKnot(), Part::BSplineCurvePy::setKnots(), Part::SurfaceOfRevolutionPy::setLocation(), Part::BSplineCurvePy::setNotPeriodic(), Part::OffsetCurvePy::setOffsetDirection(), Part::OffsetCurvePy::setOffsetValue(), Part::OffsetSurfacePy::setOffsetValue(), Part::BSplineCurvePy::setOrigin(), Part::BSplineCurvePy::setPeriodic(), Part::BezierCurvePy::setPole(), Part::BezierSurfacePy::setPole(), Part::BSplineCurvePy::setPole(), Part::BSplineSurfacePy::setPole(), Part::BezierSurfacePy::setPoleCol(), Part::BSplineSurfacePy::setPoleCol(), Part::BezierSurfacePy::setPoleRow(), Part::BSplineSurfacePy::setPoleRow(), Part::PropertyGeometryList::setPyObject(), Part::RectangularTrimmedSurfacePy::setTrim(), Part::BSplineSurfacePy::setUKnot(), Part::BSplineSurfacePy::setUKnots(), Part::BSplineSurfacePy::setUNotPeriodic(), Part::BSplineSurfacePy::setUOrigin(), Part::BSplineSurfacePy::setUPeriodic(), Part::BSplineSurfacePy::setVKnot(), Part::BSplineSurfacePy::setVKnots(), Part::BSplineSurfacePy::setVNotPeriodic(), Part::BSplineSurfacePy::setVOrigin(), Part::BSplineSurfacePy::setVPeriodic(), Part::BezierCurvePy::setWeight(), Part::BezierSurfacePy::setWeight(), Part::BSplineCurvePy::setWeight(), Part::BSplineSurfacePy::setWeight(), Part::BezierSurfacePy::setWeightCol(), Part::BSplineSurfacePy::setWeightCol(), Part::BezierSurfacePy::setWeightRow(), Part::BSplineSurfacePy::setWeightRow(), Part::GeometryCurvePy::tangent(), Part::GeometrySurfacePy::tangent(), Part::GeometryCurvePy::toBSpline(), Part::GeometrySurfacePy::toBSpline(), Part::GeometryCurvePy::toNurbs(), Part::GeometryCurvePy::toShape(), Part::GeometrySurfacePy::toShape(), transform(), translate(), Part::GeometryCurvePy::trim(), Part::GeometrySurfacePy::uIso(), Part::GeometrySurfacePy::UPeriod(), Part::GeometryCurvePy::value(), Part::GeometrySurfacePy::value(), Part::GeometrySurfacePy::vIso(), and Part::GeometrySurfacePy::VPeriod().
getTag()
Py::String GeometryPy::getTag (void) const
getter for the Tag attribute
References getGeometryPtr().
Referenced by staticCallback_getTag().
GetType()
virtual PyTypeObject* Part::GeometryPy::GetType (void) virtual
Reimplemented from Base::PersistencePy.
Reimplemented in Part::TrimmedCurvePy, Part::ToroidPy, Part::SurfaceOfRevolutionPy, Part::SurfaceOfExtrusionPy, Part::SpherePy, Part::RectangularTrimmedSurfacePy, Part::PointPy, Part::PlateSurfacePy, Part::PlanePy, Part::ParabolaPy, Part::OffsetSurfacePy, Part::OffsetCurvePy, Part::LineSegmentPy, Part::LinePy, Part::HyperbolaPy, Part::GeometrySurfacePy, Part::GeometryCurvePy, Part::EllipsePy, Part::CylinderPy, Part::ConicPy, Part::ConePy, Part::CirclePy, Part::BSplineSurfacePy, Part::BSplineCurvePy, Part::BoundedCurvePy, Part::BezierSurfacePy, Part::BezierCurvePy, Part::ArcPy, Part::ArcOfParabolaPy, Part::ArcOfHyperbolaPy, Part::ArcOfEllipsePy, Part::ArcOfConicPy, and Part::ArcOfCirclePy.
Referenced by clone(), and copy().
hasExtensionOfName()
PyObject * GeometryPy::hasExtensionOfName (PyObject * args)
implementer for the hasExtensionOfName() method
References getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_hasExtensionOfName().
hasExtensionOfType()
PyObject * GeometryPy::hasExtensionOfType (PyObject * args)
implementer for the hasExtensionOfType() method
References Base::Type::badType(), Base::Type::fromName(), getGeometryPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_hasExtensionOfType().
mirror()
PyObject * GeometryPy::mirror (PyObject * args)
implementer for the mirror() method
References getGeometryPtr(), Part::Geometry::mirror(), Part::PartExceptionOCCError, Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_mirror().
PyInit()
int GeometryPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PersistencePy.
Reimplemented in Part::TrimmedCurvePy, Part::ToroidPy, Part::SurfaceOfRevolutionPy, Part::SurfaceOfExtrusionPy, Part::SpherePy, Part::RectangularTrimmedSurfacePy, Part::PointPy, Part::PlateSurfacePy, Part::PlanePy, Part::ParabolaPy, Part::OffsetSurfacePy, Part::OffsetCurvePy, Part::LineSegmentPy, Part::LinePy, Part::HyperbolaPy, Part::GeometrySurfacePy, Part::GeometryCurvePy, Part::EllipsePy, Part::CylinderPy, Part::ConicPy, Part::ConePy, Part::CirclePy, Part::BSplineSurfacePy, Part::BSplineCurvePy, Part::BoundedCurvePy, Part::BezierSurfacePy, Part::BezierCurvePy, Part::ArcPy, Part::ArcOfParabolaPy, Part::ArcOfHyperbolaPy, Part::ArcOfEllipsePy, Part::ArcOfConicPy, and Part::ArcOfCirclePy.
PyMake()
PyObject * GeometryPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string GeometryPy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
rotate()
PyObject * GeometryPy::rotate (PyObject * args)
implementer for the rotate() method
References getGeometryPtr(), Part::Geometry::rotate(), and Base::PlacementPy::Type.
Referenced by PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart(), draftguitools.gui_rotate.Rotate::numericRadius(), ArchSectionPlane.SectionPlaneTaskPanel::rotateX(), ArchSectionPlane.SectionPlaneTaskPanel::rotateY(), ArchSectionPlane.SectionPlaneTaskPanel::rotateZ(), and staticCallback_rotate().
scale()
PyObject * GeometryPy::scale (PyObject * args)
implementer for the scale() method
References getGeometryPtr(), Part::PartExceptionOCCError, Part::Geometry::scale(), Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by automotive_design.cartesian_transformation_operator::scl(), config_control_design.cartesian_transformation_operator::scl(), ifc2x3.ifccartesiantransformationoperator::scl(), ifc4.ifccartesiantransformationoperator::scl(), and staticCallback_scale().
setCustomAttributes()
int GeometryPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setExtension()
PyObject * GeometryPy::setExtension (PyObject * args)
implementer for the setExtension() method
References getGeometryPtr(), draftfunctions.move::move(), Part::PartExceptionOCCError, Part::Geometry::setExtension(), and Part::GeometryExtensionPy::Type.
Referenced by staticCallback_setExtension().
staticCallback_clone()
PyObject * GeometryPy::staticCallback_clone (PyObject * self, PyObject * args) static
callback for the clone() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, clone(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_copy()
PyObject * GeometryPy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copy(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_deleteExtensionOfName()
PyObject * GeometryPy::staticCallback_deleteExtensionOfName (PyObject * self, PyObject * args) static
callback for the deleteExtensionOfName() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, deleteExtensionOfName(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_deleteExtensionOfType()
PyObject * GeometryPy::staticCallback_deleteExtensionOfType (PyObject * self, PyObject * args) static
callback for the deleteExtensionOfType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, deleteExtensionOfType(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getExtensionOfName()
PyObject * GeometryPy::staticCallback_getExtensionOfName (PyObject * self, PyObject * args) static
callback for the getExtensionOfName() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getExtensionOfName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getExtensionOfType()
PyObject * GeometryPy::staticCallback_getExtensionOfType (PyObject * self, PyObject * args) static
callback for the getExtensionOfType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getExtensionOfType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getExtensions()
PyObject * GeometryPy::staticCallback_getExtensions (PyObject * self, PyObject * args) static
callback for the getExtensions() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getExtensions(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTag()
PyObject * GeometryPy::staticCallback_getTag (PyObject * self, void * closure) static
getter callback for the Tag attribute
References Base::BaseExceptionFreeCADError, getTag(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_hasExtensionOfName()
PyObject * GeometryPy::staticCallback_hasExtensionOfName (PyObject * self, PyObject * args) static
callback for the hasExtensionOfName() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hasExtensionOfName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_hasExtensionOfType()
PyObject * GeometryPy::staticCallback_hasExtensionOfType (PyObject * self, PyObject * args) static
callback for the hasExtensionOfType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hasExtensionOfType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_mirror()
PyObject * GeometryPy::staticCallback_mirror (PyObject * self, PyObject * args) static
callback for the mirror() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), mirror(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_rotate()
PyObject * GeometryPy::staticCallback_rotate (PyObject * self, PyObject * args) static
callback for the rotate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), rotate(), and Base::PyObjectBase::startNotify().
staticCallback_scale()
PyObject * GeometryPy::staticCallback_scale (PyObject * self, PyObject * args) static
callback for the scale() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), scale(), and Base::PyObjectBase::startNotify().
staticCallback_setExtension()
PyObject * GeometryPy::staticCallback_setExtension (PyObject * self, PyObject * args) static
callback for the setExtension() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setExtension(), and Base::PyObjectBase::startNotify().
staticCallback_setTag()
int GeometryPy::staticCallback_setTag (PyObject * self, PyObject * value, void * closure) static
setter callback for the Tag attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_transform()
PyObject * GeometryPy::staticCallback_transform (PyObject * self, PyObject * args) static
callback for the transform() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and transform().
staticCallback_translate()
PyObject * GeometryPy::staticCallback_translate (PyObject * self, PyObject * args) static
callback for the translate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and translate().
transform()
PyObject * GeometryPy::transform (PyObject * args)
implementer for the transform() method
References getGeometryPtr(), Part::Geometry::transform(), and Base::MatrixPy::Type.
Referenced by importSVG.svgHandler::applyTrans(), importSVG.svgHandler::characters(), importSVG.svgHandler::endElement(), ArchSite.Compass::locate(), ArchSite.Compass::rotate(), ArchSite.Compass::scale(), and staticCallback_transform().
translate()
PyObject * GeometryPy::translate (PyObject * args)
implementer for the translate() method
References getGeometryPtr(), Part::PartExceptionOCCError, Part::Geometry::translate(), Base::VectorPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_translate().
Member Data Documentation
GetterSetter
PyGetSetDef GeometryPy::GetterSetter static
Initial value:
= {
    {"Tag",
        (getter) staticCallback_getTag,
        (setter) staticCallback_setTag,
        "Gives the tag of the geometry as string.",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of GeometryPy.
Methods
PyMethodDef GeometryPy::Methods static
Methods structure of GeometryPy.
Type
PyTypeObject GeometryPy::Type static
Type structure of GeometryPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), Sketcher::SketchObjectPy::addGeometry(), Sketcher::SketchPy::addGeometry(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), Part::getPyShapes(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), Part::OffsetCurvePy::PyInit(), Part::OffsetSurfacePy::PyInit(), Part::PlateSurfacePy::PyInit(), Part::SurfaceOfExtrusionPy::PyInit(), Part::SurfaceOfRevolutionPy::PyInit(), Part::TopoShapeEdgePy::PyInit(), Part::TopoShapeFacePy::PyInit(), Part::TopoShapePy::PyInit(), Sketcher::ExternalGeometryFacadePy::PyInit(), Sketcher::GeometryFacadePy::PyInit(), draftobjects.layer.Layer::set_properties(), Part::OffsetCurvePy::setBasisCurve(), Part::SurfaceOfExtrusionPy::setBasisCurve(), Part::SurfaceOfRevolutionPy::setBasisCurve(), Part::OffsetSurfacePy::setBasisSurface(), Sketcher::ExternalGeometryFacadePy::setGeometry(), Sketcher::GeometryFacadePy::setGeometry(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeometryPy.h
Sources/FreeCAD/src/Mod/Part/App/GeometryPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeometryPy.cpp