FreeCAD: TechDrawGui::lineAttributes Class Reference
TechDrawGui::lineAttributes Class Reference
#include <TaskSelectLineAttributes.h>
Public Member Functions
int getColor (void) const
App::Color getColorValue (void)
int getStyle (void) const
int getWidth (void) const
float getWidthValue (void)
lineAttributes (void)
void setColor (int)
void setStyle (int)
void setWidth (int)
Constructor & Destructor Documentation
lineAttributes()
lineAttributes::lineAttributes (void)
Member Function Documentation
getColor()
int TechDrawGui::lineAttributes::getColor (void) const
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::getPrefColor(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::setValues().
getColorValue()
App::Color lineAttributes::getColorValue (void)
getStyle()
int TechDrawGui::lineAttributes::getStyle (void) const
Referenced by TechDrawGui::TaskSelectLineAttributes::setUiEdit().
getWidth()
int TechDrawGui::lineAttributes::getWidth (void) const
getWidthValue()
float lineAttributes::getWidthValue (void)
setColor()
void lineAttributes::setColor (int newColor)
setStyle()
void lineAttributes::setStyle (int newStyle)
Referenced by TechDrawGui::TaskSelectLineAttributes::accept().
setWidth()
void lineAttributes::setWidth (int newWidth)
Referenced by ArchStructure.CommandStructuralSystem::Activated().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/TaskSelectLineAttributes.h
FreeCAD/src/Mod/TechDraw/Gui/TaskSelectLineAttributes.cpp