FreeCAD: Gui::SoFCVectorizeU3DAction Class Reference
Gui::SoFCVectorizeU3DAction Class Reference
#include <SoFCVectorizeU3DAction.h>
Public Member Functions
SoU3DVectorOutput * getU3DOutput (void) const
SoFCVectorizeU3DAction (void)
virtual ~SoFCVectorizeU3DAction ()
Static Public Member Functions
static void initClass (void)
Protected Member Functions
virtual void beginTraversal (SoNode *node)
virtual void endTraversal (SoNode *node)
virtual void printBackground (void) const
virtual void printFooter (void) const
virtual void printHeader (void) const
virtual void printItem (const SoVectorizeItem *item) const
virtual void printViewport (void) const
Friends
class SoFCVectorizeU3DActionP
Constructor & Destructor Documentation
SoFCVectorizeU3DAction()
SoFCVectorizeU3DAction::SoFCVectorizeU3DAction (void)
References SoFCVectorizeU3DActionP.
~SoFCVectorizeU3DAction()
SoFCVectorizeU3DAction::~SoFCVectorizeU3DAction () virtual
Member Function Documentation
beginTraversal()
void SoFCVectorizeU3DAction::beginTraversal (SoNode * node) protected virtual
endTraversal()
void SoFCVectorizeU3DAction::endTraversal (SoNode * node) protected virtual
getU3DOutput()
SoU3DVectorOutput * SoFCVectorizeU3DAction::getU3DOutput (void) const
Referenced by printHeader().
initClass()
void SoFCVectorizeU3DAction::initClass (void) static
Referenced by Gui::SoFCDB::init().
printBackground()
void SoFCVectorizeU3DAction::printBackground (void) const protected virtual
printFooter()
void SoFCVectorizeU3DAction::printFooter (void) const protected virtual
printHeader()
void SoFCVectorizeU3DAction::printHeader (void) const protected virtual
References Gui::SoU3DVectorOutput::getFileStream(), getU3DOutput(), and Base::tabs().
printItem()
void SoFCVectorizeU3DAction::printItem (const SoVectorizeItem * item) const protected virtual
References SoVectorizeItem::IMAGE, SoVectorizeItem::LINE, SoVectorizeItem::POINT, SoVectorizeItem::TEXT, SoVectorizeItem::TRIANGLE, and SoVectorizeItem::type.
printViewport()
void SoFCVectorizeU3DAction::printViewport (void) const protected virtual
Friends And Related Function Documentation
SoFCVectorizeU3DActionP
friend class SoFCVectorizeU3DActionP friend
Referenced by SoFCVectorizeU3DAction().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SoFCVectorizeU3DAction.h
Sources/FreeCAD/src/Gui/SoFCVectorizeU3DAction.cpp