FreeCAD: Sketcher::ConstraintPy Class Reference
Sketcher::ConstraintPy Class Reference
The python export class for Constraint.
#include <ConstraintPy.h>
Public Types
typedef Constraint * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
ConstraintPy (Constraint *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of ConstraintPy.
static PyMethodDef Methods []
Methods structure of ConstraintPy.
static PyTypeObject Type
Type structure of ConstraintPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~ConstraintPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object attributes
Py::String getType (void) const
getter for the Type attribute
Py::Long getFirst (void) const
getter for the First attribute
void setFirst (Py::Long arg)
setter for the First attribute
Py::Long getFirstPos (void) const
getter for the FirstPos attribute
void setFirstPos (Py::Long arg)
setter for the FirstPos attribute
Py::Long getSecond (void) const
getter for the Second attribute
void setSecond (Py::Long arg)
setter for the Second attribute
Py::Long getSecondPos (void) const
getter for the SecondPos attribute
void setSecondPos (Py::Long arg)
setter for the SecondPos attribute
Py::Long getThird (void) const
getter for the Third attribute
void setThird (Py::Long arg)
setter for the Third attribute
Py::Long getThirdPos (void) const
getter for the ThirdPos attribute
void setThirdPos (Py::Long arg)
setter for the ThirdPos attribute
Py::Float getValue (void) const
getter for the Value attribute
Py::String getName (void) const
getter for the Name attribute
void setName (Py::String arg)
setter for the Name attribute
Py::Boolean getDriving (void) const
getter for the Driving attribute
Py::Boolean getInVirtualSpace (void) const
getter for the InVirtualSpace attribute
Py::Boolean getIsActive (void) const
getter for the IsActive attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Constraint * getConstraintPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getType (PyObject *self, void *closure)
getter callback for the Type attribute
static int staticCallback_setType (PyObject *self, PyObject *value, void *closure)
setter callback for the Type attribute
static PyObject * staticCallback_getFirst (PyObject *self, void *closure)
getter callback for the First attribute
static int staticCallback_setFirst (PyObject *self, PyObject *value, void *closure)
setter callback for the First attribute
static PyObject * staticCallback_getFirstPos (PyObject *self, void *closure)
getter callback for the FirstPos attribute
static int staticCallback_setFirstPos (PyObject *self, PyObject *value, void *closure)
setter callback for the FirstPos attribute
static PyObject * staticCallback_getSecond (PyObject *self, void *closure)
getter callback for the Second attribute
static int staticCallback_setSecond (PyObject *self, PyObject *value, void *closure)
setter callback for the Second attribute
static PyObject * staticCallback_getSecondPos (PyObject *self, void *closure)
getter callback for the SecondPos attribute
static int staticCallback_setSecondPos (PyObject *self, PyObject *value, void *closure)
setter callback for the SecondPos attribute
static PyObject * staticCallback_getThird (PyObject *self, void *closure)
getter callback for the Third attribute
static int staticCallback_setThird (PyObject *self, PyObject *value, void *closure)
setter callback for the Third attribute
static PyObject * staticCallback_getThirdPos (PyObject *self, void *closure)
getter callback for the ThirdPos attribute
static int staticCallback_setThirdPos (PyObject *self, PyObject *value, void *closure)
setter callback for the ThirdPos attribute
static PyObject * staticCallback_getValue (PyObject *self, void *closure)
getter callback for the Value attribute
static int staticCallback_setValue (PyObject *self, PyObject *value, void *closure)
setter callback for the Value attribute
static PyObject * staticCallback_getName (PyObject *self, void *closure)
getter callback for the Name attribute
static int staticCallback_setName (PyObject *self, PyObject *value, void *closure)
setter callback for the Name attribute
static PyObject * staticCallback_getDriving (PyObject *self, void *closure)
getter callback for the Driving attribute
static int staticCallback_setDriving (PyObject *self, PyObject *value, void *closure)
setter callback for the Driving attribute
static PyObject * staticCallback_getInVirtualSpace (PyObject *self, void *closure)
getter callback for the InVirtualSpace attribute
static int staticCallback_setInVirtualSpace (PyObject *self, PyObject *value, void *closure)
setter callback for the InVirtualSpace attribute
static PyObject * staticCallback_getIsActive (PyObject *self, void *closure)
getter callback for the IsActive attribute
static int staticCallback_setIsActive (PyObject *self, PyObject *value, void *closure)
setter callback for the IsActive attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Constraint.
Member Typedef Documentation
PointerType
typedef Constraint* Sketcher::ConstraintPy::PointerType
Constructor & Destructor Documentation
~ConstraintPy()
ConstraintPy::~ConstraintPy () protected
ConstraintPy()
ConstraintPy::ConstraintPy (Constraint * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getConstraintPtr()
Constraint * ConstraintPy::getConstraintPtr (void) const
getter for the object handled by this class
Referenced by Sketcher::SketchPy::addConstraint(), getDriving(), getFirst(), getFirstPos(), getInVirtualSpace(), getIsActive(), getName(), getSecond(), getSecondPos(), getThird(), getThirdPos(), getType(), getValue(), PyInit(), representation(), setFirst(), setFirstPos(), setName(), Sketcher::PropertyConstraintList::setPyObject(), setSecond(), setSecondPos(), setThird(), and setThirdPos().
getCustomAttributes()
PyObject * ConstraintPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getDriving()
Py::Boolean ConstraintPy::getDriving (void) const
getter for the Driving attribute
References getConstraintPtr().
Referenced by staticCallback_getDriving().
getFirst()
Py::Long ConstraintPy::getFirst (void) const
getter for the First attribute
References getConstraintPtr().
Referenced by staticCallback_getFirst().
getFirstPos()
Py::Long ConstraintPy::getFirstPos (void) const
getter for the FirstPos attribute
References getConstraintPtr().
Referenced by staticCallback_getFirstPos().
getInVirtualSpace()
Py::Boolean ConstraintPy::getInVirtualSpace (void) const
getter for the InVirtualSpace attribute
References getConstraintPtr().
Referenced by staticCallback_getInVirtualSpace().
getIsActive()
Py::Boolean ConstraintPy::getIsActive (void) const
getter for the IsActive attribute
References getConstraintPtr().
Referenced by staticCallback_getIsActive().
getName()
Py::String ConstraintPy::getName (void) const
getter for the Name attribute
References getConstraintPtr().
Referenced by staticCallback_getName().
getSecond()
Py::Long ConstraintPy::getSecond (void) const
getter for the Second attribute
References getConstraintPtr().
Referenced by staticCallback_getSecond().
getSecondPos()
Py::Long ConstraintPy::getSecondPos (void) const
getter for the SecondPos attribute
References getConstraintPtr().
Referenced by staticCallback_getSecondPos().
getThird()
Py::Long ConstraintPy::getThird (void) const
getter for the Third attribute
References getConstraintPtr().
Referenced by staticCallback_getThird().
getThirdPos()
Py::Long ConstraintPy::getThirdPos (void) const
getter for the ThirdPos attribute
References getConstraintPtr().
Referenced by staticCallback_getThirdPos().
GetType()
virtual PyTypeObject* Sketcher::ConstraintPy::GetType (void) virtual
Reimplemented from Base::PersistencePy.
getType()
Py::String ConstraintPy::getType (void) const
getter for the Type attribute
References Sketcher::Angle, Sketcher::Block, Sketcher::Coincident, Sketcher::Diameter, Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, Sketcher::Equal, getConstraintPtr(), Sketcher::Horizontal, Sketcher::InternalAlignment, Sketcher::Parallel, Sketcher::Perpendicular, Sketcher::PointOnObject, Sketcher::Radius, Sketcher::SnellsLaw, Sketcher::Symmetric, Sketcher::Tangent, Type, Sketcher::Vertical, and Sketcher::Weight.
Referenced by staticCallback_getType(), PathScripts.PathToolEdit.ToolEditor::updateToolType(), and PathScripts.PathToolEdit.ToolEditor::updateUI().
getValue()
Py::Float ConstraintPy::getValue (void) const
getter for the Value attribute
References getConstraintPtr().
Referenced by staticCallback_getValue().
PyInit()
int ConstraintPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PersistencePy.
References Sketcher::Constraint::AlignmentType, Base::Unit::Angle, Sketcher::Angle, Sketcher::Block, Sketcher::BSplineControlPoint, Sketcher::Coincident, Sketcher::Diameter, Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, Sketcher::EllipseFocus1, Sketcher::EllipseFocus2, Sketcher::EllipseMajorDiameter, Sketcher::EllipseMinorDiameter, Sketcher::Equal, Sketcher::Constraint::First, Sketcher::Constraint::FirstPos, Sketcher::Constraint::GeoUndef, getConstraintPtr(), Base::Quantity::getValueAs(), Sketcher::Horizontal, Sketcher::InternalAlignment, Sketcher::Constraint::InternalAlignmentIndex, Sketcher::Constraint::LabelPosition, Sketcher::none, Sketcher::Parallel, Sketcher::Perpendicular, Sketcher::PointOnObject, Base::Quantity::Radian, Sketcher::Radius, Sketcher::Constraint::Second, Sketcher::Constraint::SecondPos, Sketcher::Constraint::setValue(), Sketcher::SnellsLaw, Sketcher::Symmetric, Sketcher::Tangent, Sketcher::Constraint::Third, Sketcher::Constraint::ThirdPos, Base::QuantityPy::Type, Sketcher::Constraint::Type, Sketcher::Undef, Sketcher::Vertical, and Sketcher::Weight.
PyMake()
PyObject * ConstraintPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References ConstraintPy().
representation()
std::string ConstraintPy::representation (void) const
References Sketcher::Angle, Sketcher::Block, Sketcher::Coincident, Sketcher::Diameter, Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, Sketcher::EllipseFocus1, Sketcher::EllipseFocus2, Sketcher::EllipseMajorDiameter, Sketcher::EllipseMinorDiameter, Sketcher::Equal, Sketcher::Constraint::First, Sketcher::Constraint::GeoUndef, getConstraintPtr(), Sketcher::Horizontal, Sketcher::InternalAlignment, Sketcher::Parallel, Sketcher::Perpendicular, Sketcher::PointOnObject, Sketcher::Radius, Sketcher::Constraint::Second, Sketcher::SnellsLaw, Sketcher::Symmetric, Sketcher::Tangent, Type, Sketcher::Undef, Sketcher::Vertical, and Sketcher::Weight.
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int ConstraintPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setFirst()
void ConstraintPy::setFirst (Py::Long arg)
setter for the First attribute
References Sketcher::Constraint::First, and getConstraintPtr().
Referenced by staticCallback_setFirst().
setFirstPos()
void ConstraintPy::setFirstPos (Py::Long arg)
setter for the FirstPos attribute
References Sketcher::Constraint::FirstPos, getConstraintPtr(), Sketcher::mid, and Sketcher::none.
Referenced by staticCallback_setFirstPos().
setName()
void ConstraintPy::setName (Py::String arg)
setter for the Name attribute
References getConstraintPtr(), and Sketcher::Constraint::Name.
Referenced by staticCallback_setName().
setSecond()
void ConstraintPy::setSecond (Py::Long arg)
setter for the Second attribute
References getConstraintPtr(), and Sketcher::Constraint::Second.
Referenced by staticCallback_setSecond().
setSecondPos()
void ConstraintPy::setSecondPos (Py::Long arg)
setter for the SecondPos attribute
References getConstraintPtr(), Sketcher::mid, Sketcher::none, and Sketcher::Constraint::SecondPos.
Referenced by staticCallback_setSecondPos().
setThird()
void ConstraintPy::setThird (Py::Long arg)
setter for the Third attribute
References getConstraintPtr(), and Sketcher::Constraint::Third.
Referenced by staticCallback_setThird().
setThirdPos()
void ConstraintPy::setThirdPos (Py::Long arg)
setter for the ThirdPos attribute
References getConstraintPtr(), Sketcher::mid, Sketcher::none, and Sketcher::Constraint::ThirdPos.
Referenced by staticCallback_setThirdPos().
staticCallback_getDriving()
PyObject * ConstraintPy::staticCallback_getDriving (PyObject * self, void * closure) static
getter callback for the Driving attribute
References Base::BaseExceptionFreeCADError, getDriving(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFirst()
PyObject * ConstraintPy::staticCallback_getFirst (PyObject * self, void * closure) static
getter callback for the First attribute
References Base::BaseExceptionFreeCADError, getFirst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFirstPos()
PyObject * ConstraintPy::staticCallback_getFirstPos (PyObject * self, void * closure) static
getter callback for the FirstPos attribute
References Base::BaseExceptionFreeCADError, getFirstPos(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getInVirtualSpace()
PyObject * ConstraintPy::staticCallback_getInVirtualSpace (PyObject * self, void * closure) static
getter callback for the InVirtualSpace attribute
References Base::BaseExceptionFreeCADError, getInVirtualSpace(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getIsActive()
PyObject * ConstraintPy::staticCallback_getIsActive (PyObject * self, void * closure) static
getter callback for the IsActive attribute
References Base::BaseExceptionFreeCADError, getIsActive(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getName()
PyObject * ConstraintPy::staticCallback_getName (PyObject * self, void * closure) static
getter callback for the Name attribute
References Base::BaseExceptionFreeCADError, getName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSecond()
PyObject * ConstraintPy::staticCallback_getSecond (PyObject * self, void * closure) static
getter callback for the Second attribute
References Base::BaseExceptionFreeCADError, getSecond(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSecondPos()
PyObject * ConstraintPy::staticCallback_getSecondPos (PyObject * self, void * closure) static
getter callback for the SecondPos attribute
References Base::BaseExceptionFreeCADError, getSecondPos(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getThird()
PyObject * ConstraintPy::staticCallback_getThird (PyObject * self, void * closure) static
getter callback for the Third attribute
References Base::BaseExceptionFreeCADError, getThird(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getThirdPos()
PyObject * ConstraintPy::staticCallback_getThirdPos (PyObject * self, void * closure) static
getter callback for the ThirdPos attribute
References Base::BaseExceptionFreeCADError, getThirdPos(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getType()
PyObject * ConstraintPy::staticCallback_getType (PyObject * self, void * closure) static
getter callback for the Type attribute
References Base::BaseExceptionFreeCADError, getType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getValue()
PyObject * ConstraintPy::staticCallback_getValue (PyObject * self, void * closure) static
getter callback for the Value attribute
References Base::BaseExceptionFreeCADError, getValue(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setDriving()
int ConstraintPy::staticCallback_setDriving (PyObject * self, PyObject * value, void * closure) static
setter callback for the Driving attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setFirst()
int ConstraintPy::staticCallback_setFirst (PyObject * self, PyObject * value, void * closure) static
setter callback for the First attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setFirst().
staticCallback_setFirstPos()
int ConstraintPy::staticCallback_setFirstPos (PyObject * self, PyObject * value, void * closure) static
setter callback for the FirstPos attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setFirstPos().
staticCallback_setInVirtualSpace()
int ConstraintPy::staticCallback_setInVirtualSpace (PyObject * self, PyObject * value, void * closure) static
setter callback for the InVirtualSpace attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setIsActive()
int ConstraintPy::staticCallback_setIsActive (PyObject * self, PyObject * value, void * closure) static
setter callback for the IsActive attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setName()
int ConstraintPy::staticCallback_setName (PyObject * self, PyObject * value, void * closure) static
setter callback for the Name attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setName().
staticCallback_setSecond()
int ConstraintPy::staticCallback_setSecond (PyObject * self, PyObject * value, void * closure) static
setter callback for the Second attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setSecond().
staticCallback_setSecondPos()
int ConstraintPy::staticCallback_setSecondPos (PyObject * self, PyObject * value, void * closure) static
setter callback for the SecondPos attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setSecondPos().
staticCallback_setThird()
int ConstraintPy::staticCallback_setThird (PyObject * self, PyObject * value, void * closure) static
setter callback for the Third attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setThird().
staticCallback_setThirdPos()
int ConstraintPy::staticCallback_setThirdPos (PyObject * self, PyObject * value, void * closure) static
setter callback for the ThirdPos attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setThirdPos().
staticCallback_setType()
int ConstraintPy::staticCallback_setType (PyObject * self, PyObject * value, void * closure) static
setter callback for the Type attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setValue()
int ConstraintPy::staticCallback_setValue (PyObject * self, PyObject * value, void * closure) static
setter callback for the Value attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
Member Data Documentation
GetterSetter
PyGetSetDef ConstraintPy::GetterSetter static
Attribute structure of ConstraintPy.
Methods
PyMethodDef ConstraintPy::Methods static
Initial value:
= {
    {NULL, NULL, 0, NULL}
}
Methods structure of ConstraintPy.
Type
PyTypeObject ConstraintPy::Type static
Type structure of ConstraintPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), Sketcher::SketchObjectPy::addConstraint(), Sketcher::SketchPy::addConstraint(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), getType(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), representation(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Sketcher/App/ConstraintPy.h
Sources/FreeCAD/src/Mod/Sketcher/App/ConstraintPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Sketcher/App/ConstraintPy.cpp