FreeCAD: Gui::PythonStderr Class Reference
Gui::PythonStderr Class Reference
Python class for redirection of stderr to FreeCAD's Python console window.
#include <PythonConsolePy.h>
Public Member Functions
Py::Object flush (const Py::Tuple &)
Py::Object getattr (const char *name)
Py::Object isatty ()
PythonStderr (PythonConsole *pc)
Py::Object repr ()
Py::Object write (const Py::Tuple &)
~PythonStderr ()
Static Public Member Functions
static void init_type (void)
Detailed Description
Python class for redirection of stderr to FreeCAD's Python console window.
This allows to show all Python messages in the same window where the commands are performed.
See also
PythonStdout
PythonConsole
Author
Werner Mayer
Constructor & Destructor Documentation
PythonStderr()
PythonStderr::PythonStderr (PythonConsole * pc)
~PythonStderr()
PythonStderr::~PythonStderr ()
Member Function Documentation
flush()
Py::Object PythonStderr::flush (const Py::Tuple &)
Referenced by init_type().
getattr()
Py::Object PythonStderr::getattr (const char * name)
init_type()
void PythonStderr::init_type (void) static
References flush(), isatty(), and write().
Referenced by Gui::Application::Application().
isatty()
Py::Object PythonStderr::isatty ()
Referenced by init_type().
repr()
Py::Object PythonStderr::repr ()
write()
Py::Object PythonStderr::write (const Py::Tuple & args)
Referenced by init_type(), and gzip_utf8.GzipFile::seek().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/PythonConsolePy.h
Sources/FreeCAD/src/Gui/PythonConsolePy.cpp