FreeCAD: TechDraw::DrawView Class Reference
TechDraw::DrawView Class Reference
Base class of all View Features in the drawing module.
#include <DrawView.h>
Public Member Functions
DrawView (void)
Constructor.
virtual ~DrawView ()
Public Member Functions inherited from App::DocumentObject
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
virtual bool adjustRelativeLinks (const std::set< App::DocumentObject * > &inList, std::set< App::DocumentObject * > *visited=nullptr)
Called to adjust link properties to avoid cyclic links.
virtual bool allowDuplicateLabel () const
virtual bool canLinkProperties () const
virtual int canLoadPartial () const
allow partial loading of dependent objects
void clearExpression (const ObjectIdentifier &path)
void clearOutListCache () const
clear internal out list cache
virtual const char * detachFromDocument () override
DocumentObject (void)
Constructor.
void enforceRecompute ()
Enforce this document object to be recomputed.
App::Document * getDocument (void) const
gets the document in which this Object is handled
std::string getExportName (bool forced=false) const
returns the name that is safe to be exported to other document
virtual const PropertyExpressionEngine::ExpressionInfo getExpression (const ObjectIdentifier &path) const
virtual std::string getFullName () const override
Return the object full name of the form DocName::ObjName.
DocumentObjectGroup * getGroup () const
get group if object is part of a group, otherwise 0 is returned
long getID () const
Return the object ID that is unique within its owner document.
const std::vector< App::DocumentObject * > & getInList (void) const
std::set< App::DocumentObject * > getInListEx (bool recursive) const
Return a set of all objects linking to this object, including possible external parent objects.
void getInListEx (std::set< App::DocumentObject * > &inSet, bool recursive, std::vector< App::DocumentObject * > *inList=nullptr) const
Get a set of all objects linking to this object, including possible external parent objects.
std::vector< App::DocumentObject * > getInListRecursive (void) const
get all objects link directly or indirectly to this object
virtual DocumentObject * getLinkedObject (bool recurse=true, Base::Matrix4D *mat=nullptr, bool transform=false, int depth=0) const
Return the linked object with optional transformation.
const char * getNameInDocument (void) const
returns the name which is set in the document for this object (not the name property!)
const std::string & getOldLabel () const
const std::vector< App::DocumentObject * > & getOutList () const
returns a list of objects this object is pointing to by Links
std::vector< App::DocumentObject * > getOutList (int option) const
void getOutList (int option, std::vector< App::DocumentObject * > &res) const
std::vector< App::DocumentObject * > getOutListOfProperty (App::Property *) const
returns a list of objects linked by the property
std::vector< App::DocumentObject * > getOutListRecursive (void) const
returns a list of objects this object is pointing to by Links and all further descended
std::vector< std::pair< App::DocumentObject *, std::string > > getParents (int depth=0) const
Obtain top parents and subnames of this object using its InList.
std::vector< std::list< App::DocumentObject * > > getPathsByOutList (App::DocumentObject *to) const
get all possible paths from this to another object following the OutList
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
unsigned long getStatus () const
return the status bits
const char * getStatusString (void) const
get the status Message
virtual DocumentObject * getSubObject (const char *subname, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
Get the sub element/object by name.
std::vector< DocumentObject * > getSubObjectList (const char *subname) const
Return a list of objects referenced by a given subname including this object.
virtual std::vector< std::string > getSubObjects (int reason=0) const
Return name reference of all sub-objects.
virtual const char * getViewProviderName (void) const
returns the type name of the ViewProvider
virtual const char * getViewProviderNameOverride () const
This function is introduced to allow Python feature override its view provider.
const char * getViewProviderNameStored () const
virtual bool hasChildElement () const
return true to activate tree view group object handling and element visibility
virtual bool isAttachedToDocument () const override
virtual int isElementVisible (const char *element) const
Get sub-element visibility.
bool isError (void) const
set this feature to error
int isExporting () const
bool isInInList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the InList
bool isInInListRecursive (DocumentObject *objToTest) const
test if this object is in the InList and recursive further down
bool isInOutList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the OutList
bool isInOutListRecursive (DocumentObject *objToTest) const
test if the given object is in the OutList and recursive further down
bool isRecomputing () const
returns true if this objects is currently recomputing
bool isRemoving () const
returns true if this objects is currently removed from the document
bool isRestoring () const
returns true if this objects is currently restoring from file
bool isTouched (void) const
test if this document object is touched
bool isValid (void) const
virtual short mustExecute (void) const
mustExecute We call this method to check if the object was modified to be invoked.
bool mustRecompute (void) const
Test if this document object must be recomputed.
virtual void onBeforeChangeLabel (std::string &newLabel)
virtual void onLostLinkToObject (DocumentObject *)
Called in case of losing a link Get called by the document when a object got deleted a link property of this object ist pointing to.
virtual void onUpdateElementReference (const Property *)
void purgeError (void)
remove the error from the object
void purgeTouched (void)
reset this document object touched
bool recomputeFeature (bool recursive=false)
Recompute only this feature.
virtual bool redirectSubName (std::ostringstream &ss, DocumentObject *topParent, DocumentObject *child) const
Allow object to redirect a subname path.
virtual bool removeDynamicProperty (const char *prop) override
virtual void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths)
App::DocumentObject * resolve (const char *subname, App::DocumentObject **parent=nullptr, std::string *childName=nullptr, const char **subElement=nullptr, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
Resolve the last document object referenced in the subname.
App::DocumentObject * resolveRelativeLink (std::string &subname, App::DocumentObject *&link, std::string &linkSub) const
Resolve a link reference that is relative to this object reference.
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
virtual int setElementVisible (const char *element, bool visible)
Child element handling.
virtual void setExpression (const ObjectIdentifier &path, std::shared_ptr< App::Expression > expr)
void setStatus (ObjectStatus pos, bool on)
bool testIfLinkDAGCompatible (App::PropertyLinkSub &linkTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSubList &linksTo) const
bool testIfLinkDAGCompatible (const std::vector< DocumentObject * > &linksTo) const
bool testIfLinkDAGCompatible (DocumentObject *linkTo) const
testIfLinkIsDAG tests a link that is about to be created for circular references.
bool testStatus (ObjectStatus pos) const
void touch (bool noRecompute=false)
Set the property touched -> changed, cause recomputation in Update()
virtual ~DocumentObject ()
Public Member Functions inherited from App::TransactionalObject
virtual const char * detachFromDocument ()
virtual bool isAttachedToDocument () const
TransactionalObject (void)
Constructor.
virtual ~TransactionalObject ()
Public Member Functions inherited from App::ExtensionContainer
ExtensionIterator extensionBegin ()
ExtensionContainer ()
ExtensionIterator extensionEnd ()
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
void registerExtension (Base::Type extension, App::Extension *ext)
virtual ~ExtensionContainer ()
virtual Property * getPropertyByName (const char *name) const override
find a property by its name
virtual const char * getPropertyName (const Property *prop) const override
get the name of a property
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
virtual void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
virtual short getPropertyType (const Property *prop) const override
get the Type of a Property
virtual short getPropertyType (const char *name) const override
get the Type of a named Property
virtual const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
virtual void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
Public Member Functions inherited from App::PropertyContainer
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false)
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual void editProperty (const char *)
virtual App::Property * getDynamicPropertyByName (const char *name) const
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual std::string getFullName () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Property * getPropertyByName (const char *name) const
find a property by its name
virtual const char * getPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * getPropertyGroup (const Property *prop) const
get the Group of a Property
virtual void getPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual const char * getPropertyName (const Property *prop) const
get the name of a property
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
const char * getPropertyPrefix () const
virtual short getPropertyType (const char *name) const
get the Type of a named Property
virtual short getPropertyType (const Property *prop) const
get the Type of a Property
bool isHidden (const char *name) const
check if the named property is hidden
bool isHidden (const Property *prop) const
check if the property is hidden
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isReadOnly (const Property *prop) const
check if the property is read-only
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus)
PropertyContainer ()
A constructor.
virtual bool removeDynamicProperty (const char *name)
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
void setPropertyPrefix (const char *prefix)
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
virtual ~PropertyContainer ()
A destructor.
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Attributes
App::PropertyString Caption
App::PropertyBool LockPosition
App::PropertyAngle Rotation
App::PropertyFloatConstraint Scale
App::PropertyEnumeration ScaleType
App::PropertyDistance X
App::PropertyDistance Y
Public Attributes inherited from App::DocumentObject
PropertyExpressionEngine ExpressionEngine
PropertyString Label
PropertyString Label2
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChange
signal before changing a property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChanged
signal on changed property of this object
PropertyBool Visibility
Allow control visibility status in App name space.
methods override Feature
boost::signals2::signal< void(const DrawView *)> signalGuiPaint
std::string pageFeatName
bool autoPos
bool mouseMove
virtual App::DocumentObjectExecReturn * execute (void) override
recalculate the Feature
virtual void onDocumentRestored () override
get called after a document has been fully restored
virtual short mustExecute () const override
mustExecute We call this method to check if the object was modified to be invoked.
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, App::Property *prop) override
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
bool isInClip ()
DrawViewClip * getClipGroup (void)
virtual const char * getViewProviderName (void) const override
returns the type name of the ViewProvider
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
virtual DrawPage * findParentPage () const
virtual std::vector< DrawPage * > findAllParentPages () const
virtual int countParentPages () const
DrawView::countParentPages Fixes a crash in TechDraw when user creates duplicate page without dependencies In fixOrphans() we check how many parent pages an object has before deleting in case it is also a child of another duplicate page.
virtual QRectF getRect () const
virtual double autoScale (void) const
virtual double autoScale (double w, double h) const
virtual bool checkFit (void) const
virtual bool checkFit (DrawPage *) const
check if View is too big for page
virtual void setPosition (double x, double y, bool force=false)
virtual bool keepUpdated (void)
virtual double getScale (void) const
void checkScale (void)
void requestPaint (void)
virtual void handleXYLock (void)
virtual bool isLocked (void) const
virtual bool showLock (void) const
std::vector< TechDraw::DrawLeaderLine * > getLeaders (void) const
void setScaleAttribute ()
virtual void onChanged (const App::Property *prop) override
get called by the container when a property was changed
virtual void validateScale ()
int prefScaleType (void)
double prefScale (void)
Additional Inherited Members
Public Types inherited from App::DocumentObject
enum GSReason { GS_DEFAULT , GS_SELECT }
reason of calling getSubObjects()
enum OutListOption { OutListNoExpression = 1 , OutListNoHidden = 2 , OutListNoXLinked = 4 }
DAG handling This part of the interface deals with viewing the document as a DAG (directed acyclic graph).
Public Types inherited from App::ExtensionContainer
typedef std::map< Base::Type, App::Extension * >::iterator ExtensionIterator
Static Public Member Functions inherited from App::DocumentObject
static const char * hasHiddenMarker (const char *subname)
Check if the subname reference ends with hidden marker.
static const std::string & hiddenMarker ()
Special marker to mark the object as hidden.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Public Attributes inherited from App::DocumentObject
static DocumentObjectExecReturn * StdReturn
Protected Member Functions inherited from App::DocumentObject
virtual App::DocumentObjectExecReturn * execute (void)
get called by the document to recompute this feature Normally this method get called in the processing of Document::recompute().
App::DocumentObjectExecReturn * executeExtensions ()
Executes the extensions of a document object.
virtual void onBeforeChange (const Property *prop) override
get called before the value is changed
virtual void onChanged (const Property *prop) override
get called by the container when a property was changed
virtual void onDocumentRestored ()
get called after a document has been fully restored
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus) override
get called when a property status has changed
virtual void onSettingDocument ()
get called after setting the document
virtual void onUndoRedoFinished ()
get called after an undo/redo transaction is finished
virtual App::DocumentObjectExecReturn * recompute (void)
recompute only this object
void resetError (void)
void setDocument (App::Document *doc)
void setError (void)
virtual void setupObject ()
get called after a brand new object was created
virtual void unsetupObject ()
get called when object is going to be removed from the document
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData (void) const
virtual void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container.
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
virtual void onBeforeChange (const Property *)
get called before the value is changed
virtual void onChanged (const Property *)
get called by the container when a property has changed
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::DocumentObject
std::string oldLabel
Old label; used for renaming expressions.
const std::string * pcNameInDocument
Py::SmartPtr PythonObject
python object of this class and all descendent
std::bitset< 32 > StatusBits
Status bits of the document object The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Detailed Description
Base class of all View Features in the drawing module.
Constructor & Destructor Documentation
DrawView()
DrawView::DrawView (void)
Constructor.
References App::Prop_Output.
~DrawView()
DrawView::~DrawView () virtual
Member Function Documentation
autoScale() [1/2]
double DrawView::autoScale (double w, double h) const virtual
References getRect(), getScale(), and TechDraw::DrawUtil::sensibleScale().
autoScale() [2/2]
double DrawView::autoScale (void) const virtual
References autoScale(), and findParentPage().
Referenced by autoScale(), TechDraw::DrawProjGroup::execute(), TechDraw::DrawViewDetail::execute(), TechDraw::DrawViewPart::execute(), TechDraw::DrawViewSection::execute(), onChanged(), TechDraw::DrawViewDetail::onChanged(), and TechDrawGui::TaskSectionView::scaleTypeChanged().
checkFit() [1/2]
bool DrawView::checkFit (TechDraw::DrawPage * p) const virtual
check if View is too big for page
Reimplemented in TechDraw::DrawProjGroupItem, and TechDraw::DrawViewSymbol.
References getRect().
checkFit() [2/2]
bool DrawView::checkFit (void) const virtual
Reimplemented in TechDraw::DrawProjGroupItem.
References checkFit(), and findParentPage().
Referenced by checkFit(), TechDraw::DrawProjGroup::execute(), TechDraw::DrawViewDetail::execute(), TechDraw::DrawViewPart::execute(), TechDraw::DrawViewSection::execute(), onChanged(), and TechDraw::DrawViewDetail::onChanged().
checkScale()
void DrawView::checkScale (void)
References findParentPage(), App::PropertyFloat::getValue(), App::PropertyEnumeration::isValue(), App::Property::purgeTouched(), TechDraw::DrawPage::Scale, Scale, ScaleType, and App::PropertyFloat::setValue().
countParentPages()
int DrawView::countParentPages () const virtual
DrawView::countParentPages Fixes a crash in TechDraw when user creates duplicate page without dependencies In fixOrphans() we check how many parent pages an object has before deleting in case it is also a child of another duplicate page.
Returns
Reimplemented in TechDraw::DrawProjGroupItem.
References Base::Persistence::getClassTypeId(), and App::DocumentObject::getInList().
Referenced by TechDraw::DrawProjGroupItem::countParentPages().
execute()
App::DocumentObjectExecReturn * DrawView::execute (void) override virtual
recalculate the Feature
Reimplemented from App::DocumentObject.
Reimplemented in TechDraw::DrawRichAnno, TechDraw::DrawViewAnnotation, TechDraw::DrawViewClip, TechDraw::DrawViewCollection, TechDraw::DrawViewDimExtent, TechDraw::DrawViewSpreadsheet, TechDraw::DrawWeldSymbol, TechDraw::DrawLeaderLine, TechDraw::DrawProjGroup, TechDraw::DrawProjGroupItem, TechDraw::DrawViewArch, TechDraw::DrawViewBalloon, TechDraw::DrawViewDetail, TechDraw::DrawViewDimension, TechDraw::DrawViewDraft, TechDraw::DrawViewImage, TechDraw::DrawViewMulti, TechDraw::DrawViewPart, TechDraw::DrawViewSection, TechDraw::DrawViewSymbol, and TechDraw::LandmarkDimension.
References App::DocumentObject::execute(), findParentPage(), handleXYLock(), App::DocumentObject::purgeTouched(), and requestPaint().
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), PathScripts.PathDressupDogbone.ObjectDressup::boneStateList(), ArchSite.Compass::buildCoordinates(), TechDraw::DrawRichAnno::execute(), TechDraw::DrawViewAnnotation::execute(), TechDraw::DrawViewClip::execute(), TechDraw::DrawViewCollection::execute(), TechDraw::DrawViewSpreadsheet::execute(), TechDraw::DrawWeldSymbol::execute(), TechDraw::DrawLeaderLine::execute(), TechDraw::DrawViewArch::execute(), TechDraw::DrawViewDetail::execute(), TechDraw::DrawViewDimension::execute(), TechDraw::DrawViewDraft::execute(), TechDraw::DrawViewImage::execute(), TechDraw::DrawViewMulti::execute(), TechDraw::DrawViewPart::execute(), TechDraw::DrawViewSection::execute(), TechDraw::DrawViewSymbol::execute(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::generateTags(), ArchPanel.PanelCut::getWires(), ArchSchedule.CommandArchSchedule::IsActive(), Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), FeaturePython.DistanceBolt::onChanged(), PathScripts.PathStock.StockFromBase::onChanged(), PathScripts.PathStock.StockCreateBox::onChanged(), PathScripts.PathStock.StockCreateCylinder::onChanged(), TechDraw::DrawViewCollection::onDocumentRestored(), onDocumentRestored(), draftobjects.draftlink.DraftLink::onDocumentRestored(), draftobjects.patharray.PathArray::onDocumentRestored(), and draftobjects.pathtwistedarray.PathTwistedArray::onDocumentRestored().
findAllParentPages()
std::vector< DrawPage * > DrawView::findAllParentPages () const virtual
Reimplemented in TechDraw::DrawProjGroupItem.
References findParentPage(), Base::Persistence::getClassTypeId(), and App::DocumentObject::getInList().
Referenced by TechDraw::DrawProjGroupItem::findAllParentPages(), and TechDrawGui::ViewProviderDrawingView::onGuiRepaint().
findParentPage()
DrawPage * DrawView::findParentPage () const virtual
Reimplemented in TechDraw::DrawProjGroupItem.
References findParentPage(), Base::Persistence::getClassTypeId(), and App::DocumentObject::getInList().
Referenced by TechDraw::DrawProjGroup::addProjection(), TechDraw::DrawViewClip::addView(), TechDraw::DrawProjGroup::arrangeViewPointers(), autoScale(), checkFit(), checkScale(), TechDrawGui::TaskWeldingSymbol::createWeldingSymbol(), execute(), findAllParentPages(), findParentPage(), TechDraw::DrawProjGroupItem::findParentPage(), TechDrawGui::QGIView::getFrameState(), TechDraw::DrawProjGroup::getPage(), getScale(), TechDraw::DrawProjGroup::getViewIndex(), keepUpdated(), TechDraw::DrawDimHelper::makeDistDim(), onChanged(), TechDraw::DrawViewDetail::onChanged(), TechDrawGui::QGIViewBalloon::placeBalloon(), prefScale(), TechDraw::DrawProjGroup::purgeProjections(), TechDrawGui::TaskProjGroup::reject(), TechDrawGui::TaskSectionView::scaleTypeChanged(), TechDrawGui::TaskDetail::TaskDetail(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), TechDrawGui::TaskProjGroup::TaskProjGroup(), TechDrawGui::TaskRichAnno::TaskRichAnno(), TechDrawGui::TaskSectionView::TaskSectionView(), TechDraw::DrawViewPart::unsetupObject(), and validateScale().
getClipGroup()
DrawViewClip * DrawView::getClipGroup (void)
References Base::Persistence::getClassTypeId(), and App::DocumentObject::getInList().
getLeaders()
std::vector< TechDraw::DrawLeaderLine * > DrawView::getLeaders (void) const
References Base::Persistence::getClassTypeId(), and App::DocumentObject::getInList().
Referenced by TechDrawGui::ViewProviderProjGroup::onDelete(), TechDrawGui::ViewProviderProjGroupItem::onDelete(), and TechDrawGui::ViewProviderViewPart::onDelete().
getPyObject()
PyObject * DrawView::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from App::DocumentObject.
Reimplemented in TechDraw::DrawRichAnno, TechDraw::DrawViewClip, TechDraw::DrawViewDimExtent, TechDraw::DrawWeldSymbol, TechDraw::DrawLeaderLine, TechDraw::DrawProjGroup, TechDraw::DrawProjGroupItem, TechDraw::DrawViewDimension, TechDraw::DrawViewPart, and TechDraw::DrawViewSymbol.
References App::DocumentObject::PythonObject.
getRect()
QRectF DrawView::getRect (void) const virtual
Reimplemented in TechDraw::DrawRichAnno, TechDraw::DrawViewAnnotation, TechDraw::DrawWeldSymbol, TechDraw::DrawLeaderLine, TechDraw::DrawViewDimension, TechDraw::DrawViewImage, TechDraw::DrawViewPart, TechDraw::DrawViewSymbol, TechDraw::DrawViewClip, TechDraw::DrawViewCollection, and TechDraw::DrawProjGroup.
Referenced by autoScale(), and checkFit().
getScale()
double DrawView::getScale (void) const virtual
Reimplemented in TechDraw::DrawLeaderLine, and TechDraw::DrawProjGroupItem.
References Base::Console(), findParentPage(), App::DocumentObject::getNameInDocument(), App::PropertyFloat::getValue(), App::PropertyEnumeration::isValue(), Base::ConsoleSingleton::Log(), Scale, and ScaleType.
Referenced by TechDraw::DrawViewPart::add1CEToGE(), TechDraw::DrawViewPart::add1CVToGV(), TechDraw::GeometryObject::addCosmeticEdge(), TechDraw::DrawViewPart::addCosmeticEdgesToGeom(), TechDraw::GeometryObject::addCosmeticVertex(), TechDraw::DrawViewPart::addCosmeticVertexesToGeom(), TechDraw::DrawViewPart::addShapes2d(), autoScale(), TechDrawGui::QGIViewBalloon::balloonLabelDragFinished(), TechDraw::CenterLine::calcEndPoints(), TechDraw::CenterLine::calcEndPoints2Lines(), TechDraw::CenterLine::calcEndPoints2Points(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::QGSPage::createBalloon(), TechDraw::DrawViewDetail::detailExec(), TechDrawGui::QGILeaderLine::draw(), TechDrawGui::QGIViewBalloon::drawBalloon(), TechDrawGui::QGIViewPart::drawHighlight(), TechDrawGui::QGIViewPart::drawMatting(), TechDrawGui::QGIViewPart::drawSectionLine(), TechDrawGui::TaskDetail::editByHighlight(), TechDrawGui::execHoleCircle(), TechDraw::DrawViewDimExtent::execute(), TechDraw::DrawViewArch::execute(), TechDraw::DrawViewDraft::execute(), TechDraw::DrawViewMulti::execute(), TechDraw::LandmarkDimension::execute(), TechDrawGui::TaskDetail::getAnchorScene(), TechDraw::DrawLeaderLine::getBaseScale(), TechDraw::DrawProjGroup::getBoundingBox(), TechDraw::DrawViewDimension::getDimValue(), TechDraw::LandmarkDimension::getPointsTwoVerts(), TechDraw::DrawViewAnnotation::getRect(), TechDraw::DrawViewCollection::getRect(), TechDraw::DrawProjGroup::getRect(), TechDrawGui::QGIView::getScale(), TechDraw::DrawLeaderLine::getScale(), TechDraw::DrawViewSpreadsheet::getSheetImage(), TechDraw::DrawDimHelper::makeExtentDim(), TechDraw::DrawViewPart::makeGeometryForShape(), TechDraw::DrawProjGroup::onChanged(), onChanged(), TechDraw::DrawViewDetail::onChanged(), TechDraw::LandmarkDimension::onDocumentRestored(), TechDrawGui::TaskDetail::onHighlightMoved(), TechDrawGui::TaskCosVertex::onTrackerFinished(), TechDrawGui::QGIViewBalloon::placeBalloon(), TechDraw::DrawViewDimension::saveArrowPositions(), TechDrawGui::TaskSectionView::saveSectionState(), TechDraw::CenterLine::scaledGeometry(), TechDraw::DrawViewSection::sectionExec(), TechDraw::DrawViewSection::sectionLineEnds(), TechDrawGui::TaskSectionView::setUiEdit(), TechDrawGui::TaskSectionView::setUiPrimary(), TechDrawGui::QGIViewBalloon::setViewPartFeature(), TechDrawGui::TaskProjGroup::TaskProjGroup(), TechDrawGui::QGIViewBalloon::updateBalloon(), TechDraw::DrawProjGroup::updateChildrenScale(), TechDrawGui::TaskProjGroup::updateTask(), and TechDrawGui::TaskProjGroup::viewToggled().
getViewProviderName()
virtual const char * TechDraw::DrawView::getViewProviderName (void) const override virtual
returns the type name of the ViewProvider
Reimplemented from App::DocumentObject.
Reimplemented in TechDraw::DrawRichAnno, TechDraw::DrawViewAnnotation, TechDraw::DrawViewClip, TechDraw::DrawViewCollection, TechDraw::DrawViewSpreadsheet, TechDraw::DrawWeldSymbol, TechDraw::DrawLeaderLine, TechDraw::DrawProjGroup, TechDraw::DrawProjGroupItem, TechDraw::DrawViewArch, TechDraw::DrawViewBalloon, TechDraw::DrawViewDetail, TechDraw::DrawViewDimension, TechDraw::DrawViewDraft, TechDraw::DrawViewImage, TechDraw::DrawViewMulti, TechDraw::DrawViewPart, TechDraw::DrawViewSection, TechDraw::DrawViewSymbol, and TechDraw::LandmarkDimension.
handleChangedPropertyType()
void DrawView::handleChangedPropertyType (Base::XMLReader & reader, const char * TypeName, App::Property * prop) override virtual
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
This method is typically called if the property on file has changed its type in more recent versions.
The default implementation does nothing.
Parameters
reader The XML stream to read from.
TypeName Name of property type on file.
prop Pointer to property to restore. Its type differs from TypeName.
Reimplemented from App::PropertyContainer.
Reimplemented in TechDraw::DrawViewDimension, TechDraw::DrawViewAnnotation, TechDraw::DrawProjGroup, and TechDraw::DrawViewBalloon.
References Base::Console(), Base::Persistence::getClassTypeId(), Base::Type::getName(), App::Property::getName(), Base::Persistence::getTypeId(), App::PropertyLink::getValue(), App::PropertyFloat::getValue(), App::PropertyQuantity::getValue(), App::Global, Base::BaseClass::isDerivedFrom(), Base::ConsoleSingleton::Log(), App::PropertyFloat::Restore(), App::PropertyLink::Restore(), Rotation, Scale, App::Property::setContainer(), App::PropertyFloat::setValue(), App::PropertyQuantity::setValue(), X, and Y.
Referenced by TechDraw::DrawViewDimension::handleChangedPropertyType(), TechDraw::DrawViewAnnotation::handleChangedPropertyType(), TechDraw::DrawProjGroup::handleChangedPropertyType(), and TechDraw::DrawViewBalloon::handleChangedPropertyType().
handleXYLock()
void DrawView::handleXYLock (void) virtual
Reimplemented in TechDraw::DrawViewBalloon.
References isLocked(), App::Property::purgeTouched(), App::Property::ReadOnly, App::Property::setStatus(), App::Property::testStatus(), X, and Y.
Referenced by execute(), TechDraw::DrawViewBalloon::handleXYLock(), onChanged(), and onDocumentRestored().
isInClip()
bool DrawView::isInClip ()
References Base::Persistence::getClassTypeId(), and App::DocumentObject::getInList().
Referenced by TechDrawGui::ViewProviderPage::claimChildren().
isLocked()
bool DrawView::isLocked (void) const virtual
Reimplemented in TechDraw::DrawProjGroupItem.
References App::PropertyBool::getValue(), and LockPosition.
Referenced by TechDrawGui::QGILeaderLine::draw(), TechDrawGui::QGIViewBalloon::drawBalloon(), handleXYLock(), TechDraw::DrawViewBalloon::handleXYLock(), TechDraw::DrawProjGroupItem::isLocked(), setPosition(), and TechDrawGui::QGIView::updateView().
keepUpdated()
bool DrawView::keepUpdated (void) virtual
Reimplemented in TechDraw::DrawLeaderLine.
References TechDraw::DrawPage::canUpdate(), findParentPage(), and TechDraw::DrawPage::forceRedraw().
Referenced by TechDraw::DrawRichAnno::execute(), TechDraw::DrawViewClip::execute(), TechDraw::DrawViewCollection::execute(), TechDraw::DrawViewDimExtent::execute(), TechDraw::DrawWeldSymbol::execute(), TechDraw::DrawProjGroup::execute(), TechDraw::DrawProjGroupItem::execute(), TechDraw::DrawViewArch::execute(), TechDraw::DrawViewDetail::execute(), TechDraw::DrawViewDimension::execute(), TechDraw::DrawViewDraft::execute(), TechDraw::DrawViewMulti::execute(), TechDraw::DrawViewPart::execute(), TechDraw::DrawViewSection::execute(), and TechDraw::LandmarkDimension::execute().
mustExecute()
short DrawView::mustExecute () const override virtual
mustExecute We call this method to check if the object was modified to be invoked.
If the object label or an argument is modified. If we must recompute the object - to call the method execute(). 0: no recomputation is needed 1: recomputation needed
Remarks
If an object is marked as 'touched' then this does not necessarily mean that it will be recomputed. It only means that all objects that link it (i.e. its InList) will be recomputed.
Reimplemented from App::DocumentObject.
Reimplemented in TechDraw::DrawRichAnno, TechDraw::DrawViewClip, TechDraw::DrawViewCollection, TechDraw::DrawViewDimExtent, TechDraw::DrawViewSpreadsheet, TechDraw::DrawWeldSymbol, TechDraw::DrawLeaderLine, TechDraw::DrawProjGroup, TechDraw::DrawProjGroupItem, TechDraw::DrawViewArch, TechDraw::DrawViewBalloon, TechDraw::DrawViewDetail, TechDraw::DrawViewDimension, TechDraw::DrawViewDraft, TechDraw::DrawViewImage, TechDraw::DrawViewMulti, TechDraw::DrawViewPart, TechDraw::DrawViewSection, TechDraw::DrawViewSymbol, and TechDraw::LandmarkDimension.
References App::DocumentObject::isRestoring(), App::Property::isTouched(), App::DocumentObject::mustExecute(), Scale, and ScaleType.
Referenced by TechDraw::DrawRichAnno::mustExecute(), TechDraw::DrawViewClip::mustExecute(), TechDraw::DrawViewCollection::mustExecute(), TechDraw::DrawViewSpreadsheet::mustExecute(), TechDraw::DrawWeldSymbol::mustExecute(), TechDraw::DrawLeaderLine::mustExecute(), TechDraw::DrawViewBalloon::mustExecute(), TechDraw::DrawViewDetail::mustExecute(), TechDraw::DrawViewDimension::mustExecute(), TechDraw::DrawViewPart::mustExecute(), TechDraw::DrawViewSection::mustExecute(), and TechDraw::DrawViewSymbol::mustExecute().
onChanged()
void DrawView::onChanged (const App::Property * prop) override protected virtual
get called by the container when a property was changed
Reimplemented from App::DocumentObject.
Reimplemented in TechDraw::DrawRichAnno, TechDraw::DrawViewAnnotation, TechDraw::DrawViewClip, TechDraw::DrawViewCollection, TechDraw::DrawViewDimExtent, TechDraw::DrawViewSpreadsheet, TechDraw::DrawWeldSymbol, TechDraw::DrawLeaderLine, TechDraw::DrawProjGroup, TechDraw::DrawProjGroupItem, TechDraw::DrawViewBalloon, TechDraw::DrawViewDetail, TechDraw::DrawViewDimension, TechDraw::DrawViewImage, TechDraw::DrawViewMulti, TechDraw::DrawViewPart, TechDraw::DrawViewSection, TechDraw::DrawViewSymbol, and TechDraw::LandmarkDimension.
References autoScale(), Caption, checkFit(), findParentPage(), getScale(), handleXYLock(), App::DocumentObject::isRestoring(), App::PropertyEnumeration::isValue(), App::DocumentObject::Label, LockPosition, App::DocumentObject::onChanged(), App::Property::purgeTouched(), App::Property::ReadOnly, requestPaint(), Scale, ScaleType, App::Property::setStatus(), App::PropertyFloat::setValue(), X, and Y.
Referenced by ArchStructure.CommandStructuralSystem::Activated(), draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSite.Compass::buildCoordinates(), draftobjects.wire.Wire::execute(), TechDraw::DrawRichAnno::onChanged(), TechDraw::DrawViewAnnotation::onChanged(), TechDraw::DrawViewClip::onChanged(), TechDraw::DrawViewCollection::onChanged(), TechDraw::DrawViewSpreadsheet::onChanged(), TechDraw::DrawWeldSymbol::onChanged(), TechDraw::DrawLeaderLine::onChanged(), TechDraw::DrawViewBalloon::onChanged(), TechDraw::DrawViewDetail::onChanged(), TechDraw::DrawViewDimension::onChanged(), TechDraw::DrawViewImage::onChanged(), TechDraw::DrawViewPart::onChanged(), TechDraw::DrawViewSection::onChanged(), TechDraw::DrawViewSymbol::onChanged(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchPanel.ViewProviderPanelSheet::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), and draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData().
onDocumentRestored()
void DrawView::onDocumentRestored () override virtual
get called after a document has been fully restored
Reimplemented from App::DocumentObject.
Reimplemented in TechDraw::DrawViewCollection, TechDraw::DrawProjGroupItem, TechDraw::DrawViewDimension, TechDraw::DrawViewPart, TechDraw::DrawViewSection, and TechDraw::LandmarkDimension.
References execute(), handleXYLock(), setScaleAttribute(), and validateScale().
Referenced by TechDraw::DrawProjGroupItem::onDocumentRestored(), and TechDraw::DrawViewPart::onDocumentRestored().
prefScale()
double DrawView::prefScale (void) protected
References findParentPage(), App::GetApplication(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), App::PropertyEnumeration::isValue(), and ScaleType.
prefScaleType()
int DrawView::prefScaleType (void) protected
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), and App::Application::GetUserParameter().
requestPaint()
void DrawView::requestPaint (void)
References signalGuiPaint.
Referenced by TechDrawGui::TaskCosmeticLine::accept(), TechDrawGui::TaskCosVertex::accept(), TechDrawGui::TaskDetail::accept(), TechDrawGui::TaskGeomHatch::accept(), TechDrawGui::TaskLineDecor::accept(), TechDrawGui::TaskCosVertex::addCosVertex(), TechDraw::DrawProjGroup::addProjection(), TechDrawGui::TaskSectionView::applyQuick(), TechDraw::DrawProjGroupItem::autoPosition(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::TaskDetail::createDetail(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), TechDrawGui::execHoleCircle(), TechDraw::DrawViewAnnotation::execute(), TechDraw::DrawViewClip::execute(), TechDraw::DrawGeomHatch::execute(), TechDraw::DrawHatch::execute(), execute(), TechDraw::DrawViewBalloon::execute(), TechDraw::DrawViewDetail::execute(), TechDraw::DrawViewImage::execute(), TechDraw::DrawViewMulti::execute(), TechDraw::DrawViewSection::execute(), TechDraw::LandmarkDimension::execute(), TechDraw::DrawDimHelper::makeDistDim(), TechDrawGui::TaskWeldingSymbol::onArrowSymbolClicked(), TechDrawGui::TaskWeldingSymbol::onArrowTextChanged(), TechDrawGui::TaskLeaderLine::onCancelEditClicked(), TechDraw::DrawRichAnno::onChanged(), TechDraw::DrawViewAnnotation::onChanged(), TechDraw::DrawViewClip::onChanged(), onChanged(), TechDraw::DrawViewBalloon::onChanged(), TechDraw::DrawViewDetail::onChanged(), TechDraw::DrawViewDimension::onChanged(), TechDraw::DrawViewImage::onChanged(), TechDraw::DrawViewSection::onChanged(), TechDrawGui::ViewProviderGeomHatch::onChanged(), TechDrawGui::ViewProviderHatch::onChanged(), TechDrawGui::TaskLineDecor::onColorChanged(), TechDrawGui::TaskWeldingSymbol::onFlipSidesClicked(), TechDrawGui::TaskWeldingSymbol::onOtherEraseClicked(), TechDrawGui::TaskWeldingSymbol::onOtherSymbolClicked(), TechDrawGui::TaskWeldingSymbol::onOtherTextChanged(), TechDrawGui::TaskLineDecor::onStyleChanged(), TechDrawGui::TaskLineDecor::onVisibleChanged(), TechDrawGui::TaskLineDecor::onWeightChanged(), TechDrawGui::TaskWeldingSymbol::onWeldingChanged(), TechDrawGui::TaskDetail::reject(), TechDrawGui::TaskSectionView::reject(), TechDraw::LandmarkDimension::unsetupObject(), TechDraw::DrawGeomHatch::unsetupObject(), TechDraw::DrawHatch::unsetupObject(), TechDrawGui::TaskRichAnno::updateAnnoFeature(), TechDrawGui::TaskDetail::updateDetail(), and TechDrawGui::TaskLeaderLine::updateLeaderFeature().
setPosition()
void DrawView::setPosition (double x, double y, bool force = false) virtual
References TechDraw::DrawUtil::fpCompare(), App::PropertyQuantity::getValue(), isLocked(), App::PropertyQuantity::setValue(), X, and Y.
Referenced by TechDrawGui::TaskRichAnno::commonFeatureUpdate(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), TechDrawGui::QGIProjGroup::mouseReleaseEvent(), and TechDrawGui::QGIView::mouseReleaseEvent().
setScaleAttribute()
void DrawView::setScaleAttribute ()
References App::PropertyEnumeration::isValue(), App::Property::ReadOnly, Scale, ScaleType, and App::Property::setStatus().
Referenced by onDocumentRestored().
showLock()
bool DrawView::showLock (void) const virtual
Reimplemented in TechDraw::DrawProjGroupItem.
Referenced by TechDraw::DrawProjGroupItem::showLock().
validateScale()
void DrawView::validateScale () protected virtual
References findParentPage(), TechDraw::DrawUtil::fpCompare(), App::PropertyFloat::getValue(), App::PropertyEnumeration::isValue(), App::Property::purgeTouched(), TechDraw::DrawPage::Scale, Scale, ScaleType, and App::PropertyEnumeration::setValue().
Referenced by onDocumentRestored().
Member Data Documentation
autoPos
bool TechDraw::DrawView::autoPos protected
Caption
App::PropertyString TechDraw::DrawView::Caption
Referenced by TechDraw::DrawViewBalloon::DrawViewBalloon(), TechDraw::DrawViewDimension::DrawViewDimension(), and onChanged().
LockPosition
App::PropertyBool TechDraw::DrawView::LockPosition
Referenced by TechDraw::DrawProjGroupItem::autoPosition(), TechDraw::DrawViewDimension::DrawViewDimension(), TechDraw::DrawProjGroup::getXYPosition(), isLocked(), TechDraw::DrawProjGroup::mustExecute(), TechDraw::DrawProjGroup::onChanged(), onChanged(), and TechDraw::DrawProjGroupItem::showLock().
mouseMove
bool TechDraw::DrawView::mouseMove protected
pageFeatName
std::string TechDraw::DrawView::pageFeatName protected
Rotation
App::PropertyAngle TechDraw::DrawView::Rotation
Referenced by TechDraw::DrawViewDetail::detailExec(), TechDrawGui::QGIViewPart::drawHighlight(), TechDrawGui::QGIViewPart::drawPainterPath(), TechDrawGui::QGIViewPart::drawSectionLine(), TechDraw::DrawViewBalloon::DrawViewBalloon(), TechDraw::DrawViewDimension::DrawViewDimension(), TechDraw::DrawViewArch::execute(), TechDraw::DrawViewMulti::execute(), handleChangedPropertyType(), TechDraw::DrawViewPart::makeGeometryForShape(), TechDraw::DrawViewPart::mustExecute(), TechDraw::DrawProjGroup::onChanged(), TechDrawGui::QGIView::rotateView(), TechDrawGui::QGIViewAnnotation::rotateView(), TechDrawGui::QGIViewImage::rotateView(), TechDrawGui::QGIViewSymbol::rotateView(), TechDraw::DrawViewSection::sectionExec(), TechDraw::DrawViewSection::sectionLineEnds(), and TechDrawGui::QGIView::updateView().
Scale
App::PropertyFloatConstraint TechDraw::DrawView::Scale
Referenced by checkScale(), TechDraw::DrawViewAnnotation::DrawViewAnnotation(), TechDraw::DrawViewDimension::DrawViewDimension(), TechDraw::DrawProjGroup::execute(), TechDraw::DrawViewDetail::execute(), TechDraw::DrawViewPart::execute(), TechDraw::DrawViewSection::execute(), getScale(), TechDraw::DrawProjGroupItem::getScale(), handleChangedPropertyType(), TechDraw::DrawProjGroup::mustExecute(), TechDraw::DrawProjGroupItem::mustExecute(), mustExecute(), TechDraw::DrawViewSection::mustExecute(), TechDraw::DrawViewSymbol::mustExecute(), TechDraw::DrawProjGroup::onChanged(), onChanged(), TechDraw::DrawViewDetail::onChanged(), TechDraw::DrawViewImage::onChanged(), TechDrawGui::TaskDetail::onScaleTypeEdit(), TechDrawGui::TaskProjGroup::restoreGroupState(), TechDrawGui::TaskSectionView::restoreSectionState(), TechDrawGui::TaskProjGroup::saveGroupState(), TechDrawGui::TaskProjGroup::scaleTypeChanged(), TechDrawGui::TaskSectionView::scaleTypeChanged(), setScaleAttribute(), TechDrawGui::TaskDetail::setUiFromFeat(), TechDrawGui::TaskDetail::updateDetail(), and validateScale().
ScaleType
App::PropertyEnumeration TechDraw::DrawView::ScaleType
Referenced by checkScale(), TechDraw::DrawViewAnnotation::DrawViewAnnotation(), TechDraw::DrawViewArch::DrawViewArch(), TechDraw::DrawViewDimension::DrawViewDimension(), TechDraw::DrawProjGroup::execute(), TechDraw::DrawViewDetail::execute(), TechDraw::DrawViewPart::execute(), TechDraw::DrawViewSection::execute(), getScale(), TechDraw::DrawProjGroup::mustExecute(), mustExecute(), TechDraw::DrawProjGroup::onChanged(), onChanged(), TechDraw::DrawViewDetail::onChanged(), TechDrawGui::TaskDetail::onScaleTypeEdit(), prefScale(), TechDrawGui::TaskProjGroup::restoreGroupState(), TechDrawGui::TaskSectionView::restoreSectionState(), TechDrawGui::TaskProjGroup::saveGroupState(), TechDrawGui::TaskSectionView::saveSectionState(), TechDrawGui::TaskProjGroup::scaleManuallyChanged(), TechDrawGui::TaskProjGroup::scaleTypeChanged(), setScaleAttribute(), TechDrawGui::TaskSectionView::setUiEdit(), TechDrawGui::TaskDetail::setUiFromFeat(), TechDrawGui::TaskSectionView::setUiPrimary(), TechDrawGui::TaskProjGroup::TaskProjGroup(), TechDrawGui::TaskProjGroup::updateTask(), validateScale(), and TechDrawGui::TaskProjGroup::viewToggled().
signalGuiPaint
boost::signals2::signal<void (const DrawView*)> TechDraw::DrawView::signalGuiPaint
Referenced by requestPaint().
X
App::PropertyDistance TechDraw::DrawView::X
Referenced by TechDraw::DrawProjGroupItem::autoPosition(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::QGSPage::createBalloon(), TechDrawGui::QGILeaderLine::draw(), TechDrawGui::QGIViewBalloon::drawBalloon(), TechDrawGui::QGIViewClip::drawClip(), TechDrawGui::TaskDetail::getAnchorScene(), TechDrawGui::QGILeaderLine::getAttachFromFeature(), TechDraw::DrawLeaderLine::getAttachPoint(), TechDraw::DrawProjGroup::getBoundingBox(), TechDraw::DrawViewBalloon::getOriginOffset(), PathMachineState.MachineState::getPosition(), PathMachineState.MachineState::getState(), TechDraw::DrawProjGroup::getXYPosition(), handleChangedPropertyType(), handleXYLock(), TechDraw::DrawProjGroupItem::onChanged(), onChanged(), TechDrawGui::TaskDetail::onHighlightMoved(), TechDrawGui::TaskCosVertex::onTrackerFinished(), TechDrawGui::TaskLeaderLine::restoreState(), TechDrawGui::TaskLeaderLine::saveState(), TechDrawGui::QGILeaderLine::setLeaderFeature(), setPosition(), TechDrawGui::QGIViewBalloon::setViewPartFeature(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), and TechDrawGui::TaskRichAnno::TaskRichAnno().
Y
App::PropertyDistance TechDraw::DrawView::Y
Referenced by TechDraw::DrawProjGroupItem::autoPosition(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::QGSPage::createBalloon(), TechDrawGui::QGILeaderLine::draw(), TechDrawGui::QGIViewBalloon::drawBalloon(), TechDrawGui::QGIViewClip::drawClip(), TechDrawGui::TaskDetail::getAnchorScene(), TechDrawGui::QGILeaderLine::getAttachFromFeature(), TechDraw::DrawLeaderLine::getAttachPoint(), TechDraw::DrawProjGroup::getBoundingBox(), TechDraw::DrawViewBalloon::getOriginOffset(), PathMachineState.MachineState::getPosition(), PathMachineState.MachineState::getState(), TechDraw::DrawProjGroup::getXYPosition(), handleChangedPropertyType(), handleXYLock(), TechDraw::DrawProjGroupItem::onChanged(), onChanged(), TechDrawGui::TaskDetail::onHighlightMoved(), TechDrawGui::TaskCosVertex::onTrackerFinished(), TechDrawGui::TaskLeaderLine::restoreState(), TechDrawGui::TaskLeaderLine::saveState(), TechDrawGui::QGILeaderLine::setLeaderFeature(), setPosition(), TechDrawGui::QGIViewBalloon::setViewPartFeature(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), and TechDrawGui::TaskRichAnno::TaskRichAnno().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/App/DrawView.h
FreeCAD/src/Mod/TechDraw/App/DrawView.cpp