FreeCAD: PartGui::ReferenceHighlighter Class Reference
PartGui::ReferenceHighlighter Class Reference
The ReferenceHighlighter class.
#include <ReferenceHighlighter.h>
Public Member Functions
void getEdgeColors (const std::vector< std::string > &elements, std::vector< App::Color > &colors) const
getEdgeColors
void getFaceColors (const std::vector< std::string > &elements, std::vector< App::Color > &colors) const
getFaceColors
void getVertexColors (const std::vector< std::string > &elements, std::vector< App::Color > &colors) const
getVertexColors
ReferenceHighlighter (const TopoDS_Shape &shape, const App::Color &color)
ReferenceHighlighter.
void setDefaultColor (const App::Color &c)
void setElementColor (const App::Color &c)
void setObjectColor (const App::Color &c)
Detailed Description
The ReferenceHighlighter class.
Author
Werner Mayer
Constructor & Destructor Documentation
ReferenceHighlighter()
ReferenceHighlighter::ReferenceHighlighter (const TopoDS_Shape & shape, const App::Color & color)
ReferenceHighlighter.
Parameters
shape The input shape.
color The standard edge color.
Member Function Documentation
getEdgeColors()
void ReferenceHighlighter::getEdgeColors (const std::vector< std::string > & elements, std::vector< App::Color > & colors) const
getEdgeColors
Parameters
elements The sub-element names. If this list is empty colors will be filled with the default color.
colors The size of the colors array is equal to the number of edges of the shape
Referenced by PartDesignGui::ViewProviderDressUp::highlightReferences(), and FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences().
getFaceColors()
void ReferenceHighlighter::getFaceColors (const std::vector< std::string > & elements, std::vector< App::Color > & colors) const
getFaceColors
Parameters
elements The sub-element names. If this list is empty colors will be filled with the default color.
colors The size of the colors array is equal to the number of faces of the shape
Referenced by PartDesignGui::ViewProviderDressUp::highlightReferences(), and FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences().
getVertexColors()
void ReferenceHighlighter::getVertexColors (const std::vector< std::string > & elements, std::vector< App::Color > & colors) const
getVertexColors
Parameters
elements The sub-element names. If this list is empty colors will be filled with the default color.
colors The size of the colors array is equal to the number of vertexes of the shape
Referenced by FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences().
setDefaultColor()
void PartGui::ReferenceHighlighter::setDefaultColor (const App::Color & c)
setElementColor()
void PartGui::ReferenceHighlighter::setElementColor (const App::Color & c)
setObjectColor()
void PartGui::ReferenceHighlighter::setObjectColor (const App::Color & c)
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/ReferenceHighlighter.h
FreeCAD/src/Mod/Part/Gui/ReferenceHighlighter.cpp