FreeCAD: Base::AbortException Class Reference
Base::AbortException Class Reference
The AbortException is thrown if a pending operation was aborted.
#include <Exception.h>
Public Member Functions
AbortException ()
Construction.
AbortException (const char *sMessage)
Construction.
virtual Base::Type getTypeId (void) const
virtual const char * what () const throw ()
Description of the exception.
virtual ~AbortException () throw ()
Destruction.
Public Member Functions inherited from Base::Exception
std::string getFile () const
std::string getFunction () const
int getLine () const
std::string getMessage () const
virtual PyObject * getPyExceptionType () const
returns the corresponding python exception type
virtual PyObject * getPyObject (void)
returns a Python dictionary containing the exception data
bool getReported () const
bool getTranslatable () const
Exception & operator= (const Exception &inst)
virtual void ReportException (void) const
Reports exception. It includes a mechanism to only report an exception once.
void setDebugInformation (const std::string &file, const int line, const std::string &function)
setter methods for including debug information intended to use via macro for autofilling of debugging information
void setMessage (const char *sMessage)
void setMessage (const std::string &sMessage)
virtual void setPyException () const
Sets the Python error indicator and an error message.
virtual void setPyObject (PyObject *pydict)
returns sets the exception data from a Python dictionary
void setReported (bool reported)
void setTranslatable (bool translatable)
virtual ~Exception () throw ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static void * create (void)
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::Exception
static void * create (void)
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Additional Inherited Members
Protected Member Functions inherited from Base::Exception
Exception (const char *sMessage)
Exception (const Exception &inst)
Exception (const std::string &sMessage)
Exception (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The AbortException is thrown if a pending operation was aborted.
Author
Werner Mayer
Constructor & Destructor Documentation
AbortException() [1/2]
AbortException::AbortException (const char * sMessage)
Construction.
AbortException() [2/2]
AbortException::AbortException ()
Construction.
~AbortException()
virtual Base::AbortException::~AbortException () throw () virtual
Destruction.
Member Function Documentation
create()
void * Base::AbortException::create (void) static
Referenced by draftguitools.gui_labels.Label::action().
getClassTypeId()
Base::Type Base::AbortException::getClassTypeId (void) static
Referenced by Spreadsheet::Sheet::recomputeCell().
getTypeId()
Base::Type Base::AbortException::getTypeId (void) const virtual
Reimplemented from Base::Exception.
init()
void Base::AbortException::init (void) static
Referenced by App::Application::initTypes(), and DocumentObject.DocumentObject::onChanged().
what()
const char * AbortException::what (void) const throw () virtual
Description of the exception.
Reimplemented from Base::Exception.
References Base::Exception::what().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Base/Exception.h
Sources/FreeCAD/src/Base/Exception.cpp