FreeCAD: ReverseEngineeringGui::SegmentationManual Class Reference
ReverseEngineeringGui::SegmentationManual Class Reference
Dialog to create segments from components, regions, the complete or single faces of a mesh.
#include <SegmentationManual.h>
Classes
class Private
Public Slots
void on_cbSelectComp_toggled (bool)
void on_cylinderDetect_clicked ()
void on_deselectAll_clicked ()
void on_planeDetect_clicked ()
void on_screenTriangles_toggled (bool)
void on_selectAll_clicked ()
void on_selectComponents_clicked ()
void on_selectRegion_clicked ()
void on_selectTriangle_clicked ()
void on_sphereDetect_clicked ()
void on_visibleTriangles_toggled (bool)
Public Member Functions
void createSegment ()
void reject ()
SegmentationManual (QWidget *parent=0, Qt::WindowFlags fl=Qt::WindowFlags())
~SegmentationManual ()
Protected Member Functions
void changeEvent (QEvent *e)
Detailed Description
Dialog to create segments from components, regions, the complete or single faces of a mesh.
Author
Werner Mayer
Constructor & Destructor Documentation
SegmentationManual()
SegmentationManual::SegmentationManual (QWidget * parent = 0, Qt::WindowFlags fl = Qt::WindowFlags())
References Gui::SelectionSingleton::clearSelection(), Gui::Selection(), MeshGui::MeshSelection::setCheckOnlyPointToUserTriangles(), MeshGui::MeshSelection::setCheckOnlyVisibleTriangles(), and MeshGui::MeshSelection::setEnabledViewerSelection().
~SegmentationManual()
SegmentationManual::~SegmentationManual ()
Member Function Documentation
changeEvent()
void SegmentationManual::changeEvent (QEvent * e) protected
createSegment()
void SegmentationManual::createSegment ()
References Gui::Document::abortCommand(), Gui::Application::activeDocument(), App::Document::addObject(), Mesh::MeshObject::clearFacetSelection(), MeshGui::MeshSelection::clearSelection(), Gui::Document::commitCommand(), MeshCore::MeshAlgorithm::CountFacetFlag(), Mesh::MeshObject::deleteFacets(), Mesh::PropertyMeshKernel::finishEditing(), Gui::Document::getDocument(), MeshCore::MeshAlgorithm::GetFacetsFlag(), App::Document::getObjectsOfType(), Gui::Application::Instance, Mesh::Feature::Mesh, Gui::Document::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, MeshCore::MeshFacet::SELECTED, App::PropertyBool::setValue(), Mesh::PropertyMeshKernel::startEditing(), Mesh::MeshObject::swap(), and App::DocumentObject::Visibility.
Referenced by ReverseEngineeringGui::TaskSegmentationManual::clicked().
on_cbSelectComp_toggled
void SegmentationManual::on_cbSelectComp_toggled (bool on) slot
References MeshGui::MeshSelection::setAddComponentOnClick().
on_cylinderDetect_clicked
void SegmentationManual::on_cylinderDetect_clicked () slot
References MeshCore::Approximation::AddPoints(), ReverseEngineeringGui::SegmentationManual::Private::findGeometry(), MeshCore::CylinderFit::Fit(), MeshCore::CylinderFit::GetAxis(), MeshCore::CylinderFit::GetBase(), MeshCore::Approximation::GetGravity(), MeshCore::CylinderFit::GetInitialAxisFromNormals(), MeshCore::CylinderFit::GetRadius(), and MeshCore::CylinderFit::SetInitialValues().
on_deselectAll_clicked
void SegmentationManual::on_deselectAll_clicked () slot
References MeshGui::MeshSelection::clearSelection().
on_planeDetect_clicked
void SegmentationManual::on_planeDetect_clicked () slot
References MeshCore::Approximation::AddPoints(), ReverseEngineeringGui::SegmentationManual::Private::findGeometry(), MeshCore::PlaneFit::Fit(), MeshCore::PlaneFit::GetBase(), and MeshCore::PlaneFit::GetNormal().
on_screenTriangles_toggled
void SegmentationManual::on_screenTriangles_toggled (bool on) slot
References MeshGui::MeshSelection::setCheckOnlyPointToUserTriangles().
on_selectAll_clicked
void SegmentationManual::on_selectAll_clicked () slot
References MeshGui::MeshSelection::fullSelection().
on_selectComponents_clicked
void SegmentationManual::on_selectComponents_clicked () slot
References MeshGui::MeshSelection::selectComponent().
on_selectRegion_clicked
void SegmentationManual::on_selectRegion_clicked () slot
References MeshGui::MeshSelection::startSelection().
on_selectTriangle_clicked
void SegmentationManual::on_selectTriangle_clicked () slot
References MeshGui::MeshSelection::selectTriangle(), and MeshGui::MeshSelection::setAddComponentOnClick().
on_sphereDetect_clicked
void SegmentationManual::on_sphereDetect_clicked () slot
References MeshCore::Approximation::AddPoints(), ReverseEngineeringGui::SegmentationManual::Private::findGeometry(), MeshCore::SphereFit::Fit(), MeshCore::SphereFit::GetCenter(), and MeshCore::SphereFit::GetRadius().
on_visibleTriangles_toggled
void SegmentationManual::on_visibleTriangles_toggled (bool on) slot
References MeshGui::MeshSelection::setCheckOnlyVisibleTriangles().
reject()
void SegmentationManual::reject (void)
References MeshGui::MeshSelection::clearSelection(), and MeshGui::MeshSelection::setEnabledViewerSelection().
Referenced by ReverseEngineeringGui::TaskSegmentationManual::clicked().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/ReverseEngineering/Gui/SegmentationManual.h
Sources/FreeCAD/src/Mod/ReverseEngineering/Gui/SegmentationManual.cpp