FreeCAD: Fem Namespace Reference
Fem Namespace Reference
Classes
class Constraint
Base class of all Constraint Objects of the Fem module.
class ConstraintBearing
class ConstraintContact
class ConstraintDisplacement
class ConstraintFixed
class ConstraintFluidBoundary
class ConstraintForce
class ConstraintGear
class ConstraintHeatflux
class ConstraintInitialTemperature
class ConstraintPlaneRotation
class ConstraintPressure
class ConstraintPulley
class ConstraintTemperature
class ConstraintTransform
class DocumentObject
class FemAnalysis
Container of objects relevant to one simulation.
class FemMesh
The representation of a FemMesh.
class FemMeshObject
class FemMeshPy
The python export class for FemMesh.
class FemMeshShapeNetgenObject
class FemMeshShapeObject
class FemPostClipFilter
class FemPostCutFilter
class FemPostDataAlongLineFilter
class FemPostDataAtPointFilter
class FemPostFilter
class FemPostFunction
class FemPostFunctionProvider
class FemPostObject
class FemPostPipeline
class FemPostPipelinePy
The python export class for FemPostPipeline.
class FemPostPlaneFunction
class FemPostScalarClipFilter
class FemPostSphereFunction
class FemPostWarpVectorFilter
class FemResultObject
Father of all result data in a Fem Analysis.
class FemSetElementsObject
class FemSetFacesObject
class FemSetGeometryObject
class FemSetNodesObject
class FemSetObject
class FemSolverObject
Father of all result data in a Fem Analysis.
class FemVTKTools
class HypothesisPy
class Module
class PropertyFemMesh
The part shape property class.
class PropertyPostDataObject
The vtk data set property class.
class SMESH_HypothesisPy
class StdMeshers_Arithmetic1DPy
class StdMeshers_AutomaticLengthPy
class StdMeshers_CompositeSegment_1DPy
class StdMeshers_Deflection1DPy
class StdMeshers_Hexa_3DPy
class StdMeshers_LayerDistributionPy
class StdMeshers_LengthFromEdgesPy
class StdMeshers_LocalLengthPy
class StdMeshers_MaxElementAreaPy
class StdMeshers_MaxElementVolumePy
class StdMeshers_MaxLengthPy
class StdMeshers_MEFISTO_2DPy
class StdMeshers_NotConformAllowedPy
class StdMeshers_NumberOfLayersPy
class StdMeshers_NumberOfSegmentsPy
class StdMeshers_Prism_3DPy
class StdMeshers_Projection_1DPy
class StdMeshers_Projection_2DPy
class StdMeshers_Projection_3DPy
class StdMeshers_ProjectionSource1DPy
class StdMeshers_ProjectionSource2DPy
class StdMeshers_ProjectionSource3DPy
class StdMeshers_Quadrangle_2DPy
class StdMeshers_QuadranglePreferencePy
class StdMeshers_QuadraticMeshPy
class StdMeshers_RadialPrism_3DPy
class StdMeshers_Regular_1DPy
class StdMeshers_SegmentAroundVertex_0DPy
class StdMeshers_SegmentLengthAroundVertexPy
class StdMeshers_StartEndLengthPy
class StdMeshers_TrianglePreferencePy
class StdMeshers_UseExisting_1DPy
class StdMeshers_UseExisting_2DPy
class Tools
Typedefs
typedef App::FeaturePythonT< Constraint > ConstraintPython
typedef App::FeaturePythonT< DocumentObject > FeaturePython
typedef App::FeaturePythonT< FemAnalysis > FemAnalysisPython
typedef App::FeaturePythonT< FemMeshObject > FemMeshObjectPython
typedef App::FeaturePythonT< FemResultObject > FemResultObjectPython
typedef App::FeaturePythonT< FemSolverObject > FemSolverObjectPython
typedef Py::ExtensionObject< HypothesisPy > Hypothesis
typedef boost::shared_ptr< SMESH_Hypothesis > SMESH_HypothesisPtr
Functions
App::DocumentObject * createObjectByType (const Base::Type type)
void exportFemMeshCells (vtkSmartPointer< vtkUnstructuredGrid > grid, const SMDS_VolumeIteratorPtr &aVolIter)
void exportFemMeshFaces (vtkSmartPointer< vtkUnstructuredGrid > grid, const SMDS_FaceIteratorPtr &aFaceIter)
App::DocumentObject * getObjectByType (const Base::Type type)
PyObject * initModule ()
template<class TReader >
vtkDataSet * readVTKFile (const char *fileName)
template<class TWriter >
void writeVTKFile (const char *filename, vtkSmartPointer< vtkUnstructuredGrid > dataset)
Typedef Documentation
ConstraintPython
typedef App::FeaturePythonT<Constraint> Fem::ConstraintPython
FeaturePython
typedef App::FeaturePythonT<DocumentObject> Fem::FeaturePython
FemAnalysisPython
typedef App::FeaturePythonT<FemAnalysis> Fem::FemAnalysisPython
FemMeshObjectPython
typedef App::FeaturePythonT<FemMeshObject> Fem::FemMeshObjectPython
FemResultObjectPython
typedef App::FeaturePythonT<FemResultObject> Fem::FemResultObjectPython
FemSolverObjectPython
typedef App::FeaturePythonT<FemSolverObject> Fem::FemSolverObjectPython
Hypothesis
typedef Py::ExtensionObject<HypothesisPy> Fem::Hypothesis
SMESH_HypothesisPtr
typedef boost::shared_ptr<SMESH_Hypothesis> Fem::SMESH_HypothesisPtr
Function Documentation
createObjectByType()
App::DocumentObject* Fem::createObjectByType (const Base::Type type)
References App::Document::addObject(), Base::Console(), App::Application::getActiveDocument(), App::Document::getActiveObject(), App::GetApplication(), Base::Persistence::getClassTypeId(), Base::ConsoleSingleton::Message(), and App::Application::newDocument().
exportFemMeshCells()
void Fem::exportFemMeshCells (vtkSmartPointer< vtkUnstructuredGrid > grid, const SMDS_VolumeIteratorPtr & aVolIter)
References Base::Console(), SMDS_MeshElement::GetID(), SMDS_MeshElement::GetNode(), Base::ConsoleSingleton::Log(), and SMDS_MeshElement::NbNodes().
Referenced by Fem::FemVTKTools::exportVTKMesh().
exportFemMeshFaces()
void Fem::exportFemMeshFaces (vtkSmartPointer< vtkUnstructuredGrid > grid, const SMDS_FaceIteratorPtr & aFaceIter)
References Base::Console(), SMDS_MeshElement::GetID(), SMDS_MeshElement::GetNode(), Base::ConsoleSingleton::Log(), and SMDS_MeshElement::NbNodes().
Referenced by Fem::FemVTKTools::exportVTKMesh().
getObjectByType()
App::DocumentObject* Fem::getObjectByType (const Base::Type type)
References Base::Console(), App::Application::getActiveDocument(), App::Document::getActiveObject(), App::GetApplication(), Base::Persistence::getClassTypeId(), Base::ConsoleSingleton::Message(), and App::Application::newDocument().
initModule()
PyObject * Fem::initModule ()
readVTKFile()
template<class TReader > vtkDataSet* Fem::readVTKFile (const char * fileName)
writeVTKFile()
template<class TWriter > void Fem::writeVTKFile (const char * filename, vtkSmartPointer< vtkUnstructuredGrid > dataset)