FreeCAD: SMESH::Controls::TSequenceOfXYZ Class Reference
SMESH::Controls::TSequenceOfXYZ Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
void clear ()
const SMDS_MeshElement * getElement () const
SMDSAbs_EntityType getElementEntity () const
gp_XYZ & operator() (size_type n)
const gp_XYZ & operator() (size_type n) const
TSequenceOfXYZ & operator= (const TSequenceOfXYZ &theSequenceOfXYZ)
void push_back (const gp_XYZ &v)
void reserve (size_type n)
void setElement (const SMDS_MeshElement *e)
size_type size () const
TSequenceOfXYZ ()
TSequenceOfXYZ (const TSequenceOfXYZ &theSequenceOfXYZ)
template<class InputIterator >
TSequenceOfXYZ (InputIterator theBegin, InputIterator theEnd)
TSequenceOfXYZ (size_type n)
TSequenceOfXYZ (size_type n, const gp_XYZ &t)
~TSequenceOfXYZ ()
Constructor & Destructor Documentation
TSequenceOfXYZ() [1/5]
TSequenceOfXYZ::TSequenceOfXYZ ()
TSequenceOfXYZ() [2/5]
TSequenceOfXYZ::TSequenceOfXYZ (size_type n) explicit
TSequenceOfXYZ() [3/5]
TSequenceOfXYZ::TSequenceOfXYZ (size_type n, const gp_XYZ & t)
TSequenceOfXYZ() [4/5]
TSequenceOfXYZ::TSequenceOfXYZ (const TSequenceOfXYZ & theSequenceOfXYZ)
TSequenceOfXYZ() [5/5]
template<class InputIterator > TSequenceOfXYZ::TSequenceOfXYZ (InputIterator theBegin, InputIterator theEnd)
~TSequenceOfXYZ()
TSequenceOfXYZ::~TSequenceOfXYZ ()
Member Function Documentation
clear()
void TSequenceOfXYZ::clear ()
Referenced by SMESH::Controls::NumericalFunctor::GetPoints().
getElement()
const SMDS_MeshElement* SMESH::Controls::TSequenceOfXYZ::getElement () const
getElementEntity()
SMDSAbs_EntityType TSequenceOfXYZ::getElementEntity () const
References SMDS_MeshElement::GetEntityType().
Referenced by SMESH::Controls::Length2D::GetValue().
operator()() [1/2]
gp_XYZ & TSequenceOfXYZ::operator() (size_type n)
operator()() [2/2]
const gp_XYZ & TSequenceOfXYZ::operator() (size_type n) const
operator=()
TSequenceOfXYZ & TSequenceOfXYZ::operator= (const TSequenceOfXYZ & theSequenceOfXYZ)
push_back()
void TSequenceOfXYZ::push_back (const gp_XYZ & v)
Referenced by SMESH::Controls::NumericalFunctor::GetPoints().
reserve()
void TSequenceOfXYZ::reserve (size_type n)
Referenced by SMESH::Controls::NumericalFunctor::GetPoints().
setElement()
void SMESH::Controls::TSequenceOfXYZ::setElement (const SMDS_MeshElement * e)
Referenced by SMESH::Controls::NumericalFunctor::GetPoints().
size()
TSequenceOfXYZ::size_type TSequenceOfXYZ::size () const
Referenced by PathScripts.PostUtils.GCodeEditorDialog::done(), SMESH::Controls::MaxElementLength2D::GetValue(), SMESH::Controls::MinimumAngle::GetValue(), SMESH::Controls::AspectRatio::GetValue(), SMESH::Controls::AspectRatio3D::GetValue(), SMESH::Controls::Warping::GetValue(), SMESH::Controls::Taper::GetValue(), SMESH::Controls::Skew::GetValue(), SMESH::Controls::Area::GetValue(), SMESH::Controls::Length::GetValue(), SMESH::Controls::MaxElementLength3D::GetValue(), and SMESH::Controls::Length2D::GetValue().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp