FreeCAD: Gui::AlignmentView Class Reference
Gui::AlignmentView Class Reference
Public Member Functions
AlignmentView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
bool canClose ()
overwrite when checking on close state
PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
SoNode * setupHeadUpDisplay (const QString &text) const
~AlignmentView ()
Public Member Functions inherited from Gui::AbstractSplitView
AbstractSplitView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
virtual bool containsViewProvider (const ViewProvider *) const
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
virtual void deleteSelf ()
delete itself
virtual const char * getName (void) const
returns the name of the view (important for messages)
PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
int getSize ()
View3DInventorViewer * getViewer (unsigned int) const
virtual void OnChange (ParameterGrp::SubjectType &rCaller, ParameterGrp::MessageType Reason)
Observer message from the ParameterGrp.
virtual bool onHasMsg (const char *pMsg) const
Message handler test.
virtual bool onMsg (const char *pMsg, const char **ppReturn)
Message handler.
virtual void onUpdate (void)
get called when the document is updated
void setOverrideCursor (const QCursor &)
void setPyObject (PyObject *)
virtual void viewAll ()
~AbstractSplitView ()
Public Member Functions inherited from Gui::MDIView
virtual bool canClose (void)
overwrite when checking on close state
virtual void deleteSelf ()
delete itself
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
View constructor Attach the view to the given document.
virtual bool onHasMsg (const char *pMsg) const
Message handler test.
virtual bool onMsg (const char *pMsg, const char **ppReturn)
Message handler.
virtual void onRelabel (Gui::Document *pDoc)
get called when the document is updated
virtual void viewAll ()
~MDIView ()
View destructor Detach the view from the document, if attached.
virtual QStringList undoActions () const
virtual QStringList redoActions () const
QSize minimumSizeHint () const
virtual void setCurrentViewMode (ViewMode mode)
If b is set to FullScreen the MDI view is displayed in full screen mode, if b is set to TopLevel then it is displayed as an own top-level window, otherwise (Normal) as tabbed window.
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=nullptr, std::string *subname=nullptr) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr) const
virtual void print ()
Print content of view.
virtual void printPdf ()
Print to PDF file.
virtual void printPreview ()
Show a preview dialog.
void savePrinterSettings (QPrinter *printer)
Save the printer configuration.
void restorePrinterSettings (QPrinter *printer)
Restore the printer configuration.
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=nullptr)
View constructor Attach the view to the given document.
virtual ~BaseView ()
View destructor Detach the view from the document, if attached!
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose (void)
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive (void) const
indicates if the view is in passive mode
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Attributes
QLabel * myLabel
Additional Inherited Members
Public Types inherited from Gui::MDIView
enum ViewMode { Child , TopLevel , FullScreen }
MDI view mode enum.
Public Slots inherited from Gui::MDIView
virtual void restoreOverrideCursor ()
virtual void print (QPrinter *printer)
Signals inherited from Gui::MDIView
void message (const QString &, int)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Protected Slots inherited from Gui::MDIView
virtual void windowStateChanged (MDIView *)
This method gets called from the main window this view is attached to whenever the window state of the active view changes.
Protected Member Functions inherited from Gui::AbstractSplitView
void setupSettings ()
Protected Member Functions inherited from Gui::MDIView
void closeEvent (QCloseEvent *e)
void changeEvent (QEvent *e)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::AbstractSplitView
ParameterGrp::handle hGrp
handle to the viewer parameter group
Protected Attributes inherited from Gui::MDIView
PyObject * pythonObject
Protected Attributes inherited from Gui::BaseView
bool bIsDetached
bool bIsPassive
Constructor & Destructor Documentation
AlignmentView()
Gui::AlignmentView::AlignmentView (Gui::Document * pcDocument, QWidget * parent, Qt::WindowFlags wflags = Qt::WindowFlags())
References Gui::View3DInventorViewer::getNumSamples(), Gui::AbstractSplitView::getViewer(), myLabel, setupHeadUpDisplay(), and Gui::AbstractSplitView::setupSettings().
~AlignmentView()
Gui::AlignmentView::~AlignmentView ()
Member Function Documentation
canClose()
bool Gui::AlignmentView::canClose (void) virtual
overwrite when checking on close state
Reimplemented from Gui::MDIView.
getPyObject()
PyObject * Gui::AlignmentView::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Gui::MDIView.
setupHeadUpDisplay()
SoNode * Gui::AlignmentView::setupHeadUpDisplay (const QString & text) const
References Gui::BitmapFactory(), Gui::BitmapFactoryInst::convert(), and Gui::QtTools::horizontalAdvance().
Referenced by AlignmentView().
Member Data Documentation
myLabel
QLabel* Gui::AlignmentView::myLabel
Referenced by AlignmentView().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ManualAlignment.cpp