FreeCAD: Import::ImpExpDxfRead Class Reference
Import::ImpExpDxfRead Class Reference
#include <ImpExpDxf.h>
Public Member Functions
void AddGraphics () const
void AddObject (Part::TopoShape *shape)
std::string Deformat (const char *text)
std::string getOptionSource ()
ImpExpDxfRead (std::string filepath, App::Document *pcDoc)
void OnReadArc (const double *s, const double *e, const double *c, bool dir, bool hidden)
void OnReadCircle (const double *s, const double *c, bool dir, bool hidden)
void OnReadDimension (const double *s, const double *e, const double *point, double rotation)
void OnReadEllipse (const double *c, double major_radius, double minor_radius, double rotation, double start_angle, double end_angle, bool dir)
void OnReadInsert (const double *point, const double *scale, const char *name, double rotation)
void OnReadLine (const double *s, const double *e, bool hidden)
void OnReadPoint (const double *s)
void OnReadSpline (struct SplineData &sd)
void OnReadText (const double *point, const double height, const char *text)
void setOptions (void)
void setOptionSource (std::string s)
Public Member Functions inherited from CDxfRead
CDxfRead (const char *filepath)
CDxfRead (const char *filepath)
CDxfRead (const char *filepath)
void DoRead (const bool ignore_errors=false)
void DoRead (const bool ignore_errors=false)
void DoRead (const bool ignore_errors=false)
bool Failed ()
bool Failed ()
bool Failed ()
bool IgnoreErrors () const
bool IgnoreErrors () const
bool IgnoreErrors () const
std::string LayerName () const
std::string LayerName () const
std::string LayerName () const
double mm (const double &value) const
double mm (double value) const
double mm (double value) const
virtual void OnReadArc (const double *, const double *, const double *, bool)
virtual void OnReadCircle (const double *, const double *, bool)
virtual void OnReadLine (const double *, const double *)
virtual ~CDxfRead ()
virtual ~CDxfRead ()
virtual ~CDxfRead ()
Protected Attributes
App::Document * document
std::map< std::string, std::vector< Part::TopoShape * > > layers
std::string m_optionSource
bool optionGroupLayers
bool optionImportAnnotations
double optionScaling
Protected Attributes inherited from CDxfRead
Aci_t m_aci
Constructor & Destructor Documentation
ImpExpDxfRead()
ImpExpDxfRead::ImpExpDxfRead (std::string filepath, App::Document * pcDoc)
References document, setOptions(), and setOptionSource().
Member Function Documentation
AddGraphics()
void ImpExpDxfRead::AddGraphics () const virtual
Reimplemented from CDxfRead.
References App::Document::addObject(), document, optionGroupLayers, Part::PropertyPartShape::setValue(), and Part::Feature::Shape.
AddObject()
void ImpExpDxfRead::AddObject (Part::TopoShape * shape)
References App::Document::addObject(), document, CDxfRead::LayerName(), optionGroupLayers, Part::PropertyPartShape::setValue(), Part::Feature::Shape, and draftgeoutils.general::vec().
Referenced by OnReadArc(), OnReadCircle(), OnReadEllipse(), OnReadInsert(), OnReadLine(), and OnReadPoint().
Deformat()
std::string ImpExpDxfRead::Deformat (const char * text)
Referenced by OnReadText().
getOptionSource()
std::string Import::ImpExpDxfRead::getOptionSource ()
Referenced by setOptions().
OnReadArc()
void ImpExpDxfRead::OnReadArc (const double * s, const double * e, const double * c, bool dir, bool hidden) virtual
Reimplemented from CDxfRead.
References AddObject(), Base::Console(), and Base::ConsoleSingleton::Warning().
OnReadCircle()
void ImpExpDxfRead::OnReadCircle (const double * s, const double * c, bool dir, bool hidden) virtual
Reimplemented from CDxfRead.
References AddObject(), Base::Console(), and Base::ConsoleSingleton::Warning().
OnReadDimension()
void ImpExpDxfRead::OnReadDimension (const double * s, const double * e, const double * point, double rotation) virtual
Reimplemented from CDxfRead.
References Base::Interpreter(), optionImportAnnotations, optionScaling, Base::InterpreterSingleton::runString(), and Base::InterpreterSingleton::runStringArg().
OnReadEllipse()
void ImpExpDxfRead::OnReadEllipse (const double * c, double major_radius, double minor_radius, double rotation, double start_angle, double end_angle, bool dir) virtual
Reimplemented from CDxfRead.
References AddObject(), Base::Console(), optionScaling, and Base::ConsoleSingleton::Warning().
OnReadInsert()
void ImpExpDxfRead::OnReadInsert (const double * point, const double * scale, const char * name, double rotation) virtual
Reimplemented from CDxfRead.
References AddObject(), Base::Matrix4D::move(), optionScaling, Base::Matrix4D::rotZ(), Base::Matrix4D::scale(), and Part::TopoShape::transformShape().
OnReadLine()
void ImpExpDxfRead::OnReadLine (const double * s, const double * e, bool hidden) virtual
Reimplemented from CDxfRead.
References AddObject().
OnReadPoint()
void ImpExpDxfRead::OnReadPoint (const double * s) virtual
Reimplemented from CDxfRead.
References AddObject().
OnReadSpline()
void ImpExpDxfRead::OnReadSpline (struct SplineData & sd) virtual
Reimplemented from CDxfRead.
OnReadText()
void ImpExpDxfRead::OnReadText (const double * point, const double height, const char * text) virtual
Reimplemented from CDxfRead.
References App::Document::addObject(), Deformat(), document, App::Annotation::LabelText, CDxfRead::LayerName(), optionImportAnnotations, optionScaling, App::Annotation::Position, App::PropertyVector::setValue(), and App::PropertyListsT< T, ListT, ParentT >::setValue().
setOptions()
void ImpExpDxfRead::setOptions (void)
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetFloat(), getOptionSource(), App::Application::GetParameterGroupByPath(), optionGroupLayers, optionImportAnnotations, and optionScaling.
Referenced by ImpExpDxfRead().
setOptionSource()
void Import::ImpExpDxfRead::setOptionSource (std::string s)
Referenced by ImpExpDxfRead().
Member Data Documentation
document
App::Document* Import::ImpExpDxfRead::document protected
Referenced by AddGraphics(), AddObject(), ImpExpDxfRead(), OnReadText(), Mod.Show.mTempoVis.TempoVis::restoreCamera(), Mod.Show.mTempoVis.TempoVis::saveCamera(), and Mod.Show.TVStack.TVStack::unwindForSaving().
layers
std::map<std::string, std::vector <Part::TopoShape*> > Import::ImpExpDxfRead::layers protected
m_optionSource
std::string Import::ImpExpDxfRead::m_optionSource protected
optionGroupLayers
bool Import::ImpExpDxfRead::optionGroupLayers protected
Referenced by AddGraphics(), AddObject(), and setOptions().
optionImportAnnotations
bool Import::ImpExpDxfRead::optionImportAnnotations protected
Referenced by OnReadDimension(), OnReadText(), and setOptions().
optionScaling
double Import::ImpExpDxfRead::optionScaling protected
Referenced by OnReadDimension(), OnReadEllipse(), OnReadInsert(), OnReadText(), and setOptions().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Import/App/ImpExpDxf.h
Sources/FreeCAD/src/Mod/Import/App/ImpExpDxf.cpp