FreeCAD: Import::StepShapePy Class Reference
Import::StepShapePy Class Reference
The python export class for StepShape.
#include <StepShapePy.h>
Public Types
typedef StepShape * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
StepShapePy (StepShape *pcObject, PyTypeObject *T=&Type)
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
StepShape * getStepShapePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of StepShapePy.
static PyMethodDef Methods []
Methods structure of StepShapePy.
static PyTypeObject Type
Type structure of StepShapePy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~StepShapePy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * read (PyObject *args)
implementer for the read() method
static PyObject * staticCallback_read (PyObject *self, PyObject *args)
callback for the read() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for StepShape.
Member Typedef Documentation
PointerType
typedef StepShape* Import::StepShapePy::PointerType
Constructor & Destructor Documentation
~StepShapePy()
StepShapePy::~StepShapePy () protected
StepShapePy()
StepShapePy::StepShapePy (StepShape * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getCustomAttributes()
PyObject * StepShapePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getStepShapePtr()
StepShape * StepShapePy::getStepShapePtr (void) const
getter for the object handled by this class
Referenced by PyInit().
GetType()
virtual PyTypeObject* Import::StepShapePy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
PyInit()
int StepShapePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
References getStepShapePtr(), and Import::StepShape::read().
PyMake()
PyObject * StepShapePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References StepShapePy().
read()
PyObject * StepShapePy::read (PyObject * args)
implementer for the read() method
Referenced by gzip_utf8.GzipFile::readline(), gzip_utf8.GzipFile::seek(), and staticCallback_read().
representation()
std::string StepShapePy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int StepShapePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_read()
PyObject * StepShapePy::staticCallback_read (PyObject * self, PyObject * args) static
callback for the read() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), read(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef StepShapePy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of StepShapePy.
Methods
PyMethodDef StepShapePy::Methods static
Initial value:
= {
    {"read",
        reinterpret_cast<PyCFunction>( staticCallback_read ),
        METH_VARARGS,
        "method read()\nRead a STEP file into memory and make it accessible\n                     "
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of StepShapePy.
Type
PyTypeObject StepShapePy::Type static
Type structure of StepShapePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Import/App/StepShapePy.h
Sources/FreeCAD/src/Mod/Import/App/StepShapePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Import/App/StepShapePy.cpp