FreeCAD: Cloud::CloudReader Class Reference
Cloud::CloudReader Class Reference
#include <AppCloud.h>
Classes
struct FileEntry
Public Member Functions
void addFile (struct Cloud::CloudReader::FileEntry *new_entry)
void checkElement (XERCES_CPP_NAMESPACE_QUALIFIER DOMElement *element)
void checkText (XERCES_CPP_NAMESPACE_QUALIFIER DOMText *text)
void checkXML (XERCES_CPP_NAMESPACE_QUALIFIER DOMNode *node)
CloudReader (const char *URL, const char *AccessKey, const char *SecretKey, const char *TCPPort, const char *Bucket, std::string ProtocolVersion, std::string Region)
void DownloadFile (Cloud::CloudReader::FileEntry *entry)
struct FileEntry * GetEntry (std::string FileName)
int isTouched (std::string FileName)
virtual ~CloudReader ()
Public Attributes
int continuation =0
int file =0
int truncated =0
Protected Attributes
const char * Bucket
std::list< Cloud::CloudReader::FileEntry * > FileList
char * NextFileName
std::string ProtocolVersion
std::string Region
const char * TCPPort
const char * TokenAuth
const char * TokenSecret
const char * URL
Constructor & Destructor Documentation
CloudReader()
Cloud::CloudReader::CloudReader (const char * URL, const char * AccessKey, const char * SecretKey, const char * TCPPort, const char * Bucket, std::string ProtocolVersion, std::string Region)
References Cloud::BuildHeaderAmzS3v2(), Cloud::BuildHeaderAmzS3v4(), Cloud::ComputeDigestAmzS3v2(), Cloud::ComputeDigestAmzS3v4(), Cloud::CurlWrite_CallbackFunc_StdString(), Cloud::eraseSubStr(), and NextFileName.
~CloudReader()
Cloud::CloudReader::~CloudReader () virtual
Member Function Documentation
addFile()
void Cloud::CloudReader::addFile (struct Cloud::CloudReader::FileEntry * new_entry)
References FileList.
checkElement()
void Cloud::CloudReader::checkElement (XERCES_CPP_NAMESPACE_QUALIFIER DOMElement * element)
Referenced by checkXML().
checkText()
void Cloud::CloudReader::checkText (XERCES_CPP_NAMESPACE_QUALIFIER DOMText * text)
References continuation, file, FileList, Cloud::CloudReader::FileEntry::FileName, NextFileName, and truncated.
Referenced by checkXML().
checkXML()
void Cloud::CloudReader::checkXML (XERCES_CPP_NAMESPACE_QUALIFIER DOMNode * node)
References checkElement(), checkText(), and checkXML().
Referenced by checkXML().
DownloadFile()
void Cloud::CloudReader::DownloadFile (Cloud::CloudReader::FileEntry * entry)
References Cloud::BuildHeaderAmzS3v2(), Cloud::BuildHeaderAmzS3v4(), Cloud::ComputeDigestAmzS3v2(), Cloud::ComputeDigestAmzS3v4(), Cloud::CurlWrite_CallbackFunc_StdString(), Cloud::eraseSubStr(), Cloud::CloudReader::FileEntry::FileName, and Cloud::CloudReader::FileEntry::FileStream.
Referenced by GetEntry().
GetEntry()
struct Cloud::CloudReader::FileEntry * Cloud::CloudReader::GetEntry (std::string FileName)
References DownloadFile(), FileList, Cloud::CloudReader::FileEntry::FileName, and Cloud::CloudReader::FileEntry::touch.
Referenced by Cloud::Module::cloudRestore().
isTouched()
int Cloud::CloudReader::isTouched (std::string FileName)
References FileList, and Cloud::CloudReader::FileEntry::FileName.
Member Data Documentation
Bucket
const char* Cloud::CloudReader::Bucket protected
continuation
int Cloud::CloudReader::continuation =0
Referenced by checkText().
file
int Cloud::CloudReader::file =0
Referenced by checkText(), exportIFCHelper.ContextCreator::createAutomaticProject(), exportIFCHelper.ContextCreator::createCustomProject(), exportIFCHelper.ContextCreator::createGeometricRepresentationContext(), exportIFCHelper.ContextCreator::createGeometricRepresentationSubContext(), exportIFCHelper.ContextCreator::createMapConversion(), exportIFCHelper.ContextCreator::createTargetCRS(), exportIFCHelper.ContextCreator::createTrueNorth(), Cloud::CloudWriter::putNextEntry(), and importIFClegacy.IfcFile::read().
FileList
std::list<Cloud::CloudReader::FileEntry*> Cloud::CloudReader::FileList protected
Referenced by addFile(), checkText(), GetEntry(), and isTouched().
NextFileName
char* Cloud::CloudReader::NextFileName protected
Referenced by checkText(), and CloudReader().
ProtocolVersion
std::string Cloud::CloudReader::ProtocolVersion protected
Region
std::string Cloud::CloudReader::Region protected
TCPPort
const char* Cloud::CloudReader::TCPPort protected
TokenAuth
const char* Cloud::CloudReader::TokenAuth protected
TokenSecret
const char* Cloud::CloudReader::TokenSecret protected
truncated
int Cloud::CloudReader::truncated =0
Referenced by checkText().
URL
const char* Cloud::CloudReader::URL protected
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Cloud/App/AppCloud.h
FreeCAD/src/Mod/Cloud/App/AppCloud.cpp