FreeCAD: Sandbox::AbstractCustomProtectorEvent Class Reference
Sandbox::AbstractCustomProtectorEvent Class Reference abstract
Public Member Functions
AbstractCustomProtectorEvent ()
virtual void execute ()=0
~AbstractCustomProtectorEvent ()
Public Attributes
QSemaphore * semaphore
Constructor & Destructor Documentation
AbstractCustomProtectorEvent()
Sandbox::AbstractCustomProtectorEvent::AbstractCustomProtectorEvent ()
~AbstractCustomProtectorEvent()
Sandbox::AbstractCustomProtectorEvent::~AbstractCustomProtectorEvent ()
References semaphore.
Member Function Documentation
execute()
virtual void Sandbox::AbstractCustomProtectorEvent::execute () pure virtual
Implemented in Sandbox::CustomPurgeEvent, Sandbox::CustomCallableEvent, Sandbox::CustomPropertyEvent, Sandbox::CustomRecomputeEvent, Sandbox::CustomRemoveObjectEvent, and Sandbox::CustomAddObjectEvent.
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), PathScripts.PathDressupDogbone.ObjectDressup::boneStateList(), ArchSite.Compass::buildCoordinates(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::generateTags(), ArchPanel.PanelCut::getWires(), ArchSchedule.CommandArchSchedule::IsActive(), Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), FeaturePython.DistanceBolt::onChanged(), PathScripts.PathStock.StockFromBase::onChanged(), PathScripts.PathStock.StockCreateBox::onChanged(), PathScripts.PathStock.StockCreateCylinder::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), draftobjects.patharray.PathArray::onDocumentRestored(), and draftobjects.pathtwistedarray.PathTwistedArray::onDocumentRestored().
Member Data Documentation
semaphore
QSemaphore* Sandbox::AbstractCustomProtectorEvent::semaphore
Referenced by ~AbstractCustomProtectorEvent().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sandbox/App/DocumentProtector.cpp