FreeCAD: ArchRebar Namespace Reference
ArchRebar Namespace Reference
Workbenches » Python workbenches » Arch
The Rebar object and tools.
Functions
def CalculatePlacement (baramount, barnumber, bardiameter, size, axis, rotation, offsetstart, offsetend, RebarShape="")
def CustomSpacingPlacement (spacinglist, barnumber, axis, rotation, offsetstart, offsetend)
def getLengthOfRebar (rebar)
def makeRebar (baseobj=None, sketch=None, diameter=None, amount=1, offset=None, name="Rebar")
def strprocessOfCustomSpacing (span_string)
Detailed Description
The Rebar object and tools.
This module provides tools to build Rebar objects. Rebars (or Reinforcing Bars) are metallic bars placed inside concrete structures to reinforce them.
Function Documentation
CalculatePlacement()
def ArchRebar.CalculatePlacement (baramount, barnumber, bardiameter, size, axis, rotation, offsetstart, offsetend, RebarShape = "")
 CalculatePlacement([baramount, barnumber, bardiameter, size, axis, rotation, offsetstart, offsetend, RebarShape]):
Calculate the placement of the bar from given values.
References DraftVecUtils.scaleTo().
Referenced by makeRebar().
CustomSpacingPlacement()
def ArchRebar.CustomSpacingPlacement (spacinglist, barnumber, axis, rotation, offsetstart, offsetend)
 CustomSpacingPlacement(spacinglist, barnumber, axis, rotation, offsetstart, offsetend):
Calculate placement of the bar from custom spacing list.
References DraftVecUtils.scaleTo().
Referenced by makeRebar().
getLengthOfRebar()
def ArchRebar.getLengthOfRebar (rebar)
 getLengthOfRebar(RebarObject): Calculates the length of the rebar.
Referenced by makeRebar().
makeRebar()
def ArchRebar.makeRebar (baseobj = None, sketch = None, diameter = None, amount = 1, offset = None, name = "Rebar")
makeRebar([baseobj,sketch,diameter,amount,offset,name]): adds a Reinforcement Bar object
to the given structural object, using the given sketch as profile.
References ArchComponent.ViewProviderComponent.attach(), CalculatePlacement(), CustomSpacingPlacement(), draftgeoutils.fillets.filletWire(), ArchCommands.getDefaultColor(), ArchComponent.ViewProviderComponent.getDisplayModes(), getLengthOfRebar(), DraftVecUtils.isNull(), ArchComponent.ViewProviderComponent.onChanged(), ArchComponent.Component.onDocumentRestored(), ArchCommands.projectToVector(), draftutils.translate.QT_TRANSLATE_NOOP, DraftVecUtils.scaleTo(), strprocessOfCustomSpacing(), and ArchComponent.ViewProviderComponent.updateData().
strprocessOfCustomSpacing()
def ArchRebar.strprocessOfCustomSpacing (span_string)
 strprocessOfCustomSpacing(span_string): This function take input
in specific syntax and return output in the form of list. For eg.
Input: "3@100+2@200+3@100"
Output: [100, 100, 100, 200, 200, 100, 100, 100]
References DraftVecUtils.find().
Referenced by makeRebar().