FreeCAD: PathScripts.PathToolController.ToolController Class Reference
PathScripts.PathToolController.ToolController Class Reference
Public Member Functions
def ensureUseLegacyTool (self, obj, legacy)
def execute (self, obj)
def getTool (self, obj)
def onDelete (self, obj, arg2=None)
def onDocumentRestored (self, obj)
def setFromTemplate (self, obj, template)
def templateAttrs (self, obj)
def usesLegacyTool (self, obj)
Member Function Documentation
ensureUseLegacyTool()
def PathScripts.PathToolController.ToolController.ensureUseLegacyTool (self, obj, legacy)
References PathScripts.PathToolController.ToolController.usesLegacyTool().
Referenced by PathScripts.PathToolController.ToolController.setFromTemplate().
execute()
def PathScripts.PathToolController.ToolController.execute (self, obj)
Referenced by ArchSite.Compass.buildCoordinates(), ArchSchedule.CommandArchSchedule.IsActive(), and FeaturePython.DistanceBolt.onChanged().
getTool()
def PathScripts.PathToolController.ToolController.getTool (self, obj)
returns the tool associated with this tool controller
onDelete()
def PathScripts.PathToolController.ToolController.onDelete (self, obj, arg2 = None)
References PathScripts.PathToolController.ToolController.usesLegacyTool().
onDocumentRestored()
def PathScripts.PathToolController.ToolController.onDocumentRestored (self, obj)
setFromTemplate()
def PathScripts.PathToolController.ToolController.setFromTemplate (self, obj, template)
setFromTemplate(obj, xmlItem) ... extract properties from xmlItem
and assign to receiver.
References PathScripts.PathToolController.ToolController.ensureUseLegacyTool().
templateAttrs()
def PathScripts.PathToolController.ToolController.templateAttrs (self, obj)
templateAttrs(obj) ... answer a dictionary with all properties that should be stored for a template.
References PathScripts.PathToolController.ToolController.usesLegacyTool().
Referenced by PathScripts.PathToolLibraryManager.ToolLibraryManager.saveMainLibrary(), and PathScripts.PathToolLibraryManager.ToolLibraryManager.write().
usesLegacyTool()
def PathScripts.PathToolController.ToolController.usesLegacyTool (self, obj)
returns True if the tool being controlled is a legacy tool
Referenced by PathScripts.PathToolController.ToolController.ensureUseLegacyTool(), PathScripts.PathToolController.ToolController.onDelete(), and PathScripts.PathToolController.ToolController.templateAttrs().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Path/PathScripts/PathToolController.py