FreeCAD: FemGui::TaskFemConstraintFluidBoundary Class Reference
FemGui::TaskFemConstraintFluidBoundary Class Reference
#include <TaskFemConstraintFluidBoundary.h>
Public Member Functions
std::string getBoundaryType (void) const
double getBoundaryValue (void) const
const std::string getDirectionName (void) const
const std::string getDirectionObject (void) const
const Fem::FemSolverObject * getFemSolver (void) const
double getHeatFluxValue (void) const
bool getHeatTransferring (void) const
double getHTCoeffValue (void) const
const std::string getReferences () const
bool getReverse (void) const
std::string getSubtype (void) const
double getTemperatureValue (void) const
std::string getThermalBoundaryType (void) const
std::string getTurbulenceModel (void) const
std::string getTurbulenceSpecification (void) const
double getTurbulentIntensityValue (void) const
double getTurbulentLengthValue (void) const
TaskFemConstraintFluidBoundary (ViewProviderFemConstraintFluidBoundary *ConstraintView, QWidget *parent=nullptr)
virtual ~TaskFemConstraintFluidBoundary ()
Public Member Functions inherited from FemGui::TaskFemConstraintOnBoundary
TaskFemConstraintOnBoundary (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="")
~TaskFemConstraintOnBoundary ()
Public Member Functions inherited from FemGui::TaskFemConstraint
const std::string getReferences (const std::vector< std::string > &items) const
virtual const std::string getReferences (void) const
const std::string getScale () const
TaskFemConstraint (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="")
virtual ~TaskFemConstraint ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Protected Member Functions
virtual void changeEvent (QEvent *e)
void clearButtons (const SelectionChangeModes notThis) override
bool event (QEvent *e)
Protected Member Functions inherited from FemGui::TaskFemConstraintOnBoundary
virtual void clearButtons (const SelectionChangeModes notThis)=0
virtual void onSelectionChanged (const Gui::SelectionChanges &) override
Protected Member Functions inherited from FemGui::TaskFemConstraint
virtual void changeEvent (QEvent *e)
void createDeleteAction (QListWidget *parentList)
bool KeyEvent (QEvent *e)
virtual void keyPressEvent (QKeyEvent *ke)
const QString makeRefText (const App::DocumentObject *obj, const std::string &subName) const
const QString makeRefText (const std::string &objName, const std::string &subName) const
virtual void onSelectionChanged (const Gui::SelectionChanges &)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Types inherited from FemGui::TaskFemConstraintOnBoundary
enum class SelectionChangeModes { none , refAdd , refRemove }
Protected Types inherited from FemGui::TaskFemConstraint
enum { seldir , selref , selloc , selnone }
Protected Slots inherited from FemGui::TaskFemConstraintOnBoundary
virtual void addToSelection ()=0
void onButtonToggled (QAbstractButton *button, bool checked)
virtual void removeFromSelection ()=0
Protected Slots inherited from FemGui::TaskFemConstraint
void onButtonReference (const bool pressed=true)
void onButtonWizCancel ()
void onButtonWizOk ()
void onReferenceDeleted (const int row)
void setSelection (QListWidgetItem *item)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from FemGui::TaskFemConstraintOnBoundary
Gui::ButtonGroup * buttonGroup
enum SelectionChangeModes selChangeMode
Protected Attributes inherited from FemGui::TaskFemConstraint
Gui::WeakPtrT< ViewProviderFemConstraint > ConstraintView
QAction * deleteAction
QWidget * proxy
enum FemGui::TaskFemConstraint:: { ... } selectionMode
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskFemConstraintFluidBoundary()
TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary (ViewProviderFemConstraintFluidBoundary * ConstraintView, QWidget * parent = nullptr)
References Fem::ConstraintFluidBoundary::BoundaryType, Fem::ConstraintFluidBoundary::BoundaryValue, Ui_TaskFemConstraintFluidBoundary::btnAdd, Ui_TaskFemConstraintFluidBoundary::btnRemove, Ui_TaskFemConstraintFluidBoundary::buttonDirection, FemGui::TaskFemConstraintOnBoundary::buttonGroup, Ui_TaskFemConstraintFluidBoundary::checkReverse, Ui_TaskFemConstraintFluidBoundary::comboBoundaryType, Ui_TaskFemConstraintFluidBoundary::comboSubtype, Ui_TaskFemConstraintFluidBoundary::comboThermalBoundaryType, Ui_TaskFemConstraintFluidBoundary::comboTurbulenceSpecification, draftgeoutils.intersections::connect(), Base::Console(), FemGui::TaskFemConstraint::ConstraintView, FemGui::TaskFemConstraint::createDeleteAction(), FemGui::TaskFemConstraint::deleteAction, Fem::ConstraintFluidBoundary::Direction, Base::Tools::fromStdString(), FemGui::ActiveAnalysisObserver::getActiveObject(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::PropertyEnumeration::getEnumVector(), App::Document::getObjectsOfType(), App::ExtensionContainer::getPropertyByName(), Part::PropertyPartShape::getShape(), Part::TopoShape::getShape(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSubList::getSubValues(), Base::Persistence::getTypeId(), App::PropertyLink::getValue(), App::PropertyLinkSub::getValue(), App::PropertyFloat::getValue(), App::PropertyBool::getValue(), App::PropertyEnumeration::getValueAsString(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyLinkSubList::getValues(), App::GroupExtension::Group, QSint::ActionGroup::groupLayout(), FemGui::ActiveAnalysisObserver::hasActiveObject(), Fem::ConstraintFluidBoundary::HeatFluxValue, Fem::ConstraintFluidBoundary::HTCoeffValue, FemGui::ActiveAnalysisObserver::instance(), Base::Type::isDerivedFrom(), Ui_TaskFemConstraintFluidBoundary::labelHelpText, Ui_TaskFemConstraintFluidBoundary::labelTurbulenceSpecification, Ui_TaskFemConstraintFluidBoundary::lineDirection, Ui_TaskFemConstraintFluidBoundary::listReferences, Base::ConsoleSingleton::Log(), FemGui::TaskFemConstraint::makeRefText(), FemGui::TaskFemConstraint::proxy, FemGui::TaskFemConstraintOnBoundary::refAdd, Fem::Constraint::References, FemGui::TaskFemConstraintOnBoundary::refRemove, FemGui::TaskFemConstraint::setSelection(), Ui_TaskFemConstraintFluidBoundary::setupUi(), Part::Feature::Shape, Ui_TaskFemConstraintFluidBoundary::spinBoundaryValue, Ui_TaskFemConstraintFluidBoundary::spinHeatFluxValue, Ui_TaskFemConstraintFluidBoundary::spinHTCoeffValue, Ui_TaskFemConstraintFluidBoundary::spinTemperatureValue, Ui_TaskFemConstraintFluidBoundary::spinTurbulentIntensityValue, Ui_TaskFemConstraintFluidBoundary::spinTurbulentLengthValue, Fem::ConstraintFluidBoundary::Subtype, Ui_TaskFemConstraintFluidBoundary::tabThermalBoundary, Ui_TaskFemConstraintFluidBoundary::tabTurbulenceBoundary, Ui_TaskFemConstraintFluidBoundary::tabWidget, Fem::ConstraintFluidBoundary::TemperatureValue, Fem::ConstraintFluidBoundary::ThermalBoundaryType, Fem::ConstraintFluidBoundary::TurbulenceSpecification, Fem::ConstraintFluidBoundary::TurbulentIntensityValue, Fem::ConstraintFluidBoundary::TurbulentLengthValue, and Base::ConsoleSingleton::Warning().
~TaskFemConstraintFluidBoundary()
TaskFemConstraintFluidBoundary::~TaskFemConstraintFluidBoundary () virtual
Member Function Documentation
changeEvent()
void TaskFemConstraintFluidBoundary::changeEvent (QEvent * e) protected virtual
Reimplemented from FemGui::TaskFemConstraint.
References FemGui::TaskFemConstraint::proxy, Ui_TaskFemConstraintFluidBoundary::retranslateUi(), and Ui_TaskFemConstraintFluidBoundary::spinBoundaryValue.
clearButtons()
void TaskFemConstraintFluidBoundary::clearButtons (const SelectionChangeModes notThis) override protected virtual
Implements FemGui::TaskFemConstraintOnBoundary.
References Ui_TaskFemConstraintFluidBoundary::btnAdd, Ui_TaskFemConstraintFluidBoundary::btnRemove, FemGui::TaskFemConstraintOnBoundary::refAdd, and FemGui::TaskFemConstraintOnBoundary::refRemove.
event()
bool TaskFemConstraintFluidBoundary::event (QEvent * e) protected
References FemGui::TaskFemConstraint::KeyEvent().
getBoundaryType()
std::string TaskFemConstraintFluidBoundary::getBoundaryType (void) const
References Ui_TaskFemConstraintFluidBoundary::comboBoundaryType, and Base::Tools::toStdString().
Referenced by FemGui::TaskDlgFemConstraintFluidBoundary::accept().
getBoundaryValue()
double TaskFemConstraintFluidBoundary::getBoundaryValue (void) const
References Ui_TaskFemConstraintFluidBoundary::spinBoundaryValue.
Referenced by FemGui::TaskDlgFemConstraintFluidBoundary::accept().
getDirectionName()
const std::string TaskFemConstraintFluidBoundary::getDirectionName (void) const
References Ui_TaskFemConstraintFluidBoundary::lineDirection.
Referenced by FemGui::TaskDlgFemConstraintFluidBoundary::accept().
getDirectionObject()
const std::string TaskFemConstraintFluidBoundary::getDirectionObject (void) const
References Ui_TaskFemConstraintFluidBoundary::lineDirection.
Referenced by FemGui::TaskDlgFemConstraintFluidBoundary::accept().
getFemSolver()
const Fem::FemSolverObject * TaskFemConstraintFluidBoundary::getFemSolver (void) const
Referenced by FemGui::TaskDlgFemConstraintFluidBoundary::accept().
getHeatFluxValue()
double TaskFemConstraintFluidBoundary::getHeatFluxValue (void) const
References Ui_TaskFemConstraintFluidBoundary::spinHeatFluxValue.
Referenced by FemGui::TaskDlgFemConstraintFluidBoundary::accept().
getHeatTransferring()
bool TaskFemConstraintFluidBoundary::getHeatTransferring (void) const
References App::PropertyBool::getValue().
getHTCoeffValue()
double TaskFemConstraintFluidBoundary::getHTCoeffValue (void) const
References Ui_TaskFemConstraintFluidBoundary::spinHTCoeffValue.
Referenced by FemGui::TaskDlgFemConstraintFluidBoundary::accept().
getReferences()
const std::string TaskFemConstraintFluidBoundary::getReferences (void) const virtual
Reimplemented from FemGui::TaskFemConstraint.
References FemGui::TaskFemConstraint::getReferences(), and Ui_TaskFemConstraintFluidBoundary::listReferences.
getReverse()
bool TaskFemConstraintFluidBoundary::getReverse (void) const
References Ui_TaskFemConstraintFluidBoundary::checkReverse.
getSubtype()
std::string TaskFemConstraintFluidBoundary::getSubtype (void) const
References Ui_TaskFemConstraintFluidBoundary::comboSubtype, and Base::Tools::toStdString().
Referenced by FemGui::TaskDlgFemConstraintFluidBoundary::accept().
getTemperatureValue()
double TaskFemConstraintFluidBoundary::getTemperatureValue (void) const
References Ui_TaskFemConstraintFluidBoundary::spinTemperatureValue.
Referenced by FemGui::TaskDlgFemConstraintFluidBoundary::accept().
getThermalBoundaryType()
std::string TaskFemConstraintFluidBoundary::getThermalBoundaryType (void) const
References Ui_TaskFemConstraintFluidBoundary::comboThermalBoundaryType, and Base::Tools::toStdString().
Referenced by FemGui::TaskDlgFemConstraintFluidBoundary::accept().
getTurbulenceModel()
std::string TaskFemConstraintFluidBoundary::getTurbulenceModel (void) const
References App::PropertyEnumeration::getValueAsString().
getTurbulenceSpecification()
std::string TaskFemConstraintFluidBoundary::getTurbulenceSpecification (void) const
References Ui_TaskFemConstraintFluidBoundary::comboTurbulenceSpecification, and Base::Tools::toStdString().
Referenced by FemGui::TaskDlgFemConstraintFluidBoundary::accept().
getTurbulentIntensityValue()
double TaskFemConstraintFluidBoundary::getTurbulentIntensityValue (void) const
References Ui_TaskFemConstraintFluidBoundary::spinTurbulentIntensityValue.
Referenced by FemGui::TaskDlgFemConstraintFluidBoundary::accept().
getTurbulentLengthValue()
double TaskFemConstraintFluidBoundary::getTurbulentLengthValue (void) const
References Ui_TaskFemConstraintFluidBoundary::spinTurbulentLengthValue.
Referenced by FemGui::TaskDlgFemConstraintFluidBoundary::accept().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintFluidBoundary.h
FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintFluidBoundary.cpp