FreeCAD: Gui::Dialog::DlgCustomCommandsImp Class Reference
Gui::Dialog::DlgCustomCommandsImp Class Reference
Shows an overview of all available commands of all groups and modules.
#include <DlgCommandsImp.h>
Public Member Functions
DlgCustomCommandsImp (QWidget *parent=0)
Constructs a DlgCustomCommandsImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
~DlgCustomCommandsImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::CustomizeActionPage
CustomizeActionPage (QWidget *parent=0)
Construction.
virtual ~CustomizeActionPage ()
Destruction.
Protected Slots
void onAddMacroAction (const QByteArray &)
void onDescription (QTreeWidgetItem *i)
Shows the description for the corresponding command.
void onGroupActivated (QTreeWidgetItem *i)
Shows all commands of this category.
void onModifyMacroAction (const QByteArray &)
void onRemoveMacroAction (const QByteArray &)
Protected Slots inherited from Gui::Dialog::CustomizeActionPage
virtual void onAddMacroAction (const QByteArray &)=0
virtual void onModifyMacroAction (const QByteArray &)=0
virtual void onRemoveMacroAction (const QByteArray &)=0
Protected Member Functions
void changeEvent (QEvent *e)
Protected Member Functions inherited from Gui::Dialog::CustomizeActionPage
bool event (QEvent *e)
Detailed Description
Shows an overview of all available commands of all groups and modules.
You can customize your workbenches just by drag&dropping any commands onto the toolbars or commandbars. But you cannot modify any standard toolbars or commandbars such as "File, View, ...". It is only poosible to customize your own toolbars or commandbars.
Author
Werner Mayer
Constructor & Destructor Documentation
DlgCustomCommandsImp()
DlgCustomCommandsImp::DlgCustomCommandsImp (QWidget * parent = 0)
Constructs a DlgCustomCommandsImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
References Gui::Application::commandManager(), draftgeoutils.intersections::connect(), Gui::CommandManager::getCommands(), Gui::Application::Instance, onDescription(), and onGroupActivated().
~DlgCustomCommandsImp()
DlgCustomCommandsImp::~DlgCustomCommandsImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void DlgCustomCommandsImp::changeEvent (QEvent * e) protected virtual
Implements Gui::Dialog::CustomizeActionPage.
References Gui::Application::commandManager(), Gui::CommandManager::getGroupCommands(), Gui::Application::Instance, and onGroupActivated().
onAddMacroAction
void DlgCustomCommandsImp::onAddMacroAction (const QByteArray & macro) protected slot
References Gui::BitmapFactory(), Gui::Application::commandManager(), Gui::CommandManager::getCommandByName(), Gui::CommandBase::getMenuText(), Gui::CommandBase::getPixmap(), Gui::CommandBase::getToolTipText(), and Gui::Application::Instance.
onDescription
void DlgCustomCommandsImp::onDescription (QTreeWidgetItem * i) protected slot
Shows the description for the corresponding command.
Referenced by DlgCustomCommandsImp(), and onModifyMacroAction().
onGroupActivated
void DlgCustomCommandsImp::onGroupActivated (QTreeWidgetItem * i) protected slot
Shows all commands of this category.
References Gui::BitmapFactory(), Gui::Application::commandManager(), Gui::CommandManager::getGroupCommands(), and Gui::Application::Instance.
Referenced by changeEvent(), and DlgCustomCommandsImp().
onModifyMacroAction
void DlgCustomCommandsImp::onModifyMacroAction (const QByteArray & macro) protected slot
References Gui::BitmapFactory(), Gui::Application::commandManager(), Gui::CommandManager::getCommandByName(), Gui::CommandBase::getMenuText(), Gui::CommandBase::getPixmap(), Gui::CommandBase::getToolTipText(), Gui::Application::Instance, and onDescription().
onRemoveMacroAction
void DlgCustomCommandsImp::onRemoveMacroAction (const QByteArray & macro) protected slot
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgCommandsImp.h
Sources/FreeCAD/src/Gui/DlgCommandsImp.cpp