FreeCAD: install_to_toolbar Namespace Reference
install_to_toolbar Namespace Reference
Functions
object ask_for_toolbar (Addon repo, custom_toolbars)
None ask_to_install_toolbar_button (Addon repo)
bool check_for_button (Addon repo)
bool check_for_toolbar (custom_toolbars, str toolbar_name)
object create_new_custom_toolbar ()
object get_toolbar_with_name (str name)
None install_macro_to_toolbar (Addon repo, object toolbar)
None install_toolbar_button (Addon repo)
None remove_custom_toolbar_button (Addon repo)
Variables
translate = FreeCAD.Qt.translate
Function Documentation
ask_for_toolbar()
object install_to_toolbar.ask_for_toolbar (Addon repo, custom_toolbars)
References ask_for_toolbar(), create_new_custom_toolbar(), and get_toolbar_with_name().
Referenced by ask_for_toolbar(), and install_toolbar_button().
ask_to_install_toolbar_button()
None install_to_toolbar.ask_to_install_toolbar_button (Addon repo)
References check_for_button(), and install_toolbar_button().
check_for_button()
bool install_to_toolbar.check_for_button (Addon repo)
Referenced by ask_to_install_toolbar_button().
check_for_toolbar()
bool install_to_toolbar.check_for_toolbar (custom_toolbars, str toolbar_name)
References get_toolbar_with_name().
Referenced by create_new_custom_toolbar().
create_new_custom_toolbar()
object install_to_toolbar.create_new_custom_toolbar ()
References check_for_toolbar().
Referenced by ask_for_toolbar().
get_toolbar_with_name()
object install_to_toolbar.get_toolbar_with_name (str name)
Referenced by ask_for_toolbar(), and check_for_toolbar().
install_macro_to_toolbar()
None install_to_toolbar.install_macro_to_toolbar (Addon repo, object toolbar)
Referenced by install_toolbar_button().
install_toolbar_button()
None install_to_toolbar.install_toolbar_button (Addon repo)
References ask_for_toolbar(), and install_macro_to_toolbar().
Referenced by ask_to_install_toolbar_button().
remove_custom_toolbar_button()
None install_to_toolbar.remove_custom_toolbar_button (Addon repo)
If this repo contains a macro, look through the custom commands and
see if one is set up for this macro. If so, remove it, including any
toolbar entries.
Variable Documentation
translate
install_to_toolbar.translate = FreeCAD.Qt.translate