FreeCAD: MeshGui::SoFCMeshFacet Class Reference
MeshGui::SoFCMeshFacet Class Reference
#include <SoFCMeshFaceSet.h>
Public Member Functions
virtual void callback (SoCallbackAction *action)
virtual void doAction (SoAction *action)
virtual void getBoundingBox (SoGetBoundingBoxAction *action)
virtual void getPrimitiveCount (SoGetPrimitiveCountAction *action)
virtual void GLRender (SoGLRenderAction *action)
virtual void pick (SoPickAction *action)
SoFCMeshFacet (void)
Static Public Member Functions
static void initClass (void)
Public Attributes
SoSFMeshFacetArray coordIndex
Protected Member Functions
virtual ~SoFCMeshFacet ()
Constructor & Destructor Documentation
SoFCMeshFacet()
SoFCMeshFacet::SoFCMeshFacet (void)
Constructor.
References coordIndex.
~SoFCMeshFacet()
SoFCMeshFacet::~SoFCMeshFacet () protected virtual
Destructor.
Member Function Documentation
callback()
void SoFCMeshFacet::callback (SoCallbackAction * action) virtual
References doAction().
Referenced by qtunittest.GUITestResult::addError(), Mod.Test.unittestgui.GUITestResult::addError(), qtunittest.GUITestResult::addFailure(), Mod.Test.unittestgui.GUITestResult::addFailure(), ArchStructure.StructSelectionObserver::addSelection(), PathScripts.PathCamoticsGui.CamoticsSimulation::execute(), qtunittest.GUITestResult::startTest(), Mod.Test.unittestgui.GUITestResult::startTest(), qtunittest.GUITestResult::stopTest(), and Mod.Test.unittestgui.GUITestResult::stopTest().
doAction()
void SoFCMeshFacet::doAction (SoAction * action) virtual
References coordIndex, and MeshGui::SoFCMeshFacetElement::set().
Referenced by callback(), getBoundingBox(), getPrimitiveCount(), GLRender(), and pick().
getBoundingBox()
void SoFCMeshFacet::getBoundingBox (SoGetBoundingBoxAction * action) virtual
References doAction().
getPrimitiveCount()
void SoFCMeshFacet::getPrimitiveCount (SoGetPrimitiveCountAction * action) virtual
References doAction().
GLRender()
void SoFCMeshFacet::GLRender (SoGLRenderAction * action) virtual
References doAction().
initClass()
void SoFCMeshFacet::initClass (void) static
pick()
void SoFCMeshFacet::pick (SoPickAction * action) virtual
References doAction().
Member Data Documentation
coordIndex
SoSFMeshFacetArray MeshGui::SoFCMeshFacet::coordIndex
Referenced by doAction(), and SoFCMeshFacet().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/Gui/SoFCMeshFaceSet.h
FreeCAD/src/Mod/Mesh/Gui/SoFCMeshFaceSet.cpp