FreeCAD: ArchPipe Namespace Reference
ArchPipe Namespace Reference
Workbenches » Python workbenches » Arch
The Pipe object and tools.
Functions
def makePipe (baseobj=None, diameter=0, length=0, placement=None, name="Pipe")
def makePipeConnector (pipes, radius=0, name="Connector")
Detailed Description
The Pipe object and tools.
This module provides tools to build Pipe and Pipe connector objects. Pipes are tubular objects extruded along a base line.
Function Documentation
makePipe()
def ArchPipe.makePipe (baseobj = None, diameter = 0, length = 0, placement = None, name = "Pipe")
Referenced by ArchStairs.makeRailing().
makePipeConnector()
def ArchPipe.makePipeConnector (pipes, radius = 0, name = "Connector")
References ArchCommands.getCutVolume(), ArchComponent.Component.onDocumentRestored(), and draftutils.translate.QT_TRANSLATE_NOOP.