FreeCAD: MeshGui::SoSFMeshFacetArray Class Reference
MeshGui::SoSFMeshFacetArray Class Reference
#include <SoFCMeshFaceSet.h>
Public Member Functions
void setValue (const MeshCore::MeshFacetArray &p)
Static Public Member Functions
static void initClass (void)
Protected Member Functions
int getNumValuesPerLine () const
SbBool read1Value (SoInput *in, unsigned long idx)
SbBool readBinaryValues (SoInput *in, unsigned long numarg)
void write1Value (SoOutput *out, unsigned long idx) const
void writeBinaryValues (SoOutput *out) const
Member Function Documentation
getNumValuesPerLine()
int SoSFMeshFacetArray::getNumValuesPerLine () const protected
initClass()
void SoSFMeshFacetArray::initClass (void) static
read1Value()
SbBool SoSFMeshFacetArray::read1Value (SoInput * in, unsigned long idx) protected
Referenced by readBinaryValues().
readBinaryValues()
SbBool SoSFMeshFacetArray::readBinaryValues (SoInput * in, unsigned long numarg) protected
References read1Value().
setValue()
void SoSFMeshFacetArray::setValue (const MeshCore::MeshFacetArray & p)
write1Value()
void SoSFMeshFacetArray::write1Value (SoOutput * out, unsigned long idx) const protected
Referenced by writeBinaryValues().
writeBinaryValues()
void SoSFMeshFacetArray::writeBinaryValues (SoOutput * out) const protected
References write1Value().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCMeshFaceSet.h
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCMeshFaceSet.cpp