FreeCAD: DrawSketchHandlerArcOfParabola Class Reference
DrawSketchHandlerArcOfParabola Class Reference
Public Types
enum SelectMode {
STATUS_SEEK_First, STATUS_SEEK_Second, STATUS_SEEK_Third, STATUS_SEEK_Fourth,
STATUS_Close
}
mode table
Public Member Functions
virtual void activated (ViewProviderSketch *)
DrawSketchHandlerArcOfParabola ()
virtual void mouseMove (Base::Vector2d onSketchPos)
virtual bool pressButton (Base::Vector2d onSketchPos)
virtual bool releaseButton (Base::Vector2d)
virtual ~DrawSketchHandlerArcOfParabola ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::none, bool createowncommand=true)
virtual void deactivated (ViewProviderSketch *)
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual void quit (void)
virtual void registerPressedKey (bool, int)
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Attributes
double arcAngle
double arcAngle_t
Base::Vector2d axisPoint
std::vector< Base::Vector2d > EditCurve
double endAngle
Base::Vector2d endPoint
Base::Vector2d focusPoint
SelectMode Mode
double startAngle
Base::Vector2d startingPoint
std::vector< AutoConstraint > sugConstr1
std::vector< AutoConstraint > sugConstr2
std::vector< AutoConstraint > sugConstr3
std::vector< AutoConstraint > sugConstr4
Protected Attributes inherited from SketcherGui::DrawSketchHandler
QCursor actCursor
QPixmap actCursorPixmap
QCursor oldCursor
ViewProviderSketch * sketchgui
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
void addCursorTail (std::vector< QPixmap > &pixmaps)
void applyCursor (QCursor &newCursor)
void applyCursor (void)
qreal devicePixelRatio ()
unsigned long getCrosshairColor ()
void setCrosshairColor ()
void setCrosshairCursor (const char *svgName)
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
Sets a cursor for 3D inventor view.
void setSvgCursor (const QString &svgName, int x, int y, const std::map< unsigned long, unsigned long > &colorMapping=std::map< unsigned long, unsigned long >())
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
void unsetCursor (void)
Member Enumeration Documentation
SelectMode
enum DrawSketchHandlerArcOfParabola::SelectMode
mode table
Enumerator
STATUS_SEEK_First
enum value -—.
STATUS_SEEK_Second
enum value -—.
STATUS_SEEK_Third
enum value -—.
STATUS_SEEK_Fourth
enum value -—.
STATUS_Close
Constructor & Destructor Documentation
DrawSketchHandlerArcOfParabola()
DrawSketchHandlerArcOfParabola::DrawSketchHandlerArcOfParabola ()
~DrawSketchHandlerArcOfParabola()
virtual DrawSketchHandlerArcOfParabola::~DrawSketchHandlerArcOfParabola () virtual
Member Function Documentation
activated()
virtual void DrawSketchHandlerArcOfParabola::activated (ViewProviderSketch *) virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::setCrosshairCursor().
mouseMove()
virtual void DrawSketchHandlerArcOfParabola::mouseMove (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::applyCursor(), arcAngle, axisPoint, SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, focusPoint, Mode, SketcherGui::DrawSketchHandler::renderSuggestConstraintsCursor(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), SketcherGui::DrawSketchHandler::setPositionText(), SketcherGui::DrawSketchHandler::sketchgui, startingPoint, STATUS_SEEK_First, STATUS_SEEK_Fourth, STATUS_SEEK_Second, STATUS_SEEK_Third, sugConstr1, sugConstr2, sugConstr3, sugConstr4, Base::Vector2d::x, and Base::Vector2d::y.
pressButton()
virtual bool DrawSketchHandlerArcOfParabola::pressButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References arcAngle, arcAngle_t, axisPoint, EditCurve, endPoint, focusPoint, Mode, startingPoint, STATUS_Close, STATUS_SEEK_First, STATUS_SEEK_Fourth, STATUS_SEEK_Second, and STATUS_SEEK_Third.
releaseButton()
virtual bool DrawSketchHandlerArcOfParabola::releaseButton (Base::Vector2d) virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), SketcherGui::DrawSketchHandler::applyCursor(), arcAngle, axisPoint, Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Base::Console(), SketcherGui::DrawSketchHandler::createAutoConstraints(), SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, Sketcher::end, endAngle, endPoint, Base::ConsoleSingleton::Error(), focusPoint, SketcherGui::geometryCreationMode, App::GetApplication(), ParameterGrp::GetBool(), SketcherGui::DrawSketchHandler::getHighestCurveIndex(), Gui::ViewProviderDocumentObject::getObject(), App::Application::GetParameterGroupByPath(), Sketcher::mid, Mode, Gui::Command::openCommand(), SketcherGui::ViewProviderSketch::purgeHandler(), draftutils.translate::QT_TRANSLATE_NOOP, SketcherGui::DrawSketchHandler::resetPositionText(), SketcherGui::DrawSketchHandler::sketchgui, Sketcher::start, startAngle, startingPoint, STATUS_Close, STATUS_SEEK_First, sugConstr1, sugConstr2, sugConstr3, sugConstr4, SketcherGui::tryAutoRecomputeIfNotSolve(), SketcherGui::DrawSketchHandler::unsetCursor(), Base::Vector2d::x, and Base::Vector2d::y.
Member Data Documentation
arcAngle
double DrawSketchHandlerArcOfParabola::arcAngle protected
Referenced by mouseMove(), pressButton(), and releaseButton().
arcAngle_t
double DrawSketchHandlerArcOfParabola::arcAngle_t protected
Referenced by pressButton().
axisPoint
Base::Vector2d DrawSketchHandlerArcOfParabola::axisPoint protected
Referenced by mouseMove(), pressButton(), and releaseButton().
EditCurve
std::vector<Base::Vector2d> DrawSketchHandlerArcOfParabola::EditCurve protected
Referenced by mouseMove(), pressButton(), and releaseButton().
endAngle
double DrawSketchHandlerArcOfParabola::endAngle protected
Referenced by releaseButton().
endPoint
Base::Vector2d DrawSketchHandlerArcOfParabola::endPoint protected
Referenced by pressButton(), and releaseButton().
focusPoint
Base::Vector2d DrawSketchHandlerArcOfParabola::focusPoint protected
Referenced by mouseMove(), pressButton(), and releaseButton().
Mode
SelectMode DrawSketchHandlerArcOfParabola::Mode protected
Referenced by mouseMove(), pressButton(), and releaseButton().
startAngle
double DrawSketchHandlerArcOfParabola::startAngle protected
Referenced by releaseButton().
startingPoint
Base::Vector2d DrawSketchHandlerArcOfParabola::startingPoint protected
Referenced by mouseMove(), pressButton(), and releaseButton().
sugConstr1
std::vector<AutoConstraint> DrawSketchHandlerArcOfParabola::sugConstr1 protected
Referenced by mouseMove(), and releaseButton().
sugConstr2
std::vector<AutoConstraint> DrawSketchHandlerArcOfParabola::sugConstr2 protected
Referenced by mouseMove(), and releaseButton().
sugConstr3
std::vector<AutoConstraint> DrawSketchHandlerArcOfParabola::sugConstr3 protected
Referenced by mouseMove(), and releaseButton().
sugConstr4
std::vector<AutoConstraint> DrawSketchHandlerArcOfParabola::sugConstr4 protected
Referenced by mouseMove(), and releaseButton().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/Gui/CommandCreateGeo.cpp