FreeCAD: Data::ComplexGeoDataPy Class Reference
Data::ComplexGeoDataPy Class Reference
The python export class for ComplexGeoData.
#include <ComplexGeoDataPy.h>
Public Types
typedef ComplexGeoData * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
ComplexGeoDataPy (ComplexGeoData *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of ComplexGeoDataPy.
static PyMethodDef Methods []
Methods structure of ComplexGeoDataPy.
static PyTypeObject Type
Type structure of ComplexGeoDataPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~ComplexGeoDataPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * getFacesFromSubelement (PyObject *args)
implementer for the getFacesFromSubelement() method
static PyObject * staticCallback_getFacesFromSubelement (PyObject *self, PyObject *args)
callback for the getFacesFromSubelement() method
callbacks and implementers for the python object attributes
Py::Object getBoundBox (void) const
getter for the BoundBox attribute
Py::Object getPlacement (void) const
getter for the Placement attribute
void setPlacement (Py::Object arg)
setter for the Placement attribute
Py::Object getMatrix (void) const
getter for the Matrix attribute
void setMatrix (Py::Object arg)
setter for the Matrix attribute
Py::Int getTag (void) const
getter for the Tag attribute
void setTag (Py::Int arg)
setter for the Tag attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ComplexGeoData * getComplexGeoDataPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getBoundBox (PyObject *self, void *closure)
getter callback for the BoundBox attribute
static int staticCallback_setBoundBox (PyObject *self, PyObject *value, void *closure)
setter callback for the BoundBox attribute
static PyObject * staticCallback_getPlacement (PyObject *self, void *closure)
getter callback for the Placement attribute
static int staticCallback_setPlacement (PyObject *self, PyObject *value, void *closure)
setter callback for the Placement attribute
static PyObject * staticCallback_getMatrix (PyObject *self, void *closure)
getter callback for the Matrix attribute
static int staticCallback_setMatrix (PyObject *self, PyObject *value, void *closure)
setter callback for the Matrix attribute
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for ComplexGeoData.
Member Typedef Documentation
PointerType
typedef ComplexGeoData* Data::ComplexGeoDataPy::PointerType
Constructor & Destructor Documentation
~ComplexGeoDataPy()
ComplexGeoDataPy::~ComplexGeoDataPy () protected
References getComplexGeoDataPtr(), and Base::Handled::unref().
ComplexGeoDataPy()
ComplexGeoDataPy::ComplexGeoDataPy (ComplexGeoData * pcObject, PyTypeObject * T = &Type)
References Base::Handled::ref().
Member Function Documentation
getBoundBox()
Py::Object ComplexGeoDataPy::getBoundBox (void) const
getter for the BoundBox attribute
Referenced by staticCallback_getBoundBox().
getComplexGeoDataPtr()
ComplexGeoData * ComplexGeoDataPy::getComplexGeoDataPtr (void) const
getter for the object handled by this class
Referenced by ~ComplexGeoDataPy().
getCustomAttributes()
PyObject * ComplexGeoDataPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getFacesFromSubelement()
PyObject * ComplexGeoDataPy::getFacesFromSubelement (PyObject * args)
implementer for the getFacesFromSubelement() method
Referenced by staticCallback_getFacesFromSubelement().
getMatrix()
Py::Object ComplexGeoDataPy::getMatrix (void) const
getter for the Matrix attribute
Referenced by staticCallback_getMatrix().
getPlacement()
Py::Object ComplexGeoDataPy::getPlacement (void) const
getter for the Placement attribute
Referenced by staticCallback_getPlacement().
getTag()
Py::Int ComplexGeoDataPy::getTag (void) const
getter for the Tag attribute
Referenced by staticCallback_getTag().
GetType()
virtual PyTypeObject* Data::ComplexGeoDataPy::GetType (void) virtual
Reimplemented from Base::PersistencePy.
Reimplemented in Points::PointsPy, Part::TopoShapeWirePy, Part::TopoShapeVertexPy, Part::TopoShapeSolidPy, Part::TopoShapeShellPy, Part::TopoShapePy, Part::TopoShapeFacePy, Part::TopoShapeEdgePy, Part::TopoShapeCompSolidPy, Part::TopoShapeCompoundPy, Mesh::MeshPy, and Fem::FemMeshPy.
PyInit()
int ComplexGeoDataPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PersistencePy.
Reimplemented in Points::PointsPy, Part::TopoShapeWirePy, Part::TopoShapeVertexPy, Part::TopoShapeSolidPy, Part::TopoShapeShellPy, Part::TopoShapePy, Part::TopoShapeFacePy, Part::TopoShapeEdgePy, Part::TopoShapeCompSolidPy, Part::TopoShapeCompoundPy, Mesh::MeshPy, and Fem::FemMeshPy.
PyMake()
PyObject * ComplexGeoDataPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string ComplexGeoDataPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int ComplexGeoDataPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setMatrix()
void ComplexGeoDataPy::setMatrix (Py::Object arg)
setter for the Matrix attribute
References Base::MatrixPy::Type.
Referenced by staticCallback_setMatrix().
setPlacement()
void ComplexGeoDataPy::setPlacement (Py::Object arg)
setter for the Placement attribute
References Base::PlacementPy::Type.
Referenced by staticCallback_setPlacement().
setTag()
void ComplexGeoDataPy::setTag (Py::Int arg)
setter for the Tag attribute
Referenced by staticCallback_setTag().
staticCallback_getBoundBox()
PyObject * ComplexGeoDataPy::staticCallback_getBoundBox (PyObject * self, void * closure) static
getter callback for the BoundBox attribute
References Base::BaseExceptionFreeCADError, getBoundBox(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFacesFromSubelement()
PyObject * ComplexGeoDataPy::staticCallback_getFacesFromSubelement (PyObject * self, PyObject * args) static
callback for the getFacesFromSubelement() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getFacesFromSubelement(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMatrix()
PyObject * ComplexGeoDataPy::staticCallback_getMatrix (PyObject * self, void * closure) static
getter callback for the Matrix attribute
References Base::BaseExceptionFreeCADError, getMatrix(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPlacement()
PyObject * ComplexGeoDataPy::staticCallback_getPlacement (PyObject * self, void * closure) static
getter callback for the Placement attribute
References Base::BaseExceptionFreeCADError, getPlacement(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTag()
PyObject * ComplexGeoDataPy::staticCallback_getTag (PyObject * self, void * closure) static
getter callback for the Tag attribute
References Base::BaseExceptionFreeCADError, getTag(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setBoundBox()
int ComplexGeoDataPy::staticCallback_setBoundBox (PyObject * self, PyObject * value, void * closure) static
setter callback for the BoundBox attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setMatrix()
int ComplexGeoDataPy::staticCallback_setMatrix (PyObject * self, PyObject * value, void * closure) static
setter callback for the Matrix attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setMatrix().
staticCallback_setPlacement()
int ComplexGeoDataPy::staticCallback_setPlacement (PyObject * self, PyObject * value, void * closure) static
setter callback for the Placement attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setPlacement().
staticCallback_setTag()
int ComplexGeoDataPy::staticCallback_setTag (PyObject * self, PyObject * value, void * closure) static
setter callback for the Tag attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setTag().
Member Data Documentation
GetterSetter
PyGetSetDef ComplexGeoDataPy::GetterSetter static
Initial value:
= {
    {"BoundBox",
        (getter) staticCallback_getBoundBox,
        (setter) staticCallback_setBoundBox,
        "Get the BoundBox of the object",
        NULL
    },
    {"Placement",
        (getter) staticCallback_getPlacement,
        (setter) staticCallback_setPlacement,
        "Get the current transformation of the object as placement",
        NULL
    },
    {"Matrix",
        (getter) staticCallback_getMatrix,
        (setter) staticCallback_setMatrix,
        "Get the current transformation of the object as matrix",
        NULL
    },
    {"Tag",
        (getter) staticCallback_getTag,
        (setter) staticCallback_setTag,
        "Geometry Tag",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of ComplexGeoDataPy.
Methods
PyMethodDef ComplexGeoDataPy::Methods static
Initial value:
= {
    {"getFacesFromSubelement",
        reinterpret_cast<PyCFunction>( staticCallback_getFacesFromSubelement ),
        METH_VARARGS,
        "Return vertexes and faces from a sub-element"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of ComplexGeoDataPy.
Type
PyTypeObject ComplexGeoDataPy::Type static
Type structure of ComplexGeoDataPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), App::LinkBaseExtension::checkGeoElementMap(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/App/ComplexGeoDataPy.h
Sources/FreeCAD/src/App/ComplexGeoDataPyImp.cpp
Sources/FreeCAD-SourceDocs/src/App/ComplexGeoDataPy.cpp