FreeCAD: StdMeshers_QuadFromMedialAxis_1D2D Class Reference
StdMeshers_QuadFromMedialAxis_1D2D Class Reference
Quadrangle mesher using Medial Axis.
#include <StdMeshers_QuadFromMedialAxis_1D2D.hxx>
Classes
class Algo1D
1D algo
Public Member Functions
virtual bool CheckHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, Hypothesis_Status &aStatus)
Check if needed hypotheses are present.
virtual bool Compute (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape)
Generate quadrangle mesh.
virtual bool Evaluate (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, MapShapeNbElems &aResMap)
Predict nb of elements.
virtual void SetEventListener (SMESH_subMesh *subMesh)
Sets event listener which removes mesh from EDGEs when 2D hyps change.
StdMeshers_QuadFromMedialAxis_1D2D (int hypId, int studyId, SMESH_Gen *gen)
Constructor sets algo features.
virtual ~StdMeshers_QuadFromMedialAxis_1D2D ()
Destructor.
Public Member Functions inherited from StdMeshers_Quadrangle_2D
FaceQuadStruct::Ptr CheckAnd2Dcompute (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, const bool CreateQuadratic)
FaceQuadStruct::Ptr CheckNbEdges (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, const bool considerMesh=false)
StdMeshers_Quadrangle_2D (int hypId, int studyId, SMESH_Gen *gen)
virtual ~StdMeshers_Quadrangle_2D ()
Public Member Functions inherited from SMESH_2D_Algo
virtual bool FixInternalNodes (const SMESH_ProxyMesh &mesh, const TopoDS_Face &face)
Method in which an algorithm generating a structured mesh fixes positions of in-face nodes after there movement due to insertion of viscous layers.
int NumberOfPoints (SMESH_Mesh &aMesh, const TopoDS_Wire &W)
int NumberOfWires (const TopoDS_Shape &S)
SMESH_2D_Algo (int hypId, int studyId, SMESH_Gen *gen)
SMESH_2D_Algo (int hypId, int studyId, SMESH_Gen *gen)
virtual ~SMESH_2D_Algo ()
Public Member Functions inherited from SMESH_Algo
virtual void CancelCompute ()
Sets _computeCanceled to true. It's usage depends on implementation of a particular mesher.
virtual bool Compute (SMESH_Mesh &aMesh, SMESH_MesherHelper *aHelper)
Computes mesh without geometry.
const std::list< const SMESHDS_Hypothesis * > & GetAppliedHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, const bool ignoreAuxiliary=true) const
Returns a list of compatible hypotheses assigned to a shape in a mesh.
const SMESH_HypoFilter * GetCompatibleHypoFilter (const bool ignoreAuxiliary) const
Returns the filter recognizing only compatible hypotheses.
const std::vector< std::string > & GetCompatibleHypothesis ()
Returns all types of compatible hypotheses.
SMESH_ComputeErrorPtr GetComputeError () const
return compute error
const Features & GetFeatures () const
virtual double GetProgress () const
If possible, returns progress of computation [0.,1.].
double GetProgressByTic () const
Return compute progress by nb of calls of this method.
virtual const std::list< const SMESHDS_Hypothesis * > & GetUsedHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, const bool ignoreAuxiliary=true) const
Returns a list of compatible hypotheses used to mesh a shape.
void InitComputeError ()
initialize compute error etc. before call of Compute()
virtual std::istream & LoadFrom (std::istream &load)
Loads nothing from a stream.
bool NeedDiscreteBoundary () const
bool NeedLowerHyps (int dim) const
bool NeedShape () const
int NumberOfPoints (SMESH_Mesh &aMesh, const TopoDS_Wire &W)
bool OnlyUnaryInput () const
virtual std::ostream & SaveTo (std::ostream &save)
Saves nothing in a stream.
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)
Just return false as the algorithm does not hold parameters values.
SMESH_Algo (int hypId, int studyId, SMESH_Gen *gen)
Creates algorithm.
std::vector< SMESH_subMesh * > & SubMeshesToCompute ()
virtual void SubmeshRestored (SMESH_subMesh *subMesh)
Allow algo to do something after persistent restoration.
bool SupportSubmeshes () const
virtual ~ SMESH_Algo ()
Destructor.
Public Member Functions inherited from SMESH_Hypothesis
void ClearParameters ()
virtual bool DataDependOnParams () const
The returned value is used by NotifySubMeshesHypothesisModification() to decide to call subMesh->AlgoStateEngine(MODIF_HYP, hyp) or not if subMesh is ready to be computed (algo+hyp==OK) but not yet computed. True result is reasonable for example if EventListeners depend on parameters of hypothesis.
virtual int GetDim () const
SMESH_Gen * GetGen () const
char * GetLastParameters () const
virtual const char * GetLibName () const
SMESH_Mesh * GetMeshByPersistentID (int id)
Find a mesh with given persistent ID.
char * GetParameters () const
virtual int GetShapeType () const
int GetStudyId () const
virtual bool IsAuxiliary () const
Return true if me is an auxiliary hypothesis.
virtual void NotifySubMeshesHypothesisModification ()
void SetLastParameters (const char *theParameters)
void SetLibName (const char *theLibName)
void SetParameters (const char *theParameters)
SMESH_Hypothesis (int hypId, int studyId, SMESH_Gen *gen)
virtual ~SMESH_Hypothesis ()
Public Member Functions inherited from SMESHDS_Hypothesis
int GetID () const
const char * GetName () const
int GetType () const
bool IsSameName (const SMESHDS_Hypothesis &other) const
Compare types of hypotheses.
bool operator!= (const SMESHDS_Hypothesis &other) const
virtual bool operator== (const SMESHDS_Hypothesis &other) const
SMESHDS_Hypothesis (int hypId)
virtual ~SMESHDS_Hypothesis ()
Static Public Member Functions
static bool IsApplicable (const TopoDS_Shape &aShape, bool toCheckAll)
Return true if the algorithm can mesh this shape.
Static Public Member Functions inherited from StdMeshers_Quadrangle_2D
static bool IsApplicable (const TopoDS_Shape &aShape, bool toCheckAll)
Return true if the algorithm can mesh this shape.
Static Public Member Functions inherited from SMESH_Algo
static GeomAbs_Shape Continuity (TopoDS_Edge E1, TopoDS_Edge E2)
Return continuity of two edges.
static double EdgeLength (const TopoDS_Edge &E)
Compute length of an edge.
static const Features & GetFeatures (const std::string &algoType)
Returns a structure describing algorithm features.
static EMeshError GetMeshError (SMESH_subMesh *subMesh)
Finds topological errors of a sub-mesh.
static bool GetNodeParamOnEdge (const SMESHDS_Mesh *theMesh, const TopoDS_Edge &theEdge, std::vector< double > &theParams)
Fill vector of node parameters on geometrical edge, including vertex nodes.
static bool GetSortedNodesOnEdge (const SMESHDS_Mesh *theMesh, const TopoDS_Edge &theEdge, const bool ignoreMediumNodes, std::map< double, const SMDS_MeshNode * > &theNodes, const SMDSAbs_ElementType typeToCheck=SMDSAbs_All)
Fill map of node parameter on geometrical edge to node it-self.
static bool IsContinuous (const TopoDS_Edge &E1, const TopoDS_Edge &E2)
Return true if an edge can be considered as a continuation of another.
static bool isDegenerated (const TopoDS_Edge &E)
Return true if an edge has no 3D curve.
static bool IsStraight (const TopoDS_Edge &E, const bool degenResult=false)
Return true if an edge can be considered straight.
static const SMDS_MeshNode * VertexNode (const TopoDS_Vertex &V, const SMESH_Mesh *mesh)
Return the node built on a vertex. A node moved to other geometry by MergeNodes() is also returned.
static const SMDS_MeshNode * VertexNode (const TopoDS_Vertex &V, const SMESHDS_Mesh *meshDS)
Return the node built on a vertex.
static const SMDS_MeshNode * VertexNode (const TopoDS_Vertex &V, const SMESHDS_SubMesh *edgeSM, const SMESH_Mesh *mesh, const bool checkV=true)
Return the node built on a vertex. A node moved to other geometry by MergeNodes() is also returned.
Static Public Member Functions inherited from SMESH_Hypothesis
static bool IsStatusFatal (Hypothesis_Status theStatus)
Additional Inherited Members
Public Types inherited from SMESH_Algo
enum EMeshError { MEr_OK = 0, MEr_HOLES, MEr_BAD_ORI, MEr_EMPTY }
Public Types inherited from SMESH_Hypothesis
enum Hypothesis_Status {
HYP_OK = 0, HYP_MISSING, HYP_CONCURENT, HYP_BAD_PARAMETER,
HYP_HIDDEN_ALGO, HYP_HIDING_ALGO, HYP_UNKNOWN_FATAL, HYP_INCOMPATIBLE,
HYP_NOTCONFORM, HYP_ALREADY_EXIST, HYP_BAD_DIM, HYP_BAD_SUBSHAPE,
HYP_BAD_GEOMETRY, HYP_NEED_SHAPE, HYP_INCOMPAT_HYPS
}
Public Types inherited from SMESHDS_Hypothesis
enum hypothesis_type {
PARAM_ALGO, ALGO_0D, ALGO_1D, ALGO_2D,
ALGO_3D
}
Protected Types inherited from StdMeshers_Quadrangle_2D
typedef std::map< StdMeshers_FaceSidePtr, std::vector< FaceQuadStruct::Ptr > > TQuadsBySide
Protected Member Functions inherited from StdMeshers_Quadrangle_2D
bool addEnforcedNodes ()
Splits quads by adding points of enforced nodes and create nodes on the sides shared by quads.
bool check ()
Checks validity of generated faces.
bool checkNbEdgesForEvaluate (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, MapShapeNbElems &aResMap, std::vector< int > &aNbNodes, bool &IsQuadratic)
bool computeQuadDominant (SMESH_Mesh &aMesh, const TopoDS_Face &aFace)
Compute quadrangles and possibly triangles on all quads of myQuadList.
bool computeQuadDominant (SMESH_Mesh &aMesh, const TopoDS_Face &aFace, FaceQuadStruct::Ptr quad)
Compute quadrangles and possibly triangles.
bool computeQuadPref (SMESH_Mesh &aMesh, const TopoDS_Face &aFace, FaceQuadStruct::Ptr quad)
bool computeReduced (SMESH_Mesh &aMesh, const TopoDS_Face &aFace, FaceQuadStruct::Ptr quad)
bool computeTriangles (SMESH_Mesh &aMesh, const TopoDS_Face &aFace, FaceQuadStruct::Ptr quad)
Compute quadrangles and triangles on the quad.
bool evaluateQuadPref (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, std::vector< int > &aNbNodes, MapShapeNbElems &aResMap, bool isQuadratic)
int getCorners (const TopoDS_Face &theFace, SMESH_Mesh &theMesh, std::list< TopoDS_Edge > &theWire, std::vector< TopoDS_Vertex > &theVertices, int &theNbDegenEdges, const bool considerMesh)
bool getEnforcedUV ()
Fills myForcedPnts.
bool setNormalizedGrid (FaceQuadStruct::Ptr quad)
void shiftQuad (FaceQuadStruct::Ptr &quad, const int num)
void smooth (FaceQuadStruct::Ptr quad)
Perform smoothing of 2D elements on a FACE with ignored degenerated EDGE.
int splitQuad (FaceQuadStruct::Ptr quad, int i, int j)
Splits a quad at I or J. Returns an index of a new side in the new quad.
void splitQuadFace (SMESHDS_Mesh *theMeshDS, const int theFaceID, const SMDS_MeshNode *theNode1, const SMDS_MeshNode *theNode2, const SMDS_MeshNode *theNode3, const SMDS_MeshNode *theNode4)
void updateDegenUV (FaceQuadStruct::Ptr quad)
Set UV of nodes on degenerated VERTEXes in the middle of degenerated EDGE.
void updateSideUV (FaceQuadStruct::Side &side, int iForced, const TQuadsBySide &quads, int *iNext=NULL)
Updates UV of a side after moving its node.
Protected Member Functions inherited from SMESH_Algo
void addBadInputElement (const SMDS_MeshElement *elem)
store a bad input element preventing computation, which may be a temporary one i.e. not residing the mesh, then it will be deleted by InitComputeError()
void addBadInputElements (const SMESHDS_SubMesh *sm, const bool addNodes=false)
bool error (const SMESH_Comment &comment="")
store COMPERR_ALGO_FAILED error and comment and then return false
bool error (int error, const SMESH_Comment &comment="")
store error and comment and then return (error == COMPERR_OK)
bool error (SMESH_ComputeErrorPtr error)
store error and return error->IsOK()
Protected Attributes inherited from StdMeshers_Quadrangle_2D
bool myCheckOri
std::vector< ForcedPoint > myForcedPnts
SMESH_MesherHelper * myHelper
bool myNeedSmooth
const StdMeshers_QuadrangleParams * myParams
SMESH_ProxyMesh::Ptr myProxyMesh
std::list< FaceQuadStruct::Ptr > myQuadList
bool myQuadranglePreference
StdMeshers_QuadType myQuadType
bool myTrianglePreference
int myTriaVertexID
Detailed Description
Quadrangle mesher using Medial Axis.
Constructor & Destructor Documentation
StdMeshers_QuadFromMedialAxis_1D2D()
StdMeshers_QuadFromMedialAxis_1D2D::StdMeshers_QuadFromMedialAxis_1D2D (int hypId, int studyId, SMESH_Gen * gen)
Constructor sets algo features.
~StdMeshers_QuadFromMedialAxis_1D2D()
StdMeshers_QuadFromMedialAxis_1D2D::~StdMeshers_QuadFromMedialAxis_1D2D () virtual
Destructor.
Member Function Documentation
CheckHypothesis()
bool StdMeshers_QuadFromMedialAxis_1D2D::CheckHypothesis (SMESH_Mesh & aMesh, const TopoDS_Shape & aShape, Hypothesis_Status & aStatus) virtual
Check if needed hypotheses are present.
Reimplemented from StdMeshers_Quadrangle_2D.
References SMESH_Algo::GetUsedHypothesis(), and SMESH_Hypothesis::HYP_OK.
Compute()
bool StdMeshers_QuadFromMedialAxis_1D2D::Compute (SMESH_Mesh & aMesh, const TopoDS_Shape & aShape) virtual
Generate quadrangle mesh.
Reimplemented from StdMeshers_Quadrangle_2D.
References SMESH_Algo::error(), and SMESH_MesherHelper::SetSubShape().
Evaluate()
bool StdMeshers_QuadFromMedialAxis_1D2D::Evaluate (SMESH_Mesh & aMesh, const TopoDS_Shape & aShape, MapShapeNbElems & aResMap) virtual
Predict nb of elements.
Reimplemented from StdMeshers_Quadrangle_2D.
References StdMeshers_Quadrangle_2D::Evaluate().
IsApplicable()
bool StdMeshers_QuadFromMedialAxis_1D2D::IsApplicable (const TopoDS_Shape & aShape, bool toCheckAll) static
Return true if the algorithm can mesh this shape.
Parameters
[in] aShape - shape to check
[in] toCheckAll - if true, this check returns OK if all shapes are OK, else, returns OK if at least one shape is OK
SetEventListener()
void StdMeshers_QuadFromMedialAxis_1D2D::SetEventListener (SMESH_subMesh * subMesh) virtual
Sets event listener which removes mesh from EDGEs when 2D hyps change.
Reimplemented from SMESH_Algo.
References SMESH_subMesh::SetEventListener().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_QuadFromMedialAxis_1D2D.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_QuadFromMedialAxis_1D2D.cpp