FreeCAD: MeshCore::MeshFacetArray Class Reference
MeshCore::MeshFacetArray Class Reference
Stores all facets of the mesh data-structure.
#include <Elements.h>
Public Member Functions
Construction
MeshFacetArray (void)
constructor
MeshFacetArray (unsigned long ulSize)
constructor
MeshFacetArray (const MeshFacetArray &)
copy-constructor
~MeshFacetArray (void)
destructor
Flag state
Note
All flag methods are const as they do NOT change the actual properties of the object
void SetFlag (MeshFacet::TFlagType tF) const
Sets the flag for all facets.
void ResetFlag (MeshFacet::TFlagType tF) const
Resets the flag for all facets.
void ResetInvalid (void) const
Sets all facets invalid.
void SetProperty (unsigned long ulVal) const
Sets the property for all facets.
MeshFacetArray & operator= (const MeshFacetArray &rclFAry)
void Erase (_TIterator pIter)
Removes the facet from the array the iterator points to.
void TransposeIndices (unsigned long ulOrig, unsigned long ulNew)
Checks and flips the point indices if needed.
void DecrementIndices (unsigned long ulIndex)
Decrements all point indices that are higher than ulIndex.
Detailed Description
Stores all facets of the mesh data-structure.
Constructor & Destructor Documentation
MeshFacetArray() [1/3]
MeshCore::MeshFacetArray::MeshFacetArray (void)
constructor
MeshFacetArray() [2/3]
MeshCore::MeshFacetArray::MeshFacetArray (unsigned long ulSize)
constructor
MeshFacetArray() [3/3]
MeshFacetArray::MeshFacetArray (const MeshFacetArray & ary)
copy-constructor
~MeshFacetArray()
MeshCore::MeshFacetArray::~MeshFacetArray (void)
destructor
Member Function Documentation
DecrementIndices()
void MeshFacetArray::DecrementIndices (unsigned long ulIndex)
Decrements all point indices that are higher than ulIndex.
Erase()
void MeshFacetArray::Erase (_TIterator pIter)
Removes the facet from the array the iterator points to.
All neighbour indices of the other facets get adjusted.
operator=()
MeshFacetArray & MeshFacetArray::operator= (const MeshFacetArray & rclFAry)
ResetFlag()
void MeshFacetArray::ResetFlag (MeshFacet::TFlagType tF) const
Resets the flag for all facets.
Referenced by MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), and MeshCore::MeshAlgorithm::CheckBorderFacets().
ResetInvalid()
void MeshFacetArray::ResetInvalid (void) const
Sets all facets invalid.
Referenced by MeshCore::MeshRemoveNeedles::Fixup().
SetFlag()
void MeshFacetArray::SetFlag (MeshFacet::TFlagType tF) const
Sets the flag for all facets.
Referenced by MeshCore::MeshAlgorithm::GetFacetBorders(), Mesh::MeshObject::splitEdges(), and MeshCore::MeshKernel::VisitNeighbourFacetsOverCorners().
SetProperty()
void MeshFacetArray::SetProperty (unsigned long ulVal) const
Sets the property for all facets.
TransposeIndices()
void MeshFacetArray::TransposeIndices (unsigned long ulOrig, unsigned long ulNew)
Checks and flips the point indices if needed.
See also
MeshFacet::Transpose().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Elements.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Elements.cpp