FreeCAD: App::ExpressionModifier< P > Class Template Reference
App::ExpressionModifier< P > Class Template Reference
#include <Expression.h>
Public Member Functions
virtual void aboutToChange () override
virtual int changed () const override
ExpressionModifier (P &_prop)
virtual App::PropertyLinkBase * getPropertyLink () override
virtual void reset () override
virtual ~ExpressionModifier ()
Public Member Functions inherited from App::ExpressionVisitor
virtual void visit (Expression &e)=0
virtual ~ExpressionVisitor ()
Protected Attributes
P & prop
App::PropertyLinkBase * propLink
AtomicPropertyChangeInterface< P >::AtomicPropertyChange signaller
Additional Inherited Members
Protected Member Functions inherited from App::ExpressionVisitor
bool adjustLinks (Expression &e, const std::set< App::DocumentObject * > &inList)
void collectReplacement (Expression &e, std::map< ObjectIdentifier, ObjectIdentifier > &, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
void getDepObjects (Expression &e, std::set< App::DocumentObject * > &, std::vector< std::string > *)
void getDeps (Expression &e, ExpressionDeps &)
void getIdentifiers (Expression &e, std::set< App::ObjectIdentifier > &)
void importSubNames (Expression &e, const ObjectIdentifier::SubNameMap &subNameMap)
void moveCells (Expression &e, const CellAddress &address, int rowCount, int colCount)
void offsetCells (Expression &e, int rowOffset, int colOffset)
bool relabeledDocument (Expression &e, const std::string &oldName, const std::string &newName)
bool renameObjectIdentifier (Expression &e, const std::map< ObjectIdentifier, ObjectIdentifier > &, const ObjectIdentifier &)
bool updateElementReference (Expression &e, App::DocumentObject *feature, bool reverse)
void updateLabelReference (Expression &e, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
Constructor & Destructor Documentation
ExpressionModifier()
template<class P > App::ExpressionModifier< P >::ExpressionModifier (P & _prop)
~ExpressionModifier()
template<class P > virtual App::ExpressionModifier< P >::~ExpressionModifier () virtual
Member Function Documentation
aboutToChange()
template<class P > virtual void App::ExpressionModifier< P >::aboutToChange () override virtual
Reimplemented from App::ExpressionVisitor.
References App::ExpressionModifier< P >::signaller.
changed()
template<class P > virtual int App::ExpressionModifier< P >::changed () const override virtual
Reimplemented from App::ExpressionVisitor.
Referenced by Spreadsheet::PropertySheet::insertColumns(), Spreadsheet::PropertySheet::insertRows(), Spreadsheet::PropertySheet::pasteCells(), Spreadsheet::PropertySheet::removeColumns(), Spreadsheet::PropertySheet::removeRows(), and Spreadsheet::PropertySheet::updateElementReference().
getPropertyLink()
template<class P > virtual App::PropertyLinkBase* App::ExpressionModifier< P >::getPropertyLink () override virtual
Reimplemented from App::ExpressionVisitor.
References App::ExpressionModifier< P >::propLink.
reset()
template<class P > virtual void App::ExpressionModifier< P >::reset () override virtual
Reimplemented from App::ExpressionVisitor.
Referenced by Spreadsheet::PropertySheet::insertColumns(), Spreadsheet::PropertySheet::insertRows(), Spreadsheet::PropertySheet::removeColumns(), Spreadsheet::PropertySheet::removeRows(), and draftguitools.gui_trackers.gridTracker::set().
Member Data Documentation
prop
template<class P > P& App::ExpressionModifier< P >::prop protected
Referenced by PathScripts.PathGui.QuantitySpinBox::updateProperty(), and PathScripts.PathGui.QuantitySpinBox::updateSpinBox().
propLink
template<class P > App::PropertyLinkBase* App::ExpressionModifier< P >::propLink protected
Referenced by App::ExpressionModifier< P >::getPropertyLink().
signaller
template<class P > AtomicPropertyChangeInterface<P>::AtomicPropertyChange App::ExpressionModifier< P >::signaller protected
Referenced by App::ExpressionModifier< P >::aboutToChange().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/App/Expression.h