FreeCAD: Base::ConsoleRefreshDisabler Class Reference
Base::ConsoleRefreshDisabler Class Reference
#include <Console.h>
Public Member Functions
ConsoleRefreshDisabler ()
~ConsoleRefreshDisabler ()
Constructor & Destructor Documentation
ConsoleRefreshDisabler()
Base::ConsoleRefreshDisabler::ConsoleRefreshDisabler ()
References Base::Console(), and Base::ConsoleSingleton::EnableRefresh().
~ConsoleRefreshDisabler()
Base::ConsoleRefreshDisabler::~ConsoleRefreshDisabler ()
References Base::Console(), and Base::ConsoleSingleton::EnableRefresh().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Base/Console.h