FreeCAD: TechDrawGui::QGIDecoration Class Reference
TechDrawGui::QGIDecoration Class Reference
#include <QGIDecoration.h>
Public Types
enum { Type = QGraphicsItem::UserType + 173 }
Public Member Functions
virtual QRectF boundingRect () const
virtual void draw ()
QColor getColor (void)
void makeMark (Base::Vector3d v)
void makeMark (double x, double y)
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr)
QGIDecoration (void)
void setColor (QColor c)
void setFill (Qt::BrushStyle bs)
void setStyle (Qt::PenStyle s)
void setWidth (double w)
int type () const
~QGIDecoration ()
Protected Member Functions
virtual QColor prefNormalColor (void)
virtual QColor prefPreColor (void)
virtual QColor prefSelectColor (void)
void setPrettyNormal ()
void setPrettyPre ()
void setPrettySel ()
Protected Attributes
QBrush m_brush
Qt::BrushStyle m_brushCurrent
QColor m_colCurrent
QColor m_colNormal
QPen m_pen
Qt::PenStyle m_styleCurrent
double m_width
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGIDecoration()
QGIDecoration::QGIDecoration (void) explicit
References setWidth().
~QGIDecoration()
TechDrawGui::QGIDecoration::~QGIDecoration ()
Member Function Documentation
boundingRect()
QRectF QGIDecoration::boundingRect () const virtual
Reimplemented in TechDrawGui::QGITile.
draw()
void QGIDecoration::draw (void) virtual
Reimplemented in TechDrawGui::QGICenterLine, TechDrawGui::QGISectionLine, TechDrawGui::QGIHighlight, and TechDrawGui::QGITile.
getColor()
QColor TechDrawGui::QGIDecoration::getColor (void)
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::getPrefColor(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::setValues().
makeMark() [1/2]
void QGIDecoration::makeMark (Base::Vector3d v)
References makeMark().
makeMark() [2/2]
void QGIDecoration::makeMark (double x, double y)
References TechDrawGui::QGICMark::setSize(), TechDrawGui::QGICMark::setThick(), and ZVALUE::VERTEX.
Referenced by makeMark().
paint()
void QGIDecoration::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) virtual
Reimplemented in TechDrawGui::QGICenterLine, TechDrawGui::QGISectionLine, TechDrawGui::QGITile, and TechDrawGui::QGIHighlight.
Referenced by TechDrawGui::QGICenterLine::paint(), TechDrawGui::QGISectionLine::paint(), TechDrawGui::QGITile::paint(), and TechDrawGui::QGIHighlight::paint().
prefNormalColor()
QColor QGIDecoration::prefNormalColor (void) protected virtual
References TechDrawGui::PreferencesGui::normalQColor().
Referenced by TechDrawGui::QGITile::QGITile().
prefPreColor()
QColor QGIDecoration::prefPreColor (void) protected virtual
References TechDrawGui::PreferencesGui::preselectQColor().
Referenced by TechDrawGui::QGITile::setPrettyPre().
prefSelectColor()
QColor QGIDecoration::prefSelectColor (void) protected virtual
References TechDrawGui::PreferencesGui::selectQColor().
Referenced by TechDrawGui::QGIGhostHighlight::QGIGhostHighlight(), and TechDrawGui::QGITile::setPrettySel().
setColor()
void QGIDecoration::setColor (QColor c)
References m_brush, m_colCurrent, m_colNormal, and m_pen.
Referenced by TechDrawGui::QGIWeldSymbol::drawTile(), TechDrawGui::QGICenterLine::QGICenterLine(), TechDrawGui::QGIGhostHighlight::QGIGhostHighlight(), TechDrawGui::QGISectionLine::QGISectionLine(), and TechDrawGui::QGISectionLine::setSectionColor().
setFill()
void TechDrawGui::QGIDecoration::setFill (Qt::BrushStyle bs)
setPrettyNormal()
void TechDrawGui::QGIDecoration::setPrettyNormal () protected
setPrettyPre()
void TechDrawGui::QGIDecoration::setPrettyPre () protected
setPrettySel()
void TechDrawGui::QGIDecoration::setPrettySel () protected
setStyle()
void QGIDecoration::setStyle (Qt::PenStyle s)
References m_pen, and m_styleCurrent.
Referenced by TechDrawGui::QGICenterLine::QGICenterLine(), TechDrawGui::QGIGhostHighlight::QGIGhostHighlight(), TechDrawGui::QGISectionLine::QGISectionLine(), and TechDrawGui::QGISectionLine::setSectionStyle().
setWidth()
void QGIDecoration::setWidth (double w)
References m_pen, and m_width.
Referenced by ArchStructure.CommandStructuralSystem::Activated(), TechDrawGui::QGIViewPart::drawCenterLines(), TechDrawGui::QGIViewPart::drawSectionLine(), TechDrawGui::QGICenterLine::QGICenterLine(), QGIDecoration(), TechDrawGui::QGIGhostHighlight::QGIGhostHighlight(), TechDrawGui::QGIHighlight::QGIHighlight(), and TechDrawGui::QGISectionLine::QGISectionLine().
type()
int TechDrawGui::QGIDecoration::type (void) const
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
Member Data Documentation
m_brush
QBrush TechDrawGui::QGIDecoration::m_brush protected
Referenced by setColor(), TechDrawGui::QGIHighlight::setTools(), and TechDrawGui::QGISectionLine::setTools().
m_brushCurrent
Qt::BrushStyle TechDrawGui::QGIDecoration::m_brushCurrent protected
Referenced by TechDrawGui::QGIHighlight::setTools(), and TechDrawGui::QGISectionLine::setTools().
m_colCurrent
QColor TechDrawGui::QGIDecoration::m_colCurrent protected
Referenced by TechDrawGui::QGITile::makeText(), TechDrawGui::QGITile::QGITile(), setColor(), TechDrawGui::QGITile::setPrettyNormal(), TechDrawGui::QGITile::setPrettyPre(), TechDrawGui::QGITile::setPrettySel(), TechDrawGui::QGICenterLine::setTools(), TechDrawGui::QGIHighlight::setTools(), and TechDrawGui::QGISectionLine::setTools().
m_colNormal
QColor TechDrawGui::QGIDecoration::m_colNormal protected
Referenced by TechDrawGui::QGITile::QGITile(), setColor(), and TechDrawGui::QGITile::setPrettyNormal().
m_pen
QPen TechDrawGui::QGIDecoration::m_pen protected
Referenced by setColor(), setStyle(), TechDrawGui::QGICenterLine::setTools(), TechDrawGui::QGIHighlight::setTools(), TechDrawGui::QGISectionLine::setTools(), and setWidth().
m_styleCurrent
Qt::PenStyle TechDrawGui::QGIDecoration::m_styleCurrent protected
Referenced by setStyle(), TechDrawGui::QGICenterLine::setTools(), TechDrawGui::QGIHighlight::setTools(), and TechDrawGui::QGISectionLine::setTools().
m_width
double TechDrawGui::QGIDecoration::m_width protected
Referenced by TechDrawGui::QGICenterLine::setTools(), TechDrawGui::QGIHighlight::setTools(), TechDrawGui::QGISectionLine::setTools(), and setWidth().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/QGIDecoration.h
FreeCAD/src/Mod/TechDraw/Gui/QGIDecoration.cpp