FreeCAD: Base::BoundBox3< _Precision > Class Template Reference
Base::BoundBox3< _Precision > Class Template Reference
The 3D bounding box class.
#include <BoundBox.h>
Public Types
typedef _Precision num_type
enum OCTANT {
OCT_LDB = 0 , OCT_RDB , OCT_LUB , OCT_RUB ,
OCT_LDF , OCT_RDF , OCT_LUF , OCT_RUF
}
enum SIDE {
LEFT =0 , RIGHT =1 , TOP =2 , BOTTOM =3 ,
FRONT =4 , BACK =5 , INVALID =255
}
typedef float_traits< num_type > traits_type
Public Member Functions
void Add (const BoundBox3< _Precision > &rcBB)
Appends the bounding box to this box.
void Add (const Vector3< _Precision > &rclVect)
Appends the point to the box.
BoundBox3 (_Precision fMinX=std::numeric_limits< _Precision >::max(), _Precision fMinY=std::numeric_limits< _Precision >::max(), _Precision fMinZ=std::numeric_limits< _Precision >::max(), _Precision fMaxX=-std::numeric_limits< _Precision >::max(), _Precision fMaxY=-std::numeric_limits< _Precision >::max(), _Precision fMaxZ=-std::numeric_limits< _Precision >::max())
Builds box from pairs of x,y,z values.
BoundBox3 (const BoundBox3< _Precision > &rcBB)
BoundBox3 (const Vector3< _Precision > &rcCnt, _Precision fDistance)
Defines a bounding box around the center rcCnt with the distances fDistance in each coordinate.
BoundBox3 (const Vector3< _Precision > *pclVect, unsigned long ulCt)
Builds box from an array of points.
_Precision CalcDiagonalLength (void) const
Compute the diagonal length of this bounding box.
bool CalcEdge (unsigned short usEdge, Vector3< _Precision > &rcP0, Vector3< _Precision > &rcP1) const
Calculates the two points of an edge.
BoundBox3< _Precision > CalcOctant (typename BoundBox3< _Precision >::OCTANT Octant) const
void CalcPlane (unsigned short usPlane, Vector3< _Precision > &rBase, Vector3< _Precision > &rNormal) const
Returns the plane of the given side.
Vector3< _Precision > CalcPoint (unsigned short usPoint) const
Returns the corner point usPoint.
Vector3< _Precision > ClosestPoint (const Vector3< _Precision > &rclPt) const
Searches for the closest point of the bounding box.
void Enlarge (_Precision fLen)
Enlarges the box with factor fLen.
Vector3< _Precision > GetCenter (void) const
Returns the center.of the box.
bool GetOctantFromVector (const Vector3< _Precision > &rclVct, OCTANT &rclOctant) const
BoundBox3< _Precision >::SIDE GetSideFromRay (const Vector3< _Precision > &rclPt, const Vector3< _Precision > &rclDir) const
Returns the side of the bounding box the ray exits.
BoundBox3< _Precision >::SIDE GetSideFromRay (const Vector3< _Precision > &rclPt, const Vector3< _Precision > &rclDir, Vector3< _Precision > &rcInt) const
Returns the side of the bounding box the ray exits.
bool Intersect (const BoundBox2d &rcBB) const
Checks for intersection.
bool Intersect (const BoundBox3< _Precision > &rcBB) const
Methods for intersection, cuttíng and union of bounding boxes.
BoundBox3< _Precision > Intersected (const BoundBox3< _Precision > &rcBB) const
Computes the intersection between two bounding boxes.
bool IntersectionPoint (const Vector3< _Precision > &rcVct, const Vector3< _Precision > &rcVctDir, Vector3< _Precision > &cVctRes, _Precision epsilon) const
Intersection point of an inner search ray with the bounding box, built of the base rcVct and the direction rcVctDir.
bool IntersectPlaneWithLine (unsigned short usSide, const Vector3< _Precision > &rcBase, const Vector3< _Precision > &rcDir, Vector3< _Precision > &rcP0) const
Computes the intersection point of line and a plane of the bounding box.
bool IntersectWithLine (const Vector3< _Precision > &rcBase, const Vector3< _Precision > &rcDir, Vector3< _Precision > &rcP0, Vector3< _Precision > &rcP1) const
Computes the intersection points of line and bounding box.
bool IsCutLine (const Vector3< _Precision > &rcBase, const Vector3< _Precision > &rcDir, _Precision fTolerance=0.0f) const
Checks for intersection with line incl.
bool IsCutPlane (const Vector3< _Precision > &rclBase, const Vector3< _Precision > &rclNormal) const
Checks if this plane specified by (point,normal) cuts this box.
bool IsInBox (const BoundBox2d &rcbb) const
Checks if this 2D box lies inside the box.
bool IsInBox (const BoundBox3< _Precision > &rcBB) const
Checks if this 3D box lies inside the box.
bool IsInBox (const Vector3< _Precision > &rcVct) const
Test methods.
bool IsValid (void) const
Checks whether the bounding box is valid.
_Precision LengthX (void) const
Calculates expansion in x-direction.
_Precision LengthY (void) const
Calculates expansion in y-direction.
_Precision LengthZ (void) const
Calculates expansion in z-direction.
void MoveX (_Precision f)
Moves in x-direction.
void MoveY (_Precision f)
Moves in y-direction.
void MoveZ (_Precision f)
Moves in z-direction.
bool operator&& (const BoundBox2d &rcBB) const
Checks for intersection.
bool operator&& (const BoundBox3< _Precision > &rcBB) const
Checks for intersection.
BoundBox3< _Precision > & operator= (const BoundBox3< _Precision > &rcBound)
Assignment operator.
void Print (std::ostream &) const
Prints the values to stream.
BoundBox2d ProjectBox (const ViewProjMethod *rclP) const
Projects the box onto a plane and returns a 2D box.
void ScaleX (_Precision f)
Scales in x-direction.
void ScaleY (_Precision f)
Scales in y-direction.
void ScaleZ (_Precision f)
Scales in z-direction.
void SetVoid (void)
void Shrink (_Precision fLen)
Shrinks the box with factor fLen.
BoundBox3< _Precision > Transformed (const Matrix4D &mat) const
Transform the corners of this box with the given matrix and create a new bounding box.
BoundBox3< _Precision > United (const BoundBox3< _Precision > &rcBB) const
The union of two bounding boxes.
~BoundBox3 ()
Public Attributes
_Precision MaxX
_Precision MaxY
_Precision MaxZ
_Precision MinX
Public attributes.
_Precision MinY
_Precision MinZ
Detailed Description
template<class _Precision>
class Base::BoundBox3< _Precision >
The 3D bounding box class.
Member Typedef Documentation
num_type
template<class _Precision > typedef _Precision Base::BoundBox3< _Precision >::num_type
traits_type
template<class _Precision > typedef float_traits<num_type> Base::BoundBox3< _Precision >::traits_type
Member Enumeration Documentation
OCTANT
template<class _Precision > enum Base::BoundBox3::OCTANT
Enumerator
OCT_LDB
OCT_RDB
OCT_LUB
OCT_RUB
OCT_LDF
OCT_RDF
OCT_LUF
OCT_RUF
SIDE
template<class _Precision > enum Base::BoundBox3::SIDE
Enumerator
LEFT
RIGHT
TOP
BOTTOM
FRONT
BACK
INVALID
Constructor & Destructor Documentation
BoundBox3() [1/4]
template<class _Precision > Base::BoundBox3< _Precision >::BoundBox3 (_Precision fMinX = std::numeric_limits<_Precision>::max(), _Precision fMinY = std::numeric_limits<_Precision>::max(), _Precision fMinZ = std::numeric_limits<_Precision>::max(), _Precision fMaxX = -std::numeric_limits<_Precision>::max(), _Precision fMaxY = -std::numeric_limits<_Precision>::max(), _Precision fMaxZ = -std::numeric_limits<_Precision>::max()) explicit
Builds box from pairs of x,y,z values.
BoundBox3() [2/4]
template<class _Precision > Base::BoundBox3< _Precision >::BoundBox3 (const BoundBox3< _Precision > & rcBB)
BoundBox3() [3/4]
template<class _Precision > Base::BoundBox3< _Precision >::BoundBox3 (const Vector3< _Precision > * pclVect, unsigned long ulCt)
Builds box from an array of points.
References Base::BoundBox3< _Precision >::MaxX, Base::BoundBox3< _Precision >::MaxY, Base::BoundBox3< _Precision >::MaxZ, Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, Base::BoundBox3< _Precision >::MinZ, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
BoundBox3() [4/4]
template<class _Precision > Base::BoundBox3< _Precision >::BoundBox3 (const Vector3< _Precision > & rcCnt, _Precision fDistance)
Defines a bounding box around the center rcCnt with the distances fDistance in each coordinate.
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
~BoundBox3()
template<class _Precision > Base::BoundBox3< _Precision >::~BoundBox3
Member Function Documentation
Add() [1/2]
template<class _Precision > void Base::BoundBox3< _Precision >::Add (const BoundBox3< _Precision > & rcBB)
Appends the bounding box to this box.
The box can grow but not shrink.
References Base::BoundBox3< _Precision >::MaxX, Base::BoundBox3< _Precision >::MaxY, Base::BoundBox3< _Precision >::MaxZ, Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, and Base::BoundBox3< _Precision >::MinZ.
Add() [2/2]
template<class _Precision > void Base::BoundBox3< _Precision >::Add (const Vector3< _Precision > & rclVect)
Appends the point to the box.
The box can grow but not shrink.
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by Base::BoundBoxPy::add(), Inspection::MeshInspectGrid::AddFacet(), MeshCore::MeshFacetGrid::AddFacet(), Points::PointsGrid::CalculateGridLength(), MeshGui::SoFCMeshSegmentShape::computeBBox(), MeshGui::SoFCMeshObjectBoundary::computeBBox(), FemGui::ViewProviderFEMMeshBuilder::createMesh(), MeshCore::PlaneFit::Dimension(), Mesh::MeshObject::getBoundBox(), Points::PointKernel::getBoundBox(), Gui::MovableGroupModel::getBoundingBox(), TechDraw::DrawProjGroup::getBoundingBox(), MeshCore::PlaneFit::GetBoundings(), Gui::Dialog::TransformStrategy::getRotationCenter(), Points::PointsGrid::InitGrid(), MeshInfoWatcher::onSelectionChanged(), Points::PointsGrid::PointsGrid(), Base::BoundBoxPy::PyInit(), PartDesignGui::ViewProviderDatumLine::setExtents(), PartDesignGui::ViewProviderDatumPlane::setExtents(), Base::BoundBox3< _Precision >::Transformed(), and Gui::View3DInventorViewer::viewSelection().
CalcDiagonalLength()
template<class _Precision > _Precision Base::BoundBox3< _Precision >::CalcDiagonalLength (void) const
Compute the diagonal length of this bounding box.
Note
It's up to the client programmer to make sure that this bounding box is valid.
Referenced by MeshCore::MeshProjection::bboxInsideRectangle(), MeshCore::MeshGrid::CalculateGridLength(), Points::PointsGrid::CalculateGridLength(), FemGui::ViewProviderFEMMeshBuilder::createMesh(), Points::PointsGrid::InSide(), MeshCore::MeshGrid::Inside(), MeshCore::MeshOutput::SaveX3DContent(), and PartGui::ViewProviderMirror::setEdit().
CalcEdge()
template<class _Precision > bool Base::BoundBox3< _Precision >::CalcEdge (unsigned short usEdge, Vector3< _Precision > & rcP0, Vector3< _Precision > & rcP1) const
Calculates the two points of an edge.
0. edge P0-P1 1. edge P1-P2 2. edge P2-P3
edge P3-P0 4. edge P4-P5 5. edge P5-P6
edge P6-P7 7. edge P7-P4 8. edge P0-P4
edge P1-P5 10. edge P2-P6 11. edge P3-P7
Referenced by Base::BoundBoxPy::getEdge().
CalcOctant()
template<class _Precision > BoundBox3< _Precision > Base::BoundBox3< _Precision >::CalcOctant (typename BoundBox3< _Precision >::OCTANT Octant) const
References Base::BoundBox3< _Precision >::MaxX, Base::BoundBox3< _Precision >::MaxY, Base::BoundBox3< _Precision >::MaxZ, Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, and Base::BoundBox3< _Precision >::MinZ.
CalcPlane()
template<class _Precision > void Base::BoundBox3< _Precision >::CalcPlane (unsigned short usPlane, Vector3< _Precision > & rBase, Vector3< _Precision > & rNormal) const
Returns the plane of the given side.
References Base::Vector3< _Precision >::Set().
CalcPoint()
template<class _Precision > Vector3< _Precision > Base::BoundBox3< _Precision >::CalcPoint (unsigned short usPoint) const
Returns the corner point usPoint.
0: front,bottom,left 1: front,bottom,right 2: front,top,right 3: front,top,left 4: back,bottom,left 5: back,bottom,right 6: back,top,right 7: back,top,left
Referenced by MeshCore::MeshTrimByPlane::CheckFacets(), Mesh::MeshObject::getBoundBox(), and Base::BoundBoxPy::getPoint().
ClosestPoint()
template<class _Precision > Vector3< _Precision > Base::BoundBox3< _Precision >::ClosestPoint (const Vector3< _Precision > & rclPt) const
Searches for the closest point of the bounding box.
References DraftVecUtils::closest(), and Base::Vector3< _Precision >::ProjectToPlane().
Referenced by Base::BoundBoxPy::closestPoint().
Enlarge()
template<class _Precision > void Base::BoundBox3< _Precision >::Enlarge (_Precision fLen)
Enlarges the box with factor fLen.
Referenced by FemGui::ViewProviderFEMMeshBuilder::createMesh(), Base::BoundBoxPy::enlarge(), MeshCore::MeshGrid::GetMeshBoundBox(), and Base::BoundBox3< _Precision >::IntersectionPoint().
GetCenter()
template<class _Precision > Vector3< _Precision > Base::BoundBox3< _Precision >::GetCenter (void) const
Returns the center.of the box.
Referenced by MeshCore::MeshProjection::bboxInsideRectangle(), MeshGui::SoFCMeshObjectShape::computeBBox(), MeshGui::SoFCMeshSegmentShape::computeBBox(), MeshGui::SoFCMeshObjectBoundary::computeBBox(), MeshPartGui::CrossSections::CrossSections(), PartGui::CrossSections::CrossSections(), MeshCore::MeshGeomEdge::IntersectBoundingBox(), MeshCore::MeshGeomFacet::IntersectBoundingBox(), DrawingGui::orthoview::orthoview(), MeshCore::MeshOutput::SaveAsymptote(), MeshCore::MeshOutput::SaveX3DContent(), Points::PointsGrid::SearchNearestFromPoint(), MeshCore::MeshFacetGrid::SearchNearestFromPoint(), MeshCore::MeshGrid::SearchNearestFromPoint(), and PartGui::ViewProviderMirror::setEdit().
GetOctantFromVector()
template<class _Precision > bool Base::BoundBox3< _Precision >::GetOctantFromVector (const Vector3< _Precision > & rclVct, OCTANT & rclOctant) const
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
GetSideFromRay() [1/2]
template<class _Precision > BoundBox3< _Precision >::SIDE Base::BoundBox3< _Precision >::GetSideFromRay (const Vector3< _Precision > & rclPt, const Vector3< _Precision > & rclDir) const
Returns the side of the bounding box the ray exits.
Referenced by Points::PointsGrid::SearchNearestFromPoint(), MeshCore::MeshFacetGrid::SearchNearestFromPoint(), and MeshCore::MeshGrid::SearchNearestFromPoint().
GetSideFromRay() [2/2]
template<class _Precision > BoundBox3< _Precision >::SIDE Base::BoundBox3< _Precision >::GetSideFromRay (const Vector3< _Precision > & rclPt, const Vector3< _Precision > & rclDir, Vector3< _Precision > & rcInt) const
Returns the side of the bounding box the ray exits.
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Intersect() [1/2]
template<class _Precision > bool Base::BoundBox3< _Precision >::Intersect (const BoundBox2d & rcBB) const
Checks for intersection.
References Base::BoundBox2d::MaxX, Base::BoundBox2d::MaxY, Base::BoundBox2d::MinX, and Base::BoundBox2d::MinY.
Intersect() [2/2]
template<class _Precision > bool Base::BoundBox3< _Precision >::Intersect (const BoundBox3< _Precision > & rcBB) const
Methods for intersection, cuttíng and union of bounding boxes.
Checks for intersection.
References Base::BoundBox3< _Precision >::MaxX, Base::BoundBox3< _Precision >::MaxY, Base::BoundBox3< _Precision >::MaxZ, Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, and Base::BoundBox3< _Precision >::MinZ.
Referenced by Base::BoundBoxPy::intersect().
Intersected()
template<class _Precision > BoundBox3< _Precision > Base::BoundBox3< _Precision >::Intersected (const BoundBox3< _Precision > & rcBB) const
Computes the intersection between two bounding boxes.
The result is also a bounding box.
References Base::BoundBox3< _Precision >::MaxX, Base::BoundBox3< _Precision >::MaxY, Base::BoundBox3< _Precision >::MaxZ, Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, and Base::BoundBox3< _Precision >::MinZ.
Referenced by Base::BoundBoxPy::intersected().
IntersectionPoint()
template<class _Precision > bool Base::BoundBox3< _Precision >::IntersectionPoint (const Vector3< _Precision > & rcVct, const Vector3< _Precision > & rcVctDir, Vector3< _Precision > & cVctRes, _Precision epsilon) const
Intersection point of an inner search ray with the bounding box, built of the base rcVct and the direction rcVctDir.
rcVct must lie inside the bounding box.
References Base::BoundBox3< _Precision >::Enlarge(), draftutils.utils::epsilon(), and Base::BoundBox3< _Precision >::IsInBox().
Referenced by Base::BoundBoxPy::getIntersectionPoint().
IntersectPlaneWithLine()
template<class _Precision > bool Base::BoundBox3< _Precision >::IntersectPlaneWithLine (unsigned short usSide, const Vector3< _Precision > & rcBase, const Vector3< _Precision > & rcDir, Vector3< _Precision > & rcP0) const
Computes the intersection point of line and a plane of the bounding box.
References Base::Vector3< _Precision >::Scale().
IntersectWithLine()
template<class _Precision > bool Base::BoundBox3< _Precision >::IntersectWithLine (const Vector3< _Precision > & rcBase, const Vector3< _Precision > & rcDir, Vector3< _Precision > & rcP0, Vector3< _Precision > & rcP1) const
Computes the intersection points of line and bounding box.
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
IsCutLine()
template<class _Precision > bool Base::BoundBox3< _Precision >::IsCutLine (const Vector3< _Precision > & rcBase, const Vector3< _Precision > & rcDir, _Precision fTolerance = 0.0f) const
Checks for intersection with line incl.
search tolerance.
References Base::Vector3< _Precision >::Length(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by Base::BoundBoxPy::intersect().
IsCutPlane()
template<class _Precision > bool Base::BoundBox3< _Precision >::IsCutPlane (const Vector3< _Precision > & rclBase, const Vector3< _Precision > & rclNormal) const
Checks if this plane specified by (point,normal) cuts this box.
Note
It's up to the client programmer to make sure that this bounding box is valid.
Referenced by MeshCore::MeshProjection::bboxInsideRectangle(), MeshCore::MeshTrimByPlane::CheckFacets(), MeshCore::MeshAlgorithm::CutWithPlane(), MeshCore::MeshAlgorithm::GetFacetsFromPlane(), and Base::BoundBoxPy::isCutPlane().
IsInBox() [1/3]
template<class _Precision > bool Base::BoundBox3< _Precision >::IsInBox (const BoundBox2d & rcbb) const
Checks if this 2D box lies inside the box.
Note
It's up to the client programmer to make sure that both bounding boxes are valid.
References Base::BoundBox2d::MaxX, Base::BoundBox2d::MaxY, Base::BoundBox2d::MinX, and Base::BoundBox2d::MinY.
IsInBox() [2/3]
template<class _Precision > bool Base::BoundBox3< _Precision >::IsInBox (const BoundBox3< _Precision > & rcBB) const
Checks if this 3D box lies inside the box.
Note
It's up to the client programmer to make sure that both bounding boxes are valid.
References Base::BoundBox3< _Precision >::MaxX, Base::BoundBox3< _Precision >::MaxY, Base::BoundBox3< _Precision >::MaxZ, Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, and Base::BoundBox3< _Precision >::MinZ.
IsInBox() [3/3]
template<class _Precision > bool Base::BoundBox3< _Precision >::IsInBox (const Vector3< _Precision > & rcVct) const
Test methods.
Checks if this point lies inside the box.
Note
It's up to the client programmer to make sure that this bounding box is valid.
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by MeshCore::MeshGeomFacet::ContainedByOrIntersectBoundingBox(), MeshCore::MeshGeomEdge::ContainedByOrIntersectBoundingBox(), MeshCore::MeshGeomFacet::IntersectBoundingBox(), Base::BoundBox3< _Precision >::IntersectionPoint(), MeshCore::MeshGeomFacet::IntersectWithFacet(), Base::BoundBoxPy::isInside(), Points::PointsGrid::SearchNearestFromPoint(), MeshCore::MeshFacetGrid::SearchNearestFromPoint(), MeshCore::MeshGrid::SearchNearestFromPoint(), MeshCore::MeshPointGrid::Verify(), and Points::PointsGrid::Verify().
IsValid()
template<class _Precision > bool Base::BoundBox3< _Precision >::IsValid (void) const
Checks whether the bounding box is valid.
Referenced by Mesh::MeshObject::getBoundBox(), TechDraw::DrawProjGroup::getXYPosition(), PartGui::ViewProvider2DObjectGrid::updateData(), and Gui::View3DInventorViewer::viewSelection().
LengthX()
template<class _Precision > _Precision Base::BoundBox3< _Precision >::LengthX (void) const
Calculates expansion in x-direction.
Referenced by PathSimulator::PathSim::BeginSimulation(), MeshCore::MeshGrid::CalculateGridLength(), Points::PointsGrid::CalculateGridLength(), MeshCore::MeshAlgorithm::CalculateMinimumGridLength(), FemGui::ViewProviderFEMMeshBuilder::createMesh(), TechDraw::DrawProjGroup::getXYPosition(), Inspection::MeshInspectGrid::InitGrid(), MeshCore::MeshGrid::InitGrid(), Points::PointsGrid::InitGrid(), Inspection::InspectActualShape::InspectActualShape(), MeshCore::MeshGeomEdge::IntersectBoundingBox(), MeshCore::MeshGeomFacet::IntersectBoundingBox(), MeshCore::MeshEigensystem::MeshEigensystem(), MeshCore::MeshFacetGrid::MeshFacetGrid(), Inspection::MeshInspectGrid::MeshInspectGrid(), MeshCore::MeshPointGrid::MeshPointGrid(), TechDraw::DrawProjGroup::minimumBbViews(), Points::PointsGrid::PointsGrid(), MeshCore::MeshOutput::SaveAsymptote(), PartDesignGui::ViewProviderDatumCoordinateSystem::setExtents(), PartDesignGui::ViewProviderDatumPlane::setExtents(), and InspectionGui::ViewProviderInspection::updateData().
LengthY()
template<class _Precision > _Precision Base::BoundBox3< _Precision >::LengthY (void) const
Calculates expansion in y-direction.
Referenced by PathSimulator::PathSim::BeginSimulation(), MeshCore::MeshGrid::CalculateGridLength(), Points::PointsGrid::CalculateGridLength(), MeshCore::MeshAlgorithm::CalculateMinimumGridLength(), FemGui::ViewProviderFEMMeshBuilder::createMesh(), TechDraw::DrawProjGroup::getXYPosition(), Inspection::MeshInspectGrid::InitGrid(), MeshCore::MeshGrid::InitGrid(), Points::PointsGrid::InitGrid(), Inspection::InspectActualShape::InspectActualShape(), MeshCore::MeshGeomEdge::IntersectBoundingBox(), MeshCore::MeshGeomFacet::IntersectBoundingBox(), MeshCore::MeshFacetGrid::MeshFacetGrid(), Inspection::MeshInspectGrid::MeshInspectGrid(), MeshCore::MeshPointGrid::MeshPointGrid(), Points::PointsGrid::PointsGrid(), MeshCore::MeshOutput::SaveAsymptote(), PartDesignGui::ViewProviderDatumCoordinateSystem::setExtents(), PartDesignGui::ViewProviderDatumPlane::setExtents(), and InspectionGui::ViewProviderInspection::updateData().
LengthZ()
template<class _Precision > _Precision Base::BoundBox3< _Precision >::LengthZ (void) const
Calculates expansion in z-direction.
Referenced by PathSimulator::PathSim::BeginSimulation(), MeshCore::MeshGrid::CalculateGridLength(), Points::PointsGrid::CalculateGridLength(), MeshCore::MeshAlgorithm::CalculateMinimumGridLength(), FemGui::ViewProviderFEMMeshBuilder::createMesh(), Inspection::MeshInspectGrid::InitGrid(), MeshCore::MeshGrid::InitGrid(), Points::PointsGrid::InitGrid(), Inspection::InspectActualShape::InspectActualShape(), MeshCore::MeshGeomEdge::IntersectBoundingBox(), MeshCore::MeshGeomFacet::IntersectBoundingBox(), MeshCore::MeshFacetGrid::MeshFacetGrid(), Inspection::MeshInspectGrid::MeshInspectGrid(), MeshCore::MeshPointGrid::MeshPointGrid(), Points::PointsGrid::PointsGrid(), MeshCore::MeshOutput::SaveAsymptote(), PartDesignGui::ViewProviderDatumCoordinateSystem::setExtents(), PartDesignGui::ViewProviderDatumLine::setExtents(), and InspectionGui::ViewProviderInspection::updateData().
MoveX()
template<class _Precision > void Base::BoundBox3< _Precision >::MoveX (_Precision f)
Moves in x-direction.
Referenced by TechDraw::DrawProjGroup::getBoundingBox(), and Base::BoundBoxPy::move().
MoveY()
template<class _Precision > void Base::BoundBox3< _Precision >::MoveY (_Precision f)
Moves in y-direction.
Referenced by TechDraw::DrawProjGroup::getBoundingBox(), and Base::BoundBoxPy::move().
MoveZ()
template<class _Precision > void Base::BoundBox3< _Precision >::MoveZ (_Precision f)
Moves in z-direction.
Referenced by Base::BoundBoxPy::move().
operator&&() [1/2]
template<class _Precision > bool Base::BoundBox3< _Precision >::operator&& (const BoundBox2d & rcBB) const
Checks for intersection.
operator&&() [2/2]
template<class _Precision > bool Base::BoundBox3< _Precision >::operator&& (const BoundBox3< _Precision > & rcBB) const
Checks for intersection.
operator=()
template<class _Precision > BoundBox3< _Precision > & Base::BoundBox3< _Precision >::operator= (const BoundBox3< _Precision > & rcBound)
Assignment operator.
References Base::BoundBox3< _Precision >::MaxX, Base::BoundBox3< _Precision >::MaxY, Base::BoundBox3< _Precision >::MaxZ, Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, and Base::BoundBox3< _Precision >::MinZ.
Print()
template<class _Precision > void Base::BoundBox3< _Precision >::Print (std::ostream &) const
Prints the values to stream.
ProjectBox()
template<class _Precision > BoundBox2d Base::BoundBox3< _Precision >::ProjectBox (const ViewProjMethod * rclP) const
Projects the box onto a plane and returns a 2D box.
References Base::BoundBox2d::Add(), Base::BoundBox2d::SetVoid(), Base::Vector3< _Precision >::x, and Base::Vector3< _Precision >::y.
Referenced by MeshCore::MeshTrimming::CheckFacets(), and PartGui::ViewProvider2DObjectGrid::updateData().
ScaleX()
template<class _Precision > void Base::BoundBox3< _Precision >::ScaleX (_Precision f)
Scales in x-direction.
Referenced by TechDraw::DrawProjGroup::getBoundingBox(), TechDraw::DrawProjGroup::makeViewBbs(), and Base::BoundBoxPy::scale().
ScaleY()
template<class _Precision > void Base::BoundBox3< _Precision >::ScaleY (_Precision f)
Scales in y-direction.
Referenced by TechDraw::DrawProjGroup::getBoundingBox(), TechDraw::DrawProjGroup::makeViewBbs(), and Base::BoundBoxPy::scale().
ScaleZ()
template<class _Precision > void Base::BoundBox3< _Precision >::ScaleZ (_Precision f)
Scales in z-direction.
Referenced by TechDraw::DrawProjGroup::getBoundingBox(), TechDraw::DrawProjGroup::makeViewBbs(), and Base::BoundBoxPy::scale().
SetVoid()
template<class _Precision > void Base::BoundBox3< _Precision >::SetVoid (void)
Referenced by Base::BoundBoxPy::setVoid().
Shrink()
template<class _Precision > void Base::BoundBox3< _Precision >::Shrink (_Precision fLen)
Shrinks the box with factor fLen.
Transformed()
template<class _Precision > BoundBox3< _Precision > Base::BoundBox3< _Precision >::Transformed (const Matrix4D & mat) const
Transform the corners of this box with the given matrix and create a new bounding box.
Note
It's up to the client programmer to make sure that this bounding box is valid.
References Base::BoundBox3< _Precision >::Add().
Referenced by Inspection::MeshInspectGrid::InitGrid(), Inspection::InspectNominalFastMesh::InspectNominalFastMesh(), Inspection::InspectNominalMesh::InspectNominalMesh(), Inspection::MeshInspectGrid::MeshInspectGrid(), MeshCore::MeshOutput::SaveX3DContent(), PartDesignGui::ViewProviderDatumLine::setExtents(), PartDesignGui::ViewProviderDatumPlane::setExtents(), and Base::BoundBoxPy::transformed().
United()
template<class _Precision > BoundBox3< _Precision > Base::BoundBox3< _Precision >::United (const BoundBox3< _Precision > & rcBB) const
The union of two bounding boxes.
References Base::BoundBox3< _Precision >::MaxX, Base::BoundBox3< _Precision >::MaxY, Base::BoundBox3< _Precision >::MaxZ, Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, and Base::BoundBox3< _Precision >::MinZ.
Referenced by Base::BoundBoxPy::united().
Member Data Documentation
MaxX
template<class _Precision > _Precision Base::BoundBox3< _Precision >::MaxX
Referenced by Base::BoundBox3< _Precision >::Add(), Inspection::MeshInspectGrid::AddFacet(), MeshCore::MeshFacetGrid::AddFacet(), Base::BoundBox3< _Precision >::BoundBox3(), Base::BoundBox3< _Precision >::CalcOctant(), MeshGui::SoFCMeshFaceSet::computeBBox(), MeshGui::SoFCMeshOpenEdgeSet::computeBBox(), MeshGui::SoFCMeshNode::computeBBox(), MeshGui::SoFCMeshOpenEdge::computeBBox(), MeshGui::SoFCMeshObjectShape::computeBBox(), MeshGui::SoFCMeshSegmentShape::computeBBox(), MeshGui::SoFCMeshObjectBoundary::computeBBox(), MeshCore::PlaneFit::Dimension(), TechDraw::DrawViewPart::getBoxX(), Gui::Dialog::TransformStrategy::getRotationCenter(), Points::PointsGrid::InSide(), MeshCore::MeshGrid::Inside(), Base::BoundBox3< _Precision >::Intersect(), Base::BoundBox3< _Precision >::Intersected(), Base::BoundBox3< _Precision >::IsInBox(), TechDraw::DrawViewSection::isReallyInBox(), MeshInfoWatcher::onSelectionChanged(), Base::BoundBox3< _Precision >::operator=(), Base::BoundBoxPy::PyInit(), Base::BoundBoxPy::representation(), PartDesignGui::ViewProviderDatumPlane::setExtents(), Base::BoundBoxPy::setXMax(), MeshCore::MeshAlgorithm::Surround(), Base::BoundBox3< _Precision >::United(), and Gui::View3DInventorViewer::viewSelection().
MaxY
template<class _Precision > _Precision Base::BoundBox3< _Precision >::MaxY
Referenced by Base::BoundBox3< _Precision >::Add(), Inspection::MeshInspectGrid::AddFacet(), MeshCore::MeshFacetGrid::AddFacet(), Base::BoundBox3< _Precision >::BoundBox3(), Base::BoundBox3< _Precision >::CalcOctant(), MeshGui::SoFCMeshFaceSet::computeBBox(), MeshGui::SoFCMeshOpenEdgeSet::computeBBox(), MeshGui::SoFCMeshNode::computeBBox(), MeshGui::SoFCMeshOpenEdge::computeBBox(), MeshGui::SoFCMeshObjectShape::computeBBox(), MeshGui::SoFCMeshSegmentShape::computeBBox(), MeshGui::SoFCMeshObjectBoundary::computeBBox(), MeshCore::PlaneFit::Dimension(), TechDraw::DrawViewPart::getBoxY(), Gui::Dialog::TransformStrategy::getRotationCenter(), Points::PointsGrid::InSide(), MeshCore::MeshGrid::Inside(), Base::BoundBox3< _Precision >::Intersect(), Base::BoundBox3< _Precision >::Intersected(), Base::BoundBox3< _Precision >::IsInBox(), TechDraw::DrawViewSection::isReallyInBox(), MeshInfoWatcher::onSelectionChanged(), Base::BoundBox3< _Precision >::operator=(), Base::BoundBoxPy::PyInit(), Base::BoundBoxPy::representation(), PartDesignGui::ViewProviderDatumPlane::setExtents(), Base::BoundBoxPy::setYMax(), MeshCore::MeshAlgorithm::Surround(), Base::BoundBox3< _Precision >::United(), and Gui::View3DInventorViewer::viewSelection().
MaxZ
template<class _Precision > _Precision Base::BoundBox3< _Precision >::MaxZ
Referenced by Base::BoundBox3< _Precision >::Add(), Inspection::MeshInspectGrid::AddFacet(), MeshCore::MeshFacetGrid::AddFacet(), Base::BoundBox3< _Precision >::BoundBox3(), Base::BoundBox3< _Precision >::CalcOctant(), MeshGui::SoFCMeshFaceSet::computeBBox(), MeshGui::SoFCMeshOpenEdgeSet::computeBBox(), MeshGui::SoFCMeshNode::computeBBox(), MeshGui::SoFCMeshOpenEdge::computeBBox(), MeshGui::SoFCMeshObjectShape::computeBBox(), MeshGui::SoFCMeshSegmentShape::computeBBox(), MeshGui::SoFCMeshObjectBoundary::computeBBox(), Gui::Dialog::TransformStrategy::getRotationCenter(), Points::PointsGrid::InSide(), MeshCore::MeshGrid::Inside(), Base::BoundBox3< _Precision >::Intersect(), Base::BoundBox3< _Precision >::Intersected(), Base::BoundBox3< _Precision >::IsInBox(), TechDraw::DrawViewSection::isReallyInBox(), MeshInfoWatcher::onSelectionChanged(), Base::BoundBox3< _Precision >::operator=(), Base::BoundBoxPy::PyInit(), Base::BoundBoxPy::representation(), PartDesignGui::ViewProviderDatumLine::setExtents(), Base::BoundBoxPy::setZMax(), MeshCore::MeshAlgorithm::Surround(), Base::BoundBox3< _Precision >::United(), and Gui::View3DInventorViewer::viewSelection().
MinX
template<class _Precision > _Precision Base::BoundBox3< _Precision >::MinX
Public attributes.
Referenced by Base::BoundBox3< _Precision >::Add(), Inspection::MeshInspectGrid::AddFacet(), MeshCore::MeshFacetGrid::AddFacet(), PathSimulator::PathSim::BeginSimulation(), Base::BoundBox3< _Precision >::BoundBox3(), Base::BoundBox3< _Precision >::CalcOctant(), MeshGui::SoFCMeshFaceSet::computeBBox(), MeshGui::SoFCMeshOpenEdgeSet::computeBBox(), MeshGui::SoFCMeshNode::computeBBox(), MeshGui::SoFCMeshOpenEdge::computeBBox(), MeshGui::SoFCMeshObjectShape::computeBBox(), MeshGui::SoFCMeshSegmentShape::computeBBox(), MeshGui::SoFCMeshObjectBoundary::computeBBox(), FemGui::ViewProviderFEMMeshBuilder::createMesh(), MeshCore::PlaneFit::Dimension(), TechDraw::DrawViewPart::getBoxX(), Gui::Dialog::TransformStrategy::getRotationCenter(), Inspection::MeshInspectGrid::InitGrid(), MeshCore::MeshGrid::InitGrid(), Points::PointsGrid::InitGrid(), Points::PointsGrid::InSide(), MeshCore::MeshGrid::Inside(), Base::BoundBox3< _Precision >::Intersect(), Base::BoundBox3< _Precision >::Intersected(), Base::BoundBox3< _Precision >::IsInBox(), TechDraw::DrawViewSection::isReallyInBox(), MeshInfoWatcher::onSelectionChanged(), Base::BoundBox3< _Precision >::operator=(), Part::TopoShapePy::optimalBoundingBox(), Base::BoundBoxPy::PyInit(), Base::BoundBoxPy::representation(), MeshCore::MeshFacetGrid::SearchNearestFromPoint(), PartDesignGui::ViewProviderDatumPlane::setExtents(), Base::BoundBoxPy::setXMin(), MeshCore::MeshAlgorithm::Surround(), Base::BoundBox3< _Precision >::United(), and Gui::View3DInventorViewer::viewSelection().
MinY
template<class _Precision > _Precision Base::BoundBox3< _Precision >::MinY
Referenced by Base::BoundBox3< _Precision >::Add(), Inspection::MeshInspectGrid::AddFacet(), MeshCore::MeshFacetGrid::AddFacet(), PathSimulator::PathSim::BeginSimulation(), Base::BoundBox3< _Precision >::BoundBox3(), Base::BoundBox3< _Precision >::CalcOctant(), MeshGui::SoFCMeshFaceSet::computeBBox(), MeshGui::SoFCMeshOpenEdgeSet::computeBBox(), MeshGui::SoFCMeshNode::computeBBox(), MeshGui::SoFCMeshOpenEdge::computeBBox(), MeshGui::SoFCMeshObjectShape::computeBBox(), MeshGui::SoFCMeshSegmentShape::computeBBox(), MeshGui::SoFCMeshObjectBoundary::computeBBox(), FemGui::ViewProviderFEMMeshBuilder::createMesh(), MeshCore::PlaneFit::Dimension(), TechDraw::DrawViewPart::getBoxY(), Gui::Dialog::TransformStrategy::getRotationCenter(), Inspection::MeshInspectGrid::InitGrid(), MeshCore::MeshGrid::InitGrid(), Points::PointsGrid::InitGrid(), Points::PointsGrid::InSide(), MeshCore::MeshGrid::Inside(), Base::BoundBox3< _Precision >::Intersect(), Base::BoundBox3< _Precision >::Intersected(), Base::BoundBox3< _Precision >::IsInBox(), TechDraw::DrawViewSection::isReallyInBox(), MeshInfoWatcher::onSelectionChanged(), Base::BoundBox3< _Precision >::operator=(), Base::BoundBoxPy::PyInit(), Base::BoundBoxPy::representation(), MeshCore::MeshFacetGrid::SearchNearestFromPoint(), PartDesignGui::ViewProviderDatumPlane::setExtents(), Base::BoundBoxPy::setYMin(), MeshCore::MeshAlgorithm::Surround(), Base::BoundBox3< _Precision >::United(), and Gui::View3DInventorViewer::viewSelection().
MinZ
template<class _Precision > _Precision Base::BoundBox3< _Precision >::MinZ
Referenced by Base::BoundBox3< _Precision >::Add(), Inspection::MeshInspectGrid::AddFacet(), MeshCore::MeshFacetGrid::AddFacet(), PathSimulator::PathSim::BeginSimulation(), Base::BoundBox3< _Precision >::BoundBox3(), Base::BoundBox3< _Precision >::CalcOctant(), MeshGui::SoFCMeshFaceSet::computeBBox(), MeshGui::SoFCMeshOpenEdgeSet::computeBBox(), MeshGui::SoFCMeshNode::computeBBox(), MeshGui::SoFCMeshOpenEdge::computeBBox(), MeshGui::SoFCMeshObjectShape::computeBBox(), MeshGui::SoFCMeshSegmentShape::computeBBox(), MeshGui::SoFCMeshObjectBoundary::computeBBox(), FemGui::ViewProviderFEMMeshBuilder::createMesh(), Gui::Dialog::TransformStrategy::getRotationCenter(), Inspection::MeshInspectGrid::InitGrid(), MeshCore::MeshGrid::InitGrid(), Points::PointsGrid::InitGrid(), Points::PointsGrid::InSide(), MeshCore::MeshGrid::Inside(), Base::BoundBox3< _Precision >::Intersect(), Base::BoundBox3< _Precision >::Intersected(), Base::BoundBox3< _Precision >::IsInBox(), TechDraw::DrawViewSection::isReallyInBox(), MeshInfoWatcher::onSelectionChanged(), Base::BoundBox3< _Precision >::operator=(), Base::BoundBoxPy::PyInit(), Base::BoundBoxPy::representation(), MeshCore::MeshFacetGrid::SearchNearestFromPoint(), PartDesignGui::ViewProviderDatumLine::setExtents(), Base::BoundBoxPy::setZMin(), MeshCore::MeshAlgorithm::Surround(), Base::BoundBox3< _Precision >::United(), and Gui::View3DInventorViewer::viewSelection().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Base/BoundBox.h