FreeCAD: SMESH_subMeshEventListenerData Struct Reference
SMESH_subMeshEventListenerData Struct Reference
Data specific for EventListener and to be stored in a submesh.
#include <SMESH_subMeshEventListener.hxx>
Public Member Functions
bool IsDeletable () const
SMESH_subMeshEventListenerData (bool isDeletable)
virtual ~SMESH_subMeshEventListenerData ()
Static Public Member Functions
static SMESH_subMeshEventListenerData * MakeData (SMESH_subMesh *dependentSM, const int type=0)
Create a default listener data.
Public Attributes
bool myIsDeletable
if true, it will be deleted by SMESH_subMesh
std::list< SMESH_subMesh * > mySubMeshes
int myType
to recognize data type
Detailed Description
Data specific for EventListener and to be stored in a submesh.
Constructor & Destructor Documentation
SMESH_subMeshEventListenerData()
SMESH_subMeshEventListenerData::SMESH_subMeshEventListenerData (bool isDeletable)
Referenced by MakeData().
~SMESH_subMeshEventListenerData()
virtual SMESH_subMeshEventListenerData::~SMESH_subMeshEventListenerData () virtual
Member Function Documentation
IsDeletable()
bool SMESH_subMeshEventListenerData::IsDeletable () const
References myIsDeletable.
Referenced by SMESH_subMesh::setEventListener().
MakeData()
static SMESH_subMeshEventListenerData* SMESH_subMeshEventListenerData::MakeData (SMESH_subMesh * dependentSM, const int type = 0) static
Create a default listener data.
Parameters
dependentSM - subMesh to store
type - data type
Return values
SMESH_subMeshEventListenerData* - a new listener data
See SMESH_subMeshEventListener::ProcessEvent() to know how the default listener uses it (implementation is in SMESH_subMesh.cxx)
References SMESH_subMeshEventListenerData().
Referenced by StdMeshers_Penta_3D::MakeMeshOnFxy1(), StdMeshers_ProjectionUtils::SetEventListener(), and VISCOUS_3D::ToClearSubWithMain().
Member Data Documentation
myIsDeletable
bool SMESH_subMeshEventListenerData::myIsDeletable
if true, it will be deleted by SMESH_subMesh
Referenced by IsDeletable().
mySubMeshes
std::list<SMESH_subMesh*> SMESH_subMeshEventListenerData::mySubMeshes
Referenced by VISCOUS_3D::_ViscousBuilder::MakeN2NMap(), StdMeshers_ProjectionUtils::SetEventListener(), and VISCOUS_3D::ToClearSubWithMain().
myType
int SMESH_subMeshEventListenerData::myType
to recognize data type
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_subMeshEventListener.hxx