FreeCAD: VISCOUS_3D::_SolidData Struct Reference
VISCOUS_3D::_SolidData Struct Reference
Data of a SOLID.
Public Types
typedef const StdMeshers_ViscousLayers * THyp
Public Member Functions
void AddShapesToSmooth (const set< _EdgesOnShape * > &shape)
Add faces for smoothing.
_ConvexFace * GetConvexFace (const TGeomID faceID)
_EdgesOnShape * GetShapeEdges (const _LayerEdge *edge)
_EdgesOnShape * GetShapeEdges (const TGeomID shapeID)
Return _EdgesOnShape* corresponding to the shape.
_EdgesOnShape * GetShapeEdges (const TopoDS_Shape &shape)
Return _EdgesOnShape* corresponding to the shape.
Handle (Geom_Curve) CurveForSmooth(const TopoDS_Edge &E
void PrepareEdgesToSmoothOnFace (_EdgesOnShape *eof, bool substituteSrcNodes)
Prepare data of the _LayerEdge for smoothing on FACE.
void Sort2NeiborsOnEdge (vector< _LayerEdge * > &edges)
Set _2neibors according to the order of _LayerEdge on EDGE.
void SortOnEdge (const TopoDS_Edge &E, vector< _LayerEdge * > &edges, SMESH_MesherHelper &helper)
Sort _LayerEdge's by a parameter on a given EDGE.
Public Attributes
_EdgesOnShape & eos
_EdgesOnShape SMESH_MesherHelper & helper
Detailed Description
Data of a SOLID.
Member Typedef Documentation
THyp
typedef const StdMeshers_ViscousLayers* VISCOUS_3D::_SolidData::THyp
Member Function Documentation
AddShapesToSmooth()
void _SolidData::AddShapesToSmooth (const set< _EdgesOnShape * > & shape)
Add faces for smoothing.
References eos, and PrepareEdgesToSmoothOnFace().
GetConvexFace()
_ConvexFace * VISCOUS_3D::_SolidData::GetConvexFace (const TGeomID faceID)
GetShapeEdges() [1/3]
_EdgesOnShape * VISCOUS_3D::_SolidData::GetShapeEdges (const _LayerEdge * edge)
References GetShapeEdges().
GetShapeEdges() [2/3]
_EdgesOnShape * _SolidData::GetShapeEdges (const TGeomID shapeID)
Return _EdgesOnShape* corresponding to the shape.
Referenced by GetShapeEdges().
GetShapeEdges() [3/3]
_EdgesOnShape * _SolidData::GetShapeEdges (const TopoDS_Shape & shape)
Return _EdgesOnShape* corresponding to the shape.
References SMESH_ProxyMesh::GetMesh(), SMESH_Mesh::GetMeshDS(), GetShapeEdges(), and SMESHDS_Mesh::ShapeToIndex().
Handle()
VISCOUS_3D::_SolidData::Handle (Geom_Curve) const &
PrepareEdgesToSmoothOnFace()
void _SolidData::PrepareEdgesToSmoothOnFace (_EdgesOnShape * eof, bool substituteSrcNodes)
Prepare data of the _LayerEdge for smoothing on FACE.
References VISCOUS_3D::_LayerEdge::ChooseSmooFunction(), SMESH_ProxyMesh::GetMesh(), VISCOUS_3D::_Simplex::GetSimplices(), helper, VISCOUS_3D::isConcave(), VISCOUS_3D::_Curvature::New(), and draftgeoutils.general::vec().
Referenced by AddShapesToSmooth().
Sort2NeiborsOnEdge()
void _SolidData::Sort2NeiborsOnEdge (vector< _LayerEdge * > & edges)
Set _2neibors according to the order of _LayerEdge on EDGE.
References VISCOUS_3D::_2NearEdges::tgtNode().
Referenced by SortOnEdge().
SortOnEdge()
void _SolidData::SortOnEdge (const TopoDS_Edge & E, vector< _LayerEdge * > & edges, SMESH_MesherHelper & helper)
Sort _LayerEdge's by a parameter on a given EDGE.
References helper, and Sort2NeiborsOnEdge().
Member Data Documentation
eos
_EdgesOnShape& VISCOUS_3D::_SolidData::eos
Referenced by AddShapesToSmooth().
helper
_EdgesOnShape SMESH_MesherHelper& VISCOUS_3D::_SolidData::helper
Referenced by PrepareEdgesToSmoothOnFace(), and SortOnEdge().
The documentation for this struct was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_ViscousLayers.cpp