FreeCAD: Gui::TreeView Class Reference
Gui::TreeView Class Reference
#include <TreeView.h>
Public Member Functions
TreeView (QWidget *parent=0)
virtual ~TreeView ()
Protected Member Functions
void mouseDoubleClickEvent (QMouseEvent *)
void rowsInserted (const QModelIndex &parent, int start, int end)
Constructor & Destructor Documentation
TreeView()
TreeView::TreeView (QWidget * parent = 0)
~TreeView()
TreeView::~TreeView () virtual
Member Function Documentation
mouseDoubleClickEvent()
void TreeView::mouseDoubleClickEvent (QMouseEvent * event) protected
References Base::Persistence::getClassTypeId(), Gui::getMainWindow(), Base::BaseClass::getTypeId(), Gui::Application::Instance, Base::Type::isDerivedFrom(), and Gui::MainWindow::setActiveWindow().
rowsInserted()
void TreeView::rowsInserted (const QModelIndex & parent, int start, int end) protected
References Base::Type::fromName(), and Base::BaseClass::getTypeId().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/TreeView.h
Sources/FreeCAD/src/Gui/TreeView.cpp