FreeCAD: Path::Tooltable Class Reference
Path::Tooltable Class Reference
The representation of a table of tools.
#include <Tooltable.h>
Public Member Functions
void addTool (const Tool &tool)
void deleteTool (int)
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
unsigned int getSize (void) const
const Tool & getTool (int pos)
const std::map< int, ToolPtr > & getTools (void) const
bool hasTool (int pos) const
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
void setTool (const Tool &tool, int)
Tooltable ()
~Tooltable ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Attributes
std::string Name
std::map< int, ToolPtr > Tools
int Version
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The representation of a table of tools.
Constructor & Destructor Documentation
Tooltable()
Tooltable::Tooltable ()
~Tooltable()
Tooltable::~Tooltable ()
Member Function Documentation
addTool()
void Tooltable::addTool (const Tool & tool)
Referenced by setTool(), and PathScripts.PathToolLibraryEditor.EditorPanel::setupUi().
deleteTool()
void Tooltable::deleteTool (int pos)
getMemSize()
unsigned int Tooltable::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
getSize()
unsigned int Path::Tooltable::getSize (void) const
Referenced by Save().
getTool()
const Tool & Path::Tooltable::getTool (int pos)
getTools()
const std::map< int, ToolPtr > & Path::Tooltable::getTools (void) const
hasTool()
bool Path::Tooltable::hasTool (int pos) const
Restore()
void Tooltable::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References Base::XMLReader::getAttributeAsInteger(), and Base::XMLReader::readElement().
Referenced by Path::PropertyTooltable::Restore().
Save()
void Tooltable::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References Base::Writer::decInd(), getSize(), Base::Writer::incInd(), Base::Writer::ind(), and Base::Writer::Stream().
setTool()
void Tooltable::setTool (const Tool & tool, int pos)
References addTool().
Member Data Documentation
Name
std::string Path::Tooltable::Name
Tools
std::map<int,ToolPtr> Path::Tooltable::Tools
Version
int Path::Tooltable::Version
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Path/App/Tooltable.h
FreeCAD/src/Mod/Path/App/Tooltable.cpp