FreeCAD: Base::ConsoleSingleton Class Reference
Base::ConsoleSingleton Class Reference
The console class This class manage all the stdio stuff.
#include <Console.h>
Public Types
enum ConnectionMode { Direct = 0 , Queued =1 }
enum ConsoleMode { Verbose = 1 }
enumaration for the console modes
enum FreeCAD_ConsoleMsgType { MsgType_Txt = 1 , MsgType_Log = 2 , MsgType_Wrn = 4 , MsgType_Err = 8 }
Public Member Functions
void AttachObserver (ILogger *pcObserver)
Attaches an Observer to FCConsole.
void DetachObserver (ILogger *pcObserver)
Detaches an Observer from FCConsole.
void EnableRefresh (bool enable)
virtual void Error (const char *pMsg,...)
Prints a error Message.
ILogger * Get (const char *Name) const
int * GetLogLevel (const char *tag, bool create=true)
bool IsMsgTypeEnabled (const char *sObs, FreeCAD_ConsoleMsgType type) const
Enables or disables message types of a certain console observer.
virtual void Log (const char *pMsg,...)
Prints a log Message.
int LogLevel (int level) const
virtual void Message (const char *pMsg,...)
Prints a Message.
void NotifyError (const char *sMsg)
void NotifyLog (const char *sMsg)
void NotifyMessage (const char *sMsg)
void NotifyWarning (const char *sMsg)
void Refresh ()
void SetConnectionMode (ConnectionMode mode)
void SetConsoleMode (ConsoleMode m)
Change mode.
void SetDefaultLogLevel (int level)
ConsoleMsgFlags SetEnabledMsgType (const char *sObs, ConsoleMsgFlags type, bool b)
Enables or disables message types of a certain console observer.
void UnsetConsoleMode (ConsoleMode m)
Change mode.
virtual void Warning (const char *pMsg,...)
Prints a warning Message.
Static Public Member Functions
static ConsoleSingleton & Instance ()
singleton
Static Public Attributes
static const unsigned int BufferSize = 4024
static PyMethodDef Methods []
Protected Member Functions
ConsoleSingleton ()
virtual ~ConsoleSingleton ()
Static Protected Member Functions
static PyObject * sPyError (PyObject *self, PyObject *args)
static PyObject * sPyGetStatus (PyObject *self, PyObject *args)
static PyObject * sPyLog (PyObject *self, PyObject *args)
static PyObject * sPyMessage (PyObject *self, PyObject *args)
static PyObject * sPySetStatus (PyObject *self, PyObject *args)
static PyObject * sPyWarning (PyObject *self, PyObject *args)
Protected Attributes
ConnectionMode connectionMode
Friends
class ConsoleOutput
Detailed Description
The console class This class manage all the stdio stuff.
This includes Messages, Warnings, Log entries and Errors. The incoming Messages are distributed with the FCConsoleObserver. The FCConsole class itself makes no IO, it's more like a manager.
ConsoleSingleton is a singleton! That means you can access the only instance of the class from every where in c++ by simply using:
#include <Base/Console.h>
Base::Console().Log("Stage: %d",i);
ConsoleSingleton is able to switch between several modes to, e.g. switch the logging on or off, or treat Warnings as Errors, and so on...
See also
ConsoleObserver
Member Enumeration Documentation
ConnectionMode
enum Base::ConsoleSingleton::ConnectionMode
Enumerator
Direct
Queued
ConsoleMode
enum Base::ConsoleSingleton::ConsoleMode
enumaration for the console modes
Enumerator
Verbose
FreeCAD_ConsoleMsgType
enum Base::ConsoleSingleton::FreeCAD_ConsoleMsgType
Enumerator
MsgType_Txt
MsgType_Log
MsgType_Wrn
MsgType_Err
Constructor & Destructor Documentation
ConsoleSingleton()
ConsoleSingleton::ConsoleSingleton () protected
Referenced by Instance().
~ConsoleSingleton()
ConsoleSingleton::~ConsoleSingleton () protected virtual
References Base::ConsoleOutput::destruct().
Member Function Documentation
AttachObserver()
void ConsoleSingleton::AttachObserver (ILogger * pcObserver)
Attaches an Observer to FCConsole.
Attaches an Observer to Console Use this method to attach a ILogger derived class to the Console.
After the observer is attached all messages will also be forwarded to it.
See also
ILogger
Referenced by CmdTestConsoleOutput::activated(), Gui::DockWnd::ReportOutput::ReportOutput(), Gui::SplashObserver::SplashObserver(), and Gui::StatusBarObserver::StatusBarObserver().
DetachObserver()
void ConsoleSingleton::DetachObserver (ILogger * pcObserver)
Detaches an Observer from FCConsole.
Detaches an Observer from Console Use this method to detach a ILogger derived class.
After detaching you can destruct the Observer or reinsert it later.
See also
ILogger
Referenced by CmdTestConsoleOutput::activated(), App::Application::destructObserver(), ILoggerBlockerTest::~ILoggerBlockerTest(), Gui::DockWnd::ReportOutput::~ReportOutput(), Gui::SplashObserver::~SplashObserver(), and Gui::StatusBarObserver::~StatusBarObserver().
EnableRefresh()
void ConsoleSingleton::EnableRefresh (bool enable)
Referenced by Base::ConsoleRefreshDisabler::ConsoleRefreshDisabler(), and Base::ConsoleRefreshDisabler::~ConsoleRefreshDisabler().
Error()
void ConsoleSingleton::Error (const char * pMsg, ...) virtual
Prints a error Message.
Prints a Message This method issues an Error which makes some execution impossible.
Errors are used to get the users attention. That means when FreeCAD is running in GUI mode an Error Message Box pops up. In console mode a colored message is printed to the console! Don't use this carelessly. For information purposes the 'Log' or 'Message' methods are more appropriate.
You can use a printf like interface like:
Console().Error("Something really bad in %s happened\n",str);
See also
Message
Warning
Log
References Error().
Referenced by ReverseEngineeringGui::Segmentation::accept(), TechDrawGui::TaskWeldingSymbol::accept(), Gui::Dialog::DlgRevertToBackupConfigImp::accept(), Gui::PythonCommand::activated(), Gui::PythonGroupCommand::activated(), CmdTestConsoleOutput::activated(), Gui::StdCmdDownloadOnlineHelp::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), Gui::Application::activateWorkbench(), Sketcher::Sketch::addAngleAtPointConstraint(), TechDraw::DrawViewPart::addCenterLinesToGeom(), Sketcher::Sketch::addConstraints(), Sketcher::SketchObject::addCopy(), Sketcher::SketchObject::addExternal(), TechDraw::DrawProjGroup::addProjection(), Sketcher::Sketch::addSnellsLawConstraint(), Sketcher::SketchObject::addSymmetric(), Sketcher::Sketch::addTangentConstraint(), Gui::CommandManager::addTo(), TechDrawGui::QGSPage::addWeldSymbol(), Measure::Measurement::angle(), TechDraw::AOE::AOE(), TechDrawGui::TaskSectionView::apply(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), TechDraw::DrawProjGroup::arrangeViewPointers(), TechDraw::BaseGeom::baseFactory(), TechDrawGui::QGIFace::buildPixHatch(), TechDraw::CenterLine::calcEndPoints(), Sketcher::SketchObject::carbonCopy(), SurfaceGui::GeomFillSurface::changeFillType(), ParameterManager::CheckDocument(), Cloud::Module::cloudRestore(), Gui::cmdAppDocumentArgs(), Gui::cmdAppObjectArgs(), Gui::cmdGuiObjectArgs(), Gui::MacroManager::commit(), SpreadsheetGui::SheetView::confirmAliasChanged(), TechDrawGui::QGIViewDimension::constructDimensionArc(), TechDrawGui::QGIViewDimension::constructDimensionLine(), Sketcher::SketchObject::convertToNURBS(), TechDrawGui::Grabber3d::copyActiveViewToSvgFile(), Gui::PythonCommand::createAction(), Gui::PythonGroupCommand::createAction(), TechDrawGui::TaskActiveView::createActiveView(), TechDrawGui::QGISVGTemplate::createClickHandles(), TechDrawGui::TaskHatch::createHatch(), Gui::WidgetFactoryInst::createPreferencePage(), Gui::WidgetFactoryInst::createPrefWidget(), Part::ExtrusionHelper::createTaperedPrismOffset(), Gui::WidgetFactoryInst::createWidget(), SketcherGui::CurveConverter::CurveConverter(), Sketcher::SketchObject::decreaseBSplineDegree(), Sketcher::SketchObject::delAllExternal(), Sketcher::SketchObject::delExternal(), Measure::Measurement::delta(), Gui::doCommandT(), FemGui::ViewProviderFemPostObject::doubleClicked(), PartGui::ViewProviderPart::doubleClicked(), TechDrawGui::QGIViewDimension::draw(), TechDrawGui::QGIViewDimension::drawAngle(), TechDrawGui::QGIViewDimension::drawDiameter(), TechDrawGui::QGIViewDimension::drawDistanceExecutive(), TechDrawGui::QGIViewDimension::drawDistanceOverride(), TechDrawGui::QGIViewDimension::drawRadiusExecutive(), TechDrawGui::TaskDetail::editByHighlight(), Error(), Gui::ViewProvider::eventCallback(), Import::FeatureImportIges::Execute(), Import::FeatureImportStep::Execute(), TechDraw::DrawSVGTemplate::execute(), Sketcher::SketchObject::execute(), TechDraw::DrawViewArch::execute(), TechDraw::DrawViewDetail::execute(), TechDraw::DrawViewDimension::execute(), TechDraw::DrawViewPart::execute(), TechDraw::DrawViewSection::execute(), Fem::FemVTKTools::exportFreeCADResult(), Part::AttachExtension::extensionOnChanged(), PartDesignGui::TaskTransformedParameters::fillAxisCombo(), PartDesignGui::TaskTransformedParameters::fillPlanesCombo(), TechDrawGui::QGIViewPart::geomToPainterPath(), TechDraw::DrawGeomHatch::getDecodedSpecsFromFile(), TechDraw::DrawProjGroup::getDirsFromFront(), TechDraw::DrawViewDimension::getPointsEdgeVert(), TechDraw::DrawViewDimension::getPointsOneEdge(), TechDraw::DrawViewDimension::getPointsTwoEdges(), TechDraw::DrawViewDimension::getPointsTwoVerts(), TechDraw::LineGroup::getRecordFromFile(), TechDraw::ShapeExtractor::getShapes(), TechDraw::ShapeExtractor::getShapesFromObject(), TechDraw::ShapeExtractor::getShapesFused(), TechDraw::DrawViewSpreadsheet::getSheetImage(), TechDraw::DrawViewPart::getSourceShape(), TechDraw::DrawViewPart::getSourceShapeFused(), Fem::FemVTKTools::importFreeCADResult(), Fem::FemVTKTools::importVTKMesh(), Sketcher::SketchObject::increaseBSplineDegree(), Gui::Application::initApplication(), Sketcher::SketchObject::insertBSplineKnot(), TechDraw::DrawProjectSplit::isOnEdge(), Measure::Measurement::length(), TechDraw::LineGroup::lineGroupFactory(), MeshCore::MeshInput::LoadNastran(), StartGui::Workbench::loadStartPage(), TechDrawGui::QGIFace::loadSvgHatch(), PartDesignGui::TaskSketchBasedParameters::make2DLabel(), TechDrawGui::QGITile::makeSymbol(), SketcherGui::makeTangentToArcOfEllipseviaNewPoint(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), SketcherGui::makeTangentToArcOfParabolaviaNewPoint(), SketcherGui::makeTangentToEllipseviaNewPoint(), Measure::Measurement::massCenter(), Sketcher::SketchObject::modifyBSplineKnotMultiplicity(), SketcherGui::ViewProviderSketch::mouseButtonPressed(), Base::Subject< _MessageType >::Notify(), Gui::GUIApplication::notify(), Sketcher::SketchObject::onChanged(), Gui::ViewProviderOrigin::onChanged(), PartGui::SectionCut::onCutXvalueChanged(), PartGui::SectionCut::onCutYvalueChanged(), PartGui::SectionCut::onCutZvalueChanged(), SketcherGui::ViewProviderSketch::onDelete(), PartDesignGui::TaskExtrudeParameters::onDirectionCBChanged(), PartGui::SectionCut::onFlipXclicked(), PartGui::SectionCut::onFlipYclicked(), PartGui::SectionCut::onFlipZclicked(), Gui::Application::onLastWindowClosed(), PartGui::SectionCut::onRefreshCutPBclicked(), Gui::GestureNavigationStyle::onRollGesture(), SketcherGui::DrawSketchHandlerCarbonCopy::onSelectionChanged(), SketcherGui::DrawSketchHandlerExternal::onSelectionChanged(), TechDrawGui::TaskLeaderLine::onTrackerClicked(), TechDrawGui::TaskCosVertex::onTrackerFinished(), TechDrawGui::TaskLeaderLine::onTrackerFinished(), App::Application::openDocuments(), Gui::Dialog::PreferenceUiForm::PreferenceUiForm(), SketcherGui::DrawSketchHandlerBSpline::pressButton(), MeshPartGui::Tessellation::process(), App::Application::processCmdLineFiles(), SketcherGui::EditModeConstraintCoinManager::processConstraints(), App::Application::processFiles(), TechDraw::GeometryObject::projectShape(), TechDraw::GeometryObject::projectShapeWithPolygonAlgo(), Measure::Measurement::radius(), Points::E57Reader::read(), Base::XMLReader::readFiles(), App::Document::readObjects(), Fem::FemVTKTools::readResult(), Fem::FemVTKTools::readVTKMesh(), App::Document::recompute(), SketcherGui::DrawSketchHandlerBSpline::registerPressedKey(), DrawSketchHandlerBSplineInsertKnot::releaseButton(), DrawSketchHandlerCopy::releaseButton(), DrawSketchHandlerRectangularArray::releaseButton(), SketcherGui::DrawSketchHandlerArc::releaseButton(), SketcherGui::DrawSketchHandler3PointArc::releaseButton(), SketcherGui::DrawSketchHandlerArcOfEllipse::releaseButton(), SketcherGui::DrawSketchHandlerCircle::releaseButton(), SketcherGui::DrawSketchHandler3PointCircle::releaseButton(), SketcherGui::DrawSketchHandlerExtend::releaseButton(), SketcherGui::DrawSketchHandlerFillet::releaseButton(), SketcherGui::DrawSketchHandlerLine::releaseButton(), SketcherGui::DrawSketchHandlerLineSet::releaseButton(), SketcherGui::DrawSketchHandlerPoint::releaseButton(), SketcherGui::DrawSketchHandlerRegularPolygon::releaseButton(), SketcherGui::DrawSketchHandlerBox::releaseButton(), SketcherGui::DrawSketchHandlerOblong::releaseButton(), SketcherGui::DrawSketchHandlerSlot::releaseButton(), SketcherGui::DrawSketchHandlerSplitting::releaseButton(), SketcherGui::DrawSketchHandlerTrimming::releaseButton(), SketcherGui::DrawSketchHandlerArcOfHyperbola::releaseButton(), SketcherGui::DrawSketchHandlerArcOfParabola::releaseButton(), Base::PyException::ReportException(), Gui::View3DInventorViewer::resetEditingRoot(), App::PropertyContainer::Restore(), Part::PropertyGeometryList::Restore(), TechDraw::PropertyCenterLineList::Restore(), TechDraw::PropertyCosmeticEdgeList::Restore(), TechDraw::PropertyCosmeticVertexList::Restore(), TechDraw::PropertyGeomFormatList::Restore(), App::Document::restore(), Gui::Document::RestoreDocFile(), Fem::PropertyPostDataObject::RestoreDocFile(), App::ExtensionContainer::restoreExtensions(), Gui::ConsoleErrorTask::run(), Sandbox::PythonThread::run(), Gui::Application::runApplication(), ILoggerBlockerTest::runSingleTest(), TechDraw::CenterLine::Save(), App::PropertyContainer::Save(), Fem::PropertyPostDataObject::SaveDocFile(), App::ExtensionContainer::saveExtensions(), TechDraw::CenterLine::scaledGeometry(), PartGui::SectionCut::SectionCut(), SketcherGui::ViewProviderSketch::setEdit(), SketcherGui::ViewProviderSketch::setEditViewer(), Gui::PropertyEditor::PropertyItem::setPropertyValue(), Gui::ViewProviderOrigin::setTemporaryVisibility(), Gui::Application::sExport(), Gui::Application::sInsert(), Sketcher::SketchObject::solve(), Gui::Application::sOpen(), sPyError(), Gui::NetworkRetriever::startDownload(), TechDrawGui::QGIViewSymbol::symbolToSvg(), Base::RedirectStdError::sync(), MeshPart::MeshingOutput::sync(), PartDesignGui::TaskBoxPrimitives::TaskBoxPrimitives(), TechDrawGui::TaskCenterLine::TaskCenterLine(), TechDrawGui::TaskCosmeticLine::TaskCosmeticLine(), TechDrawGui::TaskDetail::TaskDetail(), Gui::TaskView::TaskDialogPython::TaskDialogPython(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), TechDrawGui::TaskRichAnno::TaskRichAnno(), TechDrawGui::TaskWeldingSymbol::TaskWeldingSymbol(), TechDrawGui::QGIFace::textureFromBitmap(), Gui::AutoSaver::timerEvent(), App::PropertyPythonObject::toString(), SketcherGui::ViewProviderSketch::unsetEdit(), PartDesignGui::ViewProviderAddSub::updateAddSubShapeIndicator(), Gui::ViewProviderVRMLObject::updateData(), FemGui::ViewProviderFemConstraintBearing::updateData(), PartGui::ViewProviderCurveNet::updateData(), TechDrawGui::TaskDetail::updateDetail(), PartDesignGui::ViewProviderBody::updateOriginDatumSize(), Gui::ViewProviderOriginGroupExtension::updateOriginSize(), Gui::OutputStderr::write(), Gui::PythonDebugStderr::write(), Fem::FemVTKTools::writeResult(), Fem::FemVTKTools::writeVTKMesh(), SketcherGui::CurveConverter::~CurveConverter(), PartDesignGui::TaskBoxPrimitives::~TaskBoxPrimitives(), PartDesignGui::TaskLinearPatternParameters::~TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::~TaskMirroredParameters(), and PartDesignGui::TaskPolarPatternParameters::~TaskPolarPatternParameters().
Get()
ILogger * ConsoleSingleton::Get (const char * Name) const
References Base::ILogger::Name().
Referenced by IsMsgTypeEnabled(), Base::Builder3D::saveToLog(), SetEnabledMsgType(), sPyGetStatus(), and sPySetStatus().
GetLogLevel()
int * ConsoleSingleton::GetLogLevel (const char * tag, bool create = true)
References femsolver.elmer.equations.elasticity::create().
Instance()
ConsoleSingleton & ConsoleSingleton::Instance () static
singleton
References ConsoleSingleton().
Referenced by Base::Console(), sPyError(), sPyGetStatus(), sPyLog(), sPyMessage(), sPySetStatus(), and sPyWarning().
IsMsgTypeEnabled()
bool ConsoleSingleton::IsMsgTypeEnabled (const char * sObs, FreeCAD_ConsoleMsgType type) const
Enables or disables message types of a certain console observer.
References Base::ILogger::bErr, Base::ILogger::bLog, Base::ILogger::bMsg, Base::ILogger::bWrn, Get(), MsgType_Err, MsgType_Log, MsgType_Txt, and MsgType_Wrn.
Log()
void ConsoleSingleton::Log (const char * pMsg, ...) virtual
Prints a log Message.
Prints a Message This method is appropriate for development and tracking purposes.
It can be used to track execution of algorithms and functions. The normal user doesn't need to see it, it's more for developers and experienced users. So in normal user mode the logging is switched off.
You can use a printf-like interface for example:
Console().Log("Execute part %d in algorithm %s\n",i,str);
See also
Message
Warning
Error
References Log().
Referenced by Gui::Application::activateWorkbench(), TechDraw::GeometryObject::addGeomFromCompound(), TechDraw::DrawProjGroup::addProjection(), TechDraw::DrawProjGroup::arrangeViewPointers(), TechDraw::BSpline::asCircle(), TechDrawGui::ViewProviderPage::attach(), TechDrawGui::MDIViewPage::attachView(), Sketcher::SketchAnalysis::autoconstraint(), Gui::NS::AwaitingMoveState::AwaitingMoveState(), Gui::NS::AwaitingReleaseState::AwaitingReleaseState(), TechDraw::BezierSegment::BezierSegment(), TechDraw::BSpline::BSpline(), TechDraw::DrawViewPart::buildGeometryObject(), TechDraw::GeometryObject::calcBoundingBox(), TechDraw::DrawProjGroup::calculateAutomaticScale(), Gui::MacroManager::cancel(), Gui::ViewProvider::canDropObject(), TechDraw::GeometryUtils::chainGeoms(), Sketcher::SketchObject::changeConstraintsLocking(), PartDesignGui::TaskHoleParameters::changedObject(), TechDraw::DrawViewDimension::checkReferences2D(), TechDraw::DrawViewPart::checkXDirection(), Gui::MacroManager::commit(), App::PropertyFileIncluded::Copy(), TechDrawGui::Grabber3d::copyActiveViewToSvgFile(), TechDrawGui::TaskCenterLine::createCenterLine(), Mesh::GTSAlgos::createGTSSurface(), FemGui::ViewProviderFEMMeshBuilder::createMesh(), Gui::WidgetFactoryInst::createPreferencePage(), Gui::WidgetFactoryInst::createWidget(), Gui::Dialog::ButtonModel::data(), App::Application::destruct(), TechDraw::DrawViewDetail::detailExec(), GCS::System::diagnose(), App::Document::Document(), MeshGui::ViewProviderMeshTransformDemolding::DragEndCallback(), TechDrawGui::QGIViewDimension::draw(), TechDrawGui::QGIViewBalloon::drawBalloon(), SketcherGui::ViewProviderSketch::editDoubleClicked(), Gui::ViewerEventFilter::eventFilter(), Drawing::FeaturePage::execute(), Fem::FemMeshShapeNetgenObject::execute(), Import::FeatureImportIges::Execute(), Import::FeatureImportStep::Execute(), Part::CurveNet::execute(), Part::ImportBrep::execute(), Part::ImportIges::execute(), Part::ImportStep::execute(), Raytracing::LuxProject::execute(), Raytracing::RayProject::execute(), TechDraw::DrawSVGTemplate::execute(), TechDraw::DrawViewDimension::execute(), TechDraw::DrawViewMulti::execute(), TechDraw::DrawViewSymbol::execute(), Fem::exportFemMeshCells(), Fem::exportFemMeshFaces(), Fem::FemVTKTools::exportFreeCADResult(), Fem::FemVTKTools::exportVTKMesh(), Gui::ViewProviderGroupExtension::extensionCanDropObject(), TechDraw::DrawGeomHatch::extractFace(), TechDraw::DrawViewPart::extractFaces(), Sketcher::SketchObject::fillet(), MeshCore::MeshAlgorithm::FillupHole(), MeshCore::MeshTopoAlgorithm::FillupHoles(), MeshCore::CylinderFit::Fit(), MeshGui::SoFCMeshFaceSet::generatePrimitives(), MeshGui::SoFCMeshObjectShape::generatePrimitives(), MeshGui::SoFCMeshSegmentShape::generatePrimitives(), Gui::NS::GestureState::GestureState(), TechDrawGui::DrawGuiUtil::get3DDirAndRot(), TechDraw::DrawProjGroup::getAnchorDirection(), TechDraw::DrawLeaderLine::getBaseScale(), TechDraw::DrawProjGroup::getBoundingBox(), TechDraw::BSpline::getCircleParms(), TechDrawGui::QGIView::getClipGroup(), TechDraw::DrawViewSection::getCSFromBase(), TechDraw::DrawProjectSplit::getEdges(), TechDraw::DrawSVGTemplate::getEditableTextsFromTemplate(), TechDraw::DrawViewPart::getFaceEdgesByIndex(), TechDraw::DrawGeomHatch::getFaceOverlay(), TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::DrawUtil::getIndexFromName(), TechDrawGui::ViewProviderPage::getMDIViewPage(), Fem::FemMesh::getNodesBySolid(), TechDrawGui::Grabber3d::getPaperScale(), TechDraw::LineSet::getPatternStartPoint(), TechDrawGui::DrawGuiUtil::getProjDirFromFace(), TechDraw::DrawProjGroup::getProjItem(), TechDraw::DrawProjGroup::getProjObj(), TechDraw::DrawViewPart::getProjVertexByCosTag(), TechDraw::DrawViewPart::getProjVertexByIndex(), TechDraw::DrawView::getScale(), TechDraw::DrawLeaderLine::getScale(), TechDraw::DrawProjGroupItem::getScale(), TechDraw::DrawViewSection::getSectionCS(), TechDraw::ShapeExtractor::getShapesFromObject(), TechDraw::PATLineSpec::getSpecsForPattern(), TechDraw::DrawGeomHatch::getTrimmedLines(), TechDraw::DrawPage::handleChangedPropertyType(), TechDraw::DrawView::handleChangedPropertyType(), PartGui::ViewProviderCurveNet::handleEvent(), TechDraw::DrawProjGroup::hasProjection(), Gui::NS::IdleState::IdleState(), Fem::FemVTKTools::importFreeCADResult(), Base::Type::importModule(), Part::ImportStepParts(), Fem::FemVTKTools::importVTKMesh(), Gui::GuiNativeEvent::initSpaceball(), Gui::NS::InteractState::InteractState(), Gui::Command::invoke(), TechDraw::DrawUtil::isCrazy(), Fem::FemPostPipeline::load(), Mesh::MeshObject::load(), Gui::NS::Event::log(), Log(), GCS::SolverReportingManager::LogToConsole(), MeshPart::CurveProjectorWithToolMesh::makeToolMesh(), TechDraw::mirrorShape(), TechDrawGui::QGIPrimPath::mousePressEvent(), TechDraw::moveShape(), Gui::GUIApplication::notify(), Gui::WindowParameter::OnChange(), TechDraw::DrawProjGroup::onChanged(), TechDraw::DrawViewSymbol::onChanged(), Gui::Document::onRelabel(), Gui::GestureNavigationStyle::onRollGesture(), TechDrawGui::MDIViewPage::onSelectionChanged(), Gui::GestureNavigationStyle::onSetRotationCenter(), Gui::Document::onUpdate(), Gui::View3DInventor::onUpdate(), Gui::MacroManager::open(), Gui::NS::PanState::PanState(), TechDraw::DrawViewPart::partExec(), TechDraw::EdgeWalker::perform(), Sketcher::SketchObject::port_reversedExternalArcs(), Gui::GestureNavigationStyle::EventQueue::post(), App::Application::processFiles(), Gui::MayaGestureNavigationStyle::processSoEvent(), TechDraw::DrawSVGTemplate::processTemplate(), MeshPart::CurveProjectorSimple::projectCurve(), MeshPart::CurveProjectorShape::projectCurve(), MeshPart::MeshProjection::projectEdgeToEdge(), TechDraw::GeometryObject::projectShape(), TechDraw::GeometryObject::projectShapeWithPolygonAlgo(), TechDraw::DrawProjGroup::purgeProjections(), Base::PyObjectBase::PyObjectBase(), TestJtReader::read(), Fem::FemVTKTools::readResult(), Fem::FemVTKTools::readVTKMesh(), TechDrawGui::TaskProjGroup::reject(), TechDrawGui::TaskLeaderLine::removeFeature(), TechDrawGui::TaskRichAnno::removeFeature(), TechDraw::DrawProjGroup::removeProjection(), TechDraw::rotateShape(), Gui::NS::RotateState::RotateState(), Gui::ConsoleLogTask::run(), App::Application::runApplication(), Gui::Application::runApplication(), ILoggerBlockerTest::runSingleTest(), Gui::AutoSaver::saveDocument(), TechDraw::scaleShape(), TechDrawGui::TaskProjGroup::scaleTypeChanged(), TechDrawGui::TaskSectionView::scaleTypeChanged(), Gui::Application::setActiveDocument(), TechDrawGui::QGTracker::setCircleFromPoints(), Gui::Translator::setLocale(), TechDrawGui::QGTracker::setPathFromPoints(), TechDrawGui::QGTracker::setSquareFromPoints(), Sketcher::Sketch::setUpSketch(), Gui::Application::slotDeleteDocument(), Sketcher::Sketch::solve(), TechDraw::EdgeWalker::sortStrip(), sPyLog(), FcLodHandler::startLod(), Gui::GUISingleApplication::Private::startServer(), Gui::NS::StickyPanState::StickyPanState(), Base::RedirectStdOutput::sync(), Base::RedirectStdLog::sync(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskPostDisplay::TaskPostDisplay(), FemGui::TaskPostScalarClip::TaskPostScalarClip(), FemGui::TaskPostWarpVector::TaskPostWarpVector(), Gui::NS::TiltState::TiltState(), SpaceNavigatorDevice::translateEvent(), MeshCore::AbstractPolygonTriangulator::TriangulatePolygon(), Sketcher::SketchObject::trim(), TechDraw::DrawPage::unsetupObject(), TechDraw::DrawProjGroup::updateChildrenEnforce(), TechDraw::DrawProjGroup::updateChildrenLock(), TechDraw::DrawProjGroup::updateChildrenScale(), TechDraw::DrawProjGroup::updateChildrenSource(), TechDrawGui::MDIViewPage::updateTemplate(), TechDrawGui::QGIRichAnno::updateView(), TechDraw::DrawProjGroup::updateViews(), PartGui::ViewProviderPartExt::updateVisual(), Gui::Application::viewActivated(), TechDraw::Wire::Wire(), Fem::FemMesh::write(), Fem::FemVTKTools::writeResult(), Raytracing::LuxTools::writeShape(), Raytracing::PovTools::writeShape(), Raytracing::PovTools::writeShapeCSV(), Fem::FemVTKTools::writeVTKMesh(), Fem::FemMesh::writeZ88(), Gui::Application::~Application(), App::Document::~Document(), TechDraw::DrawTemplate::~DrawTemplate(), Gui::GuiNativeEvent::~GuiNativeEvent(), and Base::PyObjectBase::~PyObjectBase().
LogLevel()
int Base::ConsoleSingleton::LogLevel (int level) const
Referenced by Base::LogLevel::level().
Message()
void ConsoleSingleton::Message (const char * pMsg, ...) virtual
Prints a Message.
Prints a Message This method issues a Message.
Messages are used to show some non vital information. That means when FreeCAD is running in GUI mode a Message appears on the status bar. In console mode a message is printed to the console.
You can use a printf like interface like:
Console().Message("Doing something important %d times\n",i);
See also
Warning
Error
Log
References Message().
Referenced by StdCmdViewIvIssueCamPos::activated(), CmdSandboxEventLoop::activated(), TechDraw::DrawViewPart::add1CEToGE(), TechDraw::DrawViewPart::add1CLToGE(), TechDraw::DrawViewPart::add1CVToGV(), TechDraw::GeometryObject::addCosmeticVertex(), TechDraw::DrawUtil::angleWithX(), Gui::PreferencePack::apply(), TechDrawGui::TaskSectionView::applyAligned(), TechDraw::BaseGeom::baseFactory(), PartGui::TaskMeasureLinear::buildDimension(), PartGui::TaskMeasureAngular::buildDimension(), TechDraw::CenterLine::calcEndPoints(), TechDraw::CenterLine::calcEndPoints2Lines(), TechDrawGui::TaskRichAnno::calcTextStartPos(), TechDraw::DrawUtil::copyFile(), TechDraw::DrawUtil::countEdges(), TechDraw::DrawUtil::countFaces(), TechDraw::DrawUtil::countWires(), TechDrawGui::QGISVGTemplate::createClickHandles(), Fem::createObjectByType(), MeshGui::ViewProviderMeshCurvature::curvatureInfoCallback(), TechDraw::DrawViewDetail::detailExec(), TechDrawGui::QGIWeldSymbol::drawTile(), TechDrawGui::QGIViewPart::drawViewPart(), TechDraw::LineFormat::dump(), TechDraw::CosmeticVertex::dump(), TechDraw::CosmeticEdge::dump(), TechDraw::CenterLine::dump(), TechDraw::DashSpec::dump(), TechDraw::PATLineSpec::dump(), TechDraw::LineGroup::dump(), TechDraw::GeomFormat::dump(), TechDraw::Vertex::dump(), TechDraw::DrawUtil::dump1Vertex(), TechDraw::DrawViewPart::dumpCosEdges(), TechDraw::DrawViewPart::dumpCosVerts(), TechDraw::DrawUtil::dumpCS(), TechDraw::DrawUtil::dumpCS3(), TechDraw::DrawUtil::dumpEdge(), TechDraw::DrawUtil::dumpEdges(), TechDrawGui::QGEPath::dumpGhostPoints(), TechDraw::DrawProjGroup::dumpISO(), PartGui::dumpLinearResults(), TechDrawGui::QGEPath::dumpMarkerPos(), TechDrawGui::QGIViewPart::dumpPath(), TechDrawGui::DrawGuiUtil::dumpPointF(), TechDrawGui::QGIView::dumpRect(), TechDrawGui::DrawGuiUtil::dumpRectF(), TechDraw::DrawUtil::dumpVertexes(), TechDraw::DrawViewPart::dumpVerts(), TechDraw::Ellipse::Ellipse(), PartGui::evaluateAngularPreSelection(), Base::Debugger::exec(), Inspection::Feature::execute(), Sandbox::SandboxObject::execute(), Import::ImpExpDxfWrite::exportBCurve(), Import::ImpExpDxfWrite::exportBSpline(), MeshGui::ViewProviderMesh::faceInfo(), MeshGui::ViewProviderMesh::faceInfoCallback(), MeshGui::ViewProviderMesh::fillHoleCallback(), TechDraw::BaseGeom::findEndPoints(), TechDrawGui::QGIViewDimension::findIsoExt(), MeshCore::SphereFit::Fit(), TechDrawGui::TaskDetail::getAnchorScene(), TechDrawGui::QGILeaderLine::getAttachFromFeature(), TechDraw::CosmeticExtension::getCosmeticEdge(), TechDrawGui::QGEPath::getDeltasFromLeader(), TechDrawGui::ViewProviderPage::getDrawPage(), TechDraw::DrawProjectSplit::getEdges(), TechDraw::DrawSVGTemplate::getEditableTextsFromTemplate(), TechDraw::BaseGeom::getEndPoint(), MeshGui::ViewProviderMesh::getFacetsFromPolygon(), TechDraw::LineGroup::getGroupNamesFromFile(), Fem::getObjectByType(), MeshGui::CylinderFitParameter::getParameter(), TechDraw::PATLineSpec::getPatternList(), CDxfWrite::getPlateFile(), TechDraw::LineGroup::getRecordFromFile(), TechDrawGui::TaskAlignViews::getSelectedEdges(), TechDraw::PATLineSpec::getSpecsForPattern(), TechDraw::BaseGeom::getStartPoint(), TechDraw::DrawViewPart::getViewAxis(), TechDraw::DrawProjGroupItem::getViewAxis(), TechDrawGui::QGILeaderLine::getWayPointsFromFeature(), TechDraw::DrawProjGroupItem::getXDirection(), TechDraw::ShapeExtractor::getXShapes(), TechDraw::DrawProjGroup::getXYPosition(), PartGui::goDimensionAngularNoTask(), MeshGui::ViewProviderMeshNode::handleEvent(), TechDrawGui::QGVNavStyle::handleKeyPressEvent(), TechDrawGui::QGVNavStyle::handleKeyReleaseEvent(), Fem::FemVTKTools::importFreeCADResult(), InspectionGui::ViewProviderInspection::inspectCallback(), TechDraw::DrawUtil::Intersect2d(), ModelRefine::FaceTypedBSpline::isEqual(), TechDraw::DrawProjectSplit::isOnEdge(), TechDraw::PATLineSpec::load(), Gui::MainWindow::loadUrls(), TechDrawGui::QGILeaderLine::makeLeaderPath(), TechDraw::DrawViewSection::makeLineSets(), Part::TopoShape::makeLoft(), MeshGui::ViewProviderMesh::markPartCallback(), Gui::ViewProviderMeasureDistance::measureDistanceCallback(), Message(), MeshGui::DlgEvaluateMeshImp::on_analyzeSelfIntersectionButton_clicked(), Fem::ConstraintFluidBoundary::onChanged(), Sandbox::SandboxObject::onChanged(), PartDesignGui::ViewProviderBody::onChanged(), TechDraw::DrawPage::onChanged(), TechDrawGui::TaskDetail::onHighlightMoved(), TechDrawGui::TaskAlignViews::onHorizontallyClicked(), FemGui::TaskCreateNodeSet::onSelectionChanged(), TechDrawGui::TaskLeaderLine::onTrackerClicked(), TechDrawGui::TaskCosVertex::onTrackerFinished(), TechDrawGui::TaskLeaderLine::onTrackerFinished(), MeshGui::ViewProviderMesh::partMeshCallback(), FemGui::TaskPostDataAlongLine::pointCallback(), FemGui::TaskPostDataAtPoint::pointCallback(), TechDrawGui::QGSPage::postProcessXml(), TechDraw::DrawSVGTemplate::processTemplate(), Fem::FemVTKTools::readResult(), TechDraw::DrawProjectSplit::removeDuplicateEdges(), TechDrawGui::TaskLeaderLine::removeFeature(), TechDraw::CosmeticExtension::replaceCenterLine(), TechDraw::CosmeticExtension::replaceCosmeticEdge(), TechDraw::CosmeticExtension::replaceCosmeticVertex(), TechDraw::CosmeticExtension::replaceGeomFormat(), TechDraw::DrawViewImage::replaceImageIncluded(), Sandbox::SandboxObject::resetValue(), App::Document::Restore(), TechDrawGui::TaskProjGroup::restoreGroupState(), Part::TopoShape::revolve(), BarThread::run(), Gui::ConsoleMessageTask::run(), Sandbox::DocumentTestThread::run(), MeshTestJob::run(), Gui::Application::runApplication(), ILoggerBlockerTest::runSingleTest(), TechDraw::CenterLine::Save(), TechDraw::DrawViewSection::sectionExec(), MeshGui::ViewProviderMesh::segmMeshCallback(), Sandbox::SandboxObject::setIntValue(), TechDrawGui::QGTracker::setPoint(), TechDraw::DrawViewImage::setupImageIncluded(), TechDrawGui::QGEPath::showMarkers(), TechDraw::DrawUtil::simpleMinDist(), TechDraw::DrawProjectSplit::split1Edge(), sPyMessage(), TechDrawGui::TaskAlignViews::TaskAlignViews(), TechDraw::DrawProjGroup::updateSecondaryDirs(), TechDrawGui::TaskWeldingSymbol::updateTiles(), Gui::OutputStdout::write(), and Fem::FemVTKTools::writeResult().
NotifyError()
void ConsoleSingleton::NotifyError (const char * sMsg)
References Base::Error.
Referenced by Base::ConsoleOutput::customEvent().
NotifyLog()
void ConsoleSingleton::NotifyLog (const char * sMsg)
References Base::Log.
Referenced by Base::ConsoleOutput::customEvent().
NotifyMessage()
void ConsoleSingleton::NotifyMessage (const char * sMsg)
References Base::Message.
Referenced by Base::ConsoleOutput::customEvent().
NotifyWarning()
void ConsoleSingleton::NotifyWarning (const char * sMsg)
References Base::Warning.
Referenced by Base::ConsoleOutput::customEvent().
Refresh()
void ConsoleSingleton::Refresh ()
SetConnectionMode()
void ConsoleSingleton::SetConnectionMode (ConnectionMode mode)
References connectionMode, Base::ConsoleOutput::getInstance(), and Queued.
SetConsoleMode()
void ConsoleSingleton::SetConsoleMode (ConsoleMode m)
Change mode.
sets the console in a special mode
References Verbose.
SetDefaultLogLevel()
void Base::ConsoleSingleton::SetDefaultLogLevel (int level)
SetEnabledMsgType()
ConsoleMsgFlags ConsoleSingleton::SetEnabledMsgType (const char * sObs, ConsoleMsgFlags type, bool b)
Enables or disables message types of a certain console observer.
type can be OR'ed with any of the FreeCAD_ConsoleMsgType flags to enable – if b is true – or to disable – if b is false – a console observer with name sObs.
The return value is an OR'ed value of all message types that have changed their state. For example
// switch off warnings and error messages
ConsoleMsgFlags ret = Base::Console().SetEnabledMsgType("myObs",
                      Base:ConsoleSingleton::MsgType_Wrn|Base::ConsoleSingleton::MsgType_Err, false);
// do something without notifying observer myObs
...
// restore the former configuration again
Base::Console().SetEnabledMsgType("myObs", ret, true);
switches off warnings and error messages and restore the state before the modification. If the observer sObs doesn't exist then nothing happens.
References Base::ILogger::bErr, Base::ILogger::bLog, Base::ILogger::bMsg, Base::ILogger::bWrn, Get(), MsgType_Err, MsgType_Log, MsgType_Txt, and MsgType_Wrn.
Referenced by Base::ILoggerBlocker::ILoggerBlocker(), ILoggerBlockerTest::runTest(), and Base::ILoggerBlocker::~ILoggerBlocker().
sPyError()
PyObject * ConsoleSingleton::sPyError (PyObject * self, PyObject * args) static protected
References Error(), and Instance().
sPyGetStatus()
PyObject * ConsoleSingleton::sPyGetStatus (PyObject * self, PyObject * args) static protected
References Base::ILogger::bErr, Base::ILogger::bLog, Base::ILogger::bMsg, Base::ILogger::bWrn, Get(), and Instance().
sPyLog()
PyObject * ConsoleSingleton::sPyLog (PyObject * self, PyObject * args) static protected
References Instance(), and Log().
sPyMessage()
PyObject * ConsoleSingleton::sPyMessage (PyObject * self, PyObject * args) static protected
References Instance(), and Message().
sPySetStatus()
PyObject * ConsoleSingleton::sPySetStatus (PyObject * self, PyObject * args) static protected
References Base::ILogger::bErr, Base::ILogger::bLog, Base::ILogger::bMsg, Base::ILogger::bWrn, Get(), Instance(), and Base::PyExc_FC_GeneralError.
sPyWarning()
PyObject * ConsoleSingleton::sPyWarning (PyObject * self, PyObject * args) static protected
References Instance(), and Warning().
UnsetConsoleMode()
void ConsoleSingleton::UnsetConsoleMode (ConsoleMode m)
Change mode.
unsets the console from a special mode
References Verbose.
Warning()
void ConsoleSingleton::Warning (const char * pMsg, ...) virtual
Prints a warning Message.
Prints a Message This method issues a Warning.
Messages are used to get the users attention. That means when FreeCAD is in GUI mode a Message Box pops up. In console mode a colored message is returned to the console! Don't use this carelessly. For information purposes the 'Log' or 'Message' methods are more appropriate.
You can use a printf like interface like:
Console().Warning("Some defects in %s, loading anyway\n",str);
See also
Message
Error
Log
References Warning().
Referenced by Gui::TaskView::TaskView::accept(), FemGui::TaskDlgCreateNodeSet::accept(), FemGui::TaskDlgMeshShapeNetgen::accept(), FemGui::TaskDlgFemConstraintFluidBoundary::accept(), MeshGui::GmshWidget::accept(), ReverseEngineeringGui::Segmentation::accept(), RobotGui::TaskDlgEdge2Trac::accept(), Sketcher::Sketch::addEqualConstraint(), Sketcher::Sketch::addPerpendicularConstraint(), Gui::CommandManager::addTo(), TechDraw::DrawPage::addView(), Sketcher::SketchAnalysis::analyseMissingPointOnPointCoincident(), TechDraw::DrawUtil::angleWithX(), TechDraw::DrawProjGroup::arrangeViewPointers(), TechDrawGui::ViewProviderDrawingView::attach(), TechDraw::Preferences::bitmapFill(), PartDesignGui::TaskFeaturePick::buildFeatures(), TechDrawGui::QGIFace::buildPixHatch(), TechDrawGui::QGIFace::buildSvgHatch(), Gui::PropertyEditor::PropertyEditor::buildUp(), TechDraw::CenterLine::calcEndPoints(), TechDraw::CenterLine::calcEndPoints2Lines(), TechDraw::CenterLine::calcEndPoints2Points(), Attacher::AttachEngine3D::calculateAttachedPlacement(), Attacher::AttachEngineLine::calculateAttachedPlacement(), TechDraw::CenterLine::CenterLineBuilder(), Gui::Application::checkForPreviousCrashes(), Part::ExtrusionHelper::checkInnerWires(), FemGui::TaskDlgMeshShapeNetgen::clicked(), RobotGui::TaskDlgEdge2Trac::clicked(), Base::ConsoleObserverFile::ConsoleObserverFile(), TechDrawGui::Grabber3d::copyActiveViewToSvgFile(), TechDrawGui::QGISVGTemplate::createClickHandles(), PartGui::ViewProvider2DObjectGrid::createGrid(), Gui::DocumentItem::createNewItem(), Gui::WidgetFactoryInst::createPreferencePage(), Gui::WidgetFactoryInst::createWidget(), TechDrawGui::QGIFace::dashedPPath(), TechDraw::Preferences::defaultTemplate(), TechDraw::Preferences::defaultTemplateDir(), TechDraw::DrawViewDetail::detailExec(), GCS::System::diagnose(), TechDrawGui::QGIViewAnnotation::drawAnnotation(), TechDrawGui::QGIViewClip::drawClip(), SketcherGui::EditModeConstraintCoinManager::drawConstraintIcons(), TechDrawGui::QGIViewSection::drawSectionFace(), PartDesign::Transformed::execute(), Sketcher::SketchObjectSF::execute(), TechDraw::DrawViewDetail::execute(), TechDraw::DrawViewDimension::execute(), TechDraw::DrawViewPart::execute(), TechDraw::DrawViewSection::execute(), TechDraw::DrawViewSymbol::execute(), Import::ImpExpDxfWrite::exportShape(), TechDraw::DrawViewPart::extractFaces(), TechDraw::GeometryObject::extractGeometry(), Gui::PrefWidget::failedToRestore(), Gui::PrefWidget::failedToSave(), ParameterGrp::FindElement(), ParameterGrp::FindOrCreateElement(), TechDraw::DrawViewSection::findSectionPlaneIntersections(), TechDraw::DrawViewDimension::formatValue(), Path::Toolpath::getCycleTime(), TechDrawGui::QGEPath::getDeltasFromLeader(), TechDraw::DrawViewDimension::getDimValue(), TechDraw::DrawProjGroup::getDirsFromFront(), TechDraw::DrawLeaderLine::getKinkPoint(), TechDraw::DrawViewDimension::getPrefixSuffixSpec(), TechDrawGui::DrawGuiUtil::getProjDirFromFace(), TechDraw::DrawViewPart::getProjectionCS(), TechDraw::DrawViewPart::getSourceShape(), TechDraw::DrawViewPart::getSourceShapeFused(), TechDraw::DrawLeaderLine::getTailPoint(), TechDraw::DrawLeaderLine::getTileOrigin(), AttacherGui::getUIStrings(), TechDraw::DrawProjGroupItem::getViewAxis(), TechDraw::DrawProjGroup::getViewIndex(), TechDrawGui::QGILeaderLine::getWayPointsFromFeature(), Gui::View3DInventorViewer::imageFromFramebuffer(), Gui::View3DInventorViewer::init(), TechDrawGui::TaskGeomHatch::initUi(), Sketcher::SketchObject::isCarbonCopyAllowed(), Sketcher::SketchObject::isExternalAllowed(), TechDraw::Preferences::lineGroupFile(), TechDrawGui::QGIFace::lineSetToFillItems(), Mesh::MeshObject::load(), MeshCore::MeshInput::LoadAny(), MeshCore::MeshInput::LoadNastran(), Spreadsheet::PropertySheet::mergeCells(), Gui::SelectionSingleton::notify(), Gui::Dialog::DlgCustomKeyboardImp::on_editShortcut_textChanged(), Gui::Dialog::DlgMacroExecuteImp::on_toolbarButton_clicked(), TechDraw::DrawViewDimension::onChanged(), TechDraw::DrawViewSymbol::onChanged(), App::Document::onChanged(), PartGui::SectionCut::onCutXvalueChanged(), PartGui::SectionCut::onCutYvalueChanged(), PartGui::SectionCut::onCutZvalueChanged(), PartGui::SectionCut::onFlipXclicked(), PartGui::SectionCut::onFlipYclicked(), PartGui::SectionCut::onFlipZclicked(), Import::ImpExpDxfRead::OnReadArc(), Import::ImpExpDxfRead::OnReadCircle(), Import::ImpExpDxfRead::OnReadEllipse(), Import::ImpExpDxfRead::OnReadSpline(), TechDrawGui::QGILeaderLine::onSourceChange(), TechDraw::Preferences::patFile(), Gui::BitmapFactoryInst::pixmap(), Gui::Command::printConflictingAccelerators(), TechDrawGui::MDIViewPage::printPdf(), App::Application::processCmdLineFiles(), App::Application::processFiles(), Base::ScriptFactorySingleton::ProduceScript(), Gui::NS::GestureState::react(), Attacher::AttachEngine::readLinks(), Gui::TaskView::TaskView::reject(), TechDrawGui::TaskRichAnno::removeFeature(), Gui::View3DInventorViewer::resetEditingRoot(), TechDraw::CosmeticEdge::Restore(), TechDraw::CenterLine::Restore(), App::PropertyPythonObject::Restore(), App::PropertyEnumeration::Restore(), App::PropertyLink::Restore(), App::PropertyLinkSubList::Restore(), Fem::PropertyPostDataObject::RestoreDocFile(), TechDrawGui::QGIProjGroup::rotateView(), Gui::ConsoleWarningTask::run(), Gui::Application::runApplication(), Gui::PythonDebugger::runFile(), ILoggerBlockerTest::runSingleTest(), TechDraw::CosmeticEdge::Save(), MeshCore::MeshOutput::SaveOBJ(), MeshCore::MeshOutput::SaveOFF(), TechDrawGui::MDIViewPage::saveSVG(), TechDraw::CenterLine::scaledGeometry(), TechDraw::DrawViewSection::sectionExec(), Gui::Application::setActiveDocument(), SketcherGui::ViewProviderSketch::setEdit(), Gui::PrefWidget::setParamGrpPath(), Gui::SelectionSingleton::slotSelectionChanged(), Sketcher::SketchObject::solve(), TechDraw::LineGroup::split(), sPyWarning(), Gui::Application::sSendActiveView(), Gui::Application::sSendFocusView(), TechDraw::Preferences::svgFile(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), Gui::TaskView::TaskSelectLinkProperty::TaskSelectLinkProperty(), TechDraw::DrawPage::unsetupObject(), TechDraw::DrawProjGroupItem::unsetupObject(), TechDrawGui::QGILeaderLine::updateView(), TechDrawGui::QGIWeldSymbol::updateView(), Warning(), TechDrawGui::PreferencesGui::weldingDirectory(), PartGui::DlgProjectionOnSurface::~DlgProjectionOnSurface(), DocOpenGuard::~DocOpenGuard(), Base::ILoggerBlocker::~ILoggerBlocker(), and App::Application::TransactionSignaller::~TransactionSignaller().
Friends And Related Function Documentation
ConsoleOutput
friend class ConsoleOutput friend
Member Data Documentation
BufferSize
const unsigned int Base::ConsoleSingleton::BufferSize = 4024 static
Referenced by GCS::SolverReportingManager::LogToConsole().
connectionMode
ConnectionMode Base::ConsoleSingleton::connectionMode protected
Referenced by SetConnectionMode().
Methods
PyMethodDef ConsoleSingleton::Methods static
Initial value:
= {
    {"PrintMessage",         ConsoleSingleton::sPyMessage, METH_VARARGS,
     "PrintMessage(string) -- Print a message to the output"},
    {"PrintLog",             ConsoleSingleton::sPyLog, METH_VARARGS,
     "PrintLog(string) -- Print a log message to the output"},
    {"PrintError"  ,         ConsoleSingleton::sPyError, METH_VARARGS,
     "PrintError(string) -- Print an error message to the output"},
    {"PrintWarning",         ConsoleSingleton::sPyWarning, METH_VARARGS,
     "PrintWarning -- Print a warning to the output"},
    {"SetStatus",            ConsoleSingleton::sPySetStatus, METH_VARARGS,
     "Set the status for either Log, Msg, Wrn or Error for an observer"},
    {"GetStatus",            ConsoleSingleton::sPyGetStatus, METH_VARARGS,
     "Get the status for either Log, Msg, Wrn or Error for an observer"},
    {nullptr, nullptr, 0, nullptr}
}
The documentation for this class was generated from the following files:
FreeCAD/src/Base/Console.h
FreeCAD/src/Base/Console.cpp