FreeCAD: e57::BufferView Class Reference
e57::BufferView Class Reference
Tool class to read buffer efficiently without multiplying copy operations.
Public Member Functions
BufferView (const char *input, uint64_t size)
uint64_t pos () const
void read (char *buffer, uint64_t count)
bool seek (uint64_t offset, int whence)
Detailed Description
Tool class to read buffer efficiently without multiplying copy operations.
WARNING: pointer input is handled by user!
Constructor & Destructor Documentation
BufferView()
e57::BufferView::BufferView (const char * input, uint64_t size)
Parameters
[IN] input: filled buffer owned by caller.
[IN] size: size of input
Member Function Documentation
pos()
uint64_t e57::BufferView::pos () const
Referenced by draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_stretch.Stretch::action(), Mod.PartDesign.fcgear.fcgear.FCWireBuilder::arc(), Mod.PartDesign.fcgear.svggear.SVGWireBuilder::arc(), Mod.PartDesign.fcsprocket.fcsprocket.FCWireBuilder::arc(), Mod.PartDesign.fcgear.fcgear.FCWireBuilder::curve(), Mod.PartDesign.fcgear.svggear.SVGWireBuilder::curve(), Mod.PartDesign.fcsprocket.fcsprocket.FCWireBuilder::curve(), Mod.PartDesign.fcgear.fcgear.FCWireBuilder::line(), Mod.PartDesign.fcgear.svggear.SVGWireBuilder::line(), Mod.PartDesign.fcsprocket.fcsprocket.FCWireBuilder::line(), Mod.PartDesign.fcgear.fcgear.FCWireBuilder::move(), Mod.PartDesign.fcgear.svggear.SVGWireBuilder::move(), Mod.PartDesign.fcsprocket.fcsprocket.FCWireBuilder::move(), and draftguitools.gui_trackers.boxTracker::update().
read()
void e57::BufferView::read (char * buffer, uint64_t count)
Referenced by gzip_utf8.GzipFile::readline(), and gzip_utf8.GzipFile::seek().
seek()
bool e57::BufferView::seek (uint64_t offset, int whence)
References draftfunctions.offset::offset().
The documentation for this class was generated from the following file:
FreeCAD/src/3rdParty/libE57Format/src/CheckedFile.cpp