FreeCAD: nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX > Class Template Reference
nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX > Class Template Reference
deserialization of CBOR, MessagePack, and UBJSON values
#include <json.hpp>
Public Member Functions
binary_reader (binary_reader &&)=default
binary_reader (const binary_reader &)=delete
binary_reader (InputAdapterType &&adapter)
create a binary reader
binary_reader & operator= (binary_reader &&)=default
binary_reader & operator= (const binary_reader &)=delete
bool sax_parse (const input_format_t format, json_sax_t *sax_, const bool strict=true, const cbor_tag_handler_t tag_handler=cbor_tag_handler_t::error)
~binary_reader ()=default
Detailed Description
template<typename BasicJsonType, typename InputAdapterType, typename SAX = json_sax_dom_parser<BasicJsonType>>
class nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >
deserialization of CBOR, MessagePack, and UBJSON values
Constructor & Destructor Documentation
binary_reader() [1/3]
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>> nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::binary_reader (InputAdapterType && adapter) explicit
create a binary reader
Parameters
[in] adapter input adapter to read from
binary_reader() [2/3]
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>> nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::binary_reader (const binary_reader< BasicJsonType, InputAdapterType, SAX > &) delete
binary_reader() [3/3]
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>> nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::binary_reader (binary_reader< BasicJsonType, InputAdapterType, SAX > &&) default
~binary_reader()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>> nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::~binary_reader () default
Member Function Documentation
operator=() [1/2]
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>> binary_reader & nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::operator= (binary_reader< BasicJsonType, InputAdapterType, SAX > &&) default
operator=() [2/2]
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>> binary_reader & nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::operator= (const binary_reader< BasicJsonType, InputAdapterType, SAX > &) delete
sax_parse()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>> bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax_parse (const input_format_t format, json_sax_t * sax_, const bool strict = true, const cbor_tag_handler_t tag_handler = cbor_tag_handler_t::error)
Parameters
[in] format the binary format to parse
[in] sax_ a SAX event processor
[in] strict whether to expect the input to be consumed completed
[in] tag_handler how to treat CBOR tags
Returns
References nlohmann::detail::bson, nlohmann::detail::cbor, nlohmann::detail::parse_error::create(), nlohmann::detail::msgpack, nlohmann::detail::strict, and nlohmann::detail::ubjson.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::from_bson(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::from_cbor(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::from_msgpack(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::from_ubjson(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::sax_parse().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/PartDesign/App/json.hpp