FreeCAD: feminout.importPyMesh Namespace Reference
feminout.importPyMesh Namespace Reference
Functions
def export (objectslist, filename)
def write (fem_mesh, filename)
def write_python_mesh_to_file (femnodes_mesh, femelement_table, fem_mesh_type, f)
Variables
pyopen = open
Function Documentation
export()
def feminout.importPyMesh.export (objectslist, filename)
References feminout.importPyMesh.pyopen, and feminout.importPyMesh.write_python_mesh_to_file().
write()
def feminout.importPyMesh.write (fem_mesh, filename)
directly write a FemMesh to a Python mesh file
fem_mesh: a FemMesh
References feminout.importPyMesh.pyopen, and feminout.importPyMesh.write_python_mesh_to_file().
write_python_mesh_to_file()
def feminout.importPyMesh.write_python_mesh_to_file (femnodes_mesh, femelement_table, fem_mesh_type, f)
Referenced by feminout.importPyMesh.export(), and feminout.importPyMesh.write().
Variable Documentation
pyopen
feminout.importPyMesh.pyopen = open
Referenced by feminout.importPyMesh.export(), and feminout.importPyMesh.write().