FreeCAD: StdMeshers_Penta_3D Class Reference
StdMeshers_Penta_3D Class Reference
#include <StdMeshers_Penta_3D.hxx>
Public Member Functions
bool Compute (SMESH_Mesh &, const TopoDS_Shape &)
int ErrorStatus () const
bool Evaluate (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, MapShapeNbElems &aResMap)
SMESH_ComputeErrorPtr GetComputeError () const
bool LoadIJNodes (StdMeshers_IJNodeMap &theIJNodes, const TopoDS_Face &theFace, const TopoDS_Edge &theBaseEdge, SMESHDS_Mesh *theMesh)
void SetTolerance (const double theTol3D)
StdMeshers_Penta_3D ()
double Tolerance () const
~StdMeshers_Penta_3D ()
Protected Member Functions
void CheckData ()
void ClearMeshOnFxy1 ()
void CreateNode (const bool theIsUpperLayer, const gp_XYZ &aParams, StdMeshers_TNode &aTN)
void FindNodeOnShape (const TopoDS_Shape &aS, const gp_XYZ &aParams, const int z, StdMeshers_TNode &aTN)
int GetIndexOnLayer (const int aID)
SMESH_Mesh * GetMesh () const
void MakeBlock ()
void MakeConnectingMap ()
void MakeMeshOnFxy1 ()
void MakeNodes ()
void MakeVolumeMesh ()
double SetHorizEdgeXYZ (const gp_XYZ &aBNXYZ, const int aFaceID, std::vector< const SMDS_MeshNode * > *&aCol1, std::vector< const SMDS_MeshNode * > *&aCol2)
void SetMesh (SMESH_Mesh &theMesh)
void ShapeSupportID (const bool theIsUpperLayer, const SMESH_Block::TShapeID theBNSSID, SMESH_Block::TShapeID &theSSID)
Protected Attributes
StdMeshers_SMESHBlock myBlock
std::map< int, int > myConnectingMap
bool myCreateQuadratic
SMESH_ComputeErrorPtr myErrorStatus
int myISize
int myJSize
void * myMesh
TopoDS_Shape myShape
std::vector< gp_XYZ > myShapeXYZ
std::vector< StdMeshers_TNode > myTNodes
double myTol3D
SMESH_MesherHelper * myTool
std::vector< StdMeshers_IJNodeMap > myWallNodesMaps
Constructor & Destructor Documentation
StdMeshers_Penta_3D()
StdMeshers_Penta_3D::StdMeshers_Penta_3D ()
References myShapeXYZ, myTol3D, myTool, myWallNodesMaps, SMESH_Block::NbFaces(), and SMESH_Block::NbSubShapes().
~StdMeshers_Penta_3D()
StdMeshers_Penta_3D::~StdMeshers_Penta_3D ()
Member Function Documentation
CheckData()
void StdMeshers_Penta_3D::CheckData () protected
References myErrorStatus, and myShape.
Referenced by Compute().
ClearMeshOnFxy1()
void StdMeshers_Penta_3D::ClearMeshOnFxy1 () protected
References SMESH_subMesh::CLEAN, SMESH_subMesh::ComputeStateEngine(), GetMesh(), SMESH_Mesh::GetSubMeshContaining(), SMESH_Block::ID_Fxy1, myBlock, and StdMeshers_SMESHBlock::Shape().
Referenced by Compute().
Compute()
bool StdMeshers_Penta_3D::Compute (SMESH_Mesh & aMesh, const TopoDS_Shape & aShape)
References CheckData(), ClearMeshOnFxy1(), SMESH_MesherHelper::IsQuadraticSubMesh(), MakeBlock(), MakeConnectingMap(), MakeMeshOnFxy1(), MakeNodes(), MakeVolumeMesh(), myCreateQuadratic, myErrorStatus, myShape, myTool, and SetMesh().
CreateNode()
void StdMeshers_Penta_3D::CreateNode (const bool theIsUpperLayer, const gp_XYZ & aParams, StdMeshers_TNode & aTN) protected
References SMESHDS_Mesh::AddNode(), GetMesh(), SMESH_Mesh::GetMeshDS(), SMESH_Block::ID_E0y1, SMESH_Block::ID_E1y1, SMESH_Block::ID_Ex01, SMESH_Block::ID_Ex11, SMESH_Block::ID_V001, SMESH_Block::ID_V011, SMESH_Block::ID_V101, SMESH_Block::ID_V111, myShapeXYZ, StdMeshers_TNode::SetNode(), SMESH_Block::ShellPoint(), and draftgeoutils.general::v1().
Referenced by MakeNodes().
ErrorStatus()
int StdMeshers_Penta_3D::ErrorStatus () const
Evaluate()
bool StdMeshers_Penta_3D::Evaluate (SMESH_Mesh & aMesh, const TopoDS_Shape & aShape, MapShapeNbElems & aResMap)
References SMESH_Mesh::GetSubMesh(), SMESH_MesherHelper::IsQuadraticSubMesh(), and myErrorStatus.
FindNodeOnShape()
void StdMeshers_Penta_3D::FindNodeOnShape (const TopoDS_Shape & aS, const gp_XYZ & aParams, const int z, StdMeshers_TNode & aTN) protected
References StdMeshers_TNode::BaseNodeID(), SMDS_Mesh::FindNode(), GetMesh(), SMESH_Mesh::GetMeshDS(), SMESHDS_SubMesh::GetNodes(), SMESH_Block::GetShapeIDByParams(), SMESH_Mesh::GetSubMeshContaining(), SMESH_subMesh::GetSubMeshDS(), SMESH_Block::IsFaceID(), SMESH_MesherHelper::IsMedium(), myBlock, myTol3D, myTool, myWallNodesMaps, StdMeshers_SMESHBlock::Point(), StdMeshers_TNode::SetNode(), StdMeshers_SMESHBlock::ShapeID(), SMESH_Block::ShapeIndex(), SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
Referenced by MakeNodes().
GetComputeError()
SMESH_ComputeErrorPtr StdMeshers_Penta_3D::GetComputeError () const
GetIndexOnLayer()
int StdMeshers_Penta_3D::GetIndexOnLayer (const int aID) protected
References myConnectingMap, and myErrorStatus.
Referenced by MakeMeshOnFxy1(), and MakeVolumeMesh().
GetMesh()
SMESH_Mesh* StdMeshers_Penta_3D::GetMesh () const protected
Referenced by ClearMeshOnFxy1(), CreateNode(), FindNodeOnShape(), MakeBlock(), MakeMeshOnFxy1(), MakeNodes(), and MakeVolumeMesh().
LoadIJNodes()
bool StdMeshers_Penta_3D::LoadIJNodes (StdMeshers_IJNodeMap & theIJNodes, const TopoDS_Face & theFace, const TopoDS_Edge & theBaseEdge, SMESHDS_Mesh * theMesh)
References SMESH_MeshAlgos::FindFaceInSet(), SMESHDS_SubMesh::GetElements(), SMESHDS_SubMesh::GetNodes(), SMDS_MeshNode::GetPosition(), SMESH_MesherHelper::IsMedium(), SMESHDS_Mesh::MeshElements(), myCreateQuadratic, myTool, SMESHDS_SubMesh::NbNodes(), and SMDS_MeshElement::nodesIterator().
Referenced by MakeNodes().
MakeBlock()
void StdMeshers_Penta_3D::MakeBlock () protected
References StdMeshers_SMESHBlock::ErrorStatus(), SMESHDS_SubMesh::GetElements(), StdMeshers_SMESHBlock::GetError(), GetMesh(), SMESH_Mesh::GetMeshDS(), SMESH_Mesh::GetSubMeshContaining(), SMESH_subMesh::GetSubMeshDS(), SMDS_MeshElement::GetType(), SMDS_MeshElement::IsQuadratic(), StdMeshers_SMESHBlock::Load(), myBlock, myErrorStatus, myShape, SMESHDS_SubMesh::NbElements(), SMDS_MeshElement::NbNodes(), and SMESHDS_Mesh::ShapeToIndex().
Referenced by Compute().
MakeConnectingMap()
void StdMeshers_Penta_3D::MakeConnectingMap () protected
References StdMeshers_TNode::BaseNodeID(), myConnectingMap, myJSize, and myTNodes.
Referenced by Compute().
MakeMeshOnFxy1()
void StdMeshers_Penta_3D::MakeMeshOnFxy1 () protected
References SMESH_MesherHelper::AddFace(), SMESH_subMesh::CHECK_COMPUTE_STATE, SMESH_subMesh::ComputeStateEngine(), SMESHDS_SubMesh::GetElements(), SMDS_MeshElement::GetID(), GetIndexOnLayer(), GetMesh(), SMESH_Mesh::GetMeshDS(), SMESHDS_SubMesh::GetNodes(), SMESH_Mesh::GetSubMesh(), SMESH_Mesh::GetSubMeshContaining(), SMESH_subMesh::GetSubMeshDS(), SMESH_MesherHelper::GetSubShape(), SMDS_MeshElement::GetType(), SMESH_Block::ID_Fxy0, SMESH_Block::ID_Fxy1, SMESH_MesherHelper::IsMedium(), SMESH_subMeshEventListenerData::MakeData(), myBlock, myCreateQuadratic, myErrorStatus, myISize, myJSize, myShape, myTNodes, myTool, SMDS_MeshElement::NbNodes(), SMESHDS_SubMesh::NbNodes(), StdMeshers_TNode::Node(), SMDS_MeshElement::nodesIterator(), SMESH_subMesh::SetEventListener(), SMESHDS_Mesh::SetMeshElementOnShape(), SMESH_MesherHelper::SetSubShape(), and StdMeshers_SMESHBlock::Shape().
Referenced by Compute().
MakeNodes()
void StdMeshers_Penta_3D::MakeNodes () protected
References StdMeshers_TNode::BaseNodeID(), StdMeshers_SMESHBlock::ComputeParameters(), CreateNode(), StdMeshers_SMESHBlock::ErrorStatus(), FindNodeOnShape(), StdMeshers_SMESHBlock::GetError(), SMDS_MeshElement::GetID(), GetMesh(), SMESH_Mesh::GetMeshDS(), SMESHDS_SubMesh::GetNodes(), SMESH_MesherHelper::GetNodeUV(), SMDS_MeshNode::GetPosition(), SMESH_Mesh::GetSubMeshContaining(), SMESH_subMesh::GetSubMeshDS(), SMDS_EdgePosition::GetUParameter(), SMESH_Block::ID_E00z, SMESH_Block::ID_E0y0, SMESH_Block::ID_E1y0, SMESH_Block::ID_Ex00, SMESH_Block::ID_Ex10, SMESH_Block::ID_F0yz, SMESH_Block::ID_F1yz, SMESH_Block::ID_Fx0z, SMESH_Block::ID_Fx1z, SMESH_Block::ID_Fxy0, SMESH_Block::ID_Fxy1, SMESH_Block::ID_NONE, SMESH_Block::ID_Shell, SMESH_Block::ID_V000, SMESH_Block::ID_V001, SMESH_Block::ID_V010, SMESH_Block::ID_V011, SMESH_Block::ID_V100, SMESH_Block::ID_V101, SMESH_Block::ID_V110, SMESH_Block::ID_V111, SMESH_Block::IsEdgeID(), SMESH_MesherHelper::IsMedium(), SMESH_Block::IsVertexID(), LoadIJNodes(), SMESHDS_Mesh::MeshElements(), myBlock, myCreateQuadratic, myErrorStatus, myISize, myJSize, myShapeXYZ, myTNodes, myTool, myWallNodesMaps, SMESHDS_SubMesh::NbNodes(), StdMeshers_TNode::Node(), StdMeshers_TNode::NormCoord(), StdMeshers_TNode::SetBaseNodeID(), SetHorizEdgeXYZ(), StdMeshers_TNode::SetNode(), SMESHDS_Mesh::SetNodeOnFace(), StdMeshers_TNode::SetNormCoord(), StdMeshers_TNode::SetShapeSupportID(), StdMeshers_SMESHBlock::Shape(), SMESH_Block::ShapeIndex(), StdMeshers_TNode::ShapeSupportID(), ShapeSupportID(), SMESHDS_Mesh::ShapeToIndex(), draftgeoutils.general::v1(), SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
Referenced by Compute().
MakeVolumeMesh()
void StdMeshers_Penta_3D::MakeVolumeMesh () protected
References SMESH_MesherHelper::AddVolume(), SMESHDS_SubMesh::GetElements(), SMDS_MeshElement::GetID(), GetIndexOnLayer(), GetMesh(), SMESH_Mesh::GetMeshDS(), SMDS_MeshElement::GetNode(), SMESH_Mesh::GetSubMeshContaining(), SMESH_subMesh::GetSubMeshDS(), SMESH_Block::ID_Fxy0, SMESH_Block::ID_NONE, SMDS_VolumeTool::IsForward(), myBlock, myCreateQuadratic, myErrorStatus, myISize, myJSize, myShape, myTNodes, myTool, SMDS_MeshElement::NbNodes(), StdMeshers_TNode::Node(), SMDS_VolumeTool::Set(), SMESHDS_Mesh::SetMeshElementOnShape(), SMESHDS_Mesh::SetNodeInVolume(), StdMeshers_SMESHBlock::Shape(), StdMeshers_TNode::ShapeSupportID(), and SMESHDS_Mesh::ShapeToIndex().
Referenced by Compute().
SetHorizEdgeXYZ()
double StdMeshers_Penta_3D::SetHorizEdgeXYZ (const gp_XYZ & aBNXYZ, const int aFaceID, std::vector< const SMDS_MeshNode * > *& aCol1, std::vector< const SMDS_MeshNode * > *& aCol2) protected
References StdMeshers_SMESHBlock::Block(), SMESH_Block::EdgePoint(), SMESH_Block::GetCoordIndOnEdge(), SMESH_Block::GetFaceEdgesIDs(), StdMeshers_SMESHBlock::IsForwadEdge(), myBlock, myShapeXYZ, myWallNodesMaps, draftguitools.gui_annotationstyleeditor::param, SMESH_Block::ShapeIndex(), SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
Referenced by MakeNodes().
SetMesh()
void StdMeshers_Penta_3D::SetMesh (SMESH_Mesh & theMesh) protected
Referenced by Compute().
SetTolerance()
void StdMeshers_Penta_3D::SetTolerance (const double theTol3D)
ShapeSupportID()
void StdMeshers_Penta_3D::ShapeSupportID (const bool theIsUpperLayer, const SMESH_Block::TShapeID theBNSSID, SMESH_Block::TShapeID & theSSID) protected
References SMESH_Block::ID_E00z, SMESH_Block::ID_E01z, SMESH_Block::ID_E0y0, SMESH_Block::ID_E0y1, SMESH_Block::ID_E10z, SMESH_Block::ID_E11z, SMESH_Block::ID_E1y0, SMESH_Block::ID_E1y1, SMESH_Block::ID_Ex00, SMESH_Block::ID_Ex01, SMESH_Block::ID_Ex10, SMESH_Block::ID_Ex11, SMESH_Block::ID_F0yz, SMESH_Block::ID_F1yz, SMESH_Block::ID_Fx0z, SMESH_Block::ID_Fx1z, SMESH_Block::ID_Fxy0, SMESH_Block::ID_NONE, SMESH_Block::ID_V000, SMESH_Block::ID_V001, SMESH_Block::ID_V010, SMESH_Block::ID_V011, SMESH_Block::ID_V100, SMESH_Block::ID_V101, SMESH_Block::ID_V110, SMESH_Block::ID_V111, and myErrorStatus.
Referenced by MakeNodes().
Tolerance()
double StdMeshers_Penta_3D::Tolerance () const
Member Data Documentation
myBlock
StdMeshers_SMESHBlock StdMeshers_Penta_3D::myBlock protected
Referenced by ClearMeshOnFxy1(), FindNodeOnShape(), MakeBlock(), MakeMeshOnFxy1(), MakeNodes(), MakeVolumeMesh(), and SetHorizEdgeXYZ().
myConnectingMap
std::map< int, int > StdMeshers_Penta_3D::myConnectingMap protected
Referenced by GetIndexOnLayer(), and MakeConnectingMap().
myCreateQuadratic
bool StdMeshers_Penta_3D::myCreateQuadratic protected
Referenced by Compute(), LoadIJNodes(), MakeMeshOnFxy1(), MakeNodes(), and MakeVolumeMesh().
myErrorStatus
SMESH_ComputeErrorPtr StdMeshers_Penta_3D::myErrorStatus protected
Referenced by CheckData(), Compute(), Evaluate(), GetIndexOnLayer(), MakeBlock(), MakeMeshOnFxy1(), MakeNodes(), MakeVolumeMesh(), and ShapeSupportID().
myISize
int StdMeshers_Penta_3D::myISize protected
Referenced by MakeMeshOnFxy1(), MakeNodes(), and MakeVolumeMesh().
myJSize
int StdMeshers_Penta_3D::myJSize protected
Referenced by MakeConnectingMap(), MakeMeshOnFxy1(), MakeNodes(), and MakeVolumeMesh().
myMesh
void* StdMeshers_Penta_3D::myMesh protected
myShape
TopoDS_Shape StdMeshers_Penta_3D::myShape protected
Referenced by CheckData(), Compute(), MakeBlock(), MakeMeshOnFxy1(), and MakeVolumeMesh().
myShapeXYZ
std::vector<gp_XYZ> StdMeshers_Penta_3D::myShapeXYZ protected
Referenced by CreateNode(), MakeNodes(), SetHorizEdgeXYZ(), and StdMeshers_Penta_3D().
myTNodes
std::vector<StdMeshers_TNode> StdMeshers_Penta_3D::myTNodes protected
Referenced by MakeConnectingMap(), MakeMeshOnFxy1(), MakeNodes(), and MakeVolumeMesh().
myTol3D
double StdMeshers_Penta_3D::myTol3D protected
Referenced by FindNodeOnShape(), and StdMeshers_Penta_3D().
myTool
SMESH_MesherHelper* StdMeshers_Penta_3D::myTool protected
Referenced by Compute(), FindNodeOnShape(), LoadIJNodes(), MakeMeshOnFxy1(), MakeNodes(), MakeVolumeMesh(), and StdMeshers_Penta_3D().
myWallNodesMaps
std::vector<StdMeshers_IJNodeMap> StdMeshers_Penta_3D::myWallNodesMaps protected
Referenced by FindNodeOnShape(), MakeNodes(), SetHorizEdgeXYZ(), and StdMeshers_Penta_3D().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_Penta_3D.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_Penta_3D.cpp