FreeCAD: FemGui::ViewProviderFemAnalysis Class Reference
FemGui::ViewProviderFemAnalysis Class Reference
#include <ViewProviderAnalysis.h>
Public Member Functions
virtual bool canDelete (App::DocumentObject *obj) const
Asks the view provider if the given object can be deleted.
virtual std::vector< App::DocumentObject * > claimChildren (void) const
deliver the children belonging to this object this method is used to deliver the objects to the tree framework which should be grouped under its label.
virtual bool doubleClicked (void)
is called by the tree if the user double clicks on the object
virtual std::vector< std::string > getDisplayModes (void) const
A list of all possible display modes.
virtual void hide (void)
Hide the object in the view.
virtual bool isShow (void) const
checks whether the view provider is visible or not
virtual bool onDelete (const std::vector< std::string > &)
Get called if the object is about to get deleted.
void setupContextMenu (QMenu *, QObject *, const char *)
set up the context-menu with the supported edit modes
virtual void show (void)
Show the object in the view.
ViewProviderFemAnalysis ()
constructor.
virtual ~ViewProviderFemAnalysis ()
destructor.
Public Member Functions inherited from Gui::ViewProviderDocumentObjectGroup
virtual QIcon getIcon (void) const override
deliver the icon shown in the tree view
ViewProviderDocumentObjectGroup ()
constructor.
virtual ~ViewProviderDocumentObjectGroup ()
destructor.
Public Member Functions inherited from Gui::ViewProviderDocumentObject
virtual void attach (App::DocumentObject *pcObject)
virtual bool canDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const override
Query object dropping with full qualified name.
virtual void forceUpdate (bool enable=true)
virtual bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const override
return the coin node detail and path to the node of the subname
Gui::Document * getDocument () const
Get the GUI document to this ViewProvider object.
virtual bool getElementPicked (const SoPickedPoint *, std::string &subname) const override
return a hit element given the picked point which contains the full node path
App::DocumentObject * getObject (void) const
Get the object of this ViewProvider object.
PyObject * getPyObject () override
Get the python wrapper for that ViewProvider.
virtual void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const override
Get a list of TaskBoxes associated with this object.
virtual const char * getTransactionText () const override
Is called by the tree if the user double clicks on the object.
virtual bool isUpdateForced () const
virtual void reattach (App::DocumentObject *)
virtual int replaceObject (App::DocumentObject *, App::DocumentObject *) override
Replace an object to the view provider by drag and drop.
void setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
virtual bool showInTree () const override
Tell the tree view if this object should appear there.
virtual void update (const App::Property *) override
update the content of the ViewProvider this method have to implement the recalculation of the ViewProvider.
void updateView ()
Run a redraw.
ViewProviderDocumentObject ()
constructor.
virtual ~ViewProviderDocumentObject ()
destructor.
virtual void startRestoring ()
virtual void finishRestoring ()
virtual bool removeDynamicProperty (const char *prop) override
virtual App::Property * addDynamicProperty (const char *type, const char *name=0, const char *group=0, const char *doc=0, short attr=0, bool ro=false, bool hidden=false) override
virtual ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=0, bool recursive=false) const
Return the linked view object.
virtual std::string getFullName () const override
virtual bool allowOverride (const App::DocumentObject &) const
Allow this class to be used as an override for the original view provider of the given object.
void setShowable (bool enable)
bool isShowable () const
Public Member Functions inherited from Gui::ViewProvider
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual std::vector< App::DocumentObject * > claimChildren3D (void) const
deliver the children belonging to this object this method is used to deliver the objects to the 3DView which should be grouped under its scene graph.
SoSeparator * getAnnotation (void)
virtual SoSeparator * getBackRoot (void) const
virtual SoGroup * getChildRoot (void) const
virtual SoSeparator * getFrontRoot (void) const
SoSwitch * getModeSwitch (void) const
virtual SoSeparator * getRoot (void) const
SoTransform * getTransformNode () const
ViewProvider ()
constructor.
virtual ~ViewProvider ()
destructor.
virtual bool useNewSelectionModel (void) const
indicates if the ViewProvider use the new Selection model
virtual bool isSelectable (void) const
virtual std::string getElement (const SoDetail *) const
return a hit element to the selection path or 0
virtual SoDetail * getDetail (const char *) const
return the coin node detail of the subelement
int partialRender (const std::vector< std::string > &subelements, bool clear)
partial rendering setup
virtual std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const
virtual std::vector< Base::Vector3d > getSelectionShape (const char *Element) const
return the highlight lines for a given element or the whole shape
Base::BoundBox3d getBoundingBox (const char *subname=0, bool transform=true, MDIView *view=0) const
Return the bound box of this view object.
virtual void beforeDelete ()
Called before deletion.
virtual bool canDragAndDropObject (App::DocumentObject *) const
Return false to force drop only operation for a given object.
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
Add an object with full qualified name to the view provider by drag and drop.
virtual bool canRemoveChildrenFromRoot () const
Tell the tree view to remove children items from the tree root.
std::string getActiveDisplayMode (void) const
virtual void setDisplayMode (const char *ModeName)
set the display mode
virtual const char * getDefaultDisplayMode () const
get the default display mode
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
virtual void setOverrideMode (const std::string &mode)
Overrides the display mode with mode.
const std::string getOverrideMode ()
virtual bool keyPressed (bool pressed, int key)
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
virtual bool mouseMove (const SbVec2s &cursorPos, View3DInventorViewer *viewer)
is called when the provider is in edit and the mouse is moved
virtual bool mouseButtonPressed (int button, bool pressed, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
is called when the Provider is in edit and the mouse is clicked
virtual ViewProvider * startEditing (int ModNum=0)
bool isEditing () const
void finishEditing ()
virtual void setEditViewer (View3DInventorViewer *, int ModNum)
adjust viewer settings when editing a view provider
virtual void unsetEditViewer (View3DInventorViewer *)
restores viewer settings when leaving editing mode
virtual void updateData (const App::Property *)
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
virtual std::map< std::string, App::Color > getElementColors (const char *element=0) const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
virtual MDIView * getMDIView () const
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
TransactionalObject (void)
Constructor.
virtual ~TransactionalObject ()
Public Member Functions inherited from App::ExtensionContainer
ExtensionIterator extensionBegin ()
ExtensionContainer ()
ExtensionIterator extensionEnd ()
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
void registerExtension (Base::Type extension, App::Extension *ext)
virtual ~ExtensionContainer ()
virtual Property * getPropertyByName (const char *name) const override
find a property by its name
virtual const char * getPropertyName (const Property *prop) const override
get the name of a property
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
virtual void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
virtual short getPropertyType (const Property *prop) const override
get the Type of a Property
virtual short getPropertyType (const char *name) const override
get the Type of a named Property
virtual const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
Public Member Functions inherited from App::PropertyContainer
virtual App::Property * getDynamicPropertyByName (const char *name) const
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
const char * getPropertyPrefix () const
bool isHidden (const char *name) const
check if the named property is hidden
bool isHidden (const Property *prop) const
check if the property is hidden
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isReadOnly (const Property *prop) const
check if the property is read-only
PropertyContainer ()
A constructor.
void setPropertyPrefix (const char *prefix)
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
virtual ~PropertyContainer ()
A destructor.
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Gui::ViewProviderGroupExtension
virtual bool extensionCanDragObject (App::DocumentObject *) const override
virtual bool extensionCanDragObjects () const override
virtual bool extensionCanDropObject (App::DocumentObject *) const override
virtual bool extensionCanDropObjects () const override
virtual std::vector< App::DocumentObject * > extensionClaimChildren (void) const override
virtual void extensionDragObject (App::DocumentObject *) override
virtual void extensionDropObject (App::DocumentObject *) override
virtual void extensionHide (void) override
Hides the view provider.
virtual bool extensionOnDelete (const std::vector< std::string > &) override
virtual void extensionShow (void) override
Shows the view provider.
ViewProviderGroupExtension (void)
Constructor.
virtual ~ViewProviderGroupExtension ()
Public Member Functions inherited from Gui::ViewProviderExtension
virtual void extensionAttach (App::DocumentObject *)
virtual void extensionBeforeDelete ()
virtual bool extensionCanDragAndDropObject (App::DocumentObject *) const
virtual bool extensionCanDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const
virtual std::vector< App::DocumentObject * > extensionClaimChildren3D (void) const
virtual std::string extensionDropObjectEx (App::DocumentObject *obj, App::DocumentObject *, const char *, const std::vector< std::string > &)
virtual void extensionFinishRestoring ()
virtual SoSeparator * extensionGetBackRoot (void) const
virtual SoGroup * extensionGetChildRoot (void) const
virtual bool extensionGetDetailPath (const char *, SoFullPath *, SoDetail *&) const
virtual std::vector< std::string > extensionGetDisplayModes (void) const
virtual bool extensionGetElementPicked (const SoPickedPoint *, std::string &) const
virtual SoSeparator * extensionGetFrontRoot (void) const
virtual QIcon extensionMergeOverlayIcons (const QIcon &orig) const
virtual void extensionModeSwitchChange (void)
virtual void extensionReattach (App::DocumentObject *)
virtual int extensionReplaceObject (App::DocumentObject *, App::DocumentObject *)
virtual void extensionSetDisplayMode (const char *)
virtual void extensionSetupContextMenu (QMenu *, QObject *, const char *)
virtual void extensionStartRestoring ()
virtual void extensionUpdateData (const App::Property *)
Gui::ViewProviderDocumentObject * getExtendedViewProvider ()
const Gui::ViewProviderDocumentObject * getExtendedViewProvider () const
virtual PyObject * getExtensionPyObject ()
bool ignoreOverlayIcon () const
void setIgnoreOverlayIcon (bool on)
ViewProviderExtension ()
virtual ~ViewProviderExtension ()
Public Member Functions inherited from App::Extension
Extension ()
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
virtual void initExtension (App::ExtensionContainer *obj)
bool isPythonExtension ()
std::string name () const
virtual ~Extension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Drag and drop
bool canDragObjects () const
Returns true if the view provider generally supports dragging objects.
bool canDragObject (App::DocumentObject *) const
Check whether the object can be removed from the view provider by drag and drop.
void dragObject (App::DocumentObject *)
Starts to drag the object.
bool canDropObjects () const
Returns true if the view provider generally accepts dropping of objects.
bool canDropObject (App::DocumentObject *) const
Check whether the object can be dropped to the view provider by drag and drop.
void dropObject (App::DocumentObject *)
If the dropped object type is accepted the object will be added as child.
virtual bool setEdit (int ModNum)
is called by the document when the provider goes in edit mode
virtual void unsetEdit (int ModNum)
is called when you lose the edit mode
Additional Inherited Members
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0, Transform, Cutting, Color }
Public Types inherited from App::ExtensionContainer
typedef std::map< Base::Type, App::Extension * >::iterator ExtensionIterator
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Public Attributes inherited from Gui::ViewProviderDocumentObject
App::PropertyEnumeration DisplayMode
App::PropertyEnumeration OnTopWhenSelected
App::PropertyEnumeration SelectionStyle
App::PropertyBool ShowInTree
App::PropertyBool Visibility
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
Protected Member Functions inherited from Gui::ViewProviderDocumentObjectGroup
void getViewProviders (std::vector< ViewProviderDocumentObject * > &) const
Extracts the associated view providers of the objects of the associated object group group.
Protected Member Functions inherited from Gui::ViewProviderDocumentObject
virtual bool isAttachedToDocument () const override
virtual const char * detachFromDocument () override
virtual void onPropertyStatusChanged (const App::Property &prop, unsigned long oldStatus) override
get called when a property status has changed
virtual void setModeSwitch () override
Turn on mode switch.
Gui::MDIView * getActiveView () const
Gui::MDIView * getEditingView () const
Gui::MDIView * getInventorView () const
Gui::MDIView * getViewOfNode (SoNode *node) const
virtual void onBeforeChange (const App::Property *prop) override
get called before the value is changed
virtual void onChanged (const App::Property *prop) override
Gets called by the container whenever a property has been changed.
SoNode * findFrontRootOfType (const SoType &type) const
Searches in all view providers that are attached to an object that is part of the same document as the object this view provider is attached to for an front root of type.
Protected Member Functions inherited from Gui::ViewProvider
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
virtual QIcon mergeOverlayIcons (const QIcon &orig) const
bool checkRecursion (SoNode *)
Helper method to check that the node is valid, i.e.
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
Helper method to get picked entities while editing.
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
Helper method to get picked entities while editing.
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData (void) const
virtual void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container.
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
Protected Member Functions inherited from App::Extension
virtual void extensionOnChanged (const Property *p)
void initExtensionType (Base::Type type)
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Static Protected Member Functions inherited from App::Extension
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=0)
Protected Attributes inherited from Gui::ViewProviderDocumentObject
App::DocumentObject * pcObject
Gui::Document * pcDocument
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation
The root separator for annotations.
ViewProviderPy * pyViewObject
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::Object ExtensionPythonObject
Constructor & Destructor Documentation
ViewProviderFemAnalysis()
ViewProviderFemAnalysis::ViewProviderFemAnalysis ()
constructor.
~ViewProviderFemAnalysis()
ViewProviderFemAnalysis::~ViewProviderFemAnalysis () virtual
destructor.
Member Function Documentation
canDelete()
bool ViewProviderFemAnalysis::canDelete (App::DocumentObject * obj) const virtual
Asks the view provider if the given object can be deleted.
Reimplemented from Gui::ViewProviderDocumentObject.
canDragObject()
bool ViewProviderFemAnalysis::canDragObject (App::DocumentObject * obj) const virtual
Check whether the object can be removed from the view provider by drag and drop.
Reimplemented from Gui::ViewProvider.
References Base::Type::fromName(), and Base::Persistence::getClassTypeId().
Referenced by canDropObject().
canDragObjects()
bool ViewProviderFemAnalysis::canDragObjects () const virtual
Returns true if the view provider generally supports dragging objects.
Reimplemented from Gui::ViewProvider.
canDropObject()
bool ViewProviderFemAnalysis::canDropObject (App::DocumentObject * obj) const virtual
Check whether the object can be dropped to the view provider by drag and drop.
Reimplemented from Gui::ViewProvider.
References canDragObject().
canDropObjects()
bool ViewProviderFemAnalysis::canDropObjects () const virtual
Returns true if the view provider generally accepts dropping of objects.
Reimplemented from Gui::ViewProvider.
claimChildren()
std::vector< App::DocumentObject * > ViewProviderFemAnalysis::claimChildren (void) const virtual
deliver the children belonging to this object this method is used to deliver the objects to the tree framework which should be grouped under its label.
Obvious is the usage in the group but it can be used for any kind of grouping needed for a special purpose.
Reimplemented from Gui::ViewProvider.
References Gui::ViewProvider::claimChildren().
Referenced by BOPTools.JoinFeatures.ViewProviderConnect::onDelete(), BOPTools.SplitFeatures.ViewProviderBooleanFragments::onDelete(), BOPTools.SplitFeatures.ViewProviderSlice::onDelete(), and BOPTools.SplitFeatures.ViewProviderXOR::onDelete().
doubleClicked()
bool ViewProviderFemAnalysis::doubleClicked (void) virtual
is called by the tree if the user double clicks on the object
Reimplemented from Gui::ViewProvider.
References Gui::Command::addModule(), Gui::ViewProviderDocumentObject::getObject(), and Gui::Command::Gui.
Referenced by setupContextMenu().
dragObject()
void ViewProviderFemAnalysis::dragObject (App::DocumentObject * obj) virtual
Starts to drag the object.
Reimplemented from Gui::ViewProvider.
dropObject()
void ViewProviderFemAnalysis::dropObject (App::DocumentObject * obj) virtual
If the dropped object type is accepted the object will be added as child.
Reimplemented from Gui::ViewProvider.
getDisplayModes()
std::vector< std::string > ViewProviderFemAnalysis::getDisplayModes (void) const virtual
A list of all possible display modes.
Reimplemented from Gui::ViewProviderDocumentObjectGroup.
hide()
void ViewProviderFemAnalysis::hide (void) virtual
Hide the object in the view.
Reimplemented from Gui::ViewProviderDocumentObject.
References Gui::ViewProviderDocumentObject::hide().
Referenced by Mod.Show.mTempoVis.TempoVis::hide_all_dependencies(), and Mod.Show.mTempoVis.TempoVis::hide_all_dependent().
isShow()
virtual bool FemGui::ViewProviderFemAnalysis::isShow (void) const virtual
checks whether the view provider is visible or not
Reimplemented from Gui::ViewProviderDocumentObjectGroup.
onDelete()
bool ViewProviderFemAnalysis::onDelete (const std::vector< std::string > & subNames) virtual
Get called if the object is about to get deleted.
Here you can delete other objects, switch their visibility or prevent the deletion of the object.
Parameters
subNames list of selected subelements
Returns
true if the deletion is approved by the view provider.
Reimplemented from Gui::ViewProvider.
setEdit()
bool ViewProviderFemAnalysis::setEdit (int ModNum) protected virtual
is called by the document when the provider goes in edit mode
Reimplemented from Gui::ViewProvider.
References Gui::ViewProvider::setEdit().
Referenced by draftviewproviders.view_dimension.ViewProviderDimensionBase::doubleClicked(), PathScripts.PathSetupSheetGui.ViewProvider::doubleClicked(), PathScripts.PathToolBitGui.ViewProvider::doubleClicked(), Spreadsheet_legacy.ViewProviderSpreadsheet::doubleClicked(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), PathScripts.PathIconViewProvider.ViewProvider::setupContextMenu(), PathScripts.PathJobGui.ViewProvider::setupContextMenu(), PathScripts.PathOpGui.ViewProvider::setupContextMenu(), and PathScripts.PathToolControllerGui.ViewProvider::setupContextMenu().
setupContextMenu()
void ViewProviderFemAnalysis::setupContextMenu (QMenu * menu, QObject * receiver, const char * method) virtual
set up the context-menu with the supported edit modes
Reimplemented from Gui::ViewProvider.
References draftgeoutils.faces::bind(), and doubleClicked().
show()
void ViewProviderFemAnalysis::show (void) virtual
Show the object in the view.
Reimplemented from Gui::ViewProviderDocumentObject.
References Gui::ViewProviderDocumentObject::show().
Referenced by Mod.Show.mTempoVis.TempoVis::show_all_dependencies(), and Mod.Show.mTempoVis.TempoVis::show_all_dependent().
unsetEdit()
void ViewProviderFemAnalysis::unsetEdit (int ModNum) protected virtual
is called when you lose the edit mode
Reimplemented from Gui::ViewProvider.
References Gui::ControlSingleton::closeDialog(), Gui::Control(), and Gui::ViewProvider::unsetEdit().
Referenced by PathScripts.PathJobGui.ViewProvider::uneditObject().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Fem/Gui/ViewProviderAnalysis.h
Sources/FreeCAD/src/Mod/Fem/Gui/ViewProviderAnalysis.cpp