FreeCAD: Inspection::InspectActualGeometry Class Reference
Inspection::InspectActualGeometry Class Reference abstract
Delivers the number of points to be checked and returns the appropriate point to an index.
#include <InspectionFeature.h>
Public Member Functions
virtual unsigned long countPoints () const =0
Number of points to be checked.
virtual Base::Vector3f getPoint (unsigned long) const =0
InspectActualGeometry ()
virtual ~InspectActualGeometry ()
Detailed Description
Delivers the number of points to be checked and returns the appropriate point to an index.
Constructor & Destructor Documentation
InspectActualGeometry()
Inspection::InspectActualGeometry::InspectActualGeometry ()
~InspectActualGeometry()
virtual Inspection::InspectActualGeometry::~InspectActualGeometry () virtual
Member Function Documentation
countPoints()
virtual unsigned long Inspection::InspectActualGeometry::countPoints () const pure virtual
Number of points to be checked.
Implemented in Inspection::InspectActualMesh, Inspection::InspectActualPoints, and Inspection::InspectActualShape.
Referenced by Inspection::Feature::execute().
getPoint()
virtual Base::Vector3f Inspection::InspectActualGeometry::getPoint (unsigned long) const pure virtual
Implemented in Inspection::InspectActualMesh, Inspection::InspectActualPoints, and Inspection::InspectActualShape.
Referenced by ArchStructure.CommandStructuralSystem::Activated(), PathScripts.PathOpGui.TaskPanelBaseLocationPage::addLocation(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::addNewTag(), PathScripts.PathOpGui.TaskPanelBaseLocationPage::editLocation(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::editTag(), Inspection::Feature::execute(), draftguitools.gui_arcs.Arc_3Points::getPoint(), ArchCurtainWall.CommandArchCurtainWall::getPoint(), ArchTruss.CommandArchTruss::getPoint(), Inspection::DistanceInspection::mapped(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::modifyStandardButtons(), and PathScripts.PathOpGui.TaskPanelBaseLocationPage::modifyStandardButtons().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Inspection/App/InspectionFeature.h