FreeCAD: PartGui::TaskExtrusion Class Reference
PartGui::TaskExtrusion Class Reference
#include <DlgExtrusion.h>
Public Member Functions
bool accept ()
is called by the framework if the dialog is accepted (Ok)
void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual QDialogButtonBox::StandardButtons getStandardButtons () const
tells the framework which buttons are wished for the dialog
bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskExtrusion ()
~TaskExtrusion ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
ButtonPosition buttonPosition () const
bool canClose () const
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Constructor & Destructor Documentation
TaskExtrusion()
TaskExtrusion::TaskExtrusion ()
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
~TaskExtrusion()
TaskExtrusion::~TaskExtrusion ()
Member Function Documentation
accept()
bool TaskExtrusion::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References PartGui::DlgExtrusion::accept().
Referenced by PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
clicked()
void TaskExtrusion::clicked (int) virtual
is called by the framework if a button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
References PartGui::DlgExtrusion::apply().
getStandardButtons()
virtual QDialogButtonBox::StandardButtons PartGui::TaskExtrusion::getStandardButtons (void) const virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
reject()
bool TaskExtrusion::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References PartGui::DlgExtrusion::reject().
Referenced by PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/Gui/DlgExtrusion.h
Sources/FreeCAD/src/Mod/Part/Gui/DlgExtrusion.cpp