FreeCAD: App::GroupExtensionPy Class Reference
App::GroupExtensionPy Class Reference
The python export class for GroupExtension.
#include <GroupExtensionPy.h>
Public Types
typedef GroupExtension * PointerType
Public Types inherited from App::DocumentObjectExtensionPy
typedef DocumentObjectExtension * PointerType
Public Types inherited from App::ExtensionPy
typedef Extension * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
GroupExtensionPy (GroupExtension *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GroupExtension * getGroupExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from App::DocumentObjectExtensionPy
DocumentObjectExtensionPy (DocumentObjectExtension *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
DocumentObjectExtension * getDocumentObjectExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from App::ExtensionPy
ExtensionPy (Extension *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Extension * getExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::DocumentObjectExtensionPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::ExtensionPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of GroupExtensionPy.
static PyMethodDef Methods []
Methods structure of GroupExtensionPy.
static PyTypeObject Type
Type structure of GroupExtensionPy.
Static Public Attributes inherited from App::DocumentObjectExtensionPy
static PyGetSetDef GetterSetter []
Attribute structure of DocumentObjectExtensionPy.
static PyMethodDef Methods []
Methods structure of DocumentObjectExtensionPy.
static PyTypeObject Type
Type structure of DocumentObjectExtensionPy.
Static Public Attributes inherited from App::ExtensionPy
static PyGetSetDef GetterSetter []
Attribute structure of ExtensionPy.
static PyMethodDef Methods []
Methods structure of ExtensionPy.
static PyTypeObject Type
Type structure of ExtensionPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~GroupExtensionPy ()
Protected Member Functions inherited from App::DocumentObjectExtensionPy
~DocumentObjectExtensionPy ()
Protected Member Functions inherited from App::ExtensionPy
~ExtensionPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * newObject (PyObject *args)
implementer for the newObject() method
PyObject * addObject (PyObject *args)
implementer for the addObject() method
PyObject * addObjects (PyObject *args)
implementer for the addObjects() method
PyObject * setObjects (PyObject *args)
implementer for the setObjects() method
PyObject * removeObject (PyObject *args)
implementer for the removeObject() method
PyObject * removeObjects (PyObject *args)
implementer for the removeObjects() method
PyObject * removeObjectsFromDocument (PyObject *args)
implementer for the removeObjectsFromDocument() method
PyObject * getObject (PyObject *args)
implementer for the getObject() method
PyObject * hasObject (PyObject *args)
implementer for the hasObject() method
static PyObject * staticCallback_newObject (PyObject *self, PyObject *args)
callback for the newObject() method
static PyObject * staticCallback_addObject (PyObject *self, PyObject *args)
callback for the addObject() method
static PyObject * staticCallback_addObjects (PyObject *self, PyObject *args)
callback for the addObjects() method
static PyObject * staticCallback_setObjects (PyObject *self, PyObject *args)
callback for the setObjects() method
static PyObject * staticCallback_removeObject (PyObject *self, PyObject *args)
callback for the removeObject() method
static PyObject * staticCallback_removeObjects (PyObject *self, PyObject *args)
callback for the removeObjects() method
static PyObject * staticCallback_removeObjectsFromDocument (PyObject *self, PyObject *args)
callback for the removeObjectsFromDocument() method
static PyObject * staticCallback_getObject (PyObject *self, PyObject *args)
callback for the getObject() method
static PyObject * staticCallback_hasObject (PyObject *self, PyObject *args)
callback for the hasObject() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GroupExtension.
Member Typedef Documentation
PointerType
typedef GroupExtension* App::GroupExtensionPy::PointerType
Constructor & Destructor Documentation
~GroupExtensionPy()
GroupExtensionPy::~GroupExtensionPy () protected
GroupExtensionPy()
GroupExtensionPy::GroupExtensionPy (GroupExtension * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
addObject()
PyObject * GroupExtensionPy::addObject (PyObject * args)
implementer for the addObject() method
References Base::BaseExceptionFreeCADError, App::DocumentObject::getDocument(), App::DocumentObjectPy::getDocumentObjectPtr(), App::ExtensionContainer::getExtensionByType(), getGroupExtensionPtr(), App::DocumentObject::getNameInDocument(), App::ExtensionContainer::hasExtension(), App::GroupExtension::hasObject(), App::DocumentObjectPy::Type, and draftgeoutils.general::vec().
Referenced by ArchPanel.NestTaskPanel::getContainer(), ArchPanel.NestTaskPanel::getShapes(), and staticCallback_addObject().
addObjects()
PyObject * GroupExtensionPy::addObjects (PyObject * args)
implementer for the addObjects() method
References App::DocumentObjectPy::getDocumentObjectPtr(), getGroupExtensionPtr(), App::DocumentObjectPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_addObjects().
getCustomAttributes()
PyObject * GroupExtensionPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getGroupExtensionPtr()
GroupExtension * GroupExtensionPy::getGroupExtensionPtr (void) const
getter for the object handled by this class
Referenced by addObject(), addObjects(), getObject(), hasObject(), newObject(), removeObject(), removeObjects(), removeObjectsFromDocument(), and setObjects().
getObject()
PyObject * GroupExtensionPy::getObject (PyObject * args)
implementer for the getObject() method
References getGroupExtensionPtr(), App::GroupExtension::getObject(), and App::DocumentObject::getPyObject().
Referenced by staticCallback_getObject().
GetType()
virtual PyTypeObject* App::GroupExtensionPy::GetType (void) virtual
Reimplemented from App::DocumentObjectExtensionPy.
Reimplemented in App::OriginGroupExtensionPy, and App::GeoFeatureGroupExtensionPy.
hasObject()
PyObject * GroupExtensionPy::hasObject (PyObject * args)
implementer for the hasObject() method
References Base::BaseExceptionFreeCADError, App::DocumentObject::getDocument(), App::DocumentObjectPy::getDocumentObjectPtr(), getGroupExtensionPtr(), App::DocumentObject::getNameInDocument(), App::GroupExtension::hasObject(), and App::DocumentObjectPy::Type.
Referenced by staticCallback_hasObject().
newObject()
PyObject * GroupExtensionPy::newObject (PyObject * args)
implementer for the newObject() method
References App::GroupExtension::addObject(), Base::BaseExceptionFreeCADError, getGroupExtensionPtr(), and App::DocumentObject::getPyObject().
Referenced by staticCallback_newObject().
PyInit()
int GroupExtensionPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from App::DocumentObjectExtensionPy.
Reimplemented in App::OriginGroupExtensionPy, and App::GeoFeatureGroupExtensionPy.
PyMake()
PyObject * GroupExtensionPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
removeObject()
PyObject * GroupExtensionPy::removeObject (PyObject * args)
implementer for the removeObject() method
References Base::BaseExceptionFreeCADError, App::DocumentObject::getDocument(), App::DocumentObjectPy::getDocumentObjectPtr(), getGroupExtensionPtr(), App::DocumentObject::getNameInDocument(), App::DocumentObjectPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_removeObject().
removeObjects()
PyObject * GroupExtensionPy::removeObjects (PyObject * args)
implementer for the removeObjects() method
References App::DocumentObjectPy::getDocumentObjectPtr(), getGroupExtensionPtr(), App::DocumentObjectPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_removeObjects().
removeObjectsFromDocument()
PyObject * GroupExtensionPy::removeObjectsFromDocument (PyObject * args)
implementer for the removeObjectsFromDocument() method
References getGroupExtensionPtr(), and App::GroupExtension::removeObjectsFromDocument().
Referenced by staticCallback_removeObjectsFromDocument().
representation()
std::string GroupExtensionPy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int GroupExtensionPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setObjects()
PyObject * GroupExtensionPy::setObjects (PyObject * args)
implementer for the setObjects() method
References App::DocumentObjectPy::getDocumentObjectPtr(), getGroupExtensionPtr(), App::DocumentObjectPy::Type, and draftgeoutils.general::vec().
Referenced by staticCallback_setObjects().
staticCallback_addObject()
PyObject * GroupExtensionPy::staticCallback_addObject (PyObject * self, PyObject * args) static
callback for the addObject() method
References addObject(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addObjects()
PyObject * GroupExtensionPy::staticCallback_addObjects (PyObject * self, PyObject * args) static
callback for the addObjects() method
References addObjects(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getObject()
PyObject * GroupExtensionPy::staticCallback_getObject (PyObject * self, PyObject * args) static
callback for the getObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getObject(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_hasObject()
PyObject * GroupExtensionPy::staticCallback_hasObject (PyObject * self, PyObject * args) static
callback for the hasObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hasObject(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_newObject()
PyObject * GroupExtensionPy::staticCallback_newObject (PyObject * self, PyObject * args) static
callback for the newObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), newObject(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_removeObject()
PyObject * GroupExtensionPy::staticCallback_removeObject (PyObject * self, PyObject * args) static
callback for the removeObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeObject(), and Base::PyObjectBase::startNotify().
staticCallback_removeObjects()
PyObject * GroupExtensionPy::staticCallback_removeObjects (PyObject * self, PyObject * args) static
callback for the removeObjects() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeObjects(), and Base::PyObjectBase::startNotify().
staticCallback_removeObjectsFromDocument()
PyObject * GroupExtensionPy::staticCallback_removeObjectsFromDocument (PyObject * self, PyObject * args) static
callback for the removeObjectsFromDocument() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeObjectsFromDocument(), and Base::PyObjectBase::startNotify().
staticCallback_setObjects()
PyObject * GroupExtensionPy::staticCallback_setObjects (PyObject * self, PyObject * args) static
callback for the setObjects() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setObjects(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef GroupExtensionPy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of GroupExtensionPy.
Methods
PyMethodDef GroupExtensionPy::Methods static
Methods structure of GroupExtensionPy.
Type
PyTypeObject GroupExtensionPy::Type static
Type structure of GroupExtensionPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/App/GroupExtensionPy.h
Sources/FreeCAD/src/App/GroupExtensionPyImp.cpp
Sources/FreeCAD-SourceDocs/src/App/GroupExtensionPy.cpp