FreeCAD: Gui::Application Class Reference
Gui::Application Class Reference
The Application main class This is the central class of the GUI.
#include <Application.h>
Public Member Functions
Application (bool GUIenabled)
construction
~Application ()
destruction
methods for support of files
void open (const char *FileName, const char *Module)
open a file
void importFrom (const char *FileName, const char *DocName, const char *Module)
import a file into the document DocName
void exportTo (const char *FileName, const char *DocName, const char *Module)
Export objects from the document DocName to a single file.
App::Document * reopen (App::Document *doc)
Reload a partial opened document.
methods for View handling
bool sendMsgToActiveView (const char *pMsg, const char **ppReturn=0)
send Messages to the active view
bool sendHasMsgToActiveView (const char *pMsg)
send Messages test to the active view
bool sendMsgToFocusView (const char *pMsg, const char **ppReturn=0)
send Messages to the focused view
bool sendHasMsgToFocusView (const char *pMsg)
send Messages test to the focused view
void attachView (Gui::BaseView *pcView)
Attach a view (get called by the FCView constructor)
void detachView (Gui::BaseView *pcView)
Detach a view (get called by the FCView destructor)
void viewActivated (Gui::MDIView *pcView)
get called if a view gets activated, this manage the whole activation scheme
void onUpdate (void)
call update to all documents and all views (costly!)
void updateActive (void)
call update to all views of the active document
workbench handling
bool activateWorkbench (const char *name)
Activate a named workbench.
QPixmap workbenchIcon (const QString &) const
QString workbenchToolTip (const QString &) const
QString workbenchMenuText (const QString &) const
QStringList workbenches (void) const
void setupContextMenu (const char *recipient, MenuItem *) const
Appearance
void setStyleSheet (const QString &qssFile, bool tiledBackground)
Activate a named workbench.
User Commands
Gui::MacroManager * macroManager (void)
Get macro manager.
Gui::CommandManager & commandManager (void)
Reference to the command manager.
void createStandardOperations ()
helper which create the commands
Public Attributes
Signals of the Application
boost::signals2::signal< void(const Gui::Document &, bool)> signalNewDocument
signal on new Document
boost::signals2::signal< void(const Gui::Document &)> signalDeleteDocument
signal on deleted Document
boost::signals2::signal< void(const Gui::Document &)> signalRelabelDocument
signal on relabeling Document
boost::signals2::signal< void(const Gui::Document &)> signalRenameDocument
signal on renaming Document
boost::signals2::signal< void(const Gui::Document &)> signalActiveDocument
signal on activating Document
boost::signals2::signal< void(const Gui::ViewProvider &)> signalNewObject
signal on new Object
boost::signals2::signal< void(const Gui::ViewProvider &)> signalDeletedObject
signal on deleted Object
boost::signals2::signal< void(const Gui::ViewProvider &, const App::Property &)> signalBeforeChangeObject
signal on changed Object
boost::signals2::signal< void(const Gui::ViewProvider &, const App::Property &)> signalChangedObject
signal on changed object property
boost::signals2::signal< void(const Gui::ViewProvider &)> signalRelabelObject
signal on renamed Object
boost::signals2::signal< void(const Gui::ViewProvider &)> signalActivatedObject
signal on activated Object
boost::signals2::signal< void(const char *)> signalActivateWorkbench
signal on activated workbench
boost::signals2::signal< void(const char *)> signalAddWorkbench
signal on added workbench
boost::signals2::signal< void(const char *)> signalRemoveWorkbench
signal on removed workbench
boost::signals2::signal< void(const Gui::Document &)> signalShowHidden
signal on show hidden items
boost::signals2::signal< void(const Gui::MDIView *)> signalActivateView
signal on activating view
boost::signals2::signal< void(const Gui::ViewProviderDocumentObject &)> signalInEdit
signal on entering in edit mode
boost::signals2::signal< void(const Gui::ViewProviderDocumentObject &)> signalResetEdit
signal on leaving edit mode
methods for Document handling
void onLastWindowClosed (Gui::Document *pcDoc)
message when a GuiDocument is about to vanish
Gui::Document * activeDocument (void) const
Getter for the active document.
void setActiveDocument (Gui::Document *pcDocument)
Set the active document.
Gui::Document * editDocument (void) const
Getter for the editing document.
Gui::MDIView * editViewOfNode (SoNode *node) const
void setEditDocument (Gui::Document *pcDocument)
Set editing document, which will reset editing of all other document.
Gui::Document * getDocument (const char *name) const
Retrieves a pointer to the Gui::Document whose App::Document has the name name.
Gui::Document * getDocument (const App::Document *pDoc) const
Retrieves a pointer to the Gui::Document whose App::Document matches to pDoc.
Gui::MDIView * activeView (void) const
Getter for the active view of the active document or null.
void activateView (const Base::Type &, bool create=false)
Activate a view of the given type of the active document.
void showViewProvider (const App::DocumentObject *)
Shows the associated view provider of the given object.
void hideViewProvider (const App::DocumentObject *)
Hides the associated view provider of the given object.
Gui::ViewProvider * getViewProvider (const App::DocumentObject *) const
Get the view provider of the given object.
bool isClosing (void)
true when the application shutting down
void checkForPreviousCrashes ()
void slotNewDocument (const App::Document &, bool)
Observer message from the Application.
void slotDeleteDocument (const App::Document &)
void slotRelabelDocument (const App::Document &)
void slotRenameDocument (const App::Document &)
void slotActiveDocument (const App::Document &)
void slotShowHidden (const App::Document &)
void slotNewObject (const ViewProvider &)
void slotDeletedObject (const ViewProvider &)
void slotChangedObject (const ViewProvider &, const App::Property &Prop)
void slotRelabelObject (const ViewProvider &)
void slotActivatedObject (const ViewProvider &)
void slotInEdit (const Gui::ViewProviderDocumentObject &)
void slotResetEdit (const Gui::ViewProviderDocumentObject &)
Init, Destruct an Access methods
static Application * Instance = 0L
some kind of singelton
static PyMethodDef Methods []
void tryClose (QCloseEvent *e)
static void initApplication (void)
static void initTypes (void)
static void initOpenInventor (void)
static void runInitGuiScript (void)
static void runApplication (void)
static PyObject * sActivateWorkbenchHandler (PyObject *self, PyObject *args)
static PyObject * sAddWorkbenchHandler (PyObject *self, PyObject *args)
static PyObject * sRemoveWorkbenchHandler (PyObject *self, PyObject *args)
static PyObject * sGetWorkbenchHandler (PyObject *self, PyObject *args)
static PyObject * sListWorkbenchHandlers (PyObject *self, PyObject *args)
static PyObject * sActiveWorkbenchHandler (PyObject *self, PyObject *args)
static PyObject * sAddResPath (PyObject *self, PyObject *args)
static PyObject * sAddLangPath (PyObject *self, PyObject *args)
static PyObject * sAddIconPath (PyObject *self, PyObject *args)
static PyObject * sAddIcon (PyObject *self, PyObject *args)
static PyObject * sGetIcon (PyObject *self, PyObject *args)
static PyObject * sIsIconCached (PyObject *self, PyObject *args)
static PyObject * sSendActiveView (PyObject *self, PyObject *args)
static PyObject * sSendFocusView (PyObject *self, PyObject *args)
static PyObject * sGetMainWindow (PyObject *self, PyObject *args)
static PyObject * sUpdateGui (PyObject *self, PyObject *args)
static PyObject * sUpdateLocale (PyObject *self, PyObject *args)
static PyObject * sGetLocale (PyObject *self, PyObject *args)
static PyObject * sSetLocale (PyObject *self, PyObject *args)
static PyObject * sSupportedLocales (PyObject *self, PyObject *args)
static PyObject * sCreateDialog (PyObject *self, PyObject *args)
static PyObject * sAddPreferencePage (PyObject *self, PyObject *args)
static PyObject * sRunCommand (PyObject *self, PyObject *args)
static PyObject * sAddCommand (PyObject *self, PyObject *args)
static PyObject * sHide (PyObject *self, PyObject *args)
static PyObject * sShow (PyObject *self, PyObject *args)
static PyObject * sHideObject (PyObject *self, PyObject *args)
static PyObject * sShowObject (PyObject *self, PyObject *args)
static PyObject * sOpen (PyObject *self, PyObject *args)
static PyObject * sInsert (PyObject *self, PyObject *args)
static PyObject * sExport (PyObject *self, PyObject *args)
static PyObject * sReload (PyObject *self, PyObject *args)
static PyObject * sLoadFile (PyObject *self, PyObject *args)
static PyObject * sCoinRemoveAllChildren (PyObject *self, PyObject *args)
static PyObject * sActiveDocument (PyObject *self, PyObject *args)
static PyObject * sSetActiveDocument (PyObject *self, PyObject *args)
static PyObject * sActiveView (PyObject *self, PyObject *args)
static PyObject * sActivateView (PyObject *self, PyObject *args)
static PyObject * sGetDocument (PyObject *self, PyObject *args)
static PyObject * sEditDocument (PyObject *self, PyObject *args)
static PyObject * sDoCommand (PyObject *self, PyObject *args)
static PyObject * sDoCommandGui (PyObject *self, PyObject *args)
static PyObject * sAddModule (PyObject *self, PyObject *args)
static PyObject * sShowDownloads (PyObject *self, PyObject *args)
static PyObject * sShowPreferences (PyObject *self, PyObject *args)
static PyObject * sCreateViewer (PyObject *self, PyObject *args)
static PyObject * sGetMarkerIndex (PyObject *self, PyObject *args)
static PyObject * sAddDocObserver (PyObject *self, PyObject *args)
static PyObject * sRemoveDocObserver (PyObject *self, PyObject *args)
Detailed Description
The Application main class This is the central class of the GUI.
Author
Jrgen Riegel, Werner Mayer
Constructor & Destructor Documentation
Application()
Application::Application (bool GUIenabled)
construction
References Gui::Translator::activateLanguage(), Base::InterpreterSingleton::addType(), draftgeoutils.faces::bind(), Gui::FreeCADGui_methods, App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), Gui::TaskView::ControlPy::getInstance(), App::Application::GetParameterGroupByPath(), App::Application::GetUserParameter(), Gui::GetWidgetFactorySupplier(), Gui::PythonDebugModule::init_module(), Gui::ExpressionBindingPy::init_type(), Gui::MDIViewPy::init_type(), Gui::PythonStdout::init_type(), Gui::PythonStderr::init_type(), Gui::OutputStdout::init_type(), Gui::OutputStderr::init_type(), Gui::PythonStdin::init_type(), Gui::SelectionFilterPy::init_type(), Gui::AbstractSplitViewPy::init_type(), Gui::TaskView::ControlPy::init_type(), Gui::View3DInventorPy::init_type(), Gui::View3DInventorViewerPy::init_type(), Gui::UiLoaderPy::init_type(), Gui::PyResource::init_type(), Gui::Translator::instance(), Base::Interpreter(), Gui::MacroCommand::load(), Methods, Gui::SelectionSingleton::Methods, App::Application::signalActiveDocument, App::Application::signalDeleteDocument, App::Application::signalNewDocument, App::Application::signalRelabelDocument, App::Application::signalRenameDocument, App::Application::signalShowHidden, slotActiveDocument(), slotDeleteDocument(), slotNewDocument(), slotRelabelDocument(), slotRenameDocument(), slotShowHidden(), Gui::AxisOriginPy::Type, Gui::CommandPy::Type, Gui::DocumentPy::Type, Gui::LinkViewPy::Type, Gui::ViewProviderDocumentObjectPy::Type, Gui::ViewProviderLinkPy::Type, and Gui::ViewProviderPy::Type.
~Application()
Application::~Application ()
destruction
References Base::InterpreterSingleton::cleanupSWIG(), Base::Console(), Gui::WidgetFactorySupplier::destruct(), Gui::WorkbenchManager::destruct(), Gui::BitmapFactoryInst::destruct(), Gui::Translator::destruct(), Gui::SelectionSingleton::destruct(), Gui::SoFCDB::finish(), Base::Interpreter(), Base::ConsoleSingleton::Log(), and Gui::MacroCommand::save().
Member Function Documentation
activateView()
void Application::activateView (const Base::Type & type, bool create = false)
Activate a view of the given type of the active document.
Application::activateView Activates a view of the given type of the active document.
If a view of this type doesn't exist and create is true a new view of this type will be created.
Parameters
type
create
References femsolver.elmer.equations.elasticity::create(), and Base::BaseClass::isDerivedFrom().
activateWorkbench()
bool Application::activateWorkbench (const char * name)
Activate a named workbench.
Activate the matching workbench to the registered workbench handler with name name.
The handler must be an instance of a class written in Python. Normally, if a handler gets activated a workbench with the same name gets created unless it already exists.
The old workbench gets deactivated before. If the workbench to the handler is already active or if the switch fails false is returned.
References Gui::Workbench::activated(), Gui::MainWindow::activateWorkbench(), Gui::WorkbenchManager::active(), Base::Console(), Gui::WorkbenchManager::createWorkbench(), Gui::Workbench::deactivated(), Base::ConsoleSingleton::Error(), Base::Type::fromName(), App::GetApplication(), Base::BaseClass::getClassTypeId(), Gui::getMainWindow(), App::Application::GetParameterGroupByPath(), Gui::Workbench::getPyObject(), Gui::WorkbenchManager::getWorkbench(), Gui::WorkbenchManager::instance(), Base::Type::isDerivedFrom(), Base::ConsoleSingleton::Log(), Gui::Workbench::name(), Gui::WaitCursor::restoreCursor(), and Gui::WaitCursor::setWaitCursor().
Referenced by runApplication().
activeDocument()
Gui::Document * Application::activeDocument (void) const
Getter for the active document.
Getter for the active view.
Referenced by Gui::Dialog::DlgMacroExecuteImp::accept(), DrawingGui::TaskProjection::accept(), InspectionGui::VisualInspection::accept(), RobotGui::TaskDlgEdge2Trac::accept(), RobotGui::TaskDlgTrajectoryCompound::accept(), RobotGui::TaskDlgTrajectoryDressUp::accept(), Gui::MacroCommand::activated(), StdCmdGroup::activated(), StdViewDockUndockFullscreen::activated(), StdCmdMeasureDistance::activated(), DrawSketchHandlerExternal::activated(), DrawSketchHandlerCarbonCopy::activated(), Gui::RecentMacrosAction::activateFile(), SketcherGui::ViewProviderSketch::activateHandler(), Gui::SelectionSingleton::addSelection(), Gui::Command::adjustCameraPosition(), MeshGui::ViewProviderMesh::clipMeshCallback(), Gui::Dialog::TransformStrategy::commitTransform(), SketcherGui::ConstraintView::contextMenuEvent(), PartGui::DlgPrimitives::createPrimitive(), ReverseEngineeringGui::SegmentationManual::createSegment(), MeshPartGui::CrossSections::CrossSections(), PartGui::CrossSections::CrossSections(), Gui::MainWindow::customEvent(), Gui::PointMarker::customEvent(), PointsGui::ViewProviderScattered::cut(), PointsGui::ViewProviderStructured::cut(), Gui::DocumentIndex::data(), MeshGui::RemoveComponents::deleteSelection(), Gui::ViewProviderAnnotationLabel::doubleClicked(), Gui::ViewProviderMaterialObject::doubleClicked(), FemGui::ViewProviderFemPostFunction::doubleClicked(), FemGui::ViewProviderFemPostObject::doubleClicked(), RaytracingGui::ViewProviderLux::doubleClicked(), RaytracingGui::ViewProviderPovray::doubleClicked(), SketcherGui::ViewProviderSketch::doubleClicked(), Gui::ViewProviderDragger::doubleClicked(), Gui::ViewProviderPart::doubleClicked(), PartDesignGui::ViewProviderBody::doubleClicked(), PartDesignGui::ViewProviderDatum::doubleClicked(), PartGui::eraseAllDimensions(), Gui::MainWindow::event(), Gui::ViewProvider::eventCallback(), PartDesignGui::TaskBooleanParameters::exitSelectionMode(), MeshGui::ViewProviderMesh::fillHole(), ReverseEngineeringGui::SegmentationManual::Private::findGeometry(), TechDrawGui::DrawGuiUtil::get3DDirAndRot(), Gui::Command::getActiveGuiDocument(), Gui::DocumentT::getAppDocumentPython(), Gui::ViewProvider::getBoundingBox(), Gui::Command::getDocument(), Gui::DocumentT::getGuiDocumentPython(), Gui::ViewProviderT::getObjectPython(), PartGui::getViewer(), MeshGui::MeshSelection::getViewer(), StdCmdDrawStyle::isActive(), Gui::Command::isActiveObjectValid(), Gui::Command::isViewOfType(), MeshGui::ViewProviderMesh::markPartCallback(), MeshGui::DlgRegularSolidImp::on_createSolidButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_refreshButton_clicked(), FemGui::TaskFemConstraint::onButtonWizOk(), MeshGui::ViewProviderMesh::partMeshCallback(), PartDesignGui::TaskDlgBooleanParameters::reject(), RobotGui::TaskDlgTrajectoryCompound::reject(), RobotGui::TaskDlgTrajectoryDressUp::reject(), TechDrawGui::TaskLeaderLine::removeFeature(), TechDrawGui::TaskRichAnno::removeFeature(), Gui::SelectionSingleton::rmvPreselect(), Gui::SelectionSingleton::rmvSelectionGate(), Gui::TreeWidget::scrollItemToTop(), MeshGui::ViewProviderMesh::segmMeshCallback(), SpreadsheetGui::WorkbenchHelper::setBackgroundColor(), SpreadsheetGui::WorkbenchHelper::setForegroundColor(), Gui::SelectionSingleton::setPreselect(), sOpen(), Gui::TreeWidget::startItemSearch(), PartDesignGui::TaskShapeBinder::TaskShapeBinder(), RobotGui::TaskTrajectory::TaskTrajectory(), RobotGui::TrajectorySimulate::TrajectorySimulate(), and MeshGui::ViewProviderMesh::trimMeshCallback().
activeView()
Gui::MDIView * Application::activeView (void) const
Getter for the active view of the active document or null.
Referenced by PartDesignGui::assertActivePart(), PartDesignGui::getActivePart(), PartDesignGui::getBody(), Gui::ViewProvider::getBoundingBox(), PartDesignGui::setEdit(), PartDesignGui::Workbench::setupContextMenu(), and PartDesignGui::ViewProvider::unsetEdit().
attachView()
void Application::attachView (Gui::BaseView * pcView)
Attach a view (get called by the FCView constructor)
Referenced by Gui::BaseView::BaseView().
checkForPreviousCrashes()
void Application::checkForPreviousCrashes ()
References Gui::Dialog::DocumentRecovery::foundDocuments(), App::GetApplication(), Gui::getMainWindow(), and App::Application::getTempPath().
commandManager()
CommandManager & Application::commandManager (void)
Reference to the command manager.
Referenced by Gui::PythonGroupCommand::activated(), Gui::GroupCommand::addCommand(), Gui::Dialog::DlgCustomToolbarsImp::addCustomCommand(), PartDesignGui::assertActivePart(), Gui::Dialog::DlgCustomCommandsImp::changeEvent(), Gui::Dialog::DlgCustomKeyboardImp::changeEvent(), Gui::Dialog::DlgCustomToolbars::changeEvent(), Gui::MainWindow::changeEvent(), Gui::MDITabbar::contextMenuEvent(), Gui::PythonGroupCommand::createAction(), Gui::CreateDocCommands(), Gui::CreateFeatCommands(), Gui::CreateLinkCommands(), Gui::Workbench::createLinkMenu(), Gui::CreateMacroCommands(), Gui::MainWindow::createPopupMenu(), Gui::CreateStdCommands(), Gui::CreateStructureCommands(), Gui::CreateTestCommands(), Gui::CreateViewStdCommands(), Gui::CreateWindowStdCommands(), PartDesignGui::WorkflowManager::determineWorkflow(), Gui::Dialog::DlgCustomCommandsImp::DlgCustomCommandsImp(), Gui::Dialog::DlgCustomKeyboardImp::DlgCustomKeyboardImp(), Gui::Dialog::DlgCustomToolbars::DlgCustomToolbars(), Gui::MainWindow::event(), Gui::Dialog::CommandModel::goAddMacro(), Gui::PythonGroupCommand::languageChange(), Gui::MacroCommand::load(), Gui::Dialog::DlgCustomActionsImp::on_actionListWidget_itemActivated(), Gui::Dialog::DlgMacroExecuteImp::on_addonsButton_clicked(), Gui::Dialog::DlgCustomActionsImp::on_buttonAddAction_clicked(), Gui::Dialog::DlgCustomActionsImp::on_buttonRemoveAction_clicked(), Gui::Dialog::DlgCustomActionsImp::on_buttonReplaceAction_clicked(), Gui::Dialog::DlgCustomKeyboardImp::on_buttonReset_clicked(), Gui::Dialog::DlgCustomKeyboardImp::on_buttonResetAll_clicked(), Gui::Dialog::DlgCustomKeyboardImp::on_categoryBox_activated(), Gui::Dialog::DlgCustomToolbars::on_categoryBox_activated(), Gui::Dialog::DlgCustomKeyboardImp::on_commandTreeWidget_currentItemChanged(), Gui::Dialog::DlgCustomKeyboardImp::on_editShortcut_textChanged(), Gui::Dialog::DemoMode::on_fullscreen_toggled(), SketcherGui::TaskSketcherConstrains::on_listWidgetConstraints_updateActiveStatus(), SketcherGui::TaskSketcherConstrains::on_listWidgetConstraints_updateDrivingStatus(), Gui::Dialog::DlgMacroExecuteImp::on_toolbarButton_clicked(), Gui::Dialog::DlgCustomCommandsImp::onAddMacroAction(), Gui::Dialog::DlgCustomKeyboardImp::onAddMacroAction(), Gui::Dialog::DlgCustomToolbars::onAddMacroAction(), Gui::Dialog::DlgCustomCommandsImp::onGroupActivated(), Gui::Dialog::DlgCustomCommandsImp::onModifyMacroAction(), Gui::Dialog::DlgCustomKeyboardImp::onModifyMacroAction(), Gui::Dialog::DlgCustomToolbars::onModifyMacroAction(), Gui::TaskCSysDragger::open(), sAddCommand(), Gui::MacroCommand::save(), Gui::Dialog::DlgCustomKeyboardImp::setShortcutOfCurrentAction(), Gui::ToolBoxManager::setup(), Gui::ToolBarManager::setup(), MeshGui::Workbench::setupMenuBar(), sRunCommand(), SandboxGui::TaskPanelView::TaskPanelView(), FemGui::TaskPostClip::TaskPostClip(), FemGui::TaskPostCut::TaskPostCut(), Gui::TaskView::TaskWatcherCommands::TaskWatcherCommands(), Gui::TaskView::TaskWatcherPython::TaskWatcherPython(), Gui::Command::testActive(), Gui::MainWindow::updateEditorActions(), and Gui::TaskCSysDragger::~TaskCSysDragger().
createStandardOperations()
void Application::createStandardOperations ()
helper which create the commands
References Gui::CreateDocCommands(), Gui::CreateFeatCommands(), Gui::CreateLinkCommands(), Gui::CreateMacroCommands(), Gui::CreateStdCommands(), Gui::CreateStructureCommands(), Gui::CreateTestCommands(), Gui::CreateViewStdCommands(), and Gui::CreateWindowStdCommands().
detachView()
void Application::detachView (Gui::BaseView * pcView)
Detach a view (get called by the FCView destructor)
Referenced by Gui::BaseView::onClose(), and SpreadsheetGui::SheetView::~SheetView().
editDocument()
Gui::Document * Application::editDocument (void) const
Getter for the editing document.
Referenced by Gui::Document::beforeDelete(), SketcherGui::ViewProviderSketch::getEditingPlacement(), Gui::ViewProviderLink::initDraggingPlacement(), Gui::Command::invoke(), Gui::TreeWidget::mouseDoubleClickEvent(), SketcherGui::ViewProviderSketch::purgeHandler(), SketcherGui::ViewProviderSketch::setEdit(), SketcherGui::ViewProviderSketch::setEditViewer(), Gui::Document::slotDeletedObject(), Gui::DocumentItem::slotInEdit(), Gui::Document::slotSkipRecompute(), Gui::ViewProviderLink::startEditing(), and SketcherGui::ViewProviderSketch::updateData().
editViewOfNode()
Gui::MDIView * Application::editViewOfNode (SoNode * node) const
Referenced by SketcherGui::ViewProviderSketch::drawConstraintIcons(), SketcherGui::ViewProviderSketch::getScaleFactor(), and SketcherGui::ViewProviderSketch::seekConstraintPosition().
exportTo()
void Application::exportTo (const char * FileName, const char * DocName, const char * Module)
Export objects from the document DocName to a single file.
References Gui::Command::App, Gui::MainWindow::appendRecentFile(), Base::Tools::escapedUnicodeFromUtf8(), Base::Tools::escapeEncodeFilename(), Base::FileInfo::extension(), Base::FileInfo::filePath(), App::GetApplication(), Base::Persistence::getClassTypeId(), App::Application::getDocument(), App::Application::getImportFilters(), Gui::getMainWindow(), Gui::SelectionSingleton::getObjectsOfType(), Gui::WaitCursor::NoEvents, Gui::WaitCursor::restoreCursor(), Gui::Selection(), Gui::WaitCursor::setIgnoreEvents(), and Gui::WaitCursor::setWaitCursor().
Referenced by StdCmdExport::activated().
getDocument() [1/2]
Gui::Document * Application::getDocument (const App::Document * pDoc) const
Retrieves a pointer to the Gui::Document whose App::Document matches to pDoc.
If no such document exists 0 is returned.
getDocument() [2/2]
Gui::Document * Application::getDocument (const char * name) const
Retrieves a pointer to the Gui::Document whose App::Document has the name name.
If no such document exists 0 is returned.
References App::GetApplication(), and App::Application::getDocument().
Referenced by Gui::Dialog::DocumentRecovery::accept(), MeshPartGui::Tessellation::accept(), PartGui::FaceColors::accept(), PartGui::LoftWidget::accept(), PartGui::SweepWidget::accept(), TechDrawGui::TaskCenterLine::accept(), TechDrawGui::TaskCosVertex::accept(), TechDrawGui::TaskDetail::accept(), TechDrawGui::TaskLeaderLine::accept(), TechDrawGui::TaskLineDecor::accept(), TechDrawGui::TaskProjGroup::accept(), TechDrawGui::TaskRichAnno::accept(), Gui::TaskCSysDragger::accept(), Gui::Dialog::TransformStrategy::acceptDataTransform(), Gui::AlignmentGroup::addView(), Gui::TransactionViewProvider::applyNew(), Gui::Dialog::TransformStrategy::applyViewTransform(), PartDesignGui::ViewProviderBody::attach(), Gui::MainWindow::closeAllDocuments(), TechDrawGui::Grabber3d::copyActiveViewToSvgFile(), Gui::TreeWidget::dropEvent(), Gui::Document::exportObjects(), Gui::ViewProviderOriginGroupExtension::extensionAttach(), Gui::ViewProviderDocumentObject::findFrontRootOfType(), PartGui::DlgExtrusion::findShapes(), Gui::ViewProviderDocumentObject::getActiveView(), Gui::DocumentT::getDocument(), Gui::ViewProviderT::getDocument(), Gui::AlignmentGroup::getDocument(), Gui::ViewProviderDocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getEditingView(), TechDrawGui::QGIView::getFrameState(), InspectionGui::ViewProviderInspection::getIcon(), Gui::ViewProviderDocumentObject::getInventorView(), TechDrawGui::ViewProviderDrawingView::getMDIViewPage(), TechDrawGui::ViewProviderTemplate::getMDIViewPage(), TechDrawGui::ViewProviderDrawingView::getQView(), Gui::LinkInfo::getView(), Gui::ViewProviderDocumentObject::getViewOfNode(), TechDrawGui::QGIView::getViewProvider(), Gui::ViewProviderDocumentObjectGroup::getViewProviders(), Gui::MainWindow::insertFromMimeData(), Gui::TreeWidget::isObjectShowable(), Gui::TaskView::TaskView::keyPressEvent(), TechDrawGui::TaskLinkDim::loadAvailDims(), Gui::MergeDocuments::MergeDocuments(), Gui::DAG::Model::mouseDoubleClickEvent(), MeshGui::DlgEvaluateMeshImp::on_repairAllTogether_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairDegeneratedButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairDuplicatedFacesButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairDuplicatedPointsButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairFoldsButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairIndicesButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairNonmanifoldsButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairOrientationButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairSelfIntersectionButton_clicked(), Gui::TreeWidget::onActivateDocument(), Gui::TreeWidget::onFinishEditing(), PartGui::TaskDlgAttacher::open(), PartGui::FaceColors::open(), PartGui::FaceColors::Private::Private(), PartGui::FaceColors::reject(), TechDrawGui::TaskCenterLine::reject(), TechDrawGui::TaskCosVertex::reject(), TechDrawGui::TaskDetail::reject(), TechDrawGui::TaskLeaderLine::reject(), TechDrawGui::TaskLineDecor::reject(), TechDrawGui::TaskProjGroup::reject(), TechDrawGui::TaskRichAnno::reject(), Gui::Dialog::TransformStrategy::resetViewTransform(), Gui::Document::save(), Gui::Document::saveAll(), PartGui::DlgSettings3DViewPart::saveSettings(), Gui::TreeWidget::selectAll(), FemGui::ActiveAnalysisObserver::setActiveObject(), TechDrawGui::ViewProviderPage::setTemplateMarkers(), PartDesignGui::ViewProviderBody::setVisualBodyMode(), sExport(), DrawingGui::ViewProviderDrawingPage::showDrawingView(), TechDrawGui::ViewProviderPage::showMDIViewPage(), SpreadsheetGui::ViewProviderSheet::showSpreadsheetView(), sReload(), PartGui::TaskAttacher::TaskAttacher(), TechDrawGui::TaskCosVertex::TaskCosVertex(), TechDrawGui::TaskDetail::TaskDetail(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), PartDesignGui::TaskPipeOrientation::TaskPipeOrientation(), TechDrawGui::TaskProjGroup::TaskProjGroup(), TechDrawGui::TaskRichAnno::TaskRichAnno(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), DrawingGui::ViewProviderDrawingPage::updateData(), MeshGui::ViewProviderMeshCurvature::updateData(), TechDrawGui::ViewProviderGeomHatch::updateGraphic(), PartDesignGui::ViewProviderBody::updateOriginDatumSize(), and InspectionGui::VisualInspection::VisualInspection().
getViewProvider()
Gui::ViewProvider * Application::getViewProvider (const App::DocumentObject * obj) const
Get the view provider of the given object.
References Draft::gui.
Referenced by MeshPartGui::Tessellation::accept(), PartGui::DlgFilletEdges::accept(), Gui::View3DInventorViewer::checkGroupOnTop(), SketcherGui::ConstraintView::deleteSelectedItems(), SketcherGui::ElementView::deleteSelectedItems(), Gui::DlgObjectSelection::DlgObjectSelection(), Gui::SoFCUnifiedSelection::doAction(), Gui::TreeWidget::dropEvent(), Gui::ViewProviderGeoFeatureGroupExtension::extensionClaimChildren(), ExportOCAFGui::findColors(), Gui::LinkInfo::getDetail(), Gui::ViewProviderDocumentObject::getDetailPath(), Gui::ViewProviderLink::getElementColors(), Gui::ViewProviderLink::getLinkedView(), TechDrawGui::ViewProviderGeomHatch::getMDIView(), TechDrawGui::ViewProviderHatch::getMDIView(), PartDesignGui::ViewProviderDatum::getRelevantBoundBox(), Gui::DocumentItem::getViewProvider(), MeshGui::MeshSelection::getViewProviders(), PartGui::TaskCheckGeometryResults::goCheck(), SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), PartDesignGui::ViewProviderDressUp::highlightReferences(), PartDesignGui::ViewProviderShapeBinder::highlightReferences(), SurfaceGui::ViewProviderFilling::highlightReferences(), SurfaceGui::ViewProviderSections::highlightReferences(), PartDesignGui::makeBody(), Gui::ViewProviderOrigin::onChanged(), PartGui::ViewProviderOffset::onDelete(), PartGui::ViewProviderThickness::onDelete(), PartDesignGui::ViewProvider::onDelete(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), Gui::PropertyView::onTimer(), PartGui::PropertyEnumAttacherItem::openTask(), PartGui::OffsetWidget::reject(), PartGui::ThicknessWidget::reject(), PartDesignGui::TaskDlgFeatureParameters::reject(), PartDesignGui::TaskDlgSketchBasedParameters::reject(), Gui::TreeWidget::selectAllLinks(), Gui::Document::setActiveView(), Gui::Document::setEdit(), Gui::DocumentPy::setEdit(), Gui::ViewProviderLink::setOverrideMode(), PartDesignGui::ViewProviderAddSub::setPreviewDisplayMode(), Gui::ViewProviderOrigin::setTemporaryVisibility(), PartGui::DlgFilletEdges::setupFillet(), Gui::SelectionSingleton::setVisible(), sExport(), PartDesignGui::ViewProviderTransformed::startEditing(), PartDesignGui::TaskBoxPrimitives::TaskBoxPrimitives(), FemGui::TaskCreateNodeSet::TaskCreateNodeSet(), PartDesignGui::TaskFeaturePick::TaskFeaturePick(), PartDesignGui::TaskRevolutionParameters::TaskRevolutionParameters(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderMultiFuse::updateData(), PartGui::ViewProviderMultiCommon::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderFillet::updateData(), PartGui::ViewProviderChamfer::updateData(), RobotGui::ViewProviderRobotObject::updateData(), PartDesignGui::ViewProviderBody::updateData(), FemGui::ViewProviderFemPostPipeline::updateFunctionSize(), PartDesignGui::ViewProviderBody::updateOriginDatumSize(), Gui::ViewProviderOriginGroupExtension::updateOriginSize(), FemGui::ViewProviderFemPostFunctionProvider::updateSize(), Gui::View3DInventorViewer::viewSelection(), PartGui::DlgProjectionOnSurface::~DlgProjectionOnSurface(), PartDesignGui::TaskBoxPrimitives::~TaskBoxPrimitives(), PartDesignGui::TaskLinearPatternParameters::~TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::~TaskMirroredParameters(), PartDesignGui::TaskPolarPatternParameters::~TaskPolarPatternParameters(), and PartDesignGui::TaskRevolutionParameters::~TaskRevolutionParameters().
hideViewProvider()
void Application::hideViewProvider (const App::DocumentObject * obj)
Hides the associated view provider of the given object.
References Gui::ViewProvider::hide().
Referenced by FemGui::TaskDlgMeshShapeNetgen::accept(), PartDesignGui::ViewProviderBody::dropObject(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderMultiFuse::updateData(), PartGui::ViewProviderMultiCommon::updateData(), PartGui::ViewProviderCompound::updateData(), PathGui::ViewProviderArea::updateData(), PathGui::ViewProviderAreaView::updateData(), and PathGui::ViewProviderPathShape::updateData().
importFrom()
void Application::importFrom (const char * FileName, const char * DocName, const char * Module)
import a file into the document DocName
References Gui::Command::App, Gui::MainWindow::appendRecentFile(), Base::Tools::escapedUnicodeFromUtf8(), Base::Tools::escapeEncodeFilename(), Base::FileInfo::extension(), Base::FileInfo::filePath(), App::GetApplication(), ParameterGrp::GetBool(), Gui::getMainWindow(), App::Application::GetParameterGroupByPath(), Base::FileInfo::hasExtension(), Gui::WaitCursor::NoEvents, draftutils.translate::QT_TRANSLATE_NOOP, Gui::WaitCursor::restoreCursor(), Gui::WaitCursor::setIgnoreEvents(), Gui::WaitCursor::setWaitCursor(), Gui::FileDialog::setWorkingDirectory(), and Gui::MainWindow::updateActions().
Referenced by StdCmdImport::activated(), and Gui::MainWindow::loadUrls().
initApplication()
void Application::initApplication (void) static
References Base::Console(), App::Application::destructObserver(), and Base::ConsoleSingleton::Error().
initOpenInventor()
void Application::initOpenInventor (void) static
References Gui::SoFCDB::init().
initTypes()
void Application::initTypes (void) static
References Base::Persistence::getClassTypeId(), Base::BaseClass::init(), and Base::Persistence::init().
isClosing()
bool Application::isClosing (void)
true when the application shutting down
macroManager()
MacroManager * Application::macroManager (void)
Get macro manager.
Referenced by Gui::Dialog::DlgMacroExecuteImp::accept(), Gui::MacroCommand::activated(), StdCmdMacroStartDebug::activated(), StdCmdMacroStopDebug::activated(), StdCmdMacroStepOver::activated(), StdCmdMacroStepInto::activated(), StdCmdViewIvIssueCamPos::activated(), Gui::RecentMacrosAction::activateFile(), Gui::Command::addModule(), PendingLine::cancel(), Gui::SelectionSingleton::clearCompleteSelection(), Gui::SelectionSingleton::clearSelection(), Gui::Dialog::DlgMacroRecordImp::DlgMacroRecordImp(), Gui::TreeWidget::dropEvent(), Gui::SelectionSingleton::enableCommandLog(), Gui::PythonEditorView::executeScript(), Gui::Command::invoke(), StdCmdMacroStopDebug::isActive(), StdCmdMacroStepOver::isActive(), StdCmdMacroStepInto::isActive(), Gui::TreeWidget::mouseDoubleClickEvent(), PendingLine::PendingLine(), Gui::Command::printCaller(), Gui::PythonEditorP::PythonEditorP(), sDoCommand(), and sDoCommandGui().
onLastWindowClosed()
void Application::onLastWindowClosed (Gui::Document * pcDoc)
message when a GuiDocument is about to vanish
References Gui::Command::Doc, Base::BaseClass::getClassTypeId(), Gui::Document::getDocument(), Gui::getMainWindow(), App::Document::getName(), Gui::MainWindow::setActiveWindow(), and App::Document::TempDoc.
onUpdate()
void Application::onUpdate (void)
call update to all documents and all views (costly!)
Referenced by shipAreasCurve.TaskPanel.TaskPanel::initValues(), shipAreasCurve.TaskPanel.TaskPanel::onData(), and Gui::Command::updateAll().
open()
void Application::open (const char * FileName, const char * Module)
open a file
References Gui::Command::App, Gui::MainWindow::appendRecentFile(), App::Document::countObjects(), Base::Tools::escapedUnicodeFromUtf8(), Base::Tools::escapeEncodeFilename(), Base::FileInfo::extension(), Base::FileInfo::filePath(), App::Application::getActiveDocument(), App::GetApplication(), ParameterGrp::GetBool(), Gui::getMainWindow(), App::Document::getName(), App::Application::GetParameterGroupByPath(), Gui::Command::Gui, Draft::gui, Base::FileInfo::hasExtension(), Gui::WaitCursor::NoEvents, Gui::WaitCursor::restoreCursor(), Gui::WaitCursor::setIgnoreEvents(), Gui::WaitCursor::setWaitCursor(), and Gui::FileDialog::setWorkingDirectory().
Referenced by StdCmdOpen::activated(), Gui::RecentFilesAction::activateFile(), Gui::GUIApplication::event(), and sLoadFile().
reopen()
App::Document * Application::reopen (App::Document * doc)
Reload a partial opened document.
References App::GetApplication(), Base::BaseClass::getClassTypeId(), App::PropertyContainer::getPropertyList(), Gui::WaitCursor::NoEvents, App::Application::openDocument(), App::Document::PartialDoc, App::Document::PartialRestore, App::Property::purgeTouched(), Gui::Document::setActiveView(), and Gui::WaitCursor::setIgnoreEvents().
Referenced by Gui::TreeWidget::onReloadDoc(), and sReload().
runApplication()
void Application::runApplication (void) static
References activateWorkbench(), Gui::BitmapFactory(), Gui::GUIApplication::caughtException, App::Application::Config(), draftgeoutils.intersections::connect(), Base::Console(), Base::FileInfo::deleteFile(), App::Application::destructObserver(), Base::ConsoleSingleton::Error(), Gui::ActionStyleEvent::EventType, App::GetApplication(), App::Application::GetARGC(), App::Application::GetARGV(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), App::Application::getCmdLineFiles(), Gui::WindowParameter::getDefaultParameter(), App::Application::getExecutableName(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), Gui::getMainWindow(), App::Application::GetParameterGroupByPath(), App::Application::getResourceDir(), App::Application::getTempPath(), App::Application::getUserAppDataDir(), Gui::GUIApplicationNativeEventAware::initSpaceball(), Gui::AutoSaver::instance(), Gui::GUISingleApplication::isRunning(), Base::ConsoleSingleton::Log(), Base::ConsoleSingleton::Message(), Gui::FileDialog::restoreLocation(), Gui::FileDialog::saveLocation(), Gui::GUISingleApplication::sendMessage(), Gui::AutoSaver::setCompressed(), setStyleSheet(), Gui::AutoSaver::setTimeout(), Gui::FileDialog::setWorkingDirectory(), and workbenches().
runInitGuiScript()
void Application::runInitGuiScript (void) static
References Base::Interpreter(), Base::InterpreterSingleton::runString(), and Base::ScriptFactory().
sActivateView()
PyObject * Gui::Application::sActivateView (PyObject * self, PyObject * args) static
References femsolver.elmer.equations.elasticity::create(), and Base::Type::fromName().
sActivateWorkbenchHandler()
PyObject * Application::sActivateWorkbenchHandler (PyObject * self, PyObject * args) static
References Base::BaseExceptionFreeCADError.
sActiveDocument()
PyObject * Gui::Application::sActiveDocument (PyObject * self, PyObject * args) static
References Gui::Document::getPyObject().
sActiveView()
PyObject * Gui::Application::sActiveView (PyObject * self, PyObject * args) static
References Base::Type::fromName(), Base::BaseClass::getClassTypeId(), Gui::MDIView::getPyObject(), and Base::BaseClass::isDerivedFrom().
sActiveWorkbenchHandler()
PyObject * Application::sActiveWorkbenchHandler (PyObject * self, PyObject * args) static
References Gui::WorkbenchManager::active(), Gui::WorkbenchManager::instance(), and Gui::Workbench::name().
sAddCommand()
PyObject * Application::sAddCommand (PyObject * self, PyObject * args) static
References Gui::CommandManager::addCommand(), Base::BaseExceptionFreeCADError, commandManager(), Base::FileInfo::fileNamePure(), Base::FileInfo::filePath(), Instance, Gui::Command::setAppModuleName(), and Gui::Command::setGroupName().
sAddDocObserver()
PyObject * Application::sAddDocObserver (PyObject * self, PyObject * args) static
References Gui::DocumentObserverPython::addObserver().
sAddIcon()
PyObject * Application::sAddIcon (PyObject * self, PyObject * args) static
References Gui::BitmapFactoryInst::addPixmapToCache(), Base::BaseExceptionFreeCADError, and Gui::BitmapFactory().
sAddIconPath()
PyObject * Application::sAddIconPath (PyObject * self, PyObject * args) static
References Gui::BitmapFactoryInst::addPath(), Gui::BitmapFactory(), and App::GetApplication().
sAddLangPath()
PyObject * Application::sAddLangPath (PyObject * self, PyObject * args) static
References Gui::Translator::addPath(), App::GetApplication(), and Gui::Translator::instance().
sAddModule()
PyObject * Application::sAddModule (PyObject * self, PyObject * args) static
References Gui::Command::addModule(), and Gui::Command::Doc.
sAddPreferencePage()
PyObject * Application::sAddPreferencePage (PyObject * self, PyObject * args) static
sAddResPath()
PyObject * Application::sAddResPath (PyObject * self, PyObject * args) static
References Gui::BitmapFactoryInst::addPath(), Gui::Translator::addPath(), Gui::BitmapFactory(), App::GetApplication(), and Gui::Translator::instance().
sAddWorkbenchHandler()
PyObject * Application::sAddWorkbenchHandler (PyObject * self, PyObject * args) static
sCoinRemoveAllChildren()
PyObject * Application::sCoinRemoveAllChildren (PyObject * self, PyObject * args) static
References Gui::coinRemoveAllChildren(), Base::InterpreterSingleton::convertSWIGPointerObj(), and Base::Interpreter().
sCreateDialog()
PyObject * Application::sCreateDialog (PyObject * self, PyObject * args) static
sCreateViewer()
PyObject * Application::sCreateViewer (PyObject * self, PyObject * args) static
References Gui::MainWindow::addWindow(), Gui::getMainWindow(), and OfflineRenderingUtils::viewer().
sDoCommand()
PyObject * Application::sDoCommand (PyObject * self, PyObject * args) static
References Gui::MacroManager::addLine(), Gui::MacroManager::App, Instance, macroManager(), and Gui::Command::printPyCaller().
sDoCommandGui()
PyObject * Application::sDoCommandGui (PyObject * self, PyObject * args) static
References Gui::MacroManager::addLine(), Gui::MacroManager::Gui, Instance, macroManager(), and Gui::Command::printPyCaller().
sEditDocument()
PyObject * Gui::Application::sEditDocument (PyObject * self, PyObject * args) static
References Gui::Document::getPyObject().
sendHasMsgToActiveView()
bool Application::sendHasMsgToActiveView (const char * pMsg)
send Messages test to the active view
References Gui::MainWindow::activeWindow(), and Gui::getMainWindow().
Referenced by StdCmdSave::isActive(), StdCmdSaveAs::isActive(), StdCmdPrint::isActive(), StdCmdPrintPreview::isActive(), StdCmdPrintPdf::isActive(), StdCmdUndo::isActive(), StdCmdRedo::isActive(), StdCmdCut::isActive(), StdCmdViewFitAll::isActive(), StdCmdViewFitSelection::isActive(), StdCmdViewVR::isActive(), StdCmdViewExample1::isActive(), StdCmdViewExample2::isActive(), StdCmdViewExample3::isActive(), StdCmdViewIvStereoOff::isActive(), StdCmdViewIvStereoRedGreen::isActive(), StdCmdViewIvStereoQuadBuff::isActive(), StdCmdViewIvStereoInterleavedRows::isActive(), StdCmdViewIvStereoInterleavedColumns::isActive(), and StdCmdViewIvIssueCamPos::isActive().
sendHasMsgToFocusView()
bool Application::sendHasMsgToFocusView (const char * pMsg)
send Messages test to the focused view
References Gui::MainWindow::activeWindow(), and Gui::getMainWindow().
sendMsgToActiveView()
bool Application::sendMsgToActiveView (const char * pMsg, const char ** ppReturn = 0)
send Messages to the active view
References Gui::MainWindow::activeWindow(), Gui::getMainWindow(), and Gui::MainWindow::updateActions().
Referenced by StdCmdUndo::activated(), StdCmdRedo::activated(), StdCmdCut::activated(), StdCmdFreezeViews::activated(), StdCmdViewIvIssueCamPos::activated(), Gui::Dialog::UndoDialog::onSelected(), and Gui::Dialog::RedoDialog::onSelected().
sendMsgToFocusView()
bool Application::sendMsgToFocusView (const char * pMsg, const char ** ppReturn = 0)
send Messages to the focused view
send Messages to the active view
References Gui::MainWindow::activeWindow(), Gui::getMainWindow(), and Gui::MainWindow::updateActions().
Referenced by StdCmdCopy::activated(), and StdCmdPaste::activated().
setActiveDocument()
void Application::setActiveDocument (Gui::Document * pcDocument)
Set the active document.
References Gui::MacroManager::Cmt, Base::Console(), Gui::Document::getDocument(), Gui::getMainWindow(), App::Document::getName(), Base::Interpreter(), Base::ConsoleSingleton::Log(), Base::InterpreterSingleton::runString(), Gui::MainWindow::updateActions(), and Base::ConsoleSingleton::Warning().
setEditDocument()
void Application::setEditDocument (Gui::Document * pcDocument)
Set editing document, which will reset editing of all other document.
References Gui::getMainWindow(), and Gui::MainWindow::updateActions().
Referenced by Gui::ElementColors::accept(), Gui::Document::beforeDelete(), Gui::ElementColors::reject(), Gui::Document::resetEdit(), Gui::Document::setEdit(), and Gui::Document::slotDeletedObject().
setStyleSheet()
void Application::setStyleSheet (const QString & qssFile, bool tiledBackground)
Activate a named workbench.
References Gui::ActionStyleEvent::Clear, Gui::getMainWindow(), and Gui::ActionStyleEvent::Restore.
Referenced by runApplication(), and Gui::Dialog::DlgGeneralImp::saveSettings().
setupContextMenu()
void Application::setupContextMenu (const char * recipient, MenuItem * items) const
References Gui::WorkbenchManager::active(), Base::BaseClass::getClassTypeId(), Base::BaseClass::getTypeId(), Gui::WorkbenchManager::instance(), Base::Type::isDerivedFrom(), Gui::Workbench::name(), and Gui::Workbench::setupContextMenu().
Referenced by Gui::TreeWidget::contextMenuEvent(), Gui::DAG::Model::contextMenuEvent(), SketcherGui::ViewProviderSketch::mouseButtonPressed(), and Gui::NavigationStyle::openPopupMenu().
sExport()
PyObject * Application::sExport (PyObject * self, PyObject * args) static
References Base::Console(), Base::ConsoleSingleton::Error(), Gui::Document::getActiveView(), getDocument(), Gui::ViewProvider::getRoot(), getViewProvider(), Instance, App::DocumentObjectPy::Type, Gui::View3DInventor::viewAll(), and Gui::SoFCDB::writeToFile().
sGetDocument()
PyObject * Application::sGetDocument (PyObject * self, PyObject * args) static
References Gui::Document::getPyObject(), and App::DocumentPy::Type.
sGetIcon()
PyObject * Application::sGetIcon (PyObject * self, PyObject * args) static
References Gui::BitmapFactory(), Gui::PythonWrapper::fromQIcon(), Gui::PythonWrapper::loadGuiModule(), Gui::PythonWrapper::loadWidgetsModule(), and Gui::BitmapFactoryInst::pixmap().
sGetLocale()
PyObject * Application::sGetLocale (PyObject * self, PyObject * args) static
References Gui::Translator::activeLanguage(), and Gui::Translator::instance().
sGetMainWindow()
PyObject * Application::sGetMainWindow (PyObject * self, PyObject * args) static
References Gui::PythonWrapper::fromQWidget(), Gui::getMainWindow(), Gui::PythonWrapper::loadCoreModule(), Gui::PythonWrapper::loadGuiModule(), and Gui::PythonWrapper::loadWidgetsModule().
sGetMarkerIndex()
PyObject * Application::sGetMarkerIndex (PyObject * self, PyObject * args) static
References DraftVecUtils::find(), App::GetApplication(), Gui::Inventor::MarkerBitmaps::getMarkerIndex(), and App::Application::GetParameterGroupByPath().
sGetWorkbenchHandler()
PyObject * Application::sGetWorkbenchHandler (PyObject * self, PyObject * args) static
sHide()
PyObject * Application::sHide (PyObject * self, PyObject * args) static
References Gui::Document::setHide().
sHideObject()
PyObject * Application::sHideObject (PyObject * self, PyObject * args) static
References App::DocumentObjectPy::Type.
showViewProvider()
void Application::showViewProvider (const App::DocumentObject * obj)
Shows the associated view provider of the given object.
References Gui::ViewProvider::show().
Referenced by PartGui::ViewProviderBoolean::onDelete(), PartGui::ViewProviderMultiFuse::onDelete(), PartGui::ViewProviderMultiCommon::onDelete(), PartGui::ViewProviderCompound::onDelete(), PartGui::ViewProviderMirror::onDelete(), PartGui::ViewProviderFillet::onDelete(), PartGui::ViewProviderChamfer::onDelete(), PartGui::ViewProviderRevolution::onDelete(), PartGui::ViewProviderRuledSurface::onDelete(), PathGui::ViewProviderArea::onDelete(), PathGui::ViewProviderAreaView::onDelete(), PathGui::ViewProviderPathShape::onDelete(), DrawingGui::OrthoViews::OrthoViews(), PartDesignGui::TaskLoftParameters::TaskLoftParameters(), and PartDesignGui::TaskPipeScaling::TaskPipeScaling().
sInsert()
PyObject * Application::sInsert (PyObject * self, PyObject * args) static
References Gui::MainWindow::addWindow(), Gui::BitmapFactory(), Base::Console(), Base::ConsoleSingleton::Error(), App::Application::getActiveDocument(), App::GetApplication(), App::Application::getDocument(), Gui::getMainWindow(), App::Application::newDocument(), and Gui::EditorView::open().
sIsIconCached()
PyObject * Application::sIsIconCached (PyObject * self, PyObject * args) static
References Gui::BitmapFactory().
sListWorkbenchHandlers()
PyObject * Application::sListWorkbenchHandlers (PyObject * self, PyObject * args) static
sLoadFile()
PyObject * Application::sLoadFile (PyObject * self, PyObject * args) static
References Base::FileInfo::exists(), Base::FileInfo::extension(), App::GetApplication(), App::Application::getImportModules(), Instance, Base::FileInfo::isFile(), and open().
slotActivatedObject()
void Application::slotActivatedObject (const ViewProvider & vp) protected
References Gui::getMainWindow(), and Gui::MainWindow::updateActions().
Referenced by slotNewDocument().
slotActiveDocument()
void Application::slotActiveDocument (const App::Document & Doc) protected
References Gui::MainWindow::activeWindow(), Gui::getMainWindow(), Gui::MainWindow::setActiveWindow(), and Gui::MainWindow::updateActions().
Referenced by Application().
slotChangedObject()
void Application::slotChangedObject (const ViewProvider & vp, const App::Property & Prop) protected
References Gui::getMainWindow(), and Gui::MainWindow::updateActions().
Referenced by slotNewDocument().
slotDeletedObject()
void Application::slotDeletedObject (const ViewProvider & vp) protected
Referenced by slotNewDocument().
slotDeleteDocument()
void Application::slotDeleteDocument (const App::Document & Doc) protected
References Gui::SelectionSingleton::clearCompleteSelection(), Base::Console(), App::Document::getName(), Base::ConsoleSingleton::Log(), and Gui::Selection().
Referenced by Application().
slotInEdit()
void Application::slotInEdit (const Gui::ViewProviderDocumentObject & vp) protected
Referenced by slotNewDocument().
slotNewDocument()
void Application::slotNewDocument (const App::Document & Doc, bool isMainDoc) protected
Observer message from the Application.
References draftgeoutils.faces::bind(), Gui::Document::createView(), Base::BaseClass::getClassTypeId(), Gui::Document::signalActivatedObject, Gui::Document::signalChangedObject, Gui::Document::signalDeletedObject, Gui::Document::signalInEdit, Gui::Document::signalNewObject, Gui::Document::signalRelabelObject, Gui::Document::signalResetEdit, slotActivatedObject(), slotChangedObject(), slotDeletedObject(), slotInEdit(), slotNewObject(), slotRelabelObject(), and slotResetEdit().
Referenced by Application().
slotNewObject()
void Application::slotNewObject (const ViewProvider & vp) protected
Referenced by slotNewDocument().
slotRelabelDocument()
void Application::slotRelabelDocument (const App::Document & Doc) protected
Referenced by Application().
slotRelabelObject()
void Application::slotRelabelObject (const ViewProvider & vp) protected
Referenced by slotNewDocument().
slotRenameDocument()
void Application::slotRenameDocument (const App::Document & Doc) protected
Referenced by Application().
slotResetEdit()
void Application::slotResetEdit (const Gui::ViewProviderDocumentObject & vp) protected
Referenced by slotNewDocument().
slotShowHidden()
void Application::slotShowHidden (const App::Document & Doc) protected
Referenced by Application().
sOpen()
PyObject * Application::sOpen (PyObject * self, PyObject * args) static
References activeDocument(), Gui::MainWindow::addWindow(), Gui::BitmapFactory(), Base::Console(), Base::ConsoleSingleton::Error(), App::GetApplication(), Gui::getMainWindow(), Instance, Base::Interpreter(), App::Application::newDocument(), Gui::EditorView::open(), and Base::InterpreterSingleton::runString().
sReload()
PyObject * Application::sReload (PyObject * self, PyObject * args) static
References App::GetApplication(), getDocument(), Instance, and reopen().
sRemoveDocObserver()
PyObject * Application::sRemoveDocObserver (PyObject * self, PyObject * args) static
References Gui::DocumentObserverPython::removeObserver().
sRemoveWorkbenchHandler()
PyObject * Application::sRemoveWorkbenchHandler (PyObject * self, PyObject * args) static
References Gui::WorkbenchManager::instance(), and Gui::WorkbenchManager::removeWorkbench().
sRunCommand()
PyObject * Application::sRunCommand (PyObject * self, PyObject * args) static
References Base::BaseExceptionFreeCADError, commandManager(), Gui::CommandManager::getCommandByName(), Instance, and Gui::Command::invoke().
sSendActiveView()
PyObject * Application::sSendActiveView (PyObject * self, PyObject * args) static
References Base::Console(), and Base::ConsoleSingleton::Warning().
sSendFocusView()
PyObject * Application::sSendFocusView (PyObject * self, PyObject * args) static
References Base::Console(), and Base::ConsoleSingleton::Warning().
sSetActiveDocument()
PyObject * Gui::Application::sSetActiveDocument (PyObject * self, PyObject * args) static
References Gui::Document::getActiveView(), Gui::getMainWindow(), Gui::MainWindow::setActiveWindow(), and App::DocumentPy::Type.
sSetLocale()
PyObject * Application::sSetLocale (PyObject * self, PyObject * args) static
References Gui::Translator::activateLanguage(), Gui::Translator::instance(), and Gui::Translator::supportedLocales().
sShow()
PyObject * Application::sShow (PyObject * self, PyObject * args) static
References Gui::Document::setShow().
sShowDownloads()
PyObject * Application::sShowDownloads (PyObject * self, PyObject * args) static
References Gui::Dialog::DownloadManager::getInstance().
sShowObject()
PyObject * Application::sShowObject (PyObject * self, PyObject * args) static
References App::DocumentObjectPy::Type.
sShowPreferences()
PyObject * Application::sShowPreferences (PyObject * self, PyObject * args) static
References Gui::Dialog::DlgPreferencesImp::activateGroupPage(), Gui::getMainWindow(), Gui::WaitCursor::restoreCursor(), and Gui::WaitCursor::setWaitCursor().
sSupportedLocales()
PyObject * Application::sSupportedLocales (PyObject * self, PyObject * args) static
References Gui::Translator::instance(), and Gui::Translator::supportedLocales().
sUpdateGui()
PyObject * Application::sUpdateGui (PyObject * self, PyObject * args) static
sUpdateLocale()
PyObject * Application::sUpdateLocale (PyObject * self, PyObject * args) static
References Gui::Translator::instance(), and Gui::Translator::refresh().
tryClose()
void Application::tryClose (QCloseEvent * e)
References App::Application::closeAllDocuments(), App::GetApplication(), and Gui::getMainWindow().
Referenced by Gui::MainWindow::closeEvent().
updateActive()
void Application::updateActive (void)
call update to all views of the active document
viewActivated()
void Application::viewActivated (Gui::MDIView * pcView)
get called if a view gets activated, this manage the whole activation scheme
Gets called if a view gets activated, this manages the whole activation scheme.
References Base::Console(), Gui::BaseView::getGuiDocument(), Gui::BaseView::isPassive(), and Base::ConsoleSingleton::Log().
Referenced by Gui::MainWindow::changeEvent(), and Gui::MainWindow::setActiveWindow().
workbenches()
QStringList Application::workbenches (void) const
References App::Application::Config().
Referenced by Gui::Dialog::DlgCustomToolbars::DlgCustomToolbars(), Gui::Dialog::DlgGeneralImp::DlgGeneralImp(), StartGui::DlgStartPreferencesImp::DlgStartPreferencesImp(), Gui::Dialog::DlgWorkbenchesImp::DlgWorkbenchesImp(), Gui::Dialog::DlgWorkbenchesImp::load_enabled_workbenches(), Gui::WorkbenchGroup::refreshWorkbenchList(), and runApplication().
workbenchIcon()
QPixmap Application::workbenchIcon (const QString & wb) const
References Gui::BitmapFactoryInst::addPixmapToCache(), Gui::BitmapFactory(), and Gui::BitmapFactoryInst::pixmap().
Referenced by Gui::Dialog::DlgCustomToolbars::DlgCustomToolbars(), Gui::Dialog::DlgGeneralImp::DlgGeneralImp(), StartGui::DlgStartPreferencesImp::DlgStartPreferencesImp(), and Gui::WorkbenchGroup::slotAddWorkbench().
workbenchMenuText()
QString Application::workbenchMenuText (const QString & wb) const
Referenced by Gui::Dialog::DlgCustomToolbars::DlgCustomToolbars(), Gui::Dialog::DlgGeneralImp::DlgGeneralImp(), StartGui::DlgStartPreferencesImp::DlgStartPreferencesImp(), and Gui::WorkbenchGroup::slotAddWorkbench().
workbenchToolTip()
QString Application::workbenchToolTip (const QString & wb) const
Referenced by Gui::WorkbenchGroup::slotAddWorkbench().
Member Data Documentation
Instance
Application * Application::Instance = 0L static
some kind of singelton
Referenced by Gui::Dialog::DlgMacroExecuteImp::accept(), Gui::Dialog::DocumentRecovery::accept(), Gui::ElementColors::accept(), DrawingGui::TaskProjection::accept(), FemGui::TaskDlgMeshShapeNetgen::accept(), InspectionGui::VisualInspection::accept(), MeshPartGui::Tessellation::accept(), PartGui::DlgFilletEdges::accept(), PartGui::FaceColors::accept(), PartGui::LoftWidget::accept(), PartGui::SweepWidget::accept(), RobotGui::TaskDlgEdge2Trac::accept(), RobotGui::TaskDlgTrajectoryCompound::accept(), RobotGui::TaskDlgTrajectoryDressUp::accept(), TechDrawGui::TaskCenterLine::accept(), TechDrawGui::TaskCosVertex::accept(), TechDrawGui::TaskDetail::accept(), TechDrawGui::TaskLeaderLine::accept(), TechDrawGui::TaskLineDecor::accept(), TechDrawGui::TaskProjGroup::accept(), TechDrawGui::TaskRichAnno::accept(), Gui::TaskCSysDragger::accept(), Gui::Dialog::TransformStrategy::acceptDataTransform(), PartDesignGui::Workbench::activated(), Gui::PythonGroupCommand::activated(), Gui::MacroCommand::activated(), StdCmdMacroStartDebug::activated(), StdCmdMacroStopDebug::activated(), StdCmdMacroStepOver::activated(), StdCmdMacroStepInto::activated(), StdCmdGroup::activated(), StdViewDockUndockFullscreen::activated(), StdCmdMeasureDistance::activated(), CmdViewMeasureClearAll::activated(), DrawSketchHandlerExternal::activated(), DrawSketchHandlerCarbonCopy::activated(), Gui::RecentFilesAction::activateFile(), Gui::RecentMacrosAction::activateFile(), SketcherGui::ViewProviderSketch::activateHandler(), Gui::GroupCommand::addCommand(), Gui::Dialog::DlgCustomToolbarsImp::addCustomCommand(), Gui::Command::addModule(), Gui::SelectionSingleton::addSelection(), Gui::AlignmentGroup::addView(), Gui::Command::adjustCameraPosition(), Gui::TransactionViewProvider::applyNew(), Gui::Dialog::TransformStrategy::applyViewTransform(), PartDesignGui::assertActivePart(), PartDesignGui::ViewProviderBody::attach(), Gui::BaseView::BaseView(), Gui::Document::beforeDelete(), PendingLine::cancel(), Gui::Dialog::DlgCustomCommandsImp::changeEvent(), Gui::Dialog::DlgCustomKeyboardImp::changeEvent(), Gui::Dialog::DlgCustomToolbars::changeEvent(), Gui::MainWindow::changeEvent(), Gui::View3DInventorViewer::checkGroupOnTop(), Gui::TreeWidget::checkTopParent(), Gui::SelectionSingleton::clearCompleteSelection(), Gui::SelectionSingleton::clearSelection(), MeshGui::ViewProviderMesh::clipMeshCallback(), Gui::MainWindow::closeAllDocuments(), Gui::MainWindow::closeEvent(), Gui::Dialog::TransformStrategy::commitTransform(), Gui::MDITabbar::contextMenuEvent(), Gui::TreeWidget::contextMenuEvent(), SketcherGui::ConstraintView::contextMenuEvent(), Gui::DAG::Model::contextMenuEvent(), TechDrawGui::Grabber3d::copyActiveViewToSvgFile(), Gui::PythonGroupCommand::createAction(), Gui::CreateDocCommands(), Gui::CreateFeatCommands(), Gui::CreateLinkCommands(), Gui::Workbench::createLinkMenu(), Gui::CreateMacroCommands(), Gui::MainWindow::createPopupMenu(), PartGui::DlgPrimitives::createPrimitive(), ReverseEngineeringGui::SegmentationManual::createSegment(), Gui::CreateStdCommands(), Gui::CreateStructureCommands(), Gui::CreateTestCommands(), Gui::CreateViewStdCommands(), Gui::CreateWindowStdCommands(), MeshPartGui::CrossSections::CrossSections(), PartGui::CrossSections::CrossSections(), Gui::MainWindow::customEvent(), Gui::PointMarker::customEvent(), PointsGui::ViewProviderScattered::cut(), PointsGui::ViewProviderStructured::cut(), Gui::DocumentIndex::data(), PartDesignGui::Workbench::deactivated(), SketcherGui::ConstraintView::deleteSelectedItems(), SketcherGui::ElementView::deleteSelectedItems(), MeshGui::RemoveComponents::deleteSelection(), PartDesignGui::WorkflowManager::determineWorkflow(), Gui::Dialog::DlgCustomCommandsImp::DlgCustomCommandsImp(), Gui::Dialog::DlgCustomKeyboardImp::DlgCustomKeyboardImp(), Gui::Dialog::DlgCustomToolbars::DlgCustomToolbars(), Gui::Dialog::DlgDisplayPropertiesImp::DlgDisplayPropertiesImp(), Gui::Dialog::DlgGeneralImp::DlgGeneralImp(), Gui::Dialog::DlgMacroRecordImp::DlgMacroRecordImp(), Gui::DlgObjectSelection::DlgObjectSelection(), StartGui::DlgStartPreferencesImp::DlgStartPreferencesImp(), Gui::Dialog::DlgWorkbenchesImp::DlgWorkbenchesImp(), Gui::SoFCUnifiedSelection::doAction(), Gui::DocumentModel::DocumentModel(), Gui::ViewProviderAnnotationLabel::doubleClicked(), Gui::ViewProviderMaterialObject::doubleClicked(), FemGui::ViewProviderFemPostFunction::doubleClicked(), FemGui::ViewProviderFemPostObject::doubleClicked(), RaytracingGui::ViewProviderLux::doubleClicked(), RaytracingGui::ViewProviderPovray::doubleClicked(), SketcherGui::ViewProviderSketch::doubleClicked(), Gui::ViewProviderDragger::doubleClicked(), Gui::ViewProviderPart::doubleClicked(), PartDesignGui::ViewProviderBody::doubleClicked(), PartDesignGui::ViewProviderDatum::doubleClicked(), SketcherGui::ViewProviderSketch::drawConstraintIcons(), Gui::TreeWidget::dropEvent(), PartDesignGui::ViewProviderBody::dropObject(), Gui::ElementColors::ElementColors(), Gui::SelectionSingleton::enableCommandLog(), PartGui::eraseAllDimensions(), Gui::MainWindow::event(), Gui::GUIApplication::event(), Gui::ViewProvider::eventCallback(), Gui::PythonEditorView::executeScript(), PartDesignGui::TaskBooleanParameters::exitSelectionMode(), Gui::Document::exportObjects(), Gui::ViewProviderOriginGroupExtension::extensionAttach(), Gui::ViewProviderGeoFeatureGroupExtension::extensionClaimChildren(), PartGui::FaceColors::FaceColors(), MeshGui::ViewProviderMesh::fillHole(), ExportOCAFGui::findColors(), Gui::ViewProviderDocumentObject::findFrontRootOfType(), ReverseEngineeringGui::SegmentationManual::Private::findGeometry(), PartGui::DlgExtrusion::findShapes(), TechDrawGui::DrawGuiUtil::get3DDirAndRot(), PartDesignGui::getActivePart(), Gui::ViewProviderDocumentObject::getActiveView(), Gui::DocumentT::getAppDocumentPython(), PartDesignGui::getBody(), Gui::ViewProvider::getBoundingBox(), Gui::LinkInfo::getDetail(), Gui::ViewProviderDocumentObject::getDetailPath(), Gui::DocumentT::getDocument(), Gui::ViewProviderT::getDocument(), Gui::AlignmentGroup::getDocument(), Gui::ViewProviderDocumentObject::getDocument(), SketcherGui::ViewProviderSketch::getEditingPlacement(), Gui::ViewProviderDocumentObject::getEditingView(), Gui::ViewProviderLink::getElementColors(), TechDrawGui::QGIView::getFrameState(), Gui::Command::getGuiApplication(), Gui::DocumentT::getGuiDocumentPython(), InspectionGui::ViewProviderInspection::getIcon(), Gui::ViewProviderDocumentObject::getInventorView(), Gui::ViewProviderLink::getLinkedView(), Gui::ViewProviderDocumentObject::getLinkedViewProvider(), Gui::ViewProviderLink::getLinkedViewProvider(), TechDrawGui::ViewProviderGeomHatch::getMDIView(), TechDrawGui::ViewProviderHatch::getMDIView(), TechDrawGui::ViewProviderDrawingView::getMDIViewPage(), TechDrawGui::ViewProviderTemplate::getMDIViewPage(), Gui::ViewProviderT::getObjectPython(), TechDrawGui::ViewProviderDrawingView::getQView(), PartDesignGui::ViewProviderDatum::getRelevantBoundBox(), SketcherGui::ViewProviderSketch::getScaleFactor(), Gui::LinkInfo::getView(), PartGui::getViewer(), MeshGui::MeshSelection::getViewer(), Gui::ViewProviderDocumentObject::getViewOfNode(), Gui::DocumentItem::getViewProvider(), TechDrawGui::QGIView::getViewProvider(), MeshGui::MeshSelection::getViewProviders(), Gui::ViewProviderDocumentObjectGroup::getViewProviders(), Gui::Dialog::CommandModel::goAddMacro(), PartGui::TaskCheckGeometryResults::goCheck(), SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), PartDesignGui::ViewProviderDressUp::highlightReferences(), PartDesignGui::ViewProviderShapeBinder::highlightReferences(), SurfaceGui::ViewProviderFilling::highlightReferences(), SurfaceGui::ViewProviderSections::highlightReferences(), Gui::ViewProviderLink::initDraggingPlacement(), Gui::MainWindow::insertFromMimeData(), StdCmdMacroStopDebug::isActive(), StdCmdMacroStepOver::isActive(), StdCmdMacroStepInto::isActive(), StdCmdDrawStyle::isActive(), Gui::Command::isActiveObjectValid(), Gui::TreeWidget::isObjectShowable(), Gui::TreeWidget::itemSearch(), Gui::TaskView::TaskView::keyPressEvent(), Gui::PythonGroupCommand::languageChange(), Gui::MacroCommand::load(), Gui::Dialog::DlgWorkbenchesImp::load_enabled_workbenches(), TechDrawGui::TaskLinkDim::loadAvailDims(), Gui::MainWindow::loadUrls(), PartDesignGui::makeBody(), Gui::ManualAlignment::ManualAlignment(), MeshGui::ViewProviderMesh::markPartCallback(), Gui::MergeDocuments::MergeDocuments(), SketcherGui::ViewProviderSketch::mouseButtonPressed(), Gui::DAG::Model::mouseDoubleClickEvent(), Gui::TreeView::mouseDoubleClickEvent(), Gui::TreeWidget::mouseDoubleClickEvent(), Gui::Dialog::DlgCustomActionsImp::on_actionListWidget_itemActivated(), Gui::Dialog::DlgMacroExecuteImp::on_addonsButton_clicked(), Gui::Dialog::DlgCustomActionsImp::on_buttonAddAction_clicked(), Gui::Dialog::DlgCustomActionsImp::on_buttonRemoveAction_clicked(), Gui::Dialog::DlgCustomActionsImp::on_buttonReplaceAction_clicked(), Gui::Dialog::DlgCustomKeyboardImp::on_buttonReset_clicked(), Gui::Dialog::DlgCustomKeyboardImp::on_buttonResetAll_clicked(), Gui::Dialog::DlgCustomKeyboardImp::on_categoryBox_activated(), Gui::Dialog::DlgCustomToolbars::on_categoryBox_activated(), Gui::Dialog::DlgCustomKeyboardImp::on_commandTreeWidget_currentItemChanged(), MeshGui::DlgRegularSolidImp::on_createSolidButton_clicked(), Gui::Dialog::DlgCustomKeyboardImp::on_editShortcut_textChanged(), Gui::Dialog::DemoMode::on_fullscreen_toggled(), SketcherGui::TaskSketcherConstrains::on_listWidgetConstraints_updateActiveStatus(), SketcherGui::TaskSketcherConstrains::on_listWidgetConstraints_updateDrivingStatus(), MeshGui::DlgEvaluateMeshImp::on_refreshButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairAllTogether_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairDegeneratedButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairDuplicatedFacesButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairDuplicatedPointsButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairFoldsButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairIndicesButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairNonmanifoldsButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairOrientationButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairSelfIntersectionButton_clicked(), Gui::Dialog::DlgMacroExecuteImp::on_toolbarButton_clicked(), Gui::TreeWidget::onActivateDocument(), Gui::Dialog::DlgCustomCommandsImp::onAddMacroAction(), Gui::Dialog::DlgCustomKeyboardImp::onAddMacroAction(), Gui::Dialog::DlgCustomToolbars::onAddMacroAction(), Gui::ViewProvider::onBeforeChange(), FemGui::TaskFemConstraint::onButtonWizOk(), Gui::ViewProvider::onChanged(), Gui::ViewProviderOrigin::onChanged(), PartDesignGui::ViewProvider::onChanged(), Gui::BaseView::onClose(), PartGui::ViewProviderBoolean::onDelete(), PartGui::ViewProviderMultiFuse::onDelete(), PartGui::ViewProviderMultiCommon::onDelete(), PartGui::ViewProviderCompound::onDelete(), PartGui::ViewProviderMirror::onDelete(), PartGui::ViewProviderFillet::onDelete(), PartGui::ViewProviderChamfer::onDelete(), PartGui::ViewProviderRevolution::onDelete(), PartGui::ViewProviderOffset::onDelete(), PartGui::ViewProviderThickness::onDelete(), PartGui::ViewProviderRuledSurface::onDelete(), PartDesignGui::ViewProviderSketchBased::onDelete(), PathGui::ViewProviderArea::onDelete(), PathGui::ViewProviderAreaView::onDelete(), PathGui::ViewProviderPathShape::onDelete(), PartDesignGui::ViewProvider::onDelete(), PartDesignGui::ViewProviderBoolean::onDelete(), PartDesignGui::ViewProviderHole::onDelete(), Gui::TreeWidget::onFinishEditing(), Gui::Dialog::DlgCustomCommandsImp::onGroupActivated(), Gui::Dialog::DlgCustomCommandsImp::onModifyMacroAction(), Gui::Dialog::DlgCustomKeyboardImp::onModifyMacroAction(), Gui::Dialog::DlgCustomToolbars::onModifyMacroAction(), Gui::TreeWidget::onReloadDoc(), Gui::Dialog::UndoDialog::onSelected(), Gui::Dialog::RedoDialog::onSelected(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), PathGui::PathSelectionObserver::onSelectionChanged(), Gui::PropertyView::onTimer(), PartGui::TaskDlgAttacher::open(), PartGui::FaceColors::open(), Gui::TaskCSysDragger::open(), Gui::NavigationStyle::openPopupMenu(), PartGui::PropertyEnumAttacherItem::openTask(), DrawingGui::OrthoViews::OrthoViews(), MeshGui::ViewProviderMesh::partMeshCallback(), PendingLine::PendingLine(), Gui::Dialog::Placement::Placement(), Gui::Command::printCaller(), PartGui::FaceColors::Private::Private(), Gui::PropertyView::PropertyView(), SketcherGui::ViewProviderSketch::purgeHandler(), Gui::PythonEditorP::PythonEditorP(), Gui::WorkbenchGroup::refreshWorkbenchList(), Gui::ElementColors::reject(), PartGui::FaceColors::reject(), PartGui::OffsetWidget::reject(), PartGui::ThicknessWidget::reject(), PartDesignGui::TaskDlgBooleanParameters::reject(), PartDesignGui::TaskDlgFeatureParameters::reject(), PartDesignGui::TaskDlgSketchBasedParameters::reject(), RobotGui::TaskDlgTrajectoryCompound::reject(), RobotGui::TaskDlgTrajectoryDressUp::reject(), TechDrawGui::TaskCenterLine::reject(), TechDrawGui::TaskCosVertex::reject(), TechDrawGui::TaskDetail::reject(), TechDrawGui::TaskLeaderLine::reject(), TechDrawGui::TaskLineDecor::reject(), TechDrawGui::TaskProjGroup::reject(), TechDrawGui::TaskRichAnno::reject(), TechDrawGui::TaskLeaderLine::removeFeature(), TechDrawGui::TaskRichAnno::removeFeature(), Gui::Document::resetEdit(), Gui::Dialog::TransformStrategy::resetViewTransform(), Gui::SelectionSingleton::rmvPreselect(), Gui::SelectionSingleton::rmvSelectionGate(), sAddCommand(), Gui::MacroCommand::save(), Gui::Document::save(), Gui::Document::saveAll(), Gui::Dialog::DlgGeneralImp::saveSettings(), PartGui::DlgSettings3DViewPart::saveSettings(), Gui::TreeWidget::scrollItemToTop(), sDoCommand(), sDoCommandGui(), SketcherGui::ViewProviderSketch::seekConstraintPosition(), MeshGui::ViewProviderMesh::segmMeshCallback(), Gui::TreeWidget::selectAll(), Gui::TreeWidget::selectAllLinks(), Gui::TreeWidget::selectLinkedObject(), FemGui::ActiveAnalysisObserver::setActiveObject(), Gui::Document::setActiveView(), Gui::MainWindow::setActiveWindow(), SpreadsheetGui::WorkbenchHelper::setBackgroundColor(), PartDesignGui::setEdit(), Gui::Document::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), Gui::DocumentPy::setEdit(), SurfaceGui::FillingPanel::setEditedObject(), SurfaceGui::FillingEdgePanel::setEditedObject(), SurfaceGui::FillingVertexPanel::setEditedObject(), SurfaceGui::GeomFillSurface::setEditedObject(), SurfaceGui::SectionsPanel::setEditedObject(), SketcherGui::ViewProviderSketch::setEditViewer(), SpreadsheetGui::WorkbenchHelper::setForegroundColor(), Gui::LinkView::setLink(), Gui::ViewProviderLink::setOverrideMode(), Gui::SelectionSingleton::setPreselect(), PartDesignGui::ViewProviderAddSub::setPreviewDisplayMode(), Gui::Dialog::DlgCustomKeyboardImp::setShortcutOfCurrentAction(), TechDrawGui::ViewProviderPage::setTemplateMarkers(), Gui::ViewProviderOrigin::setTemporaryVisibility(), Gui::ToolBoxManager::setup(), Gui::ToolBarManager::setup(), PartDesignGui::Workbench::setupContextMenu(), PartGui::DlgFilletEdges::setupFillet(), MeshGui::Workbench::setupMenuBar(), PartDesignGui::Workbench::setupMenuBar(), Gui::SelectionSingleton::setVisible(), PartDesignGui::ViewProviderBody::setVisualBodyMode(), sExport(), DrawingGui::ViewProviderDrawingPage::showDrawingView(), TechDrawGui::ViewProviderPage::showMDIViewPage(), SpreadsheetGui::ViewProviderSheet::showSpreadsheetView(), sLoadFile(), Gui::WorkbenchGroup::slotAddWorkbench(), Gui::Document::slotDeletedObject(), Gui::DocumentItem::slotExpandObject(), Gui::DocumentItem::slotHighlightObject(), Gui::DocumentItem::slotInEdit(), Gui::Document::slotShowHidden(), Gui::Document::slotSkipRecompute(), sOpen(), sReload(), sRunCommand(), Gui::ViewProviderLink::startEditing(), PartDesignGui::ViewProviderTransformed::startEditing(), Gui::TreeWidget::startItemSearch(), Gui::TaskView::TaskAppearance::TaskAppearance(), PartGui::TaskAttacher::TaskAttacher(), PartDesignGui::TaskBoxPrimitives::TaskBoxPrimitives(), TechDrawGui::TaskCosVertex::TaskCosVertex(), FemGui::TaskCreateNodeSet::TaskCreateNodeSet(), TechDrawGui::TaskDetail::TaskDetail(), PartDesignGui::TaskFeaturePick::TaskFeaturePick(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), PartDesignGui::TaskLoftParameters::TaskLoftParameters(), SandboxGui::TaskPanelView::TaskPanelView(), PartDesignGui::TaskPipeOrientation::TaskPipeOrientation(), PartDesignGui::TaskPipeScaling::TaskPipeScaling(), FemGui::TaskPostClip::TaskPostClip(), FemGui::TaskPostCut::TaskPostCut(), TechDrawGui::TaskProjGroup::TaskProjGroup(), PartDesignGui::TaskRevolutionParameters::TaskRevolutionParameters(), TechDrawGui::TaskRichAnno::TaskRichAnno(), PartDesignGui::TaskShapeBinder::TaskShapeBinder(), SketcherGui::TaskSketcherGeneral::TaskSketcherGeneral(), RobotGui::TaskTrajectory::TaskTrajectory(), Gui::TaskView::TaskWatcherCommands::TaskWatcherCommands(), Gui::TaskView::TaskWatcherPython::TaskWatcherPython(), Gui::Command::testActive(), RobotGui::TrajectorySimulate::TrajectorySimulate(), Gui::TreeWidget::TreeWidget(), MeshGui::ViewProviderMesh::trimMeshCallback(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), PartDesignGui::ViewProvider::unsetEdit(), Gui::Command::updateAll(), DrawingGui::ViewProviderDrawingPage::updateData(), MeshGui::ViewProviderMeshCurvature::updateData(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderMultiFuse::updateData(), PartGui::ViewProviderMultiCommon::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderFillet::updateData(), PartGui::ViewProviderChamfer::updateData(), PathGui::ViewProviderArea::updateData(), PathGui::ViewProviderAreaView::updateData(), PathGui::ViewProviderPathShape::updateData(), RobotGui::ViewProviderRobotObject::updateData(), SketcherGui::ViewProviderSketch::updateData(), PartDesignGui::ViewProviderBody::updateData(), Gui::ViewProviderLink::updateDataPrivate(), Gui::MainWindow::updateEditorActions(), Gui::ViewProviderLink::updateElementList(), FemGui::ViewProviderFemPostPipeline::updateFunctionSize(), TechDrawGui::ViewProviderGeomHatch::updateGraphic(), PartDesignGui::ViewProviderBody::updateOriginDatumSize(), Gui::ViewProviderOriginGroupExtension::updateOriginSize(), FemGui::ViewProviderFemPostFunctionProvider::updateSize(), Gui::DAG::View::View(), Gui::View3DInventorViewer::viewSelection(), InspectionGui::VisualInspection::VisualInspection(), Gui::WorkbenchGroup::WorkbenchGroup(), PartGui::DlgProjectionOnSurface::~DlgProjectionOnSurface(), SpreadsheetGui::SheetView::~SheetView(), PartDesignGui::TaskBoxPrimitives::~TaskBoxPrimitives(), Gui::TaskCSysDragger::~TaskCSysDragger(), PartDesignGui::TaskLinearPatternParameters::~TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::~TaskMirroredParameters(), PartDesignGui::TaskPolarPatternParameters::~TaskPolarPatternParameters(), PartDesignGui::TaskRevolutionParameters::~TaskRevolutionParameters(), and Gui::DAG::View::~View().
Methods
PyMethodDef Application::Methods static
Referenced by Application().
signalActivatedObject
boost::signals2::signal<void (const Gui::ViewProvider&)> Gui::Application::signalActivatedObject
signal on activated Object
signalActivateView
boost::signals2::signal<void (const Gui::MDIView*)> Gui::Application::signalActivateView
signal on activating view
Referenced by StdCmdDrawStyle::StdCmdDrawStyle().
signalActivateWorkbench
boost::signals2::signal<void (const char*)> Gui::Application::signalActivateWorkbench
signal on activated workbench
Referenced by Gui::WorkbenchGroup::WorkbenchGroup().
signalActiveDocument
boost::signals2::signal<void (const Gui::Document&)> Gui::Application::signalActiveDocument
signal on activating Document
Referenced by PartDesignGui::Workbench::activated(), PartDesignGui::Workbench::deactivated(), Gui::DocumentModel::DocumentModel(), Gui::Dialog::Placement::Placement(), Gui::PropertyView::PropertyView(), Gui::TreeWidget::TreeWidget(), Gui::DAG::View::View(), and Gui::DAG::View::~View().
signalAddWorkbench
boost::signals2::signal<void (const char*)> Gui::Application::signalAddWorkbench
signal on added workbench
Referenced by Gui::WorkbenchGroup::WorkbenchGroup().
signalBeforeChangeObject
boost::signals2::signal<void (const Gui::ViewProvider&, const App::Property&)> Gui::Application::signalBeforeChangeObject
signal on changed Object
Referenced by Gui::ViewProvider::onBeforeChange().
signalChangedObject
boost::signals2::signal<void (const Gui::ViewProvider&, const App::Property&)> Gui::Application::signalChangedObject
signal on changed object property
Referenced by Gui::Dialog::DlgDisplayPropertiesImp::DlgDisplayPropertiesImp(), Gui::ViewProvider::onChanged(), Gui::PropertyView::PropertyView(), Gui::TaskView::TaskAppearance::TaskAppearance(), SketcherGui::TaskSketcherGeneral::TaskSketcherGeneral(), and Gui::TreeWidget::TreeWidget().
signalDeletedObject
boost::signals2::signal<void (const Gui::ViewProvider&)> Gui::Application::signalDeletedObject
signal on deleted Object
Referenced by Gui::ElementColors::ElementColors(), PartGui::FaceColors::FaceColors(), and Gui::PropertyView::PropertyView().
signalDeleteDocument
boost::signals2::signal<void (const Gui::Document&)> Gui::Application::signalDeleteDocument
signal on deleted Document
Referenced by Gui::DocumentModel::DocumentModel(), Gui::ElementColors::ElementColors(), PartGui::FaceColors::FaceColors(), Gui::ManualAlignment::ManualAlignment(), Gui::PropertyView::PropertyView(), Gui::TreeWidget::TreeWidget(), Gui::DAG::View::View(), and Gui::DAG::View::~View().
signalInEdit
boost::signals2::signal<void (const Gui::ViewProviderDocumentObject&)> Gui::Application::signalInEdit
signal on entering in edit mode
signalNewDocument
boost::signals2::signal<void (const Gui::Document&, bool)> Gui::Application::signalNewDocument
signal on new Document
Referenced by Gui::DocumentModel::DocumentModel(), and Gui::TreeWidget::TreeWidget().
signalNewObject
boost::signals2::signal<void (const Gui::ViewProvider&)> Gui::Application::signalNewObject
signal on new Object
signalRelabelDocument
boost::signals2::signal<void (const Gui::Document&)> Gui::Application::signalRelabelDocument
signal on relabeling Document
Referenced by Gui::DocumentModel::DocumentModel(), and Gui::TreeWidget::TreeWidget().
signalRelabelObject
boost::signals2::signal<void (const Gui::ViewProvider&)> Gui::Application::signalRelabelObject
signal on renamed Object
signalRemoveWorkbench
boost::signals2::signal<void (const char*)> Gui::Application::signalRemoveWorkbench
signal on removed workbench
Referenced by Gui::WorkbenchGroup::WorkbenchGroup().
signalRenameDocument
boost::signals2::signal<void (const Gui::Document&)> Gui::Application::signalRenameDocument
signal on renaming Document
Referenced by Gui::DocumentModel::DocumentModel(), and Gui::TreeWidget::TreeWidget().
signalResetEdit
boost::signals2::signal<void (const Gui::ViewProviderDocumentObject&)> Gui::Application::signalResetEdit
signal on leaving edit mode
signalShowHidden
boost::signals2::signal<void (const Gui::Document&)> Gui::Application::signalShowHidden
signal on show hidden items
Referenced by Gui::Document::slotShowHidden(), and Gui::TreeWidget::TreeWidget().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Application.h
Sources/FreeCAD/src/Gui/Application.cpp
Sources/FreeCAD/src/Gui/ApplicationPy.cpp