FreeCAD: VISCOUS_3D::AverageHyp Struct Reference
VISCOUS_3D::AverageHyp Struct Reference
Layers parameters got by averaging several hypotheses.
Public Member Functions
void Add (const StdMeshers_ViscousLayers *hyp)
AverageHyp (const StdMeshers_ViscousLayers *hyp=0)
int GetMethod () const
int GetNumberLayers () const
double GetStretchFactor () const
double GetTotalThickness () const
bool IsOffsetMethod () const
bool ToSmooth () const
bool UseSurfaceNormal () const
Detailed Description
Layers parameters got by averaging several hypotheses.
Constructor & Destructor Documentation
AverageHyp()
VISCOUS_3D::AverageHyp::AverageHyp (const StdMeshers_ViscousLayers * hyp = 0)
Member Function Documentation
Add()
void VISCOUS_3D::AverageHyp::Add (const StdMeshers_ViscousLayers * hyp)
References StdMeshers_ViscousLayers::GetMethod(), StdMeshers_ViscousLayers::GetNumberLayers(), StdMeshers_ViscousLayers::GetStretchFactor(), and StdMeshers_ViscousLayers::GetTotalThickness().
GetMethod()
int VISCOUS_3D::AverageHyp::GetMethod () const
GetNumberLayers()
int VISCOUS_3D::AverageHyp::GetNumberLayers () const
GetStretchFactor()
double VISCOUS_3D::AverageHyp::GetStretchFactor () const
GetTotalThickness()
double VISCOUS_3D::AverageHyp::GetTotalThickness () const
IsOffsetMethod()
bool VISCOUS_3D::AverageHyp::IsOffsetMethod () const
References StdMeshers_ViscousLayers::FACE_OFFSET.
ToSmooth()
bool VISCOUS_3D::AverageHyp::ToSmooth () const
References StdMeshers_ViscousLayers::SURF_OFFSET_SMOOTH.
UseSurfaceNormal()
bool VISCOUS_3D::AverageHyp::UseSurfaceNormal () const
References StdMeshers_ViscousLayers::SURF_OFFSET_SMOOTH.
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_ViscousLayers.cpp