FreeCAD: TechDrawGui::QGVNavStyle Class Reference
TechDrawGui::QGVNavStyle Class Reference
#include <QGVNavStyle.h>
Public Member Functions
virtual bool allowContextMenu (QContextMenuEvent *event)
QGVPage * getViewer ()
virtual void handleEnterEvent (QEvent *event)
virtual void handleFocusOutEvent (QFocusEvent *event)
virtual void handleKeyPressEvent (QKeyEvent *event)
virtual void handleKeyReleaseEvent (QKeyEvent *event)
virtual void handleLeaveEvent (QEvent *event)
virtual void handleMouseMoveEvent (QMouseEvent *event)
virtual void handleMousePressEvent (QMouseEvent *event)
virtual void handleMouseReleaseEvent (QMouseEvent *event)
virtual void handleWheelEvent (QWheelEvent *event)
virtual double mouseZoomFactor (QPoint p)
virtual void pan (QPoint p)
virtual void placeBalloon (QPoint p)
virtual void pseudoContextEvent ()
QGVNavStyle (QGVPage *qgvp)
void setViewer (QGVPage *qgvp)
virtual void startClick (Qt::MouseButton b)
virtual void startPan (QPoint p)
virtual void startZoom (QPoint p)
virtual void stopClick (void)
virtual void stopPan ()
virtual void stopZoom ()
virtual void zoom (double factor)
virtual ~QGVNavStyle ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Member Functions
virtual void initialize ()
virtual void setAnchor ()
Protected Attributes
bool altdown
bool button1down
bool button2down
bool button3down
bool ctrldown
bool invertZoom
Qt::MouseButton m_clickButton
bool m_clickPending
int m_currentmode
KeyCombination m_keyCombo
bool m_panPending
int m_reversePan
int m_reverseScroll
QCursor m_saveCursor
QGVPage * m_viewer
bool m_zoomPending
bool panningActive
QPoint panOrigin
bool shiftdown
bool zoomAtCursor
bool zoomingActive
QPoint zoomOrigin
double zoomStep
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
QGVNavStyle()
TechDrawGui::QGVNavStyle::QGVNavStyle (QGVPage * qgvp)
References initialize().
~QGVNavStyle()
TechDrawGui::QGVNavStyle::~QGVNavStyle () virtual
Member Function Documentation
allowContextMenu()
bool TechDrawGui::QGVNavStyle::allowContextMenu (QContextMenuEvent * event) virtual
Reimplemented in TechDrawGui::QGVNavStyleBlender, TechDrawGui::QGVNavStyleCAD, TechDrawGui::QGVNavStyleGesture, TechDrawGui::QGVNavStyleMaya, TechDrawGui::QGVNavStyleOCC, TechDrawGui::QGVNavStyleOpenSCAD, and TechDrawGui::QGVNavStyleRevit.
Referenced by TechDrawGui::QGVPage::contextMenuEvent().
getViewer()
QGVPage * TechDrawGui::QGVNavStyle::getViewer (void)
Referenced by handleEnterEvent(), handleFocusOutEvent(), handleKeyPressEvent(), handleLeaveEvent(), handleMouseMoveEvent(), TechDrawGui::QGVNavStyleBlender::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTinkerCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent(), handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleBlender::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleTinkerCAD::handleMouseReleaseEvent(), initialize(), pan(), placeBalloon(), pseudoContextEvent(), startPan(), startZoom(), stopPan(), stopZoom(), and zoom().
handleEnterEvent()
void TechDrawGui::QGVNavStyle::handleEnterEvent (QEvent * event) virtual
References TechDrawGui::QGVPage::getBalloonCursor(), and getViewer().
Referenced by TechDrawGui::QGVPage::enterEvent().
handleFocusOutEvent()
void TechDrawGui::QGVNavStyle::handleFocusOutEvent (QFocusEvent * event) virtual
References TechDrawGui::QGVPage::cancelBalloonPlacing(), and getViewer().
Referenced by TechDrawGui::QGVPage::focusOutEvent().
handleKeyPressEvent()
void TechDrawGui::QGVNavStyle::handleKeyPressEvent (QKeyEvent * event) virtual
Reimplemented in TechDrawGui::QGVNavStyleTouchpad.
References TechDrawGui::QGVPage::cancelBalloonPlacing(), Base::Console(), getViewer(), TechDrawGui::QGVPage::kbPanScroll(), Base::ConsoleSingleton::Message(), shiftdown, zoom(), and zoomStep.
Referenced by TechDrawGui::QGVPage::keyPressEvent().
handleKeyReleaseEvent()
void TechDrawGui::QGVNavStyle::handleKeyReleaseEvent (QKeyEvent * event) virtual
Reimplemented in TechDrawGui::QGVNavStyleBlender, TechDrawGui::QGVNavStyleCAD, TechDrawGui::QGVNavStyleMaya, TechDrawGui::QGVNavStyleOCC, TechDrawGui::QGVNavStyleOpenSCAD, and TechDrawGui::QGVNavStyleTouchpad.
References Base::Console(), Base::ConsoleSingleton::Message(), and shiftdown.
Referenced by TechDrawGui::QGVPage::keyReleaseEvent().
handleLeaveEvent()
void TechDrawGui::QGVNavStyle::handleLeaveEvent (QEvent * event) virtual
References TechDrawGui::QGVPage::getBalloonCursor(), TechDrawGui::QGVPage::getBalloonCursorPos(), and getViewer().
Referenced by TechDrawGui::QGVPage::leaveEvent().
handleMouseMoveEvent()
void TechDrawGui::QGVNavStyle::handleMouseMoveEvent (QMouseEvent * event) virtual
Reimplemented in TechDrawGui::QGVNavStyleBlender, TechDrawGui::QGVNavStyleCAD, TechDrawGui::QGVNavStyleGesture, TechDrawGui::QGVNavStyleInventor, TechDrawGui::QGVNavStyleMaya, TechDrawGui::QGVNavStyleOCC, TechDrawGui::QGVNavStyleOpenSCAD, TechDrawGui::QGVNavStyleRevit, TechDrawGui::QGVNavStyleTinkerCAD, and TechDrawGui::QGVNavStyleTouchpad.
References getViewer(), pan(), panningActive, and TechDrawGui::QGVPage::setBalloonCursorPos().
Referenced by TechDrawGui::QGVPage::mouseMoveEvent().
handleMousePressEvent()
void TechDrawGui::QGVNavStyle::handleMousePressEvent (QMouseEvent * event) virtual
Reimplemented in TechDrawGui::QGVNavStyleBlender, TechDrawGui::QGVNavStyleCAD, TechDrawGui::QGVNavStyleGesture, TechDrawGui::QGVNavStyleInventor, TechDrawGui::QGVNavStyleMaya, TechDrawGui::QGVNavStyleOCC, TechDrawGui::QGVNavStyleOpenSCAD, TechDrawGui::QGVNavStyleRevit, and TechDrawGui::QGVNavStyleTinkerCAD.
References panningActive, and startPan().
Referenced by TechDrawGui::QGVPage::mousePressEvent().
handleMouseReleaseEvent()
void TechDrawGui::QGVNavStyle::handleMouseReleaseEvent (QMouseEvent * event) virtual
Reimplemented in TechDrawGui::QGVNavStyleBlender, TechDrawGui::QGVNavStyleCAD, TechDrawGui::QGVNavStyleGesture, TechDrawGui::QGVNavStyleInventor, TechDrawGui::QGVNavStyleMaya, TechDrawGui::QGVNavStyleOCC, TechDrawGui::QGVNavStyleOpenSCAD, TechDrawGui::QGVNavStyleRevit, and TechDrawGui::QGVNavStyleTinkerCAD.
References getViewer(), panningActive, placeBalloon(), and stopPan().
Referenced by TechDrawGui::QGVPage::mouseReleaseEvent().
handleWheelEvent()
void TechDrawGui::QGVNavStyle::handleWheelEvent (QWheelEvent * event) virtual
References invertZoom, and zoom().
Referenced by TechDrawGui::QGVPage::wheelEvent().
initialize()
void TechDrawGui::QGVNavStyle::initialize (void) protected virtual
References altdown, button1down, button2down, button3down, ctrldown, App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), App::Application::GetUserParameter(), getViewer(), invertZoom, m_clickButton, m_clickPending, m_panPending, m_reversePan, m_reverseScroll, m_saveCursor, m_zoomPending, panningActive, shiftdown, zoomAtCursor, zoomingActive, and zoomStep.
Referenced by QGVNavStyle().
mouseZoomFactor()
double TechDrawGui::QGVNavStyle::mouseZoomFactor (QPoint p) virtual
References draftgeoutils.edges::invert(), invertZoom, zoomOrigin, and zoomStep.
Referenced by TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), and TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent().
pan()
void TechDrawGui::QGVNavStyle::pan (QPoint p) virtual
References getViewer(), m_reversePan, m_reverseScroll, and panOrigin.
Referenced by handleMouseMoveEvent(), TechDrawGui::QGVNavStyleBlender::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTinkerCAD::handleMouseMoveEvent(), and TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent().
placeBalloon()
void TechDrawGui::QGVNavStyle::placeBalloon (QPoint p) virtual
References TechDrawGui::QGSPage::createBalloon(), TechDrawGui::QGVPage::getBalloonCursor(), TechDrawGui::QGVPage::getScene(), getViewer(), and TechDrawGui::QGVPage::setBalloonPlacing().
Referenced by handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleBlender::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseReleaseEvent(), and TechDrawGui::QGVNavStyleTinkerCAD::handleMouseReleaseEvent().
pseudoContextEvent()
void TechDrawGui::QGVNavStyle::pseudoContextEvent () virtual
References getViewer(), and TechDrawGui::QGVPage::pseudoContextEvent().
Referenced by TechDrawGui::QGVNavStyleGesture::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), and TechDrawGui::QGVNavStyleRevit::handleMouseReleaseEvent().
setAnchor()
void TechDrawGui::QGVNavStyle::setAnchor () protected virtual
Reimplemented in TechDrawGui::QGVNavStyleTouchpad.
References m_viewer, and zoomAtCursor.
setViewer()
void TechDrawGui::QGVNavStyle::setViewer (QGVPage * qgvp)
startClick()
void TechDrawGui::QGVNavStyle::startClick (Qt::MouseButton b) virtual
References m_clickButton, and m_clickPending.
Referenced by TechDrawGui::QGVNavStyleCAD::handleMousePressEvent(), TechDrawGui::QGVNavStyleGesture::handleMousePressEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMousePressEvent(), and TechDrawGui::QGVNavStyleRevit::handleMousePressEvent().
startPan()
void TechDrawGui::QGVNavStyle::startPan (QPoint p) virtual
References getViewer(), m_panPending, panningActive, panOrigin, and TechDrawGui::QGVPage::setPanCursor().
Referenced by TechDrawGui::QGVNavStyleBlender::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTinkerCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent(), and handleMousePressEvent().
startZoom()
void TechDrawGui::QGVNavStyle::startZoom (QPoint p) virtual
References getViewer(), m_zoomPending, TechDrawGui::QGVPage::setZoomCursor(), zoomingActive, and zoomOrigin.
Referenced by TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), and TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent().
stopClick()
void TechDrawGui::QGVNavStyle::stopClick (void) virtual
References m_clickButton, and m_clickPending.
Referenced by TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), and TechDrawGui::QGVNavStyleRevit::handleMouseReleaseEvent().
stopPan()
void TechDrawGui::QGVNavStyle::stopPan () virtual
References getViewer(), m_panPending, panningActive, and TechDrawGui::QGVPage::resetCursor().
Referenced by TechDrawGui::QGVNavStyleBlender::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleCAD::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleMaya::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleTouchpad::handleKeyReleaseEvent(), handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleBlender::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseReleaseEvent(), and TechDrawGui::QGVNavStyleTinkerCAD::handleMouseReleaseEvent().
stopZoom()
void TechDrawGui::QGVNavStyle::stopZoom () virtual
References getViewer(), m_zoomPending, TechDrawGui::QGVPage::resetCursor(), and zoomingActive.
Referenced by TechDrawGui::QGVNavStyleCAD::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleTouchpad::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseReleaseEvent(), and TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent().
zoom()
void TechDrawGui::QGVNavStyle::zoom (double factor) virtual
References getViewer(), and m_zoomPending.
Referenced by handleKeyPressEvent(), TechDrawGui::QGVNavStyleTouchpad::handleKeyPressEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent(), and handleWheelEvent().
Member Data Documentation
altdown
bool TechDrawGui::QGVNavStyle::altdown protected
Referenced by draftguitools.gui_dimensions.Dimension::action(), and initialize().
button1down
bool TechDrawGui::QGVNavStyle::button1down protected
Referenced by initialize().
button2down
bool TechDrawGui::QGVNavStyle::button2down protected
Referenced by initialize().
button3down
bool TechDrawGui::QGVNavStyle::button3down protected
Referenced by initialize().
ctrldown
bool TechDrawGui::QGVNavStyle::ctrldown protected
Referenced by initialize().
invertZoom
bool TechDrawGui::QGVNavStyle::invertZoom protected
Referenced by handleWheelEvent(), initialize(), and mouseZoomFactor().
m_clickButton
Qt::MouseButton TechDrawGui::QGVNavStyle::m_clickButton protected
Referenced by TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseReleaseEvent(), initialize(), startClick(), and stopClick().
m_clickPending
bool TechDrawGui::QGVNavStyle::m_clickPending protected
Referenced by TechDrawGui::QGVNavStyleOpenSCAD::allowContextMenu(), TechDrawGui::QGVNavStyleRevit::allowContextMenu(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseReleaseEvent(), initialize(), startClick(), and stopClick().
m_currentmode
int TechDrawGui::QGVNavStyle::m_currentmode protected
m_keyCombo
KeyCombination TechDrawGui::QGVNavStyle::m_keyCombo protected
m_panPending
bool TechDrawGui::QGVNavStyle::m_panPending protected
Referenced by TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent(), initialize(), startPan(), and stopPan().
m_reversePan
int TechDrawGui::QGVNavStyle::m_reversePan protected
Referenced by initialize(), and pan().
m_reverseScroll
int TechDrawGui::QGVNavStyle::m_reverseScroll protected
Referenced by initialize(), and pan().
m_saveCursor
QCursor TechDrawGui::QGVNavStyle::m_saveCursor protected
Referenced by initialize().
m_viewer
QGVPage* TechDrawGui::QGVNavStyle::m_viewer protected
Referenced by setAnchor(), and TechDrawGui::QGVNavStyleTouchpad::setAnchor().
m_zoomPending
bool TechDrawGui::QGVNavStyle::m_zoomPending protected
Referenced by TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent(), initialize(), startZoom(), stopZoom(), and zoom().
panningActive
bool TechDrawGui::QGVNavStyle::panningActive protected
Referenced by TechDrawGui::QGVNavStyleBlender::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleCAD::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleMaya::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleTouchpad::handleKeyReleaseEvent(), handleMouseMoveEvent(), TechDrawGui::QGVNavStyleBlender::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTinkerCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent(), handleMousePressEvent(), handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleBlender::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleTinkerCAD::handleMouseReleaseEvent(), initialize(), startPan(), and stopPan().
panOrigin
QPoint TechDrawGui::QGVNavStyle::panOrigin protected
Referenced by pan(), and startPan().
shiftdown
bool TechDrawGui::QGVNavStyle::shiftdown protected
Referenced by handleKeyPressEvent(), handleKeyReleaseEvent(), and initialize().
zoomAtCursor
bool TechDrawGui::QGVNavStyle::zoomAtCursor protected
Referenced by initialize(), and setAnchor().
zoomingActive
bool TechDrawGui::QGVNavStyle::zoomingActive protected
Referenced by TechDrawGui::QGVNavStyleCAD::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleMaya::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleTouchpad::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), initialize(), startZoom(), and stopZoom().
zoomOrigin
QPoint TechDrawGui::QGVNavStyle::zoomOrigin protected
Referenced by mouseZoomFactor(), and startZoom().
zoomStep
double TechDrawGui::QGVNavStyle::zoomStep protected
Referenced by handleKeyPressEvent(), TechDrawGui::QGVNavStyleTouchpad::handleKeyPressEvent(), initialize(), and mouseZoomFactor().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/QGVNavStyle.h
FreeCAD/src/Mod/TechDraw/Gui/QGVNavStyle.cpp