FreeCAD: SketcherGui::TaskSketcherConstraints Class Reference
SketcherGui::TaskSketcherConstraints Class Reference
#include <TaskSketcherConstraints.h>
Public Slots
void on_comboBoxFilter_currentIndexChanged (int)
void on_extendedInformation_stateChanged (int state)
void on_filterInternalAlignment_stateChanged (int state)
void on_hideAllButton_clicked (bool)
void on_listWidgetConstraints_emitCenterSelectedItems (void)
void on_listWidgetConstraints_emitHideSelection3DVisibility ()
void on_listWidgetConstraints_emitShowSelection3DVisibility ()
void on_listWidgetConstraints_itemActivated (QListWidgetItem *item)
void on_listWidgetConstraints_itemChanged (QListWidgetItem *item)
void on_listWidgetConstraints_itemSelectionChanged (void)
void on_listWidgetConstraints_updateActiveStatus (QListWidgetItem *item, bool status)
void on_listWidgetConstraints_updateDrivingStatus (QListWidgetItem *item, bool status)
void on_multipleFilterButton_clicked (bool)
void on_settingsDialogButton_clicked (bool)
void on_showAllButton_clicked (bool)
void on_visibilityButton_clicked (bool)
void on_visibilityButton_trackingaction_changed ()
void on_visualisationTrackingFilter_stateChanged (int state)
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Public Member Functions
void onSelectionChanged (const Gui::SelectionChanges &msg)
Observer message from the Selection.
TaskSketcherConstraints (ViewProviderSketch *sketchView)
~TaskSketcherConstraints ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Protected Types
typedef boost::signals2::connection Connection
Protected Member Functions
void changeEvent (QEvent *e)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Protected Attributes
Connection connectionConstraintsChanged
ViewProviderSketch * sketchView
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Additional Inherited Members
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Member Typedef Documentation
Connection
typedef boost::signals2::connection SketcherGui::TaskSketcherConstraints::Connection protected
Constructor & Destructor Documentation
TaskSketcherConstraints()
TaskSketcherConstraints::TaskSketcherConstraints (ViewProviderSketch * sketchView)
References draftgeoutils.faces::bind(), draftgeoutils.intersections::connect(), connectionConstraintsChanged, QSint::ActionGroup::groupLayout(), on_comboBoxFilter_currentIndexChanged(), on_hideAllButton_clicked(), on_listWidgetConstraints_emitCenterSelectedItems(), on_listWidgetConstraints_emitHideSelection3DVisibility(), on_listWidgetConstraints_emitShowSelection3DVisibility(), on_listWidgetConstraints_itemActivated(), on_listWidgetConstraints_itemChanged(), on_listWidgetConstraints_itemSelectionChanged(), on_listWidgetConstraints_updateActiveStatus(), on_listWidgetConstraints_updateDrivingStatus(), on_multipleFilterButton_clicked(), on_settingsDialogButton_clicked(), on_showAllButton_clicked(), on_visibilityButton_clicked(), on_visibilityButton_trackingaction_changed(), SketcherGui::ViewProviderSketch::signalConstraintsChanged, and sketchView.
~TaskSketcherConstraints()
TaskSketcherConstraints::~TaskSketcherConstraints ()
References connectionConstraintsChanged.
Member Function Documentation
changeEvent()
void TaskSketcherConstraints::changeEvent (QEvent * e) protected
on_comboBoxFilter_currentIndexChanged
void TaskSketcherConstraints::on_comboBoxFilter_currentIndexChanged (int filterindex) slot
References SketcherGui::ConstraintFilter::AssociatedConstraints, SketcherGui::ConstraintFilter::isFilterMatch(), and SketcherGui::ConstraintFilter::Selection.
Referenced by TaskSketcherConstraints().
on_extendedInformation_stateChanged
void TaskSketcherConstraints::on_extendedInformation_stateChanged (int state) slot
Referenced by on_settingsDialogButton_clicked().
on_filterInternalAlignment_stateChanged
void TaskSketcherConstraints::on_filterInternalAlignment_stateChanged (int state) slot
Referenced by on_settingsDialogButton_clicked().
on_hideAllButton_clicked
void TaskSketcherConstraints::on_hideAllButton_clicked (bool) slot
Referenced by TaskSketcherConstraints().
on_listWidgetConstraints_emitCenterSelectedItems
void TaskSketcherConstraints::on_listWidgetConstraints_emitCenterSelectedItems (void) slot
References SketcherGui::ViewProviderSketch::centerSelection(), and sketchView.
Referenced by TaskSketcherConstraints().
on_listWidgetConstraints_emitHideSelection3DVisibility
void TaskSketcherConstraints::on_listWidgetConstraints_emitHideSelection3DVisibility () slot
Referenced by TaskSketcherConstraints().
on_listWidgetConstraints_emitShowSelection3DVisibility
void TaskSketcherConstraints::on_listWidgetConstraints_emitShowSelection3DVisibility () slot
Referenced by TaskSketcherConstraints().
on_listWidgetConstraints_itemActivated
void TaskSketcherConstraints::on_listWidgetConstraints_itemActivated (QListWidgetItem * item) slot
References ConstraintItem::ConstraintNbr, SketcherGui::EditDatumDialog::exec(), ConstraintItem::isDimensional(), and sketchView.
Referenced by TaskSketcherConstraints().
on_listWidgetConstraints_itemChanged
void TaskSketcherConstraints::on_listWidgetConstraints_itemChanged (QListWidgetItem * item) slot
References Gui::Command::abortCommand(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), ConstraintItem::ConstraintNbr, Sketcher::SketchObject::Constraints, ConstraintItem::data(), Base::Tools::escapedUnicodeFromUtf8(), Sketcher::PropertyConstraintList::getConstraintName(), Gui::MainWindow::getInstance(), SketcherGui::ViewProviderSketch::getIsShownVirtualSpace(), SketcherGui::ViewProviderSketch::getSketchObject(), Sketcher::PropertyConstraintList::getValues(), Sketcher::Constraint::Name, Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, sketchView, and Base::Tools::toStdString().
Referenced by TaskSketcherConstraints().
on_listWidgetConstraints_itemSelectionChanged
void TaskSketcherConstraints::on_listWidgetConstraints_itemSelectionChanged (void) slot
References Gui::SelectionSingleton::addSelections(), Gui::SelectionObserver::blockSelection(), Gui::SelectionSingleton::clearSelection(), ConstraintItem::ConstraintNbr, Sketcher::PropertyConstraintList::getConstraintName(), App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), SketcherGui::ViewProviderSketch::getSketchObject(), Gui::Selection(), and sketchView.
Referenced by TaskSketcherConstraints().
on_listWidgetConstraints_updateActiveStatus
void TaskSketcherConstraints::on_listWidgetConstraints_updateActiveStatus (QListWidgetItem * item, bool status) slot
References Gui::Application::commandManager(), Gui::Application::Instance, and Gui::CommandManager::runCommandByName().
Referenced by TaskSketcherConstraints().
on_listWidgetConstraints_updateDrivingStatus
void TaskSketcherConstraints::on_listWidgetConstraints_updateDrivingStatus (QListWidgetItem * item, bool status) slot
References Gui::Application::commandManager(), Gui::Application::Instance, and Gui::CommandManager::runCommandByName().
Referenced by TaskSketcherConstraints().
on_multipleFilterButton_clicked
void TaskSketcherConstraints::on_multipleFilterButton_clicked (bool) slot
References SketcherGui::ConstraintFilter::getFilterIntegral(), SketcherGui::ConstraintMultiFilterDialog::getMultiFilter(), SketcherGui::ConstraintFilter::isFilterMatch(), SketcherGui::ConstraintFilter::Multiple, and SketcherGui::ConstraintMultiFilterDialog::setMultiFilter().
Referenced by TaskSketcherConstraints().
on_settingsDialogButton_clicked
void TaskSketcherConstraints::on_settingsDialogButton_clicked (bool) slot
References draftgeoutils.intersections::connect(), on_extendedInformation_stateChanged(), on_filterInternalAlignment_stateChanged(), and on_visualisationTrackingFilter_stateChanged().
Referenced by TaskSketcherConstraints().
on_showAllButton_clicked
void TaskSketcherConstraints::on_showAllButton_clicked (bool) slot
Referenced by TaskSketcherConstraints().
on_visibilityButton_clicked
void TaskSketcherConstraints::on_visibilityButton_clicked (bool) slot
Referenced by TaskSketcherConstraints().
on_visibilityButton_trackingaction_changed
void TaskSketcherConstraints::on_visibilityButton_trackingaction_changed () slot
References App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetBool().
Referenced by TaskSketcherConstraints().
on_visualisationTrackingFilter_stateChanged
void TaskSketcherConstraints::on_visualisationTrackingFilter_stateChanged (int state) slot
Referenced by on_settingsDialogButton_clicked().
onSelectionChanged()
void TaskSketcherConstraints::onSelectionChanged (const Gui::SelectionChanges & msg) virtual
Observer message from the Selection.
Implements Gui::SelectionObserver.
References Gui::SelectionChanges::AddSelection, SketcherGui::ConstraintFilter::AssociatedConstraints, Gui::SelectionObserver::blockSelection(), Gui::SelectionChanges::ClrSelection, ConstraintItem::ConstraintNbr, App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), SketcherGui::ViewProviderSketch::getSketchObject(), Sketcher::none, Gui::SelectionChanges::RmvSelection, draftutils.gui_utils::select(), SketcherGui::ConstraintFilter::Selection, Gui::SelectionChanges::SetSelection, and sketchView.
Member Data Documentation
connectionConstraintsChanged
Connection SketcherGui::TaskSketcherConstraints::connectionConstraintsChanged protected
Referenced by TaskSketcherConstraints(), and ~TaskSketcherConstraints().
sketchView
ViewProviderSketch* SketcherGui::TaskSketcherConstraints::sketchView protected
Referenced by on_listWidgetConstraints_emitCenterSelectedItems(), on_listWidgetConstraints_itemActivated(), on_listWidgetConstraints_itemChanged(), on_listWidgetConstraints_itemSelectionChanged(), onSelectionChanged(), and TaskSketcherConstraints().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/Gui/TaskSketcherConstraints.h
FreeCAD/src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp