FreeCAD: StdMeshers_ImportSource1D Class Reference
StdMeshers_ImportSource1D Class Reference
Stores groups to import elements from.
#include <StdMeshers_ImportSource.hxx>
Public Member Functions
virtual bool DataDependOnParams () const
The returned value is used by NotifySubMeshesHypothesisModification() to decide to call subMesh->AlgoStateEngine(MODIF_HYP, hyp) or not if subMesh is ready to be computed (algo+hyp==OK) but not yet computed. True result is reasonable for example if EventListeners depend on parameters of hypothesis.
void GetCopySourceMesh (bool &toCopyMesh, bool &toCopyGroups) const
const std::vector< SMESH_Group * > & GetGroups (bool loaded=false) const
std::vector< SMESH_Group * > * GetResultGroups (const SMESHDS_Mesh &srcMesh, const SMESHDS_Mesh &tgtMesh)
Return groups imported from other mesh.
std::vector< SMESH_Mesh * > GetSourceMeshes () const
Return source meshes.
std::vector< SMESH_subMesh * > GetSourceSubMeshes (const SMESH_Mesh *srcMesh) const
Return submeshes whose events affect the target mesh.
virtual std::istream & LoadFrom (std::istream &load)
void RestoreGroups (const std::vector< SMESH_Group * > &groups)
Restore source groups and result groups by _resultGroupsStorage.
virtual std::ostream & SaveTo (std::ostream &save)
void SetCopySourceMesh (bool toCopyMesh, bool toCopyGroups)
void SetGroups (const std::vector< SMESH_Group * > &groups)
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)
Initialize ImportSource value by the mesh built on the geometry.
StdMeshers_ImportSource1D (int hypId, int studyId, SMESH_Gen *gen)
void StoreResultGroups (const std::vector< SMESH_Group * > &groups, const SMESHDS_Mesh &srcMesh, const SMESHDS_Mesh &tgtMesh)
Remember groups imported from other mesh.
virtual ~ StdMeshers_ImportSource1D ()
Public Member Functions inherited from SMESH_Hypothesis
void ClearParameters ()
virtual int GetDim () const
SMESH_Gen * GetGen () const
char * GetLastParameters () const
virtual const char * GetLibName () const
SMESH_Mesh * GetMeshByPersistentID (int id)
Find a mesh with given persistent ID.
char * GetParameters () const
virtual int GetShapeType () const
int GetStudyId () const
virtual bool IsAuxiliary () const
Return true if me is an auxiliary hypothesis.
virtual void NotifySubMeshesHypothesisModification ()
void SetLastParameters (const char *theParameters)
void SetLibName (const char *theLibName)
void SetParameters (const char *theParameters)
SMESH_Hypothesis (int hypId, int studyId, SMESH_Gen *gen)
virtual ~SMESH_Hypothesis ()
Public Member Functions inherited from SMESHDS_Hypothesis
int GetID () const
const char * GetName () const
int GetType () const
bool IsSameName (const SMESHDS_Hypothesis &other) const
Compare types of hypotheses.
bool operator!= (const SMESHDS_Hypothesis &other) const
virtual bool operator== (const SMESHDS_Hypothesis &other) const
SMESHDS_Hypothesis (int hypId)
virtual ~SMESHDS_Hypothesis ()
Additional Inherited Members
Public Types inherited from SMESH_Hypothesis
enum Hypothesis_Status {
HYP_OK = 0, HYP_MISSING, HYP_CONCURENT, HYP_BAD_PARAMETER,
HYP_HIDDEN_ALGO, HYP_HIDING_ALGO, HYP_UNKNOWN_FATAL, HYP_INCOMPATIBLE,
HYP_NOTCONFORM, HYP_ALREADY_EXIST, HYP_BAD_DIM, HYP_BAD_SUBSHAPE,
HYP_BAD_GEOMETRY, HYP_NEED_SHAPE, HYP_INCOMPAT_HYPS
}
Public Types inherited from SMESHDS_Hypothesis
enum hypothesis_type {
PARAM_ALGO, ALGO_0D, ALGO_1D, ALGO_2D,
ALGO_3D
}
Static Public Member Functions inherited from SMESH_Hypothesis
static bool IsStatusFatal (Hypothesis_Status theStatus)
Detailed Description
Stores groups to import elements from.
Constructor & Destructor Documentation
StdMeshers_ImportSource1D()
StdMeshers_ImportSource1D::StdMeshers_ImportSource1D (int hypId, int studyId, SMESH_Gen * gen)
Creates StdMeshers_ImportSource1D
~ StdMeshers_ImportSource1D()
virtual StdMeshers_ImportSource1D::~ StdMeshers_ImportSource1D () virtual
Member Function Documentation
DataDependOnParams()
virtual bool StdMeshers_ImportSource1D::DataDependOnParams () const virtual
The returned value is used by NotifySubMeshesHypothesisModification() to decide to call subMesh->AlgoStateEngine(MODIF_HYP, hyp) or not if subMesh is ready to be computed (algo+hyp==OK) but not yet computed. True result is reasonable for example if EventListeners depend on parameters of hypothesis.
Reimplemented from SMESH_Hypothesis.
GetCopySourceMesh()
void StdMeshers_ImportSource1D::GetCopySourceMesh (bool & toCopyMesh, bool & toCopyGroups) const
GetGroups()
const std::vector< SMESH_Group * > & StdMeshers_ImportSource1D::GetGroups (bool loaded = false) const
Returns groups to import elements from
Parameters
[in] loaded - if true, meshes holding the groups are loaded
Referenced by GetSourceMeshes(), and GetSourceSubMeshes().
GetResultGroups()
std::vector< SMESH_Group * > * StdMeshers_ImportSource1D::GetResultGroups (const SMESHDS_Mesh & srcMesh, const SMESHDS_Mesh & tgtMesh)
Return groups imported from other mesh.
Parameters
srcMesh - source mesh
tgtMesh - destination mesh
Return values
const std::vector<SMESH_Group*>& - groups
References draftgeoutils.general::vec().
GetSourceMeshes()
std::vector< SMESH_Mesh * > StdMeshers_ImportSource1D::GetSourceMeshes () const
Return source meshes.
References GetGroups(), SMESHDS_GroupBase::GetMesh(), SMESHDS_Mesh::GetPersistentId(), and studyContextStruct::mapMesh.
Referenced by StdMeshers_Import_1D::setEventListener().
GetSourceSubMeshes()
std::vector< SMESH_subMesh * > StdMeshers_ImportSource1D::GetSourceSubMeshes (const SMESH_Mesh * srcMesh) const
Return submeshes whose events affect the target mesh.
References SMESHDS_GroupBase::GetElements(), GetGroups(), SMESHDS_GroupBase::GetMesh(), SMESH_Mesh::GetMeshDS(), SMESH_Mesh::GetShapeToMesh(), SMESH_Mesh::GetSubMesh(), SMESH_Mesh::GetSubMeshContaining(), SMESH_Mesh::HasShapeToMesh(), and SMESHDS_Mesh::ShapeToIndex().
LoadFrom()
istream & StdMeshers_ImportSource1D::LoadFrom (std::istream & load) virtual
Load _toCopyMesh and _toCopyGroups from a stream
Implements SMESHDS_Hypothesis.
RestoreGroups()
void StdMeshers_ImportSource1D::RestoreGroups (const std::vector< SMESH_Group * > & groups)
Restore source groups and result groups by _resultGroupsStorage.
SaveTo()
ostream & StdMeshers_ImportSource1D::SaveTo (std::ostream & save) virtual
Save _toCopyMesh and _toCopyGroups to a stream
Implements SMESHDS_Hypothesis.
References OfflineRenderingUtils::save().
SetCopySourceMesh()
void StdMeshers_ImportSource1D::SetCopySourceMesh (bool toCopyMesh, bool toCopyGroups)
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
SetGroups()
void StdMeshers_ImportSource1D::SetGroups (const std::vector< SMESH_Group * > & groups)
Sets groups to import elements from
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
SetParametersByDefaults()
bool StdMeshers_ImportSource1D::SetParametersByDefaults (const TDefaults & dflts, const SMESH_Mesh * theMesh = 0) virtual
Initialize my parameter values by default parameters.
Return values
bool - true if parameter values have been successfully defined
Implements SMESH_Hypothesis.
SetParametersByMesh()
bool StdMeshers_ImportSource1D::SetParametersByMesh (const SMESH_Mesh * theMesh, const TopoDS_Shape & theShape) virtual
Initialize ImportSource value by the mesh built on the geometry.
Parameters
theMesh - the built mesh
theShape - the geometry of interest
Return values
bool - true if parameter values have been successfully defined
Implements SMESH_Hypothesis.
StoreResultGroups()
void StdMeshers_ImportSource1D::StoreResultGroups (const std::vector< SMESH_Group * > & groups, const SMESHDS_Mesh & srcMesh, const SMESHDS_Mesh & tgtMesh)
Remember groups imported from other mesh.
Parameters
groups - result groups
srcMesh - source mesh
tgtMesh - destination mesh
Referenced by StdMeshers_Import_1D::importMesh().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_ImportSource.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_ImportSource.cpp