FreeCAD: PartGui::ViewProviderSplineExtension Class Reference
PartGui::ViewProviderSplineExtension Class Reference
#include <ViewProviderSpline.h>
Public Member Functions
virtual void extensionSetupContextMenu (QMenu *, QObject *, const char *) override
virtual void extensionUpdateData (const App::Property *) override
ViewProviderSplineExtension ()
Constructor.
virtual ~ViewProviderSplineExtension ()=default
Public Member Functions inherited from Gui::ViewProviderExtension
virtual void extensionAttach (App::DocumentObject *)
virtual void extensionBeforeDelete ()
virtual bool extensionCanDragAndDropObject (App::DocumentObject *) const
virtual bool extensionCanDragObject (App::DocumentObject *) const
virtual bool extensionCanDragObjects () const
virtual bool extensionCanDropObject (App::DocumentObject *) const
virtual bool extensionCanDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const
virtual bool extensionCanDropObjects () const
virtual std::vector< App::DocumentObject * > extensionClaimChildren (void) const
virtual std::vector< App::DocumentObject * > extensionClaimChildren3D (void) const
virtual void extensionDragObject (App::DocumentObject *)
virtual void extensionDropObject (App::DocumentObject *)
virtual std::string extensionDropObjectEx (App::DocumentObject *obj, App::DocumentObject *, const char *, const std::vector< std::string > &)
virtual void extensionFinishRestoring ()
virtual SoSeparator * extensionGetBackRoot (void) const
virtual SoGroup * extensionGetChildRoot (void) const
virtual bool extensionGetDetailPath (const char *, SoFullPath *, SoDetail *&) const
virtual std::vector< std::string > extensionGetDisplayModes (void) const
virtual bool extensionGetElementPicked (const SoPickedPoint *, std::string &) const
virtual SoSeparator * extensionGetFrontRoot (void) const
virtual void extensionHide (void)
Hides the view provider.
virtual QIcon extensionMergeColorfullOverlayIcons (const QIcon &orig) const
virtual QIcon extensionMergeGreyableOverlayIcons (const QIcon &orig) const
virtual void extensionModeSwitchChange (void)
virtual bool extensionOnDelete (const std::vector< std::string > &)
virtual void extensionReattach (App::DocumentObject *)
virtual int extensionReplaceObject (App::DocumentObject *, App::DocumentObject *)
virtual void extensionSetDisplayMode (const char *)
virtual void extensionSetupContextMenu (QMenu *, QObject *, const char *)
virtual void extensionShow (void)
Shows the view provider.
virtual void extensionStartRestoring ()
virtual void extensionUpdateData (const App::Property *)
Gui::ViewProviderDocumentObject * getExtendedViewProvider ()
const Gui::ViewProviderDocumentObject * getExtendedViewProvider () const
virtual PyObject * getExtensionPyObject ()
bool ignoreOverlayIcon () const
void setIgnoreOverlayIcon (bool on)
ViewProviderExtension ()
virtual ~ViewProviderExtension ()
Public Member Functions inherited from App::Extension
Extension ()
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
virtual PyObject * getExtensionPyObject ()
virtual void initExtension (App::ExtensionContainer *obj)
bool isPythonExtension ()
std::string name () const
virtual ~Extension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Public Attributes
App::PropertyBool ControlPoints
Protected Member Functions
virtual void extensionOnChanged (const App::Property *p) override
void showControlPoints (bool, const App::Property *prop)
void showControlPointsOfEdge (const TopoDS_Edge &)
void showControlPointsOfFace (const TopoDS_Face &)
void toggleControlPoints (bool)
Protected Member Functions inherited from App::Extension
void initExtensionType (Base::Type type)
Protected Attributes
SoSwitch * pcControlPoints
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Additional Inherited Members
Static Protected Member Functions inherited from App::Extension
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
ViewProviderSplineExtension()
ViewProviderSplineExtension::ViewProviderSplineExtension ()
Constructor.
~ViewProviderSplineExtension()
virtual PartGui::ViewProviderSplineExtension::~ViewProviderSplineExtension () virtual default
Member Function Documentation
extensionOnChanged()
void ViewProviderSplineExtension::extensionOnChanged (const App::Property * p) override protected virtual
Reimplemented from App::Extension.
References ControlPoints, App::Extension::extensionOnChanged(), Gui::ViewProviderExtension::getExtendedViewProvider(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyBool::getValue(), and showControlPoints().
extensionSetupContextMenu()
void ViewProviderSplineExtension::extensionSetupContextMenu (QMenu * menu, QObject * , const char *) override virtual
Reimplemented from Gui::ViewProviderExtension.
References draftgeoutils.faces::bind(), ControlPoints, App::PropertyBool::getValue(), and toggleControlPoints().
extensionUpdateData()
void ViewProviderSplineExtension::extensionUpdateData (const App::Property * prop) override virtual
Reimplemented from Gui::ViewProviderExtension.
References Gui::coinRemoveAllChildren(), ControlPoints, Gui::ViewProviderExtension::extensionUpdateData(), Base::Persistence::getClassTypeId(), App::Property::getName(), Base::Persistence::getTypeId(), App::PropertyBool::getValue(), pcControlPoints, and showControlPoints().
showControlPoints()
void ViewProviderSplineExtension::showControlPoints (bool show, const App::Property * prop) protected
References Base::Persistence::getClassTypeId(), Gui::ViewProviderExtension::getExtendedViewProvider(), Gui::ViewProvider::getRoot(), Base::Persistence::getTypeId(), pcControlPoints, showControlPointsOfEdge(), and showControlPointsOfFace().
Referenced by extensionOnChanged(), and extensionUpdateData().
showControlPointsOfEdge()
void ViewProviderSplineExtension::showControlPointsOfEdge (const TopoDS_Edge & edge) protected
References PartGui::SoFCControlPoints::numPolesU, PartGui::SoFCControlPoints::numPolesV, and pcControlPoints.
Referenced by showControlPoints().
showControlPointsOfFace()
void ViewProviderSplineExtension::showControlPointsOfFace (const TopoDS_Face & face) protected
References PartGui::SoFCControlPoints::numPolesU, PartGui::SoFCControlPoints::numPolesV, and pcControlPoints.
Referenced by showControlPoints().
toggleControlPoints()
void ViewProviderSplineExtension::toggleControlPoints (bool on) protected
References ControlPoints, and App::PropertyBool::setValue().
Referenced by extensionSetupContextMenu().
Member Data Documentation
ControlPoints
App::PropertyBool PartGui::ViewProviderSplineExtension::ControlPoints
Referenced by extensionOnChanged(), extensionSetupContextMenu(), extensionUpdateData(), and toggleControlPoints().
pcControlPoints
SoSwitch* PartGui::ViewProviderSplineExtension::pcControlPoints protected
Referenced by extensionUpdateData(), showControlPoints(), showControlPointsOfEdge(), and showControlPointsOfFace().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/ViewProviderSpline.h
FreeCAD/src/Mod/Part/Gui/ViewProviderSpline.cpp