FreeCAD: SMESHDS_GroupBase Class Reference
SMESHDS_GroupBase Class Reference abstract
#include <SMESHDS_GroupBase.hxx>
Public Member Functions
virtual bool Contains (const int theID)
virtual bool Contains (const SMDS_MeshElement *elem)
virtual int Extent () const
Quantity_Color GetColor () const
int GetColorGroup () const
virtual SMDS_ElemIteratorPtr GetElements () const =0
int GetID () const
virtual int GetID (const int theIndex)
const SMESHDS_Mesh * GetMesh () const
const char * GetStoreName () const
virtual VTK_MTIME_TYPE GetTic () const =0
SMDSAbs_ElementType GetType () const
virtual bool IsEmpty ()
void SetColor (const Quantity_Color &theColor)
void SetColorGroup (int theColorGroup)
void SetStoreName (const char *theName)
virtual void SetType (SMDSAbs_ElementType theType)
SMESHDS_GroupBase (const int theID, const SMESHDS_Mesh *theMesh, const SMDSAbs_ElementType theType)
virtual ~SMESHDS_GroupBase ()
Static Public Member Functions
static void SetDefaultColor (const Quantity_Color &theColor)
Protected Member Functions
const SMDS_MeshElement * findInMesh (const int theID) const
void resetIterator ()
Constructor & Destructor Documentation
SMESHDS_GroupBase()
SMESHDS_GroupBase::SMESHDS_GroupBase (const int theID, const SMESHDS_Mesh * theMesh, const SMDSAbs_ElementType theType)
~SMESHDS_GroupBase()
virtual SMESHDS_GroupBase::~SMESHDS_GroupBase () virtual
Member Function Documentation
Contains() [1/2]
bool SMESHDS_GroupBase::Contains (const int theID) virtual
Reimplemented in SMESHDS_GroupOnGeom, SMESHDS_GroupOnFilter, and SMESHDS_Group.
References GetElements().
Referenced by StdMeshers_QuadToTriaAdaptor::Compute(), Contains(), and SMESH::Controls::BelongToMeshGroup::IsSatisfy().
Contains() [2/2]
bool SMESHDS_GroupBase::Contains (const SMDS_MeshElement * elem) virtual
Reimplemented in SMESHDS_GroupOnGeom, SMESHDS_GroupOnFilter, and SMESHDS_Group.
References Contains(), and SMDS_MeshElement::GetID().
Extent()
int SMESHDS_GroupBase::Extent () const virtual
Reimplemented in SMESHDS_GroupOnFilter, and SMESHDS_Group.
References GetElements().
Referenced by DriverUNV_W_SMDS_Mesh::Perform(), and SMESH::Controls::GroupColor::SetMesh().
findInMesh()
const SMDS_MeshElement * SMESHDS_GroupBase::findInMesh (const int theID) const protected
References SMDS_Mesh::FindElement(), SMDS_Mesh::FindNode(), GetMesh(), GetType(), and SMDS_MeshElement::GetType().
Referenced by SMESHDS_Group::Add(), SMESHDS_Group::Contains(), SMESHDS_GroupOnGeom::Contains(), and SMESHDS_Group::Remove().
GetColor()
Quantity_Color SMESHDS_GroupBase::GetColor () const
Referenced by SMESH_Mesh::ConvertToStandalone(), GetColorGroup(), and SMESH::Controls::GroupColor::SetMesh().
GetColorGroup()
int SMESHDS_GroupBase::GetColorGroup () const
References GetColor().
GetElements()
virtual SMDS_ElemIteratorPtr SMESHDS_GroupBase::GetElements () const pure virtual
Implemented in SMESHDS_GroupOnGeom, SMESHDS_GroupOnFilter, and SMESHDS_Group.
Referenced by StdMeshers_Import_1D::Compute(), StdMeshers_Import_1D2D::Compute(), Contains(), SMESH_Mesh::ConvertToStandalone(), SMESH_MeshEditor::CreateHoleSkin(), StdMeshers_Import_1D::Evaluate(), StdMeshers_Import_1D2D::Evaluate(), Extent(), GetID(), StdMeshers_ImportSource1D::GetSourceSubMeshes(), StdMeshers_Import_1D::importMesh(), IsEmpty(), and DriverUNV_W_SMDS_Mesh::Perform().
GetID() [1/2]
int SMESHDS_GroupBase::GetID () const
Referenced by SMESH_Mesh::AddGroup(), DriverUNV_W_SMDS_Mesh::Perform(), SMESH::Controls::GroupColor::SetMesh(), SMESH_MeshVSLink::SMESH_MeshVSLink(), and SMESH_Mesh::SynchronizeGroups().
GetID() [2/2]
int SMESHDS_GroupBase::GetID (const int theIndex) virtual
References GetElements().
GetMesh()
const SMESHDS_Mesh* SMESHDS_GroupBase::GetMesh () const
Referenced by StdMeshers_Import_1D::Compute(), StdMeshers_Import_1D2D::Compute(), findInMesh(), SMESHDS_GroupOnFilter::GetElements(), StdMeshers_ImportSource1D::GetSourceMeshes(), StdMeshers_ImportSource1D::GetSourceSubMeshes(), SMESHDS_GroupOnFilter::GetTic(), SMESHDS_GroupOnGeom::GetTic(), SMESHDS_GroupOnFilter::IsUpToDate(), SMESH::Controls::BelongToMeshGroup::SetMesh(), SMESHDS_GroupOnFilter::SetPredicate(), and SMESHDS_GroupOnGeom::SetShape().
GetStoreName()
const char* SMESHDS_GroupBase::GetStoreName () const
Referenced by DriverMED_R_SMESHDS_Mesh::GetGroup(), DriverUNV_W_SMDS_Mesh::Perform(), and SMESH_Group::SMESH_Group().
GetTic()
virtual VTK_MTIME_TYPE SMESHDS_GroupBase::GetTic () const pure virtual
Implemented in SMESHDS_GroupOnGeom, SMESHDS_GroupOnFilter, and SMESHDS_Group.
GetType()
SMDSAbs_ElementType SMESHDS_GroupBase::GetType () const
Referenced by Fem::FemMesh::addGroupElements(), StdMeshers_QuadToTriaAdaptor::Compute(), SMESH_Mesh::ConvertToStandalone(), SMESH_MeshEditor::CreateHoleSkin(), SMESH_Mesh::ExportMED(), findInMesh(), SMESHDS_GroupOnFilter::GetElements(), SMESHDS_GroupOnGeom::GetElements(), DriverMED_R_SMESHDS_Mesh::GetGroup(), SMESH::Controls::BelongToMeshGroup::GetType(), SMESH_Mesh::HasDuplicatedGroupNamesMED(), StdMeshers_Import_1D::importMesh(), DriverUNV_W_SMDS_Mesh::Perform(), SMESH::Controls::GroupColor::SetMesh(), and SMESHDS_Group::SetType().
IsEmpty()
bool SMESHDS_GroupBase::IsEmpty () virtual
Reimplemented in SMESHDS_GroupOnFilter, and SMESHDS_Group.
References GetElements().
Referenced by StdMeshers_QuadToTriaAdaptor::Compute(), SMESH_MeshEditor::CreateHoleSkin(), and SMESH::Controls::BelongToMeshGroup::SetMesh().
resetIterator()
void SMESHDS_GroupBase::resetIterator () protected
Internal method: resets cached iterator, should be called by ancestors when they are modified (ex: Add() or Remove())
Referenced by SMESHDS_Group::Add(), SMESHDS_Group::Clear(), and SMESHDS_Group::Remove().
SetColor()
void SMESHDS_GroupBase::SetColor (const Quantity_Color & theColor)
Referenced by SMESH_Mesh::ConvertToStandalone(), and SetColorGroup().
SetColorGroup()
void SMESHDS_GroupBase::SetColorGroup (int theColorGroup)
References SetColor().
Referenced by DriverMED_R_SMESHDS_Mesh::GetGroup().
SetDefaultColor()
static void SMESHDS_GroupBase::SetDefaultColor (const Quantity_Color & theColor) static
SetStoreName()
void SMESHDS_GroupBase::SetStoreName (const char * theName)
Referenced by SMESH_Mesh::ExportMED(), SMESH_Mesh::ExportUNV(), SMESH_Mesh::MEDToMesh(), SMESH_Group::SetName(), SMESH_Group::SMESH_Group(), and SMESH_Mesh::UNVToMesh().
SetType()
void SMESHDS_GroupBase::SetType (SMDSAbs_ElementType theType) virtual
Reimplemented in SMESHDS_Group.
Referenced by SMESHDS_Group::SetType().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESHDS_GroupBase.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESHDS/SMESHDS_GroupBase.cpp