FreeCAD: FreeCADInit Namespace Reference
FreeCADInit Namespace Reference
Classes
class FCADLogger
class PropertyType
class ScaleType
class Scheme
Functions
def InitApplications ()
def removeFromPath (module_name)
def setupSearchPaths (PathExtension)
Variables
Acceleration
AmountOfSubstance
Ampere
Angle
AngleOfFriction
AngularMinute
AngularSecond
App = FreeCAD
Area
Bar
Calorie
Candela
CentiMetre
CompressiveStrength
Coulomb
CubicFoot
DeciMetre
Degree
Density
DynamicViscosity
ElectricalCapacitance
ElectricalConductance
ElectricalConductivity
ElectricalInductance
ElectricalResistance
ElectricCharge
ElectricCurrent
ElectricPotential
ElectronVolt
Err = FreeCAD.Console.PrintError
Farad
Foot
Force
Frequency
Gauss
GigaHertz
GigaPascal
Gon
Gram
GuiUp
HeatFlux
Henry
Hertz
Hour
Hundredweights
Inch
Joule
Kelvin
KiloAmpere
KiloCalorie
KiloElectronVolt
KiloGram
KiloHertz
KiloJoule
KiloMetre
KiloNewton
KiloNewtonPerMeter
KiloOhm
KiloPascal
KiloSiemens
KiloVolt
KiloWatt
KiloWattHour
KinematicViscosity
KMH
KSI
Length
Liter
Log = FreeCAD.Console.PrintLog
LuminousIntensity
MagneticFluxDensity
Mass
MegaAmpere
MegaElectronVolt
MegaHertz
MegaNewton
MegaNewtonPerMeter
MegaOhm
MegaPascal
MegaSiemens
Metre
MicroFarad
MicroGram
MicroHenry
MicroKelvin
MicroMetre
MicroSiemens
Mile
MilliAmpere
MilliBar
MilliFarad
MilliGram
MilliHenry
MilliJoule
MilliKelvin
MilliLiter
MilliMetre
MilliMole
MilliNewton
MilliNewtonPerMeter
MilliSiemens
MilliVolt
MilliWatt
Minute
Mole
MPH
MPSI
Msg = FreeCAD.Console.PrintMessage
mTorr
NanoFarad
NanoHenry
NanoMetre
Newton
NewtonMeter
NewtonPerMeter
Oersted
Ohm
Ounce
Pascal
PicoFarad
Pound
PoundForce
Power
Pressure
process_time
PSI
Radian
Second
ShearModulus
Siemens
SpecificEnergy
SpecificHeat
SquareFoot
Stiffness
Stone
Stress
Temperature
TeraHertz
Tesla
test_ascii = lambda s: all(ord(c) < 128 for c in s)
ThermalConductivity
ThermalExpansionCoefficient
ThermalTransferCoefficient
Thou
TimeSpan
Ton
Torr
UltimateTensileStrength
VacuumPermittivity
Velocity
Volt
VoltAmpere
VoltAmpereSecond
Volume
VolumetricThermalExpansionCoefficient
Watt
WattSecond
Weber
Work
Wrn = FreeCAD.Console.PrintWarning
Yard
YieldStrength
YoungsModulus
yTorr
Function Documentation
InitApplications()
def FreeCADInit.InitApplications ()
References Err, Log, Msg, and setupSearchPaths().
removeFromPath()
def FreeCADInit.removeFromPath (module_name)
removes the module from the sys.path. The entry point for imports
    will therefore always be FreeCAD.
    eg.: from FreeCAD.Module.submodule import function
References Wrn.
setupSearchPaths()
def FreeCADInit.setupSearchPaths (PathExtension)
References Log, test_ascii, and Wrn.
Referenced by InitApplications().
Variable Documentation
Acceleration
FreeCADInit.Acceleration
AmountOfSubstance
FreeCADInit.AmountOfSubstance
Ampere
FreeCADInit.Ampere
Angle
FreeCADInit.Angle
AngleOfFriction
FreeCADInit.AngleOfFriction
AngularMinute
FreeCADInit.AngularMinute
AngularSecond
FreeCADInit.AngularSecond
App
FreeCADInit.App = FreeCAD
Area
FreeCADInit.Area
Bar
FreeCADInit.Bar
Calorie
FreeCADInit.Calorie
Candela
FreeCADInit.Candela
CentiMetre
FreeCADInit.CentiMetre
CompressiveStrength
FreeCADInit.CompressiveStrength
Coulomb
FreeCADInit.Coulomb
CubicFoot
FreeCADInit.CubicFoot
DeciMetre
FreeCADInit.DeciMetre
Degree
FreeCADInit.Degree
Density
FreeCADInit.Density
DynamicViscosity
FreeCADInit.DynamicViscosity
ElectricalCapacitance
FreeCADInit.ElectricalCapacitance
ElectricalConductance
FreeCADInit.ElectricalConductance
ElectricalConductivity
FreeCADInit.ElectricalConductivity
ElectricalInductance
FreeCADInit.ElectricalInductance
ElectricalResistance
FreeCADInit.ElectricalResistance
ElectricCharge
FreeCADInit.ElectricCharge
ElectricCurrent
FreeCADInit.ElectricCurrent
ElectricPotential
FreeCADInit.ElectricPotential
ElectronVolt
FreeCADInit.ElectronVolt
Err
FreeCADInit.Err = FreeCAD.Console.PrintError
Referenced by InitApplications().
Farad
FreeCADInit.Farad
Foot
FreeCADInit.Foot
Force
FreeCADInit.Force
Frequency
FreeCADInit.Frequency
Gauss
FreeCADInit.Gauss
GigaHertz
FreeCADInit.GigaHertz
GigaPascal
FreeCADInit.GigaPascal
Gon
FreeCADInit.Gon
Gram
FreeCADInit.Gram
GuiUp
FreeCADInit.GuiUp
HeatFlux
FreeCADInit.HeatFlux
Henry
FreeCADInit.Henry
Hertz
FreeCADInit.Hertz
Hour
FreeCADInit.Hour
Hundredweights
FreeCADInit.Hundredweights
Inch
FreeCADInit.Inch
Joule
FreeCADInit.Joule
Kelvin
FreeCADInit.Kelvin
KiloAmpere
FreeCADInit.KiloAmpere
KiloCalorie
FreeCADInit.KiloCalorie
KiloElectronVolt
FreeCADInit.KiloElectronVolt
KiloGram
FreeCADInit.KiloGram
KiloHertz
FreeCADInit.KiloHertz
KiloJoule
FreeCADInit.KiloJoule
KiloMetre
FreeCADInit.KiloMetre
KiloNewton
FreeCADInit.KiloNewton
KiloNewtonPerMeter
FreeCADInit.KiloNewtonPerMeter
KiloOhm
FreeCADInit.KiloOhm
KiloPascal
FreeCADInit.KiloPascal
KiloSiemens
FreeCADInit.KiloSiemens
KiloVolt
FreeCADInit.KiloVolt
KiloWatt
FreeCADInit.KiloWatt
KiloWattHour
FreeCADInit.KiloWattHour
KinematicViscosity
FreeCADInit.KinematicViscosity
KMH
FreeCADInit.KMH
KSI
FreeCADInit.KSI
Length
FreeCADInit.Length
Liter
FreeCADInit.Liter
Log
FreeCADInit.Log = FreeCAD.Console.PrintLog
Referenced by InitApplications(), and setupSearchPaths().
LuminousIntensity
FreeCADInit.LuminousIntensity
MagneticFluxDensity
FreeCADInit.MagneticFluxDensity
Mass
FreeCADInit.Mass
MegaAmpere
FreeCADInit.MegaAmpere
MegaElectronVolt
FreeCADInit.MegaElectronVolt
MegaHertz
FreeCADInit.MegaHertz
MegaNewton
FreeCADInit.MegaNewton
MegaNewtonPerMeter
FreeCADInit.MegaNewtonPerMeter
MegaOhm
FreeCADInit.MegaOhm
MegaPascal
FreeCADInit.MegaPascal
MegaSiemens
FreeCADInit.MegaSiemens
Metre
FreeCADInit.Metre
MicroFarad
FreeCADInit.MicroFarad
MicroGram
FreeCADInit.MicroGram
MicroHenry
FreeCADInit.MicroHenry
MicroKelvin
FreeCADInit.MicroKelvin
MicroMetre
FreeCADInit.MicroMetre
MicroSiemens
FreeCADInit.MicroSiemens
Mile
FreeCADInit.Mile
MilliAmpere
FreeCADInit.MilliAmpere
MilliBar
FreeCADInit.MilliBar
MilliFarad
FreeCADInit.MilliFarad
MilliGram
FreeCADInit.MilliGram
MilliHenry
FreeCADInit.MilliHenry
MilliJoule
FreeCADInit.MilliJoule
MilliKelvin
FreeCADInit.MilliKelvin
MilliLiter
FreeCADInit.MilliLiter
MilliMetre
FreeCADInit.MilliMetre
MilliMole
FreeCADInit.MilliMole
MilliNewton
FreeCADInit.MilliNewton
MilliNewtonPerMeter
FreeCADInit.MilliNewtonPerMeter
MilliSiemens
FreeCADInit.MilliSiemens
MilliVolt
FreeCADInit.MilliVolt
MilliWatt
FreeCADInit.MilliWatt
Minute
FreeCADInit.Minute
Mole
FreeCADInit.Mole
MPH
FreeCADInit.MPH
MPSI
FreeCADInit.MPSI
Msg
FreeCADInit.Msg = FreeCAD.Console.PrintMessage
Referenced by InitApplications().
mTorr
FreeCADInit.mTorr
NanoFarad
FreeCADInit.NanoFarad
NanoHenry
FreeCADInit.NanoHenry
NanoMetre
FreeCADInit.NanoMetre
Newton
FreeCADInit.Newton
NewtonMeter
FreeCADInit.NewtonMeter
NewtonPerMeter
FreeCADInit.NewtonPerMeter
Oersted
FreeCADInit.Oersted
Ohm
FreeCADInit.Ohm
Ounce
FreeCADInit.Ounce
Pascal
FreeCADInit.Pascal
PicoFarad
FreeCADInit.PicoFarad
Pound
FreeCADInit.Pound
PoundForce
FreeCADInit.PoundForce
Power
FreeCADInit.Power
Pressure
FreeCADInit.Pressure
process_time
FreeCADInit.process_time
PSI
FreeCADInit.PSI
Radian
FreeCADInit.Radian
Second
FreeCADInit.Second
ShearModulus
FreeCADInit.ShearModulus
Siemens
FreeCADInit.Siemens
SpecificEnergy
FreeCADInit.SpecificEnergy
SpecificHeat
FreeCADInit.SpecificHeat
SquareFoot
FreeCADInit.SquareFoot
Stiffness
FreeCADInit.Stiffness
Stone
FreeCADInit.Stone
Stress
FreeCADInit.Stress
Temperature
FreeCADInit.Temperature
TeraHertz
FreeCADInit.TeraHertz
Tesla
FreeCADInit.Tesla
test_ascii
FreeCADInit.test_ascii = lambda s: all(ord(c) < 128 for c in s)
Referenced by setupSearchPaths().
ThermalConductivity
FreeCADInit.ThermalConductivity
ThermalExpansionCoefficient
FreeCADInit.ThermalExpansionCoefficient
ThermalTransferCoefficient
FreeCADInit.ThermalTransferCoefficient
Thou
FreeCADInit.Thou
TimeSpan
FreeCADInit.TimeSpan
Ton
FreeCADInit.Ton
Torr
FreeCADInit.Torr
UltimateTensileStrength
FreeCADInit.UltimateTensileStrength
VacuumPermittivity
FreeCADInit.VacuumPermittivity
Velocity
FreeCADInit.Velocity
Volt
FreeCADInit.Volt
VoltAmpere
FreeCADInit.VoltAmpere
VoltAmpereSecond
FreeCADInit.VoltAmpereSecond
Volume
FreeCADInit.Volume
VolumetricThermalExpansionCoefficient
FreeCADInit.VolumetricThermalExpansionCoefficient
Watt
FreeCADInit.Watt
WattSecond
FreeCADInit.WattSecond
Weber
FreeCADInit.Weber
Work
FreeCADInit.Work
Wrn
FreeCADInit.Wrn = FreeCAD.Console.PrintWarning
Referenced by removeFromPath(), and setupSearchPaths().
Yard
FreeCADInit.Yard
YieldStrength
FreeCADInit.YieldStrength
YoungsModulus
FreeCADInit.YoungsModulus
yTorr
FreeCADInit.yTorr