FreeCAD: Sandbox::CustomPropertyEvent Class Reference
Sandbox::CustomPropertyEvent Class Reference
Public Member Functions
CustomPropertyEvent (App::Property &p, const App::Property &v)
void execute ()
~CustomPropertyEvent ()
Public Member Functions inherited from Sandbox::AbstractCustomProtectorEvent
AbstractCustomProtectorEvent ()
virtual void execute ()=0
~AbstractCustomProtectorEvent ()
Protected Attributes
App::Property & property
const App::Property & value
Additional Inherited Members
Public Attributes inherited from Sandbox::AbstractCustomProtectorEvent
QSemaphore * semaphore
Constructor & Destructor Documentation
CustomPropertyEvent()
Sandbox::CustomPropertyEvent::CustomPropertyEvent (App::Property & p, const App::Property & v)
~CustomPropertyEvent()
Sandbox::CustomPropertyEvent::~CustomPropertyEvent ()
Member Function Documentation
execute()
void Sandbox::CustomPropertyEvent::execute (void) virtual
Implements Sandbox::AbstractCustomProtectorEvent.
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), PathScripts.PathDressupDogbone.ObjectDressup::boneStateList(), ArchSite.Compass::buildCoordinates(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::generateTags(), ArchPanel.PanelCut::getWires(), ArchSchedule.CommandArchSchedule::IsActive(), Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), FeaturePython.DistanceBolt::onChanged(), PathScripts.PathStock.StockFromBase::onChanged(), PathScripts.PathStock.StockCreateBox::onChanged(), PathScripts.PathStock.StockCreateCylinder::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), draftobjects.patharray.PathArray::onDocumentRestored(), and draftobjects.pathtwistedarray.PathTwistedArray::onDocumentRestored().
Member Data Documentation
property
App::Property& Sandbox::CustomPropertyEvent::property protected
value
const App::Property& Sandbox::CustomPropertyEvent::value protected
Referenced by PathScripts.PathProperty.Property::displayString(), PathScripts.PathProperty.PropertyQuantity::displayString(), PathScripts.PathSetupSheetOpPrototype.Property::displayString(), PathScripts.PathSetupSheetOpPrototype.PropertyQuantity::displayString(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), PathScripts.PathProperty.Property::getValue(), PathScripts.PathSetupSheetOpPrototype.Property::getValue(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), PathScripts.PathProperty.Property::setValue(), and PathScripts.PathSetupSheetOpPrototype.Property::setValue().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sandbox/App/DocumentProtector.cpp