FreeCAD: Gui::LabelEditor Class Reference
Gui::LabelEditor Class Reference
#include <Widgets.h>
Public Types
enum InputType { String , Float , Integer }
Public Slots
virtual void setButtonText (const QString &)
Sets the browse button's text to txt.
virtual void setText (const QString &)
virtual void validateText (const QString &)
Validates if the input of the lineedit is a valid list.
Signals
void textChanged (const QString &)
Public Member Functions
QString buttonText () const
Returns the button's text.
LabelEditor (QWidget *parent=nullptr)
void setInputType (InputType)
Set the input type.
QString text () const
Returns the text.
virtual ~LabelEditor ()
Protected Member Functions
void resizeEvent (QResizeEvent *)
Properties
QString buttonText
QString text
Member Enumeration Documentation
InputType
enum Gui::LabelEditor::InputType
Enumerator
String
Float
Integer
Constructor & Destructor Documentation
LabelEditor()
LabelEditor::LabelEditor (QWidget * parent = nullptr)
References draftgeoutils.intersections::connect(), String, textChanged(), and validateText().
~LabelEditor()
LabelEditor::~LabelEditor () virtual
Member Function Documentation
buttonText()
QString LabelEditor::buttonText () const
Returns the button's text.
Returns the browse button's text.
resizeEvent()
void LabelEditor::resizeEvent (QResizeEvent * e) protected
setButtonText
void LabelEditor::setButtonText (const QString & txt) virtual slot
Sets the browse button's text to txt.
References Gui::QtTools::horizontalAdvance().
setInputType()
void LabelEditor::setInputType (InputType t)
Set the input type.
setText
void LabelEditor::setText (const QString & s) virtual slot
text()
QString LabelEditor::text () const
Returns the text.
Referenced by importSVG.svgHandler::characters(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), importSVG.svgHandler::endElement(), exportIFCHelper.SIUnitCreator::getSIPrefix(), exportIFCHelper.SIUnitCreator::getSIUnitName(), and Mod.Test.unittestgui.ProgressBar::paint().
textChanged
void Gui::LabelEditor::textChanged (const QString &) signal
Referenced by LabelEditor(), and validateText().
validateText
void LabelEditor::validateText (const QString & text) virtual slot
Validates if the input of the lineedit is a valid list.
References textChanged().
Referenced by LabelEditor().
Property Documentation
buttonText
QString Gui::LabelEditor::buttonText read write
text
QString Gui::LabelEditor::text read write
Referenced by importSVG.svgHandler::characters(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), importSVG.svgHandler::endElement(), exportIFCHelper.SIUnitCreator::getSIPrefix(), exportIFCHelper.SIUnitCreator::getSIUnitName(), and Mod.Test.unittestgui.ProgressBar::paint().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/Widgets.h
FreeCAD/src/Gui/Widgets.cpp