FreeCAD: PartGui::SectionCut Class Reference
PartGui::SectionCut Class Reference
#include <SectionCutting.h>
Public Member Functions
void reject ()
SectionCut (QWidget *parent=nullptr)
~SectionCut ()
Destroys the object and frees any allocated resources.
Static Public Member Functions
static SectionCut * makeDockWidget (QWidget *parent=nullptr)
Protected Slots
void onCutColorclicked ()
void onCutXHSChanged (int)
void onCutXHSsliderMoved (int)
void onCutXvalueChanged (double)
void onCutYHSChanged (int)
void onCutYHSsliderMoved (int)
void onCutYvalueChanged (double)
void onCutZHSChanged (int)
void onCutZHSsliderMoved (int)
void onCutZvalueChanged (double)
void onFlipXclicked ()
void onFlipYclicked ()
void onFlipZclicked ()
void onGroupBoxXtoggled ()
void onGroupBoxYtoggled ()
void onGroupBoxZtoggled ()
void onRefreshCutPBclicked ()
void onTransparencyChanged (int)
void onTransparencySliderMoved (int)
Constructor & Destructor Documentation
SectionCut()
SectionCut::SectionCut (QWidget * parent = nullptr)
References Gui::Application::activeDocument(), App::Color::asValue(), PartGui::Ui_SectionCut::AutoCutfaceColor, draftgeoutils.intersections::connect(), Base::Console(), PartGui::Ui_SectionCut::CutColor, PartGui::Ui_SectionCut::CutTransparency, PartGui::Ui_SectionCut::cutX, PartGui::Ui_SectionCut::cutXHS, PartGui::Ui_SectionCut::cutY, PartGui::Ui_SectionCut::cutYHS, PartGui::Ui_SectionCut::cutZ, PartGui::Ui_SectionCut::cutZHS, Base::ConsoleSingleton::Error(), PartGui::Ui_SectionCut::flipX, PartGui::Ui_SectionCut::flipY, PartGui::Ui_SectionCut::flipZ, Part::PropertyPartShape::getBoundingBox(), App::Document::getObject(), App::Document::getObjects(), Base::Placement::getPosition(), App::PropertyPlacement::getValue(), App::PropertyQuantity::getValue(), Gui::Application::getViewProvider(), PartGui::Ui_SectionCut::groupBoxX, PartGui::Ui_SectionCut::groupBoxY, PartGui::Ui_SectionCut::groupBoxZ, Part::Box::Height, Gui::Application::Instance, Part::Box::Length, Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, Base::BoundBox3< _Precision >::MinZ, onCutColorclicked(), onCutXHSChanged(), onCutXHSsliderMoved(), onCutXvalueChanged(), onCutYHSChanged(), onCutYHSsliderMoved(), onCutYvalueChanged(), onCutZHSChanged(), onCutZHSsliderMoved(), onCutZvalueChanged(), onFlipXclicked(), onFlipYclicked(), onFlipZclicked(), onGroupBoxXtoggled(), onGroupBoxYtoggled(), onGroupBoxZtoggled(), onRefreshCutPBclicked(), onTransparencyChanged(), onTransparencySliderMoved(), App::GeoFeature::Placement, PartGui::Ui_SectionCut::RefreshCutPB, Gui::ColorButton::setColor(), PartGui::Ui_SectionCut::setupUi(), App::PropertyBool::setValue(), Part::Feature::Shape, App::DocumentObject::Visibility, Part::Box::Width, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by makeDockWidget().
~SectionCut()
SectionCut::~SectionCut ()
Destroys the object and frees any allocated resources.
References Gui::Application::Instance, and PartGui::Ui_SectionCut::keepOnlyCutCB.
Member Function Documentation
makeDockWidget()
SectionCut * SectionCut::makeDockWidget (QWidget * parent = nullptr) static
References Gui::DockWindowManager::addDockWindow(), Gui::DockWindowManager::instance(), and SectionCut().
onCutColorclicked
void SectionCut::onCutColorclicked () protected slot
References PartGui::Ui_SectionCut::groupBoxX, PartGui::Ui_SectionCut::groupBoxY, and PartGui::Ui_SectionCut::groupBoxZ.
Referenced by SectionCut().
onCutXHSChanged
void SectionCut::onCutXHSChanged (int val) protected slot
References onCutXHSsliderMoved().
Referenced by SectionCut().
onCutXHSsliderMoved
void SectionCut::onCutXHSsliderMoved (int val) protected slot
References PartGui::Ui_SectionCut::cutX, PartGui::Ui_SectionCut::cutXHS, and Base::UnitsApi::getDecimals().
Referenced by onCutXHSChanged(), and SectionCut().
onCutXvalueChanged
void SectionCut::onCutXvalueChanged (double val) protected slot
References Base::Console(), PartGui::Ui_SectionCut::cutX, PartGui::Ui_SectionCut::cutXHS, PartGui::Ui_SectionCut::cutY, PartGui::Ui_SectionCut::cutZ, Base::ConsoleSingleton::Error(), PartGui::Ui_SectionCut::flipX, App::Document::getObject(), Base::Placement::getPosition(), App::PropertyPlacement::getValue(), App::PropertyQuantity::getValue(), Part::Box::Length, App::GeoFeature::Placement, App::DocumentObject::recomputeFeature(), Base::Placement::setPosition(), App::PropertyPlacement::setValue(), Base::ConsoleSingleton::Warning(), and Base::Vector3< _Precision >::x.
Referenced by SectionCut().
onCutYHSChanged
void SectionCut::onCutYHSChanged (int val) protected slot
References onCutYHSsliderMoved().
Referenced by SectionCut().
onCutYHSsliderMoved
void SectionCut::onCutYHSsliderMoved (int val) protected slot
References PartGui::Ui_SectionCut::cutY, PartGui::Ui_SectionCut::cutYHS, and Base::UnitsApi::getDecimals().
Referenced by onCutYHSChanged(), and SectionCut().
onCutYvalueChanged
void SectionCut::onCutYvalueChanged (double val) protected slot
References Base::Console(), PartGui::Ui_SectionCut::cutX, PartGui::Ui_SectionCut::cutY, PartGui::Ui_SectionCut::cutYHS, PartGui::Ui_SectionCut::cutZ, Base::ConsoleSingleton::Error(), PartGui::Ui_SectionCut::flipX, PartGui::Ui_SectionCut::flipY, App::Document::getObject(), Base::Placement::getPosition(), App::PropertyPlacement::getValue(), App::PropertyQuantity::getValue(), App::GeoFeature::Placement, App::DocumentObject::recomputeFeature(), Base::Placement::setPosition(), App::PropertyPlacement::setValue(), Base::ConsoleSingleton::Warning(), Part::Box::Width, and Base::Vector3< _Precision >::y.
Referenced by SectionCut().
onCutZHSChanged
void SectionCut::onCutZHSChanged (int val) protected slot
References onCutZHSsliderMoved().
Referenced by SectionCut().
onCutZHSsliderMoved
void SectionCut::onCutZHSsliderMoved (int val) protected slot
References PartGui::Ui_SectionCut::cutZ, PartGui::Ui_SectionCut::cutZHS, and Base::UnitsApi::getDecimals().
Referenced by onCutZHSChanged(), and SectionCut().
onCutZvalueChanged
void SectionCut::onCutZvalueChanged (double val) protected slot
References Base::Console(), PartGui::Ui_SectionCut::cutX, PartGui::Ui_SectionCut::cutY, PartGui::Ui_SectionCut::cutZ, PartGui::Ui_SectionCut::cutZHS, Base::ConsoleSingleton::Error(), PartGui::Ui_SectionCut::flipX, PartGui::Ui_SectionCut::flipY, PartGui::Ui_SectionCut::flipZ, App::Document::getObject(), Base::Placement::getPosition(), App::PropertyPlacement::getValue(), App::PropertyQuantity::getValue(), Part::Box::Height, App::GeoFeature::Placement, App::DocumentObject::recomputeFeature(), Base::Placement::setPosition(), App::PropertyPlacement::setValue(), Base::ConsoleSingleton::Warning(), and Base::Vector3< _Precision >::z.
Referenced by SectionCut().
onFlipXclicked
void SectionCut::onFlipXclicked () protected slot
References Base::Console(), Base::ConsoleSingleton::Error(), App::Document::getObject(), App::DocumentObject::recomputeFeature(), and Base::ConsoleSingleton::Warning().
Referenced by SectionCut().
onFlipYclicked
void SectionCut::onFlipYclicked () protected slot
References Base::Console(), Base::ConsoleSingleton::Error(), App::Document::getObject(), App::DocumentObject::recomputeFeature(), and Base::ConsoleSingleton::Warning().
Referenced by SectionCut().
onFlipZclicked
void SectionCut::onFlipZclicked () protected slot
References Base::Console(), Base::ConsoleSingleton::Error(), App::Document::getObject(), App::DocumentObject::recomputeFeature(), and Base::ConsoleSingleton::Warning().
Referenced by SectionCut().
onGroupBoxXtoggled
void SectionCut::onGroupBoxXtoggled () protected slot
Referenced by SectionCut().
onGroupBoxYtoggled
void SectionCut::onGroupBoxYtoggled () protected slot
Referenced by SectionCut().
onGroupBoxZtoggled
void SectionCut::onGroupBoxZtoggled () protected slot
Referenced by SectionCut().
onRefreshCutPBclicked
void SectionCut::onRefreshCutPBclicked () protected slot
References Gui::Application::activeDocument(), Base::Console(), Base::ConsoleSingleton::Error(), App::Document::getObject(), App::Document::getObjects(), PartGui::Ui_SectionCut::groupBoxX, PartGui::Ui_SectionCut::groupBoxY, PartGui::Ui_SectionCut::groupBoxZ, Gui::Application::Instance, and PartGui::Ui_SectionCut::RefreshCutPB.
Referenced by SectionCut().
onTransparencyChanged
void SectionCut::onTransparencyChanged (int val) protected slot
References onTransparencySliderMoved().
Referenced by SectionCut().
onTransparencySliderMoved
void SectionCut::onTransparencySliderMoved (int val) protected slot
References PartGui::Ui_SectionCut::CutTransparency, PartGui::Ui_SectionCut::groupBoxX, PartGui::Ui_SectionCut::groupBoxY, and PartGui::Ui_SectionCut::groupBoxZ.
Referenced by onTransparencyChanged(), and SectionCut().
reject()
void SectionCut::reject (void)
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/SectionCutting.h
FreeCAD/src/Mod/Part/Gui/SectionCutting.cpp