FreeCAD: TechDrawGui::TaskDlgProjGroup Class Reference
TechDrawGui::TaskDlgProjGroup Class Reference
Simulation dialog for the TaskView.
#include <TaskProjGroup.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void clicked (int)
is called by the framework if an button is clicked which has no accept or reject role
TechDraw::DrawProjGroup * getMultiView () const
virtual QDialogButtonBox::StandardButtons getStandardButtons () const
tells the framework which buttons are wished for the dialog
const ViewProviderProjGroup * getViewProvider () const
virtual void helpRequested ()
is called by the framework if the user presses the help button
virtual bool isAllowedAlterDocument (void) const
virtual void modifyStandardButtons (QDialogButtonBox *box)
virtual void open ()
is called the TaskView when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setCreateMode (bool b)
TaskDlgProjGroup (TechDraw::DrawProjGroup *featView, bool mode)
void update ()
~TaskDlgProjGroup ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
tells the framework which buttons are wished for the dialog
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Protected Attributes
TechDraw::DrawProjGroup * multiView
const ViewProviderProjGroup * viewProvider
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
Simulation dialog for the TaskView.
Constructor & Destructor Documentation
TaskDlgProjGroup()
TaskDlgProjGroup::TaskDlgProjGroup (TechDraw::DrawProjGroup * featView, bool mode)
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
~TaskDlgProjGroup()
TaskDlgProjGroup::~TaskDlgProjGroup ()
Member Function Documentation
accept()
bool TaskDlgProjGroup::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References TechDrawGui::TaskProjGroup::accept().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
clicked()
void TaskDlgProjGroup::clicked (int i) virtual
is called by the framework if an button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
References TechDrawGui::TaskProjGroup::apply().
getMultiView()
TechDraw::DrawProjGroup * TechDrawGui::TaskDlgProjGroup::getMultiView () const
References multiView.
getStandardButtons()
virtual QDialogButtonBox::StandardButtons TechDrawGui::TaskDlgProjGroup::getStandardButtons (void) const virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
getViewProvider()
const ViewProviderProjGroup * TechDrawGui::TaskDlgProjGroup::getViewProvider () const
References viewProvider.
Referenced by TechDrawGui::ViewProviderProjGroup::setEdit().
helpRequested()
virtual void TechDrawGui::TaskDlgProjGroup::helpRequested () virtual
is called by the framework if the user presses the help button
Reimplemented from Gui::TaskView::TaskDialog.
isAllowedAlterDocument()
virtual bool TechDrawGui::TaskDlgProjGroup::isAllowedAlterDocument (void) const virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
modifyStandardButtons()
void TaskDlgProjGroup::modifyStandardButtons (QDialogButtonBox * box) virtual
Reimplemented from Gui::TaskView::TaskDialog.
References TechDrawGui::TaskProjGroup::saveButtons().
open()
void TaskDlgProjGroup::open () virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
References App::GetApplication(), TechDrawGui::TaskProjGroup::getCreateMode(), and App::Application::setActiveTransaction().
reject()
bool TaskDlgProjGroup::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References TechDrawGui::TaskProjGroup::reject().
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
setCreateMode()
void TaskDlgProjGroup::setCreateMode (bool b)
References TechDrawGui::TaskProjGroup::setCreateMode().
Referenced by TechDrawGui::ViewProviderProjGroup::setEdit().
update()
void TaskDlgProjGroup::update ()
References TechDrawGui::TaskProjGroup::updateTask().
Referenced by ArchStructure.CommandStructuralSystem::Activated(), ArchAxisSystem.AxisSystemTaskPanel::addElement(), ArchComponent.ComponentTaskPanel::addElement(), ArchSectionPlane.SectionPlaneTaskPanel::addElement(), DraftGui.FacebinderTaskPanel::addElement(), femtaskpanels.task_result_mechanical._TaskPanel::calculate(), Spreadsheet_legacy.SpreadsheetView::changeCell(), draftguitools.gui_edit.Edit::endEditing(), draftguitools.gui_trackers.boxTracker::height(), draftguitools.gui_trackers.rectangleTracker::p3(), Plot.Plot::plot(), Spreadsheet_legacy.SpreadsheetView::recompute(), ArchAxisSystem.AxisSystemTaskPanel::removeElement(), ArchComponent.ComponentTaskPanel::removeElement(), ArchSectionPlane.SectionPlaneTaskPanel::removeElement(), DraftGui.FacebinderTaskPanel::removeElement(), draftguitools.gui_trackers.gridTracker::reset(), ArchNesting.Nester::run(), draftguitools.gui_trackers.gridTracker::setMainlines(), draftguitools.gui_trackers.gridTracker::setSize(), draftguitools.gui_trackers.gridTracker::setSpacing(), and draftguitools.gui_edit_arch_objects.ArchWallGuiTools::update_object_from_edit_points().
Member Data Documentation
multiView
TechDraw::DrawProjGroup* TechDrawGui::TaskDlgProjGroup::multiView protected
Referenced by getMultiView().
viewProvider
const ViewProviderProjGroup* TechDrawGui::TaskDlgProjGroup::viewProvider protected
Referenced by PathScripts.PathDressupDogbone.TaskPanel::cleanup(), PathPythonGui.simple_edit_panel.SimpleEditPanel::cleanup(), PathScripts.PathDressupPathBoundaryGui.TaskPanel::cleanup(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::cleanup(), getViewProvider(), PathScripts.PathDressupDogbone.TaskPanel::setupUi(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::setupUi(), PathScripts.PathDressupDogbone.TaskPanel::updateBoneList(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::updateTagsView(), and PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::whenTagSelectionChanged().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/TaskProjGroup.h
FreeCAD/src/Mod/TechDraw/Gui/TaskProjGroup.cpp