FreeCAD: PathScripts.PathSlotGui Namespace Reference
PathScripts.PathSlotGui Namespace Reference
Classes
class TaskPanelOpPage
Functions
def debugMsg (msg)
Variables
Command
bool DEBUG = False
Function Documentation
debugMsg()
def PathScripts.PathSlotGui.debugMsg (msg)
Referenced by PathScripts.PathSlotGui.TaskPanelOpPage.customizeReference_1(), PathScripts.PathSlotGui.TaskPanelOpPage.customizeReference_2(), PathScripts.PathSlotGui.TaskPanelOpPage.getFields(), PathScripts.PathSlotGui.TaskPanelOpPage.getForm(), PathScripts.PathSlotGui.TaskPanelOpPage.getSignalsForUpdate(), PathScripts.PathSlotGui.TaskPanelOpPage.initPage(), PathScripts.PathSlotGui.TaskPanelOpPage.setFields(), and PathScripts.PathSlotGui.TaskPanelOpPage.updateVisibility().
Variable Documentation
Command
PathScripts.PathSlotGui.Command
Initial value:
 =  PathOpGui.SetupOperation('Slot',
         PathSlot.Create,
         TaskPanelOpPage,
         'Path_Slot',
         QtCore.QT_TRANSLATE_NOOP("Path_Slot", "Slot"),
         QtCore.QT_TRANSLATE_NOOP("Path_Slot", "Create a Slot operation from selected geometry or custom points."),
         PathSlot.SetupProperties)
DEBUG
bool PathScripts.PathSlotGui.DEBUG = False