FreeCAD: VISCOUS_3D::_EdgesOnShape Struct Reference
VISCOUS_3D::_EdgesOnShape Struct Reference
_LayerEdge's on a shape and other shape data
Public Member Functions
bool GetNormal (const SMDS_MeshElement *face, gp_Vec &norm)
Returns normal of a face.
TopAbs_ShapeEnum ShapeType () const
TopAbs_ShapeEnum SWOLType () const
Detailed Description
_LayerEdge's on a shape and other shape data
Member Function Documentation
GetNormal()
bool _EdgesOnShape::GetNormal (const SMDS_MeshElement * face, gp_Vec & norm)
Returns normal of a face.
Referenced by VISCOUS_3D::_LayerEdge::SetNewLength().
ShapeType()
TopAbs_ShapeEnum VISCOUS_3D::_EdgesOnShape::ShapeType () const
Referenced by VISCOUS_3D::_LayerEdge::SetDataByNeighbors().
SWOLType()
TopAbs_ShapeEnum VISCOUS_3D::_EdgesOnShape::SWOLType () const
Referenced by VISCOUS_3D::_Shrinker1D::AddEdge(), VISCOUS_3D::_LayerEdge::Copy(), VISCOUS_3D::_LayerEdge::InvalidateStep(), VISCOUS_3D::_LayerEdge::LastSegment(), VISCOUS_3D::_LayerEdge::LastUV(), VISCOUS_3D::_LayerEdge::SetNewLength(), and VISCOUS_3D::_LayerEdge::SetNewLength2d().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_ViscousLayers.cpp