FreeCAD: Gui::Dialog::DlgCustomizeSpaceball Class Reference
Gui::Dialog::DlgCustomizeSpaceball Class Reference
#include <DlgCustomizeSpaceball.h>
Public Member Functions
DlgCustomizeSpaceball (QWidget *parent=nullptr)
virtual ~DlgCustomizeSpaceball ()
Public Member Functions inherited from Gui::Dialog::CustomizeActionPage
CustomizeActionPage (QWidget *parent=nullptr)
Construction.
virtual ~CustomizeActionPage ()
Destruction.
Protected Slots
void onAddMacroAction (const QByteArray &macroName)
void onModifyMacroAction (const QByteArray &macroName)
void onRemoveMacroAction (const QByteArray &macroName)
Protected Slots inherited from Gui::Dialog::CustomizeActionPage
virtual void onAddMacroAction (const QByteArray &)=0
virtual void onModifyMacroAction (const QByteArray &)=0
virtual void onRemoveMacroAction (const QByteArray &)=0
Protected Member Functions
void changeEvent (QEvent *e)
virtual bool event (QEvent *event)
virtual void hideEvent (QHideEvent *event)
virtual void showEvent (QShowEvent *event)
Protected Member Functions inherited from Gui::Dialog::CustomizeActionPage
virtual void changeEvent (QEvent *e)=0
bool event (QEvent *e)
Constructor & Destructor Documentation
DlgCustomizeSpaceball()
DlgCustomizeSpaceball::DlgCustomizeSpaceball (QWidget * parent = nullptr)
References draftgeoutils.intersections::connect().
~DlgCustomizeSpaceball()
DlgCustomizeSpaceball::~DlgCustomizeSpaceball () virtual
Member Function Documentation
changeEvent()
void DlgCustomizeSpaceball::changeEvent (QEvent * e) protected virtual
Implements Gui::Dialog::CustomizeActionPage.
event()
bool DlgCustomizeSpaceball::event (QEvent * event) protected virtual
References Spaceball::BUTTON_PRESSED, Spaceball::ButtonEvent::ButtonEventType, Spaceball::ButtonEvent::buttonNumber(), Spaceball::ButtonEvent::buttonStatus(), Gui::Dialog::CustomizeActionPage::event(), event(), Gui::Dialog::ButtonModel::goButtonPress(), Gui::Dialog::ButtonView::selectButton(), and Spaceball::EventBase::setHandled().
Referenced by event().
hideEvent()
void DlgCustomizeSpaceball::hideEvent (QHideEvent * event) protected virtual
onAddMacroAction
void DlgCustomizeSpaceball::onAddMacroAction (const QByteArray & macroName) protected slot
References Gui::Dialog::CommandModel::goAddMacro().
onModifyMacroAction
void DlgCustomizeSpaceball::onModifyMacroAction (const QByteArray & macroName) protected slot
onRemoveMacroAction
void DlgCustomizeSpaceball::onRemoveMacroAction (const QByteArray & macroName) protected slot
References Gui::Dialog::ButtonModel::goMacroRemoved(), and Gui::Dialog::CommandModel::goRemoveMacro().
showEvent()
void DlgCustomizeSpaceball::showEvent (QShowEvent * event) protected virtual
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgCustomizeSpaceball.h
FreeCAD/src/Gui/DlgCustomizeSpaceball.cpp