FreeCAD: e57::CompressedVectorNode Class Reference
e57::CompressedVectorNode Class Reference
#include <E57Format.h>
Public Member Functions
void checkInvariant (bool doRecurse=true, bool doUpcast=true)
Check whether CompressedVectorNode class invariant is true.
int64_t childCount () const
Get current number of records in a CompressedVectorNode.
VectorNode codecs () const
Get the codecs tree that describes the encoder/decoder configuration of the CompressedVectorNode.
CompressedVectorNode ()=delete
CompressedVectorNode (const Node &n)
Downcast a generic Node handle to a CompressedVectorNode handle.
CompressedVectorNode (ImageFile destImageFile, const Node &prototype, const VectorNode &codecs)
Create an empty CompressedVectorNode, for writing, that will store records specified by the prototype.
ImageFile destImageFile () const
Get the ImageFile that was declared as the destination for the node when it was created.
void dump (int indent=0, std::ostream &os=std::cout) const
Diagnostic function to print internal state of object to output stream in an indented format.
ustring elementName () const
Get elementName string, that identifies the node in its parent.
bool isAttached () const
Has node been attached into the tree of an ImageFile.
bool isRoot () const
Is this a root node.
operator Node () const
Upcast a CompressedVectorNode handle to a generic Node handle.
Node parent () const
Return parent of node, or self if a root node.
ustring pathName () const
Get absolute pathname of node.
Node prototype () const
Get the prototype tree that describes the types in the record.
CompressedVectorReader reader (const std::vector< SourceDestBuffer > &dbufs)
Create an iterator object for reading a series of blocks of data from a CompressedVectorNode.
CompressedVectorWriter writer (std::vector< SourceDestBuffer > &sbufs)
Create an iterator object for writing a series of blocks of data to a CompressedVectorNode.
Constructor & Destructor Documentation
CompressedVectorNode() [1/3]
e57::CompressedVectorNode::CompressedVectorNode () delete
CompressedVectorNode() [2/3]
CompressedVectorNode::CompressedVectorNode (ImageFile destImageFile, const Node & prototype, const VectorNode & codecs) explicit
Create an empty CompressedVectorNode, for writing, that will store records specified by the prototype.
Parameters
[in] destImageFile The ImageFile where the new node will eventually be stored.
[in] prototype A tree that describes the fields in each record of the CompressedVectorNode.
[in] codecs A VectorNode describing which codecs should be used for each field described in the prototype.
The destImageFile indicates which ImageFile the CompressedVectorNode will eventually be attached to. A node is attached to an ImageFile by adding it underneath the predefined root of the ImageFile (gotten from ImageFile::root). It is not an error to fail to attach the CompressedVectorNode to the destImageFile. It is an error to attempt to attach the CompressedVectorNode to a different ImageFile. The CompressedVectorNode may not be written to until it is attached to the destImageFile tree.
The prototype may be any tree consisting of only the following node types: IntegerNode, ScaledIntegerNode, FloatNode, StringNode, StructureNode, or VectorNode (i.e. CompressedVectorNode and BlobNode are not allowed). See CompressedVectorNode for discussion about the prototype argument.
The codecs must be a heterogeneous VectorNode with children as specified in the ASTM E57 data format standard. Since currently only one codec is supported (bitPackCodec), and it is the default, passing an empty VectorNode will specify that all record fields will be encoded with bitPackCodec.
Precondition
The destImageFile must be open (i.e. destImageFile.isOpen() must be true).
The destImageFile must have been opened in write mode (i.e. destImageFile.isWritable() must be true).
prototype must be an unattached root node (i.e. !prototype.isAttached() && prototype.isRoot())
prototype cannot contain BlobNodes or CompressedVectorNodes.
codecs must be an unattached root node (i.e. !codecs.isAttached() && codecs.isRoot())
Postcondition
prototype.isAttached()
codecs.isAttached()
Returns
A smart CompressedVectorNode handle referencing the underlying object.
Exceptions
E57_ERROR_IMAGEFILE_NOT_OPEN
E57_ERROR_FILE_IS_READ_ONLY
E57_ERROR_BAD_PROTOTYPE
E57_ERROR_BAD_CODECS
E57_ERROR_ALREADY_HAS_PARENT
E57_ERROR_DIFFERENT_DEST_IMAGEFILE
E57_ERROR_INTERNAL All objects in undocumented state
See also
SourceDestBuffer, Node, CompressedVectorNode::reader, CompressedVectorNode::writer
Because of shared_ptr quirks, can't set prototype,codecs in CompressedVectorNodeImpl(), so set it afterwards
References codecs().
CompressedVectorNode() [3/3]
CompressedVectorNode::CompressedVectorNode (const Node & n) explicit
Downcast a generic Node handle to a CompressedVectorNode handle.
Parameters
[in] n The generic handle to downcast.
The handle n must be for an underlying CompressedVectorNode, otherwise an exception is thrown. In designs that need to avoid the exception, use Node::type() to determine the actual type of the n before downcasting. This function must be explicitly called (c++ compiler cannot insert it automatically).
Returns
A smart CompressedVectorNode handle referencing the underlying object.
Exceptions
E57_ERROR_BAD_NODE_DOWNCAST
See also
Node::type(), CompressedVectorNode::operator, Node()
Set our shared_ptr to the downcast shared_ptr
References e57::E57_COMPRESSED_VECTOR, e57::E57_ERROR_BAD_NODE_DOWNCAST, and e57::toString().
Member Function Documentation
checkInvariant()
void CompressedVectorNode::checkInvariant (bool doRecurse = true, bool doUpcast = true)
Check whether CompressedVectorNode class invariant is true.
Parameters
[in] doRecurse If true, also check invariants of all children or sub-objects recursively.
[in] doUpcast If true, also check invariants of the generic Node class.
This function checks at least the assertions in the documented class invariant description (see class reference page for this object). Other internal invariants that are implementation-dependent may also be checked. If any invariant clause is violated, an E57Exception with errorCode of E57_ERROR_INVARIANCE_VIOLATION is thrown.
Checking the invariant recursively may be expensive if the tree is large, so should be used judiciously, in debug versions of the application.
Postcondition
No visible state is modified.
Exceptions
E57_ERROR_INVARIANCE_VIOLATION or any other E57 ErrorCode
References e57::Node::checkInvariant(), e57::VectorNode::checkInvariant(), codecs(), destImageFile(), e57::E57_ERROR_INVARIANCE_VIOLATION, isAttached(), isRoot(), and prototype().
Referenced by e57::Node::checkInvariant().
childCount()
int64_t CompressedVectorNode::childCount () const
Get current number of records in a CompressedVectorNode.
For a CompressedVectorNode with an active CompressedVectorWriter, the returned number will reflect any writes completed.
Precondition
The destination ImageFile must be open (i.e. destImageFile().isOpen()).
Postcondition
No visible state is modified.
Returns
Current number of records in CompressedVectorNode.
Exceptions
E57_ERROR_IMAGEFILE_NOT_OPEN
E57_ERROR_INTERNAL All objects in undocumented state
See also
CompressedVectorNode::reader, CompressedVectorNode::writer
codecs()
VectorNode CompressedVectorNode::codecs () const
Get the codecs tree that describes the encoder/decoder configuration of the CompressedVectorNode.
Precondition
The destination ImageFile must be open (i.e. destImageFile().isOpen()).
Postcondition
No visible state is modified.
Returns
A smart VectorNode handle referencing the root of the codecs tree.
Exceptions
E57_ERROR_IMAGEFILE_NOT_OPEN
E57_ERROR_INTERNAL All objects in undocumented state
See also
CompressedVectorNode::CompressedVectorNode, SourceDestBuffer, CompressedVectorNode::reader, CompressedVectorNode::writer
Referenced by checkInvariant(), and CompressedVectorNode().
destImageFile()
ImageFile CompressedVectorNode::destImageFile () const
Get the ImageFile that was declared as the destination for the node when it was created.
The first argument of the constructors of each of the 8 types of nodes is an ImageFile that indicates which ImageFile the node will eventually be attached to. This function returns that constructor argument. It is an error to attempt to attach the node to a different ImageFile. However it is not an error to not attach the node to any ImageFile (it's just wasteful). Use Node::isAttached to check if the node actually did get attached.
Postcondition
No visible object state is modified.
Returns
The ImageFile that was declared as the destination for the node when it was created.
See also
Node::isAttached, StructureNode::StructureNode(), VectorNode::VectorNode(), CompressedVectorNode::CompressedVectorNode(), IntegerNode::IntegerNode(), ScaledIntegerNode::ScaledIntegerNode(), FloatNode::FloatNode(), StringNode::StringNode(), BlobNode::BlobNode()
Referenced by e57::CompressedVectorReader::checkInvariant(), e57::CompressedVectorWriter::checkInvariant(), and checkInvariant().
dump()
void CompressedVectorNode::dump (int indent = 0, std::ostream & os = std::cout) const
Diagnostic function to print internal state of object to output stream in an indented format.
Parameters
[in] indent Number of spaces to indent all the printed lines of this object.
[in] os Output stream to print on.
All objects in the E57 Foundation API (with exception of E57Exception) support a dump() function. These functions print out to the console a detailed listing of the internal state of objects. The content of these printouts is not documented, and is really of interest only to implementation developers/maintainers or the really adventurous users. In implementations of the API other than the Reference Implementation, the dump() functions may produce no output (although the functions should still be defined). The output format may change from version to version.
Postcondition
No visible object state is modified.
Exceptions
No E57Exceptions
elementName()
ustring CompressedVectorNode::elementName () const
Get elementName string, that identifies the node in its parent.
The elementName is a string associated with each parent-child link between nodes. For a given parent, the elementName uniquely identifies each of its children. Thus, any node in a tree can be identified by a sequence of elementNames that form a path from the tree's root node (see Node::pathName for more details).
Three types of nodes (the container node types) can be parents: StructureNode, VectorNode, and CompressedVectorNode. The children of a StructureNode are explicitly given unique elementNames when they are attached to the parent (using StructureNode::set). The children of VectorNode and CompressedVectorNode are implicitly given elementNames based on their position in the list (starting at "0"). In a CompressedVectorNode, the elementName can become quite large: "1000000000" or more. However in a CompressedVectorNode, the elementName string is not stored in the file and is deduced by the position of the child.
Precondition
The destination ImageFile must be open (i.e. destImageFile().isOpen()).
Postcondition
No visible state is modified.
Returns
The element name of the node, or "" if a root node.
Exceptions
E57_ERROR_IMAGEFILE_NOT_OPEN
E57_ERROR_INTERNAL All objects in undocumented state
See also
Node::pathName, Node::parent, Node::isRoot
isAttached()
bool CompressedVectorNode::isAttached () const
Has node been attached into the tree of an ImageFile.
Nodes are attached into an ImageFile tree by inserting them as children (directly or indirectly) of the ImageFile's root node. Nodes can also be attached to an ImageFile if they are used in the codecs or prototype trees of an CompressedVectorNode that is attached. Attached nodes will be saved to disk when the ImageFile is closed, and restored when the ImageFile is read back in from disk. Unattached nodes will not be saved to disk. It is not recommended to create nodes that are not eventually attached to the ImageFile.
Precondition
The destination ImageFile must be open (i.e. destImageFile().isOpen()).
Postcondition
No visible object state is modified.
Returns
true if node is child of (or in codecs or prototype of a child CompressedVectorNode of) the root node of an ImageFile.
Exceptions
E57_ERROR_IMAGEFILE_NOT_OPEN
E57_ERROR_INTERNAL All objects in undocumented state
See also
Node::destImageFile, ImageFile::root
Referenced by e57::CompressedVectorReader::checkInvariant(), e57::CompressedVectorWriter::checkInvariant(), and checkInvariant().
isRoot()
bool CompressedVectorNode::isRoot () const
Is this a root node.
A root node has itself as a parent (it is not a child of any node). Newly constructed nodes (before they are inserted into an ImageFile tree) start out as root nodes. It is possible to temporarily create small trees that are unattached to any ImageFile. In these temporary trees, the top-most node will be a root node. After the tree is attached to the ImageFile tree, the only root node will be the pre-created one of the ImageTree (the one returned by ImageFile::root). The concept of attachment is slightly larger than that of the parent-child relationship (see Node::isAttached and CompressedVectorNode::CompressedVectorNode for more details).
Precondition
The destination ImageFile must be open (i.e. destImageFile().isOpen()).
Postcondition
No visible state is modified.
Returns
true if this node is a root node.
Exceptions
E57_ERROR_IMAGEFILE_NOT_OPEN
E57_ERROR_INTERNAL All objects in undocumented state
See also
Node::parent, Node::isAttached, CompressedVectorNode::CompressedVectorNode
Referenced by checkInvariant().
operator Node()
CompressedVectorNode::operator Node () const
Upcast a CompressedVectorNode handle to a generic Node handle.
An upcast is always safe, and the compiler can automatically insert it for initializations of Node variables and Node function arguments.
Returns
A smart Node handle referencing the underlying object.
Exceptions
No E57Exceptions.
See also
explanation in Node, Node::type(), CompressedVectorNode(const Node&)
Implicitly upcast from shared_ptr<CompressedVectorNodeImpl> to SharedNodeImplPtr and construct a Node object
parent()
Node CompressedVectorNode::parent () const
Return parent of node, or self if a root node.
Nodes are organized into trees (acyclic graphs) with a distinguished node (the "top-most" node) called the root node. A parent-child relationship is established between nodes to form a tree. Nodes can have zero or one parent. Nodes with zero parents are called root nodes. In the API, if a node has zero parents it is represented by having itself as a parent. Due to the set-once design of the API, a parent-child relationship cannot be modified once established. A child node can be any of the 8 node types, but a parent node can only be one of the 3 container node types (E57_STRUCTURE, E57_VECTOR, and E57_COMPRESSED_VECTOR). Each parent-child link has a string name (the elementName) associated with it (See Node::elementName for more details). More than one tree can be formed at any given time. Typically small trees are temporarily constructed before attachment to an ImageFile so that they will be written to the disk.
Warning: user algorithms that use this function to walk the tree must take care to handle the case where a node is its own parent (it is a root node). Use Node::isRoot to avoid infinite loops or infinite recursion.
Precondition
The destination ImageFile must be open (i.e. destImageFile().isOpen()).
Postcondition
No visible state is modified.
Returns
A smart Node handle referencing the parent node or this node if is a root node.
Exceptions
E57_ERROR_IMAGEFILE_NOT_OPEN
E57_ERROR_INTERNAL All objects in undocumented state
See also
Node::isRoot, Node::isAttached, CompressedVectorNode::CompressedVectorNode, Node::elementName
Referenced by PathScripts.PathSimulatorGui.CAMSimTaskUi::accept(), Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium(), PathScripts.PathSimulatorGui.CAMSimTaskUi::reject(), and PathScripts.PathOpGui.TaskPanelPage::setParent().
pathName()
ustring CompressedVectorNode::pathName () const
Get absolute pathname of node.
Nodes are organized into trees (acyclic graphs) by a parent-child relationship between nodes. Each parent-child relationship has an associated elementName string that is unique for a given parent. Any node in a given tree can be identified by a sequence of elementNames of how to get to the node from the root of the tree. An absolute pathname string that is formed by arranging this sequence of elementNames separated by the "/" character with a leading "/" prepended.
Some example absolute pathNames: "/data3D/0/points/153/cartesianX", "/data3D/0/points", "/cameraImages/1/pose/rotation/w", and "/". These examples have probably been attached to an ImageFile. Here is an example absolute pathName of a node in a pose tree that has not yet been attached to an ImageFile: "/pose/rotation/w".
A technical aside: the elementName of a root node does not appear in absolute pathnames, since the "path" is between the staring node (the root) and the ending node. By convention, in this API, a root node has the empty string ("") as its elementName.
Precondition
The destination ImageFile must be open (i.e. destImageFile().isOpen()).
Postcondition
No visible state is modified.
Returns
The absolute path name of the node.
Exceptions
E57_ERROR_IMAGEFILE_NOT_OPEN
E57_ERROR_INTERNAL All objects in undocumented state
See also
Node::elementName, Node::parent, Node::isRoot
prototype()
Node CompressedVectorNode::prototype () const
Get the prototype tree that describes the types in the record.
Precondition
The destination ImageFile must be open (i.e. destImageFile().isOpen()).
Postcondition
No visible state is modified.
Returns
A smart Node handle referencing the root of the prototype tree.
Exceptions
E57_ERROR_IMAGEFILE_NOT_OPEN
E57_ERROR_INTERNAL All objects in undocumented state
See also
CompressedVectorNode::CompressedVectorNode, SourceDestBuffer, CompressedVectorNode::reader, CompressedVectorNode::writer
Referenced by PathScripts.PathSetupSheetGui.OpTaskPanel::accept(), checkInvariant(), Points::E57Reader::read(), and PathScripts.PathSetupSheetGui.OpTaskPanel::setupUi().
reader()
CompressedVectorReader CompressedVectorNode::reader (const std::vector< SourceDestBuffer > & dbufs)
Create an iterator object for reading a series of blocks of data from a CompressedVectorNode.
Parameters
[in] dbufs Vector of memory buffers that will receive data read from a CompressedVectorNode.
The pathNames in the dbufs must identify terminal nodes (i.e. node that can have no children: IntegerNode, ScaledIntegerNode, FloatNode, StringNode) in this CompressedVectorNode's prototype. It is an error for two SourceDestBuffers in dbufs to identify the same terminal node in the prototype. It is not an error to create a CompressedVectorReader for an empty CompressedVectorNode.
Precondition
dbufs can't be empty
The destination ImageFile must be open (i.e. destImageFile().isOpen()).
The destination ImageFile can't have any writers open (destImageFile().writerCount()==0)
This CompressedVectorNode must be attached (i.e. isAttached()).
Returns
A smart CompressedVectorReader handle referencing the underlying iterator object.
Exceptions
E57_ERROR_BAD_API_ARGUMENT
E57_ERROR_IMAGEFILE_NOT_OPEN
E57_ERROR_TOO_MANY_WRITERS
E57_ERROR_NODE_UNATTACHED
E57_ERROR_PATH_UNDEFINED
E57_ERROR_BUFFER_SIZE_MISMATCH
E57_ERROR_BUFFER_DUPLICATE_PATHNAME
E57_ERROR_BAD_CV_HEADER
E57_ERROR_INTERNAL All objects in undocumented state
See also
CompressedVectorReader, SourceDestBuffer, CompressedVectorNode::CompressedVectorNode, CompressedVectorNode::prototype
Referenced by Points::E57Reader::read().
writer()
CompressedVectorWriter CompressedVectorNode::writer (std::vector< SourceDestBuffer > & sbufs)
Create an iterator object for writing a series of blocks of data to a CompressedVectorNode.
Parameters
[in] sbufs Vector of memory buffers that will hold data to be written to a CompressedVectorNode.
See CompressedVectorWriter::write(std::vector<SourceDestBuffer>&, unsigned) for discussion about restrictions on sbufs.
The pathNames in the sbufs must match one-to-one with the terminal nodes (i.e. nodes that can have no children: IntegerNode, ScaledIntegerNode, FloatNode, StringNode) in this CompressedVectorNode's prototype. It is an error for two SourceDestBuffers in dbufs to identify the same terminal node in the prototype.
It is an error to call this function if the CompressedVectorNode already has any records (i.e. a CompressedVectorNode cannot be set twice).
Precondition
sbufs can't be empty (i.e. sbufs.length() > 0).
The destination ImageFile must be open (i.e. destImageFile().isOpen()).
The destImageFile must have been opened in write mode (i.e. destImageFile.isWritable()).
The destination ImageFile can't have any readers or writers open (destImageFile().readerCount()==0 && destImageFile().writerCount()==0)
This CompressedVectorNode must be attached (i.e. isAttached()).
This CompressedVectorNode must have no records (i.e. childCount() == 0).
Returns
A smart CompressedVectorWriter handle referencing the underlying iterator object.
Exceptions
E57_ERROR_BAD_API_ARGUMENT
E57_ERROR_IMAGEFILE_NOT_OPEN
E57_ERROR_FILE_IS_READ_ONLY
E57_ERROR_SET_TWICE
E57_ERROR_TOO_MANY_WRITERS
E57_ERROR_TOO_MANY_READERS
E57_ERROR_NODE_UNATTACHED
E57_ERROR_PATH_UNDEFINED
E57_ERROR_BUFFER_SIZE_MISMATCH
E57_ERROR_BUFFER_DUPLICATE_PATHNAME
E57_ERROR_NO_BUFFER_FOR_ELEMENT
E57_ERROR_INTERNAL All objects in undocumented state
See also
CompressedVectorWriter, SourceDestBuffer, CompressedVectorNode::CompressedVectorNode, CompressedVectorNode::prototype
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/libE57Format/include/E57Format.h
FreeCAD/src/3rdParty/libE57Format/src/E57Format.cpp