FreeCAD: Gui::Breakpoint Class Reference
Gui::Breakpoint Class Reference
#include <PythonDebugger.h>
Public Member Functions
void addLine (int line)
Breakpoint ()
Breakpoint (const Breakpoint &)
bool checkBreakpoint (const QString &fn, int line)
bool checkLine (int line)
int countLines () const
const QString & filename () const
int lineIndex (int ind) const
Breakpoint & operator= (const Breakpoint &)
bool operator== (const Breakpoint &bp)
bool operator== (const QString &fn)
void removeLine (int line)
void setFilename (const QString &fn)
~Breakpoint ()
Constructor & Destructor Documentation
Breakpoint() [1/2]
Breakpoint::Breakpoint ()
Breakpoint() [2/2]
Breakpoint::Breakpoint (const Breakpoint & rBp)
References filename(), and setFilename().
~Breakpoint()
Breakpoint::~Breakpoint ()
Member Function Documentation
addLine()
void Breakpoint::addLine (int line)
Referenced by Gui::PythonDebugger::toggleBreakpoint().
checkBreakpoint()
bool Gui::Breakpoint::checkBreakpoint (const QString & fn, int line)
checkLine()
bool Breakpoint::checkLine (int line)
Referenced by Gui::PythonEditor::drawMarker().
countLines()
int Gui::Breakpoint::countLines () const
filename()
const QString & Gui::Breakpoint::filename () const
Referenced by ArchReference.ArchReferenceTaskPanel::accept(), Breakpoint(), ArchReference.ArchReferenceTaskPanel::chooseFile(), addonmanager_macro.Macro::is_installed(), operator=(), exportDRAWEXE.Drawexporter::process_object(), and exportDRAWEXE.Drawexporter::saveSweep().
lineIndex()
int Breakpoint::lineIndex (int ind) const
operator=()
Breakpoint & Breakpoint::operator= (const Breakpoint & rBp)
References filename(), and setFilename().
operator==() [1/2]
bool Gui::Breakpoint::operator== (const Breakpoint & bp)
operator==() [2/2]
bool Gui::Breakpoint::operator== (const QString & fn)
removeLine()
void Breakpoint::removeLine (int line)
setFilename()
void Breakpoint::setFilename (const QString & fn)
Referenced by Breakpoint(), operator=(), and Gui::PythonDebugger::toggleBreakpoint().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/PythonDebugger.h
Sources/FreeCAD/src/Gui/PythonDebugger.cpp