FreeCAD: SMESH_MeshEditor::ElemFeatures Struct Reference
SMESH_MeshEditor::ElemFeatures Struct Reference
< Features of element to create
#include <SMESH_MeshEditor.hxx>
Public Member Functions
SMESH_EXPORT ElemFeatures (SMDSAbs_ElementType type=SMDSAbs_All, bool isPoly=false, bool isQuad=false)
SMESH_EXPORT ElemFeatures & Init (const SMDS_MeshElement *elem, bool basicOnly=true)
Initializes members by an existing element.
SMESH_EXPORT ElemFeatures & Init (const std::vector< int > &quanities, bool isQuad=false)
SMESH_EXPORT ElemFeatures & Init (double diameter)
SMESH_EXPORT ElemFeatures & Init (SMDSAbs_ElementType type, bool isPoly=false, bool isQuad=false)
SMESH_EXPORT ElemFeatures & Init (std::vector< int > &quanities, bool isQuad=false)
SMESH_EXPORT ElemFeatures & SetID (int ID)
SMESH_EXPORT ElemFeatures & SetPoly (bool isPoly)
SMESH_EXPORT ElemFeatures & SetQuad (bool isQuad)
Public Attributes
double myBallDiameter
int myID
bool myIsPoly
bool myIsQuad
std::vector< int > myPolyhedQuantities
SMDSAbs_ElementType myType
Detailed Description
< Features of element to create
Constructor & Destructor Documentation
ElemFeatures()
SMESH_EXPORT SMESH_MeshEditor::ElemFeatures::ElemFeatures (SMDSAbs_ElementType type = SMDSAbs_All, bool isPoly = false, bool isQuad = false)
Member Function Documentation
Init() [1/5]
SMESH_MeshEditor::ElemFeatures & SMESH_MeshEditor::ElemFeatures::Init (const SMDS_MeshElement * elem, bool basicOnly = true)
Initializes members by an existing element.
Parameters
[in] elem - the source element
[in] basicOnly - if true, does not set additional data of Ball and Polyhedron
References SMDS_MeshElement::GetType(), SMDS_MeshElement::IsPoly(), SMDS_MeshElement::IsQuadratic(), myBallDiameter, myIsPoly, myIsQuad, myPolyhedQuantities, and myType.
Init() [2/5]
SMESH_EXPORT ElemFeatures& SMESH_MeshEditor::ElemFeatures::Init (const std::vector< int > & quanities, bool isQuad = false)
Init() [3/5]
SMESH_EXPORT ElemFeatures& SMESH_MeshEditor::ElemFeatures::Init (double diameter)
Init() [4/5]
SMESH_EXPORT ElemFeatures& SMESH_MeshEditor::ElemFeatures::Init (SMDSAbs_ElementType type, bool isPoly = false, bool isQuad = false)
Referenced by SMESH_MeshEditor::DoubleElements(), StdMeshers_Import_1D::importMesh(), SMESH_MeshEditor::MakeBoundaryMesh(), SMESH_MeshEditor::MergeNodes(), SMESH_MeshEditor::SewSideElements(), and SMESH_MeshEditor::Transform().
Init() [5/5]
SMESH_EXPORT ElemFeatures& SMESH_MeshEditor::ElemFeatures::Init (std::vector< int > & quanities, bool isQuad = false)
SetID()
SMESH_EXPORT ElemFeatures& SMESH_MeshEditor::ElemFeatures::SetID (int ID)
Referenced by SMESH_MeshEditor::MergeNodes(), and SMESH_MeshEditor::SewSideElements().
SetPoly()
SMESH_EXPORT ElemFeatures& SMESH_MeshEditor::ElemFeatures::SetPoly (bool isPoly)
Referenced by SMESH_MeshEditor::Make2DMeshFrom3D(), and SMESH_MeshEditor::MergeNodes().
SetQuad()
SMESH_EXPORT ElemFeatures& SMESH_MeshEditor::ElemFeatures::SetQuad (bool isQuad)
Referenced by SMESH_MeshEditor::Make2DMeshFrom3D(), and SMESH_MeshEditor::MergeNodes().
Member Data Documentation
myBallDiameter
double SMESH_MeshEditor::ElemFeatures::myBallDiameter
Referenced by SMESH_MeshEditor::AddElement(), and Init().
myID
int SMESH_MeshEditor::ElemFeatures::myID
Referenced by SMESH_MeshEditor::AddElement().
myIsPoly
bool SMESH_MeshEditor::ElemFeatures::myIsPoly
Referenced by SMESH_MeshEditor::AddElement(), and Init().
myIsQuad
bool SMESH_MeshEditor::ElemFeatures::myIsQuad
Referenced by SMESH_MeshEditor::AddElement(), Init(), and SMESH_MeshEditor::MergeNodes().
myPolyhedQuantities
std::vector<int> SMESH_MeshEditor::ElemFeatures::myPolyhedQuantities
Referenced by SMESH_MeshEditor::AddElement(), and Init().
myType
SMDSAbs_ElementType SMESH_MeshEditor::ElemFeatures::myType
Referenced by SMESH_MeshEditor::AddElement(), and Init().
The documentation for this struct was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_MeshEditor.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/SMESH_MeshEditor.cpp