FreeCAD: Base::Exception Class Reference
Base::Exception Class Reference
#include <Exception.h>
Public Member Functions
std::string getFile () const
std::string getFunction () const
int getLine () const
std::string getMessage () const
virtual PyObject * getPyExceptionType () const
returns the corresponding python exception type
virtual PyObject * getPyObject ()
returns a Python dictionary containing the exception data
bool getReported () const
bool getTranslatable () const
virtual Base::Type getTypeId (void) const
Exception & operator= (const Exception &inst)
virtual void ReportException () const
Reports exception. It includes a mechanism to only report an exception once.
void setDebugInformation (const std::string &file, const int line, const std::string &function)
setter methods for including debug information intended to use via macro for autofilling of debugging information
void setMessage (const char *sMessage)
void setMessage (const std::string &sMessage)
virtual void setPyException () const
Sets the Python error indicator and an error message.
virtual void setPyObject (PyObject *pydict)
returns sets the exception data from a Python dictionary
void setReported (bool reported)
void setTranslatable (bool translatable)
virtual const char * what () const throw ()
virtual ~Exception () throw ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static void * create (void)
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Protected Member Functions
Exception ()
Exception (const char *sMessage)
Exception (const Exception &inst)
Exception (const std::string &sMessage)
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
~Exception()
virtual Base::Exception::~Exception () throw () virtual
Exception() [1/4]
Exception::Exception (const char * sMessage) protected
Exception() [2/4]
Exception::Exception (const std::string & sMessage) protected
Exception() [3/4]
Exception::Exception () protected
Exception() [4/4]
Exception::Exception (const Exception & inst) protected
Member Function Documentation
create()
void * Exception::create (void) static
Referenced by draftguitools.gui_labels.Label::action().
getClassTypeId()
Base::Type Exception::getClassTypeId (void) static
Referenced by App::FeatureTestException::FeatureTestException(), and Spreadsheet::Sheet::recomputeCell().
getFile()
std::string Exception::getFile () const
Referenced by ArchReference.ArchReference::execute(), ArchReference.ArchReference::getColors(), ArchReference.ArchReference::getPartsList(), and getPyObject().
getFunction()
std::string Exception::getFunction () const
Referenced by getPyObject().
getLine()
int Exception::getLine () const
Referenced by getPyObject().
getMessage()
std::string Exception::getMessage () const
Referenced by getPyObject().
getPyExceptionType()
PyObject * Exception::getPyExceptionType (void) const virtual
returns the corresponding python exception type
Reimplemented in Base::BadGraphError, Base::CADKernelError, Base::AbortException, Base::XMLBaseException, Base::XMLParseException, Base::XMLAttributeError, Base::FileException, Base::FileSystemError, Base::BadFormatError, Base::MemoryException, Base::AccessViolation, Base::AbnormalProgramTermination, Base::UnknownProgramOption, Base::TypeError, Base::ValueError, Base::IndexError, Base::NameError, Base::ImportError, Base::AttributeError, Base::RuntimeError, Base::NotImplementedError, Base::ZeroDivisionError, Base::ReferenceError, Base::ExpressionError, Base::ParserError, Base::UnicodeError, Base::OverflowError, Base::UnderflowError, Base::UnitsMismatchError, Base::RestoreError, and Base::PyException.
References Base::PyExc_FC_GeneralError.
Referenced by setPyException().
getPyObject()
PyObject * Exception::getPyObject (void) virtual
returns a Python dictionary containing the exception data
Reimplemented from Base::BaseClass.
Reimplemented in Base::FileException.
References getFile(), getFunction(), getLine(), getMessage(), getTranslatable(), and what().
Referenced by Base::FileException::getPyObject().
getReported()
bool Base::Exception::getReported () const
getTranslatable()
bool Exception::getTranslatable () const
Referenced by getPyObject().
getTypeId()
Base::Type Exception::getTypeId (void) const virtual
Reimplemented from Base::BaseClass.
init()
void Exception::init (void) static
Referenced by App::Application::initTypes(), and DocumentObject.DocumentObject::onChanged().
operator=()
Exception & Exception::operator= (const Exception & inst)
Referenced by Base::FileException::operator=(), and Base::MemoryException::operator=().
ReportException()
void Exception::ReportException () const virtual
Reports exception. It includes a mechanism to only report an exception once.
Reimplemented in Base::FileException, and Base::PyException.
Referenced by PartDesignGui::TaskRevolutionParameters::fillAxisCombo(), PartDesignGui::TaskRevolutionParameters::TaskRevolutionParameters(), PartDesignGui::TaskHelixParameters::~TaskHelixParameters(), and PartDesignGui::TaskRevolutionParameters::~TaskRevolutionParameters().
setDebugInformation()
void Exception::setDebugInformation (const std::string & file, const int line, const std::string & function)
setter methods for including debug information intended to use via macro for autofilling of debugging information
setMessage() [1/2]
void Exception::setMessage (const char * sMessage)
Referenced by Attacher::ExceptionCancel::ExceptionCancel(), SketcherGui::ExceptionWrongInput::ExceptionWrongInput(), and Base::InterpreterSingleton::runInteractiveString().
setMessage() [2/2]
void Exception::setMessage (const std::string & sMessage)
setPyException()
void Exception::setPyException () const virtual
Sets the Python error indicator and an error message.
Reimplemented in Base::PyException.
References getPyExceptionType(), Base::PyExc_FC_GeneralError, and what().
setPyObject()
void Exception::setPyObject (PyObject * pydict) virtual
returns sets the exception data from a Python dictionary
Reimplemented from Base::BaseClass.
Reimplemented in Base::FileException.
Referenced by Base::PyException::PyException(), and Base::FileException::setPyObject().
setReported()
void Base::Exception::setReported (bool reported)
setTranslatable()
void Exception::setTranslatable (bool translatable)
what()
const char * Exception::what (void) const throw () virtual
Reimplemented in Base::AbortException, Base::XMLParseException, Base::XMLAttributeError, and Base::FileException.
Referenced by PartGui::DlgRevolution::accept(), PartGui::DlgExtrusion::apply(), App::Origin::execute(), App::OriginGroupExtension::extensionExecute(), PartDesignGui::TaskTransformedParameters::fillAxisCombo(), PartDesignGui::TaskTransformedParameters::fillPlanesCombo(), getPyObject(), Gui::ViewProviderOrigin::onChanged(), Base::PyException::ReportException(), setPyException(), Base::PyException::setPyException(), Gui::ViewProviderOrigin::setTemporaryVisibility(), PartDesignGui::TaskBoxPrimitives::TaskBoxPrimitives(), PartDesignGui::ViewProviderBody::updateOriginDatumSize(), Gui::ViewProviderOriginGroupExtension::updateOriginSize(), PartGui::DlgExtrusion::validate(), PartGui::DlgRevolution::validate(), Base::AbortException::what(), Base::XMLParseException::what(), Base::XMLAttributeError::what(), PartDesignGui::TaskBoxPrimitives::~TaskBoxPrimitives(), PartDesignGui::TaskLinearPatternParameters::~TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::~TaskMirroredParameters(), and PartDesignGui::TaskPolarPatternParameters::~TaskPolarPatternParameters().
The documentation for this class was generated from the following files:
FreeCAD/src/Base/Exception.h
FreeCAD/src/Base/Exception.cpp