FreeCAD: PathScripts.post.fablin_post Namespace Reference
PathScripts.post.fablin_post Namespace Reference
Functions
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
def processArguments (argstring)
Variables
string COMMAND_SPACE = " "
dictionary CORNER_MAX = {"x": 500, "y": 300, "z": 300}
dictionary CORNER_MIN = {"x": 0, "y": 0, "z": 0}
int LINENR = 100
string MACHINE_NAME = "FABLIN"
bool MODAL = False
now = datetime.datetime.now()
bool OUTPUT_COMMENTS = False
bool OUTPUT_HEADER = False
bool OUTPUT_LINE_NUMBERS = False
bool OUTPUT_TOOL_CHANGE = False
string POST_OPERATION = """"""
string POSTAMBLE
string PRE_OPERATION = """"""
string PREAMBLE
pythonopen = open
int RAPID_FEEDRATE = 10000
list RAPID_MOVES = ["G0", "G00"]
bool SHOW_EDITOR = True
list SUPPRESS_COMMANDS = ["G98", "G80", "M6", "G17"]
string TOOL_CHANGE = """"""
string TOOLTIP_ARGS
string UNITS = ""
Function Documentation
export()
def PathScripts.post.fablin_post.export (objectslist, filename, argstring)
References PathScripts.post.fablin_post.linenumber(), PathScripts.post.fablin_post.parse(), PathScripts.post.fablin_post.processArguments(), and PathScripts.post.fablin_post.pythonopen.
linenumber()
def PathScripts.post.fablin_post.linenumber ()
Referenced by PathScripts.post.fablin_post.export(), and PathScripts.post.fablin_post.parse().
parse()
def PathScripts.post.fablin_post.parse (pathobj)
References PathScripts.post.fablin_post.linenumber(), and PathScripts.post.fablin_post.parse().
Referenced by PathScripts.post.fablin_post.export(), and PathScripts.post.fablin_post.parse().
processArguments()
def PathScripts.post.fablin_post.processArguments (argstring)
Referenced by PathScripts.post.fablin_post.export().
Variable Documentation
COMMAND_SPACE
string PathScripts.post.fablin_post.COMMAND_SPACE = " "
CORNER_MAX
dictionary PathScripts.post.fablin_post.CORNER_MAX = {"x": 500, "y": 300, "z": 300}
CORNER_MIN
dictionary PathScripts.post.fablin_post.CORNER_MIN = {"x": 0, "y": 0, "z": 0}
LINENR
int PathScripts.post.fablin_post.LINENR = 100
MACHINE_NAME
string PathScripts.post.fablin_post.MACHINE_NAME = "FABLIN"
MODAL
bool PathScripts.post.fablin_post.MODAL = False
now
PathScripts.post.fablin_post.now = datetime.datetime.now()
OUTPUT_COMMENTS
bool PathScripts.post.fablin_post.OUTPUT_COMMENTS = False
OUTPUT_HEADER
bool PathScripts.post.fablin_post.OUTPUT_HEADER = False
OUTPUT_LINE_NUMBERS
bool PathScripts.post.fablin_post.OUTPUT_LINE_NUMBERS = False
OUTPUT_TOOL_CHANGE
bool PathScripts.post.fablin_post.OUTPUT_TOOL_CHANGE = False
POST_OPERATION
string PathScripts.post.fablin_post.POST_OPERATION = """"""
POSTAMBLE
string PathScripts.post.fablin_post.POSTAMBLE
Initial value:
=  """M5
G00 X-1.0 Y1.0
G90
"""
PRE_OPERATION
string PathScripts.post.fablin_post.PRE_OPERATION = """"""
PREAMBLE
string PathScripts.post.fablin_post.PREAMBLE
Initial value:
=  """G90
"""
pythonopen
PathScripts.post.fablin_post.pythonopen = open
Referenced by PathScripts.post.fablin_post.export().
RAPID_FEEDRATE
int PathScripts.post.fablin_post.RAPID_FEEDRATE = 10000
RAPID_MOVES
list PathScripts.post.fablin_post.RAPID_MOVES = ["G0", "G00"]
SHOW_EDITOR
bool PathScripts.post.fablin_post.SHOW_EDITOR = True
SUPPRESS_COMMANDS
list PathScripts.post.fablin_post.SUPPRESS_COMMANDS = ["G98", "G80", "M6", "G17"]
TOOL_CHANGE
string PathScripts.post.fablin_post.TOOL_CHANGE = """"""
TOOLTIP_ARGS
string PathScripts.post.fablin_post.TOOLTIP_ARGS
Initial value:
=  """
Arguments for fablin:
    --rapids-feedrate                ... feedrate to be used for rapids (e.g. --rapids-feedrate=300)
    --header,--no-header             ... output headers (--header)
    --comments,--no-comments         ... output comments (--comments)
    --line-numbers,--no-line-numbers ... prefix with line numbers (--no-lin-numbers)
    --show-editor, --no-show-editor  ... pop up editor before writing output(--show-editor)
"""
UNITS
string PathScripts.post.fablin_post.UNITS = ""