FreeCAD: Part::Geom2dCurve Class Reference
Part::Geom2dCurve Class Reference
#include <Geometry2d.h>
Public Member Functions
bool closestParameter (const Base::Vector2d &point, double &u) const
bool closestParameterToBasicCurve (const Base::Vector2d &point, double &u) const
Base::Vector2d firstDerivativeAtParameter (double u) const
Geom2dCurve ()
bool normal (double u, gp_Dir2d &dir) const
Base::Vector2d pointAtParameter (double u) const
Base::Vector2d secondDerivativeAtParameter (double u) const
bool tangent (double u, gp_Dir2d &) const
virtual TopoDS_Shape toShape () const
virtual ~Geom2dCurve ()
Public Member Functions inherited from Part::Geometry2d
virtual Geometry2d * clone (void) const =0
returns a cloned object
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual const Handle (Geom2d_Geometry) &handle() const =0
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
virtual TopoDS_Shape toShape () const =0
virtual ~Geometry2d ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Protected Member Functions inherited from Part::Geometry2d
Geometry2d ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
Geom2dCurve()
Geom2dCurve::Geom2dCurve ()
~Geom2dCurve()
Geom2dCurve::~Geom2dCurve () virtual
Member Function Documentation
closestParameter()
bool Geom2dCurve::closestParameter (const Base::Vector2d & point, double & u) const
References Part::Geometry2d::Handle().
Referenced by closestParameterToBasicCurve().
closestParameterToBasicCurve()
bool Geom2dCurve::closestParameterToBasicCurve (const Base::Vector2d & point, double & u) const
References closestParameter(), and Part::Geometry2d::Handle().
firstDerivativeAtParameter()
Base::Vector2d Geom2dCurve::firstDerivativeAtParameter (double u) const
References Part::Geometry2d::Handle(), and draftgeoutils.general::vec().
normal()
bool Geom2dCurve::normal (double u, gp_Dir2d & dir) const
References Part::Geometry2d::Handle().
Referenced by draftguitools.gui_trackers.arcTracker::getAngle(), draftguitools.gui_trackers.arcTracker::getDeviation(), draftguitools.gui_trackers.arcTracker::recompute(), and draftguitools.gui_trackers.arcTracker::setBy3Points().
pointAtParameter()
Base::Vector2d Geom2dCurve::pointAtParameter (double u) const
References Part::Geometry2d::Handle().
secondDerivativeAtParameter()
Base::Vector2d Geom2dCurve::secondDerivativeAtParameter (double u) const
References Part::Geometry2d::Handle(), and draftgeoutils.general::vec().
tangent()
bool Geom2dCurve::tangent (double u, gp_Dir2d & dir) const
References Part::Geometry2d::Handle().
toShape()
TopoDS_Shape Geom2dCurve::toShape () const virtual
Implements Part::Geometry2d.
References Part::Geometry2d::Handle().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/App/Geometry2d.h
FreeCAD/src/Mod/Part/App/Geometry2d.cpp