FreeCAD: Gui::DocumentIndex Class Reference
Gui::DocumentIndex Class Reference
Public Member Functions
ViewProviderIndex * cloneViewProvider (const ViewProviderDocumentObject &) const
QVariant data (int role) const
DocumentIndex (const Gui::Document &d)
void findViewProviders (const ViewProviderDocumentObject &, QList< ViewProviderIndex * > &) const
int rowOfViewProvider (const ViewProviderDocumentObject &) const
~DocumentIndex ()
Public Member Functions inherited from Gui::DocumentModelIndex
void appendChild (DocumentModelIndex *child)
DocumentModelIndex * child (int row)
int childCount () const
virtual QVariant data (int role) const
virtual Qt::ItemFlags flags () const
DocumentModelIndex * parent () const
QList< DocumentModelIndex * > removeAll ()
void removeChild (int row)
int row () const
virtual bool setData (const QVariant &value, int role)
void setParent (DocumentModelIndex *parent)
virtual ~DocumentModelIndex ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Attributes
const Gui::Document & d
Friends
class ViewProviderIndex
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Protected Member Functions inherited from Gui::DocumentModelIndex
DocumentModelIndex ()
void reset ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::DocumentModelIndex
QList< DocumentModelIndex * > childItems
DocumentModelIndex * parentItem
Constructor & Destructor Documentation
DocumentIndex()
Gui::DocumentIndex::DocumentIndex (const Gui::Document & d)
References Gui::BitmapFactory().
~DocumentIndex()
Gui::DocumentIndex::~DocumentIndex ()
References Gui::DocumentModelIndex::childItems.
Member Function Documentation
cloneViewProvider()
ViewProviderIndex * Gui::DocumentIndex::cloneViewProvider (const ViewProviderDocumentObject & vp) const
References ViewProviderIndex.
data()
QVariant Gui::DocumentIndex::data (int role) const virtual
Reimplemented from Gui::DocumentModelIndex.
References Gui::Application::activeDocument(), d, Gui::Document::getDocument(), and Gui::Application::Instance.
Referenced by Mod.Show.mTempoVis.TempoVis::activateWorkbench(), Mod.Show.SceneDetail.SceneDetail::apply_data(), importIFClegacy.IfcSchema::capitalize(), Mod.Show.mTempoVis.TempoVis::forget(), Mod.Show.mTempoVis.TempoVis::forgetDetail(), Mod.Show.mTempoVis.TempoVis::has(), ArchSchedule.CommandArchSchedule::IsActive(), importIFClegacy.IfcSchema::readEntities(), importIFClegacy.IfcSchema::readTypes(), Mod.Show.mTempoVis.TempoVis::restore(), Mod.Show.mTempoVis.TempoVis::save(), Mod.Show.mTempoVis.TempoVis::stored_val(), FeaturePython.ViewProviderOctahedron::updateData(), and Dice3DS.dom3ds.UndefinedChunk::write().
findViewProviders()
void Gui::DocumentIndex::findViewProviders (const ViewProviderDocumentObject & vp, QList< ViewProviderIndex * > & index) const
References Gui::DocumentModelIndex::childItems, and Gui::ViewProviderIndex::findViewProviders().
rowOfViewProvider()
int Gui::DocumentIndex::rowOfViewProvider (const ViewProviderDocumentObject & vp) const
References Gui::DocumentModelIndex::childItems.
Friends And Related Function Documentation
ViewProviderIndex
friend class ViewProviderIndex friend
Referenced by cloneViewProvider().
Member Data Documentation
d
const Gui::Document& Gui::DocumentIndex::d
Referenced by data().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/DocumentModel.cpp