FreeCAD: Gui::Dialog::DlgGeneralImp Class Reference
Gui::Dialog::DlgGeneralImp Class Reference
This class implements the settings for the application.
#include <DlgGeneralImp.h>
Public Member Functions
DlgGeneralImp (QWidget *parent=nullptr)
Constructs a DlgGeneralImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
void loadSettings ()
void saveSettings ()
~DlgGeneralImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Slots
void newPreferencePackDialogAccepted ()
void onLoadPreferencePackClicked (const std::string &packName)
void onManagePreferencePacksClicked ()
void recreatePreferencePackMenu ()
Protected Member Functions
void changeEvent (QEvent *e)
virtual void changeEvent (QEvent *e)=0
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Detailed Description
This class implements the settings for the application.
You can change window style, size of pixmaps, size of recent file list and so on
Author
Werner Mayer
Constructor & Destructor Documentation
DlgGeneralImp()
DlgGeneralImp::DlgGeneralImp (QWidget * parent = nullptr)
Constructs a DlgGeneralImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
References Gui::PreferencePackManager::configBackups(), draftgeoutils.intersections::connect(), Gui::Application::Instance, onManagePreferencePacksClicked(), Gui::Application::prefPackManager(), recreatePreferencePackMenu(), Gui::Application::workbenches(), Gui::Application::workbenchIcon(), and Gui::Application::workbenchMenuText().
~DlgGeneralImp()
DlgGeneralImp::~DlgGeneralImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void DlgGeneralImp::changeEvent (QEvent * e) protected virtual
Implements Gui::Dialog::PreferencePage.
loadSettings()
void DlgGeneralImp::loadSettings () virtual
Implements Gui::Dialog::PreferencePage.
References Gui::Translator::activeLanguage(), App::Application::Config(), App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), Gui::getMainWindow(), App::Application::GetParameterGroupByPath(), Gui::Translator::instance(), and Gui::Translator::supportedLocales().
newPreferencePackDialogAccepted
void DlgGeneralImp::newPreferencePackDialogAccepted () protected slot
References Gui::Application::Instance, Gui::Application::prefPackManager(), recreatePreferencePackMenu(), Gui::PreferencePackManager::save(), and Gui::PreferencePackManager::templateFiles().
onLoadPreferencePackClicked
void DlgGeneralImp::onLoadPreferencePackClicked (const std::string & packName) protected slot
References Gui::Application::Instance.
Referenced by recreatePreferencePackMenu().
onManagePreferencePacksClicked
void DlgGeneralImp::onManagePreferencePacksClicked () protected slot
References draftgeoutils.intersections::connect(), Gui::Dialog::DlgPreferencePackManagementImp::packVisibilityChanged(), and recreatePreferencePackMenu().
Referenced by DlgGeneralImp().
recreatePreferencePackMenu
void DlgGeneralImp::recreatePreferencePackMenu () protected slot
References draftgeoutils.intersections::connect(), Gui::Application::Instance, onLoadPreferencePackClicked(), Gui::PreferencePackManager::preferencePacks(), Gui::Application::prefPackManager(), and Gui::PreferencePackManager::rescan().
Referenced by DlgGeneralImp(), newPreferencePackDialogAccepted(), and onManagePreferencePacksClicked().
saveSettings()
void DlgGeneralImp::saveSettings () virtual
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), ParameterGrp::GetBool(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), Gui::getMainWindow(), App::Application::GetParameterGroupByPath(), Gui::Application::Instance, ParameterGrp::SetASCII(), ParameterGrp::SetBool(), ParameterGrp::SetInt(), and Gui::Application::setStyleSheet().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgGeneralImp.h
FreeCAD/src/Gui/DlgGeneralImp.cpp