FreeCAD: Gui::Dialog::DlgCustomKeyboardImp Class Reference
Gui::Dialog::DlgCustomKeyboardImp Class Reference
Shows an overview of all available commands of all groups and modules.
#include <DlgKeyboardImp.h>
Public Member Functions
DlgCustomKeyboardImp (QWidget *parent=0)
Constructs a DlgCustomKeyboardImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
~DlgCustomKeyboardImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::CustomizeActionPage
CustomizeActionPage (QWidget *parent=0)
Construction.
virtual ~CustomizeActionPage ()
Destruction.
Protected Slots
void on_buttonAssign_clicked ()
Assigns a new accelerator to the selected command.
void on_buttonClear_clicked ()
Clears the accelerator of the selected command.
void on_buttonReset_clicked ()
Resets the accelerator of the selected command to the default.
void on_buttonResetAll_clicked ()
Resets the accelerator of all commands to the default.
void on_categoryBox_activated (int index)
Shows all commands of this category.
void on_commandTreeWidget_currentItemChanged (QTreeWidgetItem *)
Shows the description for the corresponding command.
void on_editShortcut_textChanged (const QString &)
Checks for an already occupied shortcut.
void onAddMacroAction (const QByteArray &)
void onModifyMacroAction (const QByteArray &)
void onRemoveMacroAction (const QByteArray &)
Protected Slots inherited from Gui::Dialog::CustomizeActionPage
virtual void onAddMacroAction (const QByteArray &)=0
virtual void onModifyMacroAction (const QByteArray &)=0
virtual void onRemoveMacroAction (const QByteArray &)=0
Protected Member Functions
void changeEvent (QEvent *e)
void setShortcutOfCurrentAction (const QString &)
void showEvent (QShowEvent *e)
Protected Member Functions inherited from Gui::Dialog::CustomizeActionPage
bool event (QEvent *e)
Detailed Description
Shows an overview of all available commands of all groups and modules.
You can customize your workbenches just by drag&dropping any commands onto the toolbars or commandbars. But you cannot modify any standard toolbars or commandbars such as "File, View, ...". It is only possible to customize your own toolbars or commandbars.
Author
Werner Mayer
Constructor & Destructor Documentation
DlgCustomKeyboardImp()
DlgCustomKeyboardImp::DlgCustomKeyboardImp (QWidget * parent = 0)
Constructs a DlgCustomKeyboardImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
References Gui::Application::commandManager(), Gui::CommandManager::getCommands(), and Gui::Application::Instance.
~DlgCustomKeyboardImp()
DlgCustomKeyboardImp::~DlgCustomKeyboardImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void DlgCustomKeyboardImp::changeEvent (QEvent * e) protected virtual
Implements Gui::Dialog::CustomizeActionPage.
References Gui::Application::commandManager(), Gui::CommandManager::getGroupCommands(), Gui::Application::Instance, and on_categoryBox_activated().
on_buttonAssign_clicked
void DlgCustomKeyboardImp::on_buttonAssign_clicked () protected slot
Assigns a new accelerator to the selected command.
References setShortcutOfCurrentAction().
on_buttonClear_clicked
void DlgCustomKeyboardImp::on_buttonClear_clicked () protected slot
Clears the accelerator of the selected command.
References setShortcutOfCurrentAction().
on_buttonReset_clicked
void DlgCustomKeyboardImp::on_buttonReset_clicked () protected slot
Resets the accelerator of the selected command to the default.
References Gui::Application::commandManager(), Gui::CommandBase::getAccel(), Gui::CommandBase::getAction(), Gui::CommandManager::getCommandByName(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), Gui::Application::Instance, ParameterGrp::RemoveASCII(), Gui::Action::setShortcut(), and Gui::Action::shortcut().
on_buttonResetAll_clicked
void DlgCustomKeyboardImp::on_buttonResetAll_clicked () protected slot
Resets the accelerator of all commands to the default.
References Gui::Application::commandManager(), Gui::CommandManager::getAllCommands(), Gui::WindowParameter::getDefaultParameter(), Gui::Application::Instance, and ParameterGrp::RemoveGrp().
on_categoryBox_activated
void DlgCustomKeyboardImp::on_categoryBox_activated (int index) protected slot
Shows all commands of this category.
References Gui::BitmapFactory(), Gui::Application::commandManager(), Gui::CommandManager::getGroupCommands(), and Gui::Application::Instance.
Referenced by changeEvent(), and showEvent().
on_commandTreeWidget_currentItemChanged
void DlgCustomKeyboardImp::on_commandTreeWidget_currentItemChanged (QTreeWidgetItem * item) protected slot
Shows the description for the corresponding command.
References Gui::Application::commandManager(), Gui::CommandBase::getAccel(), Gui::CommandBase::getAction(), Gui::CommandManager::getCommandByName(), Gui::Application::Instance, and Gui::Action::shortcut().
on_editShortcut_textChanged
void DlgCustomKeyboardImp::on_editShortcut_textChanged (const QString & sc) protected slot
Checks for an already occupied shortcut.
References Gui::BitmapFactory(), Gui::Application::commandManager(), Base::Console(), Gui::CommandBase::getAction(), Gui::CommandManager::getAllCommands(), Gui::CommandManager::getCommandByName(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), Gui::Command::getName(), Gui::Application::Instance, ParameterGrp::RemoveASCII(), Gui::Action::shortcut(), and Base::ConsoleSingleton::Warning().
onAddMacroAction
void DlgCustomKeyboardImp::onAddMacroAction (const QByteArray & macro) protected slot
References Gui::BitmapFactory(), Gui::Application::commandManager(), Gui::CommandManager::getCommandByName(), Gui::CommandBase::getMenuText(), Gui::CommandBase::getPixmap(), Gui::CommandBase::getToolTipText(), and Gui::Application::Instance.
onModifyMacroAction
void DlgCustomKeyboardImp::onModifyMacroAction (const QByteArray & macro) protected slot
References Gui::BitmapFactory(), Gui::Application::commandManager(), Gui::CommandManager::getCommandByName(), Gui::CommandBase::getMenuText(), Gui::CommandBase::getPixmap(), Gui::CommandBase::getToolTipText(), and Gui::Application::Instance.
onRemoveMacroAction
void DlgCustomKeyboardImp::onRemoveMacroAction (const QByteArray & macro) protected slot
setShortcutOfCurrentAction()
void DlgCustomKeyboardImp::setShortcutOfCurrentAction (const QString & accelText) protected
References Gui::CommandBase::className(), Gui::Application::commandManager(), Gui::CommandBase::getAction(), App::GetApplication(), Gui::CommandManager::getCommandByName(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), Gui::Command::getName(), App::Application::GetParameterGroupByPath(), Gui::CommandBase::getStatusTip(), Gui::CommandBase::getToolTipText(), ParameterGrp::HasGroup(), Gui::Application::Instance, Gui::CommandBase::setAccel(), ParameterGrp::SetASCII(), and draftutils.translate::translate().
Referenced by on_buttonAssign_clicked(), and on_buttonClear_clicked().
showEvent()
void DlgCustomKeyboardImp::showEvent (QShowEvent * e) protected
References on_categoryBox_activated().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgKeyboardImp.h
Sources/FreeCAD/src/Gui/DlgKeyboardImp.cpp