FreeCAD: Gui::Dialog::Ui_DlgSettingsPythonConsole Class Reference
Gui::Dialog::Ui_DlgSettingsPythonConsole Class Reference
#include <ui_DlgSettingsPythonConsole.h>
Public Member Functions
void retranslateUi (QWidget *Gui__Dialog__DlgSettingsPythonConsole)
void setupUi (QWidget *Gui__Dialog__DlgSettingsPythonConsole)
Public Attributes
QGridLayout * gridLayout
QGridLayout * gridLayout_2
QGroupBox * GroupBox11
Gui::PrefCheckBox * PythonBlockCursor
Gui::PrefCheckBox * PythonSaveHistory
Gui::PrefCheckBox * PythonWordWrap
QSpacerItem * verticalSpacer
Member Function Documentation
retranslateUi()
void Gui::Dialog::Ui_DlgSettingsPythonConsole::retranslateUi (QWidget * Gui__Dialog__DlgSettingsPythonConsole)
References GroupBox11, PythonBlockCursor, PythonSaveHistory, PythonWordWrap, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Gui::Dialog::Ui_DlgSettingsPythonConsole::setupUi (QWidget * Gui__Dialog__DlgSettingsPythonConsole)
References gridLayout, gridLayout_2, GroupBox11, PythonBlockCursor, PythonSaveHistory, PythonWordWrap, retranslateUi(), and verticalSpacer.
Member Data Documentation
gridLayout
QGridLayout* Gui::Dialog::Ui_DlgSettingsPythonConsole::gridLayout
Referenced by setupUi().
gridLayout_2
QGridLayout* Gui::Dialog::Ui_DlgSettingsPythonConsole::gridLayout_2
Referenced by setupUi().
GroupBox11
QGroupBox* Gui::Dialog::Ui_DlgSettingsPythonConsole::GroupBox11
Referenced by retranslateUi(), and setupUi().
PythonBlockCursor
Gui::PrefCheckBox* Gui::Dialog::Ui_DlgSettingsPythonConsole::PythonBlockCursor
Referenced by retranslateUi(), and setupUi().
PythonSaveHistory
Gui::PrefCheckBox* Gui::Dialog::Ui_DlgSettingsPythonConsole::PythonSaveHistory
Referenced by retranslateUi(), and setupUi().
PythonWordWrap
Gui::PrefCheckBox* Gui::Dialog::Ui_DlgSettingsPythonConsole::PythonWordWrap
Referenced by retranslateUi(), and setupUi().
verticalSpacer
QSpacerItem* Gui::Dialog::Ui_DlgSettingsPythonConsole::verticalSpacer
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/ui_DlgSettingsPythonConsole.h