FreeCAD: PartGui::TaskFaceColors Class Reference
PartGui::TaskFaceColors Class Reference
#include <TaskFaceColors.h>
Public Member Functions
bool accept ()
is called by the framework if the dialog is accepted (Ok)
void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
QDialogButtonBox::StandardButtons getStandardButtons () const
tells the framework which buttons are wished for the dialog
void open ()
is called by the framework when the dialog is opened
bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskFaceColors (ViewProviderPartExt *vp)
~TaskFaceColors ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Constructor & Destructor Documentation
TaskFaceColors()
TaskFaceColors::TaskFaceColors (ViewProviderPartExt * vp)
References Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
~TaskFaceColors()
TaskFaceColors::~TaskFaceColors ()
Member Function Documentation
accept()
bool TaskFaceColors::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References PartGui::FaceColors::accept().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
clicked()
void TaskFaceColors::clicked (int) virtual
is called by the framework if a button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
getStandardButtons()
QDialogButtonBox::StandardButtons PartGui::TaskFaceColors::getStandardButtons (void) const virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
open()
void TaskFaceColors::open () virtual
is called by the framework when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
References PartGui::FaceColors::open().
reject()
bool TaskFaceColors::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References PartGui::FaceColors::reject().
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/Gui/TaskFaceColors.h
Sources/FreeCAD/src/Mod/Part/Gui/TaskFaceColors.cpp