FreeCAD: Segment_Header Struct Reference
Segment_Header Struct Reference
#include <Segment_Header.h>
Public Member Functions
void read (Context &cont)
Segment_Header ()
Segment_Header (Context &cont)
Public Attributes
GUID Segment_ID
I32 Segment_Length
I32 Segment_Type
Constructor & Destructor Documentation
Segment_Header() [1/2]
Segment_Header::Segment_Header ()
Segment_Header() [2/2]
Segment_Header::Segment_Header (Context & cont)
References read().
Member Function Documentation
read()
void Segment_Header::read (Context & cont)
References GUID::read(), I32::read(), Segment_ID, Segment_Length, and Segment_Type.
Referenced by gzip_utf8.GzipFile::readline(), gzip_utf8.GzipFile::seek(), and Segment_Header().
Member Data Documentation
Segment_ID
GUID Segment_Header::Segment_ID
Referenced by read().
Segment_Length
I32 Segment_Header::Segment_Length
Referenced by read().
Segment_Type
I32 Segment_Header::Segment_Type
Referenced by read().
The documentation for this struct was generated from the following file:
FreeCAD/src/Mod/JtReader/App/JrJt/Segment_Header.h