FreeCAD: TechDraw::DrawPage Class Reference
TechDraw::DrawPage Class Reference
#include <DrawPage.h>
Public Member Functions
DrawPage (void)
virtual ~DrawPage ()
Public Member Functions inherited from App::DocumentObject
virtual App::Property * addDynamicProperty (const char *type, const char *name=0, const char *group=0, const char *doc=0, short attr=0, bool ro=false, bool hidden=false) override
virtual bool adjustRelativeLinks (const std::set< App::DocumentObject * > &inList, std::set< App::DocumentObject * > *visited=0)
Called to adjust link properties to avoid cyclic links.
virtual bool allowDuplicateLabel () const
virtual bool canLinkProperties () const
virtual int canLoadPartial () const
allow partial loading of dependent objects
void clearOutListCache () const
clear internal out list cache
virtual const char * detachFromDocument () override
DocumentObject (void)
Constructor.
void enforceRecompute ()
Enforce this document object to be recomputed.
App::Document * getDocument (void) const
gets the document in which this Object is handled
std::string getExportName (bool forced=false) const
returns the name that is safe to be exported to other document
virtual const PropertyExpressionEngine::ExpressionInfo getExpression (const ObjectIdentifier &path) const
virtual std::string getFullName () const override
Return the object full name of the form DocName::ObjName.
DocumentObjectGroup * getGroup () const
get group if object is part of a group, otherwise 0 is returned
long getID () const
Return the object ID that is unique within its owner document.
const std::vector< App::DocumentObject * > & getInList (void) const
std::set< App::DocumentObject * > getInListEx (bool recursive) const
Return a set of all objects linking to this object, including possible external parent objects.
void getInListEx (std::set< App::DocumentObject * > &inSet, bool recursive, std::vector< App::DocumentObject * > *inList=0) const
Get a set of all objects linking to this object, including possible external parent objects.
std::vector< App::DocumentObject * > getInListRecursive (void) const
get all objects link directly or indirectly to this object
virtual DocumentObject * getLinkedObject (bool recurse=true, Base::Matrix4D *mat=0, bool transform=false, int depth=0) const
Return the linked object with optional transformation.
const char * getNameInDocument (void) const
returns the name which is set in the document for this object (not the name property!)
const std::string & getOldLabel () const
const std::vector< App::DocumentObject * > & getOutList () const
returns a list of objects this object is pointing to by Links
std::vector< App::DocumentObject * > getOutList (int option) const
void getOutList (int option, std::vector< App::DocumentObject * > &res) const
std::vector< App::DocumentObject * > getOutListOfProperty (App::Property *) const
returns a list of objects linked by the property
std::vector< App::DocumentObject * > getOutListRecursive (void) const
returns a list of objects this object is pointing to by Links and all further descended
std::vector< std::pair< App::DocumentObject *, std::string > > getParents (int depth=0) const
Obtain top parents and subnames of this object using its InList.
std::vector< std::list< App::DocumentObject * > > getPathsByOutList (App::DocumentObject *to) const
get all possible paths from this to another object following the OutList
unsigned long getStatus () const
return the status bits
const char * getStatusString (void) const
get the status Message
virtual DocumentObject * getSubObject (const char *subname, PyObject **pyObj=0, Base::Matrix4D *mat=0, bool transform=true, int depth=0) const
Get the sub element/object by name.
std::vector< DocumentObject * > getSubObjectList (const char *subname) const
Return a list of objects referenced by a given subname including this object.
virtual std::vector< std::string > getSubObjects (int reason=0) const
Return name reference of all sub-objects.
virtual const char * getViewProviderNameOverride () const
This function is introduced to allow Python feature override its view provider.
const char * getViewProviderNameStored () const
virtual bool hasChildElement () const
return true to activate tree view group object handling and element visibility
virtual bool isAttachedToDocument () const override
virtual int isElementVisible (const char *element) const
Get sub-element visibility.
bool isError (void) const
set this feature to error
int isExporting () const
bool isInInList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the InList
bool isInInListRecursive (DocumentObject *objToTest) const
test if this object is in the InList and recursive further down
bool isInOutList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the OutList
bool isInOutListRecursive (DocumentObject *objToTest) const
test if the given object is in the OutList and recursive further down
bool isRecomputing () const
returns true if this objects is currently recomputing
bool isRemoving () const
returns true if this objects is currently removed from the document
bool isRestoring () const
returns true if this objects is currently restoring from file
bool isTouched (void) const
test if this document object is touched
bool isValid (void) const
bool mustRecompute (void) const
Test if this document object must be recomputed.
virtual void onBeforeChangeLabel (std::string &newLabel)
virtual void onLostLinkToObject (DocumentObject *)
Called in case of losing a link Get called by the document when a object got deleted a link property of this object ist pointing to.
virtual void onUpdateElementReference (const Property *)
void purgeError (void)
remove the error from the object
void purgeTouched (void)
reset this document object touched
bool recomputeFeature (bool recursive=false)
Recompute only this feature.
virtual bool redirectSubName (std::ostringstream &ss, DocumentObject *topParent, DocumentObject *child) const
Allow object to redirect a subname path.
virtual bool removeDynamicProperty (const char *prop) override
virtual void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths)
App::DocumentObject * resolve (const char *subname, App::DocumentObject **parent=0, std::string *childName=0, const char **subElement=0, PyObject **pyObj=0, Base::Matrix4D *mat=0, bool transform=true, int depth=0) const
Resolve the last document object referenced in the subname.
App::DocumentObject * resolveRelativeLink (std::string &subname, App::DocumentObject *&link, std::string &linkSub) const
Resolve a link reference that is relative to this object reference.
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
virtual int setElementVisible (const char *element, bool visible)
Child element handling.
virtual void setExpression (const ObjectIdentifier &path, boost::shared_ptr< App::Expression > expr)
void setStatus (ObjectStatus pos, bool on)
bool testIfLinkDAGCompatible (App::PropertyLinkSub &linkTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSubList &linksTo) const
bool testIfLinkDAGCompatible (const std::vector< DocumentObject * > &linksTo) const
bool testIfLinkDAGCompatible (DocumentObject *linkTo) const
testIfLinkIsDAG tests a link that is about to be created for circular references.
bool testStatus (ObjectStatus pos) const
void touch (bool noRecompute=false)
Set the property touched -> changed, cause recomputation in Update()
virtual ~DocumentObject ()
Public Member Functions inherited from App::TransactionalObject
TransactionalObject (void)
Constructor.
virtual ~TransactionalObject ()
Public Member Functions inherited from App::ExtensionContainer
ExtensionIterator extensionBegin ()
ExtensionContainer ()
ExtensionIterator extensionEnd ()
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
void registerExtension (Base::Type extension, App::Extension *ext)
virtual ~ExtensionContainer ()
virtual Property * getPropertyByName (const char *name) const override
find a property by its name
virtual const char * getPropertyName (const Property *prop) const override
get the name of a property
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
virtual void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
virtual short getPropertyType (const Property *prop) const override
get the Type of a Property
virtual short getPropertyType (const char *name) const override
get the Type of a named Property
virtual const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
virtual void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
Public Member Functions inherited from App::PropertyContainer
virtual App::Property * getDynamicPropertyByName (const char *name) const
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
const char * getPropertyPrefix () const
bool isHidden (const char *name) const
check if the named property is hidden
bool isHidden (const Property *prop) const
check if the property is hidden
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isReadOnly (const Property *prop) const
check if the property is read-only
PropertyContainer ()
A constructor.
void setPropertyPrefix (const char *prefix)
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
virtual ~PropertyContainer ()
A destructor.
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Attributes
App::PropertyBool KeepUpdated
App::PropertyInteger NextBalloonIndex
App::PropertyEnumeration ProjectionType
App::PropertyFloatConstraint Scale
App::PropertyLink Template
App::PropertyLinkList Views
Public Attributes inherited from App::DocumentObject
PropertyExpressionEngine ExpressionEngine
PropertyString Label
PropertyString Label2
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChange
signal before changing a property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChanged
signal on changed property of this object
PropertyBool Visibility
Allow control visibility status in App name space.
methods override Feature
boost::signals2::signal< void(const DrawPage *)> signalGuiPaint
bool balloonPlacing
DrawViewPart * balloonParent
bool m_forceRedraw
virtual App::DocumentObjectExecReturn * execute (void) override
recalculate the Feature
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, App::Property *prop) override
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
int addView (App::DocumentObject *docObj)
int removeView (App::DocumentObject *docObj)
short mustExecute () const override
mustExecute We call this method to check if the object was modified to be invoked.
virtual const char * getViewProviderName (void) const override
returns the type name of the ViewProvider
PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
bool hasValidTemplate () const
Check whether we've got a valid template.
double getPageWidth () const
Returns width of the template.
double getPageHeight () const
Returns height of the template.
const char * getPageOrientation () const
bool isUnsetting (void)
void requestPaint (void)
std::vector< App::DocumentObject * > getAllViews (void)
int getNextBalloonIndex (void)
void updateAllViews (void)
void forceRedraw (bool b)
bool forceRedraw (void)
void redrawCommand ()
static bool GlobalUpdateDrawings (void)
static bool AllowPageOverride (void)
void onBeforeChange (const App::Property *prop) override
get called before the value is changed
void onChanged (const App::Property *prop) override
get called by the container when a property was changed
virtual void onDocumentRestored () override
get called after a document has been fully restored
virtual void unsetupObject () override
get called when object is going to be removed from the document
Additional Inherited Members
Public Types inherited from App::DocumentObject
enum GSReason { GS_DEFAULT, GS_SELECT }
reason of calling getSubObjects()
enum OutListOption { OutListNoExpression = 1, OutListNoHidden = 2, OutListNoXLinked = 4 }
DAG handling This part of the interface deals with viewing the document as a DAG (directed acyclic graph).
Public Types inherited from App::ExtensionContainer
typedef std::map< Base::Type, App::Extension * >::iterator ExtensionIterator
Static Public Member Functions inherited from App::DocumentObject
static const char * hasHiddenMarker (const char *subname)
Check if the subname reference ends with hidden marker.
static const std::string & hiddenMarker ()
Special marker to mark the object as hidden.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Public Attributes inherited from App::DocumentObject
static DocumentObjectExecReturn * StdReturn
Protected Member Functions inherited from App::DocumentObject
App::DocumentObjectExecReturn * executeExtensions ()
Executes the extensions of a document object.
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus) override
get called when a property status has changed
virtual void onSettingDocument ()
get called after setting the document
virtual void onUndoRedoFinished ()
get called after an undo/redo transaction is finished
virtual App::DocumentObjectExecReturn * recompute (void)
recompute only this object
void resetError (void)
void setDocument (App::Document *doc)
void setError (void)
virtual void setupObject ()
get called after a brand new object was created
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData (void) const
virtual void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container.
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::DocumentObject
std::string oldLabel
Old label; used for renaming expressions.
const std::string * pcNameInDocument
Py::Object PythonObject
python object of this class and all descendent
std::bitset< 32 > StatusBits
Status bits of the document object The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Constructor & Destructor Documentation
DrawPage()
DrawPage::DrawPage (void)
References App::GetApplication(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), TechDraw::Preferences::keepPagesUpToDate(), TechDraw::Preferences::projectionAngle(), App::Prop_None, and App::Prop_Output.
~DrawPage()
DrawPage::~DrawPage () virtual
Member Function Documentation
addView()
int DrawPage::addView (App::DocumentObject * docObj)
References Base::Console(), Base::Persistence::getClassTypeId(), Base::BaseClass::isDerivedFrom(), and Base::ConsoleSingleton::Warning().
Referenced by TechDraw::DrawPagePy::addView().
AllowPageOverride()
bool DrawPage::AllowPageOverride (void) static
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by TechDraw::DrawView::keepUpdated().
execute()
App::DocumentObjectExecReturn * DrawPage::execute (void) override virtual
recalculate the Feature
Reimplemented from App::DocumentObject.
References App::DocumentObject::StdReturn.
Referenced by ArchSite.Compass::buildCoordinates(), ArchSchedule.CommandArchSchedule::IsActive(), and FeaturePython.DistanceBolt::onChanged().
forceRedraw() [1/2]
void TechDraw::DrawPage::forceRedraw (bool b)
Referenced by TechDraw::DrawView::keepUpdated().
forceRedraw() [2/2]
bool TechDraw::DrawPage::forceRedraw (void)
getAllViews()
std::vector< App::DocumentObject * > DrawPage::getAllViews (void)
References Base::Persistence::getClassTypeId(), App::PropertyListsT< T, ListT, ParentT >::getValues(), and TechDraw::DrawViewCollection::Views.
Referenced by TechDrawGui::MDIViewPage::fixOrphans(), and TechDraw::DrawPagePy::getAllViews().
getNextBalloonIndex()
int DrawPage::getNextBalloonIndex (void)
getPageHeight()
double DrawPage::getPageHeight () const
Returns height of the template.
Exceptions
Base::Exception if no template is loaded.
References Base::Persistence::getClassTypeId(), and TechDraw::DrawTemplate::getHeight().
Referenced by TechDrawGui::TaskRichAnno::calcTextStartPos(), TechDraw::DrawProjGroup::calculateAutomaticScale(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::QGVPage::drawBackground(), and TechDrawGui::QGVPage::saveSvg().
getPageOrientation()
const char * DrawPage::getPageOrientation () const
References Base::Persistence::getClassTypeId(), App::PropertyEnumeration::getValueAsString(), and TechDraw::DrawTemplate::Orientation.
getPageWidth()
double DrawPage::getPageWidth () const
Returns width of the template.
Exceptions
Base::Exception if no template is loaded.
References Base::Persistence::getClassTypeId(), and TechDraw::DrawTemplate::getWidth().
Referenced by TechDrawGui::TaskRichAnno::calcTextStartPos(), TechDraw::DrawProjGroup::calculateAutomaticScale(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::QGVPage::drawBackground(), and TechDrawGui::QGVPage::saveSvg().
getPyObject()
PyObject * DrawPage::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from App::DocumentObject.
getViewProviderName()
virtual const char* TechDraw::DrawPage::getViewProviderName (void) const override virtual
returns the type name of the ViewProvider
Reimplemented from App::DocumentObject.
GlobalUpdateDrawings()
bool DrawPage::GlobalUpdateDrawings (void) static
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by TechDraw::DrawView::keepUpdated().
handleChangedPropertyType()
void DrawPage::handleChangedPropertyType (Base::XMLReader & reader, const char * TypeName, App::Property * prop) override virtual
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
This method is typically called if the property on file has changed its type in more recent versions.
The default implementation does nothing.
Parameters
reader The XML stream to read from.
TypeName Name of property type on file.
prop Pointer to property to restore. Its type differs from TypeName.
Reimplemented from App::PropertyContainer.
References Base::Console(), Base::Type::getName(), Base::Persistence::getTypeId(), App::PropertyFloat::getValue(), Base::ConsoleSingleton::Log(), App::PropertyFloat::Restore(), and App::Property::setContainer().
hasValidTemplate()
bool DrawPage::hasValidTemplate () const
Check whether we've got a valid template.
Returns
boolean answer to the question: "Doest thou have a valid template?"
References Base::Persistence::getClassTypeId(), TechDraw::DrawTemplate::getHeight(), and TechDraw::DrawTemplate::getWidth().
Referenced by TechDrawGui::QGVPage::drawBackground().
isUnsetting()
bool TechDraw::DrawPage::isUnsetting (void)
mustExecute()
short DrawPage::mustExecute () const override virtual
mustExecute We call this method to check if the object was modified to be invoked.
If the object label or an argument is modified. If we must recompute the object - to call the method execute(). 0: no recomputation is needed 1: recomputation needed
Remarks
If an object is marked as 'touched' then this does not necessarily mean that it will be recomputed. It only means that all objects that link it (i.e. its InList) will be recomputed.
Reimplemented from App::DocumentObject.
References App::DocumentObject::mustExecute().
onBeforeChange()
void DrawPage::onBeforeChange (const App::Property * prop) override protected virtual
get called before the value is changed
Reimplemented from App::DocumentObject.
References App::DocumentObject::onBeforeChange().
onChanged()
void DrawPage::onChanged (const App::Property * prop) override protected virtual
get called by the container when a property was changed
Reimplemented from App::DocumentObject.
References Base::Console(), Base::ConsoleSingleton::Message(), and App::DocumentObject::onChanged().
Referenced by ArchSite.Compass::buildCoordinates(), and ArchAxis.CommandArchGrid::IsActive().
onDocumentRestored()
void DrawPage::onDocumentRestored () override protected virtual
get called after a document has been fully restored
Reimplemented from App::DocumentObject.
References App::DocumentObject::onDocumentRestored().
redrawCommand()
void DrawPage::redrawCommand ()
removeView()
int DrawPage::removeView (App::DocumentObject * docObj)
References Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), and Base::BaseClass::isDerivedFrom().
Referenced by TechDraw::DrawPagePy::removeView(), and TechDraw::DrawViewPart::unsetupObject().
requestPaint()
void DrawPage::requestPaint (void)
unsetupObject()
void DrawPage::unsetupObject () override protected virtual
get called when object is going to be removed from the document
Reimplemented from App::DocumentObject.
References Base::Console(), Base::Interpreter(), Base::ConsoleSingleton::Log(), Base::InterpreterSingleton::runStringArg(), and Base::ConsoleSingleton::Warning().
updateAllViews()
void DrawPage::updateAllViews (void)
References App::DocumentObject::recomputeFeature().
Member Data Documentation
balloonParent
DrawViewPart* TechDraw::DrawPage::balloonParent
Referenced by TechDrawGui::QGVPage::mouseReleaseEvent().
balloonPlacing
bool TechDraw::DrawPage::balloonPlacing
KeepUpdated
App::PropertyBool TechDraw::DrawPage::KeepUpdated
Referenced by TechDraw::DrawView::keepUpdated(), and TechDrawGui::MDIViewPage::toggleKeepUpdated().
m_forceRedraw
bool TechDraw::DrawPage::m_forceRedraw protected
NextBalloonIndex
App::PropertyInteger TechDraw::DrawPage::NextBalloonIndex
ProjectionType
App::PropertyEnumeration TechDraw::DrawPage::ProjectionType
Referenced by TechDraw::DrawProjGroup::arrangeViewPointers(), TechDraw::DrawProjGroup::getViewIndex(), and TechDraw::DrawProjGroup::usedProjectionType().
Scale
App::PropertyFloatConstraint TechDraw::DrawPage::Scale
Referenced by TechDraw::DrawView::checkScale(), TechDraw::DrawProjGroup::onChanged(), and TechDrawGui::TaskDetail::onScaleTypeEdit().
signalGuiPaint
boost::signals2::signal<void (const DrawPage*)> TechDraw::DrawPage::signalGuiPaint
Template
App::PropertyLink TechDraw::DrawPage::Template
Referenced by TechDrawGui::MDIViewPage::addChildrenToPage(), TechDrawGui::MDIViewPage::centerOnPage(), TechDraw::DrawTemplate::execute(), TechDrawGui::MDIViewPage::matchSceneRectToTemplate(), TechDrawGui::MDIViewPage::print(), and TechDrawGui::MDIViewPage::updateTemplate().
Views
App::PropertyLinkList TechDraw::DrawPage::Views
Referenced by TechDrawGui::MDIViewPage::addChildrenToPage(), and TechDrawGui::TaskLinkDim::loadAvailDims().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/App/DrawPage.h
Sources/FreeCAD/src/Mod/TechDraw/App/DrawPage.cpp