FreeCAD: PartDesignGui::Ui_TaskPipeScaling Class Reference
PartDesignGui::Ui_TaskPipeScaling Class Reference
#include <ui_TaskPipeScaling.h>
Public Member Functions
void retranslateUi (QWidget *PartDesignGui__TaskPipeScaling)
void setupUi (QWidget *PartDesignGui__TaskPipeScaling)
Public Attributes
QToolButton * buttonRefAdd
QToolButton * buttonRefRemove
QComboBox * comboBoxScaling
QWidget * constant
QHBoxLayout * horizontalLayout
QHBoxLayout * horizontalLayout_4
QSpacerItem * horizontalSpacer
QLabel * label_2
QListWidget * listWidgetReferences
QWidget * multisection
QStackedWidget * stackedWidget
QVBoxLayout * verticalLayout_2
QVBoxLayout * verticalLayout_3
Member Function Documentation
retranslateUi()
void PartDesignGui::Ui_TaskPipeScaling::retranslateUi (QWidget * PartDesignGui__TaskPipeScaling)
References buttonRefAdd, buttonRefRemove, comboBoxScaling, label_2, listWidgetReferences, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void PartDesignGui::Ui_TaskPipeScaling::setupUi (QWidget * PartDesignGui__TaskPipeScaling)
References buttonRefAdd, buttonRefRemove, comboBoxScaling, draftgeoutils.intersections::connect(), constant, horizontalLayout, horizontalLayout_4, horizontalSpacer, label_2, listWidgetReferences, multisection, retranslateUi(), stackedWidget, verticalLayout_2, and verticalLayout_3.
Member Data Documentation
buttonRefAdd
QToolButton* PartDesignGui::Ui_TaskPipeScaling::buttonRefAdd
Referenced by retranslateUi(), and setupUi().
buttonRefRemove
QToolButton* PartDesignGui::Ui_TaskPipeScaling::buttonRefRemove
Referenced by retranslateUi(), and setupUi().
comboBoxScaling
QComboBox* PartDesignGui::Ui_TaskPipeScaling::comboBoxScaling
Referenced by retranslateUi(), and setupUi().
constant
QWidget* PartDesignGui::Ui_TaskPipeScaling::constant
Referenced by setupUi().
horizontalLayout
QHBoxLayout* PartDesignGui::Ui_TaskPipeScaling::horizontalLayout
Referenced by setupUi().
horizontalLayout_4
QHBoxLayout* PartDesignGui::Ui_TaskPipeScaling::horizontalLayout_4
Referenced by setupUi().
horizontalSpacer
QSpacerItem* PartDesignGui::Ui_TaskPipeScaling::horizontalSpacer
Referenced by setupUi().
label_2
QLabel* PartDesignGui::Ui_TaskPipeScaling::label_2
Referenced by retranslateUi(), and setupUi().
listWidgetReferences
QListWidget* PartDesignGui::Ui_TaskPipeScaling::listWidgetReferences
Referenced by retranslateUi(), and setupUi().
multisection
QWidget* PartDesignGui::Ui_TaskPipeScaling::multisection
Referenced by setupUi().
stackedWidget
QStackedWidget* PartDesignGui::Ui_TaskPipeScaling::stackedWidget
Referenced by setupUi().
verticalLayout_2
QVBoxLayout* PartDesignGui::Ui_TaskPipeScaling::verticalLayout_2
Referenced by setupUi().
verticalLayout_3
QVBoxLayout* PartDesignGui::Ui_TaskPipeScaling::verticalLayout_3
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/PartDesign/Gui/ui_TaskPipeScaling.h