FreeCAD: Base::Line2d Class Reference
Base::Line2d Class Reference
Line2d.
#include <Tools2D.h>
Public Member Functions
BoundBox2d CalcBoundBox () const
LINE2D.
bool Contains (const Vector2d &rclV) const
Vector2d FromPos (double fDistance) const
bool Intersect (const Line2d &rclLine, Vector2d &rclV) const
bool Intersect (const Vector2d &rclV, double eps) const
bool IntersectAndContain (const Line2d &rclLine, Vector2d &rclV) const
double Length () const
Line2d ()
Line2d (const Line2d &rclLine)
Line2d (const Vector2d &rclV1, const Vector2d &rclV2)
Line2d & operator= (const Line2d &rclLine)
bool operator== (const Line2d &rclLine) const
Public Attributes
Vector2d clV1
Vector2d clV2
Detailed Description
Line2d.
2D line class.
Constructor & Destructor Documentation
Line2d() [1/3]
Base::Line2d::Line2d ()
Line2d() [2/3]
Base::Line2d::Line2d (const Line2d & rclLine)
Line2d() [3/3]
Base::Line2d::Line2d (const Vector2d & rclV1, const Vector2d & rclV2)
Member Function Documentation
CalcBoundBox()
BoundBox2d Line2d::CalcBoundBox () const
LINE2D.
References clV1, clV2, Base::BoundBox2d::MaxX, Base::BoundBox2d::MaxY, Base::BoundBox2d::MinX, Base::BoundBox2d::MinY, Base::Vector2d::x, and Base::Vector2d::y.
Referenced by Contains().
Contains()
bool Base::Line2d::Contains (const Vector2d & rclV) const
References CalcBoundBox(), and Base::BoundBox2d::Contains().
Referenced by IntersectAndContain().
FromPos()
Vector2d Line2d::FromPos (double fDistance) const
References clV1, clV2, Base::Vector2d::Normalize(), Base::Vector2d::x, and Base::Vector2d::y.
Referenced by Base::Polygon2d::Intersect().
Intersect() [1/2]
bool Line2d::Intersect (const Line2d & rclLine, Vector2d & rclV) const
References clV1, clV2, Base::Vector2d::x, and Base::Vector2d::y.
Referenced by CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainAngle::applyConstraint(), and IntersectAndContain().
Intersect() [2/2]
bool Line2d::Intersect (const Vector2d & rclV, double eps) const
References clV1, clV2, Base::Vector2d::x, and Base::Vector2d::y.
IntersectAndContain()
bool Line2d::IntersectAndContain (const Line2d & rclLine, Vector2d & rclV) const
References Contains(), and Intersect().
Referenced by Base::BoundBox2d::Intersect(), and Base::Polygon2d::Intersect().
Length()
double Base::Line2d::Length (void) const
References clV1, and clV2.
Referenced by ArchStructure.CommandStructuralSystem::Activated(), ArchPanel.CommandPanel::getPoint(), ArchPanel.CommandPanel::setLength(), and ArchPanel.CommandPanel::update().
operator=()
Line2d & Base::Line2d::operator= (const Line2d & rclLine)
References clV1, and clV2.
operator==()
bool Base::Line2d::operator== (const Line2d & rclLine) const
References clV1, and clV2.
Member Data Documentation
clV1
Vector2d Base::Line2d::clV1
Referenced by CalcBoundBox(), FromPos(), Base::BoundBox2d::Intersect(), Intersect(), Length(), operator=(), and operator==().
clV2
Vector2d Base::Line2d::clV2
Referenced by CalcBoundBox(), FromPos(), Base::BoundBox2d::Intersect(), Intersect(), Length(), operator=(), and operator==().
The documentation for this class was generated from the following files:
FreeCAD/src/Base/Tools2D.h
FreeCAD/src/Base/Tools2D.cpp