FreeCAD: MeshCore::MeshFixTopology Class Reference
MeshCore::MeshFixTopology Class Reference
The MeshFixTopology class tries to fix a few cases of non-manifolds.
#include <Evaluation.h>
Public Member Functions
bool Fixup ()
This function attempts to change the mesh kernel to be valid according to the checked criterion: True is returned if the errors could be fixed, false otherwise.
const std::vector< FacetIndex > & GetDeletedFaces () const
MeshFixTopology (MeshKernel &rclB, const std::list< std::vector< FacetIndex > > &mf)
virtual ~MeshFixTopology ()
Public Member Functions inherited from MeshCore::MeshValidation
virtual bool Fixup ()=0
This function attempts to change the mesh kernel to be valid according to the checked criterion: True is returned if the errors could be fixed, false otherwise.
MeshValidation (MeshKernel &rclB)
virtual ~MeshValidation ()
Protected Attributes
std::vector< FacetIndex > deletedFaces
const std::list< std::vector< FacetIndex > > & nonManifoldList
Detailed Description
The MeshFixTopology class tries to fix a few cases of non-manifolds.
See also
MeshEvalTopology
Constructor & Destructor Documentation
MeshFixTopology()
MeshCore::MeshFixTopology::MeshFixTopology (MeshKernel & rclB, const std::list< std::vector< FacetIndex > > & mf)
~MeshFixTopology()
virtual MeshCore::MeshFixTopology::~MeshFixTopology () virtual
Member Function Documentation
Fixup()
bool MeshFixTopology::Fixup () virtual
This function attempts to change the mesh kernel to be valid according to the checked criterion: True is returned if the errors could be fixed, false otherwise.
Implements MeshCore::MeshValidation.
References deletedFaces, MeshCore::MeshEvalTopology::Evaluate(), MeshCore::MeshEvalTopology::GetFacetManifolds(), and nonManifoldList.
Referenced by Mesh::MeshObject::removeNonManifolds().
GetDeletedFaces()
const std::vector< FacetIndex > & MeshCore::MeshFixTopology::GetDeletedFaces () const
Referenced by Mesh::MeshObject::removeNonManifolds().
Member Data Documentation
deletedFaces
std::vector<FacetIndex> MeshCore::MeshFixTopology::deletedFaces protected
Referenced by Fixup().
nonManifoldList
const std::list<std::vector<FacetIndex> >& MeshCore::MeshFixTopology::nonManifoldList protected
Referenced by Fixup().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/Core/Evaluation.h
FreeCAD/src/Mod/Mesh/App/Core/Evaluation.cpp