FreeCAD: Gui::StdWorkbench Class Reference
Gui::StdWorkbench Class Reference
The StdWorkbench class defines the standard menus, toolbars, commandbars etc.
#include <Workbench.h>
Public Member Functions
virtual void createMainWindowPopupMenu (MenuItem *) const
Sets up the contextmenu for the main window for this workbench.
virtual void setupContextMenu (const char *recipient, MenuItem *) const
Defines the standard context menu.
StdWorkbench ()
virtual ~StdWorkbench ()
Public Member Functions inherited from Gui::Workbench
bool activate ()
Activates the workbench and adds/removes GUI elements.
virtual void activated ()
Run some actions when the workbench gets activated.
void addTaskWatcher (const std::vector< Gui::TaskView::TaskWatcher * > &Watcher)
helper to add TaskWatcher to the TaskView
virtual void deactivated ()
Run some actions when the workbench gets deactivated.
PyObject * getPyObject ()
The default implementation returns an instance of WorkbenchPy.
std::list< std::pair< std::string, std::list< std::string > > > getToolbarItems () const
Shows a list of all toolbars and their commands.
std::list< std::string > listCommandbars () const
std::list< std::string > listMenus () const
std::list< std::string > listToolbars () const
std::string name () const
Returns the name of the workbench object.
void removeTaskWatcher (void)
remove the added TaskWatcher
void retranslate () const
Translates the window titles of all menus, toolbars and dock windows.
void setName (const std::string &)
Set the name to the workbench object.
Workbench ()
Constructs a workbench object.
virtual ~Workbench ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual Type getTypeId (void) const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Member Functions
virtual ToolBarItem * setupCommandBars () const
Defines the standard command bars.
virtual DockWindowItems * setupDockWindows () const
Returns a DockWindowItems structure of dock windows this workbench.
virtual MenuItem * setupMenuBar () const
Defines the standard menus.
virtual ToolBarItem * setupToolBars () const
Defines the standard toolbars.
Friends
class PythonWorkbench
Additional Inherited Members
Static Public Member Functions inherited from Gui::Workbench
static void createLinkMenu (MenuItem *)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The StdWorkbench class defines the standard menus, toolbars, commandbars etc.
To define own workbenches you should inherit from StdWorkbench instead of Workbench to have defined the standard GUI elements.
Author
Werner Mayer
Constructor & Destructor Documentation
StdWorkbench()
StdWorkbench::StdWorkbench ()
~StdWorkbench()
StdWorkbench::~StdWorkbench () virtual
Member Function Documentation
createMainWindowPopupMenu()
void StdWorkbench::createMainWindowPopupMenu (MenuItem *) const virtual
Sets up the contextmenu for the main window for this workbench.
The default implementation does nothing.
Reimplemented from Gui::Workbench.
Referenced by Gui::PythonWorkbench::createMainWindowPopupMenu().
setupCommandBars()
ToolBarItem * StdWorkbench::setupCommandBars () const protected virtual
Defines the standard command bars.
Implements Gui::Workbench.
Reimplemented in WebGui::Workbench, TechDrawGui::Workbench, StartGui::Workbench, SpreadsheetGui::Workbench, SketcherGui::Workbench, SandboxGui::Workbench, ReverseEngineeringGui::Workbench, PointsGui::Workbench, PartDesignGui::Workbench, PartGui::Workbench, MeshPartGui::Workbench, MeshGui::Workbench, ImportGui::Workbench, ImageGui::Workbench, DrawingGui::Workbench, Gui::TestWorkbench, and Gui::NoneWorkbench.
References Gui::ToolBarItem::setCommand().
setupContextMenu()
void StdWorkbench::setupContextMenu (const char * recipient, MenuItem * item) const virtual
Defines the standard context menu.
Reimplemented from Gui::Workbench.
Reimplemented in Gui::NoneWorkbench, WebGui::Workbench, StartGui::Workbench, PartDesignGui::Workbench, MeshGui::Workbench, and FemGui::Workbench.
References Gui::Workbench::createLinkMenu(), Base::Persistence::getClassTypeId(), Gui::Selection(), and Gui::MenuItem::setCommand().
Referenced by PartDesignGui::Workbench::setupContextMenu(), and Gui::PythonWorkbench::setupContextMenu().
setupDockWindows()
DockWindowItems * StdWorkbench::setupDockWindows () const protected virtual
Returns a DockWindowItems structure of dock windows this workbench.
Implements Gui::Workbench.
Reimplemented in WebGui::Workbench, StartGui::Workbench, SandboxGui::Workbench, and Gui::NoneWorkbench.
References Gui::DockWindowItems::addDockWidget(), App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by Gui::PythonWorkbench::setupDockWindows(), SandboxGui::Workbench::setupDockWindows(), StartGui::Workbench::setupDockWindows(), and WebGui::Workbench::setupDockWindows().
setupMenuBar()
MenuItem * StdWorkbench::setupMenuBar () const protected virtual
Defines the standard menus.
Implements Gui::Workbench.
Reimplemented in WebGui::Workbench, TechDrawGui::Workbench, SurfaceGui::Workbench, StartGui::Workbench, SpreadsheetGui::Workbench, SketcherGui::Workbench, SandboxGui::Workbench, RobotGui::Workbench, ReverseEngineeringGui::Workbench, RaytracingGui::Workbench, PointsGui::Workbench, PartDesignGui::Workbench, PartGui::Workbench, MeshGui::Workbench, InspectionGui::Workbench, FemGui::Workbench, DrawingGui::Workbench, Gui::TestWorkbench, and Gui::NoneWorkbench.
References Gui::MenuItem::setCommand().
Referenced by Gui::PythonWorkbench::PythonWorkbench(), Gui::TestWorkbench::setupMenuBar(), StartGui::Workbench::setupMenuBar(), and WebGui::Workbench::setupMenuBar().
setupToolBars()
ToolBarItem * StdWorkbench::setupToolBars () const protected virtual
Defines the standard toolbars.
Implements Gui::Workbench.
Reimplemented in WebGui::Workbench, TechDrawGui::Workbench, SurfaceGui::Workbench, StartGui::Workbench, SpreadsheetGui::Workbench, SketcherGui::Workbench, SandboxGui::Workbench, RobotGui::Workbench, ReverseEngineeringGui::Workbench, RaytracingGui::Workbench, PointsGui::Workbench, PartDesignGui::Workbench, PartGui::Workbench, MeshPartGui::Workbench, MeshGui::Workbench, InspectionGui::Workbench, ImportGui::Workbench, ImageGui::Workbench, FemGui::Workbench, DrawingGui::Workbench, Gui::TestWorkbench, and Gui::NoneWorkbench.
References Gui::ToolBarItem::setCommand().
Referenced by Gui::PythonWorkbench::PythonWorkbench().
Friends And Related Function Documentation
PythonWorkbench
friend class PythonWorkbench friend
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Workbench.h
Sources/FreeCAD/src/Gui/Workbench.cpp