FreeCAD: PathScripts.PathDressupDogbone Namespace Reference
PathScripts.PathDressupDogbone Namespace Reference
Classes
class Bone
class Chord
class CommandDressupDogbone
class Incision
class ObjectDressup
class SelObserver
class Side
class Smooth
class Style
class TaskPanel
class ViewProviderDressup
Functions
def addAngle (a1, a2)
def anglesAreParallel (a1, a2)
def Create (base, name='DogboneDressup')
def debugCircle (vector, r, label, color=None)
def debugMarker (vector, label, color=None, radius=0.5)
def edgesForCommands (cmds, startPt)
def getAngle (v)
def pointFromCommand (cmd, pt, X='X', Y='Y', Z='Z')
def translate (context, text, disambig=None)
Variables
DraftGeomUtils = LazyLoader('DraftGeomUtils', globals(), 'DraftGeomUtils')
LOG_MODULE = PathLog.thisModule()
list movearc = movecw + moveccw
list moveccw = ['G3', 'G03']
list movecommands = ['G0', 'G00', 'G1', 'G01', 'G2', 'G02', 'G3', 'G03']
list movecw = ['G2', 'G02']
list movestraight = ['G1', 'G01']
Part = LazyLoader('Part', globals(), 'Part')
Function Documentation
addAngle()
def PathScripts.PathDressupDogbone.addAngle (a1, a2)
Referenced by PathScripts.PathDressupDogbone.Bone.adaptiveLength(), PathScripts.PathDressupDogbone.Bone.angle(), and PathScripts.PathDressupDogbone.anglesAreParallel().
anglesAreParallel()
def PathScripts.PathDressupDogbone.anglesAreParallel (a1, a2)
References PathScripts.PathDressupDogbone.addAngle().
Create()
def PathScripts.PathDressupDogbone.Create (base, name = 'DogboneDressup')
Create(obj, name='DogboneDressup') ... dresses the given PathProfile/PathContour object with dogbones.
debugCircle()
def PathScripts.PathDressupDogbone.debugCircle (vector, r, label, color = None)
debugMarker()
def PathScripts.PathDressupDogbone.debugMarker (vector, label, color = None, radius = 0.5)
edgesForCommands()
def PathScripts.PathDressupDogbone.edgesForCommands (cmds, startPt)
References PathScripts.PathDressupDogbone.getAngle(), and PathScripts.PathDressupDogbone.pointFromCommand().
Referenced by PathScripts.PathDressupDogbone.ObjectDressup.removePathCrossing().
getAngle()
def PathScripts.PathDressupDogbone.getAngle (v)
Referenced by PathScripts.PathDressupDogbone.Bone.angle(), and PathScripts.PathDressupDogbone.edgesForCommands().
pointFromCommand()
def PathScripts.PathDressupDogbone.pointFromCommand (cmd, pt, X = 'X', Y = 'Y', Z = 'Z')
Referenced by PathScripts.PathDressupDogbone.edgesForCommands().
translate()
def PathScripts.PathDressupDogbone.translate (context, text, disambig = None)
Variable Documentation
DraftGeomUtils
PathScripts.PathDressupDogbone.DraftGeomUtils = LazyLoader('DraftGeomUtils', globals(), 'DraftGeomUtils')
LOG_MODULE
PathScripts.PathDressupDogbone.LOG_MODULE = PathLog.thisModule()
movearc
list PathScripts.PathDressupDogbone.movearc = movecw + moveccw
moveccw
list PathScripts.PathDressupDogbone.moveccw = ['G3', 'G03']
movecommands
list PathScripts.PathDressupDogbone.movecommands = ['G0', 'G00', 'G1', 'G01', 'G2', 'G02', 'G3', 'G03']
movecw
list PathScripts.PathDressupDogbone.movecw = ['G2', 'G02']
movestraight
list PathScripts.PathDressupDogbone.movestraight = ['G1', 'G01']
Part
PathScripts.PathDressupDogbone.Part = LazyLoader('Part', globals(), 'Part')