FreeCAD: TechDrawGui::Ui_TaskAlignViews Class Reference
TechDrawGui::Ui_TaskAlignViews Class Reference
#include <ui_TaskAlignViews.h>
Public Member Functions
void retranslateUi (QWidget *TechDrawGui__TaskAlignViews)
void setupUi (QWidget *TechDrawGui__TaskAlignViews)
Public Attributes
QPushButton * button_horizontally
QPushButton * button_vertically
QGroupBox * groupBox
QVBoxLayout * verticalLayout
QVBoxLayout * verticalLayout_2
Member Function Documentation
retranslateUi()
void TechDrawGui::Ui_TaskAlignViews::retranslateUi (QWidget * TechDrawGui__TaskAlignViews)
References button_horizontally, button_vertically, groupBox, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void TechDrawGui::Ui_TaskAlignViews::setupUi (QWidget * TechDrawGui__TaskAlignViews)
References button_horizontally, button_vertically, groupBox, retranslateUi(), verticalLayout, and verticalLayout_2.
Member Data Documentation
button_horizontally
QPushButton* TechDrawGui::Ui_TaskAlignViews::button_horizontally
Referenced by retranslateUi(), and setupUi().
button_vertically
QPushButton* TechDrawGui::Ui_TaskAlignViews::button_vertically
Referenced by retranslateUi(), and setupUi().
groupBox
QGroupBox* TechDrawGui::Ui_TaskAlignViews::groupBox
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* TechDrawGui::Ui_TaskAlignViews::verticalLayout
Referenced by setupUi().
verticalLayout_2
QVBoxLayout* TechDrawGui::Ui_TaskAlignViews::verticalLayout_2
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/TechDraw/Gui/ui_TaskAlignViews.h