FreeCAD: PathTests.TestPathPreferences.TestPathPreferences Class Reference
PathTests.TestPathPreferences.TestPathPreferences Class Reference
Public Member Functions
def test00 (self)
def test01 (self)
def test02 (self)
def test03 (self)
def test10 (self)
Public Member Functions inherited from PathTests.PathTestUtils.PathTestBase
def assertArc (self, edge, pt1, pt2, direction="CW")
def assertCircle (self, edge, pt, r)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertCommandEqual (self, c1, c2)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertEdgeShapesMatch (self, e1, e2)
def assertEqualLocale (self, s1, s2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertPlacement (self, p1, p2)
def assertPointsMatch (self, pts0, pts1)
def assertRoughly (self, f1, f2, error=0.00001)
Member Function Documentation
test00()
def PathTests.TestPathPreferences.TestPathPreferences.test00 (self)
There is at least one search path.
Referenced by PathTests.TestPathTool.TestPathTool.test01(), PathTests.TestPathToolController.TestPathToolController.test01(), PathTests.TestPathTooltable.TestPathTooltable.test01(), PathTests.TestPathTool.TestPathTool.test02(), and PathTests.TestPathTooltable.TestPathTooltable.test02().
test01()
def PathTests.TestPathPreferences.TestPathPreferences.test01 (self)
PathScripts is part of the posts search path.
test02()
def PathTests.TestPathPreferences.TestPathPreferences.test02 (self)
PathScripts/post is part of the posts search path.
test03()
def PathTests.TestPathPreferences.TestPathPreferences.test03 (self)
Available post processors include linuxcnc, grbl and opensbp.
test10()
def PathTests.TestPathPreferences.TestPathPreferences.test10 (self)
Default paths for tools are resolved correctly
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Path/PathTests/TestPathPreferences.py