FreeCAD: TechDrawGui::TaskBalloon Class Reference
TechDrawGui::TaskBalloon Class Reference
#include <TaskBalloon.h>
Public Member Functions
virtual bool accept ()
void recomputeFeature ()
virtual bool reject ()
TaskBalloon (QGIViewBalloon *parent, ViewProviderBalloon *balloonVP)
~TaskBalloon ()
Constructor & Destructor Documentation
TaskBalloon()
TaskBalloon::TaskBalloon (QGIViewBalloon * parent, ViewProviderBalloon * balloonVP)
References App::Color::asValue(), TechDraw::DrawViewBalloon::BubbleShape, TechDrawGui::ViewProviderBalloon::Color, draftgeoutils.intersections::connect(), TechDrawGui::QGIViewBalloon::dvBalloon, TechDraw::DrawViewBalloon::EndType, TechDraw::DrawViewBalloon::EndTypeScale, TechDrawGui::ViewProviderBalloon::Fontsize, App::PropertyEnumeration::getValue(), App::PropertyFloat::getValue(), App::PropertyString::getValue(), App::PropertyBool::getValue(), App::PropertyColor::getValue(), App::PropertyQuantity::getValue(), TechDraw::DrawViewBalloon::KinkLength, Base::Unit::Length, TechDrawGui::ViewProviderBalloon::LineVisible, TechDrawGui::ViewProviderBalloon::LineWidth, TechDrawGui::DrawGuiUtil::loadArrowBox(), TechDraw::DrawViewBalloon::ShapeScale, and TechDraw::DrawViewBalloon::Text.
~TaskBalloon()
TaskBalloon::~TaskBalloon ()
Member Function Documentation
accept()
bool TaskBalloon::accept (void) virtual
References Gui::ViewProviderDocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), and App::DocumentObject::purgeTouched().
Referenced by TechDrawGui::TaskDlgBalloon::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
recomputeFeature()
void TaskBalloon::recomputeFeature ()
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), and App::Document::recomputeFeature().
Referenced by reject().
reject()
bool TaskBalloon::reject (void) virtual
References Gui::ViewProviderDocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::DocumentObject::purgeTouched(), recomputeFeature(), and TechDrawGui::QGIViewBalloon::updateView().
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), TechDrawGui::TaskDlgBalloon::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/TaskBalloon.h
FreeCAD/src/Mod/TechDraw/Gui/TaskBalloon.cpp