FreeCAD: PathScripts.PathPost.CommandPathPost Class Reference
PathScripts.PathPost.CommandPathPost Class Reference
Public Member Functions
def Activated (self)
def exportObjectsWith (self, objs, job, needFilename=True)
def GetResources (self)
def IsActive (self)
def resolveFileName (self, job)
def resolvePostProcessor (self, job)
Public Attributes
subpart
Static Public Attributes
int subpart = 1
Member Function Documentation
Activated()
def PathScripts.PathPost.CommandPathPost.Activated (self)
References PathScripts.PathPost.CommandPathPost.exportObjectsWith().
exportObjectsWith()
def PathScripts.PathPost.CommandPathPost.exportObjectsWith (self, objs, job, needFilename = True)
References PathScripts.PathPost.CommandPathPost.resolveFileName(), and PathScripts.PathPost.CommandPathPost.resolvePostProcessor().
Referenced by PathScripts.PathPost.CommandPathPost.Activated().
GetResources()
def PathScripts.PathPost.CommandPathPost.GetResources (self)
IsActive()
def PathScripts.PathPost.CommandPathPost.IsActive (self)
resolveFileName()
def PathScripts.PathPost.CommandPathPost.resolveFileName (self, job)
References PathScripts.PathPost.CommandPathPost.subpart.
Referenced by PathScripts.PathPost.CommandPathPost.exportObjectsWith().
resolvePostProcessor()
def PathScripts.PathPost.CommandPathPost.resolvePostProcessor (self, job)
Referenced by PathScripts.PathPost.CommandPathPost.exportObjectsWith().
Member Data Documentation
subpart [1/2]
int PathScripts.PathPost.CommandPathPost.subpart = 1 static
Referenced by PathScripts.PathPost.CommandPathPost.resolveFileName().
subpart [2/2]
PathScripts.PathPost.CommandPathPost.subpart
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Path/PathScripts/PathPost.py