FreeCAD: LinkID_Gen Class Reference
LinkID_Gen Class Reference
Public Member Functions
long GetLinkID (const SMDS_MeshNode *n1, const SMDS_MeshNode *n2) const
bool GetNodes (const long theLinkID, const SMDS_MeshNode *&theNode1, const SMDS_MeshNode *&theNode2) const
LinkID_Gen (const SMESHDS_Mesh *theMesh)
Constructor & Destructor Documentation
LinkID_Gen()
LinkID_Gen::LinkID_Gen (const SMESHDS_Mesh * theMesh)
Member Function Documentation
GetLinkID()
long LinkID_Gen::GetLinkID (const SMDS_MeshNode * n1, const SMDS_MeshNode * n2) const
References SMDS_MeshElement::GetID().
Referenced by SMESH_MeshEditor::SewFreeBorder(), and SMESH_MeshEditor::SewSideElements().
GetNodes()
bool LinkID_Gen::GetNodes (const long theLinkID, const SMDS_MeshNode *& theNode1, const SMDS_MeshNode *& theNode2) const
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/SMESH_MeshEditor.cpp