FreeCAD: ImportGui::OCAFBrowser Class Reference
ImportGui::OCAFBrowser Class Reference
Public Member Functions
void load (QTreeWidget *)
OCAFBrowser (Handle(TDocStd_Document) h)
Constructor & Destructor Documentation
OCAFBrowser()
ImportGui::OCAFBrowser::OCAFBrowser (Handle(TDocStd_Document) h)
Member Function Documentation
load()
void ImportGui::OCAFBrowser::load (QTreeWidget * theTree)
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::loadDefaults(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Import/Gui/AppImportGuiPy.cpp