FreeCAD: TechDrawGui::QGITile Class Reference
TechDrawGui::QGITile Class Reference
#include <QGITile.h>
Public Types
enum { Type = QGraphicsItem::UserType + 325 }
Public Types inherited from TechDrawGui::QGIDecoration
enum { Type = QGraphicsItem::UserType + 173 }
Public Member Functions
virtual QRectF boundingRect () const
virtual void draw (void)
bool isTailRight (void)
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
QGITile (TechDraw::DrawTileWeld *)
void setAltWeld (bool b)
void setFont (QFont f, double fSizePx)
void setFont (std::string fName, double fSizePx)
void setSymbolFile (std::string s)
void setTailRight (bool b)
void setTilePosition (QPointF org, int r, int c)
void setTileScale (double s)
void setTileTextCenter (std::string s)
void setTileTextLeft (std::string s)
void setTileTextRight (std::string s)
int type (void) const
~QGITile (void)
Public Member Functions inherited from TechDrawGui::QGIDecoration
QColor getColor (void)
void makeMark (Base::Vector3d v)
void makeMark (double x, double y)
QGIDecoration (void)
void setColor (QColor c)
void setFill (Qt::BrushStyle bs)
void setStyle (Qt::PenStyle s)
void setWidth (double w)
int type () const
~QGIDecoration ()
Protected Member Functions
bool getAltWeld (void)
std::string getStringFromFile (std::string inSpec)
QByteArray getSvgString (QString svgPath)
double getSymbolFactor (void) const
double getSymbolHeight (void) const
double getSymbolWidth (void) const
QColor getTileColor (void) const
bool isReadable (QString filePath)
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value)
void makeSymbol (void)
void makeText (void)
double prefFontSize (void) const
QString prefTextFont (void) const
void setPrettyNormal ()
void setPrettyPre ()
void setPrettySel ()
Protected Member Functions inherited from TechDrawGui::QGIDecoration
virtual QColor prefNormalColor (void)
virtual QColor prefPreColor (void)
virtual QColor prefSelectColor (void)
void setPrettyNormal ()
void setPrettyPre ()
void setPrettySel ()
Additional Inherited Members
Protected Attributes inherited from TechDrawGui::QGIDecoration
QBrush m_brush
Qt::BrushStyle m_brushCurrent
QColor m_colCurrent
QColor m_colNormal
QPen m_pen
Qt::PenStyle m_styleCurrent
double m_width
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGITile()
QGITile::QGITile (TechDraw::DrawTileWeld * dtw) explicit
References getSymbolHeight(), getSymbolWidth(), TechDrawGui::QGIDecoration::m_colCurrent, TechDrawGui::QGIDecoration::m_colNormal, TechDrawGui::QGIDecoration::prefNormalColor(), and prefTextFont().
~QGITile()
QGITile::~QGITile (void)
Member Function Documentation
boundingRect()
QRectF QGITile::boundingRect () const virtual
Reimplemented from TechDrawGui::QGIDecoration.
draw()
void QGITile::draw (void) virtual
Reimplemented from TechDrawGui::QGIDecoration.
References TechDrawGui::QGCustomText::boundingRect(), getAltWeld(), getSymbolHeight(), getSymbolWidth(), isTailRight(), makeSymbol(), and makeText().
Referenced by TechDrawGui::QGIWeldSymbol::drawTile(), setPrettyNormal(), setPrettyPre(), and setPrettySel().
getAltWeld()
bool QGITile::getAltWeld (void) protected
Referenced by draw().
getStringFromFile()
std::string QGITile::getStringFromFile (std::string inSpec) protected
Referenced by makeSymbol().
getSvgString()
QByteArray TechDrawGui::QGITile::getSvgString (QString svgPath) protected
getSymbolFactor()
double QGITile::getSymbolFactor (void) const protected
References App::GetApplication(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by getSymbolHeight(), getSymbolWidth(), and makeSymbol().
getSymbolHeight()
double QGITile::getSymbolHeight (void) const protected
References App::GetApplication(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), getSymbolFactor(), and App::Application::GetUserParameter().
Referenced by draw(), and QGITile().
getSymbolWidth()
double QGITile::getSymbolWidth (void) const protected
References App::GetApplication(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), getSymbolFactor(), and App::Application::GetUserParameter().
Referenced by draw(), and QGITile().
getTileColor()
QColor QGITile::getTileColor (void) const protected
References App::Color::asValue(), App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetUnsigned(), and App::Application::GetUserParameter().
isReadable()
bool TechDrawGui::QGITile::isReadable (QString filePath) protected
isTailRight()
bool QGITile::isTailRight (void)
Referenced by draw().
itemChange()
QVariant QGITile::itemChange (GraphicsItemChange change, const QVariant & value) protected virtual
makeSymbol()
void QGITile::makeSymbol (void) protected
References TechDrawGui::QGCustomSvg::centerAt(), Base::Console(), Base::ConsoleSingleton::Error(), getStringFromFile(), getSymbolFactor(), App::PropertyString::getValue(), TechDrawGui::QGCustomSvg::load(), and TechDraw::DrawTileWeld::SymbolFile.
Referenced by draw().
makeText()
void QGITile::makeText (void) protected
References TechDrawGui::QGCustomText::boundingRect(), TechDrawGui::QGCustomText::centerAt(), TechDrawGui::QGCustomText::justifyLeftAt(), TechDrawGui::QGCustomText::justifyRightAt(), TechDrawGui::PreferencesGui::labelFontSizePX(), TechDrawGui::QGIDecoration::m_colCurrent, and TechDrawGui::QGCustomText::setColor().
Referenced by draw().
paint()
void QGITile::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) virtual
Reimplemented from TechDrawGui::QGIDecoration.
References TechDrawGui::QGIDecoration::paint().
prefFontSize()
double QGITile::prefFontSize (void) const protected
prefTextFont()
QString QGITile::prefTextFont (void) const protected
Referenced by QGITile().
setAltWeld()
void TechDrawGui::QGITile::setAltWeld (bool b)
Referenced by TechDrawGui::QGIWeldSymbol::drawTile().
setFont() [1/2]
void QGITile::setFont (QFont f, double fSizePx)
Referenced by TechDrawGui::QGIWeldSymbol::drawTile(), and setFont().
setFont() [2/2]
void QGITile::setFont (std::string fName, double fSizePx)
References Base::Tools::fromStdString(), and setFont().
setPrettyNormal()
void QGITile::setPrettyNormal (void) protected
References draw(), TechDrawGui::QGIDecoration::m_colCurrent, TechDrawGui::QGIDecoration::m_colNormal, and TechDrawGui::QGCustomText::setColor().
setPrettyPre()
void QGITile::setPrettyPre (void) protected
References draw(), TechDrawGui::QGIDecoration::m_colCurrent, TechDrawGui::QGIDecoration::prefPreColor(), and TechDrawGui::QGCustomText::setColor().
setPrettySel()
void QGITile::setPrettySel (void) protected
References draw(), TechDrawGui::QGIDecoration::m_colCurrent, TechDrawGui::QGIDecoration::prefSelectColor(), and TechDrawGui::QGCustomText::setColor().
setSymbolFile()
void QGITile::setSymbolFile (std::string s)
setTailRight()
void TechDrawGui::QGITile::setTailRight (bool b)
Referenced by TechDrawGui::QGIWeldSymbol::drawTile().
setTilePosition()
void QGITile::setTilePosition (QPointF org, int r, int c)
Referenced by TechDrawGui::QGIWeldSymbol::drawTile().
setTileScale()
void QGITile::setTileScale (double s)
Referenced by TechDrawGui::QGIWeldSymbol::drawTile().
setTileTextCenter()
void QGITile::setTileTextCenter (std::string s)
Referenced by TechDrawGui::QGIWeldSymbol::drawTile().
setTileTextLeft()
void QGITile::setTileTextLeft (std::string s)
Referenced by TechDrawGui::QGIWeldSymbol::drawTile().
setTileTextRight()
void QGITile::setTileTextRight (std::string s)
Referenced by TechDrawGui::QGIWeldSymbol::drawTile().
type()
int TechDrawGui::QGITile::type (void) const
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGITile.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGITile.cpp