FreeCAD: MeshGui::DlgEvaluateMeshImp Class Reference
MeshGui::DlgEvaluateMeshImp Class Reference
#include <DlgEvaluateMeshImp.h>
Classes
class Private
Public Member Functions
DlgEvaluateMeshImp (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
Constructs a DlgEvaluateMeshImp which is a child of 'parent', with the widget flags set to 'f'.
void setMesh (Mesh::Feature *)
~DlgEvaluateMeshImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from App::DocumentObserver
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
Protected Slots
void on_analyzeAllTogether_clicked ()
void on_analyzeDegeneratedButton_clicked ()
void on_analyzeDuplicatedFacesButton_clicked ()
void on_analyzeDuplicatedPointsButton_clicked ()
void on_analyzeFoldsButton_clicked ()
void on_analyzeIndicesButton_clicked ()
void on_analyzeNonmanifoldsButton_clicked ()
void on_analyzeOrientationButton_clicked ()
void on_analyzeSelfIntersectionButton_clicked ()
void on_buttonBox_clicked (QAbstractButton *)
void on_checkDegenerationButton_clicked ()
void on_checkDuplicatedFacesButton_clicked ()
void on_checkDuplicatedPointsButton_clicked ()
void on_checkFoldsButton_clicked ()
void on_checkIndicesButton_clicked ()
void on_checkNonmanifoldsButton_clicked ()
void on_checkOrientationButton_clicked ()
void on_checkSelfIntersectionButton_clicked ()
void on_meshNameButton_activated (int)
void on_refreshButton_clicked ()
void on_repairAllTogether_clicked ()
void on_repairDegeneratedButton_clicked ()
void on_repairDuplicatedFacesButton_clicked ()
void on_repairDuplicatedPointsButton_clicked ()
void on_repairFoldsButton_clicked ()
void on_repairIndicesButton_clicked ()
void on_repairNonmanifoldsButton_clicked ()
void on_repairOrientationButton_clicked ()
void on_repairSelfIntersectionButton_clicked ()
Protected Member Functions
void addViewProvider (const char *vp, const std::vector< Mesh::ElementIndex > &indices)
void changeEvent (QEvent *e)
void cleanInformation ()
void refreshList ()
void removeViewProvider (const char *vp)
void removeViewProviders ()
void showInformation ()
Protected Member Functions inherited from App::DocumentObserver
Document * getDocument () const
Detailed Description
Author
Werner Mayer
Constructor & Destructor Documentation
DlgEvaluateMeshImp()
DlgEvaluateMeshImp::DlgEvaluateMeshImp (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Constructs a DlgEvaluateMeshImp which is a child of 'parent', with the widget flags set to 'f'.
References MeshGui::Ui_DlgEvaluateMesh::buttonBox, MeshGui::DlgEvaluateMeshImp::Private::checkNonManfoldPoints, draftgeoutils.intersections::connect(), MeshGui::DlgEvaluateMeshImp::Private::enableFoldsCheck, MeshGui::DlgEvaluateMeshImp::Private::epsilonDegenerated, App::GetApplication(), ParameterGrp::GetBool(), Gui::getMainWindow(), App::Application::GetParameterGroupByPath(), MeshGui::Ui_DlgEvaluateMesh::line, MeshGui::Ui_DlgEvaluateMesh::line_2, MeshGui::Ui_DlgEvaluateMesh::line_3, MeshGui::Ui_DlgEvaluateMesh::line_4, MeshGui::Ui_DlgEvaluateMesh::line_5, MeshGui::Ui_DlgEvaluateMesh::line_6, MeshGui::Ui_DlgEvaluateMesh::line_7, MeshGui::Ui_DlgEvaluateMesh::line_8, on_refreshButton_clicked(), MeshGui::Ui_DlgEvaluateMesh::setupUi(), MeshGui::DlgEvaluateMeshImp::Private::showFoldsFunction(), MeshGui::DlgEvaluateMeshImp::Private::strictlyDegenerated, and MeshGui::DlgEvaluateMeshImp::Private::ui.
~DlgEvaluateMeshImp()
DlgEvaluateMeshImp::~DlgEvaluateMeshImp ()
Destroys the object and frees any allocated resources.
References MeshGui::DlgEvaluateMeshImp::Private::checkNonManfoldPoints, MeshGui::DlgEvaluateMeshImp::Private::enableFoldsCheck, App::GetApplication(), App::Application::GetParameterGroupByPath(), ParameterGrp::SetBool(), MeshGui::DlgEvaluateMeshImp::Private::strictlyDegenerated, MeshGui::DlgEvaluateMeshImp::Private::view, and MeshGui::DlgEvaluateMeshImp::Private::vp.
Member Function Documentation
addViewProvider()
void DlgEvaluateMeshImp::addViewProvider (const char * vp, const std::vector< Mesh::ElementIndex > & indices) protected
References MeshGui::ViewProviderMeshDefects::attach(), Base::Type::createInstanceByName(), Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), Base::Type::isDerivedFrom(), MeshGui::DlgEvaluateMeshImp::Private::meshFeature, removeViewProvider(), MeshGui::ViewProviderMeshDefects::showDefects(), MeshGui::DlgEvaluateMeshImp::Private::view, and MeshGui::DlgEvaluateMeshImp::Private::vp.
Referenced by on_analyzeDegeneratedButton_clicked(), on_analyzeDuplicatedFacesButton_clicked(), on_analyzeDuplicatedPointsButton_clicked(), on_analyzeFoldsButton_clicked(), on_analyzeIndicesButton_clicked(), on_analyzeNonmanifoldsButton_clicked(), on_analyzeOrientationButton_clicked(), and on_analyzeSelfIntersectionButton_clicked().
changeEvent()
void DlgEvaluateMeshImp::changeEvent (QEvent * e) protected
References MeshGui::Ui_DlgEvaluateMesh::meshNameButton, MeshGui::Ui_DlgEvaluateMesh::retranslateUi(), and MeshGui::DlgEvaluateMeshImp::Private::ui.
cleanInformation()
void DlgEvaluateMeshImp::cleanInformation () protected
References MeshGui::Ui_DlgEvaluateMesh::analyzeAllTogether, MeshGui::Ui_DlgEvaluateMesh::analyzeDegeneratedButton, MeshGui::Ui_DlgEvaluateMesh::analyzeDuplicatedFacesButton, MeshGui::Ui_DlgEvaluateMesh::analyzeDuplicatedPointsButton, MeshGui::Ui_DlgEvaluateMesh::analyzeFoldsButton, MeshGui::Ui_DlgEvaluateMesh::analyzeIndicesButton, MeshGui::Ui_DlgEvaluateMesh::analyzeNonmanifoldsButton, MeshGui::Ui_DlgEvaluateMesh::analyzeOrientationButton, MeshGui::Ui_DlgEvaluateMesh::analyzeSelfIntersectionButton, MeshGui::Ui_DlgEvaluateMesh::checkDegenerationButton, MeshGui::Ui_DlgEvaluateMesh::checkDuplicatedFacesButton, MeshGui::Ui_DlgEvaluateMesh::checkDuplicatedPointsButton, MeshGui::Ui_DlgEvaluateMesh::checkFoldsButton, MeshGui::Ui_DlgEvaluateMesh::checkIndicesButton, MeshGui::Ui_DlgEvaluateMesh::checkNonmanifoldsButton, MeshGui::Ui_DlgEvaluateMesh::checkOrientationButton, MeshGui::Ui_DlgEvaluateMesh::checkSelfIntersectionButton, MeshGui::Ui_DlgEvaluateMesh::repairAllTogether, MeshGui::Ui_DlgEvaluateMesh::repairDegeneratedButton, MeshGui::Ui_DlgEvaluateMesh::repairDuplicatedFacesButton, MeshGui::Ui_DlgEvaluateMesh::repairDuplicatedPointsButton, MeshGui::Ui_DlgEvaluateMesh::repairFoldsButton, MeshGui::Ui_DlgEvaluateMesh::repairIndicesButton, MeshGui::Ui_DlgEvaluateMesh::repairNonmanifoldsButton, MeshGui::Ui_DlgEvaluateMesh::repairOrientationButton, MeshGui::Ui_DlgEvaluateMesh::repairSelfIntersectionButton, MeshGui::Ui_DlgEvaluateMesh::textLabel4, MeshGui::Ui_DlgEvaluateMesh::textLabel5, MeshGui::Ui_DlgEvaluateMesh::textLabel6, and MeshGui::DlgEvaluateMeshImp::Private::ui.
Referenced by on_buttonBox_clicked(), on_meshNameButton_activated(), and refreshList().
on_analyzeAllTogether_clicked
void DlgEvaluateMeshImp::on_analyzeAllTogether_clicked () protected slot
References MeshGui::DlgEvaluateMeshImp::Private::enableFoldsCheck, on_analyzeDegeneratedButton_clicked(), on_analyzeDuplicatedFacesButton_clicked(), on_analyzeDuplicatedPointsButton_clicked(), on_analyzeFoldsButton_clicked(), on_analyzeIndicesButton_clicked(), on_analyzeNonmanifoldsButton_clicked(), on_analyzeOrientationButton_clicked(), and on_analyzeSelfIntersectionButton_clicked().
on_analyzeDegeneratedButton_clicked
void DlgEvaluateMeshImp::on_analyzeDegeneratedButton_clicked () protected slot
References addViewProvider(), MeshGui::Ui_DlgEvaluateMesh::analyzeDegeneratedButton, MeshGui::Ui_DlgEvaluateMesh::checkDegenerationButton, MeshGui::DlgEvaluateMeshImp::Private::epsilonDegenerated, MeshCore::MeshEvalDegeneratedFacets::GetIndices(), Mesh::MeshObject::getKernel(), Mesh::PropertyMeshKernel::getValue(), Mesh::Feature::Mesh, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, removeViewProvider(), MeshGui::Ui_DlgEvaluateMesh::repairAllTogether, MeshGui::Ui_DlgEvaluateMesh::repairDegeneratedButton, and MeshGui::DlgEvaluateMeshImp::Private::ui.
Referenced by on_analyzeAllTogether_clicked().
on_analyzeDuplicatedFacesButton_clicked
void DlgEvaluateMeshImp::on_analyzeDuplicatedFacesButton_clicked () protected slot
References addViewProvider(), MeshGui::Ui_DlgEvaluateMesh::analyzeDuplicatedFacesButton, MeshGui::Ui_DlgEvaluateMesh::checkDuplicatedFacesButton, MeshCore::MeshEvalDuplicateFacets::GetIndices(), Mesh::MeshObject::getKernel(), Mesh::PropertyMeshKernel::getValue(), Mesh::Feature::Mesh, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, removeViewProvider(), MeshGui::Ui_DlgEvaluateMesh::repairAllTogether, MeshGui::Ui_DlgEvaluateMesh::repairDuplicatedFacesButton, and MeshGui::DlgEvaluateMeshImp::Private::ui.
Referenced by on_analyzeAllTogether_clicked().
on_analyzeDuplicatedPointsButton_clicked
void DlgEvaluateMeshImp::on_analyzeDuplicatedPointsButton_clicked () protected slot
References addViewProvider(), MeshGui::Ui_DlgEvaluateMesh::analyzeDuplicatedPointsButton, MeshGui::Ui_DlgEvaluateMesh::checkDuplicatedPointsButton, MeshCore::MeshEvalDuplicatePoints::Evaluate(), MeshCore::MeshEvalDuplicatePoints::GetIndices(), Mesh::MeshObject::getKernel(), Mesh::PropertyMeshKernel::getValue(), Mesh::Feature::Mesh, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, removeViewProvider(), MeshGui::Ui_DlgEvaluateMesh::repairAllTogether, MeshGui::Ui_DlgEvaluateMesh::repairDuplicatedPointsButton, and MeshGui::DlgEvaluateMeshImp::Private::ui.
Referenced by on_analyzeAllTogether_clicked().
on_analyzeFoldsButton_clicked
void DlgEvaluateMeshImp::on_analyzeFoldsButton_clicked () protected slot
References addViewProvider(), MeshGui::Ui_DlgEvaluateMesh::analyzeFoldsButton, MeshGui::Ui_DlgEvaluateMesh::checkFoldsButton, MeshCore::MeshEvalFoldsOnSurface::Evaluate(), MeshCore::MeshEvalFoldsOnBoundary::Evaluate(), MeshCore::MeshEvalFoldOversOnSurface::Evaluate(), MeshCore::MeshEvalFoldsOnSurface::GetIndices(), MeshCore::MeshEvalFoldsOnBoundary::GetIndices(), MeshCore::MeshEvalFoldOversOnSurface::GetIndices(), Mesh::MeshObject::getKernel(), Mesh::PropertyMeshKernel::getValue(), Mesh::Feature::Mesh, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, removeViewProvider(), MeshGui::Ui_DlgEvaluateMesh::repairAllTogether, MeshGui::Ui_DlgEvaluateMesh::repairFoldsButton, and MeshGui::DlgEvaluateMeshImp::Private::ui.
Referenced by on_analyzeAllTogether_clicked().
on_analyzeIndicesButton_clicked
void DlgEvaluateMeshImp::on_analyzeIndicesButton_clicked () protected slot
References addViewProvider(), MeshGui::Ui_DlgEvaluateMesh::analyzeIndicesButton, MeshGui::Ui_DlgEvaluateMesh::checkIndicesButton, MeshCore::MeshEvalRangePoint::Evaluate(), MeshCore::MeshEvalCorruptedFacets::Evaluate(), MeshCore::MeshEvalNeighbourhood::Evaluate(), MeshCore::MeshEvalCorruptedFacets::GetIndices(), MeshCore::MeshEvalNeighbourhood::GetIndices(), Mesh::MeshObject::getKernel(), Mesh::PropertyMeshKernel::getValue(), Mesh::Feature::Mesh, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, removeViewProvider(), MeshGui::Ui_DlgEvaluateMesh::repairAllTogether, MeshGui::Ui_DlgEvaluateMesh::repairIndicesButton, and MeshGui::DlgEvaluateMeshImp::Private::ui.
Referenced by on_analyzeAllTogether_clicked().
on_analyzeNonmanifoldsButton_clicked
void DlgEvaluateMeshImp::on_analyzeNonmanifoldsButton_clicked () protected slot
References addViewProvider(), MeshGui::Ui_DlgEvaluateMesh::analyzeNonmanifoldsButton, MeshGui::DlgEvaluateMeshImp::Private::checkNonManfoldPoints, MeshGui::Ui_DlgEvaluateMesh::checkNonmanifoldsButton, MeshCore::MeshEvalTopology::CountManifolds(), MeshCore::MeshEvalTopology::Evaluate(), MeshCore::MeshEvalPointManifolds::Evaluate(), MeshCore::MeshEvalTopology::GetIndices(), MeshCore::MeshEvalPointManifolds::GetIndices(), Mesh::MeshObject::getKernel(), Mesh::PropertyMeshKernel::getValue(), Mesh::Feature::Mesh, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, removeViewProvider(), MeshGui::Ui_DlgEvaluateMesh::repairAllTogether, MeshGui::Ui_DlgEvaluateMesh::repairNonmanifoldsButton, and MeshGui::DlgEvaluateMeshImp::Private::ui.
Referenced by on_analyzeAllTogether_clicked().
on_analyzeOrientationButton_clicked
void DlgEvaluateMeshImp::on_analyzeOrientationButton_clicked () protected slot
References addViewProvider(), MeshGui::Ui_DlgEvaluateMesh::analyzeOrientationButton, MeshGui::Ui_DlgEvaluateMesh::checkOrientationButton, MeshCore::MeshEvalFoldOversOnSurface::Evaluate(), MeshCore::MeshEvalOrientation::Evaluate(), MeshCore::MeshEvalOrientation::GetIndices(), Mesh::MeshObject::getKernel(), Mesh::PropertyMeshKernel::getValue(), Mesh::Feature::Mesh, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, removeViewProvider(), MeshGui::Ui_DlgEvaluateMesh::repairAllTogether, MeshGui::Ui_DlgEvaluateMesh::repairOrientationButton, and MeshGui::DlgEvaluateMeshImp::Private::ui.
Referenced by on_analyzeAllTogether_clicked().
on_analyzeSelfIntersectionButton_clicked
void DlgEvaluateMeshImp::on_analyzeSelfIntersectionButton_clicked () protected slot
References addViewProvider(), MeshGui::Ui_DlgEvaluateMesh::analyzeSelfIntersectionButton, MeshGui::Ui_DlgEvaluateMesh::checkSelfIntersectionButton, Base::Console(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), Mesh::MeshObject::getKernel(), Mesh::PropertyMeshKernel::getValue(), Mesh::Feature::Mesh, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, Base::ConsoleSingleton::Message(), removeViewProvider(), MeshGui::Ui_DlgEvaluateMesh::repairAllTogether, MeshGui::Ui_DlgEvaluateMesh::repairSelfIntersectionButton, MeshGui::DlgEvaluateMeshImp::Private::self_intersections, and MeshGui::DlgEvaluateMeshImp::Private::ui.
Referenced by on_analyzeAllTogether_clicked().
on_buttonBox_clicked
void DlgEvaluateMeshImp::on_buttonBox_clicked (QAbstractButton * button) protected slot
References MeshGui::Ui_DlgEvaluateMesh::buttonBox, MeshGui::DlgEvaluateMeshImp::Private::checkNonManfoldPoints, cleanInformation(), MeshGui::DlgEvaluateMeshImp::Private::enableFoldsCheck, MeshGui::DlgEvaluateMeshImp::Private::epsilonDegenerated, MeshGui::DlgEvaluateSettings::isDegeneratedFacetsChecked(), MeshGui::DlgEvaluateSettings::isFoldsChecked(), MeshGui::DlgEvaluateSettings::isNonmanifoldPointsChecked(), removeViewProviders(), MeshGui::DlgEvaluateMeshImp::Private::self_intersections, MeshGui::DlgEvaluateSettings::setDegeneratedFacetsChecked(), MeshGui::DlgEvaluateSettings::setFoldsChecked(), MeshGui::DlgEvaluateSettings::setNonmanifoldPointsChecked(), MeshGui::DlgEvaluateMeshImp::Private::showFoldsFunction(), showInformation(), MeshGui::DlgEvaluateMeshImp::Private::strictlyDegenerated, and MeshGui::DlgEvaluateMeshImp::Private::ui.
on_checkDegenerationButton_clicked
void DlgEvaluateMeshImp::on_checkDegenerationButton_clicked () protected slot
References MeshGui::Ui_DlgEvaluateMesh::checkDegenerationButton, MeshGui::DlgEvaluateMeshImp::Private::ui, and MeshGui::DlgEvaluateMeshImp::Private::vp.
on_checkDuplicatedFacesButton_clicked
void DlgEvaluateMeshImp::on_checkDuplicatedFacesButton_clicked () protected slot
References MeshGui::Ui_DlgEvaluateMesh::checkDuplicatedFacesButton, MeshGui::DlgEvaluateMeshImp::Private::ui, and MeshGui::DlgEvaluateMeshImp::Private::vp.
on_checkDuplicatedPointsButton_clicked
void DlgEvaluateMeshImp::on_checkDuplicatedPointsButton_clicked () protected slot
References MeshGui::Ui_DlgEvaluateMesh::checkDuplicatedPointsButton, MeshGui::DlgEvaluateMeshImp::Private::ui, and MeshGui::DlgEvaluateMeshImp::Private::vp.
on_checkFoldsButton_clicked
void DlgEvaluateMeshImp::on_checkFoldsButton_clicked () protected slot
References MeshGui::Ui_DlgEvaluateMesh::checkFoldsButton, MeshGui::DlgEvaluateMeshImp::Private::ui, and MeshGui::DlgEvaluateMeshImp::Private::vp.
on_checkIndicesButton_clicked
void DlgEvaluateMeshImp::on_checkIndicesButton_clicked () protected slot
References MeshGui::Ui_DlgEvaluateMesh::checkIndicesButton, MeshGui::DlgEvaluateMeshImp::Private::ui, and MeshGui::DlgEvaluateMeshImp::Private::vp.
on_checkNonmanifoldsButton_clicked
void DlgEvaluateMeshImp::on_checkNonmanifoldsButton_clicked () protected slot
References MeshGui::Ui_DlgEvaluateMesh::checkNonmanifoldsButton, MeshGui::DlgEvaluateMeshImp::Private::ui, and MeshGui::DlgEvaluateMeshImp::Private::vp.
on_checkOrientationButton_clicked
void DlgEvaluateMeshImp::on_checkOrientationButton_clicked () protected slot
References MeshGui::Ui_DlgEvaluateMesh::checkOrientationButton, MeshGui::DlgEvaluateMeshImp::Private::ui, and MeshGui::DlgEvaluateMeshImp::Private::vp.
on_checkSelfIntersectionButton_clicked
void DlgEvaluateMeshImp::on_checkSelfIntersectionButton_clicked () protected slot
References MeshGui::Ui_DlgEvaluateMesh::checkSelfIntersectionButton, MeshGui::DlgEvaluateMeshImp::Private::ui, and MeshGui::DlgEvaluateMeshImp::Private::vp.
on_meshNameButton_activated
void DlgEvaluateMeshImp::on_meshNameButton_activated (int i) protected slot
References cleanInformation(), Base::Persistence::getClassTypeId(), App::DocumentObserver::getDocument(), App::Document::getObjectsOfType(), MeshGui::DlgEvaluateMeshImp::Private::meshFeature, MeshGui::Ui_DlgEvaluateMesh::meshNameButton, showInformation(), and MeshGui::DlgEvaluateMeshImp::Private::ui.
Referenced by setMesh().
on_refreshButton_clicked
void DlgEvaluateMeshImp::on_refreshButton_clicked () protected slot
References Gui::Application::activeDocument(), App::DocumentObserver::attachDocument(), App::DocumentObserver::getDocument(), Draft::gui, Gui::Application::Instance, refreshList(), removeViewProviders(), and MeshGui::DlgEvaluateMeshImp::Private::view.
Referenced by DlgEvaluateMeshImp().
on_repairAllTogether_clicked
void DlgEvaluateMeshImp::on_repairAllTogether_clicked () protected slot
References Gui::Command::App, MeshGui::Ui_DlgEvaluateMesh::checkRepeatButton, MeshGui::DlgEvaluateMeshImp::Private::enableFoldsCheck, MeshGui::DlgEvaluateMeshImp::Private::epsilonDegenerated, MeshCore::MeshEvalDuplicatePoints::Evaluate(), MeshCore::MeshEvalDuplicateFacets::Evaluate(), MeshCore::MeshEvalDegeneratedFacets::Evaluate(), MeshCore::MeshEvalFoldsOnSurface::Evaluate(), MeshCore::MeshEvalFoldsOnBoundary::Evaluate(), MeshCore::MeshEvalFoldOversOnSurface::Evaluate(), MeshCore::MeshEvalRangePoint::Evaluate(), MeshCore::MeshEvalCorruptedFacets::Evaluate(), MeshCore::MeshEvalOrientation::Evaluate(), MeshCore::MeshEvalTopology::Evaluate(), MeshCore::MeshEvalSelfIntersection::Evaluate(), MeshCore::MeshEvalNeighbourhood::Evaluate(), App::GetApplication(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), App::Application::getDocumentName(), Mesh::MeshObject::getKernel(), App::DocumentObject::getNameInDocument(), Mesh::PropertyMeshKernel::getValue(), Gui::Application::Instance, Mesh::Feature::Mesh, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, draftutils.translate::QT_TRANSLATE_NOOP, and MeshGui::DlgEvaluateMeshImp::Private::ui.
on_repairDegeneratedButton_clicked
void DlgEvaluateMeshImp::on_repairDegeneratedButton_clicked () protected slot
References Gui::Command::App, MeshGui::Ui_DlgEvaluateMesh::checkDegenerationButton, MeshGui::DlgEvaluateMeshImp::Private::epsilonDegenerated, App::GetApplication(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), App::Application::getDocumentName(), App::DocumentObject::getNameInDocument(), Gui::Application::Instance, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, draftutils.translate::QT_TRANSLATE_NOOP, removeViewProvider(), MeshGui::Ui_DlgEvaluateMesh::repairDegeneratedButton, and MeshGui::DlgEvaluateMeshImp::Private::ui.
on_repairDuplicatedFacesButton_clicked
void DlgEvaluateMeshImp::on_repairDuplicatedFacesButton_clicked () protected slot
References Gui::Command::App, MeshGui::Ui_DlgEvaluateMesh::checkDuplicatedFacesButton, App::GetApplication(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), App::Application::getDocumentName(), App::DocumentObject::getNameInDocument(), Gui::Application::Instance, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, draftutils.translate::QT_TRANSLATE_NOOP, removeViewProvider(), MeshGui::Ui_DlgEvaluateMesh::repairDuplicatedFacesButton, and MeshGui::DlgEvaluateMeshImp::Private::ui.
on_repairDuplicatedPointsButton_clicked
void DlgEvaluateMeshImp::on_repairDuplicatedPointsButton_clicked () protected slot
References Gui::Command::App, MeshGui::Ui_DlgEvaluateMesh::checkDuplicatedPointsButton, App::GetApplication(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), App::Application::getDocumentName(), App::DocumentObject::getNameInDocument(), Gui::Application::Instance, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, draftutils.translate::QT_TRANSLATE_NOOP, removeViewProvider(), MeshGui::Ui_DlgEvaluateMesh::repairDuplicatedPointsButton, and MeshGui::DlgEvaluateMeshImp::Private::ui.
on_repairFoldsButton_clicked
void DlgEvaluateMeshImp::on_repairFoldsButton_clicked () protected slot
References Gui::Command::App, MeshGui::Ui_DlgEvaluateMesh::checkFoldsButton, App::GetApplication(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), App::Application::getDocumentName(), App::DocumentObject::getNameInDocument(), Gui::Application::Instance, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, draftutils.translate::QT_TRANSLATE_NOOP, removeViewProvider(), MeshGui::Ui_DlgEvaluateMesh::repairFoldsButton, and MeshGui::DlgEvaluateMeshImp::Private::ui.
on_repairIndicesButton_clicked
void DlgEvaluateMeshImp::on_repairIndicesButton_clicked () protected slot
References Gui::Command::App, MeshGui::Ui_DlgEvaluateMesh::checkIndicesButton, App::GetApplication(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), App::Application::getDocumentName(), App::DocumentObject::getNameInDocument(), Gui::Application::Instance, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, draftutils.translate::QT_TRANSLATE_NOOP, removeViewProvider(), MeshGui::Ui_DlgEvaluateMesh::repairIndicesButton, and MeshGui::DlgEvaluateMeshImp::Private::ui.
on_repairNonmanifoldsButton_clicked
void DlgEvaluateMeshImp::on_repairNonmanifoldsButton_clicked () protected slot
References Gui::Command::App, MeshGui::DlgEvaluateMeshImp::Private::checkNonManfoldPoints, MeshGui::Ui_DlgEvaluateMesh::checkNonmanifoldsButton, App::GetApplication(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), App::Application::getDocumentName(), App::DocumentObject::getNameInDocument(), Gui::Application::Instance, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, draftutils.translate::QT_TRANSLATE_NOOP, removeViewProvider(), MeshGui::Ui_DlgEvaluateMesh::repairNonmanifoldsButton, and MeshGui::DlgEvaluateMeshImp::Private::ui.
on_repairOrientationButton_clicked
void DlgEvaluateMeshImp::on_repairOrientationButton_clicked () protected slot
References Gui::Command::App, MeshGui::Ui_DlgEvaluateMesh::checkOrientationButton, App::GetApplication(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), App::Application::getDocumentName(), App::DocumentObject::getNameInDocument(), Gui::Application::Instance, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, draftutils.translate::QT_TRANSLATE_NOOP, removeViewProvider(), MeshGui::Ui_DlgEvaluateMesh::repairOrientationButton, and MeshGui::DlgEvaluateMeshImp::Private::ui.
on_repairSelfIntersectionButton_clicked
void DlgEvaluateMeshImp::on_repairSelfIntersectionButton_clicked () protected slot
References MeshGui::Ui_DlgEvaluateMesh::checkSelfIntersectionButton, Mesh::PropertyMeshKernel::finishEditing(), App::GetApplication(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), App::Application::getDocumentName(), App::DocumentObject::getNameInDocument(), Gui::Application::Instance, Mesh::Feature::Mesh, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, draftutils.translate::QT_TRANSLATE_NOOP, removeViewProvider(), MeshGui::Ui_DlgEvaluateMesh::repairSelfIntersectionButton, MeshGui::DlgEvaluateMeshImp::Private::self_intersections, Mesh::PropertyMeshKernel::startEditing(), and MeshGui::DlgEvaluateMeshImp::Private::ui.
refreshList()
void DlgEvaluateMeshImp::refreshList () protected
References cleanInformation(), Base::Persistence::getClassTypeId(), App::DocumentObserver::getDocument(), App::Document::getObjectsOfType(), MeshGui::Ui_DlgEvaluateMesh::meshNameButton, and MeshGui::DlgEvaluateMeshImp::Private::ui.
Referenced by on_refreshButton_clicked(), and setMesh().
removeViewProvider()
void DlgEvaluateMeshImp::removeViewProvider (const char * vp) protected
References MeshGui::DlgEvaluateMeshImp::Private::view, and MeshGui::DlgEvaluateMeshImp::Private::vp.
Referenced by addViewProvider(), on_analyzeDegeneratedButton_clicked(), on_analyzeDuplicatedFacesButton_clicked(), on_analyzeDuplicatedPointsButton_clicked(), on_analyzeFoldsButton_clicked(), on_analyzeIndicesButton_clicked(), on_analyzeNonmanifoldsButton_clicked(), on_analyzeOrientationButton_clicked(), on_analyzeSelfIntersectionButton_clicked(), on_repairDegeneratedButton_clicked(), on_repairDuplicatedFacesButton_clicked(), on_repairDuplicatedPointsButton_clicked(), on_repairFoldsButton_clicked(), on_repairIndicesButton_clicked(), on_repairNonmanifoldsButton_clicked(), on_repairOrientationButton_clicked(), and on_repairSelfIntersectionButton_clicked().
removeViewProviders()
void DlgEvaluateMeshImp::removeViewProviders () protected
References MeshGui::DlgEvaluateMeshImp::Private::view, and MeshGui::DlgEvaluateMeshImp::Private::vp.
Referenced by on_buttonBox_clicked(), and on_refreshButton_clicked().
setMesh()
void DlgEvaluateMeshImp::setMesh (Mesh::Feature * m)
References App::DocumentObserver::attachDocument(), App::DocumentObserver::getDocument(), MeshGui::Ui_DlgEvaluateMesh::meshNameButton, on_meshNameButton_activated(), refreshList(), and MeshGui::DlgEvaluateMeshImp::Private::ui.
showInformation()
void DlgEvaluateMeshImp::showInformation () protected
References MeshGui::Ui_DlgEvaluateMesh::analyzeAllTogether, MeshGui::Ui_DlgEvaluateMesh::analyzeDegeneratedButton, MeshGui::Ui_DlgEvaluateMesh::analyzeDuplicatedFacesButton, MeshGui::Ui_DlgEvaluateMesh::analyzeDuplicatedPointsButton, MeshGui::Ui_DlgEvaluateMesh::analyzeFoldsButton, MeshGui::Ui_DlgEvaluateMesh::analyzeIndicesButton, MeshGui::Ui_DlgEvaluateMesh::analyzeNonmanifoldsButton, MeshGui::Ui_DlgEvaluateMesh::analyzeOrientationButton, MeshGui::Ui_DlgEvaluateMesh::analyzeSelfIntersectionButton, MeshCore::MeshKernel::CountEdges(), MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::CountPoints(), Mesh::MeshObject::getKernel(), Mesh::PropertyMeshKernel::getValue(), Mesh::Feature::Mesh, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, MeshGui::Ui_DlgEvaluateMesh::textLabel4, MeshGui::Ui_DlgEvaluateMesh::textLabel5, MeshGui::Ui_DlgEvaluateMesh::textLabel6, and MeshGui::DlgEvaluateMeshImp::Private::ui.
Referenced by on_buttonBox_clicked(), and on_meshNameButton_activated().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/Gui/DlgEvaluateMeshImp.h
FreeCAD/src/Mod/Mesh/Gui/DlgEvaluateMeshImp.cpp