FreeCAD: PartDesignGui::Ui_TaskMultiTransformParameters Class Reference
PartDesignGui::Ui_TaskMultiTransformParameters Class Reference
#include <ui_TaskMultiTransformParameters.h>
Public Member Functions
void retranslateUi (QWidget *PartDesignGui__TaskMultiTransformParameters)
void setupUi (QWidget *PartDesignGui__TaskMultiTransformParameters)
Public Attributes
QPushButton * buttonAddFeature
QPushButton * buttonRemoveFeature
QCheckBox * checkBoxUpdateView
QHBoxLayout * horizontalLayout
QLabel * label
QListWidget * listTransformFeatures
QListWidget * listWidgetFeatures
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void PartDesignGui::Ui_TaskMultiTransformParameters::retranslateUi (QWidget * PartDesignGui__TaskMultiTransformParameters)
References buttonAddFeature, buttonRemoveFeature, checkBoxUpdateView, listWidgetFeatures, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void PartDesignGui::Ui_TaskMultiTransformParameters::setupUi (QWidget * PartDesignGui__TaskMultiTransformParameters)
References buttonAddFeature, buttonRemoveFeature, checkBoxUpdateView, draftgeoutils.intersections::connect(), horizontalLayout, listTransformFeatures, listWidgetFeatures, retranslateUi(), and verticalLayout.
Member Data Documentation
buttonAddFeature
QPushButton* PartDesignGui::Ui_TaskMultiTransformParameters::buttonAddFeature
Referenced by retranslateUi(), and setupUi().
buttonRemoveFeature
QPushButton* PartDesignGui::Ui_TaskMultiTransformParameters::buttonRemoveFeature
Referenced by retranslateUi(), and setupUi().
checkBoxUpdateView
QCheckBox* PartDesignGui::Ui_TaskMultiTransformParameters::checkBoxUpdateView
Referenced by retranslateUi(), and setupUi().
horizontalLayout
QHBoxLayout* PartDesignGui::Ui_TaskMultiTransformParameters::horizontalLayout
Referenced by setupUi().
label
QLabel* PartDesignGui::Ui_TaskMultiTransformParameters::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
listTransformFeatures
QListWidget* PartDesignGui::Ui_TaskMultiTransformParameters::listTransformFeatures
Referenced by setupUi().
listWidgetFeatures
QListWidget* PartDesignGui::Ui_TaskMultiTransformParameters::listWidgetFeatures
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* PartDesignGui::Ui_TaskMultiTransformParameters::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/PartDesign/Gui/ui_TaskMultiTransformParameters.h