FreeCAD: Gui::ViewParams Class Reference
Gui::ViewParams Class Reference
Convenient class to obtain view provider related parameters.
#include <ViewParams.h>
Public Member Functions
ParameterGrp::handle getHandle ()
void OnChange (Base::Subject< const char * > &, const char *sReason)
ViewParams ()
virtual ~ViewParams ()
Static Public Member Functions
static ViewParams * instance ()
Detailed Description
Convenient class to obtain view provider related parameters.
The parameters are under group "User parameter:BaseApp/Preferences/View"
Constructor & Destructor Documentation
ViewParams()
ViewParams::ViewParams ()
References Base::Subject< _MessageType >::Attach(), App::GetApplication(), and App::Application::GetParameterGroupByPath().
Referenced by instance().
~ViewParams()
ViewParams::~ViewParams () virtual
Member Function Documentation
getHandle()
ParameterGrp::handle Gui::ViewParams::getHandle ()
instance()
ViewParams * ViewParams::instance (void) static
References ViewParams().
Referenced by Gui::ViewProviderMeasureDistance::attach(), Gui::LinkInfo::getSnapshot(), Gui::SoFCPathAnnotation::GLRenderBelowPath(), Gui::SoFCSelectionRoot::renderPrivate(), Gui::View3DInventorViewer::setRenderCache(), Gui::SoFCSelection::SoFCSelection(), Gui::ViewProvider::useNewSelectionModel(), Gui::ViewProviderLink::ViewProviderLink(), PartGui::ViewProviderPartExt::ViewProviderPartExt(), and Gui::ViewProviderPointMarker::ViewProviderPointMarker().
OnChange()
void ViewParams::OnChange (Base::Subject< const char * > & , const char * sReason)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/ViewParams.h
Sources/FreeCAD/src/Gui/ViewParams.cpp