FreeCAD: SurfaceGui::Ui_TaskFillingVertex Class Reference
SurfaceGui::Ui_TaskFillingVertex Class Reference
#include <ui_TaskFillingVertex.h>
Public Member Functions
void retranslateUi (QWidget *SurfaceGui__TaskFillingVertex)
void setupUi (QWidget *SurfaceGui__TaskFillingVertex)
Public Attributes
QToolButton * buttonVertexAdd
QToolButton * buttonVertexRemove
QGridLayout * gridLayout
QGridLayout * gridLayout_2
QGroupBox * groupBox
QHBoxLayout * horizontalLayout
QListWidget * listFreeVertex
Member Function Documentation
retranslateUi()
void SurfaceGui::Ui_TaskFillingVertex::retranslateUi (QWidget * SurfaceGui__TaskFillingVertex)
References buttonVertexAdd, buttonVertexRemove, groupBox, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), SurfaceGui::FillingVertexPanel::changeEvent(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void SurfaceGui::Ui_TaskFillingVertex::setupUi (QWidget * SurfaceGui__TaskFillingVertex)
References buttonVertexAdd, buttonVertexRemove, gridLayout, gridLayout_2, groupBox, horizontalLayout, listFreeVertex, and retranslateUi().
Referenced by SurfaceGui::FillingVertexPanel::FillingVertexPanel().
Member Data Documentation
buttonVertexAdd
QToolButton* SurfaceGui::Ui_TaskFillingVertex::buttonVertexAdd
Referenced by retranslateUi(), and setupUi().
buttonVertexRemove
QToolButton* SurfaceGui::Ui_TaskFillingVertex::buttonVertexRemove
Referenced by retranslateUi(), and setupUi().
gridLayout
QGridLayout* SurfaceGui::Ui_TaskFillingVertex::gridLayout
Referenced by setupUi().
gridLayout_2
QGridLayout* SurfaceGui::Ui_TaskFillingVertex::gridLayout_2
Referenced by setupUi().
groupBox
QGroupBox* SurfaceGui::Ui_TaskFillingVertex::groupBox
Referenced by retranslateUi(), and setupUi().
horizontalLayout
QHBoxLayout* SurfaceGui::Ui_TaskFillingVertex::horizontalLayout
Referenced by setupUi().
listFreeVertex
QListWidget* SurfaceGui::Ui_TaskFillingVertex::listFreeVertex
Referenced by SurfaceGui::FillingVertexPanel::FillingVertexPanel(), SurfaceGui::FillingVertexPanel::onSelectionChanged(), SurfaceGui::FillingVertexPanel::setEditedObject(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Surface/Gui/ui_TaskFillingVertex.h