FreeCAD: SMESH_IndexedMap< TheKeyType > Class Template Reference
SMESH_IndexedMap< TheKeyType > Class Template Reference
Purpose: An indexed map is used to store keys and to bind an index to them.
#include <SMESH_IndexedMap.hxx>
Classes
class Iterator
Public Member Functions
Standard_Integer Add (const TheKeyType &theKey1)
Add.
virtual void Assign (const NCollection_BaseCollection< TheKeyType > &theOther)
Assign another collection.
void Clear (const Handle(NCollection_BaseAllocator)&theAllocator)
Clear data and reset allocator.
void Clear (const Standard_Boolean doReleaseMemory=Standard_True)
Clear data.
Standard_Boolean Contains (const TheKeyType &theKey1) const
Contains.
Standard_Integer FindIndex (const TheKeyType &theKey1) const
FindIndex.
const TheKeyType & FindKey (const Standard_Integer theKey2) const
FindKey.
const TheKeyType & operator() (const Standard_Integer theKey2) const
operator ()
SMESH_IndexedMap & operator= (const SMESH_IndexedMap &theOther)
= another map
void RemoveLast (void)
RemoveLast.
void ReSize (const Standard_Integer N)
ReSize.
virtual Standard_Integer Size (void) const
Size.
SMESH_IndexedMap (const SMESH_IndexedMap &theOther)
Copy constructor.
SMESH_IndexedMap (const Standard_Integer NbBuckets=1, const Handle(NCollection_BaseAllocator)&theAllocator=0L)
Constructor.
void Substitute (const Standard_Integer theIndex, const TheKeyType &theKey1)
Substitute.
~SMESH_IndexedMap (void)
Destructor.
Detailed Description
template<class TheKeyType>
class SMESH_IndexedMap< TheKeyType >
Purpose: An indexed map is used to store keys and to bind an index to them.
Each new key stored in the map gets an index. Index are incremented as keys are stored in the map. A key can be found by the index and an index by the key. No key but the last can be removed so the indices are in the range 1..Extent. See the class Map from NCollection for a discussion about the number of buckets.
Constructor & Destructor Documentation
SMESH_IndexedMap() [1/2]
template<class TheKeyType > SMESH_IndexedMap< TheKeyType >::SMESH_IndexedMap (const Standard_Integer NbBuckets = 1, const Handle(NCollection_BaseAllocator)& theAllocator = 0L)
Constructor.
SMESH_IndexedMap() [2/2]
template<class TheKeyType > SMESH_IndexedMap< TheKeyType >::SMESH_IndexedMap (const SMESH_IndexedMap< TheKeyType > & theOther)
Copy constructor.
~SMESH_IndexedMap()
template<class TheKeyType > SMESH_IndexedMap< TheKeyType >::~SMESH_IndexedMap (void)
Destructor.
References SMESH_IndexedMap< TheKeyType >::Clear().
Member Function Documentation
Add()
template<class TheKeyType > Standard_Integer SMESH_IndexedMap< TheKeyType >::Add (const TheKeyType & theKey1)
Add.
References SMESH_IndexedMap< TheKeyType >::ReSize().
Referenced by SMESH_IndexedMap< TheKeyType >::Assign().
Assign()
template<class TheKeyType > virtual void SMESH_IndexedMap< TheKeyType >::Assign (const NCollection_BaseCollection< TheKeyType > & theOther) virtual
Assign another collection.
References SMESH_IndexedMap< TheKeyType >::Add(), SMESH_IndexedMap< TheKeyType >::Clear(), and SMESH_IndexedMap< TheKeyType >::ReSize().
Clear() [1/2]
template<class TheKeyType > void SMESH_IndexedMap< TheKeyType >::Clear (const Handle(NCollection_BaseAllocator)& theAllocator)
Clear data and reset allocator.
References SMESH_IndexedMap< TheKeyType >::Clear().
Clear() [2/2]
template<class TheKeyType > void SMESH_IndexedMap< TheKeyType >::Clear (const Standard_Boolean doReleaseMemory = Standard_True)
Clear data.
If doReleaseMemory is false then the table of buckets is not released and will be reused.
Referenced by SMESH_IndexedMap< TheKeyType >::Assign(), SMESH_IndexedMap< TheKeyType >::Clear(), SMESH_IndexedMap< TheKeyType >::operator=(), and SMESH_IndexedMap< TheKeyType >::~SMESH_IndexedMap().
Contains()
template<class TheKeyType > Standard_Boolean SMESH_IndexedMap< TheKeyType >::Contains (const TheKeyType & theKey1) const
Contains.
FindIndex()
template<class TheKeyType > Standard_Integer SMESH_IndexedMap< TheKeyType >::FindIndex (const TheKeyType & theKey1) const
FindIndex.
FindKey()
template<class TheKeyType > const TheKeyType & SMESH_IndexedMap< TheKeyType >::FindKey (const Standard_Integer theKey2) const
FindKey.
Referenced by SMESH_IndexedMap< TheKeyType >::operator()(), and SMESH_IndexedMap< TheKeyType >::Iterator::Value().
operator()()
template<class TheKeyType > const TheKeyType & SMESH_IndexedMap< TheKeyType >::operator() (const Standard_Integer theKey2) const
operator ()
References SMESH_IndexedMap< TheKeyType >::FindKey().
operator=()
template<class TheKeyType > SMESH_IndexedMap & SMESH_IndexedMap< TheKeyType >::operator= (const SMESH_IndexedMap< TheKeyType > & theOther)
= another map
References SMESH_IndexedMap< TheKeyType >::Clear(), and SMESH_IndexedMap< TheKeyType >::ReSize().
RemoveLast()
template<class TheKeyType > void SMESH_IndexedMap< TheKeyType >::RemoveLast (void)
RemoveLast.
ReSize()
template<class TheKeyType > void SMESH_IndexedMap< TheKeyType >::ReSize (const Standard_Integer N)
ReSize.
Referenced by SMESH_IndexedMap< TheKeyType >::Add(), SMESH_IndexedMap< TheKeyType >::Assign(), and SMESH_IndexedMap< TheKeyType >::operator=().
Size()
template<class TheKeyType > virtual Standard_Integer SMESH_IndexedMap< TheKeyType >::Size (void) const virtual
Size.
Substitute()
template<class TheKeyType > void SMESH_IndexedMap< TheKeyType >::Substitute (const Standard_Integer theIndex, const TheKeyType & theKey1)
Substitute.
The documentation for this class was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_IndexedMap.hxx