FreeCAD: Gui::VectorListEditor Class Reference
Gui::VectorListEditor Class Reference
#include <VectorListEditor.h>
Public Member Functions
void accept ()
const QList< Base::Vector3d > & getValues () const
void reject ()
void setValues (const QList< Base::Vector3d > &)
VectorListEditor (int decimals, QWidget *parent=nullptr)
~VectorListEditor ()
Constructor & Destructor Documentation
VectorListEditor()
VectorListEditor::VectorListEditor (int decimals, QWidget * parent = nullptr)
References accept(), draftgeoutils.intersections::connect(), and reject().
~VectorListEditor()
VectorListEditor::~VectorListEditor ()
Member Function Documentation
accept()
void VectorListEditor::accept (void)
References Gui::VectorTableModel::values().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit(), and VectorListEditor().
getValues()
const QList< Base::Vector3d > & VectorListEditor::getValues (void) const
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::loadDefaults(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle().
reject()
void VectorListEditor::reject (void)
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit(), and VectorListEditor().
setValues()
void VectorListEditor::setValues (const QList< Base::Vector3d > & v)
References Gui::VectorTableModel::data(), and Gui::VectorTableModel::setValues().
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/VectorListEditor.h
FreeCAD/src/Gui/VectorListEditor.cpp