FreeCAD: femexamples.material_multiple_bendingbeam_fiveboxes Namespace Reference
femexamples.material_multiple_bendingbeam_fiveboxes Namespace Reference
Functions
def get_information ()
def init_doc (doc=None)
def setup (doc=None, solvertype="ccxtools")
Variables
string mesh_name = "Mesh"
Function Documentation
get_information()
def femexamples.material_multiple_bendingbeam_fiveboxes.get_information ()
init_doc()
def femexamples.material_multiple_bendingbeam_fiveboxes.init_doc (doc = None)
Referenced by femexamples.material_multiple_bendingbeam_fiveboxes.setup().
setup()
def femexamples.material_multiple_bendingbeam_fiveboxes.setup (doc = None, solvertype = "ccxtools")
References femexamples.material_multiple_bendingbeam_fiveboxes.init_doc(), ObjectsFem.makeAnalysis(), BOPTools.SplitFeatures.makeBooleanFragments(), ObjectsFem.makeConstraintFixed(), ObjectsFem.makeConstraintForce(), ObjectsFem.makeMaterialSolid(), ObjectsFem.makeMeshGmsh(), ObjectsFem.makeSolverCalculix(), and ObjectsFem.makeSolverCalculixCcxTools().
Variable Documentation
mesh_name
string femexamples.material_multiple_bendingbeam_fiveboxes.mesh_name = "Mesh"