FreeCAD: Gui::TaskView::TaskSketcherCreateCommands Class Reference
Gui::TaskView::TaskSketcherCreateCommands Class Reference
#include <TaskSketcherCreateCommands.h>
Public Member Functions
void OnChange (Gui::SelectionSingleton::SubjectType &rCaller, Gui::SelectionSingleton::MessageType Reason)
Observer message from the Selection.
TaskSketcherCreateCommands (QWidget *parent=0)
~TaskSketcherCreateCommands ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (QWidget *parent=0)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (QWidget *parent=0)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Protected Member Functions
void changeEvent (QEvent *e)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskSketcherCreateCommands()
TaskSketcherCreateCommands::TaskSketcherCreateCommands (QWidget * parent = 0)
References Base::Subject< _MessageType >::Attach(), and Gui::Selection().
~TaskSketcherCreateCommands()
TaskSketcherCreateCommands::~TaskSketcherCreateCommands ()
References Base::Subject< _MessageType >::Detach(), and Gui::Selection().
Member Function Documentation
changeEvent()
void TaskSketcherCreateCommands::changeEvent (QEvent * e) protected
OnChange()
void Gui::TaskView::TaskSketcherCreateCommands::OnChange (Gui::SelectionSingleton::SubjectType & rCaller, Gui::SelectionSingleton::MessageType Reason)
Observer message from the Selection.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Sketcher/Gui/TaskSketcherCreateCommands.h
Sources/FreeCAD/src/Mod/Sketcher/Gui/TaskSketcherCreateCommands.cpp