FreeCAD: App::MergeDocuments Class Reference
App::MergeDocuments Class Reference
#include <MergeDocuments.h>
Public Member Functions
void exportObject (const std::vector< App::DocumentObject * > &o, Base::Writer &w)
unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
const std::map< std::string, std::string > & getNameMap () const
void importObject (const std::vector< App::DocumentObject * > &o, Base::XMLReader &r)
std::vector< App::DocumentObject * > importObjects (std::istream &)
bool isVerbose () const
MergeDocuments (App::Document *doc)
void Restore (Base::XMLReader &r)
This method is used to restore properties from an XML document.
void RestoreDocFile (Base::Reader &r)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void Save (Base::Writer &w) const
This method is used to save properties to an XML document.
void SaveDocFile (Base::Writer &w) const
This method is used to save large amounts of data to a binary file.
void setVerbose (bool on)
~MergeDocuments ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
MergeDocuments()
MergeDocuments::MergeDocuments (App::Document * doc)
References draftgeoutils.faces::bind(), exportObject(), and importObject().
~MergeDocuments()
MergeDocuments::~MergeDocuments ()
Member Function Documentation
exportObject()
void MergeDocuments::exportObject (const std::vector< App::DocumentObject * > & o, Base::Writer & w)
References Save().
Referenced by MergeDocuments().
getMemSize()
unsigned int MergeDocuments::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
getNameMap()
const std::map< std::string, std::string > & App::MergeDocuments::getNameMap () const
Referenced by App::Document::importLinks().
importObject()
void MergeDocuments::importObject (const std::vector< App::DocumentObject * > & o, Base::XMLReader & r)
References Restore().
Referenced by MergeDocuments().
importObjects()
std::vector< App::DocumentObject * > MergeDocuments::importObjects (std::istream & input)
References App::Document::importObjects(), isVerbose(), and Base::XMLReader::setVerbose().
Referenced by App::Document::copyObject(), and App::Document::importLinks().
isVerbose()
bool App::MergeDocuments::isVerbose () const
Referenced by importObjects().
Restore()
void MergeDocuments::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Referenced by importObject().
RestoreDocFile()
void MergeDocuments::RestoreDocFile (Base::Reader &) virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Base::Persistence.
References App::Document::signalImportViewObjects.
Save()
void MergeDocuments::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Referenced by exportObject().
SaveDocFile()
void MergeDocuments::SaveDocFile (Base::Writer &) const virtual
This method is used to save large amounts of data to a binary file.
Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) << "\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
void PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Base::Persistence.
References App::Document::signalExportViewObjects.
setVerbose()
void App::MergeDocuments::setVerbose (bool on)
Referenced by App::Document::copyObject().
The documentation for this class was generated from the following files:
FreeCAD/src/App/MergeDocuments.h
FreeCAD/src/App/MergeDocuments.cpp