FreeCAD: Path::Toolpath Class Reference
Path::Toolpath Class Reference
The representation of a CNC Toolpath.
#include <Path.h>
Public Member Functions
void addCommand (const Command &Cmd)
void clear (void)
void deleteCommand (int)
Base::BoundBox3d getBoundBox (void) const
const Base::Vector3d & getCenter () const
const Command & getCommand (unsigned int pos) const
const std::vector< Command * > & getCommands (void) const
double getCycleTime (double, double, double, double)
double getLength (void)
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
unsigned int getSize (void) const
void insertCommand (const Command &Cmd, int)
Toolpath & operator= (const Toolpath &)
void recalculate (void)
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
void RestoreDocFile (Base::Reader &reader)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
void SaveDocFile (Base::Writer &writer) const
This method is used to save large amounts of data to a binary file.
void setCenter (const Base::Vector3d &c)
void setFromGCode (const std::string)
std::string toGCode (void) const
Toolpath ()
Toolpath (const Toolpath &)
~Toolpath ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Static Public Attributes
static const int SchemaVersion = 2
Protected Attributes
Base::Vector3d center
std::vector< Command * > vpcCommands
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The representation of a CNC Toolpath.
Constructor & Destructor Documentation
Toolpath() [1/2]
Toolpath::Toolpath ()
Toolpath() [2/2]
Toolpath::Toolpath (const Toolpath & otherPath)
References recalculate().
~Toolpath()
Toolpath::~Toolpath ()
References clear().
Member Function Documentation
addCommand()
void Toolpath::addCommand (const Command & Cmd)
References recalculate(), and vpcCommands.
Referenced by insertCommand().
clear()
void Toolpath::clear (void)
References recalculate(), and vpcCommands.
Referenced by operator=(), setFromGCode(), and ~Toolpath().
deleteCommand()
void Toolpath::deleteCommand (int pos)
References recalculate(), and vpcCommands.
getBoundBox()
Base::BoundBox3d Toolpath::getBoundBox (void) const
References BoundBoxSegmentVisitor::bb, and Path::PathSegmentWalker::walk().
getCenter()
const Base::Vector3d & Path::Toolpath::getCenter (void) const
Referenced by Path::PathSegmentWalker::walk().
getCommand()
const Command & Path::Toolpath::getCommand (unsigned int pos) const
Referenced by PathGui::ViewProviderPath::getElement(), and Path::PathSegmentWalker::walk().
getCommands()
const std::vector< Command * > & Path::Toolpath::getCommands (void) const
Referenced by Path::FeatureCompound::execute().
getCycleTime()
double Toolpath::getCycleTime (double hFeed, double vFeed, double hRapid, double vRapid)
References center, Base::Console(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), vpcCommands, Base::ConsoleSingleton::Warning(), and Base::Vector3< _Precision >::z.
Referenced by PathScripts.PathJob.ObjectJob::execute().
getLength()
double Toolpath::getLength (void)
References center, and vpcCommands.
getMemSize()
unsigned int Toolpath::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
References toGCode().
getSize()
unsigned int Path::Toolpath::getSize (void) const
Referenced by PathGui::ViewProviderPath::getElement(), Save(), PathGui::ViewProviderPath::updateShowConstraints(), VisualPathSegmentVisitor::VisualPathSegmentVisitor(), and Path::PathSegmentWalker::walk().
insertCommand()
void Toolpath::insertCommand (const Command & Cmd, int pos)
References addCommand(), recalculate(), and vpcCommands.
operator=()
Toolpath & Toolpath::operator= (const Toolpath & otherPath)
References center, clear(), recalculate(), and vpcCommands.
recalculate()
void Toolpath::recalculate (void)
References center, Base::Placement::getPosition(), Base::Rotation::getValue(), vpcCommands, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by addCommand(), clear(), deleteCommand(), insertCommand(), operator=(), setCenter(), setFromGCode(), and Toolpath().
Restore()
void Toolpath::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References Base::XMLReader::addFile(), Base::XMLReader::getAttribute(), and Base::XMLReader::readElement().
RestoreDocFile()
void Toolpath::RestoreDocFile (Base::Reader &) virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Base::Persistence.
References setFromGCode().
Save()
void Toolpath::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References Base::Writer::addFile(), center, Base::Writer::decInd(), getSize(), Base::Writer::incInd(), Base::Writer::ind(), Base::Writer::isForceXML(), Base::Writer::ObjectName, SchemaVersion, Base::Writer::Stream(), and vpcCommands.
SaveDocFile()
void Toolpath::SaveDocFile (Base::Writer &) const virtual
This method is used to save large amounts of data to a binary file.
Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) << "\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
void PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Base::Persistence.
References Base::Writer::Stream(), and toGCode().
setCenter()
void Toolpath::setCenter (const Base::Vector3d & c)
References center, and recalculate().
Referenced by draftguitools.gui_trackers.arcTracker::setBy3Points().
setFromGCode()
void Toolpath::setFromGCode (const std::string instr)
References clear(), recalculate(), and vpcCommands.
Referenced by RestoreDocFile().
toGCode()
std::string Toolpath::toGCode (void) const
References vpcCommands.
Referenced by getMemSize(), and SaveDocFile().
Member Data Documentation
center
Base::Vector3d Path::Toolpath::center protected
Referenced by drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rotate.Rotate::build_copy_subelements_command(), draftguitools.gui_scale.Scale::build_copy_subelements_command(), draftguitools.gui_rotate.Rotate::build_rotate_subelements_command(), draftguitools.gui_scale.Scale::build_scale_subelements_command(), draftguitools.gui_dimensions.Dimension::create_angle_dimension(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::create_object(), drafttaskpanels.task_polararray.TaskPanelPolarArray::create_object(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), PathScripts.PathDressupAxisMap.ObjectDressup::execute(), getCycleTime(), getLength(), draftguitools.gui_rotate.Rotate::handle_mouse_move_event(), draftguitools.gui_arcs.Arc::numericInput(), draftguitools.gui_polygons.Polygon::numericInput(), draftguitools.gui_rotate.Rotate::numericInput(), draftguitools.gui_arcs.Arc::numericRadius(), draftguitools.gui_polygons.Polygon::numericRadius(), PathScripts.PathDressupAxisMap.ObjectDressup::onChanged(), operator=(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::print_messages(), drafttaskpanels.task_polararray.TaskPanelPolarArray::print_messages(), recalculate(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reset_point(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reset_point(), draftguitools.gui_rotate.Rotate::rotate_object(), Save(), draftguitools.gui_scale.Scale::scale_object(), draftguitools.gui_rotate.Rotate::set_center(), draftguitools.gui_rotate.Rotate::set_ghosts(), draftguitools.gui_rotate.Rotate::set_rotation_angle(), and setCenter().
SchemaVersion
const int Path::Toolpath::SchemaVersion = 2 static
Referenced by Path::PropertyPath::Restore(), and Save().
vpcCommands
std::vector<Command*> Path::Toolpath::vpcCommands protected
Referenced by addCommand(), clear(), deleteCommand(), getCycleTime(), getLength(), insertCommand(), operator=(), recalculate(), Save(), setFromGCode(), and toGCode().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Path/App/Path.h
FreeCAD/src/Mod/Path/App/Path.cpp