FreeCAD: VISCOUS_3D::_ViscousListener Class Reference
VISCOUS_3D::_ViscousListener Class Reference
Listener of events of 3D sub-meshes computed with viscous layers. It is used to store data computed by _ViscousBuilder for a sub-mesh and to delete the data as soon as it has been used.
Public Member Functions
virtual void ProcessEvent (const int event, const int eventType, SMESH_subMesh *subMesh, SMESH_subMeshEventListenerData *data, const SMESH_Hypothesis *hyp)
Do something on a certain event.
Static Public Member Functions
static _MeshOfSolid * GetSolidMesh (SMESH_Mesh *mesh, const TopoDS_Shape &solid, bool toCreate=false)
static void RemoveSolidMesh (SMESH_Mesh *mesh, const TopoDS_Shape &solid)
Detailed Description
Listener of events of 3D sub-meshes computed with viscous layers. It is used to store data computed by _ViscousBuilder for a sub-mesh and to delete the data as soon as it has been used.
Member Function Documentation
GetSolidMesh()
static _MeshOfSolid* VISCOUS_3D::_ViscousListener::GetSolidMesh (SMESH_Mesh * mesh, const TopoDS_Shape & solid, bool toCreate = false) static
References SMESH_subMesh::GetEventListenerData(), and SMESH_subMesh::SetEventListener().
ProcessEvent()
virtual void VISCOUS_3D::_ViscousListener::ProcessEvent (const int event, const int eventType, SMESH_subMesh * subMesh, SMESH_subMeshEventListenerData * data, const SMESH_Hypothesis * hyp) virtual
Do something on a certain event.
Parameters
event - algo_event or compute_event itself (of SMESH_subMesh)
eventType - ALGO_EVENT or COMPUTE_EVENT (of SMESH_subMesh)
subMesh - the submesh where the event occures
data - listener data stored in the subMesh
hyp - hypothesis, if eventType is algo_event
The base implementation (see SMESH_subMesh.cxx) translates CLEAN event to the subMeshes stored in the listener data. Also it sends SUBMESH_COMPUTED event in case of successful COMPUTE event.
Parameters
event - algo_event or compute_event itself
eventType - algo_event or compute_event
subMesh - the submesh where the event occures
data - listener data stored in the subMesh
hyp - hypothesis, if eventType is algo_event
The base implementation translates CLEAN event to the subMesh stored in listener data. Also it sends SUBMESH_COMPUTED event in case of successful COMPUTE event.
Reimplemented from SMESH_subMeshEventListener.
References SMESH_subMesh::CHECK_COMPUTE_STATE, SMESH_subMesh::COMPUTE_EVENT, and SMESH_subMesh::DeleteEventListener().
RemoveSolidMesh()
static void VISCOUS_3D::_ViscousListener::RemoveSolidMesh (SMESH_Mesh * mesh, const TopoDS_Shape & solid) static
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_ViscousLayers.cpp