FreeCAD: DrawSketchHandlerCarbonCopy Class Reference
DrawSketchHandlerCarbonCopy Class Reference
Public Member Functions
virtual void activated (ViewProviderSketch *sketchgui)
virtual void deactivated (ViewProviderSketch *sketchgui)
DrawSketchHandlerCarbonCopy ()
virtual void mouseMove (Base::Vector2d onSketchPos)
virtual bool onSelectionChanged (const Gui::SelectionChanges &msg)
virtual bool pressButton (Base::Vector2d onSketchPos)
virtual bool releaseButton (Base::Vector2d onSketchPos)
virtual ~DrawSketchHandlerCarbonCopy ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::none, bool createowncommand=true)
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual void quit (void)
virtual void registerPressedKey (bool, int)
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
void addCursorTail (std::vector< QPixmap > &pixmaps)
void applyCursor (QCursor &newCursor)
void applyCursor (void)
qreal devicePixelRatio ()
unsigned long getCrosshairColor ()
void setCrosshairColor ()
void setCrosshairCursor (const char *svgName)
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
Sets a cursor for 3D inventor view.
void setSvgCursor (const QString &svgName, int x, int y, const std::map< unsigned long, unsigned long > &colorMapping=std::map< unsigned long, unsigned long >())
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
void unsetCursor (void)
Protected Attributes inherited from SketcherGui::DrawSketchHandler
QCursor actCursor
QPixmap actCursorPixmap
QCursor oldCursor
ViewProviderSketch * sketchgui
Constructor & Destructor Documentation
DrawSketchHandlerCarbonCopy()
DrawSketchHandlerCarbonCopy::DrawSketchHandlerCarbonCopy ()
~DrawSketchHandlerCarbonCopy()
virtual DrawSketchHandlerCarbonCopy::~DrawSketchHandlerCarbonCopy () virtual
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
activated()
virtual void DrawSketchHandlerCarbonCopy::activated (ViewProviderSketch * sketchgui) virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References Gui::Application::activeDocument(), Gui::SelectionSingleton::addSelectionGate(), Gui::SelectionSingleton::clearSelection(), Gui::Document::getActiveView(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::Instance, Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), SketcherGui::ViewProviderSketch::setAxisPickStyle(), SketcherGui::DrawSketchHandler::setCrosshairCursor(), SketcherGui::DrawSketchHandler::sketchgui, and OfflineRenderingUtils::viewer().
deactivated()
virtual void DrawSketchHandlerCarbonCopy::deactivated (ViewProviderSketch * sketchgui) virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References SketcherGui::ViewProviderSketch::setAxisPickStyle(), and SketcherGui::DrawSketchHandler::sketchgui.
mouseMove()
virtual void DrawSketchHandlerCarbonCopy::mouseMove (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::applyCursor(), and Gui::Selection().
onSelectionChanged()
virtual bool DrawSketchHandlerCarbonCopy::onSelectionChanged (const Gui::SelectionChanges & msg) virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), Gui::SelectionChanges::AddSelection, Gui::SelectionSingleton::clearSelection(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Base::Console(), Base::ConsoleSingleton::Error(), SketcherGui::geometryCreationMode, Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::Document::getObject(), Gui::ViewProviderDocumentObject::getObject(), Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, Gui::Selection(), SketcherGui::DrawSketchHandler::sketchgui, and SketcherGui::tryAutoRecomputeIfNotSolve().
pressButton()
virtual bool DrawSketchHandlerCarbonCopy::pressButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
releaseButton()
virtual bool DrawSketchHandlerCarbonCopy::releaseButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/Gui/CommandCreateGeo.cpp