FreeCAD: Mesh::PropertyCurvatureList Class Reference
Mesh::PropertyCurvatureList Class Reference
The Curvature property class.
#include <MeshProperties.h>
Public Types
enum {
MeanCurvature = 0, GaussCurvature = 1, MaxCurvature = 2, MinCurvature = 3,
AbsCurvature = 4
}
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, PropStaticBegin = 21,
PropDynamic = 21, PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24,
PropTransient = 25, PropHidden = 26, PropOutput = 27, PropStaticEnd = 28,
User1 = 28, User2 = 29, User3 = 30, User4 = 31
}
Public Member Functions
std::vector< float > getCurvature (int tMode) const
int getSize (void) const
const std::vector< CurvatureInfo > & getValues (void) const
const CurvatureInfo & operator[] (const int idx) const
index operator
PropertyCurvatureList ()
void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
void RestoreDocFile (Base::Reader &reader)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
void SaveDocFile (Base::Writer &writer) const
This method is used to save large amounts of data to a binary file.
void set1Value (const int idx, const CurvatureInfo &value)
void setSize (int newSize)
void setValue (const CurvatureInfo &)
void setValues (const std::vector< CurvatureInfo > &)
void transformGeometry (const Base::Matrix4D &rclMat)
~PropertyCurvatureList ()
Python interface
PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
void setPyObject (PyObject *value)
App::Property * Copy (void) const
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const App::Property &from)
Paste the value from the property (mainly for Undo/Redo and transactions)
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
Public Member Functions inherited from App::PropertyLists
bool isOrderRelevant () const
void setOrderRelevant (bool on)
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
const char * getName (void) const
get the name of this property in the belonging container
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::PropertyListsBase
void clearTouchList ()
const std::set< int > & getTouchList () const
Additional Inherited Members
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Protected Member Functions inherited from App::PropertyListsBase
virtual void setPyValues (const std::vector< PyObject * > &vals, const std::vector< int > &indices)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Detailed Description
The Curvature property class.
Author
Werner Mayer
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
MeanCurvature
Mean curvature.
GaussCurvature
Gaussian curvature.
MaxCurvature
Maximum curvature.
MinCurvature
Minimum curvature.
AbsCurvature
Absolute curvature.
Constructor & Destructor Documentation
PropertyCurvatureList()
PropertyCurvatureList::PropertyCurvatureList ()
Referenced by Copy().
~PropertyCurvatureList()
PropertyCurvatureList::~PropertyCurvatureList ()
Member Function Documentation
Copy()
App::Property * PropertyCurvatureList::Copy (void) const virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References PropertyCurvatureList().
getCurvature()
std::vector< float > PropertyCurvatureList::getCurvature (int tMode) const
References AbsCurvature, GaussCurvature, getValues(), MaxCurvature, MeanCurvature, and MinCurvature.
Referenced by MeshGui::ViewProviderMeshCurvature::setVertexCurvatureMode().
getMemSize()
virtual unsigned int Mesh::PropertyCurvatureList::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
See also
Base::Persistence
Reimplemented from App::Property.
getPyObject()
PyObject * PropertyCurvatureList::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
getSize()
int Mesh::PropertyCurvatureList::getSize (void) const virtual
Implements App::PropertyListsBase.
Referenced by SaveDocFile(), transformGeometry(), and MeshGui::ViewProviderMeshCurvature::updateData().
getValues()
const std::vector<CurvatureInfo>& Mesh::PropertyCurvatureList::getValues (void) const
Referenced by getCurvature().
operator[]()
const CurvatureInfo& Mesh::PropertyCurvatureList::operator[] (const int idx) const
index operator
Referenced by transformGeometry().
Paste()
void PropertyCurvatureList::Paste (const App::Property & from) virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Restore()
void PropertyCurvatureList::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References Base::XMLReader::addFile(), Base::XMLReader::getAttribute(), and Base::XMLReader::readElement().
RestoreDocFile()
void PropertyCurvatureList::RestoreDocFile (Base::Reader &) virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Base::Persistence.
References setValues().
Save()
void PropertyCurvatureList::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References Base::Writer::addFile(), App::Property::getName(), Base::Writer::ind(), Base::Writer::isForceXML(), and Base::Writer::Stream().
SaveDocFile()
void PropertyCurvatureList::SaveDocFile (Base::Writer &) const virtual
This method is used to save large amounts of data to a binary file.
Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) << "\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
void PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Base::Persistence.
References getSize(), and Base::Writer::Stream().
set1Value()
void Mesh::PropertyCurvatureList::set1Value (const int idx, const CurvatureInfo & value)
setPyObject()
void PropertyCurvatureList::setPyObject (PyObject * value) virtual
Reimplemented from App::PropertyLists.
setSize()
void Mesh::PropertyCurvatureList::setSize (int newSize) virtual
Implements App::PropertyListsBase.
setValue()
void PropertyCurvatureList::setValue (const CurvatureInfo & lValue)
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
setValues()
void PropertyCurvatureList::setValues (const std::vector< CurvatureInfo > & lValues)
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Referenced by Mesh::Curvature::execute(), and RestoreDocFile().
transformGeometry()
void PropertyCurvatureList::transformGeometry (const Base::Matrix4D & rclMat)
References App::Property::aboutToSetValue(), Mesh::CurvatureInfo::cMaxCurvDir, Mesh::CurvatureInfo::cMinCurvDir, getSize(), App::Property::hasSetValue(), operator[](), and Base::Matrix4D::setToUnity().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/MeshProperties.h
Sources/FreeCAD/src/Mod/Mesh/App/MeshProperties.cpp