FreeCAD: Mesh::MeshPy Class Reference
Mesh::MeshPy Class Reference
The python export class for MeshObject.
#include <MeshPy.h>
Public Types
typedef MeshObject * PointerType
Public Types inherited from Data::ComplexGeoDataPy
typedef ComplexGeoData * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
MeshPy (MeshObject *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Data::ComplexGeoDataPy
ComplexGeoDataPy (ComplexGeoData *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getFacesFromSubelement (PyObject *args)
implementer for the getFacesFromSubelement() method
Py::Object getBoundBox (void) const
getter for the BoundBox attribute
Py::Object getPlacement (void) const
getter for the Placement attribute
void setPlacement (Py::Object arg)
setter for the Placement attribute
Py::Object getMatrix (void) const
getter for the Matrix attribute
void setMatrix (Py::Object arg)
setter for the Matrix attribute
Py::Int getTag (void) const
getter for the Tag attribute
void setTag (Py::Int arg)
setter for the Tag attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ComplexGeoData * getComplexGeoDataPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Data::ComplexGeoDataPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_getFacesFromSubelement (PyObject *self, PyObject *args)
callback for the getFacesFromSubelement() method
static PyObject * staticCallback_getBoundBox (PyObject *self, void *closure)
getter callback for the BoundBox attribute
static int staticCallback_setBoundBox (PyObject *self, PyObject *value, void *closure)
setter callback for the BoundBox attribute
static PyObject * staticCallback_getPlacement (PyObject *self, void *closure)
getter callback for the Placement attribute
static int staticCallback_setPlacement (PyObject *self, PyObject *value, void *closure)
setter callback for the Placement attribute
static PyObject * staticCallback_getMatrix (PyObject *self, void *closure)
getter callback for the Matrix attribute
static int staticCallback_setMatrix (PyObject *self, PyObject *value, void *closure)
setter callback for the Matrix attribute
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of MeshPy.
static PyMethodDef Methods []
Methods structure of MeshPy.
static PyTypeObject Type
Type structure of MeshPy.
Static Public Attributes inherited from Data::ComplexGeoDataPy
static PyGetSetDef GetterSetter []
Attribute structure of ComplexGeoDataPy.
static PyMethodDef Methods []
Methods structure of ComplexGeoDataPy.
static PyTypeObject Type
Type structure of ComplexGeoDataPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~MeshPy ()
Protected Member Functions inherited from Data::ComplexGeoDataPy
~ComplexGeoDataPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * read (PyObject *args, PyObject *kwd)
implementer for the read() method
PyObject * write (PyObject *args, PyObject *kwd)
implementer for the write() method
PyObject * writeInventor (PyObject *args)
implementer for the writeInventor() method
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * offset (PyObject *args)
implementer for the offset() method
PyObject * offsetSpecial (PyObject *args)
implementer for the offsetSpecial() method
PyObject * crossSections (PyObject *args)
implementer for the crossSections() method
PyObject * unite (PyObject *args)
implementer for the unite() method
PyObject * intersect (PyObject *args)
implementer for the intersect() method
PyObject * difference (PyObject *args)
implementer for the difference() method
PyObject * inner (PyObject *args)
implementer for the inner() method
PyObject * outer (PyObject *args)
implementer for the outer() method
PyObject * coarsen (PyObject *args)
implementer for the coarsen() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * transformToEigen (PyObject *args)
implementer for the transformToEigen() method
PyObject * getEigenSystem (PyObject *args)
implementer for the getEigenSystem() method
PyObject * addFacet (PyObject *args)
implementer for the addFacet() method
PyObject * addFacets (PyObject *args)
implementer for the addFacets() method
PyObject * removeFacets (PyObject *args)
implementer for the removeFacets() method
PyObject * removeNeedles (PyObject *args)
implementer for the removeNeedles() method
PyObject * removeFullBoundaryFacets (PyObject *args)
implementer for the removeFullBoundaryFacets() method
PyObject * getInternalFacets (PyObject *args)
implementer for the getInternalFacets() method
PyObject * rebuildNeighbourHood (PyObject *args)
implementer for the rebuildNeighbourHood() method
PyObject * addMesh (PyObject *args)
implementer for the addMesh() method
PyObject * setPoint (PyObject *args)
implementer for the setPoint() method
PyObject * getPointNormals (PyObject *args)
implementer for the getPointNormals() method
PyObject * countSegments (PyObject *args)
implementer for the countSegments() method
PyObject * getSegment (PyObject *args)
implementer for the getSegment() method
PyObject * getSeparateComponents (PyObject *args)
implementer for the getSeparateComponents() method
PyObject * getFacetSelection (PyObject *args)
implementer for the getFacetSelection() method
PyObject * getPointSelection (PyObject *args)
implementer for the getPointSelection() method
PyObject * meshFromSegment (PyObject *args)
implementer for the meshFromSegment() method
PyObject * clear (PyObject *args)
implementer for the clear() method
PyObject * isSolid (PyObject *args)
implementer for the isSolid() method
PyObject * hasNonManifolds (PyObject *args)
implementer for the hasNonManifolds() method
PyObject * removeNonManifolds (PyObject *args)
implementer for the removeNonManifolds() method
PyObject * removeNonManifoldPoints (PyObject *args)
implementer for the removeNonManifoldPoints() method
PyObject * hasSelfIntersections (PyObject *args)
implementer for the hasSelfIntersections() method
PyObject * getSelfIntersections (PyObject *args)
implementer for the getSelfIntersections() method
PyObject * fixSelfIntersections (PyObject *args)
implementer for the fixSelfIntersections() method
PyObject * removeFoldsOnSurface (PyObject *args)
implementer for the removeFoldsOnSurface() method
PyObject * hasNonUniformOrientedFacets (PyObject *args)
implementer for the hasNonUniformOrientedFacets() method
PyObject * countNonUniformOrientedFacets (PyObject *args)
implementer for the countNonUniformOrientedFacets() method
PyObject * getNonUniformOrientedFacets (PyObject *args)
implementer for the getNonUniformOrientedFacets() method
PyObject * hasInvalidPoints (PyObject *args)
implementer for the hasInvalidPoints() method
PyObject * removeInvalidPoints (PyObject *args)
implementer for the removeInvalidPoints() method
PyObject * countComponents (PyObject *args)
implementer for the countComponents() method
PyObject * removeComponents (PyObject *args)
implementer for the removeComponents() method
PyObject * fixIndices (PyObject *args)
implementer for the fixIndices() method
PyObject * fixCaps (PyObject *args)
implementer for the fixCaps() method
PyObject * fixDeformations (PyObject *args)
implementer for the fixDeformations() method
PyObject * fixDegenerations (PyObject *args)
implementer for the fixDegenerations() method
PyObject * removeDuplicatedPoints (PyObject *args)
implementer for the removeDuplicatedPoints() method
PyObject * removeDuplicatedFacets (PyObject *args)
implementer for the removeDuplicatedFacets() method
PyObject * refine (PyObject *args)
implementer for the refine() method
PyObject * splitEdges (PyObject *args)
implementer for the splitEdges() method
PyObject * splitEdge (PyObject *args)
implementer for the splitEdge() method
PyObject * splitFacet (PyObject *args)
implementer for the splitFacet() method
PyObject * swapEdge (PyObject *args)
implementer for the swapEdge() method
PyObject * collapseEdge (PyObject *args)
implementer for the collapseEdge() method
PyObject * collapseFacet (PyObject *args)
implementer for the collapseFacet() method
PyObject * collapseFacets (PyObject *args)
implementer for the collapseFacets() method
PyObject * insertVertex (PyObject *args)
implementer for the insertVertex() method
PyObject * snapVertex (PyObject *args)
implementer for the snapVertex() method
PyObject * printInfo (PyObject *args)
implementer for the printInfo() method
PyObject * foraminate (PyObject *args)
implementer for the foraminate() method
PyObject * cut (PyObject *args)
implementer for the cut() method
PyObject * trim (PyObject *args)
implementer for the trim() method
PyObject * harmonizeNormals (PyObject *args)
implementer for the harmonizeNormals() method
PyObject * flipNormals (PyObject *args)
implementer for the flipNormals() method
PyObject * fillupHoles (PyObject *args)
implementer for the fillupHoles() method
PyObject * smooth (PyObject *args, PyObject *kwd)
implementer for the smooth() method
PyObject * decimate (PyObject *args)
implementer for the decimate() method
PyObject * mergeFacets (PyObject *args)
implementer for the mergeFacets() method
PyObject * optimizeTopology (PyObject *args)
implementer for the optimizeTopology() method
PyObject * optimizeEdges (PyObject *args)
implementer for the optimizeEdges() method
PyObject * nearestFacetOnRay (PyObject *args)
implementer for the nearestFacetOnRay() method
PyObject * getPlanarSegments (PyObject *args)
implementer for the getPlanarSegments() method
PyObject * getSegmentsOfType (PyObject *args)
implementer for the getSegmentsOfType() method
PyObject * getSegmentsByCurvature (PyObject *args)
implementer for the getSegmentsByCurvature() method
PyObject * getCurvaturePerVertex (PyObject *args)
implementer for the getCurvaturePerVertex() method
static PyObject * staticCallback_read (PyObject *self, PyObject *args, PyObject *kwd)
callback for the read() method
static PyObject * staticCallback_write (PyObject *self, PyObject *args, PyObject *kwd)
callback for the write() method
static PyObject * staticCallback_writeInventor (PyObject *self, PyObject *args)
callback for the writeInventor() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_offset (PyObject *self, PyObject *args)
callback for the offset() method
static PyObject * staticCallback_offsetSpecial (PyObject *self, PyObject *args)
callback for the offsetSpecial() method
static PyObject * staticCallback_crossSections (PyObject *self, PyObject *args)
callback for the crossSections() method
static PyObject * staticCallback_unite (PyObject *self, PyObject *args)
callback for the unite() method
static PyObject * staticCallback_intersect (PyObject *self, PyObject *args)
callback for the intersect() method
static PyObject * staticCallback_difference (PyObject *self, PyObject *args)
callback for the difference() method
static PyObject * staticCallback_inner (PyObject *self, PyObject *args)
callback for the inner() method
static PyObject * staticCallback_outer (PyObject *self, PyObject *args)
callback for the outer() method
static PyObject * staticCallback_coarsen (PyObject *self, PyObject *args)
callback for the coarsen() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_transformToEigen (PyObject *self, PyObject *args)
callback for the transformToEigen() method
static PyObject * staticCallback_getEigenSystem (PyObject *self, PyObject *args)
callback for the getEigenSystem() method
static PyObject * staticCallback_addFacet (PyObject *self, PyObject *args)
callback for the addFacet() method
static PyObject * staticCallback_addFacets (PyObject *self, PyObject *args)
callback for the addFacets() method
static PyObject * staticCallback_removeFacets (PyObject *self, PyObject *args)
callback for the removeFacets() method
static PyObject * staticCallback_removeNeedles (PyObject *self, PyObject *args)
callback for the removeNeedles() method
static PyObject * staticCallback_removeFullBoundaryFacets (PyObject *self, PyObject *args)
callback for the removeFullBoundaryFacets() method
static PyObject * staticCallback_getInternalFacets (PyObject *self, PyObject *args)
callback for the getInternalFacets() method
static PyObject * staticCallback_rebuildNeighbourHood (PyObject *self, PyObject *args)
callback for the rebuildNeighbourHood() method
static PyObject * staticCallback_addMesh (PyObject *self, PyObject *args)
callback for the addMesh() method
static PyObject * staticCallback_setPoint (PyObject *self, PyObject *args)
callback for the setPoint() method
static PyObject * staticCallback_getPointNormals (PyObject *self, PyObject *args)
callback for the getPointNormals() method
static PyObject * staticCallback_countSegments (PyObject *self, PyObject *args)
callback for the countSegments() method
static PyObject * staticCallback_getSegment (PyObject *self, PyObject *args)
callback for the getSegment() method
static PyObject * staticCallback_getSeparateComponents (PyObject *self, PyObject *args)
callback for the getSeparateComponents() method
static PyObject * staticCallback_getFacetSelection (PyObject *self, PyObject *args)
callback for the getFacetSelection() method
static PyObject * staticCallback_getPointSelection (PyObject *self, PyObject *args)
callback for the getPointSelection() method
static PyObject * staticCallback_meshFromSegment (PyObject *self, PyObject *args)
callback for the meshFromSegment() method
static PyObject * staticCallback_clear (PyObject *self, PyObject *args)
callback for the clear() method
static PyObject * staticCallback_isSolid (PyObject *self, PyObject *args)
callback for the isSolid() method
static PyObject * staticCallback_hasNonManifolds (PyObject *self, PyObject *args)
callback for the hasNonManifolds() method
static PyObject * staticCallback_removeNonManifolds (PyObject *self, PyObject *args)
callback for the removeNonManifolds() method
static PyObject * staticCallback_removeNonManifoldPoints (PyObject *self, PyObject *args)
callback for the removeNonManifoldPoints() method
static PyObject * staticCallback_hasSelfIntersections (PyObject *self, PyObject *args)
callback for the hasSelfIntersections() method
static PyObject * staticCallback_getSelfIntersections (PyObject *self, PyObject *args)
callback for the getSelfIntersections() method
static PyObject * staticCallback_fixSelfIntersections (PyObject *self, PyObject *args)
callback for the fixSelfIntersections() method
static PyObject * staticCallback_removeFoldsOnSurface (PyObject *self, PyObject *args)
callback for the removeFoldsOnSurface() method
static PyObject * staticCallback_hasNonUniformOrientedFacets (PyObject *self, PyObject *args)
callback for the hasNonUniformOrientedFacets() method
static PyObject * staticCallback_countNonUniformOrientedFacets (PyObject *self, PyObject *args)
callback for the countNonUniformOrientedFacets() method
static PyObject * staticCallback_getNonUniformOrientedFacets (PyObject *self, PyObject *args)
callback for the getNonUniformOrientedFacets() method
static PyObject * staticCallback_hasInvalidPoints (PyObject *self, PyObject *args)
callback for the hasInvalidPoints() method
static PyObject * staticCallback_removeInvalidPoints (PyObject *self, PyObject *args)
callback for the removeInvalidPoints() method
static PyObject * staticCallback_countComponents (PyObject *self, PyObject *args)
callback for the countComponents() method
static PyObject * staticCallback_removeComponents (PyObject *self, PyObject *args)
callback for the removeComponents() method
static PyObject * staticCallback_fixIndices (PyObject *self, PyObject *args)
callback for the fixIndices() method
static PyObject * staticCallback_fixCaps (PyObject *self, PyObject *args)
callback for the fixCaps() method
static PyObject * staticCallback_fixDeformations (PyObject *self, PyObject *args)
callback for the fixDeformations() method
static PyObject * staticCallback_fixDegenerations (PyObject *self, PyObject *args)
callback for the fixDegenerations() method
static PyObject * staticCallback_removeDuplicatedPoints (PyObject *self, PyObject *args)
callback for the removeDuplicatedPoints() method
static PyObject * staticCallback_removeDuplicatedFacets (PyObject *self, PyObject *args)
callback for the removeDuplicatedFacets() method
static PyObject * staticCallback_refine (PyObject *self, PyObject *args)
callback for the refine() method
static PyObject * staticCallback_splitEdges (PyObject *self, PyObject *args)
callback for the splitEdges() method
static PyObject * staticCallback_splitEdge (PyObject *self, PyObject *args)
callback for the splitEdge() method
static PyObject * staticCallback_splitFacet (PyObject *self, PyObject *args)
callback for the splitFacet() method
static PyObject * staticCallback_swapEdge (PyObject *self, PyObject *args)
callback for the swapEdge() method
static PyObject * staticCallback_collapseEdge (PyObject *self, PyObject *args)
callback for the collapseEdge() method
static PyObject * staticCallback_collapseFacet (PyObject *self, PyObject *args)
callback for the collapseFacet() method
static PyObject * staticCallback_collapseFacets (PyObject *self, PyObject *args)
callback for the collapseFacets() method
static PyObject * staticCallback_insertVertex (PyObject *self, PyObject *args)
callback for the insertVertex() method
static PyObject * staticCallback_snapVertex (PyObject *self, PyObject *args)
callback for the snapVertex() method
static PyObject * staticCallback_printInfo (PyObject *self, PyObject *args)
callback for the printInfo() method
static PyObject * staticCallback_foraminate (PyObject *self, PyObject *args)
callback for the foraminate() method
static PyObject * staticCallback_cut (PyObject *self, PyObject *args)
callback for the cut() method
static PyObject * staticCallback_trim (PyObject *self, PyObject *args)
callback for the trim() method
static PyObject * staticCallback_harmonizeNormals (PyObject *self, PyObject *args)
callback for the harmonizeNormals() method
static PyObject * staticCallback_flipNormals (PyObject *self, PyObject *args)
callback for the flipNormals() method
static PyObject * staticCallback_fillupHoles (PyObject *self, PyObject *args)
callback for the fillupHoles() method
static PyObject * staticCallback_smooth (PyObject *self, PyObject *args, PyObject *kwd)
callback for the smooth() method
static PyObject * staticCallback_decimate (PyObject *self, PyObject *args)
callback for the decimate() method
static PyObject * staticCallback_mergeFacets (PyObject *self, PyObject *args)
callback for the mergeFacets() method
static PyObject * staticCallback_optimizeTopology (PyObject *self, PyObject *args)
callback for the optimizeTopology() method
static PyObject * staticCallback_optimizeEdges (PyObject *self, PyObject *args)
callback for the optimizeEdges() method
static PyObject * staticCallback_nearestFacetOnRay (PyObject *self, PyObject *args)
callback for the nearestFacetOnRay() method
static PyObject * staticCallback_getPlanarSegments (PyObject *self, PyObject *args)
callback for the getPlanarSegments() method
static PyObject * staticCallback_getSegmentsOfType (PyObject *self, PyObject *args)
callback for the getSegmentsOfType() method
static PyObject * staticCallback_getSegmentsByCurvature (PyObject *self, PyObject *args)
callback for the getSegmentsByCurvature() method
static PyObject * staticCallback_getCurvaturePerVertex (PyObject *self, PyObject *args)
callback for the getCurvaturePerVertex() method
callbacks and implementers for the python object attributes
Py::List getPoints (void) const
getter for the Points attribute
Py::Long getCountPoints (void) const
getter for the CountPoints attribute
Py::Long getCountEdges (void) const
getter for the CountEdges attribute
Py::List getFacets (void) const
getter for the Facets attribute
Py::Long getCountFacets (void) const
getter for the CountFacets attribute
Py::Tuple getTopology (void) const
getter for the Topology attribute
Py::Float getArea (void) const
getter for the Area attribute
Py::Float getVolume (void) const
getter for the Volume attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
MeshObject * getMeshObjectPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getPoints (PyObject *self, void *closure)
getter callback for the Points attribute
static int staticCallback_setPoints (PyObject *self, PyObject *value, void *closure)
setter callback for the Points attribute
static PyObject * staticCallback_getCountPoints (PyObject *self, void *closure)
getter callback for the CountPoints attribute
static int staticCallback_setCountPoints (PyObject *self, PyObject *value, void *closure)
setter callback for the CountPoints attribute
static PyObject * staticCallback_getCountEdges (PyObject *self, void *closure)
getter callback for the CountEdges attribute
static int staticCallback_setCountEdges (PyObject *self, PyObject *value, void *closure)
setter callback for the CountEdges attribute
static PyObject * staticCallback_getFacets (PyObject *self, void *closure)
getter callback for the Facets attribute
static int staticCallback_setFacets (PyObject *self, PyObject *value, void *closure)
setter callback for the Facets attribute
static PyObject * staticCallback_getCountFacets (PyObject *self, void *closure)
getter callback for the CountFacets attribute
static int staticCallback_setCountFacets (PyObject *self, PyObject *value, void *closure)
setter callback for the CountFacets attribute
static PyObject * staticCallback_getTopology (PyObject *self, void *closure)
getter callback for the Topology attribute
static int staticCallback_setTopology (PyObject *self, PyObject *value, void *closure)
setter callback for the Topology attribute
static PyObject * staticCallback_getArea (PyObject *self, void *closure)
getter callback for the Area attribute
static int staticCallback_setArea (PyObject *self, PyObject *value, void *closure)
setter callback for the Area attribute
static PyObject * staticCallback_getVolume (PyObject *self, void *closure)
getter callback for the Volume attribute
static int staticCallback_setVolume (PyObject *self, PyObject *value, void *closure)
setter callback for the Volume attribute
additional declarations and methods for the wrapper class
class PropertyMeshKernel
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for MeshObject.
Member Typedef Documentation
PointerType
typedef MeshObject* Mesh::MeshPy::PointerType
Constructor & Destructor Documentation
~MeshPy()
MeshPy::~MeshPy () protected
MeshPy()
MeshPy::MeshPy (MeshObject * pcObject, PyTypeObject * T = &Type)
Referenced by copy(), difference(), getSeparateComponents(), inner(), intersect(), meshFromSegment(), outer(), PyMake(), and unite().
Member Function Documentation
addFacet()
PyObject * MeshPy::addFacet (PyObject * args)
implementer for the addFacet() method
References Mesh::MeshObject::addFacet(), Base::BaseExceptionFreeCADError, getMeshObjectPtr(), Base::VectorPy::Type, Mesh::FacetPy::Type, draftgeoutils.general::v1(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by staticCallback_addFacet().
addFacets()
PyObject * MeshPy::addFacets (PyObject * args)
implementer for the addFacets() method
References Mesh::MeshObject::addFacets(), Base::BaseExceptionFreeCADError, MeshCore::MeshGeomFacet::CalcNormal(), getMeshObjectPtr(), PyType_Object::o, Base::VectorPy::Type, and Mesh::FacetPy::Type.
Referenced by PyInit(), and staticCallback_addFacets().
addMesh()
PyObject * MeshPy::addMesh (PyObject * args)
implementer for the addMesh() method
References Mesh::MeshObject::addMesh(), getMeshObjectPtr(), and Type.
Referenced by staticCallback_addMesh().
clear()
PyObject * MeshPy::clear (PyObject * args)
implementer for the clear() method
References Mesh::MeshObject::clear(), and getMeshObjectPtr().
Referenced by staticCallback_clear().
coarsen()
PyObject * MeshPy::coarsen (PyObject * args)
implementer for the coarsen() method
Referenced by staticCallback_coarsen().
collapseEdge()
PyObject * MeshPy::collapseEdge (PyObject * args)
implementer for the collapseEdge() method
References Mesh::MeshObject::collapseEdge(), MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::GetFacets(), Mesh::MeshObject::getKernel(), and getMeshObjectPtr().
Referenced by staticCallback_collapseEdge().
collapseFacet()
PyObject * MeshPy::collapseFacet (PyObject * args)
implementer for the collapseFacet() method
References Mesh::MeshObject::collapseFacet(), and getMeshObjectPtr().
Referenced by staticCallback_collapseFacet().
collapseFacets()
PyObject * MeshPy::collapseFacets (PyObject * args)
implementer for the collapseFacets() method
References Mesh::MeshObject::collapseFacets(), and getMeshObjectPtr().
Referenced by staticCallback_collapseFacets().
copy()
PyObject * MeshPy::copy (PyObject * args)
implementer for the copy() method
References getMeshObjectPtr(), and MeshPy().
Referenced by staticCallback_copy().
countComponents()
PyObject * MeshPy::countComponents (PyObject * args)
implementer for the countComponents() method
References Mesh::MeshObject::countComponents(), and getMeshObjectPtr().
Referenced by staticCallback_countComponents().
countNonUniformOrientedFacets()
PyObject * MeshPy::countNonUniformOrientedFacets (PyObject * args)
implementer for the countNonUniformOrientedFacets() method
References Mesh::MeshObject::countNonUniformOrientedFacets(), and getMeshObjectPtr().
Referenced by staticCallback_countNonUniformOrientedFacets().
countSegments()
PyObject * MeshPy::countSegments (PyObject * args)
implementer for the countSegments() method
References Mesh::MeshObject::countSegments(), and getMeshObjectPtr().
Referenced by staticCallback_countSegments().
crossSections()
PyObject * MeshPy::crossSections (PyObject * args)
implementer for the crossSections() method
References Mesh::MeshObject::crossSections(), getMeshObjectPtr(), PyType_Object::o, and Base::VectorPy::Type.
Referenced by staticCallback_crossSections().
cut()
PyObject * MeshPy::cut (PyObject * args)
implementer for the cut() method
References Base::Polygon2d::Add(), Mesh::MeshObject::cut(), getMeshObjectPtr(), MeshCore::AbstractPolygonTriangulator::GetTransformToFitPlane(), Base::Matrix4D::inverseOrthogonal(), MeshCore::AbstractPolygonTriangulator::ProjectToFitPlane(), and MeshCore::AbstractPolygonTriangulator::SetPolygon().
Referenced by staticCallback_cut().
decimate()
PyObject * MeshPy::decimate (PyObject * args)
implementer for the decimate() method
References Mesh::MeshObject::decimate(), and getMeshObjectPtr().
Referenced by staticCallback_decimate().
difference()
PyObject * MeshPy::difference (PyObject * args)
implementer for the difference() method
References getMeshObjectPtr(), MeshPy(), Mesh::MeshObject::subtract(), and Type.
Referenced by staticCallback_difference().
fillupHoles()
PyObject * MeshPy::fillupHoles (PyObject * args)
implementer for the fillupHoles() method
References Base::BaseExceptionFreeCADError, Mesh::MeshObject::fillupHoles(), getMeshObjectPtr(), and MeshCore::AbstractPolygonTriangulator::SetVerifier().
Referenced by staticCallback_fillupHoles().
fixCaps()
PyObject * MeshPy::fixCaps (PyObject * args)
implementer for the fixCaps() method
References getMeshObjectPtr(), and Mesh::MeshObject::validateCaps().
Referenced by staticCallback_fixCaps().
fixDeformations()
PyObject * MeshPy::fixDeformations (PyObject * args)
implementer for the fixDeformations() method
References getMeshObjectPtr(), and Mesh::MeshObject::validateDeformations().
Referenced by staticCallback_fixDeformations().
fixDegenerations()
PyObject * MeshPy::fixDegenerations (PyObject * args)
implementer for the fixDegenerations() method
References getMeshObjectPtr(), and Mesh::MeshObject::validateDegenerations().
Referenced by staticCallback_fixDegenerations().
fixIndices()
PyObject * MeshPy::fixIndices (PyObject * args)
implementer for the fixIndices() method
References getMeshObjectPtr(), and Mesh::MeshObject::validateIndices().
Referenced by staticCallback_fixIndices().
fixSelfIntersections()
PyObject * MeshPy::fixSelfIntersections (PyObject * args)
implementer for the fixSelfIntersections() method
References Base::BaseExceptionFreeCADError, getMeshObjectPtr(), and Mesh::MeshObject::removeSelfIntersections().
Referenced by staticCallback_fixSelfIntersections().
flipNormals()
PyObject * MeshPy::flipNormals (PyObject * args)
implementer for the flipNormals() method
References Mesh::MeshObject::flipNormals(), and getMeshObjectPtr().
Referenced by staticCallback_flipNormals().
foraminate()
PyObject * MeshPy::foraminate (PyObject * args)
implementer for the foraminate() method
References MeshCore::MeshFacetIterator::Begin(), MeshCore::MeshGeomFacet::Foraminate(), getMeshObjectPtr(), MeshCore::MeshFacetIterator::More(), and MeshCore::MeshFacetIterator::Next().
Referenced by staticCallback_foraminate().
getArea()
Py::Float MeshPy::getArea (void) const
getter for the Area attribute
References getMeshObjectPtr().
Referenced by staticCallback_getArea().
getCountEdges()
Py::Long MeshPy::getCountEdges (void) const
getter for the CountEdges attribute
References getMeshObjectPtr().
Referenced by staticCallback_getCountEdges().
getCountFacets()
Py::Long MeshPy::getCountFacets (void) const
getter for the CountFacets attribute
References getMeshObjectPtr().
Referenced by staticCallback_getCountFacets().
getCountPoints()
Py::Long MeshPy::getCountPoints (void) const
getter for the CountPoints attribute
References getMeshObjectPtr().
Referenced by staticCallback_getCountPoints().
getCurvaturePerVertex()
PyObject * MeshPy::getCurvaturePerVertex (PyObject * args)
implementer for the getCurvaturePerVertex() method
References MeshCore::MeshCurvature::ComputePerVertex(), MeshCore::MeshCurvature::GetCurvature(), Mesh::MeshObject::getKernel(), and getMeshObjectPtr().
Referenced by staticCallback_getCurvaturePerVertex().
getCustomAttributes()
PyObject * MeshPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getEigenSystem()
PyObject * MeshPy::getEigenSystem (PyObject * args)
implementer for the getEigenSystem() method
References Mesh::MeshObject::getEigenSystem(), getMeshObjectPtr(), PyType_Object::t, and draftgeoutils.general::vec().
Referenced by staticCallback_getEigenSystem().
getFacets()
Py::List MeshPy::getFacets (void) const
getter for the Facets attribute
References getMeshObjectPtr().
Referenced by staticCallback_getFacets().
getFacetSelection()
PyObject * MeshPy::getFacetSelection (PyObject * args)
implementer for the getFacetSelection() method
References Mesh::MeshObject::getFacetsFromSelection(), and getMeshObjectPtr().
Referenced by staticCallback_getFacetSelection().
getInternalFacets()
PyObject * MeshPy::getInternalFacets (PyObject * args)
implementer for the getInternalFacets() method
References MeshCore::MeshEvalInternalFacets::Evaluate(), MeshCore::MeshEvalInternalFacets::GetIndices(), Mesh::MeshObject::getKernel(), and getMeshObjectPtr().
Referenced by staticCallback_getInternalFacets().
getMeshObjectPtr()
MeshObject * MeshPy::getMeshObjectPtr (void) const
getter for the object handled by this class
Referenced by addFacet(), addFacets(), addMesh(), clear(), collapseEdge(), collapseFacet(), collapseFacets(), copy(), countComponents(), countNonUniformOrientedFacets(), countSegments(), crossSections(), cut(), decimate(), difference(), fillupHoles(), fixCaps(), fixDeformations(), fixDegenerations(), fixIndices(), fixSelfIntersections(), flipNormals(), foraminate(), getArea(), getCountEdges(), getCountFacets(), getCountPoints(), getCurvaturePerVertex(), getEigenSystem(), getFacets(), getFacetSelection(), getInternalFacets(), getNonUniformOrientedFacets(), getPlanarSegments(), getPointNormals(), getPoints(), getPointSelection(), getSegment(), getSegmentsByCurvature(), getSegmentsOfType(), getSelfIntersections(), getSeparateComponents(), getTopology(), getVolume(), harmonizeNormals(), hasInvalidPoints(), hasNonManifolds(), hasNonUniformOrientedFacets(), hasSelfIntersections(), inner(), insertVertex(), intersect(), isSolid(), mergeFacets(), meshFromSegment(), nearestFacetOnRay(), offset(), offsetSpecial(), optimizeEdges(), optimizeTopology(), outer(), printInfo(), PyInit(), read(), rebuildNeighbourHood(), refine(), removeComponents(), removeDuplicatedFacets(), removeDuplicatedPoints(), removeFacets(), removeFoldsOnSurface(), removeFullBoundaryFacets(), removeInvalidPoints(), removeNeedles(), removeNonManifoldPoints(), removeNonManifolds(), rotate(), setPoint(), smooth(), snapVertex(), splitEdge(), splitEdges(), splitFacet(), swapEdge(), transform(), transformToEigen(), translate(), trim(), unite(), write(), and writeInventor().
getNonUniformOrientedFacets()
PyObject * MeshPy::getNonUniformOrientedFacets (PyObject * args)
implementer for the getNonUniformOrientedFacets() method
References MeshCore::MeshEvalOrientation::GetIndices(), Mesh::MeshObject::getKernel(), and getMeshObjectPtr().
Referenced by staticCallback_getNonUniformOrientedFacets().
getPlanarSegments()
PyObject * MeshPy::getPlanarSegments (PyObject * args)
implementer for the getPlanarSegments() method
References getMeshObjectPtr(), and Mesh::MeshObject::PLANE.
Referenced by staticCallback_getPlanarSegments().
getPointNormals()
PyObject * MeshPy::getPointNormals (PyObject * args)
implementer for the getPointNormals() method
References getMeshObjectPtr(), and Mesh::MeshObject::getPointNormals().
Referenced by staticCallback_getPointNormals().
getPoints()
Py::List MeshPy::getPoints (void) const
getter for the Points attribute
References getMeshObjectPtr().
Referenced by staticCallback_getPoints().
getPointSelection()
PyObject * MeshPy::getPointSelection (PyObject * args)
implementer for the getPointSelection() method
References getMeshObjectPtr(), and Mesh::MeshObject::getPointsFromSelection().
Referenced by staticCallback_getPointSelection().
getSegment()
PyObject * MeshPy::getSegment (PyObject * args)
implementer for the getSegment() method
References Mesh::MeshObject::countSegments(), Mesh::Segment::getIndices(), getMeshObjectPtr(), and Mesh::MeshObject::getSegment().
Referenced by staticCallback_getSegment().
getSegmentsByCurvature()
PyObject * MeshPy::getSegmentsByCurvature (PyObject * args)
implementer for the getSegmentsByCurvature() method
References MeshCore::MeshCurvature::ComputePerVertex(), MeshCore::MeshSegmentAlgorithm::FindSegments(), MeshCore::MeshCurvature::GetCurvature(), Mesh::MeshObject::getKernel(), getMeshObjectPtr(), and PyType_Object::t.
Referenced by staticCallback_getSegmentsByCurvature().
getSegmentsOfType()
PyObject * MeshPy::getSegmentsOfType (PyObject * args)
implementer for the getSegmentsOfType() method
References Mesh::MeshObject::CYLINDER, getMeshObjectPtr(), Mesh::MeshObject::PLANE, and Mesh::MeshObject::SPHERE.
Referenced by staticCallback_getSegmentsOfType().
getSelfIntersections()
PyObject * MeshPy::getSelfIntersections (PyObject * args)
implementer for the getSelfIntersections() method
References MeshCore::MeshEvalSelfIntersection::GetIntersections(), and getMeshObjectPtr().
Referenced by staticCallback_getSelfIntersections().
getSeparateComponents()
PyObject * MeshPy::getSeparateComponents (PyObject * args)
implementer for the getSeparateComponents() method
References Mesh::MeshObject::getComponents(), getMeshObjectPtr(), Mesh::MeshObject::meshFromSegment(), and MeshPy().
Referenced by staticCallback_getSeparateComponents().
getTopology()
Py::Tuple MeshPy::getTopology (void) const
getter for the Topology attribute
References Mesh::MeshObject::getFaces(), and getMeshObjectPtr().
Referenced by staticCallback_getTopology().
GetType()
virtual PyTypeObject* Mesh::MeshPy::GetType (void) virtual
Reimplemented from Data::ComplexGeoDataPy.
getVolume()
Py::Float MeshPy::getVolume (void) const
getter for the Volume attribute
References getMeshObjectPtr().
Referenced by staticCallback_getVolume().
harmonizeNormals()
PyObject * MeshPy::harmonizeNormals (PyObject * args)
implementer for the harmonizeNormals() method
References getMeshObjectPtr(), and Mesh::MeshObject::harmonizeNormals().
Referenced by staticCallback_harmonizeNormals().
hasInvalidPoints()
PyObject * MeshPy::hasInvalidPoints (PyObject * args)
implementer for the hasInvalidPoints() method
References getMeshObjectPtr(), and Mesh::MeshObject::hasInvalidPoints().
Referenced by staticCallback_hasInvalidPoints().
hasNonManifolds()
PyObject * MeshPy::hasNonManifolds (PyObject * args)
implementer for the hasNonManifolds() method
References getMeshObjectPtr(), and Mesh::MeshObject::hasNonManifolds().
Referenced by staticCallback_hasNonManifolds().
hasNonUniformOrientedFacets()
PyObject * MeshPy::hasNonUniformOrientedFacets (PyObject * args)
implementer for the hasNonUniformOrientedFacets() method
References Mesh::MeshObject::countNonUniformOrientedFacets(), and getMeshObjectPtr().
Referenced by staticCallback_hasNonUniformOrientedFacets().
hasSelfIntersections()
PyObject * MeshPy::hasSelfIntersections (PyObject * args)
implementer for the hasSelfIntersections() method
References getMeshObjectPtr(), and Mesh::MeshObject::hasSelfIntersections().
Referenced by staticCallback_hasSelfIntersections().
inner()
PyObject * MeshPy::inner (PyObject * args)
implementer for the inner() method
References getMeshObjectPtr(), Mesh::MeshObject::inner(), MeshPy(), and Type.
Referenced by staticCallback_inner().
insertVertex()
PyObject * MeshPy::insertVertex (PyObject * args)
implementer for the insertVertex() method
References getMeshObjectPtr(), Base::VectorPy::getVectorPtr(), Mesh::MeshObject::insertVertex(), and Base::VectorPy::Type.
Referenced by staticCallback_insertVertex().
intersect()
PyObject * MeshPy::intersect (PyObject * args)
implementer for the intersect() method
References getMeshObjectPtr(), Mesh::MeshObject::intersect(), MeshPy(), and Type.
Referenced by staticCallback_intersect().
isSolid()
PyObject * MeshPy::isSolid (PyObject * args)
implementer for the isSolid() method
References getMeshObjectPtr(), and Mesh::MeshObject::isSolid().
Referenced by staticCallback_isSolid().
mergeFacets()
PyObject * MeshPy::mergeFacets (PyObject * args)
implementer for the mergeFacets() method
References getMeshObjectPtr(), and Mesh::MeshObject::mergeFacets().
Referenced by staticCallback_mergeFacets().
meshFromSegment()
PyObject * MeshPy::meshFromSegment (PyObject * args)
implementer for the meshFromSegment() method
References getMeshObjectPtr(), Mesh::MeshObject::meshFromSegment(), and MeshPy().
Referenced by staticCallback_meshFromSegment().
nearestFacetOnRay()
PyObject * MeshPy::nearestFacetOnRay (PyObject * args)
implementer for the nearestFacetOnRay() method
References Base::InventorBuilder::addBoundingBox(), Base::InventorBuilder::addSingleArrow(), Base::InventorBuilder::addText(), Base::InventorBuilder::close(), MeshCore::MeshGridIterator::GetBoundBox(), MeshCore::MeshGridIterator::GetGridPos(), getMeshObjectPtr(), MeshCore::MeshGridIterator::Init(), MeshCore::MeshGridIterator::More(), MeshCore::MeshAlgorithm::NearestFacetOnRay(), and MeshCore::MeshGridIterator::Next().
Referenced by staticCallback_nearestFacetOnRay().
offset()
PyObject * MeshPy::offset (PyObject * args)
implementer for the offset() method
References getMeshObjectPtr(), and Mesh::MeshObject::offsetSpecial2().
Referenced by staticCallback_offset().
offsetSpecial()
PyObject * MeshPy::offsetSpecial (PyObject * args)
implementer for the offsetSpecial() method
References getMeshObjectPtr(), and Mesh::MeshObject::offsetSpecial().
Referenced by staticCallback_offsetSpecial().
optimizeEdges()
PyObject * MeshPy::optimizeEdges (PyObject * args)
implementer for the optimizeEdges() method
References getMeshObjectPtr(), and Mesh::MeshObject::optimizeEdges().
Referenced by staticCallback_optimizeEdges().
optimizeTopology()
PyObject * MeshPy::optimizeTopology (PyObject * args)
implementer for the optimizeTopology() method
References getMeshObjectPtr(), and Mesh::MeshObject::optimizeTopology().
Referenced by staticCallback_optimizeTopology().
outer()
PyObject * MeshPy::outer (PyObject * args)
implementer for the outer() method
References getMeshObjectPtr(), MeshPy(), Mesh::MeshObject::outer(), and Type.
Referenced by staticCallback_outer().
printInfo()
PyObject * MeshPy::printInfo (PyObject * args)
implementer for the printInfo() method
References getMeshObjectPtr().
Referenced by staticCallback_printInfo().
PyInit()
int MeshPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Data::ComplexGeoDataPy.
References addFacets(), Base::BaseExceptionFreeCADError, getMeshObjectPtr(), Mesh::MeshObject::load(), and Type.
PyMake()
PyObject * MeshPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References MeshPy().
read()
PyObject * MeshPy::read (PyObject * args, PyObject * kwd)
implementer for the read() method
References MeshCore::MeshIO::APLY, MeshCore::MeshIO::ASTL, MeshCore::MeshIO::BMS, MeshCore::MeshIO::BSTL, getMeshObjectPtr(), MeshCore::MeshIO::IV, Mesh::MeshObject::load(), MeshCore::MeshIO::NAS, MeshCore::MeshIO::OBJ, MeshCore::MeshIO::OFF, MeshCore::MeshIO::PLY, MeshCore::MeshIO::PY, MeshCore::MeshIO::SMF, MeshCore::MeshIO::Undefined, MeshCore::MeshIO::VRML, MeshCore::MeshIO::WRZ, MeshCore::MeshIO::X3D, and MeshCore::MeshIO::X3DZ.
Referenced by staticCallback_read().
rebuildNeighbourHood()
PyObject * MeshPy::rebuildNeighbourHood (PyObject * args)
implementer for the rebuildNeighbourHood() method
References Mesh::MeshObject::getKernel(), getMeshObjectPtr(), and MeshCore::MeshKernel::RebuildNeighbours().
Referenced by staticCallback_rebuildNeighbourHood().
refine()
PyObject * MeshPy::refine (PyObject * args)
implementer for the refine() method
References getMeshObjectPtr(), and Mesh::MeshObject::refine().
Referenced by staticCallback_refine().
removeComponents()
PyObject * MeshPy::removeComponents (PyObject * args)
implementer for the removeComponents() method
References getMeshObjectPtr(), and Mesh::MeshObject::removeComponents().
Referenced by staticCallback_removeComponents().
removeDuplicatedFacets()
PyObject * MeshPy::removeDuplicatedFacets (PyObject * args)
implementer for the removeDuplicatedFacets() method
References getMeshObjectPtr(), and Mesh::MeshObject::removeDuplicatedFacets().
Referenced by staticCallback_removeDuplicatedFacets().
removeDuplicatedPoints()
PyObject * MeshPy::removeDuplicatedPoints (PyObject * args)
implementer for the removeDuplicatedPoints() method
References getMeshObjectPtr(), and Mesh::MeshObject::removeDuplicatedPoints().
Referenced by staticCallback_removeDuplicatedPoints().
removeFacets()
PyObject * MeshPy::removeFacets (PyObject * args)
implementer for the removeFacets() method
References Mesh::MeshObject::deleteFacets(), and getMeshObjectPtr().
Referenced by staticCallback_removeFacets().
removeFoldsOnSurface()
PyObject * MeshPy::removeFoldsOnSurface (PyObject * args)
implementer for the removeFoldsOnSurface() method
References Base::BaseExceptionFreeCADError, getMeshObjectPtr(), and Mesh::MeshObject::removeFoldsOnSurface().
Referenced by staticCallback_removeFoldsOnSurface().
removeFullBoundaryFacets()
PyObject * MeshPy::removeFullBoundaryFacets (PyObject * args)
implementer for the removeFullBoundaryFacets() method
References getMeshObjectPtr(), and Mesh::MeshObject::removeFullBoundaryFacets().
Referenced by staticCallback_removeFullBoundaryFacets().
removeInvalidPoints()
PyObject * MeshPy::removeInvalidPoints (PyObject * args)
implementer for the removeInvalidPoints() method
References Base::BaseExceptionFreeCADError, getMeshObjectPtr(), and Mesh::MeshObject::removeInvalidPoints().
Referenced by staticCallback_removeInvalidPoints().
removeNeedles()
PyObject * MeshPy::removeNeedles (PyObject * args)
implementer for the removeNeedles() method
References getMeshObjectPtr(), and Mesh::MeshObject::removeNeedles().
Referenced by staticCallback_removeNeedles().
removeNonManifoldPoints()
PyObject * MeshPy::removeNonManifoldPoints (PyObject * args)
implementer for the removeNonManifoldPoints() method
References getMeshObjectPtr(), and Mesh::MeshObject::removeNonManifoldPoints().
Referenced by staticCallback_removeNonManifoldPoints().
removeNonManifolds()
PyObject * MeshPy::removeNonManifolds (PyObject * args)
implementer for the removeNonManifolds() method
References getMeshObjectPtr(), and Mesh::MeshObject::removeNonManifolds().
Referenced by staticCallback_removeNonManifolds().
representation()
std::string MeshPy::representation (void) const
References Mesh::MeshObject::representation().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
rotate()
PyObject * MeshPy::rotate (PyObject * args)
implementer for the rotate() method
References Mesh::MeshObject::getKernel(), getMeshObjectPtr(), Base::Matrix4D::rotX(), and MeshCore::MeshKernel::Transform().
Referenced by staticCallback_rotate().
setCustomAttributes()
int MeshPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setPoint()
PyObject * MeshPy::setPoint (PyObject * args)
implementer for the setPoint() method
References getMeshObjectPtr(), Mesh::MeshObject::setPoint(), and Base::VectorPy::Type.
Referenced by staticCallback_setPoint().
smooth()
PyObject * MeshPy::smooth (PyObject * args, PyObject * kwd)
implementer for the smooth() method
References Mesh::MeshObject::getKernel(), and getMeshObjectPtr().
Referenced by staticCallback_smooth().
snapVertex()
PyObject * MeshPy::snapVertex (PyObject * args)
implementer for the snapVertex() method
References getMeshObjectPtr(), Base::VectorPy::getVectorPtr(), Mesh::MeshObject::snapVertex(), and Base::VectorPy::Type.
Referenced by staticCallback_snapVertex().
splitEdge()
PyObject * MeshPy::splitEdge (PyObject * args)
implementer for the splitEdge() method
References MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::GetFacets(), Mesh::MeshObject::getKernel(), getMeshObjectPtr(), Base::VectorPy::getVectorPtr(), Mesh::MeshObject::splitEdge(), and Base::VectorPy::Type.
Referenced by staticCallback_splitEdge().
splitEdges()
PyObject * MeshPy::splitEdges (PyObject * args)
implementer for the splitEdges() method
References getMeshObjectPtr(), and Mesh::MeshObject::splitEdges().
Referenced by staticCallback_splitEdges().
splitFacet()
PyObject * MeshPy::splitFacet (PyObject * args)
implementer for the splitFacet() method
References MeshCore::MeshKernel::CountFacets(), Mesh::MeshObject::getKernel(), getMeshObjectPtr(), Base::VectorPy::getVectorPtr(), Mesh::MeshObject::splitFacet(), Base::VectorPy::Type, and draftgeoutils.general::v1().
Referenced by staticCallback_splitFacet().
staticCallback_addFacet()
PyObject * MeshPy::staticCallback_addFacet (PyObject * self, PyObject * args) static
callback for the addFacet() method
References addFacet(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addFacets()
PyObject * MeshPy::staticCallback_addFacets (PyObject * self, PyObject * args) static
callback for the addFacets() method
References addFacets(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addMesh()
PyObject * MeshPy::staticCallback_addMesh (PyObject * self, PyObject * args) static
callback for the addMesh() method
References addMesh(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_clear()
PyObject * MeshPy::staticCallback_clear (PyObject * self, PyObject * args) static
callback for the clear() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, clear(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_coarsen()
PyObject * MeshPy::staticCallback_coarsen (PyObject * self, PyObject * args) static
callback for the coarsen() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, coarsen(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_collapseEdge()
PyObject * MeshPy::staticCallback_collapseEdge (PyObject * self, PyObject * args) static
callback for the collapseEdge() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, collapseEdge(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_collapseFacet()
PyObject * MeshPy::staticCallback_collapseFacet (PyObject * self, PyObject * args) static
callback for the collapseFacet() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, collapseFacet(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_collapseFacets()
PyObject * MeshPy::staticCallback_collapseFacets (PyObject * self, PyObject * args) static
callback for the collapseFacets() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, collapseFacets(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_copy()
PyObject * MeshPy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copy(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_countComponents()
PyObject * MeshPy::staticCallback_countComponents (PyObject * self, PyObject * args) static
callback for the countComponents() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, countComponents(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_countNonUniformOrientedFacets()
PyObject * MeshPy::staticCallback_countNonUniformOrientedFacets (PyObject * self, PyObject * args) static
callback for the countNonUniformOrientedFacets() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, countNonUniformOrientedFacets(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_countSegments()
PyObject * MeshPy::staticCallback_countSegments (PyObject * self, PyObject * args) static
callback for the countSegments() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, countSegments(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_crossSections()
PyObject * MeshPy::staticCallback_crossSections (PyObject * self, PyObject * args) static
callback for the crossSections() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, crossSections(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_cut()
PyObject * MeshPy::staticCallback_cut (PyObject * self, PyObject * args) static
callback for the cut() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, cut(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_decimate()
PyObject * MeshPy::staticCallback_decimate (PyObject * self, PyObject * args) static
callback for the decimate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, decimate(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_difference()
PyObject * MeshPy::staticCallback_difference (PyObject * self, PyObject * args) static
callback for the difference() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, difference(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_fillupHoles()
PyObject * MeshPy::staticCallback_fillupHoles (PyObject * self, PyObject * args) static
callback for the fillupHoles() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, fillupHoles(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_fixCaps()
PyObject * MeshPy::staticCallback_fixCaps (PyObject * self, PyObject * args) static
callback for the fixCaps() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, fixCaps(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_fixDeformations()
PyObject * MeshPy::staticCallback_fixDeformations (PyObject * self, PyObject * args) static
callback for the fixDeformations() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, fixDeformations(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_fixDegenerations()
PyObject * MeshPy::staticCallback_fixDegenerations (PyObject * self, PyObject * args) static
callback for the fixDegenerations() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, fixDegenerations(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_fixIndices()
PyObject * MeshPy::staticCallback_fixIndices (PyObject * self, PyObject * args) static
callback for the fixIndices() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, fixIndices(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_fixSelfIntersections()
PyObject * MeshPy::staticCallback_fixSelfIntersections (PyObject * self, PyObject * args) static
callback for the fixSelfIntersections() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, fixSelfIntersections(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_flipNormals()
PyObject * MeshPy::staticCallback_flipNormals (PyObject * self, PyObject * args) static
callback for the flipNormals() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, flipNormals(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_foraminate()
PyObject * MeshPy::staticCallback_foraminate (PyObject * self, PyObject * args) static
callback for the foraminate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, foraminate(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getArea()
PyObject * MeshPy::staticCallback_getArea (PyObject * self, void * closure) static
getter callback for the Area attribute
References Base::BaseExceptionFreeCADError, getArea(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCountEdges()
PyObject * MeshPy::staticCallback_getCountEdges (PyObject * self, void * closure) static
getter callback for the CountEdges attribute
References Base::BaseExceptionFreeCADError, getCountEdges(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCountFacets()
PyObject * MeshPy::staticCallback_getCountFacets (PyObject * self, void * closure) static
getter callback for the CountFacets attribute
References Base::BaseExceptionFreeCADError, getCountFacets(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCountPoints()
PyObject * MeshPy::staticCallback_getCountPoints (PyObject * self, void * closure) static
getter callback for the CountPoints attribute
References Base::BaseExceptionFreeCADError, getCountPoints(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCurvaturePerVertex()
PyObject * MeshPy::staticCallback_getCurvaturePerVertex (PyObject * self, PyObject * args) static
callback for the getCurvaturePerVertex() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getCurvaturePerVertex(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getEigenSystem()
PyObject * MeshPy::staticCallback_getEigenSystem (PyObject * self, PyObject * args) static
callback for the getEigenSystem() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getEigenSystem(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFacets()
PyObject * MeshPy::staticCallback_getFacets (PyObject * self, void * closure) static
getter callback for the Facets attribute
References Base::BaseExceptionFreeCADError, getFacets(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFacetSelection()
PyObject * MeshPy::staticCallback_getFacetSelection (PyObject * self, PyObject * args) static
callback for the getFacetSelection() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getFacetSelection(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getInternalFacets()
PyObject * MeshPy::staticCallback_getInternalFacets (PyObject * self, PyObject * args) static
callback for the getInternalFacets() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getInternalFacets(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNonUniformOrientedFacets()
PyObject * MeshPy::staticCallback_getNonUniformOrientedFacets (PyObject * self, PyObject * args) static
callback for the getNonUniformOrientedFacets() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getNonUniformOrientedFacets(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPlanarSegments()
PyObject * MeshPy::staticCallback_getPlanarSegments (PyObject * self, PyObject * args) static
callback for the getPlanarSegments() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPlanarSegments(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPointNormals()
PyObject * MeshPy::staticCallback_getPointNormals (PyObject * self, PyObject * args) static
callback for the getPointNormals() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPointNormals(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPoints()
PyObject * MeshPy::staticCallback_getPoints (PyObject * self, void * closure) static
getter callback for the Points attribute
References Base::BaseExceptionFreeCADError, getPoints(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPointSelection()
PyObject * MeshPy::staticCallback_getPointSelection (PyObject * self, PyObject * args) static
callback for the getPointSelection() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPointSelection(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSegment()
PyObject * MeshPy::staticCallback_getSegment (PyObject * self, PyObject * args) static
callback for the getSegment() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getSegment(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSegmentsByCurvature()
PyObject * MeshPy::staticCallback_getSegmentsByCurvature (PyObject * self, PyObject * args) static
callback for the getSegmentsByCurvature() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getSegmentsByCurvature(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSegmentsOfType()
PyObject * MeshPy::staticCallback_getSegmentsOfType (PyObject * self, PyObject * args) static
callback for the getSegmentsOfType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getSegmentsOfType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSelfIntersections()
PyObject * MeshPy::staticCallback_getSelfIntersections (PyObject * self, PyObject * args) static
callback for the getSelfIntersections() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getSelfIntersections(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSeparateComponents()
PyObject * MeshPy::staticCallback_getSeparateComponents (PyObject * self, PyObject * args) static
callback for the getSeparateComponents() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getSeparateComponents(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTopology()
PyObject * MeshPy::staticCallback_getTopology (PyObject * self, void * closure) static
getter callback for the Topology attribute
References Base::BaseExceptionFreeCADError, getTopology(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVolume()
PyObject * MeshPy::staticCallback_getVolume (PyObject * self, void * closure) static
getter callback for the Volume attribute
References Base::BaseExceptionFreeCADError, getVolume(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_harmonizeNormals()
PyObject * MeshPy::staticCallback_harmonizeNormals (PyObject * self, PyObject * args) static
callback for the harmonizeNormals() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, harmonizeNormals(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_hasInvalidPoints()
PyObject * MeshPy::staticCallback_hasInvalidPoints (PyObject * self, PyObject * args) static
callback for the hasInvalidPoints() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hasInvalidPoints(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_hasNonManifolds()
PyObject * MeshPy::staticCallback_hasNonManifolds (PyObject * self, PyObject * args) static
callback for the hasNonManifolds() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hasNonManifolds(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_hasNonUniformOrientedFacets()
PyObject * MeshPy::staticCallback_hasNonUniformOrientedFacets (PyObject * self, PyObject * args) static
callback for the hasNonUniformOrientedFacets() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hasNonUniformOrientedFacets(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_hasSelfIntersections()
PyObject * MeshPy::staticCallback_hasSelfIntersections (PyObject * self, PyObject * args) static
callback for the hasSelfIntersections() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hasSelfIntersections(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_inner()
PyObject * MeshPy::staticCallback_inner (PyObject * self, PyObject * args) static
callback for the inner() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, inner(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_insertVertex()
PyObject * MeshPy::staticCallback_insertVertex (PyObject * self, PyObject * args) static
callback for the insertVertex() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, insertVertex(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_intersect()
PyObject * MeshPy::staticCallback_intersect (PyObject * self, PyObject * args) static
callback for the intersect() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, intersect(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isSolid()
PyObject * MeshPy::staticCallback_isSolid (PyObject * self, PyObject * args) static
callback for the isSolid() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isSolid(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_mergeFacets()
PyObject * MeshPy::staticCallback_mergeFacets (PyObject * self, PyObject * args) static
callback for the mergeFacets() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), mergeFacets(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_meshFromSegment()
PyObject * MeshPy::staticCallback_meshFromSegment (PyObject * self, PyObject * args) static
callback for the meshFromSegment() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), meshFromSegment(), and Base::PyObjectBase::PyObjectBase().
staticCallback_nearestFacetOnRay()
PyObject * MeshPy::staticCallback_nearestFacetOnRay (PyObject * self, PyObject * args) static
callback for the nearestFacetOnRay() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), nearestFacetOnRay(), and Base::PyObjectBase::PyObjectBase().
staticCallback_offset()
PyObject * MeshPy::staticCallback_offset (PyObject * self, PyObject * args) static
callback for the offset() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), offset(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_offsetSpecial()
PyObject * MeshPy::staticCallback_offsetSpecial (PyObject * self, PyObject * args) static
callback for the offsetSpecial() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), offsetSpecial(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_optimizeEdges()
PyObject * MeshPy::staticCallback_optimizeEdges (PyObject * self, PyObject * args) static
callback for the optimizeEdges() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), optimizeEdges(), and Base::PyObjectBase::PyObjectBase().
staticCallback_optimizeTopology()
PyObject * MeshPy::staticCallback_optimizeTopology (PyObject * self, PyObject * args) static
callback for the optimizeTopology() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), optimizeTopology(), and Base::PyObjectBase::PyObjectBase().
staticCallback_outer()
PyObject * MeshPy::staticCallback_outer (PyObject * self, PyObject * args) static
callback for the outer() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), outer(), and Base::PyObjectBase::PyObjectBase().
staticCallback_printInfo()
PyObject * MeshPy::staticCallback_printInfo (PyObject * self, PyObject * args) static
callback for the printInfo() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), printInfo(), and Base::PyObjectBase::PyObjectBase().
staticCallback_read()
PyObject * MeshPy::staticCallback_read (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the read() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), read(), and Base::PyObjectBase::startNotify().
staticCallback_rebuildNeighbourHood()
PyObject * MeshPy::staticCallback_rebuildNeighbourHood (PyObject * self, PyObject * args) static
callback for the rebuildNeighbourHood() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), rebuildNeighbourHood(), and Base::PyObjectBase::startNotify().
staticCallback_refine()
PyObject * MeshPy::staticCallback_refine (PyObject * self, PyObject * args) static
callback for the refine() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), refine(), and Base::PyObjectBase::startNotify().
staticCallback_removeComponents()
PyObject * MeshPy::staticCallback_removeComponents (PyObject * self, PyObject * args) static
callback for the removeComponents() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeComponents(), and Base::PyObjectBase::startNotify().
staticCallback_removeDuplicatedFacets()
PyObject * MeshPy::staticCallback_removeDuplicatedFacets (PyObject * self, PyObject * args) static
callback for the removeDuplicatedFacets() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeDuplicatedFacets(), and Base::PyObjectBase::startNotify().
staticCallback_removeDuplicatedPoints()
PyObject * MeshPy::staticCallback_removeDuplicatedPoints (PyObject * self, PyObject * args) static
callback for the removeDuplicatedPoints() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeDuplicatedPoints(), and Base::PyObjectBase::startNotify().
staticCallback_removeFacets()
PyObject * MeshPy::staticCallback_removeFacets (PyObject * self, PyObject * args) static
callback for the removeFacets() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeFacets(), and Base::PyObjectBase::startNotify().
staticCallback_removeFoldsOnSurface()
PyObject * MeshPy::staticCallback_removeFoldsOnSurface (PyObject * self, PyObject * args) static
callback for the removeFoldsOnSurface() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeFoldsOnSurface(), and Base::PyObjectBase::startNotify().
staticCallback_removeFullBoundaryFacets()
PyObject * MeshPy::staticCallback_removeFullBoundaryFacets (PyObject * self, PyObject * args) static
callback for the removeFullBoundaryFacets() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeFullBoundaryFacets(), and Base::PyObjectBase::startNotify().
staticCallback_removeInvalidPoints()
PyObject * MeshPy::staticCallback_removeInvalidPoints (PyObject * self, PyObject * args) static
callback for the removeInvalidPoints() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeInvalidPoints(), and Base::PyObjectBase::startNotify().
staticCallback_removeNeedles()
PyObject * MeshPy::staticCallback_removeNeedles (PyObject * self, PyObject * args) static
callback for the removeNeedles() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeNeedles(), and Base::PyObjectBase::startNotify().
staticCallback_removeNonManifoldPoints()
PyObject * MeshPy::staticCallback_removeNonManifoldPoints (PyObject * self, PyObject * args) static
callback for the removeNonManifoldPoints() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeNonManifoldPoints(), and Base::PyObjectBase::startNotify().
staticCallback_removeNonManifolds()
PyObject * MeshPy::staticCallback_removeNonManifolds (PyObject * self, PyObject * args) static
callback for the removeNonManifolds() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeNonManifolds(), and Base::PyObjectBase::startNotify().
staticCallback_rotate()
PyObject * MeshPy::staticCallback_rotate (PyObject * self, PyObject * args) static
callback for the rotate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), rotate(), and Base::PyObjectBase::startNotify().
staticCallback_setArea()
int MeshPy::staticCallback_setArea (PyObject * self, PyObject * value, void * closure) static
setter callback for the Area attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setCountEdges()
int MeshPy::staticCallback_setCountEdges (PyObject * self, PyObject * value, void * closure) static
setter callback for the CountEdges attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setCountFacets()
int MeshPy::staticCallback_setCountFacets (PyObject * self, PyObject * value, void * closure) static
setter callback for the CountFacets attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setCountPoints()
int MeshPy::staticCallback_setCountPoints (PyObject * self, PyObject * value, void * closure) static
setter callback for the CountPoints attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setFacets()
int MeshPy::staticCallback_setFacets (PyObject * self, PyObject * value, void * closure) static
setter callback for the Facets attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPoint()
PyObject * MeshPy::staticCallback_setPoint (PyObject * self, PyObject * args) static
callback for the setPoint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setPoint(), and Base::PyObjectBase::startNotify().
staticCallback_setPoints()
int MeshPy::staticCallback_setPoints (PyObject * self, PyObject * value, void * closure) static
setter callback for the Points attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setTopology()
int MeshPy::staticCallback_setTopology (PyObject * self, PyObject * value, void * closure) static
setter callback for the Topology attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setVolume()
int MeshPy::staticCallback_setVolume (PyObject * self, PyObject * value, void * closure) static
setter callback for the Volume attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_smooth()
PyObject * MeshPy::staticCallback_smooth (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the smooth() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and smooth().
staticCallback_snapVertex()
PyObject * MeshPy::staticCallback_snapVertex (PyObject * self, PyObject * args) static
callback for the snapVertex() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), snapVertex(), and Base::PyObjectBase::startNotify().
staticCallback_splitEdge()
PyObject * MeshPy::staticCallback_splitEdge (PyObject * self, PyObject * args) static
callback for the splitEdge() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), splitEdge(), and Base::PyObjectBase::startNotify().
staticCallback_splitEdges()
PyObject * MeshPy::staticCallback_splitEdges (PyObject * self, PyObject * args) static
callback for the splitEdges() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), splitEdges(), and Base::PyObjectBase::startNotify().
staticCallback_splitFacet()
PyObject * MeshPy::staticCallback_splitFacet (PyObject * self, PyObject * args) static
callback for the splitFacet() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), splitFacet(), and Base::PyObjectBase::startNotify().
staticCallback_swapEdge()
PyObject * MeshPy::staticCallback_swapEdge (PyObject * self, PyObject * args) static
callback for the swapEdge() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and swapEdge().
staticCallback_transform()
PyObject * MeshPy::staticCallback_transform (PyObject * self, PyObject * args) static
callback for the transform() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and transform().
staticCallback_transformToEigen()
PyObject * MeshPy::staticCallback_transformToEigen (PyObject * self, PyObject * args) static
callback for the transformToEigen() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and transformToEigen().
staticCallback_translate()
PyObject * MeshPy::staticCallback_translate (PyObject * self, PyObject * args) static
callback for the translate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and translate().
staticCallback_trim()
PyObject * MeshPy::staticCallback_trim (PyObject * self, PyObject * args) static
callback for the trim() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and trim().
staticCallback_unite()
PyObject * MeshPy::staticCallback_unite (PyObject * self, PyObject * args) static
callback for the unite() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and unite().
staticCallback_write()
PyObject * MeshPy::staticCallback_write (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the write() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and write().
staticCallback_writeInventor()
PyObject * MeshPy::staticCallback_writeInventor (PyObject * self, PyObject * args) static
callback for the writeInventor() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and writeInventor().
swapEdge()
PyObject * MeshPy::swapEdge (PyObject * args)
implementer for the swapEdge() method
References MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::GetFacets(), Mesh::MeshObject::getKernel(), getMeshObjectPtr(), and Mesh::MeshObject::swapEdge().
Referenced by staticCallback_swapEdge().
transform()
PyObject * MeshPy::transform (PyObject * args)
implementer for the transform() method
References Mesh::MeshObject::getKernel(), getMeshObjectPtr(), MeshCore::MeshKernel::Transform(), and Base::MatrixPy::Type.
Referenced by staticCallback_transform().
transformToEigen()
PyObject * MeshPy::transformToEigen (PyObject * args)
implementer for the transformToEigen() method
References getMeshObjectPtr(), and Mesh::MeshObject::transformToEigenSystem().
Referenced by staticCallback_transformToEigen().
translate()
PyObject * MeshPy::translate (PyObject * args)
implementer for the translate() method
References Mesh::MeshObject::getKernel(), getMeshObjectPtr(), Base::Matrix4D::move(), and MeshCore::MeshKernel::Transform().
Referenced by staticCallback_translate().
trim()
PyObject * MeshPy::trim (PyObject * args)
implementer for the trim() method
References Base::Polygon2d::Add(), getMeshObjectPtr(), MeshCore::AbstractPolygonTriangulator::GetTransformToFitPlane(), Base::Matrix4D::inverseOrthogonal(), MeshCore::AbstractPolygonTriangulator::ProjectToFitPlane(), MeshCore::AbstractPolygonTriangulator::SetPolygon(), and Mesh::MeshObject::trim().
Referenced by staticCallback_trim().
unite()
PyObject * MeshPy::unite (PyObject * args)
implementer for the unite() method
References getMeshObjectPtr(), MeshPy(), Type, and Mesh::MeshObject::unite().
Referenced by staticCallback_unite().
write()
PyObject * MeshPy::write (PyObject * args, PyObject * kwd)
implementer for the write() method
References MeshCore::MeshIO::APLY, MeshCore::MeshIO::ASTL, MeshCore::MeshIO::ASY, MeshCore::Material::binding, MeshCore::MeshIO::BMS, MeshCore::MeshIO::BSTL, Mesh::MeshObject::countFacets(), Mesh::MeshObject::countPoints(), MeshCore::Material::diffuseColor, getMeshObjectPtr(), MeshCore::MeshIO::IDTF, MeshCore::MeshIO::IV, MeshCore::MeshIO::MGL, MeshCore::MeshIO::NAS, MeshCore::MeshIO::OBJ, MeshCore::MeshIO::OFF, MeshCore::MeshIO::OVERALL, MeshCore::MeshIO::PER_FACE, MeshCore::MeshIO::PER_VERTEX, MeshCore::MeshIO::PLY, MeshCore::MeshIO::PY, Mesh::MeshObject::save(), MeshCore::MeshIO::SMF, MeshCore::MeshIO::Undefined, MeshCore::MeshIO::VRML, MeshCore::MeshIO::WRZ, MeshCore::MeshIO::X3D, MeshCore::MeshIO::X3DOM, and MeshCore::MeshIO::X3DZ.
Referenced by staticCallback_write().
writeInventor()
PyObject * MeshPy::writeInventor (PyObject * args)
implementer for the writeInventor() method
References Base::InventorBuilder::addIndexedFaceSet(), Base::InventorBuilder::addPoints(), Base::InventorBuilder::addShapeHints(), Base::InventorBuilder::beginPoints(), Base::InventorBuilder::beginSeparator(), Base::InventorBuilder::close(), Base::InventorBuilder::endPoints(), Base::InventorBuilder::endSeparator(), and getMeshObjectPtr().
Referenced by staticCallback_writeInventor().
Friends And Related Function Documentation
PropertyMeshKernel
friend class PropertyMeshKernel friend
Member Data Documentation
GetterSetter
PyGetSetDef MeshPy::GetterSetter static
Attribute structure of MeshPy.
Methods
PyMethodDef MeshPy::Methods static
Methods structure of MeshPy.
Type
PyTypeObject MeshPy::Type static
Type structure of MeshPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), addMesh(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), difference(), inner(), intersect(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), outer(), PyInit(), Mesh::PropertyMeshKernel::setPyObject(), and unite().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Mesh/App/MeshPy.h
Sources/FreeCAD/src/Mod/Mesh/App/MeshPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Mesh/App/MeshPy.cpp