FreeCAD: SpreadsheetGui::DlgSettingsImp Class Reference
SpreadsheetGui::DlgSettingsImp Class Reference
The DlgSettingsImp class implements a preference page to change settings for the Spreadsheet workbench.
#include <DlgSettingsImp.h>
Public Member Functions
DlgSettingsImp (QWidget *parent=nullptr)
~DlgSettingsImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void loadSettings ()
void saveSettings ()
virtual void changeEvent (QEvent *e)=0
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Detailed Description
The DlgSettingsImp class implements a preference page to change settings for the Spreadsheet workbench.
/author TheMarkster, based on work by Jürgen Riegel
Constructor & Destructor Documentation
DlgSettingsImp()
DlgSettingsImp::DlgSettingsImp (QWidget * parent = nullptr)
~DlgSettingsImp()
DlgSettingsImp::~DlgSettingsImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void DlgSettingsImp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
loadSettings()
void DlgSettingsImp::loadSettings () protected virtual
items "tab", ";", and "," have already been added to the combo box in the .ui file we'll recognize a few tokens: comma, semicolon, tab, and \t
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), ParameterGrp::GetASCII(), and App::Application::GetParameterGroupByPath().
saveSettings()
void DlgSettingsImp::saveSettings () protected virtual
use whatever the user has entered here we'll check for validity during import/export
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetASCII().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Spreadsheet/Gui/DlgSettingsImp.h
FreeCAD/src/Mod/Spreadsheet/Gui/DlgSettingsImp.cpp