FreeCAD: ArchProject Namespace Reference
ArchProject Namespace Reference
The Project object and tools.
Functions
def makeProject (sites=None, name="Project")
def QT_TRANSLATE_NOOP (ctxt, txt)
def translate (ctxt, txt)
Detailed Description
The Project object and tools.
This module provides tools to build Project objects.
Function Documentation
makeProject()
def ArchProject.makeProject (sites = None, name = "Project")
Create an Arch project.
If sites are provided, add them as children of the new project.
Parameters
----------
sites: list of <Part::FeaturePython>, optional
    Sites to add as children of the project. Ultimately this could be
    anything, however.
name: str, optional
    The label for the project.
Returns
-------
<Part::FeaturePython>
    The created project.
References QT_TRANSLATE_NOOP(), and ArchIFC.IfcRoot.setProperties().
QT_TRANSLATE_NOOP()
def ArchProject.QT_TRANSLATE_NOOP (ctxt, txt)
Referenced by makeProject().
translate()
def ArchProject.translate (ctxt, txt)