FreeCAD: Gui::PropertyEditor::LinkSelection Class Reference
Gui::PropertyEditor::LinkSelection Class Reference
#include <PropertyItem.h>
Public Slots
void select ()
Public Member Functions
LinkSelection (const App::SubObjectT &)
~LinkSelection ()
Constructor & Destructor Documentation
LinkSelection()
LinkSelection::LinkSelection (const App::SubObjectT & link)
~LinkSelection()
LinkSelection::~LinkSelection ()
Member Function Documentation
select
void LinkSelection::select () slot
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), App::DocumentObjectT::getDocumentName(), Gui::getMainWindow(), App::DocumentObjectT::getObjectName(), App::SubObjectT::getSubName(), App::SubObjectT::getSubObject(), Gui::Selection(), and Gui::SelectionSingleton::selStackPush().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/propertyeditor/PropertyItem.h
Sources/FreeCAD/src/Gui/propertyeditor/PropertyItem.cpp