FreeCAD: Attacher::AttachEngineLine Class Reference
Attacher::AttachEngineLine Class Reference
#include <Attacher.h>
Public Member Functions
AttachEngineLine ()
virtual Base::Placement calculateAttachedPlacement (const Base::Placement &origPlacement) const
virtual AttachEngineLine * copy () const
Public Member Functions inherited from Attacher::AttachEngine
AttachEngine ()
void EnableAllSupportedModes (void)
EnableAllModes enables all modes that have shape type lists filled.
Base::Placement placementFactory (const gp_Dir &ZAxis, gp_Vec XAxis, gp_Pnt Origin, gp_Pnt refOrg=gp_Pnt(), bool useRefOrg_Line=false, bool useRefOrg_Plane=false, bool makeYVertical=false, bool makeLegacyFlatFaceOrientation=false, Base::Placement *placeOfRef=0) const
placementFactory calculates placement from Z axis direction, optional X axis direction, and origin point.
virtual void setUp (const App::PropertyLinkSubList &references, eMapMode mapMode=mmDeactivated, bool mapReverse=false, double attachParameter=0.0, double surfU=0.0, double surfV=0.0, const Base::Placement &attachmentOffset=Base::Placement())
virtual void setUp (const AttachEngine &another)
virtual void suggestMapModes (SuggestResult &result) const
suggestMapModes is the procedure that knows everything about mapping modes.
virtual ~AttachEngine ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId (void) const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Attacher::AttachEngine
static eRefType downgradeType (eRefType type)
downgradeType converts a more-specific type into a less-specific type (e.g.
static GProp_GProps getInertialPropsOfShape (const std::vector< const TopoDS_Shape * > &shapes)
static eMapMode getModeByName (const std::string &modeName)
static std::string getModeName (eMapMode mmode)
getModeName
static eRefType getRefTypeByName (const std::string &typeName)
static std::string getRefTypeName (eRefType shapeType)
static eRefType getShapeType (const App::DocumentObject *obj, const std::string &subshape)
getShapeType by link content.
static eRefType getShapeType (const TopoDS_Shape &sh)
getShapeType by shape.
static int getTypeRank (eRefType type)
getTypeRank determines, how specific is the supplied shape type.
static int isShapeOfType (eRefType shapeType, eRefType requirement)
isShapeOfType tests if a shape fulfills the requirement of a mode, and returns a score of how spot on was the requirement.
static void verifyReferencesAreSafe (const App::PropertyLinkSubList &references)
verifyReferencesAreSafe: checks if pointers in references still point to objects contained in open documents.
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Public Attributes inherited from Attacher::AttachEngine
Base::Placement attachmentOffset
double attachParameter
eMapMode mapMode
bool mapReverse
std::vector< bool > modeEnabled
modeEnabled is an indicator, whether some mode is ever suggested or not.
std::vector< refTypeStringList > modeRefTypes
App::PropertyLinkSubList references
double surfU
double surfV
Static Public Attributes inherited from Attacher::AttachEngine
static const char * eMapModeStrings []
static const char * eRefTypeStrings []
Protected Member Functions inherited from Attacher::AttachEngine
refTypeString cat (eRefType rt1)
refTypeString cat (eRefType rt1, eRefType rt2)
refTypeString cat (eRefType rt1, eRefType rt2, eRefType rt3)
refTypeString cat (eRefType rt1, eRefType rt2, eRefType rt3, eRefType rt4)
Static Protected Member Functions inherited from Attacher::AttachEngine
static void readLinks (const App::PropertyLinkSubList &references, std::vector< App::GeoFeature * > &geofs, std::vector< const TopoDS_Shape * > &shapes, std::vector< TopoDS_Shape > &storage, std::vector< eRefType > &types)
AttachEngine3D::readLinks.
static void throwWrongMode (eMapMode mmode)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
AttachEngineLine()
AttachEngineLine::AttachEngineLine ()
References Attacher::mm1Asymptote1, Attacher::mm1Asymptote2, Attacher::mm1AxisCurv, Attacher::mm1AxisInertia1, Attacher::mm1AxisInertia2, Attacher::mm1AxisInertia3, Attacher::mm1AxisX, Attacher::mm1AxisY, Attacher::mm1AxisZ, Attacher::mm1Binormal, Attacher::mm1Directrix1, Attacher::mm1Directrix2, Attacher::mm1FaceNormal, Attacher::mm1Normal, Attacher::mm1Proximity, Attacher::mm1Tangent, Attacher::mm1TwoPoints, Attacher::mmDummy_NumberOfModes, Attacher::mmFrenetTB, Attacher::mmFrenetTN, Attacher::mmNormalToPath, Attacher::mmObjectXY, Attacher::mmObjectXZ, Attacher::mmObjectYZ, Attacher::mmRevolutionSection, Attacher::mmTangentPlane, Attacher::AttachEngine::modeRefTypes, Attacher::rtAnything, Attacher::rtConic, Attacher::rtEllipse, Attacher::rtHyperbola, Attacher::rtLine, and Attacher::rtVertex.
Member Function Documentation
calculateAttachedPlacement()
Base::Placement AttachEngineLine::calculateAttachedPlacement (const Base::Placement & origPlacement) const virtual
Implements Attacher::AttachEngine.
References Attacher::AttachEngine::attachmentOffset, Attacher::AttachEngine3D::calculateAttachedPlacement(), Base::Console(), DraftVecUtils::dist(), Base::Placement::getPosition(), Attacher::AttachEngine::mapMode, Attacher::mm1Asymptote1, Attacher::mm1Asymptote2, Attacher::mm1AxisCurv, Attacher::mm1AxisInertia1, Attacher::mm1AxisInertia2, Attacher::mm1AxisInertia3, Attacher::mm1AxisX, Attacher::mm1AxisY, Attacher::mm1AxisZ, Attacher::mm1Binormal, Attacher::mm1Directrix1, Attacher::mm1Directrix2, Attacher::mm1FaceNormal, Attacher::mm1Normal, Attacher::mm1Proximity, Attacher::mm1Tangent, Attacher::mm1TwoPoints, Attacher::mmDeactivated, Attacher::mmFrenetTB, Attacher::mmFrenetTN, Attacher::mmNormalToPath, Attacher::mmObjectXY, Attacher::mmObjectXZ, Attacher::mmObjectYZ, Attacher::mmRevolutionSection, Attacher::mmTangentPlane, Base::Placement::setRotation(), Attacher::AttachEngine::setUp(), Base::ConsoleSingleton::Warning(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
copy()
AttachEngineLine * AttachEngineLine::copy (void) const virtual
Implements Attacher::AttachEngine.
References Attacher::AttachEngine::setUp().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/App/Attacher.h
Sources/FreeCAD/src/Mod/Part/App/Attacher.cpp