FreeCAD: SketcherGui::TaskSketcherElements Class Reference
SketcherGui::TaskSketcherElements Class Reference
#include <TaskSketcherElements.h>
Public Slots
void on_autoSwitchBox_stateChanged (int state)
void on_listWidgetElements_currentFilterChanged (int index)
void on_listWidgetElements_currentModeFilterChanged (int index)
void on_listWidgetElements_filterShortcutPressed ()
void on_listWidgetElements_itemEntered (QListWidgetItem *item)
void on_listWidgetElements_itemSelectionChanged (void)
void on_namingBox_stateChanged (int state)
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Public Member Functions
void onSelectionChanged (const Gui::SelectionChanges &msg)
Observer message from the Selection.
TaskSketcherElements (ViewProviderSketch *sketchView)
~TaskSketcherElements ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Protected Types
typedef boost::signals2::connection Connection
Protected Member Functions
void changeEvent (QEvent *e)
void leaveEvent (QEvent *event)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Protected Attributes
Connection connectionElementsChanged
ViewProviderSketch * sketchView
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Additional Inherited Members
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Member Typedef Documentation
Connection
typedef boost::signals2::connection SketcherGui::TaskSketcherElements::Connection protected
Constructor & Destructor Documentation
TaskSketcherElements()
TaskSketcherElements::TaskSketcherElements (ViewProviderSketch * sketchView)
References draftgeoutils.faces::bind(), draftgeoutils.intersections::connect(), connectionElementsChanged, App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), QSint::ActionGroup::groupLayout(), on_autoSwitchBox_stateChanged(), on_listWidgetElements_currentFilterChanged(), on_listWidgetElements_currentModeFilterChanged(), on_listWidgetElements_filterShortcutPressed(), on_listWidgetElements_itemEntered(), on_listWidgetElements_itemSelectionChanged(), on_namingBox_stateChanged(), SketcherGui::ViewProviderSketch::signalElementsChanged, and sketchView.
~TaskSketcherElements()
TaskSketcherElements::~TaskSketcherElements ()
References connectionElementsChanged, App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetBool().
Member Function Documentation
changeEvent()
void TaskSketcherElements::changeEvent (QEvent * e) protected
leaveEvent()
void TaskSketcherElements::leaveEvent (QEvent * event) protected
References Gui::SelectionSingleton::rmvPreselect(), and Gui::Selection().
on_autoSwitchBox_stateChanged
void TaskSketcherElements::on_autoSwitchBox_stateChanged (int state) slot
Referenced by TaskSketcherElements().
on_listWidgetElements_currentFilterChanged
void TaskSketcherElements::on_listWidgetElements_currentFilterChanged (int index) slot
References Gui::SelectionSingleton::rmvPreselect(), and Gui::Selection().
Referenced by TaskSketcherElements().
on_listWidgetElements_currentModeFilterChanged
void TaskSketcherElements::on_listWidgetElements_currentModeFilterChanged (int index) slot
Referenced by TaskSketcherElements().
on_listWidgetElements_filterShortcutPressed
void TaskSketcherElements::on_listWidgetElements_filterShortcutPressed () slot
References ElementItem::GeometryType, Base::Persistence::getClassTypeId(), on_listWidgetElements_itemEntered(), Gui::SelectionSingleton::rmvPreselect(), and Gui::Selection().
Referenced by TaskSketcherElements().
on_listWidgetElements_itemEntered
void TaskSketcherElements::on_listWidgetElements_itemEntered (QListWidgetItem * item) slot
References ElementItem::ElementNbr, ElementItem::GeometryType, Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), SketcherGui::ViewProviderSketch::getSketchObject(), Sketcher::SketchObject::getVertexIndexGeoPos(), Gui::SelectionSingleton::rmvPreselect(), Gui::Selection(), Gui::SelectionSingleton::setPreselect(), and sketchView.
Referenced by on_listWidgetElements_filterShortcutPressed(), and TaskSketcherElements().
on_listWidgetElements_itemSelectionChanged
void TaskSketcherElements::on_listWidgetElements_itemSelectionChanged (void) slot
References Gui::SelectionSingleton::addSelections(), Gui::SelectionObserver::blockSelection(), Gui::SelectionSingleton::clearSelection(), ElementItem::ElementNbr, ElementItem::EndVertex, App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), SketcherGui::ViewProviderSketch::getSketchObject(), ElementItem::isEndPointSelected, ElementItem::isLineSelected, ElementItem::isMidPointSelected, ElementItem::isStartingPointSelected, ElementItem::MidVertex, Gui::Selection(), sketchView, and ElementItem::StartingVertex.
Referenced by TaskSketcherElements().
on_namingBox_stateChanged
void TaskSketcherElements::on_namingBox_stateChanged (int state) slot
Referenced by TaskSketcherElements().
onSelectionChanged()
void TaskSketcherElements::onSelectionChanged (const Gui::SelectionChanges & msg) virtual
Observer message from the Selection.
Implements Gui::SelectionObserver.
References Gui::SelectionChanges::AddSelection, Gui::SelectionChanges::ClrSelection, ElementItem::ElementNbr, Sketcher::end, App::DocumentObject::getDocument(), Sketcher::SketchObject::getGeoVertexIndex(), App::Document::getName(), App::DocumentObject::getNameInDocument(), SketcherGui::ViewProviderSketch::getSketchObject(), ElementItem::isEndPointSelected, ElementItem::isLineSelected, ElementItem::isMidPointSelected, ElementItem::isStartingPointSelected, Sketcher::mid, Gui::SelectionChanges::RmvSelection, draftutils.gui_utils::select(), Gui::SelectionChanges::SetSelection, sketchView, and Sketcher::start.
Member Data Documentation
connectionElementsChanged
Connection SketcherGui::TaskSketcherElements::connectionElementsChanged protected
Referenced by TaskSketcherElements(), and ~TaskSketcherElements().
sketchView
ViewProviderSketch* SketcherGui::TaskSketcherElements::sketchView protected
Referenced by on_listWidgetElements_itemEntered(), on_listWidgetElements_itemSelectionChanged(), onSelectionChanged(), and TaskSketcherElements().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/Gui/TaskSketcherElements.h
FreeCAD/src/Mod/Sketcher/Gui/TaskSketcherElements.cpp