FreeCAD: MED::TShapeFun Struct Reference
MED::TShapeFun Struct Reference abstract
Shape function definitions.
#include <MED_GaussUtils.hxx>
Classes
class TFun
Public Member Functions
bool Eval (const TCellInfo &theCellInfo, const TNodeInfo &theNodeInfo, const TElemNum &theElemNum, const TCCoordSliceArr &theRef, const TCCoordSliceArr &theGauss, TGaussCoord &theGaussCoord, EModeSwitch theMode)
TCoordSlice GetCoord (TInt theRefId)
TCCoordSlice GetCoord (TInt theRefId) const
void GetFun (const TCCoordSliceArr &theRef, const TCCoordSliceArr &theGauss, TFun &theFun) const
TInt GetNbRef () const
virtual void InitFun (const TCCoordSliceArr &theRef, const TCCoordSliceArr &theGauss, TFun &theFun) const =0
virtual bool IsSatisfy (const TCCoordSliceArr &theRefCoord) const
TShapeFun (TInt theDim=0, TInt theNbRef=0)
Public Attributes
TInt myDim
TInt myNbRef
TFloatVector myRefCoord
Detailed Description
Shape function definitions.
Constructor & Destructor Documentation
TShapeFun()
MED::TShapeFun::TShapeFun (TInt theDim = 0, TInt theNbRef = 0)
Member Function Documentation
Eval()
bool MED::TShapeFun::Eval (const TCellInfo & theCellInfo, const TNodeInfo & theNodeInfo, const TElemNum & theElemNum, const TCCoordSliceArr & theRef, const TCCoordSliceArr & theGauss, TGaussCoord & theGaussCoord, EModeSwitch theMode)
References MED::TCellInfo::GetConnDim(), MED::TCellInfo::GetConnSlice(), MED::TNodeInfo::GetCoordSlice(), MED::TGaussCoord::GetCoordSliceArr(), MED::TShapeFun::TFun::GetFunSlice(), MED::TElemInfo::GetMeshInfo(), MED::TElemInfo::GetNbElem(), MED::TGaussCoord::Init(), InitFun(), and IsSatisfy().
GetCoord() [1/2]
TCoordSlice MED::TShapeFun::GetCoord (TInt theRefId)
References myDim, and myRefCoord.
GetCoord() [2/2]
TCCoordSlice MED::TShapeFun::GetCoord (TInt theRefId) const
References myDim, and myRefCoord.
Referenced by IsSatisfy(), MED::THexa20a::THexa20a(), MED::THexa20b::THexa20b(), MED::THexa27a::THexa27a(), MED::THexa8a::THexa8a(), MED::THexa8b::THexa8b(), MED::TPenta15a::TPenta15a(), MED::TPenta15b::TPenta15b(), MED::TPenta6a::TPenta6a(), MED::TPenta6b::TPenta6b(), MED::TPyra13a::TPyra13a(), MED::TPyra13b::TPyra13b(), MED::TPyra5a::TPyra5a(), MED::TPyra5b::TPyra5b(), MED::TQuad4a::TQuad4a(), MED::TQuad4b::TQuad4b(), MED::TQuad8a::TQuad8a(), MED::TQuad8b::TQuad8b(), MED::TQuad9a::TQuad9a(), MED::TQuad9b::TQuad9b(), MED::TSeg2a::TSeg2a(), MED::TSeg3a::TSeg3a(), MED::TTetra10a::TTetra10a(), MED::TTetra10b::TTetra10b(), MED::TTetra4a::TTetra4a(), MED::TTetra4b::TTetra4b(), MED::TTria3a::TTria3a(), MED::TTria3b::TTria3b(), MED::TTria6a::TTria6a(), and MED::TTria6b::TTria6b().
GetFun()
void MED::TShapeFun::GetFun (const TCCoordSliceArr & theRef, const TCCoordSliceArr & theGauss, TFun & theFun) const
References MED::TShapeFun::TFun::Init().
Referenced by MED::TSeg2a::InitFun(), MED::TSeg3a::InitFun(), MED::TTria3a::InitFun(), MED::TTria6a::InitFun(), MED::TTria3b::InitFun(), MED::TTria6b::InitFun(), MED::TQuad4a::InitFun(), MED::TQuad8a::InitFun(), MED::TQuad9a::InitFun(), MED::TQuad4b::InitFun(), MED::TQuad8b::InitFun(), MED::TQuad9b::InitFun(), MED::TTetra4a::InitFun(), MED::TTetra10a::InitFun(), MED::TTetra4b::InitFun(), MED::TTetra10b::InitFun(), MED::THexa8a::InitFun(), MED::THexa20a::InitFun(), MED::THexa27a::InitFun(), MED::THexa8b::InitFun(), MED::THexa20b::InitFun(), MED::TPenta6a::InitFun(), MED::TPenta6b::InitFun(), MED::TPenta15a::InitFun(), MED::TPenta15b::InitFun(), MED::TPyra5a::InitFun(), MED::TPyra5b::InitFun(), MED::TPyra13a::InitFun(), and MED::TPyra13b::InitFun().
GetNbRef()
TInt MED::TShapeFun::GetNbRef () const
Referenced by IsSatisfy(), MED::THexa8a::THexa8a(), MED::THexa8b::THexa8b(), MED::TQuad4a::TQuad4a(), MED::TQuad4b::TQuad4b(), MED::TQuad8a::TQuad8a(), MED::TQuad8b::TQuad8b(), MED::TQuad9a::TQuad9a(), MED::TQuad9b::TQuad9b(), MED::TSeg2a::TSeg2a(), MED::TSeg3a::TSeg3a(), MED::TTetra10a::TTetra10a(), MED::TTetra10b::TTetra10b(), MED::TTetra4a::TTetra4a(), MED::TTetra4b::TTetra4b(), MED::TTria3a::TTria3a(), MED::TTria3b::TTria3b(), MED::TTria6a::TTria6a(), and MED::TTria6b::TTria6b().
InitFun()
virtual void MED::TShapeFun::InitFun (const TCCoordSliceArr & theRef, const TCCoordSliceArr & theGauss, TFun & theFun) const pure virtual
Implemented in MED::TSeg2a, MED::TSeg3a, MED::TTria3a, MED::TTria6a, MED::TTria3b, MED::TTria6b, MED::TQuad4a, MED::TQuad8a, MED::TQuad9a, MED::TQuad4b, MED::TQuad8b, MED::TQuad9b, MED::TTetra4a, MED::TTetra10a, MED::TTetra4b, MED::TTetra10b, MED::THexa8a, MED::THexa20a, MED::THexa27a, MED::THexa8b, MED::THexa20b, MED::TPenta6a, MED::TPenta6b, MED::TPenta15a, MED::TPenta15b, MED::TPyra5a, MED::TPyra5b, MED::TPyra13a, and MED::TPyra13b.
Referenced by Eval().
IsSatisfy()
bool MED::TShapeFun::IsSatisfy (const TCCoordSliceArr & theRefCoord) const virtual
References GetCoord(), GetNbRef(), MED::IsEqual(), and MED::TCSlice< TValueType >::size().
Referenced by Eval().
Member Data Documentation
myDim
TInt MED::TShapeFun::myDim
Referenced by GetCoord().
myNbRef
TInt MED::TShapeFun::myNbRef
myRefCoord
TFloatVector MED::TShapeFun::myRefCoord
Referenced by GetCoord(), MED::THexa20a::THexa20a(), MED::THexa20b::THexa20b(), MED::THexa27a::THexa27a(), MED::TPenta15a::TPenta15a(), MED::TPenta15b::TPenta15b(), MED::TPenta6a::TPenta6a(), MED::TPenta6b::TPenta6b(), MED::TPyra13a::TPyra13a(), MED::TPyra13b::TPyra13b(), MED::TPyra5a::TPyra5a(), and MED::TPyra5b::TPyra5b().
The documentation for this struct was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/MED_GaussUtils.hxx
FreeCAD/src/3rdParty/salomesmesh/src/SMESH/MED_GaussUtils.cpp