FreeCAD: Sketcher::SketchGeometryExtensionPy Class Reference
Sketcher::SketchGeometryExtensionPy Class Reference
The python export class for SketchGeometryExtension.
#include <SketchGeometryExtensionPy.h>
Public Types
typedef SketchGeometryExtension * PointerType
Public Types inherited from Part::GeometryExtensionPy
typedef GeometryExtension * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
SketchGeometryExtensionPy (SketchGeometryExtension *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Part::GeometryExtensionPy
GeometryExtensionPy (GeometryExtension *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * copy (PyObject *args)
implementer for the copy() method
Py::String getName (void) const
getter for the Name attribute
void setName (Py::String arg)
setter for the Name attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeometryExtension * getGeometryExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::GeometryExtensionPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_getName (PyObject *self, void *closure)
getter callback for the Name attribute
static int staticCallback_setName (PyObject *self, PyObject *value, void *closure)
setter callback for the Name attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of SketchGeometryExtensionPy.
static PyMethodDef Methods []
Methods structure of SketchGeometryExtensionPy.
static PyTypeObject Type
Type structure of SketchGeometryExtensionPy.
Static Public Attributes inherited from Part::GeometryExtensionPy
static PyGetSetDef GetterSetter []
Attribute structure of GeometryExtensionPy.
static PyMethodDef Methods []
Methods structure of GeometryExtensionPy.
static PyTypeObject Type
Type structure of GeometryExtensionPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~SketchGeometryExtensionPy ()
Protected Member Functions inherited from Part::GeometryExtensionPy
~GeometryExtensionPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * testGeometryMode (PyObject *args)
implementer for the testGeometryMode() method
PyObject * setGeometryMode (PyObject *args)
implementer for the setGeometryMode() method
static PyObject * staticCallback_testGeometryMode (PyObject *self, PyObject *args)
callback for the testGeometryMode() method
static PyObject * staticCallback_setGeometryMode (PyObject *self, PyObject *args)
callback for the setGeometryMode() method
callbacks and implementers for the python object attributes
Py::Long getId (void) const
getter for the Id attribute
void setId (Py::Long arg)
setter for the Id attribute
Py::String getInternalType (void) const
getter for the InternalType attribute
void setInternalType (Py::String arg)
setter for the InternalType attribute
Py::Boolean getBlocked (void) const
getter for the Blocked attribute
void setBlocked (Py::Boolean arg)
setter for the Blocked attribute
Py::Boolean getConstruction (void) const
getter for the Construction attribute
void setConstruction (Py::Boolean arg)
setter for the Construction attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
SketchGeometryExtension * getSketchGeometryExtensionPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getId (PyObject *self, void *closure)
getter callback for the Id attribute
static int staticCallback_setId (PyObject *self, PyObject *value, void *closure)
setter callback for the Id attribute
static PyObject * staticCallback_getInternalType (PyObject *self, void *closure)
getter callback for the InternalType attribute
static int staticCallback_setInternalType (PyObject *self, PyObject *value, void *closure)
setter callback for the InternalType attribute
static PyObject * staticCallback_getBlocked (PyObject *self, void *closure)
getter callback for the Blocked attribute
static int staticCallback_setBlocked (PyObject *self, PyObject *value, void *closure)
setter callback for the Blocked attribute
static PyObject * staticCallback_getConstruction (PyObject *self, void *closure)
getter callback for the Construction attribute
static int staticCallback_setConstruction (PyObject *self, PyObject *value, void *closure)
setter callback for the Construction attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for SketchGeometryExtension.
Member Typedef Documentation
PointerType
typedef SketchGeometryExtension* Sketcher::SketchGeometryExtensionPy::PointerType
Constructor & Destructor Documentation
~SketchGeometryExtensionPy()
SketchGeometryExtensionPy::~SketchGeometryExtensionPy () protected
SketchGeometryExtensionPy()
SketchGeometryExtensionPy::SketchGeometryExtensionPy (SketchGeometryExtension * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getBlocked()
Py::Boolean SketchGeometryExtensionPy::getBlocked (void) const
getter for the Blocked attribute
References Sketcher::GeometryMode::Blocked, getSketchGeometryExtensionPtr(), and testGeometryMode().
Referenced by staticCallback_getBlocked().
getConstruction()
Py::Boolean SketchGeometryExtensionPy::getConstruction (void) const
getter for the Construction attribute
References Sketcher::GeometryMode::Construction, getSketchGeometryExtensionPtr(), and testGeometryMode().
Referenced by staticCallback_getConstruction().
getCustomAttributes()
PyObject * SketchGeometryExtensionPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getId()
Py::Long SketchGeometryExtensionPy::getId (void) const
getter for the Id attribute
References getSketchGeometryExtensionPtr().
Referenced by staticCallback_getId().
getInternalType()
Py::String SketchGeometryExtensionPy::getInternalType (void) const
getter for the InternalType attribute
References Sketcher::SketchGeometryExtension::getInternalType(), getSketchGeometryExtensionPtr(), Sketcher::SketchGeometryExtension::internaltype2str, and Sketcher::InternalType::NumInternalGeometryType.
Referenced by staticCallback_getInternalType().
getSketchGeometryExtensionPtr()
SketchGeometryExtension * SketchGeometryExtensionPy::getSketchGeometryExtensionPtr (void) const
getter for the object handled by this class
Referenced by getBlocked(), getConstruction(), getId(), getInternalType(), PyInit(), representation(), setBlocked(), setConstruction(), setGeometryMode(), setId(), setInternalType(), and testGeometryMode().
GetType()
virtual PyTypeObject* Sketcher::SketchGeometryExtensionPy::GetType (void) virtual
Reimplemented from Part::GeometryExtensionPy.
PyInit()
int SketchGeometryExtensionPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::GeometryExtensionPy.
References getSketchGeometryExtensionPtr(), and Sketcher::SketchGeometryExtension::setId().
PyMake()
PyObject * SketchGeometryExtensionPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References SketchGeometryExtensionPy().
representation()
std::string SketchGeometryExtensionPy::representation (void) const
References Sketcher::SketchGeometryExtension::getId(), Part::GeometryExtension::getName(), Part::GeometryExtensionPy::getName(), and getSketchGeometryExtensionPtr().
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setBlocked()
void SketchGeometryExtensionPy::setBlocked (Py::Boolean arg)
setter for the Blocked attribute
References Sketcher::GeometryMode::Blocked, getSketchGeometryExtensionPtr(), and Sketcher::SketchGeometryExtension::setGeometryMode().
Referenced by staticCallback_setBlocked().
setConstruction()
void SketchGeometryExtensionPy::setConstruction (Py::Boolean arg)
setter for the Construction attribute
References Sketcher::GeometryMode::Construction, getSketchGeometryExtensionPtr(), and Sketcher::SketchGeometryExtension::setGeometryMode().
Referenced by staticCallback_setConstruction().
setCustomAttributes()
int SketchGeometryExtensionPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setGeometryMode()
PyObject * SketchGeometryExtensionPy::setGeometryMode (PyObject * args)
implementer for the setGeometryMode() method
References getSketchGeometryExtensionPtr(), and Sketcher::SketchGeometryExtension::setGeometryMode().
Referenced by staticCallback_setGeometryMode().
setId()
void SketchGeometryExtensionPy::setId (Py::Long arg)
setter for the Id attribute
References getSketchGeometryExtensionPtr(), and Sketcher::SketchGeometryExtension::setId().
Referenced by staticCallback_setId().
setInternalType()
void SketchGeometryExtensionPy::setInternalType (Py::String arg)
setter for the InternalType attribute
References Sketcher::SketchGeometryExtension::getInternalTypeFromName(), getSketchGeometryExtensionPtr(), and Sketcher::SketchGeometryExtension::setInternalType().
Referenced by staticCallback_setInternalType().
staticCallback_getBlocked()
PyObject * SketchGeometryExtensionPy::staticCallback_getBlocked (PyObject * self, void * closure) static
getter callback for the Blocked attribute
References Base::BaseExceptionFreeCADError, getBlocked(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getConstruction()
PyObject * SketchGeometryExtensionPy::staticCallback_getConstruction (PyObject * self, void * closure) static
getter callback for the Construction attribute
References Base::BaseExceptionFreeCADError, getConstruction(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getId()
PyObject * SketchGeometryExtensionPy::staticCallback_getId (PyObject * self, void * closure) static
getter callback for the Id attribute
References Base::BaseExceptionFreeCADError, getId(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getInternalType()
PyObject * SketchGeometryExtensionPy::staticCallback_getInternalType (PyObject * self, void * closure) static
getter callback for the InternalType attribute
References Base::BaseExceptionFreeCADError, getInternalType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setBlocked()
int SketchGeometryExtensionPy::staticCallback_setBlocked (PyObject * self, PyObject * value, void * closure) static
setter callback for the Blocked attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setBlocked().
staticCallback_setConstruction()
int SketchGeometryExtensionPy::staticCallback_setConstruction (PyObject * self, PyObject * value, void * closure) static
setter callback for the Construction attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setConstruction().
staticCallback_setGeometryMode()
PyObject * SketchGeometryExtensionPy::staticCallback_setGeometryMode (PyObject * self, PyObject * args) static
callback for the setGeometryMode() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setGeometryMode(), and Base::PyObjectBase::startNotify().
staticCallback_setId()
int SketchGeometryExtensionPy::staticCallback_setId (PyObject * self, PyObject * value, void * closure) static
setter callback for the Id attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setId().
staticCallback_setInternalType()
int SketchGeometryExtensionPy::staticCallback_setInternalType (PyObject * self, PyObject * value, void * closure) static
setter callback for the InternalType attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setInternalType().
staticCallback_testGeometryMode()
PyObject * SketchGeometryExtensionPy::staticCallback_testGeometryMode (PyObject * self, PyObject * args) static
callback for the testGeometryMode() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and testGeometryMode().
testGeometryMode()
PyObject * SketchGeometryExtensionPy::testGeometryMode (PyObject * args)
implementer for the testGeometryMode() method
References getSketchGeometryExtensionPtr().
Referenced by getBlocked(), getConstruction(), and staticCallback_testGeometryMode().
Member Data Documentation
GetterSetter
PyGetSetDef SketchGeometryExtensionPy::GetterSetter static
Initial value:
= {
    {"Id",
        (getter) staticCallback_getId,
        (setter) staticCallback_setId,
        "\n                Returns the Id of the SketchGeometryExtension.\n            ",
        NULL
    },
    {"InternalType",
        (getter) staticCallback_getInternalType,
        (setter) staticCallback_setInternalType,
        "\n                Returns the Id of the SketchGeometryExtension.\n            ",
        NULL
    },
    {"Blocked",
        (getter) staticCallback_getBlocked,
        (setter) staticCallback_setBlocked,
        "\n                Sets/returns whether the geometry is blocked or not.\n            ",
        NULL
    },
    {"Construction",
        (getter) staticCallback_getConstruction,
        (setter) staticCallback_setConstruction,
        "Sets/returns this geometry as a construction one, which will not be part of a later built shape.",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of SketchGeometryExtensionPy.
Methods
PyMethodDef SketchGeometryExtensionPy::Methods static
Initial value:
= {
    {"testGeometryMode",
        reinterpret_cast<PyCFunction>( staticCallback_testGeometryMode ),
        METH_VARARGS,
        "Returns a boolean indicating whether the given bit is set."
    },
    {"setGeometryMode",
        reinterpret_cast<PyCFunction>( staticCallback_setGeometryMode ),
        METH_VARARGS,
        "Sets the given bit to true/false."
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of SketchGeometryExtensionPy.
Type
PyTypeObject SketchGeometryExtensionPy::Type static
Type structure of SketchGeometryExtensionPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Sketcher/App/SketchGeometryExtensionPy.h
Sources/FreeCAD/src/Mod/Sketcher/App/SketchGeometryExtensionPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Sketcher/App/SketchGeometryExtensionPy.cpp