FreeCAD: Sketcher::ExternalGeometryExtension Class Reference
Sketcher::ExternalGeometryExtension Class Reference
#include <ExternalGeometryExtension.h>
Public Types
enum Flag {
Defining = 0 , Frozen = 1 , Detached = 2 , Missing = 3 ,
Sync = 4 , NumFlags
}
Public Member Functions
virtual std::unique_ptr< Part::GeometryExtension > copy (void) const override
ExternalGeometryExtension ()=default
virtual size_t flagSize () const override
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
virtual const std::string & getRef () const override
virtual bool isClear () const override
virtual void setFlag (int flag, bool v=true) override
virtual void setRef (const std::string &ref) override
virtual bool testFlag (int flag) const override
virtual ~ExternalGeometryExtension () override=default
Public Member Functions inherited from Part::GeometryPersistenceExtension
void Restore (Base::XMLReader &)
void Save (Base::Writer &) const
virtual ~GeometryPersistenceExtension ()=default
Public Member Functions inherited from Part::GeometryExtension
virtual std::unique_ptr< GeometryExtension > copy (void) const =0
PyObject * copyPyObject () const
const std::string & getName () const
virtual PyObject * getPyObject (void)=0
This method returns the Python wrapper for a C++ object.
virtual void notifyAttachment (Part::Geometry *)
void setName (const std::string &str)
virtual ~GeometryExtension ()=default
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static bool getFlagsFromName (std::string str, ExternalGeometryExtension::Flag &flag)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Public Attributes
static constexpr std::array< const char *, NumFlags > flag2str {{ "Defining", "Frozen", "Detached","Missing", "Sync" }}
Protected Member Functions
virtual void copyAttributes (Part::GeometryExtension *cpy) const override
virtual void restoreAttributes (Base::XMLReader &reader) override
virtual void saveAttributes (Base::Writer &writer) const override
virtual void restoreAttributes (Base::XMLReader &)
virtual void saveAttributes (Base::Writer &writer) const
Protected Member Functions inherited from Part::GeometryExtension
virtual void copyAttributes (Part::GeometryExtension *cpy) const
GeometryExtension ()
GeometryExtension (const GeometryExtension &obj)=default
GeometryExtension & operator= (const GeometryExtension &obj)=default
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Member Enumeration Documentation
Flag
enum Sketcher::ExternalGeometryExtension::Flag
Enumerator
Defining
Frozen
Detached
Missing
Sync
NumFlags
Constructor & Destructor Documentation
ExternalGeometryExtension()
Sketcher::ExternalGeometryExtension::ExternalGeometryExtension () default
Referenced by getPyObject().
~ExternalGeometryExtension()
virtual Sketcher::ExternalGeometryExtension::~ExternalGeometryExtension () override virtual default
Member Function Documentation
copy()
std::unique_ptr< Part::GeometryExtension > ExternalGeometryExtension::copy (void) const override virtual
Implements Part::GeometryExtension.
References copyAttributes(), and draftfunctions.move::move().
copyAttributes()
void ExternalGeometryExtension::copyAttributes (Part::GeometryExtension * cpy) const override protected virtual
Reimplemented from Part::GeometryExtension.
References Part::GeometryExtension::copyAttributes().
Referenced by copy().
flagSize()
virtual size_t Sketcher::ExternalGeometryExtension::flagSize () const override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
getFlagsFromName()
bool ExternalGeometryExtension::getFlagsFromName (std::string str, ExternalGeometryExtension::Flag & flag) static
References flag2str.
getPyObject()
PyObject * ExternalGeometryExtension::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
References ExternalGeometryExtension().
getRef()
virtual const std::string & Sketcher::ExternalGeometryExtension::getRef () const override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
isClear()
virtual bool Sketcher::ExternalGeometryExtension::isClear () const override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
restoreAttributes()
void ExternalGeometryExtension::restoreAttributes (Base::XMLReader & reader) override protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
References Base::XMLReader::getAttribute(), and Part::GeometryPersistenceExtension::restoreAttributes().
saveAttributes()
void ExternalGeometryExtension::saveAttributes (Base::Writer & writer) const override protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
References Part::GeometryPersistenceExtension::saveAttributes(), and Base::Writer::Stream().
setFlag()
virtual void Sketcher::ExternalGeometryExtension::setFlag (int flag, bool v = true) override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
setRef()
virtual void Sketcher::ExternalGeometryExtension::setRef (const std::string & ref) override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
testFlag()
virtual bool Sketcher::ExternalGeometryExtension::testFlag (int flag) const override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Member Data Documentation
flag2str
constexpr std::array< const char *, ExternalGeometryExtension::NumFlags > ExternalGeometryExtension::flag2str {{ "Defining", "Frozen", "Detached","Missing", "Sync" }} static constexpr
Referenced by getFlagsFromName().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/App/ExternalGeometryExtension.h
FreeCAD/src/Mod/Sketcher/App/ExternalGeometryExtension.cpp