FreeCAD: Base::ConsoleOutput Class Reference
Base::ConsoleOutput Class Reference
Public Member Functions
void customEvent (QEvent *ev)
Static Public Member Functions
static void destruct ()
static ConsoleOutput * getInstance ()
Member Function Documentation
customEvent()
void Base::ConsoleOutput::customEvent (QEvent * ev)
References Base::Console(), Base::ConsoleEvent::msg, Base::ConsoleEvent::msgtype, Base::ConsoleSingleton::MsgType_Err, Base::ConsoleSingleton::MsgType_Log, Base::ConsoleSingleton::MsgType_Txt, Base::ConsoleSingleton::MsgType_Wrn, Base::ConsoleSingleton::NotifyError(), Base::ConsoleSingleton::NotifyLog(), Base::ConsoleSingleton::NotifyMessage(), and Base::ConsoleSingleton::NotifyWarning().
destruct()
static void Base::ConsoleOutput::destruct () static
Referenced by Base::ConsoleSingleton::~ConsoleSingleton().
getInstance()
static ConsoleOutput* Base::ConsoleOutput::getInstance () static
Referenced by Base::ConsoleSingleton::SetConnectionMode().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Base/Console.cpp