FreeCAD: Ui_TaskPostClip Class Reference
Ui_TaskPostClip Class Reference
#include <ui_TaskPostClip.h>
Public Member Functions
void retranslateUi (QWidget *TaskPostClip)
void setupUi (QWidget *TaskPostClip)
Public Attributes
QWidget * Container
QToolButton * CreateButton
QCheckBox * CutCells
QComboBox * FunctionBox
QHBoxLayout * horizontalLayout
QHBoxLayout * horizontalLayout_2
QCheckBox * InsideOut
QFrame * line
QFrame * line_2
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void Ui_TaskPostClip::retranslateUi (QWidget * TaskPostClip)
References CreateButton, CutCells, InsideOut, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Ui_TaskPostClip::setupUi (QWidget * TaskPostClip)
References Container, CreateButton, CutCells, FunctionBox, horizontalLayout, horizontalLayout_2, InsideOut, line, line_2, retranslateUi(), and verticalLayout.
Member Data Documentation
Container
QWidget* Ui_TaskPostClip::Container
Referenced by setupUi().
CreateButton
QToolButton* Ui_TaskPostClip::CreateButton
Referenced by retranslateUi(), and setupUi().
CutCells
QCheckBox* Ui_TaskPostClip::CutCells
Referenced by retranslateUi(), and setupUi().
FunctionBox
QComboBox* Ui_TaskPostClip::FunctionBox
Referenced by setupUi().
horizontalLayout
QHBoxLayout* Ui_TaskPostClip::horizontalLayout
Referenced by setupUi().
horizontalLayout_2
QHBoxLayout* Ui_TaskPostClip::horizontalLayout_2
Referenced by setupUi().
InsideOut
QCheckBox* Ui_TaskPostClip::InsideOut
Referenced by retranslateUi(), and setupUi().
line
QFrame* Ui_TaskPostClip::line
Referenced by Plot.Line::getp(), Plot.Line::setp(), setupUi(), draftguitools.gui_trackers.wireTracker::update(), and draftviewproviders.view_label.ViewProviderLabel::updateData().
line_2
QFrame* Ui_TaskPostClip::line_2
Referenced by setupUi().
verticalLayout
QVBoxLayout* Ui_TaskPostClip::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Fem/Gui/ui_TaskPostClip.h