FreeCAD: MeshGui::SoFCMeshObjectBoundary Class Reference
MeshGui::SoFCMeshObjectBoundary Class Reference
#include <SoFCMeshObject.h>
Public Member Functions
SoFCMeshObjectBoundary ()
Static Public Member Functions
static void initClass ()
Protected Member Functions
virtual void computeBBox (SoAction *action, SbBox3f &box, SbVec3f &center)
Sets the bounding box of the mesh to box and its center to center.
virtual void generatePrimitives (SoAction *action)
virtual void getPrimitiveCount (SoGetPrimitiveCountAction *action)
Adds the number of the triangles to the SoGetPrimitiveCountAction.
virtual void GLRender (SoGLRenderAction *action)
Renders the open edges only.
Constructor & Destructor Documentation
SoFCMeshObjectBoundary()
SoFCMeshObjectBoundary::SoFCMeshObjectBoundary ()
Member Function Documentation
computeBBox()
void SoFCMeshObjectBoundary::computeBBox (SoAction * action, SbBox3f & box, SbVec3f & center) protected virtual
Sets the bounding box of the mesh to box and its center to center.
References Base::BoundBox3< _Precision >::Add(), MeshGui::SoFCMeshObjectElement::get(), Base::BoundBox3< _Precision >::GetCenter(), Base::BoundBox3< _Precision >::MaxX, Base::BoundBox3< _Precision >::MaxY, Base::BoundBox3< _Precision >::MaxZ, Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, and Base::BoundBox3< _Precision >::MinZ.
generatePrimitives()
void SoFCMeshObjectBoundary::generatePrimitives (SoAction * action) protected virtual
References MeshGui::SoFCMeshObjectElement::get().
getPrimitiveCount()
void SoFCMeshObjectBoundary::getPrimitiveCount (SoGetPrimitiveCountAction * action) protected virtual
Adds the number of the triangles to the SoGetPrimitiveCountAction.
References MeshGui::SoFCMeshObjectElement::get().
GLRender()
void SoFCMeshObjectBoundary::GLRender (SoGLRenderAction * action) protected virtual
Renders the open edges only.
References MeshGui::SoFCMeshObjectElement::get().
initClass()
void SoFCMeshObjectBoundary::initClass (void) static
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCMeshObject.h
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCMeshObject.cpp