FreeCAD: PropertyListDialog Class Reference
PropertyListDialog Class Reference
Public Member Functions
void accept ()
PropertyListDialog (int type, QWidget *parent)
Constructor & Destructor Documentation
PropertyListDialog()
PropertyListDialog::PropertyListDialog (int type, QWidget * parent)
Member Function Documentation
accept()
void PropertyListDialog::accept (void)
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/Widgets.cpp