FreeCAD: GCS::ConstraintPerpendicular Class Reference
GCS::ConstraintPerpendicular Class Reference
#include <Constraints.h>
Public Member Functions
ConstraintPerpendicular (Line &l1, Line &l2)
ConstraintPerpendicular (Point &l1p1, Point &l1p2, Point &l2p1, Point &l2p2)
virtual double error ()
virtual ConstraintType getTypeId ()
virtual double grad (double *)
virtual void rescale (double coef=1.)
Public Member Functions inherited from GCS::Constraint
Constraint ()
virtual double error ()
int findParamInPvec (double *param)
int getTag ()
virtual ConstraintType getTypeId ()
virtual double grad (double *)
bool isDriving () const
virtual double maxStep (MAP_pD_D &dir, double lim=1.)
VEC_pD params ()
void redirectParams (MAP_pD_pD redirectionmap)
virtual void rescale (double coef=1.)
void revertParams ()
void setDriving (bool isdriving)
void setTag (int tagId)
virtual ~Constraint ()
Constructor & Destructor Documentation
ConstraintPerpendicular() [1/2]
GCS::ConstraintPerpendicular::ConstraintPerpendicular (Line & l1, Line & l2)
References rescale().
ConstraintPerpendicular() [2/2]
GCS::ConstraintPerpendicular::ConstraintPerpendicular (Point & l1p1, Point & l1p2, Point & l2p1, Point & l2p2)
References rescale(), GCS::Point::x, and GCS::Point::y.
Member Function Documentation
error()
double GCS::ConstraintPerpendicular::error () virtual
Reimplemented from GCS::Constraint.
Referenced by femmesh.gmshtools.GmshTools::read_and_set_new_mesh(), FreeCADInit.FCADLogger::report(), and femmesh.gmshtools.GmshTools::run_gmsh_with_geo().
getTypeId()
ConstraintType GCS::ConstraintPerpendicular::getTypeId (void) virtual
Reimplemented from GCS::Constraint.
References GCS::Perpendicular.
grad()
double GCS::ConstraintPerpendicular::grad (double * param) virtual
Reimplemented from GCS::Constraint.
rescale()
void GCS::ConstraintPerpendicular::rescale (double coef = 1.) virtual
Reimplemented from GCS::Constraint.
Referenced by ConstraintPerpendicular().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/App/planegcs/Constraints.h
FreeCAD/src/Mod/Sketcher/App/planegcs/Constraints.cpp