FreeCAD: TechDrawGui::TaskProjection Class Reference
TechDrawGui::TaskProjection Class Reference
#include <TaskProjection.h>
Public Member Functions
bool accept ()
virtual bool isAllowedAlterDocument (void) const
bool reject ()
TaskProjection ()
~TaskProjection ()
Constructor & Destructor Documentation
TaskProjection()
TaskProjection::TaskProjection ()
~TaskProjection()
TaskProjection::~TaskProjection ()
Member Function Documentation
accept()
bool TaskProjection::accept (void)
References Gui::Application::activeDocument(), Gui::Command::addModule(), Gui::Command::commitCommand(), Gui::Command::Doc, Base::BaseClass::getClassTypeId(), Gui::getMainWindow(), Gui::Document::getMDIViewsOfType(), Gui::SelectionSingleton::getObjectsOfType(), Gui::Application::Instance, Gui::Command::openCommand(), Gui::Selection(), Gui::Command::updateActive(), and OfflineRenderingUtils::viewer().
Referenced by TechDrawGui::TaskDlgProjection::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
isAllowedAlterDocument()
virtual bool TechDrawGui::TaskProjection::isAllowedAlterDocument (void) const virtual
reject()
bool TaskProjection::reject (void)
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), TechDrawGui::TaskDlgProjection::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/TaskProjection.h
FreeCAD/src/Mod/TechDraw/Gui/TaskProjection.cpp