FreeCAD: Gui::DocumentObserver Class Reference
Gui::DocumentObserver Class Reference
The DocumentObserver class simplifies the step to write classes that listen to what happens inside a document.
#include <DocumentObserver.h>
Public Member Functions
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
Detailed Description
The DocumentObserver class simplifies the step to write classes that listen to what happens inside a document.
This is very useful for classes that needs to be notified when an observed object has changed.
Author
Werner Mayer
Constructor & Destructor Documentation
DocumentObserver() [1/2]
DocumentObserver::DocumentObserver ()
Constructor.
DocumentObserver() [2/2]
DocumentObserver::DocumentObserver (Document * doc)
References attachDocument().
~DocumentObserver()
DocumentObserver::~DocumentObserver () virtual
Member Function Documentation
attachDocument()
void DocumentObserver::attachDocument (Document * doc)
Attaches to another document, the old document is not longer observed then.
References draftgeoutils.faces::bind(), and detachDocument().
Referenced by DocumentObserver(), SurfaceGui::FillingPanel::setEditedObject(), SurfaceGui::FillingEdgePanel::setEditedObject(), SurfaceGui::FillingVertexPanel::setEditedObject(), SurfaceGui::GeomFillSurface::setEditedObject(), SurfaceGui::SectionsPanel::setEditedObject(), PartDesignGui::TaskBoxPrimitives::TaskBoxPrimitives(), PartDesignGui::TaskFeatureParameters::TaskFeatureParameters(), and PartDesignGui::TaskFeaturePick::TaskFeaturePick().
detachDocument()
void DocumentObserver::detachDocument ()
Detaches from the current document, the document is not longer observed then.
Referenced by attachDocument().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DocumentObserver.h
FreeCAD/src/Gui/DocumentObserver.cpp