FreeCAD: PartDesignGui::TaskDraftParameters Class Reference
PartDesignGui::TaskDraftParameters Class Reference
#include <TaskDraftParameters.h>
Public Member Functions
double getAngle (void) const
const std::vector< std::string > getFaces (void) const
void getLine (App::DocumentObject *&obj, std::vector< std::string > &sub) const
void getPlane (App::DocumentObject *&obj, std::vector< std::string > &sub) const
bool getReversed (void) const
TaskDraftParameters (ViewProviderDressUp *DressUpView, QWidget *parent=0)
~TaskDraftParameters ()
Public Member Functions inherited from PartDesignGui::TaskDressUpParameters
virtual void apply ()
Apply the changes made to the object to it.
Part::Feature * getBase (void) const
const std::vector< std::string > getReferences (void) const
int getTransactionID () const
void hideObject ()
void setupTransaction ()
void showObject ()
TaskDressUpParameters (ViewProviderDressUp *DressUpView, bool selectEdges, bool selectFaces, QWidget *parent=0)
virtual ~TaskDressUpParameters ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (QWidget *parent=0)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (QWidget *parent=0)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockConnection (bool block)
void detachSelection ()
Detaches from the selection.
bool isConnectionAttached () const
bool isConnectionBlocked () const
SelectionObserver (bool attach=true, int resolve=1)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, int resolve=1)
Constructor.
virtual ~SelectionObserver ()
Protected Member Functions
void changeEvent (QEvent *e)
virtual void clearButtons (const selectionModes notThis)
bool event (QEvent *e)
virtual void onSelectionChanged (const Gui::SelectionChanges &msg)
Protected Member Functions inherited from PartDesignGui::TaskDressUpParameters
void exitSelectionMode ()
ViewProviderDressUp * getDressUpView () const
bool KeyEvent (QEvent *e)
bool referenceSelected (const Gui::SelectionChanges &msg)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Types inherited from PartDesignGui::TaskDressUpParameters
enum selectionModes {
none, refAdd, refRemove, plane,
line
}
Protected Slots inherited from PartDesignGui::TaskDressUpParameters
void createDeleteAction (QListWidget *parentList, QWidget *parentButton)
void doubleClicked (QListWidgetItem *item)
void itemClickedTimeout ()
void onButtonRefAdd (const bool checked)
void onButtonRefRemove (const bool checked)
virtual void onRefDeleted (void)=0
void setSelection (QListWidgetItem *current)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Static Protected Member Functions inherited from PartDesignGui::TaskDressUpParameters
static void removeItemFromListWidget (QListWidget *widget, const char *itemstr)
Protected Attributes inherited from PartDesignGui::TaskDressUpParameters
bool allowEdges
bool allowFaces
QAction * deleteAction
ViewProviderDressUp * DressUpView
QWidget * proxy
selectionModes selectionMode
int transactionID
bool wasDoubleClicked = false
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskDraftParameters()
TaskDraftParameters::TaskDraftParameters (ViewProviderDressUp * DressUpView, QWidget * parent = 0)
References PartDesign::Draft::Angle, PartDesign::DressUp::Base, draftgeoutils.intersections::connect(), PartDesignGui::TaskDressUpParameters::createDeleteAction(), PartDesignGui::TaskDressUpParameters::deleteAction, PartDesignGui::TaskDressUpParameters::doubleClicked(), PartDesignGui::TaskDressUpParameters::DressUpView, Gui::ViewProviderDocumentObject::getObject(), PartDesignGui::getRefStr(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), App::PropertyBool::getValue(), App::PropertyQuantity::getValue(), QSint::ActionGroup::groupLayout(), PartDesign::Draft::NeutralPlane, PartDesignGui::TaskDressUpParameters::onButtonRefAdd(), PartDesignGui::TaskDressUpParameters::onButtonRefRemove(), PartDesignGui::TaskDressUpParameters::proxy, PartDesign::Draft::PullDirection, PartDesign::Draft::Reversed, and PartDesignGui::TaskDressUpParameters::setSelection().
~TaskDraftParameters()
TaskDraftParameters::~TaskDraftParameters ()
References Gui::SelectionSingleton::clearSelection(), Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
changeEvent()
void TaskDraftParameters::changeEvent (QEvent * e) protected
References PartDesignGui::TaskDressUpParameters::proxy.
clearButtons()
void TaskDraftParameters::clearButtons (const selectionModes notThis) protected virtual
Implements PartDesignGui::TaskDressUpParameters.
References PartDesignGui::TaskDressUpParameters::DressUpView, PartDesignGui::ViewProviderDressUp::highlightReferences(), PartDesignGui::TaskDressUpParameters::line, PartDesignGui::TaskDressUpParameters::plane, PartDesignGui::TaskDressUpParameters::refAdd, and PartDesignGui::TaskDressUpParameters::refRemove.
Referenced by onSelectionChanged().
event()
bool TaskDraftParameters::event (QEvent * e) protected
References PartDesignGui::TaskDressUpParameters::KeyEvent().
getAngle()
double TaskDraftParameters::getAngle (void) const
Referenced by PartDesignGui::TaskDlgDraftParameters::accept(), and PathScripts.PathDressupDogbone.Chord::getAngleXY().
getFaces()
const std::vector<std::string> PartDesignGui::TaskDraftParameters::getFaces (void) const
getLine()
void TaskDraftParameters::getLine (App::DocumentObject *& obj, std::vector< std::string > & sub) const
References PartDesignGui::TaskDressUpParameters::DressUpView, App::DocumentObject::getDocument(), App::Document::getObject(), and Gui::ViewProviderDocumentObject::getObject().
Referenced by PartDesignGui::TaskDlgDraftParameters::accept().
getPlane()
void TaskDraftParameters::getPlane (App::DocumentObject *& obj, std::vector< std::string > & sub) const
References PartDesignGui::TaskDressUpParameters::DressUpView, App::DocumentObject::getDocument(), App::Document::getObject(), and Gui::ViewProviderDocumentObject::getObject().
Referenced by PartDesignGui::TaskDlgDraftParameters::accept().
getReversed()
bool TaskDraftParameters::getReversed (void) const
Referenced by PartDesignGui::TaskDlgDraftParameters::accept().
onSelectionChanged()
void TaskDraftParameters::onSelectionChanged (const Gui::SelectionChanges & msg) protected virtual
Implements Gui::SelectionObserver.
References Gui::SelectionChanges::AddSelection, clearButtons(), Gui::SelectionSingleton::clearSelection(), PartDesignGui::TaskDressUpParameters::deleteAction, PartDesignGui::TaskDressUpParameters::DressUpView, PartDesignGui::TaskDressUpParameters::exitSelectionMode(), App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesignGui::getReferencedSelection(), PartDesignGui::getRefStr(), PartDesignGui::ViewProviderDressUp::highlightReferences(), PartDesignGui::TaskDressUpParameters::line, PartDesign::Draft::NeutralPlane, PartDesignGui::TaskDressUpParameters::none, PartDesignGui::TaskDressUpParameters::plane, PartDesign::Draft::PullDirection, App::Document::recomputeFeature(), PartDesignGui::TaskDressUpParameters::refAdd, PartDesignGui::TaskDressUpParameters::referenceSelected(), PartDesignGui::TaskDressUpParameters::removeItemFromListWidget(), Gui::Selection(), PartDesignGui::TaskDressUpParameters::selectionMode, PartDesignGui::TaskDressUpParameters::setupTransaction(), and App::PropertyLinkSub::setValue().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/PartDesign/Gui/TaskDraftParameters.h
Sources/FreeCAD/src/Mod/PartDesign/Gui/TaskDraftParameters.cpp