FreeCAD: SMESH::Controls::BelongToMeshGroup Class Reference
SMESH::Controls::BelongToMeshGroup Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
BelongToMeshGroup ()
const SMESHDS_GroupBase * GetGroup () const
virtual SMDSAbs_ElementType GetType () const
virtual bool IsSatisfy (long theElementId)
void SetGroup (SMESHDS_GroupBase *g)
virtual void SetMesh (const SMDS_Mesh *theMesh)
void SetStoreName (const std::string &sn)
virtual SMDSAbs_ElementType GetType () const =0
virtual bool IsSatisfy (long theElementId)=0
Public Member Functions inherited from SMESH::Controls::Functor
virtual SMDSAbs_ElementType GetType () const =0
virtual void SetMesh (const SMDS_Mesh *theMesh)=0
virtual ~Functor ()
Constructor & Destructor Documentation
BelongToMeshGroup()
BelongToMeshGroup::BelongToMeshGroup ()
Member Function Documentation
GetGroup()
const SMESHDS_GroupBase * SMESH::Controls::BelongToMeshGroup::GetGroup () const
GetType()
SMDSAbs_ElementType BelongToMeshGroup::GetType () const virtual
Implements SMESH::Controls::Predicate.
References SMESHDS_GroupBase::GetType().
IsSatisfy()
bool BelongToMeshGroup::IsSatisfy (long theElementId) virtual
Implements SMESH::Controls::Predicate.
References SMESHDS_GroupBase::Contains().
SetGroup()
void BelongToMeshGroup::SetGroup (SMESHDS_GroupBase * g)
SetMesh()
void BelongToMeshGroup::SetMesh (const SMDS_Mesh * theMesh) virtual
Implements SMESH::Controls::Functor.
References SMESHDS_GroupBase::GetMesh(), and SMESHDS_GroupBase::IsEmpty().
SetStoreName()
void BelongToMeshGroup::SetStoreName (const std::string & sn)
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp