FreeCAD: SurfaceGui::TaskFilling Class Reference
SurfaceGui::TaskFilling Class Reference
#include <TaskFilling.h>
Public Member Functions
bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual QDialogButtonBox::StandardButtons getStandardButtons () const
tells the framework which buttons are wished for the dialog
void open ()
is called by the framework when the dialog is opened
bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setEditedObject (Surface::Filling *obj)
TaskFilling (ViewProviderFilling *vp, Surface::Filling *obj)
~TaskFilling ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Constructor & Destructor Documentation
TaskFilling()
SurfaceGui::TaskFilling::TaskFilling (ViewProviderFilling * vp, Surface::Filling * obj)
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, QSint::ActionGroup::groupLayout(), and Gui::TaskView::TaskBox::hideGroupBox().
~TaskFilling()
SurfaceGui::TaskFilling::~TaskFilling ()
Member Function Documentation
accept()
bool SurfaceGui::TaskFilling::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References SurfaceGui::FillingPanel::accept(), Gui::Command::commitCommand(), Gui::Command::Gui, SurfaceGui::FillingEdgePanel::reject(), SurfaceGui::FillingVertexPanel::reject(), and Gui::Command::updateActive().
getStandardButtons()
virtual QDialogButtonBox::StandardButtons SurfaceGui::TaskFilling::getStandardButtons (void) const virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
open()
void SurfaceGui::TaskFilling::open () virtual
is called by the framework when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
References SurfaceGui::FillingPanel::open(), SurfaceGui::FillingEdgePanel::open(), and SurfaceGui::FillingVertexPanel::open().
reject()
bool SurfaceGui::TaskFilling::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Command::abortCommand(), Gui::Command::Gui, SurfaceGui::FillingPanel::reject(), SurfaceGui::FillingEdgePanel::reject(), SurfaceGui::FillingVertexPanel::reject(), and Gui::Command::updateActive().
setEditedObject()
void SurfaceGui::TaskFilling::setEditedObject (Surface::Filling * obj)
References SurfaceGui::FillingPanel::setEditedObject().
Referenced by SurfaceGui::ViewProviderFilling::setEdit().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Surface/Gui/TaskFilling.h
Sources/FreeCAD/src/Mod/Surface/Gui/TaskFilling.cpp