FreeCAD: SMESH::Controls::AspectRatio Class Reference
SMESH::Controls::AspectRatio Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
virtual double GetBadRate (double Value, int nbNodes) const
virtual SMDSAbs_ElementType GetType () const
virtual double GetValue (const TSequenceOfXYZ &thePoints)
virtual double GetValue (long theElementId)
Public Member Functions inherited from SMESH::Controls::NumericalFunctor
void GetHistogram (int nbIntervals, std::vector< int > &nbEvents, std::vector< double > &funValues, const std::vector< int > &elements, const double *minmax=0, const bool isLogarithmic=false)
Return histogram of functor values.
bool GetPoints (const int theId, TSequenceOfXYZ &theRes) const
long GetPrecision () const
NumericalFunctor ()
double Round (const double &value)
virtual void SetMesh (const SMDS_Mesh *theMesh)
void SetPrecision (const long thePrecision)
Public Member Functions inherited from SMESH::Controls::Functor
~Functor ()
Additional Inherited Members
Static Public Member Functions inherited from SMESH::Controls::NumericalFunctor
static bool GetPoints (const SMDS_MeshElement *theElem, TSequenceOfXYZ &theRes)
Protected Attributes inherited from SMESH::Controls::NumericalFunctor
const SMDS_MeshElement * myCurrElement
const SMDS_Mesh * myMesh
long myPrecision
double myPrecisionValue
Member Function Documentation
GetBadRate()
double AspectRatio::GetBadRate (double Value, int nbNodes) const virtual
Implements SMESH::Controls::NumericalFunctor.
GetType()
SMDSAbs_ElementType AspectRatio::GetType () const virtual
Implements SMESH::Controls::NumericalFunctor.
GetValue() [1/2]
double AspectRatio::GetValue (const TSequenceOfXYZ & thePoints) virtual
Reimplemented from SMESH::Controls::NumericalFunctor.
References SMESH::Controls::TSequenceOfXYZ::size().
GetValue() [2/2]
double AspectRatio::GetValue (long theElementId) virtual
Reimplemented from SMESH::Controls::NumericalFunctor.
References SMDS_Mesh::FindElement(), SMDS_MeshElement::getMeshId(), SMESH::Controls::NumericalFunctor::GetPoints(), SMDS_MeshElement::getVtkId(), SMDS_MeshElement::GetVtkType(), SMESH::Controls::NumericalFunctor::myCurrElement, SMESH::Controls::NumericalFunctor::myMesh, and SMESH::Controls::NumericalFunctor::Round().
Referenced by SMESH::Controls::AspectRatio3D::GetValue(), and SMESH_MeshEditor::Smooth().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp