FreeCAD: DriverMED_R_SMESHDS_Mesh Class Reference
DriverMED_R_SMESHDS_Mesh Class Reference
#include <DriverMED_R_SMESHDS_Mesh.h>
Public Member Functions
void CreateAllSubMeshes ()
void GetGroup (SMESHDS_Group *theGroup)
std::list< TNameAndType > GetGroupNamesAndTypes ()
std::list< std::string > GetMeshNames (Status &theStatus)
void GetSubMesh (SMESHDS_SubMesh *theSubMesh, const int theId)
virtual Status Perform ()
Reads a med file.
void SetMeshName (std::string theMeshName)
Stores a mesh name.
Public Member Functions inherited from Driver_SMESHDS_Mesh
Driver_SMESHDS_Mesh ()
void SetMesh (SMESHDS_Mesh *theMesh)
Public Member Functions inherited from Driver_Mesh
Driver_Mesh ()
virtual SMESH_ComputeErrorPtr GetError ()
Return a structure containing description of errors.
virtual std::string GetMeshName () const
virtual Status Perform ()=0
virtual void SetFile (const std::string &theFileName)
void SetMeshId (int theMeshId)
virtual void SetMeshName (const std::string &theMeshName)
virtual void SetOption (const std::string &optionName, const std::string &optionValue)
virtual ~Driver_Mesh ()
Additional Inherited Members
Public Types inherited from Driver_Mesh
enum Status {
DRS_OK , DRS_EMPTY , DRS_WARN_RENUMBER , DRS_WARN_SKIP_ELEM ,
DRS_WARN_DESCENDING , DRS_FAIL
}
Protected Member Functions inherited from Driver_Mesh
Status addMessage (const std::string &msg, const bool isFatal=false)
Stores an error message.
Protected Attributes inherited from Driver_SMESHDS_Mesh
SMESHDS_Mesh * myMesh
Protected Attributes inherited from Driver_Mesh
std::vector< std::string > myErrorMessages
std::string myFile
int myMeshId
std::string myMeshName
Status myStatus
Member Function Documentation
CreateAllSubMeshes()
void DriverMED_R_SMESHDS_Mesh::CreateAllSubMeshes ()
References SMESHDS_Mesh::IndexToShape(), Driver_SMESHDS_Mesh::myMesh, SMESHDS_Mesh::SetMeshElementOnShape(), SMESHDS_Mesh::SetNodeInVolume(), SMESHDS_Mesh::SetNodeOnEdge(), SMESHDS_Mesh::SetNodeOnFace(), and SMESHDS_Mesh::SetNodeOnVertex().
GetGroup()
void DriverMED_R_SMESHDS_Mesh::GetGroup (SMESHDS_Group * theGroup)
References SMDS_MeshGroup::Add(), SMESHDS_GroupBase::GetStoreName(), SMESHDS_GroupBase::GetType(), SMDS_MeshElement::GetType(), SMESHDS_GroupBase::SetColorGroup(), and SMESHDS_Group::SMDSGroup().
Referenced by SMESH_Mesh::MEDToMesh().
GetGroupNamesAndTypes()
list< TNameAndType > DriverMED_R_SMESHDS_Mesh::GetGroupNamesAndTypes ()
Referenced by SMESH_Mesh::MEDToMesh().
GetMeshNames()
list< string > DriverMED_R_SMESHDS_Mesh::GetMeshNames (Status & theStatus)
References MED::CrWrapper(), Driver_Mesh::DRS_FAIL, Driver_Mesh::DRS_OK, and Driver_Mesh::myFile.
GetSubMesh()
void DriverMED_R_SMESHDS_Mesh::GetSubMesh (SMESHDS_SubMesh * theSubMesh, const int theId)
References SMESHDS_SubMesh::AddElement(), and SMESHDS_SubMesh::AddNode().
Perform()
Driver_Mesh::Status DriverMED_R_SMESHDS_Mesh::Perform () virtual
Reads a med file.
Implements Driver_Mesh.
References SMESHDS_Mesh::Add0DElement(), SMESHDS_Mesh::Add0DElementWithID(), SMESHDS_Mesh::AddBall(), SMESHDS_Mesh::AddBallWithID(), SMESHDS_Mesh::AddEdge(), SMESHDS_Mesh::AddEdgeWithID(), SMESHDS_Mesh::AddFace(), SMESHDS_Mesh::AddFaceWithID(), Driver_Mesh::addMessage(), SMESHDS_Mesh::AddNodeWithID(), SMESHDS_Mesh::AddPolygonalFace(), SMESHDS_Mesh::AddPolygonalFaceWithID(), SMESHDS_Mesh::AddPolyhedralVolume(), SMESHDS_Mesh::AddPolyhedralVolumeWithID(), SMESHDS_Mesh::AddQuadPolygonalFace(), SMESHDS_Mesh::AddQuadPolygonalFaceWithID(), SMESHDS_Mesh::AddVolume(), SMESHDS_Mesh::AddVolumeWithID(), SMDS_UnstructuredGrid::AllocateDiameters(), DriverMED::buildMeshGrille(), DriverMED::checkFamilyID(), SMESHDS_Mesh::compactMesh(), MED::CrWrapper(), Driver_Mesh::DRS_EMPTY, Driver_Mesh::DRS_FAIL, Driver_Mesh::DRS_OK, Driver_Mesh::DRS_WARN_DESCENDING, Driver_Mesh::DRS_WARN_RENUMBER, Driver_Mesh::DRS_WARN_SKIP_ELEM, MED::eDESC, MED::eFAUX, MED::eHEXA20, MED::eHEXA27, MED::eHEXA8, MED::eNOD, MED::eNOEUD, MED::eOCTA12, MED::ePENTA15, MED::ePENTA6, MED::ePOINT1, MED::ePOLYEDRE, MED::ePOLYGON2, MED::ePOLYGONE, MED::ePYRA13, MED::ePYRA5, MED::eQUAD4, MED::eQUAD8, MED::eQUAD9, MED::eSEG2, MED::eSEG3, MED::eSTRUCT_ELEMENT, MED::eSTRUCTURE, MED::eTETRA10, MED::eTETRA4, MED::eTRIA3, MED::eTRIA6, MED::eTRIA7, MED::eVRAI, SMDS_Mesh::FindNode(), MED::GetCoordHelper(), SMDS_Mesh::getGrid(), SMDS_MeshElement::GetType(), SMDS_Mesh::MaxElementID(), Driver_Mesh::myFile, Driver_SMESHDS_Mesh::myMesh, Driver_Mesh::myMeshId, and MED::TCSlice< TValueType >::size().
Referenced by SMESH_Mesh::MEDToMesh().
SetMeshName()
void DriverMED_R_SMESHDS_Mesh::SetMeshName (std::string theMeshName)
Stores a mesh name.
Referenced by SMESH_Mesh::MEDToMesh().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/DriverMED_R_SMESHDS_Mesh.h
FreeCAD/src/3rdParty/salomesmesh/src/SMESH/DriverMED_R_SMESHDS_Mesh.cpp