FreeCAD: NETGENPlugin_NETGEN_3D Class Reference
NETGENPlugin_NETGEN_3D Class Reference
#include <NETGENPlugin_NETGEN_3D.hxx>
Public Member Functions
virtual void CancelCompute ()
Sets _computeCanceled to true. It's usage depends on implementation of a particular mesher.
virtual bool CheckHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, SMESH_Hypothesis::Hypothesis_Status &aStatus)
Check hypothesis definition to mesh a shape.
virtual bool Compute (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape)
virtual bool Compute (SMESH_Mesh &aMesh, SMESH_MesherHelper *aHelper)
Compute tetrahedral mesh from 2D mesh without geometry.
virtual bool Evaluate (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, MapShapeNbElems &aResMap)
evaluates size of prospective mesh on a shape
virtual double GetProgress () const
Return Compute progress.
NETGENPlugin_NETGEN_3D (int hypId, int studyId, SMESH_Gen *gen)
virtual ~NETGENPlugin_NETGEN_3D ()
Public Member Functions inherited from SMESH_3D_Algo
SMESH_3D_Algo (int hypId, int studyId, SMESH_Gen *gen)
SMESH_3D_Algo (int hypId, int studyId, SMESH_Gen *gen)
virtual ~SMESH_3D_Algo ()
Public Member Functions inherited from SMESH_Algo
virtual void CancelCompute ()
Sets _computeCanceled to true. It's usage depends on implementation of a particular mesher.
virtual bool CheckHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, SMESH_Hypothesis::Hypothesis_Status &aStatus)=0
Check hypothesis definition to mesh a shape.
virtual bool Compute (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape)=0
Computes mesh on a shape.
virtual bool Compute (SMESH_Mesh &aMesh, SMESH_MesherHelper *aHelper)
Computes mesh without geometry.
virtual bool Evaluate (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, MapShapeNbElems &aResMap)=0
evaluates size of prospective mesh on a shape
const std::list< const SMESHDS_Hypothesis * > & GetAppliedHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, const bool ignoreAuxiliary=true) const
Returns a list of compatible hypotheses assigned to a shape in a mesh.
const SMESH_HypoFilter * GetCompatibleHypoFilter (const bool ignoreAuxiliary) const
Returns the filter recognizing only compatible hypotheses.
const std::vector< std::string > & GetCompatibleHypothesis ()
Returns all types of compatible hypotheses.
SMESH_ComputeErrorPtr GetComputeError () const
return compute error
const Features & GetFeatures () const
virtual double GetProgress () const
If possible, returns progress of computation [0.,1.].
double GetProgressByTic () const
Return compute progress by nb of calls of this method.
virtual const std::list< const SMESHDS_Hypothesis * > & GetUsedHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, const bool ignoreAuxiliary=true) const
Returns a list of compatible hypotheses used to mesh a shape.
void InitComputeError ()
initialize compute error etc. before call of Compute()
virtual std::istream & LoadFrom (std::istream &load)
Loads nothing from a stream.
bool NeedDiscreteBoundary () const
bool NeedLowerHyps (int dim) const
bool NeedShape () const
int NumberOfPoints (SMESH_Mesh &aMesh, const TopoDS_Wire &W)
bool OnlyUnaryInput () const
virtual std::ostream & SaveTo (std::ostream &save)
Saves nothing in a stream.
virtual void SetEventListener (SMESH_subMesh *subMesh)
Sets event listener to submeshes if necessary.
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)
Just return false as the algorithm does not hold parameters values.
SMESH_Algo (int hypId, int studyId, SMESH_Gen *gen)
Creates algorithm.
std::vector< SMESH_subMesh * > & SubMeshesToCompute ()
virtual void SubmeshRestored (SMESH_subMesh *subMesh)
Allow algo to do something after persistent restoration.
bool SupportSubmeshes () const
virtual ~SMESH_Algo ()
Destructor.
Public Member Functions inherited from SMESH_Hypothesis
void ClearParameters ()
virtual bool DataDependOnParams () const
The returned value is used by NotifySubMeshesHypothesisModification() to decide to call subMesh->AlgoStateEngine(MODIF_HYP, hyp) or not if subMesh is ready to be computed (algo+hyp==OK) but not yet computed. True result is reasonable for example if EventListeners depend on parameters of hypothesis.
virtual int GetDim () const
SMESH_Gen * GetGen () const
char * GetLastParameters () const
virtual const char * GetLibName () const
SMESH_Mesh * GetMeshByPersistentID (int id)
Find a mesh with given persistent ID.
char * GetParameters () const
virtual int GetShapeType () const
int GetStudyId () const
virtual bool IsAuxiliary () const
Return true if me is an auxiliary hypothesis.
virtual void NotifySubMeshesHypothesisModification ()
void SetLastParameters (const char *theParameters)
void SetLibName (const char *theLibName)
void SetParameters (const char *theParameters)
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)=0
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)=0
Initialize my parameter values by the mesh built on the geometry.
SMESH_Hypothesis (int hypId, int studyId, SMESH_Gen *gen)
virtual ~SMESH_Hypothesis ()
Public Member Functions inherited from SMESHDS_Hypothesis
int GetID () const
const char * GetName () const
int GetType () const
bool IsSameName (const SMESHDS_Hypothesis &other) const
Compare types of hypotheses.
virtual std::istream & LoadFrom (std::istream &load)=0
bool operator!= (const SMESHDS_Hypothesis &other) const
virtual bool operator== (const SMESHDS_Hypothesis &other) const
virtual std::ostream & SaveTo (std::ostream &save)=0
SMESHDS_Hypothesis (int hypId)
virtual ~SMESHDS_Hypothesis ()
Protected Member Functions
bool compute (SMESH_Mesh &mesh, SMESH_MesherHelper &helper, vector< const SMDS_MeshNode * > &nodeVec, nglib::Ng_Mesh *ngMesh)
set parameters and generate the volume mesh
Protected Member Functions inherited from SMESH_Algo
void addBadInputElement (const SMDS_MeshElement *elem)
store a bad input element preventing computation, which may be a temporary one i.e. not residing the mesh, then it will be deleted by InitComputeError()
void addBadInputElements (const SMESHDS_SubMesh *sm, const bool addNodes=false)
bool error (const SMESH_Comment &comment="")
store COMPERR_ALGO_FAILED error and comment and then return false
bool error (int error, const SMESH_Comment &comment="")
store error and comment and then return (error == COMPERR_OK)
bool error (SMESH_ComputeErrorPtr error)
store error and return error->IsOK()
Additional Inherited Members
Public Types inherited from SMESH_Algo
enum EMeshError { MEr_OK = 0 , MEr_HOLES , MEr_BAD_ORI , MEr_EMPTY }
Public Types inherited from SMESH_Hypothesis
enum Hypothesis_Status {
HYP_OK = 0 , HYP_MISSING , HYP_CONCURENT , HYP_BAD_PARAMETER ,
HYP_HIDDEN_ALGO , HYP_HIDING_ALGO , HYP_UNKNOWN_FATAL , HYP_INCOMPATIBLE ,
HYP_NOTCONFORM , HYP_ALREADY_EXIST , HYP_BAD_DIM , HYP_BAD_SUBSHAPE ,
HYP_BAD_GEOMETRY , HYP_NEED_SHAPE , HYP_INCOMPAT_HYPS
}
Public Types inherited from SMESHDS_Hypothesis
enum hypothesis_type {
PARAM_ALGO , ALGO_0D , ALGO_1D , ALGO_2D ,
ALGO_3D
}
Static Public Member Functions inherited from SMESH_Algo
static GeomAbs_Shape Continuity (TopoDS_Edge E1, TopoDS_Edge E2)
Return continuity of two edges.
static double EdgeLength (const TopoDS_Edge &E)
Compute length of an edge.
static const Features & GetFeatures (const std::string &algoType)
Returns a structure describing algorithm features.
static EMeshError GetMeshError (SMESH_subMesh *subMesh)
Finds topological errors of a sub-mesh.
static bool GetNodeParamOnEdge (const SMESHDS_Mesh *theMesh, const TopoDS_Edge &theEdge, std::vector< double > &theParams)
Fill vector of node parameters on geometrical edge, including vertex nodes.
static bool GetSortedNodesOnEdge (const SMESHDS_Mesh *theMesh, const TopoDS_Edge &theEdge, const bool ignoreMediumNodes, std::map< double, const SMDS_MeshNode * > &theNodes, const SMDSAbs_ElementType typeToCheck=SMDSAbs_All)
Fill map of node parameter on geometrical edge to node it-self.
static bool IsContinuous (const TopoDS_Edge &E1, const TopoDS_Edge &E2)
Return true if an edge can be considered as a continuation of another.
static bool isDegenerated (const TopoDS_Edge &E)
Return true if an edge has no 3D curve.
static bool IsStraight (const TopoDS_Edge &E, const bool degenResult=false)
Return true if an edge can be considered straight.
static const SMDS_MeshNode * VertexNode (const TopoDS_Vertex &V, const SMESH_Mesh *mesh)
Return the node built on a vertex. A node moved to other geometry by MergeNodes() is also returned.
static const SMDS_MeshNode * VertexNode (const TopoDS_Vertex &V, const SMESHDS_Mesh *meshDS)
Return the node built on a vertex.
static const SMDS_MeshNode * VertexNode (const TopoDS_Vertex &V, const SMESHDS_SubMesh *edgeSM, const SMESH_Mesh *mesh, const bool checkV=true)
Return the node built on a vertex. A node moved to other geometry by MergeNodes() is also returned.
Static Public Member Functions inherited from SMESH_Hypothesis
static bool IsStatusFatal (Hypothesis_Status theStatus)
Constructor & Destructor Documentation
NETGENPlugin_NETGEN_3D()
NETGENPlugin_NETGEN_3D::NETGENPlugin_NETGEN_3D (int hypId, int studyId, SMESH_Gen * gen)
~NETGENPlugin_NETGEN_3D()
NETGENPlugin_NETGEN_3D::~NETGENPlugin_NETGEN_3D () virtual
Member Function Documentation
CancelCompute()
void NETGENPlugin_NETGEN_3D::CancelCompute () virtual
Sets _computeCanceled to true. It's usage depends on implementation of a particular mesher.
Reimplemented from SMESH_Algo.
References SMESH_Algo::CancelCompute(), and netgen::multithread.
CheckHypothesis()
bool NETGENPlugin_NETGEN_3D::CheckHypothesis (SMESH_Mesh & aMesh, const TopoDS_Shape & aShape, SMESH_Hypothesis::Hypothesis_Status & aStatus) virtual
Check hypothesis definition to mesh a shape.
Parameters
aMesh - the mesh
aShape - the shape
aStatus - check result
Return values
bool - true if hypothesis is well defined
Textual description of a problem can be stored in _comment field.
Implements SMESH_Algo.
References SMESH_Algo::error(), SMESH_Algo::GetUsedHypothesis(), SMESH_Hypothesis::HYP_INCOMPATIBLE, SMESH_Hypothesis::HYP_OK, and netgen::multithread.
Compute() [1/2]
bool NETGENPlugin_NETGEN_3D::Compute (SMESH_Mesh & aMesh, const TopoDS_Shape & aShape) virtual
Here we are going to use the NETGEN mesher
Implements SMESH_Algo.
References NETGENPlugin_Mesher::AddIntVerticesInSolids(), StdMeshers_QuadToTriaAdaptor::Compute(), compute(), SMESH_Algo::error(), SMESHDS_SubMesh::GetElements(), SMESH_Mesh::GetMeshDS(), SMDS_MeshElement::GetNode(), SMDS_MeshNode::GetPosition(), SMDS_MeshElement::getshapeId(), SMESH_Mesh::GetShapeToMesh(), SMDS_Position::GetTypeOfPosition(), NETGENPlugin_Internals::hasInternalVertexInSolid(), SMESHDS_Mesh::IndexToShape(), SMESH_MesherHelper::IsDegenShape(), NETGENPlugin_Internals::isInternalShape(), SMESH_MesherHelper::IsQuadraticSubMesh(), SMESH_MesherHelper::IsReversedSubMesh(), netgen::multithread, SMESH_MesherHelper::NbAncestors(), SMDS_MeshElement::NbCornerNodes(), SMESH_Mesh::NbQuadrangles(), SMESH_MesherHelper::SetElementsOnShape(), SMESHDS_Mesh::ShapeToIndex(), SMESH_Algo::VertexNode(), SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
Compute() [2/2]
bool NETGENPlugin_NETGEN_3D::Compute (SMESH_Mesh & aMesh, SMESH_MesherHelper * aHelper) virtual
Compute tetrahedral mesh from 2D mesh without geometry.
Reimplemented from SMESH_Algo.
References SMESH_MesherHelper::COMP, StdMeshers_QuadToTriaAdaptor::Compute(), compute(), SMESH_Algo::error(), SMDS_MeshElement::GetNode(), SMESH_MesherHelper::IsQuadraticMesh(), netgen::multithread, SMDS_MeshElement::NbCornerNodes(), SMESH_Mesh::NbQuadrangles(), SMESH_MesherHelper::QUADRATIC, SMESH_MesherHelper::SetIsQuadratic(), SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
compute()
bool NETGENPlugin_NETGEN_3D::compute (SMESH_Mesh & mesh, SMESH_MesherHelper & helper, vector< const SMDS_MeshNode * > & nodeVec, nglib::Ng_Mesh * ngMesh) protected
set parameters and generate the volume mesh
References SMESH_MesherHelper::AddNode(), SMESH_MesherHelper::AddVolume(), SMESH_Algo::error(), NETGENPlugin_Mesher::GetDefaultMinSize(), SMESH_MesherHelper::GetSubShape(), SMESH_Mesh::HasShapeToMesh(), netgen::mparam, netgen::multithread, netgen::OCCGenerateMesh(), NETGENPlugin_Mesher::PrepareOCCgeometry(), NETGENPlugin_Mesher::ReadErrors(), and NETGENPlugin_Mesher::SetParameters().
Referenced by Compute().
Evaluate()
bool NETGENPlugin_NETGEN_3D::Evaluate (SMESH_Mesh & aMesh, const TopoDS_Shape & aShape, MapShapeNbElems & aResMap) virtual
evaluates size of prospective mesh on a shape
Parameters
aMesh - the mesh
aShape - the shape
aResMap - prospective number of elements by SMDSAbs_ElementType by a sub-mesh
Return values
bool - is a success
Implements SMESH_Algo.
References SMESH_subMesh::GetComputeError(), and SMESH_Mesh::GetSubMesh().
GetProgress()
double NETGENPlugin_NETGEN_3D::GetProgress () const virtual
Return Compute progress.
Reimplemented from SMESH_Algo.
References netgen::multithread.
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/NETGENPlugin_NETGEN_3D.hxx
FreeCAD/src/3rdParty/salomesmesh/src/NETGENPlugin/NETGENPlugin_NETGEN_3D.cpp