FreeCAD: ImportGui::ExportOCAFGui Class Reference
ImportGui::ExportOCAFGui Class Reference
Public Member Functions
ExportOCAFGui (Handle(TDocStd_Document) h, bool explicitPlacement)
virtual void findColors (Part::Feature *part, std::vector< App::Color > &colors) const
Public Member Functions inherited from Import::ExportOCAF
void createNode (App::Part *part, int &root_it, std::vector< TDF_Label > &hierarchical_label, std::vector< TopLoc_Location > &hierarchical_loc, std::vector< App::DocumentObject * > &hierarchical_part)
int exportObject (App::DocumentObject *obj, std::vector< TDF_Label > &hierarchical_label, std::vector< TopLoc_Location > &hierarchical_loc, std::vector< App::DocumentObject * > &hierarchical_part)
ExportOCAF (Handle(TDocStd_Document) h, bool explicitPlacement)
void getFreeLabels (std::vector< TDF_Label > &hierarchical_label, std::vector< TDF_Label > &labels, std::vector< int > &label_part_id)
void getPartColors (std::vector< App::DocumentObject * > hierarchical_part, std::vector< TDF_Label > FreeLabels, std::vector< int > part_id, std::vector< std::vector< App::Color > > &Colors) const
void pushNode (int root, int node, std::vector< TDF_Label > &hierarchical_label, std::vector< TopLoc_Location > &hierarchical_loc)
void reallocateFreeShape (std::vector< App::DocumentObject * > hierarchical_part, std::vector< TDF_Label > FreeLabels, std::vector< int > part_id, std::vector< std::vector< App::Color > > &Colors)
int saveShape (Part::Feature *part, const std::vector< App::Color > &, std::vector< TDF_Label > &hierarchical_label, std::vector< TopLoc_Location > &hierarchical_loc, std::vector< App::DocumentObject * > &hierarchical_part)
virtual ~ExportOCAF ()
Constructor & Destructor Documentation
ExportOCAFGui()
ImportGui::ExportOCAFGui::ExportOCAFGui (Handle(TDocStd_Document) h, bool explicitPlacement)
Member Function Documentation
findColors()
virtual void ImportGui::ExportOCAFGui::findColors (Part::Feature * part, std::vector< App::Color > & colors) const virtual
Reimplemented from Import::ExportOCAF.
References Base::Persistence::getClassTypeId(), App::PropertyColor::getValue(), Gui::Application::getViewProvider(), Gui::Application::Instance, Base::BaseClass::isDerivedFrom(), and Gui::ViewProviderGeometryObject::ShapeColor.
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Import/Gui/AppImportGuiPy.cpp