FreeCAD: SMESH_IndexedMap< TheKeyType >::Iterator Class Reference
SMESH_IndexedMap< TheKeyType >::Iterator Class Reference
#include <SMESH_IndexedMap.hxx>
Public Member Functions
virtual TheKeyType & ChangeValue (void) const
Value change access denied - use Substitute.
Iterator (const SMESH_IndexedMap &theMap)
Constructor.
Iterator (void)
Empty constructor.
virtual Standard_Boolean More (void) const
Query if the end of collection is reached by iterator.
virtual void Next (void)
Make a step along the collection.
void * operator new (size_t theSize, const Handle(NCollection_BaseAllocator)&theAllocator)
Operator new for allocating iterators.
virtual const TheKeyType & Value (void) const
Value access.
Constructor & Destructor Documentation
Iterator() [1/2]
template<class TheKeyType > SMESH_IndexedMap< TheKeyType >::Iterator::Iterator (void)
Empty constructor.
Iterator() [2/2]
template<class TheKeyType > SMESH_IndexedMap< TheKeyType >::Iterator::Iterator (const SMESH_IndexedMap & theMap)
Constructor.
Member Function Documentation
ChangeValue()
template<class TheKeyType > virtual TheKeyType& SMESH_IndexedMap< TheKeyType >::Iterator::ChangeValue (void) const virtual
Value change access denied - use Substitute.
More()
template<class TheKeyType > virtual Standard_Boolean SMESH_IndexedMap< TheKeyType >::Iterator::More (void) const virtual
Query if the end of collection is reached by iterator.
Referenced by SMESH_IndexedMap< TheKeyType >::Iterator::Value().
Next()
template<class TheKeyType > virtual void SMESH_IndexedMap< TheKeyType >::Iterator::Next (void) virtual
Make a step along the collection.
operator new()
template<class TheKeyType > void* SMESH_IndexedMap< TheKeyType >::Iterator::operator new (size_t theSize, const Handle(NCollection_BaseAllocator)& theAllocator)
Operator new for allocating iterators.
Value()
template<class TheKeyType > virtual const TheKeyType& SMESH_IndexedMap< TheKeyType >::Iterator::Value (void) const virtual
Value access.
References SMESH_IndexedMap< TheKeyType >::FindKey(), and SMESH_IndexedMap< TheKeyType >::Iterator::More().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_IndexedMap.hxx