FreeCAD: Attacher::AttachEnginePy Class Reference
Attacher::AttachEnginePy Class Reference
The python export class for AttachEngine.
#include <AttachEnginePy.h>
Public Types
typedef AttachEngine * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
AttachEnginePy (AttachEngine *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of AttachEnginePy.
static PyMethodDef Methods []
Methods structure of AttachEnginePy.
static PyTypeObject Type
Type structure of AttachEnginePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~AttachEnginePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * getModeInfo (PyObject *args)
implementer for the getModeInfo() method
PyObject * getRefTypeOfShape (PyObject *args)
implementer for the getRefTypeOfShape() method
PyObject * isFittingRefType (PyObject *args)
implementer for the isFittingRefType() method
PyObject * downgradeRefType (PyObject *args)
implementer for the downgradeRefType() method
PyObject * getRefTypeInfo (PyObject *args)
implementer for the getRefTypeInfo() method
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * calculateAttachedPlacement (PyObject *args)
implementer for the calculateAttachedPlacement() method
PyObject * suggestModes (PyObject *args)
implementer for the suggestModes() method
PyObject * readParametersFromFeature (PyObject *args)
implementer for the readParametersFromFeature() method
PyObject * writeParametersToFeature (PyObject *args)
implementer for the writeParametersToFeature() method
static PyObject * staticCallback_getModeInfo (PyObject *self, PyObject *args)
callback for the getModeInfo() method
static PyObject * staticCallback_getRefTypeOfShape (PyObject *self, PyObject *args)
callback for the getRefTypeOfShape() method
static PyObject * staticCallback_isFittingRefType (PyObject *self, PyObject *args)
callback for the isFittingRefType() method
static PyObject * staticCallback_downgradeRefType (PyObject *self, PyObject *args)
callback for the downgradeRefType() method
static PyObject * staticCallback_getRefTypeInfo (PyObject *self, PyObject *args)
callback for the getRefTypeInfo() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_calculateAttachedPlacement (PyObject *self, PyObject *args)
callback for the calculateAttachedPlacement() method
static PyObject * staticCallback_suggestModes (PyObject *self, PyObject *args)
callback for the suggestModes() method
static PyObject * staticCallback_readParametersFromFeature (PyObject *self, PyObject *args)
callback for the readParametersFromFeature() method
static PyObject * staticCallback_writeParametersToFeature (PyObject *self, PyObject *args)
callback for the writeParametersToFeature() method
callbacks and implementers for the python object attributes
Py::String getAttacherType (void) const
getter for the AttacherType attribute
Py::String getMode (void) const
getter for the Mode attribute
void setMode (Py::String arg)
setter for the Mode attribute
Py::Object getReferences (void) const
getter for the References attribute
void setReferences (Py::Object arg)
setter for the References attribute
Py::Object getAttachmentOffset (void) const
getter for the AttachmentOffset attribute
void setAttachmentOffset (Py::Object arg)
setter for the AttachmentOffset attribute
Py::Boolean getReverse (void) const
getter for the Reverse attribute
void setReverse (Py::Boolean arg)
setter for the Reverse attribute
Py::Float getParameter (void) const
getter for the Parameter attribute
void setParameter (Py::Float arg)
setter for the Parameter attribute
Py::List getCompleteModeList (void) const
getter for the CompleteModeList attribute
Py::List getImplementedModes (void) const
getter for the ImplementedModes attribute
Py::List getCompleteRefTypeList (void) const
getter for the CompleteRefTypeList attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
AttachEngine * getAttachEnginePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getAttacherType (PyObject *self, void *closure)
getter callback for the AttacherType attribute
static int staticCallback_setAttacherType (PyObject *self, PyObject *value, void *closure)
setter callback for the AttacherType attribute
static PyObject * staticCallback_getMode (PyObject *self, void *closure)
getter callback for the Mode attribute
static int staticCallback_setMode (PyObject *self, PyObject *value, void *closure)
setter callback for the Mode attribute
static PyObject * staticCallback_getReferences (PyObject *self, void *closure)
getter callback for the References attribute
static int staticCallback_setReferences (PyObject *self, PyObject *value, void *closure)
setter callback for the References attribute
static PyObject * staticCallback_getAttachmentOffset (PyObject *self, void *closure)
getter callback for the AttachmentOffset attribute
static int staticCallback_setAttachmentOffset (PyObject *self, PyObject *value, void *closure)
setter callback for the AttachmentOffset attribute
static PyObject * staticCallback_getReverse (PyObject *self, void *closure)
getter callback for the Reverse attribute
static int staticCallback_setReverse (PyObject *self, PyObject *value, void *closure)
setter callback for the Reverse attribute
static PyObject * staticCallback_getParameter (PyObject *self, void *closure)
getter callback for the Parameter attribute
static int staticCallback_setParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the Parameter attribute
static PyObject * staticCallback_getCompleteModeList (PyObject *self, void *closure)
getter callback for the CompleteModeList attribute
static int staticCallback_setCompleteModeList (PyObject *self, PyObject *value, void *closure)
setter callback for the CompleteModeList attribute
static PyObject * staticCallback_getImplementedModes (PyObject *self, void *closure)
getter callback for the ImplementedModes attribute
static int staticCallback_setImplementedModes (PyObject *self, PyObject *value, void *closure)
setter callback for the ImplementedModes attribute
static PyObject * staticCallback_getCompleteRefTypeList (PyObject *self, void *closure)
getter callback for the CompleteRefTypeList attribute
static int staticCallback_setCompleteRefTypeList (PyObject *self, PyObject *value, void *closure)
setter callback for the CompleteRefTypeList attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for AttachEngine.
Member Typedef Documentation
PointerType
typedef AttachEngine* Attacher::AttachEnginePy::PointerType
Constructor & Destructor Documentation
~AttachEnginePy()
AttachEnginePy::~AttachEnginePy () protected
AttachEnginePy()
AttachEnginePy::AttachEnginePy (AttachEngine * pcObject, PyTypeObject * T = &Type)
Referenced by copy(), and PyMake().
Member Function Documentation
calculateAttachedPlacement()
PyObject * AttachEnginePy::calculateAttachedPlacement (PyObject * args)
implementer for the calculateAttachedPlacement() method
References Attacher::AttachEngine::calculateAttachedPlacement(), getAttachEnginePtr(), and Base::PlacementPy::Type.
Referenced by staticCallback_calculateAttachedPlacement().
copy()
PyObject * AttachEnginePy::copy (PyObject * args)
implementer for the copy() method
References AttachEnginePy(), and getAttachEnginePtr().
Referenced by staticCallback_copy().
downgradeRefType()
PyObject * AttachEnginePy::downgradeRefType (PyObject * args)
implementer for the downgradeRefType() method
References Attacher::AttachEngine::downgradeType(), Attacher::AttachEngine::getRefTypeByName(), and Attacher::AttachEngine::getRefTypeName().
Referenced by staticCallback_downgradeRefType().
getAttachEnginePtr()
AttachEngine * AttachEnginePy::getAttachEnginePtr (void) const
getter for the object handled by this class
Referenced by calculateAttachedPlacement(), copy(), getAttacherType(), getAttachmentOffset(), getCompleteModeList(), getCompleteRefTypeList(), getImplementedModes(), getMode(), getModeInfo(), getParameter(), getReferences(), getRefTypeInfo(), getReverse(), PyInit(), readParametersFromFeature(), setAttachmentOffset(), setMode(), setParameter(), setReferences(), setReverse(), suggestModes(), and writeParametersToFeature().
getAttacherType()
Py::String AttachEnginePy::getAttacherType (void) const
getter for the AttacherType attribute
References getAttachEnginePtr(), and Base::BaseClassPy::getTypeId().
Referenced by staticCallback_getAttacherType().
getAttachmentOffset()
Py::Object AttachEnginePy::getAttachmentOffset (void) const
getter for the AttachmentOffset attribute
References Attacher::AttachEngine::attachmentOffset, and getAttachEnginePtr().
Referenced by staticCallback_getAttachmentOffset().
getCompleteModeList()
Py::List AttachEnginePy::getCompleteModeList (void) const
getter for the CompleteModeList attribute
References getAttachEnginePtr(), Attacher::AttachEngine::getModeName(), and Attacher::mmDummy_NumberOfModes.
Referenced by staticCallback_getCompleteModeList().
getCompleteRefTypeList()
Py::List AttachEnginePy::getCompleteRefTypeList (void) const
getter for the CompleteRefTypeList attribute
References getAttachEnginePtr(), Attacher::AttachEngine::getRefTypeName(), and Attacher::rtDummy_numberOfShapeTypes.
Referenced by staticCallback_getCompleteRefTypeList().
getCustomAttributes()
PyObject * AttachEnginePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getImplementedModes()
Py::List AttachEnginePy::getImplementedModes (void) const
getter for the ImplementedModes attribute
References getAttachEnginePtr(), Attacher::AttachEngine::getModeName(), Attacher::mmDummy_NumberOfModes, and Attacher::AttachEngine::modeRefTypes.
Referenced by staticCallback_getImplementedModes().
getMode()
Py::String AttachEnginePy::getMode (void) const
getter for the Mode attribute
References getAttachEnginePtr(), Attacher::AttachEngine::getModeName(), and Attacher::AttachEngine::mapMode.
Referenced by staticCallback_getMode().
getModeInfo()
PyObject * AttachEnginePy::getModeInfo (PyObject * args)
implementer for the getModeInfo() method
References Base::Console(), getAttachEnginePtr(), Attacher::AttachEngine::getModeByName(), Attacher::AttachEngine::getRefTypeName(), Base::BaseClassPy::getTypeId(), Attacher::AttachEngine::modeRefTypes, and Base::ConsoleSingleton::Warning().
Referenced by staticCallback_getModeInfo().
getParameter()
Py::Float AttachEnginePy::getParameter (void) const
getter for the Parameter attribute
References Attacher::AttachEngine::attachParameter, and getAttachEnginePtr().
Referenced by staticCallback_getParameter().
getReferences()
Py::Object AttachEnginePy::getReferences (void) const
getter for the References attribute
References getAttachEnginePtr(), App::PropertyLinkSubList::getPyObject(), Attacher::AttachEngine::references, and Attacher::AttachEngine::verifyReferencesAreSafe().
Referenced by staticCallback_getReferences().
getRefTypeInfo()
PyObject * AttachEnginePy::getRefTypeInfo (PyObject * args)
implementer for the getRefTypeInfo() method
References Base::Console(), getAttachEnginePtr(), Attacher::AttachEngine::getRefTypeByName(), Attacher::AttachEngine::getTypeRank(), and Base::ConsoleSingleton::Warning().
Referenced by staticCallback_getRefTypeInfo().
getRefTypeOfShape()
PyObject * AttachEnginePy::getRefTypeOfShape (PyObject * args)
implementer for the getRefTypeOfShape() method
References Attacher::AttachEngine::getRefTypeName(), Attacher::AttachEngine::getShapeType(), and Part::TopoShapePy::Type.
Referenced by staticCallback_getRefTypeOfShape().
getReverse()
Py::Boolean AttachEnginePy::getReverse (void) const
getter for the Reverse attribute
References getAttachEnginePtr(), and Attacher::AttachEngine::mapReverse.
Referenced by staticCallback_getReverse().
GetType()
virtual PyTypeObject* Attacher::AttachEnginePy::GetType (void) virtual
Reimplemented from Base::BaseClassPy.
isFittingRefType()
PyObject * AttachEnginePy::isFittingRefType (PyObject * args)
implementer for the isFittingRefType() method
References Attacher::AttachEngine::getRefTypeByName(), and Attacher::AttachEngine::isShapeOfType().
Referenced by staticCallback_isFittingRefType().
PyInit()
int AttachEnginePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::BaseClassPy.
References Base::BaseExceptionFreeCADError, Attacher::AttachEngine::copy(), Base::Type::createInstanceByName(), Base::Type::fromName(), getAttachEnginePtr(), Base::BaseClass::getClassTypeId(), PyType_Object::o, and Type.
PyMake()
PyObject * AttachEnginePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References AttachEnginePy().
readParametersFromFeature()
PyObject * AttachEnginePy::readParametersFromFeature (PyObject * args)
implementer for the readParametersFromFeature() method
References Part::AttachExtension::AttachmentOffset, getAttachEnginePtr(), App::DocumentObjectPy::getDocumentObjectPtr(), App::ExtensionContainer::getExtensionByType(), App::PropertyPlacement::getValue(), App::PropertyEnumeration::getValue(), App::PropertyFloat::getValue(), App::PropertyBool::getValue(), App::ExtensionContainer::hasExtension(), Part::AttachExtension::MapMode, Part::AttachExtension::MapPathParameter, Part::AttachExtension::MapReversed, Attacher::AttachEngine::setUp(), Part::AttachExtension::Support, and App::DocumentObjectPy::Type.
Referenced by staticCallback_readParametersFromFeature().
representation()
std::string AttachEnginePy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setAttachmentOffset()
void AttachEnginePy::setAttachmentOffset (Py::Object arg)
setter for the AttachmentOffset attribute
References Attacher::AttachEngine::attachmentOffset, getAttachEnginePtr(), Base::PlacementPy::getPlacementPtr(), and Base::PlacementPy::Type.
Referenced by staticCallback_setAttachmentOffset().
setCustomAttributes()
int AttachEnginePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setMode()
void AttachEnginePy::setMode (Py::String arg)
setter for the Mode attribute
References getAttachEnginePtr(), Attacher::AttachEngine::getModeByName(), and Attacher::AttachEngine::mapMode.
Referenced by staticCallback_setMode().
setParameter()
void AttachEnginePy::setParameter (Py::Float arg)
setter for the Parameter attribute
References Attacher::AttachEngine::attachParameter, and getAttachEnginePtr().
Referenced by staticCallback_setParameter().
setReferences()
void AttachEnginePy::setReferences (Py::Object arg)
setter for the References attribute
References getAttachEnginePtr(), Attacher::AttachEngine::references, and App::PropertyLinkSubList::setPyObject().
Referenced by staticCallback_setReferences().
setReverse()
void AttachEnginePy::setReverse (Py::Boolean arg)
setter for the Reverse attribute
References getAttachEnginePtr(), and Attacher::AttachEngine::mapReverse.
Referenced by staticCallback_setReverse().
staticCallback_calculateAttachedPlacement()
PyObject * AttachEnginePy::staticCallback_calculateAttachedPlacement (PyObject * self, PyObject * args) static
callback for the calculateAttachedPlacement() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, calculateAttachedPlacement(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_copy()
PyObject * AttachEnginePy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copy(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_downgradeRefType()
PyObject * AttachEnginePy::staticCallback_downgradeRefType (PyObject * self, PyObject * args) static
callback for the downgradeRefType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, downgradeRefType(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getAttacherType()
PyObject * AttachEnginePy::staticCallback_getAttacherType (PyObject * self, void * closure) static
getter callback for the AttacherType attribute
References Base::BaseExceptionFreeCADError, getAttacherType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getAttachmentOffset()
PyObject * AttachEnginePy::staticCallback_getAttachmentOffset (PyObject * self, void * closure) static
getter callback for the AttachmentOffset attribute
References Base::BaseExceptionFreeCADError, getAttachmentOffset(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCompleteModeList()
PyObject * AttachEnginePy::staticCallback_getCompleteModeList (PyObject * self, void * closure) static
getter callback for the CompleteModeList attribute
References Base::BaseExceptionFreeCADError, getCompleteModeList(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getCompleteRefTypeList()
PyObject * AttachEnginePy::staticCallback_getCompleteRefTypeList (PyObject * self, void * closure) static
getter callback for the CompleteRefTypeList attribute
References Base::BaseExceptionFreeCADError, getCompleteRefTypeList(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getImplementedModes()
PyObject * AttachEnginePy::staticCallback_getImplementedModes (PyObject * self, void * closure) static
getter callback for the ImplementedModes attribute
References Base::BaseExceptionFreeCADError, getImplementedModes(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMode()
PyObject * AttachEnginePy::staticCallback_getMode (PyObject * self, void * closure) static
getter callback for the Mode attribute
References Base::BaseExceptionFreeCADError, getMode(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getModeInfo()
PyObject * AttachEnginePy::staticCallback_getModeInfo (PyObject * self, PyObject * args) static
callback for the getModeInfo() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getModeInfo(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getParameter()
PyObject * AttachEnginePy::staticCallback_getParameter (PyObject * self, void * closure) static
getter callback for the Parameter attribute
References Base::BaseExceptionFreeCADError, getParameter(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getReferences()
PyObject * AttachEnginePy::staticCallback_getReferences (PyObject * self, void * closure) static
getter callback for the References attribute
References Base::BaseExceptionFreeCADError, getReferences(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRefTypeInfo()
PyObject * AttachEnginePy::staticCallback_getRefTypeInfo (PyObject * self, PyObject * args) static
callback for the getRefTypeInfo() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getRefTypeInfo(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getRefTypeOfShape()
PyObject * AttachEnginePy::staticCallback_getRefTypeOfShape (PyObject * self, PyObject * args) static
callback for the getRefTypeOfShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getRefTypeOfShape(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getReverse()
PyObject * AttachEnginePy::staticCallback_getReverse (PyObject * self, void * closure) static
getter callback for the Reverse attribute
References Base::BaseExceptionFreeCADError, getReverse(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isFittingRefType()
PyObject * AttachEnginePy::staticCallback_isFittingRefType (PyObject * self, PyObject * args) static
callback for the isFittingRefType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), isFittingRefType(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_readParametersFromFeature()
PyObject * AttachEnginePy::staticCallback_readParametersFromFeature (PyObject * self, PyObject * args) static
callback for the readParametersFromFeature() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), readParametersFromFeature(), and Base::PyObjectBase::startNotify().
staticCallback_setAttacherType()
int AttachEnginePy::staticCallback_setAttacherType (PyObject * self, PyObject * value, void * closure) static
setter callback for the AttacherType attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setAttachmentOffset()
int AttachEnginePy::staticCallback_setAttachmentOffset (PyObject * self, PyObject * value, void * closure) static
setter callback for the AttachmentOffset attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setAttachmentOffset().
staticCallback_setCompleteModeList()
int AttachEnginePy::staticCallback_setCompleteModeList (PyObject * self, PyObject * value, void * closure) static
setter callback for the CompleteModeList attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setCompleteRefTypeList()
int AttachEnginePy::staticCallback_setCompleteRefTypeList (PyObject * self, PyObject * value, void * closure) static
setter callback for the CompleteRefTypeList attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setImplementedModes()
int AttachEnginePy::staticCallback_setImplementedModes (PyObject * self, PyObject * value, void * closure) static
setter callback for the ImplementedModes attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setMode()
int AttachEnginePy::staticCallback_setMode (PyObject * self, PyObject * value, void * closure) static
setter callback for the Mode attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setMode().
staticCallback_setParameter()
int AttachEnginePy::staticCallback_setParameter (PyObject * self, PyObject * value, void * closure) static
setter callback for the Parameter attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setParameter().
staticCallback_setReferences()
int AttachEnginePy::staticCallback_setReferences (PyObject * self, PyObject * value, void * closure) static
setter callback for the References attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setReferences().
staticCallback_setReverse()
int AttachEnginePy::staticCallback_setReverse (PyObject * self, PyObject * value, void * closure) static
setter callback for the Reverse attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setReverse().
staticCallback_suggestModes()
PyObject * AttachEnginePy::staticCallback_suggestModes (PyObject * self, PyObject * args) static
callback for the suggestModes() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and suggestModes().
staticCallback_writeParametersToFeature()
PyObject * AttachEnginePy::staticCallback_writeParametersToFeature (PyObject * self, PyObject * args) static
callback for the writeParametersToFeature() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and writeParametersToFeature().
suggestModes()
PyObject * AttachEnginePy::suggestModes (PyObject * args)
implementer for the suggestModes() method
References Attacher::SuggestResult::allApplicableModes, Attacher::SuggestResult::bestFitMode, Attacher::SuggestResult::error, getAttachEnginePtr(), Attacher::AttachEngine::getModeName(), Attacher::AttachEngine::getRefTypeName(), Attacher::SuggestResult::message, Attacher::SuggestResult::nextRefTypeHint, Attacher::SuggestResult::reachableModes, Attacher::SuggestResult::references_Types, Attacher::SuggestResult::srIncompatibleGeometry, Attacher::SuggestResult::srLinkBroken, Attacher::SuggestResult::srNoModesFit, Attacher::SuggestResult::srOK, Attacher::SuggestResult::srUnexpectedError, Attacher::AttachEngine::suggestMapModes(), and Base::Exception::what().
Referenced by staticCallback_suggestModes().
writeParametersToFeature()
PyObject * AttachEnginePy::writeParametersToFeature (PyObject * args)
implementer for the writeParametersToFeature() method
References Part::AttachExtension::AttachmentOffset, getAttachEnginePtr(), App::DocumentObjectPy::getDocumentObjectPtr(), App::ExtensionContainer::getExtensionByType(), App::ExtensionContainer::hasExtension(), Part::AttachExtension::MapMode, Part::AttachExtension::MapPathParameter, Part::AttachExtension::MapReversed, App::PropertyLinkSubList::Paste(), App::PropertyBool::setValue(), App::PropertyPlacement::setValue(), App::PropertyEnumeration::setValue(), App::PropertyFloat::setValue(), Part::AttachExtension::Support, App::DocumentObjectPy::Type, and Attacher::AttachEngine::verifyReferencesAreSafe().
Referenced by staticCallback_writeParametersToFeature().
Member Data Documentation
GetterSetter
PyGetSetDef AttachEnginePy::GetterSetter static
Attribute structure of AttachEnginePy.
Methods
PyMethodDef AttachEnginePy::Methods static
Methods structure of AttachEnginePy.
Type
PyTypeObject AttachEnginePy::Type static
Type structure of AttachEnginePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), and PyInit().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/AttachEnginePy.h
Sources/FreeCAD/src/Mod/Part/App/AttachEnginePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/AttachEnginePy.cpp