FreeCAD: Base::StopWatch Class Reference
Base::StopWatch Class Reference
#include <Tools.h>
Classes
struct Private
Public Member Functions
int elapsed ()
int restart ()
void start ()
StopWatch ()
std::string toString (int ms) const
~StopWatch ()
Constructor & Destructor Documentation
StopWatch()
StopWatch::StopWatch ()
~StopWatch()
StopWatch::~StopWatch ()
Member Function Documentation
elapsed()
int StopWatch::elapsed ()
References Base::StopWatch::Private::t.
Referenced by Gui::AutoSaver::saveDocument().
restart()
int StopWatch::restart ()
References Base::StopWatch::Private::t.
start()
void StopWatch::start ()
References Base::StopWatch::Private::t.
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::asString(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::clone(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::hasStart(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::negated(), Gui::AutoSaver::saveDocument(), and Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::value().
toString()
std::string StopWatch::toString (int ms) const
Referenced by Gui::AutoSaver::saveDocument().
The documentation for this class was generated from the following files:
FreeCAD/src/Base/Tools.h
FreeCAD/src/Base/Tools.cpp