FreeCAD: Gui::Dialog::Transform Class Reference
Gui::Dialog::Transform Class Reference
#include <Transform.h>
Public Slots
void on_applyButton_clicked ()
Signals
void directionChanged ()
Public Member Functions
void accept ()
void reject ()
void setTransformStrategy (TransformStrategy *ts)
void showStandardButtons (bool)
Transform (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~Transform ()
Public Member Functions inherited from Gui::LocationDialog
virtual Base::Vector3d getDirection () const =0
Base::Vector3d getUserDirection (bool *ok=nullptr) const
Protected Member Functions
void changeEvent (QEvent *e)
Base::Vector3d getDirection () const
Protected Member Functions inherited from Gui::LocationDialog
virtual void changeEvent (QEvent *e)=0
LocationDialog (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
virtual ~LocationDialog ()
Constructor & Destructor Documentation
Transform()
Transform::Transform (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
References draftgeoutils.intersections::connect(), directionChanged(), and setTransformStrategy().
~Transform()
Transform::~Transform ()
Member Function Documentation
accept()
void Transform::accept (void)
References on_applyButton_clicked().
Referenced by Gui::Dialog::TaskTransform::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void Transform::changeEvent (QEvent * e) protected virtual
Implements Gui::LocationDialog.
References Gui::LocationUi< Ui >::retranslate().
directionChanged
void Gui::Dialog::Transform::directionChanged () signal
Referenced by Transform().
getDirection()
Base::Vector3d Transform::getDirection () const protected virtual
Implements Gui::LocationDialog.
References Gui::LocationUi< Ui >::getDirection().
on_applyButton_clicked
void Transform::on_applyButton_clicked () slot
References Gui::Dialog::TransformStrategy::commitTransform(), Gui::Dialog::TransformStrategy::getRotationCenter(), Base::Unit::Length, Base::Placement::toMatrix(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by accept(), and Gui::Dialog::TaskTransform::clicked().
reject()
void Transform::reject (void)
References Gui::Dialog::TransformStrategy::resetTransform().
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), Gui::Dialog::TaskTransform::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
setTransformStrategy()
void Transform::setTransformStrategy (TransformStrategy * ts)
References Gui::Dialog::TransformStrategy::getRotationCenter(), Base::Unit::Length, Gui::Dialog::TransformStrategy::transformObjects(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by Gui::Dialog::TaskTransform::setTransformStrategy(), and Transform().
showStandardButtons()
void Transform::showStandardButtons (bool b)
Referenced by Gui::Dialog::TaskTransform::TaskTransform().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/Transform.h
FreeCAD/src/Gui/Transform.cpp