FreeCAD: MeshGui::ViewProviderMeshBuilder Class Reference
MeshGui::ViewProviderMeshBuilder Class Reference
#include <ViewProvider.h>
Public Member Functions
virtual void buildNodes (const App::Property *, std::vector< SoNode * > &) const
void createMesh (const App::Property *, SoCoordinate3 *, SoIndexedFaceSet *) const
ViewProviderMeshBuilder ()
~ViewProviderMeshBuilder ()
Public Member Functions inherited from Gui::ViewProviderBuilder
virtual void buildNodes (const App::Property *, std::vector< SoNode * > &) const =0
ViewProviderBuilder (void)
Constructor.
virtual ~ViewProviderBuilder ()
Additional Inherited Members
Static Public Member Functions inherited from Gui::ViewProviderBuilder
static void add (const Base::Type &, const Base::Type &)
static ViewProvider * create (const Base::Type &)
static SoFCSelection * createSelection ()
Constructor & Destructor Documentation
ViewProviderMeshBuilder()
MeshGui::ViewProviderMeshBuilder::ViewProviderMeshBuilder ()
~ViewProviderMeshBuilder()
MeshGui::ViewProviderMeshBuilder::~ViewProviderMeshBuilder ()
Member Function Documentation
buildNodes()
void ViewProviderMeshBuilder::buildNodes (const App::Property * prop, std::vector< SoNode * > & nodes) const virtual
Implements Gui::ViewProviderBuilder.
References createMesh().
createMesh()
void ViewProviderMeshBuilder::createMesh (const App::Property * prop, SoCoordinate3 * coords, SoIndexedFaceSet * faces) const
References MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::CountPoints(), MeshCore::MeshKernel::GetFacets(), and MeshCore::MeshKernel::GetPoints().
Referenced by buildNodes(), MeshGui::ViewProviderMesh::exportToVrml(), MeshGui::ViewProviderIndexedFaceSet::updateData(), and MeshGui::ViewProviderMeshFaceSet::updateData().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/Gui/ViewProvider.h
FreeCAD/src/Mod/Mesh/Gui/ViewProvider.cpp