FreeCAD: PartDesignGui::TaskHelixParameters Class Reference
PartDesignGui::TaskHelixParameters Class Reference
#include <TaskHelixParameters.h>
Public Member Functions
void addAxisToCombo (App::DocumentObject *linkObj, std::string linkSubname, QString itemText)
virtual void apply () override
apply changes made in the parameters input to the model via commands
void fillAxisCombo (bool forceRefill=false)
fillAxisCombo fills the combo and selects the item according to current value of revolution object's axis reference.
TaskHelixParameters (ViewProviderHelix *HelixView, QWidget *parent=0)
~TaskHelixParameters ()
Public Member Functions inherited from PartDesignGui::TaskSketchBasedParameters
TaskSketchBasedParameters (PartDesignGui::ViewProvider *vp, QWidget *parent, const std::string &pixmapname, const QString &parname)
~TaskSketchBasedParameters ()
Public Member Functions inherited from PartDesignGui::TaskFeatureParameters
void recomputeFeature ()
virtual void saveHistory (void)
save field history
TaskFeatureParameters (PartDesignGui::ViewProvider *vp, QWidget *parent, const std::string &pixmapname, const QString &parname)
virtual ~TaskFeatureParameters ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (QWidget *parent=0)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (QWidget *parent=0)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::DocumentObserver
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
virtual ~DocumentObserver ()
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockConnection (bool block)
void detachSelection ()
Detaches from the selection.
bool isConnectionAttached () const
bool isConnectionBlocked () const
SelectionObserver (bool attach=true, int resolve=1)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, int resolve=1)
Constructor.
virtual ~SelectionObserver ()
Protected Member Functions
void changeEvent (QEvent *e) override
void finishReferenceSelection (App::DocumentObject *profile, App::DocumentObject *base) override
void getReferenceAxis (App::DocumentObject *&obj, std::vector< std::string > &sub) const
void onSelectionChanged (const Gui::SelectionChanges &msg) override
void startReferenceSelection (App::DocumentObject *profile, App::DocumentObject *base) override
bool updateView () const
Protected Member Functions inherited from PartDesignGui::TaskSketchBasedParameters
void exitSelectionMode ()
QString getFaceReference (const QString &obj, const QString &sub) const
QVariant objectNameByLabel (const QString &label, const QVariant &suggest) const
Try to find the name of a feature with the given label.
const QString onAddSelection (const Gui::SelectionChanges &msg)
void onSelectReference (const bool pressed, const bool edge, const bool face, const bool planar)
QVariant setUpToFace (const QString &text)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Protected Attributes
App::PropertyAngle * propAngle
App::PropertyLength * propHeight
App::PropertyBool * propLeftHanded
App::PropertyEnumeration * propMode
App::PropertyBool * propOutside
App::PropertyLength * propPitch
App::PropertyLinkSub * propReferenceAxis
App::PropertyBool * propReversed
App::PropertyFloat * propTurns
Protected Attributes inherited from PartDesignGui::TaskFeatureParameters
bool blockUpdate
Lock updateUI(), applying changes to the underlying feature and calling recomputeFeature()
PartDesignGui::ViewProvider * vp
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Slots inherited from PartDesignGui::TaskFeatureParameters
void onUpdateView (bool on)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskHelixParameters()
TaskHelixParameters::TaskHelixParameters (PartDesignGui::ViewProviderHelix * HelixView, QWidget * parent = 0)
References PartDesign::Helix::Angle, PartDesignGui::TaskFeatureParameters::blockUpdate, draftgeoutils.intersections::connect(), PartDesign::Body::findBodyOf(), Gui::ViewProviderDocumentObject::getObject(), App::OriginGroupExtension::getOrigin(), App::PropertyEnumeration::getValue(), App::PropertyFloat::getValue(), App::PropertyBool::getValue(), App::PropertyQuantity::getValue(), Gui::Application::getViewProvider(), QSint::ActionGroup::groupLayout(), PartDesign::Helix::HasBeenEdited, PartDesign::Helix::Height, Gui::Application::Instance, PartDesign::Helix::LeftHanded, PartDesign::Helix::Mode, PartDesignGui::TaskFeatureParameters::onUpdateView(), PartDesign::Helix::Outside, PartDesign::Helix::Pitch, propAngle, propHeight, propLeftHanded, propMode, PartDesign::Helix::proposeParameters(), propOutside, propPitch, propReferenceAxis, propReversed, propTurns, PartDesignGui::TaskFeatureParameters::recomputeFeature(), PartDesign::Helix::ReferenceAxis, Base::Exception::ReportException(), PartDesign::ProfileBased::Reversed, Gui::ViewProviderOrigin::setTemporaryVisibility(), PartDesign::Helix::Turns, and PartDesignGui::TaskFeatureParameters::vp.
~TaskHelixParameters()
TaskHelixParameters::~TaskHelixParameters ()
References PartDesign::Body::findBodyOf(), Gui::ViewProviderDocumentObject::getObject(), App::OriginGroupExtension::getOrigin(), Gui::Application::getViewProvider(), Gui::Application::Instance, Base::Exception::ReportException(), Gui::ViewProviderOrigin::resetTemporaryVisibility(), and PartDesignGui::TaskFeatureParameters::vp.
Member Function Documentation
addAxisToCombo()
void TaskHelixParameters::addAxisToCombo (App::DocumentObject * linkObj, std::string linkSubname, QString itemText)
References App::PropertyLinkSub::setValue().
Referenced by fillAxisCombo().
apply()
void TaskHelixParameters::apply (void) override virtual
apply changes made in the parameters input to the model via commands
Reimplemented from PartDesignGui::TaskFeatureParameters.
References PartDesignGui::buildLinkSingleSubPythonStr(), Gui::ViewProviderDocumentObject::getObject(), getReferenceAxis(), App::PropertyEnumeration::getValue(), App::PropertyFloat::getValue(), App::PropertyBool::getValue(), App::PropertyQuantity::getValue(), propAngle, propHeight, propLeftHanded, propMode, propPitch, propReversed, propTurns, and PartDesignGui::TaskFeatureParameters::vp.
changeEvent()
void TaskHelixParameters::changeEvent (QEvent * e) override protected
fillAxisCombo()
void TaskHelixParameters::fillAxisCombo (bool forceRefill = false)
fillAxisCombo fills the combo and selects the item according to current value of revolution object's axis reference.
Parameters
forceRefill if true, the combo box will be completely refilled. If false, the current value of revolution object's axis will be added to the list (if necessary), and selected. If the list is empty, it will be refilled anyway.
References addAxisToCombo(), PartDesignGui::TaskFeatureParameters::blockUpdate, PartDesign::Body::findBodyOf(), Part::Part2DObject::getAxisCount(), Gui::ViewProviderDocumentObject::getObject(), App::OriginGroupExtension::getOrigin(), PartDesignGui::getRefStr(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), App::Origin::getX(), App::Origin::getY(), App::Origin::getZ(), PartDesign::ProfileBased::Profile, propReferenceAxis, Base::Exception::ReportException(), and PartDesignGui::TaskFeatureParameters::vp.
finishReferenceSelection()
void TaskHelixParameters::finishReferenceSelection (App::DocumentObject * profile, App::DocumentObject * base) override protected virtual
Reimplemented from PartDesignGui::TaskSketchBasedParameters.
References PartDesignGui::TaskSketchBasedParameters::finishReferenceSelection(), PartDesign::FeatureAddSub::getAddSubType(), Gui::ViewProviderDocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesign::FeatureAddSub::Subtractive, and PartDesignGui::TaskFeatureParameters::vp.
getReferenceAxis()
void TaskHelixParameters::getReferenceAxis (App::DocumentObject *& obj, std::vector< std::string > & sub) const protected
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), App::Document::isIn(), and PartDesignGui::TaskFeatureParameters::vp.
Referenced by apply().
onSelectionChanged()
void TaskHelixParameters::onSelectionChanged (const Gui::SelectionChanges & msg) override protected virtual
Implements PartDesignGui::TaskSketchBasedParameters.
References Gui::SelectionChanges::AddSelection, PartDesignGui::TaskSketchBasedParameters::exitSelectionMode(), Gui::ViewProviderDocumentObject::getObject(), PartDesignGui::getReferencedSelection(), propReferenceAxis, PartDesignGui::TaskFeatureParameters::recomputeFeature(), App::PropertyLinkSub::setValue(), and PartDesignGui::TaskFeatureParameters::vp.
startReferenceSelection()
void TaskHelixParameters::startReferenceSelection (App::DocumentObject * profile, App::DocumentObject * base) override protected virtual
Reimplemented from PartDesignGui::TaskSketchBasedParameters.
References PartDesign::FeatureAddSub::getAddSubType(), Gui::ViewProviderDocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesignGui::TaskSketchBasedParameters::startReferenceSelection(), PartDesign::FeatureAddSub::Subtractive, and PartDesignGui::TaskFeatureParameters::vp.
updateView()
bool PartDesignGui::TaskHelixParameters::updateView () const protected
Member Data Documentation
propAngle
App::PropertyAngle* PartDesignGui::TaskHelixParameters::propAngle protected
Referenced by apply(), and TaskHelixParameters().
propHeight
App::PropertyLength* PartDesignGui::TaskHelixParameters::propHeight protected
Referenced by apply(), and TaskHelixParameters().
propLeftHanded
App::PropertyBool* PartDesignGui::TaskHelixParameters::propLeftHanded protected
Referenced by apply(), and TaskHelixParameters().
propMode
App::PropertyEnumeration* PartDesignGui::TaskHelixParameters::propMode protected
Referenced by apply(), and TaskHelixParameters().
propOutside
App::PropertyBool* PartDesignGui::TaskHelixParameters::propOutside protected
Referenced by TaskHelixParameters().
propPitch
App::PropertyLength* PartDesignGui::TaskHelixParameters::propPitch protected
Referenced by apply(), and TaskHelixParameters().
propReferenceAxis
App::PropertyLinkSub* PartDesignGui::TaskHelixParameters::propReferenceAxis protected
Referenced by fillAxisCombo(), onSelectionChanged(), and TaskHelixParameters().
propReversed
App::PropertyBool* PartDesignGui::TaskHelixParameters::propReversed protected
Referenced by apply(), and TaskHelixParameters().
propTurns
App::PropertyFloat* PartDesignGui::TaskHelixParameters::propTurns protected
Referenced by apply(), and TaskHelixParameters().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/PartDesign/Gui/TaskHelixParameters.h
Sources/FreeCAD/src/Mod/PartDesign/Gui/TaskHelixParameters.cpp