FreeCAD: Part::GeomLineSegment Class Reference
Part::GeomLineSegment Class Reference
#include <Geometry.h>
Public Member Functions
virtual Geometry * copy (void) const
returns a copy of this object having a new randomly generated tag.
GeomLineSegment ()
GeomLineSegment (const Handle(Geom_Line)&l)
Base::Vector3d getEndPoint () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
Base::Vector3d getStartPoint () const
const Handle (Geom_Geometry) &handle() const
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
void setHandle (const Handle(Geom_Line)&)
void setHandle (const Handle(Geom_TrimmedCurve)&)
void setPoints (const Base::Vector3d &p1, const Base::Vector3d &p2)
virtual ~GeomLineSegment ()
Public Member Functions inherited from Part::GeomTrimmedCurve
virtual Geometry * copy (void) const
returns a copy of this object having a new randomly generated tag.
GeomTrimmedCurve ()
GeomTrimmedCurve (const Handle(Geom_TrimmedCurve)&)
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
virtual void getRange (double &u, double &v) const
const Handle (Geom_Geometry) &handle() const
bool intersectBasisCurves (const GeomTrimmedCurve *c, std::vector< std::pair< Base::Vector3d, Base::Vector3d > > &points, double tol=Precision::Confusion()) const
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
void setHandle (const Handle(Geom_TrimmedCurve)&)
virtual void setRange (double u, double v)
virtual ~GeomTrimmedCurve ()
Public Member Functions inherited from Part::GeomBoundedCurve
GeomBoundedCurve ()
virtual Base::Vector3d getEndPoint () const
virtual Base::Vector3d getStartPoint () const
virtual ~GeomBoundedCurve ()
Public Member Functions inherited from Part::GeomCurve
bool closestParameter (const Base::Vector3d &point, double &u) const
bool closestParameterToBasisCurve (const Base::Vector3d &point, double &u) const
double curvatureAt (double u) const
Base::Vector3d firstDerivativeAtParameter (double u) const
GeomCurve ()
double getFirstParameter () const
double getLastParameter () const
bool intersect (const GeomCurve *c, std::vector< std::pair< Base::Vector3d, Base::Vector3d > > &points, double tol=Precision::Confusion()) const
double length (double u, double v) const
bool normalAt (const Base::Vector3d &curvepoint, Base::Vector3d &dir) const
bool normalAt (double u, Base::Vector3d &dir) const
Base::Vector3d pointAtParameter (double u) const
void reverse (void)
Base::Vector3d secondDerivativeAtParameter (double u) const
bool tangent (double u, Base::Vector3d &dir) const
bool tangent (double u, gp_Dir &) const
GeomBSplineCurve * toBSpline (double first, double last) const
toBSpline Converts the curve to a B-spline
virtual GeomBSplineCurve * toNurbs (double first, double last) const
TopoDS_Shape toShape () const
Base::Vector3d value (double u) const
virtual ~GeomCurve ()
Public Member Functions inherited from Part::Geometry
Geometry * clone (void) const
returns a cloned object.
virtual Geometry * copy (void) const =0
returns a copy of this object having a new randomly generated tag.
void deleteExtension (Base::Type type)
void deleteExtension (const std::string &name)
std::weak_ptr< GeometryExtension > getExtension (Base::Type type)
std::weak_ptr< const GeometryExtension > getExtension (Base::Type type) const
std::weak_ptr< GeometryExtension > getExtension (const std::string &name)
std::weak_ptr< const GeometryExtension > getExtension (const std::string &name) const
std::vector< std::weak_ptr< const GeometryExtension > > getExtensions () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
boost::uuids::uuid getTag () const
returns the tag of the geometry object
virtual const Handle (Geom_Geometry) &handle() const =0
bool hasExtension (Base::Type type) const
bool hasExtension (const std::string &name) const
void mirror (const Base::Vector3d &point)
void mirror (const Base::Vector3d &point, const Base::Vector3d &dir)
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
void rotate (const Base::Placement &plm)
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
void scale (const Base::Vector3d &vec, double scale)
void setExtension (std::unique_ptr< GeometryExtension > &&geo)
virtual TopoDS_Shape toShape () const =0
void transform (const Base::Matrix4D &mat)
void translate (const Base::Vector3d &vec)
virtual ~Geometry ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Protected Member Functions inherited from Part::GeomTrimmedCurve
Handle (Geom_TrimmedCurve) myCurve
Protected Member Functions inherited from Part::Geometry
void assignTag (const Part::Geometry *)
copies the tag from the geometry passed as a parameter to this object
void copyNonTag (const Part::Geometry *)
void createNewTag ()
create a new tag for the geometry object
Geometry ()
Static Protected Member Functions inherited from Part::GeomCurve
static bool intersect (const Handle(Geom_Curve) c, const Handle(Geom_Curve) c2, std::vector< std::pair< Base::Vector3d, Base::Vector3d > > &points, double tol=Precision::Confusion())
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Part::Geometry
std::vector< std::shared_ptr< GeometryExtension > > extensions
boost::uuids::uuid tag
Constructor & Destructor Documentation
GeomLineSegment() [1/2]
GeomLineSegment::GeomLineSegment ()
GeomLineSegment() [2/2]
GeomLineSegment::GeomLineSegment (const Handle(Geom_Line)& l)
References setHandle().
~GeomLineSegment()
GeomLineSegment::~GeomLineSegment () virtual
Member Function Documentation
copy()
virtual Geometry * Part::GeomLineSegment::copy (void) const virtual
returns a copy of this object having a new randomly generated tag.
If you also want to copy the tag, you may use clone() instead. For creation of geometry with other handles, with or without the same tag, you may use the constructors and the sethandle functions. The tag of a geometry can be copied to another geometry using the assignTag function.
Reimplemented from Part::GeomTrimmedCurve.
Referenced by Sketcher::SketchObject::split().
getEndPoint()
Base::Vector3d Part::GeomLineSegment::getEndPoint () const virtual
Reimplemented from Part::GeomBoundedCurve.
Referenced by CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainAngle::activated(), Sketcher::SketchObject::addCopy(), Sketcher::Sketch::addLineSegment(), Sketcher::SketchObject::addSymmetric(), Sketcher::SketchAnalysis::analyseMissingPointOnPointCoincident(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), Part::createFilletGeometry(), Sketcher::SketchAnalysis::detectMissingEqualityConstraints(), Sketcher::SketchAnalysis::detectMissingPointOnPointConstraints(), Sketcher::SketchAnalysis::detectMissingVerticalHorizontalConstraints(), Sketcher::SketchObject::extend(), Sketcher::SketchObject::fillet(), Part::find2DLinesIntersection(), Part::findFilletCenter(), Sketcher::SketchObject::getAxis(), Sketcher::SketchObject::getPoint(), SketcherGui::DrawSketchHandlerExtend::mouseMove(), SketcherGui::EditModeConstraintCoinManager::processConstraints(), SketcherGui::DrawSketchHandlerExtend::releaseButton(), SketcherGui::DrawSketchHandlerFillet::releaseButton(), Save(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), Sketcher::SketchObject::split(), Part::suggestFilletRadius(), and SketcherGui::DrawSketchHandlerLineSet::updateTransitionData().
getMemSize()
unsigned int GeomLineSegment::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Part::GeomTrimmedCurve.
getPyObject()
PyObject * GeomLineSegment::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Part::GeomTrimmedCurve.
References Part::Geometry::clone().
getStartPoint()
Base::Vector3d Part::GeomLineSegment::getStartPoint () const virtual
Reimplemented from Part::GeomBoundedCurve.
Referenced by CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainAngle::activated(), Sketcher::SketchObject::addCopy(), Sketcher::Sketch::addLineSegment(), Sketcher::SketchObject::addSymmetric(), Sketcher::SketchAnalysis::analyseMissingPointOnPointCoincident(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), Part::createFilletGeometry(), Sketcher::SketchAnalysis::detectMissingEqualityConstraints(), Sketcher::SketchAnalysis::detectMissingPointOnPointConstraints(), Sketcher::SketchAnalysis::detectMissingVerticalHorizontalConstraints(), Sketcher::SketchObject::extend(), Sketcher::SketchObject::fillet(), Part::find2DLinesIntersection(), Part::findFilletCenter(), Sketcher::SketchObject::getAxis(), Sketcher::SketchObject::getPoint(), SketcherGui::DrawSketchHandlerExtend::mouseMove(), SketcherGui::EditModeConstraintCoinManager::processConstraints(), SketcherGui::DrawSketchHandlerExtend::releaseButton(), SketcherGui::DrawSketchHandlerFillet::releaseButton(), Save(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), Sketcher::SketchObject::split(), Part::suggestFilletRadius(), and SketcherGui::DrawSketchHandlerLineSet::updateTransitionData().
Handle()
const Part::GeomLineSegment::Handle (Geom_Geometry) const & virtual
Reimplemented from Part::GeomTrimmedCurve.
Referenced by setHandle().
Restore()
void GeomLineSegment::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Part::GeomTrimmedCurve.
References Base::XMLReader::getAttributeAsFloat(), Base::XMLReader::readElement(), Part::Geometry::Restore(), Base::XMLReader::setPartialRestore(), and setPoints().
Save()
void GeomLineSegment::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from Part::GeomTrimmedCurve.
References getEndPoint(), getStartPoint(), Base::Writer::ind(), Part::Geometry::Save(), Base::Writer::Stream(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
setHandle() [1/2]
void GeomLineSegment::setHandle (const Handle(Geom_Line)& l)
setHandle() [2/2]
void GeomLineSegment::setHandle (const Handle(Geom_TrimmedCurve)& c)
References Handle().
Referenced by GeomLineSegment().
setPoints()
void Part::GeomLineSegment::setPoints (const Base::Vector3d & p1, const Base::Vector3d & p2)
Referenced by Sketcher::SketchObject::addCopy(), Sketcher::SketchObject::addSymmetric(), Sketcher::SketchObject::exposeInternalGeometry(), Part::TangentialArc::makeArc(), Sketcher::SketchObject::rebuildExternalGeometry(), Restore(), and Sketcher::SketchObject::split().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/App/Geometry.h
FreeCAD/src/Mod/Part/App/Geometry.cpp