FreeCAD: Sketcher::SketchPy Class Reference
Sketcher::SketchPy Class Reference
The python export class for Sketch.
#include <SketchPy.h>
Public Types
typedef Sketch * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
SketchPy (Sketch *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of SketchPy.
static PyMethodDef Methods []
Methods structure of SketchPy.
static PyTypeObject Type
Type structure of SketchPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~SketchPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * solve (PyObject *args)
implementer for the solve() method
PyObject * addGeometry (PyObject *args)
implementer for the addGeometry() method
PyObject * addConstraint (PyObject *args)
implementer for the addConstraint() method
PyObject * clear (PyObject *args)
implementer for the clear() method
PyObject * movePoint (PyObject *args)
implementer for the movePoint() method
static PyObject * staticCallback_solve (PyObject *self, PyObject *args)
callback for the solve() method
static PyObject * staticCallback_addGeometry (PyObject *self, PyObject *args)
callback for the addGeometry() method
static PyObject * staticCallback_addConstraint (PyObject *self, PyObject *args)
callback for the addConstraint() method
static PyObject * staticCallback_clear (PyObject *self, PyObject *args)
callback for the clear() method
static PyObject * staticCallback_movePoint (PyObject *self, PyObject *args)
callback for the movePoint() method
callbacks and implementers for the python object attributes
Py::Long getConstraint (void) const
getter for the Constraint attribute
Py::Tuple getConflicts (void) const
getter for the Conflicts attribute
Py::Tuple getRedundancies (void) const
getter for the Redundancies attribute
Py::Tuple getGeometries (void) const
getter for the Geometries attribute
Py::Object getShape (void) const
getter for the Shape attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Sketch * getSketchPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getConstraint (PyObject *self, void *closure)
getter callback for the Constraint attribute
static int staticCallback_setConstraint (PyObject *self, PyObject *value, void *closure)
setter callback for the Constraint attribute
static PyObject * staticCallback_getConflicts (PyObject *self, void *closure)
getter callback for the Conflicts attribute
static int staticCallback_setConflicts (PyObject *self, PyObject *value, void *closure)
setter callback for the Conflicts attribute
static PyObject * staticCallback_getRedundancies (PyObject *self, void *closure)
getter callback for the Redundancies attribute
static int staticCallback_setRedundancies (PyObject *self, PyObject *value, void *closure)
setter callback for the Redundancies attribute
static PyObject * staticCallback_getGeometries (PyObject *self, void *closure)
getter callback for the Geometries attribute
static int staticCallback_setGeometries (PyObject *self, PyObject *value, void *closure)
setter callback for the Geometries attribute
static PyObject * staticCallback_getShape (PyObject *self, void *closure)
getter callback for the Shape attribute
static int staticCallback_setShape (PyObject *self, PyObject *value, void *closure)
setter callback for the Shape attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Sketch.
Member Typedef Documentation
PointerType
typedef Sketch* Sketcher::SketchPy::PointerType
Constructor & Destructor Documentation
~SketchPy()
SketchPy::~SketchPy () protected
SketchPy()
SketchPy::SketchPy (Sketch * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
addConstraint()
PyObject * SketchPy::addConstraint (PyObject * args)
implementer for the addConstraint() method
References Sketcher::ConstraintPy::getConstraintPtr(), and Sketcher::ConstraintPy::Type.
Referenced by staticCallback_addConstraint().
addGeometry()
PyObject * SketchPy::addGeometry (PyObject * args)
implementer for the addGeometry() method
References Part::GeometryPy::Type.
Referenced by staticCallback_addGeometry().
clear()
PyObject * SketchPy::clear (PyObject * args)
implementer for the clear() method
Referenced by staticCallback_clear().
getConflicts()
Py::Tuple SketchPy::getConflicts (void) const
getter for the Conflicts attribute
Referenced by staticCallback_getConflicts().
getConstraint()
Py::Long SketchPy::getConstraint (void) const
getter for the Constraint attribute
Referenced by staticCallback_getConstraint().
getCustomAttributes()
PyObject * SketchPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getGeometries()
Py::Tuple SketchPy::getGeometries (void) const
getter for the Geometries attribute
Referenced by staticCallback_getGeometries().
getRedundancies()
Py::Tuple SketchPy::getRedundancies (void) const
getter for the Redundancies attribute
Referenced by staticCallback_getRedundancies().
getShape()
Py::Object SketchPy::getShape (void) const
getter for the Shape attribute
Referenced by staticCallback_getShape().
getSketchPtr()
Sketch * SketchPy::getSketchPtr (void) const
getter for the object handled by this class
GetType()
virtual PyTypeObject* Sketcher::SketchPy::GetType (void) virtual
Reimplemented from Base::PersistencePy.
movePoint()
PyObject * SketchPy::movePoint (PyObject * args)
implementer for the movePoint() method
References Base::VectorPy::Type.
Referenced by staticCallback_movePoint().
PyInit()
int SketchPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PersistencePy.
PyMake()
PyObject * SketchPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string SketchPy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int SketchPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
solve()
PyObject * SketchPy::solve (PyObject * args)
implementer for the solve() method
Referenced by femsolver.run.Machine::reset(), and staticCallback_solve().
staticCallback_addConstraint()
PyObject * SketchPy::staticCallback_addConstraint (PyObject * self, PyObject * args) static
callback for the addConstraint() method
References addConstraint(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addGeometry()
PyObject * SketchPy::staticCallback_addGeometry (PyObject * self, PyObject * args) static
callback for the addGeometry() method
References addGeometry(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_clear()
PyObject * SketchPy::staticCallback_clear (PyObject * self, PyObject * args) static
callback for the clear() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, clear(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getConflicts()
PyObject * SketchPy::staticCallback_getConflicts (PyObject * self, void * closure) static
getter callback for the Conflicts attribute
References Base::BaseExceptionFreeCADError, getConflicts(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getConstraint()
PyObject * SketchPy::staticCallback_getConstraint (PyObject * self, void * closure) static
getter callback for the Constraint attribute
References Base::BaseExceptionFreeCADError, getConstraint(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getGeometries()
PyObject * SketchPy::staticCallback_getGeometries (PyObject * self, void * closure) static
getter callback for the Geometries attribute
References Base::BaseExceptionFreeCADError, getGeometries(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRedundancies()
PyObject * SketchPy::staticCallback_getRedundancies (PyObject * self, void * closure) static
getter callback for the Redundancies attribute
References Base::BaseExceptionFreeCADError, getRedundancies(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getShape()
PyObject * SketchPy::staticCallback_getShape (PyObject * self, void * closure) static
getter callback for the Shape attribute
References Base::BaseExceptionFreeCADError, getShape(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_movePoint()
PyObject * SketchPy::staticCallback_movePoint (PyObject * self, PyObject * args) static
callback for the movePoint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), movePoint(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_setConflicts()
int SketchPy::staticCallback_setConflicts (PyObject * self, PyObject * value, void * closure) static
setter callback for the Conflicts attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setConstraint()
int SketchPy::staticCallback_setConstraint (PyObject * self, PyObject * value, void * closure) static
setter callback for the Constraint attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setGeometries()
int SketchPy::staticCallback_setGeometries (PyObject * self, PyObject * value, void * closure) static
setter callback for the Geometries attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setRedundancies()
int SketchPy::staticCallback_setRedundancies (PyObject * self, PyObject * value, void * closure) static
setter callback for the Redundancies attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setShape()
int SketchPy::staticCallback_setShape (PyObject * self, PyObject * value, void * closure) static
setter callback for the Shape attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_solve()
PyObject * SketchPy::staticCallback_solve (PyObject * self, PyObject * args) static
callback for the solve() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), solve(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef SketchPy::GetterSetter static
Attribute structure of SketchPy.
Methods
PyMethodDef SketchPy::Methods static
Initial value:
= {
    {"solve",
        reinterpret_cast<PyCFunction>( staticCallback_solve ),
        METH_VARARGS,
        "solve the actual set of geometry and constraints"
    },
    {"addGeometry",
        reinterpret_cast<PyCFunction>( staticCallback_addGeometry ),
        METH_VARARGS,
        "add a geometric object to the sketch"
    },
    {"addConstraint",
        reinterpret_cast<PyCFunction>( staticCallback_addConstraint ),
        METH_VARARGS,
        "add an constraint object to the sketch"
    },
    {"clear",
        reinterpret_cast<PyCFunction>( staticCallback_clear ),
        METH_VARARGS,
        "clear the sketch"
    },
    {"movePoint",
        reinterpret_cast<PyCFunction>( staticCallback_movePoint ),
        METH_VARARGS,
        "\n          movePoint(GeoIndex,PointPos,Vector,[relative]) - move a given point (or curve)\n          to another location.\n          It moves the specified point (or curve) to the given location by adding some\n          temporary weak constraints and solve the sketch.\n          This method is mostly used to allow the user to drag some portions of the sketch\n          in real time by e.g. the mouse and it works only for underconstrained portions of\n          the sketch.\n          The argument 'relative', if present, states if the new location is given\n          relatively to the current one.\n        "
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of SketchPy.
Type
PyTypeObject SketchPy::Type static
Type structure of SketchPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Sketcher/App/SketchPy.h
Sources/FreeCAD/src/Mod/Sketcher/App/SketchPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Sketcher/App/SketchPy.cpp