FreeCAD: Gui::LocationImpUi< Ui > Class Template Reference
Gui::LocationImpUi< Ui > Class Template Reference
This is the template class that implements the interface of AbstractUi.
#include <InputVector.h>
Public Member Functions
bool directionActivated (LocationDialog *dlg, int index)
boost::any get ()
Base::Vector3d getDirection () const
Base::Vector3d getPosition () const
LocationImpUi (Ui *ui)
void retranslate (QDialog *dlg)
void setDirection (const Base::Vector3d &dir)
void setPosition (const Base::Vector3d &v)
~LocationImpUi ()
Public Member Functions inherited from Gui::AbstractUi
virtual ~AbstractUi ()=default
Detailed Description
template<class Ui>
class Gui::LocationImpUi< Ui >
This is the template class that implements the interface of AbstractUi.
The template argument is the Ui interface class built by uic out of a .ui file.
Author
Werner Mayer
Constructor & Destructor Documentation
LocationImpUi()
template<class Ui > Gui::LocationImpUi< Ui >::LocationImpUi (Ui * ui)
~LocationImpUi()
template<class Ui > Gui::LocationImpUi< Ui >::~LocationImpUi ()
Member Function Documentation
directionActivated()
template<class Ui > bool Gui::LocationImpUi< Ui >::directionActivated (LocationDialog * dlg, int index) virtual
Implements Gui::AbstractUi.
References Base::Vector3< double >::epsilon(), Gui::LocationDialog::getUserDirection(), Base::Vector3< _Precision >::Length(), and Gui::LocationImpUi< Ui >::setDirection().
get()
template<class Ui > boost::any Gui::LocationImpUi< Ui >::get () virtual
Implements Gui::AbstractUi.
Referenced by draftguitools.gui_trackers.editTracker::move().
getDirection()
template<class Ui > Base::Vector3d Gui::LocationImpUi< Ui >::getDirection (void) const virtual
Implements Gui::AbstractUi.
getPosition()
template<class Ui > Base::Vector3d Gui::LocationImpUi< Ui >::getPosition (void) const virtual
Implements Gui::AbstractUi.
retranslate()
template<class Ui > void Gui::LocationImpUi< Ui >::retranslate (QDialog * dlg) virtual
Implements Gui::AbstractUi.
References draftutils.translate::translate().
setDirection()
template<class Ui > void Gui::LocationImpUi< Ui >::setDirection (const Base::Vector3d & dir) virtual
Implements Gui::AbstractUi.
References femsolver.report::display(), Base::Vector3< double >::epsilon(), Base::Vector3< _Precision >::Length(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by Gui::LocationImpUi< Ui >::directionActivated().
setPosition()
template<class Ui > void Gui::LocationImpUi< Ui >::setPosition (const Base::Vector3d & v) virtual
Implements Gui::AbstractUi.
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/InputVector.h