FreeCAD: ArchFrame Namespace Reference
ArchFrame Namespace Reference
Workbenches » Python workbenches » Arch
The Frame object and tools.
Functions
def makeFrame (baseobj, profile, name=translate("Arch","Frame"))
Detailed Description
The Frame object and tools.
This module provides tools to build Frame objects. Frames are objects made of a profile and an object with edges along which the profile gets extruded
Function Documentation
makeFrame()
def ArchFrame.makeFrame (baseobj, profile, name = translate("Arch","Frame"))
makeFrame(baseobj,profile,[name]): creates a frame object from a base sketch (or any other object
containing wires) and a profile object (an extrudable 2D object containing faces or closed wires)
References ArchComponent.ViewProviderComponent.claimChildren(), DraftVecUtils.isNull(), ArchComponent.Component.onDocumentRestored(), and draftutils.translate.QT_TRANSLATE_NOOP.