FreeCAD: SMESHUtils Namespace Reference
SMESHUtils Namespace Reference
Classes
struct ArrayDeleter
Auto pointer to array.
struct Deleter
Auto pointer.
Functions
template<class TVECTOR >
void CompactVector (TVECTOR &vec)
template<class TVECTOR >
void FreeVector (TVECTOR &vec)
Enforce freeing memory allocated by std::vector.
Function Documentation
CompactVector()
template<class TVECTOR > void SMESHUtils::CompactVector (TVECTOR & vec)
References draftgeoutils.general::vec().
FreeVector()
template<class TVECTOR > void SMESHUtils::FreeVector (TVECTOR & vec)
Enforce freeing memory allocated by std::vector.
References draftgeoutils.general::vec().
Referenced by VISCOUS_2D::_SegmentTree::buildChildrenData(), DriverGMF_Read::Perform(), SMESH::Controls::ElementsOnShape::SetMesh(), and SMESH::Controls::ElementsOnShape::SetShape().