FreeCAD: DriverUNV_W_SMDS_Mesh Class Reference
DriverUNV_W_SMDS_Mesh Class Reference
#include <DriverUNV_W_SMDS_Mesh.h>
Public Member Functions
void AddGroup (SMESHDS_GroupBase *theGroup)
virtual Status Perform ()
Public Member Functions inherited from Driver_SMDS_Mesh
Driver_SMDS_Mesh ()
void SetMesh (SMDS_Mesh *theMesh)
Public Member Functions inherited from Driver_Mesh
Driver_Mesh ()
virtual SMESH_ComputeErrorPtr GetError ()
Return a structure containing description of errors.
virtual std::string GetMeshName () const
virtual Status Perform ()=0
virtual void SetFile (const std::string &theFileName)
void SetMeshId (int theMeshId)
virtual void SetMeshName (const std::string &theMeshName)
virtual void SetOption (const std::string &optionName, const std::string &optionValue)
virtual ~Driver_Mesh ()
Additional Inherited Members
Public Types inherited from Driver_Mesh
enum Status {
DRS_OK , DRS_EMPTY , DRS_WARN_RENUMBER , DRS_WARN_SKIP_ELEM ,
DRS_WARN_DESCENDING , DRS_FAIL
}
Protected Member Functions inherited from Driver_Mesh
Status addMessage (const std::string &msg, const bool isFatal=false)
Stores an error message.
Protected Attributes inherited from Driver_SMDS_Mesh
SMDS_Mesh * myMesh
Protected Attributes inherited from Driver_Mesh
std::vector< std::string > myErrorMessages
std::string myFile
int myMeshId
std::string myMeshName
Status myStatus
Member Function Documentation
AddGroup()
void DriverUNV_W_SMDS_Mesh::AddGroup (SMESHDS_GroupBase * theGroup)
Referenced by SMESH_Mesh::ExportUNV().
Perform()
Driver_Mesh::Status DriverUNV_W_SMDS_Mesh::Perform () virtual
Implements Driver_Mesh.
References UNV::check_file(), UNV2411::TRecord::coord, Driver_Mesh::DRS_OK, SMDS_Mesh::edgesIterator(), SMESHDS_GroupBase::Extent(), SMDS_Mesh::facesIterator(), SMESHDS_GroupBase::GetElements(), SMDS_MeshElement::GetID(), SMESHDS_GroupBase::GetID(), SMESHDS_GroupBase::GetStoreName(), SMESHDS_GroupBase::GetType(), SMDS_MeshElement::IsPoly(), SMDS_MeshElement::IsQuadratic(), UNV2411::TRecord::label, Driver_Mesh::myFile, Driver_SMDS_Mesh::myMesh, Driver_Mesh::myMeshName, SMDS_Mesh::NbEdges(), SMDS_Mesh::NbFaces(), SMDS_Mesh::NbNodes(), SMDS_MeshElement::NbNodes(), SMDS_Mesh::NbVolumes(), SMDS_Mesh::nodesIterator(), SMDS_MeshElement::nodesIteratorToUNV(), SMDS_Mesh::volumesIterator(), UNV164::Write(), UNV2420::Write(), UNV2411::Write(), UNV2412::Write(), UNV2417::Write(), SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
Referenced by SMESH_Mesh::ExportUNV().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/DriverUNV_W_SMDS_Mesh.h
FreeCAD/src/3rdParty/salomesmesh/src/DriverUNV/DriverUNV_W_SMDS_Mesh.cpp