FreeCAD: MeshCore::PlaneSurfaceFit Class Reference
MeshCore::PlaneSurfaceFit Class Reference
#include <Segmentation.h>
Public Member Functions
void AddTriangle (const MeshGeomFacet &)
bool Done () const
float Fit ()
float GetDistanceToSurface (const Base::Vector3f &) const
const char * GetType () const
void Initialize (const MeshGeomFacet &)
std::vector< float > Parameters () const
PlaneSurfaceFit ()
PlaneSurfaceFit (const Base::Vector3f &b, const Base::Vector3f &n)
bool TestTriangle (const MeshGeomFacet &) const
~PlaneSurfaceFit ()
Public Member Functions inherited from MeshCore::AbstractSurfaceFit
AbstractSurfaceFit ()
virtual ~AbstractSurfaceFit ()
Constructor & Destructor Documentation
PlaneSurfaceFit() [1/2]
PlaneSurfaceFit::PlaneSurfaceFit ()
PlaneSurfaceFit() [2/2]
PlaneSurfaceFit::PlaneSurfaceFit (const Base::Vector3f & b, const Base::Vector3f & n)
~PlaneSurfaceFit()
PlaneSurfaceFit::~PlaneSurfaceFit ()
Member Function Documentation
AddTriangle()
void PlaneSurfaceFit::AddTriangle (const MeshGeomFacet & tria) virtual
Implements MeshCore::AbstractSurfaceFit.
References MeshCore::Approximation::AddPoint(), and MeshCore::MeshGeomFacet::GetGravityPoint().
Done()
bool PlaneSurfaceFit::Done () const virtual
Implements MeshCore::AbstractSurfaceFit.
References MeshCore::Approximation::Done().
Fit()
float PlaneSurfaceFit::Fit () virtual
Implements MeshCore::AbstractSurfaceFit.
References MeshCore::PlaneFit::Fit().
GetDistanceToSurface()
float PlaneSurfaceFit::GetDistanceToSurface (const Base::Vector3f & pnt) const virtual
Implements MeshCore::AbstractSurfaceFit.
References Base::Vector3< _Precision >::DistanceToPlane(), and MeshCore::PlaneFit::GetDistanceToPlane().
GetType()
const char* MeshCore::PlaneSurfaceFit::GetType (void) const virtual
Implements MeshCore::AbstractSurfaceFit.
Initialize()
void PlaneSurfaceFit::Initialize (const MeshGeomFacet & tria) virtual
Implements MeshCore::AbstractSurfaceFit.
References MeshCore::Approximation::AddPoint(), MeshCore::Approximation::Clear(), MeshCore::PlaneFit::Fit(), MeshCore::MeshGeomFacet::GetGravityPoint(), and MeshCore::MeshGeomFacet::GetNormal().
Parameters()
std::vector< float > PlaneSurfaceFit::Parameters () const virtual
Implements MeshCore::AbstractSurfaceFit.
References MeshCore::PlaneFit::GetBase(), MeshCore::PlaneFit::GetNormal(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
TestTriangle()
bool PlaneSurfaceFit::TestTriangle (const MeshGeomFacet &) const virtual
Implements MeshCore::AbstractSurfaceFit.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Segmentation.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Segmentation.cpp