FreeCAD: StdMeshers_Arithmetic1D Class Reference
StdMeshers_Arithmetic1D Class Reference
#include <StdMeshers_Arithmetic1D.hxx>
Public Member Functions
double GetLength (bool isStartLength) const
const char * GetObjectEntry ()
const std::vector< int > & GetReversedEdges () const
virtual std::istream & LoadFrom (std::istream &load)
virtual std::ostream & SaveTo (std::ostream &save)
void SetLength (double length, bool isStartLength)
void SetObjectEntry (const char *entry)
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)
Initialize start and end length by the mesh built on the geometry.
void SetReversedEdges (std::vector< int > &ids)
StdMeshers_Arithmetic1D (int hypId, int studyId, SMESH_Gen *gen)
virtual ~StdMeshers_Arithmetic1D ()
Public Member Functions inherited from SMESH_Hypothesis
void ClearParameters ()
virtual bool DataDependOnParams () const
The returned value is used by NotifySubMeshesHypothesisModification() to decide to call subMesh->AlgoStateEngine(MODIF_HYP, hyp) or not if subMesh is ready to be computed (algo+hyp==OK) but not yet computed. True result is reasonable for example if EventListeners depend on parameters of hypothesis.
virtual int GetDim () const
SMESH_Gen * GetGen () const
char * GetLastParameters () const
virtual const char * GetLibName () const
SMESH_Mesh * GetMeshByPersistentID (int id)
Find a mesh with given persistent ID.
char * GetParameters () const
virtual int GetShapeType () const
int GetStudyId () const
virtual bool IsAuxiliary () const
Return true if me is an auxiliary hypothesis.
virtual void NotifySubMeshesHypothesisModification ()
void SetLastParameters (const char *theParameters)
void SetLibName (const char *theLibName)
void SetParameters (const char *theParameters)
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)=0
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)=0
Initialize my parameter values by the mesh built on the geometry.
SMESH_Hypothesis (int hypId, int studyId, SMESH_Gen *gen)
virtual ~SMESH_Hypothesis ()
Public Member Functions inherited from SMESHDS_Hypothesis
int GetID () const
const char * GetName () const
int GetType () const
bool IsSameName (const SMESHDS_Hypothesis &other) const
Compare types of hypotheses.
virtual std::istream & LoadFrom (std::istream &load)=0
bool operator!= (const SMESHDS_Hypothesis &other) const
virtual bool operator== (const SMESHDS_Hypothesis &other) const
virtual std::ostream & SaveTo (std::ostream &save)=0
SMESHDS_Hypothesis (int hypId)
virtual ~SMESHDS_Hypothesis ()
Friends
std::ostream & operator<< (std::ostream &save, StdMeshers_Arithmetic1D &hyp)
std::istream & operator>> (std::istream &load, StdMeshers_Arithmetic1D &hyp)
Additional Inherited Members
Public Types inherited from SMESH_Hypothesis
enum Hypothesis_Status {
HYP_OK = 0 , HYP_MISSING , HYP_CONCURENT , HYP_BAD_PARAMETER ,
HYP_HIDDEN_ALGO , HYP_HIDING_ALGO , HYP_UNKNOWN_FATAL , HYP_INCOMPATIBLE ,
HYP_NOTCONFORM , HYP_ALREADY_EXIST , HYP_BAD_DIM , HYP_BAD_SUBSHAPE ,
HYP_BAD_GEOMETRY , HYP_NEED_SHAPE , HYP_INCOMPAT_HYPS
}
Public Types inherited from SMESHDS_Hypothesis
enum hypothesis_type {
PARAM_ALGO , ALGO_0D , ALGO_1D , ALGO_2D ,
ALGO_3D
}
Static Public Member Functions inherited from SMESH_Hypothesis
static bool IsStatusFatal (Hypothesis_Status theStatus)
Constructor & Destructor Documentation
StdMeshers_Arithmetic1D()
StdMeshers_Arithmetic1D::StdMeshers_Arithmetic1D (int hypId, int studyId, SMESH_Gen * gen)
~StdMeshers_Arithmetic1D()
StdMeshers_Arithmetic1D::~StdMeshers_Arithmetic1D () virtual
Member Function Documentation
GetLength()
double StdMeshers_Arithmetic1D::GetLength (bool isStartLength) const
Referenced by StdMeshers_Regular_1D::CheckHypothesis().
GetObjectEntry()
const char * StdMeshers_Arithmetic1D::GetObjectEntry ()
GetReversedEdges()
const std::vector< int > & StdMeshers_Arithmetic1D::GetReversedEdges () const
Referenced by StdMeshers_Regular_1D::CheckHypothesis().
LoadFrom()
istream & StdMeshers_Arithmetic1D::LoadFrom (std::istream & load) virtual
Implements SMESHDS_Hypothesis.
SaveTo()
ostream & StdMeshers_Arithmetic1D::SaveTo (std::ostream & save) virtual
Implements SMESHDS_Hypothesis.
References OfflineRenderingUtils::save().
SetLength()
void StdMeshers_Arithmetic1D::SetLength (double length, bool isStartLength)
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
Referenced by MeshPart::Mesher::createMesh().
SetObjectEntry()
void StdMeshers_Arithmetic1D::SetObjectEntry (const char * entry)
SetParametersByDefaults()
bool StdMeshers_Arithmetic1D::SetParametersByDefaults (const TDefaults & dflts, const SMESH_Mesh * theMesh = 0) virtual
Initialize my parameter values by default parameters.
Return values
bool - true if parameter values have been successfully defined
Implements SMESH_Hypothesis.
SetParametersByMesh()
bool StdMeshers_Arithmetic1D::SetParametersByMesh (const SMESH_Mesh * theMesh, const TopoDS_Shape & theShape) virtual
Initialize start and end length by the mesh built on the geometry.
Parameters
theMesh - the built mesh
theShape - the geometry of interest
Return values
bool - true if parameter values have been successfully defined
Implements SMESH_Hypothesis.
References SMESH_Algo::GetNodeParamOnEdge().
SetReversedEdges()
void StdMeshers_Arithmetic1D::SetReversedEdges (std::vector< int > & ids)
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
Friends And Related Function Documentation
operator<<
std::ostream & operator<< (std::ostream & save, StdMeshers_Arithmetic1D & hyp) friend
operator>>
std::istream & operator>> (std::istream & load, StdMeshers_Arithmetic1D & hyp) friend
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_Arithmetic1D.hxx
FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_Arithmetic1D.cpp