FreeCAD: Gui::FreehandSelection Class Reference
Gui::FreehandSelection Class Reference
The freehand selection class.
#include <MouseSelection.h>
Public Member Functions
FreehandSelection ()
void setClosed (bool c)
virtual ~FreehandSelection ()
Public Member Functions inherited from Gui::PolyPickerSelection
virtual void initialize ()
implement this in derived classes
PolyPickerSelection ()
void setColor (float r, float g, float b, float a=1.0)
void setLineWidth (float l)
virtual void terminate (bool abort=false)
implement this in derived classes
virtual ~PolyPickerSelection ()
Public Member Functions inherited from Gui::BaseMouseSelection
BaseMouseSelection ()
virtual ~BaseMouseSelection ()
Public Member Functions inherited from Gui::AbstractMouseSelection
AbstractMouseSelection ()
const std::vector< SbVec2s > & getPositions () const
void grabMouseModel (Gui::View3DInventorViewer *)
virtual void initialize ()=0
implement this in derived classes
void redraw ()
void releaseMouseModel (bool abort=false)
SelectionRole selectedRole () const
virtual void terminate (bool abort=false)=0
implement this in derived classes
virtual ~AbstractMouseSelection (void)
int handleEvent (const SoEvent *const ev, const SbViewportRegion &vp)
Protected Member Functions
virtual int locationEvent (const SoLocation2Event *const e, const QPoint &pos)
virtual int mouseButtonEvent (const SoMouseButtonEvent *const e, const QPoint &pos)
virtual int popupMenu ()
Protected Member Functions inherited from Gui::PolyPickerSelection
virtual void draw ()
draw the polygon
virtual int keyboardEvent (const SoKeyboardEvent *const e)
virtual int locationEvent (const SoLocation2Event *const e, const QPoint &pos)
virtual int mouseButtonEvent (const SoMouseButtonEvent *const e, const QPoint &pos)
virtual int popupMenu ()
Protected Member Functions inherited from Gui::AbstractMouseSelection
Additional Inherited Members
Public Types inherited from Gui::AbstractMouseSelection
enum {
Continue =0 , Restart =1 , Finish =2 , Cancel =3 ,
Ignore =4
}
Protected Attributes inherited from Gui::PolyPickerSelection
bool lastConfirmed
Gui::Polyline polyline
Protected Attributes inherited from Gui::AbstractMouseSelection
QCursor m_cPrevCursor
int m_iXold
int m_iYold
int m_iXnew
int m_iYnew
SelectionRole m_selectedRole
Detailed Description
The freehand selection class.
Author
Werner Mayer
Constructor & Destructor Documentation
FreehandSelection()
FreehandSelection::FreehandSelection ()
~FreehandSelection()
FreehandSelection::~FreehandSelection () virtual
Member Function Documentation
locationEvent()
int FreehandSelection::locationEvent (const SoLocation2Event *const e, const QPoint & pos) protected virtual
Reimplemented from Gui::PolyPickerSelection.
References Gui::Polyline::addNode(), Gui::AbstractMouseSelection::Continue, Gui::PolyPickerSelection::draw(), Gui::Polyline::isWorking(), Gui::AbstractMouseSelection::m_iXnew, Gui::AbstractMouseSelection::m_iXold, Gui::AbstractMouseSelection::m_iYnew, Gui::AbstractMouseSelection::m_iYold, Gui::PolyPickerSelection::polyline, and Gui::Polyline::setCoords().
mouseButtonEvent()
int FreehandSelection::mouseButtonEvent (const SoMouseButtonEvent *const e, const QPoint & pos) protected virtual
Reimplemented from Gui::PolyPickerSelection.
References Gui::Polyline::addNode(), Gui::AbstractMouseSelection::Cancel, Gui::Polyline::clear(), Gui::AbstractMouseSelection::Continue, Gui::AbstractMouseSelection::Finish, Gui::Polyline::isWorking(), Gui::AbstractMouseSelection::m_cPrevCursor, Gui::AbstractMouseSelection::m_iXnew, Gui::AbstractMouseSelection::m_iXold, Gui::AbstractMouseSelection::m_iYnew, Gui::AbstractMouseSelection::m_iYold, Gui::PolyPickerSelection::polyline, popupMenu(), Gui::AbstractMouseSelection::releaseMouseModel(), Gui::AbstractMouseSelection::Restart, Gui::Polyline::setCoords(), and Gui::Polyline::setWorking().
popupMenu()
int FreehandSelection::popupMenu () protected virtual
Reimplemented from Gui::PolyPickerSelection.
References Gui::AbstractMouseSelection::Cancel, Gui::AbstractMouseSelection::Finish, Gui::AbstractMouseSelection::getPositions(), and Gui::AbstractMouseSelection::Restart.
Referenced by mouseButtonEvent().
setClosed()
void FreehandSelection::setClosed (bool c)
References Gui::PolyPickerSelection::polyline, Gui::Polyline::setClosed(), and Gui::Polyline::setCloseStippled().
Referenced by MeshGui::MeshSelection::prepareFreehandSelection().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/MouseSelection.h
FreeCAD/src/Gui/MouseSelection.cpp