FreeCAD: WireJoiner Struct Reference
WireJoiner Struct Reference
Classes
struct BoxGetter
struct EdgeInfo
struct PntGetter
struct VertexInfo
Public Types
typedef bg::model::box< gp_Pnt > Box
typedef std::list< EdgeInfo > Edges
Public Member Functions
void add (const TopoDS_Edge &e, bool bbox=false)
void add (const TopoDS_Shape &shape, bool bbox=false)
void add (Edges::iterator it)
int findClosedWires (double tol=Precision::Confusion())
void join (double tol)
void remove (Edges::iterator it)
void splitEdges ()
WireJoiner ()
Static Public Member Functions
static bool getBBox (const TopoDS_Edge &e, Box &box)
static TopoDS_Wire makeCleanWire (Handle(ShapeExtend_WireData) wireData, double tol)
make a clean wire with sorted, oriented, connected, etc edges
Public Attributes
bgi::rtree< Edges::iterator, RParameters, BoxGetter > boxMap
BRep_Builder builder
TopoDS_Compound comp
Edges edges
bgi::rtree< VertexInfo, RParameters, PntGetter > vmap
Member Typedef Documentation
Box
typedef bg::model::box<gp_Pnt> WireJoiner::Box
Edges
typedef std::list<EdgeInfo> WireJoiner::Edges
Constructor & Destructor Documentation
WireJoiner()
WireJoiner::WireJoiner ()
Member Function Documentation
add() [1/3]
void WireJoiner::add (const TopoDS_Edge & e, bool bbox = false)
add() [2/3]
void WireJoiner::add (const TopoDS_Shape & shape, bool bbox = false)
add() [3/3]
void WireJoiner::add (Edges::iterator it)
Referenced by Path::Area::build().
findClosedWires()
int WireJoiner::findClosedWires (double tol = Precision::Confusion())
References WireJoiner::EdgeInfo::edge, WireJoiner::EdgeInfo::iStart, WireJoiner::EdgeInfo::iteration, WireJoiner::EdgeInfo::p1, WireJoiner::EdgeInfo::p2, Path::Area::showShape(), and WireJoiner::EdgeInfo::used.
Referenced by Path::Area::project().
getBBox()
static bool WireJoiner::getBBox (const TopoDS_Edge & e, Box & box) static
join()
void WireJoiner::join (double tol)
Referenced by Path::Area::build().
makeCleanWire()
static TopoDS_Wire WireJoiner::makeCleanWire (Handle(ShapeExtend_WireData) wireData, double tol) static
make a clean wire with sorted, oriented, connected, etc edges
remove()
void WireJoiner::remove (Edges::iterator it)
splitEdges()
void WireJoiner::splitEdges ()
Referenced by Path::Area::project().
Member Data Documentation
boxMap
bgi::rtree<Edges::iterator,RParameters, BoxGetter> WireJoiner::boxMap
builder
BRep_Builder WireJoiner::builder
comp
TopoDS_Compound WireJoiner::comp
Referenced by Path::Area::build(), and Path::Area::project().
edges
Edges WireJoiner::edges
Referenced by PathScripts.PathDressupHoldingTags.MapWireToTag::addEdge(), PathScripts.PathDressupHoldingTags.MapWireToTag::commandsForEdges(), PathScripts.PathDressupTag.ObjectDressup::execute(), PathScripts.PathDressupTag.ObjectDressup::pointIsOnPath(), Path::Area::project(), and PathScripts.PathDressupHoldingTags.MapWireToTag::shell().
vmap
bgi::rtree<VertexInfo,RParameters, PntGetter> WireJoiner::vmap
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/Mod/Path/App/Area.cpp