FreeCAD: Robot::Trajectory Class Reference
Robot::Trajectory Class Reference
The representation of a Trajectory.
#include <Trajectory.h>
Public Member Functions
void addWaypoint (const Waypoint &WPnt)
void deleteLast (unsigned int n=1)
delete the last n waypoints
void generateTrajectory (void)
double getDuration (int n=-1) const
return the duration (s) of the Trajectory if -1 or of the Waypoint with the given number
double getLength (int n=-1) const
return the Length (mm) of the Trajectory if -1 or of the Waypoint with the given number
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Base::Placement getPosition (double time) const
unsigned int getSize (void) const
std::string getUniqueWaypointName (const char *Name) const
double getVelocity (double time) const
const Waypoint & getWaypoint (unsigned int pos) const
const std::vector< Waypoint * > & getWaypoints (void) const
Trajectory & operator= (const Trajectory &)
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
Trajectory ()
Trajectory (const Trajectory &)
~Trajectory ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Attributes
KDL::Trajectory_Composite * pcTrajectory
std::vector< Waypoint * > vpcWaypoints
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The representation of a Trajectory.
Constructor & Destructor Documentation
Trajectory() [1/2]
Trajectory::Trajectory ()
Trajectory() [2/2]
Trajectory::Trajectory (const Trajectory & Trac)
References operator=().
~Trajectory()
Trajectory::~Trajectory ()
References pcTrajectory, and vpcWaypoints.
Member Function Documentation
addWaypoint()
void Trajectory::addWaypoint (const Waypoint & WPnt)
References getUniqueWaypointName(), Robot::Waypoint::Name, and vpcWaypoints.
Referenced by Robot::Edge2TracObject::execute(), Robot::TrajectoryPy::insertWaypoints(), and Robot::TrajectoryPy::PyInit().
deleteLast()
void Trajectory::deleteLast (unsigned int n = 1)
delete the last n waypoints
References vpcWaypoints.
Referenced by Robot::TrajectoryPy::deleteLast().
generateTrajectory()
void Trajectory::generateTrajectory (void)
References Robot::Waypoint::LINE, pcTrajectory, Robot::Waypoint::PTP, Robot::toFrame(), vpcWaypoints, and Robot::Waypoint::WAIT.
Referenced by Robot::TrajectoryPy::insertWaypoints(), operator=(), Robot::TrajectoryPy::PyInit(), and Restore().
getDuration()
double Trajectory::getDuration (int n = -1) const
return the duration (s) of the Trajectory if -1 or of the Waypoint with the given number
References pcTrajectory.
Referenced by Robot::Simulation::getDuration(), Robot::TrajectoryPy::representation(), RobotGui::TaskTrajectory::TaskTrajectory(), and RobotGui::TrajectorySimulate::TrajectorySimulate().
getLength()
double Trajectory::getLength (int n = -1) const
return the Length (mm) of the Trajectory if -1 or of the Waypoint with the given number
References pcTrajectory.
Referenced by Robot::Simulation::getLength(), and Robot::TrajectoryPy::representation().
getMemSize()
unsigned int Trajectory::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
getPosition()
Placement Trajectory::getPosition (double time) const
References pcTrajectory, and Robot::toPlacement().
Referenced by Robot::Simulation::getPosition(), Robot::Simulation::reset(), and Robot::Simulation::setToTime().
getSize()
unsigned int Robot::Trajectory::getSize (void) const
Referenced by Robot::TrajectoryPy::getWaypoints(), Robot::TrajectoryPy::representation(), Save(), Robot::Simulation::Simulation(), RobotGui::TaskTrajectory::TaskTrajectory(), RobotGui::TrajectorySimulate::TrajectorySimulate(), and RobotGui::ViewProviderTrajectory::updateData().
getUniqueWaypointName()
std::string Trajectory::getUniqueWaypointName (const char * Name) const
References vpcWaypoints.
Referenced by addWaypoint().
getVelocity()
double Trajectory::getVelocity (double time) const
References Base::Vector3< _Precision >::Length(), pcTrajectory, and draftgeoutils.general::vec().
Referenced by Robot::Simulation::getVelocity().
getWaypoint()
const Waypoint& Robot::Trajectory::getWaypoint (unsigned int pos) const
Referenced by RobotGui::TaskTrajectory::TaskTrajectory(), RobotGui::TrajectorySimulate::TrajectorySimulate(), and RobotGui::ViewProviderTrajectory::updateData().
getWaypoints()
const std::vector<Waypoint*>& Robot::Trajectory::getWaypoints (void) const
Referenced by Robot::TrajectoryCompound::execute(), and Robot::TrajectoryDressUpObject::execute().
operator=()
Trajectory & Trajectory::operator= (const Trajectory & Trac)
References generateTrajectory(), and vpcWaypoints.
Referenced by Trajectory().
Restore()
void Trajectory::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References generateTrajectory(), Base::XMLReader::getAttributeAsInteger(), Base::XMLReader::readElement(), Robot::Waypoint::Restore(), and vpcWaypoints.
Referenced by Robot::PropertyTrajectory::Restore().
Save()
void Trajectory::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References Base::Writer::decInd(), getSize(), Base::Writer::incInd(), Base::Writer::ind(), Base::Writer::Stream(), and vpcWaypoints.
Member Data Documentation
pcTrajectory
KDL::Trajectory_Composite* Robot::Trajectory::pcTrajectory protected
Referenced by generateTrajectory(), getDuration(), getLength(), getPosition(), getVelocity(), and ~Trajectory().
vpcWaypoints
std::vector<Waypoint*> Robot::Trajectory::vpcWaypoints protected
Referenced by addWaypoint(), deleteLast(), generateTrajectory(), getUniqueWaypointName(), operator=(), Restore(), Save(), and ~Trajectory().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Robot/App/Trajectory.h
Sources/FreeCAD/src/Mod/Robot/App/Trajectory.cpp