FreeCAD: ImageGui::ImageView Class Reference
ImageGui::ImageView Class Reference
#include <ImageView.h>
Public Slots
virtual void fitImage ()
virtual void oneToOneImage ()
Public Slots inherited from Gui::MDIView
virtual void setOverrideCursor (const QCursor &)
virtual void restoreOverrideCursor ()
virtual void print (QPrinter *printer)
Signals
void closeEventIgnored ()
Signals inherited from Gui::MDIView
void message (const QString &, int)
Public Member Functions
virtual void clearColorMap ()
virtual void clearImage ()
virtual int createColorMap (int numEntriesReq=0, bool Initialise=true)
virtual int createImageCopy (void *pSrcPixelData, unsigned long width, unsigned long height, int format, unsigned short numSigBitsPerSample, int displayMode=IV_DISPLAY_RESET)
virtual void enableFitImageAction (bool Enable)
virtual void enableMouseEvents (bool Enable)
virtual void enableOneToOneAction (bool Enable)
virtual void enableStatusBar (bool Enable)
virtual void enableToolBar (bool Enable)
const char * getName (void) const
returns the name of the view (important for messages)
virtual int getNumColorMapEntries () const
virtual void ignoreCloseEvent (bool ignoreCloseEvent)
ImageView (QWidget *parent)
bool onHasMsg (const char *) const
Message handler test.
bool onMsg (const char *, const char **)
Message handler.
void onUpdate (void)
get called when the document is updated
virtual int pointImageTo (void *pSrcPixelData, unsigned long width, unsigned long height, int format, unsigned short numSigBitsPerSample, bool takeOwnership, int displayMode=IV_DISPLAY_RESET)
virtual int setColorMapAlphaValue (int index, float value)
virtual int setColorMapBlueValue (int index, float value)
virtual int setColorMapGreenValue (int index, float value)
virtual int setColorMapRedValue (int index, float value)
virtual int setColorMapRGBAValue (int index, float red, float green, float blue, float alpha=1.0)
virtual ~ImageView ()
Public Member Functions inherited from Gui::MDIView
virtual bool canClose (void)
overwrite when checking on close state
virtual void deleteSelf ()
delete itself
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
View constructor Attach the view to the given document.
virtual bool onHasMsg (const char *pMsg) const
Message handler test.
virtual bool onMsg (const char *pMsg, const char **ppReturn)
Message handler.
virtual void onRelabel (Gui::Document *pDoc)
get called when the document is updated
virtual void viewAll ()
~MDIView ()
View destructor Detach the view from the document, if attached.
virtual QStringList undoActions () const
virtual QStringList redoActions () const
QSize minimumSizeHint () const
virtual void setCurrentViewMode (ViewMode mode)
If b is set to FullScreen the MDI view is displayed in full screen mode, if b is set to TopLevel then it is displayed as an own top-level window, otherwise (Normal) as tabbed window.
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=nullptr, std::string *subname=nullptr) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr) const
virtual bool containsViewProvider (const ViewProvider *) const
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
virtual void print ()
Print content of view.
virtual void printPdf ()
Print to PDF file.
virtual void printPreview ()
Show a preview dialog.
void savePrinterSettings (QPrinter *printer)
Save the printer configuration.
void restorePrinterSettings (QPrinter *printer)
Restore the printer configuration.
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=nullptr)
View constructor Attach the view to the given document.
virtual ~BaseView ()
View destructor Detach the view from the document, if attached!
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose (void)
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive (void) const
indicates if the view is in passive mode
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Protected Types
enum {
nothing = 0 , panning , zooming , selection ,
addselection
}
Protected Slots
virtual void drawGraphics ()
Protected Slots inherited from Gui::MDIView
virtual void windowStateChanged (MDIView *)
This method gets called from the main window this view is attached to whenever the window state of the active view changes.
Protected Member Functions
virtual void addSelect (int currX, int currY)
virtual void closeEvent (QCloseEvent *e)
virtual void createActions ()
virtual QString createStatusBarText ()
virtual QSize minimumSizeHint () const
virtual void mouseDoubleClickEvent (QMouseEvent *cEvent)
virtual void mouseMoveEvent (QMouseEvent *cEvent)
virtual void mousePressEvent (QMouseEvent *cEvent)
virtual void mouseReleaseEvent (QMouseEvent *cEvent)
virtual void select (int currX, int currY)
virtual void showEvent (QShowEvent *e)
virtual void showOriginalColors ()
virtual void startDrag ()
virtual void updateStatusBar ()
virtual void wheelEvent (QWheelEvent *cEvent)
virtual void zoom (int prevX, int prevY, int currX, int currY)
Protected Member Functions inherited from Gui::MDIView
void closeEvent (QCloseEvent *e)
void changeEvent (QEvent *e)
Protected Attributes
int dragStartWCx
int dragStartWCy
Protected Attributes inherited from Gui::MDIView
PyObject * pythonObject
Protected Attributes inherited from Gui::BaseView
bool bIsDetached
bool bIsPassive
Additional Inherited Members
Public Types inherited from Gui::MDIView
enum ViewMode { Child , TopLevel , FullScreen }
MDI view mode enum.
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
nothing
panning
zooming
selection
addselection
Constructor & Destructor Documentation
ImageView()
ImageView::ImageView (QWidget * parent)
References draftgeoutils.intersections::connect(), App::GetApplication(), ParameterGrp::GetBool(), and App::Application::GetParameterGroupByPath().
~ImageView()
ImageView::~ImageView () virtual
Member Function Documentation
addSelect()
void ImageView::addSelect (int currX, int currY) protected virtual
Referenced by mouseReleaseEvent().
clearColorMap()
void ImageView::clearColorMap () virtual
clearImage()
void ImageView::clearImage () virtual
References updateStatusBar().
closeEvent()
void ImageView::closeEvent (QCloseEvent * e) protected virtual
References Gui::MDIView::closeEvent(), and closeEventIgnored().
closeEventIgnored
void ImageGui::ImageView::closeEventIgnored () signal
Referenced by closeEvent().
createActions()
void ImageView::createActions () protected virtual
References draftgeoutils.intersections::connect(), fitImage(), ImageGui::image_oneToOne, ImageGui::image_stretch, and oneToOneImage().
createColorMap()
int ImageView::createColorMap (int numEntriesReq = 0, bool Initialise = true) virtual
createImageCopy()
int ImageView::createImageCopy (void * pSrcPixelData, unsigned long width, unsigned long height, int format, unsigned short numSigBitsPerSample, int displayMode = IV_DISPLAY_RESET) virtual
References showOriginalColors(), and updateStatusBar().
createStatusBarText()
QString ImageView::createStatusBarText () protected virtual
Referenced by updateStatusBar().
drawGraphics
void ImageView::drawGraphics () protected virtual slot
enableFitImageAction()
void ImageView::enableFitImageAction (bool Enable) virtual
enableMouseEvents()
void ImageView::enableMouseEvents (bool Enable) virtual
enableOneToOneAction()
void ImageView::enableOneToOneAction (bool Enable) virtual
enableStatusBar()
void ImageView::enableStatusBar (bool Enable) virtual
enableToolBar()
void ImageView::enableToolBar (bool Enable) virtual
fitImage
void ImageView::fitImage () virtual slot
Referenced by createActions().
getName()
const char * ImageGui::ImageView::getName (void) const virtual
returns the name of the view (important for messages)
Reimplemented from Gui::BaseView.
getNumColorMapEntries()
int ImageView::getNumColorMapEntries () const virtual
ignoreCloseEvent()
virtual void ImageGui::ImageView::ignoreCloseEvent (bool ignoreCloseEvent) virtual
References ignoreCloseEvent().
Referenced by ignoreCloseEvent().
minimumSizeHint()
QSize ImageView::minimumSizeHint () const protected virtual
mouseDoubleClickEvent()
void ImageView::mouseDoubleClickEvent (QMouseEvent * cEvent) protected virtual
References updateStatusBar().
mouseMoveEvent()
void ImageView::mouseMoveEvent (QMouseEvent * cEvent) protected virtual
References dragStartWCx, dragStartWCy, nothing, panning, updateStatusBar(), zoom(), and zooming.
mousePressEvent()
void ImageView::mousePressEvent (QMouseEvent * cEvent) protected virtual
References addselection, nothing, panning, selection, and startDrag().
mouseReleaseEvent()
void ImageView::mouseReleaseEvent (QMouseEvent * cEvent) protected virtual
References addSelect(), addselection, nothing, panning, select(), and selection.
oneToOneImage
void ImageView::oneToOneImage () virtual slot
References updateStatusBar().
Referenced by createActions().
onHasMsg()
bool ImageGui::ImageView::onHasMsg (const char * pMsg) const virtual
Message handler test.
Reimplemented from Gui::MDIView.
onMsg()
bool ImageGui::ImageView::onMsg (const char * pMsg, const char ** ppReturn) virtual
Message handler.
receive a message
Reimplemented from Gui::MDIView.
onUpdate()
void ImageGui::ImageView::onUpdate (void) virtual
get called when the document is updated
Reimplemented from Gui::BaseView.
pointImageTo()
int ImageView::pointImageTo (void * pSrcPixelData, unsigned long width, unsigned long height, int format, unsigned short numSigBitsPerSample, bool takeOwnership, int displayMode = IV_DISPLAY_RESET) virtual
References showOriginalColors(), and updateStatusBar().
select()
void ImageView::select (int currX, int currY) protected virtual
Referenced by mouseReleaseEvent().
setColorMapAlphaValue()
int ImageView::setColorMapAlphaValue (int index, float value) virtual
setColorMapBlueValue()
int ImageView::setColorMapBlueValue (int index, float value) virtual
setColorMapGreenValue()
int ImageView::setColorMapGreenValue (int index, float value) virtual
setColorMapRedValue()
int ImageView::setColorMapRedValue (int index, float value) virtual
setColorMapRGBAValue()
int ImageView::setColorMapRGBAValue (int index, float red, float green, float blue, float alpha = 1.0) virtual
showEvent()
void ImageView::showEvent (QShowEvent * e) protected virtual
showOriginalColors()
void ImageView::showOriginalColors () protected virtual
Referenced by createImageCopy(), and pointImageTo().
startDrag()
void ImageView::startDrag () protected virtual
References dragStartWCx, and dragStartWCy.
Referenced by mousePressEvent().
updateStatusBar()
void ImageView::updateStatusBar () protected virtual
References createStatusBarText().
Referenced by clearImage(), createImageCopy(), mouseDoubleClickEvent(), mouseMoveEvent(), oneToOneImage(), pointImageTo(), and wheelEvent().
wheelEvent()
void ImageView::wheelEvent (QWheelEvent * cEvent) protected virtual
References updateStatusBar().
zoom()
void ImageView::zoom (int prevX, int prevY, int currX, int currY) protected virtual
Referenced by mouseMoveEvent().
Member Data Documentation
dragStartWCx
int ImageGui::ImageView::dragStartWCx protected
Referenced by mouseMoveEvent(), and startDrag().
dragStartWCy
int ImageGui::ImageView::dragStartWCy protected
Referenced by mouseMoveEvent(), and startDrag().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Image/Gui/ImageView.h
FreeCAD/src/Mod/Image/Gui/ImageView.cpp