FreeCAD: AdaptivePath::EngagePoint Class Reference
AdaptivePath::EngagePoint Class Reference
Classes
struct EngageState
Public Member Functions
EngagePoint (const Paths &p_toolBoundPaths)
DoublePoint getCurrentDir ()
IntPoint getCurrentPoint ()
EngageState GetState ()
bool moveForward (double distance)
void moveToClosestPoint (const IntPoint &pt, double step)
bool nextEngagePoint (Adaptive2d *parent, ClearedArea &clearedArea, double step, double minCutArea, double maxCutArea, int maxPases=2)
bool nextPath ()
void ResetPasses ()
void SetPaths (const Paths &paths)
void SetState (const EngageState &new_state)
Constructor & Destructor Documentation
EngagePoint()
AdaptivePath::EngagePoint::EngagePoint (const Paths & p_toolBoundPaths)
References AdaptivePath::EngagePoint::EngageState::currentPathIndex, AdaptivePath::EngagePoint::EngageState::currentSegmentIndex, AdaptivePath::EngagePoint::EngageState::segmentPos, SetPaths(), and AdaptivePath::EngagePoint::EngageState::totalDistance.
Member Function Documentation
getCurrentDir()
DoublePoint AdaptivePath::EngagePoint::getCurrentDir ()
References AdaptivePath::EngagePoint::EngageState::currentPathIndex, AdaptivePath::EngagePoint::EngageState::currentSegmentIndex, AdaptivePath::DistanceSqrd(), ClipperLib::IntPoint::X, and ClipperLib::IntPoint::Y.
getCurrentPoint()
IntPoint AdaptivePath::EngagePoint::getCurrentPoint ()
References AdaptivePath::EngagePoint::EngageState::currentPathIndex, AdaptivePath::EngagePoint::EngageState::currentSegmentIndex, AdaptivePath::DistanceSqrd(), AdaptivePath::EngagePoint::EngageState::segmentPos, ClipperLib::IntPoint::X, and ClipperLib::IntPoint::Y.
Referenced by moveToClosestPoint(), and nextEngagePoint().
GetState()
EngageState AdaptivePath::EngagePoint::GetState ()
moveForward()
bool AdaptivePath::EngagePoint::moveForward (double distance)
References AdaptivePath::EngagePoint::EngageState::currentPathIndex, AdaptivePath::EngagePoint::EngageState::currentPathLength, AdaptivePath::EngagePoint::EngageState::currentSegmentIndex, AdaptivePath::EngagePoint::EngageState::segmentPos, and AdaptivePath::EngagePoint::EngageState::totalDistance.
Referenced by moveToClosestPoint(), and nextEngagePoint().
moveToClosestPoint()
void AdaptivePath::EngagePoint::moveToClosestPoint (const IntPoint & pt, double step)
References AdaptivePath::EngagePoint::EngageState::currentPathIndex, AdaptivePath::EngagePoint::EngageState::currentSegmentIndex, AdaptivePath::DistanceSqrd(), getCurrentPoint(), moveForward(), nextPath(), AdaptivePath::PopPathWithClosestPoint(), ResetPasses(), AdaptivePath::EngagePoint::EngageState::segmentPos, and AdaptivePath::EngagePoint::EngageState::totalDistance.
nextEngagePoint()
bool AdaptivePath::EngagePoint::nextEngagePoint (Adaptive2d * parent, ClearedArea & clearedArea, double step, double minCutArea, double maxCutArea, int maxPases = 2)
References getCurrentPoint(), moveForward(), nextPath(), AdaptivePath::EngagePoint::EngageState::passes, AdaptivePath::Perf_NextEngagePoint, AdaptivePath::PerfCounter::Start(), and AdaptivePath::PerfCounter::Stop().
nextPath()
bool AdaptivePath::EngagePoint::nextPath ()
References AdaptivePath::EngagePoint::EngageState::currentPathIndex, AdaptivePath::EngagePoint::EngageState::currentSegmentIndex, AdaptivePath::EngagePoint::EngageState::segmentPos, and AdaptivePath::EngagePoint::EngageState::totalDistance.
Referenced by moveToClosestPoint(), and nextEngagePoint().
ResetPasses()
void AdaptivePath::EngagePoint::ResetPasses ()
References AdaptivePath::EngagePoint::EngageState::passes.
Referenced by moveToClosestPoint().
SetPaths()
void AdaptivePath::EngagePoint::SetPaths (const Paths & paths)
References AdaptivePath::EngagePoint::EngageState::currentPathIndex, AdaptivePath::EngagePoint::EngageState::currentSegmentIndex, AdaptivePath::EngagePoint::EngageState::passes, AdaptivePath::EngagePoint::EngageState::segmentPos, and AdaptivePath::EngagePoint::EngageState::totalDistance.
Referenced by EngagePoint().
SetState()
void AdaptivePath::EngagePoint::SetState (const EngageState & new_state)
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Path/libarea/Adaptive.cpp