FreeCAD: PathScripts.PathJob Namespace Reference
PathScripts.PathJob Namespace Reference
Classes
class JobTemplate
class NotificationClass
class ObjectJob
Functions
def Create (name, base, templateFile=None)
def createModelResourceClone (obj, orig)
def createResourceClone (obj, orig, name, icon)
def Instances ()
def isArchPanelSheet (obj)
def isResourceClone (obj, propLink, resourceName)
def translate (context, text, disambig=None)
Variables
ArchPanel = LazyLoader('ArchPanel', globals(), 'ArchPanel')
Draft = LazyLoader('Draft', globals(), 'Draft')
Notification = NotificationClass()
Function Documentation
Create()
def PathScripts.PathJob.Create (name, base, templateFile = None)
Create(name, base, templateFile=None) ... creates a new job and all it's resources.
If a template file is specified the new job is initialized with the values from the template.
createModelResourceClone()
def PathScripts.PathJob.createModelResourceClone (obj, orig)
References PathScripts.PathJob.createResourceClone().
Referenced by PathScripts.PathJob.ObjectJob.setupBaseModel().
createResourceClone()
def PathScripts.PathJob.createResourceClone (obj, orig, name, icon)
References PathScripts.PathIconViewProvider.Attach(), and PathScripts.PathJob.isArchPanelSheet().
Referenced by PathScripts.PathJob.createModelResourceClone().
Instances()
def PathScripts.PathJob.Instances ()
Instances() ... Return all Jobs in the current active document.
isArchPanelSheet()
def PathScripts.PathJob.isArchPanelSheet (obj)
Referenced by PathScripts.PathJob.createResourceClone(), and PathScripts.PathJob.ObjectJob.isBaseCandidate().
isResourceClone()
def PathScripts.PathJob.isResourceClone (obj, propLink, resourceName)
Referenced by PathScripts.PathJob.ObjectJob.baseObject(), PathScripts.PathJob.ObjectJob.removeBase(), and PathScripts.PathJob.ObjectJob.resourceClone().
translate()
def PathScripts.PathJob.translate (context, text, disambig = None)
Variable Documentation
ArchPanel
PathScripts.PathJob.ArchPanel = LazyLoader('ArchPanel', globals(), 'ArchPanel')
Draft
PathScripts.PathJob.Draft = LazyLoader('Draft', globals(), 'Draft')
Notification
PathScripts.PathJob.Notification = NotificationClass()