FreeCAD: shipGZ.PlotAux.Plot Class Reference
shipGZ.PlotAux.Plot Class Reference
Public Member Functions
def plot (self, roll, gz)
def spreadSheet (self, roll, gz, draft, trim)
Member Function Documentation
plot()
def shipGZ.PlotAux.Plot.plot (self, roll, gz)
 Plot the GZ curve.
Position arguments:
roll -- List of roll angles (in degrees).
gz -- List of GZ values (in meters).
References Plot.axes(), Plot.figure(), Plot.grid(), Plot.plot(), Plot.xlabel(), and Plot.ylabel().
Referenced by Mod.PartDesign.WizardShaft.ShaftDiagram.Diagram.update().
spreadSheet()
def shipGZ.PlotAux.Plot.spreadSheet (self, roll, gz, draft, trim)
 Create a Spreadsheet with the results
Position arguments:
roll -- List of roll angles (in degrees).
gz -- List of GZ values (in meters).
draft -- List of equilibrium drafts (in meters).
trim -- List of equilibrium trim angles (in degrees).
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Ship/shipGZ/PlotAux.py