FreeCAD: ShapeCache Struct Reference
ShapeCache Struct Reference
Public Member Functions
bool getShape (const App::DocumentObject *obj, TopoShape &shape, const char *subname=0)
void init ()
void setShape (const App::DocumentObject *obj, const TopoShape &shape, const char *subname=0)
void slotChanged (const App::DocumentObject &obj, const App::Property &prop)
void slotClear (const App::DocumentObject &obj)
void slotDeleteDocument (const App::Document &doc)
Public Attributes
std::unordered_map< const App::Document *, std::map< std::pair< const App::DocumentObject *, std::string >,TopoShape > > cache
bool inited = false
Member Function Documentation
getShape()
bool ShapeCache::getShape (const App::DocumentObject * obj, TopoShape & shape, const char * subname = 0)
init()
void ShapeCache::init (void)
References draftgeoutils.faces::bind(), App::GetApplication(), App::Application::signalChangedObject, App::Application::signalDeletedObject, App::Application::signalDeleteDocument, slotChanged(), slotClear(), and slotDeleteDocument().
Referenced by DocumentObject.DocumentObject::onChanged().
setShape()
void ShapeCache::setShape (const App::DocumentObject * obj, const TopoShape & shape, const char * subname = 0)
slotChanged()
void ShapeCache::slotChanged (const App::DocumentObject & obj, const App::Property & prop)
References App::Property::getName().
Referenced by init().
slotClear()
void ShapeCache::slotClear (const App::DocumentObject & obj)
Referenced by init().
slotDeleteDocument()
void ShapeCache::slotDeleteDocument (const App::Document & doc)
Referenced by init().
Member Data Documentation
cache
std::unordered_map<const App::Document*, std::map<std::pair<const App::DocumentObject*, std::string> ,TopoShape> > ShapeCache::cache
Referenced by Part::Feature::clearShapeCache().
inited
bool ShapeCache::inited = false
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/Mod/Part/App/PartFeature.cpp