FreeCAD: App::FeaturePythonT< FeatureT > Class Template Reference
App::FeaturePythonT< FeatureT > Class Template Reference
Generic Python feature class which allows to behave every DocumentObject derived class as Python feature – simply by subclassing.
#include <FeaturePython.h>
Public Member Functions
FeaturePythonT ()
virtual ~FeaturePythonT ()
methods override DocumentObject
short mustExecute () const override
virtual DocumentObjectExecReturn * execute (void) override
recalculate the Feature
virtual const char * getViewProviderNameOverride (void) const override
virtual const char * getViewProviderName (void) const override
returns the type name of the ViewProvider
virtual App::DocumentObject * getSubObject (const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const override
virtual std::vector< std::string > getSubObjects (int reason=0) const override
virtual App::DocumentObject * getLinkedObject (bool recurse, Base::Matrix4D *mat, bool transform, int depth) const override
virtual bool hasChildElement () const override
return true to activate tree view group object handling
virtual int isElementVisible (const char *element) const override
Get sub-element visibility.
virtual int setElementVisible (const char *element, bool visible) override
Set sub-element visibility.
virtual bool canLinkProperties () const override
virtual bool allowDuplicateLabel () const override
virtual bool redirectSubName (std::ostringstream &ss, App::DocumentObject *topParent, App::DocumentObject *child) const override
virtual int canLoadPartial () const override
virtual void editProperty (const char *propName) override
PyObject * getPyObject (void) override
void setPyObject (PyObject *obj) override
FeaturePythonT (const FeaturePythonT &)=delete
FeaturePythonT (FeaturePythonT &&)=delete
FeaturePythonT & operator= (const FeaturePythonT &)=delete
FeaturePythonT & operator= (FeaturePythonT &&)=delete
virtual void onBeforeChange (const Property *prop) override
virtual void onBeforeChangeLabel (std::string &newLabel) override
virtual void onChanged (const Property *prop) override
virtual void onDocumentRestored () override
Detailed Description
template<class FeatureT>
class App::FeaturePythonT< FeatureT >
Generic Python feature class which allows to behave every DocumentObject derived class as Python feature – simply by subclassing.
Author
Werner Mayer
Constructor & Destructor Documentation
FeaturePythonT() [1/3]
template<class FeatureT > App::FeaturePythonT< FeatureT >::FeaturePythonT ()
~FeaturePythonT()
template<class FeatureT > virtual App::FeaturePythonT< FeatureT >::~FeaturePythonT () virtual
FeaturePythonT() [2/3]
template<class FeatureT > App::FeaturePythonT< FeatureT >::FeaturePythonT (const FeaturePythonT< FeatureT > &) delete
FeaturePythonT() [3/3]
template<class FeatureT > App::FeaturePythonT< FeatureT >::FeaturePythonT (FeaturePythonT< FeatureT > &&) delete
Member Function Documentation
allowDuplicateLabel()
template<class FeatureT > virtual bool App::FeaturePythonT< FeatureT >::allowDuplicateLabel () const override virtual
References App::FeaturePythonImp::Accepted, App::FeaturePythonImp::allowDuplicateLabel(), and App::FeaturePythonImp::Rejected.
canLinkProperties()
template<class FeatureT > virtual bool App::FeaturePythonT< FeatureT >::canLinkProperties () const override virtual
References App::FeaturePythonImp::Accepted, App::FeaturePythonImp::canLinkProperties(), and App::FeaturePythonImp::Rejected.
canLoadPartial()
template<class FeatureT > virtual int App::FeaturePythonT< FeatureT >::canLoadPartial () const override virtual
References App::FeaturePythonImp::canLoadPartial().
editProperty()
template<class FeatureT > virtual void App::FeaturePythonT< FeatureT >::editProperty (const char * propName) override virtual
References App::FeaturePythonImp::editProperty().
execute()
template<class FeatureT > virtual DocumentObjectExecReturn * App::FeaturePythonT< FeatureT >::execute (void) override virtual
recalculate the Feature
References App::FeaturePythonImp::execute(), and App::DocumentObject::StdReturn.
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), PathScripts.PathDressupDogbone.ObjectDressup::boneStateList(), ArchSite.Compass::buildCoordinates(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::generateTags(), ArchPanel.PanelCut::getWires(), ArchSchedule.CommandArchSchedule::IsActive(), Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), FeaturePython.DistanceBolt::onChanged(), PathScripts.PathStock.StockFromBase::onChanged(), PathScripts.PathStock.StockCreateBox::onChanged(), PathScripts.PathStock.StockCreateCylinder::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), draftobjects.patharray.PathArray::onDocumentRestored(), and draftobjects.pathtwistedarray.PathTwistedArray::onDocumentRestored().
getLinkedObject()
template<class FeatureT > virtual App::DocumentObject * App::FeaturePythonT< FeatureT >::getLinkedObject (bool recurse, Base::Matrix4D * mat, bool transform, int depth) const override virtual
References App::FeaturePythonImp::getLinkedObject().
getPyObject()
PyObject * App::FeaturePython::getPyObject (void) override
References App::FeaturePythonImp::getPyObject().
getSubObject()
template<class FeatureT > virtual App::DocumentObject * App::FeaturePythonT< FeatureT >::getSubObject (const char * subname, PyObject ** pyObj, Base::Matrix4D * mat, bool transform, int depth) const override virtual
References App::FeaturePythonImp::getSubObject().
getSubObjects()
template<class FeatureT > virtual std::vector< std::string > App::FeaturePythonT< FeatureT >::getSubObjects (int reason = 0) const override virtual
References App::FeaturePythonImp::getSubObjects().
getViewProviderName()
const char * App::PlacementPython::getViewProviderName (void) const override virtual
returns the type name of the ViewProvider
getViewProviderNameOverride()
template<class FeatureT > virtual const char * App::FeaturePythonT< FeatureT >::getViewProviderNameOverride (void) const override virtual
References App::FeaturePythonImp::getViewProviderName().
hasChildElement()
template<class FeatureT > virtual bool App::FeaturePythonT< FeatureT >::hasChildElement () const override virtual
return true to activate tree view group object handling
References App::FeaturePythonImp::Accepted, App::FeaturePythonImp::hasChildElement(), and App::FeaturePythonImp::Rejected.
isElementVisible()
template<class FeatureT > virtual int App::FeaturePythonT< FeatureT >::isElementVisible (const char * element) const override virtual
Get sub-element visibility.
References App::FeaturePythonImp::isElementVisible().
mustExecute()
template<class FeatureT > short App::FeaturePythonT< FeatureT >::mustExecute (void) const override
References App::FeaturePythonImp::mustExecute().
onBeforeChange()
template<class FeatureT > virtual void App::FeaturePythonT< FeatureT >::onBeforeChange (const Property * prop) override protected virtual
References App::FeaturePythonImp::onBeforeChange().
Referenced by PathScripts.PathGui.QuantitySpinBox::updateProperty().
onBeforeChangeLabel()
template<class FeatureT > virtual void App::FeaturePythonT< FeatureT >::onBeforeChangeLabel (std::string & newLabel) override protected virtual
References App::FeaturePythonImp::onBeforeChangeLabel().
onChanged()
template<class FeatureT > virtual void App::FeaturePythonT< FeatureT >::onChanged (const Property * prop) override protected virtual
References App::PropertyPythonObject::getValue(), App::FeaturePythonImp::init(), and App::FeaturePythonImp::onChanged().
Referenced by ArchStructure.CommandStructuralSystem::Activated(), draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSite.Compass::buildCoordinates(), draftobjects.wire.Wire::execute(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchPanel.ViewProviderPanelSheet::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), and draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData().
onDocumentRestored()
template<class FeatureT > virtual void App::FeaturePythonT< FeatureT >::onDocumentRestored () override protected virtual
References App::FeaturePythonImp::onDocumentRestored().
operator=() [1/2]
template<class FeatureT > FeaturePythonT & App::FeaturePythonT< FeatureT >::operator= (const FeaturePythonT< FeatureT > &) delete
operator=() [2/2]
template<class FeatureT > FeaturePythonT & App::FeaturePythonT< FeatureT >::operator= (FeaturePythonT< FeatureT > &&) delete
redirectSubName()
template<class FeatureT > virtual bool App::FeaturePythonT< FeatureT >::redirectSubName (std::ostringstream & ss, App::DocumentObject * topParent, App::DocumentObject * child) const override virtual
References App::FeaturePythonImp::Accepted, App::FeaturePythonImp::redirectSubName(), and App::FeaturePythonImp::Rejected.
setElementVisible()
template<class FeatureT > virtual int App::FeaturePythonT< FeatureT >::setElementVisible (const char * element, bool visible) override virtual
Set sub-element visibility.
References App::FeaturePythonImp::setElementVisible().
setPyObject()
template<class FeatureT > void App::FeaturePythonT< FeatureT >::setPyObject (PyObject * obj) override
The documentation for this class was generated from the following files:
FreeCAD/src/App/FeaturePython.h
FreeCAD/src/App/FeaturePython.cpp
FreeCAD/src/App/Link.cpp
FreeCAD/src/App/Placement.cpp