FreeCAD: feminout.writeFenicsXDMF Namespace Reference
feminout.writeFenicsXDMF Namespace Reference
Functions
def numpy_array_to_str (npa)
def points_to_numpy (pts, dim=3)
def tuples_to_numpy (tpls, numbers_per_line)
def write_fenics_mesh_codim_xdmf (fem_mesh_obj, topologynode, nodes_dict, codim=0, encoding=ENCODING_ASCII)
def write_fenics_mesh_points_xdmf (fem_mesh_obj, geometrynode, encoding=ENCODING_ASCII)
def write_fenics_mesh_scalar_cellfunctions (name, cell_array, attributenode, encoding=ENCODING_ASCII)
def write_fenics_mesh_xdmf (fem_mesh_obj, outputfile, group_values_dict={}, encoding=ENCODING_ASCII)
Variables
string ENCODING_ASCII = "ASCII"
string ENCODING_HDF5 = "HDF5"
dictionary FreeCAD_Group_Dimensions
dictionary FreeCAD_to_Fenics_XDMF_dict
Function Documentation
numpy_array_to_str()
def feminout.writeFenicsXDMF.numpy_array_to_str (npa)
Referenced by feminout.writeFenicsXDMF.write_fenics_mesh_codim_xdmf(), feminout.writeFenicsXDMF.write_fenics_mesh_points_xdmf(), and feminout.writeFenicsXDMF.write_fenics_mesh_scalar_cellfunctions().
points_to_numpy()
def feminout.writeFenicsXDMF.points_to_numpy (pts, dim = 3)
Referenced by feminout.writeFenicsXDMF.write_fenics_mesh_points_xdmf().
tuples_to_numpy()
def feminout.writeFenicsXDMF.tuples_to_numpy (tpls, numbers_per_line)
Referenced by feminout.writeFenicsXDMF.write_fenics_mesh_codim_xdmf().
write_fenics_mesh_codim_xdmf()
def feminout.writeFenicsXDMF.write_fenics_mesh_codim_xdmf (fem_mesh_obj, topologynode, nodes_dict, codim = 0, encoding = ENCODING_ASCII)
References feminout.writeFenicsXDMF.numpy_array_to_str(), and feminout.writeFenicsXDMF.tuples_to_numpy().
Referenced by feminout.writeFenicsXDMF.write_fenics_mesh_xdmf().
write_fenics_mesh_points_xdmf()
def feminout.writeFenicsXDMF.write_fenics_mesh_points_xdmf (fem_mesh_obj, geometrynode, encoding = ENCODING_ASCII)
    Writes either into hdf5 file or into open mesh file
References feminout.writeFenicsXDMF.numpy_array_to_str(), and feminout.writeFenicsXDMF.points_to_numpy().
Referenced by feminout.writeFenicsXDMF.write_fenics_mesh_xdmf().
write_fenics_mesh_scalar_cellfunctions()
def feminout.writeFenicsXDMF.write_fenics_mesh_scalar_cellfunctions (name, cell_array, attributenode, encoding = ENCODING_ASCII)
References feminout.writeFenicsXDMF.numpy_array_to_str().
Referenced by feminout.writeFenicsXDMF.write_fenics_mesh_xdmf().
write_fenics_mesh_xdmf()
def feminout.writeFenicsXDMF.write_fenics_mesh_xdmf (fem_mesh_obj, outputfile, group_values_dict = {}, encoding = ENCODING_ASCII)
    For the export of xdmf.
References feminout.writeFenicsXDMF.write_fenics_mesh_codim_xdmf(), feminout.writeFenicsXDMF.write_fenics_mesh_points_xdmf(), and feminout.writeFenicsXDMF.write_fenics_mesh_scalar_cellfunctions().
Variable Documentation
ENCODING_ASCII
string feminout.writeFenicsXDMF.ENCODING_ASCII = "ASCII"
ENCODING_HDF5
string feminout.writeFenicsXDMF.ENCODING_HDF5 = "HDF5"
FreeCAD_Group_Dimensions
dictionary feminout.writeFenicsXDMF.FreeCAD_Group_Dimensions
Initial value:
 =  {
     "Vertex": 0,
     "Edge": 1,
     "Face": 2,
     "Volume": 3
 }
FreeCAD_to_Fenics_XDMF_dict
dictionary feminout.writeFenicsXDMF.FreeCAD_to_Fenics_XDMF_dict
Initial value:
 =  {
     ("Node", 1): ("polyvertex", 1),
     ("Edge", 1): ("polyline", 2),
     ("Edge", 2): ("edge_3", 3),
     ("Triangle", 1): ("triangle", 3),
     ("Triangle", 2): ("tri_6", 6),
     ("Tetra", 1): ("tetrahedron", 4),
     ("Tetra", 2): ("tet_10", 10)
 }