FreeCAD: importFCMat Namespace Reference
importFCMat Namespace Reference
Functions
def decode (name)
def export (exportList, filename)
def insert (filename, docname)
def open (filename)
def read (filename)
def write (filename, dictionary, write_group_section=True)
Variables
pythonopen = open
unicode = str
Function Documentation
decode()
def importFCMat.decode (name)
export()
def importFCMat.export (exportList, filename)
insert()
def importFCMat.insert (filename, docname)
References read().
open()
def importFCMat.open (filename)
References read().
read()
def importFCMat.read (filename)
References pythonopen.
Referenced by insert(), and open().
write()
def importFCMat.write (filename, dictionary, write_group_section = True)
References pythonopen.
Variable Documentation
pythonopen
importFCMat.pythonopen = open
Referenced by read(), and write().
unicode
importFCMat.unicode = str