FreeCAD: FemGui::TaskFemConstraintContact Class Reference
FemGui::TaskFemConstraintContact Class Reference
#include <TaskFemConstraintContact.h>
Public Member Functions
double get_Friction () const
double get_Slope () const
const std::string getReferences () const
TaskFemConstraintContact (ViewProviderFemConstraintContact *ConstraintView, QWidget *parent=nullptr)
~TaskFemConstraintContact ()
Public Member Functions inherited from FemGui::TaskFemConstraint
const std::string getReferences (const std::vector< std::string > &items) const
virtual const std::string getReferences (void) const
const std::string getScale () const
TaskFemConstraint (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="")
virtual ~TaskFemConstraint ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Protected Member Functions
void changeEvent (QEvent *e)
Protected Member Functions inherited from FemGui::TaskFemConstraint
virtual void changeEvent (QEvent *e)
void createDeleteAction (QListWidget *parentList)
bool KeyEvent (QEvent *e)
virtual void keyPressEvent (QKeyEvent *ke)
const QString makeRefText (const App::DocumentObject *obj, const std::string &subName) const
const QString makeRefText (const std::string &objName, const std::string &subName) const
virtual void onSelectionChanged (const Gui::SelectionChanges &)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Types inherited from FemGui::TaskFemConstraint
enum { seldir , selref , selloc , selnone }
Protected Slots inherited from FemGui::TaskFemConstraint
void onButtonReference (const bool pressed=true)
void onButtonWizCancel ()
void onButtonWizOk ()
void onReferenceDeleted (const int row)
void setSelection (QListWidgetItem *item)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from FemGui::TaskFemConstraint
Gui::WeakPtrT< ViewProviderFemConstraint > ConstraintView
QAction * deleteAction
QWidget * proxy
enum FemGui::TaskFemConstraint:: { ... } selectionMode
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskFemConstraintContact()
TaskFemConstraintContact::TaskFemConstraintContact (ViewProviderFemConstraintContact * ConstraintView, QWidget * parent = nullptr)
References Ui_TaskFemConstraintContact::btnAddMaster, Ui_TaskFemConstraintContact::btnAddSlave, Ui_TaskFemConstraintContact::btnRemoveMaster, Ui_TaskFemConstraintContact::btnRemoveSlave, draftgeoutils.intersections::connect(), FemGui::TaskFemConstraint::ConstraintView, Fem::ConstraintContact::Friction, App::PropertyLinkSubList::getSubValues(), App::PropertyFloat::getValue(), App::PropertyLinkSubList::getValues(), QSint::ActionGroup::groupLayout(), Ui_TaskFemConstraintContact::lw_referencesMaster, Ui_TaskFemConstraintContact::lw_referencesSlave, FemGui::TaskFemConstraint::makeRefText(), FemGui::TaskFemConstraint::proxy, Fem::Constraint::References, Gui::InputField::setMinimum(), FemGui::TaskFemConstraint::setSelection(), Ui_TaskFemConstraintContact::setupUi(), Gui::InputField::setValue(), Fem::ConstraintContact::Slope, Ui_TaskFemConstraintContact::spFriction, and Ui_TaskFemConstraintContact::spSlope.
~TaskFemConstraintContact()
TaskFemConstraintContact::~TaskFemConstraintContact ()
Member Function Documentation
changeEvent()
void TaskFemConstraintContact::changeEvent (QEvent * e) protected virtual
Reimplemented from FemGui::TaskFemConstraint.
get_Friction()
double TaskFemConstraintContact::get_Friction () const
References Ui_TaskFemConstraintContact::spFriction.
Referenced by FemGui::TaskDlgFemConstraintContact::accept().
get_Slope()
double TaskFemConstraintContact::get_Slope () const
References Gui::InputField::rawValue, and Ui_TaskFemConstraintContact::spSlope.
Referenced by FemGui::TaskDlgFemConstraintContact::accept().
getReferences()
const std::string TaskFemConstraintContact::getReferences (void) const virtual
Reimplemented from FemGui::TaskFemConstraint.
References FemGui::TaskFemConstraint::getReferences(), Ui_TaskFemConstraintContact::lw_referencesMaster, and Ui_TaskFemConstraintContact::lw_referencesSlave.
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintContact.h
FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintContact.cpp