FreeCAD: importSHP Namespace Reference
importSHP Namespace Reference
Functions
def checkShapeFileLibrary ()
def getFields (filename)
def insert (filename, docname, record=None)
def open (filename)
Variables
pythonopen = open
translate = FreeCAD.Qt.translate
Function Documentation
checkShapeFileLibrary()
def importSHP.checkShapeFileLibrary ()
Looks for and/or installs the ShapeFile library
References pythonopen, and addonmanager_utilities.urlopen().
Referenced by getFields(), and insert().
getFields()
def importSHP.getFields (filename)
returns the fields found in the given file
References checkShapeFileLibrary().
insert()
def importSHP.insert (filename, docname, record = None)
imports a SHP/SHX/DBF file in an existing FreeCAD document.
the record attribute is an optional string indicating the shapefile
field to use to give elevations to the different shapes. If not used,
if running in GUI mode, a dialog will pop up to ask the user which
field to use.
References checkShapeFileLibrary().
Referenced by open().
open()
def importSHP.open (filename)
opens a SHP/SHX/DBF file in a new FreeCAD document
References importIFCHelper.decode(), and insert().
Variable Documentation
pythonopen
importSHP.pythonopen = open
Referenced by checkShapeFileLibrary().
translate
importSHP.translate = FreeCAD.Qt.translate