FreeCAD: MeshCore::MeshFastBuilder Class Reference
MeshCore::MeshFastBuilder Class Reference
Class for creating the mesh structure by adding facets.
#include <Builder.h>
Classes
struct Private
Public Types
typedef int size_type
Public Member Functions
void AddFacet (const Base::Vector3f *facetPoints)
Add new facet.
void AddFacet (const MeshGeomFacet &facetPoints)
Add new facet.
void Finish ()
Finishes building up the mesh structure.
void Initialize (size_type ctFacets)
Initializes the class.
MeshFastBuilder (MeshKernel &rclM)
~MeshFastBuilder (void)
Detailed Description
Class for creating the mesh structure by adding facets.
Building the structure needs 3 steps:
initializing
adding the facets
finishing
// Sample Code for building a mesh structure
MeshFastBuilder builder(someMeshReference);
builder.Initialize(numberOfFacets);
...
for (...)
  builder.AddFacet(...);
...
builder.Finish();
Author
Werner Mayer
Member Typedef Documentation
size_type
typedef int MeshCore::MeshFastBuilder::size_type
Constructor & Destructor Documentation
MeshFastBuilder()
MeshFastBuilder::MeshFastBuilder (MeshKernel & rclM)
~MeshFastBuilder()
MeshFastBuilder::~MeshFastBuilder (void)
Member Function Documentation
AddFacet() [1/2]
void MeshFastBuilder::AddFacet (const Base::Vector3f * facetPoints)
Add new facet.
References Base::Vector3< _Precision >::x, MeshCore::MeshFastBuilder::Private::Vertex::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by MeshCore::MeshInput::LoadAsciiSTL(), and MeshCore::MeshInput::LoadBinarySTL().
AddFacet() [2/2]
void MeshFastBuilder::AddFacet (const MeshGeomFacet & facetPoints)
Add new facet.
References MeshCore::MeshFastBuilder::Private::Vertex::x.
Finish()
void MeshFastBuilder::Finish ()
Finishes building up the mesh structure.
Must be done after adding facets.
References MeshCore::parallel_sort().
Referenced by MeshCore::MeshInput::LoadAsciiSTL(), and MeshCore::MeshInput::LoadBinarySTL().
Initialize()
void MeshFastBuilder::Initialize (size_type ctFacets)
Initializes the class.
Must be done before adding facets
Parameters
ctFacets count of facets.
Referenced by MeshCore::MeshInput::LoadAsciiSTL(), and MeshCore::MeshInput::LoadBinarySTL().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Builder.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Builder.cpp