FreeCAD: App::PropertyLinkList Class Reference
App::PropertyLinkList Class Reference
#include <PropertyLinks.h>
Public Member Functions
virtual bool adjustLink (const std::set< App::DocumentObject * > &inList) override
Called to adjust the link to avoid potential cyclic dependency.
virtual void breakLink (App::DocumentObject *obj, bool clear) override
Called to reset this link property.
virtual Property * Copy (void) const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
virtual Property * CopyOnLinkReplace (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const override
Return a copy of the property if the link replacement affects this property.
DocumentObject * find (const char *sub, int *pindex=0) const
DocumentObject * find (const std::string &, int *pindex=0) const
virtual const char * getEditorName (void) const override
Get the class name of the associated property editor item.
virtual void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=0, bool newStyle=true) const override
Obtain the linked objects.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
virtual void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
PropertyLinkList ()
A constructor.
virtual void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
void set1Value (int idx, DocumentObject *const &value) override
virtual void setSize (int newSize) override
virtual void setSize (int newSize, const_reference def) override
void setValues (const std::vector< DocumentObject * > &) override
Sets the property.
virtual ~PropertyLinkList ()
A destructor.
Public Member Functions inherited from App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >
virtual int getSize (void) const override
const std::vector< DocumentObject * > & getValue (void) const
const std::vector< DocumentObject * > & getValues (void) const
const_reference operator[] (int idx) const
virtual void set1Value (int index, const_reference value)
virtual void setPyObject (PyObject *value) override
virtual void setSize (int newSize, const_reference def)
void setValue (const std::vector< DocumentObject * > &newValues=std::vector< DocumentObject * >())
void setValue (const_reference value)
Public Member Functions inherited from App::PropertyLinkBase
void checkLabelReferences (const std::vector< std::string > &subs, bool reset=true)
Check subnames for label registration.
virtual int checkRestore (std::string *msg=0) const
Test if the link is restored unchanged.
virtual Property * CopyOnImportExternal (const std::map< std::string, std::string > &nameMap) const
Return a copy of the property if any changes caused by importing external linked object.
virtual Property * CopyOnLabelChange (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const
Update object label reference in this property.
void getLinkedElements (std::map< App::DocumentObject *, std::vector< std::string > > &elements, bool newStyle=true, bool all=true) const
Helper function to return a map of linked object and its subname references.
template<class T >
void getLinkedObjects (T &inserter, bool all=false) const
Helper function to return linked objects using an std::inserter.
std::map< App::DocumentObject *, std::vector< std::string > > linkedElements (bool newStyle=true, bool all=true) const
Helper function to return a map of linked object and its subname references.
std::vector< App::DocumentObject * > linkedObjects (bool all=false) const
Helper function to return all linked objects of this property.
PropertyLinkBase ()
virtual bool referenceChanged () const
Test if the element reference has changed after restore.
void registerLabelReferences (std::vector< std::string > &&labels, bool reset=true)
Register label reference for future object relabel update.
void setAllowExternal (bool allow)
Enable/disable temporary holding external object without throwing exception.
virtual void setAllowPartial (bool enable)
bool testFlag (int flag) const
void unregisterElementReference ()
Clear internal element reference registration.
void unregisterLabelReferences ()
Clear internal label references registration.
virtual void updateElementReference (App::DocumentObject *feature, bool reverse=false, bool notify=false)
Link type property interface APIs These APIs are moved here so that any type of property can have the property link behavior, e.g.
virtual ~PropertyLinkBase ()
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
const char * getName (void) const
get the name of this property in the belonging container
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::ScopedLink
LinkScope getScope ()
Get the links scope Retrieve what kind of links are allowed.
void setScope (LinkScope scope)
Set the links scope Allows to define what kind of links are allowed.
Public Member Functions inherited from App::PropertyListsBase
void clearTouchList ()
const std::set< int > & getTouchList () const
Protected Member Functions
DocumentObject * getPyValue (PyObject *item) const override
Protected Member Functions inherited from App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >
void setPyValues (const std::vector< PyObject * > &vals, const std::vector< int > &indices) override
Protected Member Functions inherited from App::PropertyLinkBase
virtual void hasSetValue () override
Gets called by all setValue() methods after the value has changed.
void setFlag (int flag, bool value=true)
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Protected Member Functions inherited from App::AtomicPropertyChangeInterface< P >
AtomicPropertyChangeInterface ()
Additional Inherited Members
Public Types inherited from App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >
typedef AtomicPropertyChangeInterface< PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase > >::AtomicPropertyChange atomic_change
typedef ListT::const_reference const_reference
typedef std::vector< DocumentObject * > list_type
typedef PropertyLinkListBase parent_type
Public Types inherited from App::PropertyLinkBase
enum LinkFlags {
LinkAllowExternal , LinkDetached , LinkRestoring , LinkAllowPartial ,
LinkRestoreLabel
}
typedef std::pair< std::string, std::string > ShadowSub
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , PropStaticBegin = 21 ,
PropDynamic = 21 , PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 ,
PropTransient = 25 , PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 ,
User1 = 28 , User2 = 29 , User3 = 30 , User4 = 31
}
Static Public Member Functions inherited from App::PropertyLinkBase
static void breakLinks (App::DocumentObject *link, const std::vector< App::DocumentObject * > &objs, bool clear)
Helper function for breaking link properties.
static const char * exportSubName (std::string &output, const App::DocumentObject *obj, const char *subname, bool first_obj=false)
Helper function to export a subname reference.
static void getLabelReferences (std::vector< std::string > &labels, const char *subname)
Helper function to extract labels from a subname reference.
static std::string importSubName (Base::XMLReader &reader, const char *sub, bool &restoreLabel)
Helper function to import a subname reference.
static void restoreLabelReference (const App::DocumentObject *obj, std::string &sub, ShadowSub *shadow=0)
Helper function to restore label references during import.
static App::DocumentObject * tryImport (const App::Document *doc, const App::DocumentObject *obj, const std::map< std::string, std::string > &nameMap)
Helper function for link import operation.
static std::string tryImportSubName (const App::DocumentObject *obj, const char *sub, const App::Document *doc, const std::map< std::string, std::string > &nameMap)
Helper function for link import operation.
static std::pair< App::DocumentObject *, std::string > tryReplaceLink (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const char *sub=0)
Helper functions.
static std::pair< App::DocumentObject *, std::vector< std::string > > tryReplaceLinkSubs (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const std::vector< std::string > &subs)
Helper function to check and replace a link with multiple subname references.
static void updateElementReferences (DocumentObject *feature, bool reverse=false)
Update all element references in all link properties of feature.
static std::string updateLabelReference (const App::DocumentObject *linked, const char *subname, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
Helper function to update subname reference on label change.
static std::vector< std::pair< Property *, std::unique_ptr< Property > > > updateLabelReferences (App::DocumentObject *obj, const char *newLabel)
Helper function to collect changed property when an object re-label.
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Public Attributes inherited from App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >
friend atomic_change
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Protected Attributes inherited from App::AtomicPropertyChangeInterface< P >
bool hasChanged
int signalCounter
Counter for invoking transaction start/stop.
Constructor & Destructor Documentation
PropertyLinkList()
PropertyLinkList::PropertyLinkList ()
A constructor.
A more elaborate description of the constructor.
Referenced by Copy(), and CopyOnLinkReplace().
~PropertyLinkList()
PropertyLinkList::~PropertyLinkList () virtual
A destructor.
A more elaborate description of the destructor.
References Base::Persistence::getClassTypeId(), App::Property::getContainer(), App::Hidden, Base::BaseClass::isDerivedFrom(), and App::DocumentObject::testStatus().
Member Function Documentation
adjustLink()
bool PropertyLinkList::adjustLink (const std::set< App::DocumentObject * > & inList) override virtual
Called to adjust the link to avoid potential cyclic dependency.
Parameters
inList recursive in-list of the would-be parent
Returns
Return whether the link has been adjusted
This function tries to correct the link to avoid any (sub)object inside in-list. If the adjustment is impossible, exception will be raised
Implements App::PropertyLinkBase.
breakLink()
void PropertyLinkList::breakLink (App::DocumentObject * obj, bool clear) override virtual
Called to reset this link property.
Parameters
obj reset link property if it is linked to this object
clear if true, then also reset property if the owner of this property is obj
See also
breakLinks()
Implements App::PropertyLinkBase.
References App::Property::getContainer(), and setValues().
Copy()
Property * PropertyLinkList::Copy (void) const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References PropertyLinkList().
CopyOnLinkReplace()
Property * PropertyLinkList::CopyOnLinkReplace (const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj) const override virtual
Return a copy of the property if the link replacement affects this property.
Parameters
owner the parent object whose link property is to be replace. Note that The parent may not be the container of this property. Link sub property can use this opportunity to adjust its relative links.
oldObj object to be replaced
newObj object to replace with
Returns
Return a copy of the property that is adjusted for the link replacement operation.
Implements App::PropertyLinkBase.
References App::Property::getContainer(), draftfunctions.move::move(), PropertyLinkList(), and App::PropertyLinkBase::tryReplaceLink().
find() [1/2]
DocumentObject* App::PropertyLinkList::find (const char * sub, int * pindex = 0) const
References DraftVecUtils::find().
find() [2/2]
DocumentObject * PropertyLinkList::find (const std::string & name, int * pindex = 0) const
Referenced by App::GeoFeatureGroupExtension::extensionGetSubObject(), and App::GroupExtension::extensionGetSubObject().
getEditorName()
virtual const char* App::PropertyLinkList::getEditorName (void) const override virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
getLinks()
void PropertyLinkList::getLinks (std::vector< App::DocumentObject * > & objs, bool all = false, std::vector< std::string > * subs = 0, bool newStyle = true) const override virtual
Obtain the linked objects.
Parameters
objs hold the returned linked objects on output
all if true, then return all the linked object regardless of this LinkScope. If false, then return only if the LinkScope is not hidden.
sub if given, then return subname references.
newStyle whether to return new or old style subname reference
Implements App::PropertyLinkBase.
References App::Hidden.
getMemSize()
unsigned int PropertyLinkList::getMemSize (void) const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
See also
Base::Persistence
Reimplemented from App::Property.
getPyObject()
PyObject * PropertyLinkList::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
References App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >::getSize().
getPyValue()
DocumentObject * PropertyLinkList::getPyValue (PyObject * item) const override protected virtual
Implements App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >.
References App::DocumentObjectPy::Type.
Paste()
void PropertyLinkList::Paste (const Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References Base::Persistence::getClassTypeId(), Base::BaseClass::isDerivedFrom(), and setValues().
Restore()
void PropertyLinkList::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References Base::XMLReader::getAttribute(), Base::XMLReader::getAttributeAsInteger(), Base::Persistence::getClassTypeId(), App::Property::getContainer(), App::DocumentObject::getDocument(), App::Document::getName(), Base::XMLReader::getName(), Base::Type::getName(), App::Document::getObject(), Base::Persistence::getTypeId(), Base::Type::isDerivedFrom(), Base::XMLReader::isVerbose(), Base::XMLReader::readElement(), Base::XMLReader::readEndElement(), and setValues().
Referenced by Part::BodyBase::handleChangedPropertyName(), PartDesign::Boolean::handleChangedPropertyName(), and App::PropertyXLinkSubList::upgrade().
Save()
void PropertyLinkList::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References Base::Writer::decInd(), App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >::getSize(), Base::Writer::incInd(), Base::Writer::ind(), and Base::Writer::Stream().
set1Value()
void PropertyLinkList::set1Value (int idx, DocumentObject *const & value) override
References Base::Persistence::getClassTypeId(), App::Property::getContainer(), App::Hidden, Base::BaseClass::isDerivedFrom(), App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >::set1Value(), and App::DocumentObject::testStatus().
setSize() [1/2]
void PropertyLinkList::setSize (int newSize) override virtual
Reimplemented from App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >.
References App::Property::getContainer(), and App::Hidden.
Referenced by setSize().
setSize() [2/2]
void PropertyLinkList::setSize (int newSize, const_reference def) override virtual
References App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >::getSize(), and setSize().
setValues()
void PropertyLinkList::setValues (const std::vector< DocumentObject * > & lValue) override virtual
Sets the property.
Reimplemented from App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >.
References App::Property::getContainer(), App::Hidden, App::PropertyLinkBase::LinkAllowExternal, App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >::setValues(), and App::PropertyLinkBase::testFlag().
Referenced by PartDesignGui::TaskPipeParameters::accept(), PathGui::TaskDlgPathCompound::accept(), ReverseEngineeringGui::Segmentation::accept(), App::GroupExtension::addObjects(), App::GeoFeatureGroupExtension::addObjects(), TechDraw::DrawViewCollection::addView(), breakLink(), TechDrawGui::TaskDetail::createDetail(), PartGui::ViewProviderMultiFuse::dragObject(), PartGui::ViewProviderMultiCommon::dragObject(), PartGui::ViewProviderCompound::dragObject(), PathGui::ViewProviderArea::dragObject(), PathGui::ViewProviderPathShape::dragObject(), PartGui::ViewProviderMultiFuse::dropObject(), PartGui::ViewProviderMultiCommon::dropObject(), PartGui::ViewProviderCompound::dropObject(), PathGui::ViewProviderArea::dropObject(), PathGui::ViewProviderPathShape::dropObject(), App::GeoFeatureGroupExtension::extensionOnChanged(), App::GroupExtension::extensionOnChanged(), PartDesignGui::TaskTransformedParameters::indexesMoved(), PartDesign::Body::insertObject(), Gui::ViewProviderOrigin::onDelete(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), PartDesignGui::TaskTransformedParameters::originalSelected(), Paste(), TechDraw::DrawViewCollection::rebuildViewList(), PartDesign::Body::removeObject(), App::GroupExtension::removeObjects(), App::GeoFeatureGroupExtension::removeObjects(), TechDraw::DrawViewCollection::removeView(), Restore(), App::GroupExtension::setObjects(), App::Origin::setupObject(), and TechDraw::DrawViewCollection::unsetupObject().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/App/PropertyLinks.h
Sources/FreeCAD/src/App/PropertyLinks.cpp