FreeCAD: FemGui::Ui_DlgSettingsFemGmshImp Class Reference
FemGui::Ui_DlgSettingsFemGmshImp Class Reference
#include <ui_DlgSettingsFemGmsh.h>
Public Member Functions
void retranslateUi (QWidget *FemGui__DlgSettingsFemGmshImp)
void setupUi (QWidget *FemGui__DlgSettingsFemGmshImp)
Public Attributes
Gui::PrefCheckBox * cb_gmsh_binary_std
Gui::PrefFileChooser * fc_gmsh_binary_path
QGroupBox * gb_gmsh_param
QGridLayout * gridLayout
QLabel * l_gmsh_binary_path
QVBoxLayout * verticalLayout
QVBoxLayout * verticalLayout_2
QSpacerItem * verticalSpacer
Member Function Documentation
retranslateUi()
void FemGui::Ui_DlgSettingsFemGmshImp::retranslateUi (QWidget * FemGui__DlgSettingsFemGmshImp)
References cb_gmsh_binary_std, fc_gmsh_binary_path, gb_gmsh_param, l_gmsh_binary_path, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void FemGui::Ui_DlgSettingsFemGmshImp::setupUi (QWidget * FemGui__DlgSettingsFemGmshImp)
References cb_gmsh_binary_std, draftgeoutils.intersections::connect(), fc_gmsh_binary_path, gb_gmsh_param, gridLayout, l_gmsh_binary_path, retranslateUi(), verticalLayout, verticalLayout_2, and verticalSpacer.
Member Data Documentation
cb_gmsh_binary_std
Gui::PrefCheckBox* FemGui::Ui_DlgSettingsFemGmshImp::cb_gmsh_binary_std
Referenced by retranslateUi(), and setupUi().
fc_gmsh_binary_path
Gui::PrefFileChooser* FemGui::Ui_DlgSettingsFemGmshImp::fc_gmsh_binary_path
Referenced by retranslateUi(), and setupUi().
gb_gmsh_param
QGroupBox* FemGui::Ui_DlgSettingsFemGmshImp::gb_gmsh_param
Referenced by retranslateUi(), and setupUi().
gridLayout
QGridLayout* FemGui::Ui_DlgSettingsFemGmshImp::gridLayout
Referenced by setupUi().
l_gmsh_binary_path
QLabel* FemGui::Ui_DlgSettingsFemGmshImp::l_gmsh_binary_path
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* FemGui::Ui_DlgSettingsFemGmshImp::verticalLayout
Referenced by setupUi().
verticalLayout_2
QVBoxLayout* FemGui::Ui_DlgSettingsFemGmshImp::verticalLayout_2
Referenced by setupUi().
verticalSpacer
QSpacerItem* FemGui::Ui_DlgSettingsFemGmshImp::verticalSpacer
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Fem/Gui/ui_DlgSettingsFemGmsh.h