FreeCAD: DrawSketchHandlerGenConstraint Class Reference
DrawSketchHandlerGenConstraint Class Reference
Public Member Functions
DrawSketchHandlerGenConstraint (CmdSketcherConstraint *_cmd)
virtual void mouseMove (Base::Vector2d) override
virtual bool pressButton (Base::Vector2d) override
virtual bool releaseButton (Base::Vector2d onSketchPos) override
virtual ~DrawSketchHandlerGenConstraint ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void activate (ViewProviderSketch *)
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::PointPos::none, bool createowncommand=true)
void deactivate ()
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual void mouseMove (Base::Vector2d onSketchPos)=0
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual bool pressButton (Base::Vector2d onSketchPos)=0
virtual void quit (void)
virtual void registerPressedKey (bool, int)
virtual bool releaseButton (Base::Vector2d onSketchPos)=0
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Member Functions
void resetOngoingSequences ()
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
virtual QString getCrosshairCursorSVGName () const
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
void updateCursor ()
updates the actCursor with the icon by calling getCrosshairCursorSVGName(), enabling to set data member dependent icons (i.e.
void unsetCursor (void)
restitutes the cursor that was in use at the moment of starting the DrawSketchHandler (i.e. oldCursor)
void applyCursor (void)
restitutes the DSH cached cursor (e.g. without any tail due to autoconstraints, ...)
unsigned long getCrosshairColor ()
returns the color to be used for the crosshair (configurable as a parameter)
qreal devicePixelRatio ()
functions to set the cursor to a given svgName (to be migrated to NVI style)
void drawEdit (const std::vector< Base::Vector2d > &EditCurve)
void drawEdit (const std::list< std::vector< Base::Vector2d > > &list)
void drawEdit (const std::vector< Part::Geometry * > &geometries)
void drawEditMarkers (const std::vector< Base::Vector2d > &EditMarkers, unsigned int augmentationlevel=0)
void setAxisPickStyle (bool on)
void moveCursorToSketchPoint (Base::Vector2d point)
void preselectAtPoint (Base::Vector2d point)
void drawPositionAtCursor (const Base::Vector2d &position)
void drawDirectionAtCursor (const Base::Vector2d &position, const Base::Vector2d &origin)
int getPreselectPoint (void) const
int getPreselectCurve (void) const
int getPreselectCross (void) const
Sketcher::SketchObject * getSketchObject ()
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
Protected Attributes
unsigned int allowedSelTypes = 0
CmdSketcherConstraint * cmd
std::set< int > ongoingSequences
indices of currently ongoing sequences in cmd->allowedSequences
GenericConstraintSelection * selFilterGate = nullptr
std::vector< SelIdPair > selSeq
unsigned int seqIndex
Index within the selection sequences active.
Protected Attributes inherited from SketcherGui::DrawSketchHandler
ViewProviderSketch * sketchgui
QCursor oldCursor
QCursor actCursor
QPixmap actCursorPixmap
Constructor & Destructor Documentation
DrawSketchHandlerGenConstraint()
DrawSketchHandlerGenConstraint::DrawSketchHandlerGenConstraint (CmdSketcherConstraint * _cmd)
~DrawSketchHandlerGenConstraint()
virtual DrawSketchHandlerGenConstraint::~DrawSketchHandlerGenConstraint () virtual
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
mouseMove()
virtual void DrawSketchHandlerGenConstraint::mouseMove (Base::Vector2d) override virtual
Implements SketcherGui::DrawSketchHandler.
pressButton()
virtual bool DrawSketchHandlerGenConstraint::pressButton (Base::Vector2d) override virtual
Implements SketcherGui::DrawSketchHandler.
releaseButton()
virtual bool DrawSketchHandlerGenConstraint::releaseButton (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::SelectionSingleton::addSelection(), CmdSketcherConstraint::allowedSelSequences, allowedSelTypes, CmdSketcherConstraint::applyConstraint(), Gui::SelectionSingleton::clearSelection(), cmd, SketcherGui::SelIdPair::GeoId, App::DocumentObject::getDocument(), Sketcher::SketchObject::getGeoVertexIndex(), App::Document::getName(), App::DocumentObject::getNameInDocument(), SketcherGui::DrawSketchHandler::getPreselectCross(), SketcherGui::DrawSketchHandler::getPreselectCurve(), SketcherGui::DrawSketchHandler::getPreselectPoint(), SketcherGui::ViewProviderSketch::getSketchObject(), Sketcher::none, ongoingSequences, SketcherGui::SelIdPair::PosId, resetOngoingSequences(), Gui::Selection(), SketcherGui::SelEdge, SketcherGui::SelEdgeOrAxis, SketcherGui::SelExternalEdge, selFilterGate, SketcherGui::SelHAxis, SketcherGui::SelRoot, selSeq, SketcherGui::SelUnknown, SketcherGui::SelVAxis, SketcherGui::SelVertex, SketcherGui::SelVertexOrRoot, seqIndex, SketcherGui::GenericConstraintSelection::setAllowedSelTypes(), SketcherGui::DrawSketchHandler::sketchgui, Sketcher::start, Base::Vector2d::x, and Base::Vector2d::y.
resetOngoingSequences()
void DrawSketchHandlerGenConstraint::resetOngoingSequences () protected
References CmdSketcherConstraint::allowedSelSequences, allowedSelTypes, Gui::SelectionSingleton::clearSelection(), cmd, ongoingSequences, Gui::Selection(), selFilterGate, seqIndex, and SketcherGui::GenericConstraintSelection::setAllowedSelTypes().
Referenced by releaseButton().
Member Data Documentation
allowedSelTypes
unsigned int DrawSketchHandlerGenConstraint::allowedSelTypes = 0 protected
Referenced by releaseButton(), and resetOngoingSequences().
cmd
CmdSketcherConstraint* DrawSketchHandlerGenConstraint::cmd protected
Referenced by threadmilling_generator._Thread::g4LeadInOut(), threadmilling_generator._Thread::isG3(), releaseButton(), and resetOngoingSequences().
ongoingSequences
std::set<int> DrawSketchHandlerGenConstraint::ongoingSequences protected
indices of currently ongoing sequences in cmd->allowedSequences
Referenced by releaseButton(), and resetOngoingSequences().
selFilterGate
GenericConstraintSelection* DrawSketchHandlerGenConstraint::selFilterGate = nullptr protected
Referenced by releaseButton(), and resetOngoingSequences().
selSeq
std::vector<SelIdPair> DrawSketchHandlerGenConstraint::selSeq protected
Referenced by releaseButton().
seqIndex
unsigned int DrawSketchHandlerGenConstraint::seqIndex protected
Index within the selection sequences active.
Referenced by releaseButton(), and resetOngoingSequences().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/CommandConstraints.cpp