FreeCAD: ifc2x3.ifcshellbasedsurfacemodel Class Reference
ifc2x3.ifcshellbasedsurfacemodel Class Reference
Public Member Functions
def dim ()
def sbsmboundary ()
Public Member Functions inherited from ifc2x3.ifcrepresentationitem
def layerassignments ()
def styledbyitem ()
Public Attributes
sbsmboundary
Detailed Description
Entity ifcshellbasedsurfacemodel definition.
        :param sbsmboundary
        :type sbsmboundary:SET(1,None,'ifcshell', scope = schema_scope)
        :param dim
        :type dim:ifcdimensioncount
Member Function Documentation
dim()
def ifc2x3.ifcshellbasedsurfacemodel.dim ()
Referenced by ifc2x3.ifcpointonsurface.dim(), ifc2x3.ifcvector.dim(), ifc4.ifccompositecurvesegment.dim(), ifc4.ifcplacement.dim(), ifc4.ifccartesiantransformationoperator.dim(), ifc4.ifcgeometricset.dim(), ifc4.ifcpointoncurve.dim(), ifc4.ifcpointonsurface.dim(), and ifc4.ifcvector.dim().
sbsmboundary()
def ifc2x3.ifcshellbasedsurfacemodel.sbsmboundary ()
References ifc2x3.ifcshellbasedsurfacemodel._sbsmboundary, and ifc2x3.ifcshellbasedsurfacemodel.sbsmboundary.
Member Data Documentation
sbsmboundary
ifc2x3.ifcshellbasedsurfacemodel.sbsmboundary
Referenced by ifc2x3.ifcshellbasedsurfacemodel.sbsmboundary().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Import/App/ifc2x3.py