FreeCAD: VISCOUS_3D::_MeshOfSolid Struct Reference
VISCOUS_3D::_MeshOfSolid Struct Reference
SMESH_ProxyMesh computed by _ViscousBuilder for a SOLID. It is stored in a SMESH_subMesh of the SOLID as SMESH_subMeshEventListenerData.
Public Member Functions
SMESH_ProxyMesh::SubMesh * getFaceSubM (const TopoDS_Face &F, bool create=false)
void setNode2Node (const SMDS_MeshNode *srcNode, const SMDS_MeshNode *proxyNode, const SMESH_ProxyMesh::SubMesh *subMesh)
Public Member Functions inherited from SMESH_ProxyMesh
SMDS_ElemIteratorPtr GetFaces () const
Returns iterator on all faces of the mesh taking into account substitutions To be used in case of mesh without shape.
SMDS_ElemIteratorPtr GetFaces (const TopoDS_Shape &face) const
Returns iterator on all faces on the shape taking into account substitutions.
SMESH_Mesh * GetMesh () const
SMESHDS_Mesh * GetMeshDS () const
Returns mesh DS.
const SMDS_MeshNode * GetProxyNode (const SMDS_MeshNode *node) const
Returns the proxy node of a node; the input node is returned if no proxy exists.
const SubMesh * GetProxySubMesh (const TopoDS_Shape &shape) const
Returns the proxy sub-mesh of a shape; it can be NULL.
const SMESHDS_SubMesh * GetSubMesh (const TopoDS_Shape &shape) const
Returns the submesh of a shape; it can be a proxy sub-mesh.
bool IsTemporary (const SMDS_MeshElement *elem) const
Return true if the element is a temporary one.
int NbFaces () const
Return total nb of faces taking into account substitutions.
int NbProxySubMeshes () const
Returns number of proxy sub-meshes.
SMESH_ProxyMesh ()
Constructor; mesh must be set by a descendant class.
SMESH_ProxyMesh (const SMESH_Mesh &mesh)
SMESH_ProxyMesh (std::vector< SMESH_ProxyMesh::Ptr > &components)
Make a proxy mesh from components. Components become empty.
virtual ~SMESH_ProxyMesh ()
Destructor deletes proxy submeshes and tmp elemens.
Public Member Functions inherited from SMESH_subMeshEventListenerData
bool IsDeletable () const
SMESH_subMeshEventListenerData (bool isDeletable)
virtual ~SMESH_subMeshEventListenerData ()
Additional Inherited Members
Public Types inherited from SMESH_ProxyMesh
typedef boost::shared_ptr< SMESH_ProxyMesh > Ptr
typedef std::map< const SMDS_MeshNode *, const SMDS_MeshNode *, TIDCompare > TN2NMap
Static Public Member Functions inherited from SMESH_subMeshEventListenerData
static SMESH_subMeshEventListenerData * MakeData (SMESH_subMesh *dependentSM, const int type=0)
Create a default listener data.
Public Attributes inherited from SMESH_subMeshEventListenerData
bool myIsDeletable
if true, it will be deleted by SMESH_subMesh
std::list< SMESH_subMesh * > mySubMeshes
int myType
to recognize data type
Protected Member Functions inherited from SMESH_ProxyMesh
SubMesh * findProxySubMesh (int shapeIndex=0) const
Returns a proxy sub-mesh.
SubMesh * getProxySubMesh (const TopoDS_Shape &shape=TopoDS_Shape())
Returns a proxy sub-mesh; it is created if not yet exists.
SubMesh * getProxySubMesh (int shapeIndex)
Returns a proxy sub-mesh; it is created if not yet exists.
virtual SubMesh * newSubmesh (int index=0) const
void removeTmpElement (const SMDS_MeshElement *elem)
Removes tmp elements from the _mesh.
void setMesh (const SMESH_Mesh &mesh)
void setNode2Node (const SMDS_MeshNode *srcNode, const SMDS_MeshNode *proxyNode, const SubMesh *subMesh)
Set node-node correspondence.
int shapeIndex (const TopoDS_Shape &shape) const
Returns index of a shape.
void storeTmpElement (const SMDS_MeshElement *elem)
Stores tmp element residing the _mesh.
bool takeProxySubMesh (const TopoDS_Shape &shape, SMESH_ProxyMesh *proxyMesh)
Move proxy sub-mesh from other proxy mesh to this, returns true if sub-mesh found.
void takeTmpElemsInMesh (SMESH_ProxyMesh *proxyMesh)
Move tmp elements residing the _mesh from other proxy mesh to this.
Detailed Description
SMESH_ProxyMesh computed by _ViscousBuilder for a SOLID. It is stored in a SMESH_subMesh of the SOLID as SMESH_subMeshEventListenerData.
Member Function Documentation
getFaceSubM()
SMESH_ProxyMesh::SubMesh* VISCOUS_3D::_MeshOfSolid::getFaceSubM (const TopoDS_Face & F, bool create = false)
References femsolver.elmer.equations.elasticity::create(), SMESH_ProxyMesh::getProxySubMesh(), and SMESH_ProxyMesh::shapeIndex().
setNode2Node()
void VISCOUS_3D::_MeshOfSolid::setNode2Node (const SMDS_MeshNode * srcNode, const SMDS_MeshNode * proxyNode, const SMESH_ProxyMesh::SubMesh * subMesh)
References SMESH_ProxyMesh::setNode2Node().
Referenced by VISCOUS_3D::_ViscousBuilder::MakeN2NMap().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_ViscousLayers.cpp