FreeCAD: Base::XMLReader Class Reference
Base::XMLReader Class Reference
The XML reader class This is an important helper class for the store and retrieval system of objects in FreeCAD.
#include <Reader.h>
Classes
struct FileEntry
Public Types
enum ReaderStatus { PartialRestore = 0, PartialRestoreInDocumentObject = 1, PartialRestoreInProperty = 2, PartialRestoreInObject = 3 }
Public Member Functions
bool isValid () const
bool isVerbose () const
void setVerbose (bool on)
XMLReader (const char *FileName, std::istream &)
open the file and read the first element
~XMLReader ()
Parser handling
const char * localName (void) const
get the local name of the current Element
int level () const
get the current element level
void readElement (const char *ElementName=0)
read until a start element is found (<name>) or start-end element (<name/>) (with special name if given)
void readEndElement (const char *ElementName=0, int level=-1)
read until an end element is found
void readCharacters (void)
read until characters are found
void readBinFile (const char *)
read binary file
Attribute handling
unsigned int getAttributeCount (void) const
get the number of attributes of the current element
bool hasAttribute (const char *AttrName) const
check if the read element has a special attribute
long getAttributeAsInteger (const char *AttrName) const
return the named attribute as an interer (does type checking)
unsigned long getAttributeAsUnsigned (const char *AttrName) const
double getAttributeAsFloat (const char *AttrName) const
return the named attribute as a double floating point (does type checking)
const char * getAttribute (const char *AttrName) const
return the named attribute as a double floating point (does type checking)
Protected Member Functions
Content handler
virtual void startDocument ()
virtual void endDocument ()
virtual void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE_QUALIFIER Attributes &attrs)
virtual void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
virtual void characters (const XMLCh *const chars, const XMLSize_t length)
virtual void ignorableWhitespace (const XMLCh *const chars, const XMLSize_t length)
Lexical handler
virtual void startCDATA ()
virtual void endCDATA ()
Document handler
virtual void resetDocument ()
additional file reading
int DocumentSchema
Schema Version of the document.
std::string ProgramVersion
Version of FreeCAD that wrote this document.
int FileVersion
Version of the file format.
std::vector< FileEntry > FileList
const char * addFile (const char *Name, Base::Persistence *Object)
add a read request of a persistent object
void readFiles (zipios::ZipInputStream &zipstream) const
process the requested file writes
const std::vector< std::string > & getFilenames () const
get all registered file names
bool isRegistered (Base::Persistence *Object) const
virtual void addName (const char *, const char *)
virtual const char * getName (const char *) const
virtual bool doNameMapping () const
void setPartialRestore (bool on)
sets simultaneously the global and local PartialRestore bits
void clearPartialRestoreDocumentObject (void)
void clearPartialRestoreProperty (void)
void clearPartialRestoreObject (void)
bool testStatus (ReaderStatus pos) const
return the status bits
void setStatus (ReaderStatus pos, bool on)
set the status bits
bool read (void)
read the next element
Error handler
typedef std::map< std::string, std::string > AttrMapType
int Level
std::string LocalName
std::string Characters
unsigned int CharacterCount
std::map< std::string, std::string > AttrMap
enum Base::XMLReader:: { ... } ReadType
XERCES_CPP_NAMESPACE_QUALIFIER SAX2XMLReader * parser
XERCES_CPP_NAMESPACE_QUALIFIER XMLPScanToken token
std::vector< std::string > FileNames
std::bitset< 32 > StatusBits
void warning (const XERCES_CPP_NAMESPACE_QUALIFIER SAXParseException &exc)
void error (const XERCES_CPP_NAMESPACE_QUALIFIER SAXParseException &exc)
void fatalError (const XERCES_CPP_NAMESPACE_QUALIFIER SAXParseException &exc)
void resetErrors ()
Detailed Description
The XML reader class This is an important helper class for the store and retrieval system of objects in FreeCAD.
These classes mainly inherit the App::Persitance base class and implement the Restore() method.
The reader gets mainly initialized by the App::Document on retrieving a document out of a file. From there subsequently the Restore() method will by called on all object stored.
A simple example is the Restore of App::PropertyString:
void PropertyString::Save (short indent,std::ostream &str)
{
    str << "<String value=\"" <<  _cValue.c_str() <<"\"/>" ;
}
void PropertyString::Restore(Base::Reader &reader)
{
    // read my Element
    reader.readElement("String");
    // get the value of my Attribute
    _cValue = reader.getAttribute("value");
}
An more complicated example is the retrieval of the App::PropertyContainer:
void PropertyContainer::Save (short indent,std::ostream &str)
{
    std::map<std::string,Property*> Map;
    getPropertyMap(Map);
    str << ind(indent) << "<Properties Count=\"" << Map.size() << "\">" << endl;
    std::map<std::string,Property*>::iterator it;
    for(it = Map.begin(); it != Map.end(); ++it)
    {
        str << ind(indent+1) << "<Property name=\"" << it->first << "\" type=\"" << it->second->getTypeId().getName() << "\">" ;
        it->second->Save(indent+2,str);
        str << "</Property>" << endl;
    }
    str << ind(indent) << "</Properties>" << endl;
}
void PropertyContainer::Restore(Base::Reader &reader)
{
    reader.readElement("Properties");
    int Cnt = reader.getAttributeAsInteger("Count");
    for(int i=0 ;i<Cnt ;i++)
    {
        reader.readElement("Property");
        string PropName = reader.getAttribute("name");
        Property* prop = getPropertyByName(PropName.c_str());
        if(prop)
            prop->Restore(reader);
        reader.readEndElement("Property");
    }
    reader.readEndElement("Properties");
}
See also
Base::Persistence
Author
Juergen Riegel
Member Typedef Documentation
AttrMapType
typedef std::map<std::string,std::string> Base::XMLReader::AttrMapType protected
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
Chars
StartDocument
EndDocument
StartElement
StartEndElement
EndElement
StartCDATA
EndCDATA
ReaderStatus
enum Base::XMLReader::ReaderStatus
Enumerator
PartialRestore
PartialRestoreInDocumentObject
PartialRestoreInProperty
PartialRestoreInObject
Constructor & Destructor Documentation
XMLReader()
Base::XMLReader::XMLReader (const char * FileName, std::istream & str)
open the file and read the first element
References parser, and token.
~XMLReader()
Base::XMLReader::~XMLReader ()
Member Function Documentation
addFile()
const char * Base::XMLReader::addFile (const char * Name, Base::Persistence * Object)
add a read request of a persistent object
References Base::XMLReader::FileEntry::FileName, and Base::XMLReader::FileEntry::Object.
Referenced by Fem::FemMesh::Restore(), Path::Toolpath::Restore(), App::PropertyFileIncluded::Restore(), App::PropertyPythonObject::Restore(), App::VRMLObject::Restore(), Gui::Document::Restore(), Fem::PropertyPostDataObject::Restore(), Inspection::PropertyDistanceList::Restore(), Mesh::PropertyNormalList::Restore(), Mesh::PropertyCurvatureList::Restore(), Mesh::PropertyMeshKernel::Restore(), Part::PropertyPartShape::Restore(), Part::PropertyFilletEdges::Restore(), Path::PropertyPath::Restore(), Points::PointKernel::Restore(), Points::PropertyGreyValueList::Restore(), Points::PropertyNormalList::Restore(), Points::PropertyCurvatureList::Restore(), Points::PropertyPointKernel::Restore(), App::PropertyVectorList::Restore(), App::PropertyPlacementList::Restore(), App::PropertyFloatList::Restore(), App::PropertyColorList::Restore(), and App::PropertyMaterialList::Restore().
addName()
void Base::XMLReader::addName (const char * , const char *) virtual
Reimplemented in Gui::XMLMergeReader, and App::XMLMergeReader.
Referenced by App::Document::readObjects().
characters()
void Base::XMLReader::characters (const XMLCh *const chars, const XMLSize_t length) protected virtual
References StrX::c_str().
clearPartialRestoreDocumentObject()
void Base::XMLReader::clearPartialRestoreDocumentObject (void)
Referenced by App::Document::readObjects().
clearPartialRestoreObject()
void Base::XMLReader::clearPartialRestoreObject (void)
Referenced by Part::PropertyGeometryList::Restore(), TechDraw::PropertyCenterLineList::Restore(), TechDraw::PropertyCosmeticEdgeList::Restore(), TechDraw::PropertyCosmeticVertexList::Restore(), and TechDraw::PropertyGeomFormatList::Restore().
clearPartialRestoreProperty()
void Base::XMLReader::clearPartialRestoreProperty (void)
Referenced by App::PropertyContainer::Restore().
doNameMapping()
bool Base::XMLReader::doNameMapping () const virtual
Reimplemented in Gui::XMLMergeReader, and App::XMLMergeReader.
Referenced by App::PropertyLinkBase::importSubName(), and App::Document::readObjects().
endCDATA()
void Base::XMLReader::endCDATA () protected virtual
endDocument()
void Base::XMLReader::endDocument () protected virtual
endElement()
void Base::XMLReader::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) protected virtual
References StrX::c_str().
error()
void Base::XMLReader::error (const XERCES_CPP_NAMESPACE_QUALIFIER SAXParseException & exc) protected
Referenced by FreeCADInit.FCADLogger::report().
fatalError()
void Base::XMLReader::fatalError (const XERCES_CPP_NAMESPACE_QUALIFIER SAXParseException & exc) protected
getAttribute()
const char * Base::XMLReader::getAttribute (const char * AttrName) const
return the named attribute as a double floating point (does type checking)
Referenced by App::Document::importObjects(), Gui::Document::importObjects(), Spreadsheet::PropertySheet::pasteCells(), App::Document::readObjects(), Fem::FemMesh::Restore(), Part::Geometry::Restore(), Path::Command::Restore(), Path::Toolpath::Restore(), Path::Tool::Restore(), Robot::Waypoint::Restore(), TechDraw::CosmeticVertex::Restore(), TechDraw::CosmeticEdge::Restore(), TechDraw::CenterLine::Restore(), TechDraw::GeomFormat::Restore(), TechDraw::Vertex::Restore(), Part::GeometryDefaultExtension< T >::Restore(), Sketcher::Constraint::Restore(), Sketcher::ExternalGeometryExtension::Restore(), Sketcher::SketchGeometryExtension::Restore(), TechDraw::BaseGeom::Restore(), App::PropertyContainer::Restore(), App::PropertyFileIncluded::Restore(), App::PropertyPythonObject::Restore(), App::PropertyPath::Restore(), App::PropertyEnumeration::Restore(), App::PropertyMap::Restore(), App::PropertyString::Restore(), App::PropertyUUID::Restore(), App::PropertyBool::Restore(), Gui::DocumentItem::ExpandInfo::restore(), Fem::PropertyPostDataObject::Restore(), Inspection::PropertyDistanceList::Restore(), Mesh::PropertyNormalList::Restore(), Mesh::PropertyCurvatureList::Restore(), Mesh::PropertyMeshKernel::Restore(), Part::Box::Restore(), Part::PropertyGeometryList::Restore(), Part::PropertyPartShape::Restore(), Part::PropertyFilletEdges::Restore(), PartDesign::Fillet::Restore(), PartDesign::ProfileBased::Restore(), PartDesign::Transformed::Restore(), Path::PropertyPath::Restore(), Points::PointKernel::Restore(), Points::PropertyGreyValueList::Restore(), Points::PropertyNormalList::Restore(), Points::PropertyCurvatureList::Restore(), Points::PropertyPointKernel::Restore(), Spreadsheet::PropertyColumnWidths::Restore(), Spreadsheet::PropertyRowHeights::Restore(), TechDraw::PropertyCenterLineList::Restore(), TechDraw::PropertyCosmeticEdgeList::Restore(), TechDraw::PropertyCosmeticVertexList::Restore(), TechDraw::PropertyGeomFormatList::Restore(), App::Document::Restore(), App::PropertyExpressionEngine::Restore(), App::PropertyVectorList::Restore(), App::PropertyPlacementList::Restore(), App::PropertyLink::Restore(), App::PropertyLinkList::Restore(), App::PropertyLinkSub::Restore(), App::PropertyLinkSubList::Restore(), App::PropertyXLink::Restore(), App::PropertyXLinkContainer::Restore(), App::PropertyFloatList::Restore(), App::PropertyStringList::Restore(), App::PropertyBoolList::Restore(), App::PropertyColorList::Restore(), App::PropertyMaterialList::Restore(), Part::Primitive::Restore(), PartDesign::Chamfer::Restore(), Spreadsheet::PropertySheet::Restore(), Spreadsheet::Cell::restore(), App::DynamicProperty::restore(), Gui::Document::RestoreDocFile(), and App::ExtensionContainer::restoreExtensions().
getAttributeAsFloat()
double Base::XMLReader::getAttributeAsFloat (const char * AttrName) const
return the named attribute as a double floating point (does type checking)
Referenced by MeshCore::MeshInput::LoadXML(), Fem::FemMesh::Restore(), Part::GeomPoint::Restore(), Part::GeomBSplineCurve::Restore(), Part::GeomCircle::Restore(), Part::GeomArcOfCircle::Restore(), Part::GeomEllipse::Restore(), Part::GeomArcOfEllipse::Restore(), Part::GeomHyperbola::Restore(), Part::GeomArcOfHyperbola::Restore(), Part::GeomParabola::Restore(), Part::GeomArcOfParabola::Restore(), Part::GeomLine::Restore(), Part::GeomLineSegment::Restore(), Part::Geom2dPoint::Restore(), Part::Geom2dCircle::Restore(), Part::Geom2dArcOfCircle::Restore(), Part::Geom2dEllipse::Restore(), Part::Geom2dArcOfEllipse::Restore(), Part::Geom2dHyperbola::Restore(), Part::Geom2dArcOfHyperbola::Restore(), Part::Geom2dParabola::Restore(), Part::Geom2dArcOfParabola::Restore(), Part::Geom2dLineSegment::Restore(), Path::Tool::Restore(), Robot::Robot6Axis::Restore(), Robot::Waypoint::Restore(), TechDraw::CosmeticVertex::Restore(), TechDraw::CosmeticEdge::Restore(), TechDraw::CenterLine::Restore(), TechDraw::GeomFormat::Restore(), TechDraw::Vertex::Restore(), Sketcher::Constraint::Restore(), TechDraw::Circle::Restore(), TechDraw::AOC::Restore(), TechDraw::Generic::Restore(), App::PropertyMatrix::Restore(), App::PropertyFloat::Restore(), App::PropertyMaterial::Restore(), Part::GeometryDefaultExtension< T >::Restore(), Path::PropertyPath::Restore(), App::PropertyExpressionEngine::Restore(), App::PropertyVector::Restore(), App::PropertyPlacement::Restore(), Part::Geom2dConic::RestoreAxis(), and Part::Geom2dArcOfConic::RestoreAxis().
getAttributeAsInteger()
long Base::XMLReader::getAttributeAsInteger (const char * AttrName) const
return the named attribute as an interer (does type checking)
Referenced by App::Document::importObjects(), Gui::Document::importObjects(), MeshCore::MeshInput::LoadXML(), Spreadsheet::PropertySheet::pasteCells(), App::Document::readObjects(), Part::Geometry::Restore(), Part::GeomBSplineCurve::Restore(), Path::Tooltable::Restore(), Robot::Trajectory::Restore(), Robot::Waypoint::Restore(), TechDraw::CosmeticVertex::Restore(), TechDraw::CosmeticEdge::Restore(), TechDraw::CenterLine::Restore(), TechDraw::GeomFormat::Restore(), TechDraw::Vertex::Restore(), Sketcher::Constraint::Restore(), Sketcher::SketchGeometryExtension::Restore(), TechDraw::BaseGeom::Restore(), TechDraw::AOC::Restore(), TechDraw::Generic::Restore(), App::PropertyContainer::Restore(), App::PropertyInteger::Restore(), App::PropertyEnumeration::Restore(), App::PropertyIntegerSet::Restore(), App::PropertyMap::Restore(), App::PropertyString::Restore(), Gui::DocumentItem::ExpandInfo::restore(), Part::Box::Restore(), Part::GeometryDefaultExtension< T >::Restore(), Part::PropertyGeometryList::Restore(), PartDesign::Fillet::Restore(), PartDesign::ProfileBased::Restore(), PartDesign::Transformed::Restore(), Path::PropertyPath::Restore(), Spreadsheet::PropertyColumnWidths::Restore(), Spreadsheet::PropertyRowHeights::Restore(), TechDraw::PropertyCenterLineList::Restore(), TechDraw::PropertyCosmeticEdgeList::Restore(), TechDraw::PropertyCosmeticVertexList::Restore(), TechDraw::PropertyGeomFormatList::Restore(), App::Document::Restore(), App::PropertyExpressionEngine::Restore(), App::PropertyLinkList::Restore(), App::PropertyLinkSub::Restore(), App::PropertyLinkSubList::Restore(), App::PropertyXLink::Restore(), App::PropertyXLinkSubList::Restore(), App::PropertyIntegerList::Restore(), App::PropertyStringList::Restore(), Part::Primitive::Restore(), PartDesign::Chamfer::Restore(), Sketcher::PropertyConstraintList::Restore(), Spreadsheet::PropertySheet::Restore(), Gui::Document::RestoreDocFile(), and App::ExtensionContainer::restoreExtensions().
getAttributeAsUnsigned()
unsigned long Base::XMLReader::getAttributeAsUnsigned (const char * AttrName) const
Referenced by App::Document::importObjects(), App::PropertyContainer::Restore(), App::PropertyColor::Restore(), App::PropertyMaterial::Restore(), Part::Box::Restore(), App::Document::Restore(), and App::PropertyXLinkContainer::Restore().
getAttributeCount()
unsigned int Base::XMLReader::getAttributeCount (void) const
get the number of attributes of the current element
getFilenames()
const std::vector< std::string > & Base::XMLReader::getFilenames () const
get all registered file names
Referenced by Gui::Document::importObjects().
getName()
const char * Base::XMLReader::getName (const char * name) const virtual
Reimplemented in Gui::XMLMergeReader, and App::XMLMergeReader.
Referenced by App::PropertyLinkBase::importSubName(), App::Document::readObjects(), App::PropertyString::Restore(), App::PropertyLink::Restore(), App::PropertyLinkList::Restore(), App::PropertyLinkSub::Restore(), App::PropertyLinkSubList::Restore(), and App::PropertyXLink::Restore().
hasAttribute()
bool Base::XMLReader::hasAttribute (const char * AttrName) const
check if the read element has a special attribute
Referenced by App::Document::importObjects(), Gui::Document::importObjects(), App::Document::readObjects(), Fem::FemMesh::Restore(), Part::GeomCircle::Restore(), Part::GeomArcOfCircle::Restore(), Part::GeomEllipse::Restore(), Path::Tool::Restore(), Robot::Robot6Axis::Restore(), Gui::DocumentItem::Restore(), Sketcher::Constraint::Restore(), Sketcher::SketchGeometryExtension::Restore(), App::PropertyContainer::Restore(), App::PropertyFileIncluded::Restore(), App::PropertyPythonObject::Restore(), App::PropertyEnumeration::Restore(), App::PropertyString::Restore(), Gui::DocumentItem::ExpandInfo::restore(), Fem::PropertyPostDataObject::Restore(), Part::Box::Restore(), Path::PropertyPath::Restore(), Spreadsheet::PropertyColumnWidths::Restore(), Spreadsheet::PropertyRowHeights::Restore(), App::Document::Restore(), App::PropertyExpressionEngine::Restore(), App::PropertyPlacement::Restore(), App::PropertyLinkSub::Restore(), App::PropertyLinkSubList::Restore(), App::PropertyXLink::Restore(), App::PropertyXLinkSubList::Restore(), App::PropertyXLinkContainer::Restore(), App::PropertyColorList::Restore(), App::PropertyMaterialList::Restore(), Spreadsheet::PropertySheet::Restore(), Spreadsheet::Cell::restore(), App::DynamicProperty::restore(), Gui::Document::RestoreDocFile(), and App::ExtensionContainer::restoreExtensions().
ignorableWhitespace()
void Base::XMLReader::ignorableWhitespace (const XMLCh *const chars, const XMLSize_t length) protected virtual
isRegistered()
bool Base::XMLReader::isRegistered (Base::Persistence * Object) const
isValid()
bool Base::XMLReader::isValid (void) const
Referenced by Cloud::Module::cloudRestore(), App::Document::restore(), and Base::Persistence::restoreFromStream().
isVerbose()
bool Base::XMLReader::isVerbose () const
Referenced by App::PropertyLink::Restore(), App::PropertyLinkList::Restore(), App::PropertyLinkSub::Restore(), App::PropertyLinkSubList::Restore(), and App::PropertyXLink::Restore().
level()
int Base::XMLReader::level () const
get the current element level
Referenced by Gui::DocumentItem::ExpandInfo::restore().
localName()
const char * Base::XMLReader::localName (void) const
get the local name of the current Element
Referenced by Part::Geometry::Restore(), Part::PropertyGeometryList::Restore(), TechDraw::PropertyCenterLineList::Restore(), TechDraw::PropertyCosmeticEdgeList::Restore(), TechDraw::PropertyCosmeticVertexList::Restore(), and TechDraw::PropertyGeomFormatList::Restore().
read()
bool Base::XMLReader::read (void) protected
read the next element
Referenced by gzip_utf8.GzipFile::readline(), and gzip_utf8.GzipFile::seek().
readBinFile()
void Base::XMLReader::readBinFile (const char * filename)
read binary file
References Base::base64_decode().
Referenced by App::PropertyFileIncluded::Restore().
readCharacters()
void Base::XMLReader::readCharacters (void)
read until characters are found
readElement()
void Base::XMLReader::readElement (const char * ElementName = 0)
read until a start element is found (<name>) or start-end element (<name/>) (with special name if given)
Referenced by App::Document::importObjects(), Gui::Document::importObjects(), MeshCore::MeshInput::LoadXML(), Spreadsheet::PropertySheet::pasteCells(), App::Document::readObjects(), Fem::FemMesh::Restore(), Part::Geometry::Restore(), Part::GeomPoint::Restore(), Part::GeomBSplineCurve::Restore(), Part::GeomCircle::Restore(), Part::GeomArcOfCircle::Restore(), Part::GeomEllipse::Restore(), Part::GeomArcOfEllipse::Restore(), Part::GeomHyperbola::Restore(), Part::GeomArcOfHyperbola::Restore(), Part::GeomParabola::Restore(), Part::GeomArcOfParabola::Restore(), Part::GeomLine::Restore(), Part::GeomLineSegment::Restore(), Part::Geom2dPoint::Restore(), Part::Geom2dCircle::Restore(), Part::Geom2dArcOfCircle::Restore(), Part::Geom2dEllipse::Restore(), Part::Geom2dArcOfEllipse::Restore(), Part::Geom2dHyperbola::Restore(), Part::Geom2dArcOfHyperbola::Restore(), Part::Geom2dParabola::Restore(), Part::Geom2dArcOfParabola::Restore(), Part::Geom2dLineSegment::Restore(), Path::Command::Restore(), Path::Toolpath::Restore(), Path::Tool::Restore(), Path::Tooltable::Restore(), Robot::Robot6Axis::Restore(), Robot::Trajectory::Restore(), Robot::Waypoint::Restore(), TechDraw::CosmeticVertex::Restore(), TechDraw::CosmeticEdge::Restore(), TechDraw::CenterLine::Restore(), TechDraw::GeomFormat::Restore(), TechDraw::Vertex::Restore(), Gui::DocumentItem::Restore(), Sketcher::Constraint::Restore(), TechDraw::BaseGeom::Restore(), TechDraw::Circle::Restore(), TechDraw::AOC::Restore(), TechDraw::Generic::Restore(), App::PropertyContainer::Restore(), App::PropertyFileIncluded::Restore(), App::PropertyMatrix::Restore(), App::PropertyPythonObject::Restore(), App::PropertyInteger::Restore(), App::PropertyPath::Restore(), App::PropertyEnumeration::Restore(), App::PropertyIntegerSet::Restore(), App::PropertyMap::Restore(), App::PropertyFloat::Restore(), App::PropertyString::Restore(), App::PropertyUUID::Restore(), App::PropertyBool::Restore(), App::PropertyColor::Restore(), App::PropertyMaterial::Restore(), Gui::DocumentItem::ExpandInfo::restore(), Fem::PropertyPostDataObject::Restore(), Inspection::PropertyDistanceList::Restore(), Mesh::PropertyNormalList::Restore(), Mesh::PropertyCurvatureList::Restore(), Mesh::PropertyMeshKernel::Restore(), Part::Box::Restore(), Part::PropertyGeometryList::Restore(), Part::PropertyPartShape::Restore(), Part::PropertyFilletEdges::Restore(), PartDesign::Fillet::Restore(), PartDesign::ProfileBased::Restore(), PartDesign::Transformed::Restore(), Path::PropertyPath::Restore(), Points::PointKernel::Restore(), Points::PropertyGreyValueList::Restore(), Points::PropertyNormalList::Restore(), Points::PropertyCurvatureList::Restore(), Points::PropertyPointKernel::Restore(), Spreadsheet::PropertyColumnWidths::Restore(), Spreadsheet::PropertyRowHeights::Restore(), TechDraw::PropertyCenterLineList::Restore(), TechDraw::PropertyCosmeticEdgeList::Restore(), TechDraw::PropertyCosmeticVertexList::Restore(), TechDraw::PropertyGeomFormatList::Restore(), App::Document::Restore(), App::PropertyExpressionEngine::Restore(), App::PropertyVector::Restore(), App::PropertyVectorList::Restore(), App::PropertyPlacement::Restore(), App::PropertyPlacementList::Restore(), App::PropertyLink::Restore(), App::PropertyLinkList::Restore(), App::PropertyLinkSub::Restore(), App::PropertyLinkSubList::Restore(), App::PropertyXLink::Restore(), App::PropertyXLinkSubList::Restore(), App::PropertyXLinkContainer::Restore(), App::PropertyIntegerList::Restore(), App::PropertyFloatList::Restore(), App::PropertyStringList::Restore(), App::PropertyBoolList::Restore(), App::PropertyColorList::Restore(), App::PropertyMaterialList::Restore(), App::PropertyPersistentObject::Restore(), Part::Primitive::Restore(), PartDesign::Chamfer::Restore(), Sketcher::PropertyConstraintList::Restore(), Spreadsheet::PropertySheet::Restore(), Gui::Document::RestoreDocFile(), App::ExtensionContainer::restoreExtensions(), and Base::Persistence::restoreFromStream().
readEndElement()
void Base::XMLReader::readEndElement (const char * ElementName = 0, int level = -1)
read until an end element is found
Parameters
ElementName optional end element name to look for. If given, then the parser will read until this name is found.
level optional level to look for. If given, then the parser will read until this level. Note that the parse only increase the level when finding a start element, not start-end element, and decrease the level after finding an end element. So, if you obtain the parser level after calling readElement(), you should specify a level minus one when calling this function. This level parameter is only useful if you know the child element may have the same name as its parent, otherwise, using ElementName is enough.
Referenced by App::Document::importObjects(), Gui::Document::importObjects(), MeshCore::MeshInput::LoadXML(), App::Document::readObjects(), Part::Geometry::Restore(), Part::GeomBSplineCurve::Restore(), TechDraw::CenterLine::Restore(), TechDraw::Generic::Restore(), App::PropertyContainer::Restore(), App::PropertyFileIncluded::Restore(), App::PropertyEnumeration::Restore(), App::PropertyIntegerSet::Restore(), App::PropertyMap::Restore(), Gui::DocumentItem::ExpandInfo::restore(), Part::Box::Restore(), Part::PropertyGeometryList::Restore(), PartDesign::Fillet::Restore(), PartDesign::ProfileBased::Restore(), PartDesign::Transformed::Restore(), Spreadsheet::PropertyColumnWidths::Restore(), Spreadsheet::PropertyRowHeights::Restore(), TechDraw::PropertyCenterLineList::Restore(), TechDraw::PropertyCosmeticEdgeList::Restore(), TechDraw::PropertyCosmeticVertexList::Restore(), TechDraw::PropertyGeomFormatList::Restore(), App::Document::Restore(), App::PropertyExpressionEngine::Restore(), App::PropertyLinkList::Restore(), App::PropertyLinkSub::Restore(), App::PropertyLinkSubList::Restore(), App::PropertyXLink::Restore(), App::PropertyXLinkSubList::Restore(), App::PropertyXLinkContainer::Restore(), App::PropertyIntegerList::Restore(), App::PropertyStringList::Restore(), App::PropertyPersistentObject::Restore(), Part::Primitive::Restore(), PartDesign::Chamfer::Restore(), Sketcher::PropertyConstraintList::Restore(), Spreadsheet::PropertySheet::Restore(), Gui::Document::RestoreDocFile(), and App::ExtensionContainer::restoreExtensions().
readFiles()
void Base::XMLReader::readFiles (zipios::ZipInputStream & zipstream) const
process the requested file writes
References Base::Console(), Base::ConsoleSingleton::Error(), Base::Reader::getLocalReader(), Base::Type::getName(), zipios::ZipInputStream::getNextEntry(), and Base::SequencerLauncher::next().
Referenced by App::Document::restore(), and Base::Persistence::restoreFromStream().
resetDocument()
void Base::XMLReader::resetDocument () protected virtual
resetErrors()
void Base::XMLReader::resetErrors () protected
setPartialRestore()
void Base::XMLReader::setPartialRestore (bool on)
sets simultaneously the global and local PartialRestore bits
Referenced by Part::GeomLineSegment::Restore(), and App::PropertyContainer::Restore().
setStatus()
void Base::XMLReader::setStatus (ReaderStatus pos, bool on)
set the status bits
setVerbose()
void Base::XMLReader::setVerbose (bool on)
Referenced by App::MergeDocuments::importObjects().
startCDATA()
void Base::XMLReader::startCDATA () protected virtual
startDocument()
void Base::XMLReader::startDocument () protected virtual
startElement()
void Base::XMLReader::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE_QUALIFIER Attributes & attrs) protected virtual
References StrX::c_str(), and StrXUTF8::c_str().
testStatus()
bool Base::XMLReader::testStatus (ReaderStatus pos) const
return the status bits
Referenced by App::Document::readObjects(), App::PropertyContainer::Restore(), Part::PropertyGeometryList::Restore(), TechDraw::PropertyCenterLineList::Restore(), TechDraw::PropertyCosmeticEdgeList::Restore(), TechDraw::PropertyCosmeticVertexList::Restore(), TechDraw::PropertyGeomFormatList::Restore(), and App::Document::restore().
warning()
void Base::XMLReader::warning (const XERCES_CPP_NAMESPACE_QUALIFIER SAXParseException & exc) protected
Member Data Documentation
AttrMap
std::map<std::string,std::string> Base::XMLReader::AttrMap protected
CharacterCount
unsigned int Base::XMLReader::CharacterCount protected
Characters
std::string Base::XMLReader::Characters protected
DocumentSchema
int Base::XMLReader::DocumentSchema
Schema Version of the document.
Referenced by App::Document::importObjects(), Points::PointKernel::Restore(), Points::PropertyPointKernel::Restore(), App::Document::Restore(), and Gui::Document::RestoreDocFile().
FileList
std::vector<FileEntry> Base::XMLReader::FileList
FileNames
std::vector<std::string> Base::XMLReader::FileNames protected
FileVersion
int Base::XMLReader::FileVersion
Version of the file format.
Referenced by App::Document::importObjects(), App::Document::Restore(), and Gui::Document::RestoreDocFile().
Level
int Base::XMLReader::Level protected
LocalName
std::string Base::XMLReader::LocalName protected
parser
XERCES_CPP_NAMESPACE_QUALIFIER SAX2XMLReader* Base::XMLReader::parser protected
Referenced by XMLReader().
ProgramVersion
std::string Base::XMLReader::ProgramVersion
Version of FreeCAD that wrote this document.
Referenced by App::Document::importObjects(), App::Document::Restore(), and App::Document::restore().
ReadType
enum { ... } Base::XMLReader::ReadType
StatusBits
std::bitset<32> Base::XMLReader::StatusBits protected
token
XERCES_CPP_NAMESPACE_QUALIFIER XMLPScanToken Base::XMLReader::token protected
Referenced by XMLReader().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Base/Reader.h
Sources/FreeCAD/src/Base/Reader.cpp