FreeCAD: Mod.PartDesign.fcgear.involute Namespace Reference
Mod.PartDesign.fcgear.involute Namespace Reference
Functions
def bezCoeff (i, p, polyCoeffs)
def BezCoeffs (module, numTeeth, pressureAngle, order, fstart, fstop)
def binom (n, k)
def chebyExpnCoeffs (j, func)
def chebyPolyCoeffs (p, func)
def CreateExternalGear (w, m, Z, phi, split=True)
def CreateInternalGear (w, m, Z, phi, split=True)
def genInvolutePolar (Rb, R)
def rotate (pt, rads)
def toCartesian (radius, angle)
Variables
xrange = range
Function Documentation
bezCoeff()
def Mod.PartDesign.fcgear.involute.bezCoeff (i, p, polyCoeffs)
generate the polynomial coeffs in one go
References Mod.PartDesign.fcgear.involute.binom().
Referenced by Mod.PartDesign.fcgear.involute.BezCoeffs().
BezCoeffs()
def Mod.PartDesign.fcgear.involute.BezCoeffs (module, numTeeth, pressureAngle, order, fstart, fstop)
References Mod.PartDesign.fcgear.involute.bezCoeff(), Mod.PartDesign.fcgear.involute.chebyPolyCoeffs(), and Mod.PartDesign.fcgear.involute.xrange.
Referenced by Mod.PartDesign.fcgear.involute.CreateExternalGear(), and Mod.PartDesign.fcgear.involute.CreateInternalGear().
binom()
def Mod.PartDesign.fcgear.involute.binom (n, k)
References Mod.PartDesign.fcgear.involute.xrange.
Referenced by Mod.PartDesign.fcgear.involute.bezCoeff().
chebyExpnCoeffs()
def Mod.PartDesign.fcgear.involute.chebyExpnCoeffs (j, func)
References Mod.PartDesign.fcgear.involute.xrange.
Referenced by Mod.PartDesign.fcgear.involute.chebyPolyCoeffs().
chebyPolyCoeffs()
def Mod.PartDesign.fcgear.involute.chebyPolyCoeffs (p, func)
References Mod.PartDesign.fcgear.involute.chebyExpnCoeffs(), and Mod.PartDesign.fcgear.involute.xrange.
Referenced by Mod.PartDesign.fcgear.involute.BezCoeffs().
CreateExternalGear()
def Mod.PartDesign.fcgear.involute.CreateExternalGear (w, m, Z, phi, split = True)
Create an external gear
w is wirebuilder object (in which the gear will be constructed)
if split is True, each profile of a teeth will consist in 2 Bezier
curves of degree 3, otherwise it will be made of one Bezier curve
of degree 4
References Mod.PartDesign.fcgear.involute.BezCoeffs(), Mod.PartDesign.fcgear.involute.genInvolutePolar(), and Mod.PartDesign.fcgear.involute.toCartesian().
CreateInternalGear()
def Mod.PartDesign.fcgear.involute.CreateInternalGear (w, m, Z, phi, split = True)
Create an internal gear
w is wirebuilder object (in which the gear will be constructed)
if split is True, each profile of a teeth will consist in 2 Bezier
curves of degree 3, otherwise it will be made of one Bezier curve
of degree 4
References Mod.PartDesign.fcgear.involute.BezCoeffs(), Mod.PartDesign.fcgear.involute.genInvolutePolar(), and Mod.PartDesign.fcgear.involute.toCartesian().
genInvolutePolar()
def Mod.PartDesign.fcgear.involute.genInvolutePolar (Rb, R)
returns the involute angle as function of radius R.
Rb = base circle radius
Referenced by Mod.PartDesign.fcgear.involute.CreateExternalGear(), and Mod.PartDesign.fcgear.involute.CreateInternalGear().
rotate()
def Mod.PartDesign.fcgear.involute.rotate (pt, rads)
toCartesian()
def Mod.PartDesign.fcgear.involute.toCartesian (radius, angle)
Referenced by Mod.PartDesign.fcgear.involute.CreateExternalGear(), and Mod.PartDesign.fcgear.involute.CreateInternalGear().
Variable Documentation
xrange
Mod.PartDesign.fcgear.involute.xrange = range
Referenced by Mod.PartDesign.fcgear.involute.BezCoeffs(), Mod.PartDesign.fcgear.involute.binom(), Mod.PartDesign.fcgear.involute.chebyExpnCoeffs(), and Mod.PartDesign.fcgear.involute.chebyPolyCoeffs().