FreeCAD: femexamples.equation_electrostatics_electricforce_elmer_nongui6 Namespace Reference
femexamples.equation_electrostatics_electricforce_elmer_nongui6 Namespace Reference
Functions
def get_explanation (header="")
def get_information ()
def setup (doc=None, solvertype="elmer")
Function Documentation
get_explanation()
def femexamples.equation_electrostatics_electricforce_elmer_nongui6.get_explanation (header = "")
Referenced by femexamples.equation_electrostatics_electricforce_elmer_nongui6.setup().
get_information()
def femexamples.equation_electrostatics_electricforce_elmer_nongui6.get_information ()
Referenced by femexamples.equation_electrostatics_electricforce_elmer_nongui6.setup().
setup()
def femexamples.equation_electrostatics_electricforce_elmer_nongui6.setup (doc = None, solvertype = "elmer")
References femexamples.equation_electrostatics_electricforce_elmer_nongui6.get_explanation(), femexamples.equation_electrostatics_electricforce_elmer_nongui6.get_information(), ObjectsFem.makeAnalysis(), ObjectsFem.makeConstraintElectrostaticPotential(), ObjectsFem.makeEquationElectricforce(), ObjectsFem.makeEquationElectrostatic(), ObjectsFem.makeMaterialFluid(), ObjectsFem.makeMeshGmsh(), ObjectsFem.makeMeshRegion(), and ObjectsFem.makeSolverElmer().