FreeCAD: MeshGui::DlgEvaluateSettings Class Reference
MeshGui::DlgEvaluateSettings Class Reference
#include <DlgEvaluateSettings.h>
Public Member Functions
DlgEvaluateSettings (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
bool isDegeneratedFacetsChecked () const
bool isFoldsChecked () const
bool isNonmanifoldPointsChecked () const
void setDegeneratedFacetsChecked (bool)
void setFoldsChecked (bool)
void setNonmanifoldPointsChecked (bool)
~DlgEvaluateSettings ()
Detailed Description
Author
Werner Mayer
Constructor & Destructor Documentation
DlgEvaluateSettings()
DlgEvaluateSettings::DlgEvaluateSettings (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
References MeshGui::Ui_DlgEvaluateSettings::setupUi().
~DlgEvaluateSettings()
DlgEvaluateSettings::~DlgEvaluateSettings ()
Member Function Documentation
isDegeneratedFacetsChecked()
bool DlgEvaluateSettings::isDegeneratedFacetsChecked () const
References MeshGui::Ui_DlgEvaluateSettings::checkDegenerated.
Referenced by MeshGui::DlgEvaluateMeshImp::on_buttonBox_clicked().
isFoldsChecked()
bool DlgEvaluateSettings::isFoldsChecked () const
References MeshGui::Ui_DlgEvaluateSettings::checkFolds.
Referenced by MeshGui::DlgEvaluateMeshImp::on_buttonBox_clicked().
isNonmanifoldPointsChecked()
bool DlgEvaluateSettings::isNonmanifoldPointsChecked () const
References MeshGui::Ui_DlgEvaluateSettings::checkNonmanifoldPoints.
Referenced by MeshGui::DlgEvaluateMeshImp::on_buttonBox_clicked().
setDegeneratedFacetsChecked()
void DlgEvaluateSettings::setDegeneratedFacetsChecked (bool on)
References MeshGui::Ui_DlgEvaluateSettings::checkDegenerated.
Referenced by MeshGui::DlgEvaluateMeshImp::on_buttonBox_clicked().
setFoldsChecked()
void DlgEvaluateSettings::setFoldsChecked (bool on)
References MeshGui::Ui_DlgEvaluateSettings::checkFolds.
Referenced by MeshGui::DlgEvaluateMeshImp::on_buttonBox_clicked().
setNonmanifoldPointsChecked()
void DlgEvaluateSettings::setNonmanifoldPointsChecked (bool on)
References MeshGui::Ui_DlgEvaluateSettings::checkNonmanifoldPoints.
Referenced by MeshGui::DlgEvaluateMeshImp::on_buttonBox_clicked().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/Gui/DlgEvaluateSettings.h
FreeCAD/src/Mod/Mesh/Gui/DlgEvaluateSettings.cpp