FreeCAD: SMESHDS_GroupOnGeom Class Reference
SMESHDS_GroupOnGeom Class Reference
#include <SMESHDS_GroupOnGeom.hxx>
Public Member Functions
virtual bool Contains (const int theID)
virtual bool Contains (const SMDS_MeshElement *elem)
virtual SMDS_ElemIteratorPtr GetElements () const
TopoDS_Shape GetShape () const
virtual VTK_MTIME_TYPE GetTic () const
Return a value allowing to find out if a group has changed or not.
void SetShape (const TopoDS_Shape &theShape)
SMESHDS_GroupOnGeom (const int theID, const SMESHDS_Mesh *theMesh, const SMDSAbs_ElementType theType, const TopoDS_Shape &theShape)
Public Member Functions inherited from SMESHDS_GroupBase
virtual int Extent () const
Quantity_Color GetColor () const
int GetColorGroup () const
int GetID () const
virtual int GetID (const int theIndex)
const SMESHDS_Mesh * GetMesh () const
const char * GetStoreName () const
SMDSAbs_ElementType GetType () const
virtual bool IsEmpty ()
void SetColor (const Quantity_Color &theColor)
void SetColorGroup (int theColorGroup)
void SetStoreName (const char *theName)
virtual void SetType (SMDSAbs_ElementType theType)
SMESHDS_GroupBase (const int theID, const SMESHDS_Mesh *theMesh, const SMDSAbs_ElementType theType)
virtual ~SMESHDS_GroupBase ()
Additional Inherited Members
Static Public Member Functions inherited from SMESHDS_GroupBase
static void SetDefaultColor (const Quantity_Color &theColor)
Protected Member Functions inherited from SMESHDS_GroupBase
const SMDS_MeshElement * findInMesh (const int theID) const
void resetIterator ()
Constructor & Destructor Documentation
SMESHDS_GroupOnGeom()
SMESHDS_GroupOnGeom::SMESHDS_GroupOnGeom (const int theID, const SMESHDS_Mesh * theMesh, const SMDSAbs_ElementType theType, const TopoDS_Shape & theShape)
References SetShape().
Member Function Documentation
Contains() [1/2]
bool SMESHDS_GroupOnGeom::Contains (const int theID) virtual
Reimplemented from SMESHDS_GroupBase.
References SMESHDS_SubMesh::Contains(), and SMESHDS_GroupBase::findInMesh().
Contains() [2/2]
bool SMESHDS_GroupOnGeom::Contains (const SMDS_MeshElement * elem) virtual
Reimplemented from SMESHDS_GroupBase.
References SMESHDS_SubMesh::Contains().
GetElements()
SMDS_ElemIteratorPtr SMESHDS_GroupOnGeom::GetElements () const virtual
Implements SMESHDS_GroupBase.
References SMESHDS_GroupBase::GetType().
GetShape()
TopoDS_Shape SMESHDS_GroupOnGeom::GetShape () const
GetTic()
VTK_MTIME_TYPE SMESHDS_GroupOnGeom::GetTic () const virtual
Return a value allowing to find out if a group has changed or not.
Implements SMESHDS_GroupBase.
References SMESHDS_GroupBase::GetMesh(), and SMDS_Mesh::GetMTime().
SetShape()
void SMESHDS_GroupOnGeom::SetShape (const TopoDS_Shape & theShape)
References SMESHDS_Mesh::AddCompoundSubmesh(), SMESHDS_GroupBase::GetMesh(), and SMESHDS_Mesh::MeshElements().
Referenced by SMESHDS_GroupOnGeom().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESHDS_GroupOnGeom.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESHDS/SMESHDS_GroupOnGeom.cpp