FreeCAD: Gui::RecentMacrosAction Class Reference
Gui::RecentMacrosAction Class Reference
The RecentMacrosAction class holds a menu listed with the recent macros that were executed, edited, or created.
#include <Action.h>
Public Member Functions
void activateFile (int)
void appendFile (const QString &)
Adds the new item to the recent files.
RecentMacrosAction (Command *pcCmd, QObject *parent=nullptr)
void resizeList (int)
virtual ~RecentMacrosAction ()
Public Member Functions inherited from Gui::ActionGroup
ActionGroup (Command *pcCmd, QObject *parent=nullptr)
Constructs an action called name with parent parent.
QList< QAction * > actions () const
QAction * addAction (const QString &)
QAction * addAction (QAction *)
void addTo (QWidget *w)
Adds this action to widget w.
int checkedAction () const
bool isExclusive () const
void setCheckedAction (int)
void setDisabled (bool)
void setDropDownMenu (bool b)
void setEnabled (bool)
Sets whether the action is enabled.
void setExclusive (bool)
void setIsMode (bool b)
void setVisible (bool)
virtual ~ActionGroup ()
Public Member Functions inherited from Gui::Action
QAction * action () const
Action (Command *pcCmd, QAction *action, QObject *parent)
Action takes ownership of the 'action' object.
Action (Command *pcCmd, QObject *parent=nullptr)
Constructs an action called name with parent parent.
virtual void addTo (QWidget *w)
Adds this action to widget w.
QIcon icon () const
bool isChecked () const
void setCheckable (bool)
void setChecked (bool, bool no_signal=false)
virtual void setEnabled (bool)
Sets whether the action is enabled.
void setIcon (const QIcon &)
void setMenuRole (QAction::MenuRole menuRole)
void setShortcut (const QString &)
void setStatusTip (const QString &)
void setText (const QString &)
void setToolTip (const QString &)
virtual void setVisible (bool)
void setWhatsThis (const QString &)
QKeySequence shortcut () const
QString statusTip () const
QString text () const
QString toolTip () const
QString whatsThis () const
virtual ~Action ()
Additional Inherited Members
Public Slots inherited from Gui::ActionGroup
void onActivated ()
Activates the command.
void onActivated (QAction *)
Activates the command.
void onHovered (QAction *)
void onToggled (bool)
Public Slots inherited from Gui::Action
virtual void onActivated ()
Activates the command.
virtual void onToggled (bool)
Sets whether the command is toggled.
Detailed Description
The RecentMacrosAction class holds a menu listed with the recent macros that were executed, edited, or created.
Constructor & Destructor Documentation
RecentMacrosAction()
RecentMacrosAction::RecentMacrosAction (Command * pcCmd, QObject * parent = nullptr)
~RecentMacrosAction()
RecentMacrosAction::~RecentMacrosAction () virtual
Member Function Documentation
activateFile()
void RecentMacrosAction::activateFile (int id)
References Gui::Application::activeDocument(), Gui::MainWindow::addWindow(), Gui::MainWindow::appendRecentMacro(), Gui::BitmapFactory(), Gui::MacroManager::File, Gui::EditorView::FileName, Gui::Document::getDocument(), Gui::getMainWindow(), Gui::Application::Instance, Gui::Application::macroManager(), Gui::EditorView::open(), App::Document::recompute(), Gui::MacroManager::run(), and Gui::EditorView::setDisplayName().
Referenced by StdCmdRecentMacros::activated().
appendFile()
void RecentMacrosAction::appendFile (const QString & filename)
Adds the new item to the recent files.
References App::Application::Config(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), App::Application::GetParameterSet(), and ParameterManager::SaveDocument().
Referenced by Gui::MainWindow::appendRecentMacro().
resizeList()
void RecentMacrosAction::resizeList (int size)
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/Action.h
FreeCAD/src/Gui/Action.cpp