FreeCAD: PartDesignGui::Ui_TaskMirroredParameters Class Reference
PartDesignGui::Ui_TaskMirroredParameters Class Reference
#include <ui_TaskMirroredParameters.h>
Public Member Functions
void retranslateUi (QWidget *PartDesignGui__TaskMirroredParameters)
void setupUi (QWidget *PartDesignGui__TaskMirroredParameters)
Public Attributes
QPushButton * buttonAddFeature
QPushButton * buttonOK
QPushButton * buttonRemoveFeature
QCheckBox * checkBoxUpdateView
QComboBox * comboPlane
QHBoxLayout * horizontalLayout
QHBoxLayout * horizontalLayout_2
QHBoxLayout * horizontalLayout_3
QLabel * labelPlane
QListWidget * listWidgetFeatures
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void PartDesignGui::Ui_TaskMirroredParameters::retranslateUi (QWidget * PartDesignGui__TaskMirroredParameters)
References buttonAddFeature, buttonOK, buttonRemoveFeature, checkBoxUpdateView, labelPlane, listWidgetFeatures, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void PartDesignGui::Ui_TaskMirroredParameters::setupUi (QWidget * PartDesignGui__TaskMirroredParameters)
References buttonAddFeature, buttonOK, buttonRemoveFeature, checkBoxUpdateView, comboPlane, draftgeoutils.intersections::connect(), horizontalLayout, horizontalLayout_2, horizontalLayout_3, labelPlane, listWidgetFeatures, retranslateUi(), and verticalLayout.
Member Data Documentation
buttonAddFeature
QPushButton* PartDesignGui::Ui_TaskMirroredParameters::buttonAddFeature
Referenced by retranslateUi(), and setupUi().
buttonOK
QPushButton* PartDesignGui::Ui_TaskMirroredParameters::buttonOK
Referenced by retranslateUi(), and setupUi().
buttonRemoveFeature
QPushButton* PartDesignGui::Ui_TaskMirroredParameters::buttonRemoveFeature
Referenced by retranslateUi(), and setupUi().
checkBoxUpdateView
QCheckBox* PartDesignGui::Ui_TaskMirroredParameters::checkBoxUpdateView
Referenced by retranslateUi(), and setupUi().
comboPlane
QComboBox* PartDesignGui::Ui_TaskMirroredParameters::comboPlane
Referenced by setupUi().
horizontalLayout
QHBoxLayout* PartDesignGui::Ui_TaskMirroredParameters::horizontalLayout
Referenced by setupUi().
horizontalLayout_2
QHBoxLayout* PartDesignGui::Ui_TaskMirroredParameters::horizontalLayout_2
Referenced by setupUi().
horizontalLayout_3
QHBoxLayout* PartDesignGui::Ui_TaskMirroredParameters::horizontalLayout_3
Referenced by setupUi().
labelPlane
QLabel* PartDesignGui::Ui_TaskMirroredParameters::labelPlane
Referenced by retranslateUi(), and setupUi().
listWidgetFeatures
QListWidget* PartDesignGui::Ui_TaskMirroredParameters::listWidgetFeatures
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* PartDesignGui::Ui_TaskMirroredParameters::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/PartDesign/Gui/ui_TaskMirroredParameters.h