FreeCAD: PathScripts.PathSetupSheet Namespace Reference
PathScripts.PathSetupSheet Namespace Reference
Classes
class SetupSheet
class Template
Functions
def Create (name='SetupSheet')
def OpNamePrefix (name)
def OpPropertyGroup (opName)
def OpPropertyName (opName, propName)
def RegisterOperation (name, objFactory, setupProperties)
def translate (context, text, disambig=None)
Function Documentation
Create()
def PathScripts.PathSetupSheet.Create (name = 'SetupSheet')
References PathScripts.PathSetupSheet.OpPropertyName().
OpNamePrefix()
def PathScripts.PathSetupSheet.OpNamePrefix (name)
Referenced by PathScripts.PathSetupSheet.OpPropertyName().
OpPropertyGroup()
def PathScripts.PathSetupSheet.OpPropertyGroup (opName)
Referenced by PathScripts.PathSetupSheet.SetupSheet.setFromTemplate().
OpPropertyName()
def PathScripts.PathSetupSheet.OpPropertyName (opName, propName)
References PathScripts.PathSetupSheet.OpNamePrefix().
Referenced by PathScripts.PathSetupSheet.Create(), PathScripts.PathSetupSheet.SetupSheet.setFromTemplate(), PathScripts.PathSetupSheet.SetupSheet.setOperationProperties(), and PathScripts.PathSetupSheet.SetupSheet.templateAttributes().
RegisterOperation()
def PathScripts.PathSetupSheet.RegisterOperation (name, objFactory, setupProperties)
translate()
def PathScripts.PathSetupSheet.translate (context, text, disambig = None)