FreeCAD: MeshCore::MeshCleanup Class Reference
MeshCore::MeshCleanup Class Reference
#include <MeshIO.h>
Public Member Functions
MeshCleanup (MeshPointArray &p, MeshFacetArray &f)
Construction.
void RemoveInvalids ()
Remove unreferenced and invalid facets.
void SetMaterial (Material *mat)
Set the material array. In case the material array sets the colors per vertex and RemoveInvalids() removes points from the array the material array will be adjusted.
~MeshCleanup ()
Detailed Description
The MeshCleanup class is a helper class to remove points from the point array that are not referenced by any facet. It also removes facet with point indices that are out of range.
Constructor & Destructor Documentation
MeshCleanup()
MeshCleanup::MeshCleanup (MeshPointArray & p, MeshFacetArray & f)
Construction.
Parameters
p – the point array
f – the facet array
~MeshCleanup()
MeshCleanup::~MeshCleanup ()
Member Function Documentation
RemoveInvalids()
void MeshCleanup::RemoveInvalids ()
Remove unreferenced and invalid facets.
References MeshCore::MeshPoint::INVALID, MeshCore::MeshPointArray::ResetInvalid(), and MeshCore::MeshPointArray::SetFlag().
Referenced by MeshCore::MeshKernel::Cleanup(), MeshCore::MeshInput::LoadMeshNode(), MeshCore::MeshInput::LoadOBJ(), MeshCore::MeshInput::LoadOFF(), MeshCore::MeshInput::LoadPLY(), and MeshCore::MeshInput::LoadSMF().
SetMaterial()
void MeshCleanup::SetMaterial (Material * mat)
Set the material array. In case the material array sets the colors per vertex and RemoveInvalids() removes points from the array the material array will be adjusted.
Referenced by MeshCore::MeshInput::LoadOBJ(), MeshCore::MeshInput::LoadOFF(), and MeshCore::MeshInput::LoadPLY().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/MeshIO.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/MeshIO.cpp