FreeCAD: PathScripts.PathOpTools Namespace Reference
PathScripts.PathOpTools Namespace Reference
Functions
def debugEdge (label, e)
def debugWire (label, w)
def isWireClockwise (w)
def makeWires (inEdges)
def offsetWire (wire, base, offset, forward, Side=None)
def orientWire (w, forward=True)
Variables
Part = LazyLoader("Part", globals(), "Part")
bool PrintWireDebug = False
translate = FreeCAD.Qt.translate
Function Documentation
debugEdge()
def PathScripts.PathOpTools.debugEdge (label, e)
debugEdge(label, e) ... prints a python statement to create e
Currently lines and arcs are supported.
Referenced by PathScripts.PathOpTools.debugWire().
debugWire()
def PathScripts.PathOpTools.debugWire (label, w)
debugWire(label, w) ... prints python statements for all edges of w to be added to the object tree in a group.
References PathScripts.PathOpTools.debugEdge(), and PathScripts.PathOpTools.isWireClockwise().
Referenced by PathScripts.PathOpTools.offsetWire().
isWireClockwise()
def PathScripts.PathOpTools.isWireClockwise (w)
isWireClockwise(w) ... returns True if the wire winds clockwise.
Referenced by PathScripts.PathOpTools.debugWire().
makeWires()
def PathScripts.PathOpTools.makeWires (inEdges)
makeWires ... function to make non-forking wires from a collection of edges
offsetWire()
def PathScripts.PathOpTools.offsetWire (wire, base, offset, forward, Side = None)
offsetWire(wire, base, offset, forward) ... offsets the wire away from base and orients the wire accordingly.
The function tries to avoid most of the pitfalls of Part.makeOffset2D which is possible because all offsetting
happens in the XY plane.
References PathScripts.PathOpTools.debugWire(), and PathScripts.PathOpTools.orientWire().
orientWire()
def PathScripts.PathOpTools.orientWire (w, forward = True)
orientWire(w, forward=True) ... orients given wire in a specific direction.
If forward = True (the default) the wire is oriented clockwise, looking down the negative Z axis.
If forward = False the wire is oriented counter clockwise.
If forward = None the orientation is determined by the order in which the edges appear in the wire.
Referenced by PathScripts.PathOpTools.offsetWire().
Variable Documentation
Part
PathScripts.PathOpTools.Part = LazyLoader("Part", globals(), "Part")
PrintWireDebug
bool PathScripts.PathOpTools.PrintWireDebug = False
translate
PathScripts.PathOpTools.translate = FreeCAD.Qt.translate