FreeCAD: Points::PcdWriter Class Reference
Points::PcdWriter Class Reference
#include <PointsAlgos.h>
Public Member Functions
PcdWriter (const PointKernel &)
void write (const std::string &filename)
~PcdWriter ()
Public Member Functions inherited from Points::Writer
void setColors (const std::vector< App::Color > &)
void setHeight (int)
void setIntensities (const std::vector< float > &)
void setNormals (const std::vector< Base::Vector3f > &)
void setPlacement (const Base::Placement &)
void setWidth (int)
Writer (const PointKernel &)
virtual ~Writer ()
Additional Inherited Members
Protected Attributes inherited from Points::Writer
std::vector< App::Color > colors
int height
std::vector< float > intensity
std::vector< Base::Vector3f > normals
Base::Placement placement
const PointKernel & points
int width
Constructor & Destructor Documentation
PcdWriter()
PcdWriter::PcdWriter (const PointKernel & p)
~PcdWriter()
PcdWriter::~PcdWriter ()
Member Function Documentation
write()
void PcdWriter::write (const std::string & filename) virtual
Implements Points::Writer.
References Points::Writer::colors, Base::Placement::getPosition(), Base::Placement::getRotation(), Points::Writer::intensity, Base::Placement::isIdentity(), Base::Rotation::isIdentity(), Base::Placement::multVec(), Base::Rotation::multVec(), Points::Writer::normals, Points::Writer::placement, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Points/App/PointsAlgos.h
Sources/FreeCAD/src/Mod/Points/App/PointsAlgos.cpp