FreeCAD: TechDraw::CosmeticExtension Class Reference
TechDraw::CosmeticExtension Class Reference
#include <CosmeticExtension.h>
Public Member Functions
virtual std::string addCenterLine (Base::Vector3d start, Base::Vector3d end)
virtual std::string addCenterLine (TechDraw::BaseGeom *bg)
virtual std::string addCenterLine (TechDraw::CenterLine *cl)
virtual std::string addCosmeticEdge (Base::Vector3d start, Base::Vector3d end)
virtual std::string addCosmeticEdge (TechDraw::BaseGeom *bg)
virtual std::string addCosmeticVertex (Base::Vector3d pos)
virtual std::string addGeomFormat (TechDraw::GeomFormat *gf)
CosmeticExtension ()
virtual CenterLine * getCenterLine (std::string tag) const
virtual CenterLine * getCenterLineBySelection (int i) const
virtual CenterLine * getCenterLineBySelection (std::string name) const
virtual CosmeticEdge * getCosmeticEdge (std::string id) const
virtual CosmeticEdge * getCosmeticEdgeBySelection (int i) const
virtual CosmeticEdge * getCosmeticEdgeBySelection (std::string name) const
virtual CosmeticVertex * getCosmeticVertex (std::string id) const
virtual CosmeticVertex * getCosmeticVertexBySelection (int i) const
virtual CosmeticVertex * getCosmeticVertexBySelection (std::string name) const
PyObject * getExtensionPyObject (void)
virtual GeomFormat * getGeomFormat (std::string id) const
virtual GeomFormat * getGeomFormatBySelection (int i) const
virtual GeomFormat * getGeomFormatBySelection (std::string name) const
virtual void removeCenterLine (std::string tag)
virtual void removeCenterLine (std::vector< std::string > delTags)
virtual void removeCosmeticEdge (std::string tag)
virtual void removeCosmeticEdge (std::vector< std::string > delTags)
virtual void removeCosmeticVertex (std::string tag)
virtual void removeCosmeticVertex (std::vector< std::string > delTags)
virtual void removeGeomFormat (std::string tag)
virtual bool replaceCenterLine (CenterLine *newLine)
virtual bool replaceCosmeticEdge (CosmeticEdge *newEdge)
virtual bool replaceCosmeticVertex (CosmeticVertex *newVertex)
virtual bool replaceGeomFormat (TechDraw::GeomFormat *gf)
virtual ~CosmeticExtension ()
Public Member Functions inherited from App::DocumentObjectExtension
DocumentObjectExtension ()
virtual App::DocumentObjectExecReturn * extensionExecute (void)
virtual bool extensionGetLinkedObject (DocumentObject *&ret, bool recursive, Base::Matrix4D *mat, bool transform, int depth) const
Get the linked object.
virtual bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const
Get the sub object by name.
virtual bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const
Get name references of all sub objects.
virtual bool extensionHasChildElement () const
virtual int extensionIsElementVisible (const char *)
virtual short extensionMustExecute (void)
virtual int extensionSetElementVisible (const char *, bool)
App::DocumentObject * getExtendedObject ()
const App::DocumentObject * getExtendedObject () const
virtual const char * getViewProviderExtensionName (void) const
returns the type name of the ViewProviderExtension which is automatically attached to the viewprovider object when it is initiated
virtual void onExtendedDocumentRestored ()
get called after a document has been fully restored
virtual void onExtendedSettingDocument ()
get called after setting the document
virtual void onExtendedSetupObject ()
get called after a brand new object was created
virtual void onExtendedUnsetupObject ()
get called when object is going to be removed from the document
virtual ~DocumentObjectExtension ()
Public Member Functions inherited from App::Extension
Extension ()
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
virtual void initExtension (App::ExtensionContainer *obj)
bool isPythonExtension ()
std::string name () const
virtual ~Extension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Public Attributes
TechDraw::PropertyCenterLineList CenterLines
TechDraw::PropertyCosmeticEdgeList CosmeticEdges
TechDraw::PropertyCosmeticVertexList CosmeticVertexes
TechDraw::PropertyGeomFormatList GeomFormats
Additional Inherited Members
Protected Member Functions inherited from App::Extension
virtual void extensionOnChanged (const Property *p)
void initExtensionType (Base::Type type)
Static Protected Member Functions inherited from App::Extension
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=0)
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::Object ExtensionPythonObject
Constructor & Destructor Documentation
CosmeticExtension()
CosmeticExtension::CosmeticExtension ()
References App::Prop_Output.
~CosmeticExtension()
CosmeticExtension::~CosmeticExtension () virtual
Member Function Documentation
addCenterLine() [1/3]
std::string CosmeticExtension::addCenterLine (Base::Vector3d start, Base::Vector3d end) virtual
References TechDraw::CenterLine::getTagAsString().
Referenced by TechDrawGui::TaskCenterLine::createCenterLine(), and TechDraw::DrawViewPartPy::makeCenterLine().
addCenterLine() [2/3]
std::string CosmeticExtension::addCenterLine (TechDraw::BaseGeom * bg) virtual
References TechDraw::CenterLine::getTagAsString().
addCenterLine() [3/3]
std::string CosmeticExtension::addCenterLine (TechDraw::CenterLine * cl) virtual
References TechDraw::CenterLine::getTagAsString().
addCosmeticEdge() [1/2]
std::string CosmeticExtension::addCosmeticEdge (Base::Vector3d start, Base::Vector3d end) virtual
References TechDraw::CosmeticEdge::getTagAsString().
Referenced by TechDrawGui::TaskCosmeticLine::createCosmeticLine(), TechDraw::DrawViewPartPy::makeCosmeticCircle(), TechDraw::DrawViewPartPy::makeCosmeticCircleArc(), TechDraw::DrawViewPartPy::makeCosmeticLine(), and TechDraw::DrawViewPartPy::makeCosmeticLine3D().
addCosmeticEdge() [2/2]
std::string CosmeticExtension::addCosmeticEdge (TechDraw::BaseGeom * bg) virtual
References TechDraw::CosmeticEdge::getTagAsString().
addCosmeticVertex()
std::string CosmeticExtension::addCosmeticVertex (Base::Vector3d pos) virtual
References TechDraw::CosmeticVertex::getTagAsString(), and TechDraw::DrawUtil::invertY().
Referenced by TechDrawGui::TaskCosVertex::addCosVertex(), TechDraw::DrawViewPartPy::makeCosmeticVertex(), TechDraw::DrawViewPartPy::makeCosmeticVertex3d(), and TechDraw::DrawDimHelper::makeDistDim().
addGeomFormat()
std::string CosmeticExtension::addGeomFormat (TechDraw::GeomFormat * gf) virtual
References TechDraw::GeomFormat::getTagAsString().
Referenced by TechDrawGui::TaskLineDecor::applyDecorations(), and TechDraw::DrawViewPartPy::formatGeometricEdge().
getCenterLine()
TechDraw::CenterLine * CosmeticExtension::getCenterLine (std::string tag) const virtual
References TechDraw::CenterLine::getTagAsString().
Referenced by TechDraw::DrawViewPart::add1CLToGE(), TechDraw::DrawViewPartPy::getCenterLine(), and TechDrawGui::TaskCenterLine::TaskCenterLine().
getCenterLineBySelection() [1/2]
TechDraw::CenterLine * CosmeticExtension::getCenterLineBySelection (int i) const virtual
getCenterLineBySelection() [2/2]
TechDraw::CenterLine * CosmeticExtension::getCenterLineBySelection (std::string name) const virtual
References TechDraw::DrawViewPart::getGeomByIndex(), and TechDraw::DrawUtil::getIndexFromName().
Referenced by TechDrawGui::TaskLineDecor::applyDecorations(), TechDraw::DrawViewPartPy::getCenterLineBySelection(), and TechDrawGui::TaskLineDecor::getDefaults().
getCosmeticEdge()
TechDraw::CosmeticEdge * CosmeticExtension::getCosmeticEdge (std::string id) const virtual
References Base::Console(), and Base::ConsoleSingleton::Message().
Referenced by TechDraw::DrawViewPart::add1CEToGE(), TechDrawGui::TaskCosmeticLine::createCosmeticLine(), TechDraw::DrawViewPartPy::getCosmeticEdge(), TechDraw::DrawViewPartPy::makeCosmeticCircle(), TechDraw::DrawViewPartPy::makeCosmeticCircleArc(), TechDraw::DrawViewPartPy::makeCosmeticLine(), and TechDraw::DrawViewPartPy::makeCosmeticLine3D().
getCosmeticEdgeBySelection() [1/2]
TechDraw::CosmeticEdge * CosmeticExtension::getCosmeticEdgeBySelection (int i) const virtual
getCosmeticEdgeBySelection() [2/2]
TechDraw::CosmeticEdge * CosmeticExtension::getCosmeticEdgeBySelection (std::string name) const virtual
References TechDraw::DrawViewPart::getGeomByIndex(), and TechDraw::DrawUtil::getIndexFromName().
Referenced by TechDrawGui::TaskLineDecor::applyDecorations(), TechDraw::DrawViewPartPy::getCosmeticEdgeBySelection(), TechDrawGui::TaskLineDecor::getDefaults(), and TechDrawGui::TaskCosmeticLine::TaskCosmeticLine().
getCosmeticVertex()
TechDraw::CosmeticVertex * CosmeticExtension::getCosmeticVertex (std::string id) const virtual
References TechDraw::CosmeticVertex::getTagAsString().
Referenced by TechDraw::DrawViewPart::add1CVToGV(), TechDraw::DrawViewDimExtent::checkReferences2D(), TechDraw::DrawViewDimExtent::execute(), and TechDraw::DrawViewPartPy::getCosmeticVertex().
getCosmeticVertexBySelection() [1/2]
TechDraw::CosmeticVertex * CosmeticExtension::getCosmeticVertexBySelection (int i) const virtual
getCosmeticVertexBySelection() [2/2]
TechDraw::CosmeticVertex * CosmeticExtension::getCosmeticVertexBySelection (std::string name) const virtual
References TechDraw::DrawUtil::getIndexFromName(), and TechDraw::DrawViewPart::getProjVertexByIndex().
Referenced by TechDraw::DrawViewPartPy::getCosmeticVertexBySelection().
getExtensionPyObject()
PyObject * CosmeticExtension::getExtensionPyObject (void) virtual
Reimplemented from App::DocumentObjectExtension.
getGeomFormat()
TechDraw::GeomFormat * CosmeticExtension::getGeomFormat (std::string id) const virtual
References TechDraw::GeomFormat::getTagAsString().
getGeomFormatBySelection() [1/2]
TechDraw::GeomFormat * CosmeticExtension::getGeomFormatBySelection (int i) const virtual
getGeomFormatBySelection() [2/2]
TechDraw::GeomFormat * CosmeticExtension::getGeomFormatBySelection (std::string name) const virtual
References TechDraw::DrawUtil::getIndexFromName().
Referenced by TechDrawGui::TaskLineDecor::applyDecorations(), TechDraw::DrawViewPartPy::formatGeometricEdge(), and TechDrawGui::TaskLineDecor::getDefaults().
removeCenterLine() [1/2]
void CosmeticExtension::removeCenterLine (std::string tag) virtual
Referenced by TechDraw::DrawViewPartPy::removeCenterLine().
removeCenterLine() [2/2]
void CosmeticExtension::removeCenterLine (std::vector< std::string > delTags) virtual
removeCosmeticEdge() [1/2]
void CosmeticExtension::removeCosmeticEdge (std::string tag) virtual
Referenced by TechDraw::DrawViewPartPy::removeCosmeticEdge().
removeCosmeticEdge() [2/2]
void CosmeticExtension::removeCosmeticEdge (std::vector< std::string > delTags) virtual
removeCosmeticVertex() [1/2]
void CosmeticExtension::removeCosmeticVertex (std::string tag) virtual
Referenced by TechDraw::DrawViewPartPy::removeCosmeticVertex(), and TechDraw::DrawViewDimExtent::unsetupObject().
removeCosmeticVertex() [2/2]
void CosmeticExtension::removeCosmeticVertex (std::vector< std::string > delTags) virtual
removeGeomFormat()
void CosmeticExtension::removeGeomFormat (std::string tag) virtual
replaceCenterLine()
bool CosmeticExtension::replaceCenterLine (CenterLine * newLine) virtual
References Base::Console(), and Base::ConsoleSingleton::Message().
replaceCosmeticEdge()
bool CosmeticExtension::replaceCosmeticEdge (CosmeticEdge * newEdge) virtual
References Base::Console(), and Base::ConsoleSingleton::Message().
replaceCosmeticVertex()
bool CosmeticExtension::replaceCosmeticVertex (CosmeticVertex * newVertex) virtual
References Base::Console(), and Base::ConsoleSingleton::Message().
replaceGeomFormat()
bool CosmeticExtension::replaceGeomFormat (TechDraw::GeomFormat * gf) virtual
References Base::Console(), and Base::ConsoleSingleton::Message().
Member Data Documentation
CenterLines
TechDraw::PropertyCenterLineList TechDraw::CosmeticExtension::CenterLines
Referenced by TechDraw::DrawViewPart::addCenterLinesToGeom(), TechDraw::DrawViewPart::clearCenterLines(), TechDrawGui::TaskRestoreLines::countInvisibleCenters(), and TechDrawGui::TaskRestoreLines::restoreInvisibleCenters().
CosmeticEdges
TechDraw::PropertyCosmeticEdgeList TechDraw::CosmeticExtension::CosmeticEdges
Referenced by TechDraw::DrawViewPart::addCosmeticEdgesToGeom(), TechDraw::DrawViewPart::clearCosmeticEdges(), TechDrawGui::TaskRestoreLines::countInvisibleCosmetics(), TechDraw::DrawViewPart::dumpCosEdges(), and TechDrawGui::TaskRestoreLines::restoreInvisibleCosmetics().
CosmeticVertexes
TechDraw::PropertyCosmeticVertexList TechDraw::CosmeticExtension::CosmeticVertexes
Referenced by TechDraw::DrawViewPart::addCosmeticVertexesToGeom(), TechDraw::DrawViewPart::clearCosmeticVertexes(), TechDraw::DrawViewPart::dumpCosVerts(), and TechDraw::DrawViewPart::getCVIndex().
GeomFormats
TechDraw::PropertyGeomFormatList TechDraw::CosmeticExtension::GeomFormats
Referenced by TechDraw::DrawViewPart::clearGeomFormats(), TechDrawGui::TaskRestoreLines::countInvisibleGeoms(), and TechDrawGui::TaskRestoreLines::restoreInvisibleGeoms().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/App/CosmeticExtension.h
Sources/FreeCAD/src/Mod/TechDraw/App/CosmeticExtension.cpp