FreeCAD: Gui::ExpLineEdit Class Reference
Gui::ExpLineEdit Class Reference
The ExpLineEdit class provides a lineedit that support expressing binding.
#include <Widgets.h>
Public Member Functions
bool apply (const std::string &propName)
void bind (const App::ObjectIdentifier &_path)
ExpLineEdit (QWidget *parent=0, bool expressionOnly=false)
void keyPressEvent (QKeyEvent *event)
void resizeEvent (QResizeEvent *event)
void setExpression (boost::shared_ptr< App::Expression > expr)
Public Member Functions inherited from Gui::ExpressionBinding
virtual bool apply ()
bool autoApply () const
virtual void bind (const App::Property &prop)
ExpressionBinding ()
QPixmap getIcon (const char *name, const QSize &size) const
bool hasExpression () const
bool isBound () const
void setAutoApply (bool value)
virtual ~ExpressionBinding ()
Additional Inherited Members
Protected Member Functions inherited from Gui::ExpressionBinding
void expressionChange (const App::ObjectIdentifier &id)
std::string getEscapedExpressionString () const
boost::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
const App::ObjectIdentifier & getPath () const
virtual void onChange ()
Protected Attributes inherited from Gui::ExpressionBinding
boost::signals2::scoped_connection connection
QPalette defaultPalette
int iconHeight
QLabel * iconLabel
bool m_autoApply
Detailed Description
The ExpLineEdit class provides a lineedit that support expressing binding.
Author
realthunder
Constructor & Destructor Documentation
ExpLineEdit()
ExpLineEdit::ExpLineEdit (QWidget * parent = 0, bool expressionOnly = false)
References draftgeoutils.intersections::connect(), Gui::ExpressionBinding::defaultPalette, Gui::ExpressionBinding::getIcon(), Gui::ExpressionBinding::iconHeight, and Gui::ExpressionBinding::iconLabel.
Member Function Documentation
apply()
bool ExpLineEdit::apply (const std::string & propName) virtual
Reimplemented from Gui::ExpressionBinding.
References Gui::ExpressionBinding::apply(), Gui::Command::Doc, and Base::Interpreter().
bind()
void ExpLineEdit::bind (const App::ObjectIdentifier & _path) virtual
Reimplemented from Gui::ExpressionBinding.
References Gui::ExpressionBinding::bind(), and Gui::ExpressionBinding::iconLabel.
Referenced by Gui::TreeWidgetEditDelegate::createEditor(), and Gui::PropertyEditor::PropertyItem::createExpressionEditor().
keyPressEvent()
void ExpLineEdit::keyPressEvent (QKeyEvent * event)
References Gui::ExpressionBinding::hasExpression().
resizeEvent()
void ExpLineEdit::resizeEvent (QResizeEvent * event)
References Gui::ExpressionBinding::defaultPalette, Base::Tools::fromStdString(), Gui::ExpressionBinding::getExpression(), Gui::ExpressionBinding::getIcon(), Gui::ExpressionBinding::iconHeight, Gui::ExpressionBinding::iconLabel, Gui::ExpressionBinding::isBound(), and DraftVecUtils::toString().
setExpression()
void ExpLineEdit::setExpression (boost::shared_ptr< App::Expression > expr) virtual
Reimplemented from Gui::ExpressionBinding.
References Gui::ExpressionBinding::iconLabel, Gui::ExpressionBinding::isBound(), and Gui::ExpressionBinding::setExpression().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Widgets.h
Sources/FreeCAD/src/Gui/Widgets.cpp