FreeCAD: DrawSketchHandlerArcOfHyperbola Class Reference
DrawSketchHandlerArcOfHyperbola Class Reference
Public Types
enum SelectMode {
STATUS_SEEK_First, STATUS_SEEK_Second, STATUS_SEEK_Third, STATUS_SEEK_Fourth,
STATUS_Close
}
mode table
Public Member Functions
virtual void activated (ViewProviderSketch *)
DrawSketchHandlerArcOfHyperbola ()
virtual void mouseMove (Base::Vector2d onSketchPos)
virtual bool pressButton (Base::Vector2d onSketchPos)
virtual bool releaseButton (Base::Vector2d)
virtual ~DrawSketchHandlerArcOfHyperbola ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::none, bool createowncommand=true)
virtual void deactivated (ViewProviderSketch *)
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual void quit (void)
virtual void registerPressedKey (bool, int)
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Attributes
double arcAngle
double arcAngle_t
Base::Vector2d axisPoint
Base::Vector2d centerPoint
std::vector< Base::Vector2d > EditCurve
Base::Vector2d endPoint
SelectMode Mode
Base::Vector2d startingPoint
std::vector< AutoConstraint > sugConstr1
std::vector< AutoConstraint > sugConstr2
std::vector< AutoConstraint > sugConstr3
std::vector< AutoConstraint > sugConstr4
Protected Attributes inherited from SketcherGui::DrawSketchHandler
QCursor actCursor
QPixmap actCursorPixmap
QCursor oldCursor
ViewProviderSketch * sketchgui
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
void addCursorTail (std::vector< QPixmap > &pixmaps)
void applyCursor (QCursor &newCursor)
void applyCursor (void)
qreal devicePixelRatio ()
unsigned long getCrosshairColor ()
void setCrosshairColor ()
void setCrosshairCursor (const char *svgName)
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
Sets a cursor for 3D inventor view.
void setSvgCursor (const QString &svgName, int x, int y, const std::map< unsigned long, unsigned long > &colorMapping=std::map< unsigned long, unsigned long >())
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
void unsetCursor (void)
Member Enumeration Documentation
SelectMode
enum DrawSketchHandlerArcOfHyperbola::SelectMode
mode table
Enumerator
STATUS_SEEK_First
enum value -—.
STATUS_SEEK_Second
enum value -—.
STATUS_SEEK_Third
enum value -—.
STATUS_SEEK_Fourth
enum value -—.
STATUS_Close
Constructor & Destructor Documentation
DrawSketchHandlerArcOfHyperbola()
DrawSketchHandlerArcOfHyperbola::DrawSketchHandlerArcOfHyperbola ()
~DrawSketchHandlerArcOfHyperbola()
virtual DrawSketchHandlerArcOfHyperbola::~DrawSketchHandlerArcOfHyperbola () virtual
Member Function Documentation
activated()
virtual void DrawSketchHandlerArcOfHyperbola::activated (ViewProviderSketch *) virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::setCrosshairCursor().
mouseMove()
virtual void DrawSketchHandlerArcOfHyperbola::mouseMove (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::applyCursor(), arcAngle, axisPoint, centerPoint, SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, Mode, SketcherGui::DrawSketchHandler::renderSuggestConstraintsCursor(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), SketcherGui::DrawSketchHandler::setPositionText(), SketcherGui::DrawSketchHandler::sketchgui, startingPoint, STATUS_SEEK_First, STATUS_SEEK_Fourth, STATUS_SEEK_Second, STATUS_SEEK_Third, sugConstr1, sugConstr2, sugConstr3, sugConstr4, Base::Vector2d::x, and Base::Vector2d::y.
pressButton()
virtual bool DrawSketchHandlerArcOfHyperbola::pressButton (Base::Vector2d onSketchPos) virtual
Implements SketcherGui::DrawSketchHandler.
References arcAngle, arcAngle_t, axisPoint, centerPoint, EditCurve, endPoint, Mode, startingPoint, STATUS_Close, STATUS_SEEK_First, STATUS_SEEK_Fourth, STATUS_SEEK_Second, and STATUS_SEEK_Third.
releaseButton()
virtual bool DrawSketchHandlerArcOfHyperbola::releaseButton (Base::Vector2d) virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), SketcherGui::DrawSketchHandler::applyCursor(), arcAngle, axisPoint, centerPoint, Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Base::Console(), SketcherGui::DrawSketchHandler::createAutoConstraints(), SketcherGui::ViewProviderSketch::drawEdit(), EditCurve, Sketcher::end, endPoint, Base::ConsoleSingleton::Error(), SketcherGui::geometryCreationMode, App::GetApplication(), ParameterGrp::GetBool(), SketcherGui::DrawSketchHandler::getHighestCurveIndex(), Gui::ViewProviderDocumentObject::getObject(), App::Application::GetParameterGroupByPath(), Sketcher::mid, Mode, Sketcher::none, Base::Vector2d::Normalize(), Gui::Command::openCommand(), SketcherGui::ViewProviderSketch::purgeHandler(), draftutils.translate::QT_TRANSLATE_NOOP, SketcherGui::DrawSketchHandler::resetPositionText(), Base::Vector2d::Scale(), SketcherGui::DrawSketchHandler::sketchgui, Sketcher::start, startingPoint, STATUS_Close, STATUS_SEEK_First, sugConstr1, sugConstr2, sugConstr3, sugConstr4, SketcherGui::tryAutoRecomputeIfNotSolve(), SketcherGui::DrawSketchHandler::unsetCursor(), Base::Vector2d::x, and Base::Vector2d::y.
Member Data Documentation
arcAngle
double DrawSketchHandlerArcOfHyperbola::arcAngle protected
Referenced by mouseMove(), pressButton(), and releaseButton().
arcAngle_t
double DrawSketchHandlerArcOfHyperbola::arcAngle_t protected
Referenced by pressButton().
axisPoint
Base::Vector2d DrawSketchHandlerArcOfHyperbola::axisPoint protected
Referenced by mouseMove(), pressButton(), and releaseButton().
centerPoint
Base::Vector2d DrawSketchHandlerArcOfHyperbola::centerPoint protected
Referenced by mouseMove(), pressButton(), and releaseButton().
EditCurve
std::vector<Base::Vector2d> DrawSketchHandlerArcOfHyperbola::EditCurve protected
Referenced by mouseMove(), pressButton(), and releaseButton().
endPoint
Base::Vector2d DrawSketchHandlerArcOfHyperbola::endPoint protected
Referenced by pressButton(), and releaseButton().
Mode
SelectMode DrawSketchHandlerArcOfHyperbola::Mode protected
Referenced by mouseMove(), pressButton(), and releaseButton().
startingPoint
Base::Vector2d DrawSketchHandlerArcOfHyperbola::startingPoint protected
Referenced by mouseMove(), pressButton(), and releaseButton().
sugConstr1
std::vector<AutoConstraint> DrawSketchHandlerArcOfHyperbola::sugConstr1 protected
Referenced by mouseMove(), and releaseButton().
sugConstr2
std::vector<AutoConstraint> DrawSketchHandlerArcOfHyperbola::sugConstr2 protected
Referenced by mouseMove(), and releaseButton().
sugConstr3
std::vector<AutoConstraint> DrawSketchHandlerArcOfHyperbola::sugConstr3 protected
Referenced by mouseMove(), and releaseButton().
sugConstr4
std::vector<AutoConstraint> DrawSketchHandlerArcOfHyperbola::sugConstr4 protected
Referenced by mouseMove(), and releaseButton().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/Gui/CommandCreateGeo.cpp