FreeCAD: SmSwitchboard Class Reference
SmSwitchboard Class Reference
The SmSwitchboard class is a group node that can toggle children on and off arbitrarily.
#include <SmallChange/nodes/SmSwitchboard.h>
Public Member Functions
virtual void callback (SoCallbackAction *action)
virtual void doAction (SoAction *action)
virtual void getBoundingBox (SoGetBoundingBoxAction *action)
virtual void getMatrix (SoGetMatrixAction *action)
virtual void GLRender (SoGLRenderAction *action)
virtual void handleEvent (SoHandleEventAction *action)
virtual void pick (SoPickAction *action)
virtual void search (SoSearchAction *action)
SmSwitchboard ()
SmSwitchboard (int numchildren)
Static Public Member Functions
static void initClass ()
Public Attributes
SoMFBool enable
Protected Member Functions
virtual ~SmSwitchboard ()
Detailed Description
The SmSwitchboard class is a group node that can toggle children on and off arbitrarily.
FIXME: write doc
Constructor & Destructor Documentation
SmSwitchboard() [1/2]
SmSwitchboard::SmSwitchboard ()
Default constructor.
SmSwitchboard() [2/2]
SmSwitchboard::SmSwitchboard (int numchildren)
Constructor.
The argument should be the approximate number of children which is expected to be inserted below this node. The number need not be exact, as it is only used as a hint for better memory resource allocation.
~SmSwitchboard()
SmSwitchboard::~SmSwitchboard () protected virtual
Destructor.
Member Function Documentation
callback()
void SmSwitchboard::callback (SoCallbackAction * action) virtual
References doAction().
Referenced by qtunittest.GUITestResult::addError(), Mod.Test.unittestgui.GUITestResult::addError(), qtunittest.GUITestResult::addFailure(), Mod.Test.unittestgui.GUITestResult::addFailure(), ArchStructure.StructSelectionObserver::addSelection(), PathScripts.PathCamoticsGui.CamoticsSimulation::execute(), qtunittest.GUITestResult::startTest(), Mod.Test.unittestgui.GUITestResult::startTest(), qtunittest.GUITestResult::stopTest(), and Mod.Test.unittestgui.GUITestResult::stopTest().
doAction()
void SmSwitchboard::doAction (SoAction * action) virtual
Referenced by callback(), getBoundingBox(), getMatrix(), GLRender(), handleEvent(), pick(), and search().
getBoundingBox()
void SmSwitchboard::getBoundingBox (SoGetBoundingBoxAction * action) virtual
References doAction().
getMatrix()
void SmSwitchboard::getMatrix (SoGetMatrixAction * action) virtual
References doAction().
GLRender()
void SmSwitchboard::GLRender (SoGLRenderAction * action) virtual
References doAction().
handleEvent()
void SmSwitchboard::handleEvent (SoHandleEventAction * action) virtual
References doAction().
initClass()
void SmSwitchboard::initClass () static
Referenced by Gui::SoFCDB::init().
pick()
void SmSwitchboard::pick (SoPickAction * action) virtual
References doAction().
search()
void SmSwitchboard::search (SoSearchAction * action) virtual
References doAction().
Referenced by importIFClegacy.IfcDocument::find().
Member Data Documentation
enable
SoMFBool SmSwitchboard::enable
Selects which child to traverse during rendering (and some other) actions.
When the length of this multifield is larger than the number of children this group has, the enable list is modulated over the children. This lets you have full control over the number of times and order each child is traversed.
Default enabled value is FALSE.
Referenced by SketcherGui::EditModeGeometryCoinManager::processGeometry(), and SketcherGui::EditModeConstraintCoinManager::updateVirtualSpace().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/Inventor/SmSwitchboard.h
FreeCAD/src/Gui/Inventor/SmSwitchboard.cpp