FreeCAD: FemGui::ViewProviderFemMesh Class Reference
FemGui::ViewProviderFemMesh Class Reference
#include <ViewProviderFemMesh.h>
Classes
class Private
Public Member Functions
void attach (App::DocumentObject *pcObject)
Attaches the document object to this view provider.
std::vector< std::string > getDisplayModes () const
returns a list of all possible display modes
void setDisplayMode (const char *ModeName)
set the display mode
void updateData (const App::Property *)
ViewProviderFemMesh ()
constructor.
virtual ~ViewProviderFemMesh ()
destructor.
Selection handling
This group of methods do the selection handling.
Here you can define how the selection for your ViewProvider works.
virtual bool useNewSelectionModel (void) const
indicates if the ViewProvider use the new Selection model
virtual std::string getElement (const SoDetail *) const
return a hit element to the selection path or 0
virtual SoDetail * getDetail (const char *) const
return the coin node detail of the subelement
virtual std::vector< Base::Vector3d > getSelectionShape (const char *Element) const
return the highlight lines for a given element or the whole shape
void setHighlightNodes (const std::set< long > &)
std::set< long > getHighlightNodes () const
void resetHighlightNodes (void)
Public Member Functions inherited from Gui::ViewProviderGeometryObject
SoPickedPoint * getPickedPoint (const SbVec2s &pos, const View3DInventorViewer &viewer) const
This method is provided for convenience and does basically the same as getPickedPoints() unless that only the closest point to the camera will be picked.
SoPickedPointList getPickedPoints (const SbVec2s &pos, const View3DInventorViewer &viewer, bool pickAll=false) const
Returns a list of picked points from the geometry under getRoot().
bool isSelectable (void) const
ViewProviderGeometryObject ()
constructor.
virtual ~ViewProviderGeometryObject ()
destructor.
virtual void showBoundingBox (bool)
Public Member Functions inherited from Gui::ViewProviderDragger
ViewProviderDragger ()
constructor.
virtual ~ViewProviderDragger ()
destructor.
bool doubleClicked (void) override
is called by the tree if the user double clicks on the object
void setupContextMenu (QMenu *, QObject *, const char *) override
set up the context-menu with the supported edit modes
virtual ViewProvider * startEditing (int ModNum=0) override
Public Member Functions inherited from Gui::ViewProviderDocumentObject
virtual bool canDelete (App::DocumentObject *obj) const override
Asks the view provider if the given object can be deleted.
virtual bool canDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const override
Query object dropping with full qualified name.
virtual void forceUpdate (bool enable=true)
virtual bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const override
return the coin node detail and path to the node of the subname
Gui::Document * getDocument () const
Get the GUI document to this ViewProvider object.
virtual bool getElementPicked (const SoPickedPoint *, std::string &subname) const override
return a hit element given the picked point which contains the full node path
App::DocumentObject * getObject (void) const
Get the object of this ViewProvider object.
virtual void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const override
Get a list of TaskBoxes associated with this object.
virtual const char * getTransactionText () const override
Is called by the tree if the user double clicks on the object.
virtual void hide (void) override
Hide the object in the view.
virtual bool isUpdateForced () const
virtual void reattach (App::DocumentObject *)
virtual int replaceObject (App::DocumentObject *, App::DocumentObject *) override
Replace an object to the view provider by drag and drop.
void setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
virtual void show (void) override
Show the object in the view.
virtual bool showInTree () const override
Tell the tree view if this object should appear there.
virtual void update (const App::Property *) override
update the content of the ViewProvider this method have to implement the recalculation of the ViewProvider.
void updateView ()
Run a redraw.
ViewProviderDocumentObject ()
constructor.
virtual ~ViewProviderDocumentObject ()
destructor.
virtual void startRestoring ()
virtual void finishRestoring ()
virtual bool removeDynamicProperty (const char *prop) override
virtual App::Property * addDynamicProperty (const char *type, const char *name=0, const char *group=0, const char *doc=0, short attr=0, bool ro=false, bool hidden=false) override
virtual ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=0, bool recursive=false) const
Return the linked view object.
virtual std::string getFullName () const override
virtual bool allowOverride (const App::DocumentObject &) const
Allow this class to be used as an override for the original view provider of the given object.
void setShowable (bool enable)
bool isShowable () const
Public Member Functions inherited from Gui::ViewProvider
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual std::vector< App::DocumentObject * > claimChildren3D (void) const
deliver the children belonging to this object this method is used to deliver the objects to the 3DView which should be grouped under its scene graph.
SoSeparator * getAnnotation (void)
virtual SoSeparator * getBackRoot (void) const
virtual SoGroup * getChildRoot (void) const
virtual SoSeparator * getFrontRoot (void) const
SoSwitch * getModeSwitch (void) const
virtual SoSeparator * getRoot (void) const
SoTransform * getTransformNode () const
ViewProvider ()
constructor.
virtual ~ViewProvider ()
destructor.
int partialRender (const std::vector< std::string > &subelements, bool clear)
partial rendering setup
virtual std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const
Base::BoundBox3d getBoundingBox (const char *subname=0, bool transform=true, MDIView *view=0) const
Return the bound box of this view object.
virtual bool onDelete (const std::vector< std::string > &subNames)
Get called if the object is about to get deleted.
virtual void beforeDelete ()
Called before deletion.
virtual bool canDragObjects () const
Check whether children can be removed from the view provider by drag and drop.
virtual bool canDragObject (App::DocumentObject *) const
Check whether the object can be removed from the view provider by drag and drop.
virtual void dragObject (App::DocumentObject *)
Remove a child from the view provider by drag and drop.
virtual bool canDropObjects () const
Check whether objects can be added to the view provider by drag and drop or drop only.
virtual bool canDropObject (App::DocumentObject *) const
Check whether the object can be dropped to the view provider by drag and drop or drop only.
virtual bool canDragAndDropObject (App::DocumentObject *) const
Return false to force drop only operation for a given object.
virtual void dropObject (App::DocumentObject *)
Add an object to the view provider by drag and drop.
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
Add an object with full qualified name to the view provider by drag and drop.
virtual bool canRemoveChildrenFromRoot () const
Tell the tree view to remove children items from the tree root.
std::string getActiveDisplayMode (void) const
virtual const char * getDefaultDisplayMode () const
get the default display mode
virtual bool isShow (void) const
checks whether the view provider is visible or not
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
virtual void setOverrideMode (const std::string &mode)
Overrides the display mode with mode.
const std::string getOverrideMode ()
virtual bool keyPressed (bool pressed, int key)
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
virtual bool mouseMove (const SbVec2s &cursorPos, View3DInventorViewer *viewer)
is called when the provider is in edit and the mouse is moved
virtual bool mouseButtonPressed (int button, bool pressed, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
is called when the Provider is in edit and the mouse is clicked
bool isEditing () const
void finishEditing ()
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
virtual QIcon getIcon (void) const
deliver the icon shown in the tree view
virtual std::vector< App::DocumentObject * > claimChildren (void) const
deliver the children belonging to this object this method is used to deliver the objects to the tree framework which should be grouped under its label.
virtual std::map< std::string, App::Color > getElementColors (const char *element=0) const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
virtual MDIView * getMDIView () const
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
TransactionalObject (void)
Constructor.
virtual ~TransactionalObject ()
Public Member Functions inherited from App::ExtensionContainer
ExtensionIterator extensionBegin ()
ExtensionContainer ()
ExtensionIterator extensionEnd ()
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
void registerExtension (Base::Type extension, App::Extension *ext)
virtual ~ExtensionContainer ()
virtual Property * getPropertyByName (const char *name) const override
find a property by its name
virtual const char * getPropertyName (const Property *prop) const override
get the name of a property
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
virtual void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
virtual short getPropertyType (const Property *prop) const override
get the Type of a Property
virtual short getPropertyType (const char *name) const override
get the Type of a named Property
virtual const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
Public Member Functions inherited from App::PropertyContainer
virtual App::Property * getDynamicPropertyByName (const char *name) const
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
const char * getPropertyPrefix () const
bool isHidden (const char *name) const
check if the named property is hidden
bool isHidden (const Property *prop) const
check if the property is hidden
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isReadOnly (const Property *prop) const
check if the property is read-only
PropertyContainer ()
A constructor.
void setPropertyPrefix (const char *prefix)
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
virtual ~PropertyContainer ()
A destructor.
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Attributes
App::PropertyBool BackfaceCulling
App::PropertyFloatConstraint LineWidth
App::PropertyInteger MaxFacesShowInner
App::PropertyColor PointColor
App::PropertyFloatConstraint PointSize
App::PropertyBool ShowInner
Public Attributes inherited from Gui::ViewProviderGeometryObject
App::PropertyBool BoundingBox
App::PropertyBool Selectable
App::PropertyColor ShapeColor
App::PropertyMaterial ShapeMaterial
App::PropertyPercent Transparency
Public Attributes inherited from Gui::ViewProviderDocumentObject
App::PropertyEnumeration DisplayMode
App::PropertyEnumeration OnTopWhenSelected
App::PropertyEnumeration SelectionStyle
App::PropertyBool ShowInTree
App::PropertyBool Visibility
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
Postprocessing
this interfaces apply post processing stuff to the View- Provider.
They can override the positioning and the color color or certain elements.
std::vector< unsigned long > vFaceElementIdx
index of elements to their triangles
std::vector< unsigned long > vNodeElementIdx
std::vector< unsigned long > vHighlightedIdx
std::vector< Base::Vector3d > DisplacementVector
double DisplacementFactor
SoMaterial * pcPointMaterial
SoDrawStyle * pcPointStyle
SoDrawStyle * pcDrawStyle
SoShapeHints * pShapeHints
SoMaterialBinding * pcMatBinding
SoCoordinate3 * pcCoords
SoCoordinate3 * pcAnoCoords
SoIndexedFaceSet * pcFaces
SoIndexedLineSet * pcLines
bool onlyEdges
void setColorByNodeId (const std::map< long, App::Color > &NodeColorMap)
set the color for each node
void setColorByNodeId (const std::vector< long > &NodeIds, const std::vector< App::Color > &NodeColors)
void resetColorByNodeId (void)
reset the view of the node colors
void setDisplacementByNodeId (const std::map< long, Base::Vector3d > &NodeDispMap)
set the displacement for each node
void setDisplacementByNodeId (const std::vector< long > &NodeIds, const std::vector< Base::Vector3d > &NodeDisps)
void resetDisplacementByNodeId (void)
reset the view of the node displacement
void applyDisplacementToNodes (double factor)
reaply the node displacement with a certain factor and do a redraw
void setColorByElementId (const std::map< long, App::Color > &ElementColorMap)
set the color for each element
void resetColorByElementId (void)
reset the view of the element colors
const std::vector< unsigned long > & getVisibleElementFaces (void) const
PyObject * getPyObject ()
Get the python wrapper for that ViewProvider.
virtual void onChanged (const App::Property *prop)
get called by the container whenever a property has been changed
void setColorByNodeIdHelper (const std::vector< App::Color > &)
void setDisplacementByNodeIdHelper (const std::vector< Base::Vector3d > &DispVector, long startId)
Additional Inherited Members
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0, Transform, Cutting, Color }
Public Types inherited from App::ExtensionContainer
typedef std::map< Base::Type, App::Extension * >::iterator ExtensionIterator
Static Public Member Functions inherited from Gui::ViewProviderDragger
static void updateTransform (const Base::Placement &from, SoTransform *to)
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Protected Member Functions inherited from Gui::ViewProviderGeometryObject
void setSelectable (bool Selectable=true)
virtual unsigned long getBoundColor () const
Protected Member Functions inherited from Gui::ViewProviderDragger
bool setEdit (int ModNum) override
is called by the document when the provider goes in edit mode
void unsetEdit (int ModNum) override
is called when you lose the edit mode
void setEditViewer (View3DInventorViewer *, int ModNum) override
adjust viewer settings when editing a view provider
void unsetEditViewer (View3DInventorViewer *) override
restores viewer settings when leaving editing mode
Protected Member Functions inherited from Gui::ViewProviderDocumentObject
virtual bool isAttachedToDocument () const override
virtual const char * detachFromDocument () override
virtual void onPropertyStatusChanged (const App::Property &prop, unsigned long oldStatus) override
get called when a property status has changed
virtual void setModeSwitch () override
Turn on mode switch.
Gui::MDIView * getActiveView () const
Gui::MDIView * getEditingView () const
Gui::MDIView * getInventorView () const
Gui::MDIView * getViewOfNode (SoNode *node) const
virtual void onBeforeChange (const App::Property *prop) override
get called before the value is changed
SoNode * findFrontRootOfType (const SoType &type) const
Searches in all view providers that are attached to an object that is part of the same document as the object this view provider is attached to for an front root of type.
Protected Member Functions inherited from Gui::ViewProvider
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
virtual QIcon mergeOverlayIcons (const QIcon &orig) const
bool checkRecursion (SoNode *)
Helper method to check that the node is valid, i.e.
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
Helper method to get picked entities while editing.
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
Helper method to get picked entities while editing.
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData (void) const
virtual void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container.
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::ViewProviderGeometryObject
SoMaterial * pcShapeMaterial
SoFCBoundingBox * pcBoundingBox
SoSwitch * pcBoundSwitch
SoBaseColor * pcBoundColor
Protected Attributes inherited from Gui::ViewProviderDragger
SoFCCSysDragger * csysDragger = nullptr
Protected Attributes inherited from Gui::ViewProviderDocumentObject
App::DocumentObject * pcObject
Gui::Document * pcDocument
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation
The root separator for annotations.
ViewProviderPy * pyViewObject
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Constructor & Destructor Documentation
ViewProviderFemMesh()
ViewProviderFemMesh::ViewProviderFemMesh ()
constructor.
References BackfaceCulling, DisplacementFactor, App::PropertyFloat::getValue(), LineWidth, MaxFacesShowInner, onlyEdges, pcAnoCoords, pcCoords, pcDrawStyle, pcFaces, pcLines, pcMatBinding, pcPointMaterial, pcPointStyle, PointColor, PointSize, pShapeHints, App::PropertyFloatConstraint::setConstraints(), App::PropertyColor::setValue(), Gui::ViewProviderGeometryObject::ShapeColor, ShowInner, and Gui::ViewProvider::sPixmap.
~ViewProviderFemMesh()
ViewProviderFemMesh::~ViewProviderFemMesh () virtual
destructor.
References pcAnoCoords, pcCoords, pcDrawStyle, pcFaces, pcLines, pcMatBinding, pcPointMaterial, pcPointStyle, and pShapeHints.
Member Function Documentation
applyDisplacementToNodes()
void ViewProviderFemMesh::applyDisplacementToNodes (double factor)
reaply the node displacement with a certain factor and do a redraw
References DisplacementFactor, DisplacementVector, pcCoords, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by FemGui::ViewProviderFemMeshPy::applyDisplacement(), resetDisplacementByNodeId(), and setDisplacementByNodeIdHelper().
attach()
void ViewProviderFemMesh::attach (App::DocumentObject * pcObject) virtual
Attaches the document object to this view provider.
Reimplemented from Gui::ViewProviderGeometryObject.
References Gui::ViewProvider::addDisplayMaskMode(), FemGui::ViewProviderFemMesh::Private::dm_face, FemGui::ViewProviderFemMesh::Private::dm_face_wire, FemGui::ViewProviderFemMesh::Private::dm_face_wire_node, FemGui::ViewProviderFemMesh::Private::dm_node, FemGui::ViewProviderFemMesh::Private::dm_wire, FemGui::ViewProviderFemMesh::Private::dm_wire_node, pcAnoCoords, pcCoords, pcDrawStyle, pcFaces, pcLines, pcMatBinding, pcPointMaterial, pcPointStyle, Gui::ViewProviderGeometryObject::pcShapeMaterial, and pShapeHints.
getDetail()
SoDetail * ViewProviderFemMesh::getDetail (const char *) const virtual
return the coin node detail of the subelement
Reimplemented from Gui::ViewProvider.
getDisplayModes()
std::vector< std::string > ViewProviderFemMesh::getDisplayModes (void) const virtual
returns a list of all possible display modes
Reimplemented from Gui::ViewProvider.
References FemGui::ViewProviderFemMesh::Private::dm_face, FemGui::ViewProviderFemMesh::Private::dm_face_wire, FemGui::ViewProviderFemMesh::Private::dm_face_wire_node, FemGui::ViewProviderFemMesh::Private::dm_node, FemGui::ViewProviderFemMesh::Private::dm_wire, and FemGui::ViewProviderFemMesh::Private::dm_wire_node.
getElement()
std::string ViewProviderFemMesh::getElement (const SoDetail * detail) const virtual
return a hit element to the selection path or 0
Reimplemented from Gui::ViewProvider.
References onlyEdges, vFaceElementIdx, vHighlightedIdx, and vNodeElementIdx.
getHighlightNodes()
std::set< long > ViewProviderFemMesh::getHighlightNodes () const
References vHighlightedIdx.
Referenced by FemGui::ViewProviderFemMeshPy::getHighlightedNodes().
getPyObject()
PyObject * ViewProviderFemMesh::getPyObject (void) virtual
Get the python wrapper for that ViewProvider.
Reimplemented from Gui::ViewProviderDocumentObject.
getSelectionShape()
std::vector< Base::Vector3d > ViewProviderFemMesh::getSelectionShape (const char * Element) const virtual
return the highlight lines for a given element or the whole shape
Reimplemented from Gui::ViewProvider.
getVisibleElementFaces()
const std::vector<unsigned long>& FemGui::ViewProviderFemMesh::getVisibleElementFaces (void) const
Referenced by FemGui::ViewProviderFemMeshPy::getVisibleElementFaces().
onChanged()
void ViewProviderFemMesh::onChanged (const App::Property * prop) protected virtual
get called by the container whenever a property has been changed
Reimplemented from Gui::ViewProviderGeometryObject.
References BackfaceCulling, FemGui::ViewProviderFEMMeshBuilder::createMesh(), App::PropertyInteger::getValue(), App::PropertyFloat::getValue(), App::PropertyBool::getValue(), App::PropertyColor::getValue(), LineWidth, MaxFacesShowInner, onlyEdges, pcCoords, pcDrawStyle, pcFaces, pcLines, Gui::ViewProviderDocumentObject::pcObject, pcPointMaterial, pcPointStyle, PointColor, PointSize, pShapeHints, ShowInner, vFaceElementIdx, and vNodeElementIdx.
Referenced by ArchSite.Compass::buildCoordinates(), and ArchAxis.CommandArchGrid::IsActive().
resetColorByElementId()
void ViewProviderFemMesh::resetColorByElementId (void)
reset the view of the element colors
References App::PropertyColor::getValue(), pcMatBinding, Gui::ViewProviderGeometryObject::pcShapeMaterial, and Gui::ViewProviderGeometryObject::ShapeColor.
resetColorByNodeId()
void ViewProviderFemMesh::resetColorByNodeId (void)
reset the view of the node colors
References App::PropertyColor::getValue(), pcMatBinding, Gui::ViewProviderGeometryObject::pcShapeMaterial, and Gui::ViewProviderGeometryObject::ShapeColor.
Referenced by FemGui::ViewProviderFemMeshPy::resetNodeColor(), FemGui::ViewProviderFemMeshPy::setElementColor(), FemGui::ViewProviderFemMeshPy::setNodeColor(), FemGui::ViewProviderFemMeshPy::setNodeDisplacement(), and updateData().
resetDisplacementByNodeId()
void ViewProviderFemMesh::resetDisplacementByNodeId (void)
reset the view of the node displacement
References applyDisplacementToNodes(), and DisplacementVector.
Referenced by FemGui::ViewProviderFemMeshPy::resetNodeDisplacement(), and updateData().
resetHighlightNodes()
void ViewProviderFemMesh::resetHighlightNodes (void)
References pcAnoCoords, and vHighlightedIdx.
Referenced by FemGui::TaskDlgCreateNodeSet::accept(), FemGui::TaskDlgCreateNodeSet::reject(), and FemGui::ViewProviderFemMeshPy::resetHighlightedNodes().
setColorByElementId()
void ViewProviderFemMesh::setColorByElementId (const std::map< long, App::Color > & ElementColorMap)
set the color for each element
References pcMatBinding, Gui::ViewProviderGeometryObject::pcShapeMaterial, and vFaceElementIdx.
Referenced by FemGui::ViewProviderFemMeshPy::setElementColor().
setColorByNodeId() [1/2]
void ViewProviderFemMesh::setColorByNodeId (const std::map< long, App::Color > & NodeColorMap)
set the color for each node
References setColorByNodeIdHelper().
Referenced by FemGui::ViewProviderFemMeshPy::setNodeColor(), and FemGui::ViewProviderFemMeshPy::setNodeColorByScalars().
setColorByNodeId() [2/2]
void ViewProviderFemMesh::setColorByNodeId (const std::vector< long > & NodeIds, const std::vector< App::Color > & NodeColors)
References setColorByNodeIdHelper().
setColorByNodeIdHelper()
void ViewProviderFemMesh::setColorByNodeIdHelper (const std::vector< App::Color > & colorVec) protected
References pcMatBinding, Gui::ViewProviderGeometryObject::pcShapeMaterial, and vNodeElementIdx.
Referenced by setColorByNodeId().
setDisplacementByNodeId() [1/2]
void ViewProviderFemMesh::setDisplacementByNodeId (const std::map< long, Base::Vector3d > & NodeDispMap)
set the displacement for each node
References setDisplacementByNodeIdHelper().
Referenced by FemGui::ViewProviderFemMeshPy::setNodeDisplacement(), and FemGui::ViewProviderFemMeshPy::setNodeDisplacementByVectors().
setDisplacementByNodeId() [2/2]
void ViewProviderFemMesh::setDisplacementByNodeId (const std::vector< long > & NodeIds, const std::vector< Base::Vector3d > & NodeDisps)
References setDisplacementByNodeIdHelper().
setDisplacementByNodeIdHelper()
void ViewProviderFemMesh::setDisplacementByNodeIdHelper (const std::vector< Base::Vector3d > & DispVector, long startId) protected
References applyDisplacementToNodes(), DisplacementVector, and vNodeElementIdx.
Referenced by setDisplacementByNodeId().
setDisplayMode()
void ViewProviderFemMesh::setDisplayMode (const char * ModeName) virtual
set the display mode
If you add new viewing modes in getDisplayModes() then you need to reimplement also seDisplaytMode() to handle these new modes by setting the appropriate display mode.
Reimplemented from Gui::ViewProvider.
References Gui::ViewProvider::setDisplayMaskMode().
setHighlightNodes()
void ViewProviderFemMesh::setHighlightNodes (const std::set< long > & HighlightedNodes)
References pcAnoCoords, Gui::ViewProviderDocumentObject::pcObject, and vHighlightedIdx.
Referenced by FemGui::TaskCreateNodeSet::DefineNodes(), FemGui::TaskCreateNodeSet::onSelectionChanged(), FemGui::ViewProviderFemMeshPy::setHighlightedNodes(), and FemGui::TaskCreateNodeSet::TaskCreateNodeSet().
updateData()
void ViewProviderFemMesh::updateData (const App::Property * prop) virtual
Reimplemented from Gui::ViewProviderGeometryObject.
Reimplemented in FemGui::ViewProviderFemMeshShapeNetgen.
References FemGui::ViewProviderFEMMeshBuilder::createMesh(), Base::Persistence::getClassTypeId(), App::PropertyInteger::getValue(), App::PropertyBool::getValue(), Base::BaseClass::isDerivedFrom(), MaxFacesShowInner, onlyEdges, pcCoords, pcFaces, pcLines, resetColorByNodeId(), resetDisplacementByNodeId(), ShowInner, Gui::ViewProviderGeometryObject::updateData(), vFaceElementIdx, and vNodeElementIdx.
Referenced by PathScripts.PathJobDlg.JobCreate::exec_(), PathScripts.PathOpGui.TaskPanelPage::pageUpdateData(), PathScripts.PathSetupSheetGui.OpTaskPanel::setupUi(), and FemGui::ViewProviderFemMeshShapeNetgen::updateData().
useNewSelectionModel()
virtual bool FemGui::ViewProviderFemMesh::useNewSelectionModel (void) const virtual
indicates if the ViewProvider use the new Selection model
Reimplemented from Gui::ViewProvider.
Member Data Documentation
BackfaceCulling
App::PropertyBool FemGui::ViewProviderFemMesh::BackfaceCulling
Referenced by onChanged(), and ViewProviderFemMesh().
DisplacementFactor
double FemGui::ViewProviderFemMesh::DisplacementFactor protected
Referenced by applyDisplacementToNodes(), and ViewProviderFemMesh().
DisplacementVector
std::vector<Base::Vector3d> FemGui::ViewProviderFemMesh::DisplacementVector protected
Referenced by applyDisplacementToNodes(), resetDisplacementByNodeId(), and setDisplacementByNodeIdHelper().
LineWidth
App::PropertyFloatConstraint FemGui::ViewProviderFemMesh::LineWidth
Referenced by onChanged(), and ViewProviderFemMesh().
MaxFacesShowInner
App::PropertyInteger FemGui::ViewProviderFemMesh::MaxFacesShowInner
Referenced by onChanged(), updateData(), and ViewProviderFemMesh().
onlyEdges
bool FemGui::ViewProviderFemMesh::onlyEdges protected
Referenced by getElement(), onChanged(), updateData(), and ViewProviderFemMesh().
pcAnoCoords
SoCoordinate3* FemGui::ViewProviderFemMesh::pcAnoCoords protected
Referenced by attach(), resetHighlightNodes(), setHighlightNodes(), ViewProviderFemMesh(), and ~ViewProviderFemMesh().
pcCoords
SoCoordinate3* FemGui::ViewProviderFemMesh::pcCoords protected
Referenced by applyDisplacementToNodes(), attach(), onChanged(), updateData(), ViewProviderFemMesh(), and ~ViewProviderFemMesh().
pcDrawStyle
SoDrawStyle* FemGui::ViewProviderFemMesh::pcDrawStyle protected
Referenced by attach(), onChanged(), ViewProviderFemMesh(), and ~ViewProviderFemMesh().
pcFaces
SoIndexedFaceSet* FemGui::ViewProviderFemMesh::pcFaces protected
Referenced by attach(), onChanged(), updateData(), ViewProviderFemMesh(), and ~ViewProviderFemMesh().
pcLines
SoIndexedLineSet* FemGui::ViewProviderFemMesh::pcLines protected
Referenced by attach(), onChanged(), updateData(), ViewProviderFemMesh(), and ~ViewProviderFemMesh().
pcMatBinding
SoMaterialBinding* FemGui::ViewProviderFemMesh::pcMatBinding protected
Referenced by attach(), resetColorByElementId(), resetColorByNodeId(), setColorByElementId(), setColorByNodeIdHelper(), ViewProviderFemMesh(), and ~ViewProviderFemMesh().
pcPointMaterial
SoMaterial* FemGui::ViewProviderFemMesh::pcPointMaterial protected
Referenced by attach(), onChanged(), ViewProviderFemMesh(), and ~ViewProviderFemMesh().
pcPointStyle
SoDrawStyle* FemGui::ViewProviderFemMesh::pcPointStyle protected
Referenced by attach(), onChanged(), ViewProviderFemMesh(), and ~ViewProviderFemMesh().
PointColor
App::PropertyColor FemGui::ViewProviderFemMesh::PointColor
Referenced by onChanged(), and ViewProviderFemMesh().
PointSize
App::PropertyFloatConstraint FemGui::ViewProviderFemMesh::PointSize
Referenced by onChanged(), and ViewProviderFemMesh().
pShapeHints
SoShapeHints* FemGui::ViewProviderFemMesh::pShapeHints protected
Referenced by attach(), onChanged(), ViewProviderFemMesh(), and ~ViewProviderFemMesh().
ShowInner
App::PropertyBool FemGui::ViewProviderFemMesh::ShowInner
Referenced by onChanged(), updateData(), and ViewProviderFemMesh().
vFaceElementIdx
std::vector<unsigned long> FemGui::ViewProviderFemMesh::vFaceElementIdx protected
index of elements to their triangles
Referenced by getElement(), onChanged(), setColorByElementId(), and updateData().
vHighlightedIdx
std::vector<unsigned long> FemGui::ViewProviderFemMesh::vHighlightedIdx protected
Referenced by getElement(), getHighlightNodes(), resetHighlightNodes(), and setHighlightNodes().
vNodeElementIdx
std::vector<unsigned long> FemGui::ViewProviderFemMesh::vNodeElementIdx protected
Referenced by getElement(), onChanged(), setColorByNodeIdHelper(), setDisplacementByNodeIdHelper(), and updateData().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Fem/Gui/ViewProviderFemMesh.h
Sources/FreeCAD/src/Mod/Fem/Gui/ViewProviderFemMesh.cpp