FreeCAD: Gui::WindowParameter Class Reference
Gui::WindowParameter Class Reference
Adapter class to the parameter of FreeCAD for all windows Retrieve the parameter group of the specific window by the windowname.
#include <Window.h>
Public Member Functions
ParameterGrp::handle getWindowParameter (void)
return the parameter group of this window
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason)
bool setGroupName (const char *name)
Sets the group of the window to name.
WindowParameter (const char *name)
virtual ~WindowParameter ()
Static Public Member Functions
static ParameterGrp::handle getDefaultParameter (void)
get the parameters
Detailed Description
Adapter class to the parameter of FreeCAD for all windows Retrieve the parameter group of the specific window by the windowname.
Author
Jürgen Riegel
Constructor & Destructor Documentation
WindowParameter()
WindowParameter::WindowParameter (const char * name)
References getDefaultParameter(), and ParameterGrp::GetGroup().
~WindowParameter()
WindowParameter::~WindowParameter () virtual
Member Function Documentation
getDefaultParameter()
ParameterGrp::handle WindowParameter::getDefaultParameter (void) static
get the parameters
Returns a handle to the parameter group to the user parameter under BaseApp/Preferences.
References App::GetApplication(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by Gui::SoFCSelection::applySettings(), Gui::SoFCUnifiedSelection::applySettings(), Gui::ViewProviderAnnotation::attach(), MeshGui::ViewProviderIndexedFaceSet::attach(), MeshGui::ViewProviderMeshObject::attach(), MeshGui::ViewProviderMeshFaceSet::attach(), MeshGui::ViewProviderMeshNode::attach(), Gui::DockWnd::ReportOutput::contextMenuEvent(), Gui::ViewProviderBuilder::createSelection(), MeshGui::ViewProviderMesh::fillHole(), Gui::Dialog::DlgSettingsEditorImp::loadSettings(), Gui::Dialog::DlgGeneralImp::loadSettings(), MeshGui::DlgSettingsMeshView::loadSettings(), Gui::Dialog::DlgCustomKeyboardImp::on_buttonReset_clicked(), Gui::Dialog::DlgCustomKeyboardImp::on_buttonResetAll_clicked(), Gui::Dialog::DlgCustomKeyboardImp::on_editShortcut_textChanged(), Gui::PythonConsole::onSaveHistoryAs(), Gui::Dialog::Placement::Placement(), Gui::DockWnd::ReportOutput::ReportOutput(), Gui::DockWnd::ReportView::ReportView(), Gui::Application::runApplication(), Gui::Dialog::DlgSettingsEditorImp::saveSettings(), Gui::Dialog::DlgGeneralImp::saveSettings(), setGroupName(), Gui::Dialog::DlgCustomKeyboardImp::setShortcutOfCurrentAction(), MeshGui::ViewProviderMesh::ViewProviderMesh(), MeshGui::ViewProviderMeshNode::ViewProviderMeshNode(), and WindowParameter().
getWindowParameter()
ParameterGrp::handle WindowParameter::getWindowParameter (void)
return the parameter group of this window
Referenced by Gui::DockWnd::ReportOutput::changeEvent(), Gui::PythonConsole::changeEvent(), Gui::DockWnd::ReportOutput::customEvent(), Gui::Dialog::DlgMacroExecuteImp::DlgMacroExecuteImp(), Gui::Dialog::DlgMacroRecordImp::DlgMacroRecordImp(), Gui::EditorView::EditorView(), Gui::TextEditor::keyPressEvent(), Gui::Dialog::DlgMacroExecuteImp::on_fileChooser_fileNameChanged(), Gui::Dialog::DlgMacroRecordImp::on_pushButtonChooseDir_clicked(), Gui::EditorView::OnChange(), Gui::PythonConsole::OnChange(), Gui::TextEditor::OnChange(), Gui::PrefWidget::onRestore(), Gui::PrefWidget::onSave(), Gui::DockWnd::ReportOutput::onToggleError(), Gui::DockWnd::ReportOutput::onToggleGoToEnd(), Gui::DockWnd::ReportOutput::onToggleLogMessage(), Gui::DockWnd::ReportOutput::onToggleNormalMessage(), Gui::DockWnd::ReportOutput::onToggleRedirectPythonStderr(), Gui::DockWnd::ReportOutput::onToggleRedirectPythonStdout(), Gui::DockWnd::ReportOutput::onToggleShowReportViewOnError(), Gui::DockWnd::ReportOutput::onToggleShowReportViewOnLogMessage(), Gui::DockWnd::ReportOutput::onToggleShowReportViewOnNormalMessage(), Gui::DockWnd::ReportOutput::onToggleShowReportViewOnWarning(), Gui::DockWnd::ReportOutput::onToggleWarning(), Gui::PythonConsole::PythonConsole(), Gui::DockWnd::ReportOutput::ReportOutput(), Gui::PrefSpinBox::restorePreferences(), Gui::PrefDoubleSpinBox::restorePreferences(), Gui::PrefLineEdit::restorePreferences(), Gui::PrefFileChooser::restorePreferences(), Gui::PrefComboBox::restorePreferences(), Gui::PrefCheckBox::restorePreferences(), Gui::PrefRadioButton::restorePreferences(), Gui::PrefSlider::restorePreferences(), Gui::PrefColorButton::restorePreferences(), Gui::PrefUnitSpinBox::restorePreferences(), Gui::PrefFontBox::restorePreferences(), Gui::PrefSpinBox::savePreferences(), Gui::PrefDoubleSpinBox::savePreferences(), Gui::PrefLineEdit::savePreferences(), Gui::PrefFileChooser::savePreferences(), Gui::PrefComboBox::savePreferences(), Gui::PrefCheckBox::savePreferences(), Gui::PrefRadioButton::savePreferences(), Gui::PrefSlider::savePreferences(), Gui::PrefColorButton::savePreferences(), Gui::PrefUnitSpinBox::savePreferences(), Gui::PrefFontBox::savePreferences(), Gui::PrefWidget::setParamGrpPath(), Gui::StatusBarObserver::StatusBarObserver(), Gui::TextEditor::TextEditor(), Gui::EditorView::~EditorView(), Gui::PrefWidget::~PrefWidget(), Gui::PythonConsole::~PythonConsole(), Gui::PythonEditor::~PythonEditor(), Gui::DockWnd::ReportOutput::~ReportOutput(), Gui::StatusBarObserver::~StatusBarObserver(), and Gui::TextEditor::~TextEditor().
OnChange()
void WindowParameter::OnChange (Base::Subject< const char * > & rCaller, const char * sReason)
References Base::Console(), and Base::ConsoleSingleton::Log().
setGroupName()
bool WindowParameter::setGroupName (const char * name)
Sets the group of the window to name.
References App::GetApplication(), getDefaultParameter(), ParameterGrp::GetGroup(), and App::Application::GetParameterGroupByPath().
Referenced by Gui::PrefWidget::setParamGrpPath().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Window.h
Sources/FreeCAD/src/Gui/Window.cpp