FreeCAD: FemGui::TaskFemConstraintPulley Class Reference
FemGui::TaskFemConstraintPulley Class Reference
#include <TaskFemConstraintPulley.h>
Public Member Functions
double getCenterDistance (void) const
bool getIsDriven (void) const
double getOtherDiameter (void) const
double getTensionForce (void) const
double getTorque (void) const
TaskFemConstraintPulley (ViewProviderFemConstraintPulley *ConstraintView, QWidget *parent=nullptr)
Public Member Functions inherited from FemGui::TaskFemConstraintGear
double getDiameter (void) const
const std::string getDirectionName (void) const
const std::string getDirectionObject (void) const
double getForce (void) const
double getForceAngle (void) const
bool getReverse (void) const
TaskFemConstraintGear (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="FEM_ConstraintGear")
Public Member Functions inherited from FemGui::TaskFemConstraintBearing
bool getAxial (void) const
double getDistance (void) const
const std::string getLocationName (void) const
const std::string getLocationObject (void) const
virtual const std::string getReferences () const
TaskFemConstraintBearing (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="FEM_ConstraintBearing")
virtual ~TaskFemConstraintBearing ()
Public Member Functions inherited from FemGui::TaskFemConstraint
const std::string getReferences (const std::vector< std::string > &items) const
virtual const std::string getReferences (void) const
const std::string getScale () const
TaskFemConstraint (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="")
virtual ~TaskFemConstraint ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Protected Member Functions
virtual void changeEvent (QEvent *e)
Protected Member Functions inherited from FemGui::TaskFemConstraintGear
virtual void changeEvent (QEvent *e)
virtual void onSelectionChanged (const Gui::SelectionChanges &msg)
Protected Member Functions inherited from FemGui::TaskFemConstraintBearing
virtual void changeEvent (QEvent *e)
bool event (QEvent *e)
virtual void onSelectionChanged (const Gui::SelectionChanges &msg)
Protected Member Functions inherited from FemGui::TaskFemConstraint
virtual void changeEvent (QEvent *e)
void createDeleteAction (QListWidget *parentList)
bool KeyEvent (QEvent *e)
virtual void keyPressEvent (QKeyEvent *ke)
const QString makeRefText (const App::DocumentObject *obj, const std::string &subName) const
const QString makeRefText (const std::string &objName, const std::string &subName) const
virtual void onSelectionChanged (const Gui::SelectionChanges &)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Types inherited from FemGui::TaskFemConstraint
enum { seldir , selref , selloc , selnone }
Protected Slots inherited from FemGui::TaskFemConstraint
void onButtonReference (const bool pressed=true)
void onButtonWizCancel ()
void onButtonWizOk ()
void onReferenceDeleted (const int row)
void setSelection (QListWidgetItem *item)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from FemGui::TaskFemConstraintBearing
Ui_TaskFemConstraintBearing * ui
Protected Attributes inherited from FemGui::TaskFemConstraint
Gui::WeakPtrT< ViewProviderFemConstraint > ConstraintView
QAction * deleteAction
QWidget * proxy
enum FemGui::TaskFemConstraint:: { ... } selectionMode
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskFemConstraintPulley()
TaskFemConstraintPulley::TaskFemConstraintPulley (ViewProviderFemConstraintPulley * ConstraintView, QWidget * parent = nullptr)
References Ui_TaskFemConstraintBearing::buttonDirection, Fem::ConstraintPulley::CenterDistance, Ui_TaskFemConstraintBearing::checkIsDriven, Ui_TaskFemConstraintBearing::checkReversed, draftgeoutils.intersections::connect(), FemGui::TaskFemConstraint::ConstraintView, App::PropertyFloat::getValue(), App::PropertyBool::getValue(), Fem::ConstraintPulley::IsDriven, Ui_TaskFemConstraintBearing::labelCenterDistance, Ui_TaskFemConstraintBearing::labelDiameter, Ui_TaskFemConstraintBearing::labelForce, Ui_TaskFemConstraintBearing::labelOtherDiameter, Ui_TaskFemConstraintBearing::labelTensionForce, Ui_TaskFemConstraintBearing::lineDirection, Fem::ConstraintPulley::OtherDiameter, Ui_TaskFemConstraintBearing::spinCenterDistance, Ui_TaskFemConstraintBearing::spinForce, Ui_TaskFemConstraintBearing::spinOtherDiameter, Ui_TaskFemConstraintBearing::spinTensionForce, Fem::ConstraintPulley::TensionForce, and FemGui::TaskFemConstraintBearing::ui.
Member Function Documentation
changeEvent()
void TaskFemConstraintPulley::changeEvent (QEvent * e) protected virtual
Reimplemented from FemGui::TaskFemConstraintGear.
References Ui_TaskFemConstraintBearing::checkIsDriven, FemGui::TaskFemConstraint::proxy, Ui_TaskFemConstraintBearing::retranslateUi(), Ui_TaskFemConstraintBearing::spinCenterDistance, Ui_TaskFemConstraintBearing::spinOtherDiameter, Ui_TaskFemConstraintBearing::spinTensionForce, and FemGui::TaskFemConstraintBearing::ui.
getCenterDistance()
double TaskFemConstraintPulley::getCenterDistance (void) const
References Ui_TaskFemConstraintBearing::spinCenterDistance, and FemGui::TaskFemConstraintBearing::ui.
Referenced by FemGui::TaskDlgFemConstraintPulley::accept().
getIsDriven()
bool TaskFemConstraintPulley::getIsDriven (void) const
References Ui_TaskFemConstraintBearing::checkIsDriven, and FemGui::TaskFemConstraintBearing::ui.
Referenced by FemGui::TaskDlgFemConstraintPulley::accept().
getOtherDiameter()
double TaskFemConstraintPulley::getOtherDiameter (void) const
References Ui_TaskFemConstraintBearing::spinOtherDiameter, and FemGui::TaskFemConstraintBearing::ui.
Referenced by FemGui::TaskDlgFemConstraintPulley::accept().
getTensionForce()
double TaskFemConstraintPulley::getTensionForce (void) const
References Ui_TaskFemConstraintBearing::spinTensionForce, and FemGui::TaskFemConstraintBearing::ui.
Referenced by FemGui::TaskDlgFemConstraintPulley::accept().
getTorque()
double TaskFemConstraintPulley::getTorque (void) const
References Ui_TaskFemConstraintBearing::spinForce, and FemGui::TaskFemConstraintBearing::ui.
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintPulley.h
FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintPulley.cpp