FreeCAD: Base::QuantityPy Class Reference
Base::QuantityPy Class Reference
The python export class for Quantity.
#include <QuantityPy.h>
Public Types
typedef Quantity * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
QuantityPy (Quantity *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * richCompare (PyObject *v, PyObject *w, int op)
callbacks and implementers for the python object number protocol
static PyObject * number_add_handler (PyObject *self, PyObject *other)
callback for the number_add_handler
static PyObject * number_subtract_handler (PyObject *self, PyObject *other)
callback for the number_subtract_handler
static PyObject * number_multiply_handler (PyObject *self, PyObject *other)
callback for the number_multiply_handler
static PyObject * number_divide_handler (PyObject *self, PyObject *other)
callback for the number_divide_handler
static PyObject * number_remainder_handler (PyObject *self, PyObject *other)
callback for the number_remainder_handler
static PyObject * number_divmod_handler (PyObject *self, PyObject *other)
callback for the number_divmod_handler
static PyObject * number_power_handler (PyObject *self, PyObject *other, PyObject *modulo)
callback for the number_power_handler
static PyObject * number_negative_handler (PyObject *self)
callback for the number_negative_handler
static PyObject * number_positive_handler (PyObject *self)
callback for the number_positive_handler
static PyObject * number_absolute_handler (PyObject *self)
callback for the number_absolute_handler
static int number_nonzero_handler (PyObject *self)
callback for the number_nonzero_handler
static PyObject * number_invert_handler (PyObject *self)
callback for the number_invert_handler
static PyObject * number_lshift_handler (PyObject *self, PyObject *other)
callback for the number_lshift_handler
static PyObject * number_rshift_handler (PyObject *self, PyObject *other)
callback for the number_rshift_handler
static PyObject * number_and_handler (PyObject *self, PyObject *other)
callback for the number_and_handler
static PyObject * number_xor_handler (PyObject *self, PyObject *other)
callback for the number_xor_handler
static PyObject * number_or_handler (PyObject *self, PyObject *other)
callback for the number_or_handler
static int number_coerce_handler (PyObject **self, PyObject **other)
callback for the number_coerce_handler
static PyObject * number_int_handler (PyObject *self)
callback for the number_int_handler
static PyObject * number_long_handler (PyObject *self)
callback for the number_long_handler
static PyObject * number_float_handler (PyObject *self)
callback for the number_float_handler
static PyObject * number_oct_handler (PyObject *self)
callback for the number_oct_handler
static PyObject * number_hex_handler (PyObject *self)
callback for the number_hex_handler
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of QuantityPy.
static PyMethodDef Methods []
Methods structure of QuantityPy.
static PyNumberMethods Number []
static PyTypeObject Type
Type structure of QuantityPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~QuantityPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
static PyObject * staticCallback_toStr (PyObject *self, PyObject *args)
callback for the toStr() method
static PyObject * staticCallback_getUserPreferred (PyObject *self, PyObject *args)
callback for the getUserPreferred() method
static PyObject * staticCallback_getValueAs (PyObject *self, PyObject *args)
callback for the getValueAs() method
static PyObject * staticCallback___round__ (PyObject *self, PyObject *args)
callback for the round() method
PyObject * toStr (PyObject *args)
implementer for the toStr() method
PyObject * getUserPreferred (PyObject *args)
implementer for the getUserPreferred() method
PyObject * getValueAs (PyObject *args)
implementer for the getValueAs() method
callbacks and implementers for the python object attributes
static PyObject * staticCallback_getValue (PyObject *self, void *closure)
getter callback for the Value attribute
static int staticCallback_setValue (PyObject *self, PyObject *value, void *closure)
setter callback for the Value attribute
static PyObject * staticCallback_getUnit (PyObject *self, void *closure)
getter callback for the Unit attribute
static int staticCallback_setUnit (PyObject *self, PyObject *value, void *closure)
setter callback for the Unit attribute
static PyObject * staticCallback_getUserString (PyObject *self, void *closure)
getter callback for the UserString attribute
static int staticCallback_setUserString (PyObject *self, PyObject *value, void *closure)
setter callback for the UserString attribute
static PyObject * staticCallback_getFormat (PyObject *self, void *closure)
getter callback for the Format attribute
static int staticCallback_setFormat (PyObject *self, PyObject *value, void *closure)
setter callback for the Format attribute
Py::Float getValue (void) const
getter for the Value attribute
void setValue (Py::Float arg)
setter for the Value attribute
Py::Object getUnit (void) const
getter for the Unit attribute
void setUnit (Py::Object arg)
setter for the Unit attribute
Py::String getUserString (void) const
getter for the UserString attribute
Py::Dict getFormat (void) const
getter for the Format attribute
void setFormat (Py::Dict arg)
setter for the Format attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Quantity * getQuantityPtr (void) const
getter for the object handled by this class
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Quantity.
Member Typedef Documentation
PointerType
typedef Quantity* Base::QuantityPy::PointerType
Constructor & Destructor Documentation
~QuantityPy()
QuantityPy::~QuantityPy () protected
QuantityPy()
QuantityPy::QuantityPy (Quantity * pcObject, PyTypeObject * T = &Type)
Referenced by getCustomAttributes(), getValueAs(), number_absolute_handler(), number_add_handler(), number_divide_handler(), number_multiply_handler(), number_negative_handler(), number_positive_handler(), number_power_handler(), number_remainder_handler(), number_subtract_handler(), and PyMake().
Member Function Documentation
getCustomAttributes()
PyObject * QuantityPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
References Base::Quantity::AngMinute, Base::Quantity::AngSecond, Base::Quantity::mTorr, Base::Quantity::PoundForce, QuantityPy(), Base::Quantity::Torr, and Base::Quantity::yTorr.
getFormat()
Py::Dict QuantityPy::getFormat (void) const
getter for the Format attribute
References Base::Quantity::getFormat(), and getQuantityPtr().
Referenced by staticCallback_getFormat().
getQuantityPtr()
Quantity * QuantityPy::getQuantityPtr (void) const
getter for the object handled by this class
Referenced by App::expressionFromPy(), getFormat(), getUnit(), getUserPreferred(), getUserString(), getValue(), getValueAs(), number_absolute_handler(), number_add_handler(), number_divide_handler(), number_multiply_handler(), number_negative_handler(), number_nonzero_handler(), number_positive_handler(), number_power_handler(), number_remainder_handler(), number_subtract_handler(), PyInit(), App::pyObjectToAny(), App::pyToQuantity(), representation(), richCompare(), setFormat(), setUnit(), setValue(), and toStr().
GetType()
virtual PyTypeObject* Base::QuantityPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
getUnit()
Py::Object QuantityPy::getUnit (void) const
getter for the Unit attribute
References getQuantityPtr().
Referenced by getValueAs(), Base::UnitPy::PyInit(), and staticCallback_getUnit().
getUserPreferred()
PyObject * QuantityPy::getUserPreferred (PyObject * args)
implementer for the getUserPreferred() method
References getQuantityPtr(), and Base::Quantity::getUserString().
Referenced by staticCallback_getUserPreferred().
getUserString()
Py::String QuantityPy::getUserString (void) const
getter for the UserString attribute
References getQuantityPtr().
Referenced by staticCallback_getUserString().
getValue()
Py::Float QuantityPy::getValue (void) const
getter for the Value attribute
References getQuantityPtr().
Referenced by staticCallback_getValue().
getValueAs()
PyObject * QuantityPy::getValueAs (PyObject * args)
implementer for the getValueAs() method
References getQuantityPtr(), getUnit(), Base::Quantity::getUnit(), Base::Quantity::isQuantity(), Base::Quantity::isValid(), Base::Quantity::parse(), QuantityPy(), Base::Quantity::setInvalid(), Base::Quantity::setUnit(), Base::Quantity::setValue(), Type, and Base::UnitPy::Type.
Referenced by Base::MatrixPy::rotateX(), Base::MatrixPy::rotateY(), Base::MatrixPy::rotateZ(), and staticCallback_getValueAs().
number_absolute_handler()
PyObject * QuantityPy::number_absolute_handler (PyObject * self) static
callback for the number_absolute_handler
References getQuantityPtr(), QuantityPy(), and Type.
number_add_handler()
PyObject * QuantityPy::number_add_handler (PyObject * self, PyObject * other) static
callback for the number_add_handler
References getQuantityPtr(), QuantityPy(), and Type.
number_and_handler()
PyObject * QuantityPy::number_and_handler (PyObject * self, PyObject * other) static
callback for the number_and_handler
number_coerce_handler()
int QuantityPy::number_coerce_handler (PyObject ** self, PyObject ** other) static
callback for the number_coerce_handler
number_divide_handler()
PyObject * QuantityPy::number_divide_handler (PyObject * self, PyObject * other) static
callback for the number_divide_handler
References getQuantityPtr(), QuantityPy(), and Type.
number_divmod_handler()
PyObject * QuantityPy::number_divmod_handler (PyObject * self, PyObject * other) static
callback for the number_divmod_handler
number_float_handler()
PyObject * QuantityPy::number_float_handler (PyObject * self) static
callback for the number_float_handler
References Type.
number_hex_handler()
PyObject * QuantityPy::number_hex_handler (PyObject * self) static
callback for the number_hex_handler
number_int_handler()
PyObject * QuantityPy::number_int_handler (PyObject * self) static
callback for the number_int_handler
References Type.
number_invert_handler()
PyObject * QuantityPy::number_invert_handler (PyObject * self) static
callback for the number_invert_handler
number_long_handler()
PyObject * QuantityPy::number_long_handler (PyObject * self) static
callback for the number_long_handler
References Type.
number_lshift_handler()
PyObject * QuantityPy::number_lshift_handler (PyObject * self, PyObject * other) static
callback for the number_lshift_handler
number_multiply_handler()
PyObject * QuantityPy::number_multiply_handler (PyObject * self, PyObject * other) static
callback for the number_multiply_handler
References getQuantityPtr(), QuantityPy(), and Type.
number_negative_handler()
PyObject * QuantityPy::number_negative_handler (PyObject * self) static
callback for the number_negative_handler
References getQuantityPtr(), QuantityPy(), and Type.
number_nonzero_handler()
int QuantityPy::number_nonzero_handler (PyObject * self) static
callback for the number_nonzero_handler
References getQuantityPtr(), Base::Quantity::getValue(), and Type.
number_oct_handler()
PyObject * QuantityPy::number_oct_handler (PyObject * self) static
callback for the number_oct_handler
number_or_handler()
PyObject * QuantityPy::number_or_handler (PyObject * self, PyObject * other) static
callback for the number_or_handler
number_positive_handler()
PyObject * QuantityPy::number_positive_handler (PyObject * self) static
callback for the number_positive_handler
References getQuantityPtr(), QuantityPy(), and Type.
number_power_handler()
PyObject * QuantityPy::number_power_handler (PyObject * self, PyObject * other, PyObject * modulo) static
callback for the number_power_handler
References getQuantityPtr(), QuantityPy(), and Type.
number_remainder_handler()
PyObject * QuantityPy::number_remainder_handler (PyObject * self, PyObject * other) static
callback for the number_remainder_handler
References getQuantityPtr(), Base::Quantity::getValue(), QuantityPy(), and Type.
number_rshift_handler()
PyObject * QuantityPy::number_rshift_handler (PyObject * self, PyObject * other) static
callback for the number_rshift_handler
number_subtract_handler()
PyObject * QuantityPy::number_subtract_handler (PyObject * self, PyObject * other) static
callback for the number_subtract_handler
References getQuantityPtr(), QuantityPy(), and Type.
number_xor_handler()
PyObject * QuantityPy::number_xor_handler (PyObject * self, PyObject * other) static
callback for the number_xor_handler
PyInit()
int QuantityPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
References getQuantityPtr(), Base::Quantity::parse(), Type, and Base::UnitPy::Type.
PyMake()
PyObject * QuantityPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References QuantityPy().
representation()
std::string QuantityPy::representation (void) const
References getQuantityPtr(), Base::Unit::getString(), Base::Quantity::getUnit(), and Base::Quantity::getValue().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
richCompare()
PyObject * QuantityPy::richCompare (PyObject * v, PyObject * w, int op) static
References getQuantityPtr(), and Type.
setCustomAttributes()
int QuantityPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setFormat()
void QuantityPy::setFormat (Py::Dict arg)
setter for the Format attribute
References Base::Quantity::getFormat(), getQuantityPtr(), Base::Quantity::setFormat(), and Base::QuantityFormat::toFormat().
Referenced by PathScripts.PathInspect.GCodeHighlighter::highlightBlock(), PathScripts.PostUtils.GCodeHighlighter::highlightBlock(), and staticCallback_setFormat().
setUnit()
void QuantityPy::setUnit (Py::Object arg)
setter for the Unit attribute
References getQuantityPtr(), PyType_Object::o, Base::Quantity::setUnit(), and Base::UnitPy::Type.
Referenced by staticCallback_setUnit().
setValue()
void QuantityPy::setValue (Py::Float arg)
setter for the Value attribute
References getQuantityPtr(), and Base::Quantity::setValue().
Referenced by staticCallback_setValue().
staticCallback___round__()
PyObject * QuantityPy::staticCallback___round__ (PyObject * self, PyObject * args) static
callback for the round() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, and Base::PyObjectBase::isValid().
staticCallback_getFormat()
PyObject * QuantityPy::staticCallback_getFormat (PyObject * self, void * closure) static
getter callback for the Format attribute
References Base::BaseExceptionFreeCADError, getFormat(), and Base::PyObjectBase::isValid().
staticCallback_getUnit()
PyObject * QuantityPy::staticCallback_getUnit (PyObject * self, void * closure) static
getter callback for the Unit attribute
References Base::BaseExceptionFreeCADError, getUnit(), and Base::PyObjectBase::isValid().
staticCallback_getUserPreferred()
PyObject * QuantityPy::staticCallback_getUserPreferred (PyObject * self, PyObject * args) static
callback for the getUserPreferred() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getUserPreferred(), and Base::PyObjectBase::isValid().
staticCallback_getUserString()
PyObject * QuantityPy::staticCallback_getUserString (PyObject * self, void * closure) static
getter callback for the UserString attribute
References Base::BaseExceptionFreeCADError, getUserString(), and Base::PyObjectBase::isValid().
staticCallback_getValue()
PyObject * QuantityPy::staticCallback_getValue (PyObject * self, void * closure) static
getter callback for the Value attribute
References Base::BaseExceptionFreeCADError, getValue(), and Base::PyObjectBase::isValid().
staticCallback_getValueAs()
PyObject * QuantityPy::staticCallback_getValueAs (PyObject * self, PyObject * args) static
callback for the getValueAs() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getValueAs(), and Base::PyObjectBase::isValid().
staticCallback_setFormat()
int QuantityPy::staticCallback_setFormat (PyObject * self, PyObject * value, void * closure) static
setter callback for the Format attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setFormat().
staticCallback_setUnit()
int QuantityPy::staticCallback_setUnit (PyObject * self, PyObject * value, void * closure) static
setter callback for the Unit attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setUnit().
staticCallback_setUserString()
int QuantityPy::staticCallback_setUserString (PyObject * self, PyObject * value, void * closure) static
setter callback for the UserString attribute
References Base::PyObjectBase::isValid().
staticCallback_setValue()
int QuantityPy::staticCallback_setValue (PyObject * self, PyObject * value, void * closure) static
setter callback for the Value attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setValue().
staticCallback_toStr()
PyObject * QuantityPy::staticCallback_toStr (PyObject * self, PyObject * args) static
callback for the toStr() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and toStr().
toStr()
PyObject * QuantityPy::toStr (PyObject * args)
implementer for the toStr() method
References Base::Quantity::getFormat(), getQuantityPtr(), Base::Quantity::getUnit(), Base::Quantity::getValue(), and Base::QuantityFormat::precision.
Referenced by staticCallback_toStr().
Member Data Documentation
GetterSetter
PyGetSetDef QuantityPy::GetterSetter static
Initial value:
= {
    {"Value",
        (getter) staticCallback_getValue,
        (setter) staticCallback_setValue,
        "Numeric Value of the Quantity (in internal system mm,kg,s)",
        NULL
    },
    {"Unit",
        (getter) staticCallback_getUnit,
        (setter) staticCallback_setUnit,
        "Unit of the Quantity",
        NULL
    },
    {"UserString",
        (getter) staticCallback_getUserString,
        (setter) staticCallback_setUserString,
        "Unit of the Quantity",
        NULL
    },
    {"Format",
        (getter) staticCallback_getFormat,
        (setter) staticCallback_setFormat,
        "Format of the Quantity",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of QuantityPy.
Methods
PyMethodDef QuantityPy::Methods static
Initial value:
= {
    {"toStr",
        reinterpret_cast<PyCFunction>( staticCallback_toStr ),
        METH_VARARGS,
        "\n          toStr([decimals])\n          returns a string representation rounded to number of decimals. If no decimals are specified then\n          the internal precision is used\n        "
    },
    {"getUserPreferred",
        reinterpret_cast<PyCFunction>( staticCallback_getUserPreferred ),
        METH_VARARGS,
        "\n          returns a quantity with the translation factor and a string with the prevered unit\n        "
    },
    {"getValueAs",
        reinterpret_cast<PyCFunction>( staticCallback_getValueAs ),
        METH_VARARGS,
        "\n          returns a floating point value as the provided unit\n\n          Following parameters are allowed:\n          getValueAs('m/s')  # unit string to parse\n          getValueAs(2.45,1) # translatrion value and unit signature\n          getValueAs(FreeCAD.Units.Pascal) # predefined standard units \n          getValueAs(Qantity('N/m^2')) # a quantity\n          getValueAs(Unit(0,1,0,0,0,0,0,0)) # a unit\n        "
    },
    {"__round__",
        reinterpret_cast<PyCFunction>( staticCallback___round__ ),
        METH_VARARGS,
        "\nReturn the Integral closest to x, rounding half toward even.\nWhen an argument is passed, work like built-in round(x, ndigits).\n        "
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of QuantityPy.
Number
PyNumberMethods QuantityPy::Number static
Type
PyTypeObject QuantityPy::Type static
Type structure of QuantityPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), App::expressionFromPy(), getValueAs(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), number_absolute_handler(), number_add_handler(), number_divide_handler(), number_float_handler(), number_int_handler(), number_long_handler(), number_multiply_handler(), number_negative_handler(), number_nonzero_handler(), number_positive_handler(), number_power_handler(), number_remainder_handler(), number_subtract_handler(), PyInit(), Base::UnitPy::PyInit(), Sketcher::ConstraintPy::PyInit(), App::pyObjectToAny(), App::pyToQuantity(), richCompare(), Base::MatrixPy::rotateX(), Base::MatrixPy::rotateY(), Base::MatrixPy::rotateZ(), draftobjects.layer.Layer::set_properties(), Sketcher::SketchObjectPy::setDatum(), ArchReference.ArchReference::setProperties(), and Base::UnitsApi::sSchemaTranslate().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Base/QuantityPy.h
Sources/FreeCAD/src/Base/QuantityPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Base/QuantityPy.cpp