FreeCAD: SMDS_BallElement Class Reference
SMDS_BallElement Class Reference
#include <SMDS_BallElement.hxx>
Public Member Functions
bool ChangeNode (const SMDS_MeshNode *node)
virtual bool ChangeNodes (const SMDS_MeshNode *nodes[], const int)
double GetDiameter () const
virtual SMDSAbs_EntityType GetEntityType () const
virtual SMDSAbs_GeometryType GetGeomType () const
virtual const SMDS_MeshNode * GetNode (const int ind) const
Return node by its index.
virtual SMDSAbs_ElementType GetType () const
Return the type of the current element.
virtual vtkIdType GetVtkType () const
void init (vtkIdType nodeId, double diameter, SMDS_Mesh *mesh)
virtual int NbEdges () const
Return the number of edges owned by or linked with the current element.
virtual int NbFaces () const
Return the number of faces owned by or linked with the current element.
virtual int NbNodes () const
Return The number of nodes owned by the current element.
virtual void Print (std::ostream &OS) const
void SetDiameter (double diameter)
SMDS_BallElement ()
SMDS_BallElement (const SMDS_MeshNode *node, double diameter)
SMDS_BallElement (vtkIdType nodeId, double diameter, SMDS_Mesh *mesh)
Public Member Functions inherited from SMDS_MeshCell
SMDS_MeshCell ()
virtual bool vtkOrder (const SMDS_MeshNode *[], const int)
virtual ~SMDS_MeshCell ()
Public Member Functions inherited from SMDS_MeshElement
iterator begin_nodes () const
SMDS_ElemIteratorPtr edgesIterator () const
Create an iterator which iterate on edges linked with or owned by the element.
iterator end_nodes () const
SMDS_ElemIteratorPtr facesIterator () const
Create an iterator which iterate on faces linked with or owned by the element.
int GetID () const
int getIdInShape () const
ShortType getMeshId () const
virtual int GetNodeIndex (const SMDS_MeshNode *node) const
Check if a node belongs to the element.
const SMDS_MeshNode * GetNodeWrap (const int ind) const
Return node by its index.
LongType getshapeId () const
int getVtkId () const
virtual SMDS_ElemIteratorPtr interlacedNodesElemIterator () const
virtual SMDS_NodeIteratorPtr interlacedNodesIterator () const
virtual, redefined in vtkEdge, vtkFace and vtkVolume classes
virtual bool IsMediumNode (const SMDS_MeshNode *node) const
virtual bool IsPoly () const
virtual bool IsQuadratic () const
virtual bool IsValidIndex (const int ind) const
Return true if index of node is valid (0 <= ind < NbNodes())
virtual int NbCornerNodes () const
Return number of nodes excluding medium ones.
virtual SMDS_NodeIteratorPtr nodeIterator () const
SMDS_ElemIteratorPtr nodesIterator () const
Create an iterator which iterate on nodes owned by the element.
virtual SMDS_NodeIteratorPtr nodesIteratorToUNV () const
virtual, redefined in vtkEdge, vtkFace and vtkVolume classes
int WrappedIndex (const int ind) const
Return a valid node index, fixing the given one if necessary.
Public Member Functions inherited from SMDS_MeshObject
virtual ~SMDS_MeshObject ()
Protected Member Functions
SMDS_ElemIteratorPtr elementsIterator (SMDSAbs_ElementType type) const
Protected Member Functions inherited from SMDS_MeshCell
void exchange (const SMDS_MeshNode *nodes[], int a, int b)
Protected Member Functions inherited from SMDS_MeshElement
virtual void init (int id=-1, ShortType meshId=-1, LongType shapeId=0)
void setId (int id)
void setIdInShape (int id)
void setShapeId (LongType shapeId)
void setVtkId (int vtkId)
SMDS_MeshElement (int id, ShortType meshId, LongType shapeId=0)
SMDS_MeshElement (int ID=-1)
Additional Inherited Members
Public Types inherited from SMDS_MeshElement
typedef SMDS_StdIterator< const SMDS_MeshNode *, SMDS_ElemIteratorPtr > iterator
Static Public Member Functions inherited from SMDS_MeshCell
template<class VECT >
static void applyInterlace (const std::vector< int > &interlace, VECT &data)
template<class VECT >
static void applyInterlaceRev (const std::vector< int > &interlace, VECT &data)
static const std::vector< int > & fromVtkOrder (SMDSAbs_EntityType smdsType)
Return indices to transform cell connectivity from VTK to SMDS Usage: smdsIDs[i] = vtkIDs[ indices[ i ]].
static const std::vector< int > & fromVtkOrder (VTKCellType vtkType)
Return indices to transform cell connectivity from VTK to SMDS Usage: smdsIDs[i] = vtkIDs[ indices[ i ]].
static const std::vector< int > & interlacedSmdsOrder (SMDSAbs_EntityType smdsType, const size_t nbNodes=0)
Return indices to set nodes of a quadratic 1D or 2D element in interlaced order Usage: interlacedIDs[i] = smdsIDs[ indices[ i ]].
static const std::vector< int > & reverseSmdsOrder (SMDSAbs_EntityType smdsType, const size_t nbNodes=0)
Return indices to reverse an SMDS cell of given type. nbNodes is useful for polygons Usage: reverseIDs[i] = forwardIDs[ indices[ i ]].
static SMDSAbs_ElementType toSmdsType (SMDSAbs_EntityType entityType)
Return SMDSAbs_ElementType by SMDSAbs_EntityType.
static SMDSAbs_ElementType toSmdsType (SMDSAbs_GeometryType geomType)
Return SMDSAbs_ElementType by SMDSAbs_GeometryType.
static SMDSAbs_EntityType toSmdsType (VTKCellType vtkType)
Return SMDSAbs_EntityType corresponding to VTKCellType.
static const std::vector< int > & toVtkOrder (SMDSAbs_EntityType smdsType)
Return indices to transform cell connectivity from SMDS to VTK Usage: vtkIDs[i] = smdsIDs[ indices[ i ]].
static const std::vector< int > & toVtkOrder (VTKCellType vtkType)
Return indices to transform cell connectivity from SMDS to VTK Usage: vtkIDs[i] = smdsIDs[ indices[ i ]].
static VTKCellType toVtkType (SMDSAbs_EntityType vtkType)
Return VTKCellType corresponding to SMDSAbs_EntityType.
Static Public Attributes inherited from SMDS_MeshCell
static int nbCells = 0
Protected Attributes inherited from SMDS_MeshElement
int myID
Element index in vector SMDS_Mesh::myNodes or SMDS_Mesh::myCells.
int myIdInShape
Element index in SMESHDS_SubMesh vector.
ShortType myMeshId
SMDS_Mesh identification in SMESH.
LongType myShapeId
SubShape and SubMesh identification in SMESHDS.
int myVtkID
index in vtkUnstructuredGrid
Constructor & Destructor Documentation
SMDS_BallElement() [1/3]
SMDS_BallElement::SMDS_BallElement ()
References SMDS_MeshElement::init().
SMDS_BallElement() [2/3]
SMDS_BallElement::SMDS_BallElement (const SMDS_MeshNode * node, double diameter)
References SMDS_MeshElement::getMeshId(), SMDS_MeshElement::getVtkId(), and init().
SMDS_BallElement() [3/3]
SMDS_BallElement::SMDS_BallElement (vtkIdType nodeId, double diameter, SMDS_Mesh * mesh)
References init().
Member Function Documentation
ChangeNode()
bool SMDS_BallElement::ChangeNode (const SMDS_MeshNode * node)
References SMDS_MeshElement::getVtkId(), SMDS_MeshElement::myMeshId, and SMDS_MeshElement::myVtkID.
ChangeNodes()
virtual bool SMDS_BallElement::ChangeNodes (const SMDS_MeshNode * nodes[], const int) virtual
Implements SMDS_MeshCell.
elementsIterator()
SMDS_ElemIteratorPtr SMDS_BallElement::elementsIterator (SMDSAbs_ElementType type) const protected virtual
Reimplemented from SMDS_MeshElement.
References GetEntityType(), SMDS_MeshElement::myMeshId, and SMDS_MeshElement::myVtkID.
GetDiameter()
double SMDS_BallElement::GetDiameter () const
References SMDS_MeshElement::myMeshId, and SMDS_MeshElement::myVtkID.
GetEntityType()
virtual SMDSAbs_EntityType SMDS_BallElement::GetEntityType () const virtual
Implements SMDS_MeshElement.
Referenced by elementsIterator().
GetGeomType()
virtual SMDSAbs_GeometryType SMDS_BallElement::GetGeomType () const virtual
Implements SMDS_MeshElement.
GetNode()
const SMDS_MeshNode * SMDS_BallElement::GetNode (const int ind) const virtual
Return node by its index.
Parameters
ind - node index
Return values
const SMDS_MeshNode* - the node
Reimplemented from SMDS_MeshElement.
References SMDS_MeshElement::myMeshId, and SMDS_MeshElement::myVtkID.
GetType()
virtual SMDSAbs_ElementType SMDS_BallElement::GetType () const virtual
Return the type of the current element.
Implements SMDS_MeshElement.
GetVtkType()
virtual vtkIdType SMDS_BallElement::GetVtkType () const virtual
Implements SMDS_MeshElement.
Referenced by init().
init()
void SMDS_BallElement::init (vtkIdType nodeId, double diameter, SMDS_Mesh * mesh)
References GetVtkType(), SMDS_MeshElement::init(), SMDS_MeshElement::myMeshId, and SMDS_MeshElement::myVtkID.
Referenced by SMDS_Mesh::AddBallWithID(), DocumentObject.DocumentObject::onChanged(), and SMDS_BallElement().
NbEdges()
virtual int SMDS_BallElement::NbEdges () const virtual
Return the number of edges owned by or linked with the current element.
Reimplemented from SMDS_MeshElement.
NbFaces()
virtual int SMDS_BallElement::NbFaces () const virtual
Return the number of faces owned by or linked with the current element.
Reimplemented from SMDS_MeshElement.
NbNodes()
virtual int SMDS_BallElement::NbNodes () const virtual
Return The number of nodes owned by the current element.
Reimplemented from SMDS_MeshElement.
Print()
void SMDS_BallElement::Print (std::ostream & OS) const virtual
Reimplemented from SMDS_MeshElement.
References SMDS_MeshElement::GetID().
SetDiameter()
void SMDS_BallElement::SetDiameter (double diameter)
References SMDS_MeshElement::myMeshId, and SMDS_MeshElement::myVtkID.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_BallElement.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_BallElement.cpp