FreeCAD: Ui_TaskDriver Class Reference
Ui_TaskDriver Class Reference
#include <ui_TaskDriver.h>
Public Member Functions
void retranslateUi (QWidget *TaskDriver)
void setupUi (QWidget *TaskDriver)
Public Attributes
QComboBox * DrivercomboBox
QTextEdit * textEdit
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void Ui_TaskDriver::retranslateUi (QWidget * TaskDriver)
References draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Ui_TaskDriver::setupUi (QWidget * TaskDriver)
References DrivercomboBox, retranslateUi(), textEdit, and verticalLayout.
Referenced by FemGui::TaskDriver::TaskDriver().
Member Data Documentation
DrivercomboBox
QComboBox* Ui_TaskDriver::DrivercomboBox
Referenced by setupUi().
textEdit
QTextEdit* Ui_TaskDriver::textEdit
Referenced by setupUi().
verticalLayout
QVBoxLayout* Ui_TaskDriver::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Fem/Gui/ui_TaskDriver.h