FreeCAD: Gui::Dialog::DlgEditFileIncludePropertyExternal Class Reference
Gui::Dialog::DlgEditFileIncludePropertyExternal Class Reference
#include <DlgEditFileIncludePropertyExternal.h>
Public Member Functions
DlgEditFileIncludePropertyExternal (App::PropertyFileIncluded &Prop, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
Constructs a DlgEditFileIncludePropertyExternal which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
int Do (void)
virtual ~DlgEditFileIncludePropertyExternal ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::DlgRunExternal
DlgRunExternal (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
Constructs a DlgRunExternal which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
int Do (void)
virtual ~DlgRunExternal ()
Destroys the object and frees any allocated resources.
Protected Attributes
App::PropertyFileIncluded & Prop
Protected Attributes inherited from Gui::Dialog::DlgRunExternal
bool advancedHidden
QProcess process
Additional Inherited Members
Public Attributes inherited from Gui::Dialog::DlgRunExternal
QStringList arguments
QString ProcName
Protected Slots inherited from Gui::Dialog::DlgRunExternal
virtual void abort (void)
virtual void accept (void)
virtual void advanced (void)
void finished (int exitCode, QProcess::ExitStatus exitStatus)
void on_chooseProgram_clicked ()
virtual void reject (void)
Detailed Description
Author
Jürgen Riegel
Constructor & Destructor Documentation
DlgEditFileIncludePropertyExternal()
DlgEditFileIncludePropertyExternal::DlgEditFileIncludePropertyExternal (App::PropertyFileIncluded & Prop, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Constructs a DlgEditFileIncludePropertyExternal which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
~DlgEditFileIncludePropertyExternal()
DlgEditFileIncludePropertyExternal::~DlgEditFileIncludePropertyExternal () virtual
Destroys the object and frees any allocated resources.
Member Function Documentation
Do()
int DlgEditFileIncludePropertyExternal::Do (void)
References Gui::Dialog::DlgRunExternal::arguments, Gui::Dialog::DlgRunExternal::Do(), App::Application::getUserCachePath(), App::PropertyFileIncluded::getValue(), Prop, and App::PropertyFileIncluded::setValue().
Member Data Documentation
Prop
App::PropertyFileIncluded& Gui::Dialog::DlgEditFileIncludePropertyExternal::Prop protected
Referenced by Do().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgEditFileIncludePropertyExternal.h
FreeCAD/src/Gui/DlgEditFileIncludePropertyExternal.cpp