FreeCAD: Gui::CustomPageProducer< CLASS > Class Template Reference
Gui::CustomPageProducer< CLASS > Class Template Reference
The CustomPageProducer class is a value-based template class that provides the ability to create custom pages dynamically.
#include <WidgetFactory.h>
Public Member Functions
CustomPageProducer ()
Register a special type of customize page to the WidgetFactoryInst.
virtual void * Produce () const
Creates an instance of the specified widget.
virtual ~CustomPageProducer ()
Public Member Functions inherited from Base::AbstractProducer
AbstractProducer ()
virtual ~AbstractProducer ()
Detailed Description
template<class CLASS>
class Gui::CustomPageProducer< CLASS >
The CustomPageProducer class is a value-based template class that provides the ability to create custom pages dynamically.
Author
Werner Mayer
Constructor & Destructor Documentation
CustomPageProducer()
template<class CLASS > Gui::CustomPageProducer< CLASS >::CustomPageProducer ()
Register a special type of customize page to the WidgetFactoryInst.
References Gui::Dialog::DlgCustomizeImp::addPage(), Base::Factory::AddProducer(), and Gui::WidgetFactoryInst::instance().
~CustomPageProducer()
template<class CLASS > virtual Gui::CustomPageProducer< CLASS >::~CustomPageProducer () virtual
Member Function Documentation
Produce()
template<class CLASS > virtual void* Gui::CustomPageProducer< CLASS >::Produce (void) const virtual
Creates an instance of the specified widget.
Implements Base::AbstractProducer.
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/WidgetFactory.h