FreeCAD: PartGui::DlgImportExportStep Class Reference
PartGui::DlgImportExportStep Class Reference
#include <DlgSettingsGeneral.h>
Public Member Functions
DlgImportExportStep (QWidget *parent=0)
~DlgImportExportStep ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=0)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void loadSettings ()
void saveSettings ()
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
Constructor & Destructor Documentation
DlgImportExportStep()
DlgImportExportStep::DlgImportExportStep (QWidget * parent = 0)
~DlgImportExportStep()
DlgImportExportStep::~DlgImportExportStep ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void DlgImportExportStep::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
loadSettings()
void DlgImportExportStep::loadSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), and App::Application::GetUserParameter().
saveSettings()
void DlgImportExportStep::saveSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), ParameterGrp::SetASCII(), and ParameterGrp::SetInt().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/Gui/DlgSettingsGeneral.h
Sources/FreeCAD/src/Mod/Part/Gui/DlgSettingsGeneral.cpp