FreeCAD: Spaceball::EventBase Class Reference
Spaceball::EventBase Class Reference
#include <SpaceballEvent.h>
Public Member Functions
bool isHandled ()
void setHandled (bool sig)
Protected Member Functions
EventBase (QEvent::Type event)
Protected Attributes
bool handled
Constructor & Destructor Documentation
EventBase()
EventBase::EventBase (QEvent::Type event) protected
Member Function Documentation
isHandled()
bool Spaceball::EventBase::isHandled ()
References handled.
Referenced by Gui::GUIApplicationNativeEventAware::processSpaceballEvent().
setHandled()
void Spaceball::EventBase::setHandled (bool sig)
References handled.
Referenced by Gui::MainWindow::event(), Gui::Dialog::DlgCustomizeSpaceball::event(), and SpaceNavigatorDevice::translateEvent().
Member Data Documentation
handled
bool Spaceball::EventBase::handled protected
Referenced by Spaceball::ButtonEvent::ButtonEvent(), isHandled(), Spaceball::MotionEvent::MotionEvent(), Spaceball::ButtonEvent::operator=(), Spaceball::MotionEvent::operator=(), and setHandled().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SpaceballEvent.h
Sources/FreeCAD/src/Gui/SpaceballEvent.cpp