FreeCAD: PartDesignGui::Ui_TaskThicknessParameters Class Reference
PartDesignGui::Ui_TaskThicknessParameters Class Reference
#include <ui_TaskThicknessParameters.h>
Public Member Functions
void retranslateUi (QWidget *PartDesignGui__TaskThicknessParameters)
void setupUi (QWidget *PartDesignGui__TaskThicknessParameters)
Public Attributes
QToolButton * buttonRefAdd
QToolButton * buttonRefRemove
QCheckBox * checkIntersection
QCheckBox * checkReverse
QGridLayout * gridLayout_2
QHBoxLayout * horizontalLayout
QComboBox * joinComboBox
QLabel * label
QLabel * label_2
QLabel * label_3
QListWidget * listWidgetReferences
QComboBox * modeComboBox
Gui::QuantitySpinBox * Value
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void PartDesignGui::Ui_TaskThicknessParameters::retranslateUi (QWidget * PartDesignGui__TaskThicknessParameters)
References buttonRefAdd, buttonRefRemove, checkIntersection, checkReverse, joinComboBox, label_2, label_3, listWidgetReferences, modeComboBox, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void PartDesignGui::Ui_TaskThicknessParameters::setupUi (QWidget * PartDesignGui__TaskThicknessParameters)
References buttonRefAdd, buttonRefRemove, checkIntersection, checkReverse, gridLayout_2, horizontalLayout, joinComboBox, label_2, label_3, listWidgetReferences, modeComboBox, retranslateUi(), Gui::QuantitySpinBox::setMaximum(), Gui::QuantitySpinBox::setMinimum(), Gui::QuantitySpinBox::setSingleStep(), Gui::QuantitySpinBox::setValue(), Value, and verticalLayout.
Member Data Documentation
buttonRefAdd
QToolButton* PartDesignGui::Ui_TaskThicknessParameters::buttonRefAdd
Referenced by retranslateUi(), and setupUi().
buttonRefRemove
QToolButton* PartDesignGui::Ui_TaskThicknessParameters::buttonRefRemove
Referenced by retranslateUi(), and setupUi().
checkIntersection
QCheckBox* PartDesignGui::Ui_TaskThicknessParameters::checkIntersection
Referenced by retranslateUi(), and setupUi().
checkReverse
QCheckBox* PartDesignGui::Ui_TaskThicknessParameters::checkReverse
Referenced by retranslateUi(), and setupUi().
gridLayout_2
QGridLayout* PartDesignGui::Ui_TaskThicknessParameters::gridLayout_2
Referenced by setupUi().
horizontalLayout
QHBoxLayout* PartDesignGui::Ui_TaskThicknessParameters::horizontalLayout
Referenced by setupUi().
joinComboBox
QComboBox* PartDesignGui::Ui_TaskThicknessParameters::joinComboBox
Referenced by retranslateUi(), and setupUi().
label
QLabel* PartDesignGui::Ui_TaskThicknessParameters::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
label_2
QLabel* PartDesignGui::Ui_TaskThicknessParameters::label_2
Referenced by retranslateUi(), and setupUi().
label_3
QLabel* PartDesignGui::Ui_TaskThicknessParameters::label_3
Referenced by retranslateUi(), and setupUi().
listWidgetReferences
QListWidget* PartDesignGui::Ui_TaskThicknessParameters::listWidgetReferences
Referenced by retranslateUi(), and setupUi().
modeComboBox
QComboBox* PartDesignGui::Ui_TaskThicknessParameters::modeComboBox
Referenced by retranslateUi(), and setupUi().
Value
Gui::QuantitySpinBox* PartDesignGui::Ui_TaskThicknessParameters::Value
Referenced by setupUi().
verticalLayout
QVBoxLayout* PartDesignGui::Ui_TaskThicknessParameters::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/PartDesign/Gui/ui_TaskThicknessParameters.h