FreeCAD: MeshPartGui::CurveOnMeshWidget Class Reference
MeshPartGui::CurveOnMeshWidget Class Reference
#include <TaskCurveOnMesh.h>
Public Member Functions
CurveOnMeshWidget (Gui::View3DInventor *view, QWidget *parent=nullptr)
void reject ()
~CurveOnMeshWidget ()
Protected Member Functions
void changeEvent (QEvent *e)
void setup ()
Constructor & Destructor Documentation
CurveOnMeshWidget()
CurveOnMeshWidget::CurveOnMeshWidget (Gui::View3DInventor * view, QWidget * parent = nullptr)
References setup(), and MeshPartGui::Ui_TaskCurveOnMesh::setupUi().
~CurveOnMeshWidget()
CurveOnMeshWidget::~CurveOnMeshWidget ()
Member Function Documentation
changeEvent()
void CurveOnMeshWidget::changeEvent (QEvent * e) protected
References MeshPartGui::Ui_TaskCurveOnMesh::retranslateUi().
reject()
void CurveOnMeshWidget::reject (void)
References MeshPartGui::CurveOnMeshHandler::recomputeDocument().
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), MeshPartGui::TaskCurveOnMesh::reject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
setup()
void CurveOnMeshWidget::setup () protected
References MeshPartGui::Ui_TaskCurveOnMesh::continuity, MeshPartGui::Ui_TaskCurveOnMesh::maxDegree, and MeshPartGui::Ui_TaskCurveOnMesh::meshTolerance.
Referenced by CurveOnMeshWidget(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::doExecute(), PathScripts.PathDressupDogbone.ObjectDressup::execute(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::generateTags(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::pointAtBottom(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::pointIsOnPath(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::setXyEnabled(), and PathScripts.PathDressupHoldingTags.ObjectTagDressup::supportsTagGeneration().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/MeshPart/Gui/TaskCurveOnMesh.h
FreeCAD/src/Mod/MeshPart/Gui/TaskCurveOnMesh.cpp