FreeCAD: PartDesignGui::TaskPolarPatternParameters Class Reference
PartDesignGui::TaskPolarPatternParameters Class Reference
#include <TaskPolarPatternParameters.h>
Public Member Functions
void apply ()
TaskPolarPatternParameters (TaskMultiTransformParameters *parentTask, QLayout *layout)
Constructor for task with parent task (MultiTransform mode)
TaskPolarPatternParameters (ViewProviderTransformed *TransformedView, QWidget *parent=0)
Constructor for task with ViewProvider.
virtual ~TaskPolarPatternParameters ()
Public Member Functions inherited from PartDesignGui::TaskTransformedParameters
void exitSelectionMode ()
App::DocumentObject * getBaseObject () const
Get the TransformedFeature object associated with this task.
const std::vector< App::DocumentObject * > & getOriginals (void) const
Returns the originals property of associated top feeature object.
App::DocumentObject * getSketchObject () const
Get the sketch object of the first original either of the object associated with this feature or with the parent feature (MultiTransform mode)
int getTransactionID () const
void setupTransaction ()
TaskTransformedParameters (TaskMultiTransformParameters *parentTask)
Constructor for task with parent task (MultiTransform mode)
TaskTransformedParameters (ViewProviderTransformed *TransformedView, QWidget *parent=0)
Constructor for task with ViewProvider.
virtual ~TaskTransformedParameters ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (QWidget *parent=0)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (QWidget *parent=0)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockConnection (bool block)
void detachSelection ()
Detaches from the selection.
bool isConnectionAttached () const
bool isConnectionBlocked () const
SelectionObserver (bool attach=true, int resolve=1)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, int resolve=1)
Constructor.
virtual ~SelectionObserver ()
Public Member Functions inherited from Gui::DocumentObserver
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
virtual ~DocumentObserver ()
Protected Member Functions
virtual void addObject (App::DocumentObject *)
virtual void changeEvent (QEvent *e)
virtual void clearButtons ()
double getAngle (void) const
void getAxis (App::DocumentObject *&obj, std::vector< std::string > &sub) const
const std::string getAxis (void) const
unsigned getOccurrences (void) const
bool getReverse (void) const
const std::string getStdAxis (void) const
virtual void onSelectionChanged (const Gui::SelectionChanges &msg)
virtual void removeObject (App::DocumentObject *)
Protected Member Functions inherited from PartDesignGui::TaskTransformedParameters
void addReferenceSelectionGate (bool edge, bool face, bool planar=true, bool whole=false)
void checkVisibility ()
void fillAxisCombo (ComboLinks &combolinks, Part::Part2DObject *sketch)
void fillPlanesCombo (ComboLinks &combolinks, Part::Part2DObject *sketch)
PartDesign::Transformed * getObject () const
Returns the base transformation For stand alone features it will be objects associated with the view provider For features inside multitransform it will be the parent's multitransform object.
int getUpdateViewTimeout () const
void hideBase ()
void hideObject ()
bool isViewUpdated () const
bool originalSelected (const Gui::SelectionChanges &msg)
void recomputeFeature ()
Recompute either this feature or the parent feature (MultiTransform mode)
void showBase ()
void showObject ()
virtual void slotDeletedObject (const Gui::ViewProviderDocumentObject &Obj)
Notifies when the object is about to be removed.
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Types inherited from PartDesignGui::TaskTransformedParameters
enum selectionModes { none , addFeature , removeFeature , reference }
Protected Slots inherited from PartDesignGui::TaskTransformedParameters
PartDesign::Transformed * getTopTransformedObject () const
Returns the base transformed object For stand alone features it will be objects associated with this object For features inside multitransform it will be the base multitransform object.
PartDesignGui::ViewProviderTransformed * getTopTransformedView () const
Returns the base transformation view provider For stand alone features it will be view provider associated with this object For features inside multitransform it will be the view provider of the multitransform object.
void indexesMoved ()
void onButtonAddFeature (const bool checked)
void onButtonRemoveFeature (const bool checked)
virtual void onFeatureDeleted (void)=0
virtual void onSubTaskButtonOK ()
Connect the subTask OK button to the MultiTransform task.
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Static Protected Member Functions inherited from PartDesignGui::TaskTransformedParameters
static void removeItemFromListWidget (QListWidget *widget, const QString &itemstr)
Protected Attributes inherited from PartDesignGui::TaskTransformedParameters
bool blockUpdate
Lock updateUI(), applying changes to the underlying feature and calling recomputeFeature()
bool insideMultiTransform
Flag indicating whether this object is a container for MultiTransform.
TaskMultiTransformParameters * parentTask
The MultiTransform parent task of this task.
QWidget * proxy
selectionModes selectionMode
int transactionID = 0
ViewProviderTransformed * TransformedView
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskPolarPatternParameters() [1/2]
TaskPolarPatternParameters::TaskPolarPatternParameters (ViewProviderTransformed * TransformedView, QWidget * parent = 0)
Constructor for task with ViewProvider.
References PartDesignGui::TaskTransformedParameters::blockUpdate, QSint::ActionGroup::groupLayout(), PartDesignGui::TaskTransformedParameters::none, PartDesignGui::TaskTransformedParameters::proxy, and PartDesignGui::TaskTransformedParameters::selectionMode.
TaskPolarPatternParameters() [2/2]
TaskPolarPatternParameters::TaskPolarPatternParameters (TaskMultiTransformParameters * parentTask, QLayout * layout)
Constructor for task with parent task (MultiTransform mode)
References PartDesignGui::TaskTransformedParameters::blockUpdate, draftgeoutils.intersections::connect(), PartDesignGui::TaskTransformedParameters::none, PartDesignGui::TaskTransformedParameters::onSubTaskButtonOK(), PartDesignGui::TaskTransformedParameters::parentTask, PartDesignGui::TaskTransformedParameters::proxy, and PartDesignGui::TaskTransformedParameters::selectionMode.
~TaskPolarPatternParameters()
TaskPolarPatternParameters::~TaskPolarPatternParameters () virtual
References Base::Console(), Base::ConsoleSingleton::Error(), PartDesign::Body::findBodyOf(), PartDesignGui::TaskTransformedParameters::getObject(), App::OriginGroupExtension::getOrigin(), Gui::Application::getViewProvider(), Gui::Application::Instance, PartDesignGui::TaskTransformedParameters::proxy, Gui::ViewProviderOrigin::resetTemporaryVisibility(), and Base::Exception::what().
Member Function Documentation
addObject()
void TaskPolarPatternParameters::addObject (App::DocumentObject * obj) protected virtual
Reimplemented from PartDesignGui::TaskTransformedParameters.
Referenced by ArchPanel.NestTaskPanel::getContainer(), and ArchPanel.NestTaskPanel::getShapes().
apply()
void TaskPolarPatternParameters::apply (void) virtual
Implements PartDesignGui::TaskTransformedParameters.
References PartDesignGui::buildLinkSingleSubPythonStr(), getAxis(), Gui::ViewProviderDocumentObject::getObject(), getReverse(), and PartDesignGui::TaskTransformedParameters::TransformedView.
changeEvent()
void TaskPolarPatternParameters::changeEvent (QEvent * e) protected virtual
Implements PartDesignGui::TaskTransformedParameters.
References PartDesignGui::TaskTransformedParameters::proxy.
clearButtons()
void TaskPolarPatternParameters::clearButtons () protected virtual
Implements PartDesignGui::TaskTransformedParameters.
getAngle()
double TaskPolarPatternParameters::getAngle (void) const protected
Referenced by PathScripts.PathDressupDogbone.Chord::getAngleXY(), draftguitools.gui_trackers.arcTracker::setEndPoint(), and draftguitools.gui_trackers.arcTracker::setStartPoint().
getAxis() [1/2]
void TaskPolarPatternParameters::getAxis (App::DocumentObject *& obj, std::vector< std::string > & sub) const protected
References PartDesignGui::ComboLinks::getCurrentLink(), App::PropertyLinkSub::getSubValues(), and App::PropertyLinkSub::getValue().
getAxis() [2/2]
const std::string PartDesignGui::TaskPolarPatternParameters::getAxis (void) const protected
Referenced by apply().
getOccurrences()
unsigned TaskPolarPatternParameters::getOccurrences (void) const protected
getReverse()
bool TaskPolarPatternParameters::getReverse (void) const protected
Referenced by apply().
getStdAxis()
const std::string PartDesignGui::TaskPolarPatternParameters::getStdAxis (void) const protected
onSelectionChanged()
void TaskPolarPatternParameters::onSelectionChanged (const Gui::SelectionChanges & msg) protected virtual
Implements PartDesignGui::TaskTransformedParameters.
References Gui::SelectionChanges::AddSelection, PartDesign::PolarPattern::Axis, PartDesignGui::TaskTransformedParameters::exitSelectionMode(), Base::Persistence::getClassTypeId(), PartDesignGui::TaskTransformedParameters::getObject(), PartDesignGui::getReferencedSelection(), Base::BaseClass::isDerivedFrom(), PartDesignGui::TaskTransformedParameters::none, PartDesignGui::TaskTransformedParameters::originalSelected(), PartDesignGui::TaskTransformedParameters::recomputeFeature(), PartDesignGui::TaskTransformedParameters::reference, PartDesignGui::TaskTransformedParameters::selectionMode, PartDesignGui::TaskTransformedParameters::setupTransaction(), and App::PropertyLinkSub::setValue().
removeObject()
void TaskPolarPatternParameters::removeObject (App::DocumentObject * obj) protected virtual
Reimplemented from PartDesignGui::TaskTransformedParameters.
References PartDesignGui::TaskTransformedParameters::removeItemFromListWidget().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/PartDesign/Gui/TaskPolarPatternParameters.h
Sources/FreeCAD/src/Mod/PartDesign/Gui/TaskPolarPatternParameters.cpp