FreeCAD: exportIFCHelper Namespace Reference
exportIFCHelper Namespace Reference
Classes
class ContextCreator
class recycler
class SIUnitCreator
Functions
def getObjectsOfIfcType (objects, ifcType)
def writeUnits (ifcfile, unit="metre")
Function Documentation
getObjectsOfIfcType()
def exportIFCHelper.getObjectsOfIfcType (objects, ifcType)
Referenced by exportIFC.export(), and exportIFCHelper.ContextCreator.getProjectObject().
writeUnits()
def exportIFCHelper.writeUnits (ifcfile, unit = "metre")
adds additional units settings to the given ifc file if needed
Referenced by exportIFC.export().