FreeCAD: PathTests.TestPathLog.TestPathLog Class Reference
PathTests.TestPathLog.TestPathLog Class Reference
Public Member Functions
def callerFile (self)
def callerFunc (self)
def callerLine (self)
def setUp (self)
def test00 (self)
def test01 (self)
def test10 (self)
def test11 (self)
def test12 (self)
def test13 (self)
def test14 (self)
def test20 (self)
def test21 (self)
def test30 (self)
def test31 (self)
def test32 (self)
def test33 (self)
def test34 (self)
def test50 (self)
def test51 (self)
def test52 (self)
def test53 (self)
def test60 (self)
def test61 (self)
def testzz (self)
Static Public Attributes
string MODULE = 'TestPathLog'
Detailed Description
Some basic tests for the logging framework.
Member Function Documentation
callerFile()
def PathTests.TestPathLog.TestPathLog.callerFile (self)
Referenced by PathTests.TestPathLog.TestPathLog.test00().
callerFunc()
def PathTests.TestPathLog.TestPathLog.callerFunc (self)
Referenced by PathTests.TestPathLog.TestPathLog.test01().
callerLine()
def PathTests.TestPathLog.TestPathLog.callerLine (self)
setUp()
def PathTests.TestPathLog.TestPathLog.setUp (self)
test00()
def PathTests.TestPathLog.TestPathLog.test00 (self)
Check for proper module extraction.
References PathTests.TestPathLog.TestPathLog.callerFile(), and PathTests.TestPathLog.TestPathLog.MODULE.
Referenced by PathTests.TestPathTool.TestPathTool.test01(), PathTests.TestPathToolController.TestPathToolController.test01(), PathTests.TestPathTooltable.TestPathTooltable.test01(), PathTests.TestPathTool.TestPathTool.test02(), and PathTests.TestPathTooltable.TestPathTooltable.test02().
test01()
def PathTests.TestPathLog.TestPathLog.test01 (self)
Check for proper function extraction.
References PathTests.TestPathLog.TestPathLog.callerFunc().
test10()
def PathTests.TestPathLog.TestPathLog.test10 (self)
Verify default log levels is NOTICE.
References PathTests.TestPathLog.TestPathLog.MODULE.
test11()
def PathTests.TestPathLog.TestPathLog.test11 (self)
Verify setting global log level.
References PathTests.TestPathLog.TestPathLog.MODULE.
test12()
def PathTests.TestPathLog.TestPathLog.test12 (self)
Verify setting module log level.
References PathTests.TestPathLog.TestPathLog.MODULE.
test13()
def PathTests.TestPathLog.TestPathLog.test13 (self)
Verify setting other modul's log level doesn't change this one's.
References PathTests.TestPathLog.TestPathLog.MODULE.
test14()
def PathTests.TestPathLog.TestPathLog.test14 (self)
Verify resetting log level for module falls back to global level.
References PathTests.TestPathLog.TestPathLog.MODULE.
test20()
def PathTests.TestPathLog.TestPathLog.test20 (self)
Verify debug logs aren't logged by default.
test21()
def PathTests.TestPathLog.TestPathLog.test21 (self)
Verify debug logs are logged if log level is set to DEBUG.
test30()
def PathTests.TestPathLog.TestPathLog.test30 (self)
Verify log level ERROR.
test31()
def PathTests.TestPathLog.TestPathLog.test31 (self)
Verify log level WARNING.
test32()
def PathTests.TestPathLog.TestPathLog.test32 (self)
Verify log level NOTICE.
test33()
def PathTests.TestPathLog.TestPathLog.test33 (self)
Verify log level INFO.
test34()
def PathTests.TestPathLog.TestPathLog.test34 (self)
Verify log level DEBUG.
test50()
def PathTests.TestPathLog.TestPathLog.test50 (self)
Verify no tracking by default.
test51()
def PathTests.TestPathLog.TestPathLog.test51 (self)
Verify enabling tracking for module results in tracking.
References PathTests.TestPathLog.TestPathLog.MODULE.
test52()
def PathTests.TestPathLog.TestPathLog.test52 (self)
Verify untracking stops tracking.
test53()
def PathTests.TestPathLog.TestPathLog.test53 (self)
Verify trackAllModules works correctly.
test60()
def PathTests.TestPathLog.TestPathLog.test60 (self)
Verify track handles no argument.
References PathTests.TestPathLog.TestPathLog.MODULE.
test61()
def PathTests.TestPathLog.TestPathLog.test61 (self)
Verify track handles arbitrary argument types correctly.
References PathTests.TestPathLog.TestPathLog.MODULE.
testzz()
def PathTests.TestPathLog.TestPathLog.testzz (self)
Restoring environment after tests.
Member Data Documentation
MODULE
string PathTests.TestPathLog.TestPathLog.MODULE = 'TestPathLog' static
Referenced by PathTests.TestPathLog.TestPathLog.test00(), PathTests.TestPathLog.TestPathLog.test10(), PathTests.TestPathLog.TestPathLog.test11(), PathTests.TestPathLog.TestPathLog.test12(), PathTests.TestPathLog.TestPathLog.test13(), PathTests.TestPathLog.TestPathLog.test14(), PathTests.TestPathLog.TestPathLog.test51(), PathTests.TestPathLog.TestPathLog.test60(), and PathTests.TestPathLog.TestPathLog.test61().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Path/PathTests/TestPathLog.py