FreeCAD: SketcherGui::DrawSketchHandlerBSpline Class Reference
SketcherGui::DrawSketchHandlerBSpline Class Reference
#include <DrawSketchHandlerBSpline.h>
Public Types
enum MOUSE_PRESS_MODE { MOUSE_PRESSED , MOUSE_NOT_PRESSED }
enum SELECT_MODE { STATUS_SEEK_FIRST_CONTROLPOINT , STATUS_SEEK_ADDITIONAL_CONTROLPOINTS , STATUS_CLOSE }
modes
Public Member Functions
DrawSketchHandlerBSpline (int constructionMethod)
virtual void mouseMove (Base::Vector2d onSketchPos) override
virtual bool pressButton (Base::Vector2d onSketchPos) override
virtual void quit (void) override
virtual void registerPressedKey (bool pressed, int key) override
virtual bool releaseButton (Base::Vector2d onSketchPos) override
virtual ~DrawSketchHandlerBSpline ()=default
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void activate (ViewProviderSketch *)
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::PointPos::none, bool createowncommand=true)
void deactivate ()
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual void mouseMove (Base::Vector2d onSketchPos)=0
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual bool pressButton (Base::Vector2d onSketchPos)=0
virtual void quit (void)
virtual void registerPressedKey (bool, int)
virtual bool releaseButton (Base::Vector2d onSketchPos)=0
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Attributes
std::vector< Base::Vector2d > BSplinePoles
int ConstrMethod
bool IsClosed
SELECT_MODE Mode
MOUSE_PRESS_MODE MousePressMode
std::vector< int > poleGeoIds
Base::Vector2d prevCursorPosition
int SplineDegree
std::vector< std::vector< AutoConstraint > > sugConstr
Protected Attributes inherited from SketcherGui::DrawSketchHandler
ViewProviderSketch * sketchgui
QCursor oldCursor
QCursor actCursor
QPixmap actCursorPixmap
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
virtual QString getCrosshairCursorSVGName () const
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
void updateCursor ()
updates the actCursor with the icon by calling getCrosshairCursorSVGName(), enabling to set data member dependent icons (i.e.
void unsetCursor (void)
restitutes the cursor that was in use at the moment of starting the DrawSketchHandler (i.e. oldCursor)
void applyCursor (void)
restitutes the DSH cached cursor (e.g. without any tail due to autoconstraints, ...)
unsigned long getCrosshairColor ()
returns the color to be used for the crosshair (configurable as a parameter)
qreal devicePixelRatio ()
functions to set the cursor to a given svgName (to be migrated to NVI style)
void drawEdit (const std::vector< Base::Vector2d > &EditCurve)
void drawEdit (const std::list< std::vector< Base::Vector2d > > &list)
void drawEdit (const std::vector< Part::Geometry * > &geometries)
void drawEditMarkers (const std::vector< Base::Vector2d > &EditMarkers, unsigned int augmentationlevel=0)
void setAxisPickStyle (bool on)
void moveCursorToSketchPoint (Base::Vector2d point)
void preselectAtPoint (Base::Vector2d point)
void drawPositionAtCursor (const Base::Vector2d &position)
void drawDirectionAtCursor (const Base::Vector2d &position, const Base::Vector2d &origin)
int getPreselectPoint (void) const
int getPreselectCurve (void) const
int getPreselectCross (void) const
Sketcher::SketchObject * getSketchObject ()
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
Member Enumeration Documentation
MOUSE_PRESS_MODE
enum SketcherGui::DrawSketchHandlerBSpline::MOUSE_PRESS_MODE
Enumerator
MOUSE_PRESSED
MOUSE_NOT_PRESSED
SELECT_MODE
enum SketcherGui::DrawSketchHandlerBSpline::SELECT_MODE
modes
Enumerator
STATUS_SEEK_FIRST_CONTROLPOINT
STATUS_SEEK_ADDITIONAL_CONTROLPOINTS
STATUS_CLOSE
Constructor & Destructor Documentation
DrawSketchHandlerBSpline()
SketcherGui::DrawSketchHandlerBSpline::DrawSketchHandlerBSpline (int constructionMethod)
References SketcherGui::DrawSketchHandler::applyCursor().
~DrawSketchHandlerBSpline()
virtual SketcherGui::DrawSketchHandlerBSpline::~DrawSketchHandlerBSpline () virtual default
Member Function Documentation
mouseMove()
virtual void SketcherGui::DrawSketchHandlerBSpline::mouseMove (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
References Mode, prevCursorPosition, SketcherGui::DrawSketchHandler::renderSuggestConstraintsCursor(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), SketcherGui::DrawSketchHandler::setPositionText(), STATUS_SEEK_ADDITIONAL_CONTROLPOINTS, STATUS_SEEK_FIRST_CONTROLPOINT, and sugConstr.
pressButton()
virtual bool SketcherGui::DrawSketchHandlerBSpline::pressButton (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), BSplinePoles, Gui::cmdAppObjectArgs(), Sketcher::Coincident, Base::Console(), ConstrMethod, SketcherGui::DrawSketchHandler::createAutoConstraints(), Base::ConsoleSingleton::Error(), SketcherGui::DrawSketchHandler::getHighestCurveIndex(), Gui::ViewProviderDocumentObject::getObject(), IsClosed, Sketcher::mid, Mode, MOUSE_PRESSED, MousePressMode, Gui::Command::openCommand(), poleGeoIds, prevCursorPosition, draftutils.translate::QT_TRANSLATE_NOOP, SketcherGui::DrawSketchHandler::sketchgui, STATUS_CLOSE, STATUS_SEEK_ADDITIONAL_CONTROLPOINTS, STATUS_SEEK_FIRST_CONTROLPOINT, and sugConstr.
quit()
virtual void SketcherGui::DrawSketchHandlerBSpline::quit (void) override virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), App::GetApplication(), ParameterGrp::GetBool(), Gui::ViewProviderDocumentObject::getObject(), App::Application::GetParameterGroupByPath(), Mode, poleGeoIds, SketcherGui::DrawSketchHandler::quit(), SketcherGui::DrawSketchHandler::sketchgui, STATUS_CLOSE, and SketcherGui::tryAutoRecomputeIfNotSolve().
Referenced by registerPressedKey().
registerPressedKey()
virtual void SketcherGui::DrawSketchHandlerBSpline::registerPressedKey (bool pressed, int key) override virtual
Reimplemented from SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), BSplinePoles, Gui::cmdAppObjectArgs(), Base::Console(), Base::ConsoleSingleton::Error(), Gui::getMainWindow(), Gui::ViewProviderDocumentObject::getObject(), Mode, MOUSE_PRESSED, MousePressMode, poleGeoIds, prevCursorPosition, quit(), SketcherGui::DrawSketchHandler::sketchgui, SplineDegree, STATUS_CLOSE, STATUS_SEEK_FIRST_CONTROLPOINT, and sugConstr.
releaseButton()
virtual bool SketcherGui::DrawSketchHandlerBSpline::releaseButton (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
References MOUSE_NOT_PRESSED, MousePressMode, and prevCursorPosition.
Member Data Documentation
BSplinePoles
std::vector<Base::Vector2d> SketcherGui::DrawSketchHandlerBSpline::BSplinePoles protected
Referenced by pressButton(), and registerPressedKey().
ConstrMethod
int SketcherGui::DrawSketchHandlerBSpline::ConstrMethod protected
Referenced by pressButton().
IsClosed
bool SketcherGui::DrawSketchHandlerBSpline::IsClosed protected
Referenced by pressButton().
Mode
SELECT_MODE SketcherGui::DrawSketchHandlerBSpline::Mode protected
Referenced by mouseMove(), pressButton(), quit(), and registerPressedKey().
MousePressMode
MOUSE_PRESS_MODE SketcherGui::DrawSketchHandlerBSpline::MousePressMode protected
Referenced by pressButton(), registerPressedKey(), and releaseButton().
poleGeoIds
std::vector<int> SketcherGui::DrawSketchHandlerBSpline::poleGeoIds protected
Referenced by pressButton(), quit(), and registerPressedKey().
prevCursorPosition
Base::Vector2d SketcherGui::DrawSketchHandlerBSpline::prevCursorPosition protected
Referenced by mouseMove(), pressButton(), registerPressedKey(), and releaseButton().
SplineDegree
int SketcherGui::DrawSketchHandlerBSpline::SplineDegree protected
Referenced by registerPressedKey().
sugConstr
std::vector<std::vector<AutoConstraint> > SketcherGui::DrawSketchHandlerBSpline::sugConstr protected
Referenced by mouseMove(), pressButton(), and registerPressedKey().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/DrawSketchHandlerBSpline.h