FreeCAD: ImageGui::ImageOrientationDialog Class Reference
ImageGui::ImageOrientationDialog Class Reference
#include <ImageOrientationDialog.h>
Public Member Functions
void accept ()
ImageOrientationDialog ()
~ImageOrientationDialog ()
Public Attributes
int DirType
Base::Placement Pos
Protected Slots
void onPreview ()
Constructor & Destructor Documentation
ImageOrientationDialog()
ImageOrientationDialog::ImageOrientationDialog ()
References draftgeoutils.intersections::connect(), DirType, onPreview(), ImageGui::Ui_ImageOrientationDialog::Reverse_checkBox, ImageGui::Ui_ImageOrientationDialog::setupUi(), ImageGui::Ui_ImageOrientationDialog::XY_radioButton, ImageGui::Ui_ImageOrientationDialog::XZ_radioButton, and ImageGui::Ui_ImageOrientationDialog::YZ_radioButton.
~ImageOrientationDialog()
ImageOrientationDialog::~ImageOrientationDialog ()
Member Function Documentation
accept()
void ImageOrientationDialog::accept (void)
References DirType, Base::Quantity::getValue(), ImageGui::Ui_ImageOrientationDialog::Offset_doubleSpinBox, Pos, ImageGui::Ui_ImageOrientationDialog::Reverse_checkBox, Gui::QuantitySpinBox::value, ImageGui::Ui_ImageOrientationDialog::XY_radioButton, ImageGui::Ui_ImageOrientationDialog::XZ_radioButton, and ImageGui::Ui_ImageOrientationDialog::YZ_radioButton.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
onPreview
void ImageOrientationDialog::onPreview () protected slot
References Gui::BitmapFactory(), ImageGui::Ui_ImageOrientationDialog::previewLabel, ImageGui::Ui_ImageOrientationDialog::Reverse_checkBox, ImageGui::Ui_ImageOrientationDialog::XY_radioButton, ImageGui::Ui_ImageOrientationDialog::XZ_radioButton, and ImageGui::Ui_ImageOrientationDialog::YZ_radioButton.
Referenced by ImageOrientationDialog().
Member Data Documentation
DirType
int ImageGui::ImageOrientationDialog::DirType
Referenced by accept(), and ImageOrientationDialog().
Pos
Base::Placement ImageGui::ImageOrientationDialog::Pos
Referenced by accept().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Image/Gui/ImageOrientationDialog.h
FreeCAD/src/Mod/Image/Gui/ImageOrientationDialog.cpp