FreeCAD: Base::Polygon2d Class Reference
Base::Polygon2d Class Reference
Polygon2d.
#include <Tools2D.h>
Public Member Functions
bool Add (const Vector2d &rclVct)
Vector2d & At (size_t ulNdx)
const Vector2d & At (size_t ulNdx) const
BoundBox2d CalcBoundBox () const
POLYGON2d.
bool Contains (const Vector2d &rclV) const
bool Delete (size_t ulNdx)
void DeleteAll ()
size_t GetCtVectors () const
bool Intersect (const Polygon2d &rclPolygon) const
void Intersect (const Polygon2d &rclPolygon, std::list< Polygon2d > &rclResultPolygonList) const
bool Intersect (const Vector2d &rclV, double eps) const
Polygon2d & operator= (const Polygon2d &rclP)
Vector2d & operator[] (size_t ulNdx)
const Vector2d & operator[] (size_t ulNdx) const
Polygon2d ()
Polygon2d (const Polygon2d &rclPoly)
virtual ~Polygon2d ()
Detailed Description
Polygon2d.
2D polygon class.
Constructor & Destructor Documentation
Polygon2d() [1/2]
Base::Polygon2d::Polygon2d ()
Polygon2d() [2/2]
Base::Polygon2d::Polygon2d (const Polygon2d & rclPoly)
~Polygon2d()
virtual Base::Polygon2d::~Polygon2d () virtual
Member Function Documentation
Add()
bool Base::Polygon2d::Add (const Vector2d & rclVct)
Referenced by PointsGui::ViewProviderScattered::cut(), PointsGui::ViewProviderStructured::cut(), Intersect(), and MeshGui::ViewProviderMesh::trimMesh().
At() [1/2]
Vector2d & Base::Polygon2d::At (size_t ulNdx)
At() [2/2]
const Vector2d & Base::Polygon2d::At (size_t ulNdx) const
Referenced by Intersect().
CalcBoundBox()
BoundBox2d Polygon2d::CalcBoundBox () const
POLYGON2d.
References Base::BoundBox2d::MaxX, Base::BoundBox2d::MaxY, Base::BoundBox2d::MinX, and Base::BoundBox2d::MinY.
Referenced by MeshCore::MeshAlgorithm::CheckFacets(), and MeshCore::MeshTrimming::CheckFacets().
Contains()
bool Polygon2d::Contains (const Vector2d & rclV) const
References GetCtVectors(), Base::Vector2d::x, and Base::Vector2d::y.
Referenced by MeshCore::MeshAlgorithm::CheckFacets(), PointsGui::ViewProviderScattered::cut(), PointsGui::ViewProviderStructured::cut(), Base::BoundBox2d::Intersect(), and Intersect().
Delete()
bool Base::Polygon2d::Delete (size_t ulNdx)
DeleteAll()
void Base::Polygon2d::DeleteAll ()
Referenced by Intersect().
GetCtVectors()
size_t Base::Polygon2d::GetCtVectors () const
Referenced by Contains(), Base::BoundBox2d::Intersect(), and Intersect().
Intersect() [1/3]
bool Polygon2d::Intersect (const Polygon2d & rclPolygon) const
References At(), Contains(), GetCtVectors(), and Base::Line2d::IntersectAndContain().
Intersect() [2/3]
void Polygon2d::Intersect (const Polygon2d & rclPolygon, std::list< Polygon2d > & rclResultPolygonList) const
References Add(), At(), Contains(), DeleteAll(), Base::Line2d::FromPos(), GetCtVectors(), and Base::Line2d::IntersectAndContain().
Intersect() [3/3]
bool Polygon2d::Intersect (const Vector2d & rclV, double eps) const
References GetCtVectors().
operator=()
Polygon2d & Base::Polygon2d::operator= (const Polygon2d & rclP)
operator[]() [1/2]
Vector2d & Base::Polygon2d::operator[] (size_t ulNdx)
operator[]() [2/2]
const Vector2d & Base::Polygon2d::operator[] (size_t ulNdx) const
The documentation for this class was generated from the following files:
FreeCAD/src/Base/Tools2D.h
FreeCAD/src/Base/Tools2D.cpp