FreeCAD: Fem::FemMeshPy Class Reference
Fem::FemMeshPy Class Reference
The python export class for FemMesh.
#include <FemMeshPy.h>
Public Types
typedef FemMesh * PointerType
Public Types inherited from Data::ComplexGeoDataPy
typedef ComplexGeoData * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
FemMeshPy (FemMesh *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Data::ComplexGeoDataPy
ComplexGeoDataPy (ComplexGeoData *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getFacesFromSubelement (PyObject *args)
implementer for the getFacesFromSubelement() method
Py::Object getBoundBox (void) const
getter for the BoundBox attribute
Py::Object getPlacement (void) const
getter for the Placement attribute
void setPlacement (Py::Object arg)
setter for the Placement attribute
Py::Object getMatrix (void) const
getter for the Matrix attribute
void setMatrix (Py::Object arg)
setter for the Matrix attribute
Py::Int getTag (void) const
getter for the Tag attribute
void setTag (Py::Int arg)
setter for the Tag attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ComplexGeoData * getComplexGeoDataPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Data::ComplexGeoDataPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_getFacesFromSubelement (PyObject *self, PyObject *args)
callback for the getFacesFromSubelement() method
static PyObject * staticCallback_getBoundBox (PyObject *self, void *closure)
getter callback for the BoundBox attribute
static int staticCallback_setBoundBox (PyObject *self, PyObject *value, void *closure)
setter callback for the BoundBox attribute
static PyObject * staticCallback_getPlacement (PyObject *self, void *closure)
getter callback for the Placement attribute
static int staticCallback_setPlacement (PyObject *self, PyObject *value, void *closure)
setter callback for the Placement attribute
static PyObject * staticCallback_getMatrix (PyObject *self, void *closure)
getter callback for the Matrix attribute
static int staticCallback_setMatrix (PyObject *self, PyObject *value, void *closure)
setter callback for the Matrix attribute
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of FemMeshPy.
static PyMethodDef Methods []
Methods structure of FemMeshPy.
static PyTypeObject Type
Type structure of FemMeshPy.
Static Public Attributes inherited from Data::ComplexGeoDataPy
static PyGetSetDef GetterSetter []
Attribute structure of ComplexGeoDataPy.
static PyMethodDef Methods []
Methods structure of ComplexGeoDataPy.
static PyTypeObject Type
Type structure of ComplexGeoDataPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~FemMeshPy ()
Protected Member Functions inherited from Data::ComplexGeoDataPy
~ComplexGeoDataPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * setShape (PyObject *args)
implementer for the setShape() method
PyObject * compute (PyObject *args)
implementer for the compute() method
PyObject * addHypothesis (PyObject *args)
implementer for the addHypothesis() method
PyObject * setStandardHypotheses (PyObject *args)
implementer for the setStandardHypotheses() method
PyObject * addNode (PyObject *args)
implementer for the addNode() method
PyObject * addEdge (PyObject *args)
implementer for the addEdge() method
PyObject * addFace (PyObject *args)
implementer for the addFace() method
PyObject * addQuad (PyObject *args)
implementer for the addQuad() method
PyObject * addVolume (PyObject *args)
implementer for the addVolume() method
PyObject * read (PyObject *args)
implementer for the read() method
PyObject * write (PyObject *args)
implementer for the write() method
PyObject * writeABAQUS (PyObject *args)
implementer for the writeABAQUS() method
PyObject * setTransform (PyObject *args)
implementer for the setTransform() method
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * getFacesByFace (PyObject *args)
implementer for the getFacesByFace() method
PyObject * getEdgesByEdge (PyObject *args)
implementer for the getEdgesByEdge() method
PyObject * getVolumesByFace (PyObject *args)
implementer for the getVolumesByFace() method
PyObject * getccxVolumesByFace (PyObject *args)
implementer for the getccxVolumesByFace() method
PyObject * getNodeById (PyObject *args)
implementer for the getNodeById() method
PyObject * getNodesBySolid (PyObject *args)
implementer for the getNodesBySolid() method
PyObject * getNodesByFace (PyObject *args)
implementer for the getNodesByFace() method
PyObject * getNodesByEdge (PyObject *args)
implementer for the getNodesByEdge() method
PyObject * getNodesByVertex (PyObject *args)
implementer for the getNodesByVertex() method
PyObject * getElementNodes (PyObject *args)
implementer for the getElementNodes() method
PyObject * getGroupName (PyObject *args)
implementer for the getGroupName() method
PyObject * getGroupElementType (PyObject *args)
implementer for the getGroupElementType() method
PyObject * getGroupElements (PyObject *args)
implementer for the getGroupElements() method
PyObject * addGroup (PyObject *args)
implementer for the addGroup() method
PyObject * addGroupElements (PyObject *args)
implementer for the addGroupElements() method
PyObject * removeGroup (PyObject *args)
implementer for the removeGroup() method
PyObject * getElementType (PyObject *args)
implementer for the getElementType() method
PyObject * getIdByElementType (PyObject *args)
implementer for the getIdByElementType() method
static PyObject * staticCallback_setShape (PyObject *self, PyObject *args)
callback for the setShape() method
static PyObject * staticCallback_compute (PyObject *self, PyObject *args)
callback for the compute() method
static PyObject * staticCallback_addHypothesis (PyObject *self, PyObject *args)
callback for the addHypothesis() method
static PyObject * staticCallback_setStandardHypotheses (PyObject *self, PyObject *args)
callback for the setStandardHypotheses() method
static PyObject * staticCallback_addNode (PyObject *self, PyObject *args)
callback for the addNode() method
static PyObject * staticCallback_addEdge (PyObject *self, PyObject *args)
callback for the addEdge() method
static PyObject * staticCallback_addFace (PyObject *self, PyObject *args)
callback for the addFace() method
static PyObject * staticCallback_addQuad (PyObject *self, PyObject *args)
callback for the addQuad() method
static PyObject * staticCallback_addVolume (PyObject *self, PyObject *args)
callback for the addVolume() method
static PyObject * staticCallback_read (PyObject *self, PyObject *args)
callback for the read() method
static PyObject * staticCallback_write (PyObject *self, PyObject *args)
callback for the write() method
static PyObject * staticCallback_writeABAQUS (PyObject *self, PyObject *args)
callback for the writeABAQUS() method
static PyObject * staticCallback_setTransform (PyObject *self, PyObject *args)
callback for the setTransform() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_getFacesByFace (PyObject *self, PyObject *args)
callback for the getFacesByFace() method
static PyObject * staticCallback_getEdgesByEdge (PyObject *self, PyObject *args)
callback for the getEdgesByEdge() method
static PyObject * staticCallback_getVolumesByFace (PyObject *self, PyObject *args)
callback for the getVolumesByFace() method
static PyObject * staticCallback_getccxVolumesByFace (PyObject *self, PyObject *args)
callback for the getccxVolumesByFace() method
static PyObject * staticCallback_getNodeById (PyObject *self, PyObject *args)
callback for the getNodeById() method
static PyObject * staticCallback_getNodesBySolid (PyObject *self, PyObject *args)
callback for the getNodesBySolid() method
static PyObject * staticCallback_getNodesByFace (PyObject *self, PyObject *args)
callback for the getNodesByFace() method
static PyObject * staticCallback_getNodesByEdge (PyObject *self, PyObject *args)
callback for the getNodesByEdge() method
static PyObject * staticCallback_getNodesByVertex (PyObject *self, PyObject *args)
callback for the getNodesByVertex() method
static PyObject * staticCallback_getElementNodes (PyObject *self, PyObject *args)
callback for the getElementNodes() method
static PyObject * staticCallback_getGroupName (PyObject *self, PyObject *args)
callback for the getGroupName() method
static PyObject * staticCallback_getGroupElementType (PyObject *self, PyObject *args)
callback for the getGroupElementType() method
static PyObject * staticCallback_getGroupElements (PyObject *self, PyObject *args)
callback for the getGroupElements() method
static PyObject * staticCallback_addGroup (PyObject *self, PyObject *args)
callback for the addGroup() method
static PyObject * staticCallback_addGroupElements (PyObject *self, PyObject *args)
callback for the addGroupElements() method
static PyObject * staticCallback_removeGroup (PyObject *self, PyObject *args)
callback for the removeGroup() method
static PyObject * staticCallback_getElementType (PyObject *self, PyObject *args)
callback for the getElementType() method
static PyObject * staticCallback_getIdByElementType (PyObject *self, PyObject *args)
callback for the getIdByElementType() method
callbacks and implementers for the python object attributes
Py::Dict getNodes (void) const
getter for the Nodes attribute
Py::Long getNodeCount (void) const
getter for the NodeCount attribute
Py::Tuple getEdges (void) const
getter for the Edges attribute
Py::Tuple getEdgesOnly (void) const
getter for the EdgesOnly attribute
Py::Long getEdgeCount (void) const
getter for the EdgeCount attribute
Py::Tuple getFaces (void) const
getter for the Faces attribute
Py::Tuple getFacesOnly (void) const
getter for the FacesOnly attribute
Py::Long getFaceCount (void) const
getter for the FaceCount attribute
Py::Long getTriangleCount (void) const
getter for the TriangleCount attribute
Py::Long getQuadrangleCount (void) const
getter for the QuadrangleCount attribute
Py::Long getPolygonCount (void) const
getter for the PolygonCount attribute
Py::Tuple getVolumes (void) const
getter for the Volumes attribute
Py::Long getVolumeCount (void) const
getter for the VolumeCount attribute
Py::Long getTetraCount (void) const
getter for the TetraCount attribute
Py::Long getHexaCount (void) const
getter for the HexaCount attribute
Py::Long getPyramidCount (void) const
getter for the PyramidCount attribute
Py::Long getPrismCount (void) const
getter for the PrismCount attribute
Py::Long getPolyhedronCount (void) const
getter for the PolyhedronCount attribute
Py::Long getSubMeshCount (void) const
getter for the SubMeshCount attribute
Py::Long getGroupCount (void) const
getter for the GroupCount attribute
Py::Tuple getGroups (void) const
getter for the Groups attribute
Py::Object getVolume (void) const
getter for the Volume attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
FemMesh * getFemMeshPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getNodes (PyObject *self, void *closure)
getter callback for the Nodes attribute
static int staticCallback_setNodes (PyObject *self, PyObject *value, void *closure)
setter callback for the Nodes attribute
static PyObject * staticCallback_getNodeCount (PyObject *self, void *closure)
getter callback for the NodeCount attribute
static int staticCallback_setNodeCount (PyObject *self, PyObject *value, void *closure)
setter callback for the NodeCount attribute
static PyObject * staticCallback_getEdges (PyObject *self, void *closure)
getter callback for the Edges attribute
static int staticCallback_setEdges (PyObject *self, PyObject *value, void *closure)
setter callback for the Edges attribute
static PyObject * staticCallback_getEdgesOnly (PyObject *self, void *closure)
getter callback for the EdgesOnly attribute
static int staticCallback_setEdgesOnly (PyObject *self, PyObject *value, void *closure)
setter callback for the EdgesOnly attribute
static PyObject * staticCallback_getEdgeCount (PyObject *self, void *closure)
getter callback for the EdgeCount attribute
static int staticCallback_setEdgeCount (PyObject *self, PyObject *value, void *closure)
setter callback for the EdgeCount attribute
static PyObject * staticCallback_getFaces (PyObject *self, void *closure)
getter callback for the Faces attribute
static int staticCallback_setFaces (PyObject *self, PyObject *value, void *closure)
setter callback for the Faces attribute
static PyObject * staticCallback_getFacesOnly (PyObject *self, void *closure)
getter callback for the FacesOnly attribute
static int staticCallback_setFacesOnly (PyObject *self, PyObject *value, void *closure)
setter callback for the FacesOnly attribute
static PyObject * staticCallback_getFaceCount (PyObject *self, void *closure)
getter callback for the FaceCount attribute
static int staticCallback_setFaceCount (PyObject *self, PyObject *value, void *closure)
setter callback for the FaceCount attribute
static PyObject * staticCallback_getTriangleCount (PyObject *self, void *closure)
getter callback for the TriangleCount attribute
static int staticCallback_setTriangleCount (PyObject *self, PyObject *value, void *closure)
setter callback for the TriangleCount attribute
static PyObject * staticCallback_getQuadrangleCount (PyObject *self, void *closure)
getter callback for the QuadrangleCount attribute
static int staticCallback_setQuadrangleCount (PyObject *self, PyObject *value, void *closure)
setter callback for the QuadrangleCount attribute
static PyObject * staticCallback_getPolygonCount (PyObject *self, void *closure)
getter callback for the PolygonCount attribute
static int staticCallback_setPolygonCount (PyObject *self, PyObject *value, void *closure)
setter callback for the PolygonCount attribute
static PyObject * staticCallback_getVolumes (PyObject *self, void *closure)
getter callback for the Volumes attribute
static int staticCallback_setVolumes (PyObject *self, PyObject *value, void *closure)
setter callback for the Volumes attribute
static PyObject * staticCallback_getVolumeCount (PyObject *self, void *closure)
getter callback for the VolumeCount attribute
static int staticCallback_setVolumeCount (PyObject *self, PyObject *value, void *closure)
setter callback for the VolumeCount attribute
static PyObject * staticCallback_getTetraCount (PyObject *self, void *closure)
getter callback for the TetraCount attribute
static int staticCallback_setTetraCount (PyObject *self, PyObject *value, void *closure)
setter callback for the TetraCount attribute
static PyObject * staticCallback_getHexaCount (PyObject *self, void *closure)
getter callback for the HexaCount attribute
static int staticCallback_setHexaCount (PyObject *self, PyObject *value, void *closure)
setter callback for the HexaCount attribute
static PyObject * staticCallback_getPyramidCount (PyObject *self, void *closure)
getter callback for the PyramidCount attribute
static int staticCallback_setPyramidCount (PyObject *self, PyObject *value, void *closure)
setter callback for the PyramidCount attribute
static PyObject * staticCallback_getPrismCount (PyObject *self, void *closure)
getter callback for the PrismCount attribute
static int staticCallback_setPrismCount (PyObject *self, PyObject *value, void *closure)
setter callback for the PrismCount attribute
static PyObject * staticCallback_getPolyhedronCount (PyObject *self, void *closure)
getter callback for the PolyhedronCount attribute
static int staticCallback_setPolyhedronCount (PyObject *self, PyObject *value, void *closure)
setter callback for the PolyhedronCount attribute
static PyObject * staticCallback_getSubMeshCount (PyObject *self, void *closure)
getter callback for the SubMeshCount attribute
static int staticCallback_setSubMeshCount (PyObject *self, PyObject *value, void *closure)
setter callback for the SubMeshCount attribute
static PyObject * staticCallback_getGroupCount (PyObject *self, void *closure)
getter callback for the GroupCount attribute
static int staticCallback_setGroupCount (PyObject *self, PyObject *value, void *closure)
setter callback for the GroupCount attribute
static PyObject * staticCallback_getGroups (PyObject *self, void *closure)
getter callback for the Groups attribute
static int staticCallback_setGroups (PyObject *self, PyObject *value, void *closure)
setter callback for the Groups attribute
static PyObject * staticCallback_getVolume (PyObject *self, void *closure)
getter callback for the Volume attribute
static int staticCallback_setVolume (PyObject *self, PyObject *value, void *closure)
setter callback for the Volume attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for FemMesh.
Member Typedef Documentation
PointerType
typedef FemMesh* Fem::FemMeshPy::PointerType
Constructor & Destructor Documentation
~FemMeshPy()
FemMeshPy::~FemMeshPy () protected
FemMeshPy()
FemMeshPy::FemMeshPy (FemMesh * pcObject, PyTypeObject * T = &Type)
Referenced by copy(), and PyMake().
Member Function Documentation
addEdge()
PyObject * FemMeshPy::addEdge (PyObject * args)
implementer for the addEdge() method
References SMESHDS_Mesh::AddEdge(), SMESHDS_Mesh::AddEdgeWithID(), Base::BaseExceptionFreeCADError, SMDS_Mesh::FindNode(), getFemMeshPtr(), SMDS_MeshElement::GetID(), and Fem::FemMesh::getSMesh().
Referenced by PathScripts.PathDressupHoldingTags.MapWireToTag::add(), and staticCallback_addEdge().
addFace()
PyObject * FemMeshPy::addFace (PyObject * args)
implementer for the addFace() method
References SMESHDS_Mesh::AddFace(), SMESHDS_Mesh::AddFaceWithID(), Base::BaseExceptionFreeCADError, SMDS_Mesh::FindNode(), getFemMeshPtr(), and Fem::FemMesh::getSMesh().
Referenced by staticCallback_addFace().
addGroup()
PyObject * FemMeshPy::addGroup (PyObject * args)
implementer for the addGroup() method
References Fem::FemMesh::addGroup(), Base::BaseExceptionFreeCADError, and getFemMeshPtr().
Referenced by staticCallback_addGroup().
addGroupElements()
PyObject * FemMeshPy::addGroupElements (PyObject * args)
implementer for the addGroupElements() method
References Fem::FemMesh::addGroupElements(), Base::BaseExceptionFreeCADError, and getFemMeshPtr().
Referenced by staticCallback_addGroupElements().
addHypothesis()
PyObject * FemMeshPy::addHypothesis (PyObject * args)
implementer for the addHypothesis() method
References Fem::FemMesh::addHypothesis(), Base::BaseExceptionFreeCADError, getFemMeshPtr(), SMESH_Mesh::GetShapeToMesh(), Fem::FemMesh::getSMesh(), and Part::TopoShapePy::Type.
Referenced by staticCallback_addHypothesis().
addNode()
PyObject * FemMeshPy::addNode (PyObject * args)
implementer for the addNode() method
References SMESHDS_Mesh::AddNode(), SMESHDS_Mesh::AddNodeWithID(), Base::BaseExceptionFreeCADError, getFemMeshPtr(), SMDS_MeshElement::GetID(), and Fem::FemMesh::getSMesh().
Referenced by staticCallback_addNode().
addQuad()
PyObject * FemMeshPy::addQuad (PyObject * args)
implementer for the addQuad() method
References SMESHDS_Mesh::AddFace(), Base::BaseExceptionFreeCADError, SMDS_Mesh::FindNode(), getFemMeshPtr(), and Fem::FemMesh::getSMesh().
Referenced by staticCallback_addQuad().
addVolume()
PyObject * FemMeshPy::addVolume (PyObject * args)
implementer for the addVolume() method
References SMESHDS_Mesh::AddVolume(), SMESHDS_Mesh::AddVolumeWithID(), Base::BaseExceptionFreeCADError, SMDS_Mesh::FindNode(), getFemMeshPtr(), SMDS_MeshElement::GetID(), and Fem::FemMesh::getSMesh().
Referenced by staticCallback_addVolume().
compute()
PyObject * FemMeshPy::compute (PyObject * args)
implementer for the compute() method
References Base::BaseExceptionFreeCADError, Fem::FemMesh::compute(), and getFemMeshPtr().
Referenced by staticCallback_compute().
copy()
PyObject * FemMeshPy::copy (PyObject * args)
implementer for the copy() method
References FemMeshPy(), and getFemMeshPtr().
Referenced by staticCallback_copy().
getccxVolumesByFace()
PyObject * FemMeshPy::getccxVolumesByFace (PyObject * args)
implementer for the getccxVolumesByFace() method
References Base::BaseExceptionFreeCADError, Fem::FemMesh::getccxVolumesByFace(), getFemMeshPtr(), and Part::TopoShapeFacePy::Type.
Referenced by staticCallback_getccxVolumesByFace().
getCustomAttributes()
PyObject * FemMeshPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getEdgeCount()
Py::Long FemMeshPy::getEdgeCount (void) const
getter for the EdgeCount attribute
References getFemMeshPtr().
Referenced by staticCallback_getEdgeCount().
getEdges()
Py::Tuple FemMeshPy::getEdges (void) const
getter for the Edges attribute
References SMDS_Mesh::edgesIterator(), getFemMeshPtr(), SMDS_MeshElement::GetID(), SMESH_Mesh::GetMeshDS(), and Fem::FemMesh::getSMesh().
Referenced by shipOutlineDraw.TaskPanel.TaskPanel::accept(), and staticCallback_getEdges().
getEdgesByEdge()
PyObject * FemMeshPy::getEdgesByEdge (PyObject * args)
implementer for the getEdgesByEdge() method
References Base::BaseExceptionFreeCADError, Fem::FemMesh::getEdgesByEdge(), getFemMeshPtr(), and Part::TopoShapeEdgePy::Type.
Referenced by staticCallback_getEdgesByEdge().
getEdgesOnly()
Py::Tuple FemMeshPy::getEdgesOnly (void) const
getter for the EdgesOnly attribute
References Fem::FemMesh::getEdgesOnly(), and getFemMeshPtr().
Referenced by staticCallback_getEdgesOnly().
getElementNodes()
PyObject * FemMeshPy::getElementNodes (PyObject * args)
implementer for the getElementNodes() method
References Base::BaseExceptionFreeCADError, Fem::FemMesh::getElementNodes(), and getFemMeshPtr().
Referenced by staticCallback_getElementNodes().
getElementType()
PyObject * FemMeshPy::getElementType (PyObject * args)
implementer for the getElementType() method
References SMESH_Mesh::GetElementType(), getFemMeshPtr(), and Fem::FemMesh::getSMesh().
Referenced by staticCallback_getElementType().
getFaceCount()
Py::Long FemMeshPy::getFaceCount (void) const
getter for the FaceCount attribute
References getFemMeshPtr().
Referenced by staticCallback_getFaceCount().
getFaces()
Py::Tuple FemMeshPy::getFaces (void) const
getter for the Faces attribute
References SMDS_Mesh::facesIterator(), getFemMeshPtr(), SMDS_MeshElement::GetID(), SMESH_Mesh::GetMeshDS(), and Fem::FemMesh::getSMesh().
Referenced by staticCallback_getFaces().
getFacesByFace()
PyObject * FemMeshPy::getFacesByFace (PyObject * args)
implementer for the getFacesByFace() method
References Base::BaseExceptionFreeCADError, Fem::FemMesh::getFacesByFace(), getFemMeshPtr(), and Part::TopoShapeFacePy::Type.
Referenced by staticCallback_getFacesByFace().
getFacesOnly()
Py::Tuple FemMeshPy::getFacesOnly (void) const
getter for the FacesOnly attribute
References Fem::FemMesh::getFacesOnly(), and getFemMeshPtr().
Referenced by staticCallback_getFacesOnly().
getFemMeshPtr()
FemMesh * FemMeshPy::getFemMeshPtr (void) const
getter for the object handled by this class
Referenced by addEdge(), addFace(), addGroup(), addGroupElements(), addHypothesis(), addNode(), addQuad(), addVolume(), compute(), copy(), getccxVolumesByFace(), getEdgeCount(), getEdges(), getEdgesByEdge(), getEdgesOnly(), getElementNodes(), getElementType(), getFaceCount(), getFaces(), getFacesByFace(), getFacesOnly(), getGroupCount(), getGroupElements(), getGroupElementType(), getGroupName(), getGroups(), getHexaCount(), getIdByElementType(), getNodeById(), getNodeCount(), getNodes(), getNodesByEdge(), getNodesByFace(), getNodesBySolid(), getNodesByVertex(), getPolygonCount(), getPolyhedronCount(), getPrismCount(), getPyramidCount(), getQuadrangleCount(), getSubMeshCount(), getTetraCount(), getTriangleCount(), getVolume(), getVolumeCount(), getVolumes(), getVolumesByFace(), PyInit(), read(), removeGroup(), representation(), Fem::PropertyFemMesh::setPyObject(), setShape(), setStandardHypotheses(), setTransform(), write(), and writeABAQUS().
getGroupCount()
Py::Long FemMeshPy::getGroupCount (void) const
getter for the GroupCount attribute
References getFemMeshPtr().
Referenced by staticCallback_getGroupCount().
getGroupElements()
PyObject * FemMeshPy::getGroupElements (PyObject * args)
implementer for the getGroupElements() method
References getFemMeshPtr(), SMESH_Mesh::GetGroup(), SMDS_MeshElement::GetID(), and Fem::FemMesh::getSMesh().
Referenced by staticCallback_getGroupElements().
getGroupElementType()
PyObject * FemMeshPy::getGroupElementType (PyObject * args)
implementer for the getGroupElementType() method
References getFemMeshPtr(), SMESH_Mesh::GetGroup(), and Fem::FemMesh::getSMesh().
Referenced by staticCallback_getGroupElementType().
getGroupName()
PyObject * FemMeshPy::getGroupName (PyObject * args)
implementer for the getGroupName() method
References getFemMeshPtr().
Referenced by staticCallback_getGroupName().
getGroups()
Py::Tuple FemMeshPy::getGroups (void) const
getter for the Groups attribute
References getFemMeshPtr(), SMESH_Mesh::GetGroupIds(), and Fem::FemMesh::getSMesh().
Referenced by staticCallback_getGroups().
getHexaCount()
Py::Long FemMeshPy::getHexaCount (void) const
getter for the HexaCount attribute
References getFemMeshPtr().
Referenced by staticCallback_getHexaCount().
getIdByElementType()
PyObject * FemMeshPy::getIdByElementType (PyObject * args)
implementer for the getIdByElementType() method
References SMDS_Mesh::elementsIterator(), getFemMeshPtr(), SMDS_MeshElement::GetID(), SMESH_Mesh::GetMeshDS(), and Fem::FemMesh::getSMesh().
Referenced by staticCallback_getIdByElementType().
getNodeById()
PyObject * FemMeshPy::getNodeById (PyObject * args)
implementer for the getNodeById() method
References SMDS_Mesh::FindNode(), getFemMeshPtr(), SMESH_Mesh::GetMeshDS(), Fem::FemMesh::getSMesh(), Fem::FemMesh::getTransform(), draftgeoutils.general::vec(), SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
Referenced by staticCallback_getNodeById().
getNodeCount()
Py::Long FemMeshPy::getNodeCount (void) const
getter for the NodeCount attribute
References getFemMeshPtr().
Referenced by staticCallback_getNodeCount().
getNodes()
Py::Dict FemMeshPy::getNodes (void) const
getter for the Nodes attribute
References getFemMeshPtr(), SMDS_MeshElement::GetID(), SMESH_Mesh::GetMeshDS(), Fem::FemMesh::getSMesh(), Fem::FemMesh::getTransform(), SMDS_Mesh::nodesIterator(), draftgeoutils.general::vec(), SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
Referenced by staticCallback_getNodes().
getNodesByEdge()
PyObject * FemMeshPy::getNodesByEdge (PyObject * args)
implementer for the getNodesByEdge() method
References Base::BaseExceptionFreeCADError, getFemMeshPtr(), Fem::FemMesh::getNodesByEdge(), and Part::TopoShapeEdgePy::Type.
Referenced by staticCallback_getNodesByEdge().
getNodesByFace()
PyObject * FemMeshPy::getNodesByFace (PyObject * args)
implementer for the getNodesByFace() method
References Base::BaseExceptionFreeCADError, getFemMeshPtr(), Fem::FemMesh::getNodesByFace(), and Part::TopoShapeFacePy::Type.
Referenced by staticCallback_getNodesByFace().
getNodesBySolid()
PyObject * FemMeshPy::getNodesBySolid (PyObject * args)
implementer for the getNodesBySolid() method
References Base::BaseExceptionFreeCADError, getFemMeshPtr(), Fem::FemMesh::getNodesBySolid(), and Part::TopoShapeSolidPy::Type.
Referenced by staticCallback_getNodesBySolid().
getNodesByVertex()
PyObject * FemMeshPy::getNodesByVertex (PyObject * args)
implementer for the getNodesByVertex() method
References Base::BaseExceptionFreeCADError, getFemMeshPtr(), Fem::FemMesh::getNodesByVertex(), and Part::TopoShapeVertexPy::Type.
Referenced by staticCallback_getNodesByVertex().
getPolygonCount()
Py::Long FemMeshPy::getPolygonCount (void) const
getter for the PolygonCount attribute
References getFemMeshPtr().
Referenced by staticCallback_getPolygonCount().
getPolyhedronCount()
Py::Long FemMeshPy::getPolyhedronCount (void) const
getter for the PolyhedronCount attribute
References getFemMeshPtr().
Referenced by staticCallback_getPolyhedronCount().
getPrismCount()
Py::Long FemMeshPy::getPrismCount (void) const
getter for the PrismCount attribute
References getFemMeshPtr().
Referenced by staticCallback_getPrismCount().
getPyramidCount()
Py::Long FemMeshPy::getPyramidCount (void) const
getter for the PyramidCount attribute
References getFemMeshPtr().
Referenced by staticCallback_getPyramidCount().
getQuadrangleCount()
Py::Long FemMeshPy::getQuadrangleCount (void) const
getter for the QuadrangleCount attribute
References getFemMeshPtr().
Referenced by staticCallback_getQuadrangleCount().
getSubMeshCount()
Py::Long FemMeshPy::getSubMeshCount (void) const
getter for the SubMeshCount attribute
References getFemMeshPtr().
Referenced by staticCallback_getSubMeshCount().
getTetraCount()
Py::Long FemMeshPy::getTetraCount (void) const
getter for the TetraCount attribute
References getFemMeshPtr().
Referenced by staticCallback_getTetraCount().
getTriangleCount()
Py::Long FemMeshPy::getTriangleCount (void) const
getter for the TriangleCount attribute
References getFemMeshPtr().
Referenced by staticCallback_getTriangleCount().
GetType()
virtual PyTypeObject* Fem::FemMeshPy::GetType (void) virtual
Reimplemented from Data::ComplexGeoDataPy.
getVolume()
Py::Object FemMeshPy::getVolume (void) const
getter for the Volume attribute
References getFemMeshPtr().
Referenced by TankInstance.Tank::getCoG(), and staticCallback_getVolume().
getVolumeCount()
Py::Long FemMeshPy::getVolumeCount (void) const
getter for the VolumeCount attribute
References getFemMeshPtr().
Referenced by staticCallback_getVolumeCount().
getVolumes()
Py::Tuple FemMeshPy::getVolumes (void) const
getter for the Volumes attribute
References getFemMeshPtr(), SMDS_MeshElement::GetID(), SMESH_Mesh::GetMeshDS(), Fem::FemMesh::getSMesh(), and SMDS_Mesh::volumesIterator().
Referenced by staticCallback_getVolumes().
getVolumesByFace()
PyObject * FemMeshPy::getVolumesByFace (PyObject * args)
implementer for the getVolumesByFace() method
References Base::BaseExceptionFreeCADError, getFemMeshPtr(), Fem::FemMesh::getVolumesByFace(), and Part::TopoShapeFacePy::Type.
Referenced by staticCallback_getVolumesByFace().
PyInit()
int FemMeshPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Data::ComplexGeoDataPy.
References Base::BaseExceptionFreeCADError, getFemMeshPtr(), and Type.
PyMake()
PyObject * FemMeshPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References FemMeshPy().
read()
PyObject * FemMeshPy::read (PyObject * args)
implementer for the read() method
References Base::BaseExceptionFreeCADError, getFemMeshPtr(), and Fem::FemMesh::read().
Referenced by gzip_utf8.GzipFile::readline(), gzip_utf8.GzipFile::seek(), and staticCallback_read().
removeGroup()
PyObject * FemMeshPy::removeGroup (PyObject * args)
implementer for the removeGroup() method
References getFemMeshPtr().
Referenced by staticCallback_removeGroup().
representation()
std::string FemMeshPy::representation (void) const
References SMESH_Mesh::Dump(), getFemMeshPtr(), and Fem::FemMesh::getSMesh().
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int FemMeshPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setShape()
PyObject * FemMeshPy::setShape (PyObject * args)
implementer for the setShape() method
References Base::BaseExceptionFreeCADError, getFemMeshPtr(), Fem::FemMesh::getSMesh(), SMESH_Mesh::ShapeToMesh(), and Part::TopoShapePy::Type.
Referenced by staticCallback_setShape().
setStandardHypotheses()
PyObject * FemMeshPy::setStandardHypotheses (PyObject * args)
implementer for the setStandardHypotheses() method
References Base::BaseExceptionFreeCADError, getFemMeshPtr(), and Fem::FemMesh::setStandardHypotheses().
Referenced by staticCallback_setStandardHypotheses().
setTransform()
PyObject * FemMeshPy::setTransform (PyObject * args)
implementer for the setTransform() method
References Base::BaseExceptionFreeCADError, getFemMeshPtr(), Base::Placement::toMatrix(), Fem::FemMesh::transformGeometry(), and Base::PlacementPy::Type.
Referenced by staticCallback_setTransform().
staticCallback_addEdge()
PyObject * FemMeshPy::staticCallback_addEdge (PyObject * self, PyObject * args) static
callback for the addEdge() method
References addEdge(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addFace()
PyObject * FemMeshPy::staticCallback_addFace (PyObject * self, PyObject * args) static
callback for the addFace() method
References addFace(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addGroup()
PyObject * FemMeshPy::staticCallback_addGroup (PyObject * self, PyObject * args) static
callback for the addGroup() method
References addGroup(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_addGroupElements()
PyObject * FemMeshPy::staticCallback_addGroupElements (PyObject * self, PyObject * args) static
callback for the addGroupElements() method
References addGroupElements(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_addHypothesis()
PyObject * FemMeshPy::staticCallback_addHypothesis (PyObject * self, PyObject * args) static
callback for the addHypothesis() method
References addHypothesis(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addNode()
PyObject * FemMeshPy::staticCallback_addNode (PyObject * self, PyObject * args) static
callback for the addNode() method
References addNode(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addQuad()
PyObject * FemMeshPy::staticCallback_addQuad (PyObject * self, PyObject * args) static
callback for the addQuad() method
References addQuad(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addVolume()
PyObject * FemMeshPy::staticCallback_addVolume (PyObject * self, PyObject * args) static
callback for the addVolume() method
References addVolume(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_compute()
PyObject * FemMeshPy::staticCallback_compute (PyObject * self, PyObject * args) static
callback for the compute() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, compute(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_copy()
PyObject * FemMeshPy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copy(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getccxVolumesByFace()
PyObject * FemMeshPy::staticCallback_getccxVolumesByFace (PyObject * self, PyObject * args) static
callback for the getccxVolumesByFace() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getccxVolumesByFace(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getEdgeCount()
PyObject * FemMeshPy::staticCallback_getEdgeCount (PyObject * self, void * closure) static
getter callback for the EdgeCount attribute
References Base::BaseExceptionFreeCADError, getEdgeCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getEdges()
PyObject * FemMeshPy::staticCallback_getEdges (PyObject * self, void * closure) static
getter callback for the Edges attribute
References Base::BaseExceptionFreeCADError, getEdges(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getEdgesByEdge()
PyObject * FemMeshPy::staticCallback_getEdgesByEdge (PyObject * self, PyObject * args) static
callback for the getEdgesByEdge() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getEdgesByEdge(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getEdgesOnly()
PyObject * FemMeshPy::staticCallback_getEdgesOnly (PyObject * self, void * closure) static
getter callback for the EdgesOnly attribute
References Base::BaseExceptionFreeCADError, getEdgesOnly(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getElementNodes()
PyObject * FemMeshPy::staticCallback_getElementNodes (PyObject * self, PyObject * args) static
callback for the getElementNodes() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getElementNodes(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getElementType()
PyObject * FemMeshPy::staticCallback_getElementType (PyObject * self, PyObject * args) static
callback for the getElementType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getElementType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFaceCount()
PyObject * FemMeshPy::staticCallback_getFaceCount (PyObject * self, void * closure) static
getter callback for the FaceCount attribute
References Base::BaseExceptionFreeCADError, getFaceCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFaces()
PyObject * FemMeshPy::staticCallback_getFaces (PyObject * self, void * closure) static
getter callback for the Faces attribute
References Base::BaseExceptionFreeCADError, getFaces(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFacesByFace()
PyObject * FemMeshPy::staticCallback_getFacesByFace (PyObject * self, PyObject * args) static
callback for the getFacesByFace() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getFacesByFace(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFacesOnly()
PyObject * FemMeshPy::staticCallback_getFacesOnly (PyObject * self, void * closure) static
getter callback for the FacesOnly attribute
References Base::BaseExceptionFreeCADError, getFacesOnly(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getGroupCount()
PyObject * FemMeshPy::staticCallback_getGroupCount (PyObject * self, void * closure) static
getter callback for the GroupCount attribute
References Base::BaseExceptionFreeCADError, getGroupCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getGroupElements()
PyObject * FemMeshPy::staticCallback_getGroupElements (PyObject * self, PyObject * args) static
callback for the getGroupElements() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getGroupElements(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getGroupElementType()
PyObject * FemMeshPy::staticCallback_getGroupElementType (PyObject * self, PyObject * args) static
callback for the getGroupElementType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getGroupElementType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getGroupName()
PyObject * FemMeshPy::staticCallback_getGroupName (PyObject * self, PyObject * args) static
callback for the getGroupName() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getGroupName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getGroups()
PyObject * FemMeshPy::staticCallback_getGroups (PyObject * self, void * closure) static
getter callback for the Groups attribute
References Base::BaseExceptionFreeCADError, getGroups(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getHexaCount()
PyObject * FemMeshPy::staticCallback_getHexaCount (PyObject * self, void * closure) static
getter callback for the HexaCount attribute
References Base::BaseExceptionFreeCADError, getHexaCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getIdByElementType()
PyObject * FemMeshPy::staticCallback_getIdByElementType (PyObject * self, PyObject * args) static
callback for the getIdByElementType() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getIdByElementType(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNodeById()
PyObject * FemMeshPy::staticCallback_getNodeById (PyObject * self, PyObject * args) static
callback for the getNodeById() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getNodeById(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNodeCount()
PyObject * FemMeshPy::staticCallback_getNodeCount (PyObject * self, void * closure) static
getter callback for the NodeCount attribute
References Base::BaseExceptionFreeCADError, getNodeCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNodes()
PyObject * FemMeshPy::staticCallback_getNodes (PyObject * self, void * closure) static
getter callback for the Nodes attribute
References Base::BaseExceptionFreeCADError, getNodes(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNodesByEdge()
PyObject * FemMeshPy::staticCallback_getNodesByEdge (PyObject * self, PyObject * args) static
callback for the getNodesByEdge() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getNodesByEdge(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNodesByFace()
PyObject * FemMeshPy::staticCallback_getNodesByFace (PyObject * self, PyObject * args) static
callback for the getNodesByFace() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getNodesByFace(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNodesBySolid()
PyObject * FemMeshPy::staticCallback_getNodesBySolid (PyObject * self, PyObject * args) static
callback for the getNodesBySolid() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getNodesBySolid(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNodesByVertex()
PyObject * FemMeshPy::staticCallback_getNodesByVertex (PyObject * self, PyObject * args) static
callback for the getNodesByVertex() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getNodesByVertex(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPolygonCount()
PyObject * FemMeshPy::staticCallback_getPolygonCount (PyObject * self, void * closure) static
getter callback for the PolygonCount attribute
References Base::BaseExceptionFreeCADError, getPolygonCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPolyhedronCount()
PyObject * FemMeshPy::staticCallback_getPolyhedronCount (PyObject * self, void * closure) static
getter callback for the PolyhedronCount attribute
References Base::BaseExceptionFreeCADError, getPolyhedronCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPrismCount()
PyObject * FemMeshPy::staticCallback_getPrismCount (PyObject * self, void * closure) static
getter callback for the PrismCount attribute
References Base::BaseExceptionFreeCADError, getPrismCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPyramidCount()
PyObject * FemMeshPy::staticCallback_getPyramidCount (PyObject * self, void * closure) static
getter callback for the PyramidCount attribute
References Base::BaseExceptionFreeCADError, getPyramidCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getQuadrangleCount()
PyObject * FemMeshPy::staticCallback_getQuadrangleCount (PyObject * self, void * closure) static
getter callback for the QuadrangleCount attribute
References Base::BaseExceptionFreeCADError, getQuadrangleCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSubMeshCount()
PyObject * FemMeshPy::staticCallback_getSubMeshCount (PyObject * self, void * closure) static
getter callback for the SubMeshCount attribute
References Base::BaseExceptionFreeCADError, getSubMeshCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTetraCount()
PyObject * FemMeshPy::staticCallback_getTetraCount (PyObject * self, void * closure) static
getter callback for the TetraCount attribute
References Base::BaseExceptionFreeCADError, getTetraCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTriangleCount()
PyObject * FemMeshPy::staticCallback_getTriangleCount (PyObject * self, void * closure) static
getter callback for the TriangleCount attribute
References Base::BaseExceptionFreeCADError, getTriangleCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVolume()
PyObject * FemMeshPy::staticCallback_getVolume (PyObject * self, void * closure) static
getter callback for the Volume attribute
References Base::BaseExceptionFreeCADError, getVolume(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVolumeCount()
PyObject * FemMeshPy::staticCallback_getVolumeCount (PyObject * self, void * closure) static
getter callback for the VolumeCount attribute
References Base::BaseExceptionFreeCADError, getVolumeCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVolumes()
PyObject * FemMeshPy::staticCallback_getVolumes (PyObject * self, void * closure) static
getter callback for the Volumes attribute
References Base::BaseExceptionFreeCADError, getVolumes(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVolumesByFace()
PyObject * FemMeshPy::staticCallback_getVolumesByFace (PyObject * self, PyObject * args) static
callback for the getVolumesByFace() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getVolumesByFace(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_read()
PyObject * FemMeshPy::staticCallback_read (PyObject * self, PyObject * args) static
callback for the read() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), read(), and Base::PyObjectBase::startNotify().
staticCallback_removeGroup()
PyObject * FemMeshPy::staticCallback_removeGroup (PyObject * self, PyObject * args) static
callback for the removeGroup() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and removeGroup().
staticCallback_setEdgeCount()
int FemMeshPy::staticCallback_setEdgeCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the EdgeCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setEdges()
int FemMeshPy::staticCallback_setEdges (PyObject * self, PyObject * value, void * closure) static
setter callback for the Edges attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setEdgesOnly()
int FemMeshPy::staticCallback_setEdgesOnly (PyObject * self, PyObject * value, void * closure) static
setter callback for the EdgesOnly attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setFaceCount()
int FemMeshPy::staticCallback_setFaceCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the FaceCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setFaces()
int FemMeshPy::staticCallback_setFaces (PyObject * self, PyObject * value, void * closure) static
setter callback for the Faces attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setFacesOnly()
int FemMeshPy::staticCallback_setFacesOnly (PyObject * self, PyObject * value, void * closure) static
setter callback for the FacesOnly attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setGroupCount()
int FemMeshPy::staticCallback_setGroupCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the GroupCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setGroups()
int FemMeshPy::staticCallback_setGroups (PyObject * self, PyObject * value, void * closure) static
setter callback for the Groups attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setHexaCount()
int FemMeshPy::staticCallback_setHexaCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the HexaCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setNodeCount()
int FemMeshPy::staticCallback_setNodeCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the NodeCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setNodes()
int FemMeshPy::staticCallback_setNodes (PyObject * self, PyObject * value, void * closure) static
setter callback for the Nodes attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPolygonCount()
int FemMeshPy::staticCallback_setPolygonCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the PolygonCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPolyhedronCount()
int FemMeshPy::staticCallback_setPolyhedronCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the PolyhedronCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPrismCount()
int FemMeshPy::staticCallback_setPrismCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the PrismCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPyramidCount()
int FemMeshPy::staticCallback_setPyramidCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the PyramidCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setQuadrangleCount()
int FemMeshPy::staticCallback_setQuadrangleCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the QuadrangleCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setShape()
PyObject * FemMeshPy::staticCallback_setShape (PyObject * self, PyObject * args) static
callback for the setShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setShape(), and Base::PyObjectBase::startNotify().
staticCallback_setStandardHypotheses()
PyObject * FemMeshPy::staticCallback_setStandardHypotheses (PyObject * self, PyObject * args) static
callback for the setStandardHypotheses() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setStandardHypotheses(), and Base::PyObjectBase::startNotify().
staticCallback_setSubMeshCount()
int FemMeshPy::staticCallback_setSubMeshCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the SubMeshCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setTetraCount()
int FemMeshPy::staticCallback_setTetraCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the TetraCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setTransform()
PyObject * FemMeshPy::staticCallback_setTransform (PyObject * self, PyObject * args) static
callback for the setTransform() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setTransform(), and Base::PyObjectBase::startNotify().
staticCallback_setTriangleCount()
int FemMeshPy::staticCallback_setTriangleCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the TriangleCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setVolume()
int FemMeshPy::staticCallback_setVolume (PyObject * self, PyObject * value, void * closure) static
setter callback for the Volume attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setVolumeCount()
int FemMeshPy::staticCallback_setVolumeCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the VolumeCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setVolumes()
int FemMeshPy::staticCallback_setVolumes (PyObject * self, PyObject * value, void * closure) static
setter callback for the Volumes attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_write()
PyObject * FemMeshPy::staticCallback_write (PyObject * self, PyObject * args) static
callback for the write() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and write().
staticCallback_writeABAQUS()
PyObject * FemMeshPy::staticCallback_writeABAQUS (PyObject * self, PyObject * args) static
callback for the writeABAQUS() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and writeABAQUS().
write()
PyObject * FemMeshPy::write (PyObject * args)
implementer for the write() method
References Base::BaseExceptionFreeCADError, getFemMeshPtr(), and Fem::FemMesh::write().
Referenced by gzip_utf8.GzipFile::seek(), and staticCallback_write().
writeABAQUS()
PyObject * FemMeshPy::writeABAQUS (PyObject * args)
implementer for the writeABAQUS() method
References Base::BaseExceptionFreeCADError, getFemMeshPtr(), and Fem::FemMesh::writeABAQUS().
Referenced by staticCallback_writeABAQUS().
Member Data Documentation
GetterSetter
PyGetSetDef FemMeshPy::GetterSetter static
Attribute structure of FemMeshPy.
Methods
PyMethodDef FemMeshPy::Methods static
Methods structure of FemMeshPy.
Type
PyTypeObject FemMeshPy::Type static
Type structure of FemMeshPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), PyInit(), draftobjects.layer.Layer::set_properties(), Fem::SMESH_HypothesisPy< T >::setParametersByMesh(), ArchReference.ArchReference::setProperties(), and Fem::PropertyFemMesh::setPyObject().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Fem/App/FemMeshPy.h
Sources/FreeCAD/src/Mod/Fem/App/FemMeshPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Fem/App/FemMeshPy.cpp