FreeCAD: iisTaskBox Class Reference
iisTaskBox Class Reference
#include <iistaskbox.h>
Public Slots
void showHide ()
Public Member Functions
void addIconLabel (iisIconLabel *label, bool addToLayout=true)
QBoxLayout * groupLayout ()
iisTaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
iisTaskBox (const QString &title, bool expandable=true, QWidget *parent=0)
void setScheme (iisTaskPanelScheme *pointer)
virtual ~iisTaskBox ()
Protected Slots
void processHide ()
void processShow ()
Protected Member Functions
void init ()
virtual void paintEvent (QPaintEvent *event)
Protected Attributes
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
iisTaskGroup * myGroup
iisTaskHeader * myHeader
iisTaskPanelScheme * myScheme
Constructor & Destructor Documentation
iisTaskBox() [1/2]
iisTaskBox::iisTaskBox (const QString & title, bool expandable = true, QWidget * parent = 0)
References init(), and myHeader.
iisTaskBox() [2/2]
iisTaskBox::iisTaskBox (const QPixmap & icon, const QString & title, bool expandable = true, QWidget * parent = 0)
References init(), and myHeader.
~iisTaskBox()
iisTaskBox::~iisTaskBox () virtual
Member Function Documentation
addIconLabel()
void iisTaskBox::addIconLabel (iisIconLabel * label, bool addToLayout = true)
References iisTaskGroup::addIconLabel(), and myGroup.
Referenced by SandboxGui::TaskPanelView::TaskPanelView(), and test::test().
groupLayout()
QBoxLayout * iisTaskBox::groupLayout ()
References iisTaskGroup::groupLayout(), and myGroup.
Referenced by SandboxGui::TaskPanelView::TaskPanelView(), and test::test().
init()
void iisTaskBox::init (void) protected
References draftgeoutils.intersections::connect(), iisTaskPanelScheme::defaultScheme(), m_foldStep, myDummy, myGroup, myHeader, myScheme, and showHide().
Referenced by iisTaskBox(), and DocumentObject.DocumentObject::onChanged().
paintEvent()
void iisTaskBox::paintEvent (QPaintEvent * event) protected virtual
References iisTaskPanelScheme::groupFoldSteps, m_foldDirection, m_foldPixmap, m_foldStep, myDummy, and myScheme.
processHide
void iisTaskBox::processHide () protected slot
References iisTaskPanelScheme::groupFoldDelay, m_foldDelta, m_foldPixmap, m_foldStep, m_tempHeight, myDummy, myHeader, and myScheme.
Referenced by showHide().
processShow
void iisTaskBox::processShow () protected slot
References iisTaskPanelScheme::groupFoldDelay, m_foldDelta, m_foldPixmap, m_foldStep, m_fullHeight, m_tempHeight, myDummy, myGroup, myHeader, and myScheme.
Referenced by showHide().
setScheme()
void iisTaskBox::setScheme (iisTaskPanelScheme * pointer)
References myGroup, myHeader, myScheme, iisTaskGroup::setScheme(), and iisTaskHeader::setScheme().
Referenced by test::on_rbXP_clicked(), and SandboxGui::TaskPanelView::TaskPanelView().
showHide
void iisTaskBox::showHide () slot
References iisTaskPanelScheme::groupFoldDelay, iisTaskPanelScheme::groupFoldSteps, m_foldDelta, m_foldDirection, m_foldPixmap, m_foldStep, m_fullHeight, m_tempHeight, myDummy, myGroup, myScheme, processHide(), and processShow().
Referenced by init().
Member Data Documentation
m_foldDelta
double iisTaskBox::m_foldDelta protected
Referenced by processHide(), processShow(), and showHide().
m_foldDirection
int iisTaskBox::m_foldDirection protected
Referenced by paintEvent(), and showHide().
m_foldPixmap
QPixmap iisTaskBox::m_foldPixmap protected
Referenced by paintEvent(), processHide(), processShow(), and showHide().
m_foldStep
double iisTaskBox::m_foldStep protected
Referenced by init(), paintEvent(), processHide(), processShow(), and showHide().
m_fullHeight
double iisTaskBox::m_fullHeight protected
Referenced by processShow(), and showHide().
m_tempHeight
double iisTaskBox::m_tempHeight protected
Referenced by processHide(), processShow(), and showHide().
myDummy
QWidget* iisTaskBox::myDummy protected
Referenced by init(), paintEvent(), processHide(), processShow(), and showHide().
myGroup
iisTaskGroup* iisTaskBox::myGroup protected
Referenced by addIconLabel(), groupLayout(), init(), processShow(), setScheme(), and showHide().
myHeader
iisTaskHeader* iisTaskBox::myHeader protected
Referenced by iisTaskBox(), init(), processHide(), processShow(), and setScheme().
myScheme
iisTaskPanelScheme* iisTaskBox::myScheme protected
Referenced by init(), paintEvent(), processHide(), processShow(), setScheme(), and showHide().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/iisTaskPanel/src/iistaskbox.h
Sources/FreeCAD/src/Gui/iisTaskPanel/src/iistaskbox.cpp