FreeCAD: Gui::PrefQuantitySpinBox Class Reference
Gui::PrefQuantitySpinBox Class Reference
The PrefQuantitySpinBox class.
#include <PrefWidgets.h>
Public Member Functions
int historySize () const
get the value of the history size property
void onRestore ()
Convenience method as offered by PrefWidget. Does the same as setToLastUsedValue().
void onSave ()
Convenience method as offered by PrefWidget. Does the same as pushToHistory().
PrefQuantitySpinBox (QWidget *parent=0)
void setHistorySize (int)
set the value of the history size property
void setToLastUsedValue ()
set the input field to the last used value (works only if the setParamGrpPath() was called)
virtual ~PrefQuantitySpinBox ()
Public Member Functions inherited from Gui::QuantitySpinBox
virtual bool apply ()
virtual bool apply (const std::string &propName)
bool apply (const std::string &propName)
void bind (const App::ObjectIdentifier &_path)
QString boundToName () const
Gets the path of the bound property.
virtual void clear ()
void clearSchema ()
Clears the schemaand again use the system-wide schema.
int decimals () const
Gets the number of decimals.
bool event (QEvent *event)
QString expressionText () const
Gets the expression as a string.
virtual void fixup (QString &str) const
bool hasValidInput () const
Gives the current state of the user input, gives true if it is a valid input with correct quantity or returns false if the input is a unparsable string or has a wrong unit.
double maximum () const
Gets the value of the maximum property.
double minimum () const
Gets the value of the minimum property.
QSize minimumSizeHint () const
QuantitySpinBox (QWidget *parent=0)
double rawValue () const
Get the current quantity without unit.
void selectNumber ()
Set the number portion selected.
void setBoundToByName (const QString &path)
Sets the path of the bound property.
void setDecimals (int v)
Sets the number of decimals.
void setExpression (boost::shared_ptr< App::Expression > expr)
void setMaximum (double max)
Sets the value of the maximum property.
void setMinimum (double min)
Sets the value of the minimum property.
void setRange (double min, double max)
void setSchema (const Base::UnitSystem &s)
Sets a specific unit schema to handle quantities.
void setSingleStep (double val)
Set the value of the singleStep property.
void setUnit (const Base::Unit &unit)
void setUnitText (const QString &)
Set the unit property.
double singleStep () const
Get the value of the singleStep property.
QSize sizeHint () const
virtual void stepBy (int steps)
QString textFromValue (const Base::Quantity &val) const
Base::Unit unit () const
Sets the Unit this widget is working with.
QString unitText (void)
Get the unit property.
virtual QValidator::State validate (QString &input, int &pos) const
Base::Quantity value () const
Get the current quantity.
Base::Quantity valueFromText (const QString &text) const
virtual ~QuantitySpinBox ()
Public Member Functions inherited from Gui::ExpressionBinding
bool autoApply () const
virtual void bind (const App::Property &prop)
ExpressionBinding ()
QPixmap getIcon (const char *name, const QSize &size) const
bool hasExpression () const
bool isBound () const
void setAutoApply (bool value)
void unbind ()
virtual ~ExpressionBinding ()
Properties
int historySize
QByteArray prefPath
Properties inherited from Gui::QuantitySpinBox
QString binding
QString expression
double maximum
double minimum
double rawValue
double singleStep
QString unit
Base::Quantity value
history and default management
QByteArray paramGrpPath () const
the param group path where the widget writes and reads the default values
void setParamGrpPath (const QByteArray &name)
set the param group path where the widget writes and reads the default values
void pushToHistory (const QString &value=QString())
push a new value to the history, if no string given the actual text of the input field is used.
QStringList getHistory () const
get the history of the field, newest first
virtual void contextMenuEvent (QContextMenuEvent *event)
Additional Inherited Members
Public Slots inherited from Gui::QuantitySpinBox
void setValue (const Base::Quantity &val)
Sets the field with a quantity.
void setValue (double)
Set a numerical value which gets converted to a quantity with the currently set unit type.
Signals inherited from Gui::QuantitySpinBox
void showFormulaDialog (bool)
Gets emitted if formula dialog is about to be opened (true) or finished (false).
void textChanged (const QString &)
The new value is passed in text with unit.
void valueChanged (const Base::Quantity &)
Gets emitted if the user has entered a VALID input Valid means the user inputted string obeys all restrictions like: minimum, maximum and/or the right Unit (if specified).
void valueChanged (double)
Gets emitted if the user has entered a VALID input Valid means the user inputted string obeys all restrictions like: minimum, maximum and/or the right Unit (if specified).
Protected Slots inherited from Gui::QuantitySpinBox
void finishFormulaDialog ()
void handlePendingEmit ()
virtual void onChange ()
void openFormulaDialog ()
void userInput (const QString &text)
Protected Member Functions inherited from Gui::QuantitySpinBox
virtual void closeEvent (QCloseEvent *event)
virtual void focusInEvent (QFocusEvent *event)
virtual void focusOutEvent (QFocusEvent *event)
virtual void hideEvent (QHideEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void paintEvent (QPaintEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void showEvent (QShowEvent *event)
virtual StepEnabled stepEnabled () const
Protected Member Functions inherited from Gui::ExpressionBinding
void expressionChange (const App::ObjectIdentifier &id)
std::string getEscapedExpressionString () const
boost::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
const App::ObjectIdentifier & getPath () const
void objectDeleted (const App::DocumentObject &)
virtual void onChange ()
Protected Attributes inherited from Gui::ExpressionBinding
QPalette defaultPalette
boost::signals2::scoped_connection expressionchanged
int iconHeight
QLabel * iconLabel
bool m_autoApply
boost::signals2::scoped_connection objectdeleted
Detailed Description
The PrefQuantitySpinBox class.
Author
Werner Mayer
Constructor & Destructor Documentation
PrefQuantitySpinBox()
PrefQuantitySpinBox::PrefQuantitySpinBox (QWidget * parent = 0)
~PrefQuantitySpinBox()
PrefQuantitySpinBox::~PrefQuantitySpinBox () virtual
Member Function Documentation
contextMenuEvent()
void PrefQuantitySpinBox::contextMenuEvent (QContextMenuEvent * event) protected virtual
References getHistory(), and pushToHistory().
getHistory()
QStringList PrefQuantitySpinBox::getHistory (void) const
get the history of the field, newest first
Referenced by contextMenuEvent(), and setToLastUsedValue().
historySize()
int PrefQuantitySpinBox::historySize (void) const
get the value of the history size property
onRestore()
void PrefQuantitySpinBox::onRestore ()
Convenience method as offered by PrefWidget. Does the same as setToLastUsedValue().
References setToLastUsedValue().
onSave()
void PrefQuantitySpinBox::onSave ()
Convenience method as offered by PrefWidget. Does the same as pushToHistory().
References pushToHistory().
paramGrpPath()
QByteArray PrefQuantitySpinBox::paramGrpPath () const
the param group path where the widget writes and reads the default values
pushToHistory()
void PrefQuantitySpinBox::pushToHistory (const QString & value = QString())
push a new value to the history, if no string given the actual text of the input field is used.
References Gui::QuantitySpinBox::value, and Base::ConsoleSingleton::Warning().
Referenced by contextMenuEvent(), and onSave().
setHistorySize()
void PrefQuantitySpinBox::setHistorySize (int i)
set the value of the history size property
setParamGrpPath()
void PrefQuantitySpinBox::setParamGrpPath (const QByteArray & name)
set the param group path where the widget writes and reads the default values
References App::GetApplication(), and App::Application::GetParameterGroupByPath().
setToLastUsedValue()
void PrefQuantitySpinBox::setToLastUsedValue (void)
set the input field to the last used value (works only if the setParamGrpPath() was called)
References getHistory().
Referenced by onRestore().
Property Documentation
historySize
int Gui::PrefQuantitySpinBox::historySize read write
prefPath
QByteArray Gui::PrefQuantitySpinBox::prefPath read write
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/PrefWidgets.h
Sources/FreeCAD/src/Gui/PrefWidgets.cpp