FreeCAD: MeshCore::MeshDistanceGenericSurfaceFitSegment Class Reference
MeshCore::MeshDistanceGenericSurfaceFitSegment Class Reference
#include <Segmentation.h>
Public Member Functions
void AddFacet (const MeshFacet &rclFacet)
const char * GetType () const
void Initialize (FacetIndex)
MeshDistanceGenericSurfaceFitSegment (AbstractSurfaceFit *, const MeshKernel &mesh, unsigned long minFacets, float tol)
std::vector< float > Parameters () const
bool TestFacet (const MeshFacet &rclFacet) const
bool TestInitialFacet (FacetIndex) const
virtual ~MeshDistanceGenericSurfaceFitSegment ()
Public Member Functions inherited from MeshCore::MeshDistanceSurfaceSegment
MeshDistanceSurfaceSegment (const MeshKernel &mesh, unsigned long minFacets, float tol)
Public Member Functions inherited from MeshCore::MeshSurfaceSegment
virtual void AddFacet (const MeshFacet &rclFacet)
void AddSegment (const std::vector< FacetIndex > &)
MeshSegment FindSegment (FacetIndex) const
const std::vector< MeshSegment > & GetSegments () const
virtual const char * GetType () const =0
virtual void Initialize (FacetIndex)
MeshSurfaceSegment (unsigned long minFacets)
virtual bool TestFacet (const MeshFacet &rclFacet) const =0
virtual bool TestInitialFacet (FacetIndex) const
virtual ~MeshSurfaceSegment ()
Protected Attributes
AbstractSurfaceFit * fitter
Protected Attributes inherited from MeshCore::MeshDistanceSurfaceSegment
const MeshKernel & kernel
float tolerance
Protected Attributes inherited from MeshCore::MeshSurfaceSegment
unsigned long minFacets
std::vector< MeshSegment > segments
Constructor & Destructor Documentation
MeshDistanceGenericSurfaceFitSegment()
MeshDistanceGenericSurfaceFitSegment::MeshDistanceGenericSurfaceFitSegment (AbstractSurfaceFit * fit, const MeshKernel & mesh, unsigned long minFacets, float tol)
~MeshDistanceGenericSurfaceFitSegment()
MeshDistanceGenericSurfaceFitSegment::~MeshDistanceGenericSurfaceFitSegment () virtual
References fitter.
Member Function Documentation
AddFacet()
void MeshDistanceGenericSurfaceFitSegment::AddFacet (const MeshFacet & rclFacet) virtual
Reimplemented from MeshCore::MeshSurfaceSegment.
References MeshCore::AbstractSurfaceFit::AddTriangle(), fitter, MeshCore::MeshKernel::GetFacet(), and MeshCore::MeshDistanceSurfaceSegment::kernel.
GetType()
const char * MeshCore::MeshDistanceGenericSurfaceFitSegment::GetType (void) const virtual
Implements MeshCore::MeshSurfaceSegment.
Initialize()
void MeshDistanceGenericSurfaceFitSegment::Initialize (FacetIndex index) virtual
Reimplemented from MeshCore::MeshSurfaceSegment.
References fitter, MeshCore::MeshKernel::GetFacet(), MeshCore::AbstractSurfaceFit::Initialize(), and MeshCore::MeshDistanceSurfaceSegment::kernel.
Parameters()
std::vector< float > MeshDistanceGenericSurfaceFitSegment::Parameters () const
References fitter, and MeshCore::AbstractSurfaceFit::Parameters().
TestFacet()
bool MeshDistanceGenericSurfaceFitSegment::TestFacet (const MeshFacet & rclFacet) const virtual
Implements MeshCore::MeshSurfaceSegment.
References MeshCore::AbstractSurfaceFit::Done(), MeshCore::AbstractSurfaceFit::Fit(), fitter, MeshCore::AbstractSurfaceFit::GetDistanceToSurface(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshDistanceSurfaceSegment::kernel, MeshCore::AbstractSurfaceFit::TestTriangle(), and MeshCore::MeshDistanceSurfaceSegment::tolerance.
TestInitialFacet()
bool MeshDistanceGenericSurfaceFitSegment::TestInitialFacet (FacetIndex index) const virtual
Reimplemented from MeshCore::MeshSurfaceSegment.
References fitter, MeshCore::AbstractSurfaceFit::GetDistanceToSurface(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshDistanceSurfaceSegment::kernel, MeshCore::AbstractSurfaceFit::TestTriangle(), and MeshCore::MeshDistanceSurfaceSegment::tolerance.
Member Data Documentation
fitter
AbstractSurfaceFit* MeshCore::MeshDistanceGenericSurfaceFitSegment::fitter protected
Referenced by AddFacet(), Initialize(), Parameters(), TestFacet(), TestInitialFacet(), and ~MeshDistanceGenericSurfaceFitSegment().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/Core/Segmentation.h
FreeCAD/src/Mod/Mesh/App/Core/Segmentation.cpp