FreeCAD: feminout.importFenicsMesh Namespace Reference
feminout.importFenicsMesh Namespace Reference
Classes
class WriteXDMFTaskPanel
Functions
def export (objectslist, fileString, group_values_dict_nogui=None)
def import_fenics_mesh (filename, analysis=None)
def insert (filename, docname)
def open (filename)
Variables
pyopen = open
Function Documentation
export()
def feminout.importFenicsMesh.export (objectslist, fileString, group_values_dict_nogui = None)
Called when freecad exports a file.
group_dict_no_gui: dictionary with group_numbers as keys and tuples
of (marked_value (default=1), default_value (default=0))
import_fenics_mesh()
def feminout.importFenicsMesh.import_fenics_mesh (filename, analysis = None)
insert a FreeCAD FEM Mesh object in the ActiveDocument
Referenced by feminout.importFenicsMesh.insert().
insert()
def feminout.importFenicsMesh.insert (filename, docname)
References feminout.importFenicsMesh.import_fenics_mesh().
Referenced by feminout.importFenicsMesh.open().
open()
def feminout.importFenicsMesh.open (filename)
References feminout.importFenicsMesh.insert().
Variable Documentation
pyopen
feminout.importFenicsMesh.pyopen = open