FreeCAD: import3DS Namespace Reference
import3DS Namespace Reference
Workbenches » Python workbenches » Arch
3DS file format importer
Functions
def check3DS ()
def decode (name)
def insert (filename, docname)
def open (filename)
def read (filename)
Variables
bool DEBUG = True
Detailed Description
3DS file format importer
This module provides tools to import 3DS files.
Function Documentation
check3DS()
def import3DS.check3DS ()
Referenced by insert(), and open().
decode()
def import3DS.decode (name)
Referenced by open().
insert()
def import3DS.insert (filename, docname)
References check3DS(), and read().
open()
def import3DS.open (filename)
References check3DS(), decode(), and read().
read()
def import3DS.read (filename)
Referenced by insert(), and open().
Variable Documentation
DEBUG
bool import3DS.DEBUG = True