FreeCAD: Gui::Dialog::DlgSettingsMacroImp Class Reference
Gui::Dialog::DlgSettingsMacroImp Class Reference
The DlgSettingsMacroImp class implements a preference page to change settings for macro stuff.
#include <DlgSettingsMacroImp.h>
Public Member Functions
DlgSettingsMacroImp (QWidget *parent=nullptr)
Constructs a DlgSettingsMacroImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
void loadSettings ()
void saveSettings ()
~DlgSettingsMacroImp ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
virtual void changeEvent (QEvent *e)=0
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Detailed Description
The DlgSettingsMacroImp class implements a preference page to change settings for macro stuff.
Author
Jürgen Riegel
Constructor & Destructor Documentation
DlgSettingsMacroImp()
DlgSettingsMacroImp::DlgSettingsMacroImp (QWidget * parent = nullptr)
Constructs a DlgSettingsMacroImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
References App::GetApplication().
~DlgSettingsMacroImp()
DlgSettingsMacroImp::~DlgSettingsMacroImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void DlgSettingsMacroImp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
loadSettings()
void DlgSettingsMacroImp::loadSettings () virtual
Implements Gui::Dialog::PreferencePage.
References ParameterGrp::GetASCII(), Gui::WindowParameter::getDefaultParameter(), and ParameterGrp::GetGroup().
saveSettings()
void DlgSettingsMacroImp::saveSettings () virtual
Implements Gui::Dialog::PreferencePage.
References Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), and ParameterGrp::SetASCII().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgSettingsMacroImp.h
FreeCAD/src/Gui/DlgSettingsMacroImp.cpp