FreeCAD: MED::TGaussDef Struct Reference
MED::TGaussDef Struct Reference
Description of family of integration points.
#include <MED_GaussDef.hxx>
Public Member Functions
MEDWRAPPER_EXPORT int dim () const
MEDWRAPPER_EXPORT int nbPoints () const
MEDWRAPPER_EXPORT TGaussDef (const int geomType, const int nbPoints, const int variant=1)
Creates definition of gauss points family.
Public Attributes
TDoubleVector myCoords
coordinates of Gauss points
TDoubleVector myRefCoords
description of reference points
int myType
element geometry (EGeometrieElement or med_geometrie_element)
TDoubleVector myWeights
weights, len(weights)==<nb of gauss points>
Detailed Description
Description of family of integration points.
Constructor & Destructor Documentation
TGaussDef()
MED::TGaussDef::TGaussDef (const int geomType, const int nbPoints, const int variant = 1)
Creates definition of gauss points family.
Fill definition of gauss points family.
Parameters
geomType - element geometry (EGeometrieElement or med_geometrie_element)
nbPoints - nb gauss point
variant - [1-3] to choose the variant of definition
Throws in case of invalid parameters variant == 1 refers to "Fonctions de forme et points d'integration des elements finis" v7.4 by J. PELLET, X. DESROCHES, 15/09/05 variant == 2 refers to the same doc v6.4 by J.P. LEFEBVRE, X. DESROCHES, 03/07/03 variant == 3 refers to the same doc v6.4, second variant for 2D elements
References MED::eHEXA20, MED::eHEXA8, MED::ePENTA15, MED::ePENTA6, MED::ePYRA13, MED::ePYRA5, MED::eQUAD4, MED::eQUAD8, MED::eSEG2, MED::eSEG3, MED::eTETRA10, MED::eTETRA4, MED::eTRIA3, and MED::eTRIA6.
Member Function Documentation
dim()
MEDWRAPPER_EXPORT int MED::TGaussDef::dim () const
References myType.
Referenced by ifc4.ifccartesiantransformationoperator3d::axis3is3d(), ifc4.ifcaxis2placement3d::axisis3d(), ifc2x3.ifcsweptsurface::dim(), ifc2x3.ifcplacement::dim(), ifc2x3.ifccartesiantransformationoperator::dim(), ifc2x3.ifccurveboundedplane::dim(), ifc2x3.ifccompositecurvesegment::dim(), ifc2x3.ifcgeometricset::dim(), ifc2x3.ifcrectangulartrimmedsurface::dim(), ifc2x3.ifcbooleanresult::dim(), ifc2x3.ifcelementarysurface::dim(), ifc2x3.ifcpointoncurve::dim(), ifc2x3.ifcpointonsurface::dim(), ifc2x3.ifcvector::dim(), ifc4.ifccompositecurvesegment::dim(), ifc4.ifcplacement::dim(), ifc4.ifccartesiantransformationoperator::dim(), ifc4.ifcgeometricset::dim(), ifc4.ifcbooleanresult::dim(), ifc4.ifcpointoncurve::dim(), ifc4.ifcpointonsurface::dim(), ifc4.ifcvector::dim(), ifc4.ifcaxis2placement3d::refdiris3d(), ifc4.ifcfillareastylehatching::refhatchline2d(), automotive_design.axis2_placement_3d::wr2(), config_control_design.axis2_placement_3d::wr2(), ifc2x3.ifcaxis2placement3d::wr2(), ifc2x3.ifcfillareastylehatching::wr23(), automotive_design.axis2_placement_3d::wr3(), config_control_design.axis2_placement_3d::wr3(), ifc2x3.ifcaxis2placement3d::wr3(), and ifc2x3.ifccartesiantransformationoperator3d::wr4().
nbPoints()
MEDWRAPPER_EXPORT int MED::TGaussDef::nbPoints () const
References myWeights.
Member Data Documentation
myCoords
TDoubleVector MED::TGaussDef::myCoords
coordinates of Gauss points
myRefCoords
TDoubleVector MED::TGaussDef::myRefCoords
description of reference points
myType
int MED::TGaussDef::myType
element geometry (EGeometrieElement or med_geometrie_element)
Referenced by dim().
myWeights
TDoubleVector MED::TGaussDef::myWeights
weights, len(weights)==<nb of gauss points>
Referenced by nbPoints().
The documentation for this struct was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/MED_GaussDef.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/MED_GaussDef.cpp