FreeCAD: SketcherGui::CarbonCopySelection Class Reference
SketcherGui::CarbonCopySelection Class Reference
Public Member Functions
bool allow (App::Document *pDoc, App::DocumentObject *pObj, const char *sSubName)
CarbonCopySelection (App::DocumentObject *obj)
Public Member Functions inherited from Gui::SelectionFilterGate
SelectionFilterGate (const char *filter)
construct with the filter string
SelectionFilterGate (SelectionFilter *filter)
~SelectionFilterGate ()
Public Member Functions inherited from Gui::SelectionGate
virtual ~SelectionGate ()
Additional Inherited Members
Public Attributes inherited from Gui::SelectionGate
std::string notAllowedReason
notAllowedReason is a string that sets the message to be displayed in statusbar for cluing the user on why is the selection not allowed.
Protected Member Functions inherited from Gui::SelectionFilterGate
SelectionFilterGate ()
Protected Attributes inherited from Gui::SelectionFilterGate
SelectionFilter * Filter
Constructor & Destructor Documentation
CarbonCopySelection()
SketcherGui::CarbonCopySelection::CarbonCopySelection (App::DocumentObject * obj)
Member Function Documentation
allow()
bool SketcherGui::CarbonCopySelection::allow (App::Document * pDoc, App::DocumentObject * pObj, const char * sSubName) virtual
Reimplemented from Gui::SelectionFilterGate.
References Sketcher::SketchObject::isCarbonCopyAllowed(), Gui::SelectionGate::notAllowedReason, Sketcher::SketchObject::rlAxesMisaligned, Sketcher::SketchObject::rlCircularReference, Sketcher::SketchObject::rlNonParallel, Sketcher::SketchObject::rlOriginsMisaligned, Sketcher::SketchObject::rlOtherBody, Sketcher::SketchObject::rlOtherBodyWithLinks, Sketcher::SketchObject::rlOtherDoc, Sketcher::SketchObject::rlOtherPart, Sketcher::SketchObject::setAllowOtherBody(), and Sketcher::SketchObject::setAllowUnaligned().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/Gui/CommandCreateGeo.cpp