FreeCAD: Swig_python Namespace Reference
Swig_python Namespace Reference
Functions
void cleanupSWIG_T (const char *TypeName)
int convertSWIGPointerObj_T (const char *TypeName, PyObject *obj, void **ptr, int flags)
int createSWIGPointerObj_T (const char *TypeName, void *obj, PyObject **ptr, int own)
int getSWIGPointerTypeObj_T (const char *TypeName, PyTypeObject **ptr)
Function Documentation
cleanupSWIG_T()
void Swig_python::cleanupSWIG_T (const char * TypeName)
References cleanupSWIG_T().
Referenced by Base::InterpreterSingleton::cleanupSWIG(), and cleanupSWIG_T().
convertSWIGPointerObj_T()
int Swig_python::convertSWIGPointerObj_T (const char * TypeName, PyObject * obj, void ** ptr, int flags)
References convertSWIGPointerObj_T().
Referenced by Base::InterpreterSingleton::convertSWIGPointerObj(), and convertSWIGPointerObj_T().
createSWIGPointerObj_T()
int Swig_python::createSWIGPointerObj_T (const char * TypeName, void * obj, PyObject ** ptr, int own)
References createSWIGPointerObj_T().
Referenced by Base::InterpreterSingleton::createSWIGPointerObj(), and createSWIGPointerObj_T().
getSWIGPointerTypeObj_T()
int Swig_python::getSWIGPointerTypeObj_T (const char * TypeName, PyTypeObject ** ptr)
References getSWIGPointerTypeObj_T().
Referenced by Base::InterpreterSingleton::getSWIGPointerTypeObj(), and getSWIGPointerTypeObj_T().