FreeCAD: PartGui::Ui_DlgSettings3DViewPart Class Reference
PartGui::Ui_DlgSettings3DViewPart Class Reference
#include <ui_DlgSettings3DViewPart.h>
Public Member Functions
void retranslateUi (QWidget *PartGui__DlgSettings3DViewPart)
void setupUi (QWidget *PartGui__DlgSettings3DViewPart)
Public Attributes
QGridLayout * gridLayout
QGridLayout * gridLayout1
QGridLayout * gridLayout2
QGroupBox * GroupBox12
QLabel * label
Gui::PrefDoubleSpinBox * maxAngularDeflection
Gui::PrefDoubleSpinBox * maxDeviation
QSpacerItem * spacerItem
QLabel * textLabel1
Member Function Documentation
retranslateUi()
void PartGui::Ui_DlgSettings3DViewPart::retranslateUi (QWidget * PartGui__DlgSettings3DViewPart)
References GroupBox12, maxAngularDeflection, maxDeviation, textLabel1, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void PartGui::Ui_DlgSettings3DViewPart::setupUi (QWidget * PartGui__DlgSettings3DViewPart)
References gridLayout, gridLayout1, gridLayout2, GroupBox12, maxAngularDeflection, maxDeviation, retranslateUi(), spacerItem, and textLabel1.
Member Data Documentation
gridLayout
QGridLayout* PartGui::Ui_DlgSettings3DViewPart::gridLayout
Referenced by setupUi().
gridLayout1
QGridLayout* PartGui::Ui_DlgSettings3DViewPart::gridLayout1
Referenced by setupUi().
gridLayout2
QGridLayout* PartGui::Ui_DlgSettings3DViewPart::gridLayout2
Referenced by setupUi().
GroupBox12
QGroupBox* PartGui::Ui_DlgSettings3DViewPart::GroupBox12
Referenced by retranslateUi(), and setupUi().
label
QLabel* PartGui::Ui_DlgSettings3DViewPart::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
maxAngularDeflection
Gui::PrefDoubleSpinBox* PartGui::Ui_DlgSettings3DViewPart::maxAngularDeflection
Referenced by retranslateUi(), and setupUi().
maxDeviation
Gui::PrefDoubleSpinBox* PartGui::Ui_DlgSettings3DViewPart::maxDeviation
Referenced by retranslateUi(), and setupUi().
spacerItem
QSpacerItem* PartGui::Ui_DlgSettings3DViewPart::spacerItem
Referenced by setupUi().
textLabel1
QLabel* PartGui::Ui_DlgSettings3DViewPart::textLabel1
Referenced by retranslateUi(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Part/Gui/ui_DlgSettings3DViewPart.h