FreeCAD: ArchComponent.SelectionTaskPanel Class Reference
ArchComponent.SelectionTaskPanel Class Reference
Public Member Functions
def getStandardButtons (self)
def reject (self)
Public Attributes
baseform
Detailed Description
A simple TaskPanel to wait for a selection.
Typically used in conjunction with ArchComponent.ArchSelectionObserver.
Member Function Documentation
getStandardButtons()
def ArchComponent.SelectionTaskPanel.getStandardButtons (self)
Adds the cancel button.
reject()
def ArchComponent.SelectionTaskPanel.reject (self)
The method run when the user selects the cancel button.
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel.accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel.action(), femexamples.examplesgui.FemExamples.clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary.toolEdit().
Member Data Documentation
baseform
ArchComponent.SelectionTaskPanel.baseform
Referenced by ArchComponent.ComponentTaskPanel.retranslateUi(), and ArchComponent.ComponentTaskPanel.update().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Arch/ArchComponent.py