FreeCAD: TechDraw::edgeVisitor Class Reference
TechDraw::edgeVisitor Class Reference
#include <EdgeWalker.h>
Public Member Functions
void begin_face ()
void end_face ()
ewWireList getResult (void)
template<typename Edge >
void next_edge (Edge e)
void setGraph (graph &g)
Member Function Documentation
begin_face()
void edgeVisitor::begin_face ()
References TechDraw::ewWire::clear().
end_face()
void edgeVisitor::end_face ()
References TechDraw::ewWireList::push_back().
getResult()
TechDraw::ewWireList edgeVisitor::getResult (void)
Referenced by TechDraw::EdgeWalker::getResult(), TechDraw::EdgeWalker::getResultNoDups(), and TechDraw::EdgeWalker::getResultWires().
next_edge()
template<typename Edge > void edgeVisitor::next_edge (Edge e)
References TechDraw::WalkerEdge::ed, TechDraw::WalkerEdge::idx, TechDraw::ewWire::push_back(), TechDraw::WalkerEdge::v1, and TechDraw::WalkerEdge::v2.
setGraph()
void edgeVisitor::setGraph (TechDraw::graph & g)
Referenced by TechDraw::EdgeWalker::perform().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/App/EdgeWalker.h
FreeCAD/src/Mod/TechDraw/App/EdgeWalker.cpp