FreeCAD: Gui::PointMarker Class Reference
Gui::PointMarker Class Reference
#include <ViewProviderMeasureDistance.h>
Public Member Functions
void addPoint (const SbVec3f &)
int countPoints () const
PointMarker (View3DInventorViewer *view)
~PointMarker ()
Protected Member Functions
void customEvent (QEvent *e)
Constructor & Destructor Documentation
PointMarker()
PointMarker::PointMarker (View3DInventorViewer * view)
References Gui::View3DInventorViewer::addViewProvider().
~PointMarker()
PointMarker::~PointMarker ()
References Gui::View3DInventorViewer::removeViewProvider().
Member Function Documentation
addPoint()
void PointMarker::addPoint (const SbVec3f & pt)
References countPoints(), Gui::ViewProviderPointMarker::pCoords, and Gui::ViewProviderPointMarker::pMarker.
Referenced by draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_edit.Edit::evaluate_menu_action(), Gui::ViewProviderMeasureDistance::measureDistanceCallback(), and draftguitools.gui_stretch.Stretch::numericInput().
countPoints()
int PointMarker::countPoints () const
References Gui::ViewProviderPointMarker::pCoords.
Referenced by addPoint(), and Gui::ViewProviderMeasureDistance::measureDistanceCallback().
customEvent()
void PointMarker::customEvent (QEvent * e) protected
References Gui::Application::activeDocument(), App::MeasureDistance::Distance, Base::Persistence::getClassTypeId(), Base::Quantity::getUserString(), App::PropertyQuantity::getValue(), Gui::Application::Instance, App::DocumentObject::Label, Base::Unit::Length, App::MeasureDistance::P1, App::MeasureDistance::P2, Gui::ViewProviderPointMarker::pCoords, draftutils.translate::QT_TRANSLATE_NOOP, App::PropertyVector::setValue(), and App::PropertyString::setValue().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/ViewProviderMeasureDistance.h
Sources/FreeCAD/src/Gui/ViewProviderMeasureDistance.cpp
Sources/FreeCAD/src/Mod/Fem/Gui/TaskPostBoxes.cpp