FreeCAD: SketcherGui::ConstraintView Class Reference
SketcherGui::ConstraintView Class Reference
#include <TaskSketcherConstraints.h>
Signals
void emitCenterSelectedItems ()
void emitHideSelection3DVisibility ()
void emitShowSelection3DVisibility ()
void onUpdateActiveStatus (QListWidgetItem *item, bool status)
void onUpdateDrivingStatus (QListWidgetItem *item, bool status)
Public Member Functions
ConstraintView (QWidget *parent=nullptr)
~ConstraintView ()
Protected Slots
void centerSelectedItems ()
void deleteSelectedItems ()
void doSelectConstraints ()
void hideConstraints ()
void modifyCurrentItem ()
void renameCurrentItem ()
void showConstraints ()
void swapNamedOfSelectedItems ()
void updateActiveStatus ()
void updateDrivingStatus ()
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *event)
Constructor & Destructor Documentation
ConstraintView()
ConstraintView::ConstraintView (QWidget * parent = nullptr) explicit
~ConstraintView()
ConstraintView::~ConstraintView ()
Member Function Documentation
centerSelectedItems
void ConstraintView::centerSelectedItems () protected slot
References emitCenterSelectedItems().
Referenced by contextMenuEvent().
contextMenuEvent()
void ConstraintView::contextMenuEvent (QContextMenuEvent * event) protected
References Gui::Application::activeDocument(), Gui::SelectionSingleton::addSelections(), centerSelectedItems(), Gui::SelectionSingleton::clearSelection(), deleteSelectedItems(), doSelectConstraints(), Sketcher::PropertyConstraintList::getConstraintName(), hideConstraints(), Gui::Application::Instance, ConstraintItem::isActive(), ConstraintItem::isDimensional(), ConstraintItem::isEnforceable(), modifyCurrentItem(), SketcherGui::ReleaseHandler(), renameCurrentItem(), Gui::Selection(), showConstraints(), swapNamedOfSelectedItems(), updateActiveStatus(), and updateDrivingStatus().
deleteSelectedItems
void ConstraintView::deleteSelectedItems () protected slot
References App::Application::getActiveDocument(), App::GetApplication(), Gui::SelectionSingleton::getSelectionEx(), Gui::Application::getViewProvider(), Gui::Application::Instance, Gui::ViewProvider::onDelete(), and Gui::Selection().
Referenced by contextMenuEvent().
doSelectConstraints
void SketcherGui::ConstraintView::doSelectConstraints () protected slot
Referenced by contextMenuEvent().
emitCenterSelectedItems
void SketcherGui::ConstraintView::emitCenterSelectedItems () signal
Referenced by centerSelectedItems().
emitHideSelection3DVisibility
void SketcherGui::ConstraintView::emitHideSelection3DVisibility () signal
Referenced by hideConstraints().
emitShowSelection3DVisibility
void SketcherGui::ConstraintView::emitShowSelection3DVisibility () signal
Referenced by showConstraints().
hideConstraints
void ConstraintView::hideConstraints () protected slot
References emitHideSelection3DVisibility().
Referenced by contextMenuEvent().
modifyCurrentItem
void ConstraintView::modifyCurrentItem () protected slot
Referenced by contextMenuEvent().
onUpdateActiveStatus
void SketcherGui::ConstraintView::onUpdateActiveStatus (QListWidgetItem * item, bool status) signal
Referenced by updateActiveStatus().
onUpdateDrivingStatus
void SketcherGui::ConstraintView::onUpdateDrivingStatus (QListWidgetItem * item, bool status) signal
renameCurrentItem
void ConstraintView::renameCurrentItem () protected slot
Referenced by contextMenuEvent().
showConstraints
void ConstraintView::showConstraints () protected slot
References emitShowSelection3DVisibility().
Referenced by contextMenuEvent().
swapNamedOfSelectedItems
void ConstraintView::swapNamedOfSelectedItems () protected slot
References Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), ConstraintItem::ConstraintNbr, Sketcher::SketchObject::Constraints, Base::Tools::escapedUnicodeFromUtf8(), Gui::MainWindow::getInstance(), Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, and ConstraintItem::sketch.
Referenced by contextMenuEvent().
updateActiveStatus
void ConstraintView::updateActiveStatus () protected slot
References ConstraintItem::isActive(), and onUpdateActiveStatus().
Referenced by contextMenuEvent().
updateDrivingStatus
void ConstraintView::updateDrivingStatus () protected slot
References ConstraintItem::isDriving().
Referenced by contextMenuEvent().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/Gui/TaskSketcherConstraints.h
FreeCAD/src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp