FreeCAD: SMESHDS_Document Class Reference
SMESHDS_Document Class Reference
#include <SMESHDS_Document.hxx>
Public Member Functions
void AddHypothesis (SMESHDS_Hypothesis *H)
SMESHDS_Hypothesis * GetHypothesis (int HypID)
SMESHDS_Mesh * GetMesh (int MeshID)
void InitHypothesisIterator ()
void InitMeshesIterator ()
bool MoreHypothesis ()
bool MoreMesh ()
int NbHypothesis ()
int NbMeshes ()
SMESHDS_Mesh * NewMesh (bool theIsEmbeddedMode, int MeshID)
SMESHDS_Hypothesis * NextHypothesis ()
SMESHDS_Mesh * NextMesh ()
void RemoveHypothesis (int HypID)
void RemoveMesh (int MeshID)
SMESHDS_Document (int UserID)
~SMESHDS_Document ()
Constructor & Destructor Documentation
SMESHDS_Document()
SMESHDS_Document::SMESHDS_Document (int UserID)
~SMESHDS_Document()
SMESHDS_Document::~SMESHDS_Document ()
References InitMeshesIterator(), MoreMesh(), and NextMesh().
Member Function Documentation
AddHypothesis()
void SMESHDS_Document::AddHypothesis (SMESHDS_Hypothesis * H)
References SMESHDS_Hypothesis::GetID().
GetHypothesis()
SMESHDS_Hypothesis * SMESHDS_Document::GetHypothesis (int HypID)
GetMesh()
SMESHDS_Mesh * SMESHDS_Document::GetMesh (int MeshID)
InitHypothesisIterator()
void SMESHDS_Document::InitHypothesisIterator ()
InitMeshesIterator()
void SMESHDS_Document::InitMeshesIterator ()
Referenced by ~SMESHDS_Document().
MoreHypothesis()
bool SMESHDS_Document::MoreHypothesis ()
MoreMesh()
bool SMESHDS_Document::MoreMesh ()
Referenced by ~SMESHDS_Document().
NbHypothesis()
int SMESHDS_Document::NbHypothesis ()
NbMeshes()
int SMESHDS_Document::NbMeshes ()
NewMesh()
SMESHDS_Mesh * SMESHDS_Document::NewMesh (bool theIsEmbeddedMode, int MeshID)
Referenced by SMESH_Mesh::SMESH_Mesh().
NextHypothesis()
SMESHDS_Hypothesis * SMESHDS_Document::NextHypothesis ()
NextMesh()
SMESHDS_Mesh * SMESHDS_Document::NextMesh ()
Referenced by ~SMESHDS_Document().
RemoveHypothesis()
void SMESHDS_Document::RemoveHypothesis (int HypID)
RemoveMesh()
void SMESHDS_Document::RemoveMesh (int MeshID)
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESHDS_Document.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESHDS/SMESHDS_Document.cpp