FreeCAD: Base::Uuid Class Reference
Base::Uuid Class Reference
Creates a Uuid.
#include <Uuid.h>
Public Member Functions
const std::string & getValue () const
bool operator< (const Uuid &other) const
Uuid & operator= (const Uuid &)=default
bool operator== (const Uuid &other) const
void setValue (const char *sString)
void setValue (const std::string &sString)
Uuid ()
Construction.
Uuid (const Uuid &)=default
virtual ~Uuid ()
Destruction.
Static Public Member Functions
static std::string createUuid ()
Detailed Description
Creates a Uuid.
Author
Jürgen Riegel
Constructor & Destructor Documentation
Uuid() [1/2]
Uuid::Uuid ()
Construction.
A constructor.
A more elaborate description of the constructor.
References createUuid().
Referenced by createUuid().
Uuid() [2/2]
Base::Uuid::Uuid (const Uuid &) default
~Uuid()
Uuid::~Uuid () virtual
Destruction.
A destructor.
A more elaborate description of the destructor.
Member Function Documentation
createUuid()
std::string Uuid::createUuid () static
References Uuid().
Referenced by App::Document::exportObjects(), App::Document::importObjects(), Sandbox::DocumentSaverThread::run(), App::Document::saveToFile(), and Uuid().
getValue()
const std::string & Uuid::getValue () const
Referenced by App::PropertyFileIncluded::getUniqueFileName().
operator<()
bool Base::Uuid::operator< (const Uuid & other) const
operator=()
Uuid & Base::Uuid::operator= (const Uuid &) default
operator==()
bool Base::Uuid::operator== (const Uuid & other) const
setValue() [1/2]
void Uuid::setValue (const char * sString)
Referenced by setValue().
setValue() [2/2]
void Uuid::setValue (const std::string & sString)
References setValue().
The documentation for this class was generated from the following files:
FreeCAD/src/Base/Uuid.h
FreeCAD/src/Base/Uuid.cpp