FreeCAD: MeshGui::ViewProviderMesh Class Reference
MeshGui::ViewProviderMesh Class Reference
The ViewProviderMesh class offers the visualization of the mesh data structure and many algorithms to work on or edit the mesh.
#include <ViewProvider.h>
Public Member Functions
virtual void attach (App::DocumentObject *)
Extracts the mesh data from the feature pcFeature and creates an Inventor node SoNode with these data.
void exportMesh (const char *filename, const char *fmt=nullptr) const
bool exportToVrml (const char *filename, const MeshCore::Material &, bool binary=false) const
virtual std::vector< std::string > getDisplayModes () const
returns a list of all possible modes
Gui::SoFCSelection * getHighlightNode () const
virtual QIcon getIcon () const
deliver the icon shown in the tree view
PyObject * getPyObject ()
Get the python wrapper for that ViewProvider.
virtual void setDisplayMode (const char *ModeName)
Sets the correct display mode.
void setupContextMenu (QMenu *, QObject *, const char *)
set up the context-menu with the supported edit modes
virtual void updateData (const App::Property *)
virtual bool useNewSelectionModel () const
indicates if the ViewProvider use the new Selection model
ViewProviderMesh ()
virtual ~ViewProviderMesh ()
Public Member Functions inherited from Gui::ViewProviderGeometryObject
void attach (App::DocumentObject *pcObject)
Attaches the document object to this view provider.
SoPickedPoint * getPickedPoint (const SbVec2s &pos, const View3DInventorViewer &viewer) const
This method is provided for convenience and does basically the same as getPickedPoints() unless that only the closest point to the camera will be picked.
SoPickedPointList getPickedPoints (const SbVec2s &pos, const View3DInventorViewer &viewer, bool pickAll=false) const
Returns a list of picked points from the geometry under getRoot().
bool isSelectable (void) const
void updateData (const App::Property *)
ViewProviderGeometryObject ()
constructor.
virtual ~ViewProviderGeometryObject ()
destructor.
virtual void showBoundingBox (bool)
Public Member Functions inherited from Gui::ViewProviderDragger
ViewProviderDragger ()
constructor.
virtual ~ViewProviderDragger ()
destructor.
virtual ViewProvider * startEditing (int ModNum=0) override
Public Member Functions inherited from Gui::ViewProviderDocumentObject
virtual void attach (App::DocumentObject *pcObject)
virtual bool canDelete (App::DocumentObject *obj) const override
Asks the view provider if the given object can be deleted.
virtual bool canDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const override
Query object dropping with full qualified name.
virtual void forceUpdate (bool enable=true)
virtual bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const override
return the coin node detail and path to the node of the subname
Gui::Document * getDocument () const
Get the GUI document to this ViewProvider object.
virtual bool getElementPicked (const SoPickedPoint *, std::string &subname) const override
return a hit element given the picked point which contains the full node path
App::DocumentObject * getObject (void) const
Get the object of this ViewProvider object.
PyObject * getPyObject () override
Get the python wrapper for that ViewProvider.
virtual void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const override
Get a list of TaskBoxes associated with this object.
virtual const char * getTransactionText () const override
Is called by the tree if the user double clicks on the object.
virtual void hide (void) override
Hide the object in the view.
virtual bool isUpdateForced () const
virtual void reattach (App::DocumentObject *)
virtual int replaceObject (App::DocumentObject *, App::DocumentObject *) override
Replace an object to the view provider by drag and drop.
void setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
virtual void show (void) override
Show the object in the view.
virtual bool showInTree () const override
Tell the tree view if this object should appear there.
virtual void update (const App::Property *) override
update the content of the ViewProvider this method have to implement the recalculation of the ViewProvider.
void updateView ()
Run a redraw.
ViewProviderDocumentObject ()
constructor.
virtual ~ViewProviderDocumentObject ()
destructor.
virtual void startRestoring ()
virtual void finishRestoring ()
virtual bool removeDynamicProperty (const char *prop) override
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
virtual ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=nullptr, bool recursive=false) const
Return the linked view object.
virtual std::string getFullName () const override
virtual bool allowOverride (const App::DocumentObject &) const
Allow this class to be used as an override for the original view provider of the given object.
void setShowable (bool enable)
bool isShowable () const
void startDefaultEditMode ()
Start the edit mode with ViewProvider::Default.
Public Member Functions inherited from Gui::ViewProvider
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual std::vector< App::DocumentObject * > claimChildren3D (void) const
deliver the children belonging to this object this method is used to deliver the objects to the 3DView which should be grouped under its scene graph.
SoSeparator * getAnnotation (void)
virtual SoSeparator * getBackRoot (void) const
virtual SoGroup * getChildRoot (void) const
virtual SoSeparator * getFrontRoot (void) const
SoSwitch * getModeSwitch (void) const
virtual SoSeparator * getRoot (void) const
SoTransform * getTransformNode () const
ViewProvider ()
constructor.
virtual ~ViewProvider ()
destructor.
virtual std::string getElement (const SoDetail *) const
return a hit element to the selection path or 0
virtual SoDetail * getDetail (const char *) const
return the coin node detail of the subelement
int partialRender (const std::vector< std::string > &subelements, bool clear)
partial rendering setup
virtual std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const
virtual std::vector< Base::Vector3d > getSelectionShape (const char *Element) const
return the highlight lines for a given element or the whole shape
Base::BoundBox3d getBoundingBox (const char *subname=nullptr, bool transform=true, MDIView *view=nullptr) const
Return the bound box of this view object.
virtual bool onDelete (const std::vector< std::string > &subNames)
Get called if the object is about to get deleted.
virtual void beforeDelete ()
Called before deletion.
virtual bool canDragObjects () const
Check whether children can be removed from the view provider by drag and drop.
virtual bool canDragObject (App::DocumentObject *) const
Check whether the object can be removed from the view provider by drag and drop.
virtual void dragObject (App::DocumentObject *)
Remove a child from the view provider by drag and drop.
virtual bool canDropObjects () const
Check whether objects can be added to the view provider by drag and drop or drop only.
virtual bool canDropObject (App::DocumentObject *) const
Check whether the object can be dropped to the view provider by drag and drop or drop only.
virtual bool canDragAndDropObject (App::DocumentObject *) const
Return false to force drop only operation for a given object.
virtual void dropObject (App::DocumentObject *)
Add an object to the view provider by drag and drop.
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
Add an object with full qualified name to the view provider by drag and drop.
virtual bool canRemoveChildrenFromRoot () const
Tell the tree view to remove children items from the tree root.
std::string getActiveDisplayMode (void) const
virtual const char * getDefaultDisplayMode () const
get the default display mode
virtual bool isShow (void) const
checks whether the view provider is visible or not
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
virtual void setOverrideMode (const std::string &mode)
Overrides the display mode with mode.
const std::string getOverrideMode ()
virtual bool keyPressed (bool pressed, int key)
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
virtual bool mouseMove (const SbVec2s &cursorPos, View3DInventorViewer *viewer)
is called when the provider is in edit and the mouse is moved
virtual bool mouseButtonPressed (int button, bool pressed, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
is called when the Provider is in edit and the mouse is clicked
virtual bool mouseWheelEvent (int delta, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
bool isEditing () const
void finishEditing ()
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
virtual QIcon mergeColorfulOverlayIcons (const QIcon &orig) const
virtual std::vector< App::DocumentObject * > claimChildren (void) const
deliver the children belonging to this object this method is used to deliver the objects to the tree framework which should be grouped under its label.
virtual std::map< std::string, App::Color > getElementColors (const char *element=nullptr) const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
virtual MDIView * getMDIView () const
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
virtual const char * detachFromDocument ()
virtual bool isAttachedToDocument () const
TransactionalObject (void)
Constructor.
virtual ~TransactionalObject ()
Public Member Functions inherited from App::ExtensionContainer
ExtensionIterator extensionBegin ()
ExtensionContainer ()
ExtensionIterator extensionEnd ()
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
void registerExtension (Base::Type extension, App::Extension *ext)
virtual ~ExtensionContainer ()
virtual Property * getPropertyByName (const char *name) const override
find a property by its name
virtual const char * getPropertyName (const Property *prop) const override
get the name of a property
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
virtual void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
virtual short getPropertyType (const Property *prop) const override
get the Type of a Property
virtual short getPropertyType (const char *name) const override
get the Type of a named Property
virtual const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
virtual const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
Public Member Functions inherited from App::PropertyContainer
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false)
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual void editProperty (const char *)
virtual App::Property * getDynamicPropertyByName (const char *name) const
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual std::string getFullName () const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Property * getPropertyByName (const char *name) const
find a property by its name
virtual const char * getPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * getPropertyGroup (const Property *prop) const
get the Group of a Property
virtual void getPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual const char * getPropertyName (const Property *prop) const
get the name of a property
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
const char * getPropertyPrefix () const
virtual short getPropertyType (const char *name) const
get the Type of a named Property
virtual short getPropertyType (const Property *prop) const
get the Type of a Property
bool isHidden (const char *name) const
check if the named property is hidden
bool isHidden (const Property *prop) const
check if the property is hidden
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isReadOnly (const Property *prop) const
check if the property is read-only
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus)
PropertyContainer ()
A constructor.
virtual bool removeDynamicProperty (const char *name)
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
void setPropertyPrefix (const char *prefix)
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
virtual ~PropertyContainer ()
A destructor.
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Attributes
App::PropertyBool Coloring
App::PropertyFloatConstraint CreaseAngle
App::PropertyEnumeration Lighting
App::PropertyColor LineColor
App::PropertyPercent LineTransparency
App::PropertyFloatConstraint LineWidth
App::PropertyBool OpenEdges
App::PropertyFloatConstraint PointSize
Public Attributes inherited from Gui::ViewProviderGeometryObject
App::PropertyBool BoundingBox
App::PropertyBool Selectable
App::PropertyColor ShapeColor
App::PropertyMaterial ShapeMaterial
App::PropertyPercent Transparency
Public Attributes inherited from Gui::ViewProviderDocumentObject
App::PropertyEnumeration DisplayMode
App::PropertyEnumeration OnTopWhenSelected
App::PropertyEnumeration SelectionStyle
App::PropertyBool ShowInTree
App::PropertyBool Visibility
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
Editing
enum class HighlighMode { }
HighlighMode highlightMode
Gui::SoFCSelection * pcHighlight
SoGroup * pcShapeGroup
SoDrawStyle * pcLineStyle
SoDrawStyle * pcPointStyle
SoSeparator * pcOpenEdge
SoBaseColor * pOpenColor
SoMaterial * pLineColor
SoShapeHints * pShapeHints
SoMaterialBinding * pcMatBinding
bool doubleClicked ()
is called by the tree if the user double clicks on the object
bool isFacetSelected (Mesh::FacetIndex facet)
void selectComponent (Mesh::FacetIndex facet)
void deselectComponent (Mesh::FacetIndex facet)
void selectFacet (Mesh::FacetIndex facet)
void deselectFacet (Mesh::FacetIndex facet)
void setSelection (const std::vector< Mesh::FacetIndex > &)
void addSelection (const std::vector< Mesh::FacetIndex > &)
void removeSelection (const std::vector< Mesh::FacetIndex > &)
void invertSelection ()
void clearSelection ()
void deleteSelection ()
bool hasSelection () const
void getFacetsFromPolygon (const std::vector< SbVec2f > &picked, const Base::ViewProjMethod &proj, SbBool inner, std::vector< Mesh::FacetIndex > &indices) const
std::vector< Mesh::FacetIndex > getFacetsOfRegion (const SbViewportRegion &, const SbViewportRegion &, SoCamera *) const
std::vector< Mesh::FacetIndex > getVisibleFacetsAfterZoom (const SbBox2s &, const SbViewportRegion &, SoCamera *) const
std::vector< Mesh::FacetIndex > getVisibleFacets (const SbViewportRegion &, SoCamera *) const
virtual void cutMesh (const std::vector< SbVec2f > &picked, const Base::ViewProjMethod &proj, SbBool inner)
virtual void trimMesh (const std::vector< SbVec2f > &picked, const Base::ViewProjMethod &proj, SbBool inner)
virtual void appendFacets (const std::vector< Mesh::FacetIndex > &)
virtual void removeFacets (const std::vector< Mesh::FacetIndex > &)
void setFacetTransparency (const std::vector< float > &)
void resetFacetTransparency ()
void highlightSegments (const std::vector< App::Color > &)
bool setEdit (int ModNum)
Sets the edit mode.
void unsetEdit (int ModNum)
Unsets the edit mode.
void onChanged (const App::Property *prop)
get called by the container whenever a property has been changed
virtual void showOpenEdges (bool)
void setOpenEdgeColorFrom (const App::Color &col)
virtual void splitMesh (const MeshCore::MeshKernel &toolMesh, const Base::Vector3f &normal, SbBool inner)
virtual void segmentMesh (const MeshCore::MeshKernel &toolMesh, const Base::Vector3f &normal, SbBool inner)
virtual void faceInfo (Mesh::FacetIndex facet)
virtual void fillHole (Mesh::FacetIndex facet)
virtual void selectArea (short, short, short, short, const SbViewportRegion &, SoCamera *)
virtual void highlightSelection ()
virtual void unhighlightSelection ()
void highlightComponents ()
void setHighlightedComponents (bool)
void highlightSegments ()
void setHighlightedSegments (bool)
void setHighlightedColors (bool)
void highlightColors ()
bool canHighlightColors () const
App::PropertyColorList * getColorProperty () const
void tryColorPerVertexOrFace (bool)
void setColorPerVertex (const App::PropertyColorList *)
void setColorPerFace (const App::PropertyColorList *)
virtual SoShape * getShapeNode () const
virtual SoNode * getCoordNode () const
static void faceInfoCallback (void *ud, SoEventCallback *n)
static void fillHoleCallback (void *ud, SoEventCallback *n)
static void markPartCallback (void *ud, SoEventCallback *n)
static void clipMeshCallback (void *ud, SoEventCallback *n)
static void trimMeshCallback (void *ud, SoEventCallback *n)
static void partMeshCallback (void *ud, SoEventCallback *n)
static void segmMeshCallback (void *ud, SoEventCallback *n)
static void selectGLCallback (void *ud, SoEventCallback *n)
static bool createToolMesh (const std::vector< SbVec2f > &rclPoly, const SbViewVolume &vol, const Base::Vector3f &rcNormal, std::vector< MeshCore::MeshGeomFacet > &)
Creates a tool mesh from the previous picked polygon on the viewer.
Additional Inherited Members
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0 , Transform , Cutting , Color }
Public Types inherited from App::ExtensionContainer
typedef std::map< Base::Type, App::Extension * >::iterator ExtensionIterator
Static Public Member Functions inherited from Gui::ViewProviderDragger
static void updateTransform (const Base::Placement &from, SoTransform *to)
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Protected Member Functions inherited from Gui::ViewProviderGeometryObject
void setSelectable (bool Selectable=true)
virtual unsigned long getBoundColor () const
Protected Member Functions inherited from Gui::ViewProviderDragger
void setEditViewer (View3DInventorViewer *, int ModNum) override
adjust viewer settings when editing a view provider
void unsetEditViewer (View3DInventorViewer *) override
restores viewer settings when leaving editing mode
Protected Member Functions inherited from Gui::ViewProviderDocumentObject
virtual bool isAttachedToDocument () const override
virtual const char * detachFromDocument () override
virtual void onPropertyStatusChanged (const App::Property &prop, unsigned long oldStatus) override
get called when a property status has changed
virtual void setModeSwitch () override
Turn on mode switch.
void addDefaultAction (QMenu *, const QString &)
Adds a menu item and bind it with startDefaultEditMode().
Gui::MDIView * getActiveView () const
Gui::MDIView * getEditingView () const
Gui::MDIView * getInventorView () const
Gui::MDIView * getViewOfNode (SoNode *node) const
virtual void onBeforeChange (const App::Property *prop) override
get called before the value is changed
SoNode * findFrontRootOfType (const SoType &type) const
Searches in all view providers that are attached to an object that is part of the same document as the object this view provider is attached to for an front root of type.
Protected Member Functions inherited from Gui::ViewProvider
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
virtual QIcon mergeGreyableOverlayIcons (const QIcon &orig) const
bool checkRecursion (SoNode *)
Helper method to check that the node is valid, i.e.
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
Helper method to get picked entities while editing.
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
Helper method to get picked entities while editing.
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData (void) const
virtual void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container.
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container.
virtual void onBeforeChange (const Property *)
get called before the value is changed
virtual void onChanged (const Property *)
get called by the container when a property has changed
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr (void)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::ViewProviderGeometryObject
SoMaterial * pcShapeMaterial
SoFCBoundingBox * pcBoundingBox
SoSwitch * pcBoundSwitch
SoBaseColor * pcBoundColor
Protected Attributes inherited from Gui::ViewProviderDragger
SoFCCSysDragger * csysDragger = nullptr
Protected Attributes inherited from Gui::ViewProviderDocumentObject
App::DocumentObject * pcObject
Gui::Document * pcDocument
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation
The root separator for annotations.
ViewProviderPy * pyViewObject
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Detailed Description
The ViewProviderMesh class offers the visualization of the mesh data structure and many algorithms to work on or edit the mesh.
Author
Werner Mayer
Member Enumeration Documentation
HighlighMode
enum class MeshGui::ViewProviderMesh::HighlighMode strong protected
Enumerator
Component
Segment
Color
Constructor & Destructor Documentation
ViewProviderMesh()
ViewProviderMesh::ViewProviderMesh ()
References Gui::ViewProviderBuilder::createSelection(), ParameterGrp::GetBool(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), App::Color::getPackedValue(), ParameterGrp::GetUnsigned(), App::Property::Hidden, App::Prop_None, and Gui::SoFCSelection::SEL_OFF.
~ViewProviderMesh()
ViewProviderMesh::~ViewProviderMesh () virtual
References pcHighlight, pcLineStyle, pcMatBinding, pcPointStyle, pcShapeGroup, pLineColor, pOpenColor, and pShapeHints.
Member Function Documentation
addSelection()
void ViewProviderMesh::addSelection (const std::vector< Mesh::FacetIndex > & indices)
References Mesh::MeshObject::addFacetsToSelection(), highlightSelection(), and Gui::ViewProviderDocumentObject::pcObject.
Referenced by ReverseEngineeringGui::SegmentationManual::Private::findGeometry().
appendFacets()
void ViewProviderMesh::appendFacets (const std::vector< Mesh::FacetIndex > &) virtual
The triangles with the passed indices are already added to the mesh.
attach()
void ViewProviderMesh::attach (App::DocumentObject * pcFeat) virtual
Extracts the mesh data from the feature pcFeature and creates an Inventor node SoNode with these data.
Reimplemented from Gui::ViewProviderGeometryObject.
Reimplemented in MeshGui::ViewProviderIndexedFaceSet, MeshGui::ViewProviderMeshTransform, MeshGui::ViewProviderMeshTransformDemolding, MeshGui::ViewProviderMeshObject, and MeshGui::ViewProviderMeshFaceSet.
References Gui::ViewProvider::addDisplayMaskMode(), Coloring, Gui::SoFCSelection::documentName, getColorProperty(), App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::Property::Hidden, Gui::SoFCSelection::objectName, pcHighlight, pcLineStyle, pcMatBinding, pcPointStyle, pcShapeGroup, Gui::ViewProviderGeometryObject::pcShapeMaterial, pLineColor, pShapeHints, App::Property::setStatus(), and Gui::SoFCSelection::subElementName.
Referenced by MeshGui::ViewProviderIndexedFaceSet::attach(), MeshGui::ViewProviderMeshTransform::attach(), MeshGui::ViewProviderMeshTransformDemolding::attach(), MeshGui::ViewProviderMeshObject::attach(), and MeshGui::ViewProviderMeshFaceSet::attach().
canHighlightColors()
bool ViewProviderMesh::canHighlightColors () const protected
References Mesh::MeshObject::countFacets(), Mesh::MeshObject::countPoints(), App::ExtensionContainer::getPropertyByName(), App::PropertyListsT< T, ListT, ParentT >::getSize(), and Gui::ViewProviderDocumentObject::pcObject.
Referenced by setupContextMenu().
clearSelection()
void ViewProviderMesh::clearSelection ()
References Mesh::MeshObject::clearFacetSelection(), Gui::ViewProviderDocumentObject::pcObject, and unhighlightSelection().
Referenced by markPartCallback().
clipMeshCallback()
void ViewProviderMesh::clipMeshCallback (void * ud, SoEventCallback * n) static
References Gui::Document::abortCommand(), Gui::Application::activeDocument(), draftgeoutils.faces::bind(), clipMeshCallback(), Gui::Document::commitCommand(), MeshGui::MeshSplit::cutMesh(), cutMesh(), Gui::ViewProvider::finishEditing(), Base::Persistence::getClassTypeId(), Gui::ViewProvider::getEditingMode(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::Instance, Gui::Document::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, and Base::ViewProjMethod::setTransform().
Referenced by clipMeshCallback().
createToolMesh()
bool ViewProviderMesh::createToolMesh (const std::vector< SbVec2f > & rclPoly, const SbViewVolume & vol, const Base::Vector3f & rcNormal, std::vector< MeshCore::MeshGeomFacet > & aFaces) static
Creates a tool mesh from the previous picked polygon on the viewer.
References MeshCore::MeshGeomFacet::CalcNormal(), MeshCore::AbstractPolygonTriangulator::GetFacets(), MeshCore::MeshGeomFacet::GetNormal(), MeshCore::AbstractPolygonTriangulator::SetPolygon(), and MeshCore::AbstractPolygonTriangulator::TriangulatePolygon().
Referenced by MeshGui::ViewProviderMeshNode::handleEvent(), partMeshCallback(), and segmMeshCallback().
cutMesh()
void ViewProviderMesh::cutMesh (const std::vector< SbVec2f > & picked, const Base::ViewProjMethod & proj, SbBool inner) virtual
References getFacetsFromPolygon(), and removeFacets().
Referenced by clipMeshCallback(), and MeshGui::MeshSplit::cutMesh().
deleteSelection()
void ViewProviderMesh::deleteSelection ()
References Mesh::MeshObject::clearFacetSelection(), Mesh::MeshObject::getFacetsFromSelection(), Mesh::PropertyMeshKernel::getValue(), Gui::ViewProviderDocumentObject::pcObject, removeFacets(), and unhighlightSelection().
Referenced by markPartCallback().
deselectComponent()
void ViewProviderMesh::deselectComponent (Mesh::FacetIndex facet)
References Mesh::MeshObject::getKernel(), Mesh::MeshObject::hasSelectedFacets(), highlightSelection(), Gui::ViewProviderDocumentObject::pcObject, Mesh::MeshObject::removeFacetsFromSelection(), MeshCore::MeshAlgorithm::ResetFacetFlag(), unhighlightSelection(), MeshCore::MeshFacet::VISIT, and MeshCore::MeshKernel::VisitNeighbourFacets().
deselectFacet()
void ViewProviderMesh::deselectFacet (Mesh::FacetIndex facet)
References Mesh::MeshObject::countFacets(), App::PropertyColor::getValue(), Mesh::MeshObject::hasSelectedFacets(), highlightSelection(), pcMatBinding, Gui::ViewProviderDocumentObject::pcObject, Gui::ViewProviderGeometryObject::pcShapeMaterial, Mesh::MeshObject::removeFacetsFromSelection(), Gui::ViewProviderGeometryObject::ShapeColor, and unhighlightSelection().
doubleClicked()
bool MeshGui::ViewProviderMesh::doubleClicked (void) virtual
is called by the tree if the user double clicks on the object
Reimplemented from Gui::ViewProviderDragger.
exportMesh()
void ViewProviderMesh::exportMesh (const char * filename, const char * fmt = nullptr) const
References MeshCore::Material::binding, MeshCore::Material::diffuseColor, MeshCore::MeshOutput::GetFormat(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyString::getValue(), App::GeoFeature::globalPlacement(), App::DocumentObject::Label, MeshCore::MeshIO::OVERALL, Gui::ViewProviderGeometryObject::pcShapeMaterial, MeshCore::MeshIO::PER_FACE, MeshCore::MeshIO::PER_VERTEX, and MeshCore::MeshIO::Undefined.
exportToVrml()
bool ViewProviderMesh::exportToVrml (const char * filename, const MeshCore::Material & mat, bool binary = false) const
References zipios::GZIPOutputStream::close(), MeshGui::ViewProviderMeshBuilder::createMesh(), MeshCore::Material::diffuseColor, Gui::ViewProviderDocumentObject::pcObject, and Gui::SoFCDB::writeNodesToString().
faceInfo()
void ViewProviderMesh::faceInfo (Mesh::FacetIndex facet) protected virtual
References Base::Console(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshKernel::GetFacets(), Mesh::MeshObject::getKernel(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), Mesh::PropertyMeshKernel::getValue(), Mesh::Feature::Mesh, and Base::ConsoleSingleton::Message().
Referenced by faceInfoCallback().
faceInfoCallback()
void ViewProviderMesh::faceInfoCallback (void * ud, SoEventCallback * n) static
References Base::Console(), faceInfo(), faceInfoCallback(), App::GetApplication(), ParameterGrp::GetBool(), Base::BaseClass::getClassTypeId(), Base::Persistence::getClassTypeId(), App::Application::GetParameterGroupByPath(), getShapeNode(), Base::Persistence::getTypeId(), Base::Type::isDerivedFrom(), Base::ConsoleSingleton::Message(), ParameterGrp::SetBool(), Gui::Flag::setText(), and Gui::FlagLayout::TopRight.
Referenced by faceInfoCallback().
fillHole()
void ViewProviderMesh::fillHole (Mesh::FacetIndex facet) protected virtual
References Gui::Application::activeDocument(), Mesh::MeshObject::addFacets(), Gui::Document::commitCommand(), MeshCore::MeshKernel::CountPoints(), MeshCore::MeshAlgorithm::FillupHole(), Mesh::PropertyMeshKernel::finishEditing(), Gui::WindowParameter::getDefaultParameter(), MeshCore::MeshAlgorithm::GetFacetBorder(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), Mesh::MeshObject::getKernel(), Gui::ViewProviderDocumentObject::getObject(), Mesh::PropertyMeshKernel::getValue(), Gui::Application::Instance, Mesh::Feature::Mesh, Gui::Document::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, MeshCore::AbstractPolygonTriangulator::SetVerifier(), MeshCore::MeshAlgorithm::SplitBoundaryLoops(), and Mesh::PropertyMeshKernel::startEditing().
Referenced by fillHoleCallback().
fillHoleCallback()
void ViewProviderMesh::fillHoleCallback (void * ud, SoEventCallback * n) static
References Base::Console(), fillHole(), fillHoleCallback(), Base::Persistence::getClassTypeId(), getShapeNode(), Base::Persistence::getTypeId(), Base::Type::isDerivedFrom(), and Base::ConsoleSingleton::Message().
Referenced by fillHoleCallback().
getColorProperty()
App::PropertyColorList * ViewProviderMesh::getColorProperty () const protected
References Base::Persistence::getClassTypeId(), App::ExtensionContainer::getPropertyMap(), and Gui::ViewProviderDocumentObject::pcObject.
Referenced by attach(), removeFacets(), and tryColorPerVertexOrFace().
getCoordNode()
SoNode * ViewProviderMesh::getCoordNode () const protected virtual
Reimplemented in MeshGui::ViewProviderIndexedFaceSet, MeshGui::ViewProviderMeshObject, and MeshGui::ViewProviderMeshFaceSet.
Referenced by getFacetsOfRegion(), and getVisibleFacets().
getDisplayModes()
std::vector< std::string > ViewProviderMesh::getDisplayModes (void) const virtual
returns a list of all possible modes
Reimplemented from Gui::ViewProvider.
Reimplemented in MeshGui::ViewProviderMeshTransform, and MeshGui::ViewProviderMeshTransformDemolding.
Referenced by MeshGui::ViewProviderMeshTransform::getDisplayModes(), and MeshGui::ViewProviderMeshTransformDemolding::getDisplayModes().
getFacetsFromPolygon()
void ViewProviderMesh::getFacetsFromPolygon (const std::vector< SbVec2f > & picked, const Base::ViewProjMethod & proj, SbBool inner, std::vector< Mesh::FacetIndex > & indices) const
References MeshCore::MeshAlgorithm::CheckFacets(), Base::Console(), Mesh::MeshObject::countFacets(), Mesh::MeshObject::getKernel(), Mesh::PropertyMeshKernel::getValue(), Base::ConsoleSingleton::Message(), and Gui::ViewProviderDocumentObject::pcObject.
Referenced by cutMesh().
getFacetsOfRegion()
std::vector< Mesh::FacetIndex > ViewProviderMesh::getFacetsOfRegion (const SbViewportRegion & select, const SbViewportRegion & region, SoCamera * camera) const
References getCoordNode(), getShapeNode(), Gui::SoGLSelectAction::indices, and draftutils.gui_utils::select().
Referenced by selectArea().
getHighlightNode()
Gui::SoFCSelection * MeshGui::ViewProviderMesh::getHighlightNode () const
Referenced by MeshGui::ViewProviderMeshCurvature::updateData().
getIcon()
QIcon ViewProviderMesh::getIcon (void) const virtual
deliver the icon shown in the tree view
Reimplemented from Gui::ViewProvider.
References Gui::BitmapFactory(), and Gui::BitmapFactoryInst::pixmap().
Referenced by ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), and ArchSectionPlane.SectionPlaneTaskPanel::update().
getPyObject()
PyObject * ViewProviderMesh::getPyObject (void) virtual
Get the python wrapper for that ViewProvider.
Reimplemented from Gui::ViewProviderDocumentObject.
References Gui::ViewProvider::pyViewObject.
getShapeNode()
SoShape * ViewProviderMesh::getShapeNode () const protected virtual
Reimplemented in MeshGui::ViewProviderIndexedFaceSet, MeshGui::ViewProviderMeshObject, and MeshGui::ViewProviderMeshFaceSet.
Referenced by faceInfoCallback(), fillHoleCallback(), getFacetsOfRegion(), getVisibleFacets(), and markPartCallback().
getVisibleFacets()
std::vector< Mesh::FacetIndex > ViewProviderMesh::getVisibleFacets (const SbViewportRegion & vp, SoCamera * camera) const
References draftgeoutils.faces::bind(), MeshCore::MeshKernel::CountFacets(), getCoordNode(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshGeomFacet::GetGravityPoint(), getShapeNode(), Mesh::PropertyMeshKernel::getValue(), Gui::ViewProviderDocumentObject::pcObject, Gui::SoQtOffscreenRenderer::render(), Gui::SoQtOffscreenRenderer::setBackgroundColor(), MeshGui::Vertex::visible(), and Gui::SoQtOffscreenRenderer::writeToImage().
Referenced by getVisibleFacetsAfterZoom().
getVisibleFacetsAfterZoom()
std::vector< Mesh::FacetIndex > ViewProviderMesh::getVisibleFacetsAfterZoom (const SbBox2s & rect, const SbViewportRegion & vp, SoCamera * camera) const
References getVisibleFacets().
hasSelection()
bool ViewProviderMesh::hasSelection () const
References Mesh::PropertyMeshKernel::getValue(), Mesh::MeshObject::hasSelectedFacets(), and Gui::ViewProviderDocumentObject::pcObject.
highlightColors()
void ViewProviderMesh::highlightColors () protected
References Mesh::MeshObject::countFacets(), Mesh::MeshObject::countPoints(), App::ExtensionContainer::getPropertyByName(), App::PropertyListsT< T, ListT, ParentT >::getSize(), Gui::ViewProviderDocumentObject::pcObject, setColorPerFace(), and setColorPerVertex().
Referenced by setHighlightedColors().
highlightComponents()
void ViewProviderMesh::highlightComponents () protected
References Mesh::MeshObject::countFacets(), Mesh::MeshObject::getComponents(), pcMatBinding, Gui::ViewProviderDocumentObject::pcObject, and Gui::ViewProviderGeometryObject::pcShapeMaterial.
Referenced by setEdit(), and setHighlightedComponents().
highlightSegments() [1/2]
void ViewProviderMesh::highlightSegments () protected
References Mesh::MeshObject::countSegments(), App::Color::fromHexString(), Mesh::Segment::getColor(), Mesh::MeshObject::getSegment(), App::PropertyColor::getValue(), highlightSegments(), Gui::ViewProviderDocumentObject::pcObject, and Gui::ViewProviderGeometryObject::ShapeColor.
Referenced by highlightSegments(), and setHighlightedSegments().
highlightSegments() [2/2]
void ViewProviderMesh::highlightSegments (const std::vector< App::Color > & colors)
References Mesh::MeshObject::countFacets(), Mesh::MeshObject::countSegments(), Mesh::Segment::getIndices(), Mesh::MeshObject::getSegment(), pcMatBinding, Gui::ViewProviderDocumentObject::pcObject, and Gui::ViewProviderGeometryObject::pcShapeMaterial.
Referenced by MeshPartGui::Tessellation::setFaceColors().
highlightSelection()
void ViewProviderMesh::highlightSelection () protected virtual
References Mesh::MeshObject::countFacets(), Mesh::MeshObject::getFacetsFromSelection(), App::PropertyColor::getValue(), pcMatBinding, Gui::ViewProviderDocumentObject::pcObject, Gui::ViewProviderGeometryObject::pcShapeMaterial, and Gui::ViewProviderGeometryObject::ShapeColor.
Referenced by addSelection(), deselectComponent(), deselectFacet(), removeSelection(), selectArea(), selectComponent(), selectFacet(), setSelection(), MeshGui::ViewProviderIndexedFaceSet::updateData(), and MeshGui::ViewProviderMeshFaceSet::updateData().
invertSelection()
void ViewProviderMesh::invertSelection ()
References MeshCore::MeshKernel::GetFacets(), Mesh::MeshObject::getKernel(), Gui::ViewProviderDocumentObject::pcObject, MeshCore::MeshFacet::SELECTED, and setSelection().
isFacetSelected()
bool ViewProviderMesh::isFacetSelected (Mesh::FacetIndex facet)
References MeshCore::MeshKernel::GetFacets(), Mesh::MeshObject::getKernel(), Gui::ViewProviderDocumentObject::pcObject, and MeshCore::MeshFacet::SELECTED.
markPartCallback()
void ViewProviderMesh::markPartCallback (void * ud, SoEventCallback * n) static
References Gui::Application::activeDocument(), clearSelection(), Gui::Document::commitCommand(), Base::Console(), deleteSelection(), Base::Persistence::getClassTypeId(), getShapeNode(), Base::Persistence::getTypeId(), Gui::Application::Instance, Base::Type::isDerivedFrom(), markPartCallback(), Base::ConsoleSingleton::Message(), Gui::Document::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, and selectComponent().
Referenced by markPartCallback().
onChanged()
void ViewProviderMesh::onChanged (const App::Property * prop) protected virtual
get called by the container whenever a property has been changed
Reimplemented from Gui::ViewProviderGeometryObject.
References Gui::SoFCSelection::BOX, Coloring, CreaseAngle, App::Material::diffuseColor, Gui::SoFCSelection::EMISSIVE, App::PropertyInteger::getValue(), App::PropertyEnumeration::getValue(), App::PropertyFloat::getValue(), App::PropertyBool::getValue(), App::PropertyColor::getValue(), App::PropertyMaterial::getValue(), Lighting, LineColor, LineTransparency, LineWidth, OpenEdges, pcHighlight, pcLineStyle, pcMatBinding, pcPointStyle, pLineColor, PointSize, pShapeHints, Gui::ViewProviderDocumentObject::SelectionStyle, setOpenEdgeColorFrom(), Gui::ViewProviderGeometryObject::ShapeColor, Gui::ViewProviderGeometryObject::ShapeMaterial, showOpenEdges(), Gui::SoFCSelection::style, and tryColorPerVertexOrFace().
Referenced by ArchStructure.CommandStructuralSystem::Activated(), draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSite.Compass::buildCoordinates(), draftobjects.wire.Wire::execute(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchPanel.ViewProviderPanelSheet::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), and draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData().
partMeshCallback()
void ViewProviderMesh::partMeshCallback (void * ud, SoEventCallback * n) static
References Gui::Application::activeDocument(), Gui::Document::commitCommand(), Base::Console(), createToolMesh(), Gui::ViewProvider::finishEditing(), Base::Persistence::getClassTypeId(), Gui::ViewProvider::getEditingMode(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::Instance, Base::Placement::invert(), Base::ConsoleSingleton::Message(), Gui::Document::openCommand(), partMeshCallback(), draftutils.translate::QT_TRANSLATE_NOOP, Base::Sequencer(), Base::SequencerBase::setLocked(), splitMesh(), Base::Placement::toMatrix(), and MeshCore::MeshKernel::Transform().
Referenced by partMeshCallback().
removeFacets()
void ViewProviderMesh::removeFacets (const std::vector< Mesh::FacetIndex > & facets) virtual
References Coloring, Mesh::MeshObject::countFacets(), Mesh::MeshObject::countPoints(), Mesh::MeshObject::deleteFacets(), Mesh::PropertyMeshKernel::finishEditing(), getColorProperty(), Mesh::MeshObject::getPointDegree(), App::PropertyListsT< T, ListT, ParentT >::getSize(), App::PropertyBool::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Gui::ViewProviderDocumentObject::pcObject, App::DocumentObject::purgeTouched(), App::PropertyBool::setValue(), App::PropertyListsT< T, ListT, ParentT >::setValues(), and Mesh::PropertyMeshKernel::startEditing().
Referenced by cutMesh(), deleteSelection(), and splitMesh().
removeSelection()
void ViewProviderMesh::removeSelection (const std::vector< Mesh::FacetIndex > & indices)
References Mesh::MeshObject::hasSelectedFacets(), highlightSelection(), Gui::ViewProviderDocumentObject::pcObject, Mesh::MeshObject::removeFacetsFromSelection(), and unhighlightSelection().
resetFacetTransparency()
void ViewProviderMesh::resetFacetTransparency ()
References App::PropertyColor::getValue(), pcMatBinding, Gui::ViewProviderGeometryObject::pcShapeMaterial, and Gui::ViewProviderGeometryObject::ShapeColor.
segmentMesh()
void ViewProviderMesh::segmentMesh (const MeshCore::MeshKernel & toolMesh, const Base::Vector3f & normal, SbBool inner) protected virtual
References Mesh::MeshObject::addSegment(), MeshCore::MeshKernel::CountFacets(), Mesh::PropertyMeshKernel::finishEditing(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), Mesh::MeshObject::getKernel(), Mesh::PropertyMeshKernel::getValue(), Gui::ViewProviderDocumentObject::pcObject, and Mesh::PropertyMeshKernel::startEditing().
Referenced by segmMeshCallback().
segmMeshCallback()
void ViewProviderMesh::segmMeshCallback (void * ud, SoEventCallback * n) static
References Gui::Application::activeDocument(), Gui::Document::commitCommand(), Base::Console(), createToolMesh(), Gui::ViewProvider::finishEditing(), Base::Persistence::getClassTypeId(), Gui::ViewProvider::getEditingMode(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::Instance, Base::Placement::invert(), Base::ConsoleSingleton::Message(), Gui::Document::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, segmentMesh(), segmMeshCallback(), Base::Sequencer(), Base::SequencerBase::setLocked(), Base::Placement::toMatrix(), and MeshCore::MeshKernel::Transform().
Referenced by segmMeshCallback().
selectArea()
void ViewProviderMesh::selectArea (short x, short y, short w, short h, const SbViewportRegion & region, SoCamera * camera) protected virtual
References Mesh::MeshObject::addFacetsToSelection(), getFacetsOfRegion(), highlightSelection(), and Gui::ViewProviderDocumentObject::pcObject.
Referenced by selectGLCallback().
selectComponent()
void ViewProviderMesh::selectComponent (Mesh::FacetIndex facet)
References Mesh::MeshObject::addFacetsToSelection(), Mesh::MeshObject::getKernel(), highlightSelection(), Gui::ViewProviderDocumentObject::pcObject, MeshCore::MeshAlgorithm::ResetFacetFlag(), MeshCore::MeshFacet::VISIT, and MeshCore::MeshKernel::VisitNeighbourFacets().
Referenced by markPartCallback().
selectFacet()
void ViewProviderMesh::selectFacet (Mesh::FacetIndex facet)
References Mesh::MeshObject::addFacetsToSelection(), Mesh::MeshObject::countFacets(), highlightSelection(), pcMatBinding, Gui::ViewProviderDocumentObject::pcObject, and Gui::ViewProviderGeometryObject::pcShapeMaterial.
selectGLCallback()
void ViewProviderMesh::selectGLCallback (void * ud, SoEventCallback * n) static
References Gui::ViewProvider::finishEditing(), Base::Persistence::getClassTypeId(), Gui::ViewProvider::getEditingMode(), selectArea(), and selectGLCallback().
Referenced by selectGLCallback().
setColorPerFace()
void ViewProviderMesh::setColorPerFace (const App::PropertyColorList * prop) protected
References App::PropertyListsT< T, ListT, ParentT >::getValues(), pcMatBinding, and Gui::ViewProviderGeometryObject::pcShapeMaterial.
Referenced by highlightColors(), and tryColorPerVertexOrFace().
setColorPerVertex()
void ViewProviderMesh::setColorPerVertex (const App::PropertyColorList * prop) protected
References App::PropertyListsT< T, ListT, ParentT >::getValues(), pcMatBinding, and Gui::ViewProviderGeometryObject::pcShapeMaterial.
Referenced by highlightColors(), and tryColorPerVertexOrFace().
setDisplayMode()
void ViewProviderMesh::setDisplayMode (const char * ModeName) virtual
Sets the correct display mode.
Reimplemented from Gui::ViewProvider.
Reimplemented in MeshGui::ViewProviderMeshTransform, and MeshGui::ViewProviderMeshTransformDemolding.
References Gui::ViewProvider::setDisplayMaskMode().
Referenced by MeshGui::ViewProviderMeshTransform::setDisplayMode(), and MeshGui::ViewProviderMeshTransformDemolding::setDisplayMode().
setEdit()
bool ViewProviderMesh::setEdit (int ModNum) protected virtual
Sets the edit mode.
Reimplemented from Gui::ViewProviderDragger.
References highlightComponents().
Referenced by ArchGrid.ViewProviderArchGrid::doubleClicked(), ArchReference.ViewProviderArchReference::doubleClicked(), draftviewproviders.view_dimension.ViewProviderDimensionBase::doubleClicked(), draftviewproviders.view_hatch.ViewProviderDraftHatch::doubleClicked(), draftviewproviders.view_text.ViewProviderText::doubleClicked(), PathScripts.PathPropertyBagGui.ViewProvider::doubleClicked(), PathScripts.PathSetupSheetGui.ViewProvider::doubleClicked(), PathScripts.PathToolBitGui.ViewProvider::doubleClicked(), Spreadsheet_legacy.ViewProviderSpreadsheet::doubleClicked(), ArchSchedule.CommandArchSchedule::IsActive(), PathScripts.PathIconViewProvider.ViewProvider::setupContextMenu(), PathScripts.PathJobGui.ViewProvider::setupContextMenu(), PathScripts.PathOpGui.ViewProvider::setupContextMenu(), and PathScripts.PathToolControllerGui.ViewProvider::setupContextMenu().
setFacetTransparency()
void ViewProviderMesh::setFacetTransparency (const std::vector< float > & facetTransparency)
The size of the array must be equal to the number of facets.
References App::PropertyColor::getValue(), pcMatBinding, Gui::ViewProviderGeometryObject::pcShapeMaterial, and Gui::ViewProviderGeometryObject::ShapeColor.
setHighlightedColors()
void ViewProviderMesh::setHighlightedColors (bool on) protected
References Color, highlightColors(), highlightMode, and unhighlightSelection().
Referenced by setupContextMenu().
setHighlightedComponents()
void ViewProviderMesh::setHighlightedComponents (bool on) protected
References Component, highlightComponents(), highlightMode, and unhighlightSelection().
Referenced by setupContextMenu().
setHighlightedSegments()
void ViewProviderMesh::setHighlightedSegments (bool on) protected
References highlightMode, highlightSegments(), Segment, and unhighlightSelection().
Referenced by setupContextMenu().
setOpenEdgeColorFrom()
void ViewProviderMesh::setOpenEdgeColorFrom (const App::Color & col) protected
References pOpenColor.
Referenced by onChanged().
setSelection()
void ViewProviderMesh::setSelection (const std::vector< Mesh::FacetIndex > & indices)
References Mesh::MeshObject::addFacetsToSelection(), Mesh::MeshObject::clearFacetSelection(), highlightSelection(), Gui::ViewProviderDocumentObject::pcObject, and unhighlightSelection().
Referenced by invertSelection().
setupContextMenu()
void ViewProviderMesh::setupContextMenu (QMenu * menu, QObject * receiver, const char * method) virtual
set up the context-menu with the supported edit modes
Reimplemented from Gui::ViewProviderDragger.
References draftgeoutils.faces::bind(), canHighlightColors(), Color, Component, highlightMode, pcMatBinding, Segment, setHighlightedColors(), setHighlightedComponents(), and setHighlightedSegments().
showOpenEdges()
void ViewProviderMesh::showOpenEdges (bool show) protected virtual
Reimplemented in MeshGui::ViewProviderIndexedFaceSet, MeshGui::ViewProviderMeshObject, and MeshGui::ViewProviderMeshFaceSet.
References Gui::ViewProviderDocumentObject::show().
Referenced by onChanged().
splitMesh()
void ViewProviderMesh::splitMesh (const MeshCore::MeshKernel & toolMesh, const Base::Vector3f & normal, SbBool inner) protected virtual
References App::Document::addObject(), MeshCore::MeshKernel::CountFacets(), App::Application::getActiveDocument(), App::GetApplication(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), Mesh::MeshObject::getKernel(), App::DocumentObject::getNameInDocument(), Mesh::PropertyMeshKernel::getValue(), Mesh::MeshObject::meshFromSegment(), Gui::ViewProviderDocumentObject::pcObject, removeFacets(), and splitMesh().
Referenced by partMeshCallback(), and splitMesh().
trimMesh()
void ViewProviderMesh::trimMesh (const std::vector< SbVec2f > & picked, const Base::ViewProjMethod & proj, SbBool inner) virtual
References Base::Polygon2d::Add(), Mesh::MeshObject::INNER, Mesh::MeshObject::OUTER, Gui::ViewProviderDocumentObject::pcObject, and App::DocumentObject::purgeTouched().
Referenced by MeshGui::MeshSplit::trimMesh(), and trimMeshCallback().
trimMeshCallback()
void ViewProviderMesh::trimMeshCallback (void * ud, SoEventCallback * n) static
References Gui::Document::abortCommand(), Gui::Application::activeDocument(), draftgeoutils.faces::bind(), Gui::Document::commitCommand(), Gui::ViewProvider::finishEditing(), Base::Persistence::getClassTypeId(), Gui::ViewProvider::getEditingMode(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::Instance, Gui::Document::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, Base::ViewProjMethod::setTransform(), MeshGui::MeshSplit::trimMesh(), trimMesh(), and trimMeshCallback().
Referenced by trimMeshCallback().
tryColorPerVertexOrFace()
void ViewProviderMesh::tryColorPerVertexOrFace (bool on) protected
References getColorProperty(), Mesh::PropertyMeshKernel::getValue(), App::PropertyColor::getValue(), pcMatBinding, Gui::ViewProviderDocumentObject::pcObject, Gui::ViewProviderGeometryObject::pcShapeMaterial, setColorPerFace(), setColorPerVertex(), and Gui::ViewProviderGeometryObject::ShapeColor.
Referenced by onChanged().
unhighlightSelection()
void ViewProviderMesh::unhighlightSelection () protected virtual
References App::PropertyColor::getValue(), pcMatBinding, Gui::ViewProviderGeometryObject::pcShapeMaterial, and Gui::ViewProviderGeometryObject::ShapeColor.
Referenced by clearSelection(), deleteSelection(), deselectComponent(), deselectFacet(), removeSelection(), setHighlightedColors(), setHighlightedComponents(), setHighlightedSegments(), setSelection(), unsetEdit(), and MeshGui::ViewProviderMeshFaceSet::updateData().
unsetEdit()
void ViewProviderMesh::unsetEdit (int ModNum) protected virtual
Unsets the edit mode.
Reimplemented from Gui::ViewProviderDragger.
References unhighlightSelection().
Referenced by PathScripts.PathJobGui.ViewProvider::uneditObject().
updateData()
void ViewProviderMesh::updateData (const App::Property * prop) virtual
Reimplemented from Gui::ViewProviderGeometryObject.
Reimplemented in MeshGui::ViewProviderIndexedFaceSet, MeshGui::ViewProviderMeshObject, MeshGui::ViewProviderMeshFaceSet, and MeshGui::ViewProviderMeshTransform.
References Coloring, Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), App::Property::Hidden, App::Property::setStatus(), and Gui::ViewProviderGeometryObject::updateData().
Referenced by ArchStructure.CommandStructuralSystem::Activated(), PathScripts.PathJobDlg.JobCreate::exec_(), draftviewproviders.view_dimension.ViewProviderLinearDimension::onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension::onChanged(), draftviewproviders.view_wire.ViewProviderWire::onChanged(), PathScripts.PathOpGui.TaskPanelPage::pageUpdateData(), PathScripts.PathPropertyBagGui.TaskPanel::setupUi(), PathScripts.PathSetupSheetGui.OpTaskPanel::setupUi(), MeshGui::ViewProviderIndexedFaceSet::updateData(), MeshGui::ViewProviderMeshObject::updateData(), MeshGui::ViewProviderMeshFaceSet::updateData(), and MeshGui::ViewProviderMeshTransform::updateData().
useNewSelectionModel()
virtual bool MeshGui::ViewProviderMesh::useNewSelectionModel (void) const virtual
indicates if the ViewProvider use the new Selection model
Reimplemented from Gui::ViewProvider.
Member Data Documentation
Coloring
App::PropertyBool MeshGui::ViewProviderMesh::Coloring
Referenced by attach(), onChanged(), removeFacets(), and updateData().
CreaseAngle
App::PropertyFloatConstraint MeshGui::ViewProviderMesh::CreaseAngle
Referenced by onChanged().
highlightMode
HighlighMode MeshGui::ViewProviderMesh::highlightMode protected
Referenced by setHighlightedColors(), setHighlightedComponents(), setHighlightedSegments(), and setupContextMenu().
Lighting
App::PropertyEnumeration MeshGui::ViewProviderMesh::Lighting
Referenced by onChanged().
LineColor
App::PropertyColor MeshGui::ViewProviderMesh::LineColor
Referenced by onChanged().
LineTransparency
App::PropertyPercent MeshGui::ViewProviderMesh::LineTransparency
Referenced by onChanged().
LineWidth
App::PropertyFloatConstraint MeshGui::ViewProviderMesh::LineWidth
Referenced by onChanged().
OpenEdges
App::PropertyBool MeshGui::ViewProviderMesh::OpenEdges
Referenced by onChanged(), MeshGui::ViewProviderIndexedFaceSet::updateData(), and MeshGui::ViewProviderMeshFaceSet::updateData().
pcHighlight
Gui::SoFCSelection* MeshGui::ViewProviderMesh::pcHighlight protected
Referenced by attach(), MeshGui::ViewProviderIndexedFaceSet::attach(), MeshGui::ViewProviderMeshTransform::attach(), MeshGui::ViewProviderMeshTransformDemolding::attach(), MeshGui::ViewProviderMeshObject::attach(), onChanged(), and ~ViewProviderMesh().
pcLineStyle
SoDrawStyle* MeshGui::ViewProviderMesh::pcLineStyle protected
Referenced by attach(), onChanged(), MeshGui::ViewProviderIndexedFaceSet::showOpenEdges(), MeshGui::ViewProviderMeshObject::showOpenEdges(), MeshGui::ViewProviderMeshFaceSet::showOpenEdges(), and ~ViewProviderMesh().
pcMatBinding
SoMaterialBinding* MeshGui::ViewProviderMesh::pcMatBinding protected
Referenced by attach(), MeshGui::ViewProviderMeshTransformDemolding::attach(), deselectFacet(), highlightComponents(), highlightSegments(), highlightSelection(), onChanged(), resetFacetTransparency(), selectFacet(), setColorPerFace(), setColorPerVertex(), setFacetTransparency(), setupContextMenu(), tryColorPerVertexOrFace(), unhighlightSelection(), and ~ViewProviderMesh().
pcOpenEdge
SoSeparator* MeshGui::ViewProviderMesh::pcOpenEdge protected
Referenced by MeshGui::ViewProviderIndexedFaceSet::showOpenEdges(), MeshGui::ViewProviderMeshObject::showOpenEdges(), and MeshGui::ViewProviderMeshFaceSet::showOpenEdges().
pcPointStyle
SoDrawStyle* MeshGui::ViewProviderMesh::pcPointStyle protected
Referenced by attach(), onChanged(), and ~ViewProviderMesh().
pcShapeGroup
SoGroup* MeshGui::ViewProviderMesh::pcShapeGroup protected
Referenced by attach(), MeshGui::ViewProviderMeshFaceSet::attach(), MeshGui::ViewProviderMeshFaceSet::updateData(), and ~ViewProviderMesh().
pLineColor
SoMaterial* MeshGui::ViewProviderMesh::pLineColor protected
Referenced by attach(), onChanged(), and ~ViewProviderMesh().
PointSize
App::PropertyFloatConstraint MeshGui::ViewProviderMesh::PointSize
Referenced by onChanged().
pOpenColor
SoBaseColor* MeshGui::ViewProviderMesh::pOpenColor protected
Referenced by setOpenEdgeColorFrom(), MeshGui::ViewProviderIndexedFaceSet::showOpenEdges(), MeshGui::ViewProviderMeshObject::showOpenEdges(), MeshGui::ViewProviderMeshFaceSet::showOpenEdges(), and ~ViewProviderMesh().
pShapeHints
SoShapeHints* MeshGui::ViewProviderMesh::pShapeHints protected
Referenced by attach(), onChanged(), and ~ViewProviderMesh().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/Gui/ViewProvider.h
FreeCAD/src/Mod/Mesh/Gui/ViewProvider.cpp