FreeCAD: WebGui::UrlWidget Class Reference
WebGui::UrlWidget Class Reference
#include <BrowserView.h>
Public Member Functions
void display ()
UrlWidget (BrowserView *view)
~UrlWidget ()
Protected Member Functions
void keyPressEvent (QKeyEvent *keyEvt)
Constructor & Destructor Documentation
UrlWidget()
WebGui::UrlWidget::UrlWidget (BrowserView * view) explicit
~UrlWidget()
WebGui::UrlWidget::~UrlWidget ()
Member Function Documentation
display()
void WebGui::UrlWidget::display ()
References WebGui::BrowserView::url().
Referenced by draftguitools.gui_selectplane.Draft_SelectPlane::handle(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickAlign(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickAuto(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickFront(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickMove(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickSide(), draftguitools.gui_selectplane.Draft_SelectPlane::onClickTop(), WebGui::BrowserView::onMsg(), draftguitools.gui_selectplane.Draft_SelectPlane::setPlaneFromObjPlacement(), and draftguitools.gui_selectplane.Draft_SelectPlane::setPlaneOnWPProxy().
keyPressEvent()
void WebGui::UrlWidget::keyPressEvent (QKeyEvent * keyEvt) protected
References WebGui::BrowserView::load().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Web/Gui/BrowserView.h
Sources/FreeCAD/src/Mod/Web/Gui/BrowserView.cpp