FreeCAD: VISCOUS_3D::_SmoothNode Struct Reference
VISCOUS_3D::_SmoothNode Struct Reference
Data of node on a shrinked FACE.
Public Types
enum SmoothType { LAPLACIAN , CENTROIDAL , ANGULAR , TFI }
Public Member Functions
gp_XY computeAngularPos (vector< gp_XY > &uv, const gp_XY &uvToFix, const double refSign)
Computes new UV using angle based smoothing technic.
bool Smooth (int &badNb, Handle(Geom_Surface)&surface, SMESH_MesherHelper &helper, const double refSign, SmoothType how, bool set3D)
Perform smooth on the FACE.
Detailed Description
Data of node on a shrinked FACE.
Member Enumeration Documentation
SmoothType
enum VISCOUS_3D::_SmoothNode::SmoothType
Enumerator
LAPLACIAN
CENTROIDAL
ANGULAR
TFI
Member Function Documentation
computeAngularPos()
gp_XY _SmoothNode::computeAngularPos (vector< gp_XY > & uv, const gp_XY & uvToFix, const double refSign)
Computes new UV using angle based smoothing technic.
Smooth()
bool _SmoothNode::Smooth (int & badNb, Handle(Geom_Surface)& surface, SMESH_MesherHelper & helper, const double refSign, SmoothType how, bool set3D)
Perform smooth on the FACE.
Return values
bool - true if the node has been moved
References SMESH_MesherHelper::calcTFI(), SMESH_MesherHelper::GetNodeUV(), SMESH_MesherHelper::GetSubShape(), and SMESH_MesherHelper::WrapIndex().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_ViscousLayers.cpp