FreeCAD: TechDrawGui::DlgPrefsTechDrawDimensionsImp Class Reference
TechDrawGui::DlgPrefsTechDrawDimensionsImp Class Reference
#include <DlgPrefsTechDrawDimensionsImp.h>
Public Member Functions
DlgPrefsTechDrawDimensionsImp (QWidget *parent=nullptr)
~DlgPrefsTechDrawDimensionsImp ()
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void loadSettings ()
int prefArrowStyle (void) const
void saveSettings ()
virtual void changeEvent (QEvent *e)=0
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Constructor & Destructor Documentation
DlgPrefsTechDrawDimensionsImp()
DlgPrefsTechDrawDimensionsImp::DlgPrefsTechDrawDimensionsImp (QWidget * parent = nullptr)
References Base::Unit::Length.
~DlgPrefsTechDrawDimensionsImp()
DlgPrefsTechDrawDimensionsImp::~DlgPrefsTechDrawDimensionsImp ()
Member Function Documentation
changeEvent()
void DlgPrefsTechDrawDimensionsImp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
References loadSettings(), and saveSettings().
loadSettings()
void DlgPrefsTechDrawDimensionsImp::loadSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
References Base::Tools::fromStdString(), TechDrawGui::DrawGuiUtil::loadArrowBox(), and prefArrowStyle().
Referenced by changeEvent().
prefArrowStyle()
int DlgPrefsTechDrawDimensionsImp::prefArrowStyle (void) const protected
References TechDrawGui::PreferencesGui::dimArrowStyle().
Referenced by loadSettings().
saveSettings()
void DlgPrefsTechDrawDimensionsImp::saveSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
Referenced by changeEvent().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensionsImp.h
FreeCAD/src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensionsImp.cpp