FreeCAD: draftobjects.dimension.DimensionBase Class Reference
draftobjects.dimension.DimensionBase Class Reference
Workbenches » Python workbenches » Draft » draftobjects
Public Member Functions
def onDocumentRestored (self, obj)
def set_properties (self, obj)
Public Member Functions inherited from draftobjects.draft_annotation.DraftAnnotation
def add_missing_properties_0v19 (self, obj, vobj)
def execute (self, obj)
def onChanged (self, obj, prop)
def onDocumentRestored (self, obj)
Additional Inherited Members
Public Attributes inherited from draftobjects.draft_annotation.DraftAnnotation
Type
Detailed Description
The base objects for dimension objects.
This class inherits `DraftAnnotation` to define the basic properties
of all annotation type objects, like a scaling multiplier.
This class is not used directly, but inherited by all dimension
objects.
Member Function Documentation
onDocumentRestored()
def draftobjects.dimension.DimensionBase.onDocumentRestored (self, obj)
Execute code when the document is restored.
It calls the parent class to add missing annotation properties.
Reimplemented from draftobjects.draft_annotation.DraftAnnotation.
Reimplemented in draftobjects.dimension.LinearDimension, and draftobjects.dimension.AngularDimension.
References draftobjects.dimension.DimensionBase.onDocumentRestored().
Referenced by draftobjects.dimension.DimensionBase.onDocumentRestored().
set_properties()
def draftobjects.dimension.DimensionBase.set_properties (self, obj)
Set basic properties only if they don't exist.
Reimplemented in draftobjects.dimension.LinearDimension, and draftobjects.dimension.AngularDimension.
References draftutils.translate.QT_TRANSLATE_NOOP.
Referenced by draftobjects.array.Array.attach(), draftobjects.patharray.PathArray.attach(), draftobjects.pathtwistedarray.PathTwistedArray.attach(), draftobjects.pointarray.PointArray.attach(), draftobjects.layer.Layer.onDocumentRestored(), draftobjects.patharray.PathArray.onDocumentRestored(), draftobjects.pathtwistedarray.PathTwistedArray.onDocumentRestored(), and draftobjects.pointarray.PointArray.onDocumentRestored().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Draft/draftobjects/dimension.py