FreeCAD: App::PropertyListsT< T, ListT, ParentT > Class Template Reference
App::PropertyListsT< T, ListT, ParentT > Class Template Reference abstract
Helper class to implement PropertyLists.
#include <Property.h>
Public Types
typedef AtomicPropertyChangeInterface< PropertyListsT< T, ListT, ParentT > >::AtomicPropertyChange atomic_change
typedef ListT::const_reference const_reference
typedef ListT list_type
typedef ParentT parent_type
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , Busy = 15 ,
CopyOnChange = 16 , UserEdit = 17 , PropStaticBegin = 21 , PropDynamic = 21 ,
PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 , PropTransient = 25 ,
PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 , User1 = 28 ,
User2 = 29 , User3 = 30 , User4 = 31
}
Public Member Functions
virtual int getSize (void) const override
const ListT & getValue (void) const
const ListT & getValues (void) const
virtual bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
const_reference operator[] (int idx) const
virtual void set1Value (int index, const_reference value)
virtual void setPyObject (PyObject *value) override
virtual void setSize (int newSize) override
virtual void setSize (int newSize, const_reference def)
void setValue (const ListT &newValues=ListT())
void setValue (const_reference value)
virtual void setValues (const ListT &newValues=ListT())
Public Member Functions inherited from App::PropertyLists
bool isOrderRelevant () const
void setOrderRelevant (bool on)
virtual void setPyObject (PyObject *obj) override
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual Property * Copy (void) const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
int64_t getID () const
Return a unique ID for the property.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const char * getName (void) const
Get the name of this property in the belonging container With hasName() it can be checked beforehand if a valid name is set.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
bool hasName () const
Check if the property has a name set.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::PropertyListsBase
void clearTouchList ()
virtual int getSize (void) const =0
const std::set< int > & getTouchList () const
virtual void setSize (int newSize)=0
Public Attributes
friend atomic_change
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions
virtual T getPyValue (PyObject *item) const =0
void setPyValues (const std::vector< PyObject * > &vals, const std::vector< int > &indices) override
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
virtual void setPyValues (const std::vector< PyObject * > &vals, const std::vector< int > &indices)
Protected Member Functions inherited from App::AtomicPropertyChangeInterface< PropertyListsT< T, std::vector< T >, PropertyLists > >
AtomicPropertyChangeInterface ()
Additional Inherited Members
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Check if the passed name is valid.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Protected Attributes inherited from App::AtomicPropertyChangeInterface< PropertyListsT< T, std::vector< T >, PropertyLists > >
bool hasChanged
int signalCounter
Counter for invoking transaction start/stop.
Detailed Description
template<class T, class ListT = std::vector<T>, class ParentT = PropertyLists>
class App::PropertyListsT< T, ListT, ParentT >
Helper class to implement PropertyLists.
Member Typedef Documentation
atomic_change
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> typedef AtomicPropertyChangeInterface<PropertyListsT<T,ListT,ParentT>>::AtomicPropertyChange App::PropertyListsT< T, ListT, ParentT >::atomic_change
const_reference
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> typedef ListT::const_reference App::PropertyListsT< T, ListT, ParentT >::const_reference
list_type
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> typedef ListT App::PropertyListsT< T, ListT, ParentT >::list_type
parent_type
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> typedef ParentT App::PropertyListsT< T, ListT, ParentT >::parent_type
Member Function Documentation
getPyValue()
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> virtual T App::PropertyListsT< T, ListT, ParentT >::getPyValue (PyObject * item) const protected pure virtual
Implemented in App::PropertyVectorList, App::PropertyPlacementList, App::PropertyBoolList, App::PropertyColorList, App::PropertyMaterialList, App::PropertyLinkList, App::PropertyIntegerList, App::PropertyFloatList, and App::PropertyStringList.
Referenced by App::PropertyListsT< T, ListT, ParentT >::setPyObject(), and App::PropertyListsT< T, ListT, ParentT >::setPyValues().
getSize()
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> virtual int App::PropertyListsT< T, ListT, ParentT >::getSize (void) const override virtual
Implements App::PropertyListsBase.
Referenced by TechDraw::DrawPage::addView(), TechDraw::DrawViewCollection::addView(), Gui::ViewProviderLink::applyMaterial(), MeshGui::ViewProviderMesh::canHighlightColors(), Part::Loft::execute(), Part::Sweep::execute(), Fem::FemVTKTools::exportFreeCADResult(), PartGui::ViewProviderPartExt::getElementColors(), Gui::ViewProviderLink::getElementColors(), MeshGui::ViewProviderMesh::highlightColors(), Drawing::FeaturePage::onBeforeChange(), App::VRMLObject::onChanged(), Drawing::FeaturePage::onChanged(), MeshGui::ViewProviderMesh::removeFacets(), App::GroupExtension::removeObjectsFromDocument(), TechDraw::DrawPage::removeView(), TechDraw::DrawViewCollection::removeView(), App::VRMLObject::Restore(), App::VRMLObject::RestoreDocFile(), App::VRMLObject::SaveDocFile(), App::PropertyListsT< T, ListT, ParentT >::set1Value(), PartDesignGui::ViewProviderTransformed::startEditing(), Gui::ViewProviderVRMLObject::updateData(), Gui::ViewProviderLink::updateElementList(), and App::PropertyLinkSubList::upgrade().
getValue()
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> const ListT & App::PropertyListsT< T, ListT, ParentT >::getValue (void) const
References App::PropertyListsT< T, ListT, ParentT >::getValues().
Referenced by App::GroupExtension::extensionOnChanged(), and App::PropertyListsT< T, ListT, ParentT >::isSame().
getValues()
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> const ListT & App::PropertyListsT< T, ListT, ParentT >::getValues (void) const
Referenced by TechDrawGui::MDIViewPage::addChildrenToPage(), PartDesign::Body::addObject(), Path::FeatureCompound::addObject(), App::GroupExtension::addObjects(), App::GeoFeatureGroupExtension::addObjects(), TechDraw::DrawProjGroup::addProjection(), TechDraw::DrawPage::addView(), TechDraw::DrawViewClip::addView(), TechDraw::DrawViewCollection::addView(), TechDraw::DrawLeaderLine::adjustLastSegment(), TechDraw::DrawProjGroup::arrangeViewPointers(), TechDraw::DrawProjGroup::autoPositionChildren(), Gui::ViewProviderColorBuilder::buildNodes(), TechDrawGui::TaskRichAnno::calcTextStartPos(), TechDraw::DrawViewDimExtent::checkReferences2D(), FemGui::ViewProviderFemPostPipeline::claimChildren(), PartGui::ViewProviderSweep::claimChildren(), PartDesignGui::ViewProviderMultiTransform::claimChildren(), TechDrawGui::ViewProviderProjGroup::claimChildren(), TechDrawGui::ViewProviderViewClip::claimChildren(), TechDrawGui::ViewProviderPage::claimChildren(), TechDraw::DrawViewCollection::countChildren(), App::GroupExtension::countObjectsOfType(), PartGui::ViewProviderMultiFuse::dragObject(), PartGui::ViewProviderMultiCommon::dragObject(), PartGui::ViewProviderCompound::dragObject(), PartGui::ViewProviderFace::dragObject(), PathGui::ViewProviderArea::dragObject(), PathGui::ViewProviderPathShape::dragObject(), PartGui::ViewProviderMultiFuse::dropObject(), PartGui::ViewProviderMultiCommon::dropObject(), PartGui::ViewProviderCompound::dropObject(), PartGui::ViewProviderFace::dropObject(), PathGui::ViewProviderArea::dropObject(), PathGui::ViewProviderPathShape::dropObject(), PartDesignGui::ViewProviderBody::dropObject(), TechDraw::DrawProjGroup::dumpISO(), Drawing::FeatureClip::execute(), Drawing::FeaturePage::execute(), Drawing::FeatureViewAnnotation::execute(), Drawing::FeatureViewSymbol::execute(), Fem::FemPostPipeline::execute(), Inspection::Feature::execute(), Part::Compound::execute(), Part::MultiCommon::execute(), Part::MultiFuse::execute(), Part::Loft::execute(), Part::Sweep::execute(), PartDesign::Transformed::execute(), Path::FeatureArea::execute(), Path::FeatureCompound::execute(), Path::FeatureShape::execute(), Raytracing::LuxProject::execute(), Raytracing::RayProject::execute(), Robot::TrajectoryCompound::execute(), TechDraw::DrawViewClip::execute(), TechDraw::DrawViewDimExtent::execute(), Part::Face::execute(), PartDesign::Boolean::execute(), TechDraw::DrawViewMulti::execute(), TechDraw::DrawViewSymbol::execute(), TechDraw::LandmarkDimension::execute(), Fem::FemVTKTools::exportFreeCADResult(), Import::ExportOCAF::exportObject(), Gui::ViewProviderGeoFeatureGroupExtension::extensionClaimChildren(), App::GeoFeatureGroupExtension::extensionGetSubObject(), App::GroupExtension::extensionGetSubObject(), App::GeoFeatureGroupExtension::extensionGetSubObjects(), App::GroupExtension::extensionGetSubObjects(), App::GeoFeatureGroupExtension::extensionOnChanged(), App::GroupExtension::extensionOnChanged(), TechDrawGui::MDIViewPage::findMissingViews(), TechDrawGui::QGSPage::findParent(), App::GroupExtension::getAllChildren(), TechDraw::DrawProjGroup::getAllSources(), TechDraw::DrawViewPart::getAllSources(), TechDraw::DrawPage::getAllViews(), PartDesign::Transformed::getBaseObject(), TechDraw::DrawProjGroup::getBoundingBox(), TechDraw::DrawViewClip::getChildViewNames(), TechDrawGui::QGEPath::getDeltasFromLeader(), TechDraw::DrawLeaderLine::getKinkPoint(), Fem::FemPostPipeline::getLastPostObject(), PartDesign::Body::getNextSolidFeature(), App::GroupExtension::getObjects(), App::GroupExtension::getObjectsOfType(), App::Origin::getOriginFeature(), TechDraw::DrawViewDimExtent::getPointsTwoVerts(), PartDesign::Body::getPrevSolidFeature(), TechDraw::DrawProjGroup::getProjObj(), TechDraw::DrawViewAnnotation::getRect(), TechDraw::DrawViewCollection::getRect(), TechDraw::ShapeExtractor::getShapes2d(), TechDraw::ShapeExtractor::getShapesFromObject(), PartDesign::Transformed::getSketchObject(), PartDesign::Body::getSubObject(), TechDraw::DrawLeaderLine::getTailPoint(), TechDraw::DrawLeaderLine::getTileOrigin(), PartDesign::MultiTransform::getTransformations(), PartDesignGui::TaskMultiTransformParameters::getTransformFeatures(), App::PropertyListsT< T, ListT, ParentT >::getValue(), TechDraw::DrawProjGroup::getViewsAsDPGI(), TechDrawGui::QGILeaderLine::getWayPointsFromFeature(), App::Origin::hasObject(), Path::FeatureCompound::hasObject(), App::GroupExtension::hasObject(), TechDraw::DrawProjGroup::hasProjection(), PartDesignGui::ViewProviderShapeBinder::highlightReferences(), PartDesignGui::ViewProviderDressUp::highlightReferences(), FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences(), Fem::FemPostPipeline::holdsPostObject(), PartDesignGui::TaskTransformedParameters::indexesMoved(), PartDesign::Body::insertObject(), Part::BodyBase::isAfter(), PartDesign::Body::isMemberOfMultiTransform(), TechDraw::DrawViewClip::isViewInClip(), TechDrawGui::TaskLinkDim::loadAvailDims(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::loadDefaults(), TechDraw::DrawViewCollection::lockChildren(), TechDrawGui::QGIViewAnnotation::mouseDoubleClickEvent(), App::VRMLObject::onChanged(), Fem::FemPostPipeline::onChanged(), PartGui::ViewProviderPartExt::onChanged(), PartDesign::Body::onChanged(), PartDesignGui::ViewProvider::onChanged(), TechDraw::DrawPage::onChanged(), TechDraw::DrawViewMulti::onChanged(), Gui::ViewProviderOrigin::onDelete(), PartGui::ViewProviderMultiFuse::onDelete(), PartGui::ViewProviderMultiCommon::onDelete(), PartGui::ViewProviderCompound::onDelete(), PartDesignGui::ViewProviderMultiTransform::onDelete(), PathGui::ViewProviderArea::onDelete(), PathGui::ViewProviderPathShape::onDelete(), PartDesignGui::ViewProviderBoolean::onDelete(), PartDesign::Body::onDocumentRestored(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), SurfaceGui::FillingEdgePanel::onSelectionChanged(), TechDrawGui::TaskLeaderLine::onTrackerClicked(), PartDesignGui::TaskTransformedParameters::originalSelected(), TechDrawGui::MDIViewPage::orphanExists(), PartDesign::MultiTransform::positionBySupport(), PartGui::FaceColors::Private::Private(), TechDraw::DrawProjGroup::purgeProjections(), TechDraw::DrawViewCollection::rebuildViewList(), TechDraw::DrawProjGroup::recomputeChildren(), PartDesignGui::relinkToBody(), MeshGui::ViewProviderMesh::removeFacets(), Path::FeatureCompound::removeObject(), PartDesign::Body::removeObject(), App::GroupExtension::removeObjects(), App::GeoFeatureGroupExtension::removeObjects(), App::GroupExtension::removeObjectsFromDocument(), TechDraw::DrawProjGroup::removeProjection(), TechDraw::DrawPage::removeView(), TechDraw::DrawViewClip::removeView(), TechDraw::DrawViewCollection::removeView(), App::VRMLObject::Restore(), App::VRMLObject::Save(), TechDrawGui::TaskProjGroup::saveGroupState(), TechDrawGui::TaskLeaderLine::saveState(), MeshGui::ViewProviderMesh::setColorPerFace(), MeshGui::ViewProviderMesh::setColorPerVertex(), SurfaceGui::FillingPanel::setEditedObject(), SurfaceGui::FillingEdgePanel::setEditedObject(), Gui::ViewProviderLink::setElementColors(), App::PropertyLinkSubList::setPyObject(), App::PropertyXLinkList::setPyObject(), PointsGui::ViewProviderPoints::setVertexColorMode(), PartDesignGui::ViewProviderBody::setVisualBodyMode(), PartDesignGui::TaskBooleanParameters::TaskBooleanParameters(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintTransform::TaskFemConstraintTransform(), PartDesignGui::TaskMultiTransformParameters::TaskMultiTransformParameters(), PathGui::TaskWidgetPathCompound::TaskWidgetPathCompound(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), App::Origin::unsetupObject(), TechDraw::DrawViewCollection::unsetupObject(), TechDraw::DrawViewDimExtent::unsetupObject(), TechDraw::DrawPage::unsetupObject(), TechDraw::LandmarkDimension::unsetupObject(), TechDraw::DrawProjGroup::updateChildrenEnforce(), TechDraw::DrawProjGroup::updateChildrenLock(), TechDraw::DrawProjGroup::updateChildrenScale(), TechDraw::DrawProjGroup::updateChildrenSource(), FemGui::ViewProviderFemConstraintContact::updateData(), FemGui::ViewProviderFemConstraintFixed::updateData(), FemGui::ViewProviderFemConstraintFluidBoundary::updateData(), FemGui::ViewProviderFemConstraintForce::updateData(), FemGui::ViewProviderFemConstraintHeatflux::updateData(), FemGui::ViewProviderFemConstraintPlaneRotation::updateData(), FemGui::ViewProviderFemConstraintPressure::updateData(), FemGui::ViewProviderFemConstraintSpring::updateData(), FemGui::ViewProviderFemConstraintTemperature::updateData(), FemGui::ViewProviderFemConstraintTransform::updateData(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderMultiFuse::updateData(), PartGui::ViewProviderMultiCommon::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderFillet::updateData(), PartGui::ViewProviderChamfer::updateData(), PartDesignGui::ViewProviderBody::updateData(), TechDraw::DrawProjGroup::updateSecondaryDirs(), TechDraw::DrawProjGroup::updateViews(), App::PropertyLinkSubList::upgrade(), and App::PropertyXLinkSubList::upgrade().
isSame()
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> virtual bool App::PropertyListsT< T, ListT, ParentT >::isSame (const Property & other) const override virtual
Compare if this property has the same content as the given one.
Reimplemented from App::Property.
References Base::Persistence::getTypeId(), and App::PropertyListsT< T, ListT, ParentT >::getValue().
operator[]()
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> const_reference App::PropertyListsT< T, ListT, ParentT >::operator[] (int idx) const
set1Value()
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> virtual void App::PropertyListsT< T, ListT, ParentT >::set1Value (int index, const_reference value) virtual
References App::PropertyListsT< T, ListT, ParentT >::getSize(), App::PropertyListsT< T, ListT, ParentT >::setSize(), and App::AtomicPropertyChangeInterface< P >::AtomicPropertyChange::tryInvoke().
Referenced by App::VRMLObject::onChanged(), App::VRMLObject::RestoreDocFile(), and App::PropertyListsT< T, ListT, ParentT >::setPyValues().
setPyObject()
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> virtual void App::PropertyListsT< T, ListT, ParentT >::setPyObject (PyObject * value) override virtual
Reimplemented from App::PropertyLists.
Reimplemented in App::PropertyBoolList.
References App::PropertyListsT< T, ListT, ParentT >::getPyValue(), and App::PropertyListsT< T, ListT, ParentT >::setValue().
Referenced by App::PropertyLinkSubList::setPyObject(), and App::PropertyXLinkList::setPyObject().
setPyValues()
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> void App::PropertyListsT< T, ListT, ParentT >::setPyValues (const std::vector< PyObject * > & vals, const std::vector< int > & indices) override protected virtual
Reimplemented from App::PropertyListsBase.
References App::PropertyListsT< T, ListT, ParentT >::getPyValue(), draftfunctions.move::move(), App::PropertyListsT< T, ListT, ParentT >::set1Value(), App::PropertyListsT< T, ListT, ParentT >::setValues(), and App::AtomicPropertyChangeInterface< P >::AtomicPropertyChange::tryInvoke().
setSize() [1/2]
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> virtual void App::PropertyListsT< T, ListT, ParentT >::setSize (int newSize) override virtual
Implements App::PropertyListsBase.
Reimplemented in App::PropertyLinkList.
setSize() [2/2]
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> virtual void App::PropertyListsT< T, ListT, ParentT >::setSize (int newSize, const_reference def) virtual
Reimplemented in App::PropertyLinkList.
Referenced by App::VRMLObject::onChanged(), App::VRMLObject::Restore(), App::PropertyListsT< T, ListT, ParentT >::set1Value(), and Gui::ViewProviderLink::updateElementList().
setValue() [1/2]
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> void App::PropertyListsT< T, ListT, ParentT >::setValue (const ListT & newValues = ListT())
References App::PropertyListsT< T, ListT, ParentT >::setValues().
setValue() [2/2]
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> void App::PropertyListsT< T, ListT, ParentT >::setValue (const_reference value)
References App::PropertyListsT< T, ListT, ParentT >::setValues().
Referenced by PartGui::ViewProviderPartExt::onChanged(), TechDraw::DrawViewMulti::onChanged(), DraftUtils::DraftDxfRead::OnReadText(), Import::ImpExpDxfRead::OnReadText(), App::PropertyListsT< T, ListT, ParentT >::setPyObject(), and Gui::ViewProviderLink::updateDataPrivate().
setValues()
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> virtual void App::PropertyListsT< T, ListT, ParentT >::setValues (const ListT & newValues = ListT()) virtual
Reimplemented in App::PropertyLinkList.
References App::AtomicPropertyChangeInterface< P >::AtomicPropertyChange::tryInvoke().
Referenced by TechDraw::DrawLeaderLine::adjustLastSegment(), Fem::ConstraintFluidBoundary::ConstraintFluidBoundary(), Fem::ConstraintHeatflux::ConstraintHeatflux(), Fem::ConstraintTemperature::ConstraintTemperature(), Fem::ConstraintTransform::ConstraintTransform(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), Fem::FemPostDataAlongLineFilter::GetAxisData(), Fem::FemPostDataAtPointFilter::GetPointData(), PartDesignGui::ViewProviderShapeBinder::highlightReferences(), PartDesignGui::ViewProviderDressUp::highlightReferences(), FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences(), Fem::FemVTKTools::importFreeCADResult(), Fem::ConstraintContact::onChanged(), Fem::ConstraintDisplacement::onChanged(), Fem::ConstraintFixed::onChanged(), Fem::ConstraintFluidBoundary::onChanged(), Fem::ConstraintHeatflux::onChanged(), Fem::ConstraintInitialTemperature::onChanged(), Fem::ConstraintPlaneRotation::onChanged(), Fem::ConstraintPressure::onChanged(), Fem::ConstraintSpring::onChanged(), Fem::ConstraintTemperature::onChanged(), Fem::ConstraintTransform::onChanged(), PartGui::ViewProviderPartExt::onChanged(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle(), SurfaceGui::FillingPanel::onSelectionChanged(), SurfaceGui::FillingEdgePanel::onSelectionChanged(), MeshGui::ViewProviderMesh::removeFacets(), TechDrawGui::TaskLeaderLine::restoreState(), Gui::ViewProviderLink::setElementColors(), App::PropertyListsT< T, ListT, ParentT >::setPyValues(), App::PropertyListsT< T, ListT, ParentT >::setValue(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderMultiFuse::updateData(), PartGui::ViewProviderMultiCommon::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderFillet::updateData(), and PartGui::ViewProviderChamfer::updateData().
Member Data Documentation
atomic_change
template<class T , class ListT = std::vector<T>, class ParentT = PropertyLists> friend App::PropertyListsT< T, ListT, ParentT >::atomic_change
The documentation for this class was generated from the following file:
FreeCAD/src/App/Property.h