FreeCAD: Gui::Dialog::ParameterValueItem Class Reference
Gui::Dialog::ParameterValueItem Class Reference abstract
The ParameterValueItem class represents items that are added to the ParameterValue listview.
#include <DlgParameterImp.h>
Public Member Functions
virtual void appendToGroup ()=0
Append this item as leaf to the parameter group.
virtual void changeValue ()=0
Opens an input dialog to change the value.
ParameterValueItem (QTreeWidget *parent, const Base::Reference< ParameterGrp > &hcGrp)
Constructor.
virtual void removeFromGroup ()=0
Remove the leaf from the parameter group.
virtual void setData (int column, int role, const QVariant &value)
If the name of the item has changed replace() is invoked.
virtual ~ParameterValueItem ()
Protected Member Functions
virtual void replace (const QString &oldName, const QString &newName)=0
Replaces the name of the leaf from oldName to newName.
Detailed Description
The ParameterValueItem class represents items that are added to the ParameterValue listview.
Each item represents a leaf in a parameter group and allows interaction with this leaf, such as modifying its name, its value or even remove it from the parameter group.
Author
Werner Mayer
Constructor & Destructor Documentation
ParameterValueItem()
ParameterValueItem::ParameterValueItem (QTreeWidget * parent, const Base::Reference< ParameterGrp > & hcGrp)
Constructor.
~ParameterValueItem()
ParameterValueItem::~ParameterValueItem () virtual
Member Function Documentation
appendToGroup()
virtual void Gui::Dialog::ParameterValueItem::appendToGroup () pure virtual
Append this item as leaf to the parameter group.
Implemented in Gui::Dialog::ParameterText, Gui::Dialog::ParameterInt, Gui::Dialog::ParameterUInt, Gui::Dialog::ParameterFloat, and Gui::Dialog::ParameterBool.
Referenced by Gui::Dialog::ParameterValue::onCreateBoolItem(), Gui::Dialog::ParameterValue::onCreateFloatItem(), Gui::Dialog::ParameterValue::onCreateIntItem(), Gui::Dialog::ParameterValue::onCreateTextItem(), and Gui::Dialog::ParameterValue::onCreateUIntItem().
changeValue()
virtual void Gui::Dialog::ParameterValueItem::changeValue () pure virtual
Opens an input dialog to change the value.
Implemented in Gui::Dialog::ParameterText, Gui::Dialog::ParameterInt, Gui::Dialog::ParameterUInt, Gui::Dialog::ParameterFloat, and Gui::Dialog::ParameterBool.
removeFromGroup()
virtual void Gui::Dialog::ParameterValueItem::removeFromGroup () pure virtual
Remove the leaf from the parameter group.
Implemented in Gui::Dialog::ParameterText, Gui::Dialog::ParameterInt, Gui::Dialog::ParameterUInt, Gui::Dialog::ParameterFloat, and Gui::Dialog::ParameterBool.
replace()
virtual void Gui::Dialog::ParameterValueItem::replace (const QString & oldName, const QString & newName) protected pure virtual
Replaces the name of the leaf from oldName to newName.
Implemented in Gui::Dialog::ParameterText, Gui::Dialog::ParameterInt, Gui::Dialog::ParameterUInt, Gui::Dialog::ParameterFloat, and Gui::Dialog::ParameterBool.
Referenced by setData().
setData()
void ParameterValueItem::setData (int column, int role, const QVariant & value) virtual
If the name of the item has changed replace() is invoked.
References replace(), and Gui::validateInput().
Referenced by package_list.PackageListItemModel::update_item_icon(), and package_list.PackageListItemModel::update_item_status().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgParameterImp.h
FreeCAD/src/Gui/DlgParameterImp.cpp