FreeCAD: Gui::IntSpinBox Class Reference
Gui::IntSpinBox Class Reference
The IntSpinBox class does exactly the same as Qt's QSpinBox but has expression support.
#include <SpinBox.h>
Public Member Functions
bool apply (const std::string &propName)
void bind (const App::ObjectIdentifier &_path)
IntSpinBox (QWidget *parent=0)
void keyPressEvent (QKeyEvent *event)
void paintEvent (QPaintEvent *event)
void resizeEvent (QResizeEvent *event)
void setExpression (boost::shared_ptr< App::Expression > expr)
virtual ~IntSpinBox ()
Public Member Functions inherited from Gui::ExpressionBinding
virtual bool apply ()
bool autoApply () const
virtual void bind (const App::Property &prop)
ExpressionBinding ()
QPixmap getIcon (const char *name, const QSize &size) const
bool hasExpression () const
bool isBound () const
void setAutoApply (bool value)
virtual ~ExpressionBinding ()
Additional Inherited Members
Protected Member Functions inherited from Gui::ExpressionBinding
void expressionChange (const App::ObjectIdentifier &id)
std::string getEscapedExpressionString () const
boost::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
const App::ObjectIdentifier & getPath () const
virtual void onChange ()
Protected Attributes inherited from Gui::ExpressionBinding
boost::signals2::scoped_connection connection
QPalette defaultPalette
int iconHeight
QLabel * iconLabel
bool m_autoApply
Detailed Description
The IntSpinBox class does exactly the same as Qt's QSpinBox but has expression support.
Author
Stefan Tröger
Constructor & Destructor Documentation
IntSpinBox()
IntSpinBox::IntSpinBox (QWidget * parent = 0)
References draftgeoutils.intersections::connect(), Gui::ExpressionBinding::defaultPalette, Gui::ExpressionBinding::getIcon(), Gui::ExpressionBinding::iconHeight, and Gui::ExpressionBinding::iconLabel.
~IntSpinBox()
IntSpinBox::~IntSpinBox () virtual
Member Function Documentation
apply()
bool IntSpinBox::apply (const std::string & propName) virtual
Reimplemented from Gui::ExpressionBinding.
References Gui::ExpressionBinding::apply(), and Gui::Command::Doc.
bind()
void IntSpinBox::bind (const App::ObjectIdentifier & _path) virtual
Reimplemented from Gui::ExpressionBinding.
References Gui::ExpressionBinding::bind(), and Gui::ExpressionBinding::iconLabel.
keyPressEvent()
void IntSpinBox::keyPressEvent (QKeyEvent * event)
References Gui::ExpressionBinding::isBound().
paintEvent()
void IntSpinBox::paintEvent (QPaintEvent * event)
References Gui::ExpressionBinding::hasExpression().
resizeEvent()
void IntSpinBox::resizeEvent (QResizeEvent * event)
References Gui::ExpressionBinding::defaultPalette, Base::Tools::fromStdString(), Gui::ExpressionBinding::getExpression(), Gui::ExpressionBinding::getIcon(), Gui::ExpressionBinding::iconHeight, Gui::ExpressionBinding::iconLabel, Gui::ExpressionBinding::isBound(), and DraftVecUtils::toString().
setExpression()
void IntSpinBox::setExpression (boost::shared_ptr< App::Expression > expr) virtual
Reimplemented from Gui::ExpressionBinding.
References Gui::ExpressionBinding::iconLabel, Gui::ExpressionBinding::isBound(), and Gui::ExpressionBinding::setExpression().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/SpinBox.h
Sources/FreeCAD/src/Gui/SpinBox.cpp