FreeCAD: SMESH_Pattern Class Reference
SMESH_Pattern Class Reference
#include <SMESH_Pattern.hxx>
Public Types
enum ErrorCode {
ERR_OK , ERR_READ_NB_POINTS , ERR_READ_POINT_COORDS , ERR_READ_TOO_FEW_POINTS ,
ERR_READ_3D_COORD , ERR_READ_NO_KEYPOINT , ERR_READ_BAD_INDEX , ERR_READ_ELEM_POINTS ,
ERR_READ_NO_ELEMS , ERR_READ_BAD_KEY_POINT , ERR_SAVE_NOT_LOADED , ERR_LOAD_EMPTY_SUBMESH ,
ERR_LOADF_NARROW_FACE , ERR_LOADF_CLOSED_FACE , ERR_LOADF_CANT_PROJECT , ERR_LOADV_BAD_SHAPE ,
ERR_LOADV_COMPUTE_PARAMS , ERR_APPL_NOT_COMPUTED , ERR_APPL_NOT_LOADED , ERR_APPL_BAD_DIMENTION ,
ERR_APPL_BAD_NB_VERTICES , ERR_APPLF_BAD_TOPOLOGY , ERR_APPLF_BAD_VERTEX , ERR_APPLF_INTERNAL_EEROR ,
ERR_APPLV_BAD_SHAPE , ERR_APPLF_BAD_FACE_GEOM , ERR_MAKEM_NOT_COMPUTED , ERR_UNEXPECTED
}
Public Member Functions
bool Apply (const SMDS_MeshFace *theFace, const int theNodeIndexOnKeyPoint1, const bool theReverse)
bool Apply (const SMDS_MeshVolume *theVolume, const int theNode000Index, const int theNode001Index)
bool Apply (const TopoDS_Face &theFace, const TopoDS_Vertex &theVertexOnKeyPoint1, const bool theReverse)
bool Apply (const TopoDS_Shell &theBlock, const TopoDS_Vertex &theVertex000, const TopoDS_Vertex &theVertex001)
bool Apply (SMESH_Mesh *theMesh, const SMDS_MeshFace *theFace, const TopoDS_Shape &theSurface, const int theNodeIndexOnKeyPoint1, const bool theReverse)
bool Apply (SMESH_Mesh *theMesh, std::set< const SMDS_MeshFace * > &theFaces, const int theNodeIndexOnKeyPoint1, const bool theReverse)
bool Apply (std::set< const SMDS_MeshVolume * > &theVolumes, const int theNode000Index, const int theNode001Index)
void Clear ()
void DumpPoints () const
const std::list< std::list< int > > & GetElementPointIDs (bool applied) const
ErrorCode GetErrorCode () const
const std::list< int > & GetKeyPointIDs () const
bool GetMappedPoints (std::list< const gp_XYZ * > &thePoints) const
bool GetPoints (std::list< const gp_XYZ * > &thePoints) const
TopoDS_Shape GetSubShape (const int i) const
bool Is2D () const
bool IsLoaded () const
bool Load (const char *theFileContents)
bool Load (SMESH_Mesh *theMesh, const TopoDS_Face &theFace, bool theProject=false, TopoDS_Vertex the1stVertex=TopoDS_Vertex())
bool Load (SMESH_Mesh *theMesh, const TopoDS_Shell &theBlock)
bool MakeMesh (SMESH_Mesh *theMesh, const bool toCreatePolygons=false, const bool toCreatePolyedrs=false)
bool Save (std::ostream &theFile)
SMESH_Pattern ()
Friends
std::ostream & operator<< (std::ostream &OS, const TPoint &p)
Member Enumeration Documentation
ErrorCode
enum SMESH_Pattern::ErrorCode
Enumerator
ERR_OK
ERR_READ_NB_POINTS
ERR_READ_POINT_COORDS
ERR_READ_TOO_FEW_POINTS
ERR_READ_3D_COORD
ERR_READ_NO_KEYPOINT
ERR_READ_BAD_INDEX
ERR_READ_ELEM_POINTS
ERR_READ_NO_ELEMS
ERR_READ_BAD_KEY_POINT
ERR_SAVE_NOT_LOADED
ERR_LOAD_EMPTY_SUBMESH
ERR_LOADF_NARROW_FACE
ERR_LOADF_CLOSED_FACE
ERR_LOADF_CANT_PROJECT
ERR_LOADV_BAD_SHAPE
ERR_LOADV_COMPUTE_PARAMS
ERR_APPL_NOT_COMPUTED
ERR_APPL_NOT_LOADED
ERR_APPL_BAD_DIMENTION
ERR_APPL_BAD_NB_VERTICES
ERR_APPLF_BAD_TOPOLOGY
ERR_APPLF_BAD_VERTEX
ERR_APPLF_INTERNAL_EEROR
ERR_APPLV_BAD_SHAPE
ERR_APPLF_BAD_FACE_GEOM
ERR_MAKEM_NOT_COMPUTED
ERR_UNEXPECTED
Constructor & Destructor Documentation
SMESH_Pattern()
SMESH_Pattern::SMESH_Pattern ()
Member Function Documentation
Apply() [1/7]
bool SMESH_Pattern::Apply (const SMDS_MeshFace * theFace, const int theNodeIndexOnKeyPoint1, const bool theReverse)
References SMDS_MeshElement::NbCornerNodes(), SMDS_MeshElement::nodeIterator(), and draftgeoutils.general::vec().
Apply() [2/7]
bool SMESH_Pattern::Apply (const SMDS_MeshVolume * theVolume, const int theNode000Index, const int theNode001Index)
References SMESH_Block::ID_Shell, and SMESH_Block::ID_V000.
Apply() [3/7]
bool SMESH_Pattern::Apply (const TopoDS_Face & theFace, const TopoDS_Vertex & theVertexOnKeyPoint1, const bool theReverse)
References SMESH_Block::GetOrderedEdges().
Referenced by StdMeshers_Projection_2D::Compute().
Apply() [4/7]
bool SMESH_Pattern::Apply (const TopoDS_Shell & theBlock, const TopoDS_Vertex & theVertex000, const TopoDS_Vertex & theVertex001)
Apply() [5/7]
bool SMESH_Pattern::Apply (SMESH_Mesh * theMesh, const SMDS_MeshFace * theFace, const TopoDS_Shape & theSurface, const int theNodeIndexOnKeyPoint1, const bool theReverse)
References SMESH_MesherHelper::GetNodeUV(), SMESH_MesherHelper::GetNodeUVneedInFaceNode(), SMESH_MesherHelper::IsSeamShape(), SMDS_MeshElement::NbNodes(), SMDS_MeshElement::nodesIterator(), and SMESH_MesherHelper::SetSubShape().
Apply() [6/7]
bool SMESH_Pattern::Apply (SMESH_Mesh * theMesh, std::set< const SMDS_MeshFace * > & theFaces, const int theNodeIndexOnKeyPoint1, const bool theReverse)
Apply() [7/7]
bool SMESH_Pattern::Apply (std::set< const SMDS_MeshVolume * > & theVolumes, const int theNode000Index, const int theNode001Index)
References SMESH_Block::GetEdgeVertexIDs(), SMESH_Block::GetFaceEdgesIDs(), SMESH_Block::ID_F1yz, SMESH_Block::ID_V000, SMESH_Block::IsEdgeID(), and SMESH_Block::IsVertexID().
Clear()
void SMESH_Pattern::Clear ()
DumpPoints()
void SMESH_Pattern::DumpPoints () const
GetElementPointIDs()
const std::list< std::list< int > >& SMESH_Pattern::GetElementPointIDs (bool applied) const
GetErrorCode()
ErrorCode SMESH_Pattern::GetErrorCode () const
Referenced by StdMeshers_Projection_2D::Compute().
GetKeyPointIDs()
const std::list< int >& SMESH_Pattern::GetKeyPointIDs () const
GetMappedPoints()
bool SMESH_Pattern::GetMappedPoints (std::list< const gp_XYZ * > & thePoints) const
GetPoints()
bool SMESH_Pattern::GetPoints (std::list< const gp_XYZ * > & thePoints) const
GetSubShape()
TopoDS_Shape SMESH_Pattern::GetSubShape (const int i) const
Is2D()
bool SMESH_Pattern::Is2D () const
IsLoaded()
bool SMESH_Pattern::IsLoaded () const
Load() [1/3]
bool SMESH_Pattern::Load (const char * theFileContents)
Referenced by StdMeshers_Projection_2D::Compute().
Load() [2/3]
bool SMESH_Pattern::Load (SMESH_Mesh * theMesh, const TopoDS_Face & theFace, bool theProject = false, TopoDS_Vertex the1stVertex = TopoDS_Vertex())
References DraftVecUtils::dist(), SMDS_Mesh::elementsIterator(), SMESHDS_SubMesh::GetElements(), SMESH_Mesh::GetMeshDS(), SMDS_Mesh::GetMeshInfo(), SMDS_MeshElement::GetNode(), SMESHDS_SubMesh::GetNodes(), SMESH_MesherHelper::GetNodeUV(), SMESH_Block::GetOrderedEdges(), SMDS_MeshNode::GetPosition(), SMDS_MeshElement::getshapeId(), SMDS_EdgePosition::GetUParameter(), SMESH_MesherHelper::HasSeam(), SMESH_Mesh::IsMainShape(), SMESH_MesherHelper::IsMedium(), SMESH_MesherHelper::IsRealSeam(), SMESH_MesherHelper::IsSeamShape(), SMESHDS_Mesh::MeshElements(), SMDS_MeshElement::NbCornerNodes(), SMESHDS_SubMesh::NbElements(), SMDS_Mesh::NbFaces(), SMDS_MeshInfo::NbFaces(), SMESHDS_SubMesh::NbNodes(), SMDS_MeshElement::nodesIterator(), DraftVecUtils::project(), draftfunctions.scale::scale(), SMESH_MesherHelper::SetSubShape(), draftgeoutils.general::v1(), SMESH_MesherHelper::WrapIndex(), SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
Load() [3/3]
bool SMESH_Pattern::Load (SMESH_Mesh * theMesh, const TopoDS_Shell & theBlock)
References SMESH_Block::GetCoordIndOnEdge(), SMESHDS_SubMesh::GetElements(), SMDS_MeshElement::GetNode(), SMESHDS_SubMesh::GetNodes(), SMDS_MeshNode::GetPosition(), SMDS_EdgePosition::GetUParameter(), SMESH_Block::IsForwardEdge(), SMESH_MeshEditor::IsMedium(), SMDS_MeshElement::NbCornerNodes(), SMESHDS_SubMesh::NbNodes(), SMESH_Mesh::NbVolumes(), draftgeoutils.general::v1(), SMDS_MeshNode::X(), SMDS_MeshNode::Y(), and SMDS_MeshNode::Z().
MakeMesh()
bool SMESH_Pattern::MakeMesh (SMESH_Mesh * theMesh, const bool toCreatePolygons = false, const bool toCreatePolyedrs = false)
References SMESHDS_Mesh::AddNode(), SMESH_MesherHelper::CheckNodeU(), SMESHDS_Mesh::compactMesh(), SMESH_MesherHelper::GetCommonAncestor(), SMESH_Mesh::GetMeshDS(), SMESH_MesherHelper::GetSubShapeByNode(), SMESH_Mesh::HasShapeToMesh(), SMESH_MesherHelper::IsSubShape(), SMESHDS_Mesh::SetNodeInVolume(), SMESHDS_Mesh::SetNodeOnEdge(), SMESHDS_Mesh::SetNodeOnFace(), SMESHDS_Mesh::SetNodeOnVertex(), SMESH_MesherHelper::SetSubShape(), and SMESH_MesherHelper::ToFixNodeParameters().
Referenced by StdMeshers_Projection_2D::Compute().
Save()
bool SMESH_Pattern::Save (std::ostream & theFile)
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & OS, const TPoint & p) friend
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_Pattern.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/SMESH_Pattern.cpp