FreeCAD: SMESHDS_TSubMeshHolder< SUBMESH > Class Template Reference
SMESHDS_TSubMeshHolder< SUBMESH > Class Template Reference
A binder of a sub-mesh to its ID which can be negative. Provides fast access to a sub-mesh by its ID.
#include <SMESHDS_TSubMeshHolder.hxx>
Classes
struct Iterator
Public Member Functions
void Add (int id, SUBMESH *sm)
void DeleteAll ()
SUBMESH * Get (int id) const
SMDS_Iterator< SUBMESH * > * GetIterator (const bool reverse=false) const
int GetMaxID () const
int GetMinID () const
~SMESHDS_TSubMeshHolder ()
Detailed Description
template<class SUBMESH>
class SMESHDS_TSubMeshHolder< SUBMESH >
A binder of a sub-mesh to its ID which can be negative. Provides fast access to a sub-mesh by its ID.
Issue 52457: Addition of hypotheses is 8 time longer than meshing.
Constructor & Destructor Documentation
~SMESHDS_TSubMeshHolder()
template<class SUBMESH > SMESHDS_TSubMeshHolder< SUBMESH >::~SMESHDS_TSubMeshHolder ()
References SMESHDS_TSubMeshHolder< SUBMESH >::DeleteAll().
Member Function Documentation
Add()
template<class SUBMESH > void SMESHDS_TSubMeshHolder< SUBMESH >::Add (int id, SUBMESH * sm)
Referenced by SMESHDS_Mesh::NewSubMesh().
DeleteAll()
template<class SUBMESH > void SMESHDS_TSubMeshHolder< SUBMESH >::DeleteAll ()
Referenced by SMESHDS_Mesh::ShapeToMesh(), and SMESHDS_TSubMeshHolder< SUBMESH >::~SMESHDS_TSubMeshHolder().
Get()
template<class SUBMESH > SUBMESH * SMESHDS_TSubMeshHolder< SUBMESH >::Get (int id) const
Referenced by SMESHDS_Mesh::HasMeshElements(), and SMESHDS_Mesh::MeshElements().
GetIterator()
template<class SUBMESH > SMDS_Iterator< SUBMESH * > * SMESHDS_TSubMeshHolder< SUBMESH >::GetIterator (const bool reverse = false) const
References SMESHDS_TSubMeshHolder< SUBMESH >::GetMaxID(), SMESHDS_TSubMeshHolder< SUBMESH >::GetMinID(), and SMESHDS_TSubMeshHolder< SUBMESH >::Iterator::init().
Referenced by SMESHDS_Mesh::SubMeshes().
GetMaxID()
template<class SUBMESH > int SMESHDS_TSubMeshHolder< SUBMESH >::GetMaxID () const
Referenced by SMESHDS_TSubMeshHolder< SUBMESH >::GetIterator(), and SMESHDS_Mesh::MaxSubMeshIndex().
GetMinID()
template<class SUBMESH > int SMESHDS_TSubMeshHolder< SUBMESH >::GetMinID () const
Referenced by SMESHDS_TSubMeshHolder< SUBMESH >::GetIterator().
The documentation for this class was generated from the following file:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESHDS_TSubMeshHolder.hxx