FreeCAD: shipGZ.Tools Namespace Reference
shipGZ.Tools Namespace Reference
Functions
def gz (lc, rolls, var_trim=True)
def solve (ship, weights, tanks, rolls, var_trim=True)
def solve_point (W, COG, TW, VOLS, ship, tanks, roll, var_trim=True)
Variables
DENS = Units.parseQuantity("1025 kg/m^3")
G = Units.parseQuantity("9.81 m/s^2")
int MAX_EQUILIBRIUM_ITERS = 10
float TRIM_RELAX_FACTOR = 10.0
Function Documentation
gz()
def shipGZ.Tools.gz (lc, rolls, var_trim = True)
Compute the ship GZ stability curve
Position arguments:
lc -- Load condition spreadsheet
rolls -- List of roll angles to compute
Keyword arguments:
var_trim -- True if the equilibrium trim should be computed for each roll
angle, False if null trim angle can be used instead.
Returned value:
List of GZ curve points. Each point contains the GZ stability length, the
equilibrium draft, and the equilibrium trim angle (0 deg if var_trim is
False)
References shipGZ.Tools.solve().
solve()
def shipGZ.Tools.solve (ship, weights, tanks, rolls, var_trim = True)
Compute the ship GZ stability curve
Position arguments:
ship -- Ship object
weights -- List of weights to consider
tanks -- List of tanks to consider (each one should be a tuple with the
tank instance, the density of the fluid inside, and the filling level ratio)
rolls -- List of roll angles
Keyword arguments:
var_trim -- True if the equilibrium trim should be computed for each roll
angle, False if null trim angle can be used instead.
Returned value:
List of GZ curve points. Each point contains the GZ stability length, the
equilibrium draft, and the equilibrium trim angle (0 deg if var_trim is
False)
References shipGZ.Tools.solve_point().
Referenced by shipGZ.Tools.gz().
solve_point()
def shipGZ.Tools.solve_point (W, COG, TW, VOLS, ship, tanks, roll, var_trim = True)
 Compute the ship GZ value.
@param W Empty ship weight.
@param COG Empty ship Center of mass.
@param TW Tanks weights.
@param VOLS List of tank volumes.
@param tanks Considered tanks.
@param roll Roll angle.
@param var_trim True if the trim angle should be recomputed at each roll
angle, False otherwise.
@return GZ value, equilibrium draft, and equilibrium trim angle (0 if
variable trim has not been requested)
Referenced by shipGZ.Tools.solve().
Variable Documentation
DENS
shipGZ.Tools.DENS = Units.parseQuantity("1025 kg/m^3")
G
shipGZ.Tools.G = Units.parseQuantity("9.81 m/s^2")
MAX_EQUILIBRIUM_ITERS
int shipGZ.Tools.MAX_EQUILIBRIUM_ITERS = 10
TRIM_RELAX_FACTOR
float shipGZ.Tools.TRIM_RELAX_FACTOR = 10.0