FreeCAD: Gui::NS::AwaitingReleaseState Class Reference
Gui::NS::AwaitingReleaseState Class Reference
Public Types
typedef sc::custom_reaction< NS::Event > reactions
Public Member Functions
AwaitingReleaseState (my_context ctx)
sc::result react (const NS::Event &ev)
virtual ~AwaitingReleaseState ()
Member Typedef Documentation
reactions
typedef sc::custom_reaction<NS::Event> Gui::NS::AwaitingReleaseState::reactions
Constructor & Destructor Documentation
AwaitingReleaseState()
Gui::NS::AwaitingReleaseState::AwaitingReleaseState (my_context ctx)
References Base::Console(), and Base::ConsoleSingleton::Log().
~AwaitingReleaseState()
virtual Gui::NS::AwaitingReleaseState::~AwaitingReleaseState () virtual
Member Function Documentation
react()
sc::result Gui::NS::AwaitingReleaseState::react (const NS::Event & ev)
References Gui::NS::Event::flags, Gui::NS::Event::isGestureActive(), Gui::NS::Event::isLocation2Event(), Gui::NS::Event::isMouseButtonEvent(), Gui::NS::Event::isPress(), Gui::NS::Event::isRelease(), and Gui::NS::Event::mbstate().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/GestureNavigationStyle.cpp