FreeCAD: PathScripts.PathJobGui Namespace Reference
PathScripts.PathJobGui Namespace Reference
Classes
class StockCreateBoxEdit
class StockCreateCylinderEdit
class StockEdit
class StockFromBaseBoundBoxEdit
class StockFromExistingEdit
class TaskPanel
class ViewProvider
Functions
def Create (base, template=None)
def selectionEx ()
def translate (context, text, disambig=None)
Variables
Draft = LazyLoader('Draft', globals(), 'Draft')
DraftVecUtils = LazyLoader('DraftVecUtils', globals(), 'DraftVecUtils')
bool LOGLEVEL = False
Part = LazyLoader('Part', globals(), 'Part')
Function Documentation
Create()
def PathScripts.PathJobGui.Create (base, template = None)
Create(base, template) ... creates a job instance for the given base object
using template to configure it.
selectionEx()
def PathScripts.PathJobGui.selectionEx ()
Referenced by PathScripts.PathJobGui.TaskPanel.modelMove(), PathScripts.PathJobGui.TaskPanel.modelRotate(), and PathScripts.PathJobGui.TaskPanel.modelSet0().
translate()
def PathScripts.PathJobGui.translate (context, text, disambig = None)
Variable Documentation
Draft
PathScripts.PathJobGui.Draft = LazyLoader('Draft', globals(), 'Draft')
DraftVecUtils
PathScripts.PathJobGui.DraftVecUtils = LazyLoader('DraftVecUtils', globals(), 'DraftVecUtils')
LOGLEVEL
bool PathScripts.PathJobGui.LOGLEVEL = False
Part
PathScripts.PathJobGui.Part = LazyLoader('Part', globals(), 'Part')