FreeCAD: ParameterManager Class Reference
ParameterManager Class Reference
The parameter manager class This class manages a parameter XML document.
#include <Parameter.h>
Public Member Functions
void CheckDocument () const
void CreateDocument ()
int LoadDocument (const char *sFileName)
int LoadDocument (const XERCES_CPP_NAMESPACE_QUALIFIER InputSource &)
bool LoadOrCreateDocument (const char *sFileName)
ParameterManager ()
Default construction.
void SaveDocument (const char *sFileName) const
void SaveDocument (XERCES_CPP_NAMESPACE_QUALIFIER XMLFormatTarget *pFormatTarget) const
~ParameterManager ()
Destruction complete destruction of the object.
Public Member Functions inherited from ParameterGrp
void copyTo (Base::Reference< ParameterGrp >)
make a deep copy to the other group
void insertTo (Base::Reference< ParameterGrp >)
overwrite everything similar, leave the others alone
void exportTo (const char *FileName)
export this group to a file
void importFrom (const char *FileName)
import from a file to this group
void insert (const char *FileName)
insert from a file to this group, overwrite only the similar
bool GetBool (const char *Name, bool bPreset=false) const
read bool values or give default
void SetBool (const char *Name, bool bValue)
set a bool value
std::vector< bool > GetBools (const char *sFilter=nullptr) const
get a vector of all bool values in this group
std::vector< std::pair< std::string, bool > > GetBoolMap (const char *sFilter=nullptr) const
get a map with all bool values and the keys of this group
void RemoveBool (const char *Name)
remove a bool value from this group
long GetInt (const char *Name, long lPreset=0) const
read bool values or give default
void SetInt (const char *Name, long lValue)
set a int value
std::vector< long > GetInts (const char *sFilter=nullptr) const
get a vector of all int values in this group
std::vector< std::pair< std::string, long > > GetIntMap (const char *sFilter=nullptr) const
get a map with all int values and the keys of this group
void RemoveInt (const char *Name)
remove a int value from this group
unsigned long GetUnsigned (const char *Name, unsigned long lPreset=0) const
read uint values or give default
void SetUnsigned (const char *Name, unsigned long lValue)
set a uint value
std::vector< unsigned long > GetUnsigneds (const char *sFilter=nullptr) const
get a vector of all uint values in this group
std::vector< std::pair< std::string, unsigned long > > GetUnsignedMap (const char *sFilter=nullptr) const
get a map with all uint values and the keys of this group
void RemoveUnsigned (const char *Name)
remove a uint value from this group
double GetFloat (const char *Name, double dPreset=0.0) const
set a float value
void SetFloat (const char *Name, double dValue)
read float values or give default
std::vector< double > GetFloats (const char *sFilter=nullptr) const
get a vector of all float values in this group
std::vector< std::pair< std::string, double > > GetFloatMap (const char *sFilter=nullptr) const
get a map with all float values and the keys of this group
void RemoveFloat (const char *Name)
remove a float value from this group
void SetBlob (const char *Name, void *pValue, long lLength)
set a blob value
void GetBlob (const char *Name, void *pBuf, long lMaxLength, void *pPreset=nullptr) const
read blob values or give default
void RemoveBlob (const char *Name)
remove a blob value from this group
Base::Reference< ParameterGrp > GetGroup (const char *Name)
get a handle to a sub group or create one
std::vector< Base::Reference< ParameterGrp > > GetGroups ()
get a vector of all sub groups in this group
bool IsEmpty () const
test if this group is empty
bool HasGroup (const char *Name) const
test if a special sub group is in this group
void RemoveGrp (const char *Name)
remove a sub group from this group
bool RenameGrp (const char *OldName, const char *NewName)
rename a sub group from this group
void Clear ()
clears everything in this group (all types)
void SetASCII (const char *Name, const char *sValue)
set a string value
std::string GetASCII (const char *Name, const char *pPreset=nullptr) const
read a string values
void RemoveASCII (const char *Name)
remove a string value from this group
std::vector< std::string > GetASCIIs (const char *sFilter=nullptr) const
Return all string elements in this group as a vector of strings Its also possible to set a filter criteria.
std::vector< std::pair< std::string, std::string > > GetASCIIMap (const char *sFilter=nullptr) const
Same as GetASCIIs() but with key,value map.
const char * GetGroupName () const
returns the name
void NotifyAll ()
Notifies all observers for all entries except of sub-groups.
Public Member Functions inherited from Base::Handled
int getRefCount () const
Handled ()
const Handled & operator= (const Handled &)
void ref () const
void unref () const
virtual ~Handled ()
Public Member Functions inherited from Base::Subject< const char * >
void Attach (Observer< const char * > *ToObserv)
Attach an Observer Attach an Observer to the list of Observers which get called when Notify is called.
void ClearObserver ()
Clears the list of all registered observers.
void Detach (Observer< const char * > *ToObserv)
Detach an Observer Detach an Observer from the list of Observers which get called when Notify is called.
Observer< const char * > * Get (const char *Name)
Get an Observer by name Get a observer by name if the observer reimplements the Name() mthode.
void Notify (const char * rcReason)
Notify all Observers Send a message to all Observers attached to this subject.
Subject ()
A constructor.
virtual ~Subject ()
A destructor.
Static Public Member Functions
static void Init ()
static void Terminate ()
Parameter serialization
void SetSerializer (ParameterSerializer *)
Sets a serializer. The ParameterManager takes ownership of the serializer.
bool HasSerializer () const
Returns true if a serializer is set, otherwise false is returned.
int LoadDocument ()
Loads an XML document by calling the serializer's load method.
bool LoadOrCreateDocument ()
Loads or creates an XML document by calling the serializer's load method.
void SaveDocument () const
Saves an XML document by calling the serializer's save method.
Additional Inherited Members
Public Types inherited from ParameterGrp
typedef Base::Reference< ParameterGrp > handle
type of the handle
Public Types inherited from Base::Subject< const char * >
typedef const char * MessageType
typedef Observer< const char * > ObserverType
typedef Subject< const char * > SubjectType
Protected Member Functions inherited from ParameterGrp
ParameterGrp (XERCES_CPP_NAMESPACE_QUALIFIER DOMElement *GroupNode=nullptr, const char *sName=nullptr)
constructor is protected (handle concept)
~ParameterGrp ()
destructor is protected (handle concept)
bool ShouldRemove () const
XERCES_CPP_NAMESPACE_QUALIFIER DOMElement * FindNextElement (XERCES_CPP_NAMESPACE_QUALIFIER DOMNode *Prev, const char *Type) const
XERCES_CPP_NAMESPACE_QUALIFIER DOMElement * FindElement (XERCES_CPP_NAMESPACE_QUALIFIER DOMElement *Start, const char *Type, const char *Name=nullptr) const
Find an element specified by Type and Name Search in the parent element Start for the first occurrence of an element of Type and with the attribute Name=Name.
XERCES_CPP_NAMESPACE_QUALIFIER DOMElement * FindOrCreateElement (XERCES_CPP_NAMESPACE_QUALIFIER DOMElement *Start, const char *Type, const char *Name) const
Find an element specified by Type and Name or create it if not found Search in the parent element Start for the first occurrence of an element of Type and with the attribute Name=Name.
XERCES_CPP_NAMESPACE_QUALIFIER DOMNode * FindAttribute (XERCES_CPP_NAMESPACE_QUALIFIER DOMNode *Node, const char *Name) const
Find an attribute specified by Name.
Detailed Description
The parameter manager class This class manages a parameter XML document.
Does loading, saving and handling the DOM document.
See also
ParameterGrp
Constructor & Destructor Documentation
ParameterManager()
ParameterManager::ParameterManager ()
Default construction.
References Init().
~ParameterManager()
ParameterManager::~ParameterManager ()
Destruction complete destruction of the object.
Member Function Documentation
CheckDocument()
void ParameterManager::CheckDocument () const
References Base::Console(), Base::ConsoleSingleton::Error(), and SaveDocument().
Referenced by Gui::Dialog::DlgParameterImp::onChangeParameterSet().
CreateDocument()
void ParameterManager::CreateDocument ()
Referenced by ParameterGrp::exportTo(), LoadOrCreateDocument(), and Gui::PreferencePackManager::save().
HasSerializer()
bool ParameterManager::HasSerializer () const
Returns true if a serializer is set, otherwise false is returned.
Referenced by Gui::Dialog::DlgParameterImp::onChangeParameterSet().
Init()
void ParameterManager::Init () static
Referenced by ParameterManager().
LoadDocument() [1/3]
int ParameterManager::LoadDocument ()
Loads an XML document by calling the serializer's load method.
References ParameterSerializer::LoadDocument().
Referenced by LoadDocument(), and LoadOrCreateDocument().
LoadDocument() [2/3]
int ParameterManager::LoadDocument (const char * sFileName)
References LoadDocument(), and XStr::unicodeForm().
Referenced by Gui::Dialog::DlgRevertToBackupConfigImp::accept(), Gui::PreferencePack::apply(), ParameterGrp::importFrom(), ParameterGrp::insert(), ParameterSerializer::LoadDocument(), and Gui::PreferencePackManager::save().
LoadDocument() [3/3]
int ParameterManager::LoadDocument (const XERCES_CPP_NAMESPACE_QUALIFIER InputSource & inputSource)
References ParameterGrp::FindElement().
LoadOrCreateDocument() [1/2]
bool ParameterManager::LoadOrCreateDocument ()
Loads or creates an XML document by calling the serializer's load method.
References ParameterSerializer::LoadOrCreateDocument().
LoadOrCreateDocument() [2/2]
bool ParameterManager::LoadOrCreateDocument (const char * sFileName)
References CreateDocument(), and LoadDocument().
Referenced by ParameterSerializer::LoadOrCreateDocument().
SaveDocument() [1/3]
void ParameterManager::SaveDocument () const
Saves an XML document by calling the serializer's save method.
References ParameterSerializer::SaveDocument().
Referenced by CheckDocument(), and SaveDocument().
SaveDocument() [2/3]
void ParameterManager::SaveDocument (const char * sFileName) const
References SaveDocument().
Referenced by Gui::RecentFilesAction::appendFile(), Gui::RecentMacrosAction::appendFile(), Gui::PreferencePack::apply(), ParameterGrp::exportTo(), Gui::Dialog::DlgParameterImp::on_buttonSaveToDisk_clicked(), Gui::PreferencePackManager::save(), and ParameterSerializer::SaveDocument().
SaveDocument() [3/3]
void ParameterManager::SaveDocument (XERCES_CPP_NAMESPACE_QUALIFIER XMLFormatTarget * pFormatTarget) const
SetSerializer()
void ParameterManager::SetSerializer (ParameterSerializer * ps)
Sets a serializer. The ParameterManager takes ownership of the serializer.
Terminate()
void ParameterManager::Terminate () static
References XMLTools::terminate().
Referenced by App::Application::destruct().
The documentation for this class was generated from the following files:
FreeCAD/src/Base/Parameter.h
FreeCAD/src/Base/Parameter.cpp