FreeCAD: NETGENPlugin_Hypothesis Class Reference
NETGENPlugin_Hypothesis Class Reference
#include <NETGENPlugin_Hypothesis.hxx>
Public Types
enum Fineness {
VeryCoarse, Coarse, Moderate, Fine,
VeryFine, UserDefined
}
typedef std::map< std::string, double > TLocalSize
Public Types inherited from SMESH_Hypothesis
enum Hypothesis_Status {
HYP_OK = 0, HYP_MISSING, HYP_CONCURENT, HYP_BAD_PARAMETER,
HYP_HIDDEN_ALGO, HYP_HIDING_ALGO, HYP_UNKNOWN_FATAL, HYP_INCOMPATIBLE,
HYP_NOTCONFORM, HYP_ALREADY_EXIST, HYP_BAD_DIM, HYP_BAD_SUBSHAPE,
HYP_BAD_GEOMETRY, HYP_NEED_SHAPE, HYP_INCOMPAT_HYPS
}
Public Types inherited from SMESHDS_Hypothesis
enum hypothesis_type {
PARAM_ALGO, ALGO_0D, ALGO_1D, ALGO_2D,
ALGO_3D
}
Public Member Functions
Fineness GetFineness () const
bool GetFuseEdges () const
double GetGrowthRate () const
double GetLocalSizeOnEntry (const std::string &entry)
const TLocalSize & GetLocalSizesAndEntries () const
double GetMaxSize () const
double GetMinSize () const
double GetNbSegPerEdge () const
double GetNbSegPerRadius () const
bool GetOptimize () const
bool GetQuadAllowed () const
bool GetSecondOrder () const
bool GetSurfaceCurvature () const
virtual istream & LoadFrom (istream &load)
NETGENPlugin_Hypothesis (int hypId, int studyId, SMESH_Gen *gen)
virtual ostream & SaveTo (ostream &save)
void SetFineness (Fineness theFineness)
void SetFuseEdges (bool theVal)
void SetGrowthRate (double theRate)
void SetLocalSizeOnEntry (const std::string &entry, double localSize)
void SetMaxSize (double theSize)
void SetMinSize (double theSize)
void SetNbSegPerEdge (double theVal)
void SetNbSegPerRadius (double theVal)
void SetOptimize (bool theVal)
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)
Does nothing.
void SetQuadAllowed (bool theVal)
void SetSecondOrder (bool theVal)
void SetSurfaceCurvature (bool theVal)
void UnsetLocalSizeOnEntry (const std::string &entry)
Public Member Functions inherited from SMESH_Hypothesis
void ClearParameters ()
virtual bool DataDependOnParams () const
The returned value is used by NotifySubMeshesHypothesisModification() to decide to call subMesh->AlgoStateEngine(MODIF_HYP, hyp) or not if subMesh is ready to be computed (algo+hyp==OK) but not yet computed. True result is reasonable for example if EventListeners depend on parameters of hypothesis.
virtual int GetDim () const
SMESH_Gen * GetGen () const
char * GetLastParameters () const
virtual const char * GetLibName () const
SMESH_Mesh * GetMeshByPersistentID (int id)
Find a mesh with given persistent ID.
char * GetParameters () const
virtual int GetShapeType () const
int GetStudyId () const
virtual bool IsAuxiliary () const
Return true if me is an auxiliary hypothesis.
virtual void NotifySubMeshesHypothesisModification ()
void SetLastParameters (const char *theParameters)
void SetLibName (const char *theLibName)
void SetParameters (const char *theParameters)
SMESH_Hypothesis (int hypId, int studyId, SMESH_Gen *gen)
virtual ~SMESH_Hypothesis ()
Public Member Functions inherited from SMESHDS_Hypothesis
int GetID () const
const char * GetName () const
int GetType () const
bool IsSameName (const SMESHDS_Hypothesis &other) const
Compare types of hypotheses.
bool operator!= (const SMESHDS_Hypothesis &other) const
virtual bool operator== (const SMESHDS_Hypothesis &other) const
SMESHDS_Hypothesis (int hypId)
virtual ~SMESHDS_Hypothesis ()
Static Public Member Functions
static Fineness GetDefaultFineness ()
static bool GetDefaultFuseEdges ()
static double GetDefaultGrowthRate ()
static TLocalSize GetDefaultLocalSize ()
static double GetDefaultMaxSize ()
static double GetDefaultNbSegPerEdge ()
static double GetDefaultNbSegPerRadius ()
static bool GetDefaultOptimize ()
static bool GetDefaultQuadAllowed ()
static bool GetDefaultSecondOrder ()
static bool GetDefaultSurfaceCurvature ()
Static Public Member Functions inherited from SMESH_Hypothesis
static bool IsStatusFatal (Hypothesis_Status theStatus)
Friends
NETGENPLUGIN_EXPORT ostream & operator<< (ostream &save, NETGENPlugin_Hypothesis &hyp)
NETGENPLUGIN_EXPORT istream & operator>> (istream &load, NETGENPlugin_Hypothesis &hyp)
Member Typedef Documentation
TLocalSize
typedef std::map<std::string, double> NETGENPlugin_Hypothesis::TLocalSize
Member Enumeration Documentation
Fineness
enum NETGENPlugin_Hypothesis::Fineness
Enumerator
VeryCoarse
Coarse
Moderate
Fine
VeryFine
UserDefined
Constructor & Destructor Documentation
NETGENPlugin_Hypothesis()
NETGENPlugin_Hypothesis::NETGENPlugin_Hypothesis (int hypId, int studyId, SMESH_Gen * gen)
Member Function Documentation
GetDefaultFineness()
NETGENPlugin_Hypothesis::Fineness NETGENPlugin_Hypothesis::GetDefaultFineness () static
References Moderate.
Referenced by NETGENPlugin_Mesher::SetDefaultParameters().
GetDefaultFuseEdges()
bool NETGENPlugin_Hypothesis::GetDefaultFuseEdges () static
Referenced by LoadFrom(), and NETGENPlugin_Mesher::SetDefaultParameters().
GetDefaultGrowthRate()
double NETGENPlugin_Hypothesis::GetDefaultGrowthRate () static
Referenced by NETGENPlugin_Mesher::SetDefaultParameters().
GetDefaultLocalSize()
static TLocalSize NETGENPlugin_Hypothesis::GetDefaultLocalSize () static
GetDefaultMaxSize()
double NETGENPlugin_Hypothesis::GetDefaultMaxSize () static
GetDefaultNbSegPerEdge()
double NETGENPlugin_Hypothesis::GetDefaultNbSegPerEdge () static
Referenced by NETGENPlugin_Mesher::SetDefaultParameters().
GetDefaultNbSegPerRadius()
double NETGENPlugin_Hypothesis::GetDefaultNbSegPerRadius () static
Referenced by NETGENPlugin_Mesher::SetDefaultParameters().
GetDefaultOptimize()
bool NETGENPlugin_Hypothesis::GetDefaultOptimize () static
GetDefaultQuadAllowed()
bool NETGENPlugin_Hypothesis::GetDefaultQuadAllowed () static
Referenced by LoadFrom(), and NETGENPlugin_Mesher::SetDefaultParameters().
GetDefaultSecondOrder()
bool NETGENPlugin_Hypothesis::GetDefaultSecondOrder () static
Referenced by NETGENPlugin_Mesher::SetDefaultParameters().
GetDefaultSurfaceCurvature()
bool NETGENPlugin_Hypothesis::GetDefaultSurfaceCurvature () static
Referenced by LoadFrom(), and NETGENPlugin_Mesher::SetDefaultParameters().
GetFineness()
Fineness NETGENPlugin_Hypothesis::GetFineness () const
GetFuseEdges()
bool NETGENPlugin_Hypothesis::GetFuseEdges () const
GetGrowthRate()
double NETGENPlugin_Hypothesis::GetGrowthRate () const
GetLocalSizeOnEntry()
double NETGENPlugin_Hypothesis::GetLocalSizeOnEntry (const std::string & entry)
GetLocalSizesAndEntries()
const TLocalSize& NETGENPlugin_Hypothesis::GetLocalSizesAndEntries () const
GetMaxSize()
double NETGENPlugin_Hypothesis::GetMaxSize () const
GetMinSize()
double NETGENPlugin_Hypothesis::GetMinSize () const
GetNbSegPerEdge()
double NETGENPlugin_Hypothesis::GetNbSegPerEdge () const
GetNbSegPerRadius()
double NETGENPlugin_Hypothesis::GetNbSegPerRadius () const
GetOptimize()
bool NETGENPlugin_Hypothesis::GetOptimize () const
GetQuadAllowed()
bool NETGENPlugin_Hypothesis::GetQuadAllowed () const
GetSecondOrder()
bool NETGENPlugin_Hypothesis::GetSecondOrder () const
GetSurfaceCurvature()
bool NETGENPlugin_Hypothesis::GetSurfaceCurvature () const
LoadFrom()
istream & NETGENPlugin_Hypothesis::LoadFrom (istream & load) virtual
Implements SMESHDS_Hypothesis.
References GetDefaultFuseEdges(), GetDefaultQuadAllowed(), GetDefaultSurfaceCurvature(), SetFineness(), and UserDefined.
SaveTo()
ostream & NETGENPlugin_Hypothesis::SaveTo (ostream & save) virtual
Implements SMESHDS_Hypothesis.
References OfflineRenderingUtils::save(), and UserDefined.
SetFineness()
void NETGENPlugin_Hypothesis::SetFineness (Fineness theFineness)
References Coarse, Fine, Moderate, SMESH_Hypothesis::NotifySubMeshesHypothesisModification(), UserDefined, VeryCoarse, and VeryFine.
Referenced by LoadFrom().
SetFuseEdges()
void NETGENPlugin_Hypothesis::SetFuseEdges (bool theVal)
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
SetGrowthRate()
void NETGENPlugin_Hypothesis::SetGrowthRate (double theRate)
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification(), and UserDefined.
SetLocalSizeOnEntry()
void NETGENPlugin_Hypothesis::SetLocalSizeOnEntry (const std::string & entry, double localSize)
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
SetMaxSize()
void NETGENPlugin_Hypothesis::SetMaxSize (double theSize)
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
SetMinSize()
void NETGENPlugin_Hypothesis::SetMinSize (double theSize)
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
SetNbSegPerEdge()
void NETGENPlugin_Hypothesis::SetNbSegPerEdge (double theVal)
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification(), and UserDefined.
SetNbSegPerRadius()
void NETGENPlugin_Hypothesis::SetNbSegPerRadius (double theVal)
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification(), and UserDefined.
SetOptimize()
void NETGENPlugin_Hypothesis::SetOptimize (bool theVal)
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
SetParametersByDefaults()
bool NETGENPlugin_Hypothesis::SetParametersByDefaults (const TDefaults & dflts, const SMESH_Mesh * theMesh = 0) virtual
Initialize my parameter values by default parameters.
Return values
bool - true if parameter values have been successfully defined
Implements SMESH_Hypothesis.
References NETGENPlugin_Mesher::GetDefaultMinSize(), SMESH_Mesh::GetShapeToMesh(), and SMESH_Mesh::HasShapeToMesh().
SetParametersByMesh()
bool NETGENPlugin_Hypothesis::SetParametersByMesh (const SMESH_Mesh * theMesh, const TopoDS_Shape & theShape) virtual
Does nothing.
Parameters
theMesh - the built mesh
theShape - the geometry of interest
Return values
bool - always false
Implements SMESH_Hypothesis.
SetQuadAllowed()
void NETGENPlugin_Hypothesis::SetQuadAllowed (bool theVal)
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
SetSecondOrder()
void NETGENPlugin_Hypothesis::SetSecondOrder (bool theVal)
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
SetSurfaceCurvature()
void NETGENPlugin_Hypothesis::SetSurfaceCurvature (bool theVal)
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
UnsetLocalSizeOnEntry()
void NETGENPlugin_Hypothesis::UnsetLocalSizeOnEntry (const std::string & entry)
References SMESH_Hypothesis::NotifySubMeshesHypothesisModification().
Friends And Related Function Documentation
operator<<
NETGENPLUGIN_EXPORT ostream& operator<< (ostream & save, NETGENPlugin_Hypothesis & hyp) friend
operator>>
NETGENPLUGIN_EXPORT istream& operator>> (istream & load, NETGENPlugin_Hypothesis & hyp) friend
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/NETGENPlugin_Hypothesis.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/NETGENPlugin/NETGENPlugin_Hypothesis.cpp