FreeCAD: RobotGui::TaskDlgSimulate Class Reference
RobotGui::TaskDlgSimulate Class Reference
simulation dialog for the TaskView
#include <TaskDlgSimulate.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void clicked (int)
is called by the framework if an button is clicked which has no accept or rject role
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
returns for Close and Help button
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual void open ()
is called the TaskView when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgSimulate (Robot::RobotObject *pcRobotObject, Robot::TrajectoryObject *pcTrajectoryObject)
~TaskDlgSimulate ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
tells the framework which buttons are wished for the dialog
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Protected Attributes
TaskRobotControl * ctr
TaskRobotMessages * msg
TaskRobot6Axis * rob
TaskTrajectory * trac
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
simulation dialog for the TaskView
Constructor & Destructor Documentation
TaskDlgSimulate()
TaskDlgSimulate::TaskDlgSimulate (Robot::RobotObject * pcRobotObject, Robot::TrajectoryObject * pcTrajectoryObject)
References draftgeoutils.intersections::connect(), Gui::TaskView::TaskDialog::Content, ctr, msg, rob, and trac.
~TaskDlgSimulate()
TaskDlgSimulate::~TaskDlgSimulate ()
Member Function Documentation
accept()
bool TaskDlgSimulate::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
clicked()
void TaskDlgSimulate::clicked (int) virtual
is called by the framework if an button is clicked which has no accept or rject role
Reimplemented from Gui::TaskView::TaskDialog.
getStandardButtons()
virtual QDialogButtonBox::StandardButtons RobotGui::TaskDlgSimulate::getStandardButtons (void) const virtual
returns for Close and Help button
Reimplemented from Gui::TaskView::TaskDialog.
helpRequested()
void TaskDlgSimulate::helpRequested () virtual
is called by the framework if the user press the help button
Reimplemented from Gui::TaskView::TaskDialog.
open()
void TaskDlgSimulate::open () virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
References ctr, Gui::TaskView::TaskBox::hideGroupBox(), and msg.
reject()
bool TaskDlgSimulate::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
Member Data Documentation
ctr
TaskRobotControl* RobotGui::TaskDlgSimulate::ctr protected
Referenced by open(), and TaskDlgSimulate().
msg
TaskRobotMessages* RobotGui::TaskDlgSimulate::msg protected
Referenced by open(), and TaskDlgSimulate().
rob
TaskRobot6Axis* RobotGui::TaskDlgSimulate::rob protected
Referenced by TaskDlgSimulate().
trac
TaskTrajectory* RobotGui::TaskDlgSimulate::trac protected
Referenced by TaskDlgSimulate().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Robot/Gui/TaskDlgSimulate.h
FreeCAD/src/Mod/Robot/Gui/TaskDlgSimulate.cpp