FreeCAD: SMESH::Controls::ElemEntityType Class Reference
SMESH::Controls::ElemEntityType Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
ElemEntityType ()
SMDSAbs_EntityType GetElemEntityType () const
virtual SMDSAbs_ElementType GetType () const
virtual bool IsSatisfy (long theElementId)
void SetElemEntityType (SMDSAbs_EntityType theEntityType)
virtual void SetMesh (const SMDS_Mesh *theMesh)
void SetType (SMDSAbs_ElementType theType)
virtual SMDSAbs_ElementType GetType () const =0
virtual bool IsSatisfy (long theElementId)=0
Public Member Functions inherited from SMESH::Controls::Functor
virtual SMDSAbs_ElementType GetType () const =0
virtual void SetMesh (const SMDS_Mesh *theMesh)=0
virtual ~Functor ()
Constructor & Destructor Documentation
ElemEntityType()
ElemEntityType::ElemEntityType ()
Member Function Documentation
GetElemEntityType()
SMDSAbs_EntityType ElemEntityType::GetElemEntityType () const
GetType()
SMDSAbs_ElementType ElemEntityType::GetType () const virtual
Implements SMESH::Controls::Predicate.
IsSatisfy()
bool ElemEntityType::IsSatisfy (long theElementId) virtual
Implements SMESH::Controls::Predicate.
References SMDS_Mesh::FindElement(), SMDS_Mesh::FindNode(), and SMDS_MeshElement::GetEntityType().
SetElemEntityType()
void ElemEntityType::SetElemEntityType (SMDSAbs_EntityType theEntityType)
SetMesh()
void ElemEntityType::SetMesh (const SMDS_Mesh * theMesh) virtual
Implements SMESH::Controls::Functor.
SetType()
void ElemEntityType::SetType (SMDSAbs_ElementType theType)
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp