FreeCAD: FemGui::ViewProviderFEMMeshBuilder Class Reference
FemGui::ViewProviderFEMMeshBuilder Class Reference
#include <ViewProviderFemMesh.h>
Public Member Functions
virtual void buildNodes (const App::Property *, std::vector< SoNode * > &) const
void createMesh (const App::Property *, SoCoordinate3 *, SoIndexedFaceSet *, SoIndexedLineSet *, std::vector< unsigned long > &, std::vector< unsigned long > &, bool &edgeOnly, bool ShowInner, int MaxFacesShowInner) const
ViewProviderFEMMeshBuilder ()
virtual ~ViewProviderFEMMeshBuilder ()
Public Member Functions inherited from Gui::ViewProviderBuilder
virtual void buildNodes (const App::Property *, std::vector< SoNode * > &) const =0
ViewProviderBuilder (void)
Constructor.
virtual ~ViewProviderBuilder ()
Additional Inherited Members
Static Public Member Functions inherited from Gui::ViewProviderBuilder
static void add (const Base::Type &, const Base::Type &)
static ViewProvider * create (const Base::Type &)
static SoFCSelection * createSelection ()
Constructor & Destructor Documentation
ViewProviderFEMMeshBuilder()
FemGui::ViewProviderFEMMeshBuilder::ViewProviderFEMMeshBuilder ()
~ViewProviderFEMMeshBuilder()
virtual FemGui::ViewProviderFEMMeshBuilder::~ViewProviderFEMMeshBuilder () virtual
Member Function Documentation
buildNodes()
void ViewProviderFEMMeshBuilder::buildNodes (const App::Property * prop, std::vector< SoNode * > & nodes) const virtual
Implements Gui::ViewProviderBuilder.
References createMesh().
createMesh()
void ViewProviderFEMMeshBuilder::createMesh (const App::Property * prop, SoCoordinate3 * coords, SoIndexedFaceSet * faces, SoIndexedLineSet * lines, std::vector< unsigned long > & vFaceElementIdx, std::vector< unsigned long > & vNodeElementIdx, bool & edgeOnly, bool ShowInner, int MaxFacesShowInner) const
References Base::BoundBox3< _Precision >::Add(), Base::BoundBox3< _Precision >::CalcDiagonalLength(), Base::Console(), Base::TimeInfo::diffTimeF(), Base::BoundBox3< _Precision >::Enlarge(), SMDS_MeshElement::GetID(), SMDS_MeshElement::GetNode(), Base::BoundBox3< _Precision >::LengthX(), Base::BoundBox3< _Precision >::LengthY(), Base::BoundBox3< _Precision >::LengthZ(), Base::ConsoleSingleton::Log(), Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, Base::BoundBox3< _Precision >::MinZ, and SMDS_MeshElement::NbNodes().
Referenced by buildNodes(), FemGui::ViewProviderFemMesh::onChanged(), and FemGui::ViewProviderFemMesh::updateData().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/ViewProviderFemMesh.h
FreeCAD/src/Mod/Fem/Gui/ViewProviderFemMesh.cpp