FreeCAD: App::RelabelDocumentExpressionVisitor Class Reference
App::RelabelDocumentExpressionVisitor Class Reference
#include <ExpressionVisitors.h>
Public Member Functions
RelabelDocumentExpressionVisitor (const App::Document &doc)
void visit (Expression &node)
Public Member Functions inherited from App::ExpressionVisitor
virtual void aboutToChange ()
virtual int changed () const
virtual App::PropertyLinkBase * getPropertyLink ()
virtual void reset ()
virtual void visit (Expression &e)=0
virtual ~ExpressionVisitor ()
Additional Inherited Members
Protected Member Functions inherited from App::ExpressionVisitor
bool adjustLinks (Expression &e, const std::set< App::DocumentObject * > &inList)
void collectReplacement (Expression &e, std::map< ObjectIdentifier, ObjectIdentifier > &, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
void getIdentifiers (Expression &e, std::map< App::ObjectIdentifier, bool > &)
void importSubNames (Expression &e, const ObjectIdentifier::SubNameMap &subNameMap)
void moveCells (Expression &e, const CellAddress &address, int rowCount, int colCount)
void offsetCells (Expression &e, int rowOffset, int colOffset)
bool relabeledDocument (Expression &e, const std::string &oldName, const std::string &newName)
bool renameObjectIdentifier (Expression &e, const std::map< ObjectIdentifier, ObjectIdentifier > &, const ObjectIdentifier &)
bool updateElementReference (Expression &e, App::DocumentObject *feature, bool reverse)
void updateLabelReference (Expression &e, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
Constructor & Destructor Documentation
RelabelDocumentExpressionVisitor()
App::RelabelDocumentExpressionVisitor::RelabelDocumentExpressionVisitor (const App::Document & doc)
Member Function Documentation
visit()
void App::RelabelDocumentExpressionVisitor::visit (Expression & node) virtual
Implements App::ExpressionVisitor.
References App::Document::getOldLabel(), App::PropertyString::getStrValue(), App::Document::Label, and App::ExpressionVisitor::relabeledDocument().
The documentation for this class was generated from the following file:
FreeCAD/src/App/ExpressionVisitors.h