FreeCAD: Part::GeometryDoubleExtensionPy Class Reference
Part::GeometryDoubleExtensionPy Class Reference
The python export class for GeometryDoubleExtension.
#include <GeometryDoubleExtensionPy.h>
Public Types
typedef GeometryDoubleExtension * PointerType
Public Types inherited from Part::GeometryExtensionPy
typedef GeometryExtension * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
GeometryDoubleExtensionPy (GeometryDoubleExtension *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Part::GeometryExtensionPy
GeometryExtensionPy (GeometryExtension *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * copy (PyObject *args)
implementer for the copy() method
Py::String getName (void) const
getter for the Name attribute
void setName (Py::String arg)
setter for the Name attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeometryExtension * getGeometryExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::GeometryExtensionPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_getName (PyObject *self, void *closure)
getter callback for the Name attribute
static int staticCallback_setName (PyObject *self, PyObject *value, void *closure)
setter callback for the Name attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of GeometryDoubleExtensionPy.
static PyMethodDef Methods []
Methods structure of GeometryDoubleExtensionPy.
static PyTypeObject Type
Type structure of GeometryDoubleExtensionPy.
Static Public Attributes inherited from Part::GeometryExtensionPy
static PyGetSetDef GetterSetter []
Attribute structure of GeometryExtensionPy.
static PyMethodDef Methods []
Methods structure of GeometryExtensionPy.
static PyTypeObject Type
Type structure of GeometryExtensionPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~GeometryDoubleExtensionPy ()
Protected Member Functions inherited from Part::GeometryExtensionPy
~GeometryExtensionPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object attributes
Py::Float getValue (void) const
getter for the Value attribute
void setValue (Py::Float arg)
setter for the Value attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeometryDoubleExtension * getGeometryDoubleExtensionPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getValue (PyObject *self, void *closure)
getter callback for the Value attribute
static int staticCallback_setValue (PyObject *self, PyObject *value, void *closure)
setter callback for the Value attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeometryDoubleExtension.
Member Typedef Documentation
PointerType
typedef GeometryDoubleExtension* Part::GeometryDoubleExtensionPy::PointerType
Constructor & Destructor Documentation
~GeometryDoubleExtensionPy()
GeometryDoubleExtensionPy::~GeometryDoubleExtensionPy () protected
GeometryDoubleExtensionPy()
GeometryDoubleExtensionPy::GeometryDoubleExtensionPy (GeometryDoubleExtension * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getCustomAttributes()
PyObject * GeometryDoubleExtensionPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getGeometryDoubleExtensionPtr()
GeometryDoubleExtension * GeometryDoubleExtensionPy::getGeometryDoubleExtensionPtr (void) const
getter for the object handled by this class
Referenced by getValue(), PyInit(), representation(), and setValue().
GetType()
virtual PyTypeObject* Part::GeometryDoubleExtensionPy::GetType (void) virtual
Reimplemented from Part::GeometryExtensionPy.
getValue()
Py::Float GeometryDoubleExtensionPy::getValue (void) const
getter for the Value attribute
References getGeometryDoubleExtensionPtr().
Referenced by staticCallback_getValue().
PyInit()
int GeometryDoubleExtensionPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::GeometryExtensionPy.
References getGeometryDoubleExtensionPtr(), Part::GeometryExtension::setName(), and Part::GeometryDefaultExtension< T >::setValue().
PyMake()
PyObject * GeometryDoubleExtensionPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References GeometryDoubleExtensionPy().
representation()
std::string GeometryDoubleExtensionPy::representation (void) const
References getGeometryDoubleExtensionPtr(), Part::GeometryExtension::getName(), Part::GeometryExtensionPy::getName(), and Part::GeometryDefaultExtension< T >::getValue().
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int GeometryDoubleExtensionPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setValue()
void GeometryDoubleExtensionPy::setValue (Py::Float arg)
setter for the Value attribute
References getGeometryDoubleExtensionPtr(), and Part::GeometryDefaultExtension< T >::setValue().
Referenced by staticCallback_setValue().
staticCallback_getValue()
PyObject * GeometryDoubleExtensionPy::staticCallback_getValue (PyObject * self, void * closure) static
getter callback for the Value attribute
References Base::BaseExceptionFreeCADError, getValue(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setValue()
int GeometryDoubleExtensionPy::staticCallback_setValue (PyObject * self, PyObject * value, void * closure) static
setter callback for the Value attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setValue().
Member Data Documentation
GetterSetter
PyGetSetDef GeometryDoubleExtensionPy::GetterSetter static
Initial value:
= {
    {"Value",
        (getter) staticCallback_getValue,
        (setter) staticCallback_setValue,
        "\n                returns the value of the GeometryDoubleExtension.\n            ",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of GeometryDoubleExtensionPy.
Methods
PyMethodDef GeometryDoubleExtensionPy::Methods static
Initial value:
= {
    {NULL, NULL, 0, NULL}
}
Methods structure of GeometryDoubleExtensionPy.
Type
PyTypeObject GeometryDoubleExtensionPy::Type static
Type structure of GeometryDoubleExtensionPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeometryDoubleExtensionPy.h
Sources/FreeCAD/src/Mod/Part/App/GeometryDoubleExtensionPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeometryDoubleExtensionPy.cpp