FreeCAD: Part::UnifySameDomainPy Class Reference
Part::UnifySameDomainPy Class Reference
The python export class for ShapeUpgrade_UnifySameDomain.
#include <UnifySameDomainPy.h>
Public Types
typedef ShapeUpgrade_UnifySameDomain * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
UnifySameDomainPy (ShapeUpgrade_UnifySameDomain *pcObject, PyTypeObject *T=&Type)
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ShapeUpgrade_UnifySameDomain * getShapeUpgrade_UnifySameDomainPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of UnifySameDomainPy.
static PyMethodDef Methods []
Methods structure of UnifySameDomainPy.
static PyTypeObject Type
Type structure of UnifySameDomainPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~UnifySameDomainPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * initialize (PyObject *args, PyObject *kwd)
implementer for the initialize() method
PyObject * allowInternalEdges (PyObject *args)
implementer for the allowInternalEdges() method
PyObject * keepShape (PyObject *args)
implementer for the keepShape() method
PyObject * keepShapes (PyObject *args)
implementer for the keepShapes() method
PyObject * setSafeInputMode (PyObject *args)
implementer for the setSafeInputMode() method
PyObject * setLinearTolerance (PyObject *args)
implementer for the setLinearTolerance() method
PyObject * setAngularTolerance (PyObject *args)
implementer for the setAngularTolerance() method
PyObject * build (PyObject *args)
implementer for the build() method
PyObject * shape (PyObject *args)
implementer for the shape() method
static PyObject * staticCallback_initialize (PyObject *self, PyObject *args, PyObject *kwd)
callback for the initialize() method
static PyObject * staticCallback_allowInternalEdges (PyObject *self, PyObject *args)
callback for the allowInternalEdges() method
static PyObject * staticCallback_keepShape (PyObject *self, PyObject *args)
callback for the keepShape() method
static PyObject * staticCallback_keepShapes (PyObject *self, PyObject *args)
callback for the keepShapes() method
static PyObject * staticCallback_setSafeInputMode (PyObject *self, PyObject *args)
callback for the setSafeInputMode() method
static PyObject * staticCallback_setLinearTolerance (PyObject *self, PyObject *args)
callback for the setLinearTolerance() method
static PyObject * staticCallback_setAngularTolerance (PyObject *self, PyObject *args)
callback for the setAngularTolerance() method
static PyObject * staticCallback_build (PyObject *self, PyObject *args)
callback for the build() method
static PyObject * staticCallback_shape (PyObject *self, PyObject *args)
callback for the shape() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for ShapeUpgrade_UnifySameDomain.
Member Typedef Documentation
PointerType
typedef ShapeUpgrade_UnifySameDomain* Part::UnifySameDomainPy::PointerType
Constructor & Destructor Documentation
~UnifySameDomainPy()
UnifySameDomainPy::~UnifySameDomainPy () protected
UnifySameDomainPy()
UnifySameDomainPy::UnifySameDomainPy (ShapeUpgrade_UnifySameDomain * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
allowInternalEdges()
PyObject * UnifySameDomainPy::allowInternalEdges (PyObject * args)
implementer for the allowInternalEdges() method
References getShapeUpgrade_UnifySameDomainPtr().
Referenced by staticCallback_allowInternalEdges().
build()
PyObject * UnifySameDomainPy::build (PyObject * args)
implementer for the build() method
References getShapeUpgrade_UnifySameDomainPtr().
Referenced by staticCallback_build().
getCustomAttributes()
PyObject * UnifySameDomainPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getShapeUpgrade_UnifySameDomainPtr()
ShapeUpgrade_UnifySameDomain * UnifySameDomainPy::getShapeUpgrade_UnifySameDomainPtr (void) const
getter for the object handled by this class
Referenced by allowInternalEdges(), build(), initialize(), keepShape(), keepShapes(), setAngularTolerance(), setLinearTolerance(), setSafeInputMode(), and shape().
GetType()
virtual PyTypeObject* Part::UnifySameDomainPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
initialize()
PyObject * UnifySameDomainPy::initialize (PyObject * args, PyObject * kwd)
implementer for the initialize() method
References getShapeUpgrade_UnifySameDomainPtr(), shape(), and Part::TopoShapePy::Type.
Referenced by staticCallback_initialize().
keepShape()
PyObject * UnifySameDomainPy::keepShape (PyObject * args)
implementer for the keepShape() method
References getShapeUpgrade_UnifySameDomainPtr(), shape(), and Part::TopoShapePy::Type.
Referenced by staticCallback_keepShape().
keepShapes()
PyObject * UnifySameDomainPy::keepShapes (PyObject * args)
implementer for the keepShapes() method
References getShapeUpgrade_UnifySameDomainPtr().
Referenced by staticCallback_keepShapes().
PyInit()
int UnifySameDomainPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
References Base::PyObjectBase::setTwinPointer(), shape(), and Part::TopoShapePy::Type.
PyMake()
PyObject * UnifySameDomainPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References UnifySameDomainPy().
representation()
std::string UnifySameDomainPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setAngularTolerance()
PyObject * UnifySameDomainPy::setAngularTolerance (PyObject * args)
implementer for the setAngularTolerance() method
References getShapeUpgrade_UnifySameDomainPtr().
Referenced by staticCallback_setAngularTolerance().
setCustomAttributes()
int UnifySameDomainPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setLinearTolerance()
PyObject * UnifySameDomainPy::setLinearTolerance (PyObject * args)
implementer for the setLinearTolerance() method
References getShapeUpgrade_UnifySameDomainPtr().
Referenced by staticCallback_setLinearTolerance().
setSafeInputMode()
PyObject * UnifySameDomainPy::setSafeInputMode (PyObject * args)
implementer for the setSafeInputMode() method
References getShapeUpgrade_UnifySameDomainPtr().
Referenced by staticCallback_setSafeInputMode().
shape()
PyObject * UnifySameDomainPy::shape (PyObject * args)
implementer for the shape() method
References getShapeUpgrade_UnifySameDomainPtr().
Referenced by initialize(), keepShape(), PyInit(), and staticCallback_shape().
staticCallback_allowInternalEdges()
PyObject * UnifySameDomainPy::staticCallback_allowInternalEdges (PyObject * self, PyObject * args) static
callback for the allowInternalEdges() method
References allowInternalEdges(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_build()
PyObject * UnifySameDomainPy::staticCallback_build (PyObject * self, PyObject * args) static
callback for the build() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, build(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_initialize()
PyObject * UnifySameDomainPy::staticCallback_initialize (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the initialize() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, initialize(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_keepShape()
PyObject * UnifySameDomainPy::staticCallback_keepShape (PyObject * self, PyObject * args) static
callback for the keepShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), keepShape(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_keepShapes()
PyObject * UnifySameDomainPy::staticCallback_keepShapes (PyObject * self, PyObject * args) static
callback for the keepShapes() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), keepShapes(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_setAngularTolerance()
PyObject * UnifySameDomainPy::staticCallback_setAngularTolerance (PyObject * self, PyObject * args) static
callback for the setAngularTolerance() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setAngularTolerance(), and Base::PyObjectBase::startNotify().
staticCallback_setLinearTolerance()
PyObject * UnifySameDomainPy::staticCallback_setLinearTolerance (PyObject * self, PyObject * args) static
callback for the setLinearTolerance() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setLinearTolerance(), and Base::PyObjectBase::startNotify().
staticCallback_setSafeInputMode()
PyObject * UnifySameDomainPy::staticCallback_setSafeInputMode (PyObject * self, PyObject * args) static
callback for the setSafeInputMode() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setSafeInputMode(), and Base::PyObjectBase::startNotify().
staticCallback_shape()
PyObject * UnifySameDomainPy::staticCallback_shape (PyObject * self, PyObject * args) static
callback for the shape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and shape().
Member Data Documentation
GetterSetter
PyGetSetDef UnifySameDomainPy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of UnifySameDomainPy.
Methods
PyMethodDef UnifySameDomainPy::Methods static
Methods structure of UnifySameDomainPy.
Type
PyTypeObject UnifySameDomainPy::Type static
Type structure of UnifySameDomainPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/ShapeUpgrade/UnifySameDomainPy.h
Sources/FreeCAD/src/Mod/Part/App/ShapeUpgrade/UnifySameDomainPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/ShapeUpgrade/UnifySameDomainPy.cpp