FreeCAD: Gui::ApplicationIndex Class Reference
Gui::ApplicationIndex Class Reference
Public Member Functions
ApplicationIndex ()
QVariant data (int role) const
int findChild (const Gui::Document &d) const
Qt::ItemFlags flags () const
Public Member Functions inherited from Gui::DocumentModelIndex
void appendChild (DocumentModelIndex *child)
DocumentModelIndex * child (int row)
int childCount () const
virtual QVariant data (int role) const
virtual Qt::ItemFlags flags () const
DocumentModelIndex * parent () const
QList< DocumentModelIndex * > removeAll ()
void removeChild (int row)
int row () const
virtual bool setData (const QVariant &value, int role)
void setParent (DocumentModelIndex *parent)
virtual ~DocumentModelIndex ()
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Protected Member Functions inherited from Gui::DocumentModelIndex
DocumentModelIndex ()
void reset ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::DocumentModelIndex
QList< DocumentModelIndex * > childItems
DocumentModelIndex * parentItem
Constructor & Destructor Documentation
ApplicationIndex()
Gui::ApplicationIndex::ApplicationIndex ()
Member Function Documentation
data()
QVariant Gui::ApplicationIndex::data (int role) const virtual
Reimplemented from Gui::DocumentModelIndex.
Referenced by Mod.Show.mTempoVis.TempoVis::activateWorkbench(), Mod.Show.SceneDetail.SceneDetail::apply_data(), importIFClegacy.IfcSchema::capitalize(), Mod.Show.mTempoVis.TempoVis::forget(), Mod.Show.mTempoVis.TempoVis::forgetDetail(), Mod.Show.mTempoVis.TempoVis::has(), ArchSchedule.CommandArchSchedule::IsActive(), importIFClegacy.IfcSchema::readEntities(), importIFClegacy.IfcSchema::readTypes(), Mod.Show.mTempoVis.TempoVis::restore(), Mod.Show.mTempoVis.TempoVis::save(), Mod.Show.mTempoVis.TempoVis::stored_val(), FeaturePython.ViewProviderOctahedron::updateData(), and Dice3DS.dom3ds.UndefinedChunk::write().
findChild()
int Gui::ApplicationIndex::findChild (const Gui::Document & d) const
References Gui::DocumentModelIndex::child(), and Gui::DocumentModelIndex::childItems.
flags()
Qt::ItemFlags Gui::ApplicationIndex::flags () const virtual
Reimplemented from Gui::DocumentModelIndex.
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/DocumentModel.cpp