FreeCAD: TechDrawGui::Ui_SymbolChooser Class Reference
TechDrawGui::Ui_SymbolChooser Class Reference
#include <ui_SymbolChooser.h>
Public Member Functions
void retranslateUi (QDialog *TechDrawGui__SymbolChooser)
void setupUi (QDialog *TechDrawGui__SymbolChooser)
Public Attributes
QDialogButtonBox * bbButtons
Gui::FileChooser * fcSymbolDir
QGridLayout * gridLayout
QLabel * label
QListWidget * lwSymbols
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void TechDrawGui::Ui_SymbolChooser::retranslateUi (QDialog * TechDrawGui__SymbolChooser)
References fcSymbolDir, lwSymbols, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void TechDrawGui::Ui_SymbolChooser::setupUi (QDialog * TechDrawGui__SymbolChooser)
References bbButtons, draftgeoutils.intersections::connect(), Gui::FileChooser::Directory, fcSymbolDir, gridLayout, lwSymbols, retranslateUi(), Gui::FileChooser::setMode(), and verticalLayout.
Member Data Documentation
bbButtons
QDialogButtonBox* TechDrawGui::Ui_SymbolChooser::bbButtons
Referenced by setupUi().
fcSymbolDir
Gui::FileChooser* TechDrawGui::Ui_SymbolChooser::fcSymbolDir
Referenced by retranslateUi(), and setupUi().
gridLayout
QGridLayout* TechDrawGui::Ui_SymbolChooser::gridLayout
Referenced by setupUi().
label
QLabel* TechDrawGui::Ui_SymbolChooser::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
lwSymbols
QListWidget* TechDrawGui::Ui_SymbolChooser::lwSymbols
Referenced by retranslateUi(), and setupUi().
verticalLayout
QVBoxLayout* TechDrawGui::Ui_SymbolChooser::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/TechDraw/Gui/ui_SymbolChooser.h