FreeCAD: Gui::SequencerDialog Class Reference
Gui::SequencerDialog Class Reference
#include <ProgressDialog.h>
Public Member Functions
bool canAbort () const
bool isBlocking () const
Returns true if the running sequencer is blocking any user input.
void pause ()
Breaks the sequencer if needed.
void resume ()
Continues with progress.
Public Member Functions inherited from Base::SequencerBase
virtual void checkAbort ()
Check if the operation is aborted by user.
bool isLocked () const
Returns true if the sequencer was locked, false otherwise.
bool isRunning () const
Returns true if the sequencer is running, otherwise returns false.
bool setLocked (bool bLock)
If bLock is true then the sequencer gets locked.
bool wasCanceled () const
Returns true if the pending operation was canceled.
Static Public Member Functions
static SequencerDialog * instance ()
Static Public Member Functions inherited from Base::SequencerBase
static SequencerBase & Instance ()
Returns the last created sequencer instance.
Protected Member Functions
void nextStep (bool canAbort)
Increase the step indicator of the progress dialog.
void resetData ()
Resets the sequencer.
SequencerDialog ()
Construction.
void setProgress (size_t)
Sets the progress indicator to a certain position.
void setText (const char *pszTxt)
Puts text to the progress dialog.
void showRemainingTime ()
void startStep ()
Starts the progress dialog.
~SequencerDialog ()
Destruction.
Protected Member Functions inherited from Base::SequencerBase
bool next (bool canAbort=false)
Performs the next step and returns true if the operation is not yet finished.
size_t numberOfSteps () const
Returns the number of steps.
int progressInPercent () const
Returns the current state of progress in percent.
void rejectCancel ()
If you tried to cancel but then decided to continue the operation.
SequencerBase ()
construction
bool start (const char *pszStr, size_t steps)
Starts a new operation, returns false if there is already a pending operation, otherwise it returns true.
bool stop ()
Stops the sequencer if all operations are finished.
void tryToCancel ()
Try to cancel the pending operation(s).
virtual ~SequencerBase ()
Destruction.
for internal use only
class ProgressDialog
Additional Inherited Members
Protected Attributes inherited from Base::SequencerBase
size_t nProgress
Stores the current amount of progress.
size_t nTotalSteps
Stores the total number of steps.
Constructor & Destructor Documentation
SequencerDialog()
SequencerDialog::SequencerDialog () protected
Construction.
References Gui::SequencerDialogPrivate::canabort, Gui::SequencerDialogPrivate::dlg, Gui::getMainWindow(), Gui::SequencerDialogPrivate::guiThread, and ProgressDialog.
Referenced by instance().
~SequencerDialog()
SequencerDialog::~SequencerDialog () protected
Destruction.
Member Function Documentation
canAbort()
bool SequencerDialog::canAbort () const
References Gui::SequencerDialogPrivate::canabort.
Referenced by nextStep().
instance()
SequencerDialog * SequencerDialog::instance (void) static
References SequencerDialog().
isBlocking()
bool SequencerDialog::isBlocking () const virtual
Returns true if the running sequencer is blocking any user input.
This might be only of interest of the GUI where the progress bar or dialog is used from a thread. If started from a thread this method should return false, otherwise true. The default implementation always returns true.
Reimplemented from Base::SequencerBase.
References Gui::SequencerDialogPrivate::guiThread.
nextStep()
void SequencerDialog::nextStep (bool canAbort) protected virtual
Increase the step indicator of the progress dialog.
Reimplemented from Base::SequencerBase.
References Gui::SequencerDialogPrivate::canabort, canAbort(), Gui::ProgressDialog::canAbort(), Gui::SequencerDialogPrivate::dlg, Base::SequencerBase::nProgress, pause(), Base::SequencerBase::rejectCancel(), resume(), and Base::SequencerBase::wasCanceled().
pause()
void SequencerDialog::pause () virtual
Breaks the sequencer if needed.
The default implementation does nothing. Every pause() must eventually be followed by a corresponding resume().
See also
Gui::ProgressBar.
Reimplemented from Base::SequencerBase.
Referenced by nextStep().
resetData()
void SequencerDialog::resetData () protected virtual
Resets the sequencer.
Reimplemented from Base::SequencerBase.
References Gui::SequencerDialogPrivate::dlg.
resume()
void SequencerDialog::resume () virtual
Continues with progress.
The default implementation does nothing.
See also
pause(),
Gui::ProgressBar.
Reimplemented from Base::SequencerBase.
Referenced by nextStep().
setProgress()
void SequencerDialog::setProgress (size_t step) protected virtual
Sets the progress indicator to a certain position.
Reimplemented from Base::SequencerBase.
References Gui::SequencerDialogPrivate::dlg.
setText()
void SequencerDialog::setText (const char * pszTxt) protected virtual
Puts text to the progress dialog.
Reimplemented from Base::SequencerBase.
References Gui::SequencerDialogPrivate::dlg, and Gui::SequencerDialogPrivate::text.
showRemainingTime()
void SequencerDialog::showRemainingTime () protected
References Gui::SequencerDialogPrivate::dlg, Gui::SequencerDialogPrivate::measureTime, and Gui::SequencerDialogPrivate::text.
startStep()
void SequencerDialog::startStep () protected virtual
Starts the progress dialog.
Reimplemented from Base::SequencerBase.
References Gui::SequencerDialogPrivate::dlg, Gui::SequencerDialogPrivate::guiThread, Gui::SequencerDialogPrivate::measureTime, Base::SequencerBase::nTotalSteps, and Gui::SequencerDialogPrivate::progressTime.
Friends And Related Function Documentation
ProgressDialog
friend class ProgressDialog friend
Referenced by SequencerDialog().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/ProgressDialog.h
Sources/FreeCAD/src/Gui/ProgressDialog.cpp