FreeCAD: zipios::CollectionCollection Class Reference
zipios::CollectionCollection Class Reference
CollectionCollection is a FileCollection that consists of an arbitrary number of FileCollections.
#include <collcoll.h>
Public Member Functions
bool addCollection (const FileCollection &collection)
Adds a collection.
bool addCollection (FileCollection *collection)
Adds the collection pointed to by collection.
virtual FileCollection * clone () const
Create a heap allocated clone of the object this method is called for.
virtual void close ()
Closes the FileCollection.
CollectionCollection ()
Constructor.
CollectionCollection (const CollectionCollection &src)
Copy constructor.
virtual ConstEntries entries () const
Returns a vector of const pointers to the entries in the FileCollection.
virtual ConstEntryPointer getEntry (const string &name, MatchPath matchpath=MATCH) const
Returns a ConstEntryPointer to a FileEntry object for the entry with the specified name.
virtual istream * getInputStream (const ConstEntryPointer &entry)
Returns a pointer to an opened istream for the specified FileEntry.
virtual istream * getInputStream (const string &entry_name, MatchPath matchpath=MATCH)
Returns a pointer to an opened istream for the specified entry name.
const CollectionCollection & operator= (const CollectionCollection &src)
Copy assignment operator.
virtual int size () const
Returns the number in entries in all collections kept by the CollectionCollection object.
virtual ~CollectionCollection ()
Public Member Functions inherited from zipios::FileCollection
FileCollection ()
FileCollection constructor.
FileCollection (const FileCollection &src)
Copy constructor.
virtual string getName () const
Returns the name of the FileCollection.
bool isValid () const
The member function returns true if the collection is valid.
const FileCollection & operator= (const FileCollection &src)
Copy assignment operator.
virtual ~FileCollection ()
FileCollection destructor.
Static Public Member Functions
static CollectionCollection & inst ()
This static method provides a singleton instance of a CollectionCollection.
Protected Member Functions
void getEntry (const string &name, ConstEntryPointer &cep, std::vector< FileCollection * >::const_iterator &it, MatchPath matchpath=MATCH) const
A protected getEntry member function, that not only finds an entry that match the name, if such an entry exists in the collection, it also returns, which collection it was found in.
Additional Inherited Members
Public Types inherited from zipios::FileCollection
enum MatchPath { IGN, MATCH }
Detailed Description
CollectionCollection is a FileCollection that consists of an arbitrary number of FileCollections.
With a CollectionCollection the user can use multiple FileCollections transparently, making it easy for a program to keep some of its files in a zip archive and others stored in ordinary files. CollectionCollection can be used to create a simple virtual filesystem, where all collections are mounted in /. If more than one collection contain a file with the same path only the one in the first added collection will be accessible.
Constructor & Destructor Documentation
CollectionCollection() [1/2]
zipios::CollectionCollection::CollectionCollection () explicit
Constructor.
Referenced by clone(), and inst().
CollectionCollection() [2/2]
zipios::CollectionCollection::CollectionCollection (const CollectionCollection & src)
Copy constructor.
~CollectionCollection()
zipios::CollectionCollection::~CollectionCollection () virtual
Member Function Documentation
addCollection() [1/2]
bool zipios::CollectionCollection::addCollection (const FileCollection & collection)
Adds a collection.
Parameters
collection The collection to add.
Returns
true if the collection was added succesfully and the added collection is valid.
References zipios::FileCollection::clone(), and zipios::FileCollection::isValid().
addCollection() [2/2]
bool zipios::CollectionCollection::addCollection (FileCollection * collection)
Adds the collection pointed to by collection.
The CollectionCollection will call delete on the pointer when it is destructed, so the caller should make absolutely sure to only pass in a collection created with new and be sure to leave it alone after adding it. If the collection is not added false is returned and the caller remains responsible for the collection pointed to by collection.
Parameters
collection A pointer to the collection to add.
Returns
true if the collection was added succesfully and the added collection is valid.
References zipios::FileCollection::isValid().
clone()
FileCollection * zipios::CollectionCollection::clone () const virtual
Create a heap allocated clone of the object this method is called for.
The caller is responsible for deallocating the clone when he is done with it.
Returns
A heap allocated copy of the object this method is called for.
Implements zipios::FileCollection.
References CollectionCollection().
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchComponent.Component::execute(), ArchCurtainWall.CurtainWall::execute(), ArchTruss.Truss::execute(), and Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated().
close()
void zipios::CollectionCollection::close () virtual
Closes the FileCollection.
Implements zipios::FileCollection.
Referenced by femexamples.examplesgui.FemExamples::reject().
entries()
ConstEntries zipios::CollectionCollection::entries () const virtual
Returns a vector of const pointers to the entries in the FileCollection.
Returns
a ConstEntries containing the entries of the FileCollection.
Exceptions
InvalidStateException Thrown if the collection is invalid.
Reimplemented from zipios::FileCollection.
getEntry() [1/2]
void zipios::CollectionCollection::getEntry (const string & name, ConstEntryPointer & cep, std::vector< FileCollection * >::const_iterator & it, MatchPath matchpath = MATCH) const protected
A protected getEntry member function, that not only finds an entry that match the name, if such an entry exists in the collection, it also returns, which collection it was found in.
getEntry() [2/2]
ConstEntryPointer zipios::CollectionCollection::getEntry (const string & name, MatchPath matchpath = MATCH) const virtual
Returns a ConstEntryPointer to a FileEntry object for the entry with the specified name.
To ignore the path part of the filename in search of a match, specify FileCollection::IGNORE as the second argument.
Parameters
name A string containing the name of the entry to get.
matchpath Speficy MATCH, if the path should match as well, specify IGNORE, if the path should be ignored.
Returns
A ConstEntryPointer to the found entry. The returned pointer equals zero if no entry is found.
Exceptions
InvalidStateException Thrown if the collection is invalid.
Reimplemented from zipios::FileCollection.
Referenced by getInputStream().
getInputStream() [1/2]
istream * zipios::CollectionCollection::getInputStream (const ConstEntryPointer & entry) virtual
Returns a pointer to an opened istream for the specified FileEntry.
It is the callers responsibility to delete the stream when he is done with it. Returns 0, if there is no such FileEntry in the FileCollection.
Parameters
entry A ConstEntryPointer to the FileEntry to get an istream to.
Returns
an open istream for the specified entry. The istream is allocated on heap and it is the users responsibility to delete it when he is done with it.
Exceptions
InvalidStateException Thrown if the collection is invalid.
Implements zipios::FileCollection.
getInputStream() [2/2]
istream * zipios::CollectionCollection::getInputStream (const string & entry_name, MatchPath matchpath = MATCH) virtual
Returns a pointer to an opened istream for the specified entry name.
It is the callers responsibility to delete the stream when he is done with it. Returns 0, if there is no entry with the specified name in the FileCollection.
Parameters
entry_name
matchpath Speficy MATCH, if the path should match as well, specify IGNORE, if the path should be ignored.
Returns
an open istream for the specified entry. The istream is allocated on heap and it is the users responsibility to delete it when he is done with it.
Exceptions
InvalidStateException Thrown if the collection is invalid.
Implements zipios::FileCollection.
References getEntry().
inst()
CollectionCollection & zipios::CollectionCollection::inst () static
This static method provides a singleton instance of a CollectionCollection.
The instance is instantiated the first time the method is called.
Returns
A pointer to a singleton CollectionCollection instance.
References CollectionCollection().
operator=()
const CollectionCollection & zipios::CollectionCollection::operator= (const CollectionCollection & src)
Copy assignment operator.
References zipios::FileCollection::operator=().
size()
int zipios::CollectionCollection::size () const virtual
Returns the number in entries in all collections kept by the CollectionCollection object.
Reimplemented from zipios::FileCollection.
Referenced by PathScripts.PostUtils.GCodeEditorDialog::done().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/zipios++/collcoll.h
Sources/FreeCAD/src/zipios++/collcoll.cpp