FreeCAD: ClipperLib::PolyTree Class Reference
ClipperLib::PolyTree Class Reference
#include <clipper.hpp>
Public Member Functions
void Clear ()
PolyNode * GetFirst () const
int Total () const
~PolyTree ()
Public Member Functions inherited from ClipperLib::PolyNode
int ChildCount () const
PolyNode * GetNext () const
bool IsHole () const
bool IsOpen () const
PolyNode ()
virtual ~PolyNode ()
Friends
class Clipper
Additional Inherited Members
Public Attributes inherited from ClipperLib::PolyNode
PolyNodes Childs
Path Contour
PolyNode * Parent
Constructor & Destructor Documentation
~PolyTree()
ClipperLib::PolyTree::~PolyTree ()
References Clear().
Member Function Documentation
Clear()
void ClipperLib::PolyTree::Clear (void)
References ClipperLib::PolyNode::Childs.
Referenced by ClipperLib::ClipperOffset::Execute(), and ~PolyTree().
GetFirst()
PolyNode * ClipperLib::PolyTree::GetFirst () const
References ClipperLib::PolyNode::Childs.
Total()
int ClipperLib::PolyTree::Total () const
Referenced by ClipperLib::ClosedPathsFromPolyTree(), ClipperLib::OpenPathsFromPolyTree(), and ClipperLib::PolyTreeToPaths().
Friends And Related Function Documentation
Clipper
friend class Clipper friend
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Path/libarea/clipper.hpp
Sources/FreeCAD/src/Mod/Path/libarea/clipper.cpp