FreeCAD: Gui::ExpressionBinding Class Reference
Gui::ExpressionBinding Class Reference
#include <ExpressionBinding.h>
Public Member Functions
virtual bool apply ()
virtual bool apply (const std::string &propName)
bool autoApply () const
virtual void bind (const App::ObjectIdentifier &_path)
virtual void bind (const App::Property &prop)
ExpressionBinding ()
QPixmap getIcon (const char *name, const QSize &size) const
bool hasExpression () const
bool isBound () const
void setAutoApply (bool value)
void unbind ()
virtual ~ExpressionBinding ()
Protected Member Functions
void expressionChange (const App::ObjectIdentifier &id)
std::string getEscapedExpressionString () const
boost::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
const App::ObjectIdentifier & getPath () const
void objectDeleted (const App::DocumentObject &)
virtual void onChange ()
virtual void setExpression (boost::shared_ptr< App::Expression > expr)
Protected Attributes
QPalette defaultPalette
boost::signals2::scoped_connection expressionchanged
int iconHeight
QLabel * iconLabel
bool m_autoApply
boost::signals2::scoped_connection objectdeleted
Constructor & Destructor Documentation
ExpressionBinding()
ExpressionBinding::ExpressionBinding ()
~ExpressionBinding()
ExpressionBinding::~ExpressionBinding () virtual
Member Function Documentation
apply() [1/2]
bool ExpressionBinding::apply () virtual
Reimplemented in Gui::QuantitySpinBox, Gui::UIntSpinBox, Gui::QuantitySpinBox, and Gui::InputField.
References Gui::Command::getObjectCmd(), getPath(), App::Property::isReadOnly(), and App::ObjectIdentifier::toEscapedString().
Referenced by Gui::InputField::apply(), Gui::PropertyEditor::VectorLineEdit::apply(), Gui::QuantitySpinBox::apply(), Gui::UIntSpinBox::apply(), Gui::IntSpinBox::apply(), Gui::DoubleSpinBox::apply(), and Gui::ExpLineEdit::apply().
apply() [2/2]
bool ExpressionBinding::apply (const std::string & propName) virtual
Reimplemented in Gui::ExpLineEdit, Gui::DoubleSpinBox, Gui::IntSpinBox, Gui::UIntSpinBox, Gui::QuantitySpinBox, Gui::PropertyEditor::VectorLineEdit, and Gui::InputField.
References App::Application::closeActiveTransaction(), Gui::Command::Doc, App::Application::getActiveTransaction(), App::GetApplication(), App::DocumentObject::getDocument(), getEscapedExpressionString(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::PropertyString::getValue(), hasExpression(), isBound(), App::DocumentObject::Label, and App::Application::setActiveTransaction().
Referenced by Gui::ExpressionBindingPy::apply().
autoApply()
bool Gui::ExpressionBinding::autoApply () const
Referenced by Gui::ExpressionBindingPy::autoApply().
bind() [1/2]
void ExpressionBinding::bind (const App::ObjectIdentifier & _path) virtual
Reimplemented in Gui::ExpLineEdit, Gui::DoubleSpinBox, Gui::IntSpinBox, Gui::UIntSpinBox, Gui::QuantitySpinBox, Gui::PropertyEditor::PropertyItem, and Gui::InputField.
References draftgeoutils.faces::bind(), App::Property::canonicalPath(), expressionChange(), App::PropertyExpressionEngine::expressionChanged, expressionchanged, App::DocumentObject::ExpressionEngine, App::DocumentObject::getDocument(), App::ObjectIdentifier::getProperty(), objectDeleted(), and objectdeleted.
Referenced by Gui::InputField::bind(), Gui::PropertyEditor::PropertyItem::bind(), Gui::QuantitySpinBox::bind(), Gui::UIntSpinBox::bind(), Gui::IntSpinBox::bind(), Gui::DoubleSpinBox::bind(), Gui::ExpLineEdit::bind(), bind(), and Gui::ExpressionBindingPy::bind().
bind() [2/2]
void ExpressionBinding::bind (const App::Property & prop) virtual
Reimplemented in Gui::PropertyEditor::PropertyItem.
References bind().
expressionChange()
void ExpressionBinding::expressionChange (const App::ObjectIdentifier & id) protected
References onChange().
Referenced by bind().
getEscapedExpressionString()
std::string ExpressionBinding::getEscapedExpressionString () const protected
References Base::Tools::escapedUnicodeFromUtf8(), and getExpressionString().
Referenced by apply().
getExpression()
boost::shared_ptr< App::Expression > ExpressionBinding::getExpression () const protected
References App::PropertyExpressionEngine::ExpressionInfo::expression, App::DocumentObject::getExpression(), and isBound().
Referenced by Gui::QuantitySpinBox::event(), Gui::QuantitySpinBox::focusInEvent(), getExpressionString(), hasExpression(), Gui::InputField::newInput(), Gui::UIntSpinBox::onChange(), Gui::QuantitySpinBox::openFormulaDialog(), Gui::QuantitySpinBox::resizeEvent(), Gui::UIntSpinBox::resizeEvent(), Gui::IntSpinBox::resizeEvent(), Gui::DoubleSpinBox::resizeEvent(), and Gui::ExpLineEdit::resizeEvent().
getExpressionString()
std::string ExpressionBinding::getExpressionString (bool no_throw = true) const protected
References getExpression().
Referenced by getEscapedExpressionString(), Gui::PropertyEditor::PropertyVectorListItem::toString(), and Gui::PropertyEditor::PropertyVectorDistanceItem::toString().
getIcon()
QPixmap ExpressionBinding::getIcon (const char * name, const QSize & size) const
References Gui::BitmapFactory(), DraftVecUtils::find(), and Gui::BitmapFactoryInst::pixmapFromSvg().
Referenced by Gui::DoubleSpinBox::DoubleSpinBox(), Gui::ExpLineEdit::ExpLineEdit(), Gui::IntSpinBox::IntSpinBox(), Gui::UIntSpinBox::onChange(), Gui::QuantitySpinBox::QuantitySpinBox(), Gui::QuantitySpinBox::resizeEvent(), Gui::UIntSpinBox::resizeEvent(), Gui::IntSpinBox::resizeEvent(), Gui::DoubleSpinBox::resizeEvent(), Gui::ExpLineEdit::resizeEvent(), Gui::UIntSpinBox::UIntSpinBox(), ArchAxis.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), and ArchSectionPlane.SectionPlaneTaskPanel::update().
getPath()
const App::ObjectIdentifier& Gui::ExpressionBinding::getPath () const protected
Referenced by apply(), Gui::QuantitySpinBox::apply(), Gui::InputField::bind(), Gui::QuantitySpinBox::boundToName(), Gui::InputField::newInput(), and Gui::QuantitySpinBox::openFormulaDialog().
hasExpression()
bool ExpressionBinding::hasExpression () const
References getExpression(), and isBound().
Referenced by apply(), Gui::PropertyEditor::PropertyItem::hasAnyExpression(), Gui::ExpressionBindingPy::hasExpression(), Gui::ExpLineEdit::keyPressEvent(), Gui::UIntSpinBox::paintEvent(), Gui::IntSpinBox::paintEvent(), Gui::DoubleSpinBox::paintEvent(), Gui::PropertyEditor::PropertyVectorListItem::toString(), Gui::PropertyEditor::PropertyVectorDistanceItem::toString(), and Gui::PropertyEditor::PropertyPlacementItem::value().
isBound()
bool ExpressionBinding::isBound () const
Referenced by apply(), Gui::QuantitySpinBox::apply(), Gui::QuantitySpinBox::boundToName(), Gui::QuantitySpinBox::event(), Gui::QuantitySpinBox::focusInEvent(), getExpression(), hasExpression(), Gui::ExpressionBindingPy::isBound(), Gui::UIntSpinBox::keyPressEvent(), Gui::IntSpinBox::keyPressEvent(), Gui::DoubleSpinBox::keyPressEvent(), Gui::InputField::newInput(), Gui::QuantitySpinBox::openFormulaDialog(), Gui::QuantitySpinBox::resizeEvent(), Gui::UIntSpinBox::resizeEvent(), Gui::IntSpinBox::resizeEvent(), Gui::DoubleSpinBox::resizeEvent(), Gui::ExpLineEdit::resizeEvent(), Gui::UIntSpinBox::setExpression(), Gui::IntSpinBox::setExpression(), Gui::DoubleSpinBox::setExpression(), and Gui::ExpLineEdit::setExpression().
objectDeleted()
void ExpressionBinding::objectDeleted (const App::DocumentObject & obj) protected
References unbind().
Referenced by bind().
onChange()
virtual void Gui::ExpressionBinding::onChange () protected virtual
Reimplemented in Gui::UIntSpinBox, and Gui::PropertyEditor::PropertyItem.
Referenced by expressionChange().
setAutoApply()
void Gui::ExpressionBinding::setAutoApply (bool value)
Referenced by Gui::TreeWidgetEditDelegate::createEditor(), Gui::PropertyEditor::PropertyItem::createExpressionEditor(), SketcherGui::PropertyConstraintListItem::initialize(), and Gui::ExpressionBindingPy::setAutoApply().
setExpression()
void Gui::ExpressionBinding::setExpression (boost::shared_ptr< App::Expression > expr) protected virtual
Reimplemented in Gui::ExpLineEdit, Gui::DoubleSpinBox, Gui::IntSpinBox, Gui::UIntSpinBox, and Gui::QuantitySpinBox.
References App::Application::closeActiveTransaction(), App::DocumentObject::ExpressionEngine, App::Application::getActiveTransaction(), App::GetApplication(), App::PropertyString::getValue(), App::DocumentObject::Label, App::Application::setActiveTransaction(), App::PropertyExpressionEngine::setValue(), and App::PropertyExpressionEngine::validateExpression().
Referenced by Gui::InputField::newInput(), Gui::QuantitySpinBox::setExpression(), Gui::UIntSpinBox::setExpression(), Gui::IntSpinBox::setExpression(), Gui::DoubleSpinBox::setExpression(), and Gui::ExpLineEdit::setExpression().
unbind()
void ExpressionBinding::unbind ()
References expressionchanged, and objectdeleted.
Referenced by objectDeleted().
Member Data Documentation
defaultPalette
QPalette Gui::ExpressionBinding::defaultPalette protected
Referenced by Gui::DoubleSpinBox::DoubleSpinBox(), Gui::ExpLineEdit::ExpLineEdit(), Gui::IntSpinBox::IntSpinBox(), Gui::UIntSpinBox::onChange(), Gui::QuantitySpinBox::QuantitySpinBox(), Gui::QuantitySpinBox::resizeEvent(), Gui::UIntSpinBox::resizeEvent(), Gui::IntSpinBox::resizeEvent(), Gui::DoubleSpinBox::resizeEvent(), Gui::ExpLineEdit::resizeEvent(), and Gui::UIntSpinBox::UIntSpinBox().
expressionchanged
boost::signals2::scoped_connection Gui::ExpressionBinding::expressionchanged protected
Referenced by bind(), and unbind().
iconHeight
int Gui::ExpressionBinding::iconHeight protected
Referenced by Gui::DoubleSpinBox::DoubleSpinBox(), Gui::ExpLineEdit::ExpLineEdit(), Gui::IntSpinBox::IntSpinBox(), Gui::QuantitySpinBox::minimumSizeHint(), Gui::UIntSpinBox::onChange(), Gui::QuantitySpinBox::QuantitySpinBox(), Gui::QuantitySpinBox::resizeEvent(), Gui::UIntSpinBox::resizeEvent(), Gui::IntSpinBox::resizeEvent(), Gui::DoubleSpinBox::resizeEvent(), Gui::ExpLineEdit::resizeEvent(), Gui::QuantitySpinBox::sizeHint(), and Gui::UIntSpinBox::UIntSpinBox().
iconLabel
QLabel* Gui::ExpressionBinding::iconLabel protected
Referenced by Gui::QuantitySpinBox::bind(), Gui::UIntSpinBox::bind(), Gui::IntSpinBox::bind(), Gui::DoubleSpinBox::bind(), Gui::ExpLineEdit::bind(), Gui::DoubleSpinBox::DoubleSpinBox(), Gui::ExpLineEdit::ExpLineEdit(), Gui::InputField::InputField(), Gui::IntSpinBox::IntSpinBox(), Gui::InputField::newInput(), Gui::UIntSpinBox::onChange(), Gui::QuantitySpinBox::QuantitySpinBox(), Gui::InputField::resizeEvent(), Gui::QuantitySpinBox::resizeEvent(), Gui::UIntSpinBox::resizeEvent(), Gui::IntSpinBox::resizeEvent(), Gui::DoubleSpinBox::resizeEvent(), Gui::ExpLineEdit::resizeEvent(), Gui::UIntSpinBox::setExpression(), Gui::IntSpinBox::setExpression(), Gui::DoubleSpinBox::setExpression(), Gui::ExpLineEdit::setExpression(), Gui::UIntSpinBox::UIntSpinBox(), and Gui::InputField::updateIconLabel().
m_autoApply
bool Gui::ExpressionBinding::m_autoApply protected
objectdeleted
boost::signals2::scoped_connection Gui::ExpressionBinding::objectdeleted protected
Referenced by bind(), and unbind().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/ExpressionBinding.h
Sources/FreeCAD/src/Gui/ExpressionBinding.cpp