FreeCAD: Gui::DocumentWeakPtrT::Private Class Reference
Gui::DocumentWeakPtrT::Private Class Reference
Public Types
typedef boost::signals2::scoped_connection Connection
typedef boost::signals2::scoped_connection Connection
Public Member Functions
void deletedDocument (const App::Document &doc)
void deletedDocument (const Gui::Document &doc)
Private (App::Document *doc)
Private (Gui::Document *doc)
void reset ()
void reset ()
Public Attributes
Connection connectApplicationDeletedDocument
Member Typedef Documentation
Connection [1/2]
typedef boost::signals2::scoped_connection Gui::DocumentWeakPtrT::Private::Connection
Connection [2/2]
typedef boost::signals2::scoped_connection Gui::DocumentWeakPtrT::Private::Connection
Constructor & Destructor Documentation
Private() [1/2]
Gui::DocumentWeakPtrT::Private::Private (App::Document * doc)
References draftgeoutils.faces::bind(), App::GetApplication(), and App::Application::signalDeleteDocument.
Private() [2/2]
Gui::DocumentWeakPtrT::Private::Private (Gui::Document * doc)
References draftgeoutils.faces::bind(), Gui::DocumentWeakPtrT::Private::connectApplicationDeletedDocument, and Gui::DocumentWeakPtrT::Private::deletedDocument().
Member Function Documentation
deletedDocument() [1/2]
void Gui::DocumentWeakPtrT::Private::deletedDocument (const App::Document & doc)
References App::DocumentWeakPtrT::reset().
Referenced by Gui::DocumentWeakPtrT::Private::Private().
deletedDocument() [2/2]
void Gui::DocumentWeakPtrT::Private::deletedDocument (const Gui::Document & doc)
References Gui::DocumentWeakPtrT::Private::reset().
reset() [1/2]
void Gui::DocumentWeakPtrT::Private::reset ()
Referenced by Gui::DocumentWeakPtrT::Private::deletedDocument(), and draftguitools.gui_trackers.gridTracker::set().
reset() [2/2]
void Gui::DocumentWeakPtrT::Private::reset ()
References Gui::DocumentWeakPtrT::Private::connectApplicationDeletedDocument.
Referenced by draftguitools.gui_trackers.gridTracker::set().
Member Data Documentation
connectApplicationDeletedDocument
Connection Gui::DocumentWeakPtrT::Private::connectApplicationDeletedDocument
Referenced by Gui::DocumentWeakPtrT::Private::Private(), and Gui::DocumentWeakPtrT::Private::reset().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/App/DocumentObserver.cpp