FreeCAD: PathScripts.PostUtilsParse Namespace Reference
PathScripts.PostUtilsParse Namespace Reference
Functions
def create_comment (comment_string, comment_symbol)
def drill_translate (values, outstring, cmd, params)
def dump (obj)
def format_outstring (values, strTable)
def linenumber (values, space=None)
def parse (values, pathobj)
Function Documentation
create_comment()
def PathScripts.PostUtilsParse.create_comment (comment_string, comment_symbol)
Create a comment from a string using the correct comment symbol.
Referenced by PathScripts.PostUtilsParse.drill_translate(), and PathScripts.PostUtilsParse.parse().
drill_translate()
def PathScripts.PostUtilsParse.drill_translate (values, outstring, cmd, params)
Translate drill cycles.
References PathScripts.PostUtilsParse.create_comment(), PathScripts.PostUtilsParse.format_outstring(), and PathScripts.PostUtilsParse.linenumber().
Referenced by PathScripts.PostUtilsParse.parse().
dump()
def PathScripts.PostUtilsParse.dump (obj)
For debug...
format_outstring()
def PathScripts.PostUtilsParse.format_outstring (values, strTable)
Construct the line for the final output.
Referenced by PathScripts.PostUtilsParse.drill_translate(), and PathScripts.PostUtilsParse.parse().
linenumber()
def PathScripts.PostUtilsParse.linenumber (values, space = None)
Output the next line number if appropriate.
Referenced by PathScripts.PostUtilsParse.drill_translate(), and PathScripts.PostUtilsParse.parse().
parse()
def PathScripts.PostUtilsParse.parse (values, pathobj)
Parse a Path.
References PathScripts.PostUtilsParse.create_comment(), PathScripts.PostUtilsParse.drill_translate(), PathScripts.PostUtilsParse.format_outstring(), PathScripts.PostUtilsParse.linenumber(), and PathScripts.PostUtilsParse.parse().
Referenced by PathScripts.PostUtilsParse.parse().