FreeCAD: TechDrawGui::DrawGuiUtil Class Reference
TechDrawGui::DrawGuiUtil Class Reference
Convenient utility functions for TechDraw Gui Module.
#include <DrawGuiUtil.h>
Static Public Member Functions
static void dumpPointF (const char *text, const QPointF &p)
static void dumpRectF (const char *text, const QRectF &r)
static TechDraw::DrawPage * findPage (Gui::Command *cmd)
static std::pair< Base::Vector3d, Base::Vector3d > get3DDirAndRot ()
static std::pair< Base::Vector3d, Base::Vector3d > getProjDirFromFace (App::DocumentObject *obj, std::string faceName)
static bool isArchObject (App::DocumentObject *obj)
static bool isArchSection (App::DocumentObject *obj)
static bool isDraftObject (App::DocumentObject *obj)
static void loadArrowBox (QComboBox *qcb)
static bool needPage (Gui::Command *cmd)
static bool needView (Gui::Command *cmd, bool partOnly=true)
Detailed Description
Convenient utility functions for TechDraw Gui Module.
Member Function Documentation
dumpPointF()
void DrawGuiUtil::dumpPointF (const char * text, const QPointF & p) static
References Base::Console(), and Base::ConsoleSingleton::Message().
dumpRectF()
void DrawGuiUtil::dumpRectF (const char * text, const QRectF & r) static
References Base::Console(), and Base::ConsoleSingleton::Message().
findPage()
TechDraw::DrawPage * DrawGuiUtil::findPage (Gui::Command * cmd) static
References Base::Persistence::getClassTypeId(), Gui::Command::getDocument(), TechDrawGui::QGSPage::getDrawPage(), Gui::getMainWindow(), App::DocumentObject::getNameInDocument(), App::Document::getObjectsOfType(), draftutils.utils::getObjectsOfType, TechDrawGui::MDIViewPage::getQGSPage(), TechDrawGui::DlgPageChooser::getSelection(), and Gui::Command::getSelection().
get3DDirAndRot()
std::pair< Base::Vector3d, Base::Vector3d > DrawGuiUtil::get3DDirAndRot () static
References Gui::Application::activeDocument(), Base::Console(), Base::Vector3< _Precision >::Cross(), Gui::Document::getMDIViews(), Gui::Application::Instance, Base::ConsoleSingleton::Log(), and OfflineRenderingUtils::viewer().
Referenced by getProjDirFromFace().
getProjDirFromFace()
std::pair< Base::Vector3d, Base::Vector3d > DrawGuiUtil::getProjDirFromFace (App::DocumentObject * obj, std::string faceName) static
References Base::Console(), Base::Vector3< _Precision >::Cross(), get3DDirAndRot(), Part::Feature::getShape(), Base::ConsoleSingleton::Log(), draftgeoutils.general::vec(), and Base::ConsoleSingleton::Warning().
isArchObject()
bool DrawGuiUtil::isArchObject (App::DocumentObject * obj) static
References App::PropertyPythonObject::getValue().
isArchSection()
bool DrawGuiUtil::isArchSection (App::DocumentObject * obj) static
References App::PropertyPythonObject::getValue().
isDraftObject()
bool DrawGuiUtil::isDraftObject (App::DocumentObject * obj) static
References App::PropertyPythonObject::getValue().
loadArrowBox()
void DrawGuiUtil::loadArrowBox (QComboBox * qcb) static
Referenced by TechDrawGui::DlgPrefsTechDrawAnnotationImp::loadSettings(), TechDrawGui::DlgPrefsTechDrawDimensionsImp::loadSettings(), TechDrawGui::TaskLeaderLine::setUiEdit(), TechDrawGui::TaskLeaderLine::setUiPrimary(), and TechDrawGui::TaskBalloon::TaskBalloon().
needPage()
bool DrawGuiUtil::needPage (Gui::Command * cmd) static
References Base::Persistence::getClassTypeId(), Gui::Command::getDocument(), App::Document::getObjectsOfType(), and Gui::Command::hasActiveDocument().
needView()
bool DrawGuiUtil::needView (Gui::Command * cmd, bool partOnly = true) static
References Base::Persistence::getClassTypeId(), Gui::Command::getDocument(), App::Document::getObjectsOfType(), and Gui::Command::hasActiveDocument().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/DrawGuiUtil.h
FreeCAD/src/Mod/TechDraw/Gui/DrawGuiUtil.cpp