FreeCAD: SMESH_Group Class Reference
SMESH_Group Class Reference
#include <SMESH_Group.hxx>
Public Member Functions
SMESHDS_GroupBase * GetGroupDS ()
const char * GetName () const
void SetName (const char *theName)
Sets a new name.
SMESH_Group (int theID, const SMESH_Mesh *theMesh, const SMDSAbs_ElementType theType, const char *theName, const TopoDS_Shape &theShape=TopoDS_Shape(), const SMESH_PredicatePtr &thePredicate=SMESH_PredicatePtr())
SMESH_Group (SMESHDS_GroupBase *groupDS)
Constructor accesible to SMESH_Mesh only.
~SMESH_Group ()
Constructor & Destructor Documentation
SMESH_Group() [1/2]
SMESH_Group::SMESH_Group (int theID, const SMESH_Mesh * theMesh, const SMDSAbs_ElementType theType, const char * theName, const TopoDS_Shape & theShape = TopoDS_Shape(), const SMESH_PredicatePtr & thePredicate = SMESH_PredicatePtr())
References SMESHDS_GroupBase::SetStoreName().
SMESH_Group() [2/2]
SMESH_Group::SMESH_Group (SMESHDS_GroupBase * groupDS)
Constructor accesible to SMESH_Mesh only.
References SMESHDS_GroupBase::GetStoreName().
~SMESH_Group()
SMESH_Group::~SMESH_Group ()
Destructor deletes myGroupDS
Member Function Documentation
GetGroupDS()
SMESHDS_GroupBase * SMESH_Group::GetGroupDS ()
Referenced by SMESH_Mesh::AddGroup(), SMESH_Mesh::ConvertToStandalone(), SMESH_MeshEditor::CreateHoleSkin(), SMESH_Mesh::ExportMED(), SMESH_Mesh::ExportUNV(), SMESH_Mesh::HasDuplicatedGroupNamesMED(), StdMeshers_Import_1D::importMesh(), SMESH_Mesh::MEDToMesh(), SMESH_Mesh::UNVToMesh(), and Fem::FemMesh::writeABAQUS().
GetName()
const char * SMESH_Group::GetName () const
Referenced by SMESH_Mesh::ConvertToStandalone(), SMESH_Mesh::ExportMED(), SMESH_Mesh::ExportUNV(), SMESH_Mesh::HasDuplicatedGroupNamesMED(), StdMeshers_Import_1D::importMesh(), and Fem::FemMesh::writeABAQUS().
SetName()
void SMESH_Group::SetName (const char * theName)
Sets a new name.
References SMESHDS_GroupBase::SetStoreName().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_Group.hxx
FreeCAD/src/3rdParty/salomesmesh/src/SMESH/SMESH_Group.cpp