FreeCAD: PathTests.TestPathVcarve.TestPathVcarve Class Reference
PathTests.TestPathVcarve.TestPathVcarve Class Reference
Public Member Functions
def test00 (self)
def test01 (self)
def test02 (self)
def test03 (self)
def test10 (self)
def test11 (self)
def test12 (self)
def test13 (self)
Public Member Functions inherited from PathTests.PathTestUtils.PathTestBase
def assertArc (self, edge, pt1, pt2, direction='CW')
def assertCircle (self, edge, pt, r)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertCommandEqual (self, c1, c2)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertEdgeShapesMatch (self, e1, e2)
def assertEqualLocale (self, s1, s2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertPlacement (self, p1, p2)
def assertPointsMatch (self, pts0, pts1)
def assertRoughly (self, f1, f2, error=0.00001)
Detailed Description
Test Vcarve milling basics.
Member Function Documentation
test00()
def PathTests.TestPathVcarve.TestPathVcarve.test00 (self)
Verify 90 deg depth calculation
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
test01()
def PathTests.TestPathVcarve.TestPathVcarve.test01 (self)
Verify 90 deg depth limit
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
test02()
def PathTests.TestPathVcarve.TestPathVcarve.test02 (self)
Verify 60 deg depth calculation
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
test03()
def PathTests.TestPathVcarve.TestPathVcarve.test03 (self)
Verify 60 deg depth limit
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
test10()
def PathTests.TestPathVcarve.TestPathVcarve.test10 (self)
Verify 90 deg with tip dia depth calculation
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
test11()
def PathTests.TestPathVcarve.TestPathVcarve.test11 (self)
Verify 90 deg with tip dia depth limit calculation
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
test12()
def PathTests.TestPathVcarve.TestPathVcarve.test12 (self)
Verify 45 deg with tip dia depth calculation
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
test13()
def PathTests.TestPathVcarve.TestPathVcarve.test13 (self)
Verify 45 deg with tip dia depth limit calculation
References PathTests.PathTestUtils.PathTestBase.assertRoughly().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Path/PathTests/TestPathVcarve.py