FreeCAD: iisTaskGroup Class Reference
iisTaskGroup Class Reference
#include <iistaskgroup.h>
Public Member Functions
void addIconLabel (iisIconLabel *label, bool addToLayout=true)
QBoxLayout * groupLayout ()
iisTaskGroup (QWidget *parent, bool hasHeader=false)
void setScheme (iisTaskPanelScheme *scheme)
virtual ~iisTaskGroup ()
Protected Member Functions
virtual void paintEvent (QPaintEvent *event)
Protected Attributes
bool myHasHeader
iisIconLabelScheme * myLabelScheme
iisTaskPanelScheme * myScheme
Constructor & Destructor Documentation
iisTaskGroup()
iisTaskGroup::iisTaskGroup (QWidget * parent, bool hasHeader = false)
References iisTaskPanelScheme::defaultScheme(), and setScheme().
~iisTaskGroup()
iisTaskGroup::~iisTaskGroup () virtual
Member Function Documentation
addIconLabel()
void iisTaskGroup::addIconLabel (iisIconLabel * label, bool addToLayout = true)
References myLabelScheme.
Referenced by iisTaskBox::addIconLabel(), SandboxGui::TaskPanelView::TaskPanelView(), and test::test().
groupLayout()
QBoxLayout* iisTaskGroup::groupLayout ()
Referenced by iisTaskBox::groupLayout(), and SandboxGui::TaskPanelView::TaskPanelView().
paintEvent()
void iisTaskGroup::paintEvent (QPaintEvent * event) protected virtual
References iisTaskPanelScheme::groupBackground, iisTaskPanelScheme::groupBorder, myHasHeader, and myScheme.
setScheme()
void iisTaskGroup::setScheme (iisTaskPanelScheme * scheme)
References myLabelScheme, myScheme, and iisTaskPanelScheme::taskLabelScheme.
Referenced by iisTaskGroup(), iisTaskBox::setScheme(), and SandboxGui::TaskPanelView::TaskPanelView().
Member Data Documentation
myHasHeader
bool iisTaskGroup::myHasHeader protected
Referenced by paintEvent().
myLabelScheme
iisIconLabelScheme* iisTaskGroup::myLabelScheme protected
Referenced by addIconLabel(), and setScheme().
myScheme
iisTaskPanelScheme* iisTaskGroup::myScheme protected
Referenced by paintEvent(), and setScheme().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/iisTaskPanel/src/iistaskgroup.h
Sources/FreeCAD/src/Gui/iisTaskPanel/src/iistaskgroup.cpp