FreeCAD: Gui::Command Class Reference
Gui::Command Class Reference abstract
The Command class.
#include <Command.h>
Classes
class LogDisabler
Helper class to disable python console log.
Public Member Functions
Helper methods to generate help pages
const char * beginCmdHelp (void)
returns the begin of a online help page
const char * endCmdHelp (void)
returns the end of a online help page
virtual const char * getHelpUrl (void) const
Get the help URL.
Helper methods for the Active tests
bool hasActiveDocument (void) const
true when there is a document
bool hasObject (const char *Name)
true when there is a document and a Feature with Name
checking of internal state
const char * getAppModuleName (void) const
returns the name to which the command belongs
void setAppModuleName (const char *)
const char * getName () const
Get the command name.
const char * getGroupName () const
Get the name of the grouping of the command.
void setGroupName (const char *)
Public Member Functions inherited from Gui::CommandBase
Action * getAction () const
Returns the Action object of this command, or 0 if it doesn't exist.
virtual const char * getMenuText () const
virtual const char * getToolTipText () const
virtual const char * getStatusTip () const
virtual const char * getWhatsThis () const
virtual const char * getPixmap () const
virtual const char * getAccel () const
void setWhatsThis (const char *)
void setMenuText (const char *)
void setToolTipText (const char *)
void setStatusTip (const char *)
void setPixmap (const char *)
void setAccel (const char *)
virtual const char * className () const =0
The C++ class name is needed as context for the translation framework.
Protected Member Functions
Command (const char *name)
virtual ~Command ()
Methods to override when creating a new command
virtual void activated (int iMsg)=0
Methods which gets called when activated, needs to be reimplemented!
virtual Action * createAction (void)
Creates the used Action.
void applyCommandData (const char *context, Action *)
Applies the menu text, tool and status tip to the passed action object.
const char * keySequenceToAccel (int) const
Protected Member Functions inherited from Gui::CommandBase
CommandBase (const char *sMenu, const char *sToolTip=0, const char *sWhat=0, const char *sStatus=0, const char *sPixmap=0, const char *sAccel=0)
virtual ~CommandBase ()
interface used by the CommandManager and the Action
enum TriggerSource { TriggerNone, TriggerAction, TriggerChildAction }
Command trigger source.
class CommandManager
CommandManager is a friend.
virtual bool isActive (void)
Override this method if your Cmd is not always active.
void testActive (void)
Get somtile called to check the state of the command.
void setEnabled (bool)
Enables or disables the command.
TriggerSource triggerSource () const
Return the current command trigger source.
void invoke (int index, TriggerSource trigger=TriggerNone)
Called to invoke the command.
void addTo (QWidget *)
adds this command to arbitrary widgets
void addToGroup (ActionGroup *, bool checkable)
void addToGroup (ActionGroup *)
Helper methods to get important classes
Gui::Document * getActiveGuiDocument (void) const
Get pointer to the active gui document.
App::Document * getDocument (const char *Name=0) const
Get pointer to the named or active App document Returns a pointer to the named document or the active document when no name is given.
bool isViewOfType (Base::Type t) const
checks if the active view is of a special type or derived
App::DocumentObject * getObject (const char *Name) const
returns the named feature or the active one from the active document or NULL
std::string getUniqueObjectName (const char *BaseName, const App::DocumentObject *obj=0) const
Get unique Feature name from the active document.
static Application * getGuiApplication (void)
Get pointer to the Application Window.
static Gui::SelectionSingleton & getSelection (void)
Get a reference to the selection.
static std::string getObjectCmd (const char *Name, const App::Document *doc=0, const char *prefix=0, const char *postfix=0, bool gui=false)
returns a python command string to retrieve an object from a document
static std::string getObjectCmd (const App::DocumentObject *obj, const char *prefix=0, const char *postfix=0, bool gui=false)
returns a python command string to retrieve the given object
Helper methods for the Undo/Redo and Update handling
void languageChange ()
Translate command.
void updateAction (int mode)
Updates the QAction with respect to the passed mode.
void setupCheckable (int iMsg)
Setup checkable actions based on current TriggerSource.
static void openCommand (const char *sName=0)
Open a new Undo transaction on the active document.
static void commitCommand (void)
Commit the Undo transaction on the active document.
static void abortCommand (void)
Abort the Undo transaction on the active document.
static bool hasPendingCommand (void)
Check if an Undo transaction is open on the active document.
static void updateActive (void)
Updates the (active) document (propagate changes)
static void updateAll (std::list< Gui::Document * > cList)
Updates the (all or listed) documents (propagate changes)
static bool isActiveObjectValid (void)
Checks if the active object of the active document is valid.
Helper methods for issuing commands to the Python interpreter
enum DoCmd_Type { Doc, App, Gui }
types of application level actions for DoCommand()
static void blockCommand (bool)
Blocks all command objects.
static void printPyCaller ()
Print to Python console the current Python calling source file and line number.
static void printCaller (const char *file, int line)
Print to Python console the current calling source file and line number.
static void addModule (DoCmd_Type eType, const char *sModuleName)
import an external (or own) module only once
Methods for copying visiual properties
const std::string strToPython (const char *Str)
translate a string to a python string literal (needed e.g. in file names for windows...)
const std::string strToPython (const std::string &Str)
static std::string getPythonTuple (const std::string &name, const std::vector< std::string > &subnames)
Get Python tuple from object and sub-elements.
arbitrary helper methods
enum CmdType {
AlterDoc = 1, Alter3DView = 2, AlterSelection = 4, ForEdit = 8,
NoTransaction = 16
}
class LogDisabler
void adjustCameraPosition ()
Attributes
Set by the inherited constructor to set up the most important properties of the command.
In the Command constructor are set default values! The real values should be set in the constructor of the inhereting class.
const char * sAppModule
const char * sGroup
const char * sName
const char * sHelpUrl
int eType
bool bCanLog
Indicate if the command shall log to MacroManager.
Additional Inherited Members
Protected Attributes inherited from Gui::CommandBase
const char * sMenuText
const char * sToolTipText
const char * sWhatsThis
const char * sStatusTip
const char * sPixmap
const char * sAccel
std::string displayText
Detailed Description
The Command class.
This class is mostly used for commands implemented directly in C++ (see PythonCommand). It contains also a lot of helper methods to make implementing commands for FreeCAD as easy as possible.
Note
This class is intended to handle the GUI interaction like:
starting a dialog
doing view and window stuff
anything else, especially altering the document must be done on application level. See doCommand() for details.
See also
CommandManager
Author
Jrgen Riegel
Member Enumeration Documentation
CmdType
enum Gui::Command::CmdType protected
Enumerator
AlterDoc
Command change the Document.
Alter3DView
Command change the Gui.
AlterSelection
Command change the Selection.
ForEdit
Command is in a special edit mode active.
NoTransaction
Do not setup auto transaction.
DoCmd_Type
enum Gui::Command::DoCmd_Type
types of application level actions for DoCommand()
Enumerator
Doc
Action alters the document.
App
Action alters only the application.
Gui
Action alters only the Gui.
TriggerSource
enum Gui::Command::TriggerSource
Command trigger source.
Enumerator
TriggerNone
No external trigger, e.g. invoked through Python.
TriggerAction
Command triggered by an action.
TriggerChildAction
Command triggered by a child action inside an action group.
Constructor & Destructor Documentation
Command()
Command::Command (const char * name) protected
References Alter3DView, AlterDoc, AlterSelection, bCanLog, eType, sAppModule, and sGroup.
~Command()
Command::~Command () protected virtual
Member Function Documentation
abortCommand()
void Command::abortCommand (void) static
Abort the Undo transaction on the active document.
References App::Application::closeActiveTransaction(), and App::GetApplication().
Referenced by MeshGui::TaskSmoothing::accept(), ReenGui::FitBSplineSurfaceWidget::accept(), ReenGui::PoissonWidget::accept(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainCoincident::activated(), CmdSketcherConstrainPointOnObject::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), SpreadsheetGui::PropertiesDialog::apply(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainCoincident::applyConstraint(), CmdSketcherConstrainPointOnObject::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), PartDesignGui::ViewProviderBase::doubleClicked(), PartDesignGui::ViewProvider::doubleClicked(), SketcherGui::makeTangentToArcOfEllipseviaNewPoint(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), SketcherGui::makeTangentToArcOfParabolaviaNewPoint(), SketcherGui::makeTangentToEllipseviaNewPoint(), SketcherGui::TaskSketcherConstrains::on_listWidgetConstraints_itemChanged(), DrawSketchHandlerExternal::onSelectionChanged(), DrawSketchHandlerCarbonCopy::onSelectionChanged(), StdCmdExpression::pasteExpressions(), DrawSketchHandlerBSpline::pressButton(), DrawSketchHandlerBSpline::quit(), FemGui::TaskDlgCreateNodeSet::reject(), FemGui::TaskDlgMeshShapeNetgen::reject(), FemGui::TaskDlgFemConstraint::reject(), FemGui::TaskDlgFemConstraintContact::reject(), FemGui::TaskDlgFemConstraintDisplacement::reject(), FemGui::TaskDlgFemConstraintFixed::reject(), FemGui::TaskDlgFemConstraintFluidBoundary::reject(), FemGui::TaskDlgFemConstraintForce::reject(), FemGui::TaskDlgFemConstraintHeatflux::reject(), FemGui::TaskDlgFemConstraintInitialTemperature::reject(), FemGui::TaskDlgFemConstraintPlaneRotation::reject(), FemGui::TaskDlgFemConstraintPressure::reject(), FemGui::TaskDlgFemConstraintTemperature::reject(), FemGui::TaskDlgFemConstraintTransform::reject(), FemGui::TaskDlgPost::reject(), PartGui::OffsetWidget::reject(), PartGui::ThicknessWidget::reject(), PartDesignGui::TaskDlgBooleanParameters::reject(), PartDesignGui::TaskDlgFeatureParameters::reject(), PartDesignGui::TaskPrimitiveParameters::reject(), PartDesignGui::TaskDlgShapeBinder::reject(), SurfaceGui::TaskFilling::reject(), SurfaceGui::GeomFillSurface::reject(), SurfaceGui::TaskSections::reject(), TechDrawGui::TaskProjGroup::reject(), DrawSketchHandlerCoincident::releaseButton(), DrawSketchHandlerLine::releaseButton(), DrawSketchHandlerBox::releaseButton(), DrawSketchHandlerLineSet::releaseButton(), DrawSketchHandlerArc::releaseButton(), DrawSketchHandler3PointArc::releaseButton(), DrawSketchHandlerCircle::releaseButton(), DrawSketchHandlerArcOfEllipse::releaseButton(), DrawSketchHandler3PointCircle::releaseButton(), DrawSketchHandlerPoint::releaseButton(), DrawSketchHandlerFillet::releaseButton(), DrawSketchHandlerTrimming::releaseButton(), DrawSketchHandlerExtend::releaseButton(), DrawSketchHandlerSlot::releaseButton(), DrawSketchHandlerRegularPolygon::releaseButton(), DrawSketchHandlerCopy::releaseButton(), DrawSketchHandlerRectangularArray::releaseButton(), DrawSketchHandlerArcOfHyperbola::releaseButton(), DrawSketchHandlerArcOfParabola::releaseButton(), DrawSketchHandlerBSpline::releaseButton(), and SpreadsheetGui::SheetModel::setData().
activated()
virtual void Gui::Command::activated (int iMsg) protected pure virtual
Methods which gets called when activated, needs to be reimplemented!
Implemented in CmdSketcherConstraint, CmdSketcherMove, CmdSketcherClone, CmdSketcherCopy, CmdSketcherConstrainSymmetric, CmdSketcherConstrainEqual, CmdSketcherConstrainAngle, CmdSketcherConstrainDiameter, CmdSketcherConstrainRadius, CmdSketcherConstrainTangent, CmdSketcherConstrainPerpendicular, CmdSketcherConstrainParallel, CmdSketcherConstrainDistanceY, CmdSketcherConstrainDistanceX, CmdSketcherConstrainPointOnObject, CmdSketcherConstrainDistance, CmdSketcherConstrainCoincident, CmdSketcherConstrainBlock, CmdSketcherConstrainLock, CmdSketcherConstrainVertical, CmdSketcherConstrainHorizontal, CmdSandboxMeshLoader, CmdSandboxEventLoop, Gui::StdCmdDescription, Gui::StdCmdPythonHelp, Gui::StdCmdDownloadOnlineHelp, ViewZoomToFitCmd, ViewPerspectiveCmd, ViewOrthographicCmd, ViewIsometricCmd, StdCmdWindowsMenu, StdCmdStatusBar, StdCmdToolBarMenu, StdCmdDockViewMenu, StdCmdUserInterface, StdCmdWindows, StdCmdActivatePrevWindow, StdCmdActivateNextWindow, StdCmdCloseAllWindows, StdCmdCloseActiveWindow, StdCmdCascadeWindows, StdCmdTileWindows, StdCmdArrangeIcons, StdCmdSelBoundingBox, StdTreeDrag, StdCmdSelForward, StdCmdSelBack, CmdViewMeasureToggleAll, CmdViewMeasureClearAll, StdCmdDemoMode, StdCmdTextureMapping, StdCmdSceneInspector, StdCmdMeasureDistance, StdCmdTreeSelectAllInstances, StdCmdTreeExpand, StdCmdTreeCollapse, StdTreeSelection, StdBoxElementSelection, StdBoxSelection, StdViewBoxZoom, StdViewZoomOut, StdViewZoomIn, StdCmdViewIvIssueCamPos, StdCmdViewIvStereoInterleavedColumns, StdCmdViewIvStereoInterleavedRows, StdCmdViewIvStereoQuadBuff, StdCmdViewIvStereoRedGreen, StdCmdViewIvStereoOff, StdCmdViewExample3, StdCmdViewExample2, StdCmdViewExample1, StdCmdAxisCross, StdCmdToggleNavigation, StdCmdViewCreate, StdViewScreenShot, StdCmdViewVR, StdViewDockUndockFullscreen, StdViewFullscreen, StdMainFullscreen, StdViewUndock, StdViewDock, StdCmdViewFitSelection, StdCmdViewFitAll, StdCmdViewRotateRight, StdCmdViewRotateLeft, StdCmdViewTrimetric, StdCmdViewDimetric, StdCmdViewIsometric, StdCmdViewTop, StdCmdViewRight, StdCmdViewRear, StdCmdViewLeft, StdCmdViewFront, StdCmdViewBottom, StdCmdViewHome, StdCmdSetAppearance, StdCmdHideObjects, StdCmdShowObjects, StdCmdToggleObjects, StdCmdSelectVisibleObjects, StdCmdHideSelection, StdCmdShowSelection, StdCmdToggleSelectability, StdCmdToggleVisibility, StdCmdDrawStyle, StdCmdToggleClipPlane, StdCmdFreezeViews, StdCmdViewRestoreCamera, StdCmdViewSaveCamera, StdPerspectiveCamera, StdOrthographicCamera, CmdTestConsoleOutput, CmdTestMDI3, CmdTestMDI2, CmdTestMDI1, CmdTestProgress5, CmdTestProgress4, CmdTestProgress3, CmdTestProgress2, CmdTestProgress1, CmdTestCmdFuncs, FCCmdTest6, FCCmdTest5, FCCmdTest4, FCCmdTest3, FCCmdTest2, FCCmdTest1, Std_TestReloadQM, Std_TestQM, StdCmdGroup, StdCmdPart, StdCmdUnitsCalculator, StdCmdTextDocument, StdCmdMeasurementSimple, StdCmdPythonWebsite, StdCmdFreeCADFAQ, StdCmdFreeCADForum, StdCmdFreeCADPowerUserHub, StdCmdFreeCADUserHub, StdCmdFreeCADWebsite, StdCmdOnlineHelpWebsite, StdCmdOnlineHelp, StdCmdCommandLine, StdCmdDlgCustomize, StdCmdDlgPreferences, StdCmdDlgParameter, StdCmdWhatsThis, StdCmdAboutQt, StdCmdAbout, StdCmdRecentMacros, StdCmdRecentFiles, StdCmdWorkbench, StdCmdToggleBreakpoint, StdCmdMacroStepInto, StdCmdMacroStepOver, StdCmdMacroStopDebug, StdCmdMacroStartDebug, StdCmdMacroAttachDebugger, StdCmdDlgMacroExecuteDirect, StdCmdDlgMacroExecute, StdCmdMacroStopRecord, StdCmdDlgMacroRecord, StdCmdLinkSelectAllLinks, StdCmdLinkSelectLinkedFinal, StdCmdLinkSelectLinked, StdCmdLinkImportAll, StdCmdLinkImport, StdCmdLinkUnlink, StdCmdLinkReplace, StdCmdLinkMakeRelative, StdCmdLinkMake, StdCmdLinkMakeGroup, StdCmdExpression, StdCmdEdit, StdCmdAlignment, StdCmdTransformManip, StdCmdPlacement, StdCmdTransform, StdCmdRefresh, StdCmdDelete, StdCmdSelectAll, StdCmdDuplicateSelection, StdCmdPaste, StdCmdCopy, StdCmdCut, StdCmdRedo, StdCmdUndo, StdCmdQuit, StdCmdPrintPdf, StdCmdPrintPreview, StdCmdPrint, StdCmdProjectUtil, StdCmdProjectInfo, StdCmdRevert, StdCmdSaveAll, StdCmdSaveCopy, StdCmdSaveAs, StdCmdSave, StdCmdNew, StdCmdDependencyGraph, StdCmdMergeProjects, StdCmdExport, StdCmdImport, StdCmdOpen, Gui::MacroCommand, Gui::PythonGroupCommand, Gui::PythonCommand, and Gui::GroupCommand.
Referenced by invoke().
addModule()
void Command::addModule (DoCmd_Type eType, const char * sModuleName) static
import an external (or own) module only once
References Gui::MacroManager::addLine(), Gui::MacroManager::App, eType, Gui::MacroManager::Gui, Gui::Application::Instance, Base::Interpreter(), Gui::Application::macroManager(), and Base::InterpreterSingleton::runString().
Referenced by DrawingGui::TaskProjection::accept(), ReenGui::FitBSplineSurfaceWidget::accept(), ReenGui::PoissonWidget::accept(), FemGui::ViewProviderFemAnalysis::doubleClicked(), Gui::Application::sAddModule(), and SketcherGui::ViewProviderSketch::setEdit().
addTo()
void Command::addTo (QWidget * pcWidget)
adds this command to arbitrary widgets
References createAction(), and testActive().
Referenced by Gui::CommandManager::addTo(), Gui::MDITabbar::contextMenuEvent(), NaviCubeImplementation::createContextMenu(), Gui::MainWindow::createPopupMenu(), Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium(), Gui::TaskView::TaskWatcherCommands::TaskWatcherCommands(), and Gui::TaskView::TaskWatcherPython::TaskWatcherPython().
addToGroup() [1/2]
void Command::addToGroup (ActionGroup * group)
References createAction(), and testActive().
addToGroup() [2/2]
void Command::addToGroup (ActionGroup * group, bool checkable)
Referenced by StdViewDockUndockFullscreen::createAction().
adjustCameraPosition()
void Command::adjustCameraPosition ()
References Gui::Application::activeDocument(), Gui::Application::Instance, and OfflineRenderingUtils::viewer().
applyCommandData()
void Command::applyCommandData (const char * context, Action * action) protected
Applies the menu text, tool and status tip to the passed action object.
References Gui::CommandBase::getMenuText(), Gui::CommandBase::getStatusTip(), Gui::CommandBase::getToolTipText(), Gui::CommandBase::getWhatsThis(), Gui::CommandBase::sStatusTip, and draftutils.translate::translate().
Referenced by createAction(), Gui::PythonCommand::createAction(), Gui::PythonGroupCommand::createAction(), StdCmdUndo::createAction(), StdCmdRedo::createAction(), StdCmdExpression::createAction(), StdCmdLinkMakeGroup::createAction(), StdCmdFreezeViews::createAction(), StdCmdDrawStyle::createAction(), languageChange(), Gui::PythonCommand::languageChange(), and Gui::PythonGroupCommand::languageChange().
beginCmdHelp()
const char * Command::beginCmdHelp (void)
returns the begin of a online help page
blockCommand()
void Command::blockCommand (bool block) static
Blocks all command objects.
commitCommand()
void Command::commitCommand (void) static
Commit the Undo transaction on the active document.
References App::Application::closeActiveTransaction(), and App::GetApplication().
Referenced by DrawingGui::TaskProjection::accept(), FemGui::TaskDlgMeshShapeNetgen::accept(), FemGui::TaskDlgFemConstraint::accept(), FemGui::TaskDlgFemConstraintInitialTemperature::accept(), MeshGui::TaskDecimating::accept(), MeshGui::TaskSmoothing::accept(), PartGui::OffsetWidget::accept(), PartGui::ThicknessWidget::accept(), PartDesignGui::TaskDlgBooleanParameters::accept(), PartDesignGui::TaskDlgFeatureParameters::accept(), PartDesignGui::TaskDlgPipeParameters::accept(), PartDesignGui::TaskDlgShapeBinder::accept(), ReenGui::FitBSplineSurfaceWidget::accept(), ReenGui::PoissonWidget::accept(), SurfaceGui::TaskFilling::accept(), SurfaceGui::GeomFillSurface::accept(), SurfaceGui::TaskSections::accept(), TechDrawGui::TaskActiveView::accept(), TechDrawGui::TaskCosmeticLine::accept(), TechDrawGui::TaskWeldingSymbol::accept(), StdCmdDelete::activated(), CmdSketcherConstrainHorizontal::activated(), CmdSketcherConstrainVertical::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainCoincident::activated(), CmdSketcherConstrainPointOnObject::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), SpreadsheetGui::PropertiesDialog::apply(), CmdSketcherConstrainHorizontal::applyConstraint(), CmdSketcherConstrainVertical::applyConstraint(), CmdSketcherConstrainLock::applyConstraint(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainCoincident::applyConstraint(), CmdSketcherConstrainPointOnObject::applyConstraint(), CmdSketcherConstrainParallel::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), TechDrawGui::QGIViewBalloon::balloonLabelDragged(), TechDrawGui::TaskRichAnno::createAnnoFeature(), SketcherGui::DrawSketchHandler::createAutoConstraints(), TechDrawGui::TaskCenterLine::createCenterLine(), TechDrawGui::TaskDetail::createDetail(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), TechDrawGui::TaskSectionView::createSectionView(), TechDrawGui::QGIViewDimension::datumLabelDragFinished(), SpreadsheetGui::SheetTableView::deleteSelection(), SpreadsheetGui::SheetTableView::insertColumns(), SpreadsheetGui::SheetTableView::insertRows(), SketcherGui::makeTangentToArcOfEllipseviaNewPoint(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), SketcherGui::makeTangentToArcOfParabolaviaNewPoint(), SketcherGui::makeTangentToEllipseviaNewPoint(), TechDrawGui::QGVPage::mouseReleaseEvent(), SketcherGui::TaskSketcherConstrains::on_listWidgetConstraints_itemChanged(), SpreadsheetGui::SheetView::onMsg(), DrawSketchHandlerExternal::onSelectionChanged(), DrawSketchHandlerCarbonCopy::onSelectionChanged(), StdCmdExpression::pasteExpressions(), DrawSketchHandlerCoincident::releaseButton(), DrawSketchHandlerLine::releaseButton(), DrawSketchHandlerBox::releaseButton(), DrawSketchHandlerLineSet::releaseButton(), DrawSketchHandlerArc::releaseButton(), DrawSketchHandler3PointArc::releaseButton(), DrawSketchHandlerCircle::releaseButton(), DrawSketchHandlerArcOfEllipse::releaseButton(), DrawSketchHandler3PointCircle::releaseButton(), DrawSketchHandlerPoint::releaseButton(), DrawSketchHandlerFillet::releaseButton(), DrawSketchHandlerTrimming::releaseButton(), DrawSketchHandlerExtend::releaseButton(), DrawSketchHandlerSlot::releaseButton(), DrawSketchHandlerRegularPolygon::releaseButton(), DrawSketchHandlerCopy::releaseButton(), DrawSketchHandlerRectangularArray::releaseButton(), DrawSketchHandlerArcOfHyperbola::releaseButton(), DrawSketchHandlerArcOfParabola::releaseButton(), DrawSketchHandlerBSpline::releaseButton(), SpreadsheetGui::SheetTableView::removeColumns(), SpreadsheetGui::SheetTableView::removeRows(), TechDrawGui::MDIViewPage::saveDXF(), SpreadsheetGui::WorkbenchHelper::setBackgroundColor(), SpreadsheetGui::SheetModel::setData(), SpreadsheetGui::WorkbenchHelper::setForegroundColor(), SketcherGui::ConstraintView::swapNamedOfSelectedItems(), TechDrawGui::TaskRichAnno::updateAnnoFeature(), TechDrawGui::TaskCenterLine::updateCenterLine(), TechDrawGui::TaskDetail::updateDetail(), and TechDrawGui::TaskLeaderLine::updateLeaderFeature().
createAction()
Action * Command::createAction (void) protected virtual
Creates the used Action.
Reimplemented from Gui::CommandBase.
Reimplemented in Gui::StdCmdDescription, StdCmdWindowsMenu, StdCmdStatusBar, StdCmdToolBarMenu, StdCmdDockViewMenu, StdCmdSelBoundingBox, StdViewDockUndockFullscreen, StdCmdDrawStyle, StdCmdToggleClipPlane, StdCmdFreezeViews, StdPerspectiveCamera, StdOrthographicCamera, StdCmdDlgPreferences, StdCmdAbout, StdCmdRecentMacros, StdCmdRecentFiles, StdCmdWorkbench, StdCmdLinkMakeGroup, StdCmdExpression, StdCmdRedo, StdCmdUndo, Gui::MacroCommand, Gui::PythonGroupCommand, Gui::PythonCommand, Gui::GroupCommand, and Gui::StdCmdDownloadOnlineHelp.
References applyCommandData(), Gui::BitmapFactory(), Gui::CommandBase::className(), Gui::getMainWindow(), Gui::CommandBase::sAccel, Gui::Action::setIcon(), Gui::Action::setShortcut(), and Gui::CommandBase::sPixmap.
Referenced by addTo(), addToGroup(), StdCmdDlgPreferences::createAction(), StdOrthographicCamera::createAction(), StdPerspectiveCamera::createAction(), StdCmdStatusBar::createAction(), and Gui::StdCmdDescription::createAction().
endCmdHelp()
const char * Command::endCmdHelp (void)
returns the end of a online help page
getActiveGuiDocument()
Gui::Document * Command::getActiveGuiDocument (void) const
Get pointer to the active gui document.
References Gui::Application::activeDocument(), and getGuiApplication().
Referenced by SketcherCopy::activate(), StdCmdImport::activated(), StdCmdExport::activated(), StdCmdSave::activated(), StdCmdSaveAs::activated(), StdCmdSaveCopy::activated(), StdCmdProjectInfo::activated(), StdCmdRefresh::activated(), StdCmdTransformManip::activated(), StdCmdDrawStyle::activated(), StdCmdViewCreate::activated(), CmdSketcherConstrainHorizontal::activated(), CmdSketcherConstrainVertical::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainCoincident::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainPointOnObject::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), CmdSketcherConstrainHorizontal::applyConstraint(), CmdSketcherConstrainVertical::applyConstraint(), CmdSketcherConstrainLock::applyConstraint(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainCoincident::applyConstraint(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainPointOnObject::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainParallel::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), hasActiveDocument(), StdCmdImport::isActive(), StdCmdExport::isActive(), StdCmdDependencyGraph::isActive(), StdCmdSave::isActive(), StdCmdSaveAs::isActive(), StdCmdSaveCopy::isActive(), StdCmdSaveAll::isActive(), StdCmdRevert::isActive(), StdCmdProjectInfo::isActive(), StdCmdViewCreate::isActive(), CmdSketcherCopy::isActive(), CmdSketcherClone::isActive(), and CmdSketcherMove::isActive().
getAppModuleName()
const char* Gui::Command::getAppModuleName (void) const
returns the name to which the command belongs
getDocument()
App::Document * Command::getDocument (const char * Name = 0) const
Get pointer to the named or active App document Returns a pointer to the named document or the active document when no name is given.
NULL is returned when the name does not exist or no document is active!
References Gui::Application::activeDocument(), App::GetApplication(), App::Application::getDocument(), Gui::Document::getDocument(), and getGuiApplication().
Referenced by StdCmdImport::activated(), StdCmdExport::activated(), StdCmdProjectInfo::activated(), TechDrawGui::DrawGuiUtil::findPage(), getObject(), hasObject(), StdCmdRefresh::isActive(), TechDrawGui::DrawGuiUtil::needPage(), and TechDrawGui::DrawGuiUtil::needView().
getGroupName()
const char* Gui::Command::getGroupName () const
Get the name of the grouping of the command.
Referenced by Gui::Dialog::CommandModel::data().
getGuiApplication()
Application * Command::getGuiApplication (void) static
Get pointer to the Application Window.
References Gui::Application::Instance.
Referenced by StdCmdOpen::activated(), StdCmdImport::activated(), StdCmdExport::activated(), StdCmdUndo::activated(), StdCmdRedo::activated(), StdCmdCut::activated(), StdCmdCopy::activated(), StdCmdPaste::activated(), StdCmdDelete::activated(), StdCmdFreezeViews::activated(), StdCmdViewIvIssueCamPos::activated(), getActiveGuiDocument(), getDocument(), invoke(), StdCmdSave::isActive(), StdCmdSaveAs::isActive(), StdCmdPrint::isActive(), StdCmdPrintPreview::isActive(), StdCmdPrintPdf::isActive(), StdCmdUndo::isActive(), StdCmdRedo::isActive(), StdCmdCut::isActive(), StdCmdCopy::isActive(), StdCmdPaste::isActive(), StdCmdViewFitAll::isActive(), StdCmdViewFitSelection::isActive(), StdCmdViewVR::isActive(), StdCmdViewExample1::isActive(), StdCmdViewExample2::isActive(), StdCmdViewExample3::isActive(), StdCmdViewIvStereoOff::isActive(), StdCmdViewIvStereoRedGreen::isActive(), StdCmdViewIvStereoQuadBuff::isActive(), StdCmdViewIvStereoInterleavedRows::isActive(), StdCmdViewIvStereoInterleavedColumns::isActive(), StdCmdViewIvIssueCamPos::isActive(), isViewOfType(), and StdCmdDrawStyle::StdCmdDrawStyle().
getHelpUrl()
virtual const char* Gui::Command::getHelpUrl (void) const virtual
Get the help URL.
Reimplemented in Gui::PythonGroupCommand, and Gui::PythonCommand.
getName()
const char* Gui::Command::getName (void) const
Get the command name.
Referenced by StdCmdImport::activated(), StdCmdExport::activated(), StdCmdDelete::activated(), Gui::CommandManager::addCommand(), Gui::PythonCommand::createAction(), Gui::PythonGroupCommand::createAction(), Gui::Dialog::CommandModel::data(), Gui::PythonCommand::getWhatsThis(), Gui::PythonGroupCommand::getWhatsThis(), invoke(), Gui::PythonCommand::languageChange(), Gui::PythonGroupCommand::languageChange(), Gui::Dialog::DlgCustomKeyboardImp::on_editShortcut_textChanged(), Gui::CommandManager::removeCommand(), Gui::CommandPy::resetShortcut(), Gui::MacroCommand::save(), Gui::CommandPy::setShortcut(), Gui::Dialog::DlgCustomKeyboardImp::setShortcutOfCurrentAction(), and Gui::GroupCommand::setup().
getObject()
App::DocumentObject * Command::getObject (const char * Name) const
returns the named feature or the active one from the active document or NULL
References getDocument(), and App::Document::getObject().
Referenced by CmdSketcherConstrainHorizontal::activated(), CmdSketcherConstrainVertical::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainCoincident::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainPointOnObject::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), and CmdSketcherConstrainSymmetric::activated().
getObjectCmd() [1/2]
std::string Command::getObjectCmd (const App::DocumentObject * obj, const char * prefix = 0, const char * postfix = 0, bool gui = false) static
returns a python command string to retrieve the given object
References getObjectCmd(), and Draft::gui.
getObjectCmd() [2/2]
std::string Command::getObjectCmd (const char * Name, const App::Document * doc = 0, const char * prefix = 0, const char * postfix = 0, bool gui = false) static
returns a python command string to retrieve an object from a document
References App::Application::getActiveDocument(), App::GetApplication(), and Draft::gui.
Referenced by PartDesignGui::TaskDlgBooleanParameters::accept(), PartDesignGui::TaskDlgDressUpParameters::accept(), PartDesignGui::TaskDlgMultiTransformParameters::accept(), StdCmdLinkMakeRelative::activated(), Gui::ExpressionBinding::apply(), PartDesignGui::buildLinkListPythonStr(), PartDesignGui::buildLinkSingleSubPythonStr(), PartDesignGui::buildLinkSubListPythonStr(), PartDesignGui::ViewProviderBody::doubleClicked(), PartDesignGui::ViewProviderDatum::doubleClicked(), Gui::TreeWidget::dropEvent(), PartDesignGui::fixSketchSupport(), Gui::SelectionObject::getAsPropertyLinkSubString(), PartDesignGui::getBody(), getObjectCmd(), Gui::TreeWidget::mouseDoubleClickEvent(), PartDesignGui::ViewProvider::onDelete(), DrawSketchHandlerBox::releaseButton(), DrawSketchHandlerSlot::releaseButton(), DrawSketchHandlerRegularPolygon::releaseButton(), DrawSketchHandlerBSpline::releaseButton(), PartDesignGui::relinkToBody(), PartDesignGui::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), and PartDesignGui::TaskBoxPrimitives::setPrimitive().
getPythonTuple()
std::string Command::getPythonTuple (const std::string & name, const std::vector< std::string > & subnames) static
Get Python tuple from object and sub-elements.
getSelection()
Gui::SelectionSingleton & Command::getSelection (void) static
Get a reference to the selection.
References Gui::Selection().
Referenced by SketcherCopy::activate(), CmdSketcherConstrainHorizontal::activated(), CmdSketcherConstrainVertical::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainCoincident::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainPointOnObject::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), TechDrawGui::DrawGuiUtil::findPage(), and femguiutils.selection_widgets._Selector::setHelpText().
getUniqueObjectName()
std::string Command::getUniqueObjectName (const char * BaseName, const App::DocumentObject * obj = 0) const
Get unique Feature name from the active document.
Parameters
BaseName the base name
obj if not zero, then request the unique name in the document of the given object.
References App::Application::getActiveDocument(), and App::GetApplication().
hasActiveDocument()
bool Command::hasActiveDocument (void) const
true when there is a document
References getActiveGuiDocument().
Referenced by StdCmdMergeProjects::isActive(), CmdSandboxMeshLoader::isActive(), TechDrawGui::DrawGuiUtil::needPage(), and TechDrawGui::DrawGuiUtil::needView().
hasObject()
bool Command::hasObject (const char * Name)
true when there is a document and a Feature with Name
References getDocument(), and App::Document::getObject().
hasPendingCommand()
bool Command::hasPendingCommand (void) static
Check if an Undo transaction is open on the active document.
References App::Application::getActiveTransaction(), and App::GetApplication().
Referenced by SurfaceGui::FillingPanel::checkOpenCommand(), SurfaceGui::FillingEdgePanel::checkOpenCommand(), SurfaceGui::FillingVertexPanel::checkOpenCommand(), SurfaceGui::GeomFillSurface::checkOpenCommand(), SurfaceGui::SectionsPanel::checkOpenCommand(), FemGui::TaskDlgMeshShapeNetgen::open(), FemGui::TaskDlgFemConstraintContact::open(), FemGui::TaskDlgFemConstraintDisplacement::open(), FemGui::TaskDlgFemConstraintFixed::open(), FemGui::TaskDlgFemConstraintFluidBoundary::open(), FemGui::TaskDlgFemConstraintForce::open(), FemGui::TaskDlgFemConstraintHeatflux::open(), FemGui::TaskDlgFemConstraintInitialTemperature::open(), FemGui::TaskDlgFemConstraintPlaneRotation::open(), FemGui::TaskDlgFemConstraintPressure::open(), FemGui::TaskDlgFemConstraintPulley::open(), FemGui::TaskDlgFemConstraintTemperature::open(), FemGui::TaskDlgFemConstraintTransform::open(), TechDrawGui::TaskProjGroup::reject(), TechDrawGui::TaskLeaderLine::removeFeature(), and TechDrawGui::TaskRichAnno::removeFeature().
invoke()
void Command::invoke (int index, TriggerSource trigger = TriggerNone)
Called to invoke the command.
Parameters
index in case of group command, this is the index of the child command. For checkable command, this indicates the checkable state.
trigger indicate the command triggering source, see TriggerSource.
References activated(), AlterDoc, Gui::MacroManager::App, bCanLog, PendingLine::cancel(), Gui::MacroManager::Cmt, Base::Console(), Gui::CommandBase::displayText, Gui::Application::editDocument(), Base::ConsoleSingleton::Error(), eType, getGuiApplication(), Gui::getMainWindow(), Gui::CommandBase::getMenuText(), getName(), Gui::MacroManager::Gui, isActive(), Base::ConsoleSingleton::Log(), Gui::Application::macroManager(), sAppModule, App::AutoTransaction::setEnable(), Gui::MacroManager::setModule(), sName, and Gui::MainWindow::updateActions().
Referenced by Gui::PythonGroupCommand::activated(), Gui::Dialog::DemoMode::on_fullscreen_toggled(), Gui::CommandPy::run(), Gui::CommandManager::runCommandByName(), and Gui::Application::sRunCommand().
isActive()
virtual bool Gui::Command::isActive (void) virtual
Override this method if your Cmd is not always active.
Reimplemented in CmdSketcherMove, CmdSketcherClone, CmdSketcherCopy, CmdSketcherConstraint, CmdSandboxMeshLoader, CmdSandboxEventLoop, ViewZoomToFitCmd, ViewPerspectiveCmd, ViewOrthographicCmd, ViewIsometricCmd, StdCmdWindowsMenu, StdCmdStatusBar, StdCmdToolBarMenu, StdCmdDockViewMenu, StdCmdActivatePrevWindow, StdCmdActivateNextWindow, StdCmdCloseAllWindows, StdCmdCloseActiveWindow, StdCmdCascadeWindows, StdCmdTileWindows, StdCmdArrangeIcons, StdCmdSelBoundingBox, StdCmdSelForward, StdCmdSelBack, StdCmdTextureMapping, StdCmdSceneInspector, StdCmdMeasureDistance, StdCmdTreeSelectAllInstances, StdBoxElementSelection, StdBoxSelection, StdViewBoxZoom, StdViewZoomOut, StdViewZoomIn, StdCmdViewIvIssueCamPos, StdCmdViewIvStereoInterleavedColumns, StdCmdViewIvStereoInterleavedRows, StdCmdViewIvStereoQuadBuff, StdCmdViewIvStereoRedGreen, StdCmdViewIvStereoOff, StdCmdViewExample3, StdCmdViewExample2, StdCmdViewExample1, StdCmdAxisCross, StdCmdToggleNavigation, StdCmdViewCreate, StdViewScreenShot, StdCmdViewVR, StdViewDockUndockFullscreen, StdViewFullscreen, StdViewUndock, StdViewDock, StdCmdViewFitSelection, StdCmdViewFitAll, StdCmdViewRotateRight, StdCmdViewRotateLeft, StdCmdViewTrimetric, StdCmdViewDimetric, StdCmdViewIsometric, StdCmdViewTop, StdCmdViewRight, StdCmdViewRear, StdCmdViewLeft, StdCmdViewFront, StdCmdViewBottom, StdCmdViewHome, StdCmdSetAppearance, StdCmdHideObjects, StdCmdShowObjects, StdCmdToggleObjects, StdCmdSelectVisibleObjects, StdCmdHideSelection, StdCmdShowSelection, StdCmdToggleSelectability, StdCmdToggleVisibility, StdCmdDrawStyle, StdCmdToggleClipPlane, StdCmdFreezeViews, StdCmdViewRestoreCamera, StdCmdViewSaveCamera, StdPerspectiveCamera, StdOrthographicCamera, CmdTestMDI3, CmdTestMDI2, CmdTestMDI1, CmdTestProgress5, CmdTestProgress4, CmdTestProgress3, CmdTestProgress2, CmdTestProgress1, CmdTestCmdFuncs, FCCmdTest6, FCCmdTest5, FCCmdTest4, FCCmdTest3, FCCmdTest2, FCCmdTest1, StdCmdGroup, StdCmdPart, StdCmdTextDocument, StdCmdAbout, StdCmdWorkbench, StdCmdToggleBreakpoint, StdCmdMacroStepInto, StdCmdMacroStepOver, StdCmdMacroStopDebug, StdCmdMacroStartDebug, StdCmdMacroAttachDebugger, StdCmdDlgMacroExecuteDirect, StdCmdDlgMacroExecute, StdCmdMacroStopRecord, StdCmdDlgMacroRecord, StdCmdLinkSelectAllLinks, StdCmdLinkSelectLinkedFinal, StdCmdLinkSelectLinked, StdCmdLinkImportAll, StdCmdLinkImport, StdCmdLinkUnlink, StdCmdLinkReplace, StdCmdLinkMakeRelative, StdCmdLinkMake, StdCmdLinkMakeGroup, StdCmdEdit, StdCmdAlignment, StdCmdTransformManip, StdCmdPlacement, StdCmdTransform, StdCmdRefresh, StdCmdDelete, StdCmdSelectAll, StdCmdDuplicateSelection, StdCmdPaste, StdCmdCopy, StdCmdCut, StdCmdRedo, StdCmdUndo, StdCmdPrintPdf, StdCmdPrintPreview, StdCmdPrint, StdCmdProjectUtil, StdCmdProjectInfo, StdCmdRevert, StdCmdSaveAll, StdCmdSaveCopy, StdCmdSaveAs, StdCmdSave, StdCmdDependencyGraph, StdCmdMergeProjects, StdCmdExport, StdCmdImport, Gui::PythonGroupCommand, Gui::PythonCommand, and StdCmdExpression.
Referenced by Gui::Workbench::createLinkMenu(), invoke(), Gui::CommandPy::isActive(), and testActive().
isActiveObjectValid()
bool Command::isActiveObjectValid (void) static
Checks if the active object of the active document is valid.
References Gui::Application::activeDocument(), App::Document::getActiveObject(), Gui::Document::getDocument(), and Gui::Application::Instance.
isViewOfType()
bool Command::isViewOfType (Base::Type t) const
checks if the active view is of a special type or derived
References Gui::Application::activeDocument(), Gui::Document::getActiveView(), and getGuiApplication().
Referenced by StdViewScreenShot::isActive().
keySequenceToAccel()
const char * Command::keySequenceToAccel (int sk) const protected
languageChange()
void Command::languageChange () virtual
Translate command.
Implements Gui::CommandBase.
Reimplemented in Gui::StdCmdDownloadOnlineHelp, StdCmdDrawStyle, StdCmdFreezeViews, StdCmdAbout, StdCmdLinkMakeGroup, Gui::MacroCommand, Gui::PythonGroupCommand, Gui::PythonCommand, and Gui::GroupCommand.
References applyCommandData(), and Gui::CommandBase::className().
openCommand()
void Command::openCommand (const char * sCmdName = 0) static
Open a new Undo transaction on the active document.
Open a new Undo transaction on the active document This method opens a new UNDO transaction on the active document.
This transaction will later appear in the UNDO REDO dialog with the name of the command. If the user recall the transaction everything changed on the document between OpenCommand() and CommitCommand will be undone (or redone). You can use an alternative name for the operation default is the Command name.
See also
CommitCommand(),AbortCommand()
References App::GetApplication(), and App::Application::setActiveTransaction().
Referenced by DrawingGui::TaskProjection::accept(), MeshGui::TaskDecimating::accept(), MeshGui::TaskSmoothing::accept(), ReenGui::FitBSplineSurfaceWidget::accept(), ReenGui::PoissonWidget::accept(), TechDrawGui::TaskActiveView::accept(), TechDrawGui::TaskCosmeticLine::accept(), TechDrawGui::TaskWeldingSymbol::accept(), StdCmdDelete::activated(), CmdSketcherConstrainHorizontal::activated(), CmdSketcherConstrainVertical::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainCoincident::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainPointOnObject::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), SpreadsheetGui::PropertiesDialog::apply(), TechDrawGui::TaskSectionView::applyAligned(), CmdSketcherConstrainHorizontal::applyConstraint(), CmdSketcherConstrainVertical::applyConstraint(), CmdSketcherConstrainLock::applyConstraint(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainCoincident::applyConstraint(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainPointOnObject::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainParallel::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), TechDrawGui::TaskSectionView::applyQuick(), TechDrawGui::QGIViewBalloon::balloonLabelDragged(), SurfaceGui::FillingPanel::checkOpenCommand(), SurfaceGui::FillingEdgePanel::checkOpenCommand(), SurfaceGui::FillingVertexPanel::checkOpenCommand(), SurfaceGui::GeomFillSurface::checkOpenCommand(), SurfaceGui::SectionsPanel::checkOpenCommand(), TechDrawGui::TaskRichAnno::createAnnoFeature(), SketcherGui::DrawSketchHandler::createAutoConstraints(), TechDrawGui::TaskCenterLine::createCenterLine(), TechDrawGui::TaskDetail::createDetail(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), TechDrawGui::TaskSectionView::createSectionView(), TechDrawGui::QGIViewDimension::datumLabelDragFinished(), SpreadsheetGui::SheetTableView::deleteSelection(), PartGui::ViewProviderPart::doubleClicked(), PartDesignGui::ViewProviderBase::doubleClicked(), PartDesignGui::ViewProvider::doubleClicked(), PartDesignGui::ViewProviderDatum::doubleClicked(), SketcherGui::ViewProviderSketch::editDoubleClicked(), SpreadsheetGui::SheetTableView::insertColumns(), SpreadsheetGui::SheetTableView::insertRows(), TechDrawGui::QGVPage::mouseReleaseEvent(), SketcherGui::TaskSketcherConstrains::on_listWidgetConstraints_itemChanged(), SpreadsheetGui::SheetView::onMsg(), DrawSketchHandlerExternal::onSelectionChanged(), DrawSketchHandlerCarbonCopy::onSelectionChanged(), FemGui::TaskDlgMeshShapeNetgen::open(), FemGui::TaskDlgFemConstraintContact::open(), FemGui::TaskDlgFemConstraintDisplacement::open(), FemGui::TaskDlgFemConstraintFixed::open(), FemGui::TaskDlgFemConstraintFluidBoundary::open(), FemGui::TaskDlgFemConstraintForce::open(), FemGui::TaskDlgFemConstraintHeatflux::open(), FemGui::TaskDlgFemConstraintInitialTemperature::open(), FemGui::TaskDlgFemConstraintPlaneRotation::open(), FemGui::TaskDlgFemConstraintPressure::open(), FemGui::TaskDlgFemConstraintPulley::open(), FemGui::TaskDlgFemConstraintTemperature::open(), FemGui::TaskDlgFemConstraintTransform::open(), FemGui::TaskDlgPost::open(), StdCmdExpression::pasteExpressions(), DrawSketchHandlerBSpline::pressButton(), DrawSketchHandlerCoincident::releaseButton(), DrawSketchHandlerLine::releaseButton(), DrawSketchHandlerBox::releaseButton(), DrawSketchHandlerLineSet::releaseButton(), DrawSketchHandlerArc::releaseButton(), DrawSketchHandler3PointArc::releaseButton(), DrawSketchHandlerCircle::releaseButton(), DrawSketchHandlerArcOfEllipse::releaseButton(), DrawSketchHandler3PointCircle::releaseButton(), DrawSketchHandlerPoint::releaseButton(), DrawSketchHandlerFillet::releaseButton(), DrawSketchHandlerTrimming::releaseButton(), DrawSketchHandlerExtend::releaseButton(), DrawSketchHandlerSlot::releaseButton(), DrawSketchHandlerRegularPolygon::releaseButton(), DrawSketchHandlerCopy::releaseButton(), DrawSketchHandlerRectangularArray::releaseButton(), DrawSketchHandlerArcOfHyperbola::releaseButton(), DrawSketchHandlerArcOfParabola::releaseButton(), SpreadsheetGui::SheetTableView::removeColumns(), SpreadsheetGui::SheetTableView::removeRows(), TechDrawGui::MDIViewPage::saveDXF(), SpreadsheetGui::WorkbenchHelper::setBackgroundColor(), SpreadsheetGui::SheetModel::setData(), SpreadsheetGui::WorkbenchHelper::setForegroundColor(), SketcherGui::ConstraintView::swapNamedOfSelectedItems(), TechDrawGui::TaskRichAnno::updateAnnoFeature(), TechDrawGui::TaskCenterLine::updateCenterLine(), TechDrawGui::TaskDetail::updateDetail(), and TechDrawGui::TaskLeaderLine::updateLeaderFeature().
printCaller()
void Command::printCaller (const char * file, int line) static
Print to Python console the current calling source file and line number.
References Gui::MacroManager::addLine(), Gui::MacroManager::Cmt, Gui::Application::Instance, and Gui::Application::macroManager().
Referenced by printPyCaller().
printPyCaller()
void Command::printPyCaller () static
Print to Python console the current Python calling source file and line number.
References printCaller().
Referenced by Gui::Application::sDoCommand(), and Gui::Application::sDoCommandGui().
setAppModuleName()
void Command::setAppModuleName (const char * s)
References sAppModule.
Referenced by Gui::Application::sAddCommand().
setEnabled()
void Command::setEnabled (bool on)
Enables or disables the command.
Referenced by Gui::TaskCSysDragger::open(), PathScripts.PathDressupTagGui.HoldingTagMarker::setSelected(), and Gui::TaskCSysDragger::~TaskCSysDragger().
setGroupName()
void Command::setGroupName (const char * s)
References sGroup.
Referenced by Gui::Application::sAddCommand().
setupCheckable()
void Command::setupCheckable (int iMsg)
Setup checkable actions based on current TriggerSource.
References Gui::ActionGroup::actions(), TriggerAction, TriggerChildAction, TriggerNone, and triggerSource().
Referenced by Gui::PythonGroupCommand::activated().
strToPython() [1/2]
const std::string Command::strToPython (const char * Str)
translate a string to a python string literal (needed e.g. in file names for windows...)
References Base::InterpreterSingleton::strToPython().
strToPython() [2/2]
const std::string Gui::Command::strToPython (const std::string & Str)
testActive()
void Command::testActive (void)
Get somtile called to check the state of the command.
References Gui::ActionGroup::actions(), Alter3DView, AlterDoc, AlterSelection, Gui::Application::commandManager(), Gui::Control(), eType, ForEdit, Gui::CommandManager::getCommandByName(), Gui::Application::Instance, and isActive().
Referenced by addTo(), addToGroup(), and Gui::MainWindow::updateEditorActions().
triggerSource()
TriggerSource Gui::Command::triggerSource () const
Return the current command trigger source.
Referenced by Gui::GroupCommand::activated(), and setupCheckable().
updateAction()
void Command::updateAction (int mode) virtual
Updates the QAction with respect to the passed mode.
Implements Gui::CommandBase.
Reimplemented in CmdSketcherConstrainAngle, CmdSketcherConstrainDiameter, CmdSketcherConstrainRadius, CmdSketcherConstrainDistanceY, CmdSketcherConstrainDistanceX, CmdSketcherConstrainDistance, and CmdSketcherConstrainLock.
Referenced by Gui::CommandManager::updateCommands().
updateActive()
void Command::updateActive (void) static
Updates the (active) document (propagate changes)
Referenced by DrawingGui::TaskProjection::accept(), ReenGui::FitBSplineSurfaceWidget::accept(), ReenGui::PoissonWidget::accept(), SurfaceGui::TaskFilling::accept(), SurfaceGui::GeomFillSurface::accept(), SurfaceGui::TaskSections::accept(), TechDrawGui::TaskActiveView::accept(), TechDrawGui::TaskCosmeticLine::accept(), TechDrawGui::TaskWeldingSymbol::accept(), PartGui::DlgExtrusion::apply(), CmdSketcherConstrainLock::applyConstraint(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::TaskCenterLine::createCenterLine(), TechDrawGui::TaskDetail::createDetail(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), TechDrawGui::TaskSectionView::createSectionView(), SketcherGui::ViewProviderSketch::forceUpdateData(), SketcherGui::ViewProviderSketch::onDelete(), TechDrawGui::MDIViewPage::onMsg(), FemGui::TaskDlgFemConstraintContact::reject(), FemGui::TaskDlgFemConstraintDisplacement::reject(), FemGui::TaskDlgFemConstraintFixed::reject(), FemGui::TaskDlgFemConstraintFluidBoundary::reject(), FemGui::TaskDlgFemConstraintForce::reject(), FemGui::TaskDlgFemConstraintHeatflux::reject(), FemGui::TaskDlgFemConstraintInitialTemperature::reject(), FemGui::TaskDlgFemConstraintPlaneRotation::reject(), FemGui::TaskDlgFemConstraintPressure::reject(), FemGui::TaskDlgFemConstraintTemperature::reject(), FemGui::TaskDlgFemConstraintTransform::reject(), PartGui::OffsetWidget::reject(), PartGui::ThicknessWidget::reject(), SurfaceGui::TaskFilling::reject(), SurfaceGui::GeomFillSurface::reject(), SurfaceGui::TaskSections::reject(), DrawSketchHandlerExtend::releaseButton(), SketcherGui::tryAutoRecompute(), SketcherGui::ViewProviderSketch::unsetEdit(), TechDrawGui::TaskCenterLine::updateCenterLine(), TechDrawGui::TaskDetail::updateDetail(), and TechDrawGui::TaskLeaderLine::updateLeaderFeature().
updateAll()
void Command::updateAll (std::list< Gui::Document * > cList) static
Updates the (all or listed) documents (propagate changes)
References Gui::Application::Instance, and Gui::Application::onUpdate().
Friends And Related Function Documentation
CommandManager
friend class CommandManager friend
CommandManager is a friend.
LogDisabler
friend class LogDisabler friend
Member Data Documentation
bCanLog
bool Gui::Command::bCanLog protected
Indicate if the command shall log to MacroManager.
Referenced by Command(), invoke(), StdCmdLinkActions::StdCmdLinkActions(), StdCmdLinkSelectActions::StdCmdLinkSelectActions(), and StdCmdTreeViewActions::StdCmdTreeViewActions().
eType
int Gui::Command::eType protected
Referenced by StdCmdRefresh::activated(), addModule(), CmdSketcherClone::CmdSketcherClone(), CmdSketcherConstrainAngle::CmdSketcherConstrainAngle(), CmdSketcherConstrainBlock::CmdSketcherConstrainBlock(), CmdSketcherConstrainCoincident::CmdSketcherConstrainCoincident(), CmdSketcherConstrainDiameter::CmdSketcherConstrainDiameter(), CmdSketcherConstrainDistance::CmdSketcherConstrainDistance(), CmdSketcherConstrainDistanceX::CmdSketcherConstrainDistanceX(), CmdSketcherConstrainDistanceY::CmdSketcherConstrainDistanceY(), CmdSketcherConstrainEqual::CmdSketcherConstrainEqual(), CmdSketcherConstrainHorizontal::CmdSketcherConstrainHorizontal(), CmdSketcherConstrainLock::CmdSketcherConstrainLock(), CmdSketcherConstrainParallel::CmdSketcherConstrainParallel(), CmdSketcherConstrainPerpendicular::CmdSketcherConstrainPerpendicular(), CmdSketcherConstrainPointOnObject::CmdSketcherConstrainPointOnObject(), CmdSketcherConstrainRadius::CmdSketcherConstrainRadius(), CmdSketcherConstrainSymmetric::CmdSketcherConstrainSymmetric(), CmdSketcherConstrainTangent::CmdSketcherConstrainTangent(), CmdSketcherConstrainVertical::CmdSketcherConstrainVertical(), CmdSketcherCopy::CmdSketcherCopy(), CmdSketcherMove::CmdSketcherMove(), Command(), invoke(), Gui::PythonGroupCommand::PythonGroupCommand(), StdCmdDrawStyle::StdCmdDrawStyle(), StdCmdExpression::StdCmdExpression(), StdCmdFreezeViews::StdCmdFreezeViews(), StdCmdLinkActions::StdCmdLinkActions(), StdCmdLinkMakeGroup::StdCmdLinkMakeGroup(), StdCmdLinkSelectActions::StdCmdLinkSelectActions(), StdCmdTreeViewActions::StdCmdTreeViewActions(), and testActive().
sAppModule
const char* Gui::Command::sAppModule protected
Referenced by CmdSandboxEventLoop::CmdSandboxEventLoop(), CmdSandboxMeshLoader::CmdSandboxMeshLoader(), CmdSketcherClone::CmdSketcherClone(), CmdSketcherConstrainAngle::CmdSketcherConstrainAngle(), CmdSketcherConstrainBlock::CmdSketcherConstrainBlock(), CmdSketcherConstrainCoincident::CmdSketcherConstrainCoincident(), CmdSketcherConstrainDiameter::CmdSketcherConstrainDiameter(), CmdSketcherConstrainDistance::CmdSketcherConstrainDistance(), CmdSketcherConstrainDistanceX::CmdSketcherConstrainDistanceX(), CmdSketcherConstrainDistanceY::CmdSketcherConstrainDistanceY(), CmdSketcherConstrainEqual::CmdSketcherConstrainEqual(), CmdSketcherConstrainHorizontal::CmdSketcherConstrainHorizontal(), CmdSketcherConstrainLock::CmdSketcherConstrainLock(), CmdSketcherConstrainParallel::CmdSketcherConstrainParallel(), CmdSketcherConstrainPerpendicular::CmdSketcherConstrainPerpendicular(), CmdSketcherConstrainPointOnObject::CmdSketcherConstrainPointOnObject(), CmdSketcherConstrainRadius::CmdSketcherConstrainRadius(), CmdSketcherConstrainSymmetric::CmdSketcherConstrainSymmetric(), CmdSketcherConstrainTangent::CmdSketcherConstrainTangent(), CmdSketcherConstrainVertical::CmdSketcherConstrainVertical(), CmdSketcherCopy::CmdSketcherCopy(), CmdSketcherMove::CmdSketcherMove(), Command(), invoke(), and setAppModuleName().
sGroup
const char* Gui::Command::sGroup protected
Referenced by CmdSandboxEventLoop::CmdSandboxEventLoop(), CmdSandboxMeshLoader::CmdSandboxMeshLoader(), CmdSketcherClone::CmdSketcherClone(), CmdSketcherConstrainAngle::CmdSketcherConstrainAngle(), CmdSketcherConstrainBlock::CmdSketcherConstrainBlock(), CmdSketcherConstrainCoincident::CmdSketcherConstrainCoincident(), CmdSketcherConstrainDiameter::CmdSketcherConstrainDiameter(), CmdSketcherConstrainDistance::CmdSketcherConstrainDistance(), CmdSketcherConstrainDistanceX::CmdSketcherConstrainDistanceX(), CmdSketcherConstrainDistanceY::CmdSketcherConstrainDistanceY(), CmdSketcherConstrainEqual::CmdSketcherConstrainEqual(), CmdSketcherConstrainHorizontal::CmdSketcherConstrainHorizontal(), CmdSketcherConstrainLock::CmdSketcherConstrainLock(), CmdSketcherConstrainParallel::CmdSketcherConstrainParallel(), CmdSketcherConstrainPerpendicular::CmdSketcherConstrainPerpendicular(), CmdSketcherConstrainPointOnObject::CmdSketcherConstrainPointOnObject(), CmdSketcherConstrainRadius::CmdSketcherConstrainRadius(), CmdSketcherConstrainSymmetric::CmdSketcherConstrainSymmetric(), CmdSketcherConstrainTangent::CmdSketcherConstrainTangent(), CmdSketcherConstrainVertical::CmdSketcherConstrainVertical(), CmdSketcherCopy::CmdSketcherCopy(), CmdSketcherMove::CmdSketcherMove(), Command(), Gui::PythonGroupCommand::PythonGroupCommand(), setGroupName(), Gui::StdCmdDescription::StdCmdDescription(), Gui::StdCmdDownloadOnlineHelp::StdCmdDownloadOnlineHelp(), StdCmdDrawStyle::StdCmdDrawStyle(), StdCmdExpression::StdCmdExpression(), StdCmdFreezeViews::StdCmdFreezeViews(), StdCmdLinkActions::StdCmdLinkActions(), StdCmdLinkMakeGroup::StdCmdLinkMakeGroup(), StdCmdLinkSelectActions::StdCmdLinkSelectActions(), Gui::StdCmdPythonHelp::StdCmdPythonHelp(), and StdCmdTreeViewActions::StdCmdTreeViewActions().
sHelpUrl
const char* Gui::Command::sHelpUrl protected
sName
const char* Gui::Command::sName protected
Referenced by Gui::PythonCommand::activated(), Gui::PythonGroupCommand::activated(), Gui::CommandManager::addCommandMode(), Gui::PythonGroupCommand::createAction(), Gui::CommandManager::getCommandByName(), Gui::PythonCommand::getResource(), Gui::PythonGroupCommand::getResource(), invoke(), Gui::CommandManager::runCommandByName(), Gui::MacroCommand::~MacroCommand(), Gui::PythonCommand::~PythonCommand(), and Gui::PythonGroupCommand::~PythonGroupCommand().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Command.h
Sources/FreeCAD/src/Gui/Command.cpp