FreeCAD: App::FeatureCustomT< FeatureT > Class Template Reference
App::FeatureCustomT< FeatureT > Class Template Reference
FeatureCustomT is a template class to be used with DocumentObject or any of its subclasses as template parameter.
#include <FeatureCustom.h>
Public Member Functions
FeatureCustomT ()
virtual ~FeatureCustomT ()
methods override DocumentObject
short mustExecute () const
virtual DocumentObjectExecReturn * execute (void)
recalculate the Feature
virtual const char * getViewProviderName (void) const
returns the type name of the ViewProvider
PyObject * getPyObject (void)
void setPyObject (PyObject *obj)
virtual void onBeforeChange (const Property *prop)
virtual void onChanged (const Property *prop)
virtual void onDocumentRestored ()
virtual void onSettingDocument ()
FeatureCustomT (const FeatureCustomT &)=delete
FeatureCustomT (FeatureCustomT &&)=delete
FeatureCustomT & operator= (const FeatureCustomT &)=delete
FeatureCustomT & operator= (FeatureCustomT &&)=delete
Detailed Description
template<class FeatureT>
class App::FeatureCustomT< FeatureT >
FeatureCustomT is a template class to be used with DocumentObject or any of its subclasses as template parameter.
FeatureCustomT offers a way to add or remove a property at runtime. This class is similar to FeaturePythonT with the difference that it has no support for in Python written feature classes.
Author
Werner Mayer
Constructor & Destructor Documentation
FeatureCustomT() [1/3]
template<class FeatureT > App::FeatureCustomT< FeatureT >::FeatureCustomT ()
~FeatureCustomT()
template<class FeatureT > virtual App::FeatureCustomT< FeatureT >::~FeatureCustomT () virtual
FeatureCustomT() [2/3]
template<class FeatureT > App::FeatureCustomT< FeatureT >::FeatureCustomT (const FeatureCustomT< FeatureT > &) protected delete
FeatureCustomT() [3/3]
template<class FeatureT > App::FeatureCustomT< FeatureT >::FeatureCustomT (FeatureCustomT< FeatureT > &&) protected delete
Member Function Documentation
execute()
template<class FeatureT > virtual DocumentObjectExecReturn * App::FeatureCustomT< FeatureT >::execute (void) virtual
recalculate the Feature
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), PathScripts.PathDressupDogbone.ObjectDressup::boneStateList(), ArchSite.Compass::buildCoordinates(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::generateTags(), ArchPanel.PanelCut::getWires(), ArchSchedule.CommandArchSchedule::IsActive(), Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), FeaturePython.DistanceBolt::onChanged(), PathScripts.PathStock.StockFromBase::onChanged(), PathScripts.PathStock.StockCreateBox::onChanged(), PathScripts.PathStock.StockCreateCylinder::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), draftobjects.patharray.PathArray::onDocumentRestored(), and draftobjects.pathtwistedarray.PathTwistedArray::onDocumentRestored().
getPyObject()
template<class FeatureT > PyObject * App::FeatureCustomT< FeatureT >::getPyObject (void)
getViewProviderName()
template<class FeatureT > virtual const char * App::FeatureCustomT< FeatureT >::getViewProviderName (void) const virtual
returns the type name of the ViewProvider
mustExecute()
template<class FeatureT > short App::FeatureCustomT< FeatureT >::mustExecute (void) const
onBeforeChange()
template<class FeatureT > virtual void App::FeatureCustomT< FeatureT >::onBeforeChange (const Property * prop) protected virtual
Referenced by PathScripts.PathGui.QuantitySpinBox::updateProperty().
onChanged()
template<class FeatureT > virtual void App::FeatureCustomT< FeatureT >::onChanged (const Property * prop) protected virtual
Referenced by ArchStructure.CommandStructuralSystem::Activated(), draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSite.Compass::buildCoordinates(), draftobjects.wire.Wire::execute(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchPanel.ViewProviderPanelSheet::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), and draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData().
onDocumentRestored()
template<class FeatureT > virtual void App::FeatureCustomT< FeatureT >::onDocumentRestored () protected virtual
onSettingDocument()
template<class FeatureT > virtual void App::FeatureCustomT< FeatureT >::onSettingDocument (void) protected virtual
operator=() [1/2]
template<class FeatureT > FeatureCustomT & App::FeatureCustomT< FeatureT >::operator= (const FeatureCustomT< FeatureT > &) protected delete
operator=() [2/2]
template<class FeatureT > FeatureCustomT & App::FeatureCustomT< FeatureT >::operator= (FeatureCustomT< FeatureT > &&) protected delete
setPyObject()
template<class FeatureT > void App::FeatureCustomT< FeatureT >::setPyObject (PyObject * obj)
The documentation for this class was generated from the following file:
FreeCAD/src/App/FeatureCustom.h