FreeCAD: PartDesignGui::Ui_TaskBooleanParameters Class Reference
PartDesignGui::Ui_TaskBooleanParameters Class Reference
#include <ui_TaskBooleanParameters.h>
Public Member Functions
void retranslateUi (QWidget *PartDesignGui__TaskBooleanParameters)
void setupUi (QWidget *PartDesignGui__TaskBooleanParameters)
Public Attributes
QToolButton * buttonBodyAdd
QToolButton * buttonBodyRemove
QComboBox * comboType
QHBoxLayout * horizontalLayout
QListWidget * listWidgetBodies
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void PartDesignGui::Ui_TaskBooleanParameters::retranslateUi (QWidget * PartDesignGui__TaskBooleanParameters)
References buttonBodyAdd, buttonBodyRemove, comboType, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void PartDesignGui::Ui_TaskBooleanParameters::setupUi (QWidget * PartDesignGui__TaskBooleanParameters)
References buttonBodyAdd, buttonBodyRemove, comboType, horizontalLayout, listWidgetBodies, retranslateUi(), and verticalLayout.
Member Data Documentation
buttonBodyAdd
QToolButton* PartDesignGui::Ui_TaskBooleanParameters::buttonBodyAdd
Referenced by retranslateUi(), and setupUi().
buttonBodyRemove
QToolButton* PartDesignGui::Ui_TaskBooleanParameters::buttonBodyRemove
Referenced by retranslateUi(), and setupUi().
comboType
QComboBox* PartDesignGui::Ui_TaskBooleanParameters::comboType
Referenced by retranslateUi(), setupUi(), and Mod.PartDesign.FeatureHole.TaskHole.TaskHole::setupUi().
horizontalLayout
QHBoxLayout* PartDesignGui::Ui_TaskBooleanParameters::horizontalLayout
Referenced by setupUi().
listWidgetBodies
QListWidget* PartDesignGui::Ui_TaskBooleanParameters::listWidgetBodies
Referenced by setupUi().
verticalLayout
QVBoxLayout* PartDesignGui::Ui_TaskBooleanParameters::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/PartDesign/Gui/ui_TaskBooleanParameters.h