FreeCAD: importXLSX Namespace Reference
importXLSX Namespace Reference
Classes
class exprNode
class FormulaTranslator
Functions
def getText (nodelist)
def handleCells (cellList, actCellSheet, sList)
def handleStrings (theStr, sList)
def handleWorkBook (theBook, sheetDict, Doc)
def handleWorkSheet (theDom, actSheet, strList)
def insert (nameXLSX, docname)
def open (nameXLSX)
Variables
dictionary branchHigher = {'=':None}
dictionary branchLower
gui
pythonopen = open
dictionary sepToken
dictionary tokenDic
dictionary treeDict
Function Documentation
getText()
def importXLSX.getText (nodelist)
Referenced by handleCells(), handleStrings(), and handleWorkBook().
handleCells()
def importXLSX.handleCells (cellList, actCellSheet, sList)
References getText().
Referenced by handleWorkSheet().
handleStrings()
def importXLSX.handleStrings (theStr, sList)
References getText().
Referenced by insert(), and open().
handleWorkBook()
def importXLSX.handleWorkBook (theBook, sheetDict, Doc)
References getText().
Referenced by insert(), and open().
handleWorkSheet()
def importXLSX.handleWorkSheet (theDom, actSheet, strList)
References handleCells().
Referenced by insert(), and open().
insert()
def importXLSX.insert (nameXLSX, docname)
References handleStrings(), handleWorkBook(), and handleWorkSheet().
open()
def importXLSX.open (nameXLSX)
References handleStrings(), handleWorkBook(), and handleWorkSheet().
Variable Documentation
branchHigher
dictionary importXLSX.branchHigher = {'=':None}
branchLower
dictionary importXLSX.branchLower
Initial value:
 = {
   '>':None,
   '=':None
   }
gui
importXLSX.gui
pythonopen
importXLSX.pythonopen = open
sepToken
dictionary importXLSX.sepToken
Initial value:
 =  {
   '(':None,
   '=':None,
   '<':'branchLower',
   '>':'branchHigher',
   ')':None,
 #  '"':None,
 #  ';':None,
   ' ':None,
   ',':None, # Separator on lists
   '!':None, #Connector to cells on other Sheets
   '+':None,
   '-':None,
   '*':None,
   '/':None,
   '^':None
   }
tokenDic
dictionary importXLSX.tokenDic
treeDict
dictionary importXLSX.treeDict
Initial value:
 =  {
   'branchLower':branchLower,
   'branchHigher':branchHigher
   }