FreeCAD: Sketcher::GeometryTypedFacade< GeometryT > Class Template Reference
Sketcher::GeometryTypedFacade< GeometryT > Class Template Reference
#include <GeometryFacade.h>
Public Member Functions
GeometryT * getTypedGeometry ()
GeometryT * getTypedGeometry () const
Public Member Functions inherited from Sketcher::GeometryFacade
Part::Geometry * clone (void) const
Part::Geometry * copy (void) const
void deleteExtension (Base::Type type)
void deleteExtension (std::string name)
bool getBlocked () const
bool getConstruction (void) const
std::weak_ptr< const Part::GeometryExtension > getExtension (Base::Type type) const
std::weak_ptr< const Part::GeometryExtension > getExtension (std::string name) const
const std::string & getExtensionName () const
std::vector< std::weak_ptr< const Part::GeometryExtension > > getExtensions () const
template<typename GeometryT = Part::Geometry, typename = typename std::enable_if< std::is_base_of<Part::Geometry, typename std::decay<GeometryT>::type>::value >::type>
GeometryT * getGeometry ()
template<typename GeometryT = Part::Geometry, typename = typename std::enable_if< std::is_base_of<Part::Geometry, typename std::decay<GeometryT>::type>::value >::type>
GeometryT * getGeometry () const
virtual long getId () const override
virtual InternalType::InternalType getInternalType () const override
virtual PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
boost::uuids::uuid getTag () const
const Handle (Geom_Geometry) &handle() const
bool hasExtension (Base::Type type) const
bool hasExtension (std::string name) const
bool isGeoType (const Base::Type &type) const
bool isInternalAligned () const
void mirror (Base::Vector3d point)
void mirror (Base::Vector3d point, Base::Vector3d dir)
void rotate (Base::Placement plm)
void scale (Base::Vector3d vec, double scale)
void setBlocked (bool status=true)
void setConstruction (bool construction)
void setExtension (std::unique_ptr< Part::GeometryExtension > &&geo)
void setGeometry (Part::Geometry *geometry)
virtual void setGeometryMode (int flag, bool v=true) override
virtual void setId (long id) override
virtual void setInternalType (InternalType::InternalType type) override
virtual bool testGeometryMode (int flag) const override
TopoDS_Shape toShape () const
void transform (Base::Matrix4D mat)
void translate (Base::Vector3d vec)
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual Type getTypeId (void) const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
template<typename... Args>
static std::unique_ptr< GeometryTypedFacade< GeometryT > > getTypedFacade (Args &&... args)
static std::unique_ptr< const GeometryTypedFacade< GeometryT > > getTypedFacade (const GeometryT *geometry)
static std::unique_ptr< GeometryTypedFacade< GeometryT > > getTypedFacade (GeometryT *geometry)
Static Public Member Functions inherited from Sketcher::GeometryFacade
static void copyId (const Part::Geometry *src, Part::Geometry *dst)
static void ensureSketchGeometryExtension (Part::Geometry *geometry)
static bool getBlocked (const Part::Geometry *geometry)
static bool getConstruction (const Part::Geometry *geometry)
static std::unique_ptr< const GeometryFacade > getFacade (const Part::Geometry *geometry)
static std::unique_ptr< GeometryFacade > getFacade (Part::Geometry *geometry)
static bool isInternalType (const Part::Geometry *geometry, InternalType::InternalType type)
static void setConstruction (Part::Geometry *geometry, bool construction)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Additional Inherited Members
Protected Member Functions inherited from Sketcher::GeometryFacade
GeometryFacade ()
GeometryFacade (const Part::Geometry *geometry)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Member Function Documentation
getTypedFacade() [1/3]
template<typename GeometryT > template<typename... Args> static std::unique_ptr<GeometryTypedFacade<GeometryT> > Sketcher::GeometryTypedFacade< GeometryT >::getTypedFacade (Args &&... args) static
References Sketcher::GeometryTypedFacade< GeometryT >::getTypedFacade().
getTypedFacade() [2/3]
template<typename GeometryT > static std::unique_ptr<const GeometryTypedFacade<GeometryT> > Sketcher::GeometryTypedFacade< GeometryT >::getTypedFacade (const GeometryT * geometry) static
getTypedFacade() [3/3]
template<typename GeometryT > static std::unique_ptr<GeometryTypedFacade<GeometryT> > Sketcher::GeometryTypedFacade< GeometryT >::getTypedFacade (GeometryT * geometry) static
Referenced by Sketcher::GeometryTypedFacade< GeometryT >::getTypedFacade(), and Sketcher::SketchObject::SketchObject().
getTypedGeometry() [1/2]
template<typename GeometryT > GeometryT* Sketcher::GeometryTypedFacade< GeometryT >::getTypedGeometry ()
getTypedGeometry() [2/2]
template<typename GeometryT > GeometryT* Sketcher::GeometryTypedFacade< GeometryT >::getTypedGeometry () const
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Sketcher/App/GeometryFacade.h