FreeCAD: Ui_TaskPostCut Class Reference
Ui_TaskPostCut Class Reference
#include <ui_TaskPostCut.h>
Public Member Functions
void retranslateUi (QWidget *TaskPostCut)
void setupUi (QWidget *TaskPostCut)
Public Attributes
QWidget * Container
QToolButton * CreateButton
QComboBox * FunctionBox
QHBoxLayout * horizontalLayout
QFrame * line
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void Ui_TaskPostCut::retranslateUi (QWidget * TaskPostCut)
References CreateButton, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void Ui_TaskPostCut::setupUi (QWidget * TaskPostCut)
References Container, CreateButton, FunctionBox, horizontalLayout, line, retranslateUi(), and verticalLayout.
Member Data Documentation
Container
QWidget* Ui_TaskPostCut::Container
Referenced by setupUi().
CreateButton
QToolButton* Ui_TaskPostCut::CreateButton
Referenced by retranslateUi(), and setupUi().
FunctionBox
QComboBox* Ui_TaskPostCut::FunctionBox
Referenced by setupUi().
horizontalLayout
QHBoxLayout* Ui_TaskPostCut::horizontalLayout
Referenced by setupUi().
line
QFrame* Ui_TaskPostCut::line
Referenced by Plot.Line::getp(), Plot.Line::setp(), setupUi(), draftguitools.gui_trackers.wireTracker::update(), and draftviewproviders.view_label.ViewProviderLabel::updateData().
verticalLayout
QVBoxLayout* Ui_TaskPostCut::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Fem/Gui/ui_TaskPostCut.h