FreeCAD: TechDrawGui::QGMarker Class Reference
TechDrawGui::QGMarker Class Reference
#include <QGEPath.h>
Public Types
enum { Type = QGraphicsItem::UserType + 302 }
Public Types inherited from TechDrawGui::QGIVertex
enum { Type = QGraphicsItem::UserType + 105 }
Public Types inherited from TechDrawGui::QGIPrimPath
enum { Type = QGraphicsItem::UserType + 170 }
Signals
void doubleClick (QPointF pos, int idx)
void dragFinished (QPointF pos, int idx)
void dragging (QPointF pos, int idx)
void endEdit (void)
Public Member Functions
virtual void keyPressEvent (QKeyEvent *event) override
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0) override
QGMarker (int idx)
virtual void setRadius (float r) override
int type () const override
virtual ~QGMarker (void)
Public Member Functions inherited from TechDrawGui::QGIVertex
int getProjIndex () const
float getRadius ()
QGIVertex (int index)
int type () const override
~QGIVertex ()
Public Member Functions inherited from TechDrawGui::QGIPrimPath
QColor getFillColor (void)
Qt::BrushStyle getFillStyle ()
Qt::PenStyle getStyle ()
virtual double getWidth ()
QGIPrimPath ()
void resetFill ()
virtual void setCapStyle (Qt::PenCapStyle c)
void setFill (QBrush b)
void setFill (QColor c, Qt::BrushStyle s)
void setFillColor (QColor c)
void setFillOverride (bool b)
void setFillStyle (Qt::BrushStyle f)
void setHighlighted (bool state)
virtual void setNormalColor (QColor c)
virtual void setPrettyNormal ()
virtual void setPrettyPre ()
virtual void setPrettySel ()
void setStyle (int s)
void setStyle (Qt::PenStyle s)
virtual void setWidth (double w)
virtual QPainterPath shape () const override
int type () const override
~QGIPrimPath ()
Protected Member Functions
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions inherited from TechDrawGui::QGIPrimPath
virtual QColor getNormalColor (void)
Base::Reference< ParameterGrp > getParmGroup (void)
virtual QColor getPreColor (void)
virtual QColor getSelectColor (void)
virtual Qt::PenCapStyle prefCapStyle (void)
Additional Inherited Members
Protected Attributes inherited from TechDrawGui::QGIVertex
float m_radius
int projIndex
Protected Attributes inherited from TechDrawGui::QGIPrimPath
bool isHighlighted
QBrush m_brush
Qt::PenCapStyle m_capStyle
QColor m_colCurrent
QColor m_colDefFill
QColor m_colNormal
QColor m_colNormalFill
bool m_colOverride
QColor m_fillColorCurrent
bool m_fillOverride
Qt::BrushStyle m_fillStyleCurrent
QPen m_pen
Qt::PenStyle m_styleCurrent
Qt::BrushStyle m_styleDef
Qt::BrushStyle m_styleNormal
Qt::BrushStyle m_styleSelect
double m_width
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGMarker()
QGMarker::QGMarker (int idx) explicit
~QGMarker()
virtual TechDrawGui::QGMarker::~QGMarker (void) virtual
Member Function Documentation
doubleClick
void TechDrawGui::QGMarker::doubleClick (QPointF pos, int idx) signal
dragFinished
void TechDrawGui::QGMarker::dragFinished (QPointF pos, int idx) signal
Referenced by mouseReleaseEvent().
dragging
void TechDrawGui::QGMarker::dragging (QPointF pos, int idx) signal
Referenced by mousePressEvent().
endEdit
void TechDrawGui::QGMarker::endEdit (void) signal
Referenced by keyPressEvent(), mouseDoubleClickEvent(), mousePressEvent(), and mouseReleaseEvent().
hoverEnterEvent()
void QGMarker::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected virtual
Reimplemented from TechDrawGui::QGIPrimPath.
References TechDrawGui::QGIPrimPath::hoverEnterEvent().
hoverLeaveEvent()
void QGMarker::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected virtual
Reimplemented from TechDrawGui::QGIPrimPath.
References TechDrawGui::QGIPrimPath::hoverLeaveEvent().
itemChange()
QVariant QGMarker::itemChange (GraphicsItemChange change, const QVariant & value) override protected virtual
Reimplemented from TechDrawGui::QGIPrimPath.
References TechDrawGui::QGIPrimPath::itemChange().
keyPressEvent()
void QGMarker::keyPressEvent (QKeyEvent * event) override virtual
References endEdit().
mouseDoubleClickEvent()
void QGMarker::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override virtual
References endEdit().
mouseMoveEvent()
void QGMarker::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override protected virtual
mousePressEvent()
void QGMarker::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected virtual
Reimplemented from TechDrawGui::QGIPrimPath.
References dragging(), endEdit(), TechDrawGui::QGIVertex::getProjIndex(), and TechDrawGui::QGIPrimPath::mousePressEvent().
mouseReleaseEvent()
void QGMarker::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override virtual
References dragFinished(), endEdit(), and TechDrawGui::QGIVertex::getProjIndex().
paint()
void QGMarker::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) override virtual
Reimplemented from TechDrawGui::QGIVertex.
References TechDrawGui::QGIVertex::paint().
setRadius()
void QGMarker::setRadius (float r) override virtual
Reimplemented from TechDrawGui::QGIVertex.
References TechDrawGui::QGIVertex::m_radius.
type()
int TechDrawGui::QGMarker::type () const override
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGEPath.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGEPath.cpp