FreeCAD: MED::TTTimeStampInfo< eVersion > Struct Template Reference
MED::TTTimeStampInfo< eVersion > Struct Template Reference
#include <MED_TStructures.hxx>
Public Member Functions
virtual std::string GetUnitDt () const
Get unit of time for the MED TimeStamp.
virtual void SetUnitDt (const std::string &theValue)
Set unit of time for the MED TimeStamp.
TTTimeStampInfo (const PFieldInfo &theFieldInfo, const PTimeStampInfo &theInfo)
TTTimeStampInfo (const PFieldInfo &theFieldInfo, EEntiteMaillage theEntity, const TGeom2Size &theGeom2Size, const TGeom2NbGauss &theGeom2NbGauss, TInt theNumDt, TInt theNumOrd, TFloat theDt, const std::string &theUnitDt, const TGeom2Gauss &theGeom2Gauss)
Public Member Functions inherited from MED::TTimeStampInfo
TFloat GetDt () const
Defines time for the MED TimeStamp.
EEntiteMaillage GetEntity () const
Let known to what MED Entity the MED TimeStamp belong to.
const PFieldInfo & GetFieldInfo () const
Get a reference to corresponding MED Field.
const TGeom2Gauss & GetGeom2Gauss () const
Gets a map of MED Gauss entityes per geometric type.
const TGeom2Size & GetGeom2Size () const
Get map of number of cells per geometric type where the MED TimeStamp belongs to.
TInt GetNbGauss (EGeometrieElement theGeom) const
Gives number of the Gauss Points for the MED TimeStamp.
TInt GetNumDt () const
Defines number in time for the MED TimeStamp.
TInt GetNumOrd () const
Defines number for the MED TimeStamp.
Public Member Functions inherited from MED::TBase
virtual ~TBase ()
Additional Inherited Members
Public Attributes inherited from MED::TTimeStampInfo
TFloat myDt
Keeps time for the MED TimeStamp.
EEntiteMaillage myEntity
Defines the MED Entity where the MED TimeStamp belongs to.
PFieldInfo myFieldInfo
A reference to correspondig MED Field.
TGeom2Gauss myGeom2Gauss
Keeps map of MED Gauss entityes per geometric type.
TGeom2NbGauss myGeom2NbGauss
Keeps number of the Gauss Points for the MED TimeStamp.
TGeom2Size myGeom2Size
Keeps map of number of cells per geometric type where the MED TimeStamp belongs to.
TInt myNumDt
Keeps number in time for the MED TimeStamp.
TInt myNumOrd
Keeps number for the MED TimeStamp.
TString myUnitDt
Defines unit for the time for the MED TimeStamp.
Constructor & Destructor Documentation
TTTimeStampInfo() [1/2]
template<EVersion eVersion> MED::TTTimeStampInfo< eVersion >::TTTimeStampInfo (const PFieldInfo & theFieldInfo, const PTimeStampInfo & theInfo)
References MED::TTimeStampInfo::myDt, MED::TTimeStampInfo::myEntity, MED::TTimeStampInfo::myFieldInfo, MED::TTimeStampInfo::myGeom2Gauss, MED::TTimeStampInfo::myGeom2NbGauss, MED::TTimeStampInfo::myGeom2Size, MED::TTimeStampInfo::myNumDt, MED::TTimeStampInfo::myNumOrd, MED::TTimeStampInfo::myUnitDt, and MED::TTTimeStampInfo< eVersion >::SetUnitDt().
TTTimeStampInfo() [2/2]
template<EVersion eVersion> MED::TTTimeStampInfo< eVersion >::TTTimeStampInfo (const PFieldInfo & theFieldInfo, EEntiteMaillage theEntity, const TGeom2Size & theGeom2Size, const TGeom2NbGauss & theGeom2NbGauss, TInt theNumDt, TInt theNumOrd, TFloat theDt, const std::string & theUnitDt, const TGeom2Gauss & theGeom2Gauss)
References MED::TTimeStampInfo::myDt, MED::TTimeStampInfo::myEntity, MED::TTimeStampInfo::myFieldInfo, MED::TTimeStampInfo::myGeom2Gauss, MED::TTimeStampInfo::myGeom2NbGauss, MED::TTimeStampInfo::myGeom2Size, MED::TTimeStampInfo::myNumDt, MED::TTimeStampInfo::myNumOrd, MED::TTimeStampInfo::myUnitDt, and MED::TTTimeStampInfo< eVersion >::SetUnitDt().
Member Function Documentation
GetUnitDt()
template<EVersion eVersion> virtual std::string MED::TTTimeStampInfo< eVersion >::GetUnitDt () const virtual
Get unit of time for the MED TimeStamp.
Implements MED::TTimeStampInfo.
References MED::GetString(), and MED::TTimeStampInfo::myUnitDt.
SetUnitDt()
template<EVersion eVersion> virtual void MED::TTTimeStampInfo< eVersion >::SetUnitDt (const std::string & theValue) virtual
Set unit of time for the MED TimeStamp.
Implements MED::TTimeStampInfo.
References MED::TTimeStampInfo::myUnitDt, and MED::SetString().
Referenced by MED::TTTimeStampInfo< eVersion >::TTTimeStampInfo().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/MED_TStructures.hxx