FreeCAD: App::ExtensionContainerPy Class Reference
App::ExtensionContainerPy Class Reference
The python export class for ExtensionContainer.
#include <ExtensionContainerPy.h>
Public Types
typedef ExtensionContainer * PointerType
Public Types inherited from App::PropertyContainerPy
typedef PropertyContainer * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
ExtensionContainerPy (ExtensionContainer *pcObject, PyTypeObject *T=&Type)
int finalization ()
virtual PyTypeObject * GetType (void)
int initialization ()
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
ExtensionContainer * getExtensionContainerPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from App::PropertyContainerPy
PropertyContainerPy (PropertyContainer *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getPropertyByName (PyObject *args)
implementer for the getPropertyByName() method
PyObject * getPropertyTouchList (PyObject *args)
implementer for the getPropertyTouchList() method
PyObject * getTypeOfProperty (PyObject *args)
implementer for the getTypeOfProperty() method
PyObject * getTypeIdOfProperty (PyObject *args)
implementer for the getTypeIdOfProperty() method
PyObject * setEditorMode (PyObject *args)
implementer for the setEditorMode() method
PyObject * getEditorMode (PyObject *args)
implementer for the getEditorMode() method
PyObject * getGroupOfProperty (PyObject *args)
implementer for the getGroupOfProperty() method
PyObject * setPropertyStatus (PyObject *args)
implementer for the setPropertyStatus() method
PyObject * getPropertyStatus (PyObject *args)
implementer for the getPropertyStatus() method
PyObject * getDocumentationOfProperty (PyObject *args)
implementer for the getDocumentationOfProperty() method
PyObject * dumpPropertyContent (PyObject *args, PyObject *kwd)
implementer for the dumpPropertyContent() method
PyObject * restorePropertyContent (PyObject *args)
implementer for the restorePropertyContent() method
Py::List getPropertiesList (void) const
getter for the PropertiesList attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
PropertyContainer * getPropertyContainerPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::PropertyContainerPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_getPropertyByName (PyObject *self, PyObject *args)
callback for the getPropertyByName() method
static PyObject * staticCallback_getPropertyTouchList (PyObject *self, PyObject *args)
callback for the getPropertyTouchList() method
static PyObject * staticCallback_getTypeOfProperty (PyObject *self, PyObject *args)
callback for the getTypeOfProperty() method
static PyObject * staticCallback_getTypeIdOfProperty (PyObject *self, PyObject *args)
callback for the getTypeIdOfProperty() method
static PyObject * staticCallback_setEditorMode (PyObject *self, PyObject *args)
callback for the setEditorMode() method
static PyObject * staticCallback_getEditorMode (PyObject *self, PyObject *args)
callback for the getEditorMode() method
static PyObject * staticCallback_getGroupOfProperty (PyObject *self, PyObject *args)
callback for the getGroupOfProperty() method
static PyObject * staticCallback_setPropertyStatus (PyObject *self, PyObject *args)
callback for the setPropertyStatus() method
static PyObject * staticCallback_getPropertyStatus (PyObject *self, PyObject *args)
callback for the getPropertyStatus() method
static PyObject * staticCallback_getDocumentationOfProperty (PyObject *self, PyObject *args)
callback for the getDocumentationOfProperty() method
static PyObject * staticCallback_dumpPropertyContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpPropertyContent() method
static PyObject * staticCallback_restorePropertyContent (PyObject *self, PyObject *args)
callback for the restorePropertyContent() method
static PyObject * staticCallback_getPropertiesList (PyObject *self, void *closure)
getter callback for the PropertiesList attribute
static int staticCallback_setPropertiesList (PyObject *self, PyObject *value, void *closure)
setter callback for the PropertiesList attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of ExtensionContainerPy.
static PyMethodDef Methods []
Methods structure of ExtensionContainerPy.
static PyTypeObject Type
Type structure of ExtensionContainerPy.
Static Public Attributes inherited from App::PropertyContainerPy
static PyGetSetDef GetterSetter []
Attribute structure of PropertyContainerPy.
static PyMethodDef Methods []
Methods structure of PropertyContainerPy.
static PyTypeObject Type
Type structure of PropertyContainerPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~ExtensionContainerPy ()
Protected Member Functions inherited from App::PropertyContainerPy
~PropertyContainerPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * addExtension (PyObject *args)
implementer for the addExtension() method
PyObject * hasExtension (PyObject *args)
implementer for the hasExtension() method
static PyObject * staticCallback_addExtension (PyObject *self, PyObject *args)
callback for the addExtension() method
static PyObject * staticCallback_hasExtension (PyObject *self, PyObject *args)
callback for the hasExtension() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for ExtensionContainer.
Member Typedef Documentation
PointerType
typedef ExtensionContainer* App::ExtensionContainerPy::PointerType
Constructor & Destructor Documentation
~ExtensionContainerPy()
ExtensionContainerPy::~ExtensionContainerPy () protected
References finalization().
ExtensionContainerPy()
ExtensionContainerPy::ExtensionContainerPy (ExtensionContainer * pcObject, PyTypeObject * T = &Type)
References initialization().
Member Function Documentation
addExtension()
PyObject * ExtensionContainerPy::addExtension (PyObject * args)
implementer for the addExtension() method
References Base::BaseExceptionFreeCADError, Base::Type::createInstance(), Base::Type::fromName(), App::GetApplication(), getExtensionContainerPtr(), Base::Type::isBad(), Base::Type::isDerivedFrom(), App::Application::signalAddedDynamicExtension, and App::Application::signalBeforeAddingDynamicExtension.
Referenced by staticCallback_addExtension().
finalization()
int ExtensionContainerPy::finalization ()
Referenced by ~ExtensionContainerPy().
getCustomAttributes()
PyObject * ExtensionContainerPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
References App::ExtensionContainer::extensionBegin(), App::ExtensionContainer::extensionEnd(), App::PropertyContainerPy::getCustomAttributes(), getExtensionContainerPtr(), and Base::streq().
getExtensionContainerPtr()
ExtensionContainer * ExtensionContainerPy::getExtensionContainerPtr (void) const
getter for the object handled by this class
Referenced by addExtension(), getCustomAttributes(), hasExtension(), and initialization().
GetType()
virtual PyTypeObject* App::ExtensionContainerPy::GetType (void) virtual
Reimplemented from App::PropertyContainerPy.
Reimplemented in TechDraw::DrawWeldSymbolPy, TechDraw::DrawViewSymbolPy, TechDraw::DrawViewPy, TechDraw::DrawViewPartPy, TechDraw::DrawViewDimExtentPy, TechDraw::DrawViewDimensionPy, TechDraw::DrawViewCollectionPy, TechDraw::DrawViewClipPy, TechDraw::DrawViewAnnotationPy, TechDraw::DrawTileWeldPy, TechDraw::DrawTilePy, TechDraw::DrawTemplatePy, TechDraw::DrawSVGTemplatePy, TechDraw::DrawRichAnnoPy, TechDraw::DrawProjGroupPy, TechDraw::DrawProjGroupItemPy, TechDraw::DrawParametricTemplatePy, TechDraw::DrawPagePy, TechDraw::DrawLeaderLinePy, TechDraw::DrawHatchPy, TechDraw::DrawGeomHatchPy, Spreadsheet::SheetPy, Sketcher::SketchObjectSFPy, Sketcher::SketchObjectPy, Robot::RobotObjectPy, Path::FeaturePathCompoundPy, Path::FeatureAreaPy, PartDesignGui::ViewProviderPy, PartDesign::FeaturePy, PartDesign::BodyPy, Part::PartFeaturePy, Part::Part2DObjectPy, Part::BodyBasePy, MeshGui::ViewProviderMeshPy, Mesh::MeshFeaturePy, FemGui::ViewProviderFemMeshPy, Fem::FemPostPipelinePy, Gui::ViewProviderPy, Gui::ViewProviderLinkPy, Gui::ViewProviderDocumentObjectPy, App::PartPy, App::GeoFeaturePy, App::DocumentObjectPy, and App::DocumentObjectGroupPy.
hasExtension()
PyObject * ExtensionContainerPy::hasExtension (PyObject * args)
implementer for the hasExtension() method
References Base::BaseExceptionFreeCADError, Base::Type::fromName(), getExtensionContainerPtr(), Base::Type::isBad(), and Base::Type::isDerivedFrom().
Referenced by staticCallback_hasExtension().
initialization()
int ExtensionContainerPy::initialization ()
References App::ExtensionContainer::extensionBegin(), App::ExtensionContainer::extensionEnd(), and getExtensionContainerPtr().
Referenced by ExtensionContainerPy().
PyInit()
int ExtensionContainerPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from App::PropertyContainerPy.
Reimplemented in TechDraw::DrawWeldSymbolPy, TechDraw::DrawViewSymbolPy, TechDraw::DrawViewPy, TechDraw::DrawViewPartPy, TechDraw::DrawViewDimExtentPy, TechDraw::DrawViewDimensionPy, TechDraw::DrawViewCollectionPy, TechDraw::DrawViewClipPy, TechDraw::DrawViewAnnotationPy, TechDraw::DrawTileWeldPy, TechDraw::DrawTilePy, TechDraw::DrawTemplatePy, TechDraw::DrawSVGTemplatePy, TechDraw::DrawRichAnnoPy, TechDraw::DrawProjGroupPy, TechDraw::DrawProjGroupItemPy, TechDraw::DrawParametricTemplatePy, TechDraw::DrawPagePy, TechDraw::DrawLeaderLinePy, TechDraw::DrawHatchPy, TechDraw::DrawGeomHatchPy, Spreadsheet::SheetPy, Sketcher::SketchObjectSFPy, Sketcher::SketchObjectPy, Robot::RobotObjectPy, Path::FeaturePathCompoundPy, Path::FeatureAreaPy, PartDesignGui::ViewProviderPy, PartDesign::FeaturePy, PartDesign::BodyPy, Part::PartFeaturePy, Part::Part2DObjectPy, Part::BodyBasePy, MeshGui::ViewProviderMeshPy, Mesh::MeshFeaturePy, FemGui::ViewProviderFemMeshPy, Fem::FemPostPipelinePy, Gui::ViewProviderPy, Gui::ViewProviderLinkPy, Gui::ViewProviderDocumentObjectPy, App::PartPy, App::GeoFeaturePy, App::DocumentObjectPy, and App::DocumentObjectGroupPy.
PyMake()
PyObject * ExtensionContainerPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string ExtensionContainerPy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int ExtensionContainerPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_addExtension()
PyObject * ExtensionContainerPy::staticCallback_addExtension (PyObject * self, PyObject * args) static
callback for the addExtension() method
References addExtension(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_hasExtension()
PyObject * ExtensionContainerPy::staticCallback_hasExtension (PyObject * self, PyObject * args) static
callback for the hasExtension() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hasExtension(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
Member Data Documentation
GetterSetter
PyGetSetDef ExtensionContainerPy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of ExtensionContainerPy.
Methods
PyMethodDef ExtensionContainerPy::Methods static
Initial value:
= {
    {"addExtension",
        reinterpret_cast<PyCFunction>( staticCallback_addExtension ),
        METH_VARARGS,
        "Adds an extension to the object. Requires the string identifier as well as the python object \n                  used to check for overridden functions (most likely self)"
    },
    {"hasExtension",
        reinterpret_cast<PyCFunction>( staticCallback_hasExtension ),
        METH_VARARGS,
        "Returns if this object has the specified extension"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of ExtensionContainerPy.
Type
PyTypeObject ExtensionContainerPy::Type static
Type structure of ExtensionContainerPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/App/ExtensionContainerPy.h
Sources/FreeCAD/src/App/ExtensionContainerPyImp.cpp
Sources/FreeCAD-SourceDocs/src/App/ExtensionContainerPy.cpp