FreeCAD: Base::Factory Class Reference
Base::Factory Class Reference
Base class of all factories This class has the purpose to produce at runtime instances of classes not known at compile time.
#include <Factory.h>
Public Member Functions
void AddProducer (const char *sClassName, AbstractProducer *pcProducer)
Adds a new prducer instance.
std::list< std::string > CanProduce () const
returns a list of all registered producer
bool CanProduce (const char *sClassName) const
returns true if there is a producer for this class registered
Protected Member Functions
Factory (void)
construction
void * Produce (const char *sClassName) const
produce a class with the given name
virtual ~Factory ()
destruction
Detailed Description
Base class of all factories This class has the purpose to produce at runtime instances of classes not known at compile time.
It holds a map of so called producers which are able to produce an instance of a special class. Producer can be registered at runtime through e.g. application modules
Constructor & Destructor Documentation
Factory()
Base::Factory::Factory (void) protected
construction
~Factory()
Factory::~Factory () protected virtual
destruction
Member Function Documentation
AddProducer()
void Factory::AddProducer (const char * sClassName, AbstractProducer * pcProducer)
Adds a new prducer instance.
Referenced by Gui::CustomPageProducer< CLASS >::CustomPageProducer(), Base::ExceptionProducer< CLASS >::ExceptionProducer(), Gui::PrefPageProducer< CLASS >::PrefPageProducer(), Gui::PrefPagePyProducer::PrefPagePyProducer(), Gui::PrefPageUiProducer::PrefPageUiProducer(), Gui::PropertyEditor::PropertyItemProducer< CLASS >::PropertyItemProducer(), Base::ScriptProducer::ScriptProducer(), and Gui::WidgetProducer< CLASS >::WidgetProducer().
CanProduce() [1/2]
std::list< std::string > Factory::CanProduce () const
returns a list of all registered producer
CanProduce() [2/2]
bool Factory::CanProduce (const char * sClassName) const
returns true if there is a producer for this class registered
Produce()
void * Factory::Produce (const char * sClassName) const protected
produce a class with the given name
Referenced by Gui::WidgetFactoryInst::createPreferencePage(), Gui::WidgetFactoryInst::createWidget(), Gui::WorkbenchFactoryInst::createWorkbench(), and Base::ScriptFactorySingleton::ProduceScript().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Base/Factory.h
Sources/FreeCAD/src/Base/Factory.cpp