FreeCAD: PathScripts.post.heidenhain_post Namespace Reference
PathScripts.post.heidenhain_post Namespace Reference
Functions
def export (objectslist, filename, argstring)
def HEIDEN_Arc (arc_Params, arc_direction, arc_comp, arc_feed, arc_rapid, arc_M_funct, Cmd_Number)
def HEIDEN_Begin (ActualJob)
def HEIDEN_Drill (drill_Obj, drill_Params, drill_Type, drill_feed)
def HEIDEN_End (ActualJob)
def HEIDEN_Format (formatType, formatValue)
def HEIDEN_LBL_Get (GetPoint=None, GetLevel=None, GetAddit=0)
def HEIDEN_LBL_Replace ()
def HEIDEN_Line (line_Params, line_comp, line_feed, line_rapid, line_M_funct, Cmd_Number)
def HEIDEN_Numberize (GCodeStrings)
def HEIDEN_PolarArc (pol_cc_X, pol_cc_Y, pol_X, pol_Y, pol_Z, pol_Axis, pol_Incr)
def HEIDEN_ToolCall (tool_Params)
def processArguments (argstring)
Variables
action
int AXIS_DECIMALS = 3
list COMPENSATION_DIFF_STATUS = [False, True]
default
int FEED_DECIMALS = 0
int FEED_MAX_SPEED = 8000
int FIRST_LBL = 1
dictionary G_FUNCTION_STORE
help
bool LBLIZE_ACTIVE = False
int LBLIZE_PATH_LEVEL = 99999
bool LBLIZE_STAUS = False
int LINENUMBER_INCREMENT = 1
bool LINENUMBERS = True
dictionary MACHINE_CYCLE_DEF
dictionary MACHINE_LAST_CENTER
dictionary MACHINE_LAST_POSITION
bool MACHINE_SKIP_PARAMS = False
int MACHINE_SPINDLE_DIRECTION = 3
list MACHINE_STORED_PARAMS = ['', -1, '']
list MACHINE_TRASL_ROT = [0, 0, 0, 0]
bool MACHINE_USE_FMAX = False
int MACHINE_WORK_AXIS = 2
parser = argparse.ArgumentParser(prog='heidenhain', add_help=False)
list POSTGCODE = []
pythonopen = open
bool SHOW_EDITOR = True
bool SKIP_WARNS = False
bool SOLVE_COMPENSATION_ACTIVE = False
int SPINDLE_DECIMALS = 0
int STARTLINENR = 0
dictionary STORED_CANNED_PARAMS
tuple STORED_COMPENSATED_OBJ = ()
list STORED_LBL = []
string TOOLTIP
TOOLTIP_ARGS = parser.format_help()
string UNITS = 'MM'
Function Documentation
export()
def PathScripts.post.heidenhain_post.export (objectslist, filename, argstring)
References PathScripts.post.heidenhain_post.HEIDEN_Arc(), PathScripts.post.heidenhain_post.HEIDEN_Begin(), PathScripts.post.heidenhain_post.HEIDEN_Drill(), PathScripts.post.heidenhain_post.HEIDEN_End(), PathScripts.post.heidenhain_post.HEIDEN_LBL_Replace(), PathScripts.post.heidenhain_post.HEIDEN_Line(), PathScripts.post.heidenhain_post.HEIDEN_Numberize(), PathScripts.post.heidenhain_post.HEIDEN_ToolCall(), PathScripts.post.heidenhain_post.processArguments(), and PathScripts.post.heidenhain_post.pythonopen.
HEIDEN_Arc()
def PathScripts.post.heidenhain_post.HEIDEN_Arc (arc_Params, arc_direction, arc_comp, arc_feed, arc_rapid, arc_M_funct, Cmd_Number)
References PathScripts.post.heidenhain_post.HEIDEN_Format(), PathScripts.post.heidenhain_post.HEIDEN_LBL_Get(), and PathScripts.post.heidenhain_post.HEIDEN_PolarArc().
Referenced by PathScripts.post.heidenhain_post.export().
HEIDEN_Begin()
def PathScripts.post.heidenhain_post.HEIDEN_Begin (ActualJob)
Referenced by PathScripts.post.heidenhain_post.export().
HEIDEN_Drill()
def PathScripts.post.heidenhain_post.HEIDEN_Drill (drill_Obj, drill_Params, drill_Type, drill_feed)
References PathScripts.post.heidenhain_post.HEIDEN_Format().
Referenced by PathScripts.post.heidenhain_post.export().
HEIDEN_End()
def PathScripts.post.heidenhain_post.HEIDEN_End (ActualJob)
Referenced by PathScripts.post.heidenhain_post.export().
HEIDEN_Format()
def PathScripts.post.heidenhain_post.HEIDEN_Format (formatType, formatValue)
Referenced by PathScripts.post.heidenhain_post.HEIDEN_Arc(), PathScripts.post.heidenhain_post.HEIDEN_Drill(), PathScripts.post.heidenhain_post.HEIDEN_Line(), PathScripts.post.heidenhain_post.HEIDEN_PolarArc(), and PathScripts.post.heidenhain_post.HEIDEN_ToolCall().
HEIDEN_LBL_Get()
def PathScripts.post.heidenhain_post.HEIDEN_LBL_Get (GetPoint = None, GetLevel = None, GetAddit = 0)
Referenced by PathScripts.post.heidenhain_post.HEIDEN_Arc(), and PathScripts.post.heidenhain_post.HEIDEN_Line().
HEIDEN_LBL_Replace()
def PathScripts.post.heidenhain_post.HEIDEN_LBL_Replace ()
Referenced by PathScripts.post.heidenhain_post.export().
HEIDEN_Line()
def PathScripts.post.heidenhain_post.HEIDEN_Line (line_Params, line_comp, line_feed, line_rapid, line_M_funct, Cmd_Number)
References PathScripts.post.heidenhain_post.HEIDEN_Format(), and PathScripts.post.heidenhain_post.HEIDEN_LBL_Get().
Referenced by PathScripts.post.heidenhain_post.export().
HEIDEN_Numberize()
def PathScripts.post.heidenhain_post.HEIDEN_Numberize (GCodeStrings)
Referenced by PathScripts.post.heidenhain_post.export().
HEIDEN_PolarArc()
def PathScripts.post.heidenhain_post.HEIDEN_PolarArc (pol_cc_X, pol_cc_Y, pol_X, pol_Y, pol_Z, pol_Axis, pol_Incr)
References PathScripts.post.heidenhain_post.HEIDEN_Format().
Referenced by PathScripts.post.heidenhain_post.HEIDEN_Arc().
HEIDEN_ToolCall()
def PathScripts.post.heidenhain_post.HEIDEN_ToolCall (tool_Params)
References PathScripts.post.heidenhain_post.HEIDEN_Format().
Referenced by PathScripts.post.heidenhain_post.export().
processArguments()
def PathScripts.post.heidenhain_post.processArguments (argstring)
Referenced by PathScripts.post.heidenhain_post.export().
Variable Documentation
action
PathScripts.post.heidenhain_post.action
AXIS_DECIMALS
int PathScripts.post.heidenhain_post.AXIS_DECIMALS = 3
COMPENSATION_DIFF_STATUS
list PathScripts.post.heidenhain_post.COMPENSATION_DIFF_STATUS = [False, True]
default
PathScripts.post.heidenhain_post.default
FEED_DECIMALS
int PathScripts.post.heidenhain_post.FEED_DECIMALS = 0
FEED_MAX_SPEED
int PathScripts.post.heidenhain_post.FEED_MAX_SPEED = 8000
FIRST_LBL
int PathScripts.post.heidenhain_post.FIRST_LBL = 1
G_FUNCTION_STORE
dictionary PathScripts.post.heidenhain_post.G_FUNCTION_STORE
Initial value:
 =  {
     'G90': False, 'G91': False,
     'G98': False, 'G99': False,
     'G81': False, 'G82': False, 'G83': False
     }
help
PathScripts.post.heidenhain_post.help
LBLIZE_ACTIVE
bool PathScripts.post.heidenhain_post.LBLIZE_ACTIVE = False
LBLIZE_PATH_LEVEL
int PathScripts.post.heidenhain_post.LBLIZE_PATH_LEVEL = 99999
LBLIZE_STAUS
bool PathScripts.post.heidenhain_post.LBLIZE_STAUS = False
LINENUMBER_INCREMENT
int PathScripts.post.heidenhain_post.LINENUMBER_INCREMENT = 1
LINENUMBERS
bool PathScripts.post.heidenhain_post.LINENUMBERS = True
MACHINE_CYCLE_DEF
dictionary PathScripts.post.heidenhain_post.MACHINE_CYCLE_DEF
Initial value:
 =  {
     1: "CYCL DEF 1.0 FORATURA PROF." + "\n"
      + "CYCL DEF 1.1 DIST" + "{DIST}\n"
      + "CYCL DEF 1.2 PROF" + "{DEPTH}\n"
      + "CYCL DEF 1.3 INCR" + "{INCR}\n"
      + "CYCL DEF 1.4 SOSTA" + "{DWELL}\n"
      + "CYCL DEF 1.5 F" + "{FEED}",
     2: "",
     7: ""
     }
MACHINE_LAST_CENTER
dictionary PathScripts.post.heidenhain_post.MACHINE_LAST_CENTER
Initial value:
 =  {                 # CC initial values to overwrite
     'X': 99999,
     'Y': 99999,
     'Z': 99999
     }
MACHINE_LAST_POSITION
dictionary PathScripts.post.heidenhain_post.MACHINE_LAST_POSITION
Initial value:
 =  {               # axis initial values to overwrite
     'X': 99999,
     'Y': 99999,
     'Z': 99999,
     'A': 99999,
     'B': 99999,
     'C': 99999
     }
MACHINE_SKIP_PARAMS
bool PathScripts.post.heidenhain_post.MACHINE_SKIP_PARAMS = False
MACHINE_SPINDLE_DIRECTION
int PathScripts.post.heidenhain_post.MACHINE_SPINDLE_DIRECTION = 3
MACHINE_STORED_PARAMS
list PathScripts.post.heidenhain_post.MACHINE_STORED_PARAMS = ['', -1, '']
MACHINE_TRASL_ROT
list PathScripts.post.heidenhain_post.MACHINE_TRASL_ROT = [0, 0, 0, 0]
MACHINE_USE_FMAX
bool PathScripts.post.heidenhain_post.MACHINE_USE_FMAX = False
MACHINE_WORK_AXIS
int PathScripts.post.heidenhain_post.MACHINE_WORK_AXIS = 2
parser
PathScripts.post.heidenhain_post.parser = argparse.ArgumentParser(prog='heidenhain', add_help=False)
POSTGCODE
list PathScripts.post.heidenhain_post.POSTGCODE = []
pythonopen
PathScripts.post.heidenhain_post.pythonopen = open
Referenced by PathScripts.post.heidenhain_post.export().
SHOW_EDITOR
bool PathScripts.post.heidenhain_post.SHOW_EDITOR = True
SKIP_WARNS
bool PathScripts.post.heidenhain_post.SKIP_WARNS = False
SOLVE_COMPENSATION_ACTIVE
bool PathScripts.post.heidenhain_post.SOLVE_COMPENSATION_ACTIVE = False
SPINDLE_DECIMALS
int PathScripts.post.heidenhain_post.SPINDLE_DECIMALS = 0
STARTLINENR
int PathScripts.post.heidenhain_post.STARTLINENR = 0
STORED_CANNED_PARAMS
dictionary PathScripts.post.heidenhain_post.STORED_CANNED_PARAMS
Initial value:
 =  {                # Store canned cycles for match
     'DIST': 99999,
     'DEPTH': 99999,
     'INCR': 99999,
     'DWELL': 99999,
     'FEED': 99999
     }
STORED_COMPENSATED_OBJ
tuple PathScripts.post.heidenhain_post.STORED_COMPENSATED_OBJ = ()
STORED_LBL
list PathScripts.post.heidenhain_post.STORED_LBL = []
TOOLTIP
string PathScripts.post.heidenhain_post.TOOLTIP
Initial value:
 =  '''
 This is a postprocessor file for the Path workbench. It is used to
 take a pseudo-gcode fragment outputted by a Path object, and output
 real GCode suitable for a heidenhain 3 axis mill. This postprocessor, once placed
 in the appropriate PathScripts folder, can be used directly from inside
 FreeCAD, via the GUI importer or via python scripts with:
 import heidenhain_post
 heidenhain.export(object,"/path/to/file.ncc","")
 '''
TOOLTIP_ARGS
PathScripts.post.heidenhain_post.TOOLTIP_ARGS = parser.format_help()
UNITS
string PathScripts.post.heidenhain_post.UNITS = 'MM'