FreeCAD: Gui::SoAutoZoomTranslation Class Reference
Gui::SoAutoZoomTranslation Class Reference
#include <SoAutoZoomTranslation.h>
Public Member Functions
SoAutoZoomTranslation ()
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFFloat scaleFactor
Protected Member Functions
virtual void callback (SoCallbackAction *action)
virtual void doAction (SoAction *action)
virtual void getBoundingBox (SoGetBoundingBoxAction *action)
virtual void getMatrix (SoGetMatrixAction *action)
virtual void getPrimitiveCount (SoGetPrimitiveCountAction *action)
float getScaleFactor (SoAction *) const
virtual void GLRender (SoGLRenderAction *action)
virtual void pick (SoPickAction *action)
virtual ~SoAutoZoomTranslation ()
Constructor & Destructor Documentation
SoAutoZoomTranslation()
SoAutoZoomTranslation::SoAutoZoomTranslation ()
References scaleFactor.
~SoAutoZoomTranslation()
virtual Gui::SoAutoZoomTranslation::~SoAutoZoomTranslation () protected virtual
Member Function Documentation
callback()
void SoAutoZoomTranslation::callback (SoCallbackAction * action) protected virtual
References doAction().
Referenced by qtunittest.GUITestResult::addError(), Mod.Test.unittestgui.GUITestResult::addError(), qtunittest.GUITestResult::addFailure(), Mod.Test.unittestgui.GUITestResult::addFailure(), ArchStructure.StructSelectionObserver::addSelection(), PathScripts.PathCamoticsGui.CamoticsSimulation::execute(), qtunittest.GUITestResult::startTest(), Mod.Test.unittestgui.GUITestResult::startTest(), qtunittest.GUITestResult::stopTest(), and Mod.Test.unittestgui.GUITestResult::stopTest().
doAction()
void SoAutoZoomTranslation::doAction (SoAction * action) protected virtual
References getScaleFactor().
Referenced by callback(), getBoundingBox(), getPrimitiveCount(), GLRender(), and pick().
getBoundingBox()
void SoAutoZoomTranslation::getBoundingBox (SoGetBoundingBoxAction * action) protected virtual
References doAction().
getMatrix()
void SoAutoZoomTranslation::getMatrix (SoGetMatrixAction * action) protected virtual
References getScaleFactor().
getPrimitiveCount()
void SoAutoZoomTranslation::getPrimitiveCount (SoGetPrimitiveCountAction * action) protected virtual
References doAction().
getScaleFactor()
float SoAutoZoomTranslation::getScaleFactor (SoAction * action) const protected
References draftfunctions.scale::scale(), and scaleFactor.
Referenced by doAction(), and getMatrix().
GLRender()
void SoAutoZoomTranslation::GLRender (SoGLRenderAction * action) protected virtual
References doAction().
initClass()
void SoAutoZoomTranslation::initClass () static
Referenced by Gui::SoFCDB::init().
pick()
void SoAutoZoomTranslation::pick (SoPickAction * action) protected virtual
References doAction().
Member Data Documentation
scaleFactor
SoSFFloat Gui::SoAutoZoomTranslation::scaleFactor
Referenced by PartDesignGui::ViewProviderDatumCoordinateSystem::attach(), Gui::AxisOrigin::getNode(), getScaleFactor(), PartDesignGui::ViewProviderDatumCoordinateSystem::onChanged(), and SoAutoZoomTranslation().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/Inventor/SoAutoZoomTranslation.h
FreeCAD/src/Gui/Inventor/SoAutoZoomTranslation.cpp