FreeCAD: SMESH::Controls::BareBorderVolume Class Reference
SMESH::Controls::BareBorderVolume Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
BareBorderVolume ()
virtual SMDSAbs_ElementType GetType () const
virtual bool IsSatisfy (long theElementId)
virtual void SetMesh (const SMDS_Mesh *theMesh)
Public Member Functions inherited from SMESH::Controls::Functor
~Functor ()
Protected Attributes
const SMDS_Mesh * myMesh
Constructor & Destructor Documentation
BareBorderVolume()
SMESH::Controls::BareBorderVolume::BareBorderVolume ()
Member Function Documentation
GetType()
virtual SMDSAbs_ElementType SMESH::Controls::BareBorderVolume::GetType () const virtual
Implements SMESH::Controls::Predicate.
IsSatisfy()
bool BareBorderVolume::IsSatisfy (long theElementId) virtual
Implements SMESH::Controls::Predicate.
References SMDS_Mesh::FindElement(), SMDS_VolumeTool::GetFaceNodes(), SMDS_VolumeTool::IsFreeFace(), SMESH::Controls::NumericalFunctor::myMesh, SMDS_VolumeTool::NbFaceNodes(), SMDS_VolumeTool::NbFaces(), and SMDS_VolumeTool::Set().
SetMesh()
virtual void SMESH::Controls::BareBorderVolume::SetMesh (const SMDS_Mesh * theMesh) virtual
Implements SMESH::Controls::Functor.
Member Data Documentation
myMesh
const SMDS_Mesh* SMESH::Controls::BareBorderVolume::myMesh protected
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp