FreeCAD: Path::VoronoiEdgePy Class Reference
Path::VoronoiEdgePy Class Reference
The python export class for VoronoiEdge.
#include <VoronoiEdgePy.h>
Public Types
typedef VoronoiEdge * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
VoronoiEdgePy (VoronoiEdge *pcObject, PyTypeObject *T=&Type)
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * richCompare (PyObject *v, PyObject *w, int op)
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of VoronoiEdgePy.
static PyMethodDef Methods []
Methods structure of VoronoiEdgePy.
static PyTypeObject Type
Type structure of VoronoiEdgePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~VoronoiEdgePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
static PyObject * staticCallback_isFinite (PyObject *self, PyObject *args)
callback for the isFinite() method
static PyObject * staticCallback_isInfinite (PyObject *self, PyObject *args)
callback for the isInfinite() method
static PyObject * staticCallback_isLinear (PyObject *self, PyObject *args)
callback for the isLinear() method
static PyObject * staticCallback_isCurved (PyObject *self, PyObject *args)
callback for the isCurved() method
static PyObject * staticCallback_isPrimary (PyObject *self, PyObject *args)
callback for the isPrimary() method
static PyObject * staticCallback_isSecondary (PyObject *self, PyObject *args)
callback for the isSecondary() method
static PyObject * staticCallback_toShape (PyObject *self, PyObject *args)
callback for the toShape() method
static PyObject * staticCallback_getDistances (PyObject *self, PyObject *args)
callback for the getDistances() method
static PyObject * staticCallback_getSegmentAngle (PyObject *self, PyObject *args)
callback for the getSegmentAngle() method
PyObject * isFinite (PyObject *args)
implementer for the isFinite() method
PyObject * isInfinite (PyObject *args)
implementer for the isInfinite() method
PyObject * isLinear (PyObject *args)
implementer for the isLinear() method
PyObject * isCurved (PyObject *args)
implementer for the isCurved() method
PyObject * isPrimary (PyObject *args)
implementer for the isPrimary() method
PyObject * isSecondary (PyObject *args)
implementer for the isSecondary() method
PyObject * toShape (PyObject *args)
implementer for the toShape() method
PyObject * getDistances (PyObject *args)
implementer for the getDistances() method
PyObject * getSegmentAngle (PyObject *args)
implementer for the getSegmentAngle() method
callbacks and implementers for the python object attributes
static PyObject * staticCallback_getIndex (PyObject *self, void *closure)
getter callback for the Index attribute
static int staticCallback_setIndex (PyObject *self, PyObject *value, void *closure)
setter callback for the Index attribute
static PyObject * staticCallback_getColor (PyObject *self, void *closure)
getter callback for the Color attribute
static int staticCallback_setColor (PyObject *self, PyObject *value, void *closure)
setter callback for the Color attribute
static PyObject * staticCallback_getCell (PyObject *self, void *closure)
getter callback for the Cell attribute
static int staticCallback_setCell (PyObject *self, PyObject *value, void *closure)
setter callback for the Cell attribute
static PyObject * staticCallback_getVertices (PyObject *self, void *closure)
getter callback for the Vertices attribute
static int staticCallback_setVertices (PyObject *self, PyObject *value, void *closure)
setter callback for the Vertices attribute
static PyObject * staticCallback_getNext (PyObject *self, void *closure)
getter callback for the Next attribute
static int staticCallback_setNext (PyObject *self, PyObject *value, void *closure)
setter callback for the Next attribute
static PyObject * staticCallback_getPrev (PyObject *self, void *closure)
getter callback for the Prev attribute
static int staticCallback_setPrev (PyObject *self, PyObject *value, void *closure)
setter callback for the Prev attribute
static PyObject * staticCallback_getRotNext (PyObject *self, void *closure)
getter callback for the RotNext attribute
static int staticCallback_setRotNext (PyObject *self, PyObject *value, void *closure)
setter callback for the RotNext attribute
static PyObject * staticCallback_getRotPrev (PyObject *self, void *closure)
getter callback for the RotPrev attribute
static int staticCallback_setRotPrev (PyObject *self, PyObject *value, void *closure)
setter callback for the RotPrev attribute
static PyObject * staticCallback_getTwin (PyObject *self, void *closure)
getter callback for the Twin attribute
static int staticCallback_setTwin (PyObject *self, PyObject *value, void *closure)
setter callback for the Twin attribute
Py::Long getIndex (void) const
getter for the Index attribute
Py::Long getColor (void) const
getter for the Color attribute
void setColor (Py::Long arg)
setter for the Color attribute
Py::Object getCell (void) const
getter for the Cell attribute
Py::List getVertices (void) const
getter for the Vertices attribute
Py::Object getNext (void) const
getter for the Next attribute
Py::Object getPrev (void) const
getter for the Prev attribute
Py::Object getRotNext (void) const
getter for the RotNext attribute
Py::Object getRotPrev (void) const
getter for the RotPrev attribute
Py::Object getTwin (void) const
getter for the Twin attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
VoronoiEdge * getVoronoiEdgePtr (void) const
getter for the object handled by this class
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for VoronoiEdge.
Member Typedef Documentation
PointerType
typedef VoronoiEdge* Path::VoronoiEdgePy::PointerType
Constructor & Destructor Documentation
~VoronoiEdgePy()
VoronoiEdgePy::~VoronoiEdgePy () protected
VoronoiEdgePy()
VoronoiEdgePy::VoronoiEdgePy (VoronoiEdge * pcObject, PyTypeObject * T = &Type)
Referenced by getNext(), getPrev(), getRotNext(), getRotPrev(), getTwin(), and PyMake().
Member Function Documentation
getCell()
Py::Object VoronoiEdgePy::getCell (void) const
getter for the Cell attribute
Referenced by staticCallback_getCell().
getColor()
Py::Long VoronoiEdgePy::getColor (void) const
getter for the Color attribute
References Path::Voronoi::ColorMask, and getVoronoiEdgePtr().
Referenced by staticCallback_getColor().
getCustomAttributes()
PyObject * VoronoiEdgePy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getDistances()
PyObject * VoronoiEdgePy::getDistances (PyObject * args)
implementer for the getDistances() method
Referenced by staticCallback_getDistances().
getIndex()
Py::Long VoronoiEdgePy::getIndex (void) const
getter for the Index attribute
References getVoronoiEdgePtr().
Referenced by staticCallback_getIndex().
getNext()
Py::Object VoronoiEdgePy::getNext (void) const
getter for the Next attribute
References VoronoiEdgePy().
Referenced by staticCallback_getNext().
getPrev()
Py::Object VoronoiEdgePy::getPrev (void) const
getter for the Prev attribute
References VoronoiEdgePy().
Referenced by staticCallback_getPrev().
getRotNext()
Py::Object VoronoiEdgePy::getRotNext (void) const
getter for the RotNext attribute
References VoronoiEdgePy().
Referenced by staticCallback_getRotNext().
getRotPrev()
Py::Object VoronoiEdgePy::getRotPrev (void) const
getter for the RotPrev attribute
References VoronoiEdgePy().
Referenced by staticCallback_getRotPrev().
getSegmentAngle()
PyObject * VoronoiEdgePy::getSegmentAngle (PyObject * args)
implementer for the getSegmentAngle() method
Referenced by staticCallback_getSegmentAngle().
getTwin()
Py::Object VoronoiEdgePy::getTwin (void) const
getter for the Twin attribute
References VoronoiEdgePy().
Referenced by staticCallback_getTwin().
GetType()
virtual PyTypeObject* Path::VoronoiEdgePy::GetType (void) virtual
Reimplemented from Base::BaseClassPy.
getVertices()
Py::List VoronoiEdgePy::getVertices (void) const
getter for the Vertices attribute
References getVoronoiEdgePtr().
Referenced by staticCallback_getVertices().
getVoronoiEdgePtr()
VoronoiEdge * VoronoiEdgePy::getVoronoiEdgePtr (void) const
getter for the object handled by this class
Referenced by getColor(), getIndex(), getVertices(), representation(), richCompare(), and toShape().
isCurved()
PyObject * VoronoiEdgePy::isCurved (PyObject * args)
implementer for the isCurved() method
Referenced by staticCallback_isCurved().
isFinite()
PyObject * VoronoiEdgePy::isFinite (PyObject * args)
implementer for the isFinite() method
Referenced by staticCallback_isFinite().
isInfinite()
PyObject * VoronoiEdgePy::isInfinite (PyObject * args)
implementer for the isInfinite() method
Referenced by staticCallback_isInfinite().
isLinear()
PyObject * VoronoiEdgePy::isLinear (PyObject * args)
implementer for the isLinear() method
Referenced by staticCallback_isLinear().
isPrimary()
PyObject * VoronoiEdgePy::isPrimary (PyObject * args)
implementer for the isPrimary() method
Referenced by staticCallback_isPrimary().
isSecondary()
PyObject * VoronoiEdgePy::isSecondary (PyObject * args)
implementer for the isSecondary() method
Referenced by staticCallback_isSecondary().
PyInit()
int VoronoiEdgePy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::BaseClassPy.
PyMake()
PyObject * VoronoiEdgePy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References VoronoiEdgePy().
representation()
std::string VoronoiEdgePy::representation (void) const
References getVoronoiEdgePtr().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
richCompare()
PyObject * VoronoiEdgePy::richCompare (PyObject * v, PyObject * w, int op) static
References Path::VoronoiEdge::dia, getVoronoiEdgePtr(), Path::VoronoiEdge::index, and Type.
setColor()
void VoronoiEdgePy::setColor (Py::Long arg)
setter for the Color attribute
References Path::Voronoi::ColorMask.
Referenced by staticCallback_setColor().
setCustomAttributes()
int VoronoiEdgePy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_getCell()
PyObject * VoronoiEdgePy::staticCallback_getCell (PyObject * self, void * closure) static
getter callback for the Cell attribute
References Base::BaseExceptionFreeCADError, getCell(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getColor()
PyObject * VoronoiEdgePy::staticCallback_getColor (PyObject * self, void * closure) static
getter callback for the Color attribute
References Base::BaseExceptionFreeCADError, getColor(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getDistances()
PyObject * VoronoiEdgePy::staticCallback_getDistances (PyObject * self, PyObject * args) static
callback for the getDistances() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getDistances(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getIndex()
PyObject * VoronoiEdgePy::staticCallback_getIndex (PyObject * self, void * closure) static
getter callback for the Index attribute
References Base::BaseExceptionFreeCADError, getIndex(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNext()
PyObject * VoronoiEdgePy::staticCallback_getNext (PyObject * self, void * closure) static
getter callback for the Next attribute
References Base::BaseExceptionFreeCADError, getNext(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPrev()
PyObject * VoronoiEdgePy::staticCallback_getPrev (PyObject * self, void * closure) static
getter callback for the Prev attribute
References Base::BaseExceptionFreeCADError, getPrev(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRotNext()
PyObject * VoronoiEdgePy::staticCallback_getRotNext (PyObject * self, void * closure) static
getter callback for the RotNext attribute
References Base::BaseExceptionFreeCADError, getRotNext(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRotPrev()
PyObject * VoronoiEdgePy::staticCallback_getRotPrev (PyObject * self, void * closure) static
getter callback for the RotPrev attribute
References Base::BaseExceptionFreeCADError, getRotPrev(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSegmentAngle()
PyObject * VoronoiEdgePy::staticCallback_getSegmentAngle (PyObject * self, PyObject * args) static
callback for the getSegmentAngle() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getSegmentAngle(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTwin()
PyObject * VoronoiEdgePy::staticCallback_getTwin (PyObject * self, void * closure) static
getter callback for the Twin attribute
References Base::BaseExceptionFreeCADError, getTwin(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getVertices()
PyObject * VoronoiEdgePy::staticCallback_getVertices (PyObject * self, void * closure) static
getter callback for the Vertices attribute
References Base::BaseExceptionFreeCADError, getVertices(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isCurved()
PyObject * VoronoiEdgePy::staticCallback_isCurved (PyObject * self, PyObject * args) static
callback for the isCurved() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isCurved(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isFinite()
PyObject * VoronoiEdgePy::staticCallback_isFinite (PyObject * self, PyObject * args) static
callback for the isFinite() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isFinite(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isInfinite()
PyObject * VoronoiEdgePy::staticCallback_isInfinite (PyObject * self, PyObject * args) static
callback for the isInfinite() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isInfinite(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isLinear()
PyObject * VoronoiEdgePy::staticCallback_isLinear (PyObject * self, PyObject * args) static
callback for the isLinear() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isLinear(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isPrimary()
PyObject * VoronoiEdgePy::staticCallback_isPrimary (PyObject * self, PyObject * args) static
callback for the isPrimary() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isPrimary(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_isSecondary()
PyObject * VoronoiEdgePy::staticCallback_isSecondary (PyObject * self, PyObject * args) static
callback for the isSecondary() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isSecondary(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setCell()
int VoronoiEdgePy::staticCallback_setCell (PyObject * self, PyObject * value, void * closure) static
setter callback for the Cell attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setColor()
int VoronoiEdgePy::staticCallback_setColor (PyObject * self, PyObject * value, void * closure) static
setter callback for the Color attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setColor().
staticCallback_setIndex()
int VoronoiEdgePy::staticCallback_setIndex (PyObject * self, PyObject * value, void * closure) static
setter callback for the Index attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setNext()
int VoronoiEdgePy::staticCallback_setNext (PyObject * self, PyObject * value, void * closure) static
setter callback for the Next attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPrev()
int VoronoiEdgePy::staticCallback_setPrev (PyObject * self, PyObject * value, void * closure) static
setter callback for the Prev attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setRotNext()
int VoronoiEdgePy::staticCallback_setRotNext (PyObject * self, PyObject * value, void * closure) static
setter callback for the RotNext attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setRotPrev()
int VoronoiEdgePy::staticCallback_setRotPrev (PyObject * self, PyObject * value, void * closure) static
setter callback for the RotPrev attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setTwin()
int VoronoiEdgePy::staticCallback_setTwin (PyObject * self, PyObject * value, void * closure) static
setter callback for the Twin attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setVertices()
int VoronoiEdgePy::staticCallback_setVertices (PyObject * self, PyObject * value, void * closure) static
setter callback for the Vertices attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_toShape()
PyObject * VoronoiEdgePy::staticCallback_toShape (PyObject * self, PyObject * args) static
callback for the toShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and toShape().
toShape()
PyObject * VoronoiEdgePy::toShape (PyObject * args)
implementer for the toShape() method
References getVoronoiEdgePtr(), and Part::GeomLineSegment::setPoints().
Referenced by staticCallback_toShape().
Member Data Documentation
GetterSetter
PyGetSetDef VoronoiEdgePy::GetterSetter static
Attribute structure of VoronoiEdgePy.
Methods
PyMethodDef VoronoiEdgePy::Methods static
Methods structure of VoronoiEdgePy.
Type
PyTypeObject VoronoiEdgePy::Type static
Type structure of VoronoiEdgePy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), and richCompare().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/VoronoiEdgePy.h
Sources/FreeCAD/src/Mod/Path/App/VoronoiEdgePyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Path/App/VoronoiEdgePy.cpp