FreeCAD: Element_Header Struct Reference
Element_Header Struct Reference
#include <Element_Header.h>
Public Member Functions
Element_Header ()
Element_Header (Context &cont, bool zLib=false)
void read (Context &cont, bool zLib=false)
Public Attributes
I32 Element_Length
UChar Object_Base_Type
GUID Object_Type_ID
Constructor & Destructor Documentation
Element_Header() [1/2]
Element_Header::Element_Header ()
Element_Header() [2/2]
Element_Header::Element_Header (Context & cont, bool zLib = false)
References read().
Member Function Documentation
read()
void Element_Header::read (Context & cont, bool zLib = false)
References Element_Length, Object_Base_Type, Object_Type_ID, GUID::read(), I32::read(), and UChar::read().
Referenced by Element_Header(), gzip_utf8.GzipFile::readline(), and gzip_utf8.GzipFile::seek().
Member Data Documentation
Element_Length
I32 Element_Header::Element_Length
Referenced by read().
Object_Base_Type
UChar Element_Header::Object_Base_Type
Referenced by read().
Object_Type_ID
GUID Element_Header::Object_Type_ID
Referenced by read(), and JtReader::readLodSegment().
The documentation for this struct was generated from the following file:
FreeCAD/src/Mod/JtReader/App/JrJt/Element_Header.h