FreeCAD: Base::RotationPy Class Reference
Base::RotationPy Class Reference
The python export class for Rotation.
#include <RotationPy.h>
Public Types
typedef Rotation * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
RotationPy (Rotation *pcObject, PyTypeObject *T=&Type)
additional declarations and methods for the wrapper class
RotationPy (const Rotation &mat, PyTypeObject *T=&Type)
Rotation value () const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * richCompare (PyObject *v, PyObject *w, int op)
callbacks and implementers for the python object number protocol
static PyObject * number_add_handler (PyObject *self, PyObject *other)
callback for the number_add_handler
static PyObject * number_subtract_handler (PyObject *self, PyObject *other)
callback for the number_subtract_handler
static PyObject * number_multiply_handler (PyObject *self, PyObject *other)
callback for the number_multiply_handler
static PyObject * number_divide_handler (PyObject *self, PyObject *other)
callback for the number_divide_handler
static PyObject * number_remainder_handler (PyObject *self, PyObject *other)
callback for the number_remainder_handler
static PyObject * number_divmod_handler (PyObject *self, PyObject *other)
callback for the number_divmod_handler
static PyObject * number_power_handler (PyObject *self, PyObject *other, PyObject *modulo)
callback for the number_power_handler
static PyObject * number_negative_handler (PyObject *self)
callback for the number_negative_handler
static PyObject * number_positive_handler (PyObject *self)
callback for the number_positive_handler
static PyObject * number_absolute_handler (PyObject *self)
callback for the number_absolute_handler
static int number_nonzero_handler (PyObject *self)
callback for the number_nonzero_handler
static PyObject * number_invert_handler (PyObject *self)
callback for the number_invert_handler
static PyObject * number_lshift_handler (PyObject *self, PyObject *other)
callback for the number_lshift_handler
static PyObject * number_rshift_handler (PyObject *self, PyObject *other)
callback for the number_rshift_handler
static PyObject * number_and_handler (PyObject *self, PyObject *other)
callback for the number_and_handler
static PyObject * number_xor_handler (PyObject *self, PyObject *other)
callback for the number_xor_handler
static PyObject * number_or_handler (PyObject *self, PyObject *other)
callback for the number_or_handler
static int number_coerce_handler (PyObject **self, PyObject **other)
callback for the number_coerce_handler
static PyObject * number_int_handler (PyObject *self)
callback for the number_int_handler
static PyObject * number_long_handler (PyObject *self)
callback for the number_long_handler
static PyObject * number_float_handler (PyObject *self)
callback for the number_float_handler
static PyObject * number_oct_handler (PyObject *self)
callback for the number_oct_handler
static PyObject * number_hex_handler (PyObject *self)
callback for the number_hex_handler
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of RotationPy.
static PyMethodDef Methods []
Methods structure of RotationPy.
static PyNumberMethods Number []
static PyTypeObject Type
Type structure of RotationPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~RotationPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
static PyObject * staticCallback_invert (PyObject *self, PyObject *args)
callback for the invert() method
static PyObject * staticCallback_inverted (PyObject *self, PyObject *args)
callback for the inverted() method
static PyObject * staticCallback_isSame (PyObject *self, PyObject *args)
callback for the isSame() method
static PyObject * staticCallback_multiply (PyObject *self, PyObject *args)
callback for the multiply() method
static PyObject * staticCallback_multVec (PyObject *self, PyObject *args)
callback for the multVec() method
static PyObject * staticCallback_slerp (PyObject *self, PyObject *args)
callback for the slerp() method
static PyObject * staticCallback_toEuler (PyObject *self, PyObject *args)
callback for the toEuler() method
static PyObject * staticCallback_toMatrix (PyObject *self, PyObject *args)
callback for the toMatrix() method
static PyObject * staticCallback_isNull (PyObject *self, PyObject *args)
callback for the isNull() method
static PyObject * staticCallback_isIdentity (PyObject *self, PyObject *args)
callback for the isIdentity() method
PyObject * invert (PyObject *args)
implementer for the invert() method
PyObject * inverted (PyObject *args)
implementer for the inverted() method
PyObject * isSame (PyObject *args)
implementer for the isSame() method
PyObject * multiply (PyObject *args)
implementer for the multiply() method
PyObject * multVec (PyObject *args)
implementer for the multVec() method
PyObject * slerp (PyObject *args)
implementer for the slerp() method
PyObject * toEuler (PyObject *args)
implementer for the toEuler() method
PyObject * toMatrix (PyObject *args)
implementer for the toMatrix() method
PyObject * isNull (PyObject *args)
implementer for the isNull() method
PyObject * isIdentity (PyObject *args)
implementer for the isIdentity() method
callbacks and implementers for the python object attributes
static PyObject * staticCallback_getQ (PyObject *self, void *closure)
getter callback for the Q attribute
static int staticCallback_setQ (PyObject *self, PyObject *value, void *closure)
setter callback for the Q attribute
static PyObject * staticCallback_getAxis (PyObject *self, void *closure)
getter callback for the Axis attribute
static int staticCallback_setAxis (PyObject *self, PyObject *value, void *closure)
setter callback for the Axis attribute
static PyObject * staticCallback_getRawAxis (PyObject *self, void *closure)
getter callback for the RawAxis attribute
static int staticCallback_setRawAxis (PyObject *self, PyObject *value, void *closure)
setter callback for the RawAxis attribute
static PyObject * staticCallback_getAngle (PyObject *self, void *closure)
getter callback for the Angle attribute
static int staticCallback_setAngle (PyObject *self, PyObject *value, void *closure)
setter callback for the Angle attribute
Py::Tuple getQ (void) const
getter for the Q attribute
void setQ (Py::Tuple arg)
setter for the Q attribute
Py::Object getAxis (void) const
getter for the Axis attribute
void setAxis (Py::Object arg)
setter for the Axis attribute
Py::Object getRawAxis (void) const
getter for the RawAxis attribute
Py::Float getAngle (void) const
getter for the Angle attribute
void setAngle (Py::Float arg)
setter for the Angle attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Rotation * getRotationPtr (void) const
getter for the object handled by this class
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Rotation.
Member Typedef Documentation
PointerType
typedef Rotation* Base::RotationPy::PointerType
Constructor & Destructor Documentation
~RotationPy()
RotationPy::~RotationPy () protected
RotationPy() [1/2]
RotationPy::RotationPy (Rotation * pcObject, PyTypeObject * T = &Type)
Referenced by inverted(), multiply(), number_multiply_handler(), number_power_handler(), PyMake(), and slerp().
RotationPy() [2/2]
Base::RotationPy::RotationPy (const Rotation & mat, PyTypeObject * T = &Type)
Member Function Documentation
getAngle()
Py::Float RotationPy::getAngle (void) const
getter for the Angle attribute
References DraftVecUtils::angle(), getRotationPtr(), and Base::Rotation::getValue().
Referenced by PathScripts.PathDressupDogbone.Chord::getAngleXY(), draftguitools.gui_trackers.arcTracker::setEndPoint(), draftguitools.gui_trackers.arcTracker::setStartPoint(), and staticCallback_getAngle().
getAxis()
Py::Object RotationPy::getAxis (void) const
getter for the Axis attribute
References DraftVecUtils::angle(), getRotationPtr(), and Base::Rotation::getValue().
Referenced by staticCallback_getAxis().
getCustomAttributes()
PyObject * RotationPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
References getRotationPtr(), Base::Rotation::getValue(), and Base::Rotation::getYawPitchRoll().
getQ()
Py::Tuple RotationPy::getQ (void) const
getter for the Q attribute
References getRotationPtr(), and Base::Rotation::getValue().
Referenced by staticCallback_getQ().
getRawAxis()
Py::Object RotationPy::getRawAxis (void) const
getter for the RawAxis attribute
References DraftVecUtils::angle(), Base::Rotation::getRawValue(), and getRotationPtr().
Referenced by staticCallback_getRawAxis().
getRotationPtr()
Rotation * RotationPy::getRotationPtr (void) const
getter for the object handled by this class
Referenced by getAngle(), getAxis(), getCustomAttributes(), getQ(), getRawAxis(), invert(), inverted(), isIdentity(), isNull(), isSame(), multiply(), multVec(), PyInit(), richCompare(), setAngle(), setAxis(), setCustomAttributes(), setQ(), slerp(), toEuler(), and toMatrix().
GetType()
virtual PyTypeObject* Base::RotationPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
invert()
PyObject * RotationPy::invert (PyObject * args)
implementer for the invert() method
References getRotationPtr(), and Base::Rotation::invert().
Referenced by PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart(), and staticCallback_invert().
inverted()
PyObject * RotationPy::inverted (PyObject * args)
implementer for the inverted() method
References getRotationPtr(), Base::Rotation::inverse(), and RotationPy().
Referenced by staticCallback_inverted().
isIdentity()
PyObject * RotationPy::isIdentity (PyObject * args)
implementer for the isIdentity() method
References getRotationPtr(), and Base::Rotation::isIdentity().
Referenced by ArchComponent.Component::applyShape(), ArchComponent.Component::getExtrusionData(), ArchComponent.Component::processSubShapes(), and staticCallback_isIdentity().
isNull()
PyObject * RotationPy::isNull (PyObject * args)
implementer for the isNull() method
References getRotationPtr(), and Base::Rotation::isNull().
Referenced by staticCallback_isNull().
isSame()
PyObject * RotationPy::isSame (PyObject * args)
implementer for the isSame() method
References getRotationPtr(), Base::Rotation::isSame(), and Type.
Referenced by staticCallback_isSame().
multiply()
PyObject * RotationPy::multiply (PyObject * args)
implementer for the multiply() method
References getRotationPtr(), RotationPy(), and Type.
Referenced by PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart(), and staticCallback_multiply().
multVec()
PyObject * RotationPy::multVec (PyObject * args)
implementer for the multVec() method
References getRotationPtr(), Base::Rotation::multVec(), Base::VectorPy::Type, value(), and draftgeoutils.general::vec().
Referenced by staticCallback_multVec().
number_absolute_handler()
PyObject * RotationPy::number_absolute_handler (PyObject * self) static
callback for the number_absolute_handler
number_add_handler()
PyObject * RotationPy::number_add_handler (PyObject * self, PyObject * other) static
callback for the number_add_handler
number_and_handler()
PyObject * RotationPy::number_and_handler (PyObject * self, PyObject * other) static
callback for the number_and_handler
number_coerce_handler()
int RotationPy::number_coerce_handler (PyObject ** self, PyObject ** other) static
callback for the number_coerce_handler
number_divide_handler()
PyObject * RotationPy::number_divide_handler (PyObject * self, PyObject * other) static
callback for the number_divide_handler
number_divmod_handler()
PyObject * RotationPy::number_divmod_handler (PyObject * self, PyObject * other) static
callback for the number_divmod_handler
number_float_handler()
PyObject * RotationPy::number_float_handler (PyObject * self) static
callback for the number_float_handler
number_hex_handler()
PyObject * RotationPy::number_hex_handler (PyObject * self) static
callback for the number_hex_handler
number_int_handler()
PyObject * RotationPy::number_int_handler (PyObject * self) static
callback for the number_int_handler
number_invert_handler()
PyObject * RotationPy::number_invert_handler (PyObject * self) static
callback for the number_invert_handler
number_long_handler()
PyObject * RotationPy::number_long_handler (PyObject * self) static
callback for the number_long_handler
number_lshift_handler()
PyObject * RotationPy::number_lshift_handler (PyObject * self, PyObject * other) static
callback for the number_lshift_handler
number_multiply_handler()
PyObject * RotationPy::number_multiply_handler (PyObject * self, PyObject * other) static
callback for the number_multiply_handler
References RotationPy(), Base::MatrixPy::Type, Base::PlacementPy::Type, Type, Base::VectorPy::Type, value(), and Base::VectorPy::value().
number_negative_handler()
PyObject * RotationPy::number_negative_handler (PyObject * self) static
callback for the number_negative_handler
number_nonzero_handler()
int RotationPy::number_nonzero_handler (PyObject * self) static
callback for the number_nonzero_handler
number_oct_handler()
PyObject * RotationPy::number_oct_handler (PyObject * self) static
callback for the number_oct_handler
number_or_handler()
PyObject * RotationPy::number_or_handler (PyObject * self, PyObject * other) static
callback for the number_or_handler
number_positive_handler()
PyObject * RotationPy::number_positive_handler (PyObject * self) static
callback for the number_positive_handler
number_power_handler()
PyObject * RotationPy::number_power_handler (PyObject * self, PyObject * other, PyObject * modulo) static
callback for the number_power_handler
References RotationPy(), Type, and value().
number_remainder_handler()
PyObject * RotationPy::number_remainder_handler (PyObject * self, PyObject * other) static
callback for the number_remainder_handler
number_rshift_handler()
PyObject * RotationPy::number_rshift_handler (PyObject * self, PyObject * other) static
callback for the number_rshift_handler
number_subtract_handler()
PyObject * RotationPy::number_subtract_handler (PyObject * self, PyObject * other) static
callback for the number_subtract_handler
number_xor_handler()
PyObject * RotationPy::number_xor_handler (PyObject * self, PyObject * other) static
callback for the number_xor_handler
PyInit()
int RotationPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
References DraftVecUtils::angle(), Base::BaseExceptionFreeCADError, getRotationPtr(), Base::Rotation::getValue(), Base::Rotation::makeRotationByAxes(), Base::Rotation::setValue(), Base::Rotation::setYawPitchRoll(), Base::MatrixPy::Type, Type, Base::VectorPy::Type, draftgeoutils.general::v1(), and value().
PyMake()
PyObject * RotationPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References RotationPy().
representation()
std::string RotationPy::representation (void) const
References Base::Rotation::getValue().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
richCompare()
PyObject * RotationPy::richCompare (PyObject * v, PyObject * w, int op) static
References getRotationPtr(), and Type.
setAngle()
void RotationPy::setAngle (Py::Float arg)
setter for the Angle attribute
References DraftVecUtils::angle(), Base::Rotation::getRawValue(), getRotationPtr(), and Base::Rotation::setValue().
Referenced by staticCallback_setAngle().
setAxis()
void RotationPy::setAxis (Py::Object arg)
setter for the Axis attribute
References DraftVecUtils::angle(), getRotationPtr(), Base::Rotation::getValue(), and Base::Rotation::setValue().
Referenced by staticCallback_setAxis().
setCustomAttributes()
int RotationPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
References getRotationPtr(), Base::Rotation::getYawPitchRoll(), Base::Rotation::setValue(), Base::Rotation::setYawPitchRoll(), Base::MatrixPy::Type, and Base::VectorPy::Type.
setQ()
void RotationPy::setQ (Py::Tuple arg)
setter for the Q attribute
References getRotationPtr(), and Base::Rotation::setValue().
Referenced by staticCallback_setQ().
slerp()
PyObject * RotationPy::slerp (PyObject * args)
implementer for the slerp() method
References getRotationPtr(), RotationPy(), Base::Rotation::slerp(), and Type.
Referenced by staticCallback_slerp().
staticCallback_getAngle()
PyObject * RotationPy::staticCallback_getAngle (PyObject * self, void * closure) static
getter callback for the Angle attribute
References Base::BaseExceptionFreeCADError, getAngle(), and Base::PyObjectBase::isValid().
staticCallback_getAxis()
PyObject * RotationPy::staticCallback_getAxis (PyObject * self, void * closure) static
getter callback for the Axis attribute
References Base::BaseExceptionFreeCADError, getAxis(), and Base::PyObjectBase::isValid().
staticCallback_getQ()
PyObject * RotationPy::staticCallback_getQ (PyObject * self, void * closure) static
getter callback for the Q attribute
References Base::BaseExceptionFreeCADError, getQ(), and Base::PyObjectBase::isValid().
staticCallback_getRawAxis()
PyObject * RotationPy::staticCallback_getRawAxis (PyObject * self, void * closure) static
getter callback for the RawAxis attribute
References Base::BaseExceptionFreeCADError, getRawAxis(), and Base::PyObjectBase::isValid().
staticCallback_invert()
PyObject * RotationPy::staticCallback_invert (PyObject * self, PyObject * args) static
callback for the invert() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, invert(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_inverted()
PyObject * RotationPy::staticCallback_inverted (PyObject * self, PyObject * args) static
callback for the inverted() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, inverted(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_isIdentity()
PyObject * RotationPy::staticCallback_isIdentity (PyObject * self, PyObject * args) static
callback for the isIdentity() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isIdentity(), and Base::PyObjectBase::isValid().
staticCallback_isNull()
PyObject * RotationPy::staticCallback_isNull (PyObject * self, PyObject * args) static
callback for the isNull() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isNull(), and Base::PyObjectBase::isValid().
staticCallback_isSame()
PyObject * RotationPy::staticCallback_isSame (PyObject * self, PyObject * args) static
callback for the isSame() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), isSame(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::startNotify().
staticCallback_multiply()
PyObject * RotationPy::staticCallback_multiply (PyObject * self, PyObject * args) static
callback for the multiply() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and multiply().
staticCallback_multVec()
PyObject * RotationPy::staticCallback_multVec (PyObject * self, PyObject * args) static
callback for the multVec() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and multVec().
staticCallback_setAngle()
int RotationPy::staticCallback_setAngle (PyObject * self, PyObject * value, void * closure) static
setter callback for the Angle attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setAngle().
staticCallback_setAxis()
int RotationPy::staticCallback_setAxis (PyObject * self, PyObject * value, void * closure) static
setter callback for the Axis attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setAxis().
staticCallback_setQ()
int RotationPy::staticCallback_setQ (PyObject * self, PyObject * value, void * closure) static
setter callback for the Q attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), and setQ().
staticCallback_setRawAxis()
int RotationPy::staticCallback_setRawAxis (PyObject * self, PyObject * value, void * closure) static
setter callback for the RawAxis attribute
References Base::PyObjectBase::isValid().
staticCallback_slerp()
PyObject * RotationPy::staticCallback_slerp (PyObject * self, PyObject * args) static
callback for the slerp() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and slerp().
staticCallback_toEuler()
PyObject * RotationPy::staticCallback_toEuler (PyObject * self, PyObject * args) static
callback for the toEuler() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and toEuler().
staticCallback_toMatrix()
PyObject * RotationPy::staticCallback_toMatrix (PyObject * self, PyObject * args) static
callback for the toMatrix() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), and toMatrix().
toEuler()
PyObject * RotationPy::toEuler (PyObject * args)
implementer for the toEuler() method
References getRotationPtr(), and Base::Rotation::getYawPitchRoll().
Referenced by staticCallback_toEuler().
toMatrix()
PyObject * RotationPy::toMatrix (PyObject * args)
implementer for the toMatrix() method
References getRotationPtr(), and Base::Rotation::getValue().
Referenced by staticCallback_toMatrix().
value()
Rotation Base::RotationPy::value () const
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), multVec(), number_multiply_handler(), number_power_handler(), and PyInit().
Member Data Documentation
GetterSetter
PyGetSetDef RotationPy::GetterSetter static
Initial value:
= {
    {"Q",
        (getter) staticCallback_getQ,
        (setter) staticCallback_setQ,
        "The rotation elements (as quaternion)",
        NULL
    },
    {"Axis",
        (getter) staticCallback_getAxis,
        (setter) staticCallback_setAxis,
        "The rotation axis of the quaternion",
        NULL
    },
    {"RawAxis",
        (getter) staticCallback_getRawAxis,
        (setter) staticCallback_setRawAxis,
        "The rotation axis without normalization",
        NULL
    },
    {"Angle",
        (getter) staticCallback_getAngle,
        (setter) staticCallback_setAngle,
        "The rotation angle of the quaternion",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of RotationPy.
Methods
PyMethodDef RotationPy::Methods static
Methods structure of RotationPy.
Number
PyNumberMethods RotationPy::Number static
Type
PyTypeObject RotationPy::Type static
Type structure of RotationPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), App::FunctionExpression::evaluate(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), isSame(), multiply(), Base::MatrixPy::number_multiply_handler(), Base::PlacementPy::number_multiply_handler(), number_multiply_handler(), number_power_handler(), Base::PlacementPy::PyInit(), PyInit(), richCompare(), draftobjects.layer.Layer::set_properties(), Gui::View3DInventorPy::setCameraOrientation(), ArchReference.ArchReference::setProperties(), slerp(), and Base::CoordinateSystemPy::transform().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Base/RotationPy.h
Sources/FreeCAD/src/Base/RotationPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Base/RotationPy.cpp