FreeCAD: Part::BSplineCurve2dPy Class Reference
Part::BSplineCurve2dPy Class Reference
The python export class for Geom2dBSplineCurve.
#include <BSplineCurve2dPy.h>
Public Types
typedef Geom2dBSplineCurve * PointerType
Public Types inherited from Part::Curve2dPy
typedef Geom2dCurve * PointerType
Public Types inherited from Part::Geometry2dPy
typedef Geometry2d * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
BSplineCurve2dPy (Geom2dBSplineCurve *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Part::Curve2dPy
Curve2dPy (Geom2dCurve *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * reverse (PyObject *args)
implementer for the reverse() method
PyObject * toShape (PyObject *args)
implementer for the toShape() method
PyObject * discretize (PyObject *args, PyObject *kwd)
implementer for the discretize() method
PyObject * length (PyObject *args)
implementer for the length() method
PyObject * parameterAtDistance (PyObject *args)
implementer for the parameterAtDistance() method
PyObject * value (PyObject *args)
implementer for the value() method
PyObject * tangent (PyObject *args)
implementer for the tangent() method
PyObject * parameter (PyObject *args)
implementer for the parameter() method
PyObject * normal (PyObject *args)
implementer for the normal() method
PyObject * curvature (PyObject *args)
implementer for the curvature() method
PyObject * centerOfCurvature (PyObject *args)
implementer for the centerOfCurvature() method
PyObject * intersectCC (PyObject *args)
implementer for the intersectCC() method
PyObject * toBSpline (PyObject *args)
implementer for the toBSpline() method
PyObject * approximateBSpline (PyObject *args)
implementer for the approximateBSpline() method
Py::String getContinuity (void) const
getter for the Continuity attribute
Py::Boolean getClosed (void) const
getter for the Closed attribute
Py::Boolean getPeriodic (void) const
getter for the Periodic attribute
Py::Float getFirstParameter (void) const
getter for the FirstParameter attribute
Py::Float getLastParameter (void) const
getter for the LastParameter attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geom2dCurve * getGeom2dCurvePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Part::Geometry2dPy
Geometry2dPy (Geometry2d *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geometry2d * getGeometry2dPtr (void) const
getter for the object handled by this class
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * copy (PyObject *args)
implementer for the copy() method
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::Curve2dPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_reverse (PyObject *self, PyObject *args)
callback for the reverse() method
static PyObject * staticCallback_toShape (PyObject *self, PyObject *args)
callback for the toShape() method
static PyObject * staticCallback_discretize (PyObject *self, PyObject *args, PyObject *kwd)
callback for the discretize() method
static PyObject * staticCallback_length (PyObject *self, PyObject *args)
callback for the length() method
static PyObject * staticCallback_parameterAtDistance (PyObject *self, PyObject *args)
callback for the parameterAtDistance() method
static PyObject * staticCallback_value (PyObject *self, PyObject *args)
callback for the value() method
static PyObject * staticCallback_tangent (PyObject *self, PyObject *args)
callback for the tangent() method
static PyObject * staticCallback_parameter (PyObject *self, PyObject *args)
callback for the parameter() method
static PyObject * staticCallback_normal (PyObject *self, PyObject *args)
callback for the normal() method
static PyObject * staticCallback_curvature (PyObject *self, PyObject *args)
callback for the curvature() method
static PyObject * staticCallback_centerOfCurvature (PyObject *self, PyObject *args)
callback for the centerOfCurvature() method
static PyObject * staticCallback_intersectCC (PyObject *self, PyObject *args)
callback for the intersectCC() method
static PyObject * staticCallback_toBSpline (PyObject *self, PyObject *args)
callback for the toBSpline() method
static PyObject * staticCallback_approximateBSpline (PyObject *self, PyObject *args)
callback for the approximateBSpline() method
static PyObject * staticCallback_getContinuity (PyObject *self, void *closure)
getter callback for the Continuity attribute
static int staticCallback_setContinuity (PyObject *self, PyObject *value, void *closure)
setter callback for the Continuity attribute
static PyObject * staticCallback_getClosed (PyObject *self, void *closure)
getter callback for the Closed attribute
static int staticCallback_setClosed (PyObject *self, PyObject *value, void *closure)
setter callback for the Closed attribute
static PyObject * staticCallback_getPeriodic (PyObject *self, void *closure)
getter callback for the Periodic attribute
static int staticCallback_setPeriodic (PyObject *self, PyObject *value, void *closure)
setter callback for the Periodic attribute
static PyObject * staticCallback_getFirstParameter (PyObject *self, void *closure)
getter callback for the FirstParameter attribute
static int staticCallback_setFirstParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the FirstParameter attribute
static PyObject * staticCallback_getLastParameter (PyObject *self, void *closure)
getter callback for the LastParameter attribute
static int staticCallback_setLastParameter (PyObject *self, PyObject *value, void *closure)
setter callback for the LastParameter attribute
Static Public Member Functions inherited from Part::Geometry2dPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of BSplineCurve2dPy.
static PyMethodDef Methods []
Methods structure of BSplineCurve2dPy.
static PyTypeObject Type
Type structure of BSplineCurve2dPy.
Static Public Attributes inherited from Part::Curve2dPy
static PyGetSetDef GetterSetter []
Attribute structure of Curve2dPy.
static PyMethodDef Methods []
Methods structure of Curve2dPy.
static PyTypeObject Type
Type structure of Curve2dPy.
Static Public Attributes inherited from Part::Geometry2dPy
static PyGetSetDef GetterSetter []
Attribute structure of Geometry2dPy.
static PyMethodDef Methods []
Methods structure of Geometry2dPy.
static PyTypeObject Type
Type structure of Geometry2dPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~BSplineCurve2dPy ()
Protected Member Functions inherited from Part::Curve2dPy
~Curve2dPy ()
Protected Member Functions inherited from Part::Geometry2dPy
~Geometry2dPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * isRational (PyObject *args)
implementer for the isRational() method
PyObject * isPeriodic (PyObject *args)
implementer for the isPeriodic() method
PyObject * isClosed (PyObject *args)
implementer for the isClosed() method
PyObject * increaseDegree (PyObject *args)
implementer for the increaseDegree() method
PyObject * increaseMultiplicity (PyObject *args)
implementer for the increaseMultiplicity() method
PyObject * incrementMultiplicity (PyObject *args)
implementer for the incrementMultiplicity() method
PyObject * insertKnot (PyObject *args)
implementer for the insertKnot() method
PyObject * insertKnots (PyObject *args)
implementer for the insertKnots() method
PyObject * removeKnot (PyObject *args)
implementer for the removeKnot() method
PyObject * segment (PyObject *args)
implementer for the segment() method
PyObject * setKnot (PyObject *args)
implementer for the setKnot() method
PyObject * getKnot (PyObject *args)
implementer for the getKnot() method
PyObject * setKnots (PyObject *args)
implementer for the setKnots() method
PyObject * getKnots (PyObject *args)
implementer for the getKnots() method
PyObject * setPole (PyObject *args)
implementer for the setPole() method
PyObject * getPole (PyObject *args)
implementer for the getPole() method
PyObject * getPoles (PyObject *args)
implementer for the getPoles() method
PyObject * setWeight (PyObject *args)
implementer for the setWeight() method
PyObject * getWeight (PyObject *args)
implementer for the getWeight() method
PyObject * getWeights (PyObject *args)
implementer for the getWeights() method
PyObject * getPolesAndWeights (PyObject *args)
implementer for the getPolesAndWeights() method
PyObject * getResolution (PyObject *args)
implementer for the getResolution() method
PyObject * movePoint (PyObject *args)
implementer for the movePoint() method
PyObject * setNotPeriodic (PyObject *args)
implementer for the setNotPeriodic() method
PyObject * setPeriodic (PyObject *args)
implementer for the setPeriodic() method
PyObject * setOrigin (PyObject *args)
implementer for the setOrigin() method
PyObject * getMultiplicity (PyObject *args)
implementer for the getMultiplicity() method
PyObject * getMultiplicities (PyObject *args)
implementer for the getMultiplicities() method
PyObject * approximate (PyObject *args, PyObject *kwd)
implementer for the approximate() method
PyObject * getCardinalSplineTangents (PyObject *args, PyObject *kwd)
implementer for the getCardinalSplineTangents() method
PyObject * interpolate (PyObject *args, PyObject *kwd)
implementer for the interpolate() method
PyObject * buildFromPoles (PyObject *args)
implementer for the buildFromPoles() method
PyObject * buildFromPolesMultsKnots (PyObject *args, PyObject *kwd)
implementer for the buildFromPolesMultsKnots() method
PyObject * toBezier (PyObject *args)
implementer for the toBezier() method
PyObject * toBiArcs (PyObject *args)
implementer for the toBiArcs() method
PyObject * join (PyObject *args)
implementer for the join() method
PyObject * makeC1Continuous (PyObject *args)
implementer for the makeC1Continuous() method
static PyObject * staticCallback_isRational (PyObject *self, PyObject *args)
callback for the isRational() method
static PyObject * staticCallback_isPeriodic (PyObject *self, PyObject *args)
callback for the isPeriodic() method
static PyObject * staticCallback_isClosed (PyObject *self, PyObject *args)
callback for the isClosed() method
static PyObject * staticCallback_increaseDegree (PyObject *self, PyObject *args)
callback for the increaseDegree() method
static PyObject * staticCallback_increaseMultiplicity (PyObject *self, PyObject *args)
callback for the increaseMultiplicity() method
static PyObject * staticCallback_incrementMultiplicity (PyObject *self, PyObject *args)
callback for the incrementMultiplicity() method
static PyObject * staticCallback_insertKnot (PyObject *self, PyObject *args)
callback for the insertKnot() method
static PyObject * staticCallback_insertKnots (PyObject *self, PyObject *args)
callback for the insertKnots() method
static PyObject * staticCallback_removeKnot (PyObject *self, PyObject *args)
callback for the removeKnot() method
static PyObject * staticCallback_segment (PyObject *self, PyObject *args)
callback for the segment() method
static PyObject * staticCallback_setKnot (PyObject *self, PyObject *args)
callback for the setKnot() method
static PyObject * staticCallback_getKnot (PyObject *self, PyObject *args)
callback for the getKnot() method
static PyObject * staticCallback_setKnots (PyObject *self, PyObject *args)
callback for the setKnots() method
static PyObject * staticCallback_getKnots (PyObject *self, PyObject *args)
callback for the getKnots() method
static PyObject * staticCallback_setPole (PyObject *self, PyObject *args)
callback for the setPole() method
static PyObject * staticCallback_getPole (PyObject *self, PyObject *args)
callback for the getPole() method
static PyObject * staticCallback_getPoles (PyObject *self, PyObject *args)
callback for the getPoles() method
static PyObject * staticCallback_setWeight (PyObject *self, PyObject *args)
callback for the setWeight() method
static PyObject * staticCallback_getWeight (PyObject *self, PyObject *args)
callback for the getWeight() method
static PyObject * staticCallback_getWeights (PyObject *self, PyObject *args)
callback for the getWeights() method
static PyObject * staticCallback_getPolesAndWeights (PyObject *self, PyObject *args)
callback for the getPolesAndWeights() method
static PyObject * staticCallback_getResolution (PyObject *self, PyObject *args)
callback for the getResolution() method
static PyObject * staticCallback_movePoint (PyObject *self, PyObject *args)
callback for the movePoint() method
static PyObject * staticCallback_setNotPeriodic (PyObject *self, PyObject *args)
callback for the setNotPeriodic() method
static PyObject * staticCallback_setPeriodic (PyObject *self, PyObject *args)
callback for the setPeriodic() method
static PyObject * staticCallback_setOrigin (PyObject *self, PyObject *args)
callback for the setOrigin() method
static PyObject * staticCallback_getMultiplicity (PyObject *self, PyObject *args)
callback for the getMultiplicity() method
static PyObject * staticCallback_getMultiplicities (PyObject *self, PyObject *args)
callback for the getMultiplicities() method
static PyObject * staticCallback_approximate (PyObject *self, PyObject *args, PyObject *kwd)
callback for the approximate() method
static PyObject * staticCallback_getCardinalSplineTangents (PyObject *self, PyObject *args, PyObject *kwd)
callback for the getCardinalSplineTangents() method
static PyObject * staticCallback_interpolate (PyObject *self, PyObject *args, PyObject *kwd)
callback for the interpolate() method
static PyObject * staticCallback_buildFromPoles (PyObject *self, PyObject *args)
callback for the buildFromPoles() method
static PyObject * staticCallback_buildFromPolesMultsKnots (PyObject *self, PyObject *args, PyObject *kwd)
callback for the buildFromPolesMultsKnots() method
static PyObject * staticCallback_toBezier (PyObject *self, PyObject *args)
callback for the toBezier() method
static PyObject * staticCallback_toBiArcs (PyObject *self, PyObject *args)
callback for the toBiArcs() method
static PyObject * staticCallback_join (PyObject *self, PyObject *args)
callback for the join() method
static PyObject * staticCallback_makeC1Continuous (PyObject *self, PyObject *args)
callback for the makeC1Continuous() method
callbacks and implementers for the python object attributes
Py::Long getDegree (void) const
getter for the Degree attribute
Py::Long getMaxDegree (void) const
getter for the MaxDegree attribute
Py::Long getNbPoles (void) const
getter for the NbPoles attribute
Py::Long getNbKnots (void) const
getter for the NbKnots attribute
Py::Object getStartPoint (void) const
getter for the StartPoint attribute
Py::Object getEndPoint (void) const
getter for the EndPoint attribute
Py::Object getFirstUKnotIndex (void) const
getter for the FirstUKnotIndex attribute
Py::Object getLastUKnotIndex (void) const
getter for the LastUKnotIndex attribute
Py::List getKnotSequence (void) const
getter for the KnotSequence attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geom2dBSplineCurve * getGeom2dBSplineCurvePtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getDegree (PyObject *self, void *closure)
getter callback for the Degree attribute
static int staticCallback_setDegree (PyObject *self, PyObject *value, void *closure)
setter callback for the Degree attribute
static PyObject * staticCallback_getMaxDegree (PyObject *self, void *closure)
getter callback for the MaxDegree attribute
static int staticCallback_setMaxDegree (PyObject *self, PyObject *value, void *closure)
setter callback for the MaxDegree attribute
static PyObject * staticCallback_getNbPoles (PyObject *self, void *closure)
getter callback for the NbPoles attribute
static int staticCallback_setNbPoles (PyObject *self, PyObject *value, void *closure)
setter callback for the NbPoles attribute
static PyObject * staticCallback_getNbKnots (PyObject *self, void *closure)
getter callback for the NbKnots attribute
static int staticCallback_setNbKnots (PyObject *self, PyObject *value, void *closure)
setter callback for the NbKnots attribute
static PyObject * staticCallback_getStartPoint (PyObject *self, void *closure)
getter callback for the StartPoint attribute
static int staticCallback_setStartPoint (PyObject *self, PyObject *value, void *closure)
setter callback for the StartPoint attribute
static PyObject * staticCallback_getEndPoint (PyObject *self, void *closure)
getter callback for the EndPoint attribute
static int staticCallback_setEndPoint (PyObject *self, PyObject *value, void *closure)
setter callback for the EndPoint attribute
static PyObject * staticCallback_getFirstUKnotIndex (PyObject *self, void *closure)
getter callback for the FirstUKnotIndex attribute
static int staticCallback_setFirstUKnotIndex (PyObject *self, PyObject *value, void *closure)
setter callback for the FirstUKnotIndex attribute
static PyObject * staticCallback_getLastUKnotIndex (PyObject *self, void *closure)
getter callback for the LastUKnotIndex attribute
static int staticCallback_setLastUKnotIndex (PyObject *self, PyObject *value, void *closure)
setter callback for the LastUKnotIndex attribute
static PyObject * staticCallback_getKnotSequence (PyObject *self, void *closure)
getter callback for the KnotSequence attribute
static int staticCallback_setKnotSequence (PyObject *self, PyObject *value, void *closure)
setter callback for the KnotSequence attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Geom2dBSplineCurve.
Member Typedef Documentation
PointerType
typedef Geom2dBSplineCurve* Part::BSplineCurve2dPy::PointerType
Constructor & Destructor Documentation
~BSplineCurve2dPy()
BSplineCurve2dPy::~BSplineCurve2dPy () protected
BSplineCurve2dPy()
BSplineCurve2dPy::BSplineCurve2dPy (Geom2dBSplineCurve * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
approximate()
PyObject * BSplineCurve2dPy::approximate (PyObject * args, PyObject * kwd)
implementer for the approximate() method
References getGeom2dBSplineCurvePtr(), Part::PartExceptionOCCError, Part::Geom2dBSplineCurve::setHandle(), and draftgeoutils.general::vec().
Referenced by staticCallback_approximate().
buildFromPoles()
PyObject * BSplineCurve2dPy::buildFromPoles (PyObject * args)
implementer for the buildFromPoles() method
References getGeom2dBSplineCurvePtr(), interpolate(), Part::PartExceptionOCCError, Part::Geom2dBSplineCurve::setHandle(), Base::Vector2d::x, and Base::Vector2d::y.
Referenced by staticCallback_buildFromPoles().
buildFromPolesMultsKnots()
PyObject * BSplineCurve2dPy::buildFromPolesMultsKnots (PyObject * args, PyObject * kwd)
implementer for the buildFromPolesMultsKnots() method
References getGeom2dBSplineCurvePtr(), Part::PartExceptionOCCError, Part::Geom2dBSplineCurve::setHandle(), Base::Vector2d::x, and Base::Vector2d::y.
Referenced by staticCallback_buildFromPolesMultsKnots().
getCardinalSplineTangents()
PyObject * BSplineCurve2dPy::getCardinalSplineTangents (PyObject * args, PyObject * kwd)
implementer for the getCardinalSplineTangents() method
References getGeom2dBSplineCurvePtr(), Part::Curve2dPy::parameter(), draftgeoutils.general::vec(), Base::Vector2d::x, and Base::Vector2d::y.
Referenced by staticCallback_getCardinalSplineTangents().
getCustomAttributes()
PyObject * BSplineCurve2dPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getDegree()
Py::Long BSplineCurve2dPy::getDegree (void) const
getter for the Degree attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getDegree().
getEndPoint()
Py::Object BSplineCurve2dPy::getEndPoint (void) const
getter for the EndPoint attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getEndPoint().
getFirstUKnotIndex()
Py::Object BSplineCurve2dPy::getFirstUKnotIndex (void) const
getter for the FirstUKnotIndex attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getFirstUKnotIndex().
getGeom2dBSplineCurvePtr()
Geom2dBSplineCurve * BSplineCurve2dPy::getGeom2dBSplineCurvePtr (void) const
getter for the object handled by this class
Referenced by approximate(), buildFromPoles(), buildFromPolesMultsKnots(), getCardinalSplineTangents(), interpolate(), join(), makeC1Continuous(), toBezier(), and toBiArcs().
getKnot()
PyObject * BSplineCurve2dPy::getKnot (PyObject * args)
implementer for the getKnot() method
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getKnot().
getKnots()
PyObject * BSplineCurve2dPy::getKnots (PyObject * args)
implementer for the getKnots() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getKnots().
getKnotSequence()
Py::List BSplineCurve2dPy::getKnotSequence (void) const
getter for the KnotSequence attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getKnotSequence().
getLastUKnotIndex()
Py::Object BSplineCurve2dPy::getLastUKnotIndex (void) const
getter for the LastUKnotIndex attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getLastUKnotIndex().
getMaxDegree()
Py::Long BSplineCurve2dPy::getMaxDegree (void) const
getter for the MaxDegree attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getMaxDegree().
getMultiplicities()
PyObject * BSplineCurve2dPy::getMultiplicities (PyObject * args)
implementer for the getMultiplicities() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getMultiplicities().
getMultiplicity()
PyObject * BSplineCurve2dPy::getMultiplicity (PyObject * args)
implementer for the getMultiplicity() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getMultiplicity().
getNbKnots()
Py::Long BSplineCurve2dPy::getNbKnots (void) const
getter for the NbKnots attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getNbKnots().
getNbPoles()
Py::Long BSplineCurve2dPy::getNbPoles (void) const
getter for the NbPoles attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getNbPoles().
getPole()
PyObject * BSplineCurve2dPy::getPole (PyObject * args)
implementer for the getPole() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getPole().
getPoles()
PyObject * BSplineCurve2dPy::getPoles (PyObject * args)
implementer for the getPoles() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getPoles().
getPolesAndWeights()
PyObject * BSplineCurve2dPy::getPolesAndWeights (PyObject * args)
implementer for the getPolesAndWeights() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getPolesAndWeights().
getResolution()
PyObject * BSplineCurve2dPy::getResolution (PyObject * args)
implementer for the getResolution() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getResolution().
getStartPoint()
Py::Object BSplineCurve2dPy::getStartPoint (void) const
getter for the StartPoint attribute
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_getStartPoint().
GetType()
virtual PyTypeObject* Part::BSplineCurve2dPy::GetType (void) virtual
Reimplemented from Part::Curve2dPy.
getWeight()
PyObject * BSplineCurve2dPy::getWeight (PyObject * args)
implementer for the getWeight() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getWeight().
getWeights()
PyObject * BSplineCurve2dPy::getWeights (PyObject * args)
implementer for the getWeights() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_getWeights().
increaseDegree()
PyObject * BSplineCurve2dPy::increaseDegree (PyObject * args)
implementer for the increaseDegree() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_increaseDegree().
increaseMultiplicity()
PyObject * BSplineCurve2dPy::increaseMultiplicity (PyObject * args)
implementer for the increaseMultiplicity() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_increaseMultiplicity().
incrementMultiplicity()
PyObject * BSplineCurve2dPy::incrementMultiplicity (PyObject * args)
implementer for the incrementMultiplicity() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_incrementMultiplicity().
insertKnot()
PyObject * BSplineCurve2dPy::insertKnot (PyObject * args)
implementer for the insertKnot() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_insertKnot().
insertKnots()
PyObject * BSplineCurve2dPy::insertKnots (PyObject * args)
implementer for the insertKnots() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_insertKnots().
interpolate()
PyObject * BSplineCurve2dPy::interpolate (PyObject * args, PyObject * kwd)
implementer for the interpolate() method
References getGeom2dBSplineCurvePtr(), Part::PartExceptionOCCError, Part::Geom2dBSplineCurve::setHandle(), draftgeoutils.general::vec(), Base::Vector2d::x, and Base::Vector2d::y.
Referenced by buildFromPoles(), and staticCallback_interpolate().
isClosed()
PyObject * BSplineCurve2dPy::isClosed (PyObject * args)
implementer for the isClosed() method
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_isClosed().
isPeriodic()
PyObject * BSplineCurve2dPy::isPeriodic (PyObject * args)
implementer for the isPeriodic() method
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_isPeriodic().
isRational()
PyObject * BSplineCurve2dPy::isRational (PyObject * args)
implementer for the isRational() method
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_isRational().
join()
PyObject * BSplineCurve2dPy::join (PyObject * args)
implementer for the join() method
References getGeom2dBSplineCurvePtr(), Part::Geom2dBSplineCurve::join(), and Type.
Referenced by draftobjects.clone.Clone::execute(), and staticCallback_join().
makeC1Continuous()
PyObject * BSplineCurve2dPy::makeC1Continuous (PyObject * args)
implementer for the makeC1Continuous() method
References getGeom2dBSplineCurvePtr(), Part::Geom2dBSplineCurve::makeC1Continuous(), and Part::PartExceptionOCCError.
Referenced by staticCallback_makeC1Continuous().
movePoint()
PyObject * BSplineCurve2dPy::movePoint (PyObject * args)
implementer for the movePoint() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_movePoint().
PyInit()
int BSplineCurve2dPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::Curve2dPy.
PyMake()
PyObject * BSplineCurve2dPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References BSplineCurve2dPy().
removeKnot()
PyObject * BSplineCurve2dPy::removeKnot (PyObject * args)
implementer for the removeKnot() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_removeKnot().
representation()
std::string BSplineCurve2dPy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
segment()
PyObject * BSplineCurve2dPy::segment (PyObject * args)
implementer for the segment() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_segment().
setCustomAttributes()
int BSplineCurve2dPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setKnot()
PyObject * BSplineCurve2dPy::setKnot (PyObject * args)
implementer for the setKnot() method
References Part::Geometry2dPy::getGeometry2dPtr().
Referenced by staticCallback_setKnot().
setKnots()
PyObject * BSplineCurve2dPy::setKnots (PyObject * args)
implementer for the setKnots() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setKnots().
setNotPeriodic()
PyObject * BSplineCurve2dPy::setNotPeriodic (PyObject * args)
implementer for the setNotPeriodic() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setNotPeriodic().
setOrigin()
PyObject * BSplineCurve2dPy::setOrigin (PyObject * args)
implementer for the setOrigin() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setOrigin().
setPeriodic()
PyObject * BSplineCurve2dPy::setPeriodic (PyObject * args)
implementer for the setPeriodic() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setPeriodic().
setPole()
PyObject * BSplineCurve2dPy::setPole (PyObject * args)
implementer for the setPole() method
References Part::Geometry2dPy::getGeometry2dPtr(), Part::PartExceptionOCCError, and draftgeoutils.general::vec().
Referenced by staticCallback_setPole().
setWeight()
PyObject * BSplineCurve2dPy::setWeight (PyObject * args)
implementer for the setWeight() method
References Part::Geometry2dPy::getGeometry2dPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_setWeight().
staticCallback_approximate()
PyObject * BSplineCurve2dPy::staticCallback_approximate (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the approximate() method
References approximate(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_buildFromPoles()
PyObject * BSplineCurve2dPy::staticCallback_buildFromPoles (PyObject * self, PyObject * args) static
callback for the buildFromPoles() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, buildFromPoles(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_buildFromPolesMultsKnots()
PyObject * BSplineCurve2dPy::staticCallback_buildFromPolesMultsKnots (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the buildFromPolesMultsKnots() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, buildFromPolesMultsKnots(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getCardinalSplineTangents()
PyObject * BSplineCurve2dPy::staticCallback_getCardinalSplineTangents (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the getCardinalSplineTangents() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getCardinalSplineTangents(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getDegree()
PyObject * BSplineCurve2dPy::staticCallback_getDegree (PyObject * self, void * closure) static
getter callback for the Degree attribute
References Base::BaseExceptionFreeCADError, getDegree(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getEndPoint()
PyObject * BSplineCurve2dPy::staticCallback_getEndPoint (PyObject * self, void * closure) static
getter callback for the EndPoint attribute
References Base::BaseExceptionFreeCADError, getEndPoint(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getFirstUKnotIndex()
PyObject * BSplineCurve2dPy::staticCallback_getFirstUKnotIndex (PyObject * self, void * closure) static
getter callback for the FirstUKnotIndex attribute
References Base::BaseExceptionFreeCADError, getFirstUKnotIndex(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getKnot()
PyObject * BSplineCurve2dPy::staticCallback_getKnot (PyObject * self, PyObject * args) static
callback for the getKnot() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getKnot(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getKnots()
PyObject * BSplineCurve2dPy::staticCallback_getKnots (PyObject * self, PyObject * args) static
callback for the getKnots() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getKnots(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getKnotSequence()
PyObject * BSplineCurve2dPy::staticCallback_getKnotSequence (PyObject * self, void * closure) static
getter callback for the KnotSequence attribute
References Base::BaseExceptionFreeCADError, getKnotSequence(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getLastUKnotIndex()
PyObject * BSplineCurve2dPy::staticCallback_getLastUKnotIndex (PyObject * self, void * closure) static
getter callback for the LastUKnotIndex attribute
References Base::BaseExceptionFreeCADError, getLastUKnotIndex(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMaxDegree()
PyObject * BSplineCurve2dPy::staticCallback_getMaxDegree (PyObject * self, void * closure) static
getter callback for the MaxDegree attribute
References Base::BaseExceptionFreeCADError, getMaxDegree(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getMultiplicities()
PyObject * BSplineCurve2dPy::staticCallback_getMultiplicities (PyObject * self, PyObject * args) static
callback for the getMultiplicities() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getMultiplicities(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getMultiplicity()
PyObject * BSplineCurve2dPy::staticCallback_getMultiplicity (PyObject * self, PyObject * args) static
callback for the getMultiplicity() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getMultiplicity(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getNbKnots()
PyObject * BSplineCurve2dPy::staticCallback_getNbKnots (PyObject * self, void * closure) static
getter callback for the NbKnots attribute
References Base::BaseExceptionFreeCADError, getNbKnots(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getNbPoles()
PyObject * BSplineCurve2dPy::staticCallback_getNbPoles (PyObject * self, void * closure) static
getter callback for the NbPoles attribute
References Base::BaseExceptionFreeCADError, getNbPoles(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPole()
PyObject * BSplineCurve2dPy::staticCallback_getPole (PyObject * self, PyObject * args) static
callback for the getPole() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPole(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getPoles()
PyObject * BSplineCurve2dPy::staticCallback_getPoles (PyObject * self, PyObject * args) static
callback for the getPoles() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPoles(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getPolesAndWeights()
PyObject * BSplineCurve2dPy::staticCallback_getPolesAndWeights (PyObject * self, PyObject * args) static
callback for the getPolesAndWeights() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getPolesAndWeights(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getResolution()
PyObject * BSplineCurve2dPy::staticCallback_getResolution (PyObject * self, PyObject * args) static
callback for the getResolution() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getResolution(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getStartPoint()
PyObject * BSplineCurve2dPy::staticCallback_getStartPoint (PyObject * self, void * closure) static
getter callback for the StartPoint attribute
References Base::BaseExceptionFreeCADError, getStartPoint(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getWeight()
PyObject * BSplineCurve2dPy::staticCallback_getWeight (PyObject * self, PyObject * args) static
callback for the getWeight() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getWeight(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getWeights()
PyObject * BSplineCurve2dPy::staticCallback_getWeights (PyObject * self, PyObject * args) static
callback for the getWeights() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getWeights(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_increaseDegree()
PyObject * BSplineCurve2dPy::staticCallback_increaseDegree (PyObject * self, PyObject * args) static
callback for the increaseDegree() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, increaseDegree(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_increaseMultiplicity()
PyObject * BSplineCurve2dPy::staticCallback_increaseMultiplicity (PyObject * self, PyObject * args) static
callback for the increaseMultiplicity() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, increaseMultiplicity(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_incrementMultiplicity()
PyObject * BSplineCurve2dPy::staticCallback_incrementMultiplicity (PyObject * self, PyObject * args) static
callback for the incrementMultiplicity() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, incrementMultiplicity(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_insertKnot()
PyObject * BSplineCurve2dPy::staticCallback_insertKnot (PyObject * self, PyObject * args) static
callback for the insertKnot() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, insertKnot(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_insertKnots()
PyObject * BSplineCurve2dPy::staticCallback_insertKnots (PyObject * self, PyObject * args) static
callback for the insertKnots() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, insertKnots(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_interpolate()
PyObject * BSplineCurve2dPy::staticCallback_interpolate (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the interpolate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, interpolate(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_isClosed()
PyObject * BSplineCurve2dPy::staticCallback_isClosed (PyObject * self, PyObject * args) static
callback for the isClosed() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, isClosed(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_isPeriodic()
PyObject * BSplineCurve2dPy::staticCallback_isPeriodic (PyObject * self, PyObject * args) static
callback for the isPeriodic() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), isPeriodic(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_isRational()
PyObject * BSplineCurve2dPy::staticCallback_isRational (PyObject * self, PyObject * args) static
callback for the isRational() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), isRational(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_join()
PyObject * BSplineCurve2dPy::staticCallback_join (PyObject * self, PyObject * args) static
callback for the join() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), join(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_makeC1Continuous()
PyObject * BSplineCurve2dPy::staticCallback_makeC1Continuous (PyObject * self, PyObject * args) static
callback for the makeC1Continuous() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), makeC1Continuous(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_movePoint()
PyObject * BSplineCurve2dPy::staticCallback_movePoint (PyObject * self, PyObject * args) static
callback for the movePoint() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), movePoint(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_removeKnot()
PyObject * BSplineCurve2dPy::staticCallback_removeKnot (PyObject * self, PyObject * args) static
callback for the removeKnot() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeKnot(), and Base::PyObjectBase::startNotify().
staticCallback_segment()
PyObject * BSplineCurve2dPy::staticCallback_segment (PyObject * self, PyObject * args) static
callback for the segment() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), segment(), and Base::PyObjectBase::startNotify().
staticCallback_setDegree()
int BSplineCurve2dPy::staticCallback_setDegree (PyObject * self, PyObject * value, void * closure) static
setter callback for the Degree attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setEndPoint()
int BSplineCurve2dPy::staticCallback_setEndPoint (PyObject * self, PyObject * value, void * closure) static
setter callback for the EndPoint attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setFirstUKnotIndex()
int BSplineCurve2dPy::staticCallback_setFirstUKnotIndex (PyObject * self, PyObject * value, void * closure) static
setter callback for the FirstUKnotIndex attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setKnot()
PyObject * BSplineCurve2dPy::staticCallback_setKnot (PyObject * self, PyObject * args) static
callback for the setKnot() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setKnot(), and Base::PyObjectBase::startNotify().
staticCallback_setKnots()
PyObject * BSplineCurve2dPy::staticCallback_setKnots (PyObject * self, PyObject * args) static
callback for the setKnots() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setKnots(), and Base::PyObjectBase::startNotify().
staticCallback_setKnotSequence()
int BSplineCurve2dPy::staticCallback_setKnotSequence (PyObject * self, PyObject * value, void * closure) static
setter callback for the KnotSequence attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setLastUKnotIndex()
int BSplineCurve2dPy::staticCallback_setLastUKnotIndex (PyObject * self, PyObject * value, void * closure) static
setter callback for the LastUKnotIndex attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setMaxDegree()
int BSplineCurve2dPy::staticCallback_setMaxDegree (PyObject * self, PyObject * value, void * closure) static
setter callback for the MaxDegree attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setNbKnots()
int BSplineCurve2dPy::staticCallback_setNbKnots (PyObject * self, PyObject * value, void * closure) static
setter callback for the NbKnots attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setNbPoles()
int BSplineCurve2dPy::staticCallback_setNbPoles (PyObject * self, PyObject * value, void * closure) static
setter callback for the NbPoles attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setNotPeriodic()
PyObject * BSplineCurve2dPy::staticCallback_setNotPeriodic (PyObject * self, PyObject * args) static
callback for the setNotPeriodic() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setNotPeriodic(), and Base::PyObjectBase::startNotify().
staticCallback_setOrigin()
PyObject * BSplineCurve2dPy::staticCallback_setOrigin (PyObject * self, PyObject * args) static
callback for the setOrigin() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setOrigin(), and Base::PyObjectBase::startNotify().
staticCallback_setPeriodic()
PyObject * BSplineCurve2dPy::staticCallback_setPeriodic (PyObject * self, PyObject * args) static
callback for the setPeriodic() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setPeriodic(), and Base::PyObjectBase::startNotify().
staticCallback_setPole()
PyObject * BSplineCurve2dPy::staticCallback_setPole (PyObject * self, PyObject * args) static
callback for the setPole() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setPole(), and Base::PyObjectBase::startNotify().
staticCallback_setStartPoint()
int BSplineCurve2dPy::staticCallback_setStartPoint (PyObject * self, PyObject * value, void * closure) static
setter callback for the StartPoint attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setWeight()
PyObject * BSplineCurve2dPy::staticCallback_setWeight (PyObject * self, PyObject * args) static
callback for the setWeight() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setWeight(), and Base::PyObjectBase::startNotify().
staticCallback_toBezier()
PyObject * BSplineCurve2dPy::staticCallback_toBezier (PyObject * self, PyObject * args) static
callback for the toBezier() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and toBezier().
staticCallback_toBiArcs()
PyObject * BSplineCurve2dPy::staticCallback_toBiArcs (PyObject * self, PyObject * args) static
callback for the toBiArcs() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and toBiArcs().
toBezier()
PyObject * BSplineCurve2dPy::toBezier (PyObject * args)
implementer for the toBezier() method
References getGeom2dBSplineCurvePtr().
Referenced by staticCallback_toBezier().
toBiArcs()
PyObject * BSplineCurve2dPy::toBiArcs (PyObject * args)
implementer for the toBiArcs() method
References getGeom2dBSplineCurvePtr(), Part::PartExceptionOCCError, Part::Geom2dBSplineCurve::toBiArcs(), and draftutils.utils::tolerance().
Referenced by staticCallback_toBiArcs().
Member Data Documentation
GetterSetter
PyGetSetDef BSplineCurve2dPy::GetterSetter static
Attribute structure of BSplineCurve2dPy.
Methods
PyMethodDef BSplineCurve2dPy::Methods static
Methods structure of BSplineCurve2dPy.
Type
PyTypeObject BSplineCurve2dPy::Type static
Type structure of BSplineCurve2dPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), join(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/Geom2d/BSplineCurve2dPy.h
Sources/FreeCAD/src/Mod/Part/App/Geom2d/BSplineCurve2dPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/Geom2d/BSplineCurve2dPy.cpp