FreeCAD: MeshCore::MeshEvalRangePoint Class Reference
MeshCore::MeshEvalRangePoint Class Reference
The MeshEvalRangePoint class searches for facets that has point indices out of range.
#include <Degeneration.h>
Public Member Functions
bool Evaluate ()
Searches for facets that has point indices out of range.
std::vector< unsigned long > GetIndices () const
Returns the indices of all facets with invalid point indices.
MeshEvalRangePoint (const MeshKernel &rclM)
Construction.
~MeshEvalRangePoint ()
Destruction.
Public Member Functions inherited from MeshCore::MeshEvaluation
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()
Detailed Description
The MeshEvalRangePoint class searches for facets that has point indices out of range.
See also
MeshFixRangePoint
Author
Werner Mayer
Constructor & Destructor Documentation
MeshEvalRangePoint()
MeshCore::MeshEvalRangePoint::MeshEvalRangePoint (const MeshKernel & rclM)
Construction.
~MeshEvalRangePoint()
MeshCore::MeshEvalRangePoint::~MeshEvalRangePoint ()
Destruction.
Member Function Documentation
Evaluate()
bool MeshEvalRangePoint::Evaluate () virtual
Searches for facets that has point indices out of range.
Implements MeshCore::MeshEvaluation.
Referenced by MeshGui::DlgEvaluateMeshImp::on_analyzeIndicesButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairAllTogether_clicked(), and Mesh::MeshObject::validateIndices().
GetIndices()
std::vector< unsigned long > MeshEvalRangePoint::GetIndices () const
Returns the indices of all facets with invalid point indices.
Referenced by MeshCore::MeshFixRangePoint::Fixup().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Degeneration.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Degeneration.cpp