FreeCAD: PathScripts.post.rml_post Namespace Reference
PathScripts.post.rml_post Namespace Reference
Functions
def addfooter ()
def addheader ()
def convertgcode (cmd, args, state)
def convertobject (obj)
def export (objectslist, filename, argstring)
def feed (x=None, y=None, z=None, state=None)
def home ()
def jog (x=None, y=None, z=None, state=None)
def mm2cord (mm)
def motoroff ()
def motoron ()
def parse (inputstring)
def setjog ()
def speed (xy=None, z=None, state=None)
def xyarc (args, state)
Variables
pythonopen = open
string TOOLTIP
Function Documentation
addfooter()
def PathScripts.post.rml_post.addfooter ()
Referenced by PathScripts.post.rml_post.parse().
addheader()
def PathScripts.post.rml_post.addheader ()
Referenced by PathScripts.post.rml_post.parse().
convertgcode()
def PathScripts.post.rml_post.convertgcode (cmd, args, state)
Convert a single gcode command to equivalent Roland code
References PathScripts.post.rml_post.feed(), PathScripts.post.rml_post.jog(), PathScripts.post.rml_post.speed(), and PathScripts.post.rml_post.xyarc().
Referenced by PathScripts.post.rml_post.parse().
convertobject()
def PathScripts.post.rml_post.convertobject (obj)
References PathScripts.post.rml_post.parse().
Referenced by PathScripts.post.rml_post.export().
export()
def PathScripts.post.rml_post.export (objectslist, filename, argstring)
References PathScripts.post.rml_post.convertobject(), and PathScripts.post.rml_post.pythonopen.
feed()
def PathScripts.post.rml_post.feed (x = None, y = None, z = None, state = None)
References PathScripts.post.rml_post.mm2cord().
Referenced by PathScripts.post.rml_post.convertgcode(), and PathScripts.post.rml_post.xyarc().
home()
def PathScripts.post.rml_post.home ()
Referenced by PathScripts.post.rml_post.parse().
jog()
def PathScripts.post.rml_post.jog (x = None, y = None, z = None, state = None)
References PathScripts.post.rml_post.mm2cord().
Referenced by PathScripts.post.rml_post.convertgcode().
mm2cord()
def PathScripts.post.rml_post.mm2cord (mm)
Referenced by PathScripts.post.rml_post.feed(), and PathScripts.post.rml_post.jog().
motoroff()
def PathScripts.post.rml_post.motoroff ()
Referenced by PathScripts.post.rml_post.parse().
motoron()
def PathScripts.post.rml_post.motoron ()
Referenced by PathScripts.post.rml_post.parse().
parse()
def PathScripts.post.rml_post.parse (inputstring)
References PathScripts.post.rml_post.addfooter(), PathScripts.post.rml_post.addheader(), PathScripts.post.rml_post.convertgcode(), PathScripts.post.rml_post.home(), PathScripts.post.rml_post.motoroff(), PathScripts.post.rml_post.motoron(), and PathScripts.post.rml_post.speed().
Referenced by PathScripts.post.rml_post.convertobject().
setjog()
def PathScripts.post.rml_post.setjog ()
speed()
def PathScripts.post.rml_post.speed (xy = None, z = None, state = None)
Referenced by PathScripts.post.rml_post.convertgcode(), and PathScripts.post.rml_post.parse().
xyarc()
def PathScripts.post.rml_post.xyarc (args, state)
References PathScripts.post.rml_post.feed().
Referenced by PathScripts.post.rml_post.convertgcode().
Variable Documentation
pythonopen
PathScripts.post.rml_post.pythonopen = open
Referenced by PathScripts.post.rml_post.export().
TOOLTIP
string PathScripts.post.rml_post.TOOLTIP
Initial value:
 = '''
 FreeCAD Path post-processor to output code for the Roland Modela MDX-## machines.
 The machine speaks RML-1, specified in 'Roland RML-1 Programming Guidelines'
 https://itp.nyu.edu/classes/cdp-spring2014/files/2014/09/RML1_Manual.pdf
 http://altlab.org/d/content/m/pangelo/ideas/rml_command_guide_en_v100.pdf
 The format has some overlap with HPGL:
 https://en.wikipedia.org/wiki/HPGL
 http://paulbourke.net/dataformats/hpgl/
 '''