FreeCAD: SMDS_VtkEdge Class Reference
SMDS_VtkEdge Class Reference
#include <SMDS_VtkEdge.hxx>
Public Member Functions
bool ChangeNodes (const SMDS_MeshNode *node1, const SMDS_MeshNode *node2)
virtual bool ChangeNodes (const SMDS_MeshNode *nodes[], const int nbNodes)
virtual SMDS_ElemIteratorPtr elementsIterator (SMDSAbs_ElementType type) const
virtual SMDSAbs_EntityType GetEntityType () const
virtual const SMDS_MeshNode * GetNode (const int ind) const
Return node by its index.
virtual vtkIdType GetVtkType () const
void init (std::vector< vtkIdType > &nodeIds, SMDS_Mesh *mesh)
virtual SMDS_NodeIteratorPtr interlacedNodesIterator () const
virtual, redefined in vtkEdge, vtkFace and vtkVolume classes
virtual bool IsMediumNode (const SMDS_MeshNode *node) const
virtual bool IsQuadratic () const
virtual int NbEdges () const
Return the number of edges owned by or linked with the current element.
virtual int NbNodes () const
Return The number of nodes owned by the current element.
virtual SMDS_NodeIteratorPtr nodesIteratorToUNV () const
virtual, redefined in vtkEdge, vtkFace and vtkVolume classes
virtual void Print (std::ostream &OS) const
SMDS_VtkEdge ()
SMDS_VtkEdge (std::vector< vtkIdType > &nodeIds, SMDS_Mesh *mesh)
~SMDS_VtkEdge ()
Public Member Functions inherited from SMDS_MeshEdge
virtual SMDSAbs_GeometryType GetGeomType () const
virtual SMDSAbs_ElementType GetType () const
Return the type of the current element.
Public Member Functions inherited from SMDS_MeshCell
SMDS_MeshCell ()
virtual bool vtkOrder (const SMDS_MeshNode *[], const int)
virtual ~SMDS_MeshCell ()
Public Member Functions inherited from SMDS_MeshElement
iterator begin_nodes () const
SMDS_ElemIteratorPtr edgesIterator () const
Create an iterator which iterate on edges linked with or owned by the element.
iterator end_nodes () const
SMDS_ElemIteratorPtr facesIterator () const
Create an iterator which iterate on faces linked with or owned by the element.
int GetID () const
int getIdInShape () const
ShortType getMeshId () const
virtual int GetNodeIndex (const SMDS_MeshNode *node) const
Check if a node belongs to the element.
const SMDS_MeshNode * GetNodeWrap (const int ind) const
Return node by its index.
LongType getshapeId () const
int getVtkId () const
virtual SMDS_ElemIteratorPtr interlacedNodesElemIterator () const
virtual bool IsPoly () const
virtual bool IsValidIndex (const int ind) const
Return true if index of node is valid (0 <= ind < NbNodes())
virtual int NbCornerNodes () const
Return number of nodes excluding medium ones.
virtual int NbFaces () const
Return the number of faces owned by or linked with the current element.
virtual SMDS_NodeIteratorPtr nodeIterator () const
SMDS_ElemIteratorPtr nodesIterator () const
Create an iterator which iterate on nodes owned by the element.
int WrappedIndex (const int ind) const
Return a valid node index, fixing the given one if necessary.
Public Member Functions inherited from SMDS_MeshObject
virtual ~SMDS_MeshObject ()
Additional Inherited Members
Public Types inherited from SMDS_MeshElement
typedef SMDS_StdIterator< const SMDS_MeshNode *, SMDS_ElemIteratorPtr > iterator
Static Public Member Functions inherited from SMDS_MeshCell
template<class VECT >
static void applyInterlace (const std::vector< int > &interlace, VECT &data)
template<class VECT >
static void applyInterlaceRev (const std::vector< int > &interlace, VECT &data)
static const std::vector< int > & fromVtkOrder (SMDSAbs_EntityType smdsType)
Return indices to transform cell connectivity from VTK to SMDS Usage: smdsIDs[i] = vtkIDs[ indices[ i ]].
static const std::vector< int > & fromVtkOrder (VTKCellType vtkType)
Return indices to transform cell connectivity from VTK to SMDS Usage: smdsIDs[i] = vtkIDs[ indices[ i ]].
static const std::vector< int > & interlacedSmdsOrder (SMDSAbs_EntityType smdsType, const size_t nbNodes=0)
Return indices to set nodes of a quadratic 1D or 2D element in interlaced order Usage: interlacedIDs[i] = smdsIDs[ indices[ i ]].
static const std::vector< int > & reverseSmdsOrder (SMDSAbs_EntityType smdsType, const size_t nbNodes=0)
Return indices to reverse an SMDS cell of given type. nbNodes is useful for polygons Usage: reverseIDs[i] = forwardIDs[ indices[ i ]].
static SMDSAbs_ElementType toSmdsType (SMDSAbs_EntityType entityType)
Return SMDSAbs_ElementType by SMDSAbs_EntityType.
static SMDSAbs_ElementType toSmdsType (SMDSAbs_GeometryType geomType)
Return SMDSAbs_ElementType by SMDSAbs_GeometryType.
static SMDSAbs_EntityType toSmdsType (VTKCellType vtkType)
Return SMDSAbs_EntityType corresponding to VTKCellType.
static const std::vector< int > & toVtkOrder (SMDSAbs_EntityType smdsType)
Return indices to transform cell connectivity from SMDS to VTK Usage: vtkIDs[i] = smdsIDs[ indices[ i ]].
static const std::vector< int > & toVtkOrder (VTKCellType vtkType)
Return indices to transform cell connectivity from SMDS to VTK Usage: vtkIDs[i] = smdsIDs[ indices[ i ]].
static VTKCellType toVtkType (SMDSAbs_EntityType vtkType)
Return VTKCellType corresponding to SMDSAbs_EntityType.
Static Public Attributes inherited from SMDS_MeshCell
static int nbCells = 0
Protected Member Functions inherited from SMDS_MeshCell
void exchange (const SMDS_MeshNode *nodes[], int a, int b)
Protected Member Functions inherited from SMDS_MeshElement
virtual void init (int id=-1, ShortType meshId=-1, LongType shapeId=0)
void setId (int id)
void setIdInShape (int id)
void setShapeId (LongType shapeId)
void setVtkId (int vtkId)
SMDS_MeshElement (int id, ShortType meshId, LongType shapeId=0)
SMDS_MeshElement (int ID=-1)
Protected Attributes inherited from SMDS_MeshElement
int myID
Element index in vector SMDS_Mesh::myNodes or SMDS_Mesh::myCells.
int myIdInShape
Element index in SMESHDS_SubMesh vector.
ShortType myMeshId
SMDS_Mesh identification in SMESH.
LongType myShapeId
SubShape and SubMesh identification in SMESHDS.
int myVtkID
index in vtkUnstructuredGrid
Constructor & Destructor Documentation
SMDS_VtkEdge() [1/2]
SMDS_VtkEdge::SMDS_VtkEdge ()
SMDS_VtkEdge() [2/2]
SMDS_VtkEdge::SMDS_VtkEdge (std::vector< vtkIdType > & nodeIds, SMDS_Mesh * mesh)
~SMDS_VtkEdge()
SMDS_VtkEdge::~SMDS_VtkEdge ()
Member Function Documentation
ChangeNodes() [1/2]
bool SMDS_VtkEdge::ChangeNodes (const SMDS_MeshNode * node1, const SMDS_MeshNode * node2)
ChangeNodes() [2/2]
bool SMDS_VtkEdge::ChangeNodes (const SMDS_MeshNode * nodes[], const int nbNodes) virtual
Implements SMDS_MeshCell.
References SMDS_MeshElement::getVtkId().
elementsIterator()
SMDS_ElemIteratorPtr SMDS_VtkEdge::elementsIterator (SMDSAbs_ElementType type) const virtual
Reimplemented from SMDS_MeshElement.
GetEntityType()
SMDSAbs_EntityType SMDS_VtkEdge::GetEntityType () const virtual
Implements SMDS_MeshElement.
GetNode()
const SMDS_MeshNode * SMDS_VtkEdge::GetNode (const int ind) const virtual
Return node by its index.
Parameters
ind - node index
Return values
const SMDS_MeshNode* - the node
Reimplemented from SMDS_MeshElement.
GetVtkType()
vtkIdType SMDS_VtkEdge::GetVtkType () const virtual
Reimplemented from SMDS_MeshEdge.
init()
void SMDS_VtkEdge::init (std::vector< vtkIdType > & nodeIds, SMDS_Mesh * mesh)
References SMDS_MeshElement::init().
Referenced by SMDS_Mesh::AddEdgeWithID(), SMDS_Mesh::FindEdgeOrCreate(), and DocumentObject.DocumentObject::onChanged().
interlacedNodesIterator()
SMDS_NodeIteratorPtr SMDS_VtkEdge::interlacedNodesIterator () const virtual
virtual, redefined in vtkEdge, vtkFace and vtkVolume classes
Reimplemented from SMDS_MeshElement.
IsMediumNode()
bool SMDS_VtkEdge::IsMediumNode (const SMDS_MeshNode * node) const virtual
Reimplemented from SMDS_MeshElement.
References SMDS_MeshElement::getVtkId().
IsQuadratic()
bool SMDS_VtkEdge::IsQuadratic () const virtual
Reimplemented from SMDS_MeshElement.
NbEdges()
int SMDS_VtkEdge::NbEdges () const virtual
Return the number of edges owned by or linked with the current element.
Reimplemented from SMDS_MeshElement.
NbNodes()
int SMDS_VtkEdge::NbNodes () const virtual
Return The number of nodes owned by the current element.
Reimplemented from SMDS_MeshElement.
nodesIteratorToUNV()
SMDS_NodeIteratorPtr SMDS_VtkEdge::nodesIteratorToUNV () const virtual
virtual, redefined in vtkEdge, vtkFace and vtkVolume classes
Reimplemented from SMDS_MeshElement.
Print()
void SMDS_VtkEdge::Print (std::ostream & OS) const virtual
Reimplemented from SMDS_MeshElement.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_VtkEdge.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_VtkEdge.cpp