FreeCAD: SketcherGui::DrawSketchHandler3PointCircle Class Reference
SketcherGui::DrawSketchHandler3PointCircle Class Reference
#include <DrawSketchHandlerCircle.h>
Public Types
enum SelectMode { STATUS_SEEK_First , STATUS_SEEK_Second , STATUS_SEEK_Third , STATUS_End }
mode table
Public Member Functions
DrawSketchHandler3PointCircle ()
virtual void mouseMove (Base::Vector2d onSketchPos) override
virtual bool pressButton (Base::Vector2d onSketchPos) override
virtual bool releaseButton (Base::Vector2d onSketchPos) override
virtual ~DrawSketchHandler3PointCircle ()
Public Member Functions inherited from SketcherGui::DrawSketchHandler
void activate (ViewProviderSketch *)
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::PointPos::none, bool createowncommand=true)
void deactivate ()
DrawSketchHandler ()
int getHighestCurveIndex (void)
int getHighestVertexIndex (void)
virtual void mouseMove (Base::Vector2d onSketchPos)=0
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
virtual bool pressButton (Base::Vector2d onSketchPos)=0
virtual void quit (void)
virtual void registerPressedKey (bool, int)
virtual bool releaseButton (Base::Vector2d onSketchPos)=0
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void resetPositionText (void)
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void setPositionText (const Base::Vector2d &Pos)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
virtual ~DrawSketchHandler ()
Protected Attributes
Base::Vector2d CenterPoint
std::vector< Base::Vector2d > EditCurve
Base::Vector2d FirstPoint
SelectMode Mode
double N
double radius
Base::Vector2d SecondPoint
std::vector< AutoConstraint > sugConstr1
std::vector< AutoConstraint > sugConstr2
std::vector< AutoConstraint > sugConstr3
Protected Attributes inherited from SketcherGui::DrawSketchHandler
ViewProviderSketch * sketchgui
QCursor oldCursor
QCursor actCursor
QPixmap actCursorPixmap
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
virtual QString getCrosshairCursorSVGName () const
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
void updateCursor ()
updates the actCursor with the icon by calling getCrosshairCursorSVGName(), enabling to set data member dependent icons (i.e.
void unsetCursor (void)
restitutes the cursor that was in use at the moment of starting the DrawSketchHandler (i.e. oldCursor)
void applyCursor (void)
restitutes the DSH cached cursor (e.g. without any tail due to autoconstraints, ...)
unsigned long getCrosshairColor ()
returns the color to be used for the crosshair (configurable as a parameter)
qreal devicePixelRatio ()
functions to set the cursor to a given svgName (to be migrated to NVI style)
void drawEdit (const std::vector< Base::Vector2d > &EditCurve)
void drawEdit (const std::list< std::vector< Base::Vector2d > > &list)
void drawEdit (const std::vector< Part::Geometry * > &geometries)
void drawEditMarkers (const std::vector< Base::Vector2d > &EditMarkers, unsigned int augmentationlevel=0)
void setAxisPickStyle (bool on)
void moveCursorToSketchPoint (Base::Vector2d point)
void preselectAtPoint (Base::Vector2d point)
void drawPositionAtCursor (const Base::Vector2d &position)
void drawDirectionAtCursor (const Base::Vector2d &position, const Base::Vector2d &origin)
int getPreselectPoint (void) const
int getPreselectCurve (void) const
int getPreselectCross (void) const
Sketcher::SketchObject * getSketchObject ()
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Returns constraints icons scaled to width.
Member Enumeration Documentation
SelectMode
enum SketcherGui::DrawSketchHandler3PointCircle::SelectMode
mode table
Enumerator
STATUS_SEEK_First
enum value -—.
STATUS_SEEK_Second
enum value -—.
STATUS_SEEK_Third
enum value -—.
STATUS_End
Constructor & Destructor Documentation
DrawSketchHandler3PointCircle()
SketcherGui::DrawSketchHandler3PointCircle::DrawSketchHandler3PointCircle ()
~DrawSketchHandler3PointCircle()
virtual SketcherGui::DrawSketchHandler3PointCircle::~DrawSketchHandler3PointCircle () virtual
Member Function Documentation
mouseMove()
virtual void SketcherGui::DrawSketchHandler3PointCircle::mouseMove (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::applyCursor(), CenterPoint, SketcherGui::AutoConstraint::CURVE, SketcherGui::DrawSketchHandler::drawEdit(), EditCurve, FirstPoint, Part::Geom2dCircle::getCircleCenter(), SketcherGui::GetPointAngle(), Mode, N, radius, SketcherGui::DrawSketchHandler::renderSuggestConstraintsCursor(), SecondPoint, SketcherGui::DrawSketchHandler::seekAutoConstraint(), SketcherGui::DrawSketchHandler::setPositionText(), STATUS_SEEK_First, STATUS_SEEK_Second, STATUS_SEEK_Third, sugConstr1, sugConstr2, sugConstr3, Base::Vector2d::x, and Base::Vector2d::y.
pressButton()
virtual bool SketcherGui::DrawSketchHandler3PointCircle::pressButton (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
References SketcherGui::DrawSketchHandler::applyCursor(), SketcherGui::DrawSketchHandler::drawEdit(), EditCurve, FirstPoint, Mode, SecondPoint, STATUS_End, STATUS_SEEK_First, STATUS_SEEK_Second, and STATUS_SEEK_Third.
releaseButton()
virtual bool SketcherGui::DrawSketchHandler3PointCircle::releaseButton (Base::Vector2d onSketchPos) override virtual
Implements SketcherGui::DrawSketchHandler.
References Gui::Command::abortCommand(), SketcherGui::DrawSketchHandler::applyCursor(), CenterPoint, Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Base::Console(), SketcherGui::Construction, SketcherGui::DrawSketchHandler::createAutoConstraints(), SketcherGui::DrawSketchHandler::drawEdit(), EditCurve, Base::ConsoleSingleton::Error(), SketcherGui::geometryCreationMode, App::GetApplication(), ParameterGrp::GetBool(), SketcherGui::DrawSketchHandler::getHighestCurveIndex(), Gui::ViewProviderDocumentObject::getObject(), App::Application::GetParameterGroupByPath(), Mode, Sketcher::none, Gui::Command::openCommand(), SketcherGui::ViewProviderSketch::purgeHandler(), draftutils.translate::QT_TRANSLATE_NOOP, radius, SketcherGui::DrawSketchHandler::resetPositionText(), SketcherGui::DrawSketchHandler::sketchgui, STATUS_End, STATUS_SEEK_First, sugConstr1, sugConstr2, sugConstr3, SketcherGui::tryAutoRecomputeIfNotSolve(), SketcherGui::DrawSketchHandler::unsetCursor(), Base::Vector2d::x, and Base::Vector2d::y.
Member Data Documentation
CenterPoint
Base::Vector2d SketcherGui::DrawSketchHandler3PointCircle::CenterPoint protected
Referenced by mouseMove(), and releaseButton().
EditCurve
std::vector<Base::Vector2d> SketcherGui::DrawSketchHandler3PointCircle::EditCurve protected
Referenced by mouseMove(), pressButton(), and releaseButton().
FirstPoint
Base::Vector2d SketcherGui::DrawSketchHandler3PointCircle::FirstPoint protected
Referenced by mouseMove(), and pressButton().
Mode
SelectMode SketcherGui::DrawSketchHandler3PointCircle::Mode protected
Referenced by mouseMove(), pressButton(), and releaseButton().
N
double SketcherGui::DrawSketchHandler3PointCircle::N protected
Referenced by mouseMove().
radius
double SketcherGui::DrawSketchHandler3PointCircle::radius protected
Referenced by PathScripts.PathPocketBase.ObjectPocket::areaOpAreaParams(), PathScripts.PathProfile.ObjectProfile::areaOpAreaParams(), PathScripts.PathPocketBase.ObjectPocket::areaOpPathParams(), PathScripts.PathAreaOp.ObjectOp::areaOpSetDefaultValues(), DraftGui.DraftToolBar::changeRadiusValue(), PathScripts.PathDressupHoldingTags.Tag::createSolidsAt(), PathScripts.PathSurface.ObjectSurface::deleteOpVariables(), PathScripts.PathWaterline.ObjectWaterline::deleteOpVariables(), PathScripts.PathOp.ObjectOp::execute(), PathScripts.PathDressupAxisMap.TaskPanel::getFields(), ifc4.ifcsweptdisksolid::innerradiussize(), mouseMove(), draftguitools.gui_snapper.Snapper::off(), PathScripts.PathSurfaceSupport.ProcessSelectedFaces::preProcessModel(), releaseButton(), DraftGui.DraftToolBar::reset_ui_values(), draftguitools.gui_snapper.Snapper::showradius(), draftguitools.gui_snapper.Snapper::snapToCrossExtensions(), draftguitools.gui_snapper.Snapper::snapToExtensions(), draftguitools.gui_snapper.Snapper::snapToGrid(), draftguitools.gui_snapper.Snapper::snapToHold(), draftguitools.gui_snapper.Snapper::snapToPolar(), PathScripts.PathDressupAxisMap.TaskPanel::updateUI(), DraftGui.DraftToolBar::validatePoint(), automotive_design.right_circular_cone::wr1(), automotive_design.conical_surface::wr1(), config_control_design.conical_surface::wr1(), automotive_design.swept_disk_solid::wr2(), and ifc2x3.ifcsweptdisksolid::wr2().
SecondPoint
Base::Vector2d SketcherGui::DrawSketchHandler3PointCircle::SecondPoint protected
Referenced by mouseMove(), and pressButton().
sugConstr1
std::vector<AutoConstraint> SketcherGui::DrawSketchHandler3PointCircle::sugConstr1 protected
Referenced by mouseMove(), and releaseButton().
sugConstr2
std::vector<AutoConstraint> SketcherGui::DrawSketchHandler3PointCircle::sugConstr2 protected
Referenced by mouseMove(), and releaseButton().
sugConstr3
std::vector<AutoConstraint> SketcherGui::DrawSketchHandler3PointCircle::sugConstr3 protected
Referenced by mouseMove(), and releaseButton().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h