FreeCAD: Base::gzstreambuf Class Reference
Base::gzstreambuf Class Reference
#include <gzstream.h>
Public Member Functions
gzstreambuf * close ()
gzstreambuf ()
int is_open ()
gzstreambuf * open (const char *name, int open_mode, int comp)
virtual int overflow (int c=EOF)
virtual int sync ()
virtual int underflow ()
~gzstreambuf ()
Constructor & Destructor Documentation
gzstreambuf()
Base::gzstreambuf::gzstreambuf ()
~gzstreambuf()
Base::gzstreambuf::~gzstreambuf ()
Member Function Documentation
close()
gzstreambuf * Base::gzstreambuf::close ()
References is_open(), and sync().
Referenced by femexamples.examplesgui.FemExamples::reject().
is_open()
int Base::gzstreambuf::is_open ()
Referenced by close(), and open().
open()
gzstreambuf * Base::gzstreambuf::open (const char * name, int open_mode, int comp)
References is_open().
overflow()
int Base::gzstreambuf::overflow (int c = EOF) virtual
sync()
int Base::gzstreambuf::sync () virtual
Referenced by close().
underflow()
int Base::gzstreambuf::underflow () virtual
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Base/gzstream.h
Sources/FreeCAD/src/Base/gzstream.cpp