FreeCAD: MeshCore::MeshGridIterator Class Reference
MeshCore::MeshGridIterator Class Reference
The MeshGridIterator class provides an interface to walk through all grid elements of a mesh grid.
#include <Grid.h>
Classes
struct GridElement
Checks if a grid position is already visited by NextOnRay().
Public Member Functions
Base::BoundBox3f GetBoundBox (void) const
Returns the bounding box of the current grid element.
unsigned long GetCtElements () const
Returns the number of elements in the current grid.
void GetElements (std::vector< unsigned long > &raulElements) const
Returns indices of the elements in the current grid.
MeshGridIterator (const MeshGrid &rclG)
Construction.
Iteration
void Init (void)
Sets the iterator to the first element.
bool More (void) const
Checks if the iterator has not yet reached the end position.
void Next (void)
Go to the next grid.
Tests with rays
bool InitOnRay (const Base::Vector3f &rclPt, const Base::Vector3f &rclDir, std::vector< unsigned long > &raulElements)
Searches for facets around the ray.
bool InitOnRay (const Base::Vector3f &rclPt, const Base::Vector3f &rclDir, float fMaxSearchArea, std::vector< unsigned long > &raulElements)
Searches for facets around the ray.
bool NextOnRay (std::vector< unsigned long > &raulElements)
Searches for facets around the ray.
void GetGridPos (unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
Returns the grid number of the current position.
Detailed Description
The MeshGridIterator class provides an interface to walk through all grid elements of a mesh grid.
Constructor & Destructor Documentation
MeshGridIterator()
MeshGridIterator::MeshGridIterator (const MeshGrid & rclG)
Construction.
Member Function Documentation
GetBoundBox()
Base::BoundBox3f MeshCore::MeshGridIterator::GetBoundBox (void) const
Returns the bounding box of the current grid element.
Referenced by MeshCore::MeshTrimByPlane::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), MeshCore::MeshTrimming::CheckFacets(), MeshCore::MeshAlgorithm::CutWithPlane(), MeshCore::MeshAlgorithm::GetFacetsFromPlane(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), Mesh::MeshPy::nearestFacetOnRay(), MeshCore::MeshProjection::projectLineOnMesh(), MeshCore::MeshFacetGrid::Verify(), and MeshCore::MeshPointGrid::Verify().
GetCtElements()
unsigned long MeshCore::MeshGridIterator::GetCtElements () const
Returns the number of elements in the current grid.
GetElements()
void MeshCore::MeshGridIterator::GetElements (std::vector< unsigned long > & raulElements) const
Returns indices of the elements in the current grid.
Referenced by MeshCore::MeshTrimByPlane::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), MeshCore::MeshTrimming::CheckFacets(), MeshCore::MeshAlgorithm::CutWithPlane(), MeshCore::MeshEvalSelfIntersection::Evaluate(), MeshCore::MeshAlgorithm::GetFacetsFromPlane(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), MeshCore::MeshProjection::projectLineOnMesh(), MeshCore::MeshFacetGrid::Verify(), and MeshCore::MeshPointGrid::Verify().
GetGridPos()
void MeshCore::MeshGridIterator::GetGridPos (unsigned long & rulX, unsigned long & rulY, unsigned long & rulZ) const
Returns the grid number of the current position.
Referenced by Mesh::MeshPy::nearestFacetOnRay().
Init()
void MeshCore::MeshGridIterator::Init (void)
Sets the iterator to the first element.
Referenced by MeshCore::MeshTrimByPlane::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), MeshCore::MeshTrimming::CheckFacets(), MeshCore::MeshAlgorithm::CutWithPlane(), MeshCore::MeshEvalSelfIntersection::Evaluate(), MeshCore::MeshAlgorithm::GetFacetsFromPlane(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), Mesh::MeshPy::nearestFacetOnRay(), MeshCore::MeshProjection::projectLineOnMesh(), MeshCore::MeshFacetGrid::Verify(), and MeshCore::MeshPointGrid::Verify().
InitOnRay() [1/2]
bool MeshGridIterator::InitOnRay (const Base::Vector3f & rclPt, const Base::Vector3f & rclDir, float fMaxSearchArea, std::vector< unsigned long > & raulElements)
Searches for facets around the ray.
References InitOnRay().
InitOnRay() [2/2]
bool MeshGridIterator::InitOnRay (const Base::Vector3f & rclPt, const Base::Vector3f & rclDir, std::vector< unsigned long > & raulElements)
Searches for facets around the ray.
Referenced by InitOnRay(), and MeshCore::MeshAlgorithm::NearestFacetOnRay().
More()
bool MeshCore::MeshGridIterator::More (void) const
Checks if the iterator has not yet reached the end position.
Referenced by MeshCore::MeshTrimByPlane::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), MeshCore::MeshTrimming::CheckFacets(), MeshCore::MeshAlgorithm::CutWithPlane(), MeshCore::MeshEvalSelfIntersection::Evaluate(), MeshCore::MeshAlgorithm::GetFacetsFromPlane(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), Mesh::MeshPy::nearestFacetOnRay(), MeshCore::MeshProjection::projectLineOnMesh(), MeshCore::MeshFacetGrid::Verify(), and MeshCore::MeshPointGrid::Verify().
Next()
void MeshCore::MeshGridIterator::Next (void)
Go to the next grid.
Referenced by MeshCore::MeshTrimByPlane::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), MeshCore::MeshTrimming::CheckFacets(), MeshCore::MeshAlgorithm::CutWithPlane(), MeshCore::MeshEvalSelfIntersection::Evaluate(), MeshCore::MeshAlgorithm::GetFacetsFromPlane(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), Mesh::MeshPy::nearestFacetOnRay(), MeshCore::MeshProjection::projectLineOnMesh(), MeshCore::MeshFacetGrid::Verify(), and MeshCore::MeshPointGrid::Verify().
NextOnRay()
bool MeshGridIterator::NextOnRay (std::vector< unsigned long > & raulElements)
Searches for facets around the ray.
References Base::BoundBox3< _Precision >::BACK, Base::BoundBox3< _Precision >::BOTTOM, Base::BoundBox3< _Precision >::FRONT, Base::BoundBox3< _Precision >::INVALID, Base::BoundBox3< _Precision >::LEFT, Base::BoundBox3< _Precision >::RIGHT, and Base::BoundBox3< _Precision >::TOP.
Referenced by MeshCore::MeshAlgorithm::NearestFacetOnRay().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/App/Core/Grid.h
Sources/FreeCAD/src/Mod/Mesh/App/Core/Grid.cpp