FreeCAD: TechDrawGui::QGIProjGroup Class Reference
TechDrawGui::QGIProjGroup Class Reference
#include <QGIProjGroup.h>
Public Types
enum { Type = QGraphicsItem::UserType + 113 }
Public Types inherited from TechDrawGui::QGIViewCollection
enum { Type = QGraphicsItem::UserType + 110 }
Public Types inherited from TechDrawGui::QGIView
enum { Type = QGraphicsItem::UserType + 101 }
Public Member Functions
void alignTo (QGIProjGroup *, const QString &alignment)
virtual void drawBorder (void) override
QGIProjGroup ()
virtual void rotateView (void) override
int type () const override
virtual void updateView (bool update=false) override
~QGIProjGroup ()=default
Public Member Functions inherited from TechDrawGui::QGIViewCollection
QGIViewCollection ()
int type () const override
~QGIViewCollection ()=default
Public Member Functions inherited from TechDrawGui::QGIView
virtual void addArbitraryItem (QGraphicsItem *qgi)
void alignTo (QGraphicsItem *, const QString &alignment)
virtual QRectF boundingRect () const override
virtual void draw (void)
virtual void drawCaption (void)
QGIViewClip * getClipGroup (void)
virtual QColor getCurrentColor (void)
virtual bool getFrameState (void)
MDIViewPage * getMDIViewPage (void) const
virtual QColor getNormalColor (void)
virtual QColor getPreColor (void)
double getScale (void)
virtual QColor getSelectColor (void)
virtual QColor getSettingColor (void)
const char * getViewName () const
const std::string getViewNameAsString () const
TechDraw::DrawView * getViewObject () const
virtual void isVisible (bool state)
virtual bool isVisible (void)
void makeMark (Base::Vector3d v, QColor c=Qt::red)
void makeMark (double x, double y, QColor c=Qt::red)
void makeMark (QPointF p, QColor c=Qt::red)
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QGIView ()
virtual void removeChild (QGIView *child)
virtual void setGroupSelection (bool b)
void setLocked (bool b)
virtual void setSettingColor (QColor c)
void setViewFeature (TechDraw::DrawView *obj)
virtual void toggleCache (bool state)
int type () const override
virtual ~QGIView ()
void setPosition (qreal x, qreal y)
Methods to ensure that Y-Coordinates are orientated correctly.
qreal getY ()
bool isInnerView ()
void isInnerView (bool state)
double getYInClip (double y)
Protected Member Functions
QGIView * getAnchorQItem () const
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) override
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual bool sceneEventFilter (QGraphicsItem *watched, QEvent *event) override
Protected Member Functions inherited from TechDrawGui::QGIView
virtual QRectF customChildrenBoundingRect (void) const
void dumpRect (const char *text, QRectF r)
Base::Reference< ParameterGrp > getParmGroupCol (void)
QGIView * getQGIVByName (std::string name)
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
Additional Inherited Members
Public Slots inherited from TechDrawGui::QGIView
virtual void onSourceChange (TechDraw::DrawView *newParent)
Static Public Member Functions inherited from TechDrawGui::QGIView
static int calculateFontPixelSize (double sizeInMillimetres)
static int calculateFontPixelWidth (const QFont &font)
static double getDimFontSize (void)
static QGVPage * getGraphicsView (TechDraw::DrawView *dv)
static QString getPrefFont (void)
static double getPrefFontSize (void)
static Gui::ViewProvider * getViewProvider (App::DocumentObject *obj)
Public Attributes inherited from TechDrawGui::QGIView
boost::signals2::signal< void(QGIView *, QPointF)> signalSelectPoint
Static Public Attributes inherited from TechDrawGui::QGIView
static const double DefaultFontSizeInMM = 5.0
Protected Attributes inherited from TechDrawGui::QGIView
QHash< QString, QGraphicsItem * > alignHash
QGCustomBorder * m_border
QBrush m_brush
QGICaption * m_caption
QColor m_colCurrent
QColor m_colNormal
QColor m_colPre
QColor m_colSel
QColor m_colSetting
QPen m_decorPen
QFont m_font
bool m_innerView
QGCustomLabel * m_label
QGCustomImage * m_lock
bool m_locked
double m_lockHeight
double m_lockWidth
QPen m_pen
std::string viewName
TechDraw::DrawView * viewObj
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGIProjGroup()
QGIProjGroup::QGIProjGroup ()
~QGIProjGroup()
TechDrawGui::QGIProjGroup::~QGIProjGroup () default
Member Function Documentation
alignTo()
void TechDrawGui::QGIProjGroup::alignTo (QGIProjGroup * , const QString & alignment)
drawBorder()
void QGIProjGroup::drawBorder (void) override virtual
Reimplemented from TechDrawGui::QGIView.
getAnchorQItem()
QGIView * QGIProjGroup::getAnchorQItem () const protected
References TechDraw::DrawProjGroup::Anchor, and App::PropertyLink::getValue().
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and sceneEventFilter().
itemChange()
QVariant QGIProjGroup::itemChange (GraphicsItemChange change, const QVariant & value) override protected virtual
Reimplemented from TechDrawGui::QGIViewCollection.
References Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), App::PropertyEnumeration::getValueAsString(), Base::Type::isDerivedFrom(), TechDrawGui::QGIViewCollection::itemChange(), and TechDraw::DrawProjGroupItem::Type.
mouseMoveEvent()
void QGIProjGroup::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override protected virtual
References getAnchorQItem().
Referenced by sceneEventFilter().
mousePressEvent()
void QGIProjGroup::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected virtual
Reimplemented from TechDrawGui::QGIView.
References getAnchorQItem().
Referenced by sceneEventFilter().
mouseReleaseEvent()
void QGIProjGroup::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override protected virtual
Reimplemented from TechDrawGui::QGIViewCollection.
References TechDrawGui::Rez::appX(), getAnchorQItem(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getY(), TechDrawGui::QGIView::mouseReleaseEvent(), TechDrawGui::QGIViewCollection::mouseReleaseEvent(), and TechDraw::DrawView::setPosition().
Referenced by sceneEventFilter().
rotateView()
void QGIProjGroup::rotateView (void) override virtual
Reimplemented from TechDrawGui::QGIView.
References Base::Console(), and Base::ConsoleSingleton::Warning().
sceneEventFilter()
bool QGIProjGroup::sceneEventFilter (QGraphicsItem * watched, QEvent * event) override protected virtual
References getAnchorQItem(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
type()
int TechDrawGui::QGIProjGroup::type (void) const override
updateView()
void QGIProjGroup::updateView (bool update = false) override virtual
Reimplemented from TechDrawGui::QGIViewCollection.
References TechDrawGui::QGIViewCollection::updateView().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGIProjGroup.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGIProjGroup.cpp