FreeCAD: Sandbox::Module Class Reference
Sandbox::Module Class Reference
Public Member Functions
Module ()
virtual ~Module ()
Constructor & Destructor Documentation
Module()
Sandbox::Module::Module ()
References Sandbox::PythonBaseClass::init_type(), Sandbox::DocumentProtectorPy::init_type(), and Sandbox::DocumentObjectProtectorPy::init_type().
~Module()
virtual Sandbox::Module::~Module () virtual
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Sandbox/App/AppSandbox.cpp