FreeCAD: StdMeshers_ViscousLayers2D Class Reference
StdMeshers_ViscousLayers2D Class Reference
Hypothesis defining parameters of viscous layers.
#include <StdMeshers_ViscousLayers2D.hxx>
Public Member Functions
void RestoreListeners () const
At study restoration, restore event listeners used to clear an inferior dim sub-mesh modified by viscous layers.
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)
Initialize my parameter values by the mesh built on the geometry.
StdMeshers_ViscousLayers2D (int hypId, int studyId, SMESH_Gen *gen)
Public Member Functions inherited from StdMeshers_ViscousLayers
SMESH_ProxyMesh::Ptr Compute (SMESH_Mesh &theMesh, const TopoDS_Shape &theShape, const bool toMakeN2NMap=false) const
std::vector< int > GetBndShapes () const
ExtrusionMethod GetMethod () const
int GetNumberLayers () const
double GetStretchFactor () const
double GetTotalThickness () const
bool IsShapeWithLayers (int shapeIndex) const
bool IsToIgnoreShapes () const
virtual std::istream & LoadFrom (std::istream &load)
virtual std::ostream & SaveTo (std::ostream &save)
void SetBndShapes (const std::vector< int > &shapeIds, bool toIgnore)
void SetMethod (ExtrusionMethod how)
void SetNumberLayers (int nb)
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)
Initialize my parameter values by the mesh built on the geometry.
void SetStretchFactor (double factor)
void SetTotalThickness (double thickness)
StdMeshers_ViscousLayers (int hypId, int studyId, SMESH_Gen *gen)
Public Member Functions inherited from SMESH_Hypothesis
void ClearParameters ()
virtual bool DataDependOnParams () const
The returned value is used by NotifySubMeshesHypothesisModification() to decide to call subMesh->AlgoStateEngine(MODIF_HYP, hyp) or not if subMesh is ready to be computed (algo+hyp==OK) but not yet computed. True result is reasonable for example if EventListeners depend on parameters of hypothesis.
virtual int GetDim () const
SMESH_Gen * GetGen () const
char * GetLastParameters () const
virtual const char * GetLibName () const
SMESH_Mesh * GetMeshByPersistentID (int id)
Find a mesh with given persistent ID.
char * GetParameters () const
virtual int GetShapeType () const
int GetStudyId () const
virtual bool IsAuxiliary () const
Return true if me is an auxiliary hypothesis.
virtual void NotifySubMeshesHypothesisModification ()
void SetLastParameters (const char *theParameters)
void SetLibName (const char *theLibName)
void SetParameters (const char *theParameters)
virtual bool SetParametersByDefaults (const TDefaults &dflts, const SMESH_Mesh *theMesh=0)=0
Initialize my parameter values by default parameters.
virtual bool SetParametersByMesh (const SMESH_Mesh *theMesh, const TopoDS_Shape &theShape)=0
Initialize my parameter values by the mesh built on the geometry.
SMESH_Hypothesis (int hypId, int studyId, SMESH_Gen *gen)
virtual ~SMESH_Hypothesis ()
Public Member Functions inherited from SMESHDS_Hypothesis
int GetID () const
const char * GetName () const
int GetType () const
bool IsSameName (const SMESHDS_Hypothesis &other) const
Compare types of hypotheses.
virtual std::istream & LoadFrom (std::istream &load)=0
bool operator!= (const SMESHDS_Hypothesis &other) const
virtual bool operator== (const SMESHDS_Hypothesis &other) const
virtual std::ostream & SaveTo (std::ostream &save)=0
SMESHDS_Hypothesis (int hypId)
virtual ~SMESHDS_Hypothesis ()
Static Public Member Functions
static SMESH_ComputeErrorPtr CheckHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, Hypothesis_Status &aStatus)
Checks compatibility of assigned StdMeshers_ViscousLayers2D hypotheses.
static SMESH_ProxyMesh::Ptr Compute (SMESH_Mesh &theMesh, const TopoDS_Face &theShape)
Computes temporary 2D mesh to be used by 2D algorithm. Return SMESH_ProxyMesh for the given FACE, or NULL in case of error.
static const char * GetHypType ()
Static Public Member Functions inherited from StdMeshers_ViscousLayers
static SMESH_ComputeErrorPtr CheckHypothesis (SMESH_Mesh &aMesh, const TopoDS_Shape &aShape, SMESH_Hypothesis::Hypothesis_Status &aStatus)
static const char * GetHypType ()
Static Public Member Functions inherited from SMESH_Hypothesis
static bool IsStatusFatal (Hypothesis_Status theStatus)
Additional Inherited Members
Public Types inherited from StdMeshers_ViscousLayers
enum ExtrusionMethod { SURF_OFFSET_SMOOTH , FACE_OFFSET , NODE_OFFSET }
Public Types inherited from SMESH_Hypothesis
enum Hypothesis_Status {
HYP_OK = 0 , HYP_MISSING , HYP_CONCURENT , HYP_BAD_PARAMETER ,
HYP_HIDDEN_ALGO , HYP_HIDING_ALGO , HYP_UNKNOWN_FATAL , HYP_INCOMPATIBLE ,
HYP_NOTCONFORM , HYP_ALREADY_EXIST , HYP_BAD_DIM , HYP_BAD_SUBSHAPE ,
HYP_BAD_GEOMETRY , HYP_NEED_SHAPE , HYP_INCOMPAT_HYPS
}
Public Types inherited from SMESHDS_Hypothesis
enum hypothesis_type {
PARAM_ALGO , ALGO_0D , ALGO_1D , ALGO_2D ,
ALGO_3D
}
Detailed Description
Hypothesis defining parameters of viscous layers.
Constructor & Destructor Documentation
StdMeshers_ViscousLayers2D()
StdMeshers_ViscousLayers2D::StdMeshers_ViscousLayers2D (int hypId, int studyId, SMESH_Gen * gen)
References GetHypType().
Member Function Documentation
CheckHypothesis()
SMESH_ComputeErrorPtr StdMeshers_ViscousLayers2D::CheckHypothesis (SMESH_Mesh & aMesh, const TopoDS_Shape & aShape, SMESH_Hypothesis::Hypothesis_Status & theStatus) static
Checks compatibility of assigned StdMeshers_ViscousLayers2D hypotheses.
References VISCOUS_2D::findHyps(), VISCOUS_2D::_ViscousBuilder2D::GetError(), StdMeshers_FaceSide::GetFaceWires(), SMESH_Hypothesis::HYP_INCOMPAT_HYPS, SMESH_Hypothesis::HYP_OK, and SMESH_ComputeError::New().
Referenced by NETGENPlugin_NETGEN_2D_ONLY::CheckHypothesis(), StdMeshers_Quadrangle_2D::CheckHypothesis(), NETGENPlugin_NETGEN_2D::CheckHypothesis(), and StdMeshers_MEFISTO_2D::CheckHypothesis().
Compute()
SMESH_ProxyMesh::Ptr StdMeshers_ViscousLayers2D::Compute (SMESH_Mesh & theMesh, const TopoDS_Face & theShape) static
Computes temporary 2D mesh to be used by 2D algorithm. Return SMESH_ProxyMesh for the given FACE, or NULL in case of error.
References VISCOUS_2D::_ViscousBuilder2D::Compute(), VISCOUS_2D::findHyps(), SMESH_subMesh::GetComputeError(), VISCOUS_2D::_ViscousBuilder2D::GetError(), and SMESH_Mesh::GetSubMesh().
Referenced by NETGENPlugin_Mesher::Compute(), NETGENPlugin_NETGEN_2D_ONLY::Compute(), StdMeshers_MEFISTO_2D::Compute(), StdMeshers_PolygonPerFace_2D::Compute(), and StdMeshers_Quadrangle_2D::Compute().
GetHypType()
static const char * StdMeshers_ViscousLayers2D::GetHypType () static
Referenced by NETGENPlugin_NETGEN_2D_ONLY::CheckHypothesis(), NETGENPlugin_NETGEN_2D::CheckHypothesis(), VISCOUS_2D::findHyps(), NETGENPlugin_NETGEN_2D::NETGENPlugin_NETGEN_2D(), and StdMeshers_ViscousLayers2D().
RestoreListeners()
void StdMeshers_ViscousLayers2D::RestoreListeners () const
At study restoration, restore event listeners used to clear an inferior dim sub-mesh modified by viscous layers.
References DraftVecUtils::find(), SMESH_Mesh::GetMeshDS(), SMESH_Mesh::GetSubMesh(), SMESH_Mesh::HasShapeToMesh(), SMESHDS_Mesh::IsUsedHypothesis(), studyContextStruct::mapMesh, and VISCOUS_3D::ToClearSubWithMain().
SetParametersByDefaults()
virtual bool StdMeshers_ViscousLayers2D::SetParametersByDefaults (const TDefaults & dflts, const SMESH_Mesh * theMesh = 0) virtual
Initialize my parameter values by default parameters.
Return values
bool - true if parameter values have been successfully defined
Reimplemented from StdMeshers_ViscousLayers.
SetParametersByMesh()
bool StdMeshers_ViscousLayers2D::SetParametersByMesh (const SMESH_Mesh * theMesh, const TopoDS_Shape & theShape) virtual
Initialize my parameter values by the mesh built on the geometry.
Parameters
theMesh - the built mesh
theShape - the geometry of interest
Return values
bool - true if parameter values have been successfully defined
Just return false as this hypothesis does not have parameters values
Reimplemented from StdMeshers_ViscousLayers.
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/StdMeshers_ViscousLayers2D.hxx
FreeCAD/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_ViscousLayers2D.cpp