FreeCAD: MeshCore::MeshEvalDeformedFacets Class Reference
MeshCore::MeshEvalDeformedFacets Class Reference
The MeshEvalDeformedFacets class searches for deformed facets.
#include <Degeneration.h>
Public Member Functions
bool Evaluate ()
Searches deformed facets.
std::vector< FacetIndex > GetIndices () const
Returns the indices of deformed facets.
MeshEvalDeformedFacets (const MeshKernel &rclM, float fMinAngle, float fMaxAngle)
Construction.
~MeshEvalDeformedFacets ()
Destruction.
Public Member Functions inherited from MeshCore::MeshEvaluation
virtual bool Evaluate ()=0
Evaluates the mesh kernel with respect to certain criteria.
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()
Detailed Description
The MeshEvalDeformedFacets class searches for deformed facets.
A facet is regarded as deformed if an angle is < 30 deg or > 120 deg.
See also
MeshFixDegeneratedFacets
Author
Werner Mayer
Constructor & Destructor Documentation
MeshEvalDeformedFacets()
MeshCore::MeshEvalDeformedFacets::MeshEvalDeformedFacets (const MeshKernel & rclM, float fMinAngle, float fMaxAngle)
Construction.
~MeshEvalDeformedFacets()
MeshCore::MeshEvalDeformedFacets::~MeshEvalDeformedFacets ()
Destruction.
Member Function Documentation
Evaluate()
bool MeshEvalDeformedFacets::Evaluate () virtual
Searches deformed facets.
Implements MeshCore::MeshEvaluation.
References MeshCore::MeshFacetIterator::Init(), MeshCore::MeshGeomFacet::IsDeformed(), MeshCore::MeshFacetIterator::More(), and MeshCore::MeshFacetIterator::Next().
GetIndices()
std::vector< FacetIndex > MeshEvalDeformedFacets::GetIndices () const
Returns the indices of deformed facets.
References MeshCore::MeshFacetIterator::Init(), MeshCore::MeshGeomFacet::IsDeformed(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), and MeshCore::MeshFacetIterator::Position().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/Core/Degeneration.h
FreeCAD/src/Mod/Mesh/App/Core/Degeneration.cpp