FreeCAD: StartGui::Workbench Class Reference
StartGui::Workbench Class Reference
#include <Workbench.h>
Public Member Functions
virtual void activated ()
Run some actions when the workbench gets activated.
virtual void setupContextMenu (const char *recipient, Gui::MenuItem *) const
Defines the standard context menu.
Workbench ()
virtual ~Workbench ()
Public Member Functions inherited from Gui::StdWorkbench
virtual void createMainWindowPopupMenu (MenuItem *) const
Sets up the contextmenu for the main window for this workbench.
StdWorkbench ()
virtual ~StdWorkbench ()
Public Member Functions inherited from Gui::Workbench
bool activate ()
Activates the workbench and adds/removes GUI elements.
void addTaskWatcher (const std::vector< Gui::TaskView::TaskWatcher * > &Watcher)
helper to add TaskWatcher to the TaskView
virtual void deactivated ()
Run some actions when the workbench gets deactivated.
PyObject * getPyObject ()
The default implementation returns an instance of WorkbenchPy.
std::list< std::pair< std::string, std::list< std::string > > > getToolbarItems () const
Shows a list of all toolbars and their commands.
std::list< std::string > listCommandbars () const
std::list< std::string > listMenus () const
std::list< std::string > listToolbars () const
std::string name () const
Returns the name of the workbench object.
void removeTaskWatcher (void)
remove the added TaskWatcher
void retranslate () const
Translates the window titles of all menus, toolbars and dock windows.
void setName (const std::string &)
Set the name to the workbench object.
Workbench ()
Constructs a workbench object.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual Type getTypeId (void) const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static void loadStartPage ()
Static Public Member Functions inherited from Gui::Workbench
static void createLinkMenu (MenuItem *)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Protected Member Functions
virtual Gui::ToolBarItem * setupCommandBars () const
Defines the standard command bars.
virtual Gui::DockWindowItems * setupDockWindows () const
Returns a DockWindowItems structure of dock windows this workbench.
virtual Gui::MenuItem * setupMenuBar () const
Defines the standard menus.
virtual Gui::ToolBarItem * setupToolBars () const
Defines the standard toolbars.
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Author
Werner Mayer
Constructor & Destructor Documentation
Workbench()
Workbench::Workbench ()
~Workbench()
Workbench::~Workbench () virtual
Reimplemented from Gui::Workbench.
Member Function Documentation
activated()
void Workbench::activated () virtual
Run some actions when the workbench gets activated.
Reimplemented from Gui::Workbench.
loadStartPage()
void Workbench::loadStartPage () static
References Base::Console(), Base::ConsoleSingleton::Error(), Base::Tools::escapedUnicodeFromUtf8(), Gui::getMainWindow(), Base::Interpreter(), Base::InterpreterSingleton::runString(), draftutils.translate::translate(), and Gui::MainWindow::windows().
setupCommandBars()
Gui::ToolBarItem * Workbench::setupCommandBars () const protected virtual
Defines the standard command bars.
Reimplemented from Gui::StdWorkbench.
setupContextMenu()
void Workbench::setupContextMenu (const char * recipient, Gui::MenuItem * item) const virtual
Defines the standard context menu.
Reimplemented from Gui::StdWorkbench.
setupDockWindows()
Gui::DockWindowItems * Workbench::setupDockWindows () const protected virtual
Returns a DockWindowItems structure of dock windows this workbench.
Reimplemented from Gui::StdWorkbench.
References Gui::StdWorkbench::setupDockWindows(), and Gui::DockWindowItems::setVisibility().
setupMenuBar()
Gui::MenuItem * Workbench::setupMenuBar () const protected virtual
Defines the standard menus.
Reimplemented from Gui::StdWorkbench.
References Gui::StdWorkbench::setupMenuBar().
setupToolBars()
Gui::ToolBarItem * Workbench::setupToolBars () const protected virtual
Defines the standard toolbars.
Reimplemented from Gui::StdWorkbench.
References Gui::ToolBarItem::setCommand().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Start/Gui/Workbench.h
Sources/FreeCAD/src/Mod/Start/Gui/Workbench.cpp