FreeCAD: TechDrawGui Namespace Reference
TechDrawGui Namespace Reference
Namespaces
namespace Ui
Classes
struct dimVertex
class DlgPageChooser
class DlgPrefsTechDrawAdvancedImp
class DlgPrefsTechDrawAnnotationImp
class DlgPrefsTechDrawColorsImp
class DlgPrefsTechDrawDimensionsImp
class DlgPrefsTechDrawGeneralImp
class DlgPrefsTechDrawHLRImp
class DlgPrefsTechDrawScaleImp
class DlgTemplateField
class DrawGuiUtil
Convenient utility functions for TechDraw Gui Module.
class Grabber3d
Utility functions for obtaining 3d window image.
class KeyCombination
class lineAttributes
class MDIViewPage
class MDIViewPagePy
class Module
class PreferencesGui
class QGCustomBorder
class QGCustomClip
class QGCustomImage
class QGCustomLabel
class QGCustomRect
class QGCustomSvg
class QGCustomText
class QGDisplayArea
class QGEPath
class QGIArrow
class QGIBalloonLabel
class QGICaption
class QGICenterLine
class QGICMark
class QGIDatumLabel
class QGIDecoration
class QGIDimLines
class QGIDrawingTemplate
class QGIEdge
class QGIFace
class QGIGhostHighlight
class QGIHighlight
class QGILeaderLine
class QGIMatting
class QGIPrimPath
class QGIProjGroup
class QGIRichAnno
class QGISectionLine
class QGISVGTemplate
class QGITemplate
class QGITile
class QGIVertex
class QGIView
class QGIViewAnnotation
class QGIViewBalloon
class QGIViewClip
class QGIViewCollection
class QGIViewDimension
class QGIViewImage
class QGIViewPart
class QGIViewSection
class QGIViewSpreadsheet
class QGIViewSymbol
class QGIWeldSymbol
class QGMarker
class QGMText
class QGSPage
class QGTracker
class QGVNavStyle
class QGVNavStyleBlender
class QGVNavStyleCAD
class QGVNavStyleGesture
class QGVNavStyleInventor
class QGVNavStyleMaya
class QGVNavStyleOCC
class QGVNavStyleOpenSCAD
class QGVNavStyleRevit
class QGVNavStyleTinkerCAD
class QGVNavStyleTouchpad
class QGVPage
class Rez
Functions to handle mm resolution conversion.
class SymbolChooser
class TaskActiveView
class TaskAlignViews
class TaskBalloon
class TaskCenterLine
class TaskCosmeticLine
class TaskCosVertex
class TaskCustomizeFormat
class TaskDetail
class TaskDimension
class TaskDlgActiveView
class TaskDlgAlignViews
class TaskDlgBalloon
class TaskDlgCenterLine
class TaskDlgCosmeticLine
class TaskDlgCosVertex
class TaskDlgCustomizeFormat
class TaskDlgDetail
class TaskDlgDimension
class TaskDlgGeomHatch
class TaskDlgHatch
class TaskDlgLeaderLine
class TaskDlgLineDecor
class TaskDlgLinkDim
class TaskDlgProjection
class TaskDlgProjGroup
Simulation dialog for the TaskView.
class TaskDlgRichAnno
class TaskDlgSectionView
class TaskDlgSelectLineAttributes
class TaskDlgWeldingSymbol
class TaskGeomHatch
class TaskHatch
class TaskLeaderLine
class TaskLineDecor
class TaskLinkDim
class TaskProjection
class TaskProjGroup
class TaskRestoreLines
class TaskRichAnno
class TaskSectionView
class TaskSelectLineAttributes
class TaskWeldingSymbol
class TemplateTextField
QGraphicsRectItem-derived class for the text fields in title blocks.
class TileImage
class Ui_DlgPageChooser
class Ui_DlgPrefsTechDrawAdvancedImp
class Ui_DlgPrefsTechDrawAnnotationImp
class Ui_DlgPrefsTechDrawColorsImp
class Ui_DlgPrefsTechDrawDimensionsImp
class Ui_DlgPrefsTechDrawGeneralImp
class Ui_DlgPrefsTechDrawHLRImp
class Ui_DlgPrefsTechDrawScaleImp
class Ui_dlgTemplateField
class Ui_SymbolChooser
class Ui_TaskAlignViews
class Ui_TaskBalloon
class Ui_TaskCenterLine
class Ui_TaskCosmeticLine
class Ui_TaskCosVertex
class Ui_TaskCustomizeFormat
class Ui_TaskDetail
class Ui_TaskDimension
class Ui_TaskGeomHatch
class Ui_TaskHatch
class Ui_TaskLeaderLine
class Ui_TaskLineDecor
class Ui_TaskLinkDim
class Ui_TaskProjection
class Ui_TaskProjGroup
class Ui_TaskRestoreLines
class Ui_TaskRichAnno
class Ui_TaskSectionView
class Ui_TaskSelectLineAttributes
class ViewProviderAnnotation
class ViewProviderArch
class ViewProviderBalloon
class ViewProviderCosmeticExtension
class ViewProviderDimension
class ViewProviderDraft
class ViewProviderDrawingView
class ViewProviderGeomHatch
class ViewProviderHatch
class ViewProviderImage
class ViewProviderLeader
class ViewProviderPage
class ViewProviderProjGroup
class ViewProviderProjGroupItem
class ViewProviderRichAnno
class ViewProviderSpreadsheet
class ViewProviderSymbol
class ViewProviderTemplate
class ViewProviderTile
class ViewProviderViewClip
class ViewProviderViewPart
class ViewProviderViewSection
class ViewProviderWeld
class Workbench
Typedefs
typedef Gui::ViewProviderExtensionPythonT< TechDrawGui::ViewProviderCosmeticExtension > ViewProviderCosmeticExtensionPython
Functions
void execHoleCircle (Gui::Command *cmd)
PyObject * initModule ()
Variables
struct {
} sortX
struct {
} sortY
const std::string SVGCOLDEFAULT = "#000000"
const double SVGSIZEH = 64.0
const double SVGSIZEW = 64.0
Typedef Documentation
ViewProviderCosmeticExtensionPython
typedef Gui::ViewProviderExtensionPythonT<TechDrawGui::ViewProviderCosmeticExtension> TechDrawGui::ViewProviderCosmeticExtensionPython
Function Documentation
execHoleCircle()
void TechDrawGui::execHoleCircle (Gui::Command * cmd)
References TechDraw::CosmeticExtension::addCosmeticEdge(), TechDraw::ARCOFCIRCLE, TechDraw::CIRCLE, Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), TechDraw::CosmeticExtension::getCosmeticEdge(), TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), Gui::getMainWindow(), TechDraw::DrawView::getScale(), Gui::Command::getSelection(), Gui::Command::openCommand(), draftutils.translate::QT_TRANSLATE_NOOP, TechDraw::DrawViewPart::refreshCEGeoms(), TechDraw::DrawView::requestPaint(), and Base::Vector3< _Precision >::y.
initModule()
PyObject * TechDrawGui::initModule ()
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().
Variable Documentation
struct { ... } TechDrawGui::sortX
struct { ... } TechDrawGui::sortY
SVGCOLDEFAULT
const std::string TechDrawGui::SVGCOLDEFAULT = "#000000"
Referenced by TechDrawGui::QGIFace::buildPixHatch(), TechDrawGui::QGIFace::buildSvgHatch(), and TechDrawGui::QGIFace::QGIFace().
SVGSIZEH
const double TechDrawGui::SVGSIZEH = 64.0
Referenced by TechDrawGui::QGIFace::buildPixHatch(), and TechDrawGui::QGIFace::buildSvgHatch().
SVGSIZEW
const double TechDrawGui::SVGSIZEW = 64.0
Referenced by TechDrawGui::QGIFace::buildPixHatch(), and TechDrawGui::QGIFace::buildSvgHatch().