FreeCAD: SMESH::Controls::FreeEdges Class Reference
SMESH::Controls::FreeEdges Class Reference
#include <SMESH_ControlsDef.hxx>
Classes
struct Border
Public Types
typedef std::set< Border > TBorders
typedef long TElemId
Public Member Functions
FreeEdges ()
void GetBoreders (TBorders &theBorders)
virtual SMDSAbs_ElementType GetType () const
virtual bool IsSatisfy (long theElementId)
virtual void SetMesh (const SMDS_Mesh *theMesh)
Public Member Functions inherited from SMESH::Controls::Functor
~Functor ()
Static Public Member Functions
static bool IsFreeEdge (const SMDS_MeshNode **theNodes, const int theFaceId)
Protected Attributes
const SMDS_Mesh * myMesh
Member Typedef Documentation
TBorders
typedef std::set<Border> SMESH::Controls::FreeEdges::TBorders
TElemId
typedef long SMESH::Controls::FreeEdges::TElemId
Constructor & Destructor Documentation
FreeEdges()
FreeEdges::FreeEdges ()
References SMESH::Controls::NumericalFunctor::myMesh.
Member Function Documentation
GetBoreders()
void FreeEdges::GetBoreders (TBorders & theBorders)
References SMDS_Mesh::facesIterator(), SMDS_MeshElement::GetID(), SMDS_MeshElement::IsQuadratic(), myMesh, and SMDS_MeshElement::nodesIterator().
GetType()
SMDSAbs_ElementType FreeEdges::GetType () const virtual
Implements SMESH::Controls::Predicate.
IsFreeEdge()
bool FreeEdges::IsFreeEdge (const SMDS_MeshNode ** theNodes, const int theFaceId) static
References SMDS_MeshElement::GetID(), and SMDS_MeshNode::GetInverseElementIterator().
IsSatisfy()
bool FreeEdges::IsSatisfy (long theElementId) virtual
Implements SMESH::Controls::Predicate.
References SMDS_Mesh::FindElement(), SMDS_MeshElement::GetType(), SMDS_MeshElement::interlacedNodesIterator(), SMESH::Controls::NumericalFunctor::myMesh, and SMDS_MeshElement::NbNodes().
SetMesh()
void FreeEdges::SetMesh (const SMDS_Mesh * theMesh) virtual
Implements SMESH::Controls::Functor.
References SMESH::Controls::NumericalFunctor::myMesh.
Member Data Documentation
myMesh
const SMDS_Mesh* SMESH::Controls::FreeEdges::myMesh protected
Referenced by SMESH::Controls::ElemGeomType::ElemGeomType(), SMESH::Controls::FreeFaces::FreeFaces(), SMESH::Controls::FreeNodes::FreeNodes(), GetBoreders(), SMESH::Controls::FreeFaces::IsSatisfy(), SMESH::Controls::LinearOrQuadratic::IsSatisfy(), SMESH::Controls::ElemGeomType::IsSatisfy(), SMESH::Controls::FreeNodes::IsSatisfy(), SMESH::Controls::LinearOrQuadratic::LinearOrQuadratic(), SMESH::Controls::FreeNodes::SetMesh(), SMESH::Controls::FreeFaces::SetMesh(), SMESH::Controls::LinearOrQuadratic::SetMesh(), and SMESH::Controls::ElemGeomType::SetMesh().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp