FreeCAD: Fem::StdMeshers_LocalLengthPy Class Reference
Fem::StdMeshers_LocalLengthPy Class Reference
#include <HypothesisPy.h>
Public Member Functions
Py::Object getLength (const Py::Tuple &args)
Py::Object getPrecision (const Py::Tuple &args)
Py::Object setLength (const Py::Tuple &args)
Py::Object setPrecision (const Py::Tuple &args)
StdMeshers_LocalLengthPy (int hypId, int studyId, SMESH_Gen *gen)
~StdMeshers_LocalLengthPy ()
Public Member Functions inherited from Fem::SMESH_HypothesisPy< StdMeshers_LocalLengthPy >
Py::Object clearParameters (const Py::Tuple &args)
Py::Object getattr (const char *name)
boost::shared_ptr< SMESH_Hypothesis > getHypothesis () const
Py::Object getLastParameters (const Py::Tuple &args)
Py::Object getLibName (const Py::Tuple &args)
Py::Object getParameters (const Py::Tuple &args)
Py::Object isAuxiliary (const Py::Tuple &args)
Py::Object repr ()
Py::Object setLastParameters (const Py::Tuple &args)
Py::Object setLibName (const Py::Tuple &args)
Py::Object setParameters (const Py::Tuple &args)
Py::Object setParametersByMesh (const Py::Tuple &args)
SMESH_HypothesisPy (SMESH_Hypothesis *)
virtual ~SMESH_HypothesisPy ()
Static Public Member Functions
static void init_type (PyObject *)
Static Public Member Functions inherited from Fem::SMESH_HypothesisPy< StdMeshers_LocalLengthPy >
static void init_type (PyObject *)
Additional Inherited Members
Public Types inherited from Fem::SMESH_HypothesisPy< StdMeshers_LocalLengthPy >
typedef SMESH_HypothesisPy< StdMeshers_LocalLengthPy > SMESH_HypothesisPyBase
Protected Member Functions inherited from Fem::SMESH_HypothesisPy< StdMeshers_LocalLengthPy >
type * hypothesis () const
Constructor & Destructor Documentation
StdMeshers_LocalLengthPy()
StdMeshers_LocalLengthPy::StdMeshers_LocalLengthPy (int hypId, int studyId, SMESH_Gen * gen)
~StdMeshers_LocalLengthPy()
StdMeshers_LocalLengthPy::~StdMeshers_LocalLengthPy ()
Member Function Documentation
getLength()
Py::Object StdMeshers_LocalLengthPy::getLength (const Py::Tuple & args)
Referenced by init_type().
getPrecision()
Py::Object StdMeshers_LocalLengthPy::getPrecision (const Py::Tuple & args)
Referenced by init_type().
init_type()
void StdMeshers_LocalLengthPy::init_type (PyObject * module) static
References getLength(), getPrecision(), Fem::SMESH_HypothesisPy< StdMeshers_LocalLengthPy >::init_type(), setLength(), and setPrecision().
setLength()
Py::Object StdMeshers_LocalLengthPy::setLength (const Py::Tuple & args)
Referenced by init_type().
setPrecision()
Py::Object StdMeshers_LocalLengthPy::setPrecision (const Py::Tuple & args)
Referenced by init_type().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Fem/App/HypothesisPy.h
Sources/FreeCAD/src/Mod/Fem/App/HypothesisPy.cpp