FreeCAD: SpreadsheetGui::DlgSheetConf Class Reference
SpreadsheetGui::DlgSheetConf Class Reference
#include <DlgSheetConf.h>
Public Slots
void onDiscard ()
Public Member Functions
void accept ()
DlgSheetConf (Spreadsheet::Sheet *sheet, App::Range range, QWidget *parent=nullptr)
App::Property * prepare (App::CellAddress &from, App::CellAddress &to, std::string &rangeConf, App::ObjectIdentifier &path, bool init)
~DlgSheetConf ()
Constructor & Destructor Documentation
DlgSheetConf()
DlgSheetConf::DlgSheetConf (Spreadsheet::Sheet * sheet, App::Range range, QWidget * parent = nullptr) explicit
References Ui_DlgSheetConf::btnDiscard, draftgeoutils.intersections::connect(), Ui_DlgSheetConf::lineEditEnd, Ui_DlgSheetConf::lineEditGroup, Ui_DlgSheetConf::lineEditProp, Ui_DlgSheetConf::lineEditStart, onDiscard(), prepare(), Gui::ExpressionLineEdit::setDocumentObject(), Ui_DlgSheetConf::setupUi(), and App::CellAddress::toString().
~DlgSheetConf()
DlgSheetConf::~DlgSheetConf ()
Member Function Documentation
accept()
void DlgSheetConf::accept (void)
References Gui::Command::abortCommand(), Gui::cmdAppObjectArgs(), App::CellAddress::col(), Gui::Command::commitCommand(), App::Property::CopyOnChange, Gui::Command::Doc, Spreadsheet::Sheet::getCell(), Spreadsheet::Sheet::getCellBinding(), Base::BaseClass::getClassTypeId(), App::Property::getFullName(), App::DocumentObject::getFullName(), Spreadsheet::Sheet::getRange(), Ui_DlgSheetConf::lineEditGroup, Ui_DlgSheetConf::lineEditProp, App::Expression::parse(), prepare(), App::CellAddress::row(), App::Property::setStatus(), and App::CellAddress::toString().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
onDiscard
void DlgSheetConf::onDiscard () slot
References Gui::Command::abortCommand(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Gui::Command::Doc, Spreadsheet::Sheet::getCellBinding(), prepare(), and App::CellAddress::toString().
Referenced by DlgSheetConf().
prepare()
App::Property * DlgSheetConf::prepare (App::CellAddress & from, App::CellAddress & to, std::string & rangeConf, App::ObjectIdentifier & path, bool init)
References App::CellAddress::col(), Spreadsheet::Sheet::getCell(), Spreadsheet::Sheet::getCellAddress(), Base::BaseClass::getClassTypeId(), Base::Persistence::getClassTypeId(), Spreadsheet::Cell::getExpression(), draftfunctions.svgshapes::getPath(), Ui_DlgSheetConf::lineEditEnd, Ui_DlgSheetConf::lineEditProp, Ui_DlgSheetConf::lineEditStart, App::Expression::parse(), App::Property::PropDynamic, App::CellAddress::row(), App::CellAddress::setRow(), and App::CellAddress::toString().
Referenced by accept(), DlgSheetConf(), onDiscard(), and femsolver.run.Machine::reset().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Spreadsheet/Gui/DlgSheetConf.h
FreeCAD/src/Mod/Spreadsheet/Gui/DlgSheetConf.cpp