FreeCAD: TechDrawGui::QGIEdge Class Reference
TechDrawGui::QGIEdge Class Reference
#include <QGIEdge.h>
Public Types
enum { Type = QGraphicsItem::UserType + 103 }
Public Types inherited from TechDrawGui::QGIPrimPath
enum { Type = QGraphicsItem::UserType + 170 }
Public Member Functions
virtual QRectF boundingRect () const override
double getEdgeFuzz (void) const
bool getHiddenEdge ()
int getProjIndex () const
bool getSmoothEdge ()
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0) override
QGIEdge (int index)
void setCosmetic (bool state)
void setHiddenEdge (bool b)
virtual void setPrettyNormal () override
void setSmoothEdge (bool b)
virtual QPainterPath shape () const override
int type () const override
~QGIEdge ()
Public Member Functions inherited from TechDrawGui::QGIPrimPath
QColor getFillColor (void)
Qt::BrushStyle getFillStyle ()
Qt::PenStyle getStyle ()
virtual double getWidth ()
QGIPrimPath ()
void resetFill ()
virtual void setCapStyle (Qt::PenCapStyle c)
void setFill (QBrush b)
void setFill (QColor c, Qt::BrushStyle s)
void setFillColor (QColor c)
void setFillOverride (bool b)
void setFillStyle (Qt::BrushStyle f)
void setHighlighted (bool state)
virtual void setNormalColor (QColor c)
virtual void setPrettyPre ()
virtual void setPrettySel ()
void setStyle (int s)
void setStyle (Qt::PenStyle s)
virtual void setWidth (double w)
int type () const override
~QGIPrimPath ()
Protected Member Functions
QColor getHiddenColor ()
Qt::PenStyle getHiddenStyle ()
Protected Member Functions inherited from TechDrawGui::QGIPrimPath
virtual QColor getNormalColor (void)
Base::Reference< ParameterGrp > getParmGroup (void)
virtual QColor getPreColor (void)
virtual QColor getSelectColor (void)
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) override
virtual Qt::PenCapStyle prefCapStyle (void)
Protected Attributes
bool isCosmetic
bool isHiddenEdge
bool isSmoothEdge
int projIndex
Protected Attributes inherited from TechDrawGui::QGIPrimPath
bool isHighlighted
QBrush m_brush
Qt::PenCapStyle m_capStyle
QColor m_colCurrent
QColor m_colDefFill
QColor m_colNormal
QColor m_colNormalFill
bool m_colOverride
QColor m_fillColorCurrent
bool m_fillOverride
Qt::BrushStyle m_fillStyleCurrent
QPen m_pen
Qt::PenStyle m_styleCurrent
Qt::BrushStyle m_styleDef
Qt::BrushStyle m_styleNormal
Qt::BrushStyle m_styleSelect
double m_width
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGIEdge()
QGIEdge::QGIEdge (int index) explicit
References isCosmetic, TechDrawGui::QGIPrimPath::m_width, setCosmetic(), and TechDrawGui::QGIPrimPath::setFill().
~QGIEdge()
TechDrawGui::QGIEdge::~QGIEdge ()
Member Function Documentation
boundingRect()
QRectF QGIEdge::boundingRect () const override virtual
References shape().
getEdgeFuzz()
double QGIEdge::getEdgeFuzz (void) const
References TechDrawGui::PreferencesGui::edgeFuzz().
Referenced by shape().
getHiddenColor()
QColor QGIEdge::getHiddenColor () protected
References App::Color::asValue(), App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetUnsigned(), and App::Application::GetUserParameter().
Referenced by setPrettyNormal().
getHiddenEdge()
bool TechDrawGui::QGIEdge::getHiddenEdge ()
getHiddenStyle()
Qt::PenStyle QGIEdge::getHiddenStyle () protected
References App::GetApplication(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), and App::Application::GetUserParameter().
Referenced by setHiddenEdge().
getProjIndex()
int TechDrawGui::QGIEdge::getProjIndex () const
Referenced by TechDrawGui::MDIViewPage::preSelectionChanged(), and TechDrawGui::MDIViewPage::setTreeToSceneSelect().
getSmoothEdge()
bool TechDrawGui::QGIEdge::getSmoothEdge ()
paint()
void QGIEdge::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) override virtual
Reimplemented from TechDrawGui::QGIPrimPath.
References TechDrawGui::QGIPrimPath::paint().
setCosmetic()
void QGIEdge::setCosmetic (bool state)
References isCosmetic, and TechDrawGui::QGIPrimPath::setWidth().
Referenced by QGIEdge(), and TechDrawGui::QGIViewPart::toggleCosmeticLines().
setHiddenEdge()
void QGIEdge::setHiddenEdge (bool b)
References getHiddenStyle(), isHiddenEdge, and TechDrawGui::QGIPrimPath::m_styleCurrent.
Referenced by TechDrawGui::QGIViewPart::drawViewPart().
setPrettyNormal()
void QGIEdge::setPrettyNormal (void) override virtual
Reimplemented from TechDrawGui::QGIPrimPath.
References getHiddenColor(), TechDrawGui::QGIPrimPath::getNormalColor(), isHiddenEdge, and TechDrawGui::QGIPrimPath::m_colCurrent.
Referenced by TechDrawGui::QGIViewPart::drawViewPart().
setSmoothEdge()
void TechDrawGui::QGIEdge::setSmoothEdge (bool b)
shape()
QPainterPath QGIEdge::shape (void) const override virtual
Reimplemented from TechDrawGui::QGIPrimPath.
References getEdgeFuzz().
Referenced by draftguitools.gui_offset.Offset::action(), boundingRect(), PathScripts.PathSurfaceSupport.PathGeometryGenerator::generatePathGeometry(), and draftguitools.gui_offset.Offset::numericRadius().
type()
int TechDrawGui::QGIEdge::type (void) const override
Referenced by ArchProfile.ProfileTaskPanel::accept(), and ArchProfile.ProfileTaskPanel::retranslateUi().
Member Data Documentation
isCosmetic
bool TechDrawGui::QGIEdge::isCosmetic protected
Referenced by QGIEdge(), and setCosmetic().
isHiddenEdge
bool TechDrawGui::QGIEdge::isHiddenEdge protected
Referenced by setHiddenEdge(), and setPrettyNormal().
isSmoothEdge
bool TechDrawGui::QGIEdge::isSmoothEdge protected
projIndex
int TechDrawGui::QGIEdge::projIndex protected
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGIEdge.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGIEdge.cpp