FreeCAD: femexamples.square_pipe_end_twisted_edgeforces Namespace Reference
femexamples.square_pipe_end_twisted_edgeforces Namespace Reference
Functions
def get_explanation (header="")
def get_information ()
def setup (doc=None, solvertype="ccxtools")
Function Documentation
get_explanation()
def femexamples.square_pipe_end_twisted_edgeforces.get_explanation (header = "")
Referenced by femexamples.square_pipe_end_twisted_edgeforces.setup().
get_information()
def femexamples.square_pipe_end_twisted_edgeforces.get_information ()
Referenced by femexamples.square_pipe_end_twisted_edgeforces.setup().
setup()
def femexamples.square_pipe_end_twisted_edgeforces.setup (doc = None, solvertype = "ccxtools")
References femexamples.square_pipe_end_twisted_edgeforces.get_explanation(), femexamples.square_pipe_end_twisted_edgeforces.get_information(), ObjectsFem.makeAnalysis(), ObjectsFem.makeConstraintFixed(), ObjectsFem.makeConstraintForce(), ObjectsFem.makeElementGeometry2D(), ObjectsFem.makeMaterialSolid(), ObjectsFem.makeMeshGmsh(), ObjectsFem.makeSolverCalculix(), and ObjectsFem.makeSolverCalculixCcxTools().