FreeCAD: AttachmentEditor.Commands Namespace Reference
AttachmentEditor.Commands Namespace Reference
Classes
class CommandEditAttachment
Functions
def editAttachment (feature=None, take_selection=False, create_transaction=True, callback_OK=None, callback_Cancel=None, callback_Apply=None)
def QT_TRANSLATE_NOOP (ctx, msg)
Variables
command_instance = CommandEditAttachment()
Function Documentation
editAttachment()
def AttachmentEditor.Commands.editAttachment (feature = None, take_selection = False, create_transaction = True, callback_OK = None, callback_Cancel = None, callback_Apply = None)
Opens attachment editing dialog.
editAttachment(feature = None,
               take_selection = False,
               create_transaction = True,
               callback_OK = None,
               callback_Cancel = None,
               callback_Apply = None)
feature: object to attach/modify. If None is supplied, the object is taken from
selection.
take_selection: if True, current selection is filled into first references (but only
if object to be attached doesn't have any references already)
create_transaction = if False, no undo transaction operations will be done by the
dialog (consequently, canceling the dialog will not reset the feature to original
state).
callback_OK: function to be called upon OK. Invoked after writing values to feature,
committing transaction and closing the dialog.
callback_Cancel: called after closing the dialog and aborting transaction.
callback_Apply: invoked after writing values to feature.
References AttachmentEditor.Commands.editAttachment().
Referenced by AttachmentEditor.Commands.CommandEditAttachment.Activated(), and AttachmentEditor.Commands.editAttachment().
QT_TRANSLATE_NOOP()
def AttachmentEditor.Commands.QT_TRANSLATE_NOOP (ctx, msg)
Referenced by AttachmentEditor.Commands.CommandEditAttachment.GetResources().
Variable Documentation
command_instance
AttachmentEditor.Commands.command_instance = CommandEditAttachment()