FreeCAD: PartDesignGui::TaskFeaturePick Class Reference
PartDesignGui::TaskFeaturePick Class Reference
#include <TaskFeaturePick.h>
Public Types
enum featureStatus {
validFeature = 0 , invalidShape , noWire , isUsed ,
otherBody , otherPart , notInBody , basePlane ,
afterTip
}
Public Member Functions
std::vector< App::DocumentObject * > buildFeatures ()
std::vector< App::DocumentObject * > getFeatures ()
bool isSingleSelectionEnabled () const
void showExternal (bool val)
TaskFeaturePick (std::vector< App::DocumentObject * > &objects, const std::vector< featureStatus > &status, bool singleFeatureSelect, QWidget *parent=nullptr)
~TaskFeaturePick ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Public Member Functions inherited from Gui::DocumentObserver
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
Static Public Member Functions
static App::DocumentObject * makeCopy (App::DocumentObject *obj, std::string sub, bool independent)
Protected Slots
void onDoubleClick (QListWidgetItem *item)
void onItemSelectionChanged ()
void onSelectionChanged (const Gui::SelectionChanges &msg)
void onUpdate (bool)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Member Functions
virtual void slotDeletedObject (const Gui::ViewProviderDocumentObject &Obj)
Notifies when the object is about to be removed.
virtual void slotDeleteDocument (const Gui::Document &Doc)
Notifies on document deletion.
virtual void slotUndoDocument (const Gui::Document &Doc)
Notifies on undo.
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Member Enumeration Documentation
featureStatus
enum PartDesignGui::TaskFeaturePick::featureStatus
Enumerator
validFeature
invalidShape
noWire
isUsed
otherBody
otherPart
notInBody
basePlane
afterTip
Constructor & Destructor Documentation
TaskFeaturePick()
TaskFeaturePick::TaskFeaturePick (std::vector< App::DocumentObject * > & objects, const std::vector< featureStatus > & status, bool singleFeatureSelect, QWidget * parent = nullptr)
References Gui::DocumentObserver::attachDocument(), draftgeoutils.intersections::connect(), Base::Persistence::getClassTypeId(), App::Document::getName(), App::OriginFeature::getOrigin(), Gui::Application::getViewProvider(), QSint::ActionGroup::groupLayout(), Gui::Application::Instance, invalidShape, onDoubleClick(), onItemSelectionChanged(), onUpdate(), and Gui::ViewProviderOrigin::setTemporaryVisibility().
~TaskFeaturePick()
TaskFeaturePick::~TaskFeaturePick ()
Member Function Documentation
buildFeatures()
std::vector< App::DocumentObject * > TaskFeaturePick::buildFeatures ()
References Base::Console(), PartDesignGui::fixSketchSupport(), App::GetApplication(), PartDesignGui::getBody(), PartDesignGui::getBodyFor(), Base::Persistence::getClassTypeId(), App::Application::getDocument(), App::Document::getObject(), PartDesignGui::getPartFor(), makeCopy(), notInBody, otherBody, otherPart, and Base::ConsoleSingleton::Warning().
Referenced by PartDesignGui::TaskDlgFeaturePick::~TaskDlgFeaturePick().
getFeatures()
std::vector< App::DocumentObject * > TaskFeaturePick::getFeatures ()
References App::GetApplication().
Referenced by PartDesignGui::TaskDlgFeaturePick::accept().
isSingleSelectionEnabled()
bool TaskFeaturePick::isSingleSelectionEnabled () const
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by onSelectionChanged().
makeCopy()
App::DocumentObject * TaskFeaturePick::makeCopy (App::DocumentObject * obj, std::string sub, bool independent) static
References App::Document::addObject(), PartDesign::ShapeBinder::buildShapeFromReferences(), Sketcher::SketchObject::delConstraintsToExternal(), App::Application::getActiveDocument(), App::GetApplication(), Base::Persistence::getClassTypeId(), App::ExtensionContainer::getPropertyList(), Part::PropertyPartShape::getShape(), Part::TopoShape::getSubShape(), Part::PropertyPartShape::getValue(), Base::Type::isDerivedFrom(), Part::AttachExtension::MapMode, Attacher::mm0Vertex, Attacher::mm1TwoPoints, Attacher::mmDeactivated, Attacher::mmFlatFace, App::Property::Paste(), App::PropertyEnumeration::setValue(), Part::PropertyPartShape::setValue(), App::PropertyLinkSubList::setValue(), Part::Feature::Shape, and Part::AttachExtension::Support.
Referenced by PartDesignGui::TaskDlgDatumParameters::accept(), PartDesignGui::TaskPipeParameters::accept(), buildFeatures(), and PartDesignGui::getReferencedSelection().
onDoubleClick
void TaskFeaturePick::onDoubleClick (QListWidgetItem * item) protected slot
References Gui::SelectionSingleton::addSelection(), Gui::Control(), and Gui::Selection().
Referenced by TaskFeaturePick().
onItemSelectionChanged
void TaskFeaturePick::onItemSelectionChanged (void) protected slot
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), and Gui::Selection().
Referenced by TaskFeaturePick().
onSelectionChanged
void TaskFeaturePick::onSelectionChanged (const Gui::SelectionChanges & msg) protected slot
References Gui::SelectionChanges::AddSelection, Gui::Control(), draftutils.gui_utils::getSelection, isSingleSelectionEnabled(), and Gui::Selection().
onUpdate
void TaskFeaturePick::onUpdate (bool) protected slot
Referenced by TaskFeaturePick().
showExternal()
void TaskFeaturePick::showExternal (bool val)
Referenced by PartDesignGui::TaskDlgFeaturePick::showExternal().
slotDeletedObject()
void TaskFeaturePick::slotDeletedObject (const Gui::ViewProviderDocumentObject & Obj) protected virtual
Notifies when the object is about to be removed.
Reimplemented from Gui::DocumentObserver.
References DraftVecUtils::find().
slotDeleteDocument()
void TaskFeaturePick::slotDeleteDocument (const Gui::Document & Doc) protected virtual
Notifies on document deletion.
Reimplemented from Gui::DocumentObserver.
References Gui::Control().
slotUndoDocument()
void TaskFeaturePick::slotUndoDocument (const Gui::Document & Doc) protected virtual
Notifies on undo.
Reimplemented from Gui::DocumentObserver.
References Gui::Control().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/PartDesign/Gui/TaskFeaturePick.h
FreeCAD/src/Mod/PartDesign/Gui/TaskFeaturePick.cpp