FreeCAD: Gui::ExpressionLineEdit Class Reference
Gui::ExpressionLineEdit Class Reference
#include <ExpressionCompleter.h>
Public Slots
void slotCompleteText (const QString &completionPrefix)
void slotTextChanged (const QString &text)
Signals
void textChanged2 (QString text, int pos)
Public Member Functions
bool completerActive () const
ExpressionLineEdit (QWidget *parent=nullptr, bool noProperty=false, char checkPrefix=0, bool checkInList=true)
void hideCompleter ()
void setDocumentObject (const App::DocumentObject *currentDocObj, bool checkInList=true)
void setExactMatch (bool enabled=true)
void setNoProperty (bool enabled=true)
void setPrefix (char prefix)
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *event)
void keyPressEvent (QKeyEvent *event)
Constructor & Destructor Documentation
ExpressionLineEdit()
ExpressionLineEdit::ExpressionLineEdit (QWidget * parent = nullptr, bool noProperty = false, char checkPrefix = 0, bool checkInList = true)
References draftgeoutils.intersections::connect(), and slotTextChanged().
Member Function Documentation
completerActive()
bool ExpressionLineEdit::completerActive () const
Referenced by SpreadsheetGui::LineEdit::event(), Gui::Dialog::DlgExpressionInput::eventFilter(), and Gui::Dialog::DlgExpressionInput::mousePressEvent().
contextMenuEvent()
void ExpressionLineEdit::contextMenuEvent (QContextMenuEvent * event) protected
References setExactMatch().
hideCompleter()
void ExpressionLineEdit::hideCompleter ()
keyPressEvent()
void ExpressionLineEdit::keyPressEvent (QKeyEvent * event) protected
setDocumentObject()
void ExpressionLineEdit::setDocumentObject (const App::DocumentObject * currentDocObj, bool checkInList = true)
References draftgeoutils.intersections::connect(), Gui::ExpressionCompleter::setDocumentObject(), slotCompleteText(), and textChanged2().
Referenced by Gui::InputField::bind(), SpreadsheetGui::SheetView::confirmAliasChanged(), SpreadsheetGui::DlgBindSheet::DlgBindSheet(), Gui::Dialog::DlgExpressionInput::DlgExpressionInput(), SpreadsheetGui::DlgSheetConf::DlgSheetConf(), Gui::Dialog::DlgPropertyLink::init(), SpreadsheetGui::SheetView::updateAliasLine(), and SpreadsheetGui::SheetView::updateContentLine().
setExactMatch()
void ExpressionLineEdit::setExactMatch (bool enabled = true)
Referenced by contextMenuEvent(), and Gui::Dialog::DlgPropertyLink::DlgPropertyLink().
setNoProperty()
void ExpressionLineEdit::setNoProperty (bool enabled = true)
References Gui::ExpressionCompleter::setNoProperty().
Referenced by Gui::Dialog::DlgPropertyLink::DlgPropertyLink().
setPrefix()
void ExpressionLineEdit::setPrefix (char prefix)
Referenced by SpreadsheetGui::DlgBindSheet::DlgBindSheet().
slotCompleteText
void ExpressionLineEdit::slotCompleteText (const QString & completionPrefix) slot
References Gui::ExpressionCompleter::getPrefixRange(), and Gui::ExpressionCompleter::updatePrefixEnd().
Referenced by setDocumentObject().
slotTextChanged
void ExpressionLineEdit::slotTextChanged (const QString & text) slot
References textChanged2().
Referenced by ExpressionLineEdit().
textChanged2
void Gui::ExpressionLineEdit::textChanged2 (QString text, int pos) signal
Referenced by setDocumentObject(), and slotTextChanged().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/ExpressionCompleter.h
FreeCAD/src/Gui/ExpressionCompleter.cpp