FreeCAD: QDomNodeModel Class Reference
QDomNodeModel Class Reference
#include <QDomNodeModel.h>
Public Member Functions
QUrl baseUri (const QXmlNodeModelIndex &n) const
int childIndex (const QDomNode &) const
QXmlNodeModelIndex::DocumentOrder compareOrder (const QXmlNodeModelIndex &ni1, const QXmlNodeModelIndex &ni2) const
QUrl documentUri (const QXmlNodeModelIndex &n) const
QXmlNodeModelIndex elementById (const QXmlName &id) const
QXmlNodeModelIndex fromDomNode (const QDomNode &) const
QXmlNodeModelIndex::NodeKind kind (const QXmlNodeModelIndex &ni) const
QXmlName name (const QXmlNodeModelIndex &ni) const
QVector< QXmlName > namespaceBindings (const QXmlNodeModelIndex &n) const
QVector< QXmlNodeModelIndex > nodesByIdref (const QXmlName &idref) const
QVector< QDomNode > path (const QDomNode &) const
QDomNodeModel (QXmlNamePool, QDomDocument, bool parsedReadOnly=false)
QXmlNodeModelIndex root (const QXmlNodeModelIndex &n) const
QSourceLocation sourceLocation (const QXmlNodeModelIndex &index) const
QString stringValue (const QXmlNodeModelIndex &n) const
QDomNode toDomNode (const QXmlNodeModelIndex &) const
QVariant typedValue (const QXmlNodeModelIndex &node) const
Protected Member Functions
QVector< QXmlNodeModelIndex > attributes (const QXmlNodeModelIndex &element) const
QXmlNodeModelIndex nextFromSimpleAxis (SimpleAxis axis, const QXmlNodeModelIndex &origin) const
Constructor & Destructor Documentation
QDomNodeModel()
QDomNodeModel::QDomNodeModel (QXmlNamePool pool, QDomDocument doc, bool parsedReadOnly = false)
Member Function Documentation
attributes()
QVector< QXmlNodeModelIndex > QDomNodeModel::attributes (const QXmlNodeModelIndex & element) const protected
References fromDomNode(), and toDomNode().
baseUri()
QUrl QDomNodeModel::baseUri (const QXmlNodeModelIndex & n) const
childIndex()
int QDomNodeModel::childIndex (const QDomNode & n) const
compareOrder()
QXmlNodeModelIndex::DocumentOrder QDomNodeModel::compareOrder (const QXmlNodeModelIndex & ni1, const QXmlNodeModelIndex & ni2) const
References path(), and toDomNode().
documentUri()
QUrl QDomNodeModel::documentUri (const QXmlNodeModelIndex & n) const
elementById()
QXmlNodeModelIndex QDomNodeModel::elementById (const QXmlName & id) const
References fromDomNode().
fromDomNode()
QXmlNodeModelIndex QDomNodeModel::fromDomNode (const QDomNode & n) const
Referenced by attributes(), TechDrawGui::QGISVGTemplate::createClickHandles(), elementById(), TechDraw::DrawViewSymbol::execute(), TechDraw::DrawSVGTemplate::getEditableTextsFromTemplate(), nextFromSimpleAxis(), TechDraw::DrawViewSymbol::onChanged(), TechDraw::DrawSVGTemplate::processTemplate(), and root().
kind()
QXmlNodeModelIndex::NodeKind QDomNodeModel::kind (const QXmlNodeModelIndex & ni) const
References toDomNode().
name()
QXmlName QDomNodeModel::name (const QXmlNodeModelIndex & ni) const
References namespaceBindings(), and toDomNode().
Referenced by draftguitools.gui_groups.Ui_AddNamedGroup::accept(), prototype.Node::addtofreecad(), Addon.Addon::disable(), Addon.Addon::enable(), addonmanager_macro.Macro::filename(), gzip_utf8.GzipFile::filename(), addonmanager_macro.Macro::fill_details_from_code(), addonmanager_macro.Macro::fill_details_from_wiki(), Addon.Addon::get_cached_icon_filename(), ifc4.ifcapproval::hasidentifierorname(), addonmanager_macro.Macro::install(), Addon.Addon::is_disabled(), femsolver.elmer.sifio.Section::keys(), automotive_design.si_unit::named_unit_dimensions(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::output(), prototype.Node::pprint(), prototype.Node::pprint2(), PathScripts.PathSetupSheetGui.OpTaskPanel::propertyGroup(), PathScripts.PathSetupSheetGui.OpTaskPanel::propertyName(), PathScripts.PathJobGui.TaskPanel::reject(), addonmanager_macro.Macro::remove(), Addon.Addon::to_cache(), ifc2x3.ifcexternalreference::wr1(), ifc2x3.ifcdocumentreference::wr1(), ifc4.ifcexternalreference::wr1(), ifc4.ifcdocumentreference::wr1(), and automotive_design.general_property_association::wr2().
namespaceBindings()
QVector< QXmlName > QDomNodeModel::namespaceBindings (const QXmlNodeModelIndex & n) const
References toDomNode().
Referenced by name().
nextFromSimpleAxis()
QXmlNodeModelIndex QDomNodeModel::nextFromSimpleAxis (SimpleAxis axis, const QXmlNodeModelIndex & origin) const protected
References fromDomNode(), and toDomNode().
nodesByIdref()
QVector< QXmlNodeModelIndex > QDomNodeModel::nodesByIdref (const QXmlName & idref) const
path()
QVector< QDomNode > QDomNodeModel::path (const QDomNode & n) const
Referenced by compareOrder(), PathScripts.PathToolBitLibraryGui.ToolBitLibrary::librarySave(), PathScripts.PathToolBitLibraryGui.ToolBitLibrary::librarySaveAs(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::loadData().
root()
QXmlNodeModelIndex QDomNodeModel::root (const QXmlNodeModelIndex & n) const
References fromDomNode(), and toDomNode().
Referenced by Mod.Test.unittestgui.TkTestRunner::errorDialog(), Mod.Test.unittestgui.TkTestRunner::showAboutDialog(), Mod.Test.unittestgui.TkTestRunner::showHelpDialog(), and Mod.Test.unittestgui.TkTestRunner::showSelectedError().
sourceLocation()
QSourceLocation QDomNodeModel::sourceLocation (const QXmlNodeModelIndex & index) const
stringValue()
QString QDomNodeModel::stringValue (const QXmlNodeModelIndex & n) const
References toDomNode().
Referenced by typedValue().
toDomNode()
QDomNode QDomNodeModel::toDomNode (const QXmlNodeModelIndex & ni) const
Referenced by attributes(), compareOrder(), TechDrawGui::QGISVGTemplate::createClickHandles(), TechDraw::DrawViewSymbol::execute(), TechDraw::DrawSVGTemplate::getEditableTextsFromTemplate(), kind(), name(), namespaceBindings(), nextFromSimpleAxis(), TechDraw::DrawViewSymbol::onChanged(), TechDraw::DrawSVGTemplate::processTemplate(), root(), and stringValue().
typedValue()
QVariant QDomNodeModel::typedValue (const QXmlNodeModelIndex & node) const
References stringValue().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/App/QDomNodeModel.h
FreeCAD/src/Mod/TechDraw/App/QDomNodeModel.cpp