FreeCAD: PartDesignGui::TaskBoxPrimitives Class Reference
PartDesignGui::TaskBoxPrimitives Class Reference
#include <TaskPrimitiveParameters.h>
Public Slots
void onBoxHeightChanged (double)
void onBoxLengthChanged (double)
void onBoxWidthChanged (double)
void onConeAngleChanged (double)
void onConeHeightChanged (double)
void onConeRadius1Changed (double)
void onConeRadius2Changed (double)
void onCylinderAngleChanged (double)
void onCylinderHeightChanged (double)
void onCylinderRadiusChanged (double)
void onCylinderXSkewChanged (double)
void onCylinderYSkewChanged (double)
void onEllipsoidAngle1Changed (double)
void onEllipsoidAngle2Changed (double)
void onEllipsoidAngle3Changed (double)
void onEllipsoidRadius1Changed (double)
void onEllipsoidRadius2Changed (double)
void onEllipsoidRadius3Changed (double)
void onPrismCircumradiusChanged (double)
void onPrismHeightChanged (double)
void onPrismPolygonChanged (int)
void onPrismXSkewChanged (double)
void onPrismYSkewChanged (double)
void onSphereAngle1Changed (double)
void onSphereAngle2Changed (double)
void onSphereAngle3Changed (double)
void onSphereRadiusChanged (double)
void onTorusAngle1Changed (double)
void onTorusAngle2Changed (double)
void onTorusAngle3Changed (double)
void onTorusRadius1Changed (double)
void onTorusRadius2Changed (double)
void onWedgeX2maxChanged (double)
void onWedgeX2minChanged (double)
void onWedgeXmaxChanged (double)
void onWedgeXminChanged (double)
void onWedgeYmaxChanged (double)
void onWedgeYminChanged (double)
void onWedgeZ2maxChanged (double)
void onWedgeZ2minChanged (double)
void onWedgeZmaxChanged (double)
void onWedgeZminChanged (double)
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Public Member Functions
bool setPrimitive (App::DocumentObject *)
TaskBoxPrimitives (ViewProviderPrimitive *vp, QWidget *parent=nullptr)
~TaskBoxPrimitives ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::DocumentObserver
void attachDocument (Document *)
Attaches to another document, the old document is not longer observed then.
void detachDocument ()
Detaches from the current document, the document is not longer observed then.
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
Additional Inherited Members
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskBoxPrimitives()
TaskBoxPrimitives::TaskBoxPrimitives (ViewProviderPrimitive * vp, QWidget * parent = nullptr)
References PartDesign::Cylinder::Angle, PartDesign::Cone::Angle, PartDesign::Sphere::Angle1, PartDesign::Ellipsoid::Angle1, PartDesign::Torus::Angle1, PartDesign::Sphere::Angle2, PartDesign::Ellipsoid::Angle2, PartDesign::Torus::Angle2, PartDesign::Sphere::Angle3, PartDesign::Ellipsoid::Angle3, PartDesign::Torus::Angle3, Gui::DocumentObserver::attachDocument(), PartDesign::FeaturePrimitive::Box, PartDesign::Prism::Circumradius, PartDesign::FeaturePrimitive::Cone, draftgeoutils.intersections::connect(), Base::Console(), PartDesign::FeaturePrimitive::Cylinder, PartDesign::FeaturePrimitive::Ellipsoid, Base::ConsoleSingleton::Error(), PartDesign::Body::findBodyOf(), Part::PrismExtension::FirstAngle, Gui::ViewProviderDocumentObject::getDocument(), App::PropertyQuantityConstraint::getMaximum(), App::PropertyQuantityConstraint::getMinimum(), Gui::ViewProviderDocumentObject::getObject(), App::OriginGroupExtension::getOrigin(), PartDesign::FeaturePrimitive::getPrimitiveType(), App::PropertyInteger::getValue(), App::PropertyQuantity::getValue(), Gui::Application::getViewProvider(), QSint::ActionGroup::groupLayout(), PartDesign::Box::Height, PartDesign::Cylinder::Height, PartDesign::Cone::Height, PartDesign::Prism::Height, Gui::Application::Instance, PartDesign::Box::Length, onBoxHeightChanged(), onBoxLengthChanged(), onBoxWidthChanged(), onConeAngleChanged(), onConeHeightChanged(), onConeRadius1Changed(), onConeRadius2Changed(), onCylinderAngleChanged(), onCylinderHeightChanged(), onCylinderRadiusChanged(), onCylinderXSkewChanged(), onCylinderYSkewChanged(), onEllipsoidAngle1Changed(), onEllipsoidAngle2Changed(), onEllipsoidAngle3Changed(), onEllipsoidRadius1Changed(), onEllipsoidRadius2Changed(), onEllipsoidRadius3Changed(), onPrismCircumradiusChanged(), onPrismHeightChanged(), onPrismPolygonChanged(), onPrismXSkewChanged(), onPrismYSkewChanged(), onSphereAngle1Changed(), onSphereAngle2Changed(), onSphereAngle3Changed(), onSphereRadiusChanged(), onTorusAngle1Changed(), onTorusAngle2Changed(), onTorusAngle3Changed(), onTorusRadius1Changed(), onTorusRadius2Changed(), onWedgeX2maxChanged(), onWedgeX2minChanged(), onWedgeXmaxChanged(), onWedgeXminChanged(), onWedgeYmaxChanged(), onWedgeYminChanged(), onWedgeZ2maxChanged(), onWedgeZ2minChanged(), onWedgeZmaxChanged(), onWedgeZminChanged(), PartDesign::Prism::Polygon, PartDesign::FeaturePrimitive::Prism, PartDesign::Cylinder::Radius, PartDesign::Sphere::Radius, PartDesign::Cone::Radius1, PartDesign::Ellipsoid::Radius1, PartDesign::Torus::Radius1, PartDesign::Cone::Radius2, PartDesign::Ellipsoid::Radius2, PartDesign::Torus::Radius2, PartDesign::Ellipsoid::Radius3, Part::PrismExtension::SecondAngle, Gui::ViewProviderOrigin::setTemporaryVisibility(), PartDesign::FeaturePrimitive::Sphere, PartDesign::FeaturePrimitive::Torus, PartDesign::FeaturePrimitive::Wedge, Base::Exception::what(), PartDesign::Box::Width, PartDesign::Wedge::X2max, PartDesign::Wedge::X2min, PartDesign::Wedge::Xmax, PartDesign::Wedge::Xmin, PartDesign::Wedge::Ymax, PartDesign::Wedge::Ymin, PartDesign::Wedge::Z2max, PartDesign::Wedge::Z2min, PartDesign::Wedge::Zmax, and PartDesign::Wedge::Zmin.
~TaskBoxPrimitives()
TaskBoxPrimitives::~TaskBoxPrimitives ()
References Base::Console(), Base::ConsoleSingleton::Error(), PartDesign::Body::findBodyOf(), Gui::ViewProviderDocumentObject::getObject(), App::OriginGroupExtension::getOrigin(), Gui::Application::getViewProvider(), Gui::Application::Instance, Gui::ViewProviderOrigin::resetTemporaryVisibility(), and Base::Exception::what().
Member Function Documentation
onBoxHeightChanged
void TaskBoxPrimitives::onBoxHeightChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesign::Box::Height, App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onBoxLengthChanged
void TaskBoxPrimitives::onBoxLengthChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesign::Box::Length, App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onBoxWidthChanged
void TaskBoxPrimitives::onBoxWidthChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), App::PropertyQuantity::setValue(), and PartDesign::Box::Width.
Referenced by TaskBoxPrimitives().
onConeAngleChanged
void TaskBoxPrimitives::onConeAngleChanged (double v) slot
References PartDesign::Cone::Angle, App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onConeHeightChanged
void TaskBoxPrimitives::onConeHeightChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesign::Cone::Height, App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onConeRadius1Changed
void TaskBoxPrimitives::onConeRadius1Changed (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesign::Cone::Radius1, App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onConeRadius2Changed
void TaskBoxPrimitives::onConeRadius2Changed (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesign::Cone::Radius2, App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onCylinderAngleChanged
void TaskBoxPrimitives::onCylinderAngleChanged (double v) slot
References PartDesign::Cylinder::Angle, App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onCylinderHeightChanged
void TaskBoxPrimitives::onCylinderHeightChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesign::Cylinder::Height, App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onCylinderRadiusChanged
void TaskBoxPrimitives::onCylinderRadiusChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesign::Cylinder::Radius, App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onCylinderXSkewChanged
void TaskBoxPrimitives::onCylinderXSkewChanged (double v) slot
References Part::PrismExtension::FirstAngle, App::DocumentObject::getDocument(), App::PropertyQuantityConstraint::getMaximum(), App::PropertyQuantityConstraint::getMinimum(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyQuantity::getQuantityValue(), App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onCylinderYSkewChanged
void TaskBoxPrimitives::onCylinderYSkewChanged (double v) slot
References App::DocumentObject::getDocument(), App::PropertyQuantityConstraint::getMaximum(), App::PropertyQuantityConstraint::getMinimum(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyQuantity::getQuantityValue(), App::Document::recomputeFeature(), Part::PrismExtension::SecondAngle, and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onEllipsoidAngle1Changed
void TaskBoxPrimitives::onEllipsoidAngle1Changed (double v) slot
References PartDesign::Ellipsoid::Angle1, App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onEllipsoidAngle2Changed
void TaskBoxPrimitives::onEllipsoidAngle2Changed (double v) slot
References PartDesign::Ellipsoid::Angle2, App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onEllipsoidAngle3Changed
void TaskBoxPrimitives::onEllipsoidAngle3Changed (double v) slot
References PartDesign::Ellipsoid::Angle3, App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onEllipsoidRadius1Changed
void TaskBoxPrimitives::onEllipsoidRadius1Changed (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesign::Ellipsoid::Radius1, App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onEllipsoidRadius2Changed
void TaskBoxPrimitives::onEllipsoidRadius2Changed (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesign::Ellipsoid::Radius2, App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onEllipsoidRadius3Changed
void TaskBoxPrimitives::onEllipsoidRadius3Changed (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesign::Ellipsoid::Radius3, App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onPrismCircumradiusChanged
void TaskBoxPrimitives::onPrismCircumradiusChanged (double v) slot
References PartDesign::Prism::Circumradius, App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onPrismHeightChanged
void TaskBoxPrimitives::onPrismHeightChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesign::Prism::Height, App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onPrismPolygonChanged
void TaskBoxPrimitives::onPrismPolygonChanged (int v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesign::Prism::Polygon, App::Document::recomputeFeature(), and App::PropertyInteger::setValue().
Referenced by TaskBoxPrimitives().
onPrismXSkewChanged
void TaskBoxPrimitives::onPrismXSkewChanged (double v) slot
References Part::PrismExtension::FirstAngle, App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyQuantity::getQuantityValue(), App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onPrismYSkewChanged
void TaskBoxPrimitives::onPrismYSkewChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyQuantity::getQuantityValue(), App::Document::recomputeFeature(), Part::PrismExtension::SecondAngle, and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onSphereAngle1Changed
void TaskBoxPrimitives::onSphereAngle1Changed (double v) slot
References PartDesign::Sphere::Angle1, App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onSphereAngle2Changed
void TaskBoxPrimitives::onSphereAngle2Changed (double v) slot
References PartDesign::Sphere::Angle2, App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onSphereAngle3Changed
void TaskBoxPrimitives::onSphereAngle3Changed (double v) slot
References PartDesign::Sphere::Angle3, App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onSphereRadiusChanged
void TaskBoxPrimitives::onSphereRadiusChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesign::Sphere::Radius, App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onTorusAngle1Changed
void TaskBoxPrimitives::onTorusAngle1Changed (double v) slot
References PartDesign::Torus::Angle1, App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onTorusAngle2Changed
void TaskBoxPrimitives::onTorusAngle2Changed (double v) slot
References PartDesign::Torus::Angle2, App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onTorusAngle3Changed
void TaskBoxPrimitives::onTorusAngle3Changed (double v) slot
References PartDesign::Torus::Angle3, App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onTorusRadius1Changed
void TaskBoxPrimitives::onTorusRadius1Changed (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesign::Torus::Radius1, App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onTorusRadius2Changed
void TaskBoxPrimitives::onTorusRadius2Changed (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), PartDesign::Torus::Radius2, App::Document::recomputeFeature(), and App::PropertyQuantity::setValue().
Referenced by TaskBoxPrimitives().
onWedgeX2maxChanged
void TaskBoxPrimitives::onWedgeX2maxChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), App::PropertyQuantity::setValue(), and PartDesign::Wedge::X2max.
Referenced by TaskBoxPrimitives().
onWedgeX2minChanged
void TaskBoxPrimitives::onWedgeX2minChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), App::PropertyQuantity::setValue(), and PartDesign::Wedge::X2min.
Referenced by TaskBoxPrimitives().
onWedgeXmaxChanged
void TaskBoxPrimitives::onWedgeXmaxChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), App::PropertyQuantity::setValue(), and PartDesign::Wedge::Xmax.
Referenced by TaskBoxPrimitives().
onWedgeXminChanged
void TaskBoxPrimitives::onWedgeXminChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), App::PropertyQuantity::setValue(), and PartDesign::Wedge::Xmin.
Referenced by TaskBoxPrimitives().
onWedgeYmaxChanged
void TaskBoxPrimitives::onWedgeYmaxChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), App::PropertyQuantity::setValue(), and PartDesign::Wedge::Ymax.
Referenced by TaskBoxPrimitives().
onWedgeYminChanged
void TaskBoxPrimitives::onWedgeYminChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), App::PropertyQuantity::setValue(), and PartDesign::Wedge::Ymin.
Referenced by TaskBoxPrimitives().
onWedgeZ2maxChanged
void TaskBoxPrimitives::onWedgeZ2maxChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), App::PropertyQuantity::setValue(), and PartDesign::Wedge::Z2max.
Referenced by TaskBoxPrimitives().
onWedgeZ2minChanged
void TaskBoxPrimitives::onWedgeZ2minChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), App::PropertyQuantity::setValue(), and PartDesign::Wedge::Z2min.
Referenced by TaskBoxPrimitives().
onWedgeZmaxChanged
void TaskBoxPrimitives::onWedgeZmaxChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), App::PropertyQuantity::setValue(), and PartDesign::Wedge::Zmax.
Referenced by TaskBoxPrimitives().
onWedgeZminChanged
void TaskBoxPrimitives::onWedgeZminChanged (double v) slot
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Document::recomputeFeature(), App::PropertyQuantity::setValue(), and PartDesign::Wedge::Zmin.
Referenced by TaskBoxPrimitives().
setPrimitive()
bool TaskBoxPrimitives::setPrimitive (App::DocumentObject * obj)
References Gui::Command::Doc, Base::QuantityFormat::Fixed, App::Application::getActiveDocument(), App::GetApplication(), Base::UnitsApi::getDecimals(), Gui::getMainWindow(), Gui::Command::getObjectCmd(), and Base::UnitsApi::toNumber().
Referenced by PartDesignGui::TaskPrimitiveParameters::accept().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/PartDesign/Gui/TaskPrimitiveParameters.h
FreeCAD/src/Mod/PartDesign/Gui/TaskPrimitiveParameters.cpp