FreeCAD: Gui::Dialog::CommandModel Class Reference
Gui::Dialog::CommandModel Class Reference
#include <DlgCustomizeSpaceball.h>
Public Member Functions
virtual int columnCount (const QModelIndex &parent) const
CommandModel (QObject *parent=0)
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
virtual Qt::ItemFlags flags (const QModelIndex &index) const
void goAddMacro (const QByteArray &macroName)
void goRemoveMacro (const QByteArray &macroName)
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
virtual QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
virtual QModelIndex parent (const QModelIndex &index) const
virtual int rowCount (const QModelIndex &parent) const
~CommandModel ()
Constructor & Destructor Documentation
CommandModel()
CommandModel::CommandModel (QObject * parent = 0)
~CommandModel()
CommandModel::~CommandModel ()
Member Function Documentation
columnCount()
int CommandModel::columnCount (const QModelIndex & parent) const virtual
References parent().
data()
QVariant CommandModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
References Gui::Dialog::CommandNode::aCommand, Gui::BitmapFactory(), Gui::Dialog::CommandNode::children, Gui::CommandBase::className(), Gui::Dialog::CommandNode::CommandType, Gui::Command::getGroupName(), Gui::CommandBase::getMenuText(), Gui::Command::getName(), Gui::CommandBase::getPixmap(), Gui::CommandBase::getToolTipText(), Gui::Dialog::CommandNode::GroupType, and Gui::Dialog::CommandNode::nodeType.
Referenced by Mod.Show.mTempoVis.TempoVis::activateWorkbench(), Mod.Show.SceneDetail.SceneDetail::apply_data(), importIFClegacy.IfcSchema::capitalize(), Gui::Dialog::PrintModel::data(), Mod.Show.mTempoVis.TempoVis::forget(), Mod.Show.mTempoVis.TempoVis::forgetDetail(), Mod.Show.mTempoVis.TempoVis::has(), ArchSchedule.CommandArchSchedule::IsActive(), importIFClegacy.IfcSchema::readEntities(), importIFClegacy.IfcSchema::readTypes(), Mod.Show.mTempoVis.TempoVis::restore(), Mod.Show.mTempoVis.TempoVis::save(), Mod.Show.mTempoVis.TempoVis::stored_val(), FeaturePython.ViewProviderOctahedron::updateData(), and Dice3DS.dom3ds.UndefinedChunk::write().
flags()
Qt::ItemFlags CommandModel::flags (const QModelIndex & index) const virtual
References Gui::Dialog::CommandNode::CommandType, and Gui::Dialog::CommandNode::nodeType.
goAddMacro()
void CommandModel::goAddMacro (const QByteArray & macroName)
References Gui::Dialog::CommandNode::aCommand, Gui::Dialog::CommandNode::children, Gui::Application::commandManager(), Gui::Dialog::CommandNode::CommandType, Gui::CommandManager::getCommandByName(), Gui::Dialog::CommandNode::GroupType, index(), Gui::Application::Instance, and Gui::Dialog::CommandNode::parent.
Referenced by Gui::Dialog::DlgCustomizeSpaceball::onAddMacroAction().
goRemoveMacro()
void CommandModel::goRemoveMacro (const QByteArray & macroName)
References Gui::Dialog::CommandNode::children, index(), and parent().
Referenced by Gui::Dialog::DlgCustomizeSpaceball::onRemoveMacroAction().
headerData()
QVariant CommandModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
index()
QModelIndex CommandModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const virtual
References Gui::Dialog::CommandNode::children, and parent().
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::addSegment(), Dice3DS.dom3ds.FileLikeBuffer::advance(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::begin(), Gui::Dialog::PrintModel::data(), Spreadsheet_legacy.MathParser::getValue(), goAddMacro(), goRemoveMacro(), Spreadsheet_legacy.MathParser::hasNext(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::interval(), PathScripts.PathJobDlg.JobCreate::item1ValueChanged(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::length(), Spreadsheet_legacy.MathParser::parseAddition(), Spreadsheet_legacy.MathParser::parseMultiplication(), Spreadsheet_legacy.MathParser::parseNegative(), Spreadsheet_legacy.MathParser::parseNumber(), Spreadsheet_legacy.MathParser::parseParenthesis(), Spreadsheet_legacy.MathParser::parseVariable(), Spreadsheet_legacy.MathParser::peek(), Dice3DS.dom3ds.FileLikeBuffer::read(), Dice3DS.dom3ds.FileLikeBuffer::read_fbuf(), Dice3DS.dom3ds.FileLikeBuffer::read_rest(), Dice3DS.dom3ds.FileLikeBuffer::read_to_nul(), Dice3DS.dom3ds.FileLikeBuffer::room_for_chunks(), Dice3DS.dom3ds.FileLikeBuffer::seek(), PathScripts.PathJobDlg.JobCreate::setupColumnEditor(), Spreadsheet_legacy.MathParser::skipWhitespace(), Dice3DS.dom3ds.FileLikeBuffer::tell(), automotive_design.index_expression::wr1(), and automotive_design.index_expression::wr2().
parent()
QModelIndex CommandModel::parent (const QModelIndex & index) const virtual
References Gui::Dialog::CommandNode::children, and Gui::Dialog::CommandNode::parent.
Referenced by PathScripts.PathSimulatorGui.CAMSimTaskUi::accept(), columnCount(), Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium(), goRemoveMacro(), index(), PathScripts.PathSimulatorGui.CAMSimTaskUi::reject(), rowCount(), and PathScripts.PathOpGui.TaskPanelPage::setParent().
rowCount()
int CommandModel::rowCount (const QModelIndex & parent) const virtual
References Gui::Dialog::CommandNode::children, and parent().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgCustomizeSpaceball.h
Sources/FreeCAD/src/Gui/DlgCustomizeSpaceball.cpp