FreeCAD: SketcherGui::ConstraintSettingsDialog Class Reference
SketcherGui::ConstraintSettingsDialog Class Reference
#include <ConstraintSettingsDialog.h>
Public Slots
void accept ()
void on_extendedInformation_stateChanged (int state)
void on_filterInternalAlignment_stateChanged (int state)
void on_visualisationTrackingFilter_stateChanged (int state)
void reject ()
Signals
void emit_extendedInformation_stateChanged (int)
void emit_filterInternalAlignment_stateChanged (int)
void emit_visualisationTrackingFilter_stateChanged (int)
Public Member Functions
ConstraintSettingsDialog (void)
~ConstraintSettingsDialog ()
Constructor & Destructor Documentation
ConstraintSettingsDialog()
ConstraintSettingsDialog::ConstraintSettingsDialog (void)
References draftgeoutils.intersections::connect(), on_extendedInformation_stateChanged(), on_filterInternalAlignment_stateChanged(), and on_visualisationTrackingFilter_stateChanged().
~ConstraintSettingsDialog()
ConstraintSettingsDialog::~ConstraintSettingsDialog ()
Member Function Documentation
accept
void ConstraintSettingsDialog::accept (void) slot
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
emit_extendedInformation_stateChanged
void SketcherGui::ConstraintSettingsDialog::emit_extendedInformation_stateChanged (int) signal
Referenced by on_extendedInformation_stateChanged().
emit_filterInternalAlignment_stateChanged
void SketcherGui::ConstraintSettingsDialog::emit_filterInternalAlignment_stateChanged (int) signal
Referenced by on_filterInternalAlignment_stateChanged().
emit_visualisationTrackingFilter_stateChanged
void SketcherGui::ConstraintSettingsDialog::emit_visualisationTrackingFilter_stateChanged (int) signal
Referenced by on_visualisationTrackingFilter_stateChanged().
on_extendedInformation_stateChanged
void ConstraintSettingsDialog::on_extendedInformation_stateChanged (int state) slot
References emit_extendedInformation_stateChanged().
Referenced by ConstraintSettingsDialog().
on_filterInternalAlignment_stateChanged
void ConstraintSettingsDialog::on_filterInternalAlignment_stateChanged (int state) slot
References emit_filterInternalAlignment_stateChanged().
Referenced by ConstraintSettingsDialog().
on_visualisationTrackingFilter_stateChanged
void ConstraintSettingsDialog::on_visualisationTrackingFilter_stateChanged (int state) slot
References emit_visualisationTrackingFilter_stateChanged().
Referenced by ConstraintSettingsDialog().
reject
void ConstraintSettingsDialog::reject (void) slot
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/Gui/ConstraintSettingsDialog.h
FreeCAD/src/Mod/Sketcher/Gui/ConstraintSettingsDialog.cpp