FreeCAD: TechDraw::PropertyCosmeticEdgeList Class Reference
TechDraw::PropertyCosmeticEdgeList Class Reference
#include <PropertyCosmeticEdgeList.h>
Public Member Functions
virtual App::Property * Copy (void) const
Returns a new copy of the property (mainly for Undo/Redo and transactions)
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
virtual int getSize (void) const
const std::vector< CosmeticEdge * > & getValues (void) const
const CosmeticEdge * operator[] (const int idx) const
index operator
virtual void Paste (const App::Property &from)
Paste the value from the property (mainly for Undo/Redo and transactions)
PropertyCosmeticEdgeList ()
A constructor.
virtual void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const
This method is used to save properties to an XML document.
virtual void setPyObject (PyObject *)
virtual void setSize (int newSize)
void setValue (CosmeticEdge *)
Sets the property.
void setValues (const std::vector< CosmeticEdge * > &)
virtual ~PropertyCosmeticEdgeList ()
A destructor.
Public Member Functions inherited from App::PropertyLists
bool isOrderRelevant () const
void setOrderRelevant (bool on)
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
const char * getName (void) const
get the name of this property in the belonging container
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::PropertyListsBase
void clearTouchList ()
const std::set< int > & getTouchList () const
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , PropStaticBegin = 21 ,
PropDynamic = 21 , PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 ,
PropTransient = 25 , PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 ,
User1 = 28 , User2 = 29 , User3 = 30 , User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Protected Member Functions inherited from App::PropertyListsBase
virtual void setPyValues (const std::vector< PyObject * > &vals, const std::vector< int > &indices)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Constructor & Destructor Documentation
PropertyCosmeticEdgeList()
PropertyCosmeticEdgeList::PropertyCosmeticEdgeList ()
A constructor.
A more elaborate description of the constructor.
~PropertyCosmeticEdgeList()
PropertyCosmeticEdgeList::~PropertyCosmeticEdgeList () virtual
A destructor.
A more elaborate description of the destructor.
Member Function Documentation
Copy()
App::Property * PropertyCosmeticEdgeList::Copy (void) const virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
getMemSize()
unsigned int PropertyCosmeticEdgeList::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
See also
Base::Persistence
Reimplemented from App::Property.
getPyObject()
PyObject * PropertyCosmeticEdgeList::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
getSize()
int PropertyCosmeticEdgeList::getSize (void) const virtual
Implements App::PropertyListsBase.
getValues()
const std::vector<CosmeticEdge*>& TechDraw::PropertyCosmeticEdgeList::getValues (void) const
Referenced by TechDraw::DrawViewPart::addCosmeticEdgesToGeom(), TechDrawGui::TaskRestoreLines::countInvisibleCosmetics(), TechDraw::DrawViewPart::dumpCosEdges(), and TechDrawGui::TaskRestoreLines::restoreInvisibleCosmetics().
operator[]()
const CosmeticEdge* TechDraw::PropertyCosmeticEdgeList::operator[] (const int idx) const
index operator
Paste()
void PropertyCosmeticEdgeList::Paste (const App::Property & from) virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Restore()
void PropertyCosmeticEdgeList::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
References Base::XMLReader::clearPartialRestoreObject(), Base::Console(), Base::Type::createInstance(), Base::ConsoleSingleton::Error(), Base::Type::fromName(), Base::XMLReader::getAttribute(), Base::XMLReader::getAttributeAsInteger(), Base::XMLReader::localName(), Base::XMLReader::readElement(), Base::XMLReader::readEndElement(), TechDraw::CosmeticEdge::Restore(), and Base::XMLReader::testStatus().
Save()
void PropertyCosmeticEdgeList::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
References Base::Writer::decInd(), Base::Writer::incInd(), Base::Writer::ind(), and Base::Writer::Stream().
setPyObject()
void PropertyCosmeticEdgeList::setPyObject (PyObject * value) virtual
Reimplemented from App::PropertyLists.
References TechDraw::CosmeticEdgePy::getCosmeticEdgePtr().
setSize()
void PropertyCosmeticEdgeList::setSize (int newSize) virtual
Implements App::PropertyListsBase.
setValue()
void PropertyCosmeticEdgeList::setValue (CosmeticEdge * lValue)
Sets the property.
setValues()
void PropertyCosmeticEdgeList::setValues (const std::vector< CosmeticEdge * > & lValue)
Referenced by TechDraw::DrawViewPart::clearCosmeticEdges(), and TechDrawGui::TaskRestoreLines::restoreInvisibleCosmetics().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/App/PropertyCosmeticEdgeList.h
Sources/FreeCAD/src/Mod/TechDraw/App/PropertyCosmeticEdgeList.cpp