FreeCAD: MeshPart::CurveProjectorSimple Class Reference
MeshPart::CurveProjectorSimple Class Reference
Project by projecting a sampled curve to the mesh.
#include <CurveProjector.h>
Public Member Functions
CurveProjectorSimple (const TopoDS_Shape &aShape, const MeshKernel &pMesh)
bool findStartPoint (const MeshKernel &MeshK, const Base::Vector3f &Pnt, Base::Vector3f &Rslt, unsigned long &FaceIndex)
void GetSampledCurves (const TopoDS_Edge &aEdge, std::vector< Base::Vector3f > &rclPoints, unsigned long ulNbOfPoints=30)
helper to discredicice a Edge...
void projectCurve (const TopoDS_Edge &aEdge, const std::vector< Base::Vector3f > &rclPoints, std::vector< FaceSplitEdge > &vSplitEdges)
virtual ~CurveProjectorSimple ()
Public Member Functions inherited from MeshPart::CurveProjector
CurveProjector (const TopoDS_Shape &aShape, const MeshKernel &pMesh)
result_type & result (void)
void writeIntersectionPointsToFile (const char *name="export_pts.asc")
virtual ~CurveProjector ()
Protected Member Functions
virtual void Do ()
Additional Inherited Members
Public Types inherited from MeshPart::CurveProjector
typedef std::map< TopoDS_Edge, std::vector< FaceSplitEdge >, TopoDSLess< TopoDS_Edge > > result_type
Protected Attributes inherited from MeshPart::CurveProjector
result_type mvEdgeSplitPoints
Detailed Description
Project by projecting a sampled curve to the mesh.
Constructor & Destructor Documentation
CurveProjectorSimple()
CurveProjectorSimple::CurveProjectorSimple (const TopoDS_Shape & aShape, const MeshKernel & pMesh)
References Do().
~CurveProjectorSimple()
virtual MeshPart::CurveProjectorSimple::~CurveProjectorSimple () virtual
Member Function Documentation
Do()
void CurveProjectorSimple::Do (void) protected virtual
Implements MeshPart::CurveProjector.
References MeshPart::CurveProjector::mvEdgeSplitPoints, and projectCurve().
Referenced by CurveProjectorSimple().
findStartPoint()
bool CurveProjectorSimple::findStartPoint (const MeshKernel & MeshK, const Base::Vector3f & Pnt, Base::Vector3f & Rslt, unsigned long & FaceIndex)
References MeshCore::MeshGeomFacet::Foraminate(), MeshCore::MeshGeomFacet::GetNormal(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), and MeshCore::MeshFacetIterator::Position().
GetSampledCurves()
void CurveProjectorSimple::GetSampledCurves (const TopoDS_Edge & aEdge, std::vector< Base::Vector3f > & rclPoints, unsigned long ulNbOfPoints = 30)
helper to discredicice a Edge...
projectCurve()
void CurveProjectorSimple::projectCurve (const TopoDS_Edge & aEdge, const std::vector< Base::Vector3f > & rclPoints, std::vector< FaceSplitEdge > & vSplitEdges)
References Base::Console(), MeshCore::MeshGeomFacet::GetNormal(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshGeomFacet::IntersectWithLine(), Base::ConsoleSingleton::Log(), MeshCore::MeshFacetIterator::More(), Base::SequencerLauncher::next(), MeshCore::MeshFacetIterator::Next(), MeshCore::MeshFacetIterator::Position(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by Do().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/MeshPart/App/CurveProjector.h
Sources/FreeCAD/src/Mod/MeshPart/App/CurveProjector.cpp