FreeCAD: PartGui::DlgBooleanOperation Class Reference
PartGui::DlgBooleanOperation Class Reference
#include <DlgBooleanOperation.h>
Public Slots
void on_swapButton_clicked ()
Public Member Functions
void accept ()
DlgBooleanOperation (QWidget *parent=nullptr)
~DlgBooleanOperation ()
Protected Member Functions
void changeEvent (QEvent *e)
Constructor & Destructor Documentation
DlgBooleanOperation()
DlgBooleanOperation::DlgBooleanOperation (QWidget * parent = nullptr)
References draftgeoutils.faces::bind(), draftgeoutils.intersections::connect(), App::GetApplication(), App::Application::signalChangedObject, and App::Application::signalNewObject.
~DlgBooleanOperation()
DlgBooleanOperation::~DlgBooleanOperation ()
Member Function Documentation
accept()
void DlgBooleanOperation::accept (void)
References App::Document::commitTransaction(), Gui::Command::Doc, App::Application::getActiveDocument(), App::GetApplication(), App::DocumentObject::getGroup(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), App::Document::getUniqueObjectName(), Gui::Command::Gui, App::Document::openTransaction(), and App::Document::recompute().
Referenced by PartGui::TaskBooleanOperation::clicked(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
changeEvent()
void DlgBooleanOperation::changeEvent (QEvent * e) protected
on_swapButton_clicked
void DlgBooleanOperation::on_swapButton_clicked () slot
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/DlgBooleanOperation.h
FreeCAD/src/Mod/Part/Gui/DlgBooleanOperation.cpp