FreeCAD: Part::GeomSurfaceOfExtrusion Class Reference
Part::GeomSurfaceOfExtrusion Class Reference
#include <Geometry.h>
Public Member Functions
virtual Geometry * copy (void) const
returns a copy of this object having a new randomly generated tag.
GeomSurfaceOfExtrusion ()
GeomSurfaceOfExtrusion (const Handle(Geom_Curve)&, const gp_Dir &)
GeomSurfaceOfExtrusion (const Handle(Geom_SurfaceOfLinearExtrusion)&)
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
const Handle (Geom_Geometry) &handle() const
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
void setHandle (const Handle(Geom_SurfaceOfLinearExtrusion)&c)
virtual ~GeomSurfaceOfExtrusion ()
Public Member Functions inherited from Part::GeomSurface
GeomSurface ()
bool normal (double u, double v, gp_Dir &dir) const
bool tangentU (double u, double v, gp_Dir &dirU) const
bool tangentV (double u, double v, gp_Dir &dirV) const
TopoDS_Shape toShape () const
virtual ~GeomSurface ()
bool isUmbillic (double u, double v) const
double curvature (double u, double v, Curvature) const
void curvatureDirections (double u, double v, gp_Dir &maxD, gp_Dir &minD) const
Public Member Functions inherited from Part::Geometry
Geometry * clone (void) const
returns a cloned object.
void deleteExtension (Base::Type type)
void deleteExtension (std::string name)
std::weak_ptr< GeometryExtension > getExtension (Base::Type type)
std::weak_ptr< const GeometryExtension > getExtension (Base::Type type) const
std::weak_ptr< GeometryExtension > getExtension (std::string name)
std::weak_ptr< const GeometryExtension > getExtension (std::string name) const
std::vector< std::weak_ptr< const GeometryExtension > > getExtensions () const
boost::uuids::uuid getTag () const
returns the tag of the geometry object
bool hasExtension (Base::Type type) const
bool hasExtension (std::string name) const
void mirror (const Base::Vector3d &point)
void mirror (const Base::Vector3d &point, const Base::Vector3d &dir)
void rotate (const Base::Placement &plm)
void scale (const Base::Vector3d &vec, double scale)
void setExtension (std::unique_ptr< GeometryExtension > &&geo)
void transform (const Base::Matrix4D &mat)
void translate (const Base::Vector3d &vec)
virtual ~Geometry ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Public Types inherited from Part::GeomSurface
enum Curvature { Maximum, Minimum, Mean, Gaussian }
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Protected Member Functions inherited from Part::Geometry
void assignTag (const Part::Geometry *)
copies the tag from the geometry passed as a parameter to this object
void copyNonTag (const Part::Geometry *)
void createNewTag ()
create a new tag for the geometry object
Geometry ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Part::Geometry
std::vector< std::shared_ptr< GeometryExtension > > extensions
boost::uuids::uuid tag
Constructor & Destructor Documentation
GeomSurfaceOfExtrusion() [1/3]
GeomSurfaceOfExtrusion::GeomSurfaceOfExtrusion ()
GeomSurfaceOfExtrusion() [2/3]
GeomSurfaceOfExtrusion::GeomSurfaceOfExtrusion (const Handle(Geom_Curve)& c, const gp_Dir & d)
GeomSurfaceOfExtrusion() [3/3]
GeomSurfaceOfExtrusion::GeomSurfaceOfExtrusion (const Handle(Geom_SurfaceOfLinearExtrusion)& s)
References setHandle().
~GeomSurfaceOfExtrusion()
GeomSurfaceOfExtrusion::~GeomSurfaceOfExtrusion () virtual
Member Function Documentation
copy()
virtual Geometry* Part::GeomSurfaceOfExtrusion::copy (void) const virtual
returns a copy of this object having a new randomly generated tag.
If you also want to copy the tag, you may use clone() instead. For creation of geometry with other handles, with or without the same tag, you may use the constructors and the sethandle functions. The tag of a geometry can be copied to another geometry using the assignTag function.
Implements Part::Geometry.
getMemSize()
virtual unsigned int Part::GeomSurfaceOfExtrusion::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Part::Geometry.
getPyObject()
PyObject * GeomSurfaceOfExtrusion::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
References Part::Geometry::clone().
Handle()
const Part::GeomSurfaceOfExtrusion::Handle (Geom_Geometry) const & virtual
Implements Part::Geometry.
Referenced by setHandle().
Restore()
virtual void Part::GeomSurfaceOfExtrusion::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Part::Geometry.
Save()
virtual void Part::GeomSurfaceOfExtrusion::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from Part::Geometry.
setHandle()
void GeomSurfaceOfExtrusion::setHandle (const Handle(Geom_SurfaceOfLinearExtrusion)& c)
References Handle().
Referenced by GeomSurfaceOfExtrusion(), and Part::SurfaceOfExtrusionPy::PyInit().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/App/Geometry.h
Sources/FreeCAD/src/Mod/Part/App/Geometry.cpp