FreeCAD: femexamples.truss_3d_cs_circle_ele_seg3 Namespace Reference
femexamples.truss_3d_cs_circle_ele_seg3 Namespace Reference
Functions
def get_explanation (header="")
def get_information ()
def setup (doc=None, solvertype="ccxtools")
Function Documentation
get_explanation()
def femexamples.truss_3d_cs_circle_ele_seg3.get_explanation (header = "")
Referenced by femexamples.truss_3d_cs_circle_ele_seg3.setup().
get_information()
def femexamples.truss_3d_cs_circle_ele_seg3.get_information ()
Referenced by femexamples.truss_3d_cs_circle_ele_seg3.setup().
setup()
def femexamples.truss_3d_cs_circle_ele_seg3.setup (doc = None, solvertype = "ccxtools")
References femexamples.truss_3d_cs_circle_ele_seg3.get_explanation(), femexamples.truss_3d_cs_circle_ele_seg3.get_information(), ObjectsFem.makeAnalysis(), ObjectsFem.makeConstraintFixed(), ObjectsFem.makeConstraintForce(), ObjectsFem.makeElementGeometry1D(), draftmake.make_line.makeLine, ObjectsFem.makeMaterialSolid(), ObjectsFem.makeMeshGmsh(), ObjectsFem.makeSolverCalculix(), ObjectsFem.makeSolverCalculixCcxTools(), ObjectsFem.makeSolverZ88(), and draftgeoutils.general.vec().