FreeCAD: draftguitools.gui_base_original.Modifier Class Reference
draftguitools.gui_base_original.Modifier Class Reference
Workbenches » Python workbenches » Draft » draftguitools
Public Member Functions
def Activated (self, name="None", noplanesetup=False, is_subtool=False)
Public Member Functions inherited from draftguitools.gui_base_original.DraftTool
def Activated (self, name="None", noplanesetup=False, is_subtool=False)
def commit (self, name, func)
def finish (self, close=False)
def getStrings (self, addrot=None)
def IsActive (self)
Public Attributes
copymode
Public Attributes inherited from draftguitools.gui_base_original.DraftTool
call
commitList
constrain
doc
extendedCopy
featureName
node
obj
planetrack
point
pos
support
ui
view
Detailed Description
A generic Modifier tool, used by modification tools such as move.
After initializing the parent class, it sets the `copymode` attribute
to `False`.
It inherits `DraftTool`, which sets up the majority of the behavior
of this class.
Member Function Documentation
Activated()
def draftguitools.gui_base_original.Modifier.Activated (self, name = "None", noplanesetup = False, is_subtool = False)
Execute when the command is called.
If an active Gui Command exists, it will call the `finish` method
of it to terminate it.
If no active Gui Command exists, it will proceed with configuration
of the tool. The child class that subclasses this class
then should continue with its own Activated method.
Parameters
----------
name: str, optional
    It defaults to `'None'`.
    It is the `featureName` of the object, to know what is being run.
noplanesetup: bool, optional
    It defaults to `False`.
    If it is `False` it will set up the working plane
    by running `App.DraftWorkingPlane.setup()`.
is_subtool: bool, optional
    It defaults to `False`.
    This is set to `True` when we want to modify an object
    by using the mechanism of a `subtool`, introduced
    through the `Draft_SubelementHighlight` command.
    That is, first we run `Draft_SubelementHighlight`
    then we can use `Draft_Move` while setting `is_subtool` to `True`.
Reimplemented from draftguitools.gui_base_original.DraftTool.
Reimplemented in draftguitools.gui_array_simple.LinkArray, draftguitools.gui_clone.Clone, draftguitools.gui_downgrade.Downgrade, draftguitools.gui_draft2sketch.Draft2Sketch, draftguitools.gui_drawing.Drawing, draftguitools.gui_edit.Edit, draftguitools.gui_join.Join, draftguitools.gui_line_add_delete.AddPoint, draftguitools.gui_line_add_delete.DelPoint, draftguitools.gui_mirror.Mirror, draftguitools.gui_move.Move, draftguitools.gui_offset.Offset, draftguitools.gui_patharray.PathLinkArray, draftguitools.gui_pathtwistedarray.PathTwistedLinkArray, draftguitools.gui_pointarray.PointLinkArray, draftguitools.gui_rotate.Rotate, draftguitools.gui_scale.Scale, draftguitools.gui_shape2dview.Shape2DView, draftguitools.gui_split.Split, draftguitools.gui_stretch.Stretch, draftguitools.gui_styles.ApplyStyle, draftguitools.gui_subelements.SubelementHighlight, draftguitools.gui_trimex.Trimex, draftguitools.gui_upgrade.Upgrade, draftguitools.gui_wire2spline.WireToBSpline, draftguitools.gui_array_simple.Array, draftguitools.gui_patharray.PathArray, draftguitools.gui_pathtwistedarray.PathTwistedArray, and draftguitools.gui_pointarray.PointArray.
References draftguitools.gui_base_original.Modifier.Activated().
Referenced by ArchStructure.CommandStructuralSystem.Activated(), draftguitools.gui_base_original.Modifier.Activated(), draftguitools.gui_arcs.Arc.finish(), draftguitools.gui_beziers.BezCurve.finish(), draftguitools.gui_beziers.CubicBezCurve.finish(), draftguitools.gui_ellipses.Ellipse.finish(), draftguitools.gui_lines.Line.finish(), draftguitools.gui_mirror.Mirror.finish(), draftguitools.gui_move.Move.finish(), draftguitools.gui_polygons.Polygon.finish(), draftguitools.gui_rectangles.Rectangle.finish(), draftguitools.gui_rotate.Rotate.finish(), draftguitools.gui_splines.BSpline.finish(), draftguitools.gui_texts.Text.finish(), draftguitools.gui_points.Point.finish(), draftguitools.gui_shapestrings.ShapeString.finish(), draftguitools.gui_arcs.Arc_3Points.getPoint(), and ArchPanel.CommandPanel.getPoint().
Member Data Documentation
copymode
draftguitools.gui_base_original.Modifier.copymode
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Draft/draftguitools/gui_base_original.py