FreeCAD: App::PropertyExpressionEngine Class Reference
App::PropertyExpressionEngine Class Reference
#include <PropertyExpressionEngine.h>
Classes
struct ExpressionInfo
The ExpressionInfo struct encapsulates an expression.
struct Private
Public Types
enum ExecuteOption { ExecuteAll , ExecuteOutput , ExecuteNonOutput , ExecuteOnRestore }
Execute options.
typedef std::function< std::string(const App::ObjectIdentifier &path, std::shared_ptr< const App::Expression > expr)> ValidatorFunc
Public Types inherited from App::PropertyLinkBase
enum LinkFlags {
LinkAllowExternal , LinkDetached , LinkRestoring , LinkAllowPartial ,
LinkRestoreLabel , LinkSyncSubObject
}
typedef std::pair< std::string, std::string > ShadowSub
Public Types inherited from App::Property
enum Status {
Touched = 0 , Immutable = 1 , ReadOnly = 2 , Hidden = 3 ,
Transient = 4 , MaterialEdit = 5 , NoMaterialListEdit = 6 , Output = 7 ,
LockDynamic = 8 , NoModify = 9 , PartialTrigger = 10 , NoRecompute = 11 ,
Single = 12 , Ordered = 13 , EvalOnRestore = 14 , Busy = 15 ,
CopyOnChange = 16 , UserEdit = 17 , PropStaticBegin = 21 , PropDynamic = 21 ,
PropNoPersist = 22 , PropNoRecompute = 23 , PropReadOnly = 24 , PropTransient = 25 ,
PropHidden = 26 , PropOutput = 27 , PropStaticEnd = 28 , User1 = 28 ,
User2 = 29 , User3 = 30 , User4 = 31
}
Public Member Functions
virtual bool adjustLink (const std::set< App::DocumentObject * > &inList) override
Called to adjust the link to avoid potential cyclic dependency.
virtual void afterRestore () override
Called at the beginning of Document::afterRestore()
App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const override
Create a canonical object identifier of the given object p.
Property * Copy (void) const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
virtual Property * CopyOnImportExternal (const std::map< std::string, std::string > &nameMap) const override
Return a copy of the property if any changes caused by importing external linked object.
virtual Property * CopyOnLabelChange (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const override
Update object label reference in this property.
virtual Property * CopyOnLinkReplace (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const override
Return a copy of the property if the link replacement affects this property.
bool depsAreTouched () const
Determine whether any dependencies of any of the registered expressions have been touched.
DocumentObjectExecReturn * execute (ExecuteOption option=ExecuteAll, bool *touched=nullptr)
Evaluate the expressions.
virtual std::map< App::ObjectIdentifier, const App::Expression * > getExpressions () const override
unsigned int getMemSize (void) const override
Estimate memory size of this property.
void getPathsToDocumentObject (DocumentObject *, std::vector< App::ObjectIdentifier > &paths) const
Find paths to document object.
const boost::any getPathValue (const App::ObjectIdentifier &path) const override
Get expression for path.
PyObject * getPyObject (void) override
This method returns the Python wrapper for a C++ object.
size_t numExpressions () const
Number of expressions managed by this object.
virtual void onContainerRestored () override
Called before calling DocumentObject::onDocumentRestored()
virtual void onRelabeledDocument (const App::Document &doc) override
void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
PropertyExpressionEngine ()
Construct a new PropertyExpressionEngine object.
virtual bool referenceChanged () const override
Test if the element reference has changed after restore.
void renameExpressions (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths)
Rename paths based on paths.
void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths)
Rename object identifiers in the registered expressions.
void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
virtual void setExpressions (std::map< App::ObjectIdentifier, App::ExpressionPtr > &&exprs) override
void setPyObject (PyObject *) override
void setValidator (ValidatorFunc f)
void setValue ()
void setValue (const App::ObjectIdentifier &path, std::shared_ptr< App::Expression > expr)
Set expression with optional comment for path.
virtual void updateElementReference (App::DocumentObject *feature, bool reverse=false, bool notify=false) override
Link type property interface APIs These APIs are moved here so that any type of property can have the property link behavior, e.g.
std::string validateExpression (const App::ObjectIdentifier &path, std::shared_ptr< const App::Expression > expr) const
Validate the given path and expression.
~PropertyExpressionEngine ()
Destroy the PropertyExpressionEngine object.
Public Member Functions inherited from App::PropertyExpressionContainer
virtual std::map< App::ObjectIdentifier, const App::Expression * > getExpressions () const =0
PropertyExpressionContainer ()
virtual void setExpressions (std::map< App::ObjectIdentifier, App::ExpressionPtr > &&exprs)=0
virtual ~PropertyExpressionContainer ()
Public Member Functions inherited from App::PropertyXLinkContainer
virtual void afterRestore () override
Called at the beginning of Document::afterRestore()
virtual void breakLink (App::DocumentObject *obj, bool clear) override
Called to reset this link property.
virtual int checkRestore (std::string *msg=nullptr) const override
Test if the link is restored unchanged.
virtual void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=nullptr, bool newStyle=true) const override
Obtain the linked objects.
bool isLinkedToDocument (const App::Document &doc) const
PropertyXLinkContainer ()
virtual void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &writer) const override
This method is used to save properties to an XML document.
~PropertyXLinkContainer ()
Public Member Functions inherited from App::PropertyLinkBase
virtual bool adjustLink (const std::set< App::DocumentObject * > &inList)=0
Called to adjust the link to avoid potential cyclic dependency.
virtual void breakLink (App::DocumentObject *obj, bool clear)=0
Called to reset this link property.
void checkLabelReferences (const std::vector< std::string > &subs, bool reset=true)
Check subnames for label registration.
virtual int checkRestore (std::string *msg=nullptr) const
Test if the link is restored unchanged.
virtual Property * CopyOnImportExternal (const std::map< std::string, std::string > &nameMap) const
Return a copy of the property if any changes caused by importing external linked object.
virtual Property * CopyOnLabelChange (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const
Update object label reference in this property.
virtual Property * CopyOnLinkReplace (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const =0
Return a copy of the property if the link replacement affects this property.
void getLinkedElements (std::map< App::DocumentObject *, std::vector< std::string > > &elements, bool newStyle=true, bool all=true) const
Helper function to return a map of linked object and its subname references.
template<class T >
void getLinkedObjects (T &inserter, bool all=false) const
Helper function to return linked objects using an std::inserter.
virtual void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=nullptr, bool newStyle=true) const =0
Obtain the linked objects.
virtual bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
std::map< App::DocumentObject *, std::vector< std::string > > linkedElements (bool newStyle=true, bool all=true) const
Helper function to return a map of linked object and its subname references.
std::vector< App::DocumentObject * > linkedObjects (bool all=false) const
Helper function to return all linked objects of this property.
PropertyLinkBase ()
virtual bool referenceChanged () const
Test if the element reference has changed after restore.
void registerLabelReferences (std::vector< std::string > &&labels, bool reset=true)
Register label reference for future object relabel update.
void setAllowExternal (bool allow)
Enable/disable temporary holding external object without throwing exception.
virtual void setAllowPartial (bool enable)
bool testFlag (int flag) const
void unregisterElementReference ()
Clear internal element reference registration.
void unregisterLabelReferences ()
Clear internal label references registration.
virtual void updateElementReference (App::DocumentObject *feature, bool reverse=false, bool notify=false)
Link type property interface APIs These APIs are moved here so that any type of property can have the property link behavior, e.g.
virtual ~PropertyLinkBase ()
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual Property * Copy (void) const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
int64_t getID () const
Return a unique ID for the property.
virtual unsigned int getMemSize (void) const override
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
const char * getName (void) const
Get the name of this property in the belonging container With hasName() it can be checked beforehand if a valid name is set.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
bool hasName () const
Check if the property has a name set.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::ScopedLink
LinkScope getScope () const
Get the links scope Retrieve what kind of links are allowed.
void setScope (LinkScope scope)
Set the links scope Allows to define what kind of links are allowed.
Public Attributes
boost::signals2::signal< void(const App::ObjectIdentifier &)> expressionChanged
signal called when an expression was changed
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions
virtual void hasSetValue () override
Gets called by all setValue() methods after the value has changed.
virtual void onRelabeledDocument (const App::Document &doc)=0
Protected Member Functions inherited from App::PropertyXLinkContainer
virtual void aboutToSetChildValue (App::Property &prop) override
Called before a child property changing value.
void clearDeps ()
virtual PropertyXLink * createXLink ()
virtual void onAddDep (App::DocumentObject *)
virtual void onBreakLink (App::DocumentObject *obj)
virtual void onRemoveDep (App::DocumentObject *)
void updateDeps (std::map< DocumentObject *, bool > &&newDeps)
Protected Member Functions inherited from App::PropertyLinkBase
virtual void hasSetValue () override
Gets called by all setValue() methods after the value has changed.
void setFlag (int flag, bool value=true)
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Friends
class AtomicPropertyChange
Additional Inherited Members
Static Public Member Functions inherited from App::PropertyLinkBase
static void breakLinks (App::DocumentObject *link, const std::vector< App::DocumentObject * > &objs, bool clear)
Helper function for breaking link properties.
static const char * exportSubName (std::string &output, const App::DocumentObject *obj, const char *subname, bool first_obj=false)
Helper function to export a subname reference.
static void getLabelReferences (std::vector< std::string > &labels, const char *subname)
Helper function to extract labels from a subname reference.
static std::string importSubName (Base::XMLReader &reader, const char *sub, bool &restoreLabel)
Helper function to import a subname reference.
static void restoreLabelReference (const App::DocumentObject *obj, std::string &sub, ShadowSub *shadow=nullptr)
Helper function to restore label references during import.
static App::DocumentObject * tryImport (const App::Document *doc, const App::DocumentObject *obj, const std::map< std::string, std::string > &nameMap)
Helper function for link import operation.
static std::string tryImportSubName (const App::DocumentObject *obj, const char *sub, const App::Document *doc, const std::map< std::string, std::string > &nameMap)
Helper function for link import operation.
static std::pair< App::DocumentObject *, std::string > tryReplaceLink (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const char *sub=nullptr)
Helper functions.
static std::pair< App::DocumentObject *, std::vector< std::string > > tryReplaceLinkSubs (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const std::vector< std::string > &subs)
Helper function to check and replace a link with multiple subname references.
static void updateElementReferences (DocumentObject *feature, bool reverse=false)
Update all element references in all link properties of feature.
static std::string updateLabelReference (const App::DocumentObject *linked, const char *subname, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
Helper function to update subname reference on label change.
static std::vector< std::pair< Property *, std::unique_ptr< Property > > > updateLabelReferences (App::DocumentObject *obj, const char *newLabel)
Helper function to collect changed property when an object re-label.
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Check if the passed name is valid.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Member Typedef Documentation
ValidatorFunc
typedef std::function<std::string (const App::ObjectIdentifier & path, std::shared_ptr<const App::Expression> expr)> App::PropertyExpressionEngine::ValidatorFunc
Member Enumeration Documentation
ExecuteOption
enum App::PropertyExpressionEngine::ExecuteOption
Execute options.
Enumerator
ExecuteAll
Execute all expression.
ExecuteOutput
Execute only output property bindings.
ExecuteNonOutput
Execute only non-output property bindings.
ExecuteOnRestore
Execute on document restore.
Constructor & Destructor Documentation
PropertyExpressionEngine()
PropertyExpressionEngine::PropertyExpressionEngine ()
Construct a new PropertyExpressionEngine object.
Referenced by Copy().
~PropertyExpressionEngine()
PropertyExpressionEngine::~PropertyExpressionEngine ()
Destroy the PropertyExpressionEngine object.
Member Function Documentation
adjustLink()
bool PropertyExpressionEngine::adjustLink (const std::set< App::DocumentObject * > & inList) override virtual
Called to adjust the link to avoid potential cyclic dependency.
Parameters
inList recursive in-list of the would-be parent
Returns
Return whether the link has been adjusted
This function tries to correct the link to avoid any (sub)object inside in-list. If the adjustment is impossible, exception will be raised
Implements App::PropertyLinkBase.
References AtomicPropertyChange, expressionChanged, and App::Property::getContainer().
afterRestore()
void PropertyExpressionEngine::afterRestore () override virtual
Called at the beginning of Document::afterRestore()
This function is called without dependency sorting, because some types of link property can only reconstructs the linking information inside this function.
One example use case of this function is PropertyLinkSub that uses afterRestore() to parse and restore subname references, which may contain sub-object reference from external document, and there will be special mapping required during object import.
Another example is PropertyExpressionEngine which only parse the restored expression in afterRestore(). The reason, in addition to subname mapping like PropertyLinkSub, is that it can handle document name adjustment as well. It internally relies on PropertyXLink to store the external document path for external linking. When the external document is restored, its internal name may change due to name conflict with existing documents. PropertyExpressionEngine can now auto adjust external references without any problem.
Reimplemented from App::PropertyXLinkContainer.
References App::PropertyXLinkContainer::afterRestore(), AtomicPropertyChange, App::Property::getContainer(), draftfunctions.move::move(), App::ObjectIdentifier::parse(), App::Expression::parse(), and setValue().
canonicalPath()
ObjectIdentifier PropertyExpressionEngine::canonicalPath (const App::ObjectIdentifier & p) const override virtual
Create a canonical object identifier of the given object p.
Parameters
p ObjectIndentifier
Returns
New ObjectIdentifier
Reimplemented from App::Property.
References App::Property::getContainer(), and Base::BaseClass::isDerivedFrom().
Referenced by getPathValue(), renameExpressions(), setValue(), and validateExpression().
Copy()
Property * PropertyExpressionEngine::Copy (void) const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References PropertyExpressionEngine().
CopyOnImportExternal()
Property * PropertyExpressionEngine::CopyOnImportExternal (const std::map< std::string, std::string > & nameMap) const override virtual
Return a copy of the property if any changes caused by importing external linked object.
Parameters
nameMap a map from the original external object name to the imported new object name
Returns
Returns a copy of the property with the updated link reference if affected. The copy will later be assgiend to this property by calling its Paste().
Reimplemented from App::PropertyLinkBase.
CopyOnLabelChange()
Property * PropertyExpressionEngine::CopyOnLabelChange (App::DocumentObject * obj, const std::string & ref, const char * newLabel) const override virtual
Update object label reference in this property.
Parameters
obj the object owner of the changing label
ref subname reference to old label
newLabel the future new label
Returns
Returns a copy of the property if its link reference is affected. The copy will later be assgiend to this property by calling its Paste().
Reimplemented from App::PropertyLinkBase.
CopyOnLinkReplace()
Property * PropertyExpressionEngine::CopyOnLinkReplace (const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj) const override virtual
Return a copy of the property if the link replacement affects this property.
Parameters
owner the parent object whose link property is to be replace. Note that The parent may not be the container of this property. Link sub property can use this opportunity to adjust its relative links.
oldObj object to be replaced
newObj object to replace with
Returns
Return a copy of the property that is adjusted for the link replacement operation.
Implements App::PropertyLinkBase.
depsAreTouched()
bool PropertyExpressionEngine::depsAreTouched () const
Determine whether any dependencies of any of the registered expressions have been touched.
Returns
True if at least on dependency has been touched.
execute()
DocumentObjectExecReturn * App::PropertyExpressionEngine::execute (ExecuteOption option = ExecuteAll, bool * touched = nullptr)
Evaluate the expressions.
Compute and update values of all registered expressions.
Parameters
option execution option, see ExecuteOption.
Returns
StdReturn on success.
References App::Property::EvalOnRestore, App::Property::getContainer(), App::Property::getFullName(), App::Property::getPathValue(), App::isAnyEqual(), App::Prop_Transient, App::Property::setPathValue(), App::DocumentObject::StdReturn, and App::Property::Transient.
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), PathScripts.PathDressupDogbone.ObjectDressup::boneStateList(), ArchSite.Compass::buildCoordinates(), PathScripts.PathDressupHoldingTags.ObjectTagDressup::generateTags(), ArchPanel.PanelCut::getWires(), ArchSchedule.CommandArchSchedule::IsActive(), Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), FeaturePython.DistanceBolt::onChanged(), PathScripts.PathStock.StockFromBase::onChanged(), PathScripts.PathStock.StockCreateBox::onChanged(), PathScripts.PathStock.StockCreateCylinder::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), draftobjects.patharray.PathArray::onDocumentRestored(), draftobjects.pathtwistedarray.PathTwistedArray::onDocumentRestored(), and Sketcher::SketchObject::setExpression().
getExpressions()
std::map< App::ObjectIdentifier, const App::Expression * > PropertyExpressionEngine::getExpressions () const override virtual
Implements App::PropertyExpressionContainer.
Referenced by App::Document::exportGraphviz(), and Spreadsheet::Sheet::updateBindings().
getMemSize()
unsigned int PropertyExpressionEngine::getMemSize (void) const override virtual
Estimate memory size of this property.
\fixme Should probably return something else than 0.
Returns
Size of object.
Reimplemented from App::Property.
getPathsToDocumentObject()
void PropertyExpressionEngine::getPathsToDocumentObject (DocumentObject * obj, std::vector< App::ObjectIdentifier > & paths) const
Find paths to document object.
Parameters
obj Document object
paths Object identifier
References App::Property::getContainer().
getPathValue()
const boost::any PropertyExpressionEngine::getPathValue (const App::ObjectIdentifier & path) const override virtual
Get expression for path.
Parameters
path ObjectIndentifier to query for.
Returns
Expression for path, or empty boost::any if not found.
Reimplemented from App::Property.
References canonicalPath().
getPyObject()
PyObject * PropertyExpressionEngine::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
hasSetValue()
void PropertyExpressionEngine::hasSetValue (void) override protected virtual
Gets called by all setValue() methods after the value has changed.
Reimplemented from App::PropertyLinkBase.
References draftgeoutils.faces::bind(), App::Property::getContainer(), App::ObjectIdentifier::getDep(), App::DocumentObject::getNameInDocument(), App::PropertyLinkBase::hasSetValue(), App::DocumentObject::isRestoring(), App::PropertyLinkBase::LinkDetached, draftfunctions.move::move(), App::PropertyLinkBase::registerLabelReferences(), App::PropertyLinkBase::testFlag(), App::PropertyLinkBase::unregisterElementReference(), and App::PropertyXLinkContainer::updateDeps().
Referenced by renameExpressions().
numExpressions()
size_t PropertyExpressionEngine::numExpressions () const
Number of expressions managed by this object.
Returns
Number of expressions.
onContainerRestored()
void PropertyExpressionEngine::onContainerRestored () override virtual
Called before calling DocumentObject::onDocumentRestored()
This function is called after finished calling Property::afterRestore() of all properties of objects. By then, the object dependency information is assumed ready. So, unlike Property::afterRestore(), this function is called on objects with dependency order.
Reimplemented from App::Property.
References App::PropertyLinkBase::unregisterElementReference().
onRelabeledDocument()
void PropertyExpressionEngine::onRelabeledDocument (const App::Document & doc) override virtual
Implements App::PropertyExpressionContainer.
Paste()
void PropertyExpressionEngine::Paste (const Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References AtomicPropertyChange, and expressionChanged.
referenceChanged()
bool PropertyExpressionEngine::referenceChanged () const override virtual
Test if the element reference has changed after restore.
Reimplemented from App::PropertyLinkBase.
renameExpressions()
void PropertyExpressionEngine::renameExpressions (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > & paths)
Rename paths based on paths.
Parameters
paths Map with current and new object identifier.
References App::Property::aboutToSetValue(), canonicalPath(), expressionChanged, and hasSetValue().
Referenced by Sketcher::SketchObject::constraintsRenamed().
renameObjectIdentifiers()
void PropertyExpressionEngine::renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > & paths)
Rename object identifiers in the registered expressions.
Parameters
paths Map with current and new object identifiers.
Restore()
void PropertyExpressionEngine::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from App::PropertyXLinkContainer.
References Base::XMLReader::getAttribute(), Base::XMLReader::getAttributeAsFloat(), Base::XMLReader::getAttributeAsInteger(), Base::XMLReader::hasAttribute(), Base::XMLReader::readElement(), Base::XMLReader::readEndElement(), and App::PropertyXLinkContainer::Restore().
Save()
void PropertyExpressionEngine::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from App::PropertyXLinkContainer.
References Base::Writer::decInd(), Base::Persistence::encodeAttribute(), Base::Writer::incInd(), Base::Writer::ind(), App::PropertyXLinkContainer::Save(), and Base::Writer::Stream().
setExpressions()
void PropertyExpressionEngine::setExpressions (std::map< App::ObjectIdentifier, App::ExpressionPtr > && exprs) override virtual
Implements App::PropertyExpressionContainer.
References AtomicPropertyChange, draftfunctions.move::move(), and setValue().
setPyObject()
void PropertyExpressionEngine::setPyObject (PyObject *) override virtual
Reimplemented from Base::BaseClass.
setValidator()
void App::PropertyExpressionEngine::setValidator (ValidatorFunc f)
setValue() [1/2]
void App::PropertyExpressionEngine::setValue ()
Referenced by afterRestore(), Sketcher::SketchObject::constraintsRemoved(), Gui::ExpressionBinding::setExpression(), and setExpressions().
setValue() [2/2]
void PropertyExpressionEngine::setValue (const App::ObjectIdentifier & path, std::shared_ptr< App::Expression > expr)
Set expression with optional comment for path.
Parameters
path Path to update
expr New expression
comment Optional comment.
References AtomicPropertyChange, canonicalPath(), expressionChanged, App::Property::getPathValue(), App::ObjectIdentifier::getProperty(), and validateExpression().
updateElementReference()
void PropertyExpressionEngine::updateElementReference (App::DocumentObject * feature, bool reverse = false, bool notify = false) override virtual
Link type property interface APIs These APIs are moved here so that any type of property can have the property link behavior, e.g.
the PropertyExpressionEngine Called to update the element reference of this link property
See also
_updateElementReference()
Reimplemented from App::PropertyLinkBase.
References expressionChanged, App::Property::getContainer(), femsolver.signal::notify(), App::DocumentObject::onUpdateElementReference(), and App::PropertyLinkBase::unregisterElementReference().
validateExpression()
std::string PropertyExpressionEngine::validateExpression (const App::ObjectIdentifier & path, std::shared_ptr< const App::Expression > expr) const
Validate the given path and expression.
Parameters
path Object Identifier for expression.
expr Expression tree.
Returns
Empty string on success, error message on failure.
References canonicalPath(), App::ObjectIdentifier::getDocumentObject(), and App::DocumentObject::getInListEx().
Referenced by Gui::ExpressionBinding::setExpression(), and setValue().
Friends And Related Function Documentation
AtomicPropertyChange
friend class AtomicPropertyChange friend
Referenced by adjustLink(), afterRestore(), Paste(), setExpressions(), and setValue().
Member Data Documentation
expressionChanged
boost::signals2::signal<void (const App::ObjectIdentifier &)> App::PropertyExpressionEngine::expressionChanged
signal called when an expression was changed
Referenced by adjustLink(), Gui::ExpressionBinding::bind(), Paste(), renameExpressions(), setValue(), and updateElementReference().
The documentation for this class was generated from the following files:
FreeCAD/src/App/PropertyExpressionEngine.h
FreeCAD/src/App/PropertyExpressionEngine.cpp