FreeCAD: TechDrawTools.TDToolsMovers Namespace Reference
TechDrawTools.TDToolsMovers Namespace Reference
Functions
def moveView (view, fromPage, toPage, copy=False)
def projGroupMove (view, fromPage, toPage, copy)
def sectionViewMove (view, fromPage, toPage, copy)
def simpleViewMove (view, fromPage, toPage, copy)
Function Documentation
moveView()
def TechDrawTools.TDToolsMovers.moveView (view, fromPage, toPage, copy = False)
References TechDrawTools.TDToolsMovers.projGroupMove(), TechDrawTools.TDToolsMovers.sectionViewMove(), and TechDrawTools.TDToolsMovers.simpleViewMove().
projGroupMove()
def TechDrawTools.TDToolsMovers.projGroupMove (view, fromPage, toPage, copy)
Referenced by TechDrawTools.TDToolsMovers.moveView().
sectionViewMove()
def TechDrawTools.TDToolsMovers.sectionViewMove (view, fromPage, toPage, copy)
References TechDrawTools.TDToolsMovers.simpleViewMove().
Referenced by TechDrawTools.TDToolsMovers.moveView().
simpleViewMove()
def TechDrawTools.TDToolsMovers.simpleViewMove (view, fromPage, toPage, copy)
Referenced by TechDrawTools.TDToolsMovers.moveView(), and TechDrawTools.TDToolsMovers.sectionViewMove().