FreeCAD: U16 Struct Reference
U16 Struct Reference
#include <U16.h>
Public Member Functions
operator uint16_t () const
void read (Context &cont)
U16 ()
U16 (Context &cont)
U16 (uint16_t ui)
Constructor & Destructor Documentation
U16() [1/3]
U16::U16 ()
U16() [2/3]
U16::U16 (uint16_t ui)
U16() [3/3]
U16::U16 (Context & cont)
References read().
Member Function Documentation
operator uint16_t()
U16::operator uint16_t () const
read()
void U16::read (Context & cont)
References Context::Strm.
Referenced by gzip_utf8.GzipFile::readline(), gzip_utf8.GzipFile::seek(), and U16().
The documentation for this struct was generated from the following file:
FreeCAD/src/Mod/JtReader/App/JrJt/U16.h