FreeCAD: Gui::ConsoleMessageTask Class Reference
Gui::ConsoleMessageTask Class Reference
Public Member Functions
void run ()
Member Function Documentation
run()
void Gui::ConsoleMessageTask::run ()
References Base::Console(), and Base::ConsoleSingleton::Message().
Referenced by femexamples.examplesgui.FemExamples::clicked(), and femsolver.task.Task::protector().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/CommandTest.cpp