FreeCAD: Gui::PythonEditorView Class Reference
Gui::PythonEditorView Class Reference
#include <EditorView.h>
Public Slots
void executeScript ()
Runs the opened script in the macro manager.
void hideDebugMarker ()
void showDebugMarker (int line)
void startDebug ()
void toggleBreakpoint ()
Public Slots inherited from Gui::MDIView
virtual void setOverrideCursor (const QCursor &)
virtual void restoreOverrideCursor ()
Public Member Functions
bool onHasMsg (const char *pMsg) const
Checks if the action pMsg is available.
bool onMsg (const char *pMsg, const char **ppReturn)
Runs the action specified by pMsg.
PythonEditorView (PythonEditor *editor, QWidget *parent)
~PythonEditorView ()
Public Member Functions inherited from Gui::EditorView
bool canClose (void)
Checking on close state.
EditorView (QPlainTextEdit *editor, QWidget *parent)
Constructs a EditorView which is a child of 'parent', with the name 'name'.
QPlainTextEdit * getEditor () const
const char * getName (void) const
returns the name of the view (important for messages)
void OnChange (Base::Subject< const char * > &rCaller, const char *rcReason)
void onUpdate (void)
get called when the document is updated
void setDisplayName (DisplayName)
~EditorView ()
Destroys the object and frees any allocated resources.
bool open (const QString &f)
Opens the file fileName.
bool saveAs ()
Saves the content of the editor to a file specified by the appearing file dialog.
void cut ()
Copies the selected text to the clipboard and deletes it from the text edit.
void copy ()
Copies any selected text to the clipboard.
void paste ()
Pastes the text from the clipboard into the text edit at the current cursor position.
void undo ()
Undoes the last operation.
void redo ()
Redoes the last operation.
void print ()
Shows the printer dialog.
void printPdf ()
Prints the document into a Pdf file.
void printPreview ()
Show a preview dialog.
void print (QPrinter *)
QStringList undoActions () const
Get the undo history.
QStringList redoActions () const
Get the redo history.
QString fileName () const
Public Member Functions inherited from Gui::MDIView
virtual void deleteSelf ()
delete itself
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
View constructor Attach the view to the given document.
virtual void onRelabel (Gui::Document *pDoc)
get called when the document is updated
virtual void viewAll ()
~MDIView ()
View destructor Detach the view from the document, if attached.
QSize minimumSizeHint () const
virtual void setCurrentViewMode (ViewMode mode)
If b is set to FullScreen the MDI view is displayed in full screen mode, if b is set to TopLevel then it is displayed as an own top-level window, otherwise (Normal) as tabbed window.
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=0, std::string *subname=0) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=0)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=0) const
virtual bool containsViewProvider (const ViewProvider *) const
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=0)
View constructor Attach the view to the given document.
virtual ~BaseView ()
View destructor Detach the view from the document, if attached!
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose (void)
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive (void) const
indicates if the view is in passive mode
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
virtual Type getTypeId (void) const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Gui::WindowParameter
ParameterGrp::handle getWindowParameter (void)
return the parameter group of this window
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason)
bool setGroupName (const char *name)
Sets the group of the window to name.
WindowParameter (const char *name)
virtual ~WindowParameter ()
Additional Inherited Members
Public Types inherited from Gui::EditorView
enum DisplayName { FullName, FileName, BaseName }
Public Types inherited from Gui::MDIView
enum ViewMode { Child, TopLevel, FullScreen }
MDI view mode enum.
Signals inherited from Gui::EditorView
void changeFileName (const QString &)
Signals inherited from Gui::MDIView
void message (const QString &, int)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter (void)
get the parameters
Protected Slots inherited from Gui::MDIView
virtual void windowStateChanged (MDIView *)
This method gets called from the main window this view is attached to whenever the window state of the active view changes.
Protected Member Functions inherited from Gui::EditorView
void focusInEvent (QFocusEvent *e)
void showEvent (QShowEvent *)
void hideEvent (QHideEvent *)
void closeEvent (QCloseEvent *)
Protected Member Functions inherited from Gui::MDIView
void closeEvent (QCloseEvent *e)
void changeEvent (QEvent *e)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::MDIView
PyObject * pythonObject
Protected Attributes inherited from Gui::BaseView
bool bIsDetached
bool bIsPassive
Constructor & Destructor Documentation
PythonEditorView()
PythonEditorView::PythonEditorView (PythonEditor * editor, QWidget * parent)
References Gui::EditorView::changeFileName(), and draftgeoutils.intersections::connect().
~PythonEditorView()
PythonEditorView::~PythonEditorView ()
Member Function Documentation
executeScript
void PythonEditorView::executeScript () slot
Runs the opened script in the macro manager.
References Gui::MacroManager::File, Gui::EditorView::fileName(), Gui::Application::Instance, Gui::Application::macroManager(), Gui::EditorView::onHasMsg(), Gui::EditorView::onMsg(), and Gui::MacroManager::run().
Referenced by onMsg().
hideDebugMarker
void PythonEditorView::hideDebugMarker () slot
Referenced by Gui::PythonDebugger::hideDebugMarker().
onHasMsg()
bool PythonEditorView::onHasMsg (const char * pMsg) const virtual
Checks if the action pMsg is available.
This is for enabling/disabling the corresponding buttons or menu items for this action.
Reimplemented from Gui::EditorView.
References Gui::EditorView::onHasMsg().
onMsg()
bool PythonEditorView::onMsg (const char * pMsg, const char ** ppReturn) virtual
Runs the action specified by pMsg.
Reimplemented from Gui::EditorView.
References executeScript(), Gui::EditorView::onMsg(), startDebug(), and toggleBreakpoint().
showDebugMarker
void PythonEditorView::showDebugMarker (int line) slot
Referenced by Gui::PythonDebugger::showDebugMarker().
startDebug
void PythonEditorView::startDebug () slot
Referenced by onMsg().
toggleBreakpoint
void PythonEditorView::toggleBreakpoint () slot
Referenced by onMsg().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/EditorView.h
Sources/FreeCAD/src/Gui/EditorView.cpp