FreeCAD: App::DocumentObjectExtension Class Reference
App::DocumentObjectExtension Class Reference
Extension with special document object calls.
#include <DocumentObjectExtension.h>
Public Member Functions
DocumentObjectExtension ()
virtual App::DocumentObjectExecReturn * extensionExecute ()
virtual bool extensionGetLinkedObject (DocumentObject *&ret, bool recursive, Base::Matrix4D *mat, bool transform, int depth) const
Get the linked object.
virtual bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const
Get the sub object by name.
virtual bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const
Get name references of all sub objects.
virtual bool extensionHasChildElement () const
virtual int extensionIsElementVisible (const char *)
virtual short extensionMustExecute ()
virtual int extensionSetElementVisible (const char *, bool)
App::DocumentObject * getExtendedObject ()
const App::DocumentObject * getExtendedObject () const
virtual PyObject * getExtensionPyObject () override
virtual const char * getViewProviderExtensionName () const
returns the type name of the ViewProviderExtension which is automatically attached to the viewprovider object when it is initiated
virtual void onExtendedDocumentRestored ()
get called after a document has been fully restored
virtual void onExtendedSettingDocument ()
get called after setting the document
virtual void onExtendedSetupObject ()
get called after a brand new object was created
virtual void onExtendedUnsetupObject ()
get called when object is going to be removed from the document
virtual ~DocumentObjectExtension ()
Public Member Functions inherited from App::Extension
Extension ()
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
virtual PyObject * getExtensionPyObject ()
virtual void initExtension (App::ExtensionContainer *obj)
bool isPythonExtension ()
std::string name () const
virtual ~Extension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Additional Inherited Members
Protected Member Functions inherited from App::Extension
virtual void extensionOnChanged (const Property *p)
void initExtensionType (Base::Type type)
Static Protected Member Functions inherited from App::Extension
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
Extension with special document object calls.
Constructor & Destructor Documentation
DocumentObjectExtension()
DocumentObjectExtension::DocumentObjectExtension ()
~DocumentObjectExtension()
DocumentObjectExtension::~DocumentObjectExtension () virtual
Member Function Documentation
extensionExecute()
App::DocumentObjectExecReturn * DocumentObjectExtension::extensionExecute (void) virtual
Reimplemented in App::OriginGroupExtension, Part::AttachExtension, Part::PrismExtension, App::GroupExtension, and App::LinkBaseExtension.
References App::DocumentObject::StdReturn.
Referenced by Part::AttachExtension::extensionExecute(), Part::PrismExtension::extensionExecute(), App::GroupExtension::extensionExecute(), and App::LinkBaseExtension::extensionExecute().
extensionGetLinkedObject()
bool DocumentObjectExtension::extensionGetLinkedObject (DocumentObject *& ret, bool recursive, Base::Matrix4D * mat, bool transform, int depth) const virtual
Get the linked object.
See also
DocumentObject::getLinkedObject()
Returns
Return turn if handled, the linked object is returned in ret
Reimplemented in App::LinkBaseExtension.
extensionGetSubObject()
bool DocumentObjectExtension::extensionGetSubObject (DocumentObject *& ret, const char * subname, PyObject ** pyObj, Base::Matrix4D * mat, bool transform, int depth) const virtual
Get the sub object by name.
See also
DocumentObject::getSubObject()
Returns
Return turn if handled, the sub object is returned in ret
Reimplemented in App::GeoFeatureGroupExtension, App::GroupExtension, App::OriginGroupExtension, and App::LinkBaseExtension.
extensionGetSubObjects()
bool DocumentObjectExtension::extensionGetSubObjects (std::vector< std::string > & ret, int reason) const virtual
Get name references of all sub objects.
See also
DocumentObject::getSubObjects()
Returns
Return turn if handled, the sub object is returned in ret
Reimplemented in App::GeoFeatureGroupExtension, App::GroupExtension, and App::LinkBaseExtension.
extensionHasChildElement()
virtual bool App::DocumentObjectExtension::extensionHasChildElement () const virtual
Reimplemented in App::LinkBaseExtension.
extensionIsElementVisible()
virtual int App::DocumentObjectExtension::extensionIsElementVisible (const char *) virtual
Reimplemented in App::LinkBaseExtension.
extensionMustExecute()
short int DocumentObjectExtension::extensionMustExecute (void) virtual
Reimplemented in App::OriginGroupExtension, Part::AttachExtension, Part::PrismExtension, and App::LinkBaseExtension.
Referenced by App::OriginGroupExtension::extensionMustExecute().
extensionSetElementVisible()
virtual int App::DocumentObjectExtension::extensionSetElementVisible (const char * , bool) virtual
Reimplemented in App::LinkBaseExtension.
getExtendedObject() [1/2]
DocumentObject * DocumentObjectExtension::getExtendedObject ()
References Base::Persistence::getClassTypeId(), and App::Extension::getExtendedContainer().
Referenced by PartDesign::Body::addObject(), App::GroupExtension::addObject(), App::GroupExtension::addObjects(), App::GeoFeatureGroupExtension::addObjects(), Part::AttachExtension::extensionOnChanged(), App::GeoFeatureGroupExtension::extensionOnChanged(), App::GroupExtension::extensionOnChanged(), App::OriginGroupExtension::extensionOnChanged(), TechDraw::CosmeticExtension::getCenterLineBySelection(), TechDraw::CosmeticExtension::getCosmeticEdgeBySelection(), TechDraw::CosmeticExtension::getCosmeticVertexBySelection(), TechDraw::CosmeticExtension::getGeomFormatBySelection(), App::GroupExtension::getObject(), App::OriginGroupExtension::getOrigin(), Part::AttachExtension::getPlacement(), App::GeoFeatureGroupExtension::globalGroupPlacement(), App::GroupExtension::hasObject(), App::GroupExtension::isChildOf(), App::OriginGroupExtension::onExtendedSetupObject(), and App::LinkBaseExtension::updateGroup().
getExtendedObject() [2/2]
const DocumentObject * DocumentObjectExtension::getExtendedObject () const
References Base::Persistence::getClassTypeId(), and App::Extension::getExtendedContainer().
getExtensionPyObject()
PyObject * DocumentObjectExtension::getExtensionPyObject (void) override virtual
Reimplemented from App::Extension.
Reimplemented in Part::AttachExtension, TechDraw::CosmeticExtension, App::GroupExtension, and App::LinkBaseExtension.
References App::Extension::ExtensionPythonObject.
getViewProviderExtensionName()
virtual const char * App::DocumentObjectExtension::getViewProviderExtensionName () const virtual
returns the type name of the ViewProviderExtension which is automatically attached to the viewprovider object when it is initiated
onExtendedDocumentRestored()
void DocumentObjectExtension::onExtendedDocumentRestored () virtual
get called after a document has been fully restored
Reimplemented in Part::AttachExtension, App::LinkBaseExtension, and App::LinkExtension.
Referenced by App::LinkBaseExtension::onExtendedDocumentRestored().
onExtendedSettingDocument()
void DocumentObjectExtension::onExtendedSettingDocument () virtual
get called after setting the document
onExtendedSetupObject()
void DocumentObjectExtension::onExtendedSetupObject () virtual
get called after a brand new object was created
Reimplemented in App::OriginGroupExtension.
Referenced by App::OriginGroupExtension::onExtendedSetupObject().
onExtendedUnsetupObject()
void DocumentObjectExtension::onExtendedUnsetupObject () virtual
get called when object is going to be removed from the document
Reimplemented in App::LinkBaseExtension, and App::OriginGroupExtension.
Referenced by App::OriginGroupExtension::onExtendedUnsetupObject().
The documentation for this class was generated from the following files:
FreeCAD/src/App/DocumentObjectExtension.h
FreeCAD/src/App/DocumentObjectExtension.cpp