FreeCAD: Part::PointConstraintPy Class Reference
Part::PointConstraintPy Class Reference
The python export class for GeomPlate_PointConstraint.
#include <PointConstraintPy.h>
Public Types
typedef GeomPlate_PointConstraint * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
PointConstraintPy (GeomPlate_PointConstraint *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomPlate_PointConstraint * getGeomPlate_PointConstraintPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of PointConstraintPy.
static PyMethodDef Methods []
Methods structure of PointConstraintPy.
static PyTypeObject Type
Type structure of PointConstraintPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~PointConstraintPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * setOrder (PyObject *args)
implementer for the setOrder() method
PyObject * order (PyObject *args)
implementer for the order() method
PyObject * G0Criterion (PyObject *args)
implementer for the G0Criterion() method
PyObject * G1Criterion (PyObject *args)
implementer for the G1Criterion() method
PyObject * G2Criterion (PyObject *args)
implementer for the G2Criterion() method
PyObject * setG0Criterion (PyObject *args)
implementer for the setG0Criterion() method
PyObject * setG1Criterion (PyObject *args)
implementer for the setG1Criterion() method
PyObject * setG2Criterion (PyObject *args)
implementer for the setG2Criterion() method
PyObject * hasPnt2dOnSurf (PyObject *args)
implementer for the hasPnt2dOnSurf() method
PyObject * setPnt2dOnSurf (PyObject *args)
implementer for the setPnt2dOnSurf() method
PyObject * pnt2dOnSurf (PyObject *args)
implementer for the pnt2dOnSurf() method
static PyObject * staticCallback_setOrder (PyObject *self, PyObject *args)
callback for the setOrder() method
static PyObject * staticCallback_order (PyObject *self, PyObject *args)
callback for the order() method
static PyObject * staticCallback_G0Criterion (PyObject *self, PyObject *args)
callback for the G0Criterion() method
static PyObject * staticCallback_G1Criterion (PyObject *self, PyObject *args)
callback for the G1Criterion() method
static PyObject * staticCallback_G2Criterion (PyObject *self, PyObject *args)
callback for the G2Criterion() method
static PyObject * staticCallback_setG0Criterion (PyObject *self, PyObject *args)
callback for the setG0Criterion() method
static PyObject * staticCallback_setG1Criterion (PyObject *self, PyObject *args)
callback for the setG1Criterion() method
static PyObject * staticCallback_setG2Criterion (PyObject *self, PyObject *args)
callback for the setG2Criterion() method
static PyObject * staticCallback_hasPnt2dOnSurf (PyObject *self, PyObject *args)
callback for the hasPnt2dOnSurf() method
static PyObject * staticCallback_setPnt2dOnSurf (PyObject *self, PyObject *args)
callback for the setPnt2dOnSurf() method
static PyObject * staticCallback_pnt2dOnSurf (PyObject *self, PyObject *args)
callback for the pnt2dOnSurf() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeomPlate_PointConstraint.
Member Typedef Documentation
PointerType
typedef GeomPlate_PointConstraint* Part::PointConstraintPy::PointerType
Constructor & Destructor Documentation
~PointConstraintPy()
PointConstraintPy::~PointConstraintPy () protected
PointConstraintPy()
PointConstraintPy::PointConstraintPy (GeomPlate_PointConstraint * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
G0Criterion()
PyObject * PointConstraintPy::G0Criterion (PyObject * args)
implementer for the G0Criterion() method
References getGeomPlate_PointConstraintPtr().
Referenced by staticCallback_G0Criterion().
G1Criterion()
PyObject * PointConstraintPy::G1Criterion (PyObject * args)
implementer for the G1Criterion() method
References getGeomPlate_PointConstraintPtr().
Referenced by staticCallback_G1Criterion().
G2Criterion()
PyObject * PointConstraintPy::G2Criterion (PyObject * args)
implementer for the G2Criterion() method
References getGeomPlate_PointConstraintPtr().
Referenced by staticCallback_G2Criterion().
getCustomAttributes()
PyObject * PointConstraintPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getGeomPlate_PointConstraintPtr()
GeomPlate_PointConstraint * PointConstraintPy::getGeomPlate_PointConstraintPtr (void) const
getter for the object handled by this class
Referenced by G0Criterion(), G1Criterion(), G2Criterion(), hasPnt2dOnSurf(), order(), pnt2dOnSurf(), setG0Criterion(), setG1Criterion(), setG2Criterion(), setOrder(), and setPnt2dOnSurf().
GetType()
virtual PyTypeObject* Part::PointConstraintPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
hasPnt2dOnSurf()
PyObject * PointConstraintPy::hasPnt2dOnSurf (PyObject * args)
implementer for the hasPnt2dOnSurf() method
References getGeomPlate_PointConstraintPtr().
Referenced by staticCallback_hasPnt2dOnSurf().
order()
PyObject * PointConstraintPy::order (PyObject * args)
implementer for the order() method
References getGeomPlate_PointConstraintPtr().
Referenced by setOrder(), and staticCallback_order().
pnt2dOnSurf()
PyObject * PointConstraintPy::pnt2dOnSurf (PyObject * args)
implementer for the pnt2dOnSurf() method
References getGeomPlate_PointConstraintPtr().
Referenced by staticCallback_pnt2dOnSurf().
PyInit()
int PointConstraintPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
References Base::PyObjectBase::setTwinPointer(), and Base::VectorPy::Type.
PyMake()
PyObject * PointConstraintPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References PointConstraintPy().
representation()
std::string PointConstraintPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int PointConstraintPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setG0Criterion()
PyObject * PointConstraintPy::setG0Criterion (PyObject * args)
implementer for the setG0Criterion() method
References getGeomPlate_PointConstraintPtr().
Referenced by staticCallback_setG0Criterion().
setG1Criterion()
PyObject * PointConstraintPy::setG1Criterion (PyObject * args)
implementer for the setG1Criterion() method
References getGeomPlate_PointConstraintPtr().
Referenced by staticCallback_setG1Criterion().
setG2Criterion()
PyObject * PointConstraintPy::setG2Criterion (PyObject * args)
implementer for the setG2Criterion() method
References getGeomPlate_PointConstraintPtr().
Referenced by staticCallback_setG2Criterion().
setOrder()
PyObject * PointConstraintPy::setOrder (PyObject * args)
implementer for the setOrder() method
References getGeomPlate_PointConstraintPtr(), and order().
Referenced by staticCallback_setOrder().
setPnt2dOnSurf()
PyObject * PointConstraintPy::setPnt2dOnSurf (PyObject * args)
implementer for the setPnt2dOnSurf() method
References getGeomPlate_PointConstraintPtr().
Referenced by staticCallback_setPnt2dOnSurf().
staticCallback_G0Criterion()
PyObject * PointConstraintPy::staticCallback_G0Criterion (PyObject * self, PyObject * args) static
callback for the G0Criterion() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, G0Criterion(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_G1Criterion()
PyObject * PointConstraintPy::staticCallback_G1Criterion (PyObject * self, PyObject * args) static
callback for the G1Criterion() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, G1Criterion(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_G2Criterion()
PyObject * PointConstraintPy::staticCallback_G2Criterion (PyObject * self, PyObject * args) static
callback for the G2Criterion() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, G2Criterion(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_hasPnt2dOnSurf()
PyObject * PointConstraintPy::staticCallback_hasPnt2dOnSurf (PyObject * self, PyObject * args) static
callback for the hasPnt2dOnSurf() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, hasPnt2dOnSurf(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_order()
PyObject * PointConstraintPy::staticCallback_order (PyObject * self, PyObject * args) static
callback for the order() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), order(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_pnt2dOnSurf()
PyObject * PointConstraintPy::staticCallback_pnt2dOnSurf (PyObject * self, PyObject * args) static
callback for the pnt2dOnSurf() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), pnt2dOnSurf(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_setG0Criterion()
PyObject * PointConstraintPy::staticCallback_setG0Criterion (PyObject * self, PyObject * args) static
callback for the setG0Criterion() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setG0Criterion(), and Base::PyObjectBase::startNotify().
staticCallback_setG1Criterion()
PyObject * PointConstraintPy::staticCallback_setG1Criterion (PyObject * self, PyObject * args) static
callback for the setG1Criterion() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setG1Criterion(), and Base::PyObjectBase::startNotify().
staticCallback_setG2Criterion()
PyObject * PointConstraintPy::staticCallback_setG2Criterion (PyObject * self, PyObject * args) static
callback for the setG2Criterion() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setG2Criterion(), and Base::PyObjectBase::startNotify().
staticCallback_setOrder()
PyObject * PointConstraintPy::staticCallback_setOrder (PyObject * self, PyObject * args) static
callback for the setOrder() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setOrder(), and Base::PyObjectBase::startNotify().
staticCallback_setPnt2dOnSurf()
PyObject * PointConstraintPy::staticCallback_setPnt2dOnSurf (PyObject * self, PyObject * args) static
callback for the setPnt2dOnSurf() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), setPnt2dOnSurf(), and Base::PyObjectBase::startNotify().
Member Data Documentation
GetterSetter
PyGetSetDef PointConstraintPy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of PointConstraintPy.
Methods
PyMethodDef PointConstraintPy::Methods static
Methods structure of PointConstraintPy.
Type
PyTypeObject PointConstraintPy::Type static
Type structure of PointConstraintPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), Part::BuildPlateSurfacePy::add(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeomPlate/PointConstraintPy.h
Sources/FreeCAD/src/Mod/Part/App/GeomPlate/PointConstraintPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/GeomPlate/PointConstraintPy.cpp