FreeCAD: App::SubObjectT Class Reference
App::SubObjectT Class Reference
#include <DocumentObserver.h>
Public Member Functions
const char * getElementName () const
Return the sub-element (Face, Edge, etc) of the subname path.
std::string getNewElementName () const
Return the new style sub-element name.
std::string getObjectFullName (const char *docName=nullptr) const
Return docname::objname (label)
std::string getOldElementName (int *index=nullptr) const
Return the old style sub-element name.
const std::string & getSubName () const
Return the subname path.
std::string getSubNameNoElement () const
Return the subname path without sub-element.
DocumentObject * getSubObject () const
Return the sub-object.
std::string getSubObjectFullName (const char *docName=nullptr) const
Return docname::objname.subname (label)
std::vector< DocumentObject * > getSubObjectList () const
Return all objects along the subname path.
std::string getSubObjectPython (bool force=true) const
bool operator< (const SubObjectT &other) const
SubObjectT & operator= (const App::DocumentObject *)
SubObjectT & operator= (const DocumentObjectT &)
SubObjectT & operator= (const SubObjectT &)
SubObjectT & operator= (SubObjectT &&)
bool operator== (const SubObjectT &) const
void setSubName (const char *subname)
Set the subname path to the sub-object.
void setSubName (const std::string &subname)
Set the subname path to the sub-object.
SubObjectT ()
SubObjectT (const char *docName, const char *objName, const char *subname)
SubObjectT (const DocumentObject *)
SubObjectT (const DocumentObject *, const char *subname)
SubObjectT (const DocumentObjectT &obj, const char *subname)
SubObjectT (const SubObjectT &)
SubObjectT (SubObjectT &&)
Public Member Functions inherited from App::DocumentObjectT
DocumentObjectT ()
DocumentObjectT (const char *docName, const char *objName)
DocumentObjectT (const Document *, const std::string &objName)
DocumentObjectT (const DocumentObject *)
DocumentObjectT (const DocumentObjectT &)
DocumentObjectT (const Property *)
DocumentObjectT (DocumentObjectT &&)
Document * getDocument () const
const std::string & getDocumentName () const
std::string getDocumentPython () const
DocumentObject * getObject () const
template<typename T >
T * getObjectAs () const
const std::string & getObjectLabel () const
const std::string & getObjectName () const
std::string getObjectPython () const
Property * getProperty () const
template<typename T >
T * getPropertyAs () const
const std::string & getPropertyName () const
std::string getPropertyPython () const
void operator= (const DocumentObject *)
DocumentObjectT & operator= (const DocumentObjectT &)
void operator= (const Property *)
DocumentObjectT & operator= (DocumentObjectT &&)
bool operator== (const DocumentObjectT &) const
~DocumentObjectT ()
Constructor & Destructor Documentation
SubObjectT() [1/7]
SubObjectT::SubObjectT ()
Constructor
SubObjectT() [2/7]
SubObjectT::SubObjectT (const SubObjectT & other)
Constructor
SubObjectT() [3/7]
SubObjectT::SubObjectT (SubObjectT && other)
Constructor
SubObjectT() [4/7]
SubObjectT::SubObjectT (const DocumentObjectT & obj, const char * subname)
Constructor
SubObjectT() [5/7]
SubObjectT::SubObjectT (const DocumentObject * obj, const char * subname)
Constructor
SubObjectT() [6/7]
SubObjectT::SubObjectT (const DocumentObject * obj)
Constructor
SubObjectT() [7/7]
SubObjectT::SubObjectT (const char * docName, const char * objName, const char * subname)
Constructor
Member Function Documentation
getElementName()
const char * SubObjectT::getElementName () const
Return the sub-element (Face, Edge, etc) of the subname path.
References Data::ComplexGeoData::findElementName().
getNewElementName()
std::string SubObjectT::getNewElementName () const
Return the new style sub-element name.
References App::DocumentObjectT::getObject(), draftfunctions.move::move(), and App::GeoFeature::resolveElement().
getObjectFullName()
std::string SubObjectT::getObjectFullName (const char * docName = nullptr) const
Return docname::objname (label)
Parameters
docName optional document name. The document prefix will only be printed if it is different then the given 'doc'.
References App::DocumentObjectT::getDocument(), App::DocumentObjectT::getDocumentName(), App::DocumentObjectT::getObjectLabel(), and App::DocumentObjectT::getObjectName().
Referenced by getSubObjectFullName().
getOldElementName()
std::string SubObjectT::getOldElementName (int * index = nullptr) const
Return the old style sub-element name.
Parameters
index if given, then return the element type, and extract the index
References App::DocumentObjectT::getObject(), draftfunctions.move::move(), and App::GeoFeature::resolveElement().
getSubName()
const std::string & SubObjectT::getSubName () const
Return the subname path.
Referenced by Gui::Dialog::DlgPropertyLink::formatObject(), operator<(), Gui::PropertyEditor::LinkSelection::select(), Gui::SelectionSingleton::slotSelectionChanged(), and MeshPartGui::Mesh2ShapeGmsh::writeProject().
getSubNameNoElement()
std::string SubObjectT::getSubNameNoElement () const
Return the subname path without sub-element.
References Data::ComplexGeoData::noElementName().
getSubObject()
App::DocumentObject * SubObjectT::getSubObject () const
Return the sub-object.
References App::DocumentObjectT::getObject().
Referenced by getSubObjectFullName(), and Gui::PropertyEditor::LinkSelection::select().
getSubObjectFullName()
std::string SubObjectT::getSubObjectFullName (const char * docName = nullptr) const
Return docname::objname.subname (label)
Parameters
doc optional document name. The document prefix will only be printed if it is different then the given 'doc'.
References App::DocumentObjectT::getDocument(), App::DocumentObjectT::getDocumentName(), getObjectFullName(), App::DocumentObjectT::getObjectName(), and getSubObject().
getSubObjectList()
std::vector< App::DocumentObject * > SubObjectT::getSubObjectList () const
Return all objects along the subname path.
References App::DocumentObjectT::getObject().
getSubObjectPython()
std::string SubObjectT::getSubObjectPython (bool force = true) const
References Base::Tools::escapedUnicodeFromUtf8(), and App::DocumentObjectT::getObjectPython().
operator<()
bool SubObjectT::operator< (const SubObjectT & other) const
References App::DocumentObjectT::getDocumentName(), App::DocumentObjectT::getObjectName(), App::DocumentObjectT::getPropertyName(), and getSubName().
operator=() [1/4]
SubObjectT & SubObjectT::operator= (const App::DocumentObject * other)
Assignment operator
operator=() [2/4]
SubObjectT & SubObjectT::operator= (const DocumentObjectT & other)
Assignment operator
operator=() [3/4]
SubObjectT & SubObjectT::operator= (const SubObjectT & other)
Assignment operator
operator=() [4/4]
SubObjectT & SubObjectT::operator= (SubObjectT && other)
Assignment operator
References draftfunctions.move::move().
operator==()
bool SubObjectT::operator== (const SubObjectT & other) const
Equality operator
setSubName() [1/2]
void SubObjectT::setSubName (const char * subname)
Set the subname path to the sub-object.
Referenced by Gui::SelectionSingleton::slotSelectionChanged().
setSubName() [2/2]
void App::SubObjectT::setSubName (const std::string & subname)
Set the subname path to the sub-object.
The documentation for this class was generated from the following files:
FreeCAD/src/App/DocumentObserver.h
FreeCAD/src/App/DocumentObserver.cpp