FreeCAD: Gui::Dialog::DlgInputDialogImp Class Reference
Gui::Dialog::DlgInputDialogImp Class Reference
The DlgInputDialogImp dialog class does basically the same as Qt's QInputDialog unless that it provides no static function but the application programmer must create an instance and prepare it.
#include <DlgInputDialogImp.h>
Public Types
enum Type {
LineEdit , SpinBox , UIntBox , FloatSpinBox ,
ComboBox
}
Public Member Functions
DlgInputDialogImp (const QString &label, QWidget *parent=0, bool modal=true, Type=LineEdit)
Constructs a Gui::Dialog::DlgInputDialogImp as a child of 'parent', with the name 'name' and widget flags set to 'f'.
QComboBox * getComboBox () const
QDoubleSpinBox * getFloatSpinBox () const
QLineEdit * getLineEdit () const
QSpinBox * getSpinBox () const
Gui::UIntSpinBox * getUIntBox () const
void setType (Type t)
Type type () const
~DlgInputDialogImp ()
Destroys the object and frees any allocated resources.
Protected Slots
void textChanged (const QString &s)
void tryAccept ()
Protected Attributes
Type inputtype
Detailed Description
The DlgInputDialogImp dialog class does basically the same as Qt's QInputDialog unless that it provides no static function but the application programmer must create an instance and prepare it.
This requires a little more work but increases the flexibility.
Author
Werner Mayer
Member Enumeration Documentation
Type
enum Gui::Dialog::DlgInputDialogImp::Type
Enumerator
LineEdit
SpinBox
UIntBox
FloatSpinBox
ComboBox
Constructor & Destructor Documentation
DlgInputDialogImp()
DlgInputDialogImp::DlgInputDialogImp (const QString & labelTxt, QWidget * parent = 0, bool modal = true, Type type = LineEdit)
Constructs a Gui::Dialog::DlgInputDialogImp as a child of 'parent', with the name 'name' and widget flags set to 'f'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
References draftgeoutils.intersections::connect(), setType(), textChanged(), and tryAccept().
~DlgInputDialogImp()
DlgInputDialogImp::~DlgInputDialogImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
getComboBox()
QComboBox * DlgInputDialogImp::getComboBox () const
getFloatSpinBox()
QDoubleSpinBox * DlgInputDialogImp::getFloatSpinBox () const
getLineEdit()
QLineEdit * DlgInputDialogImp::getLineEdit () const
getSpinBox()
QSpinBox * DlgInputDialogImp::getSpinBox () const
getUIntBox()
Gui::UIntSpinBox * DlgInputDialogImp::getUIntBox () const
Referenced by Gui::Dialog::ParameterUInt::changeValue(), and Gui::Dialog::ParameterValue::onCreateUIntItem().
setType()
void DlgInputDialogImp::setType (DlgInputDialogImp::Type t)
References ComboBox, FloatSpinBox, inputtype, LineEdit, SpinBox, and UIntBox.
Referenced by DlgInputDialogImp().
textChanged
void DlgInputDialogImp::textChanged (const QString & s) protected slot
References LineEdit, and type().
Referenced by DlgInputDialogImp().
tryAccept
void DlgInputDialogImp::tryAccept () protected slot
Referenced by DlgInputDialogImp().
type()
DlgInputDialogImp::Type DlgInputDialogImp::type () const
References inputtype.
Referenced by ArchProfile.ProfileTaskPanel::accept(), ArchProfile.ProfileTaskPanel::retranslateUi(), and textChanged().
Member Data Documentation
inputtype
Type Gui::Dialog::DlgInputDialogImp::inputtype protected
Referenced by setType(), and type().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgInputDialogImp.h
Sources/FreeCAD/src/Gui/DlgInputDialogImp.cpp