FreeCAD: Gui::Dialog::DlgActivateWindowImp Class Reference
Gui::Dialog::DlgActivateWindowImp Class Reference
The DlgActivateWindowImp class provides a dialog to activate the MDI window of the main window you wish.
#include <DlgActivateWindowImp.h>
Public Member Functions
DlgActivateWindowImp (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
Constructs a DlgActivateWindowImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
~DlgActivateWindowImp ()
Destroys the object and frees any allocated resources.
Protected Member Functions
void accept ()
Activates the MDI window you wish and closes the dialog.
Detailed Description
The DlgActivateWindowImp class provides a dialog to activate the MDI window of the main window you wish.
Since there could be a lot of MDI windows in an application you cannot put all of them into the "Windows" popup menu.
Author
Werner Mayer
Constructor & Destructor Documentation
DlgActivateWindowImp()
DlgActivateWindowImp::DlgActivateWindowImp (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Constructs a DlgActivateWindowImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
References Gui::MainWindow::activeWindow(), Gui::Dialog::Ui_DlgActivateWindow::buttonBox, Gui::getMainWindow(), Gui::Dialog::Ui_DlgActivateWindow::setupUi(), draftguitools.gui_setstyle::translate, Gui::Dialog::Ui_DlgActivateWindow::treeWidget, and Gui::MainWindow::windows().
~DlgActivateWindowImp()
DlgActivateWindowImp::~DlgActivateWindowImp ()
Destroys the object and frees any allocated resources.
Member Function Documentation
accept()
void DlgActivateWindowImp::accept () protected
Activates the MDI window you wish and closes the dialog.
References Gui::getMainWindow(), Gui::MainWindow::setActiveWindow(), Gui::Dialog::Ui_DlgActivateWindow::treeWidget, and Gui::MainWindow::windows().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/DlgActivateWindowImp.h
FreeCAD/src/Gui/DlgActivateWindowImp.cpp