FreeCAD: MeshCore::MeshEvalCorruptedFacets Class Reference
MeshCore::MeshEvalCorruptedFacets Class Reference
The MeshEvalCorruptedFacets class searches for facets with several equal point indices.
#include <Degeneration.h>
Public Member Functions
bool Evaluate ()
Searches for corrupted facets.
std::vector< FacetIndex > GetIndices () const
Returns the indices of all corrupt facets.
MeshEvalCorruptedFacets (const MeshKernel &rclM)
Construction.
~MeshEvalCorruptedFacets ()
Destruction.
Public Member Functions inherited from MeshCore::MeshEvaluation
virtual bool Evaluate ()=0
Evaluates the mesh kernel with respect to certain criteria.
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()
Detailed Description
The MeshEvalCorruptedFacets class searches for facets with several equal point indices.
See also
MeshFixCorruptedFacets
Author
Werner Mayer
Constructor & Destructor Documentation
MeshEvalCorruptedFacets()
MeshCore::MeshEvalCorruptedFacets::MeshEvalCorruptedFacets (const MeshKernel & rclM)
Construction.
~MeshEvalCorruptedFacets()
MeshCore::MeshEvalCorruptedFacets::~MeshEvalCorruptedFacets ()
Destruction.
Member Function Documentation
Evaluate()
bool MeshEvalCorruptedFacets::Evaluate () virtual
Searches for corrupted facets.
Implements MeshCore::MeshEvaluation.
Referenced by Mesh::MeshObject::hasCorruptedFacets(), MeshGui::DlgEvaluateMeshImp::on_analyzeIndicesButton_clicked(), MeshGui::DlgEvaluateMeshImp::on_repairAllTogether_clicked(), and Mesh::MeshObject::validateIndices().
GetIndices()
std::vector< FacetIndex > MeshEvalCorruptedFacets::GetIndices () const
Returns the indices of all corrupt facets.
Referenced by MeshGui::DlgEvaluateMeshImp::on_analyzeIndicesButton_clicked().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Mesh/App/Core/Degeneration.h
FreeCAD/src/Mod/Mesh/App/Core/Degeneration.cpp