FreeCAD: Gui::ViewVolumeProjection Class Reference
Gui::ViewVolumeProjection Class Reference
#include <Utilities.h>
Public Member Functions
Base::Matrix4D getProjectionMatrix () const
Calculate the projection (+ mapping) matrix.
Base::Vector3d inverse (const Base::Vector3d &rclPt) const
Convert a 2D point on the projection plane in 3D space.
Base::Vector3f inverse (const Base::Vector3f &rclPt) const
Convert a 2D point on the projection plane in 3D space.
Base::Vector3d operator() (const Base::Vector3d &rclPt) const
Convert 3D point to 2D projection plane.
Base::Vector3f operator() (const Base::Vector3f &rclPt) const
Convert 3D point to 2D projection plane.
ViewVolumeProjection (const SbViewVolume &vv)
virtual ~ViewVolumeProjection ()
Public Member Functions inherited from Base::ViewProjMethod
Matrix4D getComposedProjectionMatrix () const
Calculate the composed projection matrix.
virtual Matrix4D getProjectionMatrix () const =0
Calculate the projection (+ mapping) matrix.
const Base::Matrix4D & getTransform () const
virtual Vector3d inverse (const Vector3d &rclPt) const =0
Convert a 2D point on the projection plane in 3D space.
virtual Vector3f inverse (const Vector3f &rclPt) const =0
Convert a 2D point on the projection plane in 3D space.
virtual bool isValid () const
virtual Vector3d operator() (const Vector3d &rclPt) const =0
Convert 3D point to 2D projection plane.
virtual Vector3f operator() (const Vector3f &rclPt) const =0
Convert 3D point to 2D projection plane.
ViewProjMethod & operator= (const ViewProjMethod &)=default
void setTransform (const Base::Matrix4D &)
Apply an additional transformation to the input points.
ViewProjMethod (const ViewProjMethod &)=default
virtual ~ViewProjMethod ()=default
Protected Attributes
SbMatrix invert
SbMatrix matrix
SbViewVolume viewVolume
Additional Inherited Members
Protected Member Functions inherited from Base::ViewProjMethod
void transformInput (const Base::Vector3d &, Base::Vector3d &) const
void transformInput (const Base::Vector3f &, Base::Vector3f &) const
ViewProjMethod ()
Constructor & Destructor Documentation
ViewVolumeProjection()
ViewVolumeProjection::ViewVolumeProjection (const SbViewVolume & vv)
References viewVolume.
~ViewVolumeProjection()
virtual Gui::ViewVolumeProjection::~ViewVolumeProjection () virtual
Member Function Documentation
getProjectionMatrix()
Base::Matrix4D ViewVolumeProjection::getProjectionMatrix () const virtual
Calculate the projection (+ mapping) matrix.
Implements Base::ViewProjMethod.
inverse() [1/2]
Base::Vector3d ViewVolumeProjection::inverse (const Base::Vector3d & rclPt) const virtual
Convert a 2D point on the projection plane in 3D space.
Implements Base::ViewProjMethod.
References inverse().
inverse() [2/2]
Base::Vector3f ViewVolumeProjection::inverse (const Base::Vector3f & rclPt) const virtual
Convert a 2D point on the projection plane in 3D space.
Implements Base::ViewProjMethod.
References Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by inverse().
operator()() [1/2]
Base::Vector3d ViewVolumeProjection::operator() (const Base::Vector3d & rclPt) const virtual
Convert 3D point to 2D projection plane.
Implements Base::ViewProjMethod.
References operator()().
operator()() [2/2]
Base::Vector3f ViewVolumeProjection::operator() (const Base::Vector3f & rclPt) const virtual
Convert 3D point to 2D projection plane.
Implements Base::ViewProjMethod.
References Base::ViewProjMethod::transformInput().
Referenced by operator()().
Member Data Documentation
invert
SbMatrix Gui::ViewVolumeProjection::invert protected
Referenced by PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadEnd(), and PathScripts.PathDressupLeadInOut.ObjectDressup::getLeadStart().
matrix
SbMatrix Gui::ViewVolumeProjection::matrix protected
viewVolume
SbViewVolume Gui::ViewVolumeProjection::viewVolume protected
Referenced by ViewVolumeProjection().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/Utilities.h
FreeCAD/src/Gui/Utilities.cpp