FreeCAD: BOPTools.JoinAPI Namespace Reference
BOPTools.JoinAPI Namespace Reference
Functions
def connect (list_of_shapes, tolerance=0.0)
def connect_legacy (shape1, shape2, tolerance=0.0)
def cutout_legacy (shape_base, shape_tool, tolerance=0.0)
def embed_legacy (shape_base, shape_tool, tolerance=0.0)
def shapeOfMaxSize (list_of_shapes)
Function Documentation
connect()
def BOPTools.JoinAPI.connect (list_of_shapes, tolerance = 0.0)
connect(list_of_shapes, tolerance = 0.0): connects solids (walled objects), shells and
wires by throwing off small parts that result when splitting them at intersections.
Compounds in list_of_shapes are automatically exploded, so self-intersecting compounds
are valid for connect.
References BOPTools.JoinAPI.connect_legacy(), BOPTools.generalFuseIsAvailable(), and BOPTools.JoinAPI.shapeOfMaxSize().
connect_legacy()
def BOPTools.JoinAPI.connect_legacy (shape1, shape2, tolerance = 0.0)
connect_legacy(shape1, shape2, tolerance = 0.0): alternative implementation of
connect, without use of generalFuse. Slow. Provided for backwards compatibility, and
for older OCC.
References BOPTools.JoinAPI.shapeOfMaxSize().
Referenced by BOPTools.JoinAPI.connect().
cutout_legacy()
def BOPTools.JoinAPI.cutout_legacy (shape_base, shape_tool, tolerance = 0.0)
cutout_legacy(shape_base, shape_tool, tolerance = 0.0): alternative implementation of
cutout, without use of generalFuse. Slow. Provided for backwards compatibility, and
for older OCC.
References BOPTools.JoinAPI.shapeOfMaxSize().
embed_legacy()
def BOPTools.JoinAPI.embed_legacy (shape_base, shape_tool, tolerance = 0.0)
embed_legacy(shape_base, shape_tool, tolerance = 0.0): alternative implementation of
embed, without use of generalFuse. Slow. Provided for backwards compatibility, and
for older OCC.
References BOPTools.JoinAPI.shapeOfMaxSize().
shapeOfMaxSize()
def BOPTools.JoinAPI.shapeOfMaxSize (list_of_shapes)
shapeOfMaxSize(list_of_shapes): finds the shape that has the largest "
"mass in the list and returns it. The shapes in the list must be of same dimension.
Referenced by BOPTools.JoinAPI.connect(), BOPTools.JoinAPI.connect_legacy(), BOPTools.JoinAPI.cutout_legacy(), and BOPTools.JoinAPI.embed_legacy().