FreeCAD: draftviewproviders.view_circulararray.ViewProviderCircularArray Class Reference
draftviewproviders.view_circulararray.ViewProviderCircularArray Class Reference
Workbenches » Python workbenches » Draft » draftviewproviders
Public Member Functions
def getIcon (self)
Public Member Functions inherited from draftviewproviders.view_array.ViewProviderDraftArray
def getIcon (self)
def resetColors (self, vobj)
Public Member Functions inherited from draftviewproviders.view_base.ViewProviderDraft
def attach (self, vobj)
def claimChildren (self)
def execute (self, vobj)
def getDefaultDisplayMode (self)
def getDisplayModes (self, vobj)
def getIcon (self)
def onChanged (self, vobj, prop)
def setDisplayMode (self, mode)
def setEdit (self, vobj, mode=0)
def unsetEdit (self, vobj, mode=0)
def updateData (self, obj, prop)
Additional Inherited Members
Public Attributes inherited from draftviewproviders.view_base.ViewProviderDraft
Object
texcoords
texture
Detailed Description
View provider for the circular array object, currently unused.
Member Function Documentation
getIcon()
def draftviewproviders.view_circulararray.ViewProviderCircularArray.getIcon (self)
Set the icon in the tree view.
Reimplemented from draftviewproviders.view_array.ViewProviderDraftArray.
Referenced by ArchAxisSystem.AxisSystemTaskPanel.update(), ArchComponent.ComponentTaskPanel.update(), and ArchSectionPlane.SectionPlaneTaskPanel.update().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Draft/draftviewproviders/view_circulararray.py