FreeCAD: PartDesignGui::Ui_TaskShapeBinder Class Reference
PartDesignGui::Ui_TaskShapeBinder Class Reference
#include <ui_TaskShapeBinder.h>
Public Member Functions
void retranslateUi (QWidget *PartDesignGui__TaskShapeBinder)
void setupUi (QWidget *PartDesignGui__TaskShapeBinder)
Public Attributes
QLineEdit * baseEdit
QToolButton * buttonBase
QToolButton * buttonRefAdd
QToolButton * buttonRefRemove
QHBoxLayout * horizontalLayout
QHBoxLayout * horizontalLayout_4
QListWidget * listWidgetReferences
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void PartDesignGui::Ui_TaskShapeBinder::retranslateUi (QWidget * PartDesignGui__TaskShapeBinder)
References buttonBase, buttonRefAdd, buttonRefRemove, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void PartDesignGui::Ui_TaskShapeBinder::setupUi (QWidget * PartDesignGui__TaskShapeBinder)
References baseEdit, buttonBase, buttonRefAdd, buttonRefRemove, horizontalLayout, horizontalLayout_4, listWidgetReferences, retranslateUi(), and verticalLayout.
Member Data Documentation
baseEdit
QLineEdit* PartDesignGui::Ui_TaskShapeBinder::baseEdit
Referenced by setupUi().
buttonBase
QToolButton* PartDesignGui::Ui_TaskShapeBinder::buttonBase
Referenced by retranslateUi(), and setupUi().
buttonRefAdd
QToolButton* PartDesignGui::Ui_TaskShapeBinder::buttonRefAdd
Referenced by retranslateUi(), and setupUi().
buttonRefRemove
QToolButton* PartDesignGui::Ui_TaskShapeBinder::buttonRefRemove
Referenced by retranslateUi(), and setupUi().
horizontalLayout
QHBoxLayout* PartDesignGui::Ui_TaskShapeBinder::horizontalLayout
Referenced by setupUi().
horizontalLayout_4
QHBoxLayout* PartDesignGui::Ui_TaskShapeBinder::horizontalLayout_4
Referenced by setupUi().
listWidgetReferences
QListWidget* PartDesignGui::Ui_TaskShapeBinder::listWidgetReferences
Referenced by setupUi().
verticalLayout
QVBoxLayout* PartDesignGui::Ui_TaskShapeBinder::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/PartDesign/Gui/ui_TaskShapeBinder.h