FreeCAD: Gui::ViewProviderExtension Class Reference
Gui::ViewProviderExtension Class Reference
Extension with special viewprovider calls.
#include <ViewProviderExtension.h>
Public Member Functions
virtual void extensionAttach (App::DocumentObject *)
virtual void extensionBeforeDelete ()
virtual bool extensionCanDragAndDropObject (App::DocumentObject *) const
virtual bool extensionCanDragObject (App::DocumentObject *) const
virtual bool extensionCanDragObjects () const
virtual bool extensionCanDropObject (App::DocumentObject *) const
virtual bool extensionCanDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const
virtual bool extensionCanDropObjects () const
virtual std::vector< App::DocumentObject * > extensionClaimChildren (void) const
virtual std::vector< App::DocumentObject * > extensionClaimChildren3D (void) const
virtual void extensionDragObject (App::DocumentObject *)
virtual void extensionDropObject (App::DocumentObject *)
virtual std::string extensionDropObjectEx (App::DocumentObject *obj, App::DocumentObject *, const char *, const std::vector< std::string > &)
virtual void extensionFinishRestoring ()
virtual SoSeparator * extensionGetBackRoot (void) const
virtual SoGroup * extensionGetChildRoot (void) const
virtual bool extensionGetDetailPath (const char *, SoFullPath *, SoDetail *&) const
virtual std::vector< std::string > extensionGetDisplayModes (void) const
virtual bool extensionGetElementPicked (const SoPickedPoint *, std::string &) const
virtual SoSeparator * extensionGetFrontRoot (void) const
virtual void extensionHide (void)
Hides the view provider.
virtual QIcon extensionMergeColorfullOverlayIcons (const QIcon &orig) const
virtual QIcon extensionMergeGreyableOverlayIcons (const QIcon &orig) const
virtual void extensionModeSwitchChange (void)
virtual bool extensionOnDelete (const std::vector< std::string > &)
virtual void extensionReattach (App::DocumentObject *)
virtual int extensionReplaceObject (App::DocumentObject *, App::DocumentObject *)
virtual void extensionSetDisplayMode (const char *)
virtual void extensionSetupContextMenu (QMenu *, QObject *, const char *)
virtual void extensionShow (void)
Shows the view provider.
virtual void extensionStartRestoring ()
virtual void extensionUpdateData (const App::Property *)
Gui::ViewProviderDocumentObject * getExtendedViewProvider ()
const Gui::ViewProviderDocumentObject * getExtendedViewProvider () const
virtual PyObject * getExtensionPyObject ()
bool ignoreOverlayIcon () const
void setIgnoreOverlayIcon (bool on)
ViewProviderExtension ()
virtual ~ViewProviderExtension ()
Public Member Functions inherited from App::Extension
Extension ()
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
virtual PyObject * getExtensionPyObject ()
virtual void initExtension (App::ExtensionContainer *obj)
bool isPythonExtension ()
std::string name () const
virtual ~Extension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Additional Inherited Members
Protected Member Functions inherited from App::Extension
virtual void extensionOnChanged (const Property *p)
void initExtensionType (Base::Type type)
Static Protected Member Functions inherited from App::Extension
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
Extension with special viewprovider calls.
Constructor & Destructor Documentation
ViewProviderExtension()
ViewProviderExtension::ViewProviderExtension ()
~ViewProviderExtension()
ViewProviderExtension::~ViewProviderExtension () virtual
Member Function Documentation
extensionAttach()
virtual void Gui::ViewProviderExtension::extensionAttach (App::DocumentObject *) virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension, and Gui::ViewProviderOriginGroupExtension.
Referenced by Gui::ViewProviderGeoFeatureGroupExtension::extensionAttach().
extensionBeforeDelete()
virtual void Gui::ViewProviderExtension::extensionBeforeDelete () virtual
Reimplemented in Gui::ViewProviderLinkObserver.
extensionCanDragAndDropObject()
virtual bool Gui::ViewProviderExtension::extensionCanDragAndDropObject (App::DocumentObject *) const virtual
extensionCanDragObject()
virtual bool Gui::ViewProviderExtension::extensionCanDragObject (App::DocumentObject *) const virtual
Reimplemented in Gui::ViewProviderGroupExtension, and Gui::ViewProviderLinkObserver.
extensionCanDragObjects()
virtual bool Gui::ViewProviderExtension::extensionCanDragObjects () const virtual
Reimplemented in Gui::ViewProviderGroupExtension.
extensionCanDropObject()
virtual bool Gui::ViewProviderExtension::extensionCanDropObject (App::DocumentObject *) const virtual
Reimplemented in Gui::ViewProviderGroupExtension, and Gui::ViewProviderLinkObserver.
extensionCanDropObjectEx()
virtual bool Gui::ViewProviderExtension::extensionCanDropObjectEx (App::DocumentObject * , App::DocumentObject * , const char * , const std::vector< std::string > &) const virtual
extensionCanDropObjects()
virtual bool Gui::ViewProviderExtension::extensionCanDropObjects () const virtual
Reimplemented in Gui::ViewProviderGroupExtension.
extensionClaimChildren()
virtual std::vector< App::DocumentObject * > Gui::ViewProviderExtension::extensionClaimChildren (void) const virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension, Gui::ViewProviderGroupExtension, and Gui::ViewProviderOriginGroupExtension.
extensionClaimChildren3D()
virtual std::vector< App::DocumentObject * > Gui::ViewProviderExtension::extensionClaimChildren3D (void) const virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension, and Gui::ViewProviderOriginGroupExtension.
extensionDragObject()
virtual void Gui::ViewProviderExtension::extensionDragObject (App::DocumentObject *) virtual
Reimplemented in Gui::ViewProviderGroupExtension.
extensionDropObject()
virtual void Gui::ViewProviderExtension::extensionDropObject (App::DocumentObject *) virtual
Reimplemented in Gui::ViewProviderGroupExtension.
extensionDropObjectEx()
virtual std::string Gui::ViewProviderExtension::extensionDropObjectEx (App::DocumentObject * obj, App::DocumentObject * , const char * , const std::vector< std::string > &) virtual
extensionFinishRestoring()
virtual void Gui::ViewProviderExtension::extensionFinishRestoring () virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension, and Gui::ViewProviderLinkObserver.
Referenced by Gui::ViewProviderGeoFeatureGroupExtension::extensionFinishRestoring().
extensionGetBackRoot()
virtual SoSeparator * Gui::ViewProviderExtension::extensionGetBackRoot (void) const virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension.
extensionGetChildRoot()
virtual SoGroup * Gui::ViewProviderExtension::extensionGetChildRoot (void) const virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension.
extensionGetDetailPath()
virtual bool Gui::ViewProviderExtension::extensionGetDetailPath (const char * , SoFullPath * , SoDetail *&) const virtual
extensionGetDisplayModes()
virtual std::vector< std::string > Gui::ViewProviderExtension::extensionGetDisplayModes (void) const virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension.
Referenced by Gui::ViewProviderGeoFeatureGroupExtension::extensionGetDisplayModes().
extensionGetElementPicked()
virtual bool Gui::ViewProviderExtension::extensionGetElementPicked (const SoPickedPoint * , std::string &) const virtual
extensionGetFrontRoot()
virtual SoSeparator * Gui::ViewProviderExtension::extensionGetFrontRoot (void) const virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension.
extensionHide()
virtual void Gui::ViewProviderExtension::extensionHide (void) virtual
Hides the view provider.
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension, and Gui::ViewProviderGroupExtension.
Referenced by Gui::ViewProviderGeoFeatureGroupExtension::extensionHide(), and Gui::ViewProviderGroupExtension::extensionHide().
extensionMergeColorfullOverlayIcons()
virtual QIcon Gui::ViewProviderExtension::extensionMergeColorfullOverlayIcons (const QIcon & orig) const virtual
Reimplemented in PartGui::ViewProviderAttachExtension.
extensionMergeGreyableOverlayIcons()
virtual QIcon Gui::ViewProviderExtension::extensionMergeGreyableOverlayIcons (const QIcon & orig) const virtual
Reimplemented in TechDrawGui::ViewProviderCosmeticExtension.
extensionModeSwitchChange()
virtual void Gui::ViewProviderExtension::extensionModeSwitchChange (void) virtual
Reimplemented in Gui::ViewProviderLinkObserver.
extensionOnDelete()
virtual bool Gui::ViewProviderExtension::extensionOnDelete (const std::vector< std::string > &) virtual
Reimplemented in Gui::ViewProviderGroupExtension.
extensionReattach()
virtual void Gui::ViewProviderExtension::extensionReattach (App::DocumentObject *) virtual
Reimplemented in Gui::ViewProviderLinkObserver.
extensionReplaceObject()
virtual int Gui::ViewProviderExtension::extensionReplaceObject (App::DocumentObject * , App::DocumentObject *) virtual
extensionSetDisplayMode()
virtual void Gui::ViewProviderExtension::extensionSetDisplayMode (const char *) virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension.
Referenced by Gui::ViewProviderGeoFeatureGroupExtension::extensionSetDisplayMode().
extensionSetupContextMenu()
virtual void Gui::ViewProviderExtension::extensionSetupContextMenu (QMenu * , QObject * , const char *) virtual
Reimplemented in PartGui::ViewProviderAttachExtension, and PartGui::ViewProviderSplineExtension.
extensionShow()
virtual void Gui::ViewProviderExtension::extensionShow (void) virtual
Shows the view provider.
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension, and Gui::ViewProviderGroupExtension.
Referenced by Gui::ViewProviderGeoFeatureGroupExtension::extensionShow(), and Gui::ViewProviderGroupExtension::extensionShow().
extensionStartRestoring()
virtual void Gui::ViewProviderExtension::extensionStartRestoring () virtual
extensionUpdateData()
void ViewProviderExtension::extensionUpdateData (const App::Property *) virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension, Gui::ViewProviderLinkObserver, PartGui::ViewProviderAttachExtension, PartGui::ViewProviderSplineExtension, TechDrawGui::ViewProviderCosmeticExtension, and Gui::ViewProviderOriginGroupExtension.
Referenced by Gui::ViewProviderGeoFeatureGroupExtension::extensionUpdateData(), PartGui::ViewProviderSplineExtension::extensionUpdateData(), and TechDrawGui::ViewProviderCosmeticExtension::extensionUpdateData().
getExtendedViewProvider() [1/2]
ViewProviderDocumentObject * ViewProviderExtension::getExtendedViewProvider ()
References Base::Persistence::getClassTypeId(), and App::Extension::getExtendedContainer().
Referenced by Gui::ViewProviderGeoFeatureGroupExtension::extensionAttach(), Gui::ViewProviderGroupExtension::extensionCanDropObject(), Gui::ViewProviderGeoFeatureGroupExtension::extensionClaimChildren(), Gui::ViewProviderGroupExtension::extensionClaimChildren(), Gui::ViewProviderGeoFeatureGroupExtension::extensionClaimChildren3D(), Gui::ViewProviderGroupExtension::extensionDragObject(), Gui::ViewProviderGroupExtension::extensionDropObject(), Gui::ViewProviderGroupExtension::extensionHide(), PartGui::ViewProviderAttachExtension::extensionMergeColorfullOverlayIcons(), PartGui::ViewProviderSplineExtension::extensionOnChanged(), Gui::ViewProviderGroupExtension::extensionOnDelete(), Gui::ViewProviderGeoFeatureGroupExtension::extensionSetDisplayMode(), PartGui::ViewProviderAttachExtension::extensionSetupContextMenu(), Gui::ViewProviderGroupExtension::extensionShow(), Gui::ViewProviderGeoFeatureGroupExtension::extensionUpdateData(), PartGui::ViewProviderAttachExtension::extensionUpdateData(), Gui::ViewProviderOriginGroupExtension::extensionUpdateData(), PartGui::ViewProviderSplineExtension::showControlPoints(), Gui::ViewProviderOriginGroupExtension::slotChangedObjectApp(), Gui::ViewProviderOriginGroupExtension::slotChangedObjectGui(), PartDesignGui::ViewProviderBody::updateOriginDatumSize(), and Gui::ViewProviderOriginGroupExtension::updateOriginSize().
getExtendedViewProvider() [2/2]
const ViewProviderDocumentObject * ViewProviderExtension::getExtendedViewProvider () const
References Base::Persistence::getClassTypeId(), and App::Extension::getExtendedContainer().
getExtensionPyObject()
PyObject * ViewProviderExtension::getExtensionPyObject (void) virtual
Reimplemented from App::Extension.
References App::Extension::ExtensionPythonObject.
ignoreOverlayIcon()
bool Gui::ViewProviderExtension::ignoreOverlayIcon () const
setIgnoreOverlayIcon()
void Gui::ViewProviderExtension::setIgnoreOverlayIcon (bool on)
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/ViewProviderExtension.h
FreeCAD/src/Gui/ViewProviderExtension.cpp