FreeCAD: SMDS_MeshNodeIDFactory Class Reference
SMDS_MeshNodeIDFactory Class Reference
#include <SMDS_MeshNodeIDFactory.hxx>
Public Member Functions
bool BindID (int ID, SMDS_MeshElement *elem)
virtual void Clear ()
SMDS_ElemIteratorPtr elementsIterator () const
virtual void emptyPool (int maxId)
virtual int GetFreeID ()
int GetMaxID () const
int GetMinID () const
SMDS_MeshElement * MeshElement (int ID)
virtual void ReleaseID (int ID, int vtkId=-1)
SMDS_MeshNodeIDFactory ()
Public Member Functions inherited from SMDS_MeshIDFactory
void adjustMaxId (int ID)
int GetFreeID ()
SMDS_Mesh * GetMesh ()
bool isPoolIdEmpty ()
void SetMesh (SMDS_Mesh *mesh)
Public Member Functions inherited from SMDS_MeshObject
virtual ~SMDS_MeshObject ()
Protected Member Functions
void updateMinMax () const
void updateMinMax (int id) const
Protected Member Functions inherited from SMDS_MeshIDFactory
SMDS_MeshIDFactory ()
Protected Attributes
int myMax
int myMin
Protected Attributes inherited from SMDS_MeshIDFactory
int myMaxID
SMDS_Mesh * myMesh
std::set< int > myPoolOfID
Constructor & Destructor Documentation
SMDS_MeshNodeIDFactory()
SMDS_MeshNodeIDFactory::SMDS_MeshNodeIDFactory ()
Member Function Documentation
BindID()
bool SMDS_MeshNodeIDFactory::BindID (int ID, SMDS_MeshElement * elem)
References updateMinMax().
Referenced by SMDS_Mesh::AddNodeWithID(), and SMDS_Mesh::Renumber().
Clear()
void SMDS_MeshNodeIDFactory::Clear () virtual
Reimplemented from SMDS_MeshIDFactory.
Reimplemented in SMDS_MeshElementIDFactory.
References SMDS_MeshIDFactory::Clear(), myMax, and myMin.
Referenced by SMDS_Mesh::Clear(), and SMDS_Mesh::Renumber().
elementsIterator()
SMDS_ElemIteratorPtr SMDS_MeshNodeIDFactory::elementsIterator () const
References SMDS_Mesh::elementsIterator(), and SMDS_MeshIDFactory::myMesh.
Referenced by SMDS_Mesh::Renumber().
emptyPool()
void SMDS_MeshNodeIDFactory::emptyPool (int maxId) virtual
Reimplemented from SMDS_MeshIDFactory.
References SMDS_MeshIDFactory::emptyPool(), and myMax.
Referenced by SMESHDS_Mesh::compactMesh().
GetFreeID()
int SMDS_MeshNodeIDFactory::GetFreeID () virtual
Reimplemented in SMDS_MeshElementIDFactory.
References SMDS_MeshIDFactory::GetFreeID(), and MeshElement().
Referenced by SMDS_Mesh::AddNode(), and SMDS_Mesh::AddNodeWithID().
GetMaxID()
int SMDS_MeshNodeIDFactory::GetMaxID () const
References myMax, and updateMinMax().
Referenced by SMDS_Mesh::adjustStructure(), and SMDS_Mesh::MaxElementID().
GetMinID()
int SMDS_MeshNodeIDFactory::GetMinID () const
References myMax, myMin, and updateMinMax().
Referenced by SMDS_Mesh::MinElementID().
MeshElement()
SMDS_MeshElement * SMDS_MeshNodeIDFactory::MeshElement (int ID)
References SMDS_Mesh::FindNode(), and SMDS_MeshIDFactory::GetMesh().
Referenced by SMDS_Mesh::Add0DElementWithID(), SMDS_Mesh::AddBallWithID(), SMDS_Mesh::AddEdgeWithID(), SMDS_Mesh::AddFaceWithID(), SMDS_Mesh::AddNodeWithID(), SMDS_Mesh::AddPolygonalFaceWithID(), SMDS_Mesh::AddPolyhedralVolumeWithID(), SMDS_Mesh::AddQuadPolygonalFaceWithID(), SMDS_Mesh::AddVolumeWithID(), SMDS_Mesh::GetElementType(), and GetFreeID().
ReleaseID()
void SMDS_MeshNodeIDFactory::ReleaseID (int ID, int vtkId = -1) virtual
Reimplemented from SMDS_MeshIDFactory.
Reimplemented in SMDS_MeshElementIDFactory.
References myMax, SMDS_MeshIDFactory::myMesh, myMin, SMDS_MeshIDFactory::ReleaseID(), and SMDS_Mesh::setMyModified().
Referenced by SMDS_Mesh::Clear(), SMDS_Mesh::RemoveElement(), SMDS_Mesh::RemoveFreeElement(), and SMDS_Mesh::~SMDS_Mesh().
updateMinMax() [1/2]
void SMDS_MeshNodeIDFactory::updateMinMax () const protected
References SMDS_Mesh::MaxNodeID(), SMDS_Mesh::MinNodeID(), myMax, SMDS_MeshIDFactory::myMesh, myMin, and SMDS_Mesh::updateNodeMinMax().
Referenced by BindID(), GetMaxID(), and GetMinID().
updateMinMax() [2/2]
void SMDS_MeshNodeIDFactory::updateMinMax (int id) const protected
Member Data Documentation
myMax
int SMDS_MeshNodeIDFactory::myMax protected
Referenced by SMDS_MeshElementIDFactory::Clear(), Clear(), emptyPool(), GetMaxID(), GetMinID(), SMDS_MeshElementIDFactory::ReleaseID(), ReleaseID(), SMDS_MeshElementIDFactory::updateMinMax(), and updateMinMax().
myMin
int SMDS_MeshNodeIDFactory::myMin mutable protected
Referenced by SMDS_MeshElementIDFactory::Clear(), Clear(), GetMinID(), SMDS_MeshElementIDFactory::ReleaseID(), ReleaseID(), SMDS_MeshElementIDFactory::updateMinMax(), and updateMinMax().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_MeshNodeIDFactory.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_MeshNodeIDFactory.cpp