FreeCAD: Gui::Thumbnail Class Reference
Gui::Thumbnail Class Reference
#include <Thumbnail.h>
Public Member Functions
void setFileName (const char *)
void setSize (int)
void setViewer (View3DInventorViewer *)
Thumbnail (int s=128)
~Thumbnail ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual unsigned int getMemSize () const =0
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
virtual Base::Type getTypeId (void) const
virtual void Restore (XMLReader &)=0
This method is used to restore properties from an XML document.
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void Save (Writer &) const =0
This method is used to save properties to an XML document.
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
virtual PyObject * getPyObject ()
This method returns the Python wrapper for a C++ object.
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
BaseClass & operator= (const BaseClass &)=default
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
I/O of the document
unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
void Save (Base::Writer &writer) const
This method is used to save properties or very small amounts of data to an XML document.
void Restore (Base::XMLReader &reader)
This method is used to restore properties from an XML document.
void SaveDocFile (Base::Writer &writer) const
This method is used to save large amounts of data to a binary file.
void RestoreDocFile (Base::Reader &reader)
This method is used to restore large amounts of data from a binary file.
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create ()
static Type getClassTypeId ()
static void init ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Constructor & Destructor Documentation
Thumbnail()
Thumbnail::Thumbnail (int s = 128)
~Thumbnail()
Thumbnail::~Thumbnail ()
Member Function Documentation
getMemSize()
unsigned int Thumbnail::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Restore()
void Thumbnail::Restore (Base::XMLReader & reader) virtual
This method is used to restore properties from an XML document.
Implements Base::Persistence.
RestoreDocFile()
void Thumbnail::RestoreDocFile (Base::Reader & reader) virtual
This method is used to restore large amounts of data from a binary file.
Reimplemented from Base::Persistence.
Save()
void Thumbnail::Save (Base::Writer & writer) const virtual
This method is used to save properties or very small amounts of data to an XML document.
Implements Base::Persistence.
References Base::Writer::addFile(), and Base::Writer::isForceXML().
Referenced by Gui::Document::Save().
SaveDocFile()
void Thumbnail::SaveDocFile (Base::Writer & writer) const virtual
This method is used to save large amounts of data to a binary file.
Reimplemented from Base::Persistence.
References Gui::BitmapFactory(), Gui::BitmapFactoryInst::BottomRight, App::Application::Config(), App::GetApplication(), Gui::View3DInventorViewer::imageFromFramebuffer(), Gui::BitmapFactoryInst::merge(), Gui::BitmapFactoryInst::pixmap(), and Base::Writer::Stream().
setFileName()
void Thumbnail::setFileName (const char * fn)
Referenced by Gui::Document::Save().
setSize()
void Thumbnail::setSize (int s)
Referenced by Gui::Document::Save().
setViewer()
void Thumbnail::setViewer (View3DInventorViewer * v)
Referenced by Gui::Document::Save().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/Thumbnail.h
FreeCAD/src/Gui/Thumbnail.cpp