FreeCAD: MED::TTElemInfo< eVersion > Struct Template Reference
MED::TTElemInfo< eVersion > Struct Template Reference
#include <MED_TStructures.hxx>
Public Member Functions
virtual std::string GetElemName (TInt theId) const
Get name of the mesh element by its order number.
virtual void SetElemName (TInt theId, const std::string &theValue)
Set name of the mesh element by its order number.
TTElemInfo (const PMeshInfo &theMeshInfo, const PElemInfo &theInfo)
TTElemInfo (const PMeshInfo &theMeshInfo, TInt theNbElem, const TIntVector &theFamilyNums, const TIntVector &theElemNums, const TStringVector &theElemNames)
TTElemInfo (const PMeshInfo &theMeshInfo, TInt theNbElem, EBooleen theIsElemNum, EBooleen theIsElemNames)
Public Member Functions inherited from MED::TElemInfo
TInt GetElemNum (TInt theId) const
Get a reference number of the mesh element by its order number.
TInt GetFamNum (TInt theId) const
Get number of a MED FAMILY by order number of the mesh element.
const PMeshInfo & GetMeshInfo () const
Get a reference to corresponding MED Mesh.
TInt GetNbElem () const
EBooleen IsElemNames () const
Let know if the mesh elements havew names.
EBooleen IsElemNum () const
Let know if the mesh elements are indexed.
EBooleen IsFamNum () const
Let know if the mesh elements family are indexed.
void SetElemNum (TInt theId, TInt theVal)
Set a reference number for the mesh element by its order number.
void SetFamNum (TInt theId, TInt theVal)
Set number of a MED FAMILY for the mesh element with the order number.
Public Member Functions inherited from MED::TBase
virtual ~TBase ()
Additional Inherited Members
Public Attributes inherited from MED::TElemInfo
PString myElemNames
Contains sequence of the names for the mesh elements.
PElemNum myElemNum
Contains sequence of the indexes for the mesh elements.
PElemNum myFamNum
Get number of mesh elements.
EBooleen myIsElemNames
Defines if the mesh elements are named.
EBooleen myIsElemNum
Defines if the mesh elements are indexed.
EBooleen myIsFamNum
Defines if the mesh elements family are indexed.
PMeshInfo myMeshInfo
A reference to correspondig MED Mesh.
TInt myNbElem
Constructor & Destructor Documentation
TTElemInfo() [1/3]
template<EVersion eVersion> MED::TTElemInfo< eVersion >::TTElemInfo (const PMeshInfo & theMeshInfo, const PElemInfo & theInfo)
References MED::eFAUX, MED::eVRAI, MED::TElemInfo::myElemNames, MED::TElemInfo::myElemNum, MED::TElemInfo::myFamNum, MED::TElemInfo::myIsElemNames, MED::TElemInfo::myIsElemNum, MED::TElemInfo::myIsFamNum, MED::TElemInfo::myMeshInfo, MED::TElemInfo::myNbElem, MED::TTElemInfo< eVersion >::SetElemName(), MED::TElemInfo::SetElemNum(), and MED::TElemInfo::SetFamNum().
TTElemInfo() [2/3]
template<EVersion eVersion> MED::TTElemInfo< eVersion >::TTElemInfo (const PMeshInfo & theMeshInfo, TInt theNbElem, EBooleen theIsElemNum, EBooleen theIsElemNames)
References MED::eFAUX, MED::TElemInfo::myElemNames, MED::TElemInfo::myElemNum, MED::TElemInfo::myFamNum, MED::TElemInfo::myIsElemNames, MED::TElemInfo::myIsElemNum, MED::TElemInfo::myIsFamNum, MED::TElemInfo::myMeshInfo, and MED::TElemInfo::myNbElem.
TTElemInfo() [3/3]
template<EVersion eVersion> MED::TTElemInfo< eVersion >::TTElemInfo (const PMeshInfo & theMeshInfo, TInt theNbElem, const TIntVector & theFamilyNums, const TIntVector & theElemNums, const TStringVector & theElemNames)
References MED::eFAUX, MED::eVRAI, MED::TElemInfo::myElemNames, MED::TElemInfo::myElemNum, MED::TElemInfo::myFamNum, MED::TElemInfo::myIsElemNames, MED::TElemInfo::myIsElemNum, MED::TElemInfo::myIsFamNum, MED::TElemInfo::myMeshInfo, MED::TElemInfo::myNbElem, and MED::TTElemInfo< eVersion >::SetElemName().
Member Function Documentation
GetElemName()
template<EVersion eVersion> virtual std::string MED::TTElemInfo< eVersion >::GetElemName (TInt theId) const virtual
Get name of the mesh element by its order number.
Implements MED::TElemInfo.
References MED::GetString(), and MED::TElemInfo::myElemNames.
SetElemName()
template<EVersion eVersion> virtual void MED::TTElemInfo< eVersion >::SetElemName (TInt theId, const std::string & theValue) virtual
Set name of the mesh element by its order number.
Implements MED::TElemInfo.
References MED::TElemInfo::myElemNames, and MED::SetString().
Referenced by MED::TTElemInfo< eVersion >::TTElemInfo().
The documentation for this struct was generated from the following file:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/MED_TStructures.hxx