FreeCAD: MeshGui::SoFCMeshOpenEdgeSet Class Reference
MeshGui::SoFCMeshOpenEdgeSet Class Reference
#include <SoFCMeshFaceSet.h>
Public Member Functions
SoFCMeshOpenEdgeSet ()
Static Public Member Functions
static void initClass ()
Protected Member Functions
virtual void computeBBox (SoAction *action, SbBox3f &box, SbVec3f &center)
Sets the bounding box of the mesh to box and its center to center.
virtual void generatePrimitives (SoAction *action)
virtual void getPrimitiveCount (SoGetPrimitiveCountAction *action)
Adds the number of the triangles to the SoGetPrimitiveCountAction.
virtual void GLRender (SoGLRenderAction *action)
Renders the open edges only.
Constructor & Destructor Documentation
SoFCMeshOpenEdgeSet()
SoFCMeshOpenEdgeSet::SoFCMeshOpenEdgeSet ()
Member Function Documentation
computeBBox()
void SoFCMeshOpenEdgeSet::computeBBox (SoAction * action, SbBox3f & box, SbVec3f & center) protected virtual
Sets the bounding box of the mesh to box and its center to center.
References MeshGui::SoFCMeshVertexElement::get(), Base::BoundBox3< _Precision >::MaxX, Base::BoundBox3< _Precision >::MaxY, Base::BoundBox3< _Precision >::MaxZ, Base::BoundBox3< _Precision >::MinX, Base::BoundBox3< _Precision >::MinY, and Base::BoundBox3< _Precision >::MinZ.
generatePrimitives()
void SoFCMeshOpenEdgeSet::generatePrimitives (SoAction * action) protected virtual
References MeshGui::SoFCMeshFacetElement::get(), and MeshGui::SoFCMeshVertexElement::get().
getPrimitiveCount()
void SoFCMeshOpenEdgeSet::getPrimitiveCount (SoGetPrimitiveCountAction * action) protected virtual
Adds the number of the triangles to the SoGetPrimitiveCountAction.
References MeshGui::SoFCMeshFacetElement::get().
GLRender()
void SoFCMeshOpenEdgeSet::GLRender (SoGLRenderAction * action) protected virtual
Renders the open edges only.
References MeshGui::SoFCMeshFacetElement::get(), and MeshGui::SoFCMeshVertexElement::get().
initClass()
void SoFCMeshOpenEdgeSet::initClass (void) static
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCMeshFaceSet.h
Sources/FreeCAD/src/Mod/Mesh/Gui/SoFCMeshFaceSet.cpp