FreeCAD: StackWalker Class Reference
StackWalker Class Reference
#include <StackWalker.h>
Classes
struct CallstackEntry
Public Types
enum { STACKWALK_MAX_NAMELEN = 1024 }
typedef BOOL(__stdcall * PReadProcessMemoryRoutine) (HANDLE hProcess, DWORD64 qwBaseAddress, PVOID lpBuffer, DWORD nSize, LPDWORD lpNumberOfBytesRead, LPVOID pUserData)
enum StackWalkOptions {
RetrieveNone = 0 , RetrieveSymbol = 1 , RetrieveLine = 2 , RetrieveModuleInfo = 4 ,
RetrieveFileVersion = 8 , RetrieveVerbose = 0xF , SymBuildPath = 0x10 , SymUseSymSrv = 0x20 ,
SymAll = 0x30 , OptionsAll = 0x3F
}
typedef enum StackWalker::StackWalkOptions StackWalkOptions
Public Member Functions
BOOL LoadModules ()
BOOL ShowCallstack (HANDLE hThread=GetCurrentThread(), const CONTEXT *context=NULL, PReadProcessMemoryRoutine readMemoryFunction=NULL, LPVOID pUserData=NULL)
StackWalker (DWORD dwProcessId, HANDLE hProcess)
StackWalker (int options=OptionsAll, LPCSTR szSymPath=NULL, DWORD dwProcessId=GetCurrentProcessId(), HANDLE hProcess=GetCurrentProcess())
virtual ~StackWalker ()
Protected Types
typedef struct StackWalker::CallstackEntry CallstackEntry
enum CallstackEntryType { firstEntry , nextEntry , lastEntry }
Protected Member Functions
virtual void OnCallstackEntry (CallstackEntryType eType, CallstackEntry &entry)
virtual void OnDbgHelpErr (LPCSTR szFuncName, DWORD gle, DWORD64 addr)
virtual void OnLoadModule (LPCSTR img, LPCSTR mod, DWORD64 baseAddr, DWORD size, DWORD result, LPCSTR symType, LPCSTR pdbName, ULONGLONG fileVersion)
virtual void OnOutput (LPCSTR szText)
virtual void OnSymInit (LPCSTR szSearchPath, DWORD symOptions, LPCSTR szUserName)
Static Protected Member Functions
static BOOL __stdcall myReadProcMem (HANDLE hProcess, DWORD64 qwBaseAddress, PVOID lpBuffer, DWORD nSize, LPDWORD lpNumberOfBytesRead)
Protected Attributes
DWORD m_dwProcessId
HANDLE m_hProcess
int m_MaxRecursionCount
BOOL m_modulesLoaded
int m_options
StackWalkerInternal * m_sw
LPSTR m_szSymPath
friend StackWalkerInternal
Member Typedef Documentation
CallstackEntry
typedef struct StackWalker::CallstackEntry StackWalker::CallstackEntry protected
PReadProcessMemoryRoutine
typedef BOOL(__stdcall * StackWalker::PReadProcessMemoryRoutine) (HANDLE hProcess, DWORD64 qwBaseAddress, PVOID lpBuffer, DWORD nSize, LPDWORD lpNumberOfBytesRead, LPVOID pUserData)
StackWalkOptions
typedef enum StackWalker::StackWalkOptions StackWalker::StackWalkOptions
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
STACKWALK_MAX_NAMELEN
CallstackEntryType
enum StackWalker::CallstackEntryType protected
Enumerator
firstEntry
nextEntry
lastEntry
StackWalkOptions
enum StackWalker::StackWalkOptions
Enumerator
RetrieveNone
RetrieveSymbol
RetrieveLine
RetrieveModuleInfo
RetrieveFileVersion
RetrieveVerbose
SymBuildPath
SymUseSymSrv
SymAll
OptionsAll
Constructor & Destructor Documentation
StackWalker() [1/2]
StackWalker::StackWalker (int options = OptionsAll, LPCSTR szSymPath = NULL, DWORD dwProcessId = GetCurrentProcessId(), HANDLE hProcess = GetCurrentProcess())
References m_dwProcessId, m_MaxRecursionCount, m_modulesLoaded, m_options, m_sw, StackWalkerInternal, and SymBuildPath.
StackWalker() [2/2]
StackWalker::StackWalker (DWORD dwProcessId, HANDLE hProcess)
References m_dwProcessId, m_MaxRecursionCount, m_modulesLoaded, m_options, m_sw, OptionsAll, and StackWalkerInternal.
~StackWalker()
StackWalker::~StackWalker () virtual
References m_sw, and m_szSymPath.
Member Function Documentation
LoadModules()
BOOL StackWalker::LoadModules ()
References StackWalkerInternal::Init(), StackWalkerInternal::LoadModules(), m_dwProcessId, m_modulesLoaded, m_options, m_sw, OnDbgHelpErr(), SymBuildPath, and SymUseSymSrv.
Referenced by ShowCallstack().
myReadProcMem()
BOOL __stdcall StackWalker::myReadProcMem (HANDLE hProcess, DWORD64 qwBaseAddress, PVOID lpBuffer, DWORD nSize, LPDWORD lpNumberOfBytesRead) static protected
Referenced by ShowCallstack().
OnCallstackEntry()
void StackWalker::OnCallstackEntry (CallstackEntryType eType, CallstackEntry & entry) protected virtual
References lastEntry, StackWalker::CallstackEntry::lineFileName, StackWalker::CallstackEntry::lineNumber, StackWalker::CallstackEntry::moduleName, StackWalker::CallstackEntry::name, StackWalker::CallstackEntry::offset, OnOutput(), STACKWALK_MAX_NAMELEN, StackWalker::CallstackEntry::undFullName, and StackWalker::CallstackEntry::undName.
Referenced by ShowCallstack().
OnDbgHelpErr()
void StackWalker::OnDbgHelpErr (LPCSTR szFuncName, DWORD gle, DWORD64 addr) protected virtual
References OnOutput(), and STACKWALK_MAX_NAMELEN.
Referenced by StackWalkerInternal::Init(), LoadModules(), and ShowCallstack().
OnLoadModule()
void StackWalker::OnLoadModule (LPCSTR img, LPCSTR mod, DWORD64 baseAddr, DWORD size, DWORD result, LPCSTR symType, LPCSTR pdbName, ULONGLONG fileVersion) protected virtual
References OnOutput(), and STACKWALK_MAX_NAMELEN.
OnOutput()
void StackWalker::OnOutput (LPCSTR szText) protected virtual
Referenced by OnCallstackEntry(), OnDbgHelpErr(), OnLoadModule(), and OnSymInit().
OnSymInit()
void StackWalker::OnSymInit (LPCSTR szSearchPath, DWORD symOptions, LPCSTR szUserName) protected virtual
References OnOutput(), and STACKWALK_MAX_NAMELEN.
Referenced by StackWalkerInternal::Init().
ShowCallstack()
BOOL StackWalker::ShowCallstack (HANDLE hThread = GetCurrentThread(), const CONTEXT * context = NULL, PReadProcessMemoryRoutine readMemoryFunction = NULL, LPVOID pUserData = NULL)
References StackWalkerInternal::IMAGEHLP_MODULE64_V3::BaseOfImage, StackWalker::CallstackEntry::baseOfImage, firstEntry, StackWalkerInternal::GetModuleInfo(), lastEntry, StackWalker::CallstackEntry::lineFileName, StackWalker::CallstackEntry::lineNumber, StackWalkerInternal::IMAGEHLP_MODULE64_V3::LoadedImageName, StackWalker::CallstackEntry::loadedImageName, LoadModules(), StackWalkerInternal::m_hDbhHelp, m_MaxRecursionCount, m_modulesLoaded, m_sw, StackWalkerInternal::IMAGEHLP_MODULE64_V3::ModuleName, StackWalker::CallstackEntry::moduleName, myReadProcMem(), StackWalker::CallstackEntry::name, nextEntry, StackWalker::CallstackEntry::offset, StackWalker::CallstackEntry::offsetFromLine, StackWalker::CallstackEntry::offsetFromSmybol, OnCallstackEntry(), OnDbgHelpErr(), StackWalkerInternal::pSGLFA, StackWalkerInternal::pSGSFA, StackWalkerInternal::pSW, StackWalkerInternal::pUDSN, StackWalkerInternal::IMAGEHLP_MODULE64_V3::SizeOfStruct, STACKWALK_MAX_NAMELEN, StackWalkerInternal::IMAGEHLP_MODULE64_V3::SymType, StackWalker::CallstackEntry::symTypeString, StackWalker::CallstackEntry::undFullName, and StackWalker::CallstackEntry::undName.
Member Data Documentation
m_dwProcessId
DWORD StackWalker::m_dwProcessId protected
Referenced by LoadModules(), and StackWalker().
m_hProcess
HANDLE StackWalker::m_hProcess protected
m_MaxRecursionCount
int StackWalker::m_MaxRecursionCount protected
Referenced by ShowCallstack(), and StackWalker().
m_modulesLoaded
BOOL StackWalker::m_modulesLoaded protected
Referenced by LoadModules(), ShowCallstack(), and StackWalker().
m_options
int StackWalker::m_options protected
Referenced by LoadModules(), and StackWalker().
m_sw
StackWalkerInternal* StackWalker::m_sw protected
Referenced by LoadModules(), ShowCallstack(), StackWalker(), and ~StackWalker().
m_szSymPath
LPSTR StackWalker::m_szSymPath protected
Referenced by ~StackWalker().
StackWalkerInternal
friend StackWalker::StackWalkerInternal protected
Referenced by StackWalker().
The documentation for this class was generated from the following files:
FreeCAD/src/Base/StackWalker.h
FreeCAD/src/Base/StackWalker.cpp