FreeCAD: U8 Struct Reference
U8 Struct Reference
#include <U8.h>
Public Member Functions
operator uint8_t () const
void read (Context &cont)
U8 ()
U8 (Context &cont)
U8 (uint8_t ui)
Constructor & Destructor Documentation
U8() [1/3]
U8::U8 ()
U8() [2/3]
U8::U8 (uint8_t ui)
U8() [3/3]
U8::U8 (Context & cont)
References read().
Member Function Documentation
operator uint8_t()
U8::operator uint8_t () const
read()
void U8::read (Context & cont)
References Context::Strm.
Referenced by gzip_utf8.GzipFile::readline(), gzip_utf8.GzipFile::seek(), and U8().
The documentation for this struct was generated from the following file:
FreeCAD/src/Mod/JtReader/App/JrJt/U8.h