FreeCAD: Raytracing::LuxTools Class Reference
Raytracing::LuxTools Class Reference
#include <LuxTools.h>
Static Public Member Functions
static std::string getCamera (const CamDef &Cam)
returns the given camera position as luxray defines
static void writeShape (std::ostream &out, const char *PartName, const TopoDS_Shape &Shape, float fMeshDeviation=0.1)
returns the given shape as luxrender material + shape data
Member Function Documentation
getCamera()
std::string LuxTools::getCamera (const CamDef & Cam) static
returns the given camera position as luxray defines
References Raytracing::CamDef::CamPos, Raytracing::CamDef::LookAt, and Raytracing::CamDef::Up.
writeShape()
void LuxTools::writeShape (std::ostream & out, const char * PartName, const TopoDS_Shape & Shape, float fMeshDeviation = 0.1) static
returns the given shape as luxrender material + shape data
References Base::Console(), Part::Tools::getPointNormals(), Part::Tools::getTriangulation(), Base::ConsoleSingleton::Log(), and Base::SequencerLauncher::next().
Referenced by Raytracing::LuxFeature::execute().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Raytracing/App/LuxTools.h
FreeCAD/src/Mod/Raytracing/App/LuxTools.cpp