FreeCAD: PartDesignGui::StateHandlerTaskPipe Class Reference
PartDesignGui::StateHandlerTaskPipe Class Reference
Convenience class to maintain states between the various task boxes for pipe.
#include <TaskPipeParameters.h>
Public Types
enum SelectionModes {
none = 0 , refProfile , refSpine , refSpineEdgeAdd ,
refSpineEdgeRemove , refAuxSpine , refAuxSpineEdgeAdd , refAuxSpineEdgeRemove ,
refSectionAdd , refSectionRemove
}
Public Member Functions
enum SelectionModes getSelectionMode ()
StateHandlerTaskPipe ()
~StateHandlerTaskPipe ()
Friends
class TaskDlgPipeParameters
Detailed Description
Convenience class to maintain states between the various task boxes for pipe.
Member Enumeration Documentation
SelectionModes
enum PartDesignGui::StateHandlerTaskPipe::SelectionModes
Enumerator
none
refProfile
refSpine
refSpineEdgeAdd
refSpineEdgeRemove
refAuxSpine
refAuxSpineEdgeAdd
refAuxSpineEdgeRemove
refSectionAdd
refSectionRemove
Constructor & Destructor Documentation
StateHandlerTaskPipe()
PartDesignGui::StateHandlerTaskPipe::StateHandlerTaskPipe ()
~StateHandlerTaskPipe()
PartDesignGui::StateHandlerTaskPipe::~StateHandlerTaskPipe ()
Member Function Documentation
getSelectionMode()
enum SelectionModes PartDesignGui::StateHandlerTaskPipe::getSelectionMode ()
Referenced by PartDesignGui::TaskPipeParameters::referenceSelected(), PartDesignGui::TaskPipeOrientation::referenceSelected(), and PartDesignGui::TaskPipeScaling::referenceSelected().
Friends And Related Function Documentation
TaskDlgPipeParameters
friend class TaskDlgPipeParameters friend
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/PartDesign/Gui/TaskPipeParameters.h