FreeCAD: App::PropertyPythonObject Class Reference
App::PropertyPythonObject Class Reference
PropertyPythonObject is used to manage Py::Object instances as properties.
#include <PropertyPythonObject.h>
Public Member Functions
virtual Property * Copy (void) const
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void fromString (const std::string &)
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
Py::Object getValue () const
virtual void Paste (const Property &from)
Paste the value from the property (mainly for Undo/Redo and transactions)
PropertyPythonObject (void)
virtual void Restore (Base::XMLReader &reader)
Use Python's pickle module to restore the object.
virtual void RestoreDocFile (Base::Reader &reader)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
virtual void Save (Base::Writer &writer) const
Use Python's pickle module to save the object.
virtual void SaveDocFile (Base::Writer &writer) const
This method is used to save large amounts of data to a binary file.
virtual void setPyObject (PyObject *)
void setValue (Py::Object)
std::string toString () const
virtual ~PropertyPythonObject ()
Public Member Functions inherited from App::Property
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual void afterRestore ()
Called at the beginning of Document::afterRestore()
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
PropertyContainer * getContainer (void) const
Get a pointer to the PropertyContainer derived class the property belongs to.
const char * getDocumentation (void) const
Get the documentation of this property.
virtual const char * getEditorName (void) const
Get the class name of the associated property editor item.
std::string getFullName () const
const char * getGroup (void) const
Get the group of this property.
const char * getName (void) const
get the name of this property in the belonging container
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
unsigned long getStatus () const
return the status bits
short getType (void) const
Get the type of the property in the container.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
bool isReadOnly () const
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
bool isTouched (void) const
Test if this property is touched.
virtual void onContainerRestored ()
Called before calling DocumentObject::onDocumentRestored()
Property ()
void purgeTouched (void)
Reset this property touched.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
void setSinglePrecision (bool single)
Sets precision of properties using floating point numbers to single, the default is double.
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
bool testStatus (Status pos) const
void touch ()
Property status handling.
virtual ~Property ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, PropStaticBegin = 21,
PropDynamic = 21, PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24,
PropTransient = 25, PropHidden = 26, PropOutput = 27, PropStaticEnd = 28,
User1 = 28, User2 = 29, User3 = 30, User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue (void)
Gets called by all setValue() methods before the value has changed.
virtual void hasSetValue (void)
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects.
Detailed Description
PropertyPythonObject is used to manage Py::Object instances as properties.
Author
Werner Mayer
Constructor & Destructor Documentation
PropertyPythonObject()
PropertyPythonObject::PropertyPythonObject (void)
Referenced by Copy().
~PropertyPythonObject()
PropertyPythonObject::~PropertyPythonObject () virtual
Member Function Documentation
Copy()
Property * PropertyPythonObject::Copy (void) const virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References PropertyPythonObject().
fromString()
void PropertyPythonObject::fromString (const std::string & repr)
Referenced by Restore(), and RestoreDocFile().
getMemSize()
unsigned int PropertyPythonObject::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence.
See also
Base::Persistence
Reimplemented from App::Property.
getPyObject()
PyObject * PropertyPythonObject::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
getValue()
Py::Object PropertyPythonObject::getValue (void) const
Referenced by App::LinkBaseExtension::extensionExecute(), Gui::ViewProviderPythonFeatureImp::finishRestoring(), TechDrawGui::DrawGuiUtil::isArchObject(), TechDrawGui::DrawGuiUtil::isArchSection(), TechDrawGui::DrawGuiUtil::isDraftObject(), Gui::ViewProviderPythonFeatureT< ViewProviderT >::onChanged(), and App::FeaturePythonT< FeatureT >::onChanged().
Paste()
void PropertyPythonObject::Paste (const Property & from) virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
References App::Property::aboutToSetValue(), Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), and App::Property::hasSetValue().
Restore()
void PropertyPythonObject::Restore (Base::XMLReader & reader) virtual
Use Python's pickle module to restore the object.
Implements Base::Persistence.
References App::Property::aboutToSetValue(), Base::XMLReader::addFile(), Base::base64_decode(), Base::Console(), fromString(), Base::XMLReader::getAttribute(), Base::XMLReader::hasAttribute(), App::Property::hasSetValue(), Base::XMLReader::readElement(), and Base::ConsoleSingleton::Warning().
RestoreDocFile()
void PropertyPythonObject::RestoreDocFile (Base::Reader &) virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Base::Persistence.
References App::Property::aboutToSetValue(), fromString(), and App::Property::hasSetValue().
Save()
void PropertyPythonObject::Save (Base::Writer & writer) const virtual
Use Python's pickle module to save the object.
Implements Base::Persistence.
References Base::base64_encode(), Base::Writer::ind(), Base::Writer::Stream(), and toString().
SaveDocFile()
void PropertyPythonObject::SaveDocFile (Base::Writer &) const virtual
This method is used to save large amounts of data to a binary file.
Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) << "\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
void PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Base::Persistence.
References Base::Writer::Stream(), and toString().
setPyObject()
void PropertyPythonObject::setPyObject (PyObject * obj) virtual
Reimplemented from Base::BaseClass.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
setValue()
void PropertyPythonObject::setValue (Py::Object o)
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Referenced by Gui::ViewProviderPythonFeatureImp::finishRestoring(), and Spreadsheet::Sheet::setObjectProperty().
toString()
std::string PropertyPythonObject::toString (void) const
References Base::Console(), and Base::ConsoleSingleton::Error().
Referenced by TechDraw::ShapeExtractor::isDraftPoint(), Save(), and SaveDocFile().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/App/PropertyPythonObject.h
Sources/FreeCAD/src/App/PropertyPythonObject.cpp