FreeCAD: Part::Geometry2dPy Class Reference
Part::Geometry2dPy Class Reference
The python export class for Geometry2d.
#include <Geometry2dPy.h>
Public Types
typedef Geometry2d * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
Geometry2dPy (Geometry2d *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geometry2d * getGeometry2dPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of Geometry2dPy.
static PyMethodDef Methods []
Methods structure of Geometry2dPy.
static PyTypeObject Type
Type structure of Geometry2dPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~Geometry2dPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * copy (PyObject *args)
implementer for the copy() method
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Geometry2d.
Member Typedef Documentation
PointerType
typedef Geometry2d* Part::Geometry2dPy::PointerType
Constructor & Destructor Documentation
~Geometry2dPy()
Geometry2dPy::~Geometry2dPy () protected
Geometry2dPy()
Geometry2dPy::Geometry2dPy (Geometry2d * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
copy()
PyObject * Geometry2dPy::copy (PyObject * args)
implementer for the copy() method
References draftmake.make_clone::clone, Part::Geometry2d::clone(), getGeometry2dPtr(), and GetType().
Referenced by staticCallback_copy().
getCustomAttributes()
PyObject * Geometry2dPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getGeometry2dPtr()
Geometry2d * Geometry2dPy::getGeometry2dPtr (void) const
getter for the object handled by this class
Referenced by Part::Curve2dPy::approximateBSpline(), Part::Curve2dPy::centerOfCurvature(), copy(), Part::Curve2dPy::curvature(), Part::Curve2dPy::discretize(), Part::OffsetCurve2dPy::getBasisCurve(), Part::Curve2dPy::getClosed(), Part::Curve2dPy::getContinuity(), Part::BezierCurve2dPy::getDegree(), Part::BSplineCurve2dPy::getDegree(), Part::BezierCurve2dPy::getEndPoint(), Part::BSplineCurve2dPy::getEndPoint(), Part::Curve2dPy::getFirstParameter(), Part::BSplineCurve2dPy::getFirstUKnotIndex(), Part::Parabola2dPy::getFocal(), Part::Parabola2dPy::getFocus(), Part::BSplineCurve2dPy::getKnot(), Part::BSplineCurve2dPy::getKnots(), Part::BSplineCurve2dPy::getKnotSequence(), Part::Curve2dPy::getLastParameter(), Part::BSplineCurve2dPy::getLastUKnotIndex(), Part::BezierCurve2dPy::getMaxDegree(), Part::BSplineCurve2dPy::getMaxDegree(), Part::BSplineCurve2dPy::getMultiplicities(), Part::BSplineCurve2dPy::getMultiplicity(), Part::BSplineCurve2dPy::getNbKnots(), Part::BezierCurve2dPy::getNbPoles(), Part::BSplineCurve2dPy::getNbPoles(), Part::OffsetCurve2dPy::getOffsetValue(), Part::Parabola2dPy::getParameter(), Part::Curve2dPy::getPeriodic(), Part::BezierCurve2dPy::getPole(), Part::BSplineCurve2dPy::getPole(), Part::BezierCurve2dPy::getPoles(), Part::BSplineCurve2dPy::getPoles(), Part::BSplineCurve2dPy::getPolesAndWeights(), Part::BezierCurve2dPy::getResolution(), Part::BSplineCurve2dPy::getResolution(), Part::BezierCurve2dPy::getStartPoint(), Part::BSplineCurve2dPy::getStartPoint(), Part::BezierCurve2dPy::getWeight(), Part::BSplineCurve2dPy::getWeight(), Part::BezierCurve2dPy::getWeights(), Part::BSplineCurve2dPy::getWeights(), Part::BezierCurve2dPy::increase(), Part::BSplineCurve2dPy::increaseDegree(), Part::BSplineCurve2dPy::increaseMultiplicity(), Part::BSplineCurve2dPy::incrementMultiplicity(), Part::BSplineCurve2dPy::insertKnot(), Part::BSplineCurve2dPy::insertKnots(), Part::BezierCurve2dPy::insertPoleAfter(), Part::BezierCurve2dPy::insertPoleBefore(), Part::Curve2dPy::intersectCC(), Part::BezierCurve2dPy::isClosed(), Part::BSplineCurve2dPy::isClosed(), Part::BezierCurve2dPy::isPeriodic(), Part::BSplineCurve2dPy::isPeriodic(), Part::BezierCurve2dPy::isRational(), Part::BSplineCurve2dPy::isRational(), Part::Curve2dPy::length(), mirror(), Part::BSplineCurve2dPy::movePoint(), Part::Curve2dPy::normal(), Part::Curve2dPy::parameter(), Part::Curve2dPy::parameterAtDistance(), Part::OffsetCurve2dPy::PyInit(), Part::Parabola2dPy::PyInit(), Part::BSplineCurve2dPy::removeKnot(), Part::BezierCurve2dPy::removePole(), rotate(), scale(), Part::BezierCurve2dPy::segment(), Part::BSplineCurve2dPy::segment(), Part::OffsetCurve2dPy::setBasisCurve(), Part::Parabola2dPy::setFocal(), Part::BSplineCurve2dPy::setKnot(), Part::BSplineCurve2dPy::setKnots(), Part::BSplineCurve2dPy::setNotPeriodic(), Part::OffsetCurve2dPy::setOffsetValue(), Part::BSplineCurve2dPy::setOrigin(), Part::BSplineCurve2dPy::setPeriodic(), Part::BezierCurve2dPy::setPole(), Part::BSplineCurve2dPy::setPole(), Part::BezierCurve2dPy::setWeight(), Part::BSplineCurve2dPy::setWeight(), Part::Curve2dPy::tangent(), Part::Curve2dPy::toBSpline(), Part::Curve2dPy::toShape(), transform(), translate(), and Part::Curve2dPy::value().
GetType()
virtual PyTypeObject* Part::Geometry2dPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
Reimplemented in Part::Parabola2dPy, Part::OffsetCurve2dPy, Part::Line2dSegmentPy, Part::Line2dPy, Part::Hyperbola2dPy, Part::Ellipse2dPy, Part::Curve2dPy, Part::Conic2dPy, Part::Circle2dPy, Part::BSplineCurve2dPy, Part::BezierCurve2dPy, Part::ArcOfParabola2dPy, Part::ArcOfHyperbola2dPy, Part::ArcOfEllipse2dPy, Part::ArcOfConic2dPy, and Part::ArcOfCircle2dPy.
Referenced by copy().
mirror()
PyObject * Geometry2dPy::mirror (PyObject * args)
implementer for the mirror() method
References getGeometry2dPtr(), Part::PartExceptionOCCError, draftgeoutils.general::vec(), Base::Vector2d::x, and Base::Vector2d::y.
Referenced by staticCallback_mirror().
PyInit()
int Geometry2dPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
Reimplemented in Part::Parabola2dPy, Part::OffsetCurve2dPy, Part::Line2dSegmentPy, Part::Line2dPy, Part::Hyperbola2dPy, Part::Ellipse2dPy, Part::Curve2dPy, Part::Conic2dPy, Part::Circle2dPy, Part::BSplineCurve2dPy, Part::BezierCurve2dPy, Part::ArcOfParabola2dPy, Part::ArcOfHyperbola2dPy, Part::ArcOfEllipse2dPy, Part::ArcOfConic2dPy, and Part::ArcOfCircle2dPy.
PyMake()
PyObject * Geometry2dPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string Geometry2dPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
rotate()
PyObject * Geometry2dPy::rotate (PyObject * args)
implementer for the rotate() method
References DraftVecUtils::angle(), getGeometry2dPtr(), Part::PartExceptionOCCError, and draftgeoutils.general::vec().
Referenced by staticCallback_rotate().
scale()
PyObject * Geometry2dPy::scale (PyObject * args)
implementer for the scale() method
References getGeometry2dPtr(), Part::PartExceptionOCCError, and draftgeoutils.general::vec().
Referenced by staticCallback_scale().
setCustomAttributes()
int Geometry2dPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
staticCallback_copy()
PyObject * Geometry2dPy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copy(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_mirror()
PyObject * Geometry2dPy::staticCallback_mirror (PyObject * self, PyObject * args) static
callback for the mirror() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), mirror(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_rotate()
PyObject * Geometry2dPy::staticCallback_rotate (PyObject * self, PyObject * args) static
callback for the rotate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), rotate(), and Base::PyObjectBase::startNotify().
staticCallback_scale()
PyObject * Geometry2dPy::staticCallback_scale (PyObject * self, PyObject * args) static
callback for the scale() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), scale(), and Base::PyObjectBase::startNotify().
staticCallback_transform()
PyObject * Geometry2dPy::staticCallback_transform (PyObject * self, PyObject * args) static
callback for the transform() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and transform().
staticCallback_translate()
PyObject * Geometry2dPy::staticCallback_translate (PyObject * self, PyObject * args) static
callback for the translate() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and translate().
transform()
PyObject * Geometry2dPy::transform (PyObject * args)
implementer for the transform() method
References getGeometry2dPtr().
Referenced by staticCallback_transform().
translate()
PyObject * Geometry2dPy::translate (PyObject * args)
implementer for the translate() method
References getGeometry2dPtr(), Part::PartExceptionOCCError, and draftgeoutils.general::vec().
Referenced by staticCallback_translate().
Member Data Documentation
GetterSetter
PyGetSetDef Geometry2dPy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of Geometry2dPy.
Methods
PyMethodDef Geometry2dPy::Methods static
Methods structure of Geometry2dPy.
Type
PyTypeObject Geometry2dPy::Type static
Type structure of Geometry2dPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/Geom2d/Geometry2dPy.h
Sources/FreeCAD/src/Mod/Part/App/Geom2d/Geometry2dPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/Geom2d/Geometry2dPy.cpp