FreeCAD: App::DocumentPy Class Reference
App::DocumentPy Class Reference
The python export class for Document.
#include <DocumentPy.h>
Public Types
typedef Document * PointerType
Public Types inherited from App::PropertyContainerPy
typedef PropertyContainer * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
DocumentPy (Document *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from App::PropertyContainerPy
PropertyContainerPy (PropertyContainer *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getPropertyByName (PyObject *args)
implementer for the getPropertyByName() method
PyObject * getPropertyTouchList (PyObject *args)
implementer for the getPropertyTouchList() method
PyObject * getTypeOfProperty (PyObject *args)
implementer for the getTypeOfProperty() method
PyObject * getTypeIdOfProperty (PyObject *args)
implementer for the getTypeIdOfProperty() method
PyObject * setEditorMode (PyObject *args)
implementer for the setEditorMode() method
PyObject * getEditorMode (PyObject *args)
implementer for the getEditorMode() method
PyObject * getGroupOfProperty (PyObject *args)
implementer for the getGroupOfProperty() method
PyObject * setPropertyStatus (PyObject *args)
implementer for the setPropertyStatus() method
PyObject * getPropertyStatus (PyObject *args)
implementer for the getPropertyStatus() method
PyObject * getDocumentationOfProperty (PyObject *args)
implementer for the getDocumentationOfProperty() method
PyObject * dumpPropertyContent (PyObject *args, PyObject *kwd)
implementer for the dumpPropertyContent() method
PyObject * restorePropertyContent (PyObject *args)
implementer for the restorePropertyContent() method
Py::List getPropertiesList (void) const
getter for the PropertiesList attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
PropertyContainer * getPropertyContainerPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::PropertyContainerPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_getPropertyByName (PyObject *self, PyObject *args)
callback for the getPropertyByName() method
static PyObject * staticCallback_getPropertyTouchList (PyObject *self, PyObject *args)
callback for the getPropertyTouchList() method
static PyObject * staticCallback_getTypeOfProperty (PyObject *self, PyObject *args)
callback for the getTypeOfProperty() method
static PyObject * staticCallback_getTypeIdOfProperty (PyObject *self, PyObject *args)
callback for the getTypeIdOfProperty() method
static PyObject * staticCallback_setEditorMode (PyObject *self, PyObject *args)
callback for the setEditorMode() method
static PyObject * staticCallback_getEditorMode (PyObject *self, PyObject *args)
callback for the getEditorMode() method
static PyObject * staticCallback_getGroupOfProperty (PyObject *self, PyObject *args)
callback for the getGroupOfProperty() method
static PyObject * staticCallback_setPropertyStatus (PyObject *self, PyObject *args)
callback for the setPropertyStatus() method
static PyObject * staticCallback_getPropertyStatus (PyObject *self, PyObject *args)
callback for the getPropertyStatus() method
static PyObject * staticCallback_getDocumentationOfProperty (PyObject *self, PyObject *args)
callback for the getDocumentationOfProperty() method
static PyObject * staticCallback_dumpPropertyContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpPropertyContent() method
static PyObject * staticCallback_restorePropertyContent (PyObject *self, PyObject *args)
callback for the restorePropertyContent() method
static PyObject * staticCallback_getPropertiesList (PyObject *self, void *closure)
getter callback for the PropertiesList attribute
static int staticCallback_setPropertiesList (PyObject *self, PyObject *value, void *closure)
setter callback for the PropertiesList attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of DocumentPy.
static PyMethodDef Methods []
Methods structure of DocumentPy.
static PyTypeObject Type
Type structure of DocumentPy.
Static Public Attributes inherited from App::PropertyContainerPy
static PyGetSetDef GetterSetter []
Attribute structure of PropertyContainerPy.
static PyMethodDef Methods []
Methods structure of PropertyContainerPy.
static PyTypeObject Type
Type structure of PropertyContainerPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~DocumentPy ()
Protected Member Functions inherited from App::PropertyContainerPy
~PropertyContainerPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * save (PyObject *args)
implementer for the save() method
PyObject * saveAs (PyObject *args)
implementer for the saveAs() method
PyObject * saveCopy (PyObject *args)
implementer for the saveCopy() method
PyObject * load (PyObject *args)
implementer for the load() method
PyObject * restore (PyObject *args)
implementer for the restore() method
PyObject * mergeProject (PyObject *args)
implementer for the mergeProject() method
PyObject * exportGraphviz (PyObject *args)
implementer for the exportGraphviz() method
PyObject * openTransaction (PyObject *args)
implementer for the openTransaction() method
PyObject * abortTransaction (PyObject *args)
implementer for the abortTransaction() method
PyObject * commitTransaction (PyObject *args)
implementer for the commitTransaction() method
PyObject * addObject (PyObject *args, PyObject *kwd)
implementer for the addObject() method
PyObject * removeObject (PyObject *args)
implementer for the removeObject() method
PyObject * copyObject (PyObject *args)
implementer for the copyObject() method
PyObject * moveObject (PyObject *args)
implementer for the moveObject() method
PyObject * importLinks (PyObject *args)
implementer for the importLinks() method
PyObject * undo (PyObject *args)
implementer for the undo() method
PyObject * redo (PyObject *args)
implementer for the redo() method
PyObject * clearUndos (PyObject *args)
implementer for the clearUndos() method
PyObject * recompute (PyObject *args)
implementer for the recompute() method
PyObject * getObject (PyObject *args)
implementer for the getObject() method
PyObject * getObjectsByLabel (PyObject *args)
implementer for the getObjectsByLabel() method
PyObject * findObjects (PyObject *args, PyObject *kwd)
implementer for the findObjects() method
PyObject * getLinksTo (PyObject *args)
implementer for the getLinksTo() method
PyObject * supportedTypes (PyObject *args)
implementer for the supportedTypes() method
PyObject * getTempFileName (PyObject *args)
implementer for the getTempFileName() method
PyObject * getDependentDocuments (PyObject *args)
implementer for the getDependentDocuments() method
static PyObject * staticCallback_save (PyObject *self, PyObject *args)
callback for the save() method
static PyObject * staticCallback_saveAs (PyObject *self, PyObject *args)
callback for the saveAs() method
static PyObject * staticCallback_saveCopy (PyObject *self, PyObject *args)
callback for the saveCopy() method
static PyObject * staticCallback_load (PyObject *self, PyObject *args)
callback for the load() method
static PyObject * staticCallback_restore (PyObject *self, PyObject *args)
callback for the restore() method
static PyObject * staticCallback_mergeProject (PyObject *self, PyObject *args)
callback for the mergeProject() method
static PyObject * staticCallback_exportGraphviz (PyObject *self, PyObject *args)
callback for the exportGraphviz() method
static PyObject * staticCallback_openTransaction (PyObject *self, PyObject *args)
callback for the openTransaction() method
static PyObject * staticCallback_abortTransaction (PyObject *self, PyObject *args)
callback for the abortTransaction() method
static PyObject * staticCallback_commitTransaction (PyObject *self, PyObject *args)
callback for the commitTransaction() method
static PyObject * staticCallback_addObject (PyObject *self, PyObject *args, PyObject *kwd)
callback for the addObject() method
static PyObject * staticCallback_removeObject (PyObject *self, PyObject *args)
callback for the removeObject() method
static PyObject * staticCallback_copyObject (PyObject *self, PyObject *args)
callback for the copyObject() method
static PyObject * staticCallback_moveObject (PyObject *self, PyObject *args)
callback for the moveObject() method
static PyObject * staticCallback_importLinks (PyObject *self, PyObject *args)
callback for the importLinks() method
static PyObject * staticCallback_undo (PyObject *self, PyObject *args)
callback for the undo() method
static PyObject * staticCallback_redo (PyObject *self, PyObject *args)
callback for the redo() method
static PyObject * staticCallback_clearUndos (PyObject *self, PyObject *args)
callback for the clearUndos() method
static PyObject * staticCallback_recompute (PyObject *self, PyObject *args)
callback for the recompute() method
static PyObject * staticCallback_getObject (PyObject *self, PyObject *args)
callback for the getObject() method
static PyObject * staticCallback_getObjectsByLabel (PyObject *self, PyObject *args)
callback for the getObjectsByLabel() method
static PyObject * staticCallback_findObjects (PyObject *self, PyObject *args, PyObject *kwd)
callback for the findObjects() method
static PyObject * staticCallback_getLinksTo (PyObject *self, PyObject *args)
callback for the getLinksTo() method
static PyObject * staticCallback_supportedTypes (PyObject *self, PyObject *args)
callback for the supportedTypes() method
static PyObject * staticCallback_getTempFileName (PyObject *self, PyObject *args)
callback for the getTempFileName() method
static PyObject * staticCallback_getDependentDocuments (PyObject *self, PyObject *args)
callback for the getDependentDocuments() method
callbacks and implementers for the python object attributes
Py::String getDependencyGraph (void) const
getter for the DependencyGraph attribute
Py::Object getActiveObject (void) const
getter for the ActiveObject attribute
Py::List getObjects (void) const
getter for the Objects attribute
Py::List getTopologicalSortedObjects (void) const
getter for the TopologicalSortedObjects attribute
Py::List getRootObjects (void) const
getter for the RootObjects attribute
Py::Int getUndoMode (void) const
getter for the UndoMode attribute
void setUndoMode (Py::Int arg)
setter for the UndoMode attribute
Py::Int getUndoRedoMemSize (void) const
getter for the UndoRedoMemSize attribute
Py::Int getUndoCount (void) const
getter for the UndoCount attribute
Py::Int getRedoCount (void) const
getter for the RedoCount attribute
Py::List getUndoNames (void) const
getter for the UndoNames attribute
Py::List getRedoNames (void) const
getter for the RedoNames attribute
Py::String getName (void) const
getter for the Name attribute
Py::Boolean getRecomputesFrozen (void) const
getter for the RecomputesFrozen attribute
void setRecomputesFrozen (Py::Boolean arg)
setter for the RecomputesFrozen attribute
Py::Boolean getHasPendingTransaction (void) const
getter for the HasPendingTransaction attribute
Py::List getInList (void) const
getter for the InList attribute
Py::List getOutList (void) const
getter for the OutList attribute
Py::Boolean getRestoring (void) const
getter for the Restoring attribute
Py::Boolean getPartial (void) const
getter for the Partial attribute
Py::Boolean getImporting (void) const
getter for the Importing attribute
Py::Boolean getRecomputing (void) const
getter for the Recomputing attribute
Py::Boolean getTransacting (void) const
getter for the Transacting attribute
Py::String getOldLabel (void) const
getter for the OldLabel attribute
Py::Boolean getTemporary (void) const
getter for the Temporary attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Document * getDocumentPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getDependencyGraph (PyObject *self, void *closure)
getter callback for the DependencyGraph attribute
static int staticCallback_setDependencyGraph (PyObject *self, PyObject *value, void *closure)
setter callback for the DependencyGraph attribute
static PyObject * staticCallback_getActiveObject (PyObject *self, void *closure)
getter callback for the ActiveObject attribute
static int staticCallback_setActiveObject (PyObject *self, PyObject *value, void *closure)
setter callback for the ActiveObject attribute
static PyObject * staticCallback_getObjects (PyObject *self, void *closure)
getter callback for the Objects attribute
static int staticCallback_setObjects (PyObject *self, PyObject *value, void *closure)
setter callback for the Objects attribute
static PyObject * staticCallback_getTopologicalSortedObjects (PyObject *self, void *closure)
getter callback for the TopologicalSortedObjects attribute
static int staticCallback_setTopologicalSortedObjects (PyObject *self, PyObject *value, void *closure)
setter callback for the TopologicalSortedObjects attribute
static PyObject * staticCallback_getRootObjects (PyObject *self, void *closure)
getter callback for the RootObjects attribute
static int staticCallback_setRootObjects (PyObject *self, PyObject *value, void *closure)
setter callback for the RootObjects attribute
static PyObject * staticCallback_getUndoMode (PyObject *self, void *closure)
getter callback for the UndoMode attribute
static int staticCallback_setUndoMode (PyObject *self, PyObject *value, void *closure)
setter callback for the UndoMode attribute
static PyObject * staticCallback_getUndoRedoMemSize (PyObject *self, void *closure)
getter callback for the UndoRedoMemSize attribute
static int staticCallback_setUndoRedoMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the UndoRedoMemSize attribute
static PyObject * staticCallback_getUndoCount (PyObject *self, void *closure)
getter callback for the UndoCount attribute
static int staticCallback_setUndoCount (PyObject *self, PyObject *value, void *closure)
setter callback for the UndoCount attribute
static PyObject * staticCallback_getRedoCount (PyObject *self, void *closure)
getter callback for the RedoCount attribute
static int staticCallback_setRedoCount (PyObject *self, PyObject *value, void *closure)
setter callback for the RedoCount attribute
static PyObject * staticCallback_getUndoNames (PyObject *self, void *closure)
getter callback for the UndoNames attribute
static int staticCallback_setUndoNames (PyObject *self, PyObject *value, void *closure)
setter callback for the UndoNames attribute
static PyObject * staticCallback_getRedoNames (PyObject *self, void *closure)
getter callback for the RedoNames attribute
static int staticCallback_setRedoNames (PyObject *self, PyObject *value, void *closure)
setter callback for the RedoNames attribute
static PyObject * staticCallback_getName (PyObject *self, void *closure)
getter callback for the Name attribute
static int staticCallback_setName (PyObject *self, PyObject *value, void *closure)
setter callback for the Name attribute
static PyObject * staticCallback_getRecomputesFrozen (PyObject *self, void *closure)
getter callback for the RecomputesFrozen attribute
static int staticCallback_setRecomputesFrozen (PyObject *self, PyObject *value, void *closure)
setter callback for the RecomputesFrozen attribute
static PyObject * staticCallback_getHasPendingTransaction (PyObject *self, void *closure)
getter callback for the HasPendingTransaction attribute
static int staticCallback_setHasPendingTransaction (PyObject *self, PyObject *value, void *closure)
setter callback for the HasPendingTransaction attribute
static PyObject * staticCallback_getInList (PyObject *self, void *closure)
getter callback for the InList attribute
static int staticCallback_setInList (PyObject *self, PyObject *value, void *closure)
setter callback for the InList attribute
static PyObject * staticCallback_getOutList (PyObject *self, void *closure)
getter callback for the OutList attribute
static int staticCallback_setOutList (PyObject *self, PyObject *value, void *closure)
setter callback for the OutList attribute
static PyObject * staticCallback_getRestoring (PyObject *self, void *closure)
getter callback for the Restoring attribute
static int staticCallback_setRestoring (PyObject *self, PyObject *value, void *closure)
setter callback for the Restoring attribute
static PyObject * staticCallback_getPartial (PyObject *self, void *closure)
getter callback for the Partial attribute
static int staticCallback_setPartial (PyObject *self, PyObject *value, void *closure)
setter callback for the Partial attribute
static PyObject * staticCallback_getImporting (PyObject *self, void *closure)
getter callback for the Importing attribute
static int staticCallback_setImporting (PyObject *self, PyObject *value, void *closure)
setter callback for the Importing attribute
static PyObject * staticCallback_getRecomputing (PyObject *self, void *closure)
getter callback for the Recomputing attribute
static int staticCallback_setRecomputing (PyObject *self, PyObject *value, void *closure)
setter callback for the Recomputing attribute
static PyObject * staticCallback_getTransacting (PyObject *self, void *closure)
getter callback for the Transacting attribute
static int staticCallback_setTransacting (PyObject *self, PyObject *value, void *closure)
setter callback for the Transacting attribute
static PyObject * staticCallback_getOldLabel (PyObject *self, void *closure)
getter callback for the OldLabel attribute
static int staticCallback_setOldLabel (PyObject *self, PyObject *value, void *closure)
setter callback for the OldLabel attribute
static PyObject * staticCallback_getTemporary (PyObject *self, void *closure)
getter callback for the Temporary attribute
static int staticCallback_setTemporary (PyObject *self, PyObject *value, void *closure)
setter callback for the Temporary attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for Document.
Member Typedef Documentation
PointerType
typedef Document* App::DocumentPy::PointerType
Constructor & Destructor Documentation
~DocumentPy()
DocumentPy::~DocumentPy () protected
DocumentPy()
DocumentPy::DocumentPy (Document * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
abortTransaction()
PyObject * DocumentPy::abortTransaction (PyObject * args)
implementer for the abortTransaction() method
References App::Document::abortTransaction(), and getDocumentPtr().
Referenced by staticCallback_abortTransaction().
addObject()
PyObject * DocumentPy::addObject (PyObject * args, PyObject * kwd)
implementer for the addObject() method
References App::Document::addObject(), Base::BaseExceptionFreeCADError, Base::Type::createInstanceByName(), Base::Persistence::getClassTypeId(), getDocumentPtr(), and App::DocumentObject::getPyObject().
Referenced by ArchPanel.NestTaskPanel::getContainer(), ArchPanel.NestTaskPanel::getShapes(), and staticCallback_addObject().
clearUndos()
PyObject * DocumentPy::clearUndos (PyObject * args)
implementer for the clearUndos() method
References App::Document::clearUndos(), and getDocumentPtr().
Referenced by staticCallback_clearUndos().
commitTransaction()
PyObject * DocumentPy::commitTransaction (PyObject * args)
implementer for the commitTransaction() method
References App::Document::commitTransaction(), and getDocumentPtr().
Referenced by staticCallback_commitTransaction().
copyObject()
PyObject * DocumentPy::copyObject (PyObject * args)
implementer for the copyObject() method
References App::Document::copyObject(), getDocumentPtr(), and App::DocumentObjectPy::Type.
Referenced by staticCallback_copyObject().
exportGraphviz()
PyObject * DocumentPy::exportGraphviz (PyObject * args)
implementer for the exportGraphviz() method
References App::Document::exportGraphviz(), and getDocumentPtr().
Referenced by staticCallback_exportGraphviz().
findObjects()
PyObject * DocumentPy::findObjects (PyObject * args, PyObject * kwd)
implementer for the findObjects() method
References Base::Type::badType(), App::Document::findObjects(), Base::Type::fromName(), Base::Persistence::getClassTypeId(), and getDocumentPtr().
Referenced by staticCallback_findObjects().
getActiveObject()
Py::Object DocumentPy::getActiveObject (void) const
getter for the ActiveObject attribute
References App::Document::getActiveObject(), getDocumentPtr(), and App::DocumentObject::getPyObject().
Referenced by staticCallback_getActiveObject().
getCustomAttributes()
PyObject * DocumentPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
References getDocumentPtr(), App::Document::getObject(), App::PropertyContainer::getPropertyByName(), and App::PropertyContainerPy::getPropertyContainerPtr().
getDependencyGraph()
Py::String DocumentPy::getDependencyGraph (void) const
getter for the DependencyGraph attribute
References App::Document::exportGraphviz(), and getDocumentPtr().
Referenced by staticCallback_getDependencyGraph().
getDependentDocuments()
PyObject * DocumentPy::getDependentDocuments (PyObject * args)
implementer for the getDependentDocuments() method
References App::Document::getDependentDocuments(), and getDocumentPtr().
Referenced by staticCallback_getDependentDocuments().
getDocumentPtr()
Document * DocumentPy::getDocumentPtr (void) const
getter for the object handled by this class
Referenced by abortTransaction(), addObject(), clearUndos(), commitTransaction(), copyObject(), exportGraphviz(), findObjects(), getActiveObject(), getCustomAttributes(), getDependencyGraph(), getDependentDocuments(), getHasPendingTransaction(), getImporting(), getInList(), getLinksTo(), getName(), getObject(), getObjects(), getObjectsByLabel(), getOldLabel(), getOutList(), getPartial(), getRecomputesFrozen(), getRecomputing(), getRedoCount(), getRedoNames(), getRestoring(), getRootObjects(), getTempFileName(), getTemporary(), getTopologicalSortedObjects(), getTransacting(), getUndoCount(), getUndoMode(), getUndoNames(), getUndoRedoMemSize(), importLinks(), load(), mergeProject(), moveObject(), openTransaction(), recompute(), redo(), removeObject(), representation(), restore(), save(), saveAs(), saveCopy(), setCustomAttributes(), setRecomputesFrozen(), setUndoMode(), and undo().
getHasPendingTransaction()
Py::Boolean DocumentPy::getHasPendingTransaction (void) const
getter for the HasPendingTransaction attribute
References getDocumentPtr().
Referenced by staticCallback_getHasPendingTransaction().
getImporting()
Py::Boolean DocumentPy::getImporting (void) const
getter for the Importing attribute
References getDocumentPtr().
Referenced by staticCallback_getImporting().
getInList()
Py::List DocumentPy::getInList (void) const
getter for the InList attribute
References App::PropertyXLink::getDocumentInList(), and getDocumentPtr().
Referenced by staticCallback_getInList().
getLinksTo()
PyObject * DocumentPy::getLinksTo (PyObject * args)
implementer for the getLinksTo() method
References getDocumentPtr(), App::Document::getLinksTo(), and App::DocumentObjectPy::Type.
Referenced by staticCallback_getLinksTo().
getName()
Py::String DocumentPy::getName (void) const
getter for the Name attribute
References getDocumentPtr().
Referenced by staticCallback_getName().
getObject()
PyObject * DocumentPy::getObject (PyObject * args)
implementer for the getObject() method
References getDocumentPtr(), App::Document::getObject(), App::Document::getObjectByID(), and App::DocumentObject::getPyObject().
Referenced by staticCallback_getObject().
getObjects()
Py::List DocumentPy::getObjects (void) const
getter for the Objects attribute
References getDocumentPtr(), and App::Document::getObjects().
Referenced by staticCallback_getObjects().
getObjectsByLabel()
PyObject * DocumentPy::getObjectsByLabel (PyObject * args)
implementer for the getObjectsByLabel() method
References getDocumentPtr(), and App::Document::getObjects().
Referenced by staticCallback_getObjectsByLabel().
getOldLabel()
Py::String DocumentPy::getOldLabel (void) const
getter for the OldLabel attribute
References getDocumentPtr().
Referenced by staticCallback_getOldLabel().
getOutList()
Py::List DocumentPy::getOutList (void) const
getter for the OutList attribute
References App::PropertyXLink::getDocumentOutList(), and getDocumentPtr().
Referenced by staticCallback_getOutList().
getPartial()
Py::Boolean DocumentPy::getPartial (void) const
getter for the Partial attribute
References getDocumentPtr().
Referenced by staticCallback_getPartial().
getRecomputesFrozen()
Py::Boolean DocumentPy::getRecomputesFrozen (void) const
getter for the RecomputesFrozen attribute
References getDocumentPtr().
Referenced by staticCallback_getRecomputesFrozen().
getRecomputing()
Py::Boolean DocumentPy::getRecomputing (void) const
getter for the Recomputing attribute
References getDocumentPtr().
Referenced by staticCallback_getRecomputing().
getRedoCount()
Py::Int DocumentPy::getRedoCount (void) const
getter for the RedoCount attribute
References getDocumentPtr().
Referenced by staticCallback_getRedoCount().
getRedoNames()
Py::List DocumentPy::getRedoNames (void) const
getter for the RedoNames attribute
References App::Document::getAvailableRedoNames(), and getDocumentPtr().
Referenced by staticCallback_getRedoNames().
getRestoring()
Py::Boolean DocumentPy::getRestoring (void) const
getter for the Restoring attribute
References getDocumentPtr().
Referenced by staticCallback_getRestoring().
getRootObjects()
Py::List DocumentPy::getRootObjects (void) const
getter for the RootObjects attribute
References getDocumentPtr(), and App::Document::getRootObjects().
Referenced by staticCallback_getRootObjects().
getTempFileName()
PyObject * DocumentPy::getTempFileName (PyObject * args)
implementer for the getTempFileName() method
References Base::FileInfo::deleteFile(), Base::FileInfo::filePath(), getDocumentPtr(), and Base::FileInfo::getTempFileName().
Referenced by staticCallback_getTempFileName().
getTemporary()
Py::Boolean DocumentPy::getTemporary (void) const
getter for the Temporary attribute
References getDocumentPtr(), and App::Document::TempDoc.
Referenced by staticCallback_getTemporary().
getTopologicalSortedObjects()
Py::List DocumentPy::getTopologicalSortedObjects (void) const
getter for the TopologicalSortedObjects attribute
References getDocumentPtr(), and App::Document::topologicalSort().
Referenced by staticCallback_getTopologicalSortedObjects().
getTransacting()
Py::Boolean DocumentPy::getTransacting (void) const
getter for the Transacting attribute
References getDocumentPtr().
Referenced by staticCallback_getTransacting().
GetType()
virtual PyTypeObject* App::DocumentPy::GetType (void) virtual
Reimplemented from App::PropertyContainerPy.
getUndoCount()
Py::Int DocumentPy::getUndoCount (void) const
getter for the UndoCount attribute
References getDocumentPtr().
Referenced by staticCallback_getUndoCount().
getUndoMode()
Py::Int DocumentPy::getUndoMode (void) const
getter for the UndoMode attribute
References getDocumentPtr().
Referenced by staticCallback_getUndoMode().
getUndoNames()
Py::List DocumentPy::getUndoNames (void) const
getter for the UndoNames attribute
References App::Document::getAvailableUndoNames(), and getDocumentPtr().
Referenced by staticCallback_getUndoNames().
getUndoRedoMemSize()
Py::Int DocumentPy::getUndoRedoMemSize (void) const
getter for the UndoRedoMemSize attribute
References getDocumentPtr().
Referenced by staticCallback_getUndoRedoMemSize().
importLinks()
PyObject * DocumentPy::importLinks (PyObject * args)
implementer for the importLinks() method
References getDocumentPtr(), App::Document::getObjects(), App::Document::importLinks(), and App::DocumentObjectPy::Type.
Referenced by staticCallback_importLinks().
load()
PyObject * DocumentPy::load (PyObject * args)
implementer for the load() method
References App::Document::FileName, getDocumentPtr(), Base::FileInfo::isReadable(), App::Document::restore(), and App::PropertyString::setValue().
Referenced by staticCallback_load().
mergeProject()
PyObject * DocumentPy::mergeProject (PyObject * args)
implementer for the mergeProject() method
References getDocumentPtr(), and App::MergeDocuments::importObjects().
Referenced by staticCallback_mergeProject().
moveObject()
PyObject * DocumentPy::moveObject (PyObject * args)
implementer for the moveObject() method
References Base::BaseExceptionFreeCADError, App::DocumentObjectPy::getDocumentObjectPtr(), getDocumentPtr(), App::Document::moveObject(), and App::DocumentObjectPy::Type.
Referenced by staticCallback_moveObject().
openTransaction()
PyObject * DocumentPy::openTransaction (PyObject * args)
implementer for the openTransaction() method
References getDocumentPtr(), and App::Document::openTransaction().
Referenced by staticCallback_openTransaction().
PyInit()
int DocumentPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from App::PropertyContainerPy.
PyMake()
PyObject * DocumentPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
recompute()
PyObject * DocumentPy::recompute (PyObject * args)
implementer for the recompute() method
References App::Document::DepNoCycle, getDocumentPtr(), App::Document::recompute(), and App::DocumentObjectPy::Type.
Referenced by draftguitools.gui_trackers.arcTracker::setApertureAngle(), draftguitools.gui_trackers.arcTracker::setEndAngle(), draftguitools.gui_trackers.arcTracker::setStartAngle(), staticCallback_recompute(), draftguitools.gui_trackers.bsplineTracker::update(), and draftguitools.gui_trackers.bezcurveTracker::update().
redo()
PyObject * DocumentPy::redo (PyObject * args)
implementer for the redo() method
References getDocumentPtr(), and App::Document::redo().
Referenced by staticCallback_redo().
removeObject()
PyObject * DocumentPy::removeObject (PyObject * args)
implementer for the removeObject() method
References Base::BaseExceptionFreeCADError, getDocumentPtr(), App::Document::getObject(), and App::Document::removeObject().
Referenced by staticCallback_removeObject().
representation()
std::string DocumentPy::representation (void) const
References getDocumentPtr().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
restore()
PyObject * DocumentPy::restore (PyObject * args)
implementer for the restore() method
References App::Document::FileName, getDocumentPtr(), App::PropertyString::getValue(), Base::FileInfo::isReadable(), and App::Document::restore().
Referenced by staticCallback_restore().
save()
PyObject * DocumentPy::save (PyObject * args)
implementer for the save() method
References App::Document::FileName, getDocumentPtr(), App::PropertyString::getValue(), and Base::FileInfo::isReadable().
Referenced by shipAreasCurve.TaskPanel.TaskPanel::accept(), shipGZ.TaskPanel.TaskPanel::accept(), shipHydrostatics.TaskPanel.TaskPanel::accept(), Mod.Show.mTempoVis.TempoVis::modify(), Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), Mod.Show.mTempoVis.TempoVis::saveCamera(), and staticCallback_save().
saveAs()
PyObject * DocumentPy::saveAs (PyObject * args)
implementer for the saveAs() method
References getDocumentPtr(), and App::Document::saveAs().
Referenced by staticCallback_saveAs().
saveCopy()
PyObject * DocumentPy::saveCopy (PyObject * args)
implementer for the saveCopy() method
References getDocumentPtr(), and App::Document::saveCopy().
Referenced by staticCallback_saveCopy().
setCustomAttributes()
int DocumentPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
References getDocumentPtr(), App::Document::getObject(), App::PropertyContainer::getPropertyByName(), and App::PropertyContainerPy::getPropertyContainerPtr().
setRecomputesFrozen()
void DocumentPy::setRecomputesFrozen (Py::Boolean arg)
setter for the RecomputesFrozen attribute
References getDocumentPtr(), and App::Document::setStatus().
Referenced by staticCallback_setRecomputesFrozen().
setUndoMode()
void DocumentPy::setUndoMode (Py::Int arg)
setter for the UndoMode attribute
References getDocumentPtr(), and App::Document::setUndoMode().
Referenced by staticCallback_setUndoMode().
staticCallback_abortTransaction()
PyObject * DocumentPy::staticCallback_abortTransaction (PyObject * self, PyObject * args) static
callback for the abortTransaction() method
References abortTransaction(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_addObject()
PyObject * DocumentPy::staticCallback_addObject (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the addObject() method
References addObject(), Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_clearUndos()
PyObject * DocumentPy::staticCallback_clearUndos (PyObject * self, PyObject * args) static
callback for the clearUndos() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, clearUndos(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_commitTransaction()
PyObject * DocumentPy::staticCallback_commitTransaction (PyObject * self, PyObject * args) static
callback for the commitTransaction() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, commitTransaction(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_copyObject()
PyObject * DocumentPy::staticCallback_copyObject (PyObject * self, PyObject * args) static
callback for the copyObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copyObject(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_exportGraphviz()
PyObject * DocumentPy::staticCallback_exportGraphviz (PyObject * self, PyObject * args) static
callback for the exportGraphviz() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, exportGraphviz(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_findObjects()
PyObject * DocumentPy::staticCallback_findObjects (PyObject * self, PyObject * args, PyObject * kwd) static
callback for the findObjects() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, findObjects(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getActiveObject()
PyObject * DocumentPy::staticCallback_getActiveObject (PyObject * self, void * closure) static
getter callback for the ActiveObject attribute
References Base::BaseExceptionFreeCADError, getActiveObject(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getDependencyGraph()
PyObject * DocumentPy::staticCallback_getDependencyGraph (PyObject * self, void * closure) static
getter callback for the DependencyGraph attribute
References Base::BaseExceptionFreeCADError, getDependencyGraph(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getDependentDocuments()
PyObject * DocumentPy::staticCallback_getDependentDocuments (PyObject * self, PyObject * args) static
callback for the getDependentDocuments() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getDependentDocuments(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getHasPendingTransaction()
PyObject * DocumentPy::staticCallback_getHasPendingTransaction (PyObject * self, void * closure) static
getter callback for the HasPendingTransaction attribute
References Base::BaseExceptionFreeCADError, getHasPendingTransaction(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getImporting()
PyObject * DocumentPy::staticCallback_getImporting (PyObject * self, void * closure) static
getter callback for the Importing attribute
References Base::BaseExceptionFreeCADError, getImporting(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getInList()
PyObject * DocumentPy::staticCallback_getInList (PyObject * self, void * closure) static
getter callback for the InList attribute
References Base::BaseExceptionFreeCADError, getInList(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getLinksTo()
PyObject * DocumentPy::staticCallback_getLinksTo (PyObject * self, PyObject * args) static
callback for the getLinksTo() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getLinksTo(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getName()
PyObject * DocumentPy::staticCallback_getName (PyObject * self, void * closure) static
getter callback for the Name attribute
References Base::BaseExceptionFreeCADError, getName(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getObject()
PyObject * DocumentPy::staticCallback_getObject (PyObject * self, PyObject * args) static
callback for the getObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getObject(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getObjects()
PyObject * DocumentPy::staticCallback_getObjects (PyObject * self, void * closure) static
getter callback for the Objects attribute
References Base::BaseExceptionFreeCADError, getObjects(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getObjectsByLabel()
PyObject * DocumentPy::staticCallback_getObjectsByLabel (PyObject * self, PyObject * args) static
callback for the getObjectsByLabel() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getObjectsByLabel(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getOldLabel()
PyObject * DocumentPy::staticCallback_getOldLabel (PyObject * self, void * closure) static
getter callback for the OldLabel attribute
References Base::BaseExceptionFreeCADError, getOldLabel(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getOutList()
PyObject * DocumentPy::staticCallback_getOutList (PyObject * self, void * closure) static
getter callback for the OutList attribute
References Base::BaseExceptionFreeCADError, getOutList(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPartial()
PyObject * DocumentPy::staticCallback_getPartial (PyObject * self, void * closure) static
getter callback for the Partial attribute
References Base::BaseExceptionFreeCADError, getPartial(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRecomputesFrozen()
PyObject * DocumentPy::staticCallback_getRecomputesFrozen (PyObject * self, void * closure) static
getter callback for the RecomputesFrozen attribute
References Base::BaseExceptionFreeCADError, getRecomputesFrozen(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRecomputing()
PyObject * DocumentPy::staticCallback_getRecomputing (PyObject * self, void * closure) static
getter callback for the Recomputing attribute
References Base::BaseExceptionFreeCADError, getRecomputing(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRedoCount()
PyObject * DocumentPy::staticCallback_getRedoCount (PyObject * self, void * closure) static
getter callback for the RedoCount attribute
References Base::BaseExceptionFreeCADError, getRedoCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRedoNames()
PyObject * DocumentPy::staticCallback_getRedoNames (PyObject * self, void * closure) static
getter callback for the RedoNames attribute
References Base::BaseExceptionFreeCADError, getRedoNames(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRestoring()
PyObject * DocumentPy::staticCallback_getRestoring (PyObject * self, void * closure) static
getter callback for the Restoring attribute
References Base::BaseExceptionFreeCADError, getRestoring(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getRootObjects()
PyObject * DocumentPy::staticCallback_getRootObjects (PyObject * self, void * closure) static
getter callback for the RootObjects attribute
References Base::BaseExceptionFreeCADError, getRootObjects(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTempFileName()
PyObject * DocumentPy::staticCallback_getTempFileName (PyObject * self, PyObject * args) static
callback for the getTempFileName() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, getTempFileName(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_getTemporary()
PyObject * DocumentPy::staticCallback_getTemporary (PyObject * self, void * closure) static
getter callback for the Temporary attribute
References Base::BaseExceptionFreeCADError, getTemporary(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTopologicalSortedObjects()
PyObject * DocumentPy::staticCallback_getTopologicalSortedObjects (PyObject * self, void * closure) static
getter callback for the TopologicalSortedObjects attribute
References Base::BaseExceptionFreeCADError, getTopologicalSortedObjects(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTransacting()
PyObject * DocumentPy::staticCallback_getTransacting (PyObject * self, void * closure) static
getter callback for the Transacting attribute
References Base::BaseExceptionFreeCADError, getTransacting(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getUndoCount()
PyObject * DocumentPy::staticCallback_getUndoCount (PyObject * self, void * closure) static
getter callback for the UndoCount attribute
References Base::BaseExceptionFreeCADError, getUndoCount(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getUndoMode()
PyObject * DocumentPy::staticCallback_getUndoMode (PyObject * self, void * closure) static
getter callback for the UndoMode attribute
References Base::BaseExceptionFreeCADError, getUndoMode(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getUndoNames()
PyObject * DocumentPy::staticCallback_getUndoNames (PyObject * self, void * closure) static
getter callback for the UndoNames attribute
References Base::BaseExceptionFreeCADError, getUndoNames(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getUndoRedoMemSize()
PyObject * DocumentPy::staticCallback_getUndoRedoMemSize (PyObject * self, void * closure) static
getter callback for the UndoRedoMemSize attribute
References Base::BaseExceptionFreeCADError, getUndoRedoMemSize(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_importLinks()
PyObject * DocumentPy::staticCallback_importLinks (PyObject * self, PyObject * args) static
callback for the importLinks() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, importLinks(), Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_load()
PyObject * DocumentPy::staticCallback_load (PyObject * self, PyObject * args) static
callback for the load() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), load(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_mergeProject()
PyObject * DocumentPy::staticCallback_mergeProject (PyObject * self, PyObject * args) static
callback for the mergeProject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), mergeProject(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_moveObject()
PyObject * DocumentPy::staticCallback_moveObject (PyObject * self, PyObject * args) static
callback for the moveObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), moveObject(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_openTransaction()
PyObject * DocumentPy::staticCallback_openTransaction (PyObject * self, PyObject * args) static
callback for the openTransaction() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), openTransaction(), Base::PyObjectBase::PyObjectBase(), and Base::PyObjectBase::startNotify().
staticCallback_recompute()
PyObject * DocumentPy::staticCallback_recompute (PyObject * self, PyObject * args) static
callback for the recompute() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), recompute(), and Base::PyObjectBase::startNotify().
staticCallback_redo()
PyObject * DocumentPy::staticCallback_redo (PyObject * self, PyObject * args) static
callback for the redo() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), redo(), and Base::PyObjectBase::startNotify().
staticCallback_removeObject()
PyObject * DocumentPy::staticCallback_removeObject (PyObject * self, PyObject * args) static
callback for the removeObject() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), removeObject(), and Base::PyObjectBase::startNotify().
staticCallback_restore()
PyObject * DocumentPy::staticCallback_restore (PyObject * self, PyObject * args) static
callback for the restore() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), restore(), and Base::PyObjectBase::startNotify().
staticCallback_save()
PyObject * DocumentPy::staticCallback_save (PyObject * self, PyObject * args) static
callback for the save() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), save(), and Base::PyObjectBase::startNotify().
staticCallback_saveAs()
PyObject * DocumentPy::staticCallback_saveAs (PyObject * self, PyObject * args) static
callback for the saveAs() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), saveAs(), and Base::PyObjectBase::startNotify().
staticCallback_saveCopy()
PyObject * DocumentPy::staticCallback_saveCopy (PyObject * self, PyObject * args) static
callback for the saveCopy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), saveCopy(), and Base::PyObjectBase::startNotify().
staticCallback_setActiveObject()
int DocumentPy::staticCallback_setActiveObject (PyObject * self, PyObject * value, void * closure) static
setter callback for the ActiveObject attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setDependencyGraph()
int DocumentPy::staticCallback_setDependencyGraph (PyObject * self, PyObject * value, void * closure) static
setter callback for the DependencyGraph attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setHasPendingTransaction()
int DocumentPy::staticCallback_setHasPendingTransaction (PyObject * self, PyObject * value, void * closure) static
setter callback for the HasPendingTransaction attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setImporting()
int DocumentPy::staticCallback_setImporting (PyObject * self, PyObject * value, void * closure) static
setter callback for the Importing attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setInList()
int DocumentPy::staticCallback_setInList (PyObject * self, PyObject * value, void * closure) static
setter callback for the InList attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setName()
int DocumentPy::staticCallback_setName (PyObject * self, PyObject * value, void * closure) static
setter callback for the Name attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setObjects()
int DocumentPy::staticCallback_setObjects (PyObject * self, PyObject * value, void * closure) static
setter callback for the Objects attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setOldLabel()
int DocumentPy::staticCallback_setOldLabel (PyObject * self, PyObject * value, void * closure) static
setter callback for the OldLabel attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setOutList()
int DocumentPy::staticCallback_setOutList (PyObject * self, PyObject * value, void * closure) static
setter callback for the OutList attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setPartial()
int DocumentPy::staticCallback_setPartial (PyObject * self, PyObject * value, void * closure) static
setter callback for the Partial attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setRecomputesFrozen()
int DocumentPy::staticCallback_setRecomputesFrozen (PyObject * self, PyObject * value, void * closure) static
setter callback for the RecomputesFrozen attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setRecomputesFrozen().
staticCallback_setRecomputing()
int DocumentPy::staticCallback_setRecomputing (PyObject * self, PyObject * value, void * closure) static
setter callback for the Recomputing attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setRedoCount()
int DocumentPy::staticCallback_setRedoCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the RedoCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setRedoNames()
int DocumentPy::staticCallback_setRedoNames (PyObject * self, PyObject * value, void * closure) static
setter callback for the RedoNames attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setRestoring()
int DocumentPy::staticCallback_setRestoring (PyObject * self, PyObject * value, void * closure) static
setter callback for the Restoring attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setRootObjects()
int DocumentPy::staticCallback_setRootObjects (PyObject * self, PyObject * value, void * closure) static
setter callback for the RootObjects attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setTemporary()
int DocumentPy::staticCallback_setTemporary (PyObject * self, PyObject * value, void * closure) static
setter callback for the Temporary attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setTopologicalSortedObjects()
int DocumentPy::staticCallback_setTopologicalSortedObjects (PyObject * self, PyObject * value, void * closure) static
setter callback for the TopologicalSortedObjects attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setTransacting()
int DocumentPy::staticCallback_setTransacting (PyObject * self, PyObject * value, void * closure) static
setter callback for the Transacting attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setUndoCount()
int DocumentPy::staticCallback_setUndoCount (PyObject * self, PyObject * value, void * closure) static
setter callback for the UndoCount attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setUndoMode()
int DocumentPy::staticCallback_setUndoMode (PyObject * self, PyObject * value, void * closure) static
setter callback for the UndoMode attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setUndoMode().
staticCallback_setUndoNames()
int DocumentPy::staticCallback_setUndoNames (PyObject * self, PyObject * value, void * closure) static
setter callback for the UndoNames attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setUndoRedoMemSize()
int DocumentPy::staticCallback_setUndoRedoMemSize (PyObject * self, PyObject * value, void * closure) static
setter callback for the UndoRedoMemSize attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_supportedTypes()
PyObject * DocumentPy::staticCallback_supportedTypes (PyObject * self, PyObject * args) static
callback for the supportedTypes() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and supportedTypes().
staticCallback_undo()
PyObject * DocumentPy::staticCallback_undo (PyObject * self, PyObject * args) static
callback for the undo() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), Base::PyObjectBase::startNotify(), and undo().
supportedTypes()
PyObject * DocumentPy::supportedTypes (PyObject * args)
implementer for the supportedTypes() method
References Base::Type::getAllDerivedFrom(), and Base::Persistence::getClassTypeId().
Referenced by staticCallback_supportedTypes().
undo()
PyObject * DocumentPy::undo (PyObject * args)
implementer for the undo() method
References getDocumentPtr(), and App::Document::undo().
Referenced by staticCallback_undo().
Member Data Documentation
GetterSetter
PyGetSetDef DocumentPy::GetterSetter static
Attribute structure of DocumentPy.
Methods
PyMethodDef DocumentPy::Methods static
Methods structure of DocumentPy.
Type
PyTypeObject DocumentPy::Type static
Type structure of DocumentPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), draftobjects.layer.Layer::set_properties(), ArchReference.ArchReference::setProperties(), Gui::Application::sGetDocument(), and Gui::Application::sSetActiveDocument().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/App/DocumentPy.h
Sources/FreeCAD/src/App/DocumentPyImp.cpp
Sources/FreeCAD-SourceDocs/src/App/DocumentPy.cpp