FreeCAD: FemGui::TaskFemConstraintHeatflux Class Reference
FemGui::TaskFemConstraintHeatflux Class Reference
#include <TaskFemConstraintHeatflux.h>
Public Member Functions
std::string get_constraint_type (void) const
double getAmbientTemp (void) const
double getFilmCoef (void) const
virtual const std::string getReferences () const
TaskFemConstraintHeatflux (ViewProviderFemConstraintHeatflux *ConstraintView, QWidget *parent=0)
virtual ~TaskFemConstraintHeatflux ()
Public Member Functions inherited from FemGui::TaskFemConstraint
const std::string getReferences (const std::vector< std::string > &items) const
const std::string getScale () const
TaskFemConstraint (ViewProviderFemConstraint *ConstraintView, QWidget *parent=0, const char *pixmapname="")
virtual ~TaskFemConstraint ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
TaskBox (QWidget *parent=0)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=0)
Constructor.
ActionGroup (QWidget *parent=0)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockConnection (bool block)
void detachSelection ()
Detaches from the selection.
bool isConnectionAttached () const
bool isConnectionBlocked () const
SelectionObserver (bool attach=true, int resolve=1)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, int resolve=1)
Constructor.
virtual ~SelectionObserver ()
Protected Member Functions
virtual void changeEvent (QEvent *e)
bool event (QEvent *e)
Protected Member Functions inherited from FemGui::TaskFemConstraint
void createDeleteAction (QListWidget *parentList)
bool KeyEvent (QEvent *e)
virtual void keyPressEvent (QKeyEvent *ke)
const QString makeRefText (const App::DocumentObject *obj, const std::string &subName) const
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Types inherited from FemGui::TaskFemConstraint
enum { seldir , selref , selloc , selnone }
Protected Slots inherited from FemGui::TaskFemConstraint
void onButtonReference (const bool pressed=true)
void onButtonWizCancel ()
void onButtonWizOk ()
void onReferenceDeleted (const int row)
void setSelection (QListWidgetItem *item)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from FemGui::TaskFemConstraint
ViewProviderFemConstraint * ConstraintView
QAction * deleteAction
QWidget * proxy
enum FemGui::TaskFemConstraint:: { ... } selectionMode
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskFemConstraintHeatflux()
TaskFemConstraintHeatflux::TaskFemConstraintHeatflux (ViewProviderFemConstraintHeatflux * ConstraintView, QWidget * parent = 0)
References Fem::ConstraintHeatflux::AmbientTemp, draftgeoutils.intersections::connect(), Fem::ConstraintHeatflux::ConstraintType, FemGui::TaskFemConstraint::ConstraintView, FemGui::TaskFemConstraint::createDeleteAction(), FemGui::TaskFemConstraint::deleteAction, Fem::ConstraintHeatflux::DFlux, Fem::ConstraintHeatflux::FilmCoef, Gui::ViewProviderDocumentObject::getObject(), App::PropertyLinkSubList::getSubValues(), App::PropertyFloat::getValue(), App::PropertyEnumeration::getValueAsString(), App::PropertyLinkSubList::getValues(), QSint::ActionGroup::groupLayout(), Base::Unit::HeatFlux, FemGui::TaskFemConstraint::makeRefText(), FemGui::TaskFemConstraint::proxy, Fem::Constraint::References, FemGui::TaskFemConstraint::setSelection(), Base::Unit::Temperature, and Base::Unit::ThermalTransferCoefficient.
~TaskFemConstraintHeatflux()
TaskFemConstraintHeatflux::~TaskFemConstraintHeatflux () virtual
Member Function Documentation
changeEvent()
void TaskFemConstraintHeatflux::changeEvent (QEvent * e) protected virtual
Reimplemented from FemGui::TaskFemConstraint.
References FemGui::TaskFemConstraint::proxy.
event()
bool TaskFemConstraintHeatflux::event (QEvent * e) protected
References FemGui::TaskFemConstraint::KeyEvent().
Referenced by draftguitools.gui_edit.Edit::evaluate_menu_action().
get_constraint_type()
std::string TaskFemConstraintHeatflux::get_constraint_type (void) const
getAmbientTemp()
double TaskFemConstraintHeatflux::getAmbientTemp (void) const
References Base::Quantity::getValueAs(), and Base::Quantity::Kelvin.
Referenced by FemGui::TaskDlgFemConstraintHeatflux::accept().
getFilmCoef()
double TaskFemConstraintHeatflux::getFilmCoef (void) const
References Base::Quantity::getValueAs(), and Base::Unit::ThermalTransferCoefficient.
Referenced by FemGui::TaskDlgFemConstraintHeatflux::accept().
getReferences()
const std::string TaskFemConstraintHeatflux::getReferences (void) const virtual
Reimplemented from FemGui::TaskFemConstraint.
References FemGui::TaskFemConstraint::getReferences().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintHeatflux.h
Sources/FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintHeatflux.cpp