FreeCAD: Gui::NS::TiltState Class Reference
Gui::NS::TiltState Class Reference
Public Types
typedef sc::custom_reaction< NS::Event > reactions
Public Member Functions
sc::result react (const NS::Event &ev)
TiltState (my_context ctx)
virtual ~TiltState ()
Member Typedef Documentation
reactions
typedef sc::custom_reaction<NS::Event> Gui::NS::TiltState::reactions
Constructor & Destructor Documentation
TiltState()
Gui::NS::TiltState::TiltState (my_context ctx)
References Base::Console(), Gui::NavigationStyle::DRAGGING, and Base::ConsoleSingleton::Log().
~TiltState()
virtual Gui::NS::TiltState::~TiltState () virtual
Member Function Documentation
react()
sc::result Gui::NS::TiltState::react (const NS::Event & ev)
References Gui::NS::Event::flags, Gui::NS::Event::inventor_event, Gui::NS::Event::isLocation2Event(), Gui::NS::Event::isMouseButtonEvent(), and Gui::NS::Event::mbstate().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/GestureNavigationStyle.cpp