FreeCAD: Base::Tools Struct Reference
Base::Tools Struct Reference
#include <Tools.h>
Static Public Member Functions
static std::string addNumber (const std::string &, unsigned int, int d=0)
static std::string escapedUnicodeFromUtf8 (const char *s)
static std::string escapedUnicodeToUtf8 (const std::string &s)
static QString escapeEncodeFilename (const QString &s)
static std::string escapeEncodeFilename (const std::string &s)
static QString escapeEncodeString (const QString &s)
static std::string escapeEncodeString (const std::string &s)
static QString fromStdString (const std::string &s)
fromStdString Convert a std::string encoded as UTF-8 into a QString.
static std::string getIdentifier (const std::string &)
static std::string getUniqueName (const std::string &, const std::vector< std::string > &, int d=0)
static std::string narrow (const std::wstring &str)
static std::string toStdString (const QString &s)
toStdString Convert a QString into a UTF-8 encoded std::string.
static std::wstring widen (const std::string &str)
Member Function Documentation
addNumber()
std::string Base::Tools::addNumber (const std::string & name, unsigned int num, int d = 0) static
escapedUnicodeFromUtf8()
std::string Base::Tools::escapedUnicodeFromUtf8 (const char * s) static
Referenced by PartGui::Mirroring::accept(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), SpreadsheetGui::PropertiesDialog::apply(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), Gui::Application::exportTo(), Gui::ExpressionBinding::getEscapedExpressionString(), App::SubObjectT::getSubObjectPython(), Gui::Application::importFrom(), Gui::Dialog::DlgPropertyLink::linksToPython(), StartGui::Workbench::loadStartPage(), SketcherGui::TaskSketcherConstrains::on_listWidgetConstraints_itemChanged(), TechDraw::DrawViewSymbol::onChanged(), Gui::Application::open(), App::Application::processFiles(), Gui::Document::saveAs(), MeshCore::MeshOutput::SaveOBJ(), Gui::PropertyEditor::PropertyEnumItem::setValue(), Gui::PropertyEditor::PropertyStringListItem::setValue(), SketcherGui::ConstraintView::swapNamedOfSelectedItems(), and App::ObjectIdentifier::toEscapedString().
escapedUnicodeToUtf8()
std::string Base::Tools::escapedUnicodeToUtf8 (const std::string & s) static
Referenced by TechDrawGui::QGIViewAnnotation::drawAnnotation(), TechDraw::DrawViewSymbol::execute(), MeshCore::MeshInput::LoadMTL(), MeshCore::MeshInput::LoadOBJ(), and Gui::PropertyEditor::PropertyStringListItem::value().
escapeEncodeFilename() [1/2]
QString Base::Tools::escapeEncodeFilename (const QString & s) static
Referenced by TechDrawGui::TaskActiveView::createActiveView(), Gui::Application::exportTo(), Gui::Application::importFrom(), WebGui::BrowserView::onLinkClicked(), Gui::Application::open(), App::Application::processCmdLineFiles(), App::Application::processFiles(), Gui::Document::saveAs(), Gui::Document::saveCopy(), and TechDrawGui::MDIViewPage::saveDXF().
escapeEncodeFilename() [2/2]
std::string Base::Tools::escapeEncodeFilename (const std::string & s) static
escapeEncodeString() [1/2]
QString Base::Tools::escapeEncodeString (const QString & s) static
Referenced by TechDrawGui::TaskWeldingSymbol::createWeldingSymbol(), TechDrawGui::TaskWeldingSymbol::updateTiles(), and TechDrawGui::TaskWeldingSymbol::updateWeldingSymbol().
escapeEncodeString() [2/2]
std::string Base::Tools::escapeEncodeString (const std::string & s) static
fromStdString()
static QString Base::Tools::fromStdString (const std::string & s) static
fromStdString Convert a std::string encoded as UTF-8 into a QString.
Parameters
s std::string, expected to be UTF-8 encoded.
Returns
String represented as a QString.
Referenced by StdCmdDelete::activated(), SpreadsheetGui::SheetModel::data(), ConstraintItem::data(), Gui::Dialog::DlgExpressionInput::DlgExpressionInput(), TechDrawGui::QGIWeldSymbol::drawTailText(), Gui::QuantitySpinBox::event(), SketcherGui::EditDatumDialog::exec(), TechDraw::DrawSVGTemplate::execute(), TechDrawGui::TaskSectionView::failNoObject(), TechDraw::DrawViewDimension::getDefaultFormatSpec(), MRichTextEdit::getDefFont(), Spreadsheet::Cell::getFormattedQuantity(), TechDrawGui::TaskLineDecor::initUi(), Gui::QuantitySpinBox::onChange(), Gui::UIntSpinBox::onChange(), SpreadsheetGui::PropertiesDialog::PropertiesDialog(), Gui::QuantitySpinBox::resizeEvent(), Gui::UIntSpinBox::resizeEvent(), Gui::IntSpinBox::resizeEvent(), Gui::DoubleSpinBox::resizeEvent(), Gui::ExpLineEdit::resizeEvent(), TechDrawGui::QGITile::setFont(), TechDrawGui::TaskSectionView::setUiEdit(), TechDrawGui::TaskCenterLine::setUiEdit(), TechDrawGui::TaskLeaderLine::setUiEdit(), TechDrawGui::TaskRichAnno::setUiEdit(), TechDrawGui::TaskDetail::setUiFromFeat(), TechDrawGui::TaskSectionView::setUiPrimary(), TechDrawGui::TaskCenterLine::setUiPrimary(), TechDrawGui::TaskCosVertex::setUiPrimary(), TechDrawGui::TaskLeaderLine::setUiPrimary(), TechDrawGui::TaskRichAnno::setUiPrimary(), SpreadsheetGui::SheetModel::SheetModel(), Gui::ExpressionCompleter::slotUpdate(), and FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary().
getIdentifier()
std::string Base::Tools::getIdentifier (const std::string & name) static
Referenced by Gui::Dialog::DlgAddProperty::accept(), App::Document::addObjects(), App::Application::getUniqueDocumentName(), and App::Document::getUniqueObjectName().
getUniqueName()
std::string Base::Tools::getUniqueName (const std::string & name, const std::vector< std::string > & names, int d = 0) static
References Base::string_comp::increment().
Referenced by App::Document::addObjects(), App::Document::getStandardObjectName(), App::Application::getUniqueDocumentName(), Base::Writer::getUniqueFileName(), App::Document::getUniqueObjectName(), App::Application::newDocument(), and App::PropertyString::setValue().
narrow()
std::string Base::Tools::narrow (const std::wstring & str) static
toStdString()
static std::string Base::Tools::toStdString (const QString & s) static
toStdString Convert a QString into a UTF-8 encoded std::string.
Parameters
s String to convert.
Returns
A std::string encoded as UTF-8.
Referenced by CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), SpreadsheetGui::SheetView::aliasChanged(), TechDrawGui::TaskSectionView::apply(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), TechDrawGui::TaskActiveView::createActiveView(), SpreadsheetGui::SheetView::editingFinished(), TechDraw::DrawSVGTemplate::execute(), TechDraw::DrawViewDimension::formatValue(), FemGui::TaskFemConstraintFluidBoundary::getBoundaryType(), TechDraw::DrawViewDimension::getDefaultFormatSpec(), Spreadsheet::Cell::getFormattedQuantity(), FemGui::TaskFemConstraintFluidBoundary::getSubtype(), FemGui::TaskFemConstraintFluidBoundary::getThermalBoundaryType(), FemGui::TaskFemConstraintFluidBoundary::getTurbulenceSpecification(), SketcherGui::TaskSketcherConstrains::on_listWidgetConstraints_itemChanged(), Spreadsheet::Sheet::recomputeCell(), Gui::ExpressionCompleter::slotUpdate(), TechDrawGui::TaskSectionView::TaskSectionView(), TechDrawGui::TaskDetail::updateDetail(), and TechDrawGui::TaskSectionView::updateSectionView().
widen()
std::wstring Base::Tools::widen (const std::string & str) static
The documentation for this struct was generated from the following files:
Sources/FreeCAD/src/Base/Tools.h
Sources/FreeCAD/src/Base/Tools.cpp