FreeCAD: GCS::ConstraintEqual Class Reference
GCS::ConstraintEqual Class Reference
#include <Constraints.h>
Public Member Functions
ConstraintEqual (double *p1, double *p2, double p1p2ratio=1.0)
virtual double error ()
virtual ConstraintType getTypeId ()
virtual double grad (double *)
virtual void rescale (double coef=1.)
Public Member Functions inherited from GCS::Constraint
Constraint ()
virtual double error ()
int findParamInPvec (double *param)
int getTag ()
virtual ConstraintType getTypeId ()
virtual double grad (double *)
bool isDriving () const
virtual double maxStep (MAP_pD_D &dir, double lim=1.)
VEC_pD params ()
void redirectParams (MAP_pD_pD redirectionmap)
virtual void rescale (double coef=1.)
void revertParams ()
void setDriving (bool isdriving)
void setTag (int tagId)
virtual ~Constraint ()
Constructor & Destructor Documentation
ConstraintEqual()
GCS::ConstraintEqual::ConstraintEqual (double * p1, double * p2, double p1p2ratio = 1.0)
References rescale().
Member Function Documentation
error()
double GCS::ConstraintEqual::error () virtual
Reimplemented from GCS::Constraint.
Referenced by femmesh.gmshtools.GmshTools::read_and_set_new_mesh(), FreeCADInit.FCADLogger::report(), and femmesh.gmshtools.GmshTools::run_gmsh_with_geo().
getTypeId()
ConstraintType GCS::ConstraintEqual::getTypeId (void) virtual
Reimplemented from GCS::Constraint.
References GCS::Equal.
grad()
double GCS::ConstraintEqual::grad (double * param) virtual
Reimplemented from GCS::Constraint.
rescale()
void GCS::ConstraintEqual::rescale (double coef = 1.) virtual
Reimplemented from GCS::Constraint.
Referenced by ConstraintEqual().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Sketcher/App/planegcs/Constraints.h
FreeCAD/src/Mod/Sketcher/App/planegcs/Constraints.cpp