FreeCAD: FemGui::TaskFemConstraintTransform Class Reference
FemGui::TaskFemConstraintTransform Class Reference
#include <TaskFemConstraintTransform.h>
Public Member Functions
std::string get_transform_type (void) const
double get_X_rot () const
double get_Y_rot () const
double get_Z_rot () const
const std::string getReferences () const
TaskFemConstraintTransform (ViewProviderFemConstraintTransform *ConstraintView, QWidget *parent=nullptr)
~TaskFemConstraintTransform ()
Public Member Functions inherited from FemGui::TaskFemConstraint
const std::string getReferences (const std::vector< std::string > &items) const
virtual const std::string getReferences (void) const
const std::string getScale () const
TaskFemConstraint (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="")
virtual ~TaskFemConstraint ()
Public Member Functions inherited from Gui::TaskView::TaskBox
void hideGroupBox ()
bool isGroupVisible () const
virtual QSize minimumSizeHint () const
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
TaskBox (QWidget *parent=nullptr)
Constructor.
~TaskBox ()
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
Constructor.
ActionGroup (QWidget *parent=nullptr)
Constructor.
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
Creates action item from the action and returns it.
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
Adds label to the group.
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
Adds widget to the group.
QBoxLayout * groupLayout ()
Returns group's layout (QVBoxLayout by default).
bool hasHeader () const
Returns true if the group has header.
QString headerText () const
Returns text of the header.
bool isExpandable () const
Returns true if the group is expandable.
QSize minimumSizeHint () const
void setScheme (ActionPanelScheme *pointer)
Sets the scheme of the panel and all the child groups to scheme.
Public Member Functions inherited from Gui::SelectionObserver
void attachSelection ()
Attaches to the selection.
bool blockSelection (bool block)
void detachSelection ()
Detaches from the selection.
bool isSelectionAttached () const
bool isSelectionBlocked () const
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
virtual ~SelectionObserver ()
Static Public Member Functions
static std::string getSurfaceReferences (const std::string showConstr)
Protected Member Functions
void changeEvent (QEvent *e)
bool event (QEvent *e)
const QString makeText (const App::DocumentObject *obj) const
Protected Member Functions inherited from FemGui::TaskFemConstraint
virtual void changeEvent (QEvent *e)
void createDeleteAction (QListWidget *parentList)
bool KeyEvent (QEvent *e)
virtual void keyPressEvent (QKeyEvent *ke)
const QString makeRefText (const App::DocumentObject *obj, const std::string &subName) const
const QString makeRefText (const std::string &objName, const std::string &subName) const
virtual void onSelectionChanged (const Gui::SelectionChanges &)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void actionEvent (QActionEvent *)
void showEvent (QShowEvent *)
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
virtual void paintEvent (QPaintEvent *event)
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void setExpandable (bool expandable=true)
Makes the group expandable if expandable is set to true.
void setHeader (bool enable=true)
Enables/disables group's header according to enable.
void setHeaderText (const QString &title)
Sets text of the header to title.
void showHide ()
Expands/collapses the group.
Protected Types inherited from FemGui::TaskFemConstraint
enum { seldir , selref , selloc , selnone }
Protected Slots inherited from FemGui::TaskFemConstraint
void onButtonReference (const bool pressed=true)
void onButtonWizCancel ()
void onButtonWizOk ()
void onReferenceDeleted (const int row)
void setSelection (QListWidgetItem *item)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from FemGui::TaskFemConstraint
Gui::WeakPtrT< ViewProviderFemConstraint > ConstraintView
QAction * deleteAction
QWidget * proxy
enum FemGui::TaskFemConstraint:: { ... } selectionMode
Protected Attributes inherited from QSint::ActionGroup
double m_foldDelta
int m_foldDirection
QPixmap m_foldPixmap
double m_foldStep
double m_fullHeight
double m_tempHeight
QWidget * myDummy
class TaskGroup * myGroup
class TaskHeader * myHeader
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Constructor & Destructor Documentation
TaskFemConstraintTransform()
TaskFemConstraintTransform::TaskFemConstraintTransform (ViewProviderFemConstraintTransform * ConstraintView, QWidget * parent = nullptr)
References Ui_TaskFemConstraintTransform::btnAdd, Ui_TaskFemConstraintTransform::btnRemove, draftgeoutils.intersections::connect(), FemGui::TaskFemConstraint::ConstraintView, FemGui::TaskFemConstraint::createDeleteAction(), FemGui::TaskFemConstraint::deleteAction, Gui::Command::Doc, App::PropertyLinkSubList::getSubValues(), getSurfaceReferences(), App::PropertyFloat::getValue(), App::PropertyEnumeration::getValueAsString(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyLinkSubList::getValues(), QSint::ActionGroup::groupLayout(), Ui_TaskFemConstraintTransform::lw_dis_cylin, Ui_TaskFemConstraintTransform::lw_dis_rect, Ui_TaskFemConstraintTransform::lw_displobj_cylin, Ui_TaskFemConstraintTransform::lw_displobj_rect, Ui_TaskFemConstraintTransform::lw_Rect, FemGui::TaskFemConstraint::makeRefText(), makeText(), Fem::ConstraintTransform::NameDispl, FemGui::TaskFemConstraint::proxy, Ui_TaskFemConstraintTransform::rb_cylin, Ui_TaskFemConstraintTransform::rb_rect, Fem::ConstraintTransform::RefDispl, Fem::Constraint::References, FemGui::TaskFemConstraint::setSelection(), Ui_TaskFemConstraintTransform::setupUi(), Ui_TaskFemConstraintTransform::sp_X, Ui_TaskFemConstraintTransform::sp_Y, Ui_TaskFemConstraintTransform::sp_Z, Ui_TaskFemConstraintTransform::sw_transform, Fem::ConstraintTransform::TransformType, Fem::ConstraintTransform::X_rot, Fem::ConstraintTransform::Y_rot, and Fem::ConstraintTransform::Z_rot.
~TaskFemConstraintTransform()
TaskFemConstraintTransform::~TaskFemConstraintTransform ()
Member Function Documentation
changeEvent()
void TaskFemConstraintTransform::changeEvent (QEvent * e) protected virtual
Reimplemented from FemGui::TaskFemConstraint.
event()
bool TaskFemConstraintTransform::event (QEvent * e) protected
References FemGui::TaskFemConstraint::KeyEvent().
get_transform_type()
std::string TaskFemConstraintTransform::get_transform_type (void) const
References Ui_TaskFemConstraintTransform::rb_cylin, and Ui_TaskFemConstraintTransform::rb_rect.
Referenced by FemGui::TaskDlgFemConstraintTransform::accept().
get_X_rot()
double TaskFemConstraintTransform::get_X_rot () const
References Ui_TaskFemConstraintTransform::sp_X.
Referenced by FemGui::TaskDlgFemConstraintTransform::accept().
get_Y_rot()
double TaskFemConstraintTransform::get_Y_rot () const
References Ui_TaskFemConstraintTransform::sp_Y.
Referenced by FemGui::TaskDlgFemConstraintTransform::accept().
get_Z_rot()
double TaskFemConstraintTransform::get_Z_rot () const
References Ui_TaskFemConstraintTransform::sp_Z.
Referenced by FemGui::TaskDlgFemConstraintTransform::accept().
getReferences()
const std::string TaskFemConstraintTransform::getReferences (void) const virtual
Reimplemented from FemGui::TaskFemConstraint.
References FemGui::TaskFemConstraint::getReferences(), and Ui_TaskFemConstraintTransform::lw_Rect.
getSurfaceReferences()
std::string TaskFemConstraintTransform::getSurfaceReferences (const std::string showConstr = "") static
Referenced by TaskFemConstraintTransform().
makeText()
const QString TaskFemConstraintTransform::makeText (const App::DocumentObject * obj) const protected
Referenced by TaskFemConstraintTransform().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintTransform.h
FreeCAD/src/Mod/Fem/Gui/TaskFemConstraintTransform.cpp