FreeCAD: MED::TGaussCoord Class Reference
MED::TGaussCoord Class Reference
Define a helper class to handle Gauss Points coordinates.
#include <MED_GaussUtils.hxx>
Public Member Functions
TCoordSliceArr GetCoordSliceArr (TInt theElemId)
Get slice of the coordinate that corresponds to defined cell.
TCCoordSliceArr GetCoordSliceArr (TInt theElemId) const
Get slice of the coordinate that corresponds to defined cell (const version)
TInt GetDim () const
TInt GetNbElem () const
TInt GetNbGauss () const
unsigned char * GetValuePtr ()
void Init (TInt theNbElem, TInt theNbGauss, TInt theDim, EModeSwitch theMode=eFULL_INTERLACE)
To init the class.
TGaussCoord ()
Detailed Description
Define a helper class to handle Gauss Points coordinates.
Constructor & Destructor Documentation
TGaussCoord()
MED::TGaussCoord::TGaussCoord ()
Member Function Documentation
GetCoordSliceArr() [1/2]
TCoordSliceArr MED::TGaussCoord::GetCoordSliceArr (TInt theElemId)
Get slice of the coordinate that corresponds to defined cell.
References MED::eFULL_INTERLACE, and MED::TModeSwitchInfo::GetModeSwitch().
GetCoordSliceArr() [2/2]
TCCoordSliceArr MED::TGaussCoord::GetCoordSliceArr (TInt theElemId) const
Get slice of the coordinate that corresponds to defined cell (const version)
References MED::eFULL_INTERLACE, and MED::TModeSwitchInfo::GetModeSwitch().
Referenced by MED::TShapeFun::Eval(), and MED::GetBaryCenter().
GetDim()
TInt MED::TGaussCoord::GetDim () const
GetNbElem()
TInt MED::TGaussCoord::GetNbElem () const
GetNbGauss()
TInt MED::TGaussCoord::GetNbGauss () const
GetValuePtr()
unsigned char * MED::TGaussCoord::GetValuePtr ()
Init()
void MED::TGaussCoord::Init (TInt theNbElem, TInt theNbGauss, TInt theDim, EModeSwitch theMode = eFULL_INTERLACE)
To init the class.
References MED::TModeSwitchInfo::myModeSwitch.
Referenced by MED::TShapeFun::Eval(), and MED::GetBaryCenter().
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/MED_GaussUtils.hxx
FreeCAD/src/3rdParty/salomesmesh/src/SMESH/MED_GaussUtils.cpp