FreeCAD: SMDS_SpacePosition Class Reference
SMDS_SpacePosition Class Reference
#include <SMDS_SpacePosition.hxx>
Public Member Functions
virtual SMDS_TypeOfPosition GetTypeOfPosition () const
SMDS_SpacePosition (double x=0, double y=0, double z=0)
Public Member Functions inherited from SMDS_Position
virtual int GetDim () const
virtual ~SMDS_Position ()
Static Public Member Functions
static SMDS_PositionPtr originSpacePosition ()
Additional Inherited Members
Protected Member Functions inherited from SMDS_Position
SMDS_Position ()
Constructor & Destructor Documentation
SMDS_SpacePosition()
SMDS_SpacePosition::SMDS_SpacePosition (double x = 0, double y = 0, double z = 0)
Member Function Documentation
GetTypeOfPosition()
SMDS_TypeOfPosition SMDS_SpacePosition::GetTypeOfPosition () const virtual
Implements SMDS_Position.
originSpacePosition()
SMDS_PositionPtr SMDS_SpacePosition::originSpacePosition () static
Referenced by SMDS_Mesh::Clear(), SMDS_Mesh::RemoveElement(), SMDS_Mesh::RemoveFreeElement(), SMESHDS_Mesh::SetNodeInVolume(), SMDS_MeshNode::SetPosition(), SMESH_MeshEditor::Transform(), SMDS_Mesh::~SMDS_Mesh(), and SMDS_MeshNode::~SMDS_MeshNode().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/SMDS_SpacePosition.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMDS/SMDS_SpacePosition.cpp