FreeCAD: Gui::Dialog::Clipping Class Reference
Gui::Dialog::Clipping Class Reference
#include <Clipping.h>
Classes
class Private
Public Member Functions
Clipping (Gui::View3DInventor *view, QWidget *parent=nullptr)
void reject ()
~Clipping ()
Destroys the object and frees any allocated resources.
Static Public Member Functions
static Clipping * makeDockWidget (Gui::View3DInventor *)
Protected Slots
void on_adjustViewdirection_toggled (bool)
void on_clipView_valueChanged (double)
void on_clipX_valueChanged (double)
void on_clipY_valueChanged (double)
void on_clipZ_valueChanged (double)
void on_dirX_valueChanged (double)
void on_dirY_valueChanged (double)
void on_dirZ_valueChanged (double)
void on_flipClipX_clicked ()
void on_flipClipY_clicked ()
void on_flipClipZ_clicked ()
void on_fromView_clicked ()
void on_groupBoxView_toggled (bool)
void on_groupBoxX_toggled (bool)
void on_groupBoxY_toggled (bool)
void on_groupBoxZ_toggled (bool)
Detailed Description
Author
Werner Mayer
Constructor & Destructor Documentation
Clipping()
Clipping::Clipping (Gui::View3DInventor * view, QWidget * parent = nullptr)
References Gui::Dialog::Clipping::Private::clipView, Gui::Dialog::Clipping::Private::clipX, Gui::Dialog::Clipping::Private::clipY, Gui::Dialog::Clipping::Private::clipZ, Gui::Dialog::Clipping::Private::node, Gui::Dialog::Clipping::Private::ui, Gui::Dialog::Clipping::Private::view, and OfflineRenderingUtils::viewer().
Referenced by makeDockWidget().
~Clipping()
Clipping::~Clipping ()
Destroys the object and frees any allocated resources.
References Gui::Dialog::Clipping::Private::clipView, Gui::Dialog::Clipping::Private::clipX, Gui::Dialog::Clipping::Private::clipY, Gui::Dialog::Clipping::Private::clipZ, and Gui::Dialog::Clipping::Private::node.
Member Function Documentation
makeDockWidget()
Clipping * Clipping::makeDockWidget (Gui::View3DInventor * view) static
References Gui::DockWindowManager::addDockWindow(), Clipping(), and Gui::DockWindowManager::instance().
Referenced by StdCmdToggleClipPlane::activated().
on_adjustViewdirection_toggled
void Clipping::on_adjustViewdirection_toggled (bool on) protected slot
References Gui::Dialog::Clipping::Private::sensor, and Gui::Dialog::Clipping::Private::ui.
on_clipView_valueChanged
void Clipping::on_clipView_valueChanged (double val) protected slot
References Gui::Dialog::Clipping::Private::clipView.
on_clipX_valueChanged
void Clipping::on_clipX_valueChanged (double val) protected slot
References Gui::Dialog::Clipping::Private::clipX, and Gui::Dialog::Clipping::Private::flipX.
on_clipY_valueChanged
void Clipping::on_clipY_valueChanged (double val) protected slot
References Gui::Dialog::Clipping::Private::clipY, and Gui::Dialog::Clipping::Private::flipY.
on_clipZ_valueChanged
void Clipping::on_clipZ_valueChanged (double val) protected slot
References Gui::Dialog::Clipping::Private::clipZ, and Gui::Dialog::Clipping::Private::flipZ.
on_dirX_valueChanged
void Clipping::on_dirX_valueChanged (double) protected slot
References Gui::Dialog::Clipping::Private::clipView, and Gui::Dialog::Clipping::Private::ui.
on_dirY_valueChanged
void Clipping::on_dirY_valueChanged (double) protected slot
References Gui::Dialog::Clipping::Private::clipView, and Gui::Dialog::Clipping::Private::ui.
on_dirZ_valueChanged
void Clipping::on_dirZ_valueChanged (double) protected slot
References Gui::Dialog::Clipping::Private::clipView, and Gui::Dialog::Clipping::Private::ui.
on_flipClipX_clicked
void Clipping::on_flipClipX_clicked () protected slot
References Gui::Dialog::Clipping::Private::clipX, and Gui::Dialog::Clipping::Private::flipX.
on_flipClipY_clicked
void Clipping::on_flipClipY_clicked () protected slot
References Gui::Dialog::Clipping::Private::clipY, and Gui::Dialog::Clipping::Private::flipY.
on_flipClipZ_clicked
void Clipping::on_flipClipZ_clicked () protected slot
References Gui::Dialog::Clipping::Private::clipZ, and Gui::Dialog::Clipping::Private::flipZ.
on_fromView_clicked
void Clipping::on_fromView_clicked () protected slot
References Gui::Dialog::Clipping::Private::clipView, and Gui::Dialog::Clipping::Private::view.
on_groupBoxView_toggled
void Clipping::on_groupBoxView_toggled (bool on) protected slot
References Gui::Dialog::Clipping::Private::clipView, and Gui::Dialog::Clipping::Private::ui.
on_groupBoxX_toggled
void Clipping::on_groupBoxX_toggled (bool on) protected slot
References Gui::Dialog::Clipping::Private::clipX, and Gui::Dialog::Clipping::Private::ui.
on_groupBoxY_toggled
void Clipping::on_groupBoxY_toggled (bool on) protected slot
References Gui::Dialog::Clipping::Private::clipY, and Gui::Dialog::Clipping::Private::ui.
on_groupBoxZ_toggled
void Clipping::on_groupBoxZ_toggled (bool on) protected slot
References Gui::Dialog::Clipping::Private::clipZ, and Gui::Dialog::Clipping::Private::ui.
reject()
void Clipping::reject ()
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/Clipping.h
Sources/FreeCAD/src/Gui/Clipping.cpp