FreeCAD: TechDraw::CosmeticExtensionPy Class Reference
TechDraw::CosmeticExtensionPy Class Reference
The python export class for CosmeticExtension.
#include <CosmeticExtensionPy.h>
Public Types
typedef CosmeticExtension * PointerType
Public Types inherited from App::DocumentObjectExtensionPy
typedef DocumentObjectExtension * PointerType
Public Types inherited from App::ExtensionPy
typedef Extension * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
CosmeticExtensionPy (CosmeticExtension *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
callbacks and implementers for the python object attributes
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
CosmeticExtension * getCosmeticExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from App::DocumentObjectExtensionPy
DocumentObjectExtensionPy (DocumentObjectExtension *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
DocumentObjectExtension * getDocumentObjectExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from App::ExtensionPy
ExtensionPy (Extension *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Extension * getExtensionPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::DocumentObjectExtensionPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from App::ExtensionPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of CosmeticExtensionPy.
static PyMethodDef Methods []
Methods structure of CosmeticExtensionPy.
static PyTypeObject Type
Type structure of CosmeticExtensionPy.
Static Public Attributes inherited from App::DocumentObjectExtensionPy
static PyGetSetDef GetterSetter []
Attribute structure of DocumentObjectExtensionPy.
static PyMethodDef Methods []
Methods structure of DocumentObjectExtensionPy.
static PyTypeObject Type
Type structure of DocumentObjectExtensionPy.
Static Public Attributes inherited from App::ExtensionPy
static PyGetSetDef GetterSetter []
Attribute structure of ExtensionPy.
static PyMethodDef Methods []
Methods structure of ExtensionPy.
static PyTypeObject Type
Type structure of ExtensionPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~CosmeticExtensionPy ()
Protected Member Functions inherited from App::DocumentObjectExtensionPy
~DocumentObjectExtensionPy ()
Protected Member Functions inherited from App::ExtensionPy
~ExtensionPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for CosmeticExtension.
Member Typedef Documentation
PointerType
typedef CosmeticExtension* TechDraw::CosmeticExtensionPy::PointerType
Constructor & Destructor Documentation
~CosmeticExtensionPy()
CosmeticExtensionPy::~CosmeticExtensionPy () protected
CosmeticExtensionPy()
CosmeticExtensionPy::CosmeticExtensionPy (CosmeticExtension * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
getCosmeticExtensionPtr()
CosmeticExtension * CosmeticExtensionPy::getCosmeticExtensionPtr (void) const
getter for the object handled by this class
getCustomAttributes()
PyObject * CosmeticExtensionPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
GetType()
virtual PyTypeObject* TechDraw::CosmeticExtensionPy::GetType (void) virtual
Reimplemented from App::DocumentObjectExtensionPy.
PyInit()
int CosmeticExtensionPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from App::DocumentObjectExtensionPy.
PyMake()
PyObject * CosmeticExtensionPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string CosmeticExtensionPy::representation (void) const
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int CosmeticExtensionPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
Member Data Documentation
GetterSetter
PyGetSetDef CosmeticExtensionPy::GetterSetter static
Initial value:
= {
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of CosmeticExtensionPy.
Methods
PyMethodDef CosmeticExtensionPy::Methods static
Initial value:
= {
    {NULL, NULL, 0, NULL}
}
Methods structure of CosmeticExtensionPy.
Type
PyTypeObject CosmeticExtensionPy::Type static
Type structure of CosmeticExtensionPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), and ArchSchedule.CommandArchSchedule::IsActive().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/TechDraw/App/CosmeticExtensionPy.h
Sources/FreeCAD/src/Mod/TechDraw/App/CosmeticExtensionPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/TechDraw/App/CosmeticExtensionPy.cpp