FreeCAD: TechDraw::CosmeticVertexPy Class Reference
TechDraw::CosmeticVertexPy Class Reference
The python export class for CosmeticVertex.
#include <CosmeticVertexPy.h>
Public Types
typedef CosmeticVertex * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0 , Immutable = 1 , Notify = 2 , NoTrack = 3 }
Public Member Functions
CosmeticVertexPy (CosmeticVertex *pcObject, PyTypeObject *T=&Type)
virtual PyTypeObject * GetType (void)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of CosmeticVertexPy.
static PyMethodDef Methods []
Methods structure of CosmeticVertexPy.
static PyTypeObject Type
Type structure of CosmeticVertexPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~CosmeticVertexPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * clone (PyObject *args)
implementer for the clone() method
PyObject * copy (PyObject *args)
implementer for the copy() method
static PyObject * staticCallback_clone (PyObject *self, PyObject *args)
callback for the clone() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
callbacks and implementers for the python object attributes
Py::String getTag (void) const
getter for the Tag attribute
Py::Object getPoint (void) const
getter for the Point attribute
void setPoint (Py::Object arg)
setter for the Point attribute
Py::Boolean getShow (void) const
getter for the Show attribute
void setShow (Py::Boolean arg)
setter for the Show attribute
Py::Object getColor (void) const
getter for the Color attribute
void setColor (Py::Object arg)
setter for the Color attribute
Py::Object getSize (void) const
getter for the Size attribute
void setSize (Py::Object arg)
setter for the Size attribute
Py::Object getStyle (void) const
getter for the Style attribute
void setStyle (Py::Object arg)
setter for the Style attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
CosmeticVertex * getCosmeticVertexPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
static PyObject * staticCallback_getPoint (PyObject *self, void *closure)
getter callback for the Point attribute
static int staticCallback_setPoint (PyObject *self, PyObject *value, void *closure)
setter callback for the Point attribute
static PyObject * staticCallback_getShow (PyObject *self, void *closure)
getter callback for the Show attribute
static int staticCallback_setShow (PyObject *self, PyObject *value, void *closure)
setter callback for the Show attribute
static PyObject * staticCallback_getColor (PyObject *self, void *closure)
getter callback for the Color attribute
static int staticCallback_setColor (PyObject *self, PyObject *value, void *closure)
setter callback for the Color attribute
static PyObject * staticCallback_getSize (PyObject *self, void *closure)
getter callback for the Size attribute
static int staticCallback_setSize (PyObject *self, PyObject *value, void *closure)
setter callback for the Size attribute
static PyObject * staticCallback_getStyle (PyObject *self, void *closure)
getter callback for the Style attribute
static int staticCallback_setStyle (PyObject *self, PyObject *value, void *closure)
setter callback for the Style attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for CosmeticVertex.
Member Typedef Documentation
PointerType
typedef CosmeticVertex* TechDraw::CosmeticVertexPy::PointerType
Constructor & Destructor Documentation
~CosmeticVertexPy()
CosmeticVertexPy::~CosmeticVertexPy () protected
CosmeticVertexPy()
CosmeticVertexPy::CosmeticVertexPy (CosmeticVertex * pcObject, PyTypeObject * T = &Type)
Member Function Documentation
clone()
PyObject * CosmeticVertexPy::clone (PyObject * args)
implementer for the clone() method
References TechDraw::CosmeticVertex::clone(), getCosmeticVertexPtr(), and GetType().
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchComponent.Component::execute(), ArchCurtainWall.CurtainWall::execute(), ArchTruss.Truss::execute(), Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated(), staticCallback_clone(), and PathTests.TestPathHelix.TestPathHelix::test04().
copy()
PyObject * CosmeticVertexPy::copy (PyObject * args)
implementer for the copy() method
References TechDraw::CosmeticVertex::copy(), getCosmeticVertexPtr(), and GetType().
Referenced by staticCallback_copy().
getColor()
Py::Object CosmeticVertexPy::getColor (void) const
getter for the Color attribute
References TechDraw::CosmeticVertex::color, TechDraw::DrawUtil::colorToPyTuple(), and getCosmeticVertexPtr().
Referenced by staticCallback_getColor().
getCosmeticVertexPtr()
CosmeticVertex * CosmeticVertexPy::getCosmeticVertexPtr (void) const
getter for the object handled by this class
Referenced by clone(), copy(), getColor(), getPoint(), getShow(), getSize(), getStyle(), getTag(), TechDraw::DrawViewPartPy::removeCosmeticVertex(), setColor(), setPoint(), TechDraw::PropertyCosmeticVertexList::setPyObject(), setShow(), setSize(), and setStyle().
getCustomAttributes()
PyObject * CosmeticVertexPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getPoint()
Py::Object CosmeticVertexPy::getPoint (void) const
getter for the Point attribute
References getCosmeticVertexPtr(), TechDraw::DrawUtil::invertY(), and TechDraw::CosmeticVertex::permaPoint.
Referenced by PathScripts.PathOpGui.TaskPanelBaseLocationPage::addLocation(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::addNewTag(), PathScripts.PathOpGui.TaskPanelBaseLocationPage::editLocation(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::editTag(), draftguitools.gui_arcs.Arc_3Points::getPoint(), ArchCurtainWall.CommandArchCurtainWall::getPoint(), ArchTruss.CommandArchTruss::getPoint(), PathScripts.PathDressupTagGui.PathDressupTagTaskPanel::modifyStandardButtons(), PathScripts.PathOpGui.TaskPanelBaseLocationPage::modifyStandardButtons(), and staticCallback_getPoint().
getShow()
Py::Boolean CosmeticVertexPy::getShow (void) const
getter for the Show attribute
References getCosmeticVertexPtr(), and TechDraw::CosmeticVertex::visible.
Referenced by staticCallback_getShow().
getSize()
Py::Object CosmeticVertexPy::getSize (void) const
getter for the Size attribute
References getCosmeticVertexPtr(), and TechDraw::CosmeticVertex::size.
Referenced by staticCallback_getSize().
getStyle()
Py::Object CosmeticVertexPy::getStyle (void) const
getter for the Style attribute
References getCosmeticVertexPtr(), and TechDraw::CosmeticVertex::style.
Referenced by staticCallback_getStyle().
getTag()
Py::String CosmeticVertexPy::getTag (void) const
getter for the Tag attribute
References getCosmeticVertexPtr().
Referenced by staticCallback_getTag().
GetType()
virtual PyTypeObject* TechDraw::CosmeticVertexPy::GetType (void) virtual
Reimplemented from Base::PyObjectBase.
Referenced by clone(), and copy().
PyInit()
int CosmeticVertexPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Base::PyObjectBase.
PyMake()
PyObject * CosmeticVertexPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
representation()
std::string CosmeticVertexPy::representation (void) const
Referenced by ifc4.ifcproduct::placementforshaperepresentation(), automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), ifc2x3.ifcproduct::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setColor()
void CosmeticVertexPy::setColor (Py::Object arg)
setter for the Color attribute
References TechDraw::CosmeticVertex::color, Base::Console(), Base::ConsoleSingleton::Error(), getCosmeticVertexPtr(), and TechDraw::DrawUtil::pyTupleToColor().
Referenced by staticCallback_setColor().
setCustomAttributes()
int CosmeticVertexPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setPoint()
void CosmeticVertexPy::setPoint (Py::Object arg)
setter for the Point attribute
References getCosmeticVertexPtr(), TechDraw::DrawUtil::invertY(), TechDraw::CosmeticVertex::permaPoint, and Base::VectorPy::Type.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::resetPoint(), and staticCallback_setPoint().
setShow()
void CosmeticVertexPy::setShow (Py::Boolean arg)
setter for the Show attribute
References getCosmeticVertexPtr(), and TechDraw::CosmeticVertex::visible.
Referenced by staticCallback_setShow().
setSize()
void CosmeticVertexPy::setSize (Py::Object arg)
setter for the Size attribute
References getCosmeticVertexPtr(), and TechDraw::CosmeticVertex::size.
Referenced by staticCallback_setSize().
setStyle()
void CosmeticVertexPy::setStyle (Py::Object arg)
setter for the Style attribute
References getCosmeticVertexPtr(), and TechDraw::CosmeticVertex::style.
Referenced by staticCallback_setStyle().
staticCallback_clone()
PyObject * CosmeticVertexPy::staticCallback_clone (PyObject * self, PyObject * args) static
callback for the clone() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, clone(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_copy()
PyObject * CosmeticVertexPy::staticCallback_copy (PyObject * self, PyObject * args) static
callback for the copy() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, copy(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getColor()
PyObject * CosmeticVertexPy::staticCallback_getColor (PyObject * self, void * closure) static
getter callback for the Color attribute
References Base::BaseExceptionFreeCADError, getColor(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getPoint()
PyObject * CosmeticVertexPy::staticCallback_getPoint (PyObject * self, void * closure) static
getter callback for the Point attribute
References Base::BaseExceptionFreeCADError, getPoint(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getShow()
PyObject * CosmeticVertexPy::staticCallback_getShow (PyObject * self, void * closure) static
getter callback for the Show attribute
References Base::BaseExceptionFreeCADError, getShow(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getSize()
PyObject * CosmeticVertexPy::staticCallback_getSize (PyObject * self, void * closure) static
getter callback for the Size attribute
References Base::BaseExceptionFreeCADError, getSize(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getStyle()
PyObject * CosmeticVertexPy::staticCallback_getStyle (PyObject * self, void * closure) static
getter callback for the Style attribute
References Base::BaseExceptionFreeCADError, getStyle(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getTag()
PyObject * CosmeticVertexPy::staticCallback_getTag (PyObject * self, void * closure) static
getter callback for the Tag attribute
References Base::BaseExceptionFreeCADError, getTag(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setColor()
int CosmeticVertexPy::staticCallback_setColor (PyObject * self, PyObject * value, void * closure) static
setter callback for the Color attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setColor().
staticCallback_setPoint()
int CosmeticVertexPy::staticCallback_setPoint (PyObject * self, PyObject * value, void * closure) static
setter callback for the Point attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setPoint().
staticCallback_setShow()
int CosmeticVertexPy::staticCallback_setShow (PyObject * self, PyObject * value, void * closure) static
setter callback for the Show attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setShow().
staticCallback_setSize()
int CosmeticVertexPy::staticCallback_setSize (PyObject * self, PyObject * value, void * closure) static
setter callback for the Size attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setSize().
staticCallback_setStyle()
int CosmeticVertexPy::staticCallback_setStyle (PyObject * self, PyObject * value, void * closure) static
setter callback for the Style attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setStyle().
staticCallback_setTag()
int CosmeticVertexPy::staticCallback_setTag (PyObject * self, PyObject * value, void * closure) static
setter callback for the Tag attribute
References Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
Member Data Documentation
GetterSetter
PyGetSetDef CosmeticVertexPy::GetterSetter static
Attribute structure of CosmeticVertexPy.
Methods
PyMethodDef CosmeticVertexPy::Methods static
Initial value:
= {
    {"clone",
        reinterpret_cast<PyCFunction>( staticCallback_clone ),
        METH_VARARGS,
        "Create a clone of this CosmeticVertex"
    },
    {"copy",
        reinterpret_cast<PyCFunction>( staticCallback_copy ),
        METH_VARARGS,
        "Create a copy of this CosmeticVertex"
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of CosmeticVertexPy.
Type
PyTypeObject CosmeticVertexPy::Type static
Type structure of CosmeticVertexPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), draftobjects.draft_annotation.DraftAnnotation::add_missing_properties_0v19(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchComponent.Component::execute(), draftobjects.layer.LayerContainer::execute(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), TechDraw::DrawViewPartPy::removeCosmeticVertex(), draftobjects.layer.Layer::set_properties(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/TechDraw/App/CosmeticVertexPy.h
Sources/FreeCAD/src/Mod/TechDraw/App/CosmeticVertexPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/TechDraw/App/CosmeticVertexPy.cpp