FreeCAD: TechDrawGui::DlgPrefsTechDrawScaleImp Class Reference
TechDrawGui::DlgPrefsTechDrawScaleImp Class Reference
#include <DlgPrefsTechDrawScaleImp.h>
Public Member Functions
DlgPrefsTechDrawScaleImp (QWidget *parent=nullptr)
~DlgPrefsTechDrawScaleImp ()
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Slots
void onScaleTypeChanged (int index)
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void loadSettings ()
void saveSettings ()
virtual void changeEvent (QEvent *e)=0
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Constructor & Destructor Documentation
DlgPrefsTechDrawScaleImp()
DlgPrefsTechDrawScaleImp::DlgPrefsTechDrawScaleImp (QWidget * parent = nullptr)
References draftgeoutils.intersections::connect(), Base::Unit::Length, and onScaleTypeChanged().
~DlgPrefsTechDrawScaleImp()
DlgPrefsTechDrawScaleImp::~DlgPrefsTechDrawScaleImp ()
Member Function Documentation
changeEvent()
void DlgPrefsTechDrawScaleImp::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
References loadSettings(), and saveSettings().
loadSettings()
void DlgPrefsTechDrawScaleImp::loadSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
Referenced by changeEvent().
onScaleTypeChanged
void DlgPrefsTechDrawScaleImp::onScaleTypeChanged (int index) protected slot
Referenced by DlgPrefsTechDrawScaleImp().
saveSettings()
void DlgPrefsTechDrawScaleImp::saveSettings () protected virtual
Implements Gui::Dialog::PreferencePage.
Referenced by changeEvent().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/TechDraw/Gui/DlgPrefsTechDrawScaleImp.h
FreeCAD/src/Mod/TechDraw/Gui/DlgPrefsTechDrawScaleImp.cpp