FreeCAD: iisIconLabel Class Reference
iisIconLabel Class Reference
#include <iisiconlabel.h>
Signals
void activated ()
void clicked ()
void contextMenu ()
void pressed ()
void released ()
Public Member Functions
iisIconLabel (const QIcon &icon, const QString &title, QWidget *parent=0)
virtual QSize minimumSizeHint () const
void setColors (const QColor &color, const QColor &colorOver, const QColor &colorOff)
void setFocusPen (const QPen &pen)
void setFont (const QFont &font)
void setSchemePointer (iisIconLabelScheme **pointer)
virtual QSize sizeHint () const
virtual ~iisIconLabel ()
Protected Member Functions
virtual void enterEvent (QEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void leaveEvent (QEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void paintEvent (QPaintEvent *event)
Protected Attributes
bool m_changeCursorOver
bool m_over
bool m_pressed
bool m_underlineOver
QColor myColor
QColor myColorDisabled
QColor myColorOver
QFont myFont
QPen myPen
QIcon myPixmap
iisIconLabelScheme ** mySchemePointer
QString myText
Constructor & Destructor Documentation
iisIconLabel()
iisIconLabel::iisIconLabel (const QIcon & icon, const QString & title, QWidget * parent = 0)
References myColor, myColorDisabled, myColorOver, myFont, and myPen.
~iisIconLabel()
iisIconLabel::~iisIconLabel () virtual
Member Function Documentation
activated
void iisIconLabel::activated () signal
Referenced by keyPressEvent(), and mouseReleaseEvent().
clicked
void iisIconLabel::clicked () signal
Referenced by mouseReleaseEvent().
contextMenu
void iisIconLabel::contextMenu () signal
Referenced by mousePressEvent().
enterEvent()
void iisIconLabel::enterEvent (QEvent * event) protected virtual
References m_over.
keyPressEvent()
void iisIconLabel::keyPressEvent (QKeyEvent * event) protected virtual
References activated().
leaveEvent()
void iisIconLabel::leaveEvent (QEvent * event) protected virtual
References m_over.
minimumSizeHint()
QSize iisIconLabel::minimumSizeHint () const virtual
References myFont, myPixmap, mySchemePointer, and myText.
mousePressEvent()
void iisIconLabel::mousePressEvent (QMouseEvent * event) protected virtual
References contextMenu(), m_pressed, and pressed().
mouseReleaseEvent()
void iisIconLabel::mouseReleaseEvent (QMouseEvent * event) protected virtual
References activated(), clicked(), m_pressed, and released().
paintEvent()
void iisIconLabel::paintEvent (QPaintEvent * event) protected virtual
References m_over, m_underlineOver, myColor, myColorDisabled, myColorOver, myFont, myPen, myPixmap, mySchemePointer, and myText.
pressed
void iisIconLabel::pressed () signal
Referenced by mousePressEvent().
released
void iisIconLabel::released () signal
Referenced by mouseReleaseEvent().
setColors()
void iisIconLabel::setColors (const QColor & color, const QColor & colorOver, const QColor & colorOff)
References myColor, myColorDisabled, and myColorOver.
Referenced by SandboxGui::TaskPanelView::TaskPanelView(), and test::test().
setFocusPen()
void iisIconLabel::setFocusPen (const QPen & pen)
References myPen.
Referenced by SandboxGui::TaskPanelView::TaskPanelView(), and test::test().
setFont()
void iisIconLabel::setFont (const QFont & font)
References myFont.
setSchemePointer()
void iisIconLabel::setSchemePointer (iisIconLabelScheme ** pointer)
References mySchemePointer.
Referenced by iisTaskHeader::iisTaskHeader().
sizeHint()
QSize iisIconLabel::sizeHint () const virtual
Member Data Documentation
m_changeCursorOver
bool iisIconLabel::m_changeCursorOver protected
m_over
bool iisIconLabel::m_over protected
Referenced by enterEvent(), leaveEvent(), and paintEvent().
m_pressed
bool iisIconLabel::m_pressed protected
Referenced by mousePressEvent(), and mouseReleaseEvent().
m_underlineOver
bool iisIconLabel::m_underlineOver protected
Referenced by paintEvent().
myColor
QColor iisIconLabel::myColor protected
Referenced by iisIconLabel(), paintEvent(), and setColors().
myColorDisabled
QColor iisIconLabel::myColorDisabled protected
Referenced by iisIconLabel(), paintEvent(), and setColors().
myColorOver
QColor iisIconLabel::myColorOver protected
Referenced by iisIconLabel(), paintEvent(), and setColors().
myFont
QFont iisIconLabel::myFont protected
Referenced by iisIconLabel(), minimumSizeHint(), paintEvent(), and setFont().
myPen
QPen iisIconLabel::myPen protected
Referenced by iisIconLabel(), paintEvent(), and setFocusPen().
myPixmap
QIcon iisIconLabel::myPixmap protected
Referenced by minimumSizeHint(), and paintEvent().
mySchemePointer
iisIconLabelScheme** iisIconLabel::mySchemePointer protected
Referenced by minimumSizeHint(), paintEvent(), and setSchemePointer().
myText
QString iisIconLabel::myText protected
Referenced by minimumSizeHint(), and paintEvent().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/iisTaskPanel/src/iisiconlabel.h
Sources/FreeCAD/src/Gui/iisTaskPanel/src/iisiconlabel.cpp