FreeCAD: draftguitools.gui_pathtwistedarray.PathTwistedLinkArray Class Reference
draftguitools.gui_pathtwistedarray.PathTwistedLinkArray Class Reference
Workbenches » Python workbenches » Draft » draftguitools
Public Member Functions
def Activated (self)
def GetResources (self)
Public Member Functions inherited from draftguitools.gui_pathtwistedarray.PathTwistedArray
def Activated (self, name=translate("draft","Path twisted array"))
def proceed (self)
Public Member Functions inherited from draftguitools.gui_base_original.DraftTool
def Activated (self, name="None", noplanesetup=False, is_subtool=False)
def commit (self, name, func)
def finish (self, close=False)
def getStrings (self, addrot=None)
def IsActive (self)
Additional Inherited Members
Public Attributes inherited from draftguitools.gui_pathtwistedarray.PathTwistedArray
call
name
use_link
Public Attributes inherited from draftguitools.gui_base_original.Modifier
copymode
Public Attributes inherited from draftguitools.gui_base_original.DraftTool
call
commitList
constrain
doc
extendedCopy
featureName
node
obj
planetrack
point
pos
support
ui
view
Detailed Description
Gui Command for the PathTwistedLinkArray tool.
Member Function Documentation
Activated()
def draftguitools.gui_pathtwistedarray.PathTwistedLinkArray.Activated (self)
Execute when the command is called.
Referenced by draftguitools.gui_arcs.Arc.finish(), draftguitools.gui_beziers.BezCurve.finish(), draftguitools.gui_beziers.CubicBezCurve.finish(), draftguitools.gui_ellipses.Ellipse.finish(), draftguitools.gui_lines.Line.finish(), draftguitools.gui_mirror.Mirror.finish(), draftguitools.gui_move.Move.finish(), draftguitools.gui_polygons.Polygon.finish(), draftguitools.gui_rectangles.Rectangle.finish(), draftguitools.gui_rotate.Rotate.finish(), draftguitools.gui_splines.BSpline.finish(), draftguitools.gui_texts.Text.finish(), draftguitools.gui_points.Point.finish(), draftguitools.gui_shapestrings.ShapeString.finish(), and ArchPanel.CommandPanel.getPoint().
GetResources()
def draftguitools.gui_pathtwistedarray.PathTwistedLinkArray.GetResources (self)
Set icon, menu and tooltip.
Reimplemented from draftguitools.gui_pathtwistedarray.PathTwistedArray.
References draftutils.translate.QT_TRANSLATE_NOOP.
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Mod/Draft/draftguitools/gui_pathtwistedarray.py