FreeCAD: Gui::InputValidator Class Reference
Gui::InputValidator Class Reference
Public Member Functions
void fixup (QString &input) const
InputValidator (InputField *parent)
State validate (QString &input, int &pos) const
~InputValidator ()
Constructor & Destructor Documentation
InputValidator()
InputValidator::InputValidator (InputField * parent)
~InputValidator()
InputValidator::~InputValidator ()
Member Function Documentation
fixup()
void InputValidator::fixup (QString & input) const
References Gui::InputField::fixup().
validate()
QValidator::State InputValidator::validate (QString & input, int & pos) const
References Gui::InputField::validate().
Referenced by AddonManager.CommandAddonManager::startup().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/InputField.cpp