FreeCAD: PathScripts.PathUtil Namespace Reference
PathScripts.PathUtil Namespace Reference
Functions
def clearExpressionEngine (obj)
def getProperty (obj, prop)
def getPropertyValueString (obj, prop)
def getPublicObject (obj)
def isSolid (obj)
def isString (string)
def isValidBaseObject (obj)
def keyValueIter (dictionary)
def opProperty (op, prop)
def setProperty (obj, prop, value)
def toolControllerForOp (op)
def toUnicode (string)
def translate (context, text, disambig=None)
Variables
list NotValidBaseTypeIds = []
Function Documentation
clearExpressionEngine()
def PathScripts.PathUtil.clearExpressionEngine (obj)
clearExpressionEngine(obj) ... removes all expressions from obj.
There is currently a bug that invalidates the DAG if an object
is deleted that still has one or more expressions attached to it.
Use this function to remove all expressions before deletion.
getProperty()
def PathScripts.PathUtil.getProperty (obj, prop)
getProperty(obj, prop) ... answer obj's property defined by its canonical name.
Referenced by PathScripts.PathUtil.getPropertyValueString().
getPropertyValueString()
def PathScripts.PathUtil.getPropertyValueString (obj, prop)
getPropertyValueString(obj, prop) ... answer a string representation of an object's property's value.
References PathScripts.PathUtil.getProperty().
getPublicObject()
def PathScripts.PathUtil.getPublicObject (obj)
getPublicObject(obj) ... returns the object which should be used to reference a feature of the given object.
isSolid()
def PathScripts.PathUtil.isSolid (obj)
isSolid(obj) ... return True if the object is a valid solid.
isString()
def PathScripts.PathUtil.isString (string)
isString(string) ... return True if string is a string, regardless of string type and python version.
isValidBaseObject()
def PathScripts.PathUtil.isValidBaseObject (obj)
isValidBaseObject(obj) ... returns true if the object can be used as a base for a job.
References draftgeoutils.general.isNull().
keyValueIter()
def PathScripts.PathUtil.keyValueIter (dictionary)
keyValueIter(dict) ... return iterable object over dictionary's (key,value) tuples.
opProperty()
def PathScripts.PathUtil.opProperty (op, prop)
opProperty(op, prop) ... return the value of property prop of the underlying operation (or None if prop does not exist)
Referenced by PathScripts.PathUtil.toolControllerForOp().
setProperty()
def PathScripts.PathUtil.setProperty (obj, prop, value)
setProperty(obj, prop, value) ... set the property value of obj's property defined by its canonical name.
toolControllerForOp()
def PathScripts.PathUtil.toolControllerForOp (op)
toolControllerForOp(op) ... return the tool controller used by the op.
If the op doesn't have its own tool controller but has a Base object, return its tool controller.
Otherwise return None.
References PathScripts.PathUtil.opProperty().
toUnicode()
def PathScripts.PathUtil.toUnicode (string)
toUnicode(string) ... returns a unicode version of string regardless of the python version.
translate()
def PathScripts.PathUtil.translate (context, text, disambig = None)
Variable Documentation
NotValidBaseTypeIds
list PathScripts.PathUtil.NotValidBaseTypeIds = []