FreeCAD: Part::GeomArcOfEllipse Class Reference
Part::GeomArcOfEllipse Class Reference
#include <Geometry.h>
Public Member Functions
virtual Geometry * copy (void) const
returns a copy of this object having a new randomly generated tag.
GeomArcOfEllipse ()
GeomArcOfEllipse (const Handle(Geom_Ellipse)&)
Base::Vector3d getMajorAxisDir () const
GeomArcOfEllipse::getMajorAxisDir.
double getMajorRadius (void) const
virtual unsigned int getMemSize (void) const
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
double getMinorRadius (void) const
virtual PyObject * getPyObject (void)
This method returns the Python wrapper for a C++ object.
virtual void getRange (double &u, double &v, bool emulateCCWXY) const
GeomArcOfEllipse::getRange.
const Handle (Geom_Geometry) &handle() const
virtual void Restore (Base::XMLReader &)
This method is used to restore properties from an XML document.
virtual void Save (Base::Writer &) const
This method is used to save properties to an XML document.
void setHandle (const Handle(Geom_Ellipse)&)
void setHandle (const Handle(Geom_TrimmedCurve)&)
void setMajorAxisDir (Base::Vector3d newdir)
GeomArcOfEllipse::setMajorAxisDir Rotates the ellipse in its plane, so that its major axis is as close as possible to the provided direction.
void setMajorRadius (double Radius)
void setMinorRadius (double Radius)
virtual void setRange (double u, double v, bool emulateCCWXY)
GeomArcOfEllipse::setRange.
virtual GeomBSplineCurve * toNurbs (double first, double last) const
virtual ~GeomArcOfEllipse ()
Public Member Functions inherited from Part::GeomArcOfConic
double getAngleXU (void) const
GeomArcOfConic::getAngleXU.
Base::Vector3d getCenter (void) const
getCenter
virtual Base::Vector3d getEndPoint () const
Base::Vector3d getEndPoint (bool emulateCCWXY) const
GeomArcOfConic::getEndPoint.
Base::Vector3d getLocation (void) const
virtual void getRange (double &u, double &v) const
virtual Base::Vector3d getStartPoint () const
Base::Vector3d getStartPoint (bool emulateCCWXY) const
GeomArcOfConic::getStartPoint.
Base::Vector3d getXAxisDir () const
GeomArcOfConic::getXAxisDir.
bool isReversed () const
GeomArcOfConic::isReversed.
void setAngleXU (double angle)
GeomArcOfConic::setAngleXU complements getAngleXU.
void setCenter (const Base::Vector3d &Center)
setCenter
void setLocation (const Base::Vector3d &Center)
virtual void setRange (double u, double v)
void setXAxisDir (const Base::Vector3d &newdir)
GeomArcOfConic::setXAxisDir Rotates the conic in its plane, so that its symmetry axis is as close as possible to the provided direction.
virtual ~GeomArcOfConic ()
Public Member Functions inherited from Part::GeomTrimmedCurve
GeomTrimmedCurve ()
GeomTrimmedCurve (const Handle(Geom_TrimmedCurve)&)
bool intersectBasisCurves (const GeomTrimmedCurve *c, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion()) const
void setHandle (const Handle(Geom_TrimmedCurve)&)
virtual ~GeomTrimmedCurve ()
Public Member Functions inherited from Part::GeomBoundedCurve
GeomBoundedCurve ()
virtual ~GeomBoundedCurve ()
Public Member Functions inherited from Part::GeomCurve
bool closestParameter (const Base::Vector3d &point, double &u) const
bool closestParameterToBasisCurve (const Base::Vector3d &point, double &u) const
double curvatureAt (double u) const
Base::Vector3d firstDerivativeAtParameter (double u) const
GeomCurve ()
double getFirstParameter () const
double getLastParameter () const
bool intersect (GeomCurve *c, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion()) const
double length (double u, double v) const
bool normalAt (double u, Base::Vector3d &dir) const
Base::Vector3d pointAtParameter (double u) const
void reverse (void)
Base::Vector3d secondDerivativeAtParameter (double u) const
bool tangent (double u, Base::Vector3d &dir) const
bool tangent (double u, gp_Dir &) const
GeomBSplineCurve * toBSpline (double first, double last) const
toBSpline Converts the curve to a B-spline
TopoDS_Shape toShape () const
virtual ~GeomCurve ()
Public Member Functions inherited from Part::Geometry
Geometry * clone (void) const
returns a cloned object.
void deleteExtension (Base::Type type)
void deleteExtension (std::string name)
std::weak_ptr< GeometryExtension > getExtension (Base::Type type)
std::weak_ptr< const GeometryExtension > getExtension (Base::Type type) const
std::weak_ptr< GeometryExtension > getExtension (std::string name)
std::weak_ptr< const GeometryExtension > getExtension (std::string name) const
std::vector< std::weak_ptr< const GeometryExtension > > getExtensions () const
boost::uuids::uuid getTag () const
returns the tag of the geometry object
bool hasExtension (Base::Type type) const
bool hasExtension (std::string name) const
void mirror (const Base::Vector3d &point)
void mirror (const Base::Vector3d &point, const Base::Vector3d &dir)
void rotate (const Base::Placement &plm)
void scale (const Base::Vector3d &vec, double scale)
void setExtension (std::unique_ptr< GeometryExtension > &&geo)
void transform (const Base::Matrix4D &mat)
void translate (const Base::Vector3d &vec)
virtual ~Geometry ()
Public Member Functions inherited from Base::Persistence
void dumpToStream (std::ostream &stream, int compression)
virtual Base::Type getTypeId (void) const
virtual void RestoreDocFile (Reader &)
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data.
void restoreFromStream (std::istream &stream)
virtual void SaveDocFile (Writer &) const
This method is used to save large amounts of data to a binary file.
Public Member Functions inherited from Base::BaseClass
BaseClass ()
Construction.
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
static Base::Type getClassTypeId (void)
static void init (void)
Static Public Member Functions inherited from Base::BaseClass
static void * create (void)
static Type getClassTypeId (void)
static void init (void)
Protected Member Functions inherited from Part::GeomArcOfConic
GeomArcOfConic ()
Protected Member Functions inherited from Part::GeomTrimmedCurve
Handle (Geom_TrimmedCurve) myCurve
Protected Member Functions inherited from Part::Geometry
void assignTag (const Part::Geometry *)
copies the tag from the geometry passed as a parameter to this object
void copyNonTag (const Part::Geometry *)
void createNewTag ()
create a new tag for the geometry object
Geometry ()
Static Protected Member Functions inherited from Part::GeomCurve
static bool intersect (const Handle(Geom_Curve) c, const Handle(Geom_Curve) c2, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion())
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Part::Geometry
std::vector< std::shared_ptr< GeometryExtension > > extensions
boost::uuids::uuid tag
Constructor & Destructor Documentation
GeomArcOfEllipse() [1/2]
GeomArcOfEllipse::GeomArcOfEllipse ()
GeomArcOfEllipse() [2/2]
GeomArcOfEllipse::GeomArcOfEllipse (const Handle(Geom_Ellipse)& e)
References setHandle().
~GeomArcOfEllipse()
GeomArcOfEllipse::~GeomArcOfEllipse () virtual
Member Function Documentation
copy()
virtual Geometry* Part::GeomArcOfEllipse::copy (void) const virtual
returns a copy of this object having a new randomly generated tag.
If you also want to copy the tag, you may use clone() instead. For creation of geometry with other handles, with or without the same tag, you may use the constructors and the sethandle functions. The tag of a geometry can be copied to another geometry using the assignTag function.
Implements Part::GeomArcOfConic.
getMajorAxisDir()
Base::Vector3d GeomArcOfEllipse::getMajorAxisDir () const
GeomArcOfEllipse::getMajorAxisDir.
Returns
the direction vector (unit-length) of major axis of the ellipse. The direction also points to the first focus.
References Handle().
Referenced by CmdSketcherConstrainPerpendicular::activated(), Sketcher::Sketch::addArcOfEllipse(), Sketcher::SketchObject::addSymmetric(), CmdSketcherConstrainPerpendicular::applyConstraint(), SketcherGui::ViewProviderSketch::doBoxSelection(), SketcherGui::ViewProviderSketch::draw(), Sketcher::SketchObject::exposeInternalGeometry(), SketcherGui::makeTangentToArcOfEllipseviaNewPoint(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), and Sketcher::SketchObject::trim().
getMajorRadius()
double Part::GeomArcOfEllipse::getMajorRadius (void) const
Referenced by CmdSketcherConstrainPerpendicular::activated(), Sketcher::Sketch::addArcOfEllipse(), Sketcher::SketchObject::addSymmetric(), CmdSketcherConstrainPerpendicular::applyConstraint(), SketcherGui::ViewProviderSketch::doBoxSelection(), SketcherGui::ViewProviderSketch::draw(), Sketcher::SketchObject::exposeInternalGeometry(), SketcherGui::makeTangentToArcOfEllipseviaNewPoint(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), and Sketcher::SketchObject::trim().
getMemSize()
unsigned int GeomArcOfEllipse::getMemSize (void) const virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Part::GeomArcOfConic.
getMinorRadius()
double GeomArcOfEllipse::getMinorRadius (void) const
References Handle().
Referenced by CmdSketcherConstrainPerpendicular::activated(), Sketcher::Sketch::addArcOfEllipse(), Sketcher::SketchObject::addSymmetric(), CmdSketcherConstrainPerpendicular::applyConstraint(), SketcherGui::ViewProviderSketch::doBoxSelection(), SketcherGui::ViewProviderSketch::draw(), Sketcher::SketchObject::exposeInternalGeometry(), SketcherGui::makeTangentToArcOfEllipseviaNewPoint(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), and Sketcher::SketchObject::trim().
getPyObject()
PyObject * GeomArcOfEllipse::getPyObject (void) virtual
This method returns the Python wrapper for a C++ object.
It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeomArcOfConic.
References Part::Geometry::clone().
getRange()
void GeomArcOfEllipse::getRange (double & u, double & v, bool emulateCCWXY) const virtual
GeomArcOfEllipse::getRange.
Parameters
u [out] start angle of the arc, in radians.
v [out] end angle of the arc, in radians.
emulateCCWXY if true, the arc will pretent to be a CCW arc in XY plane. For this to work, the arc must lie in XY plane (i.e. Axis is either +Z or -Z).
Implements Part::GeomArcOfConic.
References Part::GeomArcOfConic::isReversed().
Referenced by Sketcher::Sketch::addArcOfEllipse(), Sketcher::SketchObject::addSymmetric(), SketcherGui::ViewProviderSketch::doBoxSelection(), SketcherGui::ViewProviderSketch::draw(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), and Sketcher::SketchObject::trim().
Handle()
const Part::GeomArcOfEllipse::Handle (Geom_Geometry) const & virtual
Implements Part::GeomArcOfConic.
Referenced by getMajorAxisDir(), getMinorRadius(), Restore(), Save(), setHandle(), setMajorAxisDir(), and setMinorRadius().
Restore()
void GeomArcOfEllipse::Restore (Base::XMLReader &) virtual
This method is used to restore properties from an XML document.
It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Part::GeomTrimmedCurve.
References Base::XMLReader::getAttributeAsFloat(), Handle(), Base::XMLReader::readElement(), and Part::Geometry::Restore().
Save()
void GeomArcOfEllipse::Save (Base::Writer &) const virtual
This method is used to save properties to an XML document.
A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from Part::GeomTrimmedCurve.
References Handle(), Base::Writer::ind(), Part::Geometry::Save(), and Base::Writer::Stream().
setHandle() [1/2]
void GeomArcOfEllipse::setHandle (const Handle(Geom_Ellipse)& e)
setHandle() [2/2]
void GeomArcOfEllipse::setHandle (const Handle(Geom_TrimmedCurve)& c)
References Handle().
Referenced by Sketcher::SketchObjectPy::addGeometry(), GeomArcOfEllipse(), Part::ArcOfEllipsePy::PyInit(), and Sketcher::SketchObject::rebuildExternalGeometry().
setMajorAxisDir()
void GeomArcOfEllipse::setMajorAxisDir (Base::Vector3d newdir)
GeomArcOfEllipse::setMajorAxisDir Rotates the ellipse in its plane, so that its major axis is as close as possible to the provided direction.
Parameters
newdir [in] is the new direction. If the vector is small, the orientation of the ellipse will be preserved. If the vector is not small, but its projection onto plane of the ellipse is small, an exception will be thrown.
References Handle(), Base::Vector3< _Precision >::Length(), Base::Vector3< _Precision >::Sqr(), Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by Sketcher::SketchObject::addSymmetric(), and Sketcher::SketchObject::trim().
setMajorRadius()
void Part::GeomArcOfEllipse::setMajorRadius (double Radius)
Referenced by Part::ArcOfEllipsePy::setMajorRadius(), and Sketcher::SketchObject::trim().
setMinorRadius()
void GeomArcOfEllipse::setMinorRadius (double Radius)
References Handle().
Referenced by Part::ArcOfEllipsePy::setMinorRadius(), and Sketcher::SketchObject::trim().
setRange()
void GeomArcOfEllipse::setRange (double u, double v, bool emulateCCWXY) virtual
GeomArcOfEllipse::setRange.
Parameters
u [in] start angle of the arc, in radians.
v [in] end angle of the arc, in radians.
emulateCCWXY if true, the arc will pretent to be a CCW arc in XY plane. For this to work, the arc must lie in XY plane (i.e. Axis is either +Z or -Z).
Implements Part::GeomArcOfConic.
References Part::GeomArcOfConic::isReversed().
Referenced by Sketcher::SketchObject::addSymmetric(), and Sketcher::SketchObject::trim().
toNurbs()
virtual GeomBSplineCurve* Part::GeomArcOfEllipse::toNurbs (double first, double last) const virtual
The default implementation does the same as toBSpline. In sub-classes this can be reimplemented to create a real NURBS curve and not just an approximation.
Reimplemented from Part::GeomCurve.
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/Part/App/Geometry.h
Sources/FreeCAD/src/Mod/Part/App/Geometry.cpp