FreeCAD: SMESH::Controls::GroupColor Class Reference
SMESH::Controls::GroupColor Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
void GetColorStr (TCollection_AsciiString &) const
virtual SMDSAbs_ElementType GetType () const
GroupColor ()
virtual bool IsSatisfy (long theElementId)
void SetColorStr (const TCollection_AsciiString &)
virtual void SetMesh (const SMDS_Mesh *theMesh)
void SetType (SMDSAbs_ElementType theType)
virtual SMDSAbs_ElementType GetType () const =0
virtual bool IsSatisfy (long theElementId)=0
Public Member Functions inherited from SMESH::Controls::Functor
virtual SMDSAbs_ElementType GetType () const =0
virtual void SetMesh (const SMDS_Mesh *theMesh)=0
virtual ~Functor ()
Constructor & Destructor Documentation
GroupColor()
GroupColor::GroupColor ()
Member Function Documentation
GetColorStr()
void GroupColor::GetColorStr (TCollection_AsciiString & theResStr) const
GetType()
SMDSAbs_ElementType GroupColor::GetType () const virtual
Implements SMESH::Controls::Predicate.
IsSatisfy()
bool GroupColor::IsSatisfy (long theElementId) virtual
Implements SMESH::Controls::Predicate.
SetColorStr()
void GroupColor::SetColorStr (const TCollection_AsciiString & theStr)
SetMesh()
void GroupColor::SetMesh (const SMDS_Mesh * theMesh) virtual
Implements SMESH::Controls::Functor.
References SMESHDS_GroupBase::Extent(), SMESHDS_GroupBase::GetColor(), SMESHDS_Mesh::GetGroups(), SMESHDS_GroupBase::GetID(), SMESHDS_Mesh::GetNbGroups(), and SMESHDS_GroupBase::GetType().
SetType()
void GroupColor::SetType (SMDSAbs_ElementType theType)
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp