FreeCAD: Part::PointPy Class Reference
Part::PointPy Class Reference
The python export class for GeomPoint.
#include <PointPy.h>
Public Types
typedef GeomPoint * PointerType
Public Types inherited from Part::GeometryPy
typedef Geometry * PointerType
Public Types inherited from Base::PersistencePy
typedef Persistence * PointerType
Public Types inherited from Base::BaseClassPy
typedef BaseClass * PointerType
Public Types inherited from Base::PyObjectBase
typedef void * PointerType
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
Public Member Functions
virtual PyTypeObject * GetType (void)
PointPy (GeomPoint *pcObject, PyTypeObject *T=&Type)
virtual int PyInit (PyObject *args, PyObject *k)
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
std::string representation (void) const
Public Member Functions inherited from Part::GeometryPy
GeometryPy (Geometry *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * mirror (PyObject *args)
implementer for the mirror() method
PyObject * rotate (PyObject *args)
implementer for the rotate() method
PyObject * scale (PyObject *args)
implementer for the scale() method
PyObject * transform (PyObject *args)
implementer for the transform() method
PyObject * translate (PyObject *args)
implementer for the translate() method
PyObject * copy (PyObject *args)
implementer for the copy() method
PyObject * clone (PyObject *args)
implementer for the clone() method
PyObject * hasExtensionOfType (PyObject *args)
implementer for the hasExtensionOfType() method
PyObject * hasExtensionOfName (PyObject *args)
implementer for the hasExtensionOfName() method
PyObject * getExtensionOfType (PyObject *args)
implementer for the getExtensionOfType() method
PyObject * getExtensionOfName (PyObject *args)
implementer for the getExtensionOfName() method
PyObject * setExtension (PyObject *args)
implementer for the setExtension() method
PyObject * deleteExtensionOfType (PyObject *args)
implementer for the deleteExtensionOfType() method
PyObject * deleteExtensionOfName (PyObject *args)
implementer for the deleteExtensionOfName() method
PyObject * getExtensions (PyObject *args)
implementer for the getExtensions() method
Py::String getTag (void) const
getter for the Tag attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Geometry * getGeometryPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PersistencePy
PersistencePy (Persistence *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * dumpContent (PyObject *args, PyObject *kwd)
implementer for the dumpContent() method
PyObject * restoreContent (PyObject *args)
implementer for the restoreContent() method
Py::String getContent (void) const
getter for the Content attribute
Py::Int getMemSize (void) const
getter for the MemSize attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
Persistence * getPersistencePtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::BaseClassPy
BaseClassPy (BaseClass *pcObject, PyTypeObject *T=&Type)
std::string representation (void) const
PyObject * isDerivedFrom (PyObject *args)
implementer for the isDerivedFrom() method
PyObject * getAllDerivedFrom (PyObject *args)
implementer for the getAllDerivedFrom() method
Py::String getTypeId (void) const
getter for the TypeId attribute
Py::String getModule (void) const
getter for the Module attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
BaseClass * getBaseClassPtr (void) const
getter for the object handled by this class
Public Member Functions inherited from Base::PyObjectBase
PyObjectBase * DecRef (void)
decref method wrapper (see python extending manual)
PyObjectBase * IncRef (void)
incref method wrapper (see python extending manual)
bool isConst ()
bool isNotTracking () const
bool isValid ()
PyObjectBase (void *, PyTypeObject *T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
void setConst ()
void setInvalid ()
void setNotTracking (bool on=true)
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
Static Public Member Functions
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
Static Public Member Functions inherited from Part::GeometryPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_mirror (PyObject *self, PyObject *args)
callback for the mirror() method
static PyObject * staticCallback_rotate (PyObject *self, PyObject *args)
callback for the rotate() method
static PyObject * staticCallback_scale (PyObject *self, PyObject *args)
callback for the scale() method
static PyObject * staticCallback_transform (PyObject *self, PyObject *args)
callback for the transform() method
static PyObject * staticCallback_translate (PyObject *self, PyObject *args)
callback for the translate() method
static PyObject * staticCallback_copy (PyObject *self, PyObject *args)
callback for the copy() method
static PyObject * staticCallback_clone (PyObject *self, PyObject *args)
callback for the clone() method
static PyObject * staticCallback_hasExtensionOfType (PyObject *self, PyObject *args)
callback for the hasExtensionOfType() method
static PyObject * staticCallback_hasExtensionOfName (PyObject *self, PyObject *args)
callback for the hasExtensionOfName() method
static PyObject * staticCallback_getExtensionOfType (PyObject *self, PyObject *args)
callback for the getExtensionOfType() method
static PyObject * staticCallback_getExtensionOfName (PyObject *self, PyObject *args)
callback for the getExtensionOfName() method
static PyObject * staticCallback_setExtension (PyObject *self, PyObject *args)
callback for the setExtension() method
static PyObject * staticCallback_deleteExtensionOfType (PyObject *self, PyObject *args)
callback for the deleteExtensionOfType() method
static PyObject * staticCallback_deleteExtensionOfName (PyObject *self, PyObject *args)
callback for the deleteExtensionOfName() method
static PyObject * staticCallback_getExtensions (PyObject *self, PyObject *args)
callback for the getExtensions() method
static PyObject * staticCallback_getTag (PyObject *self, void *closure)
getter callback for the Tag attribute
static int staticCallback_setTag (PyObject *self, PyObject *value, void *closure)
setter callback for the Tag attribute
Static Public Member Functions inherited from Base::PersistencePy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_dumpContent (PyObject *self, PyObject *args, PyObject *kwd)
callback for the dumpContent() method
static PyObject * staticCallback_restoreContent (PyObject *self, PyObject *args)
callback for the restoreContent() method
static PyObject * staticCallback_getContent (PyObject *self, void *closure)
getter callback for the Content attribute
static int staticCallback_setContent (PyObject *self, PyObject *value, void *closure)
setter callback for the Content attribute
static PyObject * staticCallback_getMemSize (PyObject *self, void *closure)
getter callback for the MemSize attribute
static int staticCallback_setMemSize (PyObject *self, PyObject *value, void *closure)
setter callback for the MemSize attribute
Static Public Member Functions inherited from Base::BaseClassPy
static PyObject * PyMake (struct _typeobject *, PyObject *, PyObject *)
static PyObject * staticCallback_isDerivedFrom (PyObject *self, PyObject *args)
callback for the isDerivedFrom() method
static PyObject * staticCallback_getAllDerivedFrom (PyObject *self, PyObject *args)
callback for the getAllDerivedFrom() method
static PyObject * staticCallback_getTypeId (PyObject *self, void *closure)
getter callback for the TypeId attribute
static int staticCallback_setTypeId (PyObject *self, PyObject *value, void *closure)
setter callback for the TypeId attribute
static PyObject * staticCallback_getModule (PyObject *self, void *closure)
getter callback for the Module attribute
static int staticCallback_setModule (PyObject *self, PyObject *value, void *closure)
setter callback for the Module attribute
Static Public Member Functions inherited from Base::PyObjectBase
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
Static Public Attributes
static PyGetSetDef GetterSetter []
Attribute structure of PointPy.
static PyMethodDef Methods []
Methods structure of PointPy.
static PyTypeObject Type
Type structure of PointPy.
Static Public Attributes inherited from Part::GeometryPy
static PyGetSetDef GetterSetter []
Attribute structure of GeometryPy.
static PyMethodDef Methods []
Methods structure of GeometryPy.
static PyTypeObject Type
Type structure of GeometryPy.
Static Public Attributes inherited from Base::PersistencePy
static PyGetSetDef GetterSetter []
Attribute structure of PersistencePy.
static PyMethodDef Methods []
Methods structure of PersistencePy.
static PyTypeObject Type
Type structure of PersistencePy.
Static Public Attributes inherited from Base::BaseClassPy
static PyGetSetDef GetterSetter []
Attribute structure of BaseClassPy.
static PyMethodDef Methods []
Methods structure of BaseClassPy.
static PyTypeObject Type
Type structure of BaseClassPy.
Static Public Attributes inherited from Base::PyObjectBase
static PyMethodDef Methods []
static PyTypeObject Type
Py_Header struct from python.h.
Protected Member Functions
~PointPy ()
Protected Member Functions inherited from Part::GeometryPy
~GeometryPy ()
Protected Member Functions inherited from Base::PersistencePy
~PersistencePy ()
Protected Member Functions inherited from Base::BaseClassPy
~BaseClassPy ()
Protected Member Functions inherited from Base::PyObjectBase
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
virtual ~PyObjectBase ()
destructor
callbacks and implementers for the python object methods
PyObject * toShape (PyObject *args)
implementer for the toShape() method
static PyObject * staticCallback_toShape (PyObject *self, PyObject *args)
callback for the toShape() method
callbacks and implementers for the python object attributes
Py::Float getX (void) const
getter for the X attribute
void setX (Py::Float arg)
setter for the X attribute
Py::Float getY (void) const
getter for the Y attribute
void setY (Py::Float arg)
setter for the Y attribute
Py::Float getZ (void) const
getter for the Z attribute
void setZ (Py::Float arg)
setter for the Z attribute
PyObject * getCustomAttributes (const char *attr) const
getter method for special attributes (e.g. dynamic ones)
int setCustomAttributes (const char *attr, PyObject *obj)
setter for special attributes (e.g.
GeomPoint * getGeomPointPtr (void) const
getter for the object handled by this class
static PyObject * staticCallback_getX (PyObject *self, void *closure)
getter callback for the X attribute
static int staticCallback_setX (PyObject *self, PyObject *value, void *closure)
setter callback for the X attribute
static PyObject * staticCallback_getY (PyObject *self, void *closure)
getter callback for the Y attribute
static int staticCallback_setY (PyObject *self, PyObject *value, void *closure)
setter callback for the Y attribute
static PyObject * staticCallback_getZ (PyObject *self, void *closure)
getter callback for the Z attribute
static int staticCallback_setZ (PyObject *self, PyObject *value, void *closure)
setter callback for the Z attribute
Additional Inherited Members
Protected Attributes inherited from Base::PyObjectBase
std::bitset< 32 > StatusBits
Detailed Description
The python export class for GeomPoint.
Member Typedef Documentation
PointerType
typedef GeomPoint* Part::PointPy::PointerType
Constructor & Destructor Documentation
~PointPy()
PointPy::~PointPy () protected
PointPy()
PointPy::PointPy (GeomPoint * pcObject, PyTypeObject * T = &Type)
Referenced by PyMake().
Member Function Documentation
getCustomAttributes()
PyObject * PointPy::getCustomAttributes (const char * attr) const
getter method for special attributes (e.g. dynamic ones)
getGeomPointPtr()
GeomPoint * PointPy::getGeomPointPtr (void) const
getter for the object handled by this class
Referenced by getX(), getY(), getZ(), PyInit(), representation(), setX(), setY(), setZ(), and toShape().
GetType()
virtual PyTypeObject* Part::PointPy::GetType (void) virtual
Reimplemented from Part::GeometryPy.
getX()
Py::Float PointPy::getX (void) const
getter for the X attribute
References getGeomPointPtr().
Referenced by staticCallback_getX().
getY()
Py::Float PointPy::getY (void) const
getter for the Y attribute
References getGeomPointPtr().
Referenced by staticCallback_getY().
getZ()
Py::Float PointPy::getZ (void) const
getter for the Z attribute
References getGeomPointPtr().
Referenced by staticCallback_getZ().
PyInit()
int PointPy::PyInit (PyObject * , PyObject *) virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Reimplemented from Part::GeometryPy.
References getGeomPointPtr(), Base::VectorPy::Type, and Type.
PyMake()
PyObject * PointPy::PyMake (struct _typeobject * , PyObject * , PyObject *) static
References PointPy().
representation()
std::string PointPy::representation (void) const
References getGeomPointPtr(), and Part::GeomPoint::getPoint().
Referenced by automotive_design.motion_link_relationship::wr1(), automotive_design.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), config_control_design.pcurve::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), config_control_design.pcurve::wr2(), and config_control_design.degenerate_pcurve::wr2().
setCustomAttributes()
int PointPy::setCustomAttributes (const char * attr, PyObject * obj)
setter for special attributes (e.g.
dynamic ones) Output: Success=1, Failure=-1, Ignore=0
setX()
void PointPy::setX (Py::Float arg)
setter for the X attribute
References getGeomPointPtr().
Referenced by staticCallback_setX().
setY()
void PointPy::setY (Py::Float arg)
setter for the Y attribute
References getGeomPointPtr().
Referenced by staticCallback_setY().
setZ()
void PointPy::setZ (Py::Float arg)
setter for the Z attribute
References getGeomPointPtr().
Referenced by staticCallback_setZ().
staticCallback_getX()
PyObject * PointPy::staticCallback_getX (PyObject * self, void * closure) static
getter callback for the X attribute
References Base::BaseExceptionFreeCADError, getX(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getY()
PyObject * PointPy::staticCallback_getY (PyObject * self, void * closure) static
getter callback for the Y attribute
References Base::BaseExceptionFreeCADError, getY(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_getZ()
PyObject * PointPy::staticCallback_getZ (PyObject * self, void * closure) static
getter callback for the Z attribute
References Base::BaseExceptionFreeCADError, getZ(), Base::PyObjectBase::isValid(), and Base::PyObjectBase::PyObjectBase().
staticCallback_setX()
int PointPy::staticCallback_setX (PyObject * self, PyObject * value, void * closure) static
setter callback for the X attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setX().
staticCallback_setY()
int PointPy::staticCallback_setY (PyObject * self, PyObject * value, void * closure) static
setter callback for the Y attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setY().
staticCallback_setZ()
int PointPy::staticCallback_setZ (PyObject * self, PyObject * value, void * closure) static
setter callback for the Z attribute
References Base::BaseExceptionFreeCADError, Base::PyObjectBase::isConst(), Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and setZ().
staticCallback_toShape()
PyObject * PointPy::staticCallback_toShape (PyObject * self, PyObject * args) static
callback for the toShape() method
References Base::BaseExceptionFreeCADAbort, Base::BaseExceptionFreeCADError, Base::PyObjectBase::isValid(), Base::PyObjectBase::PyObjectBase(), and toShape().
toShape()
PyObject * PointPy::toShape (PyObject * args)
implementer for the toShape() method
References getGeomPointPtr(), and Part::PartExceptionOCCError.
Referenced by staticCallback_toShape().
Member Data Documentation
GetterSetter
PyGetSetDef PointPy::GetterSetter static
Initial value:
= {
    {"X",
        (getter) staticCallback_getX,
        (setter) staticCallback_setX,
        "X component of this point.",
        NULL
    },
    {"Y",
        (getter) staticCallback_getY,
        (setter) staticCallback_setY,
        "Y component of this point.",
        NULL
    },
    {"Z",
        (getter) staticCallback_getZ,
        (setter) staticCallback_setZ,
        "Z component of this point.",
        NULL
    },
    {NULL, NULL, NULL, NULL, NULL}
}
Attribute structure of PointPy.
Methods
PyMethodDef PointPy::Methods static
Initial value:
= {
    {"toShape",
        reinterpret_cast<PyCFunction>( staticCallback_toShape ),
        METH_VARARGS,
        "Create a vertex from this point."
    },
    {NULL, NULL, 0, NULL}
}
Methods structure of PointPy.
Type
PyTypeObject PointPy::Type static
Type structure of PointPy.
Referenced by ArchPanel.CommandPanelSheet::Activated(), ArchStructure.StructSelectionObserver::addSelection(), ArchSite.Compass::buildCoordinates(), ArchAxis.CommandArchGrid::IsActive(), ArchSchedule.CommandArchSchedule::IsActive(), PyInit(), and Part::TopoShapeVertexPy::PyInit().
The documentation for this class was generated from the following files:
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/PointPy.h
Sources/FreeCAD/src/Mod/Part/App/PointPyImp.cpp
Sources/FreeCAD-SourceDocs/src/Mod/Part/App/PointPy.cpp