FreeCAD: Gui::LocationDialog Class Reference
Gui::LocationDialog Class Reference abstract
This is the abstract base dialog class that defines the interface for specifying a direction vector by the user.
#include <InputVector.h>
Public Member Functions
virtual Base::Vector3d getDirection () const =0
Base::Vector3d getUserDirection (bool *ok=nullptr) const
Protected Member Functions
virtual void changeEvent (QEvent *e)=0
LocationDialog (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
virtual ~LocationDialog ()
Detailed Description
This is the abstract base dialog class that defines the interface for specifying a direction vector by the user.
Author
Werner Mayer
Constructor & Destructor Documentation
LocationDialog()
LocationDialog::LocationDialog (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) protected
~LocationDialog()
LocationDialog::~LocationDialog () protected virtual
Member Function Documentation
changeEvent()
virtual void Gui::LocationDialog::changeEvent (QEvent * e) protected pure virtual
Implemented in Gui::LocationDialogUi< Ui >, Gui::LocationDialogImp< Ui >, Gui::LocationDialogUiImp, Gui::Dialog::Placement, and Gui::Dialog::Transform.
getDirection()
virtual Base::Vector3d Gui::LocationDialog::getDirection () const pure virtual
Implemented in Gui::LocationDialogUi< Ui >, Gui::LocationDialogImp< Ui >, Gui::LocationDialogUiImp, Gui::Dialog::Placement, and Gui::Dialog::Transform.
getUserDirection()
Base::Vector3d LocationDialog::getUserDirection (bool * ok = nullptr) const
References Base::UnitsApi::getDecimals(), Gui::Dialog::Ui_InputVector::setupUi(), Gui::Dialog::Ui_InputVector::vectorX, Gui::Dialog::Ui_InputVector::vectorY, Gui::Dialog::Ui_InputVector::vectorZ, Base::Vector3< _Precision >::x, Base::Vector3< _Precision >::y, and Base::Vector3< _Precision >::z.
Referenced by Gui::LocationUi< Ui >::directionActivated(), and Gui::LocationImpUi< Ui >::directionActivated().
The documentation for this class was generated from the following files:
FreeCAD/src/Gui/InputVector.h
FreeCAD/src/Gui/InputVector.cpp