FreeCAD: FemGui::TaskDlgPost Class Reference
FemGui::TaskDlgPost Class Reference
simulation dialog for the TaskView
#include <TaskPostBoxes.h>
Public Member Functions
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
void appendBox (TaskPostBox *box)
virtual void clicked (int)
is called by the framework if an button is clicked which has no accept or reject role
void connectSlots ()
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
returns for Close and Help button
Gui::ViewProviderDocumentObject * getView () const
virtual bool isAllowedAlterDocument (void) const
is called by the framework if the user presses the help button
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual void open ()
is called the TaskView when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
TaskDlgPost (Gui::ViewProviderDocumentObject *view)
~TaskDlgPost ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void autoClosedOnTransactionChange ()
is called by the framework when the dialog is automatically closed due to changing the active transaction
ButtonPosition buttonPosition () const
bool canClose () const
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual void closed ()
is called by the framework when the dialog is closed
void emitDestructionSignal ()
const std::vector< QWidget * > & getDialogContent (void) const
const std::string & getDocumentName () const
virtual QDialogButtonBox::StandardButtons getStandardButtons (void) const
tells the framework which buttons are wished for the dialog
virtual void helpRequested ()
is called by the framework if the user press the help button
virtual bool isAllowedAlterDocument (void) const
virtual bool isAllowedAlterSelection (void) const
virtual bool isAllowedAlterView (void) const
bool isAutoCloseOnTransactionChange () const
bool isEscapeButtonEnabled () const
virtual void modifyStandardButtons (QDialogButtonBox *)
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
void setAutoCloseOnTransactionChange (bool on)
Defines whether a task dialog must be closed if the document changed the active transaction.
void setButtonPosition (ButtonPosition p)
void setDocumentName (const std::string &doc)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
TaskDialog ()
~TaskDialog ()
Protected Member Functions
void recompute ()
Protected Attributes
std::vector< TaskPostBox * > m_boxes
Gui::ViewProviderWeakPtrT m_view
Protected Attributes inherited from Gui::TaskView::TaskDialog
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North , South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
simulation dialog for the TaskView
Constructor & Destructor Documentation
TaskDlgPost()
TaskDlgPost::TaskDlgPost (Gui::ViewProviderDocumentObject * view)
~TaskDlgPost()
TaskDlgPost::~TaskDlgPost ()
Member Function Documentation
accept()
bool TaskDlgPost::accept (void) virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::cmdGuiDocument(), Gui::TaskView::TaskDialog::getDocumentName(), and m_boxes.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
appendBox()
void TaskDlgPost::appendBox (TaskPostBox * box)
References Gui::TaskView::TaskDialog::Content, and m_boxes.
Referenced by FemGui::ViewProviderFemPostFunction::setEdit(), FemGui::ViewProviderFemPostClip::setupTaskDialog(), FemGui::ViewProviderFemPostDataAlongLine::setupTaskDialog(), FemGui::ViewProviderFemPostDataAtPoint::setupTaskDialog(), FemGui::ViewProviderFemPostScalarClip::setupTaskDialog(), FemGui::ViewProviderFemPostWarpVector::setupTaskDialog(), FemGui::ViewProviderFemPostCut::setupTaskDialog(), and FemGui::ViewProviderFemPostObject::setupTaskDialog().
clicked()
void TaskDlgPost::clicked (int button) virtual
is called by the framework if an button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
References recompute().
connectSlots()
void TaskDlgPost::connectSlots ()
References draftgeoutils.intersections::connect(), and m_boxes.
Referenced by FemGui::ViewProviderFemPostObject::setEdit().
getStandardButtons()
QDialogButtonBox::StandardButtons TaskDlgPost::getStandardButtons (void) const virtual
returns for Close and Help button
Reimplemented from Gui::TaskView::TaskDialog.
References m_boxes.
getView()
Gui::ViewProviderDocumentObject * FemGui::TaskDlgPost::getView () const
References m_view.
Referenced by recompute(), FemGui::ViewProviderFemPostFunction::setEdit(), FemGui::ViewProviderFemPostObject::setEdit(), FemGui::ViewProviderFemPostClip::setupTaskDialog(), FemGui::ViewProviderFemPostDataAlongLine::setupTaskDialog(), FemGui::ViewProviderFemPostDataAtPoint::setupTaskDialog(), FemGui::ViewProviderFemPostScalarClip::setupTaskDialog(), FemGui::ViewProviderFemPostWarpVector::setupTaskDialog(), and FemGui::ViewProviderFemPostCut::setupTaskDialog().
isAllowedAlterDocument()
virtual bool FemGui::TaskDlgPost::isAllowedAlterDocument (void) const virtual
is called by the framework if the user presses the help button
Reimplemented from Gui::TaskView::TaskDialog.
modifyStandardButtons()
void TaskDlgPost::modifyStandardButtons (QDialogButtonBox * box) virtual
Reimplemented from Gui::TaskView::TaskDialog.
open()
void TaskDlgPost::open () virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Command::openCommand().
recompute()
void TaskDlgPost::recompute (void) protected
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), getView(), and App::Document::recompute().
Referenced by clicked(), draftguitools.gui_trackers.arcTracker::setApertureAngle(), draftguitools.gui_trackers.arcTracker::setEndAngle(), draftguitools.gui_trackers.arcTracker::setStartAngle(), draftguitools.gui_trackers.bsplineTracker::update(), and draftguitools.gui_trackers.bezcurveTracker::update().
reject()
bool TaskDlgPost::reject (void) virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
References Gui::Command::abortCommand(), Gui::cmdGuiDocument(), and Gui::TaskView::TaskDialog::getDocumentName().
Referenced by draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), femexamples.examplesgui.FemExamples::clicked(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
Member Data Documentation
m_boxes
std::vector<TaskPostBox*> FemGui::TaskDlgPost::m_boxes protected
Referenced by accept(), appendBox(), connectSlots(), and getStandardButtons().
m_view
Gui::ViewProviderWeakPtrT FemGui::TaskDlgPost::m_view protected
Referenced by getView().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Fem/Gui/TaskPostBoxes.h
FreeCAD/src/Mod/Fem/Gui/TaskPostBoxes.cpp