FreeCAD: MED::TSeg3a Struct Reference
MED::TSeg3a Struct Reference
#include <MED_GaussUtils.hxx>
Public Member Functions
virtual void InitFun (const TCCoordSliceArr &theRef, const TCCoordSliceArr &theGauss, TFun &theFun) const
TSeg3a ()
Public Member Functions inherited from MED::TShapeFun
bool Eval (const TCellInfo &theCellInfo, const TNodeInfo &theNodeInfo, const TElemNum &theElemNum, const TCCoordSliceArr &theRef, const TCCoordSliceArr &theGauss, TGaussCoord &theGaussCoord, EModeSwitch theMode)
TCoordSlice GetCoord (TInt theRefId)
TCCoordSlice GetCoord (TInt theRefId) const
void GetFun (const TCCoordSliceArr &theRef, const TCCoordSliceArr &theGauss, TFun &theFun) const
TInt GetNbRef () const
virtual bool IsSatisfy (const TCCoordSliceArr &theRefCoord) const
TShapeFun (TInt theDim=0, TInt theNbRef=0)
Additional Inherited Members
Public Attributes inherited from MED::TShapeFun
TInt myDim
TInt myNbRef
TFloatVector myRefCoord
Constructor & Destructor Documentation
TSeg3a()
MED::TSeg3a::TSeg3a ()
References MED::TShapeFun::GetCoord(), and MED::TShapeFun::GetNbRef().
Member Function Documentation
InitFun()
void MED::TSeg3a::InitFun (const TCCoordSliceArr & theRef, const TCCoordSliceArr & theGauss, TFun & theFun) const virtual
Implements MED::TShapeFun.
References MED::TShapeFun::GetFun(), and MED::TShapeFun::TFun::GetFunSlice().
The documentation for this struct was generated from the following files:
Sources/FreeCAD/src/3rdParty/salomesmesh/inc/MED_GaussUtils.hxx
Sources/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/MED_GaussUtils.cpp