FreeCAD: Gui::ViewProviderMap Class Reference
Gui::ViewProviderMap Class Reference
Public Member Functions
void deleteDocument (const App::Document &doc)
void deleteObject (const ViewProvider &vp)
Gui::ViewProvider * getViewProvider (const App::DocumentObject *obj) const
void newObject (const ViewProvider &vp)
Member Function Documentation
deleteDocument()
void Gui::ViewProviderMap::deleteDocument (const App::Document & doc)
Referenced by Gui::Application::slotDeleteDocument().
deleteObject()
void Gui::ViewProviderMap::deleteObject (const ViewProvider & vp)
Referenced by Gui::Application::slotDeletedObject().
getViewProvider()
Gui::ViewProvider * Gui::ViewProviderMap::getViewProvider (const App::DocumentObject * obj) const
Referenced by Gui::Application::getViewProvider().
newObject()
void Gui::ViewProviderMap::newObject (const ViewProvider & vp)
Referenced by Gui::Application::slotNewObject().
The documentation for this class was generated from the following file:
FreeCAD/src/Gui/Application.cpp