FreeCAD: PartGui::CrossSections Class Reference
PartGui::CrossSections Class Reference
#include <CrossSections.h>
Public Member Functions
void accept ()
void apply ()
CrossSections (const Base::BoundBox3d &bb, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~CrossSections ()
Protected Member Functions
void changeEvent (QEvent *e)
void keyPressEvent (QKeyEvent *)
Constructor & Destructor Documentation
CrossSections()
CrossSections::CrossSections (const Base::BoundBox3d & bb, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
References Gui::Application::activeDocument(), Base::BoundBox3< _Precision >::GetCenter(), Gui::Application::Instance, and Base::Unit::Length.
~CrossSections()
CrossSections::~CrossSections ()
Member Function Documentation
accept()
void CrossSections::accept (void)
References apply().
Referenced by PartGui::TaskCrossSections::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
apply()
void CrossSections::apply ()
References Gui::Command::App, draftgeoutils.faces::bind(), Base::Persistence::getClassTypeId(), draftutils.utils::getObjectsOfType, Part::Feature::getTopoShape(), Part::PropertyPartShape::getValue(), Part::TopoShape::isNull(), Base::SequencerLauncher::next(), Gui::Selection(), and Part::Feature::Shape.
Referenced by accept(), and PartGui::TaskCrossSections::clicked().
changeEvent()
void CrossSections::changeEvent (QEvent * e) protected
keyPressEvent()
void CrossSections::keyPressEvent (QKeyEvent * ke) protected
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Part/Gui/CrossSections.h
FreeCAD/src/Mod/Part/Gui/CrossSections.cpp