FreeCAD: Gui::Dialog::DlgSettingsNavigation Class Reference
Gui::Dialog::DlgSettingsNavigation Class Reference
The Ui_DlgSettingsNavigation class implements a preference page to change settings for the Inventor viewer.
#include <DlgSettingsNavigation.h>
Public Member Functions
DlgSettingsNavigation (QWidget *parent=nullptr)
Constructs a DlgSettingsNavigation which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
void loadSettings ()
void saveSettings ()
~DlgSettingsNavigation ()
Destroys the object and frees any allocated resources.
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=0)
Construction.
virtual ~PreferencePage ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e)
Sets the strings of the subwidgets using the current language.
void retranslate ()
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
Detailed Description
The Ui_DlgSettingsNavigation class implements a preference page to change settings for the Inventor viewer.
Author
Werner Mayer
Constructor & Destructor Documentation
DlgSettingsNavigation()
DlgSettingsNavigation::DlgSettingsNavigation (QWidget * parent = nullptr)
Constructs a DlgSettingsNavigation which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
References retranslate().
~DlgSettingsNavigation()
DlgSettingsNavigation::~DlgSettingsNavigation ()
Destroys the object and frees any allocated resources.
Member Function Documentation
changeEvent()
void DlgSettingsNavigation::changeEvent (QEvent * e) protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
References retranslate().
loadSettings()
void DlgSettingsNavigation::loadSettings () virtual
Implements Gui::Dialog::PreferencePage.
References Base::clamp(), draftgeoutils.intersections::connect(), App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), Base::BaseClass::getClassTypeId(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), and Gui::NavigationStyle::Trackball.
retranslate()
void DlgSettingsNavigation::retranslate () protected
References Gui::UserNavigationStyle::getUserFriendlyNames(), and draftutils.translate::translate().
Referenced by changeEvent(), and DlgSettingsNavigation().
saveSettings()
void DlgSettingsNavigation::saveSettings () virtual
Implements Gui::Dialog::PreferencePage.
References App::GetApplication(), ParameterGrp::GetGroup(), App::Application::GetParameterGroupByPath(), ParameterGrp::SetASCII(), ParameterGrp::SetBool(), ParameterGrp::SetFloat(), and ParameterGrp::SetInt().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/DlgSettingsNavigation.h
Sources/FreeCAD/src/Gui/DlgSettingsNavigation.cpp