FreeCAD: SpreadsheetGui::DlgBindSheet Class Reference
SpreadsheetGui::DlgBindSheet Class Reference
#include <DlgBindSheet.h>
Public Slots
void onDiscard ()
Public Member Functions
void accept ()
DlgBindSheet (Spreadsheet::Sheet *sheet, const std::vector< App::Range > &range, QWidget *parent=nullptr)
~DlgBindSheet ()
Constructor & Destructor Documentation
DlgBindSheet()
DlgBindSheet::DlgBindSheet (Spreadsheet::Sheet * sheet, const std::vector< App::Range > & range, QWidget * parent = nullptr) explicit
References Ui_DlgBindSheet::btnDiscard, Ui_DlgBindSheet::checkBoxHREF, Ui_DlgBindSheet::comboBox, draftgeoutils.intersections::connect(), App::GetApplication(), Spreadsheet::Sheet::getCellBinding(), App::DocumentObject::getDocument(), App::ObjectIdentifier::getDocumentObject(), App::Document::getObjectsOfType(), draftfunctions.svgtext::getText(), App::PropertyString::getValue(), App::DocumentObject::Label, Ui_DlgBindSheet::lineEditFromEnd, Ui_DlgBindSheet::lineEditFromStart, Ui_DlgBindSheet::lineEditToEnd, Ui_DlgBindSheet::lineEditToStart, onDiscard(), Gui::ExpressionLineEdit::setDocumentObject(), Gui::ExpressionLineEdit::setPrefix(), and Ui_DlgBindSheet::setupUi().
~DlgBindSheet()
DlgBindSheet::~DlgBindSheet ()
Member Function Documentation
accept()
void DlgBindSheet::accept (void)
References Gui::Command::abortCommand(), Ui_DlgBindSheet::checkBoxHREF, Gui::cmdAppObjectArgs(), Ui_DlgBindSheet::comboBox, Gui::Command::commitCommand(), Gui::Command::Doc, App::GetApplication(), App::Application::getDocument(), App::DocumentObject::getDocument(), App::Document::getObject(), App::CellAddress::isValid(), Ui_DlgBindSheet::lineEditFromEnd, Ui_DlgBindSheet::lineEditFromStart, Ui_DlgBindSheet::lineEditToEnd, Ui_DlgBindSheet::lineEditToStart, Gui::Command::openCommand(), App::quote(), App::Range::size(), and App::stringToAddress().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
onDiscard
void DlgBindSheet::onDiscard () slot
References Gui::Command::abortCommand(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Gui::Command::Doc, Ui_DlgBindSheet::lineEditFromEnd, Ui_DlgBindSheet::lineEditFromStart, and Gui::Command::openCommand().
Referenced by DlgBindSheet().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/Spreadsheet/Gui/DlgBindSheet.h
FreeCAD/src/Mod/Spreadsheet/Gui/DlgBindSheet.cpp