FreeCAD: PartGui::Ui_TaskFaceColors Class Reference
PartGui::Ui_TaskFaceColors Class Reference
#include <ui_TaskFaceColors.h>
Public Member Functions
void retranslateUi (QWidget *PartGui__TaskFaceColors)
void setupUi (QWidget *PartGui__TaskFaceColors)
Public Attributes
QPushButton * boxSelection
Gui::ColorButton * colorButton
QPushButton * defaultButton
QLabel * faceLabel
QGridLayout * gridLayout
QGridLayout * gridLayout_2
QGroupBox * groupBox
QSpacerItem * horizontalSpacer
QSpacerItem * horizontalSpacer_2
QLabel * label
QLabel * labelElement
QVBoxLayout * verticalLayout
Member Function Documentation
retranslateUi()
void PartGui::Ui_TaskFaceColors::retranslateUi (QWidget * PartGui__TaskFaceColors)
References boxSelection, defaultButton, faceLabel, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), PartGui::FaceColors::changeEvent(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void PartGui::Ui_TaskFaceColors::setupUi (QWidget * PartGui__TaskFaceColors)
References boxSelection, colorButton, defaultButton, faceLabel, gridLayout, gridLayout_2, groupBox, horizontalSpacer, horizontalSpacer_2, labelElement, retranslateUi(), and verticalLayout.
Referenced by PartGui::FaceColors::FaceColors().
Member Data Documentation
boxSelection
QPushButton* PartGui::Ui_TaskFaceColors::boxSelection
Referenced by retranslateUi(), PartGui::FaceColors::Private::selectionCallback(), and setupUi().
colorButton
Gui::ColorButton* PartGui::Ui_TaskFaceColors::colorButton
Referenced by PartGui::FaceColors::FaceColors(), DraftGui.DraftToolBar::getcol(), PartGui::FaceColors::onSelectionChanged(), setupUi(), and PartGui::FaceColors::updatePanel().
defaultButton
QPushButton* PartGui::Ui_TaskFaceColors::defaultButton
Referenced by retranslateUi(), and setupUi().
faceLabel
QLabel* PartGui::Ui_TaskFaceColors::faceLabel
Referenced by retranslateUi(), and setupUi().
gridLayout
QGridLayout* PartGui::Ui_TaskFaceColors::gridLayout
Referenced by setupUi().
gridLayout_2
QGridLayout* PartGui::Ui_TaskFaceColors::gridLayout_2
Referenced by setupUi().
groupBox
QGroupBox* PartGui::Ui_TaskFaceColors::groupBox
Referenced by PartGui::FaceColors::FaceColors(), and setupUi().
horizontalSpacer
QSpacerItem* PartGui::Ui_TaskFaceColors::horizontalSpacer
Referenced by setupUi().
horizontalSpacer_2
QSpacerItem* PartGui::Ui_TaskFaceColors::horizontalSpacer_2
Referenced by setupUi().
label
QLabel* PartGui::Ui_TaskFaceColors::label
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), and Spreadsheet_legacy.SpreadsheetView::setEditLine().
labelElement
QLabel* PartGui::Ui_TaskFaceColors::labelElement
Referenced by setupUi(), and PartGui::FaceColors::updatePanel().
verticalLayout
QVBoxLayout* PartGui::Ui_TaskFaceColors::verticalLayout
Referenced by setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Part/Gui/ui_TaskFaceColors.h