FreeCAD: TechDrawGui::QGIView Class Reference
TechDrawGui::QGIView Class Reference
#include <QGIView.h>
Public Types
enum { Type = QGraphicsItem::UserType + 101 }
Public Slots
virtual void onSourceChange (TechDraw::DrawView *newParent)
Public Member Functions
virtual void addArbitraryItem (QGraphicsItem *qgi)
void alignTo (QGraphicsItem *, const QString &alignment)
virtual QRectF boundingRect () const override
virtual void draw (void)
virtual void drawBorder (void)
virtual void drawCaption (void)
QGIViewClip * getClipGroup (void)
virtual QColor getCurrentColor (void)
virtual bool getFrameState (void)
MDIViewPage * getMDIViewPage (void) const
virtual QColor getNormalColor (void)
virtual QColor getPreColor (void)
double getScale (void)
virtual QColor getSelectColor (void)
virtual QColor getSettingColor (void)
const char * getViewName () const
const std::string getViewNameAsString () const
TechDraw::DrawView * getViewObject () const
virtual void isVisible (bool state)
virtual bool isVisible (void)
void makeMark (Base::Vector3d v, QColor c=Qt::red)
void makeMark (double x, double y, QColor c=Qt::red)
void makeMark (QPointF p, QColor c=Qt::red)
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) override
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QGIView ()
virtual void removeChild (QGIView *child)
virtual void rotateView (void)
virtual void setGroupSelection (bool b)
void setLocked (bool b)
virtual void setSettingColor (QColor c)
void setViewFeature (TechDraw::DrawView *obj)
virtual void toggleCache (bool state)
int type () const override
virtual void updateView (bool update=false)
virtual ~QGIView ()
void setPosition (qreal x, qreal y)
Methods to ensure that Y-Coordinates are orientated correctly.
qreal getY ()
bool isInnerView ()
void isInnerView (bool state)
double getYInClip (double y)
Static Public Member Functions
static int calculateFontPixelSize (double sizeInMillimetres)
static int calculateFontPixelWidth (const QFont &font)
static double getDimFontSize (void)
static QGVPage * getGraphicsView (TechDraw::DrawView *dv)
static QString getPrefFont (void)
static double getPrefFontSize (void)
static Gui::ViewProvider * getViewProvider (App::DocumentObject *obj)
Public Attributes
boost::signals2::signal< void(QGIView *, QPointF)> signalSelectPoint
Static Public Attributes
static const double DefaultFontSizeInMM = 5.0
Protected Member Functions
virtual QRectF customChildrenBoundingRect (void) const
void dumpRect (const char *text, QRectF r)
Base::Reference< ParameterGrp > getParmGroupCol (void)
QGIView * getQGIVByName (std::string name)
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
Protected Attributes
QHash< QString, QGraphicsItem * > alignHash
QGCustomBorder * m_border
QBrush m_brush
QGICaption * m_caption
QColor m_colCurrent
QColor m_colNormal
QColor m_colPre
QColor m_colSel
QColor m_colSetting
QPen m_decorPen
QFont m_font
bool m_innerView
QGCustomLabel * m_label
QGCustomImage * m_lock
bool m_locked
double m_lockHeight
double m_lockWidth
QPen m_pen
std::string viewName
TechDraw::DrawView * viewObj
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Constructor & Destructor Documentation
QGIView()
QGIView::QGIView ()
References getNormalColor(), TechDrawGui::QGCustomImage::imageSize(), TechDrawGui::PreferencesGui::labelFontSizePX(), TechDrawGui::QGCustomImage::load(), m_border, m_caption, m_colCurrent, m_decorPen, m_font, m_label, m_lock, m_lockHeight, m_lockWidth, and m_pen.
~QGIView()
QGIView::~QGIView () virtual
References signalSelectPoint.
Member Function Documentation
addArbitraryItem()
void QGIView::addArbitraryItem (QGraphicsItem * qgi) virtual
alignTo()
void QGIView::alignTo (QGraphicsItem * item, const QString & alignment)
References alignHash.
boundingRect()
QRectF QGIView::boundingRect () const override virtual
Reimplemented in TechDrawGui::QGIWeldSymbol, TechDrawGui::QGIViewPart, TechDrawGui::QGIViewDimension, TechDrawGui::QGIRichAnno, and TechDrawGui::QGILeaderLine.
References m_border.
Referenced by TechDrawGui::QGIViewPart::boundingRect(), and rotateView().
calculateFontPixelSize()
int QGIView::calculateFontPixelSize (double sizeInMillimetres) static
References TechDrawGui::Rez::guiX().
Referenced by TechDrawGui::QGIViewAnnotation::drawAnnotation(), TechDrawGui::QGIWeldSymbol::drawTailText(), TechDrawGui::QGIWeldSymbol::drawTile(), TechDrawGui::QGIHighlight::makeReference(), TechDrawGui::QGISectionLine::makeSymbolsISO(), TechDrawGui::QGISectionLine::makeSymbolsTrad(), TechDrawGui::QGIViewBalloon::placeBalloon(), TechDrawGui::QGIViewBalloon::updateBalloon(), and TechDrawGui::QGIViewDimension::updateDim().
calculateFontPixelWidth()
int QGIView::calculateFontPixelWidth (const QFont & font) static
References Gui::QtTools::horizontalAdvance().
customChildrenBoundingRect()
QRectF QGIView::customChildrenBoundingRect (void) const protected virtual
Referenced by drawBorder(), and drawCaption().
draw()
void QGIView::draw (void) virtual
Reimplemented in TechDrawGui::QGIWeldSymbol, TechDrawGui::QGIViewSymbol, TechDrawGui::QGIViewSection, TechDrawGui::QGIViewPart, TechDrawGui::QGIViewImage, TechDrawGui::QGIViewDimension, TechDrawGui::QGIViewClip, TechDrawGui::QGIViewBalloon, TechDrawGui::QGIViewAnnotation, TechDrawGui::QGIRichAnno, and TechDrawGui::QGILeaderLine.
References drawBorder(), getFrameState(), getViewObject(), TechDrawGui::Rez::guiX(), isVisible(), and setPosition().
Referenced by TechDrawGui::QGIRichAnno::draw(), TechDrawGui::QGIViewAnnotation::draw(), TechDrawGui::QGIViewImage::draw(), TechDrawGui::QGIViewSymbol::draw(), TechDrawGui::ViewProviderDrawingView::show(), and updateView().
drawBorder()
void QGIView::drawBorder (void) virtual
Reimplemented in TechDrawGui::QGIProjGroup, TechDrawGui::QGIWeldSymbol, TechDrawGui::QGIViewDimension, TechDrawGui::QGIViewBalloon, TechDrawGui::QGIRichAnno, and TechDrawGui::QGILeaderLine.
References customChildrenBoundingRect(), drawCaption(), getFrameState(), getPrefFont(), getViewObject(), getViewProvider(), TechDrawGui::PreferencesGui::labelFontSizePX(), ZVALUE::LOCK, m_border, m_colCurrent, m_decorPen, m_font, m_label, m_lock, and m_lockHeight.
Referenced by TechDrawGui::QGIViewClip::draw(), draw(), hoverEnterEvent(), hoverLeaveEvent(), and itemChange().
drawCaption()
void QGIView::drawCaption (void) virtual
References TechDrawGui::QGCustomText::boundingRect(), customChildrenBoundingRect(), getFrameState(), getPrefFont(), getViewObject(), getViewProvider(), TechDrawGui::PreferencesGui::labelFontSizePX(), m_caption, m_colCurrent, m_font, and m_label.
Referenced by drawBorder().
dumpRect()
void QGIView::dumpRect (const char * text, QRectF r) protected
References Base::Console(), and Base::ConsoleSingleton::Message().
getClipGroup()
QGIViewClip * QGIView::getClipGroup (void)
References Base::Console(), getViewName(), getViewObject(), and Base::ConsoleSingleton::Log().
getCurrentColor()
virtual QColor TechDrawGui::QGIView::getCurrentColor (void) virtual
Referenced by TechDrawGui::QGIWeldSymbol::drawAllAround(), TechDrawGui::QGIWeldSymbol::drawTailText(), and TechDrawGui::QGIWeldSymbol::drawTile().
getDimFontSize()
double QGIView::getDimFontSize (void) static
getFrameState()
bool QGIView::getFrameState (void) virtual
References TechDraw::DrawView::findParentPage(), Gui::Application::getDocument(), App::DocumentObject::getDocument(), TechDrawGui::ViewProviderPage::getFrameState(), getViewObject(), Gui::Document::getViewProvider(), and Gui::Application::Instance.
Referenced by TechDrawGui::QGIViewClip::draw(), draw(), drawBorder(), drawCaption(), and TechDrawGui::QGIViewPart::drawViewPart().
getGraphicsView()
QGVPage * QGIView::getGraphicsView (TechDraw::DrawView * dv) static
References TechDrawGui::ViewProviderDrawingView::getMDIViewPage(), TechDrawGui::MDIViewPage::getQGVPage(), and getViewProvider().
getMDIViewPage()
MDIViewPage * QGIView::getMDIViewPage (void) const
References TechDrawGui::MDIViewPage::getFromScene().
Referenced by TechDrawGui::QGIViewPart::removePrimitives().
getNormalColor()
QColor QGIView::getNormalColor (void) virtual
Reimplemented in TechDrawGui::QGIViewBalloon, and TechDrawGui::QGILeaderLine.
References TechDrawGui::PreferencesGui::normalQColor().
Referenced by TechDrawGui::QGIPrimPath::getNormalColor(), hoverLeaveEvent(), itemChange(), and QGIView().
getParmGroupCol()
Base::Reference< ParameterGrp > QGIView::getParmGroupCol (void) protected
References App::GetApplication(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
getPreColor()
QColor QGIView::getPreColor (void) virtual
References TechDrawGui::PreferencesGui::preselectQColor().
Referenced by TechDrawGui::QGIPrimPath::getPreColor(), hoverEnterEvent(), TechDrawGui::QGIWeldSymbol::hoverEnterEvent(), and TechDrawGui::QGIWeldSymbol::setPrettyPre().
getPrefFont()
QString QGIView::getPrefFont (void) static
Referenced by drawBorder(), drawCaption(), and TechDrawGui::QGIGhostHighlight::QGIGhostHighlight().
getPrefFontSize()
double QGIView::getPrefFontSize (void) static
getQGIVByName()
QGIView * QGIView::getQGIVByName (std::string name) protected
References getViewName().
Referenced by TechDrawGui::QGIViewClip::drawClip(), and TechDrawGui::QGILeaderLine::onSourceChange().
getScale()
double QGIView::getScale (void)
References TechDraw::DrawView::getScale(), and getViewObject().
Referenced by TechDrawGui::TaskLeaderLine::onTrackerFinished().
getSelectColor()
QColor QGIView::getSelectColor (void) virtual
References TechDrawGui::PreferencesGui::selectQColor().
Referenced by TechDrawGui::QGIPrimPath::getSelectColor(), hoverEnterEvent(), TechDrawGui::QGIWeldSymbol::hoverEnterEvent(), hoverLeaveEvent(), TechDrawGui::QGIWeldSymbol::hoverLeaveEvent(), itemChange(), and TechDrawGui::QGIWeldSymbol::setPrettySel().
getSettingColor()
virtual QColor TechDrawGui::QGIView::getSettingColor (void) virtual
getViewName()
const char * QGIView::getViewName () const
References viewName.
Referenced by TechDrawGui::QGIViewClip::drawClip(), getClipGroup(), getQGIVByName(), TechDrawGui::QGVPage::getQGIVByName(), and TechDrawGui::QGIViewSymbol::symbolToSvg().
getViewNameAsString()
const std::string QGIView::getViewNameAsString () const
References viewName.
Referenced by TechDrawGui::MDIViewPage::compareSelections().
getViewObject()
TechDraw::DrawView * QGIView::getViewObject (void) const
References viewObj.
Referenced by TechDrawGui::QGIViewDimension::arrowPositionsToFeature(), TechDrawGui::QGIViewBalloon::balloonLabelDragged(), TechDrawGui::QGIViewDimension::datumLabelDragFinished(), TechDrawGui::QGILeaderLine::draw(), TechDrawGui::QGIViewBalloon::draw(), TechDrawGui::QGIViewDimension::draw(), TechDrawGui::QGIViewImage::draw(), draw(), TechDrawGui::QGIViewPart::drawAllSectionLines(), TechDrawGui::QGIViewAnnotation::drawAnnotation(), drawBorder(), drawCaption(), TechDrawGui::QGIViewPart::drawCenterLines(), TechDrawGui::QGIViewClip::drawClip(), TechDrawGui::QGIViewPart::drawHighlight(), TechDrawGui::QGIViewImage::drawImage(), TechDrawGui::QGIViewPart::drawMatting(), TechDrawGui::QGIViewPart::drawPainterPath(), TechDrawGui::QGIViewSection::drawSectionFace(), TechDrawGui::QGIViewPart::drawSectionLine(), TechDrawGui::QGIViewSymbol::drawSvg(), TechDrawGui::QGIWeldSymbol::drawTailText(), TechDrawGui::QGIWeldSymbol::drawTile(), TechDrawGui::QGIViewPart::drawViewPart(), TechDrawGui::QGIViewDimension::findIsoExt(), TechDrawGui::QGVPage::findParent(), TechDrawGui::QGIViewPart::formatGeomFromCenterLine(), TechDrawGui::QGIViewPart::formatGeomFromCosmetic(), getClipGroup(), TechDrawGui::QGILeaderLine::getFeature(), TechDrawGui::QGIRichAnno::getFeature(), getFrameState(), TechDrawGui::QGILeaderLine::getLineWidth(), TechDrawGui::QGILeaderLine::getNormalColor(), TechDrawGui::QGIViewBalloon::getNormalColor(), getScale(), TechDrawGui::QGIViewBalloon::getSourceView(), isVisible(), itemChange(), TechDrawGui::QGIProjGroup::mouseReleaseEvent(), mouseReleaseEvent(), TechDrawGui::QGIViewBalloon::placeBalloon(), TechDrawGui::QGIViewDimension::prefNormalColor(), TechDrawGui::QGIRichAnno::rectPen(), rotateView(), TechDrawGui::QGIViewAnnotation::rotateView(), TechDrawGui::QGIViewImage::rotateView(), TechDrawGui::QGIViewSymbol::rotateView(), TechDrawGui::QGIDatumLabel::setPosFromCenter(), TechDrawGui::QGIDatumLabel::setTolString(), TechDrawGui::MDIViewPage::setTreeToSceneSelect(), TechDrawGui::QGILeaderLine::startPathEdit(), TechDrawGui::QGIViewBalloon::updateBalloon(), TechDrawGui::QGIViewDimension::updateDim(), updateView(), TechDrawGui::QGILeaderLine::updateView(), TechDrawGui::QGIRichAnno::updateView(), TechDrawGui::QGIViewAnnotation::updateView(), TechDrawGui::QGIViewBalloon::updateView(), TechDrawGui::QGIViewClip::updateView(), TechDrawGui::QGIViewDimension::updateView(), TechDrawGui::QGIViewImage::updateView(), TechDrawGui::QGIViewPart::updateView(), TechDrawGui::QGIViewSection::updateView(), TechDrawGui::QGIViewSymbol::updateView(), and TechDrawGui::QGIWeldSymbol::updateView().
getViewProvider()
Gui::ViewProvider * QGIView::getViewProvider (App::DocumentObject * obj) static
References Gui::Application::getDocument(), Gui::Document::getViewProvider(), and Gui::Application::Instance.
Referenced by TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), TechDrawGui::QGILeaderLine::draw(), TechDrawGui::QGIRichAnno::draw(), TechDrawGui::QGIViewBalloon::draw(), TechDrawGui::QGIViewDimension::draw(), TechDrawGui::QGIViewImage::draw(), TechDrawGui::QGIViewPart::drawAllSectionLines(), drawBorder(), drawCaption(), TechDrawGui::QGIViewPart::drawCenterLines(), TechDrawGui::QGIViewPart::drawHighlight(), TechDrawGui::QGIViewSection::drawSectionFace(), TechDrawGui::QGIViewPart::drawSectionLine(), TechDrawGui::QGIWeldSymbol::drawTailText(), TechDrawGui::QGIWeldSymbol::drawTile(), TechDrawGui::QGIViewPart::drawViewPart(), TechDrawGui::TaskLeaderLine::findParentQGIV(), TechDrawGui::TaskCenterLine::getCenterWidth(), TechDrawGui::TaskLineDecor::getDefaults(), getGraphicsView(), TechDrawGui::QGILeaderLine::getLineWidth(), TechDrawGui::QGILeaderLine::getNormalColor(), TechDrawGui::QGIViewBalloon::getNormalColor(), isVisible(), TechDrawGui::QGIViewBalloon::placeBalloon(), TechDrawGui::QGIViewDimension::prefNormalColor(), TechDrawGui::QGIRichAnno::rectPen(), TechDrawGui::QGIViewBalloon::updateBalloon(), TechDrawGui::QGIViewDimension::updateDim(), TechDrawGui::QGILeaderLine::updateView(), TechDrawGui::QGIRichAnno::updateView(), TechDrawGui::QGIViewBalloon::updateView(), TechDrawGui::QGIViewDimension::updateView(), and TechDrawGui::QGIViewPart::updateView().
getY()
qreal TechDrawGui::QGIView::getY ()
Referenced by TechDrawGui::QGIProjGroup::mouseReleaseEvent(), and mouseReleaseEvent().
getYInClip()
double QGIView::getYInClip (double y)
Referenced by mouseReleaseEvent(), and setPosition().
hoverEnterEvent()
void QGIView::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected virtual
Reimplemented in TechDrawGui::QGIWeldSymbol, and TechDrawGui::QGILeaderLine.
References drawBorder(), getPreColor(), getSelectColor(), and m_colCurrent.
Referenced by TechDrawGui::QGILeaderLine::hoverEnterEvent(), and TechDrawGui::QGIWeldSymbol::hoverEnterEvent().
hoverLeaveEvent()
void QGIView::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected virtual
Reimplemented in TechDrawGui::QGIWeldSymbol, and TechDrawGui::QGILeaderLine.
References drawBorder(), getNormalColor(), getSelectColor(), and m_colCurrent.
Referenced by TechDrawGui::QGILeaderLine::hoverLeaveEvent(), and TechDrawGui::QGIWeldSymbol::hoverLeaveEvent().
isInnerView() [1/2]
bool TechDrawGui::QGIView::isInnerView ()
Referenced by TechDrawGui::QGIViewClip::drawClip(), mouseReleaseEvent(), and setPosition().
isInnerView() [2/2]
void TechDrawGui::QGIView::isInnerView (bool state)
isVisible() [1/2]
void QGIView::isVisible (bool state) virtual
References getViewObject(), getViewProvider(), App::PropertyBool::setValue(), and Gui::ViewProviderDocumentObject::Visibility.
isVisible() [2/2]
bool QGIView::isVisible (void) virtual
References App::PropertyBool::getValue(), getViewObject(), getViewProvider(), and Gui::ViewProviderDocumentObject::Visibility.
Referenced by TechDrawGui::QGILeaderLine::draw(), TechDrawGui::QGIRichAnno::draw(), TechDrawGui::QGIViewAnnotation::draw(), TechDrawGui::QGIViewBalloon::draw(), TechDrawGui::QGIViewClip::draw(), TechDrawGui::QGIViewDimension::draw(), TechDrawGui::QGIViewImage::draw(), TechDrawGui::QGIViewPart::draw(), TechDrawGui::QGIViewSection::draw(), TechDrawGui::QGIViewSymbol::draw(), TechDrawGui::QGIWeldSymbol::draw(), and draw().
itemChange()
QVariant QGIView::itemChange (GraphicsItemChange change, const QVariant & value) override protected virtual
Reimplemented in TechDrawGui::QGIWeldSymbol, TechDrawGui::QGIViewSymbol, TechDrawGui::QGIViewPart, TechDrawGui::QGIViewImage, TechDrawGui::QGIViewDimension, TechDrawGui::QGIViewCollection, TechDrawGui::QGIViewClip, TechDrawGui::QGIViewBalloon, TechDrawGui::QGIViewAnnotation, TechDrawGui::QGIRichAnno, TechDrawGui::QGIProjGroup, and TechDrawGui::QGILeaderLine.
References alignHash, drawBorder(), Base::Persistence::getClassTypeId(), getNormalColor(), TechDraw::DrawProjGroupItem::getPGroup(), getSelectColor(), getViewObject(), m_colCurrent, and m_locked.
Referenced by TechDrawGui::QGILeaderLine::itemChange(), TechDrawGui::QGIRichAnno::itemChange(), TechDrawGui::QGIViewAnnotation::itemChange(), TechDrawGui::QGIViewBalloon::itemChange(), TechDrawGui::QGIViewClip::itemChange(), TechDrawGui::QGIViewCollection::itemChange(), TechDrawGui::QGIViewDimension::itemChange(), TechDrawGui::QGIViewImage::itemChange(), TechDrawGui::QGIViewPart::itemChange(), TechDrawGui::QGIViewSymbol::itemChange(), and TechDrawGui::QGIWeldSymbol::itemChange().
makeMark() [1/3]
void QGIView::makeMark (Base::Vector3d v, QColor c = Qt::red)
References makeMark().
makeMark() [2/3]
void QGIView::makeMark (double x, double y, QColor c = Qt::red)
References TechDrawGui::QGIPrimPath::setFillColor(), TechDrawGui::QGIPrimPath::setNormalColor(), TechDrawGui::QGIPrimPath::setPrettyNormal(), TechDrawGui::QGIVertex::setRadius(), TechDrawGui::QGIPrimPath::setWidth(), and ZVALUE::VERTEX.
Referenced by makeMark().
makeMark() [3/3]
void QGIView::makeMark (QPointF p, QColor c = Qt::red)
References makeMark().
mousePressEvent()
void QGIView::mousePressEvent (QGraphicsSceneMouseEvent * event) override virtual
Reimplemented in TechDrawGui::QGIProjGroup, and TechDrawGui::QGILeaderLine.
References signalSelectPoint.
Referenced by TechDrawGui::QGIPrimPath::mousePressEvent().
mouseReleaseEvent()
void QGIView::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override virtual
Reimplemented in TechDrawGui::QGIViewDimension, TechDrawGui::QGIViewCollection, TechDrawGui::QGIProjGroup, and TechDrawGui::QGILeaderLine.
References TechDrawGui::Rez::appX(), getViewObject(), getY(), getYInClip(), isInnerView(), m_locked, and TechDraw::DrawView::setPosition().
Referenced by TechDrawGui::QGIProjGroup::mouseReleaseEvent(), and TechDrawGui::QGIViewCollection::mouseReleaseEvent().
onSourceChange
void QGIView::onSourceChange (TechDraw::DrawView * newParent) virtual slot
Referenced by TechDrawGui::ViewProviderLeader::updateData().
paint()
void QGIView::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override virtual
Reimplemented in TechDrawGui::QGIWeldSymbol, TechDrawGui::QGIViewPart, TechDrawGui::QGIViewDimension, TechDrawGui::QGIViewBalloon, TechDrawGui::QGIRichAnno, and TechDrawGui::QGILeaderLine.
Referenced by TechDrawGui::QGILeaderLine::paint(), TechDrawGui::QGIRichAnno::paint(), TechDrawGui::QGIViewBalloon::paint(), TechDrawGui::QGIViewPart::paint(), and TechDrawGui::QGIWeldSymbol::paint().
removeChild()
void QGIView::removeChild (QGIView * child) virtual
Referenced by TechDrawGui::QGVPage::removeQViewFromScene().
rotateView()
void QGIView::rotateView (void) virtual
Reimplemented in TechDrawGui::QGIViewSymbol, TechDrawGui::QGIViewPart, TechDrawGui::QGIViewImage, TechDrawGui::QGIViewAnnotation, and TechDrawGui::QGIProjGroup.
References boundingRect(), App::PropertyQuantity::getValue(), getViewObject(), TechDraw::DrawView::Rotation, and draftutils.translate::translate().
Referenced by updateView().
setGroupSelection()
void QGIView::setGroupSelection (bool b) virtual
Reimplemented in TechDrawGui::QGIViewDimension, and TechDrawGui::QGIViewBalloon.
Referenced by TechDrawGui::MDIViewPage::clearSceneSelection().
setLocked()
void TechDrawGui::QGIView::setLocked (bool b)
setPosition()
void QGIView::setPosition (qreal x, qreal y)
Methods to ensure that Y-Coordinates are orientated correctly.
References TechDraw::DrawUtil::fpCompare(), getYInClip(), and isInnerView().
Referenced by draw(), and TechDrawGui::QGIViewClip::drawClip().
setSettingColor()
virtual void TechDrawGui::QGIView::setSettingColor (QColor c) virtual
setViewFeature()
void QGIView::setViewFeature (TechDraw::DrawView * obj)
References viewName, and viewObj.
Referenced by TechDrawGui::QGVPage::addWeldSymbol(), TechDrawGui::QGIRichAnno::QGIRichAnno(), TechDrawGui::QGILeaderLine::setLeaderFeature(), TechDrawGui::QGIViewAnnotation::setViewAnnoFeature(), TechDrawGui::QGIViewSpreadsheet::setViewFeature(), TechDrawGui::QGIViewImage::setViewImageFeature(), TechDrawGui::QGIViewBalloon::setViewPartFeature(), TechDrawGui::QGIViewDimension::setViewPartFeature(), TechDrawGui::QGIViewPart::setViewPartFeature(), and TechDrawGui::QGIViewSymbol::setViewSymbolFeature().
toggleCache()
void QGIView::toggleCache (bool state) virtual
Reimplemented in TechDrawGui::QGIViewPart.
type()
int TechDrawGui::QGIView::type (void) const override
Referenced by TechDrawGui::QGVPage::removeQViewByName().
updateView()
void QGIView::updateView (bool update = false) virtual
Reimplemented in TechDrawGui::QGIWeldSymbol, TechDrawGui::QGIViewSymbol, TechDrawGui::QGIViewSection, TechDrawGui::QGIViewPart, TechDrawGui::QGIViewImage, TechDrawGui::QGIViewDimension, TechDrawGui::QGIViewCollection, TechDrawGui::QGIViewClip, TechDrawGui::QGIViewBalloon, TechDrawGui::QGIViewAnnotation, TechDrawGui::QGIRichAnno, TechDrawGui::QGIProjGroup, and TechDrawGui::QGILeaderLine.
References draw(), TechDraw::DrawUtil::fpCompare(), App::PropertyQuantity::getValue(), getViewObject(), TechDraw::DrawView::isLocked(), rotateView(), and TechDraw::DrawView::Rotation.
Referenced by TechDrawGui::MDIViewPage::clearSceneSelection(), TechDrawGui::ViewProviderBalloon::onChanged(), TechDrawGui::ViewProviderDimension::onChanged(), TechDrawGui::ViewProviderLeader::onChanged(), TechDrawGui::ViewProviderRichAnno::onChanged(), TechDrawGui::ViewProviderWeld::onChanged(), TechDrawGui::ViewProviderImage::onChanged(), TechDrawGui::ViewProviderViewPart::onChanged(), TechDrawGui::ViewProviderDrawingView::onChanged(), TechDrawGui::ViewProviderDrawingView::onGuiRepaint(), TechDrawGui::QGVPage::refreshViews(), TechDrawGui::ViewProviderAnnotation::updateData(), TechDrawGui::ViewProviderDrawingView::updateData(), TechDrawGui::ViewProviderGeomHatch::updateGraphic(), TechDrawGui::ViewProviderViewSection::updateGraphic(), TechDrawGui::QGIViewAnnotation::updateView(), TechDrawGui::QGIViewClip::updateView(), TechDrawGui::QGIViewCollection::updateView(), TechDrawGui::QGIViewImage::updateView(), TechDrawGui::QGIViewPart::updateView(), TechDrawGui::QGIViewSection::updateView(), and TechDrawGui::QGIViewSymbol::updateView().
Member Data Documentation
alignHash
QHash<QString, QGraphicsItem*> TechDrawGui::QGIView::alignHash protected
Referenced by alignTo(), and itemChange().
DefaultFontSizeInMM
const double QGIView::DefaultFontSizeInMM = 5.0 static
m_border
QGCustomBorder* TechDrawGui::QGIView::m_border protected
Referenced by boundingRect(), drawBorder(), and QGIView().
m_brush
QBrush TechDrawGui::QGIView::m_brush protected
m_caption
QGICaption* TechDrawGui::QGIView::m_caption protected
Referenced by drawCaption(), and QGIView().
m_colCurrent
QColor TechDrawGui::QGIView::m_colCurrent protected
Referenced by drawBorder(), drawCaption(), hoverEnterEvent(), TechDrawGui::QGIWeldSymbol::hoverEnterEvent(), hoverLeaveEvent(), TechDrawGui::QGIWeldSymbol::hoverLeaveEvent(), itemChange(), QGIView(), TechDrawGui::QGIWeldSymbol::QGIWeldSymbol(), TechDrawGui::QGIWeldSymbol::setPrettyNormal(), TechDrawGui::QGIWeldSymbol::setPrettyPre(), and TechDrawGui::QGIWeldSymbol::setPrettySel().
m_colNormal
QColor TechDrawGui::QGIView::m_colNormal protected
Referenced by TechDrawGui::QGILeaderLine::getNormalColor(), TechDrawGui::QGIViewBalloon::getNormalColor(), TechDrawGui::QGIWeldSymbol::hoverLeaveEvent(), TechDrawGui::QGIWeldSymbol::prefNormalColor(), TechDrawGui::QGIViewDimension::prefNormalColor(), and TechDrawGui::QGIWeldSymbol::setPrettyNormal().
m_colPre
QColor TechDrawGui::QGIView::m_colPre protected
m_colSel
QColor TechDrawGui::QGIView::m_colSel protected
m_colSetting
QColor TechDrawGui::QGIView::m_colSetting protected
Referenced by TechDrawGui::QGIWeldSymbol::QGIWeldSymbol().
m_decorPen
QPen TechDrawGui::QGIView::m_decorPen protected
Referenced by drawBorder(), and QGIView().
m_font
QFont TechDrawGui::QGIView::m_font protected
Referenced by drawBorder(), drawCaption(), TechDrawGui::QGIViewPart::drawHighlight(), TechDrawGui::QGIViewPart::drawSectionLine(), and QGIView().
m_innerView
bool TechDrawGui::QGIView::m_innerView protected
m_label
QGCustomLabel* TechDrawGui::QGIView::m_label protected
Referenced by drawBorder(), drawCaption(), and QGIView().
m_lock
QGCustomImage* TechDrawGui::QGIView::m_lock protected
Referenced by drawBorder(), and QGIView().
m_locked
bool TechDrawGui::QGIView::m_locked protected
Referenced by itemChange(), and mouseReleaseEvent().
m_lockHeight
double TechDrawGui::QGIView::m_lockHeight protected
Referenced by drawBorder(), and QGIView().
m_lockWidth
double TechDrawGui::QGIView::m_lockWidth protected
Referenced by QGIView().
m_pen
QPen TechDrawGui::QGIView::m_pen protected
Referenced by QGIView().
signalSelectPoint
boost::signals2::signal<void (QGIView*, QPointF)> TechDrawGui::QGIView::signalSelectPoint
Referenced by mousePressEvent(), and ~QGIView().
viewName
std::string TechDrawGui::QGIView::viewName protected
Referenced by getViewName(), getViewNameAsString(), and setViewFeature().
viewObj
TechDraw::DrawView* TechDrawGui::QGIView::viewObj protected
Referenced by getViewObject(), and setViewFeature().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGIView.h
Sources/FreeCAD/src/Mod/TechDraw/Gui/QGIView.cpp