FreeCAD: SMESH::Controls::LinearOrQuadratic Class Reference
SMESH::Controls::LinearOrQuadratic Class Reference
#include <SMESH_ControlsDef.hxx>
Public Member Functions
virtual SMDSAbs_ElementType GetType () const
virtual bool IsSatisfy (long theElementId)
LinearOrQuadratic ()
virtual void SetMesh (const SMDS_Mesh *theMesh)
void SetType (SMDSAbs_ElementType theType)
virtual SMDSAbs_ElementType GetType () const =0
virtual bool IsSatisfy (long theElementId)=0
Public Member Functions inherited from SMESH::Controls::Functor
virtual SMDSAbs_ElementType GetType () const =0
virtual void SetMesh (const SMDS_Mesh *theMesh)=0
virtual ~Functor ()
Constructor & Destructor Documentation
LinearOrQuadratic()
LinearOrQuadratic::LinearOrQuadratic ()
References SMESH::Controls::FreeEdges::myMesh.
Member Function Documentation
GetType()
SMDSAbs_ElementType LinearOrQuadratic::GetType () const virtual
Implements SMESH::Controls::Predicate.
IsSatisfy()
bool LinearOrQuadratic::IsSatisfy (long theElementId) virtual
Implements SMESH::Controls::Predicate.
References SMDS_Mesh::FindElement(), SMDS_MeshElement::GetType(), SMDS_MeshElement::IsQuadratic(), and SMESH::Controls::FreeEdges::myMesh.
SetMesh()
void LinearOrQuadratic::SetMesh (const SMDS_Mesh * theMesh) virtual
Implements SMESH::Controls::Functor.
References SMESH::Controls::FreeEdges::myMesh.
SetType()
void LinearOrQuadratic::SetType (SMDSAbs_ElementType theType)
The documentation for this class was generated from the following files:
FreeCAD/src/3rdParty/salomesmesh/inc/SMESH_ControlsDef.hxx
FreeCAD/src/3rdParty/salomesmesh/src/Controls/SMESH_Controls.cpp