FreeCAD: Gui::NS::PanState Class Reference
Gui::NS::PanState Class Reference
Public Types
typedef sc::custom_reaction< NS::Event > reactions
Public Member Functions
PanState (my_context ctx)
sc::result react (const NS::Event &ev)
virtual ~PanState ()
Member Typedef Documentation
reactions
typedef sc::custom_reaction<NS::Event> Gui::NS::PanState::reactions
Constructor & Destructor Documentation
PanState()
Gui::NS::PanState::PanState (my_context ctx)
References Base::Console(), Base::ConsoleSingleton::Log(), and Gui::NavigationStyle::PANNING.
~PanState()
virtual Gui::NS::PanState::~PanState () virtual
Member Function Documentation
react()
sc::result Gui::NS::PanState::react (const NS::Event & ev)
References Gui::NS::Event::flags, Gui::NS::Event::inventor_event, Gui::NS::Event::isLocation2Event(), Gui::NS::Event::isMouseButtonEvent(), and Gui::NS::Event::mbstate().
The documentation for this class was generated from the following file:
Sources/FreeCAD/src/Gui/GestureNavigationStyle.cpp