FreeCAD: Gui::PropertyEditor::PropertyModel Class Reference
Gui::PropertyEditor::PropertyModel Class Reference
#include <PropertyModel.h>
Public Types
typedef std::vector< std::pair< std::string, std::vector< App::Property * > > > PropertyList
Public Member Functions
void appendProperty (const App::Property &)
QModelIndex buddy (const QModelIndex &index) const
void buildUp (const PropertyList &props)
int columnCount (const QModelIndex &parent=QModelIndex()) const
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Qt::ItemFlags flags (const QModelIndex &index) const
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
QModelIndex parent (const QModelIndex &index) const
QModelIndex propertyIndexFromPath (const QStringList &) const
PropertyModel (QObject *parent)
QStringList propertyPathFromIndex (const QModelIndex &) const
void removeProperty (const App::Property &)
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
int rowCount (const QModelIndex &parent=QModelIndex()) const
bool setData (const QModelIndex &idx, const QVariant &value, int role)
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
void updateProperty (const App::Property &)
virtual ~PropertyModel ()
Member Typedef Documentation
PropertyList
typedef std::vector< std::pair< std::string, std::vector<App::Property*> > > Gui::PropertyEditor::PropertyModel::PropertyList
Constructor & Destructor Documentation
PropertyModel()
PropertyModel::PropertyModel (QObject * parent)
References femsolver.elmer.equations.elasticity::create().
~PropertyModel()
PropertyModel::~PropertyModel () virtual
Member Function Documentation
appendProperty()
void PropertyModel::appendProperty (const App::Property & prop)
References Gui::PropertyEditor::PropertyItem::appendChild(), Gui::PropertyEditor::PropertyItem::child(), Gui::PropertyEditor::PropertyItem::childCount(), femsolver.elmer.equations.elasticity::create(), Gui::PropertyEditor::PropertyItemFactory::createPropertyItem(), data(), App::Property::getEditorName(), App::Property::getGroup(), App::Property::getName(), index(), Gui::PropertyEditor::PropertyItem::insertChild(), Gui::PropertyEditor::PropertyItemFactory::instance(), Gui::PropertyEditor::PropertyItem::isSeparator(), Gui::PropertyEditor::PropertyItem::propertyName(), draftutils.translate::QT_TRANSLATE_NOOP, Gui::PropertyEditor::PropertyItem::setParent(), Gui::PropertyEditor::PropertyItem::setPropertyData(), and Gui::PropertyView::showAll().
buddy()
QModelIndex PropertyModel::buddy (const QModelIndex & index) const
References index().
Referenced by Gui::PropertyEditor::PropertyEditor::contextMenuEvent().
buildUp()
void PropertyModel::buildUp (const PropertyList & props)
References Gui::PropertyEditor::PropertyItem::appendChild(), femsolver.elmer.equations.elasticity::create(), Gui::PropertyEditor::PropertyItemFactory::createPropertyItem(), App::Property::getEditorName(), App::Property::getGroup(), App::Property::getName(), Gui::PropertyEditor::PropertyItemFactory::instance(), draftutils.translate::QT_TRANSLATE_NOOP, Gui::PropertyEditor::PropertyItem::reset(), Gui::PropertyEditor::PropertyItem::setLinked(), Gui::PropertyEditor::PropertyItem::setParent(), Gui::PropertyEditor::PropertyItem::setPropertyData(), and Gui::PropertyView::showAll().
Referenced by Gui::PropertyEditor::PropertyEditor::buildUp(), and Gui::PropertyEditor::PropertyEditor::commitData().
columnCount()
int PropertyModel::columnCount (const QModelIndex & parent = QModelIndex()) const
References Gui::PropertyEditor::PropertyItem::columnCount(), and parent().
data()
QVariant PropertyModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
References Gui::PropertyEditor::PropertyItem::data().
Referenced by Mod.Show.mTempoVis.TempoVis::activateWorkbench(), appendProperty(), Mod.Show.SceneDetail.SceneDetail::apply_data(), importIFClegacy.IfcSchema::capitalize(), Mod.Show.mTempoVis.TempoVis::forget(), Mod.Show.mTempoVis.TempoVis::forgetDetail(), Mod.Show.mTempoVis.TempoVis::has(), ArchSchedule.CommandArchSchedule::IsActive(), importIFClegacy.IfcSchema::readEntities(), importIFClegacy.IfcSchema::readTypes(), Mod.Show.mTempoVis.TempoVis::restore(), Mod.Show.mTempoVis.TempoVis::save(), Mod.Show.mTempoVis.TempoVis::stored_val(), FeaturePython.ViewProviderOctahedron::updateData(), and Dice3DS.dom3ds.UndefinedChunk::write().
flags()
Qt::ItemFlags PropertyModel::flags (const QModelIndex & index) const
References Gui::PropertyEditor::PropertyItem::flags().
headerData()
QVariant PropertyModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
index()
QModelIndex PropertyModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const
References Gui::PropertyEditor::PropertyItem::child(), and parent().
Referenced by Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::addSegment(), Dice3DS.dom3ds.FileLikeBuffer::advance(), appendProperty(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::begin(), buddy(), Spreadsheet_legacy.MathParser::getValue(), Spreadsheet_legacy.MathParser::hasNext(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::interval(), PathScripts.PathJobDlg.JobCreate::item1ValueChanged(), Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::length(), Spreadsheet_legacy.MathParser::parseAddition(), Spreadsheet_legacy.MathParser::parseMultiplication(), Spreadsheet_legacy.MathParser::parseNegative(), Spreadsheet_legacy.MathParser::parseNumber(), Spreadsheet_legacy.MathParser::parseParenthesis(), Spreadsheet_legacy.MathParser::parseVariable(), Spreadsheet_legacy.MathParser::peek(), propertyIndexFromPath(), Dice3DS.dom3ds.FileLikeBuffer::read(), Dice3DS.dom3ds.FileLikeBuffer::read_fbuf(), Dice3DS.dom3ds.FileLikeBuffer::read_rest(), Dice3DS.dom3ds.FileLikeBuffer::read_to_nul(), Dice3DS.dom3ds.FileLikeBuffer::room_for_chunks(), Dice3DS.dom3ds.FileLikeBuffer::seek(), PathScripts.PathJobDlg.JobCreate::setupColumnEditor(), Spreadsheet_legacy.MathParser::skipWhitespace(), Dice3DS.dom3ds.FileLikeBuffer::tell(), Gui::PropertyEditor::PropertyEditor::updateEditorMode(), updateProperty(), automotive_design.index_expression::wr1(), and automotive_design.index_expression::wr2().
parent()
QModelIndex PropertyModel::parent (const QModelIndex & index) const
References Gui::PropertyEditor::PropertyItem::parent(), and Gui::PropertyEditor::PropertyItem::row().
Referenced by PathScripts.PathSimulatorGui.CAMSimTaskUi::accept(), columnCount(), Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium(), index(), propertyIndexFromPath(), PathScripts.PathSimulatorGui.CAMSimTaskUi::reject(), removeRows(), rowCount(), and PathScripts.PathOpGui.TaskPanelPage::setParent().
propertyIndexFromPath()
QModelIndex PropertyModel::propertyIndexFromPath (const QStringList & path) const
References index(), parent(), Gui::PropertyEditor::PropertyItem::propertyName(), and rowCount().
Referenced by Gui::PropertyEditor::PropertyEditor::buildUp().
propertyPathFromIndex()
QStringList PropertyModel::propertyPathFromIndex (const QModelIndex & index) const
References Gui::PropertyEditor::PropertyItem::isSeparator(), Gui::PropertyEditor::PropertyItem::parent(), and Gui::PropertyEditor::PropertyItem::propertyName().
Referenced by Gui::PropertyEditor::PropertyEditor::buildUp().
removeProperty()
void PropertyModel::removeProperty (const App::Property & prop)
References Gui::PropertyEditor::PropertyItem::child(), Gui::PropertyEditor::PropertyItem::childCount(), Gui::PropertyEditor::PropertyItem::hasProperty(), and Gui::PropertyEditor::PropertyItem::removeProperty().
Referenced by Gui::PropertyEditor::PropertyEditor::removeProperty().
removeRows()
bool PropertyModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex())
References parent(), and Gui::PropertyEditor::PropertyItem::removeChildren().
rowCount()
int PropertyModel::rowCount (const QModelIndex & parent = QModelIndex()) const
References Gui::PropertyEditor::PropertyItem::childCount(), and parent().
Referenced by propertyIndexFromPath(), Gui::PropertyEditor::PropertyEditor::reset(), and Gui::PropertyEditor::PropertyEditor::updateEditorMode().
setData()
bool PropertyModel::setData (const QModelIndex & idx, const QVariant & value, int role)
References Gui::PropertyEditor::PropertyItem::data(), and Gui::PropertyEditor::PropertyItem::setData().
setHeaderData()
bool PropertyModel::setHeaderData (int section, Qt::Orientation orientation, const QVariant & value, int role = Qt::EditRole)
updateProperty()
void PropertyModel::updateProperty (const App::Property & prop)
References Gui::PropertyEditor::PropertyItem::assignProperty(), Gui::PropertyEditor::PropertyItem::child(), Gui::PropertyEditor::PropertyItem::childCount(), Gui::PropertyEditor::PropertyItem::hasProperty(), index(), and Gui::PropertyEditor::PropertyItem::updateData().
Referenced by Gui::PropertyEditor::PropertyEditor::updateProperty().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/propertyeditor/PropertyModel.h
Sources/FreeCAD/src/Gui/propertyeditor/PropertyModel.cpp