FreeCAD: PartDesignGui::DlgActiveBody Class Reference
PartDesignGui::DlgActiveBody Class Reference
Dialog box to ask user to pick a Part Design body to make active or make a new one.
#include <DlgActiveBody.h>
Public Member Functions
void accept () override
DlgActiveBody (QWidget *parent, App::Document *&doc, const QString &infoText=QString())
PartDesign::Body * getActiveBody () const
~DlgActiveBody ()
Detailed Description
Dialog box to ask user to pick a Part Design body to make active or make a new one.
Constructor & Destructor Documentation
DlgActiveBody()
DlgActiveBody::DlgActiveBody (QWidget * parent, App::Document *& doc, const QString & infoText = QString())
References accept(), draftgeoutils.intersections::connect(), PartDesign::Body::findBodyOf(), Base::Persistence::getClassTypeId(), draftutils.gui_utils::getSelection, and Gui::Selection().
~DlgActiveBody()
DlgActiveBody::~DlgActiveBody ()
Member Function Documentation
accept()
void DlgActiveBody::accept (void) override
References App::Application::closeActiveTransaction(), App::GetApplication(), PartDesignGui::makeBody(), PartDesignGui::makeBodyActive(), draftutils.translate::QT_TRANSLATE_NOOP, and App::Application::setActiveTransaction().
Referenced by femexamples.examplesgui.FemExamples::clicked(), DlgActiveBody(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), and PathScripts.PathToolBitLibraryGui.ToolBitLibrary::toolEdit().
getActiveBody()
PartDesign::Body * PartDesignGui::DlgActiveBody::getActiveBody () const
Referenced by PartDesignGui::getBody().
The documentation for this class was generated from the following files:
FreeCAD/src/Mod/PartDesign/Gui/DlgActiveBody.h
FreeCAD/src/Mod/PartDesign/Gui/DlgActiveBody.cpp