FreeCAD: ArchWindow Namespace Reference
ArchWindow Namespace Reference
The Window object and tools.
Functions
def makeWindow (baseobj=None, width=None, height=None, parts=None, name=None)
def recolorize (attr)
Variables
list AllowedHosts = ["Wall","Structure","Roof"]
list WindowOpeningModes
list WindowPartTypes = ["Frame","Solid panel","Glass panel","Louvre"]
WindowPresets = ArchWindowPresets.WindowPresets
Detailed Description
The Window object and tools.
This module provides tools to build Window objects. Windows are Arch objects obtained by extruding a series of wires, and that can be inserted into other Arch objects, by defining a volume that gets subtracted from them.
Function Documentation
makeWindow()
def ArchWindow.makeWindow (baseobj = None, width = None, height = None, parts = None, name = None)
makeWindow(baseobj,[width,height,parts,name]): creates a window based on the
given base 2D object (sketch or draft).
Referenced by ArchWindowPresets.makeWindowPreset().
recolorize()
def ArchWindow.recolorize (attr)
Recolorizes an object or a [documentname,objectname] list
This basically calls the Proxy.colorize(obj) methods of objects that
have one.
References WorkingPlane.getPlacementFromFace(), draftguitools.gui_tool_utils.getPoint, DraftVecUtils.isNull(), ArchComponent.Component.onChanged(), ArchComponent.Component.onDocumentRestored(), DraftVecUtils.project(), draftutils.translate.QT_TRANSLATE_NOOP, DraftVecUtils.rotate(), DraftVecUtils.scale(), and DraftVecUtils.scaleTo().
Variable Documentation
AllowedHosts
list ArchWindow.AllowedHosts = ["Wall","Structure","Roof"]
WindowOpeningModes
list ArchWindow.WindowOpeningModes
Initial value:
 =  ["None","Arc 90","Arc 90 inv","Arc 45","Arc 45 inv","Arc 180",
                       "Arc 180 inv","Triangle","Triangle inv","Sliding","Sliding inv"]
WindowPartTypes
list ArchWindow.WindowPartTypes = ["Frame","Solid panel","Glass panel","Louvre"]
WindowPresets
ArchWindow.WindowPresets = ArchWindowPresets.WindowPresets