FreeCAD: Gui::PythonStdout Class Reference
Gui::PythonStdout Class Reference
Python class for redirection of stdout to FreeCAD's Python console window.
#include <PythonConsolePy.h>
Public Member Functions
Py::Object flush (const Py::Tuple &)
Py::Object getattr (const char *name)
Py::Object isatty ()
PythonStdout (PythonConsole *pc)
Py::Object repr ()
Py::Object write (const Py::Tuple &)
~PythonStdout ()
Static Public Member Functions
static void init_type (void)
Detailed Description
Python class for redirection of stdout to FreeCAD's Python console window.
This allows to show all Python messages in the same window where the commands are performed.
See also
PythonStderr
PythonConsole
Author
Werner Mayer
Constructor & Destructor Documentation
PythonStdout()
PythonStdout::PythonStdout (PythonConsole * pc)
~PythonStdout()
PythonStdout::~PythonStdout ()
Member Function Documentation
flush()
Py::Object PythonStdout::flush (const Py::Tuple &)
Referenced by init_type().
getattr()
Py::Object PythonStdout::getattr (const char * name)
init_type()
void PythonStdout::init_type (void) static
References flush(), isatty(), and write().
Referenced by Gui::Application::Application().
isatty()
Py::Object PythonStdout::isatty ()
Referenced by init_type().
repr()
Py::Object PythonStdout::repr ()
write()
Py::Object PythonStdout::write (const Py::Tuple & args)
Referenced by init_type(), and gzip_utf8.GzipFile::seek().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/Gui/PythonConsolePy.h
Sources/FreeCAD/src/Gui/PythonConsolePy.cpp