FreeCAD: SurfaceGui::Ui_GeomFillSurface Class Reference
SurfaceGui::Ui_GeomFillSurface Class Reference
#include <ui_TaskGeomFillSurface.h>
Public Member Functions
void retranslateUi (QWidget *SurfaceGui__GeomFillSurface)
void setupUi (QWidget *SurfaceGui__GeomFillSurface)
Public Attributes
QToolButton * buttonEdgeAdd
QToolButton * buttonEdgeRemove
QRadioButton * fillType_coons
QRadioButton * fillType_curved
QRadioButton * fillType_stretch
QGroupBox * fillTypes
QGridLayout * gridLayout
QGridLayout * gridLayout1
QHBoxLayout * horizontalLayout
QListWidget * listWidget
Member Function Documentation
retranslateUi()
void SurfaceGui::Ui_GeomFillSurface::retranslateUi (QWidget * SurfaceGui__GeomFillSurface)
References buttonEdgeAdd, buttonEdgeRemove, fillType_coons, fillType_curved, fillType_stretch, fillTypes, and draftguitools.gui_setstyle::translate.
Referenced by ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), SurfaceGui::GeomFillSurface::changeEvent(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), setupUi(), DraftGui.DraftToolBar::taskUi(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), and DraftGui.FacebinderTaskPanel::update().
setupUi()
void SurfaceGui::Ui_GeomFillSurface::setupUi (QWidget * SurfaceGui__GeomFillSurface)
References buttonEdgeAdd, buttonEdgeRemove, fillType_coons, fillType_curved, fillType_stretch, fillTypes, gridLayout, gridLayout1, horizontalLayout, listWidget, and retranslateUi().
Referenced by SurfaceGui::GeomFillSurface::GeomFillSurface().
Member Data Documentation
buttonEdgeAdd
QToolButton* SurfaceGui::Ui_GeomFillSurface::buttonEdgeAdd
Referenced by retranslateUi(), and setupUi().
buttonEdgeRemove
QToolButton* SurfaceGui::Ui_GeomFillSurface::buttonEdgeRemove
Referenced by retranslateUi(), and setupUi().
fillType_coons
QRadioButton* SurfaceGui::Ui_GeomFillSurface::fillType_coons
Referenced by retranslateUi(), SurfaceGui::GeomFillSurface::setEditedObject(), and setupUi().
fillType_curved
QRadioButton* SurfaceGui::Ui_GeomFillSurface::fillType_curved
Referenced by retranslateUi(), SurfaceGui::GeomFillSurface::setEditedObject(), and setupUi().
fillType_stretch
QRadioButton* SurfaceGui::Ui_GeomFillSurface::fillType_stretch
Referenced by retranslateUi(), SurfaceGui::GeomFillSurface::setEditedObject(), and setupUi().
fillTypes
QGroupBox* SurfaceGui::Ui_GeomFillSurface::fillTypes
Referenced by retranslateUi(), and setupUi().
gridLayout
QGridLayout* SurfaceGui::Ui_GeomFillSurface::gridLayout
Referenced by setupUi().
gridLayout1
QGridLayout* SurfaceGui::Ui_GeomFillSurface::gridLayout1
Referenced by setupUi().
horizontalLayout
QHBoxLayout* SurfaceGui::Ui_GeomFillSurface::horizontalLayout
Referenced by setupUi().
listWidget
QListWidget* SurfaceGui::Ui_GeomFillSurface::listWidget
Referenced by SurfaceGui::GeomFillSurface::accept(), SurfaceGui::GeomFillSurface::flipOrientation(), SurfaceGui::GeomFillSurface::GeomFillSurface(), SurfaceGui::GeomFillSurface::onSelectionChanged(), SurfaceGui::GeomFillSurface::setEditedObject(), and setupUi().
The documentation for this class was generated from the following file:
FreeCAD/src/Mod/Surface/Gui/ui_TaskGeomFillSurface.h