FreeCAD: zipios::InflateInputStreambuf Class Reference
zipios::InflateInputStreambuf Class Reference
InflateInputStreambuf is an input stream filter, that inflates the input from the attached input stream.
#include <inflateinputstreambuf.h>
Public Member Functions
InflateInputStreambuf (streambuf *inbuf, int s_pos=-1, bool del_inbuf=false)
InflateInputStreambuf constructor.
bool reset (int stream_position=-1)
Resets the zlib stream and purges input and output buffers.
virtual ~InflateInputStreambuf ()
Public Member Functions inherited from zipios::FilterInputStreambuf
FilterInputStreambuf (streambuf *inbuf, bool del_inbuf=false)
Constructor.
virtual ~FilterInputStreambuf ()
Destructor.
Protected Member Functions
virtual int underflow ()
Detailed Description
InflateInputStreambuf is an input stream filter, that inflates the input from the attached input stream.
Deflation/Inflation is a compression/decompression method used in gzip and zip. The zlib library is used to perform the actual inflation, this class only wraps the functionality in an input stream filter.
Constructor & Destructor Documentation
InflateInputStreambuf()
zipios::InflateInputStreambuf::InflateInputStreambuf (streambuf * inbuf, int s_pos = -1, bool del_inbuf = false) explicit
InflateInputStreambuf constructor.
Parameters
inbuf the streambuf to use for input.
s_pos a position to reset the inbuf to before reading. Specify -1 to read from the current position.
del_inbuf if true is specified inbuf will be deleted, when the InflateInputStreambuf is destructed.
References reset().
~InflateInputStreambuf()
zipios::InflateInputStreambuf::~InflateInputStreambuf () virtual
Member Function Documentation
reset()
bool zipios::InflateInputStreambuf::reset (int stream_position = -1)
Resets the zlib stream and purges input and output buffers.
repositions the input streambuf at stream_position.
Parameters
stream_position a position to reset the inbuf to before reading. Specify -1 to read from the current position.
Referenced by zipios::ZipInputStreambuf::getNextEntry(), InflateInputStreambuf(), and draftguitools.gui_trackers.gridTracker::set().
underflow()
int zipios::InflateInputStreambuf::underflow () protected virtual
Reimplemented in zipios::ZipInputStreambuf.
References zipios::OutputStringStream::str().
Referenced by zipios::ZipInputStreambuf::underflow().
The documentation for this class was generated from the following files:
Sources/FreeCAD/src/zipios++/inflateinputstreambuf.h
Sources/FreeCAD/src/zipios++/inflateinputstreambuf.cpp